### ISSUE TITLE
Unable to install deviceconsole

### ISSUE THREAD

**Issue by ShaikNagababu** [appium/appium#10007]
Unable to install deviceconsole

I'm unable to install deviceconsole,getting "Last login: Wed Jan 17 14:17:26 on ttys000
E1459T1D:~ root# npm install -g deviceconsole

> deviceconsole@1.0.1 install /usr/local/lib/node_modules/deviceconsole
> make

Making deviceconsole...
error: unable to open output file
      '/usr/local/lib/node_modules/deviceconsole/main-965f09.o':
      'Permission denied'
1 error generated.
make: *** [all] Error 1
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! deviceconsole@1.0.1 install: `make`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the deviceconsole@1.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/root/.npm/_logs/2018-01-17T08_51_32_632Z-debug.log
E1459T1D:~ root# 
" when running command rpm install -g deviceconsole.
 I'm attaching the log file please help me.

## Environment

* Appium version :1.7
* Desktop OS/version used to run Appium: Mac 10.13.2
* Node.js version (unless using Appium.app|exe): 8.9.4
* Mobile platform/version under test: iPhone 6s os: 11.2.1
* Real device or emulator/simulator: Real device
[2018-01-17T08_51_32_632Z-debug.log](https://github.com/appium/appium/files/1638293/2018-01-17T08_51_32_632Z-debug.log)

**Comment by mykola-mokhnach** [comment]
Please report the issue to npm. closed as non Appium-related

**Comment by imurchie** [comment]
@ShaikNagababu Make sure you have write permissions to `/usr/local/lib/node_modules`.
