### ISSUE TITLE
autoGrantPermissions is not working for Chrome on Android

### ISSUE THREAD

**Issue by sajidcosmo** [appium/appium#10008]
## The problem

autoGrantPermissions is not working for Chrome on Android.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: MAC OS X 10.12.6
* Node.js version (unless using Appium.app|exe): 9.3.0
* Mobile platform/version under test: Android 6.0.1
* Real device or emulator/simulator: OPPO A57 Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

I am trying to test a video conferencing website using appium on Chrome on Android. The site requires permission to use microphone and camera. I am providing autoGrantPermissions = true in my capabilities. It simply is not working for me.

## Additional Digging:

I digged into appium-adb and found out that if I use await this.grantPermissions(); after setupNewChromedriver in startChromeSession in driver.js then I can be able to see all the permissions granted to chrome but to no effect in the test. To my understanding the permissions should be granted somewhere in the middle of setupNewChromedriver function to make it for this case.

**Comment by mykola-mokhnach** [comment]
`autoGrantPermissions` capability grants Android system permissions for a newly installed application on global level. This won't work for Chrome. Check if mobile driver for chrome itself provides any internal capabilities to handle such requests, since this behaviour cannot be controlled form Appium directly

**Comment by sajidcosmo** [comment]
What I have seen with autoGrantPermissions, appium runs adb commands to get the permissions, that is totally out of scope of chrome driver. Is there any capability that stops appium resetting the permissions of chrome before launching it?
