### ISSUE TITLE
Cannot start inspector session on Android Emulator

### ISSUE THREAD

**Issue by MarceloGOliveira** [appium/appium#10003]
## The problem

I am using the latest Appium Desktop version (v1.7.2) and after I start the server (On 0.0.0.0:4723) nad I get an error after trying to get an Inspector session:

[MJSONWP] Encountered internal error running command: TypeError: Cannot read property 'startsWith' of undefined

## Environment

* Appium version: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android 8.1
* Real device or emulator/simulator: Android API 27 x86
* Appium CLI or Appium.app|exe: 1.3.1

## Details

I am new to Appium, and followed the starting guides, and after installing Android SDK and configuring the environment variables as instructed (JDK was already installed and setup according the guidlines), I run the Appium Desktop and started the server. Just to check if I could create a session with an android emulator and run my application, I gost this error.

## Link to Appium logs

https://gist.github.com/MarceloGOliveira/4d6ffff6fbcdde17a92e078a41213aea

## Code To Reproduce Issue [ Good To Have ]

I didn't run any test, I qas just trying to start a session via the Appium desktop

**Comment by mykola-mokhnach** [comment]
@dpgraham This might be also something for you

**Comment by mykola-mokhnach** [comment]
@MarceloGOliveira 

>  \Users\marcelo.oliveira\Downloads\pepe-installers\i.Pepe-4.1.0-(5399).apk

Are you sure the application path is correct? 

Also, can you try if this issue is reproducible with the recent beta version of Appium?

**Comment by mykola-mokhnach** [comment]
BTW, what is NodeJS version on the machine?

**Comment by MarceloGOliveira** [comment]
@mykola-mokhnach 
The application path is correct. Here is how it looks in the configuration JSON of the saved capability set:

{
  "platformName": "Android",
  "deviceName": "PepeEmulator",
  "app": "\\Users\\marcelo.oliveira\\Downloads\\pepe-installers\\i.Pepe-4.1.0-(5399).apk",
  "platformVersion": "8.1"
}

 I can move it to another directory (root, for example) and rename it, if you want.

NodeJs version given by the command node -v on cmd prompt is 6.9.1

Where do I get the appium beta version? Can't see it in the releases page:
 (https://github.com/appium/appium-desktop/releases)

**Comment by mykola-mokhnach** [comment]
yes, change the path to `c:\Users\marcelo.oliveira\Downloads\pepe-installers\i.Pepe-4.1.0-(5399).apk`. Otherwise Appium assumes the file might be located on smb server

**Comment by MarceloGOliveira** [comment]
How do I do that. If I try to edit it directly, it gives a JSON parse error:

![image](https://user-images.githubusercontent.com/23239215/35012309-8f48ee46-faf0-11e7-8547-a3496d22dc0b.png)

**Comment by mykola-mokhnach** [comment]
You must escape all backslashes: `\\`

**Comment by dpgraham** [comment]
@MarceloGOliveira You can also edit the capabilities on the left column
