### ISSUE TITLE
error: Could not determine Xcode version: Could not get Xcode version. /Library/Developer/Info.plist does not exist on disk.

### ISSUE THREAD

**Issue by TajinderSinghMarwaha** [appium/appium#10001]
## The problem

I am getting "error: Could not determine Xcode version: Could not get Xcode version. /Library/Developer/Info.plist does not exist on disk." on initiating run for native app.

## Environment
Xcode - 9.2
Appium - 1.7.2
OSX - 10.12.6
iPhone 6s Version 11.0.3

Appium:
https://gist.github.com/TajinderSinghMarwaha/b1b1e69ca3e34f4253b98714be7515a6

**Comment by imurchie** [comment]
Try running 
```
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
```

**Comment by mykola-mokhnach** [comment]
Don't like to use google: https://stackoverflow.com/questions/32724616/appium-error-could-not-get-xcode-version?

**Comment by TajinderSinghMarwaha** [comment]
@imurchie @mykola-mokhnach ,

I have tried this but no luck. Issue is still persist

**Comment by TajinderSinghMarwaha** [comment]
@imurchie ..

Error is resolved.. Thanks

**Comment by imurchie** [comment]
Excellent, @TajinderSinghMarwaha!

If it was not what was recommended that fixed it, would you mind mentioning what the fix was? That way other users with the problem can find the fix.
