### ISSUE TITLE
why find a element need more times by xcode9.2 rather than xcode8.3

### ISSUE THREAD

**Issue by KuKiSiNi77** [appium/appium#10004]
## The problem
FindElements Way
1. `List<MobileElement> elementBs =  elementA.findElementsByAccessibilityId("elementBName")`
2. `List<MobileElement> elementBs =  appiumDriver.findElementsByAccessibilityId("elementBName")`

a test case used many ways to find element list by the two ways. the used times by xcode9.2 more than xcode8.3 . by xcode8.3 just used 10 minutes , but need 30 minutes by the xcode9.2

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Desktop OS/version used to run Appium: 10.12.6
* Real device :10.3.2

## Details the 

```java

 AppiumServiceBuilder builder = new AppiumServiceBuilder();
 builder.usingPort(port);
 builder.withIPAddress("127.0.0.1");
 service = AppiumDriverLocalService.buildService(builder);
 File appDir = new File(System.getProperty("user.dir"), "/apps/");
 File app = new File(appDir, "rlterm3.app");
 DesiredCapabilities capabilities = new DesiredCapabilities();
 capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "");
 capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.3.0");
 capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "autotest");
 capabilities.setCapability(MobileCapabilityType.UDID, udid);
 capabilities.setCapability(IOSMobileCapabilityType.LAUNCH_TIMEOUT, 500000);
 capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.IOS_XCUI_TEST);
 capabilities.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
 capabilities.setCapability(MobileCapabilityType.NO_RESET, true);
 capabilities.setCapability("wdaLocalPort",wdaLocalPort);
 capabilities.setCapability("useNewWDA", true);
 capabilities.setCapability("newCommandTimeout", 21600);
 iosDriver = new IOSDriver<>(service.getUrl(), capabilities);
 iosDriver.manage().timeouts().implicitlyWait(6, TimeUnit.SECONDS);

```

**Comment by mykola-mokhnach** [comment]
Element search happens on WebDriverAgent side, and the search logic there is the same for all Xcode versions, which means that some stuff has been changed internally inside XCTest. I assume it's related to the fact of snapshots deprecation since Xcode9, but Apple engineers may tell you more details.
