### ISSUE TITLE
Unable to launch test app in iOS Physical device

### ISSUE THREAD

**Issue by SubaRajaram09** [appium/appium#10006]
The server is running

[Appium] Welcome to Appium v1.7.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/subarajaram/Desktop/ios_ipa/latest/Savvy_Dev.ipa","noReset":true,"bundleId":"au.com.commbank.savvy.test","xcodeConfigFile":"/Users/subarajaram/node_modules/WebDriverAgent-master/Configurations/appium.xcconfig","deviceName":"iPhone 7 Plus","agentPath":"/Users/subarajaram/node_modules/WebDriverAgent-master/WebDriverAgent.xcodeproj","bootstrapPath":"/Users/subarajaram/node_modules/WebDriverAgent-master","newCommandTimeout":180,"platformVersion":"11.1","automationName":"XCUITest","useNewWDA":true,"udid":"3df785473d472fbcdfcd11b9c572bb3498fa3f39","platformName":"iOS","autoAcceptAlerts":true},"requiredCapabilities":{},"capabilities":{"desiredCapabilities":{"app":"/Users/subarajaram/Desktop/ios_ipa/latest/Savvy_Dev.ipa","noReset":true,"bundleId":"au.com.commbank.savvy.test","xcodeConfigFile":"/Users/subarajaram/node_modules/WebDriverAgent-master/Configurations/appium.xcconfig","deviceName":"iPhone 7 Plus","agentPath":"/Users/subarajaram/node_modules/WebDr
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/subarajaram/Desktop/ios_ipa/latest/Savvy_Dev.ipa","noReset":true,"bundleId":"au.com.commbank.savvy.test","xcodeConfigFile":"/Users/subarajaram/node_modules/WebDriverAgent-master/Configurations/appium.xcconfig","deviceName":"iPhone 7 Plus","agentPath":"/Users/subarajaram/node_modules/WebDriverAgent-master/WebDriverAgent.xcodeproj","bootstrapPath":"/Users/subarajaram/node_modules/WebDriverAgent-master","newCommandTimeout":180,"platformVersion":"11.1","automationName":"XCUITest","useNewWDA":true,"udid":"3df785473d472fbcdfcd11b9c572bb3498fa3f39","platformName":"iOS","autoAcceptAlerts":true},{},{"desiredCapabilities":{"app":"/Users/subarajaram/Desktop/ios_ipa/latest/Savvy_Dev.ipa","noReset":true,"bundleId":"au.com.commbank.savvy.test","xcodeConfigFile":"/Users/subarajaram/node_modules/WebDriverAgent-master/Configurations/appium.xcconfig","deviceName":"iPhone 7 Plus","agentPath":"/Users/subarajaram/node_modules/WebDriverAgent-master/WebDriverAgent.xcodeproj","bootstrapPath":"/Users/subarajaram/no...
[BaseDriver] Event 'newSessionRequested' logged at 1516174160825 (18:29:20 GMT+1100 (AEDT))
[Appium] Creating new XCUITestDriver (v2.51.1) session
[Appium] Capabilities:
[Appium]   app: '/Users/subarajaram/Desktop/ios_ipa/latest/Savvy_Dev.ipa'
[Appium]   noReset: true
[Appium]   bundleId: 'au.com.commbank.savvy.test'
[Appium]   xcodeConfigFile: '/Users/subarajaram/node_modules/WebDriverAgent-master/Configurations/appium.xcconfig'
[Appium]   deviceName: 'iPhone 7 Plus'
[Appium]   agentPath: '/Users/subarajaram/node_modules/WebDriverAgent-master/WebDriverAgent.xcodeproj'
[Appium]   bootstrapPath: '/Users/subarajaram/node_modules/WebDriverAgent-master'
[Appium]   newCommandTimeout: 180
[Appium]   platformVersion: '11.1'
[Appium]   automationName: 'XCUITest'
[Appium]   useNewWDA: true
[Appium]   udid: '3df785473d472fbcdfcd11b9c572bb3498fa3f39'
[Appium]   platformName: 'iOS'
[Appium]   autoAcceptAlerts: true
[XCUITest] The capabilities 'autoAcceptAlerts' and 'autoDismissAlerts' do not work for XCUITest-based tests. Please adjust your alert handling accordingly.
[BaseDriver] Session created with session id: 0b2f7c07-b5be-44b5-8209-bf0086635afa
[XCUITest] Xcode version set to '9.2' (tools v9.1.0.0.1.1508540944)
[XCUITest] iOS SDK Version set to '11.2'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1516174160901 (18:29:20 GMT+1100 (AEDT))
[XCUITest] Available devices: 3df785473d472fbcdfcd11b9c572bb3498fa3f39
[XCUITest] Creating iDevice object with udid '3df785473d472fbcdfcd11b9c572bb3498fa3f39'
[XCUITest] Determining device to run tests on: udid: '3df785473d472fbcdfcd11b9c572bb3498fa3f39', real device: true
[BaseDriver] Using local app '/Users/subarajaram/Desktop/ios_ipa/latest/Savvy_Dev.ipa'
[BaseDriver] Copying local zip to tmp dir
[BaseDriver] Unzipping /var/folders/x2/gndcqf4d47v07bfvf894s2l40000gn/T/2018017-633-xyye00.d7udydgqfr/appium-app.zip
[BaseDriver] Testing zip archive: /var/folders/x2/gndcqf4d47v07bfvf894s2l40000gn/T/2018017-633-xyye00.d7udydgqfr/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/x2/gndcqf4d47v07bfvf894s2l40000gn/T/2018017-633-xyye00.d7udydgqfr/Payload/Savvy_Dev.app'
[BaseDriver] Event 'appConfigured' logged at 1516174162162 (18:29:22 GMT+1100 (AEDT))
[XCUITest] Checking whether app '/var/folders/x2/gndcqf4d47v07bfvf894s2l40000gn/T/2018017-633-xyye00.d7udydgqfr/Payload/Savvy_Dev.app' is actually present on file system
[XCUITest] App is present
[BaseDriver] Event 'resetStarted' logged at 1516174162163 (18:29:22 GMT+1100 (AEDT))
[XCUITest] Reset: fullReset not set. Leaving as is
[BaseDriver] Event 'resetComplete' logged at 1516174162164 (18:29:22 GMT+1100 (AEDT))
[iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[iOSLog] Starting iOS device log capture with: 'idevicesyslog'
[BaseDriver] Event 'logCaptureStarted' logged at 1516174162580 (18:29:22 GMT+1100 (AEDT))
[XCUITest] Setting up real device
[XCUITest] App 'au.com.commbank.savvy.test' is already installed. No need to reinstall.
[BaseDriver] Event 'appInstalled' logged at 1516174162910 (18:29:22 GMT+1100 (AEDT))
[XCUITest] Using WDA path: '/Users/subarajaram/node_modules/WebDriverAgent-master'
[XCUITest] Using WDA agent: '/Users/subarajaram/node_modules/WebDriverAgent-master/WebDriverAgent.xcodeproj'
[XCUITest] Capability 'useNewWDA' set to true, so uninstalling WDA before proceeding
[XCUITest] Shutting down sub-processes
[XCUITest] Removing WDA application from device
[BaseDriver] Event 'wdaUninstalled' logged at 1516174163179 (18:29:23 GMT+1100 (AEDT))
[BaseDriver] Event 'wdaStartAttempted' logged at 1516174163180 (18:29:23 GMT+1100 (AEDT))
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Killing running processes 'xcodebuild.*3df785473d472fbcdfcd11b9c572bb3498fa3f39, iproxy 8100' for the device 3df785473d472fbcdfcd11b9c572bb3498fa3f39...
[XCUITest] 'pgrep -nif xcodebuild.*3df785473d472fbcdfcd11b9c572bb3498fa3f39' didn't detect any matching processes. Return code: 1
[XCUITest] 'pgrep -nif iproxy 8100' didn't detect any matching processes. Return code: 1
[XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[XCUITest] Using Xcode 9.2, so fixing WDA codebase
[XCUITest] Using Xcode configuration file: '/Users/subarajaram/node_modules/WebDriverAgent-master/Configurations/appium.xcconfig'
[XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Users/subarajaram/node_modules/WebDriverAgent-master/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=3df785473d472fbcdfcd11b9c572bb3498fa3f39 IPHONEOS_DEPLOYMENT_TARGET=11.1 -xcconfig /Users/subarajaram/node_modules/WebDriverAgent-master/Configurations/appium.xcconfig' in directory '/Users/subarajaram/node_modules/WebDriverAgent-master'
[XCUITest] Output from xcodebuild will not be logged. To see xcode logging, use 'showXcodeLog' desired capability
[XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Log file for xcodebuild test: /var/folders/x2/gndcqf4d47v07bfvf894s2l40000gn/T/com.apple.dt.XCTest/IDETestRunSession-AAAB8BB0-7BB7-4FA6-86C3-D8D96442C100/WebDriverAgentRunner-213D6C29-9E2A-43CB-B23F-CB95AD254EDD/Session-WebDriverAgentRunner-2018-01-17_182930-eBpeOo.log
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] 2018-01-17 18:29:34.615 xcodebuild[1359:40951] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[Xcode] 2018-01-17 18:29:34.494650+1100 WebDriverAgentRunner-Runner[267:16033] +[CATransaction synchronize] called within transaction
[Xcode] 2018-01-17 18:29:34.514326+1100 WebDriverAgentRunner-Runner[267:16033] Running tests...
[Xcode] 2018-01-17 18:29:34.554566+1100 WebDriverAgentRunner-Runner[267:16033] The bundle “WebDriverAgentRunner” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
[Xcode] 2018-01-17 18:29:34.554612+1100 WebDriverAgentRunner-Runner[267:16033] (dlopen_preflight(/var/containers/Bundle/Application/959A629C-2FF8-474C-B9E4-788879468BC7/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner): Library not loaded: @rpath/RoutingHTTPServer.framework/RoutingHTTPServer
[Xcode]   Referenced from: /private/var/containers/Bundle/Application/959A629C-2FF8-474C-B9E4-788879468BC7/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib
[Xcode]   Reason: no suitable image found.  Did find:
[Xcode] 	/private/var/containers/Bundle/Application/959A629C-2FF8-474C-B9E4-788879468BC7/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer: required code signature missing for '/private/var/containers/Bundle/Application/959A629C-2FF8-474C-B9E4-788879468BC7/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer'
[Xcode] )
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[BaseDriver] Event 'wdaStartFailed' logged at 1516174174637 (18:29:34 GMT+1100 (AEDT))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 1358)
[XCUITest] iproxy exited with code 'null'
[XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:381:13)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:381:13)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:381:13)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 24016 ms - 470

**Comment by SubaRajaram09** [comment]
I ve posted my appium logs.. webdriverAgent app gets installed in my phone and disappears. My test app is never launched at all . Can you guys please look at my logs ..

**Comment by senevit4** [comment]
You have error 65. You need to follow the https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md.

**Comment by mykola-mokhnach** [comment]
There are problems with code signing. Closed as duplicate
