### ISSUE TITLE
Appium - Swiping horizontally on iOS application does not refresh page source of the screen 

### ISSUE THREAD

**Issue by lamlouma** [appium/appium#10009]
## The problem

I get the page source by System.out.println("Page Source: "+DriverConfiguration.getInstance().getDriver().getPageSource()); then I do swipe horizontally on a screen then I print again the page source using
System.out.println("Page Source: "+DriverConfiguration.getInstance().getDriver().getPageSource()); 
The page source does not seem to get updated and thus some buttons on the new screen after the swipe cannot be tapped 

## Environment

* Appium Desktop 1.3.1
* Macbook pro macOS Sierra
* iOS 11.1 
* simulator: iPhone 6

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/facebook/WebDriverAgent/issues
