### ISSUE TITLE
Appium desktop inspector not correct for orientation

### ISSUE THREAD

**Issue by klementynka** [appium/appium#10015]
When I set up portrait mode and I open inspector, simulator is in proper position (
portrait mode) but inspector shows me landscape mode. 

[screenshot](https://www.screencast.com/t/ThODy624sv1z)

My capabilities:
{
  "platformName": "iOS",
  "platformVersion": "11.1",
  "deviceName": "iPad Air",
  "automationName": "XCUITest",
  "app": "/Users/ProductName.app",
  "orientation": "PORTRAIT"
}

Environment:
Mac v.10.13.2
Appium v.1.7.2
Node v.8.9.3
XCUITestDriver v.2.64.0
Xcode v.9.2
Simulator iPad Air iOS v.11.1

[Appium.log](https://gist.github.com/klementynka/d64f7eb8f12b962df922c9c21905bff3)

The similar problem was registered in Appium Desktop - [ticket 211](https://github.com/appium/appium-desktop/issues/211) - but the ticket was closed because it was "an Appium issue and not an Appium Desktop issue"

**Comment by mykola-mokhnach** [comment]
Which orientation is actually returned if getOrientation is called in this state?

**Comment by klementynka** [comment]
I've added driver.getOrientation() at the end of setup method, it returned LANDSCAPE.

**Comment by mykola-mokhnach** [comment]
This means that the application under test still assumes it is in landscape mode and returns such info to XCTest. And the simulator view is also rotated based on this data. Please report the issue to Apple.

Closed as non appium-related.
