### ISSUE TITLE
Cannot find/populate element on page (iOS)

### ISSUE THREAD

**Issue by ali-mirza786** [appium/appium#10014]
## The problem

I am trying to run a simple test case with my app. Simply trying to log into the app. Appium is able to find the email field and populate it successfully, but it gets hung up after populating the email field, does not close the keyboard and then won't successfully find the password field. I know the following facts are true:

## Environment

XCUITEST
Appium version (or git revision) that exhibits the issue: v1.6.5
Desktop OS/version used to run Appium: MacOS 10.12.6
Mobile platform/version under test: ios 10.3
Real device or emulator/simulator: iPhone 6

## Details

1) I have a unique access ID for the password field, so this is not the issue
2) My script clearly calls the hide_keyboard() function

This generally seems to be a problem with my scripts, that once the first element is located.. subsequent elements cannot be located. This most simple test case demonstrates it well. 

There was some replies to a similar issue I posted #9725 and was not quite sure of what the solution was. One person recommended "printing the page source" before trying to locate element? Not sure what that means. 

Here is the history from my command line:

Traceback (most recent call last):
  File "testcbyge.py", line 249, in test_a13
    controller.select_element("login", "password_field").send_keys(caps_password)
  File "controller.py", line 93, in select_element
    return driver.find_element_by_id(path)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 271, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 756, in find_element
    'value': value})['value']
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 238, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/appium/webdriver/errorhandler.py", line 29, in check_response
    raise wde
NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

----------------------------------------------------------------------
Ran 1 test in 47.565s

## Link to Appium logs

https://gist.github.com/ali-mirza786/06ea086053d5608966075d33e686d731

## Code To Reproduce Issue [ Good To Have ]
def test_a13(self):
		"""testing case-sensitivity of passwords"""
		controller.select_element("create_account", "login_link").click()
		controller.select_element("login", "email_field").send_keys(controller.get_email_value())
		controller.driver.hide_keyboard()
		caps_password = (controller.get_password_value()).upper()
		controller.select_element("login", "password_field").send_keys(caps_password)
		controller.driver.hide_keyboard()
		controller.select_element("login", "submit_button").click()
		check = None
		error_message = check
		while error_message is None:
			try:
				error_message = (
					controller.select_element("general_page_elements", "error_message")).text
			except:
				pass

**Comment by ali-mirza786** [comment]
Can anyone help with this one??

**Comment by ali-mirza786** [comment]
@imurchie Any help on this possible?

**Comment by KazuCocoa** [comment]
I saw 500 error in your log and `[iProxy] Error connecting to device!`.

```
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["id","field.password","0e7b870e-6222-4135-9ef5-574e1bc4f479"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/20C8A6CC-D952-4668-87FB-DBD52A9D4A29/element] with body: {"using":"id","value":"field.password"}
[debug] [iProxy] Error connecting to device!
[info] [HTTP] <-- POST /wd/hub/session/0e7b870e-6222-4135-9ef5-574e1bc4f479/element 500 12 ms - 164 [info] [HTTP] --> DELETE /wd/hub/session/0e7b870e-6222-4135-9ef5-574e1bc4f479 {}
[debug] [MJSONWP] Calling AppiumDriver.deleteSession() with args: ["0e7b870e-6222-4135-9ef5-574e1bc4f479"]
[debug] [BaseDriver] Event 'quitSessionRequested' logged at 1516207631074 (11:47:11 GMT-0500 (EST))
[debug] [JSONWP Proxy] Proxying [DELETE /session/0e7b870e-6222-4135-9ef5-574e1bc4f479] to [DELETE http://localhost:8100/session/20C8A6CC-D952-4668-87FB-DBD52A9D4A29] with no body
[debug] [iProxy] Error connecting to device!
[debug] [XCUITest] Unable to DELETE session on WDA: 'Could not proxy command to remote server. Original error: Error: socket hang up'. Continuing shutdown.
[info] [XCUITest] Shutting down sub-processes
[info] [XCUITest] Shutting down xcodebuild process (pid 39949)
[info] [XCUITest] xcodebuild exited with code 'null' and signal 'SIGTERM'
[info] [XCUITest] Shutting down iproxy process (pid 39948)
[debug] [XCUITest] iproxy exited with code 'null'
```

You can see the same issue _iproxy error connecting to device with xcode 8 and appium 1.6.3 #7708_ and facebook/WebDriverAgent#372 is it.

---

> One person recommended "printing the page source" before trying to locate element? Not sure what that means
It means try `page_source` and print it.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
