### ISSUE TITLE
Mocha aparatus should not use arrow functions

### ISSUE THREAD

**Issue by imurchie** [appium/appium#10016]
## The problem

`describe` and `it` blocks depend on `this` being the mocha context, so lexical scoping (using the fat arrow to define a function) causes problems.

`eslint-config-appium` v2.1.0 has a rule for this (set to warn), and `appium-gulp-plugins` allows eslint to fix problems. So deps need to be updated, and then an npm run script ought to be added to `package.json`
```json
  // package.json
  "lint:fix": "gulp eslint --fix"
```

Run `npm run lint` to see what warning show up. They should all be of the sort
```
240:7   warning  Do not pass arrow functions to it()        mocha/no-mocha-arrows
```

Then run `npm run lint:fix`, check in the results, and make a PR.

Tada!

## Packages

Let's get somewhat systematic about this...

- [x] appium
- [x] appium-uiautomator2-server
- [x] appium-xcuitest-driver
- [x] appium-uiautomator2-driver
- [x] appium-android-driver
- [x] appium-base-driver
- [x] appium-desktop
- [ ] appium-test-support
- [x] appium-ios-driver
- [x] appium-chromedriver
- [x] appium-adb
- [x] appium.io
- [ ] appium-windows-driver
- [x] appium-support
- [ ] appium-mac-driver
- [x] appium-fake-driver
- [ ] appium-espresso-driver
- [x] appium-xcode
- [x] appium-selendroid-driver
- [x] appium-uiautomator
- [x] node-simctl
- [x] io.appium.android.ime
- [x] appium-ios-simulator
- [x] node-teen_process
- [x] io.appium.settings
- [x] appium-android-bootstrap
- [x] appium-remote-debugger
- [ ] authorize-ios
- [ ] appium-doctor
- [ ] appium-gulp-plugins
- [x] appium-event-parser
- [x] appium-ci
- [x] eslint-config-appium

**Comment by dpgraham** [comment]
Hey @imurchie I had some time on my hands, so I went ahead and put in PR's for all of these so we can get it done before sprint end.
