### ISSUE TITLE
Deep linking does not work iOS.

### ISSUE THREAD

**Issue by apanashchenko** [appium/appium#10010]
## The problem

Hi to all,
I try to navigate in our app by deep link, driver.get("blablaschema://news/11111") or driver.navigate().to("blablaschema://news/11111"). Nothing happens and I have an error (see attach).

## Environment

* Appium 1.7.2
* Macbook pro, macOS High Sierra v.10.13.2
* iOS 11.2.2
* Real device: iPhone 7
* Node.js v8.4.0
* Java language: java client 5.0.4

## Link to Appium logs
[GIST.APPIUM.LOG](https://gist.github.com/apanashchenko/b9df9705eaebab3e76bbec57c9913551)

**Comment by mykola-mokhnach** [comment]
Closed as duplicate. This only works on Simulators
