### ISSUE TITLE
Unable to parse remote response: 'deviceName' error when deviceName exists. (w3c issue)

### ISSUE THREAD

**Issue by kool79** [appium/appium#10017]
## The problem

I got the error
```
org.openqa.selenium.WebDriverException: Unable to parse remote response: 'deviceName' can't be blank
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T18:33:54.468Z'
```
when call java code: 
```java
DesiredCapabilities dc = new DesiredCapabilities();

dc.setCapability(MobileCapabilityType.PLATFORM_NAME, Platform.IOS);
dc.setCapability(MobileCapabilityType.PLATFORM_VERSION, "11.2");
dc.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 7");
dc.setCapability(MobileCapabilityType.BROWSER_NAME, BrowserType.SAFARI);
dc.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.IOS_XCUI_TEST);
dc.setCapability("newCommandTimeout", 300);

RemoteWebDriver wd = new RemoteWebDriver(hubUrl, dc);
```

Log on appium side contains:
```
[Appium] Appium REST http interface listener started on 0.0.0.0:4724
[debug] [Appium] Appium successfully registered with the grid on ta-mac-01:4444
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"automationName":"XCuiTest","browserName":"safari","deviceName":"iPhone 7","newCommandTimeout":300,"platformName":"IOS","platformVersion":"11.2"},"capabilities":{"desiredCapabilities":{"automationName":"XCuiTest","browserName":"safari","deviceName":"iPhone 7","newCommandTimeout":300,"platformName":"IOS","platformVersion":"11.2"},"firstMatch":[{"browserName":"safari","platformName":"ios"}]}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"automationName":"XCuiTest","browserName":"safari","deviceName":"iPhone 7","newCommandTimeout":300,"platformName":"IOS","platformVersion":"11.2"},null,{"desiredCapabilities":{"automationName":"XCuiTest","browserName":"safari","deviceName":"iPhone 7","newCommandTimeout":300,"platformName":"IOS","platformVersion":"11.2"},"firstMatch":[{"browserName":"safari","platformName":"ios"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1516226279848 (23:57:59 GMT+0200 (EET))
[HTTP] <-- POST /wd/hub/session 400 10 ms - 27 
```

Please note that `firstMatch` does not include any other values beside standard "browserName" and "platformName".  It seems appium requires that deviceName should also be present here. But according to w3s this is extension capability and it must be have prefix, for example, "appium:browserName", see [here]( https://www.w3.org/TR/webdriver/#dfn-extension-capabilities): 
```
Extension capabilities are typically used to provide UA or intermediary node specific 
configuration that is not handled by the table of standard capabilities.
```

**Comment by kool79** [comment]
I just digging into the source-code and found that appium actually accept capabilities with prefix `appium:`
So solution is to add prefix for all non-standard capabilities. I checked this and it works fine.
```java
String prefix = "appium:";
dc.setCapability(MobileCapabilityType.PLATFORM_NAME, Platform.IOS);
dc.setCapability(prefix + MobileCapabilityType.PLATFORM_VERSION, "11.2");
dc.setCapability(prefix + MobileCapabilityType.DEVICE_NAME, "iPhone 7");
dc.setCapability(MobileCapabilityType.BROWSER_NAME, BrowserType.SAFARI);
dc.setCapability(prefix + MobileCapabilityType.AUTOMATION_NAME, AutomationName.IOS_XCUI_TEST);
dc.setCapability(prefix + "newCommandTimeout", 300);
```

I think we can remove W3C and Bug tags but should add `Documentation` tag (or something like that). Because release v1.8 (in conjunction with selenium v3) started to parse w3c capabilities while documentation has nothing about required prefix "appuim:".

**Comment by mykola-mokhnach** [comment]
I assume it makes sense to report this issue to the java client instead. I also observe that elements finding and getting page source is broken if W3C protocol is enabled there.

**Comment by dpgraham** [comment]
This is a known issue. We need to fix the Java client and we also have a change coming in for Appium that detects if W3C has less props than MJSONWP, it falls back to MJSONWP.

**Comment by kool79** [comment]
@dpgraham 
>  we also have a change coming in for Appium that detects if W3C has less props than MJSONWP, it falls back to MJSONWP
  I just tries the latest version from master and W3C stopped work for me.  While I send all capabilities in w3c forms it looks like appium use MJSONWP (see examp[le in my comment above).   I want to propose another algorithm: use w3c if any capability starts with "appium:" and fallback to MJSONWP if there are no capabilities which starts with "appium:"
 P.S.  I use RemoteWebDriver from selenium v3.8.1. It sends capabilities both in w3c and MJSONWP.
