### ISSUE TITLE
Not able to switch to WebView Appium 1.7.2 Xcode 9.x

### ISSUE THREAD

**Issue by DanielPradoPino** [appium/appium#10028]
## The problem

I have to test some iOS hybrid apps and I am not able to switch to Webview context while using xcode 9.x, even Econnrefused is launched when I try to enumerate the available contexts.

Same tests, same Appium version, same app is working on Xcode 8.3

Also startup is taking a very long time (some times more than 5 minutes) after installing the app into simulator.

I have updated appium, libimobile but maybe I am missing something.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7..2

**Comment by vjmaiky** [comment]
i had a similar problem yesterday. I could not switch to webview. The cause was that webview was loading too slow. As a quick fix i'm using this (and it is working; i can identify and interact with elements) :

> try {
>             WebHelpers.startIosWebKit();
>             Thread.sleep(15000);
>             ContextHandler.switchToWebview();
>         } catch (Exception e) {
>             e.printStackTrace();
>         }

Interact with your elements.

> try {
>             WebHelpers.stopIosWebKit();
>             ContextHandler.switchToNative();
>         } catch (IOException e) {
>             e.printStackTrace();
>         }

**Comment by DanielPradoPino** [comment]
Hi @vjmaiky,

Sorry, I am not so familiarised with WebHelpers, nver used them, I am working in simulator and as I said the same code with same appium version and same app works on xcode 8.3 and not in xcode 9.1.

Can you please check if helpers are the responsible here?

Thanks.

**Comment by vjmaiky** [comment]
Hi @DanielPradoPino ,
WebHelpers is a class created by me (i have some methods that help me with tests). It's not something provided by selenium, or others. Just use a wait before you change context and it will work.

```
 public static void startIosWebKit() throws Exception {
        String cmd = "ios_webkit_debug_proxy -c " + ServerManager.DEVICE_ID() + ":" + ServerManager.IOS_WEBKIT();
        MyLogger.log.info("++++++++ RUNNING IOS_WEBKIT_DEBUG_PROXY++++++++ :" + cmd);

        startWebkitProxy = Runtime.getRuntime().exec(cmd);
        MyLogger.log.info("++++++++Starting IOS_WEBKIT_DEBUG_PROXY++++++++ :" + startWebkitProxy);
        iosWebKitRecordProcess
                .put(Thread.currentThread().getId(), getPid(startWebkitProxy));
        MyLogger.log.info("++++++++GET ID + PID of IOS_WEBKIT_DEBUG_PROXY++++++++ :" + startWebkitProxy);
    }
```

```
   public static void stopIosWebKit() throws IOException {
        Integer processId = iosWebKitRecordProcess.get(Thread.currentThread().getId());
        stopRunningProcess(processId);
    }
```

**Comment by imurchie** [comment]
Since the time for the webview to get initialized and available can vary, it is often helpful to poll for it's start. The Appium iOS test code, for instance, includes things like https://github.com/appium/appium-xcuitest-driver/blob/master/test/functional/basic/basic-e2e-specs.js#L262-L267

**Comment by DanielPradoPino** [comment]
Hi guys,
Sorry for late reply, Do you think the econnrefuse issue I am having when calling for getcontexts is related to the time a webview is taking to be visible?
Should it show only NATIVE_APP and thats it?
I think I have something misconfigured or outdated somewhere...
Thanks both, you are great.

**Comment by vjmaiky** [comment]
Hi again,

For some reasone i encounter this error also.

Now i'm using this method:

switchToContext("NATIVE_APP");
```

    public static void switchToContext(String context) throws Exception {
        MyLogger.log.info("Trying to switch to : " + context);
        getAllContexts();
        if (Drivers.getMobileDriver().getContext().contains(context)) {
            MyLogger.log.info("Already on context " + context);
        } else {
            Drivers.getMobileDriver().getContextHandles();
            try {
                Drivers.getMobileDriver().context(context);
                MyLogger.log.info("Successfully switched to : " + context);
            } catch (NoSuchContextException e) {
                MyLogger.log.error("Could not switch to context " + context);
                throw e;
            }
        }

    }
```

**Comment by DanielPradoPino** [comment]
Hi again guys,
I  were able to fix this, it seems java client was the guilty one in here with 6.0.0-BETA2 everything is ok and back to normal.

Thank you very much for all the support.
