### ISSUE TITLE
Unable to start WebDriverAgent session through Appium on IOS 11 device

### ISSUE THREAD

**Issue by SaptakBagchi** [appium/appium#10022]
## The problem

I am using Appium for IOS 11 ipad automation and when i am building WDA via Xcode it is getting build successfully along with the WDA app on that device but when i am trying to start the appium session with all the desired capabilities , appium is throwing some internal error and the WDA is removed from the device.

## Environment
* platformName: "iOS",
* platformVersion: "11.1.2",
* deviceName: "administrator’s iPad",
* udid: "Provided in desired cap",
* pp: "Provided in desired cap"
* Appium version (or git revision) that exhibits the issue: 1.7.1
* Desktop OS/version used to run Appium:
* Mobile platform/version under test: IOS
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium desktop

## Details

 Encountered internal error running command: Error: Unable to start WebDriverAgent session because of xcodebuild failure: "An unknown server-side error occurred while processing the command. Original error: Unhandled endpoint: /session -- http://localhost:8100/ with parameters { wildcards = ( session ); }

## Link to Appium logs

https://gist.github.com/SaptakBagchi/3bc9c66fef8e2f3061500f32bc620354

## Code To Reproduce Issue [ Good To Have ]

Currently we are tying to start the appium session manually. Will try with code once this issue is resolved.

**Comment by mykola-mokhnach** [comment]
Please attach the full log

**Comment by SaptakBagchi** [comment]
Full log is in below link:

https://gist.github.com/SaptakBagchi/3bc9c66fef8e2f3061500f32bc620354

**Comment by mykola-mokhnach** [comment]
the attached log is not full. I don't see capabilities as well as big part of driver initialisation. Also, device logs will be useful.
