### ISSUE TITLE
API do not return sessionID

### ISSUE THREAD

**Issue by luizlohn** [appium/appium#10025]
## The problem
When I request sessions/ to API, API always return null to sessionID.

## Environment

* Appium version: latest
* Desktop OS/version used to run Appium: OSX

## Details

I request GET to http://MyIp:4727/wd/hub/sessions/, in this adress is running a test, I can see into Appium Login thats everything running OK, but when I try to get a sessionID return for me: 
{
    "status": 0,
    "value": [],
    "sessionId": null
}

Into Appium debug I can see that my GET request works but do not return nothing

**Comment by mykola-mokhnach** [comment]
Can you please describe step by step what you are doing and what are you tying to achieve? I don't get what is the problem here
