### ISSUE TITLE
Unable to launch app on Android 8.1.0

### ISSUE THREAD

**Issue by raz197** [appium/appium#10021]
## The problem

I'm getting 'No such file or directory' error when launching the android app on Pixel 2 XL running 8.1.0. Appium server is running via Appium.app, it can successfully install the settings and unlock app on the device but fails to install the actual apk due to invalid path for remote apk error message. Please see log attached. 

## Environment

* Appium version - 1.5.3 (Ara)
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: macOS Sierra 10.12.5
* Node.js version (unless using Appium.app|exe): Running Appium.app
* Mobile platform/version under test: Android 8.1.0
* Real device or emulator/simulator: Real Device - Pixel 2 XL
* Appium CLI or Appium.app|exe: Appium.app

## Details

When starting the Appium server via Appium.app, I'm specifying the app path, activity, platform name and platform version.

## Link to Appium logs

https://gist.githubusercontent.com/raz197/2d265be7b4099e70d0f91cbff3665b20/raw/4c4621a5f8bec4652923412a0f300e6c802cad52/appium.log

## Code To Reproduce Issue [ Good To Have ]

1. start up the appium server via Appium.app
2. run the test using mvn clean test -Dgeb.env=android

Capabilities definition is:
 //set capabilities and appium URL
   DesiredCapabilities capa = new DesiredCapabilities()
   URL appiumUrl = new URL("http://0/0/0/0:4723/wd/hub")
   capa.setCapability("platformVersion" , "8.1.0")
   capa.setCapability("deviceName"      , "Pixel 2 XL")
   capa.setCapability("app"             , "/Users/QAE2/Documents/raz/ANDROIDAPP.apk")
   capa.setCapability("appWaitActivity" , "com.company.login.LoginActivity")

  driver = new AndroidDriver(appiumUrl, capa)

**Comment by mykola-mokhnach** [comment]
Appium 1.5.3 is outdated. Please update to 1.7.2

**Comment by raz197** [comment]
Thanks @mykola-mokhnach . If i use npm install appium@1.7.2 would it overwrite my current appium installation? If it keeps both, how can i start the appium server 1.7.2 from terminal?

**Comment by mykola-mokhnach** [comment]
it would be safer to remove the previous installation first

**Comment by raz197** [comment]
Thanks heaps, was able to install and launch the server from command line and start the app successfully 
But when i try to interact with the application, I'm getting NoSuchElementException. I have confirmed through the appium doctor the id of the object is correct, could it be that when i instantiate the driver I'm using

driver = new AndroidDriver(appiumURL, capa)

but in the logs I'm getting

[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["id","com.company:id/btnContinue","b8287b07-a349-4afb-914c-e4014e3e1e1b"]

Which one should I be using, AndroidDriver or AppiumDriver? For iOS I'm using new IOSDriver which is working without any issues.

**Comment by hardik-plume** [comment]
yeah find_element is failing for me too
