### ISSUE TITLE
Can't perform any gestures using TouchAction class

### ISSUE THREAD

**Issue by sevarudakov** [appium/appium#10035]
## The problem

I am trying to perform "tap" action with coordinates on android emulator using ruby/capybara but fail.

```
  1.1) Failure/Error: Unable to find matching line from backtrace
          
          EOFError:
            end of file reached

     1.2) Failure/Error: e = error
          
          Selenium::WebDriver::Error::NoSuchDriverError:
            A session is either terminated or not started
```

## Environment
* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): 1.7.1
* Desktop OS/version used to run Appium: Mac OS Sierra 10.12.6
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Android Emulator
* Appium CLI or Appium.app|exe: Appium.app|exe

## Link to Appium logs
https://gist.github.com/sevarudakov/5a5acc005b24d35fda986a2dea8479e4

## Code To Reproduce Issue [ Good To Have ]
 
```opts = {
                   caps: {
                     platformName: :android,
                     app: '/Users/vrudakov/Desktop/ui-tests/Jiff.apk',
                     deviceName: "testing",
                     browserName: "chrome",

                   },
                   appium_lib: {
                     wait_timeout: 30,
                     wait_interval: 1
                   }
                 }
Please help.

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/appium/ruby_lib

@KazuCocoa FYI

**Comment by KazuCocoa** [comment]
@sevarudakov
As mentioned in the above comment, could you create an issue on ruby_lib or https://github.com/appium/appium_capybara and could you also attach test scenario code?
