### ISSUE TITLE
iOS multi-touch fails when the touch actions don't have the same number of commands

### ISSUE THREAD

**Issue by PaunCostin** [appium/appium#10037]
## The problem

Performing a multi-touch on iOS fails when the touch actions doesn't not contain the same number of commands (are not equal in length). 

I'm using the .NET driver to perform a multi-touch action on a remote Appium server that runs on the macOS. 
I have a iPad Pro connected to the mac machine where I run test sessions.
I create a multi-touch action (see code in the code to repdoduce section) and upon performing I receive
"Cannot read property 'touch' of undefined."

See code in the how to reproduce section.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.3 (although the code is the same on the last version as well).
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: macOS Sierra 10.12.6
* Node.js version (unless using Appium.app|exe): N/A
* Mobile platform/version under test: iOS 9.1
* Real device or emulator/simulator: iPad Pro 9.1
* Appium CLI or Appium.app|exe: Appium Desktop 1.5.3

## Details
Please check appium logs also.

I tracked the problem in **gesture.js** from the iOS driver: https://github.com/appium/appium-ios-driver/blob/master/lib/commands/gesture.js in the `mergeStates` function.

I put logs in the file to check what vaiables are being computed and I got this:
`
/* The actions */
[iOS] action: [{"action":"press","options":{"x":200,"y":200}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"x":400,"y":400}},{"action":"release"}]
[iOS] action: [{"action":"press","options":{"x":100,"y":100}},{"action":"wait","options":{"ms":2000}},{"action":"release"}]

/* The computed states */
[iOS] states:[
[
{"touch":[{"x":200,"y":200}],"time":0.2},
{"touch":[{"x":200,"y":200}],"time":1.2},
{"touch"[{"x":600,"y":600}],"time":1.4}
],
[
{"touch":[{"x":100,"y":100}],"time":0.2},
{"touch":[{"x":100,"y":100}],"time":2.2}]
]

/* The time indexes aray */
[iOS] [0.2,1.2,1.4,2.2]

/* From the inner getSlice method */
[iOS] state[0][0] {"touch":[{"x":200,"y":200}],"time":0.2}
[iOS] state[1][0] {"touch":[{"x":100,"y":100}],"time":0.2}
[iOS] state[0][1] {"touch":[{"x":200,"y":200}],"time":1.2}
[iOS] state[1][1] {"touch":[{"x":100,"y":100}],"time":2.2}
[iOS] state[0][2] {"touch":[{"x":600,"y":600}],"time":1.4}
[iOS] state[1][2] undefined `

The error comes from that last line, as  state[1][2] is undefined. 
The iteration from the `getSlice = function (states, index)` method doesn't take into account that the second section has only two elements.

## Link to Appium logs
https://gist.github.com/PaunCostin/95a2c49a7e4a77b0f61579b719093e3d

## Code To Reproduce Issue
`
// The appiumDriver is initialized elsewhere
var touch1 = new TouchAction(appiumDriver);
// Simulate a swipe
touch1.Press(200, 200)
        .Wait(1000)
        .MoveTo(400, 400)
        .Release();

var touch2 = new TouchAction(appiumDriver);
// Simulate a press
touch2.Press(100, 100)
        .Wait(2000)
        .Release();

var multiTouch = new MultiAction(appiumDriver);
multiTouch.Add(touch1);
multiTouch.Add(touch2);

multiTouch.Perform();
`
This crashes with "Cannot read property 'touch' of undefined".

**Comment by mykola-mokhnach** [comment]
You're welcome to provide a patch if you can fix it.

**Comment by PaunCostin** [comment]
I'm not exactly sure what the desired behavior should be, although I can surely make some trials.
Maybe the original contributor for that feature will comment - @sebv ? Thanks

**Comment by mykola-mokhnach** [comment]
Closed as obsolete
