### ISSUE TITLE
How I can send a parameter to the application when starting the test?

### ISSUE THREAD

**Issue by BoazWarshawsky** [appium/appium#10036]
## The problem
I can't find a proper way to send my iOS application a parameter when I am starting the test, is there an option with the desired_capabilities?

## Environment
* Appium version 1.7.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: 11.0
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/issues/9659

Please use Appium forum (or Search) to ask questions
