### ISSUE TITLE
Can not scroll to element outside the screen

### ISSUE THREAD

**Issue by sanlengjingvv** [appium/appium#10039]
## The problem
screen size is `{"width":414,"height":736}`, element location is `{"x":167,"y":740}`
```
execute('mobile: scroll', {element: element.value.ELEMENT, 'toVisible': true})
```

**expect:**  
swipe up like `execute('mobile: scroll', {direction: 'down’})`

**actual:**  
swipe down like `execute('mobile: scroll', {direction: 'up'})`

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 1.3.1
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 11.2.2
* Real device or emulator/simulator: Real device, iPhone 7 Plus
* Appium CLI or Appium.app|exe: Appium.app

## Link to Appium logs
https://gist.github.com/sanlengjingvv/3ed727fdd59b6f21f97b550df9fdff8f

## Code To Reproduce Issue [ Good To Have ]
```javascript
// WebdriverIO
describe('scroll', function() {
    it('scroll to element', function() {
        var element = browser.element('.//XCUIElementTypeCell[6]/descendant::XCUIElementTypeStaticText[3]')
        console.log(element.getLocation())
        console.log(browser.windowHandleSize())        
        browser.execute('mobile: scroll', {element: element.value.ELEMENT, 'toVisible': true})
    })
})
```

**Comment by mykola-mokhnach** [comment]
Scrolling is done on [WebDriverAgent](https://github.com/facebook/WebDriverAgent/issues) side. Nothing we can do there. 

BTW, have you verified that element locator matches correct screen component?

**Comment by sanlengjingvv** [comment]
screen size is `{"width":414,"height":736}`, element location is `{"x":167,"y”:610}`
```
browser.execute('mobile: scroll', {element: element.value.ELEMENT, 'toVisible': true})
``` 
Do nothing
```
browser.execute('mobile: scroll', {element: element.value.ELEMENT, direction: 'down'})
browser.execute('mobile: scroll', {element: element.value.ELEMENT, direction: 'up'})
browser.execute('mobile: scroll', {element: element.value.ELEMENT, direction: 'left'})
browser.execute('mobile: scroll', {element: element.value.ELEMENT, direction: 'right’})
```
scroll to right direction
