### ISSUE TITLE
Unable to run UIAutomator2 test on Appium 1.7.2

### ISSUE THREAD

**Issue by jbruckne** [appium/appium#10030]
## The problem

When running UIAutomator2 tests, Appium is unable to run the aapt command on appium-uiautomator2-server-v0.3.0.apk. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Ubuntu 12
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe: Appium CLI

## Details

We've tried running the aapt command manually and it successfully prints the manifest information. 
We run the Appium server under the same user. We've also tried giving full permissions to the server apk. 

## Link to Appium logs

https://gist.github.com/jbruckne/f6ef3738b4b4a2f14b4b3dd5d329c8c0

**Comment by mykola-mokhnach** [comment]
Perhaps Appium server is running under different user account, which does not have permissions there?

**Comment by jbruckne** [comment]
As I mentioned in the details, the Appium server is run under the same user account that we were able to run the aapt command.

**Comment by jbruckne** [comment]
We have it working using the aapt from build tools 20.0.0. Anything from build tools 23 to 27 is throwing the error.

**Comment by mykola-mokhnach** [comment]
Then the problem lies in build tools. We execute the same command for all the cases.

**Comment by jbruckne** [comment]
Can you at least confirm Appium has tested UIAutomator2 support with versions of build tools later than 20? That way I can confirm its a problem with my installation specifically.
