### ISSUE TITLE
Appium doesn't find a element in iOS modal window

### ISSUE THREAD

**Issue by DiogoMiranda** [appium/appium#10047]
I am having an issue while automating iOS app via appium. The problem I am facing is our app have some modals windows. My suspicion is, Appium doesn't find any element in iOS modal window. If some one can suggest on how to switch to interact with that modal window, it would be really helpful. I did send a print of one window, what is possible seen  Accessibility Inspector doesn't  find an elements, for exemplo button or text on window.

Appium v1.7.1
platformName = "iOS"
platformVersion = "11.2"
deviceName = "iPhone 6"
Xcode = “9.2”

<img width="344" alt="screen shot 2018-01-20 at 10 10 32 am" src="https://user-images.githubusercontent.com/13684104/35183268-399fdff4-fdca-11e7-8072-6efe263b14b8.png">

<img width="364" alt="screen shot 2018-01-20 at 10 10 09 am" src="https://user-images.githubusercontent.com/13684104/35183273-3fe3c858-fdca-11e7-9f06-9768c96c276e.png">

<img width="557" alt="screen shot 2018-01-20 at 9 51 10 am" src="https://user-images.githubusercontent.com/13684104/35183232-a719b498-fdc9-11e7-9552-f47e32be4aca.png">

<img width="1277" alt="screen shot 2018-01-20 at 9 43 42 am" src="https://user-images.githubusercontent.com/13684104/35183234-ae4554ca-fdc9-11e7-820a-92f92e3fcd8e.png">

<img width="530" alt="screen shot 2018-01-20 at 10 09 24 am" src="https://user-images.githubusercontent.com/13684104/35183263-10839f02-fdca-11e7-8869-4ba09342bf36.png">

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/facebook/WebDriverAgent/issues

**Comment by IsaiaSilva** [comment]
Existe alguma solução? seja alternativa? mykola-mokhnach fechou, mas não vi o feedback de solução ou não.
