### ISSUE TITLE
Android Uiautomator2 has issues identify webElements but Uiautomator1 works

### ISSUE THREAD

**Issue by Erdelee** [appium/appium#10040]
## Environment
* Appium version (or git revision) that exhibits the issue:  1.7.2  with UiAutomator2
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: mac 10.11.6
* Node.js version (unless using Appium.app|exe): v8.9.1
* Mobile platform/version under test:  7.1.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Details
I run tests on an android app. The dom information is in the attachment. Using Uiautomator1, appium is able to identify elements within the "android.widget.ListView". But with Uiautomator2, it could find element the one I highlighted in red but not below that level.
![screen shot 2018-01-19 at 12 05 55 pm](https://user-images.githubusercontent.com/3970012/35170726-0c246d60-fd16-11e7-831f-7d15e7469142.png)

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
I believe it's an issue of the framework itself rather something, that we can change in Appium.

**Comment by Erdelee** [comment]
But when I switch to uiautomator1,  appium could find the elements below the part I highlighted with red. Nothing else changes.

**Comment by mykola-mokhnach** [comment]
[Here](https://github.com/appium/appium-uiautomator2-server) you can find the source of UIA2 server. Try to debug xml tree building with your app to figure out why it does not work as expected.

**Comment by vbhupalam7** [comment]
is there a limitation on uiautomator2 that it's unable to traverse beyond a certain level, seems like that's the problem this user is facing as uiautomator1 is able to identify the same element with the exact same XPath @mykola-mokhnach

**Comment by Erdelee** [comment]
@mykola-mokhnach I don't quite understand what I should do here. Here is my personal email mollyche@hotmail.com. Can you share yours with me? I can send you the whole xml layout of the page I have issues. Thanks.
