### ISSUE TITLE
Unable to click button on android 8.1.0

### ISSUE THREAD

**Issue by raz197** [appium/appium#10053]
## The problem

Unable to click a button which is visible on the application, tried the following:

MobileElement el1 = (MobileElement) driver.findElementById("com.ttt.LLLLL.sit:id/btnContinue");
el1.click();

driver.findElement(By.id('com.ttt.LLLLL.sit:id/btnContinue')).click()

driver.findElement(By.xpath("//android.widget.Button[@text='CONTINUE']")).click()

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: macOS 10.12.5 macOS Sierra
* Node.js version (unless using Appium.app|exe): 8.9.3
* Mobile platform/version under test: Android 8.1.0
* Real device or emulator/simulator: Pixel 2 XL
* Appium CLI or Appium.app|exe: Appium CLI

## Details
Script is starting the appium server, launching the app, starting the activity but fails at the very first user interaction with the app (click Continue button) and throws the following exception

 java.lang.NoClassDefFoundError: org/openqa/selenium/internal/HasIdentity
 
Same test runs fine on an iPhone 6s with iOS 9.3

## Link to Appium logs

https://gist.github.com/raz197/7a175e80d137983441ec50f0ef0989dc.js

## Code To Reproduce Issue [ Good To Have ]

   // set capabilities and appium URL
   DesiredCapabilities capa = new DesiredCapabilities()
   URL appiumUrl = new URL(System.properties["appiumUrl"])

   capa.setCapability("platformVersion" , "8.1.0")
   capa.setCapability("deviceName"      , "Pixel 2 XL")
   capa.setCapability("app"             , "/Users/QAE2/Documents/raz/LLLLLRCv1.3.0_4221QA.apk")
   capa.setCapability("appWaitActivity" , "com.ttt.ccc.presentation.start.ConfigActivity")
   capa.setCapability("automationName" , "UiAutomator2")

   driver = new AndroidDriver(appiumUrl, capa)

   println("Running on Android, going to click Continue...")
   sleep 4000

MobileElement el1 = (MobileElement) driver.findElementById("com.ttt.LLLLL.sit:id/btnContinue");
el1.click();

//driver.findElement(By.id('com.ttt.LLLLL.sit:id/btnContinue')).click()

//driver.findElement(By.xpath("//android.widget.Button[@text='CONTINUE']")).click()

**Comment by raz197** [comment]
Closing the issue as there was a problem with dependencies in pom.xml. 
I went through all dependencies in pom.xml and updated them to use the latest versions and it seems to have done the trick. 
Thanks

**Comment by Farook786** [comment]
Hi,
Am using Pixel 3 device and have used uiautomator2 capability, but the app is not launching for me and it throws an error like "An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET".
Please help me to resolve this issue
Capabilities Used :
capabilities.setCapability("newCommandTimeout", 600);
capabilities.setCapability("launchTimeout", 90000);
capabilities.setCapability("automationName", "uiautomator2");
capabilities.setCapability("deviceName", "Pixel 3");
capabilities.setCapability("platformVersion", "9");
capabilities.setCapability("platformName", "Android");
capabilities.setCapability("app", app.getAbsolutePath());
capabilities.setCapability("appPackage", "com.mobile.dev");
capabilities.setCapability("appActivity", "com.mobile.activity.MainActivity");
