### ISSUE TITLE
iOS platform: Screenshots are not honored in landscape mode(rotation issue)

### ISSUE THREAD

**Issue by AutomationInine** [appium/appium#10057]
For iOS 10.2 device, the screenshots are not capturing in landscape mode(rotation issue)

Environment:

Appium Version: Appium v1.7.2
MacOS : 10.13.2
Xcode: 9.2
Device: iPad Pro
iOS: 10.2
JavaClient: 5.0.4

Capabilities Used:

 DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("preventWDAAttachments", false);
        capabilities.setCapability("platformName", "ios");
        capabilities.setCapability("automationName", "XCUITest");
        capabilities.setCapability("realDeviceLogger", "idevicesyslog");
        capabilities.setCapability("platformVersion", "10.2");
        capabilities.setCapability("fullReset", false);
        capabilities.setCapability("useNewWDA", true);
        capabilities.setCapability("noReset", true);
        capabilities.setCapability("clearSystemFiles", true);
        capabilities.setCapability("xcodeOrgId", "xxxxxxxxx");
        capabilities.setCapability("xcodeSigningId", "iPhone Developer");
        capabilities.setCapability("deviceName", "xxxx iPad");
        capabilities.setCapability("deviceOrientation","landscape")
        capabilities.setCapability("newCommandTimeout", 100);
        capabilities.setCapability("udid", "bbbb");
        capabilities.setCapability("app", "");
        return capabilities

Screenshotcode: 

BufferedImage takeScreenshot() 
{ 
     BufferedImage bufferedImage = null 
     Debug.setDebugLevel(3) 
      if (driver != null) { 
       File scrFile = driver.getScreenshotAs(OutputType.FILE) 
   try { 
       bufferedImage = ImageIO.read(scrFile) 
    } 
   catch (IOException e) 
  { 
       e.printStackTrace() 
} 
} 
  else 
{ 
  throw new ElementNotVisibleException("Element not found - ") 
} 
return bufferedImage 
}

Server logs can be found here : https://gist.github.com/AutomationInine/446695aaf48d5a6af44cf289859fe4f8
Below is the Screenshot for your reference
![test](https://user-images.githubusercontent.com/33665019/35278837-39363f6e-0071-11e8-95fc-436a9bb54c5b.png)

**Comment by mykola-mokhnach** [comment]
Do you have the same problem if you replace WebDriverAgent source with master branch of https://github.com/appium/WebDriverAgent ?

**Comment by AutomationInine** [comment]
@mykola-mokhnach, i didn't try the option, tomorrow i will test and let you know. thank you.

**Comment by AutomationInine** [comment]
@mykola-mokhnach , i replaced the WebDriverAgent project with master branch  and built the xcode project and observed rotation issue still occurring.

**Comment by mykola-mokhnach** [comment]
Please try the patch from https://github.com/appium/WebDriverAgent/pull/42

there are for sure more things there, which work differently on iPad Pro and other models, but I don't have time to investigate them.

**Comment by AutomationInine** [comment]
@mykola-mokhnach Thank you for the time on investigating the issue.
I replaced the WebDriverAgent source code with https://github.com/appium/WebDriverAgent/tree/ipad_pro_screen (branch) . I am still facing the rotation issue. 

Server logs can be found at below URL https://gist.github.com/AutomationInine/cc34f5844f49a21d761a9df64caeaa5f 

I am able to take the right screenshot, when appium@1.7.2-beta2 on XCUITestDriver (v2.59.0) version , but i am not able to switch back to the same version when i revert to the appium@1.7.2-beta2. 

Could you help me,  how to switch back to the XCUITestDriver (v2.59.0)  version. Thank you Once again.

**Comment by mykola-mokhnach** [comment]
What is the screen size of your iPad?

**Comment by mykola-mokhnach** [comment]
Also make sure you delete the WDA binary from the device and cleanup Xcode derived data after the source is replaced, since it is cached by default.

**Comment by AutomationInine** [comment]
@mykola-mokhnach , the screen size is 2048x1536 pixels and 1024x768 points. 

Sure I will try once again as you suggested

**Comment by mykola-mokhnach** [comment]
This might be a problem, since iPad Air 2 has the same screen size and I cannot reliably determine the device modes and must rely on screen size. The  [current algorithm](https://github.com/appium/WebDriverAgent/pull/42/files#diff-0ab716f2e5cda5dc12cbf76f520d5883R94) defines the device as iPad Pro if it is a tablet and either display width or height is greater than 1024 px. I'd be happy to apply more advanced algorithm if you know such.

**Comment by Joskony** [comment]
I'm having exactly the same issue here. But I'm using the simulator provided on XCode and am mostly using an iPhone SE with iOS 9.3. Taking screenshots for android works as expected, but for a while iOS has been acting up without doing any changes to the screenshot logic. It works in landscape mode for an iPhone X with iOS 11.2. My code for taking the screenshot is similar and so are my capabilities for the device, I have less, since I'm on a simulator. If there is anything I can provide, tell me.

Appium Version: Appium v1.7.2
MacOS : 10.12.6 
Xcode: 9.2
Device: iPhone SE (Simulator)
iOS: 9.3
JavaClient: 6.0.0-BETA2

**Comment by mykola-mokhnach** [comment]
I've just tried different simulator types and the screenshots were ok with Appium and the current algorithm. However, the screenshot is rotated if I execute an integration test from Xcode with exactly the same source and exactly on the same simulator model. I really don't know what can be done there and to workaround XCTest issues that Apple put there with non-default screen orientation. you could try to investigate the problem yourself and propose a PR if you can find a better solution.

**Comment by mykola-mokhnach** [comment]
I'd also try to upgrade the device to iOS11. This might help

**Comment by AutomationInine** [comment]
@mykola-mokhnach , the screenshot logic is well working with iOS 11 devices. 

Thank you for helping . 

sorry for asking an irrelevant question here , 
I am able to take the right screenshot, when appium@1.7.2-beta2 on XCUITestDriver (v2.59.0) version , but i am not able to switch back to the same version of XCUITestDriver when i revert to the appium@1.7.2-beta2.

Could you help me, how to switch back to the XCUITestDriver (v2.59.0) version. Thank you Once again.
