### ISSUE TITLE
Real iOS Device - Interaction with popups

### ISSUE THREAD

**Issue by Gnanaraj-S** [appium/appium#10054]
When user logged into my application they will be having an option to enable location service or skip it. When user clicks on enable location service button it will give a popup having two buttons Allow and Ignore. Hitting allow will turn on the location service. The problem is I'm not able to interact with popups in real device. But for the same app I can able to interact with the popups in Simulators. 

In Real iOS device - Appium Inspector says Interactions are not available for this element(in terms of popup).
Via code also I tried, it threw me NoSuchElement Exception(Expected as it was not able to interact in Appium Inspector). 

* Appium version (or git revision) that exhibits the issue: V1.7.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MAC OS High Sierra
* Node.js version (unless using Appium.app|exe): 
* Mobile platform/version under test: iOS/10.3.3
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe:

Is this expected in Real devices? I think it is definitely a good feature to have.

**Comment by mykola-mokhnach** [comment]
It's known XCTest limitation. Please report the issue to Apple.

**Comment by Gnanaraj-S** [comment]
Raised a bug here https://bugreport.apple.com/web/?problemID=36779838

**Comment by Gnanaraj-S** [comment]
@mykola-mokhnach - I see the following code works fine in iOS 11 but not working in iOS 10.

@iOSFindBy(accessibility = "Always Allow")
 private MobileElement popupalwaysAllow;

popupalwaysAllow.click();


Any idea why it is not working with iOS 10 when it works fine with iOS 11?

**Comment by mykola-mokhnach** [comment]
No idea. It's rather a question to Apple engineers.
