### ISSUE TITLE
How to instantiate ios driver to use its methods in Qmetry framework

### ISSUE THREAD

**Issue by myProwess** [appium/appium#10050]
Hi folks,

I am currently using the command `QAFExtendedWebdriver mydriver = getQAFDriver();`

**It will store current driver in "mydriver" object so i can access its available methods.**

Now i need to create a new driver object within the  current session itself to access IOSDriver specific methods.
`IOSDriver<WebElement> driver= new IOSDriver<WebElement> (url, capabilities);`

How to get current session **url**, **capabilities** to pass as parameters.

Its not working out for me. Any inputs will help me a lot

**Comment by mykola-mokhnach** [comment]
`driver.getCapabilities()` ?

Please use Appium forum to ask questions.
