### ISSUE TITLE
Appium 1.8.0-beta: Unable to parse remote response: 'deviceName' can't be blank on driver creation

### ISSUE THREAD

**Issue by vjmaiky** [appium/appium#10055]
## The problem
org.openqa.selenium.WebDriverException: Unable to parse remote response: 'deviceName' can't be blank on driver creation

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0-beta
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2
* Desktop OS/version used to run Appium: MacOS Sierra 10.12.6
* Node.js version (unless using Appium.app|exe): 8.5.0
* Mobile platform/version under test: iOS 10.3.3
* Real device or emulator/simulator: Real Device (iphone 6+)

## Details
I create AppiumDriverLocalService and after that ios driver. When capabilities are parsed i get : org.openqa.selenium.WebDriverException: Unable to parse remote response: 'deviceName' can't be blank

## Link to Appium logs
https://gist.github.com/vjmaiky/07b4dc34049c02bc4b13d52cbab48626

**Comment by vjmaiky** [comment]
I read a bit and it has something with default/desired caps.
I moved deviceName in servers capabilities:
```

service = AppiumDriverLocalService
                .buildService(new AppiumServiceBuilder()
                       etc
                        **.withCapabilities(getCapabilities())**
                       etc
```

but still not working:

```
BaseDriver] ["automationName","deviceName"] are not standard capabilities and should have an extension prefix
[Appium] The following capabilities were provided in the JSONWP desired capabilities but
          not the W3C capabilities: ["app","clearSystemFiles","commandTimeouts","platformVersion","resetOnSessionStartOnly","udid","useNewWDA","wdaConnectionTimeout","wdaLocalPort"]
Jan 23, 2018 2:13:57 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
01-23-2018 14:14:01 - [api.apps.inflightiOS.workarounds.Workarounds / skipLoginmethod][INFO ] - Unlock the app to start testing
01-23-2018 14:14:01 - [api.apps.inflightiOS.pincode.PinCode / clickSetupLaterPin][INFO ] - Click on Setup Pin later from create a pin code page
Jan 23, 2018 2:14:01 PM org.openqa.selenium.support.ui.ExpectedConditions findElement
WARNING: WebDriverException thrown by findElement(By.id: Setup Later)
org.openqa.selenium.json.JsonException: Unable to convert: Locator Strategy 'css selector' is not supported for this session
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T18:33:54.468Z'
System info: host: 'Lucian.local', ip: '172.16.118.47', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_144'
```

**Comment by KazuCocoa** [comment]
I'm not sure Java client but it looks W3C create session stuff.

Current master branch can fallback to previous `create session`(as same as 1.7.2), and it can work with current your Java client, I guess.

**Comment by mykola-mokhnach** [comment]
I believe it's a problem in Java client

**Comment by mykola-mokhnach** [comment]
try to add `appium:` prefix to non-native caps and check if it works

**Comment by mykola-mokhnach** [comment]
@dpgraham What do you think?

**Comment by mykola-mokhnach** [comment]
BTW

> org.openqa.selenium.json.JsonException: Unable to convert: Locator Strategy 'css selector' is not supported for this session

is for sure on the client side. I've create a [prototype](https://github.com/appium/java-client/pull/817) for a fix, but this will anyway require some time. You could also contribute and test it.

**Comment by vjmaiky** [comment]
after adding appium: prefix works but remains the second problem : 
```
Jan 24, 2018 12:06:01 PM org.openqa.selenium.support.ui.ExpectedConditions findElement
WARNING: WebDriverException thrown by findElement(By.id: Setup Later)
org.openqa.selenium.json.JsonException: Unable to convert: Locator Strategy 'css selector' is not supported for this session
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T18:33:54.468Z'
```

**Comment by mykola-mokhnach** [comment]
It's for sure on java client side, Please move to https://github.com/appium/java-client/issues

**Comment by newthomas** [comment]
Interesting, that this gets closed. Works for me with Appium 1.7.2 and Java Client 6.0.0-BETA2, but doesn't work with Appium 1.8.0-beta.

**Comment by manikantagithub** [comment]
Thanks for ur help. I have the same problem "Exception in thread "main" org.openqa.selenium.InvalidArgumentException: 'deviceName' can't be blank" 

So, I downgraded java-client form  5.0.4 to 5.0.0-BETA9.  Appium v1.8.0-beta. It's working for me.
