### ISSUE TITLE
[Inspector] Could not obtain screenshot: [object Object]

### ISSUE THREAD

**Issue by raz197** [appium/appium#10061]
## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: macOS Sierra 10.12.5
* Node.js version (unless using Appium.app|exe): 8.9.3
* Mobile platform/version under test: 7.0
* Real device or emulator/simulator: Samsung Galaxy S8 Real device
* Appium CLI or Appium.app|exe: app

## Details
Appium inspector starts and gets the very first screen shot of the landing page, as soon as app is refreshed or navigate to another page, it comes up with the "Could not obtain screenshot: [object Object]" message but in the App Source pane of the inspector, code is refreshed and I can traverse through the tree and see the objects.

Screenshot capture from my tests are working fine. I have tried to 

1. Launch the appium server from command line and connect the desktop app to running server and then start inspector
2. Start the server from desktop app and launch inspector

Both result in the same error 

## Link to Appium logs
https://gist.github.com/raz197/91217720fe2d241a6c0c63d9fd729c0c.js

**Comment by mykola-mokhnach** [comment]
The attached log is impossible to read. Have you tried to capture the screenshot manually using screencap utility at the same screen? Did it work?

**Comment by raz197** [comment]
Uploaded the full log here

https://gist.github.com/raz197/e5234de11d705c0bad9ead03baebb183.js

I'm using the following code to capture a screenshot in case of a failure (in my test) and it captures the screenshot of the screen without any problem, it's only the Appium Inspector giving the error.

Code for capturing screenshot:

File scrFile = ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE);
FileUtils.copyFile(scrFile, new File("reports/fail-"+ TEST_CASE +  "-" + DateToStr  +".png"))

**Comment by mykola-mokhnach** [comment]
Can you check the content of the generated /data/local/tmp/screenshot.png file or the file, which was pulled to the temp folder? Is it really a valid png file?

**Comment by raz197** [comment]
Sorry for the late reply, it's a file with 0 size so not a valid file.

**Comment by mykola-mokhnach** [comment]
I'd assume this is not a problem in Appium then. Perhaps, the application under tests prevents screenshoting or there are some internal problems with screencap utility.
