### ISSUE TITLE
appium uiautomator2 find toast sometimes not work

### ISSUE THREAD

**Issue by FuckyouBB** [appium/appium#10062]
## The problem

appium now use uiautomator2 can find toast by find xpath "//*[@text=""]", it works , start session ,the first time to find toast always success, but then when i find the new toast ,it sometimes unable, it happened very frequently,  it's uiautomator2's bug?  now  i have to click button pop the toast many times until appium can find.

## Environment

* Appium version :1.7.2
* osx: 10.12
* Android:7.0
* Appium-Python-Client==0.26

**Comment by mykola-mokhnach** [comment]
@vmaxim Any ideas on this?

**Comment by vmaxim** [comment]
1. You are too fast and have to wait for the toast element
2. You are too slow and can not find the toast element before it's wiped (lifetime 3500 ms)
