### ISSUE TITLE
using appium 1.7.1, with fullReset to true, fail to re-install the app when new a session on real iphone device

### ISSUE THREAD

**Issue by helenren** [appium/appium#10065]
## The problem

i setup fullReset capability to true when new a session agains a real iphone device, the existing app got remove successfully, while fail to re-install my app. It complain the bundle id is unknow: [MJSONWP] Encountered internal error running command: Error: App with bundle identifier 'xxxxx' unknown. 

## Environment

* Appium version (or git revision) that exhibits the issue:1.7.1
* Last Appium version that did not exhibit the issue (if applicable): don't know
* Desktop OS/version used to run Appium: osx 10.13.2 
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: 11.0
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

**Comment by mykola-mokhnach** [comment]
One should provide full path to the app package in capabilities if fullReset is set to true.
