### ISSUE TITLE
Error while launching edge app using appium

### ISSUE THREAD

**Issue by sushantpatil39** [appium/appium#10063]
## The problem

I want to launch edge browser app using selenium hub grid architecture and appium.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Desktop OS/version used to run Appium: Window 8
* Node.js version (unless using Appium.app|exe):  v8.9.3
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real device

## Details

I want to launch edge browser app on android device using c# through selenium grid hub topology.
I created hub and appium node which registering node to hub. But while executing test case I got exception. This exception occurs due to passed capability.

So what is the capability for edge browser app and what is the exact value for property "browserName".

## Link to Appium logs
#Error
An unknown server-side error occurred while processing the command. Original error: The desired capabilities must include either an app, appPackage or browserName

## Code To Reproduce Issue [ Good To Have ]
Used capability for node creation-
  "platform":"ANDROID",
		 "browserName":"MicrosoftEdge",
		 "deviceName": "abc",
		 "platformVersion": "7.0"

Code in c#:
Capabilities.Add("platformName", "Android");
            Capabilities.Add("platformVersion", "7.0");
            Capabilities.Add("browserName", "MicrosoftEdge");
            Capabilities.Add("deviceName", "abc");
            DesiredCapabilities tttt = new DesiredCapabilities(Capabilities);           
            AndroidDriver<IWebElement> driver = new AndroidDriver<IWebElement>(new Uri("http://1.2.3.4:4444/wd/hub"), tttt, new TimeSpan(0, 3, 0));

**Comment by mykola-mokhnach** [comment]
This error is expected. Only chrome browser is supported.
