### ISSUE TITLE
W3C protocoled error message is text/html against no element found

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#10075]
## The problem

When I tried to check error handling, I found clients get `text/html` formatted message, not `application/json` when no element error raised. If anyone handles error against no element, upgrading to W3C protocol will break such test cases. (I haven't confirmed other 40x error messages)

- worked branch: https://github.com/KazuCocoa/ruby_lib_core/tree/get-response-no-element
- action:
    ```
    # After launching appium
    @@driver.find_element :id, "h" # Should return no element error
    ```

## MSJONWP
- Server log
    ```
    [debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/1756E1B1-16FB-497E-A156-FFF5764A9014/element] with body: {"using":"id","value":"h"}
    [debug] [JSONWP Proxy] Got response with status 200: {"value":{"using":"id","value":"h","description":"unable to find an element"},"sessionId":"1756E1B1-16FB-497E-A156-FFF5764A9014","status":7}
    [HTTP] <-- POST /wd/hub/session/a0e29d11-d63f-4b2e-86d1-52be02a7ae2b/element 500 30508 ms - 164
    [HTTP] --> GET /wd/hub/status {}
    ```
- The client log against the response at https://github.com/KazuCocoa/ruby_lib_core/commit/341a8077c297bca1d8b191aeb7259413ac983fb7#diff-7415632216871f3c4ea797d9c0f37eadR20 (Saw the response body directory)
   ```
    "{\"status\":7,\"value\":{\"message\":\"An element could not be located on the page using the given search parameters.\"},\"sessionId\":\"e6a57d32-b6a8-4c56-b4b2-92b99b8c0539\"}"
    ```

## W3C protocol
- Server log
    ```
    [debug] [BaseDriver] Waited for 29773 ms so far
    [debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/59DF188D-7F4C-42C4-BFEC-2A6AAC3091E3/element] with body: {"using":"id","value":"h"}
    [debug] [JSONWP Proxy] Got response with status 200: {"value":{"using":"id","value":"h","description":"unable to find an element"},"sessionId":"59DF188D-7F4C-42C4-BFEC-2A6AAC3091E3","status":7}
    [HTTP] <-- POST /wd/hub/session/2663ff7b-1246-4e34-9049-739b96bd9254/element 404 30447 ms - 78
    [HTTP] --> GET /wd/hub/status {}
    [debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
    ```
- The client log against the response at https://github.com/KazuCocoa/ruby_lib_core/commit/341a8077c297bca1d8b191aeb7259413ac983fb7#diff-7415632216871f3c4ea797d9c0f37eadR20 (Saw the response body directory)
    - content_type is "text/html" <= **should be `application/json` as well as MJSONWP**
    - The response body was: (not JSON) <= **should be JSON format as well as MJSONWP**
    ```
    "An element could not be located on the page using the given search parameters."
    ```

Thus, the client failed to handle the response.
HTTP Status code looks expected, but the body should be JSON from https://github.com/jlipps/simple-wd-spec#error-handling

I guess we should take a look at base-driver, but I have no concrete idea yet.
Do you have any idea where should we fix?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0-beta
* Last Appium version that did not exhibit the issue (if applicable): no.
* Desktop OS/version used to run Appium: macOS 10.13.2
* Node.js version (unless using Appium.app|exe): v9.3.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI and ruby_lib_core

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Error response should be json format

**Comment by KazuCocoa** [comment]
cc @imurchie @mykola-mokhnach @dpgraham

**Comment by dpgraham** [comment]
There's a fix in this for master. I'm going to add a test for it too.

@imurchie we should realize a new beta today.
