### ISSUE TITLE
An unknown server-side error occurred while processing the command. Original error: ENOENT: no such file or directory, scandir '/usr/local/Caskroom/android-platform-tools/27.0.1/platform-tools/build-tools' (Selenium::WebDriver::Error::UnknownError)

### ISSUE THREAD

**Issue by malikgaurav** [appium/appium#10071]
## The problem
I am new to mobile testing, so please help out, the build-tool directory is wrong on Appium server even though bash_profile says different. I do not know were is this value getting overwritten !!

## .Bash_profile
<img width="1208" alt="screen shot 2018-01-25 at 2 31 02 pm" src="https://user-images.githubusercontent.com/29447426/35379729-0bcd50d6-01dd-11e8-8cf5-fce2b3b1b1e5.png">

## Link to Appium logs

<img width="634" alt="screen shot 2018-01-25 at 2 34 11 pm" src="https://user-images.githubusercontent.com/29447426/35379702-f28d4766-01dc-11e8-8d42-8ea12358262d.png">

**Comment by mykola-mokhnach** [comment]
Most likely your platform tools installation is broken. Check if ANDROID_HOME env variable is pointing to a proper folder.
