### ISSUE TITLE
Unable to launch on Real device - Error: Unknown device or simulator UDID: 'XXXXXXXXXXX'

### ISSUE THREAD

**Issue by srinivasvishnubhotla** [appium/appium#10078]
## The problem

Unable to recognize the real device using appium. I am able to run the cases using the appium desktop. This issue only happens when I try to start Appium from the command line. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Desktop OS/version used to run Appium: Mac 
* Node.js version (unless using Appium.app|exe): 4.2.0 
* Mobile platform/version under test: iOS 11.2.2 
* Real device or emulator/simulator: Real Device (iPhone 7)
* Appium CLI or Appium.app|exe:

## Details
My tests run well when i start the server from the appium desktop but fail to recognize the device when i start the appium server programmatically. 

i have installed libimobiledevice using homebrew already
'brew install libimobiledevice --HEAD'.
I checked with  'xcrun simctl list' and my device is not listed in there also. 

## Link to Appium logs
Error: Unknown device or simulator UDID: 'ZZZZZ'
    at XCUITestDriver.determineDevice$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:622:17)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Unknown device or simulator UDID: 'ZZZZZ'

## Code To Reproduce Issue [ Good To Have ]

capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "");
capabilities.setCapability(MobileCapabilityType.APPIUM_VERSION, "1.7");
capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "11.2.2");
capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME,"iOS");
capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "XXXXXX");
capabilities.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());		capabilities.setCapability("newCommandTimeout", 2000);
capabilities.setCapability(MobileCapabilityType.UDID, "ZZZZZ");
capabilities.setCapability("xcodeOrgId","aaaaaa");
capabilities.setCapability("xcodeSigningId","iPhone Developer");
capabilities.setCapability("updatedWDABundleId","com.cccccc.WebDriverAgentRunner");	

builder = new AppiumServiceBuilder();
builder.withIPAddress("127.0.0.1");
builder.usingPort(4723);
builder.withCapabilities(capabilities);
builder.withArgument(GeneralServerFlag.SESSION_OVERRIDE);
builder.withArgument(GeneralServerFlag.LOG_LEVEL,"error");

service = AppiumDriverLocalService.buildService(builder);
service.start();
	 	
mobiledriver = new IOSDriver<>(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);

**Comment by mykola-mokhnach** [comment]
Do not set browser name if app capability is set. Also, it is not needed to set device name if udid is set. You can check the list of connected device ids by running `idevice_id -l` command.

Full server log would be more helpful though.
