### ISSUE TITLE
iOS App opens and immediately closes randomly

### ISSUE THREAD

**Issue by picklelv** [appium/appium#10085]
## The problem

iOS App opens and immediately closes.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2-beta2 & 1.8.0-beta
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: N/A
* Node.js version (unless using Appium.app|exe): 7.2.1
* Mobile platform/version under test: 11.1
* Real device or emulator/simulator: Simulator
* WebdriverIO: 4.6.2
* [wdio-appium-service](https://github.com/rhysd/wdio-appium-service): 0.2.3

## Details

After a full laptop reboot, the first test runs fine.  The sim starts, app is installed, app is opened and the test runs.  Subsequent test runs _might_ show the behavior of app opening and immediately closing, but it's random.  If we `Ctrl+C` a test, the next test run will almost always open the iOS app and then immediately close it.  

`fullReset` doesn't solve the problem.  We have tested a few combinations of `fullReset` & `noReset`.

A laptop reboot always solves the problem.  I have tried to manually kill `xcodebuild`.   Any other processes that would be left around that need to be cleaned up?

## Link to Appium logs

https://gist.github.com/picklelv/dde9efa5fd412898a421aab93956c467

**Comment by mykola-mokhnach** [comment]
The app under test might crash. Check the device logs for more details.

We do cache WDA instance to improve performance, however you could set `useNewWDA` capability to `true` if this is an undesired behaviour.

**Comment by picklelv** [comment]
I just started looking through the sim log, but wanted to go ahead and attach it here.

https://gist.github.com/picklelv/18e7f40a21e6669bc4f4467052f071f5

**Comment by mykola-mokhnach** [comment]
This log does not contain any useful information. Try to get the one returned by `'xcrun simctl spawn booted log stream --style compact` command

**Comment by picklelv** [comment]
https://gist.github.com/picklelv/73ac26f51f7c42ed4ebbc2666ab97733

**Comment by mykola-mokhnach** [comment]
I don't see any traces of the app or WebDriverAgent bundle identifiers in the log. Are you sure it's the one we need?
