### ISSUE TITLE
Appium is launching app on Simulator but cannot execute any commands

### ISSUE THREAD

**Issue by dhpatel15** [appium/appium#10082]
## The problem
Hi,
I am running into an error when starting the test run. Everything installed without any error messages. The app boots up, but after that I cannot execute ant commands. If I don't set the the newCommandTimeout to 0, then the scripts test running.  

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Desktop OS/version used to run Appium: macOS Sierra (10.12.6)
* Node.js version (unless using Appium.app|exe): 8.6.0
* Mobile platform/version under test:  iPhone 6 Simulator  iOS 11
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/dhpatel15/e60a07533d5abe6d495051cce7be338e

**Comment by dhpatel15** [comment]
I have also tried, Mobile platform/version under test: iPhone 6 Simulator iOS 9, and I still get the same results. I am using Xcode Version 9.0

**Comment by imurchie** [comment]
The Appium server is not receiving any commands after starting the session. What are you trying to do? What is your test script like?

**Comment by dhpatel15** [comment]
const wdio = require('webdriverio');

const options = { 
	port: 4723,
  	desiredCapabilities: { 
  		platformName: "iOS",
	    platformVersion: "11.0",
	    deviceName: "iPhone 6",
	    app: "/Users/devp/Library/Developer/Xcode/DerivedData/PeerLink-ayuucxwzzpovvkcnmwlwlnmtvgsd/Build/Products/Release-iphonesimulator/PeerStrong.app",
	    automationName: "XCUITest",
	    newCommandTimeout: 0,
}};

const driver = wdio.remote(options);
driver.init();
driver.touchPerform({
  		action: 'tap',
  		options: {
    		element: driver.element("~login")
  		}
	});
let email = driver.element("~email");
email.setValue("nrmgkgmrkm");
driver.end();

**Comment by imurchie** [comment]
Does `driver.init();` ever return?

**Comment by dhpatel15** [comment]
No. How can I set it to return?

**Comment by imurchie** [comment]
It _should_ return. The server logs indicate that the next line is not running. Or at least it never initiates a request. So I'm wondering if it is run or what.

**Comment by dhpatel15** [comment]
If I  run this script,
const options = { 
  port: 4723,
  desiredCapabilities: { 
    platformName: "iOS",
    platformVersion: "11.0",
    deviceName: "iPhone 6",
    app: "/Users/devp/Library/Developer/Xcode/DerivedData/PeerLink-ayuucxwzzpovvkcnmwlwlnmtvgsd/Build/Products/Release-iphonesimulator/PeerStrong.app",
    automationName: "XCUITest",
    newCommandTimeout: 0,
}};

const driver = wdio.remote(options);

Nothing happens.
But if I run

const options = { 
  port: 4723,
  desiredCapabilities: { 
    platformName: "iOS",
    platformVersion: "11.0",
    deviceName: "iPhone 6",
    app: "/Users/devp/Library/Developer/Xcode/DerivedData/PeerLink-ayuucxwzzpovvkcnmwlwlnmtvgsd/Build/Products/Release-iphonesimulator/PeerStrong.app",
    automationName: "XCUITest",
    newCommandTimeout: 0,
}};

const driver = wdio.remote(options);
driver.init();

The simulator opens up, it does into the WebDriverAgent app, and then my app. After it loads the landing page, even though there are commands after it, like touchPerform, the script stops running and i get this message.

[debug] [MJSONWP] Responding to client with driver.createSession() result: {"webStorageEnabled":false,"locationContextEnabled":true,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"handlesAlerts":true,"rotatable":true,"platformName":"iOS","platformVersion":"11.0","deviceName":"iPhone 6","app":"/Users/devp/Library/Developer/Xcode/DerivedData/PeerLink-ayuucxwzzpovvkcnmwlwlnmtvgsd/Build/Products/Release-iphonesimulator/PeerStrong.app","automationName":"XCUITest","requestOrigins":{"url":"http://webdriver.io","version":"4.10.1","name":"webdriverio"},"udid":"3A822649-B1FD-47CB-8755-E61D1BBDF7EF"}
[HTTP] <-- POST /wd/hub/session 200 11357 ms - 685 
[BaseDriver] Shutting down because we waited 60 seconds for a command
[Appium] Closing session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
[Appium] Removing session 366fd028-6a8f-4a97-bd38-bcf75b402be7 from our master session list
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [iOSLog] Stopping iOS log capture

**Comment by imurchie** [comment]
That's why I am wondering if the `init` function ever returns. The next command ought to send a request to the server, and there is no indication that such a request was ever sent. Certainly, the server does not receive it. 

So I ask again: does the `init` function return. Do you get any output on the client side if you run something like
```js
const wdio = require('webdriverio');

const options = { 
  port: 4723,
  desiredCapabilities: { 
    platformName: "iOS",
    platformVersion: "11.0",
    deviceName: "iPhone 6",
    app: "/Users/devp/Library/Developer/Xcode/DerivedData/PeerLink-ayuucxwzzpovvkcnmwlwlnmtvgsd/Build/Products/Release-iphonesimulator/PeerStrong.app",
    automationName: "XCUITest",
    newCommandTimeout: 0,
}};

const driver = wdio.remote(options);
driver.init();
console.log('driver.init(); returned. Performing touch action');
driver.touchPerform({
  action: 'tap',
  options: {
    element: driver.element("~login")
  }
});
let email = driver.element("~email");
email.setValue("nrmgkgmrkm");
driver.end();
```

**Comment by dhpatel15** [comment]
If I run the script about, the app opens and closes non-stop

https://gist.github.com/dhpatel15/8fb48702392fd8485bc29918b11f73c7

**Comment by imurchie** [comment]
The script I added was literally your script with a single `console.log` statement added. Can you add that statement to your script?

**Comment by dhpatel15** [comment]
I did. What exactly do you want me to show you?
The console.log statement shows up in my terminal

https://www.dropbox.com/s/yg3klwhdkfwbtfx/Screenshot%202018-01-25%2018.39.36.png?dl=0

**Comment by imurchie** [comment]
Ok. This is a problem in the usage of webdriver.io. Everything is asynchronous, but you are treating it is synchronous. So the problem that is arising is the the `driver.element("~login")` is being executed before the session is created, and it is failing.

Doing something like this should get you further:
```js
const driver = wdio.remote(options);
driver
  .init()
  .element('~login')
  .then((element) => {
    return driver.touchPerform({
      action: 'tap',
      options: {
        element,
      }
    });
  })
  .end()
  .catch((err) => {
    console.log(err);
  });
```
Or using a `click`:
```js
const driver = wdio.remote(options);
driver
  .init()
  .click('~login')
  .end()
  .catch((err) => {
    console.log(err);
  });
```

I would suggest dedicating some time to reading the docs for webdriver.io if you want to use it effectively. http://webdriver.io/guide.html

**Comment by mykola-mokhnach** [comment]
Closing as client-side issue.

**Comment by ritxart** [comment]
Im having the same issue, and everything runs OK if I use aooium localy and execute everything local. But we added a grid to be able to run tests in parallel but we see the same.. any clue?
