### ISSUE TITLE
A amout of `visible="true"` are decreased after applying appium-xcuitest-driver 2.67.0

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#10087]
## The problem

A amout of `visible="true"` are decreased after applying `"appium-xcuitest-driver": "2.67.0"`

For example, I can see the change against `XCUIElementTypeButton`.

- "appium-xcuitest-driver": "2.67.0"
 ```
 <XCUIElementTypeButton type="XCUIElementTypeButton" name="Gray" label="Gray" enabled="true" visible="false" x="239" y="146" width="125" height="47"/>
 ```
- "appium-xcuitest-driver": "2.66.0"
 ```
 <XCUIElementTypeButton type="XCUIElementTypeButton" name="Gray" label="Gray" enabled="true" visible="true" x="239" y="146" width="125" height="47"/>
 ```

The target view is:

<img src="https://user-images.githubusercontent.com/5511591/35470120-06b13206-0387-11e8-95e9-04789466af2f.png" width="200">

Do you have any idea?
The difference for WDA between them is https://github.com/appium/appium-xcuitest-driver/pull/610 .

BTW, current released Appium version is no problem.

## Environment

* Appium version (or git revision) that exhibits the issue: master and "appium-xcuitest-driver": "2.67.0"
* Last Appium version that did not exhibit the issue (if applicable): master and "appium-xcuitest-driver": "2.66.0"
* Desktop OS/version used to run Appium: macOS 10.13.2
* Node.js version (unless using Appium.app|exe): v9.3.0
* Mobile platform/version under test:  iOS 10.3
* Real device or emulator/simulator: Simulator, Xcode 9.
* Appium CLI or Appium.app|exe:

## Details

- Before running each code, I did:
    - `rm -rf node_modules`
    - `npm install`
    - Uninstall the WebDriver app from the test simulator

## "appium-xcuitest-driver": "2.67.0"

```ruby
[1] pry(#<ios/element/button>)> b = find_elements :class, 'XCUIElementTypeButton'
=> [#<Selenium::WebDriver::Element:0x6782a8b618ee2cc6 id="7783DE32-9B15-4FDF-8532-D4470C49D2AF">,
 #<Selenium::WebDriver::Element:0x149356b23a11f586 id="FAF9ED23-FB32-40E6-AAF1-6AB12E129755">,
 #<Selenium::WebDriver::Element:0x6e4d6f18d6d2f190 id="667EE118-4955-4E06-8AAC-8563FABB0960">,
 #<Selenium::WebDriver::Element:0x59151a11a470bc36 id="230E0FEB-90EC-4003-BC74-611018E9C8D7">,
 #<Selenium::WebDriver::Element:0x..fd9b68110505ecd2 id="575F72A6-6D6D-41E3-AAE5-7D7A1689945E">,
 #<Selenium::WebDriver::Element:0x..fa562c75b91fd0b68 id="8111A580-683B-4834-8E90-C6B89D763DE7">,
 #<Selenium::WebDriver::Element:0x19e7478822c58292 id="99A8A8AE-DEDB-4872-9F45-EBE4FEE3FB2E">,
 #<Selenium::WebDriver::Element:0x..fdb8befc5037e1420 id="4E2B547B-8D97-4F6D-8782-891985C7F82A">,
 #<Selenium::WebDriver::Element:0x50536d7a21022d74 id="18CF5BE2-EF3F-42A2-BB53-33D97D8C7DBA">,
 #<Selenium::WebDriver::Element:0x..fc84804a056005818 id="C931B569-B2A3-4FE8-9195-15361E5DD39B">]
[2] pry(#<ios/element/button>)> b.select(&:displayed?)
=> [#<Selenium::WebDriver::Element:0x6782a8b618ee2cc6 id="7783DE32-9B15-4FDF-8532-D4470C49D2AF">,
 #<Selenium::WebDriver::Element:0x149356b23a11f586 id="FAF9ED23-FB32-40E6-AAF1-6AB12E129755">]
```

- Full-log (include Appium server)
    - https://gist.github.com/KazuCocoa/945627e613557fc9da92d7b7c218bcba

## "appium-xcuitest-driver": "2.66.0"

```ruby
[1] pry(#<ios/element/button>)> b = find_elements :class, 'XCUIElementTypeButton'
=> [#<Selenium::WebDriver::Element:0x6af9d6fea70473e2 id="07FF6B6F-E1D6-43A5-A232-A83A491F2DD9">,
 #<Selenium::WebDriver::Element:0x..fe8b0df2c97d03f8 id="A69B2B14-A2BC-4E65-81E2-47FD2569AECD">,
 #<Selenium::WebDriver::Element:0x78fc335b80fb8dba id="40CD17B9-53B8-45C5-A3A8-4939A555A3F0">,
 #<Selenium::WebDriver::Element:0x..fa7dae979ecca5f3e id="FF41DBFB-DF03-47FA-A3EB-6E105232C082">,
 #<Selenium::WebDriver::Element:0x..f361dc00718aa7ba id="9A11B7A4-6006-420C-ADBC-1045700B5DB3">,
 #<Selenium::WebDriver::Element:0x..fbaa60a0e9940e3c id="EBAC5F3D-F197-4FC3-B0F6-7EC4526BADBE">,
 #<Selenium::WebDriver::Element:0x1f26891ec6417b82 id="20D1021F-B5D3-46E3-A8BE-72EC0429DDC4">,
 #<Selenium::WebDriver::Element:0x..fa4e29b7fba3a2d38 id="0D4EFF38-7C70-43B0-B564-2144C8A1F595">,
 #<Selenium::WebDriver::Element:0x..fc765bc8b72bb6634 id="D56ED33A-6041-4A5E-AD4C-2F011C88A9C6">,
 #<Selenium::WebDriver::Element:0x306a51d4bbb12cc2 id="2637C72C-D7ED-4C1F-A8D2-195B20A0ED01">]
[2] pry(#<ios/element/button>)> b.select(&:displayed?)
=> [#<Selenium::WebDriver::Element:0x6af9d6fea70473e2 id="07FF6B6F-E1D6-43A5-A232-A83A491F2DD9">,
 #<Selenium::WebDriver::Element:0x..fe8b0df2c97d03f8 id="A69B2B14-A2BC-4E65-81E2-47FD2569AECD">,
 #<Selenium::WebDriver::Element:0x78fc335b80fb8dba id="40CD17B9-53B8-45C5-A3A8-4939A555A3F0">,
 #<Selenium::WebDriver::Element:0x..fa7dae979ecca5f3e id="FF41DBFB-DF03-47FA-A3EB-6E105232C082">,
 #<Selenium::WebDriver::Element:0x..f361dc00718aa7ba id="9A11B7A4-6006-420C-ADBC-1045700B5DB3">]
```

- Full-log (include Appium server)
    - https://gist.github.com/KazuCocoa/945627e613557fc9da92d7b7c218bcba

The client is  https://github.com/appium/ruby_lib and its test code.
The above broke some ruby_lib test code and I noticed then.

**Comment by KazuCocoa** [comment]
@mykola-mokhnach Could you take a look at this once?

cc @imurchie

**Comment by mykola-mokhnach** [comment]
@KazuCocoa Please try to merge https://github.com/appium/WebDriverAgent/pull/40 to your local source and check the stuff again. I am currently working on this part to speed up xml source generation and to make visibility detection more precise.

**Comment by mykola-mokhnach** [comment]
@KazuCocoa Is it better in the recent beta?

**Comment by KazuCocoa** [comment]
I tried and test suite worked fine. thanks!

**Comment by mykola-mokhnach** [comment]
How about the performance of getSource call? Is it better now or the same as before?

**Comment by KazuCocoa** [comment]
I didn't measure strictly, but current performance looks (slightly) improved than before.
