### ISSUE TITLE
Unable to send element while using RSelenium

### ISSUE THREAD

**Issue by swapsha** [appium/appium#10083]
#post1<-remDr$findElement(using = 'css',  "[class = 'notranslate _5rpu']")
post1$clickElement()
post1$sendKeysToElement("Hello")

Error: Summary: UnknownError Detail: An unknown server-side error occurred while processing the command. Further Details: run errorDetails method

**Comment by dpgraham** [comment]
Do you have the Appium logs?

**Comment by swapsha** [comment]
this solved my problem:
post1<-remDr$findElement(using = 'css', "[class = 'notranslate _5rpu']")
post1$sendKeysToElement("Hello")
