### ISSUE TITLE
How running big project

### ISSUE THREAD

**Issue by wilkin07** [appium/appium#10088]
hello to everything I have a big project, I already have all planned and the functions written with python and tested and it works, the problem is the unittest that according to I read it only serves to prove indifiduales functions, and what I need is an automation that works 24 time and can return to previous functions in case of errors etc. but the unittes only tests individual functions, which I recommend for the project.

greetings.

**Comment by mykola-mokhnach** [comment]
Please use Appium forum to ask questions
