### ISSUE TITLE
Appium is launching app on Simulator instead of iOS Real Device when both are open

### ISSUE THREAD

**Issue by amitwagle** [appium/appium#10081]
## Problem
I am facing this issue especially when I tries to move from Simulator to iPAD
Though I put proper UDID and app path of iPAD , App still opens on simulator when both simulator and iPAD are open.

However when I close simulator then app opens properly on Real device.

## Environment
Appium version : 1.7.2-beta2
XCode : 9.2 
iPAD OS : 11.2.1
Mac OS : 10.13.1 (Mac OS High Sierra)
Node version : v9.3.0
Appium Desktop : 1.2.7

[IntelliJ console logs.txt](https://github.com/appium/appium/files/1665695/IntelliJ.console.logs.txt)

**Comment by mykola-mokhnach** [comment]
Do not set `browserName` capability together with `app`. Also, you can skip setting of `deviceName` if `udid` is set.

**Comment by mykola-mokhnach** [comment]
you can also try to set unique `wdaLocalPort` value for each device if these devices are located on the same machine.

**Comment by mykola-mokhnach** [comment]
> [XCUITest] Detected 1 obsolete cached process from previous WDA sessions. Cleaning up...
> [XCUITest] Failed to kill obsolete cached process '2451'. Original error: 
>     Error: Killing process 2451 failed:
>         at Array.map (<anonymous>)
>         at Promise.all.then (/usr/local/lib/node_modules/appium/node_modules/fkill/index.js:68:10)
>         at <anonymous>

This might be the problem. Although, I have no idea about why the obsolete process cannot be killed. Is it executed with sudo or as an other user?

**Comment by amitwagle** [comment]
Thanks for the reply

It is not executed with sudo or as any other user.

**Comment by mykola-mokhnach** [comment]
then try the solution with `wdaLocalPort`

**Comment by amitwagle** [comment]
I tried using wdaLocalPort but still facing same issue.

any how currently this issue is not blocking me. when I close simulator then app opens properly on Real device. I just wanted to check any setting which i though i may be missing.

Thanks

**Comment by mykola-mokhnach** [comment]
I only know the setting above. Perhaps, it's just not applied properly.

**Comment by mykola-mokhnach** [comment]
I have replaced fkill with kill, so this should work better in the next xcuitest driver release

**Comment by amitwagle** [comment]
Thanks @mykola-mokhnach
