### ISSUE TITLE
Inspector breaking after dismissing iOS popovers

### ISSUE THREAD

**Issue by kgneil** [appium/appium#10084]
## The problem

Nothing in the app is visible to the appium inspector after an iPad popup appears.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.3.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 1.7.2
* Node.js version (unless using Appium.app|exe): v8.9.4
* Mobile platform/version under test: iOS 11.2
* Xcode: 9.2
* Real device or emulator/simulator: iPad Pro (9.7-inch)
* Appium CLI or Appium.app|exe:

## Details

In the app that I work on we have several iPad Popovers. Appium works great up until the popover is dismissed (.hide()). If we refresh the page we are able to see everything again however. There is a dismiss popover region that comes with the popover feature that we have no control over. Wondering if anyone else has had this issue?

**Comment by mykola-mokhnach** [comment]
> Nothing in the app is visible

What is meaning of "nothing"? Can you attach the server log?
