### ISSUE TITLE
Xcode build fails with error code 65 because of an alert

### ISSUE THREAD

**Issue by wangtao169447** [appium/appium#10089]
## The problem

![Aaron Swartz](http://media.idownloadblog.com/wp-content/uploads/2016/06/CoySIM-No-SIM-Alerts-iPhone.png)

if there's an alert onscreen during the launch of the app, it appears not to work, when we start appium.

and it throws
[Xcode] 16:16:37.315 xcodebuild[86505:592086] -[IDETestOperationCoordinator testRunnerSession:initializationForUITestingDidFailWithError:]

[Xcode] 16:16:37.315 xcodebuild[86505:592086] Test operation failure: Failed to background test runner.

[Xcode] 16:16:37.315 xcodebuild[86505:592086] _finishWithError:Error Domain=IDETestOperationsObserverErrorDomain Code=13 "Failed to background test runner." UserInfo={NSLocalizedDescription=Failed to background test runner.} didCancel: 1

[Xcode] 

[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1517127397377 (16:16:37 GMT+0800 (CST))

[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.

[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying

## Environment

* Appium version (or git revision) that exhibits the issue:1.7.1
* Last Appium version that did not exhibit the issue (if applicable):None
* Desktop OS/version used to run Appium:10.13.1
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

**Comment by mykola-mokhnach** [comment]
Unfortunately XCTest does not provide any methods to handle such alerts. Please report the issue to Apple.
