### ISSUE TITLE
org.openqa.selenium.WebDriverException: java.net.SocketException: Connection reset error

### ISSUE THREAD

**Issue by alkaffkhanvrv** [appium/appium#10097]
I am getting this error consistently when executing my code using appium 1.7.2. The error occurs on this method  ((AndroidDriver<WebElement>) driver).pressKeyCode(AndroidKeyCode.KEYCODE_APP_SWITCH);

Java client - 5.0.4
Appium - 1.7.2
TestNG - 6.11
Device Samsung galaxy J7 (7.x version)

Attaching my appium server log
[appium-server-logs.txt](https://github.com/appium/appium/files/1676675/appium-server-logs.txt)

**Comment by mykola-mokhnach** [comment]
I don't observe any issues in the attached log. Try if it works with UIAutomator2 automation backend

**Comment by alkaffkhanvrv** [comment]
I solved this issue by downgrading the appium server to 1.7.0 still it is not working in 1.7.1 and 1.7.2

**Comment by mykola-mokhnach** [comment]
Older Appium release contains older chromedriver. Perhaps, this was the issue.

**Comment by alkaffkhanvrv** [comment]
We are not using chromedriver we are using only androiddriver.

**Comment by alkaffkhanvrv** [comment]
How can I make this work in the latest Appium version say 1.7.2. Kindly advice how to fix the issue in 1.7.2

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/blob/909694b39d8a110c50b267341b3b911be468bbae/docs/en/writing-running-appium/web/chromedriver.md

**Comment by Mayur5712** [comment]
I am also getting this error, and the problem is I am using native application in Android and running my script on laptop which is connected to mobile over USB. 
My doubt is why connection is reset though I am connected via USB

Appium Version : 1.8.0-beta3

[Appium.txt](https://github.com/appium/appium/files/1991914/Appium.txt)

**Comment by deepikashekar37** [comment]
I was getting the same error with following environment -
Appium - 1.8.2-beta
java client - 6.0.0
mac version - 10.13.4
xcode - 9.4

After upgrading java client to  6.1.0 i don't see that error.
