### ISSUE TITLE
Appium could not shows WEBVIEW but actually exists on an Android Native App

### ISSUE THREAD

**Issue by vutukuriswathi** [appium/appium#10096]
## The problem

Appium could not shows WEBVIEW but actually exists on an Android Native App
## Environment
Appium version:1.7.2
Mac os version: 10.12.6
Android version: Real device with 7.0
[appium-server-logs.txt](https://github.com/appium/appium/files/1675487/appium-server-logs.txt)

## Details

Even though the webview is present in the app,appium is not displaying webview.
## Link to Appium logs
Here I am providing the link to appium logs.

**Comment by mykola-mokhnach** [comment]
Are you sure that correct chromedriver version is selected? Have you tried to connect to the webview manually with Chrome remote debugger?

**Comment by imurchie** [comment]
When the webview is visible, can you run the following and post the results?
```
/Users/gunuputis4r/Library/Android/sdk/platform-tools/adb -P 5037 -s HT4CBJT01577 shell cat /proc/net/unix
```

**Comment by vutukuriswathi** [comment]
I am testing hybrid app where webview is present in the native app.

@imurchie 
I opened the hybrid app which contains webview and ran the above command as you suggested.Please find the result of that command.
Here I am attaching a screenshot where it will show webview in hybrid app.
<img width="1309" alt="screen shot 2018-01-31 at 1 56 14 pm" src="https://user-images.githubusercontent.com/13588038/35602876-addb15e2-068e-11e8-9f02-2868aa770f5d.png">


WS102809:~ gunuputis4r$ /Users/gunuputis4r/Library/Android/sdk/platform-tools/adb -P 5037 -s HT4CBJT01577 shell cat /proc/net/unix
Num       RefCount Protocol Flags    Type St Inode Path
0000000000000000: 00000002 00000000 00010000 0005 01 10512 /dev/socket/lmkd
0000000000000000: 00000002 00000000 00010000 0001 01  9745 /dev/socket/adbd
0000000000000000: 00000002 00000000 00010000 0001 01 15529 @com.android.internal.telephony
0000000000000000: 00000002 00000000 00010000 0001 01  9533 /dev/socket/logd
0000000000000000: 00000002 00000000 00010000 0005 01  9538 /dev/socket/logdr
0000000000000000: 0000001B 00000000 00000000 0002 01  9541 /dev/socket/logdw
0000000000000000: 00000002 00000000 00010000 0001 01 10574 /dev/socket/installd
0000000000000000: 00000002 00000000 00010000 0001 01  9807 /dev/socket/zygote
0000000000000000: 00000002 00000000 00010000 0001 01  9825 /dev/socket/zygote_secondary
0000000000000000: 00000002 00000000 00010000 0001 01 15710 @/data/misc/bluedroid/.a2dp_ctrl
0000000000000000: 00000002 00000000 00010000 0001 01  9573 /dev/socket/vold
0000000000000000: 00000002 00000000 00010000 0001 01  9580 /dev/socket/cryptd
0000000000000000: 00000002 00000000 00010000 0001 01 13973 /data/system/ndebugsocket
0000000000000000: 00000002 00000000 00010000 0001 01  9612 @android:debuggerd
0000000000000000: 00000002 00000000 00000000 0002 01 14683 /data/misc/wifi/sockets/wpa_ctrl_585-2
0000000000000000: 00000002 00000000 00000000 0002 01 14684 /data/misc/wifi/sockets/wpa_ctrl_585-3
0000000000000000: 00000002 00000000 00010000 0001 01 10436 @android:debuggerd32
0000000000000000: 00000002 00000000 00010000 0001 01  9905 /dev/socket/netd
0000000000000000: 00000002 00000000 00010000 0001 01  9910 /dev/socket/dnsproxyd
0000000000000000: 00000002 00000000 00010000 0001 01  9913 /dev/socket/mdns
0000000000000000: 00000002 00000000 00010000 0001 01  9941 /dev/socket/fwmarkd
0000000000000000: 00000002 00000000 00000000 0005 01  9954 /dev/socket/gps
0000000000000000: 00000002 00000000 00010000 0001 01  9765 @jdwp-control
0000000000000000: 00000002 00000000 00010000 0001 01  7913 /dev/socket/property_service
0000000000000000: 00000004 00000000 00000000 0002 01 14575 /dev/socket/wpa_wlan0
0000000000000000: 00000003 00000000 00000000 0001 03 18128
0000000000000000: 00000003 00000000 00000000 0001 03 20683
0000000000000000: 00000002 00000000 00000000 0002 01 10559
0000000000000000: 00000003 00000000 00000000 0005 03 19589
0000000000000000: 00000003 00000000 00000000 0001 03  9773
0000000000000000: 00000003 00000000 00000000 0001 03 24751
0000000000000000: 00000003 00000000 00000000 0005 03 13260
0000000000000000: 00000003 00000000 00000000 0001 03 12927 /dev/socket/installd
0000000000000000: 00000003 00000000 00000000 0001 03 15699
0000000000000000: 00000002 00000000 00000000 0002 01 14451
0000000000000000: 00000003 00000000 00000000 0005 03 14694
0000000000000000: 00000003 00000000 00000000 0005 03 16395
0000000000000000: 00000003 00000000 00000000 0001 03  9766
0000000000000000: 00000003 00000000 00000000 0005 03 15270
0000000000000000: 00000003 00000000 00000000 0005 03 18979
0000000000000000: 00000002 00000000 00000000 0002 01 10853
0000000000000000: 00000003 00000000 00000000 0001 03 20345
0000000000000000: 00000003 00000000 00000000 0001 03 22777
0000000000000000: 00000003 00000000 00000000 0001 03 12865
0000000000000000: 00000003 00000000 00000000 0005 03 13883
0000000000000000: 00000003 00000000 00000000 0001 03 21608
0000000000000000: 00000003 00000000 00000000 0005 03 14723
0000000000000000: 00000002 00000000 00000000 0002 01 14603
0000000000000000: 00000003 00000000 00000000 0005 03 18974
0000000000000000: 00000002 00000000 00000000 0002 01  9691
0000000000000000: 00000003 00000000 00000000 0001 03 24756
0000000000000000: 00000003 00000000 00000000 0001 03 20684
0000000000000000: 00000003 00000000 00000000 0001 03 20711
0000000000000000: 00000003 00000000 00000000 0005 03 12939
0000000000000000: 00000002 00000000 00000000 0002 01 10074
0000000000000000: 00000003 00000000 00000000 0001 03 15740
0000000000000000: 00000002 00000000 00000000 0002 01 11483
0000000000000000: 00000003 00000000 00000000 0001 03 17300
0000000000000000: 00000003 00000000 00000000 0005 03 14283
0000000000000000: 00000003 00000000 00000000 0001 03 13294
0000000000000000: 00000003 00000000 00000000 0005 03 15268
0000000000000000: 00000003 00000000 00000000 0001 03 24753
0000000000000000: 00000003 00000000 00000000 0001 03 13266 /dev/socket/cryptd
0000000000000000: 00000003 00000000 00000000 0001 03 22692
0000000000000000: 00000003 00000000 00000000 0005 03 13256
0000000000000000: 00000002 00000000 00000000 0002 01 11318
0000000000000000: 00000003 00000000 00000000 0005 03 13889
0000000000000000: 00000003 00000000 00000000 0005 03 14276
0000000000000000: 00000003 00000000 00000000 0001 03 17327
0000000000000000: 00000003 00000000 00000000 0005 03  9613
0000000000000000: 00000003 00000000 00000000 0005 03 15224
0000000000000000: 00000003 00000000 00000000 0001 03 14363
0000000000000000: 00000003 00000000 00000000 0005 03 21768
0000000000000000: 00000003 00000000 00000000 0001 03  9772
0000000000000000: 00000002 00000000 00000000 0002 01 24748
0000000000000000: 00000003 00000000 00000000 0005 03 13259
0000000000000000: 00000003 00000000 00000000 0005 03 19000
0000000000000000: 00000003 00000000 00000000 0005 03 10567
0000000000000000: 00000003 00000000 00000000 0005 03 19590
0000000000000000: 00000003 00000000 00000000 0001 03 13904 /dev/socket/zygote_secondary
0000000000000000: 00000003 00000000 00000000 0001 03 14686
0000000000000000: 00000003 00000000 00000000 0005 03 16394
0000000000000000: 00000002 00000000 00000000 0002 01  9625
0000000000000000: 00000003 00000000 00000000 0005 03 15269
0000000000000000: 00000003 00000000 00000000 0005 03 13886
0000000000000000: 00000002 00000000 00000000 0002 01 10977
0000000000000000: 00000003 00000000 00000000 0001 03 15700
0000000000000000: 00000003 00000000 00000000 0001 03 21613
0000000000000000: 00000003 00000000 00000000 0001 03 22778
0000000000000000: 00000003 00000000 00000000 0005 03 12936
0000000000000000: 00000003 00000000 00000000 0005 03 18977
0000000000000000: 00000003 00000000 00000000 0001 03 13268 /dev/socket/vold
0000000000000000: 00000003 00000000 00000000 0001 03 20702
0000000000000000: 00000003 00000000 00000000 0001 03 20346
0000000000000000: 00000003 00000000 00000000 0005 03 14708
0000000000000000: 00000003 00000000 00000000 0001 03 16325
0000000000000000: 00000002 00000000 00000000 0002 01  9707
0000000000000000: 00000003 00000000 00000000 0005 03 13882
0000000000000000: 00000003 00000000 00000000 0001 03 20710
0000000000000000: 00000003 00000000 00000000 0005 03 13220
0000000000000000: 00000003 00000000 00000000 0001 03 24754
0000000000000000: 00000003 00000000 00000000 0005 03 18975
0000000000000000: 00000003 00000000 00000000 0005 03 10437
0000000000000000: 00000003 00000000 00000000 0001 03 17304
0000000000000000: 00000003 00000000 00000000 0001 03  7911
0000000000000000: 00000003 00000000 00000000 0005 03 15271
0000000000000000: 00000003 00000000 00000000 0001 03 13276 /dev/socket/netd
0000000000000000: 00000003 00000000 00000000 0005 03 14726
0000000000000000: 00000003 00000000 00000000 0001 03 15751
0000000000000000: 00000002 00000000 00000000 0002 01 11496
0000000000000000: 00000003 00000000 00000000 0001 03 22693
0000000000000000: 00000003 00000000 00000000 0005 03 13257
0000000000000000: 00000003 00000000 00000000 0001 03 22215
0000000000000000: 00000002 00000000 00000000 0002 01 10228
0000000000000000: 00000003 00000000 00000000 0001 03 24752
0000000000000000: 00000003 00000000 00000000 0001 03 13267
0000000000000000: 00000003 00000000 00000000 0005 03 14277
0000000000000000: 00000003 00000000 00000000 0001 03 17328
0000000000000000: 00000003 00000000 00000000 0005 03 15223
0000000000000000: 00000003 00000000 00000000 0005 03 13307
0000000000000000: 00000003 00000000 00000000 0001 03 15711
0000000000000000: 00000003 00000000 00000000 0005 03 13890
0000000000000000: 00000003 00000000 00000000 0005 03 13881
0000000000000000: 00000003 00000000 00000000 0001 03 15708
0000000000000000: 00000003 00000000 00000000 0001 03  9767
0000000000000000: 00000003 00000000 00000000 0001 03 14561
0000000000000000: 00000003 00000000 00000000 0005 03 14707
0000000000000000: 00000003 00000000 00000000 0005 03 18917
0000000000000000: 00000003 00000000 00000000 0001 03 18126
0000000000000000: 00000002 00000000 00000000 0002 01 10482
0000000000000000: 00000003 00000000 00000000 0005 03 19674
0000000000000000: 00000003 00000000 00000000 0001 03 14685
0000000000000000: 00000003 00000000 00000000 0005 03 21767
0000000000000000: 00000003 00000000 00000000 0001 03 21129
0000000000000000: 00000003 00000000 00000000 0001 03 13265
0000000000000000: 00000003 00000000 00000000 0005 03 13885
0000000000000000: 00000003 00000000 00000000 0005 03 15628
0000000000000000: 00000003 00000000 00000000 0005 03 14725
0000000000000000: 00000003 00000000 00000000 0005 03 18976
0000000000000000: 00000003 00000000 00000000 0001 03 16356
0000000000000000: 00000003 00000000 00000000 0001 03  9761
0000000000000000: 00000003 00000000 00000000 0005 03 18999
0000000000000000: 00000003 00000000 00000000 0001 03 16324
0000000000000000: 00000003 00000000 00000000 0005 03 10568
0000000000000000: 00000003 00000000 00000000 0001 03 21612
0000000000000000: 00000003 00000000 00000000 0001 03 22696
0000000000000000: 00000003 00000000 00000000 0005 03 13258
0000000000000000: 00000003 00000000 00000000 0001 03 15752
0000000000000000: 00000003 00000000 00000000 0001 03 20703
0000000000000000: 00000002 00000000 00000000 0002 01 11418
0000000000000000: 00000003 00000000 00000000 0001 03 17303
0000000000000000: 00000003 00000000 00000000 0005 03 13306
0000000000000000: 00000003 00000000 00000000 0001 03 15221
0000000000000000: 00000003 00000000 00000000 0001 03 20270
0000000000000000: 00000003 00000000 00000000 0001 03 13275
0000000000000000: 00000003 00000000 00000000 0005 03 15287
0000000000000000: 00000003 00000000 00000000 0001 03  7912
0000000000000000: 00000003 00000000 00000000 0001 03 20723
0000000000000000: 00000003 00000000 00000000 0001 03 15828 /dev/socket/adbd
0000000000000000: 00000003 00000000 00000000 0005 03 12937
0000000000000000: 00000002 00000000 00000000 0002 01 10215
0000000000000000: 00000003 00000000 00000000 0001 03 15712
0000000000000000: 00000003 00000000 00000000 0005 03 13887
0000000000000000: 00000003 00000000 00000000 0005 03 14274
0000000000000000: 00000003 00000000 00000000 0005 03 17326
0000000000000000: 00000002 00000000 00000000 0002 01  9618
0000000000000000: 00000003 00000000 00000000 0005 03 15226
0000000000000000: 00000003 00000000 00000000 0001 03 14364
0000000000000000: 00000003 00000000 00000000 0001 03 20679
0000000000000000: 00000003 00000000 00000000 0005 03 10438
0000000000000000: 00000002 00000000 00000000 0002 01 18062
0000000000000000: 00000003 00000000 00000000 0005 03 13221 /dev/socket/lmkd
0000000000000000: 00000003 00000000 00000000 0001 03 22214
0000000000000000: 00000002 00000000 00000000 0002 01 11392
0000000000000000: 00000003 00000000 00000000 0001 03 14560
0000000000000000: 00000003 00000000 00000000 0005 03 14695
0000000000000000: 00000003 00000000 00000000 0005 03 18918
0000000000000000: 00000003 00000000 00000000 0001 03 13345
0000000000000000: 00000003 00000000 00000000 0001 03 15709
0000000000000000: 00000003 00000000 00000000 0001 03 21128
0000000000000000: 00000002 00000000 00000000 0002 01 10974
0000000000000000: 00000003 00000000 00000000 0001 03 18127
0000000000000000: 00000003 00000000 00000000 0005 03 19675
0000000000000000: 00000003 00000000 00000000 0005 03 14724
0000000000000000: 00000003 00000000 00000000 0001 03 16355
0000000000000000: 00000003 00000000 00000000 0001 03  9763
0000000000000000: 00000003 00000000 00000000 0005 03 13884
0000000000000000: 00000003 00000000 00000000 0005 03 15629
0000000000000000: 00000003 00000000 00000000 0001 03 21609
0000000000000000: 00000003 00000000 00000000 0001 03 22695
0000000000000000: 00000003 00000000 00000000 0001 03 12864
0000000000000000: 00000003 00000000 00000000 0005 03 18980
0000000000000000: 00000003 00000000 00000000 0001 03 24757
0000000000000000: 00000003 00000000 00000000 0001 03 17301
0000000000000000: 00000003 00000000 00000000 0005 03 14282
0000000000000000: 00000003 00000000 00000000 0001 03 13295 /dev/socket/mdns
0000000000000000: 00000003 00000000 00000000 0001 03 15220
0000000000000000: 00000003 00000000 00000000 0001 03 15827
0000000000000000: 00000002 00000000 00000000 0002 01 11435
0000000000000000: 00000003 00000000 00000000 0001 03 20722
0000000000000000: 00000003 00000000 00000000 0005 03 12938
0000000000000000: 00000002 00000000 00000000 0002 01 10154
0000000000000000: 00000003 00000000 00000000 0001 03 20271
0000000000000000: 00000003 00000000 00000000 0005 03 15288
0000000000000000: 00000003 00000000 00000000 0001 03 20680
0000000000000000: 00000003 00000000 00000000 0005 03 14275
0000000000000000: 00000003 00000000 00000000 0005 03 17325
0000000000000000: 00000003 00000000 00000000 0005 03  9614
0000000000000000: 00000003 00000000 00000000 0005 03 15225
0000000000000000: 00000003 00000000 00000000 0001 03 13903 /dev/socket/zygote
0000000000000000: 00000003 00000000 00000000 0001 03 15739
0000000000000000: 00000003 00000000 00000000 0005 03 13888
0000000000000000: 00000003 00000000 00000000 0005 03 13255
0000000000000000: 00000002 00000000 00000000 0002 01 11336
0000000000000000: 00000002 00000000 00000000 0002 01 10439
0000000000000000: 00000003 00000000 00000000 0001 03 18125

**Comment by vutukuriswathi** [comment]
@mykola-mokhnach I am testing hybrid app.So for that no need to select chrome driver version right.

**Comment by mykola-mokhnach** [comment]
>  I am testing hybrid app.So for that no need to select chrome driver version right.

No, the correct driver version should always be chosen, irrespective of the fact it is a browser or.a webview.
