### ISSUE TITLE
Could not create a new session on Safari with simulator 

### ISSUE THREAD

**Issue by SelvamaniD** [appium/appium#10091]
## The problem
Safari browser is not launching on ios Simulator 

## Environment

* Appium version: v1.8.0-beta
* Xcode Version: 9.2
* XCUITestDriver Version :  v2.67.0
* Installed Carthage
* Installed web driver agent  
## Details
Recently, Updated the Xcode and Mac OS version to get the latest devices on simulator but with latest version safari is not launching at all 
## Capabilities:
[Appium]   fullReset: true
[Appium]   platformName: iOS
[Appium]   platformVersion: 11.2
[Appium]   javascriptEnabled: false
[Appium]   acceptSslCerts: false
[Appium]   automationName: XCUITest
[Appium]   deviceName: iPhone 8 Plus
[Appium]   browserName: Safari
[Appium]   safariIgnoreFraudWarning: true
[Appium]   autoWebview: true
[Appium]   startIWDP: true
[Appium]   safariAllowPopups: false
[Appium]   version: 
[Appium]   platform: ANY

## Link to Appium logs

https://gist.github.com/SelvamaniD/c6903d67d44a02ac53fdba0a6b921a6b

# It is not throwing any error why it is failing also

**Comment by mykola-mokhnach** [comment]
Which client do you use? Downgrade the server to 1.7.2-stable if it is java client. See https://github.com/appium/java-client/issues/818 for more details.

**Comment by SelvamaniD** [comment]
Hi Mykola

I am using perl client and tried with 1.7.2 also . Issue is same every where

**Comment by mykola-mokhnach** [comment]
Please attach the updated server log and client side exception stacktrace

**Comment by SelvamaniD** [comment]
It doesn't server log and client-side exception stack trace, I have attached the whole stack trace. If need i will enable showIOSlog in desired capabilities

**Comment by mykola-mokhnach** [comment]
try to remove startIWDP capability. It is only needed for real devices.

**Comment by SelvamaniD** [comment]
Removed but issue remains same

**Comment by kool79** [comment]
@SelvamaniD 
Don't know if this will help but...
Can you open simulator and safari manually?
Close simulator (if opened) and try to execute in Terminal:
```
xcrun simctl boot iPhone\ 8\ Plus
xcrun simctl openurl iPhone\ 8\ Plus http://www.appium.io
```
Do you see the simulator with safari?
If you don't try to  `Erase all content and settings` from Simulator's `Hardware` menu.

**Comment by SelvamaniD** [comment]
@kool79  

Thanks for comments. I can able to see safari with the simulator.

I hope the problem with **newCommandTimeout** and it is not waiting until web page opens on simulator

**Comment by SelvamaniD** [comment]
Reinstalled all the modules and set all appium capabilities, it just opened safari browser and throwing the error for  **Failed to create WDA session. Retrying...
2018-01-31 06:48:00:699 - [debug] [XCUITest] Unable to start WebDriverAgent session because of xcodebuild failure: "Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100".** 
Here is full log of stack trace 

https://gist.github.com/SelvamaniD/c8064b5222e1287621616e47590879c4

**Comment by SelvamaniD** [comment]
any updates ?

**Comment by oleksandr-kulychok** [comment]
just want to note that appium sends http response for `/session` in exactly 3 minute,  *before* simulator started (in 1st log) and before wda installed.  @mykola-mokhnach, is it OK? Do we have timeouts for processing http `/session` request?

**Comment by mykola-mokhnach** [comment]
You should not set `bundleId` if `browserName` is set

**Comment by Makavelic** [comment]
Does it always fail for you? My environment is identical to yours (I've been trying on 1.7.2 and 1.8 beta). I can launch safari but my test will misbehave 50% of the time by either stalling indefinitely or taking 4+ minutes to load a url. I'm wondering if you're encountering a similar issue to me. Here's my setup:

```
capabilities = new DesiredCapabilities();
capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "11.2");
capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "Safari");
capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone X");
capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");

try {
    driver = (new IOSDriver(new URL("<servername>:" + "4723" + "/wd/hub"), capabilities));
} catch (MalformedURLException e) {
    // TODO Auto-generated catch block
    e.printStackTrace();
}

driver.manage().timeouts().implicitlyWait(8, TimeUnit.SECONDS);
driver.get("http://www.google.ca");
```

It get's stuck / takes forever after this part:
[debug] [HTTP] Sending welcome response with params: {"message":"Let's browse!"}
[HTTP] <-- GET /welcome 200 15 ms - 124
