### ISSUE TITLE
Appium : Error Could not start session

### ISSUE THREAD

**Issue by crhoads1024** [appium/appium#10093]
## The problem

Randomly when trying to launch an appium session on either a physical device or a simulator, using either the node appium or the GUI desktop I receive the following: 
Error
Could not start session.

There are no logs, there is nothing, it just throws that error and I can go no further.
![image](https://user-images.githubusercontent.com/12171707/35524879-8932ebb8-04e8-11e8-932d-daa2a96fd9aa.png)

![image](https://user-images.githubusercontent.com/12171707/35524741-1688482e-04e8-11e8-9875-855b031d4ab6.png)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.3.1
* Last Appium version that did not exhibit the issue (if applicable): N/A Issue has come and gone on this build in the last 24hrs
* Desktop OS/version used to run Appium: OSX 10.13.2
* Node.js version (unless using Appium.app|exe): 8.9.4
* Mobile platform/version under test: iOS 11.2
* Real device or emulator/simulator: BOTH
* Appium CLI or Appium.app|exe: 1.3.1 and 1.7.2 - issue witnessed when using both launched servers

## Details
Starting the appium server to run via GUI or CLI and then using the "new session window" to select saved Capability configurations to launch session randomly produces "Error cannot start session" issue. 

This happened yesterday and I was able to reinstall appium GUI and it was fixed.
Have uninstalled, reinstalled, rebooted....
This has not remedied the situation today, issue persists.

## Link to Appium logs

There are no logs, it throws error before anything can be logged.

## Code To Reproduce Issue [ Good To Have ]
No configurations will launch.
{
  "deviceName": "iPhone 6s Plus",
  "platformName": "iOS",
  "app": "Users/chrisrhoads/.npm-packages/lib/node_modules/appium/node_modules/appium-ci/iOS_Simulator_AppFiles/QsrSoft.app",
  "automationName": "XCUITest",
  "platformVersion": "11.2",
  "udid": "754B6916-E8E7-4CD0-957E-A26DD4089D52",
  "fullReset": true,
  "useNewWDA": false,
  "showIOSLog": "false",
  "showXcodeLog": "true"
}

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/appium/appium-desktop/issues
