### ISSUE TITLE
appium not able to get the webview in actual device whereas I have the same webview in simulator

### ISSUE THREAD

**Issue by suvidhapra** [appium/appium#10095]
Appium not able to get the webview in actual device whereas I have the same webview in simulator

In my application I have login screen as webview and I am not able to get the webview in actual device whereas in simulator I am easily getting both webviews(NATIVE_APP, WEBVIEW_1233), but when I run the same set of scripts in actual device it returns only one webview 'NATIVE_APP'

## Environment
* Appium version : 1.7.2
* Desktop OS/version used to run Appium: OS-X 10.13.3 (17D47)
* Node.js version (unless using Appium.app|exe): v9.4.0
* Mobile platform/version under test: iPhone 8 Plus iOS - 11.1.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

Details
In my application I have login screen as webview and I am not able to get the webview in actual device whereas in simulator I am easily getting both webviews(NATIVE_APP, WEBVIEW_1233), but when I run the same set of scripts in actual device it returns only one webview 'NATIVE_APP'

Appium logs
https://gist.github.com/suvidhapra/5f75b9d2957a750d21ff302cc7c6c66c

Code To Reproduce Issue [ Good To Have ]

webview = @driver.available_contexts
    webview.each {|st| puts st}
    @driver.set_context(webview[1])

[caps]
platformName = "ios"
deviceName = "Test Device"
platformVersion = "11.1.1"
app = "../iOSClientPOC/app/app4815162342_qa.ipa"
automationName = "XCUITest"
udid = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
xcodeOrgId = "XXXXXXXXXX"
xcodeSigningId = "iPhone Developer"

Output:
|NATIVE_APP

**Comment by kool79** [comment]
Do you see your device/webView in  Safari's Develop menu (on your mac)?

**Comment by mykola-mokhnach** [comment]
Are you able to see the webview if you connect IWDP manually?

**Comment by suvidhapra** [comment]
@kool79 I am able to see my device in safari's develop menu.
![screen shot 2018-01-31 at 9 15 56 am](https://user-images.githubusercontent.com/29312893/35636982-a3002b16-0667-11e8-8a79-426f77fa14d0.png)

**Comment by suvidhapra** [comment]
@mykola-mokhnach when I try to run the IWDP manually it returns empty JSON.

**Comment by mykola-mokhnach** [comment]
I'd rather report the issue to IWDP then

**Comment by suvidhapra** [comment]
@mykola-mokhnach @kool79 I posted this issue in ios-webkit-debug-proxy and did lot of research on suggested options. What I found after my work, the webdriver ran by appium is not detecting the web view, when I run the webdriver manually and provide the web driver server as appium desired capability I am able to get the web view. For me it looks like appium issue, can you guys take a look.

desired capabilities:
{
  "platformName": "iOS",
  "platformVersion": "11.1.1",
  "deviceName": "Test Device",
  "automationName": "XCUITest",
  "app": "/Users/praveshk/Desktop/cc-appium-demo-pravesh/app/app4815162342 2.app",
  "udid": "fcc7d6025dedc27e67d3675557fe76a380dad9c7",
  "webkitDebugProxyPort": 9221,
  "webDriverAgentUrl": "http://169.254.195.69:8100",
  "usePrebuiltWDA": true,
  "noReset": true,
  "autoWebview": true
}

https://gist.github.com/suvidhapra/89fce3835f225d2f0483a7d6fa907ff0

![screen shot 2018-02-19 at 10 57 07 am](https://user-images.githubusercontent.com/29312893/36455837-dd3d15a6-1656-11e8-872a-bca49255d16d.png)
