### ISSUE TITLE
Unable to get Performance Data

### ISSUE THREAD

**Issue by pavanbachu0604** [appium/appium#10094]
## The problem

Unable to capture the iOS vitals using the code in [link](https://appium.io/docs/en/commands/device/performance-data/get-performance-data/). 

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.5
* Mobile platform/version under test: iOS 10.3.2
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe:
* Java Client - 5.0.0. Beta 9

## Details

Able to capture the syslogs using 

> List<LogEntry> logEntries = ((IOSDriver<?>) getDriver()).manage().logs().get("syslog").getAll()

but the only issue is that I am not able to capture the data for all pages of my application. Is it limited that it can return once per each webview?

**Comment by mykola-mokhnach** [comment]
As you can see there the API is only supported on Android.

Closed as not an issue

**Comment by pavanbachu0604** [comment]
how to get performance logs for the iOS device ?
