### ISSUE TITLE
Appium not able to launch on real devices and successfully launch same script on simulator

### ISSUE THREAD

**Issue by Saurabh0311** [appium/appium#10100]
POST /wd/hub/session {"desiredCapabilities":{"automationName":"XCUITest","bundleId":"com.influenster.mobile","deviceName":"iPhone 6s Plus","platformName":"iOS","platformVersion":"10.3","showIOSLog":true,"udid":"1f4a8caaecb50c2ebe93dfd8ab3edd560fc48804"},"capabilities":{"desiredCapabilities":{"automationName":"XCUITest","bundleId":"com.influenster.mobile","deviceName":"iPhone 6s Plus","platformName":"iOS","platformVersion":"10.3","showIOSLog":true,"udid":"1f4a8caaecb50c2ebe93dfd8ab3edd560fc48804"},"firstMatch":[{"platformName":"ios"}]}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"automationName":"XCUITest","bundleId":"com.influenster.mobile","deviceName":"iPhone 6s Plus","platformName":"iOS","platformVersion":"10.3","showIOSLog":true,"udid":"1f4a8caaecb50c2ebe93dfd8ab3edd560fc48804"},null,{"desiredCapabilities":{"automationName":"XCUITest","bundleId":"com.influenster.mobile","deviceName":"iPhone 6s Plus","platformName":"iOS","platformVersion":"10.3","showIOSLog":true,"udid":"1f4a8caaecb50c2ebe93dfd8ab3edd560fc48804"},"firstMatch":[{"platformName":"ios"}]}]
[BaseDriver] Event 'newSessionRequested' logged at 1517309765122 (16:26:05 GMT+0530 (IST))
[Appium] Merged W3C capabilities {"desiredCapabilities":{"automationName":"XCUIT... into desiredCapabilities object {"automationName":"XCUITest","bundleId":"com.in...
[Appium] Creating new XCUITestDriver (v2.64.0) session
[Appium] Capabilities:
[Appium]   automationName: XCUITest
[Appium]   bundleId: com.influenster.mobile
[Appium]   deviceName: iPhone 6s Plus
[Appium]   platformName: ios
[Appium]   platformVersion: 10.3
[Appium]   showIOSLog: true
[Appium]   udid: 1f4a8caaecb50c2ebe93dfd8ab3edd560fc48804
[BaseDriver] Session created with session id: c8aceadc-ce93-4e9d-bcdb-64de3efd1e94
[XCUITest] Current user: 'admin'
[XCUITest] Current version of libimobiledevice: stable 1.2.0 (bottled), HEAD
[XCUITest] Xcode version set to '9.1' 
[XCUITest] iOS SDK Version set to '11.1'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1517309767859 (16:26:07 GMT+0530 (IST))
[XCUITest] Error: Command 'idevice_id -l' exited with code null
    at ChildProcess. (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/teen_process/lib/teen_process.js:97:19)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
 { Error: Command 'idevice_id -l' exited with code null
    at ChildProcess. (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/teen_process/lib/teen_process.js:97:19)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
  stdout: '',
  stderr: 'dyld: Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib\n  Referenced from: /usr/local/bin/idevice_id\n  Reason: no suitable image found.  Did find:\n\t/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib: not a file\n\t/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib: stat() failed with errno=1\n\t/usr/local/Cellar/openssl/1.0.2n/lib/libcrypto.1.0.0.dylib: not a file\n',
  code: null }
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[MJSONWP] Encountered internal error running command: Error: Command 'idevice_id -l' exited with code null
    at ChildProcess. (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/teen_process/lib/teen_process.js:97:19)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
[HTTP] <-- POST /wd/hub/session 500 3711 ms - 182

**Comment by mykola-mokhnach** [comment]
You local libimobiledevice setup is broken. Try to reinstall it.

Closed as non server-related
