### ISSUE TITLE
Getting an error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65".

### ISSUE THREAD

**Issue by ChethanGKC** [appium/appium#10106]
I have two appium servers one is installed through npm(1.7.1) and the other is the UI appium application(1.7.2)

I am unable to launch the application through appium UI application.

**## Environment**

* Appium version : 1.7.2 UI version of appium
* Desktop OS/version used to run Appium: 10.12.3
* Mobile platform/version under test: 10.3.3
* Real device : iPhone 6S
*Appium.app|exe:

**## Details**
I am using below desire capabilities(same capabilities are working fine for appium installed with npm 1.7.1)

DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");
			capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 300);
			capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 6S");
			capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
			capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, 10.3.3);
			capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "");
			capabilities.setCapability(MobileCapabilityType.APP, "xxxxxxxx");
			capabilities.setCapability("bundleId", "xxxxxxxx");
			capabilities.setCapability(MobileCapabilityType.UDID, "xxxxxxxxxxxxxxxxxx");
			capabilities.setCapability(MobileCapabilityType.FULL_RESET, true);
			capabilities.setCapability("shouldUseSingletonTestManager", false);
			capabilities.setCapability("startIWDP", true);
			capabilities.setCapability("useNewWDA", true);
			capabilities.setCapability("maxTypingFrequency", 10);
			capabilities.setCapability("connectHardwareKeyboard", false);
			capabilities.setCapability("sendKeyStrategy", "oneByOne"); 
driver = new IOSDriver(
					new URL("http://localhost:4723/wd/hub"), capabilities);

**## Link to Appium logs**

https://gist.github.com/ChethanGKC/3cb984fc6ff3fdce69f54b8f93f5916c

Can any one please help me on this

**Comment by ChethanGKC** [comment]
@mykola-mokhnach  @imurchie - Can you please help me on this

**Comment by mykola-mokhnach** [comment]
there are many duplicated issues like this one. Error 65 means that WDA source cannot be deployed, because it is not signed properly. Read https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

**Comment by ChethanGKC** [comment]
@mykola-mokhnach -  thanks for the fast replay.
With out using the below steps it working fine with the appium installed through npm. 
*Use the xcodeOrgId and xcodeSigningId desired capabilities
*Create a .xcconfig file somewhere on your file system and add the following to it

But same code is not working with the UI appium.

**Comment by mykola-mokhnach** [comment]
you can point the desktop application to use the same service, which is installed via CLI. By default it uses its own built-in WDA distribution, which requires separate setup

**Comment by ChethanGKC** [comment]
@mykola-mokhnach - can you please let me know the steps to do that.

**Comment by ChethanGKC** [comment]
@mykola-mokhnach - or can i know how to get the xcodeOrgId

**Comment by pavanbachu0604** [comment]
@ChethanGKC : For xcodeOrgId, please account your admin who manages the Apple developer account

**Comment by swachhab** [comment]
@ChethanGKC If you are still facing this problem for signing webdriveragent, you can watch this video: https://youtu.be/dyijACVRQOc 
Hope it will help :)
