### ISSUE TITLE
Command 'appium/app/background' throws exception 

### ISSUE THREAD

**Issue by HlebHalkouski** [appium/appium#10105]
## The problem

Command `RUN_APP_IN_BACKGROUND` command in java-client throws WebDriver exception 'Original error: Could not get focusPackageAndActivity. Original error: Could not parse activity from dumpsys (WARNING: The server did not provide any stacktrace information)'

Does not work on both the UiAutomator 1 and 2

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Desktop OS/version used to run Appium: High Sierra
* Node.js version (unless using Appium.app|exe):8.0.0
* Mobile platform/version under test: Android 6.0.1 and 7.0
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

[Capabilities](https://gist.github.com/HlebHalkouski/32d56972c67c392332f569e55744dbe0)
[Logs](https://gist.github.com/HlebHalkouski/56dce50ee294c37d890eb15720fb9d2f)

**Comment by mykola-mokhnach** [comment]
Can you attach the output of `adb shell dumpsys window windows` command before runInBackground is executed?

**Comment by HlebHalkouski** [comment]
@mykola-mokhnach [command](https://gist.github.com/HlebHalkouski/4a1eb3d4854f8633b859a36bb615d332)
Samsung Tab A Android 6.0.1

**Comment by mykola-mokhnach** [comment]
hm, the parsing result looks good with the given output. You can check it yourself at https://regex101.com/r/xZ8vF7/1

It might be a timing issue though

**Comment by HlebHalkouski** [comment]
@mykola-mokhnach 
I catched 2 different [logs](https://gist.github.com/HlebHalkouski/6915bc03ddcb7f2ff2b1e086986d8c0c)

'Permission to start activity denied' is this issue with app?

**Comment by mykola-mokhnach** [comment]
it might be. The logic there is to get the current activity name before going to background and launch it again. If this activity cannot be started then it either crashed or there is some special app architecture, which requires some other activity to be launched first in order to restore the app from background.

**Comment by HlebHalkouski** [comment]
@mykola-mokhnach Ok, thank you a lot!
