### ISSUE TITLE
findElementFromElement not returning child element

### ISSUE THREAD

**Issue by tfcardoso** [appium/appium#10101]
## The problem

After I upgraded to Xcode9, iOS11 and Appium v1.7.2 several of the nested find elements that worked before stopped working.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.7.2 / XCode9.2
* Last Appium version that did not exhibit the issue (if applicable): 1.7.1 / XCode8.3.3 / iOS10.3.3
* Mobile platform/version under test: iOS 11.2.5
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: v1.7.2

## Details

The project I test its quite complex, so I often use findElementByIosNsPredicate that gives me more freedom on my queries. After I updated to XCode9, iOS11 the queries that find element from a parent element started failing. Strangely enough if I query for elements instead of element, the first returns properly while the second doesn't find the element.

## Link to Appium logs

https://gist.github.com/tfcardoso/f57cae4cf183c8eed120eafc326477f3

## Code To Reproduce Issue [ Good To Have ]

I made an example based on the following view:
https://image.prntscr.com/image/nr0Bv3wDRRyh-p2vK2Jshg.png

Its a XCUIElementTypeCollectionView with several XCUIElementTypeCell and inside the penultimate one, there is an element that has a play button (with id/name chatView_fileTransfers_button_videoPlay).

```
IOSElement parentElement = (IOSElement) ((IOSDriver) driver).findElementByIosNsPredicate("(type = \"XCUIElementTypeCollectionView\")");
List<MobileElement> rows = parentElement.findElementsByIosNsPredicate("(type = \"XCUIElementTypeCell\")");
MobileElement cellElement = rows.get(rows.size() - 2);
System.out.println("I'm " + cellElement.getAttribute("name"));
List<MobileElement> videoButtons = cellElement.findElementsById("chatView_fileTransfers_button_videoPlay");
System.out.println("Amount of elements :"+videoButtons.size());
try {
     cellElement.findElementById("chatView_fileTransfers_button_videoPlay");
} catch (Exception e) {
     System.out.println("Element not found");
}
```

The output from the above code is:
```
I'm WMCIncomingFileTransferCell
Amount of elements :1
Element not found
```

There is other person with apparently the same problem in http://discuss.appium.io/t/appium-ios-findelementfromelement-is-not-working/20727

**Comment by mykola-mokhnach** [comment]
Is this button found if you execute find in the global context (driver.findElement) ?

**Comment by tfcardoso** [comment]
> Is this button found if you execute find in the global context (driver.findElement) ?

Yes, it is found.

**Comment by mykola-mokhnach** [comment]
The only diff I see there is the usage of `firstMatch` API. Try to comment out [this](https://github.com/appium/WebDriverAgent/blob/de5f64546a40f4cf493fa9c48a9072f11042625e/WebDriverAgentLib/Utilities/FBXCodeCompatibility.m#L84) condition in your local WDA source and check if it helps.

**Comment by tfcardoso** [comment]
I had to revert xcode, because I have urgent deliveries, so I may try that only in couple days. In the meantime @bhagarenikhi can you try and comment that condition and re-run your tests?

**Comment by bhagarenikhi** [comment]
Yes. I have tried by commenting the condition but no luck :-(. 
@mykola-mokhnach, This case is happened only when you find the parent element by `find_by_elements` method.

`cell = $driver.find_elements(:name, 'locationCell').first`
`cell.find_element(:name, 'title')`
Above code is not working. While when I tried using below code then it works fine.
`cell = $driver.find_element(:name, 'locationCell')`
`cell.find_element(:name, 'title')`

**Comment by mykola-mokhnach** [comment]
I assume it's some internal XCTest magic. I'd try to use single class chain locator instead to wrkaround this problem.  For example, the described case might use the following chain locator:

```
**/XCUIElementTypeCollectionView/XCUIElementTypeCell/**/XCUIElementTypeButton[`name == 'chatView_fileTransfers_button_videoPlay'`]
```

**Comment by newthomas** [comment]
I have the same problem. First I thought it was Appium 1.8.0 but then I see the same issue with 1.7.2.

Previously this was used:
`return (IOSElement) findCell(cellIndex).findElement(By.id(elementIdentifier))`

My very ugly workaround:
`return (IOSElement) findCell(cellIndex).findElementsById(elementIdentifier).get(0)`

**Comment by jamesvanhorn** [comment]
You can roll back to appium 1.7.1 and it should work fine, if there isn't anything specific in 1.7.2 that you rely on. `npm i -g appium@1.7.1`

**Comment by newthomas** [comment]
It also doesn't work with Appium 1.7.1 when using latest XCode 9.2

**Comment by tfcardoso** [comment]
@mykola-mokhnach 

> The only diff I see there is the usage of firstMatch API. Try to comment out this condition in your local WDA source and check if it helps.

I upgraded again to Xcode9.2. Tested again to see if it continued failing, and then with the code:
```
if (FBShouldUseFirstMatchSelector) {
    XCUIElement* result = self.firstMatch;
    return result.exists ? result : nil;
  }
```
commented it works 🥇 

You think a fix can be made?

**Comment by mykola-mokhnach** [comment]
Thanks for checking @tfcardoso. I've created a PR to patch it, so firstMatch will only be executed in application context

**Comment by newthomas** [comment]
Confirm: no issues with Appium 1.8.0-beta3.

**Comment by bowka** [comment]
It doesn't work for me on version 1.9.2 
actually I've tried multiple versions but each version has some issues
1.8.0 grandPermissions issues
1.9.1 set location issue
1.7.2 findElementFromElement issue
Anybody who still facing the issue after updating to new version?
