### ISSUE TITLE
Not able to find element.

### ISSUE THREAD

**Issue by sjdptn** [appium/appium#10104]
Eclipse: Oxygen forJAVA EE Developers Selenium: 3.7.1 Appium: 1.7.1 testing device: ios Simulator Code package appium; import java.net.MalformedURLException; import java.net.URL; import java.util.concurrent.TimeUnit; import org.openqa.selenium.By; import org.openqa.selenium.remote.DesiredCapabilities; import org.testng.annotations.Test; import io.appium.java_client.ios.IOSDriver; public class NewTest { @SuppressWarnings({ "rawtypes" }) private IOSDriver driver; @SuppressWarnings("rawtypes") @test public void first() throws MalformedURLException, InterruptedException { DesiredCapabilities caps = new DesiredCapabilities(); caps.setCapability("platformName", "iOS"); caps.setCapability("platformVersion", "11.0"); caps.setCapability("deviceName", "iPhone 7"); caps.setCapability("automationName", "XCUITest"); caps.setCapability("app",  "/Users/preeti/Library/Developer/Xcode/DerivedData/Kiosk-cqqwwmdzdfarneanaqslqyqicatp/Build/Products/Debug-iphonesimulator/Kiosk.app"); driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), caps); driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS); driver.findElementByAccessibilityId("SKIP").click(); driver.findElement(By.xpath("//XCUIElementTypeButton[1]")).click(); driver.findElementByAccessibilityId("Cheeses").click(); driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS); driver.findElementByAccessibilityId("BOAR'S HEAD LACEY SWISS CHEESE $11.99/lb. now $5.49/lb.").click(); } } 

Failure: It is failing at the last step even when the element is present and got the element accesibility ID using appium inspector
org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:07:31.527Z'
System info: host: 'preetis-air.in.ibm.com', ip: 'fe80:0:0:0:10ab:3218:4a9b:bf4b%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_151'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities {app: /Users/preeti/Library/Devel..., automationName: XCUITest, browserName: , databaseEnabled: false, deviceName: iPhone 7, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: false, platform: MAC, platformName: MAC, platformVersion: 11.0, takesScreenshot: true, udid: 411AE598-2210-4806-84E5-7D9..., webStorageEnabled: false}
Session ID: 90b5f61c-5141-4a8e-bfab-c937abff3781
*** Element info: {Using=accessibility id, value=BOAR'S HEAD LACEY SWISS CHEESE $11.99/lb. n

**Comment by mykola-mokhnach** [comment]
Please fill out the issue reporting form and provide the necessary info, especially the full server log and the page source

**Comment by sjdptn** [comment]
It is not a table view nor a scroll view, it is flat list view in the app. How to locate element in flat list for?
