### ISSUE TITLE
longPress on Element not pressing on proper coordinates - XCode9

### ISSUE THREAD

**Issue by tfcardoso** [appium/appium#10109]
## The problem

After I upgraded to Xcode9, iOS11 and Appium v1.7.2 a long press on a particular element is not being performed on correct coordinates (didn't test all long presses that I have on project to see if all the others are still working or not)

## Environment

* Appium version (or git revision) that exhibits the issue: v1.7.2 / XCode9.2
* Last Appium version that did not exhibit the issue (if applicable): 1.7.1 / XCode8.3.3 / iOS10.3.3
* Desktop OS/version used to run Appium: OSX 10.13.3
* Mobile platform/version under test: iOS 11.2.5
* Real device or emulator/simulator: Real Device
* Java client: 5.0.4

## Details

longPress on element is long pressing on a different area (apparently its on x=0, y=0 + center of element). Strangely if I long press directly on coordinates, everything works properly. 

It doesn't seem a Java Client issue, because same version works properly with Xcode8, iOS10.3.3, Appium 1.7.1

## Link to Appium logs

https://gist.github.com/tfcardoso/4fb20daeb8dddb6775b3e66f5e8e5497

## Code To Reproduce Issue [ Good To Have ]

Source code of page: https://gist.github.com/tfcardoso/82ca84ee27291d1108e87523de4c6534
Element ID: **chat_quick_share_voice_normal**
Screen of inspector: [https://image.prntscr.com/image/2nTUBpPgS6mNAPYjNFrp7w.png](url)

Test Code:
```
MobileElement element = (MobileElement) driver.findElementById("chat_quick_share_voice_normal");
new TouchAction(driver).longPress(element, Duration.ofMillis(5000)).release().perform();
```

And this code works:
```
MobileElement element = (MobileElement) driver.findElementById("chat_quick_share_voice_normal");
Point p = element.getLocation();
Dimension d = element.getSize();
new TouchAction(driver).longPress(p.getX() + (d.getWidth() / 2), p.getY() + (d.getHeight() / 2), Duration.ofMillis(5000)).release().perform();
```

Will investigate if longPress(element,duration) fails anywhere else in project

**Comment by vjmaiky** [comment]
using java 6 beta 2 and new touch actions approach using PointOption it is working.

**Comment by tfcardoso** [comment]
@vjmaiky I'll try that. Thanks

**Comment by tfcardoso** [comment]
Using:

```
new TouchAction(driver).longPress(longPressOptions().withElement(element(element)).withDuration(Duration.ofMillis(duration)))
                .release().perform();
```

With 6.0.0-BETA2 results in same behavior with the above source page.

**Comment by vjmaiky** [comment]
i'm using something like this (i need to try it also because i didn't used for more then 2 weeks): 
new TouchAction(Drivers.getMobileDriver()).longPress(PointOption.point(element)).waitAction(WaitOptions.waitOptions(Duration.ofSeconds(1))).release().perform();

**Comment by tfcardoso** [comment]
It says PointOption.point receives coordinates and not element:
https://appium.github.io/java-client/io/appium/java_client/touch/offset/PointOption.html#point-int-int-

Anyway I think the request made to appium server ends up being the same. I'll wait for someone to take a look. Thanks for help  @vjmaiky

**Comment by mykola-mokhnach** [comment]
It might be that longPress is sent to some element point, which does not listen to this event. Try to explicitly set long tap coordinates on element rectangle in the actions chain.

**Comment by tfcardoso** [comment]
@mykola-mokhnach If use the coordinates, it works. I was opening it, because it seems like an issue that somewhere along the road, the element coordinates are not extracted properly.

**Comment by mykola-mokhnach** [comment]
Then it would be better to report it to Apple
