### ISSUE TITLE
.click, .clear, .sendKeys all throw Error response status: 13

### ISSUE THREAD

**Issue by visylvius** [appium/appium#10118]
## The problem

Currently i'm using wd, and appium, and expo. 
Some methods work completely fine. such as 
elementByAccessibilityId
close_app
But whenever the methods click, sendKeys, or clear are called it always throws the following error.

[click()] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. Selenium error: Method has not yet been implemented

Example code.

## Environment
"wd": "^1.5.0"
"appium": "^1.7.2",
"react-native": "0.49.5",
* Appium version (or git revision) that exhibits the issue: "^1.7.2",
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: Genymotion
* Node.js version (unless using Appium.app|exe): 
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Expo 
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
https://gist.github.com/visylvius/92063a60d106182240d6a107e54b083c
## Code To Reproduce Issue [ Good To Have ]

```
import wd from 'wd'

jasmine.DEFAULT_TIMEOUT_INTERVAL = 60000
const PORT = 4723
const config = {
  platformName: 'Android',
  deviceName: 'Android Emulator',
  app: './e2e/apk/android%2F@visylvius%2Fprogressly-efeb21b0-084a-11e8-867e-0a580a782620-signed.apk' // relative to root of project
}

const driver = wd.promiseChainRemote('localhost', PORT)

beforeAll(async () => {
  await driver.init(config)
  await driver.sleep(2000) // wait for app to load
})

test('app renders', async () => {
  expect(await driver.hasElementByAccessibilityId('email-input')).toBe(true)
  expect(await driver.hasElementByAccessibilityId('password-input')).toBe(true)
  expect(await driver.hasElementByAccessibilityId('login-button')).toBe(true)
  expect(await driver.hasElementByAccessibilityId('notthere')).toBe(false)
})

test('will fill out the email input', async () => {
  await driver.hasElementByAccessibilityId('email-input')
    .click()
    .clear()
    .sendKeys('jackc@progressly.com')
})
```

**Comment by imurchie** [comment]
Can you provide the Appium server logs, as a link to a [gist](https://gist.github.com) so we can see what is being received?

**Comment by visylvius** [comment]
Absolutely. Give me a moment

**Comment by visylvius** [comment]
Just uploaded.

**Comment by imurchie** [comment]
I don't think this log is for your test run above.

But I just noticed in the code you provided, you call `hasElementByAccessibilityId`, which does not return a thing which can be clicked, I don't think.

Can you try
```js
test('will fill out the email input', async function () {
  await driver.elementByAccessibilityId('email-input')
    .click()
    .clear()
    .sendKeys('jackc@progressly.com')
})
```

**Comment by mykola-mokhnach** [comment]
I don't observe any problems in the log. Might it be that you don't use promises properly?

**Comment by visylvius** [comment]
I just updated the gist again with the proper logs. My apologies.

**Comment by visylvius** [comment]
Oh man. You are absolutely right, hasElementByAccesibilityId most certainly didn't return an element that could be clicked.

Switching it to the elementByAccessibilityId most certainly did the trick. Thank you both for responding so quickly and being so helpful!

**Comment by imurchie** [comment]
🎉🎉🎉
