### ISSUE TITLE
Getting huge amount of console logging when instantiating Appium Android Driver

### ISSUE THREAD

**Issue by vermad** [appium/appium#10113]
## The problem

Whenever the object of AndroidDriver instantiated, a huge log gets generated/printed in Console which consumes a lot of execution time. How to turn off or stop that logging?

## Environment

* Appium version : 1.7.1
* Desktop OS/version used to run Appium: Mac OSX (10.13.1)
* Node.js version (unless using Appium.app|exe): 9.4.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Both
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs
https://gist.github.com/vermad/8fa5137f6a3510414b4edca6fbcc3954

## Code To Reproduce Issue [ Good To Have ]
import java.net.MalformedURLException;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;
import io.appium.java_client.android.AndroidDriver;

public class Test {
	static AndroidDriver<WebElement> driver;
	public static void main(String[] args) throws MalformedURLException, InterruptedException {
		DesiredCapabilities capabilities = new DesiredCapabilities(); 
		capabilities.setCapability("deviceName", "Android Emulator");
		capabilities.setCapability(CapabilityType.BROWSER_NAME, "chrome");
		capabilities.setCapability("platformName", "android");
		driver = new AndroidDriver<WebElement>(capabilities);
		driver.get("http://business.officedepot.com");
		System.out.println("done");
	}
}

**Comment by imurchie** [comment]
You can set the log level from the command line with the `--log-level` flag (for CLI, see http://appium.io/docs/en/writing-running-appium/server-args/).

Possible choices are:
```
info
info:debug
info:info
info:warn
info:error
warn
warn:debug
warn:info
warn:warn
warn:error
error
error:debug
error:info
error:warn
error:error
debug
debug:debug
debug:info
debug:warn
debug:error'
```
