### ISSUE TITLE
Feature Request => way to skip unnecessary checks 

### ISSUE THREAD

**Issue by trix0** [appium/appium#10116]
Yo, Its me Again

## The problem
So basically whenever You run Appium Test It goes through the steps to verify if apps exists and have correct version. Thats great , but for Automated testing is it really necessary to check for it on the same device on the start of every test ? Every one of this checks is between 1.2sec to 3 secs(2sec avg).

1. app
file was not listed, instead we're going to run com.pointvoucher.playlondonpv directly on the device
Running '/home/trixo/Android/Sdk/platform-tools/adb' with args: ["-P",5037,"-s","localhost:7409","shell","pm","list","packages","com.pointvoucher.playlondonpv"]
2.
Running '/home/trixo/Android/Sdk/platform-tools/adb' with args: ["-P",5037,"-s","localhost:7409","shell","pm","list","packages","io.appium.settings"]
3.
Running '/home/trixo/Android/Sdk/platform-tools/adb' with args: ["-P",5037,"-s","localhost:7409","shell","pm","list","packages","io.appium.unlock"]
4.(second time same one ??)
unning '/home/trixo/Android/Sdk/platform-tools/adb' with args: ["-P",5037,"-s","localhost:7409","shell","pm","list","packages","com.pointvoucher.playlondonpv"]

So after all this checks its around 8 sec to add to init sequence. Ok for 1(8sec) Test , Ok for 10(80sec) tests, OK ? for 100(800Sec) tests ? 1000(8000sec), 10000(80000sec) ? 

## Suggestion 

I m thinking about add something like useStrict:true/false(true def) in capDef. What would allow to skip those unnecessary checks.

So In Real world you would use useStrict:true on a first test and on another ones You would use useStrict:false to reduce loading time.

## Environment

* Appium version (or git revision) that exhibits the issue:1.7.2 higher ( not sure about lower)
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:linux/win 10
* Node.js version (unless using Appium.app|exe):9.4.0
* Mobile platform/version under test:Android 6.0 
* Real device or emulator/simulator:Samusng A3 real
* Appium CLI or Appium.app|exe:CLI

## Link to Appium logs
https://gist.github.com/trix0/7e6fde3785c2ffa13126dda6cdffd2e2

<b>It might bring some unexpected errors So What do You think guys ?</b>

**Comment by mykola-mokhnach** [comment]
Several major performance optimizations were done in appium@beta for android driver startup. I have doubts we can do more there without breaking the functionality.
