### ISSUE TITLE
[XCUITest] Error: Carthage not found. Install using `brew install carthage`

### ISSUE THREAD

**Issue by kishanravindra** [appium/appium#10117]
## The problem

Unable to run wda on multiple simulators 

## Environment

* Desktop OS/version used to run Appium: 1.2.7
* Node.js version (unless using Appium.app|exe): 8.9.1
* Mobile platform/version under test: 11.2
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: app(Mac)

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

[Appium] Welcome to Appium v1.7.1
[Appium] Non-default server args:
[Appium]   port: 4725
[Appium] Appium REST http interface listener started on 0.0.0.0:4725
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.7.1","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 18 ms - 83 
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.7.1","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 11 ms - 83 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/KishanRavindra/Desktop/DocDock.app","networkConnectionEnabled":true,"platformVersion":"9.3","automationName":"XCUITest","browserName":"","platformName":"iOS","deviceName":"iPhone 6","launchTimeout":500000,"wdaLocalPort":"8100"},"requiredCapabilities":{},"capabilities":{"desiredCapabilities":{"app":"/Users/KishanRavindra/Desktop/DocDock.app","networkConnectionEnabled":true,"platformVersion":"9.3","automationName":"XCUITest","browserName":"","platformName":"iOS","deviceName":"iPhone 6","launchTimeout":500000,"wdaLocalPort":"8100"},"requiredCapabilities":{},"alwaysMatch":{"browserName":"","platformName":"iOS"},"firstMatch":[]}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/KishanRavindra/Desktop/DocDock.app","networkConnectionEnabled":true,"platformVersion":"9.3","automationName":"XCUITest","browserName":"","platformName":"iOS","deviceName":"iPhone 6","launchTimeout":500000,"wdaLocalPort":"8100"},{},{"desiredCapabilities":{"app":"/Users/KishanRavindra/Desktop/DocDock.app","networkConnectionEnabled":true,"platformVersion":"9.3","automationName":"XCUITest","browserName":"","platformName":"iOS","deviceName":"iPhone 6","launchTimeout":500000,"wdaLocalPort":"8100"},"requiredCapabilities":{},"alwaysMatch":{"browserName":"","platformName":"iOS"},"firstMatch":[]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1517585040657 (20:54:00 GMT+0530 (IST))
[Appium] Creating new XCUITestDriver (v2.51.1) session
[Appium] Capabilities:
[Appium]   app: '/Users/KishanRavindra/Desktop/DocDock.app'
[Appium]   platformVersion: '10.0'
[Appium]   automationName: 'XCUITest'
[Appium]   browserName: ''
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'iPhone 7'
[Appium]   launchTimeout: 500000
[Appium]   wdaLocalPort: '8100'
[BaseDriver] Capability 'wdaLocalPort' changed from string ('8100') to integer (8100). This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by appium: networkConnectionEnabled.
[BaseDriver] Session created with session id: 03c454c8-7167-44a6-9366-d2e6b770b675
[debug] [XCUITest] Xcode version set to '9.2' (tools v9.2.0.0.1.1510905681)
[debug] [XCUITest] iOS SDK Version set to '11.2'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1517585040975 (20:54:00 GMT+0530 (IST))
[iOSSim] Constructing iOS simulator for Xcode version 9.2 with udid 'E9C7C4E0-F9FE-4258-A8BA-21ADF5F08B3A'
[XCUITest] Determining device to run tests on: udid: 'E9C7C4E0-F9FE-4258-A8BA-21ADF5F08B3A', real device: false
[BaseDriver] Using local app '/Users/KishanRavindra/Desktop/DocDock.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1517585041539 (20:54:01 GMT+0530 (IST))
[debug] [XCUITest] Checking whether app '/Users/KishanRavindra/Desktop/DocDock.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [iOS] Getting bundle ID from app '/Users/KishanRavindra/Desktop/DocDock.app': 'com.docdock.ios'
[debug] [BaseDriver] Event 'resetStarted' logged at 1517585041560 (20:54:01 GMT+0530 (IST))
[XCUITest] Not scrubbing third party app in anticipation of uninstall
[debug] [BaseDriver] Event 'resetComplete' logged at 1517585041716 (20:54:01 GMT+0530 (IST))
[debug] [iOSLog] Starting iOS 9.3 simulator log capture
[debug] [iOSLog] System log path: /Users/KishanRavindra/Library/Logs/CoreSimulator/E9C7C4E0-F9FE-4258-A8BA-21ADF5F08B3A/system.log
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1517585042276 (20:54:02 GMT+0530 (IST))
[XCUITest] Setting up simulator
[debug] [iOS] No reason to set locale
[debug] [iOS] No iOS / app preferences to set
[debug] [iOSSim] Setting common Simulator preferences to {"ConnectHardwareKeyboard":false}
[debug] [iOSSim] Updated shared Simulator preferences at '/Users/KishanRavindra/Library/Preferences/com.apple.iphonesimulator.plist' with {"ConnectHardwareKeyboard":false}
[debug] [iOSSim] The count of running Simulator UI client instances is 0
[iOSSim] Booting Simulator with UDID E9C7C4E0-F9FE-4258-A8BA-21ADF5F08B3A...
[iOSSim] Starting Simulator UI with command: open -Fn /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID E9C7C4E0-F9FE-4258-A8BA-21ADF5F08B3A -ConnectHardwareKeyboard 0
[debug] [iOSSim] The count of running Simulator UI client instances is 1
[iOSSim] Simulator with UDID E9C7C4E0-F9FE-4258-A8BA-21ADF5F08B3A booted in 423 seconds
[debug] [BaseDriver] Event 'simStarted' logged at 1517585465660 (21:01:05 GMT+0530 (IST))
[debug] [XCUITest] Reset requested. Removing app with id 'com.docdock.ios' from the device
[debug] [XCUITest] Installing '/Users/KishanRavindra/Desktop/DocDock.app' on Simulator with UUID 'E9C7C4E0-F9FE-4258-A8BA-21ADF5F08B3A'...
[debug] [XCUITest] The app has been installed successfully.
[debug] [BaseDriver] Event 'appInstalled' logged at 1517585537471 (21:02:17 GMT+0530 (IST))
[XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[debug] [XCUITest] Capability 'useNewWDA' set to false, so trying to reuse currently running WDA instance at 'http://localhost:8100/'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] WDA is not listening at 'http://localhost:8100/'. Rebuilding...
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1517585538250 (21:02:18 GMT+0530 (IST))
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Error: Carthage not found. Install using `brew install carthage`
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at checkForDependencies$ (../../../lib/wda/utils.js:59:9)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
 Error: Carthage not found. Install using `brew install carthage`
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at checkForDependencies$ (../../../lib/wda/utils.js:59:9)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1517585538463 (21:02:18 GMT+0530 (IST))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: "Carthage not found. Install using `brew install carthage`".
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by imurchie** [comment]
Do you have Carthage installed?

What happens if you run `carthage version`?
