### ISSUE TITLE
iOS getAlertText not behaving as expected (XCUITestDriver + Java Client)

### ISSUE THREAD

**Issue by fuzzybinary** [appium/appium#10111]
## The problem

Using the Java Client with XCUITestDriver for iOS, I expect the following code to wait until an alert is displayed:
```
WebDriverWait wait = new WebDriverWait(driver, 10, 1000);
wait.until(ExpectedConditions.alertIsPresent());
```

Unfortunately, this throws with an unexpected exception. Looking at the java Selenium client that java appium client is based on, the expectation is looking to catch a NoAlertPresentException. It appears that the XCUITestDriver is replying with the correct error code / status, but either the Appium driver is not interpreting this status correctly, it's not handing it back to the Java Client correctly, or the Java Client is not throwing the error as the proper NoAlertPresentException. I can't tell exactly where the problem lies.

## Environment

* Appium version: 8093a3512132f226b2076ca83a3262fe717fe3e2
** appium-base-driver version (which is where I think the problem actually lies): 074697f0615ddf94672dc316292817ac79977893
* Desktop OS/version used to run Appium: macOS
* Node.js version (unless using Appium.app|exe): v6.9.5
* Mobile platform/version under test: iOS Simulator 11.2
* Appium CLI or Appium.app|exe: From Code

## Link to Appium logs

https://gist.github.com/fuzzybinary/31fabff71ec6dffc8fc2762a1e2bada4

Note there's some logging from a helper library conductor-mobile in the java output.

## Code To Reproduce Issue

In above description.

**Comment by mykola-mokhnach** [comment]
@dpgraham Can you please take look?

**Comment by dpgraham** [comment]
Yeah it's an Appium problem that was fixed with this pull request: https://github.com/appium/appium-base-driver/pull/182/files#diff-769ba2e002901f7a9c289114bc28aa9bL443

If you reinstall the latest Appium beta the problem should go away.

**Comment by fuzzybinary** [comment]
Most of my team is still on 1.7.x. Will this fix come through in an npm update against 1.7 or do we need to be on 1.8?

**Comment by mykola-mokhnach** [comment]
it's available in appium@beta, which is gonna be 1.8.9 at some point of time

**Comment by dpgraham** [comment]
@mykola-mokhnach Is there a way to force use JSONWP on the Java Client?

**Comment by mykola-mokhnach** [comment]
@dpgraham https://github.com/appium/java-client/pull/829

**Comment by mykola-mokhnach** [comment]
Closing as fixed for. @fuzzybinary Let us know if there are still problems in beta
