### ISSUE TITLE
Appium is giving error code 500 on sendKeys for textbox on a Android app developed in ReactNative

### ISSUE THREAD

**Issue by Hashili** [appium/appium#10121]
## The problem

Appium is giving error code 500 on sendKeys.

## Environment

* Appium version: 1.7.1
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android 6.0
* Real device or emulator/simulator:Real Device
* Appium CLI 

## Details

I am testing an android tablet application developed on ReactNative. I am getting error code 500 on sendKeys to some text boxes. The issue exists only with few text boxes on the application.

## Link to Appium logs

[HTTP] <-- GET /wd/hub/session/2712e85a-0a09-4730-84c0-1759e59a6c8c 200 5 ms - 991
[HTTP] --> POST /wd/hub/session/2712e85a-0a09-4730-84c0-1759e59a6c8c/element/24/value {"id":"24","value":["addeded 3"]}
[debug] [MJSONWP] Calling AppiumDriver.setValue() with args: [["addeded 3"],"24","2712e85a-0a09-4730-84c0-1759e59a6c8c"][debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:setText","params":{"elementId":"24","text":"addeded 3","replace":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:setText","params":{"elementId":"24","text":"addeded 3","replace":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: setText
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using element passed in: 24
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Attempting to clear using UiObject.clearText().
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":7,"value":"UiSelector[CLASS=android.widget.EditText, INSTANCE=2]"}
[debug] [AndroidBootstrap] Received command result from bootstrap
[HTTP] <-- POST /wd/hub/session/2712e85a-0a09-4730-84c0-1759e59a6c8c/element/24/value 500 26539 ms - 164
[HTTP] --> GET /wd/hub/session/2712e85a-0a09-4730-84c0-1759e59a6c8c/screenshot {}
[debug] [MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["2712e85a-0a09-4730-84c0-1759e59a6c8c"]
[debug] [ADB] Device API level: 23

## Code To Reproduce Issue [ Good To Have ]
The code is very straight forward sendKeys.

**Comment by mykola-mokhnach** [comment]
Try switching to uiautomator2 automation backend.

**Comment by Hashili** [comment]
Thanks a lot @mykola-mokhnach that is an awesome tweak. This solved the issue.. 
But now most of the xpath i have created previously of the app is not working. Is there any workaround for that

**Comment by mykola-mokhnach** [comment]
You'll have to update some locators though. UIAutomator 1 is anyway not supported anymore by Google since Android 5.
