### ISSUE TITLE
StackOverflowError UIAutomatorTestRunner

### ISSUE THREAD

**Issue by kevinyl18** [appium/appium#10126]
## The problem

Suddenly my test always closing session and can not recover.

## Environment

* Appium version (or git revision) that exhibits the issue: **1.7.1**, **1.7.2**
* Last Appium version that did not exhibit the issue (if applicable): **1.7.1**
* Desktop OS/version used to run Appium: **Ubuntu 16.0.4**
* Node.js version (unless using Appium.app|exe):. **6.11.5**, **8.9.4** 
* Mobile platform/version under test: **Android 4.4**, **Android 5.1**
* Real device or emulator/simulator: **Real Device**
* Appium CLI or Appium.app|exe: **Appium CLI**

## Details
I have a hybrid apps. I did not upgrade my environment, appium server-args, & the appium capabilities.

Recently i notice that the session is always closed and give error : `WebDriverException: Message: A session is either terminated or not started` when executing some test and then can not recover from it. The UiAutomator give this error : `[debug] [AndroidDriver] Shutting down Android driver
[Appium] Closing session, cause was 'UiAUtomator shut down unexpectedly'`

I notice from the log that the current session is removed

```[Appium] Removing session accb0c27-b80d-4007-9739-99809a45b0b6 from our master session list
[debug] [AndroidDriver] Stopping chromedriver for context WEBVIEW_com.test.test
[debug] [Chromedriver] Changed state to 'stopping'
[debug] [JSONWP Proxy] Proxying [DELETE /] to [DELETE http://127.0.0.1:9920/wd/hub/session/d6f34483546ba631550aa20a23c37885] with no body
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"d6f34483546ba631550aa20a23c37885","status":0,"value":[{"ELEMENT":"0.5809627464323741-1"}]}
```

And replaced 
```
[JSONWP Proxy] Replacing sessionId d6f34483546ba631550aa20a23c37885 with accb0c27-b80d-4007-9739-99809a45b0b6
[HTTP] <-- POST /wd/hub/session/accb0c27-b80d-4007-9739-99809a45b0b6/elements 200 2393 ms - 108 
```

And it tries communicate with already deleted session (notice the session id)
```
POST /wd/hub/session/accb0c27-b80d-4007-9739-99809a45b0b6/elements {"using":"css selector","sessionId":"accb0c27-b80d-4007-9739-99809a45b0b6","value":"a[id*=signin]"}
[HTTP] <-- POST /wd/hub/session/accb0c27-b80d-4007-9739-99809a45b0b6/elements 404 1 ms - 131 
```

## Findings on logcat
```
E/UiAutomatorTestRunner(13686): uncaught exception
E/UiAutomatorTestRunner(13686): java.lang.StackOverflowError: stack size 1036KB
E/UiAutomatorTestRunner(13686):         at android.util.LongArray.clone(LongArray.java:117)
E/UiAutomatorTestRunner(13686):         at android.view.accessibility.AccessibilityNodeInfo.init(AccessibilityNodeInfo.java:2711)
E/UiAutomatorTestRunner(13686):         at android.view.accessibility.AccessibilityNodeInfo.obtain(AccessibilityNodeInfo.java:2529)
E/UiAutomatorTestRunner(13686):         at android.view.accessibility.AccessibilityCache.getNode(AccessibilityCache.java:178)
E/UiAutomatorTestRunner(13686):         at android.view.accessibility.AccessibilityInteractionClient.findAccessibilityNodeInfoByAccessibilityId(AccessibilityInteractionClient.java:273)
E/UiAutomatorTestRunner(13686):         at android.view.accessibility.AccessibilityNodeInfo.getChild(AccessibilityNodeInfo.java:783)
E/UiAutomatorTestRunner(13686):         at com.android.uiautomator.core.QueryController.findNodeRegularRecursive(QueryController.java:327)
E/UiAutomatorTestRunner(13686):         at com.android.uiautomator.core.QueryController.findNodeRegularRecursive(QueryController.java:343)
...
```

please help me

**Comment by mykola-mokhnach** [comment]
Can you please attach the full log?

**Comment by mykola-mokhnach** [comment]
I'd also try to reboot the devices under test from time to time, since it quite possible that they experience memory leaks

**Comment by viccky88** [comment]
I am also getting same error.

Environment:

Appium version (or git revision) that exhibits the issue: 1.6.5
Desktop OS/version used to run Appium: MacOS sierra 10.12.6
Mobile platform/version under test: Android 7.0.1
Real device or emulator/simulator: Real Device
Appium CLI or Appium.app|exe: Appium CLI

**Comment by kevinyl18** [comment]
i change the automation to uiAutomator2, hope it solve your issue.

**Comment by jlennox** [comment]
@mykola-mokhnach 

Device logs: https://gist.github.com/jlennox/b2936ba04f53f41916c3778331f10b36
Appium logs: https://gist.github.com/jlennox/3639901543c1347ed221484535cd6f4b

The issue is triggered by:
https://github.com/appium/appium-android-bootstrap/blob/master/bootstrap/src/io/appium/android/bootstrap/utils/TheWatchers.java#L51

The returned value and any side affects appear to be completely void piped? The only consumer is: https://github.com/appium/appium-android-bootstrap/blob/e0df190e35baccf31b4e2af81db75cff580631a1/bootstrap/src/io/appium/android/bootstrap/SocketServer.java#L140

Enabling the capability `disableAndroidWatchers` appears to "fix" the issue, but has the side effect of disabling what appears to be otherwise very nice condition checks: https://github.com/appium/appium-android-bootstrap/blob/master/bootstrap/src/com/android/uiautomator/common/UiWatchers.java#L39

I do not know if what appears to be dead code that triggers this issue was removed/"fixed" if this issue would surface inside the other watchers.

**Comment by mykola-mokhnach** [comment]
Thanks for investigation @jlennox. Can you please report it as a separate issue?

**Comment by jlennox** [comment]
I have opened issue #10204
