### ISSUE TITLE
appium uiautomator2 always repeat to unlock the device ,no end,why?

### ISSUE THREAD

**Issue by WenRui13** [appium/appium#10128]
## The problem

appium uiautomator2 always repeat to unlock the device ,no end
Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment
Appium version 1.7.2
Node.js version 8.9.1
Real device  android 7.1.1

## Details

other device can be unlocked,   for example on andriod7.0 with the same appium and uiautomator2

## Link to Appium logs
appium log is bellow:
https://gist.github.com/WenRui13/ae84c8422f43c7139239c5201b372579

## Code To Reproduce Issue [ Good To Have ]

    @Parameters(["port", "udid", "deviceName", "platformVersion"])
    @BeforeClass
    void startDriver(String port, String udid, String deviceName, String platformVersion) {
        def capabilities = new DesiredCapabilities(
                platformName: "Android",
                platformVersion: platformVersion,
                browserName: "",
                deviceName: deviceName,
                uuid: udid,
                appPackage: "com.xstore.sevenfresh",
                appActivity: "com.xstore.sevenfresh.activity.MainActivity",
                ignoreUnimportantViews: "true",
                "autoGrantPermissions": "true",
//                "unicodeKeyboard": "true",
                "resetKeyboard": "true",
                "noReset": "true",
//                "newCommandTimeout": "30",
                "automationName": platformVersion > "5.0" ? "uiautomator2" : "Appium"

        )

        //uiautomator2默认使用系统闲置端口，未避免端口冲突也可指定端口
//        if (platformVersion > "5.0") {
//            capabilities.setCapability("systemPort", "4728")
//        }
//        driver = new AndroidDriver(this.service.getUrl(), capabilities)
        driver = new AndroidDriver(new URL("http://10.1.64.83:4723/wd/hub"), capabilities)
//        driver = new AndroidDriver(new URL("http://10.1.64.83:$port/wd/hub"), capabilities)
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS)
    }

**Comment by WenRui13** [comment]
ps: the language is groovy

**Comment by mykola-mokhnach** [comment]
Try to set skipUnlock capability to true. It is known, that unlock utility may not work properly on some devices. You may propose a PR if you know how to fix it.

**Comment by WenRui13** [comment]
nice , the problem has be solved followed by your configuration, tks a lot.

**Comment by WenRui13** [comment]
another problem is when unicodeKeyboard is set "true", appium android input manager unicode always need to be install on device and need to confirm by hand in condition of   "autoGrantPermissions" set to "true", if not ,the test will be suck

**Comment by mykola-mokhnach** [comment]
> appium android input manager unicode always need to be install on device and need to confirm by hand in condition of "autoGrantPermissions" set to "true"

Can you provide a screenshot about where the tools requires additional permissions? As far as I remember the UnicodeIME application does not requires any additional system permissions.
