### ISSUE TITLE
Appium always showing Waiting up to 20000ms for UiAutomator2 to be online. This works fine on unplug and re plug the device

### ISSUE THREAD

**Issue by Hashili** [appium/appium#10123]
## The problem

Appium always showing Waiting up to 20000ms for UiAutomator2 to be online. This works fine on unplug and re plug the device

## Environment

* Appium version (or git revision) that exhibits the issue:1.7.1
* Desktop OS/version used to run Appium:Windows
* Mobile platform/version under test:Android 6.0
* Real device
* Appium CLI 

## Link to Appium logs

[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\AndroidSDK\adt-bundle-windows-x86_64\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","320467e8308471c9","shell","am","force-stop","io.appium.uiautomator2.server"]
[UiAutomator2] Starting uiautomator2 server v0.1.8
[UiAutomator2] Running command: 'adb -s 320467e8308471c9 shell am instrument -w io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner'
[UiAutomator2] Waiting up to 20000ms for UiAutomator2 to be online...
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body

## Code To Reproduce Issue [ Good To Have ]

Usual capabilities

**Comment by mykola-mokhnach** [comment]
Can you also attach logcat output?

**Comment by Hashili** [comment]
@mykola-mokhnach  Got the below Error

[debug] [UiAutomator2] [UIAutomator2] io.appium.uiautomator2.server.test.AppiumUiAutomator2Server:INSTRUMENTATION_RESULT: shortMsg=Process crashed.

[debug] [UiAutomator2] [UIAutomator2] INSTRUMENTATION_CODE: 0

[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: Error: Trying to proxy a session command without session id
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\AndroidSDK\adt-bundle-windows-x86_64\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","320467e8308471c9","shell","am","force-stop","com.planready.test"]
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8200 
[debug] [ADB] Running 'C:\AndroidSDK\adt-bundle-windows-x86_64\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","320467e8308471c9","forward","--remove","tcp:8200"]
[MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Error: read ECONNRESET
    at JWProxy.proxy$ (../../../lib/jsonwp-proxy/proxy.js:152:13)
    at tryCatch (C:\Users\Hashili.MA\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Hashili.MA\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\Hashili.MA\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\Hashili.MA\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at <anonymous>
[HTTP] <-- POST /wd/hub/session 500 407923 ms - 217 
FAILED CONFIGURATION: @BeforeSuite setUp
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET (WARNING: The server did not provide any stacktrace information)

**Comment by mykola-mokhnach** [comment]
This is the server log, but not the logcat output. You can try to reboot the device under test from time to time to make sure there are no memory/resource leaks, which can lead to automation failures

**Comment by Hashili** [comment]
The issue is not reproducible on a latest high configuration tablet. But it is still present on a low profile device.closing the issue

**Comment by swathiJaya** [comment]
Im facing the same issue in Google Pixel, android 8

**Comment by surajgupta7175** [comment]
sameissue +1
