### ISSUE TITLE
can not input unicode text in native app

### ISSUE THREAD

**Issue by mehrdad-abdoli** [appium/appium#10122]
## The problem

I have set unicodeKeyboard to true but on Real device and emulators the input text is blank with no error.
Appium does not install unicode IME itself and I have installed it manually by adb:
adb install /usr/lib/node_modules/appium/node_modules/appium-android-ime/bin/UnicodeIME-debug.apk
adb shell ime enable io.appium.android.ime/.UnicodeIME
adb shell ime set io.appium.android.ime/.UnicodeIME

## Environment

* Appium version 1.7.2 and 1.7.1:
* Desktop OS/version used to run Appium:
tested on android dockers on UBuntu 16 
tested on Real device on windows 10
* Mobile platform/version under test:
android 5.1.1  6.0   7.1.1
* Real device or emulator/simulator: Both
* Appium CLI or Appium.app|exe: Both

## Link to Appium logs

https://gist.github.com/mehrdad-abdoli/d237dff0d2cdb76a8b4e4d3f75b442db

## Code To Reproduce Issue [ Good To Have ]
*** Settings ***
Library           AppiumLibrary

*** Variables ***
${REMOTE_URL}     http://localhost:4723/wd/hub
${PLATFORM_NAME}    Android
${PLATFORM_VERSION}    6.0
${DEVICE_NAME}    Android Emulator
${APP}            ${CURDIR}/ContactManager.apk

*** Test Cases ***
add_contact
    [Documentation]    demo for android_contacts(https://github.com/appium/sample-code/blob/master/sample-code/examples/python/android_contacts.py)
    [Tags]    demo
    add new contact    مهرداد عبدلی    someone@appium.io    5555555555
    Page Should Contain Text    مهرداد عبدلی

*** Keywords ***
add new contact
    [Arguments]    ${contact_name}    ${contact_phone}    ${contact_email}
    Open Application  ${REMOTE_URL}  platformName=Android  platformVersion=${PLATFORM_VERSION}  deviceName=LGK430GYPJZDVW  app=${APP}  automationName=appium  appPackage=com.example.android.contactmanager   unicodekeyboard=true    resetkeyboard=true
    Click Element    accessibility_id=Add Contact
    Input Text    xpath=//android.widget.TableLayout[@index='0']/android.widget.TableRow[@index='3']/android.widget.EditText[@index='0']    ${contact_name}
    Input Text    xpath=//android.widget.TableLayout[@index='0']/android.widget.TableRow[@index='5']/android.widget.EditText[@index='0']     ${contact_phone}
    Input Text    xpath=//android.widget.TableLayout[@index='0']/android.widget.TableRow[@index='7']/android.widget.EditText[@index='0']    ${contact_email}
    Click Element    accessibility_id=Save

**Comment by mykola-mokhnach** [comment]
> [warn] [BaseDriver] The following capabilities were provided, but are not recognized by appium: unicodekeyboard, resetkeyboard.


Are you sure that correct capabilities are provided?

**Comment by mehrdad-abdoli** [comment]
@mykola-mokhnach 
Great Job it was spell problem as:
 unicode**k**eyboard   -- >  unicode**K**eyboard   
 reset**k**eyboard  -- > reset**K**eyboard
thanks 👍
