### ISSUE TITLE
java.net.MalformedURLException trying to connect to real Android device via Appium

### ISSUE THREAD

**Issue by nast9nat4uk** [appium/appium#10127]
## The problem

I tried to connect to physical Android device via Appium. After updating Java version it gives me an error: java.net.MalformedURLException

## Environment

* Appium v1.7.2
* Desktop OS/version used to run Appium: Windows 10
* Node.js version : v8.9.4
* Mobile platform/version under test: Android 7.1.1
* Real device : Samsung Galaxy J5
* Appium CLI or Appium.app|exe: Appium.app|exe
* java version: 1.8.0_161

## Details

Before updating Java version this step (connecting to Appium using URL was passed successfully)

## Appium logs
[info] [Appium] Welcome to Appium v1.7.2
[info] [Appium] Appium REST http interface listener started on 0.0.0.0:4723
that's it. 

## Code To Reproduce Issue:

public class LoginLogoutTest {

    private DesiredCapabilities cap;
    private WebDriver driver;
    private String apkpath;
    private WebElement myAccountButton;
    private WebElement greeting;

    @BeforeClass
    public void startServer() throws Exception {

        apkpath =Data.getDataProperties("apkfullpath");
        //Set Capabilities
        cap = new DesiredCapabilities();
        cap.setCapability("platformName", "Android");
        cap.setCapability("appPackage", apkpath);
        cap.setCapability("deviceName","73c1e4ca");
        cap.setCapability("platformVersion", "7.1.1");
        driver = new RemoteWebDriver(new URL(Data.getDataProperties("appuimhost")), cap);
}

NOTE:
appuimhost was set in system.properties file as below:
appiumhost = http://0.0.0.0:4723/wd/hub

## IDEA error:
![screenshot_1](https://user-images.githubusercontent.com/25705490/35793891-81c9d982-0a64-11e8-9f3b-9a5444bc65da.jpg)

**Comment by mykola-mokhnach** [comment]
It's the exception on your side. Nothing we can do about it.
