### ISSUE TITLE
An unknown server-side error occurred while processing the command. Original error: Failed to start Chromedriver session: An error occurred (Original error: chrome not reachable

### ISSUE THREAD

**Issue by vijenkamboj** [appium/appium#10129]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by vijenkamboj** [comment]
chrome driver:2.35
chrome version :63 both
ANDorid:6
appium versoin:1.7.2

**Comment by vijenkamboj** [comment]
Can any body help on this

**Comment by trix0** [comment]
Well, You didnt tell us much :) Could you please fill all the information that are in the blueprint ? It ll speed up whole process

**Comment by vijenkamboj** [comment]
I am testing a hybrid app with the following code:
package Alchemy.Alchemy;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.Set;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.remote.DesiredCapabilities;
import io.appium.java_client.MobileElement;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.remote.AndroidMobileCapabilityType;
import io.appium.java_client.remote.MobileCapabilityType;
import io.appium.java_client.remote.MobilePlatform;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;
public class SmokeTestAlchemy
{
 public AndroidDriver<MobileElement>  driver;

      @BeforeTest
		public void setup() throws MalformedURLException, InterruptedException 
	{
		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME,MobilePlatform.ANDROID);
		capabilities.setCapability(MobileCapabilityType.UDID,"ZY223R9XDP");//Give Device ID of your mobile phone
		capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION,"6.0.1");
		capabilities.setCapability(MobileCapabilityType.DEVICE_NAME,"Moto G4");
    	capabilities.setCapability("app", "G://android-armv7-debug.apk");
		//capabilities.setCapability(AndroidMobileCapabilityType.APP_PACKAGE,"com.ecifm.otgservices");
	//	capabilities.setCapability(AndroidMobileCapabilityType.APP_ACTIVITY,"com.ecifm.otgservices.MainActivity");
	    capabilities.setCapability("fullReset","true");
	    capabilities.setCapability("autowebview", true);
	    capabilities.setCapability(AndroidMobileCapabilityType.RECREATE_CHROME_DRIVER_SESSIONS, true);
	    capabilities.setCapability("newCommandTimeout", "120");
	    capabilities.setCapability("chromedriverExecutable", "C://Users//vijender.kumar//chromedriver.exe");
	  
	    
	
	  driver =new AndroidDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
	     
	    
	    driver.manage().timeouts().implicitlyWait(30L, TimeUnit.SECONDS);
	   
	   // WebView.setWebContentsDebuggingEnabled(true);
	    /*WebDriverWait  some_element = new WebDriverWait(driver,100); 
	    some_element.until(ExpectedConditions.visibilityOfElementLocated(By.id("pageTitle")));*/
	   
	   	}


	@Test
	public void operation() 
	{
		System.out.println("operation() :: driver.start() executed");
		try{	
		Set<String> availableContexts = driver.getContextHandles();
		System.out.println("Total No of Context Found After we reach to WebView = "+ availableContexts.size());
		for(String context : availableContexts) {
			if(context.toString().toUpperCase().contains("WEBVIEW")){
				System.out.println("Context Name is " + context);
				// 4.3 Call context() method with the id of the context you want to access and change it to WEBVIEW_1
				//(This puts Appium session into a mode where all commands are interpreted as being intended for automating the web view)
				driver.context(context);
				driver.context(context);
				driver.findElement(By.xpath("//input[@type='text']")).sendKeys("bworking");
			
			}	
				
		
		}
		}catch(Exception ex){
			ex.printStackTrace();
		
		}
	}
	



	
	//driver.findElement(By.xpath("//input[@type='text']")).sendKeys("bworking");
	

  
   @AfterTest(alwaysRun= true)
	public void teardown() {
		driver.quit();
	}
}
------------------------------
chrome driver:2.35
chrome version :63 both
ANDorid:6
appium versoin:1.7.2
--------------------------------------
error I am getting:
An unknown server-side error occurred while processing the command. Original error: Failed to start Chromedriver session: An error occurred (Original error: chrome not reachable
  (Driver info: chromedriver=2.35.528161 (5b82f2d2aae0ca24b877009200ced9065a772e73),platform=Windows NT 6.1.7601 SP1 x86_64)) (WARNING: The server did not provide any stacktrace information)

**Comment by vijenkamboj** [comment]
please help

**Comment by trix0** [comment]
Heyo @vijenkamboj Looks like chrome driver does not like you :) Have you tried different version of chrome driver ?

**Comment by mykola-mokhnach** [comment]
Make sure your webview is debuggable by connecting to it manually with chrome remote debugger. If it is then make sure you use the correct chromedriver version. Read https://github.com/appium/appium/blob/909694b39d8a110c50b267341b3b911be468bbae/docs/en/writing-running-appium/web/chromedriver.md for more details

**Comment by vijenkamboj** [comment]
but my configurations are latest:chrome driver:2.35
chrome version :63 both
ANDorid:6
appium versoin:1.7.2

**Comment by vijenkamboj** [comment]
How to check this "Make sure your webview is debuggable by connecting to it manually with chrome remote debugger"

**Comment by vijenkamboj** [comment]
package Alchemy.Alchemy;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.Set;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;
import io.appium.java_client.MobileElement;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.remote.AndroidMobileCapabilityType;
import io.appium.java_client.remote.MobileCapabilityType;
import io.appium.java_client.remote.MobilePlatform;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

public class SmokeTestAlchemy {
	public AndroidDriver<MobileElement> driver;

	@BeforeTest
	public void setup() throws MalformedURLException, InterruptedException {
		DesiredCapabilities capabilities = new DesiredCapabilities();

		capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, MobilePlatform.ANDROID);

		capabilities.setCapability(MobileCapabilityType.UDID, "ZY223R9XDP");
		
		// capabilities.setCapability("UDID", "ZY223R9XDP");
	
		capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "6.0.1");

		capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Moto G4");
		// capabilities.setCapability("app", "G://android-armv7-debug.apk");

		capabilities.setCapability(AndroidMobileCapabilityType.APP_PACKAGE,"com.ecifm.otgservices");
		capabilities.setCapability(AndroidMobileCapabilityType.APP_ACTIVITY,"com.ecifm.otgservices.MainActivity");
		
		capabilities.setCapability("autowebview", true);
		capabilities.setCapability("browsername", "chrome");
	
		driver = new AndroidDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
		Thread.sleep(15000);

	}

	@Test
	public void operation() throws InterruptedException {

		System.out.println("operation() :: driver.start() executed");
		Thread.sleep(2500);
		Set<String> contextNames = driver.getContextHandles();
	     for (String contextName : contextNames) {
	     System.out.println(contextName);
	     if (contextName.contains("WEBVIEW")){
	     driver.context(contextName);
	     System.out.println(contextName);
	     Thread.sleep(1500);  
	     final WebElement inputField = driver.findElement(By.xpath("//input[@class='ng-untouched ng-pristine ng-valid mbsc-control']"));
	     inputField.sendKeys("abc");


	/*
	 * @AfterTest(alwaysRun = true) public void teardown() { driver.quit();
	 */
}
	}
	}}

**Comment by vijenkamboj** [comment]
Error:
RemoteTestNG] detected TestNG version 6.13.1
Feb 09, 2018 10:56:20 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
operation() :: driver.start() executed
NATIVE_APP
WEBVIEW_com.ecifm.otgservices
FAILED: operation
io.appium.java_client.NoSuchContextException: An unknown server-side error occurred while processing the command. Original error: Failed to start Chromedriver session: An error occurred (Original error: chrome not reachable
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.5.2', revision: '10229a9', time: '2017-08-21T17:29:55.15Z'
System info: host: 'VIJENDRAK', ip: '192.168.168.235', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_121'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{appPackage=com.ecifm.otgservices, deviceScreenSize=1080x1920, networkConnectionEnabled=true, warnings={}, browsername=chrome, databaseEnabled=false, deviceName=ZY223R9XDP, platform=LINUX, deviceUDID=ZY223R9XDP, appActivity=com.ecifm.otgservices.MainActivity, autowebview=true, desired={appPackage=com.ecifm.otgservices, appActivity=com.ecifm.otgservices.MainActivity, autowebview=true, platformVersion=6.0.1, browsername=chrome, platformName=Android, udid=ZY223R9XDP, deviceName=Moto G4}, platformVersion=6.0.1, webStorageEnabled=false, locationContextEnabled=false, takesScreenshot=true, javascriptEnabled=true, deviceModel=Moto G (4), platformName=Android, udid=ZY223R9XDP, deviceManufacturer=motorola}]
Session ID: 7992599b-8944-4940-8a98-dd8766c36a06
	at io.appium.java_client.AppiumDriver.context(AppiumDriver.java:216)
	at Alchemy.Alchemy.SmokeTestAlchemy.operation(SmokeTestAlchemy.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\

**Comment by vijenkamboj** [comment]
chrome driver:2.33
chrome version :63 both
appium versoin:1.7.2

**Comment by vijenkamboj** [comment]
package Alchemy.Alchemy;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.Set;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;
import io.appium.java_client.MobileElement;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.remote.AndroidMobileCapabilityType;
import io.appium.java_client.remote.MobileCapabilityType;
import io.appium.java_client.remote.MobilePlatform;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

public class SmokeTestAlchemy {
	public AndroidDriver<MobileElement> driver;

	@BeforeTest
	public void setup() throws MalformedURLException, InterruptedException {
		DesiredCapabilities capabilities = new DesiredCapabilities();

		capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, MobilePlatform.ANDROID);

		capabilities.setCapability(MobileCapabilityType.UDID, "ZY223R9XDP");

		// capabilities.setCapability("UDID", "ZY223R9XDP");

		capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "6.0.1");

		capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Moto G4");
		// capabilities.setCapability("app", "G://android-armv7-debug.apk");

		capabilities.setCapability(AndroidMobileCapabilityType.APP_PACKAGE, "com.ecifm.otgservices");
		capabilities.setCapability(AndroidMobileCapabilityType.APP_ACTIVITY, "com.ecifm.otgservices.MainActivity");

		capabilities.setCapability("autowebview", true);
		capabilities.setCapability("browsername", "Chrome");
		/*
		 * capabilities.setCapability(MobileCapabilityType.BROWSER_NAME,"Chrome"
		 * ); capabilities.setCapability("autowebview", true);
		 */

		driver = new AndroidDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
		// Thread.sleep(1500);

	}

	@Test
	public void operation() throws InterruptedException {

		System.out.println("operation() :: driver.start() executed");
		//Thread.sleep(2500);
		Set<String> contextNames = driver.getContextHandles();
	     for (String contextName : contextNames) {
	     System.out.println("context name================"+contextName);
	     if (contextName.contains("NATIVE_APP")){
	     driver.context(contextName);
	     System.out.println(contextName);
	  //   Thread.sleep(1500);  
	     System.out.println("Hi======================"+contextName);
	     final WebElement inputField = driver.findElement(By.xpath("//input[@class='ng-untouched ng-pristine ng-valid mbsc-control']"));
	     inputField.sendKeys("abc");
	     System.out.println("Hello================="+contextName);

}else
		{
		driver.context(contextName);
System.out.println(contextName);
		}
	}
	}
}

**Comment by vijenkamboj** [comment]
Hybrid app written using corodova -Ionic framework
_________________________________
my configurations 
Andorid ->6.0.1
appum version:1.7.2
chrome driver:2.35
java-client-5.0.0
chrome version :63 both
ANDorid sdk:3.0.1	
appium -a 127.0.0.1 -p 4723
device API level:24
----------------------------------------------------------------------
code 
package Alchemy.Alchemy;

import static org.testng.Assert.assertEquals;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.Set;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.support.ui.WebDriverWait;

import io.appium.java_client.MobileElement;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.pagefactory.AndroidBy;
import io.appium.java_client.remote.AndroidMobileCapabilityType;
import io.appium.java_client.remote.MobileCapabilityType;
import io.appium.java_client.remote.MobilePlatform;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

public class SmokeTestAlchemy {
	public AndroidDriver<MobileElement> driver;

	@BeforeTest
	public void setup() throws MalformedURLException, InterruptedException {
		DesiredCapabilities capabilities = new DesiredCapabilities();

		capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, MobilePlatform.ANDROID);

		capabilities.setCapability(MobileCapabilityType.UDID, "ZY223R9XDP");

		// capabilities.setCapability("UDID", "ZY223R9XDP");

		capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "6.0.1");

		capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Moto G4");
		// capabilities.setCapability("app", "G://android-armv7-debug.apk");

		capabilities.setCapability(AndroidMobileCapabilityType.APP_PACKAGE, "com.ecifm.otgservices");
		capabilities.setCapability(AndroidMobileCapabilityType.APP_ACTIVITY, "com.ecifm.otgservices.MainActivity");

		capabilities.setCapability("autowebview", true);
		capabilities.setCapability("browsername", "Chrome");
		capabilities.setCapability("setWebContentsDebuggingEnabled", "true");
		capabilities.setCapability("autowebview", true);

		driver = new AndroidDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);

		// Thread.sleep(1500);

	}

	@Test
	public void operation() throws InterruptedException {

		System.out.println("operation() :: driver.start() executed");
		// Thread.sleep(2500);
		By webView = By.className("android.webkit.WebView");
		// By title = By.id("pageTitle");

		// WebDriverWait wait = new WebDriverWait(driver, 300);
		// driver.findElement(title).getText();
		Set<String> availableContexts1 = driver.getContextHandles();
		System.out.println("Total No of Context Found Before reaching WebView = " + availableContexts1.size());
		System.out.println("Context Name is " + availableContexts1);
		for (String context : availableContexts1) {
			if (context.contains("WEBVIEW")) {
				System.out.println("Context Name is " + context);
				driver.context(context);
				String time = null;
				System.out.println("time:" + time);

				Thread.sleep(1500);
				String abc = driver.findElement(By.xpath("//div[text()='Services On-The-Go!']")).getText();
				assertEquals("Service On The Go!", abc);
			}
		}
	}
}
---------------------------------------------------------------------------------------
Error
operation() :: driver.start() executed
Total No of Context Found Before reaching WebView = 2
Context Name is [NATIVE_APP, WEBVIEW_com.ecifm.otgservices]
Context Name is WEBVIEW_com.ecifm.otgservices
FAILED: operation
io.appium.java_client.NoSuchContextException: An unknown server-side error occurred while processing the command. Original error: Failed to start Chromedriver session: An error occurred (Original error: chrome not reachable
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.5.2', revision: '10229a9', time: '2017-08-21T17:29:55.15Z'
System info: host: 'VIJENDRAK', ip: '192.168.168.235', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_121'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{appPackage=com.ecifm.otgservices, deviceScreenSize=1080x1920, networkConnectionEnabled=true, setWebContentsDebuggingEnabled=true, warnings={}, browsername=Chrome, databaseEnabled=false, deviceName=ZY223R9XDP, platform=LINUX, deviceUDID=ZY223R9XDP, appActivity=com.ecifm.otgservices.MainActivity, autowebview=true, desired={appPackage=com.ecifm.otgservices, appActivity=com.ecifm.otgservices.MainActivity, autowebview=true, setWebContentsDebuggingEnabled=true, platformVersion=6.0.1, browsername=Chrome, platformName=Android, udid=ZY223R9XDP, deviceName=Moto G4}, platformVersion=6.0.1, webStorageEnabled=false, locationContextEnabled=false, takesScreenshot=true, javascriptEnabled=true, deviceModel=Moto G (4), platformName=Android, udid=ZY223R9XDP, deviceManufacturer=motorola}]
Session ID: fff45a88-6b0f-4987-bf5f-5ec5c8b9c01b
	at io.appium.java_client.AppiumDriver.context(AppiumDriver.java:216)
	at Alchemy.Alchemy.SmokeTestAlchemy.operation(SmokeTestAlchemy.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.runSuites(TestNG.java:1028)
	at org.testng.TestNG.run(TestNG.java:996)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Failed to start Chromedriver session: An error occurred (Original error: chrome not reachable
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.5.2', revision: '10229a9', time: '2017-08-21T17:29:55.15Z'
System info: host: 'VIJENDRAK', ip: '192.168.168.235', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_121'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{appPackage=com.ecifm.otgservices, deviceScreenSize=1080x1920, networkConnectionEnabled=true, setWebContentsDebuggingEnabled=true, warnings={}, browsername=Chrome, databaseEnabled=false, deviceName=ZY223R9XDP, platform=LINUX, deviceUDID=ZY223R9XDP, appActivity=com.ecifm.otgservices.MainActivity, autowebview=true, desired={appPackage=com.ecifm.otgservices, appActivity=com.ecifm.otgservices.MainActivity, autowebview=true, setWebContentsDebuggingEnabled=true, platformVersion=6.0.1, browsername=Chrome, platformName=Android, udid=ZY223R9XDP, deviceName=Moto G4}, platformVersion=6.0.1, webStorageEnabled=false, locationContextEnabled=false, takesScreenshot=true, javascriptEnabled=true, deviceModel=Moto G (4), platformName=Android, udid=ZY223R9XDP, deviceManufacturer=motorola}]
Session ID: fff45a88-6b0f-4987-bf5f-5ec5c8b9c01b
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:82)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:45)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:89)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:641)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at io.appium.java_client.AppiumDriver.context(AppiumDriver.java:213)
	... 26 more


===============================================
    Default test
    Tests run: 1, Failures: 1, Skips: 0
===============================================


===============================================
Default suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================
