### ISSUE TITLE
appium-uiautomator2-driver cannot be installed

### ISSUE THREAD

**Issue by hameno** [appium/appium#10130]
## The problem

appium-uiautomator2-driver cannot be installed globally (npm install -g) and if not installed globally cannot find the unlock apk because it searches in the global node_modules folder.

## Environment

* Appium version (or git revision) that exhibits the issue: n/a
* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium: Ubuntu 16.04 (headless, server)
* Node.js version (unless using Appium.app|exe): v8.9.4 /npm 5.6.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real devices
* Appium CLI or Appium.app|exe: n/a

## Details

Installing globally fails:

```
root@jenkinsslave:~# npm -g install appium-uiautomator2-driver

> appium-chromedriver@3.3.0 install /usr/lib/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver
> node install-npm.js

(node:32135) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/201815-32135-i8lf96.dmjqn'
(node:32135) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
info Chromedriver Install Installing Chromedriver version '2.35' for platform 'linux' and architecture '64'
info Chromedriver Install Opening temp file to write chromedriver_linux64 to...
Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/201815-32135-tn352s.lq7ps'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-chromedriver@3.3.0 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-chromedriver@3.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-05T12_13_35_372Z-debug.log
```

When installed for the jenkins user it fails during test runs because it searches for the unlock apk in the /usr/lib/node_modules folder.

## Link to Appium logs

not relevant

**Comment by trix0** [comment]
Error: EACCES: permission denied . I would say its not problem with driver but problem with your instalation. You should never install npm with sudo as It brings you a lot of problems.

**Comment by hameno** [comment]
I know what I'm doing. The command is run as root (not sudo) and has all permissions for /usr/lib/node_modules. npm install -g cannot be run as a non-privileged user.

**Comment by trix0** [comment]
Well It worked for me without any problems. I would say its problem with your permissions, but lets wait for somebody who can confirm or deny that

**Comment by mykola-mokhnach** [comment]
I also assume it's configuration problem. What is the output of `ls -la /usr/lib/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/` and `whoami`

**Comment by hameno** [comment]
The folder does not exist. 

root@devicewall3:/usr/lib/node_modules# ll
total 84
drwxr-xr-x   4 root root  4096 Feb  5 13:13 ./
drwxr-xr-x 183 root root 69632 Feb  5 11:00 ../
drwxr-xr-x   9 root root  4096 Feb  5 11:04 appium/
drwxr-xr-x   9 root root  4096 Feb  5 11:00 npm/

whoami is irrelevant, I'm using the root user (which is a perfectly valid user to use).

**Comment by hameno** [comment]
I think I know the cause of this. NPM (5.6.0) is creating a ".staging" folder inside node_modules where it installs all packages into. The install script does not handle this correctly as it assumes the package is existing in "/usr/lib/node_modules" which it isnt (yet).
So definitely a bug in the install script.

**Comment by hameno** [comment]
Please see the explanation here: https://stackoverflow.com/questions/44573592/why-do-node-modules-go-into-staging-folder/44573782

**Comment by mykola-mokhnach** [comment]
@imurchie Any thoughts?

**Comment by hameno** [comment]
Same thing on MacOS with NodeJS 8.10.0 / NPM 5.6.0

**Comment by hameno** [comment]
Does nobody else have the same problem? This simply cannot work for anybody...npm uses a .staging folder for installations but appium-chromedriver tries to access the final directory.
npm install -g appium-uiautomator2-driver --unsafe-perm=true
Does seem to work, but thats no real fix.
