### ISSUE TITLE
Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65"

### ISSUE THREAD

**Issue by VivekKrishna15** [appium/appium#10139]
## The problem
I am running script in eclipse but getting the below error: 

Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
 
I have rebooted device, but still facing this issue. 

## **Environment**

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Desktop OS/version used to run Appium: 10.12.6
* Node.js version (unless using Appium.app|exe): v8.9.4
* Mobile platform/version under test: 10.3.3
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details
I did Basic(manual) configuration mentioned in this link: https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md, but it is still not working. I am getting same error again and again.

## Link to Appium logs

GIST link: https://gist.github.com/VivekKrishna15/aa2be4f2e6017b0af6ab56e2c7f495b5

**Comment by mykola-mokhnach** [comment]
> [Xcode] 2018-02-06 17:43:42.397 xcodebuild[9920:138813] Error Domain=IDEFoundationErrorDomain Code=1 "Could not obtain the bundle identifier for '/Users/developer/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/IntegrationApp.app'" UserInfo={NSLocalizedDescription=Could not obtain the bundle identifier for '/Users/developer/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/IntegrationApp.app'}
> [Xcode] 
> [Xcode] 2018-02-06 17:43:42.397 xcodebuild[9920:138813] Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Could not obtain the bundle identifier for '/Users/developer/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/IntegrationApp.app' If you believe this error represents a bug, please attach the log file at /var/folders/_5/5v1bll155rv64p67c2qcqtfw0000gn/T/com.apple.dt.XCTest/IDETestRunSession-AEB6E7EF-BC1B-4CD5-A6C5-C1A962A28E23/WebDriverAgentRunner-89C60B96-2AF2-4D52-872C-7DF5B07F0CE4/Session-WebDriverAgentRunner-2018-02-06_174341-dKXaQR.log" UserInfo={NSLocalizedDescription=Could not obtain the bundle identifier for '/Users/developer/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/IntegrationApp.app' If you believe this error represents a bug, please attach the log file at /var/folders/_5/5v1bll155rv64p67c2qcqtfw0000gn/T/com.apple.dt.XCTest/IDETestRunSession-AEB6E7EF-BC1B-4CD5-A6C5-C1A962A28E23/WebDriverAgentRunner-89C60B96-2AF2-4D52-872C-7DF5B07F0CE4/Session-WebDriverAgentRunner-2018-02-06_174341-dKXaQR.log}
> [Xcode] 

It is still the problem with codesigning. Ask your developers to help you with that
