### ISSUE TITLE
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command 'D\:\\android-sdk\\sdk\\platform-tools\\adb.exe -P 5037 -s 5e53d013 forward --remove tcp\:4728' exited with code 1'; Stderr: 'error: listener 'tcp:4728' not found'; Code: '1''

### ISSUE THREAD

**Issue by WenRui13** [appium/appium#10135]
## The problem
Test running on  single device Galaxy android 6.0.1 can works, but if I run test on 3 devices parallelly by testng.xml, the appium server for Galaxy android 6.0.1 can not start and throws a errow as my title, others works fine.  I start appium server by code as bellow:

this.service = AppiumDriverLocalService.buildService(new AppiumServiceBuilder()
.usingDriverExecutable(new File("C:/Program Files/nodejs/node.exe"))
.withAppiumJS(new File("C:/Users/yfxuxiaojun/AppData/Roaming/npm/node_modules/appium/build/lib/main.js"))
// .withArgument(GeneralServerFlag.TEMP_DIRECTORY,"C:/Windows/Temp")
// .usingPort(port as int)
.usingAnyFreePort()
// .withArgument(GeneralServerFlag.CONFIGURATION_FILE, nodeconfig)
.withArgument(GeneralServerFlag.SESSION_OVERRIDE)
// .withArgument(AndroidServerFlag.BOOTSTRAP_PORT_NUMBER, bport)
.withArgument(GeneralServerFlag.LOG_LEVEL, "debug")
// .withArgument(GeneralServerFlag.SHOW_CONFIG, "true")
.withStartUpTimeOut(60, TimeUnit.SECONDS)
)

    this.service.start()
    println this.service.getUrl()
    println this.service.isRunning()
// as so on
driver = new AndroidDriver(this.service.getUrl(), capabilities)
driver.manage().timeouts().implicitlyWait(15, TimeUnit.SECONDS)

## Environment
Appium version 1.7.2
Node.js 8.9.1
 Galaxy android 6.0.1

**Comment by WenRui13** [comment]
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:4728 (WARNING: The server did not provide any stacktrace information)

**Comment by WenRui13** [comment]
![image](https://user-images.githubusercontent.com/6370420/35841570-b33aaffe-0b37-11e8-8ccc-c4ad318e02a3.png)

I check the two apk file is not missing.

**Comment by mykola-mokhnach** [comment]
Have you seen https://github.com/appium/appium/blob/55760b7b9e1c494c6a1f22d152f0bd1fe676dae7/docs/en/advanced-concepts/parallel-tests.md ?

**Comment by WenRui13** [comment]
yes the the systemPort is conflict with each other. Now everything works fine. tks alot
