### ISSUE TITLE
Appium server is returning true for clicking an element, but on real device the click never happens

### ISSUE THREAD

**Issue by snehabadlani** [appium/appium#10136]
## The problem

I have an android app.When I run my script, the appium server returns true for finding the element and clicking on it.
But in actual, the click never happens.
I have set the automationName to “uiautomator2” and also the element i am trying to find has a unique xpath.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.7.2
* Desktop OS/version used to run Appium: Windows 10
* Mobile platform/version under test: Android-5.1
* Real device or emulator/simulator: REAL DEVICE

## Link to Appium logs
https://gist.github.com/snehabadlani/e5590db633325856de7fe05dbaaf712d

## Code To Reproduce Issue [ Good To Have ]

public class LoginEmail {

   AndroidDriver driver=null;

 

 @BeforeClass

 public void setUp() throws Exception {

 
//location of the app

 File app = new File("C:\\Users\\HP\\Downloads", "android-debug.apk");

 DesiredCapabilities capability = new DesiredCapabilities();

 capability.setCapability("device","Android");

 capability.setCapability(CapabilityType.BROWSER_NAME, "");

 capability.setCapability(CapabilityType.VERSION, "5.1");

 capability.setCapability("app", app.getAbsolutePath());

 capability.setCapability("deviceName","69TWLVHA4SOFAMT8");
capability.setCapability("platformName","Android");

 capability.setCapability("automationName","uiautomator2");
 capability.setCapability("app-package", "com.rapidue.uzed");

 capability.setCapability("app-activity", "com.rapidue.uzed.MainActivity");

 driver = new AndroidDriver<WebElement>(new URL("http://127.0.0.1:4723/wd/hub"),capability);

 }

 

 @Test

public void Loginwithemail() throws MalformedURLException, InterruptedException
{

		for(int i=1;i<4;i++)
		{
		 Dimension dim=driver.manage().window().getSize();
		int height = dim.getHeight();
		int width = dim.getWidth();
		int y = (int)(height*0.20);
		int startx = (int)(width*0.80);
		int endx = (int)(width*0.20);
		long l=1000;
		Duration d=Duration.ofMillis(1000);
		TouchAction a=new TouchAction((PerformsTouchActions) driver);
		
		a.press(startx,y).waitAction(d).moveTo(endx, y).release().perform();

		}
		Thread.sleep(5000);
		
		driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
                driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
	        WebElement b=driver.findElement(By.xpath("//android.widget.Button[@text='Get Started ']"));
                b.click();
		Thread.sleep(5000);
		 List<MobileElement> links=driver.findElements(By.xpath("//android.view.View[@index='2']"));
		 links.get(1).click();	 
		
}

**Comment by mykola-mokhnach** [comment]
It might be that the found element is not the element you are looking for or the hit point for it is not calculated properly. I'd check first if the bounds of the destination element are correct. If these are ok then try to click by relative element coordinates rather than calling `click`

**Comment by snehabadlani** [comment]
@mykola-mokhnach Yes, the bounds of the element in page source looks incorrect.

<android.widget.Button index="0" text="Get Started " class="android.widget.Button" package="com.rapidue.uzed" content-desc="" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,50][720,52]" resource-id="get-started-button-ur" instance="0"/>

Does this mean that the debug apk file has the real problem?

**Comment by mykola-mokhnach** [comment]
It might be that Google's UIAutomator framework does not handle it properly. You could try switching to UIAutomator2 or click by absolute coordinates.

**Comment by snehabadlani** [comment]
@mykola-mokhnach 
I am using UIAutomator2. 
I tried tapping on the element by using its coordinates and it worked. 
So basically when I was trying to tap on the element, using findElement, it got wrong coordinates of the element.
Why will page source have wrong coordinates?

Also, when I use Appium inspector to detect the screen, it is not able to identify individual elements. 
The individual elements are not getting highlighted when selected.

**Comment by VTINFOJames** [comment]
I've had issues with click on some elements but tap seems to work for those elements.
```
MobileElement el = driver.findElementByName(elementName);
el.tap(1, 1000);
```

**Comment by snehabadlani** [comment]
I am still facing the same issue.Can anyone please help?
I have tried using uiAutomator 2, I have used tap...but nothing seems to work.
