### ISSUE TITLE
"About Appium" doesn't bring up version details, does exactly the same as "check for updates"

### ISSUE THREAD

**Issue by Fortnox** [appium/appium#10138]
## The problem

In the Appium server window, under "File" clicking "About Appium" brings up the exact same dialogue as "check for updates". I had expected a dialogue showing what version of the software I was on, authors & legal details, etc.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium x64 v1.23.3 (according to the download link in my history, and no updates available)
* Desktop OS/version used to run Appium: Windows 10
* Mobile platform/version under test: Android, API level 27.
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Appium.exe

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/appium/appium-desktop
