### ISSUE TITLE
Decode pushed image

### ISSUE THREAD

**Issue by xuanzhaopeng** [appium/appium#10140]
## The problem
The image pushed to Android Simulator cannot be decoded.

Below is how Java_client push file to remote simulator/device, all data are encoded by base64, but when I push a image (such as .jpg/.png), the image cannot been read,  also the data of image is still encoded when I pull it back & view content.

So could you please clarify does Appium server will decode the file when java_client push a base64 encoded byte array? 

Thanks

```
public interface PushesFiles extends InteractsWithFiles, ExecutesMethod {
    default void pushFile(String remotePath, byte[] base64Data) {
        CommandExecutionHelper.execute(this, MobileCommand.pushFileCommand(remotePath, base64Data));
    }

    default void pushFile(String remotePath, File file) throws IOException {
        Preconditions.checkNotNull(file, "A reference to file should not be NULL");
        if (!file.exists()) {
            throw new IOException("The given file " + file.getAbsolutePath() + " doesn't exist");
        } else {
            this.pushFile(remotePath, Base64.encodeBase64(FileUtils.readFileToByteArray(file)));
        }
    }
}
```

## Environment
Appium 1.7.2
Java client 5.0.4

**Comment by mykola-mokhnach** [comment]
This has been addressed quite recently: https://github.com/appium/java-client/pull/816

**Comment by mykola-mokhnach** [comment]
BTW, it's java client issue

**Comment by xuanzhaopeng** [comment]
Cool thanks!

👍
