### ISSUE TITLE
appium do not show any log after “Failed to locate element”

### ISSUE THREAD

**Issue by jordankan** [appium/appium#10149]
## The problem

after Failed to locate element,the CLI show "Stream still not complete, waiting",and do not show any log any more.seems it had crash.
And i have three computer running same Version Appium and simulator.only this computer cause this problem.

## Environment

* Appium version 1.6.4
* Desktop OS/version used to run Appium:window 7
* Node.js version (unless using Appium.app|exe):9.4.0
* Mobile platform/version under test: Android 4.4.2
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

[debug] [BaseDriver] Waiting up to 30000 ms for condition
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":
"find","params":{"strategy":"id","selector":"com.ct.client:id/iv_tologin","conte
xt":"","multiple":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":
"action","action":"find","params":{"strategy":"id","selector":"com.ct.client:id/
iv_tologin","context":"","multiple":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'com.ct.client:id/iv_
tologin' using 'ID' with the contextId: '' multiple: false
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[INSTANCE=0,
 RESOURCE_ID=com.ct.client:id/iv_tologin]
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Failed to locate element. Cle
aring Accessibility cache and retrying.
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'com.ct.client:id/iv_
tologin' using 'ID' with the contextId: '' multiple: false
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[INSTANCE=0,
 RESOURCE_ID=com.ct.client:id/iv_tologin]
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":7
,"value":"No element found"}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [AndroidBootstrap] Stream still not complete, waiting

**Comment by mykola-mokhnach** [comment]
Is it reproducible with Appium 1.7.2?

**Comment by jordankan** [comment]
Appium version make me confused!The version code i got it from the log in CLI.

**Comment by jordankan** [comment]
And I have try the latest Appium.The problem still go on.

**Comment by mykola-mokhnach** [comment]
Lets see if https://github.com/appium/appium-android-bootstrap/pull/52 helps. This should at least prevent the freeze

**Comment by mykola-mokhnach** [comment]
We've added the fix to appium@beta. Can you please update and try it?

**Comment by jordankan** [comment]
it seems worked!
