### ISSUE TITLE
Attempting to close Appium for Update on Mac results in exception

### ISSUE THREAD

**Issue by BrandonBlair** [appium/appium#10141]
## The problem

When presented with the latest update, an option is given to close and restart the app. Clicking on this option causes an exception. Attempting to close the app manually then causes an Object Destroyed exception, likely because the previous failed closure did in fact kill the process.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.3.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS
* Node.js version (unless using Appium.app|exe): 10.13.3
* Mobile platform/version under test: N/A
* Real device or emulator/simulator: N/A
* Appium CLI or Appium.app|exe: Appium.app

## Details

When an update is downloaded, a modal appears asking the user if they would like to restart and install the update. Choosing to close and restart causes the exception.

## Link to Appium logs

[Screenshots of the exceptions](https://imgur.com/a/Rr5Nf)

## Code To Reproduce Issue [ Good To Have ]

N/A

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/appium/appium-desktop

@dpgraham FYI

**Comment by dpgraham** [comment]
The auto-updater is a known issue

I recommend just reinstalling it: https://github.com/appium/appium-desktop/releases/latest
