### ISSUE TITLE
href value of span is concatenated not overwritten

### ISSUE THREAD

**Issue by markring** [appium/appium#10142]
## The problem

My Ionic mobile application presents the user a temporary ID via a href value, contained within a span element ```<span>href=TEMP ID</span>``` provided by my server. After the user registers this same span is updated with the users phone number ```<span>href=###-###-####</span>```. This works fine when using the application on a phone, or manually on simulator through X-code, when using Appium the span will display a concatenation of both values ```<span>href=Temp ID + ###-###-####</span>``` . 

## HTML
      `<h2 class="phoneNumber">
          <i ng-show="!collectNowUser.numericalId" class="ion-android-phone-portrait"></i>
          <i ng-show="collectNowUser.numericalId" class="ion-pound"></i>
          <span class="userId" id="collect-code">{{ phone | ecPhoneNumberFilter:collectNowUser.numericalId }}</span>
       </h2>`

## HTML after processing {{ phone | ecPhone....}}
    `<a dir="ltr" href="tel:(794)%20493-0275" x-apple-data-detectors="true" x-apple-data-detectors-type="telephone" x-apple-data-detectors-result="0">(794) 493-0275</a>`

## Protractor Test
   `it('Collect now screen should display registered user\'s telephone number', function(){
        expect(element(by.id(collectNow.elements.collectCode)).isPresent()).toBe(true)
        element(by.id(collectNow.elements.collectCode)).getAttribute('value').then(function(hrefValue)
{
            console.log('saved: ', myPhone, 'screen: ', hrefValue)
            expect(myPhone).toEqual(hrefValue);    
            }) 
    })`

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Desktop OS/version used to run Appium: macOS High Sierra version 10.13.2
* Node.js version (unless using Appium.app|exe): 6.10.3
* Mobile platform/version under test: iOS version 3.9.2, Android version 6.0.0
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium CLI

**Comment by mykola-mokhnach** [comment]
I assume this is the default behaviour. One must explicitly call `clear` in order to make the field empty

**Comment by markring** [comment]
This is not an input field, it is a hardcoded href value.

**Comment by mykola-mokhnach** [comment]
Then it might be something on the lower level. I'd try to connect a debugger to the app while the automated test is being executed to figure out the difference between the manual and automated run.

**Comment by markring** [comment]
It was a configuration error on my end, thank you for prompt reply.
