### ISSUE TITLE
Appium IOS: XCUIElementTypeTable automatically scrolls when findelement is called 

### ISSUE THREAD

**Issue by ervin-chan-bcs** [appium/appium#10145]
## The problem

I’m currently testing out an app that has several XCUIElementTypeCell in an XCUIElementTypeTable. I search for a specific text from the table and click the specific list. Once I click it, the XCUIElementTypeCell expands, showing several items for me to interact with, one of which is a button that shows another screen.

Whenever I try to do a findelement to the button that needs to be clicked, the whole UI scrolls, causing the test script to fail since the button is no longer in view. Any reason as to why this is happening?

To add, it seems to only happen when interacting with cells found way below the list/table. It doesn’t happen when selecting the first several cells that appear upon loading.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1 and 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium: macOS Sierra 10.12.6
* Node.js version (unless using Appium.app|exe): 9.4.0
* Mobile platform/version under test: iOS - IPhone 5S on 10.3.3
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

https://gist.github.com/ervin-chan-bcs/ec946487551cd72d8ac16859a2151021

**Comment by mykola-mokhnach** [comment]
Please report the issue to https://github.com/facebook/WebDriverAgent/issues
