### ISSUE TITLE
installApp() app is deleted after appium server killed 

### ISSUE THREAD

**Issue by trix0** [appium/appium#10147]
I have to lunch session by random app and activity. Afterwards I need to verify if app exists.If app does not exists I have to use installApp() to install my app and lunch it and test if it works. After that I call end function that should end session. Then I kill the appium server. App should stay installed in device

## The problem

After I kill appium server, App is deleted from the phone.

## Environment

* Appium version (or git revision) that exhibits the issue:1.8.0-beta3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:ubuntu 16.04
* Node.js version (unless using Appium.app|exe):9.4.0
* Mobile platform/version under test:Android
* Real device or emulator/simulator:Real device samsung A3
* Appium CLI or Appium.app|exe:cli

## Link to Appium logs
[Appium Log](https://gist.github.com/trix0/c35ba920a29c59f519c10b1b20f8dd72)

## Code To Reproduce Issue [ Good To Have ]
[Code](https://gist.github.com/trix0/871aa9cb3f1d7d5fb0487e323b2d5fb1)

**Comment by mykola-mokhnach** [comment]
> After i kill appium server app disappears

What is "server app" and what is the meaning of "disappears" ?

**Comment by trix0** [comment]
After i kill appium server , app disappears :) Sorry about that . It means that its gone. Not installed even tho it Should stay in the phone. I tried all the combination of fullReset and noReset

**Comment by trix0** [comment]
So only problem is that app does not stay in the device after I kill appium server

**Comment by mykola-mokhnach** [comment]
This is strange, since I don't see any traces in the log about application removal

**Comment by trix0** [comment]
Agree :-( Gonna try emulator I ll write in a few

**Comment by trix0** [comment]
Closing .... Restart device helped. Sorry for bothering you with this :)

**Comment by trix0** [comment]
Just got this issue again... this time restart device didnt help. I was getting in on both of my real devices. Samsung A3, galaxy edge s7 any idea guys ?
Does not work even with uiautomator2 capability 
appium log 
https://gist.github.com/trix0/f54bcd86bc425ec9bc4e037eb5d35a42

code 
https://gist.github.com/trix0/c4badcb10b0768db8c26e64e6132382a

**Comment by trix0** [comment]
@mykola-mokhnach  any idea how to find out whats going on ?

**Comment by mykola-mokhnach** [comment]
I assume it is a problem in the client code. Add more logging there to see what is happening .
