### ISSUE TITLE
[1.8.0.beta3] this.shouldDismissChromeWelcome is not a function

### ISSUE THREAD

**Issue by saikrishna321** [appium/appium#10146]
Not able to trigger chrome tests with latest 1.8.0 beta3

https://gist.github.com/saikrishna321/21f066f64800bd07702a29d57dc3bea1#file-gistfile1-txt-L154

**Comment by mykola-mokhnach** [comment]
@imurchie FYI

**Comment by imurchie** [comment]
This makes sense. I'll get a fix in.
