### ISSUE TITLE
Not able to run appium script on Android Oreo

### ISSUE THREAD

**Issue by ios-dev-newbie** [appium/appium#10143]
## The problem

Not able to run appium script on android oreo. 

## Environment

* Appium version (or git revision) that exhibits the issue: v1.7.2
* Desktop OS/version used to run Appium: macOs 10.12.6
* Node.js version (unless using Appium.app|exe): 9.5.0
* Mobile platform/version under test: v8.1.0
* Real device or emulator/simulator: Real Device 
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs
 Encountered internal error running command: Error: The file at path /usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/uiautomator2/appium-uiautomator2-server-v0.3.0.apk does not exist or is not accessible
[oreo_error.txt](https://github.com/appium/appium/files/1701881/oreo_error.txt)

**Comment by mykola-mokhnach** [comment]
Is this apk file there and accessible for the appium server user?

**Comment by ios-dev-newbie** [comment]
There is no folder as uiautomator2. Also I haven't added the apk file. Don't know why the error is appearing.
![Folder_structure]()

**Comment by mykola-mokhnach** [comment]
does reinstall help?

**Comment by mykola-mokhnach** [comment]
also, have you checked that your user has R/W permissions in /usr/local/lib?

**Comment by ios-dev-newbie** [comment]
I have install node using brew. So I don't see any problem with permission. Also I have tried to uninstall appium and reinstall it using "npm install -g appium".

Same code work for Android Marshmellow.

**Comment by mykola-mokhnach** [comment]
I'd expect warnings/errors during install. Regarding permissions: `chmod -R $USER +w /usr/local/lib`

**Comment by ios-dev-newbie** [comment]
if I uninstall appium and tried to install it through command "npm install -g appium". The commands run in infinite loop.

Checkout logs
[appium_install_error.txt](https://github.com/appium/appium/files/1702506/appium_install_error.txt)

**Comment by ios-dev-newbie** [comment]
Please check the below gist file for more detailed log.
<script src="https://gist.github.com/ios-dev-newbie/ac3b0f974ef67d278e0122d5cefeaae9.js"></script>

**Comment by mykola-mokhnach** [comment]
> https://gist.github.com/ios-dev-newbie/ac3b0f974ef67d278e0122d5cefeaae9.js

This error is absolutely different from what is in the header. If the original issue is not the case anymore then a new report should be created instead. Also, the logcat output is needed for the latter.

**Comment by ios-dev-newbie** [comment]
Ok @mykola-mokhnach, I will create new issue for the same. Will you please let me know how I can get the logcat output?

**Comment by mykola-mokhnach** [comment]
http://appium.io/docs/en/commands/session/logs/get-log/

Log type should be `logcat`

**Comment by rodrigomunoz** [comment]
@mykola-mokhnach, I'm seeing the same issue on Appium 1.7.2 but not on 1.7.1. 
What happens is that the uiautomator2 folder does not exist in `<NODE_FOLDER>/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/uiautomator2/appium-uiautomator2-server-v0.3.0.apk`

It is not a permissions issue, it is simply that the folder does not exist. `<NODE_FOLDER>/lib/node_modules/appium/node_modules/appium-uiautomator2-driver` exists, but it does not have any `uiautomator2` folder.

Appium 1.7.2
```
└─┬ appium@1.7.2
  └── appium-uiautomator2-driver@0.11.0 
```

Appium 1.7.1
```
└─┬ appium@1.7.1
  └── appium-uiautomator2-driver@0.6.5 
```

Is this an issue with that version of `appium-uiautomator2-driver`? Or was there a change on how to start Appium and which capabilities to use for uiautomator2?

**Comment by mykola-mokhnach** [comment]
Most likely an issue with that particular release.
