### ISSUE TITLE
Cannot click on a hidden button that is in pageSource and uiautomatorviewer

### ISSUE THREAD

**Issue by WoodPlank** [appium/appium#10154]
## The problem

I cannot click on a hiddenButton that I used to be able to click on with automation. I am using UiAutomator2.

## Environment

* Appium version that exhibits the issue: I tried 1.6.4-beta and 1.7.2
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): v6.9.2 (tried this with 1.6.4-beta but did not try with 1.7.2)
* Mobile platform/version under test: Android version 6.0.1
* Real device or emulator/simulator: Real device

## Details

I have a test case where I try to click on a hidden button to switch servers in my .apk. The problem is that this element is "invisible" (I believe it's a square button that is clear) and it can be identified in the uiautomatorviewer.bat and also when I do a println for driver.getPageSource; however, Appium is saying that it cannot find it. I am using UiAutomator2.

## Link to Appium logs

Link to Appium logs (search for hiddenButton): https://gist.github.com/WoodPlank/74ea5f307d67740db5d787af94672f02

## Code To Reproduce Issue [ Good To Have ]

I can include this in another gist if you'd like.

**Comment by dpgraham** [comment]
If it can't find the element it probably means it is a locator problem (ie: the locator you used with automation is no longer compatible with UiAutomator2).

I would recommend using the UI (https://github.com/appium/appium-desktop/releases/latest) and running an ad-hoc session on that. The UI gives you hints on what locator you should use to find elements.

**Comment by WoodPlank** [comment]
@dpgraham Thanks for the reply. I'm using the UI inspector and I found a few interesting things that might help. 

1. I wanted to see if I could perform a "tap" interaction while I was in the UI inspector. Interestingly, when I navigate to the hiddenButton and try to perform an interaction, such as "tap", it says "Interactions are not available for this element" but it is clearly highlighted when I select it.

2. The element is inside of a WebView. The hiddenButton element is inside of "android.webkit.WebView". So I'm dealing with a hybrid app.

Any thoughts?

**Comment by dpgraham** [comment]
Can you try refreshing the source and selecting again?

**Comment by mykola-mokhnach** [comment]
Try to click the element by coordinates.

**Comment by WoodPlank** [comment]
I can click on the element by coordinates but it takes too long between each tap using TouchActions. I need 3 quick (1s) consecutive taps on the element. What's strange is that some devices have no problem finding the element but others struggle. I can provide a list of these devices if it helps. 

I'll try refreshing the source and selecting again when I can

**Comment by mykola-mokhnach** [comment]
I don't think we cannot do anything on Appium side if UIA detects the buttons as disabled. Please report the problem to Google if you think this is the erroneous behaviour.

**Comment by WoodPlank** [comment]
Thanks for the help. Does Appium update uiautomator2 or would I need to do this?

**Comment by mykola-mokhnach** [comment]
> Does Appium update uiautomator2 or would I need to do this?

WDYM? There is uiautomator2 library, which is built in into Android OS and there are client modules over it called uiautomator2-server/uiautomator2-driver on Appium side.

**Comment by skuttyihr** [comment]
I'm testing on an iOS simulator and havee the same exact issue on iOS 11.x. The element ids are visible on iOS 10.x and the tests pass. When I run the same tests on OS 11.x, the element loses it's id and I cannot click on it using the inspector. If I go down the tree, it's detected as XCUIElementTypeTabBar/XCUIElementTypeOther[3]" and has the "Interactions are not available for this element" shown.
