### ISSUE TITLE
Failure [INSTALL_FAILED_ALREADY_EXISTS: Attempt to re-install io.appium.unlock without first uninstalling.]\r\n"},"sessionId":null}

### ISSUE THREAD

**Issue by Snigdhaa** [appium/appium#10157]
## The problem

I am trying to run a simple script, which launches an  chrome app on Android N(7.0)
## Environment

* Appium version (or git revision) that exhibits the issue: 1.4.16.1
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: window 7/32 bit
* Node.js version (unless using Appium.app|exe): node-v8.9.4-x86
* Mobile platform/version under test: chrome browser /64.0.3282.123
* Real device or emulator/simulator:Android 7.0.0:MotoG(4)/Build/NPJS25.93-14-10
* Appium CLI or Appium.app|exe: Appium Desktop exe

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Code To Reproduce Issue [ Good To Have ]
package appium;

import java.net.MalformedURLException;
import java.net.URL;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.remote.MobileCapabilityType;
import org.openqa.selenium.By;
import org.openqa.selenium.Platform;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.remote.BrowserType;
import org.openqa.selenium.remote.DesiredCapabilities;
//import org.testng.annotations.Test;
 
public class StartChrome
{
 
 
public static void main(String[] args) throws MalformedURLException{

 DesiredCapabilities cd=DesiredCapabilities.android();
 
  cd.setCapability(MobileCapabilityType.BROWSER_NAME,BrowserType.CHROME);
 
 cd.setCapability(MobileCapabilityType.PLATFORM,Platform.ANDROID);
 
// we need to define platform name
  cd.setCapability(MobileCapabilityType.PLATFORM_NAME,"Android");
 
// Set the device name as well (you can give any name)
 cd.setCapability(MobileCapabilityType.DEVICE_NAME,"my phone");
 
 // set the android version as well 
   cd.setCapability(MobileCapabilityType.VERSION,"7.0");
 
 // Create object of URL class and specify the appium server address
 URL url= new URL("http://127.0.0.1:4723/wd/hub");
 
// Create object of  AndroidDriver class and pass the url and capability that we created
 WebDriver driver = new AndroidDriver(url, cd);
 
// Open url
  driver.get("http://www.facebook.com");
 
 // print the title
  System.out.println("Title "+driver.getTitle());
 
// enter username
driver.findElement(By.name("email")).sendKeys("sni****@gmail.com");
 
// enter password
      driver.findElement(By.name("pass")).sendKeys("*****8");
 
// click on submit button
driver.findElement(By.id("u_0_5")).click();
 
// close the browser
driver.quit();
 }
 }

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Appium 1.4 is outdated. Update to 1.7.2 and try again

**Comment by Snigdhaa** [comment]
can somebody please share the link to download Appium 1.7 version ,not able to find on appium.io

**Comment by mykola-mokhnach** [comment]
http://appium.io/docs/en/about-appium/getting-started/?lang=en

**Comment by Snigdhaa** [comment]
@mykola-mokhnach on the above url ,not able to see 1.7 version,its show only 1.3 ,please suggest how to get desktop version

**Comment by mykola-mokhnach** [comment]
1.3 is the version of the UI shell itself. The server version behind it is ok. Or use npm

**Comment by Snigdhaa** [comment]
@mykola-mokhnach ,i jave downloaded the same version Appium.Setup.1.3.2.exe ,but seems no luck,i simply wanted to download desktop version .
