### ISSUE TITLE
Changing time format (12/24) through Appium, same like a Language/Locale

### ISSUE THREAD

**Issue by MioOgbeni** [appium/appium#10156]
## New Feature

Hello, I would like to see that Appium will have the function to change the time format (12/24) at the beginning of the emulator. Same like today we can change language and locale. However time format are today unchangeable. I read that it is possible through ADB, but one Appium function can be more elegant if its possible.

**Comment by mykola-mokhnach** [comment]
There is a possibility to run any shell commands on the device: https://github.com/appium/appium/blob/fd0a0dc234998cd2b3c79a8e66b2da6e77506273/docs/en/writing-running-appium/android/android-shell.md
