### ISSUE TITLE
Original error: Cannot parse launchActivity from manifest: WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by prat3ik** [appium/appium#10152]
## The problem

When I am starting the session by mentioning below desired capabilities it is giving the error
**Desired Capabilities:**
{
  "platformName": "Android",
  "deviceName": "c4e3f3cd",
  "platformVersion": "8.0",
  "app": "E:\\Software\\2018\\sample_apk\\androidMessaging.apk",
  "appPackage": "com.google.android.apps.messaging"
}

**Error:**
An unknown server-side error occurred while processing the command. Original error: packageAndLaunchActivityFromManifest failed. Original error: Cannot parse launchActivity from manifest: WARNING: An illegal reflective access operation has occurred
 WARNING: Illegal reflective access by io.appium.apktools.StringsXML (file:/C:/Users/Pratik/AppData/Local/Programs/appium-desktop/resources/app/node_modules/appium/node_modules/appium-adb/jars/appium_apk_tools.jar) to field java.lang.reflect.Field.modifiers
 WARNING: Please consider reporting this to the maintainers of io.appium.apktools.StringsXML
 WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
 WARNING: All illegal access operations will be denied in a future release
 Feb 07, 2018 10:56:15 PM brut.androlib.res.decoder.ARSCDecoder readConfigFlags
 WARNING: Config flags size > 38. Exceeding bytes: 0x746E00000000000000000000000000000000.
 Feb 07, 2018 10:56:15 PM brut.androlib.res.decoder.ARSCDecoder readConfig
 WARNING: Invalid config flags detected. Dropping resources: string-sr-ERR0
 Feb 07, 2018 10:56:18 PM brut.androlib.res.decoder.AXmlResourceParser getAttributeValue
 WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=usesCleartextTraffic, value=0xffffffff
 brut.androlib.err.UndefinedResObject: resource spec: 0x010104ec
 at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
 at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:58)
 at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:54)
 at brut.androlib.res.decoder.ResAttrDecoder.decode(ResAttrDecoder.java:36)
 at brut.androlib.res.decoder.AXmlResourceParser.getAttributeValue(AXmlResourceParser.java:369)
 at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
 at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
 at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
 at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:83)
 at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:141)
 at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:153)
 at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:131)
 at brut.androlib.res.AndrolibResources.decodeManifest(AndrolibResources.java:164)
 at io.appium.apktools.AndroidManifestActivityHelper.decodeManifestXML(AndroidManifestActivityHelper.java:27)
 at io.appium.apktools.Main.main(Main.java:33)

## Environment

* Appium version : 1.7.2
* Desktop OS: Windows 7
* Node.js version: 9.5.0
* Mobile platform/version under test: Android 8.0 (Oreo)
* Real device or emulator/simulator: Real Device (One Plus 3T)
* Appium CLI or Appium.app|exe: Appium Desktop 1.7.2

## Code To Reproduce Issue 
* Open Appium Desktop and start server
* Start Inspector Session
* Create Desired Capabilities as mentioned above
* Start Session
* Observe output
![issu](https://user-images.githubusercontent.com/23506005/35934311-31b7e708-0c63-11e8-8272-10b09837d313.png)

**Comment by mykola-mokhnach** [comment]
Linking https://github.com/appium/appium/issues/10120

**Comment by mykola-mokhnach** [comment]
Would it be possible to get an example of the apk file?

**Comment by prat3ik** [comment]
Yes sure, here is the link for app(apk file): https://drive.google.com/file/d/1NzqkhEtd7nAd5mAD4yPWPmxKa17c-s4P/view?usp=drivesdk

**Comment by prat3ik** [comment]
Please let me know if I am missing something on Desired capabilities? And thanks for the assigning issue

**Comment by mykola-mokhnach** [comment]
Linking https://github.com/appium/appium-adb/pull/296

**Comment by mykola-mokhnach** [comment]
Please try the if recent appium beta works for you

**Comment by prat3ik** [comment]
Hi @mykola-mokhnach , thanks for the update, I have never installed appium beta before, Can you please suggest me a way how can I install recent appium beta?

I am using Appium Desktop (Server version 1.7.2) on Windows 7.

**Comment by mykola-mokhnach** [comment]
you must use npm to get it: `npm i -g appium@beta`

the other user has confirmed the fix, so I close this issue as well.

**Comment by prat3ik** [comment]
Thank you @mykola-mokhnach , It is fixed. Morever I had to add **appPackage** and **appActivity** in Desired capabilities

> {
  "platformName": "Android",
  "deviceName": "c4e3f3cd",
  "platformVersion": "8.0",
  "app": "E:\\Software\\2018\\sample_apk\\androidMessaging.apk",
  "appPackage": "com.google.android.apps.messaging",
  "appActivity": "com.google.android.apps.messaging.ui.ConversationListActivity"
}
