### ISSUE TITLE
Searching inside a scrollable for text containing two commas crashes Appium

### ISSUE THREAD

**Issue by olescheller** [appium/appium#10159]
## The problem

Using uiautomator, searching inside a scrollable for any string that contains at least two comma (`,`) symbols, crashes appium. E.g.: `driver.find_element_by_android_uiautomator('new UiScrollable(new UiSelector().scrollable(true)).scrollIntoView(new UiSelector().text(",,"))')`

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: MacOS
* Node.js version (unless using Appium.app|exe): 8.6.0
* Mobile platform/version under test: Android 7.1.1
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: cli

## Details

Any string containing 2 or more commas will throw the error. `,,`, `a,b,`,`a, b , c`, etc

Error: `[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":9,"value":"Could not parse UiSelector argument: UiScrollable has no \"scrollIntoView\" method that takes 2 arguments"}`

## Link to Appium logs

https://gist.github.com/oscheller1/030b75172c0cc2cce9b9eb7e669d1a3b

## Code To Reproduce Issue [ Good To Have ]

`driver.find_element_by_android_uiautomator('new UiScrollable(new UiSelector().scrollable(true)).scrollIntoView(new UiSelector().text(",,"))')`

**Comment by mykola-mokhnach** [comment]
Closed as obsolete.
