### ISSUE TITLE
Unable to launch app on iOS simulator using Appium 1.7.1

### ISSUE THREAD

**Issue by shanthi2016** [appium/appium#10153]
I am trying to run tests on an iOS simulator(11.2 or 10.3 or any) with Appium desktop 1.7.1 .
Appium installs the app and WDA, but the app is not launching.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable):NA
* Desktop OS/version used to run Appium: Mac OS 10.12.6
* Node.js version (unless using Appium.app|exe):6.10.2
* Mobile platform/version under test: 11.2,11.0 and 10.3
* Real device or emulator/simulator: Both
* Appium CLI or Appium.app|exe: .app

Here are the Appium logs:
https://gist.github.com/shanthi2016/8707c1f07025bcbe7fc5cfc7d940bb8c

Could you please let me know what could be the issue.

**Comment by mykola-mokhnach** [comment]
I don't observe any problems in the attached log

**Comment by shanthi2016** [comment]
Sorry,I think the logs are from app running through Appium inspector.

Please find attached Appium logs ran from actual test.

Logs:
https://gist.github.com/shanthi2016/c143b4f4238ed00d88a7663a5acf6a97

**Comment by mykola-mokhnach** [comment]
> [info] [iOSSim] Simulator 88D78CA9-BB0B-4650-A8F8-19CAD424C99D is in 'Shutting Down' state. Trying to shutdown...[error] [simctl] Error: simctl error running 'shutdown': An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=164):


This looks like a problem with the machine. Are you able to start and quit the simulator manually?

**Comment by shanthi2016** [comment]
Yes,I am able to.
I just opened a simulator from mac search and it opened a simulator and able to quit that.

The app launches fine when I create a simulator build from xcode and not launching through Appium.

**Comment by mykola-mokhnach** [comment]
Replace `device` capability with `deviceName`

**Comment by shanthi2016** [comment]
Changing to deviceName didn't worked.

These are the logs: 
https://gist.github.com/shanthi2016/d63832856f2daec72cf46fece0d35854

**Comment by mykola-mokhnach** [comment]
> https://gist.github.com/shanthi2016/d63832856f2daec72cf46fece0d35854

this log does not contain any issues

**Comment by shanthi2016** [comment]
But the app didn't launched.

**Comment by mykola-mokhnach** [comment]
try to get the device log - it should contain more info

**Comment by shanthi2016** [comment]
Please find attached device logs:
https://gist.github.com/shanthi2016/25565148038e1404219f0eebe14548fe

**Comment by mykola-mokhnach** [comment]
> Feb  8 10:57:04 NY1-LM005-P4300 com.apple.CoreSimulator.SimDevice.88D78CA9-BB0B-4650-A8F8-19CAD424C99D[7248] (UIKitApplication:com.apple.test.WebDriverAgentRunner-Runner[0x6a2b][7274][7349]): Service exited with abnormal code: 1

WDA crashes on the device. I'd try to manually build and deploy it to the simulator in order to understand why this is happening or get help at https://github.com/facebook/WebDriverAgent

**Comment by shanthi2016** [comment]
Can I do a re-installation of Appium, does that help fix this issue

**Comment by mykola-mokhnach** [comment]
You can try. 

Closing as third party issue
