### ISSUE TITLE
getContextHandles not working after OSX upgrade to 10.12.6

### ISSUE THREAD

**Issue by toddwinstanley** [appium/appium#10151]
## The problem

After upgrading OSX to 10.12.6 on my laptop, my test automation can no longer getContextHandles when my app displays a webview over the application.  I get the following error: 
An unknown server-side error occurred while processing the command. Original error: Could not connect to a valid app after 20 tries.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1 & 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): 1.7.1 + OSX 10.12.?
* Desktop OS/version used to run Appium: OSX 10.12.6
* Node.js version (unless using Appium.app|exe): v8.9.1
* Mobile platform/version under test: iOS 11.1
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: AppiumDriverLocalService

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/toddwinstanley/c2e35658e8e3b2926b8a30b6b747e313

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Are you able to connect to the webview manually via Safari debugger?

**Comment by mykola-mokhnach** [comment]
> [debug] [RemoteDebugger] Received app, but expected url ('null') was not found. Trying again.

@imurchie This log line looks a bit suspicious to me

**Comment by toddwinstanley** [comment]
I don't believe I'm able to connect manually with the Safari debugger, but
I'm not too familiar with that process.  Web Inspector is enabled on the
device in the simulator, but I only see my macbook in the develop menu in
safari.

**Comment by mykola-mokhnach** [comment]
The webview won't be availble in Appium if it does not exist in remote debugger menu.

**Comment by toddwinstanley** [comment]
Is there any documentation on connecting the remote debugger?

**Comment by toddwinstanley** [comment]
I found some documentation and I'm now able to find and examine the source
in the safari remote debugger.  This webview context still does not show up
when I call getContextHandles().

**Comment by toddwinstanley** [comment]
From what I've found:
Appium cannot connect to webview when safari debugger has previously
connected.  Must quit safari first.
Appium does not consistently connect to webview when multiple simulators
are running.
Appium still does not consistently get webview source after OSX/platform
upgrade.  I upgraded my platform to 11.2 and now I am able to connect to
the webview context, but often the page source is empty.  I am unable to
replicate the same behavior using safari remote debugger, the safari
debugger always gets the complete page source.  I've tried retries, waits,
sleeps, setting breakpoints, etc.  So far there is no pattern to when it
succeeds and when it fails.  If it gets empty page source the first try, it
will not get the proper page source no matter how long I wait unless I
restart the appium server.
This seems like an appium issue to me.

**Comment by mykola-mokhnach** [comment]
There is a known issue on the Apple side, that only one simulator provides remote debugging port if multiple simulators are running. We've even added `shutdownOtherSimulators` capability to the recent beta in order to workaround it. Regarding the connection stability: Appium already retires many times. If you have any concrete ideas about how the current behaviour might be improved then let us know or pop up a PR.
