### ISSUE TITLE
"driver.install_app" How to set timeout(Android/appium/python)

### ISSUE THREAD

**Issue by yuanzhengjie** [appium/appium#10167]
My APK is about 700MB.
When I use the driver.install_app to install.
The log will show:
[MJSONWP] Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command 'D:\android\sdk\platform-tools\adb.exe -P 5037 -s 7db29ae7 push D:\dowload\apk\shadertest.apk /data/local/tmp/9dc93894303068fe9a6bc17e65d4ea34.apk' timed out after 20000ms'; Stderr: ''; Code: 'null'

Actually my push is normal.
How to prolong timeout?

**Comment by mykola-mokhnach** [comment]
This is fixed in appium@beta. There the timeout is taken from driver capabilities.
