### ISSUE TITLE
JavaScript error when attempting to update Appium

### ISSUE THREAD

**Issue by Stylar66** [appium/appium#10164]
## The problem

I'm running Appium v. 1.3.1 and at start up a popup shows up that that there is an update. The update 1.3.2. I went ahead and clicked on the Download Upgrade Now action and waited until it was finished. When the download was finished it asks you to close Appium so that the installation can occur. 
After closing I get a "A JavaScript error occurred in the main process" window. See attached. 
![screen shot 2018-02-08 at 1 20 45 pm](https://user-images.githubusercontent.com/36281106/35999408-93f117f2-0cd4-11e8-80bb-96400828d91a.png)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.3.1
* Last Appium version that did not exhibit the issue (if applicable): 1.3.1
* Desktop OS/version used to run Appium: MAC
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

**Comment by dpgraham** [comment]
@Stylar66 can you report this in https://github.com/appium/appium-desktop/issues

For now I would suggest uninstalling Appium Desktop and then re-installing the latest https://github.com/appium/appium-desktop/releases/latest

The auto-updater has a lot of problems.
