### ISSUE TITLE
Is there a way to execute Appium tests on a specific page

### ISSUE THREAD

**Issue by siddharthsircar** [appium/appium#10169]
## The problem

Currently, when executing appium tests, I have to go through the complete login process in case I need to verify my dashboard.
Is it possible to execute tests on a page currently open in the device?

**Comment by mykola-mokhnach** [comment]
Try `noReset` capability. 
Also you may tweak your application under test, so it is not necessary to do all the operation via UI but rather via some API backdoor, which would be way faster.
