### ISSUE TITLE
Not a able install Appium via npn command on window 7

### ISSUE THREAD

**Issue by Snigdhaa** [appium/appium#10160]
Hi All,

please help i m not able to install Appium 1.7 version neither from any site or even with npn command ,i already did necessary setting for nodejs and veiw the changes on environment variable but when i tried to type on cm getting below error 

C:\Users\Prem Sharma>npm install -g appium
[..................] / rollbackFailedOptional: verb npm-session 74647823094408d

***Prerequisite*****
System System Path: C:\Program Files\node.js
User System Path: C:\Users\<username>\AppData\Roaming\npm

**Comment by mykola-mokhnach** [comment]
The information that you provided is not enough to make any conclusions.
