### ISSUE TITLE
Unable to run some pieces of Appium code in 7.0

### ISSUE THREAD

**Issue by siddharthsircar** [appium/appium#10168]
## The problem

There is a code in my Appium test that verifies the header of the page. While executing the test on Samsung S5, Android v6.0.1 , it runs perfectly without any hiccups. BUT, when I execute the same tests on Samsung S6, Android v7.0 [Nougat] it does not locate the elements and then at one point just stops.

[NOTE: I am calling non-gui Appium server using Java code.]

## Environment

* Appium version: Appium v1.7.2
* Desktop OS/version used to run Appium: Windows 10
* Mobile platform/version under test: Android v7.0
* Real device or emulator/simulator: Real Device [Samsung S6]
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

Link to Appium Logs: https://gist.github.com/siddharthsircar/b43ba9736d344fbf7864594bbab10448

## Code To Reproduce Issue [ Good To Have ]

	MobileElement notification_bell_icon= (MobileElement) driver.findElementById("com.onlife.alwayson.debug.release:id/layout_update_count_image_view_notifications");
		notification_bell_icon.click();
		writeDebugLogs("Notification Bell Icon Clicked");
		MobileElement notificationpage_header = (MobileElement) driver.findElementById("com.onlife.alwayson.debug.release:id/custom_toolbar_text_view_title");
		wait.until(ExpectedConditions.visibilityOf(notificationpage_header));
		String notificationpage_header_text = notificationpage_header.getText();
		softassert.assertEquals(notificationpage_header_text,"NOTIFICATIONS");
		writeDebugLogs("Notification header Verified");
		
Not just these elements, it is not locating other elements either.

**Comment by mykola-mokhnach** [comment]
Use UIAutomator2 backend for Android 6+

**Comment by siddharthsircar** [comment]
@mykola-mokhnach 
Do we need t add it as a Capability?
I am new to this.

**Comment by imurchie** [comment]
@siddharthsircar Yes. Set the `automationName` capability to `"uiautomator2"`.

**Comment by siddharthsircar** [comment]
Thanks for the help guys, a lot of code just started working.
