### ISSUE TITLE
Parallel testing.

### ISSUE THREAD

**Issue by trix0** [appium/appium#10170]
Heyo Its me Again. Sorry

Not sure If I should split this one to 2 issues

I am tryin to execute my code on multiple devices in tha same time.
## The problem
I am not able to lunch test on both devices. 
When I do not specify automationName. One of the device executes the test and other gets following error 
[UiAutomator] UiAutomator exited unexpectedly with code 0, signal null ([UiAutomator] UiAutomator exited unexpectedly with code 0, signal null
) 

Seems like the second process killed first one.

_______________________________________________
Therefore i decided to specify automationName to uiautomator2.

This time I am getting another error 
An unknown server-side error occurred while processing the command. Original error: Cannot create property 'replace' on boolean 'true'

## Environment

* Appium version (or git revision) that exhibits the issue:1.8.0beta3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:Ubuntu 16.04
* Node.js version (unless using Appium.app|exe):9.4.0
* Mobile platform/version under test:6.0.1
* Real device or emulator/simulator:1 Real  device 1 emulator 
* Appium CLI or Appium.app|exe:Cli

## Details
default driver works at least on one 1 device
Uiautomator2 does not work with none.

## Link to Appium logs
[Default driver ](https://gist.github.com/trix0/371bdf7070de2e9df8e4031c0a5b54d4)
[Default driver ports+1](https://gist.github.com/trix0/25ab11f6cfadf1a678c105dc2b849b13)

[UIautomator2 ](https://gist.github.com/trix0/9d4b47801eaf311046c0efd962f07f4c)
[Uiautomator2 ports+1](https://gist.github.com/trix0/368580ee858dff5b1b5072c795b88b23)

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/blob/55760b7b9e1c494c6a1f22d152f0bd1fe676dae7/docs/en/advanced-concepts/parallel-tests.md

**Comment by trix0** [comment]
Yeah, I followed it. 
2018-02-09 09:35:56:478 - info: [Appium] systemPort: 8200 on first one 
2018-02-09 09:35:56:474 - info: [Appium] systemPort: 8201 on second one
I have no idea whats wrong

**Comment by mykola-mokhnach** [comment]
Try to reinstall your beta in order to fix 

> An unknown server-side error occurred while processing the command. Original error: Cannot create property 'replace' on boolean 'true'

**Comment by trix0** [comment]
Reinstall fixed issue with replace. I am still not getting expected results. Can I test in parallel with default appium driver or do I have to use uiautomator2 ? I can see that in link you posted it states that I do not need multiple server instances. I ll try to keep just one I ll see whats gonna happen

**Comment by mykola-mokhnach** [comment]
It's up to you to have either one or multiple server instances. The main thing is to set different port numbers for each device. Also, UIA2 is highly recommended for devices running Android 6+
