### ISSUE TITLE
How to quit background apps in ios

### ISSUE THREAD

**Issue by anusha0009** [appium/appium#10171]
Hi,
I am trying to automate ios app using appium and my scenario is like:
I want  to launch app
After some time i want to close it  **( **Mandatory:: Close the app in background**)**
Launch it back again
I tried quit(), closeApp(), close(), resetApp() 
But none of them helps me in killing app from background.
Please can anyone help me out with this issue?.

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios/ios-xctest-mobile-apps-management.md

**Comment by anusha0009** [comment]
Hi @mykola-mokhnach ,
I saw the link you provided and tried terminateApp() ,
 but still i am able to see app in background.When i double tap on ios device home button,  there i am able to see my app.I don't want to see app in background. Can you please help me with this

**Comment by mykola-mokhnach** [comment]
There are no other primitives available in XCTest for application termination. Make sure you pass correct bundle identifier as an argument. I cannot advice more, since you didn't provide any logs or other details.
