### ISSUE TITLE
Rotation process inside a button

### ISSUE THREAD

**Issue by dron4ik85** [appium/appium#10176]
## The problem

I have a button and I need to do long pressing, after that I need to continue to press a button to rotate inside button.

![1](https://user-images.githubusercontent.com/21097858/36073436-2478c39a-0f39-11e8-9508-c76cfbc75f6b.jpg)

I try to do this process via python:
```
button = self.driver.find_element_by_accessibility_id('Status.slider')
self.action.long_press(button, duration=5000)\
        .move_to(el=button, x=272, y=376)\
        .move_to(el=button, x=187, y=455)\
        .move_to(el=button, x=99, y=361)\
        .move_to(el=button, x=218, y=290).release().perform()
```
not working for me....:(

## Environment

* Appium version : 1.7.2
* Desktop OS/version used to run Appium: Mac OS
* Node.js version (unless using Appium.app|exe): 9.4.0
* Mobile platform/version under test: iOS, Android
* Real device or emulator/simulator: iOS, Android

**Comment by mykola-mokhnach** [comment]
iOS changes for complex gestures support have been merged just recently and are not available even in beta version yet. Regarding Android - cannot say much without a server log.

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium-xcuitest-driver/commit/6af578ddcd322974b3189cf44eda518abab81fdd
