### ISSUE TITLE
Multiple Data Provider on one method

### ISSUE THREAD

**Issue by sagarsheth27** [appium/appium#10181]
Hi Guys

i have a problem like that i want to pass multiple data provider on one common method. This common method internally call other methods. Now the problem is that if this common method is not carrying parameters from dif'n data providers then i am unable to pass value in its inherits method's value as variable.

Coding structure is like below:

 @Test(priority=0,enabled=true,dataProviderClass=Utility.DataProvide.class,dataProvider="TC")
**(Here i want to add one more data provider and its parameters i want to pass in methods arguments.)**
    public void TC1(String TCID,String TCDESC,String RUNMODE) throws IOException, InterruptedException, AWTException {
    	
    	if(RUNMODE.equalsIgnoreCase("y") && TCID.equalsIgnoreCase("TC001"))
    	{
    		System.out.println("Runmode value for TC1 is:"+RUNMODE);
    		test = extent.startTest("Verify Streebo Mobile Forms Application");
    		t.testcase(driver, test, extent);
    		extent.endTest(test);
    		driver.closeApp();
    		Thread.sleep(10000);
    		
    		
    	}
    	
    	else if(RUNMODE.equalsIgnoreCase("n") && TCID.equalsIgnoreCase("TC001"))
    	{
    		test = extent.startTest("Verify Streebo Mobile Forms Application");
    		test.log(LogStatus.FAIL,"Unable to run login test case.");
    		extent.endTest(test);
    		driver.closeApp();
       		Thread.sleep(10000);
       		
    	}

Now my problem is that i want to pass here two data providers instead of one. how to pass it and what configurations i have to do?

**Comment by saikrishna321** [comment]
@sagarsheth27 Please raise questions [here](discuss.appium.io).
