### ISSUE TITLE
Issue connecting to WebDriverAgentRunner (connect ECONNREFUSED 127.0.0.1:8100)

### ISSUE THREAD

**Issue by tfcardoso** [appium/appium#10183]
## The problem

I have one client using automation, that keeps experiencing this error.

Any hint/tip for this to stop happening. It doesn't happen to me on local dev environment.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.7.1 / XCode8.3.3
* Desktop OS/version used to run Appium: OSX
* Mobile platform/version under test: iOS10.3
* Real device or emulator/simulator: Real Device

## Link to Appium logs

https://gist.github.com/tfcardoso/8ec8ddadee68bdd7f22dbe9c11b8b468

**Comment by mykola-mokhnach** [comment]
ECONNREFUSED means that WebDriverAgent stops responding to HTTP requests. I don't think one can do anything from Appium side in order to address such issues. I'd recommend updating all the components (iOS and Appium) to the most recent versions.

**Comment by tfcardoso** [comment]
Having useNewWDA set to true might help? (locally I dont have this issue, so cannot check if it fix or not).

**Comment by mykola-mokhnach** [comment]
I'd say it will make things worse for real devices. The count of WDA reinstalls between device reboots is limited.

**Comment by mykola-mokhnach** [comment]
Try to investigate the device log - perhaps you'll find more useful info there

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
