### ISSUE TITLE
Remove xcode version check when unnecessary

### ISSUE THREAD

**Issue by imurchie** [appium/appium#10188]
## The problem

When the user submits a `webDriverAgentUrl` with a running WDA instance, there is no need to check for the Xcode version, which can be slow, and can fail if indeed the server has no xcode installed. This only applied to real devices (since sims have to be run with Xcode anyway).

- [ ] Remove xcode version check from `appium-xcuitest-driver`
- [ ] Add some sort of default for xcode version (this may need to be specified, as the xcode version used to build the WDA bundle, in a cap (e.g., `wdaXcodeVersion` or something) since behavior sometimes needs to change.
- [ ] Go through the places where we use the xcode version, in both `appium-xcuitest-driver` and `appium-ios-driver`, and make sure nothing is broken
- [ ] Figure out how to run at least some tests using the `webDriverAgentUrl` cap, in CI.

**Comment by imurchie** [comment]
From `appium-xcuitest-driver`:
* ~Screenshot - on sims we can't tell whether simctl works for screenshots~
* Element screenshots - error on xcode version less than 9
* Check if we can handle the platform desired
* Automatically suppress WDA attachments
* ~Device logging is dependent on version for simulators~
* ~Sim app termination~
* Translating device name

From `appium-ios-driver`:
* ~Device logging is dependent on version for simulators~

**Comment by mykola-mokhnach** [comment]
> Screenshot - on sims we can't tell whether simctl works for screenshots

Checking the return code might be faster:

```bash
$ xcrun simctl bla
$ echo $?
1
$ xcrun simctl io
$ echo $?
117
```

**Comment by mykola-mokhnach** [comment]
We could also memoize the version getter

**Comment by imurchie** [comment]
Sims it doesn't really matter. This is mostly setting it up so you can run the system on an Xcode-less system.
