### ISSUE TITLE
WDA is not listening at 'http://localhost:8100/' iOS app not maintained opened

### ISSUE THREAD

**Issue by OscarOrozcoGomez** [appium/appium#10186]
## Environment

* Appium version 1.3.2
* Last Appium version that did not exhibit the issue (i think it was 1.3.1):
* Desktop OS/version used to run Appium: MacOS High Sierra 10.13.1
* Node.js version (unless using Appium.app|exe): v8.9.4
* Mobile platform/version under test: iOS
* Real device or emulator/simulator:N/A
* Appium CLI or Appium.app|exe: N/A

## Details

I am barely starting to automate the app, so i am going to start to build my framework but i decided to start to install the needed tools since this is my first time using appium so, i made the installation and everything was fine until the update came into place, now every time i run a script (This script is a very simple one) the appium server does not maintain the app opened, i can not use the inspector to establish the session and start object details to be able to automate the app, which in android i am able to. i been doing a couple of thing so far but nothing seems to work

## Link to Appium logs

https://github.com/OscarOrozcoGomez/Appium-logs-failures/blob/master/appiumLogs.txt

## Code To Reproduce Issue [ Good To Have ]
@BeforeMethod
    public void setUpIos() throws MalformedURLException {
        File f = new File("/Users/Application/");
        File fs = new File(f, "QA-1188.1188.ipa");
        DesiredCapabilities cap = new DesiredCapabilities();
        cap.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
        cap.setCapability(MobileCapabilityType.PLATFORM_VERSION, "11.2");
        cap.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 6");
        cap.setCapability("showXcodeLog", "true");
        cap.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.IOS_XCUI_TEST);
        cap.setCapability(MobileCapabilityType.APP, fs.getAbsolutePath());
        driver = new IOSDriver(new URL("http://localhost:4723/wd/hub"), cap);
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
        //cap.setCapability("xcodeOrgId", "R4LJ2494A9");
        //cap.setCapability("xcodeSigningId", "iPhone Developer");
        //cap.setCapability(MobileCapabilityType.UDID, "CA7E6812-9127-4AB4-A73F-603625BD1FD4");
        //cap.setCapability(IOSMobileCapabilityType.LAUNCH_TIMEOUT, "5000000");
    }
 @Test
    public void run() {
  Nothing is here yet
    }

   /@AfterMethod
    public void tearDown() {
        driver.close();
        driver.quit();
    }

Note: as you can see, it is a very simple script since i have not been able to continue

Need your help please.
Regards.
Oscar Orozco

**Comment by mykola-mokhnach** [comment]
I see a mess there and no errors. Are you testing Android or iOS? If you just want to keep app running after the test is finished then set `noReset` capability to `true`. Also, use gists to attach logs.

**Comment by OscarOrozcoGomez** [comment]
My bad, i already corrected the Log and the comments.

I am actually testing a iOS device

**Comment by mykola-mokhnach** [comment]
I don't observe any issues in the log. Try to cleanup the xcode caches and reset the simulator.

**Comment by OscarOrozcoGomez** [comment]
@mykola-mokhnach I already tried to reset Xcode and simulator but i am not able to have the app apened, i tried to execute the Inspector and this is what i get.

https://github.com/OscarOrozcoGomez/Appium-logs-failures/blob/master/Screen%20Shot%202018-02-13%20at%2012.20.54%20PM.png

And i have the plarform in the code so i wonder what is going on?

Thanks for your help

**Comment by mykola-mokhnach** [comment]
Sorry, I cannot help, since the information, that you provided, is contraversive.

**Comment by OscarOrozcoGomez** [comment]
Well, what else should i include?
The funny thing is that in android i am able to run any test without any problems but in iOS the app is installed, WebdriverAgent is also installed into the simulator, after the WDA is installed my applications opens up and closes back again, if i open the application manually this opens and closed very fast so i dont understand what is going on.

**Comment by mykola-mokhnach** [comment]
>  if i open the application manually this opens and closed very fast so i dont understand what is going on.

This means your app is most likely broken and cannot be executed on Simulator at all/crashes at startup. Check it with your developers.

**Comment by mycatnamedweb** [comment]
I had a similar issue and found out from the simulator logs that I was trying to use an App built for the ARM architecture.

Other common possible causes are:
- incorrect certificate
