### ISSUE TITLE
UiAutomator exited unexpectedly with code 255

### ISSUE THREAD

**Issue by skumar1122** [appium/appium#10185]
## The problem
I am using latest appium java client with selenium Grid to run on Android devices(OS-7/8) and I am getting an error "Unhandled rejection Error: UiAUtomator shut down unexpectedly" on my mac  machine.

Can someone please have a look at this ?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Node.js version (unless using Appium.app|exe): v8.4.0
* Mobile platform/version under test: 7.0 and 8.0
* Real device or emulator/simulator: Samsung S6 and Samsung S6Edge
* Appium CLI or Appium.app|exe: Appium from CLI on Mac

## Details
Sample Local Code: Setting capabilities 

if (DeviceHandler.getPlatformName().equalsIgnoreCase("Android")) {
                setupDevice().setDeviceType(AppiumDeviceTypesEnum.ANDROID_DEVICE).setPlatformName(DeviceHandler.getPlatformName())
                        .setPlatformVersion(DeviceHandler.getPlatFormVersion()).setDeviceName(DeviceHandler.getDeviceName()).setDeviceUDID(DeviceHandler.getUdid());
                setupDeviceServer().setBrowserName("Chrome").setFullReset(false).setAutoLaunch(false);
                ChromeOptions options = new ChromeOptions();
                options.addArguments("disable-translate");
                options.addArguments("disable-popup-blocking");
                options.addArguments("disable-save-password-bubble");
                options.addArguments("enable-automatic-password-saving");
                setupAndroidDriver().setChromeOptions(options).setAndroidDeviceReadyTimeout(60)
                        .setEnablePerformanceLogging(true);
                createAndroidDriver("http://" + DeviceHandler.getAppiumServerIP() + ":" + DeviceHandler.getAppiumServerPort() + "/wd/hub");
            } 

## Link to Appium logs

https://gist.github.com/skumar1122/5c7c497b84a562050285c9b06e0ba099

**Comment by mykola-mokhnach** [comment]
1. Use uiatomator2 backend for Android 6+
2. Change `browserName` to `chrome`

**Comment by XinCai** [comment]
i have encountered the same issue

**Comment by mrk-han** [comment]
Another potential workaround for UIAutomator:

1) Clear all data of Emulator from AVD Menu in Android Studio
2) Cold Boot the device.

This was with a pixel 2, on 9.0
