### ISSUE TITLE
Appium: Switch to nested iframe doesn't work if iframes domains are different

### ISSUE THREAD

**Issue by sugatmankar** [appium/appium#10184]
WebDriver for Appium iOS real device doesn't switch to nested inner iframe which renders from different domains.  

Application abstract structure : 

```
<iframe>   // this iframe render content from  https://www.abc.com
 
         <iframe >  // this iframe render content from https://www.xyz.com
 
         </iframe > // END of inner
 
</iframe> // END of outer
```

## Environment

* Appium version (or git revision) that exhibits the issue:  1.8.0-beta
* Desktop OS/version used to run Appium: macOS High Sierra 10.13.3
* Node.js version (unless using Appium.app|exe): 5.6.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real Device , Safari Browser

## Details

Got error : Error while executing atom: Blocked a frame with origin "https://www.xyz.com" from accessing a frame with origin "https://www.abc.com". Protocols, domains, and ports must match. (status: 18)

If i access site manually by keeping following PRIVACY & SECURITY settings i can play with application.
Prevent Cross-Site Tracking : OFF
Block All Cookies : OFF
Ask Websites Not to Track me : OFF
Fraudulent Website Warning: OFF

but when i launch application through automation, application page loads successfully and throw exception Blocked a frame with origin .... 

## Appium log

```
[debug] [RemoteDebugger] Receiving WebKit data: '{"result":{"result":{"type":"string","value":"{\"status\":18,\"value\":{\"message\":\"Blocked a frame with origin \\\"https://www.xyz.com\\\" from accessing a frame with origin \\...'

[debug] [RemoteDebugger] Found handler for message '40'

[MJSONWP] Encountered internal error running command: Error: Error while executing atom: Blocked a frame with origin "https://www.xyz.com" from accessing a frame with origin "https://www.abc.com". Protocols, domains, and ports must match. (status: 18)

    at XCUITestDriver.callee$0$0$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/web.js:197:11)

    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)

    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)

    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)

    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)

    at <anonymous>
```

Known issue is already in closed status 
Cannot access iframe content on iOS test due to same-origin policy #9464

**Comment by SanYann** [comment]
Same issue here

**Comment by Gamaiva** [comment]
I am also getting same issue @mykola-mokhnach  any solution for this

**Comment by apuig1** [comment]
Yes, same issue here. Any solution to this?

**Comment by imurchie** [comment]
This is a hard condition given by Apple. There is no general way around it, and nothing Appium can do to mitigate it. The only thing that often works is http://appium.io/docs/en/advanced-concepts/cross-domain-iframes/

**Comment by KazuCocoa** [comment]
https://appium.github.io/appium.io/docs/en/advanced-concepts/cross-domain-iframes/
