### ISSUE TITLE
Proxy error in UIA2 for gsm calls/send sms endpoints

### ISSUE THREAD

**Issue by SrinivasanTarget** [appium/appium#10198]
## The problem

Proxy error in UIA2 for gsm calls/send sms endpoints 
https://github.com/appium/appium-base-driver/blob/master/lib/protocol/routes.js#L366-L375

## Environment

* Appium version (or git revision) that exhibits the issue: latest master
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe): 8
* Mobile platform/version under test: android 8.0
* Real device or emulator/simulator: emu
* Appium CLI or Appium.app|exe:

## Details

https://gist.github.com/SrinivasanTarget/44129149c2005d46feb04e0c9593a0da

Same works fine with UIA1 mode.

@mykola-mokhnach @jlipps ping

**Comment by mykola-mokhnach** [comment]
The fix is merged and will be available in the upcoming driver version.
