### ISSUE TITLE
.getSupportedPerformanceDataTypes() &  getMemoryInfo(driver).get() giving Encountered internal error running command

### ISSUE THREAD

**Issue by Hashili** [appium/appium#10197]
## The problem

.getSupportedPerformanceDataTypes() &  getMemoryInfo(driver).get() giving Encountered internal error running command

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): dont Know
* Desktop OS/version used to run Appium: CLI
* Node.js version (unless using Appium.app|exe):8.9.3
* Mobile platform/version under test: 6.0.1
* Real device or emulator/simulator:Read Device
* Appium CLI or Appium.app|exe: CLI

## Details

Was running below g below code to get performance details of mobile app developed in ReactNative.

`try {
			// get the usage at one point in time
			LoginTests.isLoggedIn("participant");
			/*List<String> mySupportedType = driver.getSupportedPerformanceDataTypes();
			for(String type:mySupportedType) {
				System.out.println("type:"+type);
				LogUtil.info("type:"+type);
			}*/
			int totalPss1 = getMemoryInfo(driver).get(PSS_TYPE);

			// then get it again after waiting a while
			try { 
				Thread.sleep(MEMORY_USAGE_WAIT); 
			} catch (InterruptedException ign) {

			}
			int totalPss2 = (int) getMemoryInfo(driver).get(PSS_TYPE);

			// finally, verify that we haven't increased usage more than 5%
			// Assert.assertThat((double) totalPss2, Matchers.lessThan(totalPss1 * 1.05));
			LogUtil.info("totalPss1:"+totalPss1);
			LogUtil.info("totalPss2:"+totalPss2);

		} finally {
			driver.quit();
		}`

## Link to Appium logs

[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/7098bd72-5d5e-455b-bf51-80ec6b106d3e/appium/getPerformanceData] to [POST http://localhost:8201/wd/hub/session/3c695079-5f6e-48a1-a92b-e49c98272ab7/appium/getPerformanceData] with body: {"packageName":"com.planready.test","dataType":"memoryinfo","dataReadTimeout":30}
[MJSONWP] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 404 - undefined
    at doJwpProxy$ (../../../lib/mjsonwp/mjsonwp.js:384:13)
    at tryCatch (C:\Users\Hashili.MA\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Hashili.MA\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\Hashili.MA\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\Hashili.MA\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at <anonymous>
[HTTP] <-- POST /wd/hub/session/7098bd72-5d5e-455b-bf51-80ec6b106d3e/appium/getPerformanceData 500 79 ms - 274 
FAILED: testMemoryUsage
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 404 - undefined (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Can you please attach the full log?

**Comment by vjmaiky** [comment]
i gave it a try on getMemoryInfo(driver).get()  with appium 1.7.2, android emulator, and it is working as expected; i get the values...i received that error only when package id was miss-typed .

**Comment by Hashili** [comment]
@vjmaiky @mykola-mokhnach 
I am still getting the issue. I have tried with appium CLI 1.7.1 and Real Android device 6.0.1. Please see the attached Appium server log and source code. Please ReOpen this issue
[ServerLog.txt](https://github.com/appium/appium/files/1731492/ServerLog.txt)
[SourceCode.txt](https://github.com/appium/appium/files/1731494/SourceCode.txt)

**Comment by mykola-mokhnach** [comment]
Update Appium like @vjmaiky mentioned above
