### ISSUE TITLE
Appium version 1.7.2 kills other idevicesyslog process

### ISSUE THREAD

**Issue by nxt-kai-molander** [appium/appium#10195]
## The problem

Appium version 1.7.2 kills my own `idevicesyslog` process when 'logCaptureStarted' is called.

## Environment

* Appium version 1.7.2, did not occur in Appium 1.7.1.

## Details

`idevicesyslog -u <id>` is started via a Python script. Python script then runs `mvn clean test` which runs Java test code. Appium server is started via Java `AppiumDriverLocalService`.

Capabilities:

```
capabilities.setCapability("platformName", "iOS");
capabilities.setCapability("automationName", "xcuitest");
capabilities.setCapability("processArguments", <some args>);
capabilities.setCapability("deviceName", "iPhone");
capabilities.setCapability("udid", properties.local.deviceId);
capabilities.setCapability("app", properties.local.appFilePath);
capabilities.setCapability("xcodeOrgId", <id is here>);
capabilities.setCapability("xcodeSigningId", "iPhone Developer");
capabilities.setCapability("useNewWDA", true);
```

## Appium log

[debug] [BaseDriver] Event 'resetStarted' logged at 1518603741113 (12:22:21 GMT+0200 (EET))
[debug] [XCUITest] Reset: running ios real device reset flow
[debug] [BaseDriver] Event 'resetComplete' logged at 1518603741114 (12:22:21 GMT+0200 (EET))
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Starting iOS device log capture with: 'idevicesyslog'
[debug] [XCUITest] Crash reports root '/Users/admin/Library/Logs/CrashReporter/MobileDevice/admin-iphone' does not exist. Got nothing to gather.
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1518603741314 (12:22:21 GMT+0200 (EET))
[XCUITest] Setting up real device

## idevicesyslog process

kCLConnectionMessageWatchdog' received from client '/System/Library/PrivateFrameworks/BulletinBoard.framework'
Feb 14 11:58:14 admin-iphone locationd[57] <Notice>: message 'kCLConnectionMessageWatchdog' received from client '/System/Library/LocationBundles/Routine.bundle'
Feb 14 11:58:17 admin-iphone locationd[57] <Notice>: message 'kCLConnectionMessageWatchdog' received from client '/System/Library/LocationBundles/MagicalMoments.bundle'
Feb 14 11:58:17 admin-iphone locationd[57] <Notice>: Incrementing METs -- mets:<private> metsFromGrade:<private>
Feb 14 11:58:18 admin-iphone locationd[57] <Notice>: message 'kCLConnectionMessageWatchdog' received from client '/System/Library/PrivateFrameworks/CoreParsec.framework'
Feb 14 11:58:19 admin-iphone locationd[57] <Notice>: message 'kCLConnectionMessageWatchdog' received from client '/System/Library/PrivateFrameworks/HomeKitDaemon.framework'

Exiting...

**Comment by nxt-kai-molander** [comment]
Just confirmed that installing 1.7.1 and running the exact same code, this issue does not occur. Both idevicesyslog processes are left running.

**Comment by mykola-mokhnach** [comment]
This is done by design to avoid resource leaks in case if appium session has not been finished properly.

**Comment by nxt-kai-molander** [comment]
@mykola-mokhnach so you think its OK to kill processes the user has started? I really don't see that as the right approach.

**Comment by mykola-mokhnach** [comment]
Here is the code responsible for that logic: https://github.com/appium/appium-ios-driver/blob/6948dc4721ff3ed8150927036d2452bd9f088fe9/lib/device-log/ios-log.js#L95

You're welcome to implement it in a better way
