### ISSUE TITLE
Feature Request: MultiApp automation support with XCode 9.x

### ISSUE THREAD

**Issue by amitg25** [appium/appium#10190]
XCode 9.x now supports multiple application automation on iOS devices. Can Appium provide similar support so we can test multiple apps in one session on iOS on Both Simulator and Real devices?

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios/ios-xctest-mobile-apps-management.md
