### ISSUE TITLE
Unable to launch WebDriverAgent because of xcodebuild failure: “xcodebuild failed with code 65”

### ISSUE THREAD

**Issue by muditgarg13** [appium/appium#10199]
## The problem

I am trying to run amazon app on iphone 6 simulator using Xcode. The app is getting installed in the iphone Simulator but not able to interact with its elements. 
Downloaded the app (& not built it from xcode project) - i.e. xxx.app.ipa

## Environment

Appium version - 1.7.2 
Xcode Version 9.2 
Platform Mac- 10.12.6 

## Link to Appium logs

Logs: [https://gist.github.com/muditgarg13/36ec80e8b02a625309c8c1b10a57714d](https://gist.github.com/muditgarg13/36ec80e8b02a625309c8c1b10a57714d)

**Comment by mykola-mokhnach** [comment]
Are you able to run the application manually on Simulator? 

the gist returns 404 error

**Comment by imurchie** [comment]
Please attach the full server log, as a link to a [gist](https://gist.github.com).

**Comment by muditgarg13** [comment]
@mykola-mokhnach  - As soon as I click on app manually on simulator- a blank page opens & app closes instantly.

**Comment by muditgarg13** [comment]
@imurchie this are logs https://gist.github.com/muditgarg13/5fc509f6c9ff9617947c06306454bef7

**Comment by muditgarg13** [comment]
@imurchie Logs: https://gist.github.com/muditgarg13/a8176ed11cfb1775e4e895ef69c57d39

**Comment by mykola-mokhnach** [comment]
Then it is an issue with your app rather than with Appium.

**Comment by muditgarg13** [comment]
I am not creating/building any app - just re-using the app provided by dev team for testing.
Now I am using a correct app. I installed it manually to I0S simulator & it is working fine manually.
Now- I am getting some error related to webdriver. I think I am not able to install webdriver agent to simulator.
Is there a reference document which I can refer to install webdriver on the simulator?
This is my logs file: https://gist.github.com/muditgarg13/9ec4d1d2e6e3ed41305acdb82d75ce2f

**Comment by imurchie** [comment]
The logs seem to indicate that it is a permissions problem:
```
Couldn't create workspace arena folder '/Applications/Xcode.app/Contents/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs': You don’t have permission to save the file “WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs” in the folder “DerivedData”.
```

**Comment by muditgarg13** [comment]
@imurchie you are right. 
It was a permission issue. fixed that by giving permissions to this folder /Applications/Xcode.app
