### ISSUE TITLE
[iOS] Can't swipe verically on iPad in Landscape orientation.

### ISSUE THREAD

**Issue by shynkevich-alex** [appium/appium#10192]
## The problem

When i try swipe vertically it swipes horizontally.
The same issue in appium desktop

## Environment

* Appium version 1.7.2
* Desktop OS/version used to run Appium:
* npm version 5.6.0
* iOS 11.2.5
* iPad Pro (10.5-inch)
* appium-xcuitest-driver 2.68.0 
* java-client 6.0.0-BETA2

## Link to Appium logs

> [debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":938,"y":662}},{"action":"moveTo","options":{"x":-3,"y":-457}},{"action":"release","options":{}}],"e9c4ea89-4f03-4c1c-986d-16c9b9eeeb6f"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: press(options={"x":938,"y":662})-moveTo(options={"x":-3,"y":-457})-release(options={})
[debug] [XCUITest] Found matching gesture: scroll
[debug] [JSONWP Proxy] Proxying [POST /wda/dragfromtoforduration] to [POST http://localhost:8100/session/A70436F6-F616-4B58-A3CB-1883D88861BE/wda/dragfromtoforduration] with body: {"fromX":938,"fromY":662,"toX":935,"toY":205,"duration":0}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"A70436F6-F616-4B58-A3CB-1883D88861BE","status":0}
[debug] [MJSONWP] Responding to client with driver.performTouch() result: null

## Code To Reproduce Issue [ Good To Have ]

(new TouchAction(driver))
  .press({x: 938, y: 662})
  .moveTo({x: -3: y: -457})
  .release()
  .perform()

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/facebook/WebDriverAgent/issues

BTW: https://github.com/facebook/WebDriverAgent/issues/856
