### ISSUE TITLE
W3C. The wrong exception is thrown in browser mode when such element doesn't exist.

### ISSUE THREAD

**Issue by TikhomirovSergey** [appium/appium#10207]
## The problem

The wrong exception is thrown in browser mode when such element doesn't exist. W3C compliance.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0-beta3
* Last Appium version that did not exhibit the issue (if applicable): 1.7.x
* Node.js version (unless using Appium.app|exe): v8.9.1
* Mobile platform/version under test: I could reproduce it on Android. Because of some issues I don't work on iOS. I suppose it may be reproduced in iOS too.
* Real device or emulator/simulator: emulator

## Details
Result of the failed searching is returned as map to the client. This result can't be converted to WebElement or NoSuchElementException.

## Code To Reproduce Issue [ Good To Have ]

Works as expected: 
```java
   @Before public void setUp() {
        service = AppiumDriverLocalService.buildDefaultService();
        service.start();

        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Android Emulator");
        capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, MobileBrowserType.BROWSER);
        capabilities.setCapability(MobileCapabilityType.FORCE_MJSONWP, true); //<-!!!
        driver = new AndroidDriver<RemoteWebElement>(service.getUrl(), capabilities);
    }

    @Test(expected = NoSuchElementException.class) public void test() {
        driver.get("https://www.google.com");
        driver.findElement(By.id("btnG"));//there is
        //the element which has name=btnG, but not id
    }
```

![image](https://user-images.githubusercontent.com/4927589/36280100-49e24286-12aa-11e8-957e-a9274eb36f30.png)

Server output:
https://gist.github.com/TikhomirovSergey/f68a8d95ebe6826ab3a45121ef91de75

Unexpected behaviour:
```java
    @Before public void setUp() {
        service = AppiumDriverLocalService.buildDefaultService();
        service.start();

        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Android Emulator");
        capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, MobileBrowserType.BROWSER);
        //capabilities.setCapability(MobileCapabilityType.FORCE_MJSONWP, true); //<-!!!
        driver = new AndroidDriver<RemoteWebElement>(service.getUrl(), capabilities);
    }

  @Test(expected = NoSuchElementException.class) public void test() {
        driver.get("https://www.google.com");
        driver.findElement(By.id("btnG"));//there is
        //the element which has name=btnG, but not id
    }
```
![image](https://user-images.githubusercontent.com/4927589/36280302-e56d0ede-12aa-11e8-8772-eba65b82e8ed.png)

Server output:
https://gist.github.com/TikhomirovSergey/72be6b82c9fbfd52eadecf1d59dafb84

**Comment by mykola-mokhnach** [comment]
@dpgraham FYI. It looks like we need to also apply some transformation magic to responses received from chromedriver.

**Comment by dpgraham** [comment]
@mykola-mokhnach It does have logic to translate JSONWP to W3C for proxied responses. Is this not working correctly?

**Comment by mykola-mokhnach** [comment]
> Caused by: org.openqa.selenium.WebDriverException: Returned value cannot be converted to WebElement: {message=no such element: Unable to locate element: {"method":"id","selector":"btnG"}

Something is for sure not good here

**Comment by dpgraham** [comment]
@mykola-mokhnach Yep. I'll try to reproduce it on my side.

**Comment by mykola-mokhnach** [comment]
Most likely the response code still equals to 200, even if error description is returned there.

**Comment by mykola-mokhnach** [comment]
Check https://github.com/SeleniumHQ/selenium/blob/6104872dc1424838466bfa065ad69121ad1f8bb8/java/client/src/org/openqa/selenium/remote/http/W3CHttpResponseCodec.java#L85 for more details

**Comment by dpgraham** [comment]
I have a PR in for this. The issue was that C.D. is return HTTP Status Code 200 (success) despite having a JWP status code >= 0 (an error code). This was confusing base-driver and causing it to just catch it as an UnknownError. Added logic to parse this type of error.
