### ISSUE TITLE
send_keys on Android 7.0+ executes a long press

### ISSUE THREAD

**Issue by oscheller1** [appium/appium#10202]
I've noticed that when sending keys to Edit Text fields on Android 7.0 and higher (which is translated to `[debug] [MJSONWP] Calling AppiumDriver.setValue()` on the appium server) executes a long press on the Edit text field. This triggers an `Insert from clipboard` popup inside the android app, which then sometimes messes up the UI and makes the following action unrealiable (e.g. doesn't find a soft keyboard when calling hide_keyboard, even though it's there -> test crashes).

Is this a known problem? Otherwise I can investigate this a little bit further.

In my opinion, a quick fix would be Appium should never execute a long press on a Edit Text field to not have the insert popup show up.

**Comment by mykola-mokhnach** [comment]
Is it reproducible in the recent appium@beta?

**Comment by oscheller1** [comment]
Installed appium 1.8.0 beta3. It's still the same thing. Seems like 2 long presses on every Edit Text field before writing the text. This still triggeres the clipboard popups (and a cut popup if there was text beneath the long press)

**Comment by mykola-mokhnach** [comment]
I don't see any places where extra clicks are being performed in UIA2 server. Try to delete all the appium stuff manually from the device to make sure you have the latest server version.

**Comment by vmaxim** [comment]
@mykola-mokhnach It is UIA1 clear text behaviour.

**Comment by mykola-mokhnach** [comment]
So one has to use UIA2-compatible element locator in order to avoid the execution of UIA1 clear text helper. Right @vmaxim ?

**Comment by vmaxim** [comment]
@mykola-mokhnach I am not sure right now. `Logcat` can be helpful.
@oscheller1 Can you please attach `adb logcat` with this issue?

**Comment by oscheller1** [comment]
@vmaxim Will do tomorrow when I'm back at work.
Does this mean the python appium client find_element_by_uiautomator doesn't use UIA2 ? Cause I believe we have set the capability to UIA2 if i'm not mistaken! anyway, will check tomorrow

**Comment by mykola-mokhnach** [comment]
> Does this mean the python appium client find_element_by_uiautomator doesn't use UIA2 ? Cause I believe we have set the capability to UIA2 if i'm not mistaken! anyway, will check tomorrow

@oscheller1 
It works, but the problem there, that the resulting element is still of UIObject class and applies all the corresponding methods. This means you must avoid such locators for text input fields in order to not have the behaviour described above

**Comment by vmaxim** [comment]
@mykola-mokhnach I can see only one possibility which is closed by appium/appium-uiautomator2-server#89

**Comment by mykola-mokhnach** [comment]
@vmaxim Yep, that is why I asked whether the most recent server version is used

**Comment by oscheller1** [comment]
Setting `automationName` desired capability to `uiautomator2` fixed the problem (Was not set before)! No more long presses now 👍  . @vmaxim Do you still want logs for the UIA1 problem?

**Comment by mykola-mokhnach** [comment]
I don't think we want to spend time fixing UIA1. It is anyway an obsolete technology for Android 6+, which is not supported by Google anymore.
