### ISSUE TITLE
unable to run test cases on chrome browser, even after starting appium server with --chromedriver-executable parameter 

### ISSUE THREAD

**Issue by sbongara** [appium/appium#10208]
## The problem

Ubable to switch context from native android to web view, getting the following error.

Error:io.appium.java_client.NoSuchContextException: An unknown server-side error occurred while processing the command. Original error: chrome not reachable

## Environment

* Appium version (or git revision) that exhibits the issue:1.7.1
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Mac OS High Sierra 10.13.1
* Node.js version (unless using Appium.app|exe):v6.11.3
* Mobile platform/version under test:Android 7.0, Chrome 64.0.3282
* Real device or emulator/simulator: Samsung Galaxy S8+
* Appium CLI or Appium.app|exe: Appium CLI Command used to start server(node appium -a 127.0.0.1 -p 4723 -cp 4723 -bp 2345 --chromedriver-executable /Users/path/chromedriver/chromedriver)

## Details

Clicking on a button in native app will launch a new chrome instance with a new page, I just need to check the whether the page is opened or not and the content in the page is displayed

## Link to Appium logs

https://gist.github.com/sbongara/97f676027a9f03055b5ee985183b5d3c

## Code To Reproduce Issue [ Good To Have ]

supportpage.clickOnAdvanceTs();
		Thread.sleep(15000);
		
		Set<String> contextNames = wd.getContextHandles();
        System.out.println("###############"+contextNames.size());
        for (String contextName : contextNames) {
            System.out.println("@@@@@@@@@@@@"+contextName);
            if (contextName.contains("WEBVIEW_chrome")){
                wd.context(contextName);
            }
        }
		boolean charexist  = wd.getPageSource().contains("Troubleshootiing");
         System.out.println(charexist);

**Comment by sbongara** [comment]
When i check the contexts, there are three
###############3
@@@@@@@@@@@@NATIVE_APP
@@@@@@@@@@@@WEBVIEW_xxx.pvt.debug
@@@@@@@@@@@@WEBVIEW_chrome

**Comment by mykola-mokhnach** [comment]
1. Are you able to debug the webview manually via Chrome remote debugger?
2. Are you sure that the current chromedriver version [matches](https://github.com/appium/appium/blob/909694b39d8a110c50b267341b3b911be468bbae/docs/en/writing-running-appium/web/chromedriver.md) to the actual webview version?
