### ISSUE TITLE
element.sendKeys("hi there")] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command.

### ISSUE THREAD

**Issue by Codude** [appium/appium#10200]
## The problem

sendKeys() doesnt work.
click() method doesnt show response

## Environment

* Appium version (or git revision) that exhibits the issue:1.3.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:OSX 10.12
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android
* Real device or emulator/simulator: both
* Appium CLI or Appium.app|exe: Appium.dmg and appium desktop both result the same

## Details

simple automation code for my own application that had just a edit text button and a text view to display the text in the edit text when button is clicked. App works fine but automation fails with the error 
**element.sendKeys("name")] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command.**

## Link to Appium logs

[HTTP] <-- GET /wd/hub/session/2b1f2d90-a4c5-4249-ba5d-f4a5f71d7e45/source 200 194 ms - 5964 
[HTTP] --> GET /wd/hub/session/2b1f2d90-a4c5-4249-ba5d-f4a5f71d7e45/screenshot {}
[MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["2b1f2d90-a4c5-4249-ba5d-f4a5f71d7e45"]
[ADB] Device API level: 23
[MJSONWP] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAAAtAAAAUACAYAAABuzmU9AABiIUlEQVR4AezBCXxcB33o+985Z/aRNJoZ7fsuy5IsW97k3YnjBGcjhCRAFigpYcmlFOil66O8u/R2ea/tbS+llAKhhCWEQCCBQJwEO9733ZYlS9Yua5dG0mj2Oa+Hz2f6mfrJ9nhJYif/71dZvOEZHSGEEEIIIURKVIQQQgghhBApUxFCCCGEEEKkTEUIIYQQQgiRMhUhhBBCCCFEylSEEEIIIYQQKVMRQgghhBBCpExFCCGEEEIIkTIVIYQQQgghRMpUhBBCCCGEEClTEUII8Z7mdJpxZ9owm1VSoWkqmS4baU4LQgjxXmRCCCHEe5LFrJGb42RxYw6eTBvHT43Qem6cUCjGpZjNKrVVHpoX5TE9E+LoyWEuDPkJR2IIIcR7hQkhhBDvOWlOC/ULsti4tpiaCg8z/jD+uQhdvT5CoRiXYjFrVJa5WbIoh4x0K/ULsti2s5dTZ0eZngkjhBDvBSaEEEK8p7gyrLQsK2DT+lLcmTZaz41z5PgQx0+NYjarNNRlkemyYbVoaJpCPA6hUJSp6RDDI3627+5lyhekuSmXBdVeHryvBnemjd0HBpjyBRHivURVFawWjVA4RjyuI94bTAghhHjPSHNaaFlWwPs2lWMxa+za18+2Xb2EQjFqqz0srPVSXpJJlteO3W7CpKnEYjqBYJTxiTm6en2cbZ+grXOC9s5Jbl9XQsuyAjbfVoZh574+pmfC3AhWq4bDbiYSieOfC6Pr/JaqKmS6rAQCUQLBKLcSTVOpLMukrCSDE6dHGRrx83apq/GS7XVg8M2EOH5qBHH97DYTVRVuTp4Z5VpZzBqlJRmUFbvwuu3Y7SZUVUHX+S1FAV3ntxQFdJ3fUhTQdX5LUUDX+S1FAV3nhojF4swFokxOBentn6a7z0c4HOO9zsQNlJ5mYdXyArZu6yZV6WkWVi0vYOu2bq7FiuZ86hdk4XSYCQSjdHRNsmvfALFYnFSs...
[HTTP] <-- GET /wd/hub/session/2b1f2d90-a4c5-4249-ba5d-f4a5f71d7e45/screenshot 200 1142 ms - 39122 
[HTTP] --> POST /wd/hub/session/2b1f2d90-a4c5-4249-ba5d-f4a5f71d7e45/elements {"using":"id","value":"com.example.androidapp.helloworld:id/name"}
[MJSONWP] Calling AppiumDriver.findElements() with args: ["id","com.example.androidapp.helloworld:id/name","2b1f2d90-a4c5-4249-ba5d-f4a5f71d7e45"]
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Waiting up to 0 ms for condition
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"com.example.androidapp.helloworld:id/name","context":"","multiple":true}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"com.example.androidapp.helloworld:id/name","context":"","multiple":true}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'com.example.androidapp.helloworld:id/name' using 'ID' with the contextId: '' multiple: true
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[RESOURCE_ID=com.example.androidapp.helloworld:id/name]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements selector:UiSelector[RESOURCE_ID=com.example.androidapp.helloworld:id/name]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Element[] is null: (0)
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements tmp selector:UiSelector[INSTANCE=0, RESOURCE_ID=com.example.androidapp.helloworld:id/name]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Element[] is null: (1)
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements tmp selector:UiSelector[INSTANCE=1, RESOURCE_ID=com.example.androidapp.helloworld:id/name]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":[{"ELEMENT":"1"}]}
[AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"1"}]
[HTTP] <-- POST /wd/hub/session/2b1f2d90-a4c5-4249-ba5d-f4a5f71d7e45/elements 200 130 ms - 89 
[HTTP] --> POST /wd/hub/session/2b1f2d90-a4c5-4249-ba5d-f4a5f71d7e45/element/1/value {"value":["hi there"]}
[MJSONWP] Calling AppiumDriver.setValue() with args: [["hi there"],"1","2b1f2d90-a4c5-4249-ba5d-f4a5f71d7e45"]
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:setText","params":{"elementId":"1","text":"hi there","replace":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:setText","params":{"elementId":"1","text":"hi there","replace":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: setText
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using element passed in: 1
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Attempting to clear using UiObject.clearText().
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Text not cleared. Assuming remainder is hint text.
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Sending plain text to element: hi there
[AndroidBootstrap] Received command result from bootstrap
[HTTP] <-- POST /wd/hub/session/2b1f2d90-a4c5-4249-ba5d-f4a5f71d7e45/element/1/value 500 223 ms - 154 
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":13,"value":"Unknown error"}
![screen shot 2018-02-15 at 11 05 20 am](https://user-images.githubusercontent.com/36496990/36242189-81d2cde2-1240-11e8-980e-279d2a761a34.png)

**Comment by mykola-mokhnach** [comment]
What is android version? If 6.0+ then switch automationName to uiatomator2

**Comment by Codude** [comment]
6.0.1

**Comment by Codude** [comment]
sendKeys working now but i get error for click() see attached screenshot
![screen shot 2018-02-15 at 11 57 38 am](https://user-images.githubusercontent.com/36496990/36243429-7f3dc6c0-1247-11e8-91da-0fd8d1c6e9ed.png)

**Comment by trix0** [comment]
are you sure that you are pointing on correct element ?

**Comment by Codude** [comment]
yeah. I just used the appium inspector to do it.

**Comment by mykola-mokhnach** [comment]
This looks more like some internal UIA2 issue. I'd rather trigger a report to Google.
