### ISSUE TITLE
Appium hangs for a very long time during tests for one app on Samsung Galaxy S8 (Sauce Labs RDC)

### ISSUE THREAD

**Issue by tOkeshu** [appium/appium#10203]
## The problem

Some requests fail when testing a specific app on Samsung Galaxy S8, on Sauce Labs RDC, with the following error:
```Cause: io.appium.java_client.NoSuchContextException: The request '/context' took longer than 90000 ms and the appium session was closed.```

According to RDC's devs, this timeout is there to avoid Appium from hanging forever, the initial symptom should be a request hanging forever.

The testing code is trying to switch context or to retrieve elements via XPath (for instance with ```driver.findElementByXPath("/")```).

## Environment

* Appium version that exhibits the issue: 1.7.1 and 1.7.2
* Desktop OS/version used to run Appium: Sauce Labs RDC (Linux/OSX)
* Mobile platform/version under test: Samsung Galaxy S8, Android 7.0+
* Real device or emulator/simulator: Real device

## Details

* The issue occurs on android versions 7+ (happens on Android 8.x as well) for both Appium 1.7.1/1.7.2.
* This issue is happening on the native app context and fails to find any native element in that context (with XPath for instance)
* A workaround was found. It consists of sending the app to the background and then returning back a few seconds later seems to solve the issue, but we're not sure why that's the case.

## Link to Appium logs

- Appium logs (1.7.2) https://gist.github.com/tOkeshu/8f3ceef9083c4cbc8e63807d1e3faaac#file-testobject_appium_samsung_galaxy_s8_real_15-02-2018_03-20-38-txt
- Appium logs (1.7.1) https://gist.github.com/tOkeshu/8f3ceef9083c4cbc8e63807d1e3faaac#file-testobject_appium_samsung_galaxy_s8_real_15-02-2018_03-22-16-txt

## Code To Reproduce Issue

- Code used to reproduce the issue https://gist.github.com/tOkeshu/8f3ceef9083c4cbc8e63807d1e3faaac#file-s8timeouttest-java

**Comment by mykola-mokhnach** [comment]
Google says such error is usually shown if chromedriver version does not match to the webview version: https://stackoverflow.com/questions/21001652/chrome-driver-error-using-selenium-unable-to-discover-open-pages

**Comment by Hassan-Radi** [comment]
@mykola-mokhnach Thanks for the stackoverflow link, but this is not using an outdated ChromeDriver version, it is using latest stable Appium version 1.7.2. 

Can you please let me or @tOkeshu know if you need extra information?

**Comment by mykola-mokhnach** [comment]
"latest" does not mean that it matches. You need the version, which is compatible to your webview

**Comment by Hassan-Radi** [comment]
@tOkeshu Can you please provide more context here? Are you using an older ChromeDriver version in your internal cloud?

**Comment by tOkeshu** [comment]
@Hassan-Radi According to the Appium logs linked to this issue, the ChromeDriver version used was `2.33.506092`.

@mykola-mokhnach I'm a bit confused, the stackoverflow link you provided doesn't seem to have the same symptoms as the one described in this issue. Am I missing something?

**Comment by Hassan-Radi** [comment]
@mykola-mokhnach Can you please re-open this ticket as it is not resolved and we (@tOkeshu and myself) can supply any more info that you request.

**Comment by hansjoergkeser** [comment]
Hi there, 
I experience the same problem. 
In the appium 1.7.2 log of @tOkeshu in line 232 it says
Original error: unknown error: unable to discover open pages

(The error "The request '/context' took longer than 90000 ms and the appium session was closed." 
is the subsequent error as the context switching command can not be executed/finished in time)

In the same log you can see the used Chromedriver version: '2.33.506092' of appium
and the device's Webview version: 'Chrome/64.0.3282.137'
Hence the hint from @mykola-mokhnach about a mismatch is reasonable.
According to these notes:
http://chromedriver.storage.googleapis.com/2.38/notes.txt
Chromedriver 2.33 supports Chrome v60-62
but not chrome 64

So I tried to execute a test with suitable driver and chrome versions, but still get the same error:
https://gist.github.com/hansjoergkeser/a5848f85588db0583af1bff86b9ce32d
In the last lines you see
chromedriver=2.38.552518
Webview version: 'Chrome/66.0.3359.126'

**Comment by dpgraham** [comment]
@imurchie you did some work on this recently, right?

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
