### ISSUE TITLE
Unable to lockDevice() iOS device

### ISSUE THREAD

**Issue by ChethanGKC** [appium/appium#10216]
## The problem

Can any one please let me know how can i lock my iPhone 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Desktop OS/version used to run Appium: 10.12.6
* Node.js version (unless using Appium.app|exe): v6.11.4
* Mobile platform/version under test: iOS 10.3.3
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

## Details
I need to lock the device.

## Link to Appium logs

https://gist.github.com/ChethanGKC/ff49bfe4fff011dab5ee9de91dfb1bd4

## Code To Reproduce Issue [ Good To Have ]

Please find the below code : 
package com.chethan.demo.auto;

import io.appium.java_client.AppiumDriver;
import io.appium.java_client.ios.IOSDriver;
import io.appium.java_client.remote.MobileCapabilityType;

import java.net.MalformedURLException;
import java.net.URL;
import java.time.Duration;

import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.Assert;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

public class iosAppLaunch {
	AppiumDriver driver;

	@BeforeClass
	public void Setup() throws MalformedURLException {

		// set up appium against a local application
		DesiredCapabilities capabilities = new DesiredCapabilities();
		
		capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");
		capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 300);
		capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Samsung");
		capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
		capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.3.3");
		capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "");
		capabilities.setCapability(MobileCapabilityType.APP, "/Users/pramati/Desktop/firstconnect.ipa" );
		capabilities.setCapability("bundleId", "XXXXXXXXXXXXXXX");
		capabilities.setCapability(MobileCapabilityType.UDID, "XXXXXXXXXXXXXXXXXXX");
		capabilities.setCapability(MobileCapabilityType.FULL_RESET, true);
		capabilities.setCapability("shouldUseSingletonTestManager", false);
		capabilities.setCapability("startIWDP", true);
		capabilities.setCapability("useNewWDA", true);
		capabilities.setCapability("maxTypingFrequency", 10);
		capabilities.setCapability("connectHardwareKeyboard", false);
		capabilities.setCapability("sendKeyStrategy", "oneByOne");
		
		driver = new IOSDriver(new URL("http://localhost:4723/wd/hub"),
				capabilities);

	}

	@Test
	public void SimpleTest() {
		
		Assert.assertNotNull(driver.getContext());
		
		Duration oneHours = Duration.ofHours(1);
		
		((IOSDriver)driver).lockDevice(oneHours);
//		((Object) driver).unlockDevice(1);
	}

}

**Comment by mykola-mokhnach** [comment]
This functionality is only available in the recent appium@beta

**Comment by ChethanGKC** [comment]
Thanks @mykola-mokhnach i will try this
