### ISSUE TITLE
Reinitialize Browser with last cache and cookies. Also Same for Android App using appium

### ISSUE THREAD

**Issue by sagarsheth27** [appium/appium#10214]
Hi Guys

**My scenario for chrome browser is:**
I want to open chrome browser in offline mode. Also want to maintain last cookies and cache remain same. 
Do not open new app via selenium. I want same app to reopen by selenium without clearing cache and cookies.

**Scenario for android app is:**
Whenever app stared by appium. Every cache and data cleared through appium for that app. I don't want it. I want that to remain same for every time.

One more thing for android is that, run time close phone's internet and want to cross check app in offline mode. But at that time i want to use all old cache and data of that app. Do not clear it.

**These both things, i want in android's app also in chrome browser by selenium.**

**Comment by trix0** [comment]
Maybe this is what you are looking for https://appium.io/docs/en/writing-running-appium/other/reset-strategies/index.html
