### ISSUE TITLE
Capture Network logs (event) in case of IOS  browser/webview

### ISSUE THREAD

**Issue by narendra90s** [appium/appium#10217]
## The problem

Appium have added capability for enablePerformanceLogging for IOS browser and webview. When enablePerformanceLogging  is enabled it collects Timeline events while in case of android it collects Network event also. Network events helps in measuring the performance of a web application. Appium should also capture Network logs when enablePerformanceLogging  is enabled in case of IOS. 

## Environment

* Appium Desktop 1.3.2
* IOS - Safari (11.0)/webview

**Comment by mykola-mokhnach** [comment]
@imurchie I assume this issue has been addressed in the recent beta

**Comment by imurchie** [comment]
Yes. Safari network logs available now as `safariNetwork` log type.
