### ISSUE TITLE
Progress bar is moved 50% irrespective of the progressBar.setValue() param

### ISSUE THREAD

**Issue by shridharkalagi** [appium/appium#10211]
## The problem
Progress bar is moved 50% irrespective of the progressBar.setValue() param

Below is the adb command which I see in Appium Server logs
["-P",5037,"-s","FA66VBN01980","shell","ps"]

## Environment

* Appium version - 1.7.2-beta5
* Desktop OS/version used to run Appium: macOS 10.12.6 
* Node.js version: v6.12.2
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

## Code To Reproduce Issue [ Good To Have ]

MobileElement slider = (MobileElement) driver.findElementByAccessibilityId("slider");
slider.setValue("20");

**Comment by mykola-mokhnach** [comment]
I cannot help without full server log

**Comment by shridharkalagi** [comment]
@mykola-mokhnach Server logs [here](https://gist.github.com/shridharkalagi/4a5c094cd004ea95ed0c45f1f76e372b)

Though I did slider.setValue("20"), slider was moved by 50%.

**Comment by mykola-mokhnach** [comment]
Switch to UIAutomator2

**Comment by shridharkalagi** [comment]
@mykola-mokhnach UIAutomator2 logs [here](https://gist.github.com/shridharkalagi/ac7fb48657971c8b56941737361976a6.js) also adb logcat  logs [here](https://gist.github.com/shridharkalagi/4867ea66527154a8a579bd38a950d778)

**Comment by mykola-mokhnach** [comment]
Sorry, I cannot read the GIST

**Comment by shridharkalagi** [comment]
@mykola-mokhnach updated the link. Can you check?

**Comment by mykola-mokhnach** [comment]
This looks like a problem with the client. It calls `setValueImmediate` endpoint instead of `setValue`. Are you sure your java client is up to date?

**Comment by mykola-mokhnach** [comment]
I'll add a workaround to the driver though to avoid unnecessary confusion

**Comment by shridharkalagi** [comment]
This issue is on latest Java-client(6.0.0-BETA3) as well

**Comment by mykola-mokhnach** [comment]
There is this condition in code:

```
        /*
         * Execute ACTION_SET_PROGRESS action (introduced in API level 24)
         * if element has range info and text can be converted to float.
         * Falling back to element.setText() if something goes wrong.
         */
        if (nodeInfo.getRangeInfo() != null && Build.VERSION.SDK_INT >= 24) {
```

Does your application under test satisfy it?

**Comment by shridharkalagi** [comment]
@mykola-mokhnach thanks for the info. It's working on Android 7.0
However, the slider doesn't move 100% if I say .setValue("100") Am I missing anything here?

**Comment by mykola-mokhnach** [comment]
it is probably calculating from 0 to 99. Closing as fixed
