### ISSUE TITLE
Appium Freezes after executing some steps, recontinues after making intervention  by tapping on the device.

### ISSUE THREAD

**Issue by Rakeshsp05** [appium/appium#10212]
## The problem

While Automating an app, After some time the appium freezes. It doesn't give any error. If we make a small intervention by tapping on a device the scripts continue to execute. The scripts execute successfully on some devices and on some devices it freezes. The Freeze continues for a long period of time like 

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.7.2

* Mobile platform/version under test: Android 7.1.1 
* Real device or emulator/simulator: Real Device Nexus 6 , one plus 3T Android 8.
* Appium CLI or Appium.app|exe:

## Details

The behavior observed is inconsistent. 

## Link to Appium logs

<script src="https://gist.github.com/Rakeshsp05/a642f88d73dc4bf0e8b5ee34fd201d8f.js"></script>

**Comment by mykola-mokhnach** [comment]
Switch to UIAutomator2

**Comment by Rakeshsp05** [comment]
after switching uiAutomator2, still observing the issue kindly find the logs

<script src="https://gist.github.com/Rakeshsp05/5fbee0d154e75b51267b1d40369144ed.js"></script>
