### ISSUE TITLE
Can't open any app with appium

### ISSUE THREAD

**Issue by antonusername** [appium/appium#10226]
## The problem

Can't open any app with appium I've tried with different android simulators, also with real devices but without success.

My desired capabilities
 DesiredCapabilities cap = new DesiredCapabilities();
        cap.setCapability("automationName", "UiAutomator2");
        cap.setCapability("platformName","Android");
        cap.setCapability("platformVersion","8.0");
        cap.setCapability("deviceName","emulator-5554");
        cap.setCapability("autoGrantPermissions","true");
        cap.setCapability("appPackage","com.viber.voip");
        cap.setCapability("appActivity",".SplashActivity");
        WebDriver driver = new RemoteWebDriver(new URL("http://127.0.0.1:4723/wd/hub"),cap);

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error occured while starting App. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\Satellite\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 shell am start -W -n com.viber.voip/.SplashActivity -S' exited with code 4294967295'; Stderr: 'Security exception: Permission Denial: starting Intent { flg=0x10000000 cmp=com.viber.voip/.SplashActivity } from null (pid=29153, uid=2000) not exported from uid 10088

Log from appium

Appium v1.7.2

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:
* Desktop OS/version used to run Appium : Windows 8.1:
* Node.js version v9.3.0:
* Mobile platform/version under test Android 8.0:
* Real device or emulator/simulator emulator Nexus 5x API26:
java.version: '1.8.0_121'
Appium v1.7.2

## Link to Appium logs
**https://gist.github.com/antonusername/d350feea37cf7c7c18f8fb9a51bdf255**

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
This means that you provide incorrect activity name/waitActivityName in capabilities. Closed as duplicate.
