### ISSUE TITLE
Incorrect Y position for Share action sheet icons or Widget icons from Todays View.

### ISSUE THREAD

**Issue by gattasrikanth** [appium/appium#10221]
## The problem

When am trying to get tap on the elements from iOS Share action sheet or Todays View widgets, the element Y position is always incorrect. So not able to tap on the element where I wanted to.

## Environment

* Appium v1.8.0-beta3 ( But I guess same issue in 1.7.2 as well)
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac High Sierra 10.13.3
* Real device or emulator/simulator: iPhone8 real device iOS11.2.5

## Details

Let me know if you need more details

## Link to Video 

https://drive.google.com/file/d/1TbXVLipisL6oxe9zrI1PXvGcWzEiwCzc/view?usp=sharing

(This is my first reporting an issue, so let me know if am missing any required details)

**Comment by mykola-mokhnach** [comment]
This is known XCTest issue. Please report to Apple.

**Comment by lindsaysan** [comment]
If this is a known XCUITest issue can you please link to the rdar?
