### ISSUE TITLE
How to identify and click on object (X) displayed with EditText field using appium

### ISSUE THREAD

**Issue by SonalDalal** [appium/appium#10222]
## The problem

In my app I have a EditText field with X icon at the end. when I manually click on X it removes the field. I want to handle this using my appium script but I didn't find object identification property for X using uiautomatorviewer. Can anyone help?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable): none
* Desktop OS/version used to run Appium: Ubuntu 14.04 lts
* Node.js version (unless using Appium.app|exe): 8.3.0
* Mobile platform/version under test: Device info: Redmi Note 4, Android Version: 7.0
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Details
image of the same is displayed below
![screenshot from 2018-02-20 16 30 17](https://user-images.githubusercontent.com/29579912/36420560-7c1bfc74-165b-11e8-8b0d-8df0bca08739.png)

**Comment by mykola-mokhnach** [comment]
If you don't see this button in the DOM tree then the app under test itself does not expose it to accessibility manager. Either check it with developers or perform click by coordinates.

**Comment by SonalDalal** [comment]
I have added below script but it's not working

TouchAction a2 = new TouchAction(driver);
a2.tap(objJC.CustomerVerbatimTextField(driver).get(0), 748, 252).perform();

also tried as below

TouchAction a2 = new TouchAction(driver);
a2.tap(748, 252).perform();

**Comment by mykola-mokhnach** [comment]
Of course it does not, because you are not clicking the area where X button is located. One has to calculate its location manually based on the relative offset from its container edit control.

**Comment by SonalDalal** [comment]
Resolved. got location using getLocation() and then clicked on object.

int upperY = element.getLocation().getY();
int lowerY = upperY + element.getSize().getHeight();
int middleY = (upperY + lowerY) / 2;
