### ISSUE TITLE
How to retrieve data from multiple sheets using one data provider?

### ISSUE THREAD

**Issue by sagarsheth27** [appium/appium#10228]
**Here my code is:**
@DataProvider(name="TC")
	public static Object [][] TestCase() throws Exception
	{
		File filepath = new File(System.getProperty("user.dir")+"\\src\\main\\resources\\ExcelFiles\\Dataprovider.xls");
		Workbook wb= Workbook.getWorkbook(filepath);
		Sheet sheet = wb.getSheet("TestCase");
		Sheet sheet1=wb.getSheet("data");
		int row1= sheet1.getRows();
		int column1 = sheet1.getColumns();
		//String Inputdata1[][] = new String[row1-1][column1];
		int count1=0;
		int row= sheet.getRows();
		int column = sheet.getColumns();
		String Inputdata[][] = new String[row-1][column];
		String Inputdata1[][] = new String[row1-1][column1];
		int count =0;
		for (int i=1;i<row;i++)
		{
			for (int j=0;j<column;j++)
			{			Cell cell = sheet.getCell(j,i);
				Inputdata[count][j]=cell.getContents();
				System.out.println(""+Inputdata[count][j]);
			}
			
			count++;
			for (int k=1;i<row1;k++)
			{
				for (int j=0;j<column1;j++)
				{			Cell cell1 = sheet1.getCell(j,k);
				Inputdata1[count1][j]=cell1.getContents();
				System.out.println(""+Inputdata1[count1][j]);
				}
				count++;
			
			}
		}

	return (Object[][]) new Object[][]{Inputdata, Inputdata1};
}
}

**Comment by saikrishna321** [comment]
Please raise question [here](discuss.appium.io).
