### ISSUE TITLE
Working with REMenuItems

### ISSUE THREAD

**Issue by guruprasadsr** [appium/appium#10232]
The app which I am automating using Appium uses REMenuItem (https://github.com/romaonthego/REMenu). In the app they use this 3rd party library to create a dropdown menu item. I am unable to access the items present in the dropdown menu. In the dropdown menu, there is an image behind which there is a badge. which I want to access. This is not possible as the REMenuItem is not getting displayed in the page source. Please help.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Desktop OS/version used to run Appium: Mac OS/X 10.13.1
* Node.js version (unless using Appium.app|exe): 8.5.0
* Mobile platform/version under test: iOS V 11.0
* Real device or emulator/simulator: Physical device

**Comment by mykola-mokhnach** [comment]
Try appium@beta

**Comment by guruprasadsr** [comment]
Hi Mykola,

I installed Appium beta and tried to inspect the element. It was not helpful. Please find details below.

1) I used the Accessibility Inspector tool of XCODE to spy on the elements. It was also not helpful.
2) I enabled the accessibility on the physical device (Done by going to Settings -> General -> Accessibility -> VoiceOver -> Tap the switch control to turn on VoiceOver). This will help in identifying the different elements that are accessible to the UI. There as well, I saw that only the buttons are getting identified.

Still the REMenuItem is not part of the page source. Only the buttons are part of the page source.

**Comment by mykola-mokhnach** [comment]
This means that the component is not advertised to accessibility manager at all and you'll not able to see it with Appium. Closed as not an issue.
