### ISSUE TITLE
reserved word arguments in vargs module

### ISSUE THREAD

**Issue by jnrepo** [appium/appium#10237]
## The problem

Hi, I'm trying to get appium to work with my react-native application. I'm running into an issue where running the test itself runs into a reserved word issue with one of the modules being used. Specfically `vargs`. Looking at their issues, it seems it was brought up and a PR was made a while back https://github.com/cloudhead/vargs/pull/6 

Wondering if there is a workaround for this issue.

## Environment

Appium: 1.7.2
Macbook Pro High Sierra
Node: 9.4.0
Mobile Platform: Android
Android Simulator

## Details

I've run appium-doctor and fixed all the issues related to android.

## Link to Appium logs

```
FAIL  test/appium/appium.test.js
 ● Test suite failed to run

   /Users/me/projects/test123/node_modules/vargs/lib/vargs.js: arguments is a reserved word in strict mode (24:37)
       22 | //   }
       23 | //
     > 24 | exports.Constructor = function Vargs(arguments) {
          |                                      ^
       25 |     this.array = Array.prototype.slice.call(arguments);
       26 |     this.__defineGetter__('length', function () {
       27 |         if (this.callbackGiven()) {
```

**Comment by jnrepo** [comment]
this doesn't belong here, sorry

**Comment by igorrfc** [comment]
Did you solve it @jnrepo? If don't can you point me to the issue where this is being discussed?

**Comment by jnrepo** [comment]
@igorrfc there is a PR for this issue in the github for the `vargs` module here https://github.com/cloudhead/vargs/pull/6

A temporary solution I found was just changing the parameter `arguments` to `args` in the `node_modules/vargs/lib/vargs.js` and it worked. The annoying part is that you have to do this everytime you do `rm -rf node_modules`.
