### ISSUE TITLE
Screenshots with xcode 9.2 are no longer high enough quality for testing

### ISSUE THREAD

**Issue by rbadavestewart** [appium/appium#10236]
## The problem

I have built tests that compare a current screenshot with an expected screenshot. Until recently, these tests worked fine. Recently I upgraded to the 1.3.2 mac desktop app and xcode 9.2, and these tests started consistently failing.

The problem appears to be the quality / compression level in the screenshots.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): 1.7.1, however, I don't think this is relevant.
* Desktop OS/version used to run Appium: macOS 10.13.3
* Node.js version (unless using Appium.app|exe): Using Appium.app
* Mobile platform/version under test: ios 10.3.2
* Real device or emulator/simulator: Real device, iPhone 6s
* Appium CLI or Appium.app|exe: Appium.app

## Details

The screenshots I'm getting since I upgraded to xCode 9.2 are slightly different than they used to be. They appear to be at a lower quality or higher compression than previously, except they are also larger file sizes, which doesn't make a whole lot of sense. Also, they used to come with an alpha channel and now do not. I'll try to attach an example of each.

This is an image captured using old xcode:
![04_onboarding_iphone_750x1334_expect](https://user-images.githubusercontent.com/19615041/36511862-383f6c6c-171d-11e8-8a9d-840f10147d70.png)

And this is an image captured with xcode 9.2:
![04_onboarding_iphone_750x1334_actual](https://user-images.githubusercontent.com/19615041/36511869-3ed2d6e0-171d-11e8-8146-4d3957e2b164.png)

This is a comparison of the two images, with differences highlighted in red:
![04_onboarding_iphone_750x1334_diff](https://user-images.githubusercontent.com/19615041/36511899-67126a9e-171d-11e8-8fb9-67ee210c6271.png)

I suspect this is something to do with how we are calling screenshots from XCUItest, and possibly some default quality setting has changed on the xCode side.

## Link to Appium logs

If it will help, I'll certainly put up a log, just let me know.

## Code To Reproduce Issue [ Good To Have ]

I'm using ruby and calling screencaptures using:

driver.save_screenshot(actual_0)

**Comment by saikrishna321** [comment]
FYI, Sometime two exactly same images have minor difference. Pixel by Pixel comparison of such images will fail. In simple terms, by setting fuzz factor, you can ignore minor differences.. 

https://image.slidesharecdn.com/nakalthinktest2015-151208073849-lva1-app6891/95/nakal-think-test2015-19-638.jpg?cb=1449560411

Closing as non-appium issue.

**Comment by rbadavestewart** [comment]
I am already using a fuzz factor - that's how I've made these tests pass for the last two years.

compare -metric AE -fuzz 10%

I guess I can try increasing the fuzz. Or try my hand at convincing Apple to change the default settings back to what they were before xCode 9.2.

**Comment by mykola-mokhnach** [comment]
Before Xcode9 screenshots were taken in lossless PNG format, but now we must change that to lossy JPEG because of Apple bug, which made the test to crash in a hard way due to OutOfMemory error. It looks like it just does not have enough system memory to keep such screenshots. Send all complains to Apple please.

**Comment by rbadavestewart** [comment]
Thanks guys. I'll bother Apple, see what I can get out of them.

**Comment by rbadavestewart** [comment]
Thanks guys. I'll bother Apple, see what I can get out of them.

In case someone else runs into this and needs a hack... I changed my fuzz factor from 10% to 23% and I'm getting reasonably reliable pass rates again.

compare -metric AE -fuzz 23%
