### ISSUE TITLE
mobile:scroll event not working on android 

### ISSUE THREAD

**Issue by UtsavSaha** [appium/appium#10238]
## The problem

mobile:swipe event not working on android but working on iOS as expected.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2. 
* Desktop OS/version used to run Appium: Mac 10.13.3 (Mac OS High Sierra)
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Real Device (Samsung edge). 

Actual Error from appium Server : 
 Selenium error: Unknown mobile command "swipe". Only shell commands are supported.

**Comment by mykola-mokhnach** [comment]
Where it is mentioned it is supposed to work on Android?

**Comment by UtsavSaha** [comment]
is there any similar API/Eventing mechanism for android to achieve the same?

**Comment by mykola-mokhnach** [comment]
only TouchAction
