### ISSUE TITLE
Appium Desktop screen not synchronized with emulator screen

### ISSUE THREAD

**Issue by xiexu2008** [appium/appium#10235]
## The problem

I was trying to automate a 3rd-party app on an Android emulator. When launching the app on Appium Desktop by clicking the “Start Session” button, the Appium Desktop was getting stuck on the app's welcome screen, even though the related emulator correctly navigated to the main activity screen.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10 Enterprise
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android API 27 x86
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Link to Appium Logs: https://gist.github.com/xiexu2008/505fba0665a38198ac639f60e0c9ca6a

## Code To Reproduce Issue [ Good To Have ]

Below were the capabilities used in Appium Desktop:
{
“deviceName”: “Nexus 9 API 27”,
“platformName”: “Android”,
“app”: “ClinipadSoei_20180212.apk”
}

Link to the apk of the app: https://www.dropbox.com/s/7apnhk0d3141ko2/ClinipadSoei_20180212.zip?dl=0

**Comment by mykola-mokhnach** [comment]
Use uiatomation2 backend for Android 6+
