### ISSUE TITLE
There is no documented method to get text value from web element in JavaScript using WD

### ISSUE THREAD

**Issue by markring** [appium/appium#10233]
## The problem
Documentation provides the below as the method to get text via WD, I think there may have been a copy/paste error? What is the method used to retrieve text in native and web contexts?

// wd example
let element = await driver.elementByAccessibilityId("SomeAccessibilityID");
**await element.submit();**
[Appium Docs](https://appium.io/docs/en/commands/element/attributes/text/#json-parameters)

**Comment by dpgraham** [comment]
It should be `await element.text()`

Thanks for reporting this, I'll put in a fix for that.

**Comment by markring** [comment]
Thank You!
