### ISSUE TITLE
Can't unlock device with patter/pin when automationName is NOT Default ("Appium")

### ISSUE THREAD

**Issue by shynkevich-alex** [appium/appium#10240]
## The problem

I want to unlock android device with pattern but error occurred when pattern screen opens.

## Environment

* Appium 1.7.2
* Desktop/ Java client
* Android
* Real device Samsung galaxy A5 (7.0)

## Details

```
{
  "platformVersion": "7.0",
  "platformName": "Android",
  "noReset": true,
  "udid": "52001acbecea64a9",
  "app": "/Users/shynkevichaliaksandr/automation/my_project/application/app.apk",
  "deviceName": "Galaxy A5 (2017)",
  "unlockType": "pattern",
  "unlockKey": "12369",
  "appActivity": ".MainActivity",
  "automationName": "UiAutomator2"
}
```

It works well with default automationName "Appium", but with default value I must use command "adb shell input keyevent 224" before create driver or it will be failed.

Unfortunately I must use UiAutomator2 because runAppInBackground works bad with automationName "Appium" on Android >7.0 devices.

## Link to Appium logs
https://gist.github.com/shynkevich-alex/1fda5ebcae2a663cb72cdebad42b38d1

**Comment by mykola-mokhnach** [comment]
Try if it works in the recent appium@beta

**Comment by shynkevich-alex** [comment]
@mykola-mokhnach I have tried on 1.8.0-beta 3

So I see appium at lease touches first pin but then failes.

> [MJSONWP] Encountered internal error running command: Error: Screen did not unlock successfully, retrying
>     at Object.callee$1$0$ (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/android-helpers.js:464:13)
>     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
>     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
>     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
>     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
>     at <anonymous>

**Comment by mykola-mokhnach** [comment]
@vrunoa FYI

**Comment by shynkevich-alex** [comment]
@vrunoa Also add please wake up logic (shell input keyevent 224) before unlock. Because without this command it just fails

**Comment by mykola-mokhnach** [comment]
@shynkevich-alex You could try to fix it yourself. Here is the source: https://github.com/appium/appium-android-driver/blob/6ebdc8df157f704fa50124849597c89f1439e608/lib/android-helpers.js#L444

and here is the contributor guideline:

https://github.com/appium/appium/blob/master/CONTRIBUTING.md

**Comment by CoryWritesCode** [comment]
@vrunoa Is there any timeline on a fix for this bad boy? 😄

**Comment by CoryWritesCode** [comment]
Thank you!!

**Comment by IgalKorb** [comment]
@vrunoa tried to work with pattern unlock on v1.10.0 (macOS, client python) and looks like it doesn't use the relative location for each move_to call, so it does the right action but not in the right location:
pattern 14589
suppose - 360,1276 > 360,1636 > 720,1636 > 720,1996 > 1080,1996
acctual - 360,1276 > 0,360 > 360,0 > 0,360 > 360,0
i think it's more related to #11915 but it's closed already so i comment here. please advice :)
logs:
`[AndroidDriver]` Screen is locked, trying to unlock
[AndroidDriver] Trying to unlock device using pattern 14589
[ADB] Running '/usr/local/share/android-sdk/platform-tools/adb -P 5037 -s LGH930c72cd56e shell dumpsys input_method'
[AndroidDriver] Dismiss notifications from unlock view
[ADB] Running '/usr/local/share/android-sdk/platform-tools/adb -P 5037 -s LGH930c72cd56e shell service call notification 1'
[ADB] Pressing the BACK button
[ADB] Running '/usr/local/share/android-sdk/platform-tools/adb -P 5037 -s LGH930c72cd56e shell input keyevent 4'
[ADB] Device API level: 26
[AndroidDriver] Trying to dismiss keyguard
[ADB] Running '/usr/local/share/android-sdk/platform-tools/adb -P 5037 -s LGH930c72cd56e shell wm dismiss-keyguard'
[ADB] Device API level: 26
[BaseDriver] Waiting up to 0 ms for condition
[JSONWP Proxy] Matched '/element' to command name 'findElement'
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8202/wd/hub/session/61885fbf-d86e-410d-acc1-46550484ab55/element] with body: {"strategy":"id","selector":"com.android.systemui:id/lockPatternView","context":"","multiple":false}
[JSONWP Proxy] Got response with status 200: {"sessionId":"61885fbf-d86e-410d-acc1-46550484ab55","status":0,"value":{"ELEMENT":"4ee59067-16fb-4632-bf58-8ec321e76fc3"}}
[UiAutomator2] calling get location: 4ee59067-16fb-4632-bf58-8ec321e76fc3
[JSONWP Proxy] Matched '/element/4ee59067-16fb-4632-bf58-8ec321e76fc3/location' to command name 'getLocation'
[JSONWP Proxy] Proxying [GET /element/4ee59067-16fb-4632-bf58-8ec321e76fc3/location] to [GET http://localhost:8202/wd/hub/session/61885fbf-d86e-410d-acc1-46550484ab55/element/4ee59067-16fb-4632-bf58-8ec321e76fc3/location] with body: {}
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"61885fbf-d86e-410d-acc1-46550484ab55\",\"status\":0,\"value\":{\"x\":180,\"y\":1096}}"
[JSONWP Proxy] Matched '/element/4ee59067-16fb-4632-bf58-8ec321e76fc3/size' to command name 'getSize'
[JSONWP Proxy] Proxying [GET /element/4ee59067-16fb-4632-bf58-8ec321e76fc3/size] to [GET http://localhost:8202/wd/hub/session/61885fbf-d86e-410d-acc1-46550484ab55/element/4ee59067-16fb-4632-bf58-8ec321e76fc3/size] with body: {}
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"61885fbf-d86e-410d-acc1-46550484ab55\",\"status\":0,\"value\":{\"width\":1080,\"height\":1080}}"
[JSONWP Proxy] Matched '/touch/down' to command name 'touchDown'
[JSONWP Proxy] Proxying [POST /touch/down] to [POST http://localhost:8202/wd/hub/session/61885fbf-d86e-410d-acc1-46550484ab55/touch/down] with body: {"params":{"element":null,"x":360,"y":1276}}
[JSONWP Proxy] Got response with status 200: {"sessionId":"61885fbf-d86e-410d-acc1-46550484ab55","status":0,"value":true}
[JSONWP Proxy] Matched '/touch/move' to command name 'touchMove'
[JSONWP Proxy] Proxying [POST /touch/move] to [POST http://localhost:8202/wd/hub/session/61885fbf-d86e-410d-acc1-46550484ab55/touch/move] with body: {"params":{"element":null,"x":0,"y":360}}
[JSONWP Proxy] Got response with status 200: {"sessionId":"61885fbf-d86e-410d-acc1-46550484ab55","status":0,"value":true}
[JSONWP Proxy] Matched '/touch/move' to command name 'touchMove'
[JSONWP Proxy] Proxying [POST /touch/move] to [POST http://localhost:8202/wd/hub/session/61885fbf-d86e-410d-acc1-46550484ab55/touch/move] with body: {"params":{"element":null,"x":360,"y":0}}
[JSONWP Proxy] Got response with status 200: {"sessionId":"61885fbf-d86e-410d-acc1-46550484ab55","status":0,"value":true}
[JSONWP Proxy] Matched '/touch/move' to command name 'touchMove'
[JSONWP Proxy] Proxying [POST /touch/move] to [POST http://localhost:8202/wd/hub/session/61885fbf-d86e-410d-acc1-46550484ab55/touch/move] with body: {"params":{"element":null,"x":0,"y":360}}
[JSONWP Proxy] Got response with status 200: {"sessionId":"61885fbf-d86e-410d-acc1-46550484ab55","status":0,"value":true}
[JSONWP Proxy] Matched '/touch/move' to command name 'touchMove'
[JSONWP Proxy] Proxying [POST /touch/move] to [POST http://localhost:8202/wd/hub/session/61885fbf-d86e-410d-acc1-46550484ab55/touch/move] with body: {"params":{"element":null,"x":360,"y":0}}
[JSONWP Proxy] Got response with status 200: {"sessionId":"61885fbf-d86e-410d-acc1-46550484ab55","status":0,"value":true}
[JSONWP Proxy] Matched '/touch/up' to command name 'touchUp'
[JSONWP Proxy] Proxying [POST /touch/up] to [POST http://localhost:8202/wd/hub/session/61885fbf-d86e-410d-acc1-46550484ab55/touch/up] with body: {"params":{"x":360,"y":0}}
[JSONWP Proxy] Got response with status 200: {"sessionId":"61885fbf-d86e-410d-acc1-46550484ab55","status":0,"value":true}
[ADB] Running '/usr/local/share/android-sdk/platform-tools/adb -P 5037 -s LGH930c72cd56e shell dumpsys window'
[ADB] Running '/usr/local/share/android-sdk/platform-tools/adb -P 5037 -s LGH930c72cd56e shell dumpsys window'
[UiAutomator2] Deleting UiAutomator2 session
[UiAutomator2] Deleting UiAutomator2 server session
[JSONWP Proxy] Matched '/' to command name 'deleteSession'
[JSONWP Proxy] Proxying [DELETE /] to [DELETE http://localhost:8202/wd/hub/session/61885fbf-d86e-410d-acc1-46550484ab55] with no body
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"61885fbf-d86e-410d-acc1-46550484ab55\",\"status\":0,\"value\":\"Session deleted\"}"
[ADB] Running '/usr/local/share/android-sdk/platform-tools/adb -P 5037 -s LGH930c72cd56e shell am force-stop sdk.infi.com.demoapplication'
[Logcat] Stopping logcat capture
[ADB] Removing forwarded port socket connection: 8202 
[ADB] Running '/usr/local/share/android-sdk/platform-tools/adb -P 5037 -s LGH930c72cd56e forward --remove tcp\:8202'
[ADB] Device API level: 26
[BaseDriver] Event 'newSessionStarted' logged at 1547643052964 (14:50:52 GMT+0200 (IST))
[W3C] Encountered internal error running command: Error: Screen did not unlock successfully, retrying
[W3C]     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium-android-driver/lib/android-helpers.js:624:13
[W3C]     at process._tickCallback (internal/process/next_tick.js:68:7)
[HTTP] <-- POST /wd/hub/session 500 28562 ms - 678
[HTTP] 
[UiAutomator2] [UIAutomator2] io.appium.uiautomator2.server.test.AppiumUiAutomator2Server:.
[UiAutomator2] [UIAutomator2] Time: 12.092
[UiAutomator2] [UIAutomator2] OK (1 test)`

**Comment by IgalKorb** [comment]
@vrunoa @mykola-mokhnach 
pushed a small fix, not sure it's 'clear', more like a patch but works for me, please review and push/offer your fix

https://github.com/appium/appium-android-driver/pull/489

Thanks!

**Comment by KazuCocoa** [comment]
It looks some fixes have been applied
