### ISSUE TITLE
Unable to install apk with appium 1.3.2 with UIAutomator2 capability

### ISSUE THREAD

**Issue by mjevtovic** [appium/appium#10248]
## The problem

I am not able to install apk using appium 1.3.2. Error says installApkRemotely is not a function

## Environment

* Appium version 1.3.2
* Last Appium version that did not exhibit the issue (if applicable): 1.3.1
* Desktop OS/version used to run Appium: macOS Sierra 10.12.1
* Node.js version (unless using Appium.app|exe): using Appium.app
* Mobile platform/version under test: android-22
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Appium.app

## Details

Here is screenshot.
![screen shot 2018-02-21 at 4 34 05 pm](https://user-images.githubusercontent.com/10105654/36591688-1865461a-1893-11e8-81b0-6a9daab4428c.png)

**Comment by trix0** [comment]
are You sure that installApkRemotely is a function ? If yes Could you please provide link to docs. Cause I use https://appium.io/docs/en/commands/device/app/install-app/ and it works

**Comment by trix0** [comment]
Ah I see I guess you a trying to install it using caps. Thats strange Could you please provide full log ?

**Comment by trix0** [comment]
#828

**Comment by mjevtovic** [comment]
Here is the log:

https://gist.github.com/mjevtovic/3a5c0e3152846184cee37ecf48b15cc2

**Comment by mjevtovic** [comment]
Ah I saw it now, I just need to use 'appPath' instead of 'app' in capabilities, but however it leads to 2nd issue https://github.com/appium/java-client/issues/828

**Comment by mykola-mokhnach** [comment]
Update the server to the recent beta version or downgrade it to 1.7.2
This is a known issue in beta snapshot
