### ISSUE TITLE
closeApp() does not work

### ISSUE THREAD

**Issue by trix0** [appium/appium#10242]
## The problem
CloseApp() does not close the app. It just sends it to background and reset it. 

Or maybe I just do not understand the meaning of this function 
PS: Can I check if app is running somehow ?
## Environment

* Appium version (or git revision) that exhibits the issue:1.8 beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:ubuntu 
* Node.js version (unless using Appium.app|exe):9.4.0
* Mobile platform/version under test:6.0.0
* Real device or emulator/simulator:real
* Appium CLI or Appium.app|exe:cli

## Link to Appium logs
[245 line Log](https://gist.github.com/trix0/61bafc6a78fa4d85b69b2d7b8766fd01)

**Comment by mykola-mokhnach** [comment]
It is the designed behaviour. closeApp literally does the same as driver.qut. The thing is that it is not so easy to terminate the instrumented app, because then the whole automation is terminated as well.

**Comment by tfcardoso** [comment]
@trix0 There is terminateApp:
https://github.com/appium/java-client/blob/6e9bee1c8ccc39e26d1f34af57ee47e55cc433e6/src/main/java/io/appium/java_client/InteractsWithApps.java#L185

That I actually still not tested. And if you want to just force stop app on Android you can run:

    adb shell am force-stop <package>

**Comment by trix0** [comment]
@tfcardoso but that would stop automation as mykola said no ? If yes thats useless anyway :)
I needed to close the app an verify that its closed. I ll talk to my boss and see if its so important after all :) thx guys
