### ISSUE TITLE
  Element is not currently interactable and may not be manipulated (status: 12)

### ISSUE THREAD

**Issue by markring** [appium/appium#10256]
## The problem
**Android Emulator**
Tests work perfectly. 
**iOS Emulator**
The test in question is verifying form validations on an ionic hybrid application. After initial form interaction on the emulator the following tests all fail as they are unable to utilize **clear()** or **sendKeys()** commands; the below error is thrown. 

Interfacing with the app manually in the emulator the form inputs are all active after responding to an input validation and I am able to submit the form a second time. 

```Error: [element.sendKeys("firstName")] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: Error while executing atom: Element is not currently inter-actable and may not be manipulated (status: 12)```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.72
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MAC OS High Sierra 10.13.3
* Node.js version (unless using Appium.app|exe): 6.10.3
* Mobile platform/version under test: iOS 10.3
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

 [Appium Log](https://gist.github.com/markring/1e04ecc1ffa9506f96596f09518d678d) 

 [Code](https://gist.github.com/markring/dc22abddf7d3724bad8a6a90231b86e2)

**Comment by markring** [comment]
Was able to get it working through the us of the retries method provided by the Mocha framework, not sure this is the most effective solution though.  
``` 
describe('XYZ SCREEN: xyz.test.js',  function() {

    this.retries(30);

    it('Should do something',  async function() {
       await test code ...
    });
});
```

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
