### ISSUE TITLE
"Method has not yet been implemented" for TouchAction on Android web views

### ISSUE THREAD

**Issue by jacobweber** [appium/appium#10252]
## The problem

Using a Cordova app, when I'm using the web view, I can't send touch start/end events.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium.app 1.3.2 with server 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Mac OS 10.13.3
* Node.js version (unless using Appium.app|exe): 8.4.0
* Mobile platform/version under test: Android 7.1.1 (or any version)
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: Appium.app
* Python Appium client

## Details

I'm trying to test a hybrid (Cordova) app that uses touchstart/touchend events in the web view.

I already dealt with the chromedriver version-compatibility [issue with Android 8.0](https://github.com/appium/appium/issues/8958), by switching to Android 7.1.1 and chromedriver 2.28. I'm happy to use any version though.

But when I run `TouchAction(driver).press(el).release().perform()`, I get "Method has not yet been implemented":
```
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    TouchAction(driver).press(el).release().perform()
  File "/path/to/python/site-packages/appium/webdriver/common/touch_action.py", line 94, in perform
    self._driver.execute(Command.TOUCH_ACTION, params)
  File "/path/to/python/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/path/to/python/site-packages/appium/webdriver/errorhandler.py", line 29, in check_response
    raise wde
selenium.common.exceptions.WebDriverException: Message: Method has not yet been implemented
```

## Link to Appium logs

https://gist.github.com/jacobweber/2328e0c2b1be18b53ea8462ba74e0201

## Code To Reproduce Issue [ Good To Have ]

[CordovaTest.zip](https://github.com/appium/appium/files/1752628/CordovaTest.zip) is a sample app, created by running:
```
cordova create CordovaTest com.jacobweber.cordovatest CordovaTest
cd CordovaTest
cordova platform add android
```
then editing `www/js/index.js` and adding a line to the initialize() function:
```
document.getElementsByClassName('app')[0].addEventListener('touchend', function(e) { alert('OK'); });
```
then running `cordova build android --debug --emulator`, launching Appium.app, starting it with chromedriverExecutable set to a download of version 2.28, and running: `python test.py` to launch my test script.

**Comment by mykola-mokhnach** [comment]
you can only use touch actions in native context. this exception is expected.

**Comment by jacobweber** [comment]
@mykola-mokhnach Thanks. Is this a limitation of Appium? The Python client? Chromium? Is there any other way to send touch start/end events in an Android web view?

**Comment by mykola-mokhnach** [comment]
you could try switching to native context and then sending touch events by coordinates.

**Comment by jacobweber** [comment]
Thanks, I'll try that. Do you know if that's planned for any future version? Anywhere else I should be reporting it or monitoring it? Seems like a pretty important feature to have.

**Comment by tmonautoguy** [comment]
@jacobweber I am experiencing this same exact issue. It would be GREAT if touch actions could be used beyond native context.
