### ISSUE TITLE
Upload file to form using iOS 11

### ISSUE THREAD

**Issue by Icaroto** [appium/appium#10250]
## The problem

Hi, I'm trying to attach a file to a form that I have on my website. For Android I can safely use the SendKeys to a input element and works fine. For iOS I get "Element is not currently visible and may not be manipulated"

My second try was to go to the Native App and manipulate the whole process:
- Click Attach
- Select Browse or Gallery
- Select an Album 
- Select a picture

The problem for the second approach comes only on the last step, I can safely get to the pictures but I can't select any. There's no element I can refer to. 

Is there a way to get that working? 

Sorry if not the place for the question, but I couldn't find much information around upload files anywhere else.

## Environment

* Appium 1.7.2
* Mac Pro
* iPhone iOS 11.2.2
* Real Device

**Comment by mykola-mokhnach** [comment]
> The problem for the second approach comes only on the last step, I can safely get to the pictures but I can't select any. There's no element I can refer to.

Try if it works in the recent Appium beta

**Comment by Icaroto** [comment]
Hi @mykola-mokhnach  I can confirm that with beta3 I can "see" the XCUI elements that represents each picture  rather than 1 single RemoteBridge element. 

So all good, thank you very much!
