### ISSUE TITLE
iOS - Exception when getting PageSource (+ infinity coordinates)

### ISSUE THREAD

**Issue by braincraft359** [appium/appium#10259]
## The problem

Exception when trying to get PageSource on a specific screen, probably due to incorrect coordinates.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2 / Xcode 9.2
* Last Appium version that did not exhibit the issue (if applicable): 1.6.4 / Xcode 8.3 /iOS 10.3
* Desktop OS/version used to run Appium: 10.12.6 Sierra
* Node.js version (unless using Appium.app|exe): 8.9.4
* Mobile platform/version under test: 11.2
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: 1.7.2

## Details

In my app I have a type picker control for date/time selection. When I try to get PageSource (from C# code) for the first time, it takes 35-40 seconds (comparing to 3s for any other screen) but anyway works...
But when I try it again (on this specific screen) or when I try to access element by xpath the app closes (simulator is still open) and I got an exception:
> A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://10.4.156.10:4723/wd/hub/session/3a3146f6-6fad-427f-b157-1e320766f698/elements. The status of the exception was ConnectionClosed, and the message was: The underlying connection was closed: The connection was closed unexpectedly.

The same thing happens when I try to inspect it with Appium Desktop - first attempt is quite slow but it works and the second one is not successful.

I think **it might be due to some coordinates being calculated incorrectly by Appium**: `x="inf" y="inf"`

Here's the PageSource of my type picker control:
```
<XCUIElementTypeScrollView type="XCUIElementTypeScrollView" enabled="true" visible="true" x="32" y="208" width="311" height="216">
  <XCUIElementTypePicker type="XCUIElementTypePicker" enabled="true" visible="true" x="32" y="208" width="261" height="216">
    <XCUIElementTypePickerWheel type="XCUIElementTypePickerWheel" value="01" enabled="true" visible="true" x="32" y="170" width="62" height="292">
      <XCUIElementTypeAny type="XCUIElementTypeAny" enabled="true" visible="false" x="inf" y="inf" width="0" height="0"/>
      <XCUIElementTypeAny type="XCUIElementTypeAny" enabled="true" visible="false" x="inf" y="inf" width="0" height="0"/>
      <!-- ... -->
      <XCUIElementTypeAny type="XCUIElementTypeAny" enabled="true" visible="false" x="inf" y="inf" width="0" height="0"/>
    </XCUIElementTypePickerWheel>
    <XCUIElementTypePickerWheel type="XCUIElementTypePickerWheel" value="14" enabled="true" visible="true" x="98" y="170" width="62" height="292">
      <XCUIElementTypeAny type="XCUIElementTypeAny" enabled="true" visible="false" x="inf" y="inf" width="0" height="0"/>
      <XCUIElementTypeAny type="XCUIElementTypeAny" enabled="true" visible="false" x="inf" y="inf" width="0" height="0"/>
      <!-- ... -->
      <XCUIElementTypeAny type="XCUIElementTypeAny" enabled="true" visible="false" x="inf" y="inf" width="0" height="0"/>
    </XCUIElementTypePickerWheel>
    <XCUIElementTypePickerWheel type="XCUIElementTypePickerWheel" value="16" enabled="true" visible="true" x="164" y="170" width="62" height="292">
      <XCUIElementTypeAny type="XCUIElementTypeAny" enabled="true" visible="false" x="inf" y="inf" width="0" height="0"/>
      <XCUIElementTypeAny type="XCUIElementTypeAny" enabled="true" visible="false" x="inf" y="inf" width="0" height="0"/>
      <!-- ... -->
      <XCUIElementTypeAny type="XCUIElementTypeAny" enabled="true" visible="false" x="inf" y="inf" width="0" height="0"/>
    </XCUIElementTypePickerWheel>
    <XCUIElementTypePickerWheel type="XCUIElementTypePickerWheel" value="PM" enabled="true" visible="true" x="230" y="170" width="62" height="292">
      <XCUIElementTypeAny type="XCUIElementTypeAny" enabled="true" visible="false" x="inf" y="inf" width="0" height="0"/>
      <XCUIElementTypeAny type="XCUIElementTypeAny" enabled="true" visible="false" x="inf" y="inf" width="0" height="0"/>
    </XCUIElementTypePickerWheel>
  </XCUIElementTypePicker>
  <XCUIElementTypeDatePicker type="XCUIElementTypeDatePicker" enabled="true" visible="true" x="292" y="208" width="305" height="216">
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="292" y="208" width="305" height="216">
      <XCUIElementTypePickerWheel type="XCUIElementTypePickerWheel" value="February" enabled="true" visible="true" x="311" y="170" width="133" height="292"/>
      <XCUIElementTypePickerWheel type="XCUIElementTypePickerWheel" value="22" enabled="true" visible="false" x="448" y="170" width="50" height="292"/>
      <XCUIElementTypePickerWheel type="XCUIElementTypePickerWheel" value="2018" enabled="true" visible="false" x="502" y="170" width="77" height="292"/>
    </XCUIElementTypeOther>
  </XCUIElementTypeDatePicker>
</XCUIElementTypeScrollView>
```

With Appium 1.6.4 and Xcode 8.3 instead of
```
<XCUIElementTypeAny type="XCUIElementTypeAny" enabled="true" visible="false" x="inf" y="inf" width="0" height="0"/>
``` 
these picker wheel elements used to be:
```
<XCUIElementTypeOther type="XCUIElementTypeOther" enabled="false" x="0" y="0" width="0" height="0"/>
```

## Link to Appium logs

[Click me](https://gist.github.com/braincraft359/c08652b339307d263882b43d0a339a45)

## Code To Reproduce Issue [ Good To Have ]

N/A due to company policy

**Comment by mykola-mokhnach** [comment]
These coordinates are calculated not by Appium, but rather by XCTest. We just get what it returns to us. Nevertheless you can also check for similar issues at https://github.com/facebook/WebDriverAgent/pulls
