### ISSUE TITLE
Appium Desktop Installer won't let me choose installation directory

### ISSUE THREAD

**Issue by etekes** [appium/appium#10262]
## The problem

I downloaded Appium.Setup.1.3.2.exe from https://github.com/appium/appium-desktop/releases
When I run it, it automatically installs Appium Desktop in C:\Users\MyUserName\AppData\Local\Programs\appium-desktop
I want to install it in C:\Program Files but I haven't found a way to do that. I tried running it both normally and as Admin.
I tried an older version (1.2.1) but got the same result.

Any help is appreciated.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium Desktop 1.3.2 and 1.2.1
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): N/A

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/appium/appium-desktop
