### ISSUE TITLE
Unable to handle mobile browser notification with android device while automating mobile site on android device

### ISSUE THREAD

**Issue by Rakeshsp05** [appium/appium#10266]
## The problem

whenever we are launching the website. The site asks for permission to send notifications but unfortunately, we are unable to handle it. Have tried passing the capabilities.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Mobile platform/version under test: Android 
* Real device or emulator/simulator:One Plus 2 V6.0.1

## Details

Capabilities tired: 
ChromeOptions options = new ChromeOptions();
options.addArguments("--disable-notifications");
cap.setCapability(ChromeOptions.CAPABILITY, options);
cap.setCapability("autoAcceptAlerts", true);
cap.setCapability(CapabilityType.UNEXPECTED_ALERT_BEHAVIOUR, "UnexpectedAlertBehaviour.ACCEPT");
cap.setCapability("autoDismissAlerts", true);
cap.setCapability(AndroidMobileCapabilityType.AUTO_GRANT_PERMISSIONS, true);

## Link to Appium logs

https://gist.github.com/Rakeshsp05/0f9c6c868c18590097393f59ac5988fe

![Uploading Screen Sh
<img width="390" alt="screen shot 2018-02-27 at 1 03 36 pm" src="https://user-images.githubusercontent.com/32235525/36716113-1ab12c3e-1bbf-11e8-9e56-a8c3d278d58a.png">
ot 2018-02-27 at 1.03.36 PM.png…]()

**Comment by mykola-mokhnach** [comment]
> cap.setCapability("autoAcceptAlerts", true);
> cap.setCapability(AndroidMobileCapabilityType.AUTO_GRANT_PERMISSIONS, true);

These capabilities only have effect in native context. In web context try to handle alerts via the standard `alert.accept/dismiss` interface

**Comment by Rakeshsp05** [comment]
But for web chrome this capability works fine , the same fails for mobile chrome 
ChromeOptions options = new ChromeOptions();
options.addArguments("--disable-notifications");
cap.setCapability(ChromeOptions.CAPABILITY, options);
