### ISSUE TITLE
ListView is not working for second time on Android v.7 with Appium1.7.2  (NoHttpResponseException: 127.0.0.1:4723 failed to respond)

### ISSUE THREAD

**Issue by HafizEmraan** [appium/appium#10269]
Hi,
In the first listView, it was able to detect the element and click on it.
But in the second ListView it was not able to detect element.

## Environment

* Appium version 1.7.2
* Windows 10 64bit
* Device -> Android A7 
* Device OS -> Nougat 7
* Real device 

**Eclipse Exception**  

Exception in thread "main" org.openqa.selenium.WebDriverException: org.apache.http.NoHttpResponseException: 127.0.0.1:4723 failed to respond
Build info: version: 'unknown', revision: '5234b32', time: '2017-03-10 09:00:17 -0800'
System info: host: 'LAPTOPxyz', ip: '189.0.0.0:80', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_112'
Driver info: driver.version: AndroidDriver

 **Appium logs**

[HTTP] <-- POST /wd/hub/session/83da62cb-484d-4471-bd05-8921d2e3bddd/element/11/click 200 194 ms - 76 
[HTTP] --> POST /wd/hub/session/83da62cb-484d-4471-bd05-8921d2e3bddd/element {"using":"xpath","value":"//*[@class='android.widget.LinearLayout' and @bounds='[0,240][1080,441]']"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath","//*[@class='android.widget.LinearLayout' and @bounds='[0,240][1080,441]']","83da62cb-484d-4471-bd05-8921d2e3bddd"]
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Waiting up to 10000 ms for condition
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//*[@class='android.widget.LinearLayout' and @bounds='[0,240][1080,441]']","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//*[@class='android.widget.LinearLayout' and @bounds='[0,240][1080,441]']","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding '//*[@class='android.widget.LinearLayout' and @bounds='[0,240][1080,441]']' using 'XPATH' with the contextId: '' multiple: false
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[CLASS=android.widget.LinearLayout, INSTANCE=4]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":{"ELEMENT":"12"}}
[AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"12"}
[HTTP] <-- POST /wd/hub/session/83da62cb-484d-4471-bd05-8921d2e3bddd/element 200 85 ms - 88 
[HTTP] --> POST /wd/hub/session/83da62cb-484d-4471-bd05-8921d2e3bddd/element/12/click {"id":"12"}
[MJSONWP] Calling AppiumDriver.click() with args: ["12","83da62cb-484d-4471-bd05-8921d2e3bddd"]
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:click","params":{"elementId":"12"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:click","params":{"elementId":"12"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: click
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":true}
[AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.click() result: true
[HTTP] <-- POST /wd/hub/session/83da62cb-484d-4471-bd05-8921d2e3bddd/element/12/click 200 163 ms - 76 
[HTTP] --> POST /wd/hub/session/83da62cb-484d-4471-bd05-8921d2e3bddd/element {"using":"xpath","value":"//android.widget.LinearLayout[@bounds='[0,444][1080,645]']"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath","//android.widget.LinearLayout[@bounds='[0,444][1080,645]']","83da62cb-484d-4471-bd05-8921d2e3bddd"]
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Waiting up to 10000 ms for condition
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//android.widget.LinearLayout[@bounds='[0,444][1080,645]']","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//android.widget.LinearLayout[@bounds='[0,444][1080,645]']","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding '//android.widget.LinearLayout[@bounds='[0,444][1080,645]']' using 'XPATH' with the contextId: '' multiple: false
[HTTP] <-- POST /wd/hub/session/83da62cb-484d-4471-bd05-8921d2e3bddd/element - - ms - - 
[HTTP] --> POST /wd/hub/session/83da62cb-484d-4471-bd05-8921d2e3bddd/element {"using":"xpath","value":"//android.widget.LinearLayout[@bounds='[0,444][1080,645]']"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath","//android.widget.LinearLayout[@bounds='[0,444][1080,645]']","83da62cb-484d-4471-bd05-8921d2e3bddd"]
[HTTP] <-- POST /wd/hub/session/83da62cb-484d-4471-bd05-8921d2e3bddd/element - - ms - - 
[Logcat] Logcat terminated with code 0, signal null
[UiAutomator] UiAutomator exited unexpectedly with code 0, signal null
[UiAutomator] Moving to state 'stopped'
[AndroidDriver] Shutting down Android driver
[Appium] Closing session, cause was 'UiAUtomator shut down unexpectedly'
[Appium] Removing session 83da62cb-484d-4471-bd05-8921d2e3bddd from our master session list
[ADB] Getting connected devices...
[ADB] 0 device(s) connected

**Code To Reproduce Issue [ Good To Have ]**

Piece of Code:
Am using bounds to find the elements.
System.out.println(" Select Profile");
driver.findElement(By.xpath ("//android.widget.LinearLayout[@bounds='[0,1215][780,1377]']")).click();
System.out.println(" Select Password");
driver.findElement(By.xpath ("//android.widget.LinearLayout[@bounds='[0,444][1080,645]']")).click()

**Now unable to click "Password" -> for error see appium logs**

**Comment by mykola-mokhnach** [comment]
Switch to uiatomator2 backend

**Comment by HafizEmraan** [comment]
thanks, now its working fine.
