### ISSUE TITLE
Test fails due to wrong session id (Jenkins run) 

### ISSUE THREAD

**Issue by danielMayberg** [appium/appium#10267]
## The problem
happens when I run a test suite in jenkins

it looks like appium is searching for element but it’s sending the id of the previous session instead of the current one to the server, happen mostly in second+third suite runs.

## Environment

running appium 1.7.1 on mac with ruby

## Link to Appium logs
2018-02-20 21:07:21:791 - info: [debug] [BaseDriver] Waiting up to 0 ms for condition
2018-02-20 21:07:21:791 - info: [debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/95B1E2A9-E162-49E0-995D-B9038D4A0F94/element] with body: {“using”:“id”,“value”:“login_with_email_button”}
2018-02-20 21:07:21:797 - info: [debug] [JSONWP Proxy] Got response with status 200: {“value”:“Session does not exist”,“sessionId”:“BA9D733C-2FA2-4828-B8C2-22AC229F9DA9”,“status”:6}
2018-02-20 21:07:21:800 - info: [HTTP] <-- POST /wd/hub/session/df6002bb-4510-44a5-be88-8dc0c51c2c5a/element 500 10 ms - 164

**full log in file**
[appium_log.txt](https://github.com/appium/appium/files/1761796/appium_log.txt)

**Comment by mykola-mokhnach** [comment]
To me this looks like an issue in the client code

**Comment by trix0** [comment]
try to upgrade to latest version of appium, provide full log and client code if possible

**Comment by danielMayberg** [comment]
latest version is super buggy, all webview related tests failed when I upgraded, added the log,
regarding code the code is the same it always was, this bug has been happening for the past month or two, the webdriver is using the id of a previous session instead of usin the new one, I don't think that part of the code is clientside

**Comment by trix0** [comment]
well see, instead of reporting problem of latest version you are reporting a problem with older version. Maybe if you would report the problem with latest people would help you to fix it and you would benefit from new features and so on. :-) just sayin. I think it may be a bug but as I have no idea how or where to look for a problem I am not able to fix it and yeah  Please report issue with latest version so ppl can look on it.

**Comment by mykola-mokhnach** [comment]
The attached log shows version 1.7.0, which is pretty old. Try with 1.7.2 or better with appium@beta

**Comment by danielMayberg** [comment]
@mykola-mokhnach look at my previous comment, I upgraded to 1.7.2and it failed failed to recognize all webview elements so I downgraded . Also, this session id issue occured for me on 1.7.2 as well..

**Comment by danielMayberg** [comment]
@mykola-mokhnach please change the label, I tried your advice, the result is the same, putting a different label on it doesn't make it go away..

**Comment by KazuCocoa** [comment]
Could you attach the client side code?
If you implement test code with thread programming, I guess handling session id sometimes wrong.
(In this case, I have an experience handling wrong session id.)

**Comment by danielMayberg** [comment]
Hey I messed around with the WDA capabilities and the issue was solved with useNewWDA:'true'
