### ISSUE TITLE
Implementation of Memory Capture in Appium

### ISSUE THREAD

**Issue by pavanbachu0604** [appium/appium#10268]
## The problem

Is there a way, we can capture the Memory using Appium for every page (Hybrid/Native). 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Node.js version (unless using Appium.app|exe): 9.4.0
* Mobile platform/version under test: iOS 10.3.2
* Real device or emulator/simulator:Real Device

## Details

We can capture the memory of app  with respect to each WebView. This [blog](https://medium.com/xcblog/continuous-performance-testing-of-an-ios-apps-using-xctest-811df87fe227)  shows a way in implementation of Memory capture in XCUITest Automated test

**Comment by vjmaiky** [comment]
They have support for Android https://appiumpro.com/editions/5
And as far as they informed, there will not be a support for iOS in the near future.

**Comment by mykola-mokhnach** [comment]
Linking https://github.com/appium/appium-xcuitest-driver/pull/637

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios/ios-xctest-performance.md
