### ISSUE TITLE
androidInstallTimeout des cap does not work 

### ISSUE THREAD

**Issue by trix0** [appium/appium#10260]
## The problem
I am trying to install app using installApp(). My phone is one of the older ones so It takes longer to install app to it. I am getting [MJSONWP] Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command '/home/trixo/Android/Sdk/platform-tools/adb -P 5037 -s localhost\:7401 install -r /home/trixo/Code/javaRewrite/Tests/CleanInstall/apk/pl.apk' timed out after 60000ms'; Stderr: ''; Code: 'null'.

I tried to use androidInstallTimeout in des caps but it does not seem to work. It still says 60000ms.

## Environment

* Appium version (or git revision) that exhibits the issue:1.8.0-beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:ubuntu
* Node.js version (unless using Appium.app|exe):9.4.0
* Mobile platform/version under test: 6.0.0
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe:Cli

## Link to Appium logs
https://gist.github.com/trix0/93cc65e1c5c17a36c607ed8b95273e89

**Comment by mykola-mokhnach** [comment]
`InstallApp` accepts it own options, however this functionality is only implemented in the recent client versions.

**Comment by trix0** [comment]
@mykola-mokhnach  could you please give me more info about how to solve this issue "timed out after 60000ms'; Stderr: ''; Code: 'null'" ? I tried everything that was on my mind. I edited even time in appium driver and it stills keep the limit on 60s. I have tried to pass options in installApp I just have no idea what kind of and how . Only thing i need is to give it 30 more seconds and I ll be naked dancing in the forest.

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/java-client/blob/f50287394b25571408ee41ad8cddea7ce927e5f8/src/main/java/io/appium/java_client/InteractsWithApps.java#L69

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/java-client/blob/92671b2db81fffcab0c51db2a62462dc1c75886b/src/main/java/io/appium/java_client/android/appmanagement/AndroidInstallApplicationOptions.java#L67

**Comment by trix0** [comment]
Well i tried for 2 hours. I tried all the possibilities to get it to work. I would say it should be like this tho
        let options=[
          {"timeout": 1000},
          {"grantPermissions":true}
        ]
        
        await client.installApp(__dirname+'/apk/'+apkFileName+'.apk',options)

is it correct ?

**Comment by mykola-mokhnach** [comment]
Unfortunately I cannot help much if it is not Java or Python client

**Comment by trix0** [comment]
Thanks anyway Nice day bro
