### ISSUE TITLE
Trouble xcodebuild failed with code 65

### ISSUE THREAD

**Issue by MathuMarques** [appium/appium#10265]
Hey fellas, Im having a kind of weird problem while I'm trying to run Appium in my real device.

The problem is that "xcodebuild" Is failing, and I don't know why that its happening. Bellow I'll show you guys the kinds of problems that I'm having here, please if anybody could give me a hand it would be lovely!

**Comment by MathuMarques** [comment]
<img width="648" alt="captura de tela 2018-02-23 as 17 48 25" src="https://user-images.githubusercontent.com/34027867/36696090-04eadcf8-1b22-11e8-8dde-1ba9c6dd3a57.png">

**Comment by imurchie** [comment]
Have you followed the instructions in the page noted?

**Comment by imurchie** [comment]
See https://github.com/appium/appium/blob/master/docs/en/drivers/ios-xcuitest-real-devices.md

**Comment by vjmaiky** [comment]
configure WDA for mac os; go to applications - right click - show package content - and go to wda folder and open the csproj

**Comment by MathuMarques** [comment]
Yeah @imurchie I had follow the instructions more than one time, and always the problem turned to be the same. :(

**Comment by MathuMarques** [comment]
@vjmaiky I'm not able to find that folder in Appium contents, can you give me the absolute path to this folder?

**Comment by vjmaiky** [comment]
/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver

**Comment by MathuMarques** [comment]
Ok I have found the WDA folder, and what I must do right now? @vjmaiky

**Comment by vjmaiky** [comment]
to configure WDA as on @imurchie's doc posted fe comments upper. (open WDA xcodeproj and see all resources are there; if not download follow https://github.com/appium/WebDriverAgent/tree/f7110b4e12cb7b7f28a37a4f8fb348588ee003b9 )

**Comment by MathuMarques** [comment]
There are just this files inside my WDA folder, seems to be everything ok? or should must have anything else here?
<img width="1048" alt="captura de tela 2018-02-27 as 10 07 11" src="https://user-images.githubusercontent.com/34027867/36730387-02243c56-1ba6-11e8-88ef-1eda57a00979.png">

**Comment by mmorenoivy** [comment]
I am having the same issue and configured the WDA already by following this: https://github.com/appium/WebDriverAgent/tree/f7110b4e12cb7b7f28a37a4f8fb348588ee003b9..

**Comment by MathuMarques** [comment]
@mmorenoivy Yeah, I also have done the same steps and everything appears to be the same.

**Comment by mmorenoivy** [comment]
It's a pain though. I have posted this issue in Appium forum, https://discuss.appium.io/t/xcodebuild-is-successful-thru-terminal-but-i-am-still-receiving-xcodebuild-failed-with-code-65-in-appium-desktop-inspector/21134/2 and someone responded:

> I feel your pain. It took me several days just to get the WebDriverAgent app to deploy to a real device. I ended up having to create a new xcode project, then create a new Provisioning profile for that project as well. Then, I opened the WebDriverAgent project in xcode and changed the signing to use the provisioning profile I had created. Then I passed the bundle id of the project I created as the updatedWDABundleId value in my desired capabilites. It works, but every time I update appium, it resets the WebDriverAgent project settings, and I have to go update the signing again. Hope this helps!

> 

I haven't tried this yet but I'll see..

**Comment by MathuMarques** [comment]
Please tell me if you have lucky with that! Thx @mmorenoivy

**Comment by hliulka15** [comment]
I've been having a similar issue for a while now. "appium-xcuitest-driver" does not exist under /Applications/Appium.app/Contents/Resources/app/node_modules in my machine. I've tried uninstalling and reinstalling and all the above mentioned suggestions except @mmorenoivy response. Still the folder does not exist.

**Comment by MathuMarques** [comment]
I still have "appium-xcuitest-driver inside" /Applications/Appium.app/Contents/Resources/app/node_modules, maybe you didn't install correct. Try to use "sudo npm install appium" in command line.

**Comment by MathuMarques** [comment]
I want to know if appium works with a iOS version above 11, I think this is my problem. Anyone could help me with that? @hliulka15 @mmorenoivy  @vjmaiky @imurchie

**Comment by hliulka15** [comment]
Oh that was user error, I was in the wrong path from a different resource. My apologies, I've been troubleshooting this for a few days now so all my info is getting muddled. 

I'm also running iOS 11. I had appium working in early January on iOS 11. Then I left the project for a couple weeks, updated appium when I got back, and everything stopped working. Tried reverting to older versions but it didn't work. 

I suspect it's because my WebDriverAgent project in xcode appears to have errors in it and I don't know how to fix it. When run in Xcode it shows a successful build but every time I try to run it through appium I get `xcodebuild failed with code 65`

**Comment by MathuMarques** [comment]
@hliulka15 Its just the same for me, I just can't make it running trough appium, only when Im using Xcode the build is complete.

**Comment by hliulka15** [comment]
@MathuMarques in case you're still working on this, I finally got it running on my device. Ultimately I had to get a paid apple developer account and followed the steps @mmorenoivy suggested and made sure all my signing privileges were consistent with my paid account. If you're working on a free account, like I was, that may be the problem. Let me know if that's not the case.

**Comment by stigmata1** [comment]
Do we know if the free account is whats causing this issue ? Does any one know if the paid account really fix this issue ?

**Comment by vjmaiky** [comment]
i think yes; with a free account you're not able to sign an app to run on a device; on simulator it is possible but not on real device (i'm not 100% sure, but i think that's the case)

**Comment by imurchie** [comment]
A free account should give you the ability to sign _two_ apps at a time. One will have to be the Appium WebDriverAgent app, and one the app under test. It does _not_ allow you to use a wild card, and often rejects bundle identifiers for no apparent reason. That is why Appium has the `updatedWDABundleId` capability, so you can change the bundle identifier for WebDriverAgent to get signing done.

Unfortunately, since you can only sign two apps with a free account, and Apple requires you to explicitly set the permission to run apps with development signatures, it often means installing your app under test onto the device, accepting the permissions, and then running the tests without uninstalling the app.

**Comment by hliulka15** [comment]
ah that explains my issue then. I was trying to sign 3 apps at a time (WDA, UI Catalog, and my own).

**Comment by stigmata1** [comment]
That explains the problem. Thanks.
