### ISSUE TITLE
Two different pages of the android application are overlapping while finding the elements

### ISSUE THREAD

**Issue by MahadevG** [appium/appium#10276]
Hi,
I have a android application which is created using react native. I need to automate the application. To find the element I am using Appium app inspector and UIAutomator and Monator . By using these 3 I am able to get the elements . But in some of the page I am not able to get the elements because 2 pages are overlapping.
Let me clear you with example

First I will open Home page of the Application. And I will find the elements .
I will open login page and I will get the screenshot of login page to get the elements but in background I am getting Home page of the application.
Here what happening is , I can see the Screenshot of Login page , when I try to get the elements by clicking on particular icon or text. I am getting the elements of Home page ( which is in background) . It is same with UIAutomator and Monator.
I am not able to get any element of the login page.
Can anyone help me to overcome from this problem.

Please find the Screenshots
Homepage of the application: https://drive.google.com/open?id=1_AUMKpxT2cNIhOFdNe98lCpAa7RjlTFx

LoginPage: https://drive.google.com/open?id=1CnvQK1HUMoQ8CO9h1cVu0_3LVe15CwqF

WhileFindingElements: https://drive.google.com/open?id=10FlunyTvy6NLCdcZWWVsba4ZDcoal_88

**Comment by mykola-mokhnach** [comment]
Do you switch into webview context?

**Comment by MahadevG** [comment]
Yeah

**Comment by mykola-mokhnach** [comment]
This it's rather chromedriver issue

**Comment by MahadevG** [comment]
So what is the solution for this issue??

**Comment by mykola-mokhnach** [comment]
report the issue to Google? Update the webview and chromedriver version to the most recent one?

**Comment by Saravanan091** [comment]
Just try to reset app using driver.resetApp() method while launching appium session.

**Comment by MahadevG** [comment]
I am launching the app to find the element in appium desktop client. There I provided capabilities to launch the session. How to reset the app while launching  appium session.

**Comment by Deepak-merahkee** [comment]
I will provide apk file can anybody try to find the elements of the login page.Using Appium app inspector or UIAutomator. 

You can get apk here
https://drive.google.com/open?id=11XdESMfiIFlxFFy0NRhfykGFVU7EL-bY

**Comment by MahadevG** [comment]
I will provide apk file can anybody try to find the elements of the login page.Using Appium app inspector or UIAutomator.

You can get apk here
https://drive.google.com/open?id=11XdESMfiIFlxFFy0NRhfykGFVU7EL-bY

**Comment by MahadevG** [comment]
I am able to get the elements using Macaca App inspector. It resolved my problem but still issue is present with Appium app inspector and UIAutomator.

**Comment by mykola-mokhnach** [comment]
Closed as inactive
