### ISSUE TITLE
Is Chrome browser supported for automation on iPhone?

### ISSUE THREAD

**Issue by SavitaPatil01** [appium/appium#10275]
## The problem

Is there any support for IOS device automation with Chrome browser.

## Environment

* Desktop OS/version used to run Appium: Windows NT
* Mobile platform/version under test: iPhone
* Real device or emulator/simulator:  Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Due to the CORS restriction on Safari for iOS devices, we are thinking of trying Chrome for automation on iOS devices. Is there any support for Chrome browser on iPhone?

Thanks.

**Comment by mykola-mokhnach** [comment]
No, there is no such support. Only Safari is supported in iOS.
