### ISSUE TITLE
while executing Bootstrap.sh file, It is getting failed with 124 errors. 

### ISSUE THREAD

**Issue by shivam0406** [appium/appium#10271]
## Hi, 
I am trying to build WebDriverAgent project manually and before building the project, I am executing the Bootstrap.sh file. 

This file is not getting executed successfully. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2 (command line appium)
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 
* Node.js version (unless using Appium.app|exe): v9.6.1
* Mobile platform/version under test: iOS 10.3.2
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
{code}
Shivams-MacBook-Pro:WebDriverAgent shivamgupta$ ./Scripts/bootstrap.sh 
Fetching dependencies
Building Inspector
Creating bundle directory...
Fetching Inspector dependencies...
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated css-list@0.1.3: Deprecated.

> fsevents@1.1.3 install /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/fsevents
> node install

[fsevents] Success: "/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/fsevents/lib/binding/Release/node-v59-darwin-x64/fse.node" is installed via remote
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN react-dom@15.6.2 requires a peer of react@^15.6.2 but none is installed. You must install peer dependencies yourself.
npm WARN web-driver-inspector@1.0.0 No repository field.

added 684 packages in 188.249s
Validating Inspector
Launching Flow server for /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector
Spawned flow server (pid=74720)
Logs will go to /private/tmp/flow/zSusrzSlocalzSlibzSnode_moduleszSappiumzSnode_moduleszSappium-xcuitest-driverzSWebDriverAgentzSInspector.log
No errors!

/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/js/app.js
  13:18  error  Unable to resolve path to module 'js/http'                import/no-unresolved
  14:20  error  Unable to resolve path to module 'js/screen'              import/no-unresolved
  15:31  error  Unable to resolve path to module 'js/screenshot_factory'  import/no-unresolved
  16:18  error  Unable to resolve path to module 'js/tree'                import/no-unresolved
  17:22  error  Unable to resolve path to module 'js/tree_node'           import/no-unresolved
  18:25  error  Unable to resolve path to module 'js/tree_context'        import/no-unresolved
  19:23  error  Unable to resolve path to module 'js/inspector'           import/no-unresolved
  28:14  error  Missing space before function parentheses                 space-before-function-paren
  33:13  error  Missing space before function parentheses                 space-before-function-paren
  38:20  error  Missing space before function parentheses                 space-before-function-paren
  42:18  error  Missing space before function parentheses                 space-before-function-paren
  49:13  error  Expected property shorthand                               object-shorthand
  56:12  error  Missing space before function parentheses                 space-before-function-paren
  65:9   error  Missing space before function parentheses                 space-before-function-paren

/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/js/gesture_recognizer.js
  16:14  error  Missing space before function parentheses  space-before-function-paren
  26:14  error  Missing space before function parentheses  space-before-function-paren
  41:14  error  Missing space before function parentheses  space-before-function-paren
  47:12  error  Missing space before function parentheses  space-before-function-paren
  66:12  error  Missing space before function parentheses  space-before-function-paren
  70:5   error  Unexpected var, use let or const instead   no-var
  80:16  error  Missing space before function parentheses  space-before-function-paren
  84:15  error  Missing space before function parentheses  space-before-function-paren

/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/js/http.js
  13:13  error    Missing space before function parentheses  space-before-function-paren
  13:20  warning  Avoid callbacks. Prefer Async/Await        promise/prefer-await-to-callbacks
  19:7   error    Unexpected var, use let or const instead   no-var
  20:7   warning  Avoid callbacks. Prefer Async/Await        promise/prefer-await-to-callbacks
  25:14  error    Missing space before function parentheses  space-before-function-paren
  25:27  warning  Avoid callbacks. Prefer Async/Await        promise/prefer-await-to-callbacks
  29:7   error    Expected property shorthand                object-shorthand
  32:7   error    Unexpected var, use let or const instead   no-var
  33:7   warning  Avoid callbacks. Prefer Async/Await        promise/prefer-await-to-callbacks

/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/js/image_utils.js
  11:34  error    Missing space before function parentheses  space-before-function-paren
  11:55  warning  Avoid callbacks. Prefer Async/Await        promise/prefer-await-to-callbacks
  15:40  error    Missing space before function parentheses  space-before-function-paren
  15:69  warning  Avoid callbacks. Prefer Async/Await        promise/prefer-await-to-callbacks
  16:5   error    Unexpected var, use let or const instead   no-var
  20:5   error    Unexpected var, use let or const instead   no-var
  28:45  error    Missing space before function parentheses  space-before-function-paren
  28:79  warning  Avoid callbacks. Prefer Async/Await        promise/prefer-await-to-callbacks
  29:5   error    Unexpected var, use let or const instead   no-var
  33:5   error    Unexpected var, use let or const instead   no-var
  41:22  error    Missing space before function parentheses  space-before-function-paren
  41:31  warning  Avoid callbacks. Prefer Async/Await        promise/prefer-await-to-callbacks
  42:5   error    Unexpected var, use let or const instead   no-var
  44:28  error    Missing space before function parentheses  space-before-function-paren
  45:7   warning  Avoid callbacks. Prefer Async/Await        promise/prefer-await-to-callbacks

/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/js/inspector.js
  13:18  error  Unable to resolve path to module 'js/http'  import/no-unresolved
  14:1   error  Unexpected var, use let or const instead    no-var
  18:22  error  Missing space before function parentheses   space-before-function-paren
  23:9   error  Missing space before function parentheses   space-before-function-paren
  38:18  error  Missing space before function parentheses   space-before-function-paren
  64:14  error  Missing space before function parentheses   space-before-function-paren
  68:5   error  Unexpected var, use let or const instead    no-var
  86:6   error  Missing space before function parentheses   space-before-function-paren
  89:9   error  Unexpected var, use let or const instead    no-var
  97:13  error  Unexpected var, use let or const instead    no-var
  98:13  error  Unexpected var, use let or const instead    no-var

/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/js/screen.js
   13:18  error  Unable to resolve path to module 'js/http'                import/no-unresolved
   14:31  error  Unable to resolve path to module 'js/gesture_recognizer'  import/no-unresolved
   16:1   error  Unexpected var, use let or const instead                  no-var
   21:21  error  Missing space before function parentheses                 space-before-function-paren
   22:6   error  Expected indentation of 4 spaces but found 5              indent
   25:23  error  Missing space before function parentheses                 space-before-function-paren
   26:7   error  Expected indentation of 4 spaces but found 6              indent
   29:9   error  Missing space before function parentheses                 space-before-function-paren
   54:20  error  Missing space before function parentheses                 space-before-function-paren
   71:22  error  Missing space before function parentheses                 space-before-function-paren
   72:5   error  Unexpected var, use let or const instead                  no-var
   79:13  error  Missing space before function parentheses                 space-before-function-paren
   83:19  error  Missing space before function parentheses                 space-before-function-paren
   84:5   error  Unexpected var, use let or const instead                  no-var
   85:5   error  Unexpected var, use let or const instead                  no-var
   86:5   error  Unexpected var, use let or const instead                  no-var
   87:5   error  Unexpected var, use let or const instead                  no-var
   96:9   error  Unexpected var, use let or const instead                  no-var
  100:13  error  Expected property shorthand                               object-shorthand
  101:13  error  Expected property shorthand                               object-shorthand
  102:13  error  Expected property shorthand                               object-shorthand
  103:13  error  Expected property shorthand                               object-shorthand
  114:13  error  Missing space before function parentheses                 space-before-function-paren
  115:5   error  Unexpected var, use let or const instead                  no-var
  116:5   error  Unexpected var, use let or const instead                  no-var
  120:20  error  Missing space before function parentheses                 space-before-function-paren
  121:5   error  Unexpected var, use let or const instead                  no-var
  122:5   error  Unexpected var, use let or const instead                  no-var
  128:9   error  Unexpected var, use let or const instead                  no-var
  132:13  error  Expected property shorthand                               object-shorthand
  133:13  error  Expected property shorthand                               object-shorthand
  143:22  error  Missing space before function parentheses                 space-before-function-paren
  146:9   error  Unexpected var, use let or const instead                  no-var
  160:14  error  Missing space before function parentheses                 space-before-function-paren
  164:14  error  Missing space before function parentheses                 space-before-function-paren
  168:12  error  Missing space before function parentheses                 space-before-function-paren
  172:12  error  Missing space before function parentheses                 space-before-function-paren
  176:7   error  Missing space before function parentheses                 space-before-function-paren
  186:19  error  Missing space before function parentheses                 space-before-function-paren
  202:24  error  Missing space before function parentheses                 space-before-function-paren
  215:34  error  Missing space before function parentheses                 space-before-function-paren
  216:5   error  Unexpected var, use let or const instead                  no-var
  221:5   error  Unexpected var, use let or const instead                  no-var
  224:5   error  Unexpected var, use let or const instead                  no-var
  228:75  error  Missing space before opening brace                        space-before-blocks
  229:9   error  Expected indentation of 6 spaces but found 8              indent

/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/js/screenshot_factory.js
  10:24  error    Unable to resolve path to module 'js/image_utils'  import/no-unresolved
  12:30  error    Missing space before function parentheses          space-before-function-paren
  13:3   error    Unexpected var, use let or const instead           no-var
  14:3   error    Unexpected var, use let or const instead           no-var
  15:3   error    Unexpected var, use let or const instead           no-var
  17:3   error    Unexpected var, use let or const instead           no-var
  18:3   error    Unexpected var, use let or const instead           no-var
  23:26  error    Missing space before function parentheses          space-before-function-paren
  23:60  warning  Avoid callbacks. Prefer Async/Await                promise/prefer-await-to-callbacks
  33:28  error    Missing space before function parentheses          space-before-function-paren
  37:22  error    Missing space before function parentheses          space-before-function-paren
  37:43  warning  Avoid callbacks. Prefer Async/Await                promise/prefer-await-to-callbacks
  51:34  error    Missing space before function parentheses          space-before-function-paren
  51:42  warning  Avoid callbacks. Prefer Async/Await                promise/prefer-await-to-callbacks
  52:5   error    Unexpected var, use let or const instead           no-var
  58:5   warning  Avoid callbacks. Prefer Async/Await                promise/prefer-await-to-callbacks

/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/js/tree.js
   23:9   error  Missing space before function parentheses  space-before-function-paren
   42:16  error  Missing space before function parentheses  space-before-function-paren
   46:21  error  Missing space before function parentheses  space-before-function-paren
   52:13  error  Missing space before function parentheses  space-before-function-paren
   64:13  error  Missing space before function parentheses  space-before-function-paren
   84:5   error  Unexpected var, use let or const instead   no-var
  101:14  error  Missing space before function parentheses  space-before-function-paren
  107:19  error  Missing space before function parentheses  space-before-function-paren
  113:19  error  Missing space before function parentheses  space-before-function-paren

/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/js/tree_context.js
  11:14  error  Missing space before function parentheses  space-before-function-paren
  16:21  error  Missing space before function parentheses  space-before-function-paren

/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/js/tree_node.js
  11:19  error  Missing space before function parentheses  space-before-function-paren
  18:23  error  Missing space before function parentheses  space-before-function-paren
  19:5   error  Unexpected var, use let or const instead   no-var
  26:23  error  Missing space before function parentheses  space-before-function-paren
  27:5   error  Unexpected var, use let or const instead   no-var
  36:19  error  Missing space before function parentheses  space-before-function-paren
  49:14  error  Missing space before function parentheses  space-before-function-paren

✖ 137 problems (124 errors, 13 warnings)

Shivams-MacBook-Pro:WebDriverAgent shivamgupta$ pwd
/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
Shivams-MacBook-Pro:WebDriverAgent shivamgupta$ node --v
node: bad option: --v
Shivams-MacBook-Pro:WebDriverAgent shivamgupta$ node -v
v9.6.1
Shivams-MacBook-Pro:WebDriverAgent shivamgupta$ 
{code}

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/facebook/WebDriverAgent/issues

**Comment by shivam0406** [comment]
Thanks :)
