### ISSUE TITLE
Not able to get screenshot of app using app inspector in ios simulator

### ISSUE THREAD

**Issue by krupar92** [appium/appium#10272]
Hi,

I have an ios .app file in which i am trying to inspect elements using appium app inspector with an Iphone 6 simulator.I am initially able to do it, but later stages it fails with the following error

Could not obtain source: {"cause":{"sessionId":"509788da-112d-42b7-898b-43242dfc8249","status":13,"value":{"message":"An unknown server-side error occurred while processing the command. Original error: A session is either terminated or not started"}},"jsonwire-error":{"detail":"An unknown server-side error occurred while processing the command.","status":13,"summary":"UnknownError"},"message":"[source()] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: A session is either terminated or not started","status":13}

These are my versions of software used.

1.Installed driver list:
  ios: 2.0.30
2. Node.js checklist:
  node env: /usr/local/bin/node
  node version: v8.9.2
3.  iOS checklist:

  Xcode Command Line Tools is ready, version: 2349.
  xcodebuild version: 9.2
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.27.0
4. platformVersion: 11.2

Please help!!!

**Comment by krupar92** [comment]
jlipps: Can you please help in resolving this issue ?

**Comment by mykola-mokhnach** [comment]
Cannot help without the full server log

**Comment by krupar92** [comment]
@mykola-mokhnach :Please find the logs here

https://gist.github.com/krupar92/0be47112343f2812d259cde2dd3e30f2

**Comment by mykola-mokhnach** [comment]
This looks like a problem in the client code. I see that multiple sessions are created and then some requests are sent to expired/non existing ones.

**Comment by krupar92** [comment]
@mykola-mokhnach :Let me send u fresh logs. I have been trying this from long time. Doesn't seem to work at all. Please help

**Comment by krupar92** [comment]
@mykola-mokhnach :Please find latest logs

https://gist.github.com/krupar92/7f99507472da9dcbe70830585d19caa9

**Comment by mykola-mokhnach** [comment]
> [HTTP] <-- POST /wd/hub/session/ad7cf2cb-fc00-4e1d-82c5-1120266b419a/element/B0982D23-D9E6-4F0F-A241-4198B986CD9A/click 200 950 ms - 118 
> [HTTP] --> GET /wd/hub/session/ccd6af01-8bad-4af4-998c-0b02508f65d5/source {}
> [MJSONWP] Calling AppiumDriver.getPageSource() with args: ["ccd6af01-8bad-4af4-998c-0b02508f65d5"]
> [XCUITest] Executing command 'getPageSource'
> [JSONWP Proxy] Proxying [GET /source] to [GET http://localhost:8100/session/8254F014-FE77-4FB6-9602-2D8E79EB2735/source] with no body
> [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"Session does not exist\",\n  \"sessionId\" : \"22E74E00-B53E-4246-A2ED-7AC69EE5CE6A\",\n  \"status\" : 6\n}"


It is still the same error - you are trying to get a screenshot from non-existing session.

**Comment by krupar92** [comment]
@mykola-mokhnach : I am running the app in eclipse and then inspecting it through appium. The session is active in the simulator opened through eclipse, but when i see it in appium , it gives this error.

**Comment by mykola-mokhnach** [comment]
Then it is an issue with Appium desktop and should be posted to https://github.com/appium/appium-desktop. Or you are just using it in a wrong way.
