### ISSUE TITLE
The placeholder is still displaying when setValue on textField with Webview Appium hybridapp on iOS real device

### ISSUE THREAD

**Issue by miendt** [appium/appium#10279]
## The problem

The placeholder is still displaying when setValue on textField with Webview Appium hybridapp on iOS real device.
Currently, i'm using browser.setValue(selector,values); to setValue for textField

## Environment
* WebdriverIO version: 4.11.0
* Node.js version: v8.9.3
* Chimp version: 0.50.2
* Appium version: 1.7.1
* Mobile platform/version under test: iOS/v11.2.6
* Real device or emulator/simulator: iOS real Device

## Details

- I'm using iOS WebKit Debug Proxy to switch to Webview to run iOS real device for hybridapp
- I also try to click on the input field after entered the text
However, I have problem relate to the placeholder is still displaying when setValue on textField.

For example:
Login screen after inputting the id and password ==> id and password's textfield still is displaying placeholder text, so it cannot login to app.
![placeholder](https://user-images.githubusercontent.com/22675530/36823014-aa4c60c4-1d2d-11e8-953f-7c7637771c6c.png)

**Comment by mykola-mokhnach** [comment]
IWDP is wery different from chromedriver, so I wouldn't expect these to work totally similarly. 

Try clear/sendKeys instead
