### ISSUE TITLE
appium not able to get the webview in actual device whereas I have the same webview in simulator

### ISSUE THREAD

**Issue by suvidhapra** [appium/appium#10274]
Appium not able to get the webview in actual device whereas I have the same webview in simulator

In my application I have login screen as webview and I am not able to get the webview in actual device whereas in simulator I am easily getting both webviews(NATIVE_APP, WEBVIEW_1233), but when I run the same set of scripts in actual device it returns only one webview 'NATIVE_APP'

Environment
Appium version : 1.7.2
Desktop OS/version used to run Appium: OS-X 10.13.3 (17D47)
Node.js version (unless using Appium.app|exe): v9.4.0
Mobile platform/version under test: iPhone 8 Plus iOS - 11.1.1
Real device or emulator/simulator: Real Device
Appium CLI or Appium.app|exe: Appium CLI
Details
In my application I have login screen as webview and I am not able to get the webview in actual device whereas in simulator I am easily getting both webviews(NATIVE_APP, WEBVIEW_1233), but when I run the same set of scripts in actual device it returns only one webview 'NATIVE_APP'

Appium logs
https://gist.github.com/suvidhapra/5f75b9d2957a750d21ff302cc7c6c66c

Code To Reproduce Issue [ Good To Have ]

webview = @driver.available_contexts
webview.each {|st| puts st}
@driver.set_context(webview[1])

[caps]
platformName = "ios"
deviceName = "Test Device"
platformVersion = "11.1.1"
app = "../iOSClientPOC/app/app4815162342_qa.ipa"
automationName = "XCUITest"
udid = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
xcodeOrgId = "XXXXXXXXXX"
xcodeSigningId = "iPhone Developer"

Output:
|NATIVE_APP

**Note** : I opened the same issue before as well, please refer the issue for my new findings after opened a ticket to IWDP. Thank you!!!

https://github.com/appium/appium/issues/10095#event-1457450176

**Comment by suvidhapra** [comment]
[](url)

**Comment by dpgraham** [comment]
Did you follow the setup guide https://appium.io/docs/en/drivers/ios-xcuitest-real-devices/ ?

Also, did you install [ios-webkit-debug-proxy](https://appium.io/docs/en/writing-running-appium/web/ios-webkit-debug-proxy/index.html)?

**Comment by suvidhapra** [comment]
@dpgraham Hi Dan,

Yes I have done the setup as well, installation of ios-webkit-debug-proxy

**Comment by dpgraham** [comment]
Can you try using ios-webkit-debug-proxy separate from Appium to see if it can see your WebView (https://github.com/google/ios-webkit-debug-proxy)
