### ISSUE TITLE
 prompt box or  phone pops up notification cannot  be clicked event by Point coordinates

### ISSUE THREAD

**Issue by Kitty2014** [appium/appium#10288]
The problem
Cannot click the pops up notification which trigger by phone /System power is low  prompt box

Environment
Appium version (or git revision) that exhibits the issue: 1.7.2

Desktop OS/version used to run Appium: Mac High Sierra
Node.js version (unless using Appium.app|exe): v9.4.0
Mobile platform/version under test: iOS 11.3  11.2
Real device or emulator/simulator: Both
Appium CLI or Appium.app|exe: Both

**Comment by mykola-mokhnach** [comment]
This is known XCTest limitation. Please report to Apple.
