### ISSUE TITLE
Android App: widget cannot horizontal scroll using UiScrollable  

### ISSUE THREAD

**Issue by ljzhangi** [appium/appium#10282]
## The problem
I am automating an android app and i want to select the children elemwnt from the android.widget.HorizontalScrollView. I am using UiScrollable to scroll the list, but the  HorizontalScrollView widget cannot scroll.

## Environment

* Appium version (or git revision) that exhibits the issue: java client - 5.0.4
* Desktop OS/version used to run Appium: Ubuntu 16.04
* Node.js version (unless using Appium.app|exe): 9.0.4
* Mobile platform/version under test: MIUI8.1(Android 6.0.1)
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:1.7.2

## Details
When I turn on Pointer location in Developer options, I can watch the pointer is scrolling, but the widget was not changed.

## Link to Appium logs

https://gist.github.com/ljzhangi/100b5870c270d7f3199caf99010c748d

## Code To Reproduce Issue [ Good To Have ]
`String result = driver.findElement(MobileBy.AndroidUIAutomator("new UiScrollable(new UiSelector().resourceId(\"com.mijiashop.main:id/main_tab\")).setAsHorizontalList().scrollIntoView(new UiSelector().text(\"健康\"))")).getText();`
 `System.out.println(result);`

**Comment by vmaxim** [comment]
@mykola-mokhnach 


> I can watch **the pointer is scrolling**, but the widget was not changed.

The issue is not clear enough to suggest any ideas.

**Comment by ljzhangi** [comment]
@mykola-mokhnach 
Thank you,
I try with java-client:6.0.0-BETA3, still cannot be scrolled.

And I upload a screenrecord, please refer to:
[screenrecord](https://github.com/ljzhangi/LaunchTimeTest/blob/master/filename.mp4)

**Comment by vmaxim** [comment]
Looks like it's nothing to do with appium. I'll bet you get the same behavior if you perform this scrolling gesture manually.

**Comment by ljzhangi** [comment]
@vmaxim 
The widget can be scrolled when I perform scrolling gesture manually.
And when I use TouchAction to perform this scrolling, it can be worked.

**Comment by mykola-mokhnach** [comment]
> And when I use TouchAction to perform this scrolling, it can be worked.

You means it works if you use TouchAction interface?

**Comment by vmaxim** [comment]
@ljzhangi Can you please provide video with the same (**per pixel precision**) gesture via TouchAction?

**Comment by ljzhangi** [comment]
@vmaxim 
I'm sorry, I reply late. You Can refer to this [TouchAction Screenrecord](https://github.com/ljzhangi/LaunchTimeTest/blob/master/filename_1520234969457.mp4)

**Comment by vmaxim** [comment]
1. App layout on second video differs from of the first one.
2. Gesture  on second video differs from of the first one.
