### ISSUE TITLE
Android App : uiscrollable not working on the dropdown list 

### ISSUE THREAD

**Issue by shagupta92042** [appium/appium#10280]
## Not able to scroll the dropdown list

I am automating an android app and i want to select the order type from the drop down list. I am using uiscrollable to scroll the drop down list but it does not scroll the list and select the order type whatever is visible in that window.

## Environment

java client build version or git revision if you use some shapshot: 5.0.0-BETA9
Appium server version or git revision if you use some shapshot: 1.8.0 beta3
Desktop OS/version used to run Appium if necessary: Widows 7
Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: 8.9.4
Mobile platform/version under test: Android 6.0
Real device or emulator/simulator: Motorola device

## Link to Appium logs

https://gist.github.com/shagupta92042/6817ff124ed634b31722ec5027927633

## Code To Reproduce Issue [ Good To Have ]

@FindBy(xpath = "//android.view.View[@text='Order Type']/following-sibling::android.view.View")
	public WebElement clickOrderType;

        wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//android.view.View[@index='6']")));
wait.until(ExpectedConditions.visibilityOfElementLocated(MobileBy.AndroidUIAutomator("new UiScrollable(new UiSelector()).scrollIntoView(new UiSelector().className(android.view.View).textContains(\"Limit FAK\"))"))).click();

![image](https://user-images.githubusercontent.com/18581259/36828205-57970382-1d3e-11e8-9ea3-ba66eceaed6b.png)
![image](https://user-images.githubusercontent.com/18581259/36828209-6357000a-1d3e-11e8-99b0-ba46a4d41469.png)

**Comment by mykola-mokhnach** [comment]
Is it a webview? These controls don't like like native

**Comment by shagupta92042** [comment]
@mykola-mokhnach : yes this is a webview (hybrid ) app.

**Comment by mykola-mokhnach** [comment]
Then you must switch to the webview and perform operations using chromedriver.

**Comment by shagupta92042** [comment]
we do not want to test it using chromedriver as we have developed this app so we are writing test cases for app only and everything is working fine but we are facing issue while scrolling. Please suggest the workaround for the same.

**Comment by mykola-mokhnach** [comment]
you could try to execute swipe up/down until the necessary item is shown. Such workaround would be  slow, but since you don't want to work with webviews then this will be the only option.

**Comment by shagupta92042** [comment]
thanks @mykola-mokhnach for quick response , can we scroll it using uiscrollable as mentioned above ? I believe swipe has been deprecated in appium java-client 5.0.0-BETA9 .

**Comment by shagupta92042** [comment]
@mykola-mokhnach : Thanks a lot ! Scroll is working fine with TouchAction class.
Hence , closing this defect.
