### ISSUE TITLE
App is just opening and closing when running through jenkins job

### ISSUE THREAD

**Issue by amitwagle** [appium/appium#10287]
## The problem

when I am running my appium scripts through jenkins job app is just opening and closing for each scripts but not executing any steps. However when i run locally my scripts then its executing properly.
I am executing the scripts on simulator.

## Environment

Appium version : 1.7.2
XCode : 9.2 
iPAD OS : 11.2.1
Mac OS : 10.13.1 (Mac OS High Sierra)
Node version : v9.3.0
Appium Desktop : 1.3.0
Appium.app

## Link to Appium logs
[Jenkins console log.txt](https://github.com/appium/appium/files/1772724/Jenkins.console.log.txt)

**Comment by mykola-mokhnach** [comment]
This looks like client version compatibility issue. What is the selenium api/hub version?

**Comment by amitwagle** [comment]
Thanks for the reply

Following is the selenium api version
version: '3.8.1'
compile group: 'org.seleniumhq.selenium', name: 'selenium-java', version: '3.8.1'
compile group: 'io.appium', name: 'java-client', version: '5.0.4'

**Comment by mykola-mokhnach** [comment]
Use the selenium client, which is bundled with the java client.

**Comment by amitwagle** [comment]
sorry, i didn't got how to use that. could you please elaborate more on this.

**Comment by mykola-mokhnach** [comment]
> compile group: 'org.seleniumhq.selenium', name: 'selenium-java', version: '3.8.1'

remove this dependency from your config

**Comment by amitwagle** [comment]
I tried removing the selenium-java dependency however scripts are getting compilation error

**Comment by mykola-mokhnach** [comment]
long story short: since selenium 3.7 the API slowly starts to enforce W3C mode for servers, so this is expected that one gets handshake exception if an older server version is used with a newer selenium API. Update both appium and java client to the recent BETA, so you'll be able to use Selenium API 3.9.1
