### ISSUE TITLE
Cant able to run two sever Appium server for running two simulators

### ISSUE THREAD

**Issue by Gamaiva** [appium/appium#10284]
## The problem
I am running two sever Appium server for running two simulators, So i could run on app on one simulator and one web app in another simulator using safari
 - First simulator launches successfully app gets installed and opening fine 
- But the second simulator opens safari open try to load URL and closes suddenly and opens again no action
 - if I run the one simulator its running fine opening browser properly

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS 10.13.3 
* Mobile platform/version under test: ios 11.2
* Real device or emulator/simulator:  simulator

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

[debug] [iOS] No reason to set locale
[debug] [iOS] Setting iOS and app preferences
[debug] [iOSSim] Checking whether simulator has been run before
[debug] [iOSSim] Simulator has not been run before
[debug] [iOS] No simulator directories found.
[debug] [iOSSim] Attempting to launch and quit the simulator, to create directory structure
[debug] [iOSSim] Will launch with Safari? true
[debug] [iOSSim] The count of running Simulator UI client instances is 1
[iOSSim] Booting Simulator with UDID BF549828-3E13-4274-B040-F6D0C615D6E5...
[iOSSim] Simulator with UDID BF549828-3E13-4274-B040-F6D0C615D6E5 booted in 57 seconds
[debug] [iOSSim] Safari has successfully opened 'http://www.appium.io' in 7 seconds
[debug] [iOSSim] Checking whether simulator has been run before
[debug] [iOSSim] Simulator has been run before
[debug] [iOS] Setting javascript window opening to 'false'
[debug] [iOS] Setting fraudulent website warning to 'false'
[debug] [iOSSim] Updating Safari user settings
[debug] [iOSSim] Checking whether simulator has been run before
[debug] [iOSSim] Simulator has been run before
[debug] [iOSSim] Building bundle path map
[debug] [iOS] Updated plist files, rebooting the simulator if it's already open
[debug] [iOS] Killing the simulator
[debug] [iOSSim] No Simulator cache items for cleanup were matched in '/Users/Hemanathan/Library/Developer/CoreSimulator/Devices/BF549828-3E13-4274-B040-F6D0C615D6E5/data/Library/Caches'
[debug] [iOSSim] Setting common Simulator preferences to {"ConnectHardwareKeyboard":false}
[debug] [iOSSim] Updated BF549828-3E13-4274-B040-F6D0C615D6E5 Simulator preferences at '/Users/Hemanathan/Library/Preferences/com.apple.iphonesimulator.plist' with {"ConnectHardwareKeyboard":false}
[debug] [iOSSim] The count of running Simulator UI client instances is 1
[iOSSim] Booting Simulator with UDID BF549828-3E13-4274-B040-F6D0C615D6E5...
[iOSSim] Simulator with UDID BF549828-3E13-4274-B040-F6D0C615D6E5 booted in 28 seconds
[debug] [BaseDriver] Event 'simStarted' logged at 1519893175727 (14:02:55 GMT+0530 (IST))
[debug] [XCUITest] Starting log capture for iOS Simulator with udid 'BF549828-3E13-4274-B040-F6D0C615D6E5', using 'xcrun simctl spawn BF549828-3E13-4274-B040-F6D0C615D6E5 log stream --style compact'
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1519893181348 (14:03:01 GMT+0530 (IST))
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Detected 1 obsolete cached process from previous WDA sessions. Cleaning up...
[XCUITest] Failed to kill obsolete cached process '15780'. Original error: 
    Error: Killing process 15780 failed:
        at Array.map (<anonymous>)
        at Promise.all.then (/usr/local/lib/node_modules/appium/node_modules/fkill/index.js:68:10)
        at <anonymous>
[debug] [XCUITest] Capability 'useNewWDA' set to true, so uninstalling WDA before proceeding
[XCUITest] Shutting down sub-processes
[debug] [XCUITest] Removing WDA application from device
[debug] [BaseDriver] Event 'wdaUninstalled' logged at 1519893184727 (14:03:04 GMT+0530 (IST))
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1519893184729 (14:03:04 GMT+0530 (IST))
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing running processes 'xcodebuild.*BF549828-3E13-4274-B040-F6D0C615D6E5, iproxy 8100, BF549828-3E13-4274-B040-F6D0C615D6E5.*XCTRunner' for the device BF549828-3E13-4274-B040-F6D0C615D6E5...
[debug] [XCUITest] 'pgrep -nif xcodebuild.*BF549828-3E13-4274-B040-F6D0C615D6E5' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] 'pgrep -nif iproxy 8100' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] 'pgrep -nif BF549828-3E13-4274-B040-F6D0C615D6E5.*XCTRunner' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] Using Xcode 9.2, so fixing WDA codebase
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=BF549828-3E13-4274-B040-F6D0C615D6E5 IPHONEOS_DEPLOYMENT_TARGET=11.2' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged. To see xcode logging, use 'showXcodeLog' desired capability
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"11.2\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"11.2\",\n      \"ip\" : \"192.168.1.43\"\n    },\n    \"build\" : {\n      \"time\" : \"Mar  1 2018 11:46:33\"\n    }\n  },\n  \"sessionId\" : \"30D20BEA-6570-420E-82C1-8A852713707E\",\n  \"status\" : 0\n}"
[debug] [XCUITest] WebDriverAgent running on ip '192.168.1.43'
[debug] [XCUITest] WebDriverAgent successfully started after 6393ms
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1519893191353 (14:03:11 GMT+0530 (IST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.apple.mobilesafari","arguments":["-u","http://127.0.0.1:4273/welcome"],"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[debug] [XCUITest] Log file for xcodebuild test: /var/folders/nf/kswfjp9j03q0qls9tjzhrls40000gp/T/com.apple.dt.XCTest/IDETestRunSession-2519422C-F42A-4A1C-A846-A104A220938B/WebDriverAgentRunner-8F7F1F21-E244-4DF1-8A8A-B50C3C2C68F6/Session-WebDriverAgentRunner-2018-03-01_140316-ElJC5d.log

## Code To Reproduce Issue [ Good To Have ]

@BeforeTest 
	//@Test (priority=1)
	public static IOSDriver<?> setUp() throws MalformedURLException {	

	 DesiredCapabilities capabilities = new DesiredCapabilities();
	 capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "");
	 capabilities.setCapability("automationName", "XCUITest");
	 capabilities.setCapability("xcodeSigningId", "iPhone Developer");
	 capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION,"11.2"); 
	 //capabilities.setCapability("realDeviceLogger","/usr/local/lib/node_modules/deviceconsole/deviceconsole");
	 capabilities.setCapability(MobileCapabilityType.DEVICE_NAME,"iPhone 6"); 
	 capabilities.setCapability(MobileCapabilityType.UDID,"9B431E88-55F2-46B9-BF09-A1247B9032C6");
	 capabilities.setCapability("useNewWDA","true");
	 capabilities.setCapability("clearSystemFiles", "true");
	 capabilities.setCapability(MobileCapabilityType.FULL_RESET, "true");
	 capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.IOS_XCUI_TEST);
     capabilities.setCapability("bootstrap","/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/" ); 
	capabilities.setCapability("agent", "/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj"); 
	 capabilities.setCapability(IOSMobileCapabilityType.LAUNCH_TIMEOUT,500000); 
	 capabilities.setCapability("app","/Users/Hemanathan/Documents/Appium/HappyFox Chat.app"); 
	 driver = new IOSDriver<WebElement>(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);
	 driver.manage().timeouts().implicitlyWait(15, TimeUnit.SECONDS); 
	 return driver; 
	 
}
	@BeforeTest
	  public static IOSDriver<?> setUp1() throws MalformedURLException, InterruptedException {

	 DesiredCapabilities capabilities1 = new DesiredCapabilities();
	 capabilities1.setCapability(MobileCapabilityType.BROWSER_NAME, "safari");
	 capabilities1.setCapability("automationName", "XCUITest");
	 capabilities1.setCapability("xcodeSigningId", "iPhone Developer");
	 capabilities1.setCapability(MobileCapabilityType.PLATFORM_VERSION,"11.2"); 
	 capabilities1.setCapability("realDeviceLogger","/usr/local/lib/node_modules/deviceconsole/deviceconsole");
	 capabilities1.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 6 Plus");
     capabilities1.setCapability(MobileCapabilityType.UDID,"BF549828-3E13-4274-B040-F6D0C615D6E5");
     capabilities1.setCapability("app", "io.appium.SafariLauncher");
     capabilities1.setCapability("autoWebview", "true");
     capabilities1.setCapability("enablePerformanceLogging", "true");
     capabilities1.setCapability("safariOpenLinksInBackground	", "true");
     capabilities1.setCapability("useNewWDA","true");
	 capabilities1.setCapability("clearSystemFiles", "true");
	 capabilities1.setCapability(MobileCapabilityType.FULL_RESET, "true");
	 capabilities1.setCapability("safariAllowPopups", false); 
	 capabilities1.setCapability("safariIgnoreFraudWarning", true);
	 capabilities1.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.IOS_XCUI_TEST);
	 capabilities1.setCapability("bootstrap","/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent" ); 
     capabilities1.setCapability("agent", "/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj"); 
     capabilities1.setCapability(IOSMobileCapabilityType.LAUNCH_TIMEOUT,500000); 
     //capabilities1.setCapability("app","/Users/Hemanathan/Documents/Appium/HappyFox Chat.app"); 
     URL url = new URL("http://127.0.0.1:4273/wd/hub");
     driver1 = new IOSDriver<IOSElement>(url, capabilities1);

     driver1.get("https://gamaivaboy.blogspot.in/");
     Thread.sleep(50000);
     System.out.println(driver.getPageSource());
	 driver1.manage().timeouts().implicitlyWait(15, TimeUnit.SECONDS); 
	 return driver1; 
	 
	}

**Comment by Gamaiva** [comment]
@sah @tanob @admc @hugs @tonetheman  
can anyone help me with this ??

**Comment by mykola-mokhnach** [comment]
You must set unique `wdaLocalPort` values for each device. Read https://github.com/appium/appium/blob/55760b7b9e1c494c6a1f22d152f0bd1fe676dae7/docs/en/advanced-concepts/parallel-tests.md for more details

**Comment by Gamaiva** [comment]
@mykola-mokhnach  i have another question  i am facing issue in opeing web url in mobile safari 
browser now.
my previous issue is fixed

**Comment by Gamaiva** [comment]
Can any one help me with this ?  @jlipps @mykola-mokhnach @imurchie

**Comment by mykola-mokhnach** [comment]
Sorry, this is not the place to ask questions. Please use Appium forum.

**Comment by Gamaiva** [comment]
@mykola-mokhnach  okay sorry can you send me the link of appium forum if possible

**Comment by mykola-mokhnach** [comment]
http://discuss.appium.io/

**Comment by nliz77** [comment]
Thz
