### ISSUE TITLE
WDA throwing exception when no alert is present

### ISSUE THREAD

**Issue by jamesvanhorn** [appium/appium#10286]
## The problem
Using ExpectedConditions.alertIsPresent() to process alerts on app launch. As of appium 1.7.2, GET alert/text throws an exception if there is no alert present. This prevents the code from working properly as we can never reach the set timeout due the WebDriverException thrown.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): I think 1.7.1. If not it was the previous release
* Desktop OS/version used to run Appium: Mac High Sierra
* Node.js version (unless using Appium.app|exe): 9.5.0
* Mobile platform/version under test: iOS 11.2.X
* Real device or emulator/simulator: Both
* Appium CLI or Appium.app|exe: Both

## Details

WDA pushing this issue back onto Appium. 
https://github.com/facebook/WebDriverAgent/issues/857

In the meantime I just put the code into a try/catch block, but its very messy as i essnetially have to code my own timer.

## Link to Appium logs

Pasting just a snippet here
```
[HTTP] --> GET /wd/hub/session/21fd42d2-155b-43c8-8fb1-5aa5e2f21350/alert_text {}
[debug] [MJSONWP] Calling AppiumDriver.getAlertText() with args: ["21fd42d2-155b-43c8-8fb1-5aa5e2f21350"]
[debug] [XCUITest] Executing command 'getAlertText'
[debug] [XCUITest] Setting custom timeout to 180000 ms for "getAlertText" command
[debug] [JSONWP Proxy] Proxying [GET /alert/text] to [GET http://localhost:8100/session/6B2E6ABD-FFCE-4FC2-96B7-93751C9E222D/alert/text] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n\n  },\n  \"sessionId\" : \"6B2E6ABD-FFCE-4FC2-96B7-93751C9E222D\",\n  \"status\" : 27\n}"
[MJSONWP] Encountered internal error running command: Error: An attempt was made to operate on a modal dialog when one was not open.
    at JWProxy.command$ (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:176:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
[HTTP] <-- GET /wd/hub/session/21fd42d2-155b-43c8-8fb1-5aa5e2f21350/alert_text 500 438 ms - 242
```

## Code To Reproduce Issue [ Good To Have ]

in Java, this will throw a WebDriverException every time it checks, instead of checking for the alert until finding one (or throwing a TimeoutException)
```
public static void main(String[] args) {
        //Driver was initialized and app is launched
        final WebDriverWait wait = new WebDriverWait(this.driver, 30);
        wait.until(ExpectedConditions.alertIsPresent());
}
```

**Comment by mykola-mokhnach** [comment]
Does this work in appium@beta?

**Comment by jazzpetzah** [comment]
I have troubles with alert detection as well with appium@1.7.2
Especially if it is an iOS system alert.

**Comment by jamesvanhorn** [comment]
Does not work in appium@beta either. @jazzpetzah the temporary fix is to wrap the ExpectedCondition in a try/catch like this
```
try {
    final WebDriverWait wait = new WebDriverWait(this.driver, 30);
    wait.until(ExpectedConditions.alertIsPresent());
} catch (final WebDriverException ex) {
    if (ex.getMessage().contains("An attempt was made to operate on a modal dialog when one was not open")) {
       //Figure out some logic to know when to exit
       //break;
    } else {
        throw ex;
    }
}
```
The timeout will never be reached if you catch the exception, so you need to implement some type of counter yourself to figure out when you want to exit. Then wrap all this in a while loop.

**Comment by mykola-mokhnach** [comment]
@dpgraham FYI

**Comment by mykola-mokhnach** [comment]
@jamesvanhorn Can you reinstall your beta and try again. The problem should be addressed now

**Comment by jamesvanhorn** [comment]
will do. thanks @mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
@derunewige Updating Appium does not update WDA binary on the device automatically.

**Comment by derunewige** [comment]
@mykola-mokhnach how can I update the WDA binary? I am using the simulator. Reinstalling WDA and deleting derived data didn't help

**Comment by mykola-mokhnach** [comment]
Then your problem is probably something different. It might be the alert is not shown or it is shown, but invoked by some system application and thus is not visible to XCTest.
