### ISSUE TITLE
[UiAutomator2] Unable to remove port forward

### ISSUE THREAD

**Issue by scalopus** [appium/appium#10285]
## The problem

After installation and run the test in IntelliJ, the Appium not success to run the test in the emulator

## Environment

* Appium version (or git revision) that exhibits the issue: **Appium.app 1.3.2 Appium 1.7.2**
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: **macOS 10**
* Node.js version (unless using Appium.app|exe): Using **Appium.app**
* Mobile platform/version under test: **Nexus 6 API 26**
* Real device or emulator/simulator: **Emulator**
* Appium CLI or Appium.app|exe: **Appium.app**

## Details
* Run the emulator from Android Studio - AVD Manager (Nexus 6 API 26)
* Run the Appium.app from Application.
* Run the test from IntelliJ

**Appium show the error log below**
[warn] [UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command '/Users/warun/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp\:8200' exited with code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''
[error] [MJSONWP] Encountered internal error running command: TypeError: Cannot create property 'replace' on boolean 'true'

## Link to Appium logs

Appium Log: https://gist.github.com/scalopus/fc7dd2282674f6315ff2a5f1804511fb
Adb Log: https://gist.github.com/scalopus/4141abecd11446b24e083ca45e497ae0

**Comment by mykola-mokhnach** [comment]
Known issue. Install appium with npm and do not use the one, which is bundled Appium Desktop.

**Comment by DavidGangel** [comment]
I'm having the same issue as described here. @mykola-mokhnach I don't really get your suggested solution.
Can you please explain?

**Comment by wigginsyuan** [comment]
@mykola-mokhnach I'm having the same issue as @scalopus .I install appium with nom.
Appium version: .1.7.1
now ,The problem is still unsolved。Please tell me why it is so, how to solve it?Thanks。
I've changed a lot of versions
@scalopus @DavidGangel Have you solved the problem?

**Comment by DavidGangel** [comment]
@wigginsyuan actually yes. The fresh version of Appium is working fine.
1.4.0
