### ISSUE TITLE
unable to install appium@1.7.2

### ISSUE THREAD

**Issue by wangtao169447** [appium/appium#10293]
## The problem

when i run command like this:npm uninstall -g appium && npm install -g appium@1.7.2 --no-shrinkwrap

which throw this kind of exception:

36056 verbose stack Error: appium-chromedriver@3.1.4 install: `node install-npm.js`
36056 verbose stack spawn ENOENT
36056 verbose stack     at ChildProcess.<anonymous> (/home/work/Monkey/node/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
36056 verbose stack     at emitTwo (events.js:126:13)
36056 verbose stack     at ChildProcess.emit (events.js:214:7)
36056 verbose stack     at maybeClose (internal/child_process.js:925:16)
36056 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
36057 verbose pkgid appium-chromedriver@3.1.4
36058 verbose cwd /home/work/Monkey
36059 verbose Linux 3.10.0_1-0-0-8
36060 verbose argv "/home/work/Monkey/node/bin/node" "/home/work/Monkey/node/bin/npm" "install" "-g" "appium"
36061 verbose node v8.9.4
36062 verbose npm  v5.6.0
36063 error file sh
36064 error code ELIFECYCLE
36065 error errno ENOENT
36066 error syscall spawn
36067 error appium-chromedriver@3.1.4 install: `node install-npm.js`
36067 error spawn ENOENT
36068 error Failed at the appium-chromedriver@3.1.4 install script.
36068 error This is probably not a problem with npm. There is likely additional logging output above.
36069 verbose exit [ 1, true ]

and i do not think this is same issue like #10020 #10225 

and here is command line print :
/home/work/node/bin/appium -> /home/work/node/lib/node_modules/appium/build/lib/main.js

> appium-chromedriver@3.3.0 install /home/work/node/lib/node_modules/appium/node_modules/appium-chromedriver
> node install-npm.js

sh: node: command not found
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/appium/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! appium-chromedriver@3.3.0 install: `node install-npm.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the appium-chromedriver@3.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-05T03_22_32_567Z-debug.log

## Environment

* Appium version (or git revision) that exhibits the issue:1.7.2
* Last Appium version that did not exhibit the issue (if applicable):None
* Desktop OS/version used to run Appium:Linux centos 6.5
* Node.js version (unless using Appium.app|exe):v8.9.4
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

@imurchie @mykola-mokhnach @jlipps   thanks for help

**Comment by mykola-mokhnach** [comment]
> sh: node: command not found

It looks like a problem with your local environment setup.

**Comment by wangtao169447** [comment]
@mykola-mokhnach  i can run command like this ：
node -v
npm -v，and i do not think it is local environment problem.

**Comment by wangtao169447** [comment]
@mykola-mokhnach 
i success install appium by command below:
npm install -g appium —unsafe-perm=true —allow-root

**Comment by Enelar** [comment]
reproduces for me @mykola-mokhnach

**Comment by dabat** [comment]
@imurchie i had the same issue. see my comment on #10020
