### ISSUE TITLE
Error after submitting the form using appium

### ISSUE THREAD

**Issue by thamizhkumarana** [appium/appium#10295]
## The problem

Error thrown when submitting the form of ios simulator in webview context using appium.

## Environment

* Appium version -1.7.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: mac searra
* Node.js version (unless using Appium.app|exe): v7.9.0
* Mobile platform/version under test: 10.3
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe:

## Details

I tried to fill the text box in ios simulator with webview context. After successful update of the field value i tried to click on the save button.

By the time i got the "Filed is required" error message. When i run the same test with android emulator i can able to submit the form successfully.

Can any one please advice me on this please.

**Comment by mykola-mokhnach** [comment]
Nothing we can do here without logs

**Comment by thamizhkumarana** [comment]
[appium.log](https://github.com/appium/appium/files/1780831/appium.log)
![56869b6b-f729-4e30-a12b-cd727c2b93e5](https://user-images.githubusercontent.com/31132017/36975862-7eb538ec-20a1-11e8-8b4a-05626a14535a.png)

**Comment by thamizhkumarana** [comment]
please find the screenshot for your reference

**Comment by mykola-mokhnach** [comment]
Try to add more debug logging into your web page to see why it complains and which fields are expected to be set. Perhaps, the "standard" way of how IWDP does it does not work for it and you need to do it via JavaScript.
