### ISSUE TITLE
Storing clipboard text in a string variable

### ISSUE THREAD

**Issue by JeevaTamil** [appium/appium#10290]
## The problem
I need to get clipboard text and assign the value to a string variable.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.7.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac/Sierra 10.12.6
* Node.js version (unless using Appium.app|exe): 
* Mobile platform/version under test: iOS/11.2.6
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium.app

## Details

I am automating an authentication application(like Google Authenticator). The app will generate a unique verification code when user trying to log-in. That verification code element is displaying all attributes as **"CODE"** in appium inspector. So, I'm unable to get the value. Only solution is if I tap the code it will store in clipboard. I need the value from clipboard. **ANY SOLUTION????**

**Comment by mykola-mokhnach** [comment]
long tap any text edit in your application under test, click paste and then remember its text. Apple does not provide any primitives to access the clipboard context on real devices
