### ISSUE TITLE
Issue with finger print on android emulator

### ISSUE THREAD

**Issue by thomasEffberger** [appium/appium#10296]
## The problem

Fingerprint call on emulator session ends with server error "finger print is only available for emulators".
Is it necessary to mark a session as "emulator-session", maybe? I'm not starting the emulator with appium. It is already running before the session is initiated.

## Environment

* Appium version 1.8.0-beta3
* Desktop OS/version used to run Appium: Mac OS 10.13.3
* Node.js version 8.2.1
* Mobile platform: Android 8.1
* Real device or emulator:
* Appium-Java-Client  6.0.0-BETA3
* Grid-Setup with Selenium Grid 3.4.0

## Details

I'm trying to automate tests for an app using fingerprint authentication. I'm navigating to the fingerprint authentication step and then I run in the server error. I'm calling the AndroidDriver method "fingerPrint" with input parameter "1". Before I initialized the fingerprint No. 1 authentication for the emulator.

## Link to Appium logs

https://gist.github.com/thomasEffberger/48e44640b220b017811d1dab6713ee1d

**Comment by mykola-mokhnach** [comment]
Try to set `avd` capability

**Comment by thomasEffberger** [comment]
it works, when appium starts the emulator once. Thx
