### ISSUE TITLE
iOS 11.2 Works with Appium 1.7.2?

### ISSUE THREAD

**Issue by MathuMarques** [appium/appium#10291]
Hey there  I want to know if anybody already test iOS 11.2 with appium, i think this might be a issue for me, I already have done all the configurations that its possible, search all the forum around and i didn't see anybody using iOS 11.2 real device with appium.

**Comment by mykola-mokhnach** [comment]
yes it works

**Comment by MathuMarques** [comment]
Thanks!

**Comment by tfcardoso** [comment]
@MathuMarques You might want to apply this fix:
https://github.com/appium/WebDriverAgent/pull/46

Or just use appium 1.8 beta
