### ISSUE TITLE
Unable to inspect elements in iOS using Appium Inspector, after implementing cordova plugin 

### ISSUE THREAD

**Issue by dineshkumarskr** [appium/appium#10297]
## The problem

Unable to inspect elements in iOS using Appium Inspector, after implementing cordova plugin . When we try to inspect element, the whole screen gets highlighted instead of the particular element. Previously before implementation of Cordova, we could able to inspect and perform the automation using Selenium. 

But the same app, we could able to verify in the Android version. Hence we would like to know is there something we need to add from our end? or else the is that something/some flag that developer needs to ensure while developing the iOS app?

## Environment

* Appium version (or git revision) that exhibits the issue: V1.2.7
* Desktop OS/version used to run Appium: MAC OS 10.12 and Windows 7
* Mobile platform/version under test: iOS 11.2
* Real device or emulator/simulator: Xcode Simulator & Sauce labs simulator

**Comment by mykola-mokhnach** [comment]
Appium inspector is not designed to inspect web views. You could use Safari remote debugger for such purpose.
