### ISSUE TITLE
IOS App crash upon launch on appium 1.7.2 whereas runs fine on versions 1.6.5, 1.7.0, 1.7.1

### ISSUE THREAD

**Issue by gcsharathbabu** [appium/appium#10294]
## The problem

App crashes upon launch via appium 1.7.2. Here, initially, the app is installed followed by webDriverAgent. WDA will open and close followed by the app launch, where the splash screen shows up for few seconds and close. This issue is specific to 1.7.2 whereas works fine with the earlier versions.

## Environment

* Appium version that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue: 1.6.5, 1.7.0, 1.7.1
* Desktop OS/version used to run Appium: Mac OS sierra
* Node.js version (unless using Appium.app|exe): v9.4.0
* Mobile platform/version under test: iPod 9.3.3 & iPad pro 10.2
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

https://gist.github.com/gcsharathbabu/79451fef2e9aabeb4b2f3dd1f671ab7c

**Comment by mykola-mokhnach** [comment]
I have no idea about the crash might be related to WDA version. What your developers say about the stacktrace?

**Comment by gcsharathbabu** [comment]
The error doesn't occur while running it via dev setup or either the earlier versions of appium itself. So, they are unsure about the triggers leading to this crash. However, I'm curious to know what changed in 1.7.2 to cause such a crash. Anything particular hooks during the launch time? And also, Am I alone struck with this?

**Comment by mykola-mokhnach** [comment]
I'd rather add more debug logging into the app under test to see why the value turns into nil. I have doubts we can help here somehow without knowing the problem source. And it is impossible to know it without having application's source code.

**Comment by gcsharathbabu** [comment]
I'd like to focus more on what changed in 1.7.2. As there isn't an issue with the earlier versions. Would there be changes around how the app is launched? Has there been a change how it is invoked in comparison with earlier WDA version/s?

**Comment by mykola-mokhnach** [comment]
WebDriverAgent is a third-party component. I think we will not be able to help you much on it, however you could still track the diff between version tags in github.
