### ISSUE TITLE
Trouble while try to run Appium Desktop

### ISSUE THREAD

**Issue by MathuMarques** [appium/appium#10303]
There is a error in my Appium desktop that I can't fixed, I'm able to run Appium in command line, but i want to open desktop Appium to inspect the app XPath and this kind of stuff. There is anyone else that know whats is happening?

**Comment by mykola-mokhnach** [comment]
Appium desktop has its own issue tracker at https://github.com/appium/appium-desktop/issues

If this is not an issue, but a question, then please use Appium forum.
