### ISSUE TITLE
Expiry date field not filling with forward slash in Android Native app

### ISSUE THREAD

**Issue by HemaSundarPenugonda** [appium/appium#10307]
## The problem

I am trying to enter Expiry date (eg: 01/21) field in android native app using appium. 
When you fill the field manually, User don't need to enter '/'. It will get filled automatically. But when i am entering (Eg: keys sent "0121") it using appium, '/' is not auto filled. 

**Note:** '/' is auto filled in case of iOS with Appium (Eg: keys sent "0121").

## Environment

* Appium version (or git revision) that exhibits the issue: 5.0.4
* Desktop OS/version used to run Appium: 1.4.0 (Desktop version)
* Mobile platform/version under test: Android / 7.0
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: Appium.app (MAC)
* Development code: ReactJS

## Details

For expiry date field, when i sent the keys as "0121":
* **Android:** text box is filled as "0121"
* **IOS:** text box is filled as "01/21"

## Link to Appium logs

https://gist.github.com/HemaSundarPenugonda/7c705adb89e2973628a0877a09d6af1c

**Comment by trix0** [comment]
Hey mate, https://github.com/webdriverio/webdriverio/issues/2608 look in here or here is my code

function fnWriteValue(client,value,expectedValue,repeats,selector){
iCounter=0;
let write= ()=> fnWriteValueOnce(client,value,expectedValue,selector).catch(err=>{
  console.log(err);
  iCounter++;
  if(iCounter==repeats){
    logger.info("Could not write correct Value" + value)
    return Promise.reject("Could not write correct Value")
  }
  return write();
});
return write();
}



async function fnWriteValueOnce(client,value,expectedValue,selector){
  if(selector===undefined){
    selector="android=new UiSelector().className(\"android.widget.EditText\")";
   
  }
  await client.keys(value);
  return client.getText(selector).then(data=>{

    if(!expectedValue.test(data)){
      logger.info("Value is not correct -> repeating")
      throw new Error("Value is not correct")
    }
    return(true); 
})

**Comment by mykola-mokhnach** [comment]
Use uiatomator2 backend for Android 6+

**Comment by HemaSundarPenugonda** [comment]
@mykola-mokhnach I tried with UiAutomator2, but same behaviour as of UiAutomator.

**Comment by mykola-mokhnach** [comment]
do you have logs? have you also tried appium@beta?

**Comment by HemaSundarPenugonda** [comment]
Yeah, tried with latest beta as well, same behaviour.
Which logs? Appium logs link is mentioned in the issue description.

**Comment by mykola-mokhnach** [comment]
I need logs for the case where automationName is set to uiautomator2

**Comment by trix0** [comment]
https://www.youtube.com/watch?v=vq41sTVmnFI&feature=youtu.be&t=13s    I think this is what is happening mykola you can see on my date the - are inserted automatically but I am not sure whats the bug. It might be that it writes the keys too fast that it just wont process -

**Comment by HemaSundarPenugonda** [comment]
@mykola-mokhnach Please find the below Appium logs with UiAutomator2:
https://gist.github.com/HemaSundarPenugonda/6fdaf6dbdf3d56248919d12a88e8c4eb

**Comment by mykola-mokhnach** [comment]
What if you try to enter chars one after another with a delay between them?

**Comment by HemaSundarPenugonda** [comment]
@mykola-mokhnach When i am doing with setKeys method by having some delay, It worked fine.

Thank you :)
