### ISSUE TITLE
Unable to view elements using Appium Desktop Inspector for iOS 11 device. 

### ISSUE THREAD

**Issue by jjceball** [appium/appium#10304]
## The problem

Currently have Appium Desktop installed on iMac, version 1.4.0. When using the inspector on iPhone 7, iOS 11.2.5 device, the inspector fails with the following error:

An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: "Command 'Scripts/bootstrap.sh -d' exited with code 1". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.

I do not have an issue with seeing elements on iPhone 7, iOS 10 device. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.4.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: MacOS High Sierra, Version 10.13.3
* Node.js version (unless using Appium.app|exe): N/A
* Mobile platform/version under test: iOS 11.2.5
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium.app

## Details

N/A

## Link to Appium logs

https://gist.github.com/jjceball/82b13b8a039511b3a133429037620099

## Code To Reproduce Issue [ Good To Have ]

No code expected for issue.

**Comment by mykola-mokhnach** [comment]
You must configure WebDriverAgent source properly to be able to run Appium on real devices. Closed as duplicate
