### ISSUE TITLE
Impossible to find element inside element of list

### ISSUE THREAD

**Issue by Biloleg** [appium/appium#10306]
## The problem
If you try to findElement inside one of element in list you will get not such element exception.
For example next code work on 1.7.1 server but doesn't work on 1.7.2:
driver.findElementsById("{some containers id}").get(0).findElement(By.id("{some element inside container}"))
Note: reproduce on iOS only

## Environment

* Appium version (or git revision) that exhibits the issue: 1.4.0 (1.3.x also)
* Last Appium version that did not exhibit the issue (if applicable): 1.2.7
* Desktop OS/version used to run Appium: MacOS 10.13.3
* Node.js version (unless using Appium.app|exe): using Appium.app
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: real
* Appium CLI or Appium.app|exe: Appium.app

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
https://gist.github.com/Biloleg/a4e35b574de71f754c6907e4904ad361

## Code To Reproduce Issue [ Good To Have ]

driver.findElementsById("GSLOfferOverviewCell").get(1).findElement(By.id("GSLOfferOverviewCellTitleLabel")).getText()

Note: List contains 5 elements

**Comment by mykola-mokhnach** [comment]
This should be addressed in the recent appium@beta

**Comment by Biloleg** [comment]
Hello.

 

Are you readdressed this issue to relevant person? Is this issue will be fixed?

 

Thanks.
