### ISSUE TITLE
"Cannot read property 'major' of null" with Appium v1.8.0-beta 3

### ISSUE THREAD

**Issue by appiumnovice** [appium/appium#10300]
## The problem

When I run test on iOS simulator with Appium 1.8.0 Beta 3, I obtain the error message "Cannot read property 'major' of null".
No error with the same configuration on Appium 1.7.2

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0-beta3
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2
* Desktop OS/version used to run Appium: MacOS Sierra 10.12.6
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iPhone 8 with iOS 11.2 
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/appiumnovice/92b9f629e34b3b22fe8dd078955b416d

## Code To Reproduce Issue [ Good To Have ]

Just run the test.

**Comment by mykola-mokhnach** [comment]
Remove `deviceName`capability and set the `udid` as a workaround.

**Comment by appiumnovice** [comment]
The workaround doesn't seem to work.
When I add "udid", I obtain the same error message "Cannot read property 'major' of 'null'".
And when I use only the capability "udid", I get the error message " 'deviceName' can't be blank"

**Comment by mykola-mokhnach** [comment]
You can set device name to simply `iPhone` when you have udid

**Comment by reachbharathan** [comment]
Facing the same problem, Tried mentioning only udid then combined udid and devicename attribute

**Comment by picklelv** [comment]
We are running into the same issue and `udid` solved the problem.  This is just a workaround right?

**Comment by mykola-mokhnach** [comment]
The new fixed driver version has been published.
