### ISSUE TITLE
Unable to Click/Interact with element in web view in ios 11 hybrid app with Appium

### ISSUE THREAD

**Issue by Pria2811** [appium/appium#10305]
I switched to web view successfully on iOS hybrid app with Appium and Appium was able to find the element in web view with xpath but cannot click on the element . send keys are also not working with text-box control

##Environment

* Appium version : 1.7
* Node.js version :6.11.3
* Mobile platform/version under test : IOS 11
* Real device or emulator/simulator: Real Device
* Hybrid App

The following is the desired capabilities that I have used:
DesiredCapabilities cap = new DesiredCapabilities();
capabilities.setCapability("deviceName", "XXX");
capabilities.setCapability("platformVersion", "11.2");
capabilities.setCapability("wdaLocalPort", "8200");
capabilities.setCapability("startIWDP", "true");
capabilities.setCapability("webkitDebugProxyPort", "27753");
capabilities.setCapability("webkitResponseTimeout", "50000");
capabilities.setCapability("bundleId", "XXX");
capabilities.setCapability("automationName", "XCUITest");

##Link to Appium Logs:

https://gist.github.com/Pria2811/2974a12fc18bd90e9837b8a8bec2f827

## Code To Reproduce Issue [ Good To Have ]
driver = new IOSdriver<MobileElement>(new Url("https://XXXX//wd/hub"),capabilities);
Set<String> handles = driver.getContextHandles();
for(String contextName :contextHandles)
{
    if(contextName.equalsIgnoreCase("Native"))
      {
          // do nothing
       }
   else {
    driver.context(contextName);
     }
}
MobileElement ele = driver.findElement(By.Xpath(""));
if(ele.isDisplayed()) // gives true 
{
ele.sendkeys("");  // nothing happens , even at ele.click();
}

// do not by the syntax errors or closing brackets 
In Appium logs I can see that element is found but when it comes to interaction with element (either  element.click() or javascript command ) nothing happens

**Comment by Pria2811** [comment]
I am using safari remote debugging only to view the Dom and can easily see the element . I am not using Appium Desktop. I request to please read the problem and study logs attached before closing issue immediately .

**Comment by mykola-mokhnach** [comment]
I don't observe any explicit issues in the log. This looks more like IWDP issue or a problem with the webview itself. You can try to set values with raw javascript as a workaround

**Comment by Pria2811** [comment]
hi, I started IWDP manually on Mac and things started working good . Need to know why Appium suggests that in 1.7 we can give the startIWDP as true in capabilities and it will start the proxy on Mac .

**Comment by mykola-mokhnach** [comment]
Appium just starts the IWDP binary, which is present in the default PATH. Perhaps, that one is out of date.
