### ISSUE TITLE
Unable to click on the dropdown in web view of iOS 11 with Appium 

### ISSUE THREAD

**Issue by Pria2811** [appium/appium#10317]
## The problem

In the web view context on iOS 11 hybrid app Appium is able to locate the dropdown element with path but cannot click. All other elements are clicked /interacted with successfully

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7
* Node.js version (unless using Appium.app|exe): 6.11.3
* Mobile platform/version under test: iOS 11
* Real device or emulator/simulator: Real device 

## Details

According to Appium logs it is able to locate the element by path and element.isdisplayed is giving true . All other elements are getting clicked except dropdown (so I guess not a problem with IWDP). But on doing element.click Appium results null and I can't see click action on dropdown.

## Link to Appium logs
https://gist.github.com/Pria2811/4da33c667be610ef0bfa20315b8d6101

## Code To Reproduce Issue [ Good To Have ]

MobileElement element = driver.findElement(By.xpath());
if(element.isDisplayed)
{ element.click();
}

**Comment by qatesting30** [comment]
I am facing the sam problem. Any help will be highly appreciated.

**Comment by rajvinodh** [comment]
I am also facing the same issue.
When ever we call isDisplayed() for Native view elements which is visible, it returns true.
But while calling isDisplayed() for Web view elements which is visible, it returns false.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
