### ISSUE TITLE
Unable to execute on real device; Inconsistent facing [MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by Rakeshsp05** [appium/appium#10318]
## The problem

I am facing the error when I am running the scripts on a real device. The same is observed with other team members. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2 ; 1.8.0beta3 ; Appium destop
* Mobile platform/version under test: Android 
* Real device or emulator/simulator: One plus 3t

## Details

We don't receive any error. it hangs for a long time and gives ESOCKETTIMEDOUT error.
## Link to Appium logs

https://gist.github.com/Rakeshsp05/8aaffbeea974082c4d17178f83737e3e.js

**Comment by Rakeshsp05** [comment]
What would be the solution for this?
any Suggestions

**Comment by mykola-mokhnach** [comment]
There is no quick solution. Investigate the device logs, try to reboot the device under test from time to time to avoid resource leaks.
