### ISSUE TITLE
zoom is not working in appium ios 

### ISSUE THREAD

**Issue by ygsf** [appium/appium#10315]
## The problem

I upgraded appium 1.5.3 to 1.7.2 Some of the tests zooming a map in the application. The code that was working in 1.5.3 is:
```
        Dimension size = driver.manage().window().getSize();
        int x =  (size.getWidth()  / 3 );
        int y =  (size.getHeight() / 4 );
        try {
                Thread.sleep(1500);
                driver.zoom(x,y);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        return this;

```
Then I created a code that implement zoom functionality:
```
TouchAction action1 = new TouchAction(driver).press(100,100).moveTo(0,-50).release();
TouchAction acction2 = new TouchAction(driver).press(100,100).moveTo(0,50).release();
MultiTouchAction mta = new MultiTouchAction(driver);
mta.add(action1).add(acction2);
mta.perform();
```
I found that it fails on perform() method. It gets 501 error from WDA.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): 1.5.3 (Not sure if it is last)
* Desktop OS/version used to run Appium: MAC
* Node.js version (unless using Appium.app|exe): NA
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator: Emulator of iPhone 7 Plus

**Comment by mykola-mokhnach** [comment]
Try it with appium@beta or change to [mobile: pinch](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios/ios-xctest-mobile-gestures.md) call

**Comment by ygsf** [comment]
Sorry for late response but the problem is not resolved yet. I tried pinch as below:
    public void zoomTest(RemoteWebElement element){
        // Java
        JavascriptExecutor js = (JavascriptExecutor) driver;
        Map<String, Object> params = new HashMap<>();
        params.put("scale", 0.5);
        params.put("velocity", 1.1);
        params.put("element", ((RemoteWebElement) element).getId());
        js.executeScript("mobile: pinch", params);
    }

However I got following error in the log file of appium server:
[HTTP] --> POST /wd/hub/session/38d54bf9-f6a1-472d-ad1c-c88adb01b001/execute {"script":"mobile: pinch","args":[{"scale":0.5,"velocity":1.1,"element":"0B1A6D2E-D96B-4F49-8783-71D08BC1DE06"}]}
[MJSONWP] Calling AppiumDriver.execute() with args: ["mobile: pinch",[{"scale":0.5,"velocity":1.1,"element":"0B1A6D2E-D96B-4F49-8783-71D08BC1DE06"}],"38d54bf9-f6a1-472d-ad1c-c88adb01b001"]
[XCUITest] Executing command 'execute'
[JSONWP Proxy] Proxying [POST /wda/element/0B1A6D2E-D96B-4F49-8783-71D08BC1DE06/pinch] to [POST http://localhost:8100/session/DC6833BC-DD15-429E-ABD1-3896C39D4720/wda/element/0B1A6D2E-D96B-4F49-8783-71D08BC1DE06/pinch] with body: {"scale":0.5,"velocity":1.1}
[JSONWP Proxy] Got response with status 200: {"value":"velocity must be less than zero when scale is less than 1\n\n(\n\t0   CoreFoundation                      0x00000001081d7d4b __exceptionPreprocess + 171\n\t1   libobjc.A.dylib                     0x0000000107c3921e objc_exception_throw + 48\n\t2   CoreFoundation                      0x00000001082412b5 +[NSException raise:format:] + 197\n\t3   XCTest                              0x000000010765b32b -[XCUIElement(XCUIElementTouchEvents) pinchWithScale:velocity:] + 263\n\t4   WebDriverAgentLib                   0x0000000115ec474a +[FBElementCommands handlePinch:] + 538\n\t5   WebDriverAgentLib                   0x0000000115e9e053 -[FBRoute_TargetAction mountRequest:intoResponse:] + 179\n\t6   WebDriverAgentLib                   0x0000000115e901b4 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 548\n\t7   RoutingHTTPServer                   0x0000000115f5bc18 -[RoutingHTTPServer handleRoute:withRequest:response:] + 136\n\t8   RoutingHTTPServer                   0x0000000115f5c4fa __72-[Routin...
[MJSONWP] Encountered internal error running command: Error: An unknown server-side error occurred while processing the command.
    at JWProxy.command$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:176:15)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at

**Comment by mykola-mokhnach** [comment]
> velocity must be less than zero when scale is less than 1

Did you see the error message though?

**Comment by ygsf** [comment]
Nope. I missed it. Let me try it.

**Comment by ygsf** [comment]
Thanks for pointing me to the message. When I tried with negative velocity it returns no error. But it do nothing. 
May it be because of the element that I sent to the zoom? What is the purpose of the element? I am zooming a google map. I expect entire map with many elements on it to be zoomed, not only one element.

**Comment by mykola-mokhnach** [comment]
> May it be because of the element that I sent to the zoom

Most likely. Try to send the command to one of the parent containers instead. I don't think one can help you there much.

**Comment by ygsf** [comment]
I found that WDA web service works  it works with soom in, but it does not work with soom out. When I directrly call web service http://localhost:8100/session/CDB13B26-309D-459E-AB0D-2FE71A988138/wda/element/48810473-B36E-425D-B65A-98AA45A6506E/pinch 
with `{"scale":6,"velocity":2}` it works. 
However, when I zoom out with `{"scale":0.5,"velocity":-2}` it does not.

**Comment by mykola-mokhnach** [comment]
It might be XCTest issue, which should be reported to Apple. Have you tried touch actions in appium@beta?

**Comment by hienphan1472** [comment]
Is there anything new with this? 
I'm still in trouble when using scale from 0 to 1 (zoom out)

String targetElement = ((RemoteWebElement) webElement).getId();
Map<String, Object> pinchObject = new HashMap<>();
pinchObject.put("element", targetElement);
pinchObject.put("scale", 0.5);
pinchObject.put("velocity", -2);
Driver.getDriver().executeScript("mobile: pinch", pinchObject);

-> it seems that the driver just tries to pan the map (to the right bottom) instead of zooming out

Note:
- Zoom in works perfectly
- Appium -v: 1.8.1

**Comment by izik461** [comment]
Hi I am struggling with the same issue. Do you know any solution? Why does was this issue closed?
