### ISSUE TITLE
Appium use an adb server that is not running on the default port 5037?

### ISSUE THREAD

**Issue by kadir-calvid** [appium/appium#10312]
## The problem

I am trying to run a test on a remote server, using Jenkins to start the tests; but the adb does not take the default port, it usually takes a **random port.** But appium is not able to find the device because it forces to look an adb running on the default port (5037).

## Environment

* Appium version :1.7.2
* Desktop OS/version used to run Appium: Ubuntu
* Node.js version : 9.5
* Mobile platform/version under test: Android
* Real device or emulator/simulator: emulator

## Details
I found only solution to set adbPort in appium capabitilies but how can set random generated port on 
adbPort in test script?

Any solution would be appreciated.
Thanks

**Comment by mykola-mokhnach** [comment]
Try to set `ANDROID_ADB_SERVER_PORT` environment variable

**Comment by kadir-calvid** [comment]
@mykola-mokhnach can you tell me where i have to set this variable, mean which location n which format?
any sample or screen shot would be helpfull for me
Thanks

**Comment by mykola-mokhnach** [comment]
https://stackoverflow.com/questions/3836571/changing-default-port-i-e-5037-on-which-adb-server-runs

**Comment by kadir-calvid** [comment]
I have tried this before but not working still adb server running on 5855 port.
------following logs-----
[android] Using Android SDK: /var/lib/jenkins/tools/android-sdk
$ /var/lib/jenkins/tools/android-sdk/platform-tools/adb start-server
* daemon not running; starting now at tcp:5855
* daemon started successfully
