### ISSUE TITLE
Couldn't swipe and setContext in C#

### ISSUE THREAD

**Issue by xbotest** [appium/appium#10316]
## The problem

C# codes, doesn't have setContext method. Also using Swipe or TouchAction, always got "Method has not yet been implemented" error. What's the problem? How can I solve these problems?

## Environment

* Appium version 1.7.2
* Desktop OS/version used to run Appium: 1.4.1
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Real device Samsung S6
* Chrome 52, chromedriver 2.2.0

## Details

1. Couldn't set and switch contexts in C#, didn't find any useful method. How can I do that?
2. Couldn't scroll screen, TouchAction/Swipe doesn't work, report "Method has not yet been implemented" error. Any solution?

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/appium/appium-dotnet-driver

**Comment by xbotest** [comment]
It doesn't work.

**Comment by xbotest** [comment]
Do you have verified that before closing?

**Comment by mykola-mokhnach** [comment]
> Do you have verified that before closing?

WDYM?

**Comment by xbotest** [comment]
I couldn't understand why this issue was closed directly when I always got the problems.

**Comment by xbotest** [comment]
Do you think this is the driver issue, and not the appium issue?
