### ISSUE TITLE
Unable to run test after application launch - Android 7

### ISSUE THREAD

**Issue by kumarlead** [appium/appium#10328]
## The problem

Hi I am new to Appium. I am trying to set value into a text box for a native app which is already installed in my device. When I run the test it launch the app but no actions are performed on it. Similar code worked on launch and perform actions on Google Play Store but it's not working on our corporate apps.
Any suggestion please. 

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.7.2
* Desktop OS/version used to run Appium: Windows 7
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Real device (Samsung Galaxy S6)
* Appium CLI or Appium.app|exe: Appium.exe

## Link to Appium logs

https://gist.github.com/kumarlead/5fce7585b0ab2b928165e4a44a7babb0

## Code To Reproduce Issue [ Good To Have ]

package Tests;
 
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.support.ui.WebDriverWait;

import io.appium.java_client.AppiumDriver;
import io.appium.java_client.MobileElement;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.touch.WaitOptions;
 
public class LaunchPasswordManager {
	
	public static void main(String[] args) throws MalformedURLException {
		
		//Set the Desired Capabilities
		DesiredCapabilities caps = new DesiredCapabilities();
		caps.setCapability("deviceName", "My Phone");
		caps.setCapability("udid", "03157df342d3d21e"); //Give Device ID of your mobile phone
		caps.setCapability("platformName", "Android");
		caps.setCapability("platformVersion", "7.0");
		caps.setCapability("appPackage", "com.micron.pmanager");
		caps.setCapability("appActivity", "com.micron.pmanager.MainActivity");
		caps.setCapability("noReset", "true");
		

		
		AppiumDriver<MobileElement> driver = new AndroidDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"), caps);
	
driver.manage().timeouts().implicitlyWait(200,TimeUnit.SECONDS);
		
		driver.findElementByXPath("//android.widget.EditText[@text='Username']").sendKeys("tusercr115");

	}
 
}

**Comment by mykola-mokhnach** [comment]
Use use uiatomator2 backend for Android 6+

**Comment by kumarlead** [comment]
@mykola-mokhnach   Thanks for your quick response.
It did work only once when added 		caps.setCapability("AutomationName", "UiAutomator2");
I tried restart Appium server, but it didn't work.

**Comment by dmlemeshko** [comment]
@kumarlead How about change strict `=` with `contains` on locator. I think it is not working because of incorrect locator, not appium server/client issue. Xpath is evil :)

**Comment by kumarlead** [comment]
@dmlemeshko Even resource id not working
driver.findElementById("tab-t0-1").click();
All this work fine first time, they are not working from second test run. I suspect my tests not stopping the server properly or I didn't configure uiautomator2 currently.
If someone can share how to use "uiautomator2" in detail will be really appreciated?

**Comment by mykola-mokhnach** [comment]
AutomationName -> automationName

**Comment by kumarlead** [comment]
Working perfectly, thank you much.
