### ISSUE TITLE
App got stopped (crashed) when interacting it via Appium Desktop

### ISSUE THREAD

**Issue by xiexu2008** [appium/appium#10322]
## The problem

I was trying to automate a 3rd-party app on an Android emulator. The app was working well when I manually manipulated it on the emulator. It got crashed when doing it via Appium Desktop.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android Goolge APIs 27
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: CLI

## Details

As shown in this [video](https://youtu.be/SXOTDuDIabw), I manually opened the App on the Android emulator, and then navigated to a signing page. Then I clicked the 'SIGN' button and was able to do some signing. It was working all well. Then I tried to do the signing via Appium Desktop. The app somehow got stopped when it navigated me to the signing page. The crash is reproducible.

## Link to Appium logs

[Appium Server logs](https://gist.github.com/xiexu2008/ad75a0362d152c2c76f61f00c8df31df)

[APP apk file](https://www.dropbox.com/s/7apnhk0d3141ko2/ClinipadSoei_20180212.zip?dl=0)

## Code To Reproduce Issue [ Good To Have ]

Capabilities:

{
  "deviceName": "Nexus 9 API 27",
  "platformName": "Android",
  "app": "ClinipadSoei_20180212.apk",
  "automationName": "uiautomator2"
}

**Comment by mykola-mokhnach** [comment]
I don't observe any anomalies in the attached log. Try to check the adb logcat output.
