### ISSUE TITLE
click a text input field on a webview page will actually click the location a little bit upper on ios

### ISSUE THREAD

**Issue by helenren** [appium/appium#10323]
## The problem

if click an element located at the lower bottom of a webview page (it is in the view for sure) of a ios hybrid app, will actually click the place a little bit higher. 

<img width="460" alt="screen shot 2018-03-08 at 5 17 19 pm" src="https://user-images.githubusercontent.com/10765688/37185341-b5078b8e-22f4-11e8-8d2b-ed717fc08620.png">

Like the attached screen, my test is trying to click the Case Origin test field, turns out actually click on the Type Field, even the Case Origin textinput element has been found correctly. If I move that element to the top, or at least around the middle of a screen, then will click that item correctly. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: OS 10.13
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iphone, ios 11.2
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: 

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by helenren** [comment]
we hit is with our hybrid application.

**Comment by helenren** [comment]
aware any issue related?

**Comment by mykola-mokhnach** [comment]
Closed as inactive
