### ISSUE TITLE
Add deep linking to Android automation

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#10329]
* Expose [startUri method](https://github.com/appium/appium-adb/blob/c8d547ed2c1032aba1e8041e7c2e9feabe2e3915/lib/tools/apk-utils.js#L32) as a command
* Need to either edit [setUrl](https://github.com/appium/appium-base-driver/blob/c679d534e4bba3c1d2728bf69b1b8d46b10713e5/lib/protocol/routes.js#L63) to accept package as a parameter or make a new command that sets url and package
* I think we _could_ also edit Android [setUrl](https://github.com/appium/appium-android-driver/blob/5bc5bc2cddf0bb959d923593fed4711cff34639b/lib/commands/general.js#L213) to accept a semi-colon separated string like `<url>;<package>` so that the fix would be backwards compatible with all the clients

**Comment by imurchie** [comment]
Investigate where this should go (startApp? startActivity? executeScript mobile: space?

**Comment by dpgraham** [comment]
This is done and will be in the next version.

I've added a `mobile:` command that does this

Here's a sample Gist: https://gist.github.com/dpgraham/698b464a4cef376d6c2c93f0fdb00169

**Comment by PrasadMadge** [comment]
Hi Appium team,

How to use deep link for an native android app? 

`driver.execute("mobile: deepLink", {url: 'https://www.realtor.com/realestateandhomes-search/San-Jose_CA', package: 'com.move.realtor'});`

From where I will get URL for my native apps ?

**Comment by dpgraham** [comment]
@PrasadMadge This feature deep-links to native Instant Apps. If it's not doing that currently, then either: a) you need to setup the device/emulator to allow Instant Apps; b) you need to configure your url to serve an Instant App apk

**Comment by sumeetpanjabi** [comment]
Can we use this feature deep-links for native apps or only instant apps?

**Comment by sumeetpanjabi** [comment]
@dpgraham I tried but it doesn't. I had the app installed and I removed app, appPackage, appActivity from desired capabilities, but it gives errorThe desired capabilities must include either an app, appPackage or browserName. How do you initialize the driver then?

**Comment by dpgraham** [comment]
@sumeetpanjabi what's your use case? Are you trying to start an Appium session without an app or webpage to test?

If so, I would recommend just setting `browserName=Chrome` to start the session and then closing Chrome.

**Comment by ritesh2689** [comment]
Any more details on it. How we can open a deep link as "mobile: deepLink" doesnot work for me
