### ISSUE TITLE
Unhandled rejection Error: UiAUtomator shut down unexpectedly

### ISSUE THREAD

**Issue by rheab123** [appium/appium#10333]
## The problem
The issue :Unhandled rejection Error: UiAUtomator shut down unexpectedly

## Environment

* Appium version Appium Desktop server v1.7.2

* Desktop OS/version used to run Appium: Mac
* Node.js version (unless using Appium.app|exe): v8.9.4
* Mobile platform/version under test: 5.0.1,7.0,7.1.1,6 (have tried with multiple)
* Real device or emulator/simulator: Real device 
* Appium CLI or Appium.app|exe: tried both

## Details
Hi there ,  All I am trying to do is use the appium GUI to install the apk on the android device and start the inspector by providing the capabillities. 

## Link to Appium logs

https://gist.github.com/rheab123/b084aa27687a4ba1e68e73d074cf4df4

## Code To Reproduce Issue [ Good To Have ]
Trying to use the custom server to install apk on android device via appium GUI. Also installed beta versions on terminal and then trying to point the custom server to appium capabillities using GUI , still the same error.

{
  "platformName": "Android",
  "platformVersion": "7.1.1",
  "deviceName": "ZX1G42BQHB",
  "app": "/Users/user/Documents/AppFiles/android/test.apk"
}

## What i have tried so far
1) Updated command line Appium to beta version 
2) Use capabillity - automationName="uiautomator2"
3) Delete all the files from android device and start over.

Note haven't even started writing code yet , just using the GUI to install app and view components. Please Help.

**Comment by mykola-mokhnach** [comment]
Please attach logs when **automationName** is set to _uiautomator2_. Also, it will be useful to see the `adb logcat `output.

**Comment by rheab123** [comment]
Please find logs below when automationName is set to uiautomator2.

Adb logcat logs below :
https://gist.github.com/rheab123/60c1c32db4038c44bb1562c738635464

Appium logs below:
https://gist.github.com/rheab123/533b1d4e1ae2a4212df9cb1d53ab180b

**Comment by mykola-mokhnach** [comment]
Please update Appium Desktop to the recent version. The one you use has a known bug.

**Comment by rheab123** [comment]
What about the command line , i have even tried that using Beta versions as well.

**Comment by mykola-mokhnach** [comment]
Can you please attach `adb logcat` output as well?

**Comment by rheab123** [comment]
Please find adb logcat output below
https://gist.github.com/rheab123/be4d5c7102ed79997079a56ce2fb064b

**Comment by mykola-mokhnach** [comment]
This looks like some third-party issue. Does rebooting the device help?

**Comment by rheab123** [comment]
not really... i have tried multiple times. This is a new mac setup btw , so i am not sure what third party could have caused this. Also the devices are mostly new and i have tried with 4-5 different devices. Emulator setup works!

**Comment by mykola-mokhnach** [comment]
@vmaxim Can you please check the recent log?

**Comment by vmaxim** [comment]
I can't say more than the exception in the log - there is another process witch already connected to UiAutomationService like a appium#4284.

@rheab123 Can you try to reboot your device - start uiAutomator2 manually and check logcat?
```
shell am instrument -w io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner
```

**Comment by rheab123** [comment]
when i start manually via terminal --
adb shell am instrument -w io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner

io.appium.uiautomator2.server.test.AppiumUiAutomator2Server:INSTRUMENTATION_RESULT: shortMsg=Process crashed.
INSTRUMENTATION_CODE: 0
ADB logcat

https://gist.github.com/rheab123/430488f05ea388ba68883af48fbfd888

**Comment by vmaxim** [comment]
```
03-19 14:16:09.406  2068  2636 I ActivityManager: Force stopping com.experitest.uiautomator.test appid=10756 user=0: start instr
03-19 14:16:09.454  2068  2636 I ActivityManager: Start proc 3027:com.experitest.uiautomator.test/u0a756 for added application com.experitest.uiautomator.test
```

**Comment by rheab123** [comment]
sorry could you please explain?? I did not get it :(

**Comment by mykola-mokhnach** [comment]
@vmaxim Could you please clarify the answer?

**Comment by vmaxim** [comment]
> there is another process witch already connected to UiAutomationService

@rheab123 Can you remove [experitest](https://experitest.com/)'s software from host and device and try again?
