### ISSUE TITLE
AndroidBootstrap Error in app.asar file

### ISSUE THREAD

**Issue by badernmb** [appium/appium#10334]
## The problem

I have very simple app to lunch appium server using Node js. When I build (Using electron builder) it packed the app fine. The issue is when I execute the app, It did start the server but once the init function executed it error there. 

The error is shown below :  

An unknown server-side error occurred while processing the command. Original error: Error occured while starting AndroidBootstrap. Original error: Error: Error executing adbExec. Original error: 'Command C\:\\PSATS\\PSATS_Plugins\\Appium_app\\resources\\app.asar\\node_modules\\appium\\node_modules\\appium-android-bootstrap\\bootstrap\\bin\\AppiumBootstrap.jar /data/local/tmp/' exited with code 1'; Stderr: 'cannot stat 'C:\PSATS\PSATS_Plugins\Appium_app\resources\app.asar\node_modules\appium\node_modules\appium-android-bootstrap\bootstrap\bin\AppiumBootstrap.jar': No such file or directory'; Code: '1'
[errorappium.txt](https://github.com/appium/appium/files/1801282/errorappium.txt)

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/appium/appium-desktop

**Comment by badernmb** [comment]
I believe its not related to appium desktop, since i'm using appium module. However, I will reported there. 
Thabks
