### ISSUE TITLE
Unable to launch WebDriverAgent because of xcodebuild failure: "Carthage binary is not found.

### ISSUE THREAD

**Issue by timetraveler90** [appium/appium#10337]
## The problem

This issue is always happening when I try to start desktop Appium server with iOS capabilities. The app is getting installed properly but once it has to be started, the above-mentioned error message appears.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS HighSierra 10.13.2
* Node.js version (unless using Appium.app|exe): v8.10.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium.app

## Details

Whenever I try to run Appium with android capabilities everything is working as expected, but every time I try to run Appium with iOS capabilities I am getting above mentioned error message.

## Link to Appium logs

https://gist.github.com/timetraveler90/435d09313e2ada1a3770f0803b2cf6ec

## Code To Reproduce Issue [ Good To Have ]

{
  "platformName": "iOS",
  "deviceName": "iPhone X",
  "app": "path/to/my/App.app",
  "platformVersion": "11.2",
  "automationName": "XCUITest",
  "xcodeOrgId": "myXcodeOrgId",
  "bundleId": "bundleIdOfMyApp"
}

**Comment by mykola-mokhnach** [comment]
What is the output of `which carthage`. Which carthage version is installed?

**Comment by timetraveler90** [comment]
Output is:

> /usr/local/bin/carthage

**Comment by imurchie** [comment]
`/usr/local/bin` is not in the PATH as Appium gets it, most likely because of an error in defining the PATH. Here are the individual entries, with an errant `=` in two entries:
```
/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/bin=/usr/local/bin
/usr/local/sbin
/usr/bin
/bin
/usr/sbin
/sbin
/Users/petarstanisic/sm-web/bin/
/node_modules/.bin
/private/var/folders/4z/xl7wkjxd1zn282mf6k_xrsw00000gn/T/AppTranslocation/CE8E1225-92D2-4269-AB8A-B9676F4E1066/d/Appium.app/Contents/MacOS
/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/bin=/usr/local/bin
/Users/petarstanisic/Library/Android/sdk/tools
/Users/petarstanisic/Library/Android/sdk/platform-tools
/Users/petarstanisic/Library/Android/sdk/platform-tools/adb
/Users/petarstanisic/Library/Android/sdk/build-tools
/Users/petarstanisic/Library/Android/sdk/tools
/Users/petarstanisic/Library/Android/sdk/platform-tools
/Users/petarstanisic/Library/Android/sdk/platform-tools/adb
/Users/petarstanisic/Library/Android/sdk/build-tools
```

**Comment by timetraveler90** [comment]
@imurchie what is your suggestion, how to solve this problem?

**Comment by mykola-mokhnach** [comment]
This is for sure the complicated case. I'd hire a professional consultant

**Comment by timetraveler90** [comment]
Cmon man :), seriously, adding **/usr/local/bin/carthage** to PATH does not solve this issue that's the reason why i asked

**Comment by kommuswamy** [comment]
yes , even I am facing the same issue.

**Comment by mykola-mokhnach** [comment]
I don't like to spend time explaining basics, especially if these are not related to Appium itself. Just open Wiki and read it carefully: https://en.wikipedia.org/wiki/PATH_(variable)

**Comment by imurchie** [comment]
> seriously, adding /usr/local/bin/carthage to PATH does not solve this issue

Try adding `/usr/local/bin` to the `PATH`. The `PATH` gives search parameters, not actual files, so adding `/usr/local/bin/carthage` to the `PATH` would only work if you had a binary `/usr/local/bin/carthage/carthage`.

**Comment by imurchie** [comment]
As for your current `PATH` in the logs above, try changing the `=` to a `:`. `=` is syntactically wrong. If you look on the first line I provided (just splitting up the entries for readability), `/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/bin=/usr/local/bin`, this should be `/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/bin:/usr/local/bin`, which would be parsed as two, `/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/bin` and `/usr/local/bin`.

**Comment by vdubbaka** [comment]
We are seeing this issue- "carthage not found" over a year now and lots of bugs got opened against it but still lots of people couldn't resolve this issue. Please, We all kindly request that either fix this issue so that it works easily  and list the steps to resolve ourselves or make carthage not required to run Appium. Thanks, in advance

**Comment by mykola-mokhnach** [comment]
@vdubbaka Try https://github.com/appium/java-client/blob/master/docs/environment.md

**Comment by jimrocks007** [comment]
Try changing your java client. I degraded my java client 6.0.0 to java-client 4.1.2 and it's worked fine for me. Before that I also set the environment Path as suggested but doesn't work.
