### ISSUE TITLE
Image comparison using Appium

### ISSUE THREAD

**Issue by anusharao008** [appium/appium#10330]
Hi @mykola-mokhnach @imurchie ,
Is there any possibility for image comparison in Appium.
My scenario is like:
I want to capture screenshot from android, IOS and I want to compare those two images.
By any chance is there any possibility to achieve this kind of scenario?.Can you please help me with this.

**Comment by mykola-mokhnach** [comment]
There is no built-in tools to do it, however java client contains one class, that might be helpful: https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/ScreenshotState.java
