### ISSUE TITLE
driver.manage().getCookies() throwing exception with iOS driver

### ISSUE THREAD

**Issue by srivishal** [appium/appium#10340]
## The problem

I am using iOS driver and trying to get cookie using driver.manage().getCookies(), but getting below error-
org.openqa.selenium.WebDriverException: Unhandled endpoint: /session/35F63E1C-D889-420A-9BF3-8970AE2DE94D/cookie -- http://localhost:8100/ with parameters {
    wildcards =     (
        "session/35F63E1C-D889-420A-9BF3-8970AE2DE94D/cookie"
    );
}

 capabilities = new DesiredCapabilities();
          capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "");
	 capabilities.setCapability("launchTimeout", 600000);
	capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 1800);
	capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "11.2");
	capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
	capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");
	capabilities.setCapability(MobileCapabilityType.ACCEPT_SSL_CERTS, true);
	capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 7 Plus");
       capabilities.setCapability(MobileCapabilityType.APP, iOSAppPath);
      capabilities.setCapability("fullReset",true);
## Environment

* Appium version (or git revision) that exhibits the issue:1.7.0
* xcode -9.2

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Are you in webview context or native?

**Comment by srivishal** [comment]
native

**Comment by mykola-mokhnach** [comment]
Then it is by design. Such method has no sense in native context.
