### ISSUE TITLE
Need bigger and/or customizable maxBufferSize default value for appium-adb logcat 

### ISSUE THREAD

**Issue by jamie-sherriff** [appium/appium#10344]
## The problem

logcat logs on Android start getting dropped after 2-20 minutes on android depending on a number of factors including application under test logs, device manufacture system logging etc because the current limit of 10000 is reached very easily. 

For example an application i use nicely indents JSON objects to multiline for easy readability which takes up to 100 logcat lines per object.

This was introduced by https://github.com/appium/appium-adb/pull/280

I also cannot see a way of customizing this as is currently [android-helpers.js](https://github.com/appium/appium-android-driver/blob/master/lib/android-helpers.js) createADB will need to be updated to pass along any option right?

## Environment

* Appium 1.7.2
* Android (5,6,7)
* Mix of stock android AVD's and samsung tablets
* Node 8.9.4

## Details

Can maxBufferSize be made customizable like clearDeviceLogsOnStart ? what is required to make this change? is it as simple as copying clearDeviceLogsOnStart? if so i can take a look at doing this.

If no changes are wanted then perhaps updating documentation informing a consumer of logcat logs to regularly poll them so they don't miss out on logs? (which is my current workaround)

**Comment by mykola-mokhnach** [comment]
Yes, in theory it is possible to make that customizable. The reason to limit it was memory overhaul. NodeJS process has quite strict limits to the maximum heap size.

**Comment by mykola-mokhnach** [comment]
Would https://github.com/appium/appium-android-driver/pull/343 be ok as a possible solution for this problem?

**Comment by jamie-sherriff** [comment]
@mykola-mokhnach  yup that will be a perfect solution

**Comment by mykola-mokhnach** [comment]
Coll, I'll let you know when the stuff is present in beta, so you can help with testing

**Comment by mykola-mokhnach** [comment]
The change has been recently merged into appium@beta. [Here](https://github.com/appium/appium-android-driver/blob/ee9dd70205eda6dcfe2b059ec8335f04d9ab5040/test/functional/logs-e2e-specs.js) you can find web socket client implementation example

**Comment by jamie-sherriff** [comment]
@mykola-mokhnach  i pulled the latest appium@master and got the following error trying to call 
`driver.execute('mobile: startLogsBroadcast', {});`

Log snippet:
```
[Appium] Welcome to Appium v1.8.0-beta (REV f7264d848ebcaaba1b7449ee63324992eb5907a4)

[HTTP] --> POST /wd/hub/session/a19c401e-9159-4520-b675-f12a5f6fb190/execute
[HTTP] {"script":"mobile: startLogsBroadcast","args":{}}
[debug] [MJSONWP] Calling AppiumDriver.execute() with args: ["mobile: startLogsBroadcast",{},"a19c401e-9159-4520-b675-f12a5f6fb190"]
[MJSONWP] Encountered internal error running command: TypeError: Cannot read property 'getWebSocketHandlers' of undefined
```
I was using  the latest https://github.com/admc/wd as the client and pretty sure i cleared out appium and node_modules prior to testing but can double check.

Any ideas?

**Comment by mykola-mokhnach** [comment]
This might be if appium-base-driver module is out of date. I'd rather reinstall the whole appium, not just a single module

**Comment by mykola-mokhnach** [comment]
Hi Jamie

i've figured out what the problem was. We had a merge operation in the main driver, which broke web socket feature and here is the fix: https://github.com/appium/appium/pull/10496

You can either wait until it is merged or just add and transpile it to your local source. Here you can find a PR to java client lib, which demonstrates basic logs listening principles:
https://github.com/appium/java-client/pull/858

**Comment by jamie-sherriff** [comment]
Awesome thanks for looking at it again! i was about to post i did a clean re install and still the same problem. I will try build it from source in the next few days.

**Comment by mykola-mokhnach** [comment]
Closed as implemented
