### ISSUE TITLE
apk not install in android 8.0 (Oreo) device with signalr-client-sdk

### ISSUE THREAD

**Issue by planetSoftech** [appium/appium#10345]
Hello,

When i am using signalr client sdk in android , but its not installing application in android oreo(anroid 8.0) and error occurs like "Installation failed with message Failed to finalize session : INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113.".

This application works fine in marshmallow device.only error show in android oreo device.

my gradle.build file is below

android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "com.myapplication.testapp"
        minSdkVersion 17
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    implementation 'com.android.support:design:26.1.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    compile files('libs/gson-2.2.2.jar')
    compile files('libs/signalr-client-sdk.jar')
    compile files('libs/signalr-client-sdk-android.jar')
}

Please solve my issue ASAP.

**Comment by mykola-mokhnach** [comment]
Are you able to install the app manually with `adb install`?

**Comment by planetSoftech** [comment]
When i install manually this apk get error apk not install. this error occurs only in android 8.0.

Its working fine marshmallow device.

**Comment by mykola-mokhnach** [comment]
I don't see how this is related to Appium. You must fix the build first
