### ISSUE TITLE
Appium 1.8.0 beta3, fails on getting context on iOS

### ISSUE THREAD

**Issue by mirmitri** [appium/appium#10347]
## The problem

Appium fails on getting context on iOS

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0-beta3
* Last Appium version that did not exhibit the issue (if applicable): 1.7,2
* Desktop OS/version used to run Appium:  macOS Sierra 10.12.6
* Node.js version (unless using Appium.app|exe): 9.8.0
* Mobile platform/version under test:  iOS
* Real device or emulator/simulator: Real device 11.2.1
* Appium CLI or Appium.app|exe: appium from npm 

## Details
Same as above. 
ios_webkit_debug_proxy is running in background
the error is: [MJSONWP] Encountered internal error running command: RequestError: Error: Invalid URI "http:/json"

So most likely something is wrong with getting proper url for ios_webkit_debug_proxy

## Link to Appium logs

 https://gist.github.com/mirmitri/3d170d94e7b7763ad6faddb3f7e4b15f

## Code To Reproduce Issue 
Nothing fancy actually, C# code

https://gist.github.com/mirmitri/bb297154ae0c678a8d3738734c70c1dd

**Comment by imurchie** [comment]
Thanks! Investigating.

**Comment by imurchie** [comment]
This ought to be fixed, if you reinstall the Appium beta. Thanks for reporting this!

**Comment by mirmitri** [comment]
Thanks for fast response!
