### ISSUE TITLE
Get this Error while trying to automate click setting icon on my device 'Error: Error occured while starting App. Original error: Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity

### ISSUE THREAD

**Issue by zayberry** [appium/appium#10346]
## The problem

I am trying to automate a test on launching the settings app on my phone, and each time I run it, I get this error: Error: Error occured while starting App. Original error: Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity

I read somewhere that we should change the automator to v2, i have done that, but I dont know if I did the right thing.

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2
* Desktop OS/version used to run Appium: Win 10
* Node.js version (unless using Appium.app|exe):  8.9.4
* npm version (unless using Appium.app|exe):  5.6.0
* Mobile platform/version under test: Samsung S7/7.0 (Also happens on emulator Android version 4.4.)
* Real device or emulator/simulator: Both
* Appium CLI or Appium.app|exe: Appium CLI (I also have GUI installed, but do not use it)

## Details

I have tried using these as the automator2 path, could it be the reason: Are these pointing to the right uiautomatorviewers

- C:\Users\*****\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\uiautomator2\appium-uiautomator2-server-v0.3.0.apk

- C:\Users\*****\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\uiautomator2\appium-uiautomator2-server-debug-androidTest.apk

## Link to Appium logs

https://gist.github.com/zayberry/f55a6e77edfe62a21dea376a7a6b5937

## Code To Reproduce Issue [ Good To Have ]

import io.appium.java_client.android.AndroidDriver;
import org.openqa.selenium.remote.DesiredCapabilities;

import java.net.MalformedURLException;
import java.net.URL;

public class Main 
{
    public static void main(String[] args) throws MalformedURLException
 {
        DesiredCapabilities caps = new DesiredCapabilities();
        caps.setCapability("deviceName", "ce051605691ebb0c01");
        caps.setCapability("platformName", "Android");
        //caps.setCapability("app", "C:\\Users\\*****\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-uiautomator2-driver\\uiautomator2\\appium-uiautomator2-server-debug-androidTest.apk");
        caps.setCapability("appPackage", "com.android.settings");
        caps.setCapability("appActivity", "com.android.settings.dashboard");

        AndroidDriver driver = new AndroidDriver(new URL("http://0.0.0.0:4723/wd/hub"), caps);

        driver.findElementByAndroidUIAutomator("new UiSelector().description(\"Apps\")").click();
        driver.findElementByAndroidUIAutomator("new UiSelector().text(\"Settings\")").click();
       

        driver.quit();
    }
}

**Comment by mykola-mokhnach** [comment]
You must provide correct values to `appActivity`/`appWaitActivity` capabilities. One can verify if these values are correct by checking the result of 

```
adb shell am start -W -n <package_name>/.<activity_name> -S -a android.intent.action.MAIN c android.intent.category.LAUNCHER - "0x10200000
```

command execution.

**Comment by mykola-mokhnach** [comment]
Closed as duplicate, there are many issues like this one have been already reported

**Comment by zayberry** [comment]
how do I get the activity name pls?

**Comment by mykola-mokhnach** [comment]
All activities must be enumerated in application manifest. Also, try to talk to application devs.
