### ISSUE TITLE
Appium 1.7.2 + iOS 模拟器，在滑动屏幕到底部时报错，偶现

### ISSUE THREAD

**Issue by IMJIEG** [appium/appium#10354]
我在执行测试自动化时，需要将当前屏幕滑到底部，但是偶然会出现下面日志中的情况，如果有谁知道，希望能告知下，谢谢！（I need to slide the current screen to the bottom when I am running the test automation, but I happen to have the situation in the following log. If anyone knows, please tell me, thank you!）
调用方法：Var.driver_instance.execute_script("mobile: scroll", {"direction": "down"})
![image](https://user-images.githubusercontent.com/30293087/37448895-34486ddc-2863-11e8-9f72-b4afe14af22b.png)

**Comment by mykola-mokhnach** [comment]
![images](https://user-images.githubusercontent.com/7767781/37449233-cf96a3ba-2829-11e8-8b7c-bcf776490112.jpg)

**Comment by mykola-mokhnach** [comment]
@KazuCocoa Maybe you can help with translation? %)

**Comment by IMJIEG** [comment]
@mykola-mokhnach I need to slide the current screen to the bottom when I am running the test automation, but I happen to have the following log. If you know, please tell me, thank you.

**Comment by KazuCocoa** [comment]
I can feel, but only Google translate helps us accurate though... :P  @mykola-mokhnach 

----

Anyway, thanks for the updating!

**Comment by mykola-mokhnach** [comment]
@IMJIEG ON the screenshot I see that command timeout happens. Perhaps, you are trying to perform scroll on a wrong element. Device logs might disclose more information about the problem

**Comment by IMJIEG** [comment]
@mykola-mokhnach It was indeed a timeout, but I did not have any solution.

**Comment by KazuCocoa** [comment]
What about `'mobile: swipe'` or action chain following W3C (But it requires Appium 1.8.0) 
http://selenium-python.readthedocs.io/api.html#module-selenium.webdriver.common.action_chains

The below is Ruby client but it will help you to see scroll action without Element.

https://github.com/appium/ruby_lib_core/blob/d7335ee5a2c18b8d1a61b125858b825d196c72d1/test/functional/android/webdriver/w3c_actions_test.rb#L38-L46
