### ISSUE TITLE
Tests running appium-youiengine-driver apps fail with 1.8.0

### ISSUE THREAD

**Issue by simongranger** [appium/appium#10350]
## The problem

appium-youiengine-driver has not been updated to W3C and when running existing tests on 1.8.0 it fails because 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0-beta
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2
* Desktop OS/version used to run Appium: MacOS 10.13.3
* Node.js version (unless using Appium.app|exe): v8.5.0
* Mobile platform/version under test:  Android 5.1.1 (Nexus 5)
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe:

## Details

When running a driver that was not updated to support W3C it should fall back to MJSONWP.

## Link to Appium logs

https://gist.github.com/simongranger/466ba2c9b40dd3cdc457092e57ad11c5

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
@dpgraham ping

**Comment by dpgraham** [comment]
@KazuCocoa The problem is that the timeout isn't taking effect. Would the timeout changes have affected that?

**Comment by KazuCocoa** [comment]
Ruby client's timeout depends on the WebDriver client and the behaviour doesn't change from OSS. 🤔 

BTW, the logs said Ruby client works W3C mode and I could also see some ` Method has not yet been implemented`(not only timeout error). So, as described in _details_, should Ruby client work as MJSONWP mode for the YUI driver?

@simongranger What about adding `forceMjsonwp: true` in desired capability?
Then Ruby client sends MJSONWP format's `createSession` request to the base driver and the driver should return MJSONWP styled response.

**Comment by simongranger** [comment]
I will try that out

**Comment by simongranger** [comment]
Yes, that works (`forceMjsonwp: true`)

**Comment by dpgraham** [comment]
I just had a chance to take a look at it:

* There _is_ a defect in [base-driver](https://github.com/appium/appium-base-driver) that is causing it to incorrectly set the protocol to MJSONWP despite not being provided with W3C parameters. I'll have a fix for that very shortly
* The plan for porting over to W3C was that we were going to implement it on internally maintained Appium Drivers (IOS, Android, UiAutomator2,...) but still make it play nicely with 3rd party drivers that haven't implemented W3C yet (You.I, Windows, Mac,...)
* Once W3C was stabilized and we dog-fooded it, we were going to communicate with 3rd party drivers that it's ready and then they can (if they choose) implement W3C independently of our release timelines
* On my end, I'll get the patch in to fix the defect
* @simongranger on your end, this patch will fix the problems you're having right now and then you and your team can implement W3C for a future release of the You.I Driver
