### ISSUE TITLE
Error An unknown server-side error occurred while processing the command. Original error: Could not determine Xcode version: Could not get Xcode version. /Library/Developer/Info.plist does not exist on disk.

### ISSUE THREAD

**Issue by TwinkleTrivedi** [appium/appium#10351]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.7.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:Appium v1.7.2
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: 10.3
* Real device or emulator/simulator: ios simulator
* Appium CLI or Appium.app|exe:

## Details
Error An unknown server-side error occurred while processing the command. Original error: Could not determine Xcode version: Could not get Xcode version. /Library/Developer/Info.plist does not exist on disk. 

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Please attach the full log

**Comment by TwinkleTrivedi** [comment]
![screen shot 2018-03-15 at 10 46 49 pm](https://user-images.githubusercontent.com/34636524/37501083-0c44755c-28a3-11e8-9c5c-e142824e5434.png)

**Comment by TwinkleTrivedi** [comment]
![screen shot 2018-03-15 at 10 50 29 pm](https://user-images.githubusercontent.com/34636524/37501136-50235428-28a3-11e8-8f7f-e230dcde1a90.png)

the log image

**Comment by utsabpanta** [comment]
@mykola-mokhnach what was the resolution? I am running into the exact same issue.

**Comment by mykola-mokhnach** [comment]
@utsabpanta the solution is provided above by @imurchie . The described issue has nothing to do with appium itself and signals about incorrect configuration of the destination machine.

**Comment by vanigitidealz** [comment]
go to xcode of your project, go to plist file and check if app is selected in right corner.
Clear cache in xcode
