### ISSUE TITLE
Rootcause on appium slowness in Appium 1.7.1 + real device/simulator combination & XCUITest

### ISSUE THREAD

**Issue by Sandozf** [appium/appium#10353]
## The problem

When running the test script with real device, it is taking around 36 mins in real device whereas the same script runs in 16 mins in iOS Simulator. When running the same test script in XCUITest Framework (using Xcode with Source code), it is so faster (just 8 mins) than Appium. Any idea on the rootcause.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): 1.6.0 or less
* Desktop OS/version used to run Appium: Mac sierra (10.12)
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iPad Air (iOS 10.3.3)
* Real device or emulator/simulator: Real Device and iOS Simulator
* Appium CLI or Appium.app|exe:

**Comment by mykola-mokhnach** [comment]
Can you make you question more concrete? Otherwise we are talking about spherical cows - there are too many possible scenarios. One thing I can say for sure - try appium@beta with iOS11. It is constantly being improved.

**Comment by dilsreccse** [comment]
@mykola-mokhnach Even my appium test on iOS Native runs faster in simulator when compared to real device, why there is a difference in the execution speed between the simulator and real device ?

**Comment by Sandozf** [comment]
@mykola-mokhnach All we have is workarounds to run faster in devices/simulators. I have mostly used accessibility ID's for identifying elements and a very limited use of Xpath in the script. My question is why the same test script runs faster in Simulator and slower in real device with same version?

**Comment by mykola-mokhnach** [comment]
It might be that iproxy adds some overhead, but I cannot say for sure

**Comment by mykola-mokhnach** [comment]
Also an older iOS version might be the reason

**Comment by Sandozf** [comment]
@mykola-mokhnach I came up an info that instruments adds a 1 second delay for real device (very old story). Is it the same reason for XCUITest Framework also? 
Also, don't we have iproxy setup for simulators?

**Comment by mykola-mokhnach** [comment]
>  I came up an info that instruments adds a 1 second delay for real device (very old story). Is it the same reason for XCUITest Framework also?

I haven't investigated that topic, but nobody was complaining about something like this so far.

> Also, don't we have iproxy setup for simulators?

No, WDA listens on localhost when Simulator is used, so there is no need for port forwarding.

**Comment by Sandozf** [comment]
thanks @mykola-mokhnach. Atleast found some gray areas in appium. Really want to know more on the rootcause to find and fix the underlining slowness.

**Comment by andrecnogueira** [comment]
I also noticed a huge delay to start test execution. My last attempt it took 17 minutes, believe me, to start a single test. The test passes, but 17 minutes to start it's not good at all... I have tried different versions of drivers/servers/simulators and could not find a workaround. Is anyone also having similar bad experience? This is only with iOS.

Appium version: 1.7.2 and greater version
Xcode 9.2
iOS simulator: 11.2

**Comment by VenkateshPS** [comment]
I would second on this running tests on iOS is very slow.

using Appium 1.6.6 beta 4
Xcode 9.2
iPhone 6 device, with iOS 11.2.6

**Comment by mykola-mokhnach** [comment]
https://github.com/facebook/WebDriverAgent/wiki/How-To-Achieve-The-Best-Lookup-Performance

**Comment by abhishekmonti** [comment]
I am still facing same issue, it is taking to long for the app to open and then first click is taking time.
Adding the Appium log, please suggest.

[XCUITest] Using provided WebdriverAgent at 'http://localhost:4724/'
[BaseDriver] Event 'wdaSessionAttempted' logged at 1526865744242 (21:22:24 GMT-0400 (EDT))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:4724/status] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"11.3\",\n      \"sdkVersion\" : \"11.3\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"11.3\",\n      \"ip\" : \"192.168.1.14\"\n    },\n    \"build\" : {\n      \"time\" : \"May 20 2018 21:03:39\"\n    }\n  },\n  \"sessionId\" : \"5EB3269A-E57C-4DB9-A0F3-DB32E567BB11\",\n  \"status\" : 0\n}"
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:4724/session] with body: {"desiredCapabilities":{"bundleId":"com.XXXXXXXXXX.XXXXXXXX","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[Xcode] 2018-05-20 21:16:27.116321-0400 WebDriverAgentRunner-Runner[18685:623922] +[CATransaction synchronize] called within transaction
[Xcode] 2018-05-20 21:16:27.357632-0400 WebDriverAgentRunner-Runner[18685:623922] Running in the background.
[Xcode] 2018-05-20 21:16:27.361332-0400 WebDriverAgentRunner-Runner[18685:623922] Running tests...
[Xcode] objc[18685]: Class VCWeakObjectHolder is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AVConference.framework/Frameworks/ViceroyTrace.framework/ViceroyTrace (0x12c2d54d0) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AVConference.framework/AVConference (0x12aed3e38). One of the two will be used. Which one is undefined.
[Xcode] Test Suite 'All tests' started at 2018-05-20 21:16:41.998
[Xcode] Test Suite 'WebDriverAgentRunner.xctest' started at 2018-05-20 21:16:42.001
[Xcode] Test Suite 'UITestingUITests' started at 2018-05-20 21:16:42.001
[Xcode] Test Case '-[UITestingUITests testRunner]' started.
[Xcode]     t =     0.12s Start Test at 2018-05-20 21:16:42.122
[Xcode]     t =     0.12s Set Up
[Xcode] 2018-05-20 21:16:42.124804-0400 WebDriverAgentRunner-Runner[18685:623922] Built at May 20 2018 21:03:36
[Xcode] 2018-05-20 21:16:42.247395-0400 WebDriverAgentRunner-Runner[18685:623922] ServerURLHere->http://192.168.1.14:4724<-ServerURLHere
[Xcode]     t =     0.49s Open com.XXXXXX.XXXXXXXXXXX
[Xcode]     t =     0.49s     Launch com.XXXXXXXX.XXXXXXXXX
[Xcode] 2018-05-20 21:16:50.337822-0400 WebDriverAgentRunner-Runner[18685:623922] Enqueue Failure: Failed to launch com.XXXXXXXX.XXXXXXXX: Timed out attempting to launch app. /Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode]     t =    10.23s         Wait for accessibility to load
[Xcode]     t =    10.96s         Wait for com.XXXXXXX.XXXXXXXX to idle
[Xcode]     t =    70.99s             App event loop idle notification not received, will attempt to continue.
[Xcode]     t =    70.99s             App animations complete notification not received, will attempt to continue.
[Xcode] 2018-05-20 21:18:59.050144-0400 WebDriverAgentRunner-Runner[18685:623922] Enqueue Failure: Failure fetching attributes for element  Device system-wide element: Error Domain=com.apple.XCTestErrorDomain Code=-999 "Timeout waiting for fulfillment of promise for 'Fetching attributes for element  Device system-wide element'." UserInfo={NSLocalizedDescription=Timeout waiting for fulfillment of promise for 'Fetching attributes for element  Device system-wide element'.} /Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode] 2018-05-20 21:18:59.050700-0400 WebDriverAgentRunner-Runner[18685:623922] Enqueue Failure: Failure to determine system application: (null) /Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode] 2018-05-20 21:20:04.053236-0400 WebDriverAgentRunner-Runner[18685:623922] Enqueue Failure: Failure fetching attributes for element (null): Error Domain=com.apple.XCTestErrorDomain Code=-999 "Timeout waiting for fulfillment of promise for 'Fetching attributes for element (null)'." UserInfo={NSLocalizedDescription=Timeout waiting for fulfillment of promise for 'Fetching attributes for element (null)'.} /Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode] 2018-05-20 21:20:04.053926-0400 WebDriverAgentRunner-Runner[18685:623922] Enqueue Failure: Failure getting list of active applications: (null) /Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode] 2018-05-20 21:21:09.159318-0400 WebDriverAgentRunner-Runner[18685:623922] Enqueue Failure: Failure fetching attributes for element  Device system-wide element: Error Domain=com.apple.XCTestErrorDomain Code=-999 "Timeout waiting for fulfillment of promise for 'Fetching attributes for element  Device system-wide element'." UserInfo={NSLocalizedDescription=Timeout waiting for fulfillment of promise for 'Fetching attributes for element  Device system-wide element'.} /Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode] 2018-05-20 21:21:09.160032-0400 WebDriverAgentRunner-Runner[18685:623922] Enqueue Failure: Failure to determine system application: (null) /Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode] 2018-05-20 21:22:14.163160-0400 WebDriverAgentRunner-Runner[18685:623922] Enqueue Failure: Failure fetching attributes for element (null): Error Domain=com.apple.XCTestErrorDomain Code=-999 "Timeout waiting for fulfillment of promise for 'Fetching attributes for element (null)'." UserInfo={NSLocalizedDescription=Timeout waiting for fulfillment of promise for 'Fetching attributes for element (null)'.} /Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode] 2018-05-20 21:22:14.164035-0400 WebDriverAgentRunner-Runner[18685:623922] Enqueue Failure: Failure getting list of active applications: (null) /Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode]     t =   332.16s Unable to monitor event loop
[Xcode]     t =   332.17s Unable to monitor animations
[Xcode]     t =   338.40s Terminate com.XXXXX.XXXXX:18692
[Xcode]     t =   342.35s Open com.XXXXX.XXXXX
[Xcode]     t =   342.35s     Launch com.XXXXX.XXXXX
[Xcode]     t =   342.52s         Wait for com.XXXXX.XXXXX to idle
[Xcode]     t =   402.52s             App event loop idle notification not received, will attempt to continue.
[Xcode]     t =   402.52s             App animations complete notification not received, will attempt to continue.
[Xcode] 2018-05-20 21:24:30.535394-0400 WebDriverAgentRunner-Runner[18685:623922] Enqueue Failure: Failure fetching attributes for element  Device system-wide element: Error Domain=com.apple.XCTestErrorDomain Code=-999 "Timeout waiting for fulfillment of promise for 'Fetching attributes for element  Device system-wide element'." UserInfo={NSLocalizedDescription=Timeout waiting for fulfillment of promise for 'Fetching attributes for element  Device system-wide element'.} /Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode] 2018-05-20 21:24:30.536039-0400 WebDriverAgentRunner-Runner[18685:623922] Enqueue Failure: Failure to determine system application: (null) /Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode] 2018-05-20 21:25:35.542892-0400 WebDriverAgentRunner-Runner[18685:623922] Enqueue Failure: Failure fetching attributes for element (null): Error Domain=com.apple.XCTestErrorDomain Code=-999 "Timeout waiting for fulfillment of promise for 'Fetching attributes for element (null)'." UserInfo={NSLocalizedDescription=Timeout waiting for fulfillment of promise for 'Fetching attributes for element (null)'.} /Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode] 2018-05-20 21:25:35.544408-0400 WebDriverAgentRunner-

**Comment by andrecnogueira** [comment]
hey @abhishekmonti, did you manage to find a solution for that issue? I am stuck on it for a while.

**Comment by Marrowbones** [comment]
In case anyone is still having the same problem, try upgrading everything (NPM, Appium, etc); I know it sounds obvious, but what's probably happened is that you've installed an OS upgrade that's not compatible with some component of the Appium/WebDriver setup.  For me, the problem was carthage (brew update carthage) - an easy one to overlook. Hope this helps.
