### ISSUE TITLE
.manage().logs().get("server") returns null

### ISSUE THREAD

**Issue by tfcardoso** [appium/appium#10355]
## The problem

Doing

    driver.manage().logs().get("server");

Returns error:

    org.openqa.selenium.UnsupportedCommandException: malformed response to remote logs command

And on logs it appears:

    [debug] [35m[BaseDriver][39m Retrieving 'server' logs
    [debug] [35m[BaseDriver][39m Retrieving supported log types
    [debug] [35m[MJSONWP][39m Responding to client with driver.getLog() result: null
    
## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0-beta3
* Desktop OS/version used to run Appium: Windows
* Mobile platform/version under test: Tried Android 8 & Android 6 (Logs from this one)
* Real device or emulator/simulator: Real Device
* Java Client: 6.0.0-BETA4

## Link to Appium logs

https://gist.github.com/tfcardoso/4d246282814a95452d62e2a7324554de

## Code To Reproduce Issue [ Good To Have ]

```
Set<String> logTypes = driverA.getDriver().manage().logs().getAvailableLogTypes();
LogEntries logEntries = driverA.getDriver().manage().logs().get("server");
```

**Comment by mykola-mokhnach** [comment]
Can you please replace  the line

`return logger.record;`

with 

`return logger.unwrap().record;`

inside `node_modules/appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/command/logs.js` file where your node modules are installed, execute `gulp transpile`and restart appium?

**Comment by tfcardoso** [comment]
Now sure if I did it right. I had 

    return log.record;

and updated that to:

    return log.unwrap().record;

And the server logs seems to be there on last line response:

https://gist.github.com/tfcardoso/a3c1e497504b1894d4750f5170f08dbb

Code breaks with Expection:

    java.lang.IllegalArgumentException: Bad level "info"

**Comment by mykola-mokhnach** [comment]
Perfect. There's one more thing to do:

replace the line with:

`return log.unwrap().record.map(x => x.message)`

And transpile it again

**Comment by tfcardoso** [comment]
Sorry, I was kind of busy.

With that change, the following exception appears:
    
    java.lang.String cannot be cast to java.util.Map

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium-android-driver/pull/341 should do the job

**Comment by tfcardoso** [comment]
It works 🥇 Thanks.

**Comment by diemol** [comment]
Hi,

I apologise for hijacking this closed issue, but I am not able to get the server logs while using Appium 8.0 and the Java bindings 6.0.0. This is what I see in the log:

```
[debug] [W3C] Calling AppiumDriver.getLogTypes() with args: ["41356621-3634-412f-b361-e344c1771c37"]
[debug] [BaseDriver] Retrieving supported log types
[debug] [W3C] Responding to client with driver.getLogTypes() result: ["logcat","bugreport","server"]
[HTTP] <-- GET /wd/hub/session/41356621-3634-412f-b361-e344c1771c37/log/types 200 8 ms - 103
[HTTP]
[HTTP] --> POST /wd/hub/session/41356621-3634-412f-b361-e344c1771c37/log
[HTTP] {"type":"server"}
[debug] [W3C] Calling AppiumDriver.getLog() with args: ["server","41356621-3634-412f-b361-e344c1771c37"]
[debug] [BaseDriver] Retrieving 'server' logs
[debug] [BaseDriver] Retrieving supported log types
[HTTP] <-- POST /wd/hub/session/41356621-3634-412f-b361-e344c1771c37/log 500 46 ms - 1272
```

I am starting Appium like this:
```
appium --port 4444 --relaxed-security
```

I am not sure if this is a new bug or if I am doing something wrong. If I should open a new issue, please just let me know.

**Comment by mykola-mokhnach** [comment]
@diemol Try appium@beta

**Comment by diemol** [comment]
@mykola-mokhnach I am sorry, I was using the wrong startup script, and I just noticed while checking it to change the version. I basically forgot to do git pull in the machine where I was testing.

Thank you for the quick reply though!
