### ISSUE TITLE
Issue with ExecuteAsyncScript on real iOS devices

### ISSUE THREAD

**Issue by dany11aravindraj** [appium/appium#10361]
## The problem

Unable to execute Protractor tests via Appium on real iOS devices (our current test requirement). 

## Environment

* Appium version : **1.7.0** and **1.7.2**
* Desktop OS/version used to run Appium: **MacOS High Sierra**
* Node.js version (unless using Appium.app|exe): **8.9.1**
* Mobile platform/version under test: **iOS 11.2.6**
* Real device or emulator/simulator: **Real device iPhone 5S**
* Appium CLI or Appium.app|exe: **Appium CLI**

## Details

It seems like execute async script is not working with Appium (using 1.7.0 and 1.7.2). To confirm that this was not an issue with my test scripts I pulled up sample scripts from Protractor's website. Even a basic sample does not work.

## Link to Appium logs

* Appium error logs
* Using 1.7.0
https://gist.github.com/dany11aravindraj/2e68f47f02f0581ad5bdf3ff26982f78
* Using 1.7.2
https://gist.github.com/dany11aravindraj/8b1401f18ba88d42dd6de15359e358f5

* Error received in console locally
https://gist.github.com/dany11aravindraj/b10968b76232480c1c4c1d1b8f896887

## Code To Reproduce Issue

* Sample Protractor test (contains files conf.js and spec.js)
https://gist.github.com/dany11aravindraj/3e140eb31391b2e6e905a9df081ce992

**Comment by imurchie** [comment]
I do not see any attempt to call an async script.

Are the 1.7.2 logs complete? What happens in the browser? Is there any output in the `ios_webkit_debug_proxy` terminal?

**Comment by dany11aravindraj** [comment]
Yes, the 1.7.2 logs are complete.

I re-ran the test with debugging enabled in ios_webkit_debug_proxy. You can find it here along with the Appium logs  - https://gist.github.com/dany11aravindraj/25fc8199ce59bb21f691b52dc6baafac

In Mobile Safari I see the URL resolved without any issues. However the sendKeys values were not sent.

Please let me know if there are any additional details that I can provide.

**Comment by elena-dev-thought** [comment]
It is not a solution for you to use the execute Syncron Script function and to build a wait inside?

**Comment by mykola-mokhnach** [comment]
Closed as inactive

**Comment by ckzgraphics** [comment]
Related Issues-
- https://github.com/angular/protractor/issues/2840
- https://github.com/appium/appium/issues/11925
- https://github.com/appium/appium/issues/3471
