### ISSUE TITLE
setValue used for multiple Text Fields on Android crashes and breaks test

### ISSUE THREAD

**Issue by DalianaD** [appium/appium#10368]
## The problem

I am trying to fill in 4 Text Fields, on a NativeScript app for Android, using the browser.setValue(selector,values);

If I have 3 Text Fields on the screen, the test runs successfully. 
If I have 4 Text Fields on the screen, the test fails.

In the console, at the failure point, I can see this trace:

`COMMAND	POST 	 "/wd/hub/session/f1c33191-528b-4b12-bdb3-3dfef1d4f18b/element"
[14:48:03]  DATA		{"using":"accessibility id","value":"inputUserEmail"}
F․ [14:48:03]  COMMAND	DELETE 	 "/wd/hub/session/f1c33191-528b-4b12-bdb3-3dfef1d4f18b"
[14:48:03]  DATA		{}
[14:48:03]  RESULT		{"ELEMENT":"7"}
[14:48:03]  COMMAND	POST 	 "/wd/hub/session/f1c33191-528b-4b12-bdb3-3dfef1d4f18b/element/7/clear"
[14:48:03]  DATA		{}
[14:48:04]  RESULT		undefined`

It always fails at the 4rd Text Field (even if I switch the order of the fields in the demo app, so it is not the fields issue).

## Environment

* WebdriverIO version: 4.7.1
* Appium : 1.7.2
* Tests ran on Android Emulator
* Node.js version: 8.1.4

* wdio TestRunner Mode
* Additional wdio packages used (if applicable):
    "wdio-appium-service": "^0.2.3",
    "wdio-cucumber-framework": "^0.2.15",
    "wdio-junit-reporter": "0.2.0",
    "wdio-screenshot": "^0.4.0",
    "wdio-selenium-standalone-service": "0.0.8",
    "wdio-spec-reporter": "0.0.5",
    "webdriverio": “4.7.1"

   "appium": "1.7.2",
   "appium-controller": "1.1.6",
    "appium-uiautomator": "1.1.5",
    "cucumber": "~1.3.1",
    "cucumber-expressions": "^5.0.7",
    "cucumber-tag-expressions": "^1.1.1",

## Details
To reproduce the issue, make sure you have an Android Emulator open.

In the provided test app run:
`npm install`
`npm run test-only-smoke-android`

## Code To Reproduce Issue [ Good To Have ]

Please take a look into this example repository, as it contains a test app and UI integration test where we see the issue:

https://github.com/surdu/TNSTravisTest.git

I have also added the Appium logs I get.

**Comment by DalianaD** [comment]
[appium.log](https://github.com/appium/appium/files/1824442/appium.log)

**Comment by mykola-mokhnach** [comment]
Switch automationName to `uiautomator2`

**Comment by DalianaD** [comment]
hey Mykola,

Do you mean only change the automationName in this config file? https://github.com/surdu/TNSTravisTest/blob/master/wdio.conf.android.js

`capabilities: [{
    automationName: “uiautomator2",
    commandTimeout: 20000,
    sessionOverride: true,
    debugLogSpacing: true,
    platformName: 'Android',
    showIosLog: true,
    deviceName:'Android Emulator',
    isolateSimDevice: true,
    autoLaunch: false,
    autoAcceptAlerts: true,
    unicodeKeyboard: true,
    resetKeyboard: true,
    app: APP_PATH
  }],`

Can you please tell me what other changes do I need to do?

**Comment by mykola-mokhnach** [comment]
I'm not familiar with your local config, so I cannot say where and what should be changed. I've just suggested a possible option, which may solve this problem.

**Comment by DalianaD** [comment]
@mykola-mokhnach: Thank you for responding.

I tried also to add ```uiautomator2``` for the automationName. It still fails. (that is why I asked if I need to change other stuff as well, if I run with uiautomator2 instead of appium.)

If you do have the time, here is a small,easy, and functional example I made so that I can show you guys the issue. If you have any other suggestions/ ideas please let me know. 

https://github.com/surdu/TNSTravisTest.git

**Comment by mykola-mokhnach** [comment]
Do you have the updated log with UA2 backend?

**Comment by DalianaD** [comment]
I have adapted the test project to use ```uiautomator2``` and it works OK if I don’t use the ```browser.hideDeviceKeyboard();```  after i fill in a field (if I use the Appium Android Input Manager).  But, If i want to use the device keyboard, I need to use the hideKeyboard because otherwise the other fields will not be visible. 
Currently it fills in the first 3 fields and before reaching the 4th it crashes.

```
fillInTextFields: {
  value: function() {
    this.passwordTextField.setValue("Password");
    browser.pause(4000);
    browser.hideDeviceKeyboard();

    this.firstNameTextField.setValue("First Name");
    browser.pause(4000);
    browser.hideDeviceKeyboard();

    this.lastNameTextField.setValue("Last Name");
    browser.pause(4000);
    browser.hideDeviceKeyboard();

    this.emailTextField.setValue("Email");
    browser.pause(4000);
    browser.hideDeviceKeyboard();

    console.log("SUCCESS");
  }}
```
**Logs:**
[appium.log](https://github.com/appium/appium/files/1828594/appium.log)
[appium2.log](https://github.com/appium/appium/files/1828611/appium2.log)

**Comment by mykola-mokhnach** [comment]
Try to use appium@beta and UIA2 backend

**Comment by DalianaD** [comment]
After I updated the config as you mentioned above, I ran into this already reported issue:
https://github.com/appium/appium/issues/10377

**Comment by mykola-mokhnach** [comment]
The fix for that issue should be deployed today

**Comment by mykola-mokhnach** [comment]
btw, can you replace setValue with sendKeys?
