### ISSUE TITLE
Issue to get the auto populated values on Mobile safari 10.0 and 11.0

### ISSUE THREAD

**Issue by RajShekar-Bommalata** [appium/appium#10366]
## The problem

Facing issue on Mobile safari 10.0 and 11.0 to get the auto populated values after entering the zip code for FOREVER21 application.

Steps to replicate : 
1.Open url : https://www.forever21.com/MX/Mobile 
2.Search and add product to cart 
3.Navigate to checkout screen. 
4.Enter email-id and click on continue button. 
5.Click on ADD button of shipping address. 
6.Enter Zip code and click on any of the field.

The following fields should be auto populated 
State , City , Townhall , Colonia

## Environment

* Appium version that exhibits the issue: 1.7.2
* Browser : Mobile Safari
* Browser Version : 10.0,11.0.
* Mobile platform/version under test: iPhone Simulator / iPhone X
* Real device or emulator/simulator: Both simulator and real device

## Sample Code

[Mobile Safari Issue.zip](https://github.com/appium/appium/files/1824133/Mobile.Safari.Issue.zip)

**Comment by mykola-mokhnach** [comment]
Does this work on Desktop Safari?

**Comment by RajShekar-Bommalata** [comment]
Yes the address fields are auto populated when I use desktop safari 11.0 .

**Comment by mykola-mokhnach** [comment]
I don't think such problem has something to do with Appium itself. It's rather am IWDP problem or an issue with mobile Safari itself.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
