### ISSUE TITLE
shutdownOtherSimulators not recognized

### ISSUE THREAD

**Issue by ericzered** [appium/appium#10369]
## The problem

Hello,
I want to use the capabilities **shutdownOtherSimulators**, but I have _"The following capabilities were provided, but are not recognized by appium: shutdownOtherSimulators"_
I’m using Appium v1.7.2 and I’m running it with --relaxed-security option. Is they’re something else I have to do to have it works ?
Thanks a lot

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/ericzered/ce2b147a4fe86d23b03a3e011b22ba86

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
The capability is only available in appium@beta
