### ISSUE TITLE
Error: zipAlignApk failed

### ISSUE THREAD

**Issue by VenkateshPS** [appium/appium#10377]
## The problem

getting Error: zipAlignApk failed on Appium 1.8.3, while running Automation on Android .
## Environment

* Appium version (or git revision) that exhibits the issue:1.8.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: mac OS High Siera 10.3.3
* Node.js version (unless using Appium.app|exe): v7.5.0
* Mobile platform/version under test:Android 7
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe:

## Details

Attached are the logs.

## Link to Appium logs

Create a [GIST](https://gist.github.com
[zipAlignApk_failed.txt](https://github.com/appium/appium/files/1829603/zipAlignApk_failed.txt)
) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Linking https://github.com/appium/appium-adb/pull/307

**Comment by mykola-mokhnach** [comment]
We've recently published an updated module. Could you try to reinstall you beta and try again?

**Comment by xiaoqi7s** [comment]
I have the same problem,the log is:
Error: zipAlignApk failed. Original error: Command 'C\:\\Android\\android-sdk\\build-tools\\27.0.3\\zipalign.exe -f 4 C\:\\Users\\woxia\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\_appium-uiautomator2-driver\@0.11.0\@appium-uiautomator2-driver\\uiautomator2\\appium-uiautomator2-server-debug-androidTest.apk C\:\\Users\\woxia\\AppData\\Local\\Temp\\2018221-18140-1yhufwx.g87\\appium.tmp' exited with code 1. Stdout: ''; Stderr: ''
[ADB]     at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:78:13)
[ADB]     at ADB.callee$0$0$ (../../../lib/tools/apk-signing.js:173:9)
[ADB]     at tryCatch (C:\Users\woxia\AppData\Roaming\npm\node_modules\appium\node_modules\_babel-runtime@5.8.24@babel-runtime\regenerator\runtime.js:67:40)
[ADB]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\woxia\AppData\Roaming\npm\node_modules\appium\node_modules\_babel-runtime@5.8.24@babel-runtime\regenerator\runtime.js:315:22)
[ADB]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\woxia\AppData\Roaming\npm\node_modules\appium\node_modules\_babel-runtime@5.8.24@babel-runtime\regenerator\runtime.js:100:21)
[ADB]     at GeneratorFunctionPrototype.invoke (C:\Users\woxia\AppData\Roaming\npm\node_modules\appium\node_modules\_babel-runtime@5.8.24@babel-runtime\regenerator\runtime.js:136:37)
[ADB]     at <anonymous>
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: Error: Trying to proxy a session command without session id
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","R3E0216C10002466","shell","am","force-stop","com.tencent.mm"]
[debug] [ADB] Removing forwarded port socket connection: 8200
[debug] [ADB] Running 'C:\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","R3E0216C10002466","forward","--remove","tcp:8200"]
[debug] [ADB] Running 'C:\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","R3E0216C10002466","forward","--remove","tcp:8200"]
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command 'C\:\\Android\\android-sdk\\platform-tools\\adb.exe -P 5037 -s R3E0216C10002466 forward --remove tcp\:8200' exited with code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''
[MJSONWP] Encountered internal error running command: Error: zipAlignApk failed. Original error: Command 'C\:\\Android\\android-sdk\\build-tools\\27.0.3\\zipalign.exe -f 4 C\:\\Users\\woxia\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\_appium-uiautomator2-driver\@0.11.0\@appium-uiautomator2-driver\\uiautomator2\\appium-uiautomator2-server-debug-androidTest.apk C\:\\Users\\woxia\\AppData\\Local\\Temp\\2018221-18140-1yhufwx.g87\\appium.tmp' exited with code 1. Stdout: ''; Stderr: ''
[MJSONWP]     at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:78:13)
[MJSONWP]     at ADB.callee$0$0$ (../../../lib/tools/apk-signing.js:173:9)
[MJSONWP]     at tryCatch (C:\Users\woxia\AppData\Roaming\npm\node_modules\appium\node_modules\_babel-runtime@5.8.24@babel-runtime\regenerator\runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\woxia\AppData\Roaming\npm\node_modules\appium\node_modules\_babel-runtime@5.8.24@babel-runtime\regenerator\runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\woxia\AppData\Roaming\npm\node_modules\appium\node_modules\_babel-runtime@5.8.24@babel-runtime\regenerator\runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (C:\Users\woxia\AppData\Roaming\npm\node_modules\appium\node_modules\_babel-runtime@5.8.24@babel-runtime\regenerator\runtime.js:136:37)
[MJSONWP]     at <anonymous>
[HTTP] <-- POST /wd/hub/session 500 7979 ms - 627

**Comment by shynkevich-alex** [comment]
The same issue with last appium beta

**Comment by mykola-mokhnach** [comment]
Please make sure the version of appium-adb module is at 6.5.0+ before adding +1 to this report

**Comment by shynkevich-alex** [comment]
@mykola-mokhnach  hmm, I have version 2.28.3 but I was reinstalled appium, how can I update appium-adb?

**Comment by shynkevich-alex** [comment]
So I updated appium-adb via "npm install appium-adb" and issue gone for me. Thanks @mykola-mokhnach

**Comment by shynkevich-alex** [comment]
I have update appium-ad via "npm install appium-adb" to 6.5.1 but still have the same error.

**Comment by mykola-mokhnach** [comment]
@shynkevich-alex you need to uninstall and install again the whole appium@beta, not just the single module

**Comment by shynkevich-alex** [comment]
@mykola-mokhnach Thank you.
I reinstalled appium@beta and tests launches fine right now.

**Comment by VenkateshPS** [comment]
It works fine now, and App gets launched.

Although I see the below log only for the first time after installing Appium, does not shows when you run next time.

ADB] Checking whether zipalign is present
[ADB] Using zipalign from /Users/venkateshsingh/android/build-tools/27.0.1/zipalign
[ADB] Error: zipAlignApk failed. Original error: Command '/Users/venkateshsingh/android/build-tools/27.0.1/zipalign -f 4 /usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v1.3.0.apk /var/folders/z_/bz3z41cn74q1_jc1jlc4h26c0000gn/T/2018222-57389-1lbug1c.orzy9cnmi/appium.tmp' exited with code 1. Stdout: ''; Stderr: ''
[ADB]     at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:78:13)
[ADB]     at ADB.callee$0$0$ (../../../lib/tools/apk-signing.js:179:9)
[ADB]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[ADB]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[ADB]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[ADB]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[debug] [ADB] Signing '/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v1.3.0.apk' with default cert
[ADB] Using apksigner from /Users/venkateshsingh/android/build-tools/27.0.1/apksigner

**Comment by mykola-mokhnach** [comment]
That's expected for now. Thanks for checking

**Comment by benfr1** [comment]
I installed npm install -g appium@beta and have the same error.  dear ones, can somebody retell what was the solution ?
