### ISSUE TITLE
Error finding if app is installed.  ould not access the Package Manager

### ISSUE THREAD

**Issue by orevron** [appium/appium#10378]
## The problem
I am trying to run test that uses no wd (only http request to the appium server)
but when i try to create new session with the emulator, the emulator is resetting and the error (in the gist file) appear

## Environment

* appium cli version 1.7.2 
* the OS that runs the appium server is debian 
* nodejs version 8.9.4
* newest android studio emulator and Android version 7.1
* Android emulator
* Appium CLI 

## Details
the same code is working on my local machine, and works perfectly.
but when i try to run it on my cloud i see this exception and the emulator is restting 

## Link to Appium logs

https://gist.github.com/orevron/db97e82323c5fc07f6826f3925b6b68a

## Code To Reproduce Issue [ Good To Have ]
just creating new session, not something special

**Comment by mykola-mokhnach** [comment]
Most likely this happens due to slow emulator startup: https://stackoverflow.com/questions/15524185/could-not-access-the-package-manager-is-the-system-running-while-installing-and

**Comment by orevron** [comment]
not an option as the emulator is already running on the time the test is executed....

**Comment by mykola-mokhnach** [comment]
Try to set `avd` capability properly

**Comment by orevron** [comment]
To what should I set it?

**Comment by mykola-mokhnach** [comment]
Have you tried to set `avd` capability value?
