### ISSUE TITLE
Getting "Stderr: 'Failed to stat /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-unlock/bin/unlock_apk-debug.apk: No such file or directory'; Code: '1'" error

### ISSUE THREAD

**Issue by shanthi2016** [appium/appium#10372]
While running tests on Android real device 7.0 getting the following error:
Stderr: 'Failed to stat /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-unlock/bin/unlock_apk-debug.apk: No such file or directory'; Code: '1'

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable):NA
* Desktop OS/version used to run Appium: 10.12.6
* Node.js version (unless using Appium.app|exe)::6.10.2
* Mobile platform/version under test: Android OS 7.0
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:Appium.app

I am trying to run tests on an android real device 7.0 and its throwing an error:

Please find attached logs:
https://gist.github.com/shanthi2016/c74769c57f1b192a9dba31d1e5d21408

**Comment by mykola-mokhnach** [comment]
It is a problem with Appium desktop and should be reported to https://github.com/appium/appium-desktop. Most likely the installation is broken.
