### ISSUE TITLE
ebDriverAgent because of xcodebuild failure: "Command 'Scripts/bootstrap.sh -d' exited with code 1"

### ISSUE THREAD

**Issue by inggiinggita** [appium/appium#10379]
Hi!

I have problem with my WDA as i want to run ./Scripts/bootstrap.sh -d, i only get Green Light with "Fetching Dependencies" and nothing happened. As i tried without "-d" , i got a lot of problem, 137 problems to be exact : 

> npm WARN react-dom@15.6.2 requires a peer of react@^15.6.2 but none is installed. You must install peer dependencies yourself.
> npm WARN web-driver-inspector@1.0.0 No repository field.
> 
> up to date in 4.088s
> Validating Inspector
> No errors!
> 
> /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/js/app.js
  13:18  error  Unable to resolve path to module 'js/http'                import/no-unresolved
  14:20  error  Unable to resolve path to module 'js/screen'              import/no-unresolved
  15:31  error  Unable to resolve path to module 'js/screenshot_factory'  import/no-unresolved
  16:18  error  Unable to resolve path to module 'js/tree'  
etc....
> 

And in appium desktop it said : 

> [XCUITest] Fetching dependencies
[XCUITest] *** Checking out RoutingHTTPServer at "v1.0.1"
[XCUITest] Failed to check out repository into /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer: Could not create working directory (Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “RoutingHTTPServer” in the folder “Checkouts”." UserInfo={NSFilePath=/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer, NSUnderlyingError=0x7fb143736650 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}})

I really need this to be fixed, if anyone can help. I can't run any iOS test at the moment. 

I think something wrong with my node? Because as i want to try npm install, it said "no node modules because there is no permission to write access to node_modules"

Thank you! Any leads appreciated

**Comment by mykola-mokhnach** [comment]
> "You don’t have permission to save the file “RoutingHTTPServer” in the folder “Checkouts”."

I think the error is pretty obvious - grant write permissions for your user inside `/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent` folder

**Comment by inggiinggita** [comment]
Thanks @mykola-mokhnach i'll try
