### ISSUE TITLE
IOSTouchAction tap is not working on iOS Phone

### ISSUE THREAD

**Issue by CPPAlien** [appium/appium#10374]
## The problem
I use this code to perform a tap on the phone. It's worked on Android, but failed on iOS.
```
new IOSTouchAction(mDriver).tap(PointOption.point(x, y)).perform();
```
## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0-beta3
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: macOS Sierra, Version 10.12.6
* Node.js version (unless using Appium.app|exe): v7.8.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Details
I looked up the log when I run the tap action, the log is below.
```
[debug] [JSONWP Proxy] Proxying [POST /wda/touch/perform] to [POST http://localhost:8100/session/650520A9-A0B2-4981-9869-BD651785D24C/wda/touch/perform] with body: {"actions":[{"action":"tap","options":{"x":487,"y":619}}]}
```
Then I send the request to WDA manually, the response is successful, but there isn't action on my phone.

And I looked up the document of WDA, the tap endpoint of it is `wda/tap/0`. And it works well on my iOS phone. So did you guys get wrong?
```
curl -X POST $JSON_HEADER -d "{\"x\":\"487\",\"y\":\"619\"}" $DEVICE_URL/session/$SESSION_ID/wda/tap/0
```

**Comment by mykola-mokhnach** [comment]
Is the device in landscape or portrait? what is the iOS version? Have you tried to perform tap on element instead of sending absolute coordinates?
