### ISSUE TITLE
Device is not recognised by Appium when is try to launch Appium server programatically.

### ISSUE THREAD

**Issue by padmakarsrinivas** [appium/appium#10376]
## The problem
My device is not recognised by Appium when is try to launch Appium server programatically. It works fine when i launch the serve from Appium Desktop. 

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.8.0-beta
* Desktop OS/version used to run Appium: MAC 10.13.3
* Node.js version (unless using Appium.app|exe):5.6.0
* Mobile platform/version under test: iOS XCUITest
* Real device or emulator/simulator: Real device

## Details

I am not facing issue while starting Appium(v1.7.2) from Appium Desktop version. This only happens when i try to launch appium server from the code. 
## Link to Appium logs
https://gist.github.com/padmakarsrinivas/84ac73a06899c0897c99d31326560d9b!

## Code To Reproduce Issue 

public void startAppium(){
AppiumDriverLocalService service = AppiumDriverLocalService.buildDefaultService();
service.start();
}

**Comment by mykola-mokhnach** [comment]
This happens because of an issue/feature in Java client, which does not pick up the default env by default. Try to update the client to the recent BETA or pass set the necessary env variables in AppiumDriverLocalService manually.

Closed as non server-related.
