### ISSUE TITLE
Difference between Appium 1.7.0 and  Appium 1.6.5 ?

### ISSUE THREAD

**Issue by LGVN** [appium/appium#10375]
## The problem

I updated Appium server from 1.6.5 to 1.7.0, I see there is a difference with my result.
This is my testscript:

AppiumDriver<WebElement> driver1 = new AndroidDriver<>(new URL("http://127.0.0.1:4723/wd/hub"), caps);  
driver1.get("http://www.google.com");
 
AppiumDriver<WebElement> driver2 = new AndroidDriver<>(new URL("http://127.0.0.1:4723/wd/hub"), caps);
driver2.get("http://www.bing.com");

On Appium 1.6.5: driver1 works ok & the driver2 isn't created & throw exception :
A new session could not be created. Details: Problem getting session data for driver type AndroidDriver; does it implement 'get driverData'? 

On Appium 1.7.0: the driver2 is created successfully & driver1 was stopped & deleted.

Is it a appium issue or new feature when upgraded to 1.7.0 ?

## Environment

* Appium version: 1.6.5 & 1.7.0
* Desktop OS/version used to run Appium: Windows 10

## Note
- driver1 & driver2 runs same devices & capabilities
- not using --session-override flag
- also occur on latest Appium 1.7.2, the change comes from 1.7.0

## Log
http://textuploader.com/dgxri

**Comment by mykola-mokhnach** [comment]
1. The recent version is 1.7.2
2. It is not possible to assume anything without having the full server log.

**Comment by LGVN** [comment]
Hi @mykola-mokhnach
1. also occur on latest Appium 1.7.2, the issue comes from 1.7.0
2. Please view uploaded log file

**Comment by mykola-mokhnach** [comment]
Are you trying to start two parallel sessions? Have you seen https://github.com/appium/appium/blob/55760b7b9e1c494c6a1f22d152f0bd1fe676dae7/docs/en/advanced-concepts/parallel-tests.md ?

**Comment by LGVN** [comment]
Hi @mykola-mokhnach 
I don't want to run parallel sessions in this case.
I want the driver2 must not create & execute while driver1 is running. The driver2 only allow to run if having --session-override flag.
Appium 1.6.5: It satisfy my expect.
Appium 1.7.2: It stop driver1 & run driver2 although I don't allow session override, the --session-override flag alway effect.

**Comment by mykola-mokhnach** [comment]
It won't work this way anymore. There was a bug in earlier version, which made the described behaviour possible. Now it is not the case anymore.

**Comment by LGVN** [comment]
Hi @mykola-mokhnach
Suppose User A is using device then user B try to run test on the device and make user A disconnect.
If it's not a bug, please help me consider this case.

**Comment by mykola-mokhnach** [comment]
You can still use the previous Appium version. Or update your framework architecture.

**Comment by LGVN** [comment]
Hi @mykola-mokhnach
Appium should remove --session-override flag on 1.7.2

**Comment by mykola-mokhnach** [comment]
You are welcome to pop a PR if you think this is a bug.
