### ISSUE TITLE
Appium v1.7.2 + wd.js 1.6.2 - Deep linking not working with Expo app

### ISSUE THREAD

**Issue by degamer106** [appium/appium#10387]
## The problem

Not able to deep link into Expo app even though I'm passing a valud URL.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.7.2
* Desktop OS/version used to run Appium: Mac OSX 10.12.6
* Node.js version (unless using Appium.app|exe): Node v9.8.0 (also tried on Node v6.2.2 - same result)
* Mobile platform/version under test: iOS v11.2
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Details

The Expo.app client has a deep link capability that allows passing in a URL to your React-Native app.  This app can either be hosted remotely on Expo servers or locally on your machine (via Expo CLI tools, which runs a server).  The automation script I'm using is running on NodeJS using wd.js library.  driver.url() and driver.get() calls are throwing 'url.match() is not a function' errors.

## Link to Appium logs

https://gist.github.com/degamer106/7c03b0c5af1c9a7b43c873b7dad3e153.js

## Code To Reproduce Issue [ Good To Have ]

```
import wd from 'wd';
import { UrlUtils } from 'xdl';

jasmine.DEFAULT_TIMEOUT_INTERVAL = 180000;
const PORT = 4723;
const config = {
  platformName: 'iOS',
  deviceName: 'iPhone Simulator',
  xcodeOrgId: '58HKZG8YVV',
  xcodeSigningId: 'iPhone Developer',
  updatedWDABundleId: 'com.trinet.WebDriverAgentRunner',
  automationName: 'XCUITest',
  app: '/Users/alin/.expo/ios-simulator-app-cache/Exponent-2.3.0.app'
};

let url;
const getAppUrl = async () => {
  if (!url) {
    url = await UrlUtils.constructManifestUrlAsync(process.cwd());
  }

  return url;
};

const driver = wd.promiseChainRemote('localhost', PORT);

beforeAll(async () => {
  await driver.init(config);
  await driver.sleep(2000); // wait for app to load
  await driver.get(getAppUrl(), (err) => console.log(err));
});
```
I tried bringing the Automation configuration from another testing framework, Detox, to Appium found in this blog: https://medium.com/async-la/e2e-testing-react-native-with-detox-screenshots-595146073863. Basically, it works by:

1. Running the Expo app on the Simluator to generate a .app file in the ~/.expo/... folder
2. Copying over that Expo.app file over to the Automation project directory
3. Executing the detox script
4. Script starts by getting the URL that the expo app is being run on (i.e. exp://localhost:19000) using UrlUtils from the xdl npm library.
5. Calls the detox's device.launchApp({ url: url }) method to deep link into the Expo.app file and open your RN native app within Expo.
6. Executes the test cases

The main issue for the Appium script is that the deep linking using the latest version of Appium and wd.js fail when being executed in the Native Context on the iOS sim. This works perfectly in Detox. However, our company has a lot of work invested into Appium and we'd like to use this instead of picking up another framework.

**Comment by mykola-mokhnach** [comment]
> @mykola-mokhnach We can continue here: #10387
> 
> [HTTP] --> POST /wd/hub/session/fc47841c-0721-409c-9214-c44428cc9cec/url {"url":{"_40":0,"_65":0,"_55":null,"_72":null}}
> 
> Are you sure the URL value passed to Appium is correct?
> I got this issue even when I hardcoded "http://www.google.com"

Maybe it is a bug in wd? Can you put a breakpoint there to make sure the correct value is passed to Appium server?

**Comment by mykola-mokhnach** [comment]
Closed as not an issue. This endpoint is ok on Appium side, but it somehow receives the corrupted data from the client.
