### ISSUE TITLE
react native android keyboard open 

### ISSUE THREAD

**Issue by Saifalip** [appium/appium#10386]
## The problem
When i am click on text input box to enter something in iOS the header section will scroll up and i can see what i am typing.
But in android the section section is not able to scroll up and i can not able to see what i am typing in text input box.
The code is same for the iOS and android 
here is screen shots 

![screen shot 2018-03-21 at 9 58 24 am](https://user-images.githubusercontent.com/36480468/37714002-731cab9c-2d3e-11e8-9a0d-ca6931f41efc.png)
![screen shot 2018-03-21 at 9 58 32 am](https://user-images.githubusercontent.com/36480468/37714003-7353adc2-2d3e-11e8-904d-988fa905dab2.png)
![screenshot_20180321-095747](https://user-images.githubusercontent.com/36480468/37714004-738777c4-2d3e-11e8-88ae-f9d1b2df5411.png)
![screenshot_20180321-095749](https://user-images.githubusercontent.com/36480468/37714006-73bb1520-2d3e-11e8-98a6-943059ef5b6d.png)

Here is code 
if (Platform.OS === "ios") {
   return (
      <KeyboardAwareScrollView refreshControl={
         <RefreshControl
            colors={ ["#006FD2"] }
            refreshing={this.state.isLoading}
            onRefresh={this._refresh.bind(this)}
         />
      }
      style={{ backgroundColor: "#fbfaf9", flex: 1 }}
      showsHorizontalScrollIndicator={false}
      showsVerticalScrollIndicator={false}
      contentContainerStyle={{ flex: 1 }}>
         <View style={!this.state.data.resolution ? { flex: 0.9 } : { flex: 1 }}>
            {this._renderHeaderDetails()}
            { this._renderTabs() }
         </View>
         <View style={{ backgroundColor: "gray", height: 1 }}/>
         {this._renderFooter() }
      </KeyboardAwareScrollView>
   );
}
return (
   <View style={{ flex: 1, backgroundColor: "#fbfaf9" }}>
      <View style={!this.state.data.resolution ? { flex: 0.9 } : { flex: 1 }}>
         <View style={{ flexDirection: "row", margin: 10 }}>
            <KeyboardAwareScrollView refreshControl={
               <RefreshControl
                  colors={ ["#006FD2"] }
                  refreshing={this.state.isLoading}
                  onRefresh={this._refresh.bind(this)}
               />
            } contentContainerStyle={{ flex: 1 }}>
               {this._renderHeaderDetails()}
            </KeyboardAwareScrollView>
         </View>
         { this._renderTabs() }
      </View>
      <View style={{ backgroundColor: "gray", height: 1 }}/>
      {this._renderFooter() }
   </View>
);

**Comment by Saifalip** [comment]
can you help me

**Comment by mykola-mokhnach** [comment]
how this is related to Appium?

**Comment by Saifalip** [comment]
@mykola-mokhnach 
sorry its react native, if any one knows help me

**Comment by mykola-mokhnach** [comment]
Probably this is the not right place to look for help

**Comment by vikramvi** [comment]
@Saifalip please ask in https://discuss.appium.io
