### ISSUE TITLE
Cannot parse cpu data on getPerformanceData for cpuinfo

### ISSUE THREAD

**Issue by tfcardoso** [appium/appium#10384]
## The problem

I'm testing:

    ((AndroidDriver) driverA.getDriver()).getPerformanceData(PACKAGE,"cpuinfo",2)

and it returns

    An unknown server-side error occurred while processing the command. Original error: Unable to parse cpu data: '1.9% 14271/com.package: 0.3% user + 1.5% kernel / faults: 3 minor' (WARNING: The server did not provide any stacktrace information)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0-beta3
* Desktop OS/version used to run Appium: Windows
* Mobile platform/version under test: Android 8 
* Real device or emulator/simulator: Real Device
* Java Client: 6.0.0-BETA4

## Link to Appium logs

https://gist.github.com/tfcardoso/355aede1f8bab333ab76e5b0a341cd79

**Comment by VenkateshPS** [comment]
@tfcardoso what is the previous version where it works ?

**Comment by tfcardoso** [comment]
First time I tried.

**Comment by mykola-mokhnach** [comment]
The fix has been published to beta
