### ISSUE TITLE
Appium - Android - Real Devices - Remote Execution - ADB Command

### ISSUE THREAD

**Issue by Gnanaraj-S** [appium/appium#10382]
We have some test hooks available with our Android Mobile App. It is a service without launchable activity. I trigger this service in my Java code using 
Runtime.getRuntime().exec("adb shell am startservice com.hp.roam/com.hp.ronin.print.testhooks.TestHooksIntentService”);
When I execute this by connecting a Android real device in my laptop it works fine. But when I execute the same command against the Grid such as Sauce Labs real devices, it is not triggering the test hooks. 

My understanding is, in Remote it is not able to identify where to execute this command, in fact it doesn't even know that it is supposed to be executed in the remote. This can be achieved if I pass a Appium driver instance somehow with it.

Does Java Appium provides any way for executing the above adb command?

If not is there any other way of doing things?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): Yes
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real Devices
* Appium CLI or Appium.app|exe: Appium.app

**Comment by Gnanaraj-S** [comment]
Hi Start Activity API only works with respect to launchable activity. It will not work with activity which is not launchable.

**Comment by mykola-mokhnach** [comment]
There is also https://github.com/appium/appium/blob/fd0a0dc234998cd2b3c79a8e66b2da6e77506273/docs/en/writing-running-appium/android/android-shell.md, but it only works on local server instances.

**Comment by Gnanaraj-S** [comment]
Exactly - I am looking for something that I can execute i Remote Grid such as Sauce Labs. For achieving this I see no other way than passing the driver instances along.

**Comment by Gnanaraj-S** [comment]
As SauceLab Real devices are getting more and more popular day by day, it's an awesome functionality to have. Isn't it?

**Comment by dpgraham** [comment]
@Gnanaraj-S It's not something that can be done currently, but I could add it to our backlog for a future Appium release.

We could have a command like:

```javascript
driver.execute("mobile: startService", "com.hp.roam/com.hp.ronin.print.testhooks.TestHooksIntentService", <startServiceOpts>);
```

**Comment by mykola-mokhnach** [comment]
The `mobile: startService` and `mobile: stopService` helpers have been published to appium@beta
