### ISSUE TITLE
Screenshots not working on Android P

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#10388]
# Steps to Reproduce
* Run `appium-uiautomator2-driver` from latest master (`rm -rf node_modules && npm install && node .`)
* Open Appium Desktop and point Custom Server to 4884
* Start a session with capabilities 

```
{
  "app": "http://appium.github.io/appium/assets/ApiDemos-debug.apk",
  "platformName": "Android",
  "deviceName": "Samsung S7",
  "noReset": "true"
}
```

* The screenshot will show up as a blank screen

# Notes

* Taking screencap from adb doesn't work either

```
adb shell screencap -p /sdcard/screen.png
adb pull /sdcard/screen.png
adb shell rm /sdcard/screen.png
```

`screen.png` is a blank screen too

* Taking a screencap via the Emulator UI works

(related to https://github.com/appium/appium/issues/10360)

**Comment by mykola-mokhnach** [comment]
It looks like Google broke screencap in Android P, so it generates empty pictures now. I think we have to create an issue report for them. Here is the tool output on my emulator:

```
generic_x86:/sdcard/Download $ screencap -p screen.png                                                                        
127|generic_x86:/sdcard/Download $ cat screen.png                                                                             
?PNG

IHDR8+a?
d??IDATx????????
?ۃCA?_{?????IEND?B`?generic_x86:/sdcard/Download $ which screencap
/system/bin/screencap
```

But there's also a good news - they made it possible to record vide on emulators: https://github.com/appium/appium-android-driver/pull/345

**Comment by mykola-mokhnach** [comment]
https://issuetracker.google.com/issues/76114030

**Comment by dpgraham** [comment]
This is still happening with the latest API 29 System Image.

**Comment by KazuCocoa** [comment]
Can we close this?

Screencap attached in the description worked on Android Pie (28), revision 8, x86_64 emulator
Was able to take a screenshot via uiautomator2 and espresso driver
