### ISSUE TITLE
UiAutomator2 throws error running "java -version" command

### ISSUE THREAD

**Issue by tsibiski** [appium/appium#10389]
I am receiving an error launching the latest version of UiAutomator2 in . The error is "'java -version' exited with code 2", and occurs in "response = self.execute(Command.NEW_SESSION, parameters)"

This issue occurred on two separate Macs using the same conditions and variables.

* Appium 1.7.2
* n/a
* Mac Sierra 10.12.6
* Node.js version 8.8.1
* Galaxy S5 Android 4.1 Lollipop
* ZTE Android 4.4.2

Log: https://gist.github.com/tsibiski/aa5387e9055b17e357568a284e5dc7bf

**Comment by mykola-mokhnach** [comment]
What is the output of this command on the host machine if executed from terminal?

**Comment by tsibiski** [comment]
Here is the output, ran from bash on the machine(s) that are launching UiAutomator2.

java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

**Comment by mykola-mokhnach** [comment]
Perhaps, the java binary, which is found in appium's process PATH is different from the one, found by Terminal.

**Comment by tsibiski** [comment]
It could be. Do you have suggestions on how I might verify that? 

Could a problem arise here due to my Appium being 1.7.2 (as opposed to the newest 1.7.3) - but my UiAutomatior2 is v1.5.0?

I will try to download the version of UiAutomator2 that was released just after Appium 1.7.2 to verify that.

**Comment by mykola-mokhnach** [comment]
Verify the appium's process environment. Also, you could try to delete older Java installations, which are not used anymore, manually.

**Comment by tsibiski** [comment]
Will do. There's still the default 1.6.0 sitting in there that came with the OS.

**Comment by mykola-mokhnach** [comment]
http://flummox-engineering.blogspot.com/2016/02/uninstall-older-version-of-java-on-os-x.html

**Comment by tsibiski** [comment]
Hmmm, unfortunately that does not seem to be the problem - or it is not available as a solution. The first part of that guide says this,

"Mac installs Java 6 (1.6) by default. There are some components in Mac that depends on this version of Java, so avoid deleting any Java 1.6.x versions."

And that is the only other version of Java that I have.

**Comment by mykola-mokhnach** [comment]
Then fix your process environment and make sure appium process has correct PATH

**Comment by tsibiski** [comment]
I believe the PATH is correct. And the same issue still occurs.

I also uninstalled appium and reinstalled latest. I did the same with Android Studio and the android sdk. And I reset all of the env vars in my bash_profile.

appium-doctor says everything is okay, but it always exits with code 2 on "java -version".

**Comment by mykola-mokhnach** [comment]
> I believe the PATH is correct.

And what it is?

**Comment by tsibiski** [comment]
export PATH=export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:$HOME/bin
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/home
export PATH=$PATH:$JAVA_HOME/Contents/Home/bin
export PATH=$PATH:$JAVA_HOME/bin
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME
export PATH=$PATH:$HOME/Library/Android/sdk/tools
export PATH=$PATH:$HOME/Library/Android/sdk/platform-tools
export PATH=$PATH:$HOME/Library/Android/sdk/build-tools
export PATH=$PATH:$HOME/Library/Android/sdk/platform-tools

**Comment by mykola-mokhnach** [comment]
I was asking about the actual appium process environment, not about the config file content

**Comment by tsibiski** [comment]
In that case, I have no idea how to find it. Can you direct me to instructions on how to find the "appium process environment"?

**Comment by tsibiski** [comment]
I have been trying various things with one of the two affected Macs. Downgrading to the last version of Appium has fixed this particular issue.

**Comment by tsibiski** [comment]
I've got my automation up and running. I was forced to use two separate versions of Appium. I downloaded 1.4.0, and set up a symlink for appium-android.

And then I did one for appium-ios, and downloaded 1.6.0. Based on the device platform, I just use one or the other.

Since xcuitest driver only would work properly on 1.6.0, and uiautomator2 would only work properly for me on 1.4.0.
