### ISSUE TITLE
I want to check wifi(any network) connectivity on real android device using appium

### ISSUE THREAD

**Issue by Manikanta29** [appium/appium#10380]
Is their any appium capabilities, to check the netwotk(like wifi/4g/3g etc) connection on a connected real device. 

I have refered many forms, but didn't get any right solution. can any one help me in this regard.

**Comment by mykola-mokhnach** [comment]
Appium does not provide any standard API to get such information. You could try to get it with adb (https://stackoverflow.com/questions/13510865/adb-command-to-get-network-type-of-device) using `mobile: shell` [endpoint](https://github.com/appium/appium/blob/fd0a0dc234998cd2b3c79a8e66b2da6e77506273/docs/en/writing-running-appium/android/android-shell.md)
