### ISSUE TITLE
Select the first available device automatically if multiple parallel drivers are running at the same time

### ISSUE THREAD

**Issue by ericzered** [appium/appium#10383]
## The problem

I try to execute test on 2 real android phones on parallel, registered on the grid and plugged on the same machine, but all tests are running on the same device and brings error.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2

## Details

I've set my 2 phones in a json file, with different ports. and I've launch 2 instance of Appium, like that: 
command line : appium --relaxed-security --nodeconfig /path/to/nodes_4727_GalaxyS7.json -p 4727 --session-override -bp 4727
the json : https://gist.github.com/ericzered/1384671a334cc0f471636cf6f3aeb2d7

command line : appium --relaxed-security --nodeconfig /path/to/nodes_4728_Note3.json -p 4728  --session-override -bp 4728
the json : https://gist.github.com/ericzered/24348d80bd35f0a0c602b52cca2895dc

in my code I put the capabilities : 
  android: {
    browserName: 'chrome',
    platformName: 'Android',
    deviceName: 'Android_phone',
    orientation: 'PORTRAIT',
    newCommandTimeout: 60000,
    maxInstances: 2
  },

My code launch 2 tests in the same time. But it looks like appium launch the 2 tests in the same devices, I can see in the appium log that it uses the same udid.
I don't put a specific udid in my code because purpose is that test can be launch on every android available and if the first one is already in use, appium will select the second one.
I don't use UiAutomator2 because I'va got a Android 5.0 phone in the list, but maybe UiAutomator2 is mandatory to make parallel test with capabilities without udid in my caps ?
Thanks a lot

## Link to Appium logs

Log Appium 1 OK : 
https://gist.github.com/ericzered/6ab96279b715772c5fc553725c9809db
Log Appium 2 NOK : 
https://gist.github.com/ericzered/b9aea08ebd731361c7e42aa5195c999e

**Comment by mykola-mokhnach** [comment]
Do you follow https://github.com/appium/appium/blob/55760b7b9e1c494c6a1f22d152f0bd1fe676dae7/docs/en/advanced-concepts/parallel-tests.md ?

**Comment by ericzered** [comment]
Yes sur, as you see, I've set my ports. I've even tryed to configure systemPort in the command line as I see it in the last message here : https://github.com/appium/appium/issues/9774 (even I don't use UiAutomator2).
I wonder if it's possible to run parallel test on android by letting appium decide which phone to use...

**Comment by mykola-mokhnach** [comment]
You must explicitly set device id for each session. Appium just always take the first device it finds

**Comment by ericzered** [comment]
Like in this ticket, https://github.com/appium/appium/issues/9774, I can't tell in advance what udid I wil use, I want to run test on any available device. It looks like it was ok at the end in this ticket. Only difference with me is that he used UiAutomator2. But I have to much problem with it right now, I have to stay with the default one.

**Comment by mykola-mokhnach** [comment]
I can say it is not a bug for sure, but rather a feature request. BTW, you are welcome to create a PR yourself.

**Comment by ericzered** [comment]
Thanks, but I don't know what to put in the PR, first time for me

**Comment by saikrishna321** [comment]
@ericzered  
> I can't tell in advance what udid I wil use, I want to run test on any available device

You need to handle this on client side. You need to manage the device management pool, thats how i did this in framework https://github.com/saikrishna321/AppiumTestDistribution

**Comment by ericzered** [comment]
thanks @saikrishna321 I will look this

**Comment by jlipps** [comment]
there is an existing third party plugin which might cover some of the desired behaviour here: https://github.com/AppiumTestDistribution/appium-device-farm

**Comment by Radafae** [comment]
hey! you should try using udid instead of deviceName
