### ISSUE TITLE
getConnection returns WIFI even though it is still on cellular

### ISSUE THREAD

**Issue by risinek** [appium/appium#10399]
## The problem

I'm using method `getConnection` to check what network interface device is on, but when I am on cellular data interface and switch to wifi, it takes some time to change it, but `getConnection` method returns WIFI even though device is still on data as switching interfaces is still in progress.
Is there any other way to check or to wait, until the interface switch is finished? 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable):
* Mobile platform/version under test: Android 7
* Real device or emulator/simulator: rea
* Appium CLI or Appium.app|exe: CLI

**Comment by tfcardoso** [comment]
I'll talk about this also in my talk in AppiumConf. You can use:

    adb shell dumpsys wifi

and look for curState information. When it reaches CompletedState you are connected to Access Point.

You can use:

    driver.executeScript("mobile: shell", commandAndArgs);

to run command on remote device.

**Comment by risinek** [comment]
Cool thanks, it is working.. This is my method I use to check WiFi state:
```
private boolean isWifiStateConnected(){
	Map<String, Object> args = new HashMap<>();
	args.put("command", "dumpsys");
	args.put("args", "wifi");
	String response = (String) getAndroidProxiedDriver().executeScript("mobile: shell", args);
	return response.contains("curState=ConnectedState");
}
```

and I'm waiting for connected state in empty `while(!isWifiStateConnected());`
