### ISSUE TITLE
Android click drags down menu

### ISSUE THREAD

**Issue by WoodPlank** [appium/appium#10397]
## The problem
On some devices (LG4 and HTC) when we try to click on an element it doesn't click on the element and instead seems to drag down the menu.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Desktop OS/version used to run Appium: Windows 10
* Mobile platform/version under test: 6.0.1 for both
* Real device or emulator/simulator: real devices
* Appium CLI or Appium.app|exe: exe

## Details

One either of these devices (LG4 and HTC) any time we try to click on an element it instead opens the top menu on the Android devices.

## Link to Appium logs
Can provide later

**Comment by mykola-mokhnach** [comment]
This looks more like framework/device issue rather than something one can change in Appium.

**Comment by tfcardoso** [comment]
By LG4 you mean LG G4? Because I have one LG G4 also with Android M and used 1.7.2 in Windows 10 and didn't see that happening.

Can you share code/logs or try to make a small test with some native app so that I can replicate here in same conditions? My model is LG-H736

**Comment by WoodPlank** [comment]
@tfcardoso I can provide a gist later today. I can try some native apps over the weekend and I'll get back to you. We have a different model but it is an LG G4 on M.

It does seem to be device specific but it's happening on quite a few different devices. We have a hybrid app, I'm not sure if that will make a difference.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue.
