### ISSUE TITLE
Displayed message has "A connection to http://0.0.0.0:55515/ was leaked"

### ISSUE THREAD

**Issue by Manikanta29** [appium/appium#10396]
Mar 22, 2018 2:42:04 PM okhttp3.internal.platform.Platform log
WARNING: A connection to http://0.0.0.0:55515/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);

String port = getPortNumber();	
String bootStrapPort = getPortNumber();
service = startAppiumServer(port,bootStrapPort);

DesiredCapabilities capability = new DesiredCapabilities();
capability.setCapability("platformName", "Android");
capability.setCapability("deviceName", deviceName);
capability.setCapability(CapabilityType.VERSION, deviceOsVersion);
capability.setCapability("udid", deviceSerialNumber);
capability.setCapability("appPackage", "com.android.settings");
capability.setCapability("appActivity", ".Settings");
capability.setCapability("noReset", "true");
capability.setCapability("newCommandTimeout", 90);
capability.setCapability("unlockType", "pin");
capability.setCapability("unlockKey", "0000);
driver = new AppiumDriver<MobileElement>(service.getUrl(), capability);

executing the some functions 

driver.quit();

Appium version : 1.8.0-beta

**Comment by mykola-mokhnach** [comment]
This has nothing to do with Appium. Perhaps, related to https://github.com/appium/java-client
