### ISSUE TITLE
 I cannot executed startRecordingScreen on Android devices

### ISSUE THREAD

**Issue by garinhu** [appium/appium#10395]
## The problem
using  java-client-6.0.0-BETA4.jar cannot executed startRecordingScreen on Android devices

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Win 7 64bit
* Node.js version (unless using Appium.app|exe):9.2.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Xiaomi 4
* Appium CLI or Appium.app|exe:

## Details
using under code
static AndroidDriver<MobileElement> driver;
AndroidStartScreenRecordingOptions record = new AndroidStartScreenRecordingOptions();
record.withBitRate(2);
record.withVideoSize("640x480");
driver.startRecordingScreen(record);

here doing something...
driver.stopRecordingScreen();
If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

[HTTP] --> POST /wd/hub/session/ab5e73a9-29cc-48d4-8773-489c8a4e90e7/appium/start_recording_screen {"options":{"bitRate":2,"videoSize":"640x480"}}
[debug] [MJSONWP] Bad parameters: BadParametersError: Parameters were incorrect. We wanted **{"required":["filePath","videoSize","timeLimit","bitRate"]}** and you sent ["options"]
[HTTP] <-- POST /wd/hub/session/ab5e73a9-29cc-48d4-8773-489c8a4e90e7/appium/start_recording_screen 400 2 ms - 121 
Exception in thread "main" org.openqa.selenium.UnsupportedCommandException: Parameters were incorrect. We wanted {"required":["filePath","videoSize","timeLimit","bitRate"]} and you sent ["options"]
Command duration or timeout: 11 milliseconds

Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {androidScreenshotPath: /sdcard/screenshots/, appActivity: com.codyy.tpmp.tpmpandroid...., appPackage: com.codyy.tpmp.tpmpandroid.te, autoGrantPermissions: true, browserName: , databaseEnabled: false, desired: {androidScreenshotPath: /sdcard/screenshots/, appActivity: com.codyy.tpmp.tpmpandroid...., appPackage: com.codyy.tpmp.tpmpandroid.te, autoGrantPermissions: true, browserName: , deviceName: 5b53ee2d, newCommandTimeout: 300, noReset: true, platform: ANDROID, platformName: android, platformVersion: 7.0, resetKeyboard: true, udid: 5b53ee2d, unicodeKeyboard: true}, deviceManufacturer: Xiaomi, deviceModel: MI 4LTE, deviceName: 5b53ee2d, deviceScreenSize: 1080x1920, deviceUDID: 5b53ee2d, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, newCommandTimeout: 300, noReset: true, platform: ANDROID, platformName: ANDROID, platformVersion: 6.0.1, resetKeyboard: true, takesScreenshot: true, udid: 5b53ee2d, unicodeKeyboard: true, warnings: {}, webStorageEnabled: false}
Session ID: ab5e73a9-29cc-48d4-8773-489c8a4e90e7
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:634)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at io.appium.java_client.CommandExecutionHelper.execute(CommandExecutionHelper.java:27)
	at io.appium.java_client.screenrecording.CanRecordScreen.startRecordingScreen(CanRecordScreen.java:38)
	at com.app.test.TestDemo.main(TestDemo.java:87)

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
This will only work with appium@beta

**Comment by garinhu** [comment]
how to setting filePath parameter? in the class AndroidStartScreenRecordingOptions not method to setting the filePath.

**Comment by tfcardoso** [comment]
@garinhu I didn't test. But checking methods I see we can use:

    new ScreenRecordingUploadOptions().withRemotePath(remotePath)

maybe that's it?
