### ISSUE TITLE
POST is not returned during creating wd session.

### ISSUE THREAD

**Issue by elphienn** [appium/appium#10391]
## The problem

When running automated test script with appium + XCUITest, test is finished unexpectedly with below error message.
>> selenium.common.exceptions.WebDriverException: Message: A session is either terminated or not started

## Environment

* Appium version 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): 1.7.1
* Desktop OS/version used to run Appium: mac seirra 10.13.3
* Mobile platform/version under test: 11.2.6
* Real device or emulator/simulator: iphone X
* Appium CLI or Appium.app|exe: appium -p 4723

## Details

The test script was executed successfully 2 weeks ago.
I have no idea why below error was keep occurring.

## Link to Appium logs

[debug] [BaseDriver] Event 'wdaPermsAdjusted' logged at 1521682987832 (10:43:07 GMT+0900 (KST))
[debug] [BaseDriver] Event 'wdaStarted' logged at 1521682987832 (10:43:07 GMT+0900 (KST))
[debug] [XCUITest] Setting initial orientation to 'PORTRAIT'
[debug] [JSONWP Proxy] Proxying [POST /orientation] to [POST http://localhost:8103/session/6BEB8E52-C3ED-4146-9E96-517B7F3B4991/orientation] with body: {"orientation":"PORTRAIT"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"6BEB8E52-C3ED-4146-9E96-517B7F3B4991","status":0}
[debug] [BaseDriver] Event 'orientationSet' logged at 1521682988947 (10:43:08 GMT+0900 (KST))
[Appium] New XCUITestDriver session created successfully, session d43f2319-367b-411c-935b-6c469a2a622e added to master session list
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1521682988948 (10:43:08 GMT+0900 (KST))
[debug] [MJSONWP] Responding to client with driver.createSession() result: {"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"platformName":"iOS","platformVersion":"11.2.6","deviceName":"iPhone X","noReset":"false","fullReset":false,"app":"/Users/user/workspace/line-ui-test/LINE.ipa","autoAcceptAlerts":true,"automationName":"XCUITest","bundleId":"jp.naver.inhouse.talk","udid":"ec20ed861d4b207fb52d44811074feda8df25f63","xcodeOrgId":"VUTU7XXXXX","xcodeSigningId":"iPhone Developer","wdaLocalPort":8103}
[HTTP] <-- POST /wd/hub/session 200 32039 ms - 648 
[HTTP] --> DELETE /wd/hub/session/d43f2319-367b-411c-935b-6c469a2a622e {}
[debug] [MJSONWP] Calling AppiumDriver.deleteSession() with args: ["d43f2319-367b-411c-935b-6c469a2a622e"]
[debug] [BaseDriver] Event 'quitSessionRequested' logged at 1521682988952 (10:43:08 GMT+0900 (KST))
[Appium] Removing session d43f2319-367b-411c-935b-6c469a2a622e from our master session list
[debug] [JSONWP Proxy] Proxying [DELETE /session/d43f2319-367b-411c-935b-6c469a2a622e] to [DELETE http://localhost:8103/session/6BEB8E52-C3ED-4146-9E96-517B7F3B4991] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n\n  },\n  \"sessionId\" : \"B0F08E03-97F8-4006-B74B-BB052066FC1E\",\n  \"status\" : 0\n}"
[XCUITest] Setting '755' permissions to '/Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Attachments' folder
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [iOSLog] Stopping iOS log capture
[debug] [BaseDriver] Event 'quitSessionFinished' logged at 1521682989185 (10:43:09 GMT+0900 (KST))
[debug] [MJSONWP] Received response: null
[debug] [MJSONWP] But deleting session, so not returning
[debug] [MJSONWP] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/d43f2319-367b-411c-935b-6c469a2a622e 200 234 ms - 76 
[HTTP] --> DELETE /wd/hub/session/d43f2319-367b-411c-935b-6c469a2a622e {}
[HTTP] <-- DELETE /wd/hub/session/d43f2319-367b-411c-935b-6c469a2a622e 404 0 ms - 131 
[HTTP] --> POST /wd/hub/session {"capabilities":{"firstMatch":[{}],"alwaysMatch":{"platformName":"iOS"}},"desiredCapabilities":{"platformName":"iOS","platformVersion":"11.2.6","deviceName":"iPhone X","noReset":"false","fullReset":false,"app":"/Users/user/workspace/line-ui-test/LINE.ipa","autoAcceptAlerts":true,"automationName":"XCUITest","bundleId":"jp.naver.inhouse.talk","udid":"ec20ed861d4b207fb52d44811074feda8df25f63","xcodeOrgId":"VUTU7XXXXX","xcodeSigningId":"iPhone Developer","wdaLocalPort":8103}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","platformVersion":"11.2.6","deviceName":"iPhone X","noReset":"false","fullReset":false,"app":"/Users/user/workspace/line-ui-test/LINE.ipa","autoAcceptAlerts":true,"automationName":"XCUITest","bundleId":"jp.naver.inhouse.talk","udid":"ec20ed861d4b207fb52d44811074feda8df25f63","xcodeOrgId":"VUTU7XXXXX","xcodeSigningId":"iPhone Developer","wdaLocalPort":8103},null,{"firstMatch":[{}],"alwaysMatch":{"platformName":"iOS"}}]

**Comment by mykola-mokhnach** [comment]
I don't observe any errors in the log - the client calls createSession and then deleteSession

**Comment by elphienn** [comment]
Hi,

You mean, The reason of deleteSession is not related to the Appium?
And Is there any possibility that the similar issue on iOS 11.2.6 version?

Thanks,
Br Yubin.

**Comment by mykola-mokhnach** [comment]
> [HTTP] --> DELETE /wd/hub/session/d43f2319-367b-411c-935b-6c469a2a622e {}

This means the server has received session deletion request. from the client

**Comment by elphienn** [comment]
Thanks a lot :-)

Actually test script and test application were not changed.
Only changed part is upgraded iOS software version as 11.2.6.
I cannot find any clue on client side except for the version.

And If you have any idea for the result, Please let me know :-)

Br Yubin.
