### ISSUE TITLE
How to use for loop in javascript using appium 

### ISSUE THREAD

**Issue by Saifalip** [appium/appium#10393]
I want to use "for loop" in the javascript using appium to click every element in the array and navigate back.
Can any one suggest me what code should i use for "for loop"

Environment

* Appium version : 1.7.2
* Desktop OS/version used to run Appium : macOS 10.12.5
* Node.js version : 9.1.0
* Mobile platform/version under test: iOS 9.3
* Real device or emulator/simulator:  simulator

**Comment by mykola-mokhnach** [comment]
Please use Appium forum to ask questions
