### ISSUE TITLE
[Android] Appium Desktop Inspector is  keeping spinning and Screenshot is still stay in the previous ui 

### ISSUE THREAD

**Issue by baot20** [appium/appium#10392]
## The problem

I am using Appium Desktop to manipulate and recording scripts for a logout scenario 。 When I click a button in UI A  which will lead to a logout related UI B , the  Inspector is  keeping spinning and Screenshot is still showing UI A content. 
Please refer to the screenshot.jpg from here  : https://github.com/baot20/publicShare

## Environment
Appium version :  Appium desktop 1.4.0 (showing  Appium v1.7.2 from log)
Desktop OS/version used to run Appium: win10
Mobile platform/version under test: [ADB] Device API level: 24
Real device or emulator/simulator:  Real device 
Appium CLI or Appium.app|exe: Appium.exe

## Link to Appium logs
https://github.com/baot20/publicShare/blob/master/appium-server-logs.txt

## logcat log 
https://raw.githubusercontent.com/baot20/publicShare/master/logcat.txt

**Comment by mykola-mokhnach** [comment]
Try uiautomator2 backend

**Comment by baot20** [comment]
I  add "automationName ": "UiAutomator2" in desired capability  and start the new session . It's the same results.  And I found out if I manually click the home button in android phone and then back to the UI B which is keeping inspector spinning , inspector will stop spin and get the whole structure of the page resource. Do you have any clue why would that happen ?

**Comment by mykola-mokhnach** [comment]
I remember there was some issue report similar to this one and pressing back button was the only possible workaround. Something is happening under the hood, which makes UIA(2) framework to freeze. Nothing we can do about it on appium level.

**Comment by baot20** [comment]
Thank you for the reply. I do not understand  what  do you mean by "Something is happening under the hood" as I am quite new to the Appium.  Could you please kindly explain a bit more about that ? thank you very much .

**Comment by mykola-mokhnach** [comment]
I mean there is a bug somewhere in Google's UIAutomator framework, which, most likely, will never be fixed.

**Comment by baot20** [comment]
ok..... well I am going to  use coordinates to click the button .  Thank you very much for your reply.
