### ISSUE TITLE
npm install error, chromedriver download 407 code

### ISSUE THREAD

**Issue by bradyarthur** [appium/appium#10390]
## The problem

Hello, have experienced issue installing appium, running this command: npm install -g appium

Results in the following error and install is not successful: 

> node install-npm.js

info Chromedriver Install Installing Chromedriver version '2.36' for platform 'w
in' and architecture '32'
info Chromedriver Install Opening temp file to write chromedriver_win32 to...
info Chromedriver Install Downloading https://chromedriver.storage.googleapis.co
m/2.36/chromedriver_win32.zip...
RequestError: Error: tunneling socket could not be established, statusCode=407

## Environment

* Windows 7 Enterprise
* Node.js version v8.10.0
* Npm version 5.6.0
* proxy and secure proxy have been set in .npmrc

Have not experienced this issue installing other packages.

Is there a recommended version of node/npm to use with appium?

**Comment by mykola-mokhnach** [comment]
Duplicate https://github.com/appium/appium/issues/7163

Currently Appium does not support chromedriver download via proxy, however you can set a custom download url.
