### ISSUE TITLE
can not set language and locale on Android

### ISSUE THREAD

**Issue by waynema** [appium/appium#10409]
## The problem

I cannot set the language and locale in Android emulator automation using latest appium 1.8 beta or 1.7.2,
Here is the error log.  Is this a known issue? 

[W3C] Encountered internal error running command: Error: Failed to set language: en and country: en_US
[W3C]     at Object.callee$0$0$ (../../lib/android-helpers.js:100:11)
[W3C]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[W3C]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[W3C]     at <anonymous>

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2 and 1.8 beta3
* Last Appium version that did not exhibit the issue (if applicable): 1.6.5
* Desktop OS/version used to run Appium: Mac OS 10.13.3
* Node.js version (unless using Appium.app|exe): v8.4.0
* Mobile platform/version under test: Android 8
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: both

**Comment by mykola-mokhnach** [comment]
Country name is wrong. Closed as not an issue.

**Comment by waynema** [comment]
@mykola-mokhnach, what should be the right country name?

**Comment by mykola-mokhnach** [comment]
http://www.nationsonline.org/oneworld/country_code_list.htm

**Comment by waynema** [comment]
@mykola-mokhnach , thanks for the link. it works for US, however, it does not work for GB. 

[W3C] Encountered internal error running command: Error: Failed to set language: en and country: GB
[W3C]     at Object.callee$0$0$ (../../lib/android-helpers.js:100:11)
[W3C]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[W3C]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[W3C]     at <anonymous>

**Comment by mykola-mokhnach** [comment]
Perhaps, it is just not supported by the device

**Comment by waynema** [comment]
@mykola-mokhnach, yes, this does not support device, but works on simulator before with locale set as en_GB in 1.6.5.  But after the upgrade of 1.7.2,  the locale has to be set as US or GB, however, it seems only US is working now.  Would you consider this as a bug?

**Comment by waynema** [comment]
#9944

**Comment by lamquangthanh** [comment]
hi @waynema 
I also have issues same with you. But i try run: adb shell am broadcast -a io.appium.settings.locale --es lang ja --es country JP (you can change lang and country suitable with you). This cmd config the appium settings  before you run test.
(https://github.com/appium/io.appium.settings)
After that, change the capacibility like 	"language": "gb",
	"locale": "UK",
It runs normally.
Try to do that.

**Comment by waynema** [comment]
Thanks @lamquangthanh for the tip.  This seems to work on emulator but not on real device though

**Comment by lamquangthanh** [comment]
In my site, it works also on real devices.

**Comment by erichflock** [comment]
Would be possible to provide a list of the possible languages and locales that Appium accepts as a parameter to the capabilities MobileCapabilityType.LANGUAGE and MobileCapabilityType.LOCALE? I'm having some trouble with setting the language of Portuguese of Portugal for the Android Driver (iOS works fine).
