### ISSUE TITLE
content-desc returned by Android driver not updating when setting contentDescription of a menu Item in Android.

### ISSUE THREAD

**Issue by VenkateshPS** [appium/appium#10408]
## The problem

When I set the title of on a menu Item in Android (item.setTitle("available")), the same is reflected in content-desc when I do Androiddriver.getPageSource, but when I do (item.setContentDescription("available"))
content-desc is not updated.

what should be the correct behaviour ?
## Environment

* Appium version (or git revision) that exhibits the issue:1.8.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):7.5
* Mobile platform/version under test:Android 7
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by KazuCocoa** [comment]
Is this Android API related question?
`item.setContentDescription("available")`'s setContentDescription is https://developer.android.com/reference/android/view/View.html#setContentDescription(java.lang.CharSequence), it looks.

**Comment by KazuCocoa** [comment]
Ah, when you set content-desc using `setContentDescription`, only then Appium can't get content description via `getPageSource`.

**Comment by KazuCocoa** [comment]
Can you check the description via Appium inspector or [https://developer.android.com/studio/profile/hierarchy-viewer.html](hierarchy-viewer)? @VenkateshPS 

---

📓 for me
The root of content-desc is https://github.com/androidmirrors/android-sdk/blob/9b920d7964e96cbef87161bd8151fca329343735/sdk/android/view/accessibility/AccessibilityNodeInfo.java#L67:14 .

**Comment by VenkateshPS** [comment]
yes using setContentDescription in Android App code does not updates the content-desc returned by driver.getPageSource(). In my view this should be a defect.

content-desc is updated when i use setTitle on Android Menu Item.
