### ISSUE TITLE
Error: Unable to start WebDriverAgent session because of xcodebuild failure: "Could not proxy command to remote server. Original error: Error: read ECONNRESET

### ISSUE THREAD

**Issue by Devapal** [appium/appium#10401]
## The problem

A little backGround: I have installed and used appium on both iOS real device and cloud. After a month of smooth sail, I got the below error:
Unable to start WebDriverAgent session because of xcodebuild failure: "Could not proxy command to remote server. Original error: Error: read ECONNRESET".

Please see attached appium log
[appium-server-logs.txt](https://github.com/appium/appium/files/1839219/appium-server-logs.txt)

I am able to build the xCode projects successfully without any errors. I was also able to launch the integration app from the WebDriverAgent Project on my device from xCode.

I also tried to manually start the web driver by doing the below from **terminal**: 

`xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=67efaf3033f0625458f62ed51f8caac656f67b2d -configuration Debug -xcconfig /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Configurations/ProjectSettings.xcconfig`

**When I manually ran the above command, I see the WebDriverAgent deployed successfully on my device but Test Build Failed:**  Please see attached log: [Manually_Invoked_WebDriverAgent_Terminal.txt]  
[Manually_Invoke_WebDriverAgent_Terminal.txt](https://github.com/appium/appium-desktop/files/1839229/Manually_Invoke_WebDriverAgent_Terminal.txt)

**Please advice, I haven't changed anything, not sure why all of a sudden web driver agent is not able to start**.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): I was able to successfully launch on 1.4.0 and now even that version throws the same error. I don't think this is version specific.
* Desktop OS/version used to run Appium: 1.4.1
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium.app

**Comment by mykola-mokhnach** [comment]
Try to restart the device under test

**Comment by Devapal** [comment]
Hello,
Yes, I tried doing that several times but no luck.
I even tried to uninstall and reinstall appium with no luck. The only thing left is to re install xCode.
Any other thoughts ?

Thanks

**Comment by mykola-mokhnach** [comment]
What is in the real device log?

**Comment by Devapal** [comment]
Can you help me locate where the real device log is located ? Do i need to enable anything to fetch the real device logs or  does it fetch logs with default appium settings ?
I using the appium desktop app.

**Comment by Devapal** [comment]
mykola-mokhnach:
Interestingly it started working after I enabled the device logs. weird, I tried to compare the device logs before and after and the only difference **I see is: WDA is not listening at 'http://localhost:8100/ previously and now it says WDA sessions listening on port 8100 have been found.**

**Comment by Jitu1888** [comment]
How to handle this issue @mykola-mokhnach
