### ISSUE TITLE
driver.getPageSource() сuts the data cell

### ISSUE THREAD

**Issue by manyakin** [appium/appium#10403]
## The problem
Hey. I can not understand why driver.getPageSource () returns some of the data available to the item. In this element, the text is contained in two lines. Appium - inspector sees the full value in the element, but when the test is run or the command is executed driver.getPageSource, the data is not displayed.

![screenshot](https://user-images.githubusercontent.com/9164805/37813849-5ef56196-2e91-11e8-811f-9c26ad9d8053.png)

![getpage](https://user-images.githubusercontent.com/9164805/37814204-06d0cf12-2e93-11e8-8662-6d5b271a6e26.png)

[Appium-log.txt](https://github.com/appium/appium/files/1840388/Appium-log.txt)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2/.1.8.0-beta3
* Desktop OS/version used to run Appium: 1.4.1
* Mobile platform/version under test: IOS
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium.app

**Comment by mykola-mokhnach** [comment]
Might it be a race condition? Try to wait for a while after the search request has been executed.

**Comment by manyakin** [comment]
I tried it. Did not help.

**Comment by mykola-mokhnach** [comment]
Appium only reflects what [WDA](https://github.com/facebook/WebDriverAgent)/XCTest returns to it. There is not much we can change on Appium side.
