### ISSUE TITLE
Android apk unable to download gives 403 error

### ISSUE THREAD

**Issue by ddhamnekar** [appium/appium#10416]
## The problem

Appium used to work well until recently where it started experiencing 403 error while downloading the app from the pipeline (Jenkins build machine).

## Environment

* Appium version (or git revision) that exhibits the issue:1.7.1
* Last Appium version that did not exhibit the issue (if applicable):1.7.1
* Desktop OS/version used to run Appium:10.12.6
* Node.js version (unless using Appium.app|exe): 5.3.0
* Mobile platform/version under test:Android, 6.0.1
* Real device or emulator/simulator: Nexus 7 tablet
* Appium CLI or Appium.app|exe: Appium CLI

## Details

I am able to download the app when I hit the same URL as shown in the logs on the browser on the same machine that is experiencing issue.
I am also able to download the file using curl from terminal.

But for some reason its failing through appium. Any help would be really appreciated.

## Link to Appium logs

https://gist.github.com/ddhamnekar/ff4758fdf7481c8a6dd843c0440acaa2

**Comment by mykola-mokhnach** [comment]
this means are not authorized to download the file anymore. Please double check with your Jenkins administrator. Closed as not an issue
