### ISSUE TITLE
InstallApp method is not working in iOS

### ISSUE THREAD

**Issue by maximilianograjales** [appium/appium#10417]
## The problem

When I want to install an app using the command driver.installApp instead of using the capabilities in iOS, the answer from appium is always the same : 

[HTTP] --> POST /wd/hub/session/918befba-f4bb-4edc-a3fa-59e8baac3140/appium/device/install_app {"appPath":"/aftersale-hopper-resources/app/Despegar_iPhone.app"}
[MJSONWP] Calling AppiumDriver.installApp() with args: ["/aftersale-hopper-resources/app/Despegar_iPhone.app","918befba-f4bb-4edc-a3fa-59e8baac3140"]
[XCUITest] Executing command 'installApp'
[MJSONWP] Responding to client with driver.installApp() result: null
[HTTP] <-- POST /wd/hub/session/918befba-f4bb-4edc-a3fa-59e8baac3140/appium/device/install_app 200 2 ms - 76 

If I change the appPath for another one that doesn't exists the error is the same, so I think that the problem is about how appium is interpreting the path. I used the same method with the same path to install an apk in android and it worked correctly.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): no
* Desktop OS/version used to run Appium: Mac
* Node.js version (unless using Appium.app|exe): 5.6.0
* Mobile platform/version under test: iOS 11.0.1
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: APPIUM 6.0.0-BETA4 (Java)

## Code To Reproduce Issue [ Good To Have ]

driver.installApp("/aftersale-hopper-resources/app/Despegar_iPhone.app");
(aftersale-hopper-resources is a folder on root)

**Comment by mykola-mokhnach** [comment]
Can you try appium@beta?

**Comment by maximilianograjales** [comment]
I'm sorry @mykola-mokhnach but what is appium@beta? Is it another version of Appium? How can I try with it?

**Comment by mykola-mokhnach** [comment]
it is the most recent server version. One can install it using `npm i -g appium@beta`

**Comment by maximilianograjales** [comment]
It's the same error. I'm using Appium 1.8.0-beta3 now

**Comment by mykola-mokhnach** [comment]
Can you attach the server full log?

**Comment by maximilianograjales** [comment]
Here : https://gist.github.com/maximilianograjales/42cf8d933ac95a55ae36568dab1d2a83

**Comment by mykola-mokhnach** [comment]
> [Appium] Welcome to Appium v1.7.2

Are you sure the update to beta was successful?

**Comment by maximilianograjales** [comment]
I'm sorry, I was using Appium Desktop who uses Appium 1.7.2. 
Now I started Appium server using the command line, but it's failing when it's initializing the iOSDriver.
The command that I'm using is : appium -p 4725 -bp 4724 --session-override

This is the log : https://gist.github.com/maximilianograjales/940ad784c9ac6b756952195a56572349

**Comment by mykola-mokhnach** [comment]
Uninstall WebDriverAgent application from the device and try again
