### ISSUE TITLE
Unhandled endpoint /wda/screen

### ISSUE THREAD

**Issue by saikrishna321** [appium/appium#10411]
## The problem

Installed the latest beta3 and not able to start iOS tests, initialization of the driver fails.

## Environment

* Appium version (or git revision) that exhibits the issue:1.8.0-beta3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/saikrishna321/e5bbfb4ea84d094b8d517da82a84f645

## Code To Reproduce Issue [ Good To Have ]

```
private static void iosCaps() throws MalformedURLException {
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "11.0");
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 6");
        capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.IOS_XCUI_TEST);
        //sometimes environment has performance problems
        capabilities.setCapability(IOSMobileCapabilityType.LAUNCH_TIMEOUT, 700000);
        capabilities.setCapability(MobileCapabilityType.APP, System.getProperty("user.dir") + "/vodqa.zip");
        driver = new IOSDriver<MobileElement>(service.getUrl(), capabilities);
    }
```

**Comment by mykola-mokhnach** [comment]
The problem was in the outdated WDA binary
