### ISSUE TITLE
Getting invalid source xml for iOS App(for all tags-> name='AX error -25205') in Appium Inspector Session

### ISSUE THREAD

**Issue by prat3ik** [appium/appium#10414]
I am trying to automate the iOS app(I've got the ipa file from iTunes: https://www.youtube.com/watch?v=11rdZeCoh3g), I am setting the capabilities as per below and opening the Appium Inspector session in order to fetch the locators.

IPA file:
https://drive.google.com/open?id=1xSzvfP65rftgsStrCF9BMFl7I81XcOj2

Capabilities are:
```
{
  "platformName": "iOS",
  "platformVersion": "10.0.2",
  "deviceName": "Tim iPhone",
  "app": "/Users/harry/Downloads/Sing! 6.3.5.ipa",
  "fullReset": false,
  "noReset": true,
  "udid": "badded265a19dea8b1258392e6bf649a1ffc60ec"
}
```
After setting above desiredcapabilities on Appium Inspetor and while I click on 'Start Session' button in few seconds it will load the app perfectly but it is taking 5-6 minutes to fetch the first screenshot of the app and after that screenshot fetched it is giving the same kind of elements for all web elements.

XML for app:
![screen shot 2018-03-26 at 7 55 27 am](https://user-images.githubusercontent.com/23506005/37907079-11945928-30d2-11e8-96a2-f699d61a3e92.png)

## Environment
OS: MacOS Sierra 10.12.6
XCode Version: 9.2 (9C40b)
Appium Desktop version: Version 1.2.6
Appium Version: 1.8.0-beta3
 
I am getting this error for so many ios applications.

Appium log:
https://gist.github.com/prat3ik/5310d38ce3e9230d95e089261b606ae8

Thank you in advance!

**Comment by mykola-mokhnach** [comment]
Update to iOS 11. Closed as third-party (XCTest) issue.
