### ISSUE TITLE
Unable to toggle Location on/off in Android 7.0

### ISSUE THREAD

**Issue by NarasimhaPrasadi** [appium/appium#10410]
## The problem

1.Unable to toggle Location on/off in Android 7.0.

## Environment
java client 4.1.2
Appium 1.7.2 
Eclipse Oxygen

## Details

1.Unable to toggle Location on/off in Android 7.0.
Had used "adb shell settings put secure location_providers_allowed -network,gps" to toggle Locations
2.These adb shell commands work sometimes and not all the times in Andorid 7.0- Used J7 galaxy prime
but no problem faced in Andorid 6.0- S6 Edge

**Comment by mykola-mokhnach** [comment]
https://forum.xda-developers.com/android/help/activate-disable-gps-adb-shell-t3307417

The command format have been changed since Android 7
