### ISSUE TITLE
Context Menu Icon not recognized on iOS devices but the same menu has id on Android devices when viewed through Inspector

### ISSUE THREAD

**Issue by SantoshVenkataswamy** [appium/appium#10415]
## The problem

Hamburger Menu Icon not recognized on iOS devices even though it has id provided and can be viewed through normal inspect elements but the same menu has id displayed on Android devices when viewed through Inspector

## Environment

* Appium version (or git revision) that exhibits the issue: 1.4.1
* Last Appium version that did not exhibit the issue (if applicable): 1.1
* Desktop OS/version used to run Appium: macOS High Sierra
* Node.js version (unless using Appium.app|exe): 8.9.1
* Mobile platform/version under test: iOS 11.2
* Real device or emulator/simulator: iPhone 6/7
* Appium CLI or Appium.app|exe:

## Details

For any of the iOS devices when viewed through Inspector and pointed at the menu, whole screen is selected and accessibility id is displayed for whole screen.

## Code To Reproduce Issue [ Good To Have ]
![android_app_contextmenu](https://user-images.githubusercontent.com/28776812/37913281-09782594-3104-11e8-8e6e-d1bfa3bd32c5.JPG)
![ios_app_contextmenu](https://user-images.githubusercontent.com/28776812/37913296-11558b3a-3104-11e8-8481-c7c497079950.png)

**Comment by mykola-mokhnach** [comment]
Are you able to see the details though the standard iOS Accessibility inspector or via Voice over?

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/issues/6517 might be a duplicate

**Comment by SantoshVenkataswamy** [comment]
@mykola-mokhnach Context menu not recognized through standard iOS Accessibility inspector. when I move the cursor to identify the menu element, whole screen is selected. But the same can display id through standard Android Accessibility inspector.

**Comment by mykola-mokhnach** [comment]
If iOS Accessibility inspector is unable to identify the element then Appium for sure will not be able to distinguish it, since it is based on the same technology. Closed as not an issue.
