### ISSUE TITLE
Sendkeys not working for iOS-"Keyboard is not present"

### ISSUE THREAD

**Issue by harsh1406** [appium/appium#10418]
## The problem

Sendkeys not working for iOS-"Keyboard is not present",Unable to send text to any text field, I have tried clicking on element first and then using the sendekeys but that didn't work either.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4-beta
* Desktop OS/version used to run Appium: Mac OS(10.13.3)
* Node.js version (unless using Appium.app|exe): 9.9.0
* Mobile platform/version under test: iPhone 6+(11.1)
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI 

## Details

Unable to send text to any text field, I have tried clicking on element first and then using the sendekeys but that didn't work either.

## Link to Appium logs

INFO com.automation.common.ExtentReporterNG - Report generated Successfully
java.lang.AssertionError: expected [null] but found [org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error Domain=com.mobdefense.WebDriverAgent Code=1 "Keyboard is not present" UserInfo={NSLocalizedDescription=Keyboard is not present} (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:01:39.354Z'
System info: host: 'MPB009-HARSH-KUMAR.local', ip: '10.0.1.117', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.3', java.version: '1.8.0_121'
Driver info: io.appium.java_client.AppiumDriver
Capabilities {autoWebview: false, automationName: XCUITest, browserName: , bundleId: com.pocketgeek.ios, connectHardwareKeyboard: true, databaseEnabled: false, deviceName: iPhone 6s, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: false, newCommandTimeout: 120, platform: MAC, platformName: MAC, platformVersion: 11.1, startIWDP: true, takesScreenshot: true, udid: 14bf689595a9532ed5080f3a4d0..., webStorageEnabled: false, xcodeOrgId: 2H97L4MW4D, xcodeSigningId: iPhone Developer}
Session ID: 65d93de9-ff2a-4da9-99b7-840e534300fd]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotSame(Assert.java:509)
	at org.testng.Assert.assertNull(Assert.java:445)
	at org.testng.Assert.assertNull(Assert.java:434)
	at com.automation.appium.IOSMobile.insertText(IOSMobile.java:1512)
	at com.automation.common.TestCase$AppiumMobileIOSApplication.sendText(TestCase.java:2592)
	at smokeTestSuite.TechPHDiOSTestRepo.Onboarding(TechPHDiOSTestRepo.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

**Comment by mykola-mokhnach** [comment]
If the keyboard is not shown there is nothing we can do on Appium side. You could try to use the most recent Appium 1.8.0@beta. In case it still does not work then report an issue to Apple.

**Comment by hujosh** [comment]
@mykola-mokhnach 

Do you represent Appium? If yes, then how disappointing. This keyboard bug renders your product totally and completely unusable. You'd think that you'd be a little more concerned and motivated to get to the bottom of this...

'reporting to apple' 

Why don't you report this to apple? Do you care about your product actually working?

**Comment by mykola-mokhnach** [comment]
No, I don't represent Appium myself. I'm just one of its developers.

Regarding the bug. We do create issue reports, but usually Apple does not care much about these. Perhaps, they start to care if more people complain about the same issue.

All in all, this is open source tool and you like everyone else own all the necessary instruments to potentially address the problem. Or you can switch to a paid Appium alternative, pay several thousands per year and be happy about their enterprise support.

**Comment by KiranKNarayana** [comment]
I have been facing the exact same issue running tests on native iPhone device (iOS11.3) with Appium v1.7.1
Error Domain=com.facebook.WebDriverAgent Code=1 "Keyboard is not present" UserInfo={NSLocalizedDescription=Keyboard is not present} (WARNING: The server did not provide any stacktrace information)

**Comment by MangaSans** [comment]
This was happening to me with Simulator for some reason (Had to use the Shift+Cmd+K before), I added driver.getKeyboard(); before the sendkey code and works now. I have yet to try it on physical hardware though.

**Comment by BrainiacOfThemyscira** [comment]
I have the same issue, Could somebody please help?

**Comment by Manikandan1992-wipro** [comment]
Sendkeys is not working in Appium 1.7. and 1.8.0 for Ios Automation Any other solution for the same
@mykola-mokhnach, please provide

**Comment by EfiMaZa** [comment]
https://www.youtube.com/watch?v=jA0aT24kL-8

**Comment by VivaLosDoyers** [comment]
@hujosh could you please provide an Automator sample that does this? I tried creating an AppleScript to both invoke the menu item and use the keystroke. Neither case was possible as the latest Simulator doesn't have those commands in its dictionary.

**Comment by hujosh** [comment]
![screen shot 2018-10-11 at 5 03 15 pm](https://user-images.githubusercontent.com/17036601/46783854-933f4680-cd77-11e8-928e-cd2d7c4e1fed.png)

**Comment by VivaLosDoyers** [comment]
@hujosh thanks a lot for the sample. I ended up figuring that out on my own. FWIW you can also directly call osascript and pass the applescript to it. 

This also has the advantage of working in the Simulator no matter which device or iOS version its running.
In Ruby:

```
 %x(`osascript -e 'tell application "Simulator" to activate'`)
 %x(`osascript -e 'tell application "System Events" to key code 40 using {shift down, command 
down}'`)
# key code 40 -> K
```

In my case though, I had to explicitly tell it to reveal the software keyboard for this to work consistently (hence the shift-cmd-k).

**Comment by mjm987mj** [comment]
If you make sure that the physical keyboard is shown on the simulator then sendkeys will work. You can do this by opening the simulator then go to hardware/keyboard and then untick the use hardware keyboard (which is your mac keyboard)

**Comment by lvconley** [comment]
mjm987mj  is correct. This problem was really blocking me, but if you click on the element you want to send text to--the keyboard will appear. At this point, the sendKeys() method will work. It will not work unless the keyboard is visible. Sometimes however, I found that clicking on the element also had to be followed by a driver.getKeyboard() call as well or I would get the "Keyboard is not present" error.

**Comment by ckzgraphics** [comment]
Faced this behaviour on local iOS device with Appium 1.10.1. **This is a known issue on WebDriverAgent** | [https://github.com/facebookarchive/WebDriverAgent/issues/574](https://github.com/facebookarchive/WebDriverAgent/issues/574)

There are a few workarounds mentioned on the link.

**Comment by RakeshSamal37** [comment]
Same Issue **Error Domain=com.facebook.WebDriverAgent Code=1 "Keyboard is not present" UserInfo={NSLocalizedDescription=Keyboard is not present}** 
I am getting while dealing with the number keypad while entering the phone number on a REAL DEVICE (iOS 13.1). The phone number is init with country code +1

Any suggestions, please?

**Comment by Proryanator** [comment]
Interestingly enough, we know about the physical keyboard part, which should break the first time a test tries to send keys.

Has anyone seen where they can send keys to almost any other part of the app, but not _a certain page_? I'm experiencing that now and it's odd.

The pages use the same component design, so nothing should be different, even the locators are the exact same. However, occasionally I get that 'Keyboard is not present' only on that page :/

Weird.

**Comment by ashu123mae** [comment]
1.Use action class, & key events to perform keyboard operations ; or
2.Use capabilities to show keyboard : set as True; capabilities.setCapability("unicodeKeyboard", true) ; or
3. Best ask dev team to add specific keyboard listener in thier code & enable keyboard option in app; or
4. Use appium inspector to locate attribute element to perform action on keyboard; or

e.g.
driver.pressKeyEvent(66) or driver.pressKeyEvent(AndroidKeyCode.ENTER)
Driver.sendKeyEvent(66
driver.execute(“mobile:keyevent”, “keycode:66”);

**Comment by Chetantn** [comment]
Hi All,
Facing the same issue During AppleTv(tvOS) App automation on Real Device.

I have automated the AppleTV app and I have identified the elements, operation was performed successfully and my tests were running successfully on CI. But After I took latest Appium version(1.17.1) I'm getting this " Keyboard is not present" UserInfo={NSLocalizedDescription=Keyboard is not present} " exception. whenever I'm trying to identify some element and perform send key() operation. 

Scenario:
1.This is a very basic operation I'm performing on element i.e identifying element by name and performing sendKeys() operation. before new version of Appium it was working but post update to latest version getting this issue. 

Already I have tried all the solution mentioned above but no loock. Even tvOS version got updated. I'm not sure whether it is braking due to Appium or tvOS update.

please suggest me some work around.


![Screenshot 2020-06-15 at 3 10 13 PM](https://user-images.githubusercontent.com/62075128/84642834-a88c5100-af1a-11ea-845d-b20ad3708af4.png)

**Comment by NavdeepSingh09** [comment]
I got the same problem on a physical device OS-13.6, appium- 1.17.1, Can anyone please provide a solution

**Comment by Chetantn** [comment]
My issue was resolved, when i focused on the "next" button by performing "down" keyboard action, after that i'm able to perform the action on that element 💯 👍

Note: For AppleTV users, when you update the tvOS to latest one, you may get the different keyboard layout. based on the screen size, in that case may be you have to perform the "Right" keyboard action to get the next button focused.

**Comment by jddeltoro** [comment]
I'm facing the same problem, Appium 1.17.0 on a Real device, the keyboard is there, i'm able to detect the element, but sendKeys o click both fail.

`org.openqa.selenium.InvalidElementStateException: Error Domain=com.facebook.WebDriverAgent Code=1 "The on-screen keyboard must be present to send keys"`

![image](https://user-images.githubusercontent.com/2736884/96277564-ce019800-0faa-11eb-9458-19e93847f847.png)

**Comment by JunhoTT** [comment]
> I'm facing the same problem, Appium 1.17.0 on a Real device, the keyboard is there, i'm able to detect the element, but sendKeys or click actions both fail.
> 
> `org.openqa.selenium.InvalidElementStateException: Error Domain=com.facebook.WebDriverAgent Code=1 "The on-screen keyboard must be present to send keys"`
> 
> ![image](https://user-images.githubusercontent.com/2736884/96277564-ce019800-0faa-11eb-9458-19e93847f847.png)

Hi, did you fix this issue, I have exactly same error as you.

**Comment by KiranKNarayana** [comment]
Upgrade the Appium to the latest version and of course in conjunction with
your Mac+XCode. This should resolve the issue.
