### ISSUE TITLE
Question - Issues with iOS/Appium or my Application?

### ISSUE THREAD

**Issue by siggerzz** [appium/appium#10413]
**Test Scenario**
Setting the following values to update a button within the UI of my application:

![image](https://user-images.githubusercontent.com/14013357/37904229-041e235c-30f3-11e8-9be2-aad452c566a2.png)

**Expected Outcome**

When manually testing or using Appium on Android, If I set the button text to 'My new button text!' and then click the save button, the following network request is made:

![image](https://user-images.githubusercontent.com/14013357/37904191-e303df40-30f2-11e8-9157-998f7a21c13c.png)

![image](https://user-images.githubusercontent.com/14013357/37904096-7b1cfe2a-30f2-11e8-901a-7b8d18db86ec.png)

and my button is updated in the UI:

![image](https://user-images.githubusercontent.com/14013357/37904111-8b6fd234-30f2-11e8-8698-f7c7f451e9b4.png)

## The problem

If however I do the same on iOS, the following occurs:

Button value is updated and save button is clicked:
![image](https://user-images.githubusercontent.com/14013357/37904652-5acd6c66-30f4-11e8-98a6-d730738651d9.png)

However the following network request is made (Notice the lack of value for the 'text' key):

![image](https://user-images.githubusercontent.com/14013357/37904713-8315b278-30f4-11e8-8a25-e1dcee5d2191.png)

The button text also isn't updated within the UI:

![image](https://user-images.githubusercontent.com/14013357/37904819-c27f0f5e-30f4-11e8-967f-6f19c1a30fab.png)

And when opening the panel where the values are set, both the Button Text field is now blank, despite the other changes being persited:

![image](https://user-images.githubusercontent.com/14013357/37904865-eb316e06-30f4-11e8-8815-7fc5716cc2df.png)

It'd be great to know if this is an issue with iOS/Appium or my application. I've been seeing this problem since Appium 1.6.5. The majority of my iOS tests work fine, however I can't see the cause for this issue, as it works fine across all platforms (including iOS) when tested manually, and works with Android + Appium. I've only ever seen it when using Appium on iOS. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): n/A
* Desktop OS/version used to run Appium: MacOS High Sierra
* Node.js version (unless using Appium.app|exe): 9.4.0
* Mobile platform/version under test: iOS 11.0.3
* Real device or emulator/simulator: Real Device (Same occurs on simulator)
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

Will update with logs soon!

**Comment by mykola-mokhnach** [comment]
Try to add some delays/timers to make sure it is not a race condition issue.

**Comment by siggerzz** [comment]
@mykola-mokhnach Doesn't seem to be the issue. I've added a 5 second wait after each use of SendKeys() aswell as before/after clicking the save button
