### ISSUE TITLE
Unable to run Java tests after appium 1.7.2 upgrade

### ISSUE THREAD

**Issue by damitas** [appium/appium#10420]
## The problem

I am getting a error when trying to execute my java tests after upgrading to appium 1.7.2

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable):1.7.1 and WD v1.1.3
* Desktop OS/version used to run Appium: MacOs 10.13.2
* Node.js version (unless using Appium.app|exe):8.9.1
* Mobile platform/version under test:11.2
* Real device or emulator/simulator: IOS Simulator version 10 - iPhone 6
* Appium CLI or Appium.app|exe:
* WD:1.6.1
*yarn: 1.3.2

**Java**
cucumber-junit - v1.2.5
junit - v4.12
io-appium java-client - v5.0.4
maven-compiler-plugin - 1.7

## Details

After upgrading my package.json to latest WD (1.6.1) and Appium (1.7.2) using YARN not npm I can no longer run my tests, each test fails with the following 
`Encountered internal error running command: TypeError: (0 ,_appiumBaseDriver.processCapabilities) is not a function`

When starting the Appium client (v1.7.2) via the desktop application my tests execute successfuly.
When starting the Appium client (v1.7.2) via command line in the install dir ( node_modules/.bin/appium) the client starts successfully listening on port 4273 but the tests do not execute - the above error is displayed.

## Link to Appium logs

https://gist.github.com/damitas/866249ac6654c7372f4c1f868b64ddf0.js

## Code To Reproduce Issue [ Good To Have ]

`mvn test -Dtest=CukesTestRunner  -Dplatform='iPhoneSim' -Dcucumber.options='--tags @iPhone'`

**Driver Create code**
```
import io.appium.java_client.AppiumDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
public static AppiumDriver getInstance() {
        return driverInstance;
    };

    public static void createDriver() {
        
        DesiredCapabilities caps = getCaps();
        try {
            driverInstance = new AppiumDriver (new URL("http://127.0.0.1:4723/wd/hub"), caps);
            driverInstance.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
	}
```

**Comment by mykola-mokhnach** [comment]
> After upgrading my package.json to latest WD (1.6.1) and Appium (1.7.2) using YARN not npm I can no longer run my tests, each test fails with the following

We do not support yarn, so I can only suggest to try it with npm.

**Comment by damitas** [comment]
@mykola-mokhnach thanks for your reply.  Our build process is based on yarn so npm is causing me huge problems for our Android and IOS builds!  The previous version 1.7.1 worked fine with Yarn, do you possibly have any further details of what you do not support in yarn?  Incidentally my tests work if I start appium v1.7.2 via the desktop application, via command line appium the client starts successfully but the tests fail with the above error.

**Comment by mykola-mokhnach** [comment]
I haven't ever seen any similar reports before, so I don't think it is something, that can be changed in Appium itself.

**Comment by mykola-mokhnach** [comment]
Closed as client side issue.
