### ISSUE TITLE
Modal window is not visible to Appium with  android browser application. 

### ISSUE THREAD

**Issue by yzhangvitalconnect** [appium/appium#10426]
## The problem
Modal window is not visible to Appium with  android browser application. 

## Environment
{
  "platformName": "android",
  "platformVersion": "6.0.1",
  "appPackage": "com.android.browser",
  "appActivity": ".BrowserActivity",
  "deviceName": "10.0.32.96:5555"
}
* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

The application runs on android build in browser. The Appium show App Source for normal page
<android.widget.FrameLayout resource-id="com.android.browser:id/webview_wrapper">
<android.webkit.WebView>
<android.webkit.WebView content-desc="Config App.">

BUT,  the MODAL window's app source is not visible.

**Comment by mykola-mokhnach** [comment]
Do you switch to the webview before checking window presence? Can you attach the full server log?

**Comment by yzhangvitalconnect** [comment]
It's always in webview, let me know where I should do the switch. 

thanks. [appium-server-logs.txt](https://github.com/appium/appium/files/1856829/appium-server-logs.txt)

[test.py.txt](https://github.com/appium/appium/files/1856834/test.py.txt)

**Comment by yzhangvitalconnect** [comment]
This is the screen shot/log when I run the test using Appium play book. 

![screen shot 2018-03-28 at 9 31 46 am](https://user-images.githubusercontent.com/37850892/38043071-e45a0ab2-326a-11e8-8cc5-34897c92c23e.png)
[appium-server-logs2.txt](https://github.com/appium/appium/files/1856851/appium-server-logs2.txt)

**Comment by yzhangvitalconnect** [comment]
Thanks a lot. I updated info at
https://github.com/appium/appium/issues/10426

**Comment by mykola-mokhnach** [comment]
> My app is Web app (browser only), not native app or Hybrid app
> "appPackage": "com.android.browser",
> "appActivity": ".BrowserActivity",

Then you must fix you capabilities to run it not in native context. Read http://appium.io/docs/en/writing-running-appium/web/mobile-web/ for more details

**Comment by yzhangvitalconnect** [comment]
Can you be more specific what capability I should use. I am new to Appium,

**Comment by yzhangvitalconnect** [comment]
our browser is the build-in browser from android 6.0

**Comment by mykola-mokhnach** [comment]
I've provided everything you need. Please use discuss.apppium.io to ask question, since here we only solve issues.

**Comment by yzhangvitalconnect** [comment]
HI, Mykola,

Thanks a lot for your help. But as you mentioned in your previous reply

'''

My app is Web app (browser only), not native app or Hybrid app
"appPackage": "com.android.browser",
"appActivity": ".BrowserActivity",

Then you must fix you capabilities to run it not in native context. Read
http://appium.io/docs/en/writing-running-appium/web/mobile-web/ for more
details

'''

I already set the cap to run it in native context. Here is the capability
set

{
  "platformName": "android",
  "platformVersion": "6.0",
  "deviceName": "10.0.32.96:5555",
  "browserName": "Browser"
}


The problem still exists. The modal window cannot visible through
appium and appium desktop. Same problem.
