### ISSUE TITLE
Dynamic port for chrome driver using Appium service Builder 

### ISSUE THREAD

**Issue by prateekchawla** [appium/appium#10421]
## The problem

Not able to make chrome driver port dynamic using Appium service builder. It is opening on default 9515 every time.

## Environment

* Appium version (or git revision) that exhibits the issue:1.4.16
* Last Appium version that did not exhibit the issue (if applicable):NA
* Desktop OS/version used to run Appium: Windows 7
* Node.js version (unless using Appium.app|exe): NA
* Mobile platform/version under test: Any
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: exe

## Details

I need to open Appium on different chrome driver ports for parallel devices using appium service builder.

## Link to Appium logs

<script src="https://gist.github.com/prateekchawla/c472590be97093fbcf6645a17bf0998c.js"></script>

## Code To Reproduce Issue [ Good To Have ]

            OptionCollector argCollector = new OptionCollector().AddArguments(AndroidOptionList.ChromeDriverPort(openPort));
            AppiumLocalService service;
            service = new AppiumServiceBuilder().WithIPAddress(ConfigurationManager.AppSettings["AppiumIpAddress"]).WithLogFile(new FileInfo(ConfigurationManager.AppSettings["AppiumLogFilePath"] + DateTime.Now.ToString("_HHmmss") + ".txt")).UsingAnyFreePort().WithAppiumJS(new FileInfo(ConfigurationManager.AppSettings["AppiumJSPath"])).UsingDriverExecutable(new FileInfo(ConfigurationManager.AppSettings["AppiumNodePath"])).WithArguments(argCollector).Build();
            service.Start();

 DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities.SetCapability(CapabilityType.BrowserName, "Chrome");
            capabilities.SetCapability("automationName", "Appium");   //Selendroid
           capabilities.SetCapability("app", "http://google.com");
            capabilities.SetCapability("Device", "Android");
            capabilities.SetCapability("udid", DeviceId);
            capabilities.SetCapability("platformName", "Android");
            capabilities.SetCapability("deviceName", DeviceName);
            capabilities.SetCapability("newCommandTimeout", 240);

            objMobileBrowser = new Mobile_Browser(serviceUrl, capabilities);
            objMobileBrowser.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(50000));

**Comment by mykola-mokhnach** [comment]
Appium v1.4.16 is outdated. Please use the most recent one.

**Comment by prateekchawla** [comment]
@mykola-mokhnach I think this is the latest version for the appium app. I am not using appium CLI. 
I need to know if there is a way to send chrome driver port using appium service builder

**Comment by mykola-mokhnach** [comment]
The latest one is 1.8.0-beta. the version you have is several years old. You could try to ask on discuss.appium.io if you want to still use it.

**Comment by prateekchawla** [comment]
Thanks @mykola-mokhnach  Just for information. Are you talking about 1.8.0-beta as a command line appium tool ?
