### ISSUE TITLE
Automating: Text entered in a textbox is not stored while proceeding to next screen only on iOS hybrid app

### ISSUE THREAD

**Issue by dineshkumarskr** [appium/appium#10428]
When we enter a text in a textbox using selenium webdriver, it enters the desired text in the field but when it progresses to next screen the value entered is not stored or retained. This is happening only in iOS hybrid app as well as safari browser. But in other apps like Android hybrid app and chrome the value which we enter in the same text field is retained and carried to the next screen. Why it is behaving as such?

But when we try manually in iOS hybrid app using Xcode simulator it is working fine. Only through selenium webdriver, we are facing the above issue.

## Environment

* Appium version (or git revision) that exhibits the issue: V1.2.7
* Desktop OS/version used to run Appium: MAC OS 10.12 and Windows 7
* Mobile platform/version under test: iOS 11.2
* Real device or emulator/simulator: Xcode Simulator & Sauce labs simulator

**Comment by mykola-mokhnach** [comment]
I assume this happens, because the automated script does not generate some events, which are expected by the application under test. Add more debug output there to see which events are missing in comparison to when the action is done manually.
