### ISSUE TITLE
Automation: After switching to Webview context in Appium, DatePickerWheel native element is not showing up in iOS hybrid app

### ISSUE THREAD

**Issue by dineshkumarskr** [appium/appium#10431]
Our app is built with web-view cordova plugin, so we use switch context to switch to web-view to find elements and handle the same. We successfully handled all the web view elements but once we click the date a native element "DatePickerWheel" should be displayed. But which is not displaying in the app after clicking the date field.

After clicking we switched to native context but still our scripts failed.

Whether handling native app elements after switching to and fro between web-view and native context is possible in iOS hybrid app using appium/selenium?

Note: The above scenario works in same Android hybrid app only iOS platform we are facing the above issue

Environment

Appium version (or git revision) that exhibits the issue: V1.2.7
Desktop OS/version used to run Appium: MAC OS 10.12 and Windows 7
Mobile platform/version under test: iOS 11.2
Real device or emulator/simulator: Xcode Simulator & Sauce labs simulator

**Comment by mykola-mokhnach** [comment]
Sorry, but the description is not very cleat. Can you attach some screenshots and logs to make it more clear?
