### ISSUE TITLE
Session doesn't start on iOS 11.2 - Xcode 9.2

### ISSUE THREAD

**Issue by lucialuzuriaga** [appium/appium#10433]
## The problem

I've been testing without issues for several months on my app. Build target up to now had been iOS 10.3 and built using Xcode 8. After the app finally switched to iOS 11.2 SDK and Xcode 9, WebDriver Agent Runner fails to start a session. App is installed, Runner is installed, but the tests never run. This is 100% reproducible using Appium Desktop 1.4.0, and partially reproducible with Appium CLI 1.7.2. If I close and restart Appium many times or delete both app and runner, it may get to work once, and then stop working again on the next test run. 

I built the WebdriverAgent project with Xcode 9.2 without issues. I didn't perform ANY changes to my setup asides from changing the .app file building it with Xcode 9.2. After encountering this, I reinstalled Appium CLI, Appium Desktop, updated all my Homebrew packages, but the problem persists. 

## Environment

* Appium version: Appium Desktop 1.4.0, Appium 1.7.2.
* Last Appium version that did not exhibit the issue (if applicable): Same version
* Desktop OS/version used to run Appium: Mac Mini - OSX 10.13.3 High Sierra
* Node.js version: v8.9.4
* Mobile platform/version under test: iOS Simulator (iPhone 6s)
* Real device or emulator/simulator: iOS Simulator (iPhone 6s)

## Capabilities
        capabilities.setCapability("platformName", "iOS");
        capabilities.setCapability("deviceName", "iPhone 6s");
        capabilities.setCapability("platformVersion", "11.2");
        capabilities.setCapability("app", "/Users/***/Downloads/***.app");
        capabilities.setCapability("orientation", "PORTRAIT");
        capabilities.setCapability("automationName", "XCUITest"); (This line was added after the issue started happening - didn't use it with previous Xcode version)
        capabilities.setCapability("appiumVersion", "1.7.2");

## Link to Appium logs

Please find GIST here: https://gist.github.com/lucialuzuriaga/f58150f347ec8522766bd56cd5e9d6a1

**Comment by mykola-mokhnach** [comment]
I don't observe any issues in the log. However, what you can try - Delete the WebDriverAgent application manually from the device and then try to build and deploy it there directly from Xcode.

**Comment by lucialuzuriaga** [comment]
@mykola-mokhnach I am able to build the WebDriverAgent through Xcode, but I cannot seem to find a way to deploy it, nor run it, despite choosing the simulator as target. I just get "Build succeeded". Under "Product" the Run option is greyed out.

**Comment by mykola-mokhnach** [comment]
Are you able to manually install and execute your application under test on the same simulator?
Can you also attach simulator logs?

**Comment by lucialuzuriaga** [comment]
@mykola-mokhnach yes, I can manually install and execute the application on the simulator. This is done via command line, using Titanium Framework. 

Here are the simulator logs. I cut it short to the last two days. Just in case it's useful, this Mac mini is ridiculously slow and I rebooted the simulator a couple of times this week (even more times to check if it solved the problem that I'm having).
https://gist.github.com/lucialuzuriaga/30993b2c9cb7663febd04117f66eca2b

**Comment by mykola-mokhnach** [comment]
>  This is done via command line, using Titanium Framework.

Try with `xcrun simctl install <apppath>` instead

> https://gist.github.com/lucialuzuriaga/30993b2c9cb7663febd04117f66eca2b

this log does not contain any useful information. Please get the one from Appium with `showXcodeLog ` and `showIOSLog` capabilities enabled.

**Comment by lucialuzuriaga** [comment]
@mykola-mokhnach I could install the app on the simulator, using xcrun command, without problems. 

Here's the log with Xcode and iOS logs enabled while attempting to run a test: https://gist.github.com/lucialuzuriaga/c74d6b886549b0e4a01dcefebe57d183

**Comment by mykola-mokhnach** [comment]
I assume the problem lies in the application itself. Looks like XCTest manager cannot get the accessibility information from. I have no idea why, though:

> [info] [Xcode] Test Suite 'All tests' started at 2018-03-28 15:45:13.461
> [info] [Xcode] Test Suite 'WebDriverAgentLib.framework' started at 2018-03-28 15:45:13.465
> [info] [Xcode] Test Suite 'WebDriverAgentLib.framework' passed at 2018-03-28 15:45:13.466.
> [info] [Xcode] 	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.001) seconds
> [info] [Xcode] Test Suite 'WebDriverAgentRunner.xctest' started at 2018-03-28 15:45:13.467
> [info] [Xcode] Test Suite 'UITestingUITests' started at 2018-03-28 15:45:13.468
> [info] [Xcode] Test Case '-[UITestingUITests testRunner]' started.
> [info] [Xcode]     t =     0.02s Start Test at 2018-03-28 15:45:13.498
> [info] [Xcode]     t =     0.02s Set Up
> [info] [Xcode] 2018-03-28 15:45:13.514011+0200 WebDriverAgentRunner-Runner[41086:9779626] Built at Mar 28 2018 15:22:54
> [info] [Xcode] 2018-03-28 15:45:13.562789+0200 WebDriverAgentRunner-Runner[41086:9779626] ServerURLHere->http://192.168.12.211:8100<-ServerURLHere
> [info] [Xcode]     t =     0.21s Open net.roamler
> [info] [Xcode]     t =     0.21s     Launch net.roamler
> [info] [Xcode]     t =     0.70s         Wait for net.roamler to idle
> [info] [Xcode]     t =    60.79s             App event loop idle notification not received, will attempt to continue.
> [info] [Xcode]     t =    60.79s             App animations complete notification not received, will attempt to continue.
> [info] [Xcode] 2018-03-28 15:47:21.045422+0200 WebDriverAgentRunner-Runner[41086:9779626] Enqueue Failure: Failed to get attributes within 65.0s: (
> [info] [Xcode]     1001
> [info] [Xcode] ) /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
> [info] [Xcode] 2018-03-28 15:47:21.045984+0200 WebDriverAgentRunner-Runner[41086:9779626] Enqueue Failure: Neither attributes nor error returned /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
> [info] [Xcode] 2018-03-28 15:47:21.046402+0200 WebDriverAgentRunner-Runner[41086:9779626] Enqueue Failure: Failure to determine system application: (null) /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
> [info] [Xcode] 2018-03-28 15:48:26.078634+0200 WebDriverAgentRunner-Runner[41086:9779626] Enqueue Failure: Failed to get attributes within 65.0s: (
> [info] [Xcode]     1102
> [info] [Xcode] ) /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
> [info] [Xcode] 2018-03-28 15:48:26.079165+0200 WebDriverAgentRunner-Runner[41086:9779626] Enqueue Failure: Neither attributes nor error returned /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
> [info] [Xcode] 2018-03-28 15:48:26.079728+0200 WebDriverAgentRunner-Runner[41086:9779626] Enqueue Failure: Failure getting list of active applications: (null) /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
> [info] [Xcode] 2018-03-28 15:49:31.212089+0200 WebDriverAgentRunner-Runner[41086:9779626] Enqueue Failure: Failed to get attributes within 65.0s: (
> [info] [Xcode]     1001
> [info] [Xcode] ) /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
> [info] [Xcode] 2018-03-28 15:49:31.212936+0200 WebDriverAgentRunner-Runner[41086:9779626] Enqueue Failure: Neither attributes nor error returned /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
> [info] [Xcode] 2018-03-28 15:49:31.215274+0200 WebDriverAgentRunner-Runner[41086:9779626] Enqueue Failure: Failure to determine system application: (null) /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
> [info] [Xcode] 2018-03-28 15:50:36.310478+0200 WebDriverAgentRunner-Runner[41086:9779626] Enqueue Failure: Failed to get attributes within 65.0s: (
> [info] [Xcode]     1102
> [info] [Xcode] ) /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
> [info] [Xcode] 2018-03-28 15:50:36.310977+0200 WebDriverAgentRunner-Runner[41086:9779626] Enqueue Failure: Neither attributes nor error returned /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
> [info] [Xcode] 2018-03-28 15:50:36.311657+0200 WebDriverAgentRunner-Runner[41086:9779626] Enqueue Failure: Failure getting list of active applications: (null) /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
> [info] [Xcode]     t =   322.84s Unable to monitor animations
> [info] [Xcode]     t =   322.84s Unable to monitor event loop
> [info] [Xcode]     t =   322.94s Find the Application "com.apple.springboard" 0x6040002a1740
> [info] [Xcode]     t =   322.94s     Snapshot accessibility hierarchy for app with pid 36004
> [info] [Xcode]     t =   323.17s Open net.roamler
> [info] [Xcode]     t =   323.17s     Launch net.roamler
> [info] [Xcode]     t =   323.36s         Wait fo

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing that can be done on Appium side to resolve this. Try to report the issue to Apple or to https://github.com/facebook/WebDriverAgent and provide them the device log above
