### ISSUE TITLE
installed the appium with the desired chromedriver version, but still failed  Failed to start Chromedriver session: A new session could not be created. (Original error: session not created exception: Chrome version must be >= 60.0.3112.0 (Driver info:

### ISSUE THREAD

**Issue by yzhangvitalconnect** [appium/appium#10438]
## The problem

I installed appium with
npm install appium --chromedriver_version="2.33" --verbose -g

the version is

/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver
--version

ChromeDriver 2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2)

But still failed to start the session of appium.

/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver
[Chromedriver] Killing any old chromedrivers, running: pkill -15 -f
"/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver.*--port=8000"
[Chromedriver] No old chromedrivers seemed to exist
[Chromedriver] Cleaning any old adb forwarded port socket connections
[ADB] List forwarding ports
[ADB] Running '/Users/yzhang/Library/Android/sdk/platform-tools/adb' with
args: ["-P",5037,"-s","10.0.32.96:5555","forward","--list"]
[Chromedriver] Spawning chromedriver with:
/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver
--url-base=wd/hub --port=8000 --adb-port=5037 --verbose
[Chromedriver] Chromedriver version: '2.33.506106'
[JSONWP Proxy] Proxying [GET /status] to [GET
http://127.0.0.1:8000/wd/hub/status] with no body
[JSONWP Proxy] Got response with status 200:
"{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Mac
OS X\",\"version\":\"10.13.3\"}}}"
[JSONWP Proxy] Proxying [POST /session] to [POST
http://127.0.0.1:8000/wd/hub/session] with body:
{"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.browser","androidActivity":"com.android.browser.BrowserActivity","androidDeviceSerial":"
10.0.32.96:5555"}}}
[Chromedriver] Webview version: 'Chrome/44.0.2403.119'
[JSONWP Proxy] Got response with status 200:
{"sessionId":"29d042e1a755ece552a7ea35ba305495","status":33,"value":{"message":"session
not created exception: Chrome version must be >= 60.0.3112.0\n (Driver
info: chromedriver=2.33.506106
(8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2),platform=Mac OS X 10.13.3
x86_64)"}}

[Chromedriver] Error: Failed to start Chromedriver session: A new session
could not be created. (Original error: session not created exception:
Chrome version must be >= 60.0.3112.0 (Driver info:
chromedriver=2.33.506106
(8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2),platform=Mac OS X 10.13.3
x86_64)) at Object.wrappedLogger.errorAndThrow
(/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:69:13)
at Chromedriver.callee$2$0$
(/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-chromedriver/lib/chromedriver.js:217:13)
at tryCatch
(/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
at GeneratorFunctionPrototype.invoke [as _invoke]
(/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw]
(/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js💯21)
at GeneratorFunctionPrototype.invoke
(/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)

**Comment by mykola-mokhnach** [comment]
You must select appropriate chromedriver version: https://github.com/appium/appium/blob/e51db2de68cd6f065a22942307a38d6bda936c52/docs/en/writing-running-appium/web/chromedriver.md

**Comment by yzhangvitalconnect** [comment]
manually download the chromedriver and specify the path at the appium starting time works

**Comment by brianbautista** [comment]
I had the exact same problem and the fix for me was to update my Chrome Webview on my Android device
https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en

**Comment by tuyenlq** [comment]
@brianbautista , I has problem when start chromedriver but it work affter install webview

**Comment by gireinvent** [comment]
I was encountering the same issue on windows and i was behind corporate proxy.
Followed steps below and it worked for me:
- I downloaded version chromedriver ver 2.9 (https://chromedriver.storage.googleapis.com/index.html?path=2.9/) and 
- Placed it in 'C:\Users\UserName\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win'
-  Set DesiredCapabilities for  chromedriverExecutable to above folder
Set capabilities.setCapability("chromedriverExecutable", "C:\Users\UserName\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe"

**Comment by arustamov** [comment]
I was getting the same issue with setting chromedriverExecutableDir but then it worked with chromedriverExecutable as suggested by @gireinvent

**Comment by sudipdey94** [comment]
@gireinvent, thanks for details. it worked for me at last. :)
