### ISSUE TITLE
with Android buildin browser, the appium failed to start with 

### ISSUE THREAD

**Issue by yzhangvitalconnect** [appium/appium#10435]
## The problem
the capability is set to 
{
  "platformName": "android",
  "platformVersion": "6.0.1",
  "deviceName": "10.0.32.96:5555",
  "browserName": "Browser",
  "appPackage": "com.android.browser",
  "appActivity": ".BrowserActivity"
}

## Environment

* Appium version  1.4.0 (1.4.0)
* real device with android 6.0.1
* build in browser. 

## Details

failed to start the appium server with Chrome version must be >= 60.0.3112.0
  (Driver info: chromedriver=2.33.506106 

## Link to Appium logs

[appium-server-logs3.txt](https://github.com/appium/appium/files/1857161/appium-server-logs3.txt)

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by yzhangvitalconnect** [comment]
If the cap allow to use "build in" browser, it that it should support it's version 2.33.506106?

**Comment by imurchie** [comment]
Appium supports Android browsers by using Chromedriver. Chromedriver, in turn, has minimum versions of Chrome (or Chrome-backed browsers) that it supports.

Please see the documentation here: https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md

**Comment by yzhangvitalconnect** [comment]
I installed appium with
npm install appium --chromedriver_version="2.33" --verbose -g

the version is


/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver
--version

ChromeDriver 2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2)


But still failed to start the session of appium.


/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver
[Chromedriver] Killing any old chromedrivers, running: pkill -15 -f
"/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver.*--port=8000"
[Chromedriver] No old chromedrivers seemed to exist
[Chromedriver] Cleaning any old adb forwarded port socket connections
[ADB] List forwarding ports
[ADB] Running '/Users/yzhang/Library/Android/sdk/platform-tools/adb' with
args: ["-P",5037,"-s","10.0.32.96:5555","forward","--list"]
[Chromedriver] Spawning chromedriver with:
/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver
--url-base=wd/hub --port=8000 --adb-port=5037 --verbose
[Chromedriver] Chromedriver version: '2.33.506106'
[JSONWP Proxy] Proxying [GET /status] to [GET
http://127.0.0.1:8000/wd/hub/status] with no body
[JSONWP Proxy] Got response with status 200:
"{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Mac
OS X\",\"version\":\"10.13.3\"}}}"
[JSONWP Proxy] Proxying [POST /session] to [POST
http://127.0.0.1:8000/wd/hub/session] with body:
{"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.browser","androidActivity":"com.android.browser.BrowserActivity","androidDeviceSerial":"
10.0.32.96:5555"}}}
[Chromedriver] Webview version: 'Chrome/44.0.2403.119'
[JSONWP Proxy] Got response with status 200:
{"sessionId":"29d042e1a755ece552a7ea35ba305495","status":33,"value":{"message":"session
not created exception: Chrome version must be >= 60.0.3112.0\n (Driver
info: chromedriver=2.33.506106
(8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2),platform=Mac OS X 10.13.3
x86_64)"}}

[Chromedriver] Error: Failed to start Chromedriver session: A new session
could not be created. (Original error: session not created exception:
Chrome version must be >= 60.0.3112.0 (Driver info:
chromedriver=2.33.506106
(8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2),platform=Mac OS X 10.13.3
x86_64)) at Object.wrappedLogger.errorAndThrow
(/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:69:13)
at Chromedriver.callee$2$0$
(/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-chromedriver/lib/chromedriver.js:217:13)
at tryCatch
(/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
at GeneratorFunctionPrototype.invoke [as _invoke]
(/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw]
(/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
at GeneratorFunctionPrototype.invoke
(/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)



On Wed, Mar 28, 2018 at 11:49 AM, Isaac A. Murchie <notifications@github.com

**Comment by imurchie** [comment]
Did you try 2.32?

**Comment by yzhangvitalconnect** [comment]
I manually download the chromedriver and point to the executable to the
path during the appium server start up time. It works.

But there are any one can help me with this issue.
Modal window is not visible to Appium with android browser application
#10444

I open the same issue couple days ago. But it is closed even though the
problem is not solved. So I open the new issue.
