### ISSUE TITLE
appium not starting

### ISSUE THREAD

**Issue by saicholitha19** [appium/appium#10439]
My Appium server is not starting getting error as follows
[Appium]   platformName: android
[BaseDriver] Session created with session id: 45521692-d5fc-45dd-98a4-b9fe1be901e6
[debug] [AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 9.0.4
[ADB] Checking whether adb is present
[debug] [AndroidDriver] Shutting down Android driver
[debug] [AndroidDriver] Called deleteSession but bootstrap wasn't active
[MJSONWP] Encountered internal error running command: Error: ENOENT: no such file or directory, scandir 'C:\Users\xxx\AppData\Local\Android\build-tools'
[HTTP] <-- POST /wd/hub/session 500 278 ms - 243

**Comment by dpgraham** [comment]
You need to follow this setup guide: http://appium.io/docs/en/drivers/android-uiautomator2/
