### ISSUE TITLE
Methods sendKey and setValue don't working

### ISSUE THREAD

**Issue by dmersiyanov** [appium/appium#10432]
## The problem

Methods sendKey and setValue don't send value to text inputs in iOS native app. It's just skips inputs and continue to run next commands in code and after that test fail because app is still on login screen.

Also can be reproduced on appium desktop 1.4.1.

## Environment

* Appium version (or git revision) that exhibits the issue: Version 1.2.7
* Desktop OS/version used to run Appium: MacOS High Sierra 10.13.3
* Mobile platform/version under test: iOS 11.2
* Real device or emulator/simulator: Simulator iPhone 7
* Appium CLI or Appium.app|exe: 1.7.1

## Code To Reproduce Issue [ Good To Have ]

MobileElement emailTextField = (MobileElement) driver.findElementByXPath("//XCUIElementTypeApplication[@name=\"App\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeTable/XCUIElementTypeCell[2]/XCUIElementTypeTextField");

MobileElement passTextField = (MobileElement)                                                                         driver.findElementByXPath("//XCUIElementTypeApplication[@name=\"App\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeTable/XCUIElementTypeCell[3]/XCUIElementTypeSecureTextField");

emailTextField.sendKeys("dmersiyanov@mail.ru");
passTextField.sendKeys("123");

driver.findElementByXPath("//XCUIElementTypeButton[@name=\"Sign in\"]").click();

**Comment by mykola-mokhnach** [comment]
- Double check if your locator match correct fields.
- Try to tap the field before entering the text.
- Add more debug logging to your application under test to see if keyboard input events are happening - in the destination inputs.
= Try it with appium@beta

**Comment by dmersiyanov** [comment]
- I have tried to use it on different page with following test case:
            driver.findElementByAccessibilityId("ApplicationTabOrders").click();
            driver.findElementByAccessibilityId("Sign in").click();
            driver.findElementByAccessibilityId("SignInEmailTextField").sendKeys("dmersiyanov@mail.ru");
            driver.findElementByAccessibilityId("SignInPasswordTextField").sendKeys("123");
            driver.findElementByAccessibilityId("Log in").click();

but result is same Log in is clicking with empty text fields.

- Taping into the fields didn't help
- I've tried appium v1.8.0-beta4 but still doesn't work

**Comment by mykola-mokhnach** [comment]
> driver.findElementByAccessibilityId("ApplicationTabOrders").click();
> driver.findElementByAccessibilityId("Sign in").click();
> driver.findElementByAccessibilityId("SignInEmailTextField").sendKeys("dmersiyanov@mail.ru");
> driver.findElementByAccessibilityId("SignInPasswordTextField").sendKeys("123");
> driver.findElementByAccessibilityId("Log in").click();

I don't see edit field itself is clicked here:

```
inputField = driver.findElementByAccessibilityId("SignInEmailTextField");
inputField.click();
inputField.clear();
inputField.sendKeys("dmersiyanov@mail.ru");
```

**Comment by dmersiyanov** [comment]
Yes, my bad. I've tried like this as well. Now by some reason keyboard is not showing.

**Comment by mykola-mokhnach** [comment]
If the keyboard is not shown then it is rather a problem with the app or with XCTest framework itself. there is nothing we can do about it.

**Comment by dmersiyanov** [comment]
Keyboard isn't affect on result, i've change simulator settings and textfields doesn't fill by appium

**Comment by mykola-mokhnach** [comment]
Try to report your issue to https://github.com/facebook/WebDriverAgent
Appium is anyway just a proxy and all the job is done by WDA/XCTest itself.
