### ISSUE TITLE
Web navigation issues on Safari - iOS Simulator

### ISSUE THREAD

**Issue by kiranrayofhope** [appium/appium#10443]
## The problem

I'm trying write UI Automation for a web page. After the test is initiated, safari opens up on iOS Simulator and picks the URL which then redirects to authentication portal. Successfully inputs the credentials and clicks submit button. Now here comes the problem, the page doesn't navigate to next page. It reloads the same page (authentication portal) again and checks for the elements which are supposed to be present on the next page after successful sign in.

## Environment

* Appium version : 1.7.2
* Desktop OS/version used to run Appium: macOS Sierra - version 10.12.6
* Node.js version (unless using Appium.app|exe): v9.9.0
* Mobile platform/version under test: iPhone 7 Plus - 11.2
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Both 

## Quick gist of Appium logs

[debug] [iOS] Remote debugger notified us of a new page listing: {"appIdKey":"62252","pageArray":[{"id":1,"title":"","url":"https://na.amazonmoment.com/authenticate?redirect_uri=https%3A%2F%2Fna.amazonmoment.com%2F&clientId=WorkforceManagement-prod-na&preauth=1","isKey":true}]}
[debug] [iOS] Checking if page needs to load
[debug] [iOS] New page listing is same as old, doing nothing

Then it checks for the elements which are supposed to be tested after the page is navigated.

## The same test works perfect on Android platform

https://gist.github.com/kiranrayofhope/481e87a0a10cf1c6cd00c05b67aa6e2a

**Comment by imurchie** [comment]
Does this not happen if you, on the same simulator, navigate to the page, enter the same credentials, and click?

**Comment by kiranrayofhope** [comment]
Nope it doesn't happen. Doing it manually navigates perfectly

**Comment by imurchie** [comment]
What is happening on the server side?

**Comment by kiranrayofhope** [comment]
On server side, it keeps looking for the element locators and since it doesn't find the elements it throws exception:

`   [testng] 29/03/2018-19:49:25.110 [ERROR] TestNGCustomReportListener:saveBrowserInfo[169] - Exception retrieving browser logs
   [testng] org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unsupported log type 'browser' for this device. Supported types : {"syslog":"System Logs - Device logs for iOS applications on real devices and simulators","crashlog":"Crash Logs - Crash reports for iOS applications on real devices and simulators","performance":"Performance Logs - Debug Timelines on real devices and simulators"} (WARNING: The server did not provide any stacktrace information)
   [testng] Command duration or timeout: 48 milliseconds
   [testng] Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
   [testng] System info: host: '186590d6c1c9.ant.amazon.com', ip: '192.168.43.18', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_161'
   [testng] Driver info: org.openqa.selenium.remote.RemoteWebDriver
   [testng] Capabilities [{networkConnectionEnabled=false, xcodeOrgId=, databaseEnabled=false, deviceName=IOSDevice, xcodeSigningId=iPhone Developer, platform=MAC, newCommandTimeout=1800, platformVersion=10.1, webStorageEnabled=false, locationContextEnabled=false, automationName=XCUITest, browserName=Safari, takesScreenshot=true, javascriptEnabled=true, autoWebview=true, platformName=iOS, udid=511B3CFE-FD29-4AA5-A487-F28027157C6C}]
   [testng] Session ID: 9947e8c5-9245-494d-ae44-47dab96d74d1`

**Comment by imurchie** [comment]
I mean on _your_ server side. Is the request to login getting there? Is it logging in?

**Comment by kiranrayofhope** [comment]
No, it isn't logging in. It enters the credentials -> clicks submit and redirects to login page again. It happens only with iOS simulator and real devices. Android works perfectly fine.

**Comment by imurchie** [comment]
Can you try regular clicking instead of using Javascript?

**Comment by kiranrayofhope** [comment]
I have tried both and ended with no luck :(

**Comment by kiranrayofhope** [comment]
@kool79
Thanks for alerting me on this. I've removed them from the logs. Could you please delete or add privacy to your comment to secure this conversation?
