### ISSUE TITLE
DatePicker not working- UiAutomator2

### ISSUE THREAD

**Issue by NarasimhaPrasadi** [appium/appium#10442]
## The problem
The Script which was working well before at Android 6 and 7 using UIAutomator 1.0,is now failing in selecting year from datepicker at UiAutomator 2

((AndroidElement)(driver.findElementByXPath("//android.widget.NumberPicker[@index='2']//android.widget.Button[@index='0']"))).sendKeys("2000");

## Environment
Appium 1.7.2
UIAUTOMATOR2
Galaxy J7 and Edge - Android 7.0

Kindly provide solution.

**Comment by mykola-mokhnach** [comment]
I've spent some time investigating this topic and it looks like the native control does not provide enough information to the Accessibility service to change its value or even receive it: https://github.com/aosp-mirror/platform_frameworks_base/blob/2a661bff8283104648d6e4e82561a6cd4bf37082/core/java/android/widget/NumberPicker.java#L2727 

Please report the problem to Google

**Comment by manojhans** [comment]
@NarasimhaPrasadi here is the solution with uiautomator2:
**Environment:**
Device: Samsung A7/ 7.0 version.
Appium: 1.8
Java-client-5.0.4.jar

MobileElement year=((MobileElement) driver.findElement(By.xpath("//android.widget.NumberPicker[3]//android.widget.EditText")));
year.clear();
year.sendKeys("2000");

--Manoj Hans
