### ISSUE TITLE
Unable to detect some elements on Android Nougat with Appium 1.7.2

### ISSUE THREAD

**Issue by NarasimhaPrasadi** [appium/appium#10440]
The elements which are working fine under Android 6 and below versions,not support for Android 7 Naugat.

## Environment
Appium 1.7.2
UIAutomator 1.0
Jdk 1.8

## Details

Unable to scroll or click on few elements Like (ImageButton) and ID's in Android 7 which is working fine in Android 6.
Returns multiple:true and some times returns null.

What can be the solution?
Kindly let us know.

**Comment by mykola-mokhnach** [comment]
Switch to UIAutomator2 backend

**Comment by NarasimhaPrasadi** [comment]
What are the steps to update UIAutomtor2.

**Comment by mykola-mokhnach** [comment]
http://appium.io/docs/en/drivers/android-uiautomator2/
