### ISSUE TITLE
Modal window is not visible to Appium with android browser application

### ISSUE THREAD

**Issue by yzhangvitalconnect** [appium/appium#10444]
## The problem
This is still a problem, Modal window is not visible to Appium with android browser application

## Environment
{
  "platformName": "android",
  "platformVersion": "6.0",
  "deviceName": "10.0.32.96:5555",
  "browserName": "Browser"
}

using Appium desktop to inspect elements. 
connected with real device, running android 6.0
browser is build in browser. 

## Details
The normal page is visible to appium. The modal window is NOT visible. 

[appium-server-logs-3-29-2018.txt](https://github.com/appium/appium/files/1861279/appium-server-logs-3-29-2018.txt)
![screen shot 2018-03-29 at 10 41 38 am](https://user-images.githubusercontent.com/37850892/38104610-930526b8-333e-11e8-9e4a-f4ef50e5fc42.png)

**Comment by mykola-mokhnach** [comment]
It is not expected to be visible. Inspector is not designed to inspect webviews. Use Remote Chrome debugger for this purpose.

**Comment by yzhangvitalconnect** [comment]
Are there any one have successful story with the similar setup

Android real device + build in browser. Or this is just a suggestion?

**Comment by yzhangvitalconnect** [comment]
This issue is closed too early.

The problem is no matter what it is, the Modal elements are not visible to
Appium server. If you said this is not a bug, please document how to make
it visible to appium server. Inspecting elements are just one way to test
if it is visible to appium server.  Regardless, the Modal elements are not
visible to appium server.

**Comment by yzhangvitalconnect** [comment]
thanks a lot.

**Comment by mykola-mokhnach** [comment]
Closed as inactive
