### ISSUE TITLE
Unable to change the orientation of the iOS app under test on a real device in Appium

### ISSUE THREAD

**Issue by guruprasadsr** [appium/appium#10446]
Unable to change the orientation of the iOS app under test on a real device in Appium

From the documentation mentioned in https://appium.io/docs/en/commands/session/orientation/set-orientation/ , I tried to perform the screen rotation in my Java code. I am getting an error. "org.openqa.selenium.WebDriverException: Unable To Rotate Device"

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Mac OS High Sierra 10.13.1
* Node.js version (unless using Appium.app|exe): v8.5.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Code To Reproduce Issue 

System.out.println(driver.getOrientation().toString()); // Prints PORTRAIT in console
driver.rotate(ScreenOrientation.LANDSCAPE); // Line where I get the error

**Comment by mykola-mokhnach** [comment]
If the device does not allow to change the orientation then it is not be possible to do it with XCTest as well. Also, the change itself happens on [WDA](https://github.com/facebook/WebDriverAgent) side and we don't control it. Closed as not an issue.
