### ISSUE TITLE
Changing Language from iOS settings causes appium to crash and the change doesnt go through

### ISSUE THREAD

**Issue by rabhasin** [appium/appium#10459]
## The problem

Hi I was using Appium on iOS to change the language settings.For this I went to settings app->General->Language & Regions ->iPhone language(tap)-> search "French"-> select it-> click done-> tap "Change to French"(all using automation)

When the last step happened I see the screen go black and say something to the effect of "changing to french" in actual french language.Now 2 seconds later I see the whole thing being shut down (most likely by appium) and the change doesnt go through.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable):1.7.1
* Desktop OS/version used to run Appium:Mac 10.12.6
* Node.js version (unless using Appium.app|exe):9.10.1
* Mobile platform/version under test:iOS
* Real device or emulator/simulator:Real
* Appium CLI or Appium.app|exe: CLI

## Details

I believe someone on android faced a similar issue [here](https://github.com/appium/appium/issues/9944) .I too saw it happen on 1.7.2. but not on 1.7.1.
Also I tried to shut down appium right when it taps on "Change to french" but still it closed down the whole system (so the change couldnt go through)

## Link to Appium logs

[AppiumLogs](https://gist.github.com/rabhasin/adfda6c7102c18bf07779cd938e0339f)

**Comment by dpgraham** [comment]
Hey @mykola-mokhnach there's a setting in WebDriverAgent that lets you set the locale on a real device via a capability, isn't there?

**Comment by rabhasin** [comment]
Here's another log from when i had 1.7.1[https://gist.github.com/rabhasin/0d34e60ddbfe5e2f2812578b212b3fd9](url).

This maybe more helpful since you'll see lot of error messages.Mostly around not being able to connect to the device.

As an experiment I did try the whole thing with ios-webkit-debug-proxy  working in the background but it didnt help.

My guess is when the phone supposedly goes black to restore Appium things it lost connection to the device.If we can perhaps find a way to handle this exception I think it'll help resolve the issue.

**Comment by mykola-mokhnach** [comment]
Yes, restarting the device kills the connection to WebDriverAgent server and thus destroys Appium session. You could try to quit the driver after a new language is selected and then start it again after a while when the device is up again with noReset option set to true.

**Comment by tfcardoso** [comment]
@rabhasin When you change the language, iPhone closes all active connections. What I do is after the tap to change connection, I sleep for a while and then I run driver.launchApp and it works ok for me

**Comment by rabhasin** [comment]
@tfcardoso -Thanks for the suggestion.How exactly are you achieving the sleep here? AFAIK once we've started the server we dont really touch it much.Are you like sending some instruction from the client to the server to sleep?

**Comment by tfcardoso** [comment]
The client script sleeps in order to give time for iPhone to switch language

**Comment by rabhasin** [comment]
Hmm sorry for the delayed response.@tfcardoso - that's not an option for us way our stuff is setup.
However I was able to get our app working in the specified language using the locale/language parameters .Funny enough the docs say it's emulator only but so far seems to have worked.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
