### ISSUE TITLE
How to ensure the same state of App(IOS) when every script start?

### ISSUE THREAD

**Issue by MarvinLiuMing** [appium/appium#10456]
## The problem

I want to reset ios app when script start, just like set "noReset : false" in Android. 
Is there any method to do this?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Desktop OS/version used to run Appium: MAC
* Node.js version (unless using Appium.app|exe): 9.8.0
* Mobile platform/version under test: IOS 11.2
* Real device or emulator/simulator: Real device

**Comment by ochubey** [comment]
Just use following set of capabilities and application would be reinstalled on after each driver.quit():
```
fullReset: true
noReset: false
```

**Comment by mykola-mokhnach** [comment]
Please use Appium forum to ask questions

**Comment by MarvinLiuMing** [comment]
@ochubey 
when I use those capabilities to start app, app will be uninstall and cause server error. Because appium want to startup the uninstall app.

**Comment by ochubey** [comment]
@MarvinLiuMing yes application will be uninstalled and then installed again. If test starts without installation of the app - you need to create an issue on this with logs and sample of code.
I've configuration that always reinstall application to have it's in clear state before test starts and never facing behavoiur as you described above.
