### ISSUE TITLE
[XCUITest] Error: Could not navigate to webview! Err: connect ECONNREFUSED ::1:27753 on IOS Simulator

### ISSUE THREAD

**Issue by SouWilliams** [appium/appium#10455]
## The problem
Running ios simulator safari test with appium, when try to open safari and navigate to the URL, the appium console throw fatal errors.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2
* Desktop OS/version used to run Appium: MAC 10.13.4 (17E199)
* Node.js version (unless using Appium.app|exe): 9.10.1
* Mobile platform/version under test: 11.3
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe:

## Details
1. Setup ios driver capabilities:
    public void setUp() {
        DesiredCapabilities capabilities = DesiredCapabilities.iphone();
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME,"iPhone Simulator");
        capabilities.setCapability(IOSMobileCapabilityType.START_IWDP, true);
        capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME,"XCUITest");
        capabilities.setCapability(MobileCapabilityType.BROWSER_NAME,"Safari");
        capabilities.setCapability(IOSMobileCapabilityType.SAFARI_ALLOW_POPUPS, true);
        capabilities.setCapability(IOSMobileCapabilityType.SAFARI_OPEN_LINKS_IN_BACKGROUND, true);

        iosDriver = new IOSDriver<IOSElement>(capabilities);

        iosDriver.get("https://www.baidu.com");
    }
2. Run with Junit5

## Link to Appium logs
[Encountered internal error running command](https://gist.github.com/SouWilliams/74b4aea2a063b01fb77c5ff4e4fbc179)

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Apple did some major changes there. Please use appium@beta to make weviews in iOS11.3 Simulator working.

**Comment by SouWilliams** [comment]
@mykola-mokhnach Cool, it solved when I use appium@1.8.0-beta4. Thanks

**Comment by SouWilliams** [comment]
Unfortunately,  when I try to click element, the IDE throws fatal errors.
[Console error](https://gist.github.com/SouWilliams/e84ed1a6bfe756d47ee49ac38b07c023)

**Comment by SouWilliams** [comment]
The latest test code is below:

    private IOSDriver iosDriver;
    @Test
    public void setUp() throws InterruptedException {
        DesiredCapabilities capabilities = DesiredCapabilities.iphone();
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME,"iPhone Simulator");
        capabilities.setCapability(IOSMobileCapabilityType.START_IWDP, true);
        capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME,"XCUITest");
        capabilities.setCapability(MobileCapabilityType.BROWSER_NAME,"Safari");
        capabilities.setCapability(IOSMobileCapabilityType.SAFARI_ALLOW_POPUPS, true);
        capabilities.setCapability(IOSMobileCapabilityType.SAFARI_OPEN_LINKS_IN_BACKGROUND, true);

        iosDriver = new IOSDriver<IOSElement>(capabilities);

        iosDriver.get("https://getbootstrap.com/");
        iosDriver.findElement(By.xpath("/html/body/header/div/ul/li[4]/a")).click();
    }

**Comment by mykola-mokhnach** [comment]
IDE has its own built-in server. It looks like you are trying to run it while the other one is already running. Please ask your question on discuss.appium.io

**Comment by reachbharathan** [comment]
@mykola-mokhnach 
I get the below set of logs with the latest appium@1.8.2-beta on trying
[HTTP] --> GET /wd/hub/session/d84efea2-8fb3-47b1-8973-56fbbeaffa9a/contexts {}
[MJSONWP] Calling AppiumDriver.getContexts() with args: ["d84efea2-8fb3-47b1-8973-56fbbeaffa9a"]
[XCUITest] Executing command 'getContexts'
[iOS] Getting list of available contexts
[iOS] Retrieving contexts and views
[iOS] Selecting by url: false 
[RemoteDebugger] useNewSafari --> false
[MJSONWP] Encountered internal error running command: Error: connect ECONNREFUSED ::1:27753
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
[HTTP] <-- GET /wd/hub/session/d84efea2-8fb3-47b1-8973-56fbbeaffa9a/contexts 500 7 ms - 201

**Comment by vutukuriswathi** [comment]
Even I am also facing the same problem.It would be great if some body could help on this

**Comment by fdPoornima** [comment]
plus one

**Comment by imurchie** [comment]
Appium 1.7.2 _will not_ work for iOS 11.3+. Upgrade is the only solution.
