### ISSUE TITLE
Exception in thread "main" org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: An error occurred (WARNING: The server did not provide any stacktrace information)

### ISSUE THREAD

**Issue by karnan008** [appium/appium#10457]
## The problem

Exception in thread "main" org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: An error occurred (WARNING: The server did not provide any stacktrace information) 

Face the above issue in my eclipse - oxygen

## Environment

* Appium version  that exhibits the issue: Appium v1.7.2
* Desktop OS/version used to run Appium: MacOs - Sierra 10.12.6
* Node.js version (unless using Appium.app|exe): 5.6.0
* Mobile platform/version under test: iPhone 6 Simulator 11.0
* Real device or emulator/simulator:Simulator

## Details

Morning the same code i can run it and see the appium works fine and allow me to see the testing works but afternoon it through the error like above mentioned

## Link to Appium logs

https://docs.google.com/document/d/1A-2dTWupBYpk6LRucGpYOBPrKg7A9xKSgjTPV1E9_7s/edit?usp=sharing

## Code To Reproduce Issue [ Good To Have ]

package Maven.Project;
import java.io.IOException;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;
import com.gargoylesoftware.htmlunit.javascript.host.URL;
import io.appium.java_client.AppiumDriver;
import io.appium.java_client.MobileElement;
import io.appium.java_client.TouchAction;
import io.appium.java_client.ios.IOSDriver;
import io.appium.java_client.remote.MobileCapabilityType;
public class App 
{
	public static final WebDriver s = null;
	public static AppiumDriver<?> driver = null;
	public static void main(String [] args)throws InterruptedException, IOException
    {
    	DesiredCapabilities capabilities = new DesiredCapabilities();		
		capabilities.setCapability("platformName", "iOS");
		capabilities.setCapability("platformVersion", "11.0");
		capabilities.setCapability("deviceName", "iPhone Simulator");
		//capabilities.setCapability("deviceName", "iPhone 5C");
		//capabilities.setCapability(MobileCapabilityType.UDID, "56ddac5c8d9a9e8a3e23376024fedc7d0a2febfe");//iPhone5S
		//capabilities.setCapability(MobileCapabilityType.UDID, "8091e3a49dab6c4cdc394b7aa485d7b3c834ac0a");//iPhone5C
		capabilities.setCapability("bundleId", "com.commusoft.commusoftv2");
	driver=new IOSDriver<WebElement>(capabilities);
		Thread.sleep(100);
			System.out.println("Appium Server Launched Successfully");
			
			/*** PROGRAM STARTED ***/
			
			(new TouchAction(driver)).tap(32, 54).perform();
			 (new TouchAction(driver)).tap(89, 223).perform();
			 (new TouchAction(driver)).tap(43, 237).perform();//tap on field
			 
			 MobileElement name = (MobileElement) driver.findElementByXPath("//XCUIElementTypeApplication[@name=\"CommusoftV2\"]/XCUIElementTypeWindow[4]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeKeyboard/XCUIElementTypeOther/XCUIElementTypeOther[2]");
			 name.sendKeys("opal");//name
			 (new TouchAction(driver)).tap(335, 43).perform();//save
			 Thread.sleep(3000);
			 (new TouchAction(driver)).tap(46, 524).perform();//tap on address
			 MobileElement Address = (MobileElement) driver.findElementByXPath("//XCUIElementTypeApplication[@name=\"CommusoftV2\"]/XCUIElementTypeWindow[4]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeKeyboard/XCUIElementTypeOther/XCUIElementTypeOther[2]");
			 Address.clear();//address
			 Address.sendKeys("Chennai");
			 (new TouchAction(driver)).tap(343, 47).perform();//save
			 Thread.sleep(3000);
			 (new TouchAction(driver)).tap(114, 641).perform();//contacts
			 (new TouchAction(driver)).tap(130, 105).perform();//ongoing view
			 Thread.sleep(2000);
			 (new TouchAction(driver)).tap(194, 560).perform();//click the contact list
			 (new TouchAction(driver)).tap(129, 370).perform();//tap on number field
			 MobileElement num = (MobileElement) driver.findElementByXPath("//XCUIElementTypeApplication[@name=\"CommusoftV2\"]/XCUIElementTypeWindow[4]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeKeyboard/XCUIElementTypeOther/XCUIElementTypeOther");
			 num.sendKeys("9686597430");//number
			 (new TouchAction(driver)).tap(333, 44).perform();//save
			 Thread.sleep(3000);
			 (new TouchAction(driver)).tap(195, 641).perform();//tap on notes
			 (new TouchAction(driver)).press(179, 649).moveTo(-4, -574).release().perform();//swipe bottom to top
			 (new TouchAction(driver)).tap(348, 39).perform();//click + button
			 (new TouchAction(driver)).tap(177, 399).perform();//add new notes
			 (new TouchAction(driver)).tap(42, 112).perform();//tap on title field
			 MobileElement title = (MobileElement) driver.findElementByXPath("//XCUIElementTypeApplication[@name=\"CommusoftV2\"]/XCUIElementTypeWindow[4]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeKeyboard/XCUIElementTypeOther/XCUIElementTypeOther[2]");
			 title.sendKeys("Notes title");//Notes title
			 (new TouchAction(driver)).tap(43, 177).perform();//tap on notes field
			 MobileElement mes = (MobileElement) driver.findElementByXPath("//XCUIElementTypeApplication[@name=\"CommusoftV2\"]/XCUIElementTypeWindow[4]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeKeyboard/XCUIElementTypeOther/XCUIElementTypeOther[2]");
			 mes.sendKeys("Notes Message");//Notes message
			 (new TouchAction(driver)).tap(336, 44).perform();//save
			 (new TouchAction(driver)).tap(345, 43).perform();//click + button
			 (new TouchAction(driver)).tap(188, 513).perform();//add new sms
			 (new TouchAction(driver)).tap(358, 120).perform();//To contact field
			 (new TouchAction(driver)).tap(52, 46).perform();//back
			 (new TouchAction(driver)).tap(347, 40).perform();//click + button
			 (new TouchAction(driver)).tap(188, 571).perform();//add phone call
			 (new TouchAction(driver)).tap(355, 109).perform();//call type
			 (new TouchAction(driver)).tap(333, 442).perform();//done
			 (new TouchAction(driver)).tap(359, 175).perform();//To contact name
			 (new TouchAction(driver)).tap(333, 444).perform();//done
			 (new TouchAction(driver)).tap(356, 234).perform();//call with
			 (new TouchAction(driver)).tap(329, 441).perform();//done
			 (new TouchAction(driver)).tap(341, 43).perform();//save
			 (new TouchAction(driver)).tap(249, 648).perform();//appliance tab
			 (new TouchAction(driver)).press(179, 649).moveTo(-4, -574).release().perform();//swipe bottom to top
			 (new TouchAction(driver)).tap(347, 42).perform();//click + button
			 (new TouchAction(driver)).tap(355, 109).perform();//group
			 (new TouchAction(driver)).tap(190, 587).perform();//second dropdown
			 (new TouchAction(driver)).tap(331, 438).perform();//done
			 (new TouchAction(driver)).tap(356, 173).perform();//type
			 (new TouchAction(driver)).tap(329, 440).perform();//done
			 (new TouchAction(driver)).tap(353, 234).perform();//fuel 
			 (new TouchAction(driver)).tap(339, 440).perform();//done
			 (new TouchAction(driver)).tap(359, 301).perform();//make 
			 (new TouchAction(driver)).tap(130, 141).perform();//done
			 (new TouchAction(driver)).tap(358, 363).perform();//model
			 (new TouchAction(driver)).tap(125, 136).perform();//done
			 (new TouchAction(driver)).tap(358, 426).perform();//location
			 (new TouchAction(driver)).tap(335, 440).perform();//done
			 (new TouchAction(driver)).tap(340, 43).perform();//save
			 (new TouchAction(driver)).tap(335, 638).perform();//more
			 (new TouchAction(driver)).tap(181, 269).perform();//attached files
			 (new TouchAction(driver)).tap(347, 40).perform();//click + button
			 (new TouchAction(driver)).tap(188, 512).perform();//choose camera roll
			 (new TouchAction(driver)).tap(125, 105).perform();//click first row
			 (new TouchAction(driver)).tap(44, 118).perform();//select first pic
			 (new TouchAction(driver)).tap(340, 42).perform();//done
			 Thread.sleep(3000);			 
			 (new TouchAction(driver)).tap(55, 42).perform();//back

			 //ESTIMATE
			 
			 (new TouchAction(driver)).tap(306, 269).perform();//ongoing
			 (new TouchAction(driver)).tap(347, 42).perform();//click + button
			 (new TouchAction(driver)).tap(169, 511).perform();//Add Estimate
			 (new TouchAction(driver)).tap(356, 227).perform();//Description
			 (new TouchAction(driver)).tap(332, 444).perform();//Done
			 (new TouchAction(driver)).tap(335, 44).perform();//save
			 Thread.sleep(3000);(new TouchAction(driver)).tap(214, 114).perform();//open estimate first one
			 (new TouchAction(driver)).tap(110, 637).perform();//Estimate tab
			 Thread.sleep(1000);
			 (new TouchAction(driver)).tap(121, 219).perform();//price
			 Thread.sleep(1000);
			 (new TouchAction(driver)).tap(126, 117).perform();//Breakdown
			 Thread.sleep(1000);
			 (new TouchAction(driver)).tap(339, 44).perform();//save
			 Thread.sleep(1000);
			 (new TouchAction(driver)).tap(51, 112).perform();//Tap on total field
			 Thread.sleep(1000);
			 (new TouchAction(driver)).tap(312, 476).perform();//3
			 (new TouchAction(driver)).tap(187, 634).perform();//0
			 //MobileElement tot = (MobileElement) driver.findElementByXPath("//XCUIElementTypeApplication[@name=\"CommusoftV2\"]/XCUIElementTypeWindow[5]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeKeyboard/XCUIElementTypeOther/XCUIElementTypeOther");
			 //tot.sendKeys("50");//Enter amount in total field
			 (new TouchAction(driver)).tap(339, 44).perform();//save
			 (new TouchAction(driver)).tap(102, 292).perform();//invoice schedule
			 Thread.sleep(1000);
			 (new TouchAction(driver)).tap(341, 43).perform();//save
			 Thread.sleep(1000);
			 (new TouchAction(driver)).tap(90, 419).perform();//accept and Reject
			 (new TouchAction(driver)).tap(190, 113).perform();//select
			 (new TouchAction(driver)).tap(274, 614).perform();//accept
			 (new TouchAction(driver)).press(73, 397).moveTo(235, -99).release().perform();//sign	  
			 Thread.sleep(1000);
			 (new TouchAction(driver)).tap(181, 520).perform();//accept
System.out.print("Estimate Accepted from Ongoing work");
			

(new TouchAction(driver)).tap(347, 42).perform();//click + button
(new TouchAction(driver)).tap(169, 511).perform();//Add Estimate
(new TouchAction(driver)).tap(356, 227).perform();//Description
(new TouchAction(driver)).tap(332, 444).perform();//Done
(new TouchAction(driver)).tap(335, 44).perform();//save
Thread.sleep(3000);
(new TouchAction(driver)).tap(214, 114).perform();//open estimate first one
(new TouchAction(driver)).tap(110, 637).perform();//Estimate tab
Thread.sleep(1000);
(new TouchAction(driver)).tap(121, 219).perform();//price
Thread.sleep(1000);
(new TouchAction(driver)).tap(126, 117).perform();//Breakdown
Thread.sleep(1000);
(new TouchAction(driver)).tap(339, 44).perform();//save
Thread.sleep(1000);
(new TouchAction(driver)).tap(51, 112).perform();//Tap on total field
Thread.sleep(1000);
(new TouchAction(driver)).tap(312, 476).perform();//3
(new TouchAction(driver)).tap(187, 634).perform();//0
//MobileElement tot = (MobileElement) driver.findElementByXPath("//XCUIElementTypeApplication[@name=\"CommusoftV2\"]/XCUIElementTypeWindow[5]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeKeyboard/XCUIElementTypeOther/XCUIElementTypeOther");
//tot.sendKeys("50");//Enter amount in total field
(new TouchAction(driver)).tap(339, 44).perform();//save
(new TouchAction(driver)).tap(102, 292).perform();//invoice schedule
Thread.sleep(1000);
(new TouchAction(driver)).tap(341, 43).perform();//save
Thread.sleep(1000);
(new TouchAction(driver)).tap(90, 419).perform();//accept and Reject
(new TouchAction(driver)).tap(190, 113).perform();//select
(new TouchAction(driver)).tap(93, 612).perform();//reject button
(new TouchAction(driver)).tap(356, 227).perform();//reject reason
(new TouchAction(driver)).tap(336, 438).perform();//done
(new TouchAction(driver)).tap(184, 266).perform();//reject button
System.out.print("Estimate Rejected from Ongoing work");

//JOB
System.out.print("Job from Ongoing work");

(new TouchAction(driver)).tap(348, 40).perform();//click + button
(new TouchAction(driver)).tap(185, 571).perform();//add new job
(new TouchAction(driver)).tap(353, 228).perform();//description
(new TouchAction(driver)).tap(332, 440).perform();//done
(new TouchAction(driver)).tap(343, 42).perform();//save
(new TouchAction(driver)).tap(114, 110).perform();//open the first job
(new TouchAction(driver)).tap(179, 91).perform();//complete
driver.findElementByAccessibilityId("Yes").click();
(new TouchAction(driver)).tap(180, 94).perform();//click green bar
Thread.sleep(1000);
(new TouchAction(driver)).tap(176, 456).perform();//FOC
Thread.sleep(1000);
(new TouchAction(driver)).tap(335, 43).perform();//Save
Thread.sleep(1000);
(new TouchAction(driver)).tap(52, 42).perform();//back
System.out.print("Job Completed and Raise FOC from Ongoing work");

(new TouchAction(driver)).tap(347, 42).perform();//+ button
(new TouchAction(driver)).tap(185, 567).perform();//add new job
(new TouchAction(driver)).tap(355, 227).perform();//description
Thread.sleep(1000);
(new TouchAction(driver)).tap(327, 442).perform();//done
Thread.sleep(1000);
(new TouchAction(driver)).tap(339, 44).perform();//save
(new TouchAction(driver)).tap(114, 110).perform();//open the first job
(new TouchAction(driver)).tap(179, 91).perform();//complete
driver.findElementByAccessibilityId("Yes").click();
Thread.sleep(2000);
(new TouchAction(driver)).tap(180, 94).perform();//click green bar
Thread.sleep(1000);
(new TouchAction(driver)).tap(171, 509).perform();//final invoice
(new TouchAction(driver)).tap(59, 222).perform();//copy from job
(new TouchAction(driver)).tap(339, 43).perform();//next
(new TouchAction(driver)).tap(355, 552).perform();//invoice category
(new TouchAction(driver)).tap(331, 445).perform();//done
(new TouchAction(driver)).tap(340, 42).perform();//next 
(new TouchAction(driver)).tap(161, 117).perform();//No breakdown
(new TouchAction(driver)).tap(26, 122).perform();//tap on total
Thread.sleep(1000);
(new TouchAction(driver)).tap(312, 476).perform();//3
(new TouchAction(driver)).tap(187, 634).perform();//0
(new TouchAction(driver)).tap(339, 44).perform();//save
(new TouchAction(driver)).tap(177, 513).perform();//save invoice
(new TouchAction(driver)).tap(190, 626).perform();//cancel
(new TouchAction(driver)).tap(52, 46).perform();//back
System.out.print("Job Completed and Raise Final Invoice from Ongoing work");

//ERROR

(new TouchAction(driver)).tap(347, 42).perform();//+ button	
(new TouchAction(driver)).tap(180, 566).perform();//Add new job
(new TouchAction(driver)).tap(356, 227).perform();//description
(new TouchAction(driver)).tap(324, 440).perform();//done
(new TouchAction(driver)).tap(339, 43).perform();//save

//(new TouchAction(driver)).tap(164, 106).perform();//open first job
//(new TouchAction(driver)).tap(185, 640).perform();//parts tab
//(new TouchAction(driver)).tap(136, 144).perform();//tap 1st parts 

(new TouchAction(driver)).tap(164, 106).perform();//open first job

(new TouchAction(driver)).tap(258, 638).perform();//certificate tab
(new TouchAction(driver)).tap(348, 43).perform();//+ button
(new TouchAction(driver)).tap(151, 129).perform();//select first certificate
(new TouchAction(driver)).tap(343, 47).perform();//next
(new TouchAction(driver)).tap(22, 644).perform();//bottom appliance button
(new TouchAction(driver)).tap(99, 134).perform();//select appl;iance list
(new TouchAction(driver)).tap(335, 43).perform();//save
Thread.sleep(2000);
(new TouchAction(driver)).tap(339, 43).perform();//next
(new TouchAction(driver)).tap(339, 43).perform();//next
(new TouchAction(driver)).tap(339, 43).perform();//next
(new TouchAction(driver)).tap(73, 163).perform();//tap on add comments
MobileElement el1 = (MobileElement) driver.findElementByXPath("//XCUIElementTypeApplication[@name=\"CommusoftV2\"]/XCUIElementTypeWindow[4]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeKeyboard/XCUIElementTypeOther/XCUIElementTypeOther[2]");
el1.sendKeys("Comments by Karna");
(new TouchAction(driver)).tap(336, 46).perform();//next
(new TouchAction(driver)).press(42, 425).moveTo(282, -124).release().perform();//sign
(new TouchAction(driver)).tap(343, 46).perform();//next
(new TouchAction(driver)).press(51, 348).moveTo(266, -43).release().perform();//sign
(new TouchAction(driver)).tap(343, 44).perform();//save
System.out.print("Certificate created");

(new TouchAction(driver)).tap(336, 641).perform();//more tab
(new TouchAction(driver)).tap(70, 395).perform();//additional work
(new TouchAction(driver)).tap(349, 42).perform();//+ button
(new TouchAction(driver)).tap(181, 512).perform();//link to job
Thread.sleep(3000);
(new TouchAction(driver)).tap(228, 102).perform();//click on additional work created
(new TouchAction(driver)).tap(176, 507).perform();//view
(new TouchAction(driver)).tap(272, 641).perform();//estimate tab
 (new TouchAction(driver)).tap(121, 219).perform();//price
			 Thread.sleep(1000);
			 (new TouchAction(driver)).tap(126, 117).perform();//Breakdown
			 Thread.sleep(1000);
			 (new TouchAction(driver)).tap(339, 44).perform();//save
			 Thread.sleep(1000);
			 (new TouchAction(driver)).tap(51, 112).perform();//Tap on total field
			 Thread.sleep(1000);
			 (new TouchAction(driver)).tap(312, 476).perform();//3
			 (new TouchAction(driver)).tap(187, 634).perform();//0
			 //MobileElement tot = (MobileElement) driver.findElementByXPath("//XCUIElementTypeApplication[@name=\"CommusoftV2\"]/XCUIElementTypeWindow[5]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeKeyboard/XCUIElementTypeOther/XCUIElementTypeOther");
			 //tot.sendKeys("50");//Enter amount in total field
			 (new TouchAction(driver)).tap(339, 44).perform();//save
			 (new TouchAction(driver)).tap(102, 292).perform();//invoice schedule
			 Thread.sleep(1000);
			 (new TouchAction(driver)).tap(341, 43).perform();//save
			 Thread.sleep(1000);
			 (new TouchAction(driver)).tap(90, 419).perform();//accept and Reject
			 (new TouchAction(driver)).tap(190, 113).perform();//select
			 (new TouchAction(driver)).tap(274, 614).perform();//accept
			 (new TouchAction(driver)).press(73, 397).moveTo(235, -99).release().perform();//sign	  
			 Thread.sleep(1000);
			 (new TouchAction(driver)).tap(181, 520).perform();//accept
System.out.print("Additional work (Link to job) Accepted from Ongoing work");

(new TouchAction(driver)).tap(347, 40).perform();//+ button
(new TouchAction(driver)).tap(177, 570).perform();//create new job
Thread.sleep(3000);
(new TouchAction(driver)).tap(179, 106).perform();//click on additional work created
(new TouchAction(driver)).tap(187, 500).perform();//
(new TouchAction(driver)).tap(281, 641).perform();//
(new TouchAction(driver)).tap(121, 219).perform();//price
			 Thread.sleep(1000);
			 (new TouchAction(driver)).tap(126, 117).perform();//Breakdown
			 Thread.sleep(1000);
			 (new TouchAction(driver)).tap(339, 44).perform();//save
			 Thread.sleep(1000);
			 (new TouchAction(driver)).tap(51, 112).perform();//Tap on total field
			 Thread.sleep(1000);
			 (new TouchAction(driver)).tap(312, 476).perform();//3
			 (new TouchAction(driver)).tap(187, 634).perform();//0
			 //MobileElement tot = (MobileElement) driver.findElementByXPath("//XCUIElementTypeApplication[@name=\"CommusoftV2\"]/XCUIElementTypeWindow[5]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeKeyboard/XCUIElementTypeOther/XCUIElementTypeOther");
			 //tot.sendKeys("50");//Enter amount in total field
			 (new TouchAction(driver)).tap(339, 44).perform();//save
			 (new TouchAction(driver)).tap(102, 292).perform();//invoice schedule
			 Thread.sleep(1000);
			 (new TouchAction(driver)).tap(341, 43).perform();//save
			 Thread.sleep(1000);
			 (new TouchAction(driver)).tap(90, 419).perform();//accept and Reject
			 (new TouchAction(driver)).tap(190, 113).perform();//select
			 (new TouchAction(driver)).tap(274, 614).perform();//accept
			 (new TouchAction(driver)).press(73, 397).moveTo(235, -99).release().perform();//sign	  
			 Thread.sleep(1000);
			 (new TouchAction(driver)).tap(181, 520).perform();//accept
			 System.out.print("Additional work (Create as a New job) Accepted from Ongoing work");

    }
}

**Comment by gvignesh493** [comment]
Restart the server...

**Comment by mykola-mokhnach** [comment]
It is impossible to read this issue description. Please provide server logs as GIST and decorate the code example properly
