### ISSUE TITLE
Fix flaky appium-uiautomator2-driver testing

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#10452]
* Recently there seems to be intermittent test failures on UIA2 Driver (see: https://travis-ci.org/appium/appium-uiautomator2-driver/jobs/360086435)
* The two tests with troubles seem to be touch tests and keyboard tests

**Comment by lanzelot1989** [comment]
We are facing problems with Appium 1.9.0 on Android (using uiautomator2):
* Keyboard does not open when entering values on inputs (so on-leave events are not triggered)
* Tap method only shows a visual hint but does not really interact with the element (using Click solves this for us)

We are using the .NET binding and Android 8.0 emulators.

**Comment by dpgraham** [comment]
@lanzelot1989 This is unrelated. I would ask on discuss.appium.io or open a new issue at appium/appium/issues (and _make sure_ to fill out the full issue template)

**Comment by mykola-mokhnach** [comment]
Thanks to @imurchie these tests perform better now.
