### ISSUE TITLE
[MJSONWP] Encountered internal error running command: Error: An error occurred

### ISSUE THREAD

**Issue by MonkYU** [appium/appium#10466]
## The problem
I have updated the appium-desktop
appium-desktop:  version 1.5.0 
appium-server   :  version 1.7.2

when I start the server on 0.0.0.0, everything is ok
but when the iphone-device screen is captured by the app-desktop
if I tap or pan the device area in the app-desktop, then I get the error as below:

> [MJSONWP] Encountered internal error running command: Error: An error occurred
[MJSONWP]     at JWProxy.command$ (../../../lib/jsonwp-proxy/proxy.js:176:15)
[MJSONWP]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP]     at
 [HTTP] <-- POST /wd/hub/session/268d4d25-4a3d-43bc-882d-890f9eeb3c98/touch/perform 500 40 ms - 188
[HTTP] 
[XCUITest] Connection to WDA timed out
[iProxy] recv failed: Operation not permitted

#### another point is , if I comman+u to test the webDriverAgentRunner alone, it's show success status on the web page

My new appium-desktop 1.5.0 directory is 

`/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent`

thanks

## Environment

* Appium version 1.5.0 currenttly
* Last Appium version that did not exhibit the issue 1.4.1
* Desktop OS/version used to run Appium: 10.13.3
* Node.js version (unless using Appium.app|exe): v8.9.3
* Mobile platform/version under test: 11.2  iPhone 5s
* Real device or emulator/simulator: real device

**Comment by mykola-mokhnach** [comment]
This means that WebDriverAgent stopped responding to Appium requests. Nothing much we can do here. Perhaps, there are some more details in the device log.

**Comment by MonkYU** [comment]
<img width="759" alt="2018-04-03 6 06 02" src="https://user-images.githubusercontent.com/19282776/38243342-b697ff04-3769-11e8-9654-3718e50ae53d.png">
<img width="739" alt="2018-04-03 6 06 14" src="https://user-images.githubusercontent.com/19282776/38243344-b875196a-3769-11e8-9e4b-c2be6aabe0c1.png">

this is the only error info I can offer.  It's really shouldn't upgrade the appium-desktop to 1.5.0
@mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
This is not the device log. Sorry, but without it I cannot advice much. You could try [mobile endpoints](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios/ios-xctest-mobile-gestures.md) as a workaround.

**Comment by MonkYU** [comment]
@mykola-mokhnach thanks lot, I will try it
