### ISSUE TITLE
simctl error running 'install': An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2)

### ISSUE THREAD

**Issue by ZlenkoValeriy** [appium/appium#10464]
**The problem**
To Friday I was can run app in simulater with appium, yesterday I updated MacOS 10.13.4 (17E199) and Xcode 9.3, after that I get errors.

**Environment**

Appium version (or git revision) that exhibits the issue: Version 1.5.0 (1.5.0)(I loaded last version)
Mobile platform/version under test: IPhone 6
Real device or emulator/simulator: iOS Simulator
Appium CLI or Appium.app:
**Details**
Appium Logs:
[simctl] Error: simctl error running 'install': An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
[simctl] Failed to install the requested application
[simctl] An application bundle was not found at the provided path.
[simctl] Provide a valid path to the desired application bundle.
[simctl]     at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:78:13)
[simctl]     at simCommand$ (../../lib/simctl.js:50:11)
[simctl]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[simctl]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[simctl]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Applications/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[simctl]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[simctl]     at 
[XCUITest] Error: simctl error running 'install': An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
[XCUITest] Failed to install the requested application
[XCUITest] An application bundle was not found at the provided path.
[XCUITest] Provide a valid path to the desired application bundle.
[XCUITest]     at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:78:13)
[XCUITest]     at simCommand$ (../../lib/simctl.js:50:11)
[XCUITest]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[XCUITest]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[XCUITest]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Applications/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[XCUITest]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest]     at 
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: simctl error running 'install': An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
[MJSONWP] Failed to install the requested application
[MJSONWP] An application bundle was not found at the provided path.
[MJSONWP] Provide a valid path to the desired application bundle.
[MJSONWP]     at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:78:13)
[MJSONWP]     at simCommand$ (../../lib/simctl.js:50:11)
[MJSONWP]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Applications/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP]     at 
[HTTP] <-- POST /wd/hub/session 500 39343 ms - 414
[HTTP] 
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":

**Comment by mykola-mokhnach** [comment]
Please fill out the issue reporting form properly.

**Comment by mykola-mokhnach** [comment]
Did you try to install your application under test manually via `xcrun simctl install <apppath>` command?

**Comment by ZlenkoValeriy** [comment]
I get the same error
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.

**Comment by mykola-mokhnach** [comment]
Then you either provide an incorrect application path in capabilities, the application bundle itself is broken or Xcode deployment on the particular machine is broken. In any case this error has nothing to do with Appium itself.

closing as not an issue.

**Comment by ronjonesjr** [comment]
I get the same error and never used to either... [simctl] Error: simctl error running 'install': An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):

**Comment by R0xyLana** [comment]
> **The problem**
> To Friday I was can run app in simulater with appium, yesterday I updated MacOS 10.13.4 (17E199) and Xcode 9.3, after that I get errors.
> 
> **Environment**
> 
> Appium version (or git revision) that exhibits the issue: Version 1.5.0 (1.5.0)(I loaded last version)
> Mobile platform/version under test: IPhone 6
> Real device or emulator/simulator: iOS Simulator
> Appium CLI or Appium.app:
> **Details**
> Appium Logs:
> [simctl] Error: simctl error running 'install': An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
> [simctl] Failed to install the requested application
> [simctl] An application bundle was not found at the provided path.
> [simctl] Provide a valid path to the desired application bundle.
> [simctl] at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:78:13)
> [simctl] at simCommand$ (../../lib/simctl.js:50:11)
> [simctl] at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:67:40)
> [simctl] at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:315:22)
> [simctl] at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Applications/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js💯21)
> [simctl] at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:136:37)
> [simctl] at
> [XCUITest] Error: simctl error running 'install': An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
> [XCUITest] Failed to install the requested application
> [XCUITest] An application bundle was not found at the provided path.
> [XCUITest] Provide a valid path to the desired application bundle.
> [XCUITest] at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:78:13)
> [XCUITest] at simCommand$ (../../lib/simctl.js:50:11)
> [XCUITest] at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:67:40)
> [XCUITest] at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:315:22)
> [XCUITest] at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Applications/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js💯21)
> [XCUITest] at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:136:37)
> [XCUITest] at
> [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
> [iOSLog] Stopping iOS log capture
> [MJSONWP] Encountered internal error running command: Error: simctl error running 'install': An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
> [MJSONWP] Failed to install the requested application
> [MJSONWP] An application bundle was not found at the provided path.
> [MJSONWP] Provide a valid path to the desired application bundle.
> [MJSONWP] at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:78:13)
> [MJSONWP] at simCommand$ (../../lib/simctl.js:50:11)
> [MJSONWP] at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:67:40)
> [MJSONWP] at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:315:22)
> [MJSONWP] at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Applications/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js💯21)
> [MJSONWP] at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/node-simctl/node_modules/babel-runtime/regenerator/runtime.js:136:37)
> [MJSONWP] at
> [HTTP] <-- POST /wd/hub/session 500 39343 ms - 414
> [HTTP]
> [HTTP] --> POST /wd/hub/session
> [HTTP] {"desiredCapabilities":

Good Morning, I had same issue, solution is obvious and easy - we need to clean up memory of simulator. When you open iOS simulator, then `Hardware -> Erase all contents and settings `
Seems like, this issue occurs because of incorrect clean of device memory

**Comment by gaboF** [comment]
Got exactly same issue. 
Configuration iOS 12.1 / iPhone 5s / Appium version: 1.9.1
[simctl] Error: simctl error running 'install': An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
[simctl] Failed to install the requested application
[simctl] An application bundle was not found at the provided path.
[simctl] Provide a valid path to the desired application bundle.
[simctl]     at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[simctl]     at simCommand$ (/usr/local/lib/node_modules/appium/node_modules/node-simctl/lib/simctl.js:50:11)
[simctl]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[simctl]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[simctl]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[simctl]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)

**Comment by nataliabilogrud** [comment]
@gaboF did you find a solution? the same error on iOS 12.1 and Appium version: 1.9.1. Nothing helps.

**Comment by j4ko** [comment]
I am suffering the same issue.
From server log file:

[simctl] Error: simctl error running 'install': An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
[simctl] This app could not be installed at this time.
[simctl] Failed to load Info.plist from bundle at path /Users/PacoCid/Library/Developer/CoreSimulator/Devices/275B6854-1EC5-42F7-AD7D-278D5FF3375B/data/Library/Caches/com.apple.mobile.installd.staging/temp.r2y9Yg/extracted/Payload/trainingym.app
[simctl] Failed to load Info.plist from bundle at path /Users/PacoCid/Library/Developer/CoreSimulator/Devices/275B6854-1EC5-42F7-AD7D-278D5FF3375B/data/Library/Caches/com.apple.mobile.installd.staging/temp.r2y9Yg/extracted/Payload/trainingym.app
[simctl] Underlying error (domain=MIInstallerErrorDomain, code=35):
[simctl] 	Failed to load Info.plist from bundle at path /Users/PacoCid/Library/Developer/CoreSimulator/Devices/275B6854-1EC5-42F7-AD7D-278D5FF3375B/data/Library/Caches/com.apple.mobile.installd.staging/temp.r2y9Yg/extracted/Payload/trainingym.app
[simctl]     at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-support/lib/logging.js:78:13)
[simctl]     at /Applications/Appium.app/Contents/Resources/app/node_modules/node-simctl/lib/simctl.js:49:11
[simctl]     at Generator.throw ()
[simctl]     at asyncGeneratorStep (/Applications/Appium.app/Contents/Resources/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
[simctl]     at _throw (/Applications/Appium.app/Contents/Resources/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:29:9)
[simctl]     at run (/Applications/Appium.app/Contents/Resources/app/node_modules/core-js/modules/es6.promise.js:75:22)
[simctl]     at /Applications/Appium.app/Contents/Resources/app/node_modules/core-js/modules/es6.promise.js:92:30
[simctl]     at flush (/Applications/Appium.app/Contents/Resources/app/node_modules/core-js/modules/_microtask.js:18:9)
[simctl]     at process._tickCallback (internal/process/next_tick.js:61:11)

**Comment by menyp** [comment]
I see this error as well on a simulator (simctl error running 'install': An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):)
Did someone find any robust solution for this pain?

**Comment by only4arunkumar** [comment]
Hi i am finding same error.  not sure what is causing the issue. any help would be appreciated .


Appium Server Logs
[Link to  Logfile](https://drive.google.com/file/d/185cOd0D5EV6qfk7RTDe7EE8UvfSMXyGM/view?usp=sharing)
![image](https://user-images.githubusercontent.com/4882688/58481709-49895c00-81a0-11e9-9d1d-23e117e82439.png)

info] [35m[Appium][39m Welcome to Appium v1.13.0
[info] [35m[Appium][39m Appium REST http interface listener started on 0.0.0.0:4723[info] [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/sessions[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[GENERIC][39m Calling AppiumDriver.getSessions() with args: []
[debug] [35m[GENERIC][39m Responding to client with driver.getSessions() result: []
[info] [35m[HTTP][39m [37m<-- GET /wd/hub/sessions [39m[32m200[39m [90m6 ms - 40[39m
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{"desiredCapabilities":{"app":"/Users/arunkumarravikumar/mobileapps/JobAdderApp/JobAdderApp.iOS/bin/iPhoneSimulator/Release/JobAdderAppiOS.app","automationName":"XCUITest","deviceName":"iPhone Xʀ","platformName":"iOS","platformVersion":"12.2","newCommandTimeout":0,"connectHardwareKeyboard":true}}[39m
[debug] [35m[MJSONWP][39m Calling AppiumDriver.createSession() with args: [{"app":"/Users/arunkumarravikumar/mobileapps/JobAdderApp/JobAdderApp.iOS/bin/iPhoneSimulator/Release/JobAdderAppiOS.app","automationName":"XCUITest","deviceName":"iPhone Xʀ","platformName":"iOS","platformVersion":"12.2","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1559049568720 (23:19:28 GMT+1000 (AEST))
[info] [35m[Appium][39m Appium v1.13.0 creating new XCUITestDriver (v2.113.2) session
[info] [35m[Appium][39m Capabilities:
[info] [35m[Appium][39m   app: /Users/arunkumarravikumar/mobileapps/JobAdderApp/JobAdderApp.iOS/bin/iPhoneSimulator/Release/JobAdderAppiOS.app
[info] [35m[Appium][39m   automationName: XCUITest
[info] [35m[Appium][39m   deviceName: iPhone Xʀ
[info] [35m[Appium][39m   platformName: iOS
[info] [35m[Appium][39m   platformVersion: 12.2
[info] [35m[Appium][39m   newCommandTimeout: 0
[info] [35m[Appium][39m   connectHardwareKeyboard: true
[debug] [35m[BaseDriver][39m Creating session with MJSONWP desired capabilities: {"app":"/Users/arunkumarrav...
[info] [35m[BaseDriver][39m Session created with session id: 7ef806b4-7d2d-4e4a-8288-c7d59f75897f[info] [35m[iOSSim][39m Constructing iOS simulator for Xcode version 10.2.1 with udid '4AD5CFCB-3C51-49DA-BA13-414E5C5F20A3'
[info] [35m[XCUITest][39m Determining device to run tests on: udid: '4AD5CFCB-3C51-49DA-BA13-414E5C5F20A3', real device: false
[info] [35m[XCUITest][39m iOS SDK Version set to '12.2'
[debug] [35m[BaseDriver][39m Event 'xcodeDetailsRetrieved' logged at 1559049569950 (23:19:29 GMT+1000 (AEST))
[info] [35m[BaseDriver][39m Using local app '/Users/arunkumarravikumar/mobileapps/JobAdderApp/JobAdderApp.iOS/bin/iPhoneSimulator/Release/JobAdderAppiOS.app'
[debug] [35m[BaseDriver][39m Event 'appConfigured' logged at 1559049569955 (23:19:29 GMT+1000 (AEST))
[debug] [35m[XCUITest][39m Checking whether app '/Users/arunkumarravikumar/mobileapps/JobAdderApp/JobAdderApp.iOS/bin/iPhoneSimulator/Release/JobAdderAppiOS.app' is actually present on file system
[debug] [35m[XCUITest][39m App is present
[debug] [35m[iOS][39m Getting bundle ID from app '/Users/arunkumarravikumar/mobileapps/JobAdderApp/JobAdderApp.iOS/bin/iPhoneSimulator/Release/JobAdderAppiOS.app': 'com.jobadder.JobAdderApp'
[debug] [35m[BaseDriver][39m Event 'resetStarted' logged at 1559049569966 (23:19:29 GMT+1000 (AEST))[info] [35m[XCUITest][39m Not scrubbing third party app in anticipation of uninstall
[debug] [35m[BaseDriver][39m Event 'resetComplete' logged at 1559049570387 (23:19:30 GMT+1000 (AEST))[debug] [35m[XCUITest][39m Starting log capture for iOS Simulator with udid '4AD5CFCB-3C51-49DA-BA13-414E5C5F20A3', using 'xcrun simctl spawn 4AD5CFCB-3C51-49DA-BA13-414E5C5F20A3 log stream --style compact'[debug] [35m[BaseDriver][39m Event 'logCaptureStarted' logged at 1559049570903 (23:19:30 GMT+1000 (AEST))
[info] [35m[XCUITest][39m Setting up simulator
[debug] [35m[iOS][39m No reason to set locale
[debug] [35m[iOS][39m No iOS / app preferences to set
[debug] [35m[iOSSim][39m Setting preferences of 4AD5CFCB-3C51-49DA-BA13-414E5C5F20A3 Simulator to {"ConnectHardwareKeyboard":true}
[debug] [35m[iOSSim][39m Setting common Simulator preferences to {"RotateWindowWhenSignaledByGuest":true,"ConnectHardwareKeyboard":true}
[debug] [35m[iOSSim][39m Updated 4AD5CFCB-3C51-49DA-BA13-414E5C5F20A3 Simulator preferences at '/Users/arunkumarravikumar/Library/Preferences/com.apple.iphonesimulator.plist' with {"DevicePreferences":{"4AD5CFCB-3C51-49DA-BA13-414E5C5F20A3":{"ConnectHardwareKeyboard":true}},"RotateWindowWhenSignaledByGuest":true,"ConnectHardwareKeyboard":true}[debug] [35m[iOSSim][39m Got Simulator UI client PID: 39739
[info] [35m[iOSSim][39m Both Simulator with UDID 4AD5CFCB-3C51-49DA-BA13-414E5C5F20A3 and the UI client are currently running
[debug] [35m[BaseDriver][39m Event 'simStarted' logged at 1559049571163 (23:19:31 GMT+1000 (AEST))
[debug] [35m[XCUITest][39m Verifying application platform
[debug] [35m[XCUITest][39m CFBundleSupportedPlatforms: ["iPhoneSimulator"][debug] [35m[XCUITest][39m Reset requested. Removing app with id 'com.jobadder.JobAdderApp' from the device[debug] [35m[XCUITest][39m Cleaning installd cache to save the disk space
[debug] [35m[XCUITest][39m Installing '/Users/arunkumarravikumar/mobileapps/JobAdderApp/JobAdderApp.iOS/bin/iPhoneSimulator/Release/JobAdderAppiOS.app' on Simulator with UUID '4AD5CFCB-3C51-49DA-BA13-414E5C5F20A3'...[error] [35m[simctl][39m Error: simctl error running 'install': An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
[error] [35m[simctl][39m This app could not be installed at this time.
[error] [35m[simctl][39m Failed to chmod /Users/arunkumarravikumar/Library/Developer/CoreSimulator/Devices/4AD5CFCB-3C51-49DA-BA13-414E5C5F20A3/data/Bundle/Application/445D4A88-5D61-41F2-AC27-B99AD1BE6B87/JobAdderAppiOS.app/JobAdderAppiOS : No such file or directory
[error] [35m[simctl][39m Failed to chmod /Users/arunkumarravikumar/Library/Developer/CoreSimulator/Devices/4AD5CFCB-3C51-49DA-BA13-414E5C5F20A3/data/Bundle/Application/445D4A88-5D61-41F2-AC27-B99AD1BE6B87/JobAdderAppiOS.app/JobAdderAppiOS : No such file or directory
[error] [35m[simctl][39m Underlying error (domain=MIInstallerErrorDomain, code=4):
[error] [35m[simctl][39m 	Failed to chmod /Users/arunkumarravikumar/Library/Developer/CoreSimulator/Devices/4AD5CFCB-3C51-49DA-BA13-414E5C5F20A3/data/Bundle/Application/445D4A88-5D61-41F2-AC27-B99AD1BE6B87/JobAdderAppiOS.app/JobAdderAppiOS : No such file or directory
[error] [35m[simctl][39m     at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[error] [35m[simctl][39m     at errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-ios-simulator/node_modules/node-simctl/lib/simctl.js:49:11)
[info] [35m[XCUITest][39m Got an error on '/Users/arunkumarravikumar/mobileapps/JobAdderApp/JobAdderApp.iOS/bin/iPhoneSimulator/Release/JobAdderAppiOS.app' install: simctl error running 'install': An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
[info] [35m[XCUITest][39m This app could not be installed at this time.
[info] [35m[XCUITest][39m Failed to chmod /Users/arunkumarravikumar/Library/Developer/CoreSimulator/Devices/4AD5CFCB-3C51-49DA-BA13-414E5C5F20A3/data/Bundle/Application/445D4A88-5D61-41F2-AC27-B99AD1BE6B87/JobAdderAppiOS.app/JobAdderAppiOS : No such file or directory
[info] [35m[XCUITest][39m Failed to chmod /Users/arunkumarravikumar/Library/Developer/CoreSimulator/Devices/4AD5CFCB-3C51-49DA-BA13-414E5C5F20A3/data/Bundle/Application/445D4A88-5D61-41F2-AC27-B99AD1BE6B87/JobAdderAppiOS.app/JobAdderAppiOS : No such file or directory
[info] [35m[XCUITest][39m Underlying error (domain=MIInstallerErrorDomain, code=4):
[info] [35m[XCUITest][39m 	Failed to chmod /Users/arunkumarravikumar/Library/Developer/CoreSimulator/Devices/4AD5CFCB-3C51-49DA-BA13-414E5C5F20A3/data/Bundle/Application/445D4A88-5D61-41F2-AC27-B99AD1BE6B87/JobAdderAppiOS.app/JobAdderAppiOS : No such file or directory
[info] [35m[XCUITest][39m Retrying application install[error] [35m[simctl][39m Error: simctl error running 'install': An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
[error] [35m[simctl][39m This app could not be installed at this time.
[error] [35m[simctl][39m Failed to chmod /Users/arunkumarravikumar/Library/Developer/CoreSimulator/Devices/4AD5CFCB-3C51-49DA-BA13-414E5C5F20A3/data/Bundle/Application/62E1BF93-B0D7-4E31-9A23-3F1C2ED147CD/JobAdderAppiOS.app/JobAdderAppiOS : No such file or directory
[error] [35m[simctl][39m Failed to chmod /Users/arunkumarravikumar/Library/Developer/CoreSimulator/Devices/4AD5CFCB-3C51-49DA-BA13-414E5C5F20A3/data/Bundle/Application/62E1BF93-B0D7-4E31-9A23-3F1C2ED147CD/JobAdderAppiOS.app/JobAdderAppiOS : No such file or directory
[error] [35m[simctl][39m Underlying error (domain=MIInstallerErrorDomain, code=4):
[error] [35m[simctl][39m 	Failed to chmod /Users/arunkumarravikumar/Library/Developer/CoreSimulator/Devices/4AD5CFCB-3C51-49DA-BA13-414E5C5F20A3/data/Bundle/Application/62E1BF93-B0D7-4E31-9A23-3F1C2ED147CD/JobAdderAppiOS.app/JobAdderAppiOS : No such file or directory
[error] [35m[simctl][39m     at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[error] [35m[simctl][39m     at errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-ios-simulator/node_modules/node-simctl/lib/simctl.js:49:11)
[error] [35m[XCUITest][39m Error: simctl error running 'install': An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
[error] [35m[XCUITest][39m This app could not be installed at this time.
[error] [35m[XCUITest][39m Failed to chmod /Users/arunkumarravikumar/Library/Developer/CoreSimulator/Devices/4AD5CFCB-3C51-49DA-BA13-414E5C5F20A3/data/Bundle/Application/62E1BF93-B0D7-4E31-9A23-3F1C2ED147CD/JobAdderAppiOS.app/JobAdderAppiOS : No such file or directory
[error] [35m[XCUITest][39m Failed to chmod /Users/arunkumarravikumar/Library/Developer/CoreSimulator/Devices/4AD5CFCB-3C51-49DA-BA13-414E5C5F20A3/data/Bundle/Application/62E1BF93-B0D7-4E31-9A23-3F1C2ED147CD/JobAdderAppiOS.app/JobAdderAppiOS : No such file or directory
[error] [35m[XCUITest][39m Underlying error (domain=MIInstallerErrorDomain, code=4):
[error] [35m[XCUITest][39m 	Failed to chmod /Users/arunkumarravikumar/Library/Developer/CoreSimulator/Devices/4AD5CFCB-3C51-49DA-BA13-414E5C5F20A3/data/Bundle/Application/62E1BF93-B0D7-4E31-9A23-3F1C2ED147CD/JobAdderAppiOS.app/JobAdderAppiOS : No such file or directory
[error] [35m[XCUITest][39m     at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[error] [35m[XCUITest][39m     at errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-ios-simulator/node_modules/node-simctl/lib/simctl.js:49:11)
[debug] [35m[iOSLog][39m Stopping iOS log capture
[debug] [35m[BaseDriver][39m Event 'newSessionStarted' logged at 1559049575942 (23:19:35 GMT+1000 (AEST))
[debug] [35m[MJSONWP][39m Encountered internal error running command: Error: simctl error running 'install': An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
[debug] [35m[MJSONWP][39m This app could not be installed at this time.
[debug] [35m[MJSONWP][39m Failed to chmod /Users/arunkumarravikumar/Library/Developer/CoreSimulator/Devices/4AD5CFCB-3C51-49DA-BA13-414E5C5F20A3/data/Bundle/Application/62E1BF93-B0D7-4E31-9A23-3F1C2ED147CD/JobAdderAppiOS.app/JobAdderAppiOS : No such file or directory
[debug] [35m[MJSONWP][39m Failed to chmod /Users/arunkumarravikumar/Library/Developer/CoreSimulator/Devices/4AD5CFCB-3C51-49DA-BA13-414E5C5F20A3/data/Bundle/Application/62E1BF93-B0D7-4E31-9A23-3F1C2ED147CD/JobAdderAppiOS.app/JobAdderAppiOS : No such file or directory
[debug] [35m[MJSONWP][39m Underlying error (domain=MIInstallerErrorDomain, code=4):
[debug] [35m[MJSONWP][39m 	Failed to chmod /Users/arunkumarravikumar/Library/Developer/CoreSimulator/Devices/4AD5CFCB-3C51-49DA-BA13-414E5C5F20A3/data/Bundle/Application/62E1BF93-B0D7-4E31-9A23-3F1C2ED147CD/JobAdderAppiOS.app/JobAdderAppiOS : No such file or directory
[debug] [35m[MJSONWP][39m     at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[debug] [35m[MJSONWP][39m     at errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-ios-simulator/node_modules/node-simctl/lib/simctl.js:49:11)
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[31m500[39m [90m7225 ms - 1100[39m
[info] [35m[HTTP][39m [90m[39m
[info] [35m[HTTP][39m [37m-->[39m [37mDELETE[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[HTTP][39m No route found. Setting content type to 'text/plain'
[info] [35m[HTTP][39m [37m<-- DELETE /wd/hub/session [39m[33m404[39m [90m3 ms - 57[39m
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/sessions[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[GENERIC][39m Calling AppiumDriver.getSessions() with args: []
[debug] [35m[GENERIC][39m Responding to client with driver.getSessions() result: []
[info] [35m[HTTP][39m [37m<-- GET /wd/hub/sessions [39m[32m200[39m [90m2 ms - 40[39m
[info] [35m[HTTP][39m [90m[39m

**Comment by nbaryshev** [comment]
Erasing the content of the simulator solved the issue for me
