### ISSUE TITLE
  [Appium] : Hub down or not responding: Error: Invalid protocol: 974618

### ISSUE THREAD

**Issue by stephenws** [appium/appium#10465]
## The problem

Selenium Grid Is up and working properly on system . I am using Selenium 2.57 Standalone server file.
But when i am trying to connect node from system2
It shows Error 

[debug] [Appium] Hub down or not responding: Error: Invalid protocol: 974618:
[Appium] Request to register with grid was unsuccessful: Error: Invalid protocol: 974618:

## Environment

* Appium version (or git revision) that exhibits the issue: Selenium Standalone 2.57 File /Appium 1.6.4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS 10.11.6
* Node.js version (unless using Appium.app|exe): npm 5.5.1
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Json File is here: 

{
	"capabilities": [{
		"deviceName": "LGD855a714a03f",
		"browserName": "TestingTeamG3",
		"version": "5.0",
		"maxInstances": 1,
		"platform": "Android"
	}],
	"configuration": {
		"cleanUpCycle": 2000,
		"timeout": 30000,
		"proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
		"url": "http://127.0.0.1:4722/wd/hub",
		"host": "127.0.0.1",
		"port": 4722,
		"maxSession": 1,
		"register": true,
		"registerCycle": 5000,
		"hubPort": 4430,
		"hubHost": "172.30.13.28"
	}
}
## Link to Appium logs

https://gist.github.com/stephenws/3fa94e2a1e5643ae6957d9de0d7c1cff

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Appium 1.6.4 is out of date. Try with 1.7.2. Also, hub major version should be 3

**Comment by stephenws** [comment]
Thanks @mykola-mokhnach . I will update and will try.

**Comment by stephenws** [comment]
This issue is not getting after updating version so closing this.
