### ISSUE TITLE
Appium alters position within on-screen list when looking for elements

### ISSUE THREAD

**Issue by martinfranck** [appium/appium#10468]
## The problem

I have written a test that requires a user to navigate to a specific page (which contains a vertical list of tappable items) and then tap on a specific item within this list.

After the user has navigated to the correct page, the event that needs to be tapped is on-screen.  When Appium is searching for the element to be tapped, **the position within the list is reset unexpectedly**.

Note: This same incorrect behaviour occurs when I use the inspector, navigate to this list screen and tap the Inspector's 'Refresh' button.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: 1.4.1
* Node.js version (unless using Appium.app|exe): N/A
* Mobile platform/version under test: iOS - 11.2.6
* Real device or emulator/simulator: Real device (iPhone 7)
* Appium CLI or Appium.app|exe: Appium.app

## Details

Have not included code as the Appium Inspector itself can recreate this issue, so suspected it might be simpler to focus on that.

## Link to Appium logs

The issue occurs when [XCUITest] Executing command 'getPageSource'.  There are no errors in the Appium console.

## Code To Reproduce Issue [ Good To Have ]

As mentioned, this issue can be recreated by just refreshing the page on the Inspector asing for 'getPageSource'

**Comment by mykola-mokhnach** [comment]
Appium simply displays what XCTest returns to it. Please report your issue to Apple.
