### ISSUE TITLE
SAFARI_ALLOW_POPUPS capabilities not working on IOS Simulator

### ISSUE THREAD

**Issue by s2005lg** [appium/appium#10463]
## The problem
Open bootstratp website in safari with IOS simulator, when click 'Themes'  button on the top of the page, a popup alert appears and cannot click automatically.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0-beta4
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2
* Desktop OS/version used to run Appium: MAC 10.13.4 (17E199)
* Node.js version (unless using Appium.app|exe):  9.10.1
* Mobile platform/version under test: 11.3
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe:

## Details
1. set up mobile capabilities:
2. Run with Junit5
3. Click [Themes] on the page
4. When alert appears, appium doesn't click [Allow] button.

## Link to Appium logs
[Appium Logs](https://gist.github.com/SouWilliams/8b85367d159109b9e13d7b466a753f1d)

## ScreenShots
![image](https://user-images.githubusercontent.com/6127395/38231550-9ff83d5a-3745-11e8-9753-01e4f4f89465.png)

## Code To Reproduce Issue [ Good To Have ]
private IOSDriver iosDriver;
    @Test
    public void setUp() throws InterruptedException {
        DesiredCapabilities capabilities = DesiredCapabilities.iphone();
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME,"iPhone Simulator");
//        capabilities.setCapability(IOSMobileCapabilityType.START_IWDP, true);
        capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME,"XCUITest");
        capabilities.setCapability(MobileCapabilityType.BROWSER_NAME,"Safari");
        capabilities.setCapability(IOSMobileCapabilityType.SAFARI_ALLOW_POPUPS, true);
        capabilities.setCapability(IOSMobileCapabilityType.SAFARI_OPEN_LINKS_IN_BACKGROUND, true);

        iosDriver = new IOSDriver<IOSElement>(capabilities);

        iosDriver.get("https://getbootstrap.com/");
        iosDriver.findElement(By.xpath("/html/body/header/div/ul/li[2]/a")).click();
       // Click [Themes] on the page
        iosDriver.findElement(By.xpath("/html/body/header/div/ul/li[4]/a")).click();
        iosDriver.close();
    }

**Comment by SouWilliams** [comment]
[Appium log](https://gist.github.com/SouWilliams/a07d487193a1d1815193645efe7c60cd)

**Comment by SouWilliams** [comment]
I have attached a new appium log with xcode log. Anyone who can help on this ?

**Comment by SouWilliams** [comment]
Hi @mykola-mokhnach , Do you have any idea on this case ?

**Comment by SouWilliams** [comment]
Hi @imurchie Can you help on this case ? Thanks

**Comment by dpgraham** [comment]
@imurchie do you know if this is still an issue?

**Comment by mykola-mokhnach** [comment]
Should be fixed now
