### ISSUE TITLE
Android EditText element cannot be found

### ISSUE THREAD

**Issue by majkl91** [appium/appium#10471]
## The problem

I have problem with locating this EditText at google.com. It hasnt id.

i tried many xpaths.

screen of the element hierarchy in attachments

still fails on:

> Exception in thread "Thread-2" org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"class name","selector":"android.widget.EditText"}
>   (Session info: chrome=65.0.3325.109)
>   (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Windows NT 10.0.16299 x86_64) (WARNING: The server did not provide any stacktrace information)
> Command duration or timeout: 0 milliseconds
> For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
> Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:33:15.31Z'
> System info: host: 'DESKTOP-FAVBH01', ip: '192.168.1.14', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_161'
> Driver info: io.appium.java_client.android.AndroidDriver
> Capabilities {browserName: Chrome, databaseEnabled: false, desired: {browserName: Chrome, device: Android, deviceName: F8AZFG01D203, platformName: android, platformVersion: 5.0}, device: Android, deviceManufacturer: asus, deviceModel: ASUS_Z00AD, deviceName: F8AZFG01D203, deviceScreenSize: 1080x1920, deviceUDID: F8AZFG01D203, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, platform: LINUX, platformName: LINUX, platformVersion: 5.0, takesScreenshot: true, warnings: {}, webStorageEnabled: false}
> Session ID: 73566276-eefd-4657-b20b-b99ac874f984
> *** Element info: {Using=class name, value=android.widget.EditText}
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

then trying this:
List tf=driver.findElements(By.className("android.widget.EditText"));
tf.get(0).sendKeys("something");

when i call tf.size(); result is 0

> Exception in thread "Thread-2" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
> 	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
> 	at java.util.ArrayList.get(ArrayList.java:433)
> 	at testcases.GoogleSearch.startTest(GoogleSearch.java:44)
> 	at javaapplication2.Testing.run(Testing.java:54)

![38145699-f4575f28-344a-11e8-8a9e-471e2c9c7bd1](https://user-images.githubusercontent.com/23366363/38302843-67edc1a4-3804-11e8-9bfd-73102c00285a.png)

## Environment

* Appium v1.7.2
* Last Appium version that did not exhibit the issue (if applicable): dont know im new
* Desktop OS/version used to run Appium: Win 10, 64b
* Node.js version (unless using Appium.app|exe): v8.10.0
* Mobile platform/version under test: Android 5.0
* Real device or emulator/simulator: Asus Zenphone 2
* Appium CLI or Appium.app|exe: 1.4.1

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

this logs are from both variants. 

[appium-server-logs.txt](https://github.com/appium/appium/files/1875322/appium-server-logs.txt)

## Code To Reproduce Issue [ Good To Have ]

driver.findElement(By.className("android.widget.EditText")).sendKeys("something");

List tf=driver.findElements(By.className("android.widget.EditText"));
tf.get(0).sendKeys("something");

**Comment by mykola-mokhnach** [comment]
Native class names won't work inside a webview. Appium inspector can only be used in native context. Use Google remote debugger in order to test and construct locators there.

Closed as not an issue
