### ISSUE TITLE
[iOS-multiSelectedPicklist] XCUIElementTypePicker\XCUIElementTypePickerWheel does not expose the selected values

### ISSUE THREAD

**Issue by meizhang18** [appium/appium#10476]
## The problem
XCUIElementTypePicker\XCUIElementTypePickerWheel  is used for a multiple selected picklist on iOS. 

Now we need get all the selected values. However, XCUIElementTypePicker\XCUIElementTypePickerWheel value only shows the current value in the front, but did not expose whether it is selected or not.

Do we have any support to know whether a value is selected in XCUIElementTypePickerWheel when it is used for a multi selection purpose?

## Environment

* Appium version (or git revision) that exhibits the issue: v1.7.2
* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium: 10.13.4
* Node.js version (unless using Appium.app|exe): v9.4.0
* Mobile platform/version under test: iPhone 11.3 
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: 

## Details

XCUIElementTypePicker\XCUIElementTypePickerWheel value only shows the current value in the front, but did not expose whether it is selected or not.

## Link to Appium logs

https://gist.github.com/meizhang18/e71a3cca16c559aa809195d3fd962c2d

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
We can only show what XCTest returns to us. I don't know any properties there, that might be suitable for the described purpose. Let us know if you know any.

Closed as not an issue
