### ISSUE TITLE
Appium 1.7.2 not able to find locators on IOS 11.2.6

### ISSUE THREAD

**Issue by vidyasagarpesala** [appium/appium#10472]
## The problem
We are trying to click on our application home screen locators using IOS 11.2.6. Appium throws an error saying locator not found. When we execute the same test case using IOS 10+ devices appium able to click on locators, this issue comes up when we use IOS 11+ devices.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2 and later beta versions in 1.8 as well
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS High Sierra(10.13.1)
* Node.js version (unless using Appium.app|exe):9.10.1
* Mobile platform/version under test: IOS 
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe:

## Details
Attached page source of application on IOS 10.3.2 and also attached page source of application on IOS 11.2.6. Also attached screenshot of appium inspector xml where compose button on top is not displaying. we are facing this issue only IOS 11+ devices. would please tell us why is this happening only on IOS 11+ devices.

[IOS10 page source.txt](https://github.com/appium/appium/files/1875329/IOS10.page.source.txt)
[IOS11 page source..txt](https://github.com/appium/appium/files/1875330/IOS11.page.source.txt)
![ios 11 2 6- missing locator](https://user-images.githubusercontent.com/17523182/38302899-f3aef79a-3821-11e8-8a17-f1e9e2179cff.png)

**Comment by mykola-mokhnach** [comment]
This happens because of the changes that Apple did to XCTest since Xcode9. Nothing we can do about it. Please report the issue to Apple.

**Comment by VenkateshPS** [comment]
@mykola-mokhnach 
Is it possible for you to give some details on the changes which is causing this behaviour.
