### ISSUE TITLE
Appium beta 1.8 and iOS: text_field.clear or send_keys : connect ECONNREFUSED 127.0.0.1:8100

### ISSUE THREAD

**Issue by ericzered** [appium/appium#10475]
## The problem

Since I've updated Appium to the 1.8.0-beta4 I can't use .clear and .send_keys for text field in my iOS Simulator
I'm in Ruby.
It's ok with Xcode 9.3 and Appium 1.7.2 but I have _connect_ ECONNREFUSED 127.0.0.1:8100_ with beta Appium.
I've tried to click first on the text field to make the keyboard appear but same error when I want to clear or send keys.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0 beta4
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2
* Desktop OS/version used to run Appium: OSX
* Node.js version (unless using Appium.app|exe): v6.11.4
* Mobile platform/version under test: Xcode 9.3 iOS 11.0.1
* Real device or emulator/simulator: Simulator

## Link to Appium logs

here the appium log when I click on text field (OK) and then try to input text with send_keys : 
https://gist.github.com/ericzered/d8146494b0d73ba9eacf211278eeaf7f

Thanks a lot

**Comment by mykola-mokhnach** [comment]
Can you provide the device log?

**Comment by mykola-mokhnach** [comment]
it's segmentation fault. Nice. Hell knows what was changed in that bloody XCTest again

**Comment by mykola-mokhnach** [comment]
I was not able to reproduce the problem with any of local tests. Try to gather more logs/tracebacks/steps to reproduce, otherwise it won't be possible to do anything there.

**Comment by mykola-mokhnach** [comment]
You could try to update Simulator version to 11.3 and see if it helps

**Comment by mykola-mokhnach** [comment]
I'm afraid the only solution would be to use older Xcode version with older iOS builds for now.

**Comment by ericzered** [comment]
Yeah, that's the solution, thanks !
Continue the good job :)

**Comment by mykola-mokhnach** [comment]
We've added some workarounds to the web driver. You could reinstall appium@beta and try again
