### ISSUE TITLE
WebDriverAgent test failed

### ISSUE THREAD

**Issue by SouWilliams** [appium/appium#10470]
## The problem
Trying to test safari on Iphone7 plus, after complete WebDriverAgent configuration and run test with command "xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=bb080d8ed2e9a4c9bb3fc85c95138441090f1e78' test ". Got WebDriverAgent error

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0-beta4
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2
* Desktop OS/version used to run Appium: MAC 10.13.4 (17E199)
* Node.js version (unless using Appium.app|exe): 9.10.1
* Mobile platform/version under test: 11.3
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Details
Trying to test safari on Iphone7 plus, after complete WebDriverAgent configuration and run test with command "xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=bb080d8ed2e9a4c9bb3fc85c95138441090f1e78' test ". Got WebDriverAgent error

## Link to Appium logs
[WebDriverAgent test error log](https://gist.github.com/SouWilliams/ae616b8e27f1b3bfaa05885c3761ee1b)

## Code To Reproduce Issue [ Good To Have ]
private IOSDriver iosDriver;
    @Test
    public void setUp() throws InterruptedException, MalformedURLException {
        DesiredCapabilities capabilities = DesiredCapabilities.iphone();
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME,"iPhone 7 Plus");
        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME,"iOS");
        capabilities.setCapability(IOSMobileCapabilityType.XCODE_ORG_ID,"5Y9W5CLT4S");
        capabilities.setCapability(IOSMobileCapabilityType.XCODE_SIGNING_ID, "iPhone Developer");
        capabilities.setCapability(IOSMobileCapabilityType.START_IWDP, true);
        capabilities.setCapability(IOSMobileCapabilityType.AUTO_ACCEPT_ALERTS, true);
        capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME,"XCUITest");
        capabilities.setCapability(MobileCapabilityType.BROWSER_NAME,"Safari");
        capabilities.setCapability(IOSMobileCapabilityType.SAFARI_ALLOW_POPUPS, true);
        capabilities.setCapability(IOSMobileCapabilityType.SAFARI_OPEN_LINKS_IN_BACKGROUND, true);
        capabilities.setCapability(MobileCapabilityType.UDID, "bb080d8ed2e9a4c9bb3fc85c95138441090f1e78");

        iosDriver = (IOSDriver) new RemoteWebDriver(new URL("http://127.0.0.1:4723/wd/hub"),capabilities);

        iosDriver.get("https://getbootstrap.com/");
        iosDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
        iosDriver.findElement(By.xpath("/html/body/header/div/ul/li[4]/a")).click();
        iosDriver.switchTo().alert().accept();
        iosDriver.close();
    }

**Comment by mykola-mokhnach** [comment]
> 	/private/var/containers/Bundle/Application/288C6EFC-5076-467C-827F-8A529A513926/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer: required code signature missing for '/private/var/containers/Bundle/Application/288C6EFC-5076-467C-827F-8A529A513926/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer'

As you can see there is a problem with code signing

**Comment by Biloleg** [comment]
I have the same issue.
I sign WDA lib and WDA runner (as always) and change bundleId for WDA runner.
When I try to install and test WDA from xCode i get:
"Test target WebDriverAgentRunner encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)"
NOTE: WDA on device is trusted.
Please see full xCode log:
[Session-WebDriverAgentRunner-2018-04-05_105818-ajVXAo.log](https://github.com/appium/appium/files/1879036/Session-WebDriverAgentRunner-2018-04-05_105818-ajVXAo.log)

**Comment by mykola-mokhnach** [comment]
Closed as duplicate

**Comment by haseebzagir** [comment]
My solution was to navigate to the WebDriveragent.xcodeproj which is in the path your_username/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent and update the project to the recommended settings.
