### ISSUE TITLE
TouchID Enrollment Broken in 11.2

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#10477]
The OSAScript command that enables TouchId enrollment isn't working anymore

```
tell application "System Events"
  tell process "Simulator"
    set dstMenuItem to menu item "Enrolled" of menu 1 of menu item "Touch ID" of menu 1 of menu bar item "Hardware" of menu bar 1
    set isChecked to (value of attribute "AXMenuItemMarkChar" of dstMenuItem) is "✓"
    if isChecked then
      click dstMenuItem
    end if
  end tell
end tell
```

(see: https://github.com/appium/appium-ios-simulator/blob/abad79fb3ec98e860a028198d7c6d7a5d40510ca/lib/simulator-xcode-6.js#L917)

Also, the tests are inadequate because it accepts tests that show that Touch ID is not supported. This was done because old versions of IOS didn't have TouchID.

Acceptance Criteria:
* [ ] Fix the problem osascript
* [ ] Update the tests so that it doesn't accept unsupported touchId errors for IOS versions > 11

**Comment by mykola-mokhnach** [comment]
Do you have a log?

**Comment by dpgraham** [comment]
May be a false alarm. I think the issue might just be that I'm using Simulators that don't support it.

**Comment by imurchie** [comment]
Is it possible that 11.4 sims just have it turned on all the time? This is what happened with Web Inspector in 11.3

**Comment by mykola-mokhnach** [comment]
Nah, it's disabled by default. I've just checked in with iOS 12 Simulator (Xcode10 beta)
