### ISSUE TITLE
Appium 1.6.4 - In the inspector the native app elements orientation is wrong when i try to automate the iOS control centre and soft keyboard

### ISSUE THREAD

**Issue by githubdilip** [appium/appium#10473]
## The problem

I am using appium 1.6.4 with iOS native app in real device. I try to automate the iOS control centre and soft keyboard. In my inspector the view is loaded in portrait instead of landscape (I set orientation to Landscape in capability too). Can you please help in getting correct orientation. I am able to view the element in inspector but the orientation is wrong, because of which the interaction is not happening in correct location

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.4
* Last Appium version that did not exhibit the issue (if applicable):NA
* Desktop OS/version used to run Appium:10.3
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 10.2.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:Appium.app

**Comment by mykola-mokhnach** [comment]
It is known XCTest issue. You could try appium@beta, where we added some workarounds, but there is nothing much from our side  that can be done there.

**Comment by githubdilip** [comment]
@mykola-mokhnach Can you please give which version we can give a try ?

**Comment by mykola-mokhnach** [comment]
> You could try appium@beta

**Comment by githubdilip** [comment]
I am using appium-desktop-1.0.2-beta.2-mac.zip only. Can you please give exact beta version or link to get it ?

**Comment by mykola-mokhnach** [comment]
`npm i -g appium@beta`

Then you could connect to the server from Appium Desktop UI

**Comment by githubdilip** [comment]
Tried with appium@beta, still the same issue. Can you please tell is there any way to get the correct orientation

**Comment by mykola-mokhnach** [comment]
No, if we knew, we'd already have it implemented.
