### ISSUE TITLE
Appium server and VPN

### ISSUE THREAD

**Issue by sancy2017** [appium/appium#10479]
Iam connected on VPN of the workplace and when i run appium server and execute the code(basically registration), the accounts created during registration under VPN is registered under personal IP in the database. 
Expected: should be registered under the workplace ip.

.Running java in eclipse ide
.latest appium version
.windows 10
.Android simulator 
.Real device or emulator/

**Comment by mykola-mokhnach** [comment]
1. How this is related to Appium?
2. Are there any logs/examples/screenshot? It is totally unclear what the problem is from this description.
