### ISSUE TITLE
Xcode 9.3 : execute_script('mobile: scroll') : socket hang up

### ISSUE THREAD

**Issue by ericzered** [appium/appium#10474]
## The problem
I'm in Ruby,
Since I've got Xcovde 9.3, I've got issue with _execute_script('mobile: scroll', direction: "down")_ in my app on my simulator iOS 11.0.
I've got this error when I try it : 
_Selenium::WebDriver::Error::UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up_

I've got Appium 1.7.2, but I repro it on 1.8.3 beta too
I'm pretty sure it was ok before I update Xcode
## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OSX
* Node.js version (unless using Appium.app|exe): v6.11.4
* Mobile platform/version under test: iOS 11.0.1 on Xcode 9.3
* Real device or emulator/simulator: Simulator

## Link to Appium logs

https://gist.github.com/ericzered/324f626ee6bfb2012674908e367602a6

**Comment by mykola-mokhnach** [comment]
It is for sure something inside XCTest, that we cannot change anyway. Please report the problem to Apple along with the device log.

**Comment by ericzered** [comment]
Ah ok, too bad. I just test again and it's ok with Xcode 9.0, so yes, Apple fault...
