### ISSUE TITLE
Appium 1.6.4 - Finding element is extreme slowness in one particular page of iOS Native app

### ISSUE THREAD

**Issue by githubdilip** [appium/appium#10486]
## The problem

Using Appium 1.6.4 to automation iOS native app in iOS 10.2.1 version. Could see the script execution is extremely slow in one particular page of the native app, If we do manually we don't see any slowness in performance too, but with appium the find elements take very long time say 10 times slower than other pages. Can you please help in this

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable):NA
* Desktop OS/version used to run Appium:1.6.4
* Node.js version (unless using Appium.app|exe):Appium.app
* Mobile platform/version under test:iOS 10.2.1
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe:Appium.app

**Comment by mykola-mokhnach** [comment]
Element lookup speed is controlled by Apple's XCTest. Only xpath locators are implemented on WDA side and thus are slow. Read https://github.com/facebook/WebDriverAgent/wiki/How-To-Achieve-The-Best-Lookup-Performance for more details.
