### ISSUE TITLE
Impossible to run WebDriverAgent on device

### ISSUE THREAD

**Issue by Biloleg** [appium/appium#10485]
## The problem
I sign WDA lib and WDA runner (as always) and change bundleId for WDA runner.
When I try to install and test WDA from xCode i get:
"Test target WebDriverAgentRunner encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)"
NOTE: WDA on device is trusted.
When try to run test from Appium i get next error:
Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65"
NOTE: WebDriver sign correct (as always)
Please see full xCode log in attached:

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.0
* Last Appium version that did not exhibit the issue (if applicable):1.4.x
* Desktop OS/version used to run Appium: macOS 10.13.3
* Node.js version (unless using Appium.app|exe): Appium.app
* Mobile platform/version under test: iOS 11.2.6
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: Appium.app

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Please attach both server and device logs

**Comment by Biloleg** [comment]
Device crash log and Appium log
[deviceCrashLog.log](https://github.com/appium/appium/files/1879208/deviceCrashLog.log)
[AppiumLog.log](https://github.com/appium/appium/files/1879227/AppiumLog.log)

**Comment by mykola-mokhnach** [comment]
Enable `showIOSLog` and `showXcodeLog` capabilities and reattach the Appium server log

**Comment by Biloleg** [comment]
[AppiumFullLog.log](https://github.com/appium/appium/files/1879325/AppiumFullLog.log)

**Comment by Biloleg** [comment]
Fix by download WDA from facebook/WebDriverAgent git and replace it in appium
