### ISSUE TITLE
Parameters were incorrect for installApp(String, BaseInstallApplicationOptions)

### ISSUE THREAD

**Issue by therussiankid92** [appium/appium#10487]
## The problem

I'm trying to automate an upgrade/update scenario for my Android Application, using the newly enhanced 
installApp(String, BaseInstallApplicationOptions). When I get to that point of the execution, the application stops, selenium complaining about bad parameters for the installApp request. 

I've tried updating to the latest selenium-java version 3.11.0, but the issue its still present. 

## Environment

* Appium version (or git revision) that exhibits the issue: 6.0.0-BETA4
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: MAC OS 10.13.2
* Node.js version (unless using Appium.app|exe): N/A
* Mobile platform/version under test: Android 6.0
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: 1.5.0

## Link to Appium logs

https://gist.github.com/therussiankid92/41c0396a7f252001a099fddc3797b4f9

## Code To Reproduce Issue [ Good To Have ]
```
private AndroidInstallApplicationOptions androidInstallApplicationOptions = new AndroidInstallApplicationOptions();
private String appUpdateLocation = "/Users/user/Desktop/update.apk";

public void anUpdateIsRequested() {
		androidInstallApplicationOptions.withReplaceEnabled();
		driver.closeApp();
		driver.installApp(appUpdateLocation, androidInstallApplicationOptions);
		
	}
```

**Comment by mfernandez79** [comment]
Same problem here!

**Comment by mykola-mokhnach** [comment]
This only works with appium@beta. Closed as not an issue
