### ISSUE TITLE
[ADB] Error: Error occured while starting App. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\USMobile\\AndroidSDK\\platform-tools\\adb.exe -P 5037 -s 98899a444d35504b35 shell am start -W -n com.sec.android.app.launcher/com.sec.android.app.launcher.activities.LauncherActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' timed out after 20000ms'; Stderr: ''; Code: 'null'

### ISSUE THREAD

**Issue by gwkeene** [appium/appium#10489]
## The problem

**Situation:** Test machine has Java test scripts that when executed, send commands to remote Windows machine that has Android mobile device attached.  Phone screen changes but does not unlock as it should. 

## Environment

Appium v1.7.2
Windows 10 (on both pcs)
Samsung Galaxy 8
Real Device 
Android version 8.0
ADB version 1.0.39 
Appium Java Client v5.0.4 

## Details

**KNOWN:** Our testing has ran successfully up to this point while we have Samsung Galaxy 7 with Android OS version 7.0. Problem only occurs when we attached the new Samsung Galaxy 8 with Android OS version 8.0. The only difference in these two phones that stands out is the much longer device name for the Galaxy 8

https://gist.github.com/gwkeene/ae70f448f8666b4c076a2f7d62780736

The failure point in the code is upon creating the AndroidDriver:
 **new AndroidDriver(url, capabilities);** 

Again everything works fine with the Galaxy 7 Android OS 7.0

Thanks

**Comment by gwkeene** [comment]
Thanks Mykola, We built our automation to handle the unlock of the device. This is because there is a "device manager" that must remain on the device that prevents the device lock from being disabled. The screen lock can be set to a maximum of 5 min.  This is not  an environment where we work with a development team.  We are testing an "end user" experience.

**Comment by mykola-mokhnach** [comment]
Then let us know if you have a solution.

**Comment by gwkeene** [comment]
My solution to this was to install an app on the device that will keep the screen awake so it will never lock. 
However, the fact that SkipUnlock works fine for Android 7 but not for Android 8 makes it seem as if Appium needs to add support for it in Android 8.  For Android 7 we used SkipUnlock that allowed the AndroidDriver to create and then we would unlock the phone.  That will not work for Android 8 since driver creation fails.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by SuryakiranP** [comment]
Encountered internal error running command: Error: Error getting device platform version. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\suryakiranp\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 02157df29af5152e shell getprop ro.build.version.release' exited with code 3221226356'; Stderr: ''; Code: '3221226356'

**Comment by SuryakiranP** [comment]
@mykola-mokhnach I have resolved it  by downgrading the ADB version and uninstalled SDK from the android studio and Restarted Appium by run as administrator

**Comment by RamyaSeelan** [comment]
how do you downgrade adb version ?

**Comment by SuryakiranP** [comment]
Download Platform tool version and replace it with existing . Un install
your Android SDK and re install it .
