### ISSUE TITLE
Socket hang up exception 

### ISSUE THREAD

**Issue by Hrishikesh-Jayathirtha** [appium/appium#10491]
## The problem

Socket hang up exception while running a test on an Android device

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up (WARNING: The server did not provide any stacktrace information)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 7
* Node.js version (unless using Appium.app|exe):  6.3.0
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Real device, Samsung Galaxy Tab S2
* Appium CLI or Appium.app|exe: CLI

## Details
While running an automated test on the client side, an exception was thrown as mentioned in "the problem".  This happened in the middle of a test when the test was trying to find an alert dialog used in the application. However, with the same configuration, the test re-ran successfully without any issue and this issue was not seen. However, I wanted to know/understand the root cause of this issue which was a rare occurence.

## Link to Appium logs
https://gist.github.com/Hrishikesh-Jayathirtha/00f626332ecba5e981d9ac61503da4bb

**Comment by mykola-mokhnach** [comment]
This error usually happens if UIA2 server stops responding to Appium. This can happen because of multiple reasons, like the device under tests does not respond, network issues, resource leaks, internal errors in UIA2 framework, etc. Perhaps you could be able to find traces of what happened in logcat output.
