### ISSUE TITLE
Appium 1.6.4 - For iOS native app, in the inspector the dynamic elements which are generated through code are not captured

### ISSUE THREAD

**Issue by githubdilip** [appium/appium#10493]
## The problem

I am automating iOS native app which involves some text field we need to enter and get some suggestion as table/drop down. In the appium inspector the corresponding elements for the suggestion/ table is not captured. Unable to do any interaction on the values. The table is generated by code and not by design. Can you please help to get any work around to get the elements in the suggestion

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium:10.13
* Node.js version (unless using Appium.app|exe):Appium.app
* Mobile platform/version under test:10.2.1
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe:Appium.app

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/issues/6517

**Comment by githubdilip** [comment]
@mykola-mokhnach  Thank you for the help and exact material.. Seems its in developer hand to access the application elements.
