### ISSUE TITLE
Unhandled rejection StatusCodeError: 404 - [object Object] 

### ISSUE THREAD

**Issue by Saifalip** [appium/appium#10492]
The problem

My issue is, now it working on to run testdroid file in bitbar cloud for IOS application. 
I have generated IPA file from Xcode 9.2 and i given the ipa file path in script also. But when i am running test script in the terminal its generating 2 errors i.e: 
1) app press "before all" hook:
     Error: timeout of 600000ms exceeded. Ensure the done() callback is being called in this test.
 
  2) app press "after all" hook:
     Error: timeout of 600000ms exceeded. Ensure the done() callback is being called in this test.
could anyone please solve this issue.

Environment

* Appium version : 1.7.2 
* Desktop OS/version used to run Appium : macOS 10.13.4
* Node.js version : 9.1.0
* Appium CLI or Appium.app|exe: Appium tool 1..5.3 version 

Details

I have to run my full application in testdroid. But i couldn't facing "before all hook and after all hook"
errors. I have set 6 mins of time also
![screen shot 2018-04-06 at 8 52 46 am](https://user-images.githubusercontent.com/36480468/38403497-7d3c12da-3981-11e8-93ce-c97f4daaf3da.png)
![screen shot 2018-04-06 at 10 02 35 am](https://user-images.githubusercontent.com/36480468/38403522-adb6692e-3981-11e8-80a1-97376b2bd013.png)

**Comment by mykola-mokhnach** [comment]
Closed as non server-related. Please ask questions on discuss.appuim.io
