### ISSUE TITLE
INFO [DefaultRemoteProxy.onEvent] - Marking the node http://0.0.0.0:4750 as down: cannot reach the node for 2 tries

### ISSUE THREAD

**Issue by stephenws** [appium/appium#10494]
## The problem

I am using selenium-server-standalone-3.11.0 for connecting nodes to Hub. After connecting node to hub I am getting below error:

INFO [DefaultGridRegistry.add] - Registered a node http://0.0.0.0:4750
INFO [DefaultRemoteProxy.onEvent] - Marking the node http://0.0.0.0:4751 as down: cannot reach the node for 2 tries
INFO [DefaultRemoteProxy.onEvent] - Marking the node http://0.0.0.0:4750 as down: cannot reach the node for 2 tries

On hub console it shows that devices are connected as given in attached screenshot.

![image](https://user-images.githubusercontent.com/26320996/38408265-6dfe1606-399a-11e8-9d2d-c8d50fa8f532.png)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.0
* Desktop OS/version used to run Appium: 10.12.6
* Node.js version (unless using Appium.app|exe):v6.11.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

https://gist.github.com/stephenws/fe5ec8fce5dc69dba80cf8f4ba47a49c

**Comment by mykola-mokhnach** [comment]
Try to downgrade the hub to 3.7

**Comment by stephenws** [comment]
I have tried now, I am getting Error "Defaultremoteproxy unknown version,Server Response code: 407"
in Grid Console.
This might be i am sitting in office network proxy,. could you please help me how to resolve this problem?

**Comment by mykola-mokhnach** [comment]
Sorry, but I know nothing about proxy setup. Try to ask on Selenium forums. 

Closed as non server-related.

**Comment by stephenws** [comment]
As mentioned in selenium forum, I have run appium servers on hub machine and connecting devices to node machine. While running code from Hub it gives below error:
**org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Device was not in the list of connected devices** @mykola-mokhnach
