### ISSUE TITLE
set_location sometimes fails on ios simulator 

### ISSUE THREAD

**Issue by djwgit** [appium/appium#10490]
## The problem
set_location often fails on ios simulator when runs on jenkins (macos)

## Environment

* Appium version 1.7.2
* Desktop OS/version used to run Appium: Mac OS high serria, 
* Mobile platform/version under test:  ios simulator 11.2
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe:  cli  on jenkins

## Details
- with appium 1.7.2 on ios 11.2 simulator.
- set_location (it uses applescript to drive the simulator menu ui to set location),
- it works well when run on local machine, 
- but when run on a jenkins server, it fails quite often. but if vnc to the test machine, have the vnc session connected, then set_location will be ok.
- in system **security & privacy setting for accessiblity, already added for Terminal**

after some digging, this maybe due to that AppleScript fails to run when display is asleep... 

## Link to Appium logs
https://gist.github.com/djwgit/abf90854e1731b386411e7f13a603689

## Code To Reproduce Issue [ Good To Have ]
on my jenkins server
the jenkins task first start appium server, then run test with cucumber
> appium &
> cucumber test.feature

**Comment by dpgraham** [comment]
What could be happening is that during the failing tests, the Simulator loses focus. Is there other applications running that could steal the focus from the Sim?

**Comment by djwgit** [comment]
@dpgraham 
the jenkins slave node is limited to only runs one task,  most likely, Applescript has trouble driving UI when the display sleeps.   this is kind of weird if so... :-)
https://macscripter.net/viewtopic.php?id=42757

**Comment by djwgit** [comment]
@dpgraham 
adding this to the applescript for setting simulator gps location, it will wake up the screen and will be ok
```
  # wake up the screen in case
  tell application "Finder"
    do shell script "caffeinate -u true"
  end tell
```

**Comment by mykola-mokhnach** [comment]
Wouldn't it be easier to just disable sleep on the destination Jenkins node?

**Comment by jdougit** [comment]
@mykola-mokhnach , not machine sleep, display sleep, 
guess, people don't want to have the test machine monitor on all the time.
could run the applescript before running the test...
 taking care of it in appium might be nicer...

**Comment by mykola-mokhnach** [comment]
What is the point to have a display constantly connected to a node? We use http://www.fit-pc.com/web/products/fit-headless/ in our lab and all nodes are controlled remotely via screen share.

**Comment by jdougit** [comment]
@mykola-mokhnach  thanks for the info for mac minis as node.
we have several nodes are retired macbook :-)
anyway, I could workaround this issue different ways...   this issue can be closed... thanks.
