### ISSUE TITLE
Appium IOS tap not being registered

### ISSUE THREAD

**Issue by MamunC** [appium/appium#10507]
## The problem

Tap is not working for a specific button in the app. It was working previously, but all of a sudden it is not and can not pin point the reason. There has been no development changes in the app
 
## Environment

* Appium v.1.7.2
* simulator: iPhone 6/10.3
* Xcode 9.3.3

## Details

This is the code I have to tap on the element:
@iOSFindBy(accessibility = "testEL")
 private MobileElement el;
.....
new TouchAction((PerformsTouchActions) el.getWrappedDriver()).tap(el).perform();

In the appium logs, I am getting success code 200 upon execution of the tap command, however I don't see the corresponding action on the simulator. If I click through manually, the test continues executing properly.

Other buttons in the app are working fine. Other elements on the same screen are accessible and are working fine as well.

**Comment by mykola-mokhnach** [comment]
Try appium@beta

**Comment by mykola-mokhnach** [comment]
Xcode upgrade might be the reason. One never knows what else Apple changes there.

**Comment by MamunC** [comment]
Thanks for the quick response. Saw the issue with Appium 1.6.4 and Xcode 8. Upgraded but still seeing the issue. Will give Appium beta a shot

**Comment by MamunC** [comment]
Upgrading to Appium 1.8 beta has fixed the issue. Thanks!!
