### ISSUE TITLE
On MAC - Appium - Install - Using npm(as Sudo user) - Getting permission error while installing Appium using npm(as sudo user) on mac 

### ISSUE THREAD

**Issue by ravirsoni** [appium/appium#10509]
**Description :** On MAC - Appium - Install - Using npm(as Sudo user) - Getting permission error while installing Appium using npm(as sudo user) on mac  

command i used to install appium via npm is : **sudo npm install -g appium**
Mac os : 10.12.6

**Error details :: ** 

/usr/local/bin/appium -> /usr/local/lib/node_modules/appium/build/lib/main.js

> fsevents@1.1.3 install /usr/local/lib/node_modules/appium/node_modules/fsevents
> node install

[fsevents] Success: "/usr/local/lib/node_modules/appium/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> appium-chromedriver@3.1.4 install /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver
> node install-npm.js

(node:1907) **UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/201839-1907-s36e7g.2gcaq'**
(node:1907) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1907) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
info Chromedriver Install Installing Chromedriver version '2.33' for platform 'mac' and architecture '64'
info Chromedriver Install Opening temp file to write chromedriver_mac64 to...
**Error: EACCES: permission denied, mkdir** '/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/201839-1907-9g5r1.g1a0mh'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-chromedriver@3.1.4 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium-chromedriver@3.1.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/userhomedirectory/.npm/_logs/2018-04-09T22_49_54_875Z-debug.log

**More Details :** 
node -v :: v8.11.1
npm -v :: 5.8.0

**Note :**  
- I too have similar issue in the past while installing the Node and i resolved it using sudo with it. But now getting the same error for Installation of the Appium using npm. Using Sudo did not help me. 
- And also checked that i am having Admin right also. So shouldn't be the issue.

Please help me out with this.

Thanks in advance.

**Comment by mykola-mokhnach** [comment]
Appium should not be installed with sudo permissions. Make sure your current user has write permissions inside /usr/local/lib folder and retry package installation.

**Comment by mykola-mokhnach** [comment]
Change them manually

**Comment by ravirsoni** [comment]
when i checked my permission using "ls -la" for "/usr/local/lib" it shows like 
**drwxr-xr-x   7 root  tom  238 Apr  5 16:01 lib** and the current user is "ravi1234", so here the current user is "ravi1234" but shows as root and write permission is already given if you see or am i missing anything here ?

**Comment by ravirsoni** [comment]
do i really need Write access here ? Sorry asking again and again same thing.

**Comment by ravirsoni** [comment]
sudo chown -R $USER /usr/local

After running above line of code on my terminal . it changed the permission as show below and i could install the Appium successfully.   

drwxr-xr-x     9 ravii  wheel    306 Apr  6 11:40 local
