### ISSUE TITLE
Appium Desktop 1.4.1 - Unable to run tests on Iphone 5s and Iphone 7Plus

### ISSUE THREAD

**Issue by chrisd2707** [appium/appium#10508]
## The problem
I'm using the JSON below in Appium Desktop but instead of invoking a real device it gives me an error. Error and JSON are below:
 
"An unknown server-side error occurred while processing the command. Original error: Could not create simulator with name 'appiumTest-0b7b9e19-3177-4487-858e-c70bf474262c', device type id 'DhruvAnuradha' and runtime id '11.2'. Reason: 'simctl error running 'create': Invalid device type: DhruvAnuradha'  "
 
 
{
  "xcodeOrgId": "Trunk Digital Studios, LLC",
  "xcodeSigningId": "iPhone Developer",
  "platformName": "IOS",
  "bundleId": "digital.trunk.honeycomb",
  "automationName": "XCUITest",
  "UDID": "09f7caab97b6536f2c5cd213fc90fd34609f1365",
  "deviceName": "DhruvAnuradha"
}
 
I tried various combinations of Desired Capabilities but Appium Desktop 1.4.1 gives an error regardless.
 
Please troubleshoot.
 
Thanks
Dinesh
Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue: 1.4.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac High Sierrra
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: IOS latest version
* Real device or emulator/simulator: Real device Iphone 5s
* Appium CLI or Appium.app|exe: Appium Desktop V 1.4.1

## Details

I did try the same test on Iphone 7Plus with the same result. I tried several combinations of Desired capabilities; but each time the error is Appium is unable to recognise the device either by name or it's UDID.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
change `UDID` to `udid` and set `deviceName` to the value returned by `idevicename` tool.
