### ISSUE TITLE
Appium 1.7.2 - Appium inspector displays 'Could not obtain screenshot: [object Object]

### ISSUE THREAD

**Issue by githubdilip** [appium/appium#10502]
## The problem

I am using Appium 1.7.2 desktop appium version is automate iOS native app 11.2.5 OS version. In the appium inspector, couldn't get the corresponding screenshot of the application getting error as 'Could not obtain screenshot: [object Object]' in the screenshot pane but able to get the page elements in app source pane. Please do the needful

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): 1.6.4
* Desktop OS/version used to run Appium: 10.13
* Node.js version (unless using Appium.app|exe): 
* Mobile platform/version under test: iOS 11.2.5
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium.app

## Details

With Appium 1.6.4 able to inspect element with screenshot for iOS 10 version

## Appium logs

[XCUITest] Executing command 'getScreenshot'
[XCUITest] Taking screenshot with WDA
[JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/DC555037-8EC7-4A68-A462-47B6BEDFFBC7/screenshot] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"Error Domain=com.facebook.WebDriverAgent Code=1 \\\"Cannot take a screenshot of the current screen state\\\" UserInfo={NSLocalizedDescription=Cannot take a screenshot of the current screen state}\",\n  \"sessionId\" : \"DC555037-8EC7-4A68-A462-47B6BEDFFBC7\",\n  \"status\" : 13\n}"
[XCUITest] Error getting screenshot: An unknown server-side error occurred while processing the command.
[XCUITest] Taking screenshot with 'idevicescreenshot'
[JSONWP Proxy] Proxying [GET /orientation] to [GET http://localhost:8100/session/DC555037-8EC7-4A68-A462-47B6BEDFFBC7/orientation] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"LANDSCAPE\",\n  \"sessionId\" : \"DC555037-8EC7-4A68-A462-47B6BEDFFBC7\",\n  \"status\" : 0\n}"
[XCUITest] Error getting screenshot through 'idevicescreenshot': Cannot take a screenshot from the device '30880fbea7d2960298b8f478775f1a88b8994248' using idevicescreenshot. Original error: Command 'idevicescreenshot -u /var/folders/b6/pljv07_x56j_8vvvs4xxmhs40000gr/T/201839-3281-1b053sf.5za7h/screenshot-.tiff' exited with code 255

**Comment by mykola-mokhnach** [comment]
What is the output of idevicescreenshot utility if the command is executed manually? Are you sure that WDA binary on the device is up to date?

**Comment by githubdilip** [comment]
@mykola-mokhnach I am using the desktop appium 'appium-desktop-1.4.1-mac.zip' and when i execute 'idevicescreenshot -u' getting the error 'Could not connect to lockdownd, error code -21'. Can you please tell me which command exactly to use ?

**Comment by mykola-mokhnach** [comment]
You could try to fix the problem yourself: https://www.google.de/search?q=Could+not+connect+to+lockdownd%2C+error+code+-21

Regarding WebDriverAgent version - uninstall it from the device manually and then let Appium to install it again.

**Comment by githubdilip** [comment]
@mykola-mokhnach 'Could not obtain screenshot: [object Object]' this issue happens only with real device, in simulator the screenshot is getting loaded properly. Is there anything specific to real device we need to set. Can you please help ?
Getting below error:

[JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/CA131C35-AD8E-400B-9384-8384BA4C64FF/screenshot] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"Error Domain=com.facebook.WebDriverAgent Code=1 \\\"Cannot take a screenshot of the current screen state\\\" UserInfo={NSLocalizedDescription=Cannot take a screenshot of the current screen state}\",\n  \"sessionId\" : \"CA131C35-AD8E-400B-9384-8384BA4C64FF\",\n  \"status\" : 13\n}"

**Comment by mykola-mokhnach** [comment]
I've already answered above. There's nothing more I can advice.

**Comment by githubdilip** [comment]
Issue got resolved when i reinstall libimobiledevice with 'brew install libimobiledevice --HEAD' command.. Thank you...
