### ISSUE TITLE
when configed the remoteAdbHost and systemPort capabilities, the  appium server  can  not find  remote device.

### ISSUE THREAD

**Issue by WenRui13** [appium/appium#10503]
## The problem

My test is running on remote appium server by jenkins,  and the also the two server are on the same machine.  The adb server is on another machine. When configed the remoteAdbHost and systemPort capabilities, the  appium server  can  not find  remote device.

## Environment

* Appium version (or git revision) that exhibits the issue:1.7.2
* Last Appium version that did not exhibit the issue (if applicable):NA
* Desktop OS/version used to run Appium:NA
* Node.js version (unless using Appium.app|exe):v9.8.0
* Mobile platform/version under test:5.0+
* Real device or emulator/simulator:Real device on  stf
* Appium CLI or Appium.app|exe: NA

## Details

when configed the remoteAdbHost and systemPort capabilities, the  appium server  can  not find  remote device.
see the log:
>[UiAutomator2] Waiting up to 20000ms for UiAutomator2 to be online...
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8290/wd/hub/status] with no body
[UiAutomator2] [UIAutomator2 Error] Failure: 'device '5e53d013' not found'
[debug] [UiAutomator2] Full error: FailError: Failure: 'device '5e53d013' not found'
[debug] [UiAutomator2]     at /root/.nvm/v9.8.0/lib/node_modules/appium/node_modules/_adbkit@2.11.0@adbkit/lib/adb/parser.js:183:29
[debug] [UiAutomator2]     at tryCatcher (/root/.nvm/v9.8.0/lib/node_modules/appium/node_modules/_bluebird@2.9.34@bluebird/js/main/util.js:26:23)
[debug] [UiAutomator2]     at Promise._settlePromiseFromHandler (/root/.nvm/v9.8.0/lib/node_modules/appium/node_modules/_bluebird@2.9.34@bluebird/js/main/promise.js:503:31)
[debug] [UiAutomator2]     at Promise._settlePromiseAt (/root/.nvm/v9.8.0/lib/node_modules/appium/node_modules/_bluebird@2.9.34@bluebird/js/main/promise.js:577:18)
[debug] [UiAutomator2]     at Async._drainQueue (/root/.nvm/v9.8.0/lib/node_modules/appium/node_modules/_bluebird@2.9.34@bluebird/js/main/async.js:128:12)
[debug] [UiAutomator2]     at Async._drainQueues (/root/.nvm/v9.8.0/lib/node_modules/appium/node_modules/_bluebird@2.9.34@bluebird/js/main/async.js:133:10)
[debug] [UiAutomator2]     at Immediate.Async.drainQueues [as _onImmediate] (/root/.nvm/v9.8.0/lib/node_modules/appium/node_modules/_bluebird@2.9.34@bluebird/js/main/async.js:15:14)
[debug] [UiAutomator2]     at runCallback (timers.js:763:18)
[debug] [UiAutomator2]     at tryOnImmediate (timers.js:734:5)
[debug] [UiAutomator2]     at processImmediate (timers.js:716:5)
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8290/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8290/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8290/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8290/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8290/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8290/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8290/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8290/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8290/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8290/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8290/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8290/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8290/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8290/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8290/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8290/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8290/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8290/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8290/wd/hub/status] with no body
[debug] [UiAutomator2] Deleting UiAutomator2 session

## detail Appium logs
https://gist.github.com/WenRui13/f63deced7bf578781d169f6e60a07805

## Code To Reproduce Issue [ Good To Have ]
my code is bellow:
https://gist.github.com/WenRui13/2ee1ac62e42949fa7883073264824dcf

my test frame just is 
![image](https://user-images.githubusercontent.com/6370420/38491233-de4ed8c0-3c1d-11e8-98c3-59fc7d7139d3.png)

**Comment by WenRui13** [comment]
UiAutomator2  can not be launched,  Shouldn’t the command be like this?
>adb -H 10.1.64.47 -s 5e53d013 shell am instrument -w io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner

![image](https://user-images.githubusercontent.com/6370420/38493538-260f4b98-3c25-11e8-94aa-98afaf465554.png)

**Comment by saikrishna321** [comment]
@WenRui13 can you pls try with latest appium it should work. This was published in 

`
appium-uiautomator2-driver@1.0.1
`

**Comment by WenRui13** [comment]
@saikrishna321 tks, Do you mean that I should  update  appium version   to 1.8.0-beta4 ?
![image](https://user-images.githubusercontent.com/6370420/38531866-b7676f06-3ca4-11e8-9a6f-12098355831c.png)

**Comment by saikrishna321** [comment]
> how many devices does one appium server instance can support?

This depends on your system config. I have been running around 18 devices and it works fine.

**Comment by WenRui13** [comment]
@saikrishna321 tks a lot!
