### ISSUE TITLE
Method name: scrollToEnd not supported

### ISSUE THREAD

**Issue by bahunov** [appium/appium#10511]
## The problem

I'm trying to use scroll to end:
                driver.findElementByAndroidUIAutomator("new UiScrollable(new UiSelector().scrollable(true).instance(0))" +
                    ".scrollToEnd(10);");

But getting this in appium logs:
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Method name: scrollToEnd
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":9,"value":"Could not parse UiSelector argument: Must only call the 'scrollIntoView' method OR methods on UiScrollable which return UiScrollable or UiObject objects"}

## Environment
* 1.7.1
* iOS
*Android
* Simulator

## Details

Sometimes I'm not able to scroll to the end when I want to find an element at the last of a recycle_view_id

That's why I wanted to use scrollToEnd...

Is there any better approach????

**Comment by bahunov** [comment]
Found a workaround to this issue:  
private void helpScroll(){
        Dimension size = this.driver.manage ()
            .window ()
            .getSize ();
        int startX = size.getWidth () / 2;
        int startY = size.getHeight () / 2;
        int endX = 0;
        int endY = (int) (startY * -1 * 0.75);
        TouchAction action = new TouchAction (this.driver);
        action.press (startX, startY)
            .moveTo (endX, endY)
            .release ()
            .perform ();
    }

to do the last scrolling to reach the end of the list:
public WebElement scrollByDesc(String desc) {
        try {
            return scrollToDesc(desc);

        } catch (Exception e) {
            helpScroll();
            return scrollToDesc(desc);
        }
    }

private WebElement scrollToDesc(String desc){
        return driver.findElementByAndroidUIAutomator("new UiScrollable(new UiSelector().scrollable(true).instance(0))" +
            ".scrollIntoView(new UiSelector().descriptionContains(" + "\"" + desc + "\"" + "));");
    }

**Comment by Kitty2014** [comment]
any update?

**Comment by bahunov** [comment]
Yes.. just use the solution above to get around this.. helpScroll()
