### ISSUE TITLE
[MJSONWP] Encountered internal error running command: Error: You must include a platformName capability

### ISSUE THREAD

**Issue by Saifalip** [appium/appium#10513]
## The problem

When i am starting the appium, its displaying the error as "[MJSONWP] Encountered internal error running command: Error: You must include a platformName capability" 
I have set platformName as iOS also

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Desktop OS/version used to run Appium: macOS 10.13.4
* Node.js version (unless using Appium.app|exe): 9.1.0
* Appium CLI or Appium.app|exe: 1.5.3

## Code To Reproduce Issue:
This is my code to run test testdroid

module.exports.getCapabilities = function getCapabilitiesFunc(ipaData, testdroidDevices, inputDevice) {
	const devices = testdroidDevices || [];
	console.log("devices-------->", devices);
	const deviceToUse = pickDevice(devices, inputDevice) || testdroidConfig.defaultIOSDevice;
	deviceUsed(deviceToUse);
	const desired = {};
	desired.platformName = "iOS"; //"Android" in testdroid sample java project, "safari" in sample node ios project
	desired.platform = "iOS";
	desired.testdroid_target = "ios"; //"Android" in testdroid sample java project, "safari" in sample node ios project
	desired.deviceName = "iPhone device";
	desired.testdroid_username = testdroidConfig.user;
	desired.testdroid_password = testdroidConfig.pass;
	desired.testdroid_project = TESTDROID_PROJECT;
	desired.testdroid_testrun = TEST_RUN_NAME;
	desired.testdroid_device = testdroidConfig.defaultIOSDevice;
![screen shot 2018-04-10 at 3 18 18 pm](https://user-images.githubusercontent.com/36480468/38549782-7a88b1ac-3cd2-11e8-87a3-beb89f7bcf4b.png)
![screen shot 2018-04-10 at 3 18 27 pm](https://user-images.githubusercontent.com/36480468/38549783-7ab9777e-3cd2-11e8-9c96-5990797a26d6.png)
![screen shot 2018-04-10 at 11 55 38 am](https://user-images.githubusercontent.com/36480468/38549784-7ae6597e-3cd2-11e8-9117-e4d74c385685.png)

**Comment by mykola-mokhnach** [comment]
It looks like your client does not pass this capability to the Appium server

**Comment by Saifalip** [comment]
Thanks @mykola-mokhnach 
Could you please tell me how to pass the capabilities

**Comment by mykola-mokhnach** [comment]
I have no idea. Check it with the developer of your client framework

**Comment by Saifalip** [comment]
Okay thanks for replying @mykola-mokhnach

**Comment by Saifalip** [comment]
@mykola-mokhnach 
is any one faced this error and solved ?

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by nrazvan87** [comment]
@Saifalip I had the same error, after a while I've noticed that the simulator iOS version isn't the same as the one specified in capabilities (platformVersion=11.3 my case)
