### ISSUE TITLE
crash in UITestingUITests/testRunner after executing findElement with appium 1.7.2

### ISSUE THREAD

**Issue by githubdilip** [appium/appium#10512]
## The problem

Using appium 1.7.2 for iOS native app automation. Once the script is executing findElement, the test get fail and the app get closed automatically. Issue happens in once particular page alone

## Environment

* Appium version (or git revision) that exhibits the issue:1.7.2
* Last Appium version that did not exhibit the issue (if applicable):1.6.4
* Desktop OS/version used to run Appium: 10.13
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:iOS 11.2
* Real device or emulator/simulator:Real Device
* Appium CLI or Appium.app|exe:Appium.app

## Appium logs

https://gist.github.com/githubdilip/a8f63021460f5bfbf8549e45da991e86

**Comment by mykola-mokhnach** [comment]
There is nothing we can do about it on Appium side. Please report the bug to Apple's XCTest
