### ISSUE TITLE
Encountered internal error: TimeoutError

### ISSUE THREAD

**Issue by SouWilliams** [appium/appium#10510]
## The problem
Executing test on iPhone7 plus, sometimes will encounter internal timeout error.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0-beta4
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2
* Desktop OS/version used to run Appium: MAC 10.13.4 (17E199)
* Node.js version (unless using Appium.app|exe): 9.10.1
* Mobile platform/version under test: iOS 11.3
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details
Executing test on iPhone7 plus, sometimes will encounter internal timeout error.

## Link to Appium logs
[Appium log](https://gist.github.com/SouWilliams/726085521dc4b8777ecca91fbc491e09)

## Code To Reproduce Issue [ Good To Have ]

    private WebDriver iosDriver;

    @Test
    public void setUp() throws InterruptedException, MalformedURLException {

        DesiredCapabilities capabilities = DesiredCapabilities.iphone();
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME,"iPhone 7 Plus");
        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME,"iOS");
        capabilities.setCapability(IOSMobileCapabilityType.XCODE_ORG_ID,"5Y9WXXXXXX");
        capabilities.setCapability(IOSMobileCapabilityType.XCODE_SIGNING_ID, "iPhone Developer");
        capabilities.setCapability(IOSMobileCapabilityType.START_IWDP, true);
        capabilities.setCapability(IOSMobileCapabilityType.AUTO_ACCEPT_ALERTS, true);
        capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME,"XCUITest");
        capabilities.setCapability(MobileCapabilityType.BROWSER_NAME,"Safari");
        capabilities.setCapability(IOSMobileCapabilityType.SAFARI_ALLOW_POPUPS, true);
        capabilities.setCapability(IOSMobileCapabilityType.SAFARI_OPEN_LINKS_IN_BACKGROUND, true);
        capabilities.setCapability(MobileCapabilityType.UDID, "bb080d8ed2e9a4c9bb3fc85c95138441090f1e78");
        capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT,"360");
//        capabilities.setCapability(MobileCapabilityType.NO_RESET, true);

        iosDriver = new RemoteWebDriver(new URL("http://127.0.0.1:4723/wd/hub"),capabilities);
        iosDriver.get("https://getbootstrap.com/");
        iosDriver.manage().timeouts().pageLoadTimeout(20, TimeUnit.SECONDS);
        iosDriver.findElement(By.xpath("/html/body/header/div/ul/li[2]/a")).click();
//        iosDriver.switchTo().alert().accept();
//        iosDriver.close();
    }

**Comment by SouWilliams** [comment]
![image](https://user-images.githubusercontent.com/6127395/38538462-8aef3f9a-3cc6-11e8-96dc-a18affaa7d29.png)

**Comment by mykola-mokhnach** [comment]
@SouWilliams The recent appium@beta release has some fixes, so the timeout issue above should not pop up anymore
