### ISSUE TITLE
Android uiautomator and uiautomator2 driver desired_capabilities inconsistancies 

### ISSUE THREAD

**Issue by Jiurong-Yang** [appium/appium#10517]
This is ran against the latest appium beta (Master branch)
But I'm pretty sure it occurs for any appium version that supports uiautomator2

Using python appium client. When I call driver.desired_capabilities on uiautomator2 I get 

{u'deviceName': u'Samsung S7 Marsh', u'udid': u'9885e633464d585058', u'automationName': u'uiautomator2', u'platform': u'ANDROID', u'nativeWebScreenshot': True, u'newCommandTimeout': 3600, u'platformVersion': u'7.0.1', u'appPackage': u'com.google.android.apps.docs', u'platformName': u'Android', u'appActivity': u'com.google.android.apps.docs.app.NewMainProxyActivity'}

But when I call driver.desired_capabilities on uiautomator I get

{u'deviceName': u'9885e633464d585058', u'appPackage': u'com.google.android.apps.docs', u'takesScreenshot': True, u'deviceManufacturer': u'samsung', u'deviceModel': u'SM-G930F', u'warnings': {}, u'udid': u'9885e633464d585058', u'javascriptEnabled': True, u'desired': {u'deviceName': u'Samsung S7 Marsh', u'udid': u'9885e633464d585058', u'platform': u'ANDROID', u'nativeWebScreenshot': True, u'newCommandTimeout': 3600, u'platformVersion': u'7.0.1', u'appPackage': u'com.google.android.apps.docs', u'platformName': u'Android', u'appActivity': u'com.google.android.apps.docs.app.NewMainProxyActivity'}, u'deviceScreenSize': u'1440x2560', u'networkConnectionEnabled': True, u'databaseEnabled': False, u'platform': u'ANDROID', u'deviceUDID': u'9885e633464d585058', u'nativeWebScreenshot': True, u'newCommandTimeout': 3600, u'platformVersion': u'7.0', u'webStorageEnabled': False, u'locationContextEnabled': False, u'platformName': u'Android', u'appActivity': u'com.google.android.apps.docs.app.NewMainProxyActivity'}

The code is run against the same server. 

Seems like the server side of the code that causes this is 
**uiautomator2 debug code**:
[debug] [W3C] Responding to client with driver.createSession() result: {"platformName":"Android","platformVersion":"7.0.1","deviceName":"Samsung S7 Marsh","deviceManufacturer":"samsung","udid":"9885e633464d585058","automationName":"uiautomator2","platform":"ANDROID","nativeWebScreenshot":true,"newCommandTimeout":3600,"appPackage":"com.google.android.apps.docs","appActivity":"com.google.android.apps.docs.app.NewMainProxyActivity"}

**uiautomator debug code**
[debug] [W3C] Responding to client with driver.createSession() result: {u'deviceName': u'9885e633464d585058', u'appPackage': u'com.google.android.apps.docs', u'takesScreenshot': True, u'deviceManufacturer': u'samsung', u'deviceModel': u'SM-G930F', u'warnings': {}, u'udid': u'9885e633464d585058', u'javascriptEnabled': True, u'desired': {u'deviceName': u'Samsung S7 Marsh', u'udid': u'9885e633464d585058', u'platform': u'ANDROID', u'nativeWebScreenshot': True, u'newCommandTimeout': 3600, u'platformVersion': u'7.0.1', u'appPackage': u'com.google.android.apps.docs', u'platformName': u'Android', u'appActivity': u'com.google.android.apps.docs.app.NewMainProxyActivity'}, u'deviceScreenSize': u'1440x2560', u'networkConnectionEnabled': True, u'databaseEnabled': False, u'platform': u'ANDROID', u'deviceUDID': u'9885e633464d585058', u'nativeWebScreenshot': True, u'newCommandTimeout': 3600, u'platformVersion': u'7.0', u'webStorageEnabled': False, u'locationContextEnabled': False, u'platformName': u'Android', u'appActivity': u'com.google.android.apps.docs.app.NewMainProxyActivity'}

Just wondering if this is a planned change or if the uiautomator and uiautomator2 driver have some unplanned inconsistency. 

The inconsistency is important to me because in my code logic I rely on getting the manufacturer information from the driver instance because it's dynamic and requires less hard coding. But with uiautomator2 this information is no longer accessible. I just feel like the two drivers should be providing the same information to avoid backward compatibility issues. 

PS: This problem can be worked around if the deviceManufacturer is set when starting the appium server with the --default-capabilities flag. But this is not as desirable as if appium can just provide me the information without additional server set up steps.

**Comment by imurchie** [comment]
Can you provide the _full_ server logs? I don't see this happening with the latest driver, and I cannot tell from the snippet you've provided, what is running.

**Comment by dpgraham** [comment]
@Jiurong-Yang Just to confirm, are you clearing the node_modules and reinstalling them?

**Comment by Jiurong-Yang** [comment]
The instance I am running is pretty new installation. I did build the server with version 1.7.2 first but the uiautomator2 server was having issues. So i rebuild the appium server with the master branch code.  I just do the usual npm install in repo and call the transpile gulp command. I can try to remove the entire node_modules folder and rebuild the server tomorrow and see if that changes anything

**Comment by imurchie** [comment]
The change above is in `appium-uiautomator2-driver` 1.9.0 (https://github.com/appium/appium-uiautomator2-driver/commit/a7cb518a466d390bb4565f77946c2073fa75fc5e). You have 1.8.0
```
[Appium] Creating new AndroidUiautomator2Driver (v1.8.0) session
```

Upgrade and this should be fixed.

**Comment by Jiurong-Yang** [comment]
I see, I just wasn't sure if this change was intentional or not. If it's unintentional then I'll test it out once 1.8 is officially released. Thank you guys so much for this information.
