### ISSUE TITLE
Focus changes before sendKey in payment form field in 1.7.2 for Android

### ISSUE THREAD

**Issue by rabadam** [appium/appium#10515]
I get this focus change issue on android app's payment form. I'm currently on 1.7.2. Tried workarounds by do click() or clear() into other fields to somehow get a lock on my the field I want to sendKey() on, but the focus changes no matter what I do.

Emulator (Nexus_6P_API_24)
Appium Server v1.7.2
Log: [https://gist.github.com/rabadam/ee35c88bea7a9c3f4a8a448b064547ee](https://gist.github.com/rabadam/ee35c88bea7a9c3f4a8a448b064547ee)

The form is for cc payment within the app.
Enter name - Good
Enter CC# - Good
Enter Exp - Before the sendKey() happens, the field focus shifts back to the CC# field and the exp values replace the last digits in the CC# previously entered.

Thanks for your help.

Not sure it is the same issue from https://github.com/appium/appium/issues/3900

**Comment by mykola-mokhnach** [comment]
Try switching to UIAutomator2

**Comment by rabadam** [comment]
@mykola-mokhnach Thank you!! That was the solution.
