### ISSUE TITLE
Package selendroid.xx.xx.xx does not have a signature matching the target

### ISSUE THREAD

**Issue by MrShakes** [appium/appium#10527]
## The problem

I'm trying to run tests on a hybrid App (Ionic) and its not launching, getting error: `Package selendroid.xx.xx.xx does not have a signature matching the target` 
I tried uninstalling both the Apk and Selendroid Apk on the emulator and trying again with no luck. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Desktop OS/version used to run Appium: MacOS High Sierra 10.13.2
* Node.js version (unless using Appium.app|exe): 6.10.2
* Mobile platform/version under test: Android 6.0 Google Nexus 5X
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: 1.7.2

## Details

My code:
```
const wdio = require('webdriverio');

const opts = {
  port: 4723,
  desiredCapabilities: {
    platformName: "Android",
    platformVersion: "6.0",
    deviceName: "Android Emulator",
    app: '/Users/xx/Desktop/Awork/nxhealthpe/platforms/android/build/outputs/apk/debug/android-debug.apk',
    automationName: "selendroid",
    autoWebview: true
  }
};

const client = wdio.remote(opts);

client.init();
client
  .contexts().then(function (contexts) {
        return client.context(contexts[1]); 
    })

  .click("#signin")
```

## Link to Appium logs

https://gist.github.com/MrShakes/8eae6a596c74fac257707546a06fe55d

**Comment by dpgraham** [comment]
@imurchie Do we still support the Selendroid driver?

**Comment by mykola-mokhnach** [comment]
I assume this might happen because the recent fixes there are not published and libs are not up to date.

**Comment by MrShakes** [comment]
Hi, is there an alternative to Selendroid for Hybrid Android, code base isn't maintained properly?

**Comment by imurchie** [comment]
We do support it, but it's only necessary for _old_ versions of Android. This is not the case here. 

I would use `uiautomator2` as the automation, as in a normal native test. Appium will handle the background automation of the webview in the hybrid app.

**Comment by MrShakes** [comment]
Thanks, using the same code above and changing the `automationName` as suggested it loads the App however I do not get a click event nor do I get an error as the docs suggested, I have a `div` with the `id` `signin`, I'm struggling to find Ionic examples to help, gist: https://gist.github.com/MrShakes/1afdf5472a48cd8884fb2b931a6e27fd

**Comment by mykola-mokhnach** [comment]
You can use discuss.appium.io to ask questions.
