### ISSUE TITLE
Consider resurrecting package-lock.json for drivers

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#10529]
Hey all. I know that @imurchie recently went through all of Appium's repositories and knocked out and disabled all of the package-lock.json files, but after doing some research about NPM 5 (and Yarn), I think we should consider bringing it back. Only for `appium/appium` (replacing shrinkwrap) and all of the drivers (XCUITest, UIA2, Espresso, IOS, Android, Mac, Windows)

# Rationale
* Determinism
  * If we commit a package-lock.json, the dependency installations for that package will be the same across all machines because it only installs what is in the package-lock.json
  * npm@5 introduced a command called `npm ci` (that @mykola-mokhnach shared with us) which does a clean-slate installation of `node_modules` and updates the modules to only install what is in package-lock.json; no more `rm -rf node_modules && npm install`
* Fewer last minute surprises
  * Node packages are constantly being updated and thus Appium's dependencies are constantly being changed
  * It's only prior to a release that we lock it down using shrinkwrap
  * If `appium/appium` and the drivers _always_ have a package-lock.json, then the state of the dependencies will only change when we choose to upgrade the package-lock.json
* Safer Modularization (a la Appium 2)
  * Currently, the plan for Appium 2 is to make it a CLI that installs other drivers. This will make it more important for us to do releases of the drivers more cautiously. 
  * Having a package-lock.json on the drivers aids this by having the drivers use fixed dependencies so that we don't run the risk of users installing drivers and getting completely different dependencies then what we had tested
* Git History
  * Because package-lock.json is committed to source control, we can actually use `git bisect` to go through history and accurately re-create the state of dependencies of past commits

# Drawbacks
* Different versions of same dependencies
  * If two packages are using the same dependency but package-lock specifies a different version of each, it would install both versions
  * Example: If XCUITestDriver package-lock specifies appium-base-driver@1.1.1 and AndroidDriver package-lock.json specifies appium-base-driver@1.1.2, both 1.1.1 and 1.1.2 will be installed by appium/appium
* Slower upgrades
  * package-lock.json is updated in one of two ways: 1) you make a change to the dependencies (install, uninstall,...) and an updated package-lock.json is generated; 2) you force the creation of a new package-lock.json
  * Because of this, repos with package-locks that aren't updated frequently may have dependencies that fall far behind the latest version

# Solution to Drawbacks
* Using [Greenkeeper](https://greenkeeper.io/) solves both of these problems
  * Greenkeeper checks for when dependencies for a repo become outdated, and the "Greenkeeper Bot" puts in a pull request to update the package.json _and_ the package-lock.json
  * This makes it so that packages will always have very recent dependencies so they won't be out-of-date and because all of the repos will have the most up-to-date versions of packages, there won't be multiple versions of the same package
  * An added benefit is that the Greenkeeper pull request triggers CI, so that if we make a breaking change in one of our packages (like recently with `appium-adb`) all of the package's dependents will trigger a CI build and we'll know right away if it breaks the build and we'll know the build was broken because of a dependency change (and not a code defect)
  * Furthermore, the Greenkeeper's PR's only updates package.json and package-lock.json, so if we ever suspect that a regression occurred due to a dependency update, we can look through the history at Greenkeeper commits

(cc: @imurchie @mykola-mokhnach @jlipps)

**Comment by mykola-mokhnach** [comment]
We do use greenkeeper in our products and it works. Although, modules update still requires manual interaction.

**Comment by dpgraham** [comment]
@mykola-mokhnach You're talking about on local machines?

**Comment by dpgraham** [comment]
Right, yeah.

**Comment by mykola-mokhnach** [comment]
@dpgraham Is this issue addresses by the RC release approach?

**Comment by dpgraham** [comment]
@mykola-mokhnach it is yeah. And I actually don't think we need to keep the `package-lock.json` committed all the time. I think we're better just using shrinkwrap on release branches.
