### ISSUE TITLE
Standardize caps handling in the drivers

### ISSUE THREAD

**Issue by imurchie** [appium/appium#10524]
## The problem

Currently in `createSession` we deal with `caps` and `this.caps` in non-standard ways (i.e., each driver does it its own way). We should make it normal, so the same info (or, at least, _all_ the information) is in one place in every driver. This should be `this.caps`, which is also aliased in `this.opts.caps` (care needs to be taken there, and it is currently not handled well).

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

**Comment by dpgraham** [comment]
I would add that this should also apply to the `Get Session Capabilities` command (endpoint `GET /session/:session_id`)
