### ISSUE TITLE
WebDriverAgentRunner crash on macOS 10.13.4

### ISSUE THREAD

**Issue by ndinoia** [appium/appium#10528]
## The problem

WebDriverAgentRunner crashes when using TouchActions on macOS 10.13.4
## Environment

* Appium version (or git revision) that exhibits the issue: `1.7.2` but also seeing it on `v1.8.0-beta5`
* Last Appium version that did not exhibit the issue (if applicable): works OK on macOS 10.13.3
* Desktop OS/version used to run Appium: `macOS 10.13.4`
* Node.js version (unless using Appium.app|exe): `v9.4.0`
* Mobile platform/version under test: `iOS`
* Real device or emulator/simulator: `simulator`
* Appium CLI or Appium.app|exe: CLI launched via `AppiumDriverLocalService`

## Details

Getting a crash as soon as the test attempts to use `TouchActions`

## Link to Appium logs

WebDriverAgentRunner crashlog: https://gist.github.com/ndinoia/d1a65ce8ca3e841189dd119b13de32d8

Appium.log: https://gist.github.com/ndinoia/9aba27b9fb0e66f0b21186cc55f2d41b

## Code To Reproduce Issue [ Good To Have ]

```
int centerX = element.getCenter().getX();
int centerY = element.getCenter().getY();
new TouchAction<>(driver).tap(PointOption.point(centerX, centerY)).perform();
```

**Comment by dpgraham** [comment]
* Which version of Xcode are you using (9.1, 9.2, 93, etc...)
* Which IOS version is this happening on (11.2, 11.3, etc...)

**Comment by mykola-mokhnach** [comment]
I think we can have a workaround for this issue. Will create a PR today

**Comment by ndinoia** [comment]
@dpgraham we're using `Xcode 9.3`
We're seeing this on iOS `11.2` simulators. We're looking at jumping ahead to 11.3 and it looks like it might be working ok there.

Thanks for the quick response guys 👍

**Comment by mykola-mokhnach** [comment]
The workaround has been published in beta
