### ISSUE TITLE
Unable to launch WebDriverAgent because of xcodebuild failure: "Command 'Scripts/bootstrap.sh -d'

### ISSUE THREAD

**Issue by MrShakes** [appium/appium#10526]
## The problem

I'm using a hybrid App (Ionic) and I'm trying to run tests and the App does not even load, I get the error: `Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: "Command 'Scripts/bootstrap.sh -d' exited with code 1"`

## Environment
* Appium version (or git revision) that exhibits the issue: 1.7.2
* Desktop OS/version used to run Appium: MacOS HighSierra 10.13.2
* Node.js version (unless using Appium.app|exe): 6.10.2
* Mobile platform/version under test: 11.2 IOS
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: 1.7.2

## Details

My code:
```
const wdio = require('webdriverio');

const opts = {
  port: 4723,
  desiredCapabilities: {
    platformName: "iOS",
    platformVersion: "11.2",
    deviceName: "iPhone Simulator",
    app: '/Users/xx/Desktop/Awork/nxhealthpe/platforms/ios/build/emulator/nxhealthpe.app',
    automationName: "XCUITest",
    autoWebview: true
  }
};

const client = wdio.remote(opts);

client.init();
client
  .contexts().then(function (contexts) { 
        return client.context(contexts[1]); 
    })
  .click("#signin")
```

## Link to Appium logs

https://gist.github.com/MrShakes/d61a2d67dc8af583695bf2e4e293d931

**Comment by MrShakes** [comment]
@dpgraham Updated

**Comment by dpgraham** [comment]
Can you try navigating to: `/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/` and running `./Script/bootstrap.sh -d` and post the output.

**Comment by MrShakes** [comment]
```
Fetching dependencies
*** Checking out RoutingHTTPServer at "v1.0.1"
Failed to check out repository into /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer: Could not create working directory (Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “RoutingHTTPServer” in the folder “Checkouts”." UserInfo={NSFilePath=/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer, NSUnderlyingError=0x7fcabfc83a80 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}})
```

**Comment by dpgraham** [comment]
Alright, so looks like it's you need to run Appium as a super user.

Can you try running your appium server by doing `sudo appium` and then try again?

**Comment by mykola-mokhnach** [comment]
`sudo chown -R $USER /usr/local/lib` should be enough

**Comment by edrum** [comment]
I used appium 1.7.2 & i did Only two things(reinstallation & linking) to solve

1. brew uninstall carthage
2. brew install carthage
3. brew link --overwrite carthage
4. restart & try

**Comment by MrShakes** [comment]
Fixed thanks

**Comment by MrShakes** [comment]
So I don't open a new issue, Appium seems to be changing "IPhone Simulator" to "IPhone 6" which in turn gives the `Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65"` error  meant for real devices, gist:
https://gist.github.com/MrShakes/b669715ca152b86e59985db81d2018f4

**Comment by dpgraham** [comment]
`iPhone Simulator` isn't a valid deviceName so it's defaulting to `iPhone 6`... and the Xcode build failure does apply to Simulators as well as real devices

**Comment by MrShakes** [comment]
The issues I've found to fix this all point to using on real devices i.e. issue 8062, when I `cd` to `/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent` and try to build the project I get `/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Routing/FBWebServer.m:12:9: 'RoutingHTTPServer/RoutingConnection.h' file not found`
Also the logs from Appium show `brew info libimobiledevice` exits with code 1 and when I run that in the terminal I get
```
libimobiledevice: stable 1.2.0 (bottled), HEAD
Library to communicate with iOS devices natively
https://www.libimobiledevice.org/
/usr/local/Cellar/libimobiledevice/1.2.0_2 (66 files, 984.8KB) *
  Poured from bottle on 2018-04-12 at 18:14:09
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/libimobiledevice.rb
==> Dependencies
Build: pkg-config ✔
Required: libtasn1 ✔, libplist ✔, usbmuxd ✔, openssl ✔
==> Options
--HEAD
	Install HEAD version
 
```

**Comment by dpgraham** [comment]
From WebDriverAgent, can you try running `./Scripts/bootstrap.sh` and `./Scripts/build.sh`

**Comment by MrShakes** [comment]
Both failed, for `./Scripts/bootstrap.sh `:
https://gist.github.com/MrShakes/334a10585fcca9bbd083c7a94e08ee4c
For `./Scripts/build.sh`
https://gist.github.com/MrShakes/d325cdce3eaee8d0700453e6c1d12519
