### ISSUE TITLE
Sendkeys not working with  Safari browser on iOS real device 

### ISSUE THREAD

**Issue by shridharkalagi** [appium/appium#10521]
## The problem

Sendkeys not working with  Safari browser on iOS real device (11.2.6)
## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0-beta5
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: iOS 10.12
* Node.js version (unless using Appium.app|exe): 7.1.2
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: CLI
* Java-client version - 6.0.0-BETA4

## Link to Appium logs

Server logs [here](https://gist.github.com/shridharkalagi/175601961601d20c54058d37f27fd43e)

**Comment by shridharkalagi** [comment]
@mykola-mokhnach can you help me on this?

**Comment by mykola-mokhnach** [comment]
Closed as inactive

**Comment by Summerxia88** [comment]
I'm facing issue with safari browser on ios simulator. Please help to fix this issue!! 
I tried the following ways, but no luck.
input.click();
input.clear();
Thread.sleep(1000);
input.sendKeys(username);
input.sendKeys(Keys.TAB);  not working

((JavascriptExecutor) driver).executeScript("console.log(arguments[0]); $(arguments[0]).change(); return true;", input);  not working 

The value is sent but cleared right away.

**Comment by archanapura** [comment]
Even I facing issue with safari browser on ios simulator. Values entered into text field is erased immediately. Used below command 
driver.findElement(By.xpath("xpath")).sendKeys(answer);
Please help with the same!!

**Comment by AEsmerio** [comment]
I've the same issue. Not working on Simulator with iOS 14.4.
