### ISSUE TITLE
ondemand.saucelabs.com:443 failed to respond

### ISSUE THREAD

**Issue by matteocollina** [appium/appium#10520]
## The problem

When I run the command the local works, but if I make the remote call, as per documentation, it gives me error.

## Environment

* Appium version : 1.7.2

## Details

This is my java file:

`
public class TestUI {

    public static final String USERNAME = "myusername.........";
    public static final String ACCESS_KEY = "mykey.........";
    public static final String URL_REMOTE = "https://transfer.sh/......./MyApp.ipa";

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) throws MalformedURLException {
        DesiredCapabilities desiredCapabilities = DesiredCapabilities.iphone(); 

        desiredCapabilities.setCapability(MobileCapabilityType.APPIUM_VERSION, "1.7.2");
        desiredCapabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
        desiredCapabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 8 Plus");
        desiredCapabilities.setCapability(MobileCapabilityType.NO_RESET, true);
        desiredCapabilities.setCapability(MobileCapabilityType.APP, URL_REMOTE);
        desiredCapabilities.setCapability("bundleId", "it.mybundleid.mybundleid");
        desiredCapabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.IOS_XCUI_TEST);

        URL url = new URL("https://" + USERNAME + ":" + ACCESS_KEY + "@ondemand.saucelabs.com:443/wd/hub");
        //URL url = new URL("http://0.0.0.0:4723/wd/hub");    it works

        IOSDriver driver = new IOSDriver(url, desiredCapabilities);
        driver.quit();
    }
}
`

## Link to Appium logs

Full Log : 
https://gist.github.com/matteocollina/71bd3a8df3bef3c43b52d4205dc3a333

**Comment by mykola-mokhnach** [comment]
Closed as non server related. Please contact SL support.

**Comment by matteocollina** [comment]
@mykola-mokhnach Can you give me more information ? Thank you

**Comment by mykola-mokhnach** [comment]
WDYM?

https://saucelabs.com/support
