### ISSUE TITLE
driver.contexts() results in ECONNREFUSED error

### ISSUE THREAD

**Issue by markring** [appium/appium#10530]
## The problem

When attempting to switch to web context I receive the following error: ```Error: connect ECONNREFUSED ::1:27753 ```. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Desktop OS/version used to run Appium: macOS High Sierra 10.13.4
* Node.js version (unless using Appium.app|exe): 8.9.4
* Mobile platform/version under test: 11.3
* Real device or emulator/simulator: emulator 'iPad Pro (9.7-inch)'
* Appium CLI or Appium.app|exe: CLI

## Details

[debug] [MJSONWP] Calling AppiumDriver.getContexts() with args: ["b40e3315-2ee3-4df0-804f-aa412a97aeaf"]
[debug] [XCUITest] Executing command 'getContexts'
[debug] [iOS] Getting list of available contexts
[debug] [iOS] Retrieving contexts and views
[debug] [iOS] Selecting by url: false
[debug] [RemoteDebugger] useNewSafari --> false
[MJSONWP] Encountered internal error running command: Error: connect ECONNREFUSED ::1:27753
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
[HTTP] <-- GET /wd/hub/session/b40e3315-2ee3-4df0-804f-aa412a97aeaf/contexts 500 26 ms - 201

## Link to Appium logs
[APPIUM LOGS](https://gist.github.com/markring/fab9c36e95d5ee30dc9453f286011cb1)  

## Code To Reproduce Issue [ Good To Have ]
```javascript

describe('test one', function(){

    let getDriver   = require('../config/setup').getDriver
    let Index = require('../screens/index.screen')
   let chai = require('chai'); 
   const expect = chai.expect; 

    let driver = getDriver(); 
    let index = new Index(driver); 

    before( async function(){
        return await driver.contexts().then(async function(contexts){
            return driver.context(contexts[1])
        });
    })
    it('should arrive at home screen', async function(){
        let url = await driver.url() 
        let screen = await index.getScreen(url)
        return expect(screen).to.equal('index.html')
    })
})
```

**Comment by markring** [comment]
Going from X-Code version 9.3 to 9.2 and issue is resolved.

**Comment by mykola-mokhnach** [comment]
Switching to web context on Xcode 9.3 is only supported by appium@beta
Closed as duplicate.
