### ISSUE TITLE
getPageSource is not working for Android 8.0 and 8.1

### ISSUE THREAD

**Issue by pritamkarmakar** [appium/appium#10532]
## The problem

driver.getPageSource() is not returning the page source and Appium is stuck in that call and never returns anything.

## Environment

* Appium version (or git revision) that exhibits the issue: 5.0.4 (Appium java client)
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS High Sierra 10.13.3
* Node.js version (unless using Appium.app|exe): v8.9.1
* Mobile platform/version under test: Android 8.1
* Real device or emulator/simulator: applicable for both
* Appium CLI or Appium.app|exe: Appium java client

## Details

getPageSource method is not returning the page source sometime. 

## Link to Appium logs

https://gist.github.com/pritamkarmakar/6e773e3e75846e9259703f29e19807ad

## Code To Reproduce Issue [ Good To Have ]

Use Appium Java client and in any sample project call driver.getPageSource().

**Comment by mykola-mokhnach** [comment]
Switch to uiautomator2

**Comment by bakiko** [comment]
Hi. I have try call driver.getPagesource() in my sample project and I have not problem.

It's my environment :
- Appium version: 1.7.2
- Desktop version used to run Apium: Ubuntu 16.04 LTS 
- Appium java client version: 5.0.4
- Node.js version: v6.9.2
- Mobile platform/version under test: Android 8.0.0
- Real device: Honor view 10

It's my log:
`[HTTP] --> GET /wd/hub/session/3b5e239d-25fd-4915-be27-9e811b7353df/source {}
[debug] [MJSONWP] Calling AppiumDriver.getPageSource() with args: ["3b5e239d-25fd-4915-be27-9e811b7353df"]
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"source","params":{}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"source","params":{}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: source
[debug] [AndroidBootstrap] [UIAUTO STDOUT] [APPIUM-UIAUTO] [debug] Returning result: {"status":0,"value":"<?xml version=\"1.0\" encoding=\"UTF-8\"?><hierarchy rotation=\"0\"><android.widget.FrameLayout index=\"0\" text=\"\" class=\"android.widget.FrameLayout\" package=\"com.example.android.notepad\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" bounds=\"[0,0][1080,2040]\" resource-id=\"\" instance=\"0\"><android.widget.LinearLayout index=\"0\" text=\"\" class=\"android.widget.LinearLayout\" package=\"com.example.android.notepad\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" bounds=\"[0,0][1080,2040]\" resource-id=\"\" instance=\"0\">...
[HTTP] <-- GET /wd/hub/session/3b5e239d-25fd-4915-be27-9e811b7353df/source 200 226 ms - 10279 `

**Comment by mykola-mokhnach** [comment]
Closed as inactive

**Comment by ruberzen** [comment]
This is happening to me. Should I open a new issue or re-open this one?

**Comment by imurchie** [comment]
Open a new issue with all the pertinent information asked for. What seems like the same issue is often really a different issue, and also code changes make line references in logs obsolete.
