### ISSUE TITLE
TouchActions not working, getting org.openqa.selenium.WebDriverException:  Method had not yet been implemented

### ISSUE THREAD

**Issue by riticar** [appium/appium#10539]
## The problem

I am trying to click on image in the Camera Folder with TouchActions. 
org.openqa.selenium.WebDriverException: Method has not yet been implemented 

## Environment
Appium desktop version 1.5.0 (server 1.7.2)
Appium is being ran on Windows 10
Android version : 7.1.1 API 25
Device: Android emulator
Browser: Chrome

## Details

I am trying to click on the image taken by the Camera of the emulator.
I need to upload the image in the web-page I am testing. 
Please see the image below:
https://i.stack.imgur.com/44WZE.png

## Link to Appium logs

[HTTP] --> POST /wd/hub/session/68a0d2f3-7f59-4144-9b28-e318fc45c8e3/touch/perform {"actions":[{"action":"press","options":{"x":750,"y":420}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"x":993,"y":420}},{"action":"release","options":{}}]}
[MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":750,"y":420}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"x":993,"y":420}},{"action":"release","options":{}}],"68a0d2f3-7f59-4144-9b28-e318fc45c8e3"]
[HTTP] <-- POST /wd/hub/session/68a0d2f3-7f59-4144-9b28-e318fc45c8e3/touch/perform 501 13 ms - 122 

## Code To Reproduce Issue [ Good To Have ]

TouchAction a=new TouchAction((PerformsTouchActions) driver);
Duration d=Duration.ofMillis(1000);
a.press(750,420).waitAction(d).moveTo(993,420).release().perform();

**Comment by mykola-mokhnach** [comment]
You can only use this endpoint when you are in native context. It is not available inside web context.
