### ISSUE TITLE
Cannot run Appium tests on real iOS device

### ISSUE THREAD

**Issue by Testalya** [appium/appium#10534]
## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2 
* Desktop OS/version used to run Appium: MacOS 10.13.3 
* Node.js version (unless using Appium.app|exe): v9.11.1
* Mobile platform/version under test: iOS 11.2.6
* Real device or emulator/simulator: real device iPad (5th generation)
* Appium CLI or Appium.app|exe: both (Appium CLI - 1.7.2 and Appium.app - 1.5.0)

## Errors

[Xcode] 2018-04-13 12:22:51.036 xcodebuild[816:9020] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/username/Library/Developer/Xcode/DerivedData/WebDriverAgent-dxmlavdbqolbkwgarfmzxdqlzubi/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fe5faf95160 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode] 
[Xcode] 2018-04-13 12:22:51.037 xcodebuild[816:9020] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted, NSUnderlyingError=0x7fe5f7ed7480 {Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/username/Library/Developer/Xcode/DerivedData/WebDriverAgent-dxmlavdbqolbkwgarfmzxdqlzubi/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fe5faf95160 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}}}
[Xcode] 
[Xcode] 
[Xcode] Testing failed:
[Xcode] 
[Xcode] 	No signing certificate "iOS Development" found:  No "iOS Development" signing certificate matching team ID "EASZUBR6NA” with a private key was found.
[Xcode] 	Early unexpected exit, operation never finished bootstrapping - no restart will be attempted
[Xcode] ** TEST EXECUTE FAILED **

## Link to Appium logs
https://gist.github.com/Testalya/a3e46a786e0ec801030ff0f03c99c289

Is it possible just to run Appium tests using just .ipa or .app file without real project installed in xCode on the current machine (without all provisioning profiles and certificates)?

**Comment by mykola-mokhnach** [comment]
> [Xcode] 	No signing certificate "iOS Development" found:  No "iOS Development" signing certificate matching team ID "EASZUBR6NA” with a private key was found.
> [Xcode] 	Early unexpected exit, operation never finished bootstrapping - no restart will be attempted

You should fix codesigning. Closed as duplicate
