### ISSUE TITLE
switch_to.context not work on android for Hybird app with appium 1.7.2+python3.6+windows10

### ISSUE THREAD

**Issue by SirCYong** [appium/appium#10533]
## The problem
 'switch_to.context'  
error:
Message: An unknown server-side error occurred while processing the command. Original error: Failed to start Chromedriver session: A new session could not be created. (Original error: session not created exception: please close 'com.zld.zld_face_rec_app' and try again
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.16299 x86_64))

## Environment
* mobile chromedriver :2.33
* mobile chrome version: 62
* python 3.6
* selenium 3.11
* Appium 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): yes
* Desktop OS/version used to run Appium: windows 10
* Node.js : 8.11
* Mobile  : android 7
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:
![image](https://user-images.githubusercontent.com/22674868/38712972-699eda02-3f01-11e8-8d76-6d098052df50.png)

## Details

说汉语能描述清晰，有点尴尬
![image](https://user-images.githubusercontent.com/22674868/38720813-3a17f7b8-3f2a-11e8-80fc-4f2a58fb21a4.png)

## Link to Appium logs
click [log.log](https://github.com/appium/appium/files/1906118/log.log)

## Code To Reproduce Issue [ Good To Have ]

import unittest
from configparser import ConfigParser
from time import sleep
from appium import webdriver as android_driver
from Page.android.android_login import android_login, android_logout, android_employee_registration
from Page.android.get_udid import get_android_udid, get_android_version
from Page.android.handle_permissions_popovers import handle_permissions_popovers, agree_with_permissions
from Page.android.start_appium import start_android_appium
from Page.android.stop_appium import stop_android_appium
from Page.random_data import get_people_name, get_mobile
from run_path import file_path, setting_path

class AndroidLogin(unittest.TestCase):
    def setUp(self):
        conf = ConfigParser()
        self.file_path = file_path('1')
        conf.read(setting_path())
        self.username = conf.get('teamLeader', 'Zhenglinlin')
        self.password = conf.get('operation', 'password')
        self.username1 = conf.get('management', 'yangyinghua')
        self.people = get_people_name()
        self.mobile = get_mobile()
        device_name = get_android_udid()
        stop_android_appium()
        sleep(2)
        start_android_appium(device_name)
        desired_caps = {
            'platformName': 'Android',
            'deviceName': device_name,
            'platformVersion': get_android_version(),
            'appPackage': conf.get('android', 'appPackage'),
            'appActivity': conf.get('android', 'appActivity'),
            'chromeOptions': {
                'androidProcess': 'com.zld.zld_face_rec_app'
            },
            'showChromedriverLog': True,
            'recreateChromeDriverSessions': True,
            'automationName':  'Uiautomator2'
        }
        self.driver = android_driver.Remote('http://127.0.0.1:4723/wd/hub', desired_caps)
        sleep(3)

    def test_02_android_register(self):
        android_employee_registration(self.driver, '杭州富众', self.people, self.mobile)

    def tearDown(self):
        self.driver.quit()
#new_file
def android_employee_registration(driver, company_name, people, mobile):
    get_element(driver, ('id', 'com.zld.zld_face_rec_app:id/tv_register')).click()
    webview_employee_register(driver, company_name, people, mobile)

def webview_employee_register(driver, company_name, people, mobile, code='11111', password='123456'):
    # 获取当前 句柄
    print(driver.current_context)
    # 获取 所有句柄
    sleep(3)
    contexts = driver.contexts
    print(contexts)

    print(contexts[-1])
    driver.switch_to.context(contexts[-1])
    print(driver.current_context)

**Comment by SirCYong** [comment]
I want to know the reason. Please

**Comment by SirCYong** [comment]
@imurchie Please help me.

**Comment by lijiaxin2000** [comment]
I think this problem related to Windows, i use mac doesn't have this problem!

**Comment by mykola-mokhnach** [comment]
Try to [update](https://github.com/appium/appium/blob/f7264d848ebcaaba1b7449ee63324992eb5907a4/docs/en/writing-running-appium/web/chromedriver.md) the chromedriver.

**Comment by SirCYong** [comment]
@mykola-mokhnach I have tried 2.20--2.37, but all the version didn't work

**Comment by mykola-mokhnach** [comment]
Are you able to connect to the webview manually via chrome debugger?

**Comment by SirCYong** [comment]
![image](https://user-images.githubusercontent.com/22674868/38724218-1e2e2f2a-3f36-11e8-906d-42101bb234d8.png)
@mykola-mokhnach

**Comment by SirCYong** [comment]
@mykola-mokhnach What informations do I need to provide?

**Comment by liviudanu-ellation** [comment]
@SirCYong, I had a similar issue, I resolved it by changing the port chromedriver runs on. You can try start appium server with different CLI flags for appium port and chromedriver port.
Take a look here https://appium.io/docs/en/writing-running-appium/server-args/

**Comment by SirCYong** [comment]
@liviudanu-ellation Thank you for your reply，I tried to update the port (9558) ,but the didn't work

**Comment by SirCYong** [comment]
@liviudanu-ellation 
![image](https://user-images.githubusercontent.com/22674868/38807666-eb352d7c-41af-11e8-9b06-43e59f5063c6.png)

**Comment by liviudanu-ellation** [comment]
@SirCYong, Can you update the chrome version on the device and use the latest chromedriver version?

**Comment by SirCYong** [comment]
Hi @liviudanu-ellation  I tried to change android_system_webview(64.0.3282.137),but the prompt (Driver info: chromedriver=2.33.506120 ).......
 Why I'm still wrong about chrome2.33 after I changed my chromedriver(64)?
4/5000  
I don't understand...

**Comment by liviudanu-ellation** [comment]
@SirCYong , as I understand, you are unable to change chromedriver version. Am I right?

**Comment by SirCYong** [comment]
@liviudanu-ellation I use it https://chromedriver.storage.googleapis.com/index.html?path=2.37/。
Isn't that the change?

**Comment by SirCYong** [comment]
If not, then I won't change it.

**Comment by liviudanu-ellation** [comment]
Your logs say that the version is still 2.33, You can update it manually, by downloading it. the go to ~/path/to/appium/node_modules/appium-chromedriver/chromedriver/windows/ , and replace the chromedriver file with the one you downloaded

**Comment by SirCYong** [comment]
Let me change a couple of things：
1、android_system_webview  62--64
2、chromedriver  2.33 -- 2.37

**Comment by SirCYong** [comment]
path: C:\Users\CY\node_modules\appium-chromedriver\chromedriver\win
![image](https://user-images.githubusercontent.com/22674868/38976648-713b92b8-43e4-11e8-8ba8-c913b197d7e2.png)
![image](https://user-images.githubusercontent.com/22674868/38976663-7e17231c-43e4-11e8-909a-9f08bc382968.png)
 so  Why I'm still wrong about chrome2.33 after I changed my chromedriver(64)?

**Comment by liviudanu-ellation** [comment]
Are you able to connect to the webview manually via chrome debugger?
--
open chrome://inspect/ in your browser and see if you can connect to webview

**Comment by SirCYong** [comment]
Hi @liviudanu-ellation Yes I can 
![image](https://user-images.githubusercontent.com/22674868/38978385-d576a254-43e9-11e8-9c29-72167a36ab57.png)

**Comment by liviudanu-ellation** [comment]
@SirCYong , and are you able to inspect it? It works ok?

**Comment by SirCYong** [comment]
@liviudanu-ellation  Work is ok 
![image](https://user-images.githubusercontent.com/22674868/38979006-99d423c8-43eb-11e8-83c5-69ec63f70f49.png)

**Comment by liviudanu-ellation** [comment]
@SirCYong , then I have no idea what is going wrong, here are some other things you can try:
- reinstall appium
- install latest appium beta version
- try another device
- try another app, it may be a problem with your .apk
- try on another computer
- you can send me your apk to see if it works for me.

If nothing works, you might consider to contact chrome support service or report a chromedriver bug.

**Comment by liviudanu-ellation** [comment]
@SirCYong , I just tried you .apk on my machine, and everything worked fine, so must probably it's a problem with your environment set up

**Comment by SirCYong** [comment]
@liviudanu-ellation  thanks.
I know that apk is ok, but I don't know why I changed the chrome64, but I still have the wrong report about chrome23?
I'm trying to find out why, and I'll tell you.

**Comment by SirCYong** [comment]
@liviudanu-ellation 兄弟，我升级到了1.8.0，就可以了，感谢你非常热情的解答，谢谢
