### ISSUE TITLE
Unknown route warning for `wda/screen` and `window/size` numerous times during automated test

### ISSUE THREAD

**Issue by mikesalvia** [appium/appium#10531]
## The problem

I am seeing the following in my Appium logs. 
```
[XCUITest] Proxying to WDA with an unknown route: GET:/
[XCUITest] Merging WDA caps over Appium caps for session detail response
[XCUITest] Proxying to WDA with an unknown route: GET:/wda/screen
[XCUITest] Proxying to WDA with an unknown route: GET:/wda/screen
[XCUITest] Proxying to WDA with an unknown route: GET:/window/size
```

Per some information found on the internet, I looked into `FBCustomCommands.m` in the WebDriverAgentLib project and made sure that the following was present...

`[[FBRoute GET:@"/wda/screen"] respondWithTarget:self action:@selector(handleGetScreen:)],`

in the `routes` NSArray... As well as the following is present...

```
+ (id<FBResponsePayload>)handleGetScreen:(FBRouteRequest *)request
{
  FBSession *session = request.session;
  CGSize statusBarSize = [FBScreen statusBarSizeForApplication:session.activeApplication];
  return FBResponseWithObject(
  @{
    @"statusBarSize": @{@"width": @(statusBarSize.width),
                        @"height": @(statusBarSize.height),
                        },
    @"scale": @([FBScreen scale]),
    });
}
```

I did notice the absence of `window/size` in this file but it is present in `FBElementCommands`

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0-beta4
* Last Appium version that did not exhibit the issue (if applicable): ? (iOS 11.3 and Xcode 9 was not fully supported in 1.7.2)
* Desktop OS/version used to run Appium: macOS High Sierra
* Node.js version (unless using Appium.app|exe): 9.10.1
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

It doesn't appear that it hinders our testing at all but it does create chatter in logs and could point to an issue that I am not seeing.

## Link to Appium logs

Will provide logs at request as this issue may require being opened in WebDriverAgent project on GitHub.

**Comment by imurchie** [comment]
It has to do with the command timeout capability. This log line is meant to be informative so we can add those routes. I'm currently working through them.

**Comment by mikesalvia** [comment]
Thank you so much! This can be ignored then? :-) WOOOOOOOOOO!

**Comment by imurchie** [comment]
Totally ignore!

And they ought to be gone soon.
