### ISSUE TITLE
Failed to install WebDriverAgentRunner-Runner.app - iOS 11.2.6 with xCode 9.2

### ISSUE THREAD

**Issue by raz197** [appium/appium#10537]
Getting a Failed to install WebDriverAgentRunner-Runner.app error when on iPhone 6s running iOS 11.2.6. It happens when trying to launch the appium server from command line, works fine for appium started via appium.app.  

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: macOS 10.13.4
* Node.js version (unless using Appium.app|exe): 7.4.0
* Mobile platform/version under test: iOS 11.2.6
* Real device or emulator/simulator: iPhone 6s
* Appium CLI or Appium.app|exe: cli

Have set the xcodeOrgId, xcodeSigningId and updatedWDABundleId and in xCode 9.2 WebDriverAgentRunner is configured as per instructions here 

https://github.com/imurchie/appium-xcuitest-driver/blob/isaac-rs/docs/real-device-config.md#basic-manual-configuration
       
## Link to Appium logs
appium log - https://gist.github.com/raz197/269e274702ba89c2036504a2f7893abd
xcodebuild log - https://gist.github.com/raz197/3f6ab92e266f18eec14b567e7a934ed9

**Comment by mykola-mokhnach** [comment]
> [Xcode] 2018-04-13 21:57:20.616 xcodebuild[4541:45788]  iPhoneConnect: Failed to install /Users/qaepro/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app - error Error Domain=com.apple.dtdevicekit Code=-402653179 "App installation failed" UserInfo={NSLocalizedDescription=App installation failed, com.apple.dtdevicekit.stacktrace=(

Something is broken with your device/xcode setup. Try to reboot the device.

**Comment by raz197** [comment]
I have restarted a few times, uninstalled and re-installed appium, xcuitest drivers without any luck.

Same device, same machine/xcode works when launched via appium.app

here is the log for that
https://gist.github.com/raz197/ba0d99a1d53de28ac0e152d44a0c72a4

**Comment by tsibiski** [comment]
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.


What is the specific 65 error you are getting. That is a codesign error, which will normally cause the WebDriverAgent to fail to launch, and instantly be removed from device.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
