### ISSUE TITLE
Appium cannot be found by maven testng project when starting the appium server using shell script on jenkins

### ISSUE THREAD

**Issue by yeugeneu** [appium/appium#10538]
## The problem

So I am trying to create a maven project jenkins task to run the following build:

1. Fetch the source code project from bitbucket
2. Start Appium server using Execute shell in the Pre step with following script
```
#!/bin/sh
echo Kill adb:
killall adb &
wait

echo Start Server:
adb start-server &
wait

echo Kill Node:
killall node &
wait

appium &
sleep 2m
```
3. build and execute the pom.xml file using maven script ('Automation' is the test suite name)
```
clean test -PAutomation  
```
4. The Appium server starts correctly however the test cannot find it and threw the following error

> org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.

## Environment

* Appium version **1.7.2**
* Desktop OS/version used to run Appium: **MacOS High Sierra**
* Node.js version (unless using Appium.app|exe): **v8.9.4**
* Mobile platform/version under test: **Simulator iOS 11.3 and emulator Android 8.0**

## Details

If I started appium server manually using terminal script and executed the jenkins build without the pre-build script to start appium server, the test will execute correctly. So the problem probably lies at where the appium server address/port cannot be found by the maven testng project when appium started using jenkins. 

I have also tried modifying the start driver url to either http://0.0.0.0:4723/wd/hub or http://127.0.0.1:4723/wd/hub without any lucks.

## Link to Appium logs

[Log](https://gist.github.com/yeugeneu/f6c02285cf21fcb7393b4c6af562a698)

## Code To Reproduce Issue 

My testng code is in JAVA and the following are the start iOS driver method. 

I have also tried modifying the start driver url to either http://0.0.0.0:4723/wd/hub or http://127.0.0.1:4723/wd/hub without any lucks.

```
DesiredCapabilities capabilities = new DesiredCapabilities();

try {
	capabilities.setCapability("platformName", "iOS");
	capabilities.setCapability("platformVersion", "11.3");
	capabilities.setCapability("deviceName", "iPhone 8");
	capabilities.setCapability("app", _app location_);
	capabilities.setCapability("automationName", "XCUITest");
	capabilities.setCapability("fullReset", "true");
}
catch (Exception e)
{
	System.out.println("Setting desired capabilities error. " + e.toString());
}

try
{
        driver= new IOSDriver<WebElement>(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
	driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
}
catch (SessionNotCreatedException e)
{
	System.out.println("Error creating session." + e.toString());
}
catch (MalformedURLException e) 
{
	e.printStackTrace();
}
```

**Comment by mykola-mokhnach** [comment]
Is appium server listening on the port 4723 when your code tries to reach it? what is the `netstat` output for the given port?

**Comment by yeugeneu** [comment]
@mykola-mokhnach 
Yes according to the log, Appium started on 0.0.0.0:4723.

```
11:25:53  [Appium] Welcome to Appium v1.7.2
11:25:53  [Appium] Appium REST http interface listener started on 0.0.0.0:4723
11:26:03  Process leaked file descriptors. See https://jenkins.io/redirect/troubleshooting/process-leaked-file-descriptors for more information

```

I tired look at -lsof info when the appium server starts on jenkins, and  port 4723 is showing process named 

> Node *:4723

**Comment by mykola-mokhnach** [comment]
Are you waiting for it in your client script? Usually the startup procedure takes several seconds

**Comment by yeugeneu** [comment]
@mykola-mokhnach 
I did insert a sleep script right after the appium start command.

```
appium &
sleep 2m
```

I use 'sleep' instead because If I use 'wait', the maven build will not be executed.
Also according to the log, the appium did start before TestNG executed.

I believe the following log indicates the appium server has started correctly and listening on 0.0.0.0:4723

```
11:25:53  [Appium] Welcome to Appium v1.7.2
11:25:53  [Appium] Appium REST http interface listener started on 0.0.0.0:4723
```

And then TestNG started after around twenty seconds according to the following log.

```
11:26:11  [INFO] -------------------------------------------------------
11:26:11  [INFO]  T E S T S
11:26:11  [INFO] -------------------------------------------------------
11:26:11  [INFO] Running TestSuite
11:26:11  ... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
```

Still not sure why my automation couldn't find the appium server.

**Comment by mykola-mokhnach** [comment]
you should not rely on sleep. Add port availablity checking into your client code. I check server presence with

```
import org.openqa.selenium.net.UrlChecker;

private boolean waitUntilIsRunning(Duration timeout) throws Exception {
        final URL status = new URL(SERVER_URL + "/sessions");
        try {
            new UrlChecker().waitUntilAvailable(timeout.asMillis(), TimeUnit.MILLISECONDS, status);
            return true;
        } catch (UrlChecker.TimeoutException e) {
            return false;
        }
    }
```

**Comment by yeugeneu** [comment]
@mykola-mokhnach 
Thank you so much for the help. 

Now that I've added the port availability check as following:

 ```
   private static final String SERVER_URL = String.format("http://127.0.0.1:%d/wd/hub", 4723);
    public static boolean waitUntilIsRunning(Duration timeout) throws Exception {
        System.out.println("Validating whether the url is up and running.");
        final URL status = new URL(SERVER_URL + "/sessions");
        try {
            new UrlChecker().waitUntilAvailable(timeout.getMinutes(), TimeUnit.MINUTES, status);
            System.out.println("Url is up and running!");
            return true;
        } catch (UrlChecker.TimeoutException e) {
            System.out.println("Url is not running > <");
            return false;
        }
    }
```

The console log indicates that the server is indeed up and running. However, when executing the maven TestNG test, it shows the same error message of "Could not start a new session"

> 12:25:08 FAILED CONFIGURATION: @BeforeClass startUp
> 12:25:08 org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
> 12:25:08 Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
> 12:25:08 System info: host: 'Eugenes-iMac.localdomain', ip: '192.168.1.222', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.4', java.version: '1.8.0_152'

**Comment by mykola-mokhnach** [comment]
2.53 is outdated. update selenium hub/api to 3.7

**Comment by mykola-mokhnach** [comment]
I've pointed the exact version number above. If you want to use the newer one then Appium server should also be at beta version


Closed as not an issue

**Comment by kamaleshrnp** [comment]
Experience the same issue, with updated Appium Version 1.8.1

**Comment by kamaleshrnp** [comment]
@mykola-mokhnach I followed the same steps as @yeugeneu ; but with the updated Appium Version . Can someone help me ?

**Comment by yeugeneu** [comment]
> @mykola-mokhnach I followed the same steps as @yeugeneu ; but with the updated Appium Version . Can someone help me ?

FYI I have my jenkins task's pre stepset to execute shell for only the following:
```
#!/bin/sh
echo Kill Node:
killall node &
wait
```

And then have the following java code to start appium driver

```
try
{
	builder = new AppiumServiceBuilder();
	builder.withAppiumJS(new File(APPIUM_JS));
	builder.withIPAddress(serverURL);
	builder.usingPort(Integer.parseInt(APPIUM_PORT));
	builder.withArgument(GeneralServerFlag.SESSION_OVERRIDE);
	// builder.withArgument(GeneralServerFlag.LOG_LEVEL,"error");
			
	// Start the server with the builder
	appiumService = AppiumDriverLocalService.buildService(builder);
	appiumService.start();
	log.success("Appium driver starts successfully.");
}
catch (Exception e)
{
	Logger log = Logger.getInstance();
	log.fail("Error on Appium server start! : " + e.getMessage());
}
```

With following to check whether the server is running


```
private boolean waitUntilIsRunning(Duration timeout)
{
	System.out.println("Validating whether the url is up and running...");
	log.debug("Validating whether the url is up and running...");

	final URL status;

	try
	{
		status = new URL(SERVER_URL + "/sessions");

		new UrlChecker().waitUntilAvailable(timeout.getMinutes(), TimeUnit.MINUTES, status);
		log.success("Url is up and running.");

		return true;
	} catch (MalformedURLException e)
	{
		System.out.println("Error in the URL provided. " + e.toString());
		instance.terminateAll("Could not start a new session with the URL provided. " + e.toString());
		e.printStackTrace();

		return false;
	} catch (UrlChecker.TimeoutException e)
	{
		System.out.println(String.format("Server at the URL (%s) is not running. %s.", SERVER_URL, e.toString()));
		e.printStackTrace();
		instance.terminateAll(String.format("Server at the URL (%s) is not running. %s.", SERVER_URL, e.toString()));

		return false;
	}
}
```
