### ISSUE TITLE
Appium is not getting installed on windows 10

### ISSUE THREAD

**Issue by Yasir25** [appium/appium#10543]
## The problem

Whenever I try to install appium on my windows 10 machine, it comes up with an error message that "installation has failed...can not extract installer".. please help ASAP
![appium](https://user-images.githubusercontent.com/38405559/38781594-223c0efe-4105-11e8-8d8f-92d1f106285f.png)

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by dpgraham** [comment]
Can you try installing disabling antivirus during install? (Similar issue to https://github.com/atom/atom/issues/7915)

**Comment by mykola-mokhnach** [comment]
Are you sure you're installing the correct package? Your architecture must be x86_64

**Comment by mykola-mokhnach** [comment]
Closed as non server-related issue. Please report to https://github.com/appium/appium-desktop/issues if this still does not work
