### ISSUE TITLE
Appium does not build when including it as a github node module dependency

### ISSUE THREAD

**Issue by cstack** [appium/appium#10542]
## The problem

Steps to reproduce.

- Add this line to my project's package.json:
```
"appium": "git+https://github.com/appium/appium.git#62700d3b1dc0edd985502cc1279747a782f3ee74",
```
- npm install

Expected result:
- appium installs and builds in my node_modules directory

Actual result:
```
npm ERR! Darwin 17.5.0
npm ERR! argv "/Users/cstack/.nvm/versions/node/v6.10.2/bin/node" "/Users/cstack/.nvm/versions/node/v6.10.2/bin/npm" "install"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! path /Users/cstack/Development/payroll-mobile/node_modules/appium/build/lib/main.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/cstack/Development/payroll-mobile/node_modules/appium/build/lib/main.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/cstack/Development/payroll-mobile/node_modules/appium/build/lib/main.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
```

The install *does* work if I instead include the line:
```
"appium": "^1.7.1",
```

## Environment

* Appium version (or git revision) that exhibits the issue: 62700d3b1dc0edd985502cc1279747a782f3ee74
* Desktop OS/version used to run Appium: macOS High Sierra 10.13.4
* Node.js version (unless using Appium.app|exe): v6.10.2

## Link to Appium logs

npm-debug.log: https://gist.github.com/cstack/fb3a1f18b50002cc8770aa7f073afc06

**Comment by dpgraham** [comment]
Yeah that's not going to work. The build folder contains the code that gets run and is ignored by git but not by npm. 

You'll either need to run 'gulp transpile' from inside the Appium folder to build that folder or you'll need to import Appium as npm module 'npm install --save-dev appium'
