### ISSUE TITLE
Ho to delete an administrator application (Android)

### ISSUE THREAD

**Issue by nicodeur** [appium/appium#10544]
## The problem

Hello,

I use appium on my java application, and I can't delete an administrator application with Appium.

I use this maven settings : 
```
        <dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>${appium.version}</version>
        </dependency>
```

To make it with adb, I have to use 
```
adb shell dpm set-device-owner <package_name>
adb uninstall <package_name>
```

Is it exists an equivalent on appium ?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: latest docker image `appium/appium`
* Node.js version (unless using Appium.app|exe):  latest docker image `appium/appium`
* Mobile platform/version under test: Android 6.0
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:  latest docker image `appium/appium`

**Comment by mykola-mokhnach** [comment]
you can use https://github.com/appium/appium/blob/fd0a0dc234998cd2b3c79a8e66b2da6e77506273/docs/en/writing-running-appium/android/android-shell.md to execute custom shell commands. Java client has `uninstallApp` method, which can uninstall third party app (at least the recent BETA of it)

Please use Appium forum to ask questions.

**Comment by nicodeur** [comment]
Thanks for your quickly reply !

Ok for the Appium Forum.
