### ISSUE TITLE
incapable to start Safari on real iOS device "[XCUITest] Failed to check out repository into "

### ISSUE THREAD

**Issue by maluyvova** [appium/appium#10540]
## The problem
Problem with start Appium on real iOS device
[XCUITest] Fetching dependencies
[XCUITest] *** Checking out RoutingHTTPServer at "v1.0.1"
[XCUITest] Failed to check out repository into /private/var/folders/cs/w7yrhm211yj8yygl1hvn8x1m0000gn/T/AppTranslocation/2B33853D-2A94-4CC8-B4F8-DC7DB48A5767/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer: Could not create working directory (Error Domain=NSCocoaErrorDomain Code=642 "You can’t save the file “RoutingHTTPServer” because the volume is read only." UserInfo={NSFilePath=/private/var/folders/cs/w7yrhm211yj8yygl1hvn8x1m0000gn/T/AppTranslocation/2B33853D-2A94-4CC8-B4F8-DC7DB48A5767/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer, NSUnderlyingError=0x7fbc1256fd40 {Error Domain=NSPOSIXErrorDomain Code=30 "Read-only file system"}})

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.7.2
* Desktop OS/version used to run Appium:macOS High Sierra Version 10.13.2
* Mobile platform/version under test:iOS
* Real device or emulator/simulator:iPhoneX 11.2.6
*Xcode 9.2

## Details
All setups installed from this tutorial 
https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md
	static AppiumDriver driver;
	static DesiredCapabilities capabilities = new DesiredCapabilities();
	public static AppiumDriver inits() throws MalformedURLException {
		//capabilities.setCapability("xcodeConfigFile","/Users/vburian/.xcconfig");
		capabilities.setCapability("xcodeOrgId", "3RT6Z533P8");
		capabilities.setCapability("xcodeSigningId","iPhone Developer");
		capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME,"iOS");
		capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME ,"XCUITest");
		capabilities.setCapability(MobileCapabilityType.UDID,"8ac60b225c69602a5c8729a6d83e6f8973199650");
		 capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone X"); 
	     capabilities.setCapability(MobileCapabilityType.BROWSER_NAME,"Safari");
		//capabilities.setCapability("browser", "safari");
		driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"),
				capabilities);
		//driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
		return driver;
	}
	public static void main (String ...clasd) throws MalformedURLException {
		inits().get("http://saucelabs.com/test/guinea-pig");
	}

## Link to Appium logs
https://gist.github.com/maluyvova/0a631efec37823ff9421cffaa4c438e4

**Comment by mykola-mokhnach** [comment]
Appium Desktop should be installed into `/Applications` folder. Closed as not an issue.
