### ISSUE TITLE
Click action not working Android Hybrd(Ionic)

### ISSUE THREAD

**Issue by MrShakes** [appium/appium#10549]
## The problem

The element in the hybrid Ionic App is not being clicked on and neither am I getting any error, I have even tried putting wrong `ids` and still no error. I have posted on Appium discuss with no answer yet.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Desktop OS/version used to run Appium: MacOS HighSierra 10.13.2
* Node.js version (unless using Appium.app|exe): 6.10.2
* Mobile platform/version under test:  Android 6.0 Google Nexus 5X
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: 1.7.2

## Details
Ionic 3.9.2 Apk
Code:
```
const wdio = require('webdriverio');

const opts = {
  port: 4723,
  desiredCapabilities: {
    platformName: "Android",
    platformVersion: "6.0",
    deviceName: "Android Emulator",
    app: '/Users/xx/Desktop/Awork/nxhealthpe/platforms/android/build/outputs/apk/debug/android-debug.apk',
    automationName: "uiautomator2",
    autoWebview: true
  }
};

const client = wdio.remote(opts);

client
  .init()
  .contexts().then(function (contexts) {
        return client.context(contexts[1]);
    })
  .click("signin")
  .click("#signin")
  .end();
```

## Link to Appium logs
https://gist.github.com/MrShakes/1afdf5472a48cd8884fb2b931a6e27fd
## Apk I used
https://drive.google.com/file/d/1QCUzWdzE1XnEnRDg8PGhaIKWleeh0WKv/view?usp=sharing

**Comment by mykola-mokhnach** [comment]
I don't see any click requests from the client in the server log. Perhaps, promises logic is not respected in the client code
