### ISSUE TITLE
[1.7.2][Android] Too slow to locate elements

### ISSUE THREAD

**Issue by chenlujjj** [appium/appium#10548]
## The problem

Hi, I'm trying to use appium to do some automation work on an android app, but it took too long to locate element (20 ~ 30 seconds !), I cannot figure out why.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Ubuntu 16.04
* Node.js version (unless using Appium.app|exe): 8.9.4
* Mobile platform/version under test: Android 7.1.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details
Other Info:
1. use **UiAutomator2** as automation engine.
2. I tried it on another calculator app,(same device, same automationName) , the locating speed is normal

## Link to Appium logs
The log of locating a button is as below, take a look at the timestamp, it took 30 secs
https://gist.github.com/chenlujjj/6f5bc2ac8834c578089a0e729a8d9a28

**Comment by vjmaiky** [comment]
use this type of locators and make elements of objects type and interact with them. for me it's super fast
```
    private String locator = "new UiSelector()";

    public UiSelector resourceId(String value) {
        locator += ".resourceId(\"" + value + "\")";
        return this;
    }

    public UiObject makeUiObject() {
        return new UiObject(locator);
    }
```
example of element:
```
    public UiObject continueBtn() {
        if (continueBtn == null)
            continueBtn = new UiSelector().resourceId("de.telekom.conectivity.inflight.stage:id/button_continue").index(3).makeUiObject();
        return continueBtn;
    }
```

**Comment by chenlujjj** [comment]
We DO have animation, I will disable that and see if the element lookup would be faster. 
Thank you for the advice ! @mykola-mokhnach

**Comment by chenlujjj** [comment]
Maybe the type of locator is not key to the problem, I will try it later and hope it can speed up the process. 
Thank you @vjmaiky
