### ISSUE TITLE
Appium 1.8.0-beta5 --legacy-bundling dependency issue

### ISSUE THREAD

**Issue by clample** [appium/appium#10553]
## The problem

Appium 1.8.0-beta5 does not work when installed with `npm install --legacy-bundling appium@1.8.0-beta5`. This appears to be because of the `appium-xcuitest-driver` dependency on `appium-remote-debugger`.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0-beta5
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2 should work fine
* Desktop OS/version used to run Appium: linux
* Node.js version (unless using Appium.app|exe): v8.9.4
* npm version: 5.6.0
* Mobile platform/version under test: NA
* Real device or emulator/simulator: NA
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

https://gist.github.com/clample/7b6cad7df6968a8d2e3250daa206fee2

## Code To Reproduce Issue [ Good To Have ]

Steps to reproduce with docker:

```
$ docker run -it node:8.9.4 bash
$ npm install --legacy-bundling appium@1.8.0-beta5
$ node /node_modules/appium --version
```

**Comment by imurchie** [comment]
Should be fixed now.
