### ISSUE TITLE
How do i listen for events in a JavaScript Client?

### ISSUE THREAD

**Issue by lddd** [appium/appium#10556]
Hello,

For a Java Client there is
https://github.com/appium/java-client/blob/master/docs/The-event_firing.md

How i am able to do this with a JavaScript Client? 

thanks in advance

**Comment by dpgraham** [comment]
This is for Appium issues. If you have questions about you can go to discuss.appium.io or you can ask the creators of the JS client.

**Comment by lddd** [comment]
Hi there. discuss.appium.io i could not find help on this. Where to reach the creators of the JS client?

**Comment by dpgraham** [comment]
This is the documentation for WebDriver.io: http://webdriver.io/api.html

If it's not found in the docs the feature probably isn't available.

**Comment by lddd** [comment]
Thanks @dpgraham. Could not find what i am looking for. Maybe i am also searching for the wrong things.

Let me ask like this..
Is it possible to realize a Appium "Test" to automatically fetch messages received inside some App?
