### ISSUE TITLE
[1.7.2] [Android] Cannot Interact with NumberPicker widget

### ISSUE THREAD

**Issue by chenlujjj** [appium/appium#10559]
## The problem

I tried to use appium to interact with the NumberPicker in an app to set date and time.
The program didn't throw any error but the interaction didn't work at all. 
## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: Ubuntu 16.04
* Node.js version (unless using Appium.app|exe): 8.9.4
* Mobile platform/version under test: Android 7.1.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Details

use UiAutomator2 ;
use send_keys() method to set time.

## Link to Appium logs
I interacted with two NumberPicker to set the time at 19:30, the appium log: 
https://gist.github.com/chenlujjj/c2c80f24d5f519e8013d85fcbb61e003

I have searched the similar issue, but cannot solve my problem

**Comment by chenlujjj** [comment]
Does anybody have a idea about this problem? I haven't figured it out yet. maybe I should work it around if it is an appium issue/bug ？

**Comment by chenlujjj** [comment]
I used send_keys() method on EditText of NumberPicker, it worked sometimes but really flaky

**Comment by mykola-mokhnach** [comment]
This functionality is controlled by UIA2 framework itself and there is nothing much that can be done from Appium side.
