### ISSUE TITLE
Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65"

### ISSUE THREAD

**Issue by MrShakes** [appium/appium#10550]
## The problem

I'm getting `Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65"` while trying to launch my hybrid Ionic App, I have searched for answers and they all point to testing on real devices while I'm actually testing on a Simulator, nevertheless I tried 
1) `cd` to `/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent` and tried to build the project,  I got `/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Routing/FBWebServer.m:12:9: 'RoutingHTTPServer/RoutingConnection.h' file not found`
2) running `./Scripts/bootstrap.sh` and `./Scripts/build.sh` from WebDriverAgent and both failed with gists:
- https://gist.github.com/MrShakes/334a10585fcca9bbd083c7a94e08ee4c
- https://gist.github.com/MrShakes/d325cdce3eaee8d0700453e6c1d12519

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Desktop OS/version used to run Appium: MacOSHighSierra 10.13.2
* Node.js version (unless using Appium.app|exe): 6.10.2
* Mobile platform/version under test: IOS
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI 1.7.2

## Details

```
const wdio = require('webdriverio');

const opts = {
  port: 4723,
  desiredCapabilities: {
    platformName: "iOS",
    platformVersion: "11.2",
    deviceName: "iPhone Simulator",
    app: '/Users/xx/Desktop/Awork/nxhealthpe/platforms/ios/build/emulator/nxhealthpe.app',
    automationName: "XCUITest",
    autoWebview: true
  }
};

const client = wdio.remote(opts);

client.init();
client
  .contexts().then(function (contexts) { 
        return client.context(contexts[1]); 
    })
  .click("#signin")
```

## Link to Appium logs

https://gist.github.com/MrShakes/b669715ca152b86e59985db81d2018f4

## .app used 

https://drive.google.com/file/d/1xkkbFF90UfssKU51PHspjVqiPpkqDZCv/view?usp=sharing

**Comment by mykola-mokhnach** [comment]
Please read the documentation carefully. You should execute `./Scripts/bootstrap.sh -d`

closed as not an issue.

**Comment by MrShakes** [comment]
Thank you
