### ISSUE TITLE
Element not visible Xcode 9.3 / iOS 11.3

### ISSUE THREAD

**Issue by romainlouvet** [appium/appium#10551]
## The problem

A lot of XCUIElementTypeTextField are unvisible whereas upgrade of xcode (9.2) they were visible

## Environment

Appium 1.8.0-beta5 (same problem with 1.7.4)
Mac OS 10.13.4
Xcode 9.3 
iOS 11.3
Real device: iPhone SE

## Details
XCUIElementTypeCell parent is visible

<img width="1290" alt="capture d ecran 2018-04-17 a 09 45 44" src="https://user-images.githubusercontent.com/4262374/38861510-02c95d36-4233-11e8-82e7-dcc445edbd07.png">

<img width="1364" alt="capture d ecran 2018-04-17 a 09 37 26" src="https://user-images.githubusercontent.com/4262374/38861522-0a2246c4-4233-11e8-9239-3a9cdbc3f76f.png">

**Comment by mykola-mokhnach** [comment]
Visibility detection is a quite complicated topic, which also heavily depends on XCTest internals. If you have some ideas on how the thing could be improved for your particular case then you're welcome to contribute.

https://github.com/appium/WebDriverAgent/blob/585ed2ab58ee0f5b31417100f619dccef54547a5/WebDriverAgentLib/Categories/XCUIElement%2BFBIsVisible.m#L138

Closed as third party issue.

**Comment by romainlouvet** [comment]
:/
