### ISSUE TITLE
Appium Error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by cranzy** [appium/appium#10557]
Hello guys, 

I'm running an Appium Server on a Mac OS and I'm getting the following Error
An unknown server-side error occurred while processing the command. Original error: Problem downloading app from url '''link to apk .apk''': Error: self signed certificate in certificate chain

I've added all the certificates to make the internal website accessible and trusted when accessed via a browser. However, when Appium tries to download it I get the above mentioned error...

## Environment
Appium Desktop: v1.5.0 
Appium server: v1.7.2
MacOS Siera 10.12.6
Android Phone 5.0.2
I'm using the UiAutomator2 as a driver...

Detailed Error:
 selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Problem downloading app from url https://app-link.apk: Error: self signed certificate in certificate chain

**Comment by mykola-mokhnach** [comment]
NodeJS process, which hosts Appium, does not share trusted certificated root with browsers. Try to set the corresponding  environment variable for the server as it is described in https://stackoverflow.com/questions/10888610/ignore-invalid-self-signed-ssl-certificate-in-node-js-with-https-request if you still want to ignore self-signed cert error.

**Comment by cranzy** [comment]
Thank you @mykola-mokhnach !
