### ISSUE TITLE
Scrolling not working due wrong element location

### ISSUE THREAD

**Issue by renanantunes** [appium/appium#10555]
## The problem

I have a list of buttons inside a View, some of these elements are visible on screen when the page loads, the others needs to scroll to be on screen. My problem is I can find the element, but I can’t scroll to it.

## Environment

* Appium version (or git revision) that exhibits the issue: **1.7.2**
* Last Appium version that did not exhibit the issue (if applicable): **same issue with 1.4**
* Desktop OS/version used to run Appium: **Windows 10**
* Node.js version (unless using Appium.app|exe): **8.9.4**
* Mobile platform/version under test: **Android 6.0.1/Android 7.0**
* Real device or emulator/simulator: **Real devices**
* Appium CLI or Appium.app|exe: **CLI**

## Details

I’ve already tried to scroll using MobilyBy.AndroidUIAutomator, but it doesn't. I think it happens because the elements that are off screen have a ‘wrong’ location, all of them shows the same Y coordinate, something like 1092 depends on the device. So, they are not showing the correct location. When I manually scroll, or use swipe to scroll, the elements that were off screen before still with the same location coordinates.

I also tried to use a swipe to scroll, but as the locations aren’t correct It’s impossible to scroll to element and click on correct button.

## Link to Appium logs

https://gist.github.com/renanantunes/168f543be31ad5b75b1bcfa8083110b5

## Code to Reproduce Issue [ Good To Have ]

```
At this moment I’m trying this:
driver.findElement(MobileBy.AndroidUIAutomator(“new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().descriptionContains(”"+TextToFind+"").instance(0))"));

already tried:

driver.findElement(MobileBy.AndroidUIAutomator(“new UiScrollable(new UiSelector().className(“android.view.View”)).scrollIntoView(new UiSelector().descriptionContains(”"+TextToFind+"").instance(0))"));

AND

driver.findElement(MobileBy.AndroidUIAutomator(
“new UiScrollable(new UiSelector().text(“myseats”)).getChildByText(”
+ “new UiSelector().className(“android.widget.Button”), “”+TextToFind+”")"));
```

**Comment by mykola-mokhnach** [comment]
I'd swipe several times with small steps until the destination element is visible, like a real user would do it.

**Comment by renanantunes** [comment]
@mykola-mokhnach thanks for the answer!

I've already tried, but it didn't work. The location (x,y) for the elements that aren't on the screen is the same, on my device I can see the first four button of the list, the others, that I need to scroll to see, have the same location (x:10, y: 1064), this location is visible on screen, but the button is not.
So, even when I swipe, the button location don't change, still the same (x:10, y:1064), even the button isn't there. 
Note: the buttons that are visible on screen when the page loads has a correct location, only those that are below that seems to have this problem. I'm not a front-end developer, but I think it can also be a render 'problem'. it's a hybrid app, and we are using Ionic and Angular.

if needed I can share the page source

**Comment by mykola-mokhnach** [comment]
> it's a hybrid app, and we are using Ionic and Angular.

Perhaps, this is the reason. You don't need to be in the native context.

**Comment by renanantunes** [comment]
So, there is any tip or workaround to access these buttons that aren't on screen?

**Comment by mykola-mokhnach** [comment]
Switch to webview?

**Comment by renanantunes** [comment]
@mykola-mokhnach thank you!
I changed the context to webview and it worked!
you can close this issue.
Thank you again
