### ISSUE TITLE
Unable to maintain two android driver sessions for working on two apps

### ISSUE THREAD

**Issue by vallj** [appium/appium#10560]
## The problem

We have a need to perform actions on two different apps during our testing using Appium. I'm starting a different driver session for each app. But when the second driver session is started, the first driver session is getting closed. Hence I cannot access objects using first driver anymore. Is it possible to have both the driver sessions active so that I can identify objects on both the apps?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 7
* Node.js version (unless using Appium.app|exe): 9.7.1
* Mobile platform/version under test: Android OS 8.1.0
* Real device or emulator/simulator: Real device Nexus 6P
* Appium CLI or Appium.app|exe: CLI

## Details
In some of our tests, we have manual switching of applications on the phone (due to the nature of our test scenarios).  So, even though the apps are launched via appium for the first time, there may be instances later on in the script where app may have been launched manually. So, I need to have both the driver sessions active in order to be able to identify the elements.

## Link to Appium logs

https://gist.github.com/vallj/a556eb80570b871acbedfbbed6249927

## Code To Reproduce Issue [ Good To Have ]

    public static AppiumDriver<AppiumWebElement> patientAppDriver = null;
    public static AppiumDriver<AppiumWebElement> settingsAppDriver = null;
    public static AppiumDriver<AppiumWebElement> appDriver = null;
    public static Task _startAppiumServer;

string appiumServerLogFileName = "AppiumLog_1.txt";
_startAppiumServer = new Task(() => 
         StartAndroidAppiumServerAndCreateLog(appiumServerLogFileName));
_startAppiumServer.Start();
 Thread.Sleep(10000);

                DesiredCapabilities capabilities = new DesiredCapabilities();
                capabilities.SetCapability("automationName", "Appium");
                capabilities.SetCapability("platformName", "Android");
                capabilities.SetCapability("noReset", "true");
                capabilities.SetCapability("platformVersion", "8.1.0");
                capabilities.SetCapability("deviceName", "Nexus");
                capabilities.SetCapability("appPackage", "com.sjm.crmd.patientApp_Android_USA");
                capabilities.SetCapability("appActivity", "com.sjm.patientApp.android.features.common.base.views.SplashActivity");
                capabilities.SetCapability("newCommandTimeout", "14400");
                capabilities.SetCapability("dontStopAppOnReset", "true");

                patientAppDriver = new AndroidDriver<AppiumWebElement>(new Uri("http://127.0.0.1:4723/wd/hub"), capabilities);

                DesiredCapabilities capabilities2 = new DesiredCapabilities();
                capabilities2.SetCapability("automationName", "Appium");
                capabilities2.SetCapability("platformName", "Android");
                capabilities2.SetCapability("noReset", "true");
                capabilities2.SetCapability("platformVersion", "8.1.0");
                capabilities2.SetCapability("deviceName", "Nexus");
                capabilities2.SetCapability("appPackage", "com.android.settings");
                capabilities2.SetCapability("appActivity", "com.android.settings.Settings");
                capabilities2.SetCapability("newCommandTimeout", "14400");
                capabilities2.SetCapability("dontStopAppOnReset", "true");

                settingsAppDriver = new AndroidDriver<AppiumWebElement>(new Uri("http://127.0.0.1:4723/wd/hub"), capabilities2);

private void StartAndroidAppiumServerAndCreateLog(string appiumLogFileName)
    {

        System.Diagnostics.Process process = new System.Diagnostics.Process();
        System.Diagnostics.ProcessStartInfo startInfo = new System.Diagnostics.ProcessStartInfo();
        startInfo.WindowStyle = System.Diagnostics.ProcessWindowStyle.Maximized;
        startInfo.FileName = "cmd.exe";        
        startInfo.UseShellExecute = false;
        startInfo.RedirectStandardOutput = true;
        startInfo.RedirectStandardError = true;
        startInfo.RedirectStandardInput = true;
        startInfo.Arguments = "/k (appium --address 127.0.0.1 --port 4723)";
        process.StartInfo = startInfo;
        process.Start();        

        using (FileStream appiumWriteFile2 = new FileStream("C:\\UPTE\\Test Results\\AppiumLog_1.txt", FileMode.Create, FileAccess.Write, FileShare.ReadWrite))
        using (StreamWriter appiumWriter2 = new StreamWriter(appiumWriteFile2))
        {
            while (!process.StandardOutput.EndOfStream)
            {
                var appiumOutput2 = process.StandardOutput.ReadLine();
                if (appiumOutput2 != null)
                {
                    appiumWriter2.WriteLine(appiumOutput2);
                    appiumWriter2.Flush();
                }
            }

        }

    }

**Comment by mykola-mokhnach** [comment]
You should provide correct capabilities:
https://github.com/appium/appium/blob/55760b7b9e1c494c6a1f22d152f0bd1fe676dae7/docs/en/advanced-concepts/parallel-tests.md

Closed as as duplicate

**Comment by vallj** [comment]
@mykola-mokhnach 

The solution you provided seems to be for running tests on multiple phones at the same time. What I'm trying to accomplish is starting two drivers for different apps. As soon as second driver session is started, first driver session is getting closed. This is happening even after setting the systemPort capability to different ports for both the drivers. 
Logs - https://gist.github.com/vallj/0023b816f74481125ee7f82fe744e0c4

**Comment by mykola-mokhnach** [comment]
It is impossible to run simultaneous driver sessions on the same device if this is what you are talking about.
