### ISSUE TITLE
 Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65

### ISSUE THREAD

**Issue by amitrparmar** [appium/appium#10564]
## The problem

I have recently updated the X code to run my test on iOS 11 devices. But after updating it I am getting this issue. I have tried to search this issue but all similar type of issue have been closed. (I didn't get any solution from those). So I am putting this here.

Could someone please have a look and suggest how can I solve this problem

## Environment

* Appium - 1.7.2
* Desktop OS/version - macOS High Sierra - 10.13.4
* XCode - 9.3 (9E145) 
* Node.js version - 3.10.10
* Mobile platform/version - iPad Air 2 - 11.2.6 
* Real device 

## Details

Please let me know if need any additional information
Working fine on iOS 10

## Link to Appium logs

Appium Log with showXCodeLog TRUE

https://gist.github.com/amitrparmar/5554bc83afcc24c4d8c652278808a2bc#file-appiumlogwithshowxcodelogtrue

## Code To Reproduce Issue [ Good To Have ]
Just need to start.

**Comment by mykola-mokhnach** [comment]
This issue is not different from the others: 

> Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 11.3'

The error message even contains a link to he detailed tutorial: https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

What else is needed?

**Comment by amitrparmar** [comment]
Hi @mykola-mokhnach ,

However I did the steps which are mentioned in link. And as I said, it is working fine on iOS 9.X.X, and iOS 10.X.X.  (If it is working n iOS 10 and not working on iOS 11, So is there any other steps which I need to follow for iOS 11. Please guide. )

I also checked manually in WebDriverAgent xcode project. And set the TEAM and Signing Certificate. 

Still, I'll double check the setting and try.

**Comment by amitrparmar** [comment]
Hi @mykola-mokhnach ,

I again check the all setting. 
I manually opened xCode project of WebDriver and set the Signing information in all scheme of the project but It didn't worked.

I also tried setting below capabilities 

_"xcodeOrgId": "<Team ID>",
"xcodeSigningId": "iPhone Developer"_

It also didn't worked.

Then after I tried below command 

$ _npm installs -g appium_

Then It started working. You can close this. Thanks.
