### ISSUE TITLE
Delete Cookies on Mobile Safari

### ISSUE THREAD

**Issue by kiranrayofhope** [appium/appium#10568]
## The problem

I'm writing UI automation for a web application which runs on iOS and Android. These tests run on remote Phone devices. So far, the tests with the same URLs run successfully for Android but they fail on iOS devices.

I have a test suite where each test in the suite has to pass the authentication workflow and navigate to the Page Under Test. When I run the test on iPhone Safari, the first test executes fine. When the second test is started, the initial test URL directly lands on the home page (skipping the authentication part and driver still searches for Username, password fields) because the cookies are already stored on the browser.

Is there any way I can delete the cookies stored in Safari browser with automation?

P.S: The test suite works absolutely fine for Android platform.

Technical Details:

Test Framework - Selenium

Mobile Automation Framework - Appium

Device: iPhone - version 11 (internal tools setup on the cloud for test suite execution)

Browser: Safari

* Appium version (or git revision) that exhibits the issue: 1.6.5 (supported version in our org)
* Desktop OS/version used to run Appium: iPhone
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS Mobile Safari
* Real device or emulator/simulator: Real Device

**Comment by mykola-mokhnach** [comment]
Apple provides no interfaces to clear Safari cookies on real devices. this is only possible on Simulator with a hack.

However you could try to open Safari preferences and click the corresponding button from there, like the real user would do it, or create some javascript backdoor. Another solution would be to do the test in a private tab.

**Comment by nageshc** [comment]
@mykola-mokhnach,
Is this possible to open private tab in safari using Appium?
You have any JavaScript example code to clear the cache and cookies in Safari.
Thank you.
