### ISSUE TITLE
Assistive touch button work only in top left corner of iphone 11

### ISSUE THREAD

**Issue by gur49502** [appium/appium#10562]
## The problem

Assitive touch is only working in the top-left corner and not anywhere on the screen.
## Environment

* Appium version (or git revision) that exhibits the issue:1.7.2

* Desktop OS/version used to run Appium: windows 10
* Node.js version (unless using Appium.app|exe): node-v0.12.1
* Mobile platform/version under test:IOS

**Comment by mykola-mokhnach** [comment]
Please provide appropriate issue description with server logs/screenshots
