### ISSUE TITLE
How to handle the automation iOS mobile testing when the screen takes more time to load the page.

### ISSUE THREAD

**Issue by Saifalip** [appium/appium#10569]
## The problem

I am facing the errors when i start full iOS app testing, 
In between if the internet fails or the poor network connection when the screen gets loading, my remaining all test cases are getting failed. But the script code is correct when if i run a single screen means particular pages.  

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 10.13.4
* Node.js version (unless using Appium.app|exe): 9.1.0
* Mobile platform/version under test: iPhone 6s / IOS 9.3
* Real device or emulator/simulator: simulator 
* Appium tool : 1.5.3

## Details

![screen shot 2018-04-18 at 11 38 52 am](https://user-images.githubusercontent.com/36480468/39033071-ea753ff4-448d-11e8-8cd7-ca55b06fcd90.png)
![screen shot 2018-04-17 at 3 01 07 pm](https://user-images.githubusercontent.com/36480468/39033031-bee41900-448d-11e8-9868-5efe79d17c49.png)

## Code To Reproduce Issue [ Good To Have ]
module.exports = (options) => {

	describe("Login: Successful Login", function SuccessfulLoginTests() {
		this.timeout(900000);

		it("Verify in Sign in screen, entering valid email address and password in text boxes", () => options.driver
			.sleep(5000)
			.elementById("emailTextField").clear() //Clear Email
			.elementById("passwordTextField").clear() //clear Password
			.elementById("emailTextField").sendKeys(`${user.email_prefix}${user.email_suffix}`) //Enter Email in Email filed
			.elementById("passwordTextField").sendKeys(user.password) //Enter Password in Password filed
			.then(() => {
				if (process.env.npm_config_enableScreenshot === "true") {
					return options.driver.saveScreenshot(`${options.screenshotPath}Successful_Login_Test1.jpg`);
				}
			}));

		it("Verify in Sign in screen, tap on Sign in button to successful login and redirecting to Profile screen ", () => options.driver
			.elementById("signInButton").click() //Login Button
			.sleep(8000)
			.then(() => {
				utils.isExists(options, "OK", (err, isExist) => {
					if (!isExist) {
						return;
					}
					return options.driver
						.then(() => options.driver.elementById("OK").click());
				});
			})
			.sleep(5000)
			.then(() => {
				utils.isExists(options, "icClearBlack24Px", (err, isExist) => {
					if (!isExist) {
						return;
					}
					return options.driver
						.then(() => options.driver.elementById("icClearBlack24Px"))
						.then((element) => element.click());
				});
			})
			.sleep(5000)
			.then(() => {
				if (process.env.npm_config_enableScreenshot === "true") {
					return options.driver.saveScreenshot(`${options.screenshotPath}Successful_Login_Test2.jpg`);
				}
			}));
	});
};
![screen shot 2018-04-20 at 11 17 36 am](https://user-images.githubusercontent.com/36480468/39032768-9c3d51f6-448c-11e8-8f09-66bccc4c4b29.png)

 after click on Sign in button it takes max 6 to 7 secs but i am giving 8 sec to successful login. 
But when network fails or poor connection its takes more to load the page.

Because of that the remaining test cases are failed. 

I have to display the valid error message if network fails 

Could anyone look at this to solve this issue. i am facing a lot.

**Comment by surya7886** [comment]
The same Issue am facing android real device 

**Environment**

Appium version (or git revision) that exhibits the issue: 1.7.1
Last Appium version that did not exhibit the issue (if applicable):
Desktop OS/version used to run Appium: ubuntu 16.04 LTS 
Node.js version (unless using Appium.app|exe):  v7.10.1
Mobile platform/version under test: Android 6.0 v
Real device or emulator/simulator: Real device
Appium tool : 1.5.3



When system network or Real device network fails or disconnecting and connecting connection its takes more to load the page.

Because of that, reason remaining test cases are failed.

I have to display the validation error message if the network fails, i have to display error (Network connection lost) 

Could anyone help to solve this issue?

**Comment by vjmaiky** [comment]
Just make a fluent wait, to wait until your element is displayed and visible. Increase seconds. 
```
    public void waitForElementVIsibilityIOS(By element) {
        FluentWait<IOSDriver> wait = new FluentWait<IOSDriver>(Drivers.driverIos).withTimeout(20, TimeUnit.SECONDS).ignoring(NoSuchElementException.class);
        wait.until(ExpectedConditions.visibilityOfElementLocated(element));
    }
```

**Comment by Saifalip** [comment]
@vjmaiky thanks for looking in this issue 
i am using the node js
so how can we use the "public void" in node.js 
could you please help to solve this one

**Comment by mykola-mokhnach** [comment]
Please use discuss.appium.io to ask questions. Here we only solve server part issues.
