### ISSUE TITLE
How to add chrome browser extension in android real device

### ISSUE THREAD

**Issue by Elangopalakrishnan** [appium/appium#10567]
## The problem

I need to add extension in my android device's chrome browser.
And i need to do this by code.
Please suggest me on this...!

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Desktop OS/version used to run Appium: Mac High Sierra and Windows 7
* Mobile platform/version under test: Samsung S5 Version - 5.1.1
* Real device or emulator/simulator: Real device
* Android Device Chrome browser version : 65.0.3325.109
* Chrome driver version in mac : 2.37
* Code : C#

## Link to Appium logs

This is an error i'm getting in Visual studio 

An unknown server-side error occurred while processing the command. Original error: Failed to start Chromedriver session: An unknown server-side error occurred while processing the command. (Original error: unknown error: cannot parse capability: chromeOptions

from unknown error: unrecognized chrome option: prefs

  (Driver info: chromedriver=2.37.544337 (8c0344a12e552148c185f7d5117db1fd6c9e85),platform=Mac OS X 10.13.4 x86_64))

## Code To Reproduce Issue [ Good To Have ]
**Code - C#**
```csharp
ChromeOptions options = new ChromeOptions();
options.AddUserProfilePreference("credentials_enable_service", false);
options.AddUserProfilePreference("profile.password_manager_enabled", false);
options.AddArguments("test-type");
options.AddArguments("disable-infobars");
options.AddExtension(@"\\machienname\ChromeModHeaderExtension\extension_2_1_2.crx");

DesiredCaps = options.ToCapabilities() as DesiredCapabilities;
DesiredCaps.SetCapability("platformName","Android");
DesiredCaps.SetCapability("platformVersion", "5.1.1");
DesiredCaps.SetCapability("deviceName", "SAMSUNG");
DesiredCaps.SetCapability("browserName", "Chrome");
DesiredCaps.SetCapability("device", "Android");
DesiredCaps.SetCapability("newCommandTimeout", "120000");

AppDriver = new AndroidDriver<AppiumWebElement>(new Uri("http://" + AppiumIPAddress + ":" + AppiumPort + "/wd/hub"), DesiredCaps, TimeSpan.FromSeconds(300));
```
Thanks in advance!
Elango

**Comment by liviudanu-ellation** [comment]
@Elangopalakrishnan, Not sure if you can do it on mobile. Here's some info that might help you: 
https://sites.google.com/a/chromium.org/chromedriver/capabilities

**Comment by imurchie** [comment]
Chromedriver for Android does not have `prefs` in their `ChromeOptions`. See https://sites.google.com/a/chromium.org/chromedriver/getting-started/getting-started---android

**Comment by Elangopalakrishnan** [comment]
@imurchie  Thanks :)
I saw android chrome not supporting any extensions right now here -->
https://developer.chrome.com/multidevice/faq

**Does Chrome for Android support apps and extensions?
Chrome apps and extensions are currently not supported on Chrome for Android. We have no plans to announce at this time.**

please share your thoughts.....

**Comment by liviudanu-ellation** [comment]
@Elangopalakrishnan, as an advice, you can try to use Charles Proxy instead
