### ISSUE TITLE
Support FaceID in IOS Simulators

### ISSUE THREAD

**Issue by fujiisnj** [appium/appium#10563]
Does any of you know how to do "faceid automation" through appium?

**Comment by mykola-mokhnach** [comment]
Currently there is no support of such feature in Appium. You're welcome to create a PR though.

**Comment by dpgraham** [comment]
I'd like to track this issue now that this is supported (via AppleScript) in IOS 10 Simulators.

**Comment by fujiisnj** [comment]
>dpgraham
Do you know how to automate faceid identification through appium script code?

**Comment by dpgraham** [comment]
@fujiisnj it's not supported yet, but I'm adding it to our backlog as a feature.

I don't know when we'll be able to implement it, but if anyone in the community makes a pull request for it we can have it out sooner.

**Comment by dpgraham** [comment]
Acceptance Criteria
* [ ] Add an endpoint to xcuitest-driver `mobile: enrollBiometric` that enables faceId _or_ touchId
* [ ] Add an endpoint to /webdriveragent that handles faceId

**Comment by dpgraham** [comment]
@mykola-mokhnach It's available in `appium-ios-simulator` but faceId enrollment isn't available yet. We still need to make a `mobile:` endpoint that does that.

**Comment by mykola-mokhnach** [comment]
Closed as fixed
