### ISSUE TITLE
WebDriverAgent isn't launched on iPad Air 2 WIFI iOS 11.0 by Xcode 9.3

### ISSUE THREAD

**Issue by ledinhphuong** [appium/appium#10577]
## The problem

After I upgrade to the latest appium@1.8.0, my test script cannot pass on iPad Air 2 WIFI (iOS 11.0) because WebDriverAgent isn't launched (`[NSKeyedUnarchiver initForReadingFromData:error:]: unrecognized selector sent to instance` error).

## Environment

* Appium version: 1.8.0
* Node.js version: v7.10.1
* Real device: iPad Air 2 WIFI (iOS 11.0)
* Xcode: 9.3 (Build version 9E145)

## Details

* It works well if I use Appium@1.8.0 with Xcode 9.2

## Link to Appium logs

https://gist.github.com/ledinhphuong/d431cfe5298788f9355d8cdff438bd27

## Link to iOS logs

https://gist.github.com/ledinhphuong/f7103e7bcf6f9ba6af4901a346b9c9cb

**Comment by mykola-mokhnach** [comment]
Can you attach the device log?

**Comment by mykola-mokhnach** [comment]
Might be an Xcode issue: https://github.com/CocoaPods/CocoaPods/issues/7608

**Comment by ledinhphuong** [comment]
@mykola-mokhnach I've just added iOS logs link into the description of this issue. Thanks.

**Comment by ledinhphuong** [comment]
I posted an issue at https://github.com/facebook/WebDriverAgent/issues/916
