### ISSUE TITLE
Appium failed to perform tap on screen, stating the error : Coordinate [x, y] is outside of element rect: [,][,]"}

### ISSUE THREAD

**Issue by QA2Dev** [appium/appium#10574]
## The problem

Appium failed to perform tap on application screen, stating the error : Coordinate [x, y] is outside of element rect: [0,0][x,y]"}.
Resolution of Screen is :  2560x1440
Resolution of Screen adopted by Appium is : Display bounds: [0,0][2392,1440]

## Environment
Device: LGG3 (Real device - Smartphone)
Android OS: 6.0
Appium Version: 1.7.2
MacOS : 10.13.2
Xcode: 9.2
JavaClient: 5.0.4

## Details

Appium failed to perform tap on screen screen on LG G3 phone (Resolution : 2560x1440 ), stating the error : Coordinate [x, y] is outside of element rect: [0,0][x,y]"}.
Resolution of Screen is :  2560x1440
Resolution of Screen adopted by Appium is : Display bounds: [0,0][2392,1440]
Action performed at Coordinates : [2393,164] 

**Note:-**  Kindly note that it's working fine on other devices with resolutions (2048x1536, 1024x768)

## Appium logs

Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":2393,"y":164}},{"action":"release","options":{}}],"30a46825-2f88-487d-91f4-1f74f9426d73"]
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"click","params":{"x":2393,"y":164}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"click","params":{"x":2393,"y":164}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: click
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Display bounds: [0,0][2392,1440]
[debug] [AndroidBootstrap] Received command result from bootstrap
[HTTP] <-- POST /wd/hub/session/30a46825-2f88-487d-91f4-1f74f9426d73/touch/perform 500 31 ms - 153 
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":29,"value":"Coordinate [x=2393.0, y=164.0] is outside of element rect: [0,0][2392,1440]"}

**Comment by mykola-mokhnach** [comment]
Switch to uiautomator2

**Comment by QA2Dev** [comment]
Thank you @mykola-mokhnach for your suggestion, may I know if there is a way to solve the issue with Appium itself ?, is it the limitation from UIAutomator2 ?.

Is there any cap/limit setup on screen resolution to perform gestures using Appium?.

Is there any way to increase the Display Bounds of application through Appium capabilities ?.

let me also know if you required additional details to look into the issue.

**Comment by vmaxim** [comment]
@QA2Dev 
https://developer.android.com/reference/android/view/Display.html#getSize(android.graphics.Point)
>it will report the size of the entire display based on current rotation and with subtracted system decoration areas.

In your case the subtracted area is software buttons (Back/Home/Menu).

**Comment by QA2Dev** [comment]
Thank you for the details @mykola-mokhnach and @vmaxim.

**Comment by QA2Dev** [comment]
@mykola-mokhnach I switched to uiautomator2 (set the capability automationname to uiautomator2 ) as suggested but still issue persists.

As @vmaxim mentioned may I know whether uiautomator2 also substracts the actual window area and reset the displaybounds to a rect size?. (I mean to ask is, doesn't it (uiautomator2) gets the real size of the display without subtracting any window decor by adding any capability)
