### ISSUE TITLE
IOS Real Device: How to provide mock images for testing application that read camera images ?

### ISSUE THREAD

**Issue by Devapal** [appium/appium#10570]
## The problem
Can I get the current running camera instance and and give a particular file as input in **IOS Real Device**
 Is this possible with appium ?  
Please Advise 

More Details:
I am trying to feed my camera an image during runtime. So basically my application has a feature: **search a product by scanning a barcode**, Since I am trying to automate this, I want to provide an image with barcode and have camera take that image while scanning. 

## Environment
* Appium version: 1.3.2
* Desktop OS/version used to run Appium: MAC OS High Sierra (10.13.4)
* Mobile platform/version under test: iPhone 8 Plus, OS 11.3
* Real device or emulator/simulator: REAL DEVICE

Please Advise

**Comment by mykola-mokhnach** [comment]
Unfortunately, Appium does not provide such functionality. Perhaps, there are some third party apps, that you can use for such purpose.
