### ISSUE TITLE
WebDriverException: Could not find a connected Android device.

### ISSUE THREAD

**Issue by manishpraj** [appium/appium#10573]
## The problem

Getting WebDriver Exception while connecting to android devices on Raspberry pi. Device is already connected and showing in adb devices.

## Environment
I have installed Appium, Android, Selenium on Raspberry pi. Everything looks OK from Appium doctor.

## Link to Appium logs

<script src="https://gist.github.com/manishpraj/70db589c6478f36b4646171d05709edb.js"></script>

## Code To Reproduce Issue [ Good To Have ]
from appium import webdriver
import time

desired_caps = {}
desired_caps['platformName'] = 'Android'
desired_caps['platformVersion'] = '6.0.1'
desired_caps['deviceName'] = 'Nexus 5'
desired_caps['appActivity'] = 'com.cox.voiceeverywhere.main.login.LoginActivity'
desired_caps['appPackage'] = 'com.cox.voiceeverywhere.android'
desired_caps['browserName']='chrome'

phone1 = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)

**Comment by mykola-mokhnach** [comment]
what is the Appium version?
what is the terminal output of `adb -P 5037 devices` command ?

**Comment by manishpraj** [comment]
Appium Version:  Appium v1.7.2
List of devices attached 
0309fa3408e4f19d	device

**Comment by manishpraj** [comment]
pi@raspberrypi:~ $ sudo pip install Appium-Python-Client
Requirement already satisfied: Appium-Python-Client in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: selenium>=2.47.0 in /usr/local/lib/python2.7/dist-packages (from Appium-Python-Client)

**Comment by manishpraj** [comment]
Please reply

**Comment by KazuCocoa** [comment]
Could you check the below output?
If one machine has different adb versions with different paths, conflicts and such adb command error happens when we run one of them.

- `/home/pi/Android/Sdk/platform-tools/adb -P 5037 devices`
- `/home/pi/Android/Sdk/platform-tools/adb version`

--

- `adb version`

**Comment by manishpraj** [comment]
pi@raspberrypi:~ $ /home/pi/Android/Sdk/platform-tools/adb -P 5037 devices
bash: /home/pi/Android/Sdk/platform-tools/adb: cannot execute binary file: Exec format error
pi@raspberrypi:~ $ /home/pi/Android/Sdk/platform-tools/adb version
bash: /home/pi/Android/Sdk/platform-tools/adb: cannot execute binary file: Exec format error
pi@raspberrypi:~ $

**Comment by mykola-mokhnach** [comment]
> cannot execute binary file: Exec format error

Closed as third party issue
