### ISSUE TITLE
[1.8.0] [iOS] MJSONWP  failing on running tests iOS tests on Real Device

### ISSUE THREAD

**Issue by Shriniketannl** [appium/appium#10576]
## The problem
MJSONWP  failing on running tests

## Environment

* Appium version (or git revision) that exhibits the issue:  1.8.0
* Last Appium version that did not exhibit the issue (if applicable): 1.7.1
* Desktop OS/version used to run Appium:  
* Node.js version (unless using Appium.app|exe):   v7.6.0
* Mobile platform/version under test:   iPhone
* Real device or emulator/simulator:   Real Device
* Appium CLI or Appium.app|exe:  Appium CLI

## Details
Touch actions are failing which might be causing MJSONWP to fail 
 {"value":"-[NSNull floatValue]: unrecognized selector sent to instance 0x1abb7bef8\n\n(\n\t0   CoreFoundation                      0x0000000185a12ff8 <redacted> + 148\n\t1   libobjc.A.dylib                     0x0000000184474538 objc_exception_throw + 56\n\t2   CoreFoundation                      0x0000000185a19ef4 <redacted> + 0\n\t3   CoreFoundation                      0x0000000185a16f54 <redacted> + 916\n\t4   CoreFoundation                      0x0000000185912d4c _CF_forwarding_prep_0 + 92\n\t5   WebDriverAgentLib                   0x0000000101dd919c -[FBAppiumGestureItem coordinatesWithOptions:error:] + 1056\n\t6   WebDriverAgentLib                   0x0000000101dd88c0 -[FBAppiumGestureItem initWithActionItem:application:atPosition:offset:error:] + 472\n\t7   WebDriverAgentLib                   0x0000000101ddb550 -[FBAppiumActionsSynthesizer eventPathsWithAction:error:] + 1328\n\t8   WebDriverAgentLib                   0x0000000101ddc084 -[FBAppiumActionsSynthesizer synthesizeWithError:] + 984\n\t9  ...

## Link to Appium logs

https://gist.github.com/Shriniketannl/df0880932ad710a38997496afcbf24e6

**Comment by mykola-mokhnach** [comment]
> [debug] [XCUITest] Received the following touch action: tap(options={"y":null,"x":null,"count":1,"element":"17000000-0000-0000-9209-000000000000"})


The coordinates should not be `null`. Closed as not an issue

**Comment by Shriniketannl** [comment]
Hi @mykola-mokhnach but this is working fine on v1.7.1
https://gist.github.com/Shriniketannl/29e4bba4e9d0348677b667842ec2374f

**Comment by jkorany** [comment]
The Appium Python client also sends null by default for x, y coordinates when performing touch actions. See [line 121 in the touch actions file](https://github.com/appium/python-client/blob/master/appium/webdriver/common/touch_action.py). What's the expected default value for x and y if not null?

**Comment by mykola-mokhnach** [comment]
@jkorany Such behaviour is wrong and should be fixed. The coordinates should either not exist or should contain valid numeric values, but not null

**Comment by mykola-mokhnach** [comment]
I'll create a fix. For now you could provide some coordinates there, for example `(width / 2, height / 2)`, so the client does not set them to None
