### ISSUE TITLE
WebDriverAgentRunner Test failed with 1.8.0

### ISSUE THREAD

**Issue by romainlouvet** [appium/appium#10575]
## The problem

After upgrade appium 1.8.0, I try to install WebDriverAgentRunner on real device.
When execute xcodebuild test -> Test failed

## Environment

* Appium version : 1.8.0
* Real device: iPhone 7 iOS 11.3
* Xcode version: 9.3

## Details
After changed correct signing profile
xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'a42a84ac04117adaf67abf9a0586bae2b1fceffd' test 

I try to uninstall / install Appium, same problem when try to launch test

## Link to Appium logs

https://gist.github.com/romainlouvet/4a97dfae8c6fc287503cc150ff0061a5

**Comment by mykola-mokhnach** [comment]
This looks like an Xcode issue. Try to reboot/reset the device

**Comment by romainlouvet** [comment]
same :/ https://gist.github.com/romainlouvet/94e03c742185583fc3df886ea1a85bd8

**Comment by mykola-mokhnach** [comment]
The recent log is not the same. Do you have the device log?

**Comment by romainlouvet** [comment]
here my device log -> https://gist.github.com/romainlouvet/15dab0aca1a659fa33d2812345867c9e

**Comment by ledinhphuong** [comment]
There is an issue `/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer: required code signature missing` in your appium logs.

**Comment by ledinhphuong** [comment]
My fixing as: update `Code Signing Identity` in `Xcode > Build Settings` for WebDriverAgent Lib and WebDriverAgentRunner scheme by manual.

**Comment by romainlouvet** [comment]
Thank's @ledinhphuong
