### ISSUE TITLE
Socket hang up due to WebDriverAgentRunner crash

### ISSUE THREAD

**Issue by gergm** [appium/appium#10579]
## The problem

A call to WebDriver.swipe causes a socket hang up exception, ie:
```selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up```

I have attached a crash file that was generated at the same time.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: macOS High Sierra V 10.13.4
* Node.js version (unless using Appium.app|exe): v9.11.1
* Mobile platform/version under test: iOS 11.2, iPhone 7 simulator, Xcode V 9.3
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe:

## Details

See attached crash file
[WebDriverAgentRunner-Runner_2018-04-23-173535_slc-qa-autotest-2.crash.zip](https://github.com/appium/appium/files/1940699/WebDriverAgentRunner-Runner_2018-04-23-173535_slc-qa-autotest-2.crash.zip)

## Link to Appium logs

https://gist.github.com/gergm/59215196441d36b5df19ac6751a1cee1

## Code To Reproduce Issue [ Good To Have ]

self.driver.swipe(x_coord_start, y_coord_start, x_coord_end, y_coord_end, duration=duration)

**Comment by vjmaiky** [comment]
use touch actions methods and update to a later appium version

**Comment by gergm** [comment]
Thanks for your quick response. I had tried appium V1.8.0, but the swipe method did not swipe at all. Is swipe no longer recommended or supported?

Anyway, I'll give touch actions a go.

**Comment by vjmaiky** [comment]
if you uprated also the java appium library, you'll notice that it is deprecated.

Here is an example with what i use for swipe up:

```
    public static void swipeUp() throws IOException, ParseException {
        Dimension screenDim = Drivers.getMobileDriver().manage().window().getSize();
        int height = screenDim.height;
        int width = screenDim.width;
        if (isIosFromJason()) {
            MyLogger.log.info("Swipe up using iOS Driver");
            new TouchAction(Drivers.getMobileDriver()).press(PointOption.point(width / 5, height - 2)).moveTo(PointOption.point(width / 5, -height - 1)).release().perform();
        } else {
            MyLogger.log.info("Swipe up using android Driver");
            new TouchAction(Drivers.getMobileDriver()).press(PointOption.point(width / 2, height - (height / 6))).moveTo(PointOption.point(width / 2, height / 7)).release().perform();

        }
    }
```

or: 
```
    /**
     * Mobile Swipe using JS - WORKS
     *
     * @param direction direction: Either 'up', 'down', 'left' or 'right'
     */
    public static void mobileSwipe(String direction) {
        JavascriptExecutor js = (JavascriptExecutor) Drivers.getMobileDriver();
        Map<String, Object> params = new HashMap<>();
        params.put("direction", direction);
        js.executeScript("mobile: swipe", params);
    }
```

**Comment by VenkataHanuma** [comment]
Downgrade appium java-client library to 5.0.0-BETA9. This version supports swipe operations and also supports iOS 11.3.

**Comment by gergm** [comment]
thanks again for all the responses.
fyi, I am using Appium-Python-Client 0.26. There is no indication in the PyDoc that swipe is deprecated. In fact, swipe uses a TouchAction which is basically the same as the example Java from @vjmaiky

**Comment by gergm** [comment]
I guess you can close this issue. I was using relative coordinates to swipe and appium V1.8.0 only supports absolute coordinates.
I'll open another issue if I see similar behavior with Appium V1.8.0
