### ISSUE TITLE
Unable to switch to web view in hybrid app.

### ISSUE THREAD

**Issue by mmaxin** [appium/appium#10571]
## The problem

Hi, I am trying to switch to web context from native and then switch back. However it throws an error at me which I have tried to solve with solutions found online but nothing seems to be working. The code flow is to click an element within the native context which then redirects to a webpage to approve authentication and then return back to the native context.

The error is thrown by: 

`driver.context((String) contextNames.toArray()[1]);`

which is: 

`[Chromedriver] Error: Failed to start Chromedriver session: An unknown server-side error occurred while processing the command. (Original error: unknown error: Failed to get sockets matching: @webview_devtools_remote_.*23686`

My code chunk is: 

`
wait.until(ExpectedConditions.visibilityOfElementLocated
                (By.id("com.android.chrome:id/location_bar")));

        Set<String> contextNames = driver.getContextHandles();
        for (String contextName : contextNames) {
            System.out.println(contextNames); 
        }

        driver.context((String) contextNames.toArray()[1]); 
        System.out.println("Expected chrome: "+driver.getContext());

        WebView.setWebContentsDebuggingEnabled(true);

        driver.findElement(By.xpath("/html/body/div[1]/div[4]/div/div/div[4]/a[1]")).click();

        driver.context("NATIVE_APP");
`

as well as in my capabilities I have the following:

`        capabilities.setCapability("appium-version", "1.7.2");

        capabilities.setCapability("platformName", "Android");

        capabilities.setCapability("deviceName", deviceName);

        capabilities.setCapability("appPackage", "de.codenauts.hockeyapp");

        capabilities.setCapability("appActivity","net.hockeyapp.client.HomeActivity");

        capabilities.setCapability("setWebContentsDebuggingEnabled","true");
`

## Environment
My Appium version is 1.7.2
The mobile device is running chrome 65.0.3325.109
The chromedriver version I have is 3.38
node version v8.10.0
Android 6.01, real device: LG-k557

## Link to Appium logs

The Logs can be found here: https://gist.github.com/mmaxin/6cdf8cc14c372ed763b9e41599f88494

**Comment by mmaxin** [comment]
Upgrading to 6.0.0-BETA5 still gives the same output.

**Comment by imurchie** [comment]
Is the webview marked for debugging?

**Comment by mmaxin** [comment]
I am not quiet sure what you mean (I am fairly new to this). 
I have this enabled as well in my main gradle file 
`    testOptions {
        unitTests.returnDefaultValues = true
    }
`

Also one more thing to note is when using the Android Device Monitor from Android Studio I get a Error obtaining Hierarchy error while the driver is running.

`
Error obtaining UI hierarchy
Error while obtaining UI hierarchy XML file: com.android.ddmlib.SyncException: Remote object doesn't exist!
`

**Comment by mykola-mokhnach** [comment]
> Upgrading to 6.0.0-BETA5 still gives the same output.

I was talking about updating the server rather than the client

**Comment by mmaxin** [comment]
I updated to the newest release (1.8) but it still does now seem to be working, here is the new log: https://gist.github.com/mmaxin/e1e331d1b4dac49cb7766f6bbb2082d0

I have tried it with and without:
`WebView.setWebContentsDebuggingEnabled(true);`

also I have to kill it after a while as it doesn't time out.

**Comment by mykola-mokhnach** [comment]
Is the web view visible in Chrome remote debugger if you put a breakpoint there before switching to the web view?

**Comment by mmaxin** [comment]
Even without a breakpoint it works well and displays everything. I can interact and click the element I want. 

<img width="958" alt="chrome_debugger" src="https://user-images.githubusercontent.com/24641008/39086716-54dcf784-4564-11e8-8052-33f29da453f8.png">

**Comment by mykola-mokhnach** [comment]
Closed as inactive

**Comment by vutukuriswathi** [comment]
I am also facing the same issue

**Comment by kashban** [comment]
Same here, though I don't get an error at all. The context is just not switched back to web. 

Appium 1.8.1, ChromeWebDriver 2.34.

**Comment by prevostc** [comment]
Same issue here: 
- Appium 1.9.1
- Driver info: chromedriver=2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac),platform=Linux 4.4.0-134-generic x86_64
- cordova 7.0.1

**Comment by prat3ik** [comment]
I am also facing the same:

- Appium 1.10.0
- Driver info: chromedriver=2.46.628411 (Mac OS)
- React Native
