### ISSUE TITLE
Class cast exception when I am searching element under element

### ISSUE THREAD

**Issue by ptsiakos77** [appium/appium#10585]
## The problem

When I am searching for a mobile element under another element and not root I am taking the following exception message:
Returned value cannot be converted to WebElement: PLAIN_HEADER_LABEL

Vie the full stack trace below:
https://gist.github.com/ptsiakos77/b0ecef5ff6e422eee18b8ccd17a35fc4#file-gistfile1-txt

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8
* Last Appium version that did not exhibit the issue (if applicable): 1.7.1
* Node.js version (unless using Appium.app|exe): 8.9.4
* Mobile platform/version under test: IOS 11.3
* Real device or emulator/simulator: iphone6s Real Device
* Appium Java client: 3.5.3

## Details
I have problems finding an element under another element. It worked fine in appium 1.7.1. In the following code the second attempt to find the element fails with the exception above
WebElement cell = driver.findElement(MobileBy.ByIosClassChain("**/XCUIElementTypeTable[1]/XCUIElementTypeCell"))
WebElement label = cell.findElement(MobileBy.ByIosClassChain('PLAIN_HEADER_LABEL'))

## Link to Appium logs
https://gist.github.com/ptsiakos77/069df238b0583a67922932dfb8584fbc#file-gistfile1-txt

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/appium/java-client

**Comment by ptsiakos77** [comment]
Thanks @mykola-mokhnach I issued this there. The only think that troubles me is that from appium logs it seems that the WDA responds with no element found in Executing command 'findElementFromElement' although the element exists. I was wondering if there is problem to server side as well in findElementFromElement
