### ISSUE TITLE
Unable to start WebDriverAgent session because of xcodebuild failure: "Could not proxy command to remote server. Original error: Error: getaddrinfo ENOTFOUND null null:80". 

### ISSUE THREAD

**Issue by parul001** [appium/appium#10584]
## The problem

Unable to start WebDriverAgent session because of xcodebuild failure: "Could not proxy command to remote server. Original error: Error: getaddrinfo ENOTFOUND null null:80". 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5
* Desktop OS/version used to run Appium:MacOs High sierra
* Node.js version (unless using Appium.app|exe):1.9
* Mobile platform/version under test: iphone 6 version 11.3
* Appium CLI or Appium.app|exe: Appium.app

## Link to Appium logs

https://gist.github.com/parul001/cfbbce5481ac6925abfc2abf6f21c617

`DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
		desiredCapabilities.setCapability("showXcodeLog", true);
		desiredCapabilities.setCapability("deviceName", "iPhone6");
		desiredCapabilities.setCapability("platformName", "iOS");
		desiredCapabilities.setCapability("platformVersion", "11.3");
		desiredCapabilities.setCapability("udid", "e81704788af167cee32164b420eeee89894d857c");		
		desiredCapabilities.setCapability("app", "/Users/himanshug/Desktop/SafariLauncher 2018-04-24 11-50-06_for platform 11.3/SafariLauncher.ipa"); 
		desiredCapabilities.setCapability("automationName", "XCUITest");
		desiredCapabilities.setCapability("browserName", "safari");
		desiredCapabilities.setCapability("webDriverAgentUrl", "WDAServer.SERVER_URL");
		desiredCapabilities.setCapability("newCommandTimeout", "300");
		desiredCapabilities.setCapability("startIWDP", "true");
		Map<String, String> env = new HashMap<>(System.getenv());
		env.put("PATH", "/usr/local/bin:" + env.get("PATH"));
		AppiumDriverLocalService service = AppiumDriverLocalService.buildService ( new AppiumServiceBuilder ( )
				.withEnvironment(env)
				.withIPAddress("127.0.0.1")
				.usingDriverExecutable ( new File ("/usr/local/bin/node") )
				.withAppiumJS ( new File (
						"/Applications/Appium.app/Contents/Resources/app/node_modules/appium/build/lib/main.js") )
				.usingPort ( 4723 ) 
				.withArgument ( GeneralServerFlag.LOG_LEVEL ,
						"debug" ) ) ;
		service.start(); 
AppiumDriver driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), desiredCapabilities);
		driver.manage().timeouts().implicitlyWait(200, TimeUnit.SECONDS);
		driver.get("https://www.amazon.in/");`

**Comment by mykola-mokhnach** [comment]
> [Appium]   webDriverAgentUrl: WDAServer.SERVER_URL

This does not look correct at all

**Comment by parul001** [comment]
please note that while building WebDriver Agent i have use all code signing  stuff . Webdriver Agent builds without any error but when  perform Test operation it successfully  installs the WebdriverAgent app on the iphone but at last  Screen shows Test failed .

**Comment by parul001** [comment]
@mykola-mokhnach  please mention whats not correct at all .
thanks for your reply

**Comment by parul001** [comment]
https://gist.github.com/parul001/24dc1e038583d33331ce3cc828a98ebb 
 this time i removed that The WDA server URL capability  but it runs with this error:
An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device. (WARNING: The server did not provide any stacktrace information)

**Comment by mykola-mokhnach** [comment]
I assume the error message is pretty clear there. Please use discuss.appium.io if you have additional questions.
