### ISSUE TITLE
tap not work on correct coordinate with element with x and y given (using python binding)

### ISSUE THREAD

**Issue by loveiset** [appium/appium#10581]
## The problem

```
action = TouchAction(driver)
action.tap(element, x, y).perform()
```
it does not tap on expected coordinate, as a result it tap on the middle of this element.

## Environment

* Appium version: 1.8.0
* OS/version: win7 64 SP1
* Node.js version: v8.11.0
* Mobile platform/version under test: Android 6.0.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: `appium --session-override --no-reset`

## Details

I want to tap on an element on  coordinate with offset x/y set, but it seems always tap on the middle of this element when I changed the value of x/y, it seems that tap method with offset x/y not working.
### log from adb logcat
```
Element found at location (210,1229)
Get Size of element command
AppiumResponse: {"sessionId":"2a574460-f7d8-444a-bd9e-5528bf027af5","status":0,"value":{"width":144,"height":87}}
InteractionController: clickAndSync(282, 1272)
```
after calculating, click coordinates just equels to the location of element + half of element size.
### packet captured
I use fiddler to capture the actual post params
```
http://127.0.0.1:4723/wd/hub/session/ef265481-a096-4d4b-859b-98accbe8f6cd/touch/perform
{"sessionId": "ef265481-a096-4d4b-859b-98accbe8f6cd", "actions": [{"action": "tap", "options": {"y": 8.700000000000001, "x": 129.6, "count": 1, "element": "cd2482de-885a-4fc9-9f2e-cce49756a742"}}]}
```

## Link to Appium logs

[appium logs](https://gist.github.com/loveiset/61f1a49e29776a37198dcc17a92b6e3d)

**Comment by mykola-mokhnach** [comment]
> [HTTP] {"sessionId":"ef265481-a096-4d4b-859b-98accbe8f6cd","actions":[{"action":"tap","options":{"y":8.700000000000001,"x":129.6,"count":1,"element":"cd2482de-885a-4fc9-9f2e-cce49756a742"}}]}
> [debug] [W3C] Calling AppiumDriver.performTouch() with args: [[{"action":"tap","options":{"y":8.700000000000001,"x":129.6,"count":1,"element":"cd2482de-885a-4fc9-9f2e-cce49756a742"}}],"ef265481-a096-4d4b-859b-98accbe8f6cd"]
> [UiAutomator2] calling get location: cd2482de-885a-4fc9-9f2e-cce49756a742
> [debug] [JSONWP Proxy] Proxying [GET /element/cd2482de-885a-4fc9-9f2e-cce49756a742/location] to [GET http://localhost:8200/wd/hub/session/2a574460-f7d8-444a-bd9e-5528bf027af5/element/cd2482de-885a-4fc9-9f2e-cce49756a742/location] with body: {}
> [debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"2a574460-f7d8-444a-bd9e-5528bf027af5\",\"status\":0,\"value\":{\"x\":210,\"y\":1229}}"
> [debug] [JSONWP Proxy] Proxying [POST /element/cd2482de-885a-4fc9-9f2e-cce49756a742/click] to [POST http://localhost:8200/wd/hub/session/2a574460-f7d8-444a-bd9e-5528bf027af5/element/cd2482de-885a-4fc9-9f2e-cce49756a742/click] with body: {"element":"cd2482de-885a-4fc9-9f2e-cce49756a742","x":339.6,"y":1237.7}
> [debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"2a574460-f7d8-444a-bd9e-5528bf027af5","status":0,"value":true}

In the log the coordinates calculation looks good, so it should not be python issue, but rather something inside UIA2 server component:

"x":339.6 = 210 + 129.6 
"y":1237.7 = 1229 + 8.7

**Comment by mykola-mokhnach** [comment]
@vmaxim Yes, It does. See the PR above

**Comment by cuhavp** [comment]
I face the same problem with TouchAction class,
I want to scroll to bottom but I saw in appium log are opposite:
==== Appium logs ====================
[HTTP] <-- GET /wd/hub/session/7ff4bca9-5cfd-4bfa-a444-0719d9fc9f97/window/current/size 200 694 ms - 98 
[HTTP] --> POST /wd/hub/session/7ff4bca9-5cfd-4bfa-a444-0719d9fc9f97/touch/perform {"actions":[{"action":"press","options":{"x":187,"y":133}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"x":187,"y":533}},{"action":"release","options":{}}]}
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":187,"y":133}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"x":187,"y":533}},{"action":"release","options":{}}],"7ff4bca9-5cfd-4bfa-a444-0719d9fc9f97"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: press(options={"x":187,"y":133})-wait(options={"ms":1000})-moveTo(options={"x":187,"y":533})-release(options={})
[debug] [XCUITest] Found matching gesture: drag
[debug] [JSONWP Proxy] Proxying [POST /wda/dragfromtoforduration] to [POST http://localhost:8100/session/B1C13F68-1C49-42A9-B013-DF54310069C4/wda/dragfromtoforduration] with body: {"fromX":187,"fromY":133,"toX":374,"toY":666,"duration":1}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"B1C13F68-1C49-42A9-B013-DF54310069C4","status":0}
===========

== My code ===
 fun swipeVertical(startPercentage: Double = 0.8, finalPercentage: Double = 0.2, anchorPercentage: Double = 0.5, duration: Long = 1000) {
            val size = driver?.manage()!!.window().size
            val anchor = (size.width * anchorPercentage)
            val startPoint = (size.height * startPercentage)
            val endPoint = (size.height * finalPercentage)

            val start = PointOption.point(anchor.toInt(), startPoint.toInt())
            val end = PointOption.point(anchor.toInt(), endPoint.toInt())

            if (PortfolioGlobals.KARATE != null) {
                var platform = PortfolioGlobals.KARATE!!.context.vars.get("platform")?.value.toString()
                (if (platform == "android") {
                    AndroidTouchAction(driver).press(start).waitAction(WaitOptions.waitOptions(Duration.ofMillis(duration))).moveTo(end).release().perform()
                } else {
                    IOSTouchAction(driver).press(end).waitAction(WaitOptions.waitOptions(Duration.ofMillis(duration))).moveTo(start).release().perform()

                })
            }

        }
============

**Comment by MummanaSubramanya** [comment]
why this PR has not been merged yet!! https://github.com/appium/appium-uiautomator2-driver/pull/163

**Comment by dbr13** [comment]
From my side tap doesn't work with iOS devices using 3D Touch no matter iOS version. For example I can tap by coordinate on all iPads and iPhone 5s or SE but when I try tap on iPhone 6s Plus or Higher nothing happens. I can't understand why. Could you explain me if I'm doing something wrong.
I use default method self.driver.tap([(x, y)])

**Comment by mykola-mokhnach** [comment]
Pushed the fix to appium@beta.

General advice: consider switching to W3C actions to avoid legacy issues
