### ISSUE TITLE
Unable to run test on real iOS device but running on simulator

### ISSUE THREAD

**Issue by siddtiwari** [appium/appium#10597]
## The problem

As I am new to real time device testing, I need your support in resolving an issue which I am facing since long now. I have following issues in iOS devices and simulators:
1. I am able to run my script in simulator but not on real time device.
2. Unable to see WebDriverAgentRunner app on the device, however I have build that app multiple times.
3. My Scrip is able to interact with Appium, it gets installed also but never gets open (In Eclipse it gets failed with error: No element found)

## Environment

* Appium version: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): Not tested
* Desktop OS/version used to run Appium: Mac 10.13.3
* Node.js version (unless using Appium.app|exe): 8.9.4
* Mobile platform/version under test: iOS 6 Plus (11.2.6 Real device) and iOS 6(11.3- Simulator)
* Real device or emulator/simulator: Both
* Appium CLI or Appium.app|exe: Appium CLI

## Details

With the same script i am able to run everything in Simulator iPhone6 (11.2) but not working in real device (even after giving UdID and builded the app again in device) and any other simulator.

## Link to Appium logs

https://gist.github.com/siddtiwari/9f98b74ec775c823ecdb4712a16bd141

Please find the appium logs in this

## Code To Reproduce Issue [ Good To Have ]

Desired Capabilities:
IOSDriver wd = null;
		DesiredCapabilities capabilities = new DesiredCapabilities();
		System.out.println("     ");
		capabilities.setCapability("appium-version", "1.7.2");
		capabilities.setCapability("automationName", "XCUITest");
		capabilities.setCapability("platformName", "iOS");
		capabilities.setCapability("udid", “UDID”); //6Plus
		//capabilities.setCapability("noReset", "true");
		capabilities.setCapability("platformVersion", "11.2.6"); 
		capabilities.setCapability("deviceName", "iPhone 6”); 
		capabilities.setCapability("app",
				“<Path of builded Application.app>”); 

		capabilities.setCapability("bundleID", “<com.bundel id>”);
		wd = new IOSDriver(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);

**Comment by mykola-mokhnach** [comment]
Try to set different `wdaLocalPort` value for each separate device

**Comment by siddtiwari** [comment]
@mykola-mokhnach  shall I mention this in capabilities? Also what can I give the value? Any random value will work?

**Comment by mykola-mokhnach** [comment]
[Here](https://github.com/appium/appium-xcuitest-driver) is the documentation
The main requirement is that the values should be different

**Comment by siddtiwari** [comment]
@mykola-mokhnach Thanks for the info, I believe I moved a step further, but now I am getting the new error (WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65".), however i have followed the steps for webdriveragentrunner configuration in xcode and builded it in the device also. Please guide me on what needs to be done further.
Please find the attached appium logs.


[New APpium log.txt](https://github.com/appium/appium/files/1946153/New.APpium.log.txt)

**Comment by mykola-mokhnach** [comment]
it is an xcodebuild error, that has nothing to do with Appium itself. Try to find issues similar to "dyld: Library not loaded: @rpath/XCTest.framework/XCTest".

**Comment by siddtiwari** [comment]
@mykola-mokhnach could you please elaborate more on this to me, so that I can resolve it.
your help and time would be appreciated.
