### ISSUE TITLE
Android: otherApps - new Added desiredCapabilities doesn't support array

### ISSUE THREAD

**Issue by Doran-Walmart** [appium/appium#10592]
## The problem

It mentioned in the documents https://appium.io/docs/en/writing-running-appium/caps/ that
---
otherApps | App or list of apps (as a JSON array) to install prior to running tests | e.g., "/path/to/app.apk", https://www.example.com/url/to/app.apk, ["/path/to/app-a.apk", "/path/to/app-b.apk"]
---
But when passing a attribute like "otherApps":["./app/gif.apk","./app/sso.apk"], below error were thrown:
---
{ status: 33,
  value: 
   { message: 'A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s): \'otherApps\' must be of type string' },
  sessionId: null }
---

## Environment

* Appium version (or git revision) that exhibits the issue:1.8.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/Doran-Walmart/0a2867b6ee20695ff1d7fc9f1ccf8c92#file-gistfile1-txt

**Comment by mykola-mokhnach** [comment]
> [Appium]   otherApps: {
> [Appium]     0: ./app/gif.apk
> [Appium]     1: ./app/sso.apk
> [Appium]   }

This input does not look like an [array](https://www.w3schools.com/js/js_json_arrays.asp) at all.

**Comment by mykola-mokhnach** [comment]
Try to enclose the value into quotes, like: `"['a', 'b']"`

**Comment by Doran-Walmart** [comment]
Thanks a lot for the quick response @mykola-mokhnach.
Tried the formation as suggested, it seemed that cannot be recognized.
like ...,"otherApps":"['app/sso.apk','app/gif.apk']"...
below error was thrown:
----
15:35:10 [MJSONWP] Encountered internal error running command: Error: The application at '['app/sso.apk','app/gif.apk']' does not exist or is not accessible
----
more details @https://gist.github.com/Doran-Walmart/156a70e967a18a3fb1ae65d28127ed75

**Comment by mykola-mokhnach** [comment]
Replace single quotes with double quotes

**Comment by mykola-mokhnach** [comment]
Also, try to use absolute paths there instead of relative

**Comment by Doran-Walmart** [comment]
Thanks @mykola-mokhnach 
below format worked.
"otherApps":"[\"app/sso.apk\",\"app/barcode-scanning.apk\"]"
Please close the ticket.
