### ISSUE TITLE
Getting "Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65" error when trying to launch ipa app using Appium

### ISSUE THREAD

**Issue by satgh12** [appium/appium#10591]
## The problem

Getting "Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65" error when trying to launch ipa app using Appium

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1 Appium server, 5.0.4 Appium client
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 10.12.6 Mac OS Sierra
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iPhone 6 simulator
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe: Running appium -a 127.0.0.1 -p 4723 from command line

## Details

1. I want to install and launch a ipa file in the simulator as well as the real device.  My Appium code for the simulator is below.  I keep getting the below error.
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65".

I followed the steps mentioned in this link as well which did not help much.
https://github.com/appium/appium-xcuitest-driver/blob/HEAD/docs/real-device-config.md

Log is below.
## Link to Appium logs

https://gist.github.com/satgh12/bf4a65700d89c541052fc35cc3a2caec

## Code To Reproduce Issue [ Good To Have ]

DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 6");
        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "IOS");
        capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.IOS_XCUI_TEST);
        capabilities.setCapability(MobileCapabilityType.APP, "//Users//myname//Desktop//foldername//foo.ipa");
        AppiumDriver driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);

**Comment by imurchie** [comment]
First, you will not be able to automate an IPA on a simulated device. You need to build the app for the simulator, unfortunately.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
