### ISSUE TITLE
Appium script doesn't work on Android version 7+ devices on specific screen for my application.

### ISSUE THREAD

**Issue by vipinAutomation** [appium/appium#10599]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:1.7.1
* Last Appium version that did not exhibit the issue (if applicable):NA
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): 6.9.5
* Mobile platform/version under test: MotoG5 7.0
* Real device or emulator/simulator:Real Device
* Appium CLI or Appium.app|exe:

## Details

I am running appium script on multiple android devices (version 5,6,7) for most of the screen scripts are failing for android version 7 but for few screens, it's working in Android version 7 as well.
The same script is working fine with other devices android version below 7.
## Link to Appium logs

https://gist.github.com/vipinAutomation/9c3afcfb7d838b1951ac166bf6a0f78d

**Comment by mykola-mokhnach** [comment]
"Does not work" is not a clear description of a problem.

Also, it is recommended to use uiautomator2 for Android6+

**Comment by vipinAutomation** [comment]
Can you please check the logs, if you need more things i will provide.

**Comment by KazuCocoa** [comment]
As addressed the above, could you try uiautomator2?
https://appium.io/docs/en/drivers/android-uiautomator2/

The log says you use `uiautomator` (the default value) now. @vipinAutomation

**Comment by vipinAutomation** [comment]
Thanks after using capabilities.setCapability("automationName","UiAutomator2"); the code is working fine for me.
