### ISSUE TITLE
FindElementById does not work in Android when app is switched manually

### ISSUE THREAD

**Issue by vallj** [appium/appium#10593]
## The problem

When app is switched manually, Android Driver is not able to find element by ID. It is still able to find elements in the app by class name, able to get page source, but for some reason it is not able to find the 
 element by ID. The same flow works fine in iOS.

The following flow is not working on android but working on iOS:
Launch app1 using appium
Launch app2 using appium
Manually launch app1
Appium finds elements by class name but does not not find element by ID in Android for app1. Appium finds elements by ID in iOS for app1 without any issue.

The following flow works fine on android.
Launch app1 using appium
Launch app2 using appium
Launch app1 using appium
Appium finds app1 elements in android by ID without issue.

Due to the nature of our scenarios, we have to switch apps manually sometimes, and the android driver is not finding elements by ID in that scenario.

## Environment

Appium version (or git revision) that exhibits the issue: 1.7.2
Last Appium version that did not exhibit the issue (if applicable):
Desktop OS/version used to run Appium: Windows 7
Node.js version (unless using Appium.app|exe): 9.7.1
Mobile platform/version under test: Android OS 8.1.0
Real device or emulator/simulator: Real device Nexus 6P
Appium CLI or Appium.app|exe: CLI

## Link to Appium logs
https://gist.github.com/vallj/45e0d75b1d83b1ec662ef009774e90c7

## Code To Reproduce Issue [ Good To Have ]

    public static AppiumDriver<AppiumWebElement> appDriver = null;
    public static Task _startAppiumServer;

    string appiumServerLogFileName = "AppiumLog_1.txt";
    _startAppiumServer = new Task(() => StartAndroidAppiumServerAndCreateLog(appiumServerLogFileName));
    _startAppiumServer.Start();
     Thread.Sleep(10000);

                DesiredCapabilities capabilities = new DesiredCapabilities();
                capabilities.SetCapability("automationName", "Appium");
                capabilities.SetCapability("platformName", "Android");
                capabilities.SetCapability("noReset", true);
                capabilities.SetCapability("platformVersion", "8.1.0");
                capabilities.SetCapability("deviceName", "Nexus");
                capabilities.SetCapability("appPackage", "com.sjm.crmd.patientApp_Android_USA");
                capabilities.SetCapability("appActivity", "com.sjm.patientApp.android.features.common.base.views.SplashActivity");
                capabilities.SetCapability("newCommandTimeout", "14400");
                capabilities.SetCapability("dontStopAppOnReset", true);                

                appDriver = new AndroidDriver<AppiumWebElement>(new Uri("http://127.0.0.1:4723/wd/hub"), capabilities);

                DesiredCapabilities capabilities2 = new DesiredCapabilities();
                capabilities2.SetCapability("automationName", "Appium");
                capabilities2.SetCapability("platformName", "Android");
                capabilities2.SetCapability("noReset", true);
                capabilities2.SetCapability("platformVersion", "8.1.0");
                capabilities2.SetCapability("deviceName", "Nexus");
                capabilities2.SetCapability("appPackage", "com.android.settings");
                capabilities2.SetCapability("appActivity", "com.android.settings.Settings");
                capabilities2.SetCapability("newCommandTimeout", "14400");
                capabilities2.SetCapability("dontStopAppOnReset", true);

                appDriver = new AndroidDriver<AppiumWebElement>(new Uri("http://127.0.0.1:4723/wd/hub"), capabilities2);

                UserInput.WaitForOkToContinue("Manually launch patient App");
                string sPageSource = appDriver.PageSource;
                ReadOnlyCollection<AppiumWebElement> elements = appDriver.FindElementsByClassName("android.widget.Button");                                
                AppiumWebElement element = appDriver.FindElementById("Home_HistoryButton");
				
				
				
	private void StartAndroidAppiumServerAndCreateLog(string appiumLogFileName)
    {

        System.Diagnostics.Process process = new System.Diagnostics.Process();
        System.Diagnostics.ProcessStartInfo startInfo = new System.Diagnostics.ProcessStartInfo();
        startInfo.WindowStyle = System.Diagnostics.ProcessWindowStyle.Maximized;
        startInfo.FileName = "cmd.exe";        
        startInfo.UseShellExecute = false;
        startInfo.RedirectStandardOutput = true;
        startInfo.RedirectStandardError = true;
        startInfo.RedirectStandardInput = true;
        startInfo.Arguments = "/k (appium --address 127.0.0.1 --port 4723)";
        process.StartInfo = startInfo;
        process.Start();        

        using (FileStream appiumWriteFile2 = new FileStream("C:\\UPTE\\Test Results\\AppiumLog_1.txt", FileMode.Create, FileAccess.Write, FileShare.ReadWrite))
        using (StreamWriter appiumWriter2 = new StreamWriter(appiumWriteFile2))
        {
            while (!process.StandardOutput.EndOfStream)
            {
                var appiumOutput2 = process.StandardOutput.ReadLine();
                if (appiumOutput2 != null)
                {
                    appiumWriter2.WriteLine(appiumOutput2);
                    appiumWriter2.Flush();
                }
            }

        }

    }

**Comment by mykola-mokhnach** [comment]
Try to use UIAutomator2 as automation backend

**Comment by vallj** [comment]
@mykola-mokhnach 
Even after using uiautomator2 as automation name, it still doesn't identify the element by Id in the scenario I explained above. 
Log - https://gist.github.com/vallj/0698c843dcbc7fe4cd7420c8dc0f91e8

**Comment by mykola-mokhnach** [comment]
Can you also attach the logcat output?

**Comment by vallj** [comment]
logcat output

[ADBLogcat.txt](https://github.com/appium/appium/files/1952833/ADBLogcat.txt)

**Comment by mykola-mokhnach** [comment]
I don't observe any explicit issues in the log. It is, most likely, an issue with UIAutomator framework itself and should be reported to Google.
