### ISSUE TITLE
App crashed with appium 1.8

### ISSUE THREAD

**Issue by speesystack-chentianyu** [appium/appium#10600]
## The problem
My test works with appium 1.7.2. After updating to appium 1.8, the app I'm testing crashes soon after getting launched.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2
* Desktop OS/version used to run Appium: Windows 10 64bit
* Node.js version (unless using Appium.app|exe):  v8.11.1
* Mobile platform/version under test:  Android 7.1 / Android 5.1
* Real device or emulator/simulator: Both real device && simulator
* Appium CLI or Appium.app|exe: Appium.exe

## Details

It seems that the apk file in my computer gets modified by appium 1.8. There is something wrong with that modification, as the modified apk crashes just seconds after launch. I have tried to manually install the modified apk and launch the app, the crash is still the same.

I have gone back to appium 1.7.2 and replaced the modified apk with the original one. Then everything goes fine and the app no longer crashes.

I have noticed that the apk file itself in my computer does not get modified in version 1.7.2. In appium 1.8 however, both the size and time-of-modification changes. I don't know whether this is the new way around or it is just another bug. Any way, it is really a bad idea to directly modify the apk file rather than making a copy first and then making modifications to the copy.

## Link to Appium logs
[https://gist.github.com/speesystack-chentianyu/df258d348311294bda10a3f9b431baa7](https://gist.github.com/speesystack-chentianyu/df258d348311294bda10a3f9b431baa7)

The modified apk file is about 7KB larger than the original one. According to the log file, the session ends because of incorrect package or activity names. However, the same package and activity names work with apppium v1.7.2.
After the session ends, I have tried to manually open the installed app on my phone, and it craches within 2 seconds.

**Comment by mykola-mokhnach** [comment]
Sorry, I cannot advice anything without having server and device logs.

**Comment by speesystack-chentianyu** [comment]
@mykola-mokhnach Thanks for the reply, I've added the appium logs in the post now.

**Comment by mykola-mokhnach** [comment]
The application is modified, because it must be signed with debug certificate in order to be executed under instrumentation.

This is the line, where the modification is performed:

> [debug] [ADB] Starting 'C:\Users\chent\AppData\Local\Android\Sdk\build-tools\28.0.0-rc1\apksigner.bat' with args 'sign,--key,C:\Users\chent\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\keys\testkey.pk8,--cert,C:\Users\chent\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\keys\testkey.x509.pem,C:\s\app.apk'

I'm not sure though why the app crashes after that.

**Comment by mykola-mokhnach** [comment]
yes, it was a bug in 1.7.2, since we'd like to verify if the app is signed exactly with Appium's test certificate and not with any other one.

**Comment by speesystack-chentianyu** [comment]
@mykola-mokhnach 
Is it true that the app should be signed with Appium's test certificate because the test will not work otherwise?
It is strange that my test works fine in v1.7.2 with the wrong certificate and crashes in v1.8.0 with the right certificate.

**Comment by speesystack-chentianyu** [comment]
After reading another post [Why DOES Appium sign the .apk? Are there any benefits?](https://discuss.appium.io/t/why-does-appium-sign-the-apk-are-there-any-benefits/7434), now I understand why my test works fine without the signing process.

**Comment by mykola-mokhnach** [comment]
Yep, you can also try noSign capability and see if it helps

**Comment by cisum-la** [comment]
I tried noSign = true with 1.8 and having the same issue as above with a slightly different behavior. For me, i can launch the app installed by Appium on Android 6, but the test crashes (cannot launch App) with Appium 1.8. With Appium 1.7.2 the same test runs successfully. 

In process of uploading Appium logs

**Comment by mykola-mokhnach** [comment]
@cisum-la noSign capability only works for uia2 backend

**Comment by cisum-la** [comment]
@mykola-mokhnach I reran the test in Appium 1.8 with automationName=UiAutomator2, but encountered the same crash as with automationName=Appium, i updated the Appium logs:
https://gist.github.com/cisum-la/40a5e18af6d813c9a1a1abe37f917779

Which shows automationName=UiAutomator2 and noSign=true

**Comment by mykola-mokhnach** [comment]
Which crash? I don't see any crashes in the recent log

**Comment by cisum-la** [comment]
After more investigation I found that the App is indeed not crashing in 1.8, but gives an illusion of crash as the App opens and closes very quickly. What's happening is that 

wait.until(ExpectedConditions.visibilityOf(UIElement));

is not waiting as in 1.7.2 , when i added a Thread.sleep(2000) before it then the test passed.


Note that in page constructor i have below command:
wait = new WebDriverWait(driver, 15);

Has something changed w.r.t above command in 1.8 vs 1.7.2, as the same test passes by only changing Appium version to 1.7.2 (keeping everything else exactly the same).
