### ISSUE TITLE
Getting "Unable to launch WebDriverAgent because of xcodebuild failure: "Unable to start iproxy. Is it installed?"

### ISSUE THREAD

**Issue by satgh12** [appium/appium#10604]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1 Appium server, 5.0.4 Appium client
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 10.12.6 macOS sierra
* Node.js version (unless using Appium.app|exe): 6.11.4
* Mobile platform/version under test: iPad Air 2, iOS 11.3
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI using appium -a 127.0.0.1 -p 472

## Details

Getting "Unable to launch WebDriverAgent because of xcodebuild failure: "Unable to start iproxy. Is it installed?"
NOTE:
1. I already ran the following:
    npm install -g iproxy
    brew install libimobiledevice--HEAD
    Installed carthage
    npm install -g ios-deploy
2. Made sure that all targets under WebDriverAgent (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent) have valid signing certificates.
3. Followed the steps of "Full Manual configuration" from https://github.com/appium/appium-xcuitest-driver/blob/HEAD/docs/real-device-config.md 
4. I can see the app getting installed, but it cannot launch

## Link to Appium logs

https://gist.github.com/satgh12/8cf1f87c911afb3b16af0b670a253ca9

## Code To Reproduce Issue [ Good To Have ]

DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Smart iPad");
capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "IOS");
capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.IOS_XCUI_TEST);
capabilities.setCapability(MobileCapabilityType.UDID, "4b4ed722ef97d01a3dd6555215ef0b5624161fc5");
capabilities.setCapability(MobileCapabilityType.APP, "//Users//myName//Desktop//myFolder//foo.ipa");
AppiumDriver driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);

**Comment by mykola-mokhnach** [comment]
What is the output of `which iproxy`?

**Comment by satgh12** [comment]
/usr/local/bin/iproxy

**Comment by mykola-mokhnach** [comment]
Is the server environment configured properly?
https://github.com/appium/java-client/blob/master/docs/environment.md

**Comment by satgh12** [comment]
iproxy is in /usr/local/bin
$PATH shows /usr/local/bin.  See below.  Is this what you are referring to?

echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS:/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/bin:/Users/myName/Downloads/android-sdk-macosx/tools:/Users/myName/Downloads/android-sdk-macosx//tools/bin:/Users/myName/Downloads/android-sdk-macosx/platform-tools:/usr/local/lib:/usr/local/lib/node_modules/npm/bin:/Users/myName/Downloads/apache-maven-3.5.0/bin

**Comment by satgh12** [comment]
In /usr/local/bin, I see a symbolic link to iproxy

iproxy -> ../Cellar/usbmuxd/1.0.9/bin/iproxy

**Comment by satgh12** [comment]
Also, tried changing the Bundle identifier of WebDriverAgentRunner to io.appium.WebDriverAgentRunner and rebuilt WebDriverAgent project

![image](https://user-images.githubusercontent.com/20153848/39262285-d35a366e-4873-11e8-9a6b-7d890e293be3.png)

**Comment by Warren25** [comment]
@satgh12 have you used 'io.appium.WebDriverAgentRunner' as a bundle id name before? If so, you'll have to use a different name

**Comment by satgh12** [comment]
I read the document and not sure how to apply that to the error I am encountering.  Can you please be clear a bit more?  How can I apply the server process environment in my case?

**Comment by mykola-mokhnach** [comment]
What is the command output if you execute iproxy manually?

`iproxy 8100 8100 <device_udid>`

**Comment by satgh12** [comment]
iproxy 8100 8100 4b4ed722ef97d01a3dd6555215ef0b5624161fc5
usage: iproxy LOCAL_TCP_PORT DEVICE_TCP_PORT

Also, tried running brew install usbmuxd && brew link usbmuxd

_**Error: Could not link:
/usr/local/share/doc/homebrew



Please delete these paths and run `brew update`.
Warning: usbmuxd 1.0.10_1 is already installed, it's just not linked
You can use `brew link usbmuxd` to link this version.
Linking /usr/local/Cellar/usbmuxd/1.0.10_1... 
Error: Could not symlink bin/iproxy
Target /usr/local/bin/iproxy
is a symlink belonging to usbmuxd. You can unlink it:
  brew unlink usbmuxd

To force the link and overwrite all conflicting files:
  brew link --overwrite usbmuxd

To list all files that would be deleted:
  brew link --overwrite --dry-run usbmuxd**_


Just running 
**_brew link usbmuxd
Linking /usr/local/Cellar/usbmuxd/1.0.10_1... 
Error: Could not symlink bin/iproxy
Target /usr/local/bin/iproxy
is a symlink belonging to usbmuxd. You can unlink it:
  brew unlink usbmuxd

To force the link and overwrite all conflicting files:
  brew link --overwrite usbmuxd

To list all files that would be deleted:
  brew link --overwrite --dry-run usbmuxd_**

**Comment by mykola-mokhnach** [comment]
> brew link --overwrite usbmuxd

Will be your solution

**Comment by satgh12** [comment]
Yes, that worked like a charm.  Thanks a lot, Mykola.  We can close this issue.  Appreciate all your help.
