### ISSUE TITLE
Testing with YouiEngineDriver throws error

### ISSUE THREAD

**Issue by DeepikaThiru** [appium/appium#10601]
## The problem

when tried to automate the app with youiengine driver its throwing error like below even when i connect my system and mobile to the same network

**[YouiEngineDriver] Attempt #1
[YouiEngineDriver] Connecting to WebDriver: 100.90.73.3:12345
[YouiEngineDriver] Error: connect ENETUNREACH 100.90.73.3:12345
[YouiEngineDriver] Waiting 3 seconds before trying...
[YouiEngineDriver]     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)
[YouiEngineDriver] Check that WebDriver is enabled in application, if a device ensure the proper IP address is used.
[YouiEngineDriver] Connection closed**

## Environment

* Appium version (or git revision) that exhibits the issue:1.8.0
* Node.js version (unless using Appium.app|exe):8.11.1
* Mobile platform/version under test:6.0
* Real device or emulator/simulator:real device
* Appium CLI or Appium.app|exe:Appium CLI

## Details
these are the values that i set for capabilities
youiEngineAppAddress=100.90.73.3
automationName=YouiEngine
platformVersion=6.0

**Comment by mykola-mokhnach** [comment]
Is that IP address and port reachable?

**Comment by DeepikaThiru** [comment]
Sorry for late reply @mykola-mokhnach Yes its reachable

**Comment by DeepikaThiru** [comment]
Ohkk will check my firewall and application thank you

**Comment by DeepikaThiru** [comment]
@mykola-mokhnach I checked my IP and PORT and could see that it works
