### ISSUE TITLE
Running xcodebuild on WebDriverAgent is failing the tests because of 'Could not obtain the bundle identifier for '*.app'''

### ISSUE THREAD

**Issue by satgh12** [appium/appium#10606]
## The problem

Running xcodebuild on WebDriverAgent is failing the tests because of 'Could not obtain the bundle identifier for '*.app'''

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1 Appium server.  
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 10.12.6 Mac OS Sierra
* Node.js version (unless using Appium.app|exe): 6.11.4
* Mobile platform/version under test: iPhone 6 plus (11.2.6)
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

Running xcodebuild on WebDriverAgent is failing the tests because of 'Could not obtain the bundle identifier for '*.app'''

## Link to Appium logs

https://gist.github.com/satgh12/21feaa1671b507bdec86a3ab9f7ca554

## Code To Reproduce Issue [ Good To Have ]

xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' test

**Comment by mykola-mokhnach** [comment]
This is an xcode compilation problem, which happens, most likely, because of invalid/damaged application package. It has nothing to do with Appium
