### ISSUE TITLE
How to check whether the app is launched successfully or not in android real device using appium driver

### ISSUE THREAD

**Issue by Elangopalakrishnan** [appium/appium#10607]
## The problem

I'm facing the issue like, I'm launching and re-launching the my native app in android real devices.

AppDriver = new AndroidDriver<AppiumWebElement>(new Uri("http://" + AppiumIPAddress + ":" + AppiumPort + "/wd/hub"), DesiredCaps, TimeSpan.FromSeconds(300));

After above line, my app is launching successfully, But after few seconds app is closing due to my app issue not code issue. App is not good. it is happening inconsistently.

So i need to check Whether my app is launched successfully or my app is in active in android device.

Like we are using AppDriver.IsAppInstalled(budle Id); .... Like this i need to check App is launched or active in my real device....

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2
* Desktop OS/version used to run Appium: Windows 7
* Node.js version (unless using Appium.app|exe): 8.11.1
* Mobile platform/version under test: Samsung S5 
* Real device or emulator/simulator: Real Device
* Script: C#

Please share your thoughts ..... Is there any way to find out this???

Thanks in advance!
Elango

**Comment by tfcardoso** [comment]
Take a look at:
http://appium.io/docs/en/writing-running-appium/ios/ios-xctest-mobile-apps-management/index.html#mobile-queryAppState

**Comment by mykola-mokhnach** [comment]
@tfcardoso These endpoints are only available for xcuitest driver. 

There are more general functions in the recent java client BETA, which works for both Android and iOS:
https://github.com/appium/java-client/blob/c4222d80e5fe1bc53c47cba5f44bd8ec6e5d50b6/src/test/java/io/appium/java_client/android/AndroidDriverTest.java#L200

Please use appium forum to ask questions
