### ISSUE TITLE
Unable to launch the app on iOS simulator , App gets opened and closed immidiately

### ISSUE THREAD

**Issue by varun2810** [appium/appium#10602]
## The problem
I'm using 3
App is not getting opened as it just opens up and closes immediately just showing the splash screen

## Problem

 I just started a new session to get the appium inspector , but the app gets installed into the simulator and its not getting opened. It is just opens up and closes immediately. Where as in real device it runs fine.
In simulator it shows the error. 

These are my capabilities : 
{
  "platformName": "iOS",
  "deviceName": "iPhone 8 Plus",
 "platformVersion" : "11.3",
  "udid": "E42E0165-4D96-4DF4-98C1-1C360404500A",
  "app": "/Users/varun-6182/Desktop/drivers/ZohoChat.ipa",
  "automationName": "XCUITest"
}

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): As i'm using appium for iOS first time
* Desktop OS/version used to run Appium: 1.7.2
* Node.js version (unless using Appium.app|exe): 9.4.0
* Mobile platform/version under test: iPhone 8 plus simulator
* Real device or emulator/simulator: Simulator [iOS 11.3]
* Appium CLI or Appium.app|exe: Appium desktop 

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
You cannot use the same binary on Simulator and real devices.

Closed as not an issue

**Comment by varun2810** [comment]
@mykola-mokhnach Can you please explain me the case on same binary on simulator and real devices. i have successfully done automation for android , but i got struck in iOS

**Comment by varun2810** [comment]
i don't understand what the term same binary refers to.

**Comment by varun2810** [comment]
i have seperate capabilities for simulator and device
