### ISSUE TITLE
Class cast exception with Appium 1.8.0

### ISSUE THREAD

**Issue by faran** [appium/appium#10605]
Details
Started getting this after updating to the latest java client and Appium server
(Double checked by downgrading to Appium 1.7.2 and no problems)

Environment
6.0.0-BETA5
1.8.0
macOs Sierra
node 8.5.0
iOS 11.2.6
iPhone 6 Plus , real device

Exception
java.lang.ClassCastException: org.openqa.selenium.remote.RemoteWebElement cannot be cast to io.appium.java_client.MobileElement

Link to Appium logs
https://gist.github.com/faran/751537973490208cb7ad2213c7f3cdbc

**Comment by mykola-mokhnach** [comment]
This error has nothing to do with appium server. You're most likely trying to use some outdated libs.

Closed as client side issue.
