### ISSUE TITLE
driver.current_activity sometimes returns None, but activity can get from adb command(using Python binding)

### ISSUE THREAD

**Issue by loveiset** [appium/appium#10608]
## The problem

I test my app as following:
1. launch app under tested
2. goto app's main page(thus activity `com.hrt.platform.activity.MainActivity`), at this time it returned current activity correctly.
3. do some other test, and go back to main page
4. I tried to get current activity, it returned None

when this problem occured, I tried get activity from adb command line, it showed me the correct activity.

## Environment

* Appium version: 1.8.0
* OS/version: win7 64 SP1
* Node.js version: v8.11.0
* Mobile platform/version under test: Android 6.0.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: `appium --session-override --no-reset --chromedriver-executable D:\hcs\Downloads\chromedriver_win32\chromedriver.exe ---log-level info --log D:\appium.log`

### packet captured
```
http://127.0.0.1:4723/wd/hub/session/ba202fd0-2425-40ad-b0f9-fce702b8cd8d/appium/device/current_activity
returns
{"status":0,"value":null,"sessionId":"ba202fd0-2425-40ad-b0f9-fce702b8cd8d"}
```

### adb logs(if helpful)
[adb logs](https://gist.github.com/loveiset/6a779660173f8a374e0d7e32c78c116c)

### activity get from adb command
```
adb shell dumpsys activity | grep -i run
    Running activities (most recent first):
        Run #3: ActivityRecord{a371128 u0 com.crc.hrt/com.hrt.platform.activity.MainActivity t3496}
        Run #2: ActivityRecord{4957f99 u0 com.android.settings/.inputmethod.InputMethodAndLanguageSettingsActivity t3491}
        Run #1: ActivityRecord{41e5c5f u0 com.android.settings/.Settings t3491}
        Run #0: ActivityRecord{7dbd8c3 u0 com.willme.topactivity/.MainActivity t3466}
    Running activities (most recent first):
        Run #0: ActivityRecord{f94db8d u0 com.android.launcher3/.Launcher t3455}
ACTIVITY MANAGER RUNNING PROCESSES (dumpsys activity processes)
    User #0: mState=RUNNING
```
**`com.hrt.platform.activity.MainActivity`** is my expected activity

## Link to Appium logs

[link to log](https://gist.github.com/loveiset/4fcb25b520c8a136632b06eca0ea56d4)

**Comment by mykola-mokhnach** [comment]
The focused activity detection algorithm in Appium is a bit more complicated than that:
https://github.com/appium/appium-adb/blob/c49cb460839a7e5e3265812e54a2b02fe231460d/lib/tools/apk-utils.js#L142

**Comment by loveiset** [comment]
emmm... so what infomation does I provide, I run into this issue everytime I run this testcase. @mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
The regexp that we use for activity detection might have issues. Try to match your actual output to it and see if it returns correct results

**Comment by loveiset** [comment]
I add some code to get the output,
```javascript
_loggerJs2['default'].debug("testoutput====:"+stdout.split("\n").join("||"));
// logs output
_loggerJs2['default'].debug("package:"+foundMatch[1].trim());
_loggerJs2['default'].debug("activity:"+foundMatch[2].trim());
// get the result activity, but this code never executed
return context$1$0.abrupt('return', { appPackage: foundMatch[1].trim(), appActivity: foundMatch[2].trim() });
```
this this issue occurs, package and activity doesn't print anything, that means it did not go to the retun code, so the current activity result is None.

detail of the output is [here](https://gist.github.com/loveiset/53b83669908dd8d79b674beedae9dea9) I just replace any `\n` to `||`

hope these infomation do some help @mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
It seems the result is correct because `mFocusedApp=null` in your example. @vmaxim Can you please take a look?

**Comment by vmaxim** [comment]
@loveiset Are you able to repro this issue on other [devices|emulators]? Maybe this related to the particular device, because logcat output seems odd to me (custom rom?).

[WindowManagerService.java](https://android.googlesource.com/platform/frameworks/base/+/master/services/core/java/com/android/server/wm/WindowManagerService.java)

```
04-26 14:54:36.805  1325  1597 D WindowManager: null is detected

**Comment by loveiset** [comment]
I use another phone and tyr this case, it gets the correct activity, maybe it is an issue related to specfic model? The phone I use is SM901(os version v3.2.7, android 6.0.1).
but I wonder why in most condition the activity can return correctly, only in this paticular testcase it performs incorrct. @vmaxim

**Comment by mykola-mokhnach** [comment]
I've recently added activity detection by `mCurrentFocus` value. Perhaps, this might help. Check it in appium@beta @loveiset when the next version of appium-adb module is published

**Comment by vmaxim** [comment]
> but I wonder why in most condition the activity can return correctly, only in this paticular testcase it performs incorrct. @vmaxim

[Smartisan_OS](https://en.wikipedia.org/wiki/Smartisan_OS) is a custom rom - I don't know what might be broken there.
