### ISSUE TITLE
Unable to click the webview element in hybrid app using webdriver

### ISSUE THREAD

**Issue by DarshanLoga** [appium/appium#10612]
## The problem
Unable to click my hybrid app web view element using web driver click event. I tried some appium event but not succeed it(even switch to native context to click the element and back to webview context).

I could not click any element in my app using Webdriver. Please provide the solution to click my app element.

Using appium action
1. driver.tap(2, 540, 1000, 50);
2. driver.tap(x, ele, y);
3. TouchActions action = new TouchActions(driver);
action.singleTap(element);
action.perform();

## Environment
* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): 1.7.1
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: 6.0
* Real device or emulator/simulator: Emulator, Nexus 5
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Code To Reproduce Issue [ Good To Have ]

Below codes are used, but not succeed,

1. JavascriptExecutor js = (JavascriptExecutor)driver;
                js.executeScript("window.document.getElementById('.language-filter-container').click()");

2.            Point loc = element.getLocation();
                int x = loc.getX ();
                int y = loc.getY ();
                TouchActions action = new TouchActions(driver);
                switchToWebViewContext ("NATIVE_APP");
                action.singleTap (element);
                action.perform();

3.        switchToWebViewContext ("NATIVE_APP");
            driver.tap(2, 250, 500, 50);
            // Switch to Webview context after tap the subject
            switchToWebViewContext("WEBVIEW");

**Comment by liviudanu-ellation** [comment]
@Logakarti , can you provide some logs?

**Comment by Logakarti** [comment]
Appium log:
https://gist.github.com/Logakarti/cede9be4f00efa4aa6c1d0048a60ab00

FYI:
My app element has made with "touchend" event instead of "click" event. For this reason, I could not click the app element using webdriver. Please give me a solution to click the app element using appium.

But I can click my app element using Jquery 
**((JavascriptExecutor) webDriver).executeScript("$($(\".language-filter-container\")).trigger(\"touchend\")");**

**Comment by liviudanu-ellation** [comment]
Do you mean, that the element could not be clicked due to your app specific behavior?

**Comment by Logakarti** [comment]
I think it is specific. One of my other apps, the elements are clicked successfully without issue.

I think above problem occurs due to elements has wrapped with "touchend" event instead of click.

**Comment by liviudanu-ellation** [comment]
Well, I have never encountered such an issue, can't help you, sorry.
You can ask your devs to make some changes, maybe they can help you.

**Comment by Logakarti** [comment]
Thanks for the update

**Comment by Shikha3290** [comment]
Hi, 

Could anyone find a solution for this? I'm facing the same problem. Not able to click/tap on the element with touchend event. Devs say that they explicitly need the touchend event there so can't make changes. I'm trying to click the current location icon.

Thanks

**Comment by mykola-mokhnach** [comment]
https://appiumpro.com/editions/36

**Comment by ssmalan94** [comment]
Hello, @mykola-mokhnach  I've made use of this "nativeWebTap" Capability and tried to click the WebView element after switching to WebView but the action is not happening with the Element. Could you please help here. please find the logs attached here.
[appium-server-logs.txt](https://github.com/appium/appium/files/2787566/appium-server-logs.txt)
