### ISSUE TITLE
XCUI Picker value selection is not working

### ISSUE THREAD

**Issue by sebinjqburst** [appium/appium#10617]
## The problem

On selecting the picker value using driver.findElementsByClassName(PICKERWHEEL).get(0).sendKeys(heightFtValue) , the same is just selecting the next value instead of the value I had given.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0
* Last Appium version that did not exhibit the issue (if applicable): 1.8.0 - beta5
* Desktop OS/version used to run Appium: macOS Sierra
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

**Comment by mykola-mokhnach** [comment]
We don't have control over this behaviour. Please report to https://github.com/facebook/WebDriverAgent
