### ISSUE TITLE
Error installing Chromedriver binary Appium 1.8.0

### ISSUE THREAD

**Issue by Pr60** [appium/appium#10615]
## The problem

I'm unable to install appium through command line. The problem seems to be the chrome driver binary which is a part of the appium installation process. 

## Environment

* Desktop OS/version used to run Appium: Mac OSX High Sierra
* Node.js version :  10.0.0
* npm version: 5.6.0
* Appium CLI: latest version available

## Link to Appium logs

https://gist.github.com/Pr60/d83bba7bc6471058f51ac7b4fa76a5d2

## Code To Reproduce Issue 

Command used to install appium:
npm install -g appium

**Comment by dpgraham** [comment]
Can you try installing `npm install -g appium@1.7.2`?

I'd like to know if it was something introduced in 1.8.0 that's causing this issue.

**Comment by dpgraham** [comment]
Oh, I just noticed you're using node 10.0.0... we've had some issues with that.

Can you try downgrading to 9 and see what happens? (I recommend using [NVM](https://github.com/creationix/nvm) to easily switch between Node versions)

**Comment by Pr60** [comment]
Thanks for your information. The node version was the issue. I downgraded my node version to 8.11.1 and used appium version 1.8.0.

**Comment by dpgraham** [comment]
Okay thanks for reporting this issue. 

I'm going to close this since Node v10 support is a known issue already.

**Comment by priyankshah217** [comment]
Even I faced the same issue, downgrade node version by 

- Uninstall node `brew uninstall node`

- Install node lower version of node `brew install node@8`

- Do force link to node 8 `brew link --overwrite node@8 --force`

It will work.

**Comment by swapnilrasam28** [comment]
@dpgraham: Tried installing appium@1.7.2 on my corporate machine, but i am facing **Maximum call stack size exceeded**

I have configured the http and https proxy but still it doesn't work
I am having the below versions:

Node.js v8.10.0
npm v5.6.0
