### ISSUE TITLE
--suppress-adb-kill-server not working...

### ISSUE THREAD

**Issue by myso-kr** [appium/appium#10610]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Are you sure the device is visible after adb server is killed?

**Comment by mykola-mokhnach** [comment]
Appium was never tested to support connections over WiFi. You're welcome to create a PR if you see bugs there.

**Comment by myso-kr** [comment]
Hi, @mykola-mokhnach 

I finded trick on Appium for WiFi ADB.
I hope it helps those who are experiencing the same issue.

```
import WDIO from 'webdriverio';
import * as Appium from 'appium';
import * as AppiumADB from 'appium-adb';

Promise.resolve()
// Appium Start
.then(() => Appium.main())
// Appium ADB WiFi Connect
.then(() => AppiumADB.createADB())
.then(async (adb) => {
  await adb.adbExec(['connect', '192.168.35.123:5555'])
})
// Appium Test Code
.then(() => {
  /* WebDriver code (wd or wdio) */
})
```

and, solved "suppress-adb-kill-server" issue.

https://github.com/myso-kr/appium-android-driver/commit/0e51f82f1bf480c6e5d69277e73e30c2a0ac399b

**Comment by mykola-mokhnach** [comment]
We'd happy to see a PR from you
