### ISSUE TITLE
Function app_strings return empty string table since minSDK of app change from 19 to 21

### ISSUE THREAD

**Issue by haihoangtran** [appium/appium#10619]
## The problem

app_strings(<language code>, none) returns an empty string table for this language when minSDK of app is set to 21. It is still worked well when minSDK is 19. Nothing is changed in the app besides minSDK.

## Environment
* Appium version (or git revision) that exhibits the issue: 1.8.0
* Last Appium version that did not exhibit the issue (if applicable): 1.8.0
* Desktop OS/version used to run Appium: Ubuntu
* Node.js version (unless using Appium.app|exe): v7.2.1
* Mobile platform/version under test: Android / 6.0.1, 7.0, and 8.1
* Real device or emulator/simulator: Real device LG G5, Nexus 6P
* Appium CLI or Appium.app|exe:
* Language in test: Python

## Details
When App is set 19 as minSDK. Function app_strings(<language code>, none)  return a string table well. However, when app change minSDK to 21. It is return empty string table with the same language.

Would you please see attached .txt files for 2 Appium logs, minSDK21 and minSDK19

## Link to Appium logs
[minsdk21_log.txt](https://github.com/appium/appium/files/1957059/minsdk21_log.txt)
[minsdk19_log.txt](https://github.com/appium/appium/files/1957063/minsdk19_log.txt)

## Code To Reproduce Issue [ Good To Have ]
dc = {"app": cfg.get("APP", "aio-package"),
      "appWaitActivity": AIO_ACTIVITY.WAIT_ACTIVITY,
      'appPackage': PACKAGE.AIO_PACKAGE,
      'appActivity': AIO_ACTIVITY.LAUNCH_ACTIVITY,
      'fullReset': "true",
      'unicodeKeyboard': "true",
      'resetKeyboard': "true",
      'setWebContentsDebuggingEnabled': "true",
      'automationName': "uiautomator2"}
app = MobiEzApp(cfg=cfg, desired_capabilities=dc)
print app.app_strings("en-US")

**Comment by mykola-mokhnach** [comment]
Do you see the strings in the `aapt d --values resources <apkpath>` output? Under which locale they are visible?

**Comment by mykola-mokhnach** [comment]
Btw, I see you use Appium 1.7.2 instead of 1.8.0

**Comment by haihoangtran** [comment]
I tried to upgrade to Appium v1.8.0. I can get string table with uiautomator. If I use uiautomator2, It got an error:
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET

Log of appium is following:
[appium_logs.txt](https://github.com/appium/appium/files/1961822/appium_logs.txt)

**Comment by mykola-mokhnach** [comment]
The recent error has nothing to do with application strings.

**Comment by haihoangtran** [comment]
This error relate to uiautomator2 on version 1.8.0. When I execute test with uiautomator, it works well, but when I change my test to uiautomator2, It got error as above.

**Comment by Jiurong-Yang** [comment]
The error comes from the appium_apk_tool being out of date. I see that there is an effort in changing how appium get app_strings. Maybe the uiautomator2 driver is still using the old hooks?

**Comment by Jiurong-Yang** [comment]
Actually. I tried this with the latest master build of appium and uiautomator2. It's working. So I'm sure if @haihoangtran delete the node_module and reinstall appium it'll fix any inconsistencies.

**Comment by haihoangtran** [comment]
It is not worked when reinstalling appium. Any helps on issue Error: read ECONNRESET when I used uiautormator2 on appium v1.8.0

**Comment by mykola-mokhnach** [comment]
Delete all appium helpers and server components from the device under test (or reset it to make sure you didn't forget anything) and try again
