### ISSUE TITLE
Xcode 65 error message. Can't run tests on Real iOS device

### ISSUE THREAD

**Issue by garkinv** [appium/appium#10613]
## The problem

During running my tests on real iOS device I get error message: "Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device."

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Node.js version (unless using Appium.app|exe): 9.11.1
* Mobile platform/version under test: 11.3
* Real device or emulator/simulator: Real device, iPhone 6s
* Xcode 9.3
* MacOS 10.13.4

## Details

I signed xcode project according to this guide - https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md and I do it a lot of time for previous appium version and it worked fine.

First warning I got is warning in Xcode:
` CodeSign /Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app/Frameworks/XCTAutomationSupport.framework
    cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    
Signing Identity:     "iPhone Developer: Vladimir (5PU******)"

/usr/bin/codesign --force --sign 79***********E952715F6610F2ACF88F43116DF6 --deep --preserve-metadata=identifier,entitlements,flags --timestamp=none /Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app/Frameworks/XCTAutomationSupport.framework

/Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app/Frameworks/XCTAutomationSupport.framework: replacing existing signature
Warning: unable to build chain to self-signed root for signer "iPhone Developer: Vladimir (5PU******)"Warning: unable to build chain to self-signed root for signer "iPhone Developer: Vladimir (5PU******)"Warning: unable to build chain to self-signed root for signer "iPhone Developer: Vladimir (5PU******)" `

When I try to run command: xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' test

I got this errors - https://gist.github.com/garkinv/645d72033217fdb454ca9a357d8ff357

## Link to Appium logs

https://gist.github.com/garkinv/b5842b61b98f0e621bf5eb5bd0749609

## Tried solutions

1. Tried to revoke certificate and apply new one with relogin to xcode
2. Tried to reinstall appium from scratch
3. Updating Build Phases with linked libraries when they were absent like YYCache and RoutingHTTPServer
4. Reviewed all issues in Appium with 65 error message and didn't find valid solution for me.

**Comment by mykola-mokhnach** [comment]
try https://github.com/facebook/WebDriverAgent/issues/902#issuecomment-383362376

**Comment by garkinv** [comment]
@mykola-mokhnach  thanks for suggestion, now I got another error
https://gist.github.com/garkinv/3fc5e97daa93a084094761ee183cc584

**Comment by garkinv** [comment]
I solved my issue after - I untrusted all manually trusted developer and root certificates in keychain.
All certificates should be - Use system defaults.
