### ISSUE TITLE
How to write the Page Object Model file in node.js for automation mobile testing

### ISSUE THREAD

**Issue by Saifalip** [appium/appium#10624]
## The problem

I have added the code for Page Object Model to run test script but the test cases is just passing without opening the app.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Node.js version (unless using Appium.app|exe): 9.1.0
* Mobile platform/version under test: iOS 
* Real device or emulator/simulator: Simulator

## Details

I am not able to run script for mobile app testing using Page Object Model

## Code To Reproduce Issue [ Good To Have ]
This is my SuccessfulLogin.js page:

require("../../helpers/base");
const driver = require("../../helpers/driver");
const Login = require("../../ui/Login");

module.exports = (options) => {
	describe("Login: SuccessFul Login", function SuccessfulLoginTest() {
		this.timeout(900000);

		it("Verify in Login screen, Successful Login", function (driver) {
			Login.getPreSignin(driver).click();
			Login.getEmailTextBox(driver).sendKeys("Test@loxa.com");
			Login.getPasswordTextBox(driver).sendKeys("password");
			Login.getSubmitButton(driver).click();
			driver();
		});
	});
};

I am calling in this file Login.js

require("../helpers/base");
// let driver = "";
const driver = require('../helpers/driver');

module.exports = {

	getPreSignin: (driver) => {
		return driver.elementById("SIGN IN");
	},
	getEmailTextBox: (driver) => {
		return driver.elementById("emailTextField");
	},
	getPasswordTextBox: (driver) => {
		return driver.elementById("passwordTextField");
	},
	getSubmitButton: (driver) => {
		return driver.elementById("signInButton");
	}
};

Could any one solve my issue please

**Comment by mykola-mokhnach** [comment]
Please use Appium forum to ask questions

**Comment by Saifalip** [comment]
@mykola-mokhnach you have any idea about Page object model
