### ISSUE TITLE
Appium 1.7.1 installation freezes in macOS

### ISSUE THREAD

**Issue by sunil-sahoo** [appium/appium#10626]
## Appium installation using npm freezes at the package(bluebird@3.5.0).

I am trying to install appium@1.7.1 in mac(10.11) with node(7.5.0) and npm(4.1.2) installed using brew. But while installing appium@1.7.1 and appium@1.7.2 , it freezes at a package(bluebird). 
Command used - npm install -g appium@1.7.1 , npm install -g appium@1.7.2 

The latest Appium@1.8 is getting installed.

## Environment

* Appium version - 1.7.1, 1.7.2
* Desktop OS/version - OS X (10.11)
* Node.js version - 7.5.0
* NPM version - 4.1.2

**Comment by mykola-mokhnach** [comment]
This does not look an Appium issue to me
