### ISSUE TITLE
longPressKeycode presses the Keycode twotimes

### ISSUE THREAD

**Issue by kumarswamy757** [appium/appium#10622]
## The problem

I want to longpress a key on the Keyboard. So i used longPressKeyCode. But longPressKeyCode presses any key two times.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2 and 1.8.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Tried both in Linux and Windows machines
* Node.js version (unless using Appium.app|exe):  v8.11.1
* Mobile platform/version under test: 7.0 and 7.1
* Real device or emulator/simulator: Both  Real device and emulator/simulator
* Appium CLI or Appium.app|exe:

## Link to Appium logs

https://gist.github.com/kumarswamy757/8c994e712a49b05608981593e51ecdc0

## Code To Reproduce Issue [ Good To Have ]

package WebDriver.Project;

import java.net.MalformedURLException;
import java.net.URL;
import org.openqa.selenium.remote.DesiredCapabilities;
import io.appium.java_client.AppiumDriver;
import io.appium.java_client.PressesKeyCode;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.android.AndroidKeyCode;

public class AppiumTest {
	
	public static void main(String[] args) throws MalformedURLException, InterruptedException {

		DesiredCapabilities caps = new DesiredCapabilities();
		caps.setCapability("deviceName", "Android Emulator");
		caps.setCapability("browserName", "");
		caps.setCapability("platformVersion", "7.0");
		caps.setCapability("platformName", "Android");
		caps.setCapability("name", "Amazon App Testing");
		caps.setCapability("idleTimeout", "1000");
		caps.setCapability("appPackage", "com.example.kthota.myapplication");
		caps.setCapability("appActivity", "com.example.kthota.eureQaApp.LoginActivity");
		caps.setCapability("automationName", "Appium");
		caps.setCapability("autoGrantPermissions", "true");
		
		AppiumDriver driver = new AndroidDriver(new URL("http://localhost:4723/wd/hub"), caps);

		Thread.sleep(5000);
		((PressesKeyCode)driver).longPressKeyCode(AndroidKeyCode.KEYCODE_E);
		
	}
}

**Comment by kumarswamy757** [comment]
With uiautomator2 also i'm seeing the same behaviour

**Comment by kumarswamy757** [comment]
Maybe if it is possible please provide Duration for the longPressKeycode.

**Comment by mykola-mokhnach** [comment]
The fix has been published in appium@beta
