### ISSUE TITLE
"Rotation not supported: (null)" error in iOS

### ISSUE THREAD

**Issue by kumarswamy757** [appium/appium#10625]
## The problem

I want to perform DeviceRotation using the DeviceRotation class. So i created an object for DeviceRotation class and performed rotation. Rotation is performed successfully, but i'm getting org.openqa.selenium.WebDriverException: Rotation not supported: (null).

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2 and 1.8.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows and Linux
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: 11.2
* Real device or emulator/simulator: iPhone 8 Simulator
* Appium CLI or Appium.app|exe:

## Link to Appium logs
https://gist.github.com/kumarswamy757/7c63c760e3648cddec10b3dbf824e8a7

## Code To Reproduce Issue [ Good To Have ]

DeviceRotation rotate = new DeviceRotation(0, 0, 90);
driver.rotate(rotate);

**Comment by mykola-mokhnach** [comment]
Try `driver.rotate(ScreenOrientation.LANDSCAPE)`

Also, I don't see any errors in the attached logs.

**Comment by kumarswamy757** [comment]
I tried with the code that you provided it worked. But I want to rotate the device to a certain angle which cannot be done using this (driver.rotate(ScreenOrientation.LANDSCAPE)).
Please check the raw file that I provided in the gist there you can find Rotation not supported: (null) error.

Thanks

**Comment by mykola-mokhnach** [comment]
> But I want to rotate the device to a certain angle which cannot be done using this

Unfortunately such functionality is not supported

**Comment by kumarswamy757** [comment]
Could you please tell me the use of DeviceRotation class?
