### ISSUE TITLE
Not able to install appium server through npm

### ISSUE THREAD

**Issue by Snehadt** [appium/appium#10621]
Hi,
Getting the below error while installing appium through npm.Please help

Microsoft Windows [Version 6.1.7600]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\...~~>npm install -g appium
C:\Users\...``\AppData\Roaming\npm\appium -> C:\Users\S...``\AppD
ata\Roaming\npm\node_modules\appium\build\lib\main.js

> appium-chromedriver@3.5.2 install C:\Users\...``\AppData\Roaming\npm\n
ode_modules\appium\node_modules\appium-chromedriver
> node install-npm.js

info Chromedriver Install Installing Chromedriver version '2.37' for platform 'w
in' and architecture '32'
info Chromedriver Install Opening temp file to write chromedriver_win32 to...
info Chromedriver Install Downloading https://chromedriver.storage.googleapis.co
m/2.37/chromedriver_win32.zip...
info Chromedriver Install Writing binary content to C:\Users\***~1\AppData\Lo
cal\Temp\2018328-4756-lqhj23.tswri\chromedriver_win32.zip...
info Chromedriver Install Extracting C:\Users\***~1\AppData\Local\Temp\201832
8-4756-lqhj23.tswri\chromedriver_win32.zip to C:\Users\***~1\AppData\Local\Te
mp\2018328-4756-lqhj23.tswri\chromedriver_win32
info Chromedriver Install Creating C:\Users\...```\AppData\Roaming\npm\no
de_modules\appium\node_modules\appium-chromedriver\chromedriver\win...
info Chromedriver Install Copying unzipped binary, reading from C:\Users\**~
1\AppData\Local\Temp\2018328-4756-lqhj23.tswri\chromedriver_win32\chromedriver.e
xe...
Error: EPERM: operation not permitted, open 'C:\Users\**``~1\AppData\Local\Tem
p\2018328-4756-lqhj23.tswri\chromedriver_win32\chromedriver.exe'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules\app
ium\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)

**Comment by mykola-mokhnach** [comment]
> Error: EPERM: operation not permitted, open 'C:\Users**``~1\AppData\Local\Tem
p\2018328-4756-lqhj23.tswri\chromedriver_win32\chromedriver.exe'

This means that your user's folder permissions are incorrect or some third party software, for example an antivirus is blocking the binary. In both cases the issue has nothing to do with Appium itself.
