### ISSUE TITLE
iOS: takes long time to identify objects in ipad 11.3 with Appium 1.8.0

### ISSUE THREAD

**Issue by rdhandapani88** [appium/appium#10633]
## The problem
Greetings,
The script take at least 1mins to identify a basic xpath like //XCUIElementTypeStaticText[contains(@name,'SKU')]
//XCUIElementTypeButton[@name='Run Credit']

Previously this used to be very fast and now it is almost very slow. And also when we use the preceeding-siblings / following-siblings , it doesn't work.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2
* Desktop OS/version used to run Appium: Mac OS seirra
* Node.js version (unless using Appium.app|exe): 
* Mobile platform/version under test: 11.3
* Real device or emulator/simulator: Real device IPad Mini (Landscape mode)
* Appium CLI or Appium.app|exe: Appium CLI

**Comment by mykola-mokhnach** [comment]
https://github.com/facebook/WebDriverAgent/wiki/How-To-Achieve-The-Best-Lookup-Performance

Closed as third party issue
