### ISSUE TITLE
Screen record upload to FTP for Android is broken

### ISSUE THREAD

**Issue by hursevich** [appium/appium#10630]
## The problem

Unable to perform screen record FTP upload for appium-android driver.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: iOS
* Node.js version (unless using Appium.app|exe): v8.9.4
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real device - Nexus 6 (6.0.1) 
* Appium CLI or Appium.app|exe: Java Client 6.0.0-BETA5

## Link to Appium logs

Initial issue:
https://gist.github.com/hursevich/9b98f99ae154093448b3aead75960d8d

When I fix net.js a bit (commenting out file validation) ftp auth creds are not picked up:
https://gist.github.com/hursevich/37c0a97e98fa631db52334e75797239e

May be fixed in https://github.com/appium/appium-android-driver/blob/master/lib/commands/recordscreen.js#L98 replaced by remoteUrl.protocol.startsWith('ftp')

**Comment by hursevich** [comment]
@mykola-mokhnach any idea with https://gist.github.com/hursevich/9b98f99ae154093448b3aead75960d8d?
I see exception is thrown from https://github.com/appium/appium-support/blob/master/lib/net.js#L45

**Comment by mykola-mokhnach** [comment]
@imurchie Can you please assist with problem above?

**Comment by imurchie** [comment]
I can give it a look.

**Comment by imurchie** [comment]
https://github.com/appium/appium-support/pull/69
