### ISSUE TITLE
I can not see all the elements of the view or activity with appium desktop

### ISSUE THREAD

**Issue by JhonShell** [appium/appium#10635]
## The problem

I'm having trouble with an app that does not show me full content of the current activity. but I can not get all the elements. currently this using appium gui, to record the paths to editText textView, etc and then pass it to my script.

## Environment

* Appium version (or git revision) appium-desktop-1.2.6-x86_64.AppImage 
* Last Appium version that did not exhibit the issue (if applicable):

* debian 
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

![appium1 1](https://user-images.githubusercontent.com/20390864/39485554-b8b01dfe-4d3e-11e8-9bbe-96b30536a043.png)
![appium33](https://user-images.githubusercontent.com/20390864/39486856-23aeb0f8-4d43-11e8-937e-fadb13116add.png)
![appium44](https://user-images.githubusercontent.com/20390864/39486863-28d32b18-4d43-11e8-96ec-278ed7ac02d9.png)

![appium22](https://user-images.githubusercontent.com/20390864/39485672-1ea0951c-4d3f-11e8-8dbc-14495767132c.png)

I tried sending a sendkey to the edittext, recording the code it uses to make the element and it tells me that all the editext have the same xpath and the same id.

As mentioned above I can not see all the elements, and editext have the same location according to appium.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
D
[log.txt](https://github.com/appium/appium/files/1964773/log.txt)

**Comment by mykola-mokhnach** [comment]
Are these elements visible in the accessibility inspector?

**Comment by JhonShell** [comment]
yes, but not all appear, only the main class appears as it appears in the picture, the modified text does not appear for, nor the buttons, in conclusion only that tress class of the activity appears. While it has much more

**Comment by mykola-mokhnach** [comment]
This means that you application under test does not "publish" these elements. The problem should be fixed in the source code of the app. Closed as not an issue.

**Comment by JhonShell** [comment]
new version of appium otengo this error
![error](https://user-images.githubusercontent.com/20390864/39659759-80306024-4ff5-11e8-8040-8465cdde1037.png)
