### ISSUE TITLE
iOS: Unable to use perform() with TouchAction since Appium 1.8

### ISSUE THREAD

**Issue by LaforgeN** [appium/appium#10632]
## The problem

Hi,

Since the release of appium 1.8, we are unable to execute command perform() from TouchAction.

Command used:
TouchAction(self.driver).press(x=localx, y=localy).release().perform()

Exception raised:
Message: An unknown server-side error occurred while processing the command. Original error: Unhandled endpoint: /session/3865C422-018A-428D-B0DC-4947AFC4509B/wda/touch/perform -- http://localhost:8100/ with parameters {
wildcards =     (
"session/3865C422-018A-428D-B0DC-4947AFC4509B/wda/touch/perform");
}

## Environment
Appium version : 1.8
Last Appium version that it was working: 1.7.2
Desktop OS: macOS High Serria 10.13.3
Node.js version: v9.8.0
Mobile plateform/version: iPhone 6 - 10.2.1
Real device

## Link to Appium logs

https://gist.github.com/LaforgeN/2d5a08cb87ebc35d9e380cbd65f06011

## Code To Reproduce Issue [ Good To Have ]
Here's the code to reproduce the issue using Python language
TouchAction(self.driver).press(x=localx, y=localy).release().perform()
or
TouchAction(self.driver).tap(x=localx, y=localy).perform()

Thanks,
Nic

**Comment by mykola-mokhnach** [comment]
You must be in native context to be able to execute touch. Closed as not an issue.

**Comment by LaforgeN** [comment]
Hi @mykola-mokhnach , I know that TouchAction is for Native and TouchActions is for WebView. But since this command does not use an element but only coordinate it was working on Appium 1.7.2. I just re-run the test switching to Native context and still getting same issue.

Here's the appium log showing that the contextw as switched to Native:
https://gist.github.com/LaforgeN/8e371a2a6626ba7ce65211fcad475b2c

**Comment by mykola-mokhnach** [comment]
It looks like context switching fails:

```
[HTTP] --> POST /wd/hub/session/e5392113-d90d-40cf-893a-fc4510ad4077/context
IphoneLocal_appium_server |08:52:02| [HTTP] {"name":"NATIVE_APP","sessionId":"e5392113-d90d-40cf-893a-fc4510ad4077"}
IphoneLocal_appium_server |08:52:02| [HTTP] <-- POST /wd/hub/session/e5392113-d90d-40cf-893a-fc4510ad4077/context 200 5 ms - 76
IphoneLocal_appium_server |08:52:02| [HTTP] 
IphoneLocal_appium_server |08:52:02| (node:31481) UnhandledPromiseRejectionWarning: Error: Error: not opened
```

@imurchie Do you have any ideas about why such error happens?

**Comment by LaforgeN** [comment]
After switching the context to NATIVE_APP. We are calling self.driver.current_context to make sure it matches the one requested. In this case it did match, otherwise we are throwing a new exception.

But the logs are showing an empty context:

`IphoneLocal_appium_server |08:52:02| [HTTP] --> GET /wd/hub/session/e5392113-d90d-40cf-893a-fc4510ad4077/context
IphoneLocal_appium_server |08:52:02| [HTTP] {}
IphoneLocal_appium_server |08:52:02| [HTTP] <-- GET /wd/hub/session/e5392113-d90d-40cf-893a-fc4510ad4077/context 200 2 ms - 84`

**Comment by LaforgeN** [comment]
Pulled the latest version of WDA seems to have fixed our issue.
It is now working with appium v1.8.0

**Comment by WaFeIS7** [comment]
@mykola-mokhnach  
Hello. I think that  I have the issue with the command 'performTouch'.  
Environment: 
- Appium 1.8.1 
-  Mac OS 10.13.4 
-  Node v9.11.1 
-  robotframework-appiumlibrary (1.4.6)
- IOS 11.4 iPhone 6 
- XCUITestDriver (v2.84.0)
Real Device. 

Upgrade the appium today, I noticed the problem,  when, appium use  Executing command performTouch doesn`t work as expected. 
There is error: 
  
`[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: press(options={"y":null,"x":null,"element":"1F000000-0000-0000-8D06-000000000000"})-moveTo(options={"y":null,"x":null,"element":"27000000-0000-0000-8D06-000000000000"})-release(options={})
[debug] [JSONWP Proxy] Proxying [POST /wda/touch/perform] to [POST http://localhost:8100/session/ABBCAC15-0DA7-4DEC-BB12-8B38EC99E809/wda/touch/perform] with body: {"actions":[{"action":"press","options":{"y":null,"x":null,"element":"1F000000-0000-0000-8D06-000000000000"}},{"action":"moveTo","options":{"y":null,"x":null,"element":"27000000-0000-0000-8D06-000000000000"}},{"action":"release","options":{}}]}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"-[NSNull floatValue]: unrecognized selector sent to instance 0x1b5744878\n\n(\n\t0   CoreFoundation                      0x00000001833c6da4 <redacted> + 252\n\t1   libobjc.A.dylib                     0x00000001825805ec objc_exception_throw + 56\n\t2   CoreFoundation                      0x00000001833d4098 <redacted> + 0\n\t3   CoreFoundation                      0x00000001833cc5c8 <redacted> + 1380\n\t4   CoreFoundation                      0x00000001832b241c _CF_forwarding_prep_0 + 92\n\t5   WebDriverAgentLib                   0x000000010431b81c -[FBAppiumGestureItem coordinatesWithOptions:error:] + 1056\n\t6   WebDriverAgentLib                   0x000000010431af40 -[FBAppiumGestureItem initWithActionItem:application:atPosition:offset:error:] + 472\n\t7   WebDriverAgentLib                   0x000000010431c0a4 -[FBPressItem initWithActionItem:application:atPosition:offset:error:] + 216\n\t8   WebDriverAgentLib                   0x000000010431df70 -[FBAppiumActionsSynthesizer eventPathsWithAction:...
[MJSONWP] Encountered internal error running command: Error: An unknown server-side error occurred while processing the command.
[MJSONWP]     at JWProxy.command$ (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:176:15)
[MJSONWP]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP]     at <anonymous>
[HTTP] <-- POST /wd/hub/session/f0905bb9-224c-4843-958c-1ab98c6ca4fc/touch/perform 500 572 ms - 238`

Full Log:::  https://gist.github.com/WaFeIS7/ccd86a4e242799d59050d018684e476d 


Also, It works on the version appium 1.7.2, IOS 11.3 Real Device. 
Log with Appium version 1.7.2 and iOS 11.3 with successfuly execute
https://gist.github.com/WaFeIS7/7df63d5fcd4446980017effc3fc6046b 

The same problem when I use Appium 1.8.1 with iOS 11.3. 
Thanks

**Comment by mykola-mokhnach** [comment]
@WaFeIS7 It's a Python client issue. See https://github.com/appium/python-client/pull/214 for more details

**Comment by WaFeIS7** [comment]
@mykola-mokhnach Thanks
