### ISSUE TITLE
chromedriverExecutableDir and chromedriverChromeMappingFile set, but not use the right chromedriver version

### ISSUE THREAD

**Issue by loveiset** [appium/appium#10637]
## The problem

I set both chromedriverExecutableDir and chromedriverChromeMappingFile params, but when test executes, error occurs that shows `Failed to start Chromedriver session: An unknown server-side error occurred while processing the command. (Original error: unknown error: Chrome version must be >= 55.0.2883.0`

## Environment

* Appium version: 1.8.0
* OS/version: win7 64 SP1
* Node.js version: v8.11.0
* Mobile platform/version under test: Android 6.0.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: `appium --session-override --no-reset --log d:\appium.log`

## Details

```
Running 'D:\hcs\Documents\Android-SDK\platform-tools\adb.exe -P 5037 -s 1469081a shell dumpsys package com.android.chrome'
```
the log shows it get the chromedriver version of the phone using command above, but there is no package `com.android.chrome` on my phone.
I checked both of my phones, only `com.android.webview` exists.
The correct webview version on my phone is `Chrome/46.0.2490.11`

## Link to Appium logs

[link to logs](https://gist.github.com/loveiset/084b80f7d652ea8347e49a24c2c4b2a0)

**Comment by mykola-mokhnach** [comment]
@imurchie FYI

**Comment by loveiset** [comment]
does this param only work in web test(with chrome), not hybrid app(with webview)?

**Comment by bastenf** [comment]
hello, similar question,  will appium search backend chrome if I use chromedriverExecutableDir and chromedriverChromeMappingFile? or only search com.android.chrome for automatic discovery?

**Comment by mykola-mokhnach** [comment]
As far as I remember some fixes were done to this logic recently. Please check if how the stuff works in appium@beta
