### ISSUE TITLE
Unable to get Keyboard visibility in iOS Devices

### ISSUE THREAD

**Issue by kumarswamy757** [appium/appium#10639]
## The problem

I'm not able to get the keyboard visibility state for iOS 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: window & Linux
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: 11.0
* Real device or emulator/simulator: iphone 6 Simulator
* Appium CLI or Appium.app|exe:

## Link to Appium logs
Getting java.lang.ClassCastException: io.appium.java_client.ios.IOSDriver cannot be cast to io.appium.java_client.android.HasDeviceDetails error in iOS. 

when i check appium java docs (http://appium.github.io/java-client/io/appium/java_client/ios/IOSDriver.html) i found that "HasDeviceDetails" class extends only "AndroidDriver" but not "IOSDriver"

## Code To Reproduce Issue [ Good To Have ]

boolean isKeyboardShown = ((HasDeviceDetails)driver).isKeyboardShown();

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/appium/java-client
