### ISSUE TITLE
Recording video via executeScript("mobile:shell") and "screenrecord": error 'Timed out after 20000ms' 

### ISSUE THREAD

**Issue by dkolechintsev** [appium/appium#10638]
**The problem**
Hi, team!
I am trying to record video using  **executeScript("mobile:shell")** and **"screenrecord"**
_driver.executeScript("mobile:shell", ImmutableMap.of("command", "screenrecord /sdcard/demo.mp4 --time-limit 120"));_
And catch this error:
`[W3C] Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command '/Users/dev/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell 'screenrecord /sdcard/demo6.mp4 --time-limit 120'' timed out after 20000ms'; Stderr: ''; Code: 'null'
[W3C]     at ADB.execFunc$ (/usr/local/lib/node_modules/appium/node_modules/appium-adb/lib/tools/system-calls.js:317:13)
[W3C]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[W3C]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[W3C]     at <anonymous>`

## Environment
* Appium version: 1.8.0
* Mobile platform: Android 7.0 (emulator)

## Comments
Is it possible manually to set timeout for this kind of commands? May be, there is another approach to record video. Thanks for any advice or example!

**Comment by mykola-mokhnach** [comment]
This endpoint should not be used for long running operations. Although, you can still use https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/screenrecording/CanRecordScreen.java to perform video capture.

**Comment by dkolechintsev** [comment]
Is it possible to provide any simple example?

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/java-client/blob/master/src/test/java/io/appium/java_client/android/AndroidScreenRecordTest.java
