### ISSUE TITLE
Appium tests are not running in Jenkins

### ISSUE THREAD

**Issue by Mayur5712** [appium/appium#10642]
## The problem

Integrated Appium test framework with Jenkin, where appium is starting in code using AppiumDriverLocalService. When I trying to run the tests using Jenking all the tests are getting skipped and not running. 

## Environment

* Appium version : 1.8.0(beta)
* Node.js version : 5.6.0
* Mobile platform/version under test: 6.1.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

[Appium.txt](https://github.com/appium/appium/files/1971690/Appium.txt)

**Comment by mykola-mokhnach** [comment]
The error in the log is the java exception in your client code. How it is related to the Appium server functionality?

**Comment by Mayur5712** [comment]
In my framework, I am trying to start appium server using AppiumDriverLocalService. Below is the code for your reference.

 try {
            builder = new AppiumServiceBuilder();
            builder.withIPAddress("127.0.0.1");
            //builder.withArgument(GeneralServerFlag.LOG_LEVEL, "error");
            builder.usingPort(4723);
            service = AppiumDriverLocalService.buildService(builder);
            service.start();
        }catch (Exception e)
        {
            Log.error(e.toString());
        }
        Log.info("--------------------------------------------------------------------");
        Log.info("                  Appium server started successfully                ");
        Log.info("--------------------------------------------------------------------");
    }

When I run the my scripts using Jenkin, somehow it is not starting.

For now I commented the code and started appium server from command prompt and again run the from Jenkin then it works fine. 

Thats why I think it is Appium side issue

**Comment by mykola-mokhnach** [comment]
> For now I commented the code and started appium server from command prompt and again run the from Jenkin then it works fine.

If you can start the server manually from the command prompt then it must be a problem with AppiumDriverLocalService. Check the log/stacktrace, compare the command it creates with the command you use to run the server manually to find out why it fails. 

Closed as not an issue.
