### ISSUE TITLE
Location permission for app not erased on uninstall for iOS

### ISSUE THREAD

**Issue by jamesvanhorn** [appium/appium#10647]
## The problem

Leaving noReset and fullReset off, the app is uninstall/reinstalled as needed. Upon reinstall, I am not prompted for location permissions however. I am prompted for push notification permission though.

I remember researching this once and I believe the issue is a change in directory structure on device from iOS 8. Seems to affect sims and real devices (so xcrun simctl and ios-deploy)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Mac High Sierra
* Node.js version (unless using Appium.app|exe): 9.11.1
* Mobile platform/version under test: iOS 11.3.*
* Real device or emulator/simulator: both
* Appium CLI or Appium.app|exe: CLI

## Details

I currently have a method to background, swipe, and long press to uninstall manually. This does remove the location permission, but its time consuming. Calling fullReset on the sim works, but once again at the cost of time (and it also removes certificate trust settings store for the simulator, breaking its compatibility with Charles Web Proxy until i reinstall the cert)

Is there any workaround?

**Comment by mykola-mokhnach** [comment]
> Seems to affect sims and real devices (so xcrun simctl and ios-deploy)

You are right, this is rather an issue with simctl/ios-deploy. I don't think we could do anything there.
