### ISSUE TITLE
Appium 1.8.0 implicit Wait does not Work

### ISSUE THREAD

**Issue by thomasEffberger** [appium/appium#10645]
## Changing from Appium 1.8.0beta3 (or 5) to 1.8.0 leads to ClassCastException in Java-Client during WebDriverWait

I actually tried to investigate why my tests broke after changing to 1.8.0 and the newest Java-client version (6.0.0beta5). I am currently in the position that I can change the java-client version to 6.0.0beta3 (like before my update to 1.8.0) and it is resulting in the same issue. I don't know if this incompatibility refers to the java-client or the appium-server.

## Environment

* Appium version 1.8.0 & Java-Client 6.0.0beta5 (or beta3)
* Last Appium version that did not exhibit the issue: 1.8.0beta5
* Desktop OS/version used to run Appium: A
* Node.js version (unless using Appium.app|exe): 8.11.1 LTS
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Real Device S Galaxy S7
* Appium CLI or Appium.app|exe: CLI

## Details

I'm not familiar with the appium/uiautomator driver but there is a difference I observed occuring between 1.8.0 and previous versions...
I found the difference of a JSONWP call response (AndroidDriver.findElement) between 1.8.0 and 1.8.0beta5
Calling it with an implicit wait the version of 1.8.0 returns a 404 when calling the "element" endpoint. In previous appium versions the server responds with a 500 Return Code. I'll attach the different server log snippets in the following gists and also the ClassCastException of my test output.

## Link to Appium logs

Appium 1.8.0 vs 1.8.0beta5 _JSONWP call_:
https://gist.github.com/thomasEffberger/cfc4ada4b313ea03131d06d6ab02aa98

ClassCastException itself:
https://gist.github.com/thomasEffberger/57ce3ba100dc112b29dcfa922994cbea

## Code To Reproduce Issue [ Good To Have ]

With Java-Client 6.0.0beta5 assuming that you use built-in Page-Objects an the called element is actually not displayed
```
new AppiumFluentWait<AppiumDriver<MobileElement>>(driver).withTimeout(Duration.ofSeconds(durationInSeconds))
               .pollingEvery(Duration.ofMillis(500)).until(ExpectedConditions.visibilityOf(element));
```
With Java-Client 6.0.0beta3 assuming that you use built-in Page-Objects an the called element is actually not displayed
```
new WebDriverWait(driver, 10).until(ExpectedConditions.visibilityOf(element));
```

**Comment by mykola-mokhnach** [comment]
It is the client issue. See https://github.com/appium/java-client/issues?q=is%3Aissue+%22cannot+be+converted+to+WebElement%22+is%3Aclosed

**Comment by thomasEffberger** [comment]
@mykola-mokhnach rejected as client issue. See https://github.com/appium/java-client/issues/872

**Comment by KazuCocoa** [comment]
hm.. does this get W3C response?
What about running the command with W3C format..?
👀  https://gist.github.com/thomasEffberger/cfc4ada4b313ea03131d06d6ab02aa98
