### ISSUE TITLE
Appium 1.8.0 Drag and Drop does not work

### ISSUE THREAD

**Issue by FelixHahn** [appium/appium#10641]
## The problem

After long pressing on a list element, the element is highlighted but doesn't move to the wished location.

## Environment

* Appium version: v1.8.0 2b1ec77 (Java client 6.0.0-Beta5) 
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2 (Java client 5.0.3) 
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): 8.9.1
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Real Device (Samsung Galaxy Tab A6)
* Appium CLI 

## Details

We want to select an list element via long press and drag the list element to a lower position in the list.

Therefore we use this command:

touch1.press(PointOption.point(x,y)).waitAction(WaitOptions.waitOptions(Duration.ofMillis(1000))).moveTo(PointOption.point(x, y + 300)).release().perform();

Also tried it with longPress() instead of press().

What happens:

The list element is selected and marked after the long press but it doesn't move when the moveTo() is executed. 

## Logs

```
- - longpressSwipeDownElement - x: 1621 y: 355 
- sleep: 1000
[[HTTP][ [-->[ [POST[ [/wd/hub/session/676f237d-b383-4233-95f2-34b540d865a8/touch/perform[
[[HTTP][ [{"actions":[{"action":"press","options":{"x":1621,"y":355}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"x":1621,"y":655}},{"action":"wait","options":{"ms":1000}},{"action":"release","options":{}}]}[
[debug] [[W3C][ Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":1621,"y":355}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"x":1621,"y":655}},{"action":"wait","options":{"ms":1000}},{"action":"release","options":{}}],"676f237d-b383-4233-95f2-34b540d865a8"]
[debug] [[JSONWP Proxy][ Proxying [POST /touch/down] to [POST http://localhost:8210/wd/hub/session/14bbd18a-bea0-441a-bcc9-e1e23466065c/touch/down] with body: {"params":{"x":1621,"y":355}}
[debug] [[JSONWP Proxy][ Got response with status 200: {"sessionId":"14bbd18a-bea0-441a-bcc9-e1e23466065c","status":0,"value":true}
[debug] [[JSONWP Proxy][ Proxying [POST /touch/move] to [POST http://localhost:8210/wd/hub/session/14bbd18a-bea0-441a-bcc9-e1e23466065c/touch/move] with body: {"params":{"x":1621,"y":655}}
[debug] [[JSONWP Proxy][ Got response with status 200: {"sessionId":"14bbd18a-bea0-441a-bcc9-e1e23466065c","status":0,"value":true}
[debug] [[JSONWP Proxy][ Proxying [POST /touch/up] to [POST http://localhost:8210/wd/hub/session/14bbd18a-bea0-441a-bcc9-e1e23466065c/touch/up] with body: {"params":{"x":1621,"y":655}}
[debug] [[JSONWP Proxy][ Got response with status 200: {"sessionId":"14bbd18a-bea0-441a-bcc9-e1e23466065c","status":0,"value":true}
[debug] [[W3C][ Responding to client with driver.performTouch() result: null
[[HTTP][ [<-- POST /wd/hub/session/676f237d-b383-4233-95f2-34b540d865a8/touch/perform [[200[ [5684 ms - 76[
[[HTTP][ [[
```

## Code To Reproduce Issue

```
TouchAction touch1 = new TouchAction(driver);
Point pointElement = driver.findElement(element).getLocation();
Dimension dimElement = driver.findElement(element).getSize();

int x = pointElement.getX() + dimElement.getWidth()/2;	
int y = pointElement.getY() + dimElement.getHeight()/2;  

touch1.press(PointOption.point(x,y)).waitAction(WaitOptions.waitOptions(Duration.ofMillis(1000))).moveTo(PointOption.point(x, y + 300)).release().perform();
```

**Comment by mykola-mokhnach** [comment]
Please provide all the requested information

**Comment by FelixHahn** [comment]
@mykola-mokhnach Sorry, I accidentally hit the commit button. No Infos are complete.

Thank's in advance!

**Comment by mykola-mokhnach** [comment]
This log does not look like the one from Appium .1.8.0

**Comment by mykola-mokhnach** [comment]
Do you use UiAutomator2?

**Comment by FelixHahn** [comment]
@mykola-mokhnach  Yes, here are the complete logs of the test. 

https://gist.github.com/FelixHahn/2d33f7114ba70ab53bd57257a041302f

**Comment by mykola-mokhnach** [comment]
is the application native or it uses a webview?

**Comment by FelixHahn** [comment]
It is native.

**Comment by mykola-mokhnach** [comment]
I'd try to enable pointer tracking in developer settings to see if it really swipes the correct area. Also you can try to press an element instead of giving an absolute coordinates or play with sleep duration.

**Comment by FelixHahn** [comment]
Thank's we will try this today.

The swipe is executed correctly as far we could see it from pointer tracking. 

We played with the sleep duration. Nothing changed there. Always the same result. You can see how the long press is executed and the selected list item is highlighted. 

We will give a feedback during the day.

**Comment by vjmaiky** [comment]
give it a try and use longPress instead of press; i have a similar issue yesterday and longpress worked

**Comment by vjmaiky** [comment]
I'm using something like this: 
`touchAction.longPress(PointOption.point(60, 10)).waitAction(WaitOptions.waitOptions(Duration.ofMillis(500))).moveTo(PointOption.point(60, 667)).release().perform();`

**Comment by SohilKumar** [comment]
Hey @FelixHahn Did u find any solution for it..?, because i'm also facing the same issue swipe doesn't work in 1.8.0

**Comment by mdelgadoAxa** [comment]
Hello @SohilKumar, @vjmaiky i use this function to execute swipe i android and ios devices

private static void swipeRight(WebElement element) {
        int y = element.getLocation().getY() + (int) (element.getSize().getHeight() * 0.5);
        int startX = (int) (element.getSize().getWidth() * 0.5);
        int endX = (int) (element.getSize().getWidth() * 0.1);
        if (isAndroidDevice()) {
            PointOption start = PointOption.point(startX, y);
            PointOption end = PointOption.point(endX, y);
            new TouchAction(driver()).press(start).waitAction(WaitOptions.waitOptions(Duration.ofSeconds(2))).moveTo(end).release().perform();
        } else {
            Map<String, Object> params = new HashMap<>();
            params.put("duration", 2.0);
            params.put("fromX", startX);
            params.put("fromY", y);
            params.put("toX", endX);
            params.put("toY", y);
            driver().executeScript("mobile: dragFromToForDuration", params);
        }
    }

The param that is passed to this function is the Element where you want to do the swipe action. Maybe this can help you.

**Comment by FelixHahn** [comment]
@SohilKumar  Sorry for the late response. No we don't find any solution until now. Also the longPress does not work.

We will try the code from @mdelgadoAxa 

We will give you feedback.

**Comment by Kitty2014** [comment]
@FelixHahn   
Could you used the Point coordinates and longPress it? sample code as below：

action.longPress((int)(52*screenRatioX),(int)(89*screenRatioY),Duration.ofMillis(200)).perform();

waiting for you replay

**Comment by dejavu969** [comment]
"longPress" instead of "press" is working for me. Thanks!!!

public void scrollDown() 
         {
	      TouchAction ta = new TouchAction(driver);
	      ta.longPress(150, 500).moveTo(150, -200).release().perform();
	  	}

**Comment by mykola-mokhnach** [comment]
closed as third party issue
