### ISSUE TITLE
Question: Immediate Response 

### ISSUE THREAD

**Issue by lecrane54** [appium/appium#10643]
## The question

I am trying to figure out how to grab the iOS logs while the tests are written in xFramium. The code for implementation of the web driver for clicks, send keys etc. is already in there, just wondering if i could snag the iOS logs.

## Environment

Appium version - Latest
ios & Android - All versions
Both device and simulator
Using Perfecto

## Details

Any insight on this would be incredibly helpful

**Comment by mykola-mokhnach** [comment]
http://appium.io/docs/en/commands/session/logs/get-log-types/
http://appium.io/docs/en/commands/session/logs/get-log/

Also, it is possible to get logs via web socket broadcast endpoint, which has been implemented in the recent beta version of the server: https://github.com/appium/java-client/pull/871
