### ISSUE TITLE
Appium v1.8.0: With uiautomator2, Error "ProxyRequestError: Could not proxy command to remote server" displays when it use app_strings

### ISSUE THREAD

**Issue by haihoangtran** [appium/appium#10659]
## The problem

"\Error, "ProxyRequestError: Could not proxy command to remote server", displayed when it tried to use uiautomator2.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2
* Desktop OS/version used to run Appium: Ubuntu 16.0.4
* Node.js version (unless using Appium.app|exe): 6.14.2
* Mobile platform/version under test: Android O v8.1
* Real device or emulator/simulator:real device Nexus 6P
* Appium CLI or Appium.app|exe:

## Details

I installed 3 apps:
       1st app with minSDK = 16. It works well 
       2nd apps: Google Drive. Don't use uiautomator2 for app strings.
       3rd app: minSDK = 21 (changed from 19 to 21): Error happens. Please, see the logs for more details
Desire Capability for 3rd app is:
      "app": cfg.get("APP", "aio-package"),
      "appWaitActivity": AIO_ACTIVITY.WAIT_ACTIVITY,
      'appPackage': PACKAGE.AIO_PACKAGE,
      'appActivity': AIO_ACTIVITY.LAUNCH_ACTIVITY,
      'fullReset': "true",
      'unicodeKeyboard': "true",
      'resetKeyboard': "true",
      'setWebContentsDebuggingEnabled': "true",
      'automationName': 'uiautomator2'
Language: Python

It works well on appium v1.7.2.

## Link to Appium logs
[logs.txt](https://github.com/appium/appium/files/1981014/logs.txt)

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
```
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8202/wd/hub/status] with no body
[JSONWP Proxy] Got unexpected response: <HTML><HEAD>
[JSONWP Proxy] <TITLE>Network Error</TITLE>
[JSONWP Proxy] </HEAD>
[JSONWP Proxy] <BODY>
[JSONWP Proxy] <FONT face="Helvetica">
[JSONWP Proxy] <big><strong></strong></big><BR>
[JSONWP Proxy] </FONT>
[JSONWP Proxy] <blockquote>
[JSONWP Proxy] <TABLE border=0 cellPadding=1 width="80%">
[JSONWP Proxy] <TR><TD>
[JSONWP Proxy] <FONT face="Helvetica">
[JSONWP Proxy] <big>Network Error (dns_unresolved_hostname)</big>
[JSONWP Proxy] <BR>
[JSONWP Proxy] <BR>
[JSONWP Proxy] </FONT>
[JSONWP Proxy] </TD></TR>
[JSONWP Proxy] <TR><T...
```

There is a problem with your network setup. The issue has nothing to do with strings extraction.

**Comment by haihoangtran** [comment]
If the issue from network setup. it should not be worked for first app either. I used apk files for installing 1st and 3rd apps. The following is log of first app from logs.txt

[debug] [ADB] Running '/home/qata/tools/platform-tools/adb -P 5037 -s 84B7N15A04002822 shell dumpsys package io.appium.unlock'
[ADB] Checking whether aapt is present
[ADB] Using aapt from /home/qata/tools/build-tools/27.0.3/aapt
[debug] [ADB] The installed 'io.appium.unlock' package does not require upgrade ('2.0.0' >= '2.0.0')
[ADB] Getting device platform version
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/home/qata/tools/platform-tools/adb -P 5037 -s 84B7N15A04002822 shell getprop ro.build.version.release'
[debug] [ADB] Current device property 'ro.build.version.release': 8.1.0
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/home/qata/tools/platform-tools/adb -P 5037 -s 84B7N15A04002822 shell wm size'
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/home/qata/tools/platform-tools/adb -P 5037 -s 84B7N15A04002822 shell getprop ro.product.model'
[debug] [ADB] Current device property 'ro.product.model': Nexus 6P
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/home/qata/tools/platform-tools/adb -P 5037 -s 84B7N15A04002822 shell getprop ro.product.manufacturer'
[debug] [ADB] Current device property 'ro.product.manufacturer': Huawei
[debug] [ADB] Getting install status for com.hp.android.printservice
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/home/qata/tools/platform-tools/adb -P 5037 -s 84B7N15A04002822 shell pm list packages com.hp.android.printservice'
[debug] [ADB] App is installed
[debug] [ADB] Getting install status for com.hp.android.printservice
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/home/qata/tools/platform-tools/adb -P 5037 -s 84B7N15A04002822 shell pm list packages com.hp.android.printservice'
[debug] [ADB] App is installed
[debug] [ADB] Getting package info for 'com.hp.android.printservice'
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/home/qata/tools/platform-tools/adb -P 5037 -s 84B7N15A04002822 shell dumpsys package com.hp.android.printservice'
[ADB] Checking whether aapt is present
[ADB] Using aapt from /home/qata/tools/build-tools/27.0.3/aapt
[debug] [ADB] The installed 'com.hp.android.printservice' package does not require upgrade ('4.4.1' >= '4.4.1')
[AndroidDriver] Performing fast reset on 'com.hp.android.printservice'
[debug] [ADB] Getting install status for com.hp.android.printservice
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/home/qata/tools/platform-tools/adb -P 5037 -s 84B7N15A04002822 shell pm list packages com.hp.android.printservice'
[debug] [ADB] App is installed
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/home/qata/tools/platform-tools/adb -P 5037 -s 84B7N15A04002822 shell am force-stop com.hp.android.printservice'
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/home/qata/tools/platform-tools/adb -P 5037 -s 84B7N15A04002822 shell pm clear com.hp.android.printservice'
[debug] [AndroidDriver] Performed fast reset on the installed 'com.hp.android.printservice' application (stop and clear)
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/home/qata/tools/platform-tools/adb -P 5037 -s 84B7N15A04002822 shell rm -rf /data/local/tmp/strings.json'
[debug] [AndroidDriver] Extracting strings from apk
[debug] [AndroidDriver] /home/qata/Documents/Apps/hpps/HPLegacyPlugin_18.2.139.apk
[debug] [AndroidDriver] null
[debug] [AndroidDriver] /tmp/com.hp.android.printservice
[debug] [ADB] Extracting strings for language: default
[ADB] Checking whether aapt is present
[ADB] Using aapt from /home/qata/tools/build-tools/27.0.3/aapt
[ADB] Successfully extracted 712 strings from '/home/qata/Documents/Apps/hpps/HPLegacyPlugin_18.2.139.apk' resources for '(default)' configuration
[debug] [ADB] Running '/home/qata/tools/platform-tools/adb -P 5037 -s 84B7N15A04002822 push /tmp/com.hp.android.printservice/strings.json /data/local/tmp'
[debug] [AndroidBootstrap] Watching for bootstrap disconnect
[debug] [ADB] Forwarding system: 4724 to device: 4724
[debug] [ADB] Running '/home/qata/tools/platform-tools/adb -P 5037 -s 84B7N15A04002822 forward tcp\:4724 tcp\:4724'
[debug] [UiAutomator] Starting UiAutomator
[debug] [UiAutomator] Moving to state 'starting'
[debug] [UiAutomator] Parsing uiautomator jar
[debug] [UiAutomator] Found jar name: 'AppiumBootstrap.jar'
[debug] [ADB] Running '/home/qata/tools/platform-tools/adb -P 5037 -s 84B7N15A04002822 push /home/qata/.linuxbrew/lib/node_modules/appium/node_modules/appium-android-bootstrap/bootstrap/bin/AppiumBootstrap.jar /data/local/tmp/'
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/home/qata/tools/platform-tools/adb -P 5037 -s 84B7N15A04002822 shell ps'
[ADB] No uiautomator process found to kill, continuing...
[debug] [UiAutomator] Starting UIAutomator
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","84B7N15A04002822","shell","uiautomator","runtest","AppiumBootstrap.jar","-c","io.appium.android.bootstrap.Bootstrap","-e","pkg","com.hp.android.printservice","-e","disableAndroidWatchers",false,"-e","acceptSslCerts",false]
[debug] [UiAutomator] Moving to state 'online'
[AndroidBootstrap] Android bootstrap socket is now connected
[debug] [ADB] Getting connected devices...
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Client connected
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/home/qata/tools/platform-tools/adb -P 5037 -s 84B7N15A04002822 shell dumpsys window'
[AndroidDriver] Screen already unlocked, doing nothing
[debug] [ADB] Device API level: 27
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/home/qata/tools/platform-tools/adb -P 5037 -s 84B7N15A04002822 shell am start -W -n com.hp.android.printservice/com.hp.android.printservice.preferences.ActivityLegalNotice -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 --es activity-flow /automation'
[Appium] New AndroidDriver session created successfully, session 358239e2-4823-45d9-812c-9ce7e0d5962f added to master session list
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1525716795895 (11:13:15 GMT-0700 (PDT))
[debug] [MJSONWP] Responding to client with driver.createSession() result: {"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"optionalIntentArguments":"--es activity-flow /automation","deviceName":"Nexus 6P","udid":"84B7N15A04002822","app":"/home/qata/Documents/Apps/hpps/HPLegacyPlugin_18.2.139.apk","newCommandTimeout":3600,"platformVersion":"8.0","appPackage":"com.hp.android.printservice","platformName":"Android","appActivity":"com.hp.android.printservice.preferences.ActivityLegalNotice"},"optionalIntentArguments":"--es activity-flow /automation","deviceName":"84B7N15A04002822","udid":"84B7N15A04002822","app":"/home/qata/Documents/Apps/hpps/HPLegacyPlugin_18.2.139.apk","newCommandTimeout":3600,"platformVersion":"8.1.0","appPackage":"com.hp.android.printservice","platformName":"Android","appActivity":"com.hp.android.printservice.preferences.ActivityLegalNotice","deviceUDID":"84B7N15A04002822","deviceScreenSize":"1440x2560","de...
[HTTP] <-- POST /wd/hub/session 200 9116 ms - 1145
[HTTP] 
[HTTP] --> POST /wd/hub/session/358239e2-4823-45d9-812c-9ce7e0d5962f/appium/app/strings
[HTTP] {"sessionId":"358239e2-4823-45d9-812c-9ce7e0d5962f","language":"en-USA"}
[debug] [MJSONWP] Calling AppiumDriver.getStrings() with args: ["en-USA",null,"358239e2-4823-45d9-812c-9ce7e0d5962f"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/home/qata/tools/platform-tools/adb -P 5037 -s 84B7N15A04002822 shell rm -rf /data/local/tmp/strings.json'
[debug] [AndroidDriver] Extracting strings from apk
[debug] [AndroidDriver] /home/qata/Documents/Apps/hpps/HPLegacyPlugin_18.2.139.apk
[debug] [AndroidDriver] en-USA
[debug] [AndroidDriver] /tmp/com.hp.android.printservice
[debug] [ADB] Extracting strings for language: en-USA
[ADB] Checking whether aapt is present
[ADB] Using aapt from /home/qata/tools/build-tools/27.0.3/aapt
[debug] [ADB] There is no 'en-rUSA' configuration. Replacing it with '(default)'
[ADB] Successfully extracted 712 strings from '/home/qata/Documents/Apps/hpps/HPLegacyPlugin_18.2.139.apk' resources for '(default)' configuration
[debug] [ADB] Running '/home/qata/tools/platform-tools/adb -P 5037 -s 84B7N15A04002822 push /tmp/com.hp.android.printservice/strings.json /data/local/tmp'
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"updateStrings","params":{}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"updateStrings","params":{}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: updateStrings
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Loading json...
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] json loading complete.
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":true}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [MJSONWP] Responding to client with driver.getStrings() result: {"dialog_body__remove_unsupported_files":["This file is unsupported or corrupted and cannot be printed:\\n\\n%1$s","The following files are unsupported or corrupted and cannot be printed:\\n\\n%1$s"],"dialog_title__remove_unsupported_files":["Unsupported File","Unsupported Files"],"Discovery_DNS_Search_Domain":"Discovery_DNS_Search_Domain","Discovery_DNS_Search_Domain_Description":"A comma separated list containing one or more DNS search domains for use in printer discovery.","Discovery_DNS_Search_Domain_Title":"DNS Search Domain","Discovery_DNS_Server_IP_Address":"Discovery_DNS_Server_IP_Address","Discovery_DNS_Server_IP_Address_Description":"A comma separated list containing one or more DNS server IP addresses for use in printer discovery.","Discovery_DNS_Server_IP_Address_Title":"DNS Server IP Address","Discovery_Disable_WiFi_Direct_Printer_Discovery":"Discovery_Disable_WiFi_Direct_Printer_Discovery","Discovery_Disable_WiFi_Direct_Printer_Discovery_Description":"An integer value that can take on one of ...
[HTTP] <-- POST /wd/hub/session/358239e2-4823-45d9-812c-9ce7e0d5962f/appium/app/strings 200 758 ms - 39993
[HTTP] 
[HTTP] --> POST /wd/hub/session

I also tried 10 times. The error can be reproduced 10 times. 1st app is successful, 3rd app is failed.

**Comment by mykola-mokhnach** [comment]
UIA2 driver uses different approach to send commands to the driver and something in your network setup prevents it from proxying the commands properly. I have no idea what. Closed as not an issue.

**Comment by haihoangtran** [comment]
Do you have any suggestion for setting up proxy in appium? I appreciate for any help from you.
