### ISSUE TITLE
Appium is not able to read text fields with input type password

### ISSUE THREAD

**Issue by shewale29** [appium/appium#10655]
## The problem

 Appium is not able to read text fields with input type password. The text field appears blank. 

## Details

We tried assigning the text to custom attribute so that we don't have to change the input field type. However, custom attribute field is not accessible to appium. Is there a way to read from custom attribute.

**Comment by mykola-mokhnach** [comment]
I assume it is by design. Appium receives the information from XCTest, and the latter reads it from Accessibility. This means if you don't see the value in the system accessibility inspector and it won't be visible by Appium and vice versa.
