### ISSUE TITLE
app element tree (on IOS) not looking good

### ISSUE THREAD

**Issue by orevron** [appium/appium#10653]
## The problem
i have a react native app that i want to test
when i open the appium app inspector with the android version of this app, the element tree is looking well and i can identify all elements as i want too.. 
but when i try the ios version all the accessibility ids that i added (those that seen good on android) are all on the same element (see attachment for screenshot to understand better)

## Environment
* Appium version (or git revision) that exhibits the issue: 1.7.2
* Desktop OS/version used to run Appium: High Sierra 10.13.4
* Node.js version (unless using Appium.app|exe): 9.8.4
* Mobile platform/version under test: 11.3
* Real device or emulator/simulator: android emulator -> looking good; ios simulator -> not good
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs
https://gist.github.com/orevron/75a818ee0640dd81bc1fbb1e642de3ea

the app is here: [https://drive.google.com/open?id=1idGFzK-Ry229bqU6v6f0_zYPlR5yCh3o](url)

**Comment by mykola-mokhnach** [comment]
Use Safari remote debugger to debug webviews. Appium inspector is only designed to inpect native context

**Comment by orevron** [comment]
it's react native app, not webview
