### ISSUE TITLE
Appium 1.8.0 does not use specified Android appActivity to bring application to front

### ISSUE THREAD

**Issue by zgoda-mobica** [appium/appium#10657]
## The problem

Appium does not use `appActivity` I specified in desired caps to bring application from background, always uses `.activity.MainActivity` instead.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0
* Desktop OS/version used to run Appium: Linux x86-64
* Mobile platform/version under test: Android 6.0.1
* Real device or emulator/simulator: Samsung Galaxy S5
* Appium CLI or Appium.app|exe: Appium Desktop 1.6.0

## Details

The application I am testing has specified different activity as launcher. I already specified `appActivity: .activity.setup.WelcomeActivity` in desired capabilities and indeed this activity is properly used when starting application. But calling `driver.background_app()` I get "The permission to start '.activity.MainActivity' activity has been denied.Make sure the activity/package names are correct." error when driver tries to bring application back to front (I am using Python client but this should not be relevant here).

## Link to Appium logs

https://gist.github.com/zgoda-mobica/bb8e158a9db003de6e6ad4134fa2c942

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium-android-driver/blob/b8e9d3472c9f2f785368d94fcb3b4a21b267ede9/lib/commands/general.js#L99

As you can see there the app is only restored with the activity and package name provided in desired capabilities if the focused activity/package are the same as there were set before. The currently focused activity/package names are taken instead if these differs.

**Comment by zgoda-mobica** [comment]
That's a kind of problem because focused activity when sending app to background is not a launcher. What can I do about this?

**Comment by mykola-mokhnach** [comment]
Actually, yoy can try a workaround even with the current build. Just call background with -1 duration to leave the app there and then call `activateApp` with the actual application id in order to restore it.

**Comment by mykola-mokhnach** [comment]
Perhaps, you are using outdated client lib. activateApp is now available for both iOS and Android: https://github.com/appium/java-client/blob/b4ab1f4915b2829b43a63c05873de0f5016a9f61/src/main/java/io/appium/java_client/InteractsWithApps.java#L148

**Comment by zgoda-mobica** [comment]
I'm using latest Python client https://pypi.org/project/Appium-Python-Client/

**Comment by mykola-mokhnach** [comment]
It should be available there as well

**Comment by mykola-mokhnach** [comment]
It's Python, dude. What prevents you from calling
```
https://github.com/appium/python-client/blob/48b26a548f1f81546e31925840c4b49a957430aa/appium/webdriver/webdriver.py#L801
```

directly from your code?

**Comment by mykola-mokhnach** [comment]
the improvement has been merged to appium@beta
