### ISSUE TITLE
IOS Simulator Safari Mobile Browser- WebElement Click() and SendKeys() causes error when element is Displayed is false when it is visible

### ISSUE THREAD

**Issue by crs2m5smith** [appium/appium#10656]
## The problem

I am getting the error
The element '"" StaticText' is not visible on the screen and thus is not interactable

## Environment

Appium Desktop 1.5.0 and Appium Server 1.7.2
iOS 11.3
xCode 9.3
Mobile Safari browser
Any Simulators

## Details

The page is a simple login page with an input element with id="Email"
It is clearly visible on simulator and the Displayed property is always false, thus breaking when it calls Click() or SendKeys()

## Link to Appium logs

https://gist.github.com/crs2m5smith/5ffb16094d59cc13db20657143cd3232

## Code To Reproduce Issue [ Good To Have ]

WebElement that is on screen
.SendKeys()
.Click()

**Comment by mykola-mokhnach** [comment]
Try Appium 1.8

**Comment by crs2m5smith** [comment]
I should say I am using Appium Desktop 1.5.0 and Appium Server 1.7.2. I updated my Issue. I have not seen an Appium Desktop update as of yet?

**Comment by mykola-mokhnach** [comment]
You can still use Appium desktop with appium server installed via npm

**Comment by crs2m5smith** [comment]
Ok, I will start process of updating Appium Server to 1.8 and see if it resolves and update issue if so, thanks

**Comment by mykola-mokhnach** [comment]
BTW, does your application have a webview?

**Comment by mykola-mokhnach** [comment]
If the element is a part of a web view then you should change the context in order to interact with it.

**Comment by crs2m5smith** [comment]
Sorry, updated issue again. I am simply testing mobile browser, not application

**Comment by mykola-mokhnach** [comment]
Then you must switch to web view context. It is not guaranteed that elements visibility and other attributes are detected properly if you are in the native context

**Comment by crs2m5smith** [comment]
I am new to iOS Appium and not sure what you mean by web view context. Do you have quick link or example to be more clear? Thanks I will look into doing it that way

**Comment by crs2m5smith** [comment]
Thank you, are you suggesting something along this line for this situation:

`var driver = new IOSDriver<AppiumWebElement>(new Uri("https://127.0.0.1:4723/wd/hub"),caps);
driver.Navigate().GoToUrl("https://www.google.com");

//driver.Contexts gives error
//driver.Context equals NATIVE_APP
//driver.Context = "WEBVIEW_1" gives error`
