### ISSUE TITLE
alerts not handling issue with context switching

### ISSUE THREAD

**Issue by seshusangeetha** [appium/appium#10650]
Hi, I tried the default alert handling methods and using the text or other identifiers (XCUITest elements) for the alert but nothing is working. Even the basic driver.switch_to.alert() is not working and throwing the error "Could not connect to a valid app after 20 tries." I am using ios11 with Xcode 9 and Appium 1.7.2 with java

**Comment by mykola-mokhnach** [comment]
It is not possible to advice anything without having a proper issue descripiton
