### ISSUE TITLE
Python bindings: UiAutomator2 can't input into text field

### ISSUE THREAD

**Issue by gergm** [appium/appium#10662]
## The problem

Tests that work fine with the default "AndroidDriver" do not work with "AndroidUiautomator2Driver" because the latter cannot input text into a TextView element

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0; Appium-Python-Client 0.26
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 10.13.4
* Node.js version (unless using Appium.app|exe): 8.2.1
* Mobile platform/version under test: Pixel 2 API 27; Android 8.1
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe:

## Details

When using the default automator, ie, do not set the desired capability automationName. The test enters text into a TextView in the app without problems using webdriver.set_value(element, value).

The same test code fails to change the element value when the desired capability automationName is set to uiautomator2. For this case, I have tried both webdriver.set_value(element, value) and element.set_text(value). Both of which report success but do not change the value of the element.

## Link to Appium logs

GIST for the appium server log for the UiAutomator2 case with the bug https://gist.github.com/gergm/765e9484ec60f6ab805aa68414ee522c

GIST for the appium server log for the AndroidDriver case which works https://gist.github.com/gergm/ea6e234ea019a5edd184051e03abfa43

**Comment by mykola-mokhnach** [comment]
I don't see any errors in the log. Try `send_keys`

**Comment by gergm** [comment]
@mykola-mokhnach Thanks for your suggestion. I have tried both element.send_keys and element.set_text and both produce the same behavior, ie, no errors but no change in the element.

I have also tried element.click() which works OK, ie, moves the cursor to the TextView and pops up the soft keyboard.

After the click, I was also able to enter a single character with webdriver.press_keycode(31). But subsequent webdriver.press_keycode calls timed out. I'll post the logs for that situation soon.

**Comment by gergm** [comment]
I now have a work-around, where I do the initial element.click() on the TextView element, which exposes an EditText element and I do driver.set_value(EditTextElement, value)

Here is the log for that case: https://gist.github.com/gergm/a5eb4141e98b0d77f835a7ea03573e5d

imo, there is definitely a bug in UiAutomator2 because it returns success from the set_value call without actually setting the value.

**Comment by mykola-mokhnach** [comment]
I think such verification can be added though. Will mark it as an improvement

**Comment by gergm** [comment]
Thanks!

**Comment by mykola-mokhnach** [comment]
The has been merged to beta
