### ISSUE TITLE
Unable to clear text field in iOS

### ISSUE THREAD

**Issue by mayankgupta804** [appium/appium#10669]
## The problem

I am trying to clear text in a text field, but it's not working. This issue seems to be happening only on iOS and not on Android.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Desktop OS/version used to run Appium: macOS High Sierra 10.13.33
* Mobile platform/version under test: iOS 11.2
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium.app

## Details

My objective is to type text in a text field, but for that, I need to clear the text that is already present there. However, I am unable to clear the text using <webelement>.clear() and even after<webelement>.sendKeys() is not clearing the text in the text field, so the text that I am typing in the text field is appending to the text that is pre-filled.

**Comment by mykola-mokhnach** [comment]
Please attach the server log. 
Are you in webview or this is native context?

**Comment by nedo** [comment]
Hi, I am able to reproduce this behavior, unable to clear textfields please have a look on server responce, 

remote_connection.py       480 DEBUG    POST http://127.0.0.1:4723/wd/hub/session/deb62ca1-1b4b-4644-ae1c-f4a53c610fd5/element/2A000000-0000-0000-C007-000000000000/clear {"id": "2A000000-0000-0000-C007-000000000000", "sessionId": "deb62ca1-1b4b-4644-ae1c-f4a53c610fd5"}
remote_connection.py       567 DEBUG    Finished Request b'{"value":{"error":"unknown error","message":"An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 \\"Keyboard is not present\\" UserInfo={NSLocalizedDescription=Keyboard is not present}","stacktrace":"UnknownError: An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 \\"Keyboard is not present\\" UserInfo={NSLocalizedDescription=Keyboard is not present}\\n    at errorFromMJSONWPStatusCode (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:772:10)\\n    at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:797:13)\\n    at asyncHandler$ (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:352:37)\\n    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)\\n    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)\\n    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)\\n    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)\\n    at <anonymous>"}}'

**Comment by mykola-mokhnach** [comment]
> Original error: Error Domain=com.facebook.WebDriverAgent Code=1 \"Keyboard is not present\" UserInfo={NSLocalizedDescription=Keyboard is not present}\n

It is the issue with the device itself. there is nothing we can do about this. Try to reset the device under test.

**Comment by nedo** [comment]
I am working on simulator(iOS 11.3), have not yet setup on Real device.

**Comment by nedo** [comment]
Hi, can you please give more info, It used to work fine. I've a couple of steps in my situation to clear text-field, is there something changed somewhere ? 

any details will be appreciated, Thankss

**Comment by Anmol-a** [comment]
Get the xpath of "delete" button of keyboard and put it through For Loop and click on that element till the value of textFIELD is cleard i had faced this issue very badly and this is the only option which worked in my case

**Comment by SharmaKKamal** [comment]
The verified solution for clearing the text in IOS Simulator or device
MobileElement element = driver.findElement(By.id("id_data"));
Rectangle rectangle = element.getRect();
int YAxis = element.getCenter().getY();
int XAxis = rectangle.getWidth();
TouchAction action = new TouchAction(this.getIOSDriver());
action.tap(TapOptions.tapOptions().withPosition(PointOption.point(XAxis, YAxis))).perform();
element.clear();

Verified on Simulator iOS 14.3 with appium 1.21.0
