### ISSUE TITLE
--reboot doesnot work on android8.1

### ISSUE THREAD

**Issue by kingkong2013** [appium/appium#10661]
## The problem

`appium --reboot` does not work as document described, for example, I want to automatically start android emulator with name nexus6__8.1 (`${avdDevice}__${caps.platformVersion}`), it have no response.
because android studio saved the emulator with the name nexus6_8.1,  missed one underscode.
please checked ~/.android/avd

if I renamed from nexus6_8.1 to nexus6__8.1.(include the key in *.ini), the emulator can start and close automatically.

## Environment

* Appium version (or git revision) that exhibits the issue:
--Appium 1.8.0 on android 8.1
* Desktop OS/version used to run Appium:
--Mac 10.13.3 
* Node.js version (unless using Appium.app|exe):
--npm 5.5.1
* Mobile platform/version under test:
--android 8.1(Google APIs)
* Real device or emulator/simulator:
--Nexus6.0 emulator

**Comment by mykola-mokhnach** [comment]
Closed as inactive
