### ISSUE TITLE
Not able to click on GBoard keyboard's Search icon(magnifier) button

### ISSUE THREAD

**Issue by joshidipakkumar** [appium/appium#10665]
## The problem

I have enter some text in text box after that i need to hit Search button from GBoard (softkeyboard).
I have used below code but it dint work. If i use KEYCODE_1 or any other then it's working.
driver.pressKeyCode(AndroidKeyCode.KEYCODE_SEARCH);

## Environment

* Appium version : 1.6
* Windows 10
* Node.js version: 8.9.1
* Mobile platform/version under test: 5.1.1
* Real device or emulator/simulator: Real device (Lenovo PHAB Plus)
* Appium CLI or Appium.app|exe: Dont know

## Details

If necessary, describe the problem you have 
[appium-server-logs.txt](https://github.com/appium/appium/files/1983781/appium-server-logs.txt)
been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
How this is related to Appium server? Sending a key simply triggers the corresponding action on the server side. Appium works as a proxy there.

**Comment by joshidipakkumar** [comment]
As other KEYCODE are properly executed just Enter and Search keycode are not executed so thought it might be issue from Appium. Do you have any solution for this?

**Comment by mykola-mokhnach** [comment]
No idea. I might say more if I'd knew how the application under test handles keypress on the particular control in the source code.
