### ISSUE TITLE
Appium don't use older chromeDriver version

### ISSUE THREAD

**Issue by Dento55** [appium/appium#10673]
## The problem
I wrote chromeDriver mappings json file to automatically select older driver for older android devices to use chromedriverExecutableDir capability. But Appium uses newest on the list.   If newest version in the list is 2.35 it uses this version. If I used fixed chromedriver version 2.28 by
 ` appium --chromedriver-executable /path/to/my/chromedriver` it works fine for Android 5.1 device.

As I understand Appium 1.8.0 should dynamically select suitable chromeDriver for each Android device.
I use multiple devices from Android 5.1 to 8.0. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Win 10 64 bit
* Node.js version (unless using Appium.app|exe): 
* Mobile platform/version under test: Android 5.1
* Real device or emulator/simulator: Motorola Moto G
* Appium CLI or Appium.app|exe:

## Link to Appium logs
https://gist.github.com/Dento55/e777cb056e67ff480fa4e765233e9627

**Comment by imurchie** [comment]
Try removing the `.0` from the minimum chrome version in the mapping file. That is, instead of `65.0.3325.0`, give `65.0.3325`.

**Comment by mykola-mokhnach** [comment]
@imurchie Shouldn't semver properly handle such conversion automatically?

**Comment by imurchie** [comment]
No, that's not valid semver. https://github.com/appium/appium-chromedriver/pull/79 will fix the issue on our side by coercing it.

**Comment by mykola-mokhnach** [comment]
the fix has been merged to beta

**Comment by Dento55** [comment]
Removing `.0` works.  
Thanks for fast response!
