### ISSUE TITLE
Getting Timeout exception in IDE after 60secs even when 'newCommandTimeout' capability is given

### ISSUE THREAD

**Issue by Gocoollnath** [appium/appium#10672]
## The problem

Getting Timeout exception after 60secs in IDE,even when 'newCommandTimeout' capability is given. Server window waits for time given in the capability but the script doesn't run after app installation.

## Environment

* Appium version 1.8.0
* Desktop OS/version used to run Appium:  Windows 10 Pro
* Node.js version (unless using Appium.app|exe): 8.10.0
* Mobile platform/version under test: Android API 25 ,v7.1.1
* Real device or emulator/simulator: Real Device Samsung Tab
* Appium CLI or Appium.app|exe: both
* IDE: VisualStudio 2017 Enterprise and C# as coding language

## Details

If necessary, describe the problem you have been experiencing in more detail. Manually deleted AppiumSettings and Unlock files from device and tried, it isn't working. App gets installed to the device successfully(after 60 seconds) but script doesn't run

## Link to Appium logs

https://gist.github.com/Gocoollnath/08735d81ecce1ce068ba48c2a0cc89e0

IDE logs:
[IDE.log](https://github.com/appium/appium/files/1987765/IDE.log)

## Code To Reproduce Issue [ Good To Have ]

            DesiredCapabilities dc = new DesiredCapabilities();
            dc.SetCapability("deviceName", "Android device");
            dc.SetCapability("newCommandTimeout", 180);
           
            dc.SetCapability("app", "app path");
            
            dc.SetCapability("appWaitActivity", "*.Activity");
            dc.SetCapability("appWaitDuration", "40000");
            
            dc.SetCapability("autoGrantPermissions", true);
            driver = new AndroidDriver<AndroidElement>(new Uri("http://127.0.0.1:4723/wd/hub"), dc);

**Comment by mykola-mokhnach** [comment]
> but the script doesn't run after app installation

Which "script" do you expect to run? I don't observe any issues in the log.

**Comment by Gocoollnath** [comment]
The code given here is used to launch the app. But login method follows this initial setup. App gets installed and the activity mentioned in appwaitactivity gets displayed. In IDE script gets failed and state that timeout has happened. In Appium Server window, connection is ON and gets closed only after the 'newCommandTimeout' capability specified timing. Please, have a look at the IDE.log attached above.

**Comment by mykola-mokhnach** [comment]
This looks like a problem with a client. The server simply does not receive any commands from it and thus times out. Please report to https://github.com/appium/appium-dotnet-driver
