### ISSUE TITLE
Auto grant permissions (desired capability)  is not working with Appium 1.8.0 on Android devices

### ISSUE THREAD

**Issue by QA2Dev** [appium/appium#10678]
## The problem

**Auto grant permissions** desired capability is not working with Appium 1.8.0 on Android devices

## Environment

Device: Samsung Tab S3 (Real device - Smartphone)
Android OS: 7.0
Appium Version: 1.8.0
MacOS : 10.13.2
Xcode: 9.2
JavaClient: 5.0.4

## Details

Permission alerts which pop up while launching application is not automatically being accepted even though we set the desired capability  **Autograntpermissions** to true in **Appium 1.8.0 version** but ,in **Appium 1.7.2 version it is working.**

## Link to Appium logs

https://gist.github.com/QA2Dev/7957ba16d73b19020cd1b95abfd4d6dc

## Code To Reproduce Issue [ Good To Have ]
        DesiredCapabilities caps = DesiredCapabilities.android()
        caps.setCapability("platformName", "Android")
        caps.setCapability("deviceName", " SamsungTabS3_7.0_Local")
        caps.setCapability("deviceType","tablet")
        caps.setCapability("platformVersion", "Android")
        caps.setCapability("app", "app/path.apk")
        caps.setCapability("app-package", ProjectConstants.AppPackage.com)
        caps.setCapability("newCommandTimeout", 150000)
        caps.setCapability("androidInstallTimeout",150000)
        caps.setCapability("autoGrantPermissions", true)
        caps.setCapability("automationName", "UiAutomator2")

**Comment by mykola-mokhnach** [comment]
> [debug] [ADB] Running '/Users/e001844/android-sdk-macosx/platform-tools/adb -P 5037 -s 8fcbfe43 shell pm dump com.lego.dpt.connect'
> [ADB] com.lego.dpt.connect contains no permissions available for granting.

Do you see any required permissions if the command above is executed from the command line?

**Comment by QA2Dev** [comment]
Yes it asked for Location and Bluetooth permissions

**Comment by mykola-mokhnach** [comment]
Can you attach the whole output here?

**Comment by QA2Dev** [comment]
https://gist.github.com/QA2Dev/1974e7121729e7eaf33416ac0596c3cb

**Comment by QA2Dev** [comment]
When I'm launching application, a pop up is shown stating as follows  "Allow application to access this device's location".

**Comment by mykola-mokhnach** [comment]
Can it be that the app manifest is incorrect and it is necessary to include the ACCESS_FINE_LOCATION permission there as well?

**Comment by mykola-mokhnach** [comment]
Also, what is the actual permissions state if you open the corresponding tab of application settings in the System  Settings snap-in?

**Comment by QA2Dev** [comment]
Bluetooth and Location is enabled manually before launching application

**Comment by mykola-mokhnach** [comment]
I don't observe any issues there on the server side.

**Comment by QA2Dev** [comment]
Since I'm not able to accept the permissions, given/focused package name is not identified (Getting message as Incorrect package and activity) and application is not getting launched.
Is there any way to accept the permissions without desired capability ?.

**Comment by mykola-mokhnach** [comment]
@vmaxim Do you have anything to add?

**Comment by QA2Dev** [comment]
Kindly let me know if there is another way to handle this alert (permissions) and continue the app to launch( with out getting closed ). App-package passed through capability is "com.lego.dpt.connect" but package found is "'com.google.android.packageinstaller'".

**Comment by mykola-mokhnach** [comment]
@vmaxim Do we really need this? One can still set `appWaitActivity/appWaitPackage` caps in order to handle such alerts on startup

**Comment by KazuCocoa** [comment]
```
[ADB] com.lego.dpt.connect contains no permissions available for granting.
[debug] [AndroidDriver] Performed fast reset on the installed 'com.lego.dpt.connect' application (stop and clear)
```

What about uninstalling the app once and running again?
The test app should install with `-g` if the app isn't in test device and   `autoGrantPermissions` is `true`.
https://github.com/appium/appium-android-driver/blob/44374b50bbb0d3ff13b0833d7e3eb4699581df4b/lib/android-helpers.js#L273

**Comment by vmaxim** [comment]
@mykola-mokhnach Makes sense, but anyway it's easier to manage these cases on test level instead of session caps.

**Comment by QA2Dev** [comment]
@vmaxim Granting permissions during runtime is actually working in **Appium 1.7.2 version**, but not in the Appium 1.8.0, let me know if there is a possible way  to handle it on app startup. I cannot even use Alert interface methods to accept/dismiss the pop up, since the control of execution is held up there it self identifying for the focused package (not going to next line of code)

**Comment by KazuCocoa** [comment]
Installing with `-g` is the same process with 1.7.2. (https://github.com/appium/appium-adb/pull/290/files)
So, could you try https://github.com/appium/appium/issues/10678#issuecomment-388071225 ?
( to make sure if something happens or not in https://github.com/appium/appium-adb/blob/8c118227e635c2c41ef557f45f71fc2a666f9e67/lib/tools/apk-utils.js#L381-L390 )

**Comment by QA2Dev** [comment]
@KazuCocoa May I know how to pass the arg "-g" to install application with Appium 1.8.0 ?..

**Comment by KazuCocoa** [comment]
@QA2Dev 
What about the followings?

1. uninstall your test target app
2. Run the test script
    - Then, the test target app should install `-g` option if you set `autoGrantPermissions: true`

Or

1. Set `fullReset: true` capability
2. Run your test script
    - Then the test target will uninstall once and re-install with `-g` option if you set `autoGrantPermissions: true`

----

My previous comment, https://github.com/appium/appium/issues/10678#issuecomment-388071225 , has the link to the code.
> What about uninstalling the app once and running again?

**Comment by levyshachar2** [comment]
Sorry to bring this post up again , but I'm currently experiencing the same issue.
I did what @KazuCocoa recommended and it works, but now every tests reinstall the app which is kind of an overkill (it will extends our overall test run)
is there any other way without using fullReset : true ?

thank you

**Comment by KazuCocoa** [comment]
Thanks, let me consider.

**Comment by KazuCocoa** [comment]
https://github.com/KazuCocoa/appium-adb/tree/issue-grant-permission-everytime
I haven't investigated enough yet, but I remove skipping granting permission logic tentatively.
If you have a time to use the branch, could you try it? @levyshachar2 

https://github.com/KazuCocoa/appium-adb/commit/4b808115eda2187064707114c4b6db795f13934a

**Comment by levyshachar2** [comment]
Yeah sure, how can I get your commit and run it locally?

**Comment by KazuCocoa** [comment]
For example, you can run it like below.

```
git clone git@github.com:appium/appium.git
cd appium
npm install
cd node_modules
rm -rf appium-adb
git clone git@github.com:KazuCocoa/appium-adb.git
cd appium-adb
git checkout issue-grant-permission-everytime
npm install
cd ../..
node . # start node app
```

**Comment by levyshachar2** [comment]
I tried to run my tests again , with fullReset set to false .
it seems the original issue remains.
I get permission popup during my test execution (in my case it's location)

how can I be sure that my tests run with your commit changes?

**Comment by KazuCocoa** [comment]
Could you attach the server log?
I’d like to confirm some lines like “...contains no permissions...”.

**Comment by KazuCocoa** [comment]
I couldn't see any logs in https://github.com/KazuCocoa/appium-adb/commit/4b808115eda2187064707114c4b6db795f13934a#diff-83add4eba9c23315341d94aec97ce76bR184 . I wonder your target sdk wasn't over 23.

Could you run again after pull https://github.com/KazuCocoa/appium-adb/tree/issue-grant-permission-everytime ?
(I've added <code>log.debug(`apiLevel is: ${apiLevel}, targetSdk is: ${targetSdk} for grantAllPermissions`);</code>)

**Comment by levyshachar2** [comment]
I tried to run again after pull , but I don't see anything in the log (searched for "grantAllPermissions")
from the logs , my device SDK is 23.
"19-06-2018;15:22:07.880 [Thread-8] DEBUG media.muvix.framework.AppiumRunnable - appium :[debug] [ADB] Current device property 'ro.product.manufacturer': OnePlus
19-06-2018;15:22:07.881 [Thread-8] DEBUG media.muvix.framework.AppiumRunnable - appium :[debug] [ADB] **Device API level: 23**"


these are the commands i run in order to update
cd /appium/node-modules/appim-adb
git pull
npm run build

and I updated my tests to use Appium from my installation directory (not the /usr/...)

**Comment by levyshachar2** [comment]
Currently i have 
`noReset: true`
`fullReset: false`

do you want me to add another
`fastReset: true?`

**Comment by KazuCocoa** [comment]
Ah, you can enable `fastReset` with `noReset: false` and `fullReset: false`.(It is default behaviour)

```
this.opts.fastReset = !this.opts.fullReset && !this.opts.noReset;
```

After that, https://github.com/appium/appium-android-driver/blob/d60a24f98655f31d5d57326bce07e594d3002ee9/lib/android-helpers.js#L309 should be `true` and reach `grantAllPermissions` if `autoGrantPermissions` is true.

Except for that, the code doesn't reach `grantAllPermissions`.
The code keep current status.

It means if a test target app installed and `noReset`, Appium keep the installed app. If the installed app wasn't installed with `-g`, the `noRest` keep it.

**Comment by levyshachar2** [comment]
Hi @KazuCocoa , sorry for the late response, I was in vacation for a few days.
It seems like the app is getting permission with `noReset: false` and `fullReset: false`
However, it seems that the app is being reinstalled at every test run.
probably because of the `noReset: false` capability (before i had noReset: true) which brings me back to my first issue.
Every test will need to reinstall the app which impact on the tests execution time.
Maybe there is API in Appium for manually granting permissions?
Thanks

**Comment by KazuCocoa** [comment]
Thanks for the report!

If you use JS client, you can call https://github.com/appium/appium-adb/blob/1930bba72314af3919ebd979b3fefbc05e710785/lib/tools/adb-commands.js#L167
Another way is using `adb shell pm grant your.target.package.name android.permission.WRITE_SECURE_SETTINGS` via http://appium.io/docs/en/commands/mobile-command/
@levyshachar2

**Comment by KazuCocoa** [comment]
And could you give me the server log of https://github.com/appium/appium/issues/10678#issuecomment-399742592 ?
I'd like to ensure some log messages in https://github.com/appium/appium-android-driver/blob/20c9e4a64626897eb74d47852f62fbccf7cba663/lib/android-helpers.js#L305-L341 and surround since I couldn't see them in your previous log  https://github.com/appium/appium/issues/10678#issuecomment-398036825 .

**Comment by yarieldis** [comment]
This capabilities worked for me:

caps["platformName"] = "Android"
caps["platformVersion"] = "7.0"
caps["deviceName"] = "Pixel_C_API_24"
caps["automationName"] = "UiAutomator2"
caps["app"] = "/home/tests/app-debug.apk"
caps["noReset"] = False
caps["autoGrantPermissions"] = True
caps["appPackage"] = "com.mypackage"
caps["appActivity"] = ".MyActivity"

Regards.

**Comment by JeanMaritain** [comment]
@QA2Dev 
manually locate and close that permission alert, then try this:
```python
duration = 0.1
driver.background_app(duration)
```
