### ISSUE TITLE
Appium 1.8.0 - Logcat terminated with code 0, signal null

### ISSUE THREAD

**Issue by lubshilk** [appium/appium#10679]
When running few scenarios random tests suddenly report error: 

> Returned value cannot be converted to WebElement: {stacktrace=ProxyRequestError: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8200 at JWProxy.proxy$ (D:\Jenkins\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\NodeJS\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:152:13) at tryCatch (D:\Jenkins\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\NodeJS\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40) at GeneratorFunctionPrototype.invoke [as _invoke] (D:\Jenkins\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\NodeJS\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22) at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (D:\Jenkins\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\NodeJS\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21) at GeneratorFunctionPrototype.invoke (D:\Jenkins\tools\jenkins.plugins.nodejs.tools.NodeJSInstallation\NodeJS\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37) at <anonymous>, message=Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8200} Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z' System info: host: 'CELL_LAB_8', ip: '192.168.50.8', os.name: 'Windows Server 2008 R2', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_162' Driver info: driver.version: AndroidDriver

Checked in Appium server log:

> error: [Logcat]* Logcat terminated with code 0, signal null*

All following the failure tests don't run - looks like Appium disconnected from device

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0
* Last Appium version that did not exhibit the issue (if applicable): 1.7.1
* Desktop OS/version used to run Appium: Windows 2008 R2
* Node.js version (unless using Appium.app|exe): 8.11.1
* Mobile platform/version under test: Android 5.1
* Real device

## Link to Appium logs
https://gist.github.com/lubshilk/0b631f240215e735bd2730d41d794d24

Note: I've seen the same problem was reported for 1.6.5 on MAC (https://github.com/appium/appium/issues/8743)

Is there any solution for Windows? Is the problem the same in Server 1.8.0

**Comment by lubshilk** [comment]
Additional information. 
We tried to run on Android 8 device. Here it also looks like connection is broken as well
TC catches exception when tries to find element: "java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:33175 Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z' System info: host: 'CELL_LAB_8', ip: '192.168.50.8', os.name: 'Windows Server 2008 R2', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_162' Driver info: driver.version: RemoteWebDriver"
On trying to catch screenshot immediately after the above error reported:
Session ID is null. Using WebDriver after calling quit()? Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z' System info: host: 'CELL_LAB_8', ip: '192.168.50.8', os.name: 'Windows Server 2008 R2', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_162' Driver info: driver.version: RemoteWebDriver 

In Appium server there is no report at all for the same time (the above problems reported at 19:15). In appium server log there are only lines for 18:56 (the previous test) and 03:27 the next day we stopped the job to run:
2018-05-09 18:56:34:984 - info: [debug] [JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8200/wd/hub/session/4809e334-a984-41ce-9acb-bb5cbf7aca07/screenshot] with no body
2018-05-10 03:27:53:522 - info: [debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"4809e334-a984-41ce-9acb-bb5cbf7aca07\",\"status\":0,\"value\":\"iVBORw0KGgoAAAANSUhEUgAABaAAAAoACAIAAADIlhKYAAAAAXNSR0IArs4c6QAAAANzQklUCAgI\\n2+FP4AAAIABJREFUeJzMfXeYHcWV76num\\/PkoJnRaEZZKIAkogRIBIMR4ACGdfrs53XG9trG6zXe\\n9HafCTa767DsLm\\/X3vVbp3U2OQgECIxEVEA5S5PzzaFDvT96ptXTFbq67x3B+fTpu1NddepU1Qm\\/\\nOt1djaJ\\/\\/hoAIAQAgDFYCaGzJdbfLBKpI1LTkQ8prbVEpDnGs\\/53JTyH27mkc98jVYAq523u+HsT\\nCQgtsgnAkYp1iWpHVItjScUyQ3EmZNsq63O6nrsloy4Kqzv+5AiqXzWCsYQ5B\\/PjoReq3oKwdlXT\\nEXm1trrqgbMrW3YriWcS8UU1VOy5WKm5oBqCk5pU88CkJtPoqJDe0A4\\/5AEwR2E2ZNXhiOFBVL61\\n8gv5lb2tjmC0mmscJViZ40bEXUr1wtR8FUgJAWoWYqhw7hy4RHHP7MF8qnFf1agxCKwLB5aDkyPy\\nIB4LAvG7s9UR30F4EFjEm1Wzsvxe+A1rawhufZfxvxy47FPWC7YfVF7WataanFbVEJ+tZwGold0O\\ngWpmVIb8KeW0ZV2tCdlmz5X8rEsiQxYRzBo5BJuw\\/qx+9jjMWfUd9Za6n3Ts2lVNEaLqgHX+HReU\\nX4FcCNbSeJCfOjkiq+Notpw8hVtu4uToJWrSi5UDOV1VetFa+StDMM5qiojNKqyJponUr3Ie+D7Z\\nlSSskprEQc8kHtwFuVU\\/Od7I7XLbrM+DHQn2ZXXO4j7NQ0euSETrOFpKjTiuVv+cafi56escW7EH\\njFdbQxMpJzWfZQJVClNbtuLhmI\\/Aa7j63kCaW29s1K9mJm0T...

The full Appium server log: https://gist.github.com/lubshilk/6ff0a54b45f93c2b27aa891dcaf04754

**Comment by mykola-mokhnach** [comment]
This error usually happens when the device under test stops to responding to adb commands because of different reasons (like resource leaks, bugs, overheat, oudated adb version, etc). In any case there is nothing one can do on Appium side to fix that.
Closed as duplicate.

**Comment by lubshilk** [comment]
@mykola-mokhnach Sorry for bothering you again on the issue. The problem began to be real headache. 
As WA now we restart Appium server and driver with noReset=true if we receive  "Connection refuse".  The restart process takes about 2 minutes. 
Could you, please, suggest other WA? Is there a way to reload Appium server without stop/start it?

**Comment by mykola-mokhnach** [comment]
I think it is not necessary to restart the whole Appium server, but the local session is lost for sure, since the connection to UIA server is terminated. Try to find the reason why the device is disconnected from ADB. Maybe the device itself is just not good to run long-term tests or it is getting too hot in the lab...

**Comment by lubshilk** [comment]
Thank you for the fast reply :)
By "session restart" dd you mean "driver restart"?
We tried to restart only driver in case of "Logcat terminated", but got this "Connection refused".  
Tester connected via WiFi using IP. Sometimes it disconnects, but before every TC we check and if it disconnected, connecting it (using adb command) and starting new driver. In most cases it works perfectly, till we receive Logcat problem
I'll try to get logcat log from device as suggested here: https://discuss.appium.io/t/retrieving-device-information-through-logs-using-java/10029

**Comment by v3g3t4x** [comment]
we have the same issue on real device and emulated device.

**Comment by notbobutah** [comment]
I experienced this situation today after installing the ios proxy package, after removing it I also had to remove appium and reinstall to resolve the issue.
