### ISSUE TITLE
Appium Parallel execution screenshot captured from wrong device

### ISSUE THREAD

**Issue by haritbe** [appium/appium#10675]
## The problem

I am running 2 instance of appium server simultaneously on my machine. I have attached 2 android devices and 2 instance of appium server are running. scripts are running fine on both device parallely, but while taking screenshot, instead of same device, another device screenshot is captured.

## Environment

* Appium version : 1.7.1
* Desktop OS/version used to run Appium: MAC OS Sierra 10.12.6
* Node.js version (unless using Appium.app|exe): 8.6.0
* Mobile platform/version under test: Android 8.0.0 and Android 6.0.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium Cli

## Details

I have tried setting up different systemPort  as defaultCapability but that does not solve the issue.

**Comment by SrinivasanTarget** [comment]
@haritbe reach out to https://discuss.appium.io for any queries.

**Comment by haritbe** [comment]
@SrinivasanTarget  This is not a query. It's a bug in Appium driver code.

**Comment by saikrishna321** [comment]
can u provide logs ? make sure u have the driver sessions thread safe 
As Srini mentioned parallel session works very well from v1.7.2 and lot of improvement has been made in v1.8.0

**Comment by haritbe** [comment]
@saikrishna321 - did anybody experienced any issues with screenshot and parallel execution in 1.7.1. 

I am currently on 1.7.1.  I am about to upgrade to 1.7.2.  Hopefully it will resolve it.
