### ISSUE TITLE
unable to launch ipa file

### ISSUE THREAD

**Issue by Dayanandmdr** [appium/appium#10670]
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not install app: 'Command 'ios-deploy --id a77a281e05af5793d1b292eaaef151095f1b87c7 --bundle /Users/ifocus/eclipse-workspace/Voot_kidsios/apk/Payload/Voot.app' exited with code 253' (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 72.56 seconds

Plz help ASAP

**Comment by mykola-mokhnach** [comment]
Either you bundle is corrupted or there is a bug in `ios-deploy` tool. In both cases we cannot do anything on Appium side.

**Comment by Dayanandmdr** [comment]
Mykola,

Its a valid bundle id...but bundle id is not accepting in developer tool please help

**Comment by imurchie** [comment]
Try running `ios-deploy --id a77a281e05af5793d1b292eaaef151095f1b87c7 --bundle /Users/ifocus/eclipse-workspace/Voot_kidsios/apk/Payload/Voot.app` and see what the output is.

**Comment by Dayanandmdr** [comment]
imurchie,

thanks but still same error message.
but can you confirm me how to ad bundle id in developer account that might be the problem.
Note:tried some tutorials

**Comment by imurchie** [comment]
What is the output? I don't see that you've given any output.

**Comment by Dayanandmdr** [comment]
saying unknown server side error while processing command.original error: could not install app and the path of app

**Comment by imurchie** [comment]
Please: on the command line, run `ios-deploy --id a77a281e05af5793d1b292eaaef151095f1b87c7 --bundle /Users/ifocus/eclipse-workspace/Voot_kidsios/apk/Payload/Voot.app`

And copy-and-paste the output here.

**Comment by Dayanandmdr** [comment]
2018-05-09 17:16:47.682 ios-deploy[13576:260824] [ !! ] Error 0xe8008018: The identity used to sign the executable is no longer valid. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)

**Comment by Dayanandmdr** [comment]
i pasted in command line and at the end displaying error like this 

2018-05-09 17:16:47.682 ios-deploy[13576:260824] [ !! ] Error 0xe8008018: The identity used to sign the executable is no longer valid. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)

**Comment by imurchie** [comment]
That seems pretty clear. The app needs to be resigned with a valid certificate.

**Comment by imurchie** [comment]
Well, either your team, or Apple, is wrong. There is nothing that Appium can do at this point.

**Comment by Dayanandmdr** [comment]
Thanks, i will check and revert back regarding this
