### ISSUE TITLE
[BUG] [appium-xcuitest-driver] Element found but "displayed" response is empty object

### ISSUE THREAD

**Issue by isnifer** [appium/appium#10676]
## The problem
Hi! Recently my team moved from Appium 1.6.4 to 1.8.0 (Yes, we didn't upgrade to 1.7.0 there were several regressions with `appium` sub-dependencies, we've skipped this version).
Also, we used Xcode 8.3.3 on our CI.
Everything works perfectly until 1st of May when Apple started to reject apps that didn't build with Xcode 9.
We've switched to Xcode 9.3, appium 1.8.0 and got a regression.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0 (appium-xcuitest-driver 2.61.0 - 2.79.3)
* Last Appium version that did not exhibit the issue (if applicable): 1.6.4 (2.27.2 - 2.60.0)
* Desktop OS/version used to run Appium: macOS 10.13.4 (17E199)
* Node.js version (unless using Appium.app|exe): 9.4.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Details
[I have recorded a gif with the process.](https://user-images.githubusercontent.com/1788245/39858364-00ccb32a-543f-11e8-84e9-ba4f70971a00.gif)

1. It's OK to find HOME
2. It's OK to find STORE
3. It trying to find element `~Profile` and it fails on 1.8.0 (2.61.0 — 2.79.3)
2. It found an element, but the response for "displayed" request returns empty object on 1.8.0.

## Link to Appium logs
[Appium 1.8.0 log](https://gist.github.com/isnifer/8fdbac7cc1c8b4f15475bf88ead58aa9)
[Appium 1.8.0 iOS Screen Source](https://gist.github.com/isnifer/a6cea5ed5d4106b3ecbae6d4db8930e2)
[Appium 1.8.0 iOS Screen Shot](https://i.imgur.com/0JkHr8M.png)

## I tried to find a bug but it looks like it was introduced in WebDriverAgent (2.61.0).
I just tried to bump the version of `appium-xcuitest-driver` and find that last version that worked fine was `2.60.0`.

**Comment by mykola-mokhnach** [comment]
There is not much we can do there. Visibility detection is a pain with XCTest. Try to enable `simpleIsVisibleCheck` capability

**Comment by isnifer** [comment]
@mykola-mokhnach thank you, I will try. Please, do not close an issue.

**Comment by Oralce** [comment]
I also happen to this issue, if it is just like what @isnifer said,  it is a bug for appium-xcuitest-driver,  can we only replace the version for appium-xcuitest-driver? is there any workaround for this problem?

**Comment by Oralce** [comment]
And I also try enable simpleIsVisibleCheck capability, still not work.

**Comment by Tumasonis** [comment]
@isnifer Hi, were you able to fix your problem?

**Comment by isnifer** [comment]
@Tumasonis nope, I just rewrote my test :) First two items of menu everytime is visible.
I have a helper `clickUntilVisible(selectorToClick, { waitFor })`.
So I just used as `selectorToClick` my `hidden` button **Profile** and as `waitFor` selector my `visible` button **Home**

**Comment by mykola-mokhnach** [comment]
Closed as inactive
