### ISSUE TITLE
Objects not getting identified for Ionic Apps with the Appium server 1.7.2

### ISSUE THREAD

**Issue by KS261187** [appium/appium#10688]
I am trying to spy the objects for my ionic salesforce app(.ipa) using the Appium server 1.7.2. But when I try to do that I am getting whole object not individual objects. However if I use the latest Appium server, I get to spy the individual objects. Please refer the attached screenshots.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable):1.8
* Desktop OS/version used to run Appium:Mac
<img width="748" alt="screen shot 2018-05-13 at 9 09 54 pm" src="https://user-images.githubusercontent.com/26659582/39975116-4edc47aa-56f2-11e8-8255-0f8dc2ba2f06.png">

* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: 11.3
* Real device or emulator/simulator: iPhone 7
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by dpgraham** [comment]
Appium Desktop only finds elements that are in a native context. Since Ionic uses WebViews, the elements won't be seen.

To debug Ionic apps, you'll need to run a session in a webview context by setting the `autoWebView` capability to `true` (https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md) and then debug using Safari Web Inspector: https://developer.apple.com/safari/tools/

**Comment by KS261187** [comment]
I have already mentioned that it works fine with the latest Appium desktop.If that is the case. How did the objects are getting fine in Appium 1.8 version. I tried changing the autoWebView to true and it says no web view found. Please find the working example for the same app using 1.8 Appium desktop.  I am using app center to run my tests which uses 1.7.1. 
<img width="761" alt="screen shot 2018-05-13 at 9 30 22 pm" src="https://user-images.githubusercontent.com/26659582/39975572-fba871b4-56f4-11e8-943b-48a4539df36c.png">

**Comment by KS261187** [comment]
I see that the issue is already closed. But please refer the attached above screenshot which is a working with the appium 1.8.

**Comment by dpgraham** [comment]
It looks like in the second screenshot you're expanding a different menu (the menu that's adjacent to `SFLoginView`) whereas in the first screenshot you're expanding the first `XCUIElementTypeWindow`. Can you see what happens when you select elements inside the element that's adjacent to `SFLoginView`?

Also, I would still recommend using Safari Inspector because Ionic is a hybrid app and you can automate it in a Selenium context.

**Comment by KS261187** [comment]
When I try to expand, I see none of the controls getting rendered. It is only rendering unto XCUITElementTypeOther. I am not able to go past after that, since there is nothing after that. I also tried to get the page source and I see the same thing as I see with the Appium inspector. I also tried switching to web view and it errors out saying no web view found. I can still use the latest Appium desktop but the appcenter is still using Appium 1.7.1. Please suggest.

**Comment by dpgraham** [comment]
When you call `getContexts` does it only show one context?

**Comment by KS261187** [comment]
When i tried, i gave me only NATVE_APP. Any idea how it started to work with the latest appium client?

**Comment by dpgraham** [comment]
It uses XCTest under the hood so probably a new version of XCTest made it work. The UI Hierarchy is reported by XCTest and isn't controlled directly by Appium and WebViews typically have unpredictable results as to what is reported.
