### ISSUE TITLE
Make admc/wd client support W3C

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#10682]
## The problem

* Discovered that admc/wd breaks when attempting to attach to a running W3C session
* Need to update `wd` to support W3C since `wd` is the client library that Appium Desktop uses

Acceptance Criteria
* [ ] Can create W3C sessions and call a few basic commands
* [ ] Can attach to an existing session and call a few basic commands successfully
* [ ] Release new version
* [ ] Update `appium/appium-desktop` to use new version

**Comment by mykola-mokhnach** [comment]
Python client should be updated as well. At least its dependencies in PIP (currently these include Selenium APOI v. 2, for example)

**Comment by dpgraham** [comment]
Resolved in a fork `dpgraham-wd`.... will put in a PR to merge fork into `wd.

**Comment by robdaems** [comment]
> Resolved in a fork `dpgraham-wd`.... will put in a PR to merge fork into `wd.

@dpgraham Can you share link to PR, for follow-up (meaning when PR is merged) Thanks.
