### ISSUE TITLE
Appium or WDA server hang when creating new session

### ISSUE THREAD

**Issue by jamesvanhorn** [appium/appium#10687]
## The problem

Appium server/WDA hang when creating a new session. This is happening extremely often now. Used to be rare occurrence. Happens either directly after appInstalled or when posting to /session

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2 (not as much as least)
* Desktop OS/version used to run Appium: Mac OSX High Sierra
* Node.js version (unless using Appium.app|exe): v8.11.1 (tried upgrading/downgrading but didn't seem to matter)
* Mobile platform/version under test: iOS 11.3
* Real device or emulator/simulator: Both
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Hanging when posting to /session
Will stay like this for 10 minutes until reporting NoHttpResponseException at 0.0.0.0:4723
https://gist.github.com/jamesvanhorn/219b5ad49f3c98c366462bff0260163a
On the device/sim we are just looking at the Springboard waiting for the app to launch. I've even tried implementing a block of code before this to launch the same session with the same capabilities, but turning on useNewWDA to force a reinstall. This block does work most of the time, but then this following session gets stuck still. Sometimes the block of code to start/stop a session with useNewWDA does not work either, with the same logs as the above gist, just hanging after the line `20:38:45 [debug] [BaseDriver] Event 'appInstalled' logged at 1526071125194 (16:38:45 GMT-0400 (EDT))` instead of going any further. 

What precautions can we take for a real device or sim? Shutting down the simulator doesnt seem to help. I dont even know how to fix this. It just seems to stop after a little while of restarting the device/sim, manually removing WDA app, etc etc. Ends up breaking again shortly though. This is really hurting our nightly test results where we want to run a larger number of tests. Any tips or workarounds would be awesome.

Thanks.

**Comment by mykola-mokhnach** [comment]
Enable iOS native logging (`showIOSLog`) to see what is happening on the device and attach the updated logs

**Comment by jamesvanhorn** [comment]
massive full output with ios logs on https://gist.github.com/jamesvanhorn/664228a8f3c79c8fc15e90886e8dfc61

I picked through quickly and of note:

Line 2585 we post to /session with all the capabilities...
Line 2734 we get what looks to be the real issue at hand:

`[iOSLog] [IOS_SYSLOG_ROW] 2018-05-11 17:29:13.775 Df WebDriverAgentRunner-Runner[9501:4eecd] (WebDriverAgentLib) Enqueue Failure: Failed to launch <APP_BUNDLE_ID>: Timeout waiting for fulfillment of promise for 'app launch request'. /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1`

No idea what to do with this info though. Let me know if you need any other info. Anything inside <> was something i redacted just so i dont get yelled at.

Thanks for speedy response as always @mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
XCTest just fails to start the app and it is not very clear why. Try to add more logging into your app. You could also implement session init retry in your client code or play with server-specific caps, like the `shouldUseSingletonTestManager` one. There is nothing much that can be done on Appium side.

**Comment by jamesvanhorn** [comment]
@mykola-mokhnach so you think this is definitely a problem with the app? I downgraded a node back to appium 1.7.2 and haven't been able to reproduce the issue yet. Is it possible the bundled WDA with Appium 1.8 is the issue? or Xcode/node/java version issue?

**Comment by mykola-mokhnach** [comment]
There are too many changes between WDA bundled with Appium 1.7.2 and 1.8.0 to figure out which one affects your particular case. Also, it is not possible to downgrade it, since many Appium features depend on the new functionality.
