### ISSUE TITLE
Appium not finding elements on native page until app is sent to tray and brought back

### ISSUE THREAD

**Issue by mmaxin** [appium/appium#10686]
## The problem

Appium not finding any elements on native page unless I send the app to background and immediately  select it again at which point it finds the element. 

Using results in nothing being returned: 
`List elementsList = driver.findElementsByXPath("//*");`

However this works fine on an older phone LG Stylo 2 running Android 6.0.1 (above returns list of all the elements on the page) 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8 
* Last Appium version that did not exhibit the issue (if applicable): not sure, 1.7 also has this issue
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): 8.10.0
* Mobile platform/version under test: Samsung S9 Android Version 8.0.0 and Nexus Android version 8.0.1
* Real device or emulator/simulator: Real Devices
* Appium CLI or Appium.app|exe: CLI

## Details

The app is launched and navigated properly through a few pages until it gets to a select few pages where it fails to find any elements. However when I press the app tray button (one that shows background apps) and immediately select the app again it finds the elements no problem...until it gets stuck on another page a little later. This same code snippet works fine on an older device. 

## Link to Appium logs
There is no error generated but here are the logs

This one is the app constantly waiting trying to find the elements it goes for a long time without a clear timeout (I waited about 5 min): 
https://gist.github.com/mmaxin/e0823a437c9e61671c5c3302db2acd6f

This one is me using the tray method to have it run succesfully: 
https://gist.github.com/mmaxin/0e9e3448d4e7b871a68b7c17b3e87616

## Code To Reproduce Issue
Extra capabilities 
`        capabilities.setCapability("setWebContentsDebuggingEnabled","true");

        capabilities.setCapability("testobject_cache_device","true");

        capabilities.setCapability("noReset","true");
`

and the line of code used to test with is to get all elements on page: 

`List elementsList = driver.findElementsByXPath("//*");`

but it returns nothing on the newer devices and works fine on the older one, I follow this with a click on one of the elements.

**Comment by mykola-mokhnach** [comment]
Switch to UIAutomator2

**Comment by mmaxin** [comment]
That did work to get past the page it was stuck on but now it errors out at a section it was previously working on fine

https://gist.github.com/mmaxin/9f54425289ac3dde1bbdbc4862b8d682

**Comment by mmaxin** [comment]
Huh, so I ran it a few more times and it seems to have made it past this page. It seems to have the issue some times.

**Comment by KazuCocoa** [comment]
https://gist.github.com/mmaxin/9f54425289ac3dde1bbdbc4862b8d682#file-uiautomator2-error-L134 looks raising an error when it called `isDisplayed`, not tried to find elements with XPath.

( https://github.com/appium/java-client/issues/872 or https://github.com/appium/appium/issues/10583 are related one, probably.)

Could you call `driver.findElementsByXPath("//*");` skipping other `isDisplayed` to make sure if `findElementsByXPath` works or not?
https://gist.github.com/mmaxin/e0823a437c9e61671c5c3302db2acd6f#file-endless-run-L603

**Comment by mmaxin** [comment]
I ran the tests a few times again and the error seems to have gone away but when I plugged in another phone to test on it returned but once again after a few runs went away.

**Comment by mykola-mokhnach** [comment]
> https://gist.github.com/mmaxin/9f54425289ac3dde1bbdbc4862b8d682#file-uiautomator2-error-L134 looks raising an error when it called isDisplayed, not tried to find elements with XPath.

I second that. I general UIA1 is not recommended for usage on Android 6+, since it's outdated and is not supported by Google anymore.

**Comment by goelgautam1994** [comment]
Hi, I am trying to test android watch and was able to do most o the things which I need. But in some cases appium keeps searching for the element though it is displayed on the screen. For example i have to press the button and I have mentioned the d of the button which I extracted using UiInspector of appium. The few lines of the logs are:

[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:click","params":{"elementId":"12"}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: click
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [MJSONWP] Responding to client with driver.click() result: true
[HTTP] <-- POST /wd/hub/session/d57dbd11-7f82-40f7-8ce2-dd6820c19e8a/element/12/click 200 3127 ms - 76 
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":true}
[HTTP] --> POST /wd/hub/session/d57dbd11-7f82-40f7-8ce2-dd6820c19e8a/element {"using":"id","value":"com.ofss.digx.mobile.android:id/transfer_button"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["id","com.ofss.digx.mobile.android:id/transfer_button","d57dbd11-7f82-40f7-8ce2-dd6820c19e8a"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"com.ofss.digx.mobile.android:id/transfer_button","context":"","multiple":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"com.ofss.digx.mobile.android:id/transfer_button","context":"","multiple":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'com.ofss.digx.mobile.android:id/transfer_button' using 'ID' with the contextId: '' multiple: false
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=com.ofss.digx.mobile.android:id/transfer_button]
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Failed to locate element. Clearing Accessibility cache and retrying.
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'com.ofss.digx.mobile.android:id/transfer_button' using 'ID' with the contextId: '' multiple: false
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=com.ofss.digx.mobile.android:id/transfer_button]

and it just keeps searching for the emlement. How should I resolve this? 
TIA

**Comment by KazuCocoa** [comment]
What about _page source_ when it happened? @goelgautam1994
