### ISSUE TITLE
Android Python bindings: find_element_by_xpath hangs indefinitely 

### ISSUE THREAD

**Issue by gergm** [appium/appium#10684]
## The problem

About 30% of the time that I run my tests, a call to find_element_by_xpath hangs indefinitely.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 10.13.4
* Node.js version (unless using Appium.app|exe): 8.2.1
* Mobile platform/version under test: Android API 27
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe:

## Link to Appium logs

https://gist.github.com/gergm/898813d78284ffe363b1ad9703104361 this log is of the timeout case. Notice in particular the timing of the last 10 lines of this log.

https://gist.github.com/gergm/3feb6563024a2f76f659943552ce68d4 this log is from the same test case but the find did not hang, the last 10 lines of the hang log correspond to about line 2836 of this log.

## Code To Reproduce Issue [ Good To Have ]

driver.find_element_by_xpath("//android.widget.TextView[@text='Home - Sudo']")

**Comment by mykola-mokhnach** [comment]
Switch to UIAutomator2

**Comment by gergm** [comment]
@mykola-mokhnach  How and why will UiAutomator2 help? 
UiAutomator2 causes failures in other parts of my test suite, ie, tests pass OK with the default driver but fail with UiAutomator2.

Which raises the question: why is UiAutomator2 not the default?

**Comment by mykola-mokhnach** [comment]
There are multiple reasons for this, but one thing I can say for sure - UIA1 is not supported by Google anymore and no bugs there are going to be fixed. Also, the UIA1 server itself can be compiled up to API 21 and nobody is going to dig deep into this outdated source and look for possible issues there.

Good luck with using it.

**Comment by dpgraham** [comment]
@gergm The reason it's not the default is because that would introduce a breaking change.

@mykola-mokhnach Did we ever get around to adding a deprecation notice for UIAutomator1?

**Comment by mykola-mokhnach** [comment]
@dpgraham There is such warning message, but only if you explicitly provide android version in caps, since we don't know the actual device version on the stage where we are selecting the actual driver instance inside the umbrella code.

**Comment by gergm** [comment]
@dpgraham thanks for the info. Are all of the breaking changes documented here https://discuss.appium.io/t/documentation-tips-tricks-for-migrating-from-selendroid-to-uiautomator-or-uiautomator2/18624/2? ie:
Replacement strategies:

    By.linkText(“I’m tired of this track”) --> By.xpath("//android.widget.TextView[@text=‘tired of this track’]")
    By.xpath("//AppCompatTextView[@text=‘foo’]") --> By.xpath("//android.widget.TextView[@text=‘foo’]")
    By.xpath("//AppCompatButton[@text=‘foo’]") --> By.xpath("//android.widget.Button[@text=‘foo’]")
    By.xpath("//AppCompatCheckedTextView[@text=‘foo’]") --> By.xpath("//android.widget.CheckedTextView1[@text=‘foo’]")
    By.xpath("//MiniPlayerHandleView[@id=‘mini_player_handle’]") --> By.xpath("//android.widget.RelativeLayout[@resource-id=‘com.pandora.android:id/mini_player_handle’]")
    @name with @content-desc
    By.xpath("//PandoraImageButton[@name=‘Play’]") --> By.xpath("//android.widget.ImageButton[@content-desc=‘Play’]")

Also, given the current lack of support for the default, maybe it is now time to change the default?
