### ISSUE TITLE
Connect to 127.0.0.1:18421 [/127.0.0.1] failed: Connection refused (Connection refused)

### ISSUE THREAD

**Issue by ManjuAsthuthe** [appium/appium#10680]
I am trying to run appium server through java code. i am using Mac OS. After running the code appium server starts successfully but on capabilities when it tries to connect to localhost IP Address it fails. if i start appium manually through terminal and then run the code it works perfectly. i have looked into many tutorial but coudnt get any success. Tried all the different ports too.

Here is the code:

String Appium_JS_Path = "/usr/local/lib/node_modules/appium/build/lib/main.js";
    	AppiumServiceBuilder builder = new AppiumServiceBuilder().withAppiumJS(new File(Appium_JS_Path))
                        .withIPAddress("127.0.0.1")
                        .usingPort(0);
AppiumDriverLocalService appiumService = builder.build();
 appiumService.start();
service_url = appiumService.getUrl().toString();

For Capabilities:

device_id = "08df4c900c025bb2";
    	platform_version = "6.0.1";
    	device_name  = "Nexus 5";
    	appPath = "/Users/man/sam/app-v1.apk";
    	platform_name = "Android";
    	
    	DesiredCapabilities cap = new DesiredCapabilities();
    	cap.setCapability("udid", device_id);
    	cap.setCapability("deviceName", device_name);
    	cap.setCapability("platformVersion", platform_version);
    	cap.setCapability("platformName", platform_name);
    	cap.setCapability("app", appPath);
    
    	driver =  new AndroidDriver<WebElement>(new URL(service_url), cap);
    	driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);

The error is :
org.openqa.selenium.WebDriverException: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:18421 [/127.0.0.1] failed: Connection refused (Connection refused)
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'RINMAC296', ip: 'fe80:0:0:0:8c3:18c2:228b:6999%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_144'

caused by: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4723 [/127.0.0.1] failed: Connection refused (Connection refused)

Can anyone help me out in this ?

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/appium/java-client

Closed as not an issue
