### ISSUE TITLE
uiautomator2 Returned value cannot be converted to Boolean Error

### ISSUE THREAD

**Issue by mmaxin** [appium/appium#10695]
## The problem

Hi I seem to be getting a very strange error on one specific page ever since I updated to uiautomator2.

The line that gives the error is 

` wait.until(ExpectedConditions.visibilityOfElementLocated
                (By.id("com.fivemobile.myaccount.release:id/button_no_thanks"))).click();`

and the error is 

`org.openqa.selenium.WebDriverException: Returned value cannot be converted to Boolean: {stacktrace=StaleElementReferenceError: android.support.test.uiautomator.StaleObjectException` 

(full log below)

## Environment

*Appium version (or git revision) that exhibits the issue: 1.8
*Last Appium version that did not exhibit the issue (if applicable): not sure, 1.7 also has this issue
*Desktop OS/version used to run Appium: Windows 10
*Node.js version (unless using Appium.app|exe): 8.0.0
*Mobile platform/version under test: Google Pixel 8.0.0, LG Stylo 2 Android 6.0.0
*Real device or emulator/simulator: Real Devices
*Appium CLI or Appium.app|exe: CLI

## Details

I had another issue where certain pages were not returning elements even though they should (https://github.com/appium/appium/issues/10686) and the solution was to update to uiautomator2 but this has brought up this new issue.

## Link to Appium logs

https://gist.github.com/mmaxin/2a3a995f1e7fe3dce733cf5c18913383

## Code To Reproduce Issue [ Good To Have ]

It seems to only be this one page executing the line above on whatever device and android version I try.

**Comment by mmaxin** [comment]
I also tried a different approach using 

`while(driver.findElements(By.className("android.widget.ProgressBar")).size()>0){ }`

to hold the test until a loader disappears and that got me a similar error

https://gist.github.com/mmaxin/509c36e1c31a373b81a54e5854743230

**Comment by mykola-mokhnach** [comment]
This issue is known. It has been addressed in the recent beta: https://github.com/appium/appium-base-driver/pull/211

**Comment by mmaxin** [comment]
Do you have a timeline for when this would be in a full release?

**Comment by mykola-mokhnach** [comment]
It's because of the outdated client

**Comment by mykola-mokhnach** [comment]
The wd client, which is built into Appium desktop does not properly support W3C. Only the recent java client does.

**Comment by mykola-mokhnach** [comment]
Are you sure you are using the recent beta of the server? You can only install it via npm: `npm i -g appium@beta`

**Comment by mmaxin** [comment]
After updating the version of the server I can successfully run the tests on two devices (both Android 6), one is an LG Stylo 2 and the other is a Galaxy S7 but running on two newer devices fails.

On a Pixel running Android 8 and Galaxy Note 8 running Android 7.1.1 the tests fail to start at 
`driver = new AndroidDriver(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);`

and this is the log https://gist.github.com/mmaxin/76676eebcf249d197160d52e98670dde

**Comment by mmaxin** [comment]
@mykola-mokhnach any input on this one? is it worth creating into its own issue?

**Comment by mykola-mokhnach** [comment]
no idea. 

Yes, it would be better to create a separate report
