### ISSUE TITLE
[Android] Too long response from server when using Camera

### ISSUE THREAD

**Issue by isnifer** [appium/appium#10691]
## The problem
I do my tests via appium on Android and via Detox on iOS.
A test suite with a camera on Android takes **10:21** minutes, on iOS — **1:31** minutes.
I thought there was a problem with my emulator (I need to switch to software rendering for testing), but I found that appium takes too much time to find elements on the screen after camera appears on the screen.

## Environment
* Appium version (or git revision) that exhibits the issue: **1.8.0**
* Last Appium version that did not exhibit the issue (if applicable): **1.6.4, may be lower**
* Desktop OS/version used to run Appium: **macOS 10.13.4 (17E202)**
* Node.js version (unless using Appium.app|exe): **9.4.0**
* Mobile platform/version under test: **Android**
* Real device or emulator/simulator: **Emulator**
* Appium CLI or Appium.app|exe: **CLI**

## Details
[I wrote a gif with this process](https://i.imgur.com/HR3wmKm.gifv)

## Link to Appium logs
[Appium Log](https://gist.github.com/isnifer/293fc6fcefc7e501a3e153ce88bb4395)

**Comment by mykola-mokhnach** [comment]
Try to use UIAutomator2

**Comment by isnifer** [comment]
@mykola-mokhnach looks like it already used by default. Isn't it? Anyway, I tried to pass this capability explicitly — the same result.

**Comment by mykola-mokhnach** [comment]
Closed as inactive
