### ISSUE TITLE
Long press touch action is no longer working for iOS in 1.8.0

### ISSUE THREAD

**Issue by JoelWhitney** [appium/appium#10698]
## The problem

Long press TouchAction method is not recognized as long press in iOS when moving up to Appium 1.8.0. If I use Appium 1.7.2, the long press method works as expected.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0 (Appium Desktop 1.6.1)
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2 (Appium Desktop 1.5.0)
* Desktop OS/version used to run Appium: Mac (10.13.3), Ruby 2.5.1 (Ruby Gems: appium_console (2.8.1), appium_lib (9.12.0), appium_lib_core (1.5.0)
* Mobile platform/version under test: Xcode 9.2 (11.2)
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium.app

## Details

It seems like something has changed with the long press method, which has caused it to not be recognized as a long press in iOS. Executing the following commands in Appium Ruby Console, I got unexpected results when calling `long_press()` in Appium 1.8.0.

| Command | 1.7.2 gesture recognized | 1.8.0 gesture recognized | result |
| - | - | - | - |
| `Appium::TouchAction.new.press(x:200,y:100).release.perform`   |  tap  | tap  | pass |
| `Appium::TouchAction.new.long_press(x:200,y:100).release.perform` | **long press** | **tap** | **fail** |
| `Appium::TouchAction.new.press(x:200,y:100).wait(500).release.perform` | tap | tap | pass |
| `Appium::TouchAction.new.press(x:200,y:100).wait(501).release.perform` | long press |  long press  | pass |

## Link to Appium logs

_Will add if needed_

## Code To Reproduce Issue

https://github.com/JoelWhitney/sample-appium-test/tree/touch-action-bug

## Steps To Reproduce Issue
1. Clone `sample-appium-test`
2. In Appium Desktop 1.6.1, start Server 1.8.0
3. Open Terminal at `sample-appium-test` directory
4. Start Appium Ruby Console, via `arc` command
5. Execute `Appium::TouchAction.new.long_press(x:200,y:100).release.perform` command
6. Notice UILabel says `Tap occurred` instead of `Long press occurred`
7. Execute `Appium::TouchAction.new.press(x:200,y:100).wait(500).release.perform` command
8. Notice UILabel says `Long press occurred` as expected
3. In Appium Desktop 1.5.0, start server 1.7.2
4. Repeat steps 5-8 and notice long press behaves as expected

**Comment by SohilKumar** [comment]
Hi @JoelWhitney ,

I'm also facing the same problem Touch actions or long press are not working in 1.8.0 version in IOS
But if you down grade to 1.7.2 my code works as expected

Environment : JAVA

The following are the different ways i tried to make it work but was not successful, but when you go back to 1.7.2 all of them work as expected

TouchAction a = new TouchAction((MobileDriver) driver);
a.press(61,221).moveTo(300, 315).release().perform();
					
a.longPress(61, 221, 5000).moveTo(300, 315).release().perform();
					
((AppiumDriver) driver).swipe(61, 221, 300, 315, 3000); 
					
JavascriptExecutor js = (JavascriptExecutor) driver;
HashMap<String, Double> swipeObject = new HashMap<String, Double>();
swipeObject.put("startX", 61.0);
swipeObject.put("startY", 221.0);
swipeObject.put("endX", 300.0);
swipeObject.put("endY", 315.0);
swipeObject.put("duration", 3.0);
js.executeScript("mobile: swipe", swipeObject);
					 
WebElement icon = driver.findElement(By.name("New call"));
a.longPress(icon, 61, 221).waitAction(5000).moveTo(300, 315).release().perform();

**Comment by mykola-mokhnach** [comment]
Thanks, I'll increase the default duration to 501 ms ;)

**Comment by JoelWhitney** [comment]
@mykola-mokhnach thank you! 

fyi I'm about to add another issue when I get freed up. Seems the `move_to` or chaining of actions has regressed as well. I can no longer press and "slide" finger across screen on iOS using: 
`Appium::TouchAction.new.press(x:0,y:300).move_to(x:300,y:300).release.perform`

**Comment by mykola-mokhnach** [comment]
This is expected. You must add wait after press

**Comment by mykola-mokhnach** [comment]
since 1.8.0 touch action handler has been completely rewritten, so it is now using the "fair" XCTest implementation under the hood. Previously we were trying to match a limited set of action chains that were similar to the available XCUIElement method calls.

**Comment by erik1510** [comment]
I noticed the fix is merged in the master branch, is there any way for me to use it? If so, what do I need to do to use it? I am using appium 1.8.1-beta1 right now. Thank you.

**Comment by mykola-mokhnach** [comment]
simply install the beta version of appium (or reinstall it if it is already installed)

**Comment by oscheller1** [comment]
Not sure if this is connected, but i'm facing problems with long press on a 11.4 iPad real device. The long press is working only in roughly 50% of the cases. 

I'm always getting the same log message with status code `200`. Sometimes to long press is not executed at all. 

```
[HTTP] --> POST /wd/hub/session/8564da40-24dd-41d7-9cfe-41083fd6ac47/touch/perform
[HTTP] {"sessionId":"8564da40-24dd-41d7-9cfe-41083fd6ac47","actions":[{"action":"longPress","options":{"element":"5E000000-0000-0000-5501-000000000000","duration":1500}},{"action":"release","options":{}}]}
[debug] [W3C] Calling AppiumDriver.performTouch() with args: [[{"action":"longPress","options":{"element":"5E000000-0000-0000-5501-000000000000","duration":1500}},{"action":"release","options":{}}],"8564da40-24dd-41d7-9cfe-41083fd6ac47"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: longPress(options={"element":"5E000000-0000-0000-5501-000000000000","duration":1500})-release(options={})
[debug] [JSONWP Proxy] Proxying [POST /wda/touch/perform] to [POST http://localhost:8100/session/2454F0F5-D1E9-407C-AE3D-D0F2D35221F7/wda/touch/perform] with body: {"actions":[{"action":"longPress","options":{"element":"5E000000-0000-0000-5501-000000000000","duration":1500}},{"action":"release","options":{}}]}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"2454F0F5-D1E9-407C-AE3D-D0F2D35221F7","status":0}
[debug] [W3C] Responding to client with driver.performTouch() result: {}
[HTTP] <-- POST /wd/hub/session/8564da40-24dd-41d7-9cfe-41083fd6ac47/touch/perform 200 1889 ms - 12
[HTTP] 
```
I tried modifying the duration to anything from 500 to 3000, it doesn't change the inconsistency.
