### ISSUE TITLE
setting negative longitude for real devices

### ISSUE THREAD

**Issue by sowri** [appium/appium#10699]
## The problem

setting the location for a real Device with negative Longitude fails with appium-xcuitest-driver

## Environment
* Appium java client 5.0.4
* macOS High Sierra(10.13.4)
* iOS11.0.2:
* Real device

## Details
When we try to use driver.setLocation(location), it works fine the longitude is positive. Below are the logs showing that 
https://gist.github.com/sowri/d0b4a73dd1f10c6aec818afef6b9d296

But when I change the longitude to a negative number the location updates seem to be failing. below are the logs showing that 
https://gist.github.com/sowri/ea4cd4665783928b99c68128859afa57

## My Guess
i think the command passed to idevicelocation needs to include '--' before the negative longitude. i could verify that by using the idevicelocation app from https://github.com/JonGabilondoAngulo/idevicelocation

**Comment by mykola-mokhnach** [comment]
Thanks for the report

**Comment by sowri** [comment]
Vow that was impressively quick. Thanks ...Now a dumb question how do I use it in my appium java client ? Should I wait for a new version of it and when Can We expect that ?

**Comment by mykola-mokhnach** [comment]
The fix is available in appium@beta

**Comment by sowri** [comment]
@mykola-mokhnach  sorry appium@beta ? not appium java client ? can you please clarify it a little bit

**Comment by mykola-mokhnach** [comment]
the error happens on the server side. The client has nothing to do with it
