### ISSUE TITLE
error while getting field mOnAccessibilityEventListener from object android.app.UiAutomation

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#10707]
## The problem

Can't start sessions due to UiAutomator2 java server error.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8 branch
* Last Appium version that did not exhibit the issue (if applicable): 1.8.0
* Desktop OS/version used to run Appium: MacOS
* Node.js version (unless using Appium.app|exe): 9 and 10
* Mobile platform/version under test: Android UiAutomator2
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

* Logcat
https://gist.github.com/dpgraham/f39d5bab0ef65555415635fa0b71754f

* Appium
https://gist.github.com/dpgraham/97eda5fff67673814b9abd5c6b8e908e

**Comment by mykola-mokhnach** [comment]
@vmaxim Can you please take a look?
