### ISSUE TITLE
Swipe Method Issue In Appium With Selenium

### ISSUE THREAD

**Issue by sagarsheth27** [appium/appium#10700]
Swipe method is enabled when I used my project with jar files. But when I want to call it through maven dependencies, then it's shown as deprecated. What is the exact problem. That I do not understand.

**Comment by dmlemeshko** [comment]
@sagarsheth27 Swipe method is deprecated and you should not use it.
Same functionality is available via `TouchAction` class: https://github.com/appium/java-client/blob/master/src/test/java/io/appium/java_client/android/AndroidTouchTest.java#L172
