### ISSUE TITLE
Failing on setLocation For Real Devices

### ISSUE THREAD

**Issue by sowri** [appium/appium#10706]
## The problem

having Problems with setting the Location On Real IOS Device

## Environment

* Appium version v1.8.1-beta1
* Appium version 1.7.2 was working fine
* Node.js version (v6.11.4):
* iOS
* Real device 
* Appium CLI or Appium.app|exe:

## Details

The test fails when we try to set the Location using setLocation

## Link to Appium logs

Below is the log which shows the crash.
https://gist.github.com/sowri/5060fe3798743ceda3b32aee76297317

**Comment by mykola-mokhnach** [comment]
I see what the problem might be

**Comment by mykola-mokhnach** [comment]
The fix is published
