### ISSUE TITLE
Appium stock and didn't, Android

### ISSUE THREAD

**Issue by AvrahamAtia** [appium/appium#10701]
## The problem

I am executing the test but there is one page in the app that Appium stock when he try to find element, and I try manually to connect  to this session but didn't get any response. 

## Environment

* Appium server version: 1.8
* Appium desktop Version: 1.6.1
* Desktop OS/version used to run Appium: Mac version 10.13.4
* Node.js version (unless using Appium.app|exe): v8.6.0
* Mobile platform/version under test: Android Galaxy S8 OS:8.0.0
* Real device or emulator/simulator: Real device

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Appium stock in this point:

[MJSONWP] Calling AppiumDriver.getPageSource() with args: ["94806460-2c7e-4ae2-a3d5-9e99e859dada"]
[HTTP] --> POST /wd/hub/session/94806460-2c7e-4ae2-a3d5-9e99e859dada/element
[HTTP] {"using":"xpath","value":"//android.widget.TextView[@text='Photos']"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath","//android.widget.TextView[@text='Photos']","94806460-2c7e-4ae2-a3d5-9e99e859dada"]

**Comment by mykola-mokhnach** [comment]
Can you also attach the logcat output?

**Comment by AvrahamAtia** [comment]
05-17 17:01:23.012  7984  8009 E QueryController: Cannot proceed when root node is null. Aborted search
05-17 17:01:23.014  7984  8009 E QueryController: Got null root node from accessibility - Retrying...
05-17 17:01:23.139  1517  1617 I QCNEJ/CndHalConnector: -> SND notifyWifiStatusChanged(RatInfo{type=1, subType=101, state=CONNECTED, v4=IfaceAddrPair{iface=wlan0, addr=172.22.222.106}, v6=IfaceAddrPair{iface=, addr=}, timestamp=2018-05-17 17:01:23.138, isAndroidValidated=true, netHandle=433808132830, slotIdx=0} WifiInfo{freq=FIVE_GHz, state=3, ssid=SFLY_GUEST, bssid=00:a7:42:fb:8d:4d, dns=[194.90.0.1, 212.143.0.1, 0.0.0.0, 0.0.0.0, ]})
05-17 17:01:23.266  7984  8009 E QueryController: Got null root node from accessibility - Retrying...
05-17 17:01:23.518  7984  8009 E QueryController: Got null root node from accessibility - Retrying...
05-17 17:01:23.773  7984  8009 E QueryController: Cannot proceed when root node is null. Aborted search
05-17 17:01:23.774  7984  8009 E QueryController: Got null root node from accessibility - Retrying...
05-17 17:01:24.026  7984  8009 I chatty  : uid=2000(shell) WatchTimer identical 1 line
05-17 17:01:24.278  7984  8009 E QueryController: Got null root node from accessibility - Retrying...
05-17 17:01:24.530  7984  8009 E QueryController: Cannot proceed when root node is null. Aborted search
05-17 17:01:24.531  7984  8009 E QueryController: Got null root node from accessibility - Retrying...

**Comment by mykola-mokhnach** [comment]
This error happens inside the UIAutomator2 framework. There is nothing we can do about it on Appium side.
