### ISSUE TITLE
appium 1.8.0  server takes 40 seconds to start after typing appium to console

### ISSUE THREAD

**Issue by alicenahkarakol** [appium/appium#10718]
## The problem
Hi I just installed appium 1.8.0 to my windows 10 machine.
appium 1.8.0  server takes 40 seconds to start after typing appium to console

## Environment

appium 1.8.0
windows 10 
java version 1.9.4
node  8.11.2

C:\Users\ali>appium // after 40-45 seconds,
[Appium] Welcome to Appium v1.8.0
[Appium] Appium REST http interface listener started on 0.0.0.0:4723

normally it was taking 2-5 secs when I was using 1.6.5. 
Is is a known problem or are there any solution or workaroud for this?
Why it takes too long?

**Comment by aryeko** [comment]
I have the same issue on mac os high sierra 10.13.2 and node 8.9.3

**Comment by aryeko** [comment]
@pavanbachu0604 Tried with both, xcode 9.3 and 9.3.1

**Comment by pavanbachu0604** [comment]
@aryeko I am using Xcode 9.3.2 and I dint see this issue ..So I was curious if you can share the Appium logs when you are using xcode 9.3 OR 9.3.1?

**Comment by mykola-mokhnach** [comment]
Closed as inactive
