### ISSUE TITLE
Port still Open after termination of Application

### ISSUE THREAD

**Issue by VinnieM** [appium/appium#10717]
## The problem
After the appium process has finished with the test case the port is still being used. I am running a test case on a real device (iPhone 7sPlus).

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Desktop OS/version used to run Appium: High Sierra 10.13.4
* Node.js version (unless using Appium.app|exe): 8.11.1
* Mobile platform/version under test: iOS 11.3.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Details
I might be completely wrong. But these are my observations. While running the test case I was just doing a netstat on appium port.
```
Reventon:xtune-bdd reventon$ ps -ef | grep appium
  501  4362  4361   0  3:45AM ttys000    0:02.49 /usr/local/bin/node /usr/local/bin/appium --port 48907 --address 0.0.0.0 --log-level info:info --bootstrap-port 50473
  501  4551  1737   0  3:45AM ttys001    0:00.00 grep appium

Reventon:xtune-bdd reventon$ netstat -a -b | grep 48907
tcp4       0      0  192.168.1.4.48907      192.168.1.4.50489      ESTABLISHED       1918          0
tcp4       0      0  192.168.1.4.50489      192.168.1.4.48907      ESTABLISHED          0          0
tcp4       0      0  *.48907                *.*                    LISTEN               0          0
tcp4       0      0  192.168.1.4.50485      192.168.1.4.48907      TIME_WAIT          539          0
tcp4       0      0  192.168.1.4.50488      192.168.1.4.48907      TIME_WAIT          539          0
```
But even after the test case has finished it's execution and if I do a netstat again I do see a TIME_WAIT
```
Reventon:xtune-bdd reventon$ netstat -a -b | grep 48907
tcp4       0      0  192.168.1.4.50515      192.168.1.4.48907      TIME_WAIT        46384          0
```
Code wise, I'm doing a driver.quit and appiumLocalService.stop(). Just wanted to know if it's the expected behavior.

**Comment by mykola-mokhnach** [comment]
Yes, the behaviour is expected. Usually, after WDA binary is restarted 20-30 times on the device (depends on the amount of available resources) then the phone operating system just blocks it from running and only device reboot helps to solve WDA startup. That is why one must keep the agent running for as long as possible.
