### ISSUE TITLE
Appium fails to connect to a port. It retries and eventually gets connected to some port. But the execution test run is delayed upto 10 minutes (To begin the tests)

### ISSUE THREAD

**Issue by gkvappium** [appium/appium#10712]
## The problem

Appium fails to connect to a port. It retries and eventually gets connected to some port. But the execution test run is delayed upto 10 minutes (To begin the tests)

## Environment

* Appium version (or git revision) that exhibits the issue:1.8.0 release
* Last Appium version that did not exhibit the issue (if applicable):1.7.2
* Desktop OS/version used to run Appium:Mac and Windows
* Node.js version (unless using Appium.app|exe):9
* Mobile platform/version under test:Android 6,7,8 and IOS 11
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Starting server...
[Appium] Welcome to Appium v1.8.0

[Appium] Non-default server args:

[Appium]   port: 8300

[Appium] Appium REST http interface listener started on 0.0.0.0:8300

Starting server...
[Appium] Welcome to Appium v1.8.0

[Appium] Non-default server args:

[Appium]   port: 8300

Timeout expired, output not detected for: /listener started/
[Appium] Welcome to Appium v1.8.0

[Appium] Non-default server args:
[Appium]   port: 8310

[Appium] Appium REST http interface listener started on 0.0.0.0:8310

This is just one failed attempt. But I have seen instances wherein it fails for nearly 10 attempts. The above example is after running killall node (task kill /im node.exe /F on windows). 

@mykola-mokhnach any input ?

**Comment by mykola-mokhnach** [comment]
Are you sure the port is not used by some other service?

**Comment by gkvappium** [comment]
@mykola-mokhnach,

Yes, I am sure that no other service is using that port. I restarted the machine and also did a killall node before triggering the tests. In fact I saw this issue on 2 Macs and 1 windows box

**Comment by mykola-mokhnach** [comment]
how do you start the server? from the command line?

**Comment by gkvappium** [comment]
Yes from the command line. I use a plug-in called nativescript-dev-appium (wrapper for wd which is typescript  based)which takes care of start server and stop server . I have not updated the plug-in recently. I am seeing this issue only after upgrading to appium 1.8.0

**Comment by mykola-mokhnach** [comment]
It might be a problem with this wrapper, since there were no changes in appium, which are related to server startup.

**Comment by gkvappium** [comment]
I'll do some more testing on this and try to zero in on the issue. I've been using this plug-in from 4-5 months and have never encountered the issue. I'll try to figure out as to what's going wrong. Thanks

**Comment by lohiarahul** [comment]
> I'll do some more testing on this and try to zero in on the issue. I've been using this plug-in from 4-5 months and have never encountered the issue. I'll try to figure out as to what's going wrong. Thanks

Facing the same issue with NativeScript. Did you find a solution to this?

**Comment by swathiRajaPrasanth** [comment]
Facing the same issue in NativeScript-dev-appium...Is there a solution?

**Comment by dkoudrinhc** [comment]
Same issue in 2021.
