### ISSUE TITLE
Weird swiping behaviour in iOS

### ISSUE THREAD

**Issue by carolhmj** [appium/appium#10713]
## The problem
I need to run a test in a real iOS device where the wi-fi is turned off, then turned on. The most common solution to this problem I've encountered is swiping from bottom to top of the screen to reveal the control center, then turning off the wi-fi from there. I've been trying to use TouchActions to do this, but when I do the swipe from bottom to top, the control center doesn't appear, and an element on the top part of the screen (which shouldn't be affected by the swiping) is selected.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Desktop OS/version used to run Appium: macOS 10.13.4
* Node.js version (unless using Appium.app|exe): 8.11.1 
* Mobile platform/version under test: iOS 11.3.1
* Real device or emulator/simulator: Real iPhone 7+ 
* Appium CLI or Appium.app|exe: CLI

## Details

I've tried with Java client versions 5-BETA9, 5.0.3 and 5.0.4. My stack uses Selenium Grid 3.6, and the app in question is a hybrid app. 
The layout of the app in question is similar to this one. The element incorrectly selected is this text area on the top area.  https://www.fluidui.com/editor/live/preview/cF9wcXFRZnhLODlKQkJDWlU2MzU0V1FDOHNQdGlteXl1Rg==
I've tried to run this swiping code in the WebView sample app, and the control center doesn't get shown too.
 
## Link to Appium logs

Logs from the sample app test. The logs from the real app test are very similar.
https://gist.github.com/carolhmj/9ff62b0dcde9d7f0147982a99d208c3f

## Code To Reproduce Issue [ Good To Have ]

```java
setContextNative();
int height = driver.findElementByClassName("UIAWindow").getSize().getHeight();
int width = driver.findElementByClassName("UIAWindow").getSize().getWidth();
System.out.println("Scrolling from point (" + width/2 + ", " + height + ") to point (" + width/2 + ", " + (height-height/6) + ")");
TouchAction touchAction = new TouchAction(driver);
touchAction.press(width/2, height).waitAction(Duration.ofMillis(90)).moveTo(0, -height/6).release().perform();
driver.findElementByAccessibilityId("Wi-Fi").click();
setContextWeb();
```

**Comment by mykola-mokhnach** [comment]
- moveTo coordinates are absolute since Appium 1.8.0
- long tap delay should be greater than 500 ms

**Comment by mykola-mokhnach** [comment]
Check https://appiumpro.com/editions/15 for example

**Comment by carolhmj** [comment]
I'm using appium 1.7.2, as informed, so I used relative coordinates.
I've tried swiping up with JavascriptExecutor and the same behaviour happens.
```
Map<String, Object> params = new HashMap<>();
params.put("direction", "up");
JavascriptExecutor js = driver;
js.executeScript("mobile: swipe", params);
```

**Comment by mykola-mokhnach** [comment]
Then try to upgrade. We don't patch older versions

**Comment by carolhmj** [comment]
Upgrading corrected the behaviour.
