### ISSUE TITLE
appium-uiautomator2-server-v1.10.0.apk missing

### ISSUE THREAD

**Issue by GiridharKarnik** [appium/appium#10719]
## The problem

I was tryin out appium with node.js for the first time and ran into this error stating that `Encountered internal error running command: Error: /Applications/Appium.app/Contents/Resources/app/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v1.10.0.apk file doesn't exist.`

## Environment

* Appium version: 1.8.0
* Desktop OS/version used to run Appium: 1.8.0
* Node.js version: 8.11.1
* Mobile platform/version under test: Android Oreo 8.0.0
* Real device or emulator/simulator: Read device
* Appium CLI or Appium.app|exe: Appium.app

## Link to Appium logs

Logs can be found in a gist [here](https://gist.github.com/GiridharKarnik/78db2fc73632e683d3db3a3e370d5fcf)

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/appium/appium-desktop

**Comment by sevetseh28** [comment]
@mykola-mokhnach this is happening to me on Linux Mint 19 with NPM appium.
