### ISSUE TITLE
Driver fails to start on some versions. 

### ISSUE THREAD

**Issue by mmaxin** [appium/appium#10714]
## The problem

Updated to server version `appium@beta` to solve problem seen here https://github.com/appium/appium/issues/10695 but it brought upon a new issue where:

I can successfully run the tests on three devices (two Android 6), one is an LG Stylo 2, the other is a Galaxy S7, and an Android 8.1.1 Nexus.

But on a Pixel running Android 8.0.0 and Galaxy Note 8 running Android 7.1.1 the tests fail to start at
driver = new AndroidDriver(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1 (beta)
* Last Appium version that did not exhibit the issue (if applicable): 1.8
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): 8.10.0
* Mobile platform/version under test: 
Works fine on: Android 6:  LG Stylo 2 and Galaxy S7, Android 8.1.1 Nexus
Does not work on:  Android 8.0.0: Pixel, Android 7.1.1: Galaxy Note 8

* Real device or emulator/simulator: Real devices
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs
https://gist.github.com/mmaxin/902b5e1ed2eb594a7cc187307f5c2a6f

## Code To Reproduce Issue

Capabilities list:
        `capabilities.setCapability("appium-version", "1.8.0");`
        `capabilities.setCapability("platformName", "Android");`
        `capabilities.setCapability("deviceName", Device_Name);`
        `capabilities.setCapability("appPackage", "de.codenauts.hockeyapp");`
        `capabilities.setCapability("appActivity","net.hockeyapp.client.HomeActivity");`
        `capabilities.setCapability("automationName","uiautomator2");`
        `capabilities.setCapability("noReset",true);`

**Comment by mykola-mokhnach** [comment]
It looks like the app is not signed properly.

What if you try to sign it manually from terminal?

Just find the apksigner.bat script inside Android SDK and execute it with the following arguments

```
sign --key C:\Users\Michael.Maxin\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\keys\testkey.pk8 --cert C:\Users\Michael.Maxin\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\keys\testkey.x509.pem C:\Users\Michael.Maxin\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk'
```

**Comment by mykola-mokhnach** [comment]
Yep, this looks more like an issue with Android's apksigner. there is nothing much we can do here. You can play with different versions of Android SDK or switch to another OS.
