### ISSUE TITLE
## I am getting below error while launching app through appium: ountered internal error running command: Error: Command 'java -version' exited with code 2

### ISSUE THREAD

**Issue by Saurabh0311** [appium/appium#10710]
Appium Version latest

## Link to Appium logs
Start New SessionStop Server
[Appium] Welcome to Appium v1.6.5
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/sessions {}
[MJSONWP] Calling AppiumDriver.getSessions() with args: []
[MJSONWP] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 8 ms - 40 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"D:\\EcoNetQA.apk","automationName":"uiautomator2","deviceName":"08c0aa460004","platformName":"Android","platformVersion":"7.0","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"D:\\EcoNetQA.apk","automationName":"uiautomator2","deviceName":"08c0aa460004","platformName":"Android","platformVersion":"7.0","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1526627346697 (12:39:06 GMT+0530 (India Standard Time))
[Appium] Creating new AndroidUiautomator2Driver (v0.3.3) session
[Appium] Capabilities:
[Appium]   app: 'D:\\EcoNetQA.apk'
[Appium]   automationName: 'uiautomator2'
[Appium]   deviceName: '08c0aa460004'
[Appium]   platformName: 'Android'
[Appium]   platformVersion: '7.0'
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[BaseDriver] The following capabilities were provided, but are not recognized by appium: connectHardwareKeyboard.
[BaseDriver] Session created with session id: 1f71f504-a8a4-4de1-9097-21dd10ff77e9
[BaseDriver] Using local app 'D:\EcoNetQA.apk'
[UiAutomator2] Checking whether app is actually present
[UiAutomator2] UIAutomator2 Driver version:0.3.3
[AndroidDriver] Getting Java version
[UiAutomator2] Deleting UiAutomator2 session
[UiAutomator2] Unable to remove port forward 'Cannot read property 'removePortForward' of undefined'
[MJSONWP] Encountered internal error running command: Error: Command 'java -version' exited with code 2
    at ChildProcess. (C:\Users\rishabhs\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\teen_process\lib\teen_process.js:70:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
[HTTP] <-- POST /wd/hub/session 500 519 ms - 179 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"D:\\EcoNetQA.apk","automationName":"uiautomator2","deviceName":"08c0aa460004","platformName":"Android","platformVersion":"7.0","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"D:\\EcoNetQA.apk","automationName":"uiautomator2","deviceName":"08c0aa460004","platformName":"Android","platformVersion":"7.0","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1526627359980 (12:39:19 GMT+0530 (India Standard Time))
[Appium] Creating new AndroidUiautomator2Driver (v0.3.3) session
[Appium] Capabilities:
[Appium]   app: 'D:\\EcoNetQA.apk'
[Appium]   automationName: 'uiautomator2'
[Appium]   deviceName: '08c0aa460004'
[Appium]   platformName: 'Android'
[Appium]   platformVersion: '7.0'
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[BaseDriver] The following capabilities were provided, but are not recognized by appium: connectHardwareKeyboard.
[BaseDriver] Session created with session id: 827508b9-b2b7-4f52-806e-1ed79fbfc18d
[BaseDriver] Using local app 'D:\EcoNetQA.apk'
[UiAutomator2] Checking whether app is actually present
[UiAutomator2] UIAutomator2 Driver version:0.3.3
[AndroidDriver] Getting Java version
[UiAutomator2] Deleting UiAutomator2 session
[UiAutomator2] Unable to remove port forward 'Cannot read property 'removePortForward' of undefined'
[MJSONWP] Encountered internal error running command: Error: Command 'java -version' exited with code 2
    at ChildProcess. (C:\Users\rishabhs\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\teen_process\lib\teen_process.js:70:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/search?utf8=✓&q=%22java+-version%22+exited+with+code+2&type=Issues

closed as duplicate
