### ISSUE TITLE
can not switch to web context when using java8 stream filter.

### ISSUE THREAD

**Issue by WenRui13** [appium/appium#10729]
using  java8 stream filter to switch context to webview when testing hybrid app can not work,  what's the difference beteween the follow way:

Set<String> contextHandles = driver.getContextHandles();
//      switch context ,this way can work
//        for (String context : contextHandles) {
//            if (context.contains("WEBVIEW")) {
//                driver.context(context);
//                break;
//            }
//        }
        
//        can not work, and throw java.util.NoSuchElementException: No value present
//        at java.util.Optional.get(Optional.java:135)
        String webview = contextHandles.stream().filter(context -> context.contains("WEBVIEW")).findFirst().get();
        driver.context(webview);

**Comment by mykola-mokhnach** [comment]
It looks like `contextHandles` simply does not contain any web view and thus the `.get` call on empty optional fails. Anyway it's hard to say anything without server logs.

**Comment by WenRui13** [comment]
yes.this is appium log:
[debug] [W3C] Calling AppiumDriver.getContexts() with args: ["08ff33db-dab6-41d6-9f79-fc2f89a993e7"]
[debug] [AndroidDriver] Getting a list of available webviews
[debug] [ADB] Getting connected devices...
[debug] [ADB] 15 device(s) connected
[debug] [ADB] Running '/opt/android-sdk-linux/platform-tools/adb -H 10.1.64.43 -P 5037 -s a6e7b40d shell cat /proc/net/unix'
[debug] [AndroidDriver] Found webviews: []
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP"]
[debug] [W3C] Responding to client with driver.getContexts() result: ["NATIVE_APP"]
[HTTP] <-- GET /wd/hub/session/08ff33db-dab6-41d6-9f79-fc2f89a993e7/contexts 200 531 ms - 24


Why can't I use java8 to get the webview context?
