### ISSUE TITLE
Cannot find pushed files in the app's container

### ISSUE THREAD

**Issue by x-yang11** [appium/appium#10728]
## The problem

When I was using ```driver.push_file('Documents/xxx/image.txt', 'test data')``` to push file to my real device(iPhone 6), I cannot find the file through Xcode or ifuse commandline, while appium log showed that everything works well.
 
## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:Mac OS 10.13.4
* Node.js version (unless using Appium.app|exe):10.1.0
* Mobile platform/version under test: iPhone6 iOS 10.3.3
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: python

## Details
part of my code:
```Python
def main():
	desired_caps = {}
	desired_caps['platformName'] = 'iOS'
	desired_caps['platformVersion'] = '10.3.3'
	desired_caps['deviceName'] = u'name'
	desired_caps['udid'] = 'f3e8***'
	desired_caps['app'] = '/path/to/Demo.app'
	desired_caps['bundleId'] = 'com.xxx.xxx.xxx'
	driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
	driver.execute_script('mobile: alert', {'action': 'accept'})
	for imageid in range(35):
		content = open('/path/to/testData/image_%d.txt' % imageid, 'rb').read()
		encoded_file = base64.b64encode(content)
		driver.push_file('Documents/xxx/testData/image_%d.txt'%imageid, encoded_file.decode())

	mm = driver.pull_file('Documents/arlog/testData/image_0.txt')
	print (len(mm))
```
No errors is found in appium log, and the content of mm is right. However, When I use Xcode-windows-Device and Simulators to download the container of my app, there is no folder named 'Documents/xxx/testData' . What's more, I used 'ifuse -u f3e8*** ~/Media --container com.xxx.xxx.xxx', and cannot find a folder named 'Documents/xxx/testData', either.

I want to known where is the pushed file, and how can I push file into the container of my app. Thanks!

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

**Comment by mykola-mokhnach** [comment]
By default the file is copied into the global media folder. If you want to put the file into the particular application container then the following target format should be used: `@bundleId/<path_inside_container>`. Read https://github.com/appium/appium-xcuitest-driver/blob/ed9740894ebf634789feb95e70c90f5b73f144e8/lib/commands/file-movement.js#L97 for more details.

**Comment by x-yang11** [comment]
Thanks very much! It works well. 

By the way, since pull_folder seems isn't implemented for iOS Device, how can I pull files with unknown name from device, such as named by timestamp?

**Comment by mykola-mokhnach** [comment]
Create a separate feature request and we'll implement it when we have time. Or you could create a PR yourself.
