### ISSUE TITLE
How to scroll to the bottom

### ISSUE THREAD

**Issue by Humberd** [appium/appium#10720]
I have a root ScrollView element and I would like to scroll it all the way to the bottom.

 I use **wd**  and currenty I have this piece of code, but it doesn't work. What do those parameters mean on `flick` function? Or is there an easier way to do it?
```javascript
driver.elementByAccessibilityId("scroll-view").flick(1, 10 ,10);
```

**Comment by mykola-mokhnach** [comment]
There is no built-in function, which scrolls to the bottom. You can also use multiple swipes (press-wait-release), but all the necessary on-screen element verifications are anyway up to your client code
