### ISSUE TITLE
Unable to select the value from the dropdown using Appium IOS

### ISSUE THREAD

**Issue by KS261187** [appium/appium#10727]
I am trying to select a value from the dropdown but when I tried to inspect the element, all the values from the dropdown are concatenated together and hence I am not able to select a single value from the dropdown. 

Please find the attached screenshot.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: 11.3.1
<img width="1414" alt="screen shot 2018-05-21 at 5 18 55 pm" src="https://user-images.githubusercontent.com/26659582/40332918-8d536868-5d1b-11e8-9274-a407f2307bb2.png">

* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
You must switch to webview in order to properly interact with elements there. Closed as not an issue.

https://appium.io/docs/en/writing-running-appium/web/hybrid/

**Comment by mykola-mokhnach** [comment]
<img width="1414" alt="webview" src="https://user-images.githubusercontent.com/7767781/40368092-42d90c32-5ddb-11e8-87c8-2fbc3e09b0e1.png">

There IS a webview

**Comment by KS261187** [comment]
Yes but when i get the context, i get only the native and it does not
return me any webview.

Thanks

**Comment by mykola-mokhnach** [comment]
you can still use appium forum to ask questions
