### ISSUE TITLE
Port still Open after termination of Application

### ISSUE THREAD

**Issue by VinnieM** [appium/appium#10721]
## The problem

This is a related to Issue #10717 The issue I have is that test case the port is still being used. As per the reply I got, it is possible if WDA binary is restarted 20-30 times on the device. But I have not restarted 20 -30 times...well as a matter of fact it is restarted only once. I am running 1 single login testcase for a single time. So if that is the case, should this problem happen?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Desktop OS/version used to run Appium: High Sierra 10.13.4
* Node.js version (unless using Appium.app|exe): 8.11.1
* Mobile platform/version under test: iOS 11.3.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

**Comment by arjungovindgv** [comment]
I too facing this issue.

**Comment by mykola-mokhnach** [comment]
Closed as inactive
