### ISSUE TITLE
[IOS] Cannot scroll and swipe with Appium 1.8.0. Put app in background when trying to scroll

### ISSUE THREAD

**Issue by KamalSharma23** [appium/appium#10726]
##  The Problem

i am not able to scroll and swipe in IOS App using Appium 1.8.0. I have used following approaches:-

**Approach 1**
final HashMap<String, String> scrollObject = new HashMap<>();
scrollObject.put("direction", "down");
driver.executeScript("mobile: swipe", scrollObject);

**Approach 2**
final HashMap<String, String> scrollObject = new HashMap<>();
scrollObject.put("direction", "down");
driver.executeScript("mobile: scroll", scrollObject);

**Approach 3**
driver.swipe(100, 1000, 100, 500, 1000);

All these approaches put app in background instead of scrolling.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS High Sierra(10.13.4)
* Node.js version (unless using Appium.app|exe):5.8.0
* Mobile platform/version under test:iPhone X(OS: 11.3)
* Real device or emulator/simulator:Real devices
* Appium CLI or Appium.app|exe:Appium CLI

## Link to Appium logs
[debug] [MJSONWP] Calling AppiumDriver.timeouts() with args: [{"protocol":"MJSONWP","type":"implicit","ms":10000},"f83055ce-197f-4f61-8cd7-02ce3bbaf822"]
[debug] [XCUITest] Executing command 'timeouts'
[debug] [BaseDriver] type: implicit, ms: 10000
[debug] [BaseDriver] Set implicit wait to 10000ms
[debug] [MJSONWP] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/f83055ce-197f-4f61-8cd7-02ce3bbaf822/timeouts 200 2 ms - 76
[HTTP] 
[HTTP] --> POST /wd/hub/session/f83055ce-197f-4f61-8cd7-02ce3bbaf822/element/74000000-0000-0000-1804-000000000000/click
[HTTP] {"id":"74000000-0000-0000-1804-000000000000"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/f83055ce-197f-4f61-8cd7-02ce3bbaf822/element/74000000-0000-0000-1804-000000000000/click] to [POST http://localhost:8100/session/35C734E8-5BB6-4D89-9642-BBAC5E3233CB/element/74000000-0000-0000-1804-000000000000/click] with body: {"id":"74000000-0000-0000-1804-000000000000"}
[debug] [JSONWP Proxy] Got response with status 200: {"status":0,"id":"74000000-0000-0000-1804-000000000000","value":"","sessionId":"35C734E8-5BB6-4D89-9642-BBAC5E3233CB"}
[JSONWP Proxy] Replacing sessionId 35C734E8-5BB6-4D89-9642-BBAC5E3233CB with f83055ce-197f-4f61-8cd7-02ce3bbaf822
[HTTP] <-- POST /wd/hub/session/f83055ce-197f-4f61-8cd7-02ce3bbaf822/element/74000000-0000-0000-1804-000000000000/click 200 808 ms - 118
[HTTP] 
[HTTP] --> POST /wd/hub/session/f83055ce-197f-4f61-8cd7-02ce3bbaf822/touch/perform
[HTTP] {"actions":[{"action":"press","options":{"x":100,"y":1000}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"x":100,"y":500}},{"action":"release","options":{}}]}
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":100,"y":1000}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"x":100,"y":500}},{"action":"release","options":{}}],"f83055ce-197f-4f61-8cd7-02ce3bbaf822"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: press(options={"x":100,"y":1000})-wait(options={"ms":1000})-moveTo(options={"x":100,"y":500})-release(options={})
[debug] [JSONWP Proxy] Proxying [POST /wda/touch/perform] to [POST http://localhost:8100/session/35C734E8-5BB6-4D89-9642-BBAC5E3233CB/wda/touch/perform] with body: {"actions":[{"action":"press","options":{"x":100,"y":1000}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"x":100,"y":500}},{"action":"release","options":{}}]}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"35C734E8-5BB6-4D89-9642-BBAC5E3233CB","status":0}
[debug] [MJSONWP] Responding to client with driver.performTouch() result: {}
[HTTP] <-- POST /wd/hub/session/f83055ce-197f-4f61-8cd7-02ce3bbaf822/touch/perform 200 1286 ms - 74
[HTTP] 
[HTTP] --> POST /wd/hub/session/f83055ce-197f-4f61-8cd7-02ce3bbaf822/execute
[HTTP] {"script":"mobile: swipe","args":[{"direction":"down"}]}
[debug] [MJSONWP] Calling AppiumDriver.execute() with args: ["mobile: swipe",[{"direction":"down"}],"f83055ce-197f-4f61-8cd7-02ce3bbaf822"]
[debug] [XCUITest] Executing command 'execute'
[debug] [BaseDriver] Waiting up to 10000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/35C734E8-5BB6-4D89-9642-BBAC5E3233CB/element] with body: {"using":"class name","value":"XCUIElementTypeApplication"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"01000000-0000-0000-1804-000000000000"},"sessionId":"35C734E8-5BB6-4D89-9642-BBAC5E3233CB","status":0}
[XCUITest] Proxying to WDA with an unknown route: POST /wda/element/01000000-0000-0000-1804-000000000000/swipe
[debug] [JSONWP Proxy] Proxying [POST /wda/element/01000000-0000-0000-1804-000000000000/swipe] to [POST http://localhost:8100/session/35C734E8-5BB6-4D89-9642-BBAC5E3233CB/wda/element/01000000-0000-0000-1804-000000000000/swipe] with body: {"direction":"down"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"35C734E8-5BB6-4D89-9642-BBAC5E3233CB","status":0}
[debug] [MJSONWP] Responding to client with driver.execute() result: {}
[HTTP] <-- POST /wd/hub/session/f83055ce-197f-4f61-8cd7-02ce3bbaf822/execute 200 630 ms - 74
[HTTP] 
[HTTP] --> POST /wd/hub/session/f83055ce-197f-4f61-8cd7-02ce3bbaf822/timeouts
[HTTP] {"type":"implicit","ms":0}
[debug] [MJSONWP] Calling AppiumDriver.timeouts() with args: [{"protocol":"MJSONWP","type":"implicit","ms":0},"f83055ce-197f-4f61-8cd7-02ce3bbaf822"]
[debug] [XCUITest] Executing command 'timeouts'
[debug] [BaseDriver] type: implicit, ms: 0
[debug] [BaseDriver] Set implicit wait to 0ms
[debug] [MJSONWP] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/f83055ce-197f-4f61-8cd7-02ce3bbaf822/timeouts 200 4 ms - 76
[HTTP] 
[HTTP] --> GET /wd/hub/session/f83055ce-197f-4f61-8cd7-02ce3bbaf822/context
[HTTP] {}
[debug] [MJSONWP] Calling AppiumDriver.getCurrentContext() with args: ["f83055ce-197f-4f61-8cd7-02ce3bbaf822"]
[debug] [XCUITest] Executing command 'getCurrentContext'
[debug] [MJSONWP] Responding to client with driver.getCurrentContext() result: "NATIVE_APP"
[HTTP] <-- GET /wd/hub/session/f83055ce-197f-4f61-8cd7-02ce3bbaf822/context 200 4 ms - 84
[HTTP] 
[HTTP] --> POST /wd/hub/session/f83055ce-197f-4f61-8cd7-02ce3bbaf822/elements

**Comment by mykola-mokhnach** [comment]
I don't observe any issues in the log. Perhaps the application under test does not interpret swipe the way you expect it to be interpreted. I'd also try to perform the gesture using TouchAction interface.

**Comment by mjm987mj** [comment]
Hi. I'm seeing the same issue. However only on ipad when they are in landscape mode. It would be nice to have a possibility to set on offset for x/y.
