### ISSUE TITLE
documentation issue - JSONWP Specification link is broken

### ISSUE THREAD

**Issue by vikramvi** [appium/appium#10737]
## The problem

1. Goto http://appium.io/docs/en/commands/device/keys/is-keyboard-shown/
2. Check link for JSONWP Specification

Actual Result:
1. Link takes to 404 page

## Environment

NA

## Details

NA

## Link to Appium logs

NA

## Code To Reproduce Issue [ Good To Have ]

NA

**Comment by mykola-mokhnach** [comment]
@dpgraham FYI

**Comment by imurchie** [comment]
This is true for _all_ the spec links that go to our routes module, since the name was changed to `protocol`.

**Comment by imurchie** [comment]
I am working on the docs, I will fix this.

**Comment by imurchie** [comment]
This has been fixed, and the links are now dynamically created so they should stay fixed.

Thanks for the report!
