### ISSUE TITLE
Element Tree Inconsistencies following iOS scroll

### ISSUE THREAD

**Issue by AqaSquad** [appium/appium#10731]
## The problem

In iOS, performing a scroll action causes an unexpected Element Tree change, causing many test failures.

## Environment

* Appium version (or git revision) that exhibits the issue:
       Tested and seen on appium server version 1.7.2 and 1.8.0
* Last Appium version that did not exhibit the issue (if applicable):
       N/A - Tested as far back as 1.7.1 where issue was still seen.
* Desktop OS/version used to run Appium:
       macOS Sierra 10.12.6 (16G1114)
* Node.js version (unless using Appium.app|exe):
       v9.11.1
* Mobile platform/version under test:
       iOS 11.2
* Real device or emulator/simulator:
       Seen on real device and simulator
* Appium CLI or Appium.app|exe:
       Seen on standalone server and appium.app desktop client

Seen with the following combinations:

Appium java-client:         v5.0.4
Appium server:              v1.7.2

Appium java-client:         v5.0.4
Appium server:              v1.8.0

Appium java-client:         v5.0.4
Appium server:              v1.7.1

Appium java-client:         v4.1.2
Appium server:              v1.7.2

Appium java-client:         v4.1.2
Appium server:              v1.8.0

## Details

1. An getPageSource command is issued against the Appium driver and obtain the Element Tree representation of the DOM.

2. A scroll down action is performed.

3. Another getPageSource command obtains the Element Tree and a diff of both the initial and subsequent Element Trees are showing differences. This results in test failures when trying to locate elements within the tree for interactions/validations.

**Element Tree Original**
``` 
<XCUIElementTypeApplication name="AQA SQUAD">
  <XCUIElementTypeWindow>
    <XCUIElementTypeOther>
      <XCUIElementTypeOther>
        <XCUIElementTypeOther>
            <XCUIElementTypeOther>
              <XCUIElementTypeNavigationBar name="AqaSquadView">
              <XCUIElementTypeOther>
                <XCUIElementTypeOther>
                  <XCUIElementTypeOther>
                    <XCUIElementTypeScrollView>
                      <XCUIElementTypeOther>
                        <XCUIElementTypeTable>
                          <XCUIElementTypeOther>
                          <XCUIElementTypeOther name="NEWS">
                            <XCUIElementTypeStaticText name="BREAKING NEWS">
                            <XCUIElementTypeStaticText name="section.header.label">
                            <XCUIElementTypeStaticText name="section.header.seeAll">
                          <XCUIElementTypeCell>
                            <XCUIElementTypeStaticText name="Another Day, Another Dollar">
                            <XCUIElementTypeOther>
 ```
 
**Element Tree Afterwards**
 ```
<XCUIElementTypeApplication name="AQA SQUAD">
  <XCUIElementTypeWindow>
    <XCUIElementTypeOther>
      <XCUIElementTypeOther>
        <XCUIElementTypeOther>
          <XCUIElementTypeOther>
            <XCUIElementTypeOther>
              <XCUIElementTypeOther>
                <XCUIElementTypeOther>
                  <XCUIElementTypeScrollView>
                    <XCUIElementTypeOther>
                      <XCUIElementTypeTable>
                        <XCUIElementTypeOther>
                        <XCUIElementTypeOther name="NEWS">
                          <XCUIElementTypeAny type="XCUIElementTypeAny" enabled="true" visible="false" x="0" y="468" width="375" height="53"/>
                          <XCUIElementTypeAny type="XCUIElementTypeAny" enabled="true" visible="false" x="0" y="468" width="375" height="53"/>
                          <XCUIElementTypeAny type="XCUIElementTypeAny" enabled="true" visible="false" x="0" y="468" width="375" height="53"/>
                        <XCUIElementTypeCell>
                          <XCUIElementTypeStaticText name="Another Day, Another Dollar">
                          <XCUIElementTypeOther>
 ```
**Observations:**
XCUIElementTypeNavigationBar = not exist in runtime.
XCUIElementTypeStaticText has been changed to XCUIElementTypeAny in runtime and attribute and value of name="BREAKING NEWS" is empty in runtime
XCUIElementTypeStaticText has been changed to XCUIElementTypeAny in runtime and attribute and value of  name="section.header.label" is empty in runtime
XCUIElementTypeStaticText has been changed to XCUIElementTypeAny in runtime and attribute and value of name="section.header.seeAll" is empty in runtime

## Link to Appium logs

[GIST - logs](https://gist.github.com/AqaSquad/f92cd0a82eb00956e9cb670be97db503)

**Comment by mykola-mokhnach** [comment]
The tree is generated by [WebDriverAgent](https://github.com/facebook/WebDriverAgent) based on the information provided by XCTest. there is nothing that can be changed on Appium side there

**Comment by AqaSquad** [comment]
Opened issue with https://github.com/facebook/WebDriverAgent and referenced this one for continuity: https://github.com/facebook/WebDriverAgent/issues/933
