### ISSUE TITLE
The diplink does not open after clicking on the Open button in the dialog box (iOS)

### ISSUE THREAD

**Issue by Valentine11** [appium/appium#10738]
## The problem

The diplink does not open after clicking on the Open button in the dialog box (iOS).

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.7.0
* Desktop OS/version used to run Appium: 
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 10.3
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: 

## Details

I'm trying to use in autotests the deeplinks created by our developers for users of our mobile application.
At the opening of the diplink, a dialog box appears with the buttons Open and Cancel. I make a tap on the Open button, the dialog box closes, but nothing happens after that.

## Link to Appium logs

https://gist.github.com/Valentine11/fabca463c1805bb22f80d6deaeab4414

## Code To Reproduce Issue [ Good To Have ]

Here simple method for open deeplink (wd.js):

```
return driver.get(`myapp://doctorList/specialityId/${specId}/cityId/${cityId}`).then(() => {
            return driver.elementByAccessibilityId('Open').then((element) => {
                return driver.tapElement(element);
            })
        });
```

**Comment by mykola-mokhnach** [comment]
Try the latest server version (1.8.1)

**Comment by Valentine11** [comment]
I use third-party service (browserstack), appium 1.7.0 is highest version on the moment...

**Comment by mykola-mokhnach** [comment]
The we won't be able to help. There were some improvements in the recent Appium versions, but we don't patch older versions.
