### ISSUE TITLE
Trying to run DesiredCapabilities code with uiautomator2 and running into appium-uiautomator2-server-v0.1.8.apk does not exist or is not accessible issue

### ISSUE THREAD

**Issue by satgh12** [appium/appium#10732]
## The problem

Trying to run DesiredCapabilities code with uiautomator2 and running into appium-uiautomator2-server-v0.1.8.apk does not exist or is not accessible issue.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1 server.  5.0.4 client
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Ubuntu 16.04 LTS 64-bit
* Node.js version (unless using Appium.app|exe): 8.9.1
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

## Details

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: The file at path /home/sealabubuntu/.nvm/versions/node/v8.9.1/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/uiautomator2/appium-uiautomator2-server-v0.1.8.apk does not exist or is not accessible (WARNING: The server did not provide any stacktrace information)

After I did "npm install appium-uiautomator2-driver" on ubuntu machine, I do not see uiautomator2 folder under appium-uiautomator2-driver folder.  See below.

sealabubuntu@sealabubuntu:~/.nvm/versions/node/v8.9.1/lib/node_modules/appium/node_modules/appium-uiautomator2-driver$ ls -l
total 48
drwxrwxr-x  2 sealabubuntu sealabubuntu  4096 May 14 14:09 bin
drwxrwxr-x  4 sealabubuntu sealabubuntu  4096 May 14 14:09 build
-rw-rw-r--  1 sealabubuntu sealabubuntu   244 Aug 10  2017 gulpfile.js
-rw-rw-r--  1 sealabubuntu sealabubuntu   569 Aug 31  2017 index.js
drwxrwxr-x  3 sealabubuntu sealabubuntu  4096 May 14 14:09 lib
-rw-rw-r--  1 sealabubuntu sealabubuntu 11384 Sep 15  2017 LICENSE
drwxrwxr-x 21 sealabubuntu sealabubuntu  4096 May 14 14:09 node_modules
-rw-rw-r--  1 sealabubuntu sealabubuntu  3853 May 14 14:09 package.json
-rw-rw-r--  1 sealabubuntu sealabubuntu  2860 Apr 26  2017 README.md
drwxrwxr-x  4 sealabubuntu sealabubuntu  4096 May 14 14:09 test

I also looked at a similar issue at https://github.com/appium/appium/issues/8977
It was mentioned to copy apk from https://github.com/appium/appium-uiautomator2-server/releases.  But, there is no apk in there.  I tried to build an apk from Android studio.  It builds an unsigned apk under app/build/outputs/apk folder.  Should I manually create uiautomator2 folder and place the unsigned apk in that folder?  Please help.

## Link to Appium logs

N/A

## Code To Reproduce Issue [ Good To Have ]

N/A

**Comment by mykola-mokhnach** [comment]
Update the server to 1.8.0

**Comment by satgh12** [comment]
I updated appium server to 1.8.0, uninstalled and reinstalled appium-uiautomator2-driver using npm.  I still I do not see uiautomator2 folder under appium-uiautomator2-driver folder.  Should it be there?

Also, updating to 1.8.0 appium server is failing to find elements with my existing automation which was running fine on 1.7.1.  Are there any dependencies I need to look at after upgrading to 1.8.0?  I currently have  Java SE Development Kit 8u171 of jdk on ubuntu.

**Comment by mykola-mokhnach** [comment]
> updating to 1.8.0 appium server is failing to find elements with my existing automation

This might be another problem. Try to ask on Appium forum first.
