### ISSUE TITLE
encountering capability issues --> Original error: The following desired capabilities are required, but were not provided: deviceName

### ISSUE THREAD

**Issue by testerdivyaa** [appium/appium#10739]
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: The following desired capabilities are required, but were not provided: deviceName)","origValue":"The following desired capabilities are required, but were not provided: deviceName"},"sessionId":null}

**Comment by imurchie** [comment]
Add a `deviceName` to your capabilities.

**Comment by mykola-mokhnach** [comment]
Please provide the necessary issue information.

Usually such error is shown if one tries to use newer Appium server with older clients, which don't properly support W3C protocol.
