### ISSUE TITLE
I found  case can running on appium-server of version 1.7.1 faster than appium-server1.8.0,and some elements can click in appium1.7.1 ,but these elements can found and click ,but no effects,

### ISSUE THREAD

**Issue by zhaoxusun** [appium/appium#10746]
## The problem

First of all, I found  case can running on appium-server of version 1.7.1 faster than appium-server1.8.0, some elements can click in appium1.7.1 ,but these elements can found and click but no effect in appium1.7.2&1.8.0&1.8.1
Someone konw the ploblem or reason？？
element is in the app native page，and try to locate element by the way：
`
    @iOSXCUITFindBy(accessibility = "PicassoView_HTLAggregatePrepayRoomPicassoCell")
    @AndroidFindBy(id = "com.sankuai.meituan:id/hotel_qa_auto_test_integrated_room_picassoview")
    @WithTimeout(time = 5,unit = TimeUnit.SECONDS)
    private MobileElement picassoGoodsButton;
    ...
    picassoGoodsButton.click();
    ...
`

## Environment

* Appium version1.7.1&1.7.2&1.8.0&1.8.1
* appium-java-client 5.0.4
* iOS real device 11.1
* cap.automationName=XCUITest

**Comment by mykola-mokhnach** [comment]
Please fill out the issue reporting form properly. The current issue description is totally useless for solution finding purposes.

**Comment by zhaoxusun** [comment]
1.8version, can found element and click ,but I found the app page no effect after element click.
![image](https://user-images.githubusercontent.com/30275668/40472981-8c04482a-5f6d-11e8-852c-b761b9f4ba63.png)
1.7.1version the same element click is ok, I found the app page go to next page after element click.
![image](https://user-images.githubusercontent.com/30275668/40473798-c25f9148-5f6f-11e8-851d-b471053dc429.png)

**Comment by mykola-mokhnach** [comment]
Where the element is located? Is it native app or a webview? Did you try to click by coordinates? what type of element it is?

Even if there is an issue there then it should be reported to https://github.com/facebook/WebDriverAgent since Appium simply proxies requests

**Comment by zhaoxusun** [comment]
@mykola-mokhnach sorry, I will try to reported to https://github.com/facebook/WebDriverAgent later

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
