### ISSUE TITLE
Appium 1.7.2 - Unable to find element in the second app when we switch from first with connection link in IOS

### ISSUE THREAD

**Issue by githubdilip** [appium/appium#10747]
## The problem
I am using appium 1.7.2 with iOS native app in real device. We have two native app interlinked with each other. From one app we can switch to other one using some button link check availability. Once we switch to second app, we are not able to find element with second app. Both app bundle id will have same starting and we have that in provisioning profile also(like wild card). With Appium 1.6.4 its working fine but with 1.7.2 it is not finding element. getting error as 'The application under test with bundle id 'com.xxxx.xxx.xxxxxxx' is not running, possibly crashed'. Please do the needful.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): 1.6.4
* Desktop OS/version used to run Appium:Mac 10.13
* Node.js version (unless using Appium.app|exe):Appium.app
* Mobile platform/version under test: 10.1.1
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe: Appium.app

**Comment by mykola-mokhnach** [comment]
This verification is done on WebDriverAgent side to make sure the application under test didn't crash. If you want to let WDA know, that this behaviour is expected then try to call `terminateApp` with the main application's bundle identifier before doing anything with the second app..

**Comment by githubdilip** [comment]
@mykola-mokhnach Thank you for the help. After terminating the first app do we need to start the second app ?

**Comment by githubdilip** [comment]
Able to find the element after terminateApp in the second app, but the unable to bring the first app back. Please do the needful.

**Comment by mykola-mokhnach** [comment]
How do you expect to bring it back after it was terminated? There is activateApp primitive, which allows to activate an app with given bundle id.
