### ISSUE TITLE
Appium 1.8.1 cannot switch to webview context for iOS real device

### ISSUE THREAD

**Issue by jacattau** [appium/appium#10741]
## The problem

Appium 1.8.1 cannot switch to a webview context in a hybrid app for iOS.  According to the logs it is seeing 2 views, Native and Webview, but it's saying it's timing out when trying to switch.  This just started happening in 1.8.1.  It works just fine in 1.8.0.  I am tried using the startIWDP capability and using IWDP in terminal manually with the same result.  I have updated to the latest IWDP as of issue [google/ios-webkit-debug-proxy#259](https://github.com/google/ios-webkit-debug-proxy/issues/259) and artygus updating master.  

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1 (latest release)
* Last Appium version that did not exhibit the issue (if applicable): 1.8.0
* Desktop OS/version used to run Appium: Mac High Sierra
* Node.js version (unless using Appium.app|exe): 9.6.1
* Mobile platform/version under test: iOS 11.3.1
* Real device or emulator/simulator:  Real Device
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

https://gist.github.com/jacattau/9e19fc352083090c6e5c6804cd9555c4

## Code To Reproduce Issue [ Good To Have ]

`		if (device.isAndroidDevice()){
			driver.context(ANDROID_WEBVIEW_CONTEXT);
		} else {
			while (driver.getContextHandles().size() != 2){
				System.out.println("Looking for webview");
				try{Thread.sleep(1000);}catch (Exception e){}
			}
			Set<String> contexts = driver.getContextHandles();
			String[] availableContexts = contexts.toArray(new String[0]);
			driver.context(availableContexts[1]);
		}`

in the last line, trying to switch to availableContexts[1] (which is the webview) does not work anymore.  the AutoWebView capability doesn't work either.

**Comment by imurchie** [comment]
Oh no! A dependency was not published when 1.8.1 was published.

Can you try installing Appium with the `--no-shrinkwrap` flag (`npm install -g appium --no-shrinkwrap`)?

**Comment by imurchie** [comment]
Can you check what version of `appium-remote-debugger` is installed?

```
npm ls -g appium-remote-debugger
```

**Comment by jacattau** [comment]
`Last login: Wed May 23 13:01:48 on ttys000
C02Q3C0AG8WP:~ user$ npm ls -g appium-remote-debugger
/Users/user/npm/lib
└─┬ appium@1.8.1
  ├─┬ appium-ios-driver@2.4.4
  │ └── appium-remote-debugger@3.11.2 
  └─┬ appium-xcuitest-driver@2.84.0
    └── appium-remote-debugger@3.11.2  deduped
`

**Comment by imurchie** [comment]
Sorry for the bother. I think npm was having a propagation issue. Can you try again to re-install. `appium-remote-debugger` ought to come out as v3.12.0. I just tried and it is working now.

**Comment by jacattau** [comment]
I am still getting v3.11.2 unfortunately.  This was reinstalling with --no-shrinkwrap.

**Comment by SergheiRidico** [comment]
I have installed `appium-remote-debugger v3.11.2` using command: `npm install -g appium-remote-debugger` but I still can not switch context to webview on the real device.

**Comment by imurchie** [comment]
Also, installing alongside Appium will not work.

There is a new beta out. Please try that (`npm uninstall -g appium && npm install -g appium@beta`).

**Comment by jacattau** [comment]
@imurchie I have confirmed 1.8.2-beta does installed v3.12.0 of `appium-remote-debugger` and I can successfully switch to webviews!  I will run a full regression on my app and see if I encounter any issues.

**Comment by imurchie** [comment]
Excellent! Sorry for the confusion on this.

**Comment by SergheiRidico** [comment]
@jacattau my mistake. I meant `appium-remote-debugger v3.12.0`. Version 3.11.2 was installed by default.

**Comment by shabsi4u** [comment]
@imurchie @mykola-mokhnach Is there any way this can be fixed on 1.8.1? The problem is that we have a device lab and device lab owners update appium versions only once a few months. This is planned in a couple of weeks and unless the release version is 1.8.2 at that point of time, they wil update the appium version with 1.8.1. Could this change be baked in somehow to 1.8.1 release?

**Comment by jacattau** [comment]
I agree with @shabsi4u, we probably use the same vendor.  This is my biggest fear.

**Comment by shabsi4u** [comment]
@jacattau I saw a comment above that says you were able to successfully switch to webview on updating to 1.8.2 beta. However I am still running into issues (probably when switching back to native context)
[appium_log.pdf](https://github.com/appium/appium/files/2125598/appium_log.pdf)
.

@imurchie Can you look at this? Please find the logs attached
