### ISSUE TITLE
UIAutomator2 crashes: AppiumUiAutomator2Server:INSTRUMENTATION_RESULT: shortMsg=Process crashed

### ISSUE THREAD

**Issue by eduardoreynoso** [appium/appium#10749]
## The problem
UiAutomator2 crashes when initializing a new remote driver

## Environment

* Appium version: 1.8.1
* Desktop OS: macOS High Sierra 10.16.4
* Node.js version (unless using Appium.app|exe): v8.6.0
* Mobile platform/version under test: Nexus 5 X Api level 27 8.1 Oreo
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

I see that in the Server there is a log entry:
`[debug] [UiAutomator2] [UIAutomator2] io.appium.uiautomator2.server.test.AppiumUiAutomator2Server:INSTRUMENTATION_RESULT: shortMsg=Process crashed.`
This is returning a response in the Appium-Python-Client library (0.26):
<pre>
{'status': 400, 'value': '{"value":{"message":"Could not proxy command to remote server. Original error: Error: read ECONNRESET","stacktrace":"ProxyRequestError: Could not proxy command to remote server. Original error: Error: read ECONNRESET\\n    at JWProxy.proxy$ (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:152:13)\\n    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)\\n    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)\\n    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)\\n    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)\\n    at <anonymous>"}}'}
</pre>

## Link to Appium logs
Full appium logs: https://gist.github.com/eduardoreynoso/22daff835172c52ccf5dd987f711465c

**Comment by mykola-mokhnach** [comment]
Can you also attach logcat output?

**Comment by eduardoreynoso** [comment]
@mykola-mokhnach https://gist.github.com/eduardoreynoso/3a3517ca6ca9fa6bc898efa55ebdcf87 
Crash starts at line 695
Thank you for taking the time to review this!

**Comment by mykola-mokhnach** [comment]
@vmaxim any ideas on this?

**Comment by mykola-mokhnach** [comment]
Try to reboot/reset the device

**Comment by eduardoreynoso** [comment]
Wiping the device with avd manager makes it work a while but then the same issue starts happening again after several test runs. It happens on different emulators and with several apps too

**Comment by mykola-mokhnach** [comment]
It looks like uiautomator process does not get killed due to some unknown reason. can you show the output of `adb shell ps` command on the device when this error happens?

**Comment by eduardoreynoso** [comment]
For sure, I will to that tomorrow morning, thanks again!

**Comment by vmaxim** [comment]
@mykola-mokhnach I think it's nothing to do with appium. According the logs `io.appium.uiautomator2.server` was killed - so there is another process which using `UiAutomationService` eg. #10333, #4284

**Comment by vmaxim** [comment]
@mykola-mokhnach uninstall the server app or ```adb root && adb shell kill -9 PID && adb unroot``` :)

**Comment by mykola-mokhnach** [comment]
> so there is another process which using UiAutomationService eg. #10333, #4284

@eduardoreynoso are you sure that UIA2 server is the only user of UIA service?

**Comment by eduardoreynoso** [comment]
@mykola-mokhnach I got the available processes when the crash happens: https://gist.github.com/eduardoreynoso/ef99b3eb57f9615232a1c03d84b052db
I see the last one is `shell        26699  1455 1177956  79408 sk_wait_data eba9daf0 S uiautomator`
Killing that process solves the issue so I am guessing that your suggestion of killing the uia process instances on server startup would be adequate.

**Comment by mykola-mokhnach** [comment]
Can you try to apply the patch https://github.com/appium/appium-uiautomator2-driver/pull/174 locally and see if it helps? use `gulp transpile` command to transpile the updated sources

**Comment by mykola-mokhnach** [comment]
@eduardoreynoso Have you tried the patch? We cannot merge it without being verified by you first

**Comment by eduardoreynoso** [comment]
@mykola-mokhnach I will try it today and post my results, thank you very much!

**Comment by eduardoreynoso** [comment]
Full logs with patch: https://gist.github.com/eduardoreynoso/90364f2dca678c005966b2911f93e516

I tried the patch and Im seeing the following behavior:
I still see a message that the UIAutomator2 process crashed (lines 53 and 54)
<pre>
[debug] [UiAutomator2] [UIAutomator2] io.appium.uiautomator2.server.test.AppiumUiAutomator2Server:INSTRUMENTATION_RESULT: shortMsg=Process crashed.
[debug] [UiAutomator2] [UIAutomator2] INSTRUMENTATION_CODE: 0
</pre>
And it happens before your code to kill the process gets called (lines 129 and 130)
<pre>
[debug] [ADB] Running '/Users/kyrenejackson/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell ps'
[debug] [ADB] Running '/Users/kyrenejackson/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop io.appium.uiautomator2.server'
</pre>
However I do see one more attempt of force kill the ui2 process on line 50, but I do not think that is part of your patch since I saw in the PR that you query for the processes before killing it

The interesting things is that even though I am seeing the crash in the appium logs it seems to continue the execution and is able to instantiate the remote driver and interact with the app which did not happened before. What do you think @mykola-mokhnach ?

**Comment by mykola-mokhnach** [comment]
Are you sure the patch has been properly applied? I expect to see `ps` call there.

**Comment by eduardoreynoso** [comment]
I cloned the appium repository and I installed your fork from the uiautomator depenency:
`npm install https://github.com/mykola-mokhnach/appium-uiautomator2-driver.git\#kill_uia`
Then I went to the node modules for appium-uiautomator2-driver and ran `gulp transpile` 
Then I ran the appium server with `node .`
Am I missing something? I apologize I am not that familiar with `npm`

**Comment by mykola-mokhnach** [comment]
- install appium
- open `/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/lib` or where the sources are located
- change the necessary source file there
- run `gulp transplie` in the same folder
- restart appium server

**Comment by eduardoreynoso** [comment]
@mykola-mokhnach I am certain that I am running your patch I do see on the logs:
<pre>
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Running '/Users/eduardoreynoso/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell ps'
</pre>
Same as the log that I posted the first time. I still see that the UIAutomator2 process crashed. I am trying to reproduce the exact error that I was getting. In order to reproduce the crash message you can try to instantiate several remote drivers at the same time, that will trigger this message:
<pre>
[debug] [UiAutomator2] [UIAutomator2] io.appium.uiautomator2.server.test.AppiumUiAutomator2Server:INSTRUMENTATION_RESULT: shortMsg=Process crashed.
</pre>
But the behavior that I am seeing with your patch is that it can actually continue execution and create the remote driver so I believe it is working. Do you need more info on this?

**Comment by mykola-mokhnach** [comment]
No, thanks. I think the fact, that it works with the patch is enough.

**Comment by eduardoreynoso** [comment]
@mykola-mokhnach Awesome, thanks again for the quick turnaround for this issue!

**Comment by mykola-mokhnach** [comment]
The fix is available in appium@beta

**Comment by auto-mator** [comment]
literally still occurs every 3 tests...

**Comment by auto-mator** [comment]
Appium 1.8.2 Beta
[debug] [UiAutomator2] [UIAutomator2] INSTRUMENTATION_RESULT: shortMsg=Process crashed.
[debug] [UiAutomator2] [UIAutomator2] INSTRUMENTATION_CODE: 0

occurs during tests...

**Comment by dineshchakravarthy5** [comment]
> Appium 1.8.2 Beta
> [debug] [UiAutomator2] [UIAutomator2] INSTRUMENTATION_RESULT: shortMsg=Process crashed.
> [debug] [UiAutomator2] [UIAutomator2] INSTRUMENTATION_CODE: 0
> 
> occurs during tests...

@auto-mator  If you are using testNG, include Thread.sleep(5000) in @aftermethod it helped me to overcome the same issue(At least as a temporary workaround ).
I think the problem is appium server trying to execute next command in APP/device even before it is ready(Probably still loading/Previous action is still happening) ,so uiautomator2 getting crashed.

Try if it works for you as well.

**Comment by dineshchakravarthy5** [comment]
> > Appium 1.8.2 Beta
> > [debug] [UiAutomator2] [UIAutomator2] INSTRUMENTATION_RESULT: shortMsg=Process crashed.
> > [debug] [UiAutomator2] [UIAutomator2] INSTRUMENTATION_CODE: 0
> > occurs during tests...
> 
> @auto-mator If you are using testNG, include Thread.sleep(5000) in @aftermethod it helped me to overcome the same issue(At least as a temporary workaround ).
> I think the problem is appium server trying to execute next command in APP/device even before it is ready(Probably still loading/Previous action is still happening) ,so uiautomator2 getting crashed.
> 
> Try if it works for you as well.

Also, Updating uiautomator2 server & driver alone could also resolve this issue. It worked for me.
