### ISSUE TITLE
 WebDriverWait.until 10 second granularity?

### ISSUE THREAD

**Issue by gergm** [appium/appium#10759]
## The problem

WebDriverWait(self.driver, timeout).until(element_presence) seems to have a minimum wait time of 100 seconds

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 10.13.4
* Node.js version (unless using Appium.app|exe): 8.2.1
* Mobile platform/version under test: iOS 11.3 and Android API level 27
* Real device or emulator/simulator: emulator / simulator
* Appium CLI or Appium.app|exe: 

## Details

I have noticed that this code snippet:

        element_presence = EC.presence_of_element_located(locator)
        WebDriverWait(self.driver, timeout).until(element_presence)

When timeout is set to 1, the wait time is actually about 10 seconds. Here is the corresponding snippet from the Appium log:

2018-05-25 00:21:02:521 - [debug] e[35m[W3C]e[39m Calling AppiumDriver.findElement() with args: ["id","com.blah.blahrkitandroiddemo:id/gnot","40c1b16f-9ada-4822-a431-da4c5e9608f4"]
2018-05-25 00:21:02:521 - [debug] e[35m[BaseDriver]e[39m Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
2018-05-25 00:21:02:522 - [debug] e[35m[BaseDriver]e[39m Waiting up to 10000 ms for condition

When I set the WebDriverWait timeout to > 10 seconds, I see multiple calls to find with the 10 second wait.

Is there any way for me to reduce the Waiting up to 10000 ms for condition to a 1 second (or other) wait time? That is, is there some BaseDriver config that I can tweak?

I am running on:
macOS 10.13.4
Appium v1.8.0
Appium-Python-Client 0.26

I see the same behavior testing Android with UiAutomator2 and testing iOS with XCUITest

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

        element_presence = EC.presence_of_element_located(locator)
        WebDriverWait(self.driver, timeout).until(element_presence)

**Comment by gergm** [comment]
@mykola-mokhnach Thanks very much. The implicit wait is definitely the cause.

Is zero the best value to use? What is the default, ie, if WebDriver.implicitly_wait() is not called?

**Comment by mykola-mokhnach** [comment]
Yes, I usually set the value of implicit wait to zero in my project.

The default value is usually controlled by the client (selenium API), so you can check it on your side.
