### ISSUE TITLE
Is there a way to set the timeout duration for closing the webdriver?

### ISSUE THREAD

**Issue by bastenf** [appium/appium#10750]
## The problem

I got "failed to close window in 20 seconds" when I try to call WebDriver.close()

## Environment

* Appium 1.8.1:
* Windows7:
* Node.js 8.9.4:
* Android 7:
* Appium CLI

## Details

It is in hybird testing, I switch the context to H5 webview and then go a window to test something, when I try to close the window, it throw this exception

## Link to Appium logs

[debug] [JSONWP Proxy] Proxying [DELETE /wd/hub/session/2f31b7e3-872f-4be4-9da6-
668c0a78538a/window] to [DELETE http://127.0.0.1:8000/wd/hub/session/c0686233ced
8edbe33cf7843414407f5/window] with body: {}
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.getStatus() with args: []
[debug] [W3C] Responding to client with driver.getStatus() result: {"build":{"ve
rsion":"1.8.1","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 8 ms - 55
[HTTP]
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.getStatus() with args: []
[debug] [W3C] Responding to client with driver.getStatus() result: {"build":{"ve
rsion":"1.8.1","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 13 ms - 55
[HTTP]
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.getStatus() with args: []
[debug] [W3C] Responding to client with driver.getStatus() result: {"build":{"ve
rsion":"1.8.1","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 10 ms - 55
[HTTP]
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.getStatus() with args: []
[debug] [W3C] Responding to client with driver.getStatus() result: {"build":{"ve
rsion":"1.8.1","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 11 ms - 55
[HTTP]
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"c0686233ced8e
dbe33cf7843414407f5","status":13,"value":{"message":"unknown error: failed to cl
ose window in 20 seconds\n (Session info: chrome=57.0.2987.132)\n (Driver info
: chromedriver=2.26.436362 (5476ec6bf7ccbada1734a0cdec7d570bb042aa30),platform=W
indows NT 6.1.7601 SP1 x86_64)"}}

## Code To Reproduce Issue [ Good To Have ]

        AppiumDriver a = this.getContext().getWebDriver();
        a.context("WEBVIEW_com.tencent.mm:tools");
        a.switchTo().window("XXXXXXXXXXXX");
        a.close();

**Comment by bastenf** [comment]
I tried to set newCommandTimeout and webdriver.manage().timeouts().implicitlyWait(120, TimeUnit.SECONDS);

but both are no use

**Comment by mykola-mokhnach** [comment]
There is no way to limit it on appium side, because the operation is done by chrome driver.
