### ISSUE TITLE
Feature Request: Return pageDict on contexts request

### ISSUE THREAD

**Issue by eduardoreynoso** [appium/appium#10757]
## The problem
I am working on an app that renders content in multiple web views even on the same native view (a list with ads) and I am having trouble interacting with each one of them because I cannot find a way to select a specific web view context.
I see that Appium retrieves more information about the contexts than the information that sends back in the request. Currently it only sends back a list of strings with the available context and a suffix of the PID example:
`['NATIVE_APP', 'WEBVIEW_27218.1', 'WEBVIEW_27215.6', 'WEBVIEW_27551.1', 'WEBVIEW_27224.1']`
But in the appium server I see that more information is retrieved for example:
<pre>
[debug] [RemoteDebugger]     Application: 'PID:27551'
[debug] [RemoteDebugger]         id: "PID:27551"
[debug] [RemoteDebugger]         isProxy: true
[debug] [RemoteDebugger]         name: "com.apple.WebKit.WebContent"
[debug] [RemoteDebugger]         bundleId: "com.apple.WebKit.WebContent"
[debug] [RemoteDebugger]         hostId: "PID:27530"
[debug] [RemoteDebugger]         isActive: 1
[debug] [RemoteDebugger]         isAutomationEnabled: false
[debug] [RemoteDebugger]         pageDict: [{"id":1,"title":"Shop Your Way - Registration | Shop Your Way: Online Shopping & Earn Points on Tools, Appliances, Electronics & more","url":"https://www.shopyourway.com/secured/m/sign-in-or-register?dinghy=true&returnUrl=%2fsecured%2fmp%2fconnect%2fnative%3fappid%3d16250%26target%3dhttp%253A%252F%252Fwww.winitapp.com%252Fusers%252Flogin%252F%26forceToken%3dtrue","isKey":false}]
</pre>
It would be really useful to retrieve the pageDict because it contains the URL of the web view and I could use it to differentiate it from the other web views.

Here is the full output of the appium log with several contexts:
https://gist.github.com/eduardoreynoso/6ec2cecea5ec0441ab2db9104c6b8cea

I tried to search for the code that returns this but I cannot find it. If someone points me in the right direction I could potentially add this feature myself.
Thanks!

**Comment by imurchie** [comment]
I agree. I started on this a while back but have not finished. I'll add to the queue.

**Comment by eduardoreynoso** [comment]
@imurchie thank you for taking a look on this one. Let me know If I can help and It would be great if you could tag me on the PR for this, I would like to get more involved with appium development.

**Comment by imurchie** [comment]
Most of the development on this was actually already done. https://github.com/appium/appium-xcuitest-driver/pull/689 is the remainder.

**Comment by mykola-mokhnach** [comment]
The feature is present in appium@beta
