### ISSUE TITLE
ADB install fails for the testOnly apps

### ISSUE THREAD

**Issue by email2vimalraj** [appium/appium#10758]
## The problem

My app is built with android:testOnly="true" which I may not be able to change it by myself in the manifest due to many constraints. By default, the appium installs the app using `adb install <app path>`, however if the installation fails with `Failure [INSTALL_FAILED_TEST_ONLY: installPackageLI]'`, it should retry installing using the following command: `adb install -t <app path>`.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.8.0
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Mac OsX v10.13.3
* Node.js version (unless using Appium.app|exe): NA
* Mobile platform/version under test: Android v8.1.0
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium.app

## Link to Appium logs

Appium Log: https://gist.github.com/email2vimalraj/e6aeb3686015baf85faeb1a2bcb28f6e

**Comment by mykola-mokhnach** [comment]
The feature is available in appium@beta. Capability name is `allowTestPackages`

**Comment by enix12enix** [comment]
Is this feature released?

**Comment by ericsavoiewaltz** [comment]
@enix12enix I just used it in my framework and noticed the -t was added to the install command. Seems to be working.

**Comment by joshuapinter** [comment]
Confirmed working in `appium` version `1.13.0`. 👍
