### ISSUE TITLE
Pop-up on Android, iOS

### ISSUE THREAD

**Issue by MickleH** [appium/appium#10753]
## The problem

When test is running on Android/iOS I see a pop-up where I'm asked to 'Allow' or 'Block' it. 
How can I handle it via 'desired capabilities'?
I tried to set in Android:
        "autoGrantPermissions": "true" but it did not help me.
Also I tried to use iOS capabilities,  as:
        "locationServicesEnabled": true,
        "locationServicesAuthorized": true,
        "autoAcceptAlerts": true,
        "bundleId": "io.appium.TestApp"

## Environment

We are using Nightwatch.js, Android platform 7.1, iOS platform 10.2.

![screen shot 2018-05-25 at 2 08 04 pm](https://user-images.githubusercontent.com/39618786/40542415-9688e51a-600f-11e8-8409-952a7738994e.png)

**Comment by mykola-mokhnach** [comment]
Switch to native context and locate/click the Allow button like any other normal button if it is visible in the source tree  (or you have a problem if not). Tricks with alerts won't help here.

**Comment by MickleH** [comment]
mykola-mokhnach , In Nightwatch.js we have native commands to work with alerts (pop-ups) such as .acceptAlert() and .dismissAlert() but these command doesn't see/handle this pop-up.

**Comment by mykola-mokhnach** [comment]
I know nothing about such framework and can only say what the appium android driver itself is able to do. Perhaps, it would be a better idea to address your question to that framework authors instead?
