### ISSUE TITLE
Integrate automatic 3-rd party dependencies management

### ISSUE THREAD

**Issue by mykola-mokhnach** [appium/appium#10752]
It might be very handy (and also secure) to receive 3-rd party npm module updates automatically. I know at least two tools which are able to do it: [greenkeeper.io](greenkeeper.io) and [david-dm.org](david-dm.org)

**Comment by dpgraham** [comment]
Agreed. I think we should use Greenkeeper.io and have the npm-shrinkwrap.json always be committed.

**Comment by imurchie** [comment]
I agree, and have been meaning to do it for a while.

**Comment by mykola-mokhnach** [comment]
Closed as fixed
