### ISSUE TITLE
Unable to Launch Appium Inspector 

### ISSUE THREAD

**Issue by SapizonTechnologiesLLP** [appium/appium#10762]
## The problem
Unable to launch appium inspector 

successfully deployed the UIcatalog application on IOS device using apple developer account through the Xcode. Now I have set the JSON Representation as below 

{
  "deviceName": "iphone 7",
  "udid": "45bd7b306f9607dd377b44c4ff75fee6247bd7bd",
  "automationName": "XCUITest",
  "platformName": "ios",
  "bundled": "com.example.apple-samplecode.UICatalog",
  "platformVersion": "11.3.1",
  "appName": "UICatalog"
}

when I click on start session am facing an error as could not connect to server; are you sure it is running?
## Environment

* Appium version (or git revision) that exhibits the issue: Using Appium desktop application 1.6.1 v1.8.0
* Desktop OS/version used to run Appium: macOS High Sierra Version 10.13.4
* Node.js version (unless using Appium.app|exe): v8.9.4
* Mobile platform/version under test: Iphone 7 
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/appium/appium-desktop
