### ISSUE TITLE
Touch Down and Touch Up support on XCUITest

### ISSUE THREAD

**Issue by jumois** [appium/appium#10767]
## The problem

Both Touch Down and Touch Up actions respond "HTTP/1.1 501 Not Implemented" (or with python-client: "WebDriverException: Message: Method has not yet been implemented") when requested for iOS device. According to the [Touch Down](https://appium.io/docs/en/commands/interactions/touch/touch-down/) and [Touch Up](https://appium.io/docs/en/commands/interactions/touch/touch-up/) documentation, they should be both supported on iOS 9.3+ with XCUITest driver and Appium 1.6.0+ and with all Appium clients.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 10.13.4
* Node.js version (unless using Appium.app|exe): v10.1.0
* Mobile platform/version under test: 11.3.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: cli

## Details

Is the documentation for Touch Up and Touch Down incorrect or am I using them incorrectly with Appium Python Client? Is the support for these touch actions possible on XCUITest?

## Link to Appium logs

> [HTTP] --> POST /wd/hub/session/a13d0b8d-cc4d-4f8d-8db4-48b31eee1102/touch/down
> [HTTP] {"x":188,"y":325,"sessionId":"a13d0b8d-cc4d-4f8d-8db4-48b31eee1102"}
> [debug] [W3C] Calling AppiumDriver.touchDown() with args: [188,325,"a13d0b8d-cc4d-4f8d-8db4-48b31eee1102"]
> [debug] [XCUITest] Executing command 'touchDown'
> [HTTP] <-- POST /wd/hub/session/a13d0b8d-cc4d-4f8d-8db4-48b31eee1102/touch/down 501 1 ms - 122

## Code To Reproduce Issue [ Good To Have ]

With Python Appium Client:

```
from selenium.webdriver.common.touch_actions import TouchActions

TouchActions(driver).tap_and_hold(188,325).perform()
```

With curl:

`curl --header "Content-Type: application/json"   --request POST   --data '{"x":188,"y":325}' -i http://localhost:4723/wd/hub/session/<Session_ID>/touch/down`

**Comment by mykola-mokhnach** [comment]
Try `press-perform`, however if it does not work then there is nothing we can do about that - XCTest simply does not support such tricks.
