### ISSUE TITLE
org.openqa.selenium.WebDriverException: Only these gestures are supported

### ISSUE THREAD

**Issue by yjplxq** [appium/appium#10769]
Appium desktop v1.5.0

The problem

When I test with a real Iphone，I would like to slide to unlock the screen ，only in a gesture that you draw a straight line with at most 3 points,but you can't make a turn(for example draw a type L is forbidden )。Could you do me a favor,How to achieve this function.thanks

the following is the code:

MobileElement element_1 = (MobileElement) driver.findElementByXPath("(//XCUIElementTypeButton[@name="lock botton unselected"])[1]");
MobileElement element_2 = (MobileElement) driver.findElementByXPath("(//XCUIElementTypeButton[@name="lock botton unselected"])[2]");
MobileElement element_3 = (MobileElement) driver.findElementByXPath("(//XCUIElementTypeButton[@name="lock botton unselected"])[3]");
MobileElement element_9 = (MobileElement) driver.findElementByXPath("(//XCUIElementTypeButton[@name="lock botton unselected"])[9]");
TouchAction action = new TouchAction(driver);
//action.press(element_1).waitAction(200).moveTo(element_3).release().perform();
action.press(element_1).waitAction(200).moveTo(element_3).waitAction(200).moveTo(element_6).release().perform();
Thread.sleep(1000);

the following is the error:

org.openqa.selenium.WebDriverException: Support for press(options={"element":"2F308319-697D-40D8-A422-CB974CFB81CC"})-wait(options={"ms":200})-moveTo(options={"element":"A9A836C1-6F8C-4527-A90F-922305A92D76"})-wait(options={"ms":200})-moveTo(options={"element":"C68AFF5D-5A74-44DE-804B-92FE1965B0CC"})-release(options={}) gesture is not implemented. Try to use "mobile: *" interface to workaround the issue. Only these gestures are supported:
doubleTap: doubletap
tap(options={"count":2})
tap: tap
tap-release
press-release
longPress: longpress
longpress-release
press-wait-release
drag: press-wait-moveTo-release
longpress-moveTo-release
scroll: press-moveTo-release
(WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 44 milliseconds

Environment

mac 10.13.4
iphone 11.3.1

**Comment by mykola-mokhnach** [comment]
This is as designed for Appium server below 1.8.0.

**Comment by Kitty2014** [comment]
@mykola-mokhnach  if >1.8.0, could  you show the demo code for three  or  four point touchAction

**Comment by Kitty2014** [comment]
@yjplxq
