### ISSUE TITLE
[Android] An unknown server-side error occurred while processing the command

### ISSUE THREAD

**Issue by lamquangthanh** [appium/appium#10766]
[log_cat.txt](https://github.com/appium/appium/files/2046677/log_cat.txt)
## The problem
[debug] [W3C] Calling AppiumDriver.findElements() with args: ["id","com.accor.appli.hybrid:id/accor_toolbar","1a65fd21-a35f-4f69-bf6b-dc106bf19                                   b20"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8200/wd/hub/session/a91e0c51-6310-4940-9cc2-9206fde8b9a8/elements] w                                   ith body: {"strategy":"id","selector":"com.accor.appli.hybrid:id/accor_toolbar","context":"","multiple":true}
[MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Error: conne                                   ct ECONNREFUSED 127.0.0.1:8200
[MJSONWP]     at JWProxy.proxy$ (C:\Users\Ekino\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.                                   js:152:13)
[MJSONWP]     at tryCatch (C:\Users\Ekino\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Ekino\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runt                                   ime\regenerator\runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\Ekino\AppData\Roaming\npm\node_modules\appium\n                                   ode_modules\babel-runtime\regenerator\runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (C:\Users\Ekino\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerat                                   or\runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session/1a65fd21-a35f-4f69-bf6b-dc106bf19b20/elements 500 1018 ms - 271

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Win 10
* Node.js version (unless using Appium.app|exe): 5.8.0
* Mobile platform/version under test: Android v6.0.1
* Real device or emulator/simulator: SS S6 Edge
* Appium CLI or Appium.app|exe:

**Comment by mykola-mokhnach** [comment]
This means that the server has stopped responding to Appium requests. Can you also attach the logcat output for this time period?

**Comment by lamquangthanh** [comment]
@mykola-mokhnach after fail test, i use adb devices to check connection of devices. It's still connected. And just happened on android 6.x. Also check on 7.0 but it's not happen.

**Comment by lamquangthanh** [comment]
@mykola-mokhnach  i also updated my logcat file in description. Please have a look on it.

**Comment by mykola-mokhnach** [comment]
I don't observe any issues with uia2 server itself in the attached log, however there are some exceptions caused by the application under test, for example

```
E/Parcel  ( 3501): Class not found when unmarshalling: com.accorhotels.mobile.search.views.searchengine.components.searchdestination.widgets.SearchDestinationWidget$AttrHolder
E/Parcel  ( 3501): java.lang.ClassNotFoundException: com.accorhotels.mobile.search.views.searchengine.components.searchdestination.widgets.SearchDestinationWidget$AttrHolder
E/Parcel  ( 3501):      at java.lang.Class.classForName(Native Method)
E/Parcel  ( 3501):      at java.lang.Class.forName(Class.java:309)
E/Parcel  ( 3501):      at java.lang.Class.forName(Class.java:273)
E/Parcel  ( 3501):      at android.os.Parcel.readParcelableCreator(Parcel.java:2281)
E/Parcel  ( 3501):      at android.os.Parcel.readParcelable(Parcel.java:2245)
E/Parcel  ( 3501):      at android.os.Parcel.readValue(Parcel.java:2152)
E/Parcel  ( 3501):      at android.os.Parcel.readArrayMapInternal(Parcel.java:2485)
E/Parcel  ( 3501):      at android.os.BaseBundle.unparcel(BaseBundle.java:221)
E/Parcel  ( 3501):      at android.os.BaseBundle.getString(BaseBundle.java:918)
E/Parcel  ( 3501):      at android.content.Intent.getStringExtra(Intent.java:5767)
E/Parcel  ( 3501):      at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2365)
E/Parcel  ( 3501):      at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1848)
E/Parcel  ( 3501):      at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5811)
E/Parcel  ( 3501):      at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:5595)
E/Parcel  ( 3501):      at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:142)
E/Parcel  ( 3501):      at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3788)
E/Parcel  ( 3501):      at android.os.Binder.execTransact(Binder.java:461)
E/Parcel  ( 3501): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.accorhotels.mobile.search.views.searchengine.components.searchdestination.widgets.SearchDestinationWidget$AttrHolder" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
E/Parcel  ( 3501):      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/Parcel  ( 3501):      at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/Parcel  ( 3501):      at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/Parcel  ( 3501):      ... 17 more
E/Parcel  ( 3501):      Suppressed: java.lang.ClassNotFoundException: com.accorhotels.mobile.search.views.searchengine.components.searchdestination.widgets.SearchDestinationWidget$AttrHolder
E/Parcel  ( 3501):              at java.lang.Class.classForName(Native Method)
E/Parcel  ( 3501):              at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/Parcel  ( 3501):              at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/Parcel  ( 3501):              at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/Parcel  ( 3501):              ... 18 more
E/Parcel  ( 3501):      Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

or

```
E/art     (27897): invalid stream - problem with parameter iterator in /data/app/com.accor.appli.hybrid-1/base.apk for method void com.accorhotels.commonui.activities.e.call(java.lang.Object)
E/WindowManager(27897):
E/WindowManager(27897): android.view.WindowLeaked: Activity com.accorhotels.hotellist.activities.ListHotelActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{22a65753 V.E..... R......D 0,0-1336,320} that was originally added here
E/WindowManager(27897):         at android.view.ViewRootImpl.<init>(ViewRootImpl.java:500)
E/WindowManager(27897):         at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:287)
E/WindowManager(27897):         at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:87)
E/WindowManager(27897):         at android.app.Dialog.show(Dialog.java:313)
E/WindowManager(27897):         at com.accorhotels.commonui.views.a.show(SourceFile:27)
E/WindowManager(27897):         at com.accorhotels.commonui.activities.h.i(SourceFile:483)
E/WindowManager(27897):         at com.accorhotels.commonui.activities.a.a(SourceFile:285)
E/WindowManager(27897):         at com.accorhotels.commonui.activities.e.call(Unknown Source)
E/WindowManager(27897):         at rx.d.a(SourceFile:10256)
E/WindowManager(27897):         at rx.internal.operators.g.a(SourceFile:48)
E/WindowManager(27897):         at rx.internal.operators.g.call(SourceFile:33)
E/WindowManager(27897):         at rx.internal.operators.f.a(SourceFile:48)
E/WindowManager(27897):         at rx.internal.operators.f.call(SourceFile:30)
E/WindowManager(27897):         at rx.d.a(SourceFile:10352)
E/WindowManager(27897):         at rx.d.b(SourceFile:10319)
E/WindowManager(27897):         at rx.d.a(SourceFile:10159)
E/WindowManager(27897):         at com.accorhotels.hotellist.fragments.r.onCreateView(SourceFile:418)
E/WindowManager(27897):         at android.support.v4.app.Fragment.performCreateView(SourceFile:2261)
E/WindowManager(27897):         at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1419)
E/WindowManager(27897):         at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(SourceFile:1750)
E/WindowManager(27897):         at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1819)
E/WindowManager(27897):         at android.support.v4.app.BackStackRecord.executeOps(SourceFile:797)
E/WindowManager(27897):         at android.support.v4.app.FragmentManagerImpl.executeOps(SourceFile:2590)
E/WindowManager(27897):         at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(SourceFile:2377)
E/WindowManager(27897):         at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(SourceFile:2332)
E/WindowManager(27897):         at android.support.v4.app.FragmentManagerImpl.execSingleAction(SourceFile:2209)
E/WindowManager(27897):         at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(SourceFile:649)
E/WindowManager(27897):         at android.support.v4.app.FragmentPagerAdapter.finishUpdate(SourceFile:145)
E/WindowManager(27897):         at android.support.v4.view.ViewPager.a(SourceFile:1238)
E/WindowManager(27897):         at android.support.v4.view.ViewPager.c(SourceFile:1086)
E/WindowManager(27897):         at android.support.v4.view.ViewPager.onMeasure(SourceFile:1616)
E/WindowManager(27897):         at android.view.View.measure(View.java:18849)
E/WindowManager(27897):         at android.widget.LinearLayout.measureVertical(LinearLayout.java:874)
E/WindowManager(27897):         at android.widget.LinearLayout.onMeasure(LinearLayout.java:612)
E/WindowManager(27897):         at android.view.View.measure(View.java:18849)
E/WindowManager(27897):         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5904)
E/WindowManager(27897):         at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
E/WindowManager(27897):         at android.view.View.measure(View.java:18849)
E/WindowManager(27897):         at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
E/WindowManager(27897):         at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:464)
E/WindowManager(27897):         at android.view.View.measure(View.java:18849)
E/WindowManager(27897):         at android.support.v4.widget.DrawerLayout.onMeasure(SourceFile:1060)
E/WindowManager(27897):         at android.view.View.measure(View.java:18849)
E/WindowManager(27897):         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5904)
E/WindowManager(27897):         at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
E/WindowManager(27897):         at android.widget.LinearLayout.measureVertical(LinearLayout.java:721)
E/WindowManager(27897):         at android.widget.LinearLayout.onMeasure(LinearLayout.java:612)
E/WindowManager(27897):         at android.view.View.measure(View.java:18849)
E/WindowManager(27897):         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5904)
E/WindowManager(27897):         at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
E/WindowManager(27897):         at android.support.v7.widget.ContentFrameLayout.onMeasure(SourceFile:139)
E/WindowManager(27897):         at android.view.View.measure(View.java:18849)
E/WindowManager(27897):         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5904)
E/WindowManager(27897):         at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
E/WindowManager(27897):         at android.widget.LinearLayout.measureVertical(LinearLayout.java:721)
E/WindowManager(27897):         at android.widget.LinearLayout.onMeasure(LinearLayout.java:612)
E/WindowManager(27897):         at android.view.View.measure(View.java:18849)
E/WindowManager(27897):         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5904)
E/WindowManager(27897):         at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
E/WindowManager(27897):         at android.view.View.measure(View.java:18849)
E/WindowManager(27897):         at android.view.ViewGroup.measureChildWithMargins(ViewG
D/WindowManager( 3501): beginLayoutLw mStatusBar.isVisibleLw() = true, statusBarTransient=false, displayId=0
W/WindowManager( 3501): Failed looking up window
W/WindowManager( 3501): java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@386c5721 does not exist
W/WindowManager( 3501):         at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:13345)
W/WindowManager( 3501):         at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:13336)
W/WindowManager( 3501):         at com.android.server.wm.WindowManagerService.removeWindow(WindowManagerService.java:4147)
W/WindowManager( 3501):         at com.android.server.wm.Session.remove(Session.java:195)
W/WindowManager( 3501):         at android.view.IWindowSession$Stub.onTransact(IWindowSession.java:233)
W/WindowManager( 3501):         at com.android.server.wm.Session.onTransact(Session.java:138)
W/WindowManager( 3501):         at android.os.Binder.execTransact(Binder.java:461)
```

**Comment by lamquangthanh** [comment]
@mykola-mokhnach  i try to investigate again this issues, you see log appium below, appium connect with 0 devices, but after that it connected with 1 devices (BOLD in log)


[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\android-sdk_r24.4.1-windows\android-sdk-windows\platfo                                    rm-tools\adb.exe -P 5037 -s 33002b29a5b462e1 shell cat /proc/net/unix'
[debug] [AndroidDriver] WEBVIEW_21291 mapped to pid 21291
[debug] [AndroidDriver] Getting process name for webview
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'D:\android-sdk_r24.4.1-windows\android-sdk-windows\platfo                                    rm-tools\adb.exe -P 5037 -s 33002b29a5b462e1 shell ps'
[debug] [UiAutomator2] [UIAutomator2]
[debug] [UiAutomator2] [UIAutomator2] io.appium.uiautomator2.server.test.AppiumU                                    iAutomator2Server:
[Logcat] Logcat terminated with code 0, signal null
[debug] [AndroidDriver] Returning process name: 'unknown'
[debug] [AndroidDriver] Found webviews: ["WEBVIEW_unknown"]
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_unknown"]
[debug] [W3C] Responding to client with driver.setContext() result: null
[HTTP] <-- POST /wd/hub/session/ac5ee5be-b281-49c2-bd5a-4248c31bc774/context 200                                     239 ms - 76
[HTTP]
[HTTP] --> POST /wd/hub/session/ac5ee5be-b281-49c2-bd5a-4248c31bc774/elements
[HTTP] {"using":"id","value":"com.accor.appli.hybrid:id/mailField"}
[debug] [W3C] Calling AppiumDriver.findElements() with args: ["id","com.accor.ap                                    pli.hybrid:id/mailField","ac5ee5be-b281-49c2-bd5a-4248c31bc774"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class                                     name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8200/                                    wd/hub/session/f61a7a93-9369-4b3f-9a91-ba292c433b2e/elements] with body: {"strat                                    egy":"id","selector":"com.accor.appli.hybrid:id/mailField","context":"","multipl                                    e":true}
[HTTP] <-- POST /wd/hub/session/ac5ee5be-b281-49c2-bd5a-4248c31bc774/elements 40                                    0 1028 ms - 1106
[HTTP]
[HTTP] --> GET /wd/hub/session/ac5ee5be-b281-49c2-bd5a-4248c31bc774/context
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.getCurrentContext() with args: ["ac5ee5be-b28                                    1-49c2-bd5a-4248c31bc774"]
[debug] [W3C] Responding to client with driver.getCurrentContext() result: "NATI                                    VE_APP"
[HTTP] <-- GET /wd/hub/session/ac5ee5be-b281-49c2-bd5a-4248c31bc774/context 200                                     2 ms - 84
[HTTP]
[HTTP] --> GET /wd/hub/session/ac5ee5be-b281-49c2-bd5a-4248c31bc774/contexts
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.getContexts() with args: ["ac5ee5be-b281-49c2                                    -bd5a-4248c31bc774"]
[debug] [AndroidDriver] Getting a list of available webviews
[debug] [ADB] Getting connected devices...
**[debug] [ADB] 0 device(s) connected**
[W3C] Encountered internal error running command: Error: No device connected, ca                                    nnot run adb shell command 'cat /proc/net/unix'
[W3C]     at ADB.callee$0$0$ (C:\Users\Ekino\AppData\Roaming\npm\node_modules\ap                                    pium\node_modules\appium-adb\lib\tools\system-calls.js:337:11)
[W3C]     at tryCatch (C:\Users\Ekino\AppData\Roaming\npm\node_modules\appium\no                                    de_modules\babel-runtime\regenerator\runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Ekino\AppD                                    ata\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runti                                    me.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next]                                     (C:\Users\Ekino\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runt                                    ime\regenerator\runtime.js:100:21)
[W3C]     at GeneratorFunctionPrototype.invoke (C:\Users\Ekino\AppData\Roaming\n                                    pm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[HTTP] <-- GET /wd/hub/session/ac5ee5be-b281-49c2-bd5a-4248c31bc774/contexts 500                                     39 ms - 1392
[HTTP]
[HTTP] --> DELETE /wd/hub/session/ac5ee5be-b281-49c2-bd5a-4248c31bc774
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.deleteSession() with args: ["ac5ee5be-b281-49                                    c2-bd5a-4248c31bc774"]
[debug] [BaseDriver] Event 'quitSessionRequested' logged at 1527581077016 (15:04                                    :37 GMT+0700 (SE Asia Standard Time))
[Appium] Removing session ac5ee5be-b281-49c2-bd5a-4248c31bc774 from our master s                                    ession list
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[debug] [JSONWP Proxy] Proxying [DELETE /] to [DELETE http://localhost:8200/wd/h                                    ub/session/f61a7a93-9369-4b3f-9a91-ba292c433b2e] with no body
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error                                     was: ProxyRequestError: Could not proxy command to remote server. Original erro                                    r: Error: connect ECONNREFUSED 127.0.0.1:8200
[debug] [ADB] Getting connected devices...
**[debug] [ADB] 1 device(s) connected**
[debug] [ADB] Running 'D:\android-sdk_r24.4.1-windows\android-sdk-windows\platfo                                    rm-tools\adb.exe -P 5037 -s 33002b29a5b462e1 shell am force-stop com.accor.appli                                    .hybrid'
[debug] [Logcat] Stopping logcat capture
[debug] [Logcat] Logcat already stopped
[debug] [ADB] Removing forwarded port socket connection: 8200
[debug] [ADB] Running 'D:\android-sdk_r24.4.1-windows\android-sdk-windows\platfo                                    rm-tools\adb.exe -P 5037 -s 33002b29a5b462e1 forward --remove tcp\:8200'
[debug] [ADB] Running 'D:\android-sdk_r24.4.1-windows\android-sdk-windows\platfo                                    rm-tools\adb.exe -P 5037 -s 33002b29a5b462e1 forward --remove tcp\:8200'
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original                                     error: 'Command 'D\:\\android-sdk_r24.4.1-windows\\android-sdk-windows\\platform                                    -tools\\adb.exe -P 5037 -s 33002b29a5b462e1 forward --remove tcp\:8200' exited w                                    ith code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''
[debug] [BaseDriver] Event 'quitSessionFinished' logged at 1527581078877 (15:04:                                    38 GMT+0700 (SE Asia Standard Time))
[debug] [W3C] Received response: null
[debug] [W3C] But deleting session, so not returning
[debug] [W3C] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/ac5ee5be-b281-49c2-bd5a-4248c31bc774 200 1862                                     ms - 76
[HTTP]

**Comment by mykola-mokhnach** [comment]
It might be there's some ADB glitch. Make sure the android tools are up to date and try appium@beta. There the verification of connected devices count has been removed.

**Comment by lamquangthanh** [comment]
@mykola-mokhnach i will try with beta version. This issue is NOT happen in Android 7.0 (Nexus 6)

**Comment by lamquangthanh** [comment]
@mykola-mokhnach  the same issue on beta version

**Comment by mykola-mokhnach** [comment]
Can you attach the updated log?

**Comment by lamquangthanh** [comment]
[new log .txt](https://github.com/appium/appium/files/2047764/new.log.txt)
@mykola-mokhnach please check it.

**Comment by mykola-mokhnach** [comment]
I think it is a problem with the adb/device itself. There is nothing on Appium side that can be done here.
