### ISSUE TITLE
Appium Server Clear Command Prompt / Console

### ISSUE THREAD

**Issue by pbmzbr** [appium/appium#10765]
## The Question

Hello!

Every single test I run I need close and open Appium Server to "clear" the console. Has some command to clear this console after a test finished?

## Environment

* Appium version (or git revision) that exhibits the issue: Appium Server v1.8.0
* Appium Driver version: Appium Driver v4.0.30319
* Last Appium version that did not exhibit the issue (if applicable): Same
* Desktop OS/version used to run Appium: Windows 10 Pro
* Node.js version (unless using Appium.app|exe): Node.js v10.1.0
* Mobile platform/version under test: Android 8.0
* Real device or emulator/simulator: Real device Samsung S9

## Details

If necessary, describe the problem you have been experiencing in more detail.

I'm using Visual Studio Community 2017 and C# 

![inext_008](https://user-images.githubusercontent.com/11395681/40610867-ef5655f2-626b-11e8-9ed6-a17bd9e98471.png)

**Comment by mykola-mokhnach** [comment]
There is no server API available to do such things. However, you could create an enhancement request to https://github.com/appium/appium-desktop
