### ISSUE TITLE
Appium inspector for ios is not showing the elements eventhough the session is active

### ISSUE THREAD

**Issue by arjungovindgv** [appium/appium#10760]
![image](https://user-images.githubusercontent.com/39362405/40600897-ae3ec8ec-6270-11e8-9730-ec11e93b51b9.png)

**Comment by mykola-mokhnach** [comment]
Can you properly describe the issue and attach the server log?

**Comment by arjungovindgv** [comment]
[appium-server-logs.txt](https://github.com/appium/appium/files/2044598/appium-server-logs.txt)
Once I Started the appium inspector to locate elements, it is coming like this. If I killed the application and on restarting its working fine all the elements are accessible. If I stopped the server and on resuming(not quitting the application), and on opening the inspector it's coming like this.

**Comment by mykola-mokhnach** [comment]
The attached log does not contain any explicit errors.

>  If I stopped the server and on resuming(not quitting the application), and on opening the inspector it's coming like this.

**Comment by arjungovindgv** [comment]
But how it will be relating the server log. I am getting error in appium inspector as cant locate any element even I did not get any explicit errors.
