### ISSUE TITLE
Child elements are not returned once the accessibility label is enabled for parent element

### ISSUE THREAD

**Issue by wrathtodd** [appium/appium#10778]
## The problem

Child elements are not found/returned once the accessibility label is enabled for parent element

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 
* Node.js version (unless using Appium.app|exe): v8.9.2
* Mobile platform/version under test: 11.3.1
* Real device or emulator/simulator: iPhone 8
* Appium CLI or Appium.app|exe:

## Details

In our app there is a viewcontroller with some custom views as cells. Inside those cells there are several simple labels. So the hierarchy can be presented as follows 
....
```
> XCUIElementTypeCell
>>  XCUIElementTypeOther
>>>  XCUIElementTypeStaticText
>>>   XCUIElementTypeStaticText
>>>   XCUIElementTypeStaticText
>>  XCUIElementTypeOther
>>>  XCUIElementTypeStaticText
>>>   XCUIElementTypeStaticText
>>>   XCUIElementTypeStaticText
```

In Appium 1.8.0 i noticed, that when the XCUIElementTypeOther element (parent to XCUIElementTypeStaticText elements) has no accessibility label, then child XCUIElementTypeStaticText elements are found and returned after $driver.source , but if I specify the accessibility element for the parent XCUIElementTypeOther, then only the XCUIElementTypeOther elements are returned (with new label value), while children XCUIElementTypeStaticText can't be found anymore. 

I checked it several times with breakpoints, the accessibilitylabel values are present for those children in XCode, so it looks like Appium just either doesn't see them, or it has some limit in depth of querying for the source.

Does anyone know how to solve this problem?

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/facebook/WebDriverAgent/issues (but I still think it's an XCTest related). Closed as not an issue.
