### ISSUE TITLE
GetPlatform API not working for Android

### ISSUE THREAD

**Issue by VinnieM** [appium/appium#10776]
## The problem
The API appiumDriver.getCapabilities().getPlatform().is(Platform.ANDROID)) is returning false even if the Phone is Android.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Mac OS, 10.13.4
* Node.js version (unless using Appium.app|exe): 8.11.1
* Mobile platform/version under test: Android, Samsung Note8, 7.1.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

##Details##
I have set the capabilities properly. I have added the following properties

DEVICE_NAME, UDID, ACCEPT_SSL_CERTS, AUTO_WEBVIEW, NEW_COMMAND_TIMEOUT, APPIUM_VERSION, FULL_RESET, NO_RESET, PLATFORM_NAME, AUTO_GRANT_PERMISSIONS, APP_PACKAGE and APP_ACTIVITY

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/appium/java-client
