### ISSUE TITLE
Encountered internal error running command: TypeError: Cannot read property 'startConsole' of undefined

### ISSUE THREAD

**Issue by yangyang50** [appium/appium#10770]
## The problem

When I test with a real Iphone,I follow the steps below, an error occurs。Could you do me a favor,How to achieve this function.thanks。

1.[start inspector session]
2.[adesired capabilities]
{
  "deviceName": "iphone 6 Plus",
  "platformVersion": "11.3.1",
  "platformName": "iOS",
  "app": "/Users/yangyang50/Desktop/work/JDMEIphone_4.6.0.ipa",
  "udid": "ae881a9d1a264c582ee9286c043480160fe1f892",
  "autoLaunch": false,
  "automationName": "XCUITest"
}
3.[start session]

the following is the error:

[HTTP] <-- POST /wd/hub/session 200 13713 ms - 528
[HTTP] 
[HTTP] --> POST /wd/hub/session/df657f4c-c9f8-48a0-87c8-d050c2450cae/context
[HTTP] {"name":"NATIVE_APP"}
[MJSONWP] Calling AppiumDriver.setContext() with args: ["NATIVE_APP","df657f4c-c9f8-48a0-87c8-d050c2450cae"]
[XCUITest] Executing command 'setContext'
[iOS] Attempting to set context to 'NATIVE_APP'
[MJSONWP] Encountered internal error running command: TypeError: Cannot read property 'startConsole' of undefined
[MJSONWP]     at XCUITestDriver.callee$0$0$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/commands/context.js:20:23)
[MJSONWP]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP]     at 
[MJSONWP]     at process._tickCallback (internal/process/next_tick.js:188:7)
[HTTP] <-- POST /wd/hub/session/df657f4c-c9f8-48a0-87c8-d050c2450cae/context 500 6 ms - 219
[HTTP] 
[HTTP] --> GET /wd/hub/session/df657f4c-c9f8-48a0-87c8-d050c2450cae/source
[HTTP] {}
[MJSONWP] Calling AppiumDriver.getPageSource() with args: ["df657f4c-c9f8-48a0-87c8-d050c2450cae"]
[XCUITest] Executing command 'getPageSource'
[JSONWP Proxy] Proxying [GET /source] to [GET http://localhost:8100/session/DC2B5F15-D230-4303-9FB7-06E6217CF2DE/source] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"\\n\\n  \\n    \\n      \\n        \\n      <\\/XCUIElementTypeOther>\\n    <\\/XCUIElementTypeOther>\\...
[MJSONWP] Responding to client with driver.getPageSource() result: "\n  \n    \n      \n        \n      \n    \n    \n  \n  
[HTTP] <-- GET /wd/hub/session/df657f4c-c9f8-48a0-87c8-d050c2450cae/source 200 61247 ms - 18322
[HTTP] 

## Environment

Appium desktop v1.6.1(appium 1.8.0)
mac 10.13.4
iphone 11.3.1

**Comment by mykola-mokhnach** [comment]
This issue has been addressed in appium@beta

**Comment by yangyang50** [comment]
Now using the 1.8.1 version, this problem no longer appears, thank you very much

**Comment by BShivShankar** [comment]
I'm also getting the same issue 

[XCUITest] Executing command 'setContext'
[iOS] Attempting to set context to 'NATIVE_APP'
[MJSONWP] Encountered internal error running command: TypeError: Cannot read property 'startConsole' of undefined
[MJSONWP]     at XCUITestDriver.callee$0$0$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/commands/context.js:20:23)
[MJSONWP]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP]     at 
[MJSONWP]     at process._tickCallback (internal/process/next_tick.js:188:7)
[HTTP] <-- POST /wd/hub/session/f94eeade-6ba0-4d01-b58f-e2fae0c89fdc/context 500 4 ms - 219

Appium Version 1.6.1 (1.6.1)
iPhone 8 - version 11.3
Mac os High sierra-  version  10.13.3
