### ISSUE TITLE
We are facing socket hang up in Appium 1.8.1 version abruptly on Android Device

### ISSUE THREAD

**Issue by QA2Dev** [appium/appium#10777]
## The problem
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up (WARNING: The server did not provide any stacktrace information)

In the same 1.8.1 version we were not facing issue till yesterday, abruptly today we were facing this issue.

as a part of debug, when I  commented Automation Name Capability( which is UIAutomator 2) then we were not facing this issue in Appium 1.8.1 (today itself tried)

## Environment

Appium version (or git revision) that exhibits the issue: **1.8.1 (Not working from 29th May)**
Last Appium version that did not exhibit the issue (if applicable):**1.8.1(Worked until 28th May started using from 25th May)**
Desktop OS/version used to run Appium: **MAC 10.13.1**
Node.js version (unless using Appium.app|exe): **7.9.0**
Mobile platform/version under test: **Android 7.0 and Android 6.0**
Real device or emulator/simulator: **Real device**
Appium CLI or Appium.app|exe: **CLI**

## Details

[Appium]   deviceType: tablet
[Appium]   app: /Users/e001844/Desktop/App_v0.3.8.apk
[Appium]   app-package: com.ego.dpt.connect
[Appium]   version: 
[Appium]   deviceName: SamsungTabA_6.0.1_Local
[Appium]   platform: ANDROID
[Appium]   androidInstallTimeout: 150000
[Appium]   newCommandTimeout: 150000
[Appium]   platformVersion: 6.0.1
[Appium]   automationName: uiautomator2
[Appium]   browserName: android
[Appium]   autoGrantPermissions: true
[Appium]   platformName: Android

**Comment by mykola-mokhnach** [comment]
We cannot help without having both Appium server and logcat output
