### ISSUE TITLE
AppiumFieldDecorator doesn’t work with appium server 1.8.0 

### ISSUE THREAD

**Issue by dancyzheng** [appium/appium#10771]
## The problem

I use AppiumFieldDecorator to do lazy loading on elements. It works fine when appium server is 1.7.2. But when upgrade to appium server 1.8.0, the method doesn’t work. The server doesn’t receive implicit wait request, such as below (I can see this request when appium server is 1.7.2)
[HTTP] --> POST /wd/hub/session/54fff602-7a76-4173-9c54-8dd48e4257ef/timeouts{“type”:“implicit”,“ms”:20000}

## Environment

Appium 1.8
MAC OS 10.13.4
XCODe 9.3
IOS 11.3

## Link to Appium logs
https://gist.github.com/dancyzheng/404ab973c49b76095bef0f7331364f48

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/appium/java-client.
Also make sure you use the most recent version of it.
