### ISSUE TITLE
Error: '11.3' does not exist in the list of simctl SDKs. Only the following Simulator SDK versions are available on your system: 11.4

### ISSUE THREAD

**Issue by hieutrandn9889** [appium/appium#10789]
## The problem
I have just update xcode from 9.3 => 9.4 then run appium for project 
There is an error when running it

## Link to Appium logs
[Appium] Creating new XCUITestDriver (v2.76.2) session
[Appium] Capabilities:
[Appium]   app: /Users/hieutran/Desktop/Web_Mobi_Maven_Java_POM/../Web_Mobi_Maven_Java_POM/App/IntegrationApp.app
[Appium]   appiumVersion: 1.8.0
[Appium]   automationName: XCuiTest
[Appium]   browserName: 
[Appium]   deviceName: iPhone 7
[Appium]   launchTimeout: 5000000
[Appium]   platformName: iOS
[Appium]   platformVersion: 11.3
[Appium]   wdaLocalPort: 8100
[debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {"app":"/Users/hieutran/Des...
[BaseDriver] Capability 'wdaLocalPort' changed from string ('8100') to integer (8100). This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by appium: appiumVersion.
[BaseDriver] Session created with session id: 3411ca29-04a8-4b95-b305-cc9ac0a3f014
[debug] [XCUITest] Current user: 'hieutran'
[debug] [XCUITest] Xcode version set to '9.4' (tools v9.4.0.0.1.1526532315)
[debug] [XCUITest] iOS SDK Version set to '11.4'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1527767142102 (18:45:42 GMT+0700 (+07))
[XCUITest] Error: '11.3' does not exist in the list of simctl SDKs. Only the following Simulator SDK versions are available on your system: 11.4
[XCUITest]     at getDevices$ (/usr/local/lib/node_modules/appium/node_modules/node-simctl/lib/simctl.js:547:13)
[XCUITest]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[XCUITest]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[XCUITest]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[XCUITest]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest]     at <anonymous>
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1527767142303 (18:45:42 GMT+0700 (+07))
[W3C] Encountered internal error running command: Error: '11.3' does not exist in the list of simctl SDKs. Only the following Simulator SDK versions are available on your system: 11.4
[W3C]     at getDevices$ (/usr/local/lib/node_modules/appium/node_modules/node-simctl/lib/simctl.js:547:13)
[W3C]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[W3C]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[W3C]     at <anonymous>
[HTTP] <-- POST /wd/hub/session 500 368 ms - 1336
[HTTP]

**Comment by dpgraham** [comment]
You need to change the platformVersion capability to 11.4 in your desired caps.

**Comment by imurchie** [comment]
Or download the 11.3 SDK in XCode.

**Comment by hieutrandn9889** [comment]
OK thanks. I fixed it
