### ISSUE TITLE
 Getting -->Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65"

### ISSUE THREAD

**Issue by ManjuAsthuthe** [appium/appium#10782]
I'm trying to launch an ios app on real device but it's throwing me above error . App is installed successfully but its not launching .

Please find the below appium logs for more details ..

[Appium] Welcome to Appium v1.7.2
[Appium] Non-default server args:
[Appium] address: 127.0.0.1
[Appium] port: 11270
[Appium] Appium REST http interface listener started on 127.0.0.1:11270
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.7.2","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 12 ms - 72
Suite started
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/manjunath.r/MMP/app/R-Delivery.ipa","noReset":true,"clearSystemFiles":true,"xcodeOrgId":"98X3AWT99G","autoDismissAlerts":true,"deviceName":"iphone 6","xcodeSigningId":"iPhone Developer","showXcodeLog":true,"newCommandTimeout":"7200","platformVersion":"11.2.6","automationName":"XCUITest","autoGrantPermissions":true,"udid":"2cfbb1c6eb861ed4c714cf17ba61f88ba826451f","platformName":"iOS","autoAcceptAlerts":true},"requiredCapabilities":{},"capabilities":{"desiredCapabilities":{"app":"/Users/manjunath.r/MMP/app/R-Delivery.ipa","noReset":true,"clearSystemFiles":true,"xcodeOrgId":"98X3AWT99G","autoDismissAlerts":true,"deviceName":"iphone 6","xcodeSigningId":"iPhone Developer","showXcodeLog":true,"newCommandTimeout":"7200","platformVersion":"11.2.6","automationName":"XCUITest","autoGrantPermissions":true,"udid":"2cfbb1c6eb861ed4c714cf17ba61f88ba826451f","platformName":"iOS","autoAcceptAlerts":true},"requiredCapabilities":{},"alwaysMatch":{"platformName":"iO
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/manjunath.r/MMP/app/R-Delivery.ipa","noReset":true,"clearSystemFiles":true,"xcodeOrgId":"98X3AWT99G","autoDismissAlerts":true,"deviceName":"iphone 6","xcodeSigningId":"iPhone Developer","showXcodeLog":true,"newCommandTimeout":"7200","platformVersion":"11.2.6","automationName":"XCUITest","autoGrantPermissions":true,"udid":"2cfbb1c6eb861ed4c714cf17ba61f88ba826451f","platformName":"iOS","autoAcceptAlerts":true},{},{"desiredCapabilities":{"app":"/Users/manjunath.r/MMP/app/R-Delivery.ipa","noReset":true,"clearSystemFiles":true,"xcodeOrgId":"98X3AWT99G","autoDismissAlerts":true,"deviceName":"iphone 6","xcodeSigningId":"iPhone Developer","showXcodeLog":true,"newCommandTimeout":"7200","platformVersion":"11.2.6","automationName":"XCUITest","autoGrantPermissions":true,"udid":"2cfbb1c6eb861ed4c714cf17ba61f88ba826451f","platformName":"iOS","autoAcceptAlerts":true},"requiredCapabilities":{},"alwaysMatch":{"platformName":"iOS"},"firstMatch":[]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1527673529461 (15:15:29 GMT+0530 (IST))
[Appium] Merged W3C capabilities {"desiredCapabilities":{"app":"/Users/manjunath... into desiredCapabilities object {"app":"/Users/manjunath.r/MMP/app/R-Delivery.i...
[Appium] Creating new XCUITestDriver (v2.64.0) session
[Appium] Capabilities:
[Appium] app: /Users/manjunath.r/MMP/app/R-Delivery.ipa
[Appium] noReset: true
[Appium] clearSystemFiles: true
[Appium] xcodeOrgId: 98X3AWT99G
[Appium] autoDismissAlerts: true
[Appium] deviceName: iphone 6
[Appium] xcodeSigningId: iPhone Developer
[Appium] showXcodeLog: true
[Appium] newCommandTimeout: 7200
[Appium] platformVersion: 11.2.6
[Appium] automationName: XCUITest
[Appium] autoGrantPermissions: true
[Appium] udid: 2cfbb1c6eb861ed4c714cf17ba61f88ba826451f
[Appium] platformName: iOS
[Appium] autoAcceptAlerts: true
[BaseDriver] Capability 'newCommandTimeout' changed from string ('7200') to integer (7200). This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by appium: autoGrantPermissions.
[XCUITest] The capabilities 'autoAcceptAlerts' and 'autoDismissAlerts' do not work for XCUITest-based tests. Please adjust your alert handling accordingly.
[BaseDriver] Session created with session id: 19bbba06-ea0b-41c9-8a8e-adc9bb6bdd3b
[debug] [XCUITest] Current user: 'manjunath.r'
[debug] [XCUITest] Current version of libimobiledevice: stable 1.2.0 (bottled), HEAD
[debug] [XCUITest] Xcode version set to '9.2' (tools v9.0.0.0.1.1504363082)
[debug] [XCUITest] iOS SDK Version set to '11.2'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1527673530701 (15:15:30 GMT+0530 (IST))
[debug] [XCUITest] Available devices: 2cfbb1c6eb861ed4c714cf17ba61f88ba826451f
[debug] [XCUITest] Creating iDevice object with udid '2cfbb1c6eb861ed4c714cf17ba61f88ba826451f'
[XCUITest] Determining device to run tests on: udid: '2cfbb1c6eb861ed4c714cf17ba61f88ba826451f', real device: true
[BaseDriver] Using local app '/Users/manjunath.r/MMP/app/R-Delivery.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[BaseDriver] Unzipping local app '/var/folders/hn/h_4n0nb52h1g3y9c6z4gs5fm2p18km/T/2018430-16764-8v0ek3.ukmf8/appium-app.zip'...
[debug] [BaseDriver] Unzipping /var/folders/hn/h_4n0nb52h1g3y9c6z4gs5fm2p18km/T/2018430-16764-8v0ek3.ukmf8/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/hn/h_4n0nb52h1g3y9c6z4gs5fm2p18km/T/2018430-16764-8v0ek3.ukmf8/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/hn/h_4n0nb52h1g3y9c6z4gs5fm2p18km/T/2018430-16764-8v0ek3.ukmf8/Payload/Andromeda.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1527673531658 (15:15:31 GMT+0530 (IST))
[debug] [XCUITest] Checking whether app '/var/folders/hn/h_4n0nb52h1g3y9c6z4gs5fm2p18km/T/2018430-16764-8v0ek3.ukmf8/Payload/Andromeda.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [iOS] Getting bundle ID from app '/var/folders/hn/h_4n0nb52h1g3y9c6z4gs5fm2p18km/T/2018430-16764-8v0ek3.ukmf8/Payload/Andromeda.app': 'jp.co.rakuten.Delivery.ent'
[debug] [BaseDriver] Event 'resetStarted' logged at 1527673531660 (15:15:31 GMT+0530 (IST))
[debug] [XCUITest] Reset: fullReset not set. Leaving as is
[debug] [BaseDriver] Event 'resetComplete' logged at 1527673531660 (15:15:31 GMT+0530 (IST))
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Starting iOS device log capture with: 'idevicesyslog'
[debug] [XCUITest] Crash reports root '/Users/manjunath.r/Library/Logs/CrashReporter/MobileDevice/iPhone 6' does not exist. Got nothing to gather.
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1527673531881 (15:15:31 GMT+0530 (IST))
[XCUITest] Setting up real device
[debug] [XCUITest] App 'jp.co.rakuten.Delivery.ent' is already installed. No need to reinstall.
[debug] [BaseDriver] Event 'appInstalled' logged at 1527673532077 (15:15:32 GMT+0530 (IST))
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[debug] [XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] WDA is not listening at 'http://localhost:8100/'
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1527673532133 (15:15:32 GMT+0530 (IST))
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing running processes 'xcodebuild.*2cfbb1c6eb861ed4c714cf17ba61f88ba826451f, iproxy 8100' for the device 2cfbb1c6eb861ed4c714cf17ba61f88ba826451f...
[debug] [XCUITest] 'pgrep -nif xcodebuild.*2cfbb1c6eb861ed4c714cf17ba61f88ba826451f' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] 'pgrep -nif iproxy 8100' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [XCUITest] Using Xcode 9.2, so fixing WDA codebase
[debug] [XCUITest] Generating xcode config file for orgId '98X3AWT99G' and signingId 'iPhone Developer'
[debug] [XCUITest] Writing xcode config file to /var/folders/hn/h_4n0nb52h1g3y9c6z4gs5fm2p18km/T/2018430-16764-165t0hq.nz18/appium-temp.xcconfig
[debug] [XCUITest] Using Xcode configuration file: '/var/folders/hn/h_4n0nb52h1g3y9c6z4gs5fm2p18km/T/2018430-16764-165t0hq.nz18/appium-temp.xcconfig'
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=2cfbb1c6eb861ed4c714cf17ba61f88ba826451f IPHONEOS_DEPLOYMENT_TARGET=11.2 -xcconfig /var/folders/hn/h_4n0nb52h1g3y9c6z4gs5fm2p18km/T/2018430-16764-165t0hq.nz18/appium-temp.xcconfig' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will be logged. To see xcode logging, use 'showXcodeLog' desired capability
[Xcode] Build settings from command line:
[Xcode]
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] IPHONEOS_DEPLOYMENT_TARGET = 11.2
[Xcode]
[Xcode] Build settings from configuration file '/var/folders/hn/h_4n0nb52h1g3y9c6z4gs5fm2p18km/T/2018430-16764-165t0hq.nz18/appium-temp.xcconfig':
[Xcode] CODE_SIGN_IDENTITY = iPhone Developer
[Xcode] DEVELOPMENT_TEAM = 98X3AWT99G
[Xcode]
[Xcode]
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] 2018-05-30 15:15:43.758 xcodebuild[17071:6255622] DTDeviceKit: deviceType from 2cfbb1c6eb861ed4c714cf17ba61f88ba826451f was NULL
[Xcode]
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] === BUILD TARGET WebDriverAgentLib OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===
[Xcode]
[Xcode]
[Xcode] Check dependencies
[Xcode]
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] Code Signing Error: No signing certificate "iOS Development" found: No "iOS Development" signing certificate matching team ID "98X3AWT99G" with a private key was found.
[Xcode]
[Xcode]
[Xcode]
[Xcode] 2018-05-30 15:15:44.969 xcodebuild[17071:6255623] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder “WebDriverAgentRunner_iphoneos11.2-arm64.xctestrun” doesn’t exist." UserInfo={NSFilePath=/Users/manjunath.r/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/WebDriverAgentRunner_iphoneos11.2-arm64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7fef13b75a70 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode]
[Xcode] 2018-05-30 15:15:44.970 xcodebuild[17071:6255623] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder “WebDriverAgentRunner_iphoneos11.2-arm64.xctestrun” doesn’t exist." UserInfo={NSFilePath=/Users/manjunath.r/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/WebDriverAgentRunner_iphoneos11.2-arm64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7fef135ce170 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode]
[Xcode] ** TEST BUILD FAILED **
[Xcode]
[Xcode]
[Xcode]
[Xcode] The following build commands failed:
[Xcode] Check dependencies
[Xcode] (1 failure)
[Xcode]
[debug] [XCUITest] Log file for xcodebuild test: /var/folders/hn/h_4n0nb52h1g3y9c6z4gs5fm2p18km/T/com.apple.dt.XCTest/IDETestRunSession-D8AAC574-72F4-41E0-9669-5DDFCAB0CF62/WebDriverAgentRunner-F7A923CF-FE12-40D7-9CE3-3734F164D018/Session-WebDriverAgentRunner-2018-05-30_151545-JigQ1l.log
[Xcode] 2018-05-30 15:15:45.021 xcodebuild[17071:6255623] IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
[Xcode] /var/folders/hn/h_4n0nb52h1g3y9c6z4gs5fm2p18km/T/com.apple.dt.XCTest/IDETestRunSession-D8AAC574-72F4-41E0-9669-5DDFCAB0CF62/WebDriverAgentRunner-F7A923CF-FE12-40D7-9CE3-3734F164D018/Session-WebDriverAgentRunner-2018-05-30_151545-JigQ1l.log
[Xcode]
[Xcode] 2018-05-30 15:15:45.025 xcodebuild[17071:6255520] [MT] IDETestOperationsObserverDebug: (C7B200DF-1ACC-4928-B82F-DE43A2B01FA3) Beginning test session WebDriverAgentRunner-C7B200DF-1ACC-4928-B82F-DE43A2B01FA3 at 2018-05-30 15:15:45.023 with Xcode 9C40b on target <DVTiOSDevice: 0x7fef13adb3a0> {
[Xcode] deviceSerialNumber: FFMSX0XCG5MN
[Xcode] identifier: 2cfbb1c6eb861ed4c714cf17ba61f88ba826451f
[Xcode] deviceClass: iPhone
[Xcode] deviceName: iPhone 6
[Xcode] deviceIdentifier: 2cfbb1c6eb861ed4c714cf17ba61f88ba826451f
[Xcode] productVersion: 11.2.6
[Xcode] buildVersion: 15D100
[Xcode] deviceSoftwareVersion: 11.2.6 (15D100)
[Xcode] deviceArchitecture: arm64
[Xcode] deviceTotalCapacity: 12596109312
[Xcode] deviceAvailableCapacity: 9390186496
[Xcode] deviceIsTransient: NO
[Xcode] ignored: NO
[Xcode] deviceIsBusy: NO
[Xcode] deviceIsActivated: YES
[Xcode] deviceActivationState: Activated
[Xcode] isPasscodeLocked: NO
[Xcode] deviceType: <DVTDeviceType:0x7fef136b99b0 Xcode.DeviceType.iPhone>
[Xcode] supportedDeviceFamilies: (
[Xcode] 1
[Xcode] )
[Xcode] applications: (null)
[Xcode] provisioningProfiles: (null)
[Xcode] hasInternalSupport: NO
[Xcode] isSupportedOS: YES
[Xcode] developerDiskMountError: (null)
[Xcode] (null)
[Xcode] bootArgs: 
[Xcode] connected: yes
[Xcode] isWirelessEnabled: no
[Xcode] connectionType: direct
[Xcode] } (11.2.6 (15D100))
[Xcode]
[Xcode] 2018-05-30 15:15:45.070 xcodebuild[17071:6255520] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/manjunath.r/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fef13ccd960 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode]
[Xcode] 2018-05-30 15:15:45.070 xcodebuild[17071:6255520] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode]
[Xcode] ** TEST EXECUTE FAILED **
[Xcode]
[Xcode]
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[Xcode] Contents of xcodebuild log file '/var/folders/hn/h_4n0nb52h1g3y9c6z4gs5fm2p18km/T/com.apple.dt.XCTest/IDETestRunSession-D8AAC574-72F4-41E0-9669-5DDFCAB0CF62/WebDriverAgentRunner-F7A923CF-FE12-40D7-9CE3-3734F164D018/Session-WebDriverAgentRunner-2018-05-30_151545-JigQ1l.log':
[Xcode] 15:15:45.025 xcodebuild[17071:6255520] Beginning test session WebDriverAgentRunner-C7B200DF-1ACC-4928-B82F-DE43A2B01FA3 at 2018-05-30 15:15:45.023 with Xcode 9C40b on target <DVTiOSDevice: 0x7fef13adb3a0> {
[Xcode] deviceSerialNumber: FFMSX0XCG5MN
[Xcode] identifier: 2cfbb1c6eb861ed4c714cf17ba61f88ba826451f
[Xcode] deviceClass: iPhone
[Xcode] deviceName: iPhone 6
[Xcode] deviceIdentifier: 2cfbb1c6eb861ed4c714cf17ba61f88ba826451f
[Xcode] productVersion: 11.2.6
[Xcode] buildVersion: 15D100
[Xcode] deviceSoftwareVersion: 11.2.6 (15D100)
[Xcode] deviceArchitecture: arm64
[Xcode] deviceTotalCapacity: 12596109312
[Xcode] deviceAvailableCapacity: 9390186496
[Xcode] deviceIsTransient: NO
[Xcode] ignored: NO
[Xcode] deviceIsBusy: NO
[Xcode] deviceIsActivated: YES
[Xcode] deviceActivationState: Activated
[Xcode] isPasscodeLocked: NO
[Xcode] deviceType: <DVTDeviceType:0x7fef136b99b0 Xcode.DeviceType.iPhone>
[Xcode] supportedDeviceFamilies: (
[Xcode] 1
[Xcode] )
[Xcode] applications: (null)
[Xcode] provisioningProfiles: (null)
[Xcode] hasInternalSupport: NO
[Xcode] isSupportedOS: YES
[Xcode] developerDiskMountError: (null)
[Xcode] (null)
[Xcode] bootArgs: 
[Xcode] connected: yes
[Xcode] isWirelessEnabled: no
[Xcode] connectionType: direct
[Xcode] } (11.2.6 (15D100))
[Xcode] 15:15:45.026 xcodebuild[17071:6255520] /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild
[Xcode] build-for-testing
[Xcode] test-without-building
[Xcode] -project
[Xcode] /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj
[Xcode] -scheme
[Xcode] WebDriverAgentRunner
[Xcode] -destination
[Xcode] id=2cfbb1c6eb861ed4c714cf17ba61f88ba826451f
[Xcode] IPHONEOS_DEPLOYMENT_TARGET=11.2
[Xcode] -xcconfig
[Xcode] /var/folders/hn/h_4n0nb52h1g3y9c6z4gs5fm2p18km/T/2018430-16764-165t0hq.nz18/appium-temp.xcconfig
[Xcode] 15:15:45.026 xcodebuild[17071:6255520] Launching with Xcode.IDEFoundation.Launcher.PosixSpawn
[Xcode] 15:15:45.030 xcodebuild[17071:6255520] Test standard output and standard error is at /var/folders/hn/h_4n0nb52h1g3y9c6z4gs5fm2p18km/T/com.apple.dt.XCTest/IDETestRunSession-D8AAC574-72F4-41E0-9669-5DDFCAB0CF62/WebDriverAgentRunner-F7A923CF-FE12-40D7-9CE3-3734F164D018/StandardOutputAndStandardError.txt
[Xcode] 15:15:45.043 xcodebuild[17071:6255520] Setting up test runner session
[Xcode] 15:15:45.051 xcodebuild[17071:6255520] Launch session started.
[Xcode] 15:15:45.051 xcodebuild[17071:6255931] Connecting to mobile device: 2cfbb1c6eb861ed4c714cf17ba61f88ba826451f
[Xcode] 15:15:45.056 xcodebuild[17071:6255931] Starting session with mobile device
[Xcode] 15:15:45.061 xcodebuild[17071:6255520] Test operation failure: Launch session expired before checking in.
[Xcode] 15:15:45.061 xcodebuild[17071:6255520] _finishWithError:Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Launch session expired before checking in." UserInfo={NSLocalizedDescription=Launch session expired before checking in.}
[Xcode]
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1527673545129 (15:15:45 GMT+0530 (IST))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 17006)
[debug] [XCUITest] iproxy exited with code 'null'
[debug] [XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
at XCUITestDriver.quitAndUninstall$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:375:13)
at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js💯21)
at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
at 
Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
at XCUITestDriver.quitAndUninstall$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:375:13)
at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js💯21)
at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
at 
[debug] [XCUITest] 'pgrep -nif xcodebuild.*2cfbb1c6eb861ed4c714cf17ba61f88ba826451f' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] Cannot find xcodebuild's process id, so unable to retrieve DerivedData folder path
[XCUITest] No WebDriverAgent derived data available, so unable to clear system files
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
at XCUITestDriver.quitAndUninstall$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:375:13)
at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js💯21)
at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
at 
[HTTP] <-- POST /wd/hub/session 500 15899 ms - 470
FAILED CONFIGURATION: @beforemethod beforeTest
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 15.97 seconds

**Comment by mykola-mokhnach** [comment]
> [debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.

Closed as duplicate

**Comment by ManjuAsthuthe** [comment]
Hi mykola 
please dont close the issue like that , you have done the same thing for my previous issue also..
thought the issue seems to duplicate but actually its not.

i have gone through the above link and done all the configuration settings.

please help me in resolving this

**Comment by mykola-mokhnach** [comment]
I can leave it opened if it makes you happy. However, it is still a configuration issue on your side and is not an issue of the appium server, so I consider this feed is not the appropriate place for such report.

**Comment by kamikrazeguy** [comment]
mykola is correct that the issue that you are facing is indeed a configuration issue on your side. Have you tried opening webdriveragent project in xcode and trying to resolve the issues there? It'll shed some light into what you may be experiencing!

**Comment by ManjuAsthuthe** [comment]
Ok Fine ..
Once again i'll check from my side on that configuration part ,, 
Thanks for replying
