### ISSUE TITLE
WDA/iProxy don't respond: Connection to WDA timed out / recv failed: Operation not permitted 

### ISSUE THREAD

**Issue by hananguyen123** [appium/appium#10781]
## The problem
I start appium server and then start inspector session with "IntegrationApp" from app: /Users/my user name/Desktop/IntegrationApp.app

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Appium desktop: 1.6.1
* Desktop OS/version used to run Appium: MacOS High Sierra 10.13.3
* Node.js version (unless using Appium.app|exe): 10.2.1
* Mobile platform/version under test: Real device
* Real device or emulator/simulator:  iPhone 6Plus 10.0.1
* Appium CLI or Appium.app|exe: Appium.app

## Details
I got error:
[XCUITest] Connection to WDA timed out
[iProxy] recv failed: Operation not permitted

Some error from above:
[MJSONWP] Encountered internal error running command: TypeError: Cannot read property 'startConsole' of undefined
[MJSONWP]     at XCUITestDriver.callee$0$0$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/commands/context.js:20:23)
[MJSONWP]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP]     at 
[MJSONWP]     at process._tickCallback (internal/process/next_tick.js:188:7)

## Appium logs here:
[appium-server-logs.txt](https://github.com/appium/appium/files/2052909/appium-server-logs.txt)

<img width="1398" alt="screen shot 2018-05-30 at 14 27 14" src="https://user-images.githubusercontent.com/18109222/40706998-98083edc-6419-11e8-835a-6a20919d7b39.png">

**Comment by mykola-mokhnach** [comment]
This issue has been fixed in appium@beta. closed as duplicate

**Comment by hananguyen123** [comment]
@mykola-mokhnach 
how can I install appium@beta by "brew"?
I downloaded latest version of appium desktop V1.6.1 from http://appium.io/
and installed appium by npm install -g appium.
appium -v --> V1.8.1
so which appium@beta is?

**Comment by mykola-mokhnach** [comment]
https://www.google.com/search?q=install+appium+beta

Is gentleman blocked on Google?
