### ISSUE TITLE
Socket Hangup error when i use Swipe/Touch Action methods[Appium iOS simulator running through Webdriver agent]

### ISSUE THREAD

**Issue by varun2810** [appium/appium#10786]
## The problem

I'm using appium latest version. And i'm running automation in iOS simulator 11.1. Everything works fine but when i use swipe/Touch action methods . It is stopping showing Socket hang up error.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): It works well in android.Previously i haven't used appium for iOS automation 
* Desktop OS/version used to run Appium : Desktop version 1.5.0
* Node.js version (unless using Appium.app|exe): 9.11.3
* Mobile platform/version under test: iOS 11.1
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium.app

## Details

i cleared the webdriver agent and i'm installing fresh wda in every run. When i use driver. swipe methods / Touch action methods. It shows the error as socket hang up. Could not proxy error.

I have also seen the issue referred in #7063 & #10579 , but still i'm facing that issue.

Kindly please help me out. i cant able to proceed further in this. How to swipe the screen in latest appium with Webdriver agent.

## Link to Appium logs

https://gist.github.com/varun2810/210c177e33b073fb65faae2c09f1933e

## Code To Reproduce Issue [ Good To Have ]
[Code sample 1 - using touch action]
#1 MobileElement el = driver.findElement(By.xpath("//XCUIElementTypeButton[@name=\"imageBtn\"]"));
						TouchAction actions = new TouchAction(driver);
						actions.press(el).waitAction(3000).moveTo(588, 147).release().perform();

[Code sample 2 -- using driver.swipe method]
#2  size = driver.manage().window().getSize();
						  System.out.println(size);
						   
						  //Find swipe start and end point from screen's with and height.
						  //Find starty point which is at bottom side of screen.
						  int starty = (int) (size.height * 0.80);
						  //Find endy point which is at top side of screen.
						  int endy = (int) (size.height * 0.20);
						  //Find horizontal point where you wants to swipe. It is in middle of screen width.
						  int startx = size.width / 2;
						  System.out.println("starty = " + starty + " ,endy = " + endy + " , startx = " + startx);

						  //Swipe from Top to Bottom.
						  driver.swipe(startx, endy, startx, starty, 3000);
						  Thread.sleep(2000)

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by vjmaiky** [comment]
First i would try something like this:

new TouchAction<>(driver).longPress((LongPressOptions)driver.findElement(By.xpath(""))).waitAction(WaitOptions.waitOptions(Duration.ofMillis(500))).moveTo(PointOption.point(x, y)).release().perform();

If it's still not working i suggest you to try also the methods from: 
http://appium.io/docs/en/writing-running-appium/ios/ios-xctest-mobile-gestures/

Also see what appium java library do you use and what is available in it.

**Comment by mykola-mokhnach** [comment]
Update appium to 1.8.1

**Comment by varun2810** [comment]
Thanks , It works after updating to appium 1.8.1 .:) @mykola-mokhnach

**Comment by vytran9599** [comment]
@mykola-mokhnach Hi, I am having the same issue. However, I am testing a web app on iOS simulator and is using mobile gestures such as: self.driver.execute_script('mobile: tap', {'x': '100', 'y': '500'}. It is saying error socket hang up.
