### ISSUE TITLE
Appium 1.7.2 - Finding element is very slow with ios native app hosted in azure

### ISSUE THREAD

**Issue by githubdilip** [appium/appium#10783]
## The problem
I am using appium 1.7.2 with iOS native app in real device. FindElement is taking very long time with native app hosted in Azure. Earlier my app is hosted in AWS and the findelement took lesser time compared to now. Is there any known issue in findelement with Azure. Kindly help

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable):1.7.2
* Desktop OS/version used to run Appium:10.13
* Node.js version (unless using Appium.app|exe):Appium.app
* Mobile platform/version under test:11.2.5
* Real device or emulator/simulator:Real Device
* Appium CLI or Appium.app|exe:Appium.app

**Comment by mykola-mokhnach** [comment]
Use the most recent Appium version (which is currently 1.8.1)

Please ask question on Appium forum.
