### ISSUE TITLE
Appium MoveTo() rejects negative coordinates 

### ISSUE THREAD

**Issue by lbaker9** [appium/appium#10791]
## The problem

I am trying to move an element up and down. When I move the element up, I use these relative coordinates (0, .5) Even though I am telling it to move up just 0.5 of a coordinate, Appium moves my element by a much greater amount than this. Ideally, I would like my element to move about 50 coordinates but any positive y coordinate moves the element to the highest bounds of its parent element. 

The bigger issue comes when I move my element down. If I use any negative number as my y coordinate, Appium tells me that the element is not in the correct range. The reason is because Appium is trying to move my element to a negative number, even though it is supposed to be working relatively (it is saying y is -956 for some reason, instead of subtracting 0.5 from the current coordinate like I would expect). I would be happy if Appium could move my element relative to it's location or to absolute coordinates. Unfortunately, right now it will not do either. It appears that older versions of appium move the element to absolute coordinates, so I may try switching to an older version.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.8.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Microsoft Windows 10 Pro
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android 5.0
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium.exe

## Code To Reproduce Issue [ Good To Have ]

IWebElement element = _driver.FindElement(By.XPath("//android.widget.Button[@NAF='true']"));
            _driver.PerformTouchAction(new TouchAction(_driver).Press(element).Wait(500).MoveTo(0, .5).Wait(5000).Release());
       _driver.PerformTouchAction(new TouchAction(_driver).Press(element).Wait(500).MoveTo(0, -.5).Wait(5000).Release());

**Comment by mykola-mokhnach** [comment]
moveTo coordinates are absolute since Appium 1.8.0

**Comment by mykola-mokhnach** [comment]
Also, do you use UIAutomator2?
