### ISSUE TITLE
Can't tap on pop-up window buttons after upgrade to Xcode 9.3.1

### ISSUE THREAD

**Issue by gergm** [appium/appium#10798]
## The problem

Can't tap on a button in a pop-up window in iOS app built with Xcode 9.3.1. This worked fine when the app was built with Xcode 9.2

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0 and 1.8.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 10.13.4
* Node.js version (unless using Appium.app|exe): 10.2.1
* Mobile platform/version under test: iOS 11.3
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium Desktop 1.6.1

## Details

Appium locates the pop-up screen buttons at incorrect positions on the screen. See the screenshot which shows Appium's identification of the "Reminders" button. Note that the y coordinate is way off.
![screen shot 2018-06-04 at 12 12 08 pm](https://user-images.githubusercontent.com/38676591/40895983-b6a496a8-67f5-11e8-845c-5b7ceb96d131.png)

My interpretation of the appium log file is that the coordinates returned `driver.getLocation() result: {"x":9,"y":145}` are actually relative to the pop-up window and appium is interpreting them as being relative to the entire screen.

Note that I have written a small XCUITest in Swift that can accurately tap the "Reminders" button after identifying it via id, ie this line of Swift works OK:
`app.collectionViews.collectionViews.buttons["Reminders"].tap()`

## Link to Appium logs

https://gist.github.com/gergm/8a1b1e92567ea7648a2281b9b5a4592b

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Apple has changed hitpoint detection since Xcode 9.3. And the frame returned by Xcode for elements inside remote views is not absolute, but relative. That is why the click happens somewhere outside the actual control.

We have recently updated hitpoint detection in https://github.com/appium/appium-xcuitest-driver/commit/a939edca3d9b79620df5611d17dbb7cf8c9ca6a8 and this will be published in appium@beta soon.
