### ISSUE TITLE
uiautomatorviewer - incorrect UI XML snapshot

### ISSUE THREAD

**Issue by AlexsanderSagaydak** [appium/appium#10794]
## The problem

Hello, I've downloaded the SDK for try to the uiautomationviewer.bat. It is works fine with native apps like 'calculator': 
![screen2](https://user-images.githubusercontent.com/8048739/40847014-cf44d7c4-65c3-11e8-9ebb-512c36f4ed09.png)

But, it shows incorrect position of elements in some games, viewer just loose focus or so, for example: 

![screen1](https://user-images.githubusercontent.com/8048739/40847048-edcbd422-65c3-11e8-8f12-0811c3711b6f.png)

## Environment

- OS - Windows 7 Pro / Android 7.0
- Real Device - Samsung A510F
- Java - 1.8.0_151
- Android Debug Bridge version - 1.0.39
- SDK version - 26.0.1
- uiautomatorviewer - 25.3.1
 

## Details

Later, I just install latest SDK  + Java1.8 on Win 8 (another workstation) and nothing changes. I tried to kill adb process, restart device and PC but fail. Also, I tried to get snapshot from other game and the same things - incorrect positions. There are no additional info in uiautomatorviewer logs.
It is quite strange because uiviewer works well with apps predefined by OS(clock, calc etc.)
Probably I miss something?  Thank you!

**Comment by mykola-mokhnach** [comment]
Appium has nothing to do with uiautomatorviewer tool. Please report the problem to Google.

**Comment by AlexsanderSagaydak** [comment]
Oh, I see. Sorry.
