### ISSUE TITLE
[BUG] [appium-xcuitest-driver] With 'webDriverAgentUrl' capability, recovering the session after error in command not correct

### ISSUE THREAD

**Issue by priyeshkpandey** [appium/appium#10792]
## The problem

When we use _'webDriverAgentUrl'_ to provide WDA urls and any error/exceptions happens the retry logic is not correct for this capability. 

Refer: https://github.com/appium/appium-xcuitest-driver/blob/master/lib/driver.js
In the **startWDA** method, there is a call to **quitAndUninstall** local helper after exceptions from the command. In the **retryInterval** call, there is a call to **this.wda.launch**. In WDA's launch method (Ref: https://github.com/appium/appium-xcuitest-driver/blob/master/lib/wda/webdriveragent.js) the assumption with _'webDriverAgentUrl'_ is that it is already running hence xcodebuild is not done again.

Now this creates problem because the **quitAndUninstall** method has already killed and uninstalled our instance of WDA but in retries it is never built and redeployed.

In my opinion, in case of _'webDriverAgentUrl'_ capability, there should be an informative exception thrown from **quitAndUninstall** method instead of quitting and uninstalling the WDA so that the client can handle that appropriately.

## Environment

* Appium version (or git revision) that exhibits the issue: master branch of appium-xcuitest-driver
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Mac OS High Sierra (10.13.2)
* Node.js version (unless using Appium.app|exe): 6.9.5
* Mobile platform/version under test: iOS (10.x, 11.x)
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium.app

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Here is the appium logs when this error happens:
https://gist.github.com/priyeshkpandey/6824f27ff0a07b11a0e86a6aafdc27ce

## Code To Reproduce Issue [ Good To Have ]

This issue doesn't happen all the time. Happens only when some exception or error occurs, hence giving code to reproduce will not necessarily reproduce the issue. I have observed this intermittently during our test suite runs, after which all other tests fail.

**Comment by mykola-mokhnach** [comment]
Thanks for the report @priyeshkpandey. Feel free to create a PR.

**Comment by priyeshkpandey** [comment]
Thanks @mykola-mokhnach for quick response. I will create the PR and update here.

**Comment by mykola-mokhnach** [comment]
Check my comment to https://github.com/appium/appium/issues/10749

**Comment by mykola-mokhnach** [comment]
Closed as fixed
