### ISSUE TITLE
unknown error: dialog has invalid 'type'

### ISSUE THREAD

**Issue by fanxiaowen** [appium/appium#10793]
## The problem
org.openqa.selenium.WebDriverException: unknown error: dialog has invalid 'type'
  (Session info: webview=33.0.0.0)
  (Driver info: chromedriver=2.38.552518 (183d19265345f54ce39cbb94cf81ba5f15905011),platform=Mac OS X 10.12.6 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 256 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'fanawen.local', ip: '172.18.118.22', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_144'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{appPackage=com.meituan.banma.starfire, deviceName=USWWLRNFEQJRMNCQ, platform=LINUX, deviceUDID=USWWLRNFEQJRMNCQ, desired={appPackage=com.meituan.banma.starfire, recreateChromeDriverSessions=True, noSign=true, deviceName=USWWLRNFEQJRMNCQ, appActivity=com.meituan.banma.starfire.settings.SettingsActivity, platformVersion=4.4.4, browserName=, sessionOverride=true, unicodeKeyboard=true, chromeOptions={args=[], extensions=[], androidProcess=com.meituan.banma.starfire}, platformName=Android, ignoreProtectedModeSettings=true, resetKeyboard=true}, platformVersion=4.4.4, webStorageEnabled=false, takesScreenshot=true, browserName=, javascriptEnabled=true, unicodeKeyboard=true, platformName=Android, deviceManufacturer=OPPO, resetKeyboard=true, deviceScreenSize=1080x1920, networkConnectionEnabled=true, recreateChromeDriverSessions=True, noSign=true, warnings={}, databaseEnabled=false, appActivity=com.meituan.banma.starfire.settings.SettingsActivity, locationContextEnabled=false, deviceModel=OPPO R7, sessionOverride=true, chromeOptions={args=[], extensions=[], androidProcess=com.meituan.banma.starfire}, ignoreProtectedModeSettings=true}]
Session ID: ac59a98b-d2fc-4cfb-bbca-4c6a7b895406

## Environment
android 4.4.4
appium 1.8.0
chromedriver 2.38
chrome 66

## Link to Appium logs
[AndroidDriver] A port was not given, using random port: 8000
[Chromedriver] Changed state to 'starting'
[Chromedriver] The following Chromedriver executables were found:
[Chromedriver]     /Applications/Appium 2.app/Contents/Resources/app/node_modules/appium-chromedriver/chromedriver/mac/chromedriver2.38 (minimum Chrome version 'Unknown')
[ADB] Getting package info for 'com.android.chrome'
[ADB] Getting connected devices...
[ADB] 2 device(s) connected
[ADB] Running '/usr/local/Caskroom/android-platform-tools/latest/sdk/platform-tools/adb -P 5037 -s USWWLRNFEQJRMNCQ shell dumpsys package com.android.chrome'
[Chromedriver] Unable to discover Chrome version. Using Chromedriver 2.38 at '/Applications/Appium 2.app/Contents/Resources/app/node_modules/appium-chromedriver/chromedriver/mac/chromedriver2.38'
[Chromedriver] Set chromedriver binary as: /Applications/Appium 2.app/Contents/Resources/app/node_modules/appium-chromedriver/chromedriver/mac/chromedriver2.38
[Chromedriver] Killing any old chromedrivers, running: pkill -15 -f "/Applications/Appium 2.app/Contents/Resources/app/node_modules/appium-chromedriver/chromedriver/mac/chromedriver2.38.*--port=8000"
[Chromedriver] No old chromedrivers seemed to exist
[Chromedriver] Cleaning any old adb forwarded port socket connections
[ADB] List forwarding ports
[ADB] Running '/usr/local/Caskroom/android-platform-tools/latest/sdk/platform-tools/adb -P 5037 -s USWWLRNFEQJRMNCQ forward --list'
[ADB] Removing forwarded port socket connection: 12458 
[ADB] Running '/usr/local/Caskroom/android-platform-tools/latest/sdk/platform-tools/adb -P 5037 -s USWWLRNFEQJRMNCQ forward --remove tcp\:12458'
[Chromedriver] Spawning chromedriver with: /Applications/Appium 2.app/Contents/Resources/app/node_modules/appium-chromedriver/chromedriver/mac/chromedriver2.38 --url-base=wd/hub --port=8000 --adb-port=5037 --verbose
[Chromedriver] Chromedriver version: '2.38.552518'
[JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Mac OS X\",\"version\":\"10.12.6\"}}}"
[JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.meituan.banma.starfire","androidUseRunningApp":true,"args":[],"extensions":[],"androidProcess":"com.meituan.banma.starfire","androidDeviceSerial":"USWWLRNFEQJRMNCQ"}}}
[Chromedriver] Webview version: 'Chrome/33.0.0.0'
[JSONWP Proxy] Got response with status 200: {"sessionId":"e7866e21edc4cdc25d609ceb58c8076d","status":0,"value":{"acceptInsecureCerts":false,"acceptSslCerts":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"browserName":"chrome","chrome":{"chromedriverVersion":"2.38.552518 (183d19265345f54ce39cbb94cf81ba5f15905011)"},"cssSelectorsEnabled":true,"databaseEnabled":false,"handlesAlerts":true,"hasTouchScreen":false,"javascriptEnabled":true,"locationContextEnabled":true,"mobileEmulationEnabled":false,"nativeEvents":true,"pageLoadStrategy":"normal","platform":"ANDROID","rotatable":false,"setWindowRect":false,"takesHeapSnapshot":true,"takesScreenshot":true,"unexpectedAlertBehaviour":"","version":"33.0.0.0","webStorageEnabled":true}}
[Chromedriver] Changed state to 'online'
[MJSONWP] Responding to client with driver.setContext() result: null
[HTTP] <-- POST /wd/hub/session/ac59a98b-d2fc-4cfb-bbca-4c6a7b895406/context 200 1506 ms - 76
[HTTP] 
[HTTP] --> POST /wd/hub/session/ac59a98b-d2fc-4cfb-bbca-4c6a7b895406/timeouts
[HTTP] {"type":"implicit","ms":10000}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [POST /wd/hub/session/ac59a98b-d2fc-4cfb-bbca-4c6a7b895406/timeouts] to [POST http://127.0.0.1:8000/wd/hub/session/e7866e21edc4cdc25d609ceb58c8076d/timeouts] with body: {"type":"implicit","ms":10000}
[JSONWP Proxy] Got response with status 200: {"sessionId":"e7866e21edc4cdc25d609ceb58c8076d","status":0,"value":null}
[JSONWP Proxy] Replacing sessionId e7866e21edc4cdc25d609ceb58c8076d with ac59a98b-d2fc-4cfb-bbca-4c6a7b895406
[HTTP] <-- POST /wd/hub/session/ac59a98b-d2fc-4cfb-bbca-4c6a7b895406/timeouts 200 4 ms - 76
[HTTP] 
[HTTP] --> GET /wd/hub/session/ac59a98b-d2fc-4cfb-bbca-4c6a7b895406/contexts
[HTTP] {}
[MJSONWP] Calling AppiumDriver.getContexts() with args: ["ac59a98b-d2fc-4cfb-bbca-4c6a7b895406"]
[AndroidDriver] Getting a list of available webviews
[ADB] Getting connected devices...
[ADB] 2 device(s) connected
[ADB] Running '/usr/local/Caskroom/android-platform-tools/latest/sdk/platform-tools/adb -P 5037 -s USWWLRNFEQJRMNCQ shell cat /proc/net/unix'
[AndroidDriver] WEBVIEW_928 mapped to pid 928
[AndroidDriver] Getting process name for webview
[ADB] Getting connected devices...
[ADB] 2 device(s) connected
[ADB] Running '/usr/local/Caskroom/android-platform-tools/latest/sdk/platform-tools/adb -P 5037 -s USWWLRNFEQJRMNCQ shell ps'
[AndroidDriver] Parsed pid: '928' pkg: 'com.meituan.banma.starfire' from
[AndroidDriver]     USER     PID   PPID  VSIZE  RSS     WCHAN    PC         NAME
[AndroidDriver]     u0_a407   928   245   1209448 171360 ffffffff 00000000 R com.meituan.banma.starfire
[AndroidDriver] Returning process name: 'com.meituan.banma.starfire'
[AndroidDriver] Found webviews: ["WEBVIEW_com.meituan.banma.starfire"]
[AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_com.meituan.banma.starfire"]
[MJSONWP] Responding to client with driver.getContexts() result: ["NATIVE_APP","WEBVIEW_com.meituan.banma.starfire"]
[HTTP] <-- GET /wd/hub/session/ac59a98b-d2fc-4cfb-bbca-4c6a7b895406/contexts 200 110 ms - 123
[HTTP] 
[HTTP] --> POST /wd/hub/session/ac59a98b-d2fc-4cfb-bbca-4c6a7b895406/context
[HTTP] {"name":"WEBVIEW_com.meituan.banma.starfire"}
[MJSONWP] Calling AppiumDriver.setContext() with args: ["WEBVIEW_com.meituan.banma.starfire","ac59a98b-d2fc-4cfb-bbca-4c6a7b895406"]
[AndroidDriver] Getting a list of available webviews
[ADB] Getting connected devices...
[ADB] 2 device(s) connected
[ADB] Running '/usr/local/Caskroom/android-platform-tools/latest/sdk/platform-tools/adb -P 5037 -s USWWLRNFEQJRMNCQ shell cat /proc/net/unix'
[AndroidDriver] WEBVIEW_928 mapped to pid 928
[AndroidDriver] Getting process name for webview
[ADB] Getting connected devices...
[ADB] 2 device(s) connected
[ADB] Running '/usr/local/Caskroom/android-platform-tools/latest/sdk/platform-tools/adb -P 5037 -s USWWLRNFEQJRMNCQ shell ps'
[AndroidDriver] Parsed pid: '928' pkg: 'com.meituan.banma.starfire' from
[AndroidDriver]     USER     PID   PPID  VSIZE  RSS     WCHAN    PC         NAME
[AndroidDriver]     u0_a407   928   245   1209336 168856 ffffffff 00000000 R com.meituan.banma.starfire
[AndroidDriver] Returning process name: 'com.meituan.banma.starfire'
[AndroidDriver] Found webviews: ["WEBVIEW_com.meituan.banma.starfire"]
[AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_com.meituan.banma.starfire"]
[MJSONWP] Responding to client with driver.setContext() result: null
[HTTP] <-- POST /wd/hub/session/ac59a98b-d2fc-4cfb-bbca-4c6a7b895406/context 200 130 ms - 76
[HTTP] 
[HTTP] --> POST /wd/hub/session/ac59a98b-d2fc-4cfb-bbca-4c6a7b895406/element
[HTTP] {"using":"id","value":"comment"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [POST /wd/hub/session/ac59a98b-d2fc-4cfb-bbca-4c6a7b895406/element] to [POST http://127.0.0.1:8000/wd/hub/session/e7866e21edc4cdc25d609ceb58c8076d/element] with body: {"using":"id","value":"comment"}
[JSONWP Proxy] Got response with status 200: {"sessionId":"e7866e21edc4cdc25d609ceb58c8076d","status":0,"value":{"ELEMENT":"0.5399505093228072-13"}}
[JSONWP Proxy] Replacing sessionId e7866e21edc4cdc25d609ceb58c8076d with ac59a98b-d2fc-4cfb-bbca-4c6a7b895406
[HTTP] <-- POST /wd/hub/session/ac59a98b-d2fc-4cfb-bbca-4c6a7b895406/element 200 234 ms - 107
[HTTP] 
[HTTP] --> POST /wd/hub/session/ac59a98b-d2fc-4cfb-bbca-4c6a7b895406/element/0.5399505093228072-13/value
[HTTP] {"id":"0.5399505093228072-13","value":["自动化备注内容appium-android"]}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [POST /wd/hub/session/ac59a98b-d2fc-4cfb-bbca-4c6a7b895406/element/0.5399505093228072-13/value] to [POST http://127.0.0.1:8000/wd/hub/session/e7866e21edc4cdc25d609ceb58c8076d/element/0.5399505093228072-13/value] with body: {"id":"0.5399505093228072-13","value":["自动化备注内容appium-android"]}
[JSONWP Proxy] Got response with status 200: {"sessionId":"e7866e21edc4cdc25d609ceb58c8076d","status":0,"value":null}
[JSONWP Proxy] Replacing sessionId e7866e21edc4cdc25d609ceb58c8076d with ac59a98b-d2fc-4cfb-bbca-4c6a7b895406
[HTTP] <-- POST /wd/hub/session/ac59a98b-d2fc-4cfb-bbca-4c6a7b895406/element/0.5399505093228072-13/value 200 1029 ms - 76
[HTTP] 
[HTTP] --> POST /wd/hub/session/ac59a98b-d2fc-4cfb-bbca-4c6a7b895406/timeouts
[HTTP] {"type":"implicit","ms":10000}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [POST /wd/hub/session/ac59a98b-d2fc-4cfb-bbca-4c6a7b895406/timeouts] to [POST http://127.0.0.1:8000/wd/hub/session/e7866e21edc4cdc25d609ceb58c8076d/timeouts] with body: {"type":"implicit","ms":10000}
[JSONWP Proxy] Got response with status 200: {"sessionId":"e7866e21edc4cdc25d609ceb58c8076d","status":0,"value":null}
[JSONWP Proxy] Replacing sessionId e7866e21edc4cdc25d609ceb58c8076d with ac59a98b-d2fc-4cfb-bbca-4c6a7b895406
[HTTP] <-- POST /wd/hub/session/ac59a98b-d2fc-4cfb-bbca-4c6a7b895406/timeouts 200 3 ms - 76
[HTTP] 
[HTTP] --> POST /wd/hub/session/ac59a98b-d2fc-4cfb-bbca-4c6a7b895406/element
[HTTP] {"using":"id","value":"btn-submit"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [POST /wd/hub/session/ac59a98b-d2fc-4cfb-bbca-4c6a7b895406/element] to [POST http://127.0.0.1:8000/wd/hub/session/e7866e21edc4cdc25d609ceb58c8076d/element] with body: {"using":"id","value":"btn-submit"}
[JSONWP Proxy] Got response with status 200: {"sessionId":"e7866e21edc4cdc25d609ceb58c8076d","status":0,"value":{"ELEMENT":"0.5399505093228072-14"}}
[JSONWP Proxy] Replacing sessionId e7866e21edc4cdc25d609ceb58c8076d with ac59a98b-d2fc-4cfb-bbca-4c6a7b895406
[HTTP] <-- POST /wd/hub/session/ac59a98b-d2fc-4cfb-bbca-4c6a7b895406/element 200 82 ms - 107
[HTTP] 
[HTTP] --> POST /wd/hub/session/ac59a98b-d2fc-4cfb-bbca-4c6a7b895406/element/0.5399505093228072-14/click
[HTTP] {"id":"0.5399505093228072-14"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [POST /wd/hub/session/ac59a98b-d2fc-4cfb-bbca-4c6a7b895406/element/0.5399505093228072-14/click] to [POST http://127.0.0.1:8000/wd/hub/session/e7866e21edc4cdc25d609ceb58c8076d/element/0.5399505093228072-14/click] with body: {"id":"0.5399505093228072-14"}
[JSONWP Proxy] Got response with status 200: {"sessionId":"e7866e21edc4cdc25d609ceb58c8076d","status":13,"value":{"message":"unknown error: dialog has invalid 'type'\n  (Session info: webview=33.0.0.0)\n  (Driver info: chromedriver=2.38.552518 (183d19265345f54ce39cbb94cf81ba5f15905011),platform=Mac OS X 10.12.6 x86_64)"}}
[JSONWP Proxy] Replacing sessionId e7866e21edc4cdc25d609ceb58c8076d with ac59a98b-d2fc-4cfb-bbca-4c6a7b895406
[HTTP] <-- POST /wd/hub/session/ac59a98b-d2fc-4cfb-bbca-4c6a7b895406/element/0.5399505093228072-14/click 200 252 ms - 282
[HTTP] 
[HTTP] --> POST /wd/hub/session/ac59a98b-d2fc-4cfb-bbca-4c6a7b895406/element
[HTTP] {"using":"id","value":"menuSign"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [POST /wd/hub/session/ac59a98b-d2fc-4cfb-bbca-4c6a7b895406/element] to [POST http://127.0.0.1:8000/wd/hub/session/e7866e21edc4cdc25d609ceb58c8076d/element] with body: {"using":"id","value":"menuSign"}

**Comment by mykola-mokhnach** [comment]
This error is coming from chromedriver and has nothing to do with Appium itself.

Check https://chromium.googlesource.com/chromium/src/+/lkcr/chrome/test/chromedriver/chrome/javascript_dialog_manager.cc for more details.
