### ISSUE TITLE
Xcode 10-beta support

### ISSUE THREAD

**Issue by mykola-mokhnach** [appium/appium#10808]
Good news - the recent WDA can be successfully compiled and can even run tests with Xcode10-beta1 without additional modifications. But there might be changes on Apple side, which need to be picked up in time.

**Comment by jamesvanhorn** [comment]
What the target device running iOS 11 or iOS 12 beta? Trying to plan ahead when everything is released

**Comment by Kitty2014** [comment]
@mykola-mokhnach did https://libraries.io/npm/appium update for support Xcode 10-beta?

**Comment by mcopjan** [comment]
XCode Version 10.0 beta 4 (10L213o)
Appium 1.8.2-beta
appium-xcuitest-driver@2.87.0

Anyone having this problem when trying to build the WDA?

Ld /Users/martinc/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentLib.framework/WebDriverAgentLib normal arm64 (in target: WebDriverAgentLib)
    cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
    export IPHONEOS_DEPLOYMENT_TARGET=12.0
    /Users/martinc/Downloads/Xcode-beta\ 2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -dynamiclib -isysroot /Users/martinc/Downloads/Xcode-beta\ 2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.0.sdk -L/Users/martinc/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos -F/Users/martinc/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos -F/Users/martinc/Downloads/Xcode-beta\ 2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks -F/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS -F/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/Mac -filelist /Users/martinc/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Intermediates.noindex/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/Objects-normal/arm64/WebDriverAgentLib.LinkFileList -install_name @rpath/WebDriverAgentLib.framework/WebDriverAgentLib -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -miphoneos-version-min=12.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/martinc/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Intermediates.noindex/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/Objects-normal/arm64/WebDriverAgentLib_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fobjc-arc -fobjc-link-runtime -lxml2 -framework RoutingHTTPServer -framework YYCache -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/martinc/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Intermediates.noindex/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/Objects-normal/arm64/WebDriverAgentLib_dependency_info.dat -o /Users/martinc/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentLib.framework/WebDriverAgentLib

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_XCElementSnapshot", referenced from:
      l_OBJC_$_CATEGORY_XCElementSnapshot_$_FBIsVisible in XCUIElement+FBIsVisible.o
      l_OBJC_$_CATEGORY_XCElementSnapshot_$_FBUID in XCUIElement+FBUID.o
      l_OBJC_$_CATEGORY_XCElementSnapshot_$_WebDriverAttributes in XCUIElement+FBWebDriverAttributes.o
      objc-class-ref in XCUIElement+FBWebDriverAttributes.o
      objc-class-ref in XCUIElement+FBUtilities.o
      l_OBJC_$_CATEGORY_XCElementSnapshot_$_FBAccessibility in XCUIElement+FBAccessibility.o
      l_OBJC_$_CATEGORY_XCElementSnapshot_$_FBScrolling in XCUIElement+FBScrolling.o
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by KazuCocoa** [comment]
https://github.com/facebook/WebDriverAgent/issues/968 for build failing by Xcode Version 10.0 beta 4 (10L213o)

**Comment by imurchie** [comment]
On the latest beta (Xcode 10 Beta 6) at least the following does not work:
* scrolling (see test: https://github.com/appium/appium-xcuitest-driver/blob/master/test/functional/basic/find-e2e-specs.js#L305-L311, logs: https://gist.github.com/imurchie/84bf9fb98b0ff22dfe6628eb4b11a598

This is with the `appium-xcuitest-driver` and https://github.com/appium/WebDriverAgent/commit/48e839bd138ca6d3b95956f7060ab8d2b296b815.
