### ISSUE TITLE
C# IsAppInstalled error: Could not find package 

### ISSUE THREAD

**Issue by pbmzbr** [appium/appium#10805]
## The problem

Hello.

I have a class in C#  to verify if my app is installed or not in my device.

When my device has the app installed, everything works fine. However, when my device does not have the app installed, the system gives me this error message:
"Message: Test method MYAPP.Main.RunTest.RunAllTests threw exception: 
System.InvalidOperationException: An unknown server-side error occurred while processing the command. Original error: Could not find package com.android.MyApp on the device"

How to use and declare the IsAppInstalled?

I’m using VS 2017 Community, C#, and a Samsung S9 (real device).

## Environment

* Appium version (or git revision) that exhibits the issue: Appium Driver v4.0.30319
* Last Appium version that did not exhibit the issue (if applicable): Same
* Desktop OS/version used to run Appium: Windows 10 Pro
* Node.js version (unless using Appium.app|exe): Node.js v10.1.0
* Mobile platform/version under test: Android 8.0
* Real device or emulator/simulator: Real device Samsung S9
* Appium CLI or Appium.app|exe: Appium Server v1.8.0

## Details

My Capabilities:
```csharp
public class CapDeviceConfig
    {

        public DesiredCapabilities CapDeviceConfigOptions()
        {
            //set the capabilities (https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md)
            
            DesiredCapabilities cap = new DesiredCapabilities();
            cap.SetCapability("automationName", "Appium"); // Which automation engine to use

            cap.SetCapability("platformName", "Android"); // Which mobile OS platform to use

            cap.SetCapability("platformVersion", "8.0.0"); // Mobile OS version

            cap.SetCapability("deviceName", "starlte"); // The kind of mobile device or emulator to use // S9

            cap.SetCapability("udid", "2270048324037ece"); // Unique device identifier of the connected physical device

            cap.SetCapability("appPackage", "com.android.MyApp");

            cap.SetCapability("appActivity", "md5ab6683a3e3c3f0bd6864e3305b4e45c6.SplashScreenActivity");
                        
            cap.SetCapability("noReset", "True"); // Don't reset app state before this session.

            cap.SetCapability("printPageSourceOnFindFailure", "True"); // When a find operation fails, print the current page source.

            return cap;

        }
    }
```

## Link to Appium logs

https://gist.github.com/pbmzbr/b0638a0237c7d846de2e94000163c1f6

## Code To Reproduce Issue [ Good To Have ]
```
public class AppInstallVerification
            {

                //Creating instance for Appium driver
                AppiumDriver<AndroidElement> driverCheck;

                CapDeviceConfig cap = new CapDeviceConfig();

                EnrollmentTests enrollmentTests = new EnrollmentTests();

                InstallApp install = new InstallApp();

                public void IsAppInstalled()
                {

                    cap.CapDeviceConfigOptions();
                    driverCheck = new AndroidDriver<AndroidElement>(new Uri("http://127.0.0.1:4723/wd/hub"), cap.CapDeviceConfigOptions());
                    
                    if (driverCheck.IsAppInstalled("com.android.MyApp"))
                    {
                        Console.WriteLine("App is installed!");
                        enrollmentTests.CodeApplied();
                    }
                    else
                    {
                        Console.WriteLine("App is not installed!");
                        install.InstallingApp();
                    }            
                }
            }`
```

**Comment by imurchie** [comment]
If the app is not installed, you need to provide the location of the application in order for Appium to install it, using the `"app"` capability.

**Comment by mykola-mokhnach** [comment]
You cannot check whether an app is installed before the driver is instantiated. and in order to instantiate the driver the application must be already set. For this particular case you could try to create a driver instance and handle the exception above in the client code if it fails.

**Comment by pbmzbr** [comment]
> If the app is not installed, you need to provide the location of the application in order for Appium to install it, using the "app" capability.

But how I do that if the intention of the method is verify if the app is installed?

**Comment by pbmzbr** [comment]
> You cannot check whether an app is installed before the driver is instantiated. and in order to instantiate the driver the application must be already set. For this particular case you could try to create a driver instance and handle the exception above in the client code if it fails.

How can I do that?

**Comment by pbmzbr** [comment]
Sorry for close and reopen the issue.

**Comment by mykola-mokhnach** [comment]
> How can I do that?

I don't know, I'm not familiar with C#. It's just an idea.

**Comment by pbmzbr** [comment]
> I don't know, I'm not familiar with C#. It's just an idea.

Do you know how to do this in Java?
I can adapt that.

**Comment by mykola-mokhnach** [comment]
Here's a pseudocode:

```
try {
  create_driver_instance_with_noreset()
}  catch {
  if (exception_message_says_the_app_is_not_found) {
     create_driver_instance_with_app_capability_set_to_application_path()
  }
}

```

**Comment by pbmzbr** [comment]
I tried install the app, but doesn't work.

` public class InstallApp
    {

        AppiumDriver<AndroidElement> instalDriver;

        CapDeviceConfig instalCap = new CapDeviceConfig();

        [TestMethod]
        public void InstallingApp()
        {

            Console.WriteLine("Installing the App");
            DesiredCapabilities instalCap = new DesiredCapabilities();
            instalCap.SetCapability("automationName", "Appium"); // Which automation engine to use

            instalCap.SetCapability("platformName", "Android"); // Which mobile OS platform to use

            instalCap.SetCapability("platformVersion", "8.0.0"); // Mobile OS version

            instalCap.SetCapability("deviceName", "starlte"); // The kind of mobile device or emulator to use // S9

            instalCap.SetCapability("udid", "2270048324037ece"); // Unique device identifier of the connected physical device

            instalCap.SetCapability("appPackage", "com.anroid.MyApp");

            instalCap.SetCapability("appActivity", "md5ab6683a3e3c3f0bd6864e3305b4e45c6.SplashScreenActivity");

            instalCap.SetCapability("noReset", "True"); // Don't reset app state before this session.

            instalCap.SetCapability("printPageSourceOnFindFailure", "True"); // When a find operation fails, print the current page source.

            Console.WriteLine("App installed");
            
            instalDriver.InstallApp("Phone/Download/MyApp.apk");


        }
    }
}`

**Error message:**

_Message: Test method MYAPP.Main.RunTest.RunAllTests threw exception: 
System.NullReferenceException: The object reference was not defined as an instance of an object._

**Comment by imurchie** [comment]
You haven't instantiated `instalDriver` when you try to run `InstallApp`.

What is your use case? What are you trying to do? In general, if you supply the `app`, Appium will leave the app alone on the device if it is already installed and there is no need to upgrade.

**Comment by imurchie** [comment]
Appium already handles the "if the app is not installed, install it" flow. You just need to specify an `app`.

Otherwise you can start a session with one app and then check about the app you actually care about. This seems silly, though.
