### ISSUE TITLE
Can't find element after update to any new version of Selenium

### ISSUE THREAD

**Issue by MioOgbeni** [appium/appium#10806]
## The problem

Hi, by now I have used Selenium version 3.11.0, but now I have decided to update and found out that from version 3.11.2 I can not find a single element, any attempts always end up with an error.

I also asked on Selenium GitHub https://github.com/SeleniumHQ/selenium/issues/5995.
## Environment

* AppiumWebDriver version that exhibits the issue: 3.0.0.2
* AppiumServer version that exhibits the issue: 1.8.0
* Selenium version that exhibits the issue: 3.11.2
* Last Selenium version that did not exhibit the issue (if applicable): 3.11.0
* Desktop OS/version used to run Appium: Windows 10 1803 17134.48
* Node.js version (unless using Appium.app|exe): .exe
* Mobile platform/version under test: Android 8 and 7
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: .exe

## Link to Appium logs

https://gist.github.com/MioOgbeni/c3f647a50e5dbd13ed94fefbecf39c18

## Code To Reproduce Issue [ Good To Have ]

`[FindsBy(How = How.XPath, Using = "//android.view.View[@index='0']/android.widget.TextView[@index='1']")]
  [FindsBy(How = How.XPath, Using = "//android.view.ViewGroup[@index='0']/android.widget.TextView[@index='1']")]
        private IWebElement SettingsLabel { get; set; }

public bool AmIOnSettingPage()
        {
            return SettingsLabel.Displayed && SettingsLabel.Text == Session.GetDisplayText(LocalizedStrings.Setting.Settings);
        }`

Error log from Visual Studio 

`[05.06.2018 16:18:27 Warning] SetUp failed for test fixture UITests.Android.PageObjectTests.ContractTests
[05.06.2018 16:18:27 Warning] System.InvalidOperationException : An element could not be located on the page using the given search parameters.
[05.06.2018 16:18:27 Warning]    v OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   v OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   v OpenQA.Selenium.Appium.AppiumDriver`1.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   v OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
   v OpenQA.Selenium.Remote.RemoteWebDriver.FindElementByXPath(String xpath)
   v OpenQA.Selenium.By.<>c__DisplayClass19_0.<XPath>b__0(ISearchContext context)
   v OpenQA.Selenium.By.FindElement(ISearchContext context)
   v OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(By by)
   v OpenQA.Selenium.Support.PageObjects.RetryingElementLocator.LocateElement(IEnumerable`1 bys)
   v OpenQA.Selenium.Support.PageObjects.WebElementProxy.get_Element()
   v OpenQA.Selenium.Support.PageObjects.WebElementProxy.Invoke(IMessage msg)
   v System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   v OpenQA.Selenium.IWebElement.get_Displayed()
   v UITests.Android.PageObjects.Settings.SettingPage.AmIOnSettingPage() v C:\Systemart\trunk\UITests.Android\PageObjects\Settings\SettingPage.cs:řádek 137
   v UITests.Android.PageObjects.Settings.SettingPage.FindRows() v C:\Systemart\trunk\UITests.Android\PageObjects\Settings\SettingPage.cs:řádek 20
   v Session.SetTimeFormat() v C:\Systemart\trunk\UITests.Android\Session.Extensions.cs:řádek 35
   v UITests.Android.PageObjectTests.TestBase.OneTimeSetUp() v C:\Systemart\trunk\UITests.Android\PageObjectTests\TestBase.cs:řádek 15
   v UITests.Android.PageObjectTests.ContractTests.OneTimeSetUp() v C:\Systemart\trunk\UITests.Android\PageObjectTests\ContractTests.cs:řádek 13`

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/appium/appium-dotnet-driver
