### ISSUE TITLE
iOS- Able to inspect element but not able to perform any action

### ISSUE THREAD

**Issue by CharanpreetHora** [appium/appium#10807]
## The problem

iOS- Able to inspect element but not able to perform any action

## Environment

* Appium version 1.7.1
* iOS 10/11
* Real device Any iphone

## Details

While inspecting top level view i.e Login view "Interactions are not available for this element".
But able to identify Username, DOB fields and Login button inside the view.

Spoken to developer and he has communicated that **"difference is to enable or not Accessibility for elements in that view. If I disable it it will work the scripts but it will have no sense because voice over will be disabled."** We have incorporated code for voice over with respect to ADA(for disabled persons) requirements. 
In normal build scripts are working fine. Not sure what to do now for iOS. For Android code is working fine with including these requirements.

Any help in this regard will be appreciated. I have gone through the following link as well. 
https://github.com/appium/appium/issues/9766

Thanks

**Comment by mykola-mokhnach** [comment]
Also, you can show [this thread](https://github.com/appium/appium/issues/6517) to developers regarding how to properly configure accessibility properties for element containers.

**Comment by CharanpreetHora** [comment]
Thanks mykola. I have installed Appium 1.8.0. Still same issue. But I sent the thread to developers lets see what response I will get.

**Comment by mykola-mokhnach** [comment]
Can you attach the full server log? It is not very clear what exactly the issue is

**Comment by CharanpreetHora** [comment]
I will attach logs shortly. Just a quick question I am wondering why scripts are working on ADA compliant builds for Android but not for iOS? Is it like developer has taken care of the standards to identify objects in case of ADA accessibility is enabled for Android but not for iOS? Am I correct or something else?

**Comment by Kitty2014** [comment]
try http://toolsqa.com/mobile-automation/appium/extract-xpath-from-app-using-macaca-inspector/

**Comment by mykola-mokhnach** [comment]
You must switch to web context in order to work with react context

**Comment by rcuyugan** [comment]
Switching context to web didn't work. Returns this error: **No such context found.** So frustrating. Been on this for days now and still cannot find the solution.

**Comment by mykola-mokhnach** [comment]
Did you follow web view setup procedure at http://appium.io/docs/en/writing-running-appium/web/hybrid/ ? Is the web view debuggable from Safari?

**Comment by rcuyugan** [comment]
Yes. This is a React Native app. It is debuggable and can be inspected with Chrome, React Native Debugger, and Accessibility inspector but not with the appium inspector.  I have not debugged with Safari yet. Also cannot inspect/access menu lists and modals, rather shows what is on the background and does not see the foreground when a menu list or modal pops up. So I am thinking if the appium inspector cannot locate or see the elements there is no way for this work or that XCUITest might be having some issues.

I found this issue online which was posted earlier this year and still no resolution. 

https://github.com/facebook/WebDriverAgent/issues/854

Appreciate any help or guidance!
