### ISSUE TITLE
StaleObjectException make appium response timeout after 600s

### ISSUE THREAD

**Issue by robin-xl** [appium/appium#10802]
## The problem

Running test on android real device with uiautomator2. The endpont "/location" request timeout when uiautomator2 server raise a StaleObjectException and response the stacktrace error, it looked like appium not handle the response correctly.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 10.13.5
* Node.js version (unless using Appium.app|exe): v8.11.2
* Mobile platform/version under test: android/7.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: none

## Details/steps

Call endpoint "/location" ,the uiautomator2 raise StaleObjectException,it take uiautomator server 2s to response, but the appium request not response until timeout (600s)

Hope appium request can response after uiautomator server response.

## Link to Appium logs

 [Appium log](https://gist.github.com/robin-xl/11e7c575b96debf0490461217af8c005)

 [uiautomator2 log](https://gist.github.com/robin-xl/8d5e2bd3bbb1a7f1ec56bc05e829f6db)

**Comment by mykola-mokhnach** [comment]
This should be fixed in 1.8.1

**Comment by robin-xl** [comment]
1.8.1 is ok, so close this issue
