### ISSUE TITLE
Unable to launch Expedia application

### ISSUE THREAD

**Issue by SapizonTechnologiesLLP** [appium/appium#10803]
I'm trying to launch Expedia application using appium but I'm unable to launch it.

* Appium version (or git revision) that exhibits the issue: Appium 1.8.1
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): Node.js 6.14.0
* Mobile platform/version under test: 8.0.0

Getting this Logs
Link:
https://gist.github.com/SapizonTechnologiesLLP/0a2b76c946586be05014eb68eb695611

Codes:
package com.sapizon.utility;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.annotations.BeforeTest;

import io.appium.java_client.MobileElement;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.remote.MobileCapabilityType;

public class Capablities {

	@BeforeTest

	public static AndroidDriver<MobileElement> setAndroidCapablities(AndroidDriver<MobileElement> driver)
			throws MalformedURLException {

		DesiredCapabilities cap = new DesiredCapabilities();
		cap.setCapability(MobileCapabilityType.DEVICE_NAME, "Samsung");
		cap.setCapability(MobileCapabilityType.NO_RESET, true);
		cap.setCapability("appPackage", "com.expedia.bookings");
		cap.setCapability("appActivity", "com.expedia.bookings.onboarding.activity.OnboardingActivity");
		cap.setCapability(MobileCapabilityType.AUTOMATION_NAME, "UiAutomator2");
		cap.setCapability("skipUnlock", true);
		driver = new AndroidDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"), cap);
		driver.manage().timeouts().implicitlyWait(50l, TimeUnit.SECONDS);
		return driver;
	}
}

**Comment by mykola-mokhnach** [comment]
> [35m[W3C][39m Encountered internal error running command: Error: Cannot start the 'com.expedia.bookings' application. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\DELL\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 5200759ab48925bf shell am start -W -n com.expedia.bookings/com.expedia.bookings.onboarding.activity.OnboardingActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' exited with code 4294967295'; Stderr: 'Security exception: Permission Denial: starting Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.expedia.bookings/.onboarding.activity.OnboardingActivity } from null (pid=12017, uid=2000) not exported from uid 10249

I assume the error message is pretty clear here. You must set the correct activity name or the activity name to wait for.
