### ISSUE TITLE
if statements are not working properly for Appium Java code

### ISSUE THREAD

**Issue by DeepakB01** [appium/appium#10801]
I have written a Java code with if statements and user would move from 'Screen1' to 'Screen2' through any of 4 alternate routes. Code is as follow:-

![applicationflow](https://user-images.githubusercontent.com/39115769/40969321-22f53798-68a7-11e8-9bef-b290b62f9751.png)

   

## Environment

* Appium version (or git revision) that exhibits the issue: - 1.4.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: - Windows 7 Professional
* Node.js version (unless using Appium.app|exe): - 8.11.1
* Mobile platform/version under test:- Android 7.0
* Real device or emulator/simulator: - Real device (Samsung S8)
* Appium CLI or Appium.app|exe:

## Details

I have also tried with while loop but after waiting for first loop the script fails if not appears. It doesn't look for 2nd condition

## Link to Appium logs

https://gist.github.com/DeepakB01/997460bd84fa10990bed0fb7c58e15e1

## Code To Reproduce Issue [ Good To Have ]

driver.findElement(By.id("----")).click(); //this click will take from  'screen1' to next screen.
 if(driver.findElement(By.xpath("//android.widget.TextView[@resource-id='com.abc.rbanking:id/text_logo'][text()='Security Question']")).isDisplayed())
    { //case when screen B is displayed Just after screen 1

    MobileElement mfaQ = driver.findElement(By.id("com.abc.rbanking:id/MfaQuestionText"));
    String question = mfaQ.getText();

    String lastword = question.replaceAll("^.*?(\\w+)\\W*$", "$1");

    System.out.println(lastword);

    MobileElement answer = driver.findElement(By.id("com.abc.rbanking:id/MfaAnswerTextBox"));

    answer.sendKeys(lastword);

    MobileElement checkbox = driver.findElement(By.id("com.abc.rbanking:id/ShowChallengeAnswerCheckbox"));
    checkbox.click();

    Thread.sleep(3000);

    MobileElement nextb = driver.findElement(By.id("com.abc.rbanking:id/PrimaryButton"));
    nextb.click();

    Thread.sleep(8000);
    }
         
 if(driver.findElement(By.id("com.abc.rbanking:id/WhatsNew")).isDisplayed())
    { //case if screen A is displayed just after screen 1
        MobileElement cross = driver.findElement(By.xpath("//*[@class = 'android.widget.ImageView']"));
        cross.click();

        Thread.sleep(3000);

    }
 driver.findElement(By.id("----")); //this is code for 'Screen 2'

Please help me. I am stuck with this issue. Your help is much appreciated.

**Comment by mykola-mokhnach** [comment]
I don't observe any issues in the attached Appium log. Please use Appium forum to ask questions
