### ISSUE TITLE
app set with apk file under test, but it not installed when a newer version already exits on my phone.

### ISSUE THREAD

**Issue by loveiset** [appium/appium#10816]
## The problem

app set with a apk file, but it's version is lower than the existing one on my phone, so it just ignored my app setting. so if I want to test app with different versions, it can't be done.

## Environment

* Appium version: 1.8.1
* Desktop OS/version used to run Appium: win7 SP1
* Node.js version: v8.11.0
* Mobile platform/version under test: android/6.0.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: `appium --session-override  --chromedriver-executable D:\hcs\Downloads\chromedriver_win32\chromedriver.exe`

## Details

appium just ignore the insall process.
```
[debug] [ADB] The installed 'com.crc.hrt' package does not require upgrade (429 > 426)
```

## Link to Appium logs

[logs](https://gist.github.com/loveiset/73fb6a8ddd35cd0705c36e16361f9f97)

**Comment by mykola-mokhnach** [comment]
Set `fullReset` to `true`, since it is mandatory to uninstall a newer app version before installing an older one.

This behaviour is by design
