### ISSUE TITLE
Duplicate webviews when loaded dynamically

### ISSUE THREAD

**Issue by Laywanger** [appium/appium#10813]
## The problem

I need to get the content desc of a webview loaded dynamically but I have two problems, first appium see two webviews and secondly appium don’t have the webview attributes.

When I create a webview in Android XML template file, there is no problem so it seems that is a bug with webviews loaded dynamically.

Do you have an idea ?

## Code

**App code :**

` final FrameLayout interstitial_container = (FrameLayout) findViewById(R.id.interstitial_container);
final WebView interstitial_web = new WebView(getApplicationContext());
interstitial_web.setLayoutParams(new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, 
LinearLayout.LayoutParams.MATCH_PARENT));
interstitial_web.loadUrl("http://example.com");
interstitial_web.setId(R.id.interstitial_webview);
interstitial_web.setContentDescription("breakfast");
interstitial_container.addView(interstitial_web, 0);`

**Get source - Appium method :**

` <android.widget.LinearLayout
                            index="2"
                            text=""
                            class="android.widget.LinearLayout"
                            package="com.evina.adsafetyfirstdemo"
                            content-desc=""
                            checkable="false"
                            checked="false"
                            clickable="false"
                            enabled="true"
                            focusable="false"
                            focused="false"
                            scrollable="false"
                            long-clickable="false"
                            password="false"
                            selected="false"
                            bounds="[0,1584][1080,1794]"
                            resource-id="com.evina.adsafetyfirstdemo:id/banner_bottom"
                            instance="1">
                            <android.webkit.WebView
                                index="0"
                                text=""
                                class="android.webkit.WebView"
                                package="com.evina.adsafetyfirstdemo"
                                content-desc=""
                                checkable="false"
                                checked="false"
                                clickable="false"
                                enabled="true"
                                focusable="false"
                                focused="false"
                                scrollable="false"
                                long-clickable="false"
                                password="false"
                                selected="false"
                                bounds="[0,1584][1080,1794]"
                                resource-id=""
                                instance="2">
                                <android.webkit.WebView
                                    index="0"
                                    text=""
                                    class="android.webkit.WebView"
                                    package="com.evina.adsafetyfirstdemo"
                                    content-desc=""
                                    checkable="false"
                                    checked="false"
                                    clickable="false"
                                    enabled="true"
                                    focusable="true"
                                    focused="true"
                                    scrollable="true"
                                    long-clickable="false"
                                    password="false"
                                    selected="false"
                                    bounds="[0,1584][1080,1794]"
                                    resource-id=""
                                    instance="3">`

## Environment

Appium version (or git revision) that exhibits the issue: Appium version : 1.8.0
Desktop OS/version used to run Appium: Windows 10
Node.js version (unless using Appium.app|exe): Nodejs 8.9.1
Real device or emulator/simulator: Android emulator
Driver : UiAutomator2 / Webdriver.io

**Comment by mykola-mokhnach** [comment]
Appium retrieves the attributes from UIA2 framework. I don't think there's anything that can be changed on our side

**Comment by Laywanger** [comment]
Sorry you have right, I use UI Automator Viewer and I reproduce it
