### ISSUE TITLE
I cant able to use Sikuli with iOS Appium. Unable to perform image recognise in appium.

### ISSUE THREAD

**Issue by varun2810** [appium/appium#10817]
## The problem

I cant able to use Sikuli with iOS Appium. Unable to perform image recognise in appium. 
I have combined sikuli with appium and using for UI element automation. It works well in android. But when i try to capture screenshot using sikuli in iOS . It is not working.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable): ---
* Desktop OS/version used to run Appium: Mac OS High Sierra [10.13.4]
* Node.js version (unless using Appium.app|exe): 9.11.1
* Mobile platform/version under test: iOS simulator
* Real device or emulator/simulator: iOS Simulator 11.1
* Appium CLI or Appium.app|exe: Appium.app & Appium CLI both

## Details

Is sikuli supported in iOS ???

## Code To Reproduce Issue [ Good To Have ]

public static int sikulibyaccessid(IOSDriver driver,String componentname,String ssname,String expname) throws ElementNotFoundException, IOException {
					
					
					try {
				
//						WebDriverWait wait = new WebDriverWait(driver,20);
//						wait.until(ExpectedConditions.visibilityOfElementLocated(By.id(componentname)));		

						WebElement element = driver.findElementByAccessibilityId(componentname);
				
				
		      
		      //Capturing the particular element
		      Screenshot scrnshot = new AShot().coordsProvider(new WebDriverCoordsProvider()).takeScreenshot(driver,element);
		      System.out.println(filePath());
		      ImageIO.write(scrnshot.getImage(),"PNG", new File("/Users/varun-6182/eclipse-workspace/IOStest/runtimescrnshot/" + ssname + ".png" ));
		      BufferedImage actualImage = scrnshot.getImage();
		      
		      Pattern searchImage = new Pattern("/Users/varun-6182/eclipse-workspace/IOStest/screenshots/" + expname + ".png").similar((float)0.9);
		      
		      Finder objFinder = null;
		      
		      @SuppressWarnings("unused")
		  		Match objMatch = null;
		      
		      objFinder = new Finder(actualImage);
		      
		      objFinder.find(searchImage); //searchImage is the image you want to search within ScreenImage
		      int counter = 0;
		      while(objFinder.hasNext())
		      {
		          objMatch = objFinder.next(); //objMatch gives you the matching region.
		          counter++;
		      }
		      if(counter!=0) {
		      	System.out.println("True");
		      	return counter;
		      }
		      else
		      {
		      	System.out.println("False");
		      }
					
					}
					
					catch(Exception e){
						e.printStackTrace();
						System.out.println("Exception found");
						
					}
					return 0;
		}

**Comment by mykola-mokhnach** [comment]
We neither test nor support anything like this explicitly.
