### ISSUE TITLE
iOS – Cannot perform TouchActions on Elements

### ISSUE THREAD

**Issue by mylesbarros** [appium/appium#10812]
## The problem

Elements are not responding to TouchActions when run on an iOS simulator.

## Environment

* Appium version (or git revision) that exhibits the issue: **`1.8.1` (`1.8.2-beta` exhibits the same behaviour)**
* Last Appium version that did not exhibit the issue (if applicable): **Unknown**
* Desktop OS/version used to run Appium: **OS X 10.13.3**
* Node.js version (unless using Appium.app|exe): **`10.1.0`**
* Mobile platform/version under test: **iOS 11.4 (iPhone 7)**
* Real device or emulator/simulator: **Simulator**
* Appium CLI or Appium.app|exe: **CLI**

## Details

When I attempt to apply Actions to interactive Elements I receive a `WebDriverException` with the message, `An unknown server-side error occurred while processing the command.`

When I attempt to interact with the same element using coordinates it executes successfully. For example,

**Fails:**
```python
next_button = driver.find_element_by_accessibility_id("Onboarding.NextPage")
print(next_button.is_enabled()) # True

action = TouchAction(driver)
action.tap(next_button)
action.perform()
```
Fails with (Appium CLI output):
```
[MJSONWP] Encountered internal error running command: Error: An unknown server-side error occurred while processing the command.
[MJSONWP]     at JWProxy.command$ (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:176:15)
[MJSONWP]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
```

**Succeeds:**
```python
next_button_x = 269
next_button_y = 561

action = TouchAction(driver)
action.tap(x=next_button_x, y=next_button_y)
action.perform()
```

## Link to Appium logs

**Appium CLI Log:**
https://gist.github.com/mylesbarros/56992cb1f05bd5302f7fac862dd42939

## Code To Reproduce Issue [ Good To Have ]

**Page Source Gist:**
https://gist.github.com/mylesbarros/23e03c88b604f916a1d2ae875f74d270
Element is on line `33`

**Fails:**
```python
next_button = driver.find_element_by_accessibility_id("Onboarding.NextPage")
print(next_button.is_enabled()) # True

action = TouchAction(driver)
action.tap(next_button)
action.perform()
```

_Possibly_ related to this issue:
https://github.com/appium/appium/issues/10807

**Comment by mykola-mokhnach** [comment]
This is a python client issue: https://github.com/appium/python-client/pull/214

**Comment by mylesbarros** [comment]
Thanks, mykola! You're absolutely right.
