### ISSUE TITLE
After an app reset command, the protocol is switched from W3C to MJSONWP.

### ISSUE THREAD

**Issue by studuffy** [appium/appium#10819]
## The problem

Given a session started with W3C capabilities, when I run an app reset command, then the protocol is switched from W3C to MJSONWP. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.2-beta
* Last Appium version that did not exhibit the issue (if applicable): unknown 
* Desktop OS/version used to run Appium: Mac
* Node.js version (unless using Appium.app|exe): 8.11.1
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Details

It seems that after the reset command, when creating the new session, it uses the same capabilities but does not end up with the same protocol being chosen. This can cause a problem on the client side if the client is expecting responses conforming to the W3C style.

## Link to Appium logs

https://gist.github.com/studuffy/30697ec560769fc25055d2676d450ff4

## Code To Reproduce Issue [ Good To Have ]

Create a W3C session:

```
curl -X "POST" "http://localhost:4723/wd/hub/session" \
     -H 'Content-Type: application/json' \
     -d $'{
  "capabilities": {
    "alwaysMatch": {
      "platformName": "iOS",
      "showXcodeLog": true,
      "app": "{path_to_app}",
      "deviceName": "Simulator",
      "platformVersion": "11.4",
      "udid": "{valid_udid}",
      "processArguments": {
        "args": [
          "ClearKeychain"
        ]
      },
      "automationName": "XCUITest",
      "language": "de"
    }
  }
}'
```

Then reset the app:

```
curl -X "POST" "http://localhost:4723/wd/hub/session/{session_id}/appium/app/reset" \
     -H 'Content-Type: application/json'
```

**Comment by mykola-mokhnach** [comment]
I'd rather simply quit the driver and start it again. The reset api literally is supposed to do the same.

**Comment by mykola-mokhnach** [comment]
@dpgraham FYI

**Comment by dpgraham** [comment]
Thanks for submitting this issue.

It's probably taking the processed capabilities and then creating the session using those caps in MJSONWP format. I'll have a look at this today.

**Comment by dpgraham** [comment]
There's a PR for this. Fix will be published today and will be available in appium beta.

**Comment by studuffy** [comment]
Thanks for looking at this so quickly!

**Comment by dpgraham** [comment]
No problem. Thank you for reporting this issue @studuffy!
