### ISSUE TITLE
Error getting device API level - An unknown server-side error occurred

### ISSUE THREAD

**Issue by amitrparmar** [appium/appium#10811]
## The problem

I am getting this issue when run multiple tests run n suite. Sometimes it run when I manually uninstall the "Appium Settings", "io.appium.uiautomator2.server" and "io.appium.uiautomator2.server.test" app from android device. But again when seconds test invoke it throws the same error.

## Environment

* Appium version : 1.7.2
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe):  v6.9.2 (node -v)
* Mobile platform/version under test: 6.0.1
* Real device or emulator/simulator: Real device (Nexus 7)
* Appium CLI or Appium.app|exe: Don't know how to check
* npm -v : 3.10.9

## Details

I am getting this issue when run multiple tests run n suite. Sometimes it run when I manually uninstall the "Appium Settings", "io.appium.uiautomator2.server" and "io.appium.uiautomator2.server.test" app from android device. But again when seconds test invoke it throws the same error.

## Code To Reproduce Issue [ Good To Have ]
Randomly, If we Hard Reset the device, and run on same machine, it may work without issue. But I observed that, suppose if you have multiple appium server running on different machine having different appium versions. Then it may start giving error.

**Comment by mykola-mokhnach** [comment]
Use the most recent Appium version

**Comment by amitrparmar** [comment]
Hi @mykola-mokhnach ,

I have updated Appium to 1.8.1.

I also encountered the same issue couple of times.
Could you please have a look into below log.

https://gist.github.com/amitrparmar/6c8489b011d12fb50924290a0ac5e7f2

**Comment by mykola-mokhnach** [comment]
It is the problem with adb or the device itself that it stops responding. There is nothing we can do here
