### ISSUE TITLE
error occurs when install app through adb, "Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES"

### ISSUE THREAD

**Issue by loveiset** [appium/appium#10820]
## The problem

I set app with apk path under test, when I run my testcase, error occurs
```
message=An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'D\:\\hcs\\Documents\\Android-SDK\\platform-tools\\adb.exe -P 5037 -s 1df270ff install D\:\\hcs\\Documents\\workspace\\app_auto_android\\lib\\appbase\\apps\\android_v280.apk' exited with code 1'; Stderr: 'adb: failed to install D:\hcs\Documents\workspace\app_auto_android\lib\appbase\apps\android_v280.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl312947254.tmp/base.apk: META-INF/CERT.SF indicates /data/app/vmdl312947254.tmp/base.apk is signed using APK Signature Scheme v2, but no such signature was found. Signature stripped?]'; Code: '1'
```

## Environment

- Appium version: 1.8.1
- Desktop OS/version used to run Appium: win7 SP1
- Node.js version: v8.11.0
- Mobile platform/version under test: android/7.1.1
- Real device or emulator/simulator: real device
- Appium CLI or Appium.app|exe: `appium --session-override --chromedriver-executable D:\hcs\Downloads\chromedriver_win32\chromedriver.exe`

#### firstly, I just test this command in windows command line, everything look fine, I can install this app correctly.
```
D:\hcs\Documents\Android-SDK\platform-tools\adb.exe -P 5037 -s 1df270ff install D:\hcs\Documents\workspace\app_auto_anndroid\lib\appbase\apps\android_v280.apk
Success
```
#### then, I run my testcase, error occurs
```
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl312947254.tmp/base.apk: META-INF/CERT.SF indicates /data/app/vmdl312947254.tmp/base.apk is signed using APK Signature Scheme v2, but no such signature was found. Signature stripped?]'; Code: '1'
```
#### at the end, I run this command in windows command line again, same error showed up
```
D:\hcs\Documents\Android-SDK\platform-tools\adb.exe -P 5037 -s 1df270ff install D:\hcs\Documents\workspace\app_auto_android\lib\appbase\apps\android_v280.apk
adb: failed to install D:\hcs\Documents\workspace\app_auto_android\lib\appbase\apps\android_v280.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl2018455872.tmp/base.apk: META-INF/CERT.SF indicates /data/app/vmdl2018455872.tmp/base.apk is signed using APK Signature Scheme v2, but no such signature was found. Signature stripped?]
```
#### assumption
has any possibility that appium modify my apk file under test?
I use beyond compare to differ this apk file before and after appium's executeion. only rear two bites are different.

## Link to Appium logs

[logs](https://gist.github.com/loveiset/98acb1e58327c8a8a2cf65fbfc6fecc6)

## Code To Reproduce Issue [ Good To Have ]

```
desired_caps = {
            "unicodeKeyboard": "True",
            "resetKeyboard": "True",
            "platformName": "Android",
            "platformVersion": "7.1.1",
            "deviceName": self.device.deviceId,
            "automationName": "Uiautomator2",
            "noReset": needReset,
            "nativeWebScreenshot": True,
            "fullReset": False,
            "autoGrantPermissions": True,
            "app": os.path.abspath(apk_file),
            "recreateChromeDriverSessions": True,
            "chromedriverExecutableDir": os.path.abspath(chrome_dir),
            "chromedriverChromeMappingFile": os.path.abspath(map_file),
        }
```

**Comment by mykola-mokhnach** [comment]
Try setting `noSign` capability to true

**Comment by loveiset** [comment]
after setting `noSign`, things look fine. I can run my testcase correctly, after test, I compare these two apk files, they keep same exactly.
[logs normal](https://gist.github.com/loveiset/cb7ac175c7b42e007b19f54c764756cb)
@mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
Ok, that's fine. I have a feeling that apksigner provided by Android SDK might be broken on Windows. This report seems to be similar to https://github.com/appium/appium/issues/10714

@loveiset Can you try the same and check if the file is signed properly?

**Comment by loveiset** [comment]
I found two build tools on my computer and tried them both with following command:
```
apksigner.bat sign --key C:\Users\hechangshu1\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\keys\testkey.pk8 --cert C:\Users\hechangshu1\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\keys\testkey.x509.pem D:\hcs\Documents\workspace\app_auto_android\lib\appbase\apps\android_v260.apk
```
after signing, both app can install through adb command correctly
```
D:\hcs\Documents\Android-SDK\platform-tools\adb.exe -P 5037 -s 1df270ff install D:\hcs\Documents\workspace\app_auto_android\lib\appbase\apps\android_v260.apk
Success
```

**Comment by liangyuan531** [comment]
I add onsign, it still happen.

**Comment by loveiset** [comment]
[appium beta log](https://gist.github.com/loveiset/b5f7df1aef74927aa2ad62b884f12b35)
@mykola-mokhnach 1.8.2 beta log, may this be helpful.

**Comment by mykola-mokhnach** [comment]
Thanks for assistance. I see the patch is not published yet :( . I'll let you know when to update.

**Comment by mykola-mokhnach** [comment]
@loveiset Please check it now. Make sure the appium-adb component is at 6.11.0+

**Comment by loveiset** [comment]
@mykola-mokhnach sorry for late replay, I have tried latest appium@beta, things woks fine with `noSign` set to `True` or `False`, logs here(both True and False in the link) [appium beta log](https://gist.github.com/loveiset/53bc8a1545d77664acbee01f9648c1f8)
