### ISSUE TITLE
browserName: null returned from current session capabilities when using Xcode 8 (XCUITest)

### ISSUE THREAD

**Issue by Dan-Maor** [appium/appium#10822]
## The problem

Starting with Appium 1.8.0, using Xcode 8 for testing iOS devices causes browserName: null to be returned from the current capabilities command.

This is likely a result of removing query & resolve from fb_activeApplication - by removing it the label property of the application is not resolved, and thus returns null instead of the application label.

This issue does not happen when using Xcode 9, and it may also affect other places in the WebDriverAgent code.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0 & 1.8.1
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2 (before query & resolve were removed)
* Desktop OS/version used to run Appium: Mac
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe:

**Comment by mykola-mokhnach** [comment]
@Dan-Maor Please check if https://github.com/appium/WebDriverAgent/pull/88 works for you

**Comment by DanMPerfecto** [comment]
Yup, that does the trick.
That's exactly the change I've used in my attempt to work around the issue locally, I even used the fb_isActivateSupported condition as well :)

**Comment by Dan-Maor** [comment]
Yup, that does the trick.
That's how I've worked around it locally, I even used the fb_isActivateSupported function as well :)

**Comment by mykola-mokhnach** [comment]
Why don't you create PRs then? I would make the process faster

**Comment by Dan-Maor** [comment]
I haven't contributed to any GitHub project before, I'm a bit new in this field.
I'll do some reading about it and will create proper PRs should I find other issues in the future.

**Comment by mykola-mokhnach** [comment]
np. Here you can get something to read: https://github.com/appium/appium/tree/master/docs/en/contributing-to-appium

**Comment by Dan-Maor** [comment]
Thanks.

**Comment by mykola-mokhnach** [comment]
The fix has been published in appium@beta
