### ISSUE TITLE
Encountered internal error running command: Error: Could not sign with default certificate with Latest Appium 

### ISSUE THREAD

**Issue by skumar1122** [appium/appium#10823]
## The problem
I am getting error when I am running with latest appium version by using uiautomator2 and getting below error around signing. When I remove uiautomator2 cap it works ok with same code.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe): 6.1.0
* Mobile platform/version under test: Android 6.0
* Real device or emulator/simulator: HTC
* Appium CLI or Appium.app|exe: CLI

## Details
WH5003627MUK:~ skumar$ appium-doctor 
info AppiumDoctor Appium Doctor v.1.4.3
info AppiumDoctor ### Diagnostic starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: /usr/local/bin/node
info AppiumDoctor  ✔ Node version is 6.10.3
info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ Xcode Command Line Tools are installed.
info AppiumDoctor  ✔ DevToolsSecurity is enabled.
info AppiumDoctor  ✔ The Authorization DB is set up properly.
info AppiumDoctor  ✔ Carthage was found at: /usr/local/bin/carthage
info AppiumDoctor  ✔ HOME is set to: /Users/skumar
info AppiumDoctor  ✔ ANDROID_HOME is set to: /Users/skumar/Library/Android/sdk
info AppiumDoctor  ✔ JAVA_HOME is set to: /Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home
info AppiumDoctor  ✔ adb exists at: /Users/skumar/Library/Android/sdk/platform-tools/adb
info AppiumDoctor  ✔ android exists at: /Users/skumar/Library/Android/sdk/tools/android
info AppiumDoctor  ✔ emulator exists at: /Users/skumar/Library/Android/sdk/tools/emulator
info AppiumDoctor  ✔ Bin directory of $JAVA_HOME is set
info AppiumDoctor ### Diagnostic completed, no fix needed. ###
info AppiumDoctor 
info AppiumDoctor Everything looks good, bye!
info AppiumDoctor 

**CAPS**:
{
   "desiredCapabilities":{
      "androidDeviceReadyTimeout":60,
      "goog:chromeOptions":{
         "args":[
            "disable-translate",
            "disable-popup-blocking",
            "disable-save-password-bubble",
            "enable-automatic-password-saving"
         ],
         "extensions":[
         ]
      },
      "platformVersion":"Android",
      "automationName":"uiautomator2",
      "browserName":"chrome",
      "platformName":"Android",
      "udid":"SH48FWM00673",
      "deviceName":"SH48FWM00673",
      "enablePerformanceLogging":true
   }

**Started from terminal:**
appium -p 4723 -U SH48FWM00673 --session-override --command-timeout 600 --no-reset

## Link to Appium logs
https://gist.github.com/skumar1122/bf05c4f27149daca55200f4acb371beb

Could someone help me ?

**Comment by mykola-mokhnach** [comment]
Which output do you get in terminal if this command is executed manully?

`[debug] [ADB] Starting '/Users/skumar/Library/Android/sdk/build-tools/28.0.0-rc2/apksigner' with args 'sign,--key,/usr/local/lib/node_modules/appium/node_modules/appium-adb/keys/testkey.pk8,--cert,/usr/local/lib/node_modules/appium/node_modules/appium-adb/keys/testkey.x509.pem,/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v1.12.0.apk'
`

**Comment by skumar1122** [comment]
Hi @mykola-mokhnach ,

I have added complete logs in above gist. do you more ?

**Comment by mykola-mokhnach** [comment]
I want the output from the command above being executed manually on the system where the test is running

**Comment by skumar1122** [comment]
-bash: /Users/skumar/Library/Android/sdk/build-tools/28.0.0-rc2/apksigner with args sign,--key,/usr/local/lib/node_modules/appium/node_modules/appium-adb/keys/testkey.pk8,--cert,/usr/local/lib/node_modules/appium/node_modules/appium-adb/keys/testkey.x509.pem,/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v1.12.0.apk: No such file or directory

**Comment by mykola-mokhnach** [comment]
🤦‍♂️ Perhaps, I cannot help here

**Comment by tester200xm** [comment]
I am having the same issue here on Windows.
Appium 1.8.1 bundled with Appium Desktop 1.6.1.
Appium Desktop is installed for "All Users".

Relevant log entries below.
```
[ADB] Running 'D:\Android\SDK\platform-tools\adb.exe -P 5037 -s emulator-5554 shell am force-stop io.appium.uiautomator2.server'
[ADB] Checking app cert for C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v1.12.0.apk
[ADB] Starting 'D:\Android\SDK\build-tools\28.0.0\apksigner.bat' with args 'verify,--print-certs,C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v1.12.0.apk'
[ADB] 'C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v1.12.0.apk' is not signed with debug cert.
[ADB] Zip-aligning 'C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v1.12.0.apk'
[ADB] Signing 'C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v1.12.0.apk' with default cert
[ADB] Starting 'D:\Android\SDK\build-tools\28.0.0\apksigner.bat' with args 'sign,--key,C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-adb\keys\testkey.pk8,--cert,C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-adb\keys\testkey.x509.pem,C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v1.12.0.apk'
[ADB] Cannot use apksigner tool for signing. Defaulting to sign.jar. Original error: Command 'D\:\\Android\\SDK\\build-tools\\28.0.0\\apksigner.bat sign --key 'C:\\Program Files (x86)\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-adb\\keys\\testkey.pk8' --cert 'C:\\Program Files (x86)\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-adb\\keys\\testkey.x509.pem' 'C:\\Program Files (x86)\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v1.12.0.apk'' exited with code 1; StdErr: Exception in thread "main" java.nio.file.AccessDeniedException: C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v1.12.0.apk
[ADB] 	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
[ADB] 	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
[ADB] 	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
[ADB] 	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:376)
[ADB] 	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
[ADB] 	at java.nio.file.Files.move(Files.java:1395)
[ADB] 	at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:342)
[ADB] 	at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:89)
[ADB] 
[ADB] Resigning apk.
[UiAutomator2] Deleting UiAutomator2 session
[UiAutomator2] Deleting UiAutomator2 server session
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: Error: Trying to proxy a session command without session id
[ADB] Running 'D:\Android\SDK\platform-tools\adb.exe -P 5037 -s emulator-5554 shell am force-stop ru.csat.cesarcar'
[ADB] Removing forwarded port socket connection: 8200 
[ADB] Running 'D:\Android\SDK\platform-tools\adb.exe -P 5037 -s emulator-5554 forward --remove tcp\:8200'
[ADB] Running 'D:\Android\SDK\platform-tools\adb.exe -P 5037 -s emulator-5554 forward --remove tcp\:8200'
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command 'D\:\\Android\\SDK\\platform-tools\\adb.exe -P 5037 -s emulator-5554 forward --remove tcp\:8200' exited with code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''
[BaseDriver] Event 'newSessionStarted' logged at 1529048825328 (10:47:05 GMT+0300 (Russia TZ 2 Standard Time))
[W3C] Encountered internal error running command: Error: Could not sign with default certificate. Original error Command ''C:\\Program Files\\Java\\jdk1.8.0_152\\bin\\java.exe' -jar 'C:\\Program Files (x86)\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-adb\\jars\\sign.jar' 'C:\\Program Files (x86)\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v1.12.0.apk' --override' exited with code 1
[W3C]     at ADB.callee$0$0$ (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\apk-signing.js:79:13)
[W3C]     at tryCatch (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[W3C]     at GeneratorFunctionPrototype.invoke (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[W3C]     at 
[HTTP] <-- POST /wd/hub/session 500 5068 ms - 2278

```
If I install for "Just me", everything works just fine with the same Java test code.
I assume that signing command tries to sign UiAutomator2 related apks in-place, where current user has no write rights (Program Files).

**Comment by mykola-mokhnach** [comment]
> Exception in thread "main" java.nio.file.AccessDeniedException: C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v1.12.0.apk

> If I install for "Just me", everything works just fine with the same Java test code.
I assume that signing command tries to sign UiAutomator2 related apks in-place, where current user has no write rights (Program Files).

Most likely. You need to adjust file permissions manually

**Comment by skumar1122** [comment]
HI @mykola-mokhnach ,

> WH5003627MUK:apks skumar$ java -jar appium-uiautomator2-server-v1.12.0.apk sign,--key,/usr/local/lib/node_modules/appium/node_modules/appium-adb/keys/testkey.pk8,--cert,/usr/local/lib/node_modules/appium/node_modules/appium-adb/keys/testkey.x509.pem,/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v1.12.0.apk
> no main manifest attribute, in appium-uiautomator2-server-v1.12.0.apk
> 

Do you know how do I set this manually ?
I am using appium for running mobile web tests here , Do i still need to sign this ?

**Comment by skumar1122** [comment]
```
[debug] [ADB] Running '/Users/skumar/Library/Android/sdk/platform-tools/adb -P 5037 -s ce0317132298d91403 shell am force-stop io.appium.uiautomator2.server'
[debug] [ADB] Checking app cert for /usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v1.12.0.apk
[debug] [ADB] Starting '/Users/skumar/Library/Android/sdk/build-tools/28.0.0-rc2/apksigner' with args 'verify,--print-certs,/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v1.12.0.apk'
[debug] [ADB] '/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v1.12.0.apk' is not signed with debug cert.
[debug] [ADB] Zip-aligning '/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v1.12.0.apk'
[debug] [ADB] Signing '/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v1.12.0.apk' with default cert
[debug] [ADB] Starting '/Users/skumar/Library/Android/sdk/build-tools/28.0.0-rc2/apksigner' with args 'sign,--key,/usr/local/lib/node_modules/appium/node_modules/appium-adb/keys/testkey.pk8,--cert,/usr/local/lib/node_modules/appium/node_modules/appium-adb/keys/testkey.x509.pem,/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v1.12.0.apk'
[ADB] Cannot use apksigner tool for signing. Defaulting to sign.jar. Original error: Command '/Users/skumar/Library/Android/sdk/build-tools/28.0.0-rc2/apksigner sign --key /usr/local/lib/node_modules/appium/node_modules/appium-adb/keys/testkey.pk8 --cert /usr/local/lib/node_modules/appium/node_modules/appium-adb/keys/testkey.x509.pem /usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v1.12.0.apk' exited with code 1; StdErr: Exception in thread "main" java.nio.file.AccessDeniedException: /usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v1.12.0.apk
[ADB] 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
[ADB] 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
[ADB] 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
[ADB] 	at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:447)
[ADB] 	at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
[ADB] 	at java.nio.file.Files.move(Files.java:1395)
[ADB] 	at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:342)
[ADB] 	at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:89)
[ADB] 
[debug] [ADB] Resigning apk.
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: Error: Trying to proxy a session command without session id
[debug] [ADB] Running '/Users/skumar/Library/Android/sdk/platform-tools/adb -P 5037 -s ce0317132298d91403 shell am force-stop com.android.chrome'
[debug] [ADB] Removing forwarded port socket connection: 8200 
[debug] [ADB] Running '/Users/skumar/Library/Android/sdk/platform-tools/adb -P 5037 -s ce0317132298d91403 forward --remove tcp\:8200'
[debug] [ADB] Running '/Users/skumar/Library/Android/sdk/platform-tools/adb -P 5037 -s ce0317132298d91403 forward --remove tcp\:8200'
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command '/Users/skumar/Library/Android/sdk/platform-tools/adb -P 5037 -s ce0317132298d91403 forward --remove tcp\:8200' exited with code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1529491058632 (11:37:38 GMT+0100 (BST))
[MJSONWP] Encountered internal error running command: Error: Could not sign with default certificate. Original error Command '/Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/bin/java -jar /usr/local/lib/node_modules/appium/node_modules/appium-adb/jars/sign.jar /usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v1.12.0.apk --override' exited with code 1
[MJSONWP]     at ADB.callee$0$0$ (/usr/local/lib/node_modules/appium/node_modules/appium-adb/lib/tools/apk-signing.js:79:13)
[MJSONWP]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 2884 ms - 503
[HTTP] 

```

**Comment by mykola-mokhnach** [comment]
> Do you know how do I set this manually ?

In Posix env there are `chown` and `chmod` commands for such purpose. Closed as not an issue

**Comment by skumar1122** [comment]
@tester200xm Is it working for you now?

**Comment by tester200xm** [comment]
Widening permissions in Program Files is a security hole, as any other user of the workstation can replace the legit binary with malicious one. I just use a per user install. Maybe I will later submit a PR to put signed apk into a per user location and deploy to device from there.

**Comment by Alwirasheikh** [comment]
getting the same error. Do you know how do I set this permission manually ? I am a new testing and dont have much tech knowledge

**Comment by AfonsoASilva** [comment]
I have the same problem here with appium desktop 1.6.3 you said I have to change the permission the only file/directory I can see to change the permission is /tmp/.mount_appiumsszq7C/app/resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/ but I don't thik is a good idea use a chmod in one temp directory like this.

You can be more specific, about what to do.

**Comment by AfonsoASilva** [comment]
I have the same problem here with appium desktop 1.6.3 you said I had to change the permission using chmod, the only file/directory I can see to change the permission is /tmp/.mount_appiumsszq7C/app/resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/ but I don't thik is a good idea use a chmod in one temp directory like this.

You can be more specific, about what to do.

**Comment by MummanaSubramanya** [comment]
In windows try to launch you appium app with "Run as Administrator" this would fix the error.

**Comment by MeghaHulage** [comment]
To Run code for Andriod os 7 & above 
set uiautomator2 to capability 
cap.setCapability("automationName", "uiautomator2");
and install uiautomator2 from cmd 
npm install -g appium-uiautomator2-driver --unsafe-perm=true (to run npm command Node.js must be installed on system)
and Run appium as Administrator- 
Right click on Appium and select option “Run As Administrator “

**Comment by fantasyado** [comment]
> In windows try to launch you appium app with "Run as Administrator" this would fix the error.

you saved my day bro!
