### ISSUE TITLE
Cannot get elements of obfuscated application

### ISSUE THREAD

**Issue by umashankaryadagiri1** [appium/appium#10821]
One of the class contains obfuscated , Because of that i am unable to find elements.

Is there any solution for obfuscated application

![ob](https://user-images.githubusercontent.com/38857489/41101431-c036aef2-6a81-11e8-8a70-d3d07d12fe62.png)

**Comment by mykola-mokhnach** [comment]
Assign accessibility ids to elements. Otherwise there is no workaround.
