### ISSUE TITLE
Unable to run TouchAction Command in Appium for Android

### ISSUE THREAD

**Issue by siddtiwari** [appium/appium#10827]
## The problem

Hi Everyone,

    I have less experience in Appium.
    I want to perform below mentioned action in my screen of emulator

    1. Scroll down a little to get one button
    2. Swipe left to find other button.

    I have tried Touch Action Command, but they are not scrolling the `screen also its not getting failed. My scripts just gets end there, without performing any action.`

## Environment
    My System config is:

    1. Mac OS 10.13
    2. Android Emulator 6 and 7
    3. Gson 2.8.2
    4. Appium 1.7.2
    5. Standalone 3.9.1
    6. javaclinet 6.0.0 Beta3

## Code To Reproduce Issue [ Good To Have ]

    Commands I have tried:

    1. action.press(427, 878).waitAction().moveTo(427, 
    554).release().perform();
    2. action.press(427, 878).moveTo(427, 554).release().perform();

3.
         Dimension size = wd.manage().window().getSize();
		 int startx = size.getWidth() / 2;
		 int starty = (int) (size.getHeight() * 0.8);
		 int endy = (int) (size.getHeight() * 0.2);

**Comment by mykola-mokhnach** [comment]
Use the most recent appium version (1.8.1). 

Also, please use discuss.appium.io to ask questions.
