### ISSUE TITLE
always loading for android test

### ISSUE THREAD

**Issue by liangyuan531** [appium/appium#10825]
## The problem
when I use appium to catch android element, it always loading, I need to refresh. sometimes, it works, but sometimes not.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Win10
* Node.js version (unless using Appium.app|exe): 8.11.1
* Mobile platform/version under test: android 8.1
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: appium.exe

**Comment by mykola-mokhnach** [comment]
We are unable to help without logs/screenshots
