### ISSUE TITLE
[error] [MJSONWP] Encountered internal error running command: Error: An unknown server-side error occurred while processing the command.

### ISSUE THREAD

**Issue by siddhantraut** [appium/appium#10830]
## The problem

[error] [MJSONWP] Encountered internal error running command: Error: An unknown server-side error occurred while processing the command.
    at JWProxy.command$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:176:15)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)

## Environment

* Appium version (Desktop 1.5.0 Server 1.7.2) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MAC Sierra 10.12.6
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:11.0.3 iPhone 8 Plus
* Real device or emulator/simulator: Real device

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/siddhantraut/45fb54b68b8ad54e78b92377d84c56d7

## Code To Reproduce Issue [ Good To Have ]

{
  "platformName": "iOS",
  "platformVersion": "11.0.3",
  "deviceName": "Enterprise Group’s iPhone",
  "automationName": "XCUITest",
  "udid": "72da4f9887ff1ad0b3163XXXXXXXX924b918a421",
  "app": "/Users/admin/Desktop/com.XXXX.XXXXXX.testf.iOS.ipa",
  "launchTimeout": 500000,
  "noReset": true
}

	public static void verify_joblist() throws InterruptedException, MalformedURLException {
		Setup.launch_APP("iOS");
		
		System.out.println("Entering User email");
		MobileElement el1 =  driver.findElement(By.xpath("//XCUIElementTypeApplication[@name=\"TestFlow\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeOther[3]/XCUIElementTypeOther[3]/XCUIElementTypeTextField/XCUIElementTypeOther"));
		el1.sendKeys("testqa01@gmail.com");

**Comment by mykola-mokhnach** [comment]
This error means that WDA unexpectedly stops responding to Appium commands. Try to update Appium to the most recent version and void using xpath for elements location.

**Comment by zane001** [comment]
I met the same error, my appium version is 1.8.1, Real device, iOS 11.3,  when i wrote this code self.driver.tap([(X, Y), ]),  i  got this error.
