### ISSUE TITLE
Can you put content list file in each doc directory?

### ISSUE THREAD

**Issue by tbwork** [appium/appium#10835]
Each directory of documents only has a list of sub-directories, which is very confusing to our fresh of appium.
Hope you can notice this problem.

**Comment by mykola-mokhnach** [comment]
Can you please properly describe what the problem is? Which directory it is? Which structure do you expect there (need an example), etc?

**Comment by tbwork** [comment]
@mykola-mokhnach  Hi，buddy. Almost every directory in the docs has no readme.md to list that what this directory is for: e.g., [main doc entry for English reader](https://github.com/appium/appium/tree/master/docs/en), [writing-running-appium](https://github.com/appium/appium/tree/master/docs/en/writing-running-appium), etc.

**Comment by imurchie** [comment]
This seems like a reasonable thing to do. I'll add it to our work. Thanks for the suggestion!

**Comment by tbwork** [comment]
Thanks for providing such an awesome tool~ @imurchie

**Comment by mykola-mokhnach** [comment]
Closed as fixed
