### ISSUE TITLE
getDeviceTime format

### ISSUE THREAD

**Issue by WildOrangutan** [appium/appium#10832]
#### Note

I'm looking this from Android perspective. Tough this could be a general improvement, especially when testing on multiple platforms, with common code.

#### Function in question

driver.getDeviceTime()

#### Suggestion

- Standardize default date return format.

- Optional date format parameter: _driver.getDeviceTime(formatString)_

## Environment

* Appium version (or git revision) that exhibits the issue: using 1.7.2, tough functionallity in question didn't change in newer versions
* Node.js version: 6.14.0
* Mobile platform/version under test: using Android, tough can be cross platform related
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: CLI

## Details

Atm this function (on Android) returns output from Linux's date command. For example "Fri Jun  8 21:14:05 UTC 2018". I have to do some time dependant tests, so I have to parse this date. 

I'm annoyed cause I have no control over date format, which can be one more thing to haunt you, if date happened to change.

Also, this may get annoying if you're testing on multiple platforms (e.g. Android + IOS), since there's even higher change default format may differ. As far as I've checked, it already does, please correct me if I'm wrong.

**Comment by mykola-mokhnach** [comment]
In appium@beta the date is returned in ISO-8601 format by default

**Comment by KazuCocoa** [comment]
Can set custom format. 
https://github.com/appium/appium-base-driver/pull/225 , https://github.com/appium/appium-android-driver/pull/378
