### ISSUE TITLE
Parameters were incorrect error from appium when called from protractor. 

### ISSUE THREAD

**Issue by jiwrakhkiran** [appium/appium#10838]
## The problem

When I try to run the device specific command (rotationGesture in this case), it throws error 

_Parameters were incorrect We wanted {"required":["x","y","radius","rotation","touchCount","duration"],"optional":["element","sessionId","id"]} and you sent ["x","y","duration","rotation","touchCount"]_

## Environment

* Appium.app version 1.8.0
* Desktop OS/version used to run Appium: MacOS 10.13.4
* Mobile platform/version under test: Andriod/ 7.1.1
* Real device or emulator/simulator: emulator

## Details
We are using protractor(5.3.2) + [WDBridge](https://github.com/sebv/wd-bridge) for creating session on Appium. Above error does not occur for all commands, e.g. lockDevice method works just fine.  I tried implmenting comments from [this](https://github.com/appium/python-client/issues/162) issue, but had no luck. 

## Link to Appium logs

[GIST](https://gist.github.com/jiwrakhkiran/e1d025e8579b29ea9c30da962a111fd0)

## Code To Reproduce Issue [ Good To Have ]
config:
```
let wd = require('wd');
let protractor = require('protractor');
let wdBridge = require('wd-bridge')(protractor, wd);
exports.config = {
    seleniumAddress: 'http://localhost:4723/wd/hub',

    multiCapabilities: [{
        browserName: '',
        platformName: 'Android',
        platformVersion: '7.1.1',
        deviceName: `simulatorName`,
        app: 'apk path',
        newCommandTimeout: 30 * 60000,
        appPackage: 'com.kerio.mykerio',
        appActivity: 'com.kerio.mykerio.AppliancesActivity',
    }],
    onPrepare: function () {
        wdBridge.initFromProtractor(exports.config);
        reportersSetup.onPrepareSetup();
    },
```

Spec
```
import {browser} from 'protractor';
await extend(browser.driver).rotationGesture(0, 0, 5, 0);
```

**Comment by mykola-mokhnach** [comment]
The endpoint you are trying to use is not implemented in Android driver anyway. I assume you have to build TouchAction chain instead in order to simulate rotation gesture.

**Comment by jiwrakhkiran** [comment]
@mykola-mokhnach Thanks for pointing out unimplemented API. I tried with iphone capability but got the same error. Any guess?

**Comment by mykola-mokhnach** [comment]
In general, only changing device orientation to landscape and back to portrait is only supported.

**Comment by jiwrakhkiran** [comment]
Interesting, [this](http://appium.io/docs/en/commands/device/interactions/rotate/) page says otherwise
`driver.rotateDevice({x: 114, y: 198, duration: 5, radius: 3, rotation: 220, touchCount: 2});
`
@mykola-mokhnach should we remove above from documentation if not supported, because for there is [separate section](http://appium.io/docs/en/commands/session/orientation/get-orientation/) for orientation.

**Comment by mykola-mokhnach** [comment]
I think this a mistake in the documentation. I've never seen this endpoint is supported in xcuitest driver

**Comment by jiwrakhkiran** [comment]
Great, Shouldn't this be fixed? I can submit a PR if need be.

**Comment by mykola-mokhnach** [comment]
Submitting a PR is always a good idea

**Comment by dpgraham** [comment]
@mykola-mokhnach Do any Appium drivers support rotation? Is it only IOS Driver?

**Comment by mykola-mokhnach** [comment]
@dpgraham I don't know. I've never worked with this API

**Comment by dpgraham** [comment]
Confirmed that IOS Driver is the only one that supports this: https://github.com/search?q=org%3Aappium+mobileRotation&type=Code
