### ISSUE TITLE
Tap works on all the element in real device using UiAutomator GUI but not work with code using Appium1.6.1

### ISSUE THREAD

**Issue by Ashishqa** [appium/appium#10833]
## The problem

I am able to tap on element and record it using UiAutomator GUI , however after implementing in code tap doesn't work on real device without throwing any error.  

## Environment
Appium Versio: 1.6.1
JavaClient: 6.0.0
Selenium Standalone server: 3.12

## Details

I am automating mobile browser application in real android device(Samsung Galaxy S8+). I am changing the context from webview to native then tap works for few element but not for all. It doesn't throw any error while tap doesn't happen. If I use capability automationName=uiautomator2 then it throw error for MobileElement.

Note:- Tap works for all the element using UiAutomator GUI

Kindly help me to fix this issue.

**Comment by mykola-mokhnach** [comment]
It is impossible to suggest anything without logs
