### ISSUE TITLE
Need to get current city name and country name through java and Appium

### ISSUE THREAD

**Issue by grpratap69** [appium/appium#10845]
## The problem

Need to get current city name and country name through java and Appium on the run. Since my app reflects current city name and country name dynamically and I need to verify that correct city n country name is displayed

## Environment

Real device

node 10.4.0
nam 6.1.0

**Comment by mykola-mokhnach** [comment]
Unfortunately  the question does not contain enough data to answer it.
Please use Appium forum to ask questions.
