### ISSUE TITLE
setGeoLocation iOS Real device problem

### ISSUE THREAD

**Issue by ktanev** [appium/appium#10848]
## The problem

Execution of the command `idevicelocation -d -u REAL_DEVICE_UUID 30 23` changes my coordinates on the real device, but when executing the test with 

`driver.setLocation(new Location(30.0001, 21.0002, 1));`

returns 

` Responding to client with driver.setGeoLocation() result: null`  
and the coordinates aren't changed 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1 
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 10.13.4
* Node.js version (unless using Appium.app|exe): v8.11.2
* Mobile platform/version under test: 11.4
* Real device or emulator/simulator: real device 
* Appium CLI or Appium.app|exe: node Appium cli 

## Link to Appium logs

https://gist.github.com/ktanev/f51605bfd7cf4606f8df8e841f1983d2

## Code To Reproduce Issue [ Good To Have ]

`driver.setLocation(new Location(30.0001, 21.0002, 1));`

**Comment by mykola-mokhnach** [comment]
What do you expect it to return instead?

**Comment by ktanev** [comment]
Not sure about the returned result, but the location isn't changed.

**Comment by mykola-mokhnach** [comment]
Can you try appium@beta?

**Comment by ktanev** [comment]
Yes. A little bit later i will check the beta and i will write you. Thanks

**Comment by ktanev** [comment]
With the appium@beta it works. Thanks!
