### ISSUE TITLE
Error: Error finding if app is installed. Original error: Error executing adbExec. Original error: 'Command '/Users/XXX/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pm list packages io.appium.settings' exited with code 1'; Stderr: 'Error: Could not access the Package Manager.  Is the system running?'; Code: '1'

### ISSUE THREAD

**Issue by ashwinibaisutrave** [appium/appium#10842]
## The problem

I am facing this issue all of sudden while executing the Android scripts on all the machines .

Error: Error finding if app is installed. Original error: Error executing adbExec. Original error: 'Command '/Users/asu22/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pm list packages io.appium.settings' exited with code 1'; Stderr: 'Error: Could not access the Package Manager.  Is the system running?'; Code: '1'

## Environment

* Appium version (or git revision) that exhibits the issue:Appium v1.7.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:Mac high sierra and Mac Sierra
* Node.js version (unless using Appium.app|exe): v9.5.0
* Mobile platform/version under test:
* Real device or emulator/simulator: Android Emulators OS 7.1 ,OS 8.1 ,OS.6.0
* Appium CLI or Appium.app|exe: Both

## Link to Appium logs

https://gist.github.com/ashwinibaisutrave/c908d4291570286e715acbb27798aeb6

**Comment by mykola-mokhnach** [comment]
It is a problem with your emulator. We cannot do anything about this on Appium side.

**Comment by msaperst** [comment]
can you elaborate on the problem with the emulator? Or the solution? I'm running into the same issue
