### ISSUE TITLE
chromedriverExecutableDir capability is applicable for both Desktop and Mobile ?

### ISSUE THREAD

**Issue by KiThoSivaPrakash** [appium/appium#10844]
One of the feature of Appium 1.8 is to provide the chromedriverExecutableDir and chromedriverChromeMappingFile capabilities to test in different versions of Chrome.

Is this capabilities are applicable only for Desktop Chrome or we can use these capabilities to specify the appium chromedriver version for testing in different Mobile Chrome version also ?

**Comment by jacattau** [comment]
Appium is for mobile, so the capability is used for mobile chrome.
