### ISSUE TITLE
Find and Tap action is not working in appium 1.8.2 beta.

### ISSUE THREAD

**Issue by akhand-pratap2807** [appium/appium#10841]
Not able to click on an element which is present at last corner of scroller after updated the appium library.
When I was using the appium.io client as 5.90 BETA and appium 1.7.2 then I was able to click the element if it is not present on the screen as well.
In that case I was using below code:
 		
 		MultiTouchAction multiTouch = new MultiTouchAction(mAppiumDriver);
		TouchAction tap = new TouchAction(mAppiumDriver);
		multiTouch.add(tap.press(getElementUsingAccessibilityID(accessiblityID)).waitAction(Duration.ofMillis(100)).release());
multiTouch.perform();

However, after updating appium as 1.8.2 beta and appium.io as 6.0.0, I am not able to click the element even I have modified the code as per new libs
               
               MultiTouchAction multiTouch = new MultiTouchAction(mAppiumDriver);
		IOSTouchAction tap = new IOSTouchAction(mAppiumDriver);	
		multiTouch.add(tap.press(iosPressOptions().withElement(ElementOption.element(ele)))
				.waitAction(WaitOptions.waitOptions(Duration.ofMillis(2000)))
				.release());
		multiTouch.perform();
	}
## Environment

* Appium version (or git revision) that exhibits the issue:1.8.2beta
* Last Appium version that did not exhibit the issue (if applicable):1.7.2
* Desktop OS/version used to run Appium:10.13.5
* Node.js version (unless using Appium.app|exe):10
* Mobile platform/version under test:10.3.3,11.3.1
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe:APPium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Can you attach the server log?

**Comment by akhand-pratap2807** [comment]
Log path: https://gist.github.com/akhand-pratap2807/d80e22d2ebdd6ea917aa975422f670c8

**Comment by akhand-pratap2807** [comment]
Observation: 
Everytime it taps on the last element of the scroller which is visible on the screen.
Either for left movement or right scrolling.

**Comment by mykola-mokhnach** [comment]
Are you sure this is the correct log? I don't observe any multi touch calls there.

**Comment by akhand-pratap2807** [comment]
Please see at line number: 89 & 90

**Comment by mykola-mokhnach** [comment]
> [35m[HTTP][39m [90m{"actions":[{"action":"press","options":{"element":"14000000-0000-0000-0026-000000000000"}},{"action":"wait","options":{"ms":2000}},{"action":"release","options":{}}]}[39m

That one is a single long press

**Comment by akhand-pratap2807** [comment]
I am using below code to identify an element which is present at last corner of the scrollbar.

  MultiTouchAction multiTouch = new MultiTouchAction(mAppiumDriver);
	IOSTouchAction tap = new IOSTouchAction(mAppiumDriver);	
	multiTouch.add(tap.press(iosPressOptions().withElement(ElementOption.element(ele)))
			.waitAction(WaitOptions.waitOptions(Duration.ofMillis(2000)))
			.release());
	multiTouch.perform();

It behaves like a long press tap. I expect that it would search for that last element and do the long press.

 Because previously when I was using 1.7.2 version  and with below code
MultiTouchAction multiTouch = new MultiTouchAction(mAppiumDriver);
	TouchAction tap = new TouchAction(mAppiumDriver);
	multiTouch.add(tap.press(getElementUsingAccessibilityID(accessiblityID)).waitAction(Duration.ofMillis(100)).release());

It searches first for that last element and then click.  
Please suggest the way for below requirement:

Search a Web-element horizontally which is not present on the screen, and then tap on that.

**Comment by mykola-mokhnach** [comment]
You could try to use scroll or swipe in order to scroll to the element and make it visible first. Check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios/ios-xctest-mobile-gestures.md for more details

In general touch actions have been rewritten since Appium 1.8.0 to use native XCTest calls, so if something does not work there then please create an issue report to Apple.

**Comment by akhand-pratap2807** [comment]
@mykola-mokhnach  **mobile: tap** is also not working in my case. Could you please look into this issue. Till the previous release touch action did the scroll and click both operations. It was expected that in 1.8.2 it behaves like this. But the APIs and the way you suggested to use is also not working.
Can you reopen the issue.

**Comment by mykola-mokhnach** [comment]
Ok, I'll keep it opened

**Comment by akhand-pratap2807** [comment]
Please provide any update

**Comment by akhand-pratap2807** [comment]
@mykola-mokhnach I am not able to scroll and click the actual element. 
Let assume I have 3 buttons A,B and C. A and B is visible on current screen but C is present after first-time scroll. When I am trying to move the C using below code, every-time scrolling finishes at point B. Which is last point of current screen. I was expecting that it will by pass B and reached out to C. Could you please suggest If I have written wrong code or bug? I am stuck somewhere. Help would really be appreciated.
//			multiTouch.add(action.press(IOSPressOptions.iosPressOptions().withElement(ElementOption.element(ele)))
			.waitAction(WaitOptions.waitOptions(Duration.ofMillis(5000)))
			.moveTo(PointOption.point(200, ele.getLocation().getY())).release());

**Comment by akhand-pratap2807** [comment]
@imurchie Please suggest

**Comment by akhand-pratap2807** [comment]
We wanted information about how to use below XCUITest function in Appium
Source page: https://developer.apple.com/documentation/xctest/xcuielement
**
func click(forDuration: TimeInterval, thenDragTo: XCUIElement)
Clicks and holds for a specified duration (generally long enough to start a drag operation) then drags to the other element.
**

**Comment by akhand-pratap2807** [comment]
Kindly provide an update. Need to deliver a project. I have updated Appium and got hinged.

**Comment by Kitty2014** [comment]
@akhand-pratap2807 @mykola-mokhnach  any update process？

**Comment by akhand-pratap2807** [comment]
@Kitty2014 did you face the same issue?

**Comment by Kitty2014** [comment]
@akhand-pratap2807  sure, multiTouch three position same issue

**Comment by akhand-pratap2807** [comment]
@Kitty2014 Did you get any workaround for this. Because it seems like it is WDA issue. Even I saw the changes in WDA to fix this Apple issue and update my lib too. Still, I am getting the same problem.
When I am trying to click the element which is not present on current screen and needs one-time scroll to reach there then failed by appium to click that element. It is clicking on the last element of the screen. Previously before the update, it was clicking on the correct element. I must do the appium update because in last release they were not providing webview support and failed to identify Web elements.
suggest if you have any solution for this.

**Comment by Kitty2014** [comment]
@akhand-pratap2807 I can resold  using xcode recorder script and run in Xcode  ,but fail with appium

**Comment by Kitty2014** [comment]
@mykola-mokhnach  could you have a look, thanks very much😊

**Comment by akhand-pratap2807** [comment]
If you have to scroll then you can use below method:
public void scrollForOption(String ID){
		RemoteWebElement parent = (RemoteWebElement)mAppiumDriver.findElement(By.className("XCUIElementTypeTable"));
		String parentID = parent.getId();
		HashMap<String, String> scrollObject = new HashMap<String, String>();
		scrollObject.put("element", parentID);
		scrollObject.put("name", ID);
		mAppiumDriver.executeScript("mobile:scroll", scrollObject);
	}

But it is slow. Try and let me know.

**Comment by akhand-pratap2807** [comment]
@Kitty2014 , I saw your posts and questions related to app performance measuring using appium.
I tried and ran successfully with your code. Also, trace file is generating but when I open that file it is the blank document. Did you face this issue or do you have any workaround for this?

**Comment by akhand-pratap2807** [comment]
appreciate your help here.

**Comment by mykola-mokhnach** [comment]
Closed as inactive

**Comment by akhand-pratap2807** [comment]
Attached device log here: https://gist.github.com/akhand-pratap2807/11654f79b1e05ae23744343c6c0da97a
