### ISSUE TITLE
idevicesyslog managed by appium when not requested

### ISSUE THREAD

**Issue by kazzmir** [appium/appium#10849]
## The problem

The appium-ios-driver will 1) kill any existing idevicesyslog processes for the given udid being tested (https://github.com/appium/appium-ios-driver/blob/30b3c545278cba286b786c8360812164cf7d5f3e/lib/device-log/ios-log.js#L279) and 2) spawn a new idevicesyslog even if the `showIOSLog` capability is not set.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Desktop OS/version used to run Appium: macos
* Mobile platform/version under test: ios
* Real device or emulator/simulator: real

## Details

I run my own idevicesyslog but it is killed by appium when a new session is started. I would prefer that appium does not kill my idevicesyslog process. My current workaround is to copy the idevicesyslog binary to a new name, thus avoiding being targeted by `pkill`.

**Comment by jlipps** [comment]
@mykola-mokhnach @imurchie do we need to run idevicesyslog for our own purposes even if log capture is not requested via caps?

**Comment by mykola-mokhnach** [comment]
Previously it was necessary because we were reading WDA URL from the log, but now it is not the case anymore. I think we could add a separate capability to not  start the log listener automatically. However, this will require to change several other places where we assume that the log listener is running.

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-xcuitest-driver/pull/878

**Comment by KazuCocoa** [comment]
`skipLogCapture` capability can disable crash, system, safari console and safari network logs by appium/appium-xcuitest-driver#878
