### ISSUE TITLE
Error : An unknown server-side error occurred while processing the command. Original error: Could not initialize ios-deploy make sure it is installed (npm install -g ios-deploy) and works on your system.

### ISSUE THREAD

**Issue by kalp-shah** [appium/appium#10843]
![screen shot 2018-05-11 at 3 51 21 pm](https://user-images.githubusercontent.com/38104571/39920064-5ff012f8-5533-11e8-82ce-25b3f10fcb1c.png)
## The problem

After insert desired capabilities when I start Appium server at that moment I got error "An unknown server-side error occurred while processing the command. Original error: Could not initialize ios-deploy make sure it is installed (npm install -g ios-deploy) and works on your system."

My desired capabilities is 
{
  "platformName": "iOS",
  "platformVersion": "11.1.2",
  "deviceName": "iPhone 8",
  "app": "/Users/Desktop/iOSApp.ipa",
  "udid": "<device_udid>"
}

Previously It works and I am able to inspect element by Appium Inspector.
For Android App, It's working fine and I am able to inspect element of App by Appium inspector.
Here I attached my error message screen shot.

## Environment

- I am running Appium Desktop version _<1.6.1>_.
- I am on (pick one):
    - [ Y] Mac OS - 10.13.4
        Xcode version is :- 9.3

**Comment by mykola-mokhnach** [comment]
>  Could not initialize ios-deploy make sure it is installed (npm install -g ios-deploy) and works on your system.

Did you try this?

**Comment by kalp-shah** [comment]
@mykola-mokhnach  - After start Appium Server and when user set desired capabilities and start a session then got error.
Here I set capabilities.

{
  "platformName": "iOS",
  "platformVersion": "11.1.2",
  "deviceName": "iPhone 8 ",
  "automationName": "Appium",
  "app": "<App_Path>",
  "appium-version": "1.2.7",
  "udid": "<udid>"
}

let me know what other information you needed.

**Comment by mykola-mokhnach** [comment]
Once again, did you try the solution from the error message? Is the `ios-deploy` tool present in your PATH? Does it work if executed manually?

**Comment by mykola-mokhnach** [comment]
Have you checked the process [environment](https://github.com/appium/java-client/blob/master/docs/environment.md)? Is the binary visible to Appium server?

**Comment by kalp-shah** [comment]
Yes. 
I uninstall node (nvm + npm) & appium and after uninstall, I install it. ( when you install at that moment, install all your dependent libraries) 
My Issue resolved.
Thanks for your help..!
