### ISSUE TITLE
Appium Version 1.8.0 Issue

### ISSUE THREAD

**Issue by sagarsheth27** [appium/appium#10856]
Hi Guys

I am unable to open app using appium 1.8.0. App is not opened in phone and error got generated.
I installed uiautomator2 via npm command through terminal in MAC.
Below are the capabilities in my script.

**capabilities.setCapability("deviceName", "Nexus");
		capabilities.setCapability(CapabilityType.VERSION, "7.0");
		capabilities.setCapability("platformName", "Android");
		// Set android app package capability names
		capabilities.setCapability("appPackage", "Xxxxxxx");
		//com.pscu.mobile
		capabilities.setCapability("automationName", "uiautomator2");
		//capabilities.setCapability("versionNmae", "");
		capabilities.setCapability("appActivity", "xxxxxxxxx");
		capabilities.setCapability("noReset",true);
		capabilities.setCapability("fullReset", false);**

**Comment by saikrishna321** [comment]
@sagarsheth27 without logs its impossible to help. Please add appium logs

**Comment by sagarsheth27** [comment]
Hi @saikrishna321 

PFA of server log.
[appium-server-logs copy.txt](https://github.com/appium/appium/files/2093536/appium-server-logs.copy.txt)

On Appium 1.7.0, its's working properly, but in this version, not.
Kindly share version 1.7.0 appium's link please.

**Comment by saikrishna321** [comment]
@sagarsheth27 

> [error] [W3C] Encountered internal error running command: Error: Cannot start the 'com.bpi.ng.mobilebanking' application. Original error: Cannot start the 'com.bpi.ng.mobilebanking' application. Original error: Activity name '.com.bpi.ng.mobilebanking.MainActivity' used to start the app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity

can you make sure Application is installed on device else provide the app capability with path to apk.

**Comment by sagarsheth27** [comment]
That is already installed and before that in appium 1.7.0, it's working
properly.
THANKS & REGARDS
SAGAR SHETH

**Comment by sagarsheth27** [comment]
[appium-server-logs copy.txt](https://github.com/appium/appium/files/2094067/appium-server-logs.copy.txt)
PFA of log after updating sdk manager as well.

**Comment by dpgraham** [comment]
@sagarsheth27 Can you try running `/Users/sagarsheth/android-sdk-macosx/platform-tools/adb -P 5037 -s HT7AB1A04042 shell am start -W -n com.bpi.ng.mobilebanking/.com.bpi.ng.mobilebanking.MainActivity -S` from the command line?

**Comment by sagarsheth27** [comment]
What command I have to type exactly. Can you please send me exact line?

**Comment by dpgraham** [comment]
`/Users/sagarsheth/android-sdk-macosx/platform-tools/adb -P 5037 -s HT7AB1A04042 shell am start -W -n com.bpi.ng.mobilebanking/.com.bpi.ng.mobilebanking.MainActivity -S`
