### ISSUE TITLE
[Android] Appium can't upgrade package version sometimes

### ISSUE THREAD

**Issue by vduhautois** [appium/appium#10859]
## The problem

We just noticed when our Android team delivers us a new build of the a pre-release app (example - old : 4.10.0.550, new : 4.10.0.557) , appium won't install the new apk and only perform a fast reset.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

## Details

This is the dump badging of our 2 versions : 
➜  ~ aapt d badging apk/4.10.0.557.apk | grep "package"
package: name='fr.leboncoin.delivery' versionCode='50557' versionName='4.10.0.557'

➜  ~ aapt d badging apk/4.10.0.550.apk | grep "package"
package: name='fr.leboncoin.delivery' versionCode='50550' versionName='4.10.0.550'

But, when i execute a test, server side, appium respond :
The installed 'fr.leboncoin.delivery' package does not require upgrade ('4.10.0' >= '4.10.0')

After looking at the code, i found why in appium-adb module, in tools/apk-utils.js 

In installOrUpgrade method, we check if package needs to be updated regarding versionCode or versionName.
But, the versionName is coerce into SemVer :
 - line 464 : const pkgVersionName = semver.valid(semver.coerce(pkgVersionNameStr));
 - line 469 : const apkVersionName = semver.valid(semver.coerce(apkVersionNameStr));

And this is why only '4.10.0' is taken for comparison. The additional labels for pre-release and build metadata are deleted.
So we can't launch on multiple pre-release version of an app if the semantic version hasn't changed, even if the versionCode has changed.

I think of two possible solutions :
 - the possibility not to coerce the versionName and keep all additional labels in versionName
 - change logic in installOrUpgrad method : instead of checking all conditions no to upgrade a package, begin to check if the package should be upgraded (because in our context, versionCode has changed - 50550 to 50557). 

Thanks guys,
BR,
Vaïk Duhautois

**Comment by mykola-mokhnach** [comment]
You can set fullReset to true as a workaround.
Can you also attach the server logs?

**Comment by vduhautois** [comment]
We won't the apk uninstall at the end of the test, this is why we don't put the fullReset tag to true.
I attach the full server logs right now

**Comment by mykola-mokhnach** [comment]
Also it would be interesting to see the output of `adb shell dumpsys package fr.leboncoin.delivery` command

**Comment by mykola-mokhnach** [comment]
This is the actual algorithm, so comparison of version codes should work. Perhaps, they are not parsed properly

```
  const {versionCode:pkgVersionCode, versionName:pkgVersionNameStr} = await this.getPackageInfo(pkg);
  const pkgVersionName = semver.valid(semver.coerce(pkgVersionNameStr));
  if (!apkInfo) {
    apkInfo = await this.getApkInfo(apk);
  }
  const {versionCode:apkVersionCode, versionName:apkVersionNameStr} = apkInfo;
  const apkVersionName = semver.valid(semver.coerce(apkVersionNameStr));

  if (!_.isNumber(apkVersionCode) || !_.isNumber(pkgVersionCode)) {
    log.warn(`Cannot read version codes of '${apk}' and/or '${pkg}'`);
    if (!_.isString(apkVersionName) || !_.isString(pkgVersionName)) {
      log.warn(`Cannot read version names of '${apk}' and/or '${pkg}'. Assuming correct app version is already installed`);
      return;
    }
  }
  if (_.isNumber(apkVersionCode) && _.isNumber(pkgVersionCode) && pkgVersionCode > apkVersionCode) {
    log.debug(`The installed '${pkg}' package does not require upgrade (${pkgVersionCode} > ${apkVersionCode})`);
    return;
  }
  // Check version names in case if version codes are not being updated properly
  if (_.isString(apkVersionName) && _.isString(pkgVersionName)) {
    if (semver.satisfies(pkgVersionName, `>=${apkVersionName}`)) {
      log.debug(`The installed '${pkg}' package does not require upgrade ('${pkgVersionName}' >= '${apkVersionName}')`);
      return;
    }
  } else if (_.isNumber(apkVersionCode) && _.isNumber(pkgVersionCode) && pkgVersionCode === apkVersionCode) {
    log.debug(`The installed '${pkg}' package does not require upgrade (${pkgVersionCode} === ${apkVersionCode})`);
    return;
  }

  log.debug(`The installed '${pkg}' package is older than '${apk}' ` +
            `(${pkgVersionCode} < ${apkVersionCode} or '${pkgVersionName}' < '${apkVersionName}')'. ` +
            `Executing upgrade`);
  try {
    await this.install(apk, Object.assign({}, options, {replace: true}));
  } catch (err) {
    log.warn(`Cannot upgrade '${pkg}' because of '${err.message}'. Trying full reinstall`);
    if (!await this.uninstallApk(pkg)) {
      throw new Error(`'${pkg}' package cannot be uninstalled`);
    }
    await this.install(apk, Object.assign({}, options, {replace: false}));
  }
```

**Comment by vduhautois** [comment]
this is the semver.coerce(pkgVersionNameStr) that cause the problem.
It coerces the versionName from 4.10.0.557 to 4.10.0 only

**Comment by vduhautois** [comment]
https://www.npmjs.com/package/semver
=> https://semver.org/

**Comment by mykola-mokhnach** [comment]
The fix has been merged to appium@beta. You can try it
