### ISSUE TITLE
Opening View Controller is extremely slow on Appium

### ISSUE THREAD

**Issue by randhirkumarcse** [appium/appium#10853]
## In my app, instantiating and pushing view controller is extremely slow means it's taking 5+ minutes. Tested on simulator only.

Other than this, mostly automation is going good. This is the only where I got stuck right now.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 10.13.4
* Node.js version (unless using Appium.app|exe): v8.11.2
* Mobile platform/version under test: iOS 11.3
* Real device or emulator/simulator: Simulator iPhone 6
* Appium CLI or Appium.app|exe: Appium.app

## Capabilities:

"platformName": "iOS", "platformVersion": "11.3", "deviceName": "iPhone 6", "automationName": "XCUITest", "app": "/Users/xxx/Documents/Downloads/iOSApp.app", "autoAcceptAlerts": true, "autoDismissAlerts": true, "autoGrantPermissions": true, "databaseEnabled": true

## Code To Reproduce Issue [ Good To Have ]

```
@IBAction fileprivate func locationButtonTapped(_ sender: UIButton)
    {
        if (mSelectLocationVC == nil)
        {
            mSelectLocationVC = self.storyboard?.instantiateViewController(withIdentifier: "SelectLocationViewController") as? SelectLocationViewController
            mSelectLocationVC?.delegate = self
        }         self.navigationController?.pushViewController(mSelectLocationVC!, animated: true)
}
```

**Comment by mykola-mokhnach** [comment]
Appium proxies all requests to https://github.com/facebook/WebDriverAgent/issues, so please report such issues there. There is nothing that can be done on our side.
