### ISSUE TITLE
How can I get uidump.xml file while running appium

### ISSUE THREAD

**Issue by Dan2712** [appium/appium#10855]
## The problem

     I'm doing secondary development over appium, and I need to execute "uiautomator dump" command to get the whole element with the uidump.xml. But when I run the appium, the port seems to be used by appium, and I cannot get it via executing command line. So if there is any way I can do via appium to get this. 
     I've tried the driver.executeScript, but seems not work, and the logs says nothing.
     Many thx! 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows
* Node.js version (unless using Appium.app|exe): 10.3.0
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

**Comment by mykola-mokhnach** [comment]
Try getPageSource()

Please use Appium forum for questions
