### ISSUE TITLE
[XCUITEST] class chain locator support for mobile gestures

### ISSUE THREAD

**Issue by derunewige** [appium/appium#10858]
## The problem

I am using the mobile gestures for xcuitesting to scroll to certain elements. As mentioned in the [docs](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios/ios-xctest-mobile-gestures.md) there are the params "name" and predicateString". 
I am able top map accessibility IDs or classnames to a predicate string, but is there any way to handle class chain locators?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Desktop OS/version used to run Appium: macOS 10.13.4
* Mobile platform/version under test: iOS 11.3.3
* Real device or emulator/simulator: both
* Appium CLI or Appium.app|exe: CLI

## Code To Reproduce Issue [ Good To Have ]

```
// add name of element to params
switch (locator.getRecognitionStrategy()) {
case IOS_PREDICATE:
	scrollParameter.put("predicateString", locator.getLocator());
	break;
case IOS_CLASSCHAIN:
	// TODO workaround for class chain scrolling
	break;
case CLASSNAME:
	scrollParameter.put("predicateString", "type = '" + locator.getLocator() + "'");
	break;
case ACCESSIBILITY:
	scrollParameter.put("name", locator.getLocator());
	break;
default:
	LOG.error("Unknown instance of locator. Could not do a scroll operation");
	return;
}

// add scroll direction to params
switch (searchStrategy) {
case DOWN:
	scrollParameter.put("direction", "down");
	break;
case UP:
	scrollParameter.put("direction", "up");
	break;
default:
	LOG.error("Unknown instance of searchStrategy. Could not do a scroll operation");
	return;
}

// execute scroll command
js.executeScript("mobile: scroll", scrollParameter);

```

**Comment by mykola-mokhnach** [comment]
Please create WebDriverAgent's requests for improvement in the proper place: https://github.com/facebook/WebDriverAgent/issues
