### ISSUE TITLE
 An unknown server-side error occurred while processing the command. Original error: '11.4' does not exist in the list of simctl SDKs. Only the following Simulator SDK versions are available on your system: 11.3, 10.3

### ISSUE THREAD

**Issue by rainedAllNight** [appium/appium#10857]
An unknown server-side error occurred while processing the command. Original error: '11.4' does not exist in the list of simctl SDKs. Only the following Simulator SDK versions are available on your system: 11.3, 10.3

i have this error message when i start session, i am use mobile device and the version is 11.4

**Comment by rainedAllNight** [comment]
![JSON Representation](https://user-images.githubusercontent.com/16357931/41283468-3f5e452e-6e69-11e8-8ea5-b569749dbd81.png)

**Comment by mykola-mokhnach** [comment]
You can only set platformVersion value to `11.3` or `10.3`. Otherise you need to setup the corresponding Simulator SDK from Xcode. Closed as duplicate

**Comment by mykola-mokhnach** [comment]
You must set the udid of the connected real device if you want to use it. Otherwise Appium will try to match a Simulator

**Comment by rainedAllNight** [comment]
i have been set the udid of the connected real device, it show me this message

An unknown server-side error occurred while processing the command. Original error: Unknown device or simulator UDID: '85ac411cb34b17f19250a5e7de827b101b0b06c6'

**Comment by mykola-mokhnach** [comment]
Make sure the device is visible to the system when connected. This can be checked in Xcode's Window->Devices And Simulators snap in

**Comment by rainedAllNight** [comment]
yes, the device is visible

**Comment by mykola-mokhnach** [comment]
Try `idevice_id -l`. If this device id is also visible there then attach the updated server log

**Comment by Owen-ET** [comment]
https://github.com/appium/appium/issues/11681

The problem has been solved here.
