### ISSUE TITLE
The target element can not be location correctly after scroll the view which contain the target view three times

### ISSUE THREAD

**Issue by robin-xl** [appium/appium#10851]
## The problem

Runing test on android real device with uia2,after sroll up list view for many times,find the target element by xpath `//*[contains(@content-desc,卖出)]`, the item view's location is `{"x":0,"y":0}` and size is `{"width":1080,"height":1920}`, this is the phone's location and size not this element's.

It look like uia2 not get the value correctly.

## Environment

* Appium version (or git revision) that exhibits the issue:1.8.2-beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macos 10.14-beta
* Node.js version (unless using Appium.app|exe):8.11.2
* Mobile platform/version under test: android/5.1.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

## Details

test hybrid app with uia2, in h5 page  uia2 treat h5 as native view, so i use this function to test h5 without chromedriver, this method work very well, But sometimes when i scroll h5 page it change to little strange,in uia2 side , the endpoint `/location` and `/size` return the wrong value, and the endpoint `/source` will not recognize dynamic h5 element

Is there someone can help without suggest change to chromedriver

## Link to Appium logs

[uia2 log](https://gist.github.com/robin-xl/45fe23e39153275e02d885f53e86d9e2)
[screencap](https://gist.github.com/robin-xl/3e6b314289b49e93e5116defa6ec0689)
[appium log](https://gist.github.com/robin-xl/75085cf37d6355b23789f991c34e97ce)
[/source value](https://gist.github.com/robin-xl/7ff4274a8c8b709f1a68c91572250d75)

**Comment by mykola-mokhnach** [comment]
This information is returned by UIA2 driver. You must either switch to webview context or report this issue to Google

**Comment by robin-xl** [comment]
I had read the resource code of uia2 service, it is a clever way to get page source by reflection, this problem can be reproduced below android M,  i think no one wish to fix it , so close this issue.
