### ISSUE TITLE
Does ActionChains or TouchAction work for iOS automation in Appium? 

### ISSUE THREAD

**Issue by vytran9599** [appium/appium#10860]
I currently have scripts for web browser automation for my web app, and I am trying to implement those scripts for mobile automation. Everything seems to work, but my code will exit where I implemented ‘ActionChains’ and I receive the error that “Method has not yet been implemented.” Is ActionChains not compatible with Appium?

Also, I tried using TouchAction in place of Action Chains, but it gives me errors such as

AttributeError: ‘int’ object has no attribute ‘id’

‘Str’ object has no attribute ‘id’

I saw somewhere that TouchAction only works in a native context. I am trying to test my web app on an iPad, so does TouchAction not support web context?

Mac Mini: High Sierra 
Appium: 1.8.2 beta

**Comment by mykola-mokhnach** [comment]
Yes TouchAction is only supported in native context.
