### ISSUE TITLE
undefined method `click' for #<Array:0x00007fada411ae50> (NoMethodError)

### ISSUE THREAD

**Issue by gratefulHeart** [appium/appium#10865]
`require 'rubygems'
require 'appium_lib'

caps = {}
caps["platformName"] = "iOS"
caps["deviceName"] = "iPhone Simulator"
caps["app"] = "/Users/gfy/Library/Developer/Xcode/DerivedData/CloudLearning-cygtqjghhxyefpcvmgfvkolvbhmd/Build/Products/Debug-iphonesimulator/CloudLearning_fz.app"
caps["automationName"] = "XCUITest"
caps["platfromVersion"] = "11.1"
caps["noReset"] = true
opts = {
    sauce_username: nil,
    server_url: "http://localhost:4723/wd/hub"
}
driver = Appium::Driver.new({caps: caps, appium_lib: opts}).start_driver

el1 = driver.find_elements(:accessibility_id, "确定")
el1.click
el2 = driver.find_elements(:xpath, "//XCUIElementTypeButton[@name=\"登录\"]")
el2.click
el3 = driver.find_elements(:xpath, "//XCUIElementTypeApplication[@name=\"云学习fz\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]")
el3.click
el4 = driver.find_elements(:xpath, "//XCUIElementTypeApplication[@name=\"云学习fz\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[3]/XCUIElementTypeCollectionView/XCUIElementTypeCell[2]/XCUIElementTypeOther")
el4.click
TouchAction
  .new
  .tap(x: 363, y: 186)
  .perform
    

driver.quit`

/Users/gfy/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/appium_lib_core-1.7.0/lib/appium_lib_core/common/base/bridge/w3c.rb:8: warning: already initialized constant Selenium::WebDriver::PointerActions::DEFAULT_MOVE_DURATION
/Users/gfy/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/common/interactions/pointer_actions.rb:21: warning: previous definition of DEFAULT_MOVE_DURATION was here
[DEPRECATION] Appium::Driver.new(opts) will not generate global driver by default.If you would like to generate the global driver dy default, please initialise driver with Appium::Driver.new(opts, true)
Traceback (most recent call last):
aa.rb:22:in `<main>': undefined method `click' for #<Array:0x00007fada411ae50> (NoMethodError)

**Comment by mykola-mokhnach** [comment]
the result of `driver.find_elements` is an array, so you cannot invoke `click` on it. Closed as not an issue.
