### ISSUE TITLE
uiautomator2 session on real device: 503 (Service Unavailable). 

### ISSUE THREAD

**Issue by yahman72** [appium/appium#10862]
## The problem

Appium fails to start the uiautomator2 session 
Error in the logs: 
`Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body`

After a couple of tries the session creation fails with HTTP code 503 (Service Unavailable).

## Environment

* Appium version (or git revision) that exhibits the issue: v1.7.2
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Windows 7
* Node.js version (unless using Appium.app|exe): v8.9.4
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Real Device (Samsung S7)
* Appium CLI or Appium.app|exe: CLI

## Details

Very similar to #10343, except that:
- rebooting the device does not help
- factory resetting the device does not help

The really odd thing is that when sending the GET request outside appium it gets a proper response i.e.
```
[12.06.2018 17:44:14 C:\git\]
> curl http://127.0.0.1:8200/wd/hub/status
{"sessionId":"SESSIONID","status":0,"value":"Status Invoked"}
[12.06.2018 17:44:16 C:\git\]
> curl http://127.0.0.1:8200/wd/hub/status
{"sessionId":"SESSIONID","status":0,"value":"Status Invoked"}
[12.06.2018 17:44:19 C:\git\]
> curl http://127.0.0.1:8200/wd/hub/status
{"sessionId":"SESSIONID","status":0,"value":"Status Invoked"}
```
BTW. same results with "127.0.0.1" and "localhost"

Any ideas why? 

## Link to Appium logs
https://gist.github.com/yahman72/2d05795c364fa35faf3fcd8bfde2e9bb

**Comment by mykola-mokhnach** [comment]
It is usually an issue in corporate networks if you have an external proxy running on the same port. Make sure your network is configured properly.

**Comment by yahman72** [comment]
In that case `curl` should also fail or not? They both have the same environment (variables) ...

**Comment by mykola-mokhnach** [comment]
most likely. Anyway the response you get is not coming from UIA2 server for sure

**Comment by yahman72** [comment]
thanks, that's something I can work with = then there's something odd with the network setup... 

curl works with the `http(s)_proxy` environment variables - not so sure about the node.js. Things might go wrong if node gets it's proxy settings from windows' "Internet Options".
