### ISSUE TITLE
Using Jenkins to trigger IOS test failed.

### ISSUE THREAD

**Issue by waitshang** [appium/appium#10866]
## The problem
I have made the IOS tests(with appium, testng, maven) running locally on real device well. But if failed when I use Jenkins to trigger maven test.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: MacOS 10.13.5 (17F77)
* Node.js version (unless using Appium.app|exe): 10.1.0
* Mobile platform/version under test: iPhone 7 iOS 10.3.3
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Details

I have listed two appium server log, first locally, second with Jenkins. 

## Link to Appium logs

[appium_server_locally.log](https://github.com/appium/appium/files/2096970/appium_server_locally.log)

[appium_server_withJenkins.log](https://github.com/appium/appium/files/2096972/appium_server_withJenkins.log)

## Log file for xcodebuild test

*For locally:
[Session-WebDriverAgentRunner-2018-06-13_141423-3IJfQm.log](https://github.com/appium/appium/files/2096997/Session-WebDriverAgentRunner-2018-06-13_141423-3IJfQm.log)

*For Jenkins:
[Session-WebDriverAgentRunner-2018-06-13_143132-rdVXli.log](https://github.com/appium/appium/files/2096998/Session-WebDriverAgentRunner-2018-06-13_143132-rdVXli.log)

**Comment by SrinivasanTarget** [comment]
@waitshang Nothing that appium could do. You should raise it in appium discuss forum.

**Comment by mykola-mokhnach** [comment]
>     NSLocalizedFailureReason = "The application does not have a valid signature.";
>     NSLocalizedRecoverySuggestion = "The application does not have a valid signature.";

The error there is pretty clear. You need to set up WDA signing properly.

**Comment by waitshang** [comment]
@mykola-mokhnach I wonder how the same file can be installed locally and no signing problem.

**Comment by mykola-mokhnach** [comment]
I had the similar issue previously and the problem was in keychain access. Jenkins agent is not a UI process, so it cannot access keychain to extract the private key needed for signing. I had to unlock the keychain explicitly with a terminal command prior to start signing.

**Comment by waitshang** [comment]
@mykola-mokhnach Could you give me some advice to unlock the keychain?

**Comment by waitshang** [comment]
@mykola-mokhnach I have done it. Just add shell "security unlock-keychain -p {loginpassword} ~/Library/Keychains/login.keychain-db" before. Thank you very much.
