### ISSUE TITLE
isdisplayed returns true but appium not able to select that element in dropdown

### ISSUE THREAD

**Issue by d-rai** [appium/appium#10867]
## The problem

isdisplayed returns true but appium does not able to select that element from dropdown. Because that element is not visible.

Please help me to solve this issue.

* Appium version : 1.2.5
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS High Sierra 10.13.5
* Xcode : 8.3.3

## Code To Reproduce Issue

public void selectAge(String ageValue) throws InterruptedException{
		driver.findElement(By.xpath("//XCUIElementTypeOther[@name='navigation']/XCUIElementTypeOther[29]")).click();
		Thread.sleep(2000);
		WebElement element = driver.findElementByAccessibilityId(ageValue);
		for (int i = 0; i < 35; i++) {
			if (element.isDisplayed()) {
				element.click();
				break;
			} else {
				(new TouchAction(driver)).press(228, 1138).moveTo(7, -151).release().perform();

			}
		}

**Comment by mykola-mokhnach** [comment]
Is the element inside webview? Can you attach the page source and the server log?

**Comment by d-rai** [comment]
Page source:

<?xml version="1.0" encoding="UTF-8"?><AppiumAUT><XCUIElementTypeApplication type="XCUIElementTypeApplication" name="XXXXXX" label="XXXXX" enabled="true" visible="true" x="0" y="0" width="1024" height="1366">
  <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="1024" height="1366">
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="1024" height="1366"/>
  </XCUIElementTypeOther>
  <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" visible="true" x="0" y="0" width="1024" height="1366">
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="1024" height="1366">
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="1024" height="1366">
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="1024" height="1366">
          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="1024" height="1366">
            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="1024" height="1366">
              <XCUIElementTypeWebView type="XCUIElementTypeWebView" enabled="true" visible="true" x="0" y="0" width="1024" height="1366">
                <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="1024" height="1366">
                  <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="0" height="0">
                    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="0" height="0">
                      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="1024" height="1366">
                        <XCUIElementTypeOther type="XCUIElementTypeOther" name="Canada Sales App" label="Canada Sales App" enabled="true" visible="true" x="0" y="0" width="1024" height="1366">
                          <XCUIElementTypeOther type="XCUIElementTypeOther" name="navigation" label="navigation" enabled="true" visible="true" x="0" y="0" width="1024" height="1366">
                            <XCUIElementTypeImage type="XCUIElementTypeImage" enabled="true" visible="false" x="0" y="137" width="60" height="38"/>
                            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="143" width="285" height="27">
                              <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="Home" name="Home" label="Home" enabled="true" visible="false" x="0" y="141" width="63" height="30"/>
                            </XCUIElementTypeOther>

                            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="76" y="887" width="271" height="48">
                              <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="Age" name="Age" label="Age" enabled="true" visible="true" x="76" y="899" width="34" height="24"/>
                              <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="*" name="*" label="*" enabled="true" visible="true" x="108" y="899" width="8" height="24"/>
                            </XCUIElementTypeOther>
                            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="76" y="933" width="267" height="50">
                              <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="Select" name="Select" label="Select" enabled="true" visible="true" x="89" y="944" width="51" height="25"/>
                            </XCUIElementTypeOther>
                            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="77" y="935" width="14" height="47"/>
                            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="308" y="935" width="35" height="47"/>
                            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="77" y="981" width="265" height="182">
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="&lt;1" label="&lt;1" enabled="true" visible="false" x="77" y="440" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="1" label="1" enabled="true" visible="false" x="77" y="487" width="265" height="48"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="2" label="2" enabled="true" visible="false" x="77" y="533" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="3" label="3" enabled="true" visible="false" x="77" y="580" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="4" label="4" enabled="true" visible="false" x="77" y="627" width="265" height="48"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="5" label="5" enabled="true" visible="false" x="77" y="673" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="6" label="6" enabled="true" visible="false" x="77" y="720" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="7" label="7" enabled="true" visible="false" x="77" y="767" width="265" height="48"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="8" label="8" enabled="true" visible="false" x="77" y="813" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="9" label="9" enabled="true" visible="false" x="77" y="860" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="10" label="10" enabled="true" visible="false" x="77" y="907" width="265" height="48"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="11" label="11" enabled="true" visible="true" x="77" y="953" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="12" label="12" enabled="true" visible="true" x="77" y="1000" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="13" label="13" enabled="true" visible="true" x="77" y="1047" width="265" height="48"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="14" label="14" enabled="true" visible="true" x="77" y="1093" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="15" label="15" enabled="true" visible="true" x="77" y="1140" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="16" label="16" enabled="true" visible="true" x="77" y="1187" width="265" height="48"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="17" label="17" enabled="true" visible="true" x="77" y="1233" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="18" label="18" enabled="true" visible="true" x="77" y="1280" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="19" label="19" enabled="true" visible="true" x="77" y="1327" width="265" height="48"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="20" label="20" enabled="true" visible="false" x="77" y="1373" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="21" label="21" enabled="true" visible="false" x="77" y="1420" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="22" label="22" enabled="true" visible="false" x="77" y="1467" width="265" height="48"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="23" label="23" enabled="true" visible="false" x="77" y="1513" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="24" label="24" enabled="true" visible="false" x="77" y="1560" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="25" label="25" enabled="true" visible="false" x="77" y="1607" width="265" height="48"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="26" label="26" enabled="true" visible="false" x="77" y="1653" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="27" label="27" enabled="true" visible="false" x="77" y="1700" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="28" label="28" enabled="true" visible="false" x="77" y="1747" width="265" height="48"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="29" label="29" enabled="true" visible="false" x="77" y="1793" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="30" label="30" enabled="true" visible="false" x="77" y="1840" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="31" label="31" enabled="true" visible="false" x="77" y="1887" width="265" height="48"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="32" label="32" enabled="true" visible="false" x="77" y="1933" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="33" label="33" enabled="true" visible="false" x="77" y="1980" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="34" label="34" enabled="true" visible="false" x="77" y="2027" width="265" height="48"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="35" label="35" enabled="true" visible="false" x="77" y="2073" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="36" label="36" enabled="true" visible="false" x="77" y="2120" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="37" label="37" enabled="true" visible="false" x="77" y="2167" width="265" height="48"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="38" label="38" enabled="true" visible="false" x="77" y="2213" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="39" label="39" enabled="true" visible="false" x="77" y="2260" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="40" label="40" enabled="true" visible="false" x="77" y="2307" width="265" height="48"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="41" label="41" enabled="true" visible="false" x="77" y="2353" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="42" label="42" enabled="true" visible="false" x="77" y="2400" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="43" label="43" enabled="true" visible="false" x="77" y="2447" width="265" height="48"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="44" label="44" enabled="true" visible="false" x="77" y="2493" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="45" label="45" enabled="true" visible="false" x="77" y="2540" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="46" label="46" enabled="true" visible="false" x="77" y="2587" width="265" height="48"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="47" label="47" enabled="true" visible="false" x="77" y="2633" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="48" label="48" enabled="true" visible="false" x="77" y="2680" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="49" label="49" enabled="true" visible="false" x="77" y="2727" width="265" height="48"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="50" label="50" enabled="true" visible="false" x="77" y="2773" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="51" label="51" enabled="true" visible="false" x="77" y="2820" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="52" label="52" enabled="true" visible="false" x="77" y="2867" width="265" height="48"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="53" label="53" enabled="true" visible="false" x="77" y="2913" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="54" label="54" enabled="true" visible="false" x="77" y="2960" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="55" label="55" enabled="true" visible="false" x="77" y="3007" width="265" height="48"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="56" label="56" enabled="true" visible="false" x="77" y="3053" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="57" label="57" enabled="true" visible="false" x="77" y="3100" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="58" label="58" enabled="true" visible="false" x="77" y="3147" width="265" height="48"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="59" label="59" enabled="true" visible="false" x="77" y="3193" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="60" label="60" enabled="true" visible="false" x="77" y="3240" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="61" label="61" enabled="true" visible="false" x="77" y="3287" width="265" height="48"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="62" label="62" enabled="true" visible="false" x="77" y="3333" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="63" label="63" enabled="true" visible="false" x="77" y="3380" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="64" label="64" enabled="true" visible="false" x="77" y="3427" width="265" height="48"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="65" label="65" enabled="true" visible="false" x="77" y="3473" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="66" label="66" enabled="true" visible="false" x="77" y="3520" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="67" label="67" enabled="true" visible="false" x="77" y="3567" width="265" height="48"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="68" label="68" enabled="true" visible="false" x="77" y="3613" width="265" height="49"/>
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="69" label="69" enabled="true" visible="false" x="77" y="3660" width="265" height="49"/>
                            </XCUIElementTypeOther>
                            <XCUIElementTypeButton type="XCUIElementTypeButton" name="Calculate" label="Calculate" enabled="true" visible="true" x="344" y="1020" width="336" height="58"/>
                          </XCUIElementTypeOther>


[appium-server-logs.txt](https://github.com/appium/appium/files/2097344/appium-server-logs.txt)

**Comment by mykola-mokhnach** [comment]
I assume you're trying to interact with a webview in native context. Not everything is going to work there....

**Comment by d-rai** [comment]
Hi @mykola-mokhnach 
is there any other way to solve this issue?

**Comment by mykola-mokhnach** [comment]
I don't know such. You can try to look for similar issues (there are such for sure) and ask their creators though.
