### ISSUE TITLE
Implicit wait doesn't work in 1.8.1 for UIAutomator2

### ISSUE THREAD

**Issue by olezhkalviv** [appium/appium#10879]
## The problem

Implicit wait doesn't work in 1.8.1 for UIAutomator2

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): NA
* Mobile platform/version under test: Android 6.0 
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: app

## Details

When I put 'Appium' automation name - implicit timeout is 60 sec.
`Wrapper.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(60);`
But after I put 'UIAutomator2' - it doesn't work - looks like implicit wait is 0 seconds because when screen starts loading after login it failed immediately like the element cannot be found.

## Link to Appium logs

[GIST](https://gist.github.com/olezhkalviv/181a3f6456081def649816ef605e32be)

## Code To Reproduce Issue [ Good To Have ]

NA

**Comment by mykola-mokhnach** [comment]
this is fixed in appium@beta. Closed as duplicate
