### ISSUE TITLE
[iOS] Appium unlock iOS real device

### ISSUE THREAD

**Issue by Gilbert1024** [appium/appium#10873]
## The problem
Hi folks, wondering if there is a way to unlock/wake an iOS device in iOS 11? What I am trying to do is to wake up an connected iOS real device and run tests on it. 

## Environment

* Appium version: 1.7+
* Mobile platform: iOS 11
* Real device

**Comment by mykola-mokhnach** [comment]
There are lock/unlock commands available since Appium 1.8.It is only possible to unlock a device if the lock is "simple", e.g. contains no security code.
