### ISSUE TITLE
Getting xcodebuild failed code 65 on real device

### ISSUE THREAD

**Issue by mishroom** [appium/appium#10872]
## The problem

I got Appium running on the iOS simulator but was not able to get it running on my physical iPhone, using the Appium XCUITest Driver Real Device Setup. Getting this error: 
The environment you requested was unavailable.
'An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.'

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: macOS High Sierra 10.13
* Node.js version (unless using Appium.app|exe): 8.11.1
* Mobile platform/version under test: iOS 11.4
* Real device or emulator/simulator: Real iPhone 7
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

https://gist.github.com/mishroom/44251573da173e95e31ad00541d8f43c

## Code To Reproduce Issue [ Good To Have ]

https://gist.github.com/mishroom/ff3b4a66228ded7d0233694dd3e16b25

**Comment by mykola-mokhnach** [comment]
The WDA bundle is not signed properly;

> [Xcode] 	No profiles for 'com.facebook.WebDriverAgentRunner' were found:  Xcode couldn't find any iOS App Development provisioning profiles matching 'com.facebook.WebDriverAgentRunner'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
> [Xcode] 	Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 11.4'

Closed as duplicate
