### ISSUE TITLE
Appium failed to find element in Android Oreo

### ISSUE THREAD

**Issue by sanojqa** [appium/appium#10870]
appium failed to find element in Android Oreo. 

I am using appium 1.7.2, Android Version: 8.0.0 and java-client: 5.0.4

**Comment by dpgraham** [comment]
@sanojqa Can you fill out the issue template.

**Comment by sanojqa** [comment]
@dpgraham @SrinivasanTarget 
Following are the details:

MAC OS X: macOs High Sierra (10.13.2)
Appium: 1.7.2
Android Version: 8.0.0
java-client: 5.0.4
Selenium java: 3.7.1
Selenium server: 3.7.1

Below are the scripts:
================
WebDriver driver;
		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Nexus 6");
		capabilities.setCapability(MobileCapabilityType.PLATFORM, "Android");
		capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "8.0.0");
		capabilities.setCapability("newCommandTimeout", 180);
		capabilities.setCapability("udid", "CVH7N16B14000835");
		capabilities.setCapability(MobileCapabilityType.APP, "/Users/Downloads/DMart.apk");
		try {
			driver = new AndroidDriver<WebElement>(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);
			Thread.sleep(4000);
			WebElement element = driver.findElement(By.id("in.dmart:id/more"));
			element.click();

		} catch (MalformedURLException e) {
			e.printStackTrace();
		} catch (Exception e) {
			e.printStackTrace();
		}

Getting error in finding the element for performing the action.

**Comment by sanojqa** [comment]
@dpgraham @SrinivasanTarget 
Following are the details:

MAC OS X: macOs High Sierra (10.13.2)
Appium: 1.7.2
Android Version: 8.0.0
java-client: 5.0.4
Selenium java: 3.7.1
Selenium server: 3.7.1

Below are the scripts:
================
WebDriver driver;
		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Nexus 6");
		capabilities.setCapability(MobileCapabilityType.PLATFORM, "Android");
		capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "8.0.0");
		capabilities.setCapability("newCommandTimeout", 180);
		capabilities.setCapability("udid", "CVH7N16B14000835");
		capabilities.setCapability(MobileCapabilityType.APP, "/Users/Downloads/DMart.apk");
		try {
			driver = new AndroidDriver<WebElement>(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);
			Thread.sleep(4000);
			WebElement element = driver.findElement(By.id("in.dmart:id/more"));
			element.click();

		} catch (MalformedURLException e) {
			e.printStackTrace();
		} catch (Exception e) {
			e.printStackTrace();
		}

Getting error in finding the element for performing the action.

**Comment by vikramvi** [comment]
@sanojqa Can you please provide the full Appium server logs?  https://www.youtube.com/watch?v=mOkgAxIWdGg&list=PLhr2WKNPXcZOmOf1k2aqkbMZwnZb2pSZL&index=6

Issue temple clearly asks for appium server log without it; it's hard to debug.

**Comment by sanojqa** [comment]
@vikramvi Now its running and finding elements. I have added the capability 
capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME,AutomationName.ANDROID_UIAUTOMATOR2); to my code.

**Comment by saikrishna321** [comment]
Closing as its resolved.
