### ISSUE TITLE
appium server is disabling the microphone input in android device.

### ISSUE THREAD

**Issue by sonkusare** [appium/appium#10878]
## The problem

Appium server is disabling the microphone input in android device, when device is connected with the 
 appium server and i m trying to send wave file device is rejecting the input and for cross verification i tried manually saying the word the device is not at all listening.

## Environment
android 6.0.1

* Appium version 1.8.0v
* 
* Desktop OS/version used to run Appium: win 7 64 bit
* Node.js 
* Real device

**Comment by mykola-mokhnach** [comment]
The issue description is not helpful. Please provide more details.

**Comment by mykola-mokhnach** [comment]
Does it work if apiium server is not running? What is in the logcat output?
