### ISSUE TITLE
Appium scripts are not working when we comment few lines 

### ISSUE THREAD

**Issue by Deepi26** [appium/appium#10875]
#Tools
1)Appiim version :1.7.2
2)Eclipse oxygen 
3)Test NG Framework 

#The problem 
I am trying to run automated scripts in real mobile device but in the following code if i remove some piece of code the appium is not executing other scripts ,it is skipping the some id's.I am new to appium ,some please help me.....Thanks in Advance 

#code 

package test;
		
		import java.io.File;
		import java.net.MalformedURLException;
		import java.net.URL;
		import java.util.concurrent.TimeUnit;
		
		import org.openqa.selenium.By;
		
		import org.openqa.selenium.remote.DesiredCapabilities;
		import org.openqa.selenium.support.ui.ExpectedConditions;
		import org.openqa.selenium.support.ui.WebDriverWait;
		import org.testng.annotations.AfterTest;
		import org.testng.annotations.BeforeTest;
		import org.testng.annotations.Test;

import io.appium.java_client.AppiumDriver;
import io.appium.java_client.android.AndroidDriver;
		import io.appium.java_client.remote.MobileCapabilityType;
		import io.appium.java_client.service.local.AppiumDriverLocalService;
		
		public class Settings {
			
			AndroidDriver driver; 
			  AppiumDriverLocalService appiumService;
			    String appiumServiceUrl;
			
		@BeforeTest
		public void setUp() throws MalformedURLException {
			
			//Starting appium server
			appiumService = AppiumDriverLocalService.buildDefaultService();
			appiumService.start();
		 appiumServiceUrl = appiumService.getUrl().toString();
		 System.out.println("Appium Service Address : - "+ appiumServiceUrl);
			
		 //Device capabilities to launch mysa app
			  File app= new File("C:\\Users\\ANAGAGUNADeepika\\Downloads\\MySA_7.3.1_11thJune.apk");
				DesiredCapabilities capabilities= new DesiredCapabilities();
				capabilities.setCapability("deviceName", "Android");
				capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "7.1.2");
				capabilities.setCapability("platformName", "Android");
				capabilities.setCapability("automationName", "uiautomator2");
				capabilities.setCapability("app", app.getAbsolutePath());
				//capabilities.setCapability("testdroid_testTimeout", 1200);
				capabilities.setCapability("--session-override", true);
				
				
				
		   driver =  new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"),capabilities);
		   driver.manage().timeouts().implicitlyWait(240, TimeUnit.SECONDS);
		   WebDriverWait wait = new WebDriverWait(driver, 60);
		   wait.until(ExpectedConditions.elementToBeClickable(By.className("android.widget.FrameLayout")));
		
				 }
		
		
		
		@Test
		public void A1a_Login() {
			
			
			driver.findElement(By.xpath("//android.widget.EditText[contains(@resource-id,'uname')]")).sendKeys("nagagua6@in.ibm.com");
			new WebDriverWait(driver, 30).until(ExpectedConditions.presenceOfElementLocated(By.xpath("//android.widget.EditText[contains(@resource-id,'pwd')]")));
		 
		 driver.findElement(By.xpath("//android.widget.EditText[contains(@resource-id,'pwd')]")).sendKeys("Subha777#");
		 
		  driver.findElement(By.xpath("//android.widget.Button[contains(@resource-id,'login_button')]")).click();
		  
		  
		  new WebDriverWait(driver, 60).until(ExpectedConditions.presenceOfElementLocated(By.xpath("//android.widget.Button[contains(@resource-id,'com.ibm.cio.be.mysa:id/cancel_button')]")));
			
		  driver.findElement(By.xpath("//android.widget.Button[contains(@resource-id,'com.ibm.cio.be.mysa:id/cancel_button')]")).click();
		  
		  new WebDriverWait(driver, 60).until(ExpectedConditions.presenceOfElementLocated(By.xpath("//android.widget.Button[contains(@resource-id,'FPViewBtn-3')]")));
		  driver.findElement(By.xpath("//android.widget.Button[contains(@resource-id,'FPViewBtn-3')]")).click();
		  
		  new WebDriverWait(driver, 60).until(ExpectedConditions.presenceOfElementLocated(By.xpath("//android.widget.Button[contains(@text,'3')]")));
		  driver.findElement(By.xpath("//android.widget.Button[contains(@text,'3')]")).click();
		 
		  new WebDriverWait(driver, 60).until(ExpectedConditions.presenceOfElementLocated(By.xpath("//android.widget.Button[contains(@text,'back to find an Object filter page')]")));
		  driver.findElement(By.xpath("//android.widget.Button[contains(@text,'back to find an Object filter page')]")).click();
		 
		  new WebDriverWait(driver, 60).until(ExpectedConditions.presenceOfElementLocated(By.xpath("//android.widget.Button[contains(@resource-id,'FPFilterBtn-6')]")));
			
			driver.findElement(By.xpath("//android.widget.Button[contains(@resource-id,'FPFilterBtn-6')]")).click();

		  
		  new WebDriverWait(driver, 60).until(ExpectedConditions.presenceOfElementLocated(By.xpath("//android.widget.Button[contains(@resource-id,'menu')]")));
		 
		  driver.findElement(By.xpath("//android.widget.Button[contains(@resource-id,'menu')]")).click();
		  
		  
		  
		  new WebDriverWait(driver, 120).until(ExpectedConditions.presenceOfElementLocated(By.xpath("//android.view.View[contains(@text,'Settings')]")));
			 
		  driver.findElement(By.xpath("//android.view.View[contains(@text,'Settings')]")).click();
		    
		  driver.findElement(By.xpath("//android.view.View[contains(@resource-id,'terms')]")).click();
		  
		  driver.findElement(By.xpath("//android.widget.Button[contains(@text,'')]")).click();
		  
		  driver.findElement(By.xpath("//android.view.View[contains(@resource-id,'help')]")).click();
		  
		  driver.findElement(By.xpath("//android.widget.Button[contains(@text,'Cancel')]")).click();
		  
		}
		
		
		
		@AfterTest
		public void Logout() {
		
			driver.quit();
		}
		
		
		}

**Comment by mykola-mokhnach** [comment]
Please use appium forum to ask questions

**Comment by Deepi26** [comment]
Can u pls explain where may the issue in my code ?
