### ISSUE TITLE
Xcuitest Connection Refused errors after trying to dismiss device alerts

### ISSUE THREAD

**Issue by tsibiski** [appium/appium#10887]
## The problem

There does not seem to be a way to boolean-check if a device alert is present before trying to dismiss it. I've searched high and low for that functionality and come up empty. So instead I've wrapped "self.driver.switch_to.alert.accept()" in a try catch, and occasionally call it to dismiss any alerts that happen to have appeared.

The result when no alert is present it this error "An attempt was made to operate on a modal dialog when one was not open.", which makes sense. But after that friendlier error happens enough times (sometimes it only takes one time) all future attempts to interact with device alerts throw this error "<urlopen error [Errno 61] Connection refused". This error occurs no matter what when trying to interact with device alerts, or trying to take screenshots.

An important note is that I only use Appium to load the .ipa onto a device, dismiss device alerts, and take screenshots. My python scripts are then sending commands over socket to the app, which has its own test framework embedded. So appium is not trying to do anything else besides what is described above.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable): This has occurred forever for me, but has gotten worse recently. Recently as in the last few days, and I've had 1.8.1 since it was released.
* Desktop OS/version used to run Appium: Mac OS 10.12.6
* Node.js version (unless using Appium.app|exe): v9.11.1
* Mobile platform/version under test: iPhone 11.0.3
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

https://gist.github.com/tsibiski/cc155eb9ecac9994b75bd6fe5cd014f2

## Code To Reproduce Issue [ Good To Have ]

Simply calling self.driver.switch_to.alert.accept() inside of a try catch when alerts are not present. It is variable how many times it takes to cause this issue. I am not even sure if the fact that this error is being thrown is causing the issue. It may be a variable time-based issue, where the appium driver eventually gets into this state after a certain amount of time.

**Comment by tsibiski** [comment]
I should also mention that I have "androidInstallTimeout" set to 99,999 ms. These device-dismissal commands happen ever 20 seconds, so it should not be a case of an expected timeout by appium.

**Comment by mykola-mokhnach** [comment]
I don't observe any errors in the attached server log. Also, it might be useful to see the device log. 
In general "Connection refused" error means that WebDriverAgent just stops responding to Appium requests, so this is most likely a third party issue.

**Comment by tsibiski** [comment]
Gotchya. I will get a better log, and gist it. And also will try and grab the device log. If needed, I will report the issue in the WebDriverAgent github.
