### ISSUE TITLE
Got Response with status 200 Failed to launch status 13 Appium,

### ISSUE THREAD

**Issue by chanu519** [appium/appium#10889]
I am Using the Appium currently to captures the Xpaths for all the elements for the automation scripts 

I have the Xcode 9.2 installed with Appium 1.4 running on server 1.7.1 

here are the capabilities that I have mentioned in the inspector session 
{
  "deviceName": "iPhone 7 Plus",
  "platformName": "iOS",
  "bundleId": "blueshieldca.com",
  "platformVersion": "11.2",
  "app": "Users/cgarik01/Library/Developer/Xcode/DerivedData/CEM-hfvrazpzytupapbxtpunclczmslx/Build/Products/CEM_Debug-iphonesimulator/CEM.app"
}

When I start the inspector session the Appium server is installing the WDA session and also the app from the location that I have specified. But the problem here is it is not able to open the app for me to capture the xpath's 

Here are the server logs:

[info] [Appium] Welcome to Appium v1.7.2
[info] [Appium] Appium REST http interface listener started on 0.0.0.0:4723[info] [HTTP] --> GET /wd/hub/sessions {}
[debug] [MJSONWP] Calling AppiumDriver.getSessions() with args: []
[debug] [MJSONWP] Responding to client with driver.getSessions() result: []
[info] [HTTP] <-- GET /wd/hub/sessions 200 9 ms - 29 [info] [HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"Users/cgarik01/Library/Developer/Xcode/DerivedData/CEM-hfvrazpzytupapbxtpunclczmslx/Build/Products/CEM_Debug-iphonesimulator/CEM.app","bundleId":"com.blueshieldca.com-npe","deviceName":"iPhone 7 Plus","platformName":"iOS","platformVersion":"11.2","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"Users/cgarik01/Library/Developer/Xcode/DerivedData/CEM-hfvrazpzytupapbxtpunclczmslx/Build/Products/CEM_Debug-iphonesimulator/CEM.app","bundleId":"com.blueshieldca.com-npe","deviceName":"iPhone 7 Plus","platformName":"iOS","platformVersion":"11.2","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1529094359790 (13:25:59 GMT-0700 (PDT))
[info] [Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[info] [Appium] Creating new XCUITestDriver (v2.64.0) session
[info] [Appium] Capabilities:
[info] [Appium]   app: Users/cgarik01/Library/Developer/Xcode/DerivedData/CEM-hfvrazpzytupapbxtpunclczmslx/Build/Products/CEM_Debug-iphonesimulator/CEM.app
[info] [Appium]   bundleId: com.blueshieldca.com-npe
[info] [Appium]   deviceName: iPhone 7 Plus
[info] [Appium]   platformName: iOS
[info] [Appium]   platformVersion: 11.2
[info] [Appium]   newCommandTimeout: 0
[info] [Appium]   connectHardwareKeyboard: true
[info] [BaseDriver] Session created with session id: e2266c74-0d2b-4ae1-a507-e9c215cfee93
[debug] [XCUITest] Current user: 'cgarik01'
[debug] [XCUITest] Unable to get version of libimobiledevice: Command 'brew' not found. Is it installed?[debug] [XCUITest] Xcode version set to '9.2' (tools v9.0.0.0.1.1504363082)[debug] [XCUITest] iOS SDK Version set to '11.2'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1529094365931 (13:26:05 GMT-0700 (PDT))[info] [iOSSim] Constructing iOS simulator for Xcode version 9.2 with udid '4007D8F9-6FA9-40EA-ABB6-D49F2B33BD36'
[info] [XCUITest] Determining device to run tests on: udid: '4007D8F9-6FA9-40EA-ABB6-D49F2B33BD36', real device: false
[info] [BaseDriver] Using local app 'Users/cgarik01/Library/Developer/Xcode/DerivedData/CEM-hfvrazpzytupapbxtpunclczmslx/Build/Products/CEM_Debug-iphonesimulator/CEM.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1529094366713 (13:26:06 GMT-0700 (PDT))
[debug] [XCUITest] Checking whether app 'Users/cgarik01/Library/Developer/Xcode/DerivedData/CEM-hfvrazpzytupapbxtpunclczmslx/Build/Products/CEM_Debug-iphonesimulator/CEM.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [BaseDriver] Event 'resetStarted' logged at 1529094366713 (13:26:06 GMT-0700 (PDT))
[info] [XCUITest] Not scrubbing third party app in anticipation of uninstall
[debug] [BaseDriver] Event 'resetComplete' logged at 1529094366809 (13:26:06 GMT-0700 (PDT))
[warn] [XCUITest] Continuing without capturing logs: iOS Simulator with udid 4007D8F9-6FA9-40EA-ABB6-D49F2B33BD36 is not running
[info] [XCUITest] Setting up simulator
[debug] [iOS] No reason to set locale
[debug] [iOS] No iOS / app preferences to set[debug] [iOSSim] Matched 1 Simulator cache item for cleanup: /Users/cgarik01/Library/Developer/CoreSimulator/Devices/4007D8F9-6FA9-40EA-ABB6-D49F2B33BD36/data/Library/Caches/com.apple.mobile.installd.staging
[debug] [iOSSim] Setting common Simulator preferences to {"ConnectHardwareKeyboard":true}
[debug] [iOSSim] Updated 4007D8F9-6FA9-40EA-ABB6-D49F2B33BD36 Simulator preferences at '/Users/cgarik01/Library/Preferences/com.apple.iphonesimulator.plist' with {"ConnectHardwareKeyboard":true}[debug] [iOSSim] The count of running Simulator UI client instances is 0
[info] [iOSSim] Booting Simulator with UDID 4007D8F9-6FA9-40EA-ABB6-D49F2B33BD36...[info] [iOSSim] Starting Simulator UI with command: open -Fn /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID 4007D8F9-6FA9-40EA-ABB6-D49F2B33BD36 -ConnectHardwareKeyboard 1[info] [iOSSim] Simulator with UDID 4007D8F9-6FA9-40EA-ABB6-D49F2B33BD36 booted in 35 seconds
[debug] [BaseDriver] Event 'simStarted' logged at 1529094402273 (13:26:42 GMT-0700 (PDT))[debug] [XCUITest] Starting log capture for iOS Simulator with udid '4007D8F9-6FA9-40EA-ABB6-D49F2B33BD36', using 'xcrun simctl spawn 4007D8F9-6FA9-40EA-ABB6-D49F2B33BD36 log stream --style compact'[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1529094402953 (13:26:42 GMT-0700 (PDT))[debug] [XCUITest] Installing 'Users/cgarik01/Library/Developer/Xcode/DerivedData/CEM-hfvrazpzytupapbxtpunclczmslx/Build/Products/CEM_Debug-iphonesimulator/CEM.app' on Simulator with UUID '4007D8F9-6FA9-40EA-ABB6-D49F2B33BD36'...[debug] [XCUITest] The app has been installed successfully.
[debug] [BaseDriver] Event 'appInstalled' logged at 1529094408623 (13:26:48 GMT-0700 (PDT))
[info] [XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[info] [XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[debug] [XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] WDA is not listening at 'http://localhost:8100/'
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1529094408864 (13:26:48 GMT-0700 (PDT))
[info] [XCUITest] Launching WebDriverAgent on the device[debug] [XCUITest] Killing running processes 'xcodebuild.*4007D8F9-6FA9-40EA-ABB6-D49F2B33BD36, iproxy 8100, 4007D8F9-6FA9-40EA-ABB6-D49F2B33BD36.*XCTRunner' for the device 4007D8F9-6FA9-40EA-ABB6-D49F2B33BD36...
[debug] [XCUITest] 'pgrep -nif xcodebuild.*4007D8F9-6FA9-40EA-ABB6-D49F2B33BD36' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] 'pgrep -nif iproxy 8100' didn't detect any matching processes. Return code: 1[debug] [XCUITest] 'pgrep -nif 4007D8F9-6FA9-40EA-ABB6-D49F2B33BD36.*XCTRunner' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] Using Xcode 9.2, so fixing WDA codebase
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=4007D8F9-6FA9-40EA-ABB6-D49F2B33BD36 IPHONEOS_DEPLOYMENT_TARGET=11.2' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged. To see xcode logging, use 'showXcodeLog' desired capability[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [XCUITest] Log file for xcodebuild test: /var/folders/lr/979z4nz57c9ch884mp0qdcl80000gv/T/com.apple.dt.XCTest/IDETestRunSession-FD7E3DBD-7043-47A7-9080-ACF7CC7A6AAD/WebDriverAgentRunner-6D564F2A-0FD5-413D-87F7-6AD967D0E712/Session-WebDriverAgentRunner-2018-06-15_132659-Pez3Ew.log[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"11.2\",\n      \"sdkVersion\" : \"11.2\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"11.2\",\n      \"ip\" : \"10.5.51.20\"\n    },\n    \"build\" : {\n      \"time\" : \"Jun 11 2018 10:02:34\"\n    }\n  },\n  \"sessionId\" : \"0C0A4A2B-1FCE-4BD3-B4BD-179007F490AD\",\n  \"status\" : 0\n}"
[debug] [XCUITest] WebDriverAgent running on ip '10.5.51.20'
[debug] [XCUITest] WebDriverAgent successfully started after 24745ms
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1529094433909 (13:27:13 GMT-0700 (PDT))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.blueshieldca.com-npe","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}[debug] [JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.blueshieldca.com-npe application","sessionId":"0C0A4A2B-1FCE-4BD3-B4BD-179007F490AD","status":13}
[debug] [XCUITest] Failed to create WDA session. Retrying...[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1529094616735 (13:30:16 GMT-0700 (PDT))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.blueshieldca.com-npe","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}[debug] [JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.blueshieldca.com-npe application","sessionId":"0C0A4A2B-1FCE-4BD3-B4BD-179007F490AD","status":13}
[debug] [XCUITest] Failed to create WDA session. Retrying...[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1529094799040 (13:33:19 GMT-0700 (PDT))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.blueshieldca.com-npe","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}[info] [HTTP] <-- POST /wd/hub/session - - ms - - 
[info] [HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"Users/cgarik01/Library/Developer/Xcode/DerivedData/CEM-hfvrazpzytupapbxtpunclczmslx/Build/Products/CEM_Debug-iphonesimulator/CEM.app","bundleId":"com.blueshieldca.com-npe","deviceName":"iPhone 7 Plus","platformName":"iOS","platformVersion":"11.2","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"Users/cgarik01/Library/Developer/Xcode/DerivedData/CEM-hfvrazpzytupapbxtpunclczmslx/Build/Products/CEM_Debug-iphonesimulator/CEM.app","bundleId":"com.blueshieldca.com-npe","deviceName":"iPhone 7 Plus","platformName":"iOS","platformVersion":"11.2","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1529094960092 (13:36:00 GMT-0700 (PDT))
[info] [Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[info] [Appium] Creating new XCUITestDriver (v2.64.0) session
[info] [Appium] Capabilities:
[info] [Appium]   app: Users/cgarik01/Library/Developer/Xcode/DerivedData/CEM-hfvrazpzytupapbxtpunclczmslx/Build/Products/CEM_Debug-iphonesimulator/CEM.app
[info] [Appium]   bundleId: com.blueshieldca.com-npe
[info] [Appium]   deviceName: iPhone 7 Plus
[info] [Appium]   platformName: iOS
[info] [Appium]   platformVersion: 11.2
[info] [Appium]   newCommandTimeout: 0
[info] [Appium]   connectHardwareKeyboard: true
[info] [BaseDriver] Session created with session id: 452c7442-0ddb-44c1-9b58-a4b0af141868
[debug] [XCUITest] Current user: 'cgarik01'
[debug] [XCUITest] Unable to get version of libimobiledevice: Command 'brew' not found. Is it installed?
[debug] [XCUITest] Xcode version set to '9.2' (tools v9.0.0.0.1.1504363082)
[debug] [XCUITest] iOS SDK Version set to '11.2'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1529094960237 (13:36:00 GMT-0700 (PDT))[info] [iOSSim] Constructing iOS simulator for Xcode version 9.2 with udid '4007D8F9-6FA9-40EA-ABB6-D49F2B33BD36'
[info] [XCUITest] Determining device to run tests on: udid: '4007D8F9-6FA9-40EA-ABB6-D49F2B33BD36', real device: false
[info] [BaseDriver] Using local app 'Users/cgarik01/Library/Developer/Xcode/DerivedData/CEM-hfvrazpzytupapbxtpunclczmslx/Build/Products/CEM_Debug-iphonesimulator/CEM.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1529094960520 (13:36:00 GMT-0700 (PDT))
[debug] [XCUITest] Checking whether app 'Users/cgarik01/Library/Developer/Xcode/DerivedData/CEM-hfvrazpzytupapbxtpunclczmslx/Build/Products/CEM_Debug-iphonesimulator/CEM.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [BaseDriver] Event 'resetStarted' logged at 1529094960521 (13:36:00 GMT-0700 (PDT))
[info] [XCUITest] Not scrubbing third party app in anticipation of uninstall
[debug] [BaseDriver] Event 'resetComplete' logged at 1529094960703 (13:36:00 GMT-0700 (PDT))[debug] [XCUITest] Starting log capture for iOS Simulator with udid '4007D8F9-6FA9-40EA-ABB6-D49F2B33BD36', using 'xcrun simctl spawn 4007D8F9-6FA9-40EA-ABB6-D49F2B33BD36 log stream --style compact'
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1529094961007 (13:36:01 GMT-0700 (PDT))
[info] [XCUITest] Setting up simulator
[debug] [iOS] No reason to set locale
[debug] [iOS] No iOS / app preferences to set
[debug] [iOSSim] Matched 1 Simulator cache item for cleanup: /Users/cgarik01/Library/Developer/CoreSimulator/Devices/4007D8F9-6FA9-40EA-ABB6-D49F2B33BD36/data/Library/Caches/com.apple.mobile.installd.staging
[debug] [iOSSim] Setting common Simulator preferences to {"ConnectHardwareKeyboard":true}[debug] [iOSSim] Updated 4007D8F9-6FA9-40EA-ABB6-D49F2B33BD36 Simulator preferences at '/Users/cgarik01/Library/Preferences/com.apple.iphonesimulator.plist' with {"ConnectHardwareKeyboard":true}[debug] [iOSSim] The count of running Simulator UI client instances is 1
[info] [iOSSim] Both Simulator with UDID 4007D8F9-6FA9-40EA-ABB6-D49F2B33BD36 and the UI client are currently running
[debug] [BaseDriver] Event 'simStarted' logged at 1529094961464 (13:36:01 GMT-0700 (PDT))[debug] [XCUITest] Installing 'Users/cgarik01/Library/Developer/Xcode/DerivedData/CEM-hfvrazpzytupapbxtpunclczmslx/Build/Products/CEM_Debug-iphonesimulator/CEM.app' on Simulator with UUID '4007D8F9-6FA9-40EA-ABB6-D49F2B33BD36'...[debug] [XCUITest] The app has been installed successfully.
[debug] [BaseDriver] Event 'appInstalled' logged at 1529094967420 (13:36:07 GMT-0700 (PDT))[debug] [JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.blueshieldca.com-npe application","sessionId":"0C0A4A2B-1FCE-4BD3-B4BD-179007F490AD","status":13}
[debug] [XCUITest] Failed to create WDA session. Retrying...[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1529094981325 (13:36:21 GMT-0700 (PDT))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.blueshieldca.com-npe","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}[debug] [JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.blueshieldca.com-npe application","sessionId":"0C0A4A2B-1FCE-4BD3-B4BD-179007F490AD","status":13}
[debug] [XCUITest] Failed to create WDA session. Retrying...[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1529095163611 (13:39:23 GMT-0700 (PDT))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.blueshieldca.com-npe","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}[debug] [JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.blueshieldca.com-npe application","sessionId":"0C0A4A2B-1FCE-4BD3-B4BD-179007F490AD","status":13}
[debug] [XCUITest] Failed to create WDA session. Retrying...[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1529095345886 (13:42:25 GMT-0700 (PDT))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.blueshieldca.com-npe","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}[info] [HTTP] --> DELETE /wd/hub/session {}
[debug] [HTTP] No route found. Setting content type to 'text/plain'
[info] [HTTP] <-- DELETE /wd/hub/session 404 4 ms - 57 [info] [HTTP] --> GET /wd/hub/sessions {}
[debug] [MJSONWP] Calling AppiumDriver.getSessions() with args: []
[debug] [MJSONWP] Responding to client with driver.getSessions() result: []
[info] [HTTP] <-- GET /wd/hub/sessions 200 3 ms - 40 [debug] [JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.blueshieldca.com-npe application","sessionId":"0C0A4A2B-1FCE-4BD3-B4BD-179007F490AD","status":13}
[debug] [XCUITest] Failed to create WDA session. Retrying...[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1529095528208 (13:45:28 GMT-0700 (PDT))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.blueshieldca.com-npe","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}[info] [HTTP] <-- POST /wd/hub/session - - ms - - 
[info] [HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"Users/cgarik01/Library/Developer/Xcode/DerivedData/CEM-hfvrazpzytupapbxtpunclczmslx/Build/Products/CEM_Debug-iphonesimulator/CEM.app","bundleId":"com.blueshieldca.com-npe","deviceName":"iPhone 7 Plus","platformName":"iOS","platformVersion":"11.2","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"Users/cgarik01/Library/Developer/Xcode/DerivedData/CEM-hfvrazpzytupapbxtpunclczmslx/Build/Products/CEM_Debug-iphonesimulator/CEM.app","bundleId":"com.blueshieldca.com-npe","deviceName":"iPhone 7 Plus","platformName":"iOS","platformVersion":"11.2","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1529095560146 (13:46:00 GMT-0700 (PDT))
[info] [Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[info] [Appium] Creating new XCUITestDriver (v2.64.0) session
[info] [Appium] Capabilities:
[info] [Appium]   app: Users/cgarik01/Library/Developer/Xcode/DerivedData/CEM-hfvrazpzytupapbxtpunclczmslx/Build/Products/CEM_Debug-iphonesimulator/CEM.app
[info] [Appium]   bundleId: com.blueshieldca.com-npe
[info] [Appium]   deviceName: iPhone 7 Plus
[info] [Appium]   platformName: iOS
[info] [Appium]   platformVersion: 11.2
[info] [Appium]   newCommandTimeout: 0
[info] [Appium]   connectHardwareKeyboard: true
[info] [BaseDriver] Session created with session id: 71646fdf-96b8-499b-b7c2-d955da8d893e
[debug] [XCUITest] Current user: 'cgarik01'
[debug] [XCUITest] Unable to get version of libimobiledevice: Command 'brew' not found. Is it installed?
[debug] [XCUITest] Xcode version set to '9.2' (tools v9.0.0.0.1.1504363082)
[debug] [XCUITest] iOS SDK Version set to '11.2'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1529095560282 (13:46:00 GMT-0700 (PDT))[info] [iOSSim] Constructing iOS simulator for Xcode version 9.2 with udid '4007D8F9-6FA9-40EA-ABB6-D49F2B33BD36'
[info] [XCUITest] Determining device to run tests on: udid: '4007D8F9-6FA9-40EA-ABB6-D49F2B33BD36', real device: false
[info] [BaseDriver] Using local app 'Users/cgarik01/Library/Developer/Xcode/DerivedData/CEM-hfvrazpzytupapbxtpunclczmslx/Build/Products/CEM_Debug-iphonesimulator/CEM.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1529095560614 (13:46:00 GMT-0700 (PDT))
[debug] [XCUITest] Checking whether app 'Users/cgarik01/Library/Developer/Xcode/DerivedData/CEM-hfvrazpzytupapbxtpunclczmslx/Build/Products/CEM_Debug-iphonesimulator/CEM.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [BaseDriver] Event 'resetStarted' logged at 1529095560620 (13:46:00 GMT-0700 (PDT))
[info] [XCUITest] Not scrubbing third party app in anticipation of uninstall
[debug] [BaseDriver] Event 'resetComplete' logged at 1529095560812 (13:46:00 GMT-0700 (PDT))[debug] [XCUITest] Starting log capture for iOS Simulator with udid '4007D8F9-6FA9-40EA-ABB6-D49F2B33BD36', using 'xcrun simctl spawn 4007D8F9-6FA9-40EA-ABB6-D49F2B33BD36 log stream --style compact'[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1529095561246 (13:46:01 GMT-0700 (PDT))
[info] [XCUITest] Setting up simulator
[debug] [iOS] No reason to set locale
[debug] [iOS] No iOS / app preferences to set
[debug] [iOSSim] Matched 1 Simulator cache item for cleanup: /Users/cgarik01/Library/Developer/CoreSimulator/Devices/4007D8F9-6FA9-40EA-ABB6-D49F2B33BD36/data/Library/Caches/com.apple.mobile.installd.staging
[debug] [iOSSim] Setting common Simulator preferences to {"ConnectHardwareKeyboard":true}
[debug] [iOSSim] Updated 4007D8F9-6FA9-40EA-ABB6-D49F2B33BD36 Simulator preferences at '/Users/cgarik01/Library/Preferences/com.apple.iphonesimulator.plist' with {"ConnectHardwareKeyboard":true}[debug] [iOSSim] The count of running Simulator UI client instances is 1
[info] [iOSSim] Both Simulator with UDID 4007D8F9-6FA9-40EA-ABB6-D49F2B33BD36 and the UI client are currently running
[debug] [BaseDriver] Event 'simStarted' logged at 1529095561751 (13:46:01 GMT-0700 (PDT))[debug] [XCUITest] Installing 'Users/cgarik01/Library/Developer/Xcode/DerivedData/CEM-hfvrazpzytupapbxtpunclczmslx/Build/Products/CEM_Debug-iphonesimulator/CEM.app' on Simulator with UUID '4007D8F9-6FA9-40EA-ABB6-D49F2B33BD36'...[debug] [XCUITest] The app has been installed successfully.
[debug] [BaseDriver] Event 'appInstalled' logged at 1529095564246 (13:46:04 GMT-0700 (PDT))

Can some one please help me on this.

Thanks,
Chanakya.

**Comment by mykola-mokhnach** [comment]
> [info] [HTTP] <-- GET /wd/hub/sessions 200 3 ms - 40 [debug] [JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.blueshieldca.com-npe application","sessionId":"0C0A4A2B-1FCE-4BD3-B4BD-179007F490AD","status":13}

This error means that WDA cannot launch the given app. Are you able to start it manually?

**Comment by mykola-mokhnach** [comment]
Can you also attach the device log? (it can be enabled by `showIOSLog` capability)
