### ISSUE TITLE
It is extremely slow on ios 10.1.1

### ISSUE THREAD

**Issue by robin-xl** [appium/appium#10881]
## The problem

Running compatibility test on ios 10.1.1 with wda, it looked like wda side take long time to response, especially the endpoint `/source` take `60-70s` to response.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.2-beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macos 10.14-beta
* Node.js version (unless using Appium.app|exe): 8.11.3
* Mobile platform/version under test: ios/10.1.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

## Details

appium has fork and modify `facebook/WebDriverAgent` ,So i report this issue here,  is it possible to improve the test speed. At least, the endpoint `/source` take 60-70s maybe need to fix.

In my test ,has set ` { 'useJSONSource': True}` and not use `xpath` in findby function.

## Link to Appium logs

[Appium log](https://gist.github.com/robin-xl/0d895dcad865cb8de3641fb19ff9cb38)

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/facebook/WebDriverAgent/issues

Closed as third party issue.
