### ISSUE TITLE
[simctl] The com.apple.CoreSimulator.SimDeviceType.iPad-Retina simulator device type is not supported by the com.apple.CoreSimulator.SimRuntime.iOS-10-2 runtime.

### ISSUE THREAD

**Issue by Shahunks** [appium/appium#10882]
## The problem

Getting the error in appium desktop  when i tried to use ipad pro to run.
xcode version- 9.4

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Desktop OS/version used to run Appium: macOS 10.13.5
* Node.js version (unless using Appium.app|exe):6.10.1
* Mobile platform/version under test: IOS 10.2
*  emulator/simulator: IPad Pro (12.9 inch)
* Appium.app|exe:1.6.1

## Details

Running appium desktop with capabilities:
{
  "platformName": "iOS",
  "platformVersion": "10.2",
  "deviceName": "iPad Simulator",
  "app": "Link to my app",
  "noReset": true,
  "showXcodeLog": true
}
## Link to Appium logs

https://gist.github.com/Shahunks/a883bce3992e7e514a0b4914155a8898

**Comment by mykola-mokhnach** [comment]
Which device are shown for iOS 10.2 in the `xcrun simctl list`?

**Comment by Shahunks** [comment]
here is the list 
https://gist.github.com/Shahunks/fe3b15bdb51f4b6ad374ecb2b8e9b168

**Comment by mykola-mokhnach** [comment]
Simply put one of these device names into `deviceName` cap:

```
-- iOS 10.2 --
    iPhone 5 (E736AE12-5D52-436D-9065-5D629C9A278C) (Shutdown)
    iPhone 5s (BA9378AB-1F14-47AD-8963-FE1ACBF532DC) (Shutdown)
    iPhone 6 (090A053E-DDE1-4E54-8A5A-642FA0527BAB) (Shutdown)
    iPhone 6 Plus (A4EBDD55-2067-49D1-B8D9-C234146EDBE7) (Shutdown)
    iPhone 6s (7C696135-42B7-4823-B19F-BD082B8E47C2) (Shutdown)
    iPhone 6s Plus (F722C486-0428-42DF-B0F3-1B19B6549BF8) (Shutdown)
    iPhone 7 (055B4963-91C7-4C24-B2C1-36FB9C5453E9) (Shutdown)
    iPhone 7 Plus (5EF300FA-FCAF-40AF-97A6-357912EBAAFB) (Shutdown)
    iPhone SE (27BDD7F8-74EC-43F4-8E80-13A7BA3C3308) (Shutdown)
    iPad Air (C1B7CC41-BD74-4E76-AD51-C17960E9F143) (Shutdown)
    iPad Air 2 (13C1500E-2243-483B-8182-C41E534787FE) (Shutdown)
    iPad Pro (9.7 inch) (F97956D5-D40C-4193-9CF4-0DA245C14693) (Shutdown)
    iPad Pro (12.9 inch) (06DCA6D1-B293-42FC-97AA-894660BF7329) (Booted)
```

**Comment by mykola-mokhnach** [comment]
instead of `iPad Simulator`

**Comment by Shahunks** [comment]
Perfect, thank you.
