### ISSUE TITLE
Android: Mobile Web: touch action code executes but page is not swiped/scrolled

### ISSUE THREAD

**Issue by Nishant-Taksande** [appium/appium#10888]
## The problem
Trying to do horizontal swipe, not working in android

## Environment
Tried with below versions
Appium: 1.8.1, 1.7.0 (supported by aws device farm), 1.6.5
Java Client: java-client-6.0.0-BETA5
Android real devices: Samsung Galaxy (5.0, 7.0, 6.0) Google pixel (8.0)

## Details
I tried with below code for android mobile web, code works with out error but swipe does not happen in real.

WebElement el = driver.findElement(By.xpath("//div[@Class='slide']//div[@Class='image']//div[@Class='arrow']"));
Point loc = el.getLocation();

String currentcontext = driver.getContext();
driver.context("NATIVE_APP");
Thread.sleep(5000);

TouchAction touchAction = new TouchAction(driver);
touchAction.press(loc.x, loc.y).moveTo(0, loc.y).release().perform();
driver.context(currentcontext);

Also Tried with
//	Dimension size = driver.manage().window().getSize();
//	System.out.println(size);
//	int startx = (int) (size.width * 0.30);
//	int endx = (int) (size.width * 0.70);
//	int starty = size.height / 2;

I tried with different combinations of start and end x y co ordinates.
also tried adding a delay between the operations.

**Comment by mykola-mokhnach** [comment]
Closed as inactive
