### ISSUE TITLE
SendKeys clears text input field when the field loses focus

### ISSUE THREAD

**Issue by goloroden** [appium/appium#10883]
## The problem

I am running a test on iOS using Appium on BrowserStack. The test tries to use a login form, and it needs to enter username, password, and then click the submit button.

Filling the text inputs fields basically works, but as soon as the test selects the password field, the previously entered value gets cleared in the user input field. The same is true for when the tests then clicks submit: The password field is then empty.

Apparently, a field's content gets cleared once the field loses focus. This is similar to what has been described in #9988, but unfortunately that issue was just closed without any helpful answer.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium: n/a
* Node.js version (unless using Appium.app|exe): n/a
* Mobile platform/version under test: iOS 11.0, 11.2 and 11.3
* Real device or emulator/simulator: Real device (iPhone X)
* Appium CLI or Appium.app|exe: n/a

## Details

In case it matters, it's a login form from Auth0. To get to it, go to the website we are using for the test: https://boards.ity.cloud/

## Link to Appium logs

n/a

## Code To Reproduce Issue [ Good To Have ]

n/a

**Comment by dfosticupgrade** [comment]
does anybody found a fix/workaround?

**Comment by adrianso** [comment]
We are having exactly the same issue with our Auth0 log in page.
https://app.crimsoneducation.org

Once the email input field lost focus, all the text inside the field would be gone.

**Comment by otaviolandim** [comment]
@adrianso this works?

**Comment by otaviolandim** [comment]
I'm facing a related problem when I try to invoke sendKeys() on an input. Visually the input gets the value I send, but the input's onChange isn't fired. For instance, my input is a search input; whenever my test tries to search something, the search input is updated, by the list is still the same.

Mobile platform/version under test: iOS 11.4
Real device: Iphone 6
Node: v8.11.3
Appium: 1.7.2

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by phemasundar** [comment]
@otaviolandim found any work around for this ? Am facing the similar issue. 

Thanks in advance.

**Comment by ajay19381** [comment]
I am also facing the similar issue , does any one have workaround for same
