### ISSUE TITLE
Android: Mobile Web: Unable to do horizontal swipe

### ISSUE THREAD

**Issue by Nishant-Taksande** [appium/appium#10886]
## The problem
Trying to do horizontal swipe, works for ios mobile web not for android mobile web 

## Environment
Tried with below versions
Appium: 1.8.1, 1.7.0 (supported by aws device farm), 1.6.5
Java Client: java-client-6.0.0-BETA5
Android real devices: Samsung Galaxy (5.0, 7.0, 6.0) Google pixel (8.0)

## Details
**Below code works fine for iOS**
JavascriptExecutor js = (JavascriptExecutor) driver;
HashMap<String, String> scrollObject = new HashMap<String, String>();
scrollObject.put("direction", "right");
js.executeScript("mobile: swipe", scrollObject);

**On Android mobile web it returns below error:**
org.openqa.selenium.WebDriverException: Appium error: unknown error: swipe is not defined
  (Session info: chrome=63.0.3239.111)
  (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 3.19.8-100.fc20.x86_64 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:03.216Z'
System info: host: 'asthammishra', ip: 'fe80:0:0:0:1c98:ee53:29de:f14d%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.4', java.version: '1.8.0_144'
Driver info: io.appium.java_client.AppiumDriver
Capabilities {browserName: chrome, chromeOptions: {args: [test-type, --proxy-server=http://194.1..., --disable-translate]}, databaseEnabled: false, deviceManufacturer: Google, deviceModel: Pixel, deviceName: FA69T0310673, deviceScreenSize: 1080x1920, deviceUDID: FA69T0310673, enablePerformanceLogging: false, javascriptEnabled: true, locationContextEnabled: false, loggingPrefs: org.openqa.selenium.logging..., networkConnectionEnabled: true, newCommandTimeout: 300, platform: LINUX, platformName: LINUX, platformVersion: 8.0.0, realMobile: true, systemPort: 8202, takesScreenshot: true, udid: FA69T0310673, warnings: {}, webStorageEnabled: false}
Session ID: 9553235a3d296faeb12444b77e77731f395e2859

## Code To Reproduce Issue
**I tried with below code for android mobile web, code works with out error but swipe does not happen in real.**

WebElement el = driver.findElement(By.xpath("//div[@class='slide']//div[@class='image']//div[@class='arrow']"));
Point loc = el.getLocation();

String currentcontext = driver.getContext();
driver.context("NATIVE_APP");
Thread.sleep(5000);

TouchAction touchAction = new TouchAction(driver);
touchAction.press(loc.x, loc.y).moveTo(0, loc.y).release().perform();
driver.context(currentcontext);

Also Tried with 
//		Dimension size = driver.manage().window().getSize();
//		System.out.println(size);
//		int startx = (int) (size.width * 0.30);
//		int endx = (int) (size.width * 0.70);
//		int starty = size.height / 2;

**I tried with different combinations of start and end x y co ordinates.**
**also tried adding a delay between the operations.**

_The mobile web application i am dealing with is full of images and sliders. Without swipe operation i cannot write a script for android mobile web_

**Comment by mykola-mokhnach** [comment]
It is the expected behaviour. On Android you should only use TouchAction interface.

**Comment by Nishant-Taksande** [comment]
Yes, i used the TouchAction interface, but it is not doing the swipe

**Comment by mykola-mokhnach** [comment]
try to add wait after press

**Comment by mykola-mokhnach** [comment]
Also note that since 1.8.0 moveTo expects absolute coordinates

**Comment by jinisrivastava-Mediware** [comment]
TouchAction.perform() is showing error method not yet implemented in c#
