### ISSUE TITLE
Unable to launch specific URL through Safari browser on iOS device

### ISSUE THREAD

**Issue by QA2Dev** [appium/appium#10898]
## The problem

Unable to launch specific URL through Safari browser on iOS device, safari browser is getting launched but with the default URL"**appium.io**" and then test is getting failed.

But not able to launch required/specific URL, @ driver  instantiation itself script is failing not going through next line of script.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable): Didn't try
* Desktop OS/version used to run Appium: MAC 10.13.1
* Node.js version (unless using Appium.app|exe): 7.9
* Mobile platform/version under test: iOS, 9.3.3
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Unable to launch specific URL through Safari browser on iOS device, safari browser is getting launched with url "appium.io" and then test is getting failed.

## Link to Appium logs

https://gist.github.com/QA2Dev/dcbc7221ebd5758d42ae2eaac971caef

## Code To Reproduce Issue [ Good To Have ]
capabilities.setCapability("platformName", "iOS");
capabilities.setCapability("useNewWDA", true);
 capabilities.setCapability("automationName", "XCUITest");
capabilities.setCapability("realDeviceLogger", "idevicesyslog");
capabilities.setCapability("platformVersion", "9.3");
capabilities.setCapability("noReset", false);
capabilities.setCapability("clearSystemFiles", true);
capabilities.setCapability("xcodeOrgId", "XXXXXXXXX");
capabilities.setCapability("xcodeSigningId", "iPhone Developer");
capabilities.setCapability("deviceName", "iPad Air");
capabilities.setCapability("newCommandTimeout", 150000);
capabilities.setCapability("udid", "e0f086esdfd949e8d39475343c72ed97fd524045");
capabilities.setCapability("browserName", "Safari");
capabilities.setCapability("webkitResponseTimeout", 150000);

driver = new AppiumDriver(new URL("http://127.0.0.1:4723/wd/hub"), setAndroidCapabilities());

**Comment by mykola-mokhnach** [comment]
Try appium@beta

**Comment by JagatheswaranSelvakumar** [comment]
Hi QA2Dev, could try  adding this capaility 
setCapability("safariInitialUrl", "YOUR_APPLICATION_URL");
