### ISSUE TITLE
Unable to perform swipe action in Appium desktop 1.6.2

### ISSUE THREAD

**Issue by tanmoysahat** [appium/appium#10897]
## The problem

while performing swipe action using appium desktop, no action is performing in the real device.  

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2
* Desktop OS/version used to run Appium: 10.13.4
* Node.js version (unless using Appium.app|exe): 10.2.1
* Mobile platform/version under test: 11.2.2
* Appium Java client: 5.0.4

## Details

same action working fine with appium 1.7.2 but in 1.8.1 not working.
Here m trying to perform vertical swipe in the integration application from appium desktop, but no swipe action executed in the real device

## Link to Appium logs

https://gist.github.com/tanmoysahat/028e626713ba8f4befb04ff57d3fc0e7

## Code To Reproduce Issue [ Good To Have ]

(new TouchAction(getWebDriver())).press(startx,starty).moveTo(startx,endy).release().perform();

**Comment by mykola-mokhnach** [comment]
You must add wait after press or perform longPress instead. Closed as duplicate

**Comment by tanmoysahat** [comment]
@mykola-mokhnach thanks for replay.it works with wait statement.
(new TouchAction(getWebDriver())).press(endx,starty).waitAction(Duration.ofMillis(2000)).moveTo(startx,starty).release().perform();
