### ISSUE TITLE
runAppInBackground() gives webdriverExeption saying that a java.util.HashMap cannot be cast to java.lang.Long

### ISSUE THREAD

**Issue by mjm987mj** [appium/appium#10899]
## The problem
Whenever I try to execute: getDriver().getAppiumDriver().runAppInBackground(Duration.ofSeconds(10));

I get the following exception:
org.openqa.selenium.WebDriverException: java.util.HashMap cannot be cast to java.lang.Long

## Environment
* Appium version: Appium 6.0.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Run in Cloud (Perfecto)
* Mobile platform/version under test: iOS and Android
* Real device or emulator/simulator: Real Device in Cloud

## Details
If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
https://gist.github.com/mjm987mj/e28970d02c4d67e4b65e1e1930cbe3f1

## Code To Reproduce Issue
getDriver().getAppiumDriver().runAppInBackground(Duration.ofSeconds(10));

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/appium/appium/issues/10899

To me it looks like you are truing to use an outdated java client version.
