### ISSUE TITLE
Add cloud based real device + emulator/simulator testing to CI

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#10896]
In an effort to improve CI and testing, we'd like to have our end-to-end tests run on a grid of real devices and emulators/simulators instead of just the small number of local emulators/simulators they run on now.

We can run the tests on Sauce Labs (real device and ondemand).

We worked on this in the past but ran into some issues with timeouts and overuse of the real devices. I think I have a solution that will resolve those problems though. We ought to do it like this:

* [ ] Set up a free OSS Bintray dashboard and have the CI for `appium/appium` publish a zip to Bintray every commit
* [ ] Run a cronjob on all of the Appium drivers (xcui, uiautomator2, espresso) every night that runs the E2E tests, targetting a grid of devices/emulators/simulators using the most recently published Appium zip is as the staging URL for the cloud provider

This would also have the added positive side effect of having readily available Appium bundles for every commit. We'll reduce the number of MacOSX builds we run on Travis because instead of running a batch of OSX builds on several different OSX versions, we could reduce it and rely on the cloud testing.

Any questions/concerns would be appreciated.

(cc: @dmissman @vrunoa)

**Comment by mykola-mokhnach** [comment]
Closed as obsolete
