### ISSUE TITLE
Appiums inspector gives internal error when trying to inspect IOS apps

### ISSUE THREAD

**Issue by PunkWithAStache** [appium/appium#10893]
## The problem
I am working on how to add unique accessibility identifiers for Ionic Applications and use those in test automation. When i try to launch an inspector session to view the app, i get the error message i linked in a gist further down.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Desktop OS/version used to run Appium: MacOS High Sierra
* Node.js version (unless using Appium.app|exe): 10.4.1
* Mobile platform/version under test: iPhone 8 with iOS 11.2.6
* Appium CLI or Appium.app|exe: Appium.app

## Details

I am not sure what other details i can provide, since i am relatively new to automating mobile applications.

## Link to Appium logs

https://gist.github.com/PunkWithAStache/c662f602868e7d834a813e7545074778

**Comment by mykola-mokhnach** [comment]
Try appium@beta

**Comment by PunkWithAStache** [comment]
Where can i find the appium@beta?
I took a look at https://github.com/appium/appium-desktop/releases but could not find anything other than the latest release, there.

**Comment by PunkWithAStache** [comment]
Ok. So instead of using the desktop app to view the accessibility id's i need for my scripts, i should rather use safari/chrome inspector to view it and run my tests on appium@beta to verify that my tests work?

I wasn't aware of this, thank you for guiding me in the correct direction
