### ISSUE TITLE
Get Appium server version from client

### ISSUE THREAD

**Issue by oscheller1** [appium/appium#10892]
Is there a way to get the Appium server version (e.g. 1.8.1) from the Appium client (e.g. python client) ?

**Comment by mykola-mokhnach** [comment]
try to request the  /status endpoint

**Comment by oscheller1** [comment]
The request is giving me `<session>/status' did not map to a valid resource`

**Comment by mykola-mokhnach** [comment]
https://www.w3.org/TR/webdriver/#status

**Comment by oscheller1** [comment]
returns
```
{
    "value": {
        "build": {
            "version": "1.8.1",
            "revision": null
        }
    }
}
```

Thanks

**Comment by oscheller1** [comment]
@mykola-mokhnach Do you know of any particular reason why this endpoint is not implemented in the selenium python client?

**Comment by mykola-mokhnach** [comment]
You'd rather ask selenium maintainers.
