### ISSUE TITLE
Appium - IOS scripts are running very slow.

### ISSUE THREAD

**Issue by Akhileshldc** [appium/appium#10905]
I have setup a Framework for Mobile automation with Appium and Java. I have used the same framework for Android and IOS script creation. When I run iOS scripts its execution is very slow, even android scripts are running much faster than iOS.

I am giving the scenario for Login page. On login page there three elements(UserName, Password fields and Login button). Driver fill the vale in Username field and then before moving to Password field it waits for few seconds, same happens after filling password field. It fills the password and then again wait for few seconds(curser remains blinking in password field for approx 3 to 5 seconds) before clicking on Login button.

I am observing this problem only for Appium-IOS.

## Environment

* Appium version 1.8.1
* Using Server address 127.0.0.1 Port 4723
* Appium Desktop Version 1.6.2 (1.6.2)
* Node.js version 9.8.0
* Java 1.8.0_144
* Mac OSX 10.12.6
* Xcode Version 9.1 (9B55)
* Real device iPhone 5 S(v 11.1.2)

##Code details

1. Using Driver: 
WebDriver driver = new IOSDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"), caps);
2. Using Xpath for locating the elements
3. Using sendKeys() for filling the value input fields.
4. Using the click() for clicking the button.

##Used capabilities

	         DesiredCapabilities caps = new DesiredCapabilities().iphone();
		caps.setCapability("no", true);
		caps.setCapability("newCommandTimeout", 120);
		caps.setCapability("launchTimeout", "1000");
		caps.setCapability("deviceName", "iPhone 5s");
		caps.setCapability("udid", sDeviceId); // Give Device UDID 
		caps.setCapability("bundleid", "com.xyz.dev");
		caps.setCapability("platformName", "iOS");
		caps.setCapability("app", app.getAbsolutePath());
		caps.setCapability("platformVersion", sDeviceVersion);
		caps.setCapability("noReset", false);
		caps.setCapability("forceMjsonwp", true);
		caps.setCapability("clearSystemFiles", true);
		caps.setCapability("xcodeOrgId", "GH922ECD");
		caps.setCapability("xcodeSigningId", "iPhone Developer");
		caps.setCapability(IOSMobileCapabilityType.AUTO_ACCEPT_ALERTS, Boolean.TRUE);		
		caps.setCapability("simpleIsVisibleCheck", true);
		caps.setCapability("automationName", "XCUITest");
		caps.setCapability("simpleIsVisibleCheck", true);
		caps.setCapability("preventWDAAttachments", true);
		caps.setCapability("useJSONSource", true);

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/facebook/WebDriverAgent/issues

Closed as third party issue.

BTW, xpath lookup strategy is the slowest one. Check https://github.com/facebook/WebDriverAgent/wiki/How-To-Achieve-The-Best-Lookup-Performance for more details.
