### ISSUE TITLE
HTTP Status: '400' -> incorrect JSON status mapping for 'unknown error' (500 expected)

### ISSUE THREAD

**Issue by VenkateshPS** [appium/appium#10909]
## The problem

HTTP Status: '400' -> incorrect JSON status mapping for 'unknown error' (500 expected). 
Appium fails to lunch App.

Log details below:

https://gist.github.com/VenkateshPS/978b677c9198a20d98f29639cb589735

[978b677c9198a20d98f29639cb589735-7afe054eab883bbcaff6b860bacd5184fc255d8a.zip](https://github.com/appium/appium/files/2118915/978b677c9198a20d98f29639cb589735-7afe054eab883bbcaff6b860bacd5184fc255d8a.zip)

## Environment

Appium 1.8.1
Appium java client 6.0.0 BETA 4
selenium-java 3.11.0
ANDROID 7
## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by VenkateshPS** [comment]
No I don't have any customised firmware using  macOS High Sierra 10.13.4 and yes it was reproducible on other devices.

**Comment by VenkateshPS** [comment]
I uninstalled and reinstalled Appium, now I don't see the issue.

**Comment by VenkateshPS** [comment]
Reproduction steps:
1. Install Appium [npm install -g appium]
2. build web driver Agent and run iOS Test.
3. Now try running Android tests, issue can be observed.

**Comment by Nasen** [comment]
I found out the root cause, it's because of my android device have old version of UIAutomator2-server, by uninstalling it, rerun test works.

**Comment by VenkateshPS** [comment]
Do you mind putting steps for the fix.

Thanks,
Venkatesh

**Comment by Fanch-** [comment]
@VenkateshPS You have to go on Parameters - > Applications on your phone, remove old io.appium.uiautomator2.server apks then relaunch your test. It also fixed my problem.
