### ISSUE TITLE
Is Pagefactory deprecated in latest appium clients?

### ISSUE THREAD

**Issue by Gocoollnath** [appium/appium#10906]
## The problem

No warning of Pagefactory deprecation in latest appium java and c# clients. But Selenium threads saying its deprecated. Please, clarify

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Appium client: 3.0.0.2 for .Net and 6.0.0 for Java

## Code used

The below code works fine without any issues

[FindsBy(How = How.Id, Using = "packagename:id/LoginView_txtUsername")]
        public  IWebElement UserName_Field;

**Comment by saikrishna321** [comment]
@Gocoollnath nope appium java-client n c# has not deprecated Pagefactory in the latest versions.

**Comment by Gocoollnath** [comment]
@saikrishna321  Thank you for prompt reply. Will it be deprecated in near future releases? Because if it's so, I need to revamp the script now, so that it doesn't piles up later.

**Comment by saikrishna321** [comment]
> Will it be deprecated in near future releases?

@TikhomirovSergey @jlipps  would be able to answer this

**Comment by mykola-mokhnach** [comment]
I assume that each client decides on its own, so it would be better to ask in the appropriate client issues tracker.
