### ISSUE TITLE
Unable to launch app on iOS 11.4.1 beta 

### ISSUE THREAD

**Issue by QA2Dev** [appium/appium#10908]
## The problem

Unable to launch app on **iOS 11.4.1 beta** device, getting an error as "Could not proxy command to remote server. Original error: Error: read ECONNRESET".

This issue is not occurring on **iOS 10.2 OS**

## Environment

* Appium version (or git revision) that exhibits the issue:1.8.1 (iOS 11.4.1beta)
* Last Appium version that did not exhibit the issue (if applicable):1.8.1 (iOS  10.2)
* Desktop OS/version used to run Appium: MAC
* Node.js version (unless using Appium.app|exe): 7.9
* Mobile platform/version under test: iOS 11.4.1 beta
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Unable to launch app on iOS 11.4.1 beta 

## Link to Appium logs

https://gist.github.com/QA2Dev/52a02924c20ecd76ecd471a9258644bb

## Code To Reproduce Issue [ Good To Have ]

[Appium] Capabilities:
[Appium]   app: /Users/e001844/Desktop/WeDo.ipa
[Appium]   noReset: false
[Appium]   clearSystemFiles: true
[Appium]   xcodeOrgId: xxxxxxxxxxxxx
[Appium]   deviceName: iPad_Pro_iOS_10.2_Local
[Appium]   xcodeSigningId: iPhone Developer
[Appium]   realDeviceLogger: idevicesyslog
[Appium]   newCommandTimeout: 15000
[Appium]   platformVersion: 10.2
[Appium]   useNewWDA: true
[Appium]   automationName: XCUITest
[Appium]   platformName: ios
[Appium]   udid: 2cc0b52a5dfaedb4664werwer99c029874bc28

**Comment by mykola-mokhnach** [comment]
Have you tried to install and execute the app manually?

> [XCUITest] Cannot parse major and minor version numbers from platformVersion "11". Will build for the default 

I observe that in the last test this capability is not set to a proper value. 

It is also necessary to have the device log

**Comment by QA2Dev** [comment]
@mykola-mokhnach, It's the wrong input of capability platformVersion which caused the issue, thank you, issue is resolved now.
