### ISSUE TITLE
Matched JSONWP error code 7 to NoSuchElementError 

### ISSUE THREAD

**Issue by MioOgbeni** [appium/appium#10917]
## The problem

Hi, I tried in our project switch to UiAutomator2 from default Appium automation engine. Main reason why we decide to do this, were issues here on git, where some commiters writed that UIAutomation2 is more stable then Appium automation engine. Now with UiAutomator2 i have problem, that i can't call .FindElement() on another element to find his son element. Or at least I think that this is a this problem. Can you look on this two logs and say what can be wrong? 

If you need additional resources for investigation, do not be afraid to write me.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable): 1.8.1
* Desktop OS/version used to run Appium: Win 10
* Node.js version (unless using Appium.app|exe): .exe (1.6.2)
* Mobile platform/version under test: And 7 (API 24)
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: .exe

## Link to Appium logs

Log of function test with Appium automation engine:
https://gist.github.com/MioOgbeni/50b11441dd4c1bff031bd0721c7c07a6

Log of non-function test with UiAutomator2:
https://gist.github.com/MioOgbeni/9a5fc62351ebb80717fef8ee8688944b

## Code To Reproduce Issue [ Good To Have ]

```
        [FindsBy(How = How.XPath, Using = "//android.support.v7.widget.RecyclerView[@index='0']/android.widget.LinearLayout")]
        private IList<IWebElement> Rows { get; set; }

        public List<SettingPageRow> RowList = new List<SettingPageRow>();

        public void FindRows()
        {
            if (!AmIOnSettingPage()) return;
            RowList.Clear();
            foreach (var item in Rows)
            {
                var row = new SettingPageRow();
                try
                {
                    row.Value = item.FindElement(By.Id("summary"));
                }
                catch
                {
                    row.Value = null;
                }

                try
                {
                    row.CheckBox = item.FindElement(By.Id("switchWidget"));
                }
                catch
                {
                    try
                    {
                        row.CheckBox = item.FindElement(By.Id("checkbox"));
                    }
                    catch
                    {
                        row.CheckBox = null;
                    }
                }

                try
                {
                    row.Text = item.FindElement(By.Id("title"));
                }
                catch
                {
                    row.Text = null;
                }

                RowList.Add(row);
            }
        }

```

**Comment by MioOgbeni** [comment]
UPDATE: I've also tried primitive test where i only launch app and try to login in app. There I don't use own creepy code, but only in page object I've declare textboxs of AccountName, Email and Password. In test i only call .Clear() and .SendKeys() on every of these elements, but again tests end with same error. The first called element (AccountName) passed these commands but tests crashed on the second (Email).

**Comment by mykola-mokhnach** [comment]
Try to print the actual page source before locating the element and make sure it is really there.

**Comment by MioOgbeni** [comment]
Here is log with capability, `printPageSourceOnFindFailure` with the value set to true https://gist.github.com/MioOgbeni/c13ac017a4852984f32d067628e5198e

**Comment by mykola-mokhnach** [comment]
There is no element with id `title` in the xml, only `android:id/title`

**Comment by MioOgbeni** [comment]
Yeah it's possible, but why test passed without use of UIAutomator2 and found id `title`, despite there is also `android:id/title` in the xml, when I don't used UIAutomator2.

https://gist.github.com/MioOgbeni/51b3fc3feb5e7189fe76444ff27f292d
Look on gist where I tried simulate error by finding `title4` for invoking of error with `printPageSourceOnFindFailure` on default Appium automation engine

**Comment by mykola-mokhnach** [comment]
Because in UAI2 the expressions parser is more strict

**Comment by MioOgbeni** [comment]
It's good to know but it isn't specified somewhere in the documentation.

But why some commands passed only with `someMyId` and don't need prefix `android:id/`?

**Comment by mykola-mokhnach** [comment]
As far as I remember this only works if the prefix equals to your package id.

**Comment by MioOgbeni** [comment]
Ou, it's true. Now I noticed it. In our application are some elements with `android` prefix and some with our package prefix. I will try to use this prefixes in my test, and after this I give you know if you can close this issue.

**Comment by MioOgbeni** [comment]
Thanks for help. Adding prefix for all ids helped in most cases.

But some element still doing weird things. This things refer to this issue 
https://github.com/appium/appium/issues/7517

**Comment by JoelWhitney** [comment]
@mykola-mokhnach I'm also running into this. I've tried on 1.11.0-beta.3 through CLI and 1.10.0 through Appium.app. Whenever I set capabilities for `automationName = "UiAutomator2" I can no longer find my element by id, but removing `automationName` capability works..


<details><summary>Appium output with and without automationName set</summary>

```
automationName not specified

[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/2140e673-5c20-4a81-8864-6f2d3a8de988/element[39m
[info] [35m[HTTP][39m [90m{"using":"id","value":"idp_Name"}[39m
[debug] [35m[W3C (2140e673)][39m Calling AppiumDriver.findElement() with args: ["id","idp_Name","2140e673-5c20-4a81-8864-6f2d3a8de988"]
[debug] [35m[BaseDriver][39m Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [35m[BaseDriver][39m Waiting up to 0 ms for condition
[debug] [35m[AndroidBootstrap][39m Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"idp_Name","context":"","multiple":false}}
[debug] [35m[AndroidBootstrap][39m [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"idp_Name","context":"","multiple":false}}
[debug] [35m[AndroidBootstrap][39m [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [35m[AndroidBootstrap][39m [BOOTSTRAP LOG] [debug] Got command action: find
[debug] [35m[AndroidBootstrap][39m [BOOTSTRAP LOG] [debug] Finding 'idp_Name' using 'ID' with the contextId: '' multiple: false
[debug] [35m[AndroidBootstrap][39m [BOOTSTRAP LOG] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=com.esri.navigator.qa:id/idp_Name][debug] [35m[AndroidBootstrap][39m [BOOTSTRAP LOG] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=idp_Name]
[debug] [35m[AndroidBootstrap][39m Received command result from bootstrap
[debug] [35m[W3C (2140e673)][39m Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"16","ELEMENT":"16"}
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session/2140e673-5c20-4a81-8864-6f2d3a8de988/element [39m[32m200[39m [90m144 ms - 69[39m
[info] [35m[HTTP][39m [90m[39m
[debug] [35m[AndroidBootstrap][39m [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":{"ELEMENT":"16"}}


automationName = "UiAutomator2"

[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/63a7e37d-00a1-48ec-99cc-cf6b5037ef90/element[39m
[info] [35m[HTTP][39m [90m{"using":"id","value":"idp_Name"}[39m
[debug] [35m[W3C (63a7e37d)][39m Calling AppiumDriver.findElement() with args: ["id","idp_Name","63a7e37d-00a1-48ec-99cc-cf6b5037ef90"]
[debug] [35m[BaseDriver][39m Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [35m[BaseDriver][39m Waiting up to 0 ms for condition
[debug] [35m[JSONWP Proxy][39m Matched '/element' to command name 'findElement'
[debug] [35m[JSONWP Proxy][39m Proxying [POST /element] to [POST http://localhost:8200/wd/hub/session/68d554dd-b7f0-4b1f-8f20-162d03a8acfb/element] with body: {"strategy":"id","selector":"idp_Name","context":"","multiple":false}[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/63a7e37d-00a1-48ec-99cc-cf6b5037ef90/timeouts[39m
[info] [35m[HTTP][39m [90m{"implicit":20000}[39m
[debug] [35m[W3C (63a7e37d)][39m Calling AppiumDriver.timeouts() with args: [null,null,null,null,20000,"63a7e37d-00a1-48ec-99cc-cf6b5037ef90"]
[debug] [35m[BaseDriver][39m W3C timeout argument: {"implicit":20000}}
[debug] [35m[BaseDriver][39m Set implicit wait to 20000ms
[debug] [35m[W3C (63a7e37d)][39m Responding to client with driver.timeouts() result: null
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session/63a7e37d-00a1-48ec-99cc-cf6b5037ef90/timeouts [39m[32m200[39m [90m1 ms - 14[39m
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/63a7e37d-00a1-48ec-99cc-cf6b5037ef90/timeouts[39m
[info] [35m[HTTP][39m [90m{"implicit":0}[39m
[debug] [35m[W3C (63a7e37d)][39m Calling AppiumDriver.timeouts() with args: [null,null,null,null,0,"63a7e37d-00a1-48ec-99cc-cf6b5037ef90"]
[debug] [35m[BaseDriver][39m W3C timeout argument: {"implicit":0}}
[debug] [35m[BaseDriver][39m Set implicit wait to 0ms
[debug] [35m[W3C (63a7e37d)][39m Responding to client with driver.timeouts() result: null
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session/63a7e37d-00a1-48ec-99cc-cf6b5037ef90/timeouts [39m[32m200[39m [90m3 ms - 14[39m
```

</details><br>

The XML for my element is as follows:
```
<android.view.View index="1" package="com.esri.navigator.qa" class="android.view.View" text="SAML SHIBBOLETH" resource-id="idp_Name" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[47,682][1034,801]" displayed="true"/>
```

Running Appium Ruby Console, I can find the element with the following:
- `find_elements(:xpath, "//android.view.View[@text='SAML SHIBBOLETH']")` 

I cannot find the element with any of the following until I remove `automationName = "UiAutomator2" capability:
- `id("idp_Name")`, 
- `id("android:id/idp_Name")`
- `id("com.esri.navigator.qa:id/idp_Name")`

Any ideas?

**Comment by mykola-mokhnach** [comment]
@JoelWhitney Try to use AccessibilityId locator instead of id

**Comment by mykola-mokhnach** [comment]
The lookup logic depends on the UIA framework itself and we cannot do much in Appium to influence that. Also, you should use webview context if the application itself is not native

**Comment by JoelWhitney** [comment]
Thanks @mykola-mokhnach. There is only "NATIVE_APP" context available.. I'll work around it in the meantime as no elements within a "android.webkit.WebView" can be found by id using UiAutomator2 even though their respective resource id's are exposed in the source.

I poked around a little bit before giving up, and what's interesting is that I can find it by resource id if I make my own POST calls to the server

```
http://localhost:8200/wd/hub/session/147176f2-e5a0-4e5d-a7d4-ea0d45a96285/elements] with body: 

DOES NOT find element
{"strategy":"id","selector":"idp_Name","context":"","multiple":false} 
{"strategy":"accessibility id","selector":"idp_Name","context":"","multiple":false}

Finds element
{"strategy":"-android uiautomator","selector":"new UiSelector().className(\"android.view.View\").resourceId(\"idp_Name\");","context":"","multiple":false}
{"strategy":"-android uiautomator","selector":"new UiSelector().resourceId(\"idp_Name\");","context":"","multiple":false}
```

**Comment by mykola-mokhnach** [comment]
You can get more details from the source code: https://github.com/appium/appium-uiautomator2-server/blob/20de6220d4d9b888892b8e148a1e16b6aa8b874d/app/src/main/java/io/appium/uiautomator2/handler/FindElement.java#L95

**Comment by JoelWhitney** [comment]
Thank you for that @mykola-mokhnach! After looking at the implementation I figured out I could find the element with `find_element(:uiautomator, "resourceId(\"idp_Name\")")`

**Comment by irineu** [comment]
Hi, i'm having the same issue, @JoelWhitney thanks for your tip using native uiautomator. My app has only one context as well. With Appium automator it worked perfectly without the package prefix, but my  scenarios needs to run with uiautomator server.

The resource-id shows at the inspector but the element selector wont work, i believe that's a improvement point.
