### ISSUE TITLE
How to kill app in iOS?

### ISSUE THREAD

**Issue by EltonZhong** [appium/appium#10913]
## The problem

What's the solution if I want to kill app in ios and start a new session without launching the app?
since autolauch capability is deprecated in appium 1.5.

## Environment
Any

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by EltonZhong** [comment]
What if I just don't want to open app in the foreground when launching app?

**Comment by mykola-mokhnach** [comment]
I don't know any other ways. Let us know if you find out something new there.

**Comment by EltonZhong** [comment]
OK, will check in project WebDriverAgent
