### ISSUE TITLE
Proxying [GET /wda/screen] repeating

### ISSUE THREAD

**Issue by Michael-Benton** [appium/appium#10911]
## The problem

I've been testing my companies app using Appium for about 2 months now and its recently become slower and slower. I recently updated to the latest version of Appium(1.8.1) and it's still incredibly slow. I'm testing on a real device. It occasionally will freeze when trying to find an element and just hang there.

## Environment

* Appium version: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable):1.7(But started to exhibit issue)
* Desktop OS/version used to run Appium: (macOS High Sierra Version 10.13.5
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 11.4
* Real device or emulator/simulator: iPhone 6 Plus and iPhone 7
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/Michael-Benton/af0d9b9493421cf0201c3b6999b67301

**Comment by SrinivasanTarget** [comment]
@Michael-Benton https://github.com/appium/appium-xcuitest-driver/pull/701

**Comment by Michael-Benton** [comment]
Will those changes be applied in the next update?

**Comment by SrinivasanTarget** [comment]
Yes @Michael-Benton Well soon there will be a release or feel free to build it from source and apply locally.

**Comment by Michael-Benton** [comment]
@SrinivasanTarget Right, I'll make a local build and test. I'll keep this open until fixed?

**Comment by SrinivasanTarget** [comment]
Sure @Michael-Benton

**Comment by mykola-mokhnach** [comment]
There was also an issue with java client v. 5. Update it to version 6 in order to avoid extra /session calls.

**Comment by Michael-Benton** [comment]
@mykola-mokhnach I have version 8 installed.

**Comment by mykola-mokhnach** [comment]
I'm not talking about the JDK version, but the client itself.

**Comment by Michael-Benton** [comment]
@mykola-mokhnach So I updated the xcuitest-driver using `npm i appium-xcuitest-driver` but I'm still experiencing the same issue. I saw the update to 2.86.0 for the xcuitest-driver, but I'm not sure if this included this issue.

**Comment by mykola-mokhnach** [comment]
My PR is not published yet. Wait for the next version tag

**Comment by Michael-Benton** [comment]
@mykola-mokhnach Any chance I can download it manually right now? If so, how would I achieve that?

**Comment by mykola-mokhnach** [comment]
easy, just get the source code from master and replace the content of the `/lib` subfolder inside `appium-xcuitest-driver`. Then run `gulp transpile`, restart node and you're good to go

**Comment by Michael-Benton** [comment]
Cloned Master-> replaced my `/lib` subfolder inside `appium-xcuitest-driver` then ran `gulp transpile`. Still having the same issue.

https://gist.github.com/Michael-Benton/d3e8718bd90692f82611a28a5b6a48d7

**Comment by mykola-mokhnach** [comment]
Perhaps, something was not done properly. Wait for the next version

**Comment by mykola-mokhnach** [comment]
The change has been published in 2.85.0
