### ISSUE TITLE
getPageSource() hang

### ISSUE THREAD

**Issue by bastenf** [appium/appium#10916]
## The problem
getPageSource() hang

## Environment

* Appium 1.8.1:
* Windows7:
* Node.js 8.9.4:
* Android7:
* Real device:
* Appium CLI:

## Details
Start mobile chrome, switch to NATIVE_APP context, then some clicks, a page in B app will popup, I want to get the source of that page, it hangs

## Link to Appium logs

[HTTP] --> GET /wd/hub/session/861696d3-eed3-4e12-9745-eb6ff3d84e43/source
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.getPageSource() with args: ["861696d3-eed3-4e
12-9745-eb6ff3d84e43"]
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":
"source","params":{}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":
"action","action":"source","params":{}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: source
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.getStatus() with args: []
[debug] [W3C] Responding to client with driver.getStatus() result: {"build":{"ve
rsion":"1.8.1","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 15 ms - 55
[HTTP]
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.getStatus() with args: []
[debug] [W3C] Responding to client with driver.getStatus() result: {"build":{"ve
rsion":"1.8.1","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 6 ms - 55
[HTTP]
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.getStatus() with args: []
[debug] [W3C] Responding to client with driver.getStatus() result: {"build":{"ve
rsion":"1.8.1","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 8 ms - 55
[HTTP]
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.getStatus() with args: []
[debug] [W3C] Responding to client with driver.getStatus() result: {"build":{"ve
rsion":"1.8.1","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 6 ms - 55
[HTTP]

## Code To Reproduce Issue [ Good To Have ]

        DesiredCapabilities c = new DesiredCapabilities();
        c.setCapability(MobileCapabilityType.BROWSER_NAME, "chrome");
        c.setCapability("platformName", "Android");
        c.setCapability("deviceName", "M960BDQG229P9");
        c.setCapability("appPackage", "com.android.chrome");
        c.setCapability("unicodeKeyboard", "True");
        c.setCapability("resetKeyboard", "True");
        c.setCapability("noSign", "True");
        c.setCapability("appActivity", "com.google.android.apps.chrome.Main");
        c.setCapability("fastReset", "false");
        c.setCapability("fullReset", "false");
        c.setCapability("noReset", "true");
        c.setCapability("skipUnlock", "true");
        c.setCapability("clearSystemFiles", "true");
        // Since the default webview in is CHROMIUM
        // switch back to native_app
        AndroidDriver.context("NATIVE_APP")
        // Do some clicks. **it will switch to another app**
        
        // when I want to click on the other app or getPageSource, it hangs.
        AndroidDriver.getPageSource();

**Comment by mykola-mokhnach** [comment]
Use uiatomator2 backend for android6+

**Comment by bastenf** [comment]
great, uiautomator2  solves my problem, thanks a lot
