### ISSUE TITLE
org.openqa.selenium.WebDriverException: unknown error (An unknown server-side error occurred. status='false'. Failed to complete internal method: 'elementSendText args: [NATIVE, xpath=(//*[contains(@resource-id,'password2')])[1], 0, 1234]', details: Failed to send text to 'xpath=(//*[contains(@resource-id,'password2')])[1]'. )  (WARNING: The server did not provide any stacktrace information)

### ISSUE THREAD

**Issue by praveendayalan** [appium/appium#10912]
## The problem

When I am trying to enter a password in the password field using sendkeys() method. I am getting this error “org.openqa.selenium.WebDriverException: unknown error (An unknown server-side error occurred. status=‘false’. Failed to complete internal method: ‘elementSendText args: [NATIVE, xpath=(//[contains(@resource-id,‘password2’)])[1], 0, 1234]’, details: Failed to send text to 'xpath=(//[contains(@resource-id,‘password2’)])[1]’. ) (WARNING: The server did not provide any stacktrace information)”

## Environment

java.version: '1.8.0_171'

I am using Experitest appiumstudio

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]
![appium](https://user-images.githubusercontent.com/34325218/41677249-c5070210-7495-11e8-9717-179326b53a9f.PNG)

@FindBy(xpath="//*[contains(@resource-id,‘password1’)]")
AndroidElement TypePassword;

@FindBy(xpath="//*[contains(@resource-id,'password2')]")
WebElement RepeatPassword;

public void EnterPassword() {
    TypePassword.click();
	TypePassword.sendKeys("1234");
	RepeatPassword.sendKeys("1234");

**Comment by mykola-mokhnach** [comment]
Please write to the support team of the corresponding product.
