### ISSUE TITLE
Original error: App with bundle identifier '***.****.WebDriverAgentRunner' unknown

### ISSUE THREAD

**Issue by Demitsuru** [appium/appium#10919]
## The problem

Hi.
I have experienced an issue when there is an error shown upon a try to create an IOSDriver. I have followed step-by-step guide and everything is fine when I execute the following command:
```
xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<device udid>' test
```
From the appium node-modules 'xcuitest-driver' folder everything is as expected, so I can see the following output:
```
...
Test Suite 'All tests' started at 2018-06-21 16:19:18.050
Test Suite 'WebDriverAgentRunner.xctest' started at 2018-06-21 16:19:18.056
Test Suite 'UITestingUITests' started at 2018-06-21 16:19:18.059
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.02s Start Test at 2018-06-21 16:19:18.079
    t =     0.02s Set Up
2018-06-21 16:19:18.090 WebDriverAgentRunner-Runner[1168:675810] Built at Jun 21 2018 12:33:18
2018-06-21 16:19:18.154 WebDriverAgentRunner-Runner[1168:675810] ServerURLHere->http://10.1.40.48:0<-ServerURLHere
```

But when I am trying to run WebDriverAgent from my tests, e.g create an IOSDriver instance - it fails with the following error:
```
Original error: App with bundle identifier 'com.facebook.WebDriverAgentRunner' unknown (WARNING: The server did not provide any stacktrace information)
```
## Environment

* Appium version (or git revision) that exhibits the issue: **1.8.1**
* Desktop OS/version used to run Appium: macOS High Sierra 10.13.5 / macOS Sierra 10.1
* Node.js version (unless using Appium.app|exe): **v8.4.0,v8.5.0,v6.4.0**
* Mobile platform/version under test: **iOS**
* Real device or emulator/simulator: **Real device - iPhone 5S, iPhone 6, iPhone 7Plus**
* Appium CLI or Appium.app|exe: **appium-cli**

## Link to Appium logs
https://gist.github.com/Demitsuru/65c42d681fd70f4543a76908423a2bdd#file-gistfile1-txt

## Code To Reproduce Issue [ Good To Have ]

```
DesiredCapabilities mobileCapabilities = new DesiredCapabilities();
            mobileCapabilities.setCapability("browserName", "safari");
            mobileCapabilities.setCapability("deviceName", "Reason 5s");
            mobileCapabilities.setCapability("platformName", "iOS");
            mobileCapabilities.setCapability("platformVersion", "9.3.2");
            mobileCapabilities.setCapability("bundleId", "*****.WebDriverAgentRunner");
            mobileCapabilities.setCapability("udid", "*****");
            mobileCapabilities.setCapability("automationName", "XCUITest");
            mobileCapabilities.setCapability("updatedWDABundleId", "co.uk.reasontest.WebDriverAgentRunner");
            mobileCapabilities.setCapability("xcodeOrgId", "M*****9");
            mobileCapabilities.setCapability("xcodeSigningId", "iPhone Developer");
            iosDriver = new IOSDriver(new URL("http://*****:4723/wd/hub"), mobileCapabilities);
```

**Comment by imurchie** [comment]
`bundleId` should be _your_ app, not Appium's.

**Comment by imurchie** [comment]
That is to say, the app under test.

**Comment by mykola-mokhnach** [comment]
There is no point to set bundleId at all if `mobileCapabilities.setCapability("browserName", "safari");`

**Comment by Demitsuru** [comment]
@imurchie Thank you for the response. Will check @mykola-mokhnach advice

**Comment by imurchie** [comment]
Oh yeah. Missed the Safari part. No `bundleId` is the only way to go.

**Comment by Demitsuru** [comment]
@mykola-mokhnach @imurchie Thank you for your help. Seems to be working now. As I used 'bundleId' for apps before. Didn't realize you need only 'browserName'. Resolved.

**Comment by imurchie** [comment]
If you are testing an app (not MobileSafari) you either need an `app` (which Appium will install) or a `bundleId` (if the app is already installed).
