### ISSUE TITLE
UIAutomator exited with code 255, signal null

### ISSUE THREAD

**Issue by anu6986** [appium/appium#10928]
## The problem

The UiAutomator exits with code 255

This is my code:

<snip>
AndroidDriver wd = null;
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("platformName", "Android");
        capabilities.setCapability("browserName", "Chrome");
        String apkpath="/Users/anupamanarisetty/Downloads/app-fsapp-debug.apk";
        File app=new File(apkpath);
        capabilities.setCapability("appPackage", "example.com.ondemandapp");
        capabilities.setCapability("appActivity", "example.com.ondemandapp.MainActivity");
        capabilities.setCapability("deviceName", "emulator-5554");
        capabilities.setCapability("app", "<the apk goes here>");
        try {
            wd = new AndroidDriver(new URL("http://0.0.0.0:4723" + "/wd/hub"), capabilities);
            wd.installApp(apkpath);
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        return wd;
</snip>
## Environment

* Appium 1.6.2

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

[debug] [UiAutomator] Starting UIAutomator
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","emulator-5554","shell","uiautomator","runtest","AppiumBootstrap.jar","-c","io.appium.android.bootstrap.Bootstrap","-e","pkg","com.android.chrome","-e","disableAndroidWatchers",false,"-e","acceptSslCerts",false][error] [UiAutomator] UiAutomator exited unexpectedly with code 255, signal null
[debug] [UiAutomator] Moving to state 'stopped'

**Comment by mykola-mokhnach** [comment]
Use uiatomator2 for Android6+

**Comment by anu6986** [comment]
I added this capability now:

capabilities.setCapability("automationName", "UiAutomator2");

Now iI am getting this error:

<snip>
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1529666018030 (16:43:38 GMT+0530 (IST))
[error] [MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Error: read ECONNRESET
[error] [MJSONWP]     at JWProxy.proxy$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:152:13)
[error] [MJSONWP]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[error] [MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[error] [MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[error] [MJSONWP]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[error] [MJSONWP]     at <anonymous>
[info] [HTTP] <-- POST /wd/hub/session 500 27458 ms - 217
[info] [HTTP] 

</snip>

**Comment by mykola-mokhnach** [comment]
Please attach the full log. Also, why do you set activity name if browser name is already set? It seems like capabilities are incorrect.

**Comment by anu6986** [comment]
[appium-server-logs.txt](https://github.com/appium/appium/files/2127407/appium-server-logs.txt)
 I have attached the full logs now

**Comment by mykola-mokhnach** [comment]
> why do you set activity name if browser name is already set?

Closed as not an issue
