### ISSUE TITLE
Appium 1.7.2 - 1.8.1

### ISSUE THREAD

**Issue by shabsi4u** [appium/appium#10923]
## The problem

Clicks do not work for certain elements on the UI. This happens on all release versions > 1.7.2 all the way upto 1.8.1. The latest version of appium where these clicks work is 1.7.1. Owing to this I am stuck with using 1.6.5 and I am not able to use newer version of appium. This is critical looking at the newer iOS releases. Please fix this issue

## Environment

* Appium version (or git revision) that exhibits the issue: All versions above 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): 1.7.1
* Desktop OS/version used to run Appium: Mac OS Sierra
* Node.js version (unless using Appium.app|exe):  v9.11.1
* Mobile platform/version under test: iOS 11
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI, app

## Details

The app under test is build on react native. There are few modals in the app where these clicks do not work. The element can be found, but the click does not trigger the required actions.

## Link to Appium logs

https://gist.github.com/shabsi4u/a65f987ebeb0aaa06b62e3d8bb48fda6

## Code To Reproduce Issue [ Good To Have ]

Sample code:
```
 public void navigateToTestPage(final MobileDriver driver) {
        driver.findElementByAccessibilityId(ComposeConstants.COMPOSE_PRODUCT).click();
        return this;
    }
```

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/facebook/WebDriverAgent/issues

Closed as third party issue
