### ISSUE TITLE
How to solve [INSTALL_PARSE_FAILED_NO_CERTIFICATES

### ISSUE THREAD

**Issue by liangyuan531** [appium/appium#10924]
## The problem

[INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl1973269417.tmp/base.apk: META-INF/CERT.SF indicates /data/app/vmdl1973269417.tmp/base.apk is signed using APK Signature Scheme v2, but no such signature was found. Signature stripped?]'; Code: '1'

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Win10
* Node.js version (unless using Appium.app|exe): 
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

[MJSONWP] Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\Deveoper\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 install D\:\\apps\\android\\app-release.apk' exited with code 1'; Stderr: 'adb: failed to install D:\apps\android\app-release.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl1973269417.tmp/base.apk: META-INF/CERT.SF indicates /data/app/vmdl1973269417.tmp/base.apk is signed using APK Signature Scheme v2, but no such signature was found. Signature stripped?]'; Code: '1'
[MJSONWP]     at ADB.execFunc$ (C:\Users\Deveoper\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:317:13)
[MJSONWP]     at tryCatch (C:\Users\Deveoper\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Deveoper\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\Deveoper\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (C:\Users\Deveoper\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[MJSONWP]     at 
[HTTP] <-- POST /wd/hub/session 500 11536 ms - 740
[HTTP]

**Comment by mykola-mokhnach** [comment]
1. Try appium@beta
2. Try with `noSign` capability

**Comment by liangyuan531** [comment]
@mykola-mokhnach  I tried soSign, it doesn't work

**Comment by mykola-mokhnach** [comment]
Also the full server log is needed from appium@beta if it still fails.
