### ISSUE TITLE
Not able to automate unity 3D app using appium. Is there any possiblity ?

### ISSUE THREAD

**Issue by ashoksqa** [appium/appium#10921]
Is there any possiblity for unity 3D app automation using appium.

**Comment by mykola-mokhnach** [comment]
Check https://www.youtube.com/watch?v=KwmanWMTh10

**Comment by Kitty2014** [comment]
http://wetest.qq.com/product/cube?from=content_testerhome   @ashoksqa

**Comment by mykola-mokhnach** [comment]
In appium forum would be a better place for such questions

**Comment by ashoksqa** [comment]
@mykola-mokhnach Thannk you so much for the response. I will check it.
