### ISSUE TITLE
Not able to click on Allow button in the Safari browser popup ( Appium 1.8.2  ) AND also very slow while using sendKeys method

### ISSUE THREAD

**Issue by ashoksqa** [appium/appium#10920]
## The problem

1.Launch safri broweser and clicked one button
2.It displayed popup with BLOCK and ALLOW buttons (This site is attempting to open a pop-up window)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.2 beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: When we run the same manually then the same popup not displayed.Only when we running through appium
* Node.js version (unless using Appium.app|exe): 8.8.0
* Mobile platform/version under test: 11.4 iOS - iPhone 8
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:
java-client : 5.0.4

## Details

I tried all possible cases. Some times after 5 mins '**driver.switchTo().alert();**' working and sometimes not working

## Link to Appium logs

https://github.com/ashoksqa/HybridAutomationFramework/blob/4984b51ce687db3020db8e439fe3c8cfdaa34696/Appium%20Logs

## Code To Reproduce Issue [ Good To Have ]
Appium Setup : 
public void appiumDriverIOS(boolean fullReset, boolean noReset) {
			cap = new DesiredCapabilities();
			cap.setCapability("clearSystemFiles", true);
			service = AppiumDriverLocalService.buildService(new AppiumServiceBuilder()
					.usingDriverExecutable(new File(nodeExecutablePath)).withAppiumJS(new File(appiumJS_Path))
					.withCapabilities(cap).withIPAddress("127.0.0.1").usingAnyFreePort());
	
			DesiredCapabilities cap = new DesiredCapabilities();
	
			cap.setCapability("xcodeOrgId", "92C2BE6YZQ");
			cap.setCapability("xcodeSigningId", "iPhone Developer");
			cap.setCapability(MobileCapabilityType.BROWSER_NAME, deviceInfo(Trow, 5));
			cap.setCapability(MobileCapabilityType.DEVICE_NAME, deviceInfo(Trow, 3));
			cap.setCapability("platformName", deviceInfo(Trow, 1));
			cap.setCapability("udid", deviceInfo(Trow, 0));
			cap.setCapability("newCommandTimeout", 120);
			cap.setCapability("webkitResponseTimeout", 25000);
			cap.setCapability("automationName", "XCUITest");
			// cap.setCapability("autoWebview", true);
			cap.setCapability(MobileCapabilityType.NO_RESET, noReset);
			cap.setCapability("platformVersion", deviceInfo(Trow, 4));
			cap.setCapability("startIWDP", true);
			cap.setCapability("commandTimeouts", "40000");
			cap.setCapability("autoGrantPermissions", true);
			// cap.setCapability("doNotPauseOnExceptionsAndMuteConsole", false);
			cap.setCapability("useNewWDA", true);
			cap.setCapability("safariInitialUrl",
					"https://drive.google.com/file/d/1leV7mcA_hG-6j7VHIMi6jwmto5bjzLZc/view?usp=sharing");
			String wdaLocalPort = Trow + randomNumString(3);
			cap.setCapability("wdaLocalPort", convertStrToInt(wdaLocalPort));
			cap.setCapability("webkitDebugProxyPort", convertStrToInt(Trow + randomNumString(4)));
	
			driver = new IOSDriver<MobileElement>(service, cap);
			driver.manage().timeouts().implicitlyWait(120, TimeUnit.SECONDS);
	
		}

**Comment by ashoksqa** [comment]
@imurchie  Please help me on this. I have blocked .Except this all are working fine for me.

**Comment by ashoksqa** [comment]
I have done work around and it`s wrking by using switch to context to NATIVE_APP and finding by name as 'Allow'.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
