### ISSUE TITLE
admc/wd version 1.10 breaks tests for multiple drivers

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#10937]
* uiautomator2-driver, xcuitest-driver have broken tests
* wd/lib/actions.js line 21: `if(el && !(el instanceof Element)) {` is getting an error `Right-hand side of 'instanceof' is not callable` repeatedly
* I think it's a problem with a third party dependency because nothing in the source between 1.9.0 and 1.10.0 would explain this problem
* I'll look into it myself and post a patch to `admc/wd`

**Comment by dpgraham** [comment]
Seems to be an issue with `PromiseElement` not being an instanceof `Element`

**Comment by imurchie** [comment]
But it works if you just revert to 1.9.0 without changing anything in the dependencies.

For some reason `Element` is not a constructor any longer.

**Comment by imurchie** [comment]
The problem is a circularity in internal dependencies.
