### ISSUE TITLE
Attributes text is different on different MacOS/XCode/iOS versions

### ISSUE THREAD

**Issue by olezhkalviv** [appium/appium#10932]
## The problem

There is a difference between how 'Value' attribute is retrived from the same application same version and same Appium but with different XCode/MacOS/iOS

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: Mac OS High Sierra 10.13.1 / 10.13.3
* Node.js version (unless using Appium.app|exe): -
* Mobile platform/version under test: iOS 11.1 / 11.4 (XCode 9.1 / XCode 9.4.1)
* Real device or emulator/simulator: simultor
* Appium CLI or Appium.app|exe: app
* Lang: C#

## Details

When getting 'Value' attribute - for 'Mac OS High Sierra 10.13.1 / iOS 11.1 / XCode 9.1' it returns:

> "Server is not reached. Try again. (55)"

for 'Mac OS High Sierra 10.13.3 / iOS 11.4 / XCode 9.4.1' - it returns:

> "Server is not reached.\r\nTry again. (55)"

It could be the issue with C# appium driver, but also in Appium logs there is a difference what returns, please see below

## Link to Appium logs

Mac OS High Sierra 10.13.1 / iOS 11.1 / XCode 9.1

```
[info] [HTTP] --> GET /wd/hub/session/6473d9d9-9830-436d-96ce-43d86ba0d520/element/60000000-0000-0000-964E-000000000000/attribute/value
[info] [HTTP] {}
[debug] [MJSONWP] Calling AppiumDriver.getAttribute() with args: ["value","60000000-0000-0000-964E-000000000000","6473d9d9-9830-436d-96ce-43d86ba0d520"]
[debug] [XCUITest] Executing command 'getAttribute'
[debug] [JSONWP Proxy] Proxying [GET /element/60000000-0000-0000-964E-000000000000/attribute/value] to [GET http://localhost:8100/session/D2B8AD11-37AA-4212-ACCB-6F2483B99D09/element/60000000-0000-0000-964E-000000000000/attribute/value] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"Server is not reached. Try again. (55)\",\n  \"sessionId\" : \"D2B8AD11-37AA-4212-ACCB-6F2483B99D09\",\n  \"status\" : 0\n}"
[debug] [MJSONWP] Responding to client with driver.getAttribute() result: "Server is not reached. Try again. (55)"
```

Mac OS High Sierra 10.13.3 / iOS 11.4 / XCode 9.4.1

```
[info] [HTTP] --> GET /wd/hub/session/e238bf38-a5e3-4c80-8926-f530452c030a/element/60000000-0000-0000-A382-000000000000/attribute/value
[info] [HTTP] {}
[debug] [MJSONWP] Calling AppiumDriver.getAttribute() with args: ["value","60000000-0000-0000-A382-000000000000","e238bf38-a5e3-4c80-8926-f530452c030a"]
[debug] [XCUITest] Executing command 'getAttribute'
[debug] [JSONWP Proxy] Proxying [GET /element/60000000-0000-0000-A382-000000000000/attribute/value] to [GET http://localhost:8100/session/0722C6DA-0DF5-435A-991B-B83743116187/element/60000000-0000-0000-A382-000000000000/attribute/value] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"Server is not reached.\\nTry again. (55)\",\n  \"sessionId\" : \"0722C6DA-0DF5-435A-991B-B83743116187\",\n  \"status\" : 0\n}"
[debug] [MJSONWP] Responding to client with driver.getAttribute() result: "Server is not reached.\nTry again. (55)"
```

The error is assigned in Swift by assigning 'message' variable:
let message = "\(errorTitle)\n\(errorMessage)"

**Comment by mykola-mokhnach** [comment]
This behaviour is controlled by the third party component https://github.com/facebook/WebDriverAgent/pulls and there is nothign that can be done about it on our side.
