### ISSUE TITLE
Certificate installation on iOS problem

### ISSUE THREAD

**Issue by glinius** [appium/appium#10940]
## The problem

I'm trying to deploy a certificate onto iOS simulator 11.4 as per http://appium.io/docs/en/writing-running-appium/ios/ios-xctest-install-certificate/ instruction

## Environment

* Appium version 1.8,1
* Desktop OS/version used to run Appium: MacOSX 10.13.5
* Node.js version (unless using Appium.app|exe): 9.4.0
* Mobile platform/version under test: iOS 
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI / embedded

## Details

Looking into https://github.com/nodejs/node/blob/master/lib/buffer.js shouldn't the encoding in _certificate.js_ be **latin1**?

## Link to Appium logs

https://gist.github.com/glinius/d32094f78ed652bda460ab04b80926f1

## Code To Reproduce Issue [ Good To Have ]
```
Map<String, Object> args = new HashMap<>();
byte[] byteContent = Files.readAllBytes(new File("custom.cer").toPath());
args.put("content", Base64.getEncoder().encodeToString(byteContent));
driver.executeScript("mobile: installCertificate", args);
```

**Comment by mykola-mokhnach** [comment]
Thanks you for the report

Can you please try to replace encoding with `binary` or `ascii` and rerun the test? it is necessary to run `gulp transpile` and then restart node after the fix is done in order to apply the changes.

**Comment by glinius** [comment]
@mykola-mokhnach thanks for prompt response, I do confirm that using `ascii`  fixes the issue. Just in case my certificate looks like:

> /tmp/cert.crt: text/plain; charset=us-ascii

**Comment by mykola-mokhnach** [comment]
Thanks, I'll create a PR. Meanwhil,m you're welcome to also contribute to the project if you know how to fix a problem
