### ISSUE TITLE
Appium XCUITest Driver MITM certificate installation - "Install" pop-up cannot be clicked

### ISSUE THREAD

**Issue by glinius** [appium/appium#10942]
## The problem

I'm trying to deploy a certificate onto iOS simulator 11.4 as per http://appium.io/docs/en/writing-running-appium/ios/ios-xctest-install-certificate/ instruction

## Environment
* Appium version 1.8,1
* Desktop OS/version used to run Appium: MacOSX 10.13.5
* Node.js version (unless using Appium.app|exe): 9.4.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI / embedded

## Details

At least on iOS 11.4 simulator _certificate.js_ script fails to click on "Install" button (3rd one, which is a pop-up at the bottom of the screen)

I've managed to get this working by changing selector type to _xpath_ and using the following expression:

```
value: '//XCUIElementTypeSheet/descendant::*/XCUIElementTypeButton[@label = "Install"]'
```

## Link to Appium logs

https://gist.github.com/glinius/a2564727227c14ae2450f1f4043059b5

```
Map<String, Object> args = new HashMap<>();
byte[] byteContent = Files.readAllBytes(new File("custom.cer").toPath());
args.put("content", Base64.getEncoder().encodeToString(byteContent));
driver.executeScript("mobile: installCertificate", args);
```

**Comment by mykola-mokhnach** [comment]
The problem might be here:

> [Xcode]  - -[XCElementSnapshot hitPoint]: unrecognized selector sent to instance 0x6000003808f0. Will use element frame for hit point calculation instead

Try this with appium@beta

**Comment by glinius** [comment]
It doesn't really help, the relevant log part is:

`[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/BFE7B7A2-400D-4CF7-BF6D-DAE4F783A1CE/element] with body: {"using":"class chain","value":"**/XCUIElementTypeSheet/**/XCUIElementTypeButton[`label == 'Install'`]"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"5C000000-0000-0000-3553-010000000000"},"sessionId":"BFE7B7A2-400D-4CF7-BF6D-DAE4F783A1CE","status":0}
[debug] [JSONWP Proxy] Proxying [POST /element/5C000000-0000-0000-3553-010000000000/click] to [POST http://localhost:8100/session/BFE7B7A2-400D-4CF7-BF6D-DAE4F783A1CE/element/5C000000-0000-0000-3553-010000000000/click] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: {"status":0,"id":"5C000000-0000-0000-3553-010000000000","value":"","sessionId":"BFE7B7A2-400D-4CF7-BF6D-DAE4F783A1CE"}
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/BFE7B7A2-400D-4CF7-BF6D-DAE4F783A1CE/element] with body: {"using":"accessibility id","value":"Done"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"using":"accessibility id","value":"Done","description":"unable to find an element"},"sessionId":"BFE7B7A2-400D-4CF7-BF6D-DAE4F783A1CE","status":7}
[debug] [MJSONWP] Matched JSONWP error code 7 to NoSuchElementError`

However Appium fails to click on the "Install" button therefore "Done" button is never found

**Comment by mykola-mokhnach** [comment]
It is not a good idea to use xpath, since it may introduce serious performance hits. Also, it would be interesting to know what is the difference between 

```
**/XCUIElementTypeSheet/**/XCUIElementTypeButton[`label == 'Install'`]
```

```
//XCUIElementTypeSheet/descendant::*/XCUIElementTypeButton[@label = "Install"]
```

and 

```
//XCUIElementTypeSheet//XCUIElementTypeButton[@label = "Install"]
```

locators.

In theory they all should match the same element.
