### ISSUE TITLE
[MJSONWP] Encountered internal error running command: Error: No open port found

### ISSUE THREAD

**Issue by cuhavp** [appium/appium#10946]
## The problem

could not start appium server

## Environment

* Appium 1.7.2
* Desktop OS/version used to run Appium: mac OS

## Details
[MJSONWP] Encountered internal error running command: Error: No open port found
  

## Link to Appium logs
https://gist.github.com/cuhavp/6cb4efd4d4dc0a04f9d6a5f8facc8e08

## Code To Reproduce Issue [ Good To Have ] I'm using Koltin

val service = AppiumDriverLocalService.buildService(AppiumServiceBuilder().usingAnyFreePort().withArgument(GeneralServerFlag.SESSION_OVERRIDE))
            service.start()
            var capabilities = DesiredCapabilities();
            capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, Platform.ANDROID)
            capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "android")
            capabilities.setCapability(MobileCapabilityType.APP, File("apps").walkTopDown().filter { p -> p.toString().endsWith(".apk") }.first().absolutePath);
            capabilities.setCapability(MobileCapabilityType.NO_RESET, false)
            capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.ANDROID_UIAUTOMATOR2)
            capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 900)

            capabilities.setCapability(AndroidMobileCapabilityType.CHROMEDRIVER_EXECUTABLE, "/Users/dtha/Desktop/chromedriver")
            return AppiumDriver(service.url, capabilities)

**Comment by mykola-mokhnach** [comment]
Is it reproducible with the latest appium version
