### ISSUE TITLE
XCUITest doesn't reset with updatedWDABundleId

### ISSUE THREAD

**Issue by mayureshshirodkar** [appium/appium#10945]
## The problem

On starting a WebdriverAgent session, if there is a failure in the kick off, there is a reset that occurs as per the logs. But the logs show that the reset doesn't pick the updated bundle id, but the default one.

**On a reset:**
[debug] [XCUITest] Successfully reset '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj/project.pbxproj' with bundle id 'com.facebook.WebDriverAgentRunner'

**On Deleting the WebDriverAgent app and starting again, the updated bundle id is used.**
[debug] [XCUITest] Successfully updated '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj/project.pbxproj' with bundle id 'com.xxx.WebDriverAgentRunner'

## Environment

* Appium version (or git revision) that exhibits the issue: **1.8.2-beta**
* Desktop OS/version used to run Appium: **MacOS v10.13.5**
* Mobile platform/version under test: **iOS 11.4**
* Real device or emulator/simulator: **iPhone 6**

## Details
Capabilities used:
		iOSCapabilities.setCapability("xcodeOrgId",Base.getValue("xcodeorg_id"));
		iOSCapabilities.setCapability("xcodeSigningId","iPhone Developer");
		iOSCapabilities.setCapability("deviceName", Base.getValue("ios_device"));
		iOSCapabilities.setCapability("platformVersion", utils.findIphoneVersion());
		iOSCapabilities.setCapability("automationName", "XCUITest");
		iOSCapabilities.setCapability("udid", utils.findIphoneUDID());
		iOSCapabilities.setCapability("startIWDP",true);
		iOSCapabilities.setCapability("updatedWDABundleId","com.xxx.WebDriverAgentRunner");
 		iOSCapabilities.setCapability("wdaConnectionTimeout", 60000);
		iOSCapabilities.setCapability("wdaStartupRetries", 4);
		iOSCapabilities.setCapability("wdaStartupRetryInterval", 10000);
		iOSCapabilities.setCapability("showXcodeLog", true);

## Link to Appium logs

XcuiTest Reset gist: https://gist.github.com/mayureshshirodkar/92dbd154a75977a61e2fdb5ea888a0db

XcuiTest Update gist(WebDriverAgent is removed):
https://gist.github.com/mayureshshirodkar/a8df0d07c1375519085295115e25c8f4

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-xcuitest-driver/blob/9dbbeb9f7a819abba76d8ce18928127d5308c02b/lib/driver.js#L414

---

- Use running WDA

https://gist.github.com/mayureshshirodkar/92dbd154a75977a61e2fdb5ea888a0db#file-xcuitestreset-txt-L68-L75

```
[debug] [XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"11.4\",\n      \"sdkVersion\" : \"11.3\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"11.4\",\n      \"ip\" : \"169.254.108.201\"\n    },\n    \"build\" : {\n      \"time\" : \"Jun 24 2018 15:12:09\"\n    }\n  },\n  \"sessionId\" : \"874C4150-19A1-41B2-A7C9-C42ACEBD98C6\",\n  \"status\" : 0\n}"
[XCUITest] Will reuse previously cached WDA instance at 'http://localhost:8100/'. Set the wdaLocalPort capability to a value different from 8100 if this is an undesired behavior.
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1529990954537 (10:59:14 GMT+0530 (IST))
[XCUITest] Using provided WebdriverAgent at 'http://localhost:8100/'
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1529990954539 (10:59:14 GMT+0530 (IST))
[debug] [XCUITest] Sending createSession command to WDA
```

---

- Update

https://gist.github.com/mayureshshirodkar/a8df0d07c1375519085295115e25c8f4#file-xcuitestupdate-txt-L68-L75

```
[debug] [XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] WDA is not listening at 'http://localhost:8100/'
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1529991167861 (11:02:47 GMT+0530 (IST))
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing running processes 'xcodebuild.*771c2184b4beaa9c61de1af5027b241904076351, iproxy 8100' for the device 771c2184b4beaa9c61de1af5027b241904076351...
[debug] [XCUITest] 'pgrep -nif xcodebuild.*771c2184b4beaa9c61de1af5027b241904076351' didn't detect any matching processes. Return code: 1

```

**Comment by mayureshshirodkar** [comment]
@KazuCocoa Are this changes deployed in the Beta?

**Comment by KazuCocoa** [comment]
No, not yet

**Comment by KazuCocoa** [comment]
@mayureshshirodkar 
You can try with the latest `appium@beta`
That requires to use new WDA to handle product bundle id correctly.
