### ISSUE TITLE
[XCUITest] Connection to WDA timed out error when running on real device

### ISSUE THREAD

**Issue by sylviancb** [appium/appium#10958]
## The problem

When I run my tests from Jenkins, on a real device the connection to WDA will time out. Restarting appium and WDA won't fix the issue. I have to physically reconnect the device in order for the tests to work again. I also tried the latest version of appium beta (1.8.1), but the issue still persists.

[debug] [XCUITest] Connection to WDA timed out
[debug] [iProxy] recv failed: Operation not permitted
[debug] [RemoteDebugger] WebKit remote debugger socket disconnected

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.0
* Node.js version (unless using Appium.app|exe): 7.7.1
* Mobile platform/version under test: iPhone 7/11.2.6
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI
* MAC OS version: 10.13.5
* Xcode version: 9.4.1

## Link to Appium logs

https://gist.github.com/sylviancb/5e4984341ddfad7051cfef3f0942b616

**Comment by mykola-mokhnach** [comment]
Try appium@beta. If this not help then there is nothing that can be done on Appium side when WebDriverAgent stops responding.
