### ISSUE TITLE
issues appium-uiautomator2-server-v1.12.0.apk 

### ISSUE THREAD

**Issue by JohnE4528** [appium/appium#10954]
# The problem
when executing appium desktop 1.6.2 and appium 1.8.1 is showing me an error and not running the emulator

## Environment

* Appium version 1.8.1

* Desktop kubuntu 18.4
* Node.js version v8.10.0
* Mobile platform android 6.0 and 7.1.1
* simulator:
## Details

when performing a start session on the appium desktop with the following desired capabilities
{
  "platformName": "Android",
  "platformVersion": "7.1.1",
  "deviceName": "Nexus 5x API 23",
  "noReset": true,
  "appPackage": "com.example.android.contactmanager",
  "appActivity": "com.example.android.contactmanager.ContactManager",
  "automationName": "uiautomator2",
  "app": "/home/john-sarmiento/Android/APK/ContactManager.apk"
}
 Msreata an error message and does not reliably connect to the device
this is the message that shows

An unknown server-side error occurred while processing the command. Original error: Could not sign with default certificate. Original error Command '/ usr / lib / jvm / java-8-oracle / bin / java -jar /tmp/.mount_appiumCl4ZdG/app/resources/app/node_modules/appium/node_modules/appium-adb/jars/sign.jar / tmp / .mount_appiumCl4ZdG / app / resources / app / node_modules / appium / node_modules / appium-uiautomator2-server / apks / appium-uiautomator2-server-v1.12.0.apk --override 'exited with code 1

the executing the appium-doctor informs me that all the configurations are ok-
--this is the log that shows me appium-server
[info] [35m[Appium][39m Welcome to Appium v1.8.1
[info] [35m[Appium][39m Appium REST http interface listener started on 0.0.0.0:4723[info] [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/sessions[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[MJSONWP][39m Calling AppiumDriver.getSessions() with args: []
[debug] [35m[MJSONWP][39m Responding to client with driver.getSessions() result: []
[info] [35m[HTTP][39m [37m<-- GET /wd/hub/sessions [39m[32m200[39m [90m6 ms - 40[39m
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{"desiredCapabilities":{"app":"/home/john-sarmiento/Android/APK/ContactManager.apk","appActivity ":"com.example.android.contactmanager.ContactManager","appPackage":"com.example.android.contactmanager","automationName":"uiautomator2","deviceName":"Nexus 5x API 23","noReset":true,"platformName":"Android","platformVersion":"7.1.1","newCommandTimeout":0,"connectHardwareKeyboard":true}}[39m
[debug] [35m[MJSONWP][39m Calling AppiumDriver.createSession() with args: [{"app":"/home/john-sarmiento/Android/APK/ContactManager.apk","appActivity ":"com.example.android.contactmanager.ContactManager","appPackage":"com.example.android.contactmanager","automationName":"uiautomator2","deviceName":"Nexus 5x API 23","noReset":true,"platformName":"Android","platformVersion":"7.1.1","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1530047442282 (16:10:42 GMT-0500 (-05))
[info] [35m[Appium][39m Creating new AndroidUiautomator2Driver (v1.12.0) session
[info] [35m[Appium][39m Capabilities:
[info] [35m[Appium][39m   app: /home/john-sarmiento/Android/APK/ContactManager.apk
[info] [35m[Appium][39m   appActivity : com.example.android.contactmanager.ContactManager
[info] [35m[Appium][39m   appPackage: com.example.android.contactmanager
[info] [35m[Appium][39m   automationName: uiautomator2
[info] [35m[Appium][39m   deviceName: Nexus 5x API 23
[info] [35m[Appium][39m   noReset: true
[info] [35m[Appium][39m   platformName: Android
[info] [35m[Appium][39m   platformVersion: 7.1.1
[info] [35m[Appium][39m   newCommandTimeout: 0
[info] [35m[Appium][39m   connectHardwareKeyboard: true
[debug] [35m[BaseDriver][39m Creating session with MJSONWP desired capabilities: {"app":"/home/john-sarmient...
[warn] [35m[BaseDriver][39m The following capabilities were provided, but are not recognized by appium: appActivity , connectHardwareKeyboard.
[info] [35m[BaseDriver][39m Session created with session id: 07602d93-a493-4786-b565-652ce9426eec
[info] [35m[BaseDriver][39m Using local app '/home/john-sarmiento/Android/APK/ContactManager.apk'
[debug] [35m[UiAutomator2][39m Checking whether app is actually present
[debug] [35m[AndroidDriver][39m Getting Java version
[info] [35m[AndroidDriver][39m Java version is: 1.8.0_171
[info] [35m[ADB][39m Checking whether adb is present
[info] [35m[ADB][39m Found 2 'build-tools' folders under '/home/john-sarmiento/Android/Sdk' (newest first):
[info] [35m[ADB][39m     /home/john-sarmiento/Android/Sdk/build-tools/28.0.0
[info] [35m[ADB][39m     /home/john-sarmiento/Android/Sdk/build-tools/27.0.3
[info] [35m[ADB][39m Using adb from /home/john-sarmiento/Android/Sdk/platform-tools/adb
[info] [35m[AndroidDriver][39m Retrieving device list
[debug] [35m[ADB][39m Trying to find a connected android device
[debug] [35m[ADB][39m Getting connected devices...
[debug] [35m[ADB][39m 1 device(s) connected
[info] [35m[AndroidDriver][39m Looking for a device with Android '7.1.1'
[debug] [35m[ADB][39m Setting device id to emulator-5554
[info] [35m[ADB][39m Getting device platform version
[debug] [35m[ADB][39m Running '/home/john-sarmiento/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell getprop ro.build.version.release'
[debug] [35m[ADB][39m Current device property 'ro.build.version.release': 7.1.1
[info] [35m[AndroidDriver][39m Using device: emulator-5554
[debug] [35m[ADB][39m Setting device id to emulator-5554
[debug] [35m[ADB][39m Running '/home/john-sarmiento/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk'
[debug] [35m[ADB][39m Current device property 'ro.build.version.sdk': 25
[debug] [35m[ADB][39m Device API level: 25
[debug] [35m[AndroidDriver][39m Parsing package and activity from app manifest
[info] [35m[ADB][39m Using apkanalyzer from /home/john-sarmiento/Android/Sdk/tools/bin/apkanalyzer
[debug] [35m[ADB][39m Starting '/home/john-sarmiento/Android/Sdk/tools/bin/apkanalyzer' with args ["-h","manifest","print","/home/john-sarmiento/Android/APK/ContactManager.apk"][info] [35m[ADB][39m Package name: 'com.example.android.contactmanager'
[info] [35m[ADB][39m Main activity name: '.ContactManager'
[debug] [35m[AndroidDriver][39m Parsed package and activity are: com.example.android.contactmanager/.ContactManager
[info] [35m[ADB][39m Getting device platform version
[debug] [35m[ADB][39m Running '/home/john-sarmiento/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell getprop ro.build.version.release'
[debug] [35m[ADB][39m Current device property 'ro.build.version.release': 7.1.1
[debug] [35m[ADB][39m Running '/home/john-sarmiento/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell wm size'[debug] [35m[ADB][39m Running '/home/john-sarmiento/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell wm density'[debug] [35m[ADB][39m Running '/home/john-sarmiento/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell getprop ro.product.model'
[debug] [35m[ADB][39m Current device property 'ro.product.model': Android SDK built for x86
[debug] [35m[ADB][39m Running '/home/john-sarmiento/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell getprop ro.product.manufacturer'
[debug] [35m[ADB][39m Current device property 'ro.product.manufacturer': Google
[debug] [35m[ADB][39m Device API level: 25
[debug] [35m[ADB][39m Running '/home/john-sarmiento/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop io.appium.uiautomator2.server'[debug] [35m[ADB][39m Checking app cert for /tmp/.mount_appiumY2dAWv/app/resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v1.12.0.apk
[info] [35m[ADB][39m Using apksigner from /home/john-sarmiento/Android/Sdk/build-tools/28.0.0/apksigner
[debug] [35m[ADB][39m Starting '/home/john-sarmiento/Android/Sdk/build-tools/28.0.0/apksigner' with args 'verify,--print-certs,/tmp/.mount_appiumY2dAWv/app/resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v1.12.0.apk'[debug] [35m[ADB][39m '/tmp/.mount_appiumY2dAWv/app/resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v1.12.0.apk' is not signed with debug cert.
[debug] [35m[ADB][39m Zip-aligning '/tmp/.mount_appiumY2dAWv/app/resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v1.12.0.apk'
[info] [35m[ADB][39m Checking whether zipalign is present
[info] [35m[ADB][39m Using zipalign from /home/john-sarmiento/Android/Sdk/build-tools/28.0.0/zipalign
[debug] [35m[ADB][39m Signing '/tmp/.mount_appiumY2dAWv/app/resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v1.12.0.apk' with default cert
[debug] [35m[ADB][39m Starting '/home/john-sarmiento/Android/Sdk/build-tools/28.0.0/apksigner' with args 'sign,--key,/tmp/.mount_appiumY2dAWv/app/resources/app/node_modules/appium/node_modules/appium-adb/keys/testkey.pk8,--cert,/tmp/.mount_appiumY2dAWv/app/resources/app/node_modules/appium/node_modules/appium-adb/keys/testkey.x509.pem,/tmp/.mount_appiumY2dAWv/app/resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v1.12.0.apk'[warn] [35m[ADB][39m Cannot use apksigner tool for signing. Defaulting to sign.jar. Original error: Command '/home/john-sarmiento/Android/Sdk/build-tools/28.0.0/apksigner sign --key /tmp/.mount_appiumY2dAWv/app/resources/app/node_modules/appium/node_modules/appium-adb/keys/testkey.pk8 --cert /tmp/.mount_appiumY2dAWv/app/resources/app/node_modules/appium/node_modules/appium-adb/keys/testkey.x509.pem /tmp/.mount_appiumY2dAWv/app/resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v1.12.0.apk' exited with code 1; StdErr: Exception in thread "main" java.nio.file.FileSystemException: /tmp/.mount_appiumY2dAWv/app/resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v1.12.0.apk: Sistema de archivos de solo lectura
[warn] [35m[ADB][39m 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
[warn] [35m[ADB][39m 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
[warn] [35m[ADB][39m 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
[warn] [35m[ADB][39m 	at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:447)
[warn] [35m[ADB][39m 	at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
[warn] [35m[ADB][39m 	at java.nio.file.Files.move(Files.java:1395)
[warn] [35m[ADB][39m 	at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:342)
[warn] [35m[ADB][39m 	at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:89)
[warn] [35m[ADB][39m 
[debug] [35m[ADB][39m Resigning apk.[debug] [35m[UiAutomator2][39m Deleting UiAutomator2 session
[debug] [35m[UiAutomator2][39m Deleting UiAutomator2 server session
[warn] [35m[UiAutomator2][39m Did not get confirmation UiAutomator2 deleteSession worked; Error was: Error: Trying to proxy a session command without session id
[debug] [35m[ADB][39m Running '/home/john-sarmiento/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop com.example.android.contactmanager'[debug] [35m[ADB][39m Removing forwarded port socket connection: 8200 
[debug] [35m[ADB][39m Running '/home/john-sarmiento/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp\:8200'
[debug] [35m[ADB][39m Running '/home/john-sarmiento/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp\:8200'
[warn] [35m[UiAutomator2][39m Unable to remove port forward 'Error executing adbExec. Original error: 'Command '/home/john-sarmiento/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp\:8200' exited with code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''
[debug] [35m[BaseDriver][39m Event 'newSessionStarted' logged at 1530047445075 (16:10:45 GMT-0500 (-05))
[error] [35m[MJSONWP][39m Encountered internal error running command: Error: Could not sign with default certificate. Original error Command '/usr/lib/jvm/java-8-oracle/bin/java -jar /tmp/.mount_appiumY2dAWv/app/resources/app/node_modules/appium/node_modules/appium-adb/jars/sign.jar /tmp/.mount_appiumY2dAWv/app/resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v1.12.0.apk --override' exited with code 1
[error] [35m[MJSONWP][39m     at ADB.callee$0$0$ (/tmp/.mount_appiumY2dAWv/app/resources/app/node_modules/appium/node_modules/appium-adb/lib/tools/apk-signing.js:79:13)
[error] [35m[MJSONWP][39m     at tryCatch (/tmp/.mount_appiumY2dAWv/app/resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[error] [35m[MJSONWP][39m     at GeneratorFunctionPrototype.invoke [as _invoke] (/tmp/.mount_appiumY2dAWv/app/resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[error] [35m[MJSONWP][39m     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/tmp/.mount_appiumY2dAWv/app/resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[error] [35m[MJSONWP][39m     at GeneratorFunctionPrototype.invoke (/tmp/.mount_appiumY2dAWv/app/resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[error] [35m[MJSONWP][39m     at <anonymous>
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[31m500[39m [90m2796 ms - 521[39m
[info] [35m[HTTP][39m [90m[39m

**Comment by mykola-mokhnach** [comment]
> [debug] �[35m[ADB]�[39m Signing '/tmp/.mount_appiumY2dAWv/app/resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v1.12.0.apk' with default cert
[debug] �[35m[ADB]�[39m Starting '/home/john-sarmiento/Android/Sdk/build-tools/28.0.0/apksigner' with args 'sign,--key,/tmp/.mount_appiumY2dAWv/app/resources/app/node_modules/appium/node_modules/appium-adb/keys/testkey.pk8,--cert,/tmp/.mount_appiumY2dAWv/app/resources/app/node_modules/appium/node_modules/appium-adb/keys/testkey.x509.pem,/tmp/.mount_appiumY2dAWv/app/resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v1.12.0.apk'[warn] �[35m[ADB]�[39m Cannot use apksigner tool for signing. Defaulting to sign.jar. Original error: Command '/home/john-sarmiento/Android/Sdk/build-tools/28.0.0/apksigner sign --key /tmp/.mount_appiumY2dAWv/app/resources/app/node_modules/appium/node_modules/appium-adb/keys/testkey.pk8 --cert /tmp/.mount_appiumY2dAWv/app/resources/app/node_modules/appium/node_modules/appium-adb/keys/testkey.x509.pem /tmp/.mount_appiumY2dAWv/app/resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v1.12.0.apk' exited with code 1; StdErr: Exception in thread "main" java.nio.file.FileSystemException: /tmp/.mount_appiumY2dAWv/app/resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v1.12.0.apk: Sistema de archivos de solo lectura

You must make the file(s) writable. 

Closed as not an issue.

**Comment by sevetseh28** [comment]
Same is happening to me. @mykola-mokhnach , you shouldnt have closed this. We cannot make those files writeable since they are on /tmp/ . They are automatically created/removed when you open/close the app.

**Comment by imurchie** [comment]
You need to move the app off the mounted drive and onto your harddrive. Appium will not work otherwise.

**Comment by jaelson-ciandt** [comment]
The same is happening to me. Someone knows how to solve that?

**Comment by yifei325325** [comment]
> Same is happening to me. @mykola-mokhnach , you shouldnt have closed this. We cannot make those files writeable since they are on /tmp/ . They are automatically created/removed when you open/close the app.

I have the same problem, but i work out it .  when you install the appium desk top , there is a option:
install for all users or only install for you. you should choose "only install for you ". because you are not the Administrator, have not right to writeable the file in "c:/program files/...". hope can help.

**Comment by jaelson-ciandt** [comment]
In my case, I just run appium-desktop-1.7.0-x86_64.AppImage as root and I keep getting write permission error.

**Comment by wenbinke** [comment]
I have the same issue `Error: Unable to access jarfile /tmp/.mount_appiumZ4Ewda/resources/app/node_modules/appium-adb/jars/sign.jar` with appium-desktop or appium on ubuntu.
