### ISSUE TITLE
Appium unable to launch iOS driver instance in real device

### ISSUE THREAD

**Issue by hsarmah09** [appium/appium#10959]
## The problem
I am trying to run existing test cases in iPad using Appium in Macbook. Appium does not return a new instance of iOS driver. It exits by throwing a timeout exception while changing context to webview.

## Environment

* Appium version (or git revision) that exhibits the issue:1.8.1
* Appium desktop version: 1.6.2
* Mac OS used to run Appium: 10.13.5
* iOS version under test: 11.2.6
* Real device or emulator/simulator: real device

## Link to Appium logs
https://gist.github.com/hsarmah09/09b48efe240b544e6d3218911135ee99

**Comment by mykola-mokhnach** [comment]
Try appium@beta

**Comment by FredsBruder** [comment]
i've got the same issue, it works now with appium@beta v1.8.2
