### ISSUE TITLE
Android 8 Oreo - appium is freezing

### ISSUE THREAD

**Issue by GrzegorzSidwa** [appium/appium#10950]
## The problem

During performing some tests on new devices with android 8 I've noticed that there is a problem with performing actions on elements (click/request for location). At first I thoguht that it is related to appium-dotnet-driver. But I've reproduced the issue on java-client. The behavior is that on some requests server is hanging. I tried both versions, with click, with touch actions. Nothing is working. Issue has been recreated on appium 1.7.2 and 1.8.0  with uiautomator2 server 1.7.0 and 1.12.0 with same results. Appium server is freezing and timeout is thrown.

**Exactly the same tests executed on device with Android 7 are working correctly.** 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2, 1.8.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS 10.13.2/Win10
* Node.js version (unless using Appium.app|exe): v7.7.3/v8.11.1
* Mobile platform/version under test: Android 8
* Real device or emulator/simulator: real device - Samsung Galaxy Tab 3
* Appium CLI or Appium.app|exe: CLI
* AUTOMATION_NAME: uiautomator2

## Link to Appium logs

_**logs from appium-dotnet-driver execution**_
> [HTTP] --> POST /wd/hub/session/23a503cc-e4b2-4e48-b750-63e4d362b354/touch/perform
[HTTP] {"actions":[{"action":"press","options":{"element":"dcbad3b6-d315-42f7-a574-8ebb59fead73"}},{"action":"wait","options":{"ms":500}},{"action":"release"}]}
[debug] [W3C] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"element":"dcbad3b6-d315-42f7-a574-8ebb59fead73"}},{"action":"wait","options":{"ms":500}},{"action":"release"}],"23a503cc-e4b2-4e48-b750-63e4d362b354"]
[UiAutomator2] calling get location: dcbad3b6-d315-42f7-a574-8ebb59fead73
[debug] [JSONWP Proxy] Proxying [GET /element/dcbad3b6-d315-42f7-a574-8ebb59fead73/location] to [GET http://localhost:8200/wd/hub/session/b493e649-4d2f-48ca-af88-a3ebacd59f51/element/dcbad3b6-d315-42f7-a574-8ebb59fead73/location] with body: {}

_**logs from java-client uiautomator2 execution**_
> [HTTP] --> POST /wd/hub/session/5ed3282d-6d05-4ce1-b61c-65e51b56e007/element/160bbe9a-b513-411a-98fe-072e96ee6576/click
[HTTP] {"id":"160bbe9a-b513-411a-98fe-072e96ee6576"}
[debug] [W3C] Calling AppiumDriver.click() with args: ["160bbe9a-b513-411a-98fe-072e96ee6576","5ed3282d-6d05-4ce1-b61c-65e51b56e007"]
[debug] [JSONWP Proxy] Proxying [POST /element/160bbe9a-b513-411a-98fe-072e96ee6576/click] to [POST http://localhost:8200/wd/hub/session/4ad824e3-8852-41ca-922b-c262b248a78d/element/160bbe9a-b513-411a-98fe-072e96ee6576/click] with body: {"element":"160bbe9a-b513-411a-98fe-072e96ee6576"}
[HTTP] <-- POST /wd/hub/session/5ed3282d-6d05-4ce1-b61c-65e51b56e007/element/160bbe9a-b513-411a-98fe-072e96ee6576/click - - ms - -

**_Logcat device logs_**
https://gist.github.com/GrzegorzSidwa/20785948221a23e6757ae80557b76c4c

**_Logcat appium-uiautomator2-server logs_**
https://gist.github.com/GrzegorzSidwa/0750ace36bcaaf2b3711f1bff92f6aaa

## Code To Reproduce Issue [ Good To Have ]

**_Java-client code_:**
`DesiredCapabilities capabilities = new DesiredCapabilities();
 capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "auto");
 capabilities.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
 capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, 
 AutomationName.ANDROID_UIAUTOMATOR2);
 AppiumDriver<MobileElement> driver = new AndroidDriver<>(
                    new URL("http://127.0.0.1:4723/wd/hub"),
                    capabilities);
  MobileElement element = driver.findElementById("android:id/tabs");
  final List<MobileElement> elementsByXPath = element.findElementsByXPath("//*");
  element.findElementsByXPath("//*").stream().filter((x) -> x.getText().equals("CONTROLS")).findFirst().get().click();
`
**_appium-dotnet-driver code_**
`AndroidDriver<AppiumWebElement> driver = new AndroidDriver<AppiumWebElement>(new Uri("http://127.0.0.1:4723/wd/hub"), caps, TimeSpan.FromMinutes(15));
var element = driver.FindElementById(@"android:id/tabs");
var appiumWebElement = element.FindElementsByXPath("//*").FirstOrDefault(x => x.Text == "CONTROLS");
new TouchAction(driver).Press(appiumWebElement).Wait(500).Release().Perform();`

**Comment by mykola-mokhnach** [comment]
I saw similar behaviour when date picker was shown on the screen and this was a bug in UIA2 framework itself.

**Comment by GrzegorzSidwa** [comment]
@mykola-mokhnach  basically in this case it's not related to one type of control, but looks like it's not working on many controls, but only Android 8. 

How we can proceed in this case? How we can speed it up?

**Comment by mykola-mokhnach** [comment]
You could probably start at getting a thread dump of uiautomator server app: https://stackoverflow.com/questions/13589074/how-to-make-java-thread-dump-in-android

**Comment by ArturKurowski1** [comment]
[dump.txt](https://github.com/appium/appium/files/2166616/dump.txt)

**Comment by mykola-mokhnach** [comment]
Closed as third party issue. You are welcome to commit a PR if you know what should be changed in order to address this problem

**Comment by NijaCN** [comment]
So， how to resolve this problem?  Wish your help

**Comment by ArturKurowski1** [comment]
The problem occured only in case where whole Activitiy was added as a tab , we did change our Android app to use Fragents intead Activities and that helped.
