### ISSUE TITLE
The AndroidElement sometimes can not be found by the same scripts with xpath

### ISSUE THREAD

**Issue by lwb2001258** [appium/appium#10956]
## The problem

we find an Element by xpath always can be found but sometimes can not be found sometimes  in the same test scripts. I do not know what is the problem. Sometimes by id would be not found also.

## Environment

* Appium version (or git revision) that exhibits the issue:1.8.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:win 10
* Node.js version (unless using Appium.app|exe):8.11.3
* Mobile platform/version under test:Android 7.0
* Real device or emulator/simulator:real device
* Appium CLI or Appium.app|exe:installed by npm
java-client 6.0.1 selenium .3.12.0

## Details

adb logcat
[adblogcat.txt](https://github.com/appium/appium/files/2139852/adblogcat.txt)
the wrong message was below:
06-27 13:16:59.696 13238 13374 I appium  : find element command using 'xpath' with selector '//android.widget.TextView[@text='参数管理']'.
06-27 13:16:59.726 13238 13374 E appium  : Element not found: 
06-27 13:16:59.726 13238 13374 E appium  : io.appium.uiautomator2.common.exceptions.ElementNotFoundException: Could not find an element using supplied strategy. 
06-27 13:16:59.726 13238 13374 E appium  : 	at io.appium.uiautomator2.handler.FindElement.getXPathUiObject(FindElement.java:80)
06-27 13:16:59.726 13238 13374 E appium  : 	at io.appium.uiautomator2.handler.FindElement.findElement(FindElement.java:152)
06-27 13:16:59.726 13238 13374 E appium  : 	at io.appium.uiautomator2.handler.FindElement.safeHandle(FindElement.java:102)
06-27 13:16:59.726 13238 13374 E appium  : 	at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:56)
06-27 13:16:59.726 13238 13374 E appium  : 	at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:239)
06-27 13:16:59.726 13238 13374 E appium  : 	at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:230)
06-27 13:16:59.726 13238 13374 E appium  : 	at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)
06-27 13:16:59.726 13238 13374 E appium  : 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
06-27 13:16:59.726 13238 13374 E appium  : 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
06-27 13:16:59.726 13238 13374 E appium  : 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
06-27 13:16:59.726 13238 13374 E appium  : 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
06-27 13:16:59.726 13238 13374 E appium  : 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
06-27 13:16:59.726 13238 13374 E appium  : 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
06-27 13:16:59.726 13238 13374 E appium  : 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
06-27 13:16:59.726 13238 13374 E appium  : 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
06-27 13:16:59.726 13238 13374 E appium  : 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
06-27 13:16:59.726 13238 13374 E appium  : 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
06-27 13:16:59.726 13238 13374 E appium  : 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
06-27 13:16:59.726 13238 13374 E appium  : 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
06-27 13:16:59.726 13238 13374 E appium  : 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
06-27 13:16:59.726 13238 13374 E appium  : 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
06-27 13:16:59.726 13238 13374 E appium  : 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
06-27 13:16:59.726 13238 13374 E appium  : 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
06-27 13:16:59.726 13238 13374 E appium  : 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
06-27 13:16:59.726 13238 13374 E appium  : 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
06-27 13:16:59.726 13238 13374 E appium  : 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
06-27 13:16:59.726 13238 13374 E appium  : 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
06-27 13:16:59.726 13238 13374 E appium  : 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:552)
06-27 13:16:59.726 13238 13374 E appium  : 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466)
06-27 13:16:59.726 13238 13374 E appium  : 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
06-27 13:16:59.726 13238 13374 E appium  : 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
06-27 13:16:59.726 13238 13374 E appium  : 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
06-27 13:16:59.726 13238 13374 E appium  : 	at java.lang.Thread.run(Thread.java:776)
06-27 13:16:59.727 13238 13374 I appium  : AppiumResponse: {"sessionId":"4b60a815-d757-41b8-9574-84653e7b7c63","status":7,"value":"An element could not be located on the page using the given search parameters."}
06-27 13:16:59.782 13238 13375 I appium  : channel read invoked!

## Link to Appium logs
[appium0627131536.txt](https://github.com/appium/appium/files/2139855/appium0627131536.txt)

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]
public static void selectParameter(AndroidDriver<AndroidElement> driver, int j) throws Exception {
		driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
		Thread.sleep(1000);
		driver.findElementByXPath("//*[@text='我的']").click();
		WriteToTxt.logWriteToTxt(df.format(new Date()) + "   " + "点击我的按钮");
		Thread.sleep(3000);
		driver.findElementByXPath("//android.widget.TextView[@text='参数管理']").click();
		WriteToTxt.logWriteToTxt(df.format(new Date()) + "   " + "点击参数管理按钮");
		Thread.sleep(1000);
		AndroidElement wifi = driver.findElement(By.id("com.iteach.zed.a03:id/switch_wifi"));
		Thread.sleep(1000);
		AndroidElement black = driver.findElement(By.id("com.iteach.zed.a03:id/switch_black"));
		// if (i == 1) {
		// if (!wifi.isSelected()) {
		// wifi.click();
		// Thread.sleep(1000);
		// WriteToTxt.logWriteToTxt(df.format(new Date()) + " " + "打开WIFI采集");
		// }
		// WriteToTxt.logWriteToTxt(df.format(new Date()) + " " + "WIFI采集已经被打开");
		// } else if (i == 2) {
		// if (wifi.isSelected()) {
		// wifi.click();
		// Thread.sleep(1000);
		// WriteToTxt.logWriteToTxt(df.format(new Date()) + " " + "关闭WIFI采集");
		// }
		// WriteToTxt.logWriteToTxt(df.format(new Date()) + " " + "WIFI采集已经被关闭");
		// }
		if (j == 1) {
			if (!black.isSelected()) {
				black.click();
				Thread.sleep(1000);
				WriteToTxt.logWriteToTxt(df.format(new Date()) + "   " + "打开黑白名单震动");
			}
			WriteToTxt.logWriteToTxt(df.format(new Date()) + "   " + "已经打开黑白名单震动");
		} else {
			if (black.isSelected()) {
				black.click();
				Thread.sleep(1000);
				WriteToTxt.logWriteToTxt(df.format(new Date()) + "   " + "关闭黑白名单震动");
			}
			WriteToTxt.logWriteToTxt(df.format(new Date()) + "   " + "已经关闭黑白名单震动");
		}

		driver.findElement(By.className("android.widget.ImageButton")).click();// 返回按钮
		Thread.sleep(1000);
		WriteToTxt.logWriteToTxt(df.format(new Date()) + "   " + "点击返回按钮");
	}

this line of the Element sometimes can not be found.
driver.findElementByXPath("//android.widget.TextView[@text='参数管理']").click();
Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
If the element cannot be found then it does not exist. Try to use explicit waits. Please use Appium forum to ask questions. Here is the place for issues.
