### ISSUE TITLE
The appium server is not stable

### ISSUE THREAD

**Issue by lwb2001258** [appium/appium#10955]
## The problem

When I debug the test scripts in the day time it shows no problems. But my automation runs for a long time. But when the test scripts ran in the night time, it went wrong too much. So I don't know where are  the problems. The only successful case was the uiautomator server, but uiautomator 2 server was not success. Can anyone help me to find the problems. Is the bugs of uiautomator2?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0(java-client 6.0.1,selenium3.12.0）
* Last Appium version that did not exhibit the issue (if applicable):1.6.1（java 4.0.0,selenium 2.583.1)
* Desktop OS/version used to run Appium: win 10
* Node.js version (unless using Appium.app|exe): 8.11.3
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator:real device
* Appium CLI or Appium.app|exe:install by npm
when we use the 1.6.1 version ,sometimes the server could not find the devices

## Details

If necessary, describe the problem you have been experiencing in more detail.
[A03ATHTMLReport  (2).txt](https://github.com/appium/appium/files/2139411/A03ATHTMLReport.2.txt)
you can see the report. You can change the .txt to .html and use chrome to open. The test result was very bad.

## Link to Appium logs

There was too much of logs

## Code To Reproduce Issue [ Good To Have ]
below was the maven main fuction:
[A03ATHTMLReport  (2).txt](https://github.com/appium/appium/files/2139424/A03ATHTMLReport.2.txt)
below was the InitDriver
[A03InitDriver (2).txt](https://github.com/appium/appium/files/2139428/A03InitDriver.2.txt)
[AppiumInit.txt](https://github.com/appium/appium/files/2139429/AppiumInit.txt)
below was one of the testng test:
[ZhenMaTest.txt](https://github.com/appium/appium/files/2139434/ZhenMaTest.txt)
[A03ZhenMa.txt](https://github.com/appium/appium/files/2139435/A03ZhenMa.txt)
[DriverUtil.txt](https://github.com/appium/appium/files/2139439/DriverUtil.txt)

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Try to update the client to 6.1.0 I don't observe any issues in the server log though.
