### ISSUE TITLE
Appium is not detecting element in Android 7.0

### ISSUE THREAD

**Issue by VivekKrishna15** [appium/appium#10951]
## The problem

I have written code in Java for android app automation. The code is working fine for android 4.4.2 and android 6 but it is not working for android 7.0. It is detecting very 1st element after that second element onwards it is throwing error as it is finding multiple elements. i.e. **using 'XPATH' with the contextId: '' multiple: false** Appium logs link is attached.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.8.1
* Desktop OS/version used to run Appium: Windows 7, 32 bit
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium desktop

## Link to Appium logs

https://gist.github.com/VivekKrishna15/c6a0e47959db816479c15f01042aed13

**Comment by mykola-mokhnach** [comment]
Use UIAutomator2 for Android 6+

**Comment by VivekKrishna15** [comment]
Thank you Mykola Mokhnach. It is working fine now.
