### ISSUE TITLE
[XCUITest] Failed to create WDA session. Retrying

### ISSUE THREAD

**Issue by eldor4do** [appium/appium#10961]
I am trying to test my ios app using Appium, but I keep getting the error "Failed to create WDA session. Retrying..."

I'm using Appium v.1.8.1, xcode 9.4.1, macOS High Sierra 10.13.5.
I'm running it via Appium's GUI client, with these capabilities - 
```
{
 "platformName": "iOS",
 "app": "/Users/devuser/Library/Developer/Xcode/DerivedData/MYAPP-ekepqtzbescodugjfqbkkuwfnkow/Build/Products/Staging-iphoneos/MYAPP.app",
 "deviceName": "iPhone Simulator",
 "automationName": "XCUITest"
}
```

This is the complete logs - 
[GIST to log](https://gist.github.com/eldor4do/d222a32f6e304e8b91b455fd8579cc9a)

**Comment by imurchie** [comment]
```
[warn] [XCUITest] Simulator architecture appears to be unsupported by the '/Users/devuser/Library/Developer/Xcode/DerivedData/MYAPP-ekepqtzbescodugjfqbkkuwfnkow/Build/Products/Staging-iphoneos/MYAPP.app' application. Make sure the correct deployment target has been selected for its compilation in Xcode.
[warn] [XCUITest] Don't be surprised if the application fails to launch.
```
You need a simulator build of the app in order to run it on a simulator.

**Comment by eldor4do** [comment]
@imurchie Would I be able to get that if I follow these steps?
http://simulatorbuild.blogspot.com/p/generate-simulator-build-in-order-to.html

**Comment by imurchie** [comment]
Yes. You can just go into your project directory, and run 
```
xcodebuild -sdk iphonesimulator$(xcrun --sdk iphonesimulator --show-sdk-version)
```

**Comment by maxsudik** [comment]
I have 2 questions:
1) After I run the line of code above i received next error:
xcodebuild: error: The directory /Users/maxsudik/Downloads does not contain an Xcode project.

Does it mean that I am able to run applications through Appium only with Xcode files?

2) What should I do if I want to test production version of a application. Let's say "What's Up". Can I download .ipa file from the internet and run a simulator with it through Appium?

**Comment by mykola-mokhnach** [comment]
Please use appium forum to ask questions. This is the place for issues

**Comment by imurchie** [comment]
@maxsudik No, you cannot. Apple requires a simulator build of an app in order to run it. You cannot just pull an app off a real phone and expect it to run on a simulator.

**Comment by at-duytran** [comment]
I have same issue and fixed it now.
Step 1: In Xcode: Preferences -> Derived Data. Then remove all folder inside that folder.
Step 2: Clean Xcode (Command + Shift + K), then Quit Xcode.
Step 3: Re-open workspace and Build app to simulator.
Step 4: Quit all Xcode and Simulator, run Appium and edit again key `app` of `Capabilities`, and place it correct with your new new `yourApp.app` path.
Done !! My problems fixed !!

- I saw new path is differences than old, but it's working now.
old path: `.../Staging-iphoneos/...`
new path: `.../Staging-iphonesimulator/...`

Sorry for my bad english.
