### ISSUE TITLE
appium-uiautomator2-server-v1.10.0.apk and appium-uiautomator2-server-debug-androidTest.apk reinstall every testing

### ISSUE THREAD

**Issue by WindInMay524** [appium/appium#10969]
## The problem
appium-uiautomator2-server-v1.10.0.apk and appium-uiautomator2-server-debug-androidTest.apk reinstall every testing ,And I need to click  confirm button to ensure installation continiue.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable): I cannot ensure last version has the problem
* Desktop OS/version used to run Appium: Android 7.1.1 
* Node.js version (unless using Appium.app|exe): v10.4.1
* Mobile platform/version under test: Mi Note 3
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI 

## Details
When I try to modify appium\node_modules\appium-uiautomator2-driver\lib\uiautomator2.js,It seems doesn't any effect. If it can be the same as appium setting apk needed to install only once except has any new version,My problem can be solved perfectly

## Link to Appium logs
https://gist.github.com/WindInMay524/68f63393d53b1acc33157a82cb1f0e33

## Code To Reproduce Issue [ Good To Have ]
   def startApp(self):        
        desired_caps = {}
        desired_caps['platformName'] = 'Android'
        desired_caps['platformVersion'] = '6.0.1'
        desired_caps['deviceName'] = '3b44cc34'
        desired_caps['appPackage'] = 'com.tencent.mm'
        desired_caps['appActivity'] = 'com.tencent.mm.ui.LauncherUI'
        desired_caps['chromeOptions'] = {'androidProcess': 'com.tencent.mm:tools'}
        desired_caps['automationName'] = 'UIAutomator2'
        desired_caps['recreateChromeDriverSessions'] = 'true'
        desired_caps['noReset'] = 'true'
        self.driver = webdriver.Remote('http://localhost:4723/wd/hub',desired_caps)
        return self.driver
![image](https://user-images.githubusercontent.com/38344643/42082254-18ddc75e-7bba-11e8-912d-b2c4c9f69787.png)

**Comment by mykola-mokhnach** [comment]
Such alert is shown by the third-party firmware (MiUI, etc) and we are not going to handle it in Appium. Please use appropriate phones with Google-based firmware. Closed as duplicate.

**Comment by WindInMay524** [comment]
Can I reset to install them only once

**Comment by mykola-mokhnach** [comment]
I think you cannot. Try to contact vendor's customer support to know for sure

**Comment by WindInMay524** [comment]
Okay,Thanks for you help
