### ISSUE TITLE
Set UIAutomator2 as default for version 6+

### ISSUE THREAD

**Issue by saikrishna321** [appium/appium#10975]
When client does not set AutomationName as UIAutomator2 appium server currently considers UIAutomator1. 

Server should consider UIA2 when device version is 6+.

@mykola-mokhnach @jlipps Thoughts ?

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/pull/10073

**Comment by mykola-mokhnach** [comment]
I tried...

**Comment by saikrishna321** [comment]
@mykola-mokhnach Kool ... 

I don't see the warn in the logs 

https://gist.github.com/saikrishna321/24577d99e0495fbc425db4f666521651

**Comment by mykola-mokhnach** [comment]
The warning is only shown if platform version is provided in capabilities. Otherwise the umbrella driver knows nothing about the current platform version.

**Comment by mykola-mokhnach** [comment]
In theory such warning might also be added into android driver, where we know the actual platform version, but I'm not quite sure about such step. @jlipps @imurchie what do you think

**Comment by imurchie** [comment]
That would be the place to add it, yes. After the device's API level has been determined.
