### ISSUE TITLE
 io.appium.java_client.remote.AppiumCommandExecutor$1 lambda$0

### ISSUE THREAD

**Issue by shital17jun** [appium/appium#10974]
driver.findElement(By.id("android:id/text1[@text='OS']")).click();
for these getting error

**Comment by shital17jun** [comment]
Appium version 1.6.1
Jul 01, 2018 12:24:58 AM
io.appium.java_client.remote.AppiumCommandExecutor$1 lambda$0

Before adding commons-lang3-3.7-bin.jar it wasnt run now it run but error
its showing
The server is running
[Appium] Welcome to Appium v1.8.0
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP]
{"desiredCapabilities":{"appActivity":"com.android.calculator2.Calculator","appPackage":"com.android.calculator2","platformName":"Android","deviceName":"emulator-5554"},"capabilities":{"alwaysMatch":{"appium:appActivity":"com.android.calculator2.Calculator","appium:appPackage":"com.android.calculator2","appium:deviceName":"emulator-5554","platformName":"android"},"firstMatch":[{}]}}
[MJSONWP] Calling AppiumDriver.createSession() with args:
[{"appActivity":"com.android.calculator2.Calculator","appPackage":"com.android.calculator2","platformName":"Android","deviceName":"emulator-5554"},null,{"alwaysMatch":{"appium:appActivity":"com.android.calculator2.Calculator","appium:appPackage":"com.android.calculator2","appium:deviceName":"emulator-5554","platformName":"android"},"firstMatch":[{}]}]
[BaseDriver] Event 'newSessionRequested' logged at 1530384886077 (00:24:46
GMT+0530 (India Standard Time))
[Appium] Creating new AndroidDriver (v2.6.0) session
[Appium] Capabilities:
[Appium] platformName: android
[Appium] appActivity: com.android.calculator2.Calculator
[Appium] appPackage: com.android.calculator2
[Appium] deviceName: emulator-5554
[BaseDriver] W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP
desired capabilities [object Object] were provided
[BaseDriver] Creating session with W3C capabilities:
{"alwaysMatch":{"platformNa...
[BaseDriver] Session created with session id:
7c0f299b-00eb-4fe0-ad8c-a753a82a7396
[AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_171
[ADB] Checking whether adb is present
[ADB] Found 2 'build-tools' folders under
'C:\Users\shital\AppData\Local\Android\sdk' (newest first):
[ADB] C:/Users/shital/AppData/Local/Android/sdk/build-tools/28.0.0
[ADB] C:/Users/shital/AppData/Local/Android/sdk/build-tools/23.0.1
[ADB] Using adb.exe from
C:\Users\shital\AppData\Local\Android\sdk\platform-tools\adb.exe
[AndroidDriver] Retrieving device list
[ADB] Trying to find a connected android device
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[AndroidDriver] Using device: emulator-5554
[ADB] Checking whether adb is present
[ADB] Using adb.exe from
C:\Users\shital\AppData\Local\Android\sdk\platform-tools\adb.exe
[ADB] Setting device id to emulator-5554
[AndroidDriver] App file was not listed, instead we're going to run
com.android.calculator2 directly on the device
[AndroidDriver] Checking whether package is present on the device
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running
'C:\Users\shital\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037
-s emulator-5554 shell pm list packages com.android.calculator2'
[AndroidDriver] Starting Android session
[ADB] Running
'C:\Users\shital\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037
-s emulator-5554 wait-for-device'
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running
'C:\Users\shital\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037
-s emulator-5554 shell echo ping'
[AndroidDriver] Pushing settings apk to device...
[ADB] Getting install status for io.appium.settings
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running
'C:\Users\shital\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037
-s emulator-5554 shell pm list packages io.appium.settings'
[ADB] App is installed
[ADB] Getting package info for 'io.appium.settings'
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running
'C:\Users\shital\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037
-s emulator-5554 shell dumpsys package io.appium.settings'
[ADB] Checking whether aapt is present
[ADB] Using aapt.exe from
C:\Users\shital\AppData\Local\Android\sdk\build-tools\28.0.0\aapt.exe
[ADB] The installed 'io.appium.settings' package does not require upgrade
('2.3.0' >= '2.3.0')
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running
'C:\Users\shital\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037
-s emulator-5554 shell ps'
[AndroidDriver] io.appium.settings is already running. There is no need to
reset its permissions.
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running
'C:\Users\shital\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037
-s emulator-5554 shell getprop ro.build.version.sdk'
[ADB] Current device property 'ro.build.version.sdk': 22
[ADB] Device API level: 22
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running
'C:\Users\shital\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037
-s emulator-5554 shell settings put secure mock_location 1'
[AndroidDriver] setDeviceLanguageCountry requires language or country.
[AndroidDriver] Got language: 'undefined' and country: 'undefined'
[Logcat] Starting logcat capture
[AndroidDriver] Pushing unlock helper app to device...
[ADB] Getting install status for io.appium.unlock
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running
'C:\Users\shital\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037
-s emulator-5554 shell pm list packages io.appium.unlock'
[ADB] App is installed
[ADB] Getting package info for 'io.appium.unlock'
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running
'C:\Users\shital\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037
-s emulator-5554 shell dumpsys package io.appium.unlock'
[ADB] Checking whether aapt is present
[ADB] Using aapt.exe from
C:\Users\shital\AppData\Local\Android\sdk\build-tools\28.0.0\aapt.exe
[ADB] The installed 'io.appium.unlock' package does not require upgrade
('2.0.0' >= '2.0.0')
[ADB] Getting device platform version
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running
'C:\Users\shital\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037
-s emulator-5554 shell getprop ro.build.version.release'
[ADB] Current device property 'ro.build.version.release': 5.1.1
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running
'C:\Users\shital\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037
-s emulator-5554 shell wm size'
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running
'C:\Users\shital\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037
-s emulator-5554 shell getprop ro.product.model'
[ADB] Current device property 'ro.product.model': Android SDK built for x86
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running
'C:\Users\shital\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037
-s emulator-5554 shell getprop ro.product.manufacturer'
[ADB] Current device property 'ro.product.manufacturer': unknown
[AndroidDriver] No app sent in, not parsing package/activity
[AndroidDriver] No app capability. Assuming it is already on the device
[ADB] Getting install status for com.android.calculator2
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running
'C:\Users\shital\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037
-s emulator-5554 shell pm list packages com.android.calculator2'
[ADB] App is installed
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running
'C:\Users\shital\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037
-s emulator-5554 shell am force-stop com.android.calculator2'
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running
'C:\Users\shital\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037
-s emulator-5554 shell pm clear com.android.calculator2'
[AndroidDriver] Performed fast reset on the installed
'com.android.calculator2' application (stop and clear)
[AndroidBootstrap] Watching for bootstrap disconnect
[ADB] Forwarding system: 4724 to device: 4724
[ADB] Running
'C:\Users\shital\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037
-s emulator-5554 forward tcp\:4724 tcp\:4724'
[UiAutomator] Starting UiAutomator
[UiAutomator] Moving to state 'starting'
[UiAutomator] Parsing uiautomator jar
[UiAutomator] Found jar name: 'AppiumBootstrap.jar'
[ADB] Running
'C:\Users\shital\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037
-s emulator-5554 push 'C:\\Program Files
(x86)\\Appium\\resources\\app\\node_modules\\appium-android-bootstrap\\bootstrap\\bin\\AppiumBootstrap.jar'
/data/local/tmp/'
[ADB] Attempting to kill all uiautomator processes
[ADB] Getting all processes with uiautomator
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running
'C:\Users\shital\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037
-s emulator-5554 shell ps'
[ADB] No uiautomator process found to kill, continuing...
[UiAutomator] Starting UIAutomator
[ADB] Creating ADB subprocess with args:
["-P",5037,"-s","emulator-5554","shell","uiautomator","runtest","AppiumBootstrap.jar","-c","io.appium.android.bootstrap.Bootstrap","-e","pkg","com.android.calculator2","-e","disableAndroidWatchers",false,"-e","acceptSslCerts",false]
[UiAutomator] Moving to state 'online'
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] json loading complete.
[AndroidBootstrap] Android bootstrap socket is now connected
[ADB] Getting connected devices...
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Registered crash watchers.
[ADB] 1 device(s) connected
[ADB] Running
'C:\Users\shital\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037
-s emulator-5554 shell dumpsys window'
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Client connected
[AndroidDriver] Screen already unlocked, doing nothing
[ADB] Device API level: 22
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running
'C:\Users\shital\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037
-s emulator-5554 shell am start -W -n
com.android.calculator2/com.android.calculator2.Calculator -S'
[Appium] New AndroidDriver session created successfully, session
7c0f299b-00eb-4fe0-ad8c-a753a82a7396 added to master session list
[BaseDriver] Event 'newSessionStarted' logged at 1530384898226 (00:24:58
GMT+0530 (India Standard Time))
[MJSONWP] Responding to client with driver.createSession() result:
{"capabilities":{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"android","appActivity":"com.android.calculator2.Calculator","appPackage":"com.android.calculator2","deviceName":"emulator-5554"},"platformName":"android","appActivity":"com.android.calculator2.Calculator","appPackage":"com.android.calculator2","deviceName":"emulator-5554","deviceUDID":"emulator-5554","platformVersion":"5.1.1","deviceScreenSize":"1080x1920","deviceModel":"Android
SDK built for x86","deviceManufacturer":"unknown"}}
[HTTP] <-- POST /wd/hub/session 200 12157 ms - 732
[HTTP]
[HTTP] --> GET /wd/hub/session/7c0f299b-00eb-4fe0-ad8c-a753a82a7396
[HTTP] {}
[W3C] Calling AppiumDriver.getSession() with args:
["7c0f299b-00eb-4fe0-ad8c-a753a82a7396"]
[W3C] Responding to client with driver.getSession() result:
{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"android","appActivity":"com.android.calculator2.Calculator","appPackage":"com.android.calculator2","deviceName":"emulator-5554"},"platformName":"android","appActivity":"com.android.calculator2.Calculator","appPackage":"com.android.calculator2","deviceName":"emulator-5554","deviceUDID":"emulator-5554","platformVersion":"5.1.1","deviceScreenSize":"1080x1920","deviceModel":"Android
SDK built for x86","deviceManufacturer":"unknown"}
[HTTP] <-- GET /wd/hub/session/7c0f299b-00eb-4fe0-ad8c-a753a82a7396 200 30
ms - 664
[HTTP]
[HTTP] --> GET /wd/hub/session/7c0f299b-00eb-4fe0-ad8c-a753a82a7396
[HTTP] {}
[W3C] Calling AppiumDriver.getSession() with args:
["7c0f299b-00eb-4fe0-ad8c-a753a82a7396"]
[W3C] Responding to client with driver.getSession() result:
{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"android","appActivity":"com.android.calculator2.Calculator","appPackage":"com.android.calculator2","deviceName":"emulator-5554"},"platformName":"android","appActivity":"com.android.calculator2.Calculator","appPackage":"com.android.calculator2","deviceName":"emulator-5554","deviceUDID":"emulator-5554","platformVersion":"5.1.1","deviceScreenSize":"1080x1920","deviceModel":"Android
SDK built for x86","deviceManufacturer":"unknown"}
[HTTP] <-- GET /wd/hub/session/7c0f299b-00eb-4fe0-ad8c-a753a82a7396 200 4
ms - 664
[HTTP]
[HTTP] --> POST
/wd/hub/session/7c0f299b-00eb-4fe0-ad8c-a753a82a7396/elements
[HTTP] {"using":"id","value":"com.android.calculator2:id/digit_4"}
[W3C] Calling AppiumDriver.findElements() with args:
["id","com.android.calculator2:id/digit_4","7c0f299b-00eb-4fe0-ad8c-a753a82a7396"]
[BaseDriver] Valid locator strategies for this request: xpath, id, class
name, accessibility id, -android uiautomator
[BaseDriver] Waiting up to 0 ms for condition
[AndroidBootstrap] Sending command to android:
{"cmd":"action","action":"find","params":{"strategy":"id","selector":"com.android.calculator2:id/digit_4","context":"","multiple":true}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client:
{"cmd":"action","action":"find","params":{"strategy":"id","selector":"com.android.calculator2:id/digit_4","context":"","multiple":true}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding
'com.android.calculator2:id/digit_4' using 'ID' with the contextId: ''
multiple: true
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using:
UiSelector[RESOURCE_ID=com.android.calculator2:id/digit_4]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements
selector:UiSelector[RESOURCE_ID=com.android.calculator2:id/digit_4]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Element[] is null: (0)
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements tmp
selector:UiSelector[INSTANCE=0,
RESOURCE_ID=com.android.calculator2:id/digit_4]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Element[] is null: (1)
[AndroidBootstrap] Received command result from bootstrap
[W3C] Responding to client with driver.findElements() result:
[{"element-6066-11e4-a52e-4f735466cecf":"1"}]
[HTTP] <-- POST
/wd/hub/session/7c0f299b-00eb-4fe0-ad8c-a753a82a7396/elements 200 971 ms -
55
[HTTP]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements tmp
selector:UiSelector[INSTANCE=1,
RESOURCE_ID=com.android.calculator2:id/digit_4]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result:
{"status":0,"value":[{"ELEMENT":"1"}]}
[HTTP] --> GET
/wd/hub/session/7c0f299b-00eb-4fe0-ad8c-a753a82a7396/element/1/displayed
[HTTP] {}
[W3C] Calling AppiumDriver.elementDisplayed() with args:
["1","7c0f299b-00eb-4fe0-ad8c-a753a82a7396"]
[AndroidBootstrap] Sending command to android:
{"cmd":"action","action":"element:getAttribute","params":{"attribute":"displayed","elementId":"1"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client:
{"cmd":"action","action":"element:getAttribute","params":{"attribute":"displayed","elementId":"1"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: getAttribute
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result:
{"status":0,"value":"true"}
[AndroidBootstrap] Received command result from bootstrap
[W3C] Responding to client with driver.elementDisplayed() result: true
[HTTP] <-- GET
/wd/hub/session/7c0f299b-00eb-4fe0-ad8c-a753a82a7396/element/1/displayed 200 45
ms - 14
[HTTP]
[HTTP] --> GET
/wd/hub/session/7c0f299b-00eb-4fe0-ad8c-a753a82a7396/element/1/enabled
[HTTP] {}
[W3C] Calling AppiumDriver.elementEnabled() with args:
["1","7c0f299b-00eb-4fe0-ad8c-a753a82a7396"]
[AndroidBootstrap] Sending command to android:
{"cmd":"action","action":"element:getAttribute","params":{"attribute":"enabled","elementId":"1"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client:
{"cmd":"action","action":"element:getAttribute","params":{"attribute":"enabled","elementId":"1"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: getAttribute
[AndroidBootstrap] Received command result from bootstrap
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result:
{"status":0,"value":"true"}
[W3C] Responding to client with driver.elementEnabled() result: true
[HTTP] <-- GET
/wd/hub/session/7c0f299b-00eb-4fe0-ad8c-a753a82a7396/element/1/enabled 200 63
ms - 14
[HTTP]
[HTTP] --> POST
/wd/hub/session/7c0f299b-00eb-4fe0-ad8c-a753a82a7396/element/1/click
[HTTP] {"id":"1"}
[W3C] Calling AppiumDriver.click() with args:
["1","7c0f299b-00eb-4fe0-ad8c-a753a82a7396"]
[AndroidBootstrap] Sending command to android:
{"cmd":"action","action":"element:click","params":{"elementId":"1"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client:
{"cmd":"action","action":"element:click","params":{"elementId":"1"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: click
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result:
{"status":0,"value":true}
[AndroidBootstrap] Received command result from bootstrap
[W3C] Responding to client with driver.click() result: true
[HTTP] <-- POST
/wd/hub/session/7c0f299b-00eb-4fe0-ad8c-a753a82a7396/element/1/click 200 447
ms - 14
[HTTP]
[BaseDriver] Shutting down because we waited 60 seconds for a command
[AndroidDriver] Shutting down Android driver
[ADB] Getting connected devices...
[Appium] Closing session, cause was 'New Command Timeout of 60 seconds
expired. Try customizing the timeout using the 'newCommandTimeout' desired
capability'
[Appium] Removing session 7c0f299b-00eb-4fe0-ad8c-a753a82a7396 from our
master session list
[ADB] 1 device(s) connected
[ADB] Running
'C:\Users\shital\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037
-s emulator-5554 shell am force-stop com.android.calculator2'
[ADB] Pressing the HOME button
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running
'C:\Users\shital\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037
-s emulator-5554 shell input keyevent 3'
[AndroidBootstrap] Sending command to android: {"cmd":"shutdown"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client:
{"cmd":"shutdown"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type SHUTDOWN
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result:
{"status":0,"value":"OK, shutting down"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Closed client connection
[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: numtests=1
[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: stream=.
[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS:
id=UiAutomatorTestRunner
[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS:
test=testRunServer
[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: class
[AndroidBootstrap] Received command result from bootstrap
[UiAutomator] Shutting down UiAutomator
[UiAutomator] Moving to state 'stopping'
[UiAutomator] UiAutomator shut down normally
[UiAutomator] Moving to state 'stopped'
[ADB] Attempting to kill all uiautomator processes
[ADB] Getting all processes with uiautomator
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running
'C:\Users\shital\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037
-s emulator-5554 shell ps'
[ADB] No uiautomator process found to kill, continuing...
[UiAutomator] Moving to state 'stopped'
[Logcat] Stopping logcat capture
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running
'C:\Users\shital\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037
-s emulator-5554 shell am force-stop io.appium.unlock'
[AndroidDriver] Not cleaning generated files. Add `clearSystemFiles`
capability if wanted.

**Comment by mykola-mokhnach** [comment]
I don't observe any issues in the attached log. If you think this an issue in the client then report it to https://github.com/appium/java-client with the full stack trace
