### ISSUE TITLE
noReset capability option is still uninstalling and re-installing server app

### ISSUE THREAD

**Issue by jsalama99** [appium/appium#10983]
## The problem

Specifying the noReset to be true doesn't seem to prevent Appium from uninstalling and re-installing the server apk.

## Environment
Appium desktop v1.8.1
Windows 10 Desktop

Desired Capabilities:
{
  "deviceName": "MyDevice",
  "platformName": "Android",
  "platformVersion": "7.0",
  "automationName": "uiautomator2",
  "appPackage": "com.android.settings",
  "appActivity": "com.android.settings.Settings",
  "deviceReadyTimeOut": "40",
  "deviceOrientation": "portrait",
  "noReset": true
}

## Details

I have tried a few flags to get it to stop from re-installing that app. It's important to prevent it because our environment initiates and terminates appium sessions in quick succession.

**Comment by mykola-mokhnach** [comment]
Can you attach the server log? The server apk is usually only uninstalled if it is outdated or not present on the device

**Comment by jsalama99** [comment]
Sure they are attached. I have 2 logs:
1. From Appium Desktop
2. Appium Node Install
Thanks!
[NodeJSServerLog.txt](https://github.com/appium/appium/files/2159547/NodeJSServerLog.txt)
[AppiumDesktopLog.txt](https://github.com/appium/appium/files/2159548/AppiumDesktopLog.txt)

**Comment by mykola-mokhnach** [comment]
> io.appium.uiautomator2.server'[debug][35m[ADB][39m Checking app cert for C:\Users\jsalama\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v1.12.0.apk
> [info][35m[ADB][39m Using apksigner.bat from C:\Users\jsalama\AppData\Local\Android\sdk\build-tools\26.0.2\apksigner.bat
> [debug][35m[ADB][39m Patching 'C:\Users\jsalama\AppData\Local\Android\sdk\build-tools\26.0.2\apksigner.bat' for Windows...
> [debug][35m[ADB][39m Starting patched 'C:\Users\jsalama\AppData\Local\Temp\201862-20548-13kw1b.txnsuj\apksigner.bat' with args 'verify,--print-certs,C:\Users\jsalama\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v1.12.0.apk'
> [debug][35m[ADB][39m 'C:\Users\jsalama\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v1.12.0.apk' is not signed with debug cert.

this is the expected behaviour. The script checks whether the server is signed and reinstalls it if it is not signed. Also, the server is going to be reinstalled if it is not present on the device or has lower version number/code than the current one. Otherwise it should be kept untouched.

**Comment by jsalama99** [comment]
This is 1 of 2 sections I am referring to:
```
[debug] [ADB] Uninstalling io.appium.uiautomator2.server                                                                                                                                                                                      
[debug] [ADB] Getting install status for io.appium.uiautomator2.server                                                                                                                                                                        
[debug] [ADB] Running 'C:\Users\jsalama\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037 -s d346b21c shell pm list packages io.appium.uiautomator2.server'                                                                            
[debug] [ADB] App is installed                                                                                                                                                                                                                
[debug] [ADB] Running 'C:\Users\jsalama\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037 -s d346b21c shell am force-stop io.appium.uiautomator2.server'                                                                               
[debug] [ADB] Running 'C:\Users\jsalama\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037 -s d346b21c uninstall io.appium.uiautomator2.server'                                                                                         
[debug] [ADB] 'adb uninstall io.appium.uiautomator2.server' command output: Success 
```

It checks to see if its installed, stops it, uninstalls it, and then re-installs it. Should this happen if the noReset flag is set to true?

**Comment by mykola-mokhnach** [comment]
noReset flag only affects the application under test, not the server itself.

**Comment by jsalama99** [comment]
That makes sense. Thank you. Is there no way to prevent the server from having to be re-installed? We are trying to reduce overhead where we can.

**Comment by mykola-mokhnach** [comment]
No, currently this behaviour cannot be controlled from the client side. You can only change it in the source code.
