### ISSUE TITLE
iOS - Failed to launch safari - real device

### ISSUE THREAD

**Issue by pavkr** [appium/appium#10980]
## The problem

Enqueue Failure: Failed to launch com.apple.mobilesafari: The operation couldn’t be completed. Application "com.apple.mobilesafari" is installing or uninstalling, and cannot be launched.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: macOS High Sierra
* Node.js version (unless using Appium.app|exe): 5.6.0
* Mobile platform/version under test:  11.0.3 (15A432)
* Real device or emulator/simulator: real
* Appium CLI or Appium.app|exe: cli

## Details

Cannot create appium session

## Link to Appium logs

 [GIST]("https://gist.github.com/pavkr/33ba4787e6e12fd45ff389ad6e9b5df7.js"

## Code To Reproduce Issue [ Good To Have ]

`
 var capabilities = new DesiredCapabilities();
 capabilities.SetCapability("xcodeOrgId", (string)doc.capabilities[0].xcodeOrgId);
 capabilities.SetCapability("xcodeSigningId", (string)doc.capabilities[0].xcodeSigningId);
 capabilities.SetCapability("reportDirectory", (string)doc.capabilities[0].reportDirectory);
 capabilities.SetCapability("reportFormat", (string)doc.capabilities[0].reportFormat);
 capabilities.SetCapability("testName", (string)doc.capabilities[0].testName);
 capabilities.SetCapability("automationName", (string)doc.capabilities[0].automationName);
 capabilities.SetCapability("newCommandTimeout", 200);
 capabilities.SetCapability("udid", (string)(doc.capabilities[0].deviceName));
 capabilities.SetCapability("deviceName", (string)doc.capabilities[0].deviceName);
 capabilities.SetCapability("fullReset", "false");
 capabilities.SetCapability("webkitResponseTimeout", 20000);
 capabilities.SetCapability(CapabilityType.BrowserName, MobileBrowserType.Safari);
 capabilities.SetCapability(CapabilityType.Platform, MobilePlatform.IOS);
 capabilities.SetCapability(CapabilityType.IsJavaScriptEnabled(string)doc.capabilities[0].javascriptEnable);
 capabilities.SetCapability("bundleId", (string)doc.capabilities[0].bundleId);
 
return new IOSDriver<RemoteWebElement>(new Uri(Hosts.Grid), capabilities, new TimeSpan(0, 0, 50));
`

**Comment by saikrishna321** [comment]
@pavkr its hard to help with server logs. Please provide logs.

Make sure you remove the bundleID capability and make sure you have ios-webkit-debug-proxy running

**Comment by mykola-mokhnach** [comment]
What do you want to achieve? In order to automate testing of a web site you need to only set the browserName capability without bundleId.

**Comment by pavkr** [comment]
Yeah, sorry that was my bad, I removed bundleID, however, it didn't help me.
So basically what's happening, after I run the test, I can see how Launcher app gets created and then Safari launches, but don't get the return of the driver object and have failure on timeout:
result: after a minute the device has safari open but returns timeoutError on step:
`return new IOSDriver<RemoteWebElement>(new Uri(Bro.Data.Hosts.Grid), capabilities, new TimeSpan(0, 0, 60));` 
increasing timeout doesn't help

I did restart the device, server and node, increased commandTimeout but seems like i'm missing something else

**Comment by mykola-mokhnach** [comment]
Please attach the updated logs

**Comment by skumar1122** [comment]
Heya @mykola-mokhnach ,
 
I am seeing same issue on my iPhone7Plus device. 

My capabilities:
 ```
capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 7 PLus");
capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "Safari"); capabilities.setCapability(MobileCapabilityType.UDID, deviceName);
capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");
capabilities.setCapability("showXcodeLog", true);
capabilities.setCapability("startIWDP", true);
capabilities.setCapability("xcodeOrgId", "3******Y7");
capabilities.setCapability("xcodeSigningId", "iPhone Developer");
capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "12.1");
```
Appium Start -
```
appium -U xxxxxxxxxxxxxxx -p4723 --webkit-debug-proxy-port 27790 

IWDP:

ios_webkit_debug_proxy -c xxxxxxxxxxxxxxx:27753 -d

```
Gits logs:
https://gist.github.com/skumar1122/c62590db4b92e1b9cf60ce273f7a4272

Could you please let me know If I am missing anything ?


Thanks

**Comment by Jonahss** [comment]
@skumar1122 your appium logs show that the session is starting successfully. Does Safari appear on the device? What error do your tests output?
Right now, I'd guess that the test starts fine, but your client is waiting so long it is timing out and ending your test, even though Appium eventually is ready.

**Comment by skumar1122** [comment]
Hi @Jonahss ,
Yes Appium starts successfully and I can see WDA app launches on real device but It failing to open safari browser. Hangs up at same place.
Also If I manually tap safari browser icon and then I can see tests started executing.

**Comment by Jonahss** [comment]
Ah @mykola-mokhnach mentioned on another issue that this is a [bug in XCTest](https://stackoverflow.com/questions/41872848/xctests-failing-to-launch-app-in-simulator-intermittently).

Try restarting the device.
