### ISSUE TITLE
Appium 1.8.2-beta  scroll to visible is broken for  iOS

### ISSUE THREAD

**Issue by bearxc** [appium/appium#10999]
if a  table has complex items , scroll to visible does not work  on Appium1.8.2 beta for iOS  ,  while  latest WDA code works fine .    There are couple fixes on WDA for scroll/visible recently.

Since there are so many differences between appium version of WDA and  FB version of WDA,  I can not simply  grab  FB  WDA into appium  any more.

Please help merge latest WDA into appium .

**Comment by Kitty2014** [comment]
same with you ,try with below WDA PRJ? @bearxc 
[appium-xcuitest-driver_618_stable.zip](https://github.com/appium/appium/files/2164796/appium-xcuitest-driver_618_stable.zip)

**Comment by bearxc** [comment]
@kitty2014
谢谢！
Does this zip contain latest FB WDA  or roll back to old ?

**Comment by mykola-mokhnach** [comment]
> Please help merge latest WDA into appium .

There are several key differences between our and their forks, so they are not interchangeable. Although, you can still use WDA from Facebook separately, without Appium or even switch to pure XCTest.

Also you are welcome to debug and solve the visibility issues in our WDA fork.
