### ISSUE TITLE
MobileElement getText is not working everytime.

### ISSUE THREAD

**Issue by Zbr123** [appium/appium#10998]
MobileElement getText is not working everytime and its doesnot return the text when thou text is present. 

Exception on Android console:

17:51:33.585 [Forwarding getElementText on session dea4c027-bb82-4f29-86d7-78b9b0d64b83 to remote] INFO  org.apache.http.impl.execchain.RetryExec - I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://0.0.0.0:4723: The target server failed to respond
17:51:33.585 [Forwarding getElementText on session dea4c027-bb82-4f29-86d7-78b9b0d64b83 to remote] INFO  org.apache.http.impl.execchain.RetryExec - Retrying request to {}->http://0.0.0.0:4723
18:01:33.590 [Forwarding getElementText on session dea4c027-bb82-4f29-86d7-78b9b0d64b83 to remote] INFO  org.apache.http.impl.execchain.RetryExec - I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://0.0.0.0:4723: The target server failed to respond
18:01:33.591 [Forwarding getElementText on session dea4c027-bb82-4f29-86d7-78b9b0d64b83 to remote] INFO  org.apache.http.impl.execchain.RetryExec - Retrying request to {}->http://0.0.0.0:4723

Env:
Appium 1.6.1
Android/6.0 Emulator Nexus 6p

**Comment by mykola-mokhnach** [comment]
The provided information is not enough to make any assumptions. Please attach full server log along with code examples

**Comment by Zbr123** [comment]
Code Snippet:

logVerifyTrue("Flight Duration Verification",flightDuration, getPageRequestFlightAndroid().getFlightDurationId().getText() );

logVerifyTrue("Departure Airport Text Verification",departureAirportText, getPageRequestFlightAndroid().getOnBookingDeptAirportText().getText() );

logVerifyTrue("Departure Airport Name Verification",departureAirportName, getPageRequestFlightAndroid().getOnBookingDeptAirportName().getText() );

logVerifyTrue("Arrival Airport Text Verification",arrivalAirportText, getPageRequestFlightAndroid().getOnBookingArrAirportText().getText() );
 
logVerifyTrue("Arrival Airport Name Verification",arrivalAirportName, getPageRequestFlightAndroid().getOnBookingArrAirportName().getText() );

logVerifyTrue("Pax Count Verification","01",getPageRequestFlightAndroid().getPaxCountBookingScreen().getText());

logVerifyTrue("Aircraft Verification",aircraftName,getPageRequestFlightAndroid().getAircraftNameBookingScreen().getText());

Issue: 
[Forwarding getElementText on session 1a6cb406-6c04-48a9-a9aa-0152cc3eda96 to remote] INFO  org.apache.http.impl.execchain.RetryExec - I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://0.0.0.0:4723: The target server failed to respond
12:33:59.605 [Forwarding getElementText on session 1a6cb406-6c04-48a9-a9aa-0152cc3eda96 to remote] INFO  org.apache.http.impl.execchain.RetryExec - Retrying request to {}->http://0.0.0.0:4723

Logs:

[ADB] Getting install status for io.appium.settings
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\VenD-Zubair\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pm list packages io.appium.settings'
[ADB] Signing 'C:\Users\VenD-Zubair\apk.apk' with default cert
[ADB] Using apksigner.bat from C:\Users\VenD-Zubair\AppData\Local\Android\Sdk\build-tools\27.0.3\apksigner.bat
[ADB] Patching 'C:\Users\VenD-Zubair\AppData\Local\Android\Sdk\build-tools\27.0.3\apksigner.bat' for Windows...
[ADB] Starting patched 'C:\Users\VEND-Z~1\AppData\Local\Temp\201863-237560-1tggl8x.qrew\apksigner.bat' with args 'sign,--key,C:\Program Files (x86)\Appium\resources\app\node_modules\appium-adb\keys\testkey.pk8,--cert,C:\Program Files (x86)\Appium\resources\app\node_modules\appium-adb\keys\testkey.x509.pem,C:\Users\VenD-Zubair\apk.apk'
[ADB] Getting install status for com.vistajet.app.android.qa
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\VenD-Zubair\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pm list packages com.vistajet.app.android.qa'
[ADB] App is installed
[ADB] Getting package info for 'io.appium.settings'
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\VenD-Zubair\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys package io.appium.settings'
[ADB] Checking whether aapt is present
[ADB] Using aapt.exe from C:\Users\VenD-Zubair\AppData\Local\Android\Sdk\build-tools\27.0.3\aapt.exe
[ADB] The installed 'io.appium.settings' package does not require upgrade ('2.3.0' >= '2.3.0')
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\VenD-Zubair\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell ps'
[ADB] App is not installed
[AndroidDriver] Running full reset on 'com.vistajet.app.android.qa' (reinstall)
[ADB] Running 'C:\Users\VenD-Zubair\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 install -r C\:\\Users\\VenD-Zubair\\apk.apk'
[AndroidDriver] io.appium.settings is already running. There is no need to reset its permissions.
[ADB] Device API level: 23
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\VenD-Zubair\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell appops set io.appium.settings android\:mock_location allow'
[AndroidDriver] setDeviceLanguageCountry requires language or country.
[AndroidDriver] Got language: 'undefined' and country: 'undefined'
[Logcat] Starting logcat capture
[AndroidDriver] Pushing unlock helper app to device...
[ADB] Getting install status for io.appium.unlock
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\VenD-Zubair\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pm list packages io.appium.unlock'
[ADB] App is installed
[ADB] Getting package info for 'io.appium.unlock'
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\VenD-Zubair\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys package io.appium.unlock'
[ADB] Checking whether aapt is present
[ADB] Using aapt.exe from C:\Users\VenD-Zubair\AppData\Local\Android\Sdk\build-tools\27.0.3\aapt.exe
[ADB] The installed 'io.appium.unlock' package does not require upgrade ('2.0.0' >= '2.0.0')
[UiAutomator2] Forwarding UiAutomator2 Server port 6790 to 8203
[ADB] Forwarding system: 8203 to device: 6790
[ADB] Running 'C:\Users\VenD-Zubair\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 forward tcp\:8203 tcp\:6790'
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\VenD-Zubair\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell rm -rf /data/local/tmp/strings.json'
[AndroidDriver] Extracting strings from apk
[AndroidDriver] C:\Users\VenD-Zubair\apk.apk
[AndroidDriver] undefined
[AndroidDriver] C:\Users\VEND-Z~1\AppData\Local\Temp\com.vistajet.app.android.qa
[ADB] Extracting strings for language: default
[ADB] Checking whether aapt is present
[ADB] Using aapt.exe from C:\Users\VenD-Zubair\AppData\Local\Android\Sdk\build-tools\27.0.3\aapt.exe
[ADB] Successfully extracted 1956 strings from 'C:\Users\VenD-Zubair\apk.apk' resources for '(default)' configuration
[ADB] Running 'C:\Users\VenD-Zubair\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 push C\:\\Users\\VEND-Z~1\\AppData\\Local\\Temp\\com.vistajet.app.android.qa\\strings.json /data/local/tmp'
[ADB] Uninstalling com.vistajet.app.android.qa
[ADB] Getting install status for com.vistajet.app.android.qa
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\VenD-Zubair\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pm list packages com.vistajet.app.android.qa'
[ADB] App is not installed
[ADB] com.vistajet.app.android.qa was not uninstalled, because it was not present on the device
[ADB] Checking app cert for C:\Users\VenD-Zubair\apk.apk
[ADB] Using apksigner.bat from C:\Users\VenD-Zubair\AppData\Local\Android\Sdk\build-tools\27.0.3\apksigner.bat
[ADB] Using apksigner.bat from C:\Users\VenD-Zubair\AppData\Local\Android\Sdk\build-tools\27.0.3\apksigner.bat
[ADB] Patching 'C:\Users\VenD-Zubair\AppData\Local\Android\Sdk\build-tools\27.0.3\apksigner.bat' for Windows...
[ADB] Starting patched 'C:\Users\VEND-Z~1\AppData\Local\Temp\201863-237560-c3sq3k.m51yo\apksigner.bat' with args 'verify,--print-certs,C:\Users\VenD-Zubair\apk.apk'
[ADB] 'C:\Users\VenD-Zubair\apk.apk' is not signed with debug cert.
[ADB] Using apksigner.bat from C:\Users\VenD-Zubair\AppData\Local\Android\Sdk\build-tools\27.0.3\apksigner.bat
[ADB] Zip-aligning 'C:\Users\VenD-Zubair\apk.apk'
[ADB] Checking whether zipalign is present
[ADB] Using zipalign.exe from C:\Users\VenD-Zubair\AppData\Local\Android\Sdk\build-tools\27.0.3\zipalign.exe
[ADB] Signing 'C:\Users\VenD-Zubair\apk.apk' with default cert
[ADB] Using apksigner.bat from C:\Users\VenD-Zubair\AppData\Local\Android\Sdk\build-tools\27.0.3\apksigner.bat
[ADB] Patching 'C:\Users\VenD-Zubair\AppData\Local\Android\Sdk\build-tools\27.0.3\apksigner.bat' for Windows...
[ADB] Starting patched 'C:\Users\VEND-Z~1\AppData\Local\Temp\201863-237560-jbutol.u7vjs\apksigner.bat' with args 'sign,--key,C:\Program Files (x86)\Appium\resources\app\node_modules\appium-adb\keys\testkey.pk8,--cert,C:\Program Files (x86)\Appium\resources\app\node_modules\appium-adb\keys\testkey.x509.pem,C:\Users\VenD-Zubair\apk.apk'
[ADB] Getting install status for com.vistajet.app.android.qa
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\VenD-Zubair\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pm list packages com.vistajet.app.android.qa'
[ADB] App is not installed
[AndroidDriver] Running full reset on 'com.vistajet.app.android.qa' (reinstall)
[ADB] Running 'C:\Users\VenD-Zubair\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 install -r C\:\\Users\\VenD-Zubair\\apk.apk'
[ADB] Install command stdout: [  0%] /data/local/tmp/apk.apk
[ADB] [  0%] /data/local/tmp/apk.apk
[ADB] [  0%] /data/local/tmp/apk.apk
[ADB] [  0%] /data/local/tmp/apk.apk
[ADB] [  0%] /data/local/tmp...%] /data/local/tmp/apk.apk
[ADB] C:\Users\VenD-Zubair\apk.apk: 1 file pushed. 15.7 MB/s (63430840 bytes in 3.863s)
[ADB] 	pkg: /data/local/tmp/apk.apk

[ADB] Success
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\VenD-Zubair\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell am force-stop io.appium.uiautomator2.server'
[UiAutomator2] Starting uiautomator2 server 1.10.0
[UiAutomator2] Using UIAutomator2 server from 'C:\Program Files (x86)\Appium\resources\app\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v1.10.0.apk' and test from 'C:\Program Files (x86)\Appium\resources\app\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk'
[UiAutomator2] Running command: 'adb -s emulator-5554 shell am instrument -w io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner'
[UiAutomator2] Waiting up to 20000ms for UiAutomator2 to be online...
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8203/wd/hub/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8203/wd/hub/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8203/wd/hub/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8203/wd/hub/status] with no body
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"SESSIONID\",\"status\":0,\"value\":\"Status Invoked\"}"
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8203/wd/hub/session] with body: {"desiredCapabilities":{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"app":"C:\\Users\\VenD-Zubair\\apk.apk","noReset":false,"clearSystemFiles":true,"newCommandTimeout":15000,"platformVersion":"6.0","automationName":"UiAutomator2","appWaitActivity":"com.vistajet.app.android.ui.activities.EducationalActivity","platformName":"Android","deviceName":"192.168.56.101:5555","fullReset":true,"autoAcceptAlerts":false},"app":"C:\\Users\\VenD-Zubair\\apk.apk","noReset":false,"clearSystemFiles":true,"newCommandTimeout":15000,"platformVersion":"6.0","automationName":"UiAutomator2","appWaitActivity":"com.vistajet.app.android.ui.activities.EducationalActivity","platformName":"Android","deviceName":"emulator-5554","fullReset":true,"autoAcceptAlerts":false,"deviceUDID":"emulator-5554","deviceScreenSize":"1080x1920","deviceScreenDensity":420,"deviceModel":"Android SD...
[JSONWP Proxy] Got response with status 200: {"sessionId":"32913d3a-0fb5-4b94-a196-f5b67884da70","status":0,"value":"Created Session"}
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\VenD-Zubair\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys window'
[AndroidDriver] Screen already unlocked, doing nothing
[UiAutomator2] UiAutomator2 did not start the activity we were waiting for, 'com.vistajet.app.android.qa/com.vistajet.app.android.ui.activities.EducationalActivity'. Starting it ourselves
[ADB] Device API level: 23
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\VenD-Zubair\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell am start -W -n com.vistajet.app.android.qa/com.vistajet.app.android.ui.activities.SplashActivity -S'
[ADB] Waiting up to 20000ms for activity matching pkg: 'com.vistajet.app.android.qa' and activity: 'com.vistajet.app.android.ui.activities.EducationalActivity' to be focused
[ADB] Possible activities, to be checked: 'com.vistajet.app.android.ui.activities.EducationalActivity', 'com.vistajet.app.android.qa.com.vistajet.app.android.ui.activities.EducationalActivity'
[ADB] Getting focused package and activity
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\VenD-Zubair\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys window windows'
[ADB] Found package: 'com.vistajet.app.android.qa' and fully qualified activity name : 'com.vistajet.app.android.ui.activities.SplashActivity'
[ADB] Incorrect package and activity. Retrying.
[ADB] Getting focused package and activity
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'C:\Users\VenD-Zubair\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys window windows'
[ADB] Found package: 'com.vistajet.app.android.qa' and fully qualified activity name : 'com.vistajet.app.android.ui.activities.EducationalActivity'
[JSONWP Proxy] Proxying [GET /appium/device/pixel_ratio] to [GET http://localhost:8203/wd/hub/session/32913d3a-0fb5-4b94-a196-f5b67884da70/appium/device/pixel_ratio] with body: {}
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"32913d3a-0fb5-4b94-a196-f5b67884da70\",\"status\":0,\"value\":2.625}"
[JSONWP Proxy] Proxying [GET /appium/device/system_bars] to [GET http://localhost:8203/wd/hub/session/32913d3a-0fb5-4b94-a196-f5b67884da70/appium/device/system_bars] with body: {}
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"32913d3a-0fb5-4b94-a196-f5b67884da70\",\"status\":0,\"value\":{\"statusBar\":63}}"
[JSONWP Proxy] Proxying [GET /window/current/size] to [GET http://localhost:8203/wd/hub/session/32913d3a-0fb5-4b94-a196-f5b67884da70/window/current/size] with body: {}
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"32913d3a-0fb5-4b94-a196-f5b67884da70\",\"status\":0,\"value\":{\"height\":1794,\"width\":1080}}"
[Appium] New AndroidUiautomator2Driver session created successfully, session d6cd6afe-2172-4c93-97d5-b0bd4e1de95e added to master session list
[BaseDriver] Event 'newSessionStarted' logged at 1530625088343 (18:38:08 GMT+0500 (Pakistan Standard Time))
[MJSONWP] Responding to client with driver.createSession() result: {"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"app":"C:\\Users\\VenD-Zubair\\apk.apk","noReset":false,"clearSystemFiles":true,"newCommandTimeout":15000,"platformVersion":"6.0","automationName":"UiAutomator2","appWaitActivity":"com.vistajet.app.android.ui.activities.EducationalActivity","platformName":"Android","deviceName":"192.168.56.101:5555","fullReset":true,"autoAcceptAlerts":false},"app":"C:\\Users\\VenD-Zubair\\apk.apk","noReset":false,"clearSystemFiles":true,"newCommandTimeout":15000,"platformVersion":"6.0","automationName":"UiAutomator2","appWaitActivity":"com.vistajet.app.android.ui.activities.EducationalActivity","platformName":"Android","deviceName":"emulator-5554","fullReset":true,"autoAcceptAlerts":false,"deviceUDID":"emulator-5554","deviceScreenSize":"1080x1920","deviceScreenDensity":420,"deviceModel":"Android SDK built for x86_64","de...
[HTTP] <-- POST /wd/hub/session 200 118600 ms - 1284
[HTTP] 
[HTTP] --> POST /wd/hub/session/d6cd6afe-2172-4c93-97d5-b0bd4e1de95e/timeouts
[HTTP] {"type":"implicit","ms":60000}
[MJSONWP] Calling AppiumDriver.timeouts() with args: [{"protocol":"MJSONWP","type":"implicit","ms":60000},"d6cd6afe-2172-4c93-97d5-b0bd4e1de95e"]
[BaseDriver] type: implicit, ms: 60000
[BaseDriver] Set implicit wait to 60000ms
[MJSONWP] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/d6cd6afe-2172-4c93-97d5-b0bd4e1de95e/timeouts 200 6 ms - 76
[HTTP] 
[HTTP] --> GET /wd/hub/session/d6cd6afe-2172-4c93-97d5-b0bd4e1de95e
[HTTP] {}
[MJSONWP] Calling AppiumDriver.getSession() with args: ["d6cd6afe-2172-4c93-97d5-b0bd4e1de95e"]
[UiAutomator2] Getting session details from server to mix in
[JSONWP Proxy] Proxying [GET /] to [GET http://localhost:8203/wd/hub/session/32913d3a-0fb5-4b94-a196-f5b67884da70] with body: {}
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"32913d3a-0fb5-4b94-a196-f5b67884da70\",\"status\":0,\"value\":{}}"
[MJSONWP] Responding to client with driver.getSession() result: {"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"app":"C:\\Users\\VenD-Zubair\\apk.apk","noReset":false,"clearSystemFiles":true,"newCommandTimeout":15000,"platformVersion":"6.0","automationName":"UiAutomator2","appWaitActivity":"com.vistajet.app.android.ui.activities.EducationalActivity","platformName":"Android","deviceName":"192.168.56.101:5555","fullReset":true,"autoAcceptAlerts":false},"app":"C:\\Users\\VenD-Zubair\\apk.apk","noReset":false,"clearSystemFiles":true,"newCommandTimeout":15000,"platformVersion":"6.0","automationName":"UiAutomator2","appWaitActivity":"com.vistajet.app.android.ui.activities.EducationalActivity","platformName":"Android","deviceName":"emulator-5554","fullReset":true,"autoAcceptAlerts":false,"deviceUDID":"emulator-5554","deviceScreenSize":"1080x1920","deviceScreenDensity":420,"deviceModel":"Android SDK built for x86_64","de...
[HTTP] <-- GET /wd/hub/session/d6cd6afe-2172-4c93-97d5-b0bd4e1de95e 200 44 ms - 1284
[HTTP] 
[HTTP] --> POST /wd/hub/session/d6cd6afe-2172-4c93-97d5-b0bd4e1de95e/element
[HTTP] {"using":"id","value":"com.vistajet.app.android.qa:id/login_layout"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["id","com.vistajet.app.android.qa:id/login_layout","d6cd6afe-2172-4c93-97d5-b0bd4e1de95e"]
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Waiting up to 60000 ms for condition
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8203/wd/hub/session/32913d3a-0fb5-4b94-a196-f5b67884da70/element] with body: {"strategy":"id","selector":"com.vistajet.app.android.qa:id/login_layout","context":"","multiple":false}
[BaseDriver] Waited for 69 ms so far
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8203/wd/hub/session/32913d3a-0fb5-4b94-a196-f5b67884da70/element] with body: {"strategy":"id","selector":"com.vistajet.app.android.qa:id/login_layout","context":"","multiple":false}
[BaseDriver] Waited for 607 ms so far
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8203/wd/hub/session/32913d3a-0fb5-4b94-a196-f5b67884da70/element] with body: {"strategy":"id","selector":"com.vistajet.app.android.qa:id/login_layout","context":"","multiple":false}
[BaseDriver] Waited for 1194 ms so far
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8203/wd/hub/session/32913d3a-0fb5-4b94-a196-f5b67884da70/element] with body: {"strategy":"id","selector":"com.vistajet.app.android.qa:id/login_layout","context":"","multiple":false}
[BaseDriver] Waited for 1746 ms so far
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8203/wd/hub/session/32913d3a-0fb5-4b94-a196-f5b67884da70/element] with body: {"strategy":"id","selector":"com.vistajet.app.android.qa:id/login_layout","context":"","multiple":false}
[BaseDriver] Waited for 2266 ms so far
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8203/wd/hub/session/32913d3a-0fb5-4b94-a196-f5b67884da70/element] with body: {"strategy":"id","selector":"com.vistajet.app.android.qa:id/login_layout","context":"","multiple":false}
[BaseDriver] Waited for 2826 ms so far
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8203/wd/hub/session/32913d3a-0fb5-4b94-a196-f5b67884da70/element] with body: {"strategy":"id","selector":"com.vistajet.app.android.qa:id/login_layout","context":"","multiple":false}
[BaseDriver] Waited for 3381 ms so far
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8203/wd/hub/session/32913d3a-0fb5-4b94-a196-f5b67884da70/element] with body: {"strategy":"id","selector":"com.vistajet.app.android.qa:id/login_layout","context":"","multiple":false}
[BaseDriver] Waited for 3896 ms so far
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8203/wd/hub/session/32913d3a-0fb5-4b94-a196-f5b67884da70/element] with body: {"strategy":"id","selector":"com.vistajet.app.android.qa:id/login_layout","context":"","multiple":false}
[BaseDriver] Waited for 4415 ms so far
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8203/wd/hub/session/32913d3a-0fb5-4b94-a196-f5b67884da70/element] with body: {"strategy":"id","selector":"com.vistajet.app.android.qa:id/login_layout","context":"","multiple":false}
[BaseDriver] Waited for 4946 ms so far
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8203/wd/hub/session/32913d3a-0fb5-4b94-a196-f5b67884da70/element] with body: {"strategy":"id","selector":"com.vistajet.app.android.qa:id/login_layout","context":"","multiple":false}
[BaseDriver] Waited for 5459 ms so far
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8203/wd/hub/session/32913d3a-0fb5-4b94-a196-f5b67884da70/element] with body: {"strategy":"id","selector":"com.vistajet.app.android.qa:id/login_layout","context":"","multiple":false}
[BaseDriver] Waited for 5974 ms so far
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8203/wd/hub/session/32913d3a-0fb5-4b94-a196-f5b67884da70/element] with body: {"strategy":"id","selector":"com.vistajet.app.android.qa:id/login_layout","context":"","multiple":false}
[BaseDriver] Waited for 6508 ms so far
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8203/wd/hub/session/32913d3a-0fb5-4b94-a196-f5b67884da70/element] with body: {"strategy":"id","selector":"com.vistajet.app.android.qa:id/login_layout","context":"","multiple":false}
[BaseDriver] Waited for 7022 ms so far
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8203/wd/hub/session/32913d3a-0fb5-4b94-a196-f5b67884da70/element] with body: {"strategy":"id","selector":"com.vistajet.app.android.qa:id/login_layout","context":"","multiple":false}
[BaseDriver] Waited for 7549 ms so far
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8203/wd/hub/session/32913d3a-0fb5-4b94-a196-f5b67884da70/element] with body: {"strategy":"id","selector":"com.vistajet.app.android.qa:id/login_layout","context":"","multiple":false}
[BaseDriver] Waited for 8084 ms so far
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8203/wd/hub/session/32913d3a-0fb5-4b94-a196-f5b67884da70/element] with body: {"strategy":"id","selector":"com.vistajet.app.android.qa:id/login_layout","context":"","multiple":false}
[BaseDriver] Waited for 8608 ms so far
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8203/wd/hub/session/32913d3a-0fb5-4b94-a196-f5b67884da70/element] with body: {"strategy":"id","selector":"com.vistajet.app.android.qa:id/login_layout","context":"","multiple":false}
[BaseDriver] Waited for 9124 ms so far
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8203/wd/hub/session/32913d3a-0fb5-4b94-a196-f5b67884da70/element] with body: {"strategy":"id","selector":"com.vistajet.app.android.qa:id/login_layout","context":"","multiple":false}
[BaseDriver] Waited for 9642 ms so far
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8203/wd/hub/session/32913d3a-0fb5-4b94-a196-f5b67884da70/element] with body: {"strategy":"id","selector":"com.vistajet.app.android.qa:id/login_layout","context":"","multiple":false}
[BaseDriver] Waited for 10171 ms so far
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8203/wd/hub/session/32913d3a-0fb5-4b94-a196-f5b67884da70/element] with body: {"strategy":"id","selector":"com.vistajet.app.android.qa:id/login_layout","context":"","multiple":false}
[BaseDriver] Waited for 10882 ms so far
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8203/wd/hub/session/32913d3a-0fb5-4b94-a196-f5b67884da70/element] with body: {"strategy":"id","selector":"com.vistajet.app.android.qa:id/login_layout","context":"","multiple":false}
[BaseDriver] Waited for 11396 ms so far
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8203/wd/hub/session/32913d3a-0fb5-4b94-a196-f5b67884da70/element] with body: {"strategy":"id","selector":"com.vistajet.app.android.qa:id/login_layout","context":"","multiple":false}
[BaseDriver] Waited for 11917 ms so far
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8203/wd/hub/session/32913d3a-0fb5-4b94-a196-f5b67884da70/element] with body: {"strategy":"id","selector":"com.vistajet.app.android.qa:id/login_layout","context":"","multiple":false}
[BaseDriver] Waited for 12456 ms so far
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8203/wd/hub/session/32913d3a-0fb5-4b94-a196-f5b67884da70/element] with body: {"strategy":"id","selector":"com.vistajet.app.android.qa:id/login_layout","context":"","multiple":false}
[BaseDriver] Waited for 13010 ms so far
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8203/wd/hub/session/32913d3a-0fb5-4b94-a196-f5b67884da70/element] with body: {"strategy":"id","selector":"com.vistajet.app.android.qa:id/login_layout","context":"","multiple":false}

**Comment by Zbr123** [comment]
@mykola-mokhnach : The major issue, APPIUM unable to get the getText from specific locators and Application is hung and trying to get the text but did not find.

Issue area is 
[Forwarding getElementText on session 1a6cb406-6c04-48a9-a9aa-0152cc3eda96 to remote] INFO org.apache.http.impl.execchain.RetryExec - I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://0.0.0.0:4723: The target server failed to respond

Let me know what else i can provide.

**Comment by mykola-mokhnach** [comment]
What I see in the log is that the particular element cannot be found:

> [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8203/wd/hub/session/32913d3a-0fb5-4b94-a196-f5b67884da70/element] with body: {"strategy":"id","selector":"com.vistajet.app.android.qa:id/login_layout","context":"","multiple":false}

I don't observe any requests to get the text of an element.
