### ISSUE TITLE
"toVisible":"true" fail in XCUIElementTypeCollectionView view ,predicateString sometimes timed out 

### ISSUE THREAD

**Issue by Kitty2014** [appium/appium#10990]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version: 1.8.2-beta
Latest version of WDA
Desktop OS/version used to run Appium: Mac OS 10.13.6 Beta (17G54a)
Node.js version: v9.4.0
Mobile platform/version under test: iOS 11.4 (iPhone 6+ iphoneX)
Real device: iphoneX

## Details
{"script":"mobile:scroll","args":[{"toVisible":"true","predicateString":"wdLabel == '优信认证'"}]}

works in XCUIElementTypeTable view
fail in XCUIElementTypeCollectionView view

## Link to Appium logs

[debug] [XCUITest] Log file for xcodebuild test: /var/folders/c2/cllky7gs5mg0n8rbz8jygwz40000gn/T/com.apple.dt.XCTest/IDETestRunSession-987C7AA8-30EE-44A8-A3B8-C8E644A484C4/WebDriverAgentRunner-70D1CE68-4B5A-4C51-B446-EA9BDEE3926B/Session-WebDriverAgentRunner-2018-07-04_105453-4Unfov.log
[Xcode] 2018-07-04 10:54:53.176 xcodebuild[18186:3816663]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
[Xcode] /var/folders/c2/cllky7gs5mg0n8rbz8jygwz40000gn/T/com.apple.dt.XCTest/IDETestRunSession-987C7AA8-30EE-44A8-A3B8-C8E644A484C4/WebDriverAgentRunner-70D1CE68-4B5A-4C51-B446-EA9BDEE3926B/Session-WebDriverAgentRunner-2018-07-04_105453-4Unfov.log
[Xcode] 
[Xcode] 2018-07-04 10:54:53.177 xcodebuild[18186:3816427] [MT] IDETestOperationsObserverDebug: (66713145-DA3B-4AB8-8A43-3B2897A89528) Beginning test session WebDriverAgentRunner-66713145-DA3B-4AB8-8A43-3B2897A89528 at 2018-07-04 10:54:53.177 with Xcode 9F2000 on target <DVTiOSDevice: 0x7fef32680be0> {
[Xcode] 		deviceSerialNumber:         F17VLJAAJCLG
[Xcode] 		identifier:                 b8cf8bea07d2b25bf3b0ae8a129a5718f9c29c0c
[Xcode] 		deviceClass:                iPhone
[Xcode] 		deviceName:                 iPhone
[Xcode] 		deviceIdentifier:           b8cf8bea07d2b25bf3b0ae8a129a5718f9c29c0c
[Xcode] 		productVersion:             11.4
[Xcode] 		buildVersion:               15F79
[Xcode] 		deviceSoftwareVersion:      (null)
[Xcode] 		deviceArchitecture:         arm64
[Xcode] 		deviceTotalCapacity:        60254281728
[Xcode] 		deviceAvailableCapacity:    46683947008
[Xcode] 		deviceIsTransient:          NO
[Xcode] 		ignored:                    YES
[Xcode] 		deviceIsBusy:               NO
[Xcode] 		deviceIsActivated:          YES
[Xcode] 		deviceActivationState:      Activated
[Xcode] 		isPasscodeLocked:           NO
[Xcode] 		deviceType:                 <DVTDeviceType:0x7fef2fb1d460 Xcode.DeviceType.iPhone>
[Xcode] 		supportedDeviceFamilies:    (null)
[Xcode] 		applications:              (null)
[Xcode] 		provisioningProfiles:      (null)
[Xcode] 		hasInternalSupport:        NO
[Xcode] 		isSupportedOS:             NO
[Xcode] 		developerDiskMountError:   (null)
[Xcode] (null)
[Xcode] 	bootArgs:                  <unavailable>
[Xcode] 		connected:                 no
[Xcode] 		isWirelessEnabled:         no
[Xcode] 		connectionType:            direct
[Xcode] 		} ((null))
[Xcode] 
[HTTP] --> POST /wd/hub/session/63aebd1f-26a8-4449-a29d-0e981f73c9b8/execute
[HTTP] {"script":"mobile:scroll","args":[{"toVisible":"true","predicateString":"wdLabel == '优信认证'"}]}
[debug] [MJSONWP] Calling AppiumDriver.execute() with args: ["mobile:scroll",[{"toVisible":"true","predicateString":"wdLabel == '优信认证'"}],"63aebd1f-26a8-4449-a29d-0e981f73c9b8"]
[debug] [XCUITest] Executing command 'execute'
[debug] [BaseDriver] Waiting up to 1000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:4601/session/E79D9B33-E3BF-4D0E-8353-7E605321122B/element] with body: {"using":"class name","value":"XCUIElementTypeApplication"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"using":"class name","value":"XCUIElementTypeApplication","description":"unable to find an element"},"sessionId":"E79D9B33-E3BF-4D0E-8353-7E605321122B","status":7}
[HTTP] <-- POST /wd/hub/session/63aebd1f-26a8-4449-a29d-0e981f73c9b8/execute 500 65221 ms - 164
[HTTP] 
[debug] [XCUITest] Connection to WDA timed out
[debug] [iProxy] recv failed: Operation not permitted
[HTTP] --> POST /wd/hub/session/63aebd1f-26a8-4449-a29d-0e981f73c9b8/element
[HTTP] {"using":"-ios predicate string","value":"name = '优信认证'"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["-ios predicate string","name = '优信认证'","63aebd1f-26a8-4449-a29d-0e981f73c9b8"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 1000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:4601/session/E79D9B33-E3BF-4D0E-8353-7E605321122B/element] with body: {"using":"predicate string","value":"name = '优信认证'"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"using":"predicate string","value":"name = '优信认证'","description":"unable to find an element"},"sessionId":"E79D9B33-E3BF-4D0E-8353-7E605321122B","status":7}
[HTTP] <-- POST /wd/hub/session/63aebd1f-26a8-4449-a29d-0e981f73c9b8/element 500 5056 ms - 164
[HTTP] 
[HTTP] --> POST /wd/hub/session/63aebd1f-26a8-4449-a29d-0e981f73c9b8/appium/app/close
[HTTP] {}
[debug] [MJSONWP] Calling AppiumDriver.closeApp() with args: ["63aebd1f-26a8-4449-a29d-0e981f73c9b8"]
[debug] [XCUITest] Executing command 'closeApp'
[debug] [JSONWP Proxy] Proxying [DELETE /session/63aebd1f-26a8-4449-a29d-0e981f73c9b8] to [DELETE http://localhost:4601/session/E79D9B33-E3BF-4D0E-8353-7E605321122B] with no body
[HTTP] <-- POST /wd/hub/session/63aebd1f-26a8-4449-a29d-0e981f73c9b8/appium/app/close - - ms - -

Success Log

-C9B9-449D-A1B3-D39892598FC7 with 2d51a13d-8b81-4f6c-9507-eb413eba6327
[HTTP] <-- GET /wd/hub/session/2d51a13d-8b81-4f6c-9507-eb413eba6327/element/2F030000-0000-0000-9116-000000000000/text 200 248 ms - 75
[HTTP] 
[debug] [XCUITest] Connection to WDA timed out
[debug] [iProxy] recv failed: Operation not permitted
[HTTP] --> POST /wd/hub/session/2d51a13d-8b81-4f6c-9507-eb413eba6327/execute
[HTTP] {"script":"mobile:scroll","args":[{"toVisible":"true","predicateString":"wdName == '优信认证'"}]}
[debug] [MJSONWP] Calling AppiumDriver.execute() with args: ["mobile:scroll",[{"toVisible":"true","predicateString":"wdName == '优信认证'"}],"2d51a13d-8b81-4f6c-9507-eb413eba6327"]
[debug] [XCUITest] Executing command 'execute'
[debug] [BaseDriver] Waiting up to 1000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:4601/session/BFDC7224-C9B9-449D-A1B3-D39892598FC7/element] with body: {"using":"class name","value":"XCUIElementTypeApplication"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"01000000-0000-0000-9116-000000000000"},"sessionId":"BFDC7224-C9B9-449D-A1B3-D39892598FC7","status":0}
[XCUITest] Proxying to WDA with an unknown route: POST /wda/element/01000000-0000-0000-9116-000000000000/scroll
[debug] [JSONWP Proxy] Proxying [POST /wda/element/01000000-0000-0000-9116-000000000000/scroll] to [POST http://localhost:4601/session/BFDC7224-C9B9-449D-A1B3-D39892598FC7/wda/element/01000000-0000-0000-9116-000000000000/scroll] with body: {"predicateString":"wdName == '优信认证'"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"BFDC7224-C9B9-449D-A1B3-D39892598FC7","status":0}
[debug] [MJSONWP] Responding to client with driver.execute() result: {}
[HTTP] <-- POST /wd/hub/session/2d51a13d-8b81-4f6c-9507-eb413eba6327/execute 200 6137 ms - 74
[HTTP] 
[HTTP] --> POST /wd/hub/session/2d51a13d-8b81-4f6c-9507-eb413eba6327/element
[HTTP] {"using":"name","value":"优信认证"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["name","优信认证","2d51a13d-8b81-4f6c-9507-eb413eba6327"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 1000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:4601/session/BFDC7224-C9B9-449D-A1B3-D39892598FC7/element] with body: {"using":"name","value":"优信认证"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"1D040000-0000-0000-9116-000000000000"},"sessionId":"BFDC7224-C9B9-449D-A1B3-D39892598FC7","status":0}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"1D040000-0000-0000-9116-000000000000"}
[HTTP] <-- POST /wd/hub/session/2d51a13d-8b81-4f6c-9507-eb413eba6327/element 200 409 ms - 122
[HTTP] 
[HTTP] --> POST /wd/hub/session/2d51a13d-8b81-4f6c-9507-eb413eba6327/element
[HTTP] {"using":"-ios predicate string","value":"wdName == '优信认证' AND visible == 1"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["-ios predicate string","wdName == '优信认证' AND visible == 1","2d51a13d-8b81-4f6c-9507-eb413eba6327"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 1000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:4601/session/BFDC7224-C9B9-449D-A1B3-D39892598FC7/element] with body: {"using":"predicate string","value":"wdName == '优信认证' AND visible == 1"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"1D040000-0000-0000-9116-000000000000"},"sessionId":"BFDC7224-C9B9-449D-A1B3-D39892598FC7","status":0}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"1D040000-0000-0000-9116-000000000000"}
[HTTP] <-- POST /wd/hub/session/2d51a13d-8b81-4f6c-9507-eb413eba6327/element 200 679 ms - 122
[HTTP] 
[HTTP] --> POST /wd/hub/session/2d51a13d-8b81-4f6c-9507-eb413eba6327/element/1D040000-0000-0000-9116-000000000000/click
[HTTP] {"id":"1D040000-0000-0000-9116-000000000000"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/2d51a13d-8b81-4f6c-9507-eb413eba6327/element/1D040000-0000-0000-9116-000000000000/click] to [POST http://localhost:4601/session/BFDC7224-C9B9-449D-A1B3-D39892598FC7/element/1D040000-0000-0000-9116-000000000000/click] with body: {"id":"1D040000-0000-0000-9116-000000000000"}
[debug] [JSONWP Proxy] Got response with status 200: {"status":0,"id":"1D040000-0000-0000-9116-000000000000","value":"","sessionId":"BFDC7224-C9B9-449D-A1B3-D39892598FC7"}
[JSONWP Proxy] Replacing sessionId BFDC7224-C9B9-449D-A1B3-D39892598FC7 with 2d51a13d-8b81-4f6c-9507-eb413eba6327
[HTTP] <-- POST /wd/hub/session/2d51a13d-8b81-4f6c-9507-eb413eba6327/element/1D040000-0000-0000-9116-000000000000/click 200 1627 ms - 118
[HTTP]

**Comment by Kitty2014** [comment]
<img width="690" alt="xcuielementtypecollectionview" src="https://user-images.githubusercontent.com/7512412/42255585-0a9849b2-7f7f-11e8-81ee-92b302badb2c.png">

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/appium/WebDriverAgent

Closed as third party issue.
