### ISSUE TITLE
MobileElement not returning the updated text value from getText().

### ISSUE THREAD

**Issue by feekay** [appium/appium#10995]
MobileElement not returning the updated text value from getText(). Although the updated text is visible on the screen. The MobileElement returns the default value set instead.

* Appium 1.6.1
* Android/6.0 Emulator Nexus 6p

**Comment by mykola-mokhnach** [comment]
Please provide the required issue details, like server logs and source tree snapshots.

**Comment by shehzadafahad** [comment]
try getAttribute("value") instead of getText()

**Comment by Zbr123** [comment]
@shehzadafahad : Nope it does not work.
![actualscreen](https://user-images.githubusercontent.com/19738774/42280334-df113372-7fb9-11e8-8368-c937fc69632d.PNG)
![screen1](https://user-images.githubusercontent.com/19738774/42280336-df45fddc-7fb9-11e8-9f77-42882abba51e.PNG)
![screen2](https://user-images.githubusercontent.com/19738774/42280337-df793c9c-7fb9-11e8-847f-f26c9473efba.PNG)

**Comment by mykola-mokhnach** [comment]
The actual value equals to what the accessibility framework retrieves from the application under test. You can verify it using any screen reader or accessibility inspector. So I would assume you must rather solve the problem with the application developers.
