### ISSUE TITLE
NoSuchElementException: Message

### ISSUE THREAD

**Issue by jason102190** [appium/appium#10991]
## The problem

NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

## Environment

* Appium version-1.8.0
* Selenium version- 2.53.6
* Desktop OS/version-windows7
* Node.js version-v8.11.3
* Mobile platform/version-Android 8.0 
* Real device or emulator/simulator:Pixel
* Appium CLI or Appium.app|exe:

## Details

When I run my script on my phone(NEXUS,android6.0),is worked;but when I run it on my another test device(Pixel,android8.0),its throw an err:NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

**Comment by mykola-mokhnach** [comment]
- Do you use uiautomator2?
- Have you verified whether the element is present in the page source?
- Do you have server logs?

**Comment by jason102190** [comment]
##I dont have uiautomator2;but it worked on my android(6.0) device
##then I change my android(8.0);

##log out -->

'''C:\Users\Administrator>appium
[Appium] Welcome to Appium v1.8.0
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"requiredCapabilities":{},"desiredCapabilities":{"platformVersion":"8.0"
,"deviceName":"FA6BK0301264","platformName":"Android","appActivity":".BlmSplashA
ctivity","appPackage":"com.blockchain.blm"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformVer
sion":"8.0","deviceName":"FA6BK0301264","platformName":"Android","appActivity":"
.BlmSplashActivity","appPackage":"com.blockchain.blm"},{},null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1530696774480 (17:32:
54 GMT+0800 (中国标准时间))
[Appium] Consider setting 'automationName' capability to 'uiautomator2' on Andro
id >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.

[Appium] Creating new AndroidDriver (v2.7.0) session
[Appium] Capabilities:
[Appium]   platformVersion: 8.0
[Appium]   deviceName: FA6BK0301264
[Appium]   platformName: Android
[Appium]   appActivity: .BlmSplashActivity
[Appium]   appPackage: com.blockchain.blm
[debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {"platf
ormVersion":"8.0","d...
[BaseDriver] Session created with session id: 5cba9ca0-8b04-4aaf-a74f-455ac43840
b4
[debug] [AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_112
[ADB] Checking whether adb is present
[ADB] Found 3 'build-tools' folders under 'D:\android-sdk-windows' (newest first
):
[ADB]     D:/android-sdk-windows/build-tools/26.0.0
[ADB]     D:/android-sdk-windows/build-tools/26.0.0-preview
[ADB]     D:/android-sdk-windows/build-tools/23.0.1
[ADB] Using adb.exe from D:\android-sdk-windows\platform-tools\adb.exe
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[AndroidDriver] Looking for a device with Android '8.0'
[debug] [ADB] Setting device id to FA6BK0301264
[ADB] Getting device platform version
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s
FA6BK0301264 shell getprop ro.build.version.release'
[debug] [ADB] Current device property 'ro.build.version.release': 8.0.0
[AndroidDriver] Using device: FA6BK0301264
[debug] [ADB] Setting device id to FA6BK0301264
[AndroidDriver] App file was not listed, instead we're going to run com.blockcha
in.blm directly on the device
[debug] [AndroidDriver] Checking whether package is present on the device
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s
FA6BK0301264 shell pm list packages com.blockchain.blm'
[AndroidDriver] Starting Android session
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s
FA6BK0301264 wait-for-device'
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s
FA6BK0301264 shell echo ping'
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Getting install status for io.appium.settings
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s
FA6BK0301264 shell pm list packages io.appium.settings'
[debug] [ADB] App is installed
[debug] [ADB] Getting package info for 'io.appium.settings'
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s
FA6BK0301264 shell dumpsys package io.appium.settings'
[ADB] Checking whether aapt is present
[ADB] Using aapt.exe from D:\android-sdk-windows\build-tools\26.0.0\aapt.exe
[debug] [ADB] The installed 'io.appium.settings' package does not require upgrad
e ('2.3.0' >= '2.3.0')
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s
FA6BK0301264 shell ps'
[debug] [AndroidDriver] io.appium.settings is already running. There is no need
to reset its permissions.
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s
FA6BK0301264 shell getprop ro.build.version.sdk'
[debug] [ADB] Current device property 'ro.build.version.sdk': 26
[debug] [ADB] Device API level: 26
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s
FA6BK0301264 shell appops set io.appium.settings android\:mock_location allow'
[AndroidDriver] setDeviceLanguageCountry requires language or country.
[AndroidDriver] Got language: 'null' and country: 'null'
[debug] [Logcat] Starting logcat capture
[debug] [AndroidDriver] Pushing unlock helper app to device...
[debug] [ADB] Getting install status for io.appium.unlock
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s
FA6BK0301264 shell pm list packages io.appium.unlock'
[debug] [ADB] App is installed
[debug] [ADB] Getting package info for 'io.appium.unlock'
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s
FA6BK0301264 shell dumpsys package io.appium.unlock'
[debug] [ADB] The installed 'io.appium.unlock' package does not require upgrade
('2.0.0' >= '2.0.0')
[ADB] Getting device platform version
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s
FA6BK0301264 shell getprop ro.build.version.release'
[debug] [ADB] Current device property 'ro.build.version.release': 8.0.0
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s
FA6BK0301264 shell wm size'
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s
FA6BK0301264 shell getprop ro.product.model'
[debug] [ADB] Current device property 'ro.product.model': Pixel
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s
FA6BK0301264 shell getprop ro.product.manufacturer'
[debug] [ADB] Current device property 'ro.product.manufacturer': Google
[AndroidDriver] No app sent in, not parsing package/activity
[debug] [AndroidDriver] No app capability. Assuming it is already on the device
[debug] [ADB] Getting install status for com.blockchain.blm
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s
FA6BK0301264 shell pm list packages com.blockchain.blm'
[debug] [ADB] App is installed
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s
FA6BK0301264 shell am force-stop com.blockchain.blm'
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s
FA6BK0301264 shell pm clear com.blockchain.blm'
[debug] [AndroidDriver] Performed fast reset on the installed 'com.blockchain.bl
m' application (stop and clear)
[debug] [AndroidBootstrap] Watching for bootstrap disconnect
[debug] [ADB] Forwarding system: 4724 to device: 4724
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s
FA6BK0301264 forward tcp\:4724 tcp\:4724'
[debug] [UiAutomator] Starting UiAutomator
[debug] [UiAutomator] Moving to state 'starting'
[debug] [UiAutomator] Parsing uiautomator jar
[debug] [UiAutomator] Found jar name: 'AppiumBootstrap.jar'
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s
FA6BK0301264 push D\:\\appium-1.8.0\\node_modules\\appium-android-bootstrap\\boo
tstrap\\bin\\AppiumBootstrap.jar /data/local/tmp/'
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s
FA6BK0301264 shell ps'
[ADB] No uiautomator process found to kill, continuing...
[debug] [UiAutomator] Starting UIAutomator
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","FA6BK0301264",
"shell","uiautomator","runtest","AppiumBootstrap.jar","-c","io.appium.android.bo
otstrap.Bootstrap","-e","pkg","com.blockchain.blm","-e","disableAndroidWatchers"
,false,"-e","acceptSslCerts",false]
[debug] [UiAutomator] Moving to state 'online'
[AndroidBootstrap] Android bootstrap socket is now connected
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s
FA6BK0301264 shell dumpsys window'
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Client connected
[AndroidDriver] Screen already unlocked, doing nothing
[debug] [ADB] Device API level: 26
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s
FA6BK0301264 shell am start -W -n com.blockchain.blm/.BlmSplashActivity -S -a an
droid.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[Appium] New AndroidDriver session created successfully, session 5cba9ca0-8b04-4
aaf-a74f-455ac43840b4 added to master session list
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1530696781927 (17:33:01
 GMT+0800 (中国标准时间))
[debug] [MJSONWP] Responding to client with driver.createSession() result: {"pla
tform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabl
ed":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContex
tEnabled":false,"warnings":{},"desired":{"platformVersion":"8.0","deviceName":"F
A6BK0301264","platformName":"Android","appActivity":".BlmSplashActivity","appPac
kage":"com.blockchain.blm"},"platformVersion":"8.0.0","deviceName":"FA6BK0301264
","platformName":"Android","appActivity":".BlmSplashActivity","appPackage":"com.
blockchain.blm","deviceUDID":"FA6BK0301264","deviceScreenSize":"1080x1920","devi
ceModel":"Pixel","deviceManufacturer":"Google"}
[HTTP] <-- POST /wd/hub/session 200 7469 ms - 684
[HTTP]
[HTTP] --> POST /wd/hub/session/5cba9ca0-8b04-4aaf-a74f-455ac43840b4/element
[HTTP] {"using":"id","sessionId":"5cba9ca0-8b04-4aaf-a74f-455ac43840b4","value":
"com.blockchain.blm:id/tab_mycenter"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["id","com.block
chain.blm:id/tab_mycenter","5cba9ca0-8b04-4aaf-a74f-455ac43840b4"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class
 name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":
"find","params":{"strategy":"id","selector":"com.blockchain.blm:id/tab_mycenter"
,"context":"","multiple":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":
"action","action":"find","params":{"strategy":"id","selector":"com.blockchain.bl
m:id/tab_mycenter","context":"","multiple":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'com.blockchain.blm:i
d/tab_mycenter' using 'ID' with the contextId: '' multiple: false
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[INSTANCE=0,
 RESOURCE_ID=com.blockchain.blm:id/tab_mycenter]
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Failed to locate element. Cle
aring Accessibility cache and retrying.
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'com.blockchain.blm:i
d/tab_mycenter' using 'ID' with the contextId: '' multiple: false
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[INSTANCE=0,
 RESOURCE_ID=com.blockchain.blm:id/tab_mycenter]
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":7
,"value":"No element found"}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [MJSONWP] Matched JSONWP error code 7 to NoSuchElementError
[HTTP] <-- POST /wd/hub/session/5cba9ca0-8b04-4aaf-a74f-455ac43840b4/element 500
 3083 ms - 164
[HTTP]
[Appium] Received SIGINT - shutting down
[Logcat] Logcat terminated with code 3221225786, signal null
[UiAutomator] UiAutomator exited unexpectedly with code 3221225786, signal null
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [AndroidDriver] Shutting down Android driver
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s
FA6BK0301264 shell am force-stop com.blockchain.blm'
[Appium] Closing session, cause was 'UiAUtomator shut down unexpectedly'
[Appium] Removing session 5cba9ca0-8b04-4aaf-a74f-455ac43840b4 from our master s
ession list
[debug] [ADB] Pressing the HOME button
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s
FA6BK0301264 shell input keyevent 3'
[AndroidBootstrap] Cannot shut down Android bootstrap; it has already shut down
[debug] [Logcat] Stopping logcat capture
[debug] [Logcat] Logcat already stopped
[debug] [ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s
FA6BK0301264 shell am force-stop io.appium.unlock'
[debug] [AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` cap
ability if wanted.'''

**Comment by mykola-mokhnach** [comment]
uiautomator1 is considered obsolete for Android6+. Closed as not an issue
