### ISSUE TITLE
When iPhone with the WDA in the LAN cause the scripts is so slow 

### ISSUE THREAD

**Issue by TedCobra** [appium/appium#10992]
## The problem

When iPhone with the WDA in the LAN cause the scripts is so slow 

## Environment

* Appium version: 1.8.1
* Desktop OS: macOS High Sierra(10.13.5)
* Node.js version: v10.5.0
* Mobile platform: iOS 11.0.1,11.0.3....,11.4
* Real device: iPhone 6, iPhone 6 Plus, iPhone 6s Plus, iPhone 7 Plus
* Scripts: Python 2.7

## Details

When iPhone with the WDA in the LAN,starting the animation will become very slow, with obvious stagnation and scripts is so slow.

## Appium logs

[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.azazie.ios","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1530676746717 (11:59:06 GMT+0800 (中國標準時間))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.azazie.ios","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1530676747839 (11:59:07 GMT+0800 (中國標準時間))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.azazie.ios","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1530676748954 (11:59:08 GMT+0800 (中國標準時間))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.azazie.ios","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1530676750072 (11:59:10 GMT+0800 (中國標準時間))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.azazie.ios","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"sessionId":"705A10EE-A149-48BF-A4C2-A1011E4FAF5D","capabilities":{"device":"iphone","browserName":"Azazie","sdkVersion":"11.0.1","CFBundleIdentifier":"com.azazie.ios"}},"sessionId":"705A10EE-A149-48BF-A4C2-A1011E4FAF5D","status":0}
[debug] [BaseDriver] Event 'wdaSessionStarted' logged at 1530676754219 (11:59:14 GMT+0800 (中國標準時間))
[debug] [BaseDriver] Event 'wdaStarted' logged at 1530676754219 (11:59:14 GMT+0800 (中國標準時間))
[XCUITest] Skipping setting of the initial display orientation. Set the "orientation" capability to either "LANDSCAPE" or "PORTRAIT", if this is an undesired behavior.
[debug] [BaseDriver] Event 'orientationSet' logged at 1530676754220 (11:59:14 GMT+0800 (中國標準時間))
[Appium] New XCUITestDriver session created successfully, session 5edd5d0b-fa9a-40b4-aba3-be691f8236dc added to master session list
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1530676754221 (11:59:14 GMT+0800 (中國標準時間))
[debug] [MJSONWP] Responding to client with driver.createSession() result: {"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"platformVersion":"11.0.1","deviceName":"iPhone","app":"/Users/azazie/Documents/Apps/mobile.ipa","platformName":"iOS","udid":"b4846ad187bf256be1657df7c7aca535cc6d4088"}
[HTTP] <-- POST /wd/hub/session 200 53223 ms - 437
[HTTP]
[HTTP] --> POST /wd/hub/session/5edd5d0b-fa9a-40b4-aba3-be691f8236dc/element
[HTTP] {"using":"accessibility id","sessionId":"5edd5d0b-fa9a-40b4-aba3-be691f8236dc","value":"SIGN UP"}
[debug] [W3C] Calling AppiumDriver.findElement() with args: ["accessibility id","SIGN UP","5edd5d0b-fa9a-40b4-aba3-be691f8236dc"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/705A10EE-A149-48BF-A4C2-A1011E4FAF5D/element] with body: {"using":"accessibility id","value":"SIGN UP"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"3A5B46A8-9748-4BF0-8C91-CA00BB755179"},"sessionId":"705A10EE-A149-48BF-A4C2-A1011E4FAF5D","status":0}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"3A5B46A8-9748-4BF0-8C91-CA00BB755179"}
[HTTP] <-- POST /wd/hub/session/5edd5d0b-fa9a-40b4-aba3-be691f8236dc/element 200 523 ms - 122
[HTTP]
[HTTP] --> POST /wd/hub/session/5edd5d0b-fa9a-40b4-aba3-be691f8236dc/element/3A5B46A8-9748-4BF0-8C91-CA00BB755179/click
[HTTP] {"sessionId":"5edd5d0b-fa9a-40b4-aba3-be691f8236dc","id":"3A5B46A8-9748-4BF0-8C91-CA00BB755179"}
[W3C] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/5edd5d0b-fa9a-40b4-aba3-be691f8236dc/element/3A5B46A8-9748-4BF0-8C91-CA00BB755179/click] to [POST http://localhost:8100/session/705A10EE-A149-48BF-A4C2-A1011E4FAF5D/element/3A5B46A8-9748-4BF0-8C91-CA00BB755179/click] with body: {"sessionId":"5edd5d0b-fa9a-40b4-aba3-be691f8236dc","id":"3A5B46A8-9748-4BF0-8C91-CA00BB755179"}
[debug] [JSONWP Proxy] Got response with status 200: {"status":0,"id":"3A5B46A8-9748-4BF0-8C91-CA00BB755179","value":"","sessionId":"705A10EE-A149-48BF-A4C2-A1011E4FAF5D"}
[JSONWP Proxy] Replacing sessionId 705A10EE-A149-48BF-A4C2-A1011E4FAF5D with 5edd5d0b-fa9a-40b4-aba3-be691f8236dc
[HTTP] <-- POST /wd/hub/session/5edd5d0b-fa9a-40b4-aba3-be691f8236dc/element/3A5B46A8-9748-4BF0-8C91-CA00BB755179/click 200 4474 ms - 118
[HTTP]
[HTTP] --> POST /wd/hub/session/5edd5d0b-fa9a-40b4-aba3-be691f8236dc/element
[HTTP] {"using":"accessibility id","sessionId":"5edd5d0b-fa9a-40b4-aba3-be691f8236dc","value":"Email"}
[debug] [W3C] Calling AppiumDriver.findElement() with args: ["accessibility id","Email","5edd5d0b-fa9a-40b4-aba3-be691f8236dc"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/705A10EE-A149-48BF-A4C2-A1011E4FAF5D/element] with body: {"using":"accessibility id","value":"Email"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"FFDA2C04-9FBE-47F6-BF50-08DDAA97D9DC"},"sessionId":"705A10EE-A149-48BF-A4C2-A1011E4FAF5D","status":0}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"FFDA2C04-9FBE-47F6-BF50-08DDAA97D9DC"}
[HTTP] <-- POST /wd/hub/session/5edd5d0b-fa9a-40b4-aba3-be691f8236dc/element 200 941 ms - 122
[HTTP]
[HTTP] --> POST /wd/hub/session/5edd5d0b-fa9a-40b4-aba3-be691f8236dc/element/FFDA2C04-9FBE-47F6-BF50-08DDAA97D9DC/value
[HTTP] {"text":"cliu@tetx.com","sessionId":"5edd5d0b-fa9a-40b4-aba3-be691f8236dc","id":"FFDA2C04-9FBE-47F6-BF50-08DDAA97D9DC","value":["c","l","i","u","@","t","e","t","x",".","c","o","m"]}
[debug] [W3C] Calling AppiumDriver.setValue() with args: [["c","l","i","u","@","t","e","t","x",".","c","o","m"],"FFDA2C04-9FBE-47F6-BF50-08DDAA97D9DC","5edd5d0b-fa9a-40b4-aba3-be691f8236dc"]
[debug] [XCUITest] Executing command 'setValue'
[debug] [JSONWP Proxy] Proxying [POST /element/FFDA2C04-9FBE-47F6-BF50-08DDAA97D9DC/value] to [POST http://localhost:8100/session/705A10EE-A149-48BF-A4C2-A1011E4FAF5D/element/FFDA2C04-9FBE-47F6-BF50-08DDAA97D9DC/value] with body: {"value":["c","l","i","u","@","t","e","t","x",".","c","o","m"]}
[debug] [JSONWP Proxy] Got response with status 200: {"status":0,"id":"FFDA2C04-9FBE-47F6-BF50-08DDAA97D9DC","value":"","sessionId":"705A10EE-A149-48BF-A4C2-A1011E4FAF5D"}
[debug] [MJSONWP] Responding to client with driver.setValue() result: null
[HTTP] <-- POST /wd/hub/session/5edd5d0b-fa9a-40b4-aba3-be691f8236dc/element/FFDA2C04-9FBE-47F6-BF50-08DDAA97D9DC/value 200 15009 ms - 76
[HTTP]
[debug] [XCUITest] Connection to WDA timed out
[debug] [iProxy] recv failed: Operation not permitted
[BaseDriver] Shutting down because we waited 60 seconds for a command
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [iOSLog] Stopping iOS log capture
[Appium] Closing session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
[Appium] Removing session 5edd5d0b-fa9a-40b4-aba3-be691f8236dc from our master session list

# WDA logs:
2018-07-04 11:59:10.114894+0800 WebDriverAgentRunner-Runner[2453:2618745] ServerURLHere->http://192.168.3.37:8100<-ServerURLHere
    t =     0.12s Open com.azazie.ios
    t =     0.12s     Launch com.azazie.ios
    t =     0.54s         Wait for accessibility to load
    t =     0.64s         Wait for com.azazie.ios to idle
    t =     3.71s Find the Application "com.azazie.ios" 0x1c00c6820
    t =     3.71s     Snapshot accessibility hierarchy for app with pid 2456
    t =     6.24s Find the Application "com.azazie.ios" 0x1c00c6820
    t =     6.24s     Snapshot accessibility hierarchy for app with pid 2456
    t =     6.46s Snapshot accessibility hierarchy for app with pid 2456
    t =     6.69s Find the "SIGN UP" Any
    t =     6.69s     Snapshot accessibility hierarchy for app with pid 2456
    t =     6.90s Find the "SIGN UP" Button
    t =     6.90s     Snapshot accessibility hierarchy for app with pid 2456
    t =     7.14s Snapshot accessibility hierarchy for app with pid 2456
    t =     7.26s Find the "SIGN UP" Button
    t =     7.26s     Snapshot accessibility hierarchy for app with pid 2456
    t =     7.52s Snapshot accessibility hierarchy for app with pid 2456
    t =     7.79s Find the "SIGN UP" Button
    t =     7.79s     Snapshot accessibility hierarchy for app with pid 2456
    t =     8.09s Snapshot accessibility hierarchy for app with pid 2456
    t =     8.10s Snapshot accessibility hierarchy for app with pid 2456
    t =     8.43s Find the "SIGN UP" Button
    t =     8.43s     Snapshot accessibility hierarchy for app with pid 2456
    t =     8.80s Snapshot accessibility hierarchy for app with pid 2456
    t =     8.91s Find the "SIGN UP" Button
    t =     8.91s     Snapshot accessibility hierarchy for app with pid 2456
    t =     9.29s Snapshot accessibility hierarchy for app with pid 2456
    t =     9.68s Find the "SIGN UP" Button
    t =     9.68s     Snapshot accessibility hierarchy for app with pid 2456
    t =    10.11s Snapshot accessibility hierarchy for app with pid 2456
    t =    10.12s Snapshot accessibility hierarchy for app with pid 2456
    t =    10.56s Find the "SIGN UP" Button
    t =    10.56s     Snapshot accessibility hierarchy for app with pid 2456
    t =    11.04s Snapshot accessibility hierarchy for app with pid 2456
    t =    13.21s Find the Application "com.azazie.ios" 0x1c00c6820
    t =    13.21s     Snapshot accessibility hierarchy for app with pid 2456
    t =    13.53s Snapshot accessibility hierarchy for app with pid 2456
    t =    14.11s Find the "Email" Any
    t =    14.11s     Snapshot accessibility hierarchy for app with pid 2456
    t =    14.67s Find the "Email" StaticText
    t =    14.67s     Snapshot accessibility hierarchy for app with pid 2456
    t =    15.25s Find the "Email" StaticText
    t =    15.25s     Snapshot accessibility hierarchy for app with pid 2456
    t =    15.87s Find the "Email" StaticText
    t =    15.87s     Snapshot accessibility hierarchy for app with pid 2456
    t =    16.50s Find the "Email" StaticText
    t =    16.51s     Snapshot accessibility hierarchy for app with pid 2456
    t =    17.16s Snapshot accessibility hierarchy for app with pid 2456
    t =    17.28s Find the "Email" StaticText
    t =    17.28s     Snapshot accessibility hierarchy for app with pid 2456
    t =    17.97s Snapshot accessibility hierarchy for app with pid 2456
    t =    18.81s Find the "Email" StaticText
    t =    18.81s     Snapshot accessibility hierarchy for app with pid 2456
    t =    19.57s Snapshot accessibility hierarchy for app with pid 2456
    t =    19.58s Snapshot accessibility hierarchy for app with pid 2456
    t =    20.33s Find the "Email" StaticText
    t =    20.33s     Snapshot accessibility hierarchy for app with pid 2456
    t =    21.10s Snapshot accessibility hierarchy for app with pid 2456
    t =    21.21s Find the "Email" StaticText
    t =    21.22s     Snapshot accessibility hierarchy for app with pid 2456
    t =    22.02s Snapshot accessibility hierarchy for app with pid 2456
    t =    22.84s Find the "Email" StaticText
    t =    22.84s     Snapshot accessibility hierarchy for app with pid 2456
    t =    23.71s Snapshot accessibility hierarchy for app with pid 2456
    t =    23.72s Snapshot accessibility hierarchy for app with pid 2456
    t =    24.60s Find the "Email" StaticText
    t =    24.60s     Snapshot accessibility hierarchy for app with pid 2456
    t =    25.51s Snapshot accessibility hierarchy for app with pid 2456
    t =    25.77s Find the Application "com.azazie.ios" 0x1c00c6820
    t =    25.77s     Snapshot accessibility hierarchy for app with pid 2456
    t =    26.24s Find the Application "com.azazie.ios" 0x1c00c6820
    t =    26.25s     Snapshot accessibility hierarchy for app with pid 2456
    t =    26.71s Snapshot accessibility hierarchy for app with pid 2456
    t =    26.72s Find the Application "com.azazie.ios" 0x1c00c6820
    t =    26.72s     Snapshot accessibility hierarchy for app with pid 2456
    t =    27.18s Snapshot accessibility hierarchy for app with pid 2456
    t =    27.29s Find the Application "com.azazie.ios" 0x1c00c6820
    t =    27.29s     Snapshot accessibility hierarchy for app with pid 2456
    t =    27.76s Find the Application "com.azazie.ios" 0x1c00c6820
    t =    27.76s     Snapshot accessibility hierarchy for app with pid 2456
    t =    28.25s Snapshot accessibility hierarchy for app with pid 2456
    t =    28.26s Find the Application "com.azazie.ios" 0x1c00c6820
    t =    28.26s     Snapshot accessibility hierarchy for app with pid 2456
    t =    28.76s Snapshot accessibility hierarchy for app with pid 2456

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/facebook/WebDriverAgent

Closed as third party issue.
