### ISSUE TITLE
unable to uninstall appium 1.7.2

### ISSUE THREAD

**Issue by moagarwa** [appium/appium#11000]
## The problem

unable to uninstall appium 1.7.2

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): 1.7.1
* Desktop OS/version used to run Appium: 10.13.5
* Node.js version (unless using Appium.app|exe): 5.0.3
* Mobile platform/version under test: NA
* Real device or emulator/simulator: NA
* Appium CLI or Appium.app|exe: NA

## Details
on performing npm uninstall -g appium
It gives the the removed 1 package in 0.045s

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by moagarwa** [comment]
<img width="603" alt="screen shot 2018-07-05 at 1 42 56 pm" src="https://user-images.githubusercontent.com/40819697/42310632-8acf9902-8059-11e8-87ab-d8d5c489ac25.png">

**Comment by moagarwa** [comment]
Please help

**Comment by moagarwa** [comment]
Any update on the issue

**Comment by vjmaiky** [comment]
you installed it as an admin?

**Comment by moagarwa** [comment]
I don't remember, but i tried the same command with sudo it showed the same output and still appium was not uninstalled

**Comment by vjmaiky** [comment]
maybe you have it installed on another account from mac? with no rights to uninstall it?

**Comment by moagarwa** [comment]
![image](https://user-images.githubusercontent.com/40819697/42559811-d01226f2-8512-11e8-857b-6501704c8c6e.png)

Please find the attached screenshot

**Comment by moagarwa** [comment]
should I uninstall npm and then try again after reinstalling it

**Comment by messianic** [comment]
Hey @moagarwa I think the main problem might be with your `node` installation. 
1. Completely remove the existing node installation(search on stack) and install it using brew. I would recommend node 8. 
2. Run the command `brew install node@8`.
3. Install appium `npm install -g appium`

P.S: npm comes bundled with your node installation.
