### ISSUE TITLE
 I am testing a web app on iOS 11.2 simulator and is using mobile gestures such as: self.driver.execute_script('mobile: tap', {'x': '100', 'y': '500'}. It is saying error socket hang up.

### ISSUE THREAD

**Issue by vytran9599** [appium/appium#11005]
I am using Appium beta 1.8.2.  The issue only happens when I use iOS 11+

**Comment by mykola-mokhnach** [comment]
Socket hang up error is generated when WebDriverAgent stops responding to Appium and there is nothing that can be done on our side to fix that. 

If you work with web views then try [switching to web context](http://appium.io/docs/en/writing-running-appium/web/hybrid/)
