### ISSUE TITLE
Is there a way to keep WebDriverAgent running on real device for Appium test?

### ISSUE THREAD

**Issue by vytran9599** [appium/appium#11003]
WebDriverAgent will remove itself after a period of time on my iPad when I am testing. Is there a way to keep it on the iPad permanently?

If so, preferably written in Python.

**Comment by vjmaiky** [comment]
define a period of time..if you use the capability for using new wda or to remove wda after test, ofc will be removed.

**Comment by vytran9599** [comment]
I am using 'usePrebuiltWDA' and it is still removing it.

**Comment by vjmaiky** [comment]
please pot server logs

**Comment by mykola-mokhnach** [comment]
WebDriverAgent does not remove itself, however appium may try to reinstall it only if WDA stops responding on session init. You may try to provide `webDriverAgentUrl` capability with appium@beta to prevent such behaviour, so WDA application will be kept untouched independently of its state.
