### ISSUE TITLE
Encountered internal error running command Error executing adbExec. Original error: 'Command '/Users/it/Library/Android/sdk/platform-tools/adb -P 5037 -s a8dbf256 shell am start -W -n tv.hooq.android/tv.hooq.androidbeta.views.activity.MainActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' exited with code 1'; Stderr: 'java.lang.SecurityException: Permission Denial: starting Intent

### ISSUE THREAD

**Issue by ivantay2003** [appium/appium#11004]
## The problem
I am not able to launch the android app and get error (see appium log) in device and emulator. 

-  Encountered internal error running command: Error: Cannot start the 'tv.hooq.android' application. Original error: Error executing adbExec. Original error: 'Command '/Users/it/Library/Android/sdk/platform-tools/adb -P 5037 -s a8dbf256 shell am start -W -n tv.hooq.android/tv.hooq.androidbeta.views.activity.MainActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' exited with code 1'; Stderr: 'java.lang.SecurityException: Permission Denial: starting Intent

I am using the appium 1.8.1

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 1.6.2
* Node.js version (unless using Appium.app|exe): v10.1.0
* Mobile platform/version under test: Android / 7.1
* Real device or emulator/simulator: Samsung J2 Pro
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
https://github.com/ivantay2003/hooqtv_log/blob/master/appium_log.rtf

## Code To Reproduce Issue [ Good To Have ]
Desired Caps
https://github.com/ivantay2003/hooqtv_log/blob/master/hooqtv.json

## Started from terminal
appium &

Can someone please help me? I repro this problem on emulator beside device

**Comment by mykola-mokhnach** [comment]
Most likely the activity name that you provide is not the main one and should be changed.

**Comment by ivantay2003** [comment]
Thanks for the reply. 

I launch the hooqtv app on the device , and then do a shell in 
dumpsys window windows | grep -E 'mCurrentFocus'

returns
mCurrentFocus=Window{5b3d149d0 u0 tv.hooq.android/tv.hooq.androidbeta.views.activity.MainActivity}

The activity is correct in the json file.

**Comment by imurchie** [comment]
The activity that eventually starts may be right, but it is not the one that should be launched.

Try running the command outside of Appium:
```
/Users/it/Library/Android/sdk/platform-tools/adb -P 5037 -s a8dbf256 shell am start -W -n tv.hooq.android/tv.hooq.androidbeta.views.activity.MainActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000
```

I would try removing the `appActivity` and `appPackage` desired capabilities and see what comes when Appium parses them from the app's manifest.

**Comment by ivantay2003** [comment]
Thanks @imurchie . It seem that adb produces the same error

Stopping: tv.hooq.android
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=tv.hooq.android/tv.hooq.androidbeta.views.activity.MainActivity launchParam=MultiScreenLaunchParams { mDisplayId=0 mBaseDisplayId=0 mFlags=0 } }
java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=tv.hooq.android/tv.hooq.androidbeta.views.activity.MainActivity launchParam=MultiScreenLaunchParams { mDisplayId=0 mBaseDisplayId=0 mFlags=0 } } from null (pid=13278, uid=2000) not exported from uid 10161
	at android.os.Parcel.readException(Parcel.java:1704)
	at android.os.Parcel.readException(Parcel.java:1654)
	at android.app.ActivityManagerProxy.startActivityAndWait(ActivityManagerNative.java:3716)
	at com.android.commands.am.Am.runStart(Am.java:658)
	at com.android.commands.am.Am.onRun(Am.java:392)
	at com.android.internal.os.BaseCommand.run(BaseCommand.java:51)
	at com.android.commands.am.Am.main(Am.java:125)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:315)


Will see if i can dig more from here. thanks

**Comment by mykola-mokhnach** [comment]
I don't think this problem has anything to do with appium. It is just necessary to pass correct capabilities.
