### ISSUE TITLE
Unable to click on elements after changing view - IONIC app

### ISSUE THREAD

**Issue by mjevtovic** [appium/appium#11006]
## The problem

I am unable to click on elements which appear on different views. It seems like appium doesn't load them. Probably this is related to Ionic app I am using

## Environment

* Appium version 1.6.2 UI, 1.8.1 Server
* Desktop OS/version used to run Appium: macOS High Sierra 10.13.5
* Mobile platform/version under test: Android / 6.0
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Appium.app

## Details

There are 3 views in my app if i inspect elements on 1st view I would be able to click on elements if I click on 2nd view I won't be able to click elements from that view because elements from 1st view are visible to appium and not new elements on the 2nd view.

## Link to Appium logs

https://gist.github.com/mjevtovic/668f8164733ecb62dd1173b7a3bd72a6

## Code To Reproduce Issue [ Good To Have ]

Here is the link of reproduced issue with appium inspector. Same thing happens if I use java code to create test or use ruby console with 'arc' to inspect elements and interact with them.
https://youtu.be/FQFNRJOPPdE

P.S I can share my sample app, just let me know what's the best way to do it.

Thanks!

**Comment by mykola-mokhnach** [comment]
Closed as inactive. You are always welcome to commit a PR if you know what should be changed in order to resolve the problem.
