### ISSUE TITLE
Is there a way I can get a screenshot of particular dimension like 100 X 100

### ISSUE THREAD

**Issue by moagarwa** [appium/appium#11001]
## The problem

Is there a way I can get a screenshot of particular dimension like 100 X 100

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: 10.13.5
* Node.js version (unless using Appium.app|exe):5.0.3
* Mobile platform/version under test: 10.3.3
* Real device or emulator/simulator: NA
* Appium CLI or Appium.app|exe: NA

## Details

I am doing screenshot comparison and to validate it I have to take screenshot on each of my mobile devices as size differs on each device.
It will be really helpful if somehow I can get screenshot of particular dimension

## Code To Reproduce Issue [ Good To Have ]
File a = ((TakeScreenshot) driver).getScreenshotAs(OutputType.FILE);

**Comment by mykola-mokhnach** [comment]
No, Selenium API does not provide such features.
