### ISSUE TITLE
move_to not work with relative coordinates and not work press in TouchAction with move_to

### ISSUE THREAD

**Issue by romansvesh** [appium/appium#11010]
## The problem

After update from 1.7.2 to 1.8.1 I want to work with TouchAction for slide. It's worked in 1.7.2 (see code to reproduce) and I thought to add small fix with relative coordinates in move_to. But move_to not use relative coordinates. After that I try to use long_press instead of press and it's work fine (but like in 1.7.2 with absolute coordinates). But why it's not work with press?

After all:
- In documentation for python usage of move_to (https://appium.io/docs/en/commands/interactions/touch/move/) uses "tap_and_hold" with TouchAction. But "tap_and_hold" in TouchActions only. And its not work anyway.

## Environment

Appi

* um version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2
* Desktop OS/version used to run Appium: macOS 10.13.5
* Node.js version (unless using Appium.app|exe): 10.6.0
* Mobile platform/version under test: IOS 10.3.1
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: cli 
* Appum client: Appium-Python-Client 0.26

## Details

move_to don't work with relative coordinates (TouchAction).
Code from below only will work like tap(x=300, y=300).
But if use long_press instead of press code work as in 1.7.2 with absolute coordinates for move_to. It's strange.

## Link to Appium logs

press:
https://gist.github.com/romansvesh/0fa440501319455467f41db780aad13e

long_press:
https://gist.github.com/romansvesh/df57affc2ceb6b7ea01e114d185dba70

## Code To Reproduce Issue [ Good To Have ]

```
action = TouchAction(self.driver)
action.press(x=187, y=333)
action.move_to(x=300, y=300)
action.release().perform()
```

**Comment by mykola-mokhnach** [comment]
Because you must add wait action after press (not less than 500 ms). This is by design.

**Comment by mykola-mokhnach** [comment]
Regarding coordinates - they are absolute in the original spec and the fact they were relative in previous versions means there was a bug, which is fixed now.
