### ISSUE TITLE
[Android] Error when running appium on a remote machine and sharing app file through network

### ISSUE THREAD

**Issue by oscheller1** [appium/appium#11012]
Using two machines to run automated tests:  
- PC: Bamboo agent 
- MAC: Appium server with connected devices

Downloading the apk file on the PC, sharing folder to the network. MAC mounts the network drive to access the apk file, e.g. `/Volumes/shared/app.apk`. MAC has full rights to modify the apk file. This setup works for iOS tests (using an ipa file just fine. On Android though, i'm getting the following error:
```
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: packageAndLaunchActivityFromManifest failed. Original error: Could not find aapt Please set the ANDROID_HOME environment variable with the Android SDK root directory path.
```

`ANDROID_HOME` is set on the MAC. 
```
$ echo $ANDROID_HOME
/Users/user/Library/Android/sdk
```

**Comment by mykola-mokhnach** [comment]
Such error means that appium process does not see this particular variable in its environment. Most likely this is an issue with you CI setup. Check https://github.com/appium/java-client/blob/master/docs/environment.md for more details

**Comment by oscheller1** [comment]
I think I missed the right SDK version. I installed it now and am getting a new error:
```
[ADB] Using the alternative activity name detection method because of: Could not find apkanalyzer in /Users/user/platform-tools/apkanalyzer,/Users/user/emulator/apkanalyzer,/Users/user/tools/apkanalyzer,/Users/user/tools/bin/apkanalyzer. Do you have the Android SDK installed at ''?
```
Somehow adb looks inside the HOME folder instead of the ANDROID_HOME folder for apkanalyzer?

**Comment by mykola-mokhnach** [comment]
CI agent may create its own environment, which is not the same as the system one. Also make sure you restart the server after the environment is changed.

**Comment by oscheller1** [comment]
Problem seemed to be a mix of starting appium with sudo (which seems to cause problems) and network drive getting disconnected during execution. 

Fixed
