### ISSUE TITLE
Appium is clearing the app data and cache everytime I open the app

### ISSUE THREAD

**Issue by sujitpathak** [appium/appium#11011]
## The problem
I have a Login application, I logged in and now I want to test the app after invoking and app starts with Home screen.

I set the flag :- 
cap.setCapability("no-reset", true);
cap.setCapability("full-reset", false);

OR

cap.setCapability("no-reset", "true");
cap.setCapability("full-reset", "false");

## Environment
I am using 
Appium: 1.7.2
Android Real Devices

**Comment by mykola-mokhnach** [comment]
Please update to the recent Appium version (1.8.1) and attach the full server log

**Comment by sujitpathak** [comment]
Yeah , it worked with below code

DesiredCapabilities cap = new DesiredCapabilities();
cap.setCapability("noReset", "true");
cap.setCapability("fullReset", "false");
