### ISSUE TITLE
Proposal for near-real-time image element interaction

### ISSUE THREAD

**Issue by jlipps** [appium/appium#11021]
### Context

I've been working on some projects recently that highlight the power of the new image matching functionality in Appium. I think we can take this to the next level through a series of improvements. I wanted to lay out the proposal here before beginning work since it would be several different pieces and a fair amount of code.

Basically, the goal is very quick recognition and interaction with screen positions based on image matching. The pieces for this are already present in Appium, but they are too slow. The process right now looks like:

1. Take a screenshot (costs a client-server roundtrip, and whatever time Appium's screenshot dumping methods take)
2. Send the screenshot together with a reference image template back to the Appium server, to get match details like x/y coordinates (costs a client-server roundtrip, and whatever time Appium's opencv matching methods take)
3. Tap the screen based on the coordinates received (costs a client-server roundtrip, and whatever time Appium's tap methods take)

All of these steps take so much time that matching and interacting with image areas on screen will not be reliable unless the screen is completely static. I think we can open up greater reliability and the possibility of completely new applications (for example, game testing) with a faster process. Looking at the current process, there are a number of potential areas for speedup:

1. 3 client-server roundtrips over HTTP (potentially in high-latency contexts like cloud testing)
2. Screenshot time
3. OpenCV matching time
4. Tap screen time

I'm going to ignore (3) and (4) above since I don't see any easy way to improve them. (2) is already being addressed by https://github.com/appium/appium-support/pull/75 and related PRs, for those who have access to an mjpeg screenshot stream (currently thinking about how to make this technology available via Appium for all users as well).

That leaves the 3 client-server roundtrips as the primary bottleneck, which is a big bottleneck indeed when running in a cloud environment. I think we can eliminate all of them.

#### 1. Find Element By Image

I have already implemented (in the Python and WD.js clients), an element-like interface for image template matches. In my opinion, this is the most natural and useful way of using Appium's image matching feature. From the perspective of the user, they supply an image template to a "findElementByImage" command, and they get back an element object in their script, just as if they had tried to find an element by xpath or anything else. The only difference is that the element object is of a different class (`ImageElement`, say), and has only a subset of `WebElement`'s methods--`click`, `getSize`, `getLocation`, `getRect`, and `isVisible`.

Right now this logic is being duplicated in each client. Instead, I propose to move this logic to the Appium server, specifically in BaseDriver. Basically, from the client perspective, we would have simply a new locator strategy (`-image`), and the selector passed in would be the base64-encoded template image (with one wrinkle; see below). The response from the server would be the same JSON response as for a `WebElement`, and from the client perspective, it can be wrapped up into a `WebElement` object.

To support this, the server side would be implemented as follows:

1. New code added to BaseDriver to trap calls to `find` and check if the strategy is `-image`
2. If so, screenshot retrieved and image matching methods called immediately
3. In case of a match, a unique image element ID is created and stored in a hash together with the match position location
4. In case of no match, `NoSuchElementException` returned
5. When the client calls an element method using an image element ID, the server would check for this situation in `execute` before passing control onto the command methods. If we're operating on an image element, we check that the command is in the list of available image element commands.
6. If so, we perform the action (tap etc...) in BaseDriver itself
7. If not, we return `NotImplementedException`

This procedure solves two main problems:

1. Eliminates one of the server-client roundtrips (now no need to get screenshot and do the image match separately---the server does them both in the same request)
2. Reduces the amount of work required to support this feature (it's in the server in one place, rather than requiring many client implementations).

The wrinkle in this proposal so far is that matching image templates doesn't just require the image to be matched--it also takes a threshold parameter, a match below which would be rejected. We could simply set this at a default value and hope it's good enough for all users. Better would be to have a default value but allow users to set the match threshold in their client code, for example:

```js
driver.elementByImage(b64Data, 0.5);
```

The problem here is that the find element commands take a strategy and a selector, but we want a third parameter. Rather than adjust the API, I would propose to encode the threshold in the selector itself, something like this:

```js
// before the client sends the selector to the server
let selector = `threshold=0.5|${b64Data}`;
```

In other words, add a bit of preamble to the base 64 string which is easy to parse and strip out.

#### 2. Stale Image Elements

One problem with image matching and tapping via coordinate in general is that there's no guarantee the coordinates of a matched image on the screen still represent the correct underlying element---who's to say it didn't change in between the time we get an element and act on it?

The solution to this is to re-match the template and assert that the coordinates are the same, before attempting to do an action. I.e., if a user calls `imageElement.click()` in their client code, then the server would re-match the image template and assert that its coordinates match the previously-retrieved coordinates for that image element, before performing the tap. If there's no match or the coordinates differ, a `StaleElementException` is returned instead.

How does the server know how to re-match the image template? Well, the base64 image template data string would have to be stored as part of the image element hash. Since image data can get large, we would probably want to have some sort of ejection policy for the hash, maybe making it an LRU cache bounded by total memory usage or something.

This also points out a nagging issue, not just with finding and acting on image elements, but finding and acting on _any_ element: the chance that, between the time an element is found and the time it is interacted with, the situation in the app might have changed. This is what `StaleElementExceptions` are designed to notify us about. But what if we could greatly reduce the chance of such an exception, and speed up our tests in the process? We can!

#### 3. findAndAct

I propose we bring back a feature we had in the old bad days of Apple's UIAutomation driver, when we ran into this problem very frequently of elements being invalidated and unavailable for actions, just in the time it took for a client-server roundtrip. The primary motivation here is to help with extremely low-latency test applications (dynamic image matching), but the benefit extends to interacting with elements as a whole.

Basically, we add a new endpoint which encapsulates both finding and acting. It would take a strategy, selector, command name, and any command parameters. As a first pass, it could look like:

```
# endpoint
POST /session/:sessionid/appium/find_and_act

# request JSON
{
  "using": "xpath",
  "value": "//foo/bar",
  "command": "sendKeys",
  "params": {
    "text": "hello world"
  }
}

# response is the response for the action--no element is returned
# however, if an element is not found, NoSuchElementException
# would be returned
```

Since we want to act immediately on a found element, this only makes sense in the singular (no findElements support is necessary).

Putting all of these changes together, we have the potential for an extremely fast and reliable way of interacting with apps based on image matching, with side benefits for speeding up tests in other regards as well. We can reduce finding and tapping on a matched image to one client-server roundtrip, with the least possible chance of any slippage of app state (between finding a matched image coordinate set and tapping on it there is only the time that the tap itself takes, which should be in low ms).

I'd be happy to implement this proposal, but because it's pretty large and cross-cutting I wanted to get conceptual buy-in from the other maintainers first and solicit other ideas or any issues you see with it.

**Comment by dpgraham** [comment]
A few comments:

* The `find-and-act` should be implemented in `appium-base-driver` so that we don't have to implement it on WebDriverAgent, UiAutomator2Server, etc...
* Perhaps we can actually support doing multiple actions
* We'll probably want to implement this fully on the clients; I think it should be similar to how we do touchActions

```java
(new FindAndAct(driver))
  .findElement(By.XPATH, "//some/xpath")
  .sendKeys("hello world")
  .perform();
```

**Comment by mykola-mokhnach** [comment]
- Regarding p1. The idea is good. Several things I'd like to pay attention to: it might be hard to properly implement a wrapper on such locater in statically typed languages, like Java or C#; the lookup configuration should be more flexible. I'd rather add a special structure for it into `/settings` endpoint.

- Regarding p2 and p3. Yes, the stale element exception and overhead is a pain in mobile automation in general. The proposed approach look quite limited to me. I'd rather generify it, so it could be possible to create promises chain consisting of any element operations, not only find and click.

**Comment by mykola-mokhnach** [comment]
I was thinking about the endpoint, which looks like:

```
POST 
/appium/performChain
{[
  {
    method: 'POST',
    command: 'findElement',
    arguments: ['id', 'elementId'],
  },
  {
    method: 'GET',
    command: 'getValue',
    arguments: [],
  },
  {
    method: 'POST',
    command: 'setValue',
    arguments: ['$!AndMore'],
  },
]}
```

from client perspective.

`$!` there is the result of the recent chain item invocation and is replaced automatically as soon as the item has been successfully executed and returned a result. In more advanced scenarios, one could just mimic the same string templates approach there as used in BASH scripting. 

On the client side such chains could be represented as promises/futures, which are only getting fulfilled (or rejected) after `applyCommands()` method is called on an element, for example:

```java
LazyWebElement lazyEdit = driver.findElement(By.LazyId('elementId'));
CompletableFuture<String> text = lazyEdit.getValue();
lazyEdit.setValue("$!AndMore");
lazyEdit.applyCommands();
```

**Comment by jlipps** [comment]
@mykola-mokhnach:

> Regarding p1. The idea is good. Several things I'd like to pay attention to: it might be hard to properly implement a wrapper on such locator in statically typed languages, like Java or C#; also the lookup configuration should be more flexible. I'd rather add a special structure for it into /settings endpoint.

I'm not clear on what you mean. Are you saying the additional threshold parameter would be hard to shoehorn into the find element client apis? And so we should set it via an `imageMatchThreshold` setting or capability? That's a good idea, I'd be in favor of that.

> The proposed approach look quite limited to me. I'd rather generify it, so it could be possible to create promises chain consisting of any element operations, not only find and click.

My proposal is supposed to be generic, allowing any kind of Appium command that operates on an element.

> On the client side such chains could be represented as promises/futures, which are only getting fulfilled (or rejected) after applyCommands() method is called on an element

This is a really cool idea. One potential issue is that the client interface looks exactly like using the driver and element objects, so users would expect to be able to do _anything_. In principle they could, but it would mean creating an API which could encode arbitrary Appium commands. How much work would this be for the clients?

I also like your idea of using responses from previous commands in future commands. Something like regex backreferences might be more generic than `$!`. I could see another common use case being tapping by coordinates (find an element, get its location, and tap coordinates based on that location)

Another thought on the API. What if the client just sent in the URL for the command in each command step? Clients already know the URLs for each command and how to put them together. Clients also already know how to form JSON request bodies. So your example would be modified as follows (with a random idea for the backreferences and a magic `{{<element}}` backreference, referring to the most recently-found element):

```
POST /appium/perform_chain
{actions: [
  {
    method: 'POST',
    endpoint: '/element',
    request: {
      strategy: 'id',
      using: 'elementId'
    }
  },
  {
    method: 'GET',
    command: '/element/{{<element}}/text',
    request: {}
  },
  {
    method: 'POST',
    command: '/element/{element}/value',
    request: {text: '{{<1}}'}
  }
]}
```

The response would be an array, each element in the array corresponding to the same element in the request:

```
{actions: [
  {
    response: {element-1234-1234-1234: 'asdf-asdf-asdf-asdf'},
    meta: {actionStart: 10123401234, actionEnd: 10123401254}
  }, {
    response: 'some text',
    meta: {actionStart: 10123401255, actionEnd: 10123401274}
  }, {
    response: null,
    meta: {actionStart: 10123401276, actionEnd: 10123401294}
  }
]}
```

Notice we also include timing information since once we take this out of the client it becomes impossible to distinguish the timing of individual commands in a chain, which is essential for performance-based testing. We could also figure out how to return errors as part of this, including chain commands which didn't get run because a command earlier in the chain errored out.

One other advantage of the request format above is we could probably make sense of the Appium router in some way and reduce the overall amount of code that needs to be written on both client and server.

@dpgraham good ideas as well, I agree. I'm definitely open to mirroring the client-side API after the touch action chain API. Clients could provide multiple ways to access this, including @mykola-mokhnach's future/promise-based idea. Doesn't really matter from the server side.

Here's another stab at what the client could look like (also trying on "batch" verbiage instead of "chain", but I don't really care one way or another):

```js
let batch = new BatchedCommands();
batch.elementByAccessibilityId('foo');
batch.lastElement.text();  // lastElement is converted to {{<element}}
batch.lastElement.sendKeys(`${batch.lastResult}...and more!`); // lastResult is converted to {{<1}}
let res = await batch.perform();

// different ways to get data out
let [el, text,] = res.values;
let [elMeta, textMeta,] = res.metas;
let [[el, elMeta], [text, textMeta],] = res.all;
// el is a WebElement, elMeta has timings
// text is a string, textMeta has timings
```

Thoughts?

**Comment by mykola-mokhnach** [comment]
> I'm not clear on what you mean. Are you saying the additional threshold parameter would be hard to shoehorn into the find element client apis? And so we should set it via an imageMatchThreshold setting or capability? That's a good idea, I'd be in favor of that.

Request example:

```
POST
/appium/settings

{
  batchOptions: {
    matchThreshold: 0.5,
    .... // other options than might be useful in the future
  }
...
{
```

**Comment by mykola-mokhnach** [comment]
Batch entity would be more appropriate. +1 to that

**Comment by jlipps** [comment]
By the way, if you're all cool with P1 (image element finding on the server side), I can start implementing that while we debate the whole batched commands proposal.

**Comment by jlipps** [comment]
OK, find by image work is now underway: https://github.com/appium/appium-base-driver/pull/235

**Comment by jlipps** [comment]
@mykola-mokhnach @dpgraham @imurchie any more thoughts on the concrete batch actions proposal (https://github.com/appium/appium/issues/11021#issuecomment-404769888)? since it's a pretty sizable and totally new API i'd love to make sure we're all on board. @KazuCocoa  @vmaxim and anyone else please also chime in!

**Comment by KazuCocoa** [comment]
For me, https://github.com/appium/appium/issues/11021#issuecomment-404769888 way looks good.

Sometimes, I heard some game companies in Japan customise similar thing by themselves, I remembered. They'd like to reduce delays by HTTP communication between server and clients. Thus, like the chaining request is pretty good 👍

**Comment by dpgraham** [comment]
@jlipps has there been any movement on the Batched Commands feature?

**Comment by dpgraham** [comment]
Based on conversations with my Sauce colleagues and with open source users, I think there is a huge desire for the method batching feature. This would help the performance of Appium Desktop quite significantly and we have customers who have problems with delays between commands.

Shall we pull this into our next sprint?

**Comment by imurchie** [comment]
I would like to, yes.

**Comment by jlipps** [comment]
Sorry I missed these comments. I think work on the batched command is highly appropriate. I can probably help out with this soon too.

**Comment by jlipps** [comment]
I spent some time working on the batch commands problem this weekend, and might have something to show soon. It's kind of a different idea, will see what you think of the PR :-)

**Comment by imurchie** [comment]
I look forward to seeing it!

**Comment by mykola-mokhnach** [comment]
Closed as fixed
