### ISSUE TITLE
SendKeys command not working with elements in class "TextInputLayout", for android 6.0.1 and 7.0

### ISSUE THREAD

**Issue by kcchaitanya** [appium/appium#11026]
No such element found is returned in response when tried to use "Sendkeys" command against any TextInputLayout field in android 6.0.1 and 7.0 firmware versions.

Response error message:

"[MJSONWP] Matched JSONWP error code 7 to NoSuchElementError

## Environment

* Appium version - 1.8.1
* Desktop OS/version used to run Appium: Mac High Sierra (10.13.1)
* Mobile platform/version under test: Android 6.0.1 and Android 7.0
* Real device or emulator/simulator: Nexus and Samsung S6

Automation Snippet: 
"
    public static void EnterFirstName() throws InterruptedException {
        MobileElement EnterFirstName = driver.findElementByName(By.xpath("TextInputLayout[@text = 'First Name']");
        System.out.println("Element is displayed:" + EnterFirstName);
        EnterFirstName.sendKeys("hello");
        System.out.println("Entered FirstName Successfully");
        Thread.sleep(1000);

    }
"

Appium Logs:

[HTTP] {"using":"xpath","value":"TextInputLayout[@text = 'First Name']"}
[W3C] Calling AppiumDriver.findElement() with args: ["xpath","TextInputLayout[@text = 'First Name']","c527efb6-7b25-4804-9194-4b36f827f9d6"]
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Waiting up to 0 ms for condition
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"TextInputLayout[@text = 'First Name']","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"TextInputLayout[@text = 'First Name']","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'TextInputLayout[@text = 'First Name']' using 'XPATH' with the contextId: '' multiple: false
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Failed to locate element. Clearing Accessibility cache and retrying.
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'TextInputLayout[@text = 'First Name']' using 'XPATH' with the contextId: '' multiple: false
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":7,"value":"No element found"}
[AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Matched JSONWP error code 7 to NoSuchElementError
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"source","params":{}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"source","params":{}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: source
[AndroidBootstrap] [UIAUTO STDOUT] [APPIUM-UIAUTO] [debug] Returning result: {"status":0,"value":"<\/android.view.ViewGroup>
[AndroidBootstrap] Received command result from bootstrap
[AndroidBootstrap] Stream still not complete, waiting up to 60000ms for the data to arrive
[AndroidBootstrap] [UIAUTO STDOUT] rkruit:id\/\" instance=\"3\"><\/android.widget.FrameLayout><\/TextInputLayout><\/android.widget.FrameLayout><\/TextInputLayout><\/android.widget.FrameLayout><\/TextInputLayout><\/android.widget.FrameLayout><\/TextInputLayout><\/android.widget.LinearLayout><\/android.widget.ScrollView><\/android.widget.LinearLayout><\/android.widget.LinearLayout><\/android.widget.FrameLayout><\/android.widget.LinearLayout><\/android.widget.FrameLayout><\/android.widget.LinearLayout><\/android.widget.FrameLayout><\/hierarchy>"}[/APPIUM-UIAUTO]
[AndroidBootstrap] Received command result from bootstrap
[BaseDriver] Error finding element: An element could not be located on the page using the given search parameters.
[BaseDriver] Page source requested through 'printPageSourceOnFindFailure':
[BaseDriver] 

ScreenShot:
<img width="799" alt="screen shot 2018-07-10 at 10 29 51 pm" src="https://user-images.githubusercontent.com/16398128/42551382-907934e0-84f4-11e8-9dee-a910f7f7feda.png">

**Comment by mykola-mokhnach** [comment]
- Switch to UIAutomator2
- Make sure the destination element is present in page source before executing the action

**Comment by messianic** [comment]
Also, use the locator strategy below:
`driver.findElementByAndroidUIAutomator("new UiSelector().text(\"First Name\")").sendKeys("xyz");`

**Comment by kcchaitanya** [comment]
@mykola-mokhnach 
I tried using UIAutomator2, but the result didn't change.

**Comment by kcchaitanya** [comment]
@messianic  Thanks a lot for the response. Using your method to find the locator helped.
