### ISSUE TITLE
android video recording

### ISSUE THREAD

**Issue by WildOrangutan** [appium/appium#11024]
## The problem

Android emulators are starting to support video recording with "adb". Would it be possible to add video recording support to Appium?

## Details

https://developer.android.com/studio/releases/emulator#screen_recording

**Comment by KazuCocoa** [comment]
Do you mean below?

- https://github.com/search?q=org%3Aappium+start_recording_screen&type=Code
- https://github.com/search?q=org%3Aappium+startRecordingScreen&type=Code

**Comment by WildOrangutan** [comment]
Yes, seems like it missed this feature. Sorry about that.
