### ISSUE TITLE
Could not set driver.setSetting(Setting.WAIT_FOR_IDLE_TIMEOUT, time)

### ISSUE THREAD

**Issue by Dan2712** [appium/appium#11028]
## The problem
   I just wanna set the wait for idle time by call driver.setSetting(Setting.WAIT_FOR_IDLE_TIMEOUT, time). But it returns a 500 error and says: "UnsupportedSettingException: Setting 'setWaitForIdleTimeout' is not supported".

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows
* Node.js version (unless using Appium.app|exe): 6.1.0
* Mobile platform/version under test: Android 7.1.2
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Link to Appium logs
https://gist.github.com/Dan2712/bfbef6d2e172df78628fd1d87c129b75

## Code To Reproduce Issue [ Good To Have ]
driver.setSetting(Setting.WAIT_FOR_IDLE_TIMEOUT, Duration.ofSeconds(1))
driver.setSetting(Setting.WAIT_FOR_IDLE_TIMEOUT, 1)

**Comment by mykola-mokhnach** [comment]
This functionality is currently not supported by UIA2 driver, but I think it could be added.

**Comment by mykola-mokhnach** [comment]
There is no workaround except of modifying the source code of UIA2 server

**Comment by Dan2712** [comment]
Could u pls tell the exact the file path that need to modify. I wanna have a try. Many thx!

**Comment by mykola-mokhnach** [comment]
Actually, try appium@beta first. This functionality might be already available there.

**Comment by Dan2712** [comment]
Still got this error: Matched JSONWP error code 13 to UnknownError.
appium version is 1.8.2beta

**Comment by mykola-mokhnach** [comment]
Attach the full log please

**Comment by Dan2712** [comment]
This time the log only show few info, no more details. 
https://gist.github.com/7917bc80cb0824168b84d2e28ccf4246.git

**Comment by mykola-mokhnach** [comment]
> [debug] [JSONWP Proxy] Proxying [POST /appium/settings] to [POST http://localhost:8200/wd/hub/session/335a189b-1c57-4cf4-8639-03fe479ab32b/appium/settings] with body: {"settings":{"setWaitForIdleTimeout":{"zero":false,"negative":false,"seconds":0,"nano":100000000,"units":["Seconds","Nanos"],"hCode":805032704,"class":"java.time.Duration"}}}

I don't think the server expects such kind of object there, but rather just a simple value

**Comment by Dan2712** [comment]
I also tried a simple int value, but got the same. The log is just attached below that one

**Comment by mykola-mokhnach** [comment]
Are there any errors in the logcat output?

**Comment by Dan2712** [comment]
No other errors. And I also upload the full log.https://gist.github.com/0e71b826d2339b2cb3eababb2249bd6f.git
And really thx for so much help

**Comment by mykola-mokhnach** [comment]
> [debug] [MJSONWP] Responding to client with driver.getLog() result: [{"timestamp":1531381358580,"level":"ALL","message":"--------- beginning of system"},{"timestamp":1531381358594,"level":"ALL","message":"01-18 08:50:05.630   222   222 I vold    : Vold 3.0 (the awakening) firing up"},{"timestamp":1531381358594,"level":"ALL","message":"01-18 08:50:05.630   222   222 V vold    :
> Detected support for: ext4 f2fs vfat"},{"timestamp":1531381358594,"level":"ALL","message":"01-18 08:50:05.640   222   222 D Vold    : Vendor path: /sys/bus/usb/devices/1-1/idVendor"},{"timestamp":1531381358594,"level":"ALL","message":"01-18 08:50:05.640   222   222 D Vold    : === config_file is: 65646f6d_7520230a"},{"timestamp":1531381358594,"level":"ALL","message":"01-18 08:5
> 0:05.671   222   228 D vold    : e4crypt_init_user0"},{"timestamp":1531381358594,"level":"ALL","message":"01-18 08:50:05.671   222   228 D vold    : e4crypt_prepare_user_storage for volume null, user 0, serial 0, flags 1"},{"timestamp":1531381358594,"level":"ALL","message":"01-18 08:50:05.671   222   228 D vold    : Preparing: ...

This is not enough. Check the complete output for possible stack traces or exceptions
