### ISSUE TITLE
Unable to click and hold the object in Appium 

### ISSUE THREAD

**Issue by QA2Dev** [appium/appium#11023]
## The problem

I want to handle a slider object which will retract itself, once we move slider to top and release.

Unable to click and hold the slider object in Appium as I want to take screenshot before releasing the slider

Issue exists on iOS Devices

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Desktop OS/version used to run Appium: MAC 10.13.5
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Details

I have to automate a slider object, which will come back to it's default position itself once we move the slider bar to top and release.

My challenge : I want to move the slider object to top using touch action and take a screen shot then release the slider object.

I'm unable to take screenshot as Slider is moving back to default position as soon as object is released.

Sample expected Code:

ta.longPress(srcx, srcy).moveTo(trgtx, trgty).perform(); -> which also releases the object
getScreenshot()
ta.release()

## Code To Reproduce Issue [ Good To Have ]
TouchAction ta = new TouchAction(this.driver);
System.out.println("Performing the Drag and drop operation (" + srcx + "," + srcy + "), (" + trgtx + "," + trgty + ")");
ta.longPress(srcx, srcy).moveTo(trgtx, trgty).perform();

**Comment by mykola-mokhnach** [comment]
It is not possible to do it with XCTest, since it requires all accessibility actions to be performed on main thread only.

**Comment by QA2Dev** [comment]
@mykola-mokhnach Thank you for information, by the way may I know what are the other accessibility actions ?.
