### ISSUE TITLE
error observed while trying to run recorded test case in katlan studio 

### ISSUE THREAD

**Issue by atom118** [appium/appium#11034]
## The problem

Recorded test case in Katlon Studio , while trying to run on local android device following error getting observed "Root cause: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unable to uninstall APK. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\Home\\.katalon\\tools\\android_sdk\\platform-tools\\adb.exe -P 5037 -s OBPZ45WWWSORMZRW uninstall com.android.contacts' exited with code 1'; Stderr: ''; Code: '1' (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 39.02 seconds"

**Comment by mykola-mokhnach** [comment]
You cannot uninstall built-in system apps without having root permissions, so the returned error is expected. Also, I'd recommend to contact the vendor's support if you use their product.

Closed as not an issue
