### ISSUE TITLE
Command double_tap provokes "An unknown server-side error occurred while processing the command"

### ISSUE THREAD

**Issue by fabiohsl** [appium/appium#11035]
## The problem

The application where I am running auto-test double tap perform "zooming" then using the given command found in the appium documentation, I am getting the given error shown within this issue. Am I missing something? It looks like an issue.

## Environment

* Appium version (or git revision) that exhibits the issue: Versione 1.6.2 (1.6.2)
* Desktop OS/version used to run Appium: Mac High Sierra
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real device

## Details

When I run 

`Appium::TouchAction.new.double_tap(x:0.5, y:0.5).perform`

I get an error shown below: 

" Selenium::WebDriver::Error::UnknownError: An unknown server-side error occurred while processing the command. Original error: unknown action doubleTap"

## Code To Reproduce Issue [ Good To Have ]

`Appium::TouchAction.new.double_tap(x:0.5, y:0.5).perform`

**or**

`2.times {Appium::TouchAction.new.tap(x:0.5, y:0.5).perform}`

Aren't working. Within the second option I use to get double tap but then isn't reproducing the same as we have when you do the same manually.

**Comment by mykola-mokhnach** [comment]
Please attach the full server log. Also, `tap` has a `count` argument, which might be useful.

**Comment by fabiohsl** [comment]
for the given command 2.times { Appium::TouchAction.new.tap(x:0.5, y:0.5).perform }

[HTTP] --> POST /wd/hub/session/a06a68b3-53d9-40bf-96ea-6db90353984c/touch/perform
[HTTP] {"actions":[{"action":"tap","options":{"x":0.5,"y":0.5,"count":1}}]}
[W3C] Calling AppiumDriver.performTouch() with args: [[{"action":"tap","options":{"x":0.5,"y":0.5,"count":1}}],"a06a68b3-53d9-40bf-96ea-6db90353984c"]
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"click","params":{"x":0.5,"y":0.5}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"click","params":{"x":0.5,"y":0.5}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: click
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Display bounds: [0,0][1440,2392]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":true}
[AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.performTouch() result: null
[HTTP] <-- POST /wd/hub/session/a06a68b3-53d9-40bf-96ea-6db90353984c/touch/perform 200 127 ms - 76
[HTTP] 


This one for the given command "Appium::TouchAction.new.tap(x:0.5, y:0.5, duration: 700).perform"

[HTTP] --> POST /wd/hub/session/a06a68b3-53d9-40bf-96ea-6db90353984c/touch/perform
[HTTP] {"actions":[{"action":"tap","options":{"x":0.5,"y":0.5,"duration":700,"count":1}}]}
[W3C] Calling AppiumDriver.performTouch() with args: [[{"action":"tap","options":{"x":0.5,"y":0.5,"duration":700,"count":1}}],"a06a68b3-53d9-40bf-96ea-6db90353984c"]
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"click","params":{"x":0.5,"y":0.5}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"click","params":{"x":0.5,"y":0.5}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: click
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Display bounds: [0,0][1440,2392]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":true}
[AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.performTouch() result: null
[HTTP] <-- POST /wd/hub/session/a06a68b3-53d9-40bf-96ea-6db90353984c/touch/perform 200 122 ms - 76
[HTTP] 

Then for double_tap "Appium::TouchAction.new.double_tap(x:0.5, y:0.5).perform"

[HTTP] --> POST /wd/hub/session/a06a68b3-53d9-40bf-96ea-6db90353984c/touch/perform
[HTTP] {"actions":[{"action":"doubleTap","options":{"x":0.5,"y":0.5}}]}
[W3C] Calling AppiumDriver.performTouch() with args: [[{"action":"doubleTap","options":{"x":0.5,"y":0.5}}],"a06a68b3-53d9-40bf-96ea-6db90353984c"]
[AndroidDriver] Error: unknown action doubleTap
[AndroidDriver]     at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[AndroidDriver]     at AndroidDriver.callee$0$0$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-driver/lib/commands/touch.js:32:11)
[AndroidDriver]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[AndroidDriver]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[AndroidDriver]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[AndroidDriver]     at invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[AndroidDriver]     at enqueueResult (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
[AndroidDriver]     at new Promise ()
[AndroidDriver]     at new F (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
[AndroidDriver]     at AsyncIterator.enqueue (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
[AndroidDriver]     at AsyncIterator.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[AndroidDriver]     at Object.runtime.async (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
[AndroidDriver]     at AndroidDriver.callee$0$0 [as doTouchAction] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-driver/build/lib/commands/touch.js:42:30)
[AndroidDriver]     at AndroidDriver.callee$0$0$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-driver/lib/commands/touch.js:121:23)
[AndroidDriver]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[AndroidDriver]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[AndroidDriver]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[AndroidDriver]     at invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[AndroidDriver]     at enqueueResult (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
[AndroidDriver]     at new Promise ()
[AndroidDriver]     at new F (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
[AndroidDriver]     at AsyncIterator.enqueue (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
[AndroidDriver]     at AsyncIterator.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[AndroidDriver]     at Object.runtime.async (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
[AndroidDriver]     at AndroidDriver.callee$0$0 [as performGesture] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-driver/build/lib/commands/touch.js:335:30)
[AndroidDriver]     at AndroidDriver.callee$0$0$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-driver/lib/commands/touch.js:191:18)
[AndroidDriver]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[AndroidDriver]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[AndroidDriver]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[AndroidDriver]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[AndroidDriver]     at 
[MJSONWP] Encountered internal error running command: Error: unknown action doubleTap
[MJSONWP]     at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[MJSONWP]     at AndroidDriver.callee$0$0$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-driver/lib/commands/touch.js:32:11)
[MJSONWP]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP]     at enqueueResult (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
[MJSONWP]     at new Promise ()
[MJSONWP]     at new F (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
[MJSONWP]     at AsyncIterator.enqueue (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
[MJSONWP]     at AsyncIterator.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at Object.runtime.async (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
[MJSONWP]     at AndroidDriver.callee$0$0 [as doTouchAction] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-driver/build/lib/commands/touch.js:42:30)
[MJSONWP]     at AndroidDriver.callee$0$0$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-driver/lib/commands/touch.js:121:23)
[MJSONWP]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP]     at enqueueResult (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
[MJSONWP]     at new Promise ()
[MJSONWP]     at new F (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
[MJSONWP]     at AsyncIterator.enqueue (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
[MJSONWP]     at AsyncIterator.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at Object.runtime.async (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
[MJSONWP]     at AndroidDriver.callee$0$0 [as performGesture] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-driver/build/lib/commands/touch.js:335:30)
[MJSONWP]     at AndroidDriver.callee$0$0$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-driver/lib/commands/touch.js:191:18)
[MJSONWP]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP]     at 
[HTTP] <-- POST /wd/hub/session/a06a68b3-53d9-40bf-96ea-6db90353984c/touch/perform 500 8 ms - 195
[HTTP]

**Comment by fabiohsl** [comment]
@mykola-mokhnach Done. First of all thanks for the quickly answer!

**Comment by mykola-mokhnach** [comment]
Use UIAutomator2 for Android6+. Also, tap coordinates should be integer numbers

**Comment by mykola-mokhnach** [comment]
uia1 is unlikely to be fixed, since it is considered deprecated.

**Comment by fabiohsl** [comment]
@mykola-mokhnach but on "ops" those values could be the same? I mean for all "automationName"

**Comment by mykola-mokhnach** [comment]
> but on "ops" those values could be the same? I mean for all "automationName"

I don't get this question. Please clarify
