### ISSUE TITLE
Cannot tap an element at the bottom of the screen for Galaxy S8 and S9

### ISSUE THREAD

**Issue by gkvappium** [appium/appium#11037]
## The problem

In case of S8, I cannot seem to tap an element which is at bottom most part of the screen

## Environment

* Appium version (or git revision) that exhibits the issue:1.8.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:MacOS
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Samsung S8 (8.0)
* Real device or emulator/simulator:Real Device
* Appium CLI or Appium.app|exe: CLI

## Details

1. I am using wd (javascript) and also a custom wrapper to write the tests in typescript.
2. I can spy the element using the appium inspector but not using the uiautomatorviewer. That part of the screen cannot be spied
3. When I do a getWindow size, This returns x=1080 and y=2076. This y value seems to be much lesser than the actual y value which is something like 2213 (Enabled pointer location and checked)
        let size = await driver.driver.getWindowSize();
        let x = size.width;
        let y = size.height;
        console.log(x);
        console.log(y);
4. When I do a isDisplayed() for the element, it returns True
5. It is not able to click the element (Which is a switch) no matter what (Using co-ordinates as well probably because y max is very less 2076)

This works on other phones. Seems to be a problem with Galaxy S8 and S9 (Maybe because of the design)

I cannot give a higher value for y since Appium treats it as out of bounds though it is not. I get the error something like,

 **_Error: [performTouchAction([{"action":"tap","options":{"x":972,"y":2146}}])] Error response status: 29, , InvalidElementCoordinates - The coordinates provided to an interactions operation are invalid. Selenium error: The coordinates provided to an interactions operation areinvalid._**

@mykola-mokhnach , @imurchie ,can you please advice

**Comment by mykola-mokhnach** [comment]
Do you use uiautomator2?

**Comment by gkvappium** [comment]
@mykola-mokhnach ,yes I use uiautomator2. There seems to be a problem only with this element and only on Galaxy S8 and S9 since this seems to be at the fag end of the screen and the y co-ordinate value that I am getting is much lesser than the actual y value

**Comment by mykola-mokhnach** [comment]
Appium uses the standard APIs to retrieve screen dimensions. I believe there must be an issue in Samsung firmware, that makes it to return wrong coordinates.

https://github.com/appium/appium-uiautomator2-server/blob/c92e52b8aa0167cb04720c2ed3c7c387bb4ddd81/app/src/main/java/io/appium/uiautomator2/handler/GetDeviceSize.java

**Comment by gkvappium** [comment]
Can you think of any workaround to mitigate this problem? Not sure why it isn't able to tap/click the element though isDisplayed() returns true. Tried the touch from the touch action class as well.

**Comment by mykola-mokhnach** [comment]
No, I don't have any ideas. It is necessary to have the physical device (and enough time) in order to try different options.

**Comment by gkvappium** [comment]
Hi @mykola-mokhnach , turns out to be a simple thingy. The problem can be mitigated by enabling the navigation bar (To be shown always at the bottom of the screen). Once this is done, appium is able to pick it up and tap it. I'll close the ticket

**Comment by antovrv** [comment]
@mykola-mokhnach I'm facing the nearly the same issue. When I try to click the option at the bottom of the screen. It's clicked on the soft keys at the bottom. (I mean Back, Home soft keys at the bottom). Is there any way to disable the soft keys while running automation?

**Comment by InfantAnto** [comment]
@gkvappium How did you enabled the navigation bar in appium?

**Comment by antovrv** [comment]
@mykola-mokhnach @gkvappium Any updates on this?

**Comment by rabbit0022** [comment]
@antovrv @InfantAnto Took me a while to figure this out too, but the navigation bar is turned on in the settings of your phone, not in appium...

**Comment by InfantAnto** [comment]
I don't see this issue after started using uiautomator2 and latest appium version as well
