### ISSUE TITLE
Unable to inspect UI-Catalog application

### ISSUE THREAD

**Issue by SapizonTechnologiesLLP** [appium/appium#11033]
## The problem

Unable to launch and inspect uicatalog application by setting the desired capabilities 
## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:  MacOS High Sierra Version 10.13.5
* Mobile platform/version under test: iPhone 7 version 11.4
* Real device or emulator/simulator: real device 
* Appium CLI or Appium.app|exe: Appium.app

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/SapizonTechnologiesLLP/f94c8c8bee6f8aa0b6dcecb330551c62

## Code To Reproduce Issue [ Good To Have ]

JSON Representation
```json
{
  "deviceName": "iphone 7",
  "udid": "45bd7b306f9607dd377b44c4ff75fee6247bd7bd",
  "automationName": "XCUITest",
  "platformName": "iOS",
  "platformVersion": "11.4",
  "showXcodeLog": "true",
  "xcodeOrgId": "78VUJKFNQZ",
  "xcodeSigningId": "siddharth81286@gmail.com",
  "noReset": true,
  "app": "/Users/apple/Library/Developer/Xcode/DerivedData/UICatalog-acatdmwvjisajobhpobwowuvzrhr/Build/Products/Debug-iphoneos/UICatalog"
}
```

**Comment by mykola-mokhnach** [comment]
> [MJSONWP] Encountered internal error running command: Error: Unknown device or simulator UDID: '45bd7b306f9607dd377b44c4ff75fee6247bd7bd'

The device is either not connected or not visible to imobiledevicelib. Double check your caps

**Comment by SapizonTechnologiesLLP** [comment]
The device is connected and even application is installed on the device.

**Comment by mykola-mokhnach** [comment]
if it is connected and configured properly then its udid should be present in `idevice_id -l` output

**Comment by SapizonTechnologiesLLP** [comment]
Can you please share the configurations steps so that I can cross-check at my end.

**Comment by SapizonTechnologiesLLP** [comment]
There is no videos or documentation available for installation and running test on real devices.

**Comment by mykola-mokhnach** [comment]
This is a place for issues. Please use Appium forum to ask questions

**Comment by imurchie** [comment]
You do not have `idevice_id` installed. It is installed with `libimobiledevice`, which can be installed through homebrew.

There is documentation for the whole process, which can be difficult: https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

**Comment by messianic** [comment]
Hey @SapizonTechnologiesLLP in case you are using Eclipse IDE, it is possible that it doesn't has access to your environment variables. Follow the below steps:
1. Go to the Applications folder.
2. Navigate and right click on the eclipse.app and choose 'show package contents'.
3. Goto Contents>MacOS and click on the eclipse shell file to open it.

It happens, despite of everything set up it doesn't work because of this.
