### ISSUE TITLE
How to Hide the Android Key Board using Java in latest version

### ISSUE THREAD

**Issue by ShibiKP** [appium/appium#11036]
In Java client 5.0.4 hideKeyboard() method has not present. How to handle the issue in latest Java Client version

## Environment

* Appium version 1.7.1
* Desktop OS/version used to run Appium:  OS Windows 8
* Node.js version (unless using Appium.app|exe): v8.11.3
* Mobile platform/version under test: Android/6.0.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: nodejs

## Details
HideKeyboad() have removed in the Latest version and how to use the latest version.

**Comment by mykola-mokhnach** [comment]
Please use appium forum to ask questions.
