### ISSUE TITLE
Android App just wouldn't launch (on emulator AND real device)

### ISSUE THREAD

**Issue by xinyan-y13** [appium/appium#11038]
## The problem

Hi everyone! I'm new to Appium and trying to do the protractor tests on devices and emulators using Appium. But although I already set everything up according to the tutorial, I simply cannot get the App to run on emulator or device. 
According to the Appium log I guess it's a proxy issue, but what confuses me is the error log "You tried to visit: http://localhost:8200/wd/hub/status", where does the port number 8200 come from? 

This is what I get on the server side:
> ...
> [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
> [JSONWP Proxy] Got unexpected response: 
> [JSONWP Proxy] 
> [JSONWP Proxy] 
> [JSONWP Proxy] 
> [JSONWP Proxy] 
> ...
> 

## Environment

* appium-version: 1.6.5
* Desktop OS/version used to run Appium: Windows 7
* Node.js version (unless using Appium.app|exe): v6.11.5
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: both with same error
* Appium CLI or Appium.app|exe: Appium.exe

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

[https://gist.github.com/xinyan-y13/1c07662cf6e6f12525ffc9161e7edfe7](url)

(I don't know why the link is 404, but Copy Paste it to browser is fine) 

## Code To Reproduce Issue [ Good To Have ]

protractor.conf.js looks like this: 

```
seleniumAddress: 'http://localhost:4723/wd/hub',
  capabilities:{
    browserName: '',
    autoWebview: true,
    platformName: 'Android',
    'appium-version': '1.6.5',
    platformVersion:'7.0',
    // udid: 'ce01171153cb9c1305',
    // deviceName: 'Samsung Galaxy S7',
    deviceName: 'emulator-5554',
    avd : 'Nexus_4',
    app:'C:/.../android-debug.apk',
    automationName: 'UIAutomator2'
  },
baseUrl: 'http://localhost:8100'
```

Thanks in advance.

**Comment by mykola-mokhnach** [comment]
Yes, this is an issue with your local proxy, which intercepts server requests. You must solve it with you network administrator.

Closed as not issue.
