### ISSUE TITLE
Appium iOS app scroll is not happening for touch action, swipe 

### ISSUE THREAD

**Issue by BShivShankar** [appium/appium#11042]
## The problem

Appium iOS app scroll is not happening for touch action, swipe tried not working. 

## Environment

* Appium version 1.8.0 - appium Desktop
* Desktop OS/version used to run Appium: MAC
* Node.js version (unless using Appium.app|exe): v8.11.3
* Mobile platform/version under test: iphoneX/11.2.6
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium desktop

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

No logs populated, getting search for next element 

## Code To Reproduce Issue [ Good To Have ]

TouchAction action = new TouchAction(driver)
			  .press(150, 602)
			  .moveTo(147,199)
			  .release()
			  .perform();

And help me to scroll continuously to find an exact element and click

**Comment by mykola-mokhnach** [comment]
Replace press with longPress or add wait with duration >= 500 ms after press. Closed as duplicate
