### ISSUE TITLE
In documentation message about issue, bun there is no link

### ISSUE THREAD

**Issue by romansvesh** [appium/appium#11041]
## The problem

There is the text in documentation http://appium.io/docs/en/writing-running-appium/finding-elements/index.html:
```
Issues
There's a known issue with table cell elements becoming invalidated before there's time to interact with them. We're working on a fix
```
But there is no link to this issue.

**Comment by dpgraham** [comment]
Closing as "won't fix" because there's no issue open for it and I don't think we'll be able to fix this in UiAutomator2.

The Espresso driver probably won't have these issues.
