### ISSUE TITLE
Appium does not build on debian stretch

### ISSUE THREAD

**Issue by elijahbal** [appium/appium#11040]
## The problem

Installation from git repository is failing with npm 1.4.21 on debian stretch.

## Environment

* git HEAD 09b80e2e625909b2e09c69d8e6581ddf56816b26
* Debian Stretch
* Node.js version: v8.11.2
* Mobile platform/version under test: NA
* Real device or emulator/simulator: NA
* Appium CLI or Appium.app|exe: NA

## Details

Command:

```
npm install .
```

## Link to Appium logs

https://gist.github.com/elijahbal/62096483155ab3fdf4da01528c150981

**Comment by imurchie** [comment]
My first suggestion would be to try to update npm. Version 1.4.21 [was released](https://github.com/npm/npm/releases/tag/v1.4.21) just under four years ago, and almost certainly is unsupported.
