### ISSUE TITLE
setLocation crashes the app on IOS

### ISSUE THREAD

**Issue by sarathsp23** [appium/appium#11053]
## The problem

While trying to setLocation on IOS read device, the application crashes most of the time.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.2-beta (tried 1.8.1 as well)
* Last Appium version that did not exhibit the issue (if applicable): (I so far have not been able to successful with setting the location on any version of appium)
* Desktop OS/version used to run Appium: High Sierra
* Node.js version (unless using Appium.app|exe): v10.6.0
* Mobile platform/version under test: iPhone 6
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Details

It fails while trying to set locations multiple times, I have noticed that it is sometimes able to set the locations but most of the times fails setting it.

Following are the location details I have been trying to set 
|latitude      | longitude   | altitude |
|-33.80133 | 150.95640 | 43        |
|-33.78726 | 150.95147 | 32         |
|-33.77430 | 150.93614 | 33         |

## Link to Appium logs

<script src="https://gist.github.com/sarathsp23/b71f09d4ff342c2e9aa7fbe7a13f2793.js"></script>

**Comment by mykola-mokhnach** [comment]
There is nothing that can be done on Appium side to change that, since we use third party tool (idevicelocation) in order to fake GPS location. Please describe the problem in their issues tracker.

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing that can be done on Appium side.
