### ISSUE TITLE
Not able to connect from eclipse to appium. If you try to connect same device from appium, it is. Please help me on this issue

### ISSUE THREAD

**Issue by RajSelenuim** [appium/appium#11050]
## The problem

Could not able to connect with eclipse to device as it is throwing below error_

Capabilities [{clearSystemFiles=true, noReset=true, commandTimeouts=180000, newCommandTimeout=18000, platformVersion=11.4, automationName=XCUITest, bundleId=com.bns.universalbanker.customer, xcodeConfigFile=/Users/automation/Desktop/ExtentWorkspace/UniversalSeleniumAutomation-sept08-2017/Configuration/xcodeConfigfile.xcconfig, udid=086ea2903953fb4a915fc5b3f050f1046d5b8266, platformName=ios, deviceName=testersipad, fullReset=false}]
http://0.0.0.0:4723/wd/hub
An unknown server-side error occurred while processing the command. Original error: App with bundle identifier 'com.bns.universalbanker.customer' unknown (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
System info: host: 'ubmac.local', ip: 'fe80:0:0:0:1062:e60a:f436:511e%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.4', java.version: '1.8.0_112'
Driver info: driver.version: IOSDriver

Capabilities from appium to device connectivity is similar to which provided into eclipse to connect
  

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable): 1.8.1
* Desktop OS/version used to run Appium: NA
* Node.js version (unless using Appium.app|exe): NA
* Mobile platform/version under test: iOS, 11.4
* Real device or emulator/simulator: iPad
* Appium CLI or Appium.app|exe: NA

appium log 👍 

[info] [Appium] Welcome to Appium v1.8.1[info] [HTTP] --> POST /wd/hub/session
[info] [HTTP] {"desiredCapabilities":{"clearSystemFiles":true,"noReset":true,"commandTimeouts":"180000","bundleId":"com.bns.universalbanker.customer","xcodeConfigFile":"/Users/automation/Desktop/ExtentWorkspace/UniversalSeleniumAutomation-sept08-2017/Configuration/xcodeConfigfile.xcconfig","deviceName":"testersipad","fullReset":false,"newCommandTimeout":18000,"platformVersion":"11.4","automationName":"XCUITest","udid":"086ea2903953fb4a915fc5b3f050f1046d5b8266","platformName":"iOS"},"requiredCapabilities":{},"capabilities":{"desiredCapabilities":{"clearSystemFiles":true,"noReset":true,"commandTimeouts":"180000","bundleId":"com.bns.universalbanker.customer","xcodeConfigFile":"/Users/automation/Desktop/ExtentWorkspace/UniversalSeleniumAutomation-sept08-2017/Configuration/xcodeConfigfile.xcconfig","deviceName":"testersipad","fullReset":false,"newCommandTimeout":18000,"platformVersion":"11.4","automationName":"XCUITest","udid":"086ea2903953fb4a915fc5b3f050f1046d5b8266","platformName":"iOS"},"requiredCapa
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"clearSystemFiles":true,"noReset":true,"commandTimeouts":"180000","bundleId":"com.bns.universalbanker.customer","xcodeConfigFile":"/Users/automation/Desktop/ExtentWorkspace/UniversalSeleniumAutomation-sept08-2017/Configuration/xcodeConfigfile.xcconfig","deviceName":"testersipad","fullReset":false,"newCommandTimeout":18000,"platformVersion":"11.4","automationName":"XCUITest","udid":"086ea2903953fb4a915fc5b3f050f1046d5b8266","platformName":"iOS"},{},{"desiredCapabilities":{"clearSystemFiles":true,"noReset":true,"commandTimeouts":"180000","bundleId":"com.bns.universalbanker.customer","xcodeConfigFile":"/Users/automation/Desktop/ExtentWorkspace/UniversalSeleniumAutomation-sept08-2017/Configuration/xcodeConfigfile.xcconfig","deviceName":"testersipad","fullReset":false,"newCommandTimeout":18000,"platformVersion":"11.4","automationName":"XCUITest","udid":"086ea2903953fb4a915fc5b3f050f1046d5b8266","platformName":"iOS"},"requiredCapabilities":{}}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1531754150703 (11:15:50 GMT-0400 (EDT))
[warn] [Appium] Could not parse W3C capabilities: 'platformName' can't be blank; 'deviceName' can't be blank. Falling back to JSONWP protocol.
[warn] [Appium] The following capabilities were provided in the JSONWP desired capabilities that are missing in W3C capabilities: ["clearSystemFiles","noReset","commandTimeouts","bundleId","xcodeConfigFile","deviceName","fullReset","newCommandTimeout","platformVersion","automationName","udid","platformName"]. Falling back to JSONWP protocol.
[info] [Appium] Creating new XCUITestDriver (v2.84.0) session
[info] [Appium] Capabilities:
[info] [Appium]   clearSystemFiles: true
[info] [Appium]   noReset: true
[info] [Appium]   commandTimeouts: 180000
[info] [Appium]   bundleId: com.bns.universalbanker.customer
[info] [Appium]   xcodeConfigFile: /Users/automation/Desktop/ExtentWorkspace/UniversalSeleniumAutomation-sept08-2017/Configuration/xcodeConfigfile.xcconfig
[info] [Appium]   deviceName: testersipad
[info] [Appium]   fullReset: false
[info] [Appium]   newCommandTimeout: 18000
[info] [Appium]   platformVersion: 11.4
[info] [Appium]   automationName: XCUITest
[info] [Appium]   udid: 086ea2903953fb4a915fc5b3f050f1046d5b8266
[info] [Appium]   platformName: iOS
[debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {"clearSystemFiles":true,"n...
[info] [BaseDriver] Session created with session id: edcd3470-3fa4-46ce-b807-dadcbf242c8e[debug] [XCUITest] Xcode version set to '9.4.1' (tools v9.4.1.0.1.1528165917)[debug] [XCUITest] Available devices: 086ea2903953fb4a915fc5b3f050f1046d5b8266
[debug] [XCUITest] Creating iDevice object with udid '086ea2903953fb4a915fc5b3f050f1046d5b8266'
[info] [XCUITest] Determining device to run tests on: udid: '086ea2903953fb4a915fc5b3f050f1046d5b8266', real device: true
[debug] [BaseDriver] Event 'appConfigured' logged at 1531754168649 (11:16:08 GMT-0400 (EDT))
[debug] [BaseDriver] Event 'resetStarted' logged at 1531754168649 (11:16:08 GMT-0400 (EDT))
[debug] [XCUITest] Reset: fullReset not set. Leaving as is
[debug] [BaseDriver] Event 'resetComplete' logged at 1531754168650 (11:16:08 GMT-0400 (EDT))
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Starting iOS device log capture with: 'idevicesyslog'[debug] [XCUITest] Crash reports root '/Users/automation/Library/Logs/CrashReporter/MobileDevice/testersipad' does not exist. Got nothing to gather.
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1531754169357 (11:16:09 GMT-0400 (EDT))
[info] [XCUITest] Setting up real device

Please advise me if required provide you more details.

Thanks,
Raj

**Comment by mykola-mokhnach** [comment]
> An unknown server-side error occurred while processing the command. Original error: App with bundle identifier 'com.bns.universalbanker.customer' unknown (WARNING: The server did not provide any stacktrace information)

The application with given bundle identifier seems to be not present on the device.

**Comment by messianic** [comment]
Hey @RajSelenuim , try starting eclipse from its shell file. Follow these steps:
1. Goto Applications folder or wherever your eclipse is installed.
2. Right click on eclipse icon and choose show package contents.
3. Open the Contents folder.
4. Find the folder named MacOS and double click on the eclispse shell file.

This will fire up a terminal window and open your eclipse.
