### ISSUE TITLE
Appium -  Error communicating with the remote browser.

### ISSUE THREAD

**Issue by AvrahamAtia** [appium/appium#11058]
## The problem

The problem happen sometime, not always.
 
## Environment

* Desktop OS/version used to run Appium: 10.2.6
* Node.js version (unless using Appium.app|exe): v7.5.0
* Mobile platform/version under test: Android, Galaxy S9+, 8.0.0
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: 1.7.2

## Details

06:49:07 Jul 17, 2018 3:49:07 AM org.openqa.selenium.support.ui.ExpectedConditions findElement
06:49:07 WARNING: WebDriverException thrown by findElement(By.xpath: //*[@text='FN1531823251126 test'])
06:49:07 org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
06:49:07 Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
06:49:07 System info: host: 'automacus', ip: '172.20.48.48', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_121'
06:49:07 Driver info: driver.version: AndroidDriver
06:49:07 Capabilities [{app=/Staging/Staging5.12.apk, appPackage=com.**.staging, deviceScreenSize=1440x2960, networkConnectionEnabled=true, warnings={}, commandTimeout=60, appWaitPackage=com.**.staging, appWaitActivity=com.**.activity***LauncherActivity, databaseEnabled=false, deviceName=4659545751543098, platform=LINUX, deviceUDID=4659545751543098, appActivity=com.***.activity.****LauncherActivity, desired={app=/Staging/Staging5.12.apk, platformVersion=8.0.0, commandTimeout=60, platformName=Android, deviceName=Galaxy S9+}, platformVersion=8.0.0, webStorageEnabled=false, locationContextEnabled=false, takesScreenshot=true, javascriptEnabled=true, deviceModel=SM-G965U, platformName=Android, deviceManufacturer=samsung}]
06:49:07 Session ID: 9e932809-b498-4525-84b2-c20bbaf5f19e
06:49:07 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)
06:49:07 	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:40)
06:49:07 	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
06:49:07 	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
06:49:07 	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:363)
06:49:07 	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:56)
06:49:07 	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
06:49:07 	at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriver.java:1)
06:49:07 	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:500)
06:49:07 	at io.appium.java_client.DefaultGenericMobileDriver.findElementByXPath(DefaultGenericMobileDriver.java:134)
06:49:07 	at io.appium.java_client.AppiumDriver.findElementByXPath(AppiumDriver.java:1)
06:49:07 	at io.appium.java_client.android.AndroidDriver.findElementByXPath(AndroidDriver.java:1)
06:49:07 	at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
06:49:07 	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:355)
06:49:07 	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:52)
06:49:07 	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
06:49:07 	at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriver.java:1)
06:49:07 	at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:899)
06:49:07 	at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:41)
06:49:07 	at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:205)
06:49:07 	at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:201)
06:49:07 	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
06:49:07 	at infra.driver.actions.AppiumActionBotImpl.getIsVisible(AppiumActionBotImpl.java:440)
06:49:07 	at infra.driver.verifications.AppiumVerificationBotImpl.verifyVisible(AppiumVerificationBotImpl.java:54)
06:49:07 	at infra.pages.cart.android.ShippingAddressAP.verifyAddress(ShippingAddressAP.java:317)
06:49:07 	at tests.Android.Account.EditAddressFromNonUSToUS.accountEditAddressFromNonUSToUS(EditAddressFromNonUSToUS.java:47)
06:49:07 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
06:49:07 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
06:49:07 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
06:49:07 	at java.lang.reflect.Method.invoke(Method.java:498)
06:49:07 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
06:49:07 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
06:49:07 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
06:49:07 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
06:49:07 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
06:49:07 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
06:49:07 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
06:49:07 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
06:49:07 	at java.lang.Thread.run(Thread.java:745)
06:49:07 Caused by: org.openqa.selenium.WebDriverException: org.apache.http.NoHttpResponseException: 127.0.0.1:4726 failed to respond
06:49:07 Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
06:49:07 System info: host: 'automacus', ip: '172.20.48.48', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_121'
06:49:07 Driver info: driver.version: AndroidDriver
06:49:07 	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:84)
06:49:07 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
06:49:07 	... 38 more
06:49:07 Caused by: org.apache.http.NoHttpResponseException: 127.0.0.1:4726 failed to respond
06:49:07 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
06:49:07 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
06:49:07 	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
06:49:07 	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
06:49:07 	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
06:49:07 	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
06:49:07 	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
06:49:07 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
06:49:07 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
06:49:07 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
06:49:07 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
06:49:07 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
06:49:07 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
06:49:07 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
06:49:07 	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:162)
06:49:07 	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:90)
06:49:07 	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
06:49:07 	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:69)
06:49:07 	... 39 more
06:49:07 
06:59:07 Jul 17, 2018 3:59:07 AM org.apache.http.impl.execchain.RetryExec execute
06:59:07 INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://127.0.0.1:4726: The target server failed to respond
06:59:07 Jul 17, 2018 3:59:07 AM org.apache.http.impl.execchain.RetryExec execute
06:59:07 INFO: Retrying request to {}->http://127.0.0.1:4726
07:09:07 Jul 17, 2018 4:09:07 AM org.apache.http.impl.execchain.RetryExec execute
07:09:07 INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://127.0.0.1:4726: The target server failed to respond
07:09:07 Jul 17, 2018 4:09:07 AM org.apache.http.impl.execchain.RetryExec execute
07:09:07 INFO: Retrying request to {}->http://127.0.0.1:4726
07:19:07 Jul 17, 2018 4:19:07 AM org.apache.http.impl.execchain.RetryExec execute
07:19:07 INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://127.0.0.1:4726: The target server failed to respond
07:19:07 Jul 17, 2018 4:19:07 AM org.apache.http.impl.execchain.RetryExec execute
07:19:07 INFO: Retrying request to {}->http://127.0.0.1:4726

**Comment by mykola-mokhnach** [comment]
Please attach the server log

**Comment by AvrahamAtia** [comment]
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//android.widget.TextView[@text='Automation Qa (self)']","context":"","multiple":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding '//android.widget.TextView[@text='Automation Qa (self)']' using 'XPATH' with the contextId: '' multiple: false
[HTTP] <-- POST /wd/hub/session/cd10c4c6-946a-4076-8dab-25e9f13dba25/element - - ms - - 
[HTTP] --> POST /wd/hub/session/cd10c4c6-946a-4076-8dab-25e9f13dba25/element {"using":"xpath","value":"//android.widget.TextView[@text='Automation Qa (self)']"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath","//android.widget.TextView[@text='Automation Qa (self)']","cd10c4c6-946a-4076-8dab-25e9f13dba25"]
[HTTP] <-- POST /wd/hub/session/cd10c4c6-946a-4076-8dab-25e9f13dba25/element - - ms - - 
[HTTP] --> GET /wd/hub/session/cd10c4c6-946a-4076-8dab-25e9f13dba25/screenshot {}
[debug] [MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["cd10c4c6-946a-4076-8dab-25e9f13dba25"]
[HTTP] <-- GET /wd/hub/session/cd10c4c6-946a-4076-8dab-25e9f13dba25/screenshot - - ms - - 
[HTTP] --> GET /wd/hub/session/cd10c4c6-946a-4076-8dab-25e9f13dba25/screenshot {}
[debug] [MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["cd10c4c6-946a-4076-8dab-25e9f13dba25"]
[HTTP] <-- GET /wd/hub/session/cd10c4c6-946a-4076-8dab-25e9f13dba25/screenshot - - ms - - 
[HTTP] --> GET /wd/hub/session/cd10c4c6-946a-4076-8dab-25e9f13dba25/screenshot {}
[debug] [MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["cd10c4c6-946a-4076-8dab-25e9f13dba25"]
[HTTP] <-- GET /wd/hub/session/cd10c4c6-946a-4076-8dab-25e9f13dba25/screenshot - - ms - - 
[HTTP] --> GET /wd/hub/session/cd10c4c6-946a-4076-8dab-25e9f13dba25/screenshot {}
[debug] [MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["cd10c4c6-946a-4076-8dab-25e9f13dba25"]
[HTTP] <-- GET /wd/hub/session/cd10c4c6-946a-4076-8dab-25e9f13dba25/screenshot - - ms - - 
[HTTP] --> GET /wd/hub/session/cd10c4c6-946a-4076-8dab-25e9f13dba25/screenshot {}
[debug] [MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["cd10c4c6-946a-4076-8dab-25e9f13dba25"]
[HTTP] <-- GET /wd/hub/session/cd10c4c6-946a-4076-8dab-25e9f13dba25/screenshot - - ms - - 
[HTTP] --> GET /wd/hub/session/cd10c4c6-946a-4076-8dab-25e9f13dba25/screenshot {}
[debug] [MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["cd10c4c6-946a-4076-8dab-25e9f13dba25"]
[HTTP] <-- GET /wd/hub/session/cd10c4c6-946a-4076-8dab-25e9f13dba25/screenshot - - ms - - 
[HTTP] --> GET /wd/hub/session/cd10c4c6-946a-4076-8dab-25e9f13dba25/screenshot {}
[debug] [MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["cd10c4c6-946a-4076-8dab-25e9f13dba25"]
[HTTP] <-- GET /wd/hub/session/cd10c4c6-946a-4076-8dab-25e9f13dba25/screenshot - - ms - - 
[HTTP] --> GET /wd/hub/session/cd10c4c6-946a-4076-8dab-25e9f13dba25/screenshot {}
[debug] [MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["cd10c4c6-946a-4076-8dab-25e9f13dba25"]
[HTTP] <-- GET /wd/hub/session/cd10c4c6-946a-4076-8dab-25e9f13dba25/screenshot - - ms - - 
[HTTP] --> GET /wd/hub/session/cd10c4c6-946a-4076-8dab-25e9f13dba25/screenshot {}
[debug] [MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["cd10c4c6-946a-4076-8dab-25e9f13dba25"]
[HTTP] <-- GET /wd/hub/session/cd10c4c6-946a-4076-8dab-25e9f13dba25/screenshot - - ms - - 
[HTTP] --> GET /wd/hub/session/cd10c4c6-946a-4076-8dab-25e9f13dba25/screenshot {}
[debug] [MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["cd10c4c6-946a-4076-8dab-25e9f13dba25"]

**Comment by AvrahamAtia** [comment]
But we have too many problems with UIAutomator2

**Comment by mykola-mokhnach** [comment]
Then you are most likely on your own, because Google does not support UIAutomator1 since Android6

**Comment by AvrahamAtia** [comment]
does Appium not support UIAutomator1??

**Comment by AvrahamAtia** [comment]
sometime it is work and sometime is not working//

**Comment by mykola-mokhnach** [comment]
We do support it but only for legacy Android versions (5 and older)

**Comment by AvrahamAtia** [comment]
What is the best way to start Appium severs, in code before the tests starts or start Appium server and live the server run al the time?

**Comment by AvrahamAtia** [comment]
Device log: 07-26 14:30:31.913 15048-15263/? D/DnsProxyListener: DNSDBG::dns addrinfo af 2
07-26 14:30:32.015 4843-4886/? I/uiautomator: SuspendAllInternal: 1. proc_name - 
    SuspendAllInternal: 2.proc_name - uiautomator
07-26 14:30:32.111 4843-4891/? E/QueryController: Got null root node from accessibility - Retrying...
07-26 14:30:32.300 15048-7539/? E/DnsProxyListener: send_dns_err: Not Ready to mdc
07-26 14:30:32.363 4843-4891/? E/QueryController: Cannot proceed when root node is null. Aborted search
    Got null root node from accessibility - Retrying...
07-26 14:30:32.614 4843-4891/? I/chatty: uid=2000(shell) WatchTimer identical 1 line
07-26 14:30:32.867 4843-4891/? E/QueryController: Got null root node from accessibility - Retrying...
07-26 14:30:33.119 4843-4891/? E/QueryController: Cannot proceed when root node is null. Aborted search
07-26 14:30:33.120 4843-4891/? E/QueryController: Got null root node from accessibility - Retrying...
07-26 14:30:33.376 4278-4278/? I/android.hardware.wifi@1.0-service: getLinkLayerStats
07-26 14:30:33.624 4843-4891/? E/QueryController: Got null root node from accessibility - Retrying...
07-26 14:30:33.875 4843-4891/? E/QueryController: Cannot proceed when root node is null. Aborted search
07-26 14:30:33.876 4843-4891/? E/QueryController: Got null root node from accessibility - Retrying...
07-26 14:30:34.128 4843-4891/? I/chatty: uid=2000(shell) WatchTimer identical 1 line
07-26 14:30:34.379 4843-4891/? E/QueryController: Got null root node from accessibility - Retrying...
07-26 14:30:34.630 4843-4891/? E/QueryController: Cannot proceed when root node is null. Aborted search
    Got null root node from accessibility - Retrying...
07-26 14:30:34.887 5925-5925/? D/io_stats: !@   8,0 r 12396367 830677972 w 20808687 334738908 d 1982863 184744444 f 5699829 5891177 iot 14529564 10631924 th 235388 0 0 pt 0 inp 0 0 4677095.024
07-26 14:30:35.135 4843-4891/? E/QueryController: Got null root node from accessibility - Retrying...
07-26 14:30:35.387 4843-4891/? E/QueryController: Cannot proceed when root node is null. Aborted search
07-26 14:30:35.388 4843-4891/? E/QueryController: Got null root node from accessibility - Retrying...
07-26 14:30:35.495 15302-17201/? D/BatteryService: !@BatteryListener : batteryPropertiesChanged!
07-26 14:30:35.496 15302-17201/? D/BatteryService: level:100, scale:100, status:5, health:2, present:true, voltage: 4297, temperature: 343, technology: Li-ion, AC powered:false, USB powered:true, POGO powered:false, Wireless powered:false, icon:17303838, invalid charger:0, maxChargingCurrent:0, maxChargingVoltage:0, chargeCounter:2940000
    online:4, current avg:245, charge type:1, power sharing:false, high voltage charger:false, capacity:280000, batterySWSelfDischarging:false, misc_event:0, current_event:0, current_now:254
07-26 14:30:35.496 15302-15302/? D/BatteryService: Sending ACTION_BATTERY_CHANGED.
07-26 14:30:35.499 15302-15302/? I/MotionRecognitionService: Plugged
07-26 14:30:35.499 15302-15302/? D/MotionRecognitionService:   mCableConnection= 1
    setPowerConnected : mGripEnabled = false
07-26 14:30:35.500 15302-15302/? D/SamsungPhoneWindowManager: ACTION_BATTERY_CHANGED - Level :: 100, battStatus :: 5
07-26 14:30:35.502 15302-15407/? D/UsbDeviceManager: handleMessage -> MSG_UPDATE_CHARGING_STATE = 1
07-26 14:30:35.506 15849-15849/? D/KeyguardUpdateMonitor: received broadcast android.intent.action.BATTERY_CHANGED
07-26 14:30:35.510 15849-15849/? D/BatteryController: onReceive-ACTION_BATTERY_CHANGED : mLevel=100, mBatteryStatus=5
07-26 14:30:35.517 15814-15814/? V/HeadsetService: Received Intent.ACTION_BATTERY_CHANGED
07-26 14:30:35.519 15814-16532/? D/HeadsetStateMachine: Disconnected process message: 10, size: 0
07-26 14:30:35.521 15849-15849/? D/PowerUI: priorPlugType = 2 mPlugType =  2
07-26 14:30:35.640 4843-4891/? E/QueryController: Got null root node from accessibility - Retrying...
07-26 14:30:35.892 4843-4891/? E/QueryController: Got null root node from accessibility - Retrying...
07-26 14:30:36.144 4843-4891/? E/QueryController: Cannot proceed when root node is null. Aborted search
07-26 14:30:36.145 4843-4891/? E/QueryController: Got null root node from accessibility - Retrying...
07-26 14:30:36.453 4278-4278/? I/android.hardware.wifi@1.0-service: getLinkLayerStats
07-26 14:30:36.511 17182-17299/? D/ContactsProvider_EventLog: contents_sample_state: [CONTACT contacts(0) data(0) accounts({}) accounts deleted({}) calls([]) countryIso(IL) userId(0)  ]
    contents_sample_state: [ agr({})  ]

**Comment by mykola-mokhnach** [comment]
> What is the best way to start Appium severs, in code before the tests starts or to start Appium server and live the server run al the time?

Please use appium forum to ask questions

**Comment by dkTeks** [comment]
I am using UIAutomator2. still I am getting this error sometimes-"Error communicating with the remote browser. It may have died."  Please help me out.
