### ISSUE TITLE
How can I switch between handles in case when I am using robot-framewok and AppiumLibrary?

### ISSUE THREAD

**Issue by antonkobzar** [appium/appium#11051]
## The problem

Hi,
I've faced problem described in issue 'https://github.com/appium/appium/issues/3802'.
I can not switch between window handles using 'AppiumLibrary'. There are no keywords for that.
So, can you please suggest how to switch between handles by using Robot Framework

* Appium version (or git revision) that exhibits the issue: 1.8.2 beta
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: 10.13.4
* Node.js version (unless using Appium.app|exe): N/A
* Mobile platform/version under test: IOS 11.4
* Real device or emulator/simulator: Real (Iphone 6s)

Simple TC:
1) Open application (Contexts: NATIVE_APP, WEBVIEW_1)
2) Click 'Login via Facebook' (contexts: NATIVE_APP, WEBVIEW_2)
3) Complete 'Login via Facebook' (contexts: NATIVE_APP)

AR: There are no any contexts except of 'NATIVE_APP'

**Comment by mykola-mokhnach** [comment]
Please use Appium forum to ask questions. This is the place for server issues.
