### ISSUE TITLE
Launching app from Visual Studio returns Error: Could not find adb Please set the ANDROID_HOME environment variable with the Android SDK root directory path even if it is there

### ISSUE THREAD

**Issue by yotsubakoiwai** [appium/appium#11054]
## The problem

I have a Test created in Visual Studio that launches the United Airlines native app on an Android emulator. When I try to run the test, it results in:
`[ADB] The ANDROID_HOME environment variable is not set to the Android SDK root directory path. ANDROID_HOME is required for compatibility with SDK 23+. Checking along PATH for adb.
[debug] [AndroidDriver] Shutting down Android driver
[debug] [AndroidDriver] Called deleteSession but bootstrap wasn't active
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1531814615888 (16:03:35 GMT+0800 (AWST))
[MJSONWP] Encountered internal error running command: Error: Could not find adb Please set the ANDROID_HOME environment variable with the Android SDK root directory path.
[MJSONWP]     at ADB.callee$0$0$ (/usr/local/lib/node_modules/appium/node_modules/appium-adb/lib/tools/system-calls.js:124:11)
[MJSONWP]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP]     at <anonymous>`

I have checked ANDROID_HOME and PATH environment variables and the Android SDK path is there.

When I use the same capabilities from my code to launch the app via Appium Inspector, it successfully launches the app from the emulator without any problem.

## Environment

* Appium version: 1.8.1
* Desktop OS/version used to run Appium: macOS High Sierra 10.13.3
* Node.js version: 8.11.3
* Mobile platform/version under test: Android Emulator > Nexus_5X_API_26 (8.0)
* Appium CLI: 1.8.1
* .bash_profile
export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
export ANDROID_HOME=/Users/[userName]/Library/Android/sdk
export PATH=${PATH}:$ANDROID_HOME:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$JAVA_HOME/bin

When I echo $PATH and echo $ANDROID_HOME, they're returning the correct details.
I have also restarted the system a couple of times. The test still fails and cannot connect to Appium.

## Link to Appium logs

https://gist.github.com/yotsubakoiwai/eb5ed4c61e818de71f9e3ba799da5e7e

**Comment by mykola-mokhnach** [comment]
You must properly configure the environment. Read https://github.com/appium/java-client/blob/master/docs/environment.md for more details. Closed as duplicate.

**Comment by yotsubakoiwai** [comment]
hello @mykola-mokhnach...

all other setup are there. Appium-doctor is fine too. Only difference is when I do echo $PATH, it will return these
`/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin:/Users/user/Library/Android/sdk:/Users/user/Library/Android/sdk/tools:/Users/user/Library/Android/sdk/platform-tools:/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/bin`

but when I do the ps eww, PATH is like this: PATH=/usr/bin:/bin

**Comment by mykola-mokhnach** [comment]
> but when I do the ps eww, PATH is like this: PATH=/usr/bin:/bin

This is the problem. You need to configure it particularly for Visual Studio or for your client code, since it does not pickup the value from the default user environment.
