### ISSUE TITLE
Android Emulator in Docker, appium failed to install "Can't find service: package"

### ISSUE THREAD

**Issue by andyjamesdavies** [appium/appium#11057]
## The problem

I have a docker image setup with appium and an android emulator installed, these get run on startup and then e2e tests run against these. When trying to run the e2e tests I get the following error output:
```
[MJSONWP] Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command '/opt/android/platform-tools/adb -P 5037 -s emulator-5554 install gen/instances/eng/native_app/eng_dev.apk' exited with code 1'; Stderr: 'adb: failed to install gen/instances/eng/native_app/eng_dev.apk: cmd: Can't find service: package'; Code: '1'
[MJSONWP]     at ADB.execFunc$ (/usr/lib/node_modules/appium/node_modules/appium-adb/lib/tools/system-calls.js:317:13)
[MJSONWP]     at tryCatch (/usr/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (/usr/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP]     at <anonymous>
```

## Environment

The docker image:
- appium: v1.8.1
- android sdk:
-- buildtools;28.0.1
-- platform-tools
-- platforms;android-28
-- system-images;android-28;google_apis_playstore;x86

test run setup:
```
url = 'http://localhost:4723/wd/hub'
desired_caps = {
    'platformVersion': '9',
    'deviceName': 'Android Emulator',
    'platformName': 'Android',
    'app': 'gen/instances/eng/native_app/eng_dev.apk',
}
cls.driver = webdriver.Remote(url, desired_caps)
```

## Details

What's strange is that if I run the docker instance and then run `/opt/android/platform-tools/adb -P 5037 -s emulator-5554 install gen/instances/eng/native_app/eng_dev.apk` in a shell in the docker container it installs fine without errors.

What's also strange is I don't get this error for the android emulator `system-images;android-27;google_apis_playstore;x86`

**Comment by mykola-mokhnach** [comment]
Try to set the `avd` capability. I saw such issues usually happen if the emulator is too slow, so not all services have enough time for initialisation before application install is invoked.

**Comment by andyjamesdavies** [comment]
That was exactly what I needed, thanks @mykola-mokhnach
