### ISSUE TITLE
Screen rotation for application with fixed orientation

### ISSUE THREAD

**Issue by GrzegorzSidwa** [appium/appium#11060]
## The problem

When setting orientation to portrait for application which has fixed landscape orientation request hangs for about 2minutes.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS, Windows
* Mobile platform/version under test: Android 7
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: cli

## Details

When setting orientation to portrait for application which has fixed landscape orientation request hangs for about 2minutes. Issue has been recreated on both Java and .Net clients. 
**In terms of .Net error thrown:**

> A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://127.0.0.1:4723/wd/hub/session/a2fcd098-ebda-4c13-a218-f45d6f03c423/orientation. The status of the exception was ConnectionClosed, and the message was: The underlying connection was closed: The connection was closed unexpectedly.
> The underlying connection was closed: The connection was closed unexpectedly.

**In terms of Java client:**

> java.io.IOException: unexpected end of stream on Connection{10.5.17.244:4723, proxy=DIRECT hostAddress=/10.5.17.244:4723 cipherSuite=none protocol=http/1.1}
> Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'

Is there a way to check before sending change rotation request if application is restricted to specific orientation? 

## Link to Appium logs

https://gist.github.com/GrzegorzSidwa/f00176d848beba2ab6c9965c2d4b9a51

## Code To Reproduce Issue [ Good To Have ]

Every app with fixed orientation.

**Comment by mykola-mokhnach** [comment]
XCTest does not provide any methods to check such things. Please let us know if you find one.

Closed as third party issue.

**Comment by GrzegorzSidwa** [comment]
@mykola-mokhnach  I will be grateful for reopening the issue since it's related to Android.

> Mobile platform/version under test: Android 7

XCTest is for iOS as far as I remember ;)

Even if we will be not able to extract such information using Appium I think that issue shouldn't be closed. I suppose freezing of request for such long time in such case is not appropriate behavior, am I right?

**Comment by mykola-mokhnach** [comment]
Android also does not provide such information, because we are working with accessibility layer and don't have access to the application views (perhaps, the situation could be better in Espresso driver from this perspective). 

We cannot do anything regarding freezing, since that happens on UIA2 framework side and cannot be controlled explicitly.

**Comment by GrzegorzSidwa** [comment]
@mykola-mokhnach 
Hm... that's very bad news. 

I faced also another issue with rotating today. I've locked rotation screen on Android, I was not able to manually rotate the screen (on browser). When I run appium command rotate screen orietnation has been changed. Is that also appropriate behavior? If no I will report another issue for it.  Thanks for quit replies.

**Comment by mykola-mokhnach** [comment]
I cannot say for sure if the behaviour is expected or not. I can only say, that no custom APIs are used for orientation change, which means if there are problems then these should be addressed to UIA framework itself.
