### ISSUE TITLE
iPad: getPageSource() does not return all elements.

### ISSUE THREAD

**Issue by jiwrakhkiran** [appium/appium#11063]
## The problem

We are automating new app First time on iPad( though we have have successfully automated same app on iPhone). We started off using Appium Desktop to locate elements and we noticed that some elements are not present in the App Source. Then to be double sure I used getPageSource() and got the same results. 

## Environment

* Appium version: tried with 1.8.1 & 1.8.2-beta
* XCode Version: 9.4.1
* Node.js version : 10.0.0
* Mobile platform/version under test: iPad Pro/Air,  iOS Version: 11.4/11.3 
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Tried with both

## Details
Here is the [App Source](https://gist.github.com/jiwrakhkiran/df67a65f40587c9bcbd33f2587f5cb72)
Here is the screenShot for the reference: Please observe that none of the language elements are present under app source
<img width="1433" alt="screen shot 2018-07-18 at 8 49 29 pm" src="https://user-images.githubusercontent.com/31607877/42892183-d3c98724-8ace-11e8-8038-d428d453404a.png">

## Link to Appium logs

[Appium Logs](https://gist.github.com/jiwrakhkiran/e73a5a9517fcc7010860acde7c390375)

**Comment by mykola-mokhnach** [comment]
The actual page source is returned by WebDriverAgent. I don't think that anything can be changed on Appium side.

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/facebook/WebDriverAgent
