### ISSUE TITLE
iOS picker wheels can not be found.

### ISSUE THREAD

**Issue by Donavan** [appium/appium#11065]
## The problem

Appium can not see picker wheels that were not visible from the start.  Even then, if the wheels are hidden then shown again Appium can not see them

## Environment

* Appium version: 162
* Last Appium version that did not exhibit the issue: N/A
* Desktop OS/version used to run Appium: OSX 10.13.6
* Node.js version (unless using Appium.app|exe): Using Appium App
* Mobile platform/version under test: iOS 11.4
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium app

## Details

We have multiple date pickers that appear when you tap a static text then disappear when done. (See: [These screenshots](https://imgur.com/a/wQm7uGn) Appium does not recognize the pickers as being present unless I first tap the toggle in the emulator by hand before looking for them.  If I interact with the dialog at all via Appium it will not be able to see the pickers in the xml source or inspector (since it uses the XML source).

I've created a [gist](https://gist.github.com/Donavan/f711c11fcb4f8df3a6f597833b7fbfc1) with the XML for when the pickers were exposed by hand, when closed, and when opened again by hand.  The XML for the first and the last should be identical. 

All of the above assumes that I've only used Appium to tap the button that causes this form to appear.  If, instead of stopping at that point, I use Appium to tap the static text to expose the picker wheels the wheels will not show up in the XML source or the inspector. (Screenshot in the imgur link)

**Comment by mykola-mokhnach** [comment]
closed as third party issue

**Comment by Donavan** [comment]
So where should I open an issue?  The XCUI driver page says to open them here...

**Comment by mykola-mokhnach** [comment]
> So where should I open an issue?

Please open it in Apple's bug tracker
