### ISSUE TITLE
IOS : Element visibility is getting changed to false when the element is behind another element

### ISSUE THREAD

**Issue by gkvappium** [appium/appium#11074]
## The problem
![screen shot 2018-07-19 at 6 25 11 pm](https://user-images.githubusercontent.com/27851378/42944067-4cd90d48-8b82-11e8-9b25-12e71c62691b.png)
![screen shot 2018-07-19 at 6 32 01 pm](https://user-images.githubusercontent.com/27851378/42944070-4d1132ea-8b82-11e8-80af-1c6a2c5cd30b.png)

This problem is specific to IOS. Works fine on android. I have a bubble image whose visibility is fine when it is there any where on the screen. But the problem happens when this image gets associated with a sound preset label (Like Sound bass value). Say if we have a label Club and the bubble image is moved to this preset, the visibility changes to false and appium cannot find the element (isDisplayed() returns false. I have attached couple of images. I need the bubble position when it is attached to a preset since I do something like 

    async getBubbleLocationView(){
        let element = await this.bubbleImage();
        return (JSON.stringify(await element.getLocationInView()));
    }

getLocationInView returns the x and y for the bubble image

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOSX 
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: IOS 11.4 (Iphone6)
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

@mykola-mokhnach , any inputs?

**Comment by gkvappium** [comment]
@mykola-mokhnach @imurchie , any inputs?

**Comment by mykola-mokhnach** [comment]
Element visibility is provided by iOS accessibility itself and we cannot influence that. Although, feel free to push a fix if you have any ideas on how this algorithm might be improved: https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Categories/XCUIElement%2BFBIsVisible.m

Closed as third party issue.

**Comment by gkvappium** [comment]
Hi @mykola-mokhnach,

Do you think this issue is related to https://github.com/facebook/WebDriverAgent/pull/794 ?Currently I am on 1.8.0. Should I try with higher version of appium to see if it makes any difference?
