### ISSUE TITLE
Android Capability noSign:true does not work when Uiautomator2 is used.

### ISSUE THREAD

**Issue by shynkevich-alex** [appium/appium#11072]
## The problem

I see in logs that appium resign apk if Automation name is Uiautomator2.
It seems appium should not sign apk for Uiautomator2 if noSign is true

## Environment

* Appium v1.8.2-beta
* Android

## My Capabilities
[Appium]   platformName: android
[Appium]   unlockKey: 12369
[Appium]   unlockType: pattern
[Appium]   autoGrantPermissions: true
[Appium]   automationName: UiAutomator2
[Appium]   deviceName: SM-G935F
[Appium]   newCommandTimeout: 120
[Appium]   noReset: true
[Appium]   noSign: true
[Appium]   platformVersion: 7.0
[Appium]   udid: 9886784f4738414655

## Logs
[ADB] Using apksigner from /Users/shynkevichaliaksandr/Library/Android/sdk/build-tools/28.0.1/apksigner

**Comment by mykola-mokhnach** [comment]
noSign disables signing of the application under test, but not the UIA2 server apk itself. Also, the attached log is not clear. Please properly describe the actual and the expected result

**Comment by shynkevich-alex** [comment]
I have no best logs about this issue.
I just saw  that appium used apksigner.

So if it does not mean that apk was signed close this issue.
