### ISSUE TITLE
Unable to instal Appium through terminal

### ISSUE THREAD

**Issue by maxsudik** [appium/appium#11076]
**Environment:**
Machine Imac
Brew version - Homebrew 1.7.0
Node version - v8.11.3
NPM version - 5.6.0

**Full log**
Last login: Thu Jul 19 11:04:44 on ttys000
QA-iMac:~ Maksym$ brew -v
Homebrew 1.7.0
Homebrew/homebrew-core (git revision b47f; last commit 2018-07-19)
QA-iMac:~ Maksym$ node -v
v8.11.3
QA-iMac:~ Maksym$ npm -v
5.6.0
QA-iMac:~ Maksym$ sudo npm install -g appium
Password:
/usr/local/bin/appium -> /usr/local/lib/node_modules/appium/build/lib/main.js

> appium-chromedriver@4.0.0 install /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver
> node install-npm.js

(node:3505) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/2018619-3505-wnbmgx.578xp'
(node:3505) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3505) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
info Chromedriver Install Installing Chromedriver version '2.38' for platform 'mac' and architecture '64'
info Chromedriver Install Opening temp file to write chromedriver_mac64 to...
Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/2018619-3505-njnvk1.qi7zm'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-chromedriver@4.0.0 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium-chromedriver@4.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Maksym/.npm/_logs/2018-07-19T18_22_03_422Z-debug.log
QA-iMac:~ Maksym$

**Comment by mykola-mokhnach** [comment]
Make sure that `/usr/local/lib` is writeable for the current user
