### ISSUE TITLE
Unable to verify 'Setting up iOS Real Devices Tests with XCUITest'

### ISSUE THREAD

**Issue by maxsudik** [appium/appium#11077]
Environment Mac
appium-doctor - all installed
all dependencies were installed

The problem is - when I run "xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' test" using device ID, I have next error:

Testing failed:
	'RoutingHTTPServer/RoutingConnection.h' file not found
** TEST FAILED **

The following build commands failed:
	CompileC /Users/Maksym/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Intermediates.noindex/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/Objects-normal/arm64/FBWebServer.o WebDriverAgentLib/Routing/FBWebServer.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Also can't get e certificate for WebDriverAgentLib, but I have it for WebDriverAgentRun
Screens attached.
![screen shot 2018-07-19 at 4 52 03 pm](https://user-images.githubusercontent.com/40281293/42975994-24eb9034-8b74-11e8-8f7d-dbe0094ef57d.png)
![screen shot 2018-07-19 at 4 51 45 pm](https://user-images.githubusercontent.com/40281293/42975995-25287a62-8b74-11e8-84f3-772c138cdf3a.png)

**Comment by mykola-mokhnach** [comment]
Did you run bootstrap script to fetch carthage dependencies first?

**Comment by maxsudik** [comment]
@mykola-mokhnach do you mean this one 

mkdir -p Resources/WebDriverAgent.bundle
    ./Scripts/bootstrap.sh -d

If this is one, I tun it.

**Comment by mykola-mokhnach** [comment]
Can you provide the full xcodebuild log?

**Comment by maxsudik** [comment]
So far I have this log in my terminal:

Last login: Fri Jul 20 13:59:15 on ttys000
QA-iMac:~ Maksym$ which appium
/usr/local/bin/appium
QA-iMac:~ Maksym$ cd /usr/local//lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
QA-iMac:WebDriverAgent Maksym$  mkdir -p Resources/WebDriverAgent.bundle
QA-iMac:WebDriverAgent Maksym$ ./Scripts/bootstrap.sh -d
Fetching dependencies
*** Checking out RoutingHTTPServer at "v1.0.1"
*** Checking out YYCache at "1.0.5"
*** xcodebuild output can be found in /var/folders/lc/hchmqy350cs21gcyy0fz08yc0000gq/T/carthage-xcodebuild.E0yM30.log
*** Downloading RoutingHTTPServer.framework binary at "v1.0.1"
*** Downloading YYCache.framework binary at "v1.0.5"
QA-iMac:WebDriverAgent Maksym$ open .
QA-iMac:WebDriverAgent Maksym$ 

After I opened WebDriverAgent.xcodeproj and build it in Xcode, I have I fail, log and screen - attached:

/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

#import "FBWebServer.h"

#import <RoutingHTTPServer/RoutingConnection.h>
#import <RoutingHTTPServer/RoutingHTTPServer.h>

#import "FBCommandHandler.h"
#import "FBErrorBuilder.h"
#import "FBExceptionHandler.h"
#import "FBRouteRequest.h"
#import "FBRuntimeUtils.h"
#import "FBSession.h"
#import "FBUnknownCommands.h"
#import "FBConfiguration.h"
#import "FBLogger.h"

#import "XCUIDevice+FBHelpers.h"

static NSString *const FBServerURLBeginMarker = @"ServerURLHere->";
static NSString *const FBServerURLEndMarker = @"<-ServerURLHere";
![screen shot 2018-07-20 at 2 09 55 pm](https://user-images.githubusercontent.com/40281293/43025440-9e42f6a4-8c26-11e8-8d60-42d9de446fd7.png)

**Comment by mykola-mokhnach** [comment]
Try to reset Xcode caches. Usually such errors are shown if carthage fails to download dependencies

**Comment by maxsudik** [comment]
How to do it right? 
Do I need to enter particular command into the terminal , or do it manually in the Xcode?

**Comment by maxsudik** [comment]
Also I'm not sure whether it is important but now I have WebDriverAgent on My iPad, if i try to launch it - I just see only black screen.
Also, there is no WebDriverAgent in the 'Permission' section of the device

Screens are attached.
![image-1-24](https://user-images.githubusercontent.com/40281293/43028046-5d85d67a-8c32-11e8-9078-e7c7221e781a.jpg)
![image-1-25](https://user-images.githubusercontent.com/40281293/43028047-5f4aca1a-8c32-11e8-8e1f-d3c726fc7d7b.jpg)

Please help

**Comment by mykola-mokhnach** [comment]
What do you expect to see instead? WDA is just a proxy and provides REST APIs. The described behaviour is expected

**Comment by maxsudik** [comment]
I expected to see what I saw in the installation manual:
" Test Suite 'All tests' started at 2017-01-23 15:49:12.585
    Test Suite 'WebDriverAgentRunner.xctest' started at 2017-01-23 15:49:12.586
    Test Suite 'UITestingUITests' started at 2017-01-23 15:49:12.587
    Test Case '-[UITestingUITests testRunner]' started.
        t =     0.00s     Start Test at 2017-01-23 15:49:12.588
        t =     0.00s     Set Up"

I would also appreciate if you can share a ling with the next steps to create an automation test.

I mean I have all these parts of the IDE, I have driver to test application on the real device, but how can I start inspect objects of the application and invoke interaction  between my future test and the application?

But in case if you say it's expected behaviour - issue could be closed

Thank you for your patience.

**Comment by mykola-mokhnach** [comment]
https://github.com/facebook/WebDriverAgent/wiki/Starting-WebDriverAgent
