### ISSUE TITLE
WDA is removed after certain amount of time using Appium on real device. Is there a way to automate building WDA before running a test on real device? 

### ISSUE THREAD

**Issue by vytran9599** [appium/appium#11088]
I've been trying to find a workaround to keep WDA on my iPad, even using webDriverAgentUrl and WDALocalPort. I want to be able to build WDA on the iPad when executing my scripts. Is there a way to automate that?

**Comment by mykola-mokhnach** [comment]
Isn't it duplicate of https://github.com/appium/appium/issues/11003 ?

**Comment by vytran9599** [comment]
@mykola-mokhnach Yes, I tried the suggested solution to use webDriverAgentUrl with appium@beta (appium 1.8.2-beta) but it failed to connect to WDA with the webDriverAgentUrl capability.

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/wda-custom-server.md
