### ISSUE TITLE
Appium failed to tap at iOS 

### ISSUE THREAD

**Issue by vslm698-p** [appium/appium#11080]
## The problem

When trying to perform tap action with coordinate button in appium-desktop, it reports that it meets  an unknown server-side error(as below picture)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable): yes
* Desktop OS/version used to run Appium: 10.13.6
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 11.3
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium-desktop

## Details
I first met this issue when coding with python-client, during debugging, I found it also can be reproduced at appium-desktop, to make it simple, let's use appium-desktop app to have a check. 
When tap on real device with coordinate button, it reports that it meets an unknown server-side error.

![image](https://note.youdao.com/yws/api/personal/file/WEBced196a1d44d7951db8b812415531253?method=download&shareKey=86f9e2e7250b19f91dc82b71694eb405)

## Link to Appium logs

[GIST](https://gist.github.com/vslm698-p/f9ffbd5f10cb7f6a1507a0ce8d8a2e86)

**Comment by mykola-mokhnach** [comment]
> [debug] [JSONWP Proxy] Got response with status 200: {"value":"Unhandled endpoint: /session/F725B80C-BEC0-40AD-A044-7F287E95A484/wda/touch/perform -- http://localhost:8100/ with parameters {\n    wildcards =     (\n        \"session/F725B80C-BEC0-40AD-A044-7F287E95A484/wda/touch/perform\"\n    );\n}","sessionId":"F725B80C-BEC0-40AD-A044-7F287E95A484","status":1}


The WebDriverAgent binary looks outdated. Make sure it is up to date on the device under test and reset Xcode caches

**Comment by vslm698-p** [comment]
WebDriverAgent is built with the latest code of Facebook(e92bce2de3200e1145b79f12709e17551b284bf4), and I will reset Xcode caches and will update later.

**Comment by mykola-mokhnach** [comment]
You must use WDA built from our local fork: https://github.com/appium/WebDriverAgent

The one from Facebook won't work with Appium.
Closed as not an issue

**Comment by vslm698-p** [comment]
Thanks @mykola-mokhnach, after switched to the local fork, Appium works well:)
