### ISSUE TITLE
Unable to take a screenshot in Chrome/Android

### ISSUE THREAD

**Issue by vmuzikar** [appium/appium#11083]
## The problem

I'm using Appium Java Client with Chrome on Android to test a web app. When I try to take a screenshot the test gets stuck and eventually timeouts. Looking to the log, it seems like the Appium Server never receives a proper response after requesting the screenshot.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1, 1.8.2-beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 10.13.6
* Node.js version (unless using Appium.app|exe): 8.11.3
* Mobile platform/version under test: Android 8.0, 8.1
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

https://gist.github.com/vmuzikar/33b0f34f8ef383d2711803d37d902474

## Code To Reproduce Issue [ Good To Have ]

```java
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "android");
capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "chrome");
capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "doesnt-matter");
capabilities.setCapability(AndroidMobileCapabilityType.AVD, "Nexus_5X_API_26");
capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "UiAutomator2");
capabilities.setCapability("showChromedriverLog", "true");

driver = new AndroidDriver(capabilities);
driver.navigate().to("http://www.google.com");

TakesScreenshot screenshotDriver = (TakesScreenshot) driver;
File file = screenshotDriver.getScreenshotAs(OutputType.FILE);
```

**Comment by mykola-mokhnach** [comment]
Try `nativeWebScreenshot` capability

**Comment by vmuzikar** [comment]
@mykola-mokhnach Thanks! That worked but takes screenshot of the whole screen (obviously), not just the viewport. Shouldn't also work taking screenshot directly through chromedriver?

**Comment by mykola-mokhnach** [comment]
That must be chromedriver issue. Please report it to their bugtracker with all the necessary logs
