### ISSUE TITLE
[appium-base-driver] [iOS] Appium could not proxy response

### ISSUE THREAD

**Issue by isnifer** [appium/appium#11081]
## The problem

Today my daily tests have failed on the CI. Checked locally — the same result.
Checked appium repos — the latest update 17-18 hrs ago :)

## Environment

* Appium version (or git revision) that exhibits the issue: **1.8.1**
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: **macOS High Sierra 10.13.6 (17G65)**
* Node.js version (unless using Appium.app|exe): **v9.11.2**
* Mobile platform/version under test: **iOS**
* Real device or emulator/simulator: **Simulator**
* Appium CLI or Appium.app|exe: **CLI**

## Details

When appium **Executing command 'proxyReqRes'** it got next error:
`Encountered internal error running command: Error: Could not proxy. Proxy error: Could not find :session section for url: /wd/hub/session/03e83d5c-2198-4323-b879-a922fa782ea6/element/10000000-0000-0000-53D1-000000000000/displayed`

## Link to Appium logs

[GIST](https://gist.github.com/isnifer/af037134f7ede64f860a987adfc81c48)

## Code To Reproduce Issue [ Good To Have ]

I just started my tests

### Looks like the latest changes broke my tests
https://github.com/appium/appium-base-driver/commit/0fd07f93321c402b1613a711caf95187018a1e02.

### Line in appium-base-driver that have failed: 
https://github.com/appium/appium-base-driver/blob/master/lib/protocol/protocol.js#L450

**Comment by mykola-mokhnach** [comment]
Yes, this problem started to happen after the recent base driver bump. We are going to address it soon.

**Comment by imurchie** [comment]
I've reverted the commit and published `appium-base-driver@3.2.0`. When I have the time I'll explore why it was broken and re-implement.

Thanks!

**Comment by isnifer** [comment]
Thank you @mykola-mokhnach @imurchie 👍
