### ISSUE TITLE
Appium iOS with AWS device Farm

### ISSUE THREAD

**Issue by kuchmiyalex** [appium/appium#11098]
## The problem

I want to configure AWS Device Farm with existing Appium UI tests. 
First of all there's no guide how to achieve this, right now i'm just guessing how to configure capabilities. Considering that device and iOS version should be coming from AWS configuration, where should be 'app' path pointing to?
I tried with './App.ipa" but error is "App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name." Looks like Appium can't work with IPA files?
Please suggest a solution for AWS + python + Appium + iOS.

**Comment by mykola-mokhnach** [comment]
Please use appium forum to ask questions. this is the place for issues.
