### ISSUE TITLE
Can't run test on real device with Appium

### ISSUE THREAD

**Issue by dmitrykorj** [appium/appium#11097]
## The problem

Can't run tests!

## Environment

* Appium version 1.8.1 command for run `appium`
* Node 10.6.0
* ios_webkit_debug_proxy 1.8 command for run `ios_webkit_debug_proxy -c my_udid:27753`
* libimobiledevice v1.2.0
* libplist v2.0.0
* Real device : iPhone 6 (11.0)
* MacOS 10.13.6

## My logs
[Appium Server](https://gist.github.com/dmitrykorj/138e74b77e1bd99efa3f27aa0369a600)

**Comment by mykola-mokhnach** [comment]
Try appium@beta

**Comment by messianic** [comment]
Hey @dmitrykorj , have you signed your WDA to run on real device. Follow the steps below:
[here](https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md)

**Comment by dmitrykorj** [comment]
@mykola-mokhnach works fine! thank you very much! 
@messianic yep. Sure
