### ISSUE TITLE
Android Fullscreen dialog not showing in uiautomator dump

### ISSUE THREAD

**Issue by vrunoa** [appium/appium#11099]
## The problem

When running an Android test on a clean Emulator or Real Device a Dialog appears if it's the first time you run your app in fullscreen mode. This dialog blocks the interaction with your app and cannot be close since when trying to get the uiaumator dump to find an ID, or XPATH to interact, it doesnt show anything about this dialog. 

<img width="1076" alt="screen shot 2018-07-23 at 4 42 31 pm" src="https://user-images.githubusercontent.com/329957/43104374-9d2406d6-8ea7-11e8-82b1-f9a3b35b1c90.png">

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable): Seems to have never worked
* Desktop OS/version used to run Appium: MacOS
* Node.js version (unless using Appium.app|exe): v8.1.0
* Mobile platform/version under test: Android 7.0 (API 24)
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Both

## Code To Reproduce Issue [ Good To Have ]

This can simply be done with any app that goes to fullscreen. If needed I can provide an app withi this feature.

**Comment by mykola-mokhnach** [comment]
There is nothing much, that can be done on Appium side. We just show the stuff, which the application itself provides to the accessibility framework. I would check with application developers whether it is possible to provide some workaround there.

**Comment by vrunoa** [comment]
@mykola-mokhnach any idea why would this dialog not show in the uiautomator dump? For ex. the welcome dialog is accesibld via the uiautomator dump, but apparently this fullscreen dialog it isent. Should we create a ticket on Android?

**Comment by vrunoa** [comment]
@mykola-mokhnach do you know if we can close a window via adb?

```
Window #8 Window{890fd36 u0 ImmersiveModeConfirmation}:
    mDisplayId=0 stackId=0 mSession=Session{452763e 1654:1000} mClient=android.view.ViewRootImpl$W@6221ed1
    mOwnerUid=1000 mShowToOwnerOnly=false package=android appop=NONE
    mAttrs=WM.LayoutParams{(0,0)(fillxfill) sim=#20 ty=2014 fl=#1000108 pfl=0x10 fmt=-3 wanim=0x10302f7 vsysui=0x300}
    Requested w=1080 h=1920 mLayoutSeq=152
    mBaseLayer=171000 mSubLayer=0 mAnimLayer=171000+0=171000 mLastLayer=171000
    mToken=WindowToken{20c3310 null}
    mRootToken=WindowToken{20c3310 null}
    mViewVisibility=0x0 mHaveFrame=true mObscured=false
    mSeq=0 mSystemUiVisibility=0x300
    mGivenContentInsets=[0,0][0,0] mGivenVisibleInsets=[0,0][0,0]
    mTouchableInsets=3 mGivenInsetsPending=false
    touchable region=SkRegion((0,0,1080,654))
    mMergedConfiguration={1.0 310mcc260mnc [en_US] ldltr sw411dp w411dp h659dp 420dpi nrml port finger qwerty/v/v dpad/v s.5}
    mHasSurface=true mShownPosition=[0,0] isReadyForDisplay()=true hasSavedSurface()=false mWindowRemovalAllowed=false
    mFrame=[0,0][1080,1920] last=[0,0][1080,1920]
    Frames: containing=[0,0][1080,1920] parent=[0,0][1080,1920]
        display=[0,0][1080,1920] overscan=[0,0][1080,1920]
        content=[0,63][1080,1794] visible=[0,0][1080,1920]
        decor=[0,0][1080,1920]
        outset=[0,0][0,0]
    Cur insets: overscan=[0,0][0,0] content=[0,63][0,126] visible=[0,0][0,0] stable=[0,63][0,126] surface=[0,0][0,0] outsets=[0,0][0,0]
    Lst insets: overscan=[0,0][0,0] content=[0,63][0,126] visible=[0,0][0,0] stable=[0,63][0,126] physical=[0,0][0,0] outset=[0,0][0,0]
    WindowStateAnimator{1b4a80e ImmersiveModeConfirmation}:
      mSurface=Surface(name=ImmersiveModeConfirmation)
      Surface: shown=true layer=171000 alpha=1.0 rect=(0.0,0.0) 1080.0 x 1920.0
```

**Comment by mykola-mokhnach** [comment]
You could try to tap by coordinates.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
