### ISSUE TITLE
Appium takes a long time to get ADB logs

### ISSUE THREAD

**Issue by shreyasshenoy** [appium/appium#11095]
## The problem

We are testing apps based on unity, and as a result uielements don't show up on the UIinspector. So as a work around, we enable unity logs which we can obtain from ADB, which in turn contains the information on the cordinates of the UI elements. This allows us to click and perform other actions on the app. However from the latest Appium build, the process of obtaining these logs have been increased to more than a minute for some reason. leading to an exponential increase in our test cases. Also for some reason the relaxed security flag has to be set to true to get logs now.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2
* Desktop OS/version used to run Appium: Mac Os 10.4
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Real Device

**Comment by mykola-mokhnach** [comment]
We cannot help much without having server logs (preferably with timestamps).

Also, the recent server versions can broadcast logs via web socket with (almost) realtime performance. See  https://github.com/appium/java-client/blob/345676a1207fc93a3de86b6dac279048c7b00962/src/test/java/io/appium/java_client/android/AndroidLogcatListenerTest.java
