### ISSUE TITLE
Is it possible to run IOS application without Xcode project, using Appium and simulator?

### ISSUE THREAD

**Issue by maxsudik** [appium/appium#11092]
I'm faced with a problem, to run application downloaded from the internet.

If I don't have any Xcode files or projects, how can I do it?

Just for now, if I set a path to the application and receive 

XCUITest] Simulator architecture appears to be unsupported by the '/var/folders/fl/88s8bv_57w5508kz9r2bwlhw0000gp/T/2018621-29283-kb1bu4.p028g/Payload/WhatsApp.app' application. Make sure the correct deployment target has been selected for its compilation in Xcode.

And don't close the issue, before it is resolved...

**Comment by imurchie** [comment]
You cannot, no. First off, without Xcode there are no simulators. Then there is the entire apparatus of running tests, which uses the tools in Xcode. Those _can_ be reverse engineered, but it would be much more work than downloading Xcode, which is both free and easy.

You also will probably not be able to automate a random app downloaded from the internet. S
