### ISSUE TITLE
Unable to take WebElement screenshot UiAutomator2

### ISSUE THREAD

**Issue by sumanguduru** [appium/appium#11094]
## The problem
Getting below error while taking WebElement screenshot
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 404 - "unknown command: session/09ffa20a2f2e3200e41f896faa98fe2e/element/0.04131264370898369-1/screenshot" (WARNI

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.2 beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: mac 
* Node.js version (unless using Appium.app|exe): v10.5.0
* Mobile platform/version under test: Android, 7.0
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/sumanguduru/0fc008475e38f00de3b1df9effe5768e

## Code To Reproduce Issue [ Good To Have ]

File scrFile = element.getScreenshotAs(OutputType.FILE);

**Comment by mykola-mokhnach** [comment]
This is W3C<>JSONWP protocols translation issue. 
https://github.com/appium/appium-base-driver/pull/238 should fix it as soon as it is merged (and if chromedriver supports element screenshot). For now you could set `MobileCapabilityType.FORCE_MJSONWP` to true if you use java client and see if it helps

**Comment by sumanguduru** [comment]
Hi For XCUITest also im unable to get the screenshot its throwing below error.
and there is no getElementScreenshot.js file in atoms folder.

 Error: Unable to load Atom 'getElementScreenshot' from file '/usr/local/lib/node_modules/appium/node_modules/appium-remote-debugger/atoms/getElementScreenshot.js'

**Comment by imurchie** [comment]
There is not, and has never been, a "get element screenshot" capability in MobileSafari. This is a mistake to not just throw an error saying it doesn't exist.

**Comment by sumanguduru** [comment]
Can we request get element screenshot feature this will be helpful for visual testing.

**Comment by imurchie** [comment]
You can request it.

It would be unreliable, though, since the only way would be to somehow relate the webview element to a native element (which can be done, but only for certain types of elements) and then do the native screenshot on that element.

**Comment by sumanguduru** [comment]
@mykola-mokhnach  @imurchie  
Can you please suggest any work around to get the particular element screenshot

**Comment by imurchie** [comment]
My only suggestion would be to go into the Native context, and try to find the element (get the source to see what, if anything, it is showing up as) and then use the native method.

**Comment by mykola-mokhnach** [comment]
urls replacement fix has been deployed into appium@beta. Although if chromedriver itself does not implement such endpoint then there's nothing that can be done on Appium side.
