### ISSUE TITLE
[Android] After upgrade from appium java client 5.0.4 to 6.0.1 not able to scroll in touch action

### ISSUE THREAD

**Issue by lamquangthanh** [appium/appium#11096]
## The problem
Not able to scroll in touch action after upgrade java client to 6.0.1
**5.0.4
new TouchAction(driver).press(startx, starty).waitAction(Duration.ofSeconds(duration)).moveTo(endx, endy).release().perform();
**6.0.1
new TouchAction(driver).press(new PointOption().withCoordinates(startx, starty)).waitAction(waitOptions(Duration.ofMillis(duration))).moveTo(point(endx, endy)).release().perform();

**==> Code run without error but not have action in mobile screen.**

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1 / java client 6.0.2
* Last Appium version that did not exhibit the issue (if applicable): 1.8.1 / java client 5.0.4
* Desktop OS/version used to run Appium: Win 10
* Node.js version (unless using Appium.app|exe):  6.1.0 
* Mobile platform/version under test: Android 7
* Real device or emulator/simulator: real device/Nexus 6
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs
[W3C] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/c4ea4382-7441-4695-a243-2fa                                                               00ba77fc1/window/current/size] to [GET http://localhost:8200/wd/hub/session/dd88                                                               e9fb-209f-4f09-8a90-7727abc00078/window/current/size] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"dd88e9fb-                                                               209f-4f09-8a90-7727abc00078\",\"status\":0,\"value\":{\"height\":2392,\"width\":                                                               1440}}"
[JSONWP Proxy] Replacing sessionId dd88e9fb-209f-4f09-8a90-7727abc00078 with c4e                                                               a4382-7441-4695-a243-2fa00ba77fc1
[HTTP] <-- GET /wd/hub/session/c4ea4382-7441-4695-a243-2fa00ba77fc1/window/curre                                                               nt/size 200 17 ms - 100
[HTTP]
[HTTP] --> POST /wd/hub/session/c4ea4382-7441-4695-a243-2fa00ba77fc1/touch/perform
[HTTP] {"actions":[{"action":"press","options":{"x":1196,"y":1674}},{"action":"wait","options":{"ms":4}}                                       ,{"action":"moveTo","options":{"x":1196,"y":717}},{"action":"release","options":{}}]}
[debug] [W3C] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":1196,"y"                                       :1674}},{"action":"wait","options":{"ms":4}},{"action":"moveTo","options":{"x":1196,"y":717}},{"action":                                       "release","options":{}}],"c4ea4382-7441-4695-a243-2fa00ba77fc1"]
[debug] [JSONWP Proxy] Proxying [POST /touch/perform] to [POST http://localhost:8200/wd/hub/session/dd88                                       e9fb-209f-4f09-8a90-7727abc00078/touch/perform] with body: {"startX":1196,"startY":1674,"endX":1196,"end                                       Y":717,"steps":0}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"dd88e9fb-209f-4f09-8a90-7727abc00078"                                       ,"status":0,"value":true}
[debug] [MJSONWP] Responding to client with driver.performTouch() result: true
[HTTP] <-- POST /wd/hub/session/c4ea4382-7441-4695-a243-2fa00ba77fc1/touch/perform 200 810 ms - 76
[HTTP]

**Comment by mykola-mokhnach** [comment]
Try to increase the duration of wait action to at least 500-600ms and compare the server log generated by the previous client and the current one. Otherwise I don't see any issues.

**Comment by lamquangthanh** [comment]
@mykola-mokhnach  i see my mistake, change ofMillis(duration)--> ofSeconds(duration).
