### ISSUE TITLE
--log-levels is not usefully documented.

### ISSUE THREAD

**Issue by sleekweasel** [appium/appium#11107]
The 'log-level' options are not displayed usefully.

Are info and info:info are the same? Does debug:info means 'you're welcome to guess which levels live between debug and info'? Why are 'debug:warn' and 'warn:debug' are both listed, if it's a range?

Please change it to something like

--log-level warn:debug sends different levels of logging to console:logfile where debug, info, warn, error are progressively less verbose. If only one level is specified, both console and logfile get it.

**Comment by sleekweasel** [comment]
Or even this, helpfully hidden in the code as a comment:

    // --log-level arg can optionally provide diff logging levels for console and file  separated by a colon

**Comment by sleekweasel** [comment]
Perhaps:

--log-level warn:debug sends different levels of logging to console:logfile where debug, info, warn, error are progressively less verbose. If only one level is specified, both console and logfile get it.

**Comment by imurchie** [comment]
Thanks for this suggestion! Always great to get feedback about the usability of the docs (since the devs are a little to close to it to make it clear, sometimes).

**Comment by dpgraham** [comment]
Closing as fixed.
