### ISSUE TITLE
StaleElementReferenceError after page reload when switched to frame

### ISSUE THREAD

**Issue by tonyhignett** [appium/appium#11102]
## The problem

In iOS, if you've switched to a frame and a new page loads outside of Appium, then executing javascript fails in the new page.

e.g. in python
```
>>> driver.get("https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_iframe")
>>> driver.switch_to.frame(0)
[reload page manually]
>>> driver.execute_script("return document.readyState")
WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: StaleElementReferenceError: Element does not exist in cache
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: macOS High Sierra
* Node.js version (unless using Appium.app|exe): v9.4.0
* Mobile platform/version under test: iOS 11.3
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI

## Details

Appium keeps trying to apply the frame to the atom, but of course it makes no sense any more.

I'm not sure whether this is a bug or not, but
- it causes tests to die when the page under test behaves unexpectedly (i.e. causes a navigation when you don't expect it to);
- it isn't a problem when using chromedriver - you're left in the default content of the new page. 

## Link to Appium logs

https://gist.github.com/tonyhignett/02291cd79d906834f40b806eebdf180b

## Code To Reproduce Issue [ Good To Have ]

See above.

**Comment by bhusingh** [comment]
Hi, I am using Appium desktop 1.8.2 and facing the same issue. Whenever I refresh the page or open a new page, StaleElementReferenceError exception is thrown. Could you please tell which appium version should I use to fix this issue?
I have opened following issue in appium forum but didn't get any response yet:
https://discuss.appium.io/t/staleelementreferenceexception-in-ios-real-device/26648
I also want to understand how appium-xcuitest-driver uses appium-ios-driver. Any documentation around it would be helpful. Thanks in advance.

**Comment by bhusingh** [comment]
Also please tell if there is any other way to clear frames using JSExecutor and without using the latest version of appium because my org is not using latest version of appium and it is an expensive(time taking) task to upgrade appium.
