### ISSUE TITLE
Full Reset capability is not working in Appium 1.8.1 in real device

### ISSUE THREAD

**Issue by alkaffkhanvrv** [appium/appium#11104]
I am trying to uninstall the app after the test execution completed using fullReset as true

```
capabilities.setCapability(MobileCapabilityType.FULL_RESET, true);
capabilities.setCapability(MobileCapabilityType.VERSION, deviceConfig.getPlatformVersion());
        capabilities.setCapability(DeviceConfig.KEY_DEVICE_NAME, deviceConfig.getDeviceName());
        capabilities.setCapability(DeviceConfig.KEY_PLATFORM_NAME, deviceConfig.getPlatformName());
        capabilities.setCapability(MobileCapabilityType.APP, getAppPathFromServer(appName));
        capabilities.setCapability(DeviceConfig.KEY_CLEAR_SYSTEM_FILES, true);
        capabilities.setCapability(MobileCapabilityType.UDID, deviceConfig.getDeviceUdid());
        capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.IOS_XCUI_TEST);
```
**But it is not uninstalling the app after the test executed**

**Appium version 1.8.1**
**Device : iPhoneX**
**OS version 11.4.1**

Appium log is [here](https://gist.github.com/alkaffkhanvrv/3987ca8a8e985f141056ee2b348d7765)

**Note: It is working fine in Android**

**Comment by alkaffkhanvrv** [comment]
Then how can I uninstall the app after test execution? May I need to use driver.removeApp(bundleId)?

**Comment by mykola-mokhnach** [comment]
yes you can use this API if you need it. Appium does not remove the app after the session is stopped except if you set `resetOnSessionStartOnly` to false, which is going to increase your suite execution time.
