### ISSUE TITLE
Unhandled rejection Error: UiAUtomator shut down unexpectedly

### ISSUE THREAD

**Issue by sridharrajendran1** [appium/appium#11105]
## The problem

When I run the test second time from IDE, getting the error as "Unhandled rejection Error: UiAUtomator shut down unexpectedly"

## Environment

* Appium version - 1.8.1
* Desktop OS/version used to run Appium - Mac OS HighSierra 10.13.1
* Node.js version: v8.9.0
* Mobile platform/version under test: Android/8.0 and above
* Real device or emulator/simulator: Real Device - Samsung S9, Pixel 2XL
* Appium GUI: 1.4.1

## Details

Steps
1. Start the Appium server  using **appium -a 127.0.0.1 -p 4723**
2. Trigger the test in IDE
3. Stop the test
4. Re-run the test again
5. Error : Unhandled rejection Error: UiAUtomator shut down unexpectedly, will be thrown

## Link to Appium logs

https://gist.github.com/sridharrajendran1/7de037be537a189f213b16d7dfbc2b8c

**Comment by sridharrajendran1** [comment]
After adding UIAutomator2 it is working. Could you pls explain how come it is related to UIAutomator2 capability?

**Comment by mykola-mokhnach** [comment]
UIAutomator1, which is used by default is obsolete and is only recommended for legacy Android version (5 and older)
