### ISSUE TITLE
StartRecordingScreen on specific Android device fails

### ISSUE THREAD

**Issue by notihs** [appium/appium#11117]
## The problem
Trying to record one specific device works for a bit and then stops with an exception on appium server.
The device in which this happens is a VDF 710 with Android 7.0.
Using the exact same code, but with another device (Sony FB331, Android 8.0) it works just fine.

## Environment

* Appium 1.8.2-beta

## Link to Appium logs

https://gist.github.com/notihs/7f19a7d2d72c3f426eed96317ff5bce0

## Code To Reproduce Issue [ Good To Have ]
Simply calling `driver.startRecordingScreen();`

**Comment by notihs** [comment]
If I start it manually, only after the process has stopped.

**Comment by mykola-mokhnach** [comment]
ok, I'll change the algorithm to accept any file size

**Comment by mykola-mokhnach** [comment]
The fix has been published in appium@beta
