### ISSUE TITLE
Safari on the iOS real device end unexpectedly after navigating to a specified URL

### ISSUE THREAD

**Issue by dustin71728** [appium/appium#11119]
## The problem

Everything works fine until Safari navigates to the specified URL. Remote Debugger's log shows that Safari has loaded the content, but what I saw is Safari's location bar changes to the URL. Before rendering the entire page, it ends unexpectedly. When the testing script tries to fetch URL's title, it returns the title of https://appium.io ( safariInitialUrl is absent in the capability settings ), not the title of the specified URL.

Other platforms didn't have this issue and can resolve the expected title.

## Environment

* Appium: 1.8.2-beta 
* Desktop OS/Version: macOS High Sierra 10.13.4
* Node.js version: 9.3.0
* Mobile platform/version: iOS 11.4
* Real device or emulator/simulator: Real device iPhone 5s
* Java Version: java 10.0.1 2018-04-17
* Appium CLI or Appium.app|exe: Appium CLI

## Details

I use 1.8.2-beta instead of 1.8.1 because of the issue https://github.com/facebook/WebDriverAgent/issues/827.

The default initial URL ( https://appium.io ) is fully rendered, but this is not the case when navigating the testing URL.

## Link to Appium logs

https://gist.github.com/dustin71728/3bc3f83edd91dbc24ffe38996d9a9271

## Code To Reproduce Issue [ Good To Have ]

My script(webdriver.io):

```
const assert = require('assert');

describe('webdriver.io page', function () {
  it('should have the right title - the fancy generator way', function () {
    browser.url('http://webdriver.io');
    var title = browser.getTitle();
    assert.equal(title, 'WebdriverIO - WebDriver bindings for Node.js');
  });
});

```
wdio.conf.js
```
exports.config = {
  host: '172.21.20.4',
  port: 4444,
  path: '/wd/hub',
  specs: [
    './e2etest/specs/**/*.js'
  ],
  exclude: [
  ],
  maxInstances: 10,
  capabilities: [
    {
      maxInstances: 1,
      platformName: 'linux',
      browserName: 'firefox'
    },
    {
      maxInstances: 1,
      platformName: 'linux',
      browserName: 'chrome'
    },
    {
      maxInstances: 1,
      platformName: 'mac',
      browserName: 'safari'
    },
    {
      maxInstances: 1,
      platformName: 'windows',
      browserName: 'internet explorer',
    },
    {
      maxInstances: 1,
      platformName: 'windows',
      browserName: 'MicrosoftEdge',
    },
    {
      maxInstances: 1,
      platformName: 'Android',
      browserName: 'chrome',
      deviceName: 'Android Emulator',
      platformVersion: 'P',
      automationName: 'UiAutomator2'
    },
    {
      platformName: 'iOS',
      platformVersion: '11.4',
      automationName: 'XCUITest',
      browserName: 'safari',
      deviceName: 'iPhone',
      maxInstances: 1,
      seleniumProtocol: 'WebDriver',
      bundleid: 'com.apple.mobilesafari',
      wdaStartupRetries: 1,
      udid: '.......',
      startIWDP: true,
      xcodeOrgId: '.........',
      xcodeSigningId: 'iPhone Developer'
    }
  ],
  sync: true,
  logLevel: 'verbose',
  coloredLogs: true,
  deprecationWarnings: true,
  bail: 0,
  screenshotPath: './e2etest/errorShots/',
  baseUrl: 'http://localhost',
  waitforTimeout: 10000,
  connectionRetryTimeout: 300000,
  connectionRetryCount: 1,
  framework: 'mocha',
  reporters: ['spec', 'allure', 'mochawesome'],
  reporterOptions: {
    allure: {
      outputDir: './e2etest/reports/allure',
    },
    mochawesome: {
      outputDir: './e2etest/reports/mochawesome',
    },
  },
  mochaOpts: {
    ui: 'bdd',
    timeout: 300000,
  },
}
```

**Comment by mykola-mokhnach** [comment]
I don't think there's anything there we can fix on Appium side. Closed as third party issue.
