### ISSUE TITLE
AppiumDriver throws error as 'Error: Cannot get screenshot data because of 'Unable to get file size for '/data/local/tmp/screenshot.png': Unable to parse size from list output: '-rw-rw-r--    1 root     root. Make sure the 'LayoutParams.FLAG_SECURE' is not set for the current view

### ISSUE THREAD

**Issue by yaseenmd** [appium/appium#11116]
## The problem

I am trying to locate the elements in my app. I am using 'Appium Desktop' to locate the elements in my app. but the driver throws this error

:Error: Cannot get screenshot data because of 'Unable to get file size for '/data/local/tmp/screenshot.png': Unable to parse size from list output: '-rw-rw-r--    1 root     root         18172 Jul 26 15:16 /data/local/tmp/screenshot.png''. Make sure the 'LayoutParams.FLAG_SECURE' is not set for the current view

## Environment

* Appium version (or git revision) that exhibits the issue: 
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:  Android 6.0
* Real device 
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/yaseenmd/7baa14632652f49a71112a66e77a743a!

**Comment by yaseenmd** [comment]
i have noticed that screenshot has been taken and it is greater than zero size. UIdump.xml is missing

**Comment by mykola-mokhnach** [comment]
Switch to UiAutomator2
