### ISSUE TITLE
[Appium Install on Windows] WinAppDriver not being auto-installed anymore 

### ISSUE THREAD

**Issue by liquidomgenes** [appium/appium#11110]
Hi, 

It looks like with the latest Appium install (whether through NPM or the GUI), WinAppDriver is not being auto-installed anymore, nor is there an option to install it. 

Is there a reason for this?

**Comment by dpgraham** [comment]
Was there a certain version where this stopped working?

**Comment by yodurr** [comment]
which Appium version?  I wonder if the change to only pull 1.x has anything to do with this (I don't see why it would, but little if anything should have changed with this code over recent months)

**Comment by yodurr** [comment]
I believe the issue is identified.  Fix PR is submitted.
