### ISSUE TITLE
'WebDriver' object has no attribute 'find_element_by_image'

### ISSUE THREAD

**Issue by messianic** [appium/appium#11115]
## The problem

Unable to use findElementByImage locator(python client).

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS High Sierra
* Node.js version (unless using Appium.app|exe): 8.11.1
* Mobile platform/version under test: Android/7.1.1
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: Appium CLI

[python_findByImage.log](https://github.com/appium/appium/files/2231762/python_findByImage.log)

**Comment by KazuCocoa** [comment]
=> https://github.com/appium/python-client/issues/233
