### ISSUE TITLE
Screen recording on iOS crashes WebDriverAgent

### ISSUE THREAD

**Issue by hursevich** [appium/appium#11118]
## The problem

WebDriverAgent crashes attempting to start iOS screen recording using xrecord.
Probably any specific steps required for xrecord setup?

## Environment

* Appium version: **1.8.1**
* Desktop OS/version used to run Appium: **latest MacOS**
* Node.js version (unless using Appium.app|exe): **v10.4.1**
* Mobile platform/version under test: **iOS**
* Real device or emulator/simulator: **real device**
* Appium CLI or Appium.app|exe: **Appium Java Client**

## Details

We were able to start xrecord manually and screen recording works well. 

## Link to Appium logs
https://gist.github.com/hursevich/5b81aec735a43a5d434e280daada5580

**Comment by kolyakrasnik** [comment]
We noticed, that if we start xrecord manually BEFORE and then run a test - video recording looks correct, WDA works fine. But if we try to start xrecord after WDA had beed started (like appium does) we see connection to WDA timed out issue. We tried to run with capability.shouldUseSingletonTestManager=false, no success. Any idea?

**Comment by mykola-mokhnach** [comment]
xrecord is open source, so probably you could debug it and figure out which exact operator causes connection interruption and hack it in some way. As I said, I don't see any possibility to address this problem from Appium perspective, since both of these tools are third party - we are just initiating them with correct parameters and starting sessions.

**Comment by uterator** [comment]
In the main.swift, comment this condition and rebuild the project
```
if !debug.value {
  let proc = Process()
  var args = Swift.CommandLine.arguments
  proc.launchPath = args[0]
  args.append("--debug")
  proc.arguments = args
  proc.standardError = Pipe()
  proc.launch()
  xRecord_Bridge.installSignalHandler(proc.processIdentifier)
  proc.waitUntilExit()
  quit(proc.terminationStatus)
}
```
then put the new xrecord somewhere visible in the PATH

**Comment by kolyakrasnik** [comment]
@uterator You are right, after running quickTimePlayer I'm getting connection to WDA timed out, WDA session no longer alive. Do you have any work around for that?
@mykola-mokhnach  Do we have ability to start firstly xrecord and then WDA session? Seems like this way WDA works as expected.

**Comment by mykola-mokhnach** [comment]
No there is no such possibility. Feel free to push a PR if you'd like to add it

**Comment by uterator** [comment]
> Do you have any work around for that?
Nop, the isonic1/flick was the solution

**Comment by mykola-mokhnach** [comment]
Thanks @uterator. I'll replace the default video recording tool for real devices with flick

**Comment by mykola-mokhnach** [comment]
Linking https://github.com/appium/appium-xcuitest-driver/pull/746

**Comment by mykola-mokhnach** [comment]
This feature request can be closed now. There are still some problems there, but the main functionality  is in place
