### ISSUE TITLE
Spinning indicator keep spinning and stuck

### ISSUE THREAD

**Issue by rishbaranwal** [appium/appium#11121]
## The problem

I have installed appium desktop successfully on my **mac book 1** and it is working properly , **on my mac book 2** , I did the same step to configure the appium desktop set up, but I am stuck while starting the session, it continues to spin through long time and suddenly spinner disappears.

## Environment

* Appium version : 1.6.2
* Desktop OS/version used to run Appium: mac OS High Sierra 10.13.4 (17E199)
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real Device

## Details

After doing all the necessary configurations mentioned in following link:

https://github.com/appium/appium-xcuitest-driver
https://github.com/appium/appium-desktop/releases
https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

I am successfully able to setup and launch the web driver agent, but it always stuck on server url line
After that, when I start the session from the appium desktop after providing the device capabilities, it always keep spinning , after certain period of time , spinner on appium desktop keep disappear.

Please find the device capabilities as image in attachment.

<img width="1192" alt="screen shot 2018-07-27 at 5 18 36 pm" src="https://user-images.githubusercontent.com/5096659/43319105-20bad152-91c1-11e8-918d-21ce9c26d6a3.png">

Please help me as I am stuck here from 3 days onwards.

## Link to Appium logs

No Logs is generated on Appium logs

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/appium/appium-desktop

Closed as not a server issue
