### ISSUE TITLE
[Docs] Docs display images at full size on page ios xcuitest real device.

### ISSUE THREAD

**Issue by meehanman** [appium/appium#11123]
## The problem

Docs display images at full size under Basic (manual) configuration instead of thumbnails.

## Environment
N/a 

## Details

See Link:
http://appium.io/docs/en/drivers/ios-xcuitest-real-devices/

## Link to Appium logs

N/A

## Code To Reproduce Issue [ Good To Have ]

N/A

**Comment by imurchie** [comment]
This should be fixed.
