### ISSUE TITLE
Cannot install appium-doctor via npm on Windows 10

### ISSUE THREAD

**Issue by grechko-an** [appium/appium#11122]
## The problem

Cannot install appium-doctor via npm

## Environment

* Appium version: 1.8.1:
* Desktop OS/version: Windows 10 Pro, version 1803, build 17134.165:
* Node.js version: 8.11.3

## Details

I installed Appium via npm successfully. But when I tried to install appium-doctor via npm (npm install appium-doctor -g. It gave me some errors in cmd and eventually appium-doctor wasn't installed. 

I added log and screenshot of this issue.

[2018-07-27T13_24_02_363Z-debug.log](https://github.com/appium/appium/files/2235909/2018-07-27T13_24_02_363Z-debug.log)

![screenshot_69](https://user-images.githubusercontent.com/38503607/43323819-5506eb22-91bb-11e8-96db-8342623ce731.png)

Hope you help me.

Thanks!

**Comment by mykola-mokhnach** [comment]
I would say the error message there is pretty clear. there's nothing to add

**Comment by imurchie** [comment]
`appium-support@2.20.0` should not install that dependency. Please try to re-install `appium-doctor`.

**Comment by grechko-an** [comment]
Hurray! 
It was installed! 
Thank you guys!!!
