### ISSUE TITLE
[IOS] Appium doesn't use mac os keychain for certificates

### ISSUE THREAD

**Issue by Jiurong-Yang** [appium/appium#11129]
I'm working behind a company proxy and is trying to set up Appium to start the driver session with url instead of having the apk/ipa on the appium server machines. This way i can keep a centralized repository for packages. The centralized server is a database that is using an internal certificate. This works great for Android appium server that is running on ubuntu (I just add the certificate to the system ca cert list and it's working fine). But for IOS i cannot get the appium server to use our internal certificates. 

I've tried:
Putting the certificates into the mac os keychain (Which works for curl and a web browser)
Putting the certificates into keystore of JRE (From what I can tell doesn't do anything)

I'm using Appium 1.8.1
macOS High Sierra Version 10.13.6

I don't know what else to do and I'm not as familiar with macOS as I am familiar with ubuntu so hopefully someone can provide an answer. 

IOS Appium log ->

[Appium]   app: https://saldb06.vcs.rd.hpicorp.net/test_package_storage/6b01a0435dc14c259b0b1641fb21e7ea/RemoteControl_AdHoc.ipa
[debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {"platformName":"IOS","plat...
[BaseDriver] The following capabilities were provided, but are not recognized by appium: deviceManufacturer, platform.
[BaseDriver] Session created with session id: 914fbb44-2ff5-4d2f-9bac-4b68b2d0bd49
[debug] [XCUITest] Current user: 'trex'
[debug] [XCUITest] Xcode version set to '9.4.1' (tools v9.4.0.0.1.1526532315)
[debug] [XCUITest] iOS SDK Version set to '11.4'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1533001146722 (18:39:06 GMT-0700 (PDT))
[debug] [XCUITest] Available devices: 375ffb6abfe5b68110b8798c5339433d239f687a
[debug] [XCUITest] Creating iDevice object with udid '375ffb6abfe5b68110b8798c5339433d239f687a'
[XCUITest] Determining device to run tests on: udid: '375ffb6abfe5b68110b8798c5339433d239f687a', real device: true
[BaseDriver] Using downloadable app 'https://saldb06.vcs.rd.hpicorp.net/test_package_storage/6b01a0435dc14c259b0b1641fb21e7ea/RemoteControl_AdHoc.ipa'
[XCUITest] Error: Problem downloading app from url https://saldb06.vcs.rd.hpicorp.net/test_package_storage/6b01a0435dc14c259b0b1641fb21e7ea/RemoteControl_AdHoc.ipa: Error: unable to verify the first certificate
[XCUITest]     at downloadApp$ (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/helpers.js:150:11)
[XCUITest]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[XCUITest]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[XCUITest]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[XCUITest]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest] Error: Bad app: https://saldb06.vcs.rd.hpicorp.net/test_package_storage/6b01a0435dc14c259b0b1641fb21e7ea/RemoteControl_AdHoc.ipa. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name.
[XCUITest]     at XCUITestDriver.configureApp$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:625:13)
[XCUITest]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[XCUITest]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[XCUITest]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[XCUITest]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest] No WebDriverAgent derived data available, so unable to clear system files
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1533001147018 (18:39:07 GMT-0700 (PDT))
[MJSONWP] Encountered internal error running command: Error: Bad app: https://saldb06.vcs.rd.hpicorp.net/test_package_storage/6b01a0435dc14c259b0b1641fb21e7ea/RemoteControl_AdHoc.ipa. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name.
[MJSONWP]     at XCUITestDriver.configureApp$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:625:13)
[MJSONWP]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)

**Comment by mykola-mokhnach** [comment]
You could do this: https://stackoverflow.com/questions/10888610/ignore-invalid-self-signed-ssl-certificate-in-node-js-with-https-request

**Comment by mykola-mokhnach** [comment]
Also if you want the client to accept the self signed cert then the code in base driver component has to be changed to explicitly trust that certificate, like it is described in https://community.apigee.com/articles/28041/nodejs-and-self-signed-ssl-certificates.html

**Comment by Jiurong-Yang** [comment]
Just to clearify. The solution you propose is to ignore validation. Which can be done with environment variable

export NODE_TLS_REJECT_UNAUTHORIZED=0

(Third solution from the link you posted). Which i will try tomorrow when i get into work. Wasn't quite sure what the second reply means. As this entire process is on the server side and all the client side is doing is requesting a session with the dc "app" field pointed to a database attachment url. Also since the client side is running on Ubuntu(we run everything remote) the client has no issue communicating with the certificates.

**Comment by Jiurong-Yang** [comment]
The solution i mentioned above worked. So i guess this can be closed.
