### ISSUE TITLE
Trying to get the attribute of an AndroidElement throws NoSuchElementException

### ISSUE THREAD

**Issue by Akshaj** [appium/appium#11137]
## The problem
http://appium.io/docs/en/commands/element/attributes/attribute/
Says that response will be value of the attribute or NULL if not set.

See my line of code below:

	System.out.println(element.getAttribute("content-desc"));

Attribute "content-desc" has value in it. 
So, why am I getting NoSuchElementException here?

## Environment

* Appium version (or git revision) that exhibits the issue: appium v1.8.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe):  v8.11.3
* Mobile platform/version under test: Android oreo
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

**Comment by imurchie** [comment]
Please provide the server logs (as a link to a [gist](https://gist.github.com)) so that a determination can be made. With this information nothing can be said.

**Comment by Akshaj** [comment]
Find the logs in the below link:

https://gist.github.com/Akshaj/ca586e8a7cae989c3265c6cc50de24c1

**Comment by Akshaj** [comment]
Given Below is the exact code:
*******************************

		List<AndroidElement> list = driver.findElementsByClassName("android.view.View");
		
		for(AndroidElement element : list)
		{
			
			System.out.println(element.getAttribute("content-desc"));
			//Exception is Thrown in the above line

		}

**Comment by mykola-mokhnach** [comment]
> [debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":7,"value":"This element does not have the 'content-desc' attribute"}

So the exception is correct. check https://github.com/appium/appium-android-bootstrap/blob/master/bootstrap/src/io/appium/android/bootstrap/handler/GetAttribute.java to get the full list of supported attributes. Also, it is highly recommended to use UIAutomator2 for Androdi6+

**Comment by Akshaj** [comment]
The value of the Attribute "Content-desc" can be accessed as follows:
		System.out.println(element.getAttribute("name")); //"name" must be used instead of "content-desc"

found it in issue #355 :
https://github.com/appium/java-client/issues/355

Closing this now.
