### ISSUE TITLE
new session in ios is very slow

### ISSUE THREAD

**Issue by orevron** [appium/appium#11132]
## The problem

after using the 'wd driver', driver.init() function i can see the app installed on the device and this is the last log from the appium, server: 

> [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.capriza.approvalsapp.qaBeta","arguments":["-detoxServer","http://localhost:8099","-detoxSessionId","1111"],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}

and than the function stuck for 5.5 minutes minutes and finish with success.
it happens only on ios.

## Environment

* 1.8.1
* MacOSX High Sierra 10.13.6
* Node.js version: 8.9.4
* iPhone X iOS 11.4
* simulator
* Appium.app

## Details

attached appium log:
https://gist.github.com/orevron/ee51a36179dd4e78c85ae03fd6a3f01c

**Comment by KazuCocoa** [comment]
I'm not familiar with running with detox, but what about changing your test app to another app which doesn't need detox like test app in https://github.com/appium/appium/tree/master/sample-code/apps ?

https://github.com/wix/detox/blob/7650996f3c02c853c483421587f4d03d4a025fea/detox/ios/Detox/DetoxManager.m#L48

```
[Appium]   processArguments: {
[Appium]     args: {
[Appium]       0: -detoxServer
[Appium]       1: http://localhost:8099
[Appium]       2: -detoxSessionId
[Appium]       3: 1111
[Appium]     }
[Appium]   }
```

I wondered the slow is waiting for launching the test app with detox server.

**Comment by orevron** [comment]
Actually I already solved it by adding the
“waitForQuietness: false” capability.

**Comment by KazuCocoa** [comment]
thanks

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-xcuitest-driver/search?utf8=%E2%9C%93&q=waitForQuiescence&type=
@mike-pt 

ah, we should update the readme. will do.
