### ISSUE TITLE
'browserName' cannot set together with 'bundleId' capability

### ISSUE THREAD

**Issue by mohit1206** [appium/appium#11134]
Hi,

I am working on latest iOS version and when I am trying to launch browser in Safari in real device, I am getting error logs in appium.
Below are the logs.

Last login: Tue Jul 31 16:13:45 on ttys000
WKMIN0378477:~ sulshriv$ appium -a 0.0.0.0 -p 4723 --session-override
[Appium] Welcome to Appium v1.8.2-beta
[Appium] Non-default server args:
[Appium]   sessionOverride: true
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"":"","automationName":"XCuiTest","browserName":"Safari","bundleId":"com.bst.wda","cleanSession":true,"deviceName":"Amit Pareek’s iPhone","javascriptEnabled":true,"platform":"MAC","platformName":"iOS","platformVersion":"11.4.1","safari.options":{"cleanSession":true,"port":0,"technologyPreview":false},"takesScreenshot":"true","udid":"6f5161d2225bf69c8a95d116d82f0f6bfe61e4e2","xcodeOrgId":"4CYMJA762C","xcodeSigningId":"iPhone Developer"},"capabilities":{"desiredCapabilities":{"":"","automationName":"XCuiTest","browserName":"Safari","bundleId":"com.bst.wda","cleanSession":true,"deviceName":"Amit Pareek’s iPhone","javascriptEnabled":true,"platform":"MAC","platformName":"iOS","platformVersion":"11.4.1","safari.options":{"cleanSession":true,"port":0,"technologyPreview":false},"takesScreenshot":"true","udid":"6f5161d2225bf69c8a95d116d82f0f6bfe61e4e2","xcodeOrgId":"4CYMJA762C","xcodeSigningId":"iPhone Developer"},"firstMatch":[{"browserName":"Safari","platformName":"ios
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"":"","automationName":"XCuiTest","browserName":"Safari","bundleId":"com.bst.wda","cleanSession":true,"deviceName":"Amit Pareek’s iPhone","javascriptEnabled":true,"platform":"MAC","platformName":"iOS","platformVersion":"11.4.1","safari.options":{"cleanSession":true,"port":0,"technologyPreview":false},"takesScreenshot":"true","udid":"6f5161d2225bf69c8a95d116d82f0f6bfe61e4e2","xcodeOrgId":"4CYMJA762C","xcodeSigningId":"iPhone Developer"},null,{"desiredCapabilities":{"":"","automationName":"XCuiTest","browserName":"Safari","bundleId":"com.bst.wda","cleanSession":true,"deviceName":"Amit Pareek’s iPhone","javascriptEnabled":true,"platform":"MAC","platformName":"iOS","platformVersion":"11.4.1","safari.options":{"cleanSession":true,"port":0,"technologyPreview":false},"takesScreenshot":"true","udid":"6f5161d2225bf69c8a95d116d82f0f6bfe61e4e2","xcodeOrgId":"4CYMJA762C","xcodeSigningId":"iPhone Developer"},"firstMatch":[{"browserName":"Safari","platformName":"ios"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1533034094323 (16:18:14 GMT+0530 (India Standard Time))
[Appium] Could not parse W3C capabilities: 'deviceName' can't be blank. Falling back to JSONWP protocol.
[Appium] The following capabilities were provided in the JSONWP desired capabilities that are missing in W3C capabilities: ["","automationName","browserName","bundleId","cleanSession","deviceName","javascriptEnabled","platform","platformName","platformVersion","safari.options","takesScreenshot","udid","xcodeOrgId","xcodeSigningId"]. Falling back to JSONWP protocol.
[Appium] Creating new XCUITestDriver (v2.87.0) session
[Appium] Capabilities:
[Appium]   : 
[Appium]   automationName: XCuiTest
[Appium]   browserName: Safari
[Appium]   bundleId: com.bst.wda
[Appium]   cleanSession: true
[Appium]   deviceName: Amit Pareek’s iPhone
[Appium]   javascriptEnabled: true
[Appium]   platform: MAC
[Appium]   platformName: iOS
[Appium]   platformVersion: 11.4.1
[Appium]   safari.options: {
[Appium]     cleanSession: true
[Appium]     port: 0
[Appium]     technologyPreview: false
[Appium]   }
[Appium]   takesScreenshot: true
[Appium]   udid: 6f5161d2225bf69c8a95d116d82f0f6bfe61e4e2
[Appium]   xcodeOrgId: 4CYMJA762C
[Appium]   xcodeSigningId: iPhone Developer
[debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {"":"","automationName":"XC...
[BaseDriver] The following capabilities were provided, but are not recognized by appium: , cleanSession, javascriptEnabled, platform, safari.options, takesScreenshot.
[XCUITest] Error: 'browserName' cannot be set together with 'bundleId' capability
[XCUITest]     at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[XCUITest]     at XCUITestDriver.validateDesiredCaps (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:928:13)
[XCUITest]     at XCUITestDriver.callee$0$0$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-base-driver/lib/basedriver/commands/session.js:45:8)
[XCUITest]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[XCUITest]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[XCUITest]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[XCUITest]     at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest]     at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
[XCUITest]     at new Promise (<anonymous>)
[XCUITest]     at new F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
[XCUITest]     at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
[XCUITest]     at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[XCUITest]     at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
[XCUITest]     at XCUITestDriver.callee$0$0 [as createSession] (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-base-driver/build/lib/basedriver/commands/session.js:35:30)
[XCUITest]     at XCUITestDriver.createSession$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:101:21)
[XCUITest]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[XCUITest]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[XCUITest]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[XCUITest]     at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest]     at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
[XCUITest]     at new Promise (<anonymous>)
[XCUITest]     at new F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
[XCUITest]     at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
[XCUITest]     at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[XCUITest]     at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
[XCUITest]     at XCUITestDriver.createSession (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/build/lib/driver.js:220:34)
[XCUITest]     at AppiumDriver.callee$2$0$ (/usr/local/lib/node_modules/appium/lib/appium.js:244:43)
[XCUITest]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[XCUITest]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[XCUITest]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[XCUITest]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest]     at process._tickCallback (internal/process/next_tick.js:68:7)
[XCUITest] Error: 'browserName' cannot be set together with 'bundleId' capability
[XCUITest]     at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[XCUITest]     at XCUITestDriver.validateDesiredCaps (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:928:13)
[XCUITest]     at XCUITestDriver.callee$0$0$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-base-driver/lib/basedriver/commands/session.js:45:8)
[XCUITest]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[XCUITest]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[XCUITest]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[XCUITest]     at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest]     at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
[XCUITest]     at new Promise (<anonymous>)
[XCUITest]     at new F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
[XCUITest]     at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
[XCUITest]     at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[XCUITest]     at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
[XCUITest]     at XCUITestDriver.callee$0$0 [as createSession] (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-base-driver/build/lib/basedriver/commands/session.js:35:30)
[XCUITest]     at XCUITestDriver.createSession$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:101:21)
[XCUITest]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[XCUITest]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[XCUITest]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[XCUITest]     at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest]     at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
[XCUITest]     at new Promise (<anonymous>)
[XCUITest]     at new F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
[XCUITest]     at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
[XCUITest]     at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[XCUITest]     at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
[XCUITest]     at XCUITestDriver.createSession (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/build/lib/driver.js:220:34)
[XCUITest]     at AppiumDriver.callee$2$0$ (/usr/local/lib/node_modules/appium/lib/appium.js:244:43)
[XCUITest]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[XCUITest]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[XCUITest]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[XCUITest]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest]     at process._tickCallback (internal/process/next_tick.js:68:7)
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1533034094359 (16:18:14 GMT+0530 (India Standard Time))
[MJSONWP] Encountered internal error running command: Error: 'browserName' cannot be set together with 'bundleId' capability
[MJSONWP]     at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[MJSONWP]     at XCUITestDriver.validateDesiredCaps (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:928:13)
[MJSONWP]     at XCUITestDriver.callee$0$0$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-base-driver/lib/basedriver/commands/session.js:45:8)
[MJSONWP]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP]     at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
[MJSONWP]     at new Promise (<anonymous>)
[MJSONWP]     at new F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
[MJSONWP]     at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
[MJSONWP]     at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
[MJSONWP]     at XCUITestDriver.callee$0$0 [as createSession] (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-base-driver/build/lib/basedriver/commands/session.js:35:30)
[MJSONWP]     at XCUITestDriver.createSession$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:101:21)
[MJSONWP]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP]     at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
[MJSONWP]     at new Promise (<anonymous>)
[MJSONWP]     at new F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
[MJSONWP]     at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
[MJSONWP]     at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
[MJSONWP]     at XCUITestDriver.createSession (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/build/lib/driver.js:220:34)
[MJSONWP]     at AppiumDriver.callee$2$0$ (/usr/local/lib/node_modules/appium/lib/appium.js:244:43)
[MJSONWP]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP]     at process._tickCallback (internal/process/next_tick.js:68:7)
[HTTP] <-- POST /wd/hub/session 500 46 ms - 200
[HTTP]

**Comment by mykola-mokhnach** [comment]
the error is correct. You must set either browser name or bundle id, but now both
