### ISSUE TITLE
Unable to open Deep link using uiautomator2 driver with Appium Python client

### ISSUE THREAD

**Issue by majdukovic** [appium/appium#11149]
## The problem

Hi, I'm unable to open deep link on real Android device (Samsung Galaxy S8) if I use uiautomator2 as automation driver. If I use Appium as automation driver then I can open deep link but I'm not able to click on the elements in the app. I use Appium Python client.

The error I get is "Appium error: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 404 - undefined"

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: iMac, macOS High Sierra (10.13.6)
* Node.js version (unless using Appium.app|exe): v8.9.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real device, Samsung Galaxy S8 with os 7.0 (device running on BS cloud platform)
* Appium CLI or Appium.app|exe: 

## Link to Appium logs

https://gist.github.com/majdukovic/e4ad81cb6c9e6a1449806491d79b5ca5

## Code To Reproduce Issue [ Good To Have ]

self.driver = webdriver.Remote(server_url, desired_caps)
self.driver.find_element(*self._install_update_later_button_android).click()
self.driver.find_element(*self._privacy_policy_accept_button_android).click()
self.driver.get(https://www.matchbook.com/deepLink/login/username-password)

## Desired capabilities

desired_caps = {
    'samsung_galaxy_s8_7_0': {
        'app': 'location',
        'platformName': 'Android',
        'platformVersion': '7.0',
        'deviceName': 'Samsung Galaxy S8',
        'avd': 'Samsung_Galaxy_S8',
        'automationName': 'uiautomator2',
        'autoGrantPermissions' : True,
        'appWaitPackage': 'com.matchbook.client',
        'appWaitActivity': 'com.android.xanadu.matchbook.MainActivity',
        'browserstack.local': True,
        'browserstack.appium_version': '1.8.1',
        'browserstack.idleTimeout': '10'
    }
}

**Comment by majdukovic** [comment]
Hey, hm, it's what I've set as capability (see gist), I've tried also setting Appium version to  1.7.1 but it didn't work. Also, I had same issue on Google Nexus emulator locally with os v7.0

I have latest Appium desktop on my Mac. 

Why do you think it might be older version, just curious?

**Comment by majdukovic** [comment]
This is from error:

2018-08-03 14:49:11:835 - [MJSONWP] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 404 - undefined
    at doJwpProxy$ (../../../lib/mjsonwp/mjsonwp.js:385:13)
    at tryCatch (/usr/local/.browserstack/appium_1.6.5_bstack/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/.browserstack/appium_1.6.5_bstack/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw]

Maybe you are right, maybe it's running 1.6.5 if 'appium_1.6.5_bstack' means that?

I might check with Browserstack support, but then it should work on emulator. I'll need to check local logs when I'm in the office

**Comment by dpgraham** [comment]
The latest Appium has a method `execute('mobile: deepLink')` (http://appium.io/docs/en/commands/mobile-command/) that opens deep links. Have you tried that?

**Comment by imurchie** [comment]
`appium-uiautomator2-driver` [0.5.2](https://github.com/appium/appium-uiautomator2-driver/releases/tag/v0.5.2) was published on August 3, 2017. So it is a year old, and from the beta phase of support for UiAutomator2. It's not a version that was part of any Appium release. I presume BrowserStack is broken, unfortunately.

Browserstack's documentation makes it seem like they only support Appium 1.6.5, 1.7.1, and 1.7.2. And Android defaults to 1.6.5. That they don't tell you that they're adjusting it is problematic for any testing scenario though.

**Comment by majdukovic** [comment]
You are both right, thank you.
It is older version of Appium, they don't support newer releases yet so it falls back to default and that was causing the error.
I'll close the issue, thanks again.
