### ISSUE TITLE
IOSTouchAction tap does not tap fast enough

### ISSUE THREAD

**Issue by satgh12** [appium/appium#11143]
## The problem

I am trying to tap on an element which was implemented by UITapGestureRecognizer.  Functionality is that I tap on the element few times to bring up developer options (just like Androids developer options, but the context here is iOS.)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1 server and 5.0.4 client
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: 10.13.4, XCode: 9.4.1
* Node.js version (unless using Appium.app|exe): 6.11.4
* Mobile platform/version under test: iPad mini 11.4.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/satgh12/4fa39de87c4a37e10a7035d6e2d83833

## Code To Reproduce Issue [ Good To Have ]
Trying to tap 7 times like below to bring up developer options.  I can introduce a for loop as well.  Tried TouchAction and TouchActions classes as well.  Also, tried to find element and click on it instead of tapping.  Introduced a Thread.sleep(50) in between taps as well.  None of the methods worked.  My coordinates of x and y are correct.  In the iOS app, the element is implemented using UITapGestureRecognizer.

    IOSTouchAction action = new IOSTouchAction(driver);
    action.tap(154, 271).perform();
    action.tap(154, 271).perform();
    action.tap(154, 271).perform();
    action.tap(154, 271).perform();
    action.tap(154, 271).perform();
    action.tap(154, 271).perform();
    action.tap(154, 271).perform();

Also tried tapping this way.  This throws an exception.
action.tap(154, 271).tap(154, 271).tap(154, 271).tap(154, 271).tap(154, 271).tap(154, 271).perform();

**Comment by mykola-mokhnach** [comment]
Version 1.7.1 is out of date. Upgrade to 1.8.2-beta and try again

**Comment by satgh12** [comment]
@mykola-mokhnach 
I upgraded to 1.8.2-beta2.
I am running into a different set of problem now.  
Logged this new issue: https://github.com/appium/appium/issues/11146
The same code which worked on 1.7.1 is now failing on 1.8.2-beta.

**Comment by mykola-mokhnach** [comment]
Closed as obsolete. We don't make patches to older appium releases
