### ISSUE TITLE
Can not switch to webview on ios real device

### ISSUE THREAD

**Issue by loveiset** [appium/appium#11148]
## The problem

can not switch to webview on ios real device, error info
```
[debug] [W3C] Calling AppiumDriver.setContext() with args: ["WEBVIEW_3","66fd0ff6-4461-4123-9237-24292b44ca22"]
[debug] [XCUITest] Executing command 'setContext'
[debug] [iOS] Attempting to set context to 'WEBVIEW_3'
[debug] [RemoteDebugger] WebKit debugger web socket connected to url: ws://localhost:27753/devtools/page/3
[debug] [RemoteDebugger] Starting to listen for JavaScript console
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Console.enable","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true}}
[debug] [RemoteDebugger] Webkit response timeout: 90000
[debug] [XCUITest] Connection to WDA timed out
[debug] [iProxy] recv failed: Operation not permitted
[MJSONWP] Encountered internal error running command: TimeoutError: operation timed out
[MJSONWP]     at afterTimeout (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/release/timers.js:46:19)
[MJSONWP]     at Timeout.timeoutTimeout [as _onTimeout] (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/release/timers.js:76:13)
[MJSONWP]     at ontimeout (timers.js:427:11)
[MJSONWP]     at tryOnTimeout (timers.js:289:5)
[MJSONWP]     at listOnTimeout (timers.js:252:5)
[MJSONWP]     at Timer.processTimers (timers.js:212:10)
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1(1.8.2 beta)
* Desktop OS/version used to run Appium: Mac OSX Hign Sierra
* node v10.4.0
* npm -v6.3.0
* Mobile platform/version under test: iOS 11.2.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: `appium -p 4724 --session-override`

## Details

the problem may be the same as issue #10741 , but I am not sure because I tried all the solutions, did not solve my problem.

### user appium 1.8.1
First I `npm install -g appium` and `npm install -g appium-remote-debugger@3.12.0`
```
/usr/local/lib
├─┬ appium@1.8.1
│ ├─┬ appium-ios-driver@2.5.1
│ │ └── appium-remote-debugger@3.19.2 
│ └─┬ appium-xcuitest-driver@2.88.0
│   └── appium-remote-debugger@3.19.2  deduped
└── appium-remote-debugger@3.12.0 
``` 

### use appium 1.8.2 beta
then I install appium beta `npm install -g appium@beta`
```
/usr/local/lib
├─┬ appium@1.8.2-beta
│ ├─┬ appium-ios-driver@2.5.1
│ │ └── appium-remote-debugger@3.19.2 
│ └─┬ appium-xcuitest-driver@2.88.0
│   └── appium-remote-debugger@3.19.2  deduped
└── appium-remote-debugger@3.12.0 
```

### manual inspect webview using ios_webkit_debug_proxy
I can successfully inspect into my webview using url 
```
chrome-devtools://devtools/bundled/inspector.html?ws=localhost:9222/devtools/page/2
```

## Link to Appium logs

[full log](https://gist.github.com/loveiset/6493aa405b13717c5682d291d14b1f50)

**Comment by gramai** [comment]
`[Xcode] Check dependencies
[Xcode] Code Signing Error: Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.
[Xcode] Code Signing Error: Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 11.4'
[Xcode] 
[Xcode] Code Signing Error: Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.
[Xcode] 
[Xcode] Code Signing Error: Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 11.4'
[Xcode] Code Signing Error: Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.
[Xcode] 
[Xcode] Code Signing Error: Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 11.4'
[Xcode] Code Signing Error: Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.
[Xcode] Code Signing Error: Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 11.4'
[Xcode] 
[Xcode] Code Signing Error: Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 11.4'
[Xcode] Code Signing Error: Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 11.4'
[Xcode] Code Signing Error: Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 11.4'
`
Hello.
I believe this could be an app signing problem. 
Have you tried signing the WebDriverAgent and WebDriverAgentLib in xCode?
The project to be signed should be in 
`/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj`

**Comment by KazuCocoa** [comment]
@gramai Did you try http://appium.io/docs/en/drivers/ios-xcuitest-real-devices/ ?

**Comment by loveiset** [comment]
@gramai @KazuCocoa I can run test on real device successfully with native app, I just can't switch to webview, so I think it may be something wrong with webview switching process or other config needed for webview on real device?
ps: I can successfully inspect webview through safari manually.

**Comment by gramai** [comment]
I encountered similar problems on certain parts of the app I am currently testing, but other parts worked fine. Have your tried setting the webview context on other pages? If so, did it behave the same?

**Comment by ochubey** [comment]
@loveiset what do you get when getting the list of contexts available?
I've done it with several retries - please see java example:
`public boolean switchToWebViewContext() {
        int retries = 0;
        while (retries <= 5) {
            try {
                general.sleepInSeconds(shortElementWaitingTimeout);
                Set allContexts = getDriverInstance().getDriver().getContextHandles();
                String nativeAppContextPrefix = "NATIVE";
                for (Object context : allContexts) {
                    if (!context.toString().contains(nativeAppContextPrefix)) {
                        getDriverInstance().getDriver().context(context.toString());
                        return !isNativeContext();
                    }
                }
            } catch (NotFoundException ex) {
                logError(ex.getMessage());
            } finally {
                retries++;
            }
        }
        return false;
    }`

**Comment by loveiset** [comment]
@ochubey I get contexts，it return a list contains native and a webview context startswith 'webview`，but when I switch to webview using this context, an error occurs (error message shows in my description)

**Comment by mykola-mokhnach** [comment]
Try the solution from https://github.com/facebook/WebDriverAgent/issues/827

Otherwise I don't think there's anything else that could be changed on Appium side here.
