### ISSUE TITLE
Appium tests randomly failing due to the app becomes unresponsive.

### ISSUE THREAD

**Issue by saim80** [appium/appium#11145]
## The problem

While running tests, the app process consumes near 100% CPU, it becomes unresponsive. The tests are randomly failing because of this.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Desktop OS/version used to run Appium: MacOS 10.13.6
* Node.js version (unless using Appium.app|exe): 10.8.0
* Mobile platform/version under test: iPhone X (iOS 11.4)
* Real device or emulator/simulator: Simulator iPhone X (iOS 11.4)
* Appium CLI or Appium.app|exe: Both CLI and macOS server app are tried and have the same issue.

## Details

I’m currently trying to make Appium test working locally on my laptop. I observed that the test gets slower over time within single session. Element/displayed query takes 7-10 seconds according to the server app’s log. The slowdown is significant and noticeable by just watching the test. I also observed that once the test starts the target app process uses around 100% CPU, sometimes it goes above 100%. I also observed that sometimes the process gets paused for a while before resuming.

I’m using Rspec and Ruby to write tests for iOS simulators. Where should I start to solve this problem? Any helps appreciated.

I took a video of what I’m observing. https://d.pr/v/YuhGEp

It looks like Android had a similar issue, then disableAndroidWathers was added to lower cpu consumption. I cannot seem to find anything in iOS side to just give a try. I’m just guessing around to figure this out though.https://github.com/appium/appium/issues/4698

**Comment by mykola-mokhnach** [comment]
Try appium@beta. If that does not help then report the issue to https://github.com/facebook/WebDriverAgent

There is nothing much that can be done on Appium side

**Comment by saim80** [comment]
Using 1.8.2 beta solved the issue for me.

**Comment by saim80** [comment]
Oh well, it worked for few instances, but it came back again with beta server... I'm so confused how things worked when installed the beta for the first time...

**Comment by addbrick** [comment]
@mykola-mokhnach The WebDriverAgent you linked to isn't the one used by Appium. It uses this fork https://github.com/appium/WebDriverAgent, which is appears to be actively maintained, unlike the Facebook one. What is the relationship here? Is Facebook maintaining the web driver?

**Comment by mykola-mokhnach** [comment]
@addbrick Facebook does maintain it, but kind'a slow. So, we have forked their repository and keep adding improvements on our own, otherwise it takes too long to wait until they are reviewed and merged in the original rep.
