### ISSUE TITLE
 Incorrect package and activity. Retrying. Getting focused package and activity Cannot initialize the appium driver

### ISSUE THREAD

**Issue by irfanpace** [appium/appium#11142]
## The problem

I’m not able to start the appium driver (application gets instlled), I have tried with all the appium version starting from 1.3 to 1.6 version, with which I’m getting the same error.

## Environment

* Appium version: 1.6
* Desktop OS/version used to run Appium: windows 10
* Mobile platform/version under test: Androif
* Real device or emulator/simulator: emulator

## Details

Tried with both appium driver as well as android driver.

## Link to Appium logs

[ADB] Found package: ‘com.karwatechnologies.karwataxi’ and fully qualified activity name : ‘com.karwatechnologies.karwataxi.activities.LoginAndRegistrationActivity’
[ADB] Incorrect package and activity. Retrying.
[ADB] Getting focused package and activity
[ADB] Getting connected devices…
[ADB] 1 device(s) connected
[ADB] Running ‘C:\Users\mirfan.KARWASOLUTIONS\AppData\Local\Android\Sdk\platform-tools\adb.exe’ with args: ["-P",5037,"-s",“emulator-5554”,“shell”,“dumpsys”,“window”,“windows”]

## Code To Reproduce Issue [ Good To Have ]

 cap.setCapability(MobileCapabilityType.PLATFORM_NAME, MobilePlatform.ANDROID);
    cap.setCapability(MobileCapabilityType.APP, 
   "C:\\Users\\mirfan.KARWASOLUTIONS\\AppiumJarFiles\\androidLiveBooking.apk");
    cap.setCapability(MobileCapabilityType.DEVICE_NAME, "PixelXL");
    
    AppiumDriver<AndroidElement> driver = new AppiumDriver<>(new URL("http://127.0.0.1:4723/wd/hub"), cap);

**Comment by mykola-mokhnach** [comment]
You must set correct appActivity/appWaitActivity and appPackage capability values
