### ISSUE TITLE
Appium server takes 19 minutes to start session

### ISSUE THREAD

**Issue by maxsudik** [appium/appium#11141]
Anybody know why it takes 19 minutes to run the session?
Any suggestions to reduce the time?
Is this behaviour expected for my environment?

Thank you in advance.

Environment:
iMac (21.5-inch, Late 2012), 2.7 GHz Intel Core i5, 8 GB 1600 MHz DDR3, NVIDIA GeForce GT 640M 512 MB

info AppiumDoctor Appium Doctor v.1.4.3
info AppiumDoctor ### Diagnostic starting ###
info AppiumDoctor  :heavy_check_mark: The Node.js binary was found at: /usr/local/bin/node
info AppiumDoctor  :heavy_check_mark: Node version is 6.9.1
info AppiumDoctor  :heavy_check_mark: Xcode is installed at: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  :heavy_check_mark: Xcode Command Line Tools are installed.
info AppiumDoctor  :heavy_check_mark: DevToolsSecurity is enabled.
info AppiumDoctor  :heavy_check_mark: The Authorization DB is set up properly.
info AppiumDoctor  :heavy_check_mark: Carthage was found at: /usr/local/bin/carthage
info AppiumDoctor  :heavy_check_mark: HOME is set to: /Users/Maksym
info AppiumDoctor  :heavy_check_mark: ANDROID_HOME is set to: /Users/Maksym/Library/Android/sdk
info AppiumDoctor  :heavy_check_mark: JAVA_HOME is set to: /Library/Java/JavaVirtualMachines/jdk-10.0.2.jdk/Contents/Home
info AppiumDoctor  :heavy_check_mark: adb exists at: /Users/Maksym/Library/Android/sdk/platform-tools/adb
info AppiumDoctor  :heavy_check_mark: android exists at: /Users/Maksym/Library/Android/sdk/tools/android
info AppiumDoctor  :heavy_check_mark: emulator exists at: /Users/Maksym/Library/Android/sdk/tools/emulator
info AppiumDoctor  :heavy_check_mark: Bin directory of $JAVA_HOME is set
info AppiumDoctor ### Diagnostic completed, no fix needed. ###
info AppiumDoctor
info AppiumDoctor Everything looks good, bye!
info AppiumDoctor

[Link to Appium Log](https://gist.github.com/maxsudik/9da04404b98a67010dc8953dc7d7195b)

**Comment by maxsudik** [comment]
The reason why it worked so slow is type of hdd. I had SATA, but after I moved xcode, app file with project to external hdd everything works fine.

Issue can be closed

**Comment by KazuCocoa** [comment]
Ah, interesting.
Thanks for the report!
