### ISSUE TITLE
Upgrading to 1.8.2-beta to run iOS test is causing Exception in thread "main" org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. 

### ISSUE THREAD

**Issue by satgh12** [appium/appium#11146]
## The problem

After upgrading to 1.8.2-beta from 1.7.1, I am running into the below exception
Exception in thread "main" org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. 

The below code worked fine with no issues on 1.7.1.  Issue only with 1.8.2-beta

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.2-beta
* Last Appium version that did not exhibit the issue (if applicable): 1.7.1
* Desktop OS/version used to run Appium: 10.13.4, XCode: 9.4.1
* Node.js version (unless using Appium.app|exe): 6.11.4
* Mobile platform/version under test: iPad mini 11.4.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/satgh12/b956a3ef44592459b61fb85354af8090

## Code To Reproduce Issue [ Good To Have ]

DesiredCapabilities capabilities = new DesiredCapabilities();   
	capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "FOO");	
    capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "IOS");
    capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.IOS_XCUI_TEST);    
    capabilities.setCapability(MobileCapabilityType.UDID, "<UDID>");      
    capabilities.setCapability(MobileCapabilityType.FULL_RESET, false);
    capabilities.setCapability(MobileCapabilityType.NO_RESET, false);      
    capabilities.setCapability("bundleId", "<BUNDLE_ID>");    
    AppiumDriver<MobileElement> driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);    
    Thread.sleep(3000);
    driver.findElement(By.id("Button")).click();

**Comment by mykola-mokhnach** [comment]
Such error happens because WDA binary on the device is outdated and must be updated. Closed as duplicate

**Comment by satgh12** [comment]
@mykola-mokhnach 
Can you please help as to how to update existing WDA binary?

**Comment by satgh12** [comment]
@mykola-mokhnach 
1. Removed the WDA file from the iOS device
2. Clean built WDA project in xcode
3. Deleted the files under ~/Library/Developer/Xcode/DerivedData/ModuleCache
4. Restarted both Mac machine and iOS device

Still get the above error.  This issue cannot be closed without proper resolution.  What is it a duplicate of and what was the resolution there?

**Comment by imurchie** [comment]
Step `3` should probably be deleting files under `~/Library/Developer/Xcode/DerivedData/WebDriverAgent-*`

**Comment by satgh12** [comment]
@imurchie 
Tried all the below four steps, but still get the same error.
1. Removed the WDA file from the iOS device
2. Clean built WDA project in xcode
3. Deleted the files under ~/Library/Developer/Xcode/DerivedData/WebDriverAgent-*
    Deleted files and folders under both the WebDriverAgent folders.
4. Restarted both Mac machine and iOS device

**Comment by mykola-mokhnach** [comment]
Closed as inactive
