### ISSUE TITLE
Android - Unable to identify elements using Appium desktop or UIAUtomator Viewer

### ISSUE THREAD

**Issue by hm2286** [appium/appium#11151]
## The problem

Android - Unable to identify elements using Appium desktop or UIAUtomator Viewer. Getting error as,
An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)

## Environment
Appium v1.8.1
gson - 2.8.2 jar
selenium-server-standalone-3.12.0
java-client-6.1.0
common-lang3.jar

## Details
None of the locators working, tried below options,
driver.findElement(By.xpath("//*[@text='Username']"));
driver.findElement(By.xpath("//android.view.View[@text='Username']"));
MobileElement username = (MobileElement)(driver.findElement(By.name("Username")));
driver.findElement(By.xpath("//UIAButton[@name='Username']"));

## Link to Appium logs
Appium Log:
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding '//android.view.View[@text='Username']' using 'XPATH' with the contextId: '' multiple: false
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Failed to locate element. Clearing Accessibility cache and retrying.
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding '//android.view.View[@text='Username']' using 'XPATH' with the contextId: '' multiple: false
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":7,"value":"No element found"}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [MJSONWP] Matched JSONWP error code 7 to NoSuchElementError
[HTTP] <-- POST /wd/hub/session/7db2d3c0-49d5-405f-9f84-fce89cdf07c5/element 500 826 ms - 164

## Code To Reproduce Issue [ Good To Have ]

**Comment by mykola-mokhnach** [comment]
Please attach full page source you get before executing the lookup. Also, use UIAutomator2 backend for Android 6+

**Comment by hm2286** [comment]
Source code:
public class Config {

	static AppiumDriver<MobileElement> driver;
	static String path;
	
	public static void androidCap()
	{
		System.out.println("Appium Session is creating");
		path = System.getProperty("user.dir");
		DesiredCapabilities cap = new DesiredCapabilities();
		cap.setCapability("platformName", "Android");
		cap.setCapability("deviceName", "***");
		cap.setCapability("autoGrantPermissions","true");
		cap.setCapability("noReset", true);
	    cap.setCapability("fullReset", false);
	    cap.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, "100");
	    cap.setCapability("automationName", "UiAutomator2");
		cap.setCapability("app", path+"***");
		cap.setCapability("AndroidMobileCapabilityType.APP_PACKAGE", "***");
		cap.setCapability("AndroidMobileCapabilityType.APP_ACTIVITY","***");
		cap.setCapability("takesScreenshot", true); 
		cap.setCapability("appWaitActivity","***");
		
		try {
			driver = new AndroidDriver<MobileElement>(new URL("http://0.0.0.0:4723/wd/hub"), cap);
		} catch (MalformedURLException e) {
			Common.error = Common.error +"\n"+e;
			Common.error="Error in androidCap method : - \n"+Common.error;
			Common.failure=1;
			e.printStackTrace();
		}
		driver.manage().timeouts().implicitlyWait(35, TimeUnit.SECONDS);
		System.out.println("Session is created");
	}
	
	public static void login() throws Exception {  

		try {
			System.out.println("Login started");

			//Code for Demo build
			Thread.sleep(1000);
//			driver.findElement(By.xpath("//*[@name='Username']"));
			/*if(username!=null)
				System.out.println("Passed");
			else
				System.out.println("Failed");*/
			driver.findElement(By.xpath("//android.view.View[@text='Username']"));
//			MobileElement username = (MobileElement)(driver.findElement(By.name("Username")));
//			driver.findElement(By.xpath("//UIAButton[@name='Username']"));
			/*
//				xpath(@class='android.widget.EditText'));
			if(username!=null) {			
				username.sendKeys("***");
				Thread.sleep(500);
				driver.findElementByName("LoginButton").click();*/
/*			Thread.sleep(5000);
//			Allow the popup
				driver.switchTo().alert().accept();
				Thread.sleep(2000);
				driver.findElement(By.name("phoneNav_Open")).click();
				Thread.sleep(1000);
				driver.findElement(By.name("DashboardMenuItem")).click();
				
				Thread.sleep(2000);		
			}		
			else{
				System.out.println("Login page is not found");
			}
			System.out.println("Login successful");*/	
		} catch (Exception e) {
			Common.error = Common.error +"\n"+e;
			Common.error="Error in login method : - \n"+Common.error;
			Common.failure=1;
			e.printStackTrace();
		}
	}

**Comment by mykola-mokhnach** [comment]
I've asked for the page source, not the code

**Comment by hm2286** [comment]
I tried using "driver.getPageSource();" method but I am not able to fetch page source.

Can you suggest the alternate way.

**Comment by hm2286** [comment]
<img width="322" alt="pagesource" src="https://user-images.githubusercontent.com/41812001/43664524-d1fd78f6-978a-11e8-9b55-b766eafe94ef.PNG">

**Comment by hm2286** [comment]
Hope this image will help...

**Comment by hm2286** [comment]
<img width="363" alt="pagesource1" src="https://user-images.githubusercontent.com/41812001/43664624-299efa6c-978b-11e8-93a7-5748b908912f.PNG">

**Comment by mykola-mokhnach** [comment]
If the element is inside a web view then you must work with it being switched to web context. 
Also, don't expect native lookup to work if the page source cannot be retrieved.

http://appium.io/docs/en/writing-running-appium/web/hybrid/

**Comment by mykola-mokhnach** [comment]
> Hi, I checked the current context through function getcurrentcontext(). It gives as NATIVE but still my locators ae not working.

the web view should be compiled with debuggable option, so you could also inspect it with Chrome remote debugger. Double check the link above.

**Comment by hm2286** [comment]
@mykola-mokhnach : Thanks for your input. I am able to identify element and even able to send text.

But now the problem i am facing is with login button. A web element is seemingly clicked but in fact no action is performed. Any suggestion.

**Comment by mykola-mokhnach** [comment]
This must be a chromedriver issue. I'd try to click it using javascript and/or debug the actual events generated by the automated script and compare them to these generated by manual tap.
