### ISSUE TITLE
The revision field is always null in the /status output

### ISSUE THREAD

**Issue by mykola-mokhnach** [appium/appium#11159]
## The problem

When Selenium Grid requests /status for Appium node it always returns null as 'revision' field value 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.2-beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe): 8
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe: CLI

## Details

The problem under the hood is that `getGitRev` method expects that git meta information is present for the package. Although it is not true for packages installed from npm, since such meta info is stripped out upon publishing. So the command `git rev-parse HEAD` always fails with non-zero code.

**Comment by imurchie** [comment]
Yes. Release versions have never had a git revision.

**Comment by mykola-mokhnach** [comment]
Closed as fixed
