### ISSUE TITLE
iOS - Able to identify elements using name property but  using xpath not able to identify same element using Appium Desktop 1.8

### ISSUE THREAD

**Issue by CharanpreetHora** [appium/appium#11150]
## The problem

iOS - Able to identify elements using Appium desktop but find element not working at run time
driver.findElement(by).click();

## Environment

Appium 1.8
Any iOS

**Comment by ochubey** [comment]
It cannot find an element or cannot click on it?
Are you sure that there is only one element with the same identifier?
Please provide appium logs for the better understanding of a problem.

**Comment by CharanpreetHora** [comment]
Yes only one element. This is pretty strange. In fact for iOS this is not working for one of the Hybrid app functionality. We tried switch context as well. Able to identify elements using Appium desktop, but at runtime not able to click as find element not able to find element.

**Comment by mykola-mokhnach** [comment]
there's no way to help without logs

**Comment by mykola-mokhnach** [comment]
also it would be handy to see the page source before lookup operation is performed

**Comment by CharanpreetHora** [comment]
One important update on this. I am not able to identify element using By.name (By.name("main")). But if I am trying to identify using xpath it is not identifiable. //XCUIElementTypeOther[@name="main"].
We need to use xpath as this is a list and we need to traverse list to validate certain values. 
Any inputs on this will be highly appreciable.

**Comment by saikrishna321** [comment]
@CharanpreetHora By.name is replaced with AccessibilityId

**Comment by CharanpreetHora** [comment]
I have tried using //XCUIElementTypeLink[@accessibility id="main"]. Not working cannot find in Appium Desktop inspector itself. If I am using direct properties like name, Id then able to find elements. I have to use xpath as I need to traverse through list which is not possible without using index properties. This is very strange xpath search not working. Android it is working fine.

**Comment by CharanpreetHora** [comment]
Read //XCUIElementTypeOther[@accessibility id="main"].

**Comment by CharanpreetHora** [comment]
Someone told me the following statement 
"not to use xpath with iOS as XCUI API provided by apple are not efficient for xpath"

Is this correct statement?

**Comment by mykola-mokhnach** [comment]
Yes it [is](url
https://github.com/facebook/WebDriverAgent/wiki/How-To-Achieve-The-Best-Lookup-Performance)
