### ISSUE TITLE
safari real device - keep on Retrieving contexts and views

### ISSUE THREAD

**Issue by AbinashB** [appium/appium#11158]
webdriverIO- 4.9.8
Appium - 1.8.1
ios_webkit_debug_proxy 1.8 (running in separate port)
Built with libimobiledevice v1.2.1, libplist v2.0.0

**Observations**: able to connect the real device, webdriveragent is installed, able to open safari browser. by defult appium.io is opening always and keep on retrying.
only problem with safari browser automation, installing app and working with app is working fine.
not facing any issue if I run the same program on the simulator.

Attached **Appium log**:
[35m[Appium][39m Welcome to Appium v1.8.1 (REV 1b8e10e9c9440875520b0a104094a46a4409b7a4)
[35m[Appium][39m Appium REST http interface listener started on 0.0.0.0:4723
[35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[35m[HTTP][39m [90m{"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"udid":"67024c15cce700957f48773a4a18061d3535ced8","deviceName":"iPhone X","browserName":"Safari","platformVersion":"11.4","platformName":"ios","automationName":"XCUITest","orientation":"PORTRAIT","newCommandTimeout":"111000","showXcodeLog":true,"cssSelectorsEnabled":true,"nativeWebTap":true,"nativeEvents":true,"webkitDebugProxyPort":"9224","requestOrigins":{"url":"http://webdriver.io","version":"4.9.8","name":"webdriverio"}}}[39m
[debug] [35m[MJSONWP][39m Calling AppiumDriver.createSession() with args: [{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"udid":"67024c15cce700957f48773a4a18061d3535ced8","deviceName":"iPhone X","browserName":"Safari","platformVersion":"11.4","platformName":"ios","automationName":"XCUITest","orientation":"PORTRAIT","newCommandTimeout":"111000","showXcodeLog":true,"cssSelectorsEnabled":true,"nativeWebTap":true,"nativeEvents":true,"webkitDebugProxyPort":"9224","requestOrigins":{"url":"http://webdriver.io","version":"4.9.8","name":"webdriverio"}},null,null]
[debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1533702568134 (11:29:28 GMT+0700 (+07))
[35m[Appium][39m Creating new XCUITestDriver (v2.84.0) session
[35m[Appium][39m Capabilities:
[35m[Appium][39m   javascriptEnabled: true
[35m[Appium][39m   locationContextEnabled: true
[35m[Appium][39m   handlesAlerts: true
[35m[Appium][39m   rotatable: true
[35m[Appium][39m   udid: 67024c15cce700957f48773a4a18061d3535ced8
[35m[Appium][39m   deviceName: iPhone X
[35m[Appium][39m   browserName: Safari
[35m[Appium][39m   platformVersion: 11.4
[35m[Appium][39m   platformName: ios
[35m[Appium][39m   automationName: XCUITest
[35m[Appium][39m   orientation: PORTRAIT
[35m[Appium][39m   newCommandTimeout: 111000
[35m[Appium][39m   showXcodeLog: true
[35m[Appium][39m   cssSelectorsEnabled: true
[35m[Appium][39m   nativeWebTap: true
[35m[Appium][39m   nativeEvents: true
[35m[Appium][39m   webkitDebugProxyPort: 9224
[35m[Appium][39m   requestOrigins: {
[35m[Appium][39m     url: http://webdriver.io
[35m[Appium][39m     version: 4.9.8
[35m[Appium][39m     name: webdriverio
[35m[Appium][39m   }
[debug] [35m[BaseDriver][39m Creating session with MJSONWP desired capabilities: {"javascriptEnabled":true,"...
[35m[BaseDriver][39m Capability 'newCommandTimeout' changed from string ('111000') to integer (111000). This may cause unexpected behavior
[35m[BaseDriver][39m Capability 'webkitDebugProxyPort' changed from string ('9224') to integer (9224). This may cause unexpected behavior
[35m[BaseDriver][39m The following capabilities were provided, but are not recognized by appium: javascriptEnabled, locationContextEnabled, handlesAlerts, rotatable, cssSelectorsEnabled, nativeEvents, requestOrigins.
[35m[BaseDriver][39m Session created with session id: a2029ca7-de54-43aa-88af-b1c1db279550
[debug] [35m[XCUITest][39m Current user: 'abinash'
[debug] [35m[XCUITest][39m Xcode version set to '9.4.1' (tools v9.4.1.0.1.1528165917)
[debug] [35m[XCUITest][39m iOS SDK Version set to '11.4'
[debug] [35m[BaseDriver][39m Event 'xcodeDetailsRetrieved' logged at 1533702568326 (11:29:28 GMT+0700 (+07))
[debug] [35m[XCUITest][39m Available devices: 6b3f5db6830b6269da38a23e6016d44717a7a19e, 67024c15cce700957f48773a4a18061d3535ced8
[debug] [35m[XCUITest][39m Creating iDevice object with udid '67024c15cce700957f48773a4a18061d3535ced8'
[35m[XCUITest][39m Determining device to run tests on: udid: '67024c15cce700957f48773a4a18061d3535ced8', real device: true
[35m[XCUITest][39m Safari test requested
[debug] [35m[BaseDriver][39m Event 'appConfigured' logged at 1533702568483 (11:29:28 GMT+0700 (+07))
[debug] [35m[BaseDriver][39m Event 'resetStarted' logged at 1533702568484 (11:29:28 GMT+0700 (+07))
[debug] [35m[XCUITest][39m Reset: running ios real device reset flow
[debug] [35m[BaseDriver][39m Event 'resetComplete' logged at 1533702568484 (11:29:28 GMT+0700 (+07))
[debug] [35m[iOSLog][39m Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [35m[iOSLog][39m Starting iOS device log capture with: 'idevicesyslog'
[debug] [35m[BaseDriver][39m Event 'logCaptureStarted' logged at 1533702568671 (11:29:28 GMT+0700 (+07))
[35m[XCUITest][39m Setting up real device
[35m[XCUITest][39m Using WDA path: '/Users/abinash/Documents/jet/jet-e2e/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[35m[XCUITest][39m Using WDA agent: '/Users/abinash/Documents/jet/jet-e2e/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[debug] [35m[XCUITest][39m No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[debug] [35m[JSONWP Proxy][39m Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [35m[XCUITest][39m WDA is not listening at 'http://localhost:8100/'
[debug] [35m[BaseDriver][39m Event 'wdaStartAttempted' logged at 1533702568796 (11:29:28 GMT+0700 (+07))
[35m[XCUITest][39m Launching WebDriverAgent on the device
[debug] [35m[XCUITest][39m Carthage found: '/usr/local/bin/carthage'
[debug] [35m[XCUITest][39m Killing running processes 'xcodebuild.*67024c15cce700957f48773a4a18061d3535ced8, iproxy 8100' for the device 67024c15cce700957f48773a4a18061d3535ced8...
[debug] [35m[XCUITest][39m 'pgrep -nif xcodebuild.*67024c15cce700957f48773a4a18061d3535ced8' didn't detect any matching processes. Return code: 1
[debug] [35m[XCUITest][39m 'pgrep -nif iproxy 8100' didn't detect any matching processes. Return code: 1
[debug] [35m[XCUITest][39m Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [35m[XCUITest][39m Using Xcode 9.4.1, so fixing WDA codebase
[debug] [35m[XCUITest][39m Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Users/abinash/Documents/jet/jet-e2e/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=67024c15cce700957f48773a4a18061d3535ced8 IPHONEOS_DEPLOYMENT_TARGET=11.4' in directory '/Users/abinash/Documents/jet/jet-e2e/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [35m[XCUITest][39m Output from xcodebuild will be logged. To change this, use 'showXcodeLog' desired capability
[35m[Xcode][39m Build settings from command line:
[35m[Xcode][39m 
[debug] [35m[XCUITest][39m Waiting up to 60000ms for WebDriverAgent to start
[debug] [35m[JSONWP Proxy][39m Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[35m[Xcode][39m     IPHONEOS_DEPLOYMENT_TARGET = 11.4
[35m[Xcode][39m 
[35m[Xcode][39m 
[debug] [35m[JSONWP Proxy][39m Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"11.4.1\",\n      \"sdkVersion\" : \"11.3\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"11.4.1\",\n      \"ip\" : \"10.100.246.206\"\n    },\n    \"build\" : {\n      \"time\" : \"Aug  7 2018 15:54:58\"\n    }\n  },\n  \"sessionId\" : \"532FCBDC-67DE-4F0D-94DD-B97CC8E0ABEC\",\n  \"status\" : 0\n}"
[debug] [35m[XCUITest][39m WebDriverAgent running on ip '10.100.246.206'
[debug] [35m[XCUITest][39m WebDriverAgent successfully started after 1318ms
[debug] [35m[BaseDriver][39m Event 'wdaSessionAttempted' logged at 1533702575403 (11:29:35 GMT+0700 (+07))
[debug] [35m[XCUITest][39m Sending createSession command to WDA
[debug] [35m[JSONWP Proxy][39m Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.apple.mobilesafari","arguments":["-u","http://appium.io"],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[35m[Xcode][39m 2018-08-08 11:29:35.683 xcodebuild[73715:2058606]  DTDeviceKit: deviceType from 67024c15cce700957f48773a4a18061d3535ced8 was NULL
[35m[Xcode][39m 
[35m[Xcode][39m 2018-08-08 11:29:35.717 xcodebuild[73715:2058627]  DTDeviceKit: deviceType from 67024c15cce700957f48773a4a18061d3535ced8 was NULL
[35m[Xcode][39m 
[35m[Xcode][39m === BUILD TARGET WebDriverAgentLib OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===
[35m[Xcode][39m 
[35m[Xcode][39m 
[35m[Xcode][39m Check dependencies
[35m[Xcode][39m 
[35m[Xcode][39m 
[35m[Xcode][39m 
[35m[Xcode][39m === BUILD TARGET IntegrationApp OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===
[35m[Xcode][39m 
[35m[Xcode][39m 
[35m[Xcode][39m Check dependencies
[35m[Xcode][39m 
[35m[Xcode][39m Validate /Users/abinash/Library/Developer/Xcode/DerivedData/WebDriverAgent-aosmnxailrwwijewngcryehzspsx/Build/Products/Debug-iphoneos/IntegrationApp.app
[35m[Xcode][39m     cd /Users/abinash/Documents/jet/jet-e2e/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
[35m[Xcode][39m     export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/abinash/Documents/jet/jet-e2e/node_modules/.bin:/Users/abinash/.config/yarn/link/node_modules/.bin:/Users/abinash/Documents/jet/jet-e2e/node_modules/.bin:/Users/abinash/.config/yarn/link/node_modules/.bin:/usr/local/Cellar/node@8/8.11.1/libexec/lib/node_modules/npm/bin/node-gyp-bin:/usr/local/Cellar/node@8/8.11.1/lib/node_modules/npm/bin/node-gyp-bin:/usr/local/Cellar/node@8/8.11.1/bin/node_modules/npm/bin/node-gyp-bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
[35m[Xcode][39m     export PRODUCT_TYPE=com.apple.product-type.application
[35m[Xcode][39m     builtin-validationUtility /Users/abinash/Library/Developer/Xcode/DerivedData/WebDriverAgent-aosmnxailrwwijewngcryehzspsx/Build/Products/Debug-iphoneos/IntegrationApp.app
[35m[Xcode][39m 
[35m[Xcode][39m 
[35m[Xcode][39m === BUILD TARGET WebDriverAgentRunner OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===
[35m[Xcode][39m 
[35m[Xcode][39m 
[35m[Xcode][39m Check dependencies
[35m[Xcode][39m 
[35m[Xcode][39m 
[35m[Xcode][39m 
[35m[Xcode][39m ** TEST BUILD SUCCEEDED **
[35m[Xcode][39m 
[35m[Xcode][39m 
[debug] [35m[XCUITest][39m Log file for xcodebuild test: /var/folders/tl/8d_fk52d6p71vjvv2zlr32hw0000gn/T/com.apple.dt.XCTest/IDETestRunSession-B2315EBE-A669-46CF-A682-31677C1870CE/WebDriverAgentRunner-0C11C427-DDA4-4F64-8363-5FAB2556706F/Session-WebDriverAgentRunner-2561-08-08_112936-RgNTIB.log
[35m[Xcode][39m 2018-08-08 11:29:36.910 xcodebuild[73715:2058605]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
[35m[Xcode][39m /var/folders/tl/8d_fk52d6p71vjvv2zlr32hw0000gn/T/com.apple.dt.XCTest/IDETestRunSession-B2315EBE-A669-46CF-A682-31677C1870CE/WebDriverAgentRunner-0C11C427-DDA4-4F64-8363-5FAB2556706F/Session-WebDriverAgentRunner-2561-08-08_112936-RgNTIB.log
[35m[Xcode][39m 
[35m[Xcode][39m 2018-08-08 11:29:36.911 xcodebuild[73715:2058599] [MT] IDETestOperationsObserverDebug: (098ADB9A-E1BB-4DE1-871E-9CD9F1AC42FF) Beginning test session WebDriverAgentRunner-098ADB9A-E1BB-4DE1-871E-9CD9F1AC42FF at 2018-08-08 11:29:36.911 with Xcode 9F2000 on target <DVTiOSDevice: 0x7feb5f4977c0> {
[35m[Xcode][39m 		deviceSerialNumber:         G6TVWWVGJCLJ
[35m[Xcode][39m 		identifier:                 67024c15cce700957f48773a4a18061d3535ced8
[35m[Xcode][39m 		deviceClass:                iPhone
[35m[Xcode][39m 		deviceName:                 Abinasha Biswal’s iPhone
[35m[Xcode][39m 		deviceIdentifier:           67024c15cce700957f48773a4a18061d3535ced8
[35m[Xcode][39m 		productVersion:             11.4.1
[35m[Xcode][39m 		buildVersion:               15G77
[35m[Xcode][39m 		deviceSoftwareVersion:      11.4.1 (15G77)
[35m[Xcode][39m 		deviceArchitecture:         arm64
[35m[Xcode][39m 		deviceTotalCapacity:        60313497600
[35m[Xcode][39m 		deviceAvailableCapacity:    58102767616
[35m[Xcode][39m 		deviceIsTransient:          NO
[35m[Xcode][39m 		ignored:                    NO
[35m[Xcode][39m 		deviceIsBusy:               NO
[35m[Xcode][39m 		deviceIsActivated:          YES
[35m[Xcode][39m 		deviceActivationState:      Activated
[35m[Xcode][39m 		isPasscodeLocked:           NO
[35m[Xcode][39m 		deviceType:                 <DVTDeviceType:0x7feb5f31ad30 Xcode.DeviceType.iPhone>
[35m[Xcode][39m 		supportedDeviceFamilies:    (
[35m[Xcode][39m     1
[35m[Xcode][39m )
[35m[Xcode][39m 		applications:              (null)
[35m[Xcode][39m 		provisioningProfiles:      (null)
[35m[Xcode][39m 		hasInternalSupport:        NO
[35m[Xcode][39m 		isSupportedOS:             YES
[35m[Xcode][39m 		developerDiskMountError:   (null)
[35m[Xcode][39m (null)
[35m[Xcode][39m 	bootArgs:                  <unavailable>
[35m[Xcode][39m 		connected:                 yes
[35m[Xcode][39m 		isWirelessEnabled:         no
[35m[Xcode][39m 		connectionType:            direct
[35m[Xcode][39m 		} (11.4.1 (15G77))
[35m[Xcode][39m 
[35m[Xcode][39m MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
[35m[Xcode][39m state->old_bundle: /var/folders/tl/8d_fk52d6p71vjvv2zlr32hw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/5e57d765c0f0144baf65030af5f0e361/67024c15cce700957f48773a4a18061d3535ced8/WebDriverAgentRunner-Runner.app
[35m[Xcode][39m state->new_bundle: /Users/abinash/Library/Developer/Xcode/DerivedData/WebDriverAgent-aosmnxailrwwijewngcryehzspsx/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
[35m[Xcode][39m state->dst_bundle: /var/folders/tl/8d_fk52d6p71vjvv2zlr32hw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.Aa5tTX/WebDriverAgentRunner-Runner.app_sparse.ipa/Payload//WebDriverAgentRunner-Runner.app, binaryDiff flag: FALSE
[35m[Xcode][39m 	dst_ipa: /var/folders/tl/8d_fk52d6p71vjvv2zlr32hw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.Aa5tTX/WebDriverAgentRunner-Runner.app_sparse.ipa
[35m[Xcode][39m 
[35m[Xcode][39m MDMDirectoryDiff_block_invoke:1473 calling writeDictToFile with: /var/folders/tl/8d_fk52d6p71vjvv2zlr32hw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.Aa5tTX/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
[35m[Xcode][39m 
[35m[Xcode][39m writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/tl/8d_fk52d6p71vjvv2zlr32hw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.Aa5tTX/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
[35m[Xcode][39m 
[debug] [35m[XCUITest][39m Failed to create WDA session. Retrying...
[debug] [35m[BaseDriver][39m Event 'wdaSessionAttempted' logged at 1533702578352 (11:29:38 GMT+0700 (+07))
[debug] [35m[XCUITest][39m Sending createSession command to WDA
[debug] [35m[JSONWP Proxy][39m Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.apple.mobilesafari","arguments":["-u","http://appium.io"],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[debug] [35m[XCUITest][39m Failed to create WDA session. Retrying...
[debug] [35m[BaseDriver][39m Event 'wdaSessionAttempted' logged at 1533702579360 (11:29:39 GMT+0700 (+07))
[debug] [35m[XCUITest][39m Sending createSession command to WDA
[debug] [35m[JSONWP Proxy][39m Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.apple.mobilesafari","arguments":["-u","http://appium.io"],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[debug] [35m[XCUITest][39m Failed to create WDA session. Retrying...
[debug] [35m[BaseDriver][39m Event 'wdaSessionAttempted' logged at 1533702580368 (11:29:40 GMT+0700 (+07))
[debug] [35m[XCUITest][39m Sending createSession command to WDA
[debug] [35m[JSONWP Proxy][39m Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.apple.mobilesafari","arguments":["-u","http://appium.io"],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[debug] [35m[XCUITest][39m Failed to create WDA session. Retrying...
[debug] [35m[BaseDriver][39m Event 'wdaSessionAttempted' logged at 1533702581376 (11:29:41 GMT+0700 (+07))
[debug] [35m[XCUITest][39m Sending createSession command to WDA
[debug] [35m[JSONWP Proxy][39m Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.apple.mobilesafari","arguments":["-u","http://appium.io"],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[debug] [35m[XCUITest][39m Failed to create WDA session. Retrying...
[debug] [35m[BaseDriver][39m Event 'wdaSessionAttempted' logged at 1533702582386 (11:29:42 GMT+0700 (+07))
[debug] [35m[XCUITest][39m Sending createSession command to WDA
[debug] [35m[JSONWP Proxy][39m Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.apple.mobilesafari","arguments":["-u","http://appium.io"],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[debug] [35m[XCUITest][39m Failed to create WDA session. Retrying...
[debug] [35m[BaseDriver][39m Event 'wdaSessionAttempted' logged at 1533702583394 (11:29:43 GMT+0700 (+07))
[debug] [35m[XCUITest][39m Sending createSession command to WDA
[debug] [35m[JSONWP Proxy][39m Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.apple.mobilesafari","arguments":["-u","http://appium.io"],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[debug] [35m[JSONWP Proxy][39m Got response with status 200: {"value":{"sessionId":"69D666CE-2F91-44C0-8827-F808742DE478","capabilities":{"device":"iphone","browserName":"Safari","sdkVersion":"11.4.1","CFBundleIdentifier":"com.apple.mobilesafari"}},"sessionId":"69D666CE-2F91-44C0-8827-F808742DE478","status":0}
[debug] [35m[BaseDriver][39m Event 'wdaSessionStarted' logged at 1533702585078 (11:29:45 GMT+0700 (+07))
[debug] [35m[BaseDriver][39m Event 'wdaStarted' logged at 1533702585078 (11:29:45 GMT+0700 (+07))
[debug] [35m[XCUITest][39m Setting initial orientation to 'PORTRAIT'
[debug] [35m[JSONWP Proxy][39m Proxying [POST /orientation] to [POST http://localhost:8100/session/69D666CE-2F91-44C0-8827-F808742DE478/orientation] with body: {"orientation":"PORTRAIT"}
[debug] [35m[JSONWP Proxy][39m Got response with status 200: {"value":{},"sessionId":"69D666CE-2F91-44C0-8827-F808742DE478","status":0}
[debug] [35m[BaseDriver][39m Event 'orientationSet' logged at 1533702586627 (11:29:46 GMT+0700 (+07))
[debug] [35m[XCUITest][39m Waiting for initial webview
[debug] [35m[iOS][39m Waiting for 3000 ms before navigating to view.
[debug] [35m[iOS][39m Navigating to most recently opened webview
[debug] [35m[iOS][39m Retrieving contexts and views
[debug] [35m[iOS][39m Selecting by url: true (expected url: 'http://appium.io')
[debug] [35m[RemoteDebugger][39m Getting WebKitRemoteDebugger pageArray: localhost, 9224
[debug] [35m[RemoteDebugger][39m Sending request to: http://localhost:9224/json
[debug] [35m[RemoteDebugger][39m Page element JSON: [{"devtoolsFrontendUrl":"/devtools/devtools.html?ws=localhost:9224/devtools/page/3","faviconUrl":"","thumbnailUrl":"/thumb/http://appium.io/","title":"Appium: Mobile App Automation Made Awesome.","url":"http://appium.io/","webSocketDebuggerUrl":"ws://localhost:9224/devtools/page/3","appId":"PID:1048"}]
[debug] [35m[iOS][39m Retrieving contexts and views
[debug] [35m[iOS][39m Selecting by url: true (expected url: 'http://appium.io')
[debug] [35m[RemoteDebugger][39m Getting WebKitRemoteDebugger pageArray: localhost, 9224
[debug] [35m[RemoteDebugger][39m Sending request to: http://localhost:9224/json
[debug] [35m[RemoteDebugger][39m Page element JSON: [{"devtoolsFrontendUrl":"/devtools/devtools.html?ws=localhost:9224/devtools/page/3","faviconUrl":"","thumbnailUrl":"/thumb/http://appium.io/","title":"Appium: Mobile App Automation Made Awesome.","url":"http://appium.io/","webSocketDebuggerUrl":"ws://localhost:9224/devtools/page/3","appId":"PID:1048"}]
[debug] [35m[iOS][39m Picking webview 'WEBVIEW_3'
[debug] [35m[iOS][39m Attempting to set context to 'WEBVIEW_3'
[debug] [35m[RemoteDebugger][39m WebKit debugger web socket connected to url: ws://localhost:9224/devtools/page/3
[debug] [35m[RemoteDebugger][39m Starting to listen for JavaScript console
[debug] [35m[RemoteDebugger][39m Sending WebKit data: {"method":"Console.enable","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true}}
[debug] [35m[RemoteDebugger][39m Webkit response timeout: 5000
[debug] [35m[RemoteDebugger][39m Receiving WebKit data: '{"result":{},"id":1}'
[debug] [35m[RemoteDebugger][39m Found handler for message '1'
[debug] [35m[RemoteDebugger][39m WebKit debugger got a message for 'Console.enable' and have no handler, doing nothing.
[35m[XCUITest][39m TimeoutError: operation timed out
[35m[XCUITest][39m     at afterTimeout (/Users/abinash/Documents/jet/jet-e2e/node_modules/appium/node_modules/bluebird/js/release/timers.js:46:19)
[35m[XCUITest][39m     at Timeout.timeoutTimeout [as _onTimeout] (/Users/abinash/Documents/jet/jet-e2e/node_modules/appium/node_modules/bluebird/js/release/timers.js:76:13)
[35m[XCUITest][39m     at ontimeout (timers.js:482:11)
[35m[XCUITest][39m     at tryOnTimeout (timers.js:317:5)
[35m[XCUITest][39m     at Timer.listOnTimeout (timers.js:277:5)
[debug] [35m[JSONWP Proxy][39m Proxying [DELETE /session/a2029ca7-de54-43aa-88af-b1c1db279550] to [DELETE http://localhost:8100/session/69D666CE-2F91-44C0-8827-F808742DE478] with no body
[debug] [35m[JSONWP Proxy][39m Got response with status 200: "{\n  \"value\" : {\n\n  },\n  \"sessionId\" : \"2EAE7F8F-CEB0-4BB3-90CB-910268CEB7FB\",\n  \"status\" : 0\n}"
[debug] [35m[XCUITest][39m Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [35m[XCUITest][39m In a web session. Removing remote debugger
[debug] [35m[RemoteDebugger][39m Disconnecting from WebKit remote debugger
[debug] [35m[iOSLog][39m Stopping iOS log capture
[debug] [35m[RemoteDebugger][39m WebKit remote debugger socket disconnected
[debug] [35m[BaseDriver][39m Event 'newSessionStarted' logged at 1533702594882 (11:29:54 GMT+0700 (+07))
[35m[MJSONWP][39m Encountered internal error running command: TimeoutError: operation timed out
[35m[MJSONWP][39m     at afterTimeout (/Users/abinash/Documents/jet/jet-e2e/node_modules/appium/node_modules/bluebird/js/release/timers.js:46:19)
[35m[MJSONWP][39m     at Timeout.timeoutTimeout [as _onTimeout] (/Users/abinash/Documents/jet/jet-e2e/node_modules/appium/node_modules/bluebird/js/release/timers.js:76:13)
[35m[MJSONWP][39m     at ontimeout (timers.js:482:11)
[35m[MJSONWP][39m     at tryOnTimeout (timers.js:317:5)
[35m[MJSONWP][39m     at Timer.listOnTimeout (timers.js:277:5)
[35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[31m500[39m [90m26755 ms - 156[39m
[35m[HTTP][39m [90m[39m

**Comment by AbinashB** [comment]
logs form ios_webkit_debug_proxy : curl --get http://localhost:9224/json
[{
   "devtoolsFrontendUrl": "/devtools/devtools.html?ws=localhost:9224/devtools/page/3",
   "faviconUrl": "",
   "thumbnailUrl": "/thumb/http://appium.io/",
   "title": "Appium: Mobile App Automation Made Awesome.",
   "url": "http://appium.io/",
   "webSocketDebuggerUrl": "ws://localhost:9224/devtools/page/3",
   "appId": "PID:1048"
}]%

**Comment by mykola-mokhnach** [comment]
This should be addressed in appium@beta

**Comment by AbinashB** [comment]
Hey, are you able to reproduce it? am I missing something?

**Comment by AbinashB** [comment]
changed appium to 1.7.2 and now it is working fine.
