### ISSUE TITLE
WDA fails to initialize with xcodebuild failure "DVTAssertion: macroName should be a non-empty string, but it's an empty string"

### ISSUE THREAD

**Issue by NortonMob** [appium/appium#11156]
## The Problem
Xcode fails to initialize WebDriverAgent in Appium 1.6.2 with error: 
>[Xcode] 2018-08-06 11:50:41.848 xcodebuild[35538:235363] [MT] DVTAssertions: ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-14141/DVTFoundation/MacroExpansion/DVTMacroDefinitionTable.mm:966
[Xcode] Details:  macroName should be a non-empty string, but it's an empty string

## Environment
* Appium desktop version 1.6.2
* Desktop OS/version used to run Appium: macOS 10.13.3
* Xcode version set to '9.4.1' (tools v9.1.0.0.1.1508540944)
* Mobile platform/version under test: iOS 11.4.1
* Real device or emulator/simulator: Real Device (iPhone 7 Plus)
* Appium CLI or Appium.app|exe: Appium.app

## Details
I have been unable to get any recent version of Appium desktop to initialize the WDA at startup. I seem to constantly run into this DVTAssertions issue on Xcode. I have tried several versions of Xcode (9.2-9.4.1) and several version of Appium desktop. I am able to get is running under Appium 1.4.2 or 1.5.0, and then update to 1.6.2, but within hours or days, the WDA will stop initializing at startup. This kind of looks like an environment issue with Xcode to me, but it is a bit above my head to figure out what exactly is going on.

## Link to Appium logs
Gist: https://gist.github.com/NortonMob/6e67cb145726477341004f7cc1ccb7ff
Error in gist log:

> [Xcode] 2018-08-06 12:21:33.704 xcodebuild[36700:259863] [MT] DVTAssertions: ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-14141/DVTFoundation/MacroExpansion/DVTMacroDefinitionTable.mm:966
[Xcode] Details:  macroName should be a non-empty string, but it's an empty string
[Xcode] Object:   
[Xcode] Method:   -setValue:forMacroName:conditionSet:
[Xcode] Thread:   {number = 1, name = main}
[Xcode] Hints: 
[Xcode] 
[Xcode] Backtrace:
[Xcode]   0   -[DVTAssertionHandler handleFailureInMethod:object:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in DVTFoundation)
[Xcode]   1   _DVTAssertionHandler (in DVTFoundation)
[Xcode]   2   _DVTAssertionFailureHandler (in DVTFoundation)
[Xcode]   3   -[DVTMacroDefinitionTable setValue:forMacroName:conditionSet:] (in DVTFoundation)
[Xcode]   4   -[DVTMacroDefinitionTable(XCMacroExpansionExtensions) _xc_setValue:forMacroName:conditionSet:errorHandler:] (in DevToolsCore)
[Xcode]   5   -[DVTMacroDefinitionTable(XCMacroExpansionExtensions) _xc_setValue:forMacroName:errorHandler:] (in DevToolsCore)
[Xcode]   6   __108-[DVTMacroDefinitionTable(XCMacroExpansionExtensions) xc_setMacroNamesAndValuesFromDictionary:errorHandler:]_block_invoke (in DevToolsCore)
[Xcode]   7   -[__NSFrozenDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] (in CoreFoundation)
[Xcode]   8   -[DVTMacroDefinitionTable(XCMacroExpansionExtensions) xc_setMacroNamesAndValuesFromDictionary:errorHandler:] (in DevToolsCore)
[Xcode]   9   -[NSProcessInfo(XCMacroExpansionExtensions) xc_cachedEnvironmentAsMacroDefinitionTable] (in DevToolsCore)
[Xcode]  10   -[PBXTarget createMacroExpansionScopeWithBuildParameters:] (in DevToolsCore)
[Xcode]  11   -[PBXTarget cachedMacroExpansionScopeForBuildParameters:] (in DevToolsCore)
[Xcode]  12   -[PBXTarget expandedValueForString:forBuildParameters:] (in DevToolsCore)
[Xcode]  13   -[PBXNativeTarget fullProductNameForBuildParameters:] (in DevToolsCore)
[Xcode]  14   -[PBXNativeTarget fullProductNameForConfigurationNamed:] (in DevToolsCore)
[Xcode]  15   -[PBXTarget fullProductName] (in DevToolsCore)
[Xcode]  16   -[PBXReference setProducingTarget:] (in DevToolsCore)
[Xcode]  17   -[PBXTarget awakeFromPListUnarchiver:] (in DevToolsCore)
[Xcode]  18   -[PBXNativeTarget awakeFromPListUnarchiver:] (in DevToolsCore)
[Xcode]  19   -[NSArray makeObjectsPerformSelector:withObject:] (in CoreFoundation)
[Xcode]  20   -[PBXPListUnarchiver decodeRootObject] (in DevToolsCore)
[Xcode]  21   +[PBXProject projectWithFile:errorHandler:readOnly:] (in DevToolsCore)
[Xcode]  22   -[Xcode3Project initWithFilePath:extension:workspace:options:error:] (in DevToolsCore)
[Xcode]  23   __82+[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:]_block_invoke_2 (in IDEFoundation)
[Xcode]  24   _dispatch_client_callout (in libdispatch.dylib)
[Xcode]  25   _dispatch_queue_barrier_sync_invoke_and_complete (in libdispatch.dylib)
[Xcode]  26   DVTDispatchBarrierSync (in DVTFoundation)
[Xcode]  27   -[DVTDispatchLock performLockedBlock:] (in DVTFoundation)
[Xcode]  28   __82+[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:]_block_invoke (in IDEFoundation)
[Xcode]  29   __58-[DVTModelObjectGraph performBlockCoalescingModelChanges:]_block_invoke (in DVTFoundation)
[Xcode]  30   -[DVTModelGraphTransactionScope performTransaction:] (in DVTFoundation)
[Xcode]  31   -[DVTModelObjectGraph performBlockCoalescingModelChanges:] (in DVTFoundation)
[Xcode]  32   +[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:] (in IDEFoundation)
[Xcode]  33   +[IDEContainer retainedContainerAtFilePath:fileDataType:workspace:error:] (in IDEFoundation)
[Xcode]  34   -[IDEWorkspace _configureWrappedWorkspaceWithError:] (in IDEFoundation)
[Xcode]  35   __82+[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:]_block_invoke (in IDEFoundation)
[Xcode]  36   +[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:] (in IDEFoundation)
[Xcode]  37   +[IDEContainer retainedWrappedWorkspaceForContainerAtFilePath:fileDataType:error:] (in IDEFoundation)
[Xcode]  38   -[Xcode3CommandLineBuildTool _resolveInputOptionsWithTimingSection:] (in Xcode3Core)
[Xcode]  39   -[Xcode3CommandLineBuildTool run] (in Xcode3Core)
[Xcode]  40   main (in xcodebuild)
[Xcode]  41   start (in libdyld.dylib)
[Xcode] 
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGABRT'

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/facebook/WebDriverAgent
