### ISSUE TITLE
TouchAction does not work on SauceLabs

### ISSUE THREAD

**Issue by schwarcu** [appium/appium#11160]
## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Desktop OS/version used to run Appium: MacOS 10.13.5
* Mobile platform/version under test: 11.2
* Real device or emulator/simulator: iPad Air Simulator

## The problem
When running tests on SauceLabs  TouchAction is never executed. Works on local device emulator with no issues.

TouchAction action = new TouchAction(driver);
action.tap(X, Y).perform();

## Code To Reproduce Issue [ Good To Have ]
Due to company policy, I am not able to share logs and the code to reproduce. 
But the reproduction is pretty simple:

1. Run the test app on iOS device emulator
2. Try to use TouchAction to perform click or swipe.
3. Run the same test on saucelabs, same iOS device emulator
4. Try to use TouchAction to perform click or swipe.

Result: tap does not work, no action is executed when running on SauceLabs. On local device emulator, it works fine.

**Comment by mykola-mokhnach** [comment]
Please try with Appium 1.8.1. We do not patch older Appium versions. Also, it is not possible to suggest anything more without server logs. Sorry.

**Comment by imurchie** [comment]
Can you provide a link to a job so we can have some idea of what is going on? There is little that can be done without something to go on.

**Comment by imurchie** [comment]
A job will be necessary. I can produce working touch actions on Sauce Labs, so it is not a general problem.

code: https://gist.github.com/imurchie/63d57e8d3e10a01ab27972f3ceeaf8ce
Sauce: https://saucelabs.com/beta/tests/cefab2b858c04814a7b7547a63c797ea/commands#0
