### ISSUE TITLE
Launching app on real iOS device failing with latest Appium Desktop version 1.6.3

### ISSUE THREAD

**Issue by ashishyadav2020** [appium/appium#11164]
## The problem
I have downloaded latest Appium desktop version for Mac. While running my old test scripts which used to work with previous Appium verison, failing with:
The 'idevice_id' program is not installed. If you are running a real device test it is necessary. Install with 'brew install libimobiledevice --HEAD'

## Environment

* Appium version (or git revision) that exhibits the issue: Desktop version 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): Desktop version 1.6.2
* Desktop OS/version used to run Appium: MacOS 10.38.6
* Node.js version (unless using Appium.app|exe): 8.9.0
* Mobile platform/version under test: iOS 11.3
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium.app

## Details

I have checked connected real device using command:
idevice_id --list
and it shows connected real device id (single device).

Also, Added path 'idevice_id' to $PATH variable and 'echo $PATH' command showing the updated path.

I tried executing command (provided in Appium error logs as solution):
'brew install libimobiledevice --HEAD'
and, it returned with 'already installed'. Though I tried reinstall as well and getting same problem.

## Link to Appium logs

https://gist.github.com/ashishyadav2020/088f768c0f2dd0f5f80a9e59d707ddef

**Comment by mykola-mokhnach** [comment]
It might be that Appium desktop does not pick up you PATH value. Check https://github.com/appium/java-client/blob/master/docs/environment.md for more details.

Please report your issue to https://github.com/appium/appium-desktop if it still happens
