### ISSUE TITLE
Not able to upgrade the chrome browser at 7.0 emulator

### ISSUE THREAD

**Issue by PoonamBairagi** [appium/appium#11167]
I want to upgrade the chrome browser at Android 7.0 emulator.
I followed this steps from this link https://github.com/appium/appium/issues/7179

1. C:\Users\poonam\AppData\Local\Android\Sdk\emulator\emulator -avd Nexus1 -writable-system 
used this command to start emulator and then do above instructions.

2. used the CMD to uninstall it using these commands
  ```
  adb root
  adb remount
  adb shell
  cd system
  cd app
  rm Chrome -f -rR
  ```
But i am getting this error in my command prompt screen

UpdateLayeredWindowIndirect failed for ptDst=(-251, 31), size=(300x21), dirty=(300x21 0, 0) (A device attached to the system is not functioning.)
![image](https://user-images.githubusercontent.com/42250192/43919263-662bb568-9be3-11e8-97b7-380e6086fe86.png)

## Environment
Windows 10- 64 bit
Android Studio 3.1.3
Build #AI-173.4819257, built on June 4, 2018
JRE: 1.8.0_152-release-1024-b02 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by mykola-mokhnach** [comment]
How this is related to Appium?

**Comment by PoonamBairagi** [comment]
**I am a beginner in appium so i used below code to try a small test**

package browser_tests;

import java.net.MalformedURLException;
import java.net.URL;

import org.openqa.selenium.remote.DesiredCapabilities;
import io.appium.java_client.AppiumDriver;
import io.appium.java_client.MobileElement;
import io.appium.java_client.android.AndroidDriver;

public class ChromeTest {

	public static void main(String[] args) {
		
		//Set the Desired Capabilities
		DesiredCapabilities caps = new DesiredCapabilities();

		caps.setCapability("deviceName", "Nexus1");
		caps.setCapability("udid", "emulator-5554"); //Give Device ID of your mobile phonecaps.setCapability("platformName", "Android");
		caps.setCapability("platformVersion", "7.0");
		caps.setCapability("browserName", "Chrome");
		caps.setCapability("launchTimeout", "200000");
		caps.setCapability("noReset", true);
		caps.setCapability("skipUnlock", true);

		
		//Set ChromeDriver location
        System.setProperty("webdriver.chrome.driver", "D:\\ChromeDri\\chromedriver.exe");
		
		//Instantiate Appium Driver
		AppiumDriver<MobileElement> driver = null;
		try {
			driver = new AndroidDriver<MobileElement>(new URL("http://0.0.0.0:4723/wd/hub"), caps);
			
		} catch (MalformedURLException e) {
			System.out.println(e.getMessage());
		}
				
		//Open URL in Chrome Browser
		driver.get("https://google.com");
	}
}

**I got below error in appium. I searched solution for it and found that i need to upgrade my chrome version for emulator or Avd.  I am trying to do that and i facing the challenge mentioned above. **


The server is running

[Appium] Welcome to Appium v1.8.1
[Appium] Non-default server args:
[Appium]   sessionOverride: true
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"noReset":true,"platformVersion":"7.0","browserName":"Chrome","skipUnlock":true,"platformName":"Android","udid":"emulator-5554","deviceName":"Nexus1","launchTimeout":"200000"},"capabilities":{"alwaysMatch":{"browserName":"Chrome","appium:deviceName":"Nexus1","appium:launchTimeout":"200000","appium:noReset":true,"platformName":"android","appium:platformVersion":"7.0","skipUnlock":true,"appium:udid":"emulator-5554"},"firstMatch":[{}]}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"noReset":true,"platformVersion":"7.0","browserName":"Chrome","skipUnlock":true,"platformName":"Android","udid":"emulator-5554","deviceName":"Nexus1","launchTimeout":"200000"},null,{"alwaysMatch":{"browserName":"Chrome","appium:deviceName":"Nexus1","appium:launchTimeout":"200000","appium:noReset":true,"platformName":"android","appium:platformVersion":"7.0","skipUnlock":true,"appium:udid":"emulator-5554"},"firstMatch":[{}]}]
[BaseDriver] Event 'newSessionRequested' logged at 1533896491845 (06:21:31 GMT-0400 (Eastern Daylight Time))
[BaseDriver] The capabilities ["skipUnlock"] are not standard capabilities and should have an extension prefix
[Appium] Consider setting 'automationName' capability to 'uiautomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.
[Appium] Creating new AndroidDriver (v2.7.0) session
[Appium] Capabilities:
[Appium]   browserName: Chrome
[Appium]   platformName: android
[Appium]   skipUnlock: true
[Appium]   deviceName: Nexus1
[Appium]   launchTimeout: 200000
[Appium]   noReset: true
[Appium]   platformVersion: 7.0
[Appium]   udid: emulator-5554
[BaseDriver] W3C capabilities {"alwaysMatch":{"browserNam... and MJSONWP desired capabilities [object Object] were provided
[BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"browserNam...
[BaseDriver] The following capabilities were provided, but are not recognized by appium: launchTimeout.
[BaseDriver] Session created with session id: 5724094d-79fb-4686-9df2-c512b8caf42b
[AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_181
[AndroidDriver] We're going to run a Chrome-based session
[AndroidDriver] Chrome-type package and activity are com.android.chrome and com.google.android.apps.chrome.Main
[ADB] Checking whether adb is present
[ADB] Found 2 'build-tools' folders under 'C:\Users\poonam\AppData\Local\Android\Sdk' (newest first):
[ADB]     C:/Users/poonam/AppData/Local/Android/Sdk/build-tools/28.0.1
[ADB]     C:/Users/poonam/AppData/Local/Android/Sdk/build-tools/27.0.3
[ADB] Using adb.exe from C:\Users\poonam\AppData\Local\Android\Sdk\platform-tools\adb.exe
[AndroidDriver] Retrieving device list
[ADB] Trying to find a connected android device
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[AndroidDriver] Using device: emulator-5554
[ADB] Setting device id to emulator-5554
[AndroidDriver] App file was not listed, instead we're going to run com.android.chrome directly on the device
[AndroidDriver] Checking whether package is present on the device
[ADB] Running 'C:\Users\poonam\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pm list packages com.android.chrome'
[AndroidDriver] Starting Android session
[ADB] Running 'C:\Users\poonam\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 wait-for-device'
[ADB] Running 'C:\Users\poonam\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell echo ping'
[AndroidDriver] Pushing settings apk to device...
[ADB] Getting install status for io.appium.settings
[ADB] Running 'C:\Users\poonam\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pm list packages io.appium.settings'
[ADB] App is not installed
[ADB] App 'C:\Users\poonam\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\io.appium.settings\app\build\outputs\apk\settings_apk-debug.apk' not installed. Installing
[ADB] Running 'C:\Users\poonam\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk'
[ADB] Current device property 'ro.build.version.sdk': 24
[ADB] Device API level: 24
[ADB] Running 'C:\Users\poonam\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 install -g C\:\\Users\\poonam\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\io.appium.settings\\app\\build\\outputs\\apk\\settings_apk-debug.apk'
[ADB] Install command stdout: Success
[ADB] Running 'C:\Users\poonam\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell ps'
[ADB] Device API level: 24
[ADB] Running 'C:\Users\poonam\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell am start -W -n io.appium.settings/.Settings -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[ADB] Device API level: 24
[ADB] Running 'C:\Users\poonam\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell appops set io.appium.settings android\:mock_location allow'
[AndroidDriver] setDeviceLanguageCountry requires language or country.
[AndroidDriver] Got language: 'undefined' and country: 'undefined'
[Logcat] Starting logcat capture
[AndroidDriver] Pushing unlock helper app to device...
[ADB] Getting install status for io.appium.unlock
[ADB] Running 'C:\Users\poonam\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pm list packages io.appium.unlock'
[ADB] App is not installed
[ADB] App 'C:\Users\poonam\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-unlock\bin\unlock_apk-debug.apk' not installed. Installing
[ADB] Device API level: 24
[ADB] Running 'C:\Users\poonam\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 install -g C\:\\Users\\poonam\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-unlock\\bin\\unlock_apk-debug.apk'
[ADB] Install command stdout: Success
[ADB] Getting device platform version
[ADB] Running 'C:\Users\poonam\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.release'
[ADB] Current device property 'ro.build.version.release': 7.0
[ADB] Running 'C:\Users\poonam\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell wm size'
[ADB] Running 'C:\Users\poonam\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.product.model'
[ADB] Current device property 'ro.product.model': Android SDK built for x86_64
[ADB] Running 'C:\Users\poonam\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.product.manufacturer'
[ADB] Current device property 'ro.product.manufacturer': unknown
[AndroidDriver] No app sent in, not parsing package/activity
[AndroidDriver] No app capability. Assuming it is already on the device
[AndroidBootstrap] Watching for bootstrap disconnect
[ADB] Forwarding system: 4724 to device: 4724
[ADB] Running 'C:\Users\poonam\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 forward tcp\:4724 tcp\:4724'
[UiAutomator] Starting UiAutomator
[UiAutomator] Moving to state 'starting'
[UiAutomator] Parsing uiautomator jar
[UiAutomator] Found jar name: 'AppiumBootstrap.jar'
[ADB] Running 'C:\Users\poonam\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 push C\:\\Users\\poonam\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-android-bootstrap\\bootstrap\\bin\\AppiumBootstrap.jar /data/local/tmp/'
[ADB] Attempting to kill all uiautomator processes
[ADB] Getting all processes with uiautomator
[ADB] Running 'C:\Users\poonam\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell ps'
[ADB] No uiautomator process found to kill, continuing...
[UiAutomator] Starting UIAutomator
[ADB] Creating ADB subprocess with args: ["-P",5037,"-s","emulator-5554","shell","uiautomator","runtest","AppiumBootstrap.jar","-c","io.appium.android.bootstrap.Bootstrap","-e","pkg","com.android.chrome","-e","disableAndroidWatchers",false,"-e","acceptSslCerts",false]
[UiAutomator] Moving to state 'online'
[AndroidBootstrap] Android bootstrap socket is now connected
[AndroidDriver] Starting a chrome-based browser session
[AndroidDriver] A port was not given, using random port: 8000
[Chromedriver] Changed state to 'starting'
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Client connected
[Chromedriver] The following Chromedriver executables were found:
[Chromedriver]     C:/Users/poonam/AppData/Local/Programs/Appium/resources/app/node_modules/appium/node_modules/appium-chromedriver/chromedriver/win/chromedriver.exe (minimum Chrome version '65.0.3325')
[ADB] Getting package info for 'com.android.chrome'
[ADB] Running 'C:\Users\poonam\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys package com.android.chrome'
[Chromedriver] Found Chrome bundle 'com.android.chrome' version '51.0.2704'
[Chromedriver] Error: No Chromedriver found that can automate Chrome '51.0.2704'. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md for more details.
[Chromedriver]     at Object.wrappedLogger.errorAndThrow (C:\Users\poonam\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:78:13)
[Chromedriver]     at Chromedriver.getCompatibleChromedriver$ (C:\Users\poonam\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-chromedriver\lib\chromedriver.js:227:11)
[Chromedriver]     at tryCatch (C:\Users\poonam\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[Chromedriver]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\poonam\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[Chromedriver]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\poonam\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[Chromedriver]     at GeneratorFunctionPrototype.invoke (C:\Users\poonam\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[Chromedriver]     at 
[Chromedriver] Error: No Chromedriver found that can automate Chrome '51.0.2704'. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md for more details.
[Chromedriver]     at Object.wrappedLogger.errorAndThrow (C:\Users\poonam\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:78:13)
[Chromedriver]     at Chromedriver.getCompatibleChromedriver$ (C:\Users\poonam\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-chromedriver\lib\chromedriver.js:227:11)
[Chromedriver]     at tryCatch (C:\Users\poonam\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[Chromedriver]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\poonam\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[Chromedriver]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\poonam\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[Chromedriver]     at GeneratorFunctionPrototype.invoke (C:\Users\poonam\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[Chromedriver]     at 
[AndroidDriver] Shutting down Android driver
[ADB] Pressing the HOME button
[ADB] Running 'C:\Users\poonam\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell input keyevent 3'
[AndroidBootstrap] Sending command to android: {"cmd":"shutdown"}
[AndroidBootstrap] Received command result from bootstrap
[UiAutomator] Shutting down UiAutomator
[UiAutomator] Moving to state 'stopping'
[UiAutomator] UiAutomator shut down normally
[UiAutomator] Moving to state 'stopped'
[ADB] Attempting to kill all uiautomator processes
[ADB] Getting all processes with uiautomator
[ADB] Running 'C:\Users\poonam\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell ps'
[ADB] No uiautomator process found to kill, continuing...
[UiAutomator] Moving to state 'stopped'
[Logcat] Stopping logcat capture
[ADB] Running 'C:\Users\poonam\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell am force-stop io.appium.unlock'
[AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[BaseDriver] Event 'newSessionStarted' logged at 1533896515465 (06:21:55 GMT-0400 (Eastern Daylight Time))
[W3C] Encountered internal error running command: Error: No Chromedriver found that can automate Chrome '51.0.2704'. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md for more details.
[W3C]     at Object.wrappedLogger.errorAndThrow (C:\Users\poonam\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:78:13)
[W3C]     at Chromedriver.getCompatibleChromedriver$ (C:\Users\poonam\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-chromedriver\lib\chromedriver.js:227:11)
[W3C]     at tryCatch (C:\Users\poonam\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\poonam\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\poonam\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[W3C]     at GeneratorFunctionPrototype.invoke (C:\Users\poonam\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[W3C]     at 
[HTTP] <-- POST /wd/hub/session 500 25189 ms - 1794
[HTTP]

**Comment by mykola-mokhnach** [comment]
You can either upgrade chrome or downgrade the chromedriver version like it is described in https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md.

**Comment by PoonamBairagi** [comment]
I already tried to downgrade the chromedriver version as mentioned in link
shared buy you. But it gave the same error.

So i tried to upgrade chrome on my emulator/avd and which is also not
working. Thats why i created this thread.

**Comment by mykola-mokhnach** [comment]
Closed as inactive

**Comment by PoonamBairagi** [comment]
I  have not found solution for it. I  think you also don't have solution for it. Thank you.

**Comment by mykola-mokhnach** [comment]
I'd try another emulator version. There are also different emulator implementations (I mean not one the one from Google)

**Comment by deepak4175** [comment]
I was also struggling with this issue.
one of the of setting chromedriver is to:
1. Download chromedriver for your required chrome version from [appium site](http://appium.io/docs/en/writing-running-appium/web/chromedriver/)
2. Extract the chromedriver to location "C:\Users\Admin\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win"
 (i.e. This is the location where appium store chromedriver) .
3. Delete the existing chromedriver at that location. And paste your required chromedriver overther.
4.start your appium server.
For Me it is working fine. Try yours
