### ISSUE TITLE
Appium inspector not able to tap on an element successfully

### ISSUE THREAD

**Issue by dokmetas** [appium/appium#11162]
## The problem

Appium inspector is not able to tap on a particular element successfully, appium logs say it did but I do not observe it on the phone screen.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Windows 10 Enterprise x64
* Node.js version (unless using Appium.app|exe): N/A
* Mobile platform/version under test: Android version 5.0
* Real device or emulator/simulator: Real Device, Samsung Galaxy Note3
* Appium CLI or Appium.app|exe: Appium.exe, Graphical interface for the Appium server, and an app inspector.

## Details

1. Opened up Appium inspector and My Application is opened
2. Navigated to the phone screen that contains the element I am trying to tap on
3. The element I am trying to tap on was not in view so I scrolled the screen down to be able to see the element.
4. On the appium inspector GUI, App screenshot was blank so I clicked on "Refresh Source & Screenhot" button
5. Clicked on "Search for element"
6. Selected "Id" as locator Strategy
7. Entered "remove-from-pab" to the selector field
8. Clicked on Search, one element found with number 1
9. Selected the element found
10. Clicked on "Tap Element" button

Observed Result : Nothing happened on the phone screen.
Expected Result : a pop-up window should have been displayed for delete confirmation.

## Link to Appium logs
https://gist.github.com/dokmetas/e591c2a8c1d097ba26a9404f90d8ff93

## Code To Reproduce Issue [ Good To Have ]
Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Is the element inside a web view?

**Comment by dokmetas** [comment]
I believe so as I am able to see the element via Chrome Developer Tools inspect.

Btw, is there a way to switch to webview context while using Appium Inspector?

I wonder whether adding Uiautomator2 capability would make a difference?

**Comment by mykola-mokhnach** [comment]
You must switch to webview context in order to properly handle elements inside it. Read http://appium.io/docs/en/writing-running-appium/web/hybrid/ for more details. Also check https://discuss.appium.io/t/android-hybrid-app-element-seems-to-be-clicked-but-in-fact-no-action-is-performed/23101
