### ISSUE TITLE
run testcase more and more slow

### ISSUE THREAD

**Issue by bournli** [appium/appium#11166]
## The problem

when i am running 300 testcases,the appium server run more and more slow.

e.g: 
the first case the total time is 20s
the  second case is 23 s
...
the 100th case is 68s

my case is the same ,
Circular execution is 300 times

 

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:1.6.2,the appium server version is 1.8.1
* Node.js version (unless using Appium.app|exe):10.7
* Mobile platform/version under test: iOS 11.4.1
* Real device :
* Appium CLI or Appium.app|exe  both is same

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by imurchie** [comment]
Without more information it is hard to know what to do with this.

What is the test case? What is it doing? Anything else that might help pinpoint things?

**Comment by mykola-mokhnach** [comment]
Check if it performs better in appiu@beta
