### ISSUE TITLE
grant permission activity does not allows App activity to be found by Appium driver

### ISSUE THREAD

**Issue by VenkateshPS** [appium/appium#11171]
## The problem

If i don't set autoGrantPermissions to true in capabilities, App activity  is not found by Android driver.
This clearly shows that app is running, just that the grant permissions activity is currently running on top of us. 

 Running activities (most recent first):
      TaskRecord{b94127c #429 A=com.xxxxxx.ux U=0 StackId=1 sz=2}
        Run #1: ActivityRecord{dcd3d7e u0 com.google.android.packageinstaller/com.android.packageinstaller.permission.ui.GrantPermissionsActivity t429}
        Run #0: ActivityRecord{efcffef u0 com.xxxx.ux/.authentication.AuthenticationActivity t429}

    mResumedActivity: ActivityRecord{dcd3d7e u0 com.google.android.packageinstaller/com.android.packageinstaller.permission.ui.GrantPermissionsActivity t429}
 

 

## Environment

* Appium version (or git revision) that exhibits the issue:1.81
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Android 7 , Real device
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
I cannot understand what Appium itself has to do with this problem. Can you please properly describe the actual and expected result and attach the logs?
