### ISSUE TITLE
Cannot set implicit wait on Android.

### ISSUE THREAD

**Issue by FilipWennerdahlSopraSteria** [appium/appium#11178]
## The problem

Still seeing issues when setting implicit wait while using W3C (forcing MSJONWP through MobileCapabilityType.FORCE_MJSONWP works fine). This issue is related to [this closed issue.](https://github.com/appium/appium/issues/11016) As stated in the original issue everything works fine with Appium 1.8.1.

## Environment
* Appium version (or git revision) that exhibits the issue: 1.8.2-beta
* Last Appium version that did not exhibit the issue (if applicable): 1.8.1
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): v8.0.0
* Mobile platform/version under test: Android 8.0
* Real device or emulator/simulator: real device, hybrid webview app
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Error response

```
[HTTP] --> POST /wd/hub/session/e66113e6-0bde-4a3c-8b53-066a15510bb8/timeouts
[HTTP] {"implicit":1000}
[W3C] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Matched '/wd/hub/session/e66113e6-0bde-4a3c-8b53-066a15510bb8/timeouts' to command name 'timeouts'
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/e66113e6-0bde-4a3c-8b53-066a15510bb8/timeouts] to [POST http://127.0.0.1:8000/wd/hub/session/8d237d70c8d8c81541220680d1aac4c4/timeouts] with body: {"implicit":1000}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"8d237d70c8d8c81541220680d1aac4c4","status":13,"value":{"message":"unknown error: 'ms' must be a double\n  (Session info: chrome=67.0.3396.87)\n  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 10.0.17134 x86_64)"}}
[W3C] Encountered internal error running command:  {"w3cStatus":400,"jsonwp":{"sessionId":"8d237d70c8d8c81541220680d1aac4c4","status":13,"value":{"message":"unknown error: 'ms' must be a double\n  (Session info: chrome=67.0.3396.87)\n  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 10.0.17134 x86_64)"}}} ProxyRequestError: Could not proxy command to remote server. Original error: The request to /wd/hub/session/e66113e6-0bde-4a3c-8b53-066a15510bb8/timeouts has failed
```

## Link to Appium logs

[Full log](https://gist.github.com/FilipWennerdahlSopraSteria/43d74deeec0e7c602ca814942487fac3)

**Comment by mykola-mokhnach** [comment]
@FilipWennerdahlSopraSteria Could you please put the updated file https://github.com/appium/appium-base-driver/pull/248/files#diff-7c7fef3719a4565efc2ac0d28ac10731 into your local source (/lib/jsonwp-proxy/proxy.js) and run `gulp transpile`? Then do not forged to restart appium. I'd like to make sure this change works properly for you before merging it.

**Comment by mykola-mokhnach** [comment]
It looks like the file has not been really updated. Try to update it inside `appium/node_modules/appium-xcuitest-driver/node_modules/appium-base-driver`

**Comment by FilipWennerdahlSopraSteria** [comment]
@mykola-mokhnach Since this is Android using a webview i updated the appium-base-driver inside appium-chromedriver. Now everything works correctly with W3C. Thank you for the fast response and help!

**Comment by mykola-mokhnach** [comment]
The change has been published to appium@beta
