### ISSUE TITLE
Unable to navigate to given URL after launching the safari on iPhone 6s

### ISSUE THREAD

**Issue by nageshc** [appium/appium#11177]
# org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: operation timed out (WARNING: The server did not provide any stacktrace information)

`Command duration or timeout: 18.61 seconds
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:25:02.294Z'
System info: host: 'Playbackweb-Automation.local', ip: '10.10.5.127', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.3', java.version: '1.8.0_20'
Driver info: driver.version: IOSDriver`

Unable to navigate to given URL after launching the safari on iPhone 6s.
But on Android test it execute fine.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 
* Node.js version (unless using Appium.app|exe): v8.9.1
* Mobile platform/version under test: iOS 10.1.1
* Real device or emulator/simulator: iPhone 6s
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/nageshc/d6a5bf4d7fdb4fd63ce1ce7dc191638b

Intelli J log

/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/bin/java -Dplatform=web -DplatformName=ios -Dudid=e7d3e1759e5cb6724a473320209139f217436d8c -DbrowserName=Safari -DautomationName=XCUITest -DdeviceName=iPhone6s -DplatformVersion=10.1.1 -DnewCommandTimeout=90000 -DshowIOSLog=true -DbundleId=com.apple.mobilesafari -javaagent:/Users/playbackautomation/.m2/repository/org/aspectj/aspectjweaver/1.8.10/aspectjweaver-1.8.10.jar -Didea.test.cyclic.buffer.size=1048576 "-javaagent:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar=50994:/Applications/IntelliJ IDEA CE.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/testng/lib/testng-plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/lib/tools.jar:/Users/playbackautomation/Desktop/ipsymobile/ipsy-android/target/test-classes:/Users/playbackautomation/Desktop/ipsymobile/ipsy-android/target/classes:/Users/playbackautomation/.m2/repository/org/testng/testng/6.8/testng-6.8.jar:/Users/playbackautomation/.m2/repository/junit/junit/4.10/junit-4.10.jar:/Users/playbackautomation/.m2/repository/org/hamcrest/hamcrest-core/1.1/hamcrest-core-1.1.jar:/Users/playbackautomation/.m2/repository/org/beanshell/bsh/2.0b4/bsh-2.0b4.jar:/Users/playbackautomation/.m2/repository/com/beust/jcommander/1.27/jcommander-1.27.jar:/Users/playbackautomation/.m2/repository/org/seleniumhq/selenium/selenium-java/3.9.1/selenium-java-3.9.1.jar:/Users/playbackautomation/.m2/repository/org/seleniumhq/selenium/selenium-chrome-driver/3.9.1/selenium-chrome-driver-3.9.1.jar:/Users/playbackautomation/.m2/repository/org/seleniumhq/selenium/selenium-edge-driver/3.9.1/selenium-edge-driver-3.9.1.jar:/Users/playbackautomation/.m2/repository/org/seleniumhq/selenium/selenium-firefox-driver/3.9.1/selenium-firefox-driver-3.9.1.jar:/Users/playbackautomation/.m2/repository/org/seleniumhq/selenium/selenium-ie-driver/3.9.1/selenium-ie-driver-3.9.1.jar:/Users/playbackautomation/.m2/repository/org/seleniumhq/selenium/selenium-opera-driver/3.9.1/selenium-opera-driver-3.9.1.jar:/Users/playbackautomation/.m2/repository/org/seleniumhq/selenium/selenium-safari-driver/3.9.1/selenium-safari-driver-3.9.1.jar:/Users/playbackautomation/.m2/repository/org/seleniumhq/selenium/selenium-support/3.9.1/selenium-support-3.9.1.jar:/Users/playbackautomation/.m2/repository/net/bytebuddy/byte-buddy/1.7.9/byte-buddy-1.7.9.jar:/Users/playbackautomation/.m2/repository/org/apache/commons/commons-exec/1.3/commons-exec-1.3.jar:/Users/playbackautomation/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:/Users/playbackautomation/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/Users/playbackautomation/.m2/repository/com/google/code/gson/gson/2.8.2/gson-2.8.2.jar:/Users/playbackautomation/.m2/repository/com/google/guava/guava/23.6-jre/guava-23.6-jre.jar:/Users/playbackautomation/.m2/repository/org/checkerframework/checker-compat-qual/2.0.0/checker-compat-qual-2.0.0.jar:/Users/playbackautomation/.m2/repository/com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3.jar:/Users/playbackautomation/.m2/repository/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar:/Users/playbackautomation/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.jar:/Users/playbackautomation/.m2/repository/org/apache/httpcomponents/httpclient/4.5.3/httpclient-4.5.3.jar:/Users/playbackautomation/.m2/repository/org/apache/httpcomponents/httpcore/4.4.6/httpcore-4.4.6.jar:/Users/playbackautomation/.m2/repository/com/squareup/okhttp3/okhttp/3.9.1/okhttp-3.9.1.jar:/Users/playbackautomation/.m2/repository/com/squareup/okio/okio/1.13.0/okio-1.13.0.jar:/Users/playbackautomation/.m2/repository/org/seleniumhq/selenium/selenium-server/3.9.1/selenium-server-3.9.1.jar:/Users/playbackautomation/.m2/repository/org/apache/commons/commons-lang3/3.7/commons-lang3-3.7.jar:/Users/playbackautomation/.m2/repository/org/apache/commons/commons-text/1.1/commons-text-1.1.jar:/Users/playbackautomation/.m2/repository/commons-io/commons-io/2.6/commons-io-2.6.jar:/Users/playbackautomation/.m2/repository/commons-net/commons-net/3.6/commons-net-3.6.jar:/Users/playbackautomation/.m2/repository/org/w3c/css/sac/1.3/sac-1.3.jar:/Users/playbackautomation/.m2/repository/net/sourceforge/cssparser/cssparser/0.9.24/cssparser-0.9.24.jar:/Users/playbackautomation/.m2/repository/net/sourceforge/htmlunit/htmlunit-core-js/2.28/htmlunit-core-js-2.28.jar:/Users/playbackautomation/.m2/repository/net/sourceforge/htmlunit/neko-htmlunit/2.28/neko-htmlunit-2.28.jar:/Users/playbackautomation/.m2/repository/org/apache/httpcomponents/httpmime/4.5.3/httpmime-4.5.3.jar:/Users/playbackautomation/.m2/repository/net/jcip/jcip-annotations/1.0/jcip-annotations-1.0.jar:/Users/playbackautomation/.m2/repository/org/seleniumhq/selenium/jetty-repacked/9.4.7.v20171121/jetty-repacked-9.4.7.v20171121.jar:/Users/playbackautomation/.m2/repository/org/eclipse/jetty/jetty-client/9.4.7.v20170914/jetty-client-9.4.7.v20170914.jar:/Users/playbackautomation/.m2/repository/org/eclipse/jetty/jetty-http/9.4.8.v20171121/jetty-http-9.4.8.v20171121.jar:/Users/playbackautomation/.m2/repository/org/eclipse/jetty/jetty-io/9.4.8.v20171121/jetty-io-9.4.8.v20171121.jar:/Users/playbackautomation/.m2/repository/org/eclipse/jetty/jetty-util/9.4.8.v20171121/jetty-util-9.4.8.v20171121.jar:/Users/playbackautomation/.m2/repository/org/eclipse/jetty/jetty-xml/9.4.7.v20170914/jetty-xml-9.4.7.v20170914.jar:/Users/playbackautomation/.m2/repository/org/seleniumhq/selenium/htmlunit-driver/2.29.0/htmlunit-driver-2.29.0.jar:/Users/playbackautomation/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar:/Users/playbackautomation/.m2/repository/org/eclipse/jetty/websocket/websocket-api/9.4.7.v20170914/websocket-api-9.4.7.v20170914.jar:/Users/playbackautomation/.m2/repository/org/eclipse/jetty/websocket/websocket-client/9.4.7.v20170914/websocket-client-9.4.7.v20170914.jar:/Users/playbackautomation/.m2/repository/org/eclipse/jetty/websocket/websocket-common/9.4.7.v20170914/websocket-common-9.4.7.v20170914.jar:/Users/playbackautomation/.m2/repository/xalan/serializer/2.7.2/serializer-2.7.2.jar:/Users/playbackautomation/.m2/repository/xalan/xalan/2.7.2/xalan-2.7.2.jar:/Users/playbackautomation/.m2/repository/xerces/xercesImpl/2.11.0/xercesImpl-2.11.0.jar:/Users/playbackautomation/.m2/repository/xml-apis/xml-apis/1.4.01/xml-apis-1.4.01.jar:/Users/playbackautomation/.m2/repository/org/seleniumhq/selenium/selenium-api/3.9.1/selenium-api-3.9.1.jar:/Users/playbackautomation/.m2/repository/org/seleniumhq/selenium/selenium-remote-driver/3.9.1/selenium-remote-driver-3.9.1.jar:/Users/playbackautomation/.m2/repository/io/appium/java-client/6.0.0-BETA5/java-client-6.0.0-BETA5.jar:/Users/playbackautomation/.m2/repository/cglib/cglib/3.2.6/cglib-3.2.6.jar:/Users/playbackautomation/.m2/repository/org/ow2/asm/asm/6.0/asm-6.0.jar:/Users/playbackautomation/.m2/repository/org/apache/ant/ant/1.9.6/ant-1.9.6.jar:/Users/playbackautomation/.m2/repository/org/apache/ant/ant-launcher/1.9.6/ant-launcher-1.9.6.jar:/Users/playbackautomation/.m2/repository/commons-validator/commons-validator/1.6/commons-validator-1.6.jar:/Users/playbackautomation/.m2/repository/commons-beanutils/commons-beanutils/1.9.2/commons-beanutils-1.9.2.jar:/Users/playbackautomation/.m2/repository/commons-digester/commons-digester/1.8.1/commons-digester-1.8.1.jar:/Users/playbackautomation/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar:/Users/playbackautomation/.m2/repository/org/springframework/spring-context/5.0.3.RELEASE/spring-context-5.0.3.RELEASE.jar:/Users/playbackautomation/.m2/repository/org/springframework/spring-aop/5.0.3.RELEASE/spring-aop-5.0.3.RELEASE.jar:/Users/playbackautomation/.m2/repository/org/springframework/spring-beans/5.0.3.RELEASE/spring-beans-5.0.3.RELEASE.jar:/Users/playbackautomation/.m2/repository/org/springframework/spring-core/5.0.3.RELEASE/spring-core-5.0.3.RELEASE.jar:/Users/playbackautomation/.m2/repository/org/springframework/spring-jcl/5.0.3.RELEASE/spring-jcl-5.0.3.RELEASE.jar:/Users/playbackautomation/.m2/repository/org/springframework/spring-expression/5.0.3.RELEASE/spring-expression-5.0.3.RELEASE.jar:/Users/playbackautomation/.m2/repository/org/aspectj/aspectjweaver/1.8.13/aspectjweaver-1.8.13.jar:/Users/playbackautomation/.m2/repository/org/openpnp/opencv/3.2.0-1/opencv-3.2.0-1.jar:/Users/playbackautomation/.m2/repository/javax/websocket/javax.websocket-api/1.1/javax.websocket-api-1.1.jar:/Users/playbackautomation/.m2/repository/org/glassfish/tyrus/tyrus-client/1.1/tyrus-client-1.1.jar:/Users/playbackautomation/.m2/repository/org/glassfish/tyrus/tyrus-core/1.1/tyrus-core-1.1.jar:/Users/playbackautomation/.m2/repository/org/glassfish/tyrus/tyrus-spi/1.1/tyrus-spi-1.1.jar:/Users/playbackautomation/.m2/repository/org/glassfish/tyrus/tyrus-websocket-core/1.1/tyrus-websocket-core-1.1.jar:/Users/playbackautomation/.m2/repository/org/glassfish/tyrus/tyrus-container-grizzly/1.1/tyrus-container-grizzly-1.1.jar:/Users/playbackautomation/.m2/repository/org/glassfish/grizzly/grizzly-framework/2.3.3/grizzly-framework-2.3.3.jar:/Users/playbackautomation/.m2/repository/org/glassfish/grizzly/grizzly-http-server/2.3.3/grizzly-http-server-2.3.3.jar:/Users/playbackautomation/.m2/repository/org/glassfish/grizzly/grizzly-http/2.3.3/grizzly-http-2.3.3.jar:/Users/playbackautomation/.m2/repository/org/glassfish/grizzly/grizzly-rcm/2.3.3/grizzly-rcm-2.3.3.jar:/Users/playbackautomation/.m2/repository/net/sourceforge/htmlunit/htmlunit/2.21/htmlunit-2.21.jar:/Users/playbackautomation/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar:/Users/playbackautomation/.m2/repository/ru/yandex/qatools/allure/allure-model/1.5.0.RC2/allure-model-1.5.0.RC2.jar:/Users/playbackautomation/.m2/repository/org/jvnet/jaxb2_commons/jaxb2-basics-runtime/0.9.3/jaxb2-basics-runtime-0.9.3.jar:/Users/playbackautomation/.m2/repository/ru/qatools/commons/properties/2.0.RC3/properties-2.0.RC3.jar:/Users/playbackautomation/.m2/repository/org/slf4j/slf4j-api/1.7.12/slf4j-api-1.7.12.jar:/Users/playbackautomation/.m2/repository/com/google/gdata/core/1.47.1/core-1.47.1.jar:/Users/playbackautomation/.m2/repository/com/google/oauth-client/google-oauth-client-jetty/1.11.0-beta/google-oauth-client-jetty-1.11.0-beta.jar:/Users/playbackautomation/.m2/repository/com/google/oauth-client/google-oauth-client-java6/1.11.0-beta/google-oauth-client-java6-1.11.0-beta.jar:/Users/playbackautomation/.m2/repository/com/google/oauth-client/google-oauth-client/1.11.0-beta/google-oauth-client-1.11.0-beta.jar:/Users/playbackautomation/.m2/repository/com/google/http-client/google-http-client/1.11.0-beta/google-http-client-1.11.0-beta.jar:/Users/playbackautomation/.m2/repository/xpp3/xpp3/1.1.4c/xpp3-1.1.4c.jar:/Users/playbackautomation/.m2/repository/org/mortbay/jetty/jetty/6.1.26/jetty-6.1.26.jar:/Users/playbackautomation/.m2/repository/org/mortbay/jetty/jetty-util/6.1.26/jetty-util-6.1.26.jar:/Users/playbackautomation/.m2/repository/org/mortbay/jetty/servlet-api/2.5-20081211/servlet-api-2.5-20081211.jar:/Users/playbackautomation/.m2/repository/com/google/code/findbugs/jsr305/1.3.7/jsr305-1.3.7.jar:/Users/playbackautomation/.m2/repository/javax/mail/mail/1.4/mail-1.4.jar:/Users/playbackautomation/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar:/Users/playbackautomation/.m2/repository/ru/yandex/qatools/allure/allure-testng-adaptor/1.5.0.RC2/allure-testng-adaptor-1.5.0.RC2.jar:/Users/playbackautomation/.m2/repository/ru/yandex/qatools/allure/allure-java-aspects/1.5.0.RC2/allure-java-aspects-1.5.0.RC2.jar:/Users/playbackautomation/.m2/repository/ru/yandex/qatools/allure/allure-java-adaptor-api/1.5.0.RC2/allure-java-adaptor-api-1.5.0.RC2.jar:/Users/playbackautomation/.m2/repository/org/apache/tika/tika-core/1.7/tika-core-1.7.jar:/Users/playbackautomation/.m2/repository/org/aspectj/aspectjrt/1.8.3/aspectjrt-1.8.3.jar:/Users/playbackautomation/.m2/repository/ru/yandex/qatools/allure/allure-java-annotations/1.5.0.RC2/allure-java-annotations-1.5.0.RC2.jar:/Users/playbackautomation/.m2/repository/io/qameta/allure/allure-testng/2.7.0/allure-testng-2.7.0.jar:/Users/playbackautomation/.m2/repository/io/qameta/allure/allure-descriptions-javadoc/2.7.0/allure-descriptions-javadoc-2.7.0.jar:/Users/playbackautomation/.m2/repository/io/qameta/allure/allure-java-commons/2.7.0/allure-java-commons-2.7.0.jar:/Users/playbackautomation/.m2/repository/io/qameta/allure/allure2-model-api/1.0.0/allure2-model-api-1.0.0.jar:/Users/playbackautomation/.m2/repository/io/qameta/allure/allure2-model-pojo/1.0.0/allure2-model-pojo-1.0.0.jar:/Users/playbackautomation/.m2/repository/io/qameta/allure/allure2-model-jackson/1.0.0/allure2-model-jackson-1.0.0.jar:/Users/playbackautomation/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.7.0/jackson-databind-2.7.0.jar:/Users/playbackautomation/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.7.0/jackson-annotations-2.7.0.jar:/Users/playbackautomation/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.7.0/jackson-core-2.7.0.jar:/Users/playbackautomation/.m2/repository/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.7.0/jackson-module-jaxb-annotations-2.7.0.jar:/Users/playbackautomation/.m2/repository/org/jooq/joor-java-8/0.9.9/joor-java-8-0.9.9.jar:/Users/playbackautomation/.m2/repository/org/apache/xmlbeans/xmlbeans/2.6.0/xmlbeans-2.6.0.jar:/Users/playbackautomation/.m2/repository/stax/stax-api/1.0.1/stax-api-1.0.1.jar:/Users/playbackautomation/.m2/repository/org/assertj/assertj-core/3.6.2/assertj-core-3.6.2.jar:/Users/playbackautomation/.m2/repository/org/yaml/snakeyaml/1.19/snakeyaml-1.19.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/testng/lib/jcommander.jar" org.testng.RemoteTestNGStarter -usedefaultlisteners false -socket50993 @w@/private/var/folders/21/8t2w6_s9307_08d6nz_f92500000gq/T/idea_working_dirs_testng.tmp -temp /private/var/folders/21/8t2w6_s9307_08d6nz_f92500000gq/T/idea_testng.tmp
objc[13658]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/bin/java (0x10ced54c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x10cf584e0). One of the two will be used. Which one is undefined.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[TestNG] Running:
  /Users/playbackautomation/Library/Caches/IdeaIC2017.3/temp-testng-customsuite.xml
18/08/13 15:16:35 INFO utils.ReadPropertyFile: appName : app-staging-release.apk/n
18/08/13 15:16:35 INFO utils.ReadPropertyFile: appDir : ../../../Downloads//n

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: operation timed out (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 18.61 seconds
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:25:02.294Z'
System info: host: 'Playbackweb-Automation.local', ip: '10.10.5.127', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.3', java.version: '1.8.0_20'
Driver info: driver.version: IOSDriver

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
	at org.openqa.selenium.remote.JsonWireProtocolResponse$$Lambda$130/1737077873.apply(Unknown Source)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
	at org.openqa.selenium.remote.JsonWireProtocolResponse$$Lambda$132/51317621.apply(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
	at org.openqa.selenium.remote.ProtocolHandshake$$Lambda$139/376769118.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:138)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:129)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:84)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:94)
	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:82)
	at com.ipsy.utils.WebDriverFactory.initializeDriver(WebDriverFactory.java:95)
	at com.ipsy.E2E.Chrome.LoginTest.BeforeClass(LoginTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)

Test ignored.
18/08/13 15:16:58 INFO ipsy.BaseTest:  >>>>>>>>> Execution completed for Test case : loginand Result is 3>>>>>>>>>>

Test ignored.
18/08/13 15:16:58 INFO ipsy.BaseTest:  >>>>>>>>> Execution completed for Test case : verifyLoginPageTestand Result is 3>>>>>>>>>>

Test ignored.
18/08/13 15:16:58 INFO ipsy.BaseTest:  >>>>>>>>> Execution completed for Test case : validLoginand Result is 3>>>>>>>>>>

===============================================
Default Suite
Total tests run: 3, Failures: 0, Skips: 3
Configuration Failures: 1, Skips: 5
===============================================

Process finished with exit code 0

Could you please help me with this issue.
Thank you.

**Comment by mykola-mokhnach** [comment]
you must not set `bundleId` if `browserName` is set.

**Comment by nageshc** [comment]
@mykola-mokhnach, Thank you for quick response.

I have tried it by removing the -DbundleId

`-Dplatform="web"
-DplatformName="ios"
-Dudid="e7d3e1759e5cb6724a473320209139f217436d8c"
-DbrowserName="Safari"
-DautomationName="XCUITest"
-DdeviceName="iPhone6s"
-DplatformVersion="10.1.1"
-DnewCommandTimeout=90000
-DshowIOSLog="true"`

But Still getting the same error.

It is launching the safari browser but not navigating to URL.
Is there still any issue with my setup?

Thank you.

**Comment by mykola-mokhnach** [comment]
Try to upgrade to appium@beta

**Comment by nageshc** [comment]
Hi @mykola-mokhnach ,

I have Downgraded Appium Version to 1.8.0. and it is working fine.

I think may be this issue with Appium version 1.8.1

Thank you
