### ISSUE TITLE
can't test react native app

### ISSUE THREAD

**Issue by daisyzou** [appium/appium#11179]
When I try to create driver using Script or try to launch the application to locate element using Appium GUI, driver creation is taking around 5 mins.

Then I checked the FacebookWebDriver log:

    t =   728.90s             App event loop idle notification not received, will attempt to continue.
    t =   728.90s             App animations complete notification not received, will attempt to continue.

**Comment by mykola-mokhnach** [comment]
Try to set `waitForQuiescence` to true. Otherwise there is nothing that can be done on Appium side.

Closed as third party issue.

**Comment by daisyzou** [comment]
I solve the problem by set waitForQuiescence to false
