### ISSUE TITLE
Braintree drop-in-ui appium automation issue in appium

### ISSUE THREAD

**Issue by kadir-calvid** [appium/appium#11176]
## The problem

I want to do appium automation for Braintree drop-in-ui  but unable to inspect the elements to automate
is there any way to inspect elements for find there ids or class name
## Environment

* Appium version (or git revision) that exhibits the issue: 18.2
* Desktop OS/version used to run Appium: Ubuntu
* Node.js version (unless using Appium.app|exe): 9.5
* Mobile platform/version under test: Android
* Real device or emulator/simulator:Real device

## Details

Hello,
I want to do appium automation for Braintree drop-in-ui  but unable to inspect the elements to automate
is there any way to inspect elements for find there ids or class name
Any suggestion and solution would be appreciated

## Link to Appium logs

[elementByAndroidUIAutomator("new UiSelector().textContains(\"Expiration Date\")")] Error response status: 7, , NoSuchElement - An element could not be located on the page using the given search parameters. Selenium error: An element could not be located on the page using the given search parameters.

Thanks
kadir khan

**Comment by mykola-mokhnach** [comment]
Appium just reflects what the application itself provides to accessibility framework. This means that there is nothing to be done on our side if some element is not present in the tree. 

However, it is possible that the element itself is a part of web context and you're trying to interact with it being in native context. then switching the context would help to resolve the issue.
