### ISSUE TITLE
ANDROID_HOME Environment Not Set Even Though Appium-Doctor Says It Is

### ISSUE THREAD

**Issue by mojojojo94** [appium/appium#11172]
## The problem

Error: Could not find adb Please set the ANDROID_HOME environment variable with the Android SDK root directory path.

Appium-Doctor keeps flip flopping on this:
![screen shot 2018-08-10 at 2 48 17 pm](https://user-images.githubusercontent.com/15100526/43978476-f9b7c6f4-9cac-11e8-860f-2e0a4c2a609e.png)

if I close the terminal window and reopen it again to check if change was valid
it becomes:
![screen shot 2018-08-10 at 2 46 23 pm](https://user-images.githubusercontent.com/15100526/43978735-ea5942a4-9cad-11e8-8d1c-9f8ae3dcb63a.png)

This is my .bash_profile:
export JAVA_HOME=$(/usr/libexec/java_home)
export ANDROID_HOME=/Users/<my_username>/Library/Android/sdk
export PATH=$ANDROID_HOME/platform-tools:$PATH
export PATH=$ANDROID_HOME/tools:$PATH
export PATH=${JAVA_HOME}/bin:$PATH

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable): 1.8.0
* Desktop OS/version used to run Appium: macOS 10.13.4
* Node.js version (unless using Appium.app|exe): 8.0.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: emulator/simulator
* Appium CLI or Appium.app|exe: Appium.app

## Details
This is the error I get in appium desktop server console window:
[MJSONWP] Encountered internal error running command: Error: Could not find adb Please set the ANDROID_HOME environment variable with the Android SDK root directory path.

**Comment by mykola-mokhnach** [comment]
It is an issue with Appium Desktop. Please report to https://github.com/appium/appium-desktop
