### ISSUE TITLE
Java Null pointer Exception while starting Appium 

### ISSUE THREAD

**Issue by VasanthamS** [appium/appium#11180]
## The problem
Trying to perform login activity in my test app.Able to Launch App only in emulator with Android Version 6.0 , And further action not taking place. like locating element and providing input kind of things.

## Environment

* Appium version : 8.1
* Desktop OS/version used to run Appium: Windows 10
* Mobile platform/version under test: Android /6.0
* Real device or emulator/simulator: Emulator

## Link to Appium logs

https://gist.github.com/VasanthamS/058edc1299682490f9bb158d7c2ede89

## Code To Reproduce Issue [ Good To Have ]

package KLite;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import io.appium.java_client.AppiumDriver;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.remote.MobileCapabilityType;

public class Sample {

	
	public static AndroidDriver driver;

	
	  
	@BeforeClass
	public void set() throws MalformedURLException
	{
		DesiredCapabilities cap=new DesiredCapabilities();
		
		//cap.setCapability(MobileCapabilityType.DEVICE_NAME,"emulator-5554");
		cap.setCapability("autoGrantPermissions", true);
		cap.setCapability("automationName", "uiautomator2");
		cap.setCapability("deviceName", "Emulator device");
		cap.setCapability("udid", "emulator-5554"); 
		cap.setCapability("platformName", "Android");
		cap.setCapability("platformVersion", "6.0");
		cap.setCapability("noReset","true");
		cap.setCapability("appPackage","com.amazon.klite");
		cap.setCapability("appActivity","com.amazon.klite.LoginActivity");
		
	//	driver =new AndroidDriver<WebElement>(new URL("http://10.45.164.176:4723/wd/hub"),cap);
	//	driver = new AndroidDriver(new URL("http://0.0.0.0:4723/wd/hub"),cap);
		
		WebDriver driver = new AndroidDriver<WebElement>(new URL("http://0.0.0.0:4723/wd/hub"),cap);

	}

	//@Test(invocationCount = 10)
	@Test

	  public void Login()
	  
	  {
	//	driver.findElement(By.xpath("//android.widget.Button[@text='GET STARTED']")).click();
	    driver.findElement(By.id("com.amazon.klite:id/activity_login_login_button")).click();
		driver.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
		driver.findElement(By.xpath("//android.widget.EditText[@content-desc=\"Email (phone for mobile accounts)\"]")).sendKeys("lite+2@amazon.com");
		driver.findElement(By.xpath("//android.webkit.WebView[@content-desc=\"Amazon Sign In\"]/android.view.View[2]/android.view.View[6]/android.widget.EditText")).sendKeys("rainyday");
		driver.findElement(By.xpath("//android.widget.Button[@content-desc=\" Sign in \"]")).click();
		driver.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
		driver.findElement(By.id("com.amazon.klite:id/text_size_settings_full_width_save_button")).click();
		driver.findElement(By.xpath("//android.widget.TextView[@text='More']")).click();
		driver.findElement(By.xpath("//android.widget.TextView[@text='Settings']")).click();
		driver.findElement(By.xpath("//android.widget.TextView[@text='Deregister this device']")).click();
		driver.findElement(By.id("com.amazon.klite:id/dialog_positive_button")).click();
	  }

}

Eclipse console logs:

[RemoteTestNG] detected TestNG version 6.7.0
[TestNG] Running:
  C:\Users\vaselvar\AppData\Local\Temp\testng-eclipse--42737290\testng-customsuite.xml

Aug 14, 2018 4:14:14 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
FAILED: Login
java.lang.NullPointerException
	at KLite.Sample.Login(Sample.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

===============================================
    Default test
    Tests run: 1, Failures: 1, Skips: 0
===============================================

===============================================
Default suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================

[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@2ed94a8b: 21 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter@79b4d0f: 7 ms
[TestNG] Time taken by [TestListenerAdapter] Passed:0 Failed:0 Skipped:0]: 18 ms
[TestNG] Time taken by org.testng.reporters.jq.Main@566776ad: 69 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@668bc3d5: 19 ms
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@35f983a6: 163 ms

**Comment by mykola-mokhnach** [comment]
I don't observe any issues in the server log. The session has been terminated because of missing client input:

> [BaseDriver] Shutting down because we waited 60 seconds for a command

The problem most likely lies in the client code

**Comment by VasanthamS** [comment]
Can you please address the solution for this.
[BaseDriver] Shutting down because we waited 60 seconds for a command
By the way what could the command was?

**Comment by mykola-mokhnach** [comment]
> Can you please address the solution for this.

No, since it is not an Appium problem.

> By the way what could the command was?

Sorry, didn't get your question.
