### ISSUE TITLE
fb_snapshotWithAttributes is broken in Xcode 10 Beta 4+

### ISSUE THREAD

**Issue by Dan-Maor** [appium/appium#11182]
The snapshot retrieval function (`fb_snapshotWithAttributes`) relies on the private `[XCElementSnapshot snapshotAttributesForElementSnapshotKeyPaths]` which has been removed in Xcode 10 beta 4 and replaced by `[XCElementSnapshot axAttributesForElementSnapshotKeyPaths]`.

Their internal implementation appears to be the same when checked with Hopper (both call `XCAXSnappshotAttributesForElementSnapshotKeys` internally).

I won't be able to make a PR for fixing it since I'm currently overloaded by other projects, I've noticed it because I keep track of XCTest header changes for my own XCTest uses.

**Comment by dpgraham** [comment]
Thanks for notifying us. @mykola-mokhnach are you aware of this issue?

**Comment by mykola-mokhnach** [comment]
yep. I'll check it when I have time

**Comment by chinnarii** [comment]
When I'm trying to run the WebDriverAgent getting below error:

" Implicit conversion from nullable pointer 'XCElementSnapshot * _Nullable' to non-nullable pointer type 'XCElementSnapshot * _Nonnull' "

please help me

**Comment by KazuCocoa** [comment]
It was because of Xcode version, I assume.
Can you try out with newer one?

**Comment by chinnarii** [comment]
> It was because of Xcode version, I assume.
> Can you try out with newer one?

I tried with Xcode version 8.2 also but same issue with it... 
Mac OS X 11.4
Appium 1.6.1
Xcode 8.2

please help me

**Comment by KazuCocoa** [comment]
ah, you tried to use Appium 1.6.1, which was almost 2 years ago.

Did you build from a clean environment?
While Xcode 8 support is going to drop from our support in next release, Appium had been able to build with Xcode 8. So, you probably build with Xcode 8.x up to 1.9.1, I think.
https://github.com/appium/appium/blob/master/CHANGELOG.md#changes-in-version-191-from-190

You can build `node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj` with your Xcode in order to make sure the WDA in your env can build with Xcode 8.

(We'd recommend you to use newer Appium)

**Comment by chinnarii** [comment]
Installed 
VM ware
Mac OS X 10.11.4
Xcode 8.2 with commandline tools
Simulator 9.3
please suggest me the Appium version, which is working well with my above installed setup

**Comment by chinnarii** [comment]
Hi,
Now installed Appium 1.7.0 and now able get build success but when when i'm trying to run a script getting error " A new session could not be created.Details: Appium's iOSDriver doest not support  Xcode version 8.2 . Apple has deprecated UIAutomation. Use XCUITest automationName capability Instead"

please help

**Comment by KazuCocoa** [comment]
Did you read http://appium.io/docs/en/about-appium/getting-started/ , http://appium.io/docs/en/drivers/ios-xcuitest/index.html and _Use XCUITest automationName capability Instead_ described in the error log?

**Comment by chinnarii** [comment]
Under my capabilities I havn't mentioned automationName, still it is showing use instead?

**Comment by KazuCocoa** [comment]
Yes, according to http://appium.io/docs/en/writing-running-appium/caps/ , the default value is `Appium`. It is not `XCUITest`.
http://appium.io/docs/en/about-appium/platform-support/

**Comment by chinnarii** [comment]
Thanks a looooooot...... Its working as expected...........
