### ISSUE TITLE
Test and Release Appium 1.9.0

### ISSUE THREAD

**Issue by imurchie** [appium/appium#11183]
It is time to get a new release out. given the number of features that have been added, make it a feature release (not 1.8.2).

**Comment by rsdeepu** [comment]
Hi Imurchie,

Can we expect 1.8.2 full release soon?
Or do we need to wait another three ,four month to get the full release 1.9.0

Regards
Deepu

**Comment by SrinivasanTarget** [comment]
@rsdeepu All the features which 1.9.0 going to contain is already available in 1.8.2-beta so Appium never makes you to wait. Feel free to uninstall existing Appium and install Appium beta using 'npm install -g appium@beta'.

**Comment by rsdeepu** [comment]
Hi Imurchie,

Could you please help with 1.8.2 full release date . Because for appium , no where we can find the release forecast news.
So facing some difficulty to planning some development activity.

**Comment by dpgraham** [comment]
@SrinivasanTarget You can install from the command line and run it there. Then on Appium Desktop you start a new session, select `Custom Server` and then point the host/port to the server running from the command line.

**Comment by imurchie** [comment]
Appium 1.8.2 will not be released. It was decided that there were too many features involved, so a minor release (1.9.0) rather than a patch release (1.8.2) was warranted.

We are getting things together and hope to have the release done by the end of the week or early next week.

**Comment by rsdeepu** [comment]
thanks @dpgraham  and @SrinivasanTarget , We will try this and let you know

**Comment by eMTe123** [comment]
Hello :)

I am trying to use appium 1.9.0 with the new espresso driver to be able to use view-tags in my tests. When running the inspector from appium desktop or running the test with capability automationName: 'Espresso' set, I get the error below.

I've tried to delete the temp logs and re-run several times. I've also tried to edit file permissions without any luck. Any suggestions?

Thanks in advance!

`[Espresso] Repackaging espresso server for: '_"appname"_'
[Espresso] Creating new manifest: 'C:\Users\username\AppData\Local\Temp\AndroidManifest.xml'
[ADB] Compiling manifest C:\Users\username\AppData\Local\Temp\AndroidManifest.xml
[ADB] Found the most recent Android platform: {"platform":"android-28","platformPath":"C:/Users/username/AppData/Local/Android/Sdk/platforms/android-28"}
[ADB] Compiling manifest.
[ADB] Compiled manifest
[ADB] Inserting manifest, src: C:\Users\username\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-espresso-driver\espresso-server\app\build\outputs\apk\androidTest\debug\app-debug-androidTest.apk dst: C:\Users\username\AppData\Local\Temp\io.appium.espressoserver.test_1.0.0-beta.9__"appname"_.apk
[ADB] Unzipping C:\Users\username\AppData\Local\Temp\AndroidManifest.xml.apk
[ADB] Testing zip archive: 'C:\Users\username\AppData\Local\Temp\AndroidManifest.xml.apk'
[ADB] Unzip successful
[ADB] Testing new tmp apk
[ADB] Testing zip archive: 'C:\Users\username\AppData\Local\Temp\io.appium.espressoserver.test_1.0.0-beta.9__"appname"_.apk'
[ADB] Moving manifest
[ADB] Inserted manifest.
[Espresso] Repackaged espresso server ready: 'C:\Users\username\AppData\Local\Temp\io.appium.espressoserver.test_1.0.0-beta.9__"appname"_.apk'
[ADB] Checking app cert for C:\Users\username\AppData\Local\Temp\io.appium.espressoserver.test_1.0.0-beta.9__"appname"_.apk
[ADB] Starting 'C:\Users\username\AppData\Local\Android\Sdk\build-tools\28.0.1\apksigner.bat' with args 'verify,--print-certs,C:\Users\username\AppData\Local\Temp\io.appium.espressoserver.test_1.0.0-beta.9__"appname"_.apk'
[ADB] 'C:\Users\username\AppData\Local\Temp\io.appium.espressoserver.test_1.0.0-beta.9__"appname"_.apk' is not signed with debug cert.
[ADB] Zip-aligning 'C:\Users\username\AppData\Local\Temp\io.appium.espressoserver.test_1.0.0-beta.9__"appname"_.apk'
[ADB] Checking whether zipalign is present
[ADB] Using zipalign.exe from C:\Users\username\AppData\Local\Android\Sdk\build-tools\28.0.1\zipalign.exe
[ADB] Signing 'C:\Users\username\AppData\Local\Temp\io.appium.espressoserver.test_1.0.0-beta.9__"appname"_.apk' with default cert
[ADB] Starting 'C:\Users\username\AppData\Local\Android\Sdk\build-tools\28.0.1\apksigner.bat' with args 'sign,--key,C:\Users\username\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-adb\keys\testkey.pk8,--cert,C:\Users\username\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-adb\keys\testkey.x509.pem,C:\Users\username\AppData\Local\Temp\io.appium.espressoserver.test_1.0.0-beta.9__"appname"_.apk'
[ADB] Cannot use apksigner tool for signing. Defaulting to sign.jar. Original error: Command 'C\:\\Users\\username\\AppData\\Local\\Android\\Sdk\\build-tools\\28.0.1\\apksigner.bat sign --key C\:\\Users\\username\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-adb\\keys\\testkey.pk8 --cert C\:\\Users\\username\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-adb\\keys\\testkey.x509.pem C\:\\Users\\username\\AppData\\Local\\Temp\\io.appium.espressoserver.test_1.0.0-beta.9__"appname"_.apk' exited with code 1; StdErr: Exception in thread "main" java.nio.file.FileAlreadyExistsException: C:\Users\username\AppData\Local\Temp\apksigner5087486382376924560.apk -> C:\Users\username\AppData\Local\Temp\io.appium.espressoserver.test_1.0.0-beta.9__"appname"_.apk
[ADB] 	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
[ADB] 	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
[ADB] 	at sun.nio.fs.WindowsFileCopy.move(Unknown Source)
[ADB] 	at sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source)
[ADB] 	at java.nio.file.Files.move(Unknown Source)
[ADB] 	at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:342)
[ADB] 	at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:89)
[ADB] 
[ADB] Resigning apk.
[Espresso] Deleting espresso session
[ADB] Running 'C:\Users\username\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell am broadcast -a io.appium.settings.animation -n io.appium.settings/.receivers.AnimationSettingReceiver --es setstatus enable'
[ADB] Running 'C:\Users\username\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell am force-stop _"appname"_'
[Logcat] Stopping logcat capture
[ADB] Removing forwarded port socket connection: 8080 
[ADB] Running 'C:\Users\username\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 forward --remove tcp\:8080'
[BaseDriver] Event 'newSessionStarted' logged at 1535456803700 (13:46:43 GMT+0200 (Vest-Europa (sommertid)))
[MJSONWP] Encountered internal error running command: Error: Could not sign with default certificate. Original error Command ''C:\\Program Files\\Java\\jdk-10.0.1\\bin\\java.exe' -jar C\:\\Users\\username\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-adb\\jars\\sign.jar C\:\\Users\\username\\AppData\\Local\\Temp\\io.appium.espressoserver.test_1.0.0-beta.9__"appname"_.apk --override' exited with code 1
[MJSONWP]     at ADB.callee$0$0$ (C:\Users\username\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\apk-signing.js:79:13)
[MJSONWP]     at tryCatch (C:\Users\username\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\username\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\username\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (C:\Users\username\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[MJSONWP]     at 
[HTTP] <-- POST /wd/hub/session 500 26505 ms - 593
[HTTP] `

**Comment by imurchie** [comment]
Please make an issue with all the relevant details. This is for tracking the release, and will be closed without comment.
