### ISSUE TITLE
[Chromedriver] Error: Failed to start Chromedriver session: An unknown server-side error occurred while processing the command. (Original error: unknown error: Failed to get sockets matching: @webview_devtools_remote_.*24811

### ISSUE THREAD

**Issue by dokmetas** [appium/appium#11189]
## The problem

Chromedriver error when trying to switch to webview.

## Environment

Appium version (or git revision) that exhibits the issue: 1.6.3
Last Appium version that did not exhibit the issue (if applicable): N/A
Desktop OS/version used to run Appium: Windows 10 Enterprise x64
Node.js version (unless using Appium.app|exe): N/A
Mobile platform/version under test: Android version 8.1.0
Real device or emulator/simulator: Real Device, General Mobile 8
Appium CLI or Appium.app|exe: Appium.exe, Graphical interface for the Appium server, and an app inspector.

p.s. 
1. I tried the same scenario with various Android phones(Android versions 5,6,7,8), Chromedriver versions (2.22, 2.23, 2.24, 2.33, 2.36, 2.37, 2.38, 2.39, 2.40, 2.41).
2. I can see the webview using Chrome debug remote devices. See attached snapshot.
![capture](https://user-images.githubusercontent.com/11345785/44138508-e014b094-a07c-11e8-90d2-fb80d5768388.PNG)

## Details

1. AUT started
2. Context handles set contains ;
[NATIVE_APP, WEBVIEW_stetho_com.rbbn.optus.smb, WEBVIEW_com.genband.smartoffice]
3. driver.context("WEBVIEW_com.genband.smartoffice");
4. I see the following error in apium logs.
[Chromedriver] Error: Failed to start Chromedriver session: An unknown server-side error occurred while processing the command. (Original error: unknown error: Failed to get sockets matching: @webview_devtools_remote_.*24811

## Link to Appium logs

https://gist.github.com/dokmetas/f45ade6b1309cc2117726fb1ec7b88f4

**Comment by mykola-mokhnach** [comment]
@imurchie FYI

**Comment by robin-xl** [comment]
@dokmetas did you set webview debug?
```
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
    WebView.setWebContentsDebuggingEnabled(true);
}
```

**Comment by dokmetas** [comment]
@robin-xl 
the fact that I can see webview via Chrome dev tools /remote devices means debugging enabled. isn't it? Let me know if that is not the case.

**Comment by ColinCee** [comment]
I'm also having the same issue, any updates?

**Comment by mykola-mokhnach** [comment]
I would say it is a problem with Crosswalk webview itself. Check https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/issues/229 https://github.com/appium/appium/issues/4620 for more details.

Closed as third party issue

**Comment by Lanuet** [comment]
Anyone have solution, i get the same issue. Im using python, when trying switch to webview, i get the problem. I can see webview via Chrome dev tools devices. chromedriver is latest version. I dont know why? Can anyone help me? plsss

selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Failed to start Chromedriver session: An unknown server-side error occurred while processing the command. Original error: unknown error: Failed to get sockets matching: @webview_devtools_remote_.*11000
  (make sure the app has its WebView configured for debugging)
  (Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5),platform=Windows NT 10.0.17134 x86_64)

**Comment by benfr1** [comment]
reproduced with chrome V73.0.3683 and appium server 1.12.1 installed by default :
io.appium.java_client.NoSuchContextException: An unknown server-side error occurred while processing the command. Original error: Failed to start Chromedriver session: An unknown server-side error occurred while processing the command. Original error: unknown error: Failed to get sockets matching: @webview_devtools_remote_.*14253
  (make sure the app has its WebView configured for debugging)

**Comment by benfr1** [comment]
I found a solution

**Comment by walternolak** [comment]
> I found a solution

Hi, can you please share your solution.. I'm having the same issue right now.
Thanks in advance.

**Comment by benfr1** [comment]
sure. just try the solution https://stackoverflow.com/questions/54671269/appium-protractor-cordova-app-when-i-try-to-run-simple-test-i-get-following/55899339#55899339 I just put there.

**Comment by JohnnyVip** [comment]
> @dokmetas did you set webview debug?
> 
> ```
> if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
>     WebView.setWebContentsDebuggingEnabled(true);
> }
> ```

 I got you, haha
