### ISSUE TITLE
Running a test multiple times produces different location and size values for the same element, which causes misclicks

### ISSUE THREAD

**Issue by mc-sm** [appium/appium#11188]
## The problem

Inconsistent behavior is occurring when running an Appium test script (.java) on multiple occasions to test an Android app. The script successfully finds the target element that needs to be clicked. On some occasions the test script successfully clicks the target element. However, on other occasions the script performs a click but fails to click the target element; instead it clicks a location on the the screen where the element is not located.

When applying the getLocation() and getSize() methods to the target element, on some occasions the location and size values are correct and other times they are incorrect. The x-axis values are always correct but the y-axis values are often incorrect. In other words, Appium sometimes identifies the wrong Y-axis value and the wrong height for the element. This prevents the script from successfully clicking the element. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.2 (Appium Desktop)
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): 8.9.3
* Mobile platform/version under test: Android 5.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium Desktop

## Additional Details

* The problem often occurs when Chrome Inspect is running (chrome://inspect/#devices).
* The click() method is being used to click the target element.
* The isDisplayed() method confirms that the test does find the element.
* The app is created with Cordova.
* The underlying HTML used by Cordova to create the app includes use of Bootstrap modals.
* The context of the view where the problem occurs is Native, not WebView.
* The "Point location" setting is activated in the device's Developer Options, so we're able to observe the click occur but in the wrong location on the screen.

## Link to Appium logs

https://gist.github.com/mc-sm/3d85e6410f2986b53464bc0b58ac7a1d

**Comment by mykola-mokhnach** [comment]
Do you switch to web context? Working with web views in native context is expected to be unstable
