### ISSUE TITLE
Touch Action Does Nothing

### ISSUE THREAD

**Issue by davidamplify** [appium/appium#11181]
## The problem

Trying to use Touch Action to interact with sliding date picker and scroll down a page. However what I'm writing produces no errors but does nothing.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium: Mac OS High Sierra 10.13.6
* Node.js version (unless using Appium.app|exe): Appium.app
* Mobile platform/version under test: iPhone 6/11.4
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium.app

## Details

code is executed but nothing happens. Below touch action code is scrolling code which scrolls down as expected (picture included) and would be perfectly usable if I could control the amount it scrolls. Any help much appreciated!

## Link to Appium logs

https://gist.github.com/davidamplify/bc72c9d77579d421a61a0381b34ebc0b

## Code To Reproduce Issue [ Good To Have ]

`IOSElement daydate = (IOSElement) driver.findElementByAccessibilityId("Aug");
    
int x = daydate.getLocation().getX();
    
int y = daydate.getLocation().getY();
     
setDriverToWebContext(); (function I wrote that changes driver (IOSDriver) to Webview

 io.appium.java_client.TouchAction action = new TouchAction((IOSDriver)driver);
action.press(PointOption.point(x, y)).moveTo(PointOption.point(x, y + 80)).release().perform();
JavascriptExecutor js2 = (JavascriptExecutor) driver;
HashMap<String, String> scrollObject2 = new HashMap<String, String>();
scrollObject2.put("direction", "down");
scrollObject2.put("element", ((IOSElement) daydate).getId());
js2.executeScript("mobile: scroll", scrollObject);`

**Comment by mykola-mokhnach** [comment]
Add 600ms delay after `press`

**Comment by davidamplify** [comment]
@mykola-mokhnach how do I do that? Sorry, new to this also thanks for all your help on other posts they have been very useful

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/java-client/blob/742db4eb751c07e93c58e697d8fe21cde2849135/src/test/java/io/appium/java_client/ios/IOSTouchTest.java#L68

**Comment by davidamplify** [comment]
ah awesome thanks it worked cheers

**Comment by moagarwa** [comment]
I am checking your solution.
Please give me one hour and I will revert on this thread

**Comment by moagarwa** [comment]
Thanks @mykola-mokhnach. It worked like charm for me.
Need one more help, since I am new to Appium. Earlier we used to find an object on scroller but just the accessibility ID, but now I think we need to scroll to the element and tap that element.
Can you please help me with the API to tap on the element on the scroller that is not on screen.

Waiting for your reply.
Thanks,
Mohit

**Comment by mykola-mokhnach** [comment]
Please use appium forum to ask questions

**Comment by moagarwa** [comment]
I will definitely do that but it would be really great, if you can help me with the same as we have a release scheduled and I am running out of time.

Thanks in advance for your help.

**Comment by amit-punjabi** [comment]
After adding **wait** as mentioned [here](https://github.com/appium/appium/issues/11181#issuecomment-412884102), not able to perform swipe on iOS. I have added the details here- [12474](https://github.com/appium/appium/issues/12474)
