### ISSUE TITLE
Deep linking does not work when iOS Siri language is not English

### ISSUE THREAD

**Issue by sanlengjingvv** [appium/appium#11187]
## The problem

When siri language is Chinese, url endpoint not work. It works fine when language is English.

POST /wd/hub/session/:session_id/url
```JSON
{"url": "bilibili://"}
```
![img_2518](https://user-images.githubusercontent.com/6478615/44134323-023be3e4-a097-11e8-8e11-83c2c694a814.PNG)

## Environment

Appium 1.8.1
iOS 11.4.1

**Comment by mykola-mokhnach** [comment]
Sorry, there's nothing we can do to address it. You could change the code locally though: https://github.com/appium/WebDriverAgent/blob/c4cbd8002053c20339779b3643ae50ee0138257e/WebDriverAgentLib/Categories/XCUIDevice%2BFBHelpers.m#L222

Or switch the device language to English.
