### ISSUE TITLE
Encountered internal error when tap element

### ISSUE THREAD

**Issue by goel-shobit** [appium/appium#11199]
## The problem
Encounter internal error when tap element in Android

## Environment
* Appium version (or git revision) that exhibits the issue:1.8.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac 10.13.1
* Node.js version (unless using Appium.app|exe):10.4.1
* Mobile platform/version under test:Android 7.0
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe: CLI

## Details

Similar code works for iOS without any error but giving issue in Android 

## Link to Appium logs
[](https://gist.github.com/goel-shobit/69cafa34d0488d2b0debc5314071390f)

## Code To Reproduce Issue [ Good To Have ]
androidDriver = new AndroidDriver<AndroidElement>(new URL(driverCapabilities.serverUrl),
									capabilities);
							androidDriver.manage().timeouts().implicitlyWait(implicitWait, TimeUnit.SECONDS);

new TouchAction<>(androidDriver)
							.tap(new TapOptions().withElement(ElementOption.element(remoteWebElement)))
							.waitAction(WaitOptions.waitOptions(Duration.ofMillis(dwell))).release().perform();

**Comment by robin-xl** [comment]
should attach appium server log

**Comment by goel-shobit** [comment]
I did. I linked it. 
https://gist.github.com/goel-shobit/69cafa34d0488d2b0debc5314071390f

**Comment by mykola-mokhnach** [comment]
> [debug] [JSONWP Proxy] Proxying [POST /touch/up] to [POST http://localhost:8200/wd/hub/session/aca6a8b6-d743-4738-8027-90a070f8ec5b/touch/up] with body: {"params":{"x":852.5,"y":1330}}

Are you sure that the second coordinate fits screen borders?

**Comment by goel-shobit** [comment]
yes, the tap is performed successfully but somehow it logs error.

**Comment by mykola-mokhnach** [comment]
What is the actual screen size? Can you also attach the `adb logcat` output?

**Comment by goel-shobit** [comment]
1080*2220
https://gist.github.com/goel-shobit/e7095f91e96e8ba87f3a25bcf7366e1a

**Comment by robin-xl** [comment]
if tap work, try to remove methed .release()

**Comment by goel-shobit** [comment]
I tried on couple of devices and so far not observed issue. I will do some more extensive testing on different devices and let you know. Thanks.

**Comment by goel-shobit** [comment]
Although it works fine after couple of days of testing but could you please explain why it is working for iOS and why not for Android?

**Comment by mykola-mokhnach** [comment]
Please use appium forum to ask question. Most likely people won't be able to explain the difference because:

- low-level touch actions emulation in general is quite complicated topic
- iOS XCTest is a proprietary framework, so nobody (except of Apple engineers) knows how it works under the hood.
