### ISSUE TITLE
isDisplayed() is not working in Xcode 9.4 , appium 1.7.1

### ISSUE THREAD

**Issue by SanjayDhami** [appium/appium#11191]
## The problem

I recently updated Xcode from 9.2 to 9.4.1 in order to support ios 11.4 and i found that element.isDisplayed is not working. It is returning false even element it displayed on the screen. How ever it was working in 9.2. Please help me.

Thank you

## Environment

* Last Appium version that did not exhibit the issue (if applicable):1.7.1
* Desktop OS/version used to run Appium: 10.13.6
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: 11.4.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

**Comment by mykola-mokhnach** [comment]
Appium 1.7.1 is outdated. Please upgrade to 1.8.1 or appium@beta
