### ISSUE TITLE
Exception in thread "main" org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command.

### ISSUE THREAD

**Issue by shilpatailor4** [appium/appium#11197]
## The problem

Appium version 1.8.0
Device Samsung Galaxy S4 (android 5.0.1)
Java 1.8.0

My first test to check whether appium is working correct:

import java.net.MalformedURLException;
import java.net.URL;

import org.openqa.selenium.remote.DesiredCapabilities;

import io.appium.java_client.AppiumDriver;
import io.appium.java_client.MobileElement;
import io.appium.java_client.android.AndroidDriver;

public class kitchen {

static AppiumDriver<MobileElement> driver = null;
public static MobileElement mobileElement;
public static void main(String[] args) throws InterruptedException {

DesiredCapabilities caps = new DesiredCapabilities();
caps.setCapability("deviceName", "My Phone");
caps.setCapability("udid", "e5696a1a0703");
caps.setCapability("platformName", "Android");
caps.setCapability("platformVersion", "7.0 NRD90M");
caps.setCapability("appPackage", "kichenmanager.sitsl");
caps.setCapability("appActivity", "kichenmanager.sitsl.activity.SplashScreen"); // cd downloads. where apk is present. give this command in terminal. aapt dump badging ./Downloads/kitchen_manager.apk
caps.setCapability("noReset", "true"); //Command to get App activity: aapt dump badging ./Downloads/kitchen_manager.apk

//Instantiate Appium Driver
try {
driver = new AndroidDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"), caps);

} catch (MalformedURLException e) {
System.out.println(e.getMessage());

}
Thread.sleep(5000);
if (driver!=null)
{
System.out.println("Driver is not null");
//driver.findElementById("kichenmanager.sitsl:id/imageViewMenu").click();
driver.findElementById("kichenmanager.sitsl:id/edtUsername").sendKeys("adm@gmail.com");
}

driver.findElementById("kichenmanager.sitsl:id/tv_title").click();
driver.findElementById("kichenmanager.sitsl:id/imageViewEditIcon").click();

}
}

When I run my first test I see below unknown server-side error:

[HTTP] {"desiredCapabilities":{"appActivity":"kichenmanager.sitsl.activity.SplashScreen","appPackage":"kichenmanager.sitsl","noReset":"true","platformVersion":"7.0 NRD90M","platformName":"Android","udid":"e5696a1a0703","deviceName":"My Phone"},"capabilities":{"alwaysMatch":{"appium:appActivity":"kichenmanager.sitsl.activity.SplashScreen","appium:appPackage":"kichenmanager.sitsl","appium:deviceName":"My Phone","appium:noReset":"true","platformName":"android","appium:platformVersion":"7.0 NRD90M","appium:udid":"e5696a1a0703"},"firstMatch":[{}]}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"appActivity":"kichenmanager.sitsl.activity.SplashScreen","appPackage":"kichenmanager.sitsl","noReset":"true","platformVersion":"7.0 NRD90M","platformName":"Android","udid":"e5696a1a0703","deviceName":"My Phone"},null,{"alwaysMatch":{"appium:appActivity":"kichenmanager.sitsl.activity.SplashScreen","appium:appPackage":"kichenmanager.sitsl","appium:deviceName":"My Phone","appium:noReset":"true","platformName":"android","appium:platformVersion":"7.0 NRD90M","appium:udid":"e5696a1a0703"},"firstMatch":[{}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1534482799199 (10:43:19 GMT+0530 (India Standard Time))
[BaseDriver] Boolean capability passed in as string. Functionality may be compromised.
[Appium] Consider setting 'automationName' capability to 'uiautomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.
[Appium] Creating new AndroidDriver (v2.7.0) session
[Appium] Capabilities:
[Appium]   platformName: android
[Appium]   appActivity: kichenmanager.sitsl.activity.SplashScreen
[Appium]   appPackage: kichenmanager.sitsl
[Appium]   deviceName: My Phone
[Appium]   noReset: true
[Appium]   platformVersion: 7.0 NRD90M
[Appium]   udid: e5696a1a0703
[debug] [BaseDriver] W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP desired capabilities [object Object] were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"platformNa...
[BaseDriver] Boolean capability passed in as string. Functionality may be compromised.
[BaseDriver] Capability 'noReset' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Session created with session id: 9bef3da9-d372-49f2-b455-f370751119a9
[debug] [AndroidDriver] Getting Java version
(node:7343) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[AndroidDriver] Java version is: 1.8.0_181
[ADB] Checking whether adb is present
[ADB] The ANDROID_HOME environment variable is not set to the Android SDK root directory path. ANDROID_HOME is required for compatibility with SDK 23+. Checking along PATH for adb.
[ADB] Using adb from /usr/bin/adb
[ADB] 
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[AndroidDriver] Using device: e5696a1a0703
[debug] [ADB] Setting device id to e5696a1a0703
[AndroidDriver] App file was not listed, instead we're going to run kichenmanager.sitsl directly on the device
[debug] [AndroidDriver] Checking whether package is present on the device
[debug] [ADB] Running '/usr/bin/adb -P 5037 -s e5696a1a0703 shell pm list packages kichenmanager.sitsl'
[AndroidDriver] Starting Android session
[debug] [ADB] Running '/usr/bin/adb -P 5037 -s e5696a1a0703 wait-for-device'
[debug] [ADB] Running '/usr/bin/adb -P 5037 -s e5696a1a0703 shell echo ping'
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Getting install status for io.appium.settings
[debug] [ADB] Running '/usr/bin/adb -P 5037 -s e5696a1a0703 shell pm list packages io.appium.settings'
[debug] [ADB] App is not installed
[debug] [ADB] App '/home/shilpatailor/.linuxbrew/lib/node_modules/appium/node_modules/io.appium.settings/app/build/outputs/apk/settings_apk-debug.apk' not installed. Installing
[debug] [ADB] Running '/usr/bin/adb -P 5037 -s e5696a1a0703 shell getprop ro.build.version.sdk'
[debug] [ADB] Current device property 'ro.build.version.sdk': 24
[debug] [ADB] Device API level: 24
[debug] [ADB] Running '/usr/bin/adb -P 5037 -s e5696a1a0703 install -g /home/shilpatailor/.linuxbrew/lib/node_modules/appium/node_modules/io.appium.settings/app/build/outputs/apk/settings_apk-debug.apk'
[debug] [ADB] Install command stdout: Error: java.lang.SecurityException: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag
[debug] [ADB] Running '/usr/bin/adb -P 5037 -s e5696a1a0703 shell ps'
[debug] [ADB] Device API level: 24
[debug] [ADB] Running '/usr/bin/adb -P 5037 -s e5696a1a0703 shell am start -W -n io.appium.settings/.Settings -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[AndroidDriver] Failed to launch settings app: Cannot start the 'io.appium.settings' application. Original error: Activity name '.Settings' used to start the app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity
[debug] [ADB] Device API level: 24
[debug] [ADB] Running '/usr/bin/adb -P 5037 -s e5696a1a0703 shell appops set io.appium.settings android\:mock_location allow'
[AndroidDriver] setDeviceLanguageCountry requires language or country.
[AndroidDriver] Got language: 'null' and country: 'null'
[debug] [Logcat] Starting logcat capture
[debug] [AndroidDriver] Pushing unlock helper app to device...
[debug] [ADB] Getting install status for io.appium.unlock
[debug] [ADB] Running '/usr/bin/adb -P 5037 -s e5696a1a0703 shell pm list packages io.appium.unlock'
[debug] [ADB] App is not installed
[debug] [ADB] App '/home/shilpatailor/.linuxbrew/lib/node_modules/appium/node_modules/appium-unlock/bin/unlock_apk-debug.apk' not installed. Installing
[debug] [ADB] Device API level: 24
[debug] [ADB] Running '/usr/bin/adb -P 5037 -s e5696a1a0703 install -g /home/shilpatailor/.linuxbrew/lib/node_modules/appium/node_modules/appium-unlock/bin/unlock_apk-debug.apk'
[debug] [ADB] Install command stdout: Error: java.lang.SecurityException: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag
[ADB] Getting device platform version
[debug] [ADB] Running '/usr/bin/adb -P 5037 -s e5696a1a0703 shell getprop ro.build.version.release'
[debug] [ADB] Current device property 'ro.build.version.release': 7.0
[debug] [ADB] Running '/usr/bin/adb -P 5037 -s e5696a1a0703 shell wm size'
[debug] [ADB] Running '/usr/bin/adb -P 5037 -s e5696a1a0703 shell getprop ro.product.model'
[debug] [ADB] Current device property 'ro.product.model': Redmi Note 4
[debug] [ADB] Running '/usr/bin/adb -P 5037 -s e5696a1a0703 shell getprop ro.product.manufacturer'
[debug] [ADB] Current device property 'ro.product.manufacturer': Xiaomi
[AndroidDriver] No app sent in, not parsing package/activity
[debug] [AndroidDriver] No app capability. Assuming it is already on the device
[debug] [AndroidBootstrap] Watching for bootstrap disconnect
[debug] [ADB] Forwarding system: 4724 to device: 4724
[debug] [ADB] Running '/usr/bin/adb -P 5037 -s e5696a1a0703 forward tcp\:4724 tcp\:4724'
[debug] [UiAutomator] Starting UiAutomator
[debug] [UiAutomator] Moving to state 'starting'
[debug] [UiAutomator] Parsing uiautomator jar
[debug] [UiAutomator] Found jar name: 'AppiumBootstrap.jar'
[debug] [ADB] Running '/usr/bin/adb -P 5037 -s e5696a1a0703 push /home/shilpatailor/.linuxbrew/lib/node_modules/appium/node_modules/appium-android-bootstrap/bootstrap/bin/AppiumBootstrap.jar /data/local/tmp/'
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Running '/usr/bin/adb -P 5037 -s e5696a1a0703 shell ps'
[ADB] No uiautomator process found to kill, continuing...
[debug] [UiAutomator] Starting UIAutomator
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","e5696a1a0703","shell","uiautomator","runtest","AppiumBootstrap.jar","-c","io.appium.android.bootstrap.Bootstrap","-e","pkg","kichenmanager.sitsl","-e","disableAndroidWatchers",false,"-e","acceptSslCerts",false]
[debug] [UiAutomator] Moving to state 'online'
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Loading json...
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Registered crash watchers.
[AndroidBootstrap] Android bootstrap socket is now connected
[debug] [ADB] Running '/usr/bin/adb -P 5037 -s e5696a1a0703 shell dumpsys window'
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Client connected
[debug] [AndroidDriver] Screen is locked, trying to unlock
[AndroidDriver] Using app unlock, this is going to be deprecated!
[AndroidDriver] Unlocking screen
[debug] [ADB] Running '/usr/bin/adb -P 5037 -s e5696a1a0703 shell am force-stop io.appium.unlock'
[AndroidDriver] Launching io.appium.unlock
[debug] [ADB] Device API level: 24
[debug] [ADB] Running '/usr/bin/adb -P 5037 -s e5696a1a0703 shell am start -W -n io.appium.unlock/.Unlock -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[debug] [ADB] Running '/usr/bin/adb -P 5037 -s e5696a1a0703 shell dumpsys window'
[AndroidDriver] Launching io.appium.unlock
[debug] [ADB] Device API level: 24
[debug] [ADB] Running '/usr/bin/adb -P 5037 -s e5696a1a0703 shell am start -W -n io.appium.unlock/.Unlock -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[debug] [ADB] Running '/usr/bin/adb -P 5037 -s e5696a1a0703 shell dumpsys window'
[AndroidDriver] Launching io.appium.unlock
[debug] [ADB] Device API level: 24
[debug] [ADB] Running '/usr/bin/adb -P 5037 -s e5696a1a0703 shell am start -W -n io.appium.unlock/.Unlock -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[debug] [AndroidDriver] Shutting down Android driver
[debug] [ADB] Running '/usr/bin/adb -P 5037 -s e5696a1a0703 shell am force-stop kichenmanager.sitsl'
[debug] [ADB] Pressing the HOME button
[debug] [ADB] Running '/usr/bin/adb -P 5037 -s e5696a1a0703 shell input keyevent 3'
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"shutdown"}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"shutdown"}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [UiAutomator] Shutting down UiAutomator
[debug] [UiAutomator] Moving to state 'stopping'
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type SHUTDOWN
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
[debug] [UiAutomator] UiAutomator shut down normally
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Running '/usr/bin/adb -P 5037 -s e5696a1a0703 shell ps'
[ADB] No uiautomator process found to kill, continuing...
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Running '/usr/bin/adb -P 5037 -s e5696a1a0703 shell am force-stop io.appium.unlock'
[debug] [AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1534482814294 (10:43:34 GMT+0530 (India Standard Time))
[W3C] Encountered internal error running command: Error: Cannot start the 'io.appium.unlock' application. Original error: Activity name '.Unlock' used to start the app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity
[W3C]     at ADB.callee$0$0$ (/home/shilpatailor/.linuxbrew/lib/node_modules/appium/node_modules/appium-adb/lib/tools/apk-utils.js:125:11)
[W3C]     at tryCatch (/home/shilpatailor/.linuxbrew/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/home/shilpatailor/.linuxbrew/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/shilpatailor/.linuxbrew/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[W3C]     at GeneratorFunctionPrototype.invoke (/home/shilpatailor/.linuxbrew/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 15130 ms - 1570

**Comment by mykola-mokhnach** [comment]
First, there are several major warnings you need to consider:

> [Appium] Consider setting 'automationName' capability to 'uiautomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.

> [ADB] The ANDROID_HOME environment variable is not set to the Android SDK root directory path. ANDROID_HOME is required for compatibility with SDK 23+. Checking along PATH for adb.

Second:
> [debug] [ADB] Install command stdout: Error: java.lang.SecurityException: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag

It looks like either ADB manager is corrupted/outdated or something is wrong with the device under test. Normally, it should not complain about installing packages with `-g` option. Try another device

**Comment by shilpatailor4** [comment]
#mykola-mokhanach ok thanks
