### ISSUE TITLE
Appium cant find elements when Agreement to sending and reading SMS was shown before

### ISSUE THREAD

**Issue by piotrekcz** [appium/appium#11198]
Hi everyone,

Currently I am testing android app. And I identify  2 problems.
1. When I am using UI inspector and App will show message form with question about access to sending and reading SMS, and next I click Allow or Deny (it doesn't matter) Appium inspector hangs.
2. I do above steps by Appium programatically and result of it is that Appium cant find any object on view which is under message with question.

I am sure that cause of this problems is message from Android system because when I grant permission in capabilities there is no problem.

Problem from 1st point was solved when I updated Appium to 1.6.3 but 2nd still exist. 

## Environment

* For both point 1.6.2, for only 2 1.6.3
* 1.6.3
* macOS High Sierra
* Android 8.0
* emulator
* Appium CLI or Appium.app|exe:

**Comment by mykola-mokhnach** [comment]
Please attach the server log

**Comment by piotrekcz** [comment]
Currently problem from 1st point is still existing .
I attached log for 1st and 2nd problem.
[log1.docx](https://github.com/appium/appium/files/2296405/log1.docx)
[log2.docx](https://github.com/appium/appium/files/2296406/log2.docx)

**Comment by mykola-mokhnach** [comment]
Can you attach the files as gists? I don't have msword to read them

**Comment by piotrekcz** [comment]
[log2.zip](https://github.com/appium/appium/files/2296601/log2.zip)
[log1.zip](https://github.com/appium/appium/files/2296602/log1.zip)

**Comment by mykola-mokhnach** [comment]
Switch to UIAutomator2

**Comment by piotrekcz** [comment]
How should I do it ?

**Comment by piotrekcz** [comment]
Ok it helped. Please explain me more clearly what is the cause of this problem.

**Comment by mykola-mokhnach** [comment]
This has been discussed many times here. Kindly use search

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by piotrekcz** [comment]
Thank you for your help.
