### ISSUE TITLE
Running the Ruby examples with Appium 1.8.1 fails with "no sessionId in returned payload"

### ISSUE THREAD

**Issue by fpbouchard** [appium/appium#11200]
## The problem

Running the Ruby examples with Appium 1.8.1 fails with a 
```
Selenium::WebDriver::Error::WebDriverError:
       no sessionId in returned payload
```
Reproduced on multiple computers.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8 flavours (works with 1.7.1 & 1.7.2, does not work with 1.8.0, 1.8.1 & 1.8.2beta)
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2
* Desktop OS/version used to run Appium: MacOS 10.13.3
* Node.js version (unless using Appium.app|exe): 9.4.0
* Mobile platform/version under test: iOS 11.1 (tried with 10.3, 11.0 & 11.3)
* Real device or emulator/simulator: Simulator (6s as in example)
* Appium CLI or Appium.app|exe: Ruby gem

## Details

Installing from scratch, having this issue.

## Link to Appium logs

Appium log: https://gist.github.com/fpbouchard/71473d828a3df1f47b5999879f898ff2
Ruby log: https://gist.github.com/fpbouchard/f535365bfb4b3228206aae70603831af

## Code To Reproduce Issue [ Good To Have ]

`bundle exec rspec spec/ios_basic_interactions_spec.rb`

**Comment by mykola-mokhnach** [comment]
Which examples did you run? 

https://github.com/appium-boneyard/sample-code is not supported anymore

**Comment by fpbouchard** [comment]
In this repo: `appium/sample-code/ruby/spec/ios_basic_interactions_spec.rb`

**Comment by mykola-mokhnach** [comment]
@KazuCocoa Do you know something about this code?

**Comment by fpbouchard** [comment]
The example itself isn't important. `start_session` fails no matter from where we call it from 1.8 onwards.

It seems to be a problem with how the result is sent back from appium to the client libraries because we have the same issue with the python client (no sessionId in returned payload). This bubbles up from the selenium web driver.

**Comment by KazuCocoa** [comment]
I haven't faced such error...

I haven't tried node `9.4.0`. Let me try the version.
In my local, I just ran current master's the same sample code with node `9.3.0`. It worked.

**Comment by fpbouchard** [comment]
We also tried with `8.11.1`. I'll try with `9.3.0`.

**Comment by mykola-mokhnach** [comment]
There are no failures in the server log. There must be a problem in client libs

**Comment by KazuCocoa** [comment]
It worked with 9.4.0.
https://gist.github.com/KazuCocoa/0875bfb81f6e3ce0cf47f0e6437795b3

The ruby lib is `'~> 9.10'` in the Gemfile. The version should work with Appium 1.8.x 🤔

**Comment by fpbouchard** [comment]
Issue seems to be with my node installation. Trying a full fresh install and reporting back.

**Comment by fpbouchard** [comment]
I got it working. Is this test failure expected?

https://gist.github.com/fpbouchard/add69f66cc36c160e458b5e41a19aead

**Comment by KazuCocoa** [comment]
yes, so far. I'll update it.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
