### ISSUE TITLE
Could not find adb.exe

### ISSUE THREAD

**Issue by prajaktachougule** [appium/appium#11209]
## The problem

I am new to this appium...and m not able to launch app
## Environment

* Appium version (or git revision) that exhibits the issue:1.6.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: windows 10
* Node.js version (unless using Appium.app|exe):8.11.4
* Mobile platform/version under test:Andriod
* Real device or emulator/simulator:Galaxy J7
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by KazuCocoa** [comment]
> Could not find adb.exe in C:\Users\Owner\AppData\Local\Android\Sdk\platform-tools\platform-tools\adb.exe,C:\Users\Owner\AppData\Local\Android\Sdk\platform-tools\emulator\adb.exe,C:\Users\Owner\AppData\Local\Android\Sdk\platform-tools\tools\adb.exe,C:\Users\Owner\AppData\Local\Android\Sdk\platform-tools\tools\bin\adb.exe. Do you have the Android SDK installed at 'C:\Users\Owner\AppData\Local\Android\Sdk\platform-tools'

Where did you set the path to `adb.exe`?
Appium couldn't find `adb.exe` in `C:\Users\Owner\AppData\Local\Android\Sdk\platform-tools\platform-tools\adb.exe`. I guess `$ANDROID_HOME` is wrong in your env.

**Comment by mykola-mokhnach** [comment]
Please refer https://github.com/appium/java-client/blob/master/docs/environment.md for environment setup

**Comment by mykola-mokhnach** [comment]
Also full server log is necessary
