### ISSUE TITLE
How to resolve the Failed to create WDA session. Retrying... Exception in iOS Simulators

### ISSUE THREAD

**Issue by Manish503** [appium/appium#11218]
## The problem

Failed to create WDA session. Retrying in IOS Emulators

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Xcode: 9.1
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

Below details are capabilities

"deviceName": "iPhone 7 Plus",
  "platformVersion": "11.1",
  "noReset": true,
  "udid": "AAAF863B-8E86-4D88-9B9F-3AE90687FCF3",
  "app": "/Users/anakin/Downloads/MKETradeSIT 3.app",
  "platformName": "IOS",
  "useNewWDA": true,
  "clearSystemFiles": true,
  "shouldUseTestManagerForVisibilityDetection": false,
  "shouldUseSingletonTestManager": true,
  "shouldWaitForQuiescence": true,
  "showXcodeLog": true,
  "bundleId": "com.mayBank.MKETradeSIT",
  "automationName": "XCUITest",
  "startIWDP": true

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
No suggestions are possible without detailed server logs. Also, the device log might be necessary

**Comment by Manish503** [comment]
@mykola-mokhnach Thanks
Please find the below logs

Appium] Creating new XCUITestDriver (v2.84.0) session
[Appium] Capabilities:
[Appium]   app: /Users/anakin/Downloads/MKETradeSIT 3.app
[Appium]   automationName: XCUITest
[Appium]   bundleId: com.mayBank.MKETradeSIT
[Appium]   clearSystemFiles: true
[Appium]   deviceName: iPhone 7 Plus
[Appium]   noReset: true
[Appium]   platformName: IOS
[Appium]   platformVersion: 11.1
[Appium]   shouldUseSingletonTestManager: true
[Appium]   shouldUseTestManagerForVisibilityDetection: false
[Appium]   shouldWaitForQuiescence: true
[Appium]   showXcodeLog: true
[Appium]   startIWDP: true
[Appium]   udid: AAAF863B-8E86-4D88-9B9F-3AE90687FCF3
[Appium]   useNewWDA: true
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[BaseDriver] Creating session with MJSONWP desired capabilities: {"app":"/Users/anakin/Downl...
[BaseDriver] The following capabilities were provided, but are not recognized by appium: shouldUseTestManagerForVisibilityDetection, shouldWaitForQuiescence.
[BaseDriver] Session created with session id: 2276bc85-bbdc-449a-952e-d343dc1de8f5
[XCUITest] Current user: 'anakin'
[XCUITest] Xcode version set to '9.1' (tools v9.2.0.0.1.1510905681)
[XCUITest] iOS SDK Version set to '11.1'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1534839871236 (16:24:31 GMT+0800 (+08))
[iOSSim] Constructing iOS simulator for Xcode version 9.1 with udid 'AAAF863B-8E86-4D88-9B9F-3AE90687FCF3'
[XCUITest] Determining device to run tests on: udid: 'AAAF863B-8E86-4D88-9B9F-3AE90687FCF3', real device: false
[BaseDriver] Using local app '/Users/anakin/Downloads/MKETradeSIT 3.app'
[BaseDriver] Event 'appConfigured' logged at 1534839871632 (16:24:31 GMT+0800 (+08))
[XCUITest] Checking whether app '/Users/anakin/Downloads/MKETradeSIT 3.app' is actually present on file system
[XCUITest] App is present
[BaseDriver] Event 'resetStarted' logged at 1534839871633 (16:24:31 GMT+0800 (+08))
[XCUITest] Reset: noReset is on. Leaving simulator as is
[BaseDriver] Event 'resetComplete' logged at 1534839871634 (16:24:31 GMT+0800 (+08))
[XCUITest] Starting log capture for iOS Simulator with udid 'AAAF863B-8E86-4D88-9B9F-3AE90687FCF3', using 'xcrun simctl spawn AAAF863B-8E86-4D88-9B9F-3AE90687FCF3 log stream --style compact'
[BaseDriver] Event 'logCaptureStarted' logged at 1534839872246 (16:24:32 GMT+0800 (+08))
[XCUITest] Setting up simulator
[iOS] No reason to set locale
[iOS] No iOS / app preferences to set
[iOSSim] Matched 1 Simulator cache item for cleanup: /Users/anakin/Library/Developer/CoreSimulator/Devices/AAAF863B-8E86-4D88-9B9F-3AE90687FCF3/data/Library/Caches/com.apple.mobile.installd.staging
[iOSSim] Setting preferences of AAAF863B-8E86-4D88-9B9F-3AE90687FCF3 Simulator to {"ConnectHardwareKeyboard":true}
[iOSSim] Setting common Simulator preferences to {"ConnectHardwareKeyboard":true}
[iOSSim] Updated AAAF863B-8E86-4D88-9B9F-3AE90687FCF3 Simulator preferences at '/Users/anakin/Library/Preferences/com.apple.iphonesimulator.plist' with {"DevicePreferences":{"AAAF863B-8E86-4D88-9B9F-3AE90687FCF3":{"ConnectHardwareKeyboard":true}},"ConnectHardwareKeyboard":true}
[iOSSim] The count of running Simulator UI client instances is 1
[iOSSim] Both Simulator with UDID AAAF863B-8E86-4D88-9B9F-3AE90687FCF3 and the UI client are currently running
[BaseDriver] Event 'simStarted' logged at 1534839872681 (16:24:32 GMT+0800 (+08))
[XCUITest] Verifying application platform
[XCUITest] CFBundleSupportedPlatforms: ["iPhoneOS"]
[XCUITest] *********************************
[XCUITest] Simulator architecture appears to be unsupported by the '/Users/anakin/Downloads/MKETradeSIT 3.app' application. Make sure the correct deployment target has been selected for its compilation in Xcode.
[XCUITest] Don't be surprised if the application fails to launch.
[XCUITest] *********************************
[XCUITest] App 'com.mayBank.MKETradeSIT' is already installed. No need to reinstall.
[BaseDriver] Event 'appInstalled' logged at 1534839872842 (16:24:32 GMT+0800 (+08))
[XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[XCUITest] Capability 'useNewWDA' set to true, so uninstalling WDA before proceeding
[XCUITest] Shutting down sub-processes
[XCUITest] Removing WDA application from device
[BaseDriver] Event 'wdaUninstalled' logged at 1534839874143 (16:24:34 GMT+0800 (+08))
[BaseDriver] Event 'wdaStartAttempted' logged at 1534839874145 (16:24:34 GMT+0800 (+08))
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Killing running processes 'xcodebuild.*AAAF863B-8E86-4D88-9B9F-3AE90687FCF3, iproxy 8100, AAAF863B-8E86-4D88-9B9F-3AE90687FCF3.*XCTRunner' for the device AAAF863B-8E86-4D88-9B9F-3AE90687FCF3...
[XCUITest] 'pgrep -nif xcodebuild.*AAAF863B-8E86-4D88-9B9F-3AE90687FCF3' didn't detect any matching processes. Return code: 1
[XCUITest] 'pgrep -nif iproxy 8100' didn't detect any matching processes. Return code: 1
[XCUITest] 'pgrep -nif AAAF863B-8E86-4D88-9B9F-3AE90687FCF3.*XCTRunner' didn't detect any matching processes. Return code: 1
[XCUITest] Using Xcode 9.1, so fixing WDA codebase
[XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=AAAF863B-8E86-4D88-9B9F-3AE90687FCF3 IPHONEOS_DEPLOYMENT_TARGET=11.1' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Output from xcodebuild will be logged. To change this, use 'showXcodeLog' desired capability
[Xcode] Build settings from command line:
[Xcode] 
[XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode]     IPHONEOS_DEPLOYMENT_TARGET = 11.1
[Xcode] 
[Xcode] 
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] === BUILD TARGET WebDriverAgentLib OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===
[Xcode] 
[Xcode] 
[Xcode] 
[Xcode] 
[Xcode] Check dependencies
[Xcode] 
[Xcode] 
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] 
[Xcode] 
[Xcode] === BUILD TARGET WebDriverAgentRunner OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===
[Xcode] 
[Xcode] 
[Xcode] 
[Xcode] 
[Xcode] Check dependencies
[Xcode] 
[Xcode] 
[Xcode] 
[Xcode] ** TEST BUILD SUCCEEDED **
[Xcode] 
[Xcode] 
[XCUITest] Log file for xcodebuild test: /var/folders/g5/y4w2fpm93f7cgc4fl8prgxw40000gn/T/com.apple.dt.XCTest/IDETestRunSession-846AF081-7205-40F7-B635-EABA4E680401/WebDriverAgentRunner-9AC874CF-1EFB-47CC-AECF-C5FEA46D6FA0/Session-WebDriverAgentRunner-2018-08-21_162436-zK6js0.log
[Xcode] 2018-08-21 16:24:36.523 xcodebuild[13969:543379]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
[Xcode] /var/folders/g5/y4w2fpm93f7cgc4fl8prgxw40000gn/T/com.apple.dt.XCTest/IDETestRunSession-846AF081-7205-40F7-B635-EABA4E680401/WebDriverAgentRunner-9AC874CF-1EFB-47CC-AECF-C5FEA46D6FA0/Session-WebDriverAgentRunner-2018-08-21_162436-zK6js0.log
[Xcode] 
[Xcode] 2018-08-21 16:24:36.524 xcodebuild[13969:543366] [MT] IDETestOperationsObserverDebug: (1067C03B-56EE-44F7-A6DE-5749F4F4BBA3) Beginning test session WebDriverAgentRunner-1067C03B-56EE-44F7-A6DE-5749F4F4BBA3 at 2018-08-21 16:24:36.524 with Xcode 9B55 on target  {
[Xcode] 		SimDevice: iPhone 7 Plus (AAAF863B-8E86-4D88-9B9F-3AE90687FCF3, iOS 11.1, Booted)
[Xcode] } (11.1 (15B87))
[Xcode] 
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"11.1\",\n      \"sdkVersion\" : \"11.1\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"11.1\",\n      \"ip\" : \"10.252.198.158\"\n    },\n    \"build\" : {\n      \"time\" : \"Jul 24 2018 11:22:30\"\n    }\n  },\n  \"sessionId\" : \"6B2E30AB-FCE4-4602-9058-97223F93A181\",\n  \"status\" : 0\n}"
[XCUITest] WebDriverAgent running on ip '10.252.198.158'
[XCUITest] WebDriverAgent successfully started after 6280ms
[BaseDriver] Event 'wdaSessionAttempted' logged at 1534839880835 (16:24:40 GMT+0800 (+08))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.mayBank.MKETradeSIT","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.mayBank.MKETradeSIT application","sessionId":"6B2E30AB-FCE4-4602-9058-97223F93A181","status":13}
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1534840063090 (16:27:43 GMT+0800 (+08))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.mayBank.MKETradeSIT","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.mayBank.MKETradeSIT application","sessionId":"6B2E30AB-FCE4-4602-9058-97223F93A181","status":13}
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1534840245393 (16:30:45 GMT+0800 (+08))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.mayBank.MKETradeSIT","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.mayBank.MKETradeSIT application","sessionId":"6B2E30AB-FCE4-4602-9058-97223F93A181","status":13}
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1534840427658 (16:33:47 GMT+0800 (+08))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.mayBank.MKETradeSIT","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[HTTP] <-- POST /wd/hub/session - - ms - -
[HTTP] 
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"/Users/anakin/Downloads/MKETradeSIT 3.app","automationName":"XCUITest","bundleId":"com.mayBank.MKETradeSIT","clearSystemFiles":true,"deviceName":"iPhone 7 Plus","noReset":true,"platformName":"IOS","platformVersion":"11.1","shouldUseSingletonTestManager":true,"shouldUseTestManagerForVisibilityDetection":false,"shouldWaitForQuiescence":true,"showXcodeLog":true,"startIWDP":true,"udid":"AAAF863B-8E86-4D88-9B9F-3AE90687FCF3","useNewWDA":true,"newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/anakin/Downloads/MKETradeSIT 3.app","automationName":"XCUITest","bundleId":"com.mayBank.MKETradeSIT","clearSystemFiles":true,"deviceName":"iPhone 7 Plus","noReset":true,"platformName":"IOS","platformVersion":"11.1","shouldUseSingletonTestManager":true,"shouldUseTestManagerForVisibilityDetection":false,"shouldWaitForQuiescence":true,"showXcodeLog":true,"startIWDP":true,"udid":"AAAF863B-8E86-4D88-9B9F-3AE90687FCF3","useNewWDA":true,"newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1534840470972 (16:34:30 GMT+0800 (+08))

**Comment by mykola-mokhnach** [comment]
```
[XCUITest] Verifying application platform
[XCUITest] CFBundleSupportedPlatforms: ["iPhoneOS"]
[XCUITest] *********************************
[XCUITest] Simulator architecture appears to be unsupported by the '/Users/anakin/Downloads/MKETradeSIT 3.app' application. Make sure the correct deployment target has been selected for its compilation in Xcode.
[XCUITest] Don't be surprised if the application fails to launch.
[XCUITest] *********************************
```

You need the app to be built for Simulator. Closed as not an issue

**Comment by Manish503** [comment]
@mykola-mokhnach 
My development provide that file in debug mode can you please elaborate 'app to be built for Simulator' what it means ,facing this issue from last 20 days onwards could you please help me.
Thanks

**Comment by mykola-mokhnach** [comment]
Read https://github.com/appium/appium/issues/10961
