### ISSUE TITLE
IOS hybrid app, unable to find element when app opens link within app browser

### ISSUE THREAD

**Issue by sumanguduru** [appium/appium#11213]
## The problem
Hi , im not able to find the elements on page when app open the link within app browser in ios real devices.

But in the case of android i can use driver.getWindowhandle to move the the control to new page.

## Environment

* Appium version (or git revision) that exhibits the issue:1.8.2 beta
* Last Appium version that did not exhibit the issue (if applicable):n/a
* Desktop OS/version used to run Appium: mac os
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: 11.4
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

**Comment by sumanguduru** [comment]
![screen shot 2018-08-20 at 10 52 01 am](https://user-images.githubusercontent.com/40868667/44351366-b7fdf880-a46f-11e8-9e7a-66f222f77328.png)

**Comment by sumanguduru** [comment]
i have attached the screen shot where i can see the both pages in Safari.
and i tried with the Set<String> contextNames = driver.getContextHandles(); on both pages it's getting the [NATIVE_APP,WEBVIEW_1] on both pages

**Comment by mykola-mokhnach** [comment]
Any logs?

**Comment by sumanguduru** [comment]
please find below link for logs

https://gist.github.com/sumanguduru/c92539718d502d22b50e61a57fed2c64

**Comment by mykola-mokhnach** [comment]
Is the target element present in the page source if you print it?

**Comment by sumanguduru** [comment]
target element is not present in the page source.
when i say driver.getPagesource(); its printing the page source of App.

**Comment by mykola-mokhnach** [comment]
If the web view is inherited from SafariWebView component then this is by design. Such web views are not supported by Appium.
