### ISSUE TITLE
Appium execution in one device get struck when executing in two device in parallel

### ISSUE THREAD

**Issue by githubdilip** [appium/appium#11217]
## The problem

I am testing android parallel execution using emulator with testing & java. I have started appium server in different ports and able to start the two instance of driver. But once the driver is created the app get launched in two device, after that execution is continues in one device only and the other device is idle. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:v8.11.3
* Real device or emulator/simulator:simulator
* Appium CLI or Appium.app|exe:

## Details
Session 1: appium --address 0.0.0.0 --nodeconfig nodeConfig.json -p 4723 -bp 100   --default-capabilities "{\"udid\":\"emulator-5556\",\"systemPort\":8200}"
Session 2: appium --address 127.0.0.1 --nodeconfig nodeConfig2.json -p 4725 -bp 200  --default-capabilities "{\"udid\":\"emulator-5554\",\"systemPort\":8202}"

One Session which get struck with below details and the other one work well continue to find elements

[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"d73d5741-d196-410e-9b91-d633b16b3846\",\"status\":0,\"value\":2.625}"
[debug] [JSONWP Proxy] Proxying [GET /appium/device/system_bars] to [GET http://localhost:8202/wd/hub/session/d73d5741-d196-410e-9b91-d633b16b3846/appium/device/system_bars] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"d73d5741-d196-410e-9b91-d633b16b3846\",\"status\":0,\"value\":{\"statusBar\":63}}"
[debug] [JSONWP Proxy] Proxying [GET /window/current/size] to [GET http://localhost:8202/wd/hub/session/d73d5741-d196-410e-9b91-d633b16b3846/window/current/size] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"d73d5741-d196-410e-9b91-d633b16b3846\",\"status\":0,\"value\":{\"height\":1794,\"width\":1080}}"
[Appium] New AndroidUiautomator2Driver session created successfully, session 7f357b21-7db9-454f-be34-f0ee72705bc8 added to master session list
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1534826982886 (10:19:42 GMT+0530 (India Standard Time))
[debug] [MJSONWP] Responding to client with driver.createSession() result: {"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"udid":"emulator-5554","systemPort":8202,"appActivity":"com.xx.xxx.android.account.Activity","appPackage":"com.xx.xx.android","automationName":"uiAutomator2","deviceName":"emulator-5554","newCommandTimeout":120000,"noReset":true,"platformName":"ANDROID","platformVersion":"7.1.1","version":"7.1.1"},"udid":"emulator-5554","systemPort":8202,"appActivity":"com.xx.xxx.android.account.Activity","appPackage":"com.xx.xx.android","automationName":"uiAutomator2","deviceName":"emulator-5554","newCommandTimeout":120000,"noReset":true,"platformName":"ANDROID","platformVersion":"7.1.1","version":"7.1.1","deviceUDID":"emulator-5554","deviceScreenSize":"1080x1920","deviceScreenDensity":420,"deviceModel":"Android SDK built for x86","deviceManufacturer":"Google","deviceApiLevel":25,...
[HTTP] <-- POST /wd/hub/session 200 12376 ms - 1193
[HTTP]

**Comment by saikrishna321** [comment]
@githubdilip pls refer this https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/parallel-tests.md

I'm able to run parallel test using the latest appium server and client. You need to check your client and make sure drivers are thread safe.

**Comment by mykola-mokhnach** [comment]
Closed as client side issue.

**Comment by Anand093** [comment]
This happens when we launch both driver in parallel & at a same time.
Solution of above problem is -> provide a static wait of 2 sec before launching another instance of driver which is in parallel.

This will execute tests on both the devices with a difference of 2 secs.
