### ISSUE TITLE
An unknown server-side error occurred while processing the command. Original error: unknown error: cannot reserve port for Chrome from unknown error: unable to find open port (

### ISSUE THREAD

**Issue by hujiachun** [appium/appium#11211]
## The problem

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: unknown error: cannot reserve port for Chrome from unknown error: unable to find open port (Driver info: chromedriver=2.28.455517 (2c6d2707d8ea850c862f04ac066724273981e88f),platform=Mac OS X 10.13.2 x86_64) (WARNING: The server did not provide any stacktrace information) Command duration or timeout: 1.58 seconds Build info: version: 'unknown', revision: 'unknown', time: 'unknown' System info: host: 'C02SD9EYFVH5', ip: 'fe80:0:0:0:83b:183a:8861:b3c9%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.2', java.version: '1.8.0_65' Driver info: io.appium.java_client.android.AndroidDriver Capabilities [{appPackage=com.pingan.lifeinsurance.browser, noReset=true, deviceName=3391b609, nativeWebTap=true, platform=LINUX, deviceUDID=3391b609, desired={app=/Users/test-server/Documents/apache-tomcat-7.0.82/webapps/apps/8675ff9192ed0104ae6c3f7d6589eef8.apk, appPackage=com.pingan.lifeinsurance.browser, recreateChromeDriverSessions=true, noReset=true, noSign=true, deviceName=3391b609, nativeWebTap=true, appActivity=.MainActivity, newCommandTimeout=120.0, autoGrantPermissions=true, unicodeKeyboard=true, platformName=Android, udid=3391b609, resetKeyboard=true}, newCommandTimeout=120.0, platformVersion=5.0, webStorageEnabled=false, takesScreenshot=true, javascriptEnabled=true, unicodeKeyboard=true, platformName=Android, udid=3391b609, deviceManufacturer=samsung, resetKeyboard=true, app=/Users/test-server/Documents/apache-tomcat-7.0.82/webapps/apps/8675ff9192ed0104ae6c3f7d6589eef8.apk, deviceScreenSize=1080x1920, networkConnectionEnabled=true, recreateChromeDriverSessions=true, noSign=true, warnings={}, databaseEnabled=false, appActivity=.MainActivity, locationContextEnabled=false, autoGrantPermissions=true, deviceModel=SM-N9008S}] Session ID: 74fd7008-195d-426d-9f4d-2468b8f6da7f

## Environment

osx 10.13.2
Appium Desktop 1.0.0
chromedriver 2.28

## Details

Where Multiple devices concurrent chromedriver，After a period of execution，

## Link to Appium logs

No devices found

**Comment by mykola-mokhnach** [comment]
Do you follow https://github.com/appium/appium/blob/55760b7b9e1c494c6a1f22d152f0bd1fe676dae7/docs/en/advanced-concepts/parallel-tests.md?

Also the full server log is necessary.
