### ISSUE TITLE
Getting error "It is impossible to create a new session because 'createSession' which takes HttpClient, InputStream and long was not found or it is not accessible" while running tests over VPN.

### ISSUE THREAD

**Issue by SinghDurga** [appium/appium#11210]
Hello Team,

I am seeking help for below issue. 

## The problem

Whenever I am running my tests over VPN getting error - It is impossible to create a new session because 'createSession' which takes HttpClient, InputStream and long was not found or it is not accessible.

## Environment

- Appium Server: 1.8.2 Beta
- Mac OS: 10.13.6 (17G65)
- Platforms-Android(Api 28) and iOS(Os 11.4)(Both Emulators)
- Browsers under test: Chrome and Safari for Android and iOS respectively
- Java client: 1.6.1

## Details
This has been happening constantly from past one week now. Earlier I used to restart system and problem used to get resolve but now constantly getting error as mentioned above. 

Please note that website under test is launching perfectly fine manually with VPN connected. Its just that with VPN connected, Appium tests are not getting triggered. 

I have tried following different threads before posting here. 
Have switched to and fro to different Java client versions but with no success.

Am I missing any trick here ? Any help is appreciated.

Thanks in advance.

Appium logs

Eclipse console shows below logs:

Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'WKMIN7737414', ip: '2401:4900:2767:e3eb:154e:1058:1397:7848%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '1.8.0_181'
Driver info: driver.version: IOSDriver
Caused by: org.openqa.selenium.WebDriverException: 
It is impossible to create a new session because 'createSession' which takes HttpClient, InputStream and long was not found or it is not accessible
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'WKMIN7737414', ip: '2401:4900:2767:e3eb:154e:1058:1397:7848%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '1.8.0_181'
Driver info: driver.version: IOSDriver
Caused by: java.lang.reflect.InvocationTargetException
Caused by: java.net.ConnectException: Failed to connect to /0.0.0.0:4723
Caused by: java.net.ConnectException: Operation timed out (Connection timed out)
 

Appium terminal does not print anything other than server running status as the connection is not getting established.

[Appium] Welcome to Appium v1.8.2-beta
[Appium] Appium REST http interface listener started on 0.0.0.0:4723

**Comment by mykola-mokhnach** [comment]
> Caused by: java.net.ConnectException: Failed to connect to /0.0.0.0:4723

This means that java client cannot connect to the server because it does not listen on the given host/port. Make sure the server is listening there first, for example with `netstat` tool.

**Comment by SinghDurga** [comment]
@mykola-mokhnach 
Thank you so much for prompt reply:
when I run command sudo lsof -PiTCP -sTCP:LISTEN

I get below results. Which is showing that port 4723 is listening. Any suggestions which port I can use ?? 
COMMAND    PID      USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
launchd      1      root    8u  IPv6 0xe05e75703486c91d      0t0  TCP *:22 (LISTEN)
launchd      1      root    9u  IPv4 0xe05e7570348715c5      0t0  TCP *:22 (LISTEN)
launchd      1      root   13u  IPv4 0xe05e7570348715c5      0t0  TCP *:22 (LISTEN)
launchd      1      root   16u  IPv6 0xe05e75703486c91d      0t0  TCP *:22 (LISTEN)
cirratod    52      root    7u  IPv4 0xe05e757034872885      0t0  TCP localhost:8089 (LISTEN)
cirratod    52      root    8u  IPv6 0xe05e75703486b7dd      0t0  TCP localhost:8089 (LISTEN)
cirratod    52      root    9u  IPv4 0xe05e7570348731e5      0t0  TCP localhost:8090 (LISTEN)
cirratod    52      root   10u  IPv6 0xe05e75703486d49d      0t0  TCP localhost:8090 (LISTEN)
cirratod    52      root   12u  IPv4 0xe05e757034873b45      0t0  TCP *:5001 (LISTEN)
TracSrvWr  100      root   11u  IPv4 0xe05e757037bae885      0t0  TCP localhost:7778 (LISTEN)
xartstora  204      root    3u  IPv4 0xe05e757034871f25      0t0  TCP *:61500 (LISTEN)
xartstora  204      root    4u  IPv6 0xe05e75703486bd9d      0t0  TCP *:61500 (LISTEN)
studio     528 dursingh1  207u  IPv4 0xe05e75703f108b45      0t0  TCP localhost:6942 (LISTEN)
studio     528 dursingh1  431u  IPv4 0xe05e75703f5cff25      0t0  TCP localhost:63342 (LISTEN)
rapportd   545 dursingh1    3u  IPv4 0xe05e7570462f4f25      0t0  TCP *:51426 (LISTEN)
rapportd   545 dursingh1    4u  IPv6 0xe05e75703bcc3a5d      0t0  TCP *:51426 (LISTEN)
PanGPS    1175      root    5u  IPv4 0xe05e757042dbff25      0t0  TCP localhost:4767 (LISTEN)
_node      1433 dursingh1   13u  IPv4 0xe05e75703f1081e5      0t0  TCP *:4723 (LISTEN)_
java      1449 dursingh1  192u  IPv6 0xe05e75703bcc235d      0t0  TCP *:49208 (LISTEN)
qemu-syst 1454 dursingh1   38u  IPv4 0xe05e757045ffbf25      0t0  TCP localhost:5555 (LISTEN)
qemu-syst 1454 dursingh1   39u  IPv6 0xe05e75703bcc17dd      0t0  TCP localhost:5555 (LISTEN)
qemu-syst 1454 dursingh1   40u  IPv4 0xe05e757045ffc885      0t0  TCP localhost:5554 (LISTEN)
adb       1469 dursingh1    8u  IPv4 0xe05e7570462be1e5      0t0  TCP localhost:5037 (LISTEN)
cupsd     1740      root    5u  IPv6 0xe05e75703486e5dd      0t0  TCP localhost:631 (LISTEN)
cupsd     1740      root    6u  IPv4 0xe05e757046c315c5      0t0  TCP localhost:631 (LISTEN)

**Comment by SinghDurga** [comment]
command netstat -ap tcp | grep -i "listen" results in :

tcp6       0      0  *.51426                *.*                    LISTEN     
tcp4       0      0  *.51426                *.*                    LISTEN     
tcp4       0      0  localhost.ipp          *.*                    LISTEN     
tcp6       0      0  localhost.ipp          *.*                    LISTEN     
tcp4       0      0  localhost.5037         *.*                    LISTEN     
tcp4       0      0  localhost.sgi-esphttp  *.*                    LISTEN     
tcp6       0      0  localhost.personal-age *.*                    LISTEN     
tcp4       0      0  localhost.personal-age *.*                    LISTEN     
tcp46      0      0  *.49208                *.*                    LISTEN     
tcp4       0      0  *.4723                 *.*                    LISTEN     
tcp4       0      0  localhost.63342        *.*                    LISTEN     
tcp4       0      0  localhost.4767         *.*                    LISTEN     
tcp4       0      0  localhost.6942         *.*                    LISTEN     
tcp4       0      0  localhost.interwise    *.*                    LISTEN     
tcp4       0      0  *.commplex-link        *.*                    LISTEN     
tcp6       0      0  localhost.8090         *.*                    LISTEN     
tcp4       0      0  localhost.8090         *.*                    LISTEN     
tcp6       0      0  localhost.8089         *.*                    LISTEN     
tcp4       0      0  localhost.8089         *.*                    LISTEN     
tcp6       0      0  *.61500                *.*                    LISTEN     
tcp4       0      0  *.61500                *.*                    LISTEN     
tcp4       0      0  *.ssh                  *.*                    LISTEN     
tcp6       0      0  *.ssh                  *.*                    LISTEN

**Comment by mykola-mokhnach** [comment]
try to start the server on `localhost` instead of 0.0.0.0.
Also make sure the server is already in running state when the client is starting

**Comment by SinghDurga** [comment]
Thanks @mykola-mokhnach !!! Thanks for valuable guidance. I changed the port from 0.0.0.0:4723 to 127.0.0.1:4723. And it works fine now.

**Comment by tatarynov** [comment]
I faced this problem for Android automation project as well. 
Found solution. Deleting 'io.appium.uiautomator2.server' and 'io.appium.uiautomator2.server.test' packages before tests has helped.
These two packages will be reinstalled automatically during creating a session.

**Comment by VinceBarresi** [comment]
I'm also seeing this issue consistently. 
**My environment**
Appium 1.9
OSX 10.14
iOS 11.2 Simulator in Xcode 9.2
Java client 6.1
Hub is 127.0.0.1:4444 and node is 127.0.0.1:4723 and are up and running fine

**Comment by kousikbhukta** [comment]
Hi All,

I am getting the same error. Please help me to resolve this issue.
Appium 1.9.1

I have tried changing port number as well. But same error is occurred still.
Please suggest how to resolve this.

**Comment by drawat71** [comment]
hey ,any solution for this ?

**Comment by steveyoungqa** [comment]
I am also getting the same issue on Appium 1.9, OSX 10.14.1, Java Client 6.1

**Comment by Eyesonly88** [comment]
We used `localhost` for the appium server instead of an IP address and it worked.

**Comment by tomkeiev** [comment]
Is there a solution?

**Comment by vinodbhardwaj1** [comment]
Working fine for 'UiAutomator2' But facing same issue if trying with 'Espresso'.  
 cap.setCapability(MobileCapabilityType.AUTOMATION_NAME, "Espresso");
Java-client - 6.1.0

**Comment by mikalaikarol** [comment]
I face the same issue - any solutions/suggestions?

**Comment by Yathin-C** [comment]
Guys I too faced the Same Problem even after changed 0.0.0.0:4723 to 127.0.0.1:4723 and localhost:4723 Still faced the same Issue

Actually there are 2 ways to start Appium
1. Thru Desktop App and Starting the server manually
2. Thru Terminal(mac) or command prompt(windows)

Try to Start Appium Server by entering "Ythns-iMac:~ Yathin$ **appium**" in the Terminal
It works for me....

**Comment by tahirakhlaaq** [comment]
Its not Working On Windows

**Comment by UjjwalS123** [comment]
try to start the server on localhost instead of 0.0.0.0.
It will work.

**Comment by Revathi2910** [comment]
I updated my carthage command  - brew upgrade carthage and updated my appium to recent (1.16.0) -> issue got resolved for me
