### ISSUE TITLE
Server side exception after upgrade in xcuitest

### ISSUE THREAD

**Issue by kamaroyl** [appium/appium#11216]
## The problem

When trying to run an ios test on a remote ios device I'm running into a server side exception

## Environment
macbook air runnin g
ProductName:	Mac OS X
ProductVersion:	10.13.6
appium 1.8 
* Last Appium version that did not exhibit the issue 1.8@beta
* Node.js version v10.9.0
* Real device 11.4
*package.json from the system:
https://gist.github.com/kamaroyl/271a6a595b261bb7e7dcfe551d71cd1a

## Details

After an update the server fails before start. Appium is running as a launch agent as root; ran       
     path.resolve(process.env.HOME, 'Library', 'Logs', 'CrashReporter', 'MobileDevice') :
      path.resolve(process.env.HOME, 'Library', 'Logs', 'DiagnosticReports'));
as root to make sure they resolved correctly and they did. This system was updated as an experiment, we have several others that are running 1.8.2-beta that are still running in the same conditions. 

## Link to Appium logs

https://gist.github.com/kamaroyl/57f190c8ef73fe4b154c9ef265bd189b

## Code To Reproduce Issue [ Good To Have ]

Can't give you the code, but it failed before launching the test, so the equivalent of

**Comment by mykola-mokhnach** [comment]
The script there is trying to retrieve the value of HOME env variable and fails to do it as the variable does not exist. It is not recommended to run Appium as root. Also you have to make sure the process has correct environment in general. Check https://github.com/appium/java-client/blob/master/docs/environment.md for more details.

**Comment by kamaroyl** [comment]
Thanks! That was it; ended up creating a privileged user and just running appium as a service under that. Do you all have any setup examples for a service and if not is that something that could be contributed?

**Comment by mykola-mokhnach** [comment]
If you are talking about the documentation then no, we don't have any particular setup examples for services setup. You could add one if you want.
