### ISSUE TITLE
Setting unicodeKeyboard true make keycode  not work

### ISSUE THREAD

**Issue by reflyhight** [appium/appium#11220]
use unicodeKeyboard  for chinese input ,I set unicodeKeyboard true,  the method press_keycode does not work.this problem confused a long time. I use python

```
"unicodeKeyboard": True,
"resetKeyboard": True,
```
```
driver.press_keycode(66)    # does not work.
```

**Comment by mykola-mokhnach** [comment]
Please provide the necessary issue information and full server log

**Comment by reflyhight** [comment]
@mykola-mokhnach   just does not work, no other logs

**Comment by mykola-mokhnach** [comment]
no logs - no solution

**Comment by reflyhight** [comment]
{
"appPackage": "com.tencent.mm",
"platformName": "android",
"deviceName": "virgo",
"appActivity": ".ui.LauncherUI",
"unicodeKeyboard": true,
"resetKeyboard": false ,
"noReset":true
}

**Comment by reflyhight** [comment]
[HTTP] --> POST /wd/hub/session/ed226291-028f-4a34-8745-2290ef2bd2ed/appium/element/4/replace_value
[HTTP] {"id":"4","sessionId":"ed226291-028f-4a34-8745-2290ef2bd2ed","value":["鹿晗"]}
[W3C] Calling AppiumDriver.replaceValue() with args: [["鹿晗"],"4","ed226291-028f-4a34-8745-2290ef2bd2ed"]
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:setText","params":{"elementId":"4","text":"鹿晗","replace":true,"unicodeKeyboard":true}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:setText","params":{"elementId":"4","text":"鹿晗","replace":true,"unicodeKeyboard":true}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: setText
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using element passed in: 4
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Attempting to clear using UiObject.clearText().
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Sending Unicode text to element: 鹿晗
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Encoded text: &nn9mVw-
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":true}
[AndroidBootstrap] Received command result from bootstrap
[W3C] Responding to client with driver.replaceValue() result: true
[HTTP] <-- POST /wd/hub/session/ed226291-028f-4a34-8745-2290ef2bd2ed/appium/element/4/replace_value 200 4636 ms - 14
[HTTP] 
[HTTP] --> POST /wd/hub/session/ed226291-028f-4a34-8745-2290ef2bd2ed/appium/device/press_keycode
[HTTP] {"keycode":66,"sessionId":"ed226291-028f-4a34-8745-2290ef2bd2ed"}
[W3C] Calling AppiumDriver.pressKeyCode() with args: [66,null,null,"ed226291-028f-4a34-8745-2290ef2bd2ed",null,"ed226291-028f-4a34-8745-2290ef2bd2ed"]
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"pressKeyCode","params":{"keycode":66,"metastate":null}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"pressKeyCode","params":{"keycode":66,"metastate":null}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: pressKeyCode
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":true}
[AndroidBootstrap] Received command result from bootstrap
[W3C] Responding to client with driver.pressKeyCode() result: true
[HTTP] <-- POST /wd/hub/session/ed226291-028f-4a34-8745-2290ef2bd2ed/appium/device/press_keycode 200 1026 ms - 14
[HTTP]
