### ISSUE TITLE
[appium] Failed to create WDA session

### ISSUE THREAD

**Issue by mickmick35** [appium/appium#11227]
## The problem

Hello, 

I have the following problem « **XCUITest] Failed to create WDA session** » if my Mac mini is on corporate network.

If the mac mini is not connected to the corporate network, the problem isn't present. 

In my network configuration, the proxy isn't use for : 
*.local, 169.252/16, 127.0.0.1, localhost 

So, i don"t understand this behaviour on the corporate network ? 

Moreover, if I try in chrome http://localhost:8100/status, i receive 

{ 
"value" : { 
"state" : "success", 
"os" : { 
"name" : "iOS", 
"version" : "11.4.1", 
"sdkVersion" : "11.3" 
}, 
"ios" : { 
"simulatorVersion" : "11.4.1", 
"ip" : "169.254.246.64" 
}, 
"build" : { 
"time" : "Aug 17 2018 17:46:36" 
} 
}, 
"sessionId" : "57ADAE69-C308-4801-928A-DC54EA8F1EDC", 
"status" : 0 
} 

Thanks in advance 

## Environment
* MacOS 10.13.5 
* Appium 1.8.1 
* Xcode 9.4.1 
* Node.js 10.4.1
* IOS 11
* Real device
* Appium CLI

## Link to Appium logs
https://gist.github.com/mickmick35/08658ad115d64da8a391b949552c56ec

**Comment by mykola-mokhnach** [comment]
> [debug] [XCUITest] Unable to connect to running WebDriverAgent: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: getaddrinfo ENOTFOUND ad-subs ad-subs:80 

The problem for sure has nothing to do with Appium itself. We use `iproxy` tool to forward TCP traffic from the device to the host machine (the default port is 8100). Most likely there is a clash between your local network policies and the forwarding. There's nothing we can do there.

**Comment by mickmick35** [comment]
Maybe you have some idea to resolve this ? 

Thanks

**Comment by mykola-mokhnach** [comment]
No idea. You system administrator should know it
