### ISSUE TITLE
io.appium.java_client.ios.IOSDriver cannot be cast to io.appium.java_client.MobileElement

### ISSUE THREAD

**Issue by siddhantraut** [appium/appium#11221]
## The problem
java.lang.ClassCastException: io.appium.java_client.ios.IOSDriver cannot be cast to io.appium.java_client.MobileElement

## Environment
 
 * Desktop OS/version used to run Appium: 1.6.1
* Mobile platform/version under test:iOS 11.4.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: App

## Link to Appium logs

 
[appium-server-logs.txt](https://github.com/appium/appium/files/2306065/appium-server-logs.txt)

## Code To Reproduce Issue [ Good To Have ]

public static void logout()  {
//		driver.navigate().back();
 
		MobileElement el2 = ((MobileElement) driver).findElementByAccessibilityId("Log out");
		el2.click();
	 
		MobileElement el3 = ((MobileElement) driver).findElementByXPath("//XCUIElementTypeButton[@name=\"Log out\"]");
		el3.click();
	}

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/appium/java-client/issues

**Comment by siddhantraut** [comment]
done https://github.com/appium/java-client/issues/1004
