### ISSUE TITLE
Appium/WinAppDriver: Could not proxy command to remote server.Error: connect ECONNREFUSED 127.0.0.1:4724'

### ISSUE THREAD

**Issue by hinakanthed** [appium/appium#11223]
**## The problem**
Launching the app (WPF Application) for first user in the Excel sheet runs without error but when it completes the loop and tries to run for the next it throws error  Could not proxy command to remote server.Error: connect ECONNREFUSED 127.0.0.1:4724'. The tests run smoothly with the same code previously but now suddenly this error is blocking my automation.

**## Environment**
Appium: v1.8.1
Windows 10
WinAppDriver v1.0
Selenium webdriver v3.11.2 Works only with this

## Link to Appium logs
Attached Image
![appium](https://user-images.githubusercontent.com/42252622/44415758-6ff1db00-a52e-11e8-9def-7e0be3d41f86.PNG)

I have tried Implicitwait, Sleep but none works.

**Comment by dpgraham** [comment]
@yodurr this is probably related to the problems we had before, right?

**Comment by hinakanthed** [comment]
@dpgraham Let me know what information you need?

**Comment by hinakanthed** [comment]
@mykola-mokhnach Yes, It is failing when I am switching to another window handle. But I have a excel sheet with different user information. And the test is set to run for the whole range within the sheet. It did run fine but suddenly I am now getting this error.  Even now the first user logs in fine but when the session ends and gets into the loop for the second one it is failing every time at the same point with the same error.

**Comment by mykola-mokhnach** [comment]
Perhaps there is a race condition somehwere in your code

**Comment by hinakanthed** [comment]
@mykola-mokhnach How do I check for that. My knowledge on that is very minimal.  And If not a race condition what else can throw that error?

**Comment by mykola-mokhnach** [comment]
I would hire a consultant, who could figure out how the client code works.

**Comment by hinakanthed** [comment]
The issue got resolved on its own when I ran the tests today morning.
