### ISSUE TITLE
Appium hangs when call getPageSource in one of the device language change settings screen - iOS

### ISSUE THREAD

**Issue by goel-shobit** [appium/appium#11231]
## The problem
Issue is Appium hangs when I call getPageSource in one of device language settings screen. Below is the screen where Appium hangs to give page source. The screen can be viewed via General/Language & Region/Other Languages 
![img_0874](https://user-images.githubusercontent.com/14111252/44458151-ed971300-a622-11e8-9dee-ed5ca17713fd.png)

## Environment

* Appium version (or git revision) that exhibits the issue:1.8.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:Mac 10.13.1
* Node.js version (unless using Appium.app|exe):10.4.1
* Mobile platform/version under test: iOS 11.2.1
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe:CLI

## Details
I waited for 30 seconds to get page source but none response was received.

## Link to Appium logs
https://gist.github.com/goel-shobit/3aa0046dfabe01c89dcc9e81f2000734

## Code To Reproduce Issue [ Good To Have ]
iosDriver = new IOSDriver<IOSElement>(new URL(driverCapabilities.serverUrl), capabilities);
iosDriver.manage().timeouts().implicitlyWait(1, TimeUnit.SECONDS);
iosDriver.getPageSource();

**Comment by mykola-mokhnach** [comment]
Try appium@beta. Also the device log is needed

**Comment by goel-shobit** [comment]
Tried but no success. Here are the logs [](https://gist.github.com/goel-shobit/f4d351bb41eeda67609b6d109ea37e65)

**Comment by mykola-mokhnach** [comment]
Unfortunately this log does not contain the detailed info. Try to set the `showIOSLog` capability to `true` and then get the generated server log

**Comment by mykola-mokhnach** [comment]
It looks like this is a problem in WebDriverAgent itself. Please report it to https://github.com/facebook/WebDriverAgent
