### ISSUE TITLE
If Element is only visible with 1px in an iOS App, it is not possible to check if it is fully visible or just partially

### ISSUE THREAD

**Issue by Seijan** [appium/appium#11238]
## The problem

I have an iOS app that has a lot of input fields on a single page. I want to automate those inputs and i know how to scroll to those elements and everything, but I have a problem with partially displayed elements.

There are two cases in which partially displayed elements cause a problem:
The first case is caused when another element is overlapping with the element in the background. If I click on the element in the background, than Appium clicks on the overlapping element. This causes the wrong interaction and therefor the test crashes. The function isDisplayed() is not usable as the result is true for partially displayed elements, even if just one or two lines of pixels are visible.

The second case is happening when I type something into an element with sendKeys(). This opens the keyboard on iOS and when I want to click on the next element, it is possible that the keyboard is exactly over the element, except for some space that is still visible from the element, so that isDisplayed() returns true for the element. I know there is the option of hideKeyboard(), but this isn't always possible, as the keyboard displayed must have the hide key as a key visible.

One solution for me is that I don't click on the next element, but on the one below it, but this is ugly as hell, and there should be a nicer solution.

I'm not quite sure if it is an issue or it's a feature that has to be implemented. This isn't a problem in Android as an element has a certain height that can be calculated and you can scroll until the element is fully visible.

## Environment

* Appium version: 
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: 1.6.3
* Node.js version (unless using Appium.app|exe): 
* Mobile platform/version under test: iOS 11.4
* Real device or emulator/simulator: emulator and real device
* Appium CLI or Appium.app|exe: appium.app

**Comment by mykola-mokhnach** [comment]
We feel your appin, but it is not possible to fix anything on our side. We do retrieve visibility attribute directly from XCTest. Also XCTest does not provide any functionality to hide the keyboard (actually, there is such method, but it ha no effect %) )

**Comment by Seijan** [comment]
Can a bug/feature request be entered to XCTest? Or is this a dead end, that is not possible to fix?

**Comment by mykola-mokhnach** [comment]
There is Apple Radar bugtracker for this purpose. But the harsh reality confirms they care about such issues very little.
