### ISSUE TITLE
Appium Server Failing For Android starting with Version 1.8.0

### ISSUE THREAD

**Issue by Warren25** [appium/appium#11234]
## The problem

When I'm trying to run my regression suite, appium server version 1.7.2 works successfully. Starting with version 1.8.0 (and I have tested 1.8.1 and 1.8.2-beta), Appium fails to launch, due to what I believe is the 'startServer' method, according to the logs.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0, 1.8.1, 1.8.2-beta
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2
* Desktop OS/version used to run Appium: macOS High Sierra version 10.13.6
* Node.js version (unless using Appium.app|exe): v8.11.1
* Mobile platform/version under test: Android, 8.1.0, Nexus 6P
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Both

## Details

It could possibly have something to do with my serenity dependencies

**Pom File:**

    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <serenity.version>1.9.36</serenity.version>
    <serenity-cucumber.version>1.9.14</serenity-cucumber.version>
    <surefire.version>2.20.1</surefire.version>
    <compiler.version>3.5</compiler.version>
    <slf4j.version>1.6.1</slf4j.version>
    <assertj.version>3.6.2</assertj.version>

  <build>

    <plugins>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${compiler.version}</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>

      <plugin>
        <artifactId>maven-failsafe-plugin</artifactId>
        <version>${surefire.version}</version>
        <dependencies>
          <dependency>
            <groupId>org.apache.maven.surefire</groupId>
            <artifactId>surefire-junit4</artifactId>
            <version>${surefire.version}</version>
          </dependency>
        </dependencies>
        <configuration>
          <argLine>-Xmx2048m</argLine>
          <includes>
            <include>**/*Runner.java</include>
          </includes>
          <forkCount>1</forkCount>
          <reuseForks>false</reuseForks>
          <testFailureIgnore>true</testFailureIgnore>
        </configuration>
        <executions>
          <execution>
            <id>cucumber-tests</id>
            <phase>integration-test</phase>
            <goals>
              <goal>integration-test</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>net.serenity-bdd.maven.plugins</groupId>
        <artifactId>serenity-maven-plugin</artifactId>
        <version>${serenity.version}</version>
        <dependencies>
          <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
          </dependency>
        </dependencies>
        <executions>
          <execution>
            <id>serenity-reports</id>
            <phase>post-integration-test</phase>
            <goals>
              <goal>aggregate</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

    </plugins>

  </build>

  <dependencies>

    <dependency>
      <groupId>net.serenity-bdd</groupId>
      <artifactId>serenity-core</artifactId>
      <version>${serenity.version}</version>
    </dependency>

    <dependency>
      <groupId>net.serenity-bdd</groupId>
      <artifactId>serenity-cucumber</artifactId>
      <version>${serenity-cucumber.version}</version>
    </dependency>

    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-simple</artifactId>
      <version>${slf4j.version}</version>
    </dependency>

    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
      <version>${assertj.version}</version>
    </dependency>

    <dependency>
      <groupId>org.apache.maven.surefire</groupId>
      <artifactId>surefire-junit4</artifactId>
      <version>${surefire.version}</version>
    </dependency>

  </dependencies>

</project>

**Serenity Properties File:** (project name and app name are censored due to sensitivity)

serenity.project.name = [******************************************]
webdriver.driver = appium
serenity.take.screenshots = AFTER_EACH_STEP
serenity.test.root = src/test/resources/features
webdriver.timeouts.implicitlywait = 3000

###Appium Config###
appium.platformName = Android
#appium.deviceName = Nexus 6P
appium.deviceName = SM-G95OU

appium.newCommandTimeout = 300

###Specify Apk !!!THIS MAY NEED TO BE AN ABSOLUTE PATH!!!###
appium.app = [******************************************]

###Fresh Install or open if exists###
appium.noReset = true

###Appium use UI2
appium.automationName = uiautomator2

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

https://gist.github.com/Warren25/acac5a0605c6b9b0a3de97709bc52411

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Try to reset the device under test

**Comment by Warren25** [comment]
@mykola-mokhnach Thank you for quick response. I am confused what you mean by "under test". Could you clarify please?

**Comment by mykola-mokhnach** [comment]
I mean the device where the automated testing is done.

**Comment by Warren25** [comment]
I reset the device, turned it off and back on. I am still seeing this error when testing with latest beta, and have been seeing it since 1.8.0:

Time: 0.015
[debug] [UiAutomator2] [UIAutomator2] There was 1 failure:
[debug] [UiAutomator2] [UIAutomator2] 1) startServer(io.appium.uiautomator2.server.test.AppiumUiAutomator2Server)
[debug] [UiAutomator2] [UIAutomator2] java.lang.NoSuchMethodError: No static method getInstance(Landroid/content/Context;I)Lio/appium/uiautomator2/server/ServerInstrumentation; in class Lio/appium/uiautomator2/server/ServerInstrumentation; or its super classes (declaration of 'io.appium.uiautomator2.server.ServerInstrumentation' appears in /data/app/io.appium.uiautomator2.server-k1dkISOckySO6SS6k9M2Fg==/base.apk)

**Comment by mykola-mokhnach** [comment]
Strange... Check https://github.com/appium/appium/issues/10909

**Comment by Warren25** [comment]
@mykola-mokhnach Thank you for the reference. Following the steps they noted, first I tried just deleting io.appium.uiatutomator2.server, then running appium 1.8.0, that didn't work. Then I tried deleting both io.appium.uiatutomator2.server and io.appium.uiatutomator2.server.test, then running appium 1.8.0, and that didn't work. 

Finally, I deleted both io.appium.uiatutomator2.server and io.appium.uiatutomator2.server.test, also deleted Appium Settings app, uninstalled Appium, restarted my test device, installed appium 1.8.1, and then it worked. Maybe all those steps were not necessary, but at least doing all that in that order worked for me. 

Confirmed appium versions 1.8.0, 1.8.1, 1.9.0-beta working successfully

**Comment by thepoppingone** [comment]
> io.appium.uiatutomator2.server

How did you delete both `io.appium.uiatutomator2.server` and `io.appium.uiatutomator2.server.test`?

Can't seem to find it, I tried removing appium initially but the error came back after some time.

**Comment by Warren25** [comment]
@thepoppingone For Android OS, it should be navigate to 'Settings', then navigate to 'Apps'

**Comment by NotTooReact89** [comment]
@Warren25 how can i delete io.appium.uiatutomator2.server and io.appium.uiatutomator2.server.test ? I was able to uninstall Appium settings from the emulator.  I am using macOS and running appium desktop.

**Comment by Warren25** [comment]
@NotTooReact89 You have to navigate to 'Apps' in your settings, and you should be able to locate them. The image below is from a physical device, but I assume it should be the same for an emulator as well.

![image](https://user-images.githubusercontent.com/17141304/48560792-a7b5b800-e8bc-11e8-8c2b-79cebd053231.png)
