### ISSUE TITLE
How to install mobile application(Android/iOS) in emulators directly by accessing path from different network location using appium ?

### ISSUE THREAD

**Issue by GowriSethu** [appium/appium#11236]
Hi,

I'm launching my android & ios emulators in windows & mac machine respectively, 

My application is generated by CI system in a network location (path: \\xxx.yyy.com\<folder_Name>\Mobile\android and \\xxx.yyy.com\<folder_Name>\Mobile\ios)

If try to install the mobile app in emulators by directly accessing the path(path:\\xxx.yyy.com\<folder_Name>\Mobile\android), getting below error. How to handle this situation?

Error in console :

Exception encountered in getDriver Method: An unknown server-side error occurred while processing the command. Original error: Error: UNKNOWN: unknown error, lstat '\\xxx.yyy.com\<folder_Name>\Mobile\android\android_application.apk' (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 23.25 seconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'MOBILETESTTR01', ip: '10.7.0.86', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: io.appium.java_client.android.AndroidDriver 

Environment: 

Appium version that exhibits the issue: 1.8.0
Desktop OS/version used to run Appium: Windows 10
Real device or emulator/simulator:simulator
Selenium server: 2.53.1
java-client: 4.0.0

is there any way to install the mobile app by directly accessing the path using appium ? Please suggest .

Thanks in Advance!

**Comment by mykola-mokhnach** [comment]
Appium supports application installs from:
- http(s) links
- windows shares (links starting with `\\`)
- local paths

Everything else is not supported.
Please use Appium forum to ask questions

**Comment by GowriSethu** [comment]
@mykola-mokhnach : when using the windows share files starting with ( \\ )also I'm facing same issue & same error is throwing
 Exception encountered in getDriver Method: An unknown server-side error occurred while processing the command. Original error: Error: UNKNOWN: unknown error, lstat '\xxx.yyy.com<folder_Name>\Mobile\android\android_application.apk' (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 23.25 seconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'MOBILETESTTR01', ip: '10.7.0.86', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: io.appium.java_client.android.AndroidDrive
