### ISSUE TITLE
Uable to Intreract with UI Elements with IOS12

### ISSUE THREAD

**Issue by Ashwini12345** [appium/appium#11237]
## The problem

NosuchElemeny Exeception for all the elements on UI

## Environment

* Appium version (or git revision) that exhibits the issue:1.9.0-beta1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:10.13.5
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:IOS12
* Real device or emulator/simulator:Simulator
* Appium CLI or Appium.app|exe: CLI

## Details

Able to Create Session and when app is getting launched i am unable to click or do any actions on UI
## Link to Appium logs

[appium-server-logs (1).txt](https://github.com/appium/appium/files/2314117/appium-server-logs.1.txt)

**Comment by mykola-mokhnach** [comment]
Is the element present in page source output?

**Comment by Ashwini12345** [comment]
Yes it is present, its working totally fine with Xcode 9.2 on Appium 1.7.1 but when i upgraded to xcode 10 its not working

**Comment by mykola-mokhnach** [comment]
Can you attach the actual output?

**Comment by Ashwini12345** [comment]
I am using Appium 1.9.0 beta so i am not able to launch appium inspector with this version. i am not sure how i can give u the actual output.

Or did u mean to give u the just the appium logs output?

**Comment by mykola-mokhnach** [comment]
I need the output of `getPageSource` method to check if the element you are trying to find is really present in the page source.

**Comment by Ashwini12345** [comment]
I got pagesource using Xcode 9..2, with the latest beta versions i was not not able to get any page source.

[PageSource.txt](https://github.com/appium/appium/files/2316992/PageSource.txt)

**Comment by mykola-mokhnach** [comment]
I don't see any element with "Manage Environments" identifier in this page source. In any case the actual page source and elements lookup is performed on webdriveragent side. So please report the issue to https://github.com/facebook/WebDriverAgent (if you think this is really a bug of the downstream driver).

**Comment by Ashwini12345** [comment]
Hi, If u see there is an element called "Debug Settings", even for this element i am not able do any actions on this element.
