### ISSUE TITLE
scrollIntoView returns elements outside the scrollview

### ISSUE THREAD

**Issue by oscheller1** [appium/appium#11247]
## The problem

Searching for an element via uiautomator, e.g. `new UiScrollable(new UiSelector().resourceId("id/container")).scrollIntoView(new UiSelector().text("My Text"))` returns elements that are outside the `id/container`-container. This is a problem when there are two texts `My Text`, one inside the container, one not.

I can reproduce the issue on a Samsung S8 **real device** running Android 8.0 with appium 1.9.0beta1 and appium 1.8.1. 
On a Pixel 2 XL **Simulator** running 8.0 though, the error does not occur, again appium 1.8.1. and 1.9.0beta1.

Might be a problem with 8.0 real devices?

Error occurs

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.0beta1, 1.8.1
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: mac os
* Node.js version (unless using Appium.app|exe): 6.4.0
* Mobile platform/version under test: android 8.0 
* Real device or emulator/simulator: samsung s8 real device
* Appium CLI or Appium.app|exe: cli

# Appium logs

https://gist.github.com/oscheller1/3404006cae3369de160b179c56628521 
This one shows that 2 elements are found and first one is returned: https://gist.github.com/oscheller1/11904bc3b74318f9b33ff4c1988dd04b

Somehow there's a simple query `getElements selector:UiSelector[TEXT=Validation]` without the outer scrollable element.

**Comment by mykola-mokhnach** [comment]
I think this might be a problem of the UIA framework.

**Comment by mykola-mokhnach** [comment]
Try to avoid using UiSelector locators, since these cannot be mapped to UiObject2 entities.

**Comment by oscheller1** [comment]
What would be the alternative to using UiSelector for Ui Automator 2? I see there's `BySelector` (https://developer.android.com/reference/android/support/test/uiautomator/BySelector), but couldn't find a way to use those with Appium.

**Comment by mykola-mokhnach** [comment]
In our case `xpath` works as `BySelector`, since elements there have the same set of attributes

**Comment by oscheller1** [comment]
So if I should avoid using UiSelectors, does that mean, the "find_element_by_android_uiautomator" (i.e. `AppiumDriver.findElements() with args: ["-android uiautomator" ...]` ) method is not fully supported by Ui Automator 2 anymore? In my understanding, that method relies on UiSelector queries.

**Comment by mykola-mokhnach** [comment]
It is there only for backward compatibility with UIA1 framework and I wouldn't use it with newer Android versions.

**Comment by oscheller1** [comment]
Thanks for the heads-up

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
