### ISSUE TITLE
iOS 12 + Appium 1.9.0 beta waitForQuiesence doesn't work 

### ISSUE THREAD

**Issue by jamesvanhorn** [appium/appium#11249]
## The problem

Turning off waitForQuiesence causes errors with launching the app under test. 

Leaving waitForQuiesence : true does work, but on certain machines we have (running iOS sim), the app never reports as idle. If you have any idea on a fix there, that would be great. My laptop running same app build/appium/xcode/node setup works with waitForQuiesence true, but on our automation machine (just another mac setup as a jenkins node), the app never reports itself as idle. Seems a separate, yet somewhat related issue. This inconsistency in waitForQuiesence has existed since at least appium 1.7 

```
14:21:23 [debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"bundleID","arguments":["-AppleLanguages","(en)","-NSLanguages","(en)","-AppleLocale","en_US"],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":5,"shouldUseSingletonTestManager":true}}
14:21:23 [Xcode]     t =     0.24s Open bundleID
14:21:23 [Xcode] 
14:21:23 [Xcode]     t =     0.24s     Launch bundleID
14:21:23 [Xcode] 
14:21:24 [Xcode]     t =     0.39s         Wait for accessibility to load
14:21:24 [Xcode] 
14:21:24 [Xcode]     t =     0.63s         Wait for bundleID to idle
14:21:24 [Xcode] 
14:22:24 [Xcode]     t =    60.64s             App event loop idle notification not received, will attempt to continue.
14:22:24 [Xcode] 
14:22:24 [Xcode]     t =    60.65s             App animations complete notification not received, will attempt to continue.
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.0-beta.1
* Last Appium version that did not exhibit the issue (if applicable): prod (1.8.1?)
* Desktop OS/version used to run Appium: Mac High Sierra
* Node.js version (unless using Appium.app|exe): 8.11.1
* Mobile platform/version under test: iOS 12 
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

https://gist.github.com/jamesvanhorn/5e857d83bba2f67e29ebf4f3e3c9e416

## Code To Reproduce Issue [ Good To Have ]

Just try to create an IOSDriver with waitForQuiesence:false

**Comment by jamesvanhorn** [comment]
Actually scratch the secondary issue about different results for waitForQuiesence on different machines. I did a full brew update (grabbing new node and carthage version), and it works now? Beats me, im not asking questions.

**Comment by mykola-mokhnach** [comment]
Please report the problem to https://github.com/facebook/WebDriverAgent

There is nothing much we can do on Appium side

**Comment by jamesvanhorn** [comment]
Actually this seems to have been resolved in WDA @mykola-mokhnach I seem to recall there being a way to manually pull in that change into my Appium instance, but i cant find the doc. Do you know where it is or the steps? https://github.com/facebook/WebDriverAgent/pull/979

**Comment by ZhouYiKoo** [comment]
I had the same problem, how to solve it?
