### ISSUE TITLE
how to change wda 

### ISSUE THREAD

**Issue by 141801** [appium/appium#11243]
I had installed appium 1.8.1 and then the wda is in the folder as follows
/Users/zhangliang/.npm-global/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent

Then I installed appium-desktop1.6.4 and the default wda is as follows
'/Applications/Appium1.6.4.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/

I want to use first  WDA and how can I do when I use appium-desktop to start a session

**Comment by KazuCocoa** [comment]
If you can find the path to `.app` of WDA which you'd like to use, what about using below capability? I guess you can use specific WDA via the desktop app.

- `usePrebuiltWDA`
- `derivedDataPath`

https://github.com/appium/appium-xcuitest-driver

**Comment by mykola-mokhnach** [comment]
Please use Appium forum to ask questions
