### ISSUE TITLE
Respect the legacy

### ISSUE THREAD

**Issue by CNSNGopenSourceProjects** [appium/appium#11252]
I was very pleased using Appium for IoS (iPhone), but all my legacy scripts stop working with the new Appium release since the changes did not respect the legacy.

It is very nice the new release fixed bugs and provided new features, but it is not good the new release changing API that impact the available scripts running.  

If you what to provide new feature create a new method or class but never, never, never, never, never, never, never, never, never, change what was running on field.  It is my decision (not yours) to update the available script to used the new features (or correction), since the bypass is on my script.

Now I want to use the new features on new scripts, but I have to review hundreds of Scripts before since they stop working.

Few examples:

- The press(x,y) has been replaced by press(point). What is the problem to keep both?
- The moveTo(x,y) has been replaced by moveTo(point). What is the problem to keep both?
- The moveTo() has been changed from relative to coordinate.  Why? Sometime relative is the best option. The better option should be to add move() to go to a specific position.
- The waitAction(delay) has been replaced by waitAction(option).  What is the problem to keep both?
- The driver.getKeyboard().sendKeys(string) stop working.  What is the problem to address keyboard directly?  It was nice you fix the problem that didn't allow me to use the WebElement sendKeys, butyou don't need to kill what was working in this process.

I appreciate if you could create a version review to fix it and, used "deprecated" or "not support" tag on legacy instead of remove or change the method behavior.

Please, see my concerns as recommendations to improve the product.

Best regards,

Fernando

**Comment by mykola-mokhnach** [comment]
> The move(x,y) has been replaced by move(point). What is the problem to keep both?
> The wait(delay) has been replaced by delay(option). What is the problem to keep both?

This is about java client and the methods had deprecated label. Although, if you skip more than one version then it is not guaranteed these deprecations stay for long.

> The move_to(x,y) has been changed from relative to coordinate. WhY? The move() already do it!

Because this was a bug and a major inconsistency, which has been fixed.

> The driver.getKeyboard().sendKeys(string) stop working. What is the problem to address keyboard directly? It was nice you fix the problem that didn't allow me to use the WebElement sendKeys, butyou don't need to kill what was working in this process.

There is a reason for it. Appium has switched to full W3C support since and such endpoint is not present in W3C standard. Also, xctest framework itself does not allow generic key press emulation.

**Comment by CNSNGopenSourceProjects** [comment]
Sorry, but I never got any warning of depreciation.  Can you please tell me:
- When these functions started to be marked as depreciated?
- How many months is the police between marked a function as depreciated and remove it?
- Where can I find the recommendation about how to update rework the script?

**Comment by mykola-mokhnach** [comment]
> When these functions started to be marked as depreciated?

This can be checked in file changes history: https://github.com/appium/java-client/commits/master/src/main/java/io/appium/java_client/TouchAction.java

> How many months is the police between marked a function as depreciated and remove it?

Usually the deprecated stuff is removed when the new major version is released

> Where can I find the recommendation about how to update rework the script?

There are no such recommendations

**Comment by CNSNGopenSourceProjects** [comment]
OK.  Thank you very much for the clarification.
