### ISSUE TITLE
Will appium try to search chrome-backed webview if I use chromedriverExecutableDir to automatic discovery?

### ISSUE THREAD

**Issue by bastenf** [appium/appium#11257]
## The problem
From the logs, I only see applium search the "com.android.chrome", not including the backend chrome

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.2-beta
* Desktop OS/version used to run Appium: Mac 10.13.4
* Node.js version (unless using Appium.app|exe): 10.8.0
* Mobile platform/version under test:  Android 7.0
* Real device or emulator/simulator: Real device 
* Appium CLI or Appium.app|exe: Appium CLI

## Details

I want to test wechat which has a backend chrome(version 57) on android, and want to use the chromedriverExecutableDir to automatic discovery of chromedriver. But it seems applium can't automatical find it.

**Comment by bastenf** [comment]
[debug] [AndroidDriver] Connecting to chrome-backed webview context 'WEBVIEW_com.tencent.mm:tools'
[debug] [AndroidDriver] A port was not given, using random port: 8000
[debug] [Chromedriver] Changed state to 'starting'
[debug] [Chromedriver] Attempting to use Chromedriver-Chrome mapping from '/basten/appium/mappings.json'
[debug] [Chromedriver] Found 4 executables in '/basten/selenium/chromedriver/'
[debug] [Chromedriver] The following Chromedriver executables were found:
[debug] [Chromedriver]     /basten/selenium/chromedriver/chromedriver_2_41 (minimum Chrome version 'Unknown')
[debug] [Chromedriver]     /basten/selenium/chromedriver/chromedriver_2_38 (minimum Chrome version '65.0.3325')
[debug] [Chromedriver]     /basten/selenium/chromedriver/chromedriver_2_26 (minimum Chrome version '53.0.2785')
[debug] [Chromedriver]     /basten/selenium/chromedriver/chromedriver_2_15 (minimum Chrome version 'Unknown')
[debug] [ADB] Device API level: 24
[debug] [ADB] Getting package info for 'com.android.chrome'
[debug] [ADB] Running '/basten/android-sdk/platform-tools/adb -P 5037 -s M960BDQG229P9 shell dumpsys package com.android.chrome'
[Chromedriver] Unable to discover Chrome version. Using Chromedriver 2.41 at '/basten/selenium/chromedriver/chromedriver_2_41'
[Chromedriver] Set chromedriver binary as: /basten/selenium/chromedriver/chromedriver_2_41
[debug] [Chromedriver] Killing any old chromedrivers, running: pkill -15 -f "/basten/selenium/chromedriver/chromedriver_2_41.*--port=8000"
[Chromedriver] No old chromedrivers seemed to exist
[debug] [Chromedriver] Cleaning any old adb forwarded port socket connections
[debug] [ADB] List forwarding ports
[debug] [ADB] Running '/basten/android-sdk/platform-tools/adb -P 5037 -s M960BDQG229P9 forward --list'
[debug] [ADB] Removing forwarded port socket connection: 50235 
[debug] [ADB] Running '/basten/android-sdk/platform-tools/adb -P 5037 -s M960BDQG229P9 forward --remove tcp\:50235'
[debug] [ADB] Removing forwarded port socket connection: 50249 
[debug] [ADB] Running '/basten/android-sdk/platform-tools/adb -P 5037 -s M960BDQG229P9 forward --remove tcp\:50249'
[debug] [ADB] Removing forwarded port socket connection: 50266 
[debug] [ADB] Running '/basten/android-sdk/platform-tools/adb -P 5037 -s M960BDQG229P9 forward --remove tcp\:50266'
[debug] [ADB] Removing forwarded port socket connection: 50285 
[debug] [ADB] Running '/basten/android-sdk/platform-tools/adb -P 5037 -s M960BDQG229P9 forward --remove tcp\:50285'
[Chromedriver] Spawning chromedriver with: /basten/selenium/chromedriver/chromedriver_2_41 --url-base=wd/hub --port=8000 --adb-port=5037 --verbose
[debug] [Chromedriver] Chromedriver version: '2.41.578706'
[debug] [JSONWP Proxy] Matched '/status' to command name 'getStatus'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Mac OS X\",\"version\":\"10.13.4\"}}}"
[debug] [JSONWP Proxy] Matched '/session' to command name 'createSession'
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.tencent.mm","androidUseRunningApp":true,"androidProcess":"com.tencent.mm:tools","androidDeviceSerial":"M960BDQG229P9"}}}
[debug] [Chromedriver] Webview version: 'Chrome/57.0.2987.132'
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"9b4ed2d48a194215daa9a56f915abc2e","status":33,"value":{"message":"session not created exception: Chrome version must be >= 67.0.3396.0\n  (Driver info: chromedriver=2.41.578706 (5f725d1b4f0a4acbf5259df887244095596231db),platform=Mac OS X 10.13.4 x86_64)"}}
[debug] [MJSONWP] Matched JSONWP error code 33 to SessionNotCreatedError
[Chromedriver] Error: Failed to start Chromedriver session: A new session could not be created. Details: session not created exception: Chrome version must be >= 67.0.3396.0
[Chromedriver]   (Driver info: chromedriver=2.41.578706 (5f725d1b4f0a4acbf5259df887244095596231db),platform=Mac OS X 10.13.4 x86_64)

**Comment by mykola-mokhnach** [comment]
Closed as inactive.

You could investigate the code flow yourself: https://github.com/appium/appium-chromedriver/tree/master/lib
