### ISSUE TITLE
[question] how can I determine the chrome version of webview

### ISSUE THREAD

**Issue by loveiset** [appium/appium#11258]
## The problem

I have a phone with android 6.0.1, but came out with webview with package name `com.android.webview`，it has it's own version `3.2.0`，not chrome version like package `com.google.android.webview`， how do I know the chrome version through the version of `com.android.webview`？

## Details

the newest appium support auto chromedriver discovery，but with the package `com.android.webview`，it seems not work
```
[debug] [ADB] Getting package info for 'com.google.android.webview'
[debug] [ADB] Running 'D:\hcs\Documents\Android-SDK\platform-tools\adb.exe -P 5037 -s 1469081a shell dumpsys package com.google.android.webview'
[debug] [ADB] Getting package info for 'com.android.webview'
[debug] [ADB] Running 'D:\hcs\Documents\Android-SDK\platform-tools\adb.exe -P 5037 -s 1469081a shell dumpsys package com.android.webview'
[debug] [Chromedriver] Found Chrome bundle 'com.android.webview' version '3.2.0'
[Chromedriver] Error: No Chromedriver found that can automate Chrome '3.2.0'. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md for more details.
```

**Comment by mykola-mokhnach** [comment]
Try appium@beta

**Comment by mykola-mokhnach** [comment]
Closed as inactive. 
You could still investigate the code on your own: https://github.com/appium/appium-chromedriver/tree/master/lib
