### ISSUE TITLE
Can we feed an image to andoid camera with appium ?

### ISSUE THREAD

**Issue by githubdilip** [appium/appium#11259]
## The problem

I need to automate the app with takes input from camera image. Can we feed particular image using appium ? Kindly help ? Is there any other tools available ?

## Environment

* Appium version (or git revision) that exhibits the issue:1.8.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:real device
* Appium CLI or Appium.app|exe:

**Comment by mykola-mokhnach** [comment]
No, appium does not provide any tools for that. Please use appium forum to ask quesions
