### ISSUE TITLE
WebDriverAgent function getPageSource hangs for over a minute

### ISSUE THREAD

**Issue by donioe** [appium/appium#11260]
## The problem

WebDriverAgent function getPageSource hangs for 65 seconds at a time due to an error in XCElementSnapshot.hitTest. This prevents using the WDA method "/source".

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.2-beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OSX High Sierra
* Mobile platform/version under test: iOS 12 beta-10 with Xcode 10 beta-6 (problems exists since beta-4)
* Real device or emulator/simulator: Real device

## Details

The current implementation of WebDriverAgent method XCUIElement+FBIsVisible.fb_isVisible uses the XCTest method XCElementSnapshot.hitTest which sometimes hangs for over a minute. Commenting out the line which uses this method solves the problem.

## Link to Appium logs

https://gist.github.com/donioe/dd362d927811e37193823c5710347a41

## Code To Reproduce Issue [ Good To Have ]

Reproduces immediately with almost any app (even iOS SpringBoard):

1. Run WebDriverAgent when device is connected.
2. Open http://<serverurl>:8100/source
3. Wait until the response arrives.

**Comment by mykola-mokhnach** [comment]
Please report the problem to https://github.com/facebook/WebDriverAgent

**Comment by mykola-mokhnach** [comment]
FB is also using hitTest to check the visibility

**Comment by mykola-mokhnach** [comment]
Also make sure your code is up to date. Get the last master snapshot from the fork manually

**Comment by donioe** [comment]
The code is up-to-date.
The issue also exists in facebook/WebDriverAgent. I opened the issue there:
https://github.com/facebook/WebDriverAgent/issues/984

Thanks.

**Comment by donioe** [comment]
any news regards the issue?
