### ISSUE TITLE
 I used the correct chromedriver version, error occurs that shows “chrome not reachable”

### ISSUE THREAD

**Issue by ldonlytest** [appium/appium#11267]
## The problem

chromedriverExecutableDir and chromedriverChromeMappingFile set, and use the right chromedriver version，error occurs that shows “chrome not reachable”

## Environment

* Appium version (or git revision) that exhibits the issue:1.8.1
* Desktop OS/version used to run Appium:win7
* Node.js version (unless using Appium.app|exe):v8.10.0
* Mobile platform/version under test:android v8.1.0
* Real device or emulator/simulator:Real device （nexus 6p）

## Details
mobile chrome version：61.0.3163.98
mapping.json：
{
  "2.33":"60.0.3112",
  "2.34":"61.0.3163",
  "2.41":"67.0.3360"
}
try user chromeDriver version：2.33、2.34，error occurs that shows “chrome not reachable”, please tell me why? tks

**Comment by mykola-mokhnach** [comment]
- Please attach the full server log
- Please try appium@beta
