### ISSUE TITLE
Appium is taking too much time for finding the elements on screen when there are many UI elements.

### ISSUE THREAD

**Issue by prat3ik** [appium/appium#11264]
## The problem

I am working on one Android application, Appium is working perfectly normal until one particular screen which has many UI components. Whereas that screen appears Appium takes so much time(About 2 minutes) to find particular elements. I am using ID selectors on that screen.
I have also observed when I print the page source on a console it does take around 40 to 50 seconds.

## Environment

* Appium Desktop version: 1.6.3
* Desktop OS: Mac OS High Sierra 10.3.6
* Node.js version: 10.9.0
* Mobile platform/version under test: One Plus 3T(8.0), Emulator(Google Pixel2 8.0)

**Desired Capabilities:**

> Capabilities {app: /Users/pratik/IdeaProjects/..., appPackage: com.sweep6.cloudtimer.qa, autoGrantPermissions: true, automationName: uiautomator2, databaseEnabled: false, desired: {app: /Users/pratik/IdeaProjects/..., autoGrantPermissions: true, automationName: uiautomator2, deviceName: c4e3f3cd, fullReset: false, noReset: false, platformName: android, platformVersion: 8.0}, deviceApiLevel: 26, deviceManufacturer: OnePlus, deviceModel: ONEPLUS A3003, deviceName: c4e3f3cd, deviceScreenDensity: 420, deviceScreenSize: 1080x1920, deviceUDID: c4e3f3cd, fullReset: false, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, noReset: false, pixelRatio: 2.625, platform: LINUX, platformName: Android, platformVersion: 8.0.0, statBarHeight: 63, takesScreenshot: true, viewportRect: {height: 1857, left: 0, top: 63, width: 1080}, warnings: {}, webStorageEnabled: false}

## Link to Appium logs
Appium Log: https://gist.github.com/prat3ik/5081316b537fbc01cac451e91f38e796
Video Execution: https://drive.google.com/open?id=1U3jzQcfKmM8EfklzXprMv9ZcMqhL5S2V

**Comment by mykola-mokhnach** [comment]
Try to disable the animations

**Comment by prat3ik** [comment]
I've already tried it but that didn't help. I think I need to ask the developer to disable animations for a test build.

**Comment by mykola-mokhnach** [comment]
By the way Appium has `disableWindowAnimation` capability, which worth trying. 

`adb logcat` output may also bring some interesting output.

**Comment by Warren25** [comment]
I have experienced this exact issue on the iOS side, the app worked fine until it hit a certain page. The developers allow me to make modifications to the app on a seperate fork, and commenting the line  'cell.slideInSubtle()' on that page fixed the issue.

I'll have to test out that 'disableWindowAnimation' capability

**Comment by mykola-mokhnach** [comment]
I'd also say it is an issue with the app itself, which prevents the UIA framework from interacting with elements properly. Closed as third party issue.
