### ISSUE TITLE
After updating appium version 1.9.0, facing this error org.openqa.selenium.InvalidArgumentException: 'wdaLaunchTimeout' must be of type number; 'wdaConnectionTimeout' must be of type number; 'wdaStartupRetries' must be of type number; 'wdaStartupRetryInterval' must be of type number

### ISSUE THREAD

**Issue by nageshc** [appium/appium#11269]
## The problem

After updating appium version 1.9.0, facing this error org.openqa.selenium.InvalidArgumentException: 'wdaLaunchTimeout' must be of type number; 'wdaConnectionTimeout' must be of type number; 'wdaStartupRetries' must be of type number; 'wdaStartupRetryInterval' must be of type number

## Environment

* Appium version (or git revision) that exhibits the issue: **1.9.0**
* Last Appium version that did not exhibit the issue (if applicable): **1.8.0**
* Desktop OS/version used to run Appium: **10.13.3 macOs High Sierra**
* Node.js version (unless using Appium.app|exe): **v8.9.1**
* Mobile platform/version under test: **iPhone 6s iOS 10.1.1**
* Real device or emulator/simulator: **Real iPhone device**

Selenium.version = **3.9.1**
Java-client = **6.0.0-BETA5**

## Details
Before appium 1.8.0 version my script is working fine, but today I have updated appium version to 1.9.0 and I am facing issue.

Getting error as following:
org.openqa.selenium.InvalidArgumentException: 'wdaLaunchTimeout' must be of type number; 'wdaConnectionTimeout' must be of type number; 'wdaStartupRetries' must be of type number; 'wdaStartupRetryInterval' must be of type number

In My Inetllij I have used this option to run the code:

-Dplatform="web"
-DplatformName="ios"
-Dudid="1234455"
-DbrowserName="Safari"
-DautomationName="XCUITest"
-DdeviceName="iPhone6"
-DplatformVersion="10.1.1"
-DnewCommandTimeout=90000
-DshowIOSLog="true"
-DbundleId="com.apple.mobilesafari"
-DappiumPort="4723"

## Link to Appium logs
https://gist.github.com/nageshc/4e1b91b362f4b27f9ccc7365938b6d2b

Could you please take look and help me to solve it.

Thank you

**Comment by mykola-mokhnach** [comment]
It is an issue with the client code. Make sure these capabilities are not strings, but numbers. 

Closed as not an issue.

**Comment by nageshc** [comment]
Thanks for the quick reply.

I have used as in double quote now I have removed the quotes.
Now it is working fine.

Thank you once again. 👍
