### ISSUE TITLE
Unable to set focus on Text Box in iOS Real Device.

### ISSUE THREAD

**Issue by nageshc** [appium/appium#11270]
## The problem

Unable to set focus on Text Box in iOS Real Device. I have test cases for Search box and I am using sendKeys method to enter search query but sendkeys just type the keys but not focusing so I unable to get search suggestion drop down.

I have used sendkeys method for Android Chrome and it works fine its types the keys and get the suggested list.

Manually on iPhone safari when I type in search box it shows the suggested list but in automation it does not just type the keys.

When clicks on any input field Keyboard should be open but keyboard is also not open on screen.

When clicks on any input filed mouse cursor should be displayed

## Environment

* Appium version (or git revision) that exhibits the issue: **1.9.0**
* Last Appium version that did not exhibit the issue (if applicable): **1.8.0**
* Desktop OS/version used to run Appium: **10.13.3 macOs High Sierra**
* Node.js version (unless using Appium.app|exe): **v8.9.1**
* Mobile platform/version under test: **iPhone 6s iOS 10.1.1**
* Real device or emulator/simulator: **Real iPhone 6s**

Selenium.version = 3.9.1
Java-client = 6.0.0-BETA5

## Details
I have tried following scenarios:

Scenarios 1 Steps :

1. Click on the search box using Searchbox.click();
2. Enter search query using Sendkeys()

Scenarios 2 Steps :

1. Click on the search box using Searchbox.click();
2. Enter search query using Send keys using javascript code

Scenarios 3 Steps :

1. Click on the search box using Searchbox.click();
2. Used Actions class but not works

## Link to Appium logs
https://gist.github.com/nageshc/654e00f19eea1b84c15b3392292d08a4

## Code To Reproduce Issue [ Good To Have ]

(getWebElement(shopperPageLocators.get("BY_XPATH_SEARCH_BOX_EB")).click();
(getWebElement(shopperPageLocators.get("BY_XPATH_SEARCH_BOX_WEB")).sendKeys( "Eye");      waitForPresence(getWebElement(shopperPageLocators.get("BY_XPATH_SEARCH_SUGGESTION_WEB")));

I have facing this issue only on iPhone safari not on Android Chrome.
Could you please help me to resolve this issue.

Thank you

**Comment by mykola-mokhnach** [comment]
I asume the standard sendKeys call simply does not trigger the input events which are needed to search search suggestions. I would try to emulate this by executing custom javascript.

**Comment by nageshc** [comment]
Hi @mykola-mokhnach ,

I have used following javaScript code:

`WebElement wb = (driver.findElement(getWebElement(shopperPageLocators.get("BY_XPATH_SEARCH_BOX_WEB"))));
JavascriptExecutor js = (JavascriptExecutor)driver;
js.executeScript("arguments[0].value='MAC';",wb);
waitForPresence(getWebElement(shopperPageLocators.get("BY_XPATH_SHOPPER_SEARCH_SUGGESTION_WEB")));`

It sends the keys but still search suggestion it not displayed and like on android chrome it is not blinking the mouse cursor.

Thanks for quick look. :)

**Comment by mykola-mokhnach** [comment]
You must check it with site developers on which events are expected and trigger these in your script

**Comment by mykola-mokhnach** [comment]
I cannot say anything there because I don't know how your application works. I would record all the js events generated manually then all the events generated by the automated script and would try to make them the same.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
