### ISSUE TITLE
Can't play screen recorded video

### ISSUE THREAD

**Issue by Trane9991** [appium/appium#11276]
## The problem

Can't play screen recorded video

## Environment

* Appium version 1.9.0
* OSX
* v10.9.0
* Android
* Emulator image: `system-images;android-27;google_apis_playstore;x86`

## Details
[stopRecordingScreen](http://appium.io/docs/en/commands/device/recording-screen/stop-recording-screen/) results in base64 video, which can be decoded fine with `bas64 --decode` but can't be played after

**Comment by mykola-mokhnach** [comment]
Please attach the full server log.  Also did you try to record the video from the emulator on your own with `adb shell screenrecor`? Is it playable?

**Comment by Trane9991** [comment]
`adb shell screenrecord` works fine.

I will try to send you server log tomorrow. But nothing suspicious was there.
Also, any reason why no such option to output video to the local path? Would be very useful for debugging, or at least some option not to clean up video from temporary dir where it is pulled from the device.

**Comment by Trane9991** [comment]
[appium.log](https://github.com/appium/appium/files/2331544/appium.log)
Appium server log attached.

**Comment by mykola-mokhnach** [comment]
Try if the patch from https://github.com/appium/appium-android-driver/pull/416 works for you

**Comment by Trane9991** [comment]
Nope, that didn't help, I can see updated kill command but video unplayable as well
`[debug] [ADB] Running '/usr/local/share/android-sdk/platform-tools/adb -P 5037 -s emulator-5554 shell kill -2 30877'`

VLC returns an error:
```
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fed62072800] moov atom not found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fed61970000] moov atom not found
```

Also, just to be sure, I removed the code line which deletes the temp dir and tried to play local video just pulled from adb. Doesn't work as well.

Going to try the same but on the device.

**Comment by mykola-mokhnach** [comment]
Can you please try the patch now? I've also added a verification of process termination

**Comment by Trane9991** [comment]
Still doesn't work... no idea what differs from calling the same from `adb shell` manually and it works :(

@mykola-mokhnach 
we could try to chat in Telegram, maybe it will be more productive :)

**Comment by mykola-mokhnach** [comment]
You can find me in Appium Slack. Also, the recent logs might be useful

**Comment by Trane9991** [comment]
Appium slack has a limited number of mail domains for signup and my not one of them.

**Comment by Trane9991** [comment]
New logfile
[appium.log](https://github.com/appium/appium/files/2332253/appium.log)

**Comment by Trane9991** [comment]
hmmm... good idea. I tried `kill -1` and `kill -2` and it worked fine.
But now I tried `kill -9` and it produces exactly the same error as video recorded from appium.

```
MPlayer 1.3.0-4.2.1 (C) 2000-2016 MPlayer Team

Playing ./kill9.mp4.
libavformat version 57.25.100 (internal)
libavformat file format detected.
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x102b0f4f0]moov atom not found
LAVF_header: av_open_input_stream() failed
ISO: File Type Major Brand: ISO/IEC 14496-1 (MPEG-4 system) v2
MOV: missing header (moov/cmov) chunk! Maybe broken file...
libavformat file format detected.
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x102b0f4f0]moov atom not found
LAVF_header: av_open_input_stream() failed


Exiting... (End of file)
```

**Comment by mykola-mokhnach** [comment]
Good. I have updated the code to kill the process via adb first. Can you please try it?

**Comment by mykola-mokhnach** [comment]
the fix has been published in appium@beta

**Comment by Trane9991** [comment]
@mykola-mokhnach 
fix is missing from appium@beta channel because `npm install -g appium@beta` installs version `1.9.0-beta.1` which depends on [`"appium-android-driver": "3.x"`](https://github.com/appium/appium/blob/v1.9.0-beta.1/package.json#L37) which doesn't have your patch included.

**Comment by mykola-mokhnach** [comment]
@dpgraham Do you mind publishing new beta with 4.x driver version?

**Comment by bjacog** [comment]
@Trane9991 @mykola-mokhnach I'm experiencing the same thing with `appium@1.11` even though it has this patch.

If I create a recording manually I can play it, but creating it via driver results in unplayable video.

**Comment by Trane9991** [comment]
@bjacog I didn't update to `appium@1.11` yet. Was it working fine on the `1.9.1` for you?

**Comment by bjacog** [comment]
@Trane9991 I'll give `1.9.1` a try.

**Comment by bjacog** [comment]
@Trane9991 I swapped out my devices for genymotion and the video recordings are working perfectly on `1.11`.

**Comment by moonatamanchuk** [comment]
Faced the same problem with `appium@1.11.1`
Downgrade appium-android-driver to version `4.7.0` resolved issue

**Comment by hemantbanafal** [comment]
I am facing this issue on appium@1.11 or appium@1.12 but it is working perfectly fine on appium@1.9.1. Can anyone please look into this on the latest version of appium ?

**Comment by alex-i-rybkin** [comment]
@mykola-mokhnach could you pls join the discussion?

**Comment by KuznietsovMaksym** [comment]
Hello Team,

Appium 1.9.1, I have the same issue. Maybe I'm doing something wrong, please advice:

// I'm staring screen recording and doing some actions
driver.startRecordingScreen(new IOSStartScreenRecordingOptions().withFps(30));

// Than I'm finishing screen recording and decode to .mp4
String base64 = driver.stopRecordingScreen();
        String videoLocationIOS = "/Users/myuser/folder/folder2/java/src/test/resources/File.mp4";
        byte[] decode = Base64.getDecoder().decode(base64);
        FileUtils.writeByteArrayToFile(new File(videoLocationIOS),
                decode);

But I'm not able to open the video. Looks like everybody have the same issue, right?

**Comment by hemantbanafal** [comment]
> Hello Team,
> 
> Appium 1.9.1, I have the same issue. Maybe I'm doing something wrong, please advice:
> 
> // I'm staring screen recording and doing some actions
> driver.startRecordingScreen(new IOSStartScreenRecordingOptions().withFps(30));
> 
> // Than I'm finishing screen recording and decode to .mp4
> String base64 = driver.stopRecordingScreen();
> String videoLocationIOS = "/Users/myuser/folder/folder2/java/src/test/resources/File.mp4";
> byte[] decode = Base64.getDecoder().decode(base64);
> FileUtils.writeByteArrayToFile(new File(videoLocationIOS),
> decode);
> 
> But I'm not able to open the video. Looks like everybody have the same issue, right?

For me iOS file is not playable in Appium 1.9.1, only Android file is playable. 
And in Appium 1.10+, iOS file is playable but not Android.

**Comment by KuznietsovMaksym** [comment]
Thanks **hemantbanafal**, I'll check.

**Comment by alex-i-rybkin** [comment]
Tried to use adb only solution in code, faced with video files corruption also. Had to add some delay between interrupting `adb screenrecord` process and pulling/removing file from device. This resolved the problem with corruption.
So from my point of view there is something going on straight on the phone after interrupting the screenrecord process. Mb similar logic should be added to appium-android-driver.

**Comment by mykola-mokhnach** [comment]
@alex-i-rybkin I've added a fix to appium@beta. No delay is needed if the process is terminated via adb shell. There is an issue in the current stable version where appium-adb cannot properly detect running process by its name.

**Comment by tanistra** [comment]
I am facing the same issue but with iOS (12.1) and Appium 1.13.0 (1.13.0.20190505.5). Cannot open recorded video. 

Works for android. 

my python code: 


    def setUp(self):
        self.driver.start_recording_screen()

    def tearDown(self):
        payload = self.driver.stop_recording_screen()
        if not self.is_failed():
            video_dir = os.path.join('../video', self.PLATFORM)
            video_name = os.path.join(
                video_dir, f'{self.__dict__["_testMethodName"]}.mp4')
            os.makedirs(video_dir, exist_ok=True)

            with open(video_name, "wb") as fd:
                fd.write(base64.decodestring(payload))


payload returns value: https://gist.github.com/tanistra/d8f14ebc33358e13f9241b1f6075d4ea

appium logs: https://gist.github.com/tanistra/ea3aa4b58cb53c4d741768a95a12efd7

@mykola-mokhnach can you help ?

**Comment by RishuKS** [comment]
**I am also facing the same issue with iOS  and Appium 1.13.0. Cannot open recorded video for IOS,** **Works for android.**

**My Kotlin code:**

   fun startVideoRecording() {
    
    (driver as IOSDriver).startRecordingScreen()
}

fun stopVideoRecording() {

    val video = (driver as IOSDriver).stopRecordingScreen()
    val decode = Base64.getMimeDecoder().decode(video)
    val finalPath = "$videoPath/$videoName"
    FileUtils.writeByteArrayToFile(File(finalPath), decode)
}

can any one please help?
Thank you

**Comment by tanistra** [comment]
@RishuKS After few hours of searching I found solution for this. I am not familiar with kotlin but it should works similar to my code in python. 

You have to set videoType = 'h264' argument in startRecordingScreen() method.

**Comment by RishuKS** [comment]
Hi @tanistra ,
Thank you for you reply but after adding videoType='h264' , I am getting error.

**Sample code to Start Recording:**

(driver as IOSDriver).startRecordingScreen( IOSStartScreenRecordingOptions().
                withVideoType("h264"))

**Error :**
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: The screen capture process 'ffmpeg' died unexpectedly. Check server logs for more details.

**Note :** I have tried with 'fmp4' but  error is same.

**Comment by hemantbanafal** [comment]
@RishuKS Try with "mpeg4"

`((CanRecordScreen) mobileDriver).startRecordingScreen(new IOSStartScreenRecordingOptions()
                    .withTimeLimit(Duration.ofSeconds(600)).withVideoType("mpeg4").withVideoQuality(VideoQuality.MEDIUM)
                    .enableForcedRestart());`

**Comment by RishuKS** [comment]
@hemantbanafal 
Working with 'mpeg4'.
Thank you for help.

**Comment by kkallu** [comment]
> hmmm... good idea. I tried `kill -1` and `kill -2` and it worked fine.
> But now I tried `kill -9` and it produces exactly the same error as video recorded from appium.
> 
> ```
> MPlayer 1.3.0-4.2.1 (C) 2000-2016 MPlayer Team
> 
> Playing ./kill9.mp4.
> libavformat version 57.25.100 (internal)
> libavformat file format detected.
> [mov,mp4,m4a,3gp,3g2,mj2 @ 0x102b0f4f0]moov atom not found
> LAVF_header: av_open_input_stream() failed
> ISO: File Type Major Brand: ISO/IEC 14496-1 (MPEG-4 system) v2
> MOV: missing header (moov/cmov) chunk! Maybe broken file...
> libavformat file format detected.
> [mov,mp4,m4a,3gp,3g2,mj2 @ 0x102b0f4f0]moov atom not found
> LAVF_header: av_open_input_stream() failed
> 
> 
> Exiting... (End of file)
> ```

Hi Friend ,

I'm facing this issue in Appium while recording ,can you please help me how can i fix this ??
FAILED CONFIGURATION: @BeforeMethod setupDriver
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unable to stop the background screen recording: Error executing adbExec. Original error: 'Command ''C:\\Users\\karthik kallu\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe' -P 5037 -s be716809 shell kill -15 2810' exited with code 1'; Stderr: '/system/bin/sh: kill: 2810: Operation not permitted'; Code: '1'

Here is my peace of code : 
((CanRecordScreen)driver).startRecordingScreen();


String media=((CanRecordScreen)driver).stopRecordingScreen();
			String dir="TestResults";
			File TestResultsDir=new File(dir);
			if(!TestResultsDir.exists())
			{
				TestResultsDir.mkdirs();
			}
			FileOutputStream stream=new FileOutputStream(TestResultsDir+File.separator+"TestCase_"+method.getName()+"_"+generateRandomNumber()+".mp4");
			stream.write(Base64.decodeBase64(media));
			driver.quit();
			}
