### ISSUE TITLE
Session ID is null  in Appium 1.9.0

### ISSUE THREAD

**Issue by pavanbachu0604** [appium/appium#11271]
## The problem

Trying to obtain the device Performance as mentioned in the [link](http://appium.io/docs/en/commands/device/performance-data/get-performance-data/) , we need to get the session ID as one of the inputs for the API which I am trying to retrieve from _/wd/hub/status_ but response obtained is 

_{"status":0,"value":{"build":{"version":"1.9.0"}},"sessionId":null}_

## Environment

* Appium version (or git revision) that exhibits the issue:1.9
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:10.9.0
* Real device or emulator/simulator:Real Device
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Gist to Appium [Logs](https://gist.github.com/pavanbachu0604/3bd8bdf622b11c902c510d30485e60e1)

**Comment by mykola-mokhnach** [comment]
Can you please properly describe the actual and the expected result and fix the link to logs?

**Comment by imurchie** [comment]
Based on the logs, there seems to be something wrong... The `Buffer` deprecation warning is from an older version of Appium. I was getting it and found that the problem was I had an errant install that was being run preferentially. While I wanted to run `/Users/isaacmurchie/.nvm/versions/node/v10.9.0/bin/appium` there was one in `/usr/local/bin/appium` too. It also meant I was getting some old dependencies.

**Comment by pavanbachu0604** [comment]
I have only appium installed at `/usr/local/bin/appium`, I dont want folder .nvm created at `/Users/`

**Comment by KazuCocoa** [comment]
Attached log => https://gist.github.com/pavanbachu0604/3bd8bdf622b11c902c510d30485e60e1

All session id looks below. No `null` one.

```
"sessionId":"560E02D1-F504-4C47-81C7-4CA3EAC10A6F"
```

And the `sessionId` in http://appium.io/docs/en/commands/device/performance-data/get-performance-data/ should be handled by the client. It's enough to manage _JSON Parameters_ in the lint.

Hence, I think you can call `getPerformanceData` correctly after establishing connections..

Did I miss something??
