### ISSUE TITLE
Unable to launch application and start test with appium 1.9.0 CLI tool

### ISSUE THREAD

**Issue by BoazWarshawsky** [appium/appium#11282]
## The problem
Since I moved to appium 1.9.0 I start seeing the following error:
Requested iOS support with version >= 10, using 'XCUITest' driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.

My actual problem is that I can't start any of my tests, with appium 1.8.1 all is working fine.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.0
* Last Appium version that did not exhibit the issue (if applicable): 1.8.0
* Desktop OS/version used to run Appium: Mac OS
* Node.js version (unless using Appium.app|exe): v8.11.2
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs
https://github.com/BoazWarshawsky/iOSAutomationAgent/blob/master/appium.log

## Code To Reproduce Issue [ Good To Have ]
Just start empty test, without any command.

**Comment by BoazWarshawsky** [comment]
The way I am installing appium server is as follow:
npm install -g appium
npm install wd

**Comment by BoazWarshawsky** [comment]
Hi Support,
I now see something else, sorry for reporting wrong details. 
My issue is that the test is stuck on dismissing startup Alerts. 
So far today with appium 1.8.1, since I can not tell how many alerts are expecting me on launch of the app I use to run in a loop(wrapped with try&catch):
self.driver.switch_to.alert.dismiss()

and when I got exceptions, I would have know that no Alerts are showing on screen. But now it seems that you handled the case and on dismiss() call its not throwing an exception when no alert is showing.

Can you please advice how I can know if more alerts are showing on screen?

**Comment by BoazWarshawsky** [comment]
@mykola-mokhnach

**Comment by Warren25** [comment]
@BoazWarshawsky You can try predicate strategy

Example 1.
@iOSXCUITFindBy(iOSNsPredicate = "name CONTAINS 'Update available'")
    private WebElement updateAlert;

boolean updateAlertIsDisplayed() {
try { return updateAlert.isDisplayed(); }
catch (NoSuchElementException e) { return false; }
}

if (updateAlertIsDisplayed)
// psuedo code to click some button to dismiss alert

Example 2.
WebElement foo = driver.findElementByIosNsPredicate("name == 'foo alert'");

**Comment by BoazWarshawsky** [comment]
"Update available" should be a hardcoded string?

**Comment by BoazWarshawsky** [comment]
@Warren25 Can I have this code in Python?
"Update available" should be a hardcoded string?

**Comment by Warren25** [comment]
@BoazWarshawsky https://qxf2.com/blog/page-object-model-selenium/

**Comment by KazuCocoa** [comment]
https://github.com/appium/python-client/blob/f8d600edd635a576d359534f1eec8d0f9f582287/appium/webdriver/webelement.py#L44 for find by predicate in Python

**Comment by mykola-mokhnach** [comment]
closed as inactive
