### ISSUE TITLE
Accesibility ID available in Appium inspector but not being found by driver in scripts

### ISSUE THREAD

**Issue by davidamplify** [appium/appium#11280]
## The problem

I'm trying to find an element using its accessibility id which shows in Appium inspector but searches for it are unsuccessful.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac
* Node.js version (unless using Appium.app|exe):using app
* Mobile platform/version under test:Android 8.1
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe:app

## Details

use below code to try searching for all these elements in web view and native app but array size is always 0. not sure why. extra note is that when I first load inspector on to the page nothing is individually recognised, just the whole screen but these items become visible after a refresh. in ionic
<img width="1082" alt="screen shot 2018-08-29 at 09 57 24" src="https://user-images.githubusercontent.com/41067524/44777237-faab8900-ab71-11e8-87d8-3a604d15456b.png">
<img width="1080" alt="screen shot 2018-08-29 at 09 54 51" src="https://user-images.githubusercontent.com/41067524/44777238-faab8900-ab71-11e8-860e-54f0ba7adc58.png">

## Link to Appium logs

https://gist.github.com/davidamplify/4b8b560f856b4115939091aad7c69e1e

## Code To Reproduce Issue [ Good To Have ]

```
List<WebElement> searchParametersElement = (List<WebElement>) driver.findElementsByAccessibilityId("28");
```

**Comment by davidamplify** [comment]
@mykola-mokhnach sorry I'm not sure how, thanks for quick reply btw

**Comment by davidamplify** [comment]
is this it? https://gist.github.com/davidamplify/588416e4dc63c53d774263a91c1bbf83

**Comment by mykola-mokhnach** [comment]
Yes, and I don't observe an element with accessibility id "28" there

**Comment by davidamplify** [comment]
any idea why it appears in appium inspector and not in the page source output. is there a way to "refresh" the page source like in the inspector which seems to reveal it's presence ?

**Comment by mykola-mokhnach** [comment]
This might be a race condition. Anyway, there is nothing that can be done on appium side. You could also check how it works with appium@beta though.

**Comment by davidamplify** [comment]
@mykola-mokhnach hope its okay to ask one more question here, I am now viewing it in web view. how to I access an element using this?
<div class="day-header" data-id="20180725">
      <div class="month">July</div>
      <ion-row class="row">
        <div class="day">
          25
        </div>
        <div class="day-text">
          Wed
        </div>
      </ion-row>
    </div>

The class day is not sufficient as all days are referred to as this, what can the number below be referenced as, if at all? Thanks very much

**Comment by mykola-mokhnach** [comment]
Appium desktop is only designed to work in native context. Use Chrome Debugger for web views
