### ISSUE TITLE
Javascript click not performing any action on unclickable element(Chrome browser)

### ISSUE THREAD

**Issue by surajgupta7175** [appium/appium#11288]
OS:  
ChromeDriver 2.38.55
Selenium Version:  3.12.0
Appium version 1.8

Browser:  Chrome

JavascriptClick not working on above version on any element. It executes and moves ahead without any change in screen(Element in webview-Chrome browser)

WebElement element = driver.findElement(By.xpath(xpath));
		JavascriptExecutor executor = (JavascriptExecutor) driver;
		executor.executeScript("arguments[0].click();", element);

Browser Version:  
Android - Chorme 68.0

## Actual Behavior - It is not
Note: This was working with java-client 5.0.4(Updated to 6.1.0 and it is not working)

**Comment by mykola-mokhnach** [comment]
I'm not quite sure how this worked before, but you cannot rely on `element` identifier from java lib. Replace `arguments[0]` with an element locator.

**Comment by mykola-mokhnach** [comment]
I don't observe any server issues in there. Please use appium forum to ask questions.
