### ISSUE TITLE
Unable to use UiAutomator2 on a Android 7.1.1 real device

### ISSUE THREAD

**Issue by oscheller1** [appium/appium#11284]
## The problem

When using 'automationName': 'UiAutomator2' desired capability, I get the following error (see gist).
As an alternative, I'm using  'automationName': 'Appium', which works but leads to other problems.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.0beta1
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: Mac os
* Node.js version (unless using Appium.app|exe): 6.4.0
* Mobile platform/version under test: Android 7.1.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: cli

## Link to Appium logs

https://gist.github.com/oscheller1/23dc689ab6a49bdca6c2ee1c398bab3b

**Comment by oscheller1** [comment]
Same problem as in https://github.com/appium/appium/issues/10993

Fix is to run
```
adb uninstall io.appium.uiautomator2.server
adb uninstall io.appium.uiautomator2.server.test
```

**Comment by mykola-mokhnach** [comment]
Many thanks for using search. Highly appreciated.
