### ISSUE TITLE
UiAutomator2's pageSource is different from UiAutomator1's, out of bounds child views

### ISSUE THREAD

**Issue by oscheller1** [appium/appium#11291]
## The problem

Just asking if anyone has found a solution to this problem: Getting the page source of an android app with UIA2 does not return out of bounds child views inside a parent container. This differs from UIA1, which still returned the child views, even if they were out of bounds of the parent container.
Unfortunately I'm testing an app, which has such out of bounds child views and I need to interact with them. This is was possible using 'automationName': 'Appium'. Using UIA2, there seems to be no way to return or interact with those elements, as UIA2 seems to only strictly return views that are "visible" to the end user, i.e. in bounds of parent views.

I've tried setting the `/setting` endpoint with `{"ignoreUnimportantViews": false, "allowInvisibleElements": true}`, this didn't change the behavior unfortunately.

I understand that this is properly intended behavior by UIA2 which makes sense in many ways. I still need some kind of workaround, since a refactoring of the app is not feasible. 

One solution could be to switch drivers on-the-fly to 'Appium' during test execution. Is that possible?

Any other suggestions would be highly appreciated.

**Comment by mykola-mokhnach** [comment]
Appium retrieves the page source from UIA2 framework. There is nothing that can be changed there.
