### ISSUE TITLE
(Referred issue 8376) An unknown server-side error occurred while processing the command. Original error: Unable to start WebDriverAgent session: Unexpected token < in JSON at position 0 and then the device disconnects

### ISSUE THREAD

**Issue by rstalekar** [appium/appium#11290]
## The problem
When I try to connect Appium client to Appium server running on a remote host within the organization following is the error:-
"An unknown server-side error occurred while processing the command. Original error: Unable to start WebDriverAgent session: Unexpected token < in JSON at position 0 "

## Environment
* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable):NA
* Desktop OS/version used to run Appium: Mac OS X 10.13.6
* Node.js version (unless using Appium.app|exe):8.11.3
* Mobile platform/version under test:iOS
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Steps:
Having referred to the issue https://github.com/appium/appium/issues/8376
I tried overriding proxy by doing export no_proxy=localhost, even export no_proxy=127.0.0.1 also export no_proxy=10.21.1.12 on the machine in which Appium server was running
1.	Launch Appium server on cli
2.	On the Appium client side(10.21.12.22)  to Appium server running on 10.21.1.12 
     We have added capability to connect existing WDA running on device
by specifying "webDriverAgentURL" = 'http://10.21.1.12:8000'
3.	Client connects to Appium server
4.	when Appium server sends create session command to WDA running on device
error thrown

## Link to Appium logs

[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.4","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 143 ms - 83
[HTTP] --> POST /wd/hub/session {"requiredCapabilities":{},"desiredCapabilities":{"deviceName":"iphone7_test","udid":"8ee6ffeb84b890497f61760e7fcf5df7c604f7d2","app":"/BerryPieRemote/Apps/LocationDemo.ipa","noReset":true,"newCommandTimeout":600,"platformVersion":"10.2","platformName":"IOS","webDriverAgentUrl":"http://10.21.1.12:8000"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"deviceName":"iphone7_test","udid":"8ee6ffeb84b890497f61760e7fcf5df7c604f7d2","app":"/BerryPieRemote/Apps/LocationDemo.ipa","noReset":true,"newCommandTimeout":600,"platformVersion":"10.2","platformName":"IOS","webDriverAgentUrl":"http://10.21.1.12:8000"},{},null,null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1535694455026 (11:17:35 GMT+0530 (IST))
[Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver (v2.27.2) session
[Appium] Capabilities:
[Appium]   deviceName: 'iphone7_test'
[Appium]   udid: '8ee6ffeb84b890497f61760e7fcf5df7c604f7d2'
[Appium]   app: '/BerryPieRemote/Apps/LocationDemo.ipa'
[Appium]   noReset: true
[Appium]   newCommandTimeout: 600
[Appium]   platformVersion: '10.2'
[Appium]   platformName: 'IOS'
[Appium]   webDriverAgentUrl: 'http://10.21.1.12:8000'
[debug] [XCUITest] XCUITestDriver version: 2.27.2
[BaseDriver] Session created with session id: fa9537a3-4590-440e-92c1-a93a5a570688
[debug] [XCUITest] Xcode version set to '9.4.1' (tools v9.4.1.0.1.1528165917)
[debug] [XCUITest] iOS SDK Version set to '11.4'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1535694455542 (11:17:35 GMT+0530 (IST))
[debug] [XCUITest] Available devices: 8ee6ffeb84b890497f61760e7fcf5df7c604f7d2
[debug] [XCUITest] Creating iDevice object with udid '8ee6ffeb84b890497f61760e7fcf5df7c604f7d2'
[XCUITest] Determining device to run tests on: udid: '8ee6ffeb84b890497f61760e7fcf5df7c604f7d2', real device: true
[BaseDriver] Using local app '/BerryPieRemote/Apps/LocationDemo.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[debug] [BaseDriver] Unzipping /var/folders/jn/wvm5yf1516d1w7331tdxl_pc0000gn/T/2018731-5561-1n60ip9.eug0f/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/jn/wvm5yf1516d1w7331tdxl_pc0000gn/T/2018731-5561-1n60ip9.eug0f/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/jn/wvm5yf1516d1w7331tdxl_pc0000gn/T/2018731-5561-1n60ip9.eug0f/Payload/LocationService.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1535694456155 (11:17:36 GMT+0530 (IST))
[debug] [XCUITest] Checking whether app '/var/folders/jn/wvm5yf1516d1w7331tdxl_pc0000gn/T/2018731-5561-1n60ip9.eug0f/Payload/LocationService.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [iOS] Getting bundle ID from app '/var/folders/jn/wvm5yf1516d1w7331tdxl_pc0000gn/T/2018731-5561-1n60ip9.eug0f/Payload/LocationService.app': 'com.xoriant.AtHoc'
[debug] [BaseDriver] Event 'resetStarted' logged at 1535694456163 (11:17:36 GMT+0530 (IST))
[debug] [XCUITest] Reset: fullReset not set. Leaving as is
[debug] [BaseDriver] Event 'resetComplete' logged at 1535694456163 (11:17:36 GMT+0530 (IST))
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1535694456333 (11:17:36 GMT+0530 (IST))
[XCUITest] Setting up real device
[debug] [XCUITest] App 'com.xoriant.AtHoc' is already installed. No need to reinstall.
[debug] [BaseDriver] Event 'appInstalled' logged at 1535694456462 (11:17:36 GMT+0530 (IST))
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1535694456463 (11:17:36 GMT+0530 (IST))
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Using provided WebdriverAgent at 'http://10.21.1.12:8000'
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1535694456463 (11:17:36 GMT+0530 (IST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://10.21.1.12:8000/session] with body: {"desiredCapabilities":{"bundleId":"com.xoriant.AtHoc","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1535694457467 (11:17:37 GMT+0530 (IST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://10.21.1.12:8000/session] with body: {"desiredCapabilities":{"bundleId":"com.xoriant.AtHoc","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1535694458476 (11:17:38 GMT+0530 (IST))
[debug] [XCUITest] Unable to start WebDriverAgent session: Unexpected token < in JSON at position 0
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[debug] [XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to start WebDriverAgent session: Unexpected token < in JSON at position 0
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:374:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
 Error: Unable to start WebDriverAgent session: Unexpected token < in JSON at position 0
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:374:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Unable to start WebDriverAgent session: Unexpected token < in JSON at position 0
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:374:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
[HTTP] <-- POST /wd/hub/session 500 52182 ms - 217
[HTTP] --> GET /wd/hub/status {}

**Comment by mykola-mokhnach** [comment]
Appium 1.6.4 is out of date. Please use the most recent version
