### ISSUE TITLE
Losing connection with Appium while turning off the mobile data connection on emulator

### ISSUE THREAD

**Issue by aleksandrawy** [appium/appium#11294]
## The problem

While using the UiAutomator2 (automationName) there is a problem while turning off the data connection on emulator. I have a test to check behaviour of the app while there is no Internet connection. Everything works fine if I don't set the automationName capability to UiAutomator2. 

## Environment

* appium-java-client 6.1.0
* Desktop OS/version used to run Appium: 1.9.0
* Node.js version: 10.8.0
* Mobile platform/version under test: Android (all APIs)
* Real device or emulator/simulator: emulator
* macOS High Sierra 10.13.6 

## Details

While there is the UiAutomator2 set, the following error appears in my console (I use maven to run tests):
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8200. There is also the Appium log attached below.

My app is build by ./gradlew with the connection to local server set on my Mac (and every test succeeds instead of those which use the mobile data connection turning off function).

## Link to Appium logs
The same error is shown in the Appium logs:
https://gist.github.com/aleksandrawy/8ecafe0984459cbfec09b51a0ac82d15

## Code To Reproduce Issue [ Good To Have ]

I've tried the following code variants to turn off the mobile data connection:
1) driver.setConnection(new ConnectionStateBuilder()
                .withDataDisabled()
                .build());
2) driver.toggleData()

and both options works fine while there is no UiAutomator2 set as automationName capability.

**Comment by mykola-mokhnach** [comment]
I don't think this can be fixed. Try to restart the driver after the data connection is disabled.

**Comment by aleksandrawy** [comment]
Ok, I'll try. Do you have any idea how to do it in Java during test executing?

**Comment by mykola-mokhnach** [comment]
Kindly use Appium forum for questions

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
