### ISSUE TITLE
endpoint /touch/perform encounter WebDriverException([NSNull floatValue])

### ISSUE THREAD

**Issue by robin-xl** [appium/appium#11302]
## The problem

call endpoint `/touch/perform` to imitate  drap and drop action,  raise WebDriverException

## Environment

* Appium version (or git revision) that exhibits the issue:1.9.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:mojave
* Node.js version (unless using Appium.app|exe):8.11.2
* Mobile platform/version under test:ios 10.3
* Real device or emulator/simulator:real device
* Appium CLI or Appium.app|exe:

## Link to Appium logs

[appium log](https://gist.github.com/robin-xl/f62236fd3d4a7e3a0413afc3eea503db)

**Comment by mykola-mokhnach** [comment]
There was a bug in python client. make sure you use the latest one. Closed as duplicate
