### ISSUE TITLE
Get error when start session  Security exception: Permission Denial: starting Intent

### ISSUE THREAD

**Issue by 631068264** [appium/appium#11307]
> An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.kingnet.fiveline' application. Original error: Error executing adbExec. Original error: 'Command '/Users/wyx/Library/Android/sdk/platform-tools/adb -P 5037 -s 85528347 shell am start -W -n com.kingnet.fiveline/com.kingnet.fiveline.ui.main.MainActivity -S' exited with code 255'; Stderr: 'Security exception: Permission Denial: starting Intent { flg=0x10000000 cmp=com.kingnet.fiveline/.ui.main.MainActivity } from null (pid=19537, uid=2000) not exported from uid 10246 java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=com.kingnet.fiveline/.ui.main.MainActivity } from null (pid=19537, uid=2000) not exported from uid 10246 at com.android.server.am.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1685) at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:542) at com.android.server.am.ActivityStarter.startActivityLocked(ActivityStarter.java:307) at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:945) at com.android.server.am.ActivityManagerService.startActivityAndWait(ActivityManagerService.java:5656) at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:417) at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:146) at android.os.ShellCommand.exec(ShellCommand.java:96) at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:16843) at android.os.Binder.shellCommand(Binder.java:611) at android.os.Binder.onTransact(Binder.java:509) at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:4281) at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3436) at android.os.Binder.execTransact(Binder.java:714)'; Code: '255'

Capabilities:
```
{
  "deviceName": "ONEPLUS_A5000",
  "appPackage": "com.kingnet.fiveline",
  "appActivity": "com.kingnet.fiveline.ui.main.MainActivity",
  "platformName": "Android",
  "noReset": true
}
```

The app can start without appium and appium can start other app's session

**Comment by mykola-mokhnach** [comment]
Closed as duplicate. Read https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup for more details.

**Comment by 631068264** [comment]
The link is invalid. @mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
fixed
