### ISSUE TITLE
Unable to override capability defined in --desired-capabilities with W3C protocol

### ISSUE THREAD

**Issue by kool79** [appium/appium#11308]
* Appium version (or git revision) 1.9.0
* java-client by SeleniumHQ v3.14.0 (direct connection without grid-hub)

## The problem
**Given:** appium server launched with 
`> appium --default-capabilities='{"appium:newCommandTimeout":100}'`

**When** I try to create new W3C session and override `newCommandTimeout` capability:
```java
	DesiredCapabilities dc = new DesiredCapabilities();
	dc.setCapability(CapabilityType.PLATFORM_NAME, Platform.IOS);
	dc.setCapability(CapabilityType.BROWSER_NAME, BrowserType.SAFARI);

	dc.setCapability("appium:automationName", "XCUITest");
	dc.setCapability("appium:platformVersion", "11.4");
	dc.setCapability("appium:deviceName", "iPhone 7");

	dc.setCapability("appium:newCommandTimeout ", 15);
	WebDriver wd = new RemoteWebDriver("http://ta-mac-01:4724/wd/hub", dc)  
```
**Then Actual behavior is:** 

1. appium log contains wrong warning about "not standard capabilities should have an extension prefix" (line 10) and 
2. appium switches to old JSONWP protocol with error:
`   [BaseDriver] property 'newCommandTimeout' should not exist on both primary ({"newCommandTimeout":100}) and secondary ({"browserName":"safari", "platformName":"ios", "automationName":"XCUITest", "deviceName":"iPhone 7", "newCommandTimeout":15, "platformVersion":"11.4"}) object`
`   [Appium] Could not parse fixed W3C capabilities: The arguments passed to the command are either invalid or malformed. Falling back to JSONWP protocol`

**But Expected behavior is:**
1. no warnings about "not standard capabilities should have an extension prefix" because I provide all non-standard caps with "appium:" prefix
2. all capabilities from --desired-capabilities are merged into w3c capabilities and/or jsonwp capabilities 
3. W3C session created

Log: https://gist.github.com/kool79/bbe16df469ea016cffaae4aef87bf6c4#file-appium-log-log-L21:L26

Additional info: 
* Releted issue: #10949
* Below is json object which was sent by selenium-java client with POST /session (grabbed by wireshark)
It includes both jsonwp and w3c data. By default appium tries to use w3c (and success if  I dont override any values from  `--desired-capabilities` )
``` json
{
  "desiredCapabilities": {
    "appium:newCommandTimeout": 15,
    "browserName": "safari",
    "appium:deviceName": "iPhone 7",
    "platformName": "IOS",
    "appium:automationName": "XCUITest",
    "appium:platformVersion": "11.4"
  },
  "capabilities": {
    "firstMatch": [
      {
        "appium:automationName": "XCUITest",
        "appium:deviceName": "iPhone 7",
        "appium:newCommandTimeout": 15,
        "appium:platformVersion": "11.4",
        "browserName": "safari",
        "platformName": "ios"
      }
    ]
  }
}
```

**Comment by mykola-mokhnach** [comment]
The fix for this one is already included to https://github.com/appium/appium/issues/11300

**Comment by mykola-mokhnach** [comment]
You could try to test it locally by merging https://github.com/appium/appium/pull/11303
