### ISSUE TITLE
Not able to integrate this with the npms used in my projects

### ISSUE THREAD

**Issue by anilkumar1505** [appium/appium#11305]
## The problem
We are using appium in our project and we got stuck in adding this to the npm dependencies that we used in the same. Here we are not able to add the accessibility labels to all the node modules so please suggest us to use any generic way of automating the third party dependencies.
Please help us to resolve this issue.

## Environment
We tried using this in android react native.

"appium": "^1.8.1",
 "appium-doctor": "^1.4.3"
 "react-native-calendars": "^1.16.1",
 "react-native-navigation": "^1.1.370",
 "react-native": "0.54.0",

## Details

We are using appium in our project and we got stuck in adding this to the npm dependencies that we used in the same. Here we are not able to add the accessibility labels to all the node modules so please suggest us to use any generic way of automating the third party dependencies.
We tried this in react-native navigation and react-native-calender.

Please help us to resolve this issue.

Thanks.

**Comment by mykola-mokhnach** [comment]
Please use appium forum for questions
