### ISSUE TITLE
Interactions are not available for textfield in iOS9

### ISSUE THREAD

**Issue by wangzi1325** [appium/appium#11304]
## The problem

In ios9.3, I can't  tap or  sendkeys with a textfeild 

## Environment

* Appium version (or git revision) that exhibits the issue: Appium desktop 1.6.3
* Desktop OS/version used to run Appium:  macOS 10.13.6
* Node.js version (unless using Appium.app|exe):8.11.4
* Mobile platform/version under test:  iOS  9.3.5
* Real device or emulator/simulator:  iPad mini
* Appium CLI or Appium.app|exe: Appium.app

## Details

Just  tap or sendkeys in inspector

## Link to Appium logs
https://gist.github.com/wangzi1325/45654bedea5cae23c2dd9facab379259

**Comment by mykola-mokhnach** [comment]
I don't observe any issues in the log. The element is simply not found

**Comment by wangzi1325** [comment]
I found the element by  predicate string like this：type="XCUIElementTypeTextField"
![image](https://user-images.githubusercontent.com/4196935/44986908-dad3f500-afb7-11e8-8aa2-41afafb62695.png)
But I couldn't   tap or sendkeys  with this element. 
The keybord didn't turn up。

**Comment by mykola-mokhnach** [comment]
There is nothing we can do to show the keyboard. Please report the problem to Apple.

**Comment by wangzi1325** [comment]
But  when  i tap the textfield by coordinates,  the keyboard appeared immediately。
![image](https://user-images.githubusercontent.com/4196935/45006447-8702f380-b02b-11e8-88c3-e7468bb6928d.png)
Do you mean that appium  does not  support iOS9 ？
