### ISSUE TITLE
Command ''C:\\Users\\Om Prasad\\sdk\\platform-tools\\adb.exe' -P 5037 -s ZX1D62S3MB push 'C:\\Users\\Om Prasad\\AppData\\Local\\appium-desktop\\app-1.5.0\\resources\\app\\node_modules\\appium\\node_modules\\appium-android-bootstrap\\bootstrap\\bin\\AppiumBootstrap.jar' /data/local/tmp/' exited with code 1

### ISSUE THREAD

**Issue by ommprasad** [appium/appium#11311]
## The problem
Cosole
------
An unknown server-side error occurred while processing the command. Original error: Error occured while starting AndroidBootstrap. Original error: Error: Error executing adbExec. Original error: 'Command ''C:\\Users\\Om Prasad\\sdk\\platform-tools\\adb.exe' -P 5037 -s ZX1D62S3MB push 'C:\\Users\\Om Prasad\\AppData\\Local\\appium-desktop\\app-1.5.0\\resources\\app\\node_modules\\appium\\node_modules\\appium-android-bootstrap\\bootstrap\\bin\\AppiumBootstrap.jar' /data/local/tmp/' exited with code 1'; Stderr: ''; Code: '1' (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 24.90 seconds

## Environment

* Appium version (or git revision) that exhibits the issue:1.7.2
* Last Appium version that did not exhibit the issue (if applicable):ya
* Desktop OS/version used to run Appium:window 10
* Node.js version (unless using Appium.app|exe):ya
* Mobile platform/version under test:Andriod 6.0
* Real device or emulator/simulator:real device
* Appium CLI or Appium.app|exe:

## Details

It is not able to lunch the application.

## Link to Appium logs

[AndroidDriver] Shutting down Android driver
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[MJSONWP] Encountered internal error running command: Error: Error occured while starting AndroidBootstrap. Original error: Error: Error executing adbExec. Original error: 'Command ''C:\\Users\\Om Prasad\\sdk\\platform-tools\\adb.exe' -P 5037 -s ZX1D62S3MB push 'C:\\Users\\Om Prasad\\AppData\\Local\\appium-desktop\\app-1.5.0\\resources\\app\\node_modules\\appium\\node_modules\\appium-android-bootstrap\\bootstrap\\bin\\AppiumBootstrap.jar' /data/local/tmp/' exited with code 1'; Stderr: ''; Code: '1'
    at Object.wrappedLogger.errorAndThrow (C:\Users\Om Prasad\AppData\Local\appium-desktop\app-1.5.0\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:69:13)
    at AndroidBootstrap.start$ (C:\Users\Om Prasad\AppData\Local\appium-desktop\app-1.5.0\resources\app\node_modules\appium\node_modules\appium-android-bootstrap\lib\bootstrap.js:98:11)
    at tryCatch (C:\Users\Om Prasad\AppData\Local\appium-desktop\app-1.5.0\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Om Prasad\AppData\Local\appium-desktop\app-1.5.0\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\Om Prasad\AppData\Local\appium-desktop\app-1.5.0\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\Om Prasad\AppData\Local\appium-desktop\app-1.5.0\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at 
[HTTP] <-- POST /wd/hub/session 500 24778 ms - 619 

## Code To Reproduce Issue [ Good To Have ]

import java.net.MalformedURLException;
import java.net.URL;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import io.appium.java_client.AppiumDriver;
import io.appium.java_client.MobileElement;
import io.appium.java_client.android.AndroidDriver;

public class Finlead1 {
	
	static AppiumDriver<MobileElement> driver;
	
//	static WebDriver  driver=null;
	
	public static void main(String[] args) throws Exception {
		
		
		
		DesiredCapabilities caps = new DesiredCapabilities();
		
		caps.setCapability("deviceName", "my_phone");
		
		caps.setCapability("udid", "ZX1D62S3MB"); //Give Device ID of your mobile phone
		
		caps.setCapability("platformName", "Android");
		
		caps.setCapability("platformVersion", "6.0");
		
        caps.setCapability("appPackage", "com.fl.finleadz.finleadz");
		
		caps.setCapability("appWaitActivity", "com.fl.finleadz.finleadz.LoginActivity");
		 
		
		
        //caps.setCapability("appPackage", "com.mindzglobal.vaf.virtualadmissionfair");
		
	    //  caps.setCapability("appActivity", "com.mindzglobal.vaf.virtualadmissionfair.LoginSignup.LoginActivity");
		
        // caps.setCapability("appPackage", "com.fl.finleadz.finleadz");
		
		// caps.setCapability("appActivity", "com.fl.finleadz.finleadz.ResetPassword");
		 
		// caps.setCapability("appPackage", "expertseller.mmes.com.es.expert_new");
			
		// caps.setCapability("appActivity", "expertseller.mm.mmes.com.ui.LauncherActivity");
		
		caps.setCapability("noReset", "true");
		
		System.out.println("it is my appium test");
		
		
		
		
		//Instantiate Appium Driver
		try {
				driver = new AndroidDriver<MobileElement>(new URL("http://0.0.0.0:4723/wd/hub"), caps);
			
			//driver = new RemoteWebDriver(new URL("http://0.0.0.0:4723/wd/hub"), caps);
			
		} catch (MalformedURLException e) {
			
			Thread.sleep(2000);
			
			System.out.println(e.getMessage());
		}
	}

**Comment by mykola-mokhnach** [comment]
Use UiAutomator2 for Android 6+

**Comment by mykola-mokhnach** [comment]
Also you appium server seems to be outdated.

**Comment by ommprasad** [comment]
No it is already 1.7.2

**Comment by mykola-mokhnach** [comment]
The most recent one is 1.9.0

**Comment by ommprasad** [comment]
It is opening lunching gmail,playstores and other applications  but my application only is not lunching .
why it is ?

**Comment by mykola-mokhnach** [comment]
I cannot say why unless you upgrade the server and switch to UiAutomator2. Unfortunately we don't have much time to spend on legacy stuff.

**Comment by ommprasad** [comment]
I update the appium server version stil it unable to lunch my app.

**Comment by mykola-mokhnach** [comment]
Any logs?

**Comment by ommprasad** [comment]
Device API level: 23
[ADB] Running 'C:\Users\Om Prasad\sdk\platform-tools\adb.exe -P 5037 -s
ZX1D62S3MB shell am start -W -n
com.fl.finleadz.finleadz/com.fl.finleadz.finleadz.ResetPassword -S'
[AndroidDriver] Shutting down Android driver
[ADB] Running 'C:\Users\Om Prasad\sdk\platform-tools\adb.exe -P 5037 -s
ZX1D62S3MB shell am force-stop com.fl.finleadz.finleadz'
[ADB] Pressing the HOME button
[ADB] Running 'C:\Users\Om Prasad\sdk\platform-tools\adb.exe -P 5037 -s
ZX1D62S3MB shell input keyevent 3'
[AndroidBootstrap] Sending command to android: {"cmd":"shutdown"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client:
{"cmd":"shutdown"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type SHUTDOWN
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result:
{"status":0,"value":"OK, shutting down"}
[AndroidBootstrap] Received command result from bootstrap
[UiAutomator] Shutting down UiAutomator
[UiAutomator] Moving to state 'stopping'
[UiAutomator] UiAutomator shut down normally
[UiAutomator] Moving to state 'stopped'
[ADB] Attempting to kill all uiautomator processes
[ADB] Getting all processes with uiautomator
[ADB] Running 'C:\Users\Om Prasad\sdk\platform-tools\adb.exe -P 5037 -s
ZX1D62S3MB shell ps'
[ADB] No uiautomator process found to kill, continuing...
[UiAutomator] Moving to state 'stopped'
[Logcat] Stopping logcat capture
[ADB] Running 'C:\Users\Om Prasad\sdk\platform-tools\adb.exe -P 5037 -s
ZX1D62S3MB shell am force-stop io.appium.unlock'
[AndroidDriver] Not cleaning generated files. Add `clearSystemFiles`
capability if wanted.
[BaseDriver] Event 'newSessionStarted' logged at 1536227705569 (15:25:05
GMT+0530 (India Standard Time))
[MJSONWP] Encountered internal error running command: Error: Cannot start
the 'com.fl.finleadz.finleadz' application. Visit
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md
for troubleshooting. Original error: The permission to start
'com.fl.finleadz.finleadz.ResetPassword' activity has been denied.Make sure
the activity/package names are correct.
[MJSONWP]     at ADB.callee$0$0$ (C:\Users\Om
Prasad\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\apk-utils.js:134:11)
[MJSONWP]     at tryCatch (C:\Users\Om
Prasad\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke]
(C:\Users\Om
Prasad\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function)
[as next] (C:\Users\Om
Prasad\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (C:\Users\Om
Prasad\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[MJSONWP]     at
[HTTP] <-- POST /wd/hub/session 500 19378 ms - 480

**Comment by mykola-mokhnach** [comment]
> [MJSONWP] Encountered internal error running command: Error: Cannot start
the 'com.fl.finleadz.finleadz' application. Visit
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: The permission to start
'com.fl.finleadz.finleadz.ResetPassword' activity has been denied.Make sure
the activity/package names are correct.

I assume the error description there does not require any further comments. Also, I don't observe the automation backend has been switched to uia2

**Comment by ommprasad** [comment]
M. Not getting

**Comment by mykola-mokhnach** [comment]
I have nothing more to add here from my side

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
