### ISSUE TITLE
Appium issue not able to select date

### ISSUE THREAD

**Issue by RohitrajElpis** [appium/appium#11319]
I am trying to automate insurance related android app. where I need to select policy effective date. but I am not able to click on policy effective date I even tried all locators sucj as: id, name, classname, xpath.

The part below mentions all locators I used such as:

#id
clickeffectivee=ebroker.com.ebroker:id/edt_effective_date

#by name
clickeffectivee1=Policy Effective Date

#class name
clickeffectivee2=android.widget.EditText

#classname2
clickeffectivee3=TextInputLayout

#xpath with text
clickeffectivee4=//android.widget.EditText[@text="Policy Effective Date"]
clickeffectivee5=//android.widget.EditText[@name='Policy Effective Date']

#xpath with contain

clickeffectivee6=//android.widget.EditText[contains(@resource-id,'effective_date_layout')]

#xpath with contain and text 

clickeffectivee7=//android.widget.EditText[contains(@resource-id,'effective_date_layout')and (@text='Policy Effective Date')]
for this particular method as

    public void  selectdate () throws InterruptedException, FileNotFoundException, IOException,
    EncryptedDocumentException, InvalidFormatException {
    Thread.sleep(5000);
    WebElementcp(appium.findElement(By.xpath(Lib.getProperty(CONFIG_PATH, "clickeffectivee7"))));
    cp.click();
After running I am getting an error message I even tried so many times still I am getting the same below mentioned error message

 PFA image [issue image ][1]

        Thread.sleep(3000);

  [1]: https://i.stack.imgur.com/sPL1n.png

**Comment by mykola-mokhnach** [comment]
Please provide the information requested by the issue template along with full server logs

**Comment by RohitrajElpis** [comment]
Hi @mykola-mokhnach  **please find log file and Console file and template** 
![dump_2050496096745176487](https://user-images.githubusercontent.com/43004068/45212432-829c3c00-b2b2-11e8-8d38-5cffc8934c96.png)


please do need full help still i am facing same issue
[appium-server-logs.txt](https://github.com/appium/appium/files/2360529/appium-server-logs.txt)
![eclipse consol](https://user-images.githubusercontent.com/43004068/45212220-f68a1480-b2b1-11e8-9927-e20d0842fa49.PNG)
![log file 1](https://user-images.githubusercontent.com/43004068/45212221-f68a1480-b2b1-11e8-93e4-ae57d22610dd.PNG)

**Comment by RohitrajElpis** [comment]
[appium-server-logs.txt](https://github.com/appium/appium/files/2360546/appium-server-logs.txt)

**Comment by mykola-mokhnach** [comment]
Use UiAutomator2 backend for Android 6+

**Comment by RohitrajElpis** [comment]
Hi @mykola-mokhnach can you please give me any small hint how to use UiAutomator2 for Automation point of view as i am using uiautomatorViewer. 

why i am asking because i am new person just now i started working on Mobile Automation so please help me out ASAP.

**Comment by KazuCocoa** [comment]
@RohitrajElpis 
As you can see below message in the logs, simply, it's enough to add `automationName: 'uiautomator2'` in your capability like http://appium.io/docs/en/about-appium/getting-started/#running-your-first-test to use uiautomator2 as your android driver.


> [warn] [35m[Appium][39m Consider setting 'automationName' capability to 'uiautomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.

**Comment by mykola-mokhnach** [comment]
http://appium.io/docs/en/drivers/android-uiautomator2/

**Comment by RohitrajElpis** [comment]
hi @KazuCocoa as you suggested me i did as same can u please have a look on my attached image
![uiautomator 2](https://user-images.githubusercontent.com/43004068/45220850-35799380-b2cd-11e8-9f68-9052581417ca.PNG)

**Comment by KazuCocoa** [comment]
No, you should add `caps.setCapability("automationName", "UiAutomator2")`, it looks.
You added the `UiAutomator2` as `value` capability.

**Comment by RohitrajElpis** [comment]
hi @KazuCocoa  sure i did like same and i added automatic server as same 
![appium](https://user-images.githubusercontent.com/43004068/45222190-652a9a80-b2d1-11e8-9c61-c64c0ba0c022.PNG)

please have a look once is this valid

**Comment by RohitrajElpis** [comment]
![uiautomator 2](https://user-images.githubusercontent.com/43004068/45222465-4c6eb480-b2d2-11e8-8733-dc44e97a086d.PNG)

**Comment by KazuCocoa** [comment]
looks fine

**Comment by mykola-mokhnach** [comment]
@RohitrajElpis Please use Appium forum if you have questions. Here we only solve issues (or at least try to).

**Comment by RohitrajElpis** [comment]
@KazuCocoa and @mykola-mokhnach  tq so much for support i will use Appium forum else i will ask there if i get any doubt

**Comment by KazuCocoa** [comment]
Log in to the forum and create a topic via _New Topic_ with support category. You can leave the topic without changing status.

**Comment by RohitrajElpis** [comment]
Hi @KazuCocoa it's relay important to me know about forum can you  please send me link where i can create forum login and create issue so i can get result soon , please do need full help.

![forum](https://user-images.githubusercontent.com/43004068/45360377-02950f80-b5ed-11e8-983f-f17f647b0e79.JPG)
 according to your comment i am not getting any option to 
1.login to forum 
2.creation new topic 
3.support category
4,rasing issue

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium/issues/11349#issuecomment-420266197
