### ISSUE TITLE
iOS hideKeyboard doesn't work

### ISSUE THREAD

**Issue by romainlouvet** [appium/appium#11313]
## The problem

When call driver.hideKeyboard() -> do nothing

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.0
* Appium client: java client 6.1.0
* Xcode: 9.4.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS 10.13.6
* Mobile platform/version under test: iOS 11.4.1
* Real device or emulator/simulator: real device

## Link to Appium logs

https://gist.github.com/romainlouvet/c1ad8fad6d87bf9a2c9e208c4e833a2e

**Comment by romainlouvet** [comment]
it's work with element.sendKeys("\n\n\n\n\n")

**Comment by mykola-mokhnach** [comment]
Please report the problem to Apple. We can do nothing to resolve it.
