### ISSUE TITLE
Get location using appium driver not working

### ISSUE THREAD

**Issue by InfantAnto** [appium/appium#11318]
Setting mock location in Android real device works fine now with appium driver:
> driver.setLocation(new Location(38.926592, -77.039932, 10));
            
But getting the actual geo location throws the following error:
> INFO: HTTP Status: '404' -> incorrect JSON status mapping for 'unknown method' (405 expected)
> org.openqa.selenium.UnsupportedCommandException: Method has not yet been implemented
> 
> Location location = getDriver().location();

@mykola-mokhnach Can you help me to solve this issue.
I could see in appium docs like the driver should be implemented locationContext. AppiumDriver implements locationContext. But why its not working?

**Comment by mykola-mokhnach** [comment]
This does not work because it is not implemented. There is a [feature request](url
https://github.com/appium/appium/issues/5047) for it. Feel free to take care of it and push a PR.
