### ISSUE TITLE
Appium v1.8.1 - [XCUITest] Error: Command 'ps' not found. Is it installed?

### ISSUE THREAD

**Issue by satapathysidhant** [appium/appium#11328]
i am trying to launch appium server by code.
the server starts and the first test case runs on the iphone7 simulator,
but the moment the second test case starts i get the error below. This doesnt happen when i start the server manually and the run the same test cases.

`
[Appium] Welcome to Appium v1.8.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[debug] [BaseDriver] Event 'simStarted' logged at 1536258086372 (23:51:26 GMT+0530 (India Standard Time))
[debug] [XCUITest] Verifying application platform
[debug] [XCUITest] CFBundleSupportedPlatforms: ["iPhoneSimulator"]
[debug] [XCUITest] Reset requested. Removing app with id 'com.pvh.PVHDigitalAssistant' from the device
[debug] [XCUITest] Installing '/Users/sidhant.satapathy/Desktop/DigitalAssistant.app' on Simulator with UUID 'D62C5C0C-2B61-46F9-99A0-91CC0A3A8515'...
[debug] [XCUITest] The app has been installed successfully.
[debug] [BaseDriver] Event 'appInstalled' logged at 1536258090293 (23:51:30 GMT+0530 (India Standard Time))
[XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
**[XCUITest] Error: Command 'ps' not found. Is it installed?**
[XCUITest]     at ChildProcess.<anonymous> (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/[debug]node [_mXCUIodTestules/te] Not encle_procearissng log files. Use `clearSystemFiles` capabil/lib/exec.js:39:1ity4)
[ tXCUITesto tur]     an ont Ch.
il[debdProcess.emugit (ev] [iOSLog] Stoppineng iOts.jsS l:182:og cap13)tu
[Xre
CUITest]     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
[XCUITest]     at onErrorNT (internal/child_process.js:406:16)
[XCUITest]     at process._tickCallback (internal/process/next_tick.js:63:19)
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1536258090394 (23:51:30 GMT+0530 (India Standard Time))
[W3C] Encountered internal error running command: Error: Command 'ps' not found. Is it installed?
[W3C]     at ChildProcess.<anonymous> (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/teen_process/lib/exec.js:39:14)
[W3C]     at ChildProcess.emit (events.js:182:13)
[W3C]     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
[W3C]     at onErrorNT (internal/child_process.js:406:16)
[W3C]     at process._tickCallback (internal/process/next_tick.js:63:19)`

**Comment by mykola-mokhnach** [comment]
Is `/bin/ps` present on your system? Is the PATH environment variable value correct?

**Comment by mykola-mokhnach** [comment]
I assume there is a problem with your environment setup. Refer https://github.com/appium/java-client/blob/master/docs/environment.md for more details

**Comment by satapathysidhant** [comment]
yes ps is there in the bin folder i have set the path variable as below
bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/bin/ps

**Comment by satapathysidhant** [comment]
I think i corrected the path variable now its working. closing the ticket
