### ISSUE TITLE
exists function shows error in log

### ISSUE THREAD

**Issue by waynema** [appium/appium#11321]
## The problem

Before Appium 1.9 the exists function won't show error in log if the element does not exist.  But on the 1.9.0 version, it show warning/errors in log

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.0
* Last Appium version that did not exhibit the issue (if applicable): 1.8.1
* Desktop OS/version used to run Appium: High Sierra
* Node.js version (unless using Appium.app|exe): v9.3.0
* Mobile platform/version under test: iOS 11
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI

## Details
I use the exists function in appium ruby_lib.  This error shows in log on Appium 1.9.0 when an element does not exist
[W3C] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[W3C]     at XCUITestDriver.callee$0$0$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:130:13)
[W3C]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[W3C]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[W3C]     at <anonymous>

**Comment by dpgraham** [comment]
Does this cause problems?

**Comment by waynema** [comment]
it causes no harm. however, it shows as an error in log

**Comment by dpgraham** [comment]
So I guess if I understand correctly, you have tests where you expect the element to not exist and it causes confusion because the errors + stacktrace make it look like your test is not passing.

**Comment by waynema** [comment]
@mykola-mokhnach ,  the 1.9.1-beta2 does not work for me.  I got "[XCUITest] Error: Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: *** -[NSProxy forwardInvocation:] called!"

**Comment by mykola-mokhnach** [comment]
Can you provide the full exception stack?

**Comment by waynema** [comment]
I am using Xcode10 beta-5

**Comment by mykola-mokhnach** [comment]
The log level has been changed to `debug`, so you can exclude this stack trace from server log in the recent  appium@beta by adjusting the `--log-level` server argument. Regarding the error - I cannot reproduce it locally. Make sure that WebDriverAgent source is not cached.

**Comment by manyakin** [comment]
Perhaps you have a waitForQuiescence dependency in the settings, if you delete it, it will work

**Comment by waynema** [comment]
@manyakin , thanks for the suggestion.  If I comment out the property, the error won't show up.  However, the test is stuck on the initial screen for a long long time.  The following is the property we put into the capability to workaround the last Xcode and appium update.  And it works with the appium version 1.9.0 and before( less startup wait time)
-----------------------
clearSystemFiles = true
#wdaStartupRetryInterval = 1000
#useNewWDA = true
#waitForQuiescence = false
shouldUseSingletonTestManager = false

**Comment by waynema** [comment]
@mykola-mokhnach ,  we do have this waitForQuiescence = false capability property to speed up the initial screen processing time.  However, if that is on, the appium 1.9.1 won't be starting with the error we encountered.  Is there some reason this cap is not supported anymore?

**Comment by waynema** [comment]
@dpgraham @mykola-mokhnach ,  I change the bug title for this report.  Since this bug is closed,  should I open a new issue to track this "waitForQuiescence = false capability leads to starting error in appium 1.9.1"?

**Comment by waynema** [comment]
@mykola-mokhnach,  thanks.  When will be the next appium release that will have this fix?

**Comment by mykola-mokhnach** [comment]
it will be merged to beta soon

**Comment by nenaddrop** [comment]
@mykola-mokhnach any idea when will this make it into the beta build? Thanks!

**Comment by mykola-mokhnach** [comment]
I'll publish the fix this week

**Comment by sansong-db** [comment]
Hi @mykola-mokhnach has a fix been published yet? My team is also facing the same issue i.e. when  waitForQuiescence=false we get the following error: 

[XCUITest] Error: Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: *** -[NSProxy forwardInvocation:] called!
 
Appium Server  v1.9.1
Xcode v10.0

**Comment by KazuCocoa** [comment]
You can try the latest one with `npm install -g appium@beta` @sansong-db (1.9.2-beta)

**Comment by sansong-db** [comment]
Thanks @KazuCocoa , @mykola-mokhnach , tested with version 1.9.2-beta.2 today and can confirm it work for me, I'm no longer getting the "NSProxy forwardInvocation" issue.

Xcode v10.0
Appium Server v1.9.2-beta.2
