### ISSUE TITLE
[iOS] Incorrect element location for native Share dialog buttons

### ISSUE THREAD

**Issue by ndinoia** [appium/appium#11324]
## The problem

The iOS share dialog buttons are untappable and unclickable, most likely because Appium is getting incorrect element coordinates.

## Environment

* Appium version (or git revision) that exhibits the issue: Used the inspector feature from Appium Desktop `1.6.3` connected to a CL Appium `1.9.0` server
* Desktop OS/version used to run Appium: MacOS High Sierra `10.13.4`
* Node.js version (unless using Appium.app|exe): `v10.3.0`
* Mobile platform/version under test: iOS `11.3`
* Real device or emulator/simulator: `simulator`
* Appium CLI or Appium.app|exe: `both`

## Details

I programatically tried tapping and clicking on the found element `Accessibility id = "Copy"` but nothing happens. When I opened up the inspector I tried both as well and nothing happened. However I finally was able to hit the copy button by using the `Tap by Coordinates` button on the inspector using the real screen coordinates from the screenshot and not the XML.

## Link to Appium logs

https://gist.github.com/ndinoia/85411cbb9d693c3613d9ea17d740f2c2

## Code To Reproduce Issue [ Good To Have ]

`driver.findElement(MobileBy.AccessibilityId("Copy")).click();`

![screen shot 2018-09-05 at 3 42 31 pm](https://user-images.githubusercontent.com/24900139/45117493-c90f6080-b123-11e8-8383-490320909086.png)

**Comment by mykola-mokhnach** [comment]
These coordinates are returned by XCTest. Please report the bug to Apple

**Comment by ndinoia** [comment]
@mykola-mokhnach not sure of the inner workings of appium but the parent element `ActivityListView` is showing the correct coordinates

**Comment by mykola-mokhnach** [comment]
I know. There is nothing that can be done on our side.

**Comment by ndinoia** [comment]
Ok, thanks for the quick response
