### ISSUE TITLE
Appium IOS Driver is not giving correct Page Source, not able to execute Driver.FindElements from an IOS App Console

### ISSUE THREAD

**Issue by nehacPyramid** [appium/appium#11327]
Appium IOS Driver is not giving correct Page Source from an IOS App Console after executing 'Driver.PageSource' method in C# language.

I am testing a Console app(native app) on a real IOS device wherein I am using appium to install and launch the app using the ipa file and setting the desired capabilities.
App is being launched successfully by the appium by creating appium's IOS driver instance, then my test-script executes a set of 242 commands on the console app which runs by a file already embedded in the ipa file.
After the commands execution completes, I am executing 'Driver.PageSource' method to fetch the page source in-order to validate the output of each command.
Issue 1: Page Source fetched after commands execution, is appearing in an 'XML' format in an arbitrary manner, as in the sequence of commands and its output is not in sync with the sequence executed on the app. All the nodes corresponding to each command and its output is showing descrepancies because of which, reading the page source is becoming challenging.
Issue 2: I tried executing 'Driver.FindElements' but it is showing 'Timeout' exception. Even after setting 'newCommandTimeout' to few minutes.
Issue 3: 'newCommandTimeout' capability doesn't seem to work at all.

## Environment

* Appium Desktop version 1.2.7
* Appium CLI v1.8.1
* OS version used to run Appium: macOS High Sierra Version-10.13.2
* Node.js version : 5.6.0
* Mobile platform/version under test: iOS, Version: 11.2
* Real device : iPhone 7

## Code To Reproduce Issue [ Good To Have ]

public static IWebDriver driver;
public static  RemoteWebDriver driver;  

//@ Initiating AppiumLocalService to start Appium server at the backend
AppiumLocalService AppiumService = AppiumLocalService.BuildDefaultService();

//@ Setting environment variables before starting the Appium server
//Environment.SetEnvironmentVariable(AppiumServiceConstants.NodeBinaryPath, objConfig.strNodeBinaryPath);
//Environment.SetEnvironmentVariable(AppiumServiceConstants.AppiumBinaryPath, objConfig.strAppiumBinaryPath);

//@ Starting Appium Server
AppiumService.Start();

if (!AppiumService.IsRunning)
{
	Thread.Sleep(5000);
}

DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.SetCapability("platformName", "iOS");
capabilities.SetCapability("platformVersion", "11.2");
capabilities.SetCapability("deviceName", "Kamlesh’s iPhone");
capabilities.SetCapability("automationName", "XCUITest");
capabilities.SetCapability("udid", "2415512fd124339aba74be71d682c5b589bb1f82");
capabilities.SetCapability("app", "/Users/nehachauhan/Documents/SocketMobileIOS/SocketMobile_IOS_Latest/TestData/IPAFile/CaptureConsole.ipa");
capabilities.SetCapability("noReset", true);
capabilities.SetCapability("clearSystemFiles", true);
capabilities.SetCapability("newCommandTimeout", 30000);
capabilities.SetCapability("waitForAppScript", "$.delay(5000); true");
capabilities.SetCapability("autoAcceptAlerts", true);
driver = new IOSDriver<IWebElement>(AppiumService, capabilities);
driver = new RemoteWebDriver(new Uri("http://127.0.0.1:4723/wd/hub"), capabilities);
driver = new IOSDriver<IWebElement>(new Uri("http://127.0.0.1:4723/wd/hub"), capabilities);

**Comment by mykola-mokhnach** [comment]
The actual page source is returned by WebDriverAgent/XCTest. There is nothing that can be changed there on Appium side. Please report your problem to https://github.com/facebook/WebDriverAgent

Also, make sure you use the most recent server version (preferably \@beta)

**Comment by nehacPyramid** [comment]
Hi,
Thank you so much for the information.
Can you please help me with the 'newCommandTimeOut' capability issue?
This doesn't seem to work and the test gives time out exception even after setting the same to '600000'.
Please help, stuck because of this issue :(

**Comment by mykola-mokhnach** [comment]
If you want to limit the maximum duration of command execution then you probably would like to use the `commandTimeouts` capability. There is also another limitation there. If WDA is stuck executing something then there is no way to continue the session. You must quit the session, restart WDA and start a new session. This means such capability is only useful to prevent unexpected freezes on the client side.

**Comment by nehacPyramid** [comment]
OK.
So if I restart WDA before every run, will it solve my problem?
My commands takes around a minute to execute for which I am using thread.sleep. But as soon as the command execution completes, Page Source is fetched which is throwing ''timed out after 60 seconds' exception.
I have set newCommandTimeOut to '60000'.
I am not sure what else is required.
Please help.

**Comment by nehacPyramid** [comment]
Hi mykola,

Thanks so much for the info.
I am using appium CLI version '1.8.1' and manually installing WDA on the real IOS device before starting the test.
Exception I am getting is 'The HTTP request to the remote WebDriver server for URL http://127.0.0.1:4723/wd/hub/session/460de234-a418-4056-aabf-24a55c24dfd4/source timed out after 60 seconds."'.
Can 'idleTimeOut' work in my case?

**Comment by mykola-mokhnach** [comment]
I wouldn't recommend to reinstall WDA very often. After several retries (depending on the device model and the amount of resources) it will refuse to run and it will be necessary to reboot the device.

Regarding the endpoint execution duration - try appium@beta and see if it works better there.
