### ISSUE TITLE
Tizen driver available commands do not work, exited with code 1'; Stderr: 'closed';

### ISSUE THREAD

**Issue by pkebets** [appium/appium#11326]
## The problem

The commands tizen driver offers us do not work. Every connection to real tizen device is followed by "Getting install status for 'appPackage'" command.  This and other available commands are executed over "sdb shell".
"sdb shell" is not supported neither by emulators not by real devices, unless real device has "debug firmware installed".
According to what I see from Appium server log, tizen driver executes 'sdb shell' scripts directly against device and throws "sdb shell ... exited with code 1'; Stderr: 'closed';". 
It will never work since it is blocked by firmware. The only way it could be done is over socket connection, I see some JS code related to socket connection but most likely the requests to the device are not going through the socket.
 
## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.0
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe):  5.6.0
* Mobile platform/version under test: Tizen 3.0, same behavior for Tizen 2.3 and Tizen 4.0
* Real device or emulator/simulator: Real Devices
* Appium CLI or Appium.app|exe:

## Link to Appium logs
[GIST](https://gist.github.com/pkebets/744005ddb510c3e91903547839344b85) 

## Code To Reproduce Issue [ Good To Have ]
To repro the issue it is enough to start Appium server 1.9.0 with capabilities 
{
  "appPackage": "sample",
  "deviceName": "Tizen",
  "platformName": "Tizen"
}

**Comment by KazuCocoa** [comment]
@pkebets 
Can you report it to https://github.com/Samsung/appium-tizen-driver ?
Since it looks happining in tizen driver and it's `appium-sdb` commands.

cc @flyofsky

**Comment by pkebets** [comment]
@KazuCocoa reported to appium-tizen-driver
https://github.com/Samsung/appium-tizen-driver/issues/10
please remove or close this one
