### ISSUE TITLE
'find-root' gets project root dynamically which breaks Webpack dependency resolution

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#11320]
*  If a project is built with Webpack (Appium Desktop is), to build the project, it crawls through the dependency tree and resolves dependencies statically
* The 'find-root' module is used at https://github.com/appium/appium/blob/7a00b3f875991ba1d95359ed53a3eda47911f64b/lib/parser.js which resolves the path dynamically
* This breaks Webpack builds because it can't resolve the dependency at compile-time

**Comment by mykola-mokhnach** [comment]
@dpgraham Is this still the case?

**Comment by dpgraham** [comment]
It is. I'll take this right now, thanks.

**Comment by mykola-mokhnach** [comment]
Closed as fixed

**Comment by boneskull** [comment]
I found [this old comment](https://github.com/appium/appium-desktop/blob/88e220481b857d410e63a0e049ca113bf9bdef84/app/main/appium.js#L117-L124) in `appium-desktop` in reference to this issue.  Given it has sat so long, maybe nobody missed it?  It's unclear what the "feature" even is. @jlipps @dpgraham ?

**Comment by jlipps** [comment]
it must be appium desktop. but we moved from webpack to parcel so i don't think it's an issue anymore either.
