### ISSUE TITLE
Alert - Send keys incorrect parameters sent

### ISSUE THREAD

**Issue by jlegorburuJC** [appium/appium#11323]
## The problem

When i try to use the command `alert.send_keys("Some text")` an exception is raised with the following messge.
`InvalidArgumentException: Message: Parameters were incorrect. We wanted {"required":["text"]} and you sent ["text","sessionId","value"]`

## Environment

* Appium version: v1.9.0
* Node.js version: v9.3.0
* iOS
* Real Device
* Appium CLI

## Link to Appium logs
https://gist.github.com/jlegorburuJC/ca0ee8b2f724c224f4da1bc590bae5f1

**Comment by dpgraham** [comment]
What client are you using?

This looks like an Appium W3C bug.

**Comment by jlegorburuJC** [comment]
Im using Appium-Python-Client-0.28

**Comment by jlegorburuJC** [comment]
what should i update to see the fix?

**Comment by dpgraham** [comment]
```
npm uninstall -g appium
npm install appium@1.9.1-beta2
```

This will give you the latest beta that has the fix

**Comment by dpgraham** [comment]
Let me know if it works. If it does we can close this issue.

**Comment by jlegorburuJC** [comment]
yes this is fixed. Im also having other issue with the Alerts. When i do `driver.switch_to.alert` and there is no Alert present it does not raise an exception it returns an alert with this text
`{u'protocol': u'W3C', u'error': {u'_stacktrace': None, u'w3cStatus': 404, u'jsonwpCode': 27, u'error': u'no such alert'}}`

**Comment by dpgraham** [comment]
It's supposed to throw an exception when the payload looks like that. Can you post the server logs?

^ @KazuCocoa is this a python client error?

**Comment by jlegorburuJC** [comment]
https://gist.github.com/jlegorburuJC/ca0ee8b2f724c224f4da1bc590bae5f1#file-appium-log-L183

**Comment by mykola-mokhnach** [comment]
Yes it would be better to open a new issue report. Also, I observe the server version in the log is still 19.0. Can you please try it with 1.9.1-beta2?

**Comment by mykola-mokhnach** [comment]
@jlegorburuJC If the flow still fails with appium@beta then please edit 

https://github.com/appium/appium-base-driver/blob/eee6d6ddd1700311a6f6f34b75dfbd1664ccc60b/lib/protocol/protocol.js#L283

and insert 

```
      log.debug(JSON.stringify(driverRes));
      log.debug(JSON.stringify(parsedDriverRes));
```

after this line.

Execute `gulp transpile` in order to transpile your changes and restart appium. This will help us a lot to catch the problem if it exists.
