### ISSUE TITLE
Alert - Does not raise exception when its not present

### ISSUE THREAD

**Issue by jlegorburuJC** [appium/appium#11334]
## The problem
When i use `driver.switch_to.alert` and there is no Alert present it does not raise an exception it returns an alert with this text
`{u'protocol': u'W3C', u'error': {u'_stacktrace': None, u'w3cStatus': 404, u'jsonwpCode': 27, u'error': u'no such alert'}}`

I made the changes mentioned by @mykola-mokhnach here https://github.com/appium/appium/issues/11323#issuecomment-419332704

## Environment
Appium version: v1.9.1-beta2
Node.js version: v9.3.0
iOS 
Real Device
Appium-Python-Client-0.28

## Link to Appium logs

https://gist.github.com/jlegorburuJC/3632e9b35a73920d89e20c6e53411b54

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium-base-driver/pull/256 should resolve your problem. You could also try it locally
