### ISSUE TITLE
How to get real device screen size (Viewport)

### ISSUE THREAD

**Issue by cswarnan** [appium/appium#11333]
## The problem

I am doing mobile automation, and trying to get mobile viewport size to put some conditional checks. But there is no way I can get that size. I can retrieve pixel size of the device by doing driver.desired_capabilities[u'deviceScreenSize'].split('x'), But I need viewport size

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1 beta
* Last Appium version that did not exhibit the issue (if applicable): Not known
* Desktop OS/version used to run Appium: iOS
* Node.js version (unless using Appium.app|exe): v10.1.0
* Mobile platform/version under test: Android 8
* Real device or emulator/simulator: Real device

## Details

I need to know if there is any way we can get viewport size of real device.

Need urgent help on this.
Thanks

**Comment by mykola-mokhnach** [comment]
You can get the real screen size from adb. See https://stackoverflow.com/questions/7527459/how-to-get-the-android-device-screen-size-from-the-adb-command-line and https://github.com/appium/appium/blob/ff6b3a16f807fe8c7046a27726fe1a54dc85cf3f/docs/en/writing-running-appium/android/android-shell.md

Please use appium forum for questions
