### ISSUE TITLE
Click not working in Hybrid ionic app on iOS devices

### ISSUE THREAD

**Issue by KrazySush** [appium/appium#11337]
## The problem

Click method is not working on webelements in ionic hybrid apps for iOS devices(It is working fine for Android devices). While runnnig tests, click() method is executed without error but no action is performed for iOS device.
Tried with "nativeWebTap" capability, but it is not working accurately. It is clicking element below expected element.

## Environment

* Appium version : 1.9.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS High Sierra (latest)
* Node.js version (unless using Appium.app|exe): latest
* Mobile platform/version under test: iOS 10, iOS 11
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

**Comment by mykola-mokhnach** [comment]
Please attach full server log.

I would try to perform click with custom javascript.

It might be that Appium's click does not trigger the event expected by your application under test. Just track which events are generated on manual click and compare them with the automated one.
