### ISSUE TITLE
What is the strategy choosing port 8201 or 8200

### ISSUE THREAD

**Issue by Dan2712** [appium/appium#11345]
## The problem

I'm working on a test case, and in the case the device needs to reboot one time. After rebooting and re-init appium, some findelement proxy post to port 8200 works well, while to port 8201 always get the connect ECONNREFUSED error. So I wanna some help to know the choosing strategy, and how to re-init port 8201(cus I think the port is still dead)
Many thx!

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 7
* Node.js version (unless using Appium.app|exe): 5.6.0
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Link to Appium logs

https://gist.github.com/Dan2712/9ef30a9885e522a7ab3eafe907c2f3ba

**Comment by KazuCocoa** [comment]
Port 82xxx are used by `systemPort` in http://appium.io/docs/en/writing-running-appium/caps/ . It's used to communicate with `appium-uiautomator2-server`.

In your case, you establish connections with below Appium servers with default `systemPort`, right?

Appium 1. `http://localhost:8200/wd/hub/` 
Appium 2.  `http://localhost:8201/wd/hub/`

In the case, I guess port conclicts can happen between the session and `systemPort`.
What about specifying `systemPort` to avoid them?


----

Appium logs help us to understand/guide your capabilities.

**Comment by Dan2712** [comment]
Specifying port seems work fine after 100 times running! Many thx about this, and can close the issue
