### ISSUE TITLE
Signature issue under Mobile Automation 

### ISSUE THREAD

**Issue by RohitrajElpis** [appium/appium#11349]
HI @KazuCocoa one issue i am facing , need to automate Signature . we have a one option where we need to do signature for approval . But there is no locators for that field's , so please help me out how can pass signature to move further step  . please follow screen shot and locators FUR.

1.
![sighnature](https://user-images.githubusercontent.com/43004068/45357221-4420bd00-b5e3-11e8-843a-75c6173b0654.JPG)

1.1.![signature 2](https://user-images.githubusercontent.com/43004068/45357181-1e93b380-b5e3-11e8-9570-1033cb7947d1.JPG)

2.![locator 1](https://user-images.githubusercontent.com/43004068/45357109-ed1ae800-b5e2-11e8-9500-974c6ce949e4.JPG)
3.![locators 2](https://user-images.githubusercontent.com/43004068/45357110-ed1ae800-b5e2-11e8-9f5c-a883769aec59.JPG)

**Comment by mykola-mokhnach** [comment]
This is not a server issue. Please report to Appium forum

**Comment by RohitrajElpis** [comment]
hi @mykola-mokhnach 
it's relay important to me know about forum can you  please send me link where i can create forum login and create issue so i can get result soon , please do need full help.

![forum](https://user-images.githubusercontent.com/43004068/45360377-02950f80-b5ed-11e8-983f-f17f647b0e79.JPG)
 according to your comment i am not getting any option to 
1.login to forum 
2.creation new topic 
3.support category
4,rasing issue

**Comment by mykola-mokhnach** [comment]
This link is stated in the repotting template: https://discuss.appium.io

**Comment by RohitrajElpis** [comment]
tq @mykola-mokhnach i will ask my question there

**Comment by RohitrajElpis** [comment]
HI @mykola-mokhnach  @KazuCocoa  i have created New topic as support category please do need full help

https://discuss.appium.io/t/signature-issue-under-mobile-automation/23523
