### ISSUE TITLE
Accessibilty id is blank in appium inspector for iphone 6s plus

### ISSUE THREAD

**Issue by shagupta92042** [appium/appium#11340]
## The problem

we are automating the hybrid app for iOS which we are running on iPhone6s Plus. I am using appium inspector to view the elements but we are not getting the accessibility id in the viewer . Developers are using HTML5 and we are not sure which tag will populate the accessibility id.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MAC OS 10.13.2
* Node.js version (unless using Appium.app|exe):  
* Mobile platform/version under test:  11.4.1
* Real device or emulator/simulator:  Real device iPhone6sPlus
![screen shot 2018-09-10 at 3 16 49 pm](https://user-images.githubusercontent.com/18581259/45290511-6a742900-b50d-11e8-9d2d-365a7434bd10.png)
* Appium CLI or Appium.app|exe: appium inspector

## Details

please suggest which tag we must use so that accessibility id would be populated. please check the screenshot for more info.

**Comment by shagupta92042** [comment]
![c2a0d9004f86c511483d75c5841f1fe49cdbde075e18f3db06 pimgpsh_thumbnail_win_distr](https://user-images.githubusercontent.com/18581259/45290386-16694480-b50d-11e8-888b-ac7c4a634009.jpg)

**Comment by shagupta92042** [comment]
![screen shot 2018-09-10 at 3 16 49 pm](https://user-images.githubusercontent.com/18581259/45290473-4b759700-b50d-11e8-981c-85bdbc18a237.png)

**Comment by mykola-mokhnach** [comment]
Appium inspector is not applicable for web views. Use Remote Safari debugger in order to inspect them. Aslo check http://appium.io/docs/en/writing-running-appium/web/hybrid/ for more details.

Closed as not an issue

**Comment by shagupta92042** [comment]
Actually we are not automating or testing it through browser as it is a hybrid app so we are automating it after launching the app and we are using the Appium to automate it . Safari debugger wont work in this case.
