### ISSUE TITLE
showXcodeLog cap == false but although prints xcode logs

### ISSUE THREAD

**Issue by derunewige** [appium/appium#11347]
## The problem

The showXcodeLog capability is FALSE, but random in the middle of a test the console starts printing xcode logs.
in the added gist it starts at timestamp 2018-09-11 09:16:30:253

## Environment

Appium version (or git revision) that exhibits the issue: 1.9.1-beta2
Last Appium version that did not exhibit the issue (if applicable): 1.8.1
Desktop OS/version used to run Appium: MacOs 10.13.6
Node.js version (unless using Appium.app|exe): node 10.10.0; npm 6.4.1
Mobile platform/version under test: iOS 12
Real device or emulator/simulator: real device
Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

[GIST](https://gist.github.com/derunewige/c48d4155677d57a47384c5c6365a7de8)

**Comment by mykola-mokhnach** [comment]
I assume it is by design: https://github.com/appium/appium-xcuitest-driver/blob/55b8860ef9a3f8e9c32d40842e8bf4a7d959b214/lib/wda/xcodebuild.js#L249

**Comment by derunewige** [comment]
Thank you!!

**Comment by ddubtsov35** [comment]
@mykola-mokhnach  Appium v1.12.1. This problem also. Is there a way not to output the log?

**Comment by KazuCocoa** [comment]
`skipLogCapture` can help, i think
https://github.com/appium/appium-xcuitest-driver

**Comment by ddubtsov35** [comment]
@KazuCocoa  this didn't help me
