### ISSUE TITLE
iOS 12 Support

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#11351]

**Comment by dpgraham** [comment]
Results of `/functional/basic` test run: https://gist.github.com/dpgraham/df35ceedee4ca13d2b4de039d287933a

**Comment by imurchie** [comment]
Yes, scrolling doesn't work, so many of the tests are borked.

**Comment by dpgraham** [comment]
@imurchie I think it's because of this: https://github.com/appium/appium/issues/11352

Scrolling is broken only when we use predicate selector.

**Comment by imurchie** [comment]
In my investigation it internal to the `XCElementSnapshot#hitTest`.

**Comment by mykola-mokhnach** [comment]
@imurchie Could you please try if https://github.com/appium/WebDriverAgent/pull/115 works for you?

**Comment by dpgraham** [comment]
@mykola-mokhnach I just tried it and it's working now!

**Comment by imurchie** [comment]
Continues to work with Xcode 10 RC.
