### ISSUE TITLE
Location keeps jumping from test location to real location

### ISSUE THREAD

**Issue by sowri** [appium/appium#11353]
## The problem

setLocation sets the new location for a second and them jumps Back to my real location

## Environment

* Appium version (or git revision) that exhibits the issue:
* Node.js version (unless using Appium.app|exe): 1.8.1
* Mobile platform/version under test: Android
* Real device 

## Details

The way I see this I have my Appium Test Running for the app in background , Open Maps to see where my current location is.It keep on jumping to the location set in the Appium Test and the real location.

**Comment by dpgraham** [comment]
Can you provide the logs

**Comment by dpgraham** [comment]
The logs may still help us see why it changed to the real location.

**Comment by dpgraham** [comment]
Also, the `logcat` logs would be helpful.

**Comment by mykola-mokhnach** [comment]
No logs - no luck

**Comment by xlenz** [comment]
same for me

**Comment by xlenz** [comment]
@mykola-mokhnach appium sets location like this on my Android device (pixel 2, android 9)
`/usr/local/share/android-sdk/platform-tools/adb -P 5037 -s FA8131A03509 shell am startservice -e longitude 0 -e latitude 51 io.appium.settings/.LocationService`

however after couple of settings location is updated to real one. 
I don't have such problem with Fake Gps app. Maybe I'm missing some special configuration or something?

**Comment by mykola-mokhnach** [comment]
This problem might be fixed by https://github.com/appium/io.appium.settings/pull/35

**Comment by xlenz** [comment]
@mykola-mokhnach might be, however there is another issue on Oreo and later.
```
[0-0] 2019-01-23T15:14:33.581Z ERROR webdriver: Request failed due to Error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: ‘Command ‘/usr/local/share/android-sdk/platform-tools/adb -P 5037 -s FA8131A03509 shell am startservice -e longitude 0 -e latitude 51 io.appium.settings/.LocationService’ exited with code 255'; Stderr: ‘Error: app is in background uid UidRecord{a8f8455 u0a198 CEM  bg:+1m31s436ms idle change:cached procs:1 seq(0,0,0)}’; Code: ‘255’
```

We have to use start-foreground-service on devices with Oreo and later. Looks like appium is sending this command, not Appium Settings.

Shall I rise a ticket for this?
