### ISSUE TITLE
Appium 1.9.0 fails on find_element with ruby client

### ISSUE THREAD

**Issue by l0gg3r** [appium/appium#11354]
## The problem

Ruby selenium-webdriver 3.14.0 fails on `driver.find_element`
```
Failure/Error: driver.find_element(class: 'UIAButton').click     
  Selenium::WebDriver::Error::InvalidSelectorError:
    Locator Strategy 'css selector' is not supported for this session
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.0
* Last Appium version that did not exhibit the issue (if applicable): 1.8.1
* Desktop OS/version used to run Appium: OSX
* Node.js version (unless using Appium.app|exe): 8.6.0
* Mobile platform/version under test: 11.3 / Xcode 10
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs
![Logs](https://preview.ibb.co/hHrG79/Screen_Shot_2018_09_12_at_12_15_30_AM.png)
## Code To Reproduce Issue [ Good To Have ]

```
def driver_for(capabilities)
  client = Selenium::WebDriver::Remote::Http::Default.new
  client.read_timeout = 180
  options = {
    http_client: client,
    url: "http://localhost:4723",
    desired_capabilities: capabilities
  }
  Selenium::WebDriver.for :remote, options
end

describe "#{caps['deviceName']}, #{caps['platformName']} #{caps['platformVersion']}", :iphone, :ipad do
  it 'loads the UI' do
    driver = driver_for caps
    driver.find_element(class: 'UIAButton').click
    label = driver.find_element(class: 'UIAStaticText')
    expect(label.text).to eql '0'
  end
end
```

**Comment by KazuCocoa** [comment]
Did you use https://github.com/appium/ruby_lib ?

The pure selenium-webdriver convert some locators to css. In Appium clients include Ruby client have removed the convertor.

**Comment by luizlohn** [comment]
I`m with this problem too 
My code:
  def wait_element_class(element)
    $driver.wait { find_element :class, element }
  end

SHow me:
[HTTP] --> POST /wd/hub/session/4827e80f-0081-4b9b-9b3a-b85f267c48e7/element
[HTTP] {"using":"css selector","value":".android\\.support\\.v4\\.view\\.ViewPager"}

But I`m using class name
@KazuCocoa
