### ISSUE TITLE
iOS 12: Predicate String selector is broken

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#11352]
## The problem

The predicate string selector doesn't work on iOS 12. It gets stuck and tests time out. This is a problem both for element selectors and for `mobile: scroll` when it uses `toVisible` parameter

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.0
* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium: Mac OS High Sierra 10
* Node.js version (unless using Appium.app|exe): 10
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: iOS 12.0 (beta) Simulator
* Appium CLI or Appium.app|exe: CLI

## Details

* See https://gist.github.com/dpgraham/df35ceedee4ca13d2b4de039d287933a for sample test results)
* Here's the error logs with the Xcode logs: https://gist.github.com/dpgraham/36eaab326015b68e8c84bf51d973745d
* Looks like it's an Objective-C error

```
info Xcode Exception: value for key 'NS.objects' was of unexpected class 'XCAccessibilityElement'. Allowed classes are '{(
info Xcode     NSDictionary,
info Xcode     NSDate,
info Xcode     NSSet,
info Xcode     NSOrderedSet,
info Xcode     NSString,
info Xcode     NSNumber,
info Xcode     NSArray,
info Xcode     NSData,
info Xcode     NSNull
info Xcode )}'.
```

## Code To Reproduce Issue [ Good To Have ]

Run any mocha tests that use predicate string

**Comment by mykola-mokhnach** [comment]
@Dan-Maor Do you have any ideas on how this can be fixed?

**Comment by dpgraham** [comment]
This isn't happening anymore. I think @imurchie's fix worked.
