### ISSUE TITLE
Android 8.0 driver.getPageSource() Failed

### ISSUE THREAD

**Issue by yifei325325** [appium/appium#11355]
## The problem
first i run the program on Android 8.0
My program find a button element on the app to click, then a confirm dialog pops up. click the 'Ok' button，the dialog disappeared. the app shows the last view before pops up. but now driver.getPageSource() with no response BTW driver.getElementById() can not work either. and i tried before the dialog pops up , i run driver.getPageSource() or driver.getElementById(), they works.

I have another Phone is  Android 6.0, the same code run properly at the Android 6.0 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:1.7.0
* Node.js version (unless using Appium.app|exe):8.12.0
* Mobile platform/version under test:Android 8.0
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe: Appim CLI

## Link to Appium logs

Here is my codes and logs:
https://gist.github.com/yifei325325/a319b20ffefc27743ad1fcaf0913f6ab

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Switch to UiAutomator2. Closed as duplicate
