### ISSUE TITLE
Does Appium support CEF based desktop application automation for windows ? 

### ISSUE THREAD

**Issue by MuhammadzaibLiquidsky** [appium/appium#11366]
I have a Chromium embedded framework windows application to automate tests on, im able to open it with appium and perform enter key to skip intro but nothing after that.

**Comment by mykola-mokhnach** [comment]
I would say it does not. Most likely you need to create two drivers - one for native context and the other for web context and interact with then both at the same time.

**Comment by MuhammadzaibLiquidsky** [comment]
> I would say it does not. Most likely you need to create two drivers - one for native context and the other for web context and interact with then both at the same time.

can you give any example for that? to lead me in right direction. would greatly appreciate

**Comment by mykola-mokhnach** [comment]
I don't have any examples. It was just an assumption

**Comment by dpgraham** [comment]
@MuhammadzaibLiquidsky I would recommend discuss.appium.io for help with that.

**Comment by dpgraham** [comment]
@MuhammadzaibLiquidsky To add to that, I would bring this issue up with the WinAppDriver team as a feature request to implement `contexts` so that you can debug webviews in windows apps.
