### ISSUE TITLE
appium-xcuitest-driver, web.js: Misleading error thrown by waitForAtom()

### ISSUE THREAD

**Issue by pedropaco** [appium/appium#11367]
## The problem

I encountered an error in the appium server output that suggested something timed out after 300 seconds (error below). This error is incorrect, the timeout was from webkitResponseTimeout being exceeded (which was default five seconds). Using ATOM_WAIT_TIMEOUT in the exception message was confusing.

```
[debug] [RemoteDebugger] Webkit response timeout: 5000
[W3C] Encountered internal error running command: Error: Did not get any response after 300s
[W3C]     at XCUITestDriver.callee$0$0$ (/Users/crexi/.virtualenvs/webdriver/lib/node_modules/appium-xcuitest-driver/lib/commands/web.js:284:13)
[W3C]     at tryCatch (/Users/crexi/.virtualenvs/webdriver/lib/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/crexi/.virtualenvs/webdriver/lib/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/crexi/.virtualenvs/webdriver/lib/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[W3C]     at GeneratorFunctionPrototype.invoke (/Users/crexi/.virtualenvs/webdriver/lib/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session/a632dadd-3e32-471a-ab48-a58d692abcb8/element 500 8431 ms - 1283
```

## Environment

* master branch, https://github.com/appium/appium-xcuitest-driver/commit/f5267acab3bc9285161397fa19a8daf60ae0c6ae
* Mobile platform/version under test: ios
* Real device or emulator/simulator: real device

## Details
Problematic line: https://github.com/appium/appium-xcuitest-driver/commit/f5267acab3bc9285161397fa19a8daf60ae0c6ae

**Comment by mykola-mokhnach** [comment]
Thanks for the report. Feel free to push a fix for it

**Comment by mykola-mokhnach** [comment]
the patch has been merged to beta
