### ISSUE TITLE
Could not start session in appium desktop v1.9.0

### ISSUE THREAD

**Issue by archanarathnam** [appium/appium#11365]
I am getting error saying "Could not start session"

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.0
* Desktop OS/version used to run Appium: Windows 10
* Mobile platform/version under test: 8.0.0
* Real device or emulator/simulator: Real device

## Details

Have added the following capabilities as per below image
![image](https://user-images.githubusercontent.com/37412798/45558916-f8675100-b838-11e8-8ada-f163185f6a5b.png)

Squid proxy server is running in the background with port 3128

When I try to access http://localhost:4723/wd/hub/status, I am getting below response -
**{"status":0,"value":{"build":{"version":"1.9.0"}},"sessionId":null}**

but when I start session in appium desktop, it says Error:Could not start session

Can you please let me know why this is happening.

**Comment by mykola-mokhnach** [comment]
Please use appium forum discuss.appium.io for question. Your problem is not a server issue.
