### ISSUE TITLE
I cant run tests on my Android app

### ISSUE THREAD

**Issue by adrirrFOS** [appium/appium#11360]
## The problem

Just trying to run and click on an element and it is not working. The app starts in the emulator and nothing happens afterwards.
Using Appium Inspector Session, there is no problem to click on the elements.

## Environment

* Appium version: 1.9.0
* Desktop OS/version used to run Appium: macOs High Sierra - 10.13.4
* Node.js version: v8.11.3
* Mobile platform/version under test: Android
* Real device or emulator/simulator: emulator (Nexus_5X_API_28)

## Code To Reproduce Issue [ Good To Have ]

`
const wdio = require('webdriverio');
const caps = {"app":"/Users/adrianareigadas/Documents/Projects/yourmapp/yourmapp-android/app/build/outputs/apk/cherrystoneProduction/debug/cherrystoneProductionDebug-2.4.6.apk","deviceName":"Android Emulator","automationName":"UiAutomator2","platformName":"Android","appActivity":"com.bespokesoftware.yourmapp.android.view.StartupActivity_","appPackage":"com.bespokesoftware.yourmapp.android.cherrystone"};
const driver = wdio.remote({
  protocol: "http",
  host: "localhost",
  port: 4723,
  path: "/wd/hub",
  desiredCapabilities: caps
});

driver.init()
  .touchAction({actions: 'tap', x: 766, y: 1041})
  .touchAction({actions: 'tap', x: 999, y: 197})
  .back()
  .end();
[appium-server-logs.txt](https://github.com/appium/appium/files/2379021/appium-server-logs.txt)
`

**Comment by mykola-mokhnach** [comment]
> [info] [HTTP] --> POST /wd/hub/session/7f59fe3a-e1d4-4718-b7da-9bb65f12edc0/touch/perform
> [info] [HTTP] {"actions":[{"options":{"x":766,"y":1041}}]}
> [debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"options":{"x":766,"y":1041}}],"7f59fe3a-e1d4-4718-b7da-9bb65f12edc0"]
> [error] [AndroidDriver] Error: unknown action undefined
> [error] [AndroidDriver]     at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)

Make sure you pass the correct parameters to touch action.

Closed as not an issue
