### ISSUE TITLE
Android - Scroll

### ISSUE THREAD

**Issue by adrirrFOS** [appium/appium#11376]
## The problem

How to scroll in a Android app?

## Environment

* Development: javascript / webdriver.io
* Appium version : 1.9.0
* On macOs High Sierra: 10.13.4
* Node.js version: 8.11.3
* automationName: UiAutomator2
platformName: android

## Details

Want to scroll to an element off the view.
Ex:
client.click("new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().text(\"RV SERVICES\").instance(0))")

## Link to Appium logs
'
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8208/wd/hub/session/a4d76602-2255-4c5a-8567-94d958b94095/element] with body: {"strategy":"xpath","selector":"/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.RelativeLayout/android.widget.FrameLayout[1]/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View[1]/android.view.View/android.view.View/android.view.View[3]/android.view.View/android.view.View[4]/android.view.View/android.view.View[1]","context":"","multiple":false}[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"a4d76602-2255-4c5a-8567-94d958b94095","status":0,"value":{"ELEMENT":"69e25e6c-631e-4528-974b-740881cdfbfb"}}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"69e25e6c-631e-4528-974b-740881cdfbfb"}
[info] [HTTP] <-- POST /wd/hub/session/9fd4bd8d-eaf2-4f43-88af-0b3dbe7cd4b6/element 200 581 ms - 122
[info] [HTTP] 
[info] [HTTP] --> POST /wd/hub/session/9fd4bd8d-eaf2-4f43-88af-0b3dbe7cd4b6/element/69e25e6c-631e-4528-974b-740881cdfbfb/click
[info] [HTTP] {}
[debug] [MJSONWP] Calling AppiumDriver.click() with args: ["69e25e6c-631e-4528-974b-740881cdfbfb","9fd4bd8d-eaf2-4f43-88af-0b3dbe7cd4b6"]
[debug] [JSONWP Proxy] Matched '/element/69e25e6c-631e-4528-974b-740881cdfbfb/click' to command name 'click'
[debug] [JSONWP Proxy] Proxying [POST /element/69e25e6c-631e-4528-974b-740881cdfbfb/click] to [POST http://localhost:8208/wd/hub/session/a4d76602-2255-4c5a-8567-94d958b94095/element/69e25e6c-631e-4528-974b-740881cdfbfb/click] with body: {"element":"69e25e6c-631e-4528-974b-740881cdfbfb"}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"a4d76602-2255-4c5a-8567-94d958b94095","status":0,"value":true}
[debug] [MJSONWP] Responding to client with driver.click() result: true
[info] [HTTP] <-- POST /wd/hub/session/9fd4bd8d-eaf2-4f43-88af-0b3dbe7cd4b6/element/69e25e6c-631e-4528-974b-740881cdfbfb/click 200 37 ms - 76
[info] [HTTP] 
[info] [HTTP] --> POST /wd/hub/session/9fd4bd8d-eaf2-4f43-88af-0b3dbe7cd4b6/back
[info] [HTTP] {}
[info] [MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Matched '/wd/hub/session/9fd4bd8d-eaf2-4f43-88af-0b3dbe7cd4b6/back' to command name 'back'
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/9fd4bd8d-eaf2-4f43-88af-0b3dbe7cd4b6/back] to [POST http://localhost:8208/wd/hub/session/a4d76602-2255-4c5a-8567-94d958b94095/back] with body: {}[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"a4d76602-2255-4c5a-8567-94d958b94095","status":0,"value":true}
[info] [JSONWP Proxy] Replacing sessionId a4d76602-2255-4c5a-8567-94d958b94095 with 9fd4bd8d-eaf2-4f43-88af-0b3dbe7cd4b6
[info] [HTTP] <-- POST /wd/hub/session/9fd4bd8d-eaf2-4f43-88af-0b3dbe7cd4b6/back 200 1592 ms - 76
[info] [HTTP] 
[info] [HTTP] --> POST /wd/hub/session/9fd4bd8d-eaf2-4f43-88af-0b3dbe7cd4b6/element
[info] [HTTP] {"using":"css selector","value":"new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().text(\"RV SERVICES\").instance(0))"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["css selector","new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().text(\"RV SERVICES\").instance(0))","9fd4bd8d-eaf2-4f43-88af-0b3dbe7cd4b6"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[error] [MJSONWP] Encountered internal error running command: InvalidSelectorError: Locator Strategy 'css selector' is not supported for this session
[error] [MJSONWP]     at AndroidUiautomator2Driver.validateLocatorStrategy (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:349:13)
[error] [MJSONWP]     at AndroidUiautomator2Driver.callee$0$0$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:26:8)
[error] [MJSONWP]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[error] [MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[error] [MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[error] [MJSONWP]     at invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[error] [MJSONWP]     at enqueueResult (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
[error] [MJSONWP]     at new Promise (<anonymous>)
[error] [MJSONWP]     at new F (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
[error] [MJSONWP]     at AsyncIterator.enqueue (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
[error] [MJSONWP]     at AsyncIterator.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[error] [MJSONWP]     at Object.runtime.async (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
[error] [MJSONWP]     at AndroidUiautomator2Driver.callee$0$0 [as findElOrElsWithProcessing] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/build/lib/basedriver/commands/find.js:47:30)
[error] [MJSONWP]     at AndroidUiautomator2Driver.callee$0$0$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:46:21)
[error] [MJSONWP]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[error] [MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[error] [MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[error] [MJSONWP]     at invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[error] [MJSONWP]     at enqueueResult (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
[error] [MJSONWP]     at new Promise (<anonymous>)
[error] [MJSONWP]     at new F (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
[error] [MJSONWP]     at AsyncIterator.enqueue (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
[error] [MJSONWP]     at AsyncIterator.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[error] [MJSONWP]     at Object.runtime.async (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
[error] [MJSONWP]     at AndroidUiautomator2Driver.callee$0$0 [as findElement] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/build/lib/basedriver/commands/find.js:88:30)
[error] [MJSONWP]     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:296:26
[error] [MJSONWP]     at tryCatcher (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/util.js:26:23)
[error] [MJSONWP]     at Promise._settlePromiseFromHandler (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/promise.js:510:31)
[error] [MJSONWP]     at Promise._settlePromiseAt (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/promise.js:584:18)
[error] [MJSONWP]     at Promise._settlePromiseAtPostResolution (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/promise.js:248:10)
[error] [MJSONWP]     at Async._drainQueue (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/async.js:128:12)
[error] [MJSONWP]     at Async._drainQueues (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/async.js:133:10)
[error] [MJSONWP]     at Immediate.Async.drainQueues [as _onImmediate] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/async.js:15:14)
[error] [MJSONWP]     at runCallback (timers.js:789:20)
[error] [MJSONWP]     at tryOnImmediate (timers.js:751:5)
[error] [MJSONWP]     at processImmediate [as _immediateCallback] (timers.js:722:5)
[info] [HTTP] <-- POST /wd/hub/session/9fd4bd8d-eaf2-4f43-88af-0b3dbe7cd4b6/element 500 6 ms - 152
[info] [HTTP] 
[info] [HTTP] --> DELETE /wd/hub/session/9fd4bd8d-eaf2-4f43-88af-0b3dbe7cd4b6
[info] [HTTP] {}
[debug] [MJSONWP] Calling AppiumDriver.deleteSession() with args: ["9fd4bd8d-eaf2-4f43-88af-0b3dbe7cd4b6"]
[debug] [BaseDriver] Event 'quitSessionRequested' logged at 1537193617652 (15:13:37 GMT+0100 (BST))
[info] [Appium] Removing session 9fd4bd8d-eaf2-4f43-88af-0b3dbe7cd4b6 from our master session list
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[debug] [JSONWP Proxy] Matched '/' to command name 'deleteSession'
[debug] [JSONWP Proxy] Proxying [DELETE /] to [DELETE http://localhost:8208/wd/hub/session/a4d76602-2255-4c5a-8567-94d958b94095] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"a4d76602-2255-4c5a-8567-94d958b94095\",\"status\":0,\"value\":\"Session deleted\"}"
[debug] [ADB] Running '/Users/adrianareigadas/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop com.bespokesoftware.yourmapp.android.cherrystone'
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8208 
[debug] [ADB] Running '/Users/adrianareigadas/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp\:8208'
[debug] [BaseDriver] Event 'quitSessionFinished' logged at 1537193617773 (15:13:37 GMT+0100 (BST))
[debug] [MJSONWP] Received response: null
[debug] [MJSONWP] But deleting session, so not returning
[debug] [MJSONWP] Responding to client with driver.deleteSession() result: null
[info] [HTTP] <-- DELETE /wd/hub/session/9fd4bd8d-eaf2-4f43-88af-0b3dbe7cd4b6 200 126 ms - 76
[info] [HTTP] [debug] [UiAutomator2] [UIAutomator2] io.appium.uiautomator2.server.test.AppiumUiAutomator2Server:.
[debug] [UiAutomator2] [UIAutomator2] Time: 46.084
[debug] [UiAutomator2] [UIAutomator2] OK (1 test)
'

**Comment by adrirrFOS** [comment]
So, how to scroll?

**Comment by mykola-mokhnach** [comment]
There is discuss.appium.io for questions. This is the place for issues only.,
