### ISSUE TITLE
appium-windows-driver published npm version does not match published Github version.

### ISSUE THREAD

**Issue by jamie-sherriff** [appium/appium#11372]
Hi, 

I have noticed for appium-windows-driver the GitHub Source code does not match the npm published source code (Github has your package.json version at 1.2.0) and npm has a published version of 1.2.1. From what I can tell the WAD_VER (in appium-windows-driver/lib/installer.js)   is set to 1.0 in 1.2.1 and 1.1-RC in 1.2.0, this is very confusing.

I am comparing https://www.npmjs.com/package/appium-windows-driver and https://github.com/appium/appium-windows-driver

Would this mean someone has published with local changes and has not pushed them? If so can you please publish the same source code to GitHub that has been published to npm?

Thanks

**Comment by KazuCocoa** [comment]
ah... 
@imurchie do you have any idea?
I think we haven't published 1.2.1 since I can't see any commit about 1.2.1 in https://github.com/appium/appium-windows-driver/commits/master ...

**Comment by imurchie** [comment]
Yes, this means it was published but the commit with the version was not pushed. Not sure who did that, but it's not uncommon.

Both ought to be at 1.3.0 now.

**Comment by KazuCocoa** [comment]
```
+ appium-windows-driver@1.3.0
```

https://www.npmjs.com/package/appium-windows-driver

**Comment by jamie-sherriff** [comment]
Thanks guys!
