### ISSUE TITLE
Appium Inspector - Unexpected Element Tree for iOS React Native Application

### ISSUE THREAD

**Issue by mgraf0** [appium/appium#11379]
## The problem

Testing a react native application on both the Android and iOS platform.  For android the element tree seems to be fine.  For iOS the element tree for the app is just a single element.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.0
* Desktop OS/version used to run Appium: MacOS
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: iOS XCode Simulator
* Appium.app

## Details
iOS Element Tree
![image](https://user-images.githubusercontent.com/4855390/45645941-fea33a80-ba8f-11e8-91af-37ae5bb0c7b1.png)

Android Element Tree
![image](https://user-images.githubusercontent.com/4855390/45651632-f94dec00-ba9f-11e8-9e1f-0c76b2116fce.png)

**Comment by mykola-mokhnach** [comment]
The actual page source is generated by WebDriverAgent/XCTest and Appium itself has nothing to do with that. Try to debug and interact with webviews in [webview context](http://appium.io/docs/en/writing-running-appium/web/hybrid/) instead of native.

Closed as third party problem.
