### ISSUE TITLE
Parallel iOS/Android.

### ISSUE THREAD

**Issue by AvrahamAtia** [appium/appium#11370]
## The problem
When I execute parallel with one instance of Appium server it is very slow but when I use several instances of Appium with diff ports it works very fast. Why is that happen?! Appium is a server that should handle several devices with the same instance? it is the same for both platform Android and iOS.
I follow http://appium.io/docs/en/advanced-concepts/parallel-tests/ 
## Environment

* Appium server version: 1.8.1
* Node.js version (unless using Appium.app|exe): v10.4.1
* Mobile platform/version under test: iOS/Android
* Real device or emulator/simulator: Both

**Comment by mykola-mokhnach** [comment]
It is impossible to say anything here having such a poor issue description. Please add logs, metrics, caparisons and the other necessary details.

**Comment by AvrahamAtia** [comment]
Start Appium Server by bash script: 
** 
killall node
osascript -e 'tell app "Terminal"
do script "appium -a 127.0.0.1 -p 4723 -bp 8100 --webdriveragent-port 9019 --log 4723_AppiumServerLog.txt"
end tell'
sleep 10

osascript -e 'tell app "Terminal"
do script "appium -a 127.0.0.1 -p 4726 -bp 8103 --webdriveragent-port 9016 --log 4726_AppiumServerLog.txt"
end tell'
sleep 10

osascript -e 'tell app "Terminal"
do script "appium -a 127.0.0.1 -p 4729 -bp 8106 --webdriveragent-port 9013 --log 4729_AppiumServerLog.txt"
end tell'
sleep 10

osascript -e 'tell app "Terminal"
do script "appium -a 127.0.0.1 -p 4732 -bp 8109 --webdriveragent-port 9010 --log 4732_AppiumServerLog.txt"
end tell'
sleep 10 
** 
this script works fine.

but When I start Appium with "appium" is too slowly

**Comment by AvrahamAtia** [comment]
when I just start appium in command line and I handle the WDA ports fro iOS in the project self it is very slow!!

**Comment by mykola-mokhnach** [comment]
Like I said "slow" is too generic term. It is not possible to diagnose possible issues there without the detailed data.

**Comment by dpgraham** [comment]
I don't think these results are surprising. One Appium server runs on just one process. Multiple servers run on multiple processes.

**Comment by jumois** [comment]
I think the issue here is that the documentation suggests to use single server setup for parallel testing when Appium is not capable for it.

**Comment by AvrahamAtia** [comment]
@dpgraham @jumois  So should I used with several instance?! 
If Appium is server So the server should handle a several sessions!!

**Comment by saikrishna321** [comment]
@AvrahamAtia @jumois 

> Appium is not capable for it

Appium is capable of handling multiple request.

@SrinivasanTarget and myself are running tests against single server session and we have not seen any issues from server side. 

Like @mykola-mokhnach said 'slow' is too generic, what is slow, response from server for the request is slow or the actions to complete is slow. So what is slow ?

**Comment by AvrahamAtia** [comment]
@saikrishna321 (Just to verify!)So you are running diff sessions on the server in parallel?

**Comment by saikrishna321** [comment]
> (Just to verify!)So you are running diff sessions on one server in parallel?

Yes, Two devices two driver session pointing to same server port (ex:4723) with different WDA and SYSTEM_PORT

**Comment by AvrahamAtia** [comment]
Ok, I will try again! Thanks:):)

**Comment by AvrahamAtia** [comment]
SYSTEM_PORT is for both platform Android and iOS?

**Comment by saikrishna321** [comment]
> When you run tests in parallel, you must adjust the port to avoid conflicts. 

Yes

> Son if I use uiautomator1 I do not need this capabilities?

UI1 is obsolete. So pls use UIA2

**Comment by AvrahamAtia** [comment]
I have several issue with UIA2 :(:(

**Comment by AvrahamAtia** [comment]
Ok, it is works fine now!!
