### ISSUE TITLE
Appium 1.7.0 data driven Issue

### ISSUE THREAD

**Issue by RohitrajElpis** [appium/appium#11387]
HI @KazuCocoa if i am using Appium 1.7.0 latest version , then i am not able to take data from Excel sheet , if i have use  same code same logic for Appium 1.6.3 then it is working fine .

Please suggest me and do need full help . if any jar file issue and any set up please provide me link so i can understand better .

**Comment by saikrishna321** [comment]
> i am not able to take data from Excel sheet

What is this got to do with appium ?

**Comment by saikrishna321** [comment]
Please ask for questions in discuss.appium.io. This place is for defect

**Comment by KazuCocoa** [comment]
Right > Please ask for questions in discuss.appium.io. This place is for defect

I guess you mean your own framework for data-driven testing or keyword-driven one.
Appium doesn't provide such features.

**Comment by RohitrajElpis** [comment]
hi @KazuCocoa i have asked that question under appium discuss https://discuss.appium.io/t/appium-version-issue-with-data-driven/23626?u=rohit1
