### ISSUE TITLE
Cannot set sendKeyStrategy

### ISSUE THREAD

**Issue by FilipWennerdahlSopraSteria** [appium/appium#11383]
## The problem

When sending keys to an input field, "setValue" strategy is used on simulators as default. Also you cannot change the strategy using the capability "sendKeyStrategy". This causes issues on some sites on iOS, not registering as actually inputting keys to the field or showing search results.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.0
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: Mac,
* Node.js version (unless using Appium.app|exe): 9.5.0
* Mobile platform/version under test: Safari iOS 11.4
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

 [Full appium server logs](https://gist.github.com/FilipWennerdahlSopraSteria/c0de3b08b85937a3d1edc71e1e6fe2fc)

**Comment by KazuCocoa** [comment]
📝 
- https://github.com/appium/appium-xcuitest-driver/blob/aa7aa1524c0dca3853a892e07e5cb1035a915c01/lib/commands/element.js#L160 ?
- https://github.com/appium/appium-remote-debugger/blob/f5cfeb4ee2f3306f09006140f2462a50a4729106/lib/remote-debugger.js#L369 ?

**Comment by FilipWennerdahlSopraSteria** [comment]
@KazuCocoa So if I'm understanding this correctly, appium forces setting the value directly in web contexts? 

If that's the case it still leaves the issue that some sites (in this case yahoo weather - add location input element on mobile browser) does not detect that text actually was entered into the search field (even thought it was) hence not showing any results. It seems to only update the search result field when using the keyboard to type, for example after letting appium set the value of the input element i have to manually bring up the keyboard and press a key.

**Comment by KazuCocoa** [comment]
Yes, probably. This issue is an enhancement, I think. (Sorry only links which are just noted to me)

Do you know any good site to use it as a test page when we confirm the behaviour?

**Comment by KazuCocoa** [comment]
> in this case yahoo weather

ah, https://www.yahoo.com/news/weather/ ?

**Comment by FilipWennerdahlSopraSteria** [comment]
@KazuCocoa Yes, [https://www.yahoo.com/news/weather/](https://www.yahoo.com/news/weather/) on mobile Safari.
Click this element:
![yahoo-weather-1](https://user-images.githubusercontent.com/37865736/45802578-88811c80-bcb7-11e8-8ae5-f2c01739e6bc.png)

Which takes you to this screen, it's this input element that causes issues:
![yahoo-weather-2](https://user-images.githubusercontent.com/37865736/45802612-9b93ec80-bcb7-11e8-9063-4f5ce252ad8f.png)

I performed tests on a iPhone8 Plus simulator using Appium 1.9.0. (screenshots are from firefox responsive design mode and may not look exactly like mobile safari on the simulator)

**Comment by mykola-mokhnach** [comment]
Closed as obsolete
