### ISSUE TITLE
After updating to mac os Hign Sierra 10.13.6 and appium 1.9.0, can not start webdriveragent on real iOS device with appium started using ssh connection.

### ISSUE THREAD

**Issue by EltonZhong** [appium/appium#11385]
## The problem

In the past, I was using scripts like `ssh **@** -t "source ~/.bash_profile && appium -p 4723"` to start appium on remote mac machines.  It was always working well in mac os 10.13, appium 1.7.2.

After updating to Mac OS Hign Sierra 10.13.6 and appium 1.9.0, 
problems occur.
When I run cases using a real device,  I find that error like below occurs.
![image](https://user-images.githubusercontent.com/20570738/45726610-8bfea000-bbf2-11e8-917a-ceed8b1c4d67.png)
While when I start appium on the machine using its local terminal, I find that everything works well.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.0
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2
* Desktop OS/version used to run Appium: mac os 10.13.6, Hign Sierra
* Node.js version (unless using Appium.app|exe): v10.8.0
* Mobile platform/version under test:11.2.6
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: npm install -g appium && appium -p [port]

## Details

`ssh **@** -t "source ~/.bash_profile && appium -p 4723"`

## Code To Reproduce Issue [ Good To Have ]

`ssh **@** -t "source ~/.bash_profile && appium -p 4723"`
appium get started and run any case in an iOS real device of any version, 
when installing webdriveragent, the appium tells that certification is expired or reverted.
while using a local terminal session, run `appium -p 4723`
everything goes well.

##Hint:
When I chmod 100
~/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, 
I found that 
`ssh **@** -t "source ~/.bash_profile && appium -p 4723"` produce log like below:
![image](https://user-images.githubusercontent.com/20570738/45726919-0e3b9400-bbf4-11e8-9194-bb0b5d070997.png)
While when  I start appium with `ssh ***@***` and `appium -p 4723`, appium got started successfully.
I guess script `ssh **@** -t "source ~/.bash_profile && appium -p 4723"` changes something on ~/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
with write permisson while `start appium on the machine using its local terminal` don't.
Since I don't know much about iOS, I hope you guys could kindly solve my problem.
Thanks!!

**Comment by EltonZhong** [comment]
In the past, I was using scripts like ssh **@** -t "source ~/.bash_profile && appium -p 4723" to start appium on remote mac machines.
It was always working well in mac os 10.13, appium 1.7.2.

**Comment by mykola-mokhnach** [comment]
The error in the log clearly states there is a problem with your signing certificate, so WDA cannot be deployed on the device.

Closed as not an issue.

**Comment by EltonZhong** [comment]
> The error in the log clearly states there is a problem with your signing certificate, so WDA cannot be deployed on the device.
> 
> Closed as not an issue.

While, it might be some problem with webdriveragent

**Comment by mykola-mokhnach** [comment]
If you think this is a webdriveragent issue then please report it to https://github.com/facebook/WebDriverAgent
