### ISSUE TITLE
After running for a long certain time, got connect ENOBUFS error

### ISSUE THREAD

**Issue by Dan2712** [appium/appium#11380]
## The problem

Doing a long time testing, it's more about downloading pressure test, and the flow is like: download -> wait -> delete -> re-download. The test worked well at the beginning, but after a day running, the appium stopped and showed a ENOBUFS error on the log. While got this, the appium needs to restart.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Win 7
* Node.js version (unless using Appium.app|exe): 6.1.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

https://gist.github.com/Dan2712/e04cbc867f49fbb4cd9a290b45f43a9a

**Comment by mykola-mokhnach** [comment]
I assume it is an issue with downstream node HTTP server. Try to throttle the frequency of requests on the client side like it is described at https://stackoverflow.com/questions/44679614/can-someone-explain-an-enobufs-error

**Comment by mykola-mokhnach** [comment]
Also, try use the most recent Appium and NodeJS versions.

**Comment by mykola-mokhnach** [comment]
Did you update NodeJS? This is important

**Comment by Dan2712** [comment]
Yes, have made it to 8.11.4

**Comment by mykola-mokhnach** [comment]
Can you provide the updated log with new server and node versions?

**Comment by Dan2712** [comment]
Ok, I'll re-produce the issue, and the log seems the same

**Comment by mykola-mokhnach** [comment]
Try to patch your local source with https://github.com/appium/appium-base-driver/pull/260 and let me know if that helps

**Comment by mykola-mokhnach** [comment]
do not forget to run `gulp transplie` after patching and restart the server

**Comment by mykola-mokhnach** [comment]
I assume everything is fine now if there are no new comments
