### ISSUE TITLE
Can't get page source and screenshot of iOS list view

### ISSUE THREAD

**Issue by appiumnovice** [appium/appium#11384]
## The problem

When I recorded the test on a iOS device, it was able to scroll on a list of items.
Now, without change of Appium server, Appium client or XCode, it's not possible to scroll and select an item, to get source or screenshot with Appium Desktop and Appium CLI.

## Environment

* Appium version (or git revision) that exhibits the issue: tested with Appium 1.8.1 and 1.9.0
* Desktop OS/version used to run Appium: 1.8.1 and 1.9.0
* Node.js version (unless using Appium.app|exe): 10.6.0
* Mobile platform/version under test: iOS 10.1.1, iOS 11.2, ...
* Real device or emulator/simulator: real devices iPhone 5s, iPhone 6s, ...
* Appium CLI or Appium.app|exe: both

## Link to Appium logs

In this gist, there are 3 examples of getPageSource, the third was applied on the list of items, and it took 10 minutes, till to have an "unKnownError"
https://gist.github.com/appiumnovice/32ed56b0c740e46ff58a7f6bff7a2ef3#file-appium-server-log

**Comment by mykola-mokhnach** [comment]
This looks like internal error inside WebDriverAgent. Try if it works better in appium@beta. In case the same problem is still present then report it to https://github.com/facebook/WebDriverAgent

Closed as third party issue.
