### ISSUE TITLE
Why does appium contain parts of selenium package org.openqa.selenium?

### ISSUE THREAD

**Issue by AndiCover** [appium/appium#11394]
I upgraded appium from 4.0.0 to 6.1.0 and run into a problem because appium uses parts of a selenium package. For me it looks like you copied the package partly to your project instead of adding selenium as dependency.
I receive errors like 'The method domClick(WebElement, WebDriver) is ambiguous for the type Interactions'. That error is because WebElement exists in package with the same name in java-client-6.1.0.jar and in selenium-api-3.14.0.jar.

When I create my own appium library which does not contain the package org.openqa.selenium or using appium <= 4.0.0 this works just fine. 

I am using selenium 3.14.

Does it have a reason why you copied this package to your project instead of adding selenium as dependency?
When is this going to be corrected?

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/appium/java-client

**Comment by mykola-mokhnach** [comment]
I assume the reason for that was that Selenium did not include the changes that were needed for proper appium extension functionality (some PRs are waiting for more than two years there), so we had to override some classes there to make the stuff working.
