### ISSUE TITLE
No suitable method found for longPress

### ISSUE THREAD

**Issue by lakesierra96** [appium/appium#11398]
## Link to Appium logs

Error:(60, 15) java: no suitable method found for longPress(org.openqa.selenium.WebElement)
    method io.appium.java_client.TouchAction.longPress(io.appium.java_client.touch.LongPressOptions) is not applicable
      (argument mismatch; org.openqa.selenium.WebElement cannot be converted to io.appium.java_client.touch.LongPressOptions)
    method io.appium.java_client.TouchAction.longPress(io.appium.java_client.touch.offset.PointOption) is not applicable
      (argument mismatch; org.openqa.selenium.WebElement cannot be converted to io.appium.java_client.touch.offset.PointOption)

## Code To Reproduce Issue [ Good To Have ]

        action.longPress(ele1).moveTo(ele2).release().perform();

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/appium/java-client
