### ISSUE TITLE
Compile errors when launching Appium 1.8.0/1.9.0 for IOS devices, but simulator is ok

### ISSUE THREAD

**Issue by ragavanb** [appium/appium#11405]
Problem
======

I have setup Appium for IOS. When I run on the simulator, everything works fine. However, when I run on actual device, I am getting build errors for the following. Not sure if I am doing anything wrong. Has anyone seen this. If someone help with this, that would be great.

WebDriverAgentLib - Compile errors . (see below)
WebDriverAgentRunner - Compile errors (see below)
IntegrationApp - compiles fine and able install on the phone

The compile errors is also seen when done in Xcode/command line.

ENVIRONMENT
==========
Xcode: 9.4.1
phone IOS: 11.4.1
Phone: 6s
Appium Version: 1.8.0 ( I also tried 1.9.0)
Mac OS: 10.13.6

BUILD Command used by Appium (Note: the build passes for Simulator, only difference in the command is the ID)
xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=1db89426fd318738d591768002bafc7d9d197674 IPHONEOS_DEPLOYMENT_TARGET=11.4

LOGS & COMPILE ERROR
================

info] [XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing running processes 'xcodebuild.*1db89426fd318738d591768002bafc7d9d197674, iproxy 8100' for the device 1db89426fd318738d591768002bafc7d9d197674...[debug] [XCUITest] 'pgrep -nif iproxy 8100' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB[debug] [XCUITest] Using Xcode 9.4.1, so fixing WDA codebase
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=1db89426fd318738d591768002bafc7d9d197674 IPHONEOS_DEPLOYMENT_TARGET=11.4' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will be logged. To change this, use 'showXcodeLog' desired capability[info] [Xcode] Build settings from command line:
[info] [Xcode]
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[info] [Xcode] IPHONEOS_DEPLOYMENT_TARGET = 11.4
[info] [Xcode]
[info] [Xcode] [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[info] [Xcode] === BUILD TARGET WebDriverAgentLib OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===
[info] [Xcode]
[info] [Xcode]
[info] [Xcode] Check dependencies
[info] [Xcode] [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[info] [Xcode]
[info] [Xcode]
[info] [Xcode] ProcessInfoPlistFile /Users/raga/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphoneos/WebDriverAgentLib.framework/Info.plist WebDriverAgentLib/Info.plist
[info] [Xcode] cd /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
[info] [Xcode] export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/node_modules/.bin:/Applications/Appium.app/Contents/MacOS"
[info] [Xcode] builtin-infoPlistUtility /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Info.plist -expandbuildsettings -format binary -platform iphoneos -requiredArchitecture arm64 -o /Users/raga/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphoneos/WebDriverAgentLib.framework/Info.plist
[info] [Xcode]
[info] [Xcode]
[info] [Xcode]
[info] [Xcode] CompileC /Users/raga/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Intermediates.noindex/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/Objects-normal/arm64/FBXPath.o WebDriverAgentLib/Utilities/FBXPath.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
[info] [Xcode] cd /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
[info] [Xcode] export LANG=en_US.US-ASCII
[info] [Xcode] export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/node_modules/.bin:/Applications/Appium.app/Contents/MacOS"
[info] [Xcode] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch arm64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/raga/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/raga/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -O0 -fno-common -Werror -Wmissing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Warc-repeated-use-of-weak -Wno-arc-maybe-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wunused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -pedantic -Wshadow -Wno-four-char-constants -Wconversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wfloat-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wassign-enum -Wsign-compare -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=11.4 -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -index-store-path /Users/raga/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Index/DataStore -iquote /Users/raga/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Intermediates.noindex/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/WebDriverAgentLib-generated-files.hmap -I/Users/raga/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Intermediates.noindex/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/WebDriverAgentLib-own-target-headers.hmap -I/Users/raga/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Intermediates.noindex/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/WebDriverAgentLib-all-target-headers.hmap -iquote /Users/raga/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Intermediates.noindex/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/WebDriverAgentLib-project-headers.hmap -I/Users/raga/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphoneos/include -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk/usr/include/libxml2 -I/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Modules -I/Users/raga/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Intermediates.noindex/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/DerivedSources/arm64 -I/Users/raga/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Intermediates.noindex/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/DerivedSources -Weverything -Wno-objc-missing-property-synthesis -Wno-unused-macros -Wno-disabled-macro-expansion -Wno-gnu-statement-expression -Wno-language-extension-token -Wno-overriding-method-mismatch -Wno-missing-variable-declarations -Rno-module-build -Wno-auto-import -Wno-objc-interface-ivars -Wno-documentation-unknown-command -Wno-reserved-id-macro -Wno-unused-parameter -Wno-gnu-conditional-omitted-operand -Wno-explicit-ownership-type -Wno-date-time -Wno-cast-align -Wno-cstring-format-directive -Wno-double-promotion -Wno-partial-availability -F/Users/raga/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphoneos -F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks -F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/PrivateFrameworks -F/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS -F/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/Mac -MMD -MT dependencies -MF /Users/raga/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Intermediates.noindex/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/Objects-normal/arm64/FBXPath.d --serialize-diagnostics /Users/raga/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Intermediates.noindex/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/Objects-normal/arm64/FBXPath.dia -c /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.m -o /Users/raga/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Intermediates.noindex/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/Objects-normal/arm64/FBXPath.o
[info] [Xcode] [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[info] [Xcode] In file included from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.m:10:
[info] [Xcode] In file included from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.h:13:
[info] [Xcode] /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/PrivateHeaders/XCTest/XCElementSnapshot.h:14:1: error: duplicate interface definition for class 'XCElementSnapshot'
[info] [Xcode] @interface XCElementSnapshot : NSObject <XCUIElementAttributes, NSSecureCoding>
[info] [Xcode] ^
[info] [Xcode] In module 'XCTest' imported from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.h:11:
[info] [Xcode] /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/Headers/XCElementSnapshot.h:12:12: note: previous definition is here
[info] [Xcode] @interface XCElementSnapshot : NSObject <XCElementAttributesPrivate, NSSecureCoding>
[info] [Xcode] ^
[info] [Xcode] In file included from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.m:10:
[info] [Xcode] In file included from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.h:13:
[info] [Xcode] /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/PrivateHeaders/XCTest/XCElementSnapshot.h:40:16: error: property has a previous declaration
[info] [Xcode] @Property BOOL hasFocus; // @synthesize hasFocus=_hasFocus;
[info] [Xcode] ^
[info] [Xcode] In module 'XCTest' imported from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.h:11:
[info] [Xcode] /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/Headers/XCElementSnapshot.h:64:17: note: property declared here
[info] [Xcode] @Property _Bool hasFocus; // @synthesize hasFocus=_hasFocus;
[info] [Xcode] ^
[info] [Xcode] In file included from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.m:10:
[info] [Xcode] In file included from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.h:13:
[info] [Xcode] /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/PrivateHeaders/XCTest/XCElementSnapshot.h:41:16: error: property has a previous declaration
[info] [Xcode] @Property BOOL hasKeyboardFocus; // @synthesize hasKeyboardFocus=_hasKeyboardFocus;
[info] [Xcode] ^
[info] [Xcode] In module 'XCTest' imported from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.h:11:
[info] [Xcode] /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/Headers/XCElementSnapshot.h:65:17: note: property declared here
[info] [Xcode] @Property _Bool hasKeyboardFocus; // @synthesize hasKeyboardFocus=_hasKeyboardFocus;
[info] [Xcode] ^
[info] [Xcode] In file included from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.m:10:
[info] [Xcode] In file included from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.h:13:
[info] [Xcode] /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/PrivateHeaders/XCTest/XCElementSnapshot.h:42:31: error: property has a previous declaration
[info] [Xcode] @Property(copy) NSDictionary *additionalAttributes; // @synthesize additionalAttributes=_additionalAttributes;
[info] [Xcode] ^
[info] [Xcode] In module 'XCTest' imported from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.h:11:
[info] [Xcode] /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/Headers/XCElementSnapshot.h:50:31: note: property declared here
[info] [Xcode] @Property(copy) NSDictionary *additionalAttributes; // @synthesize additionalAttributes=_additionalAttributes;
[info] [Xcode] ^
[info] [Xcode] In file included from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.m:10:
[info] [Xcode] In file included from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.h:13:
[info] [Xcode] /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/PrivateHeaders/XCTest/XCElementSnapshot.h:43:26: error: property has a previous declaration
[info] [Xcode] @Property(copy) NSArray *userTestingAttributes; // @synthesize userTestingAttributes=_userTestingAttributes;
[info] [Xcode] ^
[info] [Xcode] In module 'XCTest' imported from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.h:11:
[info] [Xcode] /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/Headers/XCElementSnapshot.h:85:26: note: property declared here
[info] [Xcode] @Property(copy) NSArray *userTestingAttributes; // @synthesize userTestingAttributes=_userTestingAttributes;
[info] [Xcode] ^
[info] [Xcode] In file included from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.m:10:
[info] [Xcode] In file included from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.h:13:
[info] [Xcode] /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/PrivateHeaders/XCTest/XCElementSnapshot.h:44:30: error: property has a previous declaration
[info] [Xcode] @Property unsigned long long traits; // @synthesize traits=_traits;
[info] [Xcode] ^
[info] [Xcode] In module 'XCTest' imported from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.h:11:
[info] [Xcode] /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/Headers/XCElementSnapshot.h:84:30: note: property declared here
[info] [Xcode] @Property unsigned long long traits; // @synthesize traits=_traits;
[info] [Xcode] ^
[info] [Xcode] In file included from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.m:10:
[info] [Xcode] In file included from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.h:13:
[info] [Xcode] /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/PrivateHeaders/XCTest/XCElementSnapshot.h:45:16: error: property has a previous declaration
[info] [Xcode] @Property BOOL isMainWindow; // @synthesize isMainWindow=_isMainWindow;
[info] [Xcode] ^
[info] [Xcode] In module 'XCTest' imported from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.h:11:
[info] [Xcode] /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/Headers/XCElementSnapshot.h:72:17: note: property declared here
[info] [Xcode] @Property _Bool isMainWindow; // @synthesize isMainWindow=_isMainWindow;
[info] [Xcode] ^
[info] [Xcode] In file included from /
[info] [Xcode] Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.m:10:
[info] [Xcode] In file included from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.h:13:
[info] [Xcode] /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/PrivateHeaders/XCTest/XCElementSnapshot.h:46:26: error: property has a previous declaration
[info] [Xcode] @Property(copy) NSArray *children; // @synthesize children=_children;
[info] [Xcode] ^
[info] [Xcode] In module 'XCTest' imported from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.h:11:
[info] [Xcode] /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/Headers/XCElementSnapshot.h:52:26: note: property declared here
[info] [Xcode] @Property(copy) NSArray *children; // @synthesize children=_children;
[info] [Xcode] ^
[info] [Xcode] In file included from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.m:10:
[info] [Xcode] In file included from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.h:13:
[info] [Xcode] /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/PrivateHeaders/XCTest/XCElementSnapshot.h:47:30: error: property has a previous declaration
[info] [Xcode] @Property XCElementSnapshot *parent; // @synthesize parent=_parent;
[info] [Xcode] ^
[info] [Xcode] In module 'XCTest' imported from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.h:11:
[info] [Xcode] /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/Headers/XCElementSnapshot.h:75:30: note: property declared here
[info] [Xcode] @Property XCElementSnapshot *parent; // @synthesize parent=_parent;
[info] [Xcode] ^
[info] [Xcode] In file included from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.m:10:
[info] [Xcode] In file included from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.h:13:
[info] [Xcode] /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/PrivateHeaders/XCTest/XCElementSnapshot.h:48:43: error: property has a previous declaration
[info] [Xcode] @Property(retain) XCAccessibilityElement *parentAccessibilityElement; // @synthesize parentAccessibilityElement=_parentAccessibilityElement;
[info] [Xcode] ^
[info] [Xcode] In module 'XCTest' imported from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.h:11:
[info] [Xcode] /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/Headers/XCElementSnapshot.h:76:43: note: property declared here
[info] [Xcode] @Property(retain) XCAccessibilityElement *parentAccessibilityElement; // @synthesize parentAccessibilityElement=_parentAccessibilityElement;
[info] [Xcode] ^
[info] [Xcode] In file included from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.m:10:
[info] [Xcode] In file included from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.h:13:
[info] [Xcode] /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/PrivateHeaders/XCTest/XCElementSnapshot.h:49:43: error: property has a previous declaration
[info] [Xcode] @Property(retain) XCAccessibilityElement *accessibilityElement; // @synthesize accessibilityElement=_accessibilityElement;
[info] [Xcode] ^
[info] [Xcode] In module 'XCTest' imported from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.h:11:
[info] [Xcode] /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/Headers/XCElementSnapshot.h:49:43: note: property declared here
[info] [Xcode] @Property(retain) XCAccessibilityElement *accessibilityElement; // @synthesize accessibilityElement=_accessibilityElement;
[info] [Xcode] ^
[info] [Xcode] In file included from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.m:10:
[info] [Xcode] In file included from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.h:13:
[info] [Xcode] /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/PrivateHeaders/XCTest/XCElementSnapshot.h:50:30: error: property has a previous declaration
[info] [Xcode] @Property(readonly) NSArray *suggestedHitpoints;
[info] [Xcode] ^
[info] [Xcode] In module 'XCTest' imported from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.h:11:
[info] [Xcode] /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/Headers/XCElementSnapshot.h:88:30: note: property declared here
[info] [Xcode] @Property(readonly) NSArray *suggestedHitpoints;
[info] [Xcode] ^
[info] [Xcode] In file included from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.m:10:
[info] [Xcode] In file included from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.h:13:
[info] [Xcode] /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/PrivateHeaders/XCTest/XCElementSnapshot.h:51:35: error: property has a previous declaration
[info] [Xcode] @Property(readonly) struct CGRect visibleFrame;
[info] [Xcode] ^
[info] [Xcode] In module 'XCTest' imported from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.h:11:
[info] [Xcode] /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/Headers/XCElementSnapshot.h:90:35: note: property declared here
[info] [Xcode] @Property(readonly) struct CGRect visibleFrame;
[info] [Xcode] ^
[info] [Xcode] In file included from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.m:10:
[info] [Xcode] In file included from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.h:13:
[info] [Xcode] /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/PrivateHeaders/XCTest/XCElementSnapshot.h:52:40: error: property has a previous declaration
[info] [Xcode] @Property(readonly) XCElementSnapshot *scrollView;
[info] [Xcode] ^
[info] [Xcode] In module 'XCTest' imported from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.h:11:
[info] [Xcode] /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/Headers/XCElementSnapshot.h:82:40: note: property declared here
[info] [Xcode] @Property(readonly) XCElementSnapsh
[info] [Xcode] ot *scrollView;
[info] [Xcode] ^
[info] [Xcode] In file included from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.m:10:
[info] [Xcode] In file included from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.h:13:
[info] [Xcode] /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/PrivateHeaders/XCTest/XCElementSnapshot.h:53:37: error: property has a previous declaration
[info] [Xcode] @Property(readonly, copy) NSString *truncatedValueString;
[info] [Xcode] ^
[info] [Xcode] In module 'XCTest' imported from /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.h:11:
[info] [Xcode] /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/Headers/XCElementSnapshot.h:89:37: note: property declared here

**Comment by mykola-mokhnach** [comment]
Try to clear Xcode caches, and to clean the project.
