### ISSUE TITLE
Double click and element or coordinates using appium javascript client (wd

### ISSUE THREAD

**Issue by gkvappium** [appium/appium#11409]
## The problem

The documentation from wd says, 
// Not supported

// wd example
// Using tapElement method
await driver.tapElement(elementOne);

// Using touch actions
let action = new wd.TouchAction();
action.tap({el: element});
await action.perform();

Is there no method for double tapping an element using the javascript client? If there is a workaround for this problem?

* Appium version (or git revision) that exhibits the issue: 1.9.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOSX 10.13.6
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android 8.0
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

@mykola-mokhnach , is there any workaround for appium javascript client?

**Comment by mykola-mokhnach** [comment]
Pleas use Appium forum to ask question. I have no idea how the stuff works in wd client

**Comment by gkvappium** [comment]
hi @mykola-mokhnach , I did pose this question in the forum. I also tried doubleclick() method. But nothing seems to work for javascript. Can you please re-direct the question to somebody who maintains the js appium client? Thanks

**Comment by mykola-mokhnach** [comment]
I'm not quite sure about who is the maintainer there. Try to looks at https://github.com/webdriverio

**Comment by gkvappium** [comment]
thanks @mykola-mokhnach , I now use the touch from webio instead of wd. Something like this.

    async doubleTapCoordinates(xValue: Number, yValue: Number) {
        await this._driver.webio().touchAction([
            {action: 'tap', x: xValue, y: yValue},
            {action: 'tap', x: xValue, y: yValue}
        ]);
    }
