### ISSUE TITLE
Unable to launch the Inspector in Appium Android run, Facing this error : [MJSONWP] Encountered internal error running command: Error: Error executing adbExec. Original error: Command '/Users/mbf-soundhar/Documents/Testing/Automation/SDK/platform-tools/adb -P 5037 -s ce10160afacf440204 shell stop' exited with code 1{"stdout":"","stderr":"stop: must be root\n","code":1}

### ISSUE THREAD

**Issue by ssoundhar** [appium/appium#11408]
Launching Appium with command: export ANDROID_HOME="/Users/mbf-soundhar/Documents/Testing/Automation/SDK"; export ANDROID_HOME="/Users/mbf-soundhar/Documents/Testing/Automation/SDK"; '/Applications/Appium.app/Contents/Resources/node/bin/node' appium/build/lib/main.js --address "127.0.0.1" --debug-log-spacing --automation-name "Appium" --platform-name "Android" --platform-version "7.0" --app "/Users/mbf-soundhar/Documents/Testing/Soundhar/app-staging-debug.apk" --dont-stop-app-on-reset --device-name "Samsung" --language "en"

[Appium] Welcome to Appium v1.5.3

[Appium] Non-default server args:

[Appium]   address: '127.0.0.1'
[Appium]   debugLogSpacing: true
[Appium]   platformName: 'Android'

[Appium]   platformVersion: '7.0'
[Appium]   automationName: 'Appium'
[Appium]   deviceName: 'Samsung'
[Appium]   app: '/Users/mbf-soundhar/Documents/Testing/Soundhar/app-staging-debug.apk'
[Appium]   language: 'en'
[Appium]   dontStopAppOnReset: true
[Appium] Deprecated server args:
[Appium]   --platform-name => --default-capabilities '{"platformName":"Android"}'
[Appium]   --platform-version => --default-capabilities '{"platformVersion":"7.0"}'
[Appium]   --automation-name => --default-capabilities '{"automationName":"Appium"}'
[Appium]   --device-name => --default-capabilities '{"deviceName":"Samsung"}'
[Appium]   --app => --default-capabilities '{"app":"/Users/mbf-soundhar/Documents/Testing/Soundhar/app-staging-debug.apk"}'
[Appium]   --language => --default-capabilities '{"language":"en"}'
[Appium]   --dont-stop-app-on-reset => --default-capabilities '{"dontStopAppOnReset":true}'

[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:

[Appium]   platformName: 'Android'

[Appium]   platformVersion: '7.0'
[Appium]   automationName: 'Appium'
[Appium]   deviceName: 'Samsung'
[Appium]   app: '/Users/mbf-soundhar/Documents/Testing/Soundhar/app-staging-debug.apk'
[Appium]   language: 'en'

[Appium]   dontStopAppOnReset: true

[Appium] Appium REST http interface listener started on 127.0.0.1:4723

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 29 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 10 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 7 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 285 ms - 83 

[HTTP] --> GET /wd/hub/sessions {}
[MJSONWP] Calling AppiumDriver.getSessions() with args: []
[MJSONWP] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 4 ms - 40 

[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"Android","newCommandTimeout":"7200","app":"/Users/mbf-soundhar/Documents/Testing/Soundhar/app-staging-debug.apk","platformVersion":"7.0","deviceName":"Samsung","language":"en","automationName":"Appium"}}

[MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"Android",...

[Appium] Creating new AndroidDriver session
[Appium] Capabilities:
[Appium]   platformName: 'Android'
[Appium]   newCommandTimeout: '7200'
[Appium]   app: '/Users/mbf-soundhar/Documents/Testing/Soundhar/app-staging-debug.apk'
[Appium]   platformVersion: '7.0'
[Appium]   deviceName: 'Samsung'
[Appium]   language: 'en'
[Appium]   automationName: 'Appium'
[Appium]   dontStopAppOnReset: true
[BaseDriver] Capability 'newCommandTimeout' changed from string ('7200') to integer (7200). This may cause unexpected behavior

[BaseDriver] Session created with session id: c65e3fb2-1dc7-46c1-8de1-b39826651687

[debug] [AndroidDriver] Getting Java version

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[AndroidDriver] Java version is: 10.0.2

[ADB] Checking whether adb is present

[ADB] Using adb from /Users/mbf-soundhar/Documents/Testing/Automation/SDK/platform-tools/adb

[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device

[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected

[AndroidDriver] Looking for a device with Android 7.0
[debug] [ADB] Setting device id to ce10160afacf440204

[ADB] Getting device platform version
[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected

[debug] [ADB] Running /Users/mbf-soundhar/Documents/Testing/Automation/SDK/platform-tools/adb with args: ["-P",5037,"-s","ce10160afacf440204","shell","getprop","ro.build.version.release"]

[AndroidDriver] Using device: ce10160afacf440204

[ADB] Checking whether adb is present

[ADB] Using adb from /Users/mbf-soundhar/Documents/Testing/Automation/SDK/platform-tools/adb

[debug] [ADB] Setting device id to ce10160afacf440204

[BaseDriver] Using local app '/Users/mbf-soundhar/Documents/Testing/Soundhar/app-staging-debug.apk'
[debug] [AndroidDriver] Checking whether app is actually present
[AndroidDriver] Starting Android session
[debug] [ADB] Running /Users/mbf-soundhar/Documents/Testing/Automation/SDK/platform-tools/adb with args: ["-P",5037,"-s","ce10160afacf440204","wait-for-device"]
[debug] [ADB] Getting connected devices...
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/mbf-soundhar/Documents/Testing/Automation/SDK/platform-tools/adb with args: ["-P",5037,"-s","ce10160afacf440204","shell","echo","ping"]

[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/mbf-soundhar/Documents/Testing/Automation/SDK/platform-tools/adb with args: ["-P",5037,"-s","ce10160afacf440204","shell","getprop","ro.build.version.sdk"]

[debug] [ADB] Device API level: 24

[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected

[debug] [ADB] Running /Users/mbf-soundhar/Documents/Testing/Automation/SDK/platform-tools/adb with args: ["-P",5037,"-s","ce10160afacf440204","shell","getprop","persist.sys.locale"]

[debug] [ADB] Current device property 'persist.sys.locale': en-GB

[debug] [ADB] Setting device property 'persist.sys.locale' to 'en'
[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/mbf-soundhar/Documents/Testing/Automation/SDK/platform-tools/adb with args: ["-P",5037,"-s","ce10160afacf440204","shell","setprop","persist.sys.locale","en"]

[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected

[debug] [ADB] Running /Users/mbf-soundhar/Documents/Testing/Automation/SDK/platform-tools/adb with args: ["-P",5037,"-s","ce10160afacf440204","shell","stop"]

[debug] [ADB] Running /Users/mbf-soundhar/Documents/Testing/Automation/SDK/platform-tools/adb with args: ["-P",5037,"-s","ce10160afacf440204","shell","stop"]

[debug] [AndroidDriver] Shutting down Android driver

[AndroidDriver] Cannot shut down Android driver; it has already shut down

**[MJSONWP] Encountered internal error running command: Error: Error executing adbExec. Original error: Command '/Users/mbf-soundhar/Documents/Testing/Automation/SDK/platform-tools/adb -P 5037 -s ce10160afacf440204 shell stop' exited with code 1{"stdout":"","stderr":"stop: must be root\n","code":1}**

    at ADB.execFunc$ (lib/tools/system-calls.js:189:13)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

[HTTP] <-- POST /wd/hub/session 500 5932 ms - 384 

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 660 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 208 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 63 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 159 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 124 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 117 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 121 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 101 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 369 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 51 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 10 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 108 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 57 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 441 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 150 ms - 83

**Comment by mykola-mokhnach** [comment]
Please properly filk out  the reporting form with the necessary information and provide the full server log, not just a part of it

**Comment by ssoundhar** [comment]
Is any one know, why is this happening.?

**Comment by mykola-mokhnach** [comment]
Appium 1.5.3 is out of date. Please upgrade your server to the recent version

**Comment by ssoundhar** [comment]
Thanks, Updated and worked.
