### ISSUE TITLE
Unable to run tests on iOS < 9.3 (test run goes into an infinite loop with the latest log entry: "[debug] [XCUITest] Removing WDA application from device")

### ISSUE THREAD

**Issue by tooborg** [appium/appium#11402]
## The problem

The test framework is configured to support all iOS platforms starting from version 8.0 till latest. 
iOS 9.3+ uses latest supported non-beta Xcode (10.0);
iOS < 9.3 uses Xcode 7.3.1.

DEVELOPER_DIR env variable sets in runtime in such block:

```
if (Double.parseDouble(mobileApiLevel.substring(0, apiLevel.lastIndexOf("."))) < 9.3d) {
    appiumEnv.put("DEVELOPER_DIR", "/Applications/Xcode7.3.1/Xcode.app/Contents/Developer");
} else {
    appiumEnv.put("DEVELOPER_DIR", "/Applications/Xcode.app/Contents/Developer");
}

AppiumServiceBuilder builder = new AppiumServiceBuilder();
builder.usingDriverExecutable(new File(nodeJsPath));
if (appiumEnv.size() != 0) {
    builder.withEnvironment(appiumEnv);
}
builder.usingPort(Integer.parseInt(driverPort));
builder.withArgument(GeneralServerFlag.SESSION_OVERRIDE);

AppiumDriverLocalService appiumDriverLocalService = AppiumDriverLocalService.buildService(builder);
appiumDriverLocalService.start();
```

The test run goes into an infinite loop with the latest log entry (for each loop): "[debug] [XCUITest] Removing WDA application from device"
Tested on simulators with such OS versions: 9.2, 9.1, 8.4 

## Environment

* Appium version (or git revision) that exhibits the issue: **1.9.1**
* Last Appium version that did not exhibit the issue (if applicable): **1.7.2** with manually pre-set proper Xcode via "sudo xcode-select -s /Applications/Xcode7.3.1/Xcode.app/Contents/Developer"
* Desktop OS/version used to run Appium: **OS X 10.13.6 (17G65)**
* Node.js version (unless using Appium.app|exe): **v8.12.0**
* Mobile platform/version under test: **iOS 9.2/9.1/8.4**
* Real device or emulator/simulator: **simulator**
* Appium CLI or Appium.app|exe: **CLI**

## Details

It is possible to manually compile WDA using Xcode 10.0 but not possible in Xcode 7.3.1 -->
an error occurs: 
"/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBMjpegServer.m:50:27: No known class method for selector 'scheduledTimerWithTimeInterval:repeats:block:'"

in the following block -->

`_mainTimer = [NSTimer scheduledTimerWithTimeInterval:1.0 / FPS repeats:YES block:^(NSTimer * _Nonnull timer)
`

## Link to Appium logs

[appium_logs](https://gist.github.com/tooborg/025822a4dde28db05579a8f2ed043877#file-gistfile1-txt)

**Comment by tooborg** [comment]
Just switched to UIAutomation and got no success as well:

infinitely get an error: "[debug] [MJSONWP] Encountered internal error running command: Error: Command failed: ideviceinstaller -u 565269B3-2545-447E-B9A5-8475187C3243 -l "

1. ideviceinstaller is installed
2. "xcrun simctl list | egrep '(Booted)'" returns "iPhone 5s (565269B3-2545-447E-B9A5-8475187C3243) (Booted)"

[Log](https://gist.github.com/tooborg/64bc7c42757abe0032bed2d0336b9cfe#file-gistfile1-txt)

**Comment by mykola-mokhnach** [comment]
And what this particular command returns? Is the test is suppoed to run on real device or a simulator? If this is a simulator then udid should be dropped from caps

**Comment by tooborg** [comment]
The tests supposed to be executed on simulators.
Solved by proper reconfiguration of caps for UIAutomation.
Thanks!
