### ISSUE TITLE
Apk doesn't start on specific device

### ISSUE THREAD

**Issue by notihs** [appium/appium#11403]
## The problem

When trying to start apk to begin tests, one of the devices doesn't seem to be able to start its app. Always throws an error 500.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable): 1.9.0 and 1.8.1
* Desktop OS/version used to run Appium: Windows 10 and OS High Sierra
* Mobile platform/version under test: Android 7.0 - real device 

## Details

This issue only started to appear on 1.9.1. On previous versions it worked fine.

## Link to Appium logs

https://gist.github.com/notihs/d0ecd7bf44e5451bc8c3734ca95f2551

## Code To Reproduce Issue [ Good To Have ]

Just simply launch the app

**Comment by mykola-mokhnach** [comment]
@imurchie this probably happens because of https://github.com/appium/appium-android-driver/commit/187c66950ea430fd84704d21035c009cb4bebbc0

**Comment by KazuCocoa** [comment]
@notihs 
After happening the issue, what value returned by below command?

```
> C:\AndroidSDK\platform-tools\adb.exe -P 5037 -s QGZSPNJBDUSWS8PN pull /data/app/com.witsoftware.rcsplus.qa-1/base.apk C\:\\Users\\Daniel\\AppData\\Local\\Temp\\com.witsoftware.rcsplus.qa.apk
```

Please replace `QGZSPNJBDUSWS8PN` and `/data/app/com.witsoftware.rcsplus.qa-1/base.apk C\:\\Users\\Daniel\\AppData\\Local\\Temp\\com.witsoftware.rcsplus.qa.apk` following https://gist.github.com/notihs/d0ecd7bf44e5451bc8c3734ca95f2551#file-appium_logs_1-9-1_apk_install_fail-L288 


We expect the returned value is like `/data/app/io.appium.settings-1/base.apk: 1 file pulled. 8.5 MB/s (45149 bytes in 0.005s)`

---

ah.. according to the log, `pullApk` probably failed.

https://github.com/appium/appium-android-driver/commit/187c66950ea430fd84704d21035c009cb4bebbc0#diff-97eeab6ebf462ba97a11ee0221ddaf13R509

```
  const app = opts.app || await adb.pullApk(opts.appPackage, opts.tmpDir);
```

https://github.com/appium/appium-uiautomator2-driver/blob/c69adf7b6cceb591e181bdd4fa60abb2f2838c91/lib/driver.js#L387 raises error in `createSession` and calles deleteSession. https://github.com/appium/appium-uiautomator2-driver/blob/c69adf7b6cceb591e181bdd4fa60abb2f2838c91/lib/driver.js#L207

**Comment by lamquangthanh** [comment]
Hello
The same issue with me:

An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'D\:\\android-sdk_r24.4.1-windows\\android-sdk-windows\\platform-tools\\adb.exe -P 5037 -s ZX1G227NJC pull /data/app/com.accor.appli.hybrid-1/base.apk C\:\\Users\\Ekino\\AppData\\Local\\Temp\\com.accor.appli.hybrid.apk' exited with code 1'; Stderr: ''; Code: '1' (WARNING: The server did not provide any stacktrace information

**Comment by KazuCocoa** [comment]
@lamquangthanh 
What value you can get calling `'D:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe -P 5037 -s ZX1G227NJC pull /data/app/com.accor.appli.hybrid-1/base.apk C:\Users\Ekino\AppData\Local\Temp\com.accor.appli.hybrid.apk'` directly on your machine? (Not via Appium.)

**Comment by lamquangthanh** [comment]
@KazuCocoa This log is on Eclipse console. Below is log of appium:

_[debug] [ADB] 'adb uninstall io.appium.uiautomator2.server.test' command output:                              Success
[ADB] io.appium.uiautomator2.server.test was successfully uninstalled
[debug] [ADB] Getting install status for io.appium.uiautomator2.server
[debug] [ADB] Running 'D:\android-sdk_r24.4.1-windows\android-sdk-windows\platfo                             rm-tools\adb.exe -P 5037 -s ZX1G227NJC shell pm list packages io.appium.uiautoma                             tor2.server'
[debug] [ADB] App is not installed
[debug] [ADB] App 'C:\Users\Ekino\AppData\Roaming\npm\node_modules\appium\node_m                             odules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v1.18.0.apk' n                             ot installed. Installing
[debug] [ADB] Running 'D:\android-sdk_r24.4.1-windows\android-sdk-windows\platfo                             rm-tools\adb.exe -P 5037 -s ZX1G227NJC install C\:\\Users\\Ekino\\AppData\\Roami                             ng\\npm\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\a                             ppium-uiautomator2-server-v1.18.0.apk'
[debug] [ADB] Install command stdout: Success
[debug] [ADB] Getting install status for io.appium.uiautomator2.server.test
[debug] [ADB] Running 'D:\android-sdk_r24.4.1-windows\android-sdk-windows\platfo                             rm-tools\adb.exe -P 5037 -s ZX1G227NJC shell pm list packages io.appium.uiautoma                             tor2.server.test'
[debug] [ADB] App is not installed
[debug] [ADB] App 'C:\Users\Ekino\AppData\Roaming\npm\node_modules\appium\node_m                             odules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidT                             est.apk' not installed. Installing
[debug] [ADB] Running 'D:\android-sdk_r24.4.1-windows\android-sdk-windows\platfo                             rm-tools\adb.exe -P 5037 -s ZX1G227NJC install C\:\\Users\\Ekino\\AppData\\Roami                             ng\\npm\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\a                             ppium-uiautomator2-server-debug-androidTest.apk'
[debug] [ADB] Install command stdout: Success
[debug] [UiAutomator2] Waiting up to 20000ms for instrumentation 'io.appium.uiau                             tomator2.server.test/android.support.test.runner.AndroidJUnitRunner' to be avail                             able
[debug] [ADB] Running 'D:\android-sdk_r24.4.1-windows\android-sdk-windows\platfo                             rm-tools\adb.exe -P 5037 -s ZX1G227NJC shell pm list instrumentation'
[debug] [UiAutomator2] Instrumentation 'io.appium.uiautomator2.server.test/andro                             id.support.test.runner.AndroidJUnitRunner' available
[debug] [ADB] Running 'D:\android-sdk_r24.4.1-windows\android-sdk-windows\platfo                             rm-tools\adb.exe -P 5037 -s ZX1G227NJC wait-for-device'
[debug] [ADB] Running 'D:\android-sdk_r24.4.1-windows\android-sdk-windows\platfo                             rm-tools\adb.exe -P 5037 -s ZX1G227NJC shell echo ping'
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Getting install status for io.appium.settings
[debug] [ADB] Running 'D:\android-sdk_r24.4.1-windows\android-sdk-windows\platfo                             rm-tools\adb.exe -P 5037 -s ZX1G227NJC shell pm list packages io.appium.settings                             '
[debug] [ADB] App is installed
[debug] [ADB] Getting package info for 'io.appium.settings'
[debug] [ADB] Running 'D:\android-sdk_r24.4.1-windows\android-sdk-windows\platfo                             rm-tools\adb.exe -P 5037 -s ZX1G227NJC shell dumpsys package io.appium.settings'
[ADB] Checking whether aapt is present
[ADB] Using aapt.exe from D:\android-sdk_r24.4.1-windows\android-sdk-windows\bui                             ld-tools\28.0.2\aapt.exe
[debug] [ADB] The installed 'io.appium.settings' package does not require upgrad                             e ('2.3.0' >= '2.3.0')
[debug] [ADB] Running 'D:\android-sdk_r24.4.1-windows\android-sdk-windows\platfo                             rm-tools\adb.exe -P 5037 -s ZX1G227NJC shell ps'
[debug] [ADB] Device API level: 24
[debug] [ADB] Running 'D:\android-sdk_r24.4.1-windows\android-sdk-windows\platfo                             rm-tools\adb.exe -P 5037 -s ZX1G227NJC shell am start -W -n io.appium.settings/.                             Settings -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x                             10200000'
[debug] [ADB] Device API level: 24
[debug] [ADB] Running 'D:\android-sdk_r24.4.1-windows\android-sdk-windows\platfo                             rm-tools\adb.exe -P 5037 -s ZX1G227NJC shell appops set io.appium.settings andro                             id\:mock_location allow'
[debug] [ADB] Device API level: 24
[debug] [ADB] Running 'D:\android-sdk_r24.4.1-windows\android-sdk-windows\platfo                             rm-tools\adb.exe -P 5037 -s ZX1G227NJC shell getprop persist.sys.locale'
[debug] [ADB] Current device property 'persist.sys.locale': en-GB
[debug] [ADB] Current locale: 'en-GB'; requested locale: 'en-GB'
[debug] [ADB] Device API level: 24
[debug] [ADB] Running 'D:\android-sdk_r24.4.1-windows\android-sdk-windows\platfo                             rm-tools\adb.exe -P 5037 -s ZX1G227NJC shell getprop persist.sys.locale'
[debug] [ADB] Current device property 'persist.sys.locale': en-GB
[debug] [Logcat] Starting logcat capture
[debug] [AndroidDriver] Pushing unlock helper app to device...
[debug] [ADB] Getting install status for io.appium.unlock
[debug] [ADB] Running 'D:\android-sdk_r24.4.1-windows\android-sdk-windows\platfo                             rm-tools\adb.exe -P 5037 -s ZX1G227NJC shell pm list packages io.appium.unlock'
[debug] [ADB] App is installed
[debug] [ADB] Getting package info for 'io.appium.unlock'
[debug] [ADB] Running 'D:\android-sdk_r24.4.1-windows\android-sdk-windows\platfo                             rm-tools\adb.exe -P 5037 -s ZX1G227NJC shell dumpsys package io.appium.unlock'
[debug] [ADB] The installed 'io.appium.unlock' package does not require upgrade                              ('2.0.0' >= '2.0.0')
[debug] [UiAutomator2] Forwarding UiAutomator2 Server port 6790 to 8200
[debug] [ADB] Forwarding system: 8200 to device: 6790
[debug] [ADB] Running 'D:\android-sdk_r24.4.1-windows\android-sdk-windows\platfo                             rm-tools\adb.exe -P 5037 -s ZX1G227NJC forward tcp\:8200 tcp\:6790'
[debug] [ADB] Running 'D:\android-sdk_r24.4.1-windows\android-sdk-windows\platfo                             rm-tools\adb.exe -P 5037 -s ZX1G227NJC shell rm -rf /data/local/tmp/strings.json                             '
[debug] [ADB] Running 'D:\android-sdk_r24.4.1-windows\android-sdk-windows\platfo                             rm-tools\adb.exe -P 5037 -s ZX1G227NJC shell pm path com.accor.appli.hybrid'
[debug] [ADB] Running 'D:\android-sdk_r24.4.1-windows\android-sdk-windows\platfo                             rm-tools\adb.exe -P 5037 -s ZX1G227NJC pull /data/app/com.accor.appli.hybrid-1/b                             ase.apk C\:\\Users\\Ekino\\AppData\\Local\\Temp\\com.accor.appli.hybrid.apk'
[debug] [ADB] Running 'D:\android-sdk_r24.4.1-windows\android-sdk-windows\platfo                             rm-tools\adb.exe -P 5037 -s ZX1G227NJC pull /data/app/com.accor.appli.hybrid-1/b                             ase.apk C\:\\Users\\Ekino\\AppData\\Local\\Temp\\com.accor.appli.hybrid.apk'
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[debug] [JSONWP Proxy] Matched '/' to command name 'deleteSession'
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error                              was: UnknownError: An unknown server-side error occurred while processing the c                             ommand. Original error: Trying to proxy a session command without session id
[debug] [ADB] Running 'D:\android-sdk_r24.4.1-windows\android-sdk-windows\platfo                             rm-tools\adb.exe -P 5037 -s ZX1G227NJC shell am force-stop com.accor.appli.hybri                             d'
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8200
[debug] [ADB] Running 'D:\android-sdk_r24.4.1-windows\android-sdk-windows\platfo                             rm-tools\adb.exe -P 5037 -s ZX1G227NJC forward --remove tcp\:8200'
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1537761719796 (11:01:59                              GMT+0700 (SE Asia Standard Time))
[debug] [MJSONWP] Encountered internal error running command: Error: Error execu                             ting adbExec. Original error: 'Command 'D\:\\android-sdk_r24.4.1-windows\\androi                             d-sdk-windows\\platform-tools\\adb.exe -P 5037 -s ZX1G227NJC pull /data/app/com.                             accor.appli.hybrid-1/base.apk C\:\\Users\\Ekino\\AppData\\Local\\Temp\\com.accor                             .appli.hybrid.apk' exited with code 1'; Stderr: ''; Code: '1'
[debug] [MJSONWP]     at ADB.execFunc$ (C:\Users\Ekino\AppData\Roaming\npm\node_                             modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:327:13)
[debug] [MJSONWP]     at tryCatch (C:\Users\Ekino\AppData\Roaming\npm\node_modul                             es\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[debug] [MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\User                             s\Ekino\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regen                             erator\runtime.js:315:22)
[debug] [MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous functio                             n) [as throw] (C:\Users\Ekino\AppData\Roaming\npm\node_modules\appium\node_modul                             es\babel-runtime\regenerator\runtime.js:100:21)
[debug] [MJSONWP]     at GeneratorFunctionPrototype.invoke (C:\Users\Ekino\AppDa                             ta\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtim                             e.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 33216 ms - 471
[HTTP]_

**Comment by KazuCocoa** [comment]
@lamquangthanh 
Thanks! But what I'd like to know is an original output by https://github.com/appium/appium/issues/11403#issuecomment-423871543 .

You can call the adb command directly via command prompt. Appium handles outputs by commands internally. So, I'd like to observe it. Could you try it?

It means probably something happens around below process. If it is because of adb command, we must handle some error case.

```
[debug] [ADB] Running 'D:\android-sdk_r24.4.1-windows\android-sdk-windows\platfo rm-tools\adb.exe -P 5037 -s ZX1G227NJC pull /data/app/com.accor.appli.hybrid-1/b ase.apk C:\Users\Ekino\AppData\Local\Temp\com.accor.appli.hybrid.apk'
[debug] [ADB] Running 'D:\android-sdk_r24.4.1-windows\android-sdk-windows\platfo rm-tools\adb.exe -P 5037 -s ZX1G227NJC pull /data/app/com.accor.appli.hybrid-1/b ase.apk C:\Users\Ekino\AppData\Local\Temp\com.accor.appli.hybrid.apk'
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
```

**Comment by lamquangthanh** [comment]
@KazuCocoa  https://gist.github.com/lamquangthanh/3d27676959ddba6b2cbd045442710266

All log of appium that i had. Hope it helped you handle some error case.

**Comment by KazuCocoa** [comment]
Thanks, but it isn't I meant. @lamquangthanh 

> But what I'd like to know is an original output by #11403 (comment) .
> You can call the adb command directly via command prompt

I meant what output you can get by `D:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe -P 5037 -s ZX1G227NJC pull /data/app/com.accor.appli.hybrid-1/base.apk C:\Users\Ekino\AppData\Local\Temp\com.accor.appli.hybrid.apk` via https://www.lifewire.com/how-to-open-command-prompt-2618089 .

**Comment by lamquangthanh** [comment]
@KazuCocoa my ouput:
_adb: error: remote object '/data/app/com.accor.appli.hybrid-1/base.apk' does not exist_

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-android-driver/pull/430/files

If you can use https://github.com/appium/appium directly, could you try below?
```
$ cd node_modules/appium-android-driver/
$ vi lib/android-helpers.js # Apply https://github.com/appium/appium-android-driver/pull/430/files#diff-97eeab6ebf462ba97a11ee0221ddaf13R509
$ npm install # or gulp transpile
$ cd ../..
$ node .
# Run your tests
```

@lamquangthanh

**Comment by lamquangthanh** [comment]
@KazuCocoa 
After do as followed your steps:
**-The appium version is 1.8.1:**
_$ node .
[Appium] Appium support for versions of node < 8 has been deprecated and will be
 removed in a future version. Please upgrade!
[Appium] Welcome to Appium v1.8.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723_
**-Log of Eclipse:**
_An unknown server-side error occurred while processing the command. Original error: Could not sign with default certificate. Original error Command ''C:\\Program Files\\Java\\jre1.8.0_171\\bin\\java.exe' -jar C\:\\Windows\\System32\\node_modules\\appium\\node_modules\\appium-adb\\jars\\sign.jar C\:\\Windows\\System32\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v1.12.0.apk --override' exited with code 1 (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 8.23 seconds_
**-Log of Appium:**
_[debug] [ADB] Resigning apk.
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error
 was: Error: Trying to proxy a session command without session id
[debug] [ADB] Running 'D:\android-sdk_r24.4.1-windows\android-sdk-windows\platfo
rm-tools\adb.exe -P 5037 -s ZX1G227NJC shell am force-stop com.accor.appli.hybri
d'
[debug] [ADB] Removing forwarded port socket connection: 8200
[debug] [ADB] Running 'D:\android-sdk_r24.4.1-windows\android-sdk-windows\platfo
rm-tools\adb.exe -P 5037 -s ZX1G227NJC forward --remove tcp\:8200'
[debug] [ADB] Running 'D:\android-sdk_r24.4.1-windows\android-sdk-windows\platfo
rm-tools\adb.exe -P 5037 -s ZX1G227NJC forward --remove tcp\:8200'
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original
error: 'Command 'D\:\\android-sdk_r24.4.1-windows\\android-sdk-windows\\platform
-tools\\adb.exe -P 5037 -s ZX1G227NJC forward --remove tcp\:8200' exited with co
de 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1537775402894 (14:50:02
 GMT+0700 (SE Asia Standard Time))
[MJSONWP] Encountered internal error running command: Error: Could not sign with
 default certificate. Original error Command ''C:\\Program Files\\Java\\jre1.8.0
_171\\bin\\java.exe' -jar C\:\\Windows\\System32\\node_modules\\appium\\node_mod
ules\\appium-adb\\jars\\sign.jar C\:\\Windows\\System32\\node_modules\\appium\\n
ode_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v1.12.
0.apk --override' exited with code 1
[MJSONWP]     at ADB.callee$0$0$ (C:\Windows\System32\node_modules\appium\node_m
odules\appium-adb\lib\tools\apk-signing.js:79:13)
[MJSONWP]     at tryCatch (C:\Windows\System32\node_modules\appium\node_modules\
babel-runtime\regenerator\runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Windows\Syst
em32\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:2
2)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as t
hrow] (C:\Windows\System32\node_modules\appium\node_modules\babel-runtime\regene
rator\runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (C:\Windows\System32\node_mod
ules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 7953 ms - 556
[HTTP]_

**Comment by KazuCocoa** [comment]
Could you try with current the latest master? Since 1.8.1 has different code.

**Comment by lamquangthanh** [comment]
@KazuCocoa this meant uninstall and install again with appium version 1.9.1?

**Comment by notihs** [comment]
Hi @KazuCocoa 
Sry for the late response. In my case, after running 
`> C:\AndroidSDK\platform-tools\adb.exe -P 5037 -s QGZSPNJBDUSWS8PN pull /data/app/com.witsoftware.rcsplus.qa-1/base.apk C\:\\Users\\Daniel\\AppData\\Local\\Temp\\com.witsoftware.rcsplus.qa.apk`

I get this as result: 
`The process cannot access the file because it is being used by another process.`

**Comment by lamquangthanh** [comment]
@KazuCocoa after install as your steps:

_Ekino@EVN-D-W-0017 MINGW64 ~/node_modules/appium/node_modules/appium-android-dri                                                                                                                                                                                               ver
$ npm install
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly                                                                                                                                                                                               ` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` fo                                                                                                                                                                                               r more information.

> appium-android-driver@2.7.0 prepublish C:\Users\Ekino\node_modules\appium\node                                                                                                                                                                                               _modules\appium-android-driver
> gulp prepublish

[16:25:40] Using gulpfile ~\node_modules\appium\node_modules\appium-android-driver\gulpfile.js
[16:25:40] Starting 'prepublish'...
[16:25:40] Starting 'clean'...
[16:25:40] Finished 'clean' after 290 ms
[16:25:40] Starting 'transpile'...
[16:25:49] Finished 'transpile' after 9.32 s
[16:25:49] Finished 'prepublish' after 9.61 s
audited 27172 packages in 57.058s
found 0 vulnerabilities_

**Got the same error above:**

_An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'D\:\\android-sdk_r24.4.1-windows\\android-sdk-windows\\platform-tools\\adb.exe -P 5037 -s ZX1G227NJC pull /data/app/com.accor.appli.hybrid-1/base.apk C\:\\Users\\Ekino\\AppData\\Local\\Temp\\com.accor.appli.hybrid.apk' exited with code 1'; Stderr: ''; Code: '1' (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 34.00 seconds_

**Comment by KazuCocoa** [comment]
@lamquangthanh Could you attach a gist of entire the server log?
If changed `lib/android-helpers.js` like https://github.com/appium/appium-android-driver/pull/430/files#diff-97eeab6ebf462ba97a11ee0221ddaf13R509` expectedly in https://github.com/appium/appium/issues/11403#issuecomment-423905289 steps, we can see a message like `Failed to pull an apk from....` there.

**Comment by KazuCocoa** [comment]
@notihs 
Thanks! hm.. a process conflict..
Could you apply https://github.com/appium/appium-android-driver/pull/430/files in your local and reproduce the error? And I'm happy if you attach the server log eigher works well or not.

hint: https://github.com/appium/appium/issues/11403#issuecomment-423905289

**Comment by lamquangthanh** [comment]
@KazuCocoa please have a look on my **android-helpers** file:
https://gist.github.com/lamquangthanh/deece57f2957e05601db6a14f4d3275d

**Comment by KazuCocoa** [comment]
Hm, it isn't the latest one since some .

Assumption: You have `appium` directory which is git cloned.

```
# Remove `appium/node_modules`, first
$ npm install
$ cd node_modules/appium-android-driver/
$ vi lib/android-helpers.js # Apply https://github.com/appium/appium-android-driver/pull/430/files#diff-97eeab6ebf462ba97a11ee0221ddaf13R509
$ npm install # or gulp transpile in `appium-android-driver`
$ cd ../..
$ node .
# Run your tests
```

After the running, you probably can see below message

```
$ node .
[Appium] Welcome to Appium v1.9.2-beta.1 (REV 0e506d38c98ee4c9743b7c6d531f38e496828f99)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
```

**Comment by lamquangthanh** [comment]
@KazuCocoa Is it the same way with **npm uninstall -g appium**  and **npm install -g appium@1.9.2-beta.1**???

**Comment by notihs** [comment]
Hi again @KazuCocoa 
The app has launched now and your error was thrown at https://gist.github.com/notihs/fa947a1d08fc051eb647450b4f20dfe4#file-appium-logs-with-latest-fix-L153

Full logs:
https://gist.github.com/notihs/fa947a1d08fc051eb647450b4f20dfe4

**Comment by KazuCocoa** [comment]
@lamquangthanh Similar, but you need to apply https://github.com/appium/appium-android-driver/pull/430 to your local code and re-build it

@notihs 
Thanks! The behaviour is expected to me. (the log as well.)

**Comment by lamquangthanh** [comment]
@KazuCocoa 
![image](https://user-images.githubusercontent.com/29390692/45949354-d6828100-c025-11e8-8f7d-aa3e1c6913c1.png)
Apply new **android-helper** file like picture? And open another cmd to put **npm install**?? Is it right?

**Comment by KazuCocoa** [comment]
@lamquangthanh 
After releasing https://github.com/appium/appium-android-driver/pull/430 , you can try it installing `npm install -g appium@beta`. (You don't need to change code/re-build it.)
Please wait for the release.

cc @notihs 
The change will be available in `appium@beta` soon.
