### ISSUE TITLE
The “TouchActions” is not available

### ISSUE THREAD

**Issue by sjlnl** [appium/appium#11414]
## The problem
The “TouchActions” is not available
When I use TouchActions to perform some H5 operations, an error is reported

## Environment

* Appium version (or git revision) that exhibits the issue:  appium 1.8.1、java-client 6.1.0、selenium 3.14.0

## Details
When I use TouchActions to perform some H5 operations, an error is reported

The error message：
java.lang.ClassCastException: io.appium.java_client.android.AndroidDriver cannot be cast to org.openqa.selenium.interactions.HasTouchScreen

## Code To Reproduce Issue [ Good To Have ]

TouchActions action = new TouchActions(driver);
action.down(540, 1590).perform();

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/appium/java-client
