### ISSUE TITLE
I'm Using "Name" Locator But Getting Error -Locator Strategy 'css selector' is not supported for this session

### ISSUE THREAD

**Issue by Nagu7190** [appium/appium#11410]
## The problem

I'm trying to click on an element using name.
driver.findElementByName("Scrolling").click(); 
But i'm getting error like invalid css selector But this code working fine in commandline appium

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.0(desktop)
* Last Appium version that did not exhibit the issue (if applicable): 1.8.2beta(cmdline)
* Desktop OS/version used to run Appium: MacOS High Sierra
* Node.js version (unless using Appium.app|exe): v8.11.1
* Mobile platform/version under test: iPhone 7 (iOS 11.4)
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium.app

## Link to Appium logs

[Appium] New XCUITestDriver session created successfully, session 38d89f52-0d0c-4a13-b554-31735a517776 added to master session list
[BaseDriver] Event 'newSessionStarted' logged at 1537788292334 (16:54:52 GMT+0530 (IST))
[W3C] Responding to client with driver.createSession() result: {"capabilities":{"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"IOS","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"platformName":"ios","bundleId":"com.facebook.wda.integrationApp","deviceName":"Orugunta’s iPhone","platformVersion":"11.1","udid":"e647c2802660d73c9340fb00411373e4b5068960"}}
[HTTP] <-- POST /wd/hub/session 200 12997 ms - 451
[HTTP] 
[HTTP] --> POST /wd/hub/session/38d89f52-0d0c-4a13-b554-31735a517776/element
[HTTP] {"value":"*[name='Scrolling']","using":"css selector"}
[W3C] Calling AppiumDriver.findElement() with args: ["css selector","*[name='Scrolling']","38d89f52-0d0c-4a13-b554-31735a517776"]
[XCUITest] Executing command 'findElement'
[BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[W3C] Encountered internal error running command: InvalidSelectorError: Locator Strategy 'css selector' is not supported for this session
[W3C]     at XCUITestDriver.validateLocatorStrategy (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:349:13)
[W3C]     at XCUITestDriver.validateLocatorStrategy (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:111:21)
[W3C]     at XCUITestDriver.callee$0$0$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:26:8)
[W3C]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[W3C]     at invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[W3C]     at enqueueResult (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
[W3C]     at new Promise ()
[W3C]     at new F (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
[W3C]     at AsyncIterator.enqueue (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
[W3C]     at AsyncIterator.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[W3C]     at Object.runtime.async 

## Code To Reproduce Issue [ Good To Have ]

          DesiredCapabilities capabilities= new DesiredCapabilities();
	  capabilities.setCapability("platformName", "iOS");
          capabilities.setCapability("deviceName", "nagu’s iPhone");
          capabilities.setCapability("platformVersion", "11.4");
          capabilities.setCapability(CapabilityType.PLATFORM,"iOS");
          capabilities.setCapability("bundleId", "com.facebook.wda.integrationApp");
          capabilities.setCapability("udid", "XXXXX");

           IOSDriver driver= new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
	   Thread.sleep(2000);
	   driver.findElementByName("Scrolling").click();

Thank You in Advance....

**Comment by sandeepmosali** [comment]
Hi @Nagu7190 

Please use in below format it should work ( i mean use '~')
driver.findElementByName("~Scrolling").click();

Thanks 
Sandeep

**Comment by mykola-mokhnach** [comment]
This must be client issue. Which client version do you use?

**Comment by Nagu7190** [comment]
Thanks for reply...
I'm using Java-client 5.0.4

**Comment by mykola-mokhnach** [comment]
Upgrade it to 6.1.0

**Comment by Nagu7190** [comment]
Hi Mykola,

I tried already Updated java-client 6.1.0 but it's not working for me.
And my selenium version is 3.8.1

Thank You,

**Comment by mykola-mokhnach** [comment]
The selenium api version should be the same as it is used by the client. You should not override it.

**Comment by mykola-mokhnach** [comment]
Closed as client side issue. New server version requires updated client.
