### ISSUE TITLE
Appium1.9.0 switch to webview failed

### ISSUE THREAD

**Issue by hibean** [appium/appium#11418]
## The problem

appium switch to weview failed.

I dont understand why appium don't solve this bug for a long time,so many people get this issue,but appium dont care about this. i am so disappointed for this. i have followed this for months.

who can tell me why??

## Environment

Appium：1.9.0
Android version：7.1.2
chrome：64

**Comment by vjmaiky** [comment]
strange; i'm using 1.9.0 and i can switch to android webview and back to native; also on iOS

**Comment by hibean** [comment]
> strange; i'm using 1.9.0 and i can switch to android webview and back to native; also on iOS

HI,thank u for reply!
It work well on android 5 and appium 1.8.0,switch to webview from native.

but it failed on android 7 and appium 1.9.0.

can you tell me how to do ? android

**Comment by vjmaiky** [comment]
Tried now on Android 9 with latest appium beta and worked without any problem:

```

    public static Set<String> getContextHandles() throws WebDriverException {
        return driver.getContextHandles();
    }

    public static void switchToWebview() throws Exception {
        MyLogger.log.info("Trying to switch to first non NATIVE_APP view");
        boolean foundNonNativeContext = false;
        for (String context : getContextHandles()) {
            if ((!foundNonNativeContext) && !NATIVE_APP.equals(context)) {
                foundNonNativeContext = true;
                MyLogger.log.info("Found non native context: " + context);
                switchToContext(context);
            }
        }
        if (!foundNonNativeContext) {
            MyLogger.log.info("ONLY NATIVE_APP CONTEXT AVAILABLE");
        }
    }

    public static void switchToContext(String context) throws Exception {
        MyLogger.log.info("Trying to switch to : " + context);
        getAllContexts();
        if (Drivers.getMobileDriver().getContext().contains(context)) {
            MyLogger.log.info("Already on context " + context);
        } else {
            Drivers.getMobileDriver().getContextHandles();
            try {
                Drivers.getMobileDriver().context(context);
                MyLogger.log.info("Successfully switched to : " + context);
            } catch (NoSuchContextException e) {
                MyLogger.log.error("Could not switch to context " + context);
                throw e;
            }
        }

    }

    public static void switchToNative() {
        MyLogger.log.info("Trying to switch from WEBVIEW to NATIVE_APP context");
        if (Drivers.getMobileDriver().getContext().equalsIgnoreCase(NATIVE_APP)) {
            MyLogger.log.info("NATIVE_APP is already set as context");
        } else {
            Drivers.getMobileDriver().getContextHandles();
            try {
                Drivers.getMobileDriver().context(NATIVE_APP);
                MyLogger.log.info("Successfully switched to NATIVE_APP contexts");
            } catch (NoSuchContextException e) {
                MyLogger.log.error("Could not switch to NATIVE_APP context");
                throw e;
            }
        }

    }
```

**Comment by mykola-mokhnach** [comment]
Closed as incomplete

**Comment by hibean** [comment]
> Tried now on Android 9 and 6 with latest appium beta and worked without any problem:
> 
> ```
> 
>     public static Set<String> getContextHandles() throws WebDriverException {
>         return driver.getContextHandles();
>     }
> 
>     public static void switchToWebview() throws Exception {
>         MyLogger.log.info("Trying to switch to first non NATIVE_APP view");
>         boolean foundNonNativeContext = false;
>         for (String context : getContextHandles()) {
>             if ((!foundNonNativeContext) && !NATIVE_APP.equals(context)) {
>                 foundNonNativeContext = true;
>                 MyLogger.log.info("Found non native context: " + context);
>                 switchToContext(context);
>             }
>         }
>         if (!foundNonNativeContext) {
>             MyLogger.log.info("ONLY NATIVE_APP CONTEXT AVAILABLE");
>         }
>     }
> 
>     public static void switchToContext(String context) throws Exception {
>         MyLogger.log.info("Trying to switch to : " + context);
>         getAllContexts();
>         if (Drivers.getMobileDriver().getContext().contains(context)) {
>             MyLogger.log.info("Already on context " + context);
>         } else {
>             Drivers.getMobileDriver().getContextHandles();
>             try {
>                 Drivers.getMobileDriver().context(context);
>                 MyLogger.log.info("Successfully switched to : " + context);
>             } catch (NoSuchContextException e) {
>                 MyLogger.log.error("Could not switch to context " + context);
>                 throw e;
>             }
>         }
> 
>     }
> 
>     public static void switchToNative() {
>         MyLogger.log.info("Trying to switch from WEBVIEW to NATIVE_APP context");
>         if (Drivers.getMobileDriver().getContext().equalsIgnoreCase(NATIVE_APP)) {
>             MyLogger.log.info("NATIVE_APP is already set as context");
>         } else {
>             Drivers.getMobileDriver().getContextHandles();
>             try {
>                 Drivers.getMobileDriver().context(NATIVE_APP);
>                 MyLogger.log.info("Successfully switched to NATIVE_APP contexts");
>             } catch (NoSuchContextException e) {
>                 MyLogger.log.error("Could not switch to NATIVE_APP context");
>                 throw e;
>             }
>         }
> 
>     }
> ```

it's a bug,appium don't support other webkit that is not chrome webkit.
