### ISSUE TITLE
Updating tests to 1.9.0 and above causes "Method has not yet been implemented" in AppiumDriver.getElementRect()

### ISSUE THREAD

**Issue by CoryWritesCode** [appium/appium#11427]
## The problem

For some reason it seems like appium is finding elements with `AppiumDriver.getElementRect()` and returning with the error `Method has not yet been implemented` causing all scenarios to fail. Seems like it might have something to do when we try to invoke `element.location` (Selenium::WebDriver::Element). Let me know what other info you might need to help.

On android it will find the elements but fails at `scroll_into_view`.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable):1.8.2-beta
* Desktop OS/version used to run Appium: Mojave
* Node.js version (unless using Appium.app|exe): 10.3.0
* Mobile platform/version under test: Any iOS
* Real device or emulator/simulator: iPhone
* Appium CLI or Appium.app|exe: `bundle exec rake <tests>`

## Details

Same tests run correctly on 1.8.2-beta

## Link to Appium logs

https://gist.github.com/CoryWritesCode/82c33f1e4b31dfb6f33539c8b3c82785

**Comment by KazuCocoa** [comment]
Could you try again after uninstall and install the appium? @CoryWritesCode 

I could get like below. (Current the latest master though)

```
[HTTP] --> GET /wd/hub/session/6e86e001-1b1f-4d63-9bbf-133f93c8f07f/element/0D000000-0000-0000-9DA8-000000000000/rect
[HTTP] {}
[W3C] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Matched '/wd/hub/session/6e86e001-1b1f-4d63-9bbf-133f93c8f07f/element/0D000000-0000-0000-9DA8-000000000000/rect' to command name 'getElementRect'
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/6e86e001-1b1f-4d63-9bbf-133f93c8f07f/element/0D000000-0000-0000-9DA8-000000000000/rect] to [GET http://localhost:8100/session/D01994AE-F40B-4354-A30E-57185F04B784/element/0D000000-0000-0000-9DA8-000000000000/rect] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"y\" : 24,\n    \"x\" : 0,\n    \"width\" : 375,\n    \"height\" : 52\n  },\n  \"sessionId\" : \"D01994AE-F40B-4354-A30E-57185F04B784\",\n  \"status\" : 0\n}"
[JSONWP Proxy] Replacing sessionId D01994AE-F40B-4354-A30E-57185F04B784 with 6e86e001-1b1f-4d63-9bbf-133f93c8f07f
[HTTP] <-- GET /wd/hub/session/6e86e001-1b1f-4d63-9bbf-133f93c8f07f/element/0D000000-0000-0000-9DA8-000000000000/rect 200 158 ms - 110
[HTTP]
```

command:

```ruby
      e = @driver.find_element :accessibility_id, 'UICatalog'
      e.rect
```

**Comment by mykola-mokhnach** [comment]
this might be the case for web views, since these still use MJSONWP protocol, for which the /rect method is undefined. We cannot change much there unless downstream webdrivers fully support W3C spec

**Comment by CoryWritesCode** [comment]
@mykola-mokhnach How would I go about swapping my protocol over to W3C spec?

**Comment by mykola-mokhnach** [comment]
This does not depend on you but rather on mobile safari maintainers. You could still use location+size to get the actual rect

**Comment by CoryWritesCode** [comment]
Do you have an idea of what that might look like with the test I provided? I'm somewhat confused what happened to make the tests we have written with Selenium to no longer pass with upgrading the appium version.

**Comment by KazuCocoa** [comment]
@CoryWritesCode 
I'm not sure which client do you use. But if you use Appium client, you can set `forceMjsonwp: true` in desired capability. Then, Clients create a session as MJSONProtocol (not W3C).

In the case, all communication between client and Appium server become MJSONWP

**Comment by mykola-mokhnach** [comment]
@KazuCocoa This won't help. We are talking here about the missing endpoint, which is implemented for desktop client, but does not exist for the mobile one.

**Comment by CoryWritesCode** [comment]
How can I implement the endpoint?
We are using Selenium Webdriver to test our mobile app since the app uses a webview.

**Comment by mykola-mokhnach** [comment]
You don't need to implement it. Like I said you can still use the combination of `location` and `size` to replace `rect`. 

All the endpoints endpoints are implemented using selenium atoms. Check https://github.com/appium/appium-ios-driver/tree/master/lib/commands for more details

**Comment by KazuCocoa** [comment]
ah, i see > missing endpoint

**Comment by CoryWritesCode** [comment]
I think the issue is that we are not explicitly calling `rect` but it seems to do it automatically.

**Comment by KazuCocoa** [comment]
ah, you use Ruby > `bundle exec rake <tests>`

`element.location` calls `/rect` in W3C. But it calls `/location` in MJSONWP.
So, to call `/location` behind `element.location`, you should establish a session based on MJSONWP setting `forceMjsonwp: true` in your capability. Then, you can call `/location` behind `element.location` because the session works as MJSONWP

`element.location` = `/location` => Appium = `/location` => mobile safari


---

`element.rect` calls combination of `/location` and `/size` in MJSONWP, btw

**Comment by CoryWritesCode** [comment]
@KazuCocoa Where would I set that to true?

**Comment by KazuCocoa** [comment]
Can you share entire your server log?
If the client establishes the session with non W3C, the client has no method to call `/rect` endpoint.
I wonder which endpoint leads `AppiumDriver.getElementRect()`

**Comment by CoryWritesCode** [comment]
@KazuCocoa https://gist.github.com/CoryWritesCode/8154a0d5a1eebc5362b2ac0eee105ed3

**Comment by KazuCocoa** [comment]
Thanks.

https://gist.github.com/CoryWritesCode/8154a0d5a1eebc5362b2ac0eee105ed3#file-full_appium_log-L5 in this line, `firstMatch` shouldn't send it to servers if you specify `forceMjsonwp: true`...

@CoryWritesCode 
Could you share your current client version and the capability?
If `forceMjsonwp: true` doesn't work, I should fix it in client side.

**Comment by CoryWritesCode** [comment]
I'm sorry, what do you mean by client version in this context?
Appium - 1.9.1
Node - 10.3.0

Gem list (not all gems) - 
appium_lib - 9.15.1
appium_lib_core - 2.0.1
httparty - 0.16.2
httpclient - 2.8.3
rake - 12.3.1
rake-compiler - 1.0.5
selenium - 0.2.11
selenium-webdriver - 3.14.0

**Comment by CoryWritesCode** [comment]
```
caps: {
        platformName: @platform_name,
        platformVersion: @platform_version,
        deviceName: @name,
        udid: @udid,
        app: EnvVarManager.app_path,
        automationName: @automation_name,
        autoWebview: true,
        xcodeOrgId: (EnvVarManager.ios_team_id if EnvVarManager.platform_ios?),
        xcodeSigningId: ('iPhone Developer' if EnvVarManager.platform_ios?),
        chromeDriverPort: EnvVarManager.chromedriver_port.to_i,
        systemPort: EnvVarManager.system_port.to_i,
        wdaLocalPort: EnvVarManager.wda_local_port.to_i,
        webkitDebugProxyPort: EnvVarManager.iwdp_port.to_i,
        forceMjsonwp: true
      }
```

**Comment by CoryWritesCode** [comment]
Let me know if you need different/other info!

**Comment by KazuCocoa** [comment]
@CoryWritesCode 

Thanks! I meant below, especially `appium_lib`.

> appium_lib - 9.15.1
> appium_lib_core - 2.0.1

I couldn't reproduce in current repositories of appium_lib and appium_lib_core

I've added some logs in appium_lib_core. Can you specify below branch in your Gemfile? And could you give me the Ruby side's logs?

https://github.com/KazuCocoa/ruby_lib_core/tree/add-inspect

We expect below log appear there if you set the branch correctly.

```
------in merged_capabilities-------
#<Selenium::WebDriver::Remote::W3C::Capabilities:0x00007f9204ab20c8 @capabilities={:forceMjsonwp=>true, :platformName=>:ios, :automationName=>"XCUITest", :app=>"/Users/kazuaki/GitHub/ruby_lib_core/test/functional/app/UICatalog.app", :platformVersion=>"10.3", :deviceName=>"iPhone 6", :useNewWDA=>true, :useJSONSource=>true, :someCapability=>"some_capability", :newCommandTimeout=>120, :wdaLocalPort=>8100, :proxy=>nil}>
#<Selenium::WebDriver::Remote::W3C::Capabilities:0x00007f92049bab48 @capabilities={:proxy=>nil, :platformName=>:ios, :automationName=>"XCUITest", :app=>"/Users/kazuaki/GitHub/ruby_lib_core/test/functional/app/UICatalog.app", :platformVersion=>"10.3", :deviceName=>"iPhone 6", :useNewWDA=>true, :useJSONSource=>true, :someCapability=>"some_capability", :newCommandTimeout=>120, :wdaLocalPort=>8100}>
------after delete_force_mjsonwp------

```

**Comment by KazuCocoa** [comment]
@CoryWritesCode 
Could you specify https://github.com/KazuCocoa/ruby_lib_core/tree/add-inspect branch as `appium_lib_core` in your gemfile and run your tests? And could you attach the log in client side (on Ruby code side) and appium server side?

In the branch, I've added some logs.
I hope the log helps us to clarify why `forceMjsonwp` doesn't work in your environment.
https://github.com/appium/appium/issues/11427#issuecomment-425100006

**Comment by mykola-mokhnach** [comment]
The /rect handler has been published to appium@beta

**Comment by svetikshark** [comment]
having the same issue 
[debug] [XCUITest] Executing command 'getElementRect' 
appium - latest
even after setting caps forceMjsonwp  
/usr/local/bin/appium  -p 4723 --log-timestamp --nodeconfig /var/gridextras/node_4723.json --log /var/gridextras/log/node_4723.log  -dc '{"deviceName":"iPhone",  "automationName": "XCUITest", "udid": "***", "platformVersion": "12.0","xcodeOrgId": "***" ,"updatedWDABundleId":"com.test.jabundle1" ,"newCommandTimeout":60,"forceMjsonwp": "true"}'

**Comment by svetikshark** [comment]
or do I need to open another issue?

**Comment by mykola-mokhnach** [comment]
@svetikshark beta and latest is not the same thing

**Comment by svetikshark** [comment]
Welcome to Appium v1.9.2-beta.1 - well - may be it is not the same thing but issue is the same

**Comment by mykola-mokhnach** [comment]
What is the version of appium-xcuitest-driver component?

**Comment by CoryWritesCode** [comment]
What's your `appium_lib` @svetikshark?

**Comment by CoryWritesCode** [comment]
@KazuCocoa I'm working on getting your those results, I've been a bit busier haha.

**Comment by svetikshark** [comment]
Thanks fellas, don't know where to check exactly - but based on package json  in appium-xcuitest-driver folder it is 2.96 - is there any command in terminal for that?

**Comment by mykola-mokhnach** [comment]
the fix is in 2.97
You can use `npm list` to list installed modules and their versions

**Comment by svetikshark** [comment]
yeah , already  tried npm list -g and there is no appium_lib  there

**Comment by svetikshark** [comment]
so should I update appium-xcuitest-driver separately ?

**Comment by KazuCocoa** [comment]
You can uninstall `appium@beta` from your locale once and install it again. Then, you can use `appium-xcuitest-driver` 2.97.0. (Mine was 2.9.7 just now.)

**Comment by svetikshark** [comment]
ok driver is updated to 2.9.7 but appium fails to start - 
Fatal TypeError: Class constructor BaseDriver cannot be invoked without 'new'
    at new AppiumDriver (/usr/local/lib/node_modules/appium/lib/appium.js:131:19)
    at main$ (/usr/local/lib/node_modules/appium/lib/main.js:124:16)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)

**Comment by KazuCocoa** [comment]
same issue => https://github.com/appium/appium/issues/11477
I assume this is because of babel related... 🤔

**Comment by svetikshark** [comment]
And do you have an idea of how to fix it - you say in  #11477 that you didn't face it after reinstalling appium - I did that

**Comment by svetikshark** [comment]
do you think upgrading node and npm can help?

**Comment by svetikshark** [comment]
Arrrr - updated to  1.9.2-beta.2 - that fixed issue with BaseDriver  constructor -but still getting rectangle exception as appium-xcuitest-driver is 2.96 not 2.97

**Comment by KazuCocoa** [comment]
Did you uninstall it before the installation?

**Comment by svetikshark** [comment]
Yes

**Comment by KazuCocoa** [comment]
The log looks new, i.g. iPeoxy.
Could you share your full serve log with us?

**Comment by svetikshark** [comment]
Ok seems this iProxy error is not related - it seems it tries to rotate the screen and not able to perform it - It was kinda hard to read logs on mac, this recv doesn't stop test execution and happens even before the test started

2018-10-08 06:15:14:535 - info: [debug] [JSONWP Proxy] Got response with status 200: {"value":{"sessionId":"B91B17A8-D58A-45B3-A7AC-8E65DAECF122","capabilities":{"device":"iphone","browserName":"Safari","sdkVersion":"12.0","CFBundleIdentifier":"com.apple.mobilesafari"}},"sessionId":"B91B17A8-D58A-45B3-A7AC-8E65DAECF122","status":0}
2018-10-08 06:15:14:536 - info: [debug] [BaseDriver] Event 'wdaSessionStarted' logged at 1538979314536 (09:15:14 GMT+0300 (EEST))
2018-10-08 06:15:14:537 - info: [debug] [BaseDriver] Event 'wdaStarted' logged at 1538979314537 (09:15:14 GMT+0300 (EEST))
2018-10-08 06:15:14:538 - info: [XCUITest] Skipping setting of the initial display orientation. Set the "orientation" capability to either "LANDSCAPE" or "PORTRAIT", if this is an undesired behavior.
2018-10-08 06:15:14:539 - info: [debug] [BaseDriver] Event 'orientationSet' logged at 1538979314538 (09:15:14 GMT+0300 (EEST))
2018-10-08 06:15:14:539 - info: [debug] [XCUITest] Waiting for initial webview
2018-10-08 06:15:14:540 - info: [debug] [iOS] Waiting for 3000 ms before navigating to view.
2018-10-08 06:15:14:541 - info: [debug] [XCUITest] Connection to WDA timed out
2018-10-08 06:15:14:541 - info: [debug] [iProxy] recv failed: Operation not permitted
2018-10-08 06:15:17:285 - info: [HTTP] --> GET /wd/hub/status
2018-10-08 06:15:17:286 - info: [debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
2018-10-08 06:15:17:287 - info: [debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.9.2-beta.2","git-sha":"d7d328a0d0493e79799b6525ffe385c90414a0db","built":"2018-10-04T15:17:02Z"}}
2018-10-08 06:15:17:289 - info: [HTTP] <-- GET /wd/hub/status 200 3 ms - 158
2018-10-08 06:15:17:289 - info: [HTTP] 
2018-10-08 06:15:17:541 - info: [debug] [iOS] Navigating to most recently opened webview
2018-10-08 06:15:17:542 - info: [debug] [iOS] Retrieving contexts and views
2018-10-08 06:15:17:543 - info: [debug] [iOS] Selecting by url: true (expected url: 'http://appium.io')
2018-10-08 06:15:17:544 - info: [debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
2018-10-08 06:15:17:545 - info: [debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
2018-10-08 06:15:17:551 - info: [debug] [RemoteDebugger] Page element JSON: [{"devtoolsFrontendUrl":"/devtools/devtools.html?ws=localhost:27753/devtools/page/16","faviconUrl":"","thumbnailUrl":"/thumb/http://appium.io/","title":"Appium: Mobile App Automation Made Awesome.","url":"http://appium.io/","webSocketDebuggerUrl":"ws://localhost:27753/devtools/page/16","appId":"PID:1372"}]
2018-10-08 06:15:17:552 - info: [debug] [iOS] Retrieving contexts and views
2018-10-08 06:15:17:553 - info: [debug] [iOS] Selecting by url: true (expected url: 'http://appium.io')
2018-10-08 06:15:17:553 - info: [debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
2018-10-08 06:15:17:553 - info: [debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
2018-10-08 06:15:17:557 - info: [debug] [RemoteDebugger] Page element JSON: [{"devtoolsFrontendUrl":"/devtools/devtools.html?ws=localhost:27753/devtools/page/16","faviconUrl":"","thumbnailUrl":"/thumb/http://appium.io/","title":"Appium: Mobile App Automation Made Awesome.","url":"http://appium.io/","webSocketDebuggerUrl":"ws://localhost:27753/devtools/page/16","appId":"PID:1372"}]
2018-10-08 06:15:17:558 - info: [debug] [iOS] Picking webview 'WEBVIEW_16'
2018-10-08 06:15:17:559 - info: [debug] [iOS] Attempting to set context to 'WEBVIEW_16'
2018-10-08 06:15:17:564 - info: [debug] [RemoteDebugger] WebKit debugger web socket connected to url: ws://localhost:27753/devtools/page/16

**Comment by svetikshark** [comment]
[node_4723.log](https://github.com/appium/appium/files/2455291/node_4723.log)

**Comment by KazuCocoa** [comment]
I see.
Mobile safari doesn't support W3C spec yet. so, the no implementation error happens in web context.

Native context works well.

**Comment by svetikshark** [comment]
Thx! Does it mean i can  reinstall appium to get you fix? Or this pull request is not yet merged?

**Comment by svetikshark** [comment]
Also i wonder why this bug is still shown as closed

**Comment by Nesaganesh** [comment]
I am also having the same issue

Appium  version - 1.9.2-beta.2

[HTTP] {}
[debug] [W3C (415f64f2)] Calling AppiumDriver.getElementRect() with args: ["5002","415f64f2-67bb-44bb-b537-17cde51e9519"]
[debug] [XCUITest] Executing command 'getElementRect'
[debug] [W3C (415f64f2)] Encountered internal error running command: NotYetImplementedError: Method has not yet been implemented
[debug] [W3C (415f64f2)]     at /usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:266:13
[debug] [W3C (415f64f2)]     at next (native)
[debug] [W3C (415f64f2)]     at asyncGeneratorStep (/usr/local/lib/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
[debug] [W3C (415f64f2)]     at _next (/usr/local/lib/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
[debug] [W3C (415f64f2)]     at /usr/local/lib/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
[debug] [W3C (415f64f2)]     at /usr/local/lib/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12
[debug] [W3C (415f64f2)]     at XCUITestDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:246:39)
[debug] [W3C (415f64f2)]     at _superprop_callExecuteCommand (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:619:39)
[debug] [W3C (415f64f2)]     at /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:629:18
[debug] [W3C (415f64f2)]     at next (native)
[debug] [W3C (415f64f2)]     at asyncGeneratorStep (/usr/local/lib/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
[debug] [W3C (415f64f2)]     at _next (/usr/local/lib/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
[debug] [W3C (415f64f2)]     at /usr/local/lib/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
[debug] [W3C (415f64f2)]     at /usr/local/lib/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12
[debug] [W3C (415f64f2)]     at XCUITestDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:619:39)
[debug] [W3C (415f64f2)]     at /usr/local/lib/node_modules/appium/lib/appium.js:424:36
[debug] [W3C (415f64f2)]     at next (native)
[debug] [W3C (415f64f2)]     at asyncGeneratorStep (/usr/local/lib/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
[debug] [W3C (415f64f2)]     at _next (/usr/local/lib/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
[debug] [W3C (415f64f2)]     at process._tickCallback (internal/process/next_tick.js:103:7)
[HTTP] <-- GET /wd/hub/session/415f64f2-67bb-44bb-b537-17cde51e9519/element/5002/rect 404 54 ms - 2096
[HTTP]

**Comment by KazuCocoa** [comment]
Will be fixed in the next publishment of xcuites-driver as 2.98.

**Comment by svetikshark** [comment]
How would I know that the new version of xcuites-driver is published?

**Comment by KazuCocoa** [comment]
Watching https://www.npmjs.com/package/appium-xcuitest-driver is the handiest, I think.

**Comment by svetikshark** [comment]
thank you! waiting then
