### ISSUE TITLE
Error start session: Appium 1.9.0 + docker container

### ISSUE THREAD

**Issue by aikuznetsov** [appium/appium#11428]
## The problem

Hi! I wanna perform my test in parallel at some devices with docker. I launched docker container, which sees only 1 necessary device. But when I try to create appium driver I receive "[GET http://localhost:8200/wd/hub/status] with no body" error.

## Environment
* Appium version Appium v1.9.1
* Desktop OS/version used to run Appium: 16.04.1-Ubuntu
* Node.js version:  6.4.1 
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Real device
* Docker container: docker pull appium/appium (with updated appium and node.js)
https://hub.docker.com/r/appium/appium/

Link to Appium logs

https://gist.github.com/aikuznetsov/50abddf6dfc0ea9a04fdb5a704c66f05

## Code To Reproduce Issue [ Good To Have ]
1. Start docker container:  docker run --rm -d   --device /dev/bus/usb/003/075:/dev/bus/usb/003/075 -v ~/.android:/root/.android  --name device1 appium/appium

2. Attempt to create driver:
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability("deviceName", deviceID);
            capabilities.setCapability("model", "SM_A310F");
            capabilities.setCapability("udid", deviceID);
            capabilities.setCapability("automationName", "uiautomator2");
            capabilities.setCapability("platformName", "Android");
            capabilities.setCapability("platformVersion", "7.0");
            capabilities.setCapability("newCommandTimeout", "0");
            capabilities.setCapability("appPackage", HOTSPOTSHIELD);
            capabilities.setCapability("appActivity", HSS_MAIN_ACTIVITY);

**Comment by saikrishna321** [comment]
Please raise issue here https://github.com/appium/appium-docker-android

**Comment by aikuznetsov** [comment]
> Please raise issue here https://github.com/appium/appium-docker-android

Created https://github.com/appium/appium-docker-android/issues/87
