### ISSUE TITLE
Chromedriver error when trying to switch to webview -- hybrid app

### ISSUE THREAD

**Issue by dokmetas** [appium/appium#11421]
## The problem

Chromedriver error when trying to switch to webview.

[Chromedriver] Error: Failed to start Chromedriver session: An unknown server-side error occurred while processing the command. Original error: unknown error: Failed to get sockets matching: @webview_devtools_remote_.*3202

## Environment

- Appium version (or git revision) that exhibits the issue: 1.7.0
- Last Appium version that did not exhibit the issue (if applicable): N/A
- Desktop OS/version used to run Appium: Windows 10 Enterprise x64
- Node.js version (unless using Appium.app|exe): N/A
- Mobile platform/version under test: Android version 8.0.0
- Real device or emulator/simulator: Real Device, Samsung S7edge
- Appium CLI or Appium.app|exe: Appium.exe, Graphical interface for the Appium server, and an app inspector.

## Details
1. AUT started
2. Context handles set contains ;
[NATIVE_APP, WEBVIEW_com.genband.omni.mobile]
3. driver.context("WEBVIEW_com.genband.omni.mobile");
4. I see the following error in appium logs.
[Chromedriver] Error: Failed to start Chromedriver session: An unknown server-side error occurred while processing the command. Original error: unknown error: Failed to get sockets matching: @webview_devtools_remote_.*3202

p.s. 
- app does not contain Crosswalk webview.

- Tried all chromedriver versions available @ https://chromedriver.storage.googleapis.com/index.html
with no change in result.

- app debug is enabled
![capture](https://user-images.githubusercontent.com/11345785/46012201-21a59e00-c0d1-11e8-92c2-37e6c7ebb69e.PNG)

`	
//Set the Desired Capabilities
DesiredCapabilities caps = new DesiredCapabilities();
caps.setCapability(MobileCapabilityType.DEVICE_NAME, "S7edge");
caps.setCapability("deviceName", "My Phone");
caps.setCapability("udid", "ad0617021631688b45"); 
caps.setCapability("platformName", "Android");
caps.setCapability("platformVersion", "8.0.0");
caps.setCapability("appPackage","com.genband.omni.mobile");
caps.setCapability("appActivity","com.genband.omni.mobile.SplashActivity");
caps.setCapability("noReset", true);
caps.setCapability("automationName", "UiAutomator2");
caps.setCapability("autoGrantPermissions", true); // allow permissions automatically
caps.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 120);
caps.setCapability("chromedriverExecutable","D:\\webdrivers\\2.42\\chromedriver.exe");
caps.setCapability("showChromedriverLog", true);
		
	
//Instantiate Appium Driver
try {
	AppiumDriver<MobileElement> driver = new AndroidDriver<MobileElement>(new 
                 URL("http://0.0.0.0:4723/wd/hub"), caps);
Thread.sleep(20000);
System.out.println(driver.getContextHandles());
driver.context("WEBVIEW_com.genband.omni.mobile");
driver.findElement(By.id("username"));
 } catch (MalformedURLException | InterruptedException e) {
       System.out.println(e.getMessage());
}
`

## Link to Appium logs

https://gist.github.com/dokmetas/7106a82c4abacfb0b186c3e613912f40

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/issues?q=is%3Aissue+%22Failed+to+get+sockets+matching%22+is%3Aclosed

**Comment by Lanuet** [comment]
i also read all related post and common suggestion but it's not works. Did you fix it? @dokmetas

**Comment by KazuCocoa** [comment]
> Hi, i fixed this by add 'chromeOptions': {'androidPackage': 'com.android.chrome'} in dessired_caps {}

https://github.com/appium/python-client/issues/255#issuecomment-426903322

**Comment by dokmetas** [comment]
@KazuCocoa 

When capabilities.setCapability("chromeOptions", "'androidPackage':'com.android.chrome'"); provided;

I am seeing different result than you did. Appium logs for the arg passed in and a subsequent warning message in bold below.

The following arg in bold is passed to AppiumDriver.createSession().

[Appium] Creating new AndroidUiautomator2Driver (v1.19.0) session
[Appium] Capabilities:
**[Appium]   goog:chromeOptions: 'androidPackage':'com.android.chrome'**
[Appium]   platformName: android


**[BaseDriver] The following capabilities were provided, but are not recognized by appium: goog:chromeOptions, chromeOptions.**

**Comment by dokmetas** [comment]
@KazuCocoa

When capabilities.setCapability("chromeOptions", "'androidPackage':'com.android.chrome'"); provided;

I am seeing different result than you did. Appium logs for the arg passed in and a subsequent warning message in bold below.

The following arg in bold is passed to AppiumDriver.createSession().

[Appium] Creating new AndroidUiautomator2Driver (v1.19.0) session
[Appium] Capabilities:
**[Appium] goog:chromeOptions: 'androidPackage':'com.android.chrome'**
[Appium] platformName: android

**[BaseDriver] The following capabilities were provided, but are not recognized by appium: goog:chromeOptions, chromeOptions.**

**Comment by KazuCocoa** [comment]
@dokmetas 
Which client and version did you use?
I'm not sure why `goog:` prefix appears in the log... She was python client. Below is Ruby client's log.
If you use another client, could you report it to the client's repository?

```
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"platformName":"android","automationName":"uiautomator2","browserName":"chrome","platformVersion":"7.1.1","deviceName":"Android Emulator","someCapability":"some_capability","unicodeKeyboard":true,"resetKeyboard":true,"disableWindowAnimation":true,"newCommandTimeout":300,"chromeOptions":{"androidPackage":"com.android.chrome"}},"capabilities":{"firstMatch":[{"platformName":"android","appium:automationName":"uiautomator2","browserName":"chrome","appium:platformVersion":"7.1.1","appium:deviceName":"Android Emulator","appium:someCapability":"some_capability","appium:unicodeKeyboard":true,"appium:resetKeyboard":true,"appium:disableWindowAnimation":true,"appium:newCommandTimeout":300,"appium:chromeOptions":{"androidPackage":"com.android.chrome"}}]}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"platformName":"android","automationName":"uiautomator2","browserName":"chrome","platformVersion":"7.1.1","deviceName":"Android Emulator","someCapability":"some_capability","unicodeKeyboard":true,"resetKeyboard":true,"disableWindowAnimation":true,"newCommandTimeout":300,"chromeOptions":{"androidPackage":"com.android.chrome"}},null,{"firstMatch":[{"platformName":"android","appium:automationName":"uiautomator2","browserName":"chrome","appium:platformVersion":"7.1.1","appium:deviceName":"Android Emulator","appium:someCapability":"some_capability","appium:unicodeKeyboard":true,"appium:resetKeyboard":true,"appium:disableWindowAnimation":true,"appium:newCommandTimeout":300,"appium:chromeOptions":{"androidPackage":"com.android.chrome"}}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1539001013313 (21:16:53 GMT+0900 (Japan Standard Time))
[Appium] Creating new AndroidUiautomator2Driver (v1.22.0) session
[Appium] Capabilities:
[Appium]   platformName: android
[Appium]   browserName: chrome
[Appium]   automationName: uiautomator2
[Appium]   platformVersion: 7.1.1
[Appium]   deviceName: Android Emulator
[Appium]   someCapability: some_capability
[Appium]   unicodeKeyboard: true
[Appium]   resetKeyboard: true
[Appium]   disableWindowAnimation: true
[Appium]   newCommandTimeout: 300
[Appium]   chromeOptions: {
[Appium]     androidPackage: com.android.chrome
[Appium]   }
[debug] [BaseDriver] W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP desired capabilities {"platformName":"android","... were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"platformNa...
[BaseDriver] The following capabilities were provided, but are not recognized by appium: someCapability, chromeOptions.
[BaseDriver] Session created with session id: 76e17fb2-591e-4e05-bdb1-90a713080127
[UiAutomator2] We're going to run a Chrome-based session
```

**Comment by KazuCocoa** [comment]
What about tweak the _chromeOptions_?
http://chromedriver.chromium.org/getting-started/getting-started---android

**Comment by Lanuet** [comment]
@dokmetas try with latest chrome version

**Comment by dokmetas** [comment]
Problem solved with the newer version of the app under test.
Just fyi, I did not have to provide any Chrome options besides bare minimum standard ones.
When tried directly with chrome driver without appium as below it works;

> from selenium import webdriver
> capabilities = {
>   'chromeOptions': {
>     'androidPackage': 'com.yourApp.package.name','androidUseRunningApp': True
>   }
> }
> driver = webdriver.Remote('http://localhost:9515', capabilities)
> webview = 'WEBVIEW_that_you_want_to_switch_to'
> driver.switch_to.context(webview)


it works with appium as well;

> import unittest
> from appium import webdriver

> desired_caps = {}
> desired_caps['platformName'] = 'Android'
> desired_caps['platformVersion'] = '8.0.0'
> desired_caps['deviceName'] = 'Samsung'
> desired_caps['automationName'] = 'UiAutomator2'
> desired_caps['appPackage'] = 'com.yourApp.package'
> desired_caps['appActivity'] = 'com.yourApp.activity'
> desired_caps['chromedriverExecutable'] = "D:\\webdrivers\\2.42\\chromedriver.exe";
> desired_caps['udid'] = "ad0617021631688b45";
> desired_caps['newCommandTimeout'] = 300;
> desired_caps['chromeOptions'] = {'androidUseRunningApp': True}
> 
> driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
> 
> 
> webview = 'WEBVIEW_that_you_want_to_switch_to'
> driver.switch_to.context(webview)

**Comment by KazuCocoa** [comment]
Thanks for the _fyi_

**Comment by Nilesh61181** [comment]
@dokmetas 
@KazuCocoa 

I have tried these capabilites to make it work on UC browser dev apk.
DesiredCapabilities capabilities = new DesiredCapabilities();

			capabilities.setCapability("deviceName", "42100c599614a491");

			capabilities.setCapability("platformName", "Android");

			capabilities.setCapability("appPackage", "com.UCMobile.intl");
			capabilities.setCapability("appActivity", "com.UCMobile.main.UCMobile");
			capabilities.setCapability("noReset", true);
			capabilities.setCapability("showChromedriverLog",true); 
			ChromeOptions chromeOpt = new ChromeOptions();
			chromeOpt.setExperimentalOption("androidPackage","com.android.chrome");
			capabilities.setCapability(ChromeOptions.CAPABILITY,chromeOpt);


its still not working for me, we are using Appium 1.7.2 and java client4.1.2

**Comment by KazuCocoa** [comment]
I'm not sure your environment, but did you use proper Chromedriver?
https://github.com/appium/appium-chromedriver#upgrading-chromedriver-version

While I recommend you to use the latest Appium and Client since your versions are an outdated one.
