### ISSUE TITLE
Parallel testing docs unclear

### ISSUE THREAD

**Issue by dazinator** [appium/appium#11420]
## The problem

Referring to this page:
https://github.com/appium/appium/blob/55760b7b9e1c494c6a1f22d152f0bd1fe676dae7/docs/en/advanced-concepts/parallel-tests.md

It says single machine and single server (assuming it means appium server) automating multiple android sessions. But then it says start each appium "instanceset" on its own port.. whats an "instancset" ? This sounds like you have to start up multiple appium servers running, each with its own port and its own driver connecting to it is that correct? If so then how is that a single server instance on a single machine? I am very confused. Perhaps its just me,  but am raising this as I feel the doc could be more clear on this subject. Thanks

**Comment by mykola-mokhnach** [comment]
Linking https://github.com/appium/appium/pull/11424

**Comment by dpgraham** [comment]
This will eventually be published to Appium.io
