### ISSUE TITLE
System.InvalidOperationException : Session [(null externalkey)] not available and is not among the last 1000 terminated sessions. Active sessions are[ext. key 9fdb9bdb-1ffa-4529-aa4c-9a26584d4ae1]

### ISSUE THREAD

**Issue by saigovindu** [appium/appium#11423]
was trying to connect appium(1.9) node using selenium 3.14 but it is failing because of (Session [(null externalkey)] not available and is not among the last 1000 terminated sessions.) not available error.
Device setup information:
OS: Mac OS El Capitan 10.11.6
Selenium Version: 3.14
Browser: Safari
Appium:1.9
Following things I did:
• Ran selenium hub on windows machine: java -jar selenium-server-standalone-3.14.0.jar -host 10.82.88.147 -role hub
• Ran Appium node on Mac Mini with following attributes:
 {
 "capabilities": [
 {
 "browserName": "safari",
 "maxInstances": 1,
 "platform":"MAC",
 "seleniumProtocol": "WebDriver",
 "automationName": "XCUITest"
 }
 ],
 "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
 "url": "http://10.177.255.145:4444/wd/hub",
 "host": "10.177.255.145", //node ip
 "port": 4444, //node port
 "maxSession": 5,
 "register": true,
 "registerCycle": 5000,
 "role": "node",
 "hub": "http://10.82.88.147:4444",
 "hubPort": 4444,
 "hubHost": "10.82.88.147",
 "debug": false,
 "servlets" : [],
 "withoutServlets": [],
 "custom": {}
 }
• Ran following Selenium test on hub.
o IWebDriver driver = null;
DesiredCapabilities capabilities = new DesiredCapabilities();
o capabilities.SetCapability("browserName","safari");
o capabilities.SetCapability("platformName", "iOS");
o capabilities.SetCapability("platform", "MAC");
o capabilities.SetCapability("platformVersion", "10.1");
o capabilities.SetCapability("automationName", "XCUITest");
o capabilities.SetCapability("deviceName", "iPhone 7");
o Uri url = new Uri("http://10.82.88.147:4444/wd/hub");
o driver = new IOSDriver(url, capabilities, TimeSpan.FromSeconds(180));
o driver.Navigate().GoToUrl("https://www.google.com");
o driver.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(10));
o driver.Navigate().GoToUrl("https://www.facebook.com");
o Console.WriteLine(driver.Title);
In MacMini, I can see IOS emulator open and safari browser open but it is not redirecting specified page(“https://www.google.com”) in code , it just simply stays in welcome page. Please see attached logs.
[
logs.txt
](url)
[logs.txt](https://github.com/appium/appium/files/2416237/logs.txt)

**Comment by mykola-mokhnach** [comment]
> [BaseDriver] Shutting down because we waited 60 seconds for a command
> [Appium] Closing session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
> [Appium] Removing session 9fdb9bdb-1ffa-4529-aa4c-9a26584d4ae1 from our master session list

I would say such response is expected, since the session is killed due to timeout

**Comment by mykola-mokhnach** [comment]
Or it might be the client issue, where it sends `null` instead of the actual session id

**Comment by mykola-mokhnach** [comment]
@akinsolb Did you see any similar issues in dotnet so far?

**Comment by saigovindu** [comment]
Thanks for looking at this issue. I was able find the root cause for this, I am using C# client library to communicate with node, this library have Appium webdriver that is using old selenium 3.0.1 so I manually upgrade that to latest 3.12 version then it worked.

Thanks
