### ISSUE TITLE
Is there any way to forward waitForQuiescence to activateApp?

### ISSUE THREAD

**Issue by jamesvanhorn** [appium/appium#11425]
## The problem

Using terminateApp/activateApp does not honor waitForQuiesence capability. This results in activateApp hanging often for us on simulators.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Mac 10.13
* Node.js version (unless using Appium.app|exe): 10.1.0
* Mobile platform/version under test: iOS 12.0
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Code To Reproduce Issue [ Good To Have ]

Initialize a driver (with waitForQuiesence set to false) then call terminate and activate app back to back. On activateApp look at Xcode logs and you will see the log message "Wait for accessibility to load". This is undesired behavior, since often times for us accessibility never loads on the simulator only.

**Comment by jamesvanhorn** [comment]
will do shortly. thanks for super quick response as usual.

**Comment by jamesvanhorn** [comment]
So i ran it a few times and seems to work? Interestingly though, Im not seeing anything passed to activateApp() method aside from bundle ID and session?
`["<BUNDLEID>",null,null,null,"48d94e46-19b4-4e6c-93a8-e3558bb9f358"]`

Full log:
```
17:17:02 [HTTP] --> POST /wd/hub/session/48d94e46-19b4-4e6c-93a8-e3558bb9f358/appium/device/activate_app
17:17:02 [HTTP] {"bundleId":"<BUNDLEID>"}
17:17:02 [debug] [W3C] Calling AppiumDriver.activateApp() with args: ["<BUNDLEID>",null,null,null,"48d94e46-19b4-4e6c-93a8-e3558bb9f358"]
17:17:02 [debug] [XCUITest] Executing command 'activateApp'
17:17:02 [debug] [XCUITest] Setting custom timeout to 180000 ms for 'mobileLaunchApp' command
17:17:02 [debug] [JSONWP Proxy] Proxying [POST /wda/apps/launch] to [POST http://localhost:8100/session/364CDDD0-D4A3-4D15-9E52-20C401C5BA6B/wda/apps/launch] with body: {"bundleId":"<BUNDLEID>"}
17:17:02 [Xcode]     t =    93.98s Open <BUNDLEID>
17:17:02 [Xcode] 
17:17:02 [Xcode]     t =    93.98s     Launch <BUNDLEID>
17:17:02 [Xcode] 
17:18:03 [Xcode] 2018-09-25 17:18:02.957342-0400 WebDriverAgentRunner-Runner[97485:9822105] Enqueue Failure: Application '<BUNDLEID> does not have a process ID /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
17:18:03 [Xcode] 
17:18:04 [Xcode]     t =   155.03s Open <BUNDLEID>
17:18:04 [Xcode]     t =   155.03s     Activate <BUNDLEID>
17:18:04 [Xcode] 
17:18:04 [debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"364CDDD0-D4A3-4D15-9E52-20C401C5BA6B","status":0}
17:18:04 [debug] [MJSONWP] Responding to client with driver.activateApp() result: {}
17:18:04 [HTTP] <-- POST /wd/hub/session/48d94e46-19b4-4e6c-93a8-e3558bb9f358/appium/device/activate_app 200 61104 ms - 74
17:18:04 [HTTP] 
17:18:04 2018-09-25 17:18:04 INFO  IOSBaseTest         :96   - App activated
```

Running some more to confirm. Might be just a logging thing. Made sure to remove DerivedData and all that when checking out `noq_activate` branch. Manually uninstalled WDA from sims and restarted sim/Appium as well. I saw the dependencies re-download as well so i dont think i missed anything.

**Comment by mykola-mokhnach** [comment]
> So i ran it a few times and seems to work? Interestingly though, Im not seeing anything passed to activateApp() method aside from bundle ID and session?

This is normal. As you can see in the code I'm just trying to restore the state from createSession call if the argument has not been overridden explicitly

**Comment by jamesvanhorn** [comment]
working great.

**Comment by mykola-mokhnach** [comment]
The change has been published in appium@beta
