### ISSUE TITLE
Scrolling on iOS is very slow (a distance of max one page scrolled at a time)

### ISSUE THREAD

**Issue by ania-s** [appium/appium#11434]
## The problem
Scrolling on iOS using "mobile: scroll" scrolls only by maximum one page at a gesture. While in real life when user scrolls it might move the view by few pages every time the user makes a scrolling gesture. It slows down the testing a lot and if the scrolling view is very long (e.g. long Terms and Conditions) then it might even timeout before reaching the end of the page. 

## Environment
appium: 1.9.1

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/facebook/WebDriverAgent

Closed as third party issue.
