### ISSUE TITLE
[Fingerprint unlock]Does appium support test fingerprint unlock?

### ISSUE THREAD

**Issue by adadale** [appium/appium#11439]
## The problem

I have implemented gesture unlock.But How to use Appium to achieve fingerprint unlock for ios app

## Environment

* Appium version ：1.8.1
* Desktop OS/version used to run Appium:mac os

## Details

Does Appium Support test fingerprint unlock?

**Comment by KazuCocoa** [comment]
Do you mean http://appium.io/docs/en/writing-running-appium/ios/ios-touch-id/ ? @adadale

**Comment by KazuCocoa** [comment]
ah, fingerprint. maybe, I see.

**Comment by mykola-mokhnach** [comment]
This is not supported because the downstream framework has no support of it

**Comment by adadale** [comment]
Does it have other solutions to this problem？Thanks @mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
None I know of
