### ISSUE TITLE
iphone xs max udid

### ISSUE THREAD

**Issue by kazzmir** [appium/appium#11448]
## The problem

The new iphones (XS, XS max, probably Xr) have 25-digit udid's that also (sometimes) have a dash at the 9th character. libimobildevice tools expect to not have the dash, but xcodebuild wants the dash.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: linux
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: appium cli

Locally I have modified the idevicetools to accept a 25-digit udid, and also changed appium to not check if the udid is actually present (because the udid I pass in has a dash, but the udids appium knows about from idevice_id doesn't have the dash).

Anyway I think the solution is just to strip the - when passing the udid to ios-deploy or the idevicetools, as well as having updated idevicetools that allow for a 25-digit udid. The alternative would be to insert a dash at the 9th character when passing the udid to xcodebuild. I haven't tested that end-to-end though.

**Comment by mykola-mokhnach** [comment]
Thanks for reporting it. Can you please provide pseudo-code examples of udid transformation, since I don't have any device to check with? Also, we would be happy if you could submit a PR since you've already tested the necessary fixes locally.

**Comment by kazzmir** [comment]
I went in a different direction that modifying appium. Instead, I modified the idevicetools to handle the - in the following ways:

```
    * idevice_id checks if the udid is 24 chars, and if so will insert a - after the 8th character
    * iproxy will check for a - in the udid and remove it
    * all other idevice* tools similarly remove the - if passed in on the command line
```
ios-deploy actually wants the - so there is no issue.

Anyway a udid on an iphone xs max looks like
```
00008020-0011600000000000
```
libusbmuxd will output device id's without the - in the 9th character, but xcode and ios-deploy want the - there, thus my changes require the udid to be specified with the - when passed to appium and the imobiledevice tools will remove the - when communicating via usbmuxd. Although then a question is when xcode talks via usbmuxd does it pass the - or not? Well that will take some investigation..

**Comment by mykola-mokhnach** [comment]
I agree, that it would be more practically to add that fix directly into idevicelibrary. As far as I remember we don't do any assumptions about udid format in appium code, so the change should be pretty transparent in theory.

**Comment by KazuCocoa** [comment]
They've removed the length check => https://github.com/libimobiledevice/libimobiledevice/commit/b34e3435c21d06b3e5a4e7b5246fb6ddb6641a9f

**Comment by mykola-mokhnach** [comment]
@kazzmir I see this PR has been merged, so you could install libimobiledevice from HEAD and check if it works now with appium. Let us know if there are any issues on our side.

**Comment by CoryBe** [comment]
I updated my installs, the issue I am seeing is that the ID for prior devices was expected to be in lower case. The XS ID's are expected to be upper case.

**Comment by kazzmir** [comment]
It is working for me now after installing the latest libimobiledevice, ideviceinstaller, appium 1.9.1 and xcode 10.

**Comment by ajoyashwinth** [comment]
I am still facing the issue. Updated the libimobiledevice, ideviceinstaller to latest and using appium 1.12.1 and xcode 10.1 . 

Getting error **Error 0xe8008015: A valid provisioning profile for this executable was not found.**  while running on iPhone XS max(UDID Format changed) but working fine on other devices with older format of UDID. Need pointers on the same. @mykola-mokhnach  @kazzmir

**Comment by 4ndrey** [comment]
some for us, any update here?
