### ISSUE TITLE
Unable Launch App(.ipa file) in Simulator But its installed successfully

### ISSUE THREAD

**Issue by Nagu7190** [appium/appium#11440]
## The problem

I'm using Appium inspector to launch App and getting elements from the Appium But Here app is not launching its opened frequently and closing like blinking.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.0
* Last Appium version that did not exhibit the issue (if applicable): it's not working.
* Desktop OS/version used to run Appium: MacOS 10.13.6
* Node.js version (unless using Appium.app|exe): v8.11.1
* Mobile platform/version under test: 11.4
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium.app

## Link to Appium logs

[XCUITest] *********************************
[XCUITest] Simulator architecture appears to be unsupported by the '/var/folders/b5/y07mx20s71d7r7rvvd7w8x3h0000gn/T/2018826-676-l6v6x0.yiwdl/Payload/wp.app' application. Make sure the correct deployment target has been selected for its compilation in Xcode.
[XCUITest] Don't be surprised if the application fails to launch.
[XCUITest] *********************************
[XCUITest] Installing '/var/folders/b5/y07mx20s71d7r7rvvd7w8x3h0000gn/T/2018826-676-l6v6x0.yiwdl/Payload/wp.app' on Simulator with UUID 'C2E1992D-2C66-402C-88DF-E677ED53B278'.

[XCUITest] The app has been installed successfully.
[BaseDriver] Event 'appInstalled' logged at 1537973370140 (10:49:30 GMT-0400 (EDT))
[JSONWP Proxy] Got response with status 200: {"value":"Failed to launch org.wordpress application","sessionId":"5998A380-C391-4323-BC2B-DBD54DB82112","status":13}
[MJSONWP] Matched JSONWP error code 13 to UnknownError
[XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Failed to launch org.wordpress application). Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1537973420401 (10:50:20 GMT-0400 (EDT))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Matched '/session' to command name 'createSession'
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"org.wordpress","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 5 ms - 57
[HTTP] 
[JSONWP Proxy] Got response with status 200: {"value":"Failed to launch org.wordpress application","sessionId":"5998A380-C391-4323-BC2B-DBD54DB82112","status":13}
[MJSONWP] Matched JSONWP error code 13 to UnknownError
[XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Failed to launch org.wordpress application). Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1

## Code To Reproduce Issue [ Good To Have ]

Appium JSON:

{
  "platformName": "iOS",
  "deviceName": "iPhone 8",
  "platformVersion": "11.4",
  "udid": "C2E1992D-2C66-402C-88DF-E677ED53B278",
  "app": "/user/path/WordPressSample.ipa"
}

**Comment by mykola-mokhnach** [comment]
```
[XCUITest] *********************************
[XCUITest] Simulator architecture appears to be unsupported by the '/var/folders/b5/y07mx20s71d7r7rvvd7w8x3h0000gn/T/2018826-676-l6v6x0.yiwdl/Payload/wp.app' application. Make sure the correct deployment target has been selected for its compilation in Xcode.
[XCUITest] Don't be surprised if the application fails to launch.
[XCUITest] *********************************
```

Closed as not an issue (and also a duplicate)

**Comment by Nagu7190** [comment]
Thanks for Reply..

But what I need to do To launch an APP

**Comment by mykola-mokhnach** [comment]
You must get a proper simulator-compatible build
