### ISSUE TITLE
[runAppInBackground]Can't lanuch app after using runAppInBackground command

### ISSUE THREAD

**Issue by adadale** [appium/appium#11449]
## The problem

 I used  1.driver.runAppInBackground(Duration.ofSeconds(2));
             2.driver.launchApp();
but just 1 worked,And 2 didn't work.How can i launch APP After using 1?
Thanks
## Environment
* Appium version (or git revision) that exhibits the issue:appium 1.8.1

## Link to Appium logs

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "Timeout waiting until SpringBoard is visible" UserInfo={NSLocalizedDescription=Timeout waiting until SpringBoard is visible}

**Comment by mykola-mokhnach** [comment]
Please try with the most recent server version. If it still does not work then report the problem to https://github.com/facebook/WebDriverAgent

Closed as third party issue
