### ISSUE TITLE
Support double as argument type in appium-uiautomator2-server #Android #Enhancement #Quick-Fix

### ISSUE THREAD

**Issue by kwhite5555** [appium/appium#11443]
## The problem

The code that supported double types in the UiExpressionParser was lost over time.
The issue is here:
https://github.com/appium-boneyard/appium-android-bootstrap/pull/33
## Environment
appium-uiautomator2-server on android devices
## Details
This is required to use setSwipeDeadZonePercentage on the UIScrollable Class

## Code To Reproduce Issue [ Good To Have ]
//Initialize parent with appium url and desired capabilities
AndroidDriver appDriver = (AndroidDriver) parent;
                appDriver.findElement(MobileBy
                        .AndroidUIAutomator("new UiScrollable(new UiSelector().scrollable(true).instance(0)).setMaxSearchSwipes(" +
                                maxAndroidSearchSwipes + ").setSwipeDeadZonePercentage(0.2).scrollIntoView(new UiSelector().description(\"" + locator + "\").instance(0))"));
In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by imurchie** [comment]
The functionality still exists for UiAutomator (see https://github.com/appium/appium-android-driver/blob/master/bootstrap/src/io/appium/android/bootstrap/utils/UiScrollableParser.java#L338-L340).

**Comment by imurchie** [comment]
A fix has been published in `appium-uiautomator2-server@1.19.1`.
