### ISSUE TITLE
Could not proxy command to remote server. Original error: Error: socket hang up

### ISSUE THREAD

**Issue by malatibehera** [appium/appium#11441]
## The problem

The problem is occurring on only one particular page.  The page is basically a search page containing all airports. Not able to inspect this page with appium desktop. While running automation sendkeys and click on an element taking more than 7 minutes and most of the time it got failed to perform them.

## Environment
* Appium version (or git revision) that exhibits the issue: 1.8.0
* Desktop OS/version used to run Appium:macOS High Sierra 10.13.2
* Mobile platform/version under test:iOS 11.4.1
* Real device or emulator/simulator: real device(iPhone 6s)
*Appium CLI or Appium.app|exe: Appium CLI
*Xcode 9.4.1

## Link to Appium logs
here the appium log when I try to inspect the page
[https://gist.github.com/malatibehera/eed839b8b77cb229052a138dcb42a656](url)

**Comment by mykola-mokhnach** [comment]
Upgrade Appium to the most recent version. If this does not help then report the problem to https://github.com/facebook/WebDriverAgent, as we cannot fix much there.
