### ISSUE TITLE
driver.current_window_handle error：unknown command: session/9544c7df7bf5098703035184941f1bd7/window

### ISSUE THREAD

**Issue by chenchengyuan** [appium/appium#11458]
## The problem
driver.current_window_handle  error
I change the request 
```GET http://127.0.0.1:8000/wd/hub/session/9544c7df7bf5098703035184941f1bd7/window```
to 
```GET http://127.0.0.1:8000/wd/hub/session/9544c7df7bf5098703035184941f1bd7/window_handle```,
then it works.

So, maybe the return of the code ```self.w3c``` in the ```start_session(appium/webdriver/webdriver.py #line148)``` is wrong.

Can you check it? 
Thank you.

## Environment

* Appium version (or git revision) that exhibits the issue:1.9.1 （1.7.2 has no error）
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macos 10.13.6
* Node.js version (unless using Appium.app|exe): v8.12.0
* Mobile platform/version under test:Android8.1.0
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

```
Proxying [GET /wd/hub/session/7197a5e7-e0ca-41ab-8a3b-19e25c177eb1/window] to [GET http://127.0.0.1:8000/wd/hub/session/9544c7df7bf5098703035184941f1bd7/window] with body: {"sessionId":"7197a5e7-e0ca-41ab-8a3b-19e25c177eb1"}
[JSONWP Proxy] Got an unexpected response: unknown command: session/9544c7df7bf5098703035184941f1bd7/window
[debug] [W3C] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 404 - "unknown command: session/9544c7df7bf5098703035184941f1bd7/window"
```

## Code To Reproduce Issue [ Good To Have ]

```driver.current_window_handle```

**Comment by mykola-mokhnach** [comment]
Thanks for reporting the problem

**Comment by mykola-mokhnach** [comment]
the fix has been published in appium@beta
