### ISSUE TITLE
Start appium to execute the script, and appium driver automatically deletes the session

### ISSUE THREAD

**Issue by Ocean0227** [appium/appium#11454]
## The problem

Start appium to execute the script, and appium driver automatically deletes the session

## Environment

* Appium version ：1.6.3
* xcode：9.4.1
* appium-xcuitest-driver：2.92
* iPhone 8，iOS 11.4

## Link to Appium logs

 didi@bogon  ~  appium -p 4723
(node:18198) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[Appium] Welcome to Appium v1.6.3
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"capabilities":{"alwaysMatch":{"appium:path":"","appium:command_executor":"http://127.0.0.1:4723/wd/hub","appium:noReset":true,"appium:xcodeOrgId":"xxxxxxxxxx","appium:automationName":"xcuitest","appium:newCommandTimeout":300,"appium:udid":"f899b567337e8eb4505ccad03752e00f56809ac8","appium:bundleId":"com.xx.inhouse","appium:deviceName":"iPhone 8","appium:platformVersion":"11.4","platformName":"iOS","appium:xcodeSigningId":"iPhone Developer"},"firstMatch":[{}]},"desiredCapabilities":{"deviceName":"iPhone 8","xcodeOrgId":"xxxxxxxxxx","udid":"f899b567337e8eb4505ccad03752e00f56809ac8","automationName":"xcuitest","noReset":true,"command_executor":"http://127.0.0.1:4723/wd/hub","xcodeSigningId":"iPhone Developer","newCommandTimeout":300,"platformVersion":"11.4","path":"","platformName":"iOS","bundleId":"com.xx.inhouse"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"deviceName":"iPhone 8","xcodeOrgId":"xxxxxxxxxx","udid":"f899b567337e8eb4505ccad03752e00f56809ac8","automationName":"xcuitest","noReset":true,"command_executor":"http://127.0.0.1:4723/wd/hub","xcodeSigningId":"iPhone Developer","newCommandTimeout":300,"platformVersion":"11.4","path":"","platformName":"iOS","bundleId":"com.xxinhouse"},null,{"alwaysMatch":{"appium:path":"","appium:command_executor":"http://127.0.0.1:4723/wd/hub","appium:noReset":true,"appium:xcodeOrgId":"xxxxxxxxxx","appium:automationName":"xcuitest","appium:newCommandTimeout":300,"appium:udid":"f899b567337e8eb4505ccad03752e00f56809ac8","appium:bundleId":"com.xx.inhouse","appium:deviceName":"iPhone 8","appium:platformVersion":"11.4","platformName":"iOS","appium:xcodeSigningId":"iPhone Developer"},"firstMatch":[{}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1538126862386 (17:27:42 GMT+0800 (中国标准时间))
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   deviceName: 'iPhone 8'
[Appium]   xcodeOrgId: 'xxxxxxxxxx'
[Appium]   udid: 'f899b567337e8eb4505ccad03752e00f56809ac8'
[Appium]   automationName: 'xcuitest'
[Appium]   noReset: true
[Appium]   command_executor: 'http://127.0.0.1:4723/wd/hub'
[Appium]   xcodeSigningId: 'iPhone Developer'
[Appium]   newCommandTimeout: 300
[Appium]   platformVersion: '11.4'
[Appium]   path: ''
[Appium]   platformName: 'iOS'
[Appium]   bundleId: 'com.xx.inhouse'
[debug] [BaseDriver] W3C capabilities [] and MJSONWP desired capabilities {"deviceName":"iPhone 8","x... were provided
[BaseDriver] Falling back to MJSONWP desired capabilities
[BaseDriver] The following capabilities were provided, but are not recognized by appium: command_executor, path.
[BaseDriver] Session created with session id: 6e484fc3-1c7a-4830-b890-593e708d6c68
[debug] [XCUITest] Current user: 'didi'
[debug] [XCUITest] Xcode version set to '9.4.1' (tools v9.4.1.0.1.1528165917)
[debug] [XCUITest] iOS SDK Version set to '11.4'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1538126862692 (17:27:42 GMT+0800 (中国标准时间))
[debug] [XCUITest] Available devices: f899b567337e8eb4505ccad03752e00f56809ac8
[debug] [XCUITest] Creating iDevice object with udid 'f899b567337e8eb4505ccad03752e00f56809ac8'
[XCUITest] Determining device to run tests on: udid: 'f899b567337e8eb4505ccad03752e00f56809ac8', real device: true
[debug] [BaseDriver] Event 'appConfigured' logged at 1538126863010 (17:27:43 GMT+0800 (中国标准时间))
[debug] [BaseDriver] Event 'resetStarted' logged at 1538126863010 (17:27:43 GMT+0800 (中国标准时间))
[debug] [XCUITest] Reset: fullReset not set. Leaving as is
[debug] [BaseDriver] Event 'resetComplete' logged at 1538126863011 (17:27:43 GMT+0800 (中国标准时间))
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Starting iOS device log capture with: 'idevicesyslog'
[XCUITest] Cannot get the name of the crashes folder for the device with udid 'f899b567337e8eb4505ccad03752e00f56809ac8'. Original error: Command 'idevicename -u f899b567337e8eb4505ccad03752e00f56809ac8' exited with code 255
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1538126863835 (17:27:43 GMT+0800 (中国标准时间))
[XCUITest] Setting up real device
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/_appium-xcuitest-driver@2.92.1@appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/_appium-xcuitest-driver@2.92.1@appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[debug] [XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[debug] [JSONWP Proxy] Matched '/status' to command name 'getStatus'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] WDA is not listening at 'http://localhost:8100/'
[debug] [XCUITest] WDA is currently not running. There is nothing to cache
[debug] [XCUITest] Trying to start WebDriverAgent 1 times with 10000ms interval
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1538126864138 (17:27:44 GMT+0800 (中国标准时间))
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing running processes 'xcodebuild.*f899b567337e8eb4505ccad03752e00f56809ac8, iproxy 8100' for the device f899b567337e8eb4505ccad03752e00f56809ac8...
[debug] [XCUITest] 'pgrep -nif xcodebuild.*f899b567337e8eb4505ccad03752e00f56809ac8' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] 'pgrep -nif iproxy 8100' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB for the device f899b567337e8eb4505ccad03752e00f56809ac8
[debug] [XCUITest] Using Xcode 9.4.1, so fixing WDA codebase
[debug] [XCUITest] Generating xcode config file for orgId 'xxxxxxxxxx' and signingId 'iPhone Developer'
[debug] [XCUITest] Writing xcode config file to /var/folders/2w/tt1p_4td3yq9xlbl7c2t4jn00000gn/T/2018828-18198-970f0z.bpuwn/appium-temp.xcconfig
[debug] [XCUITest] Using Xcode configuration file: '/var/folders/2w/tt1p_4td3yq9xlbl7c2t4jn00000gn/T/2018828-18198-970f0z.bpuwn/appium-temp.xcconfig'
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/_appium-xcuitest-driver@2.92.1@appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=f899b567337e8eb4505ccad03752e00f56809ac8 IPHONEOS_DEPLOYMENT_TARGET=11.4 -xcconfig /var/folders/2w/tt1p_4td3yq9xlbl7c2t4jn00000gn/T/2018828-18198-970f0z.bpuwn/appium-temp.xcconfig' in directory '/usr/local/lib/node_modules/appium/node_modules/_appium-xcuitest-driver@2.92.1@appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged. To change this, use 'showXcodeLog' desired capability
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Matched '/status' to command name 'getStatus'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Matched '/status' to command name 'getStatus'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Matched '/status' to command name 'getStatus'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Log file for xcodebuild test: /var/folders/2w/tt1p_4td3yq9xlbl7c2t4jn00000gn/T/com.apple.dt.XCTest/IDETestRunSession-C33BED17-9C15-468D-8058-B1141C636044/WebDriverAgentRunner-BE913B4F-B997-4607-A64A-389CEFD28545/Session-WebDriverAgentRunner-2018-09-28_172756-faSaGt.log
[debug] [JSONWP Proxy] Matched '/status' to command name 'getStatus'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Matched '/status' to command name 'getStatus'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Matched '/status' to command name 'getStatus'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Matched '/status' to command name 'getStatus'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Matched '/status' to command name 'getStatus'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Matched '/status' to command name 'getStatus'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Matched '/status' to command name 'getStatus'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"11.4\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"11.4\",\n      \"ip\" : \"172.22.139.27\"\n    },\n    \"build\" : {\n      \"time\" : \"Sep 26 2018 16:08:49\"\n    }\n  },\n  \"sessionId\" : \"00C0CC62-A29B-446C-87BB-5C6C6C1656D0\",\n  \"status\" : 0\n}"
[debug] [XCUITest] WebDriverAgent information:
[debug] [XCUITest] {
[debug] [XCUITest]   "state": "success",
[debug] [XCUITest]   "os": {
[debug] [XCUITest]     "name": "iOS",
[debug] [XCUITest]     "version": "11.4"
[debug] [XCUITest]   },
[debug] [XCUITest]   "ios": {
[debug] [XCUITest]     "simulatorVersion": "11.4",
[debug] [XCUITest]     "ip": "172.22.139.27"
[debug] [XCUITest]   },
[debug] [XCUITest]   "build": {
[debug] [XCUITest]     "time": "Sep 26 2018 16:08:49"
[debug] [XCUITest]   }
[debug] [XCUITest] }
[debug] [XCUITest] WebDriverAgent successfully started after 13682ms
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1538126883019 (17:28:03 GMT+0800 (中国标准时间))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Matched '/session' to command name 'createSession'
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.xx.inhouse","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"sessionId":"E76BD7F8-F242-48F5-A573-449D4391CE49","capabilities":{"device":"iphone","browserName":"滴滴出行","sdkVersion":"11.4","CFBundleIdentifier":"com.xx.inhouse"}},"sessionId":"E76BD7F8-F242-48F5-A573-449D4391CE49","status":0}
[debug] [BaseDriver] Event 'wdaSessionStarted' logged at 1538126888353 (17:28:08 GMT+0800 (中国标准时间))
[debug] [BaseDriver] Event 'wdaStarted' logged at 1538126888353 (17:28:08 GMT+0800 (中国标准时间))
[XCUITest] Skipping setting of the initial display orientation. Set the "orientation" capability to either "LANDSCAPE" or "PORTRAIT", if this is an undesired behavior.
[debug] [BaseDriver] Event 'orientationSet' logged at 1538126888354 (17:28:08 GMT+0800 (中国标准时间))
[Appium] New XCUITestDriver session created successfully, session 6e484fc3-1c7a-4830-b890-593e708d6c68 added to master session list
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1538126888356 (17:28:08 GMT+0800 (中国标准时间))
[debug] [W3C] Responding to client with driver.createSession() result: {"capabilities":{"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"deviceName":"iPhone 8","xcodeOrgId":"xxxxxxxxxx","udid":"f899b567337e8eb4505ccad03752e00f56809ac8","automationName":"xcuitest","noReset":true,"command_executor":"http://127.0.0.1:4723/wd/hub","xcodeSigningId":"iPhone Developer","newCommandTimeout":300,"platformVersion":"11.4","path":"","platformName":"iOS","bundleId":"com.xx.inhouse"}}
[HTTP] <-- POST /wd/hub/session 200 25975 ms - 625
[HTTP]
[HTTP] --> GET /wd/hub/session/6e484fc3-1c7a-4830-b890-593e708d6c68/screenshot
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.getScreenshot() with args: ["6e484fc3-1c7a-4830-b890-593e708d6c68"]
[debug] [XCUITest] Executing command 'getScreenshot'
[debug] [XCUITest] Taking screenshot with WDA
[debug] [JSONWP Proxy] Matched '/screenshot' to command name 'getScreenshot'
[debug] [JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/E76BD7F8-F242-48F5-A573-449D4391CE49/screenshot] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"iVBORw0KGgoAAAANSUhEUgAAAu4AAAU2CAIAAABFtaRRAAAAAXNSR0IArs4c6QAA\\r\\nABxpRE9UAAAAAgAAAAAAAAKbAAAAKAAAApsAAAKbAAHuOGiYLQYAAEAASURBVHgB\\r\\n7N0HgGZFlTZ+\\/xu+3W\\/Dt8GNru7q7qprzlnXiAGQqIK4BAEJKkhmYk\\/35CGngWEY\\r\\nhgwSFcwCijlgQhEYhhnEHNZAZuL7\\/739zBzv9nQ3E3qmm\\/UWl5q6VadOnTqVnjpV\\r\\n9+1HdVrXamALauDBzq9XdO5dubqzbEVn9arus4q\\/mgT3dzoPdFZ3Yzqdez3iVqxa\\r\\nyet\\/xHYT+t1Dnc5DKLtP59fdB5VnVN3qhitBVq4cbbFKlDbQaqDVwO+gBvrnyf4Z\\r\\n06TZfdbMluZfz8rl3ac7tXanWk+m1fX37+l0PGvcylUdT\\/+MvbqzwtNZnac70Yf\\/\\r\\nWtKR\\/\\/dRI8+y5dhqYGgNwDGe5St\\/C2XW0g4CZbpY5RECZdbWAjLrOsCmYtpAq4FW\\r\\nA60GRkcD\\/aikhTKjo\\/y21P\\/FGli+PDaY+zodz\\/LVqx5auayL3bs7gq7ZZdXqVStW\\r\\nP9jpLBOOPSbKSLg\\/V7YM3Y1El777rAH8v+h0PKPjWuwyOnpvS2010GpgGA1knuyf\\r\\nMzNNZvrMxLnWtt2fvzmvJtf6+2G9Zh7ucvsfZYXzmoKHkXWTklqrzCapr828oRoo\\r\\nKLPaKdJqgGX5mkGVYeNl9UpQpotmVkM9jJ9xYx3KkDL2mLUCD3yt+DbQaqDVQKuB\\r\\nLaSBFspsIUW3xfyuaWAN9l\\/N\\/tLFMZ7Vy1Ytv3\\/NqeoaS0wMov2jcF1E34xpgv81\\r\\nYOh3TaFtfVsNtBpoNTCUBvo3gf3XEjNxZm61VYzt224y8Rt8TSb...
[debug] [W3C] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAAAu4AAAU2CAIAAABFtaRRAAAAAXNSR0IArs4c6QAA\r\nABxpRE9UAAAAAgAAAAAAAAKbAAAAKAAAApsAAAKbAAHuOGiYLQYAAEAASURBVHgB\r\n7N0HgGZFlTZ+/xu+3W/Dt8GNru7q7qprzlnXiAGQqIK4BAEJKkhmYk/35CGngWEY\r\nhgwSFcwCijlgQhEYhhnEHNZAZuL7/739zBzv9nQ3E3qmm/UWl5q6VadOnTqVnjpV\r\n9+1HdVrXamALauDBzq9XdO5dubqzbEVn9arus4q/mgT3dzoPdFZ3Yzqdez3iVqxa\r\nyet/xHYT+t1Dnc5DKLtP59fdB5VnVN3qhitBVq4cbbFKlDbQaqDVwO+gBvrnyf4Z\r\n06TZfdbMluZfz8rl3ac7tXanWk+m1fX37+l0PGvcylUdT/+MvbqzwtNZnac70Yf/\r\nWtKR//dRI8+y5dhqYGgNwDGe5St/C2XW0g4CZbpY5RECZdbWAjLrOsCmYtpAq4FW\r\nA60GRkcD/aikhTKjo/y21P/FGli+PDaY+zodz/LVqx5auayL3bs7gq7ZZdXqVStW\r\nP9jpLBOOPSbKSLg/V7YM3Y1El777rAH8v+h0PKPjWuwyOnpvS2010GpgGA1knuyf\r\nMzNNZvrMxLnWtt2fvzmvJtf6+2G9Zh7ucvsfZYXzmoKHkXWTklqrzCapr828oRoo\r\nKLPaKdJqgGX5mkGVYeNl9UpQpotmVkM9jJ9xYx3KkDL2mLUCD3yt+DbQaqDVQKuB\r\nLaSBFspsIUW3xfyuaWAN9l/N/tLFMZ7Vy1Ytv3/NqeoaS0wMov2jcF1E34xpgv81\r\nYOh3TaFtfVsNtBpoNTCUBvo3gf3XEjNxZm61VYzt224y8Rt8TSbZcj+mP5yIbDqb\r\n/hrOm3l+bq0yQ/WANn7zaGC1e2YrVhsAOn5n+coVrvrGNuMC2rLVq4SNgkcelFnO\r\n...
[HTTP] <-- GET /wd/hub/session/6e484fc3-1c7a-4830-b890-593e708d6c68/screenshot 200 311 ms - 234308
[HTTP]
[HTTP] --> DELETE /wd/hub/session/6e484fc3-1c7a-4830-b890-593e708d6c68
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.deleteSession() with args: ["6e484fc3-1c7a-4830-b890-593e708d6c68"]
[debug] [BaseDriver] Event 'quitSessionRequested' logged at 1538126903728 (17:28:23 GMT+0800 (中国标准时间))
[debug] [JSONWP Proxy] Matched '/session/6e484fc3-1c7a-4830-b890-593e708d6c68' to command name 'deleteSession'
[debug] [JSONWP Proxy] Proxying [DELETE /session/6e484fc3-1c7a-4830-b890-593e708d6c68] to [DELETE http://localhost:8100/session/E76BD7F8-F242-48F5-A573-449D4391CE49] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n\n  },\n  \"sessionId\" : \"3A04C6AD-8264-456F-BB1B-FC7693DCC9B8\",\n  \"status\" : 0\n}"
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [iOSLog] Stopping iOS log capture
[Appium] Removing session 6e484fc3-1c7a-4830-b890-593e708d6c68 from our master session list
[debug] [BaseDriver] Event 'quitSessionFinished' logged at 1538126904025 (17:28:24 GMT+0800 (中国标准时间))
[debug] [W3C] Received response: null
[debug] [W3C] But deleting session, so not returning
[debug] [W3C] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/6e484fc3-1c7a-4830-b890-593e708d6c68 200 300 ms - 14
[HTTP]
[debug] [XCUITest] Connection to WDA timed out
[debug] [iProxy] recv failed: Operation not permitted
^C[Appium] Received SIGINT - shutting down
[debug] [XCUITest] Log file for xcodebuild test: /var/folders/2w/tt1p_4td3yq9xlbl7c2t4jn00000gn/T/com.apple.dt.XCTest/IDETestRunSession-C33BED17-9C15-468D-8058-B1141C636044/WebDriverAgentRunner-BE913B4F-B997-4607-A64A-389CEFD28545/Session-WebDriverAgentRunner-2018-09-28_191930-OpmUHZ.log
[Xcode] 2018-09-28 19:19:30.378 xcodebuild[18222:25850765] [MT] IDETestOperationsObserverDebug: (E9FD78AD-C3A0-4817-A90F-D6623AC75281) Failed to make test runner session:
[Xcode] Error Domain=com.apple.dt.xctest.error Code=4 "Unable to find device with identifier: f899b567337e8eb4505ccad03752e00f56809ac8" UserInfo={NSLocalizedDescription=Unable to find device with identifier: f899b567337e8eb4505ccad03752e00f56809ac8}
[Xcode] 2018-09-28 19:19:30.401 xcodebuild[18222:25850765] Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Unable to find device with identifier: f899b567337e8eb4505ccad03752e00f56809ac8 If you believe this error represents a bug, please attach the log file at /var/folders/2w/tt1p_4td3yq9xlbl7c2t4jn00000gn/T/com.apple.dt.XCTest/IDETestRunSession-C33BED17-9C15-468D-8058-B1141C636044/WebDriverAgentRunner-BE913B4F-B997-4607-A64A-389CEFD28545/Session-WebDriverAgentRunner-2018-09-28_191930-OpmUHZ.log" UserInfo={NSLocalizedDescription=Unable to find device with identifier: f899b567337e8eb4505ccad03752e00f56809ac8 If you believe this error represents a bug, please attach the log file at /var/folders/2w/tt1p_4td3yq9xlbl7c2t4jn00000gn/T/com.apple.dt.XCTest/IDETestRunSession-C33BED17-9C15-468D-8058-B1141C636044/WebDriverAgentRunner-BE913B4F-B997-4607-A64A-389CEFD28545/Session-WebDriverAgentRunner-2018-09-28_191930-OpmUHZ.log}
[Xcode]
[Xcode] Testing failed:
[Xcode] 	Unable to find device with identifier: f899b567337e8eb4505ccad03752e00f56809ac8 If you believe this error represents a bug, please attach the log file at /var/folders/2w/tt1p_4td3yq9xlbl7c2t4jn00000gn/T/com.apple.dt.XCTest/IDETestRunSession-C33BED17-9C15-468D-8058-B1141C636044/WebDriverAgentRunner-BE913B4F-B997-4607-A64A-389CEFD28545/Session-WebDriverAgentRunner-2018-09-28_191930-OpmUHZ.log
[Xcode] ** TEST EXECUTE FAILED **

**Comment by mykola-mokhnach** [comment]
> I don't understand why the delete session operation is performed

Me too. There must be a problem in the client code.

**Comment by KazuCocoa** [comment]
> The following problems exist in the logs：The following capabilities were provided, but are not recognized by appium: command_executor, path.

I guess you're using Python client. In the case, I assume your capability is wrong. You can find some `command_executor` in Python samples like https://github.com/appium/appium/blob/cd12ed9a511b061244c98701614f7f13b7ae3725/sample-code/python/test/test_android_basic_interactions.py#L17-L26

Your log looks calling `delete` after getting screenshot. Could you take a look at your code again correcting your capability?

**Comment by KazuCocoa** [comment]
@Ocean0227 ^

**Comment by Ocean0227** [comment]
> > I don't understand why the delete session operation is performed
> 
> Me too. There must be a problem in the client code.

Confirmed ，It's a code issue，thank you very much~
