### ISSUE TITLE
npm install fails for v1.9.1

### ISSUE THREAD

**Issue by h3dkandi** [appium/appium#11453]
## The problem
I run Appium from the git clone.
I saw that there is a stable 1.9.1 release and decided to switch git head to it from 1.9.0 . When I removed the node_modules directory  and ran npm install it failed at gulp prepublish the error was:
`Error: Cannot find module 'lodash/lang/isFunction'`
 
## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable): 1.9.0
* Desktop OS/version used to run Appium: macOS 10.13.6 
* Node.js version (unless using Appium.app|exe): v10.11.0
* NPM version: 6.4.1

## Details

I did a clean git clone and then checked out the tag for 1.9.1
NPM debug log [gist](https://gist.github.com/h3dkandi/d0e1d61a60785317d1967f7e92f847bd)
Relevant part of the console output:
```
> node postinstall

npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> appium@1.9.1 prepublish /Users/macmini2014/automated_testing/github/appium
> gulp prepublish

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'lodash/lang/isFunction'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/macmini2014/automated_testing/github/appium/node_modules/babel-core/lib/api/node.js:21:29)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium@1.9.1 prepublish: `gulp prepublish`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium@1.9.1 prepublish script.
```

**Comment by KazuCocoa** [comment]
I could reproduce it. it looks npm and versions in package.json, I guess.

Can you install `appium@1.9.1`?

**Comment by h3dkandi** [comment]
What do you mean by install. Install the 1.7 binary an update to 1.9.1 trough it? Or do you mean if Appium works despite this step breaking?

**Comment by KazuCocoa** [comment]
@h3dkandi 
What about `$ npm install --production`?
Since the tagged branch has `shrinkwrap` which only has "dependencies".
On my env, it succeeded to build.

**Comment by h3dkandi** [comment]
Using `$ npm install --production` completes without errors but... When I run `node .` inside the Appium folder to see if it starts it spits this:

```
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/Users/macmini2014/automated_testing/github/appium'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:752:3)

```

**Comment by KazuCocoa** [comment]
@h3dkandi 
mmm.
I completed to install & run with `node .` on my env.

node is v10.11.0.
npm is 6.4.1.

What version of npm did you use?

**Comment by h3dkandi** [comment]
Same versions as well: node is v10.11.0, npm is 6.4.1.
Here is what I do:

```
git clone https://github.com/appium/appium.git
cd appium
git checkout tags/v1.9.1
npm install --production
node .
```

Here is what the terminal spits during `npm install --production`: [gist](https://gist.github.com/h3dkandi/ae252092c0fe9ea23a7badb771d8a70e)

**Comment by KazuCocoa** [comment]
what about below? (maybe, `build` doesn't need though)

```
git clone https://github.com/appium/appium.git
cd appium
git checkout tags/v1.9.1
npm install --production
npm install
npm run build
node .
```

**Comment by h3dkandi** [comment]
This seems to do the job. Thank you for your time and help.
