### ISSUE TITLE
UI automator shows error on Launching.

### ISSUE THREAD

**Issue by vasu1122** [appium/appium#11456]
While launching UI Automator through command line or by double clicking the batch file,UI automator is not launched.Error comes up everytime after I pass the command through cmd. 
![error](https://user-images.githubusercontent.com/36469577/46250115-9110ea00-c451-11e8-94c8-6d1aab218360.PNG)

**Comment by KazuCocoa** [comment]
This is not Appium toolchain.

https://developer.android.com/training/testing/ui-automator

Please search it on the web (or any forums)

**Comment by vasu1122** [comment]
> This is not Appium toolchain.
> 
> https://developer.android.com/training/testing/ui-automator
> 
> Please search it on the web (or any forums)

Working fine after I installed Java version 8.Issue is with java 9 update.
