### ISSUE TITLE
Question: Is it possible to get sibling in class chain

### ISSUE THREAD

**Issue by romansvesh** [appium/appium#11451]
## The problem
1) Is it possible to rewrite this xpath to class chain? How exactly can I do it?
///XCUIElementTypeStaticText[@name="Name 1"]/following-sibling::XCUIElementTypeTextField[@name="Name 2"]

2) by the way, how rewrite this xpath to class chain? I have no idea :(
//XCUIElementTypeCell[./XCUIElementTypeStaticText[@name="Video"]]/XCUIElementTypeButton

**Comment by mykola-mokhnach** [comment]
No, this is not possible, at least in a single query.

**Comment by mykola-mokhnach** [comment]
Please use appium forum for questions
