### ISSUE TITLE
elementByImage returns wrong coordinates for the found image.

### ISSUE THREAD

**Issue by zbranzov** [appium/appium#11460]
## The problem

I run a simple test case where a bigger more complicated image center is far above the expected. This is the image I'm looking for https://www.screencast.com/t/K9GGCPZ7Q . In the video https://screencast.com/t/u2BobJLzst you will see that the click is not happening in the center of the image we are looking for. So in the case with the simpler image "blue square" it clicks on top of it but still able to click. On the other side, when looking for the more complex image above, it clicks too far above the matching center.
In my code I'm using :
wd.updateSettings({imageMatchThreshold: 0.9});
wd.updateSettings({autoUpdateImageElementPosition: true});
wd.updateSettings({fixImageTemplateSize: true});

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.0
* Last Appium version that did not exhibit the issue (if applicable): never used image recognition before
* Desktop OS/version used to run Appium: Mac OSX High Sierra 10.13.6
* Node.js version (unless using Appium.app|exe): 8.9.4
* Mobile platform/version under test: iOS 11.2/Android 24
* Real device or emulator/simulator: emulator/simulator
* Appium CLI or Appium.app|exe:

## Code To Reproduce Issue [ Good To Have ]

I'm using JavaScript client 'wd' and elementByImageFile('path to image') method which seems to find the image but on click, it clicks far above its center.

**Comment by mykola-mokhnach** [comment]
@jlipps Do you have anything to add here?

**Comment by saikrishna321** [comment]
@mykola-mokhnach i tried with java-client with latest appium beta and i get NoSuchElementException 

https://gist.github.com/saikrishna321/d21248eec9a0f73880196022261ff4b3

```
        File file = new File("/Users/saikrisv/Desktop/login.png");
        File refImgFile = Paths.get(file.toURI()).toFile();
        String s = Base64.getEncoder().encodeToString(Files.readAllBytes(refImgFile.toPath()));
        driver.findElementByImage(s).click();
```
###  Image to click
<img width="73" alt="login" src="https://user-images.githubusercontent.com/4045041/46317030-cd675600-c5c9-11e8-8fba-6319271c208a.png">

### Actual Screen
![simulator screen shot - iphone x - 2018-10-01 at 22 25 42](https://user-images.githubusercontent.com/4045041/46317031-cd675600-c5c9-11e8-854b-5766f7121c20.png)

**Comment by zbranzov** [comment]
@mykola-mokhnach I'll try to get the logs. Why did you put iOS label only? It happens on Android too as in the video.

**Comment by mykola-mokhnach** [comment]
You can actually try to get the rectangle of the matched element and compare it with the current view layout. Click must be performed at the center of this rectangle.

**Comment by saikrishna321** [comment]
@KazuCocoa No luck it's still the same.

**Comment by zbranzov** [comment]
[log.txt.zip](https://github.com/appium/appium/files/2440935/log.txt.zip)
Hi @mykola-mokhnach,
Please find attached the log. It is a console output so it can have other stuff as well. The image search begins at around line 3231. What I found strange is that the second image I search for (https://www.screencast.com/t/K9GGCPZ7Q) has been found far above its real coordinates https://screencast.com/t/Levw12Qx

**Comment by saikrishna321** [comment]
@mykola-mokhnach 

```
        File screenshotAs = driver.getScreenshotAs(OutputType.FILE);
        OccurrenceMatchingResult result = driver
                .findImageOccurrence(screenshotAs, new File("/Users/saikrisv/Desktop/login.png") ,
                        new OccurrenceMatchingOptions()
                        .withEnabledVisualization());
```

https://gist.github.com/saikrishna321/4088a4dc0bbfffb732482c7d48673f47

Any help here ?

**Comment by mykola-mokhnach** [comment]
@zbranzov Any updates?

**Comment by zbranzov** [comment]
@mykola-mokhnach Sorry, I was afk for a while. I'm using the JavaScript client https://github.com/admc/wd and assume that saveScreenshot method is what happens on the server to create screenshot. If this is true, I can try to use the screenshot and my template and compare them using opencv4nodejs to check the outcome. I suspect that the screenshot is somehow different from the expected but I'm not sure how to obtain the one made from the comparison process.

**Comment by EzimetYusup** [comment]
@mykola-mokhnach  @zbranzov I'm using python client, I think the screenshot not matching the dimensions of the screen itself, in my case if the device is iphone6 the coordinate returned by finde_element_by_image and actual position in device's coordinate system is exactly 2x, if i divide the x,y of element  by 2, and click on that coordinate, it is working as expected,FYI i have turned on fixImageFindScreenshotDims, but this flag doesn't fix the problem at all

**Comment by mykola-mokhnach** [comment]
@EzimetYusup Try it with https://github.com/appium/appium-base-driver/pull/306

**Comment by EzimetYusup** [comment]
@mykola-mokhnach  not sure how to do it, how can i make a version with this pull request, since this appium-base-driver is 
a module for Appium.

**Comment by mykola-mokhnach** [comment]
https://appiumpro.com/editions/47
