### ISSUE TITLE
Appium 1.9.1 is not able to find the UIbutton

### ISSUE THREAD

**Issue by SanjayDhami** [appium/appium#11463]
I was using appium 1.8 with xcode 9.4 before and tests were working fine, once i updated to appium 1.9.1 and xcode 10, i see that appium is not able to see the some of ui buttons. i did driver.getSource()  and even i cannot see UIButton in source but it does showed in previous version( same version of app). is there something i can get help on this.

**Comment by auto-mator** [comment]
I was having the same issue, so stopped using 1.9.1 right away.

**Comment by XianfengCai** [comment]
I'm facing the same issue on Android, I used v1.7.2 before, it works fine. But now v1.9.1 randomly can't find the UI widgets from the screen.

**Comment by KazuCocoa** [comment]
Can anyone attach server logs with some information following the issue template?
https://github.com/appium/appium/issues/new

`page_source` also help us to investigate the cause.

**Comment by mykola-mokhnach** [comment]
No logs - no luck
