### ISSUE TITLE
Interactions not available for some elements in Android application

### ISSUE THREAD

**Issue by mojojojo94** [appium/appium#11462]
## The problem

Interactions not available for some elements in Android application

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.0
* Last Appium version that did not exhibit the issue (if applicable): 1.8.1
* Desktop OS/version used to run Appium: 10.13.4
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: both

## Details

Not able to automate / interact with elements with new app build devs have created, they detailed they moved from an fragment framework to an activity framework and some pages are entirely written in kotlin. We are able to interact with some pages and not with others. I was hoping the appium team knows if there is an accessibility setting that the android devs are missing because they are unclear. We are able to automate/interact with previous builds of the app but not the new versions since the previously mentioned changes were introduced.

**Comment by mojojojo94** [comment]
I am not able to get any data from element attributes, for example clicking, send keys, get text/name/class and such. Elements are visible on the page source though. I will attach a screen shot.

**Comment by mykola-mokhnach** [comment]
In general the app should follow the general accessibility design requirements: https://codelabs.developers.google.com/codelabs/basic-android-accessibility/index.html

**Comment by mojojojo94** [comment]
<img width="1079" alt="screen shot 2018-09-20 at 7 41 50 pm" src="https://user-images.githubusercontent.com/15100526/46305192-5654a200-c576-11e8-91ec-f9cc43dd98fa.png">

**Comment by mykola-mokhnach** [comment]
this might be a problem with appium inspector itself. What is in the server log?

**Comment by mojojojo94** [comment]
This is just view in the appium inspector, but I am not able to run my automated scripts using appium because appium is not able to click/get data/send keys with the elements. Before the android devs made the change from a fragment framework to an activity framework it worked. Even today if I run my android automated scripts against the older version of the build those scripts work. They also changes lots of ids and I made those changes accordingly, but some ids have not like the above one yet appium is not able to interact with it. I am thinking it has to do with some accessibility setting that the devs missed when doing a lot of the refactor and writing this page in Kotlin. 

I will share an old build version run and a new build version run with you, so you can compare the logs of both.

**Comment by mykola-mokhnach** [comment]
Any updates? If none then I'm going to close the report

**Comment by mojojojo94** [comment]
Apologies, got caught up, let me upload gist of the appium logs right away.

**Comment by mojojojo94** [comment]
Appium server logs of the old version that works
https://gist.github.com/mojojojo94/e094283d55bbba41735ac2b7d4efdd86

**Comment by mojojojo94** [comment]
Appium server logs new version, that we cannot interact with through appium commands
https://gist.github.com/mojojojo94/5cbd717d2433b3ab45c03fe160c3094d

**Comment by mykola-mokhnach** [comment]
UiAutomator is considered obsolete for Android6+. Switch to uiautomator2

**Comment by Nayay** [comment]
I am facing something similar can you please help me how you resolved it?

**Comment by duvergara** [comment]
I am facing something similar can you please help me how you resolved it? please

**Comment by satyasreem** [comment]
Using UIAutomator2 as automationName works with the inspector.

**Comment by ost1007** [comment]
I'm still facing the same issue with UiAutomator2.

**Comment by red1586** [comment]
Still facing this issue, anyone resolved it ?

**Comment by red1586** [comment]
![image](https://user-images.githubusercontent.com/83364970/116480191-e4888600-a84e-11eb-980f-1b4e230326b6.png)

**Comment by Afusuma** [comment]
I'm still facing the same issue with UiAutomator2.

**Comment by meabtestuser** [comment]
It does not working, i'm trying to access the mailinator inbox to catch the OTP however the appium is unable to find the element , tried to locate element using both uiautomator and automator2 however no luck so far

**Comment by mtaylor-evidation** [comment]
Also having this issue. We cannot seem to interact with the elements using React Native. Getting a similar error.

**Comment by swatitest-prog** [comment]
i am facing same issue can anyone help me.
