### ISSUE TITLE
Inconsistent behavior on Android and IOS

### ISSUE THREAD

**Issue by gkvappium** [appium/appium#11472]
## The problem

There is a cell which when tapped, shows a check mark. I can spy the text as well as the check mark on android. During validation of the check mark, there is no problem. But in case of IOS, when there is a table view and in this view when we tap a cell, the check mark is not spyable. Appium also tells that that this element is not interactive. As a result I cannot do any validations on this screen for IOS

## Environment

* Appium version (or git revision) that exhibits the issue:1.9.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOSX 1.7.1
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: IOS 12.0
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

![screen shot 2018-10-03 at 3 25 36 pm](https://user-images.githubusercontent.com/27851378/46404068-ceab9680-c721-11e8-96a4-5de2c8d34787.png)
![screen shot 2018-10-03 at 3 26 48 pm](https://user-images.githubusercontent.com/27851378/46404069-cf442d00-c721-11e8-8fe4-5b6fa8bc0aca.png)

@mykola-mokhnach , any input from your side on this issue?

**Comment by mykola-mokhnach** [comment]
The actual behaviour is defined by XCTest/WebDriverAgent and there is nothing we can change there on Appium side.

You could also try to ask at https://github.com/facebook/WebDriverAgent

Closed as third party issue.
