### ISSUE TITLE
Need help to register nodes to selenium hub  http://192.168.56.1:4444

### ISSUE THREAD

**Issue by Pramodnp28** [appium/appium#11474]
## The problem

Am trying to register appium nodes for parallel execution using selenium jar selenium-server-standalone-3.14.0 it was starting on localhost i.e 127.0.0.1:4444 but once I install dockers appium image selenium hub is starting on http://192.168.56.1:4444 
## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable): 1.6.3 
* Desktop OS/version used to run Appium:  Windows 10 

## Details

running this command to start selenium hub java -jar selenium-server-standalone-3.14.0.jar -role hub

## Code To Reproduce Issue [ Good To Have ]

`{
"capabilities":
[
{
"browserName": "",
"version": "8.0.0",
"maxInstances": 1,
"platform": "ANDROID",
"deviceName": "5200759ab48925bf"
}
],
"configuration":
{
"nodeTimeout":120, 
"port":4728, 
"hubPort":4444,
"proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
"url":"http://192.168.56.1:4444/grid/register/",
"hub": "192.168.56.1:4444/wd/hub",
"hubHost":"192.168.56.1",
"registerCycle":10000,
"register":true,
"cleanUpCycle":2000, 
"timeout":30000, 
"maxSession":1
}
}`

**Comment by mykola-mokhnach** [comment]
Please use appium forum for questions
