### ISSUE TITLE
xcode 10 and appium 1.7.2 compatibility issue

### ISSUE THREAD

**Issue by sherylmiscala** [appium/appium#11470]
## The problem

after updating xcode to 10.0 and run my test script, getting `Encountered internal error running command: Error: Xcode version '0.0'. Support for Xcode 0.0 is not supported. Please upgrade to version 7.3 or higher` error.

## Environment
* Appium version 1.7.2 that exhibits the issue:
* macOS High Sierra, 10.13.6 used to run Appium:
* Real device - iphone os12:

## Link to Appium logs
https://gist.github.com/sherylmiscala/90b6f3aa2f60f73cb539d591b59254b5

**Comment by SrinivasanTarget** [comment]
@sherylmiscala logs are quite readable. appium 1.7.0 is years old. please install latest version of appium which is v1.9.2-beta.1 or 1.9.1 which supports xcode 10.

**Comment by sherylmiscala** [comment]
I'm using that old version as its the version required for AWS device farm - https://docs.aws.amazon.com/devicefarm/latest/developerguide/test-types-android-appium-java-junit.html

**Comment by SrinivasanTarget** [comment]
@sherylmiscala Please reach AWS then.
