### ISSUE TITLE
Appium 1.8.1 on iOS real device is still very slow

### ISSUE THREAD

**Issue by mihaiserdeanyopeso** [appium/appium#11479]
Appium latest on iOS real device is still very slow. Can you give us some hints on how to make it run faster? We have fluent Waits and are not using hardcoded timeouts.
We have latest Appium, latest Serenity-BDD, iPhone 8 connected via USB.

On Android everything works fast.

**Comment by mykola-mokhnach** [comment]
Could you be more precise on what "slow" is?

The general suggestion would be to user the most recent server version and to use [fast](url
https://github.com/facebook/WebDriverAgent/wiki/How-To-Achieve-The-Best-Lookup-Performance) locators

**Comment by livastar** [comment]
> Appium latest on iOS real device is still very slow. Can you give us some hints on how to make it run faster? We have fluent Waits and are not using hardcoded timeouts.
> We have latest Appium, latest Serenity-BDD, iPhone 8 connected via USB.
> 
> On Android everything works fast.

Hi @mihaiserdeanyopeso,
:) This is not related to appium at all. :) What we've faced in our daily work it's [WDA](https://github.com/facebook/WebDriverAgent/issues). 
This is the hardest and not stable part of iOS automation. 
@mykola-mokhnach, @TikhomirovSergey correct me if I'm wrong, guys :)

**Comment by mykola-mokhnach** [comment]
I'd rather not try to guess without having a proper and detailed problem description

**Comment by tomaszjam** [comment]
Hi @mihaiserdeanyopeso ,
I am currently developing ios tests (however during development i run them on Simulator of Iphone X with ios 11.4).
I got similar - slow results with appium 1.8.1.
However a few days ago I went into using 1.9.1 (with java-client of appium version 6.1.0) and after some code corrections it seems that it's going nearly 3x faster (on 1.8.1 full test suite was running about 45 minutes, now it's 18).
Maybe consider trying to update?

**Comment by mihaiserdeanyopeso** [comment]
@tomaszjam thanks for the info. We will try and get back to you.

**Comment by mykola-mokhnach** [comment]
Closed as incomplete

**Comment by cristianmuresan** [comment]
We have updated the dependency from pom.xml (java-client 6.1.0, serenity 2.0.4) and appium 1.9.1. Running the tests on iOS real devices is really improved. Thanks for the info.

**Comment by tomaszjam** [comment]
I'm glad that I could help, you are welcome.

**Comment by syedzubair1989** [comment]
Hi @tomaszjam , what code changes did u do for ios automation to become 3x faster.
I am currently using Appium server version 1.10.0 , and java-client 6.1.0 and it's still very slow.

@mykola-mokhnach  can you please help on this slowness issue, the same scenario which takes 50 seconds on Android takes close to 5 minutes on iOS. 

I am automating on Iphone 5, and same is the case on other high end iPhones.

**Comment by mykola-mokhnach** [comment]
@syedzubair1989 I cannot help with slowness issue, because it has to do with how XCTest works internally. Which is, thanks to Apple, a black box. Although, I have previously observed lookup speed issues if the application under test contained active background animations and was not in idle state.

**Comment by syedzubair1989** [comment]
@mykola-mokhnach U mean there is no way in appium through  which we can resolve this slowness issue on ios automation.

Any other good automation tool , alternate to appium you know?

**Comment by mykola-mokhnach** [comment]
You can try to write your tests on pure XCTest/Swift. Let us know if it performs better.
