### ISSUE TITLE
Android 8.0 Support for Hybrid App

### ISSUE THREAD

**Issue by MummanaSubramanya** [appium/appium#11487]
## The problem
Im trying to run the tests on Android O but the test fails. Bleow are the things Which I have done:

Setup 1: I had appium 1.8.1 CLI, With Android O real device connected and automation Name: Appium. Test failed as Appium server freezes.
Exception: OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://127.0.0.1:4723/wd/hub/session/009f9f1f-cf3d-44d8-a4e9-d36dc88fcf61/screenshot timed out after 60 seconds. ---> System.Net.WebException: The request was aborted: The operation has timed out.

Setup 2:  I had appium 1.8.1 CLI, With Android O real device connected and automation Name: UiAtuomator2. Test failed as Appium cannot switch to Webview.

Exception:
`[ADB] Zip-aligning 'C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v1.12.0.apk'
[ADB] Signing 'C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v1.12.0.apk' with default cert
[ADB] Starting 'C:\AndroidSDK\build-tools\28.0.1\apksigner.bat' with args 'sign,--key,C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-adb\keys\testkey.pk8,--cert,C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-adb\keys\testkey.x509.pem,C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v1.12.0.apk'
[ADB] Cannot use apksigner tool for signing. Defaulting to sign.jar. Original error: Command 'C\:\\AndroidSDK\\build-tools\\28.0.1\\apksigner.bat sign --key 'C:\\Program Files (x86)\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-adb\\keys\\testkey.pk8' --cert 'C:\\Program Files (x86)\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-adb\\keys\\testkey.x509.pem' 'C:\\Program Files (x86)\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v1.12.0.apk'' exited with code 1; StdErr: Exception in thread "main" java.nio.file.AccessDeniedException: C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v1.12.0.apk`

Setup 3:  I had appium 1.9.1 CLI, With Android O real device connected and automation Name: Appium. Test failed as Appium server freezes.
Exception: OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://127.0.0.1:4723/wd/hub/session/009f9f1f-cf3d-44d8-a4e9-d36dc88fcf61/screenshot timed out after 60 seconds. ---> System.Net.WebException: The request was aborted: The operation has timed out.

Setup 4: I had appium 1.9.1 CLI, With Android O real device connected and automation Name: UIAutomator2. Test failed : https://github.com/appium/appium-dotnet-driver/issues/265

Im unable to automate Android O. which is very important for me. In documents you guys mention Android O/8.0 support is available now it doesn't seem to work.
 
## Environment
* language: C# with specflow
* Appium version (or git revision) that exhibits the issue: 1.8.1 and .19.1
* Mobile platform/version under test: Android O
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe:

**Comment by mykola-mokhnach** [comment]
> x86)\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v1.12.0.apk'' exited with code 1; StdErr: Exception in thread "main" java.nio.file.AccessDeniedException: C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v1.12.0.apk

Most likely there is some third party software on your machine, like an antivirus app, which blocks appium stuff from working properly.

**Comment by MummanaSubramanya** [comment]
@mykola-mokhnach : Sorry but did you read my whole Details? I don't have anything blocking as you could see Setup 4 works fine but the test fails because of different issue appium/appium-dotnet-driver#265

**Comment by mykola-mokhnach** [comment]
Yes I did read it and did respond with what I know of. The problem described in 
https://github.com/appium/appium-dotnet-driver/issues/265 is a client issue and has nothing to do with the server
