### ISSUE TITLE
Unable to connect appium nodes to selenium hub  

### ISSUE THREAD

**Issue by SapizonTechnologiesLLP** [appium/appium#11486]
## The problem

Am unable to register appium nodes to selenium hub after updating appium 

## Environment

* Appium version (or git revision) that exhibits the issue:
*Last Appium version that did not exhibit the issue (if applicable):
*Desktop OS/version used to run Appium: Windows 10 pro
*Mobile platform/version under test: 
*Real device or emulator/simulator: 
*Appium CLI or Appium.app|exe: Appium.app 1.7.1

## Link to Appium logs

https://gist.github.com/SapizonTechnologiesLLP/b3b1f69f7d252e1cf4790632b309cdb1.js

## Code To Reproduce Issue [ Good To Have ]
to start selenium hub : java -jar selenium-server-standalone-3.11.0.jar -role hub -host 127.0.0.1
to start appium node1 : 
node.exe C:\Users\DELL\AppData\Local\Programs\appium\resources\app\node_modules\appium\build\lib\main.js -a 127.0.0.1 -p 4723 -cp 4723 -bp 2251 --udid ce031603b320862704 --nodeconfig C:\Users\DELL\Desktop\AppiumRequired\appiumnodeImp\node1.js
to start appium node2 : 
node.exe C:\Users\DELL\AppData\Local\Programs\appium\resources\app\node_modules\appium\build\lib\main.js -a 127.0.0.1 -p 4728 -cp 4728 -bp 2252 --udid 5200759ab48925bf --nodeconfig C:\Users\DELL\Desktop\AppiumRequired\appiumnodeImp\node2.js

node1.js file
{
"capabilities":
[
{
"browserName": "",
"version": "8.0.0",
"maxInstances": 1,
"platform": "ANDROID",
"deviceName": "ce031603b320862704"
}
],
"configuration":
{
"nodeTimeout":120, 
"port":4723, 
"hubPort":4444,
"proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
"url":"http://127.0.0.1:4723/wd/hub",
"hub": "127.0.0.1:4444/grid/register",
"hubHost":"127.0.0.1",
"registerCycle":10000,
"register":true,
"cleanUpCycle":2000, 
"timeout":30000, 
"maxSession":1
}
}

node2 
{
"capabilities":
[
{
"browserName": "",
"version": "8.0.0",
"maxInstances": 1,
"platform": "ANDROID",
"deviceName": "5200759ab48925bf"
}
],
"configuration":
{
"nodeTimeout":120, 
"port":4728, 
"hubPort":4444,
"proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
"url":"http://127.0.0.1:4723/wd/hub",
"hub": "127.0.0.1:4444/grid/register",
"hubHost":"127.0.0.1",
"registerCycle":10000,
"register":true,
"cleanUpCycle":2000, 
"timeout":30000, 
"maxSession":1
}
}

**Comment by mykola-mokhnach** [comment]
We don't patch older appium versions. Please upgrade to the most recent version first

**Comment by mykola-mokhnach** [comment]
> [Appium] Unable to load node configuration file to register with grid: ENOENT: no such file or directory, open 'C:\Users\DELL\Desktop\AppiumRequired\appiumnodeImp\node2.js'

Also the error there is pretty clear
