### ISSUE TITLE
[iOS parallel execution]: problems about the start of two or more WDA instances

### ISSUE THREAD

**Issue by rtardi** [appium/appium#11480]
## The problem

I'm opening in parallel two or more instances of the WDA (appium_web_driver.Remote in Python), with appium, to execute some tests on more iOS and/or Android devices.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1 (also 1.8.1) 
* Last Appium version that did not exhibit the issue (if applicable): never verified
* Desktop OS/version used to run Appium: macOs High Sierra version 10.13.6
* Node.js version (unless using Appium.app|exe): 8.11.1
* Mobile platform/version under test: iOS 10.3.3, 12.0
* Real device or emulator/simulator: iPhone (iOS 10.3.3), iPad (iOS 10.3.3), iPhone (iOS 12)
* XCode version: 10

## Details

One WDA instance generates an error (for both android or iOS environment).
**SOMETIMES** (random), not always, I have the error about one device WDA instance (you can see the log above)

## Link to Appium logs

[log](https://gist.github.com/rtardi/1c13fc41aa4959d3b0db77980ac124db)

## Code To Reproduce Issue [ Good To Have ]
Started appium server with:
**appium -p 15279 -bp 57059 --webdriveragent-port 57062 --webkit-debug-proxy-port 57065
appium -p 15280 -bp 57060 --webdriveragent-port 57063 --webkit-debug-proxy-port 57066
appium -p 15281 -bp 57061 --webdriveragent-port 57064 --webkit-debug-proxy-port 57067**

Python code:
(three execution in parallel)
**desired_capabilities = {
		'automationName' : 'XCUITest',
		'platformName' : 'iOS',
		'bundleId' : your_app_pkg',
		'showXcodeLog' : 'true',
		'deviceName' : 'your_device_name',
		'udid' : 'your_device_uuid',
		'newCommandTimeout' : 7200
		}
self.desired_capabilities = desired_capabilities
command_executor = 'http://127.0.0.1:' + str(self.appium_service_port) + '/wd/hub'
self.mobile_driver = appium_web_driver.Remote(command_executor, self.desired_capabilities)**

**Comment by KazuCocoa** [comment]
https://stackoverflow.com/questions/35641332/node-js-events-js154-throw-err-write-epipe-program-crashing ?

**Comment by rtardi** [comment]
> Maybe try using 'useNewWDA' capability to false , so that it won't open multiple WebDriverAgents

@sumanthmattapalli Thanks!
