### ISSUE TITLE
Safari getWindowHandles always returns 1 handle

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#11484]
## The problem

* Later versions of Appium only return 1 window handle when running a safari session, regardless of how many tabs are open
* This did not happen in older versions

## Environment

* Appium version (or git revision) that exhibits the issue: _1.9.1_
* Last Appium version that did not exhibit the issue (if applicable): _1.6.3_
* Desktop OS/version used to run Appium: _Mac_
* Node.js version (unless using Appium.app|exe): _10_
* Mobile platform/version under test: _iOS 12.0_
* Real device or emulator/simulator: _iPad Simulator_
* Appium CLI or Appium.app|exe: _CLI_

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/dpgraham/1b47a99d7875ce87d3df54ec701adabd

## Code To Reproduce Issue [ Good To Have ]

Unzip this: [window-handles.zip](https://github.com/appium/appium/files/2448005/window-handles.zip)

Run this:
```
cd window-handles
npm install -g protractor
protractor conf
```

```javascript
it('should open a new tab', function() {

  browser.driver.get('https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_link_target');

  browser.driver.sleep(5000);

  browser.driver.getAllWindowHandles().then(function(handles) {
      expect(handles.length).toBe(1);
  });

  browser.driver.findElement(by.css('a[href="https://www.w3schools.com"]')).then(function(el) {
      return el.click();
  });

  browser.driver.sleep(5000);

  browser.driver.getAllWindowHandles().then(function(handles) {
      expect(handles.length).toBe(2); // This fails. It's actually 1
  });

});
```

**Comment by mykola-mokhnach** [comment]
@dpgraham Does the fix work for you in appium@beta?

**Comment by dpgraham** [comment]
@mykola-mokhnach I'll check that today

**Comment by dpgraham** [comment]
ios-driver 2.12.0 resolves this
