### ISSUE TITLE
Error: The desired should not include both of an 'appPackage' and a 'browserName'

### ISSUE THREAD

**Issue by neerajkumar-lad** [appium/appium#11488]
## The problem

After updating appium from 1.7.1 to 1.9.1 found the "Error: The desired should not include both of an 'appPackage' and a 'browserName'" when I start my script.

## Environment

* Appium version :1.9.1
* Desktop OS/version used to run Appium: Mac High Sierra v10.13.3
* Node.js version (unless using Appium.app|exe): v8.11.3
* Mobile platform/version under test: Android v8
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI
* React Native : v57.1

## Details

I have updated appium from 1.7.1 to 1.9.1. When I started my script it shows error  "Error: The desired should not include both of an 'appPackage' and a 'browserName'"

Basically, our application was built on RN 53.0 and we upgraded to 57.1. While running already running the script on 57.1 RN version. It takes lots more time to find an element. Hence decided to upgrade it to the latest version of appium.

```
                params = new HashMap<String,String>();  
		params.put("deviceName_", "emulator-5554");
		params.put("UDID_", "emulator-5554");
		params.put("platformVersion_", "7.0.0");
		params.put("URL_", "http://127.0.0.1:4723/wd/hub");
                params.put("appUrl_", "/Users/userName/eclipse-workspace/test-mobile-test/src/test/resources/app/Android/XXXX-release.apk");
params.put("platform_", "ANDROID");

                 caps = DesiredCapabilities.android();
                 caps.setCapability(MobileCapabilityType.DEVICE_NAME, params.get("deviceName_"));
		caps.setCapability(MobileCapabilityType.PLATFORM_NAME, params.get("platform_").split("_")[0]);
		caps.setCapability(MobileCapabilityType.PLATFORM_VERSION, params.get("platformVersion_"));
		caps.setCapability("newCommandTimeout", 1500);
			File app = new File(params.get("appUrl_"));
			caps.setCapability("app", app.getAbsolutePath());
			//Fresh session
			caps.setCapability(MobileCapabilityType.NO_RESET, false);
		caps.setCapability("udid", params.get("UDID_"));
```

## Link to Appium logs

 [Appium log](https://gist.github.com/neerajkumar-lad/12d9141a38882425b8267eadbd00f36c)

**Comment by mykola-mokhnach** [comment]
Such behaviour is expected. You must remove one of these capabilities. Which one - depends on what you want to test.

Closed as not an issue
