### ISSUE TITLE
Input Text from Certain Coordinates

### ISSUE THREAD

**Issue by agilesai1294** [appium/appium#11489]
## The problem
Hi, I want to send text to an Edit Text using appium library in Robot framework. I want to write the text from a certain position. Is it possible to do that?

**Comment by mykola-mokhnach** [comment]
Please use appium forum for questions

**Comment by agilesai1294** [comment]
Where can i find the appium form?

**Comment by mykola-mokhnach** [comment]
It's stated in the issue reporting form (if anyone ever cares to read it):

> Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!
