### ISSUE TITLE
XCUIElementTypeSecureTextField is not being recognised in the popup

### ISSUE THREAD

**Issue by prakashpqa** [appium/appium#11494]
## The problem

I am not able to send keys to a "XCUIElementTypeSecureTextField" field which comes on the popup. The username is getting recognised and script is able to send the data.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium:  1.7.1
* Node.js version (unless using Appium.app|exe): 8.12.0
* Mobile platform/version under test: iPhone, iOS 12.0
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Please refer the snapshot below.

![img_8592e3b2a001-1](https://user-images.githubusercontent.com/30907200/46594947-8b2d9f80-cb08-11e8-9f19-4eef606f5690.jpg)

Using my automation scripts I am able to enter the password. But I am not able to send keys to the password field which is of type "XCUIElementTypeSecureTextField".

I tried all of finding (@Findby or driver.findbyxpath), but nothing is working and the password is being entered in the username field itself.

My developer said it is a custom overlay view.

## Link to Appium logs

https://gist.github.com/prakashpqa/7f9fa369ab89410cf86d3af88368f2ab

**Comment by mykola-mokhnach** [comment]
Is the control a part of a web view? What is visible in the page source output?

**Comment by prakashpqa** [comment]
I got to know from developer that It's a custom view looking like an alert. It's a UIView. Hope that helps.


```
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="375" height="667">
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="375" height="667">
        <XCUIElementTypeScrollView type="XCUIElementTypeScrollView" enabled="true" visible="true" x="0" y="0" width="375" height="667">
          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="375" height="667">
            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="56" y="233" width="263" height="201">
              <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="89" y="253" width="197" height="91">
                <XCUIElementTypeTextField type="XCUIElementTypeTextField" value="User name" enabled="true" visible="true" x="89" y="253" width="197" height="46"/>
                <XCUIElementTypeSecureTextField type="XCUIElementTypeSecureTextField" value="Password" enabled="true" visible="true" x="89" y="298" width="197" height="46"/>
              </XCUIElementTypeOther>
              <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="89" y="343" width="197" height="91">
                <XCUIElementTypeButton type="XCUIElementTypeButton" name="LOG IN" label="LOG IN" enabled="true" visible="true" x="89" y="373" width="99" height="31"/>
                <XCUIElementTypeButton type="XCUIElementTypeButton" name="CANCEL" label="CANCEL" enabled="true" visible="true" x="187" y="373" width="99" height="31"/>
              </XCUIElementTypeOther>
            </XCUIElementTypeOther>
          </XCUIElementTypeOther>
        </XCUIElementTypeScrollView>
      </XCUIElementTypeOther>
    </XCUIElementTypeOther>
```

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing there, which can be fixed on Appium side. Please report the issue to https://github.com/facebook/WebDriverAgent
