### ISSUE TITLE
setLocation crashes on real Android devices

### ISSUE THREAD

**Issue by juria** [appium/appium#11496]
## The problem

Since Appium 1.9.1, the tests crash when AppiumDriver.setLocation(Location location) is used with a real device. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable): 1.8.1
* Desktop OS/version used to run Appium: Windows 10 Home (Version: 1803)
* Node.js version (unless using Appium.app|exe): v8.11.1
* Mobile platform/version under test: Android 7.1.1
* Real device or emulator/simulator: Real device (Moto Z Play, Samsung Galaxy S8) - it works using the emulator (Nexus 5). 
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

[crash logs](https://gist.github.com/juria/f9842b8434275f3fc614c391aa890d7e)

**Comment by mykola-mokhnach** [comment]
try with appium@beta

**Comment by juria** [comment]
Thank you, it works with appium@1.9.2-beta.2.

**Comment by juria** [comment]
The issue is back with appium@1.10.0 (and also appium@1.11.0-beta.3). 

## The problem

Since appium@1.10.0, the tests crash when AppiumDriver.setLocation(Location location) is used with a real device. This time it works sometimes, but I couldn't find a pattern why it works sometime. I've also tried the latest beta appium@1.11.0-beta.3 and it has the same issue.

I couldn't reproduce the issue on Samsung Galaxy S4 with Android 5.0.1.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0 & 1.11.0-beta.3
* Last Appium version that did not exhibit the issue (if applicable): 1.9.2-beta.2 & 1.8.1
* Desktop OS/version used to run Appium: Windows 10 Home (Version: 1803)
* Node.js version (unless using Appium.app|exe): v8.11.1
* Mobile platform/version under test: Android 8.1.0 & 8.0.0
* Real device or emulator/simulator: Real device (Moto Z Play, Samsung Galaxy J7 - it works using the Samsung Galax S4 with Android 5.0.1). 
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

[crash logs](https://gist.github.com/juria/805d850456f36652a32518966141c1b2)

**Comment by KazuCocoa** [comment]
https://developer.android.com/about/versions/oreo/background-location-limits ?
If we call update location frequesntly, the error happenes.

To prevent the error, we probably can make the setting app foreground when the set location is called.
https://github.com/appium/io.appium.settings

**Comment by mykola-mokhnach** [comment]
@juria The issue should be fixed in appium@beta. Now Appium Settings has a foreground service, which prevents it from being blocked from location access while in background
