### ISSUE TITLE
unable to install Appium Server via cmd

### ISSUE THREAD

**Issue by NataliaPr** [appium/appium#11498]
Hi, 
I have an error when downloading Appium via cmd. I was also trying to run cmd as admin but it did not help. I copied the following paths to env. variables:
C:\Program Files\nodejs     and
C:\Program Files\nodejs\node_modules\npm\bin   (as new path) 
 Please see the logs above. Kindly asking to assist with this issue.
![cmd](https://user-images.githubusercontent.com/43983333/46653190-02693f00-cbae-11e8-9478-148a6a2ff1a3.PNG)
[2018-10-09T07_26_13_340Z-debug.log](https://github.com/appium/appium/files/2459303/2018-10-09T07_26_13_340Z-debug.log)

Thank you

**Comment by mykola-mokhnach** [comment]
I assume the error there is pretty clear. You must install python and have it in your PATH. Closed as not an issue
