### ISSUE TITLE
[iOS parallel execution]: Safari collapses when next virtual device starting

### ISSUE THREAD

**Issue by igorlantushenko** [appium/appium#11509]
## The problem

We are running tests in ios safari with virtual device emulator. 
F.e. we have 2 parallel sessions.
The first device launched and opened Safari with initial url, in the same time the second device loaded up and also opens safari. And now on the first device Safari gets collapsed like you press Home button, **BUT** test successfully continuing. When we want to take a screenshot of the first devices - there is always the Home screen. 

**How to avoid collapsing Safari on the first device when second appears?**

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Desktop OS/version used to run Appium: High Sierra 10.13.6
* Node.js version (unless using Appium.app|exe): 8.11.4
* Mobile platform/version under test: iOs, iPhone 8
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

When run in parallel every new launched device will collapse Safari on active emulators
https://www.youtube.com/watch?v=mL9x9AK6ZNU

**Comment by mykola-mokhnach** [comment]
Please attach full server logs

**Comment by igorlantushenko** [comment]
@mykola-mokhnach  updated

**Comment by mykola-mokhnach** [comment]
As a quick workaround you might try to use `activeApp` helper to restore Safari

**Comment by igorlantushenko** [comment]
thanks, will try

**Comment by mykola-mokhnach** [comment]
Closed as inactive
