### ISSUE TITLE
add flag to avoid getting git rev

### ISSUE THREAD

**Issue by kazzmir** [appium/appium#11504]
## The problem

Appium sends a request to api.github.com to get the git rev, which ends up in the `config.BUILD_INFO` variable. These requests cause issues in my environment such as:
  * timeout errors from certain networks that cannot reach the github ip
  * api rate limiting enforced by github

As far as I can tell the relevant call graph is

`AppiumDriver::constructor -> config.updateBuildInfo() -> config.getGitRev()`

Could a flag be added to disable the github api check?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: linux
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

**Comment by imurchie** [comment]
I personally would prefer all that code to be pulled out entirely. The revision adds no information on released versions of Appium, if the release was performed correctly. Appium run from source needs the revision sha in order to identify the code the server is running.

**Comment by mykola-mokhnach** [comment]
The fix has been merged and will be published in appium@beta.3
