### ISSUE TITLE
Appium 1.9.1 server is not able to find the some elements  in IOS11.4  but finds in IOS10.4

### ISSUE THREAD

**Issue by SanjayDhami** [appium/appium#11505]
I was using appium 1.8 with xcode 9.4 before and tests were working fine, once i updated to appium 1.9.1 and xcode 10, i see that appium is not able to see the some of ui buttons. i did driver.getSource() and even i cannot see UIButton in source but it does showed in previous version( same version of app). is there something i can get help on this.

I have attached the screenshot of element that  i am looking for in Appium inspector [Version 1.7.1 (1.7.1.20180926.9)[
<img width="1359" alt="screen shot 2018-10-09 at 1 16 33 pm" src="https://user-images.githubusercontent.com/28166259/46689972-c2628600-cbc6-11e8-9be6-17d9bb3ee947.png">
Actually i am looking for **type="XCUIElementTypeButton" name="foursquare calculator"** 
which i can see in Appium inspector and device with IOS10.3 but not in device with IOS11.4
Also i have attached the snippet source DOM structure at that point in both version of IOS.
Even source tree looks does not match for the same version of app.

[IOS10.3.txt](https://github.com/appium/appium/files/2461739/IOS10.3.txt)
[IOS_11.4.1.txt](https://github.com/appium/appium/files/2461740/IOS_11.4.1.txt)

Please help.

And i think log will not provide much value in this case.

**Comment by mykola-mokhnach** [comment]
The actual page source is generated by WebDriverAgent and XCTest and there is nothing that can be done on Appium side. Please report the problem to https://github.com/facebook/WebDriverAgent
