### ISSUE TITLE
Can't skip xcode version check even though webDriverAgentUrl is set

### ISSUE THREAD

**Issue by umutuzgur** [appium/appium#11508]
## The problem

Appium is still checking for xcode version even though webDriverAgentUrl is supplied

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0, 1.8.1, 1.9.1
* Node.js version (unless using Appium.app|exe): node 8
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: real device

## Code To Reproduce Issue [ Good To Have ]

The reason is basically the https://github.com/appium/appium-xcuitest-driver/blob/master/lib/driver.js#L254. This check is always true due to opts.realDevice being set at line https://github.com/appium/appium-xcuitest-driver/blob/master/lib/driver.js#L266. Therefore, the opts.realDevice is always null or false at the if check. I managed to pass that by supplying realDevice=true in my desired capabilities but this is a hack since appium doesn't recognise the capability and you can see it in the appium logs that it is not recognised

**Comment by mykola-mokhnach** [comment]
The fix has been published in appium@beta
