### ISSUE TITLE
Incorrect iOS coordinates for webview elements

### ISSUE THREAD

**Issue by LyubomirStoimchev** [appium/appium#11502]
## The problem

Elements in webview have incorrect coordinates. When you switch to webview context, then Appium disregards the native parts in the screen and acts like the webview takes the entire screen. If you have a native header and try to click on an element in the webview then nothing happens because the element has incorrect coordinates.

Getting screen size when in native context: {Width = 375 Height = 667}
Getting screen size when in webview context: {Width = 375 Height = 553}

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1, 1.9.0, 1.9.1, 1.9.2@beta-2
* Desktop OS/version used to run Appium: 1.6.3, 1.7.0, 1.7.1
* Mobile platform/version under test: iOS 11.4, iOS 12.0
* Real device or emulator/simulator: simulator

**Comment by mykola-mokhnach** [comment]
The actual element coordinates are returned by XCTest and is not controlled by us. This is one of the reasons not to interact with web views being in native context.

This is also the reason why Appium has the nativeWebTap capability (and why this capability implementation is so flaky). You can read https://appiumpro.com/editions/36 to get more details on this topic.

Closed as third party issue.

**Comment by LyubomirStoimchev** [comment]
Hi,
Thanks for the reply. I actually tried that capability l, but sometimes it works and sometimes it doesn't.

**Comment by mykola-mokhnach** [comment]
There are many corner cases, which are hardly possible to cover. You are always welcome to improve the logic there.
