### ISSUE TITLE
iOS Tap is not working 

### ISSUE THREAD

**Issue by aryalakshmi** [appium/appium#11511]
## The problem

Tap action is not working in iOS

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.2-beta
* Last Appium version that did not exhibit the issue (if applicable): Never worked before
* Desktop OS/version used to run Appium: NA
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium Cli 

## Details

Tap action in appium is returning with unknown error

## Link to Appium logs

[debug] [W3C] Calling AppiumDriver.findElements() with args: ["css selector","div#homepagecircleholder","9da67bec-ee59-4b11-868f-f7199979e0b6"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [RemoteDebugger] Executing 'find_elements' atom in default context
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var k=this;functi...
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"expression":"(function(){return function(){var k=this;functi...
[debug] [RemoteDebugger] Webkit response timeout: 180000
[debug] [RemoteDebugger] Receiving WebKit data: '{"result":{"result":{"type":"string","value":"{\"status\":0,\"value\":[{\"ELEMENT\":\":wdc:1539245118046\"}]}"},"wasThrown":false},"id":25}'
[debug] [RemoteDebugger] Found handler for message '25'
[debug] [RemoteDebugger] Received result for atom 'find_elements' execution: [{"ELEMENT":":wdc:1539245118046"}]
[debug] [MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"5010"}]
[HTTP] <-- POST /wd/hub/session/9da67bec-ee59-4b11-868f-f7199979e0b6/elements 200 29 ms - 92
[HTTP] 
[HTTP] --> POST /wd/hub/session/9da67bec-ee59-4b11-868f-f7199979e0b6/elements
[HTTP] {"using":"css selector","sessionId":"9da67bec-ee59-4b11-868f-f7199979e0b6","value":".dropdown-arrow"}
[debug] [W3C] Calling AppiumDriver.findElements() with args: ["css selector",".dropdown-arrow","9da67bec-ee59-4b11-868f-f7199979e0b6"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [RemoteDebugger] Executing 'find_elements' atom in default context
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var k=this;functi...
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"expression":"(function(){return function(){var k=this;functi...
[debug] [RemoteDebugger] Webkit response timeout: 180000
[debug] [RemoteDebugger] Receiving WebKit data: '{"result":{"result":{"type":"string","value":"{\"status\":0,\"value\":[{\"ELEMENT\":\":wdc:1539245118047\"}]}"},"wasThrown":false},"id":26}'
[debug] [RemoteDebugger] Found handler for message '26'
[debug] [RemoteDebugger] Received result for atom 'find_elements' execution: [{"ELEMENT":":wdc:1539245118047"}]
[debug] [MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"5011"}]
[HTTP] <-- POST /wd/hub/session/9da67bec-ee59-4b11-868f-f7199979e0b6/elements 200 23 ms - 92
[HTTP] 
[HTTP] --> POST /wd/hub/session/9da67bec-ee59-4b11-868f-f7199979e0b6/touch/perform
[HTTP] {"sessionId":"9da67bec-ee59-4b11-868f-f7199979e0b6","actions":[{"action":"tap","options":{"y":"55","x":"169","count":1,"element":"5011"}}]}
[debug] [W3C] Calling AppiumDriver.performTouch() with args: [[{"action":"tap","options":{"y":"55","x":"169","count":1,"element":"5011"}}],"9da67bec-ee59-4b11-868f-f7199979e0b6"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: tap(options={"y":"55","x":"169","count":1,"element":"5011"})
[debug] [JSONWP Proxy] Proxying [POST /wda/touch/perform] to [POST http://localhost:8100/session/9DB90463-DBCA-4A13-8B0B-FB97DBAFB641/wda/touch/perform] with body: {"actions":[{"action":"tap","options":{"y":"55","x":"169","count":1,"element":"5011"}}]}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"-[NSTaggedPointerString fb_lastSnapshot]: unrecognized selector sent to instance 0xa000000313130354\n\n(\n\t0   CoreFoundation                      0x000000018137eda4 <redacted> + 252\n\t1   libobjc.A.dylib                     0x00000001805385ec objc_exception_throw + 56\n\t2   CoreFoundation                      0x000000018138c098 <redacted> + 0\n\t3   CoreFoundation                      0x00000001813845c8 <redacted> + 1380\n\t4   CoreFoundation                      0x000000018126a41c _CF_forwarding_prep_0 + 92\n\t5   WebDriverAgentLib                   0x0000000104ab1f00 -[FBBaseGestureItem hitpointWithElement:positionOffset:error:] + 508\n\t6   WebDriverAgentLib                   0x0000000104a93800 -[FBAppiumGestureItem coordinatesWithOptions:error:] + 1248\n\t7   WebDriverAgentLib                   0x0000000104a92e64 -[FBAppiumGestureItem initWithActionItem:application:atPosition:offset:error:] + 472\n\t8   WebDriverAgentLib                   0x0000000104a95e94 -[FBAppiumActionsSynthesizer ev...
[MJSONWP] Encountered internal error running command: Error: An unknown server-side error occurred while processing the command.
[MJSONWP]     at JWProxy.command$ (/Users/digitalhome/.npm-packages/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:176:15)
[MJSONWP]     at tryCatch (/Users/digitalhome/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/digitalhome/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/digitalhome/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (/Users/digitalhome/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session/9da67bec-ee59-4b11-868f-f7199979e0b6/touch/perform 500 44 ms - 238

## Code To Reproduce Issue [ Good To Have ]

Tap	css=.dropdown-arrow	169	55

**Comment by mykola-mokhnach** [comment]
This behaviour is expected. You must be in native context in order to perform touch actions

**Comment by aryalakshmi** [comment]
So what about tap performed in webview? isnt that supported in appium?

**Comment by mykola-mokhnach** [comment]
Tap by coordinates is only supported in native context

**Comment by mykola-mokhnach** [comment]
you could use executeScript being in web context to trigger click (or any other) events by particular coordinates manually

**Comment by aryalakshmi** [comment]
HI,
 Javascript doesnt accept tap() as it is for the webelement. It says undefined methos tap when trying to execute javascript

**Comment by aryalakshmi** [comment]
Hi,

I have written a javascript code to execute in appium and it works fine if i use a click action as in below example as "document.querySelectorAll('selector')[0].click(); 
But, When i use tap action for another element as "document.querySelectorAll('selector')[0].tap(); --> It says tap is undefined. Even if i give this in my chrome console , i am not able to find any TAP event there.

**Comment by KazuCocoa** [comment]
using appium forum (for questions) or create another issue with logs is pretty good
