### ISSUE TITLE
Extra browser capability appears and session cannot be created

### ISSUE THREAD

**Issue by vjmaiky** [appium/appium#11514]
## The problem
I'm trying to start appium desktop for an android device using capabilities and appium desktop:
{
  "platformName": "android",
  "platformVersion": "7",
  "deviceName": "Nexus 7",
  "app": "C:\\automation\\test.apk",
  "automationName": "UiAutomator2",
  "udid": "a350b460"
}

and i get 
[BaseDriver] SessionNotCreatedError: A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s): 'deviceName' can't be blank

In logs i can see that some capabilities are put by default, especially:
[Appium] browserName: firefox 
which can be the source of the problem.

Did something changed in latest version?

## Environment
Windows x64, Latest Appium Desktop, Android 7, Real Device

## Link to Appium logs
https://gist.github.com/vjmaiky/0e2109d830d2fbb0f9eaf4251500b3d9

**Comment by mykola-mokhnach** [comment]
Make sure you use the most recent client version

**Comment by vjmaiky** [comment]
1.7.1 --> appium-desktop-setup-1.7.1.exe
124 MB

**Comment by mykola-mokhnach** [comment]
again, we are talking about the CLIENT

**Comment by vjmaiky** [comment]
Version 1.7.1 i meant
https://github.com/appium/appium-desktop/releases/tag/v1.7.1

**Comment by vjmaiky** [comment]
i don;t see how to manipulate appium java client when you;re installing the desktop appium version for inspectiv the app on devices...isn't built inside of appium desktop?

**Comment by mykola-mokhnach** [comment]
Appium desktop uses WD as the default client. There is a known bug there about it does not work properly with W3C https://github.com/appium/appium/issues/10682

Should the issue be reported to Appium Desktop issues tracker instead?

**Comment by vjmaiky** [comment]
ok i'll move the thread there. thanks
