### ISSUE TITLE
Automation is too slow on iOS 12 devices

### ISSUE THREAD

**Issue by shivakrishnach31** [appium/appium#11512]
## The problem

Automation scripts execution starting in regular speed but getting slower and slower after running several scripts. I run scripts on audio playing app, in first script playback slider moves smoothly but in 12th or 13th script playback sliders position jerks not moves smoothly due to slowness.
When I try the same scenarios manually, app working perfectly. But in automation I am facing this issue every-time. 
Initially I thought it was an issue with the app on iOS 12 but app working fine on iOS 11.4, 11.4.1 and 12 when I tried manually. I am not sure what is problem for this slowness but my scripts are taking double the time what they usually take.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable): 1.9.1
* Desktop OS/version used to run Appium: Mac High Sierra 10.13.6
* Node.js version (unless using Appium.app|exe): 7.1.0
* Mobile platform/version under test: iOS 12 and 12.0.1
* Real device or emulator/simulator: Real Device iPhone 7
* Appium CLI or Appium.app|exe: Appium CLI

**Comment by mykola-mokhnach** [comment]
The term "slow" provides no any useful context to us.

What exactly is slow? How slow it is in comparison to the "ideal" case? Did you try to investigate/compare server and device logs?

**Comment by shivakrishnach31** [comment]
Hi @mykola-mokhnach My complete suite is taking 45 minutes to iOS 11.4.1 devices and ~125 minutes in iOS 12 devices. 
I don't know how to compare server and device logs. If you help me how to do that, I will do and provide you more details. Thanks.

**Comment by mykola-mokhnach** [comment]
You can enable timestamps in server logs, run the tests on both platforms and compare the timestamps for the same operations to figure out which particular operation requires more time.

**Comment by mykola-mokhnach** [comment]
Also @jlipps has a nice set of articles about general tests designing principles: https://appiumpro.com/editions/19

**Comment by shivakrishnach31** [comment]
Hi @mykola-mokhnach - I have investigated the problem. When the playback slider is moving, if script tries to tap on next and previous buttons, it is not able to tap immediately as the slider is moving. Taking some extra time to tap/access other elements on screen when something is in progress. In my app, we starts recording after than timestamp starts. As the timestamp keeps updating accessing other elements on the same screen taking longer time unlike in iOS 11.4.1 devices.

**Comment by mykola-mokhnach** [comment]
Try to avoid having active background animations while performing accessibility actions in general. I don't think there is something that can be done on appium side here, because elements lookup and interaction is done by XCTest.

**Comment by shivakrishnach31** [comment]
My automation scripts whole point is to test how the application is working in background and while something is running(interruptions). 

Will logging a bug for appium-xcuitest-driver help?

**Comment by mykola-mokhnach** [comment]
No it won't help. Consider logging a bug to Apple
