### ISSUE TITLE
iOS Real Device - [Hybrid App] Inspector Recording Generate Script?

### ISSUE THREAD

**Issue by AsteaDevelopment** [appium/appium#11518]
I can't seem to find this answer anywhere, but is it possible to tap on an element on a real iOS device and the script is generated when recording in the appium inspector? Our app was built using cordova so it is a HYBRID app. I can only seem to get it working when clicking an element in the screenshot and sending an action...

Do we have to add any specific code to make this work? I have the iOS Proxy Debugger connected and working...

Maybe I am missing a step or am just confused on the product. Please let me know.

Thank you.

**Comment by mykola-mokhnach** [comment]
It is necessary to switch from native to WEBIEW context when automating hybrid apps. Appium inspector does not support switching the context and inspecting apps in web context. For that purpose you must use the remote Safari debugger.
