### ISSUE TITLE
Inspector Crashes Appium Desktop v 1.9.1

### ISSUE THREAD

**Issue by rcuyugan** [appium/appium#11519]
## The problem

The appium desktop inspector crashes. This happens when aatached to an existing session. 

## Environment
Mac OS High Sierra
Appium 1.9.1
Appium Server 1.7.1

This was also happening on version 1.8 but a workaround was applied by adding capabilities.setCapability("forceMjsonwp", true);

Now even with that workaround enabled, the inspector still crashes and closes out server when inspecting.

Steps to repro:
Open the inspector
Attach to an existing session
Inspect
Appium crashes and closes

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/appium/appium-desktop
