### ISSUE TITLE
Mobile Safari tests stuck after loading page

### ISSUE THREAD

**Issue by lukasz-burak** [appium/appium#11522]
## The problem

I'm experiencing a problem with mobile Safari tests. I’m able to boot iOS simulator, Safari is opening, the page that tests are supposed to execute on is loaded but after that it stuck, nothing happen until timeout is recieved.

I have no ideat whether  I’m doing something wrong or it’s the issue with appium/my environment (I’m using MacOSX 10.14 Mojave, maybe it’s the problem)

## Environment

* Appium version: 1.9.1 
* Mac OSX 10.14 Mojave
* Node.js version: v10.11.0
* Mobile platform/version under test: iOS 11.4 (I've tested also with iOS 12 with same result)
* simulator: iPhone 7 (tested with 8, X as well)
* Appium CLI

## Link to Appium logs

Appium logs: [appium.log]([appium.log · GitHub](https://gist.github.com/lukasz-burak/b3e3776f02a24a594afe15b09fc66eec))

## Code To Reproduce Issue

Protractor config file I use:

```
 exports.config = {
  seleniumAddress: 'http://localhost:4723/wd/hub',
  specs: [
    'example_spec.js'
  ],

  capabilities: {
    browserName: 'Safari',
    platformName: 'iOS',
    platformVersion: '11.4',
    deviceName: 'iPhone 7'
  }
};
 ```

Test I use (very simple yet still does not work):

```
describe('Protractor Demo App', function() {
  it('should have a title', function() {
    browser.get('https://angular.io/');

    expect(browser.getTitle()).toEqual('Angular');
  });
});
```

Protractor output:
```
lukaszburak:e2e lukasz.burak$ protractor conf.js 
[13:56:35] I/launcher - Running 1 instances of WebDriver
[13:56:35] I/hosted - Using the selenium server at http://localhost:4723/wd/hub
Started
FA Jasmine spec timed out. Resetting the WebDriver Control Flow.
A Jasmine spec timed out. Resetting the WebDriver Control Flow.


Failures:
1) Protractor Demo App should have a title
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at ontimeout (timers.js:425:11)
        at tryOnTimeout (timers.js:289:5)
        at listOnTimeout (timers.js:252:5)
        at Timer.processTimers (timers.js:212:10)
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at ontimeout (timers.js:425:11)
        at tryOnTimeout (timers.js:289:5)
        at listOnTimeout (timers.js:252:5)
        at Timer.processTimers (timers.js:212:10)

1 spec, 1 failure
Finished in 60.018 seconds

[13:58:01] I/launcher - 0 instance(s) of WebDriver still running
[13:58:01] I/launcher - Safari #01 failed 1 test(s)
[13:58:01] I/launcher - overall: 1 failed spec(s)
[13:58:01] E/launcher - Process exited with error code 1
```

**Comment by mykola-mokhnach** [comment]
I don't observe any issues in the attached logs. You could also try appium@beta. Perhaps it works better.

**Comment by lukasz-burak** [comment]
I've tested it against appium@beta, same issue.
I've updated issue description with protractor output.

**Comment by imurchie** [comment]
I think the main problem is that Appium has no idea what is going on when everything is done by injecting JavaScript. It keeps track of windows and what is going on when using the API built for this, but when everything is changed underneath all bets are off.

**Comment by lukasz-burak** [comment]
@imurchie I followed your suggestion and used Java client for Appium and it worked like a charm.

It means that Appium is not a problem here as I initially thought it's rather Protractor that has some issues with working properly with Appium.
I believe this issue can be closed, thanks for your help.
