### ISSUE TITLE
WebDriverAgent-MJPEG server cannot start because the current iOS version is not supoprted

### ISSUE THREAD

**Issue by chenchengyuan** [appium/appium#11521]
## The problem
git clone https://github.com/appium/WebDriverAgent.git
then xcode build the project

error log:
```
Runner[2054:376229] ServerURLHere->http://192.168.3.63:8100<-ServerURLHere
2018-10-12 15:54:57.673430+0800 WebDriverAgentRunner-Runner[2054:376229] Using singleton test manager
2018-10-12 15:54:57.673589+0800 WebDriverAgentRunner-Runner[2054:376229] MJPEG server cannot start because the current iOS version is not supoprted
MJPEG server cannot start because the current iOS version is not supoprted.
```
When I get the url(http://192.168.3.63:8100/status), it has no response.
## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: osx 10.13.6
* Node.js version (unless using Appium.app|exe): v8.12.0
* Mobile platform/version under test: ios 10.3.3 error  (but ios 12.0.1 is ok)
**I also try the project from https://github.com/facebook/WebDriverAgent.git, ios 10.3.3 ok, 
ios 12.0.1 error same as the issue https://github.com/facebook/WebDriverAgent/issues/991**
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe:  Xcode.app

**Comment by mykola-mokhnach** [comment]
This is expected. Xcode8 SDK has been dropped in the recent beta

**Comment by chenchengyuan** [comment]
ok, thanks.

**Comment by zyeungcsuf** [comment]
@mykola-mokhnach I'm also facing the same issue. Which Appium release(s) are compatible with older iOS versions (specifically iOS 9.3.5)? I would like to automate tests for a range of iOS versions, but I'm only able to get it working for iOS 12.0

**Comment by mykola-mokhnach** [comment]
Try to use older appium releases

**Comment by codeskyblue** [comment]
What is the miminum supported version if I want to use MJPEG-Server. Thanks.
