### ISSUE TITLE
Session startup times (uiautomator/uiautomator2)

### ISSUE THREAD

**Issue by yahman72** [appium/appium#11527]
## The problem

The session creation takes too long and contains steps that are not always needed.
**Improvement idea: it would be good to have capabilities (or other ways) to skip certain steps/checks during session creation.**

I have a lot of test cases where I start a session (~200 sessions per test suite/run) do something simple with an app and then close it again --> the execution logs show that ~30% of the execution time is spent in waiting for the session to be created.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.7.2 & v1.9.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): v8.12.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real Device - Samsung S7 (Android 7.0)
* Appium CLI or Appium.app|exe: 

## Details
Here some examples from the session setup times
- appium v1.7.2 + uiautomator2: session creation 16:53:15:771-16:53:35:005 **~20 seconds**
- appium v1.7.2 + uiautomator: session creation 17:07:50:162-17:08:02:781 **~12 seconds**
- appium v1.9.0 + uiautomator: session creation 17:09:55:056-17:10:02:939 **~9 seconds**
- appium v1.9.0 + uiautomator2:  uiautomator2 crashes (see #11528)

For example: that uiautomator2 session creation and 200 session creations in a Test Suite --> we spend _more than 1 hour_ waiting for sessions to be created.

Looking at the logs, there are quite a lot of steps that are IMHO most of the times obsolete, e.g.
- it's not necessary to check the existence of the "io.appium.*" packages
- it's not necessary to check the versions of the "io.appium.*" packages
- it's not necessary to check the API level, manufacturer and model

These checks take ~5 seconds on every session creation = remove them and we have saved 15 mins of execution time (200x5sec) 

Sure those checks are needed in general, but I know what packages and what versions are on my devices i.e. it would be good have capabilities to skip/override those checks. 

Especially the uiautomator2 steps seem to be slow (8-10s per session), because the uiautomator-server is first stopped and then started again. Here it would also be good to use the uiautomator2-server without restart = would save another (200x8s) ~25mins of execution time.

## Link to Appium logs
Various Scenarios: 
- session: appium v1.7.2 + uiautomator2 (https://gist.github.com/yahman72/0d4f325dcac9c7d81c098a024c9f93b5)
- session: appium v1.7.2 + uiautomator (https://gist.github.com/yahman72/2810eedefd6890cc6bc016812b3c6d9f)
- session: appium v1.9.0 + uiautomator (https://gist.github.com/yahman72/c7e6d114caa0e999f1bec2a5a350ed0c)
- session: appium v1.9.0 + uiautomator2: CRASH - different issue: #11528 (https://gist.github.com/yahman72/9ff1de5c72b59a3c1b9541e96d8547bb)

## Code To Reproduce Issue [ Good To Have ]
DC's for uiautomator2
```
dc_s7a7_smsr = {
    'automationName': 'uiautomator2',
    'udid': u'ce10171a6078523a03',
    'deviceName': u'Dummy',
    'appPackage': 'com.samsung.android.messaging',
    'appActivity': 'com.android.mms.ui.ConversationComposer',
    'platformName': 'Android',
    'noReset': True,
    'dontStopAppOnReset': False,
    'optionalIntentArguments': "-W",
    'skipUnlock': True,
    }
```
DC's for uiautomator
```
dc_s7a7_smsr = {
    'udid': u'ce10171a6078523a03',
    'deviceName': u'Dummy',
    'appPackage': 'com.samsung.android.messaging',
    'appActivity': 'com.android.mms.ui.ConversationComposer',
    'platformName': 'Android',
    'noReset': True,
    'dontStopAppOnReset': False,
    'optionalIntentArguments': "-W",
    'skipUnlock': True,
    }
```

Create Session:
```
from appium import webdriver as appium_webdriver
appium_webdriver.Remote('http://localhost:4723/wd/hub', dc_s7a7_smsr)
```

**Comment by mykola-mokhnach** [comment]
This has been already optimised in appium@beta

**Comment by yahman72** [comment]
what is optimised?
- io.appium.* package handling/checking
- uiautomator2 (re)starting
- both

**Comment by mykola-mokhnach** [comment]
both

**Comment by yahman72** [comment]
excellent! ... and thanks for the prompt replies
