### ISSUE TITLE
Appium not selecting correct device

### ISSUE THREAD

**Issue by kalibu02** [appium/appium#11534]
## The problem

Appium is not selecting the correct device when multiple real devices are connected.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Desktop OS/version used to run Appium: Ubuntu
* Node.js version (unless using Appium.app|exe): v6.9.2
* Mobile platform/version under test: ANDROID
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If 2 devices with android version 5.1 (device name = TNM9XA1641500285) and 5.1.1 (device name = 210118214937834a) are connected. When trying to run Appium with capabilities: platformName: android, appActivity: test.xx, RemoteAdbHost: 172.16.60.55, automationName: UiAutomator2, deviceName: TNM9XA1641500285, platformVersion: 5.1, appPackage: com.test.xx, systemPort: 8200 it was observed that Appium use the wrong device (see logs)

## Link to Appium logs

https://gist.github.com/kalibu02/614ac735b8cf36a12b180a229e92a3b1

**Comment by mykola-mokhnach** [comment]
What if you skip platformVersion cap?

**Comment by kalibu02** [comment]
Same problem. I have found a solution. If I add capability udid=TNM9XA1641500285 the correct device will be selected.

**Comment by imurchie** [comment]
Appium uses the `platformVersion` to select the device, and pretty much ignored `deviceName`. @kalibu02 is correct, the `udid`, not the `deviceName`, will give access to a selecting a specific device.

**Comment by kalibu02** [comment]
Thanks. I will close the issue.

**Comment by malavparekh** [comment]
Could you tell me how to handle this specific scenario. 

I have multiple builds running in parallel with the same configuration. I don't want to pass any device specific information in the capability but only want to pass general information that is common in both builds.

In my setup I have a selenium grid hub (2.53) and 2 appium nodes (1.13.0) reporting to the same grid hub.
Both nodes are iOS 12.2 with name - iPhone 7. 

Here's how I expect my capabilities to look like-
        capabilities = DesiredCapabilities.safari();
        capabilities.setCapability("platformName", "iOS");
        capabilities.setCapability("platformVersion", "12.2");
        capabilities.setCapability("deviceName", "iPhone 7");
        capabilities.setCapability("automationName", "XCUITest");        
        capabilities.setCapability("browserName", "Safari");
I don't want to pass any device specific info like udid or device name (if unique). I expect the grid to pick up any device that has this configuration.

Here's my node config for appium

"deviceName":"iPhone 7",
"browserName": "Safari",
"version":"12.2",
"maxInstances": 1,
"automationName": "XCUITest",
"platform":"MAC"

In this case it so happens that even if I have 2 iPhone simulators running with the name iPhone 7, only the one of the iPhone simulators gets used. 

If I pass unique udid to both builds running in parallel, it works ok.
