### ISSUE TITLE
Appium with UiAutomator2 returns a different DOM than UiAutomatorViewer

### ISSUE THREAD

**Issue by liviudanu-ellation** [appium/appium#11539]
## The problem

Inspecting a Activity via UiAutomator2 returns all available elements. Inspecting it with appium desktop using UiAutomator2 as automationName does not return all the elements

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1, 1.9.2.beta.2
* Last Appium version that did not exhibit the issue (if applicable): none
* Desktop OS/version used to run Appium: MacOS Sierra
* Node.js version (unless using Appium.app|exe): v8.9.3
* Mobile platform/version under test: Android
* Real device or emulator/simulator: both
* Appium CLI or Appium.app|exe: both

## Link to Appium logs

Not needed

## Note
ignoreUninmportantViews is set to false

## Please see the attached screenshots
![screen shot 2018-10-17 at 12 43 55 pm](https://user-images.githubusercontent.com/31648187/47078523-28c15700-d20c-11e8-8f51-9aa1532da42c.png)
<img width="914" alt="screen shot 2018-10-17 at 12 56 10 pm" src="https://user-images.githubusercontent.com/31648187/47078542-2fe86500-d20c-11e8-8b73-7a43fad011be.png">

**Comment by mykola-mokhnach** [comment]
What is in getPageSource output there?

**Comment by mykola-mokhnach** [comment]
I don't think there is something, that can be fixed there on uia2 server side. You could try to debug and improve that code yourself though:

https://github.com/appium/appium-uiautomator2-server/blob/master/app/src/main/java/io/appium/uiautomator2/handler/Source.java
