### ISSUE TITLE
Python+IOS+appium,tab() of appium is wrong

### ISSUE THREAD

**Issue by sandy533hs** [appium/appium#11537]
## The problem

Python+IOS+appium, 
TouchAction(driver).tap(x,y).perform();
tab() of appium is wrong，

## Environment

* Appium version (or git revision) that exhibits the issue:1.9.1
* Last Appium version that did not exhibit the issue (if applicable):1.6.4
* Desktop OS/version used to run Appium:Mac 10.13.6 (17G65)/Xcode 10.0
* Node.js version (unless using Appium.app|exe):8.12.0
* Mobile platform/version under test:IOS12
* Real device or emulator/simulator:Real Device
* Appium CLI or Appium.app|exe:Appium CLI

## Details

IDE log:
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Unhandled endpoint: /session/4AA13824-D62D-4659-B1A5-CEB7DD76A187/wda/touch/perform -- http://localhost:8100/ with parameters {
    wildcards =     (
        "session/4AA13824-D62D-4659-B1A5-CEB7DD76A187/wda/touch/perform"
    );
}

Appium log:
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Unhandled endpoint: /session/4AA13824-D62D-4659-B1A5-CEB7DD76A187/wda/touch/perform -- http://localhost:8100/ with parameters {
    wildcards =     (
        "session/4AA13824-D62D-4659-B1A5-CEB7DD76A187/wda/touch/perform"
    );
}

anwser of other people：
After I upgrade to Xcode 10, even click method is working for me.
I am using touchAction as:
TouchAction(driver).tap(point(x, y)).perform()

but i use Python, appium-python-client is 0.28, python not have “TouchAction(driver).tap(point(x, y)).perform()”，i want to use tap() and sending absolute coordinates only, 

please help me, thanks!

**Comment by mykola-mokhnach** [comment]
Make sure you have the correct WDA version on the device under test built from Appium's fork: https://github.com/appium/WebDriverAgent

Closed as not an issue.
