### ISSUE TITLE
[Intermittent]: Unable to start appium 1.9.1. 

### ISSUE THREAD

**Issue by afatima28** [appium/appium#11532]
## The problem

[Intermittent]: Unable to start appium 1.9.1. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable): 1.8.x
* Desktop OS/version used to run Appium: MAC OS
* Node.js version (unless using Appium.app|exe): v8.11.1
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: issue happening on both

## Details

When trying to run Appium (either through terminal or through app), I'm getting this error-

[Appium] Cannot retrieve git revision for Appium version 1.9.1 from GitHub. Original error: 403 - "{\"message\":\"API rate limit exceeded for <IP>. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)\",\"documentation_url\":\"https://developer.github.com/v3/#rate-limiting\"}"

**Comment by mykola-mokhnach** [comment]
This is just a log message. It should not prevent the server to start.

**Comment by afatima28** [comment]
Thanks for your reply. You're right. Server is running fine but when I'm triggering my test scripts, it is throwing this error- Unable to bind <udid> on port 27753-27753 post which test script exits.

I've checked the said port, no other process is using it.

Can anyone suggest anything that might help?

**Comment by mykola-mokhnach** [comment]
I cannot say anything without having the full log

**Comment by afatima28** [comment]
The server is running

[Appium] Welcome to Appium v1.9.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"udid":"81ab1752c488e1e1e1ff8b0ca9f8e016357d1a46","deviceName":"User's iPad","platformVersion":"11.4.1","platformName":"iOS","xcodeOrgId":"ABCD","xcodeSigningId":"iPhone Developer","startIWDP":true,"app":"com.company.product.enterprise"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"udid":"81ab1752c488e1e1e1ff8b0ca9f8e016357d1a46","deviceName":"User's iPad","platformVersion":"11.4.1","platformName":"iOS","xcodeOrgId":"ABCD","xcodeSigningId":"iPhone Developer","startIWDP":true,"app":"com.company.product.enterprise"},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1539703800157 (21:00:00 GMT+0530 (IST))
[Appium] Requested iOS support with version >= 10, using 'XCUITest' driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver (v2.94.2) session
[Appium] Capabilities:
[Appium]   udid: 81ab1752c488e1e1e1ff8b0ca9f8e016357d1a46
[Appium]   deviceName: User's iPad
[Appium]   platformVersion: 11.4.1
[Appium]   platformName: iOS
[Appium]   xcodeOrgId: ABCD
[Appium]   xcodeSigningId: iPhone Developer
[Appium]   startIWDP: true
[Appium]   app: com.company.product.enterprise
[BaseDriver] Creating session with MJSONWP desired capabilities: {"udid":"81ab1752c488e1e1e1...
[BaseDriver] Session created with session id: 5e629140-5b0c-48bb-bb18-a97f4e4f7895
[XCUITest] Current user: 'username'
[XCUITest] Xcode version set to '10.0' (tools v10.0.0.0.1.1535735448)
[XCUITest] iOS SDK Version set to '12.0'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1539703800336 (21:00:00 GMT+0530 (IST))
[XCUITest] Available devices: 81ab1752c488e1e1e1ff8b0ca9f8e016357d1a46
[XCUITest] Creating iDevice object with udid '81ab1752c488e1e1e1ff8b0ca9f8e016357d1a46'
[XCUITest] Determining device to run tests on: udid: '81ab1752c488e1e1e1ff8b0ca9f8e016357d1a46', real device: true
[XCUITest] App is an iOS bundle, will attempt to run as pre-existing
[BaseDriver] Event 'appConfigured' logged at 1539703800588 (21:00:00 GMT+0530 (IST))
[BaseDriver] Event 'resetStarted' logged at 1539703800588 (21:00:00 GMT+0530 (IST))
[XCUITest] Reset: running ios real device reset flow
[BaseDriver] Event 'resetComplete' logged at 1539703800589 (21:00:00 GMT+0530 (IST))
[iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[iOSLog] Starting iOS device log capture with: 'idevicesyslog'
[BaseDriver] Event 'logCaptureStarted' logged at 1539703800778 (21:00:00 GMT+0530 (IST))
[XCUITest] Setting up real device
[XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[JSONWP Proxy] Matched '/status' to command name 'getStatus'
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] WDA is not listening at 'http://localhost:8100/'
[XCUITest] WDA is currently not running. There is nothing to cache
[XCUITest] Trying to start WebDriverAgent 1 times with 10000ms interval
[BaseDriver] Event 'wdaStartAttempted' logged at 1539703801236 (21:00:01 GMT+0530 (IST))
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Killing running processes 'xcodebuild.*81ab1752c488e1e1e1ff8b0ca9f8e016357d1a46, iproxy 8100' for the device 81ab1752c488e1e1e1ff8b0ca9f8e016357d1a46...
[XCUITest] 'pgrep -nif xcodebuild.*81ab1752c488e1e1e1ff8b0ca9f8e016357d1a46' didn't detect any matching processes. Return code: 1
[XCUITest] 'pgrep -nif iproxy 8100' didn't detect any matching processes. Return code: 1
[XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB for the device 81ab1752c488e1e1e1ff8b0ca9f8e016357d1a46
[XCUITest] Generating xcode config file for orgId 'ABCD' and signingId 'iPhone Developer'
[XCUITest] Writing xcode config file to /var/folders/wt/mv316j8j5ksdk5wfdbz_l9th0000gp/T/2018916-4338-kobc5n.rw8ic/appium-temp.xcconfig
[XCUITest] Using Xcode configuration file: '/var/folders/wt/mv316j8j5ksdk5wfdbz_l9th0000gp/T/2018916-4338-kobc5n.rw8ic/appium-temp.xcconfig'
[XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=81ab1752c488e1e1e1ff8b0ca9f8e016357d1a46 IPHONEOS_DEPLOYMENT_TARGET=11.4 -xcconfig /var/folders/wt/mv316j8j5ksdk5wfdbz_l9th0000gp/T/2018916-4338-kobc5n.rw8ic/appium-temp.xcconfig' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Output from xcodebuild will not be logged. To change this, use 'showXcodeLog' desired capability
[XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[JSONWP Proxy] Matched '/status' to command name 'getStatus'
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Matched '/status' to command name 'getStatus'
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Matched '/status' to command name 'getStatus'
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Log file for xcodebuild test: /Users/username/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2018.10.16_21-00-07-+0530.xcresult/2_Test/Diagnostics/WebDriverAgentRunner-6ADCD61C-A7C1-42BC-8799-3D114D35AB8A/WebDriverAgentRunner-7DB92385-7A8A-4E39-8976-A99B1E20A872/Session-WebDriverAgentRunner-2018-10-16_210009-RlgOGH.log
[JSONWP Proxy] Matched '/status' to command name 'getStatus'
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Matched '/status' to command name 'getStatus'
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Matched '/status' to command name 'getStatus'
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Matched '/status' to command name 'getStatus'
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Matched '/status' to command name 'getStatus'
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Matched '/status' to command name 'getStatus'
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Matched '/status' to command name 'getStatus'
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"11.4.1\",\n      \"sdkVersion\" : \"12.0\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"11.4.1\",\n      \"ip\" : \"169.254.167.105\"\n    },\n    \"build\" : {\n      \"upgradedAt\" : \"1539154538000\",\n      \"time\" : \"Oct 16 2018 17:14:33\",\n      \"productBundleIdentifier\" : \"com.facebook.WebDriverAgentRunner\"\n    }\n  },\n  \"sessionId\" : \"DFB217E4-143D-4D0B-A87C-8C90DE6C8403\",\n  \"status\" : 0\n}"
[XCUITest] WebDriverAgent information:
[XCUITest] {
[XCUITest]   "state": "success",
[XCUITest]   "os": {
[XCUITest]     "name": "iOS",
[XCUITest]     "version": "11.4.1",
[XCUITest]     "sdkVersion": "12.0"
[XCUITest]   },
[XCUITest]   "ios": {
[XCUITest]     "simulatorVersion": "11.4.1",
[XCUITest]     "ip": "169.254.167.105"
[XCUITest]   },
[XCUITest]   "build": {
[XCUITest]     "upgradedAt": "1539154538000",
[XCUITest]     "time": "Oct 16 2018 17:14:33",
[XCUITest]     "productBundleIdentifier": "com.facebook.WebDriverAgentRunner"
[XCUITest]   }
[XCUITest] }
[XCUITest] WebDriverAgent successfully started after 9462ms
[BaseDriver] Event 'wdaSessionAttempted' logged at 1539703815763 (21:00:15 GMT+0530 (IST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Matched '/session' to command name 'createSession'
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.company.product.enterprise","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[JSONWP Proxy] Got response with status 200: {"value":{"sessionId":"2ADD3ED1-8245-46B2-8C8A-535A26EA7926","capabilities":{"device":"ipad","browserName":"company product","sdkVersion":"11.4.1","CFBundleIdentifier":"com.company.product.enterprise"}},"sessionId":"2ADD3ED1-8245-46B2-8C8A-535A26EA7926","status":0}
[BaseDriver] Event 'wdaSessionStarted' logged at 1539703819451 (21:00:19 GMT+0530 (IST))
[BaseDriver] Event 'wdaStarted' logged at 1539703819451 (21:00:19 GMT+0530 (IST))
[XCUITest] Skipping setting of the initial display orientation. Set the "orientation" capability to either "LANDSCAPE" or "PORTRAIT", if this is an undesired behavior.
[BaseDriver] Event 'orientationSet' logged at 1539703819452 (21:00:19 GMT+0530 (IST))
[BaseDriver] Event 'iwdpStarting' logged at 1539703819452 (21:00:19 GMT+0530 (IST))
[iOS] Starting ios_webkit_debug_proxy at port 27753 on device 81ab1752c488e1e1e1ff8b0ca9f8e016357d1a46
[BaseDriver] Event 'iwdpStarted' logged at 1539703819971 (21:00:19 GMT+0530 (IST))
[XCUITest] Started ios_webkit_debug proxy server at: http://localhost:27753
[Appium] New XCUITestDriver session created successfully, session 5e629140-5b0c-48bb-bb18-a97f4e4f7895 added to master session list
[BaseDriver] Event 'newSessionStarted' logged at 1539703819973 (21:00:19 GMT+0530 (IST))
[MJSONWP] Cached the protocol value 'MJSONWP' for the new session 5e629140-5b0c-48bb-bb18-a97f4e4f7895
[MJSONWP] Responding to client with driver.createSession() result: {"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"udid":"81ab1752c488e1e1e1ff8b0ca9f8e016357d1a46","deviceName":"User's iPad","platformVersion":"11.4.1","platformName":"iOS","xcodeOrgId":"ABCD","xcodeSigningId":"iPhone Developer","startIWDP":true,"app":"com.company.product.enterprise"}
[HTTP] <-- POST /wd/hub/session 200 19824 ms - 516
[HTTP] 
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"udid":"81ab1752c488e1e1e1ff8b0ca9f8e016357d1a46","deviceName":"User's iPad","platformVersion":"11.4.1","platformName":"iOS","xcodeOrgId":"ABCD","xcodeSigningId":"iPhone Developer","startIWDP":true,"app":"com.company.product.enterprise"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"udid":"81ab1752c488e1e1e1ff8b0ca9f8e016357d1a46","deviceName":"User's iPad","platformVersion":"11.4.1","platformName":"iOS","xcodeOrgId":"ABCD","xcodeSigningId":"iPhone Developer","startIWDP":true,"app":"com.company.product.enterprise"},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1539703840017 (21:00:40 GMT+0530 (IST))
[Appium] Requested iOS support with version >= 10, using 'XCUITest' driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver (v2.94.2) session
[Appium] Capabilities:
[Appium]   udid: 81ab1752c488e1e1e1ff8b0ca9f8e016357d1a46
[Appium]   deviceName: User's iPad
[Appium]   platformVersion: 11.4.1
[Appium]   platformName: iOS
[Appium]   xcodeOrgId: ABCD
[Appium]   xcodeSigningId: iPhone Developer
[Appium]   startIWDP: true
[Appium]   app: com.company.product.enterprise
[BaseDriver] Creating session with MJSONWP desired capabilities: {"udid":"81ab1752c488e1e1e1...
[BaseDriver] Session created with session id: 6a932c79-b16c-44a7-81a5-886936e3e71e
[XCUITest] Current user: 'username'
[XCUITest] Xcode version set to '10.0' (tools v10.0.0.0.1.1535735448)
[XCUITest] iOS SDK Version set to '12.0'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1539703840083 (21:00:40 GMT+0530 (IST))
[XCUITest] Available devices: 81ab1752c488e1e1e1ff8b0ca9f8e016357d1a46
[XCUITest] Creating iDevice object with udid '81ab1752c488e1e1e1ff8b0ca9f8e016357d1a46'
[XCUITest] Determining device to run tests on: udid: '81ab1752c488e1e1e1ff8b0ca9f8e016357d1a46', real device: true
[XCUITest] App is an iOS bundle, will attempt to run as pre-existing
[BaseDriver] Event 'appConfigured' logged at 1539703840301 (21:00:40 GMT+0530 (IST))
[BaseDriver] Event 'resetStarted' logged at 1539703840301 (21:00:40 GMT+0530 (IST))
[XCUITest] Reset: running ios real device reset flow
[BaseDriver] Event 'resetComplete' logged at 1539703840302 (21:00:40 GMT+0530 (IST))
[iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[iOSLog] Starting iOS device log capture with: 'idevicesyslog'
[BaseDriver] Event 'logCaptureStarted' logged at 1539703840426 (21:00:40 GMT+0530 (IST))
[XCUITest] Setting up real device
[XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[JSONWP Proxy] Matched '/status' to command name 'getStatus'
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"11.4.1\",\n      \"sdkVersion\" : \"12.0\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"11.4.1\",\n      \"ip\" : \"169.254.167.105\"\n    },\n    \"build\" : {\n      \"upgradedAt\" : \"1539154538000\",\n      \"time\" : \"Oct 16 2018 17:14:33\",\n      \"productBundleIdentifier\" : \"com.facebook.WebDriverAgentRunner\"\n    }\n  },\n  \"sessionId\" : \"2ADD3ED1-8245-46B2-8C8A-535A26EA7926\",\n  \"status\" : 0\n}"
[XCUITest] Upgrade timestamp of the currently bundled WDA: 1539154538000
[XCUITest] Upgrade timestamp of the WDA on the device: 1539154538000
[XCUITest] Will reuse previously cached WDA instance at 'http://localhost:8100/' with 'com.facebook.WebDriverAgentRunner'. Set the wdaLocalPort capability to a value different from 8100 if this is an undesired behavior.
[XCUITest] Trying to start WebDriverAgent 1 times with 10000ms interval
[BaseDriver] Event 'wdaStartAttempted' logged at 1539703840797 (21:00:40 GMT+0530 (IST))
[XCUITest] Using provided WebdriverAgent at 'http://localhost:8100/'
[BaseDriver] Event 'wdaSessionAttempted' logged at 1539703840798 (21:00:40 GMT+0530 (IST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Matched '/status' to command name 'getStatus'
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"11.4.1\",\n      \"sdkVersion\" : \"12.0\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"11.4.1\",\n      \"ip\" : \"169.254.167.105\"\n    },\n    \"build\" : {\n      \"upgradedAt\" : \"1539154538000\",\n      \"time\" : \"Oct 16 2018 17:14:33\",\n      \"productBundleIdentifier\" : \"com.facebook.WebDriverAgentRunner\"\n    }\n  },\n  \"sessionId\" : \"2ADD3ED1-8245-46B2-8C8A-535A26EA7926\",\n  \"status\" : 0\n}"
[JSONWP Proxy] Matched '/session' to command name 'createSession'
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.company.product.enterprise","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[JSONWP Proxy] Got response with status 200: {"value":{"sessionId":"EC967D92-B45F-4746-912C-1778D2B29339","capabilities":{"device":"ipad","browserName":"company product","sdkVersion":"11.4.1","CFBundleIdentifier":"com.company.product.enterprise"}},"sessionId":"EC967D92-B45F-4746-912C-1778D2B29339","status":0}
[BaseDriver] Event 'wdaSessionStarted' logged at 1539703844361 (21:00:44 GMT+0530 (IST))
[BaseDriver] Event 'wdaStarted' logged at 1539703844361 (21:00:44 GMT+0530 (IST))
[XCUITest] Skipping setting of the initial display orientation. Set the "orientation" capability to either "LANDSCAPE" or "PORTRAIT", if this is an undesired behavior.
[BaseDriver] Event 'orientationSet' logged at 1539703844361 (21:00:44 GMT+0530 (IST))
[BaseDriver] Event 'iwdpStarting' logged at 1539703844361 (21:00:44 GMT+0530 (IST))
[iOS] Starting ios_webkit_debug_proxy at port 27753 on device 81ab1752c488e1e1e1ff8b0ca9f8e016357d1a46
[BaseDriver] Event 'iwdpStarted' logged at 1539703844373 (21:00:44 GMT+0530 (IST))
[XCUITest] Started ios_webkit_debug proxy server at: http://localhost:27753
[Appium] New XCUITestDriver session created successfully, session 6a932c79-b16c-44a7-81a5-886936e3e71e added to master session list
[BaseDriver] Event 'newSessionStarted' logged at 1539703844374 (21:00:44 GMT+0530 (IST))
[MJSONWP] Cached the protocol value 'MJSONWP' for the new session 6a932c79-b16c-44a7-81a5-886936e3e71e
[MJSONWP] Responding to client with driver.createSession() result: {"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"udid":"81ab1752c488e1e1e1ff8b0ca9f8e016357d1a46","deviceName":"User's iPad","platformVersion":"11.4.1","platformName":"iOS","xcodeOrgId":"ABCD","xcodeSigningId":"iPhone Developer","startIWDP":true,"app":"com.company.product.enterprise"}
[HTTP] <-- POST /wd/hub/session 200 4359 ms - 516
[HTTP] 
[IWDP] Unable to bind 81ab1752c488e1e1e1ff8b0ca9f8e016357d1a46 on port 27753-27753

**Comment by afatima28** [comment]
Please let me know if you meant some other logs. I'll post those.

**Comment by mykola-mokhnach** [comment]
This might be a problem with IWDP config. Try to ask at https://github.com/google/ios-webkit-debug-proxy

Closed as third party issue

**Comment by imurchie** [comment]
My guess is because two sessions are being created in a row, using the same device. ios-webkit-debug-proxy is being started for the first and is still running when the second is started.

Your test should start a session, do stuff, then close the session. Not start a session, then start another identical session.
