### ISSUE TITLE
ios> real device> get page source issue

### ISSUE THREAD

**Issue by vamsikrishna1234563839303** [appium/appium#11545]
## The problem

when i try to inspect elements using appium inspector in the server screen i got WDA time out error and also i got some errors for big screns. but it is working some times to load big screens (lot data in it).  for small screens it is working fine

## Environment

* Appium version (or git revision) that exhibits the issue: appium version 1.8.1
* Mobile platform/version under test: ios 11.4.1
 Real device or emulator/simulator: Real Device
Xcode: 9.4

Desired Capabilities are: 

{
  "platformName": "iOS",
  "deviceName": "ipad Air",
  "udid": "a451bdb8bbc400788dc63bd56f4fe24f99642d0f",
  "bundleId": "ie.eida.iphoneapp.EIDA-iphone",
  "automationName": "XCUITest",
  "noReset": true,
  "platformVersion": "11.4.1",
  "showXcodeLog": true
}

## Details

page source issue in finding elements

## Link to Appium logs

The server is running

[Appium] Welcome to Appium v1.8.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/sessions
[HTTP] {}
[MJSONWP] Calling AppiumDriver.getSessions() with args: []
[MJSONWP] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 7 ms - 40
[HTTP] 
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"automationName":"XCUITest","bundleId":"ie.eida.iphoneapp.EIDA-iphone","deviceName":"ipad Air","noReset":true,"platformName":"iOS","platformVersion":"11.4.1","showXcodeLog":true,"udid":"a451bdb8bbc400788dc63bd56f4fe24f99642d0f","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"automationName":"XCUITest","bundleId":"ie.eida.iphoneapp.EIDA-iphone","deviceName":"ipad Air","noReset":true,"platformName":"iOS","platformVersion":"11.4.1","showXcodeLog":true,"udid":"a451bdb8bbc400788dc63bd56f4fe24f99642d0f","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1539855402165 (10:36:42 GMT+0100 (IST))
[Appium] Creating new XCUITestDriver (v2.84.0) session
[Appium] Capabilities:
[Appium]   automationName: XCUITest
[Appium]   bundleId: ie.eida.iphoneapp.EIDA-iphone
[Appium]   deviceName: ipad Air
[Appium]   noReset: true
[Appium]   platformName: iOS
[Appium]   platformVersion: 11.4.1
[Appium]   showXcodeLog: true
[Appium]   udid: a451bdb8bbc400788dc63bd56f4fe24f99642d0f
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[BaseDriver] Creating session with MJSONWP desired capabilities: {"automationName":"XCUITest...
[BaseDriver] Session created with session id: 688acf55-24f0-424d-a7b5-29f8d08623f4
[XCUITest] Current user: 'vamsi'
[XCUITest] Xcode version set to '9.4' (tools v10.0.0.0.1.1535735448)
[XCUITest] iOS SDK Version set to '11.4'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1539855402554 (10:36:42 GMT+0100 (IST))
[XCUITest] Available devices: a451bdb8bbc400788dc63bd56f4fe24f99642d0f
[XCUITest] Creating iDevice object with udid 'a451bdb8bbc400788dc63bd56f4fe24f99642d0f'
[XCUITest] Determining device to run tests on: udid: 'a451bdb8bbc400788dc63bd56f4fe24f99642d0f', real device: true
[BaseDriver] Event 'appConfigured' logged at 1539855404116 (10:36:44 GMT+0100 (IST))
[BaseDriver] Event 'resetStarted' logged at 1539855404116 (10:36:44 GMT+0100 (IST))
[XCUITest] Reset: fullReset not set. Leaving as is
[BaseDriver] Event 'resetComplete' logged at 1539855404117 (10:36:44 GMT+0100 (IST))
[iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[iOSLog] Starting iOS device log capture with: 'idevicesyslog'
[XCUITest] Crash reports root '/Users/vamsi/Library/Logs/CrashReporter/MobileDevice/iPad Air' does not exist. Got nothing to gather.
[BaseDriver] Event 'logCaptureStarted' logged at 1539855404553 (10:36:44 GMT+0100 (IST))
[XCUITest] Setting up real device
[XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"11.4.1\",\n      \"sdkVersion\" : \"11.3\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"11.4.1\",\n      \"ip\" : \"192.168.1.39\"\n    },\n    \"build\" : {\n      \"time\" : \"Sep  4 2018 10:27:07\"\n    }\n  },\n  \"sessionId\" : \"832F23C9-5AF2-470E-9F74-460F411FB68B\",\n  \"status\" : 0\n}"
[XCUITest] Will reuse previously cached WDA instance at 'http://localhost:8100/'. Set the wdaLocalPort capability to a value different from 8100 if this is an undesired behavior.
[BaseDriver] Event 'wdaStartAttempted' logged at 1539855405266 (10:36:45 GMT+0100 (IST))
[XCUITest] Using provided WebdriverAgent at 'http://localhost:8100/'
[BaseDriver] Event 'wdaSessionAttempted' logged at 1539855405267 (10:36:45 GMT+0100 (IST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"11.4.1\",\n      \"sdkVersion\" : \"11.3\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"11.4.1\",\n      \"ip\" : \"192.168.1.39\"\n    },\n    \"build\" : {\n      \"time\" : \"Sep  4 2018 10:27:07\"\n    }\n  },\n  \"sessionId\" : \"832F23C9-5AF2-470E-9F74-460F411FB68B\",\n  \"status\" : 0\n}"
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"ie.eida.iphoneapp.EIDA-iphone","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[JSONWP Proxy] Got response with status 200: {"value":{"sessionId":"1271920E-BBD1-44DF-84ED-DF5388AAFE67","capabilities":{"device":"ipad","browserName":"EIDA App","sdkVersion":"11.4.1","CFBundleIdentifier":"ie.eida.iphoneapp.EIDA-iphone"}},"sessionId":"1271920E-BBD1-44DF-84ED-DF5388AAFE67","status":0}
[BaseDriver] Event 'wdaSessionStarted' logged at 1539855411647 (10:36:51 GMT+0100 (IST))
[BaseDriver] Event 'wdaStarted' logged at 1539855411647 (10:36:51 GMT+0100 (IST))
[XCUITest] Skipping setting of the initial display orientation. Set the "orientation" capability to either "LANDSCAPE" or "PORTRAIT", if this is an undesired behavior.
[BaseDriver] Event 'orientationSet' logged at 1539855411648 (10:36:51 GMT+0100 (IST))
[Appium] New XCUITestDriver session created successfully, session 688acf55-24f0-424d-a7b5-29f8d08623f4 added to master session list
[BaseDriver] Event 'newSessionStarted' logged at 1539855411650 (10:36:51 GMT+0100 (IST))
[MJSONWP] Responding to client with driver.createSession() result: {"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"automationName":"XCUITest","bundleId":"ie.eida.iphoneapp.EIDA-iphone","deviceName":"ipad Air","noReset":true,"platformName":"iOS","platformVersion":"11.4.1","showXcodeLog":true,"udid":"a451bdb8bbc400788dc63bd56f4fe24f99642d0f","newCommandTimeout":0,"connectHardwareKeyboard":true}
[HTTP] <-- POST /wd/hub/session 200 9489 ms - 550
[HTTP] 
[HTTP] --> POST /wd/hub/session/688acf55-24f0-424d-a7b5-29f8d08623f4/context
[HTTP] {"name":"NATIVE_APP"}
[MJSONWP] Calling AppiumDriver.setContext() with args: ["NATIVE_APP","688acf55-24f0-424d-a7b5-29f8d08623f4"]
[XCUITest] Executing command 'setContext'
[iOS] Attempting to set context to 'NATIVE_APP'
[MJSONWP] Responding to client with driver.setContext() result: null
[HTTP] <-- POST /wd/hub/session/688acf55-24f0-424d-a7b5-29f8d08623f4/context 200 6 ms - 76
[HTTP] 
[HTTP] --> GET /wd/hub/session/688acf55-24f0-424d-a7b5-29f8d08623f4/source
[HTTP] {}
[MJSONWP] Calling AppiumDriver.getPageSource() with args: ["688acf55-24f0-424d-a7b5-29f8d08623f4"]
[XCUITest] Executing command 'getPageSource'
[JSONWP Proxy] Proxying [GET /source] to [GET http://localhost:8100/session/1271920E-BBD1-44DF-84ED-DF5388AAFE67/source] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"\\n\\n  \\n    \\n      \\n        
[MJSONWP] Responding to client with driver.getPageSource() result: "\n  \n    \n      \n        \n      \n      
[HTTP] <-- GET /wd/hub/session/688acf55-24f0-424d-a7b5-29f8d08623f4/source 200 2522 ms - 8390
[HTTP] 
[HTTP] --> GET /wd/hub/session/688acf55-24f0-424d-a7b5-29f8d08623f4/screenshot
[HTTP] {}
[MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["688acf55-24f0-424d-a7b5-29f8d08623f4"]
[XCUITest] Executing command 'getScreenshot'
[XCUITest] Taking screenshot with WDA
[JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/1271920E-BBD1-44DF-84ED-DF5388AAFE67/screenshot] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"iVBORw0KGgoAAAANSUhEUgAABgAAAAgACAIAAABvs29hAAAAAXNSR0IArs4c6QAA\\r\\nABxpRE9UAAAAAgAAAAAAAAQAAAAAKAAABAAAAAQAAAeALzfCMegAAEAASURBVHgB\\r\\n7L1nlBXXlf5dJElEiSSUkxEgROd8u2\\/nnBMZBEIIhLKVoyXo7pvq5gZkJYexLcvZ\\r\\n1thjW1awJAtFELETdM65QfKM5\\/30\\/vapbiRbHv\\/BHo9TrXXWXZe6Veec2lXNec6z\\r\\nn723NmK3jNjjh53Rg66oAT2s1x3R447u9Fg63Clt7swOPbNTz+xxpfS7Eged0cPO\\r\\nqGF9+aAeNuCM73daB5yWQYdlzJY46LC2edJaPWld7sQBV+ygK4LW77L0uqz9rviz\\r\\naj26RbXEXt3ChYx40hEy4ozodFtbPRmd7pQe3coJ\\/GTMh6l2uWnxvXp8rzu6Xx9v\\r\\nA65oo3Eat0Y\\/dEIbc0TRuN9hR+ygM5b5M0\\/ujql+pvHPRA7SBvQo+unVY5mPGiix\\r\\nRzd+ZQJitxFH9Jg9VrX4MfvZ3exZWcY82bSAaQHTAqYFTAv861gA7KFWfPBAPAvx\\r\\nsKzgYSdp9ogxezTQhRUcHCIG0WNl9Xem8E9OY+Hu8Fjb3GAGro0dcK+ggW3oZ9hB\\r\\nA5wkdoElPFEcpLG4czKYp8uVMeCwnrRHnbJFjThiwTkd7gwa6z6jjDjDjM573PEd\\r\\n7jQDI\\/W40hTsiaK3Tk9sm9cCXAFXMArAgEkqLJTIJTITnblF8AWwBKRp9QCx0jhh\\r\\nzBHxiX3Fv86TNe\\/UtIBpAdMCpgX+ni1g7K9ZuZgku35WW9USWSJpao9sYe1jtZVd\\r\\nvx7Woef2uDJYN0\\/ao9kgs3qq5Vt4AE5j8WXzzrrMosxirVgC6dk4Lrt7V9qgPW3A\\r\\nk...
[MJSONWP] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAABgAAAAgACAIAAABvs29hAAAAAXNSR0IArs4c6QAA\r\nABxpRE9UAAAAAgAAAAAAAAQAAAAAKAAABAAAAAQAAAeALzfCMegAAEAASURBVHgB\r\n7L1nlBXXlf5dJElEiSSUkxEgROd8u2/nnBMZBEIIhLKVoyXo7pvq5gZkJYexLcvZ\r\n1thjW1awJAtFELETdM65QfKM5/30/vapbiRbHv/BHo9TrXXWXZe6Veec2lXNec6z\r\nn723NmK3jNjjh53Rg66oAT2s1x3R447u9Fg63Clt7swOPbNTz+xxpfS7Eged0cPO\r\nqGF9+aAeNuCM73daB5yWQYdlzJY46LC2edJaPWld7sQBV+ygK4LW77L0uqz9rviz\r\naj26RbXEXt3ChYx40hEy4ozodFtbPRmd7pQe3coJ/GTMh6l2uWnxvXp8rzu6Xx9v\r\nA65oo3Eat0Y/dEIbc0TRuN9hR+ygM5b5M0/ujql+pvHPRA7SBvQo+unVY5mPGiix\r\nRzd+ZQJitxFH9Jg9VrX4MfvZ3exZWcY82bSAaQHTAqYFTAv861gA7KFWfPBAPAvx\r\nsKzgYSdp9ogxezTQhRUcHCIG0WNl9Xem8E9OY+Hu8Fjb3GAGro0dcK+ggW3oZ9hB\r\nA5wkdoElPFEcpLG4czKYp8uVMeCwnrRHnbJFjThiwTkd7gwa6z6jjDjDjM573PEd\r\n7jQDI/W40hTsiaK3Tk9sm9cCXAFXMArAgEkqLJTIJTITnblF8AWwBKRp9QCx0jhh\r\nzBHxiX3Fv86TNe/UtIBpAdMCpgX+ni1g7K9ZuZgku35WW9USWSJpao9sYe1jtZVd\r\nvx7Woef2uDJYN0/ao9kgs3qq5Vt4AE5j8WXzzrrMosxirVgC6dk4Lrt7V9qgPW3A\r\nkdLmjW/1x3Z52M7HslKf3pt36Wl8l/27M5rlm0tYaoUQYPV3xbOkcpDFVKaqGht/\r\n...
[HTTP] <-- GET /wd/hub/session/688acf55-24f0-424d-a7b5-29f8d08623f4/screenshot 200 390 ms - 975986
[HTTP] 
[HTTP] --> GET /wd/hub/session/688acf55-24f0-424d-a7b5-29f8d08623f4/window/current/size
[HTTP] {}
[MJSONWP] Calling AppiumDriver.getWindowSize() with args: ["current","688acf55-24f0-424d-a7b5-29f8d08623f4"]
[XCUITest] Executing command 'getWindowSize'
[JSONWP Proxy] Proxying [GET /window/size] to [GET http://localhost:8100/session/1271920E-BBD1-44DF-84ED-DF5388AAFE67/window/size] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"width\" : 768,\n    \"height\" : 1024\n  },\n  \"sessionId\" : \"1271920E-BBD1-44DF-84ED-DF5388AAFE67\",\n  \"status\" : 0\n}"
[MJSONWP] Responding to client with driver.getWindowSize() result: {"width":768,"height":1024}
[HTTP] <-- GET /wd/hub/session/688acf55-24f0-424d-a7b5-29f8d08623f4/window/current/size 200 164 ms - 99
[HTTP] 
[HTTP] --> GET /wd/hub/session/688acf55-24f0-424d-a7b5-29f8d08623f4/source
[HTTP] {}
[MJSONWP] Calling AppiumDriver.getPageSource() with args: ["688acf55-24f0-424d-a7b5-29f8d08623f4"]
[XCUITest] Executing command 'getPageSource'
[JSONWP Proxy] Proxying [GET /source] to [GET http://localhost:8100/session/1271920E-BBD1-44DF-84ED-DF5388AAFE67/source] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"Cannot get 'xml' source of the current application\",\n  \"sessionId\" : \"1271920E-BBD1-44DF-84ED-DF5388AAFE67\",\n  \"status\" : 13\n}"
[MJSONWP] Encountered internal error running command: Error: An unknown server-side error occurred while processing the command.
[MJSONWP]     at JWProxy.command$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:176:15)
[MJSONWP]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP]     at 
[HTTP] <-- GET /wd/hub/session/688acf55-24f0-424d-a7b5-29f8d08623f4/source 500 252231 ms - 238
[HTTP] 
[HTTP] --> GET /wd/hub/session/688acf55-24f0-424d-a7b5-29f8d08623f4/screenshot
[HTTP] {}
[MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["688acf55-24f0-424d-a7b5-29f8d08623f4"]
[XCUITest] Executing command 'getScreenshot'
[XCUITest] Taking screenshot with WDA
[JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/1271920E-BBD1-44DF-84ED-DF5388AAFE67/screenshot] with no body
JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"iVBORw0KGgoAAAANSUhEUgAABgAAAAgACAIAAABvs29hAAAAAXNSR0IArs4c6QAA\\r\\nABxpRE9UAAAAAgAAAAAAAAQAAAAAKAAABAAAAAQAAABQyfrcpT8AAEAASURBVHgB\\r\\n7NCBAAAAAICg\\/akXKYQKAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBg\\r\\nwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIAB\\r\\nAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYM\\r\\nGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBg\\r\\nwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIAB\\r\\nAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYM\\r\\nGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBg\\r\\nwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIAB\\r\\nAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYM\\r\\nGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBg\\r\\nwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIAB\\r\\nAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYM\\r\\nGDBgwIABAwYMGDBgwIA...
[MJSONWP] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAABgAAAAgACAIAAABvs29hAAAAAXNSR0IArs4c6QAA\r\nABxpRE9UAAAAAgAAAAAAAAQAAAAAKAAABAAAAAQAAABQyfrcpT8AAEAASURBVHgB\r\n7NCBAAAAAICg/akXKYQKAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBg\r\nwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIAB\r\nAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYM\r\nGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBg\r\nwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIAB\r\nAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYM\r\nGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBg\r\nwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIAB\r\nAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYM\r\nGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBg\r\nwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIAB\r\nAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYM\r\nGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBgwIABAwYMGDBg\r\n...
[HTTP] <-- GET /wd/hub/session/688acf55-24f0-424d-a7b5-29f8d08623f4/screenshot 200 88270 ms - 58694
[HTTP] 
[HTTP] --> GET /wd/hub/session/688acf55-24f0-424d-a7b5-29f8d08623f4/window/current/size
[HTTP] {}
[MJSONWP] Calling AppiumDriver.getWindowSize() with args: ["current","688acf55-24f0-424d-a7b5-29f8d08623f4"]
[XCUITest] Executing command 'getWindowSize'
[JSONWP Proxy] Proxying [GET /window/size] to [GET http://localhost:8100/session/1271920E-BBD1-44DF-84ED-DF5388AAFE67/window/size] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"The application under test with bundle id 'ie.eida.iphoneapp.EIDA-iphone' is not running, possibly crashed\",\n  \"sessionId\" : \"1271920E-BBD1-44DF-84ED-DF5388AAFE67\",\n  \"status\" : 889\n}"
[MJSONWP] Encountered internal error running command: Error: An error occurred
[MJSONWP]     at JWProxy.command$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:176:15)
[MJSONWP]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP]     at 
[HTTP] <-- GET /wd/hub/session/688acf55-24f0-424d-a7b5-29f8d08623f4/window/current/size 500 160 ms - 188
[HTTP]

**Comment by mykola-mokhnach** [comment]
Upgrade Appium to the most recent version. If that does not work then please report the issue to https://github.com/facebook/WebDriverAgent as there is not much to there on Appium side
