### ISSUE TITLE
UIautomator/appium do not display classname while identifying object for ReactNative 0.57.1

### ISSUE THREAD

**Issue by neerajkumar-lad** [appium/appium#11546]
## The problem

Our application got updated from React Native 0.53.0 to 0.57.1. When I run the stable script on a new version of React Native app, Script got failed at first object only.  When I investigate the object property, I found that UIautomator is not capturing class name.
  
## Environment

* Appium version (or git revision) that exhibits the issue: **1.9.1 and 1.8.1**
* Last Appium version that did not exhibit the issue (if applicable): **N/A**
* Desktop OS/version used to run Appium: **N/A**
* Node.js version (unless using Appium.app|exe): **v8.9.4**
* Mobile platform/version under test: **Android 7,8 API Level 24 and 26**
* Real device or emulator/simulator: **Both**
* Appium CLI or Appium.app|exe: **1.9.1 and 1.8.1**
* React Native app version: 0.57.1

## Details

It was working fine when our app was using React Native 0.53.0. However, not for 0.57.1

## Link to Appium logs

Log [GIST](https://gist.github.com/neerajkumar-lad/267d9573715673650365aeeeada87108)

<img width="446" alt="qr9cg" src="https://user-images.githubusercontent.com/41137182/47147611-44039380-d2ec-11e8-8005-39b0a444c261.png">

**Comment by mykola-mokhnach** [comment]
This is an issue in React itself. It simply stopped providing accessibility information for some elements.

Closed as third party problem.

**Comment by mykola-mokhnach** [comment]
Linking https://github.com/appium/appium/issues/11513
