### ISSUE TITLE
Appium 1.9.1 - Android - Unable to respond to In App Permissions

### ISSUE THREAD

**Issue by auto-mator** [appium/appium#11549]
## The problem

Upgraded from 1.8.2 -> 1.9.1 and now I am unable to respond to Android Permissions when they are displayed upon launching the application. Prior to this release, I was always able to respond using:

`WebDriverWait(self.driver,5).until(EC.element_to_be_clickable((By.ID, "com.android.packageinstaller:id/permission_allow_button"))).click()`

But this no longer is working...

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable): 1.8.2
* Desktop OS/version used to run Appium: MAC 10.13.6
* Mobile platform/version under test: Android (all versions)
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Code To Reproduce Issue [ Good To Have ] 

SEE ABOVE

**Comment by mykola-mokhnach** [comment]
Is the element present in page source?

**Comment by auto-mator** [comment]
seems like it, see below


test_performance (__main__.MCT) ... <?xml version="1.0" encoding="UTF-8"?><hierarchy rotation="0"><android.widget.FrameLayout index="0" text="" class="android.widget.FrameLayout" package="com.google.android.packageinstaller" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[46,84][1393,2560]" resource-id="" instance="0"><android.widget.FrameLayout index="0" text="" class="android.widget.FrameLayout" package="com.google.android.packageinstaller" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[46,84][1393,2560]" resource-id="" instance="1"><android.widget.FrameLayout index="0" text="" class="android.widget.FrameLayout" package="com.google.android.packageinstaller" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[46,84][1393,2560]" resource-id="android:id/content" instance="2"><android.view.ViewGroup index="0" text="" class="android.view.ViewGroup" package="com.google.android.packageinstaller" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[46,84][1393,2560]" resource-id="" instance="0"><android.widget.LinearLayout index="0" text="" class="android.widget.LinearLayout" package="com.google.android.packageinstaller" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[46,1033][1393,1611]" resource-id="com.android.packageinstaller:id/dialog_container" instance="0"><android.widget.FrameLayout index="0" text="" class="android.widget.FrameLayout" package="com.google.android.packageinstaller" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[46,1033][1393,1359]" resource-id="com.android.packageinstaller:id/desc_container" instance="3"><android.widget.LinearLayout index="0" text="" class="android.widget.LinearLayout" package="com.google.android.packageinstaller" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[123,1117][1337,1359]" resource-id="com.android.packageinstaller:id/perm_desc_root" instance="1"><android.widget.ImageView index="0" text="" class="android.widget.ImageView" package="com.google.android.packageinstaller" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[123,1128][249,1254]" resource-id="com.android.packageinstaller:id/permission_icon" instance="0"/><android.widget.TextView index="1" text="Allow AT&amp;T Mobile Transfer to access photos, media, and files on your device?" class="android.widget.TextView" package="com.google.android.packageinstaller" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[249,1128][1337,1359]" resource-id="com.android.packageinstaller:id/permission_message" instance="0"/></android.widget.LinearLayout></android.widget.FrameLayout><android.widget.LinearLayout index="1" text="" class="android.widget.LinearLayout" package="com.google.android.packageinstaller" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[46,1359][1393,1611]" resource-id="" instance="2"><android.widget.LinearLayout index="0" text="" class="android.widget.LinearLayout" package="com.google.android.packageinstaller" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[123,1359][1337,1583]" resource-id="com.android.packageinstaller:id/button_group" instance="3"><android.widget.TextView index="0" text="1 of 6" class="android.widget.TextView" package="com.google.android.packageinstaller" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[130,1455][297,1549]" resource-id="com.android.packageinstaller:id/current_page_text" instance="1"/><android.widget.Button index="1" text="Deny" class="android.widget.Button" package="com.google.android.packageinstaller" content-desc="" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[815,1415][1041,1583]" resource-id="com.android.packageinstaller:id/permission_deny_button" instance="0"/><android.widget.Button index="2" text="Allow" class="android.widget.Button" package="com.google.android.packageinstaller" content-desc="" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[1069,1415][1337,1583]" resource-id="com.android.packageinstaller:id/permission_allow_button" instance="1"/></android.widget.LinearLayout></android.widget.LinearLayout></android.widget.LinearLayout></android.view.ViewGroup></android.widget.FrameLayout></android.widget.FrameLayout></android.widget.FrameLayout></hierarchy>

**Comment by auto-mator** [comment]
From Appium log:

[HTTP] --> POST /wd/hub/session/de003a0f-bec6-40a2-9bf6-7cc5eb8a76f3/element
[HTTP] {"using":"css selector","value":"[id=\"com.android.packageinstaller:id/permission_allow_button\"]"}
[debug] [W3C] Calling AppiumDriver.findElement() with args: ["css selector","[id=\"com.android.packageinstaller:id/permission_allow_button\"]","de003a0f-bec6-40a2-9bf6-7cc5eb8a76f3"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [W3C] Encountered internal error running command: InvalidSelectorError: Locator Strategy 'css selector' is not supported for this session
[debug] [W3C]     at AndroidUiautomator2Driver.validateLocatorStrategy (/usr/local/avm/versions/1.9.1/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:349:13)
[debug] [W3C]     at AndroidUiautomator2Driver.callee$0$0$ (/usr/local/avm/versions/1.9.1/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:26:8)
[debug] [W3C]     at tryCatch (/usr/local/avm/versions/1.9.1/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[debug] [W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/avm/versions/1.9.1/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[debug] [W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/avm/versions/1.9.1/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[debug] [W3C]     at invoke (/usr/local/avm/versions/1.9.1/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[debug] [W3C]     at enqueueResult (/usr/local/avm/versions/1.9.1/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
[debug] [W3C]     at Promise (<anonymous>)
[debug] [W3C]     at F (/usr/local/avm/versions/1.9.1/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
[debug] [W3C]     at AsyncIterator.enqueue (/usr/local/avm/versions/1.9.1/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
[debug] [W3C]     at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/avm/versions/1.9.1/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[debug] [W3C]     at Object.runtime.async (/usr/local/avm/versions/1.9.1/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
[debug] [W3C]     at AndroidUiautomator2Driver.callee$0$0 [as findElOrElsWithProcessing] (/usr/local/avm/versions/1.9.1/node_modules/appium/node_modules/appium-base-driver/build/lib/basedriver/commands/find.js:47:30)
[debug] [W3C]     at AndroidUiautomator2Driver.callee$0$0$ (/usr/local/avm/versions/1.9.1/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:46:21)
[debug] [W3C]     at tryCatch (/usr/local/avm/versions/1.9.1/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[debug] [W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/avm/versions/1.9.1/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[debug] [W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/avm/versions/1.9.1/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[debug] [W3C]     at invoke (/usr/local/avm/versions/1.9.1/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[debug] [W3C]     at enqueueResult (/usr/local/avm/versions/1.9.1/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
[debug] [W3C]     at Promise (<anonymous>)
[debug] [W3C]     at F (/usr/local/avm/versions/1.9.1/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
[debug] [W3C]     at AsyncIterator.enqueue (/usr/local/avm/versions/1.9.1/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
[debug] [W3C]     at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/avm/versions/1.9.1/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[debug] [W3C]     at Object.runtime.async (/usr/local/avm/versions/1.9.1/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
[debug] [W3C]     at AndroidUiautomator2Driver.callee$0$0 [as findElement] (/usr/local/avm/versions/1.9.1/node_modules/appium/node_modules/appium-base-driver/build/lib/basedriver/commands/find.js:88:30)
[debug] [W3C]     at /usr/local/avm/versions/1.9.1/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:296:26
[debug] [W3C]     at tryCatcher (/usr/local/avm/versions/1.9.1/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/util.js:26:23)
[debug] [W3C]     at Promise._settlePromiseFromHandler (/usr/local/avm/versions/1.9.1/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/promise.js:510:31)
[debug] [W3C]     at Promise._settlePromiseAt (/usr/local/avm/versions/1.9.1/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/promise.js:584:18)
[debug] [W3C]     at Promise._settlePromiseAtPostResolution (/usr/local/avm/versions/1.9.1/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/promise.js:248:10)
[debug] [W3C]     at Async._drainQueue (/usr/local/avm/versions/1.9.1/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/async.js:128:12)
[debug] [W3C]     at Async._drainQueues (/usr/local/avm/versions/1.9.1/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/async.js:133:10)
[debug] [W3C]     at Immediate.Async.drainQueues (/usr/local/avm/versions/1.9.1/node_modules/appium/node_modules/appium-base-driver/node_modules/bluebird/js/main/async.js:15:14)
[debug] [W3C]     at runCallback (timers.js:781:20)
[debug] [W3C]     at tryOnImmediate (timers.js:743:5)
[debug] [W3C]     at processImmediate [as _immediateCallback] (timers.js:714:5)

**Comment by mykola-mokhnach** [comment]
> I am seeing this "[W3C] Encountered internal error running command: InvalidSelectorError: Locator Strategy 'css selector' is not supported for this session"...but I am not using css selector, I am searching by ID.

It is the problem of your client. Make sure it is up to date.
Closed as duplicate

**Comment by auto-mator** [comment]
What client? Can you please be a little bit more specific...

**Comment by auto-mator** [comment]
And duplicate of what other ticket?

**Comment by auto-mator** [comment]
If you are going to close a ticket, provide some information.

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/search?q=%22Locator+Strategy+%27css+selector%27+is+not+supported+for+this+session%22&type=Issues

Kindly use search feature. The similar problem has been already reported many times.
