### ISSUE TITLE
I can't start .js for appium-ios-simulator code

### ISSUE THREAD

**Issue by aluckin3** [appium/appium#11548]
## The problem

I write script with this code:
```
#!/usr/bin/env node
import { getSimulator } from 'appium-ios-simulator';
import SimulatorXcode6 from '../../lib/simulator-xcode-6';

let sim = await getSimulator('udid');
await sim.cleanSafari(true);
```

udid is id of simulator

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOSx
* Node.js version (unless using Appium.app|exe): v10.7.0
* Mobile platform/version under test: iOS/iPhone X
* Real device or emulator/simulator: 
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

I get this error:
```
/xxx/test.js:2
import { getSimulator } from 'appium-ios-simulator';
       ^

SyntaxError: Unexpected token {
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
```

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
You must transplie the code first in order to pass it to node interpreter, for example, using babel. Current node release is unable to understand ES2017.

**Comment by aluckin3** [comment]
After using babel on that code i get:
repl: await is a reserved word (5:10)

**Comment by imurchie** [comment]
How are you using it? What is the code like? `await` can only be used within an `async` function.

**Comment by aluckin3** [comment]
> How are you using it? What is the code like? `await` can only be used within an `async` function.
```
#!/usr/bin/env node
import { getSimulator } from 'appium-ios-simulator';
import SimulatorXcode6 from '../../lib/simulator-xcode-6';

let sim = await getSimulator('udid');
await sim.cleanSafari(true);
```
i changed this to:
```
#!/usr/bin/env node
import { getSimulator } from 'appium-ios-simulator';
import SimulatorXcode6 from '../../lib/simulator-xcode-6';

let sim = async () => {await getSimulator('78892108-FC0C-408E-B3A8-57F43A99CE6C');}
async() => { await sim.cleanSafari(true); }
```
and i get this from babel:
```
function _asyncToGenerator(fn) { return function () { var gen = fn.apply(this, arguments); return new Promise(function (resolve, reject) { function step(key, arg) { try { var info = gen[key](arg); var value = info.value; } catch (error) { reject(error); return; } if (info.done) { resolve(value); } else { return Promise.resolve(value).then(function (value) { step("next", value); }, function (err) { step("throw", err); }); } } return step("next"); }); }; }

import { getSimulator } from 'appium-ios-simulator';
import SimulatorXcode6 from '../../lib/simulator-xcode-6';

let sim = (() => {
  var _ref = _asyncToGenerator(function* () {
    yield getSimulator('78892108-FC0C-408E-B3A8-57F43A99CE6C');
  });

  return function sim() {
    return _ref.apply(this, arguments);
  };
})();
_asyncToGenerator(function* () {
  yield sim.cleanSafari(true);
});
```

and i get same error like in first posts

**Comment by imurchie** [comment]
Babel isn't transpiling the `import` statements. This is a babel config issue. How are you configuring it? What version? All sorts of variables are involved here.

**Comment by dpgraham** [comment]
Swapping ```
import SimulatorXcode6 from '../../lib/simulator-xcode-6';``` with ```
import SimulatorXcode6 from '../../build/lib/simulator-xcode-6';``` should fix the problem.

**Comment by aluckin3** [comment]
Question: Is it matter where this .js file is, in which directory?
imurchie i install like 2015/2016/2017, but i transpile this file from their site. How should my project should because now i only have that file in my project.

**Comment by imurchie** [comment]
No, it's a matter of getting babel configured correctly to transpile the code. This should really be asked of them, since it has nothing to do with Appium, though.
