### ISSUE TITLE
inspector could not get page source after run app successfully on ios12

### ISSUE THREAD

**Issue by yuesongjie** [appium/appium#11558]
## The problem
I have successfully run app on real device(ios12) through appium mac app on Mac but the page keeps showing 'Gathering initial app source...' and could not show the page source as before when using xcode 9 and ios11 device.

## Environment

* Appium version (or git revision) that exhibits the issue:V1.9.1
* Last Appium version that did not exhibit the issue (if applicable):I can't remember
* Desktop OS/version used to run Appium:.1.7.1
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:ios12
* Real device or emulator/simulator:real device iphone6s plus
* Appium CLI or Appium.app|exe:

## Details

as the picture shows
<img width="1080" alt="wx20181022-153643 2x" src="https://user-images.githubusercontent.com/29249726/47282063-5a715e00-d610-11e8-9299-c00a65108c71.png">

##report
[XCUITest] WebDriverAgent information:
[XCUITest] {
[XCUITest]   "state": "success",
[XCUITest]   "os": {
[XCUITest]     "name": "iOS",
[XCUITest]     "version": "12.0.1"
[XCUITest]   },
[XCUITest]   "ios": {
[XCUITest]     "simulatorVersion": "12.0.1",
[XCUITest]     "ip": "192.168.3.4"
[XCUITest]   },
[XCUITest]   "build": {
[XCUITest]     "time": "Oct 22 2018 11:43:42"
[XCUITest]   }
[XCUITest] }
[XCUITest] WebDriverAgent successfully started after 20421ms
[BaseDriver] Event 'wdaSessionAttempted' logged at 1540193093828 (15:24:53 GMT+0800 (CST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Matched '/session' to command name 'createSession'
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.lanyiapplive.qizhichan","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[JSONWP Proxy] Got response with status 200: {"value":{"sessionId":"BD42BAA5-2704-46E8-A6CB-EA2A4F9E6061","capabilities":{"device":"iphone","browserName":"七指禅","sdkVersion":"12.0.1","CFBundleIdentifier":"com.lanyiapplive.qizhichan"}},"sessionId":"BD42BAA5-2704-46E8-A6CB-EA2A4F9E6061","status":0}
[BaseDriver] Event 'wdaSessionStarted' logged at 1540193097159 (15:24:57 GMT+0800 (CST))
[BaseDriver] Event 'wdaStarted' logged at 1540193097160 (15:24:57 GMT+0800 (CST))
[XCUITest] Skipping setting of the initial display orientation. Set the "orientation" capability to either "LANDSCAPE" or "PORTRAIT", if this is an undesired behavior.
[BaseDriver] Event 'orientationSet' logged at 1540193097162 (15:24:57 GMT+0800 (CST))
[Appium] New XCUITestDriver session created successfully, session 74bb958d-59fc-4dbb-a1d8-43eb876e6c74 added to master session list
[BaseDriver] Event 'newSessionStarted' logged at 1540193097167 (15:24:57 GMT+0800 (CST))
[MJSONWP] Cached the protocol value 'MJSONWP' for the new session 74bb958d-59fc-4dbb-a1d8-43eb876e6c74
[MJSONWP] Responding to client with driver.createSession() result: {"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"automationName":"XCUITest","bundleId":"com.lanyiapplive.qizhichan","deviceName":"iPhone 6s Plus","noReset":true,"platformName":"iOS","platformVersion":"12.0.1","udid":"6eaec690714d9d23c386339e0c07268109d9fabc","newCommandTimeout":0,"connectHardwareKeyboard":true}
[HTTP] <-- POST /wd/hub/session 200 31926 ms - 533
[HTTP] 
[HTTP] --> POST /wd/hub/session/74bb958d-59fc-4dbb-a1d8-43eb876e6c74/context
[HTTP] {"name":"NATIVE_APP"}
[MJSONWP] Calling AppiumDriver.setContext() with args: ["NATIVE_APP","74bb958d-59fc-4dbb-a1d8-43eb876e6c74"]
[XCUITest] Executing command 'setContext'
[iOS] Attempting to set context to 'NATIVE_APP'
[MJSONWP] Responding to client with driver.setContext() result: null
[HTTP] <-- POST /wd/hub/session/74bb958d-59fc-4dbb-a1d8-43eb876e6c74/context 200 6 ms - 76
[HTTP] 
[HTTP] --> GET /wd/hub/session/74bb958d-59fc-4dbb-a1d8-43eb876e6c74/source
[HTTP] {}
[MJSONWP] Calling AppiumDriver.getPageSource() with args: ["74bb958d-59fc-4dbb-a1d8-43eb876e6c74"]
[XCUITest] Executing command 'getPageSource'
[JSONWP Proxy] Matched '/source' to command name 'getPageSource'
[JSONWP Proxy] Proxying [GET /source] to [GET http://localhost:8100/session/BD42BAA5-2704-46E8-A6CB-EA2A4F9E6061/source] with no body
[HTTP] <-- GET /wd/hub/session/74bb958d-59fc-4dbb-a1d8-43eb876e6c74/source - - ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/74bb958d-59fc-4dbb-a1d8-43eb876e6c74/source
[HTTP] {}
[MJSONWP] Calling AppiumDriver.getPageSource() with args: ["74bb958d-59fc-4dbb-a1d8-43eb876e6c74"]
[XCUITest] Executing command 'getPageSource'

**Comment by mykola-mokhnach** [comment]
Please report the problem to https://github.com/facebook/WebDriverAgent as there is nothing to fix on appium side

**Comment by ShubhamPagarwar** [comment]
Any update on this issue? Please reply i am facing the same issue on iOS 12.2 version.
Xcode Version - 10.2.1
Appium Version - 1.12.1

Request you to provide solution on this issue.

**Comment by ShubhamPagarwar** [comment]
@yuesongjie and @mykola-mokhnach  Please provide an latest update on this issue.
@yuesongjie did you solve this issue.

**Comment by sp090** [comment]
Please give me solution i am also facing same issue

**Comment by KazuCocoa** [comment]
If the response is because of process timeout inside the WDA, _useJSONSource_ or 
 https://github.com/appium/appium/pull/9338/files 's `description` format could help in some cases. The inspector has no ability to parsing the later one tho. (It is a debug option for clients)

**Comment by sp090** [comment]
When i try to appium inspector on ios it started but no element shown .
But when i try on android its working .
Please give me solution i stuck in this issue.

**Comment by ShubhamPagarwar** [comment]
Restart your Mac machine as well as your iPhone.  And try again

**Comment by sp090** [comment]
I tried this solution but still when i open inspector it shows me get page source with no body response

**Comment by sp090** [comment]
I got solution.
Reinstall homebrew & related package after this it will be working fine.

**Comment by hananurrehman** [comment]
Another solution to this, remove the following apps from test device:
`io.appium.uiautomator2.server`
`io.appium.uiautomator2.server.test`

**Comment by phatle1** [comment]
hi there, any solution for this issue, I'm facing this by using Appium CLI, works fine with Appium GUI

**Comment by hananurrehman** [comment]
@phatle1 
remove the following apps from the test device:

io.appium.uiautomator2.server io.appium.uiautomator2.server.test
