### ISSUE TITLE
Could not parse W3C capabilities: 'deviceName' can't be blank

### ISSUE THREAD

**Issue by hsafari** [appium/appium#11556]
## The problem

Appium Desktop error :
: Could not parse W3C capabilities: 'deviceName' can't be blank

## Environment

* Appium version : v1.9.1
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Samaubg Galaxy 
* Real device

		capabilities.setCapability("deviceName","G890A");
		capabilities.setCapability("BROWSER_NAME", "Android");
		capabilities.setCapability("VERSION", "7.0"); 
		capabilities.setCapability("platformName","Android");
		capabilities.setCapability("noReset", "True");
		capabilities.setCapability("appPackage", "com.samsung.android.contacts");
		capabilities.setCapability("appActivity", "com.android.dialer.DialtactsActivity");

## Details

If necessary, describe the problem you have been experiencing in more detail.

## 

[info] [Appium] Welcome to Appium v1.9.1
[info] [Appium] Appium REST http interface listener started on 0.0.0.0:4723[info] [HTTP] --> POST /wd/hub/session
[info] [HTTP] {"desiredCapabilities":{"appActivity":"com.android.dialer.DialtactsActivity","appPackage":"com.samsung.android.contacts","noReset":"True","BROWSER_NAME":"Android","VERSION":"7.0","platformName":"Android","deviceName":"G890A"},"capabilities":{"firstMatch":[{"platformName":"android"}]}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"appActivity":"com.android.dialer.DialtactsActivity","appPackage":"com.samsung.android.contacts","noReset":"True","BROWSER_NAME":"Android","VERSION":"7.0","platformName":"Android","deviceName":"G890A"},null,{"firstMatch":[{"platformName":"android"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1540143641367 (10:40:41 GMT-0700 (PDT))
[info] [Appium] Could not parse W3C capabilities: 'deviceName' can't be blank
[info] [Appium] Trying to fix W3C capabilities by merging them with JSONWP caps
[warn] [BaseDriver] The capabilities ["appActivity","appPackage","noReset","BROWSER_NAME","VERSION","deviceName"] are not standard capabilities and should have an extension prefix
[warn] [BaseDriver] Boolean capability passed in as string. Functionality may be compromised.
[info] [Appium] Creating new AndroidDriver (v4.1.1) session
[info] [Appium] Capabilities:
[info] [Appium]   appActivity: com.android.dialer.DialtactsActivity
[info] [Appium]   appPackage: com.samsung.android.contacts
[info] [Appium]   noReset: True
[info] [Appium]   BROWSER_NAME: Android
[info] [Appium]   VERSION: 7.0
[info] [Appium]   deviceName: G890A
[info] [Appium]   platformName: android
[debug] [BaseDriver] W3C capabilities {"alwaysMatch":{"appium:app... and MJSONWP desired capabilities {"appActivity":"com.android... were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"appium:app...
[warn] [BaseDriver] Boolean capability passed in as string. Functionality may be compromised.
[warn] [BaseDriver] Capability 'noReset' changed from string to boolean. This may cause unexpected behavior
[warn] [BaseDriver] The following capabilities were provided, but are not recognized by appium: BROWSER_NAME, VERSION.
[info] [BaseDriver] Session created with session id: 3c6944dd-f9a5-4702-b810-d7c51a9839dd
[info] [AndroidDriver] Java version is: 10.0.2
[info] [AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...[debug] [ADB] 1 device(s) connected
[info] [AndroidDriver] Using device: 1215fca550e13604
[debug] [ADB] Setting device id to 1215fca550e13604
[debug] [ADB] Running '/home/svt/Android/Sdk/platform-tools/adb -P 5037 -s 1215fca550e13604 shell getprop ro.build.version.sdk'[debug] [ADB] Current device property 'ro.build.version.sdk': 24
[debug] [ADB] Device API level: 24
[warn] [AndroidDriver] Consider setting 'automationName' capability to 'uiautomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.
[info] [AndroidDriver] App file was not listed, instead we're going to run com.samsung.android.contacts directly on the device
[debug] [AndroidDriver] Checking whether package is present on the device
[debug] [ADB] Running '/home/svt/Android/Sdk/platform-tools/adb -P 5037 -s 1215fca550e13604 shell pm list packages com.samsung.android.contacts'[info] [AndroidDriver] Starting Android session
[debug] [ADB] Running '/home/svt/Android/Sdk/platform-tools/adb -P 5037 -s 1215fca550e13604 wait-for-device'
[debug] [ADB] Running '/home/svt/Android/Sdk/platform-tools/adb -P 5037 -s 1215fca550e13604 shell echo ping'
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Getting install status for io.appium.settings
[debug] [ADB] Running '/home/svt/Android/Sdk/platform-tools/adb -P 5037 -s 1215fca550e13604 shell pm list packages io.appium.settings'[debug] [ADB] App is installed
[debug] [ADB] Getting package info for 'io.appium.settings'
[debug] [ADB] Running '/home/svt/Android/Sdk/platform-tools/adb -P 5037 -s 1215fca550e13604 shell dumpsys package io.appium.settings'[debug] [ADB] The installed 'io.appium.settings' package does not require upgrade ('2.3.0' >= '2.3.0')
[debug] [ADB] Running '/home/svt/Android/Sdk/platform-tools/adb -P 5037 -s 1215fca550e13604 shell ps'
[debug] [ADB] Device API level: 24
[debug] [ADB] Running '/home/svt/Android/Sdk/platform-tools/adb -P 5037 -s 1215fca550e13604 shell am start -W -n io.appium.settings/.Settings -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'[debug] [ADB] Device API level: 24
[debug] [ADB] Running '/home/svt/Android/Sdk/platform-tools/adb -P 5037 -s 1215fca550e13604 shell appops set io.appium.settings android\:mock_location allow'
[warn] [AndroidDriver] setDeviceLanguageCountry requires language or country.
[warn] [AndroidDriver] Got language: 'undefined' and country: 'undefined'
[debug] [Logcat] Starting logcat capture
[debug] [AndroidDriver] Pushing unlock helper app to device...
[debug] [ADB] Getting install status for io.appium.unlock
[debug] [ADB] Running '/home/svt/Android/Sdk/platform-tools/adb -P 5037 -s 1215fca550e13604 shell pm list packages io.appium.unlock'[debug] [ADB] App is installed
[debug] [ADB] Getting package info for 'io.appium.unlock'
[debug] [ADB] Running '/home/svt/Android/Sdk/platform-tools/adb -P 5037 -s 1215fca550e13604 shell dumpsys package io.appium.unlock'
[debug] [ADB] The installed 'io.appium.unlock' package does not require upgrade ('2.0.0' >= '2.0.0')
[info] [ADB] Getting device platform version
[debug] [ADB] Running '/home/svt/Android/Sdk/platform-tools/adb -P 5037 -s 1215fca550e13604 shell getprop ro.build.version.release'
[debug] [ADB] Current device property 'ro.build.version.release': 7.0
[debug] [ADB] Running '/home/svt/Android/Sdk/platform-tools/adb -P 5037 -s 1215fca550e13604 shell wm size'[debug] [ADB] Running '/home/svt/Android/Sdk/platform-tools/adb -P 5037 -s 1215fca550e13604 shell getprop ro.product.model'
[debug] [ADB] Current device property 'ro.product.model': SAMSUNG-SM-G890A
[debug] [ADB] Running '/home/svt/Android/Sdk/platform-tools/adb -P 5037 -s 1215fca550e13604 shell getprop ro.product.manufacturer'[debug] [ADB] Current device property 'ro.product.manufacturer': samsung
[warn] [AndroidDriver] No app sent in, not parsing package/activity
[debug] [AndroidDriver] No app capability. Assuming it is already on the device
[debug] [AndroidBootstrap] Watching for bootstrap disconnect
[debug] [ADB] Forwarding system: 4724 to device: 4724
[debug] [ADB] Running '/home/svt/Android/Sdk/platform-tools/adb -P 5037 -s 1215fca550e13604 forward tcp\:4724 tcp\:4724'
[debug] [UiAutomator] Starting UiAutomator
[debug] [UiAutomator] Moving to state 'starting'
[debug] [UiAutomator] Parsing uiautomator jar
[debug] [UiAutomator] Found jar name: 'AppiumBootstrap.jar'
[debug] [ADB] Running '/home/svt/Android/Sdk/platform-tools/adb -P 5037 -s 1215fca550e13604 push /tmp/.mount_appiumNYeccR/app/resources/app/node_modules/appium/node_modules/appium-android-driver/bootstrap/bin/AppiumBootstrap.jar /data/local/tmp/'
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Running '/home/svt/Android/Sdk/platform-tools/adb -P 5037 -s 1215fca550e13604 shell ps'[info] [ADB] No uiautomator process found to kill, continuing...
[debug] [UiAutomator] Starting UIAutomator
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","1215fca550e13604","shell","uiautomator","runtest","AppiumBootstrap.jar","-c","io.appium.android.bootstrap.Bootstrap","-e","pkg","com.samsung.android.contacts","-e","disableAndroidWatchers",false,"-e","acceptSslCerts",false][debug] [UiAutomator] Moving to state 'online'
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Registered crash watchers.
[info] [AndroidBootstrap] Android bootstrap socket is now connected
[debug] [ADB] Running '/home/svt/Android/Sdk/platform-tools/adb -P 5037 -s 1215fca550e13604 shell dumpsys window'
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Client connected
[info] [AndroidDriver] Screen already unlocked, doing nothing
[debug] [ADB] Device API level: 24
[debug] [ADB] Running '/home/svt/Android/Sdk/platform-tools/adb -P 5037 -s 1215fca550e13604 shell am start -W -n com.samsung.android.contacts/com.android.dialer.DialtactsActivity -S'[info] [Appium] New AndroidDriver session created successfully, session 3c6944dd-f9a5-4702-b810-d7c51a9839dd added to master session list
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1540143652706 (10:40:52 GMT-0700 (PDT))
[debug] [W3C] Cached the protocol value 'W3C' for the new session 3c6944dd-f9a5-4702-b810-d7c51a9839dd
[debug] [W3C] Responding to client with driver.createSession() result: {"capabilities":{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"android","appActivity":"com.android.dialer.DialtactsActivity","appPackage":"com.samsung.android.contacts","noReset":true,"BROWSER_NAME":"Android","VERSION":"7.0","deviceName":"G890A"},"platformName":"android","appActivity":"com.android.dialer.DialtactsActivity","appPackage":"com.samsung.android.contacts","noReset":true,"BROWSER_NAME":"Android","VERSION":"7.0","deviceName":"1215fca550e13604","deviceUDID":"1215fca550e13604","platformVersion":"7.0","deviceScreenSize":"1440x2560","deviceModel":"SAMSUNG-SM-G890A","deviceManufacturer":"samsung"}}
[info] [HTTP] <-- POST /wd/hub/session 200 11343 ms - 845
[info] [HTTP] [warn] [BaseDriver] Shutting down because we waited 60 seconds for a command
[debug] [AndroidDriver] Shutting down Android driver
[debug] [ADB] Running '/home/svt/Android/Sdk/platform-tools/adb -P 5037 -s 1215fca550e13604 shell am force-stop com.samsung.android.contacts'
[warn] [Appium] Closing session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
[info] [Appium] Removing session 3c6944dd-f9a5-4702-b810-d7c51a9839dd from our master session list[debug] [ADB] Pressing the HOME button
[debug] [ADB] Running '/home/svt/Android/Sdk/platform-tools/adb -P 5037 -s 1215fca550e13604 shell input keyevent 3'[debug] [AndroidBootstrap] Sending command to android: {"cmd":"shutdown"}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"shutdown"}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type SHUTDOWN
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Closed client connection
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: numtests=1
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: stream=.
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: current=1
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [UiAutomator] Shutting down UiAutomator
[debug] [UiAutomator] Moving to state 'stopping'
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS_CODE: 0
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: stream=
[debug] [AndroidBootstrap] [UIAUTO STDOUT] Test results for WatcherResultPrinter=.
[debug] [AndroidBootstrap] [UIAUTO STDOUT] Time: 63.319
[debug] [AndroidBootstrap] [UIAUTO STDOUT] OK (1 test)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS_CODE: -1
[debug] [UiAutomator] UiAutomator shut down normally
[debug] [UiAutomator] Moving to state 'stopped'

**Comment by mykola-mokhnach** [comment]
Please report the problem to https://github.com/appium/appium-desktop

**Comment by hsafari** [comment]
@mykola-mokhnach    Hi, When I use Appium desktop, everything works well. These errors happen only when I attempt to run a Java code from eclips. Do you still think its Desktop issue?

**Comment by mykola-mokhnach** [comment]
> Appium Desktop error :
> : Could not parse W3C capabilities: 'deviceName' can't be blank

You write it yourself.

Also, I don't observe any explicit errors in the attached log. The session is closed because of the timeout:

> [warn] [Appium] Closing session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'

**Comment by hsafari** [comment]
That timeout was not issue. I am looking for the issue at the beginning of the file. For example  why it shows :
[info] [Appium] Could not parse W3C capabilities: 'deviceName' can't be blank
[info] [Appium] Trying to fix W3C capabilities by merging them with JSONWP caps
[warn] [BaseDriver] The capabilities ["appActivity","appPackage","noReset","BROWSER_NAME","VERSION","deviceName"] are not standard capabilities and should have an extension prefix

**Comment by mykola-mokhnach** [comment]
These are just warnings. They don't break the session. Also, make sure your client is up to date

**Comment by hsafari** [comment]
Its good to know. Thanks. Since some the functions in my Java code such as " By.id().Click()" does not show any reaction on the phone screen, I thought its because of these warning. Just one quick question please: What do you mean by client is up to date? Do you mean I have to update something on the real phone?

**Comment by hsafari** [comment]
Its already updated. Thank you very much for your quick responses. I'll try to troubleshoot the issue in the libraries.

**Comment by chauminhnhut90** [comment]
Same issue to me. Always work on Appium Desktop but java code

**Comment by ando0689** [comment]
I have the same issue, what prefix is it talking about?
