### ISSUE TITLE
Slow parallel iOS real device session creation

### ISSUE THREAD

**Issue by jumois** [appium/appium#11551]
## The problem
Starting client sessions simultaneously on multiple real iOS devices is very time consuming. 

I have up to 5-10 real iOS devices connected to one Appium server. I start simultaneously each client session on all test devices. This takes a long time and with default capabilities Appium begins to destroy first sessions before all are started.

I'm observing that the app under test is deployed and launched synchronously. Same is for the WebDriverAgentRunner app. Could Appium handle deployment of apps asynchronously?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: macOS High Sierra 10.13.6 
* Node.js version (unless using Appium.app|exe): v10.11.0
* Mobile platform/version under test: iOS 11.4.1
* Real device or emulator/simulator: Multiple (4-10) real devices
* Appium CLI or Appium.app|exe: CLI

**Comment by mykola-mokhnach** [comment]
Closing it for now. Will reopen if there are any concrete proposals for improvement

**Comment by jumois** [comment]
I'm now using "webDriverAgentUrl" capability to connect to already open WDA session. This helps to speed up my test device setup between test suites.

I keep track of WDA port assignments and if WDA responds in this port, I set the "webDriverAgentUrl" in the device capabilities.

**Comment by mykola-mokhnach** [comment]
This is what the driver is also doing on its own: https://github.com/appium/appium-xcuitest-driver/blob/3a85140ac710604e89932b01ac3619e4825e00c1/lib/driver.js#L459
