### ISSUE TITLE
Encountered internal error running command: Error: An error occurred with appium 1.8.1 ios 11.4 and xcode 9.4 

### ISSUE THREAD

**Issue by helenren** [appium/appium#11550]
## The problem

During my test, randomly hit this issue with different commands, like switch context, find element, find session, etc.

19:36:15 2018-10-19 02:36:16:296 - [HTTP] --> GET /wd/hub/session/83618108-1851-4536-a129-1ed204e84ec8
19:36:15 2018-10-19 02:36:16:296 - [HTTP] {}
19:36:15 2018-10-19 02:36:16:320 - [MJSONWP] Encountered internal error running command: Error: An error occurred
19:36:15 2018-10-19 02:36:16:320 - [MJSONWP]     at JWProxy.command$ (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:176:15)
19:36:15 2018-10-19 02:36:16:320 - [MJSONWP]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
19:36:15 2018-10-19 02:36:16:320 - [MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
19:36:15 2018-10-19 02:36:16:320 - [MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
19:36:15 2018-10-19 02:36:16:321 - [MJSONWP]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
19:36:15 Test Method resides in com.salesforce.mobiletest.test.gatekeeper.SanityTest
19:36:15 Test Status: Fail
19:36:15 2018-10-19 02:36:16:321 - [HTTP] <-- GET /wd/hub/session/83618108-1851-4536-a129-1ed204e84ec8 500 25 ms - 188

another repro:

19:17:00 2018-10-19 02:17:01:173 - [HTTP] --> GET /wd/hub/session/65e04280-0a91-4aa0-9916-a2381fcd9c17/title
19:17:00 2018-10-19 02:17:01:173 - [HTTP] {}
19:17:00 2018-10-19 02:17:01:192 - [MJSONWP] Encountered internal error running command: Error: appIdKey
19:17:00 2018-10-19 02:17:01:192 - [MJSONWP]     at RemoteDebugger.execute$ (/usr/local/lib/node_modules/appium/node_modules/appium-remote-debugger/build/lib/remote-debugger.js:1456:19)
19:17:00 2018-10-19 02:17:01:192 - [MJSONWP]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
19:17:00 2018-10-19 02:17:01:193 - [MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
19:17:00 2018-10-19 02:17:01:193 - [MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
19:17:00 2018-10-19 02:17:01:193 - [MJSONWP]     at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
19:17:00 2018-10-19 02:17:01:196 - [MJSONWP]     at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
19:17:00 2018-10-19 02:17:01:197 - [MJSONWP]     at new Promise (<anonymous>)
19:17:00 2018-10-19 02:17:01:197 - [MJSONWP]     at new F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
19:17:00 2018-10-19 02:17:01:198 - [MJSONWP]     at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
19:17:00 2018-10-19 02:17:01:199 - [MJSONWP]     at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
19:17:00 2018-10-19 02:17:01:199 - [MJSONWP]     at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
19:17:00 2018-10-19 02:17:01:200 - [MJSONWP]     at RemoteDebugger.execute (/usr/local/lib/node_modules/appium/node_modules/appium-remote-debugger/build/lib/remote-debugger.js:1431:34)
19:17:00 2018-10-19 02:17:01:200 - [MJSONWP]     at RemoteDebugger.executeAtom$ (/usr/local/lib/node_modules/appium/node_modules/appium-remote-debugger/build/lib/remote-debugger.js:926:51)
19:17:00 2018-10-19 02:17:01:201 - [MJSONWP]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
19:17:00 2018-10-19 02:17:01:201 - [MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
19:17:00 2018-10-19 02:17:01:202 - [MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
19:17:00 2018-10-19 02:17:01:202 - [MJSONWP]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
19:17:00 2018-10-19 02:17:01:207 - [HTTP] <-- GET /wd/hub/session/65e04280-0a91-4aa0-9916-a2381fcd9c17/title 500 31 ms - 179

## Environment

* Appium version: 1.8.1
* Desktop OS/version used to run Appium: macOS High Sierra: 10.13.6
* Node.js version (unless using Appium.app|exe): v10.12
* Mobile platform/version under test: ios 11.4, xcode 9.4
* Real device or emulator/simulator: simulator

**Comment by mykola-mokhnach** [comment]
Please try the most recent appium version first or appium@beta

**Comment by vsadineni1** [comment]
I have the latest appium beta: Appium v1.9.2-beta.2. The session **creation failed**.

I have shared the logs:
Appium Server Log: https://gist.github.com/vsadineni1/9e7ee6f0fd9c676e59dc79c4fa3a4c96
Test failure Exception: https://gist.github.com/vsadineni1/a1a36fe1e942ba5f703b11f51068c11b
