### ISSUE TITLE
org.openqa.selenium.NoSuchElementException: Can't locate an element by this strategy: By.chained({By.className: android.widget.Button})

### ISSUE THREAD

**Issue by irfanpace** [appium/appium#11567]
## The problem
**I have an element which is not working in mac os** the seme element which is working in Windows OS, with the same versions of  appium, selenium

below is my code

{
	OnBoardingElements(AppiumDriver driver)
	 {
	   PageFactory.initElements(new AppiumFieldDecorator(driver), this); 
	 }
	
	@AndroidFindBy(id = "com.karwatechnologies.karwataxi:id/intro_btn_skip") 
	public MobileElement skip;
	
	@FindBy(id = "com.karwatechnologies.karwataxi:id/intro_btn_skip")
	public MobileElement sskip;
	
	@AndroidFindBy(className = "android.widget.Button")
	public MobileElement clsskip;
}

I tried with all the elements, none of the elements is working, all throw the same error

## Environment

appium version: 1.9.1
Mac os : 10.14
Real android device : ver: 7.0 (motto XT)
selenium : 3.11
java-cleint : 6.0.0 BETA1

## Link to Appium logs - eclipse logs

org.openqa.selenium.NoSuchElementException: Can't locate an element by this strategy: By.chained({By.className: android.widget.Button})
	at io.appium.java_client.pagefactory.AppiumElementLocator.findElement(AppiumElementLocator.java:126)
	at io.appium.java_client.pagefactory.interceptors.InterceptorOfASingleElement.intercept(InterceptorOfASingleElement.java:61)
	at io.appium.java_client.android.AndroidElement$$EnhancerByCGLIB$$b598166c.click(<generated>)
	at KarwaApp.TaxiBookingAndroid.OnBoardingTestCases.onBoarding(OnBoardingTestCases.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)

## Code To Reproduce Issue [ Good To Have ]

**Elements**
public class OnBoardingElements 
{
	OnBoardingElements(AppiumDriver driver)
	 {
	   PageFactory.initElements(new AppiumFieldDecorator(driver), this); 
	 }
	
	@AndroidFindBy(id = "com.karwatechnologies.karwataxi:id/intro_btn_skip") 
	public MobileElement skip;
	
	@FindBy(id = "com.karwatechnologies.karwataxi:id/intro_btn_skip")
	public MobileElement sskip;
	
	@AndroidFindBy(className = "android.widget.Button")
	public MobileElement clsskip;
	
	@AndroidFindBy(id = "com.karwatechnologies.karwataxi:id/intro_btn_next")
	public MobileElement next;	
	
	@AndroidFindBy(id = "com.karwatechnologies.karwataxi:id/intro_btn_finish")
	public MobileElement finish;
}

**TEST CASE:**
public class OnBoardingTestCases 
{
	AndroidDriver<AndroidElement> driver;
	//Installation of Application
	
	@BeforeClass()
	public void setup() throws MalformedURLException, InterruptedException
	{
		SerDesiredCapabilities sdc = new SerDesiredCapabilities();
		driver = sdc.SetupDC();
		Thread.sleep(5000);			
	}
	
	@Test()
	public void onBoarding() throws InterruptedException
	{
		OnBoardingElements obe = new OnBoardingElements(driver);
		{
			obe.clsskip.click();			
		}
	}

Please have a look

**Comment by mykola-mokhnach** [comment]
Please attach full server log.

Is the destination element present in page source?

**Comment by irfanpace** [comment]
**Attaching the Both the Logs as below:

Yes, all the Elements is present in the page source, As I said you same elements work good with appium with windows OS, have an issue with Mac oS**


[AppiumLog.txt](https://github.com/appium/appium/files/2509004/AppiumLog.txt)
[EclipsIDEErrorLogs.txt](https://github.com/appium/appium/files/2509006/EclipsIDEErrorLogs.txt)

**Comment by mykola-mokhnach** [comment]
This is the problem of outdated client library.

Closed as duplicate: https://github.com/appium/appium/search?q=%22Locator+Strategy+%27css+selector%27+is+not+supported+for+this+session%22&type=Issues
