### ISSUE TITLE
Appium inspector is not capable of fetching react native  animated button for iOS

### ISSUE THREAD

**Issue by neerajkumar-lad** [appium/appium#11564]
## The problem

In my React Native app, There is one animated button which visible after once swipe (bottom to top swipe). I have set with a developer and he set testID and accessibilityLabel. When I opened the appium inspector and try to get the animated button object property then found that that animated button is not present in the XML. I copied the XML and pasted in the notepad and try to find that object but failed to find it. 

I even tried with Macaca app inspector, there also a button is not present. 

**_Note: UIAutomator can indentify the same button._** 
## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.2-beta.2
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Mac High Sierra 10.13.6
* Node.js version (unless using Appium.app|exe): v8.9.4
* Mobile platform/version under test: iOS iPhone 7 ( v12.0)
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI

## Details

N/A

## Link to Appium logs

N/A

## Code To Reproduce Issue [ Good To Have ]

No code is required to reproduce this issue 

Application: download the curefit app (https://itunes.apple.com/us/app/cure-fit/id1217794588)

Steps to reproduce:
- Click the Skip button
- Click the 'X' button present on login screen
- Navigate to 'eat.fit' tab >> tap on 'Subscribe' menu
- A User will see Weekly and Monthly widget 
- Swipe down once and 'Subscribe' button will visible
- Now, try to identify the Subscribe button which visible when user swipe

Open Appium inspector and copy the XML and try to find the object (Subscribe)

**Comment by mykola-mokhnach** [comment]
Please report the problem to https://github.com/facebook/WebDriverAgent as there is nothing to do there on Appium side. 

Also, you could try switching to webview context.
