### ISSUE TITLE
Maximum length exception in Id

### ISSUE THREAD

**Issue by sebinjqburst** [appium/appium#11569]
## The problem

I have an element with the name having a length of more than 128 characters and the same returns exception invalid query.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.2-beta2
* Last Appium version that did not exhibit the issue (if applicable): 1.8.0
* Desktop OS/version used to run Appium: MacOS High Sierra
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 12
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Link to Appium logs

[debug] [W3C (959616d5)] Calling AppiumDriver.findElements() with args: ["id","ETT    Intubation       Process Notes    ￼          Vent : No Mask Vent       Outcome Notes          No Complications : Positive ETCO2          Complications : Lip Injury    Extubation/Emergence       Process Notes          Sustained Tetanus       Outcome Notes          No Complications : Eyes Open          Complications : Aspiration","959616d5-bf16-44bd-9945-65ba9af87b4a"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Matched '/elements' to command name 'findElements'
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/B1EEF6BB-1BF8-4A68-ABBD-FCF97D557BFB/elements] with body: {"using":"id","value":"ETT    Intubation       Process Notes    ￼          Vent : No Mask Vent       Outcome Notes          No Complications : Positive ETCO2          Complications : Lip Injury    Extubation/Emergence       Process Notes          Sustained Tetanus       Outcome Notes          No Complications : Eyes Open          Complications : Aspiration"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Invalid query - string identifier 'ETT    Intubation       Process Notes    ￼          Vent : No Mask Vent       Outcome Notes          No Complications : Positive ETCO2          Complications : Lip Injury    Extubation/Emergence       Process Notes          Sustained Tetanus       Outcome Notes          No Complications : Eyes Open          Complications : Aspiration' exceeds maximum length of 128 characters. You can work around this limitation by constructing a query with a custom NSPredicate that specifies the property (label, title, value, placeholderValue, or identifier) to match against.\n\n(\n\t0   CoreFoundation                      0x00000001fd086f10 <redacted> + 252\n\t1   libobjc.A.dylib                     0x00000001fc254a40 objc_exception_throw + 56\n\t2   CoreFoundation                      0x00000001fcf9b06c <redacted> + 0\n\t3   Foundation                          0x00000001fda873e0 <redacted> + 112\n\t4   XCTest                              0x0000000101136fa4 -[XCUIElementQuery _...

**Comment by mykola-mokhnach** [comment]
> Aspiration' exceeds maximum length of 128 characters. You can work around this limitation by constructing a query with a custom NSPredicate that specifies the property (label, title, value, placeholderValue, or identifier) to match against

As you can see there it is a limitation of NSPredicate class. You should either change the query, for example use CONTAINS instead of exact match or try another locator (xpath is slower, but would be probably ok for this particular case). Closed as third party issue

**Comment by sebinjqburst** [comment]
@mykola-mokhnach Thank you! _Contains_ worked for me :-)
