### ISSUE TITLE
Appium server version and Feature version

### ISSUE THREAD

**Issue by vishnu1262** [appium/appium#11575]
Can any one help me to understand. What's the difference between Appium server version and Feature version.

![appium version 1](https://user-images.githubusercontent.com/27680923/47481221-8aa73f80-d850-11e8-84c7-dbd7161a739c.png)

![appium version](https://user-images.githubusercontent.com/27680923/47481283-bb877480-d850-11e8-87b8-2526a439a97c.png)

**Comment by mykola-mokhnach** [comment]
Please use Appium forum to ask questions.

**Comment by imurchie** [comment]
The server version and the desktop GUI version are entirely different. They have different release schedules. You can see the releases on the [appium-desktop](https://github.com/appium/appium-desktop/releases) repository. Where a version of the GUI corresponds with a version of the server, it will have something along the lines of `Feature: Upgrade to Appium 1.9.1` in its change set.
