### ISSUE TITLE
TouchAction not working with UIAutomator2 Automation

### ISSUE THREAD

**Issue by SharmaKKamal** [appium/appium#11570]
## The problem

TouchAction methods are not working with UIAutomator2 automation approach. However same code work with UIAutomator/Appium automation approach to move to targeted element

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS HighSierra 13.10.6
* Node.js version (unless using Appium.app|exe): 10.10.0
* Mobile platform/version under test: Google Pixel 2
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: CLI

## Details

Performing touch action not move to targeted elements in Number Picker for Android Platform

## Link to Appium logs
https://gist.github.com/SharmaKKamal/5fa4d66786516728bfe22524372677fc

## Code To Reproduce Issue [ Good To Have ]
new TouchAction<>(driver).press(PointOption.point(desiredElMidX, currentElement.getLocation().getY()))
				.waitAction(WaitOptions.waitOptions(Duration.ofMillis(1000)))
				.moveTo(PointOption.point(desiredElMidX, desiredElMidY))
				.release().perform();

**Comment by mykola-mokhnach** [comment]
Double check the coordinates passed to the touch action. Otherwise I don't observe any touch action issues in the attached log

**Comment by SharmaKKamal** [comment]
Is there any difference between coordinates for UIAutomator2 and UIAutomator.
As this sample code working fine for UIAutomator.
With UIAutomator2 it is not throwing any error but no action performed on the device

**Comment by mykola-mokhnach** [comment]
I cannot say what the difference is. You could also try W3C actions as an alternative: https://appiumpro.com/editions/29

**Comment by SharmaKKamal** [comment]
@mykola-mokhnach thanks

Resolved by using absolute coordinate

closing the issue
