### ISSUE TITLE
unable to clear the textfield 

### ISSUE THREAD

**Issue by LayMuiToh** [appium/appium#11576]
When I use the iOS Simulator to automate the app, it could not clear the textfield
the new text becomes appended to the existing text

* Appium version (or git revision) that exhibits the issue:1.9.1
* Last Appium version that did not exhibit the issue (if applicable):NA
* Desktop OS/version used to run Appium: macOS 10.13.1
* Node.js version (unless using Appium.app|exe): exe
* Mobile platform/version under test:10.3.1
* Real device or emulator/simulator:iOS simulator iPad (5th generation)
* Appium CLI or Appium.app|exe: exe

 await driver.elementByAccessibilityId('textUserName').click();
 await driver.elementByAccessibilityId('textUserName').clear();

**Comment by mykola-mokhnach** [comment]
Please report the issue to https://github.com/facebook/WebDriverAgent
