### ISSUE TITLE
TouchActions not working in IOS 12 with appium versions 1.7.2 above

### ISSUE THREAD

**Issue by Bhagyacse** [appium/appium#11571]
## The problem

I have upgraded my Mac ,Xcode and IOS versions to latest. Mac- 10.13.6, Xcode-10 , appium - 1.9.1, IOS - 12.0.1
I am not able to swipe on the IOS device with these upgrades. Touch is not performing . Upgraded Java-client to 6.1.0 . 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable):1.7.1
* Desktop OS/version used to run Appium: Source code
* Node.js version (unless using Appium.app|exe):6.1.0
* Mobile platform/version under test:IOS 12.0.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: 

## Details

Please suggest the working versions for IOS 12 to avoid this swipe issue. I have tried with all the version combinations. I don't see any error in appium log while trying to swipe. But it is not swiping on Native_App in IOS.

## Code To Reproduce Issue [ Good To Have ]

Code:

TouchAction swipe2 = new TouchAction(driver)
			                .press(PointOption.point(hsx, hsy))
			                .waitAction(waitOptions(ofSeconds(10)))
			                .moveTo(PointOption.point(-300,0))
			                .release();//307,0
			        swipe2.perform();

**Comment by mykola-mokhnach** [comment]
If you say there are no errors in the log then I don't think there is anything more to suggest there. Try to experiment with different action argument values

**Comment by mykola-mokhnach** [comment]
Closed as inactive

**Comment by JasonBarile-Tableau** [comment]
FWIW, we're seeing a similar problem. We also don't see any errors in the logs, but scrolling just doesn't seem to happen using the same combination of press, moveTo, release that works with iOS 11.

**Comment by Bhagyacse** [comment]
Jason- I found an alternative way to swipe for this issue. But however I still have challenge for swiping little or to some point. For a workaround you can use the below approach for swiping up, down,left,right.
	Map<String, Object> args = new HashMap<>();
					args.put("direction", "right");
					driver.executeScript("mobile: swipe", args);

**Comment by manishboricha** [comment]
@Bhagyacse : 
Hope this helps because its working fine for me

Appium : 1.9.1
Device : iPhone X - 11.4.1
io.appium - 6.1.0

https://medium.com/@manishboricha308/swipe-doesnt-work-on-appium-1-9-1-40fe80a2cd9d
