### ISSUE TITLE
Strange problem concerning adb and appium

### ISSUE THREAD

**Issue by edubrusch** [appium/appium#11572]
## The problem

Hi there thanks for the attention in advance.

The problem I face is that all of the sudden (from one build to another) the adb install command fails. when I take a look at it, it's putting an extra slash in the path, like so:

`
An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C\:\\dev_tools\\Android\\android-sdk-windows\\platform-tools\\adb.exe -P 5037 -s emulator-5554 install C\:\\EBRUSCH_WORKSPACE\\TESTES\\Automacao\\git\\mb-unicred-TFS\\android\\mb-unicred-mobile-android-automation\\app-homolog.apk' timed out after 120ms'; Stderr: ''; Code: 'null' (WARNING: The server did not provide any stacktrace information)`

Please notice in the path there's this thing  `C\:\\` which completely invalidate the path, probably causing the problem.

On my CI server I have a similar message:

`
An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/Users/jenkins/android-sdk/platform-tools/adb -P 5037 -s emulator-5554 install -g /Users/jenkins/app/app-homolog.apk' timed out after 120ms'; Stderr: ''; Code: 'null' (WARNING: The server did not provide any stacktrace information)`

I have tried three approaches:

1. Direct absolute path:

**pom.xml**
```
<profiles>
  		<profile>
  			<id>local</id>
  			<properties>    		
    			<testEnv>local</testEnv>
    			<reportDir>C:/EBRUSCH_WORKSPACE/resultado_teste_automatizado/local/</reportDir>
    			<debugOutput>true</debugOutput>
    			<testSuite>fullsuite2.xml</testSuite>
    			<localHub>127.0.0.1:4723</localHub>
    			<installApp>true</installApp>
    			<appInstallDir>C:\\EBRUSCH_WORKSPACE\\TESTES\\APP\\4.11\\app-homolog.apk</appInstallDir>    
    			<deviceName>emulator-5554</deviceName>
</properties>
</profile>
```

the class in which i describe the device:
```

public static DesiredCapabilities nextInstallAppLocal() {
		
		DesiredCapabilities capabilities = new DesiredCapabilities();		
		
		capabilities.setCapability("deviceName", "emulator-5554");		
		capabilities.setCapability("platformVersion", "6.0");
		capabilities.setCapability("platformName", "Android");
		capabilities.setCapability("autoGrantPermissions", true);		

		capabilities.setCapability("androidInstallTimeout", "120");
		capabilities.setCapability("appWaitDuration", "30");
		capabilities.setCapability("deviceReadyTimeout", "30");
		capabilities.setCapability("newCommandTimeout", "120");		
		capabilities.setCapability("no-reset", "true");
		capabilities.setCapability("full-reset", "False");
		capabilities.setCapability("apiKey", "4a46b62e84f942e7b6d4eed8f31556e9");	
		
		
		capabilities.setCapability("appWaitActivity", "br.com.unicredmobile.LoginActivity");
		capabilities.setCapability("app", System.getProperty("app.location"));		
		
		return capabilities;
	}
```
2. Creating a file:

```
File apk = new File(System.getProperty("app.location"));		
		
		System.out.println(apk.getAbsolutePath()+"\n\n\tcanread ==> "+apk.canRead());
		
		DesiredCapabilities capabilities = new DesiredCapabilities();		
		
		capabilities.setCapability("deviceName", "emulator-5554");		
		capabilities.setCapability("platformVersion", "6.0");
		capabilities.setCapability("platformName", "Android");
		capabilities.setCapability("autoGrantPermissions", true);
		capabilities.setCapability("androidInstallTimeout", "120");
		capabilities.setCapability("appWaitDuration", "120");
		capabilities.setCapability("deviceReadyTimeout", "30");
		capabilities.setCapability("newCommandTimeout", "120");		
		//capabilities.setCapability("fullReset", true);
		capabilities.setCapability("apiKey", "4a46b62e84f942e7b6d4eed8f31556e9");	
		
		
		capabilities.setCapability("appWaitActivity", "br.com.unicredmobile.LoginActivity");
		capabilities.setCapability("app", apk.getAbsolutePath());	
```

3. downloading from the CI which creates it (from stackoverflow)

```
try {
			File apk = new File("app-homolog.apk");
			
			FileUtils.copyURLToFile(
					new URL("https://jenkins-arq.e-unicred.com.br/job/UnicredMobile/job/mb-unicred-mobile-android-piloto-A/lastSuccessfulBuild/artifact/app/build/outputs/apk/homolog/app-homolog.apk"),
					apk);
			
			System.out.println(apk.getAbsolutePath()+"\n\n\tcanread ==> "+apk.canRead());
			
			DesiredCapabilities capabilities = new DesiredCapabilities();		
			capabilities.setCapability("deviceName", "emulator-5554");		
			capabilities.setCapability("platformVersion", "6.0");
			capabilities.setCapability("platformName", "Android");
			//capabilities.setCapability("autoGrantPermissions", true);
			capabilities.setCapability("androidInstallTimeout", "120");
			capabilities.setCapability("appWaitDuration", "30");
			capabilities.setCapability("deviceReadyTimeout", "30");
			capabilities.setCapability("newCommandTimeout", "120");		
			//capabilities.setCapability("full-reset", "true");
			capabilities.setCapability("apiKey", "4a46b62e84f942e7b6d4eed8f31556e9");	
			
			
			capabilities.setCapability("appWaitActivity", "br.com.unicredmobile.LoginActivity");
			capabilities.setCapability("app", apk.getAbsolutePath());
			
			return capabilities;
			
		} catch (MalformedURLException e) {
			throw new RuntimeException("URL do apk está incorreta", e);			
		} catch (IOException e) {			
			throw new RuntimeException("Erro ao manupular arquivo apk salvo em disco.", e);
		}
```

I have the same result regardless of the method I tried.

I tried looking in this site for a solution without success, so I thought it would be reasonable to ask if you guys saw this before.

I appreciate your time and if I found a bug I'd would be glad.

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium UI running on windows 10 version 1.6.2 on my machine and 1.9.x on the CI server (mac mini with MAC OS High Sierra 10.13)
* Running maven 3.5.4 in both systems 
* Jenkins ver. 2.121.2
* Running using Java compliance 1.7 compiled in the 1.8 JDK
* Appium java-client dependency version 4.1.2
* Selenium-java version 3.4.0
* Simulating using emulator with android 6 (api 23)

## Link to Appium logs

CI logs (MAC mini):
https://gist.github.com/edubrusch/e053ea636c77dd5030668456fbc1b417

Local logs:
https://gist.github.com/edubrusch/9cdab5a9ef9ae02416b4d0935cd5dc63

## Code To Reproduce Issue [ Good To Have ]
About the code I'm really sorry but I'm not able to share it due to legal reasons. if this problem goes every so further I can try and make a pet project with no legal coverage. and see if it reproduces.

**Comment by mykola-mokhnach** [comment]
I think the problem there is that androidInstallTimeout is expected to be in milliseconds and not in seconds, so the command simply times out unexpectedly. Double check the measurement units for your capability values

**Comment by edubrusch** [comment]
Hi mykola-mokhnach thanks a lot for your reply!

I took a look at the documentation and indeed:
http://appium.io/docs/en/writing-running-appium/caps/

androidInstallTimeout => **milliseconds**
appWaitDuration => **milliseconds**
deviceReadyTimeout => **seconds**
newCommandTimeout => **seconds**

That's the confusion. Timing also explains the "suddenness".
After I properly configured the capabilities it worked.

I'll just comment if you want to do something else before closing.

Thanks a lot.
