### ISSUE TITLE
fail to find an element byname on native app appium 1.9.1

### ISSUE THREAD

**Issue by helenren** [appium/appium#11574]
## The problem

On a native page, my test tries to find an element via byname: command passed into driver is: findElement(By.name: EULA.agree), while I saw the command executed to the appium server is:

2018-10-25 03:23:24:329 - info: [HTTP] --> POST /wd/hub/session/22bd911d-ed10-47f6-bd77-f327b5562c48/elements
2018-10-25 03:23:24:329 - info: [HTTP] {"value":"*[name='EULA.agree']","using":"css selector"}

The same test works fine against appium 1.8.1

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable): 1.8.1
* Desktop OS/version used to run Appium: xcode 9.4.1, mac os version: 10.13.6
* Node.js version (unless using Appium.app|exe):v7.1.0
* Mobile platform/version under test: ios 9.4/9.2
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe:

**Comment by KazuCocoa** [comment]
What client and the version did you use?
This should be client versions issue like https://github.com/appium/appium/issues/11410

If the issue happens even you use the latest client, could you create this issue in the client repository?

**Comment by helenren** [comment]
we used java client and the version is 5.0.4.

**Comment by KazuCocoa** [comment]
5.x has the issue. Please try out 6.x
