### ISSUE TITLE
[Android/JAVA/MacOS] - org.openqa.selenium.InvalidSelectorException: Locator Strategy 'css selector' is not supported for this session

### ISSUE THREAD

**Issue by Ajitpatil3011** [appium/appium#11589]
## The problem

I am new to Mobile automation, I am getting an error "org.openqa.selenium.InvalidSelectorException: Locator Strategy 'css selector' is not supported for this session" while accessing elements on Android 8.0, the same code is running on Windows but for os X and Appium 1.8.0 it is throwing an error.
I checked existing issue's there was one same issue but it was for Python, I did not understood how to solve this for JAVA. Please help me to solve this issue
 
## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: Mac OS X 10.13.6
* Node.js version (unless using Appium.app|exe): v7.9.0
* Mobile platform/version under test: Android 8.0
* Real device or emulator/simulator: Sony G3116
* Appium CLI or Appium.app|exe: Appium App

## Details

![screen shot 2018-10-29 at 12 44 07 pm](https://user-images.githubusercontent.com/42935945/47635696-f1dc3100-db7b-11e8-9eba-9ca19ce4f405.png)
![screen shot 2018-10-29 at 12 30 41 pm](https://user-images.githubusercontent.com/42935945/47635716-091b1e80-db7c-11e8-8601-0ce7cd4d07ee.png)

## Link to Appium logs

<script src="https://gist.github.com/Ajitpatil3011/4b6a3b01c7074b32c0aa20aef846a342.js"></script>

## Code To Reproduce Issue [ Good To Have ]

![screen shot 2018-10-29 at 12 44 07 pm](https://user-images.githubusercontent.com/42935945/47635817-4ed7e700-db7c-11e8-86de-df1d7d9647e1.png)

**Comment by mykola-mokhnach** [comment]
Kindly use search: https://github.com/appium/appium/search?q=%22Locator+Strategy+%27css+selector%27+is+not+supported+for+this+session%22&type=Issues

Closed as duplicate
