### ISSUE TITLE
android genymotion execution stalls without any timeouts 

### ISSUE THREAD

**Issue by vikramvi** [appium/appium#11588]
## The problem

- Since last few days, I'm seeing this really weird issue
- Test suite execution is stalling and no timeout happens as well
- [appium server log ](https://gist.github.com/vikramvi/dff50f7e0ddb458c4d7f7d6407ed5390)

## Environment

* Appium version (or git revision) that exhibits the issue:  1.9.1
* Last Appium version that did not exhibit the issue (if applicable):  
* Desktop OS/version used to run Appium:  Mac  10.13.5
* Node.js version (unless using Appium.app|exe): v11.0.0
* Mobile platform/version under test:  Genymotion Emulator 
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: CLI

## Details

- I didn't see this issue last few weeks but suddenly from last 2-3 days it has started occurring
- I'm not sure if this is because of flaky internet ?  As I've shifted ISP
- But in this case appium server should complain or timeout isn't it 

## Link to Appium logs

- provided in the description

## Code To Reproduce Issue [ Good To Have ]

NA

**Comment by vikramvi** [comment]
@mykola-mokhnach please clarify why this issue is marked *ThirdParty* ?

**Comment by mykola-mokhnach** [comment]
Because you've mention that an unsupported NodeJS version is used. Please confirm the issue is reproducible with the supported one

**Comment by vikramvi** [comment]
@mykola-mokhnach  After downgrading node version to **v10.12.0**, this issue is no more reproducible.

where can I see `compatible version of node with appium` ?  Without this info, others as well will end up wasting lots of their time in debugging

**Comment by mykola-mokhnach** [comment]
The most recent appium versions do support two recent LTS Node versions as a rule (for now these are 8 and 10). I don't know where and if this is documented.

**Comment by vikramvi** [comment]
Thanks for clarification, I didn't know about LTS rule. Found out under https://github.com/nodejs/Release, for those who doesn't know like me jusy fyi..
