### ISSUE TITLE
Csharp test solutions not going through

### ISSUE THREAD

**Issue by eliassal** [appium/appium#11584]
## The problem

I downloaded the samples zip, opened the test.sln in visual studio 2017, updated nuget packages, projects compile, running any test, I get the following message:

[10/26/2018 7:08:25 PM Informational] Test project test does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
It's recommended to reference NuGet test adapters in each test project in the solution.
[10/26/2018 7:08:25 PM Informational] ========== Run test finished: 0 run (0:00:01.7409422) ==========

## Environment
Win 10 64bit, VS 2K17, .Net Framework 4.6.1
* Just installe Appium with npm
* win 10 64 bit:
* Node.js version v6.12.3
## Details

Tests cannot execute missing nuget test adapters

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/appium/appium-dotnet-driver

**Comment by eliassal** [comment]
so please reopen the issue

**Comment by mykola-mokhnach** [comment]
I assume these samples are simply not supported by anyone as we don't have resources for that

**Comment by eliassal** [comment]
I come from MS world and interested of testing win application or web application, so what are my options? No solution is working. I tried to follow also instructions on appium url
http://appium.io/docs/en/drivers/windows/index.html#create-test-project
C# Samples, always getting 

> Message: Test method CodedUIAppium.CodedUITest1.EditorEnterTextLocal threw exception:
> OpenQA.Selenium.WebDriverException: Unexpected error. The URL '/session' did not map to a valid resource

**Comment by akinsolb** [comment]
@eliassal This solution is targeting .Net 4.7, so ensure you have the .Net developer pack installed.

Secondly, in reference to your test run log message. Ensure you have the NUnit 3 Test Adapter extension installed into your Visual Studio instance by Selecting Tools > Extensions and Updates > Online > [search for 'Unit 3 Test Adapter'] and install. You will probably have to relaunch your visual studio instance for the extension to complete installation. 

Please confirm once you have this working so @mykola-mokhnach can close this.

**Comment by eliassal** [comment]
Thanks, I updated the project to target 4.7.1. Started appium from command line, di "Run All" in test explorer in visual studio. This is what is indicated on the project page, download VS, run all. I get

> [10/29/2018 5:47:16 PM Informational] ------ Discover test started ------
> [10/29/2018 5:47:19 PM Warning] No test is available in C:\Projects\01-A faire\appium-master\sample-code\csharp\test\test.csproj. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
> [10/29/2018 5:47:19 PM Informational] ========== Discover test finished: 0 found (0:00:02.9613958) ==========
> [10/29/2018 5:47:31 PM Informational] ------ Run test started ------
> [10/29/2018 5:47:34 PM Informational] ========== Run test finished: 0 run (0:00:02.3552468) ==========

So any other configuration missings?

**Comment by eliassal** [comment]
I forgot to mention that nUnit is 
nunit.framework  3.10.1.0

**Comment by akinsolb** [comment]
Have you also installed the NUnit3 Visual Studio Test adapter? I've forked this repo this morning and got test displaying and running. So let's find the differences between our workspace.

**Comment by akinsolb** [comment]
Btw, if you have an NUnit2 Visual Studio Test adapter, it will have to be disabled, as one or the other works at the same time.

**Comment by eliassal** [comment]
I have just followed your instructions and downloaded "Unit 3 Test Adapter' from extensions, closed VS reopened it but getting the same exact message.
I am not sure if there was version 2, how can I disable it,

**Comment by eliassal** [comment]
Appium Dotnet Driver    3.0.0.2
WebDriver     3.8.0.0
WebDriver.Support    3.8.0.0
nunit.framework    3.10.1.0


Appium v1.9.1

**Comment by akinsolb** [comment]
To check if you have an NUnit2 Test Adapter, you can follow the path  Tools > Extensions and Updates > Installed, and see if you have it installed.

**Comment by eliassal** [comment]
So do I need to download a new version as your indicated that you have forked!

**Comment by akinsolb** [comment]
I will make a PR

**Comment by eliassal** [comment]
Waiting for your instructions to proceed

**Comment by akinsolb** [comment]
@eliassal Once #11593 is merged. Please close all instances of Visual Studio, download the samples.zip file again and open the solution.

**Comment by eliassal** [comment]
Thanks for your help, when it will be merged?

**Comment by eliassal** [comment]
Akin, I downloaded another zip code at 
https://github.com/appium-boneyard/sample-code
>> appium-boneyard/sample-code 
Opening the solution AppiumDotNetSample, I am getting the same exact behavior, no test is discovered

> [10/29/2018 6:56:05 PM Informational] Executing test method 'Appium.Samples.iOS.iOSWebviewTest.GetPageTestCase'
> [10/29/2018 6:56:05 PM Informational] ------ Run test started ------
> [10/29/2018 6:56:06 PM Informational] NUnit Adapter 3.11.0.0: Test execution started
> [10/29/2018 6:56:06 PM Informational] Running all tests in C:\Projects\01-A faire\sample-code-master\sample-code\examples\dotnet\AppiumDotNetSample\bin\Debug\AppiumDotNetSample.dll
> [10/29/2018 6:56:06 PM Informational]    NUnit couldn't find any tests in C:\Projects\01-A faire\sample-code-master\sample-code\examples\dotnet\AppiumDotNetSample\bin\Debug\AppiumDotNetSample.dll
> [10/29/2018 6:56:06 PM Informational] NUnit Adapter 3.11.0.0: Test execution complete
> [10/29/2018 6:56:06 PM Warning] No test matches the given testcase filter `FullyQualifiedName=Appium.Samples.iOS.iOSWebviewTest.GetPageTestCase` in C:\Projects\01-A faire\sample-code-master\sample-code\examples\dotnet\AppiumDotNetSample\bin\Debug\AppiumDotNetSample.dll
> [10/29/2018 6:56:06 PM Informational] ========== Run test finished: 0 run (0:00:01.1436491) ==========
>

**Comment by eliassal** [comment]
One last question, should I install something for Android locally? I see that all sample codes test is directed for iOs, Android.......etc

**Comment by eliassal** [comment]
Hi Akin, any news?

**Comment by eliassal** [comment]
Akin, why it is closed? Does this mean that I it is merged and I can download the updated version?
