### ISSUE TITLE
appium installation with "npm install -g appium" throws lots of erros

### ISSUE THREAD

**Issue by vikramvi** [appium/appium#11587]
## The problem

- After completely uninstalling and trying to install latest stable version with command 
**npm install -g appium**
- Mac command line I could tons of [error messages](https://gist.github.com/vikramvi/a56f739aff1d45300469c70200a79803)
- I don't remember seeing this with earlier versions installation, please review

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable):  
* Desktop OS/version used to run Appium: Mac  10.13.5
* Node.js version (unless using Appium.app|exe):  v11.0.0
* Mobile platform/version under test: NA
* Real device or emulator/simulator: NA
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

NA

## Code To Reproduce Issue [ Good To Have ]

NA

**Comment by mykola-mokhnach** [comment]
Unfortunately not all modules used by Appium support NodeJS v11, nor we test it for compatibility. You must downgrade to v10 for now.

**Comment by mykola-mokhnach** [comment]
Yes it might be the same problem cause.

**Comment by ole-vegard** [comment]
Doesn't `npm install -g` require super user privileges? Which in turns makes the permissions so that appium can't modify some files it needs to? I've had tonnes of issues with this. 

 I ended up running `npm install appium` in `HOME` and then adding `$HOME/node_modules/.bin` to `PATH`

**Comment by vikramvi** [comment]
@ole-vegard no, it doesn't need super user permissions. Never ever use **sudo** while installation global packages

**Comment by ole-vegard** [comment]
I've never been able to make it work without `sudo`. Though I guess it could be because I was using an older version of `npm`?

**Comment by vikramvi** [comment]
@mykola-mokhnach  I've installed node version 10 

node -v
v10.12.0

But I'm still getting [errors](https://gist.github.com/vikramvi/8cefb005fdfcaaa70e368ff0833004f0) during appium installation 

I've do complete node uninstallation as linking to older node was not working on Mac 10.13.5

- https://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x

Later have installed older version 

- https://stackoverflow.com/questions/53043476/installing-particular-version-of-node-with-homebrew-is-giving-error

**Comment by mykola-mokhnach** [comment]
The heapdump is an optional package, so it does not affect the overall appium state. Although, we would probably consider removing it from the next release if it still does not support never node releases. 

Linking @imurchie

**Comment by mykola-mokhnach** [comment]
BTW, these are not errors, but warnings, so the module itself has been compiled successfully

**Comment by imurchie** [comment]
Both the erroring packages, `heapdump` and (for MacOS) `fsevents` are optional dependencies. So if they won't compile they should just be ignored.
