### ISSUE TITLE
zipAlignApk failed  : header mismatch

### ISSUE THREAD

**Issue by ole-vegard** [appium/appium#11580]
## The problem
When runing appium, it will sometimes fail with the error 
```
[W3C] Encountered internal error running command: 
Error: zipAlignApk failed. 
Original error: Command '/home/user/Android/Sdk/build-tools/28.0.3/zipalign -f 4 ../android/app/build/outputs/apk/app-debug.apk /tmp/2018925-2052-1uda64y.ytgf/appium.tmp' exited with code 1. 
Stdout: ''; Stderr: 'W/zip     ( 2213): WARNING: header mismatch
```
## Environment

* Appium version (or git revision) that exhibits the issue: `1.9.1`
* Last Appium version that did not exhibit the issue (if applicable): `1.7.1`
* Desktop OS/version used to run Appium:  `Linux-4.9.0-8-amd64-x86_64-with-debian-9.5` also tried on `OS Darwin-17.7.0-x86_64-i386-64bit` with the same result
* Node.js version (unless using Appium.app|exe): `10.12.0`
* Mobile platform/version under test: `Android`
* Real device or emulator/simulator: `emulator`
* Appium CLI or Appium.app|exe:  `CLI`
* Java : 	`openjdk version 1.8.0_181`
* npm : `6.4.1`

`npm --list` : 
https://gist.github.com/ole-vegard/829d4021800adfcb71eded4ae20cba1f

## Details
The logs will say `file not found`, but the file is there. This also seems to happens on successful runs so I'm not sure it's relevant. 
I've tried experimenting with different versions of build-tools, but it doesn't change anything

## Link to Appium logs
https://gist.github.com/ole-vegard/4243bff95900817a9ab5252589cf2a79

The issue seems similar to https://github.com/appium/appium/issues/10377 but this is build from a clean state and newer appium

## Code To Reproduce Issue [ Good To Have ]

Can't share the code, and it didn't seem to happen running the sample app. But here is roughly what the `Dockerfile` does

Start with `debian:stretch-20180625`

`apt install python3 pip openjdk-8-jdk-headless libpulse libgl1-mesa-glx`

`pip3 install Appium-Python-Client selenium`

Add JAVA_HOME` and add `JAVA_HOME/bin` to path

Install node 10

`npm install appium appium-doctor`

Setup `ANDROID_HOME` env variable and add `platform-tools`. `tools`,  `platform-tools`, `emulator` and `tools/bin` to `PATH`

Download Android sdk from https://dl.google.com/android/repository/ and unzip to `ANDROID_HOME`

install  `platforms;android-28`, `platform-tools`, `build-tools-28.0.3` and `emulator` using `sdkmanager`

Accept licenses

Create an avd

Copy in files from repo

Build using gradle

**Comment by mykola-mokhnach** [comment]
Trey to provide an absolute path to the app instead of relative

**Comment by ole-vegard** [comment]
Added some additional info : it only fails sometimes. Also we have been running using relative path for a long time without it being an issue. 

But I agree it's a good idea to use absolute paths so I'll update the tests to do that and get back to you if that fixes the tests.

**Comment by ole-vegard** [comment]
Update: Using an absolute path seems to have worked. But it wasn't like that before. I think something should be done so that other people won't have the same error.

**Comment by mykola-mokhnach** [comment]
You are always welcome to push a fix
