### ISSUE TITLE
Test WebDriverAgent，ServerURLHere->http://169.254.144.xxx:8100<-ServerURLHere，it is not localhost,computer IP or WIFI IP

### ISSUE THREAD

**Issue by sandy533hs** [appium/appium#11595]
## The problem
2018-10-30 10:20:46.679909+0800 WebDriverAgentRunner-Runner[3005:1389505] ServerURLHere->http://169.254.144.xxx:8100<-ServerURLHere
it is not localhost,computer IP or WIFI IP,but IOS UI test is ok sometimes. so i do not know which IP shuold be show in Xcode, or all is right?  all IP is right,why IOS UI test is wrong? thank you.

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):1.9.2@beta
* Desktop OS/version used to run Appium:1.9.2@beta
* Node.js version (unless using Appium.app|exe):8.12.0
* Mobile platform/version under test:12.0.1
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe:Appium CLI 

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Sending createSession command to WDA
[debug] [JSONWP Proxy] Matched '/session' to command name 'createSession'
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.aaa.bbb","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[JSONWP Proxy] Got an unexpected response: {"code":"ESOCKETTIMEDOUT","connect":false}
[debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT). Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1540866098685 (10:21:38 GMT+0800 (CST))

## Xcode
break:
->  0x10439e3cc <+144>: b    0x10439e418 ; <+220> at RoutingHTTPServer.m:193   Thread 1: signal SIGKILL
console:
t =    31.26s Open com.aaa.bbb
    t =    31.27s     Launch com.aaa.bbb
    t =    31.27s         Terminate com.aaa.bbb:2988
    t =    32.77s         Wait for com.aaa.bbb to idle
    t =    39.58s Find the Application 'com.aaa.bbb'
    t =    39.59s     Snapshot accessibility hierarchy for app with pid 3009
    t =    41.08s Open com.aaa.bbb
    t =    41.08s     Launch com.aaa.bbb
    t =    41.09s         Terminate com.aaa.bbb:3009
    t =    42.36s         Wait for com.aaa.bbb to idle
(lldb) 

## Code To Reproduce Issue [ Good To Have ]

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

**Comment by sandy533hs** [comment]
![image](https://user-images.githubusercontent.com/44222869/47694050-1e08b800-dc37-11e8-9e02-3e2bc990541c.png)

**Comment by mykola-mokhnach** [comment]
This is the IP address of the device where WebDriverAgent is running (a mobile phone, for example). Appium uses a tool called iproxy in order to forward network requests to/from the device to the host, to which the device is connected, so this address is used merely for logging purposes.
