### ISSUE TITLE
Element Location incorrect if the element is not visible on the screen

### ISSUE THREAD

**Issue by sebinjqburst** [appium/appium#11598]
## The problem

The elements on the bottom of the current screen view are having the location listed incorrectly.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.2-beta2
* Last Appium version that did not exhibit the issue (if applicable):1.9.1 (Not sure, but my elements were getting recognised correctly before)
* Desktop OS/version used to run Appium: High Sierra
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 12.0.1
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe:

## Details

The corresponding cell shows the location and size as 
**location: {72, 1038}
size: {950, 151}**
But, all the elements inside the cell shows location as
**location: {72, -976}**. The size varies accordingly, but the location remains a constant. And the _y value_ is negative. As my element is on the bottom of the current screen, I was expecting the y value to be positive. 
The cell is having radio button elements in 3 rows with 3 columns each.

**Comment by mykola-mokhnach** [comment]
Element locations are returned by WebDriverAgent. Please report the problem tohttps://github.com/facebook/WebDriverAgent
