### ISSUE TITLE
Add `forceMjsonwp` as server capability

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#11599]
A few of the clients (Ruby, Java, Python) have a capability called `forceMjsonwp` that forces the creation JSONWP instead of W3C sessions. This is a client-side capability only. I think we should temporarily add this as a server-side capability until _all_ of the clients have full W3C support.

One example where this is causing problems is in attaching sessions (see https://github.com/appium/appium-desktop/issues/536). When a client creates a W3C session and the user tries to attach to that session using Appium Desktop, it throws an error because the client that Appium Desktop uses, `admc/wd`, can't handle W3C yet.

Another reason is that this can be used in case of an emergency. If there's a bug related to W3C, we can give users the option to fallback to MJSONWP.

(cc: @imurchie @jlipps @mykola-mokhnach what are your thoughts on this?)

**Comment by mykola-mokhnach** [comment]
I'm not very positive about such feature. The server already possesses quite complicated logic for setting the protocol and we going to make it even more complicated

**Comment by dpgraham** [comment]
Appium Desktop users are having [problems](https://github.com/appium/appium-desktop/issues/669) because they're creating sessions in clients that use W3C and then they're trying to attach to sessions using Desktop (which uses wd), which doesn't support W3C. I'd like to include this as a stop-gap until we get all of the clients to be W3C client.

All I would need to do is something like:

```javascript
commands.createSession = async function (jsonwpDesiredCapabilities, jsonwpRequiredCaps, w3cCapabilities) { // eslint-disable-line require-await
  if (this.sessionId !== null) {
    throw new errors.SessionNotCreatedError('Cannot create a new session ' +
                                            'while one is in progress');
  }
  // TODO: Deprecate and remove this capability once all of the clients are W3C compliant
  if (jsonwpDesiredCapabilities.forceMjsonwp === true) {
    logger.info(`Received "forceMjsonwpCapability". Defaulting to MJSONWP protocol`);
    w3cCapabilities = null;
  }

```

Once we get all of the clients to be fully W3C compliant, we can drop this.

**Comment by dpgraham** [comment]
Closing as won't fix.
