### ISSUE TITLE
push a zip file to my Android device in Appium

### ISSUE THREAD

**Issue by Ucoon** [appium/appium#11596]
## The problem

is there any way that pushing a zip file to my Android device? When using push_file() I found that it can push file such as text, but except zip file. I use python to write my scripts.
## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.0
* Desktop OS/version used to run Appium: Ubuntu 18.04
* Node.js version (unless using Appium.app|exe): v8.12.0
* Mobile platform/version under test: Android 5.0

**Comment by mykola-mokhnach** [comment]
this API should internally call `adb push`, which works for any file types.

Can you attach the server log?

**Comment by mykola-mokhnach** [comment]
This a problem in Python client. I assume @KazuCocoa has recently done some fixes on that.

**Comment by mykola-mokhnach** [comment]
This issue should be reported to https://github.com/appium/python-client

**Comment by Ucoon** [comment]
OK. Looking forward next version that solved this problem
