### ISSUE TITLE
Unable to unlock Samsung Galaxy Phones with PIN

### ISSUE THREAD

**Issue by RalphSleighC4** [appium/appium#11605]
## The problem

Appium throws an error when attempting to unlock a Samsung Galaxy S7/S9 with a PIN

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: OSX
* Node.js version (unless using Appium.app|exe): 8.9.1
* Mobile platform/version under test:
* Real device or emulator/simulator: Samsung Galaxy S9, Android 8, Samsung Galaxy S7, Android 8
* Appium CLI or Appium.app|exe: CLI

## Details

When attempting to unlock the phone using a pin, appium enters the pin correctly but then can't find the ok button to continue.

It's looking for com.android.systemui:id/key_enter, but using the desktop inspector the ok button is com.android.systemui:id/key_enter_text

Same error on both the S7 and S9. I have verified my setup can unlock a Nexus 6P correctly so suspect it's because of Samsung's branded pin entry screen.

I have solved this step before by using adb shell input keyevent KEYCODE_ENTER, but would rather use the inbuilt unlock. 

## Link to Appium logs

[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8200/wd/hub/session/cdc64b8c-0c5c-42e3-975e-8f1205b5fb7a/element] with body: {"strategy":"id","selector":"com.android.systemui:id/key_enter","context":"","multiple":false}
[debug] [MJSONWP] Matched JSONWP error code 7 to NoSuchElementError

**Comment by mykola-mokhnach** [comment]
The fix has been added to appium@beta
