### ISSUE TITLE
uncaughtException: Android bootstrap socket crashed: Error: read ECONNRESET

### ISSUE THREAD

**Issue by Anger87** [appium/appium#11606]
log appium 1.9.0:
[01-11-2018__06_06_18AM_PORT4762.txt](https://github.com/appium/appium/files/2538235/01-11-2018__06_06_18AM_PORT4762.txt)
[01-11-2018__10_29_59AM_PORT4727.txt](https://github.com/appium/appium/files/2538236/01-11-2018__10_29_59AM_PORT4727.txt)
[01-11-2018__11_50_40AM_PORT4762.txt](https://github.com/appium/appium/files/2538237/01-11-2018__11_50_40AM_PORT4762.txt)
log appium 1.7.2:
[01-11-2018__11_35_49AM_PORT4744.txt](https://github.com/appium/appium/files/2538390/01-11-2018__11_35_49AM_PORT4744.txt)

## The problem
uncaughtException: Android bootstrap socket crashed: Error: read ECONNRESET
Error repeats almost each time when I run tests
## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.0 , 1.7.2

* Last Appium version that did not exhibit the issue (if applicable): didnt tried
* Desktop OS/version used to run Appium: Windows 10 pro 64x
* Node.js version (unless using Appium.app|exe):8.11.3
* Mobile platform/version under test: Android 4.4 , 6, 7
* Real device or emulator/simulator: AVD emulator 
* Appium CLI or Appium.app|exe: Appium CLI 

## Link to Appium logs

15:12:00 uncaughtException: Android bootstrap socket crashed: Error: read ECONNRESET
15:12:00 	{"date":"Wed Oct 31 2018 15:12:00 GMT+0200 (Ð¤Ð¸Ð½Ð»Ñ�Ð½Ð´Ð¸Ñ� (Ð·Ð¸Ð¼Ð°))","process":{"pid":13604,"uid":null,"gid":null,"cwd":"C:\\JENKINS\\workspace\\project","execPath":"C:\\Program Files\\nodejs\\node.exe","version":"v8.11.3","argv":["C:\\Program Files\\nodejs\\node.exe","C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\appium\\build\\lib\\main.js","--port","4738","--address","0.0.0.0","--log-level","error","--bootstrap-port","4739","--session-override","-l"],"memoryUsage":{"rss":154054656,"heapTotal":105959424,"heapUsed":95126744,"external":166568}},"os":{"loadavg":[0,0,0],"uptime":2251.9456716},"trace":[{"column":21,"file":"C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-android-bootstrap\\lib\\bootstrap.js","function":null,"line":97,"method":null,"native":false},{"column":13,"file":"events.js","function":"emitOne","line":116,"method":null,"native":false},{"column":7,"file":"events.js","function":"Socket.emit","line":211,"method":"emit","native":false},{"column":8,"file":"internal/streams/destroy.js","function":"emitErrorNT","line":64,"method":null,"native":false},{"column":11,"file":"internal/process/next_tick.js","function":"_combinedTickCallback","line":138,"method":null,"native":false},{"column":9,"file":"internal/process/next_tick.js","function":"process._tickCallback","line":180,"method":"_tickCallback","native":false}],"stack":["Error: Android bootstrap socket crashed: Error: read ECONNRESET","    at Socket.<anonymous> (C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-android-bootstrap\\lib\\bootstrap.js:97:21)","    at emitOne (events.js:116:13)","    at Socket.emit (events.js:211:7)","    at emitErrorNT (internal/streams/destroy.js:64:8)","    at _combinedTickCallback (internal/process/next_tick.js:138:11)","    at process._tickCallback (internal/process/next_tick.js:180:9)"]}
15:12:01 org.openqa.selenium.WebDriverException: org.apache.http.conn.HttpHostConnectException: Connect to 0.0.0.0:4738 [/0.0.0.0] failed: Connection refused: connect
15:12:01 Build info: version: '3.5.2', revision: '10229a9', time: '2017-08-21T17:29:55.15Z'
15:12:01 System info: host: 'SERV-MP-605', ip: '172.27.160.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
15:12:01 Driver info: driver.version: RemoteWebDriver
15:12:01 	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:177)
15:12:01 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
15:12:01 	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:46)
15:12:01 	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
15:12:01 	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
15:12:01 	at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:343)
15:12:01 	at de.autodoc.android.automation.utils.ScreenshotUtils.screenshotOnFail(ScreenshotUtils.java:33)
15:12:01 	at de.autodoc.android.automation.tests.listners.CustomTestListener.onTestFailure(CustomTestListener.java:34)
15:12:01 	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1731)
15:12:01 	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1714)
15:12:01 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
15:12:01 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
15:12:01 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
15:12:01 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
15:12:01 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
15:12:01 	at org.testng.TestRunner.privateRun(TestRunner.java:744)
15:12:01 	at org.testng.TestRunner.run(TestRunner.java:602)
15:12:01 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
15:12:01 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
15:12:01 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
15:12:01 	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
15:12:01 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
15:12:01 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
15:12:01 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
15:12:01 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
15:12:01 	at org.testng.TestNG.runSuites(TestNG.java:1144)
15:12:01 	at org.testng.TestNG.run(TestNG.java:1115)
15:12:01 	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
15:12:01 	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
15:12:01 	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
15:12:01 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
15:12:01 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
15:12:01 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
15:12:01 Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 0.0.0.0:4738 [/0.0.0.0] failed: Connection refused: connect
15:12:01 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
15:12:01 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
15:12:01 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
15:12:01 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
15:12:01 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
15:12:01 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
15:12:01 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
15:12:01 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
15:12:01 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
15:12:01 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
15:12:01 	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:142)
15:12:01 	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:88)
15:12:01 	at io.appium.java_client.remote.AppiumCommandExecutor.doExecute(AppiumCommandExecutor.java:132)
15:12:01 	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:162)
15:12:01 	... 32 more
15:12:01 Caused by: java.net.ConnectException: Connection refused: connect
15:12:01 	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
15:12:01 	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
15:12:01 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
15:12:01 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:204)
15:12:01 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
15:12:01 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
15:12:01 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
15:12:01 	at java.net.Socket.connect(Socket.java:589)
15:12:01 	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
15:12:01 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
15:12:01 	... 45 more

## Code To Reproduce Issue [ Good To Have ]

 DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(CapabilityType.PLATFORM, MobilePlatform.ANDROID);
        capabilities.setCapability("deviceName", deviceName);
        capabilities.setCapability("udid", udid);
        capabilities.setCapability("platformName", "Android");
        capabilities.setCapability("app", appPath);
        capabilities.setCapability("appPackage", appPackage);
        capabilities.setCapability("appActivity", appActivity);
        capabilities.setCapability("noSign", true);
        capabilities.setCapability("newCommandTimeout", 360);
        capabilities.setCapability("clearSystemFiles", true);
        capabilities.setCapability("automationName", "uiautomator2");
        capabilities.setCapability("systemPort", Integer.valueOf(p));
        // Soft keyboard not shown
        capabilities.setCapability("unicodeKeyboard", true);
        capabilities.setCapability("resetKeyboard", true);

Start appium method: 
    service = AppiumDriverLocalService.buildService(new AppiumServiceBuilder()
                .usingDriverExecutable(new File(nodePath))
                .withAppiumJS(new File(MainJSPAth))
                .usingPort(Integer.parseInt(port))
                .withArgument(AndroidServerFlag.BOOTSTRAP_PORT_NUMBER, String.valueOf(Integer.valueOf(port) + 1))
                .withArgument(GeneralServerFlag.LOG_LEVEL, "error")
                .withArgument(GeneralServerFlag.SESSION_OVERRIDE, "-l")
        );
[01-11-2018__06_06_18AM_PORT4762.txt](https://github.com/appium/appium/files/2538303/01-11-2018__06_06_18AM_PORT4762.txt)
[01-11-2018__10_29_59AM_PORT4727.txt](https://github.com/appium/appium/files/2538304/01-11-2018__10_29_59AM_PORT4727.txt)
[01-11-2018__11_50_40AM_PORT4762.txt](https://github.com/appium/appium/files/2538305/01-11-2018__11_50_40AM_PORT4762.txt)

**Comment by mykola-mokhnach** [comment]
Please attach the full server log

**Comment by Anger87** [comment]
@mykola-mokhnach  attached appium logs to the ticket

**Comment by mykola-mokhnach** [comment]
In the log it is visible that connection reset error is happening on node level, so I would say it is some stability issue with your machine or the network connection in general. I don't think it is possible to do anything about that on server side.

**Comment by auto-mator** [comment]
This happens every day for me. You won't get a real answer as to why it occurs. Sorry

**Comment by MummanaSubramanya** [comment]
im facing same issue with c# client uiautomator2 https://github.com/appium/appium-dotnet-driver/issues/275

**Comment by mykola-mokhnach** [comment]
Linking https://stackoverflow.com/questions/17245881/node-js-econnreset

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
