### ISSUE TITLE
Issue with appium taking too long to find elements and execute next step if element is not found in IOS.

### ISSUE THREAD

**Issue by Jaspreet23** [appium/appium#11600]
## The problem

I am facing the issue with my script/Appium taking too long to find the elements.
Platform: iOS

For a simple step in my Gherkin Scenario : Click a trolley icon in Checkout
This step has to look if any unavailable items are present then handle it

This alone step takes more than 1m and few seconds as it keeps looking for the element again and again in a loop. Attaching the logs for your reference. Please help as this issue is really making all the scripts very slow and time consuming. As an idea, the appium looks for an element which is not present for approx 20 times before it moves further which is making it extremely slow.

For finding elements, I am either relying on accessibility ids wherever I have access to those other wise I am using this approach
@iOSXCUITFindBy(iOSNsPredicate = "name BEGINSWITH 'DRIVER INSTRUCTIONS'")

## Environment

Appium version : Version 1.7.0 (1.7.0)
Last Appium version that did not exhibit the issue (if applicable):Never tried
MAC OS/version used to run Appium:10.13.4
Node.js version (unless using Appium.app|exe):v10.10.0
Mobile platform/version under test: iOS
Real device or emulator/simulator:Real device(iPhone 8)
Appium CLI or Appium.app|exe:
Kindly let me know if you need any other info.

## Link to Appium logs
[AppiumLogs.txt](https://github.com/appium/appium/files/2532021/AppiumLogs.txt)

## Code To Reproduce Issue [ Good To Have ]
    @iOSFindBy(id="editButton")
    private MobileElement CheckoutEditButton;

    @iOSXCUITFindBy(iOSNsPredicate = "name BEGINSWITH 'DRIVER INSTRUCTIONS'")
    private MobileElement CheckoutDriverInstructions;

   if(CheckoutEditButton.isDisplayed()) -- This line takes close to a minute if this element is not present
           return CheckoutDeliverToButton.getText();

**Comment by mykola-mokhnach** [comment]
Please report the problem to https://github.com/facebook/WebDriverAgent as there is nothing we can do there in Appium. Also, make sure your Appium server is up to date.

**Comment by JasWoolieX** [comment]
Hello @mykola-mokhnach Thanks for your reply. However appium looking for the same elements again and again if the element is not present is an issue with Appium itself as it is similar behaviour in Android also. However iOS is bit more slower than Android.
Your help is really needed.
Thanks

**Comment by Jaspreet23** [comment]
Hello @mykola-mokhnach Thanks for your reply. However appium looking for the same elements again and again if the element is not present is an issue with Appium itself as it is similar behaviour in Android also. However iOS is bit more slower than Android.
Your help is really needed.
Thanks

**Comment by mykola-mokhnach** [comment]
> However appium looking for the same elements again and again if the element is not present is an issue with Appium itself as it is similar behaviour in Android also.

This might be an influence of an implicit wait, which is anyway set on the client side.

**Comment by Jaspreet23** [comment]
> This might be an influence of an implicit wait, which is anyway set on the client side.

I can confirm @mykola-mokhnach that there is no implicit wait being used. A simple example of code where it tries to find the element 20-30 times is:
   @iOSFindBy(id = "Skip for Now")
    private MobileElement skipIOSLoginScreen;

 try {
           ` {The script here tries to find the element 20-30 times, if the element/screen is not present} `
            if (skipIOSLoginScreen.isDisplayed()) --- 
                skipIOSLoginScreen.click();
       }
 } catch (Exception e) {
            logger.info("Log in and Rewards process already done");
        }
       
Capabilities that I am using:

  "appiumServerCapabilities": {
          "app": "Supers2.app",
          "platformName": "iOS",
          "deviceName":"iPhone 7 Plus",
          "udid": "1F9657EE-811C-4534-862F-9A30A61FCA8E",
          "automationName": "XCUITest",
          "printPageSourceOnFailure":true
        },
        "iOSOnlyCapabilities": {
          "launchTimeout": 30000,
          "bundleId": "**",
          "noReset":true,
          "fullReset":false,
          "autoAcceptAlerts":true,
          "autoGrantPermissions": true,
          "xcodeOrgId": "**",
          "xcodeSigningId":"iPhone Developer",
          "updatedWDABundleId":"***",
          "clearSystemFiles":true,
          "simpleIsVisibleCheck":true,
          "useJSONSource":true
        }

Can you kindly suggest whats wrong I am doing?

**Comment by JasWoolieX** [comment]
Hello @mykola-mokhnach Can you guide please, your help is really appreciated. I have also submitted my issue to the facebook github link but haven't heard back anything.

**Comment by mykola-mokhnach** [comment]
Unfortunately Facebook people are not very responsive, but I don't have any other proposals from my side.

You could try to hire a consultant though.

**Comment by Jaspreet23** [comment]
> You could try to hire a consultant though.

Do you mean I can hire one of the Appium consultants to help with this issue? Whats the process for it?

**Comment by mykola-mokhnach** [comment]
We usually don't advertise any paid services here, but you could try to contact

<details><summary>this company</summary>
<p>

https://cloudgrey.io/

</p>
</details>


Because it is setup by one of Appium creators.
