### ISSUE TITLE
android driver: set 'page load' timeout is not implemented yet

### ISSUE THREAD

**Issue by DudaGod** [appium/appium#11609]
## The problem

Hello guys.
Can you explain please: why `page load` timeout is not implemented yet - https://github.com/appium/appium-base-driver/blob/master/lib/basedriver/commands/timeout.js#L89?

Are there any blockers or you didn't have time to implement it?

**Comment by mykola-mokhnach** [comment]
In native context such parameter does not make sense.

**Comment by DudaGod** [comment]
I did not understand why it does not make sense in a native context?
I want kill my app if some external source will load extremely long

> In native context such parameter does not make sense.
Does it mean if I change context on webview in my hybrid app I can set this `page load` timeout?
I just checked and it doesn't work.

**Comment by mykola-mokhnach** [comment]
Yes the behaviour described above is the designed one.

**Comment by DudaGod** [comment]
Why then in ios driver this timeout is implemented - https://github.com/appium/appium-ios-driver/blob/master/lib/commands/timeout.js#L5-L12?
