### ISSUE TITLE
customFindModules not recognized by Appium 1.9.2-beta.2

### ISSUE THREAD

**Issue by ericsavoiewaltz** [appium/appium#11607]
## The problem

I upgraded to Appium v1.9.2-beta.2 to try out the customFindModules capability with Test.AI element finding. 

## Environment

* Appium v1.9.2-beta.2
* New to 1.9.2-beta.2 
* macOS High Sierra 10.13.6
* Node v11.0.0
* iPhone 11.4
* Real device
* Appium CLI

## Details

I added           customFindModules: {
              "ai": "test-ai-classifier"
          },

to my capabilities block and Appium does not recognize the capability

## Link to Appium logs

After it spits out the message that it doesn't recognize the capability the automation works as normal.

[Appium]   customFindModules: {
[Appium]     ai: test-ai-classifier
[Appium]   }
[Appium]   shouldUseCompactResponses: false
[Appium]   browserName: null
[Appium]   versionNumber: null
[debug] [BaseDriver] W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP desired capabilities {"platformName":"iOS","brow... were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"platformNa...
[BaseDriver] The following capabilities were provided, but are not recognized by appium: customFindModules, shouldUseCompactResponses, versionNumber.
[BaseDriver] Session created with session id: 33b99288-0bf3-4d32-ad9e-360ef25b9f70
(node:49312) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

@jlipps

**Comment by ericsavoiewaltz** [comment]
Ya. Right. I had already done that. 

![screen shot 2018-10-31 at 2 02 18 pm](https://user-images.githubusercontent.com/36003722/47808829-a198d680-dd15-11e8-980c-ccdf4ff1f73c.png)

**Comment by ericsavoiewaltz** [comment]
@saikrishna321 
Sorry I didn't mention I had already installed it. 

Is this not the correct set up?

![screen shot 2018-10-31 at 2 14 58 pm](https://user-images.githubusercontent.com/36003722/47809518-71523780-dd17-11e8-870e-6c713e4c1465.png)

**Comment by saikrishna321** [comment]
@KazuCocoa does ruby client support custom module

**Comment by ericsavoiewaltz** [comment]
Hi Kazu, 

Thanks for getting back to me! 

I gave it a try and I'm seeing this now: 

 @ios_driver.driver.find_element :custom, "f:foo"
ArgumentError: cannot find element by :custom
from /Users/ericsavoie/.rvm/gems/ruby-2.3.1/gems/appium_lib_core-1.8.4/lib/appium_lib_core/common/base/search_context.rb:60:in `_set_by_from_finders'

**Comment by KazuCocoa** [comment]
The core should be over _2.0.4_
Could you update your ruby_lib to the latest one? 
https://github.com/appium/ruby_lib/blob/master/CHANGELOG.md#v9151

**Comment by ericsavoiewaltz** [comment]
Thanks @KazuCocoa @ericsavoiewaltz  it works!! Very very cool. 
```
[3] pry(#<Object>)> @ios_driver.driver.find_element :custom, "ai:qr code"
=> #<Selenium::WebDriver::Element:0x..f9b4edc3e42a609e2 id="C9000000-0000-0000-5E0B-000000000000">
```
