### ISSUE TITLE
While Testing app testing on Android , Error occured while starting App. Original error: 'com.rastreator.app.SplashActivity' never started

### ISSUE THREAD

**Issue by sumitgos** [appium/appium#11603]
## The problem

An unknown server-side error occurred while processing the command. Original error: Error occured while starting App. Original error: 'com.rastreator.app.SplashActivity' never started

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:Window
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:Android/V-7
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe:Appium CLI

## Details

An unknown server-side error occurred while processing the command. Original error: Error occured while starting App. Original error: 'com.rastreator.app.SplashActivity' never started

[debug] [ADB] Found package: 'com.rastreator.app' and fully qualified activity n
ame : 'com.rastreator.app.LoginActivity'
[debug] [ADB] Incorrect package and activity. Retrying.
[debug] [ADB] Getting focused package and activity
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'E:\Sumit\MobileAutomation\Android SDK\adt-bundle-windows-
x86_64-20140702\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe' w
ith args: ["-P",5037,"-s","0715f769e9d9123a","shell","dumpsys","window","windows

## Link to Appium logs

[debug] [ADB] Found package: 'com.rastreator.app' and fully qualified activity n
ame : 'com.rastreator.app.LoginActivity'
[debug] [ADB] Incorrect package and activity. Retrying.
[debug] [ADB] Getting focused package and activity
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'E:\Sumit\MobileAutomation\Android SDK\adt-bundle-windows-
x86_64-20140702\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe' w
ith args: ["-P",5037,"-s","0715f769e9d9123a","shell","dumpsys","window","windows

## Code To Reproduce Issue [ Good To Have ]

 DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities.SetCapability("automationName", "Appium");
            capabilities.SetCapability("platformName", "Android");
            capabilities.SetCapability("deviceName", DeviceName);
            capabilities.SetCapability("udid", DeviceId);
            capabilities.SetCapability("app", "Q:\\VSTS_Automation\\AndroidApp\\Rastreator\\Rastreator.apk

");
            capabilities.SetCapability("app-package", "com.rastreator.app"); // This is package name of your app (you can get it from apk info app)
            capabilities.SetCapability("app-activity", "app.SplashActivity"); // This is Launcher activity of your app (you can get it from apk info app)
            capabilities.SetCapability("autoInstrument", true);
            capabilities.SetCapability("noSign", true);
            capabilities.SetCapability("newCommandTimeout", 240);
            capabilities.SetCapability("noReset", "false");
            capabilities.SetCapability("setWebContentsDebuggingEnabled", "true");  // newly added for testing
            capabilities.SetCapability("autoWebview", "true");

            try
            {
                objMobileBrowser = new Mobile_Browser(serviceUrl, capabilities);
                objMobileBrowser.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(50000));
            }

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md

Also, v1.7.2  is out of date

**Comment by sumitgos** [comment]
Thnx for help we will check out for same
