### ISSUE TITLE
Appium server is not working properly.

### ISSUE THREAD

**Issue by Muvidevlopers** [appium/appium#11613]
## Problem - 
The Application is only opening but as per our resource ID (attribute) written in script, the element is not being located. Previously web driver agent was being installed and then the application was being installed but after updating to new appium and Xcode, only the application is being installed and stays still with following error in console. Sometimes the application runs and identifies the element and sometimes it doesn't.

@imurchie  could you please look into this and help us to resolve.

## Environment
Appium version (or git revision) that exhibits the issue: 1.9.2-beta.2
Desktop OS/version used to run Appium: 10.13.6
Node.js version (unless using Appium.app|exe): 10.7.0
Mobile platform/version under test: iOS 12.0
Real device or emulator/simulator: Real Device and Simulator
Appium CLI or Appium.app|exe: Appium.app

Error Log - 

[Xcode] t = 0.64s Open com.release.*****
[Xcode]
[Xcode] t = 0.64s Launch com.release.*****
[Xcode]
[Xcode] t = 0.74s Wait for com.release.***** to idle
[Xcode]
[Xcode] t = 60.77s App event loop idle notification not received, will attempt to continue.
[Xcode]
[Xcode] t = 60.78s App animations complete notification not received, will attempt to continue.

**Comment by mykola-mokhnach** [comment]
This is an issue with WebDriverAgent rather than with Appium. People say that setting of `waitForQuiescence` cap to false sometimes helps

**Comment by Muvidevlopers** [comment]
@mykola-mokhnach Thank you so much for the help. It works for me.
