### ISSUE TITLE
In most conditions, /wda/getPasteboard can not get the string in the pasteboard on iOS

### ISSUE THREAD

**Issue by StephenShang** [appium/appium#11610]
## The problem

In most conditions, /wda/getPasteboard can not get the string in the pasteboard, even though there's actually astring inthe general pasteboard.

## Environment

the newest WebDriverAgent from appium/WebDriverAgent
Xcode 10
real device of iOS 12.0 & 10.3.3

## Details

UIPasteboard *pb = UIPasteboard.generalPasteboard;
 returns a pasteboard instance. But pb.string is nil in most conditions, but in other apps, pb.string is not nil.

**Comment by mykola-mokhnach** [comment]
This is due to iOS security restrictions. On Simulators it works better.

Closed as not an issue

**Comment by StephenShang** [comment]
I found the reason, when app is in background, wo can not get from pasteboard, but can get the information in front
