### ISSUE TITLE
Cannot retrieve value from password field, when it is in shown state

### ISSUE THREAD

**Issue by SergheiRidico** [appium/appium#11614]
## The problem
Password field in my application has two states: shown/hidden.
When the password is hidden, the text field has type `XCUIElementTypeSecureTextField` 
and its values consists of `•••••••••••••` symbols. 
When I press show button, password field change its type to `XCUIElementTypeTextField` 
and its value is `1` instead of entered password which is visible on the screen.

## Environment

* Appium version (or git revision) that exhibits the issue: `1.9.1-beta2`
* Desktop OS/version used to run Appium: `macOS High Sierra v10.13.6`
* Node.js version (unless using Appium.app|exe): `10.12`
* Mobile platform/version under test: `iOS`
* Real device or emulator/simulator: `both`

## Link to Appium logs

[Appium logs](https://gist.github.com/SergheiRidico/495a81d8205f17637beed7eb4b0d5e98)

**Comment by mykola-mokhnach** [comment]
I think, there is nothing that can be changed on the Appium side. 

Do you see the value via system accessibility inspector?

**Comment by SergheiRidico** [comment]
Accessibility inspector also returns value: `1`.

**Comment by mykola-mokhnach** [comment]
Then please either change your source code to provide proper accessibility value or report the problem to Apple.
