### ISSUE TITLE
getSize not working in Linux appium 1.9.1

### ISSUE THREAD

**Issue by MummanaSubramanya** [appium/appium#11619]
## The problem
I have hybrid app and Im trying the below method 
`MobileDriver.FindElement(LocateElement(type, object)).Size` which works fine when running in windows machine with appium server 1.9.1 here is the [windows gist](https://gist.github.com/MummanaSubramanya/ef966924f9cd13abd760366645a5e4fb) When I try to run the same code in Linux machine with appium server 1.9.1 it fails with error "Unknown command". Here is the gist for linux appium server [linux gist](https://gist.github.com/MummanaSubramanya/1c7f34b7d99e7cee0b9465dc96b3688a) 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable): 1.8.1
* Desktop OS/version used to run Appium: Linux and Windows 10
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android o
* Real device or emulator/simulator: real
* Appium CLI or Appium.app|exe: CLI for linux and Exe for windows

## Details

`<add key="AppiumServer" value="127.0.0.1" />
      <add key="AppiumServerPort" value="4723" />
      <add key="PlatformName" value="Android" />
      <add key="AutomationName" value="uia" />
      <add key="PlatformVersion" value="8.0" />
      <add key="DeviceName" value="xxxxxxx" />
      <add key="AppPackage" value="com.xxx.xxx" />
      <add key="AppActivity" value=".MainActivity" />
      <add key="AutoWebview" value="true" />`

**Comment by mykola-mokhnach** [comment]
Try appium@beta

**Comment by MummanaSubramanya** [comment]
tried with appium1.9.2-beta still facing the isue.

`[W3C (3244b5c7)] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Matched '/wd/hub/session/3244b5c7-dc47-43d5-ace3-03ae0c86befe/element/0.5961594775190369-15/rect' to command name 'getElementRect'
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/3244b5c7-dc47-43d5-ace3-03ae0c86befe/element/0.5961594775190369-15/rect] to [GET http://127.0.0.1:8000/wd/hub/session/565a3e30785450e6bc286486136ceea9/element/0.5961594775190369-15/rect] with body: {}
[JSONWP Proxy] Got an unexpected response: unknown command: session/565a3e30785450e6bc286486136ceea9/element/0.5961594775190369-15/rect
[debug] [W3C (3244b5c7)] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 404 - "unknown command: session/565a3e30785450e6bc286486136ceea9/element/0.5961594775190369-15/rect"
[debug] [W3C (3244b5c7)]     at /home/pi/node_modules/appium-base-driver/lib/protocol/protocol.js:550:13
[debug] [W3C (3244b5c7)]     at Generator.next (<anonymous>)
[debug] [W3C (3244b5c7)]     at asyncGeneratorStep (/home/pi/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
[debug] [W3C (3244b5c7)]     at _next (/home/pi/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
[debug] [W3C (3244b5c7)]     at <anonymous>
[HTTP] <-- GET /wd/hub/session/3244b5c7-dc47-43d5-ace3-03ae0c86befe/element/0.5961594775190369-15/rect 500 32 ms - 1054
[HTTP]
[HTTP] --> GET /wd/hub/session/3244b5c7-dc47-43d5-ace3-03ae0c86befe/screenshot
[HTTP] {}`

**Comment by mykola-mokhnach** [comment]
What is appium-xcuitest-driver component version?

**Comment by MummanaSubramanya** [comment]
how come appium-xcuitest-driver comes into picture its and android device and automation name
 is UIautomator2

**Comment by mykola-mokhnach** [comment]
If this is uiautomator2 driver then you could try to replace the call to getRect with getLocation/getSize , since chromedriver itself does not support the /rect endpoint.

**Comment by MummanaSubramanya** [comment]
Im using c# 'MobileDriver.FindElement(LocateElement(type, object)).Size' is the command im using. There is no command to get Rect in c#. IF the command was an issue it should fail in both linux and windows.

**Comment by mykola-mokhnach** [comment]
It probably calls getRect insternally

**Comment by MummanaSubramanya** [comment]
so its an implementation issue?

**Comment by mykola-mokhnach** [comment]
I think it might be handled on both sides. For iOS the driver has been patched to "split" /rect call in web context into /location + /size. I'm not quite sure if the same trick could be done for Android. Although patching this on driver level will allow to void possible issues with all clients and not only the .NET one.

@imurchie Perhaps you have more ideas on a possible fix?

**Comment by MummanaSubramanya** [comment]
Im still not able to understand the code works fine with Windows Appium server 1.9.1 and it fails with Linux Appium server 1.9.1 -- I believe the server code is same for all platforms

**Comment by akinsolb** [comment]
@mykola-mokhnach I think it calls getRect internally, I saw this a while back. It got replaced as part of the W3C changes. Will calling /location/size work in a web context?

**Comment by mykola-mokhnach** [comment]
It will, but patching that would only fix the problem for .net client. Let see if we can patch it on driver level first

**Comment by MummanaSubramanya** [comment]
@akinsolb : sorry but can i expect this fix at early?

**Comment by mykola-mokhnach** [comment]
I have published the patch for uia2 in appium@beta
