### ISSUE TITLE
Appium randomly cranks up to 100% cpu usage and never recovers

### ISSUE THREAD

**Issue by daviesdoclc** [appium/appium#11616]
## The problem

I have a feature set with a dozen tests.  I was able to complete the entire sequence on a previous MacBook Pro.  I recently moved to a 2018 MacBook Pro and reinstalled my Appium environment.  It's the same version of Appium, but probably newer Node version.  On the new machine I've been unable to complete all 12 tests without one of them hanging and spinning up the cpu to 100%.  It's random.  Sometimes it's within the first 3 tests.  Other times it's the very last test.  It happens on both the Android and iOS simulators.  Some times it happens right at the beginning of the test and other times several steps in.  I have to kill appium, as the rest of the tests fails and take forever to time out.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1 (I've tried 1.9.0 and beta)
* Last Appium version that did not exhibit the issue (if applicable): unknown 
* Desktop OS/version used to run Appium: Mac OS X 10.14
* Node.js version (unless using Appium.app|exe): 11.0.0
* Mobile platform/version under test: Android 7.1 and iOS 12
* Real device or emulator/simulator: emulator (Android Studio 3.2.1 and Xcode 10.0)
* Appium CLI or Appium.app|exe: CLI

## Details

Nothing further

## Link to Appium logs

Android: https://gist.github.com/daviesdoclc/b28b1308dcb7222225a49c45885c9f0c
iOS: https://gist.github.com/daviesdoclc/e63573cb964552778c9acc501f2975c4

This Android run failed on about the 10th test (before it even ran).  I've shown the test above it.  The iOS one stopped on the 9th test (before it even ran).

  @group3
  Scenario: Remove all items from list
  ✔ Given I loaded the app in mock mode
  ✔ And I select the "Change Item Location" page for "OCLC Basic Tests" branch
  ✔ And I select the move type "Clear Temporary Location"
  ✔ And I scan "11223344553"
  ✔ When I select "Remove all items"
  ✔ And I select "Remove All"
  ✔ Then the change item location counter should indicate zero
  ✔ And there should be no items on the change item location list

  @group4
  Scenario: Start another move session with one in progress
  - Given I loaded the app in mock mode
  - And I select the "Change Item Location" page for "OCLC Basic Tests" branch
  - And I select the move type "Clear Temporary Location"
  - And I scan "11223344553"
  - And I select "Home"
  - When I select the menu "Change Item Location"
  - Then I should see the popup "session-popup" with message "You have a Change Item Location session active."

## Code To Reproduce Issue [ Good To Have ]

I can provide something upon request, although I don't know that the code is that helpful since it freezes at different spots.

**Comment by mykola-mokhnach** [comment]
I would try to downgrade NodeJS first. See https://github.com/appium/appium/issues/11588

**Comment by mykola-mokhnach** [comment]
Also it would be also helpful if you could debug the process and figure out on which method call causes the freeze happens. 
You could follow https://stackoverflow.com/questions/10167477/how-to-debug-node-js-causing-100-cpu-usage and send us the resulting file for analysis.

**Comment by daviesdoclc** [comment]
@mykola-mokhnach Thank you! That was it.  I rolled back to 10.12.0 of Node and it works.  I'll run the debug process for you tomorrow and send you details.

**Comment by daviesdoclc** [comment]
Here's the output.  I ran appium as follows:

node --prof node_modules/.bin/appium

it generated the isolate*-v8.log file

then I ran

node-tick-processor isolate-0x105000000-v8.log > node-tick-processor.log 2>&1

Is that what you were looking for?

[isolate-0x105000000-v8.log](https://github.com/appium/appium/files/2542723/isolate-0x105000000-v8.log)
[node-tick-processor.log](https://github.com/appium/appium/files/2542724/node-tick-processor.log)

**Comment by mykola-mokhnach** [comment]
Did you catch these logs for node11?

**Comment by daviesdoclc** [comment]
@mykola-mokhnach this was node11

**Comment by mykola-mokhnach** [comment]
All calls there seem to be obfuscated. Not really helpful information :(

@imurchie @jlipps Do you have any better ideas on how to debug high CPU usage?

**Comment by mykola-mokhnach** [comment]
I don't observe any similar issues in 1.10.0
