### ISSUE TITLE
An unknown server-side error occurred while processing the command: timed out after 20000ms

### ISSUE THREAD

**Issue by Ucoon** [appium/appium#11617]
## The problem

I tried to push zip file to My Android device, but there is a problem occured.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.0
* Desktop OS/version used to run Appium:Ubuntu 18.04
* Node.js version (unless using Appium.app|exe):v 8.12.0
* Mobile platform/version under test:Android 5.0
* Real device or emulator/simulator:real device

## This is server log

[Appium] Welcome to Appium v1.9.0
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"capabilities":{"firstMatch":[{}],"alwaysMatch":{"platformName":"Android","appium:platformVersion":"5.0","appium:deviceName":"SA17607795","appium:appPackage":"com.android.settings","appium:appActivity":".Settings","appium:newCommandTimeout":"1000000"}},"desiredCapabilities":{"platformName":"Android","platformVersion":"5.0","deviceName":"SA17607795","appPackage":"com.android.settings","appActivity":".Settings","newCommandTimeout":"1000000"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"Android","platformVersion":"5.0","deviceName":"SA17607795","appPackage":"com.android.settings","appActivity":".Settings","newCommandTimeout":"1000000"},null,{"firstMatch":[{}],"alwaysMatch":{"platformName":"Android","appium:platformVersion":"5.0","appium:deviceName":"SA17607795","appium:appPackage":"com.android.settings","appium:appActivity":".Settings","appium:newCommandTimeout":"1000000"}}]
[BaseDriver] Event 'newSessionRequested' logged at 1541126207012 (10:36:47 GMT+0800 (CST))
[Appium] Could not parse W3C capabilities: 'newCommandTimeout' must be of type number
[Appium] Trying to fix W3C capabilities by merging them with JSONWP caps
[BaseDriver] The capabilities ["platformVersion","deviceName","appPackage","appActivity","newCommandTimeout"] are not standard capabilities and should have an extension prefix
[Appium] Could not parse fixed W3C capabilities: 'newCommandTimeout' must be of type number. Falling back to JSONWP protocol
[Appium] Creating new AndroidDriver (v3.7.0) session
[Appium] Capabilities:
[Appium]   platformName: Android
[Appium]   platformVersion: 5.0
[Appium]   deviceName: SA17607795
[Appium]   appPackage: com.android.settings
[Appium]   appActivity: .Settings
[Appium]   newCommandTimeout: 1000000
[BaseDriver] Creating session with MJSONWP desired capabilities: {"platformName":"Android","...
[BaseDriver] Capability 'newCommandTimeout' changed from string ('1000000') to integer (1000000). This may cause unexpected behavior
[BaseDriver] Session created with session id: c6dbdce7-9a8d-4dea-8305-f04ff65c798e
[AndroidDriver] Java version is: 1.8.0_181
[AndroidDriver] Retrieving device list
[ADB] Trying to find a connected android device
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[AndroidDriver] Looking for a device with Android '5.0'
[ADB] Setting device id to SA17607795
[ADB] Getting device platform version
[ADB] Running '/home/hezj/Software/AndroidStudio/SDK/platform-tools/adb -P 5037 -s SA17607795 shell getprop ro.build.version.release'
[ADB] Current device property 'ro.build.version.release': 5.0
[AndroidDriver] Using device: SA17607795
[ADB] Setting device id to SA17607795
[ADB] Running '/home/hezj/Software/AndroidStudio/SDK/platform-tools/adb -P 5037 -s SA17607795 shell getprop ro.build.version.sdk'
[ADB] Current device property 'ro.build.version.sdk': 21
[ADB] Device API level: 21
[AndroidDriver] App file was not listed, instead we're going to run com.android.settings directly on the device
[AndroidDriver] Checking whether package is present on the device
[ADB] Running '/home/hezj/Software/AndroidStudio/SDK/platform-tools/adb -P 5037 -s SA17607795 shell pm list packages com.android.settings'
[AndroidDriver] Starting Android session
[ADB] Running '/home/hezj/Software/AndroidStudio/SDK/platform-tools/adb -P 5037 -s SA17607795 wait-for-device'
[ADB] Running '/home/hezj/Software/AndroidStudio/SDK/platform-tools/adb -P 5037 -s SA17607795 shell echo ping'
[AndroidDriver] Pushing settings apk to device...
[ADB] Getting install status for io.appium.settings
[ADB] Running '/home/hezj/Software/AndroidStudio/SDK/platform-tools/adb -P 5037 -s SA17607795 shell pm list packages io.appium.settings'
[ADB] App is installed
[ADB] Getting package info for 'io.appium.settings'
[ADB] Running '/home/hezj/Software/AndroidStudio/SDK/platform-tools/adb -P 5037 -s SA17607795 shell dumpsys package io.appium.settings'
[ADB] The installed 'io.appium.settings' package does not require upgrade ('2.3.0' >= '2.3.0')
[ADB] Running '/home/hezj/Software/AndroidStudio/SDK/platform-tools/adb -P 5037 -s SA17607795 shell ps'
[AndroidDriver] io.appium.settings is already running. There is no need to reset its permissions.
[ADB] Device API level: 21
[ADB] Running '/home/hezj/Software/AndroidStudio/SDK/platform-tools/adb -P 5037 -s SA17607795 shell settings put secure mock_location 1'
[AndroidDriver] setDeviceLanguageCountry requires language or country.
[AndroidDriver] Got language: 'undefined' and country: 'undefined'
[Logcat] Starting logcat capture
[AndroidDriver] Pushing unlock helper app to device...
[ADB] Getting install status for io.appium.unlock
[ADB] Running '/home/hezj/Software/AndroidStudio/SDK/platform-tools/adb -P 5037 -s SA17607795 shell pm list packages io.appium.unlock'
[ADB] App is installed
[ADB] Getting package info for 'io.appium.unlock'
[ADB] Running '/home/hezj/Software/AndroidStudio/SDK/platform-tools/adb -P 5037 -s SA17607795 shell dumpsys package io.appium.unlock'
[ADB] The installed 'io.appium.unlock' package does not require upgrade ('2.0.0' >= '2.0.0')
[ADB] Getting device platform version
[ADB] Running '/home/hezj/Software/AndroidStudio/SDK/platform-tools/adb -P 5037 -s SA17607795 shell getprop ro.build.version.release'
[ADB] Current device property 'ro.build.version.release': 5.0
[ADB] Running '/home/hezj/Software/AndroidStudio/SDK/platform-tools/adb -P 5037 -s SA17607795 shell wm size'
[ADB] Running '/home/hezj/Software/AndroidStudio/SDK/platform-tools/adb -P 5037 -s SA17607795 shell getprop ro.product.model'
[ADB] Current device property 'ro.product.model': M5-53
[ADB] Running '/home/hezj/Software/AndroidStudio/SDK/platform-tools/adb -P 5037 -s SA17607795 shell getprop ro.product.manufacturer'
[ADB] Current device property 'ro.product.manufacturer': alps
[AndroidDriver] No app sent in, not parsing package/activity
[AndroidDriver] No app capability. Assuming it is already on the device
[ADB] Getting install status for com.android.settings
[ADB] Running '/home/hezj/Software/AndroidStudio/SDK/platform-tools/adb -P 5037 -s SA17607795 shell pm list packages com.android.settings'
[ADB] App is installed
[ADB] Running '/home/hezj/Software/AndroidStudio/SDK/platform-tools/adb -P 5037 -s SA17607795 shell am force-stop com.android.settings'
[ADB] Running '/home/hezj/Software/AndroidStudio/SDK/platform-tools/adb -P 5037 -s SA17607795 shell pm clear com.android.settings'
[AndroidDriver] Performed fast reset on the installed 'com.android.settings' application (stop and clear)
[AndroidBootstrap] Watching for bootstrap disconnect
[ADB] Forwarding system: 4724 to device: 4724
[ADB] Running '/home/hezj/Software/AndroidStudio/SDK/platform-tools/adb -P 5037 -s SA17607795 forward tcp\:4724 tcp\:4724'
[UiAutomator] Starting UiAutomator
[UiAutomator] Moving to state 'starting'
[UiAutomator] Parsing uiautomator jar
[UiAutomator] Found jar name: 'AppiumBootstrap.jar'
[ADB] Running '/home/hezj/Software/AndroidStudio/SDK/platform-tools/adb -P 5037 -s SA17607795 push /tmp/.mount_appium22wWsP/app/resources/app/node_modules/appium/node_modules/appium-android-bootstrap/bootstrap/bin/AppiumBootstrap.jar /data/local/tmp/'
[ADB] Attempting to kill all uiautomator processes
[ADB] Getting all processes with uiautomator
[ADB] Running '/home/hezj/Software/AndroidStudio/SDK/platform-tools/adb -P 5037 -s SA17607795 shell ps'
[ADB] No uiautomator process found to kill, continuing...
[UiAutomator] Starting UIAutomator
[ADB] Creating ADB subprocess with args: ["-P",5037,"-s","SA17607795","shell","uiautomator","runtest","AppiumBootstrap.jar","-c","io.appium.android.bootstrap.Bootstrap","-e","pkg","com.android.settings","-e","disableAndroidWatchers",false,"-e","acceptSslCerts",false]
[UiAutomator] Moving to state 'online'
[AndroidBootstrap] Android bootstrap socket is now connected
[ADB] Running '/home/hezj/Software/AndroidStudio/SDK/platform-tools/adb -P 5037 -s SA17607795 shell dumpsys window'
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] json loading complete.
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Registered crash watchers.
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Client connected
[AndroidDriver] Screen is locked, trying to unlock
[AndroidDriver] Using app unlock, this is going to be deprecated!
[AndroidDriver] Unlocking screen
[ADB] Running '/home/hezj/Software/AndroidStudio/SDK/platform-tools/adb -P 5037 -s SA17607795 shell am force-stop io.appium.unlock'
[AndroidDriver] Launching io.appium.unlock
[ADB] Device API level: 21
[ADB] Running '/home/hezj/Software/AndroidStudio/SDK/platform-tools/adb -P 5037 -s SA17607795 shell am start -W -n io.appium.unlock/.Unlock -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[ADB] Device API level: 21
[ADB] Running '/home/hezj/Software/AndroidStudio/SDK/platform-tools/adb -P 5037 -s SA17607795 shell am start -W -n com.android.settings/.Settings -S'
[Appium] New AndroidDriver session created successfully, session c6dbdce7-9a8d-4dea-8305-f04ff65c798e added to master session list
[BaseDriver] Event 'newSessionStarted' logged at 1541126218891 (10:36:58 GMT+0800 (CST))
[MJSONWP] Responding to client with driver.createSession() result: {"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"Android","platformVersion":"5.0","deviceName":"SA17607795","appPackage":"com.android.settings","appActivity":".Settings","newCommandTimeout":1000000},"platformName":"Android","platformVersion":"5.0","deviceName":"SA17607795","appPackage":"com.android.settings","appActivity":".Settings","newCommandTimeout":1000000,"deviceUDID":"SA17607795","deviceScreenSize":"540x960","deviceModel":"M5-53","deviceManufacturer":"alps"}
[HTTP] <-- POST /wd/hub/session 200 11881 ms - 714
[HTTP] 
[HTTP] --> POST /wd/hub/session/c6dbdce7-9a8d-4dea-8305-f04ff65c798e/appium/device/push_file
[HTTP] {"path":"/storage/sdcard1/myupdate.zip","data":"UEsDBAoAAAAAAMZiUU3mh7E0qBVuAKgVbgAOAAAAM3JkcGFydC50YXIueHr9N3pYWgAABObWtEYCACEBFgAAAHQv5aPiMYzv/l0ANhpIZkrFUX3nn2wrKa87ZYljTzzfQoTEYiKqCjiGNgEcVlI3fhQ/ol3Hu+86oivHZx9hCouEYcpMC+u6leWS8qkIqpMxB5kZ//AmmHPfKp1xH/e22ebiUEBMhFURiep+jU6XhdS7/HkpR4P8wwIYuOQRbBRMaCTLyL3FWMe3qp5RfzqIkH1JZDV3bZDZDoL41ccqd0QJjzLeTbvq6Lw7/+dNRYpIWE7eOdwKPg5lzD5vdoE0m4zsfIaFrJI+lvgmyuztrgl8TlUbM0DPGhaBhRVgyfa4tTmBsvgJEWdA8X49HqM5XOcB0zu/DTDHOUVxAfEv/LW8MoAxJDMjyFGRM8ax3jmBPl9mX6sbFV7qZsIiDS8Ydoj3FVinwmZt8Z53PI1n174/BXnzk6I+Pk7AX5fby+ibpke2X6BZos/iaP1ih8G9E7ECgdrEk2Sq2qbVNmjntYw1zAhYkJ7Z1EQO668XaTh0/UTE/e5Rs7SHEr2PlKgAAAL3hmC4I1M/WApAsA54IfPFvLpCGQYWcOom6y2HwQ7sDDSlH33u+t0Vb+79J7t3MyG1JgWAFCS83gkTUGtB3/aEEKFtFCqkYtk09CVzualyqpgNEnCCJVlpQAHJ5dia8TZmnm+FChCbFSd5vQ8psZOSCco/CeGvNiHAOY71nMCwaYIHc3mDCvCe6VpXxR0uTDXbIXxClnzeu1HGImQQUZX5ckzaHIIJTbQ/oqqIuFHOaTBn8SDvkwh6LGWEOJYnYKPD1jHTZdIt54FxJzddmdPZ93E/eheHBo3mkw7yMCoz/nXV0aWHRfS4zETXVHvLiiTT71//ArZ7Mvbv1WlR3cuxGZVWPIrQ8i0Q
[W3C] Calling AppiumDriver.pushFile() with args: ["/storage/sdcard1/myupdate.zip","UEsDBAoAAAAAAMZiUU3mh7E0qBVuAKgVbgAOAAAAM3JkcGFydC50YXIueHr9N3pYWgAABObWtEYCACEBFgAAAHQv5aPiMYzv/l0ANhpIZkrFUX3nn2wrKa87ZYljTzzfQoTEYiKqCjiGNgEcVlI3fhQ/ol3Hu+86oivHZx9hCouEYcpMC+u6leWS8qkIqpMxB5kZ//AmmHPfKp1xH/e22ebiUEBMhFURiep+jU6XhdS7/HkpR4P8wwIYuOQRbBRMaCTLyL3FWMe3qp5RfzqIkH1JZDV3bZDZDoL41ccqd0QJjzLeTbvq6Lw7/+dNRYpIWE7eOdwKPg5lzD5vdoE0m4zsfIaFrJI+lvgmyuztrgl8TlUbM0DPGhaBhRVgyfa4tTmBsvgJEWdA8X49HqM5XOcB0zu/DTDHOUVxAfEv/LW8MoAxJDMjyFGRM8ax3jmBPl9mX6sbFV7qZsIiDS8Ydoj3FVinwmZt8Z53PI1n174/BXnzk6I+Pk7AX5fby+ibpke2X6BZos/iaP1ih8G9E7ECgdrEk2Sq2qbVNmjntYw1zAhYkJ7Z1EQO668XaTh0/UTE/e5Rs7SHEr2PlKgAAAL3hmC4I1M/WApAsA54IfPFvLpCGQYWcOom6y2HwQ7sDDSlH33u+t0Vb+79J7t3MyG1JgWAFCS83gkTUGtB3/aEEKFtFCqkYtk09CVzualyqpgNEnCCJVlpQAHJ5dia8TZmnm+FChCbFSd5vQ8psZOSCco/CeGvNiHAOY71nMCwaYIHc3mDCvCe6VpXxR0uTDXbIXxClnzeu1HGImQQUZX5ckzaHIIJTbQ/oqqIuFHOaTBn8SDvkwh6LGWEOJYnYKPD1jHTZdIt54FxJzddmdPZ93E/eheHBo3mkw7yMCoz/nXV0aWHRfS4zETXVHvLiiTT71//ArZ7Mvbv1WlR3cuxGZVWPIrQ8i0QNVuRShyAQIykshY+rzTi4XNQcv5eq3GBOAP...
[ADB] Running '/home/hezj/Software/AndroidStudio/SDK/platform-tools/adb -P 5037 -s SA17607795 push /tmp/appium118102-4690-1ilvzkt.xl6fi.tmp /storage/sdcard1/myupdate.zip'
[ADB] Running '/home/hezj/Software/AndroidStudio/SDK/platform-tools/adb -P 5037 -s SA17607795 push /tmp/appium118102-4690-1ilvzkt.xl6fi.tmp /storage/sdcard1/myupdate.zip'
[MJSONWP] Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command '/home/hezj/Software/AndroidStudio/SDK/platform-tools/adb -P 5037 -s SA17607795 push /tmp/appium118102-4690-1ilvzkt.xl6fi.tmp /storage/sdcard1/myupdate.zip' timed out after 20000ms'; Stderr: ''; Code: 'null'
[MJSONWP]     at ADB.execFunc$ (/tmp/.mount_appium22wWsP/app/resources/app/node_modules/appium/node_modules/appium-adb/lib/tools/system-calls.js:327:13)
[MJSONWP]     at tryCatch (/tmp/.mount_appium22wWsP/app/resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/tmp/.mount_appium22wWsP/app/resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/tmp/.mount_appium22wWsP/app/resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (/tmp/.mount_appium22wWsP/app/resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP]     at 
[HTTP] <-- POST /wd/hub/session/c6dbdce7-9a8d-4dea-8305-f04ff65c798e/appium/device/push_file 500 42928 ms - 428
[HTTP] 
[HTTP] --> DELETE /wd/hub/session/c6dbdce7-9a8d-4dea-8305-f04ff65c798e
[HTTP] {}
[W3C] Calling AppiumDriver.deleteSession() with args: ["c6dbdce7-9a8d-4dea-8305-f04ff65c798e"]
[BaseDriver] Event 'quitSessionRequested' logged at 1541126265669 (10:37:45 GMT+0800 (CST))
[Appium] Removing session c6dbdce7-9a8d-4dea-8305-f04ff65c798e from our master session list
[AndroidDriver] Shutting down Android driver
[ADB] Running '/home/hezj/Software/AndroidStudio/SDK/platform-tools/adb -P 5037 -s SA17607795 shell am force-stop com.android.settings'
[ADB] Pressing the HOME button
[ADB] Running '/home/hezj/Software/AndroidStudio/SDK/platform-tools/adb -P 5037 -s SA17607795 shell input keyevent 3'
[AndroidBootstrap] Sending command to android: {"cmd":"shutdown"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"shutdown"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type SHUTDOWN
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
[AndroidBootstrap] [UIAUTO STDOUT] [CDS]close[4724]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Closed client connection
[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: numtests=1
[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: stream=.
[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: current=1
[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS_CODE: 0
[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: stream=
[AndroidBootstrap] [UIAUTO STDOUT] Test results for WatcherResultPrinter=.
[AndroidBootstrap] [UIAUTO STDOUT] Time: 52.512
[AndroidBootstrap] [UIAUTO STDOUT] OK (1 test)
[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS_CODE: -1
[AndroidBootstrap] Received command result from bootstrap
[UiAutomator] Shutting down UiAutomator
[UiAutomator] Moving to state 'stopping'
[UiAutomator] UiAutomator shut down normally
[UiAutomator] Moving to state 'stopped'
[ADB] Attempting to kill all uiautomator processes
[ADB] Getting all processes with uiautomator
[ADB] Running '/home/hezj/Software/AndroidStudio/SDK/platform-tools/adb -P 5037 -s SA17607795 shell ps'
[ADB] No uiautomator process found to kill, continuing...
[UiAutomator] Moving to state 'stopped'
[Logcat] Stopping logcat capture
[ADB] Running '/home/hezj/Software/AndroidStudio/SDK/platform-tools/adb -P 5037 -s SA17607795 shell am force-stop io.appium.unlock'
[AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[BaseDriver] Event 'quitSessionFinished' logged at 1541126267987 (10:37:47 GMT+0800 (CST))
[MJSONWP] Received response: null
[MJSONWP] But deleting session, so not returning
[MJSONWP] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/c6dbdce7-9a8d-4dea-8305-f04ff65c798e 200 2320 ms - 76

## This client log:

selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/home/hezj/Software/AndroidStudio/SDK/platform-tools/adb -P 5037 -s SA17607795 push /tmp/appium118102-4690-1ilvzkt.xl6fi.tmp /storage/sdcard1/myupdate.zip' timed out after 20000ms'; Stderr: ''; Code: 'null'

## This my code 
```
resource_path = mkResourcesDir()
        local_zip_path = find_file(resource_path, "myupdate.zip")
        with open(local_zip_path, 'rb') as zip_file:
            data = base64.b64encode(zip_file.read()).decode('UTF-8')
        self.driver.push_file('/storage/sdcard1/myupdate.zip', data)
        zip_file.close()
```

**Comment by KazuCocoa** [comment]
`DEFAULT_ADB_EXEC_TIMEOUT = 20000; // in milliseconds` is used in https://github.com/appium/appium-android-driver/blob/d16c7161d92ab6f6c9cec3f22218219ac3659716/lib/commands/actions.js#L198

@Ucoon Could you tell us how large the zip file is? (Or how long does it take to complet push command?)
You can run `/home/hezj/Software/AndroidStudio/SDK/platform-tools/adb -P 5037 -s SA17607795 push /tmp/appium118102-4690-1ilvzkt.xl6fi.tmp /storage/sdcard1/myupdate.zip`. We'd like to know how long the command takes.
(Maybe, you should replace `/tmp/appium118102-4690-1ilvzkt.xl6fi.tmp` properly.)

**Comment by KazuCocoa** [comment]
oh, appium-android-driver has `adbExecTimeout`.

@Ucoon What about adding `adbExecTimeout` in your capability like `newCommandTimeout`?
I'll add it in the documentation of capability.

**Comment by KazuCocoa** [comment]
link https://github.com/appium/appium-adb/pull/373
Maybe, we need the change to apply `adbExecTimeout` in `appium-adb` instance

**Comment by KazuCocoa** [comment]
ah.. thanks. > size and time

`adbExecTimeout` probably works with appium/appium-adb#373 
If you can apply the change in your locale, it works.

**Comment by Ucoon** [comment]
Should I change my code from python to js? it seems that appium-android-driver working in js

**Comment by KazuCocoa** [comment]
No. That is Appium server side. It doesn't in the client thing.

You can wait for publishing the new version. Then, you can try it with `appium@beta`

**Comment by Ucoon** [comment]
OK. thanks.  Looking forward the new version that solved this problem.

**Comment by KazuCocoa** [comment]
@Ucoon 
This should work the latest `appium@beta` as `adbExecTimeout` capability
