### ISSUE TITLE
disableAndroidWatchers not recognized

### ISSUE THREAD

**Issue by daviesdoclc** [appium/appium#11620]
## The problem

The fans kick on quite frequently during my Android simulator tests.  I was trying to set disableAndroidWatchers, but Appium 1.9.1 says it's not recognized.

018-11-02 13:24:09:300 - warn: [BaseDriver] The following capabilities were provided, but are not recognized by appium: disableAndroidWatchers.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable): unknown
* Desktop OS/version used to run Appium: MacOS X 10.14
* Node.js version (unless using Appium.app|exe): 10.12.0
* Mobile platform/version under test: Android 7.1.1
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: CLI

## Details

None

## Link to Appium logs

None

## Code To Reproduce Issue [ Good To Have ]

None

**Comment by mykola-mokhnach** [comment]
This option is only support to work with UIA1, but not with UIA2

**Comment by daviesdoclc** [comment]
@mykola-mokhnach ah thanks. I missed that.
