### ISSUE TITLE
Appium with Xcode 10.1 simulator not updating display

### ISSUE THREAD

**Issue by daviesdoclc** [appium/appium#11621]
## The problem

Since installing Xcode 10.1, when running iOS simulator tests the simulator launches and the tests run successfully, but the display on the simulator never changes.  You don't see the app or webdriver installation, app launch, or any of the ui.  The app runs fine on the simulator when run by hand.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable): unknown
* Desktop OS/version used to run Appium: MacOS 10.14.1
* Node.js version (unless using Appium.app|exe): 10.12.0
* Mobile platform/version under test: iOS 12.1
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI

## Details

You can see a video of it here https://www.dropbox.com/s/dc13f94pkyyjohw/appium-ios-simulator.mov?dl=0

## Link to Appium logs

N/A

## Code To Reproduce Issue [ Good To Have ]

N/A

**Comment by daviesdoclc** [comment]
Almost acts as if isHeadless capability is true, except for the fact the simulator is launched.

**Comment by jcalabek** [comment]
We also ran into the same issue. It looks like the simulator completely freezes up and the the only way to resolve the issues is to restart the simulator. We've tested running iOS 12.0 simulator from Xcode 10.1 but still running into the same issue.

**Comment by mykola-mokhnach** [comment]
This looks like Xcode/Simulator issue to me

**Comment by Power041** [comment]
I was having the same issue, what fixed it for me was to remove the `fullReset` capability.

**Comment by daviesdoclc** [comment]
@Power041 hmmm... we aren't using full reset. And it doesn't freeze up per se.  It just doesn't display what it's doing.  The test completes fine.

**Comment by Power041** [comment]
I turned off full reset because when the tests were starting, you could see Appium bring up the simulator once and then kill it and try to bring it back up again. This is normal behaviour as per 1.8.1 and xcode 9.4, but on xcode 10.1 (even 10 is having these issues) and iOS 11.4 and 12.1, when the simulator is being brought up the second time, it's frozen, sometimes even the frame would be stuck (iPhone 6 frame on an iPhone X simulator), or stuck on the boot loading screen. But, as you said, the tests are running fine, and if you try inspecting the UI using xcode, you can clearly see the app screen like it should be shown in the simulator.

Restarting the simulator via Hardware > Restart seems to fix this too, but appium throws an exception and fails the test.

**Comment by derunewige** [comment]
@Power041 I have observed exactly the same situation. It occurred after updating xcode to version 10.1. I was quite confused and tried a couple of things like downgrading to xcode 10.0, completely new reinstall of xcode, reinstall of appium... Unfortunately nothing helped.

**Comment by devstrat** [comment]
The only thing that reliably fixes the problem (downgrading to the previous xcode version will not help most of the time) is to find someone with a pre-10.1 xcode and take their "/Library/Developer/PrivateFrameworks/CoreSimulator.framework" folder and replace yours with it. This fixes the issue until Apple does something about it. Enjoy

**Comment by daviesdoclc** [comment]
@devstrat thanks! that worked.

**Comment by benzman81** [comment]
@devstrat is working for us, too

**Comment by emayala** [comment]
Does anyone have a zip file containing the contents of an older version of the "/Library/Developer/PrivateFrameworks/CoreSimulator.framework" folder?

**Comment by BasouKazuma** [comment]
Here is a copy of the "/Library/Developer/PrivateFrameworks/CoreSimulator.framework" folder taken from a computer running Xcode 10.0 for people to download in the meantime.
https://drive.google.com/file/d/17ga-1V3sESWXOVrLwqXizfGCvu_Obar0/view?usp=sharing

**Comment by CristianSchez** [comment]
For me the workaround of the replacement of the folder "/Library/Developer/PrivateFrameworks/CoreSimulator.framework" does not work

**Comment by PraveenKumarQA** [comment]
@BasouKazuma , Thanks the work around mentioned worked for me, so what I have done
Downloaded and installed Xcode 10.0
Copied and pasted CoreSimulator.Framework as mentioned in #11621
Updated Pom.xml, Selenium-java - 3.9.1, java-client - 6.0.0-BETA5
And it started working, Thanks again @BasouKazuma

**Comment by ganjarpanji** [comment]
little bit OOT, hi @daviesdoclc how you can manage setup your test app to launch with mocked state and run test with appium? or is there any link that could guide me to implement that? thanks in advance !

**Comment by ilearnio** [comment]
Restarting appium server helped! Thanks to http://www.qaautomationsimplified.com/android/restarting-appium-server-improve-various-server-freezing-issues-may-improve-execution-time/

**Comment by cwsears** [comment]
@BasouKazuma and @devstrat You are wonderful. Thank you.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
