### ISSUE TITLE
Failed on connecting to Appium server

### ISSUE THREAD

**Issue by BoazWarshawsky** [appium/appium#11625]
## The problem
My test fail on connecting to appium server when calling:
webdriver.Remote(appium_server_url, self.desired_caps)

**My device is new and I managed to build successfully all targets in WebDriverAgent app**

## Environment
* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable): None
* Desktop OS/version used to run Appium: Mac 1.7.1
* Node.js version (unless using Appium.app|exe): v8.11.2
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium.app

## Details

**My device is new and I managed to build successfully all targets in WebDriverAgent app**

## Link to Appium logs

[JSONWP Proxy] Matched '/status' to command name 'getStatus'
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Matched '/status' to command name 'getStatus'
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] 2018-11-04 12:22:13.963 xcodebuild[85860:1988629]  iPhoneConnect: 📱 failed to install /Users/boazw/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app - error Error Domain=com.apple.dtdevicekit Code=-402620395 "App installation failed" UserInfo={NSLocalizedDescription=App installation failed, com.apple.dtdevicekit.stacktrace=(
[Xcode] 	0   DTDeviceKitBase                     0x0000000110a0ac61 DTDKCreateNSError + 113
[Xcode] 	1   DTDeviceKitBase                     0x0000000110a0b4a9 DTDK_AMDErrorToNSError + 1139
[Xcode] 	2   DTDeviceKitBase                     0x0000000110a4d2c2 __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 158
[Xcode] 	3   DVTFoundation                       0x000000010655fd8b DVTInvokeWithStrongOwnership + 73
[Xcode] 	4   DTDeviceKitBase                     0x0000000110a4cff0 -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1432
[Xcode] 	5   IDEiOSSupportCore                   0x0000000110930045 __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.342 + 4116
[Xcode] 	6   DVTFoundation                       0x00000001066960a6 __DVTDispatchAsync_block_invoke + 801
[Xcode] 	7   libdispatch.dylib                   0x00007fff7e92cd4f _dispatch_call_block_and_release + 12
[Xcode] 	8   libdispatch.dylib                   0x00007fff7e92ddcb _dispatch_client_callout + 8
[Xcode] 	9   libdispatch.dylib                   0x00007fff7e934120 _dispatch_lane_serial_drain + 618
[Xcode] 	10  libdispatch.dylib                   0x00007fff7e934bd8 _dispatch_lane_invoke + 388
[Xcode] 	11  libdispatch.dylib                   0x00007fff7e93d084 _dispatch_workloop_worker_thread + 603
[Xcode] 	12  libsystem_pthread.dylib             0x00007fff7eb6d61c _pthread_wqthread + 409
[Xcode] 	13  libsystem_pthread.dylib             0x00007fff7eb6d415 start_wqthread + 13
[Xcode] ), NSLocalizedRecoverySuggestion=A valid provisioning profile for this executable was not found., NSLocalizedFailureReason=A valid provisioning profile for this executable was not found.}
[Xcode] 
[Xcode] 
[Xcode] 
[Xcode] *** If you believe this error represents a bug, please attach the result bundle at /Users/boazw/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2018.11.04_12-22-11-+0200.xcresult
[Xcode] 
[Xcode] 
[Xcode] 2018-11-04 12:22:13.968 xcodebuild[85860:1988349] [MT] IDETestOperationsObserverDebug: 2.071 elapsed -- Testing started completed.
[Xcode] 2018-11-04 12:22:13.968 xcodebuild[85860:1988349] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
[Xcode] 
[Xcode] 2018-11-04 12:22:13.968 xcodebuild[85860:1988349] [MT] IDETestOperationsObserverDebug: 2.071 sec, +2.071 sec -- end
[Xcode] 2018-11-04 12:22:13.968 xcodebuild[85860:1988349] Error Domain=com.apple.dtdevicekit Code=-402620395 "App installation failed" UserInfo={NSLocalizedDescription=App installation failed, com.apple.dtdevicekit.stacktrace=(
[Xcode] 	0   DTDeviceKitBase                     0x0000000110a0ac61 DTDKCreateNSError + 113
[Xcode] 	1   DTDeviceKitBase                     0x0000000110a0b4a9 DTDK_AMDErrorToNSError + 1139
[Xcode] 	2   DTDeviceKitBase                     0x0000000110a4d2c2 __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 158
[Xcode] 	3   DVTFoundation                       0x000000010655fd8b DVTInvokeWithStrongOwnership + 73
[Xcode] 	4   DTDeviceKitBase                     0x0000000110a4cff0 -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1432
[Xcode] 	5   IDEiOSSupportCore                   0x0000000110930045 __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.342 + 4116
[Xcode] 	6   DVTFoundation                       0x00000001066960a6 __DVTDispatchAsync_block_invoke + 801
[Xcode] 	7   libdispatch.dylib                   0x00007fff7e92cd4f _dispatch_call_block_and_release + 12
[Xcode] 	8   libdispatch.dylib                   0x00007fff7e92ddcb _dispatch_client_callout + 8
[Xcode] 	9   libdispatch.dylib                   0x00007fff7e934120 _dispatch_lane_serial_drain + 618
[Xcode] 	10  libdispatch.dylib                   0x00007fff7e934bd8 _dispatch_lane_invoke + 388
[Xcode] 	11  libdispatch.dylib                   0x00007fff7e93d084 _dispatch_workloop_worker_thread + 603
[Xcode] 	12  libsystem_pthread.dylib             0x00007fff7eb6d61c _pthread_wqthread + 409
[Xcode] 	13  libsystem_pthread.dylib             0x00007fff7eb6d415 start_wqthread + 13
[Xcode] ), NSLocalizedRecoverySuggestion=A valid provisioning profile for this executable was not found., NSLocalizedFailureReason=A valid provisioning profile for this executable was not found.}
[Xcode] 2018-11-04 12:22:13.968 xcodebuild[85860:1988349] Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Failed to install or launch the test runner" UserInfo={NSLocalizedRecoverySuggestion=If you believe this error represents a bug, please attach the result bundle at /Users/boazw/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2018.11.04_12-22-11-+0200.xcresult, NSLocalizedDescription=Failed to install or launch the test runner, NSUnderlyingError=0x7fab68c72f70 {Error Domain=com.apple.dtdevicekit Code=-402620395 "App installation failed" UserInfo={NSLocalizedDescription=App installation failed, com.apple.dtdevicekit.stacktrace=(
[Xcode] 	0   DTDeviceKitBase                     0x0000000110a0ac61 DTDKCreateNSError + 113
[Xcode] 	1   DTDeviceKitBase                     0x0000000110a0b4a9 DTDK_AMDErrorToNSError + 1139
[Xcode] 	2   DTDeviceKitBase                     0x0000000110a4d2c2 __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 158
[Xcode] 	3   DVTFoundation                       0x000000010655fd8b DVTInvokeWithStrongOwnership + 73
[Xcode] 	4   DTDeviceKitBase                     0x0000000110a4cff0 -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1432
[Xcode] 	5   IDEiOSSupportCore                   0x0000000110930045 __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.342 + 4116
[Xcode] 	6   DVTFoundation                       0x00000001066960a6 __DVTDispatchAsync_block_invoke + 801
[Xcode] 	7   libdispatch.dylib                   0x00007fff7e92cd4f _dispatch_call_block_and_release + 12
[Xcode] 	8   libdispatch.dylib                   0x00007fff7e92ddcb _dispatch_client_callout + 8
[Xcode] 	9   libdispatch.dylib                   0x00007fff7e934120 _dispatch_lane_serial_drain + 618
[Xcode] 	10  libdispatch.dylib                   0x00007fff7e934bd8 _dispatch_lane_invoke + 388
[Xcode] 	11  libdispatch.dylib                   0x00007fff7e93d084 _dispatch_workloop_worker_thread + 603
[Xcode] 	12  libsystem_pthread.dylib             0x00007fff7eb6d61c _pthread_wqthread + 409
[Xcode] 	13  libsystem_pthread.dylib             0x00007fff7eb6d415 start_wqthread + 13
[Xcode] ), NSLocalizedRecoverySuggestion=A valid provisioning profile for this executable was not found., NSLocalizedFailureReason=A valid provisioning profile for this executable was not found.}}}
[Xcode] 
[Xcode] 
[Xcode] Testing failed:
[Xcode] 	Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor. (in target 'WebDriverAgentRunner')
[Xcode] 	WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: App installation failed. A valid provisioning profile for this executable was not found.))
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[Xcode] Testing started on 'Qa gmail’s iPhone'
[Xcode] ## Code To Reproduce Issue [ Good To Have ]

**Comment by BoazWarshawsky** [comment]
Hi @KazuCocoa the team id shuold is fine and I also did what is ask in https://support.apple.com/en-ng/HT204460, but it still fails with the same error

**Comment by KazuCocoa** [comment]
What about below method? @BoazWarshawsky 

1. Install another app in the device with the `team id` credential
    - And launch it
2. Run your appium test

The 1st step's app is okay just after creating sample project from Xcode template. The point is you will pre-install any apps signed by the `team id` before installing and launching Appium's WebDriverAgent and test apps.

If your error is launching apps, this probably helps. (Mine was fixed by this way before I faced a similar issue.)

**Comment by BoazWarshawsky** [comment]
Hi @KazuCocoa , 
I am now getting this error:
[Xcode] Testing failed:
[Xcode] 	No profiles for 'com.facebook.WebDriverAgentRunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.facebook.WebDriverAgentRunner'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'WebDriverAgentRunner')
[Xcode] 	WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: App installation failed. A valid provisioning profile for this executable was not found.))
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **

**Comment by KazuCocoa** [comment]
It says Xcode can't find proper provisioning file in your env to install the built app into your device.

What about adding _updatedWDABundleId_ like `updatedWDABundleId: your.team.id.WebDriverAgentRunner`?
https://github.com/appium/appium-xcuitest-driver

It replaces `com.facebook.WebDriverAgentRunner` to the bundle id.
@BoazWarshawsky

**Comment by BoazWarshawsky** [comment]
@KazuCocoa 
Getting this:

[Xcode] Testing failed:
[Xcode] 	No profiles for 'com.facebook.wda.runner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.facebook.wda.runner'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'WebDriverAgentRunner')
[Xcode] 
[Xcode] 	WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: App installation failed. A valid provisioning profile for this executable was not found.))
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[Xcode] Testing started on 'Qa gmail’s iPhone'

Did I copied the bundle identifier correctly?

**Comment by BoazWarshawsky** [comment]
@KazuCocoa 
[Xcode] Testing failed:
[Xcode] 	No profiles for 'com.facebook.wda.runner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.facebook.wda.runner'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'WebDriverAgentRunner')
[Xcode] 
[Xcode] 	WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: App installation failed. A valid provisioning profile for this executable was not found.))
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[Xcode] Testing started on 'Qa gmail’s iPhone'

Did I copy correctly the bundle identifier?

**Comment by BoazWarshawsky** [comment]
![screen shot 2018-11-06 at 13 31 22](https://user-images.githubusercontent.com/32813176/48061624-49a41900-e1c8-11e8-8dde-49c73b77b70e.png)

**Comment by BoazWarshawsky** [comment]
My desire capabilities:
![screen shot 2018-11-06 at 13 33 11](https://user-images.githubusercontent.com/32813176/48061723-90920e80-e1c8-11e8-9f91-cdffd808dece.png)

**Comment by KazuCocoa** [comment]
The bundle id must be your organisation identifier valided by your provisioning profile.

For example, if your organisation is `com.example`, the bundle id must be `com.example.xxxx`.
You specified `com.facebook`. It means your organisation is facebook.

Provisioning profile valids the organisation identifier. If your provisioning profile valids `com.example`, the profile probably valids for `com.example.*`, for example.

Thus,

1. you must make sure what organisation identifier is valides by the xcodeOrgId's profiler 
2. Set the identiifer instead of `com.facebook`

**Comment by BoazWarshawsky** [comment]
@KazuCocoa 
When saying "Set the identiifer instead of com.facebook",
for what target?
WebDriverAgentRunner
WebDriverAgentLib
?

**Comment by BoazWarshawsky** [comment]
@KazuCocoa Problem solved, 
You can close the ticket.

Issue was that the team id (7 characters) was not matching to the account id which I was building with the WebDriverAgentRunner.

My group at work has 2 accounts for development. 

Thanks!
