### ISSUE TITLE
Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "The element '"(topicButton)" Button' is not visible on the screen and thus is not interactable"

### ISSUE THREAD

**Issue by EchoWang1024** [appium/appium#11635]
## The problem
hi~ 
I can't click on some elements in our app recommendation page. and the visible attribute of this element is false

## Environment
- Appium version :1.9.1
- Desktop OS/version used to run Appium: macOS 10.14
- Node.js version: 8.10.0
- Mobile platform/version under test: iOS11.4.1
- Real device or emulator/simulator: Real Device

## Link to Appium logs
https://gist.github.com/EchoWang1024/6f38e63a46ed5b76a2d9f0c9536812bc

## Screenshot
![17_00_35__11_06_2018](https://user-images.githubusercontent.com/29889237/48053493-d01b2380-e1e5-11e8-8a89-602efb29a9c9.jpg)

**Comment by mykola-mokhnach** [comment]
The visibility state is handled by XCTest. Please report the problem to Apple.
