### ISSUE TITLE
driver.getTitle() throws "Method has not yet been implemented"

### ISSUE THREAD

**Issue by anand853** [appium/appium#11631]
## Environment

* Appium version (or git revision) that exhibits the issue:1.8.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]
[HTTP] <-- POST /wd/hub/session/fdb4eaef-2a06-41c8-a732-caee083c8cf3/element/3/click 200 156 ms - 14
[HTTP] 
[HTTP] --> GET /wd/hub/session/fdb4eaef-2a06-41c8-a732-caee083c8cf3/title
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.title() with args: ["fdb4eaef-2a06-41c8-a732-caee083c8cf3"]
[HTTP] <-- GET /wd/hub/session/fdb4eaef-2a06-41c8-a732-caee083c8cf3/title 404 5 ms - 2388
[HTTP] 
[HTTP] --> GET /wd/hub/session/fdb4eaef-2a06-41c8-a732-caee083c8cf3/title
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.title() with args: ["fdb4eaef-2a06-41c8-a732-caee083c8cf3"]
[HTTP] <-- GET /wd/hub/session/fdb4eaef-2a06-41c8-a732-caee083c8cf3/title 404 4 ms - 2388

**Comment by dpgraham** [comment]
This is expected. `title` isn't a supported endpoint in Appium native contexts (Android, IOS native app automation).

If you're testing a webview (do so by setting `autoWebView=true` or switching to a web context (http://appium.io/docs/en/commands/context/set-context/)) and then `getTitle` will work.
