### ISSUE TITLE
【Appium-1.9.1】 uncaughtException: Android bootstrap socket crashed: Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by csmijo** [appium/appium#11632]
## The problem

mac os,  appium 1.9.1 ,  run simple  python test , but find error.

uncaughtException: Android bootstrap socket crashed: Error: connect ETIMEDOUT
{"date":"Tue Nov 06 2018 13:04:48 GMT+0800 (中国标准时间)","process":{"pid":8819,"uid":501,"gid":20,"cwd":"/Users/arvin","execPath":"/usr/local/Cellar/node/11.1.0/bin/node","version":"v11.1.0","argv":["/usr/local/Cellar/node/11.1.0/bin/node","/usr/local/bin/appium"],"memoryUsage":{"rss":111190016,"heapTotal":80097280,"heapUsed":67359832,"external":135164}},"os":{"loadavg":[2.08984375,2.09765625,2.1513671875],"uptime":5725},"trace":[{"column":21,"file":"/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/bootstrap.js","function":null,"line":97,"method":null,"native":false},{"column":13,"file":"events.js","function":"Socket.emit","line":182,"method":"emit","native":false},{"column":8,"file":"internal/streams/destroy.js","function":"emitErrorNT","line":82,"method":null,"native":false},{"column":3,"file":"internal/streams/destroy.js","function":"emitErrorAndCloseNT","line":50,"method":null,"native":false},{"column":19,"file":"internal/process/next_tick.js","function":"process.internalTickCallback","line":72,"method":"internalTickCallback","native":false}],"stack":["Error: Android bootstrap socket crashed: Error: connect ETIMEDOUT 30.129.144.64:4724","    at Socket.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/bootstrap.js:97:21)","    at Socket.emit (events.js:182:13)","    at emitErrorNT (internal/streams/destroy.js:82:8)","    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)","    at process.internalTickCallback (internal/process/next_tick.js:72:19)"]}

## Environment
* appium : 1.9.1
* node : v11.1.0

**Comment by mykola-mokhnach** [comment]
1. Downgrade node to v10
2. Use uia2 for Androd 6+

Closed as duplicate
