### ISSUE TITLE
find element by image does not work in chrome sessions

### ISSUE THREAD

**Issue by jlipps** [appium/appium#11638]
## The problem

You'd expect find element by image to work on any platform since it doesn't rely on anything outside of base driver to work. But it doesn't work in Chrome sessions, presumably because our proxying happens before we look inside the find element call to determine that it is an `-image` strategy.

Not sure what the most elegant solution would be; I don't really like the idea of peeking into every findElement call before continuing with the proxy but maybe it's not that hard/ugly.

(cc in-person reporter @jcneally)

**Comment by mykola-mokhnach** [comment]
I believe this is now fixed after we have plugins
