### ISSUE TITLE
Android emulator interferance from other apps

### ISSUE THREAD

**Issue by WildOrangutan** [appium/appium#11634]
## The problem

Just having some random thoughts, that it would maybe be nice, if we could automatically "filter out" random dialogs (see pictures) from apps, that are __not__ currently being tested. 
Maybe in a similar way that permission dialogs are automatically "dealt with".

[system ui crash](https://user-images.githubusercontent.com/5972966/48052676-f078bd00-e1a8-11e8-8432-cbae2c85ff2c.png)
[google app crash](https://user-images.githubusercontent.com/5972966/48052660-e8b91880-e1a8-11e8-9fec-f91f75808cc9.png)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Desktop OS/version used to run Appium: Linux (can't see details)
* Node.js version (unless using Appium.app|exe): 7.4.0
* Mobile platform/version under test: Android AVD 23, 25
* Appium CLI or Appium.app|exe: CLI

**Comment by mykola-mokhnach** [comment]
Feel free to push a PR if you know how to handle these.
