### ISSUE TITLE
Appium beta: set/get geolocation is not working for Android emulator

### ISSUE THREAD

**Issue by vlprus** [appium/appium#11630]
## The problem

Trying to use geolocation for testing on the android studio emulator with Appium beta.
Using wd api. After calling driver.getGeoLocation(), getting error (Ran "adb root"):

Error: [getGeoLocation()] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: Cannot parse the actual location values from the command output: Broadcasting: Intent { act=io.appium.settings.location flg=0x400000 cmp=io.appium.settings/.receivers.LocationInfoReceiver }

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.9.2-beta.2
* Last Appium version that did not exhibit the issue (if applicable): - 
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): v8.11.3
* Mobile platform/version under test: Android 
* Real device or emulator/simulator: Emulator 28 API

**Comment by mykola-mokhnach** [comment]
What is the version of io.appium.settings component?

**Comment by vlprus** [comment]
Version: 5.6.0
Info that might help:
On the lab run we start of the fresh device and use "install -g Appium@beta --chromedriver+version="2.40"", so all the io settings should be installed correctly if I understand this correctly.

**Comment by vlprus** [comment]
Shouldn't it install it with beta appium by default or you are talking about the chromedriver version?

**Comment by mykola-mokhnach** [comment]
yes it should be installed together with the recent beta

**Comment by antovrv** [comment]
@mykola-mokhnach I'm using appium v1.9.2-beta.2. Also as we discussed in appium forum, I've manually intsalled io.appium.setting v2.10.0. But still now get location not working. And I couldn't install v1.9.2-beta.**3** as well. Kindly suggest me on how to make this work?

**Comment by mykola-mokhnach** [comment]
@antovrv Check out https://github.com/appium/io.appium.settings sources and debug network location feature on your device

**Comment by antovrv** [comment]
Yes @mykola-mokhnach I've already checkout and installed the latest version 2.10.0 and installed in the device. Where should I see debug network location? I'm using samsung.

**Comment by mykola-mokhnach** [comment]
I mean you should understand and debug the source code to figure out why it does not work for you

**Comment by antovrv** [comment]
Is there any fixes in 1.9.2-beta.3 related to this get location? I couldn't install beta.3

**Comment by sp090** [comment]
Mobile web geo location disabled using chromeoption not working .
Please help me out in this situation.
