### ISSUE TITLE
Appium taking long time get response from server

### ISSUE THREAD

**Issue by saigovindu** [appium/appium#11639]
## The problem

I had setup selenium hub with appium node and tried to run 100 test cases(all test cases same) sequentially, for the first 58< test cases running fast(around 12 seconds) after that each test case taking (80 seconds) to run. After looking at the logs, i found appium is waiting (around 60 seconds) to get response from server. 

2018-11-05 13:20:56:858 - [debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.9.1","git-sha":"f9ee7d068e14f10729f88ebd85db802c2e8ac21a","built":"2018-09-20T18:14:29Z"}}
2018-11-05 13:20:56:859 - [HTTP] <-- GET /wd/hub/status 200 4 ms - 151
2018-11-05 13:20:56:859 - [HTTP] 

after 60 seconds, Appium get the following, and start to run
2018-11-05 13:21:57:314 - [debug] [JSONWP Proxy] Got response with status 200: {"value":{"sessionId":"8A26BA3C-7392-4291-A567-6422C756DEB5","capabilities":{"device":"iphone","browserName":"Safari","sdkVersion":"10.1","CFBundleIdentifier":"com.apple.mobilesafari"}},"sessionId":"8A26BA3C-7392-4291-A567-6422C756DEB5","status":0}

## Environment

Appium version (or git revision) that exhibits the issue: 1.9.1,
Desktop OS/version used to run Appium: Mac OS 10.11.6
Node.js version (unless using Appium.app|exe): v8.12.0
Mobile platform/version under test: iOS 10.1
Real device or emulator/simulator: simulator
Appium CLI or Appium.app|exe: CLI
Xcode version: 8.1

## Link to Appium logs
Log: https://gist.github.com/saigovindu/d8fa7ca5226d8ea701fca8111fe667c0

## Code To Reproduce Issue [ Good To Have ]
Currently, I was able to run all test cases(open safari-> search test and scroll and take screenshot) but after 55 test cases appium taking more time to execute.

if i restart the simulator then it working as expected for first 55 test cases.

**Comment by mykola-mokhnach** [comment]
Session init performance depends on WebDriverAgent, which is a third party component. I don't think there is anything, that can be changed in Appium.

You could also try to analyze the device logs.

**Comment by saigovindu** [comment]
Thanks for the quick response, where can I find the device logs in MAC?

**Comment by saigovindu** [comment]
I can see following failures in system.log. is this something related to appium? or do you have any idea on this @mykola-mokhnach ?.


Nov  6 13:47:07 Bings-Mac-mini CoreSimulatorBridge[8844]: Pasteboard change listener callback port <NSMachPort: 0x7fb940f09010> registered
--
  |   |   |   | 84 | Nov  6 13:47:38 Bings-Mac-mini CoreSimulatorBridge[8844]: Pasteboard change listener callback port <NSMachPort: 0x7fb940e05ab0> registered
  |   |   |   | 85 | Nov  6 13:47:58 Bings-Mac-mini logd[6544]: metadata shared cached uuid is null (using logd's shared cache info) coresymbolicati (8875)
  |   |   |   | 86 | Nov  6 13:47:58 Bings-Mac-mini logd[6544]: Failed to harvest strings for pathless uuid '00000000-0000-0000-0000-000000000000'
  |   |   |   | 87 | Nov  6 13:47:58 Bings-Mac-mini WebDriverAgentRunner-Runner[6622]: Enqueue Failure: UI Testing Failure - App accessibility isn't loaded <unknown> 0 1

**Comment by mykola-mokhnach** [comment]
> Nov  6 13:47:58 Bings-Mac-mini WebDriverAgentRunner-Runner[6622]: Enqueue Failure: UI Testing Failure - App accessibility isn't loaded 0 1

This must be some XCTest issue. I'd try to check on Apple side.
