### ISSUE TITLE
appium_doctor_mojave_error

### ISSUE THREAD

**Issue by jpita** [appium/appium#11636]
## The problem

Using appium-doctor with macOS Mojave I'm getting an error

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.0
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: macOS Mojave 10.14
* Node.js version (unless using Appium.app|exe): v10.8.0
* Mobile platform/version under test: ios
* Real device or emulator/simulator: N/A
* Appium CLI or Appium.app|exe: CLI

## Details

Using appium-doctor with macOS Mojave I'm getting this error
`Error: Could not detect Mac OS X Version from sw_vers output: '10.14'
    at Object.macOsxVersion$ (/usr/local/lib/node_modules/appium-doctor/node_modules/appium-support/lib/system.js:43:11)
    at tryCatch (/usr/local/lib/node_modules/appium-doctor/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium-doctor/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium-doctor/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium-doctor/node_modules/babel-runtime/regenerator/runtime.js:136:37)`

## Link to Appium logs

https://gist.github.com/jpita/033ffc9f0152d9189e0525912fe8b3d2

## Code To Reproduce Issue [ Good To Have ]

`appium-doctor --ios`

**Comment by mykola-mokhnach** [comment]
This issue was fixed in appium@beta
Closed as duplicate

**Comment by jpita** [comment]
@mykola-mokhnach thanks.
how can I install appium@beta?

**Comment by jpita** [comment]
@mykola-mokhnach  just installed appium beta and isn't fixed 

`npm install -g appium@beta` 

and

1.9.2-beta.2

**Comment by mykola-mokhnach** [comment]
What is the version of appium-doctor module?

**Comment by mykola-mokhnach** [comment]
It should be at 1.6.0

**Comment by jpita** [comment]
maybe npm is not installing the latest beta for some reason, on the releases page there's a beta.3 but npm installs beta.2

any way I can force it?

**Comment by mykola-mokhnach** [comment]
npm uninstall -g appium-doctor
npm install -g appium-doctor

**Comment by jpita** [comment]
for some reason I had appium-doctor installed on two different locations, had to manually delete the module from the node_modules folder and reinstall it.

thanks for the help.

**Comment by antovrv** [comment]
@mykola-mokhnach Why installing appium@1.9.2-beta.3 throws an error?
> npm install -g appium@1.9.2-beta.3

Error log:
npm ERR! code ETARGET
npm ERR! notarget No matching version found for appium@1.9.2-beta.3
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/anto/.npm/_logs/2018-11-16T10_14_59_802Z-debug.log

> anto@beijing:~$ sudo npm install -g appium@1.9.2-beta.3
> npm ERR! Linux 4.15.0-34-generic
> npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "appium@1.9.2-beta.3"
> npm ERR! node v8.10.0
> npm ERR! npm  v3.5.2
> 
> npm ERR! No compatible version found: appium@1.9.2-beta.3
> npm ERR! Valid install targets:
> npm ERR! 1.9.2-beta.2, 1.9.2-beta.1, 1.9.1, 1.9.1-beta2, 1.9.0, 1.9.0-beta.1, 1.8.2-beta, 1.8.1, 1.8.1-beta1, 1.8.0, 1.8.0-beta5, 1.8.0-beta4, 1.8.0-beta3, 1.8.0-beta, 1.7.2, 1.7.2-beta5, 1.7.2-beta4, 1.7.2-beta3, 1.7.2-beta2, 1.7.2-beta, 1.7.1, 1.7.0, 1.7.0-beta, 1.6.6-beta.4, 1.6.6-beta.3, 1.6.6-beta.2, 1.6.6-beta, 1.6.5, 1.6.5-beta, 1.6.4, 1.6.4-beta.2, 1.6.4-beta, 1.6.3, 1.6.2, 1.6.1, 1.6.1-beta, 1.6.0, 1.6.0-beta3, 1.6.0-beta2, 1.6.0-beta1, 1.5.3, 1.5.2, 1.5.1, 1.5.0, 1.5.0-beta7, 1.5.0-beta6, 1.5.0-beta5, 1.5.0-beta4, 1.5.0-beta3, 1.5.0-beta2, 1.5.0-beta16, 1.5.0-beta15, 1.5.0-beta14, 1.5.0-beta13, 1.5.0-beta12, 1.5.0-beta11, 1.5.0-beta1, 1.4.16, 1.4.15, 1.4.14, 1.4.13, 1.4.12, 1.4.11, 1.4.10, 1.4.9-beta, 1.4.8, 1.4.8-beta, 1.4.7, 1.4.7-beta3, 1.4.7-beta2, 1.4.7-beta, 1.4.6, 1.4.6-beta2, 1.4.6-beta, 1.4.5, 1.4.5-beta, 1.4.4, 1.4.3, 1.4.3-beta, 1.4.2, 1.4.1, 1.4.0, 1.4.0-beta, 1.3.7, 1.3.6, 1.3.5, 1.3.5-beta, 1.3.4, 1.3.4-beta1, 1.3.3, 1.3.2-beta2, 1.3.1, 1.3.0, 1.3.0-beta1, 1.2.4, 1.2.3, 1.2.2, 1.2.1, 1.2.0, 1.1.0, 1.0.0, 1.0.0-beta.2, 1.0.0-beta.1, 0.18.2, 0.18.1, 0.18.0, 0.17.6, 0.17.5, 0.17.4, 0.17.3, 0.17.2, 0.17.0, 0.16.0, 0.15.0, 0.14.2, 0.14.1, 0.14.0, 0.13.0, 0.12.3, 0.12.2, 0.12.1-b, 0.12.0, 0.11.4, 0.11.3, 0.11.2, 0.11.1, 0.11.0, 0.10.4, 0.10.3, 0.10.2, 0.10.1, 0.10.0, 0.9.1, 0.9.0, 0.8.5, 0.8.4, 0.8.3, 0.8.2, 0.8.1, 0.8.0, 0.7.3, 0.7.2, 0.7.1, 0.7.0, 0.6.1, 0.6.0, 0.5.2, 0.5.1, 0.5.0, 0.4.1, 0.4.0, 0.3.1, 0.3.0, 0.2.3, 0.2.2, 0.2.1, 0.2.0, 0.1.2, 0.1.1, 0.1.0, 0.0.15, 0.0.14, 0.0.13, 0.0.12, 0.0.11, 0.0.10, 0.0.9, 0.0.8, 0.0.7, 0.0.6, 0.0.5, 0.0.4, 0.0.3, 0.0.2, 0.0.1
> 
>

**Comment by antovrv** [comment]
Ok fine @KazuCocoa It may not be available in npm still now. I just saw the beta.3 version in the appium release link. So only I just tried the latest beta.3 version

https://github.com/appium/appium/releases
https://github.com/appium/appium/releases/tag/1.9.2-beta.3
