### ISSUE TITLE
Unable to run XCUITest (WebDriverAgentRunner) in XCode 10

### ISSUE THREAD

**Issue by RuiGamito** [appium/appium#11642]
## The problem

Instructions on https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md no longer apply for XCode 10.1.
In previous versions of XCode, the WebDriverAgentRunner app would be generated and installed on the (real) device under test by triggering the tests. This is not happening anymore.

## Environment

* Appium version: 1.9.1
* Appium CLI
* Mobile platform: iOS 12.0.1
* Real device: iPhone 6
* XCode Version: 10.1
* OS Version: macOS High Sierra 10.13.6

## Details

As mentioned on https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md, it should suffice that WebDriverAgentLib and WebDriverAgentRunner have their Signing properly setup (and this is indeed how I'm using it with Appium 1.7.2 and XCode 9).
This behaviour seems to have changed, and now, performing the same actions results on XCode showing the following warning: 
"Testing couldn’t begin on the device “Harold’s iPhone”: Logic Testing Unavailable
Logic Testing on iOS devices is not supported. You can run logic tests on the Simulator."

In order to be able to actually run the tests, I've got to setup signing with the Team in all the 5 remaining targets (UnitTests, IntegrationTests_1, IntegrationTests_2, IntegrationTests_3 and IntegrationApp), as well as point the Host Application in the UnitTests target to "IntegrationApp".
Even after doing so, I see the IntegrationApp being triggered on my device, but all the unit tests fail with the following error:
_"IntegrationApp.app (6944) encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted. (Underlying error: The test runner exited with code 1 before checking in.))"._

As per the integration tests, the error is:
_"Showing Recent Messages
IntegrationTests_1-Runner.app (6949) encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted. (Underlying error: The test runner failed to load the test bundle. Executable cannot be loaded for some other reason, such as a problem with a library it depends on or a code signature/entitlements mismatch.))"_

My question is: did anyone actually succeed at installing WebDriverAgentRunner on a real device using Xcode 10? If so, could you please provide some instructions?

**Comment by mayureshshirodkar** [comment]
@mykola-mokhnach I have been experiencing similar issue with Xcode 10.1 and iOS 12.1.
Logs:
https://gist.github.com/mayureshshirodkar/be204e0e7867e670c4291c1b5ca1d0f6
```
Testing failed:
	linker command failed with exit code 1 (use -v to see invocation)
	Testing cancelled because the build failed.
** TEST FAILED **
```


The following build commands failed:
	Ld /Users/shirodkm/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentLib.framework/WebDriverAgentLib normal arm64
(1 failure)

**Comment by RuiGamito** [comment]
Hi @mykola-mokhnach, thanks for the quick reply.

There actually isn't a server log because I'm not trying to actually run automation, but only trying to install the WDA runner so that I can run automation!

**Comment by mykola-mokhnach** [comment]
@mayureshshirodkar Your issue has been fixed in appium@beta

**Comment by mykola-mokhnach** [comment]
@RuiGamito Try to compile WDA sources that are included into appium@beta

**Comment by mayureshshirodkar** [comment]
@mykola-mokhnach  
i just installed Appium beta -1.9.2 beta 2 and i am getting the same error, as i mentioned before.
WDA version installed with it is  appium-xcuitest-driver@2.87.0
Command to install latest appium:  npm install -g appium@beta --no-shrinkwrap --verbose 

Appium Log:
https://gist.github.com/mayureshshirodkar/d3e3ecffb55f6c095f4c90c5a5a453db

**Comment by mykola-mokhnach** [comment]
make sure that Xcode caches are clean before compilation

**Comment by mykola-mokhnach** [comment]
Also the most recent xcuitest driver version is `2.98.0`

**Comment by mayureshshirodkar** [comment]
Thanks @mykola-mokhnach upgrading xcuitest driver version to 2.98.0 separately, seems to fix the issue for me.
For some reason this command doesn't update to latest xcuitest driver npm install -g appium@beta --no-shrinkwrap --verbose

**Comment by RuiGamito** [comment]
@mykola-mokhnach, appium@beta did the trick!

But the instructions at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md for full manual configuration seem to no longer stand.
I had to trigger an actual appium run for everything to work.

Thanks!
