### ISSUE TITLE
WDA fails to create session from cached WDA instance

### ISSUE THREAD

**Issue by mayureshshirodkar** [appium/appium#11641]
## The problem

WDA is trying to create a appium session from cached previous sessions, even though there are no cached sessions running.
This ultimately leads to failure of the appium session and the WDA app is never launched.

This issue occurs mostly, when i kill the previously running successful session, and start a new one. Am i missing any capability while running the session?

2 statements marked below are misleading:
**2018-11-05 18:08:59:628 - [debug] [XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found**
2018-11-05 18:08:59:629 - [debug] [JSONWP Proxy] Matched '/status' to command name 'getStatus'
2018-11-05 18:08:59:631 - [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
2018-11-05 18:08:59:647 - [debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"12.0.1\",\n      \"sdkVersion\" : \"12.0\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"12.0.1\",\n      \"ip\" : \"192.168.2.6\"\n    },\n    \"build\" : {\n      \"time\" : \"Oct 30 2018 21:14:44\",\n      \"productBundleIdentifier\" : \"com.facebook.WebDriverAgentRunner\"\n    }\n  },\n  \"sessionId\" : \"B11310AC-B918-4784-923C-7D70D85B58B9\",\n  \"status\" : 0\n}"
**2018-11-05 18:08:59:648 - [XCUITest] Will reuse previously cached WDA instance at 'http://localhost:8100/'. Set the wdaLocalPort capability to a value different from 8100 if this is an undesired behavior.**

## Environment

* Appium version (or git revision) that exhibits the issue: v1.9.2-beta.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 10.14 Mojave
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 12.0
* Real device or emulator/simulator: Iphone 6

## Link to Appium logs

https://gist.github.com/mayureshshirodkar/a15f3c2fa86f9a08fe970c2ea2facd25

## Code To Reproduce Issue [ Good To Have ]

            "deviceName": "iPhone 6",
            "platformVersion": get_ios_version(),
            "platformName": "iOS",
            "automationName": "XCUITest",
            "udid": "auto",
            "app": os.getcwd + "xxx.ipa",
            "autoWebview": "true",
            "startIWDP": "true",
            "xcodeOrgId": "XXXX",
            "xcodeSigningId": "iPhone Developer",
            "updatedWDABundleId": "com.xxx.WebDriverAgentRunner",
            "showXcodeLog": "true",
            "newCommandTimeout": 1000,
            "webkitResponseTimeout": 35000

**Comment by mykola-mokhnach** [comment]
I don't see any problems there, the behaviour is expected. The first log line is shown when Appium verifies that WDA is not running for different device device ID on the same port (and locks it). This might happen when one, for example, executes Appium on a real devices and then switches to a Simulator. The second log asks WDA to return the status. If the operation succeeds we assume the instance can be reused. This is effective, because killing WDA and deploying it multiple times exceeds resources on real devices and makes it impossible to run the app after some time without manual reboot.

**Comment by mayureshshirodkar** [comment]
@mykola-mokhnach got you. But how can i try and avoid the logs that i got?
Is there some capability to make sure it doesn't happen?

**Comment by mykola-mokhnach** [comment]
What do you mean under "avoid"? The log reflects the current flow. Feel free to push a PR if you have any proposals
