### ISSUE TITLE
getAttribute("value") of empty native textfield returns placeholder value

### ISSUE THREAD

**Issue by joerg1985** [appium/appium#11643]
## The problem

getAttribute("value") of empty textfield returns placeholder value and it is not possible to determinate if the native textfield is empty and the placeholder value is returned or the real value is returned.

## Environment

* Appium Version: 6.1
* Desktop OS/version used to run Appium: Windows 10 & macOS
* Mobile platform/version under test: iPad
* Real device or emulator/simulator: real

## Details

We need to check if the fields are empty, before sending keys to it. This is currently not possible, becase we can not distinguish between the placeholder and the real value. We tried to find other attributes to detect if the field is empty but we didn't find an solution so far.

**Comment by mykola-mokhnach** [comment]
The actual value is retrieved by WebDriverAgent and WDA retrieves that from XCTest, which gets it from the accessibility. For the accessibility there is no diff between placeholder or the actual value. I'd probably try add some flags to the `label` attribute programatically. Such would only be visible to our tests (and to the accessibility layer), but it might help to make the distinction. 
The other possible trick might be to clear the text field and then make sure it still contains the same value.

Closed as third party issue.

**Comment by joerg1985** [comment]
We are testing applications developed by 3rd party, so we cannot modify the applcation it self and we can't use .clear, because this triggers code of the tested application.

A new attribute "placehoder" would be great, might this be possible? This might also help people to identify the fields by the placeholder value. see: https://stackoverflow.com/questions/32845078/need-to-get-placeholder-text-of-uitextfield 

Kind regards

**Comment by mykola-mokhnach** [comment]
Feel free to create an improvement request for Apple.
