### ISSUE TITLE
The test application launched and closed with error [JSONWP Proxy] Got an unexpected response: {"code":"ECONNRESET"}

### ISSUE THREAD

**Issue by archital** [appium/appium#11657]
## The problem
The test application launched and closed several times after installing on real device. 

## Environment
* Appium version that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable): 1.9.1
* Node.js version 8.12.0
* Real device iOS 12.1
*Xcode 10.1

## Details
It starts happened after I update iPhone with IOS 12.1 version. The update of XCODE did not help.
WebDriverAgentRunner-Runner installed successful, testApp installed successful too on device, but for some reason testUpp launched and closed several times and Appium driver not initialized (null)

## Link to Appium logs
https://github.com/archital/appiumIssue/blob/master/appium%20log
## Code To Reproduce Issue [ Good To Have ]
Appium Driver initialization:
https://github.com/archital/appiumIssue/blob/master/Java%20Appium%20driver%20initialization

Please, help me. I'm stuck with that...

**Comment by mykola-mokhnach** [comment]
It looks like WDA cannot start the application under test. Try updating to appium@beta. If that does not help then report an issue to https://github.com/facebook/WebDriverAgent

There is nothing we can do about it on Appium side.
