### ISSUE TITLE
error 'apksigner stderr: Exception in thread "main" java.nio.file.AccessDeniedException:

### ISSUE THREAD

**Issue by testfortest06** [appium/appium#11662]
## The problem

Getting an error 'apksigner stderr: Exception in thread "main" java.nio.file.AccessDeniedException:' when executing script

## Environment

* Appium java-client version : 6.1.0
* Appium server version: 1.9.1
* Desktop OS/version used to run Appium: Windows 7
* Node.js version (unless using Appium.app|exe): 8.12.0
* Real device or emulator/simulator: Emulator
* Java version: 1.8.0

## Details
Getting an error 'apksigner stderr: Exception in thread "main" java.nio.file.AccessDeniedException:' when executing script
Please Help how to resolve this...
## Link to Appium logs
[info] [35m[Appium][39m Welcome to Appium v1.9.1
[info] [35m[Appium][39m Appium REST http interface listener started on 0.0.0.0:4723[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{"desiredCapabilities":{"appActivity":"com.android.calculator2.Calculator","appPackage":"com.android.calculator2","platformVersion":"8.1.0","automationName":"UiAutomator2","platformName":"Android","udid":"emulator-5554","deviceName":"AVD1"},"capabilities":{"alwaysMatch":{"appium:appActivity":"com.android.calculator2.Calculator","appium:appPackage":"com.android.calculator2","appium:automationName":"UiAutomator2","appium:deviceName":"AVD1","platformName":"android","appium:platformVersion":"8.1.0","appium:udid":"emulator-5554"},"firstMatch":[{}]}}[39m
[debug] [35m[W3C][39m Calling AppiumDriver.createSession() with args: [{"appActivity":"com.android.calculator2.Calculator","appPackage":"com.android.calculator2","platformVersion":"8.1.0","automationName":"UiAutomator2","platformName":"Android","udid":"emulator-5554","deviceName":"AVD1"},null,{"alwaysMatch":{"appium:appActivity":"com.android.calculator2.Calculator","appium:appPackage":"com.android.calculator2","appium:automationName":"UiAutomator2","appium:deviceName":"AVD1","platformName":"android","appium:platformVersion":"8.1.0","appium:udid":"emulator-5554"},"firstMatch":[{}]}]
[debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1541765096870 (17:34:56 GMT+0530 (India Standard Time))
[info] [35m[Appium][39m Creating new AndroidUiautomator2Driver (v1.19.0) session
[info] [35m[Appium][39m Capabilities:
[info] [35m[Appium][39m   platformName: android
[info] [35m[Appium][39m   appActivity: com.android.calculator2.Calculator
[info] [35m[Appium][39m   appPackage: com.android.calculator2
[info] [35m[Appium][39m   automationName: UiAutomator2
[info] [35m[Appium][39m   deviceName: AVD1
[info] [35m[Appium][39m   platformVersion: 8.1.0
[info] [35m[Appium][39m   udid: emulator-5554
[debug] [35m[BaseDriver][39m W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP desired capabilities {"appActivity":"com.android... were provided
[debug] [35m[BaseDriver][39m Creating session with W3C capabilities: {"alwaysMatch":{"platformNa...
[info] [35m[BaseDriver][39m Session created with session id: c8bb71ed-7994-45ab-a3f4-0eef2fb111e3[info] [35m[AndroidDriver][39m Java version is: 1.8.0_91
[info] [35m[AndroidDriver][39m Retrieving device list
[debug] [35m[ADB][39m Trying to find a connected android device
[debug] [35m[ADB][39m Getting connected devices...
[debug] [35m[ADB][39m 1 device(s) connected
[info] [35m[AndroidDriver][39m Using device: emulator-5554
[debug] [35m[ADB][39m Setting device id to emulator-5554
[debug] [35m[ADB][39m Running 'C:\Users\Office\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk'[debug] [35m[ADB][39m Current device property 'ro.build.version.sdk': 27
[debug] [35m[ADB][39m Device API level: 27
[warn] [35m[AndroidDriver][39m No app sent in, not parsing package/activity
[info] [35m[ADB][39m Getting device platform version
[debug] [35m[ADB][39m Running 'C:\Users\Office\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.release'[debug] [35m[ADB][39m Current device property 'ro.build.version.release': 8.1.0
[debug] [35m[ADB][39m Running 'C:\Users\Office\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell wm size'[debug] [35m[ADB][39m Running 'C:\Users\Office\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell wm density'[debug] [35m[ADB][39m Running 'C:\Users\Office\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.product.model'[debug] [35m[ADB][39m Current device property 'ro.product.model': Android SDK built for x86
[debug] [35m[ADB][39m Running 'C:\Users\Office\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.product.manufacturer'[debug] [35m[ADB][39m Current device property 'ro.product.manufacturer': Google
[debug] [35m[ADB][39m Device API level: 27
[debug] [35m[ADB][39m Running 'C:\Users\Office\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell am force-stop io.appium.uiautomator2.server'[debug] [35m[ADB][39m Checking app cert for C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v1.18.0.apk
[debug] [35m[ADB][39m Starting 'C:\Users\Office\AppData\Local\Android\Sdk\build-tools\28.0.3\apksigner.bat' with args '["verify","--print-certs","C:\\Program Files (x86)\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v1.18.0.apk"]'[debug] [35m[ADB][39m apksigner stdout: Signer #1 certificate DN: C=US, O=Android, CN=Android Debug
[debug] [35m[ADB][39m Signer #1 certificate SHA-256 digest: 707bc2493ea5b0267dc10a9bd4cedbab5431976f13274cdd045d93470179556d
[debug] [35m[ADB][39m Signer #1 certificate SHA-1 digest: b8db0b11cec13cc7574a7d62f383ec16c0d275ee
[debug] [35m[ADB][39m Signer #1 certificate MD5 digest: 4fcd3b10d1e80a20bbd28758c8a3e19b
[debug] [35m[ADB][39m WARNING: META-INF/INDEX.LIST not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
[debug] [35m[ADB][39m WARNING: META-INF/io.netty.versions.properties not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
[debug] [35m[ADB][39m 
[debug] [35m[ADB][39m 'C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v1.18.0.apk' is not signed with debug cert.[debug] [35m[ADB][39m C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v1.18.0.apk' is already zip-aligned. Doing nothing
[debug] [35m[ADB][39m Signing 'C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v1.18.0.apk' with default cert
[debug] [35m[ADB][39m Starting 'C:\Users\Office\AppData\Local\Android\Sdk\build-tools\28.0.3\apksigner.bat' with args '["sign","--key","C:\\Program Files (x86)\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-adb\\keys\\testkey.pk8","--cert","C:\\Program Files (x86)\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-adb\\keys\\testkey.x509.pem","C:\\Program Files (x86)\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v1.18.0.apk"]'[warn] [35m[ADB][39m Got an error during apksigner execution: Command 'C\:\\Users\\Office\\AppData\\Local\\Android\\Sdk\\build-tools\\28.0.3\\apksigner.bat sign --key 'C:\\Program Files (x86)\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-adb\\keys\\testkey.pk8' --cert 'C:\\Program Files (x86)\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-adb\\keys\\testkey.x509.pem' 'C:\\Program Files (x86)\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v1.18.0.apk'' exited with code 1
[warn] [35m[ADB][39m apksigner stderr: Exception in thread "main" java.nio.file.AccessDeniedException: C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v1.18.0.apk
[warn] [35m[ADB][39m 	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
[warn] [35m[ADB][39m 	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
[warn] [35m[ADB][39m 	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
[warn] [35m[ADB][39m 	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:376)
[warn] [35m[ADB][39m 	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
[warn] [35m[ADB][39m 	at java.nio.file.Files.move(Files.java:1395)
[warn] [35m[ADB][39m 	at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:342)
[warn] [35m[ADB][39m 	at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:89)
[warn] [35m[ADB][39m 
[warn] [35m[ADB][39m Cannot use apksigner tool for signing. Defaulting to sign.jar. Original error: Command 'C\:\\Users\\Office\\AppData\\Local\\Android\\Sdk\\build-tools\\28.0.3\\apksigner.bat sign --key 'C:\\Program Files (x86)\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-adb\\keys\\testkey.pk8' --cert 'C:\\Program Files (x86)\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-adb\\keys\\testkey.x509.pem' 'C:\\Program Files (x86)\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v1.18.0.apk'' exited with code 1; StdErr: Exception in thread "main" java.nio.file.AccessDeniedException: C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v1.18.0.apk
[warn] [35m[ADB][39m 	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
[warn] [35m[ADB][39m 	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
[warn] [35m[ADB][39m 	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
[warn] [35m[ADB][39m 	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:376)
[warn] [35m[ADB][39m 	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
[warn] [35m[ADB][39m 	at java.nio.file.Files.move(Files.java:1395)
[warn] [35m[ADB][39m 	at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:342)
[warn] [35m[ADB][39m 	at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:89)
[warn] [35m[ADB][39m 
[debug] [35m[ADB][39m Resigning apk.[debug] [35m[UiAutomator2][39m Deleting UiAutomator2 session
[debug] [35m[UiAutomator2][39m Deleting UiAutomator2 server session
[debug] [35m[JSONWP Proxy][39m Matched '/' to command name 'deleteSession'
[warn] [35m[UiAutomator2][39m Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
[debug] [35m[ADB][39m Running 'C:\Users\Office\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell am force-stop com.android.calculator2'[debug] [35m[ADB][39m Removing forwarded port socket connection: 8200 
[debug] [35m[ADB][39m Running 'C:\Users\Office\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 forward --remove tcp\:8200'
[debug] [35m[ADB][39m Running 'C:\Users\Office\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 forward --remove tcp\:8200'
[warn] [35m[UiAutomator2][39m Unable to remove port forward 'Error executing adbExec. Original error: 'Command 'C\:\\Users\\Office\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 forward --remove tcp\:8200' exited with code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''
[debug] [35m[BaseDriver][39m Event 'newSessionStarted' logged at 1541765103730 (17:35:03 GMT+0530 (India Standard Time))
[debug] [35m[W3C][39m Encountered internal error running command: Error: Could not sign with default certificate. Original error Command ''C:\\Program Files\\Java\\jdk1.8.0_91\\bin\\java.exe' -jar 'C:\\Program Files (x86)\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-adb\\jars\\sign.jar' 'C:\\Program Files (x86)\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v1.18.0.apk' --override' exited with code 1
[debug] [35m[W3C][39m     at ADB.callee$0$0$ (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\apk-signing.js:109:13)
[debug] [35m[W3C][39m     at tryCatch (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[debug] [35m[W3C][39m     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[debug] [35m[W3C][39m     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[debug] [35m[W3C][39m     at GeneratorFunctionPrototype.invoke (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[debug] [35m[W3C][39m     at run (C:\Program Files (x86)\Appium\resources\app\webpack:\~\babel-polyfill\~\core-js\modules\es6.promise.js:75:1)
[debug] [35m[W3C][39m     at C:\Program Files (x86)\Appium\resources\app\webpack:\~\babel-polyfill\~\core-js\modules\es6.promise.js:92:1
[debug] [35m[W3C][39m     at flush (C:\Program Files (x86)\Appium\resources\app\webpack:\~\babel-polyfill\~\core-js\modules\_microtask.js:18:1)
[debug] [35m[W3C][39m     at process._tickCallback (internal/process/next_tick.js:61:11)
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[31m500[39m [90m6864 ms - 2717[39m
[info] [35m[HTTP][39m [90m[39m

## Code To Reproduce Issue [ Good To Have ]
public class launchApp {

    AndroidDriver<AndroidElement> driver;

    @BeforeMethod
    public void beforeClass() throws MalformedURLException, InterruptedException {
        DesiredCapabilities capabilities = new DesiredCapabilities();
       capabilities.setCapability("udid", "emulator-5554");
        capabilities.setCapability("platformName", "Android");
        capabilities.setCapability("automationName", "UiAutomator2");
       capabilities.setCapability("deviceName", "AVD1");
        capabilities.setCapability("platformVersion", "8.1.0");
        capabilities.setCapability("appPackage", "com.android.calculator2");
       capabilities.setCapability("appActivity", "com.android.calculator2.Calculator");
        driver = new AndroidDriver<AndroidElement>(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);
       Thread.sleep(5000);

    }

    @Test
    public void m1() throws InterruptedException {
        System.out.println("Test");
        Thread.sleep(2000);

    }
}

**Comment by mykola-mokhnach** [comment]
@dpgraham @imurchie shouldn't permissions be set automatically by the install script?

**Comment by testfortest06** [comment]
@mykola-mokhnach  thanks for the quick reply under folder : C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\ these are two file 1. appium-uiautomator2-server-debug-androidTest.apk
2. appium-uiautomator2-server-v1.18.0.apk 
How will be make writable ?

**Comment by mykola-mokhnach** [comment]
Ask you system administrator.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by antovrv** [comment]
I've also faced this issue and was hanged with this for the past two days.
Finally, I've solved the issue by making the **lib** folder **writable** which contains the node_modules packages.

> sudo chmod -R 775 /usr/local/lib

I'm using ubuntu, so in my case the path of node_modules is
> /usr/local/lib/node_modules

I've installed the **uiautomator2** driver as well. But which is not needed after gave permission for lib folder.

**To install:**
> npm install -g appium-uiautomator2-driver --unsafe-perm=true

I've uninstalled this and checked again, It's working fine now.

**To uninstall:**
> npm uninstall -g appium-uiautomator2-driver
