### ISSUE TITLE
Application 'PID:' disconnected. Removing from app dictionary.

### ISSUE THREAD

**Issue by saigovindu** [appium/appium#11666]
I had setup selenium hub with appium node and tried to run 100 test cases(all test cases same) sequentially, for the first 58< test cases running fast(around 12 seconds) after that each test case taking (80 seconds) to run. After looking at the logs, I Application 'PID:3579' disconnected. Removing from app dictionary and trying to restart again.

2018-11-09 15:49:11:050 - [debug] [RemoteDebugger] Application 'PID:3579' disconnected. Removing from app dictionary.
2018-11-09 15:49:11:050 - [debug] [RemoteDebugger] Current app is PID:3581
2018-11-09 15:49:11:050 - [debug] [RemoteDebugger] Application 'PID:3581' disconnected. Removing from app dictionary.
2018-11-09 15:49:11:051 - [debug] [RemoteDebugger] Current app is PID:3581
2018-11-09 15:49:11:051 - [debug] [RemoteDebugger] No longer have app id. Attempting to find new one.
2018-11-09 15:49:11:750 - [debug] [RemoteDebugger] Notified that new application 'PID:3588' has connected

Here I am using precompiled WDA for faster execution of test cases.

Environment
Appium version (or git revision) that exhibits the issue: 1.9.1,
Desktop OS/version used to run Appium: Mac OS 10.11.6
Node.js version (unless using Appium.app|exe): v8.12.0
Mobile platform/version under test: iOS 10.1
Real device or emulator/simulator: simulator
Appium CLI or Appium.app|exe: CLI
Xcode version: 8.1

## Link to Appium logs
https://gist.github.com/saigovindu/dd0e8bbb2cc4d0e9378d756bd17cb1f8

**Comment by mykola-mokhnach** [comment]
Try appium@beta

**Comment by hepsi204** [comment]
I am seeing the issue too after updating to latest Appium. has anyone found a solution yet ?

**Comment by helenren** [comment]
hit the similar issue in our hybrid application test on iphone simulator:

13:14:16 2018-12-05 21:14:16:782 - [debug] [RemoteDebugger] Garbage collecting with 5000ms timeout
13:14:16 2018-12-05 21:14:16:785 - [debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to remote debugger
13:14:16 2018-12-05 21:14:16:818 - [debug] [RemoteDebugger] Received page change notice for app 'PID:63351' but listening for 'PID:63343'. Ignoring.
13:14:16 2018-12-05 21:14:16:821 - [debug] [RemoteDebugger] Application 'PID:63350' disconnected. Removing from app dictionary.
13:14:16 2018-12-05 21:14:16:821 - [debug] [RemoteDebugger] Current app is PID:63343
13:14:16 2018-12-05 21:14:16:824 - [debug] [RemoteDebugger] Application 'PID:63343' disconnected. Removing from app dictionary.
13:14:16 2018-12-05 21:14:16:824 - [debug] [RemoteDebugger] Current app is PID:63343
13:14:16 2018-12-05 21:14:16:824 - [debug] [RemoteDebugger] No longer have app id. Attempting to find new one.
13:14:16 2018-12-05 21:14:16:824 - [debug] [RemoteDebugger] Found app id key 'PID:63330' for bundle 'com.salesforce.chatter'
13:14:16 2018-12-05 21:14:16:824 - [debug] [RemoteDebugger] Found separate bundleId 'com.apple.WebKit.WebContent' acting as proxy for 'com.salesforce.chatter', with app id 'PID:63351'
13:14:16 2018-12-05 21:14:16:825 - [debug] [RemoteDebugger] Using proxied app id 'PID:63351'
13:14:16 2018-12-05 21:14:16:825 - [debug] [RemoteDebugger] Application 'PID:63330' disconnected. Removing from app dictionary.
13:14:16 2018-12-05 21:14:16:825 - [debug] [RemoteDebugger] Current app is PID:63351
13:14:16 2018-12-05 21:14:16:828 - [debug] [RemoteDebugger] Application 'PID:63351' disconnected. Removing from app dictionary.
13:14:16 2018-12-05 21:14:16:828 - [debug] [RemoteDebugger] Current app is PID:63351
13:14:16 2018-12-05 21:14:16:828 - [debug] [RemoteDebugger] No longer have app id. Attempting to find new one.

we are using appium 1.9.1, ios 11.4 and xcode 9.4.1.

**Comment by mykola-mokhnach** [comment]
Closed as inactive
