### ISSUE TITLE
Error: 'browserName' cannot be set together with 'bundleId' capability

### ISSUE THREAD

**Issue by ValentinaLN** [appium/appium#11664]
## The problem
 [XCUITest] Error: 'browserName' cannot be set together with 'bundleId' capability. But at our project we use both of them. We didn't have such issue with appium 1.8.1 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable): 1.8.1
* Desktop OS/version used to run Appium:Mac OS X 10.14
* Mobile platform/version under test: iOS 12.0.1
* Real device or emulator/simulator: real device

## Appium logs

[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.9.1"}}
[HTTP] <-- GET /wd/hub/status 200 3 ms - 67
[HTTP] 
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"xcodeOrgId":"4XGDRF4ETY","bundleId”:”XXX”,”deviceName":"iPhone","updatedWDABundleId”:”XXX”,”xcodeSigningId":"iPhone Developer","platform":"MAC","showXcodeLog":"true","autoLaunch":false,"newCommandTimeout":"520","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole","platformVersion":"12.0.1","browserName":"iPhone5s","platformName":"iOS"},"requiredCapabilities":{}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"xcodeOrgId":"4XGDRF4ETY","bundleId”:”XXX”,”deviceName":"iPhone","updatedWDABundleId”:”XXX”,”xcodeSigningId":"iPhone Developer","platform":"MAC","showXcodeLog":"true","autoLaunch":false,"newCommandTimeout":"520","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole","platformVersion":"12.0.1","browserName":"iPhone5s","platformName":"iOS"},{},null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1541082736523 (17:32:16 GMT+0300 (+03))
[Appium] Requested iOS support with version >= 10, using 'XCUITest' driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver (v2.94.2) session
[Appium] Capabilities:
[Appium]   udid: XXXXXX
[Appium]   xcodeOrgId: 4XGDRF4ETY
[Appium]   bundleId: XXX
[Appium]   deviceName: iPhone
[Appium]   updatedWDABundleId: XXX
[Appium]   xcodeSigningId: iPhone Developer
[Appium]   platform: MAC
[Appium]   showXcodeLog: true
[Appium]   autoLaunch: false
[Appium]   newCommandTimeout: 520
[Appium]   realDeviceLogger: /usr/local/lib/node_modules/deviceconsole
[Appium]   platformVersion: 12.0.1
[Appium]   browserName: iPhone5s
[Appium]   platformName: iOS
[debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {"udid":"daadb1f524aeb7bf8b...
[BaseDriver] Capability 'showXcodeLog' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Capability 'newCommandTimeout' changed from string ('520') to integer (520). This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by appium: platform.
[XCUITest] Error: 'browserName' cannot be set together with 'bundleId' capability
[XCUITest]     at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[XCUITest]     at XCUITestDriver.validateDesiredCaps (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:947:13)
[XCUITest]     at XCUITestDriver.callee$0$0$ (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/session.js:45:8)
[XCUITest]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[XCUITest]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[XCUITest]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[XCUITest]     at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest]     at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
[XCUITest]     at Promise.F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
[XCUITest]     at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
[XCUITest]     at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[XCUITest]     at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
[XCUITest]     at XCUITestDriver.callee$0$0 [as createSession] (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/build/lib/basedriver/commands/session.js:35:30)
[XCUITest]     at XCUITestDriver.createSession$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:111:21)
[XCUITest]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[XCUITest]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[XCUITest]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[XCUITest]     at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest]     at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
[XCUITest]     at Promise.F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
[XCUITest]     at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
[XCUITest]     at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[XCUITest]     at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
[XCUITest]     at XCUITestDriver.createSession (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/build/lib/driver.js:247:34)
[XCUITest]     at AppiumDriver.callee$2$0$ (/usr/local/lib/node_modules/appium/lib/appium.js:291:43)
[XCUITest]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[XCUITest]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[XCUITest]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[XCUITest]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest]     at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by mykola-mokhnach** [comment]
This is the expected behaviour. One of these caps must be removed.

Closed as not an issue
