### ISSUE TITLE
Not able to change iOS video recording format for real devices.

### ISSUE THREAD

**Issue by kolyakrasnik** [appium/appium#11677]
## The problem

I'm trying to change video_type format to H264 for video recording iOS real devices but nothing happens. Currently default video format for iOS real devices is mjpeg. So, resulting video for 3 mins video is too big - about 70 MB. Also, mjpeg format is not maintained by browsers, so we are not able to stream this video via browsers.  Is it a way to change video format?

## Environment

Appium version (or git revision) that exhibits the issue: 1.9.1
Desktop OS/version used to run Appium: macOS Mojave 10.14
Mobile platform/version under test: iOS 12.0.1
Real device or emulator/simulator: real device.

## Link to Appium logs

https://gist.github.com/kolyakrasnik/b50d8116569b8c5fafbd488947d09fb6

## Code To Reproduce Issue [ Good To Have ]

IOSStartScreenRecordingOptions o1 = new IOSStartScreenRecordingOptions()
                .withVideoQuality(VideoQuality.LOW)
                .withVideoType(VideoType.H264)
                .withTimeLimit(Duration.ofSeconds(180));
((IOSDriver) driver).startRecordingScreen(o1);
......
test actions
......
String s = ((IOSDriver) driver).stopRecordingScreen();

**Comment by kolyakrasnik** [comment]
We find out some workaround for video recording for now. We use the next command: ffmpeg -f mjpeg -r 10 -i http://localhost:9100 -vf scale=-2:720 -vcodec libx264 -y /var/folders/mq/y43tw_dj7s12ltsgydvff86h0000gn/T/20181016-78932-18h9njr.9cwb/appium_40f225.mp4

We got enough quality with very small video size. Tested on iPhoneSE, iPhoneX, iPhone6s, iPhone7Plus real devices.

**Comment by mykola-mokhnach** [comment]
The change has been published
