### ISSUE TITLE
Appium cannot see all children of an Android ListView spinner

### ISSUE THREAD

**Issue by achaters** [appium/appium#11679]
## The problem

In a ListView set up as a spinner, only 3 of 4 child items are visible to Appium, last item cannot be found by locators despite being fully visible on screen. Appium Desktop also cannot see the last TextView in the list.

## Environment

* Appium version (or git revision) that exhibits the issue: **1.9.1**
* Appium Desktop: **1.8.2**
* Desktop OS/version used to run Appium: macOS Mojave **10.14.1**
* Mobile platform/version under test: **Android API 28**

## Details

According to Appium Desktop's inspector, the visible element tree (once the spinner has been clicked and the list of elements presented) looks like this:

```xml
<android.widget.FrameLayout>
    <android.widget.FrameLayout>
        <android.widget.ListView>
            <android.widget.TextView resource-id="android:id/text1">
            <android.widget.TextView resource-id="android:id/text1">
            <android.widget.TextView resource-id="android:id/text1">
        </android.widget.ListView>
    </android.widget.FrameLayout>
</android.widget.FrameLayout>
```
What is actually in the spinner is a list of elements like this:
* Spinner Item 1
* Spinner Item 2
* Spinner Item 3
* Spinner Item 4

All elements appear to be the same height, with no parts of the top or bottom element obscured. The ListView is generated using an ArrayAdapter; there is no other customization of the rendered elements.

The last item is user-clickable without problems. When mousing over the last element in the inspector, the entire ListView is highlighted and will be selected on click. Clicking the third TextView in the list will properly select the second to last item.

## Link to Appium logs

Log was generated by simply opening the application, expanding the spinner, and asking for all visible TextView elements available by XPath.

https://gist.github.com/achaters/f86d47f99c171f728df5434ce222f398

**Comment by dpgraham** [comment]
The app hierarchy is reported to Appium by UiAutomator2

I recommend seeing what [UiAutomator Viewer](https://developer.android.com/training/testing/ui-automator) shows, and if it's the same as Appium (which I expect it will be), then it isn't an Appium issue.

You probably need to call a scroll or swipe event on the spinner to scroll down and then it will become part of the view hierarchy. 

You can also set the value of an Android Spinner using `setValue`.

**Comment by achaters** [comment]
UIAutomator Viewer is showing me four TextView elements in the list without needing to interact with the screen aside from clicking to open the drop down.

My highest version of Android Studio is 3.3 beta 1.

**Comment by ChitSuShine** [comment]
For me, I have card view. After clicking this card view, some ui changes happen. But appium 1.9.1 cannot find elements on this screen for Android. I tried with 1.8.1, it's OK. Do you have any idea for this?

**Comment by mykola-mokhnach** [comment]
Try to switch to Espresso driver and see if it works better there. I don't this we can do anything on Appium side for that unless you test it and prepare a PR on your own.

**Comment by dkavithavijay** [comment]
UIAutomatorViewer and Emulator are not showing the spinner-list items while testing with appium.

Spinner is listing in emulator but while testing it is not listing and not performing any actions like click(),setValue("string".

Is this an issue reported in appium?

If so, how to switch to Espresso driver, please provide sample code.

**Comment by mykola-mokhnach** [comment]
http://appium.io/docs/en/drivers/android-espresso/
