### ISSUE TITLE
[Findelements]how to get elements of ios system view by appium like the example below

### ISSUE THREAD

**Issue by adadale** [appium/appium#11672]
## The problem
I cannot find some elements by appium in some ios system uiremoteview
Thanks
## Environment
* Appium version (or git revision) that exhibits the issue:appium 1.9.1

## Link to Appium logs

can't find app icon by find element by id or other methods.Which i can't find are the app icons below.
![img_0393 2](https://user-images.githubusercontent.com/30455538/48330316-1e697000-e687-11e8-9346-045521a7906e.PNG)

**Comment by dpgraham** [comment]
I would recommend using [Appium Desktop](https://github.com/appium/appium-desktop) to run sessions and explorer the app hierarchy and test selectors.

For any Appium help try going to https://discuss.appium.io
