### ISSUE TITLE
Getting exception linker command failed with exit code 1 (use -v to see invocation) in WebdriverAgent

### ISSUE THREAD

**Issue by Manish503** [appium/appium#11673]
Getting linker command exception in webdriver agent  xcode project

![image](https://user-images.githubusercontent.com/31891014/48330341-35a85d80-e687-11e8-82bd-889c0de3f5fc.png)

**Comment by Manish503** [comment]
@mykola-mokhnach could you please help me on this  i was trying to launch app in IOS device ,in xcode i'm getting above error and appium server i'm getting below error but provisional certificate setup and accepted successfully in xcode.
Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
**These are my Capabilities:**
Appium] Creating new XCUITestDriver (v2.94.2) session
[Appium] Capabilities:
[Appium]   app: /Users/anakin/Downloads/MKETradeSIT.ipa
[Appium]   automationName: XCUITest
[Appium]   clearSystemFiles: true
[Appium]   deviceName: iPhone
[Appium]   platformName: IOS
[Appium]   platformVersion: 11.2.6
[Appium]   udid: auto
[Appium]   xcodeOrgId: 3R6*******
[Appium]   xcodeSigningId: iPhone Developer
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true

**Comment by mykola-mokhnach** [comment]
Use appium@beta to automate Xcode10+
