### ISSUE TITLE
Underlying error: The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file. The file doesn’t exist. 

### ISSUE THREAD

**Issue by Manish503** [appium/appium#11675]
[Appium] Welcome to Appium v1.9.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/sessions
[HTTP] {}
[GENERIC] Calling AppiumDriver.getSessions() with args: []
[GENERIC] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 6 ms - 40
[HTTP] 
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"/Users/anakin/Downloads/MKETradeSIT.ipa","automationName":"XCUITest","clearSystemFiles":true,"deviceName":"iPhone","platformName":"IOS","platformVersion":"11.2.6","udid":"auto","xcodeOrgId":"3R6C4ZD3NV","xcodeSigningId":"iPhone Developer","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/anakin/Downloads/MKETradeSIT.ipa","automationName":"XCUITest","clearSystemFiles":true,"deviceName":"iPhone","platformName":"IOS","platformVersion":"11.2.6","udid":"auto","xcodeOrgId":"3R6C4ZD3NV","xcodeSigningId":"iPhone Developer","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1542083696342 (12:34:56 GMT+0800 (+08))
[Appium] Creating new XCUITestDriver (v2.94.2) session
[Appium] Capabilities:
[Appium]   app: /Users/anakin/Downloads/MKETradeSIT.ipa
[Appium]   automationName: XCUITest
[Appium]   clearSystemFiles: true
[Appium]   deviceName: iPhone
[Appium]   platformName: IOS
[Appium]   platformVersion: 11.2.6
[Appium]   udid: auto
[Appium]   xcodeOrgId: 3R6C4ZD***
[Appium]   xcodeSigningId: iPhone Developer
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[BaseDriver] Creating session with MJSONWP desired capabilities: {"app":"/Users/anakin/Downl...
[BaseDriver] Session created with session id: 67d3f7c8-6f77-4b3c-818c-af3c9f796ef5
[XCUITest] Current user: 'anakin'
[XCUITest] Xcode version set to '10.1' 
[XCUITest] iOS SDK Version set to '12.1'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1542083696698 (12:34:56 GMT+0800 (+08))
[XCUITest] Auto-detecting real device udid...
[XCUITest] Using idevice_id
[XCUITest] Detected real device udid: '43be09bfb5bc5ad54015eb541b5e04e7f0ff8d91'
[XCUITest] Creating iDevice object with udid '43be09bfb5bc5ad54015eb541b5e04e7f0ff8d91'
[XCUITest] Determining device to run tests on: udid: '43be09bfb5bc5ad54015eb541b5e04e7f0ff8d91', real device: true
[BaseDriver] Using local app '/Users/anakin/Downloads/MKETradeSIT.ipa'
[BaseDriver] Copying local zip to tmp dir
[BaseDriver] Unzipping local app '/var/folders/g5/y4w2fpm93f7cgc4fl8prgxw40000gn/T/20181013-33509-15ovfeg.c47z/appium-app.zip'...
[BaseDriver] Unzipping /var/folders/g5/y4w2fpm93f7cgc4fl8prgxw40000gn/T/20181013-33509-15ovfeg.c47z/appium-app.zip
[BaseDriver] Testing zip archive: /var/folders/g5/y4w2fpm93f7cgc4fl8prgxw40000gn/T/20181013-33509-15ovfeg.c47z/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/g5/y4w2fpm93f7cgc4fl8prgxw40000gn/T/20181013-33509-15ovfeg.c47z/Payload/MKETradeSIT.app'
[BaseDriver] Event 'appConfigured' logged at 1542083699308 (12:34:59 GMT+0800 (+08))
[XCUITest] Checking whether app '/var/folders/g5/y4w2fpm93f7cgc4fl8prgxw40000gn/T/20181013-33509-15ovfeg.c47z/Payload/MKETradeSIT.app' is actually present on file system
[XCUITest] App is present
[iOS] Getting bundle ID from app '/var/folders/g5/y4w2fpm93f7cgc4fl8prgxw40000gn/T/20181013-33509-15ovfeg.c47z/Payload/MKETradeSIT.app': 'com.mayBank.MKETradeSIT'
[BaseDriver] Event 'resetStarted' logged at 1542083699322 (12:34:59 GMT+0800 (+08))
[XCUITest] Reset: running ios real device reset flow
[BaseDriver] Event 'resetComplete' logged at 1542083699323 (12:34:59 GMT+0800 (+08))
[iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[iOSLog] Starting iOS device log capture with: 'idevicesyslog'
[XCUITest] Cannot get the name of the crashes folder for the device with udid '43be09bfb5bc5ad54015eb541b5e04e7f0ff8d91'. Original error: Command 'idevicename -u 43be09bfb5bc5ad54015eb541b5e04e7f0ff8d91' exited with code 255
[BaseDriver] Event 'logCaptureStarted' logged at 1542083700275 (12:35:00 GMT+0800 (+08))
[XCUITest] Setting up real device
[XCUITest] Verifying application platform
[XCUITest] CFBundleSupportedPlatforms: ["iPhoneOS"]
[XCUITest] Reset requested. Removing app with id 'com.mayBank.MKETradeSIT' from the device
[XCUITest] Installing '/var/folders/g5/y4w2fpm93f7cgc4fl8prgxw40000gn/T/20181013-33509-15ovfeg.c47z/Payload/MKETradeSIT.app' on device with UUID '43be09bfb5bc5ad54015eb541b5e04e7f0ff8d91'...
[XCUITest] The app has been installed successfully.
[BaseDriver] Event 'appInstalled' logged at 1542083706046 (12:35:06 GMT+0800 (+08))
[XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[JSONWP Proxy] Matched '/status' to command name 'getStatus'
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] WDA is not listening at 'http://localhost:8100/'
[XCUITest] WDA is currently not running. There is nothing to cache
[XCUITest] Trying to start WebDriverAgent 1 times with 10000ms interval
[BaseDriver] Event 'wdaStartAttempted' logged at 1542083706197 (12:35:06 GMT+0800 (+08))
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Killing running processes 'xcodebuild.*43be09bfb5bc5ad54015eb541b5e04e7f0ff8d91, iproxy 8100' for the device 43be09bfb5bc5ad54015eb541b5e04e7f0ff8d91...
[XCUITest] 'pgrep -nif xcodebuild.*43be09bfb5bc5ad54015eb541b5e04e7f0ff8d91' didn't detect any matching processes. Return code: 1
[XCUITest] 'pgrep -nif iproxy 8100' didn't detect any matching processes. Return code: 1
[XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB for the device 43be09bfb5bc5ad54015eb541b5e04e7f0ff8d91
[XCUITest] Generating xcode config file for orgId '3R6C4ZD3NV' and signingId 'iPhone Developer'
[XCUITest] Writing xcode config file to /var/folders/g5/y4w2fpm93f7cgc4fl8prgxw40000gn/T/20181013-33509-1pkbsss.9tqbh/appium-temp.xcconfig
[XCUITest] Using Xcode configuration file: '/var/folders/g5/y4w2fpm93f7cgc4fl8prgxw40000gn/T/20181013-33509-1pkbsss.9tqbh/appium-temp.xcconfig'
[XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=43be09bfb5bc5ad54015eb541b5e04e7f0ff8d91 IPHONEOS_DEPLOYMENT_TARGET=11.2 -xcconfig /var/folders/g5/y4w2fpm93f7cgc4fl8prgxw40000gn/T/20181013-33509-1pkbsss.9tqbh/appium-temp.xcconfig' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Output from xcodebuild will not be logged. To change this, use 'showXcodeLog' desired capability
[XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[JSONWP Proxy] Matched '/status' to command name 'getStatus'
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Matched '/status' to command name 'getStatus'
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Matched '/status' to command name 'getStatus'
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Log file for xcodebuild test: /Users/anakin/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2018.11.13_12-35-13-+0800.xcresult/2_Test/Diagnostics/WebDriverAgentRunner-9C4CE0EC-5C53-40F2-A191-BF91C02B0243/WebDriverAgentRunner-AB16809F-EE4B-4687-9AEF-53B5A3C3C727/Session-WebDriverAgentRunner-2018-11-13_123514-BG9uRx.log
[Xcode] 2018-11-13 12:35:14.706 xcodebuild[33740:495542] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/anakin/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7f883b30c770 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode] 2018-11-13 12:35:14.706 xcodebuild[33740:495542] Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Failed to install or launch the test runner" UserInfo={NSLocalizedRecoverySuggestion=If you believe this error represents a bug, please attach the result bundle at /Users/anakin/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2018.11.13_12-35-13-+0800.xcresult, NSLocalizedDescription=Failed to install or launch the test runner, NSUnderlyingError=0x7f883ab72e90 {Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/anakin/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7f883b30c770 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}}}
[Xcode] 
[Xcode] 
[Xcode] Testing failed:
[Xcode] 	No profiles for 'com.facebook.WebDriverAgentRunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.facebook.WebDriverAgentRunner'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'WebDriverAgentRunner')
[Xcode] 	No signing certificate "iOS Development" found: No "iOS Development" signing certificate matching team ID "3R6C4ZD3NV" with a private key was found. (in target 'WebDriverAgentLib')
[Xcode] 	WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file. The file doesn’t exist. (Underlying error: The operation couldn’t be completed. No such file or directory)))
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[Xcode] Testing started on 'iPhone'
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Killing running processes 'xcodebuild.*43be09bfb5bc5ad54015eb541b5e04e7f0ff8d91, iproxy 8100' for the device 43be09bfb5bc5ad54015eb541b5e04e7f0ff8d91...
[XCUITest] 'pgrep -nif xcodebuild.*43be09bfb5bc5ad54015eb541b5e04e7f0ff8d91' didn't detect any matching processes. Return code: 1
[XCUITest] iproxy exited with code 'null'
[XCUITest] 'pgrep -nif iproxy 8100' didn't detect any matching processes. Return code: 1
[XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB for the device 43be09bfb5bc5ad54015eb541b5e04e7f0ff8d91
[XCUITest] Using Xcode configuration file: '/var/folders/g5/y4w2fpm93f7cgc4fl8prgxw40000gn/T/20181013-33509-1pkbsss.9tqbh/appium-temp.xcconfig'
[XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=43be09bfb5bc5ad54015eb541b5e04e7f0ff8d91 IPHONEOS_DEPLOYMENT_TARGET=11.2 -xcconfig /var/folders/g5/y4w2fpm93f7cgc4fl8prgxw40000gn/T/20181013-33509-1pkbsss.9tqbh/appium-temp.xcconfig' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Output from xcodebuild will not be logged. To change this, use 'showXcodeLog' desired capability
[XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[JSONWP Proxy] Matched '/status' to command name 'getStatus'
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Matched '/status' to command name 'getStatus'
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Matched '/status' to command name 'getStatus'
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Log file for xcodebuild test: /Users/anakin/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2018.11.13_12-35-22-+0800.xcresult/2_Test/Diagnostics/WebDriverAgentRunner-A35BDB71-C434-4ECF-A9A4-AB3F53AB0123/WebDriverAgentRunner-69A49FAF-DE7D-422E-AC44-18B1C4FA0868/Session-WebDriverAgentRunner-2018-11-13_123523-Auj6HY.log
[Xcode] 2018-11-13 12:35:23.070 xcodebuild[33756:495744] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/anakin/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7facb29f93c0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode] 
[Xcode] 2018-11-13 12:35:23.070 xcodebuild[33756:495744] Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Failed to install or launch the test runner" UserInfo={NSLocalizedRecoverySuggestion=If you believe this error represents a bug, please attach the result bundle at /Users/anakin/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2018.11.13_12-35-22-+0800.xcresult, NSLocalizedDescription=Failed to install or launch the test runner, NSUnderlyingError=0x7facb2b02e40 {Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/anakin/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7facb29f93c0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}}}
[Xcode] 
[Xcode] 
[Xcode] Testing failed:
[Xcode] 	No profiles for 'com.facebook.WebDriverAgentRunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.facebook.WebDriverAgentRunner'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'WebDriverAgentRunner')
[Xcode] 	No signing certificate "iOS Development" found: No "iOS Development" signing certificate matching team ID "3R6C4ZD3NV" with a private key was found. (in target 'WebDriverAgentLib')
[Xcode] 	WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file. The file doesn’t exist. (Underlying error: The operation couldn’t be completed. No such file or directory)))
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[Xcode] Testing started on 'iPhone'
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[BaseDriver] Event 'wdaStartFailed' logged at 1542083723097 (12:35:23 GMT+0800 (+08))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 33753)
[XCUITest] iproxy exited with code 'null'
[XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[XCUITest]     at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:444:13)
[XCUITest]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[XCUITest]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[XCUITest]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[XCUITest]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest]     at run (/Applications/Appium.app/Contents/Resources/app/webpack:/~/babel-polyfill/~/core-js/modules/es6.promise.js:75:1)
[XCUITest]     at /Applications/Appium.app/Contents/Resources/app/webpack:/~/babel-polyfill/~/core-js/modules/es6.promise.js:92:1
[XCUITest]     at flush (/Applications/Appium.app/Contents/Resources/app/webpack:/~/babel-polyfill/~/core-js/modules/_microtask.js:18:1)
[XCUITest]     at process._tickCallback (internal/process/next_tick.js:61:11)
[XCUITest] Parsed BUILD_DIR configuration value: '/Users/anakin/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products'
[XCUITest] Got derived data root: '/Users/anakin/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs'
[XCUITest] Started background XCTest logs cleanup: find -E /private/var/folders -regex '.*/Session-WebDriverAgentRunner.*\.log$|.*/StandardOutputAndStandardError\.txt$' -type f -exec sh -c 'echo "" > "{}"' \;
[XCUITest] Cleaning test logs in '/Users/anakin/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs' folder
[iOS] Clearing log files
[iOS] Deleting '/Users/anakin/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs'. Freeing 132K.
[iOS] Finished clearing log files
[iOSLog] Stopping iOS log capture
[BaseDriver] Event 'newSessionStarted' logged at 1542083726031 (12:35:26 GMT+0800 (+08))
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[MJSONWP]     at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:444:13)
[MJSONWP]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP]     at run (/Applications/Appium.app/Contents/Resources/app/webpack:/~/babel-polyfill/~/core-js/modules/es6.promise.js:75:1)
[MJSONWP]     at /Applications/Appium.app/Contents/Resources/app/webpack:/~/babel-polyfill/~/core-js/modules/es6.promise.js:92:1
[MJSONWP]     at flush (/Applications/Appium.app/Contents/Resources/app/webpack:/~/babel-polyfill/~/core-js/modules/_microtask.js:18:1)
[MJSONWP]     at process._tickCallback (internal/process/next_tick.js:61:11)
[HTTP] <-- POST /wd/hub/session 500 29692 ms - 470
[HTTP] 
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 7 ms - 57
[HTTP]

**Comment by NiveditaMirjikar** [comment]
@Manish503 Can you please tell me what solution did you find for the above problem. I'm facing similar issue

**Comment by Manish503** [comment]
Try with command in terminal 
xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' test 
if it is successful u will get below message in terminal
 Test Suite 'All tests' started at 2017-01-23 15:49:12.585
    Test Suite 'WebDriverAgentRunner.xctest' started at 2017-01-23 15:49:12.586
    Test Suite 'UITestingUITests' started at 2017-01-23 15:49:12.587
    Test Case '-[UITestingUITests testRunner]' started.
        t =     0.00s     Start Test at 2017-01-23 15:49:12.588
        t =     0.00s     Set Up
if this message didn't get means something issue with xcode configuration

**Comment by rkn411** [comment]
Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder “WebDriverAgentRunner_iphoneos13.1-arm64.xctestrun” doesn’t exist."

@ appium 1.15
xcode 11.1 seed
iphone8- 12.4

@imurchie @jlipps

**Comment by rafaelcs** [comment]
I'm having the same issue
