### ISSUE TITLE
XPath not working.

### ISSUE THREAD

**Issue by sairamprasath** [appium/appium#11674]
Hi,
I am automating a UWP application (Windows 10) through Appium + Winapp driver. 

I am using Appium inspector to spy the objects in the windows 10 app. There is no name available for the button and therefore trying to use the Xpath - //Window/Window[2]/Button[2]

I tried clicking the tap button in the appium inspector and it is clicking on the button name.

If use the xpath in my selenium code like the below it is not working.

driver.findElementByXPath("//Window[2]/Button[2]").click();

Can you please let me know why the script is not able to click the button at the same time the appium inspector can click it.

**Environment**
Appium version - 1.9.1
WinApp Version - 1.1
Java client - 6.1
OS - Windows 10

**Comment by mykola-mokhnach** [comment]
Because the xpath `//Window[2]/Button[2]` is not equal to `/Window/Window[2]/Button[2]`

**Comment by sairamprasath** [comment]
Hi Mykola,
Even if I put double slash before it doesn't work.  What should I do to make it work?

**Comment by mykola-mokhnach** [comment]
Depending on what one wants to find. I'd start with studying how xpath queries work.

**Comment by mykola-mokhnach** [comment]
https://stackoverflow.com/questions/3674569/how-to-select-specified-node-within-xpath-node-sets-by-index-with-selenium
