### ISSUE TITLE
【Resolved】Original error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". 

### ISSUE THREAD

**Issue by Owen-ET** [appium/appium#11688]
## The problem

An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.

## Environment

* Appium version ：1.9.1
* Appium-desktop：1.7.1
* Xcode：10.0
* iPhone5S：IOS(10.3.3)
* Mac：10.13.6
* WDA

## Details

When I first started the appium-desktop+IOS automation test, I started WDA manually. The configured WDA is also replaced under appium-desktop. The second time to implement automation, because WDA is about, I just started appium-desktop. Do I have to start WDA manually every time? This is too troublesome. Is there a solution to start appium with automatic starting WDA?

## Link to Appium logs

[Xcode] 
[Xcode] 
[Xcode] Testing failed:
[Xcode] 	Provisioning profile "iOS Team Provisioning Profile: com.facebook.WebDriverAgentRunner.zc1224" expired on 2018年11月15日. (in target 'WebDriverAgentRunner')
[Xcode] 
[Xcode] 	WebDriverAgentRunner-Runner.app encountered an error (A valid provisioning profile for this executable was not found.)
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[Xcode] Testing started on 'iPhone5s'
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[BaseDriver] Event 'wdaStartFailed' logged at 1542245730814 (09:35:30 GMT+0800 (CST))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 1178)
[XCUITest] iproxy exited with code 'null'
[XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[XCUITest]     at XCUITestDriver.quitAndUninstall$ (/Applications/Project/Appium1.7.1.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:444:13)
[XCUITest]     at tryCatch (/Applications/Project/Appium1.7.1.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[XCUITest]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Project/Appium1.7.1.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[XCUITest]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Project/Appium1.7.1.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[XCUITest]     at GeneratorFunctionPrototype.invoke (/Applications/Project/Appium1.7.1.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest]     at 
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[iOSLog] Stopping iOS log capture
[BaseDriver] Event 'newSessionStarted' logged at 1542245731474 (09:35:31 GMT+0800 (CST))
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[MJSONWP]     at XCUITestDriver.quitAndUninstall$ (/Applications/Project/Appium1.7.1.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:444:13)
[MJSONWP]     at tryCatch (/Applications/Project/Appium1.7.1.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Project/Appium1.7.1.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Project/Appium1.7.1.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (/Applications/Project/Appium1.7.1.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP]     at 
[HTTP] <-- POST /wd/hub/session 500 38438 ms - 470
[HTTP] 
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 2 ms - 57
[HTTP]

**Comment by Owen-ET** [comment]
After querying, you can add "useNewWDA": "true" in the appium configuration parameter. As shown in the following picture.

<img width="917" alt="default" src="https://user-images.githubusercontent.com/42259434/48526139-8905f000-e8c1-11e8-9c44-a3b82f1b0581.png">

**Comment by mykola-mokhnach** [comment]
> A valid provisioning profile for this executable was not found

Closed as duplicate
