### ISSUE TITLE
App not launching after updating iOS to 12.1 and Appium 1.9.1

### ISSUE THREAD

**Issue by JasWoolieX** [appium/appium#11685]
## The problem

After the IPhone software updated to 12.1, Appium is not able to launch the app when when I use the desktop Appium client.
I upgraded appium to 1.9.1, Xcode to 10.0 and upgraded carthage. Please help!!

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 10.13.6
* Node.js version (unless using Appium.app|exe):v10.10.0
* Mobile platform/version under test: IPhone 8 plus (12.1)
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: CLI and exe both

## LOG Details

The server is running
[Appium] Welcome to Appium v1.9.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/sessions
[HTTP] {}
[GENERIC] Calling AppiumDriver.getSessions() with args: []
[GENERIC] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 6 ms - 40
[HTTP] 
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"/Users/njbh1/***/app/qa.ipa","automationName":"XCUITest","deviceName":"jaspreet’s iPhone","platformName":"iOS","udid":"a4454e3ce24a8fbc46e714ccd83d6906ba1ac79c","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/njbh1/***app/qa.ipa","automationName":"XCUITest","deviceName":"jaspreet’s iPhone","platformName":"iOS","udid":"a4454e3ce24a8fbc46e714ccd83d6906ba1ac79c","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1542194963318 (22:29:23 GMT+1100 (AEDT))
[Appium] Creating new XCUITestDriver (v2.94.2) session
[Appium] Capabilities:
[Appium]   app: /Users/***/Official/app/qa.ipa
[Appium]   automationName: XCUITest
[Appium]   deviceName: jas’s iPhone
[Appium]   platformName: iOS
[Appium]   udid: a4454e3ce24a8fbc46e714ccd83d6906ba1ac79c
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[BaseDriver] Creating session with MJSONWP desired capabilities: {"app":"/Users/njbh1/Deskto...
[BaseDriver] Session created with session id: f514617c-5350-4a84-b4ad-e350155bab3a
[XCUITest] Current user: 'njbh1'
[XCUITest] Xcode version set to '10.0' (tools v10.1.0.0.1.1539992718)
[XCUITest] iOS SDK Version set to '12.0'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1542194963690 (22:29:23 GMT+1100 (AEDT))

--Now its failing with " xcodebuild exited with code '70' and signal 'null'" error. Please help.

**Comment by mykola-mokhnach** [comment]
Make sure Xcode caches/derived data are reset. Also, it is recommended to use appium@beta with Xcode10

**Comment by JasWoolieX** [comment]
thanks @mykola for your reply.
Should I upgrade to 1.9.2 beta version for appium?
How can I upgrade from 1.9.1?

**Comment by JasWoolieX** [comment]
@mykola-mokhnach I have upgraded to 1.9.2-beta.2
and also Cleared the cache and derived data of Xcode.
But still the build fails with this message:

 Original error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 70".

**Comment by mykola-mokhnach** [comment]
Try another machine.

**Comment by mromero3005** [comment]
I ran into that issue and iOS 12.1 requires update of Xcode to 10.1. I believe that's all you should need to do. Hope this helps

**Comment by swatikalra** [comment]
Hi, I am using appium 1.11.1 and xcode 10.0.2. When running an appium test, the application gets installed on a real iOS device but the WDA fails to launch the app.

Original error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65".
