### ISSUE TITLE
Can't switch window on ipad device with ios12

### ISSUE THREAD

**Issue by thaichau298** [appium/appium#11683]
## The problem

I run automation test on ipad with ios12. When button are clicked and open the new tab then switch window command are performed. The error are appreanced

##Message error on Jenkins :
(err_0038)Error Message:An unknown server-side error occurred while processing the command. Original error: this.rpcClient.allowNavigationWithoutReload is not a function
Build info: version: '3.141.0', revision: '2ecb7d9a', time: '2018-10-31T20:09:30'

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.2-beta.2
* Desktop OS/version used to run Appium: macOS High Sierra (10.13.6)
* Node.js version (unless using Appium.app|exe): 11.1.0
* Mobile platform/version under test: ipad air (12.0.1)
* Real device or emulator/simulator: Real device

## Link to Appium logs

https://gist.github.com/thaichau298/d0f28d21722717a4349d177d6c23fc9e

**Comment by mykola-mokhnach** [comment]
@imurchie FYI

**Comment by thaichau298** [comment]
@mykola-mokhnach this is a bug and can't resolve now ? Please provide for me advice

**Comment by mykola-mokhnach** [comment]
The fix has been merged to appium@beta

**Comment by thaichau298** [comment]
> The fix has been merged to appium@beta

Which version had fixed ? i'm using appium 1.9.2-beta.2 but can't switch

**Comment by KazuCocoa** [comment]
Which version of `appium-remote-debugger` did you use in current your environment?

If your `appium 1.9.2-beta.2` is not the latest one, you should uninstall and install the `appium 1.9.2-beta.2`. Then, the beta should have `appium-remote-debugger` `3.22.3`
