### ISSUE TITLE
WebdriverAgent taking 1-2 minutes to create session after run 51 test cases 

### ISSUE THREAD

**Issue by saigovindu** [appium/appium#11687]
While creating IOSDriver instance, it taking around 1-2 min to create WDA session.
 driver = new IOSDriver(new Uri(config.Grid), capabilities, TimeSpan.FromMinutes(2));

Environment
Appium version (or git revision) that exhibits the issue: 1.9.1
Desktop OS/version used to run Appium:OS X EI Caption
Node.js version : 9
Xcode:8.1
Mobile platform/version under test: iOS 10.1
Real device or emulator/simulator: Simulator
Appium CLI or Appium.app|exe: Appium CLI

Details
While "Sending createSession command to WDA", it take few min.
If I restart simulator, first 51 test cases it working fine but in next execution again I face same issue.

2018-11-14 12:37:44:583 - [debug] [XCUITest] Sending createSession command to WDA
2018-11-14 12:38:48:210 - [Appium] New XCUITestDriver session created successfully, session b2f23ff2-1c1d-412a-a01f-d0609b62e077 added to master session list
2018-11-14 12:38:48:210 - [debug] [BaseDriver] Event 'newSessionStarted' logged at 1542227928210 (12:38:48 GMT-0800 (PST))

I had seen some related issues, https://github.com/appium/appium/issues/8721, they suggested to use waitForQuiescence:false so I used but it not working even single time, Webdriver just open and close multiple times (Logs: https://gist.github.com/saigovindu/a7eb123eb88a7c056da3c3cac6fba39e) 

Code line while executing :-
 driver = new IOSDriver(new Uri(config.Grid), capabilities, TimeSpan.FromMinutes(2));

Appium Server Log :-
https://gist.github.com/saigovindu/53e027c049a40584cf90950048671e7a

**Comment by lanzelot1989** [comment]
Is it always the 52nd test that has the problems? I guess then it would be interesting what the test case before it does.

**Comment by saigovindu** [comment]
I am performing performance test so same I am using same test case for all tests. 
I wrote code that will create web driver -> run test case -> close web driver, this will repeat for few hours to see how the webdriver performing.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue. Please report to https://github.com/facebook/WebDriverAgent
