### ISSUE TITLE
A lot of errors when try to run ios tests

### ISSUE THREAD

**Issue by seregajoys** [appium/appium#11684]
What the problem?
Appium desktop 1.8.2 appium server 1.9.1
Iphone 7 IOS 11.4(emulator)
MacOS 10.13.6
Xcode 9.14.1
node v10.13.0
maven 3.6.0
jdk 1.8

[MJSONWP] Encountered internal error running command: Error: Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: *** -[NSProxy forwardInvocation:] called!
[MJSONWP]
[MJSONWP] (
[MJSONWP] 0 CoreFoundation 0x000000010ddb91e6 __exceptionPreprocess + 294
[MJSONWP] 1 libobjc.A.dylib 0x000000010d44e031 objc_exception_throw + 48
[MJSONWP] 2 CoreFoundation 0x000000010de2e975 +[NSException raise:format:] + 197
[MJSONWP] 3 Foundation 0x000000010ce8ba90 -[NSProxy respondsToSelector:] + 95
[MJSONWP] 4 Foundation 0x000000010ce32e3e _NSDescriptionWithStringProxyFunc + 49
[MJSONWP] 5 CoreFoundation 0x000000010dcf4214 __CFStringAppendFormatCore + 10180
[MJSONWP] 6 CoreFoundation 0x000000010dcf1a14 _CFStringCreateWithFormatAndArgumentsAux2 + 116
[MJSONWP] 7 XCTest 0x000000010cd189ac _XCINFLog + 241
[MJSONWP] 8 XCTest 0x000000010cd46bdf -[XCUIApplicationImpl setCurrentProcess:] + 68
[MJSONWP] 9 Foundation 0x000000010ce6fb47 -[NSObject(NSKeyValueCoding) setValue:forKey:] + 292
[MJSONWP] 10 WebDriverAgentLib 0x0000000123dad32a -[FBApplication observeValueForKeyPath:ofObject:change:context:] + 554
[MJSONWP] 11 Foundation 0x000000010ce63820 NSKeyValueNotifyObserver + 349
[MJSONWP] 12 Foundation 0x000000010ce43fa0 -[NSObject(NSKeyValueObserverRegistration) _addObserver:forProperty:options:context:] + 255
[MJSONWP] 13 Foundation 0x000000010ce42e33 -[NSObject(NSKeyValueObserverRegistration) addObserver:forKeyPath:options:context:] + 103
[MJSONWP] 14 WebDriverAgentLib 0x0000000123dace29 -[FBApplication launch] + 153
[MJSONWP] 15 WebDriverAgentLib 0x0000000123d9ae03 +[FBSessionCommands handleCreateSession:] + 1555
[MJSONWP] 16 WebDriverAgentLib 0x0000000123d73a63 -[FBRoute_TargetAction mountRequest:intoResponse:] + 179
[MJSONWP] 17 WebDriverAgentLib 0x0000000123d60f54 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 548
[MJSONWP] 18 RoutingHTTPServer 0x0000000123e51c18 -[RoutingHTTPServer handleRoute:withRequest:response:] + 136
[MJSONWP] 19 RoutingHTTPServer 0x0000000123e524fa __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 47
[MJSONWP] 20 libdispatch.dylib 0x000000011253c779 _dispatch_client_callout + 8
[MJSONWP] 21 libdispatch.dylib 0x0000000112547c3f _dispatch_sync_thread_bound_invoke + 108
[MJSONWP] 22 libdispatch.dylib 0x000000011253c779 _dispatch_client_callout + 8
[MJSONWP] 23 libdispatch.dylib 0x0000000112546778 _dispatch_main_queue_callback_4CF + 1279
[MJSONWP] 24 CoreFoundation 0x000000010dd7bc99 CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE + 9
[MJSONWP] 25 CoreFoundation 0x000000010dd3fea6 _CFRunLoopRun + 2342
[MJSONWP] 26 CoreFoundation 0x000000010dd3f30b CFRunLoopRunSpecific + 635
[MJSONWP] 27 Foundation 0x000000010ce49b4a -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 274
[MJSONWP] 28 WebDriverAgentLib 0x0000000123d5fafd -[FBWebServer startServing] + 365
[MJSONWP] 29 WebDriverAgentRunner 0x000000012344814e -[UITestingUITests testRunner] + 126
[MJSONWP] 30 CoreFoundation 0x000000010dd3cccc invoking + 140
[MJSONWP] 31 CoreFoundation 0x000000010dd3cb84 -[NSInvocation invoke] + 308
[MJSONWP] 32 XCTest 0x000000010ccd501a __24-[XCTestCase invokeTest]_block_invoke.184 + 74
[MJSONWP] 33 XCTest 0x000000010cd2fae3 +[XCTestCase(Failures) performFailableBlock:shouldInterruptTest:] + 36
[MJSONWP] 34 XCTest 0x000000010cd2fa2e -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] + 54
[MJSONWP] 35 XCTest 0x000000010ccd4ce3 __24-[XCTestCase invokeTest]_block_invoke + 847
[MJSONWP] 36 XCTest 0x000000010cd34a7d -[XCUITestContext performInScope:] + 248
[MJSONWP] 37 XCTest 0x000000010ccd497f -[XCTestCase invokeTest] + 175
[MJSONWP] 38 XCTest 0x000000010ccd6555 __26-[XCTestCase performTest:]_block_invoke_2 + 42
[MJSONWP] 39 XCTest 0x000000010cd2fae3 +[XCTestCase(Failures) performFailableBlock:shouldInterruptTest:] + 36
[MJSONWP] 40 XCTest 0x000000010cd2fa2e -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] + 54
[MJSONWP] 41 XCTest 0x000000010ccd6402 __26-[XCTestCase performTest:]_block_invoke.318 + 90
[MJSONWP] 42 XCTest 0x000000010cd3c061 +[XCTContext runInContextForTestCase:block:] + 225
[MJSONWP] 43 XCTest 0x000000010ccd5aff -[XCTestCase performTest:] + 673
[MJSONWP] 44 XCTest 0x000000010cd18727 -[XCTest runTest] + 57
[MJSONWP] 45 XCTest 0x000000010ccd1341 __27-[XCTestSuite performTest:]_block_invoke + 365
[MJSONWP] 46 XCTest 0x000000010ccd0b1d -[XCTestSuite _performProtectedSectionForTest:testSection:] + 55
[MJSONWP] 47 XCTest 0x000000010ccd0dde -[XCTestSuite performTest:] + 296
[MJSONWP] 48 XCTest 0x000000010cd18727 -[XCTest runTest] + 57
[MJSONWP] 49 XCTest 0x000000010ccd1341 __27-[XCTestSuite performTest:]_block_invoke + 365
[MJSONWP] 50 XCTest 0x000000010ccd0b1d -[XCTestSuite _performProtectedSectionForTest:testSection:] + 55
[MJSONWP] 51 XCTest 0x000000010ccd0dde -[XCTestSuite performTest:] + 296
[MJSONWP] 52 XCTest 0x000000010cd18727 -[XCTest runTest] + 57
[MJSONWP] 53 XCTest 0x000000010ccd1341 __27-[XCTestSuite performTest:]_block_invoke + 365
[MJSONWP] 54 XCTest 0x000000010ccd0b1d -[XCTestSuite _performProtectedSectionForTest:testSection:] + 55
[MJSONWP] 55 XCTest 0x000000010ccd0dde -[XCTestSuite performTest:] + 296
[MJSONWP] 56 XCTest 0x000000010cd18727 -[XCTest runTest] + 57
[MJSONWP] 57 XCTest 0x000000010cd45fa6 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 40
[MJSONWP] 58 XCTest 0x000000010cce9389 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 594
[MJSONWP] 59 XCTest 0x000000010cd45db1 -[XCTTestRunSession runTestsAndReturnError:] + 369
[MJSONWP] 60 XCTest 0x000000010ccb7c71 -[XCTestDriver runTestsAndReturnError:] + 447
[MJSONWP] 61 XCTest 0x000000010cd3abb1 _XCTestMain + 960
[MJSONWP] 62 WebDriverAgentRunner-Runner 0x000000010ca3049f _XCTRunnerRunTests + 57
[MJSONWP] 63 CoreFoundation 0x000000010dd5bb0c CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK + 12
[MJSONWP] 64 CoreFoundation 0x000000010dd402db __CFRunLoopDoBlocks + 331
[MJSONWP] 65 CoreFoundation 0x000000010dd3fa84 __CFRunLoopRun + 1284
[MJSONWP] 66 CoreFoundation 0x000000010dd3f30b CFRunLoopRunSpecific + 635
[MJSONWP] 67 GraphicsServices 0x00000001110e0a73 GSEventRunModal + 62
[MJSONWP] 68 UIKit 0x000000010e2360b7 UIApplicationMain + 159
[MJSONWP] 69 WebDriverAgentRunner-Runner 0x000000010ca306dc main + 42
[MJSONWP] 70 libdyld.dylib 0x00000001125b1955 start + 1
[MJSONWP] 71 ??? 0x0000000000000005 0x0 + 5
[MJSONWP] )
[MJSONWP] at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:444:13)
[MJSONWP] at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP] at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP] at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js💯21)
[MJSONWP] at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP] at run (/Applications/Appium.app/Contents/Resources/app/webpack://babel-polyfill//core-js/modules/es6.promise.js:75:1)
[MJSONWP] at /Applications/Appium.app/Contents/Resources/app/webpack://babel-polyfill//core-js/modules/es6.promise.js:92:1
[MJSONWP] at flush (/Applications/Appium.app/Contents/Resources/app/webpack://babel-polyfill//core-js/modules/_microtask.js:18:1)
[MJSONWP] at process._tickCallback (internal/process/next_tick.js:61:11)
[HTTP] <-- POST /wd/hub/session 500 137837 ms - 7916
[HTTP]

**Comment by mykola-mokhnach** [comment]
This is fixed in appium@beta.
Closed as duplicate
