### ISSUE TITLE
After clicking WeChat search box, it does not display page source.

### ISSUE THREAD

**Issue by ERICXZY** [appium/appium#11689]
## The problem

After each login, the page source can be displayed by clicking the search box in a short time. But after a while, it will not work.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac and Ubuntu
* Node.js version (unless using Appium.app|exe): v8.11.4
* Mobile platform/version under test: android 6.0 flyme/meizu
* Real device or emulator/simulator: real
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

```
        self.desired_caps = {}
        self.desired_caps['platformName'] = 'Android'
        self.desired_caps['platformVersion'] = "6.0"
        self.desired_caps['deviceName'] = serial
        self.desired_caps['newCommandTimeout'] = 200
        self.desired_caps['appPackage'] = 'com.tencent.mm'
        '.plugin.account.ui.MobileInputUI'
        '.app.WeChatSplashActivity'
        self.desired_caps['appActivity'] = '.ui.LauncherUI'
        self.desired_caps['systemPort'] = systemPort
        # self.desired_caps['resetKeyboard'] = True
        self.desired_caps['unicodeKeyboard'] = True
        self.desired_caps['noReset'] = True
        # self.desired_caps['automationName'] = 'UiAutomator2'
        self.desired_caps['chromeOptions'] = {'androidProcess': 'com.tencent.mm:appbrand0'}
        self.desired_caps['recreateChromeDriverSessions'] = True
        self.driver = webdriver.Remote('http://localhost:%s/wd/hub' % port, self.desired_caps)**

        el = self.driver.find_element_by_android_uiautomator('new UiSelector().description("搜索")')
```

**Comment by mykola-mokhnach** [comment]
Please provide full server log

**Comment by ERICXZY** [comment]
> Please provide full server log

[HTTP] --> POST /wd/hub/session/6c064f22-a5e8-4330-a195-b950896b1186/element
[HTTP] {"using":"xpath","value":"//android.widget.EditText[@resource-id=\"com.tencent.mm:id/ji\" or @resource-id=\"com.tencent.mm:id/ij\" or @resource-id=\"com.tencent.mm:id/jd\"]","sessionId":"6c064f22-a5e8-4330-a195-b950896b1186"}
[MJSONWP] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[MJSONWP]     at AndroidDriver.callee$0$0$ (/Users/exiao/.nvm/versions/node/v8.9.0/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/find.js:75:11)
[MJSONWP]     at tryCatch (/Users/exiao/.nvm/versions/node/v8.9.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/exiao/.nvm/versions/node/v8.9.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/exiao/.nvm/versions/node/v8.9.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (/Users/exiao/.nvm/versions/node/v8.9.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP]     at <anonymous>
[HTTP] <-- POST /wd/hub/session/6c064f22-a5e8-4330-a195-b950896b1186/element 500 412 ms - 164
[HTTP] 
*** selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.
