### ISSUE TITLE
UI Automator shows elements with [0,0][0,0] for the tab elements

### ISSUE THREAD

**Issue by parasuramankumarasami** [appium/appium#11691]
Android : Pie
when we take device screenshot in UI automator, we are getting elements with [0,0][0,0]. any idea?

Please find the UI automator screenshot. this issue happening in only Android Pie(9) not in Android O or N.
Android P device screenshot:
![image](https://user-images.githubusercontent.com/12612847/48547311-54f5f380-e8f0-11e8-9b32-864aad4641c6.png)

Android O device screenshot.
![image](https://user-images.githubusercontent.com/12612847/48547607-0eed5f80-e8f1-11e8-97c5-0e0c050616a8.png)

**Comment by mykola-mokhnach** [comment]
These values are sent by the operating system. There is nothing that can be changed in Appium about it.
