### ISSUE TITLE
Unable to do perform any Touch, Press, Long press actions in iOS native app

### ISSUE THREAD

**Issue by viveksoundar** [appium/appium#11696]
Hi folks,
 I use Appium for iOS native app testing with Selenium and TestNG, I face this 
"Unhandled endpoint: /session/$session_ID/wda/touch/perform -- http://localhost:8080/ with parameters { wildcards =("$session_Id");} "  error while doing swipe or touch actions in my native app.

Appium version - 1.8.2
Appium server - v1.9.1
Xcode version - 10.1
iOS version - 12.0
Selenium-standalone-jar - 3.141.5

![screen shot 2018-11-16 at 2 35 18 pm](https://user-images.githubusercontent.com/37587895/48613506-f1cc9580-e9b1-11e8-90ca-5cc043c72620.png)

**Comment by mykola-mokhnach** [comment]
Use appium@beta with Xcode10.1
Also. clear Xcode caches and delete WebDriverAgent binary from the device to make sure you have the most recent version of it

**Comment by viveksoundar** [comment]
@mykola-mokhnach Even now I am facing the same problem, I am using Appium server version 1.9.2 Beta.

**Comment by mykola-mokhnach** [comment]
I still don't see where the full server log is

**Comment by viveksoundar** [comment]
@mykola-mokhnach Here is the complete [log](https://gist.github.com/viveksoundar/97e06b9c87f63c00edb75cf7a5359ada).

**Comment by mykola-mokhnach** [comment]
> Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Unhandled endpoint: /session/D6105D2F-BBEA-40A6-AD42-35125FFDEB78/wda/touch/perform

The WebDriverAgent binary on the device is either outdated or wrong. Try to clear Xcode caches, uninstall WebDriverAgentRunner manually and make sure the correct version of it is deployed

**Comment by viveksoundar** [comment]
@mykola-mokhnach I used the latest commit of [WebDriverAgent](https://github.com/facebook/WebDriverAgent) repository. Should I change the commit version or anything? Even I tried to remove the WebDriverAgentRunner from my device manually and cleared derived data from Xcode.

**Comment by mykola-mokhnach** [comment]
The build from Facebook repository is not compatible to the one used by Appium: https://github.com/appium/WebDriverAgent

**Comment by viveksoundar** [comment]
@mykola-mokhnach Thanks. It's working perfectly fine (y).
