### ISSUE TITLE
How to automate an app downloaded from App Store on real iOS device

### ISSUE THREAD

**Issue by oldstone** [appium/appium#11695]
I want to be able to use Appium to automate iOS apps that are on the App Store e.g. GoogleMaps (of which I do not own) on multiple real iOS devices. What I have done so far is using a tool called iMazing to download the app into an IPA file and then use the `App` capability to let Appium install and launch the app. However, I found that to use the downloaded app on a different iOS device I have to modify the AppleId in the IPA file's `itunesmetadata.plist` file to match the iOS device in order for this to work.

My questions are:
1. Is there any other way to automate iOS apps that I don't own on real iOS devices?  A way in which I do not need to unzip, change the itunes data and rezip to use for Appium testing.
2. Is there another way to extract/download an iOS app I don't own and produce an app file that is Appium firendly?

**Environment**
Appium version (or git revision) that exhibits the issue: 1.9.1
Desktop OS/version used to run Appium: Mac OS Pro
Mobile platform/version under test: iOS 11.2
Real device or emulator/simulator: real

**Comment by Dan-Maor** [comment]
You can use the old iTunes version which still has the ability to download IPA files from the Appstore.

You can download it from here:
https://support.apple.com/en-il/HT208079

**Comment by oldstone** [comment]
> 
> 
> You can use the old iTunes version which still has the ability to download IPA files from the Appstore.
> 
> You can download it from here:
> https://support.apple.com/en-il/HT208079

Dan-Maor The IPA files downloaded from the old iTunes are associated with the iTune's Apple ID and the unpack/repack still needs to be done to use those IPA files on different devices.

**Comment by Dan-Maor** [comment]
They are associated, of course, but you can still install them, that's how I'm testing these sort of apps.
If the Apple ID is associated with the device you can just install and launch them, if not - you'll need to launch them manually first and input the iTunes user name and password used for downloading the app in the shown popup (only once, you can then uninstall and reinstall it and the popup won't appear again).

If you would like to refrain from sharing the account's password on other devices, then unfortunately I'm not aware of other _legal_ ways of producing such IPA files.

**Comment by mykola-mokhnach** [comment]
Developer signature is anyway necessary to run WebDriverAgent on real device.
