### ISSUE TITLE
UIAutomator exits with code 134.

### ISSUE THREAD

**Issue by sachinnrao** [appium/appium#11692]
## The problem

I have an automated test case for which I use Appium to automate the UI. The test case contains a step where Appium polls for a particular button to appear on the screen. While doing this, I get an error stating **UiAutomator exited unexpectedly with code 134, signal null**

Not sure what this error code is. Please help.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Desktop OS/version used to run Appium: Ubuntu 
* Mobile platform/version under test: Android P
* Real device or emulator/simulator: Real Device

## Link to Appium logs

https://gist.github.com/sachinnrao/45f21ba08e44ae06a7e1aa7599f78be5

**Comment by mykola-mokhnach** [comment]
Just don't use UIA1 for Android  6+. Switch to UIA2
