### ISSUE TITLE
driver.findImageOccurrence - how set threshold value? 

### ISSUE THREAD

**Issue by jerzynowakowski** [appium/appium#11705]
## The problem

Can't manipulate expected threshold value for image occurence 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1

## Details
Unable to manipulate the threshold value for some images using
driver.findImageOccurrence

## Link to Appium logs

`Cannot find any occurrences of the partial image in the full image above the threshold of 0.5`

## Code To Reproduce Issue [ Good To Have ]

`File screenShot = ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE);`
`String expectedImagesPath = System.getProperty("user.dir") + "/src/test/resources/images/";`
`driver.findImageOccurrence(screenShot, new File(expectedImagesPath + "image.png"));`

**Comment by jerzynowakowski** [comment]
> https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/image-comparison.md

I tried that before writing the post, but did not help.

**Comment by mykola-mokhnach** [comment]
What exactly did you try? I don't see any additional options are passed in the code example above

**Comment by mykola-mokhnach** [comment]
Probably, it is just necessary to use another matcher

**Comment by jerzynowakowski** [comment]
> What exactly did you try? I don't see any additional options are passed in the code example above

I tried with Feature-based Comparison part of the code modifed per my images:

`byte[] screenshot = Base64.encodeBase64(driver.getScreenshotAs(OutputType.BYTES));
FeaturesMatchingResult result = driver
        .matchImagesFeatures(screenshot, originalImg, new FeaturesMatchingOptions()
                .withDetectorName(FeatureDetector.ORB)
                .withGoodMatchesFactor(40)
                .withMatchFunc(MatchingFunction.BRUTE_FORCE_HAMMING)
                .withEnabledVisualization());
assertThat(result.getVisualization().length, is(greaterThan(0)));
assertThat(result.getCount(), is(greaterThan(0)));
assertThat(result.getTotalCount(), is(greaterThan(0)));
assertFalse(result.getPoints1().isEmpty());
assertNotNull(result.getRect1());
assertFalse(result.getPoints2().isEmpty());
assertNotNull(result.getRect2());`

**Comment by jerzynowakowski** [comment]
> Probably, it is just necessary to use another matcher

The problem is how to force matcher to expected threshold value

**Comment by mykola-mokhnach** [comment]
I'm not quite sure what threshold we are talking about. Can you please go through the source code and say which exact value should be tuned? 

Here is the Appium client code
https://github.com/appium/appium-support/blob/master/lib/image-util.js
and here is the wrapper library:
https://github.com/justadudewhohacks/opencv4nodejs

**Comment by mykola-mokhnach** [comment]
Try if https://github.com/appium/java-client/pull/1060 works for you. Use jitpack.io repository to get the recent master snapshot
