### ISSUE TITLE
Connection Problem with devices when using an USB hub

### ISSUE THREAD

**Issue by nicodeur** [appium/appium#11710]
## The problem

Hello, I have connections issues with my Android devices with Adb when I use a USB hub

Devices are disconnected regulary when I use an autoalimented hub (I use [this hub](https://www.amazon.fr/Plugable-SuperSpeed-adaptateur-secteur-appareils/dp/B00RNFY8HQ/ref=sr_1_fkmr0_1?ie=UTF8&qid=1542271619&sr=8-1-fkmr0&keywords=Plugable+USB+2.0+7-Port+High+Speed+Charging+Hub+with+60W+Power+Adapter) who is advice by [openstf](https://github.com/openstf/stf) ). I already try others hub, and i havec the same problem :'(

I don't have any problem when I plug devices directly on Computer Machine.

Have you any idea to resolve the problem ?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable): 1.8.1
* Desktop OS/version used to run Appium: Ubuntu 16.04
* Node.js version (unless using Appium.app|exe): v7.10.1
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real device throw a USB hub
* Appium CLI or Appium.app|exe: CLI

## Details
/

## Link to Appium logs
[Adb log](https://gist.github.com/nicodeur/3894e952895fdec3a4aaf472382c2d06#file-adb_disconnected_log )

 [Appium log](https://gist.github.com/nicodeur/28fe41a90fd67c987cbc00f5bb30cdfb#file-appium_disconnected_log)

## Code To Reproduce Issue [ Good To Have ]
/

**Comment by mykola-mokhnach** [comment]
How the problem might be related to Appium?

**Comment by nicodeur** [comment]
I don't think if it is a problem with Appium, but I just ask to you if you already had a similar problem ...

**Comment by mykola-mokhnach** [comment]
I would rather ask on Appium forum. This is the place for issues

**Comment by nicodeur** [comment]
Ok, I move this to the forum
