### ISSUE TITLE
Clear Webview cache

### ISSUE THREAD

**Issue by patoski123** [appium/appium#11713]
## The problem

hello, 
 i have manage to successfully automate my app (C#), but when i re-run the test it fails and i know why it fails but dont know how to solve it. The problem is:
1. when app starts 'click the sign in button'
2. it take you to Chrome(which is a webview) for authentication(enter UserId and password)
3 Valid credentials signs User in and redirects them back to the app
4 User sets up pin code as a first User and start using the app

but when i re-run the test with In_Valid credential which should fail at authentication, this happens:
1.'Sign in button ' is clicked (which is fine)
2. it takes me to Chrome for authentication, but on getting to chrome it quickly re-directs me to the app as if i have passed the authentication.
3.User asked to set up pin.   

## Environment

*  Appium v1.7.2
* Desktop OS/version used to run Appium:
* Node.js version 6.4.1
* Mobile platform/version under test: Android
* Real device : Samsung S8

## Details

i have tried FullReset "true",NoReset "false".. not working
MobileDriver.Manage().Cookies.DeleteAllCookies; not working

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]
DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
                desiredCapabilities.SetCapability(MobileCapabilityType.PlatformName, "Android");
                desiredCapabilities.SetCapability(MobileCapabilityType.DeviceName, "device");
              desiredCapabilities.SetCapability("appPackage", "");
              desiredCapabilities.SetCapability("appActivity", "");
                desiredCapabilities.SetCapability(MobileCapabilityType.AutomationName, "UiAutomator2");
                desiredCapabilities.SetCapability(MobileCapabilityType.App, @"C:");
                desiredCapabilities.SetCapability(MobileCapabilityType.FullReset, "true");
                MobileDriver = new AndroidDriver<AppiumWebElement>(new Uri("http://localhost:4723/wd/hub"), desiredCapabilities);

**Comment by KazuCocoa** [comment]
> MobileDriver.Manage().Cookies.DeleteAllCookies; not working

Did you get any logs about this? Could you attach full server log here?

(Should we use https://stackoverflow.com/questions/28998241/how-to-clear-cookies-and-cache-of-webview-on-android-when-not-in-webview to clear cookies in webview , btw?)

**Comment by mykola-mokhnach** [comment]
no log - no luck
