### ISSUE TITLE
Appium is unable to connect to ade.exe, Environment variable is proper.

### ISSUE THREAD

**Issue by adeadobe** [appium/appium#11726]
The server is running

[Appium] Welcome to Appium v1.9.1
[Appium] Non-default server args:
[Appium]   address: 127.0.0.1
[Appium] Appium REST http interface listener started on 127.0.0.1:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"appPackage":"com.adobe.digitaleditions","appActivity":"com.adobe.reader.ReaderMainActivity","platformVersion":"8.1.0","browserName":"","platformName":"Android","deviceName":"ASUS_X00TD"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"appPackage":"com.adobe.digitaleditions","appActivity":"com.adobe.reader.ReaderMainActivity","platformVersion":"8.1.0","browserName":"","platformName":"Android","deviceName":"ASUS_X00TD"},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1542961204433 (13:50:04 GMT+0530 (India Standard Time))
[Appium] Consider setting 'automationName' capability to 'UiAutomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.
[Appium] Creating new AndroidDriver (v4.1.1) session
[Appium] Capabilities:
[Appium]   appPackage: com.adobe.digitaleditions
[Appium]   appActivity: com.adobe.reader.ReaderMainActivity
[Appium]   platformVersion: 8.1.0
[Appium]   browserName: 
[Appium]   platformName: Android
[Appium]   deviceName: ASUS_X00TD
[BaseDriver] Creating session with MJSONWP desired capabilities: {"appPackage":"com.adobe.di...
[BaseDriver] Session created with session id: a31c48ad-096b-4776-bbac-cb6a905755c0
[AndroidDriver] Java version is: 1.8.0_144
[AndroidDriver] Shutting down Android driver
[AndroidDriver] Called deleteSession but bootstrap wasn't active
[BaseDriver] Event 'newSessionStarted' logged at 1542961204905 (13:50:04 GMT+0530 (India Standard Time))
[MJSONWP] Encountered internal error running command: Error: Could not find adb.exe in C:\Users\goud\AppData\Local\Android\sdk;C:\Users\goud\AppData\Local\Android\sdk\platform-tools;\platform-tools\adb.exe,C:\Users\goud\AppData\Local\Android\sdk;C:\Users\goud\AppData\Local\Android\sdk\platform-tools;\emulator\adb.exe,C:\Users\goud\AppData\Local\Android\sdk;C:\Users\goud\AppData\Local\Android\sdk\platform-tools;\tools\adb.exe,C:\Users\goud\AppData\Local\Android\sdk;C:\Users\goud\AppData\Local\Android\sdk\platform-tools;\tools\bin\adb.exe. Do you have the Android SDK installed at 'C:\Users\goud\AppData\Local\Android\sdk;C:\Users\goud\AppData\Local\Android\sdk\platform-tools;'?
[MJSONWP]     at ADB.callee$0$0$ (C:\Users\goud\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:106:11)
[MJSONWP]     at tryCatch (C:\Users\goud\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\goud\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\goud\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (C:\Users\goud\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[MJSONWP]     at 
[HTTP] <-- POST /wd/hub/session 500 473 ms - 833
[HTTP]

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/java-client/blob/master/docs/environment.md
