### ISSUE TITLE
Terminate and Activete app - session terminated

### ISSUE THREAD

**Issue by Phoenix124** [appium/appium#11734]
## The problem

Hello
I'm trying to terminateApp and than activateApp, and login into, but i have a problem
org.openqa.selenium.NoSuchSessionException: A session is either terminated or not started
Build info: version: ‘3.12.0’, revision: ‘7c6e0b3’, time: ‘2018-05-08T14:04:26.12Z’
System info: host: ‘iMac-Maksim.local’, ip: ‘fe80:0:0:0:18ac:14fb:349f:a1c0%en0’, os.name: ‘Mac OS X’, os.arch: ‘x86_64’, os.version: ‘10.13.6’, java.version: ‘1.8.0_192’
Driver info: io.appium.java_client.ios.IOSDriver

## Environment

* Appium version (or git revision) that exhibits the issue:
* Appium 1.9.1
* simulator:
* Appium CLI 

## Link to Appium logs

https://gist.github.com/Phoenix124/3d9374b7fb4210e7c39111911a985914

## Code To Reproduce Issue [ Good To Have ]

protected void closeApp() {
       Optional
               .ofNullable(driver)
               .ifPresent(driver -> driver.terminateApp(application.appBundleId));
   }

   protected void terminateAndRunApp(){
       closeApp();
       JavascriptExecutor js = driver;
       Map<String, Object> params = new HashMap<>();
       params.put(“bundleId”, application.appBundleId);
       js.executeScript(“mobile: activateApp”, params);
   }

**Comment by mykola-mokhnach** [comment]
Please attach full server log with `showIOSLog` cap set to true

**Comment by Phoenix124** [comment]
https://gist.github.com/Phoenix124/a7666f78218dd9f27396e3ae6b5eded3

**Comment by mykola-mokhnach** [comment]
I think this trick would only work with native apps, but not web views. For such case I would try to close the driver completely and then start it with noReset cap, so the webview connection state is synchronized properly.

**Comment by Phoenix124** [comment]
Ok, but can i do this in one Test?

**Comment by Phoenix124** [comment]
> I think this trick would only work with native apps, but not web views. For such case I would try to close the driver completely and then start it with noReset cap, so the webview connection state is synchronized properly.

@mykola-mokhnach it it worked , when i make driver.quit() and create new driver in one session.
Thanks for help.
