### ISSUE TITLE
[iOS 12.1] Wrong value of "enabled" attribute for SegmentedControl (XCUITest)

### ISSUE THREAD

**Issue by AnnaWyrwal** [appium/appium#11736]
## The problem

On iOS 12.1 there is an issue with XCUIElementTypeSegmentedControl: wrong value for "Enabled" attribute is returned from appium. It appeared that returned value for disabled control is true, although it should be false and on previous iOS versions (11.3) it was returned correctly. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.2-beta.2
* Desktop OS/version used to run Appium: macOS Mojave
* Node.js version (unless using Appium.app|exe): v8.12.0
* Mobile platform/version under test: iOS 12.1
* Real device or emulator/simulator: Both real iPad device and iPad Air 2 simulator
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

2 log files: one from iOS 11.3 and one from iOS 12.1 you can find under: https://gist.github.com/AnnaWyrwal/acbd451fa7d435a2901d9a3e16f52387

**Comment by mykola-mokhnach** [comment]
Please report the issue to Apple. Appium only shows what XCTest returns to it.

**Comment by rafaelcs** [comment]
Hello @AnnaWyrwal 

Did you find any solution to handle it? I'm getting the same issue.
Did you report this issue to Apple?

Thanks!

**Comment by AnnaWyrwal** [comment]
Hi @rafaelcs,

no, I didn't find a solution.  I reported that to Apple, but no response so far.
