### ISSUE TITLE
Tests start before appActivity and app are loaded. No timeout for this.

### ISSUE THREAD

**Issue by alexhidalgo** [appium/appium#11739]
## The problem

Tests start before app sign in view is displayed. This only happens on android v4 using UIAutomator.
It takes approximately 50 seconds for the Sign In view to display but by then the tests are already running. There doesn't appear to be a timeout available to increase the time between the `.MainActivity` and the view actually rendering that I am aware of.

Does anyone know of such timeout?

I'm unable to start the app using any other activity such as `.Splash` using a `appWait` config properties.

Is there another appium version i can try? 1.8.1 does not have `uiautomator` driver for me to test.

## Environment

* Appium version 1.9.1
* Last Appium version that did not exhibit the issue (if applicable): None
* Desktop OS/version used to run Appium: OSX 10.13.6
* Node.js version (unless using Appium.app|exe): v9.0.0
* Mobile platform/version under test: android v4.3.1
* Real device or emulator/simulator: REAL
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

https://gist.github.com/alexhidalgo/5142387e532b6a1f79770e13809c06fc

**Comment by mykola-mokhnach** [comment]
Closed as inactive. Unfortunately, not many people work with old Android versions (also the UIA1 driver itself is considered obsolete).
