### ISSUE TITLE
Date is not being set in UIAutomator2

### ISSUE THREAD

**Issue by prakashpqa** [appium/appium#11735]
## The problem

Date is not being set in UIAutomator2.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MAC OS 10.14.1
* Node.js version (unless using Appium.app|exe): 8.12.0
* Mobile platform/version under test: 8.0.0
* Real device or emulator/simulator: Real Device CLI
* Appium CLI or Appium.app|exe:

## Details

This is about date picker. Please refer the snapshot attached. I am able to set the year by locating the element, but when I am clicking on OK it's considering 2018 only.

![whatsapp](https://user-images.githubusercontent.com/30907200/49009388-70dc7d80-f1ab-11e8-85d3-aa0bb057bd66.jpeg)

## Code To Reproduce Issue [ Good To Have ]

```
    @AndroidFindBy(xpath = "(//android.widget.LinearLayout[@resource-id='android:id/pickers']//android.widget.EditText)[3]")
    private AndroidElement txtYear;

    public AndroidElement getTxtYear() {
        return txtYear;
    }

getTxtYear.clear();
getTxtYear.sendKeys("1998");
```

**Comment by mykola-mokhnach** [comment]
UIA2 framework does not provide methods to change date picker values. You should either try to change the value by swiping the control like a user would do or switch to Espresso driver.
