### ISSUE TITLE
Session is not started.  Code=4 "Failed to load Info.plist from bundle at path"

### ISSUE THREAD

**Issue by Artem-Kushch** [appium/appium#11741]
## The problem

Session is not started. Application is installing, openning and then nothing happens. Please, help me.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0-beta.6
* Desktop OS/version used to run Appium: MacOS Mojave 10.14.1
* Node.js version (unless using Appium.app|exe): 10.13.0
* Mobile platform/version under test: IOS 12.0
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI
* Xcode: 10.0

## Details
Maybe the problem in this errors.
`04:39:06.318 xcodebuild[84305:2273659] Test operation failure: Failed to load Info.plist from bundle at path /Users/jenkins/Library/Developer/CoreSimulator/Devices/6FA59349-4D07-4BD2-945D-4916897CEB45/data/Library/Caches/com.apple.mobile.installd.staging/temp.1uw6NP/extracted/Payload/WebDriverAgentRunner-Runner.app
04:39:06.318 xcodebuild[84305:2273659] _finishWithError:Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Failed to load Info.plist from bundle at path /Users/jenkins/Library/Developer/CoreSimulator/Devices/6FA59349-4D07-4BD2-945D-4916897CEB45/data/Library/Caches/com.apple.mobile.installd.staging/temp.1uw6NP/extracted/Payload/WebDriverAgentRunner-Runner.app" UserInfo={NSLocalizedDescription=Failed to load Info.plist from bundle at path /Users/jenkins/Library/Developer/CoreSimulator/Devices/6FA59349-4D07-4BD2-945D-4916897CEB45/data/Library/Caches/com.apple.mobile.installd.staging/temp.1uw6NP/extracted/Payload/WebDriverAgentRunner-Runner.app}`

`[Xcode] 2018-11-27 04:40:28.267671+0200 WebDriverAgentRunner-Runner[84340:2274235] Enqueue Failure: Application 'com.app.App.Enterprise' does not have a process ID /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
`

## Link to Appium logs

appium log - https://gist.github.com/Artem-Kushch/b077154cb839a4cd9b8d0a9cddc88311
WebDriverAgentRunner-log - https://gist.github.com/Artem-Kushch/ffb5c5a07dd69c8aba23f42c9703b176

## Capabilities:
`              automationName: "XCUITest",
                platformName: "iOS",
                showIosLog: true,
                showXcodeLog: true,
                platformVersion: "12.0",
                deviceName: "iPhone 6",
                useNewWDA: true,
                sessionOverride: true,
                connectHardwareKeyboard: false,
                shouldUseSingletonTestManager: false,
                waitForQuiescence: false,
                newCommandTimeout: 950,
                webkitResponseTimeout: 15000,
                launchTimeout: 60000
                iosInstallPause: 8000,
                wdaStartupRetryInterval: 60000,
                wdaLaunchTimeout: 180000, 
                wdaConnectionTimeout: 720000,
                app: /path/to/App.app
`

**Comment by mykola-mokhnach** [comment]
This might be a problem with the application itself. Did you try to execute any sample application, like a Calculator one?

**Comment by Artem-Kushch** [comment]
@mykola-mokhnach 
I try to test more with your fix and start session with "New session window..." from Appium Desktop

**Environment:** 
MacOS; 
Processor: 2.6 GHz Intel Core i5; 
Memory: 16 GB 1600 MHz DDR3;
Graphics: Intel Iris 1536 MB;
Disk: HDD;

**Capabilities:** 
`{
  "platformName": "iOS",
  "platformVersion": "12.0",
  "deviceName": "iPhone 6",
  "automationName": "XCUITest",
  "app": "/path/to/app/App.app",
  "showIosLog": true,
  "showXcodeLog": true,
  "useNewWDA": true
}`

Before test, I am started docker what use 1 CPU and 7 Memory.
And when I start session I have a problem, session starts long time.

appium full log - https://gist.github.com/Artem-Kushch/542deed1fd9921b1ab05936ff4e6f2b4
Session WebDriverAgentRunner full log https://gist.github.com/Artem-Kushch/5f1a8d8ff47a0423e994532de3477340

Appium freeze on this steps:
`[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.App.App.Enterprise","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[Xcode]     t =     0.36s Open com.App.App.Enterprise
[Xcode] 
[Xcode]     t =     0.37s     Launch com.App.App.Enterprise
[Xcode] 
[Xcode]     t =     0.59s         Wait for accessibility to load
[Xcode] 
[Xcode]     t =     1.20s         Wait for com.App.App.Enterprise to idle
[Xcode] 
[Xcode]     t =    61.22s             App event loop idle notification not received, will attempt to continue.
[Xcode] 
[Xcode]     t =    61.22s             App animations complete notification not received, will attempt to continue.
[Xcode] 
[Xcode] 2018-12-02 20:37:13.931527+0200 WebDriverAgentRunner-Runner[62613:12889876] Enqueue Failure: Failure fetching attributes for Device system-wide element: Error Domain=com.apple.XCTestErrorDomain Code=1000 "Timeout waiting for fulfillment of promise for 'Fetching attributes for Device system-wide element'." UserInfo={NSLocalizedDescription=Timeout waiting for fulfillment of promise for 'Fetching attributes for Device system-wide element'.} /Users/jenkins/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode] 
[Xcode] 2018-12-02 20:37:13.932397+0200 WebDriverAgentRunner-Runner[62613:12889876] Enqueue Failure: Failure to determine system application: (null) /Users/jenkins/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode] 
[Xcode] 2018-12-02 20:38:18.937717+0200 WebDriverAgentRunner-Runner[62613:12889876] Enqueue Failure: Failure fetching attributes for (null): Error Domain=com.apple.XCTestErrorDomain Code=1000 "Timeout waiting for fulfillment of promise for 'Fetching attributes for (null)'." UserInfo={NSLocalizedDescription=Timeout waiting for fulfillment of promise for 'Fetching attributes for (null)'.} /Users/jenkins/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode] 
[Xcode] 2018-12-02 20:38:18.939318+0200 WebDriverAgentRunner-Runner[62613:12889876] Enqueue Failure: Failure getting list of active applications: (null) /Users/jenkins/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode] 
[Xcode] 2018-12-02 20:39:24.053261+0200 WebDriverAgentRunner-Runner[62613:12889876] Enqueue Failure: Failure fetching attributes for Device system-wide element: Error Domain=com.apple.XCTestErrorDomain Code=1000 "Timeout waiting for fulfillment of promise for 'Fetching attributes for Device system-wide element'." UserInfo={NSLocalizedDescription=Timeout waiting for fulfillment of promise for 'Fetching attributes for Device system-wide element'.} /Users/jenkins/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode] 
[Xcode] 2018-12-02 20:39:24.054483+0200 WebDriverAgentRunner-Runner[62613:12889876] Enqueue Failure: Failure to determine system application: (null) /Users/jenkins/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode] 
[Xcode] 2018-12-02 20:40:29.064186+0200 WebDriverAgentRunner-Runner[62613:12889876] Enqueue Failure: Failure fetching attributes for (null): Error Domain=com.apple.XCTestErrorDomain Code=1000 "Timeout waiting for fulfillment of promise for 'Fetching attributes for (null)'." UserInfo={NSLocalizedDescription=Timeout waiting for fulfillment of promise for 'Fetching attributes for (null)'.} /Users/jenkins/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode] 
[Xcode] 2018-12-02 20:40:29.065065+0200 WebDriverAgentRunner-Runner[62613:12889876] Enqueue Failure: Failure getting list of active applications: (null) /Users/jenkins/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode] 
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"sessionId":"3D6A8054-9EC8-4C60-9AA4-0FDABC87210C","capabilities":{"device":"iphone","browserName":null,"sdkVersion":"12.0","CFBundleIdentifier":null}},"sessionId":"3D6A8054-9EC8-4C60-9AA4-0FDABC87210C","status":0}
[debug] [BaseDriver] Event 'wdaSessionStarted' logged at 1543776029073 (20:40:29 GMT+0200 (Eastern European Standard Time))
[debug] [BaseDriver] Event 'wdaStarted' logged at 1543776029074 (20:40:29 GMT+0200 (Eastern European Standard Time))
[XCUITest] Skipping setting of the initial display orientation. Set the "orientation" capability to either "LANDSCAPE" or "PORTRAIT", if this is an undesired behavior.
[debug] [BaseDriver] Event 'orientationSet' logged at 1543776029078 (20:40:29 GMT+0200 (Eastern European Standard Time))
[Appium] New XCUITestDriver session created successfully, session ee5759f1-4f14-44e8-bde3-24654361d70f added to master session list
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1543776029080 (20:40:29 GMT+0200 (Eastern European Standard Time))
[debug] [MJSONWP (ee5759f1)] Cached the protocol value 'MJSONWP' for the new session ee5759f1-4f14-44e8-bde3-24654361d70f
[debug] [MJSONWP (ee5759f1)] Responding to client with driver.createSession() result: {"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"app":"/Users/jenkins/workspace/App-test/mobile-tests/build-ios-social-qa/build/Local-iphonesimulator/App-LOC.app","automationName":"XCUITest","deviceName":"iPhone 6","platformName":"iOS","platformVersion":"12.0","showIosLog":true,"showXcodeLog":true,"useNewWDA":true,"newCommandTimeout":0,"connectHardwareKeyboard":true,"udid":"555526A4-775D-4CEE-8E78-136E62F036FC"}
[HTTP] <-- POST /wd/hub/session 200 385964 ms - 642
[HTTP] 
[Xcode]     t =   324.14s Unable to monitor animations
[Xcode]     t =   324.14s Unable to monitor event loop`

If I use sessionOverride, the second start of the new session will be fast.
If I stop docker, session will be start normal every time and it fix my problem.
The problem is the performance of my Mac?

**Comment by mykola-mokhnach** [comment]
Closed as third party issue. Feel free to push a PR if you have a solution to it.

**Comment by Artem-Kushch** [comment]
@mykola-mokhnach FYI
On this mac, we remove docker and upgrade hdd to ssd and this problem disappears.
