### ISSUE TITLE
Mac access alert message request during test run

### ISSUE THREAD

**Issue by BoazWarshawsky** [appium/appium#11743]
## The problem
I am getting a Macintosh popup message during test run which causing my test to fail.
My tested application is mainly testing playing of video data. Every time that my tests opening some video item to play its showing this message:
<img width="430" alt="screen shot 2018-11-27 at 7 29 25" src="https://user-images.githubusercontent.com/32813176/49060793-aae36900-f217-11e8-9007-2b37c9fab6f7.png">

When I start playing my video this message popup and not allowing me to continue the test unless I am approving the message.

I need some automatic solution since my test is running in CI and I cannot manually disable this message in the Simulator UI menu.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable): Never
* Desktop OS/version used to run Appium: using CLI appium
* Node.js version (unless using Appium.app|exe): v8.12.0
* Mobile platform/version under test: iOS 12.1
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs
No need

## Code To Reproduce Issue [ Good To Have ]
Play some video in test app

**Comment by mykola-mokhnach** [comment]
Closed as inactive

**Comment by BoazWarshawsky** [comment]
Hi @mykola-mokhnach , why did we close the ticket? I still having the problem.

Any advice here?

Thanks
