### ISSUE TITLE
Unable to use mobile commands for Android devices (e.g.: mobile:batteryInfo)

### ISSUE THREAD

**Issue by ochubey** [appium/appium#11744]
## The problem

When trying to use most of described in documentation commands tests fail with following error: "org.openqa.selenium.UnsupportedCommandException: Unknown mobile command "batteryInfo". Only shell,startLogsBroadcast,stopLogsBroadcast commands are supported."
http://appium.io/docs/en/commands/mobile-command/

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Mac OS Mojave
* Node.js version (unless using Appium.app|exe): v8.7.0
* Mobile platform/version under test: Android, Nexus 6P, 6.0.1
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: CLI

## Details

N/A

## Link to Appium logs
Appium server logs: https://gist.github.com/ochubey/122199a3d4dc3a573f3c5f2936e1142e

## Code To Reproduce Issue [ Good To Have ]
Java code to reproduce (simplified): https://gist.github.com/ochubey/316ef4490bdd46239835fd2837910852

**Comment by dpgraham** [comment]
Some of these features are brand new and are in version 1.10 which was just released an hour ago... can you try upgrading and let me know if you have any success?

**Comment by mykola-mokhnach** [comment]
This endpoint only works for UIAutomator2. Closed as not an issue

**Comment by dpgraham** [comment]
@ochubey try setting `automationName=UIAutomator2`

**Comment by ochubey** [comment]
> This endpoint only works for UIAutomator2. Closed as not an issue

Thank you @mykola-mokhnach. Although there is, then, issue in documentation. `mobile:batteryInfo` not listed under "Android (UiAutomator2 only)" section.

**Comment by dpgraham** [comment]
Thanks @ochubey 

I just put in a PR to address that: https://github.com/appium/appium/pull/11747

**Comment by ochubey** [comment]
@dpgraham - thanks, I'll close my own (did not completed it yersterday).
