### ISSUE TITLE
Appium release process

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#11746]
Yes, yet another one of my Appium screeds....

I was thinking about the way we do releases, and had some ideas on how we can get releases out in a more frequent, safer way.

This my recommended approach:
* Do scheduled minor releases (maybe once a month)
* Have a release candidate testing period prior to the release (maybe 2 weeks before?) 
* Start the testing period by creating the release branch (1.10, 1.11, etc...) and shrinkwrap the production dependencies. Keep the `npm-shrinkwrap.json` committed to that branch.
* Put in the PR for the CHANGELOG.md for this release.
* From the release branch, publish a release candidate to npm (something like `npm publish --tag rc` where the version is something like `1.2.3-rc0`) and announce it on Slack so that Appium users and cloud providers can start testing
* Any new features that come after the rc release will have to wait for the _next_ minor release (unless there's a really compelling reason why we can't wait)
* Patch bugfixes into the release branch. 
* If a bugfix is in a dependency (which most will be), just run `npm install <some-dependency>@<bugfix-version>` from the release branch; commit and push the updated `package.json` + `npm-shrinkwrap.json`; increment and publish a new release candidate
* After the testing period is over, and we're satisfied with the latest release candidate, graduate that release candidate to production by publishing a minor version to NPM (e.g.: 1.10.0, 1.11.0, ...)
* Any subsequent bugfixes that can't wait for the next minor version can be patched into the release branch and we can publish a patch package (e.g.: 1.10.1, 1.11.2, ...)

Reasons:
* Changing the dependencies at the last minute is risky (sometimes it _literally_ is the last minute)
* Having a testing period gives cloud providers and Appium early adopters adequate time to review the CHANGELOG and test out the upcoming version without any last minute surprises
* Releases won't be delayed because of last minute features/pull-requests. If a feature isn't published in time for one release, it will have to wait to be included in the next release. But the time between releases should be a lot shorter than it is now, so we'll actually get features out to users quicker than we did before
* Bugfixes can be published much quicker.
* More predictable release cycle

Other notes:
* We can still do betas. We can have a `beta` channel which publishes what's on master and has no shrinkwrap. The `rc` channel will publish from release branches with shrinkwrap.

Prior Art:
* https://docs.gitlab.com/ee/workflow/gitlab_flow.html
* [VSCode](https://github.com/Microsoft/vscode/releases)

(cc: @vrunoa @mykola-mokhnach @imurchie @jlipps)

**Comment by mykola-mokhnach** [comment]
Some ideas of mine:
- having rc candidates is fine if beta is not shrinkwrapped. Otherwise non-shrinkwrapped alpha and shrinkwrapped beta would do just fine
- patch bugfixes into the release branch. Can we afford such luxury? This will require even more human resources

Otherwise I second everything

**Comment by dpgraham** [comment]
"having rc candidates is fine if beta is not shrinkwrapped. Otherwise non-shrinkwrapped alpha and shrinkwrapped beta would do just fine"

Yeah, my thought was just to have two channels. One for shrinkwrapped release candidates and one for non-shrinkwrapped, built from master. I'm fine with either naming scheme.

"patch bugfixes into the release branch. Can we afford such luxury? This will require even more human resources"

We don't have to do it for every single bugfix. Only the bugfixes that are urgent and can't wait for the next minor release. And we don't need to be too strict about only allowing fixes. If upgrading a dependency brings in a bugfix but also brings in a feature, it's not a huge problem.

**Comment by imurchie** [comment]
So, at any given time we would have three versions?
1. Full release, installed with `npm install -g appium`
1. Beta release, with un-shrinkwrapped deps, installed with `npm install -g appium@beta`
1. Release candidates, with shrinkwrapped deps, installed with `npm install -g appium@rc`

I think this is worth a try, at any rate. We've tried to have a higher release cadence in the past without a structured process, to no avail. This might be the process we need!

I don't think the overhead would be onerous. And if we have a fully scheduled release cycle it would give some measure of stability to users, which would be good. This hemming and hawing, and eventually releasing, is a drag.

**Comment by dpgraham** [comment]
@imurchie that's correct... one beta channel for unshrinkwrapped, bleeding edge; one rc channel for shrinkwrapped.

I think we have some consensus here. I can take the lead on this for a December release, and we'll see how we like it. If we stick with this approach I can update the documentation, and then add Slack reminders to do the scheduled releases.
