### ISSUE TITLE
Application is getting crashed post launching via appium for devices with iOS version 12.0.1

### ISSUE THREAD

**Issue by iamsiddharath** [appium/appium#11755]
## The problem

Application is getting crashed post launching via appium for devices with iOS version 12.0.1

## Environment

* Appium version :  Appium v1.9.1
* Desktop OS/version used to run Appium: MacOS Mojave- 10.14 Appium desktop Version 1.8.2 (1.8.2.20181101.4)
* Mobile platform/version under test:iOS 12.0.1
* Real device or emulator/simulator:Real device - iPhone 6

## Details

The application is getting crashed while launching the same using Appium(1.9.1v).
Xcode version used : 10.1
The crash is observed when the Appium tries to 'getPageSource'

## Link to Appium logs

https://gist.github.com/iamsiddharath/567e48d6940dc50e7bcb050ea2c784c0

**Comment by mykola-mokhnach** [comment]
Try appium 1.10. If it does not help then there is nothing else that can be done on appium side. Try to report the issue to https://github.com/facebook/WebDriverAgent or to Apple.
