### ISSUE TITLE
Cann't snapshot toast element [android]

### ISSUE THREAD

**Issue by 141801** [appium/appium#11756]
環境　appium 1.9.1
           ruby 2.5.1p57
           engine: uiautomator2

line1:  el=@driver.find_elements(:xpath,'//*[@text="全てのダウンロードが完了しました。"]')[0]
line2:  @driver.save_element_screenshot(el,@tar_pic_dir+'toast_message.png')
         
line1  no problem but  line2  error occurs

----------log as follows-----------

![2018-10-25 18 36 47](https://user-images.githubusercontent.com/42635299/49144388-9e0e6480-f340-11e8-8d53-646162468dce.png)

**Comment by mykola-mokhnach** [comment]
This is expected, because toast element is not a "real" element in the page source. you can only take full screen shot, but not a screenshot of that particular element.

**Comment by 141801** [comment]
thanks very much !
