### ISSUE TITLE
XCUITest: pressKeyCode not implemented

### ISSUE THREAD

**Issue by dklompmaker** [appium/appium#11767]
## The problem

pressKeyCode not implemented in XCUITest driver. I need the capability to send key code events to native ios.

[XCUITest] Executing command 'pressKeyCode'
[W3C] Encountered internal error running command: NotYetImplementedError: Method has not yet been implemented

## Environment

* Version 1.8.2 (1.8.2.20181101.4)
* Desktop Mac App
* iOS Simulator

**Comment by KazuCocoa** [comment]
XCUITest does not have the command since they send keycode implemented in Android OS.
http://appium.io/docs/en/commands/device/keys/press-keycode/

What do you mean _keycode_ in iOS?

**Comment by dklompmaker** [comment]
@KazuCocoa For our Android tests, we can simulate key presses which get sent to the IME soft keyboard. This allows us to mock the entire user input into our fields. On iOS we don't have the luxury because it appears that this method is not implemented in the driver.

For more context, we are build game via Unity game engine. Utilizing the [x,y] coords, we can select the input fields to pop-open the IME keyboard. Then using press_keycode, we can send a key event to the simulator or device. This works on android simulator and real device.

We'd like to do the same with iOS.

**Comment by KazuCocoa** [comment]
> because it appears that this method is not implemented in the driver.

Yes, since Apple does not provide such API for XCUITest framework.

Ah, Unity.
What about getting active element using http://appium.io/docs/en/commands/element/other/active/ and send_keys?
You can probably call _setImmediateValue_ like https://github.com/search?l=Markdown&q=org%3Aappium+set+Immediate+Value&type=Code as well.

Or what about W3C actions http://appium.io/docs/en/commands/interactions/actions/ ?
You can tap particular coordinates like: 
```ruby
       @driver.action
          .move_to_location(x_val, y_val)
          .pointer_down(:left)
          .pointer_up(:left)
          .perform
```

**Comment by dklompmaker** [comment]
@KazuCocoa Thanks for the ideas.

Unfortunately, doing `driver.switch_to.active_element` yields:
```
NoSuchElementException: Message: {u'using': u'', u'description': u'unable to find an element', u'value': u''}
```
And the W3C actions would have the same effect as there is not 'element' per-say; Unity is rendering natively. Can you think of any other way to send native keyboard events? I suppose I could always write a native ios plugin to communicate to; I'd prefer not to :)

**Comment by KazuCocoa** [comment]
Thanks, I see.

Probably, no, unfortunately...

If iOS keyboard apepars, you can tap the keyboard directly using find_element/s and click.
e.g.: `find_element :accessibiliy_id, 'Done'` can find _Done_ key.

I found https://github.com/appium/python-client/issues/192#issuecomment-349593765 but the situation is not same for you.

I think you have already searched in https://discuss.appium.io/search?q=unity , but I'd link here.

**Comment by mykola-mokhnach** [comment]
Unfortunately XCTest does not allow to generate keyboard events. Please report an issue to Apple.
