### ISSUE TITLE
Docs for mobile: for espresso driver

### ISSUE THREAD

**Issue by saikrishna321** [appium/appium#11764]
Address https://github.com/appium/appium-espresso-driver/pull/324

Mobile commands: setDate, setTime, navigateTo, scrollToPage, openDrawer, closeDrawer

**Comment by KazuCocoa** [comment]
oh.. sorry I noticed this after creating https://github.com/appium/appium/pull/11784

**Comment by saikrishna321** [comment]
@KazuCocoa No worries. Thanks for the PR. I was testing the mobile: and found ViewPager does not work.
