### ISSUE TITLE
App is launch and exit automatically and "/wd/hub/session" throws 500 Error

### ISSUE THREAD

**Issue by DarshanLoga** [appium/appium#11761]
## The problem

App is launching and close the app automatically and in the appium log "/wd/hub/session" throws 500 Error.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): 1.6.5
* Desktop OS/version used to run Appium: MAC OS
* Node.js version (unless using Appium.app|exe): 
* Mobile platform/version under test: Android 8
* Real device or emulator/simulator: Moto X4
* Appium CLI or Appium.app|exe:

## Link to Appium logs

https://gist.github.com/DarshanLoga/cd9e07e86e455a308ba9e291eaae61ab

## Code To Reproduce Issue [ Good To Have ]
**Capabilities** 

final String URL_STRING = "http://127.0.0.1:4723/wd/hub";
        URL url = new URL( URL_STRING );
        //Use a empty DesiredCapabilities object
        DesiredCapabilities capabilities = new DesiredCapabilities();
        File appdir = new File( "/Users/apple/Documents/AndroidiOSBuilds/ProductionFlexbookApp/1.0.6PA/" );
        File app = new File( appdir, "android-debug.apk" );
        capabilities.setCapability( CapabilityType.BROWSER_NAME, "" );
        capabilities.setCapability( "noReset", true );
        capabilities.setCapability( MobileCapabilityType.NEW_COMMAND_TIMEOUT, 1000 );
        capabilities.setCapability( MobileCapabilityType.APP, app.getAbsolutePath() );
        capabilities.setCapability( "autoLaunch", Boolean.parseBoolean( "autolaunch" ) );
        capabilities.setCapability( "autoLaunch", Boolean.parseBoolean( String.valueOf( true ) ) );
        capabilities.setCapability( MobileCapabilityType.APP_ACTIVITY, "org.ck12.reader.MainActivity" );
        capabilities.setCapability( MobileCapabilityType.APP_PACKAGE, "org.ck12.reader" );
        capabilities.setCapability( MobileCapabilityType.PLATFORM_NAME, MobilePlatform.ANDROID );
        capabilities.setCapability("recreateChromeDriverSessions", true );
        capabilities.setCapability("autoWebview","true");
        //capabilities.setCapability ("Webview.setWebContentsDebuggingEnabled", "true");
        capabilities.setCapability ( MobileCapabilityType.DEVICE_NAME, "ZY224QJNRJ"); // 0a9d425a0bfc6fac"  TA38500ME6
        capabilities.setCapability ( "chromedriverExecutable", "/Users/apple/Desktop/ChromeDriver/44/chromedriver" );
        driver = new AndroidDriver<MobileElement>( new URL( "http://127.0.0.1:4723/wd/hub" ), capabilities );
        driver.manage().timeouts().implicitlyWait( 40, TimeUnit.SECONDS );
        try {
            Thread.sleep(15000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }

Please have a look and give me a solution to fix this issue.

Thanks in advance.

**Comment by mykola-mokhnach** [comment]
I don't observe any errors in the attached log. Error 500 means you are trying to access a session, which does not exist.

Also Appium 1.7.1 is out of date. Please upgrade it to the most recent version and switch to UIA2 for Android 6+
