### ISSUE TITLE
Appium - screenshotWaitTimeout  capability not recognized. 

### ISSUE THREAD

**Issue by AvrahamAtia** [appium/appium#11763]
## The problem

[Appium] Creating new AndroidDriver (v4.1.1) session
[Appium] Capabilities:
[Appium]   app: /Users/aviatia/Downloads/Staging5.18.apk
[Appium]   screenshotWaitTimeout: 10
[Appium]   commandTimeout: 60
[Appium]   platformVersion: 8.1
[Appium]   platformName: Android
[Appium]   deviceName: Nexus_5X_API_27
[debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {"app":"/Users/aviatia/Down...
**[BaseDriver] The following capabilities were provided, but are not recognized by appium: screenshotWaitTimeout**

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Node.js version (unless using Appium.app|exe): v10.4.
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: appium

**Comment by mykola-mokhnach** [comment]
This is expected. The capability only works in ios (and probably windows)

**Comment by AvrahamAtia** [comment]
@mykola-mokhnach  Ok, thank you.
