### ISSUE TITLE
Open iOS App in English environment with Appium 1.9.1，but it shows the default Chinese.

### ISSUE THREAD

**Issue by AlanFightting** [appium/appium#11779]
## The problem

Our app supports multiple languages, but I test app in English environment with Appium, Actually it shows Chinese in app.

## Environment

Appium v1.9.1
iOS 12.1

**Comment by mykola-mokhnach** [comment]
Please properly fill out the issue reporting form.

**Comment by AlanFightting** [comment]
> Please properly fill out the issue reporting form.

I added a “language”parameter in desired_caps 
{
	"platformName" : "iOS",
    "platformVersion" : "12.1",
	"deviceName" : "iPhone",
	"bundleId" : "test",
    "udid" : "00008adadada0232002E",
	"language" : "Chinese"

}

if open iOS App in English environment，it will show Chinese

**Comment by AlanFightting** [comment]
> Could you attach logs you could get via Appium server?
> We would like to track what happened in your environment.
> 
> If you used a simulator, the language was probably affected the system language. Could you open the app in English after changing the system language to Chinese and re-install the app?

Yes, I try to install app in Chinese. After setting the "language" parameter to English, it opens to show in English. Setting other things, such as Japanese and French, is the same.

**Comment by AlanFightting** [comment]
"Language to set for iOS and Android. It is only available for simulator on iOS"
I see this in the documentation, but am I doing the same on a real device?

**Comment by AlanFightting** [comment]
> > [Appium] Creating new XCUITestDriver (v2.94.2) session
> > [Appium] Capabilities:
> > [Appium] platformName: iOS
> > [Appium] udid: 38b1b888634bec8ca067adfb8b010d045670224
> > [Appium] bundleId: "com.make"
> > [Appium] deviceName: Makeblock123
> > [Appium] platformVersion: 11.4
> > [Appium] language: English
> > [debug] [BaseDriver] W3C capabi
> 
> Your capability had ` language: English`. Below sent to Appium server and your app probably launch in English.
> 
> > [debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.makerworks.makeblock","arguments":["-AppleLanguages","(English)","-NSLanguages","(English)"],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
> > [debug] [JSONWP Proxy] Got response with status 200: {"value":{"sessionId":"7E89C43A-9141-42DA-8E2C-F5072C97B06C","capabilities":
> 
> What about swithing current language capability with `"language": "en"` following https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md and https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/LanguageandLocaleIDs/LanguageandLocaleIDs.html ?
> (The `language` in caps document, we show 2 charactors example like `fr`.

"Language to set for iOS and Android. It is only available for simulator on iOS"
I see this in the documentation, but am I doing the same on a real device?

**Comment by KazuCocoa** [comment]
ah, you're using a real device, sorry I missed it in the log because of my question and your reply, yes.

We do not provide language preference for read devices in iOS.
The launching argument was following  https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/TestingYourInternationalApp/TestingYourInternationalApp.html


If the launching argument works in real device x Xcode 9+, we probably can do it thouth it.(I have not investigated it though)

**Comment by KazuCocoa** [comment]
You can set the prosess arguments like below in your capability. If `AppleLanguages` and `AppleLocale` work on real device, it probably helps your case.

```
    automationName: 'XCUITest',
    ...
    processArguments: {
      env: {
        "PROCESS_VALUE": "process value"
      }
    }
```

**Comment by AlanFightting** [comment]
> You can set the prosess arguments like below in your capability. If `AppleLanguages` and `AppleLocale` work on real device, it probably helps your case.
> 
> ```
>     automationName: 'XCUITest',
>     ...
>     processArguments: {
>       env: {
>         "PROCESS_VALUE": "process value"
>       }
>

**Comment by AlanFightting** [comment]
> You can set the prosess arguments like below in your capability. If `AppleLanguages` and `AppleLocale` work on real device, it probably helps your case.
> 
> ```
>     automationName: 'XCUITest',
>     ...
>     processArguments: {
>       env: {
>         "PROCESS_VALUE": "process value"
>       }
> ```

I'll try it. Thank you.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
