### ISSUE TITLE
android: is there a possibility to change intent during the test execution?

### ISSUE THREAD

**Issue by DudaGod** [appium/appium#11776]
## The problem

Hello, I write tests on javascript using webdriverio. And before running my tests I launch app with some intent. In some of my tests I must change default intent, which is set in desiredCapabilities. Is there a possibility to change it during the test execution (some method)?

If it is not implemented yet, can you please direct me where to look some related code?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Desktop OS/version used to run Appium: Mac OS
* Node.js version (unless using Appium.app|exe): 8.6.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: CLI

**Comment by mykola-mokhnach** [comment]
https://appiumpro.com/editions/23

**Comment by DudaGod** [comment]
Thank you, I read about `startActivity` but I need to pass some intent arguments too. In `desiredCapabilities` I use `optionalIntentArguments` for this. But `startActivity` takes only: `appPackage`, `appActivity`, `appWaitPackage`, `appWaitActivity`

**Comment by KazuCocoa** [comment]
Does http://appium.io/docs/en/writing-running-appium/caps/ help you?
e.g.: `optionalIntentArguments`

**Comment by DudaGod** [comment]
> Does http://appium.io/docs/en/writing-running-appium/caps/ help you?

No, I have already read about it and use `optionalIntentArguments` in my config. But I can't found a method on which I can pass my intents (`intentAction` and `optionalIntentArguments`) during test execution.

**Comment by mykola-mokhnach** [comment]
You can pass it directly via shell command: https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/android-shell.md

**Comment by mykola-mokhnach** [comment]
Or create a backdoor in your app and use deep linking

**Comment by KazuCocoa** [comment]
ah, I see.

What about http://appium.io/docs/en/commands/mobile-command/ 's `mobile:shell`?
https://appiumpro.com/editions/3

You can use it if you can set `--relaxed-security` for appium server.

(oh, mykola just mentioned during I was writing it)

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/java-client/blob/1991a8a0f9e4a3ff467dbb713cb5c51c8edc060f/src/test/java/io/appium/java_client/android/IntentTest.java#L59

**Comment by DudaGod** [comment]
Thank you guys. You helped me a lot.
