### ISSUE TITLE
Android - Cannot identify URLSpan

### ISSUE THREAD

**Issue by cosminstirbu** [appium/appium#11775]
## The problem

We are trying to interact (tap) on URLSpan (links) in our Android application but it seems they are not identified by Appium.

It can easily be reproduced using https://github.com/appium/android-apidemos, navigating to Text -> Linkify and then retrieving App Source via Appium Desktop.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Desktop OS/version used to run Appium: macOS 10.14
* Node.js version (unless using Appium.app|exe): Appium.app
* Mobile platform/version under test: Android
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: Appium.app

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/cosminstirbu/c05334a5a9533d0d606ba9fb3a84ffd5

**Comment by mykola-mokhnach** [comment]
You can only see what the application under test provides to Accessibility. This has nothing to do with Appium at all. 

Try to use Espresso driver as a workaround if it is impossible to fix the app

**Comment by cosminstirbu** [comment]
I did try using Espresso but I get a `java.lang.SecurityException` as per https://gist.github.com/cosminstirbu/60c2fd25ca447e471ef7ab48a6d706c9.

It's interesting that UIAutomator2 doesn't expose them since Google is recommending using URLSpan in their accessibility guidelines: https://support.google.com/accessibility/android/answer/6378148?hl=en

**Comment by mykola-mokhnach** [comment]
> I did try using Espresso but I get a java.lang.SecurityException as per  https://gist.github.com/cosminstirbu/60c2fd25ca447e471ef7ab48a6d706c9.

Quite a lot of fixes has been done there since 1.9.1 Try appium@beta instead

**Comment by cosminstirbu** [comment]
Unfortunately Espresso doesn't expose the URLSpan(s) either :(

https://gist.github.com/cosminstirbu/8f9e3b8c542b49e93626e31b9148cf58

**Comment by mykola-mokhnach** [comment]
Then there is nothing more we can do there. Consider fixing/changing the application under test
