### ISSUE TITLE
MAC terminal running appium for a long time causes disk space to become smaller.

### ISSUE THREAD

**Issue by ZhouShuaiQuan** [appium/appium#11778]
## The problem

The MAC terminal runs appium to do the loop test. After a while, the MAC prompts me that the disk space is insufficient. Until I finish the appium running on the terminal, my 50 G space is released.I don't want to interrupt my task.

## Environment

* Appium 1.8.1
* MAC
* IOS 11
* iPhone5s，6s

## Details
![1543912577965](https://user-images.githubusercontent.com/33561100/49429142-bf5cce00-f7e2-11e8-9da4-fa127d1ae9bc.jpg)

**Comment by mykola-mokhnach** [comment]
- Try the most recent appium version
- Please provide more detailed information on what exactly is using the disk space (file/folder names, when do they appear, how big are they, etc)

**Comment by ZhouShuaiQuan** [comment]
Thanks for your reply, I will try the new version, but I still want to know the reason for the problem.
The terminal file of mac is hidden. I can't find it. It has a size of 17.5G, but it will increase slowly. There will be 100G in a week. Until I shut down the appium of the terminal. I started appium using "node /Applications/Appium.app/Contents/Resources/app/node_modules/appium/build/lib/main.js -p 4727 --webdriveragent-port 8104 --log-level error".

**Comment by mykola-mokhnach** [comment]
> Thanks for your reply, I will try the new version, but I still want to know the reason for the problem.

We also would like to know and thus requested more info. Appium has a huge codebase and creates tons of temporary files. It is impossible to figure out what is deleted and what is not without the actual information about the created items .

> The terminal file of mac is hidden.

Sorry, I cannot understand this.

**Comment by ZhouShuaiQuan** [comment]
Ok, maybe some settings have gone wrong, thank you.

**Comment by Artem-Kushch** [comment]
@ZhouShuaiQuan read this - https://ianlunn.co.uk/articles/quickly-showhide-hidden-files-mac-os-x-mavericks/
The Quickest Way to Show/Hide Hidden Files: `CMD + SHIFT + .`
