### ISSUE TITLE
Android Bootstrap Socket Crashed Getting Window Size or Closing Driver while Running in Parallel

### ISSUE THREAD

**Issue by InvisibleExo** [appium/appium#11773]
## The problem

I get Android Bootstrap Socket Error when I attempt to declare Dimensions for my mobile device or close the driver, I get this error: `Encountered internal error running command: Error: Android bootstrap socket crashed: Error: This socket has been ended by the other party [MJSONWP] at Socket.<anonymous>`

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10  build: 17134
* Node.js version (unless using Appium.app|exe): v1.8.1
* Mobile platform/version under test: Android 5 and Android 6
* Real device or emulator/simulator: Emulators
* Appium CLI or Appium.app|exe: CLI

## Details

The issue only affects one of the devices if I have 2 or more running in parallel and attempt to call getWindowSize() around the same time.

## Link to Appium logs

GIST logs of Dimensions Socket Error [Here!](https://gist.github.com/InvisibleExo/b363d7090a966d95ca6d829e0f1c1ee3)
GIST logs of driver.quit() Socket Error [Here!](https://gist.github.com/InvisibleExo/6c2697f78f6ec325f948888e7a716611)

## Code To Reproduce Issue [ Good To Have ]
Note: I use Maven to call for my appium dependencies.

(Setup for drivers before test) 

`@BeforeClass(alwaysRun=true)
	@Parameters({"platform", "udid", "deviceName", "URL", "port"})
	public void driverSetUp(String platform, String udid, String deviceName, 
			String URL ,String port) throws MalformedURLException {
		System.out.println("before test");
		driver = driverSetup.driverPreTestSetUp(platform, udid, deviceName, URL, port);
		System.out.println("Testing driver: " + driver.getCapabilities().getCapability("deviceName"));
		TLDriverFactory.setTLDriver(driver);
		wait = new WebDriverWait(TLDriverFactory.getTLDriver(), 15);
	}`

(Method where Dimensions is initialized during test)
`  
      public  void  swipeVertical  (double startPercentage, double finalPercentage, int duration) {
		driver.context("NATIVE_APP");
		Dimension size = driver.manage().window().getSize();
		int width = (int) (size.width/2);
		int startPoint = (int) (size.getHeight() * startPercentage);
		int endPoint = (int) (size.getHeight() * finalPercentage);
		new TouchAction(driver)
			.press(PointOption.point(width, startPoint))
			.waitAction(WaitOptions.waitOptions(Duration.ofMillis(duration)))
			.moveTo(PointOption.point(width, endPoint))
			.release()
			.perform();
		driver.context(defaultContext);
	} `

**Comment by saikrishna321** [comment]
@InvisibleExo Please set _automationName_ as UIAutomator2

**Comment by InvisibleExo** [comment]
@saikrishna321 after adding UIAutomator in my capabilities, (if set to Android,) I'm not getting socket crash errors. 
@mykola-mokhnach While, not shown here, I've been using a systemPort setup, but thank you for the link.
The only errors, (low repro,) but I'll see if I can narrow down the issue.
Thanks
