### ISSUE TITLE
Unable to create IOSDriver

### ISSUE THREAD

**Issue by JamesChungZLL** [appium/appium#11785]
## The problem

I new a IOSDriver object in code, and have this problem,pls refer to the Appium log.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.10.0
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium:Mac 10.14.1
* Node.js version (unless using Appium.app|exe):v8.2.1
* Mobile platform/version under test:iOS 12.1
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

https://gist.github.com/JamesChungZLL/93e07b843d6e4e1ae44a9f59c4f5cb0f

**Comment by mykola-mokhnach** [comment]
Make sure WDA binary on the device is up to date and is built from the source bundled with appium xcuitest driver. Closed as duplicate
