### ISSUE TITLE
Application file removed from the /app directory after the failed test

### ISSUE THREAD

**Issue by sanyco92** [appium/appium#11782]
## The problem

Hello everyone! 
Just updated to Appium 1.10.0 and faced the issue, when my application file for iOS simulator (.app file) removed after the test if failed. Is there any way to disable this?

Maybe this affected? https://github.com/appium/appium-base-driver/pull/274

## Logs
[appium.log](https://github.com/appium/appium/files/2644124/appium.log)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0
* Last Appium version that did not exhibit the issue (if applicable): 1.9.1 beta 2
* Desktop OS/version used to run Appium: OSX

**Comment by mykola-mokhnach** [comment]
Provide the full path to the application file instead of the relative one

**Comment by sanyco92** [comment]
> Provide the full path to the application file instead of the relative one

Seems like it works! Thank you!
