### ISSUE TITLE
ERROR: ESOCKETTIMEDOUT appears when trying to start tests with Jenkins on remote server

### ISSUE THREAD

**Issue by sanyco92** [appium/appium#11788]
[appium.log](https://github.com/appium/appium.io/files/2648829/appium.before.adding.caps.log)

Hello Guys. I have jenkins server where I run tests with Appium 1.10.0 and WebDriver.io. I have several spec files, I run them like this:
wdio ./config/platforms/wdio.conf.ios.js --suite sync,login,settings,home,myCourses,myEvaluations,myForms,myPublications,
but for the first spec file I'm always getting error:

ERROR: ESOCKETTIMEDOUT
ipadpro(12_9-inch).ios.12_0.app365_beta_app
at new RuntimeError (/Users/company/.jenkins/workspace/app-automation-ios/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
at Request._callback (/Users/company/.jenkins/workspace/app-automation-ios/node_modules/webdriverio/build/lib/utils/RequestHandler.js:332:43)
at self.callback (/Users/company/.jenkins/workspace/app-automation-ios/node_modules/request/request.js:185:22)
at emitOne (events.js:116:13)
at Request.emit (events.js:211:7)
at ClientRequest.<anonymous> (/Users/company/.jenkins/workspace/app-automation-ios/node_modules/request/request.js:819:16)
at Object.onceWrapper (events.js:313:30)
at emitNone (events.js:106:13)
at ClientRequest.emit (events.js:208:7)
at Socket.emitTimeout (_http_client.js:706:34)

Checked appium logs:
[debug] [35m[JSONWP Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[JSONWP Proxy][39m Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[35m[JSONWP Proxy][39m Got an unexpected response: {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}

Also, I noticed this one:
WebDriverAgent successfully started after 259484ms

Maybe someone knows how to solve the issue? Here're my capabilities:

capabilities: [{
maxInstances: 1,
platformName: 'iOS',
platformVersion: '12.0',
automationName: 'XCUITest',
orientation: 'PORTRAIT',
app: '/Users/user/Documents/projects/app365/app/ios/app365_Beta.app',
wdaLaunchTimeout: 600000,
wdaConnectionTimeout: 600000,
newCommandTimeout: 600,
clearSystemFiles: true,
noReset: false,
useJSONSource: true,
maxTypingFrequency: 10,
reduceMotion: true
}],
appium: {
waitStartTime: 90000,
logFileName: 'appium.log',
args: {
address: 'localhost',
port: 4723,
commandTimeout: '7200',
sessionOverride: true,
debugLogSpacing: true
}
},

Then I added the following capabilities, but it didn't help (see the log file [appium (after adding caps).log](https://github.com/appium/appium.io/files/2648830/appium.after.adding.caps.log):
wdaStartupRetries: 5,
wdaStartupRetryInterval: 60000,
useNewWDA: true.

I have a weak computer configuration on remote, so maybe I need to increase some timeouts or something. Please, help.

**Comment by mykola-mokhnach** [comment]
the log is very messy, but I agree, you probably need a better computer

**Comment by sanyco92** [comment]
The issue is still actual and seems like my customer doesn't want to improve computer configuration. Any other ideas how to fix this? Attaching Appium logs including logs from xCode
[appium_xcodeLogs.log](https://github.com/appium/appium/files/2653802/appium_xcodeLogs.log)

**Comment by mykola-mokhnach** [comment]
You can check capabilities setup for driver functional tests. Travis nodes are also not very performant, so the configuration there might be similar to what you need: https://github.com/appium/appium-xcuitest-driver/tree/master/test/functional

**Comment by sanyco92** [comment]
Guys, please help. This issue is kindly annoying. I've found the reason, but I need to find a solution. The reason actually is related to WDA, it's building more than 3-4 minutes. What I see every time on the device:
1) The app under test is installed on the device successfully.
2) WDA is trying to build and install on the device, but sometimes the build process takes 3-4 minutes. After some timeout, the build process is restarting. And again, the app under test reinstalls on the device, then WDA again tries to be built and installed on the device.  This process may have 4 attempts (each 4 minutes). And it takes exactly 16 minutes to display the error ESOCKETTIMEDOUT. Exactly 16 minutes, the difference between 2 timestamps = 16 minutes:

```
16:12:04 [1;30m[08:12:04] [0m [0;35mCOMMAND	[0mPOST 	 "/wd/hub/session"
16:12:04 [1;30m[08:12:04] [0m [0;33mDATA		[0m{"desiredCapabilities": bla bla bla...
16:28:04 ERROR: ESOCKETTIMEDOUT
```

All this time, during each attempt appium, tries to connect to WDA (localhost:8100), and sometimes it may connect, after e.g. 15 minutes and 30 seconds, but when the connection is successful, exactly after 16 minutes I'm gettings the error. Please, help, how can I increase the timeout, this freaking timeout of 16 minutes. Where can I set it? 
I even tried to use prebuilt WDA, but it doesn't help. Sometimes it's connected to WDA after 2 minutes, sometimes after 15, sometimes it doesn't connect at all and ESCOCKETTIMEOUT appears.
Also, I tried to play with capabilities and increase timeouts. Here you can see my capabilities.
```launchTimeout: 20 * 60000,
        deviceReadyTimeout: 120000,
        wdaLaunchTimeout: 10 * 60000,
        wdaConnectionTimeout: 10 * 60000,
        wdaStartupRetries: 10,
        wdaStartupRetryInterval: 500,
        showXcodeLog: false,
        clearSystemFiles: true,
        useNewWDA: false,
        newCommandTimeout: 1800,
        noReset: false,
        maxTypingFrequency: 40,
        reduceMotion: false,
        isHeadless: false,
        usePrebuiltWDA: true,
        derivedDataPath: "~/mobileAutomation/DerivedData/WebDriverAgent"
```
I need your help, also, attaching logs from appium. 
[appium.log](https://github.com/appium/appium/files/3219445/appium.log)

**Comment by mykola-mokhnach** [comment]
The log shows that Appium fails to create a new session. Try to enable the `showIOSLog` and check what xctest daemon/WDA say about application startup

**Comment by sanyco92** [comment]
Guys, according to this issue. I had parameters in webdriverIO: connectionRetryTimeout = 240000 and connectionRetryCount = 3. That's why it has 1st attempt for 4 minutes, then it made 3 more attempts to connect (each for 4 minutes). In sum = 16 minutes. Played with those parameters and solved the issue.

**Comment by hanaavram** [comment]
so which are the settings which solved this issue? I'm running into the exact same problem
