### ISSUE TITLE
Appium@1.10.0: After opening the app, an error is reported

### ISSUE THREAD

**Issue by xukaixin11** [appium/appium#11797]
## The problem

An error is reported when appium starts the application。

## Environment

Appium version (or git revision) that exhibits the issue: v1.10.0
Desktop OS/version used to run Appium:Mac
Node.js version (unless using Appium.app|exe): v11.3.0
Mobile platform/version under test: Any iOS
Real device or emulator/simulator: iPhone

## Details

Appium-version v1.10.0
IPhone-version v12.0.1
Xcode-version v10.1
Java-client v6.1.0

Hoping to get help.Thank you!

## Code To Reproduce Issue [ Good To Have ]
[Appium] Creating new XCUITestDriver (v2.104.0) session
[Appium] Capabilities:
[Appium]   platformName: ios
[Appium]   app: /Users/xuhappy/lifeplus_restructure.ipa
[Appium]   autoAcceptAlerts: true
[Appium]   automationName: XCUITest
[Appium]   bundleId: com.gzyghn.lifeplus
[Appium]   deviceName: 7p
[Appium]   noReset: true
[Appium]   noSign: true
[Appium]   platformVersion: 12.1
[Appium]   udid: fbf74d6cb05c991c6508072ba5c65a6adc17f841
[BaseDriver] W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP desired capabilities {"app":"/Users/xuhappy/life... were provided
[BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"platformNa...
[BaseDriver] The following capabilities were provided, but are not recognized by appium: noSign.
[BaseDriver] Session created with session id: 3370a525-e282-4297-8467-9f768676f25e
[XCUITest] Current user: 'xuhappy'
[XCUITest] Available devices: fbf74d6cb05c991c6508072ba5c65a6adc17f841
[XCUITest] Creating iDevice object with udid 'fbf74d6cb05c991c6508072ba5c65a6adc17f841'
[XCUITest] Determining device to run tests on: udid: 'fbf74d6cb05c991c6508072ba5c65a6adc17f841', real device: true
[XCUITest] Xcode version set to '10.1' 
[XCUITest] iOS SDK Version set to '12.1'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1544153858126 (11:37:38 GMT+0800 (CST))
[BaseDriver] Using local app '/Users/xuhappy/lifeplus_restructure.ipa'
[BaseDriver] Will reuse previously cached application at '/var/folders/nt/8_lpr1jj24n0cktsh6qt1n740000gn/T/2018117-1783-1d4vq6r.c45g/Payload/LifePlus.app'
[BaseDriver] Event 'appConfigured' logged at 1544153858394 (11:37:38 GMT+0800 (CST))
[XCUITest] Checking whether app '/var/folders/nt/8_lpr1jj24n0cktsh6qt1n740000gn/T/2018117-1783-1d4vq6r.c45g/Payload/LifePlus.app' is actually present on file system
[XCUITest] App is present
[BaseDriver] Event 'resetStarted' logged at 1544153858397 (11:37:38 GMT+0800 (CST))
[XCUITest] Reset: fullReset not set. Leaving as is
[BaseDriver] Event 'resetComplete' logged at 1544153858397 (11:37:38 GMT+0800 (CST))
[iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[iOSLog] Starting iOS device log capture with: 'idevicesyslog'
[XCUITest] Crash reports root '/Users/xuhappy/Library/Logs/CrashReporter/MobileDevice/7p' does not exist. Got nothing to gather.
[BaseDriver] Event 'logCaptureStarted' logged at 1544153858586 (11:37:38 GMT+0800 (CST))
[XCUITest] Setting up real device
[XCUITest] Verifying application platform
[XCUITest] CFBundleSupportedPlatforms: ["iPhoneOS"]
[XCUITest] App 'com.gzyghn.lifeplus' is already installed. No need to reinstall.
[BaseDriver] Event 'appInstalled' logged at 1544153859016 (11:37:39 GMT+0800 (CST))
[XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[JSONWP Proxy] Matched '/status' to command name 'getStatus'
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"12.1\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"12.1\",\n      \"ip\" : \"10.102.21.54\"\n    },\n    \"build\" : {\n      \"time\" : \"Dec  7 2018 11:13:01\"\n    }\n  },\n  \"sessionId\" : \"AB08EDF1-1E97-4C8D-AF50-6FC7444C8C3B\",\n  \"status\" : 0\n}"
[XCUITest] Connection to WDA timed out
[iProxy] recv failed: Operation not permitted
[XCUITest] Upgrade timestamp of the currently bundled WDA: 1537947140000
[XCUITest] Upgrade timestamp of the WDA on the device: undefined
[XCUITest] Will reuse previously cached WDA instance at 'http://localhost:8100/'. Set the wdaLocalPort capability to a value different from 8100 if this is an undesired behavior.
[XCUITest] Trying to start WebDriverAgent 1 times with 10000ms interval
[BaseDriver] Event 'wdaStartAttempted' logged at 1544153859105 (11:37:39 GMT+0800 (CST))
[XCUITest] Using provided WebdriverAgent at 'http://localhost:8100/'
[BaseDriver] Event 'wdaSessionAttempted' logged at 1544153859105 (11:37:39 GMT+0800 (CST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Matched '/status' to command name 'getStatus'
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"12.1\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"12.1\",\n      \"ip\" : \"10.102.21.54\"\n    },\n    \"build\" : {\n      \"time\" : \"Dec  7 2018 11:13:01\"\n    }\n  },\n  \"sessionId\" : \"AB08EDF1-1E97-4C8D-AF50-6FC7444C8C3B\",\n  \"status\" : 0\n}"
[JSONWP Proxy] Matched '/session' to command name 'createSession'
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.gzyghn.lifeplus","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true,"defaultAlertAction":"accept"}}
[XCUITest] Connection to WDA timed out
[iProxy] recv failed: Operation not permitted
[JSONWP Proxy] Got response with status 200: {"value":{"sessionId":"65AD8D95-6A2B-4374-8CD4-23F45A039063","capabilities":{"device":"iphone","browserName":"生活Plus","sdkVersion":"12.1","CFBundleIdentifier":"com.gzyghn.lifeplus"}},"sessionId":"65AD8D95-6A2B-4374-8CD4-23F45A039063","status":0}
[BaseDriver] Event 'wdaSessionStarted' logged at 1544153862716 (11:37:42 GMT+0800 (CST))
[BaseDriver] Event 'wdaStarted' logged at 1544153862716 (11:37:42 GMT+0800 (CST))
[XCUITest] Skipping setting of the initial display orientation. Set the "orientation" capability to either "LANDSCAPE" or "PORTRAIT", if this is an undesired behavior.
[BaseDriver] Event 'orientationSet' logged at 1544153862717 (11:37:42 GMT+0800 (CST))
[Appium] New XCUITestDriver session created successfully, session 3370a525-e282-4297-8467-9f768676f25e added to master session list
[BaseDriver] Event 'newSessionStarted' logged at 1544153862717 (11:37:42 GMT+0800 (CST))
[W3C (3370a525)] Cached the protocol value 'W3C' for the new session 3370a525-e282-4297-8467-9f768676f25e
[W3C (3370a525)] Responding to client with driver.createSession() result: {"capabilities":{"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"platformName":"ios","app":"/Users/xuhappy/lifeplus_restructure.ipa","autoAcceptAlerts":true,"automationName":"XCUITest","bundleId":"com.gzyghn.lifeplus","deviceName":"7p","noReset":true,"noSign":true,"platformVersion":"12.1","udid":"fbf74d6cb05c991c6508072ba5c65a6adc17f841"}}
[HTTP] <-- POST /wd/hub/session 200 5356 ms - 551
[HTTP] 
[XCUITest] Connection to WDA timed out
[iProxy] recv failed: Operation not permitted
[HTTP] --> GET /wd/hub/session/3370a525-e282-4297-8467-9f768676f25e
[HTTP] {}
[W3C (3370a525)] Calling AppiumDriver.getSession() with args: ["3370a525-e282-4297-8467-9f768676f25e"]
[XCUITest] Executing command 'getSession'
[JSONWP Proxy] Matched '/' to command name 'getSession'
[JSONWP Proxy] Proxying [GET /] to [GET http://localhost:8100/session/65AD8D95-6A2B-4374-8CD4-23F45A039063] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"sessionId\" : \"65AD8D95-6A2B-4374-8CD4-23F45A039063\",\n    \"capabilities\" : {\n      \"device\" : \"iphone\",\n      \"browserName\" : \"生活Plus\",\n      \"sdkVersion\" : \"12.1\",\n      \"CFBundleIdentifier\" : \"com.gzyghn.lifeplus\"\n    }\n  },\n  \"sessionId\" : \"65AD8D95-6A2B-4374-8CD4-23F45A039063\",\n  \"status\" : 0\n}"
[JSONWP Proxy] Proxying [GET /wda/screen] to [GET http://localhost:8100/session/65AD8D95-6A2B-4374-8CD4-23F45A039063/wda/screen] with no body
[XCUITest] Connection to WDA timed out
[iProxy] recv failed: Operation not permitted
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"Unhandled endpoint: \\/session\\/65AD8D95-6A2B-4374-8CD4-23F45A039063\\/wda\\/screen -- http:\\/\\/localhost:8100\\/ with parameters {\\n    wildcards =     (\\n        \\\"session\\/65AD8D95-6A2B-4374-8CD4-23F45A039063\\/wda\\/screen\\\"\\n    );\\n}\",\n  \"sessionId\" : \"65AD8D95-6A2B-4374-8CD4-23F45A039063\",\n  \"status\" : 1\n}"
[MJSONWP] Matched JSONWP error code 1 to UnknownError
[XCUITest] Connection to WDA timed out
[iProxy] recv failed: Operation not permitted
[W3C (3370a525)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Unhandled endpoint: /session/65AD8D95-6A2B-4374-8CD4-23F45A039063/wda/screen -- http://localhost:8100/ with parameters {
[W3C (3370a525)]     wildcards =     (
[W3C (3370a525)]         "session/65AD8D95-6A2B-4374-8CD4-23F45A039063/wda/screen"
[W3C (3370a525)]     );
[W3C (3370a525)] }
[W3C (3370a525)]     at errorFromMJSONWPStatusCode (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/lib/protocol/errors.js:789:10)
[W3C (3370a525)]     at ProxyRequestError.getActualError (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/lib/protocol/errors.js:683:14)
[W3C (3370a525)]     at JWProxy.command (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:234:19)
[HTTP] <-- GET /wd/hub/session/3370a525-e282-4297-8467-9f768676f25e 500 116 ms - 1131
[HTTP]

**Comment by KazuCocoa** [comment]
> [JSONWP Proxy] Got response with status 200: "{\n "value" : {\n "state" : "success",\n "os" : {\n "name" : "iOS",\n "version" : "12.1"\n },\n "ios" : {\n "simulatorVersion" : "12.1",\n "ip" : "10.102.21.54"\n },\n "build" : {\n "time" : "Dec 7 2018 11:13:01"\n }\n },\n "sessionId" : "AB08EDF1-1E97-4C8D-AF50-6FC7444C8C3B",\n "status" : 0\n}"
[XCUITest] Connection to WDA timed out
[iProxy] recv failed: Operation not permitted
[XCUITest] Upgrade timestamp of the currently bundled WDA: 1537947140000
[XCUITest] Upgrade timestamp of the WDA on the device: undefined
[XCUITest] Will reuse previously cached WDA instance at 'http://localhost:8100/'. Set the wdaLocalPort capability to a value different from 8100 if this is an undesired behavior.
[XCUITest] Trying to start WebDriverAgent 1 times with 10000ms interval
[BaseDriver] Event 'wdaStartAttempted' logged at 1544153859105 (11:37:39 GMT+0800 (CST))
[XCUITest] Using provided WebdriverAgent at 'http://localhost:8100/'
[BaseDriver] Event 'wdaSessionAttempted' logged at 1544153859105 (11:37:39 GMT+0800 (CST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Matched '/status' to command name 'getStatus'
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Got response with status 200: "{\n "value" : {\n "state" : "success",\n "os" : {\n "name" : "iOS",\n "version" : "12.1"\n },\n "ios" : {\n "simulatorVersion" : "12.1",\n "ip" : "10.102.21.54"\n },\n "build" : {\n "time" : "Dec 7 2018 11:13:01"\n }\n },\n "sessionId" : "AB08EDF1-1E97-4C8D-AF50-6FC7444C8C3B",\n "status" : 0\n}"
[JSONWP Proxy] Matched '/session' to command name 'createSession'
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.gzyghn.lifeplus","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true,"defaultAlertAction":"accept"}}

Failed to launch WDA, it looks.

What about adding `useNewWDA: true` in your capability or uninstalling WDA app from your test device once?

**Comment by mykola-mokhnach** [comment]
The WDA binary is cached and it is necessary to clear Xcode caches, remove the obsolete stuff from the device and make sure the binary is deployed from source, which is bundled together with xcuitest driver

**Comment by xukaixin11** [comment]
Yes, it is the problem of environment deployment
thank you
