### ISSUE TITLE
Launch app and Reset app each create new session(iOS)

### ISSUE THREAD

**Issue by SquidLips** [appium/appium#11799]
## The problem

LaunchApp and Reset app both create new sessions while disposing the previous one. This causes my test to randomly crash in the middle when my webdriver tries to use the disposed session. For reference, Android runs fine using the same setup. Spinning up new webdrivers for each session is many times slower than simply resetting the app

## Environment

* Desktop OS/version used to run Appium: Mac Appium Version 1.8.2 (1.8.2.20181101.4)
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real device

## Link to Appium logs

https://gist.github.com/SquidLips/bd7fd2e3c48f0bb204621c8cf6cf3264

## Code To Reproduce Issue [ Good To Have ]

for (int i = 0; i < 10; ++i)
            {
                iOSDriver.ResetApp();
                iOSDriver.FindElementByAccessibilityId("hamburger").Click();//Any clickable element
            }

**Comment by mykola-mokhnach** [comment]
resetApp internally does the same thing as quit and init the driver. In general, it is not recommended for use. You can use noReset capability or/and different wda-related capabilities to control the server behaviour on session init. Regarding the fact, that webdriveragent stops responding being reinstalled multiple times on real device - this is known is up to Apple. We cannot do nothing to fix that on appium side. This is also the reason why Appium tries to cache WDA and avoid rebuilding it if that is not necessary.

Closed as not an issue
