### ISSUE TITLE
Appium able to locate element, but freezing while clicking/getting location for same element

### ISSUE THREAD

**Issue by aleks2a** [appium/appium#11796]
## The problem
Hi, I was able to locate element in Application, but when clicking on element Appium just freezes.
I was also tried to call `.location` and it's also freezes, when I manually pressing on element, then Appium returning coordinates right away.

## Environment

* Appium version (or git revision) that exhibits the issue: Version 1.8.2 (1.8.2.20181101.4)
* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium: macOS HighSierra 10.13.6
* Node.js version (unless using Appium.app|exe): using Appium.app
* Mobile platform/version under test: Android Nexus 5, Android 8.1.0
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: Appium.app

## Link to Appium logs
Appium log: https://gist.github.com/aleks2a/04dfa4da9c2c2c02b4b63ce863746e68
ADB log: https://gist.github.com/aleks2a/874d3402d163c2b10b14409daa795080

## Code To Reproduce Issue [ Good To Have ]

Not sure if it's actual bug in Appium, but would appreciate if anyone could suggest how to resolve it.
 
Also screenshot from UIAutomatorviewer:
<img width="400" alt="screen shot 2018-12-06 at 12 39 49 pm" src="https://user-images.githubusercontent.com/4288853/49610782-62812500-f954-11e8-9ce4-3c9309600cf9.png">

**Comment by mykola-mokhnach** [comment]
Try to upgrade appium to the most recent version or appium@beta

**Comment by aleks2a** [comment]
@mykola-mokhnach thanks for reply,
I tried latest Appium version: Appium v1.10.0
In latest Appium element is not reachable.
Here is results:
<img width="999" alt="screen shot 2018-12-06 at 1 54 07 pm" src="https://user-images.githubusercontent.com/4288853/49614240-8ea1a380-f95e-11e8-81a1-cecacc6feb54.png">


Appium: https://gist.github.com/aleks2a/5053313e3e1d5a5838e09fdbee1c8977
ADB log: https://gist.github.com/aleks2a/450475e92ef4d965a13488b7fd21d03e

**Comment by mykola-mokhnach** [comment]
The full appium log is needed. The current part of the log does not show any settings or version numbers.

Also, this might be an issue with UIA2 framework itself. Then there will be no solution except of changing the driver type, for example to Espresso one.

**Comment by aleks2a** [comment]
Attaching full Appium log:
https://gist.github.com/aleks2a/75aaad29191738cc22b66a52ee970049

**Comment by mykola-mokhnach** [comment]
You can still check if it works with appium@beta, but I think it is an issue in UIA2 framework and should be reported to Google.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by aleks2a** [comment]
We didn't confirm that, right?
We have 2 different behaviors on 2 Appium versions locating same element. So something broken in Appium for sure.
