### ISSUE TITLE
Webelement.clear() is not working on the iOS

### ISSUE THREAD

**Issue by Phoenix124** [appium/appium#11798]
## The problem

Trying to use method webelement.clear() at the ionic app input field
but this method is not working
Could you say some help/advice how to clear field faster than clicking on backspase button at native keyboard?
  
## Environment

* appium 1.10.0
* High Siera 10.13.6
* node: 11.1.0
* ios 12.1
* emulator iPhone 6s

## Code To Reproduce Issue [ Good To Have ]
webelement.clear() at the ionic app

**Comment by mykola-mokhnach** [comment]
Switch to web context and clear the field with javascript. Nothing else can be done on Appium side.

See https://appiumpro.com/editions/36 for more details

**Comment by Phoenix124** [comment]
@mykola-mokhnach can you write an examle of clear  script?
I found that i need to set capabilities.setCapability("nativeWebTap", true);
and what else?
When i'm trying to use element.clear(), it doesn't work.

**Comment by mykola-mokhnach** [comment]
There is no example.  You should write a script, which is compatible to your particular application

**Comment by imurchie** [comment]
@Phoenix124 This _can_ work. Do you have the logs? Unfortunately "not working" is unhelpful in diagnosing anything, or giving any sort of advice.

**Comment by Phoenix124** [comment]
@imurchie no exceptions when try to use 
.clear().Besides, .sendKeys(Keys.BACK_SPACE)  is working.
