### ISSUE TITLE
how to execute multiple mobile: shell commands ?

### ISSUE THREAD

**Issue by selenUser** [appium/appium#11793]
according to [here](http://appium.io/docs/en/writing-running-appium/android/android-shell/#mobile-shell)
we can run shell commands like this
`
Map<String, Object> args = new HashMap<>();

args.put("command", "echo");

args.put("args", Lists.newArrayList("arg1", "arg2"));

String output = driver.executeScript("mobile: shell", args);
`

how can I run multiple commands ?
command 1: su
command 2: cp from to
command 3: rm from

Thanks for help

**Comment by mykola-mokhnach** [comment]
this is not possible

**Comment by selenUser** [comment]
What is not possible ? Multi commands or su or both ?

**Comment by mykola-mokhnach** [comment]
Both not possible.
I would also try to separate each command with `;` to create oneliner, but there is no guarantee it is going to work. Also, pushFile/pullFile API does support interaction with files inside application containers, which are complied in debug mode. See https://github.com/appium/java-client/blob/1991a8a0f9e4a3ff467dbb713cb5c51c8edc060f/src/main/java/io/appium/java_client/android/PushesFiles.java#L34
