### ISSUE TITLE
Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65".

### ISSUE THREAD

**Issue by Balamuruganvsb** [appium/appium#11792]
![screen shot 2018-12-06 at 3 57 39 pm](https://user-images.githubusercontent.com/17315457/49578702-5c993d00-f970-11e8-8752-719a3632e8ba.png)

I'm getting code 65 after updating the Xcode latest version(10.1).

In WebDriverAgent project, Some of the files(WebDriverAgentLib, WebDriverAgentRunner,Modules) are displayed as an error and the same error the displayed after manually creating WebDriverAgent.bundle folder and clean the derived data. I'm not sure, Code 65 error comes due to this project error. 

When running the WebdriverAgent project, the build got succeeded but the app is not installed in the device.

But, the appium inspector is working fine and able to inspect the elements. While using appium inspector, the webdriveragent app is installed in the device.

[appium-server-logs.txt](https://github.com/appium/appium/files/2652688/appium-server-logs.txt)
![Uploading Screen Shot 2018-12-06 at 3.57.39 PM.png…]()

Attached Appium logs.

## Environment

* Appium server version: 1.10.0  (Appium inspector version: 1.9.1)
* Desktop OS/version used to run Appium:  macOS High Sierra (10.13.6)
* Mobile platform/version under test: iOS 10.3.2 and 12.0
* Real device or emulator/simulator: Real Device

**Comment by mykola-mokhnach** [comment]
> [warn] [XCUITest] Cannot parse major and minor version numbers from platformVersion "undefined". Will build for the default platform instead

> [info] [Xcode] 	The test runner encountered an error (Failed to install or launch the test runner. (Underlying error: The bundle identifier for IntegrationApp.app couldn’t be read. No such file or directory: “/Users/balamurugan/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/IntegrationApp.app”.))
[info] [Xcode] ** TEST EXECUTE FAILED **

I can observe these two issues in the log and I assume they are the reason why the testing cannot start

**Comment by Balamuruganvsb** [comment]
@mykola-mokhnach Thanks a lot. It works fine after adding the IntegrationApp.app in the particular path.

**Comment by AvrahamAtia** [comment]
@mykola-mokhnach  @Balamuruganvsb How can I add the IntegrationApp.app in the particular path?

**Comment by Pr60** [comment]
@Balamuruganvsb I have the same problem. The IntegrationApp.app exists but is 0 Bytes. How did you add IntegrationApp.app (In case @AvrahamAtia you figured this out in a month)

**Comment by deedora** [comment]
@Pr60 I have the same error. Did you fix it?

**Comment by Pr60** [comment]
@deedora - I deleted `WebDriverAgent-* ` folders under `/Users/username/Library/Developer/Xcode/DerivedData/` and then started my tests again. This worked for me.
