### ISSUE TITLE
Locating of elements takes a long time

### ISSUE THREAD

**Issue by mjm987mj** [appium/appium#11809]
## The problem
I've been trying to automate an app with Appium and React Native (0.57.5) however I'm experiencing very slow response times when interacting with elements. This only happens for Android for iOS I undergo no issues.

## Environment
* Appium version: Appium Desktop v1.10.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: MacOS Mojave 10.14.1
* Node.js version: v11.3.0
* Mobile platform/version under test: Android 8.1.0
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: v1.10.0
* React native version: 0.57.5

## Details
I'm trying to click on the first element on the screen in order to continue to the second screen. However it seems that Appium is taking a very long time locating (let alone interact with) the elements. The logs provided below show the time that it takes to only identify the element. When I compare this to a full native app I get a 200 back almost immediately.

## Link to Appium logs
https://gist.github.com/mjm987mj/937a729f12b89c9cf320068539a06c73#file-appiumlogs

## Code To Reproduce Issue [ Good To Have ]
Simply clicking on a MobileElement by accessibility id or any other selector.

**Comment by dpgraham** [comment]
Xpath is slow. I recommend using either accessibility ID or  `-android uiautomator`.

You can also try the Espresso driver (`automationName="Espresso"`)

**Comment by mjm987mj** [comment]
Hi Thanks for the feedback. I know xpath is slow. With accessibility ID  I have the same issues.  Did we then not closed the ticket to soon?

I will try with Espresso and see if it speeds up the process.

Kind regards,

**Comment by mjm987mj** [comment]
Hi @dpgraham,

Here you can see that I'm looking for accessibility ID = doorgaan. But still it takes aprox. 30sec to find the element. See the below gists for the appium logs.

UiAutomater2
https://gist.github.com/mjm987mj/613d10abd45df7f9f9ef8356f089eb06
UiAutomaer
https://gist.github.com/mjm987mj/d964711e9a79cb16737b44933d03a9ff

I can't seem to figure out why it is taking so long. I did a cross check with a full native app and I have no issues there. The app I'm targeting is a react native app (react native version 0.57.5). Are you aware of any issues with automating a React Native app with Appium for Android? I'm kinda hitting a dead end here :(

P.S, I haven't got Espresso driver to work yet. I will continue to work on that this week

Thanks for your time,
