### ISSUE TITLE
Appium+iOS Device + Jenkins - [XCUITest] The 'idevice_id' program is not installed.

### ISSUE THREAD

**Issue by dduphorn** [appium/appium#11800]
I'm having the same issue. 

I can execute my Appium iOS test on real device from both Eclipse and Maven, but when I execute the same script from Jenkins I get the error:

[XCUITest] The 'idevice_id' program is not installed. If you are running a real device test it is necessary. Install with 'brew install libimobiledevice --HEAD'

I added the following to figure out where it's looking for the idevice_id, and the director looks correct.

    which idevice_id
    /usr/local/bin/idevice_id
    brew install libimobiledevice
    Warning: libimobiledevice 1.2.0_3 is already installed and up-to-date
    To reinstall 1.2.0_3, run brew reinstall libimobiledevice

When I use FruitStrip it finds the device from Jenkins. Is there a way to use FruitStrip with Appium?

**Comment by mykola-mokhnach** [comment]
The app might be visible for your user, but the Jenkins user might have different permissions and environment settings. Read https://github.com/appium/java-client/blob/master/docs/environment.md for more details. 

>  Is there a way to use FruitStrip with Appium?

No this is not possible unless you modify the source code locally.

Closed as duplicate

**Comment by dduphorn** [comment]
You already had me go there, and nothing there assisted in my effort.   This is very frustrating.

**Comment by dduphorn** [comment]
I copied by bash_profile values into the Execute Shell, and I'm still getting the error

[XCUITest] The 'idevice_id' program is not installed. If you are running a real device test it is necessary. Install with 'brew install libimobiledevice --HEAD' 

Where is jenkins looking for idevice_id?

I see you closed this, which sucks because it's still not working for me.  Hopefully someone else runs into this issue and can help me resolve it.

**Comment by mykola-mokhnach** [comment]
The report has been closed because it is not a problem with the server, but rather an issue with local environment setup. We have Appium forum where people can ask questions.

**Comment by dduphorn** [comment]
Ok, if anyone runs into this issue or can assist me, please navigate here. https://discuss.appium.io/t/appium-jenkins-real-device-ios/21166/26

**Comment by dduphorn** [comment]
> The report has been closed because it is not a problem with the server, but rather an issue with local environment setup. We have Appium forum where people can ask questions.

Have you successfully run appium from jenkins using a real iOS device?
