### ISSUE TITLE
use of w3c elements as execute script args is broken

### ISSUE THREAD

**Issue by jlipps** [appium/appium#11806]
## The problem

Finding elements via the Safari atoms returns elements with the form {ELEMENT: "id"}. Appium correctly rewrites ELEMENT to the w3c element prefix.

Now, if the client runs an executeScript command passing in the element object as a parameter, the safari atoms will not treat this as an actual element, because they are looking for something with the key ELEMENT

## The fix

Before sending off an executeScript atom, we should look at its arguments recursively to see if we need to rewrite the w3c element prefix to ELEMENT.

**Comment by dpgraham** [comment]
I'll take this....

I think the proper fix for this is that we shouldn't be renaming keys but rather duplicating them.

We should send both formats: 

```
{
  "ELEMENT": "abcd-1234-efgh",
  "element-6066-11e4-a52e-4f735466cecf": "abcd-1234-efgh"
}
```
