### ISSUE TITLE
Locale/language not working on Android 8 emulators

### ISSUE THREAD

**Issue by vrunoa** [appium/appium#11815]
## The problem

Locale/language capabilities are not working on Android 8 Emulators

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS 10.13.6
* Node.js version (unless using Appium.app|exe): v8.1.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Android 8 Emulator
* Appium CLI or Appium.app|exe:

## Details

Seems like Android 8 needs root access for setting the locale/language. 

## Link to Appium logs

https://gist.github.com/vrunoa/37bfabe8d1827489b091a279921c44bb

## Code To Reproduce Issue [ Good To Have ]

Boot an emulator and try to run an appium test setting locale/language capabilities, for a quick test im using runsauce

```
runsauce -c local -t android -v 8.0 -d "Android Emulator" -b "chrome" -a 1.9.1 -e '{"locale":"es_AR", "language":"es"}'
```
Error
```
[debug] [MJSONWP] Encountered internal error running command: Error: Failed to set language: es and country: es_AR
[debug] [MJSONWP]     at Object.callee$0$0$ (/Users/brunoalassia/.nvm/versions/node/v8.1.0/lib/node_modules/appium/node_modules/appium-android-driver/lib/android-helpers.js:152:11)
[debug] [MJSONWP]     at tryCatch (/Users/brunoalassia/.nvm/versions/node/v8.1.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[debug] [MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/brunoalassia/.nvm/versions/node/v8.1.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[debug] [MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/brunoalassia/.nvm/versions/node/v8.1.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[debug] [MJSONWP]     at GeneratorFunctionPrototype.invoke (/Users/brunoalassia/.nvm/versions/node/v8.1.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[debug] [MJSONWP]     at <anonymous>
[HTTP] <-- POST /wd/hub/session 500 4430 ms - 182
```

**Comment by KazuCocoa** [comment]
What about setting `locale: 'AR', language: 'es'` instead of `locale: 'es_AR', language: 'es'`?

Currently, the logic uses https://github.com/appium/io.appium.settings#changing-of-system-settings . It does not require root permission, but the `locale` in capability is used in `country` part as `Failed to set language: es and country: es_AR`.
Could you try to change the capability or try to call `adb shell am broadcast -a io.appium.settings.locale --es lang es --es country AR` directly after `adb shell pm grant io.appium.settings android.permission.CHANGE_CONFIGURATION`?

**Comment by vrunoa** [comment]
@KazuCocoa yeap, using only that fixes it. On older Android versions we use 'es_AR` and was working. Going to investigate a bit to see if this format works with older appium/android versions.
