### ISSUE TITLE
Chromedriver ports conflict when there are multiple webviews and --chromedriver-port argument is specified

### ISSUE THREAD

**Issue by ajithvl** [appium/appium#11820]
## The problem

I have an Android app that has multiple webviews. Say WEBVIEW_1 and WEBVIEW_2
NOTE: This bug is only reproducible if we start Appium with the argument `--chromedriver-port`
Switching to WEBVIEW_2 after switching to WEBVIEW_1 kills the chromedriver process associated with WEBVIEW_1 and the command fails with `unknown error`

## Environment

* Reproducible on Appium 1.8.1, 1.9.1, and 1.10.0 (tested on chromedriver 2.43, 2.44, and 2.45)
* OS: Ubuntu 16
* Node.js version : v8.1.0
* Mobile platform/version under test: HUAWEI Nexus 6P on android 8.0.0
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium using python or java client

## Details
STEPS:
1) Start appium with lets say `appium --chromedriver-port 1815`
Suppose the Android has tewo webviews. Say `WEBVIEW_chrome` and `WEBVIEW_com.app.package`
Output of `driver.contexts`: ['NATIVE_APP', 'WEBVIEW_chrome', 'WEBVIEW_com.app.package']
2) Switch to `WEBVIEW_com.app.package` using `driver.switch_to.context('WEBVIEW_com.app.package')`
At this point if we do a `ps -ef | grep chromedriver` we get this 
pbox     31270 30840  0 13:29 ?        00:00:00 /home/path/chromedriver_64 --url-base=wd/hub --port=1815 --adb-port=5037 --verbose
3) Clicking on a link within `WEBVIEW_com.app.package` displays the 2nd webview `WEBVIEW_chrome`. 
CODE: 
driver.find_element_by_xpath("//SPAN[text()='Sign Up Now']").click()
4) Switch to the second webview `WEBVIEW_chrome` using `driver.switch_to.context('WEBVIEW_chrome')` returns the error 

500 {"value":{"error":"unknown error","message":"An unknown server-side error occurred while processing the command. Original error: Chromedriver quit unexpectedly during session","stacktrace":"UnknownError: An unknown server-side error occurred while processing the command. Original error: Chromedriver quit unexpectedly during session\n    at getResponseForW3CError (/home/path/errors.js:826:9)\n    at asyncHandler (/home/path/protocol.js:447:37)\n    at <anonymous>"}}

Looks like at this point appium tried to pkill chromedriver process associated with `WEBVIEW_com.app.package` running on 1815 with 

```
2018-12-11 12:56:23:237 - [debug] [Chromedriver] Killing any old chromedrivers, running: pkill -15 -f "/home/path/chromedriver_64.*--port=1815"
2018-12-11 12:56:23:252 - [Chromedriver] Chromedriver exited unexpectedly with code null, signal SIGTERM
2018-12-11 12:56:23:253 - [debug] [Chromedriver] Changed state to 'stopped'
2018-12-11 12:56:23:253 - [AndroidDriver] Chromedriver for context WEBVIEW_com.app.package stopped unexpectedly
2018-12-11 12:56:23:279 - [debug] [UiAutomator2] Deleting UiAutomator2 session
2018-12-11 12:56:23:280 - [debug] [AndroidDriver] Stopping chromedriver for context WEBVIEW_com.app.package
2018-12-11 12:56:23:280 - [debug] [Chromedriver] Changed state to 'stopping'
2018-12-11 12:56:23:284 - [debug] [JSONWP Proxy] Proxying [DELETE /] to [DELETE http://127.0.0.1:1815/wd/hub/session/dfab7a550f961ba3be22e6aaa32fc996] with no body
```

## Link to Appium logs

 [Relevant Appium logs](https://gist.github.com/ajithvl/abc16ed66f1884b0015c7cf4a3c1ef4f)

## Code To Reproduce Issue [ Good To Have ]

I dont have a public app with webview enabled. The code looks like this

driver = webdriver.Remote(url, dc)
driver.find_element_by_xpath("//*[contains(@text, 'Shop Today')]").click()
driver.switch_to.context('WEBVIEW_com.app.package)
driver.find_element_by_xpath("//SPAN[text()='Sign Up Now']").click()
driver.switch_to.context('WEBVIEW_chrome) <-- Fails at this line

**Comment by mykola-mokhnach** [comment]
@imurchie FYI

**Comment by jlipps** [comment]
seems like the combination of usage of `--chromedriver-port` and the existence of multiple webviews in one app has not been foreseen or tested?

**Comment by ajithvl** [comment]
Thanks @jlipps. Closing this as its no longer an issue with `chromedriverPorts` cap now available.
