### ISSUE TITLE
WebDriverAgent does not launch with Appium 1.10.0

### ISSUE THREAD

**Issue by Warren25** [appium/appium#11834]
## The problem

WDA fails to launch with appium server version 1.10.0. Can not automate iOS app. However, I am able to launch WDA and automate with iOS on previous version of 1.9.1, so it appears this issue starts with 1.10.0.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0
* Last Appium version that did not exhibit the issue (if applicable): 1.9.1
* Desktop OS/version used to run Appium: Mac OS High Sierra
* Node.js version (unless using Appium.app|exe): 8.11.1
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium Desktop

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/Warren25/da308c639b93872662376b2fc71d40e7

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
> [info] [35m[Xcode][39m 
> [info] [35m[Xcode][39m 2018-12-13 12:40:56.053 xcodebuild[9692:316409] Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Failed to install or launch the test runner" UserInfo={NSLocalizedRecoverySuggestion=If you believe this error represents a bug, please attach the result bundle at /Users/warren.jones/Library/Developer/Xcode/DerivedData/WebDriverAgent-dyjflyxscdlrfnazvdwutnfxwpqk/Logs/Test/Test-WebDriverAgentRunner-2018.12.13_12-40-53--0500.xcresult, NSLocalizedDescription=Failed to install or launch the test runner, NSUnderlyingError=0x7fedaec55870 {Error Domain=IDETestApplcationDependencyMapperErrorDomain Code=2 "The bundle identifier for WebDriverAgentRunner-Runner.app couldn’t be read." UserInfo={NSLocalizedFailureReason=The application may be damaged or incomplete: “/Users/warren.jones/Library/Developer/Xcode/DerivedData/WebDriverAgent-dyjflyxscdlrfnazvdwutnfxwpqk/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app”., NSURL=file:///Users/warren.jones/Library/Developer/Xcode/DerivedData/WebDriverAgent-dyjflyxscdlrfnazvdwutnfxwpqk/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app/, NSFilePath=/Users/warren.jones/Library/Developer/Xcode/DerivedData/WebDriverAgent-dyjflyxscdlrfnazvdwutnfxwpqk/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSLocalizedDescription=The bundle identifier for WebDriverAgentRunner-Runner.app couldn’t be read.}}}
> [info] [35m[Xcode][39m 
> [info] [35m[Xcode][39m 
> [info] [35m[Xcode][39m Testing failed:
> [info] [35m[Xcode][39m 	'RoutingHTTPServer/RoutingConnection.h' file not found
> [info] [35m[Xcode][39m 	The test runner encountered an error (Failed to install or launch the test runner. (Underlying error: The bundle identifier for WebDriverAgentRunner-Runner.app couldn’t be read. The application may be damaged or incomplete: “/Users/warren.jones/Library/Developer/Xcode/DerivedData/WebDriverAgent-dyjflyxscdlrfnazvdwutnfxwpqk/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app”.))
> [info] [35m[Xcode][39m ** TEST EXECUTE FAILED **

WebDriverAgent at /Applications/Appium 1-9-0.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj cannot be compiled according to the log. 
Make sure you can compile and deploy it to the phone manually via Xcode first. Also, it might be necessary  to clear Xcode caches.

**Comment by Warren25** [comment]
Hey guys (@mykola-mokhnach @imurchie), I'm officially pretty lost at this point. I've followed both your suggestions, compiling and deploying the WDA project onto the device. I've also cleared my cleaned the build folder for the project and deleted all `/Users/warren.jones/Library/Developer/Xcode/DerivedData/WebDriverAgent-*` files.

At this point, I'm running into signing issues which I've ran into many times before. Do you have to resign every time you update to a new server version?

Anyway, here is the new gist log that shows error "WebDriverAgentRunner" requires a development team: https://gist.github.com/Warren25/fa8d0c5f9d48ec211c0df9f426980034

And here is a screenshot of showing that I have manually configured the signing certificate, and had a successful output after running this command -> `xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' test`

**Comment by mykola-mokhnach** [comment]
Double check if the xctest config contains correct information

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
