### ISSUE TITLE
Appium Failed to run tests with appium-uiautomator 2 with tablet and Android 7: Original error: Could not proxy command to remote server. Original error: Error: socket hang up (WARNING: The server did not provide any stacktrace information)

### ISSUE THREAD

**Issue by BrunoCarvalho18** [appium/appium#11830]
## The problem

Failed to run tests with appium-uiautomator2-server-debug-androidTest.apk and appium-uiautomator2-server-v0.1.5.apk automatically, appium stop the server and return " Original error: Could not proxy command to remote server. Original error: Error: socket hang up (WARNING: The server did not provide any stacktrace information)".

I have reboot the device but still it isn't working

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Desktop OS/version used to run Appium: MacOS High Sierra
* Node.js version (unless using Appium.app|exe):v10.14.2 
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Real Device(Tablet)
* Appium CLI or Appium.app|exe: appium cli

## Details

I'm run my tests and Appium Return "org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up (WARNING: The server did not provide any stacktrace information)".

I'm using Tablet Android and UIAutomator 2, but ins't work with Appium 1.8.1

## Link to Appium logs

https://gist.github.com/BrunoCarvalho18/1464a805eda0a8c7f4bf37bf1115f37b

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Please use the most recent server version (1.10.0). Also make sure there are no leftovers on the device from previous versions.

**Comment by BrunoCarvalho18** [comment]
Hi Mykola-Mokhnach,

I tried to install recent server version(1.10.0), but this version has a bug with recognize the locators.I'm using a physical device (tablet).

Thank you for help me.

Bruno Carvalho.

**Comment by imurchie** [comment]
Can you provide the Appium server log as well as the logcat logs?

**Comment by BrunoCarvalho18** [comment]
Hi Imurchie,

I has a logcat in gist: https://gist.github.com/BrunoCarvalho18/1464a805eda0a8c7f4bf37bf1115f37b

Do you want more information Imurchie ?

Thank you for help me.
Bruno Carvalho.

**Comment by imurchie** [comment]
All I see there is the output from your test.

In order to be of any help we need the server logs (from wherever Appium is running) and the device logs (run `adb logcat -d`).

**Comment by mykola-mokhnach** [comment]
> I tried to install recent server version(1.10.0), but this version has a bug with recognize the locators.

Do you have a reference to this bug?

> I has a logcat in gist: https://gist.github.com/BrunoCarvalho18/1464a805eda0a8c7f4bf37bf1115f37b

This is not the server log

**Comment by BrunoCarvalho18** [comment]
Hi Imurchie,

> In order to be of any help we need the server logs (from wherever Appium is running) and the device logs (run `adb logcat -d`).

Do you see the logcat in the below:
https://gist.github.com/BrunoCarvalho18/1f0a011eddd2d9587e348edf68f1a8e7

Thank you for help me.
Bruno Carvalho.

**Comment by mykola-mokhnach** [comment]
> https://gist.github.com/BrunoCarvalho18/e10b62205162d1ecbee7b106cf20e307

This is not a bug, but an issue with your client library, which is out of date and is not compatible with newer server releases. See https://github.com/search?q=org%3Aappium+%22Locator+Strategy+%27css+selector%27+is+not+supported+for+this+session%22&type=Issues

**Comment by BrunoCarvalho18** [comment]
Hi Mykola-mokhnach,

Thank you for help me, i'm solve the issue.

Bruno Carvalho.

**Comment by BrunoCarvalho18** [comment]
Hi Mykola-mokhnach,

In this case with Appium return Returned value cannot be converted to WebElement, this may be what I'm using WebDriver and not AndroidDriver ?

https://gist.github.com/BrunoCarvalho18/beec067270db08f93a546bf1f7174ad1

Thank you for help me.

Best Regards,
Bruno Carvalho.

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/issues/11827 is the same

**Comment by mykola-mokhnach** [comment]
> In this case with Appium return Returned value cannot be converted to WebElement, this may be what I'm using WebDriver and not AndroidDriver ?

Yes you are right. In W3C mode selenium API forcefully overrides some API calls to make them spec compatible, but this does not work in mobile environment. That is why descendants of AppiumDriver cancel most of these workarounds.
