### ISSUE TITLE
new Audio() API in JS gives error in appium: NotImplementedError: Method is not implemented

### ISSUE THREAD

**Issue by LayMuiToh** [appium/appium#11838]
## The problem

new Audio('../testdata/audio/show_me_basf.wav').play();

gives the error:
Method is not implemented
running
Error: An unknown server-side error occurred while processing the command.
    at execute(<Function>) - index.js:312:3

## Environment

Appium 1.9.1
macOS High Sierra 10.13.6
node --version
v9.1.0
iOS 12.0
iphone 6s
appium CLI
## Details
In my Javascript using webdriver.io, when I call the JS method

function playAudio() {
    new Audio('../testdata/audio/my.wav').play();
  }

 
      

## Link to Appium logs

https://gist.github.com/LayMuiToh/5db50bee0d1d1b44a3945ea8f09cf78a

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by dpgraham** [comment]
You need to switch to a web context.

**Comment by LayMuiToh** [comment]
Hi, This is for native app not hybrid. can I still use Web context API?

**Comment by mykola-mokhnach** [comment]
> can I still use Web context API?

no, this is impossible outside the web context
