### ISSUE TITLE
WebDriverAgentRunner -Failure trying to serialize updated test configuration." UserInfo={NSLocalizedDescription=Failure trying to serialize updated test configuration.

### ISSUE THREAD

**Issue by SoundaryaBhavanam** [appium/appium#11836]
## The problem

WebDriverAgentRunner is failing intermittently with the "serialize updated test configuration"

## Environment

* Appium version (or git revision) that exhibits the issue:1.10.0
* Last Appium version that did not exhibit the issue (if applicable):1.8.0
* Desktop OS/version used to run Appium: Mac OS
* Node.js version (unless using Appium.app|exe):6.4.1
* Mobile platform/version under test:IOS 12.x & IOS 9.3
* Real device or emulator/simulator:Real devices 
* Appium CLI or Appium.app|exe:

Selenium version tried with 3.3.1 And above all versions

## Details

[35m[Xcode][39m 2018-12-13 17:02:38.364 xcodebuild[78699:932304] Error Domain=com.apple.platform.iphoneos Code=-1 "Failure trying to serialize updated test configuration." UserInfo={NSLocalizedDescription=Failure trying to serialize updated test configuration.}
[35m[Xcode][39m 2018-12-13 17:02:38.364 xcodebuild[78699:932304] Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Failed to install or launch the test runner" UserInfo={NSLocalizedRecoverySuggestion=If you believe this error represents a bug, please attach the result bundle at /Users/mposautomation/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Test-WebDriverAgentRunner-2018.12.13_17-02-17--0500.xcresult, NSLocalizedDescription=Failed to install or launch the test runner, NSUnderlyingError=0x7fdb267f4060 {Error Domain=com.apple.platform.iphoneos Code=-1 "Failure trying to serialize updated test configuration." UserInfo={NSLocalizedDescription=Failure trying to serialize updated test configuration.}}}
[35m[Xcode][39m 
[35m[Xcode][39m 
[35m[Xcode][39m Testing failed:
[35m[Xcode][39m 
[35m[Xcode][39m 	Command CodeSign failed with a nonzero exit code
[35m[Xcode][39m 	WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: Failure trying to serialize updated test configuration.))
[35m[Xcode][39m ** TEST EXECUTE FAILED **
[35m[Xcode][39m 
[35m[Xcode][39m 
[35m[Xcode][39m Testing started on 'MPOS67'
[35m[Xcode][39m 
[35m[XCUITest][39m xcodebuild exited with code '65' and signal 'null'
[35m[XCUITest][39m Launching WebDriverAgent on the device

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

Node.json
{  
"capabilities":
      [
        {
          "deviceName": "iPad",
          "app": "",
          "maxInstances":1,
          "platformName":"iOS",
          "platform":"MAC"
        }
      ],
  "configuration":
  {
    "cleanUpCycle":5000,
    "timeout":300000,
    "nodeTimeout":300, 
    "browserTimeout": 240,
    "newSessionWaitTimeout":-1,
    "browserTimeout":240,
    "proxy":"org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
    "url":"http://:4723/wd/hub",
    "host":"",
    "port":4723,
    "maxSession":1,
    "register":true,
    "registerCycle":5000,
    "hubPort":4444,
    "hubHost":""
  }
}

https://gist.github.com/SoundaryaBhavanam/256adec706a85f64d807993570ea483d

With same code configuration appium 1.8.0 was good , with latest version i am facing this issue

**Comment by mykola-mokhnach** [comment]
WebDriverAgent at /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj cannot be compiled according to the log.
Make sure you can compile and deploy it to the phone manually via Xcode first. Also, it might be necessary to clear Xcode caches.

**Comment by SoundaryaBhavanam** [comment]
Cleared all the cache & Derived data in Xcode 
Installed manually WebDriverAgentRunner ->successfully installed (10 devices)
Note : When i connect 2 devices WebDriverAgentRunner is not failing with this issue 
But when i connect more than that facing this issue 
with 1.8.x Appium was good with 10 devices

**Comment by mykola-mokhnach** [comment]
> Installed manually WebDriverAgentRunner ->successfully installed (10 devices)
> Note : When i connect 2 devices WebDriverAgentRunner is not failing with this issue

This looks like an issue with WebDriverAgent/XCTest itself. I don't know any solution to it

**Comment by SoundaryaBhavanam** [comment]
Whom can help ?

**Comment by SoundaryaBhavanam** [comment]
Is any one looking into this issue ?

**Comment by mykola-mokhnach** [comment]
Closed as third party issue. Please report to https://github.com/facebook/WebDriverAgent/issues
