### ISSUE TITLE
Fix for driver.getKeyboard().sendKeys() with the W3C protocol

### ISSUE THREAD

**Issue by adrianth** [appium/appium#11843]
It is my understanding that, since the switch from JSONWP to the W3C protocol, the syntax `driver.getKeyboard().sendKeys()` is not supported anymore, the reason being that the underlying command is not present in the W3C specification. Can somebody please help answer these two questions:

- What is the recommended way to accomplish the same functionality with the latest version of Appium?
- Should the `driver.getKeyboard().sendKeys()` API be removed from all language bindings? My stance on this is that we should get the `driver.getKeyboard().sendKeys()` syntax working again through a workaround implemented in either language bindings or Appium code, but I am not familiar with the Appium internals and I might be wrong.

Any qualified opinion and advice on this issue is highly appreciated.

**Comment by mykola-mokhnach** [comment]
The workaround would be to get the active element and send keys to it (like in https://github.com/appium/appium/issues/11389). Regarding method removal: this is going to be tricky, since Appium may operate multiple protocol in the scope of a single sessions.

**Comment by Warren25** [comment]
Example syntax:

private MobileElement  username;
username.sendKeys("example");

**Comment by adrianth** [comment]
@mykola-mokhnach I tried the `driver.switchTo().activeElement()` and it looks like it gets the job done. I'm guessing it doesn't perfectly overlap the `driver.getKeyboard().sendKeys()` API, but it's probably a good enough replacement in most cases. Thanks for the suggestion.
