### ISSUE TITLE
On appium 1.11.0-beta.2 is failing to fetch dependencies for Appium iOS inspector

### ISSUE THREAD

**Issue by notihs** [appium/appium#11841]
## The problem

After going to the correct location, creating the dir as in the documentation if we run `./Scripts/bootstrap.sh -d` we get this output:
> Fetching dependencies

Only this. No progress at all and we get our command line back to us, immediately. 

As far as I understand this is what is responsible for letting us access Appium iOS inspector (which on this version has stopped working, because the server keeps returning 304 as response)
Reverting to 1.8.1 and the output for the same command is what is expected. Also, Appium iOS inspector is working fine there. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.11.0-beta.2
* Last Appium version that did not exhibit the issue (if applicable): 1.8.1
* Desktop OS/version used to run Appium: Mac OS High Sierra
* Node.js version (unless using Appium.app|exe): v10.8.0
* Mobile platform/version under test: iOS 11.4.1 (iPhone 5S)

## Link to Appium logs

https://gist.github.com/notihs/2a59bc22020e082956dfd703d778461b

**Comment by imurchie** [comment]
That means they are already downloaded. If you want to force them, delete the `Carthage` directory, and rerun the bootstrap script.

**Comment by mykola-mokhnach** [comment]
Looks like a local Carthage issue.

**Comment by notihs** [comment]
Somehow seems that that was the issue (with not fetching anything). Now I was able to fetch everything. However, I m still unable to get anything on iOS Appium Inspector. 
>Appium session at http://<myip:myport>/wd/hub is unreachable. Make sure your Appium test is running and click this message to retry.

I do have appium tests on debug AND server seems to be responding, but always with the 304 code. 
I can attach some more logs, which i think are exactly the same as the previous ones, but confirm please: 
https://gist.github.com/notihs/735ab0c08c2de04cb859df34f59b68ac

**Comment by mykola-mokhnach** [comment]
> 2018-12-14 12:53:11:347 - [debug] [XCUITest] Connection to WDA timed out
> 2018-12-14 12:53:11:347 - [debug] [iProxy] recv failed: Operation not permitted

WDA stops responding unexpectedly. Try to reboot the device and investigate the system logs.

**Comment by mykola-mokhnach** [comment]
I think it also makes sense to update the device itself. I saw problems earlier with iPhone5S, since this device has quite limited resources.

**Comment by notihs** [comment]
> > 2018-12-14 12:53:11:347 - [debug] [XCUITest] Connection to WDA timed out
> > 2018-12-14 12:53:11:347 - [debug] [iProxy] recv failed: Operation not permitted
> 
> WDA stops responding unexpectedly. Try to reboot the device and investigate the system logs.

That is something that happens quite often (WDA stops responding unexpectedly. Try to reboot the device and investigate the system logs.) Always has, since I remember. 
However, we never had any issues with iOS Appium Inspector. Sometimes seems like it is a bit "stubborn" which lead us to uninstall WDA and/or restart appium server. But after a bit of effort, usually it does work. 
Right now, doesn't seem like it. 
I will see if I can update the device. And if so, if it makes any difference or not

**Comment by notihs** [comment]
I've updated the device which now has iOS 12.1.1
Also, Xcode as been updated to 10.1.
Now the tests take minutes to start and some errors appear on appium logs: 

https://gist.github.com/notihs/5c1d09e712264d036100bea3569f5cb2

Some enqueue failures at 10:28:24, for example. Also, after every `[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body` I would get `ECONNRESET`. I have tried different approaches, like uninstalling WDA, re-using it, etc and the output on appium server is always this. Lots of `ECONNRESET` then nothing happens and enqueue failures start to appear. After some time the test finally runs. 
However, iOS inspector is still not working. Seems like the first time I request PageSource it returns a 200 and after that, every refresh keeps returning 304:

> 2018-12-17 10:30:18:321 - [HTTP] --> GET /wd/hub/sessions
> 2018-12-17 10:30:18:322 - [HTTP] {}
> 2018-12-17 10:30:18:322 - [debug] [GENERIC] Calling AppiumDriver.getSessions() with args: []
> 2018-12-17 10:30:18:323 - [debug] [GENERIC] Responding to client with driver.getSessions() result: [{"id":"2f49c636-1368-40f5-9b73-724ab2d6a819","capabilities":{"platformName":"ios","automationName":"XCuiTest","bundleId":"com.witsoftware.rcsplus.dev","deviceName":"iPhone5S","newCommandTimeout":3600,"noReset":true,"platformVersion":"11.2.5","udid":"1f91a71fb0622572b9f9afafc821d97186d13f1a"}}]
> 2018-12-17 10:30:18:324 - [HTTP] <-- GET /wd/hub/sessions 200 3 ms - 333
> 2018-12-17 10:30:18:325 - [HTTP] 
> 2018-12-17 10:30:38:295 - [HTTP] --> GET /wd/hub/sessions
> 2018-12-17 10:30:38:295 - [HTTP] {}
> 2018-12-17 10:30:38:295 - [debug] [GENERIC] Calling AppiumDriver.getSessions() with args: []
> 2018-12-17 10:30:38:296 - [debug] [GENERIC] Responding to client with driver.getSessions() result: [{"id":"2f49c636-1368-40f5-9b73-724ab2d6a819","capabilities":{"platformName":"ios","automationName":"XCuiTest","bundleId":"com.witsoftware.rcsplus.dev","deviceName":"iPhone5S","newCommandTimeout":3600,"noReset":true,"platformVersion":"11.2.5","udid":"1f91a71fb0622572b9f9afafc821d97186d13f1a"}}]
> 2018-12-17 10:30:38:297 - [HTTP] <-- GET /wd/hub/sessions 304 2 ms - -
> 2018-12-17 10:30:38:297 - [HTTP] 


On iOS Appium Inspector I always get the same error: `Appium session at http://172.18.4.72:4732/wd/hub is unreachable. Make sure your Appium test is running and click this message to retry.` even the first 200 received

**Comment by mykola-mokhnach** [comment]
Closed as third party issue. Please report to https://github.com/facebook/WebDriverAgent/issues
