### ISSUE TITLE
Android Driver : driver.getKeyboard().sendKeys("String") isn't working

### ISSUE THREAD

**Issue by lavellj12** [appium/appium#11845]
## The problem
I am trying to `.SendKeys` in YAML with no Resource ID. 

**Issue w/ Opentest** https://github.com/mcdcorp/opentest/issues/36 
I have a issue open with the creator of Opentest, and he directed me to 
> https://github.com/appium/appium/issues/10900

## Environment

* Appium version that exhibits the issue: 1.9.0
* Last Appium version that did not exhibit the issue: 1.7
* Desktop OS/version used to run Appium: Ubuntu 16.04 LTS
* Node.js version (unless using Appium.app|exe): 9.7.1
* Mobile platform/version under test: Samsung S7
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium Terminal

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Such behaviour is expected. `activeElement` API should be used instead
