### ISSUE TITLE
Appium return ClassLoader referenced unknown path: /data/app/io.appium.uiautomator2.server-1/lib/arm issue with uiautomator2

### ISSUE THREAD

**Issue by BrunoCarvalho18** [appium/appium#11842]
## The problem

Failed to run tests with appium-uiautomator2-server-debug-androidTest.apk and appium-uiautomator2-server-v0.1.5.apk automatically, appium stop the server and return " Original error: Could not proxy command to remote server. Original error: Error: socket hang up (WARNING: The server did not provide any stacktrace information)".

## Environment

Appium version (or git revision) that exhibits the issue: 1.8.1
Desktop OS/version used to run Appium: MacOS High Sierra
Node.js version (unless using Appium.app|exe):v10.14.2
Mobile platform/version under test: Android 7.0
Real device or emulator/simulator: Real Device(Tablet)
Appium CLI or Appium.app|exe: appium cli

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/BrunoCarvalho18/11cd731e8513a55f0f242cb3280e5dab

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
- Please use the most recent server version
- Make sure there are no leftovers from previous installations on the device under test

**Comment by BrunoCarvalho18** [comment]
Hi Mykola-Mokhnach,

Thank you.

Bruno Carvalho.
