### ISSUE TITLE
Enhancement Request : Get background color/ text color details in native context.

### ISSUE THREAD

**Issue by appuCES** [appium/appium#11852]
**The problem:**

I am testing an android native application whose theming and colors can be customized based on the user needs and I want to test the application theming and element/text colors. I know as of now it is not possible to fetch background color/ text color for native apps using Appium. But, I am curious to know why Appium is not able to fetch these details, as this can be done seamlessly in Selenium.

Please consider this issue as an enhancement request if it is possible to bring in this feature now. I strongly believe this will be helpful to many people who are looking at Appium as a mobile app testing solution from both UI and functionality perspective.

**Environment**

* Appium client version : 6.1.0
* Appium server version : 1.8.2
* Desktop OS/version used to run Appium: Windows 10
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Emulator

**Comment by mykola-mokhnach** [comment]
This is impossible to achieve, at least in UIA-based drivers. Espresso driver, though, contains [backdoor](https://github.com/appium/appium-espresso-driver/pull/317) implementation, which might be useful.
