### ISSUE TITLE
reset() crash, Error: Can't stop process; it's not currently running (cmd: 'xcrun simctl spawn log stream --style compact')

### ISSUE THREAD

**Issue by Artem-Kushch** [appium/appium#11858]
## The problem

Sometimes reset() method is crashed on appium (1.11.0-beta.2v Appium CLI )
When I use 1.9.1 desktop version, I don't have this problem

## Environment

* Appium version (or git revision) that exhibits the issue:1.11.0-beta.2
* Last Appium version that did not exhibit the issue (if applicable):1.9.1 Appium.app|
* Desktop OS/version used to run Appium: MacOS High Sierra 10.13.6
* Node.js version (unless using Appium.app|exe): v10.13.0
* Mobile platform/version under test: IOS
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Appium CLI 
* Xcode: 10.0

## Details

`[Xcode] 17:12:09.185 xcodebuild[65822:9704998] (LOG ARBITER) Discarding message, buffer is full.
[Xcode] 
[iOSLog] Cannot stop log capture process. Sending SIGKILL...
[debug] [MJSONWP (c123eb30)] Encountered internal error running command: Error: Can't stop process; it's not currently running (cmd: 'xcrun simctl spawn 3A374644-50EF-4308-BE4F-F80B808083FF log stream --style compact')
[debug] [MJSONWP (c123eb30)]     at SubProcess.stop (/usr/local/lib/node_modules/appium/node_modules/teen_process/lib/subprocess.js:206:13)
[debug] [MJSONWP (c123eb30)]     at IOSLog.killLogSubProcess (/usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/lib/device-log/ios-log.js:234:25)
[HTTP] <-- POST /wd/hub/session/c123eb30-1a20-4153-b26f-918164f1007a/appium/app/reset 500 32470 ms - 309
[HTTP] `

## Link to Appium logs

Full appium log: https://gist.github.com/Artem-Kushch/c114c63ba46a56e227d9e1deee72d71a
Full Session-WebDriverAgentRunner log: https://gist.github.com/Artem-Kushch/f46e48a364dc517b0f2a5160a072ee7c

## Code To Reproduce Issue [ Good To Have ]

Appium capabilities

```
                automationName: "XCUITest",
                platformName: "iOS",

                // Logs
                showIosLog: true,
                showXcodeLog: true,

                // Simulator
                platformVersion: config.iOSVersion,
                deviceName: config.deviceModelName,

                // WDA
                processArguments: '{"args": ["PORT"], "env": { "PORT": "8150" }}',
                wdaLocalPort: 8150,
                mjpegServerPort: 9150,
                useNewWDA: true,
                eventTimings: true,

                // Other
                bundleId: bundleId,
                useJSONSource: true,
                sessionOverride: true,
                connectHardwareKeyboard: false,
                waitForQuiescence: true,
                maxTypingFrequency: 15,

                // Timeouts & retries
                newCommandTimeout: 950,
                webkitResponseTimeout: 15000, 
                launchTimeout: 300000, 
                iosInstallPause: 8000,
                wdaStartupRetryInterval: 30000, 
                wdaLaunchTimeout: 180000, 
                wdaStartupRetries: 3,
                webviewConnectRetries: 20, 
                wdaConnectionTimeout: 480000, 
                app: path to .app
```

**Comment by mykola-mokhnach** [comment]
The fix has been published in appium@beta
