### ISSUE TITLE
Error : org.w3c.dom.DOMException: android.support.v7.app.ActionBar.ˋ

### ISSUE THREAD

**Issue by hiteshsh** [appium/appium#11854]
## The problem

I'm getting the error when I'm trying to find the below element by XPath.
 @AndroidFindBy(xpath = "//android.widget.TextView[@text='MORE']")
public MobileElement moreTile;

public void test(){
 wait.until(ExpectedConditions.visibilityOf(moreTile)).click();
}

I tried to print the page source and I think it can be because of the **`** character.
Page source : 
https://gist.github.com/hiteshsh/47183baf2f9d718c9fb35c401b2b5e0f

## Environment

* Appium version (or git revision) that exhibits the issue: v1.10.0
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: mac
* Node.js version (unless using Appium.app|exe): v11.4.0
* Mobile platform/version under test: Android API(28)
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium CLI and java client : f10393a

## Link to Appium logs
https://gist.github.com/hiteshsh/9d84b2917a2ca2a015029870f81c9cbb

**Comment by hiteshsh** [comment]
tried with Appium v1.11.0-beta.2. The problem still persists.
Below are the Appium logs:
https://gist.github.com/hiteshsh/c51951a18ec0a7e60e21d8df7cee9d4e

**Comment by mykola-mokhnach** [comment]
Can you please attach page source?

**Comment by hiteshsh** [comment]
please find the page source here:
https://gist.github.com/hiteshsh/b89ff51f289e46e3116e1c71520a100b

**Comment by mykola-mokhnach** [comment]
This is a bug in the standard android xpath engine implementation. I'll try to replace it with an alternative one

**Comment by mykola-mokhnach** [comment]
@hiteshsh Can you please check if https://github.com/appium/appium-uiautomator2-server/pull/236 works for you? [Here](https://github.com/appium/appium-uiautomator2-server) you can read on how to build custom server apk

**Comment by hiteshsh** [comment]
@mykola-mokhnach 
After building and using the custom server apk, I'm still getting the error:
https://gist.github.com/hiteshsh/8e37115aa64e52dca77f78aad4a8f636

**Comment by mykola-mokhnach** [comment]
Thanks for trying. These Apache libs are driving me crazy. Let me try another one

**Comment by mykola-mokhnach** [comment]
@hiteshsh Please try if https://github.com/appium/appium-uiautomator2-server/pull/237 works for you

**Comment by hiteshsh** [comment]
@mykola-mokhnach Tried the above one as well. Unfortunately, it is also throwing 'org.jdom2.input.JDOMParseException' exception. Logs attached here
https://gist.github.com/hiteshsh/49bee91cc1b19163418d1d457a680c75

**Comment by mykola-mokhnach** [comment]
It should work with the recent commit.

I don't really like to perform class name replacements, but it looks like Android only supports xpath search based on Apache harmony DOM implementation, which is buggy and does not work properly with Unicode characters allowed by XMLv1 standard. Unfortunately, I don't see any other open-source Apache/BSD-license based alternatives to it.

**Comment by hiteshsh** [comment]
@mykola-mokhnach Sorry didn't look into it again as I thought there won't be any further change done on it. Anyway, I'm trying it again but I'm still getting the same error. As per your comment on the [(https://github.com/appium/appium-uiautomator2-server/pull/237)] the normalizeTagNames will be disabled by default. To enable it do I need to add it in DesiredCapabilities ?

**Comment by mykola-mokhnach** [comment]
> I'm trying it again but I'm still getting the same error.

Are you sure you use the most recent version of the source? Can you please show the stack trace?

> To enable it do I need to add it in DesiredCapabilities

No this can be enabled/disabled in runtime via appium settings interface (driver.setSetting)

**Comment by hiteshsh** [comment]
I have performed the below steps.
1. took the latest pull from `mykola-mokhnach:jdom` branch
2. Executed command `gradle clean assembleServerDebug` to build the apk.
3. The replaced the apk in  UIautomator2 folder with the one I build.

I didn't use driver.setSetting yet. But won't that require a change in java-client(Setting) as well?

**Comment by mykola-mokhnach** [comment]
> I didn't use driver.setSetting yet. But won't that require a change in java-client(Setting) as well?

No it should not require any changes on the client side

**Comment by hiteshsh** [comment]
@mykola-mokhnach Yes, it worked now. I didn't get any error and it was able to find the element. Thanks for solving it.

**Comment by mykola-mokhnach** [comment]
It worked WITH this setting enabled or without?

**Comment by hiteshsh** [comment]
It worked with setting enabled only.
`CommandExecutionHelper.execute(driver, new AbstractMap.SimpleEntry<>("setSettings", prepareArguments("settings", prepareArguments("normalizeTagNames", true))));`

**Comment by mykola-mokhnach** [comment]
Can you please also attach the source tree generated if this setting is `on` and `off`?

**Comment by hiteshsh** [comment]
I'm sorry I didn't understand what you mean by source tree generated?

**Comment by mykola-mokhnach** [comment]
I mean the output of getPageSource

**Comment by hiteshsh** [comment]
Please find below the page source output:
With Setting on: https://gist.github.com/hiteshsh/0a8a8cea1f3d79e660b0f3bf4a40cb91
With Setting off: https://gist.github.com/hiteshsh/3f76102b24d507fafcf1ab5806389698

**Comment by mykola-mokhnach** [comment]
Thanks you for the assistance. The fix will be merged and published soon. After that I'll add the new setting to java client

**Comment by mykola-mokhnach** [comment]
The change has been published in appium@beta

**Comment by syddel** [comment]
Is it possible to set `normalizeTagNames` to `true` when starting Appium from the terminal?

**Comment by pankajpat2014** [comment]
> It worked with setting enabled only.
> `CommandExecutionHelper.execute(driver, new AbstractMap.SimpleEntry<>("setSettings", prepareArguments("settings", prepareArguments("normalizeTagNames", true))));`

I tried the same code, but its giving below error, can you please help me out what am I missing here,
The method prepareArguments(String, boolean) is undefined

and If I am trying	: CommandExecutionHelper.execute(driver, new AbstractMap.SimpleEntry<>("setSettings", prepareArguments("settings",MobileCommand.prepareArguments("normalizeTagNames", true))));
its giving below error 
The method prepareArguments(String, ImmutableMap<String,Object>) is undefined

**Comment by hiteshsh** [comment]
you can use the latest client and try below code:
`((AndroidDriver) driver).setSetting(Setting.NORMALIZE_TAG_NAMES,true);`
It worked for me.
