### ISSUE TITLE
WDA agent can't be uninstalled

### ISSUE THREAD

**Issue by Phoenix124** [appium/appium#11855]
## The problem

Hello
I need to uninstall WDA with `driver.removeApp("com.facebook.WebDriverAgentRunner")` command
Could you please tell why?
P.S also trying to uninstall using `xcrun simctl uninstall booted com.facebook.WebDriverAgentRunner `, but no success.

## Environment

* Appium 1.10.0
* iOS 12.1
* Emulator

**Comment by mykola-mokhnach** [comment]
Perhaps, the bundle id of the app has been changed? What is shown in the terminal if you list the installed apps?

**Comment by Phoenix124** [comment]
@mykola-mokhnach yep, i cahnge bundleID to com.apple.test.WebDriverAgentRunner-Runner and it works
