### ISSUE TITLE
Original error: Error: read ECONNRESET

### ISSUE THREAD

**Issue by machade** [appium/appium#11851]
## The problem

When using uiautomator2: Original error: Error: read ECONNRESET.

## Environment

* Appium version: 1.10.0
* Platform: Android 7.0
* Device: Samsung Tab A (Real)
* Node.js version: 10.14.2
* Appium java-client: 6.0.0

## Details

When running my tests, after a few of then occur this error:: 
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET (WARNING: The server did not provide any stacktrace information)

## Link to Appium logs
https://gist.github.com/machade/4a2388993fdaadc6bddff16791cfe10b
(I used "Logcat -d". if there is a better way do to it, pls let me know)

Appium server log
https://gist.github.com/machade/adebdc956241e5aa721e197f96e6fe8f

##NOTE
Using uiautomator works perfectly on devices with android 5.0

**Comment by mykola-mokhnach** [comment]
Please provide full server log. I don't see any issues in the provided system logs

**Comment by mykola-mokhnach** [comment]
`ECONNRESET` error happens if the connection with the server is unexpectedly terminated and might also be an indicator of internal adb/device/connection problems.

**Comment by machade** [comment]
> `ECONNRESET` error happens if the connection with the server is unexpectedly terminated and might also be an indicator of internal adb/device/connection problems.

**Comment by machade** [comment]
I have updated the xCode version and its not happening this error anymore.
