### ISSUE TITLE
[Android 5.1.1 - Appium Desktop 1.9.0]Could not obtain source -  UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command.","status":13}

### ISSUE THREAD

**Issue by quyennt44** [appium/appium#11867]
## The problem
I create a Capability in appium desktop then I start appium inspector. The application is opened on my device. Wait some minutes for the app loading, then I click the refresh button on appium to get element of my application but it can not get page source like this:
![capture2](https://user-images.githubusercontent.com/43987470/50214953-38981b80-03b4-11e9-8815-5fa8eb834d47.PNG)

## Environment

* Appium version: appium-desktop-setup-1.9.0.exe
* Desktop OS/version used to run Appium: Windows 10
* Node.js version: v8.12.0
* Mobile platform/version under test: Android 5.1.1
* Real device or emulator/simulator: Real device

## Link to Appium logs

[Appium log](https://github.com/quyennt44/logs/blob/master/appium-server-logs.txt)

## Code To Reproduce Issue [ Good To Have ]

> {
  "deviceName": "Samsung Galaxy J3",
  "udid": "42006fd2cc118400",
  "platformName": "Android",
  "platformVersion": "5.1.1",
  "appPackage": "host.exp.exponent",
  "appActivity": "host.exp.exponent.LauncherActivity",
  "noReset": "true",
  "fullReset": "false"
}

You can get the application on Google Play with name: Expo, icon like this:
![capture](https://user-images.githubusercontent.com/43987470/50214695-7a749200-03b3-11e9-8bc2-946961c90cc0.PNG)

Plz have a look.
Thanks!

**Comment by mykola-mokhnach** [comment]
Switch to uiautomator2

**Comment by quyennt44** [comment]
I tried uiautomator2 already but it can not open the application on my device then. 
Moreover, my android platform version is 5.1.1. uiautomator2 supports from version 6 only.

**Comment by mykola-mokhnach** [comment]
UIA2 supports Android API 21+
It is just more stable on API 23+, but we run our tests on 21.

> I tried uiautomator2 already but it can not open the application on my device then.
What is the server log?

**Comment by quyennt44** [comment]
This is the capability with UIA2:

> {
  "deviceName": "Samsung Galaxy J3",
  "udid": "42006fd2cc118400",
  "platformName": "Android",
  "platformVersion": "5.1.1",
  "appPackage": "host.exp.exponent",
  "appActivity": "host.exp.exponent.LauncherActivity",
  "noReset": "true",
  "fullReset": "false",
  "automationName": "uiautomator2"
}
When I start the server, it hangs out like this:
![capture3](https://user-images.githubusercontent.com/43987470/50263403-249df980-0448-11e9-8413-68a8a7f5d00d.PNG)

This is the log file:
[Log](https://github.com/quyennt44/logs/blob/master/appium-server-logs2.txt)

**Comment by mykola-mokhnach** [comment]
> Starting 'C:\Users\Teko\AppData\Local\Android\android-sdk\build-tools\28.0.3\apksigner.bat' with args '["verify","--print-certs","C:\\Program Files (x86)\\Appium\\resources\\app\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v2.8.0.apk"]'

The code freezes on signature verification step. It might something is broken on your machine. Try to execute the command above manually and check the output

**Comment by quyennt44** [comment]
I waited over one hour but nothing happened.
This is what printed out when I execute the command manually. I don't know what to do with it:
![capture4](https://user-images.githubusercontent.com/43987470/50268447-66856a80-045d-11e9-8a85-e7d95f2eb475.PNG)

**Comment by mykola-mokhnach** [comment]
Maybe the appium's call is blocked by some third-party software, like an antivirus. Try to change the machine/switch to Linux or MacOS

**Comment by quyennt44** [comment]
Hmm. Itried the version appium-desktop-1.9.1-x86_64.AppImage on Ubuntu 16.04 but this error happened:
[Log](https://github.com/quyennt44/logs/blob/master/appium-server-logs4.txt)
- I tried this already: 
run Appium from terminal and run sessions using Custom Server
> sudo ./appium-desktop-1.8.2-x86_64.AppImage

- I tried to change permission also but can not:
![selection_004](https://user-images.githubusercontent.com/43987470/50322761-34314700-0509-11e9-8aa0-1ab378c40eea.png)

**Comment by mykola-mokhnach** [comment]
sudo should never be used. appium service must work from non-privileged user account. Also, use npm to install the service.

**Comment by quyennt44** [comment]
I don't see an useful advice here. What's the root problem?

**Comment by quyennt44** [comment]
For more information, this is what I get when I  use uiautomatorviewer tool to view element:
![selection_005](https://user-images.githubusercontent.com/43987470/50329246-e88e9580-0528-11e9-8f91-127d60b89cd7.png)

**Comment by KazuCocoa** [comment]
Does espresso driver help this?

**Comment by mykola-mokhnach** [comment]
Closed as inactive

**Comment by marktilly** [comment]
@DaisyLi2015 @quyennt44 
You are not alone. I have same 
"Could not obtain source:{"cause":{"sessionId":....status:13" error with the accompanying "An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command, status:13."

I am connecting to an Android v8.1.0 device
Appium 1.10.0
mac OS Mojave 10.14.1
Java 1.8.0_192
Node.js 11.3

My application under test is a React native app. Are either or both of you testing React native?

**Comment by VasilijSviridov** [comment]
same issue within hybrid app
