### ISSUE TITLE
[Appium iOS] - WDA timed out and force quits the created WDA XCUITest driver session

### ISSUE THREAD

**Issue by arjunrv0** [appium/appium#11860]
## The problem

WDA timed out and force quits the created WDA XCUITest driver session

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0
* Last Appium version that did not exhibit the issue (if applicable): 1.10.0
* Desktop OS/version used to run Appium: MacOS Mojave 10.14
* Node.js version (unless using Appium.app|exe): v11.3.0
* Mobile platform/version under test: iOS/12.0
* Real device or emulator/simulator: Real device (iPhone X)
* Appium CLI or Appium.app|exe: Appium CLI & Appium.app

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/arjunrv0/85c16491a9b5a72815f7d0b5729152ec

## Code To Reproduce Issue [ Good To Have ]

package com.automate.ola.ios.tests;

import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.testng.annotations.*;

import io.appium.java_client.AppiumDriver;
import io.appium.java_client.ios.IOSDriver;
import io.appium.java_client.remote.MobileCapabilityType;

public class DeviceSetup extends BaseTest 
{
	
      static AppiumDriver prepareDeviceForTest() throws Exception{
	  	  
	  DesiredCapabilities capabilities = new DesiredCapabilities();
	 
	  capabilities.setCapability("platformName", "iOS");
	  capabilities.setCapability("deviceName", "iPhone X");
	  capabilities.setCapability("app", "/Users/arjun.ravi/Desktop/test.app");
	  capabilities.setCapability("automationName","XCUITest");
	  capabilities.setCapability("xcodeOrgId", "SCV2VP7XA6");
	  capabilities.setCapability("xcodeSigningId","iOS Developer");
	  capabilities.setCapability("platformVersion","12.0");
	  capabilities.setCapability("udid","5cd825dfa94b3e8aaf5ae5bd6b56e5424417300e");
	  capabilities.setCapability("autoAcceptAlerts", true);
	  capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 30000);
	  driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
	  driver.manage().timeouts().implicitlyWait(15, TimeUnit.SECONDS);
	  return driver;
      }

}

**Comment by mykola-mokhnach** [comment]
The attached log is not very useful. Can you also attach the device log?
Most likely the problem has nothing to do with Appium and is an XcTest/WebDriverAgent issue

**Comment by arjunrv0** [comment]
[appium_ios_log.txt](https://github.com/appium/appium/files/2693850/appium_ios_log.txt)
After launching the test app the WDA times out and the created session is deleted automatically.

PFA log file for the complete logs

[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n\n  },\n  \"sessionId\" : \"A7EAE14E-D25D-4276-A323-83C21FB99F27\",\n  \"status\" : 0\n}"
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [iOSLog] Stopping iOS log capture
[debug] [XCUITest] Connection to WDA timed out
[debug] [iProxy] recv failed: Operation not permitted
[debug] [BaseDriver] Event 'quitSessionFinished' logged at 1545206843330 (13:37:23 GMT+0530 (India Standard Time))
[debug] [MJSONWP (9756283b)] Received response: null
[debug] [MJSONWP (9756283b)] But deleting session, so not returning
[debug] [MJSONWP (9756283b)] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/9756283b-f5f8-4e23-8a70-db7965171046 200 2353 ms - 76

**Comment by Siddh010** [comment]
Type using  "clearSystemFiles" : true

([debug] [XCUITest] Not clearing log files. Use clearSystemFiles capability to turn on)

**Comment by mykola-mokhnach** [comment]
closed as third party issue. You can also try to describe the issue at https://github.com/facebook/WebDriverAgent
