### ISSUE TITLE
[Appium][Android] --> Cannot send keys to pickerwheel

### ISSUE THREAD

**Issue by raghu1992** [appium/appium#11862]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe): v8.9.1
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

![image](https://user-images.githubusercontent.com/23488313/50165327-ba078500-02b2-11e9-98d6-281b585859f6.png)

I couldn't send keys to my pickerwheel in Android.

I tried the following,

#1
@AndroidFindBy(uiAutomator = "new UiSelector().resourceId(\"tavie.patient.pso.fr.prod.v3:id/wheelPicker\")")
	public List<WebElement> weightWheelPicker;

weightWheelPicker.get(0).sendKeys("1");

#2 
@AndroidFindBy(xpath ="//android.view.View[@index='0']")
	public WebElement weightWheelPicker;

weightWheelPicker.sendKeys("2");

**Comment by mykola-mokhnach** [comment]
UiAutomator2 does not provide any methods for changing picker values. You could try to either swipe it or switch to Espresso driver.
