### ISSUE TITLE
 Failed to install ipa via appium 1.10.0

### ISSUE THREAD

**Issue by kokahkhk** [appium/appium#11887]
## The problem
In previously version such as 1.9.1,it's works.Currently upgrade to appium 1.10,failed to install ipa fie.I just tried to manual install works fine with command "ios-deploy --id xxxx  xx.ipa",but via appium to install app which was broken.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.10

**Comment by saikrishna321** [comment]
Please post full server logs.

**Comment by kokahkhk** [comment]
attached log

[35m[Appium][39m Appium support for versions of node < 8 has been deprecated and will be removed in a future version. Please upgrade!
[35m[Appium][39m Welcome to Appium v1.10.0
[35m[Appium][39m Non-default server args:
[35m[Appium][39m   port: 4923
[35m[Appium][39m   bootstrapPort: 4933
[35m[Appium][39m Appium REST http interface listener started on 0.0.0.0:4923
[35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub[39m
[35m[HTTP][39m [90m{}[39m
[debug] [35m[HTTP][39m No route found. Setting content type to 'text/plain'
[35m[HTTP][39m [37m<-- GET /wd/hub [39m[33m404[39m [90m7 ms - 49[39m
[35m[HTTP][39m [90m[39m
[35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub[39m
[35m[HTTP][39m [90m{}[39m
[debug] [35m[HTTP][39m No route found. Setting content type to 'text/plain'
[35m[HTTP][39m [37m<-- GET /wd/hub [39m[33m404[39m [90m2 ms - 49[39m
[35m[HTTP][39m [90m[39m
[35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub[39m
[35m[HTTP][39m [90m{}[39m
[debug] [35m[HTTP][39m No route found. Setting content type to 'text/plain'
[35m[HTTP][39m [37m<-- GET /wd/hub [39m[33m404[39m [90m2 ms - 49[39m
[35m[HTTP][39m [90m[39m
[35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[35m[HTTP][39m [90m{"desiredCapabilities":{"app":"/Users/qa/jk/workspace/iOS/test/apps/testMobileApp.ipa","noReset":"true","xcodeOrgId":"2KWAGZM2TW","bundleId":"com.testApp.ibl","deviceName":"iPhone 7","launchTimeout":"60000","xcodeSigningId":"iPhone Developer","wdaLaunchTimeout":"60000","newCommandTimeout":"120","platformVersion":"11.2.5","automationName":"XCUITest","useNewWDA":"false","platformName":"iOS","udid":"038422b884c2cb3bdca850bb662f4aab46ef5dd1"},"capabilities":{"alwaysMatch":{"appium:app":"/Users/qa/jk/workspace/iOS/test/apps/testMobileApp.ipa","appium:automationName":"XCUITest","appium:bundleId":"com.testApp.ibl","appium:deviceName":"iPhone 7","appium:launchTimeout":"60000","appium:newCommandTimeout":"120","appium:noReset":"true","platformName":"ios","appium:platformVersion":"11.2.5","appium:udid":"038422b884c2cb3bdca850bb662f4aab46ef5dd1","appium:useNewWDA":"false","appium:wdaLaunchTimeout":"60000","appium:xcodeOrgId":"2KWAGZM2TW","appium:xcodeSigningId":"iPh[39m
[debug] [35m[W3C][39m Calling AppiumDriver.createSession() with args: [{"app":"/Users/qa/jk/workspace/iOS/test/apps/testMobileApp.ipa","noReset":"true","xcodeOrgId":"2KWAGZM2TW","bundleId":"com.testApp.ibl","deviceName":"iPhone 7","launchTimeout":"60000","xcodeSigningId":"iPhone Developer","wdaLaunchTimeout":"60000","newCommandTimeout":"120","platformVersion":"11.2.5","automationName":"XCUITest","useNewWDA":"false","platformName":"iOS","udid":"038422b884c2cb3bdca850bb662f4aab46ef5dd1"},null,{"alwaysMatch":{"appium:app":"/Users/qa/jk/workspace/iOS/test/apps/testMobileApp.ipa","appium:automationName":"XCUITest","appium:bundleId":"com.testApp.ibl","appium:deviceName":"iPhone 7","appium:launchTimeout":"60000","appium:newCommandTimeout":"120","appium:noReset":"true","platformName":"ios","appium:platformVersion":"11.2.5","appium:udid":"038422b884c2cb3bdca850bb662f4aab46ef5dd1","appium:useNewWDA":"false","appium:wdaLaunchTimeout":"60000","appium:xcodeOrgId":"2KWAGZM2TW","appium:xcodeSigningId":"iPhone Developer"},"firstMatch":[{}]}]
[debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1545283905382 (13:31:45 GMT+0800 (CST))
[35m[BaseDriver][39m Number capability passed in as string. Functionality may be compromised.
[35m[BaseDriver][39m Boolean capability passed in as string. Functionality may be compromised.
[35m[Appium][39m Creating new XCUITestDriver (v2.104.0) session
[35m[Appium][39m Capabilities:
[35m[Appium][39m   platformName: ios
[35m[Appium][39m   app: /Users/qa/jk/workspace/iOS/test/apps/testMobileApp.ipa
[35m[Appium][39m   automationName: XCUITest
[35m[Appium][39m   bundleId: com.testApp.ibl
[35m[Appium][39m   deviceName: iPhone 7
[35m[Appium][39m   launchTimeout: 60000
[35m[Appium][39m   newCommandTimeout: 120
[35m[Appium][39m   noReset: true
[35m[Appium][39m   platformVersion: 11.2.5
[35m[Appium][39m   udid: 038422b884c2cb3bdca850bb662f4aab46ef5dd1
[35m[Appium][39m   useNewWDA: false
[35m[Appium][39m   wdaLaunchTimeout: 60000
[35m[Appium][39m   xcodeOrgId: 2KWAGZM2TW
[35m[Appium][39m   xcodeSigningId: iPhone Developer
[debug] [35m[BaseDriver][39m W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP desired capabilities {"app":"/Users/qa/jk/worksp... were provided
[debug] [35m[BaseDriver][39m Creating session with W3C capabilities: {"alwaysMatch":{"platformNa...
[35m[BaseDriver][39m Number capability passed in as string. Functionality may be compromised.
[35m[BaseDriver][39m Boolean capability passed in as string. Functionality may be compromised.
[35m[BaseDriver][39m Boolean capability passed in as string. Functionality may be compromised.
[35m[BaseDriver][39m Number capability passed in as string. Functionality may be compromised.
[35m[BaseDriver][39m Capability 'noReset' changed from string to boolean. This may cause unexpected behavior
[35m[BaseDriver][39m Capability 'useNewWDA' changed from string to boolean. This may cause unexpected behavior
[35m[BaseDriver][39m Capability 'newCommandTimeout' changed from string ('120') to integer (120). This may cause unexpected behavior
[35m[BaseDriver][39m Capability 'wdaLaunchTimeout' changed from string ('60000') to integer (60000). This may cause unexpected behavior
[35m[BaseDriver][39m Session created with session id: dd8ce899-ba14-4145-8743-1306e3cbd34e
[debug] [35m[XCUITest][39m Current user: 'qa'
[debug] [35m[XCUITest][39m Available devices: 038422b884c2cb3bdca850bb662f4aab46ef5dd1
[debug] [35m[XCUITest][39m Creating iDevice object with udid '038422b884c2cb3bdca850bb662f4aab46ef5dd1'
[35m[XCUITest][39m Determining device to run tests on: udid: '038422b884c2cb3bdca850bb662f4aab46ef5dd1', real device: true
[debug] [35m[XCUITest][39m Xcode version set to '9.2' (tools v9.2.0.0.1.1510905681)
[debug] [35m[XCUITest][39m iOS SDK Version set to '11.2'
[debug] [35m[BaseDriver][39m Event 'xcodeDetailsRetrieved' logged at 1545283905594 (13:31:45 GMT+0800 (CST))
[35m[BaseDriver][39m Using local app '/Users/qa/jk/workspace/iOS/test/apps/testMobileApp.ipa'
[debug] [35m[BaseDriver][39m Unzipping '/Users/qa/jk/workspace/iOStest/apps/testMobileApp.ipa'
[debug] [35m[BaseDriver][39m Extracted 3182 item(s) from '/Users/qa/jk/workspace/iOS/test/apps/testMobileApp.ipa'
[debug] [35m[BaseDriver][39m Matched 3181 item(s) in the extracted archive. Assuming 'Payload/testMobileApp.app' is the correct bundle
[35m[BaseDriver][39m Unzipped local app to '/var/folders/xy/vbr20wjs109_cknqw9rpqgdh0000gp/T/20181120-31008-14ll5pi.j91tuo9a4i/Payload/testMobileApp.app'
[debug] [35m[BaseDriver][39m Event 'appConfigured' logged at 1545283909134 (13:31:49 GMT+0800 (CST))
[debug] [35m[XCUITest][39m Checking whether app '/var/folders/xy/vbr20wjs109_cknqw9rpqgdh0000gp/T/20181120-31008-14ll5pi.j91tuo9a4i/Payload/testMobileApp.app' is actually present on file system
[debug] [35m[XCUITest][39m App is present
[debug] [35m[BaseDriver][39m Event 'resetStarted' logged at 1545283909135 (13:31:49 GMT+0800 (CST))
[debug] [35m[XCUITest][39m Reset: fullReset not set. Leaving as is
[debug] [35m[BaseDriver][39m Event 'resetComplete' logged at 1545283909135 (13:31:49 GMT+0800 (CST))
[debug] [35m[iOSLog][39m Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [35m[iOSLog][39m Starting iOS device log capture with: 'idevicesyslog'
[debug] [35m[XCUITest][39m Crash reports root '/Users/qa/Library/Logs/CrashReporter/MobileDevice/iPhone' does not exist. Got nothing to gather.
[debug] [35m[BaseDriver][39m Event 'logCaptureStarted' logged at 1545283909334 (13:31:49 GMT+0800 (CST))
[35m[XCUITest][39m Setting up real device
[debug] [35m[XCUITest][39m Verifying application platform
[debug] [35m[XCUITest][39m CFBundleSupportedPlatforms: ["iPhoneOS"]
[debug] [35m[XCUITest][39m Installing '/var/folders/xy/vbr20wjs109_cknqw9rpqgdh0000gp/T/20181120-31008-14ll5pi.j91tuo9a4i/Payload/testMobileApp.app' on device with UUID '038422b884c2cb3bdca850bb662f4aab46ef5dd1'...
[debug] [35m[XCUITest][39m Stdout: '[....] Waiting for iOS device to be connected
[debug] [35m[XCUITest][39m [....] Using 038422b884c2cb3bdca850bb662f4aab46ef5dd1 (D10AP, iPhone 7, iphoneos, arm64) a.k.a. 'iPhone'.
[debug] [35m[XCUITest][39m ------ Install phase ------
[debug] [35m[XCUITest][39m [  0%] Found 038422b884c2cb3bdca850bb662f4aab46ef5dd1 (D10AP, iPhone 7, iphoneos, arm64) a.k.a. 'iPhone' connected through USB, beginning install
[debug] [35m[XCUITest][39m [  5%] Copying /var/folders/xy/vbr20wjs109_cknqw9rpqgdh0000gp/T/20181120-31008-14ll5pi.j91tuo9a4i/Payload/testMobileApp.app/META-INF/ to device
[debug] [35m[XCUITest][39m [  5%] Copying /var/folders/xy/vbr20wjs109_cknqw9rpqgdh0000gp/T/20181120-31008-14ll5pi.j91tuo9a4i/Payload/testMobileApp.app/META-INF/com.apple.ZipMetadata.plist to device
[debug] [35m[XCUITest][39m [  5%] Copying /var/folders/xy/vbr20wjs109_cknqw9rpqgdh0000gp/T/20181120-31008-14ll5pi.j91tuo9a4i/Payload/testMobileApp.app/_CodeSignature/ to device
[debug] [35m[XCUITest][39m [  5%] Copying /var/folders/xy/vbr20wjs109_cknqw9rpqgdh0000gp/T/20181120-31008-14ll5pi.j91tuo9a4i/Payload/testMobileApp.app/_CodeSignature/CodeResources to device
[debug] [35m[XCUITest][39m [  5%] Copying /var/folders/xy/vbr20wjs109_cknqw9rpqgdh0000gp/T/20181120-31008-14ll5pi.j91tuo9a4i/Payload/testMobileApp.app/about.html to device
[debug] [35m[XCUITest][39m [  5%] Copying /var/folders/xy/vbr20wjs109_cknqw9rpqgdh0000gp/T/20181120-31008-14ll5pi.j91tuo9a4i/Payload/testMobileApp.app/address.plist to device
[debug] [35m[XCUITest][39m [  5%] Copying /var/folders/xy/vbr20wjs109_cknqw9rpqgdh0000gp/T/20181120-31008-14ll5pi.j91tuo9a4i/Payload/testMobileApp.app/AlipaySDK.bundle/ to device
[debug] [35m[XCUITest][39m [  5%] Copying /var/folders/xy/vbr20wjs109_cknqw9rpqgdh0000gp/T/20181120-31008-14ll5pi.j91tuo9a4i/Payload/testMobileApp.app/AlipaySDK.bundle/.svn/ to device
[debug] [35m[XCUITest][39m [  5%] Copying /var/folders/xy/vbr20wjs109_cknqw9rpqgdh0000gp/T/20181120-31008-14ll5pi.j91tuo9a4i/Payload/testMobileApp.app/AlipaySDK.bundle/bar@2x.png to device
[debug] [35m[XCUITest][39m [  5%] Copying /var/folders/xy/vbr20wjs109_cknqw9rpqgdh0000gp/T/20181120-31008-14ll5pi.j91tuo9a4i/Payload/testMobileApp.app/AlipaySDK.bundle/refresh@2x.png to device
[debug] [35m[XCUITest][39m [  5%] Copying /var/folders/xy/vbr20wjs109_cknqw9rpqgdh0000gp/T/20181120-31008-14ll5pi.j91tuo9a4i/Payload/testMobileApp.app/AlipaySDK.bundle/refresh_click@2x.png to device
[debug] [35m[XCUITest][39m [  5%] Copying /var/folders/xy/vbr20wjs109_cknqw9rpqgdh0000gp/T/20181120-31008-14ll5pi.j91tuo9a4i/Payload/testMobileApp.app/AlipaySDK.bundle/shutdown@2x.png to device
[debug] [35m[XCUITest][39m [  5%] Copying /var/folders/xy/vbr20wjs109_cknqw9rpqgdh0000gp/T/20181120-31008-14ll5pi.j91tuo9a4i/Payload/testMobileApp.app/AlipaySDK.bundle/shutdown_click@2x.png to device
[debug] [35m[XCUITest][39m [  5%] Copying /var/folders/xy/vbr20wjs109_cknqw9rpqgdh0000gp/T/20181120-31008-14ll5pi.j91tuo9a4i/Payload/testMobileApp.app/allCityAreas.json to device
[debug] [35m[XCUITest][39m [  5%] Copying /var/folders/xy/vbr20wjs109_cknqw9rpqgdh0000gp/T/20181120-31008-14ll5pi.j91tuo9a4i/Payload/testMobileApp.app/AMap.bundle/ to device
[debug] [35m[XCUITest][39m [  5%] Copying /var/folders/xy/vbr20wjs109_cknqw9rpqgdh0000gp/T/20181120-31008-14ll5pi.j91tuo9a4i/Payload/testMobileApp.app/AMap.bundle/AMap3D.bundle/ to device
[debug] [35m[XCUITest][39m [  5%] Copying /var/folders/xy/vbr20wjs109_cknqw9rpqgdh0000gp/T/20181120-31008-14ll5pi.j91tuo9a4i/Payload/testMobileApp.app/AMap.bundle/AMap3D.bundle/3d_sky_day.data to device
[debug] [35m[XCUITest][39m [  5%] Copying /var/folders/xy/vbr20wjs109_cknqw9rpqgdh0000gp/T/20181120-31008-14ll5pi.j91tuo9a4i/Payload/testMobileApp.app/AMap.bundle/AMap3D.bundle/3d_sky_night.data to device
[debug] [35m[XCUITest][39m [  5%] Copying /var/folders/xy/vbr20wjs109_cknqw9rpqgdh0000gp/T/20181120-31008-14ll5pi.j91tuo9a4i/Payload/testMobileApp.app/AMap.bundle/AMap3D.bundle/3dlandscape.xml to device
[debug] [35m[XCUITest][39m [  5%] Copying /var/folders/xy/vbr20wjs109_cknqw9rpqgdh0000gp/T/20181120-31008-14ll5pi.j91tuo9a4i/Payload/testMobileApp.app/AMap.bundle/AMap3D.bundle/3dportrait.xml to device
[debug] [35m[XCUITest][39m [  5%] Copying /var/folders/xy/
......................
[debug] [35m[XCUITest][39m [ 49%] Copying /var/folders/xy/vbr20wjs109_cknqw9rpqgdh0000gp/T/20181120-31008-14ll5pi.j91tuo9a4i/Payload/testMobileApp.app/YZFPassGuardCtrlBundle.bundle/τ║»µò░σ¡ùµîëΘö«µ¿¬µ¥┐@2x.png to device
[debug] [35m[XCUITest][39m [ 52%] CreatingStagingDirectory
[debug] [35m[XCUITest][39m [ 57%] ExtractingPackage
[debug] [35m[XCUITest][39m [ 60%] InspectingPackage
[debug] [35m[XCUITest][39m [ 60%] TakingInstallLock
[debug] [35m[XCUITest][39m [ 65%] PreflightingApplication
[debug] [35m[XCUITest][39m [ 65%] InstallingEmbeddedProfile
[debug] [35m[XCUITest][39m [ 70%] VerifyingApplication
[debug] [35m[XCUITest][39m '. Stderr: '2018-12-20 13:33:08.601 ios-deploy[31029:7542724] [ !! ] Error 0xe8008017: A signed resource has been added, modified, or deleted. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)
[debug] [35m[XCUITest][39m '.
[debug] [35m[XCUITest][39m Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [35m[iOSLog][39m Stopping iOS log capture
[debug] [35m[BaseDriver][39m Event 'newSessionStarted' logged at 1545283988803 (13:33:08 GMT+0800 (CST))
[debug] [35m[W3C][39m Encountered internal error running command: Error: Could not install app: 'Command 'ios-deploy --id 038422b884c2cb3bdca850bb662f4aab46ef5dd1 --bundle /var/folders/xy/vbr20wjs109_cknqw9rpqgdh0000gp/T/20181120-31008-14ll5pi.j91tuo9a4i/Payload/testMobileApp.app' exited with code 253'
[debug] [35m[W3C][39m     at IOSDeploy.install (/usr/local/lib/node_modules/appium/node_modules/._appium-xcuitest-driver@2.104.0@appium-xcuitest-driver/lib/ios-deploy.js:40:13)
[35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[31m500[39m [90m83443 ms - 1019[39m
[35m[HTTP][39m [90m[39m
[35m[XCUITest][39m Error: Could not install app: 'Command 'ios-deploy --id 038422b884c2cb3bdca850bb662f4aab46ef5dd1 --bundle /var/folders/xy/vbr20wjs109_cknqw9rpqgdh0000gp/T/20181120-31008-14ll5pi.j91tuo9a4i/Payload/testMobileApp.app' exited with code 253'
[35m[XCUITest][39m     at IOSDeploy.install (/usr/local/lib/node_modules/appium/node_modules/._appium-xcuitest-driver@2.104.0@appium-xcuitest-driver/lib/ios-deploy.js:40:13)

**Comment by gaierlj** [comment]
I meet the same problem, how to Solve？
