### ISSUE TITLE
Not able to start ios driver on real device, gives error Error: The desired capabilities must include either an app or a bundleId for iOS

### ISSUE THREAD

**Issue by sumeetpanjabi** [appium/appium#11888]
## The problem

I'm trying to run cucumber tests on my ios device using Appium. I have the framework setup where I am passing some capabilities to config. I have passed the app path in capabilities and that is also picked in APP_PATH variable. But while running the tests, Appium is not able to pick up the app and it is giving error "Error: The desired capabilities must include either an app or a bundleId for iOS"
On the Android end, I am able to run the tests, there is no issue

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Desktop OS/version used to run Appium: MAC OS Mojave 10.14
* Node.js version (unless using Appium.app|exe): v10.11.0
* Mobile platform/version under test: 12.0
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

## Details

Setting the variable before running the test
export CONNECTED_DEVICE_IDS=90fbc4d5c63183d28820bd54309726111568741c
export APP_TYPE=ios
export APP_PATH=~/Downloads/AppName.ipa
export MODE=e2e
export REGION=IN
export CHECK_ANALYTICS=true

## Link to Appium logs

https://gist.github.com/sumeetpanjabi/4c93ba365930b038cda3adf2e03c1ba2

**Comment by KazuCocoa** [comment]
Your capability sending to appium server was below. Please make sure your testing tool to send correct capability.

> 2018-12-21 09:46:41 INFO  DriverUtils:19 - [null] - Appium server url - http://0.0.0.0:9242/wd/hub
> 2018-12-21 09:46:41 INFO  DriverUtils:19 - [null] -     with capabilities - Capabilities {appPackage: com.vuclip.viu, automationName: XCuiTest, deviceName: iPhone 6s plus, platformName: ios, showIOSLog: true, showXcodeLog: true}
> [XCUITest] Error: The desired capabilities must include either an app or a bundleId for iOS

http://appium.io/docs/en/drivers/ios-xcuitest/index.html
