### ISSUE TITLE
Unable to remove port forward - Appium 1.10.0

### ISSUE THREAD

**Issue by danwoodbury** [appium/appium#11886]
## The problem

I am trying to setup our automated testing environment on Travis CI using Appium and an Android Emulator but I keep getting the error `Unable to remove port forward 'Error executing adbExec. Original error: 'Command '/usr/local/android-sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp\:8200' exited with code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''` no matter what I try, there are various other issues about this but none of the attempted fixes are working for me.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Ubuntu 14.04
* Node.js version (unless using Appium.app|exe): 0.10.36
* Mobile platform/version under test: android
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs
https://gist.github.com/danwoodbury/787a23bd3aeed686df59fde37ce97d44

No code as such but the travis ci is located in this gist: https://gist.github.com/danwoodbury/787a23bd3aeed686df59fde37ce97d44

Thanks in advance

**Comment by mykola-mokhnach** [comment]
This rather looks like a problem in the client code. The session is being unexpectedly deleted while it is being initialised. 

Also, it is quite strange that x86 emulator works on Travis. Last time we tried its nodes didn't support KVM virtualization required for this type of emulator.

**Comment by danwoodbury** [comment]
When you say client, do you mean npm appium client? Im new to the appium world so this is all very new to me.

As with virtualization, you can make it run with the `-no-accel` option. Although im not sure how well it work as i cant get appium to launch correctly.

**Comment by mykola-mokhnach** [comment]
Did you try to execute the stuff on local machine?
We also run our tests on Travis and observe no issues: https://travis-ci.org/appium/appium-uiautomator2-driver/builds/469004500

**Comment by mykola-mokhnach** [comment]
> Node.js version (unless using Appium.app|exe): 0.10.36

The minimum supported NodeJS version is 8

Otherwise i don't observe anything suspicious in the log. You can also check the logcat output for more glues.

**Comment by KazuCocoa** [comment]
You also can increase the number of timeouts for avd if it happens only on Travis (emulator) environment.

- avdLaunchTimeout
- avdReadyTimeout
- adbExecTimeout

http://appium.io/docs/en/writing-running-appium/caps/

**Comment by anujtiwari24** [comment]
If this is not resolved then please try to change the App Activity and try all the activities of the app. I was facing the same error and for me it worked after changing the app activity.

**Comment by akalankaudesh** [comment]
> > Node.js version (unless using Appium.app|exe): 0.10.36
> 
> The minimum supported NodeJS version is 8
> 
> Otherwise i don't observe anything suspicious in the log. You can also check the logcat output for more glues.

hey bro , i have the same issue. appium desktop works fine, bit in npm try to start appium server it getting the same error
