### ISSUE TITLE
iOS class chain returns wrong element

### ISSUE THREAD

**Issue by cosminstirbu** [appium/appium#11881]
## The problem

In our iOS application we have a list of cells and each cell contains a label that can have an empty string value. By default those empty string labels are not exposed by XCUITest.

So if for instance we're running the following command:

```
[HTTP] --> POST /wd/hub/session/d5a4903f-b359-4b42-b016-00e91443cd80/element
[HTTP] {"using":"-ios class chain","value":"**/XCUIElementTypeCell[`name == \"SearchResultsVehicleCell\"`][1]/XCUIElementTypeStaticText[`name == \"GradeLabel\"`]"}
```

if GradeLabel is empty in the first cell, then this should return no such element.

However, it returns the first GradeLabel that actually has some text.

I would expect this to work similar to `findElementFromElement` which works correctly.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 10.14
* Node.js version (unless using Appium.app|exe): v8.6.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: cli

**Comment by mykola-mokhnach** [comment]
Please provide a page source example and describe what you want to achieve with your locator relatively to this page source.

**Comment by cosminstirbu** [comment]
In this page source - https://gist.github.com/cosminstirbu/d008133b76b7228c5491e9bb901a5f9d

I would expect the class chain above to return no such element, but instead it returns the first GradeLabel which is contained by the 7th SearchResultsVehicleCell.

**Comment by mykola-mokhnach** [comment]
I have checked the current implementation and this proposal makes sense. However, I'll need your help to test the fix.

**Comment by mykola-mokhnach** [comment]
Please checkout the changes from https://github.com/appium/WebDriverAgent/pull/135/files to your local source, redeploy WDA and check if the lookup works as expected now

**Comment by cosminstirbu** [comment]
I have checked out the changes and I can confirm that the issue was fixed.

NoSuchElementError is now returned for the class chain above.

Thank you.

**Comment by mykola-mokhnach** [comment]
The fix has been published in appium@beta
