### ISSUE TITLE
org.openqa.selenium.WebDriverException: It is impossible to create a new session because 'createSession' which takes HttpClient, InputStream and long was not found or it is not accessible

### ISSUE THREAD

**Issue by MondyLau** [appium/appium#11889]
Hi Team,
I am seeking help for below issue.

## The problem

Whenever I am running my tests on localhost getting error -  It is impossible to create a new session because 'createSession' which takes HttpClient, InputStream and long was not found or it is not accessible

## Environment

* Appium version : v1.10.0
* Selenium-server-standalone-3.14.0
* os.version: Windows 10(64 bit)
* Node.js version : v10.14.2
* Mobile platform/version : Android /5.1.1
* Real device : mi3
* Java-client-6.1.0
* TestNG version: 6.14.2
* Wechat version: 6.7.3

## Details

This has been happening constantly from past two weeks . 
I have tried following different threads before posting here.
Have switched to and fro to different Java client versions but with no success.
 I used to change another real device but it getting error as mentioned above. 
Any help is appreciated.
Thanks in advance.

## Link to Appium logs

C:\Users\mondy>appium -a 127.0.0.1 -p 4723 -U la595528 --no-reset
[Appium] Welcome to Appium v1.10.0
[Appium] Non-default server args:
[Appium]   address: 127.0.0.1
[Appium]   udid: la595528
[Appium]   noReset: true
[Appium] Deprecated server args:
[Appium]   -U,--udid => --default-capabilities '{"udid":"la595528"}'
[Appium]   --no-reset => --default-capabilities '{"noReset":true}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   udid: la595528
[Appium]   noReset: true
[Appium] Appium REST http interface listener started on 127.0.0.1:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"appActivity":".ui.LauncherUI","appPackage":"com.tencent.mm","goog:chromeOptions":{"androidProcess":"com.tencent.mm:tools","args":[],"extensions":[]},"platformVersion":"5.1.1","browserName":"chrome","unicodeKeyboard":"true","platformName":"Android","deviceName":"1a595528","resetKeyboard":"true"},"capabilities":{"alwaysMatch":{"appium:appActivity":".ui.LauncherUI","appium:appPackage":"com.tencent.mm","browserName":"chrome","appium:deviceName":"1a595528","goog:chromeOptions":{"androidProcess":"com.tencent.mm:tools","args":[],"extensions":[]},"platformName":"android","appium:platformVersion":"5.1.1","appium:resetKeyboard":"true","appium:unicodeKeyboard":"true"},"firstMatch":[{}]}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"appActivity":".ui.LauncherUI","appPackage":"com.tencent.mm","goog:chromeOptions":{"androidProcess":"com.tencent.mm:tools","args":[],"extensions":[]},"platformVersion":"5.1.1","browserName":"chrome","unicodeKeyboard":"true","platformName":"Android","deviceName":"1a595528","resetKeyboard":"true"},null,{"alwaysMatch":{"appium:appActivity":".ui.LauncherUI","appium:appPackage":"com.tencent.mm","browserName":"chrome","appium:deviceName":"1a595528","goog:chromeOptions":{"androidProcess":"com.tencent.mm:tools","args":[],"extensions":[]},"platformName":"android","appium:platformVersion":"5.1.1","appium:resetKeyboard":"true","appium:unicodeKeyboard":"true"},"firstMatch":[{}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1545362152516 (11:15:52 GMT+0800 (GMT+08:00))
[BaseDriver] The capabilities ["udid","noReset"] are not standard capabilities and should have an extension prefix
[Appium] Creating new AndroidDriver (v4.8.0) session
[Appium] Capabilities:
[Appium]   browserName: chrome
[Appium]   goog:chromeOptions: {
[Appium]     androidProcess: com.tencent.mm:tools
[Appium]     args: {
[Appium]     }
[Appium]     extensions: {
[Appium]     }
[Appium]   }
[Appium]   platformName: android
[Appium]   appActivity: .ui.LauncherUI
[Appium]   appPackage: com.tencent.mm
[Appium]   deviceName: 1a595528
[Appium]   platformVersion: 5.1.1
[Appium]   resetKeyboard: true
[Appium]   unicodeKeyboard: true
[Appium]   udid: la595528
[Appium]   noReset: true
[debug] [BaseDriver] W3C capabilities {"alwaysMatch":{"browserNam... and MJSONWP desired capabilities {"udid":"la595528","noReset... were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"browserNam...
[BaseDriver] Boolean capability passed in as string. Functionality may be compromised.[BaseDriver] Boolean capability passed in as string. Functionality may be compromised.[BaseDriver] Capability 'unicodeKeyboard' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Capability 'resetKeyboard' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by appium: goog:chromeOptions.
[AndroidDriver] Error: The desired should not include both of an 'appPackage' and a 'browserName'
[AndroidDriver]     at Object.wrappedLogger.errorAndThrow (C:\Users\mondy\AppData\Roaming\npm\node_modules\appium\node_modules\_appium-support@2.25.0@appium-support\lib\logging.js:78:13)
[AndroidDriver]     at Object.helpers.validateDesiredCaps (C:\Users\mondy\AppData\Roaming\npm\node_modules\appium\node_modules\_appium-android-driver@4.8.0@appium-android-driver\lib\android-helpers.js:720:14)
[AndroidDriver]     at AndroidDriver.validateDesiredCaps (C:\Users\mondy\AppData\Roaming\npm\node_modules\appium\node_modules\_appium-android-driver@4.8.0@appium-android-driver\lib\driver.js:488:20)
[AndroidDriver]     at AndroidDriver.commands.createSession (C:\Users\mondy\AppData\Roaming\npm\node_modules\appium\node_modules\_appium-base-driver@3.13.1@appium-base-driver\lib\basedriver\commands\session.js:45:8)
[AndroidDriver]     at AndroidDriver.createSession (C:\Users\mondy\AppData\Roaming\npm\node_modules\appium\node_modules\_appium-android-driver@4.8.0@appium-android-driver\lib\driver.js:61:43)
[AndroidDriver]     at AppiumDriver.createSession (C:\Users\mondy\AppData\Roaming\npm\node_modules\appium\lib\appium.js:292:43)
[AndroidDriver]     at process._tickCallback (internal/process/next_tick.js:68:7)
[debug] [AndroidDriver] Shutting down Android driver
[debug] [AndroidDriver] Called deleteSession but bootstrap wasn't active
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1545362152609 (11:15:52 GMT+0800 (GMT+08:00))
[debug] [W3C] Encountered internal error running command: Error: The desired should not include both of an 'appPackage' and a 'browserName'
[debug] [W3C]     at Object.wrappedLogger.errorAndThrow (C:\Users\mondy\AppData\Roaming\npm\node_modules\appium\node_modules\_appium-support@2.25.0@appium-support\lib\logging.js:78:13)
[debug] [W3C]     at Object.helpers.validateDesiredCaps (C:\Users\mondy\AppData\Roaming\npm\node_modules\appium\node_modules\_appium-android-driver@4.8.0@appium-android-driver\lib\android-helpers.js:720:14)
[debug] [W3C]     at AndroidDriver.validateDesiredCaps (C:\Users\mondy\AppData\Roaming\npm\node_modules\appium\node_modules\_appium-android-driver@4.8.0@appium-android-driver\lib\driver.js:488:20)
[debug] [W3C]     at AndroidDriver.commands.createSession (C:\Users\mondy\AppData\Roaming\npm\node_modules\appium\node_modules\_appium-base-driver@3.13.1@appium-base-driver\lib\basedriver\commands\session.js:45:8)
[debug] [W3C]     at AndroidDriver.createSession (C:\Users\mondy\AppData\Roaming\npm\node_modules\appium\node_modules\_appium-android-driver@4.8.0@appium-android-driver\lib\driver.js:61:43)
[debug] [W3C]     at AppiumDriver.createSession (C:\Users\mondy\AppData\Roaming\npm\node_modules\appium\lib\appium.js:292:43)
[debug] [W3C]     at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2388) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[HTTP] <-- POST /wd/hub/session 500 114 ms - 830

## Code To Reproduce Issue [ Good To Have ]

import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.android.AndroidElement;
import io.appium.java_client.remote.AndroidMobileCapabilityType;
import io.appium.java_client.remote.MobileCapabilityType;
import java.net.URL;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.annotations.Test;

public class iteshop {
	
	public static AndroidDriver<AndroidElement> driver;
	@Test
	public void startapp() throws Exception{
	DesiredCapabilities capabilities=new DesiredCapabilities();
	capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "1a595528");
	capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "5.1.1");
	capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
	capabilities.setCapability(AndroidMobileCapabilityType.APP_PACKAGE, "com.tencent.mm");
	capabilities.setCapability(AndroidMobileCapabilityType.APP_ACTIVITY,".ui.LauncherUI");
	capabilities.setCapability("unicodeKeyboard", "true");
	capabilities.setCapability("resetKeyboard", "true");

	ChromeOptions options = new ChromeOptions();
        options.setExperimentalOption("androidProcess", "com.tencent.mm:tools");
	capabilities.setCapability(ChromeOptions.CAPABILITY, options);

	driver=new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
	Thread.sleep(2000);
	}	
}

**Comment by mykola-mokhnach** [comment]
> [AndroidDriver] Error: The desired should not include both of an 'appPackage' and a 'browserName'

The error message is pretty clear. You must fix the capabilities.
