### ISSUE TITLE
WebDriverAgentRunner: Failed to run tests: Timed out trying to establish connection to IDE.

### ISSUE THREAD

**Issue by kawerty2** [appium/appium#11884]
## The problem

I try to run xcuitest driver on a real device with running command:
## Environment

* Appium version: I tried several: 1.11.0-beta.2/1.10.0/1.9.1
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2
* Desktop OS/version used to run Appium: 1.10.0
* Node.js version (unless using Appium.app|exe): v11.5.0
* Mobile platform/version under test: 12.0/12.1
* Real device or emulator/simulator: iPhone 8/iPhoneX 
* XCode v.: 10.1 (10B61)

## Link to Appium logs

```
==== Successfully wrote Manifest cache to /var/folders/z4/wczkmbk53dq5jr0xn_9sjpy80000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.oh7jOD/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
2018-12-20 17:54:15.138882+0200 WebDriverAgentRunner-Runner[544:173749] Running tests...
objc[544]: Class GCDAsyncSocketPreBuffer is implemented in both /private/var/containers/Bundle/Application/2570DFAE-3894-4747-9DD3-A132D41339A4/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/CocoaAsyncSocket.framework/CocoaAsyncSocket (0x105250578) and /private/var/containers/Bundle/Application/2570DFAE-3894-4747-9DD3-A132D41339A4/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer (0x1051e9358). One of the two will be used. Which one is undefined.
objc[544]: Class GCDAsyncReadPacket is implemented in both /private/var/containers/Bundle/Application/2570DFAE-3894-4747-9DD3-A132D41339A4/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/CocoaAsyncSocket.framework/CocoaAsyncSocket (0x1052505c8) and /private/var/containers/Bundle/Application/2570DFAE-3894-4747-9DD3-A132D41339A4/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer (0x1051e93a8). One of the two will be used. Which one is undefined.
objc[544]: Class GCDAsyncWritePacket is implemented in both /private/var/containers/Bundle/Application/2570DFAE-3894-4747-9DD3-A132D41339A4/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/CocoaAsyncSocket.framework/CocoaAsyncSocket (0x105250618) and /private/var/containers/Bundle/Application/2570DFAE-3894-4747-9DD3-A132D41339A4/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer (0x1051e93f8). One of the two will be used. Which one is undefined.
objc[544]: Class GCDAsyncSpecialPacket is implemented in both /private/var/containers/Bundle/Application/2570DFAE-3894-4747-9DD3-A132D41339A4/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/CocoaAsyncSocket.framework/CocoaAsyncSocket (0x105250668) and /private/var/containers/Bundle/Application/2570DFAE-3894-4747-9DD3-A132D41339A4/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer (0x1051e9448). One of the two will be used. Which one is undefined.
objc[544]: Class GCDAsyncSocket is implemented in both /private/var/containers/Bundle/Application/2570DFAE-3894-4747-9DD3-A132D41339A4/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/CocoaAsyncSocket.framework/CocoaAsyncSocket (0x1052506b8) and /private/var/containers/Bundle/Application/2570DFAE-3894-4747-9DD3-A132D41339A4/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer (0x1051e9498). One of the two will be used. Which one is undefined.
Failed to run tests: Timed out trying to establish connection to IDE.
Dumping buffered debug messages:
====================
17:54:15.141 WebDriverAgentRunner-Runner[544:173749] Linked XCTest.framework from /var/containers/Bundle/Application/2570DFAE-3894-4747-9DD3-A132D41339A4/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest, built with Xcode 1010(10B43a), modified on Thursday, December 20, 2018 at 16:43:40 Eastern European Standard Time
XCTest.framework bundle version: 14460.20
17:54:15.142 WebDriverAgentRunner-Runner[544:173749] System uptime: 22:25:54
17:54:15.142 WebDriverAgentRunner-Runner[544:173749] Process arguments: (
    "/var/containers/Bundle/Application/2570DFAE-3894-4747-9DD3-A132D41339A4/WebDriverAgentRunner-Runner.app/WebDriverAgentRunner-Runner",
    "-NSTreatUnknownArgumentsAsOpen",
    NO,
    "-ApplePersistenceIgnoreState",
    YES
)
17:54:15.142 WebDriverAgentRunner-Runner[544:173749] Process environment: {
    "CA_ASSERT_MAIN_THREAD_TRANSACTIONS" = 0;
    "CA_DEBUG_TRANSACTIONS" = 0;
    "CFFIXED_USER_HOME" = "/private/var/mobile/Containers/Data/Application/3AB0A67F-BD76-4C73-87BD-88D715648EB6";
    CLASSIC = 1;
    "DYLD_FRAMEWORK_PATH" = "/private/var/containers/Bundle/Application/2570DFAE-3894-4747-9DD3-A132D41339A4/WebDriverAgentRunner-Runner.app/Frameworks:";
    "DYLD_LIBRARY_PATH" = "/private/var/containers/Bundle/Application/2570DFAE-3894-4747-9DD3-A132D41339A4/WebDriverAgentRunner-Runner.app/Frameworks";
    HOME = "/private/var/mobile/Containers/Data/Application/3AB0A67F-BD76-4C73-87BD-88D715648EB6";
    LOGNAME = mobile;
    "MJPEG_SERVER_PORT" = "";
    "MTC_CRASH_ON_REPORT" = 1;
    NSUnbufferedIO = YES;
    "OS_ACTIVITY_DT_MODE" = YES;
    PATH = "/usr/bin:/bin:/usr/sbin:/sbin";
    SHELL = "/bin/sh";
    "SQLITE_ENABLE_THREAD_ASSERTIONS" = 1;
    TMPDIR = "/private/var/mobile/Containers/Data/Application/3AB0A67F-BD76-4C73-87BD-88D715648EB6/tmp/";
    "UPGRADE_TIMESTAMP" = "";
    USER = mobile;
    "USE_PORT" = "";
    "WDA_PRODUCT_BUNDLE_IDENTIFIER" = "";
    XCTestConfigurationFilePath = "/private/var/mobile/Containers/Data/Application/3AB0A67F-BD76-4C73-87BD-88D715648EB6/tmp/WebDriverAgentRunner-D61E6F9A-7F30-449C-820C-E2F292850956.xctestconfiguration";
    "XPC_FLAGS" = 0x0;
    "XPC_SERVICE_NAME" = "UIKitApplication:com.apple.test.WebDriverAgentRunner-Runner[0x306e][65]";
    "__CF_USER_TEXT_ENCODING" = "0x1F5:0:0";
}
17:54:15.142 WebDriverAgentRunner-Runner[544:173749] App Sandbox active: YES
17:54:15.142 WebDriverAgentRunner-Runner[544:173749] Loading test bundle at: file:///private/var/containers/Bundle/Application/2570DFAE-3894-4747-9DD3-A132D41339A4/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest
17:54:15.202 WebDriverAgentRunner-Runner[544:173749] Finished loading test bundle
17:54:15.202 WebDriverAgentRunner-Runner[544:173749] Readying IDE session
17:54:15.203 WebDriverAgentRunner-Runner[544:173749] Creating future for 'Exchange protocol versions with daemon' with timeout 15.00
17:54:15.204 WebDriverAgentRunner-Runner[544:173749] <XCTWaiter: 0x28188a0a0, state: XCTWaiterStateInProgress> entering wait loop for 15.00s with expectations: `Exchange protocol versions with daemon`
17:54:15.204 WebDriverAgentRunner-Runner[544:173768] <XCTWaiter: 0x28188a0a0, state: XCTWaiterStateSucceeded>: cancelWaiting
17:54:15.204 WebDriverAgentRunner-Runner[544:173749] <XCTWaiter: 0x28188a0a0, state: XCTWaiterStateSucceeded> done waiting
17:54:15.205 WebDriverAgentRunner-Runner[544:173749] Canceling watchdog for <XCTWaiter: 0x28188a0a0, state: XCTWaiterStateInProgress>.
17:54:15.205 WebDriverAgentRunner-Runner[544:173749] <XCTWaiter: 0x28188a0a0, state: XCTWaiterStateSucceeded> cleaning up `Exchange protocol versions with daemon`
17:54:15.205 WebDriverAgentRunner-Runner[544:173749] Got daemon protocol version 26
17:54:15.205 WebDriverAgentRunner-Runner[544:173749] Requesting IDE connection transport
17:54:15.205 WebDriverAgentRunner-Runner[544:173749] <XCTWaiter: 0x28188a100, state: XCTWaiterStateInProgress> entering wait loop for 60.00s with expectations: `Transport for IDE session acquired`
17:55:15.209 WebDriverAgentRunner-Runner[544:173749] <XCTWaiter: 0x28188a100, state: XCTWaiterStateInProgress> done waiting
17:55:15.209 WebDriverAgentRunner-Runner[544:173749] Canceling watchdog for <XCTWaiter: 0x28188a100, state: XCTWaiterStateInProgress>.
17:55:15.210 WebDriverAgentRunner-Runner[544:173749] <XCTWaiter: 0x28188a100, state: XCTWaiterStateFailed> reporting timed out failure with Transport for IDE session acquired
17:55:15.210 WebDriverAgentRunner-Runner[544:173749] <XCTWaiter: 0x28188a100, state: XCTWaiterStateFailed> cleaning up `Transport for IDE session acquired`
====================
2018-12-20 17:55:22.039 xcodebuild[6835:85497] [MT] IDETestOperationsObserverDebug: 72.236 elapsed -- Testing started completed.
2018-12-20 17:55:22.039 xcodebuild[6835:85497] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2018-12-20 17:55:22.039 xcodebuild[6835:85497] [MT] IDETestOperationsObserverDebug: 72.236 sec, +72.236 sec -- end
2018-12-20 17:55:22.040 xcodebuild[6835:85497] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted, NSUnderlyingError=0x7fca68e24730 {Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Test runner exited before starting test execution." UserInfo={NSLocalizedDescription=Test runner exited before starting test execution., NSLocalizedRecoverySuggestion=If you believe this error represents a bug, please attach the result bundle at /Users/anastasiia.dedikova/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Test-WebDriverAgentRunner-2018.12.20_17-54-07-+0200.xcresult}}}

Testing failed:
	WebDriverAgentRunner-Runner.app (544) encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted. (Underlying error: Test runner exited before starting test execution.))
** TEST FAILED **
```

**Comment by mykola-mokhnach** [comment]
Are you able to deploy and execute WebDriverAgent on the device under test manually from Xcode?

**Comment by kawerty2** [comment]
@mykola-mokhnach It executes with the same error:
`2018-12-20 18:47:09.725022+0200 WebDriverAgentRunner-Runner[556:180288] Running tests...
objc[556]: Class GCDAsyncSocketPreBuffer is implemented in both /private/var/containers/Bundle/Application/C8D9F7E6-945E-4EC6-BD56-2C3E4BD70D23/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/CocoaAsyncSocket.framework/CocoaAsyncSocket (0x108d7c578) and /private/var/containers/Bundle/Application/C8D9F7E6-945E-4EC6-BD56-2C3E4BD70D23/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer (0x108d15358). One of the two will be used. Which one is undefined.
objc[556]: Class GCDAsyncReadPacket is implemented in both /private/var/containers/Bundle/Application/C8D9F7E6-945E-4EC6-BD56-2C3E4BD70D23/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/CocoaAsyncSocket.framework/CocoaAsyncSocket (0x108d7c5c8) and /private/var/containers/Bundle/Application/C8D9F7E6-945E-4EC6-BD56-2C3E4BD70D23/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer (0x108d153a8). One of the two will be used. Which one is undefined.
objc[556]: Class GCDAsyncWritePacket is implemented in both /private/var/containers/Bundle/Application/C8D9F7E6-945E-4EC6-BD56-2C3E4BD70D23/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/CocoaAsyncSocket.framework/CocoaAsyncSocket (0x108d7c618) and /private/var/containers/Bundle/Application/C8D9F7E6-945E-4EC6-BD56-2C3E4BD70D23/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer (0x108d153f8). One of the two will be used. Which one is undefined.
objc[556]: Class GCDAsyncSpecialPacket is implemented in both /private/var/containers/Bundle/Application/C8D9F7E6-945E-4EC6-BD56-2C3E4BD70D23/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/CocoaAsyncSocket.framework/CocoaAsyncSocket (0x108d7c668) and /private/var/containers/Bundle/Application/C8D9F7E6-945E-4EC6-BD56-2C3E4BD70D23/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer (0x108d15448). One of the two will be used. Which one is undefined.
objc[556]: Class GCDAsyncSocket is implemented in both /private/var/containers/Bundle/Application/C8D9F7E6-945E-4EC6-BD56-2C3E4BD70D23/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/CocoaAsyncSocket.framework/CocoaAsyncSocket (0x108d7c6b8) and /private/var/containers/Bundle/Application/C8D9F7E6-945E-4EC6-BD56-2C3E4BD70D23/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer (0x108d15498). One of the two will be used. Which one is undefined.
Failed to run tests: Timed out trying to establish connection to IDE.
Dumping buffered debug messages:
====================
18:47:09.731 WebDriverAgentRunner-Runner[556:180288] Linked XCTest.framework from /var/containers/Bundle/Application/C8D9F7E6-945E-4EC6-BD56-2C3E4BD70D23/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest, built with Xcode 1010(10B43a), modified on Thursday, December 20, 2018 at 16:43:40 Eastern European Standard Time
XCTest.framework bundle version: 14460.20
18:47:09.732 WebDriverAgentRunner-Runner[556:180288] System uptime: 23:18:49
18:47:09.732 WebDriverAgentRunner-Runner[556:180288] Process arguments: (
    "/var/containers/Bundle/Application/C8D9F7E6-945E-4EC6-BD56-2C3E4BD70D23/WebDriverAgentRunner-Runner.app/WebDriverAgentRunner-Runner",
    "-NSTreatUnknownArgumentsAsOpen",
    NO,
    "-ApplePersistenceIgnoreState",
    YES
)
18:47:09.732 WebDriverAgentRunner-Runner[556:180288] Process environment: {
    "CA_ASSERT_MAIN_THREAD_TRANSACTIONS" = 0;
    "CA_DEBUG_TRANSACTIONS" = 0;
    "CFFIXED_USER_HOME" = "/private/var/mobile/Containers/Data/Application/3EF101F8-EAFB-479C-8BFB-66800650CDFF";
    CLASSIC = 1;
    "DYLD_FRAMEWORK_PATH" = "/private/var/containers/Bundle/Application/C8D9F7E6-945E-4EC6-BD56-2C3E4BD70D23/WebDriverAgentRunner-Runner.app/Frameworks:";
    "DYLD_LIBRARY_PATH" = "/private/var/containers/Bundle/Application/C8D9F7E6-945E-4EC6-BD56-2C3E4BD70D23/WebDriverAgentRunner-Runner.app/Frameworks";
    HOME = "/private/var/mobile/Containers/Data/Application/3EF101F8-EAFB-479C-8BFB-66800650CDFF";
    LOGNAME = mobile;
    "MJPEG_SERVER_PORT" = "";
    "MTC_CRASH_ON_REPORT" = 1;
    NSUnbufferedIO = YES;
    "OS_ACTIVITY_DT_MODE" = YES;
    PATH = "/usr/bin:/bin:/usr/sbin:/sbin";
    SHELL = "/bin/sh";
    "SQLITE_ENABLE_THREAD_ASSERTIONS" = 1;
    TMPDIR = "/private/var/mobile/Containers/Data/Application/3EF101F8-EAFB-479C-8BFB-66800650CDFF/tmp/";
    "UPGRADE_TIMESTAMP" = "";
    USER = mobile;
    "USE_PORT" = "";
    "WDA_PRODUCT_BUNDLE_IDENTIFIER" = "";
    XCTestConfigurationFilePath = "/private/var/mobile/Containers/Data/Application/3EF101F8-EAFB-479C-8BFB-66800650CDFF/tmp/WebDriverAgentRunner-E365DFA8-1389-49F0-854D-AD1E30980253.xctestconfiguration";
    "XPC_FLAGS" = 0x0;
    "XPC_SERVICE_NAME" = "UIKitApplication:com.apple.test.WebDriverAgentRunner-Runner[0xe5e1][65]";
    "__CF_USER_TEXT_ENCODING" = "0x1F5:0:0";
}
18:47:09.732 WebDriverAgentRunner-Runner[556:180288] App Sandbox active: YES
18:47:09.732 WebDriverAgentRunner-Runner[556:180288] Loading test bundle at: file:///private/var/containers/Bundle/Application/C8D9F7E6-945E-4EC6-BD56-2C3E4BD70D23/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest
18:47:09.927 WebDriverAgentRunner-Runner[556:180288] Finished loading test bundle
18:47:09.928 WebDriverAgentRunner-Runner[556:180288] Readying IDE session
18:47:09.931 WebDriverAgentRunner-Runner[556:180288] Creating future for 'Exchange protocol versions with daemon' with timeout 15.00
18:47:09.932 WebDriverAgentRunner-Runner[556:180288] <XCTWaiter: 0x280d30070, state: XCTWaiterStateInProgress> entering wait loop for 15.00s with expectations: `Exchange protocol versions with daemon`
18:47:09.933 WebDriverAgentRunner-Runner[556:180368] <XCTWaiter: 0x280d30070, state: XCTWaiterStateSucceeded>: cancelWaiting
18:47:09.934 WebDriverAgentRunner-Runner[556:180288] <XCTWaiter: 0x280d30070, state: XCTWaiterStateSucceeded> done waiting
18:47:09.934 WebDriverAgentRunner-Runner[556:180288] Canceling watchdog for <XCTWaiter: 0x280d30070, state: XCTWaiterStateInProgress>.
18:47:09.934 WebDriverAgentRunner-Runner[556:180288] <XCTWaiter: 0x280d30070, state: XCTWaiterStateSucceeded> cleaning up `Exchange protocol versions with daemon`
18:47:09.934 WebDriverAgentRunner-Runner[556:180288] Got daemon protocol version 26
18:47:09.935 WebDriverAgentRunner-Runner[556:180288] Requesting IDE connection transport
18:47:09.935 WebDriverAgentRunner-Runner[556:180288] <XCTWaiter: 0x280d2c100, state: XCTWaiterStateInProgress> entering wait loop for 60.00s with expectations: `Transport for IDE session acquired`
18:48:09.937 WebDriverAgentRunner-Runner[556:180288] <XCTWaiter: 0x280d2c100, state: XCTWaiterStateInProgress> done waiting
18:48:09.937 WebDriverAgentRunner-Runner[556:180288] Canceling watchdog for <XCTWaiter: 0x280d2c100, state: XCTWaiterStateInProgress>.
18:48:09.938 WebDriverAgentRunner-Runner[556:180288] <XCTWaiter: 0x280d2c100, state: XCTWaiterStateFailed> reporting timed out failure with Transport for IDE session acquired
18:48:09.938 WebDriverAgentRunner-Runner[556:180288] <XCTWaiter: 0x280d2c100, state: XCTWaiterStateFailed> cleaning up `Transport for IDE session acquired`
====================`

**Comment by mykola-mokhnach** [comment]
Then it is probably an issue with the device/Xcode itself. What if you try to change the device or use another host machine?

**Comment by kawerty2** [comment]
@mykola-mokhnach I have the newest Xcode (10.1 (10B61)) and I ran it on two different machines and two different devices.

**Comment by mykola-mokhnach** [comment]
Try to also get the system log. Perhaps there is some useful information in that one

**Comment by kawerty2** [comment]
@mykola-mokhnach like what logs? 
How can I get it?

The issue still is not resolved.

**Comment by mykola-mokhnach** [comment]
https://www.google.com/search?q=iphone+xcode+get+logs

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by manishboricha** [comment]
Getting above mentioned error while running the app and app crashes

Logs 

objc[584]: Class GCDAsyncSocketPreBuffer is implemented in both /private/var/containers/Bundle/Application/44902459-79AB-4DF8-BE55-1C5312B6D070/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/CocoaAsyncSocket.framework/CocoaAsyncSocket (0x104590578) and /private/var/containers/Bundle/Application/44902459-79AB-4DF8-BE55-1C5312B6D070/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer (0x1043c9330). One of the two will be used. Which one is undefined.
[Xcode] 
[Xcode] objc[584]: Class GCDAsyncReadPacket is implemented in both /private/var/containers/Bundle/Application/44902459-79AB-4DF8-BE55-1C5312B6D070/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/CocoaAsyncSocket.framework/CocoaAsyncSocket (0x1045905c8) and /private/var/containers/Bundle/Application/44902459-79AB-4DF8-BE55-1C5312B6D070/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer (0x1043c9380). One of the two will be used. Which one is undefined.
[Xcode] objc[584]: Class GCDAsyncWritePacket is implemented in both /private/var/containers/Bundle/Application/44902459-79AB-4DF8-BE55-1C5312B6D070/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/CocoaAsyncSocket.framework/CocoaAsyncSocket (0x104590618) and /private/var/containers/Bundle/Application/44902459-79AB-4DF8-BE55-1C5312B6D070/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer (0x1043c93d0). One of the two will be used. Which one is undefined.
[Xcode] 
[Xcode] objc[584]: Class GCDAsyncSpecialPacket is implemented in both /private/var/containers/Bundle/Application/44902459-79AB-4DF8-BE55-1C5312B6D070/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/CocoaAsyncSocket.framework/CocoaAsyncSocket (0x104590668) and /private/var/containers/Bundle/Application/44902459-79AB-4DF8-BE55-1C5312B6D070/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer (0x1043c9420). One of the two will be used. Which one is undefined.
[Xcode] objc[584]: Class GCDAsyncSocket is implemented in both /private/var/containers/Bundle/Application/44902459-79AB-4DF8-BE55-1C5312B6D070/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/CocoaAsyncSocket.framework/CocoaAsyncSocket (0x1045906b8) and /private/var/containers/Bundle/Application/44902459-79AB-4DF8-BE55-1C5312B6D070/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer (0x1043c9470). One of the two will be used. Which one is undefined.
[Xcode]
