### ISSUE TITLE
Appium web driver on emulator iPhone 6 -12.1 returns value, name, and label the same value as accessibility key for XCUIElementTypeStaticText

### ISSUE THREAD

**Issue by ochemerys** [appium/appium#11883]
## The problem

Appium web driver on emulator iPhone 6 -12.1 returns value, name, and label the same value as accessibility key for XCUIElementTypeStaticText

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: iOS 10.14.2
* Node.js version (unless using Appium.app|exe): v10.5.0
* Mobile platform/version under test: iPhone 6 - 12.1
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: CLI

## Details

It can be easily reproduced with Appium Desktop.

iOS device:
![image](https://user-images.githubusercontent.com/20651535/50294769-dd0d7280-0433-11e9-917c-aedb765214bd.png)

Android simulator:
![image](https://user-images.githubusercontent.com/20651535/50294981-4db48f00-0434-11e9-8823-bd8ca5e3ccc2.png)

for testing JavaScript client "webdriverio": "^4.12.0"
the line of code 
`var elText = await driver.getText('~pageTitleText');`
returns from iPhone the same value as accessibility id "pageTitleText"
at the same time Android device returns correct value "Home"
 
## Code To Reproduce Issue [ Good To Have ]

It can be easily reproduced with Appium Desktop.
see images above 
I logged issue for Appium Desktop:  https://github.com/appium/appium-desktop/issues/779

**Comment by mykola-mokhnach** [comment]
These values are retrieved from [WebDriverAgent](https://github.com/facebook/WebDriverAgent). Please report an issue there if you consider the current behaviour wrong.
