### ISSUE TITLE
Getting "java.lang.SecurityException: Permission Denial" while trying to swtich to browser from the app

### ISSUE THREAD

**Issue by logakarthi** [appium/appium#11894]
## The problem

I'm getting the below exception while trying to switch to chrome browser from my app and unable to interact into the browser.

java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=com.android.chrome/org.chromium.chrome.browser.customtabs.CustomTabActivity } from null (pid=14572, uid=2000) not exported from uid 10108
        at com.android.server.am.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1682)
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:442)
        at com.android.server.am.ActivityStarter.startActivityLocked(ActivityStarter.java:276)
        at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:835)
        at com.android.server.am.ActivityManagerService.startActivityAndWait(ActivityManagerService.java:4740)
        at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:408)
        at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:142)
        at android.os.ShellCommand.exec(ShellCommand.java:96)
        at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:15244)
        at android.os.Binder.shellCommand(Binder.java:573)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Desktop OS/version used to run Appium: MAC
* Mobile platform/version under test: Android 8.0
* Real device or emulator/simulator: Moto x4

## Link to Appium logs

https://gist.github.com/logakarthi/4670b88ff787e546ea55e4b477ff88f0

## Code To Reproduce Issue [ Good To Have ]
@BeforeSuite
    public void setUpAppium() throws MalformedURLException {
        final String URL_STRING = "http://127.0.0.1:4723/wd/hub";
        URL url = new URL(URL_STRING);
        //Use a empty DesiredCapabilities object
        DesiredCapabilities capabilities = new DesiredCapabilities();
        File appdir = new File("/Users/apple/Documents/AndroidiOSBuilds/GammaPracticeApp/3.9.0GA/");
        File app = new File(appdir, "CK12-debug-gamma-3.9.0.254808.apk");
        capabilities.setCapability(CapabilityType.BROWSER_NAME, "");
        capabilities.setCapability("noReset", true);
        capabilities.setCapability("autoWebview", "true");
        capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 1000);
        capabilities.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
        capabilities.setCapability("autoLaunch", Boolean.parseBoolean("autolaunch"));
        capabilities.setCapability("autoLaunch", Boolean.parseBoolean(String.valueOf(true)));
        capabilities.setCapability(MobileCapabilityType.APP_ACTIVITY, "org.ck12.app.practice.MainActivity");
        capabilities.setCapability(MobileCapabilityType.APP_PACKAGE, "org.ck12.app.practice");
        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, MobilePlatform.ANDROID);
        capabilities.setCapability("recreateChromeDriverSessions", true);
        capabilities.setCapability("nativeWebTap", true);
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "ZY224QJNRJ"); // Moto E TA38500ME6
        capabilities.setCapability("chromedriverExecutable", "/Users/apple/Desktop/ChromeDriver/44/chromedriver");
        driver = new AndroidDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
        driver.manage().timeouts().implicitlyWait(80, TimeUnit.SECONDS);
        try {
            Thread.sleep(15000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        switchToWebViewContext("NATIVE_APP");
        System.out.println("switching the context to native");
        try {
            if (driver.findElementById("com.android.packageinstaller:id/permission_allow_button").isDisplayed()) {
                driver.findElementById("com.android.packageinstaller:id/permission_allow_button").click();
            } else {
                System.out.println("Permission popup is not displayed");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        switchToWebViewContext("WEBVIEW");
        System.out.println("switching the context to native");
        try {
            Thread.sleep(15000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        switchApp();
        return capabilities;
}
      
    @Test
    public boolean switchApp () {
        if (driver.findElement(By.cssSelector("a.sign-btn")).isDisplayed()) {
            driver.findElement(By.cssSelector("a.sign-btn")).click();
            //driver.runAppInBackground(10);
            try {
                Thread.sleep(15000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
        try {
            System.out.println("switching...");
            ((AndroidDriver) driver).startActivity("com.android.chrome", "org.chromium.chrome.browser.customtabs.CustomTabActivity");
            switchToWebViewContext("NATIVE_APP");
            try {
                Thread.sleep(10000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            System.out.println(driver.getCurrentUrl());
            switchToWebViewContext("WEBVIEW");
            try {
                Thread.sleep(10000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            ((AndroidDriver) driver).startActivity("org.ck12.app.practice", "org.ck12.app.practice.MainActivity");
            System.out.println(driver.getCurrentUrl());
        }catch (Exception e){
            e.printStackTrace();
        }
        return true;
    }

**Comment by saikrishna321** [comment]
@logakarthi Please update the server to the latest and also pls use _UIAutomator2_ as automationName

**Comment by logakarthi** [comment]
Still, I'm getting the same exception even though I updated the appium version and set the automationName as per above comments. 

https://gist.github.com/logakarthi/e61f4084e401874bb234e8f401e835a4

AppPackage and AppActivity are showing correctly while trying the below commands in ADB shell,

$ mCurrentFocus=Window{d9753ca u0 com.android.chrome/org.chromium.chrome.browser.customtabs.CustomTabActivity}

I tried another way, I directly give the ur using the commands(driver.navigate.to(browserurl) from the app, it redirected successfully, but elements are not clickable in this page even though elements are available in this page(I ensured using driver.pageSource()).

Please suggest the solution to fix this issue.

**Comment by mykola-mokhnach** [comment]
Are you sure you execute the same command `adb -P 5037 -s ZY224QJNRJ shell am start -W -n com.android.chrome/org.chromium.chrome.browser.customtabs.CustomTabActivity -S` while Chrome is running? Perhaps, command options should be customized? Maybe it worth trying to replicate user actions instead of using adb directly?

**Comment by logakarthi** [comment]
Yes, @mykola-mokhnach. I tried the below commands while chrome browser is running after coming back from my app manually.

adb -P 5037 -s ZY224QJNRJ shell am start -W -n com.android.chrome/org.chromium.chrome.browser.customtabs.CustomTabActivity -S
Stopping: com.android.chrome
Starting: Intent { cmp=com.android.chrome/org.chromium.chrome.browser.customtabs.CustomTabActivity }
Security exception: Permission Denial: starting Intent { flg=0x10000000 cmp=com.android.chrome/org.chromium.chrome.browser.customtabs.CustomTabActivity } from null (pid=5765, uid=2000) not exported from uid 10108

java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=com.android.chrome/org.chromium.chrome.browser.customtabs.CustomTabActivity } from null (pid=5765, uid=2000) not exported from uid 10108
	at com.android.server.am.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1682)
	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:442)
	at com.android.server.am.ActivityStarter.startActivityLocked(ActivityStarter.java:276)
	at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:835)
	at com.android.server.am.ActivityManagerService.startActivityAndWait(ActivityManagerService.java:4740)
	at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:408)
	at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:142)
	at android.os.ShellCommand.exec(ShellCommand.java:96)
	at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:15244)
	at android.os.Binder.shellCommand(Binder.java:573)
	at android.os.Binder.onTransact(Binder.java:473)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:4339)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3054)
	at android.os.Binder.execTransact(Binder.java:674)

After hitting the above commands in terminal, automatically switch over to my app again from the chrome browser.

**Comment by mykola-mokhnach** [comment]
I close the report, since your problem is not an appium issue. Please use Appium forum for questions
