### ISSUE TITLE
How to avoid autolaunch the App in iOS when I new a IOSDriver object?

### ISSUE THREAD

**Issue by JamesChungZLL** [appium/appium#11897]
## The problem
When new a IOSDriver object, Appium start the App automatically, I am sure I do not call the launchApp() function. 
How can I avoid auto launch the App when I new a IOSDriver object?

## Environment

* Appium version (or git revision) that exhibits the issue: v1.10.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:Mac 10.14.1
* Node.js version (unless using Appium.app|exe):v8.2.1
* Mobile platform/version under test:iOS 12.1
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Code To Reproduce Issue [ Good To Have ]
`capabilities.setCapability("deviceName", "“iOS device");`
       `capabilities.setCapability("platformName", "iOS");`
        `capabilities.setCapability("useNewWDA", false);`
       `capabilities.setCapability("useJSONSource", true);`
        `capabilities.setCapability("realDeviceScreenshotter", "idevicescreenshot");`
        `capabilities.setCapability("autoLaunch", "false");`
        `capabilities.setCapability("usePrebuiltWDA", true);`
        `capabilities.setCapability("noReset", true);`
        `capabilities.setCapability("autoAcceptAlerts", true);`
        `capabilities.setCapability("automationName", "XCUITest");`
        `capabilities.setCapability("newCommandTimeout", 999999);`
`capabilities.setCapability("udid", udid);`
            `capabilities.setCapability("bundleId", bundleID);`
            `capabilities.setCapability("wdaLocalPort", wdaLocalPort`

**Comment by mykola-mokhnach** [comment]
This is currently impossible either app path or a bundle id must be set. Please use appium forum for questions

**Comment by JamesChungZLL** [comment]
OK, Could this be done with modifying Appium code?

**Comment by mykola-mokhnach** [comment]
Yes it could be this way

**Comment by JamesChungZLL** [comment]
Could you please show me the code line?
And, in my opinion, new a IOSDriver() object should not start the target App, otherwise what the 'launchApp()' function use for?

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium-xcuitest-driver/blob/master/lib/driver.js

launchApp is a legacy thing and is not recommended for use

**Comment by JamesChungZLL** [comment]
Then, what the recommend function name for start a app?

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/InteractsWithApps.java
