### ISSUE TITLE
node-simctl hardcoded to iOS

### ISSUE THREAD

**Issue by simongranger** [appium/appium#11892]
## The problem

appium-youiengine-driver supports tvOS and would like to make use of appium-ios-simulator and node-simctl. At the moment is it hardcoded to only support iOS.

https://github.com/appium/node-simctl/blob/master/lib/simctl.js#L528

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe): 
* Mobile platform/version under test: tvOS
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe:

## Details

To test this out, I've rebuilt node-simctl to replace iOS by tvOS on line 528 and 531 and was able to run tvOS simulator commands fine from rebuilt appium-ios-simulator.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Closed as fixed
