### ISSUE TITLE
MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xfd79b0>: Failed to establish a new connection: [Errno 61] Connection refused',))

### ISSUE THREAD

**Issue by winterLiang** [appium/appium#11898]
The problem

MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xfd79b0>: Failed to establish a new connection: [Errno 61] Connection refused',))

Environment

* Appium version (or git revision) that exhibits the issue: 1.9.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: os
* Node.js version (unless using Appium.app|exe): v10.14.1
* Mobile platform/version under test:
* Real device or emulator/simulator:Real device 
* Appium CLI or Appium.app|exe:

 Details

on jenkins , when I try to use the command "appium/build/lib/main.js --address '127.0.0.1' --port '4723' --session-override &" to  start the  appium-server ,Startup always fails

 The complete error message is as follows：
  [ WARN ] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xfd7510>: Failed to establish a new connection: [Errno 61] Connection refused',)': /wd/hub/session
[ WARN ] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xfbfd30>: Failed to establish a new connection: [Errno 61] Connection refused',)': /wd/hub/session
[ WARN ] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xfbfd50>: Failed to establish a new connection: [Errno 61] Connection refused',)': /wd/hub/session
[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: No application is open
[ WARN ] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xfd7670>: Failed to establish a new connection: [Errno 61] Connection refused',)': /wd/hub/session
[ WARN ] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xfd7970>: Failed to establish a new connection: [Errno 61] Connection refused',)': /wd/hub/session
[ WARN ] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xfd77d0>: Failed to establish a new connection: [Errno 61] Connection refused',)': /wd/hub/session
[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: No application is open
[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: No application is open
| FAIL |
MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xfd79b0>: Failed to establish a new connection: [Errno 61] Connection refused',))

I can't find a solution。

**Comment by mykola-mokhnach** [comment]
- Appium 1.9.0 is out of date
- Please attach full server log

**Comment by winterLiang** [comment]
In which folder can I see the log?

**Comment by mykola-mokhnach** [comment]
Please use appium forum for questions. Closed as not an issue

**Comment by gatamar** [comment]
Well, I had a very similar issue and the answer was: my Appium server was not running when I ran my test client.

**Comment by luoei** [comment]
Encountered the same problem, how to solve it?

**Comment by KimEklund13** [comment]
I launched Appium (Desktop) and ran my script with the desired caps and it crashes with this error. I also tried launching Appium, provided desired caps in the GUI, and clicked "start new session" and Appium still crashes.

I don't see how this can be closed as not an issue.

Server v1.15.1

**Comment by RishikeshShah** [comment]
I had the same issue. 
Solution:
Before running the test, I started the Appium server from the command prompt by simply typing appium.

**Comment by amanzan** [comment]
Same issue here and no idea how to solve it. It happens the second time I try to run tests on Android. I suppose it's because the session is not being correctly closed the first time...
Closing issues without any suggestion, doesn't help at all

**Comment by v1v3kls** [comment]
Facing the same issue.

+Following
