### ISSUE TITLE
Failed to create WDA session  for Appium 1.9.1 - App keep launch and closing non stop

### ISSUE THREAD

**Issue by ivantay2003** [appium/appium#11899]
## The problem

Appium launch and close the app (iOS real device) repeatedly.  It did not happen for 1.8.1

## Environment

* Appium version (or git revision) that exhibits the issue:1.9.1
* Last Appium version that did not exhibit the issue (if applicable): 1.8.1
* Desktop OS/version used to run Appium: OS X 10.14.2
* Node.js version (unless using Appium.app|exe): v10.9.0
* Mobile platform/version under test: 12.1.2
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium app

## Details

I am trying to launch the app using appium app. It used to work in v1.8.1 and the tests are able to run
The desired caps in the appium inspector are 
{
  "deviceName": "iPhone",
  "bundleId": "com.homage.carepro",
  "udid": “UUID”,
  "platformVersion": "12.1.2",
  "xcodeOrgId": “XXXXXX”,
  "xcodeSigningId": "iPhone Developer",
  "platformName": "IOS",
  "automationName": "XCuiTest",
  "noReset": true,
  "forceMjsonwp": true
}

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
https://gist.github.com/ivantay2003/aef970f4c0de1a8416b3cc506f8d09d5

## Code To Reproduce Issue [ Good To Have ]
- Have the app in the real device
- Include the above desired cap settings in appium app
- Launch inspector

Result The app will keep launching and closing non stop.

**Comment by mykola-mokhnach** [comment]
Try to retrieve the log with `showIOSLog` cap enabled. The error happens because Appium retrieves an unexpected empty session creation response from WebDriverAgent, which is a third party component.

**Comment by ivantay2003** [comment]
Hi @mykola-mokhnach , I am using the appium desktop app. Do I add this in the desired cap ?
showIOSLog : true 

Thanks

**Comment by ivantay2003** [comment]
Hi @mykola-mokhnach 

I have enabled to showIOSLog . The gist is in here
https://gist.github.com/ivantay2003/18df4b05ec1e18a94f7f71e84990be8f

Thanks

**Comment by ivantay2003** [comment]
@mykola-mokhnach 
These are the log for appium app 1.8.1 . It is able to successfully launch app
https://gist.github.com/ivantay2003/20c6f1af02e3fa0a8e5e1970a57d0f44

I do not understand the above comment as it shows the capability. The only difference I see is that Appium 1.9.1 have this additional lines at the beginning which Appium 1.8.1 gist does not have.

Appium app 1.9.1
[23:12:57:0108] [info] Retrieving session for window with id: 2
[23:12:57:0109] [error] Could not find session with window id '2'. Availalable sessions are: '[]'
[23:12:57:0121] [info] Creating method handler for session with window id: 2
[23:12:57:0121] [info] The following session window ID's have active sessions: '["2"]'

Appium app 1.9.1 log is also missing portion (which is extracted from Appium app 1.8.1) for below
[XCUITest] WebDriverAgent information:
[XCUITest] {
[XCUITest]   "state": "success",
[XCUITest]   "os": {
[XCUITest]     "name": "iOS",
[XCUITest]     "version": "12.1.2",
[XCUITest]     "sdkVersion": "12.0"
[XCUITest]   },
[XCUITest]   "ios": {
[XCUITest]     "simulatorVersion": "12.1.2",
[XCUITest]     "ip": "192.168.1.4"
[XCUITest]   },
[XCUITest]   "build": {
[XCUITest]     "upgradedAt": "1545605820760",
[XCUITest]     "time": "Dec 24 2018 06:57:16",
[XCUITest]     "productBundleIdentifier": "com.facebook.WebDriverAgentRunner"
[XCUITest]   }
[XCUITest] }

**Comment by Warren25** [comment]
What happens if you try appium version 1.10.0?

**Comment by ivantay2003** [comment]
This happens only for desktop version. 1.9.1 is the latest desktop ver

**Comment by mykola-mokhnach** [comment]
closed as inactive
