### ISSUE TITLE
iOS: accessibility id duplicated into name attribute

### ISSUE THREAD

**Issue by spraveenk91** [appium/appium#11891]
Hello Team,

We are trying to automate our iOS application and we are facing some issues for retrieving the actual UI element's value. We can retrieve an UI element using `accessibility id` in appium. Please, refer the below iOS appium desktop image:

![screenshot 2018-12-21 at 3 10 08 pm](https://user-images.githubusercontent.com/3426723/50339290-17166b80-053d-11e9-9435-c50a31371d08.png)

In above image, `accessibility id` has the identifier value for the `UILabel` element. But, `name` attribute also having the same `accessibility id` instead of that label's actual value **`United Kingdom and Ireland`**

We have cross checked this with the developers, and they have tried giving this identifier value to the UI elements using other available features such as `label.accessibilityIdentifier` or `label.accessibilityLabel` or `label.accessibilityValue`  whichever the feature they are giving the id value, always this `name` attribute is getting duplicated value of `accessibility id` instead of its actual value. 

And, this is not happening in the case of **Android**  Please, refer the below Android appium desktop image:

![screen shot 2018-12-21 at 3 31 15 pm](https://user-images.githubusercontent.com/3426723/50340031-45954600-053f-11e9-9103-96b91f038d6c.png)

In android, it is coming perfectly. In `accessibility id` it has the id value. And, in `text` attribute it is holding the element's actual value, Ex: **`United Kingdom and Ireland`** 

Can someone help us why this is happening with iOS?

**Comment by mykola-mokhnach** [comment]
Duplicate of https://github.com/appium/appium/issues/11883

Sorry, we can do nothing on Appium side.
