### ISSUE TITLE
Appium stuck 

### ISSUE THREAD

**Issue by AvrahamAtia** [appium/appium#11908]
## The problem

I executed multiple Android devices in parallel, After some tests Appium stuck in specific log: 
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Running '/usr/local/bin/adb -P 5037 -s ***** shell am force-stop io.appium.unlock'
[debug] [AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.

## Environment
Mac 
* Appium version: 18.1
* Node.js version: v11.5.0
* Mobile platform/version under test: 8.0.0
* Real device or emulator/simulator: Android real devices

**Comment by mykola-mokhnach** [comment]
- Use uiautomator2/espresso for Android 6+, UIA1 is obsolete
- Appium 1.8.1 is out of date
