### ISSUE TITLE
The application at 'xxxxx/target.ipa' does not exist or is not accessible

### ISSUE THREAD

**Issue by OspreyRen** [appium/appium#11905]
## The problem

Get error when install ipa file to real device:
The application at '/tmp/task_bundle/361fb7aa-1883-4c7e-a296-f575f05ae68e/payload/target.ipa' does not exist or is not accessible

## Environment

* Appium Service running at headspin
* Running test at ubuntu by Python3.7
* file permission: -rw-r--r-- 1 ubuntu ubuntu 105698531 Dec 25 18:10 target.ipa

## Details

selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: The application at '/tmp/task_bundle/361fb7aa-1883-4c7e-a296-f575f05ae68e/payload/target.ipa' does not exist or is not accessible

**Comment by mykola-mokhnach** [comment]
We cannot help nothing without the full server log

**Comment by OspreyRen** [comment]
> We cannot help nothing without the full server log

It is look like my ipa file was damaged, sorry for bugging you
