### ISSUE TITLE
Can not switch to WebView on ios real device

### ISSUE THREAD

**Issue by wangzi1325** [appium/appium#11902]
## The problem

When  I called switch context like this :
```java
  Set<String> contextNames = driver.getContextHandles();
        for (String contextName : contextNames) {
            System.out.println(contextName);
            if (contextName.contains("WEBVIEW")) {
                driver.context(contextName);
            }
        }
```
I got  "NoSuchContextException".  But  “driver.getContextHandles()”  already  got the context.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Node.js version (unless using Appium.app|exe): 10
* Mobile platform/version under test:  ios 9.3.5
* Real device or emulator/simulator: iPad mini2
* Appium CLI or Appium.app|exe:  both
* XCode Version 9.2
* MacOS Version 10.13.4
* usbmuxd  libimobiledevice   ios_webkit_debub_proxy :  last version
## Details
Inspectable pages from  ios_webkit_debug_proxy  
![image](https://user-images.githubusercontent.com/4196935/50409723-be421e00-082f-11e9-8bf9-60b974c9c893.png)

## Link to Appium logs

https://gist.github.com/wangzi1325/4e5928cb8287abc02273fc441e4a4125

**Comment by mykola-mokhnach** [comment]
I don't observe any errors in the attached logs. Also, Appium 1.8.1 is out of date. Please use the most recent one.

**Comment by mykola-mokhnach** [comment]
Yes, the support of Xcode 8 and older has been recently dropped. I assume we cannot help much with older versions then, since no patches are being provided. Maybe, other people had similar issues with older devices.

**Comment by mykola-mokhnach** [comment]
Closed as inactive
