### ISSUE TITLE
SafariNetwork][39m   Initiator: script uncaughtException: _lodash2.default.truncate(...).padEnd is not a function

### ISSUE THREAD

**Issue by khanhdodang** [appium/appium#11907]
## The problem

It can't run automation on iOS web with desiredCap capabilities.setCapability("showSafariNetworkLog", true);

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Mobile platform/version under test: iOS

## Details

It initializes the test session and is failed.

## Link to Appium logs

https://gist.github.com/khanhdodang/9a785388be52c75bea9e047232bf7eb2

## Code To Reproduce Issue [ Good To Have ]

public static DesiredCapabilities desiredCapabilitiesiOSWeb(){
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("browserName", "safari");
        capabilities.setCapability("deviceName", "*");
        capabilities.setCapability("platformName", "iOS");
        capabilities.setCapability("showSafariNetworkLog", true);
        return capabilities;
    }

**Comment by mykola-mokhnach** [comment]
The fix has been published in appium@beta
