### ISSUE TITLE
Not able to take screenshot in UIAutomatorviewer in Windows 7

### ISSUE THREAD

**Issue by PrabodhGhosh** [appium/appium#11906]
## The problem

I am trying to take the Device Screenshot of an emulator for finding element ids in UIAutomator Viewer in Windows 7. But When I click on the "Device Screenshot" button, I am getting "Error Obtaining UI Hierarchy Reason: Error Taking Device Screenshot : EOF".

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.1
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Windows 7
* Node.js version (unless using Appium.app|exe):8.11.4
* Mobile platform/version under test: Android Studio
* Real device or emulator/simulator: Emulator
![image](https://user-images.githubusercontent.com/28348577/50430714-a8922e80-08eb-11e9-91f6-eedd8649aea6.png)

**Comment by RohimMolla** [comment]
You can close the UIAutomator and start again or unplug the wire from device and plug it once again , seems it may work.

**Comment by PrabodhGhosh** [comment]
@RohimMolla  - I am not using real device, I am using emulator.

**Comment by mykola-mokhnach** [comment]
This viewer is not a part of appium. Please report your problem to Google
