### ISSUE TITLE
Logcat terminated with code 0, signal null and UiAutomator exited unexpectedly with code 0, signal null

### ISSUE THREAD

**Issue by parthbmodi** [appium/appium#11903]
## The problem

Logcat terminated with code 0, signal null and UiAutomator exited unexpectedly with code 0, signal null

## Environment

* Appium version (or git revision) that exhibits the issue: v1.10.0
* Last Appium version that did not exhibit the issue (if applicable):V1.9.1
* Desktop OS/version used to run Appium: macOS Mojave (Version 10.14.2)
* Node.js version (unless using Appium.app|exe): 6.5.0
* Mobile platform/version under test: android
* Real device or emulator/simulator: Emulator 
* Appium CLI or Appium.app|exe:

## Details
Getting error during automation script execution 
## Link to Appium logs

https://drive.google.com/file/d/1bxBUYnhgnG7ZqyTlduD1yjMsh_8w7T7k/view?usp=sharing

**Comment by parthbmodi** [comment]
Updated logs with automationName:-  "UiAutomator2"


[info] [35m[Appium][39m Welcome to Appium v1.10.0
[info] [35m[Appium][39m Non-default server args:
[info] [35m[Appium][39m   address: 127.0.0.1
[info] [35m[Appium][39m Appium REST http interface listener started on 127.0.0.1:4723[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{"desiredCapabilities":{"platformName":"android","platformVersion":"8.0","deviceName":"Android 8.0","noReset":true,"app":"/Users/apple/Projects/AppiumTest/AppiumTest/APK/tvd-debug.apk","automationName":"UiAutomator2"},"capabilities":{"firstMatch":[{"platformName":"android"}]}}[39m
[debug] [35m[W3C][39m Calling AppiumDriver.createSession() with args: [{"platformName":"android","platformVersion":"8.0","deviceName":"Android 8.0","noReset":true,"app":"/Users/apple/Projects/AppiumTest/AppiumTest/APK/tvd-debug.apk","automationName":"UiAutomator2"},null,{"firstMatch":[{"platformName":"android"}]}]
[debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1545756652210 (22:20:52 GMT+0530 (IST))
[info] [35m[Appium][39m Could not parse W3C capabilities: 'deviceName' can't be blank
[info] [35m[Appium][39m Trying to fix W3C capabilities by merging them with JSONWP caps
[warn] [35m[BaseDriver][39m The capabilities ["platformVersion","deviceName","noReset","app","automationName"] are not standard capabilities and should have an extension prefix
[info] [35m[Appium][39m Creating new AndroidUiautomator2Driver (v1.24.0) session
[info] [35m[Appium][39m Capabilities:
[info] [35m[Appium][39m   platformVersion: 8.0
[info] [35m[Appium][39m   deviceName: Android 8.0
[info] [35m[Appium][39m   noReset: true
[info] [35m[Appium][39m   app: /Users/apple/Projects/AppiumTest/AppiumTest/APK/tvd-debug.apk
[info] [35m[Appium][39m   automationName: UiAutomator2
[info] [35m[Appium][39m   platformName: android
[debug] [35m[BaseDriver][39m W3C capabilities {"alwaysMatch":{"appium:pla... and MJSONWP desired capabilities {"platformName":"android","... were provided
[debug] [35m[BaseDriver][39m Creating session with W3C capabilities: {"alwaysMatch":{"appium:pla...
[info] [35m[BaseDriver][39m Session created with session id: 9c0bfe1e-f0ea-436d-aa58-e4177ed7c895
[info] [35m[BaseDriver][39m Using local app '/Users/apple/Projects/AppiumTest/AppiumTest/APK/tvd-debug.apk'
[debug] [35m[UiAutomator2][39m Checking whether app is actually present
[info] [35m[AndroidDriver][39m Java version is: 1.8.0_191
[info] [35m[ADB][39m Checking whether adb is present
[info] [35m[ADB][39m Found 1 'build-tools' folders under '/Users/apple/Library/Android/sdk' (newest first):
[info] [35m[ADB][39m     /Users/apple/Library/Android/sdk/build-tools/28.0.3
[info] [35m[ADB][39m Using adb from /Users/apple/Library/Android/sdk/platform-tools/adb
[info] [35m[AndroidDriver][39m Retrieving device list
[debug] [35m[ADB][39m Trying to find a connected android device
[debug] [35m[ADB][39m Getting connected devices...[debug] [35m[ADB][39m 1 device(s) connected
[info] [35m[AndroidDriver][39m Looking for a device with Android '8.0'
[debug] [35m[ADB][39m Setting device id to emulator-5554
[info] [35m[ADB][39m Getting device platform version
[debug] [35m[ADB][39m Running '/Users/apple/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell getprop ro.build.version.release'
[debug] [35m[ADB][39m Current device property 'ro.build.version.release': 8.0.0
[info] [35m[AndroidDriver][39m Using device: emulator-5554
[debug] [35m[ADB][39m Setting device id to emulator-5554
[debug] [35m[ADB][39m Running '/Users/apple/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk'
[debug] [35m[ADB][39m Current device property 'ro.build.version.sdk': 26
[debug] [35m[ADB][39m Device API level: 26
[debug] [35m[AndroidDriver][39m Parsing package and activity from app manifest
[info] [35m[ADB][39m Using apkanalyzer from /Users/apple/Library/Android/sdk/tools/bin/apkanalyzer
[debug] [35m[ADB][39m Starting '/Users/apple/Library/Android/sdk/tools/bin/apkanalyzer' with args ["-h","manifest","print","/Users/apple/Projects/AppiumTest/AppiumTest/APK/tvd-debug.apk"][info] [35m[ADB][39m Package name: 'com.wb.wbtvdistribution.debug'
[info] [35m[ADB][39m Main activity name: 'com.wb.wbtvd.domain.login.LoginActivity'
[debug] [35m[AndroidDriver][39m Parsed package and activity are: com.wb.wbtvdistribution.debug/com.wb.wbtvd.domain.login.LoginActivity
[debug] [35m[ADB][39m Getting all processes with uiautomator
[debug] [35m[ADB][39m Running '/Users/apple/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell ps'[warn] [35m[ADB][39m Unable to root adb daemon: 'adbd cannot run as root in production builds'. Continuing
[debug] [35m[ADB][39m Running '/Users/apple/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell kill -9 15426'
[debug] [35m[ADB][39m Running '/Users/apple/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell kill -9 15426'
[warn] [35m[UiAutomator2][39m Unable to stop uiautomator process: Error executing adbExec. Original error: 'Command '/Users/apple/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell kill -9 15426' exited with code 1'; Stderr: '/system/bin/sh: kill: 15426: Operation not permitted'; Code: '1'
[debug] [35m[ADB][39m Running '/Users/apple/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop io.appium.uiautomator2.server'
[debug] [35m[ADB][39m Checking app cert for /Applications/Appium.app/Contents/Resources/app/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v2.8.0.apk
[info] [35m[ADB][39m Using apksigner from /Users/apple/Library/Android/sdk/build-tools/28.0.3/apksigner
[debug] [35m[ADB][39m Starting '/Users/apple/Library/Android/sdk/build-tools/28.0.3/apksigner' with args '["verify","--print-certs","/Applications/Appium.app/Contents/Resources/app/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v2.8.0.apk"]'[debug] [35m[ADB][39m apksigner stdout: Signer #1 certificate DN: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
[debug] [35m[ADB][39m Signer #1 certificate SHA-256 digest: a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc
[debug] [35m[ADB][39m Signer #1 certificate SHA-1 digest: 61ed377e85d386a8dfee6b864bd85b0bfaa5af81
[debug] [35m[ADB][39m Signer #1 certificate MD5 digest: e89b158e4bcf988ebd09eb83f5378e87
[debug] [35m[ADB][39m 
[debug] [35m[ADB][39m '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v2.8.0.apk' is already signed.
[debug] [35m[ADB][39m Checking app cert for /Applications/Appium.app/Contents/Resources/app/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk
[debug] [35m[ADB][39m Starting '/Users/apple/Library/Android/sdk/build-tools/28.0.3/apksigner' with args '["verify","--print-certs","/Applications/Appium.app/Contents/Resources/app/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk"]'[debug] [35m[ADB][39m apksigner stdout: Signer #1 certificate DN: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
[debug] [35m[ADB][39m Signer #1 certificate SHA-256 digest: a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc
[debug] [35m[ADB][39m Signer #1 certificate SHA-1 digest: 61ed377e85d386a8dfee6b864bd85b0bfaa5af81
[debug] [35m[ADB][39m Signer #1 certificate MD5 digest: e89b158e4bcf988ebd09eb83f5378e87
[debug] [35m[ADB][39m 
[debug] [35m[ADB][39m '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk' is already signed.
[debug] [35m[ADB][39m Getting install status for io.appium.uiautomator2.server
[debug] [35m[ADB][39m Running '/Users/apple/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.uiautomator2.server'[debug] [35m[ADB][39m 'io.appium.uiautomator2.server' is installed
[debug] [35m[ADB][39m Getting package info for 'io.appium.uiautomator2.server'
[debug] [35m[ADB][39m Running '/Users/apple/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.uiautomator2.server'
[info] [35m[ADB][39m Checking whether aapt is present
[info] [35m[ADB][39m Using aapt from /Users/apple/Library/Android/sdk/build-tools/28.0.3/aapt
[debug] [35m[ADB][39m The version name of the installed 'io.appium.uiautomator2.server' is greater or equal to the application version name ('2.8.0' >= '2.8.0')
[debug] [35m[ADB][39m There is no need to install/upgrade '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v2.8.0.apk'
[debug] [35m[ADB][39m Getting install status for io.appium.uiautomator2.server.test
[debug] [35m[ADB][39m Running '/Users/apple/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.uiautomator2.server.test'
[debug] [35m[ADB][39m 'io.appium.uiautomator2.server.test' is installed
[debug] [35m[ADB][39m Getting package info for 'io.appium.uiautomator2.server.test'
[debug] [35m[ADB][39m Running '/Users/apple/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.uiautomator2.server.test'
[warn] [35m[ADB][39m Cannot read version codes of '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk' and/or 'io.appium.uiautomator2.server.test'
[warn] [35m[ADB][39m Cannot read version names of '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk' and/or 'io.appium.uiautomator2.server.test'
[debug] [35m[ADB][39m The current install state of '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk' is unknown. Installing anyway
[debug] [35m[ADB][39m Device API level: 26
[debug] [35m[ADB][39m Running '/Users/apple/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 install -r /Applications/Appium.app/Contents/Resources/app/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk'[debug] [35m[ADB][39m Install command stdout: Success
[debug] [35m[UiAutomator2][39m Waiting up to 20000ms for instrumentation 'io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner' to be available
[debug] [35m[ADB][39m Running '/Users/apple/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pm list instrumentation'[debug] [35m[UiAutomator2][39m Instrumentation 'io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner' available
[debug] [35m[ADB][39m Running '/Users/apple/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 wait-for-device'
[debug] [35m[ADB][39m Running '/Users/apple/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell echo ping'
[debug] [35m[AndroidDriver][39m Pushing settings apk to device...
[debug] [35m[ADB][39m Getting install status for io.appium.settings
[debug] [35m[ADB][39m Running '/Users/apple/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.settings'
[debug] [35m[ADB][39m 'io.appium.settings' is installed
[debug] [35m[ADB][39m Getting package info for 'io.appium.settings'
[debug] [35m[ADB][39m Running '/Users/apple/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.settings'
[debug] [35m[ADB][39m The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('2.11.0' >= '2.11.0')
[debug] [35m[ADB][39m There is no need to install/upgrade '/Applications/Appium.app/Contents/Resources/app/node_modules/io.appium.settings/apks/settings_apk-debug.apk'
[debug] [35m[ADB][39m Running '/Users/apple/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell ps'
[debug] [35m[AndroidDriver][39m io.appium.settings is already running. There is no need to reset its permissions.
[debug] [35m[ADB][39m Device API level: 26
[debug] [35m[ADB][39m Running '/Users/apple/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell appops set io.appium.settings android\:mock_location allow'
[warn] [35m[AndroidDriver][39m setDeviceLanguageCountry requires language or country.
[warn] [35m[AndroidDriver][39m Got language: 'undefined' and country: 'undefined'
[debug] [35m[Logcat][39m Starting logcat capture
[debug] [35m[UiAutomator2][39m Forwarding UiAutomator2 Server port 6790 to 8200
[debug] [35m[ADB][39m Forwarding system: 8200 to device: 6790
[debug] [35m[ADB][39m Running '/Users/apple/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward tcp\:8200 tcp\:6790'
[debug] [35m[ADB][39m Checking app cert for /Users/apple/Projects/AppiumTest/AppiumTest/APK/tvd-debug.apk
[debug] [35m[ADB][39m Starting '/Users/apple/Library/Android/sdk/build-tools/28.0.3/apksigner' with args '["verify","--print-certs","/Users/apple/Projects/AppiumTest/AppiumTest/APK/tvd-debug.apk"]'[debug] [35m[ADB][39m apksigner stdout: Signer #1 certificate DN: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
[debug] [35m[ADB][39m Signer #1 certificate SHA-256 digest: a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc
[debug] [35m[ADB][39m Signer #1 certificate SHA-1 digest: 61ed377e85d386a8dfee6b864bd85b0bfaa5af81
[debug] [35m[ADB][39m Signer #1 certificate MD5 digest: e89b158e4bcf988ebd09eb83f5378e87
[debug] [35m[ADB][39m 
[debug] [35m[ADB][39m '/Users/apple/Projects/AppiumTest/AppiumTest/APK/tvd-debug.apk' is already signed.
[debug] [35m[ADB][39m Getting install status for com.wb.wbtvdistribution.debug
[debug] [35m[ADB][39m Running '/Users/apple/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package com.wb.wbtvdistribution.debug'
[debug] [35m[ADB][39m 'com.wb.wbtvdistribution.debug' is installed
[debug] [35m[ADB][39m Getting package info for 'com.wb.wbtvdistribution.debug'
[debug] [35m[ADB][39m Running '/Users/apple/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package com.wb.wbtvdistribution.debug'
[debug] [35m[ADB][39m The version code of the installed 'com.wb.wbtvdistribution.debug' is greater than the application version code (25 > 23)
[debug] [35m[ADB][39m There is no need to install/upgrade '/Users/apple/Projects/AppiumTest/AppiumTest/APK/tvd-debug.apk'
[debug] [35m[ADB][39m Getting all processes with uiautomator
[debug] [35m[ADB][39m Running '/Users/apple/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell ps'
[debug] [35m[ADB][39m Running '/Users/apple/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop io.appium.uiautomator2.server'
[info] [35m[UiAutomator2][39m Starting uiautomator2 server 2.8.0
[info] [35m[UiAutomator2][39m Using UIAutomator2 server from '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v2.8.0.apk' and test from '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk'
[info] [35m[UiAutomator2][39m Running command: 'adb -s emulator-5554 shell am instrument -w io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner'
[info] [35m[UiAutomator2][39m Waiting up to 20000ms for UiAutomator2 to be online...
[debug] [35m[JSONWP Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[JSONWP Proxy][39m Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[warn] [35m[JSONWP Proxy][39m Got an unexpected response: {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}[debug] [35m[JSONWP Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[JSONWP Proxy][39m Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body[warn] [35m[JSONWP Proxy][39m Got an unexpected response: {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}[debug] [35m[JSONWP Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[JSONWP Proxy][39m Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body[debug] [35m[JSONWP Proxy][39m Got response with status 200: "{\"sessionId\":\"SESSIONID\",\"status\":0,\"value\":\"Status Invoked\"}"
[debug] [35m[JSONWP Proxy][39m Matched '/session' to command name 'createSession'
[debug] [35m[JSONWP Proxy][39m Proxying [POST /session] to [POST http://localhost:8200/wd/hub/session] with body: {"desiredCapabilities":{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"android","platformVersion":"8.0","deviceName":"Android 8.0","noReset":true,"app":"/Users/apple/Projects/AppiumTest/AppiumTest/APK/tvd-debug.apk","automationName":"UiAutomator2"},"platformName":"android","platformVersion":"8.0","deviceName":"emulator-5554","noReset":true,"app":"/Users/apple/Projects/AppiumTest/AppiumTest/APK/tvd-debug.apk","automationName":"UiAutomator2","deviceUDID":"emulator-5554","appPackage":"com.wb.wbtvdistribution.debug"}}
[debug] [35m[JSONWP Proxy][39m Got response with status 200: {"sessionId":"2c2c78d8-96f4-4cd2-b823-089512d6fe17","status":0,"value":"Created Session"}
[debug] [35m[JSONWP Proxy][39m Proxying [GET /appium/device/info] to [GET http://localhost:8200/wd/hub/session/2c2c78d8-96f4-4cd2-b823-089512d6fe17/appium/device/info] with no body
[debug] [35m[JSONWP Proxy][39m Got response with status 200: "{\"sessionId\":\"2c2c78d8-96f4-4cd2-b823-089512d6fe17\",\"status\":0,\"value\":{\"androidId\":\"fbe80557794b52fb\",\"manufacturer\":\"Google\",\"model\":\"Android SDK built for x86\",\"brand\":\"google\",\"apiVersion\":\"26\",\"platformVersion\":\"8.0.0\",\"carrierName\":\"Android\",\"realDisplaySize\":\"480x800\",\"displayDensity\":240}}"
[debug] [35m[ADB][39m Running '/Users/apple/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys window'
[info] [35m[AndroidDriver][39m Screen already unlocked, doing nothing
[info] [35m[UiAutomator2][39m UiAutomator2 did not start the activity we were waiting for, 'com.wb.wbtvdistribution.debug/com.wb.wbtvd.domain.login.LoginActivity'. Starting it ourselves
[debug] [35m[ADB][39m Device API level: 26
[debug] [35m[ADB][39m Running '/Users/apple/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am start -W -n com.wb.wbtvdistribution.debug/com.wb.wbtvd.domain.login.LoginActivity -S'[debug] [35m[ADB][39m Waiting up to 20000ms for activity matching pkg: 'com.wb.wbtvdistribution.debug' and activity: 'com.wb.wbtvd.domain.login.LoginActivity' to be focused
[debug] [35m[ADB][39m Possible activities, to be checked: 'com.wb.wbtvd.domain.login.LoginActivity', 'com.wb.wbtvdistribution.debug.com.wb.wbtvd.domain.login.LoginActivity'
[debug] [35m[ADB][39m Getting focused package and activity
[debug] [35m[ADB][39m Running '/Users/apple/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys window windows'
[debug] [35m[ADB][39m Found package: 'com.wb.wbtvdistribution.debug' and fully qualified activity name : 'com.wb.wbtvd.domain.login.LoginActivity'
[debug] [35m[JSONWP Proxy][39m Proxying [GET /appium/device/pixel_ratio] to [GET http://localhost:8200/wd/hub/session/2c2c78d8-96f4-4cd2-b823-089512d6fe17/appium/device/pixel_ratio] with body: {}
[debug] [35m[JSONWP Proxy][39m Got response with status 200: "{\"sessionId\":\"2c2c78d8-96f4-4cd2-b823-089512d6fe17\",\"status\":0,\"value\":1.5}"
[debug] [35m[JSONWP Proxy][39m Matched '/appium/device/system_bars' to command name 'getSystemBars'
[debug] [35m[JSONWP Proxy][39m Proxying [GET /appium/device/system_bars] to [GET http://localhost:8200/wd/hub/session/2c2c78d8-96f4-4cd2-b823-089512d6fe17/appium/device/system_bars] with body: {}
[debug] [35m[JSONWP Proxy][39m Got response with status 200: "{\"sessionId\":\"2c2c78d8-96f4-4cd2-b823-089512d6fe17\",\"status\":0,\"value\":{\"statusBar\":36}}"
[debug] [35m[JSONWP Proxy][39m Matched '/window/current/size' to command name 'getWindowSize'
[debug] [35m[JSONWP Proxy][39m Proxying [GET /window/current/size] to [GET http://localhost:8200/wd/hub/session/2c2c78d8-96f4-4cd2-b823-089512d6fe17/window/current/size] with body: {}
[debug] [35m[JSONWP Proxy][39m Got response with status 200: "{\"sessionId\":\"2c2c78d8-96f4-4cd2-b823-089512d6fe17\",\"status\":0,\"value\":{\"height\":800,\"width\":480}}"
[info] [35m[Appium][39m New AndroidUiautomator2Driver session created successfully, session 9c0bfe1e-f0ea-436d-aa58-e4177ed7c895 added to master session list
[debug] [35m[BaseDriver][39m Event 'newSessionStarted' logged at 1545756665644 (22:21:05 GMT+0530 (IST))
[debug] [35m[W3C (9c0bfe1e)][39m Cached the protocol value 'W3C' for the new session 9c0bfe1e-f0ea-436d-aa58-e4177ed7c895
[debug] [35m[W3C (9c0bfe1e)][39m Responding to client with driver.createSession() result: {"capabilities":{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"android","platformVersion":"8.0","deviceName":"Android 8.0","noReset":true,"app":"/Users/apple/Projects/AppiumTest/AppiumTest/APK/tvd-debug.apk","automationName":"UiAutomator2"},"platformName":"android","platformVersion":"8.0.0","deviceName":"emulator-5554","noReset":true,"app":"/Users/apple/Projects/AppiumTest/AppiumTest/APK/tvd-debug.apk","automationName":"UiAutomator2","deviceUDID":"emulator-5554","appPackage":"com.wb.wbtvdistribution.debug","deviceApiLevel":26,"deviceScreenSize":"480x800","deviceScreenDensity":240,"deviceModel":"Android SDK built for x86","deviceManufacturer":"Google","pixelRatio":1.5,"statBarHeight":36,"viewportRect":{"left":0,"top":36,"width":480,"height":764}}}
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[32m200[39m [90m13441 ms - 992[39m
[info] [35m[HTTP][39m [90m[39m[debug] [35m[UiAutomator2][39m [UIAutomator2] io.appium.uiautomator2.server.test.AppiumUiAutomator2Server:
[error] [35m[Logcat][39m Logcat terminated with code 0, signal null[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/9c0bfe1e-f0ea-436d-aa58-e4177ed7c895/element[39m
[info] [35m[HTTP][39m [90m{"using":"css selector","value":"#com\\.wb\\.wbtvdistribution\\.debug\\:id\\/email"}[39m
[debug] [35m[W3C (9c0bfe1e)][39m Calling AppiumDriver.findElement() with args: ["css selector","#com\\.wb\\.wbtvdistribution\\.debug\\:id\\/email","9c0bfe1e-f0ea-436d-aa58-e4177ed7c895"]
[debug] [35m[BaseDriver][39m Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [35m[W3C (9c0bfe1e)][39m Encountered internal error running command: InvalidSelectorError: Locator Strategy 'css selector' is not supported for this session
[debug] [35m[W3C (9c0bfe1e)][39m     at AndroidUiautomator2Driver.validateLocatorStrategy (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/lib/basedriver/driver.js:344:13)
[debug] [35m[W3C (9c0bfe1e)][39m     at AndroidUiautomator2Driver.helpers.findElOrElsWithProcessing (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/lib/basedriver/commands/find.js:28:8)
[debug] [35m[W3C (9c0bfe1e)][39m     at AndroidUiautomator2Driver.commands.findElement (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/lib/basedriver/commands/find.js:50:21)
[debug] [35m[W3C (9c0bfe1e)][39m     at curCommandCancellable._bluebird.default.resolve.then (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/lib/basedriver/driver.js:291:18)
[debug] [35m[W3C (9c0bfe1e)][39m     at tryCatcher (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/bluebird/js/main/util.js:26:23)
[debug] [35m[W3C (9c0bfe1e)][39m     at Promise._settlePromiseFromHandler (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/bluebird/js/main/promise.js:510:31)
[debug] [35m[W3C (9c0bfe1e)][39m     at Promise._settlePromiseAt (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/bluebird/js/main/promise.js:584:18)
[debug] [35m[W3C (9c0bfe1e)][39m     at Promise._settlePromiseAtPostResolution (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/bluebird/js/main/promise.js:248:10)
[debug] [35m[W3C (9c0bfe1e)][39m     at Async._drainQueue (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/bluebird/js/main/async.js:128:12)
[debug] [35m[W3C (9c0bfe1e)][39m     at Async._drainQueues (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/bluebird/js/main/async.js:133:10)
[debug] [35m[W3C (9c0bfe1e)][39m     at Immediate.Async.drainQueues (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/node_modules/bluebird/js/main/async.js:15:14)
[debug] [35m[W3C (9c0bfe1e)][39m     at runCallback (timers.js:696:18)
[debug] [35m[W3C (9c0bfe1e)][39m     at tryOnImmediate (timers.js:667:5)
[debug] [35m[W3C (9c0bfe1e)][39m     at processImmediate (timers.js:649:5)
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session/9c0bfe1e-f0ea-436d-aa58-e4177ed7c895/element [39m[33m400[39m [90m23 ms - 2180[39m
[info] [35m[HTTP][39m [90m[39m
[info] [35m[HTTP][39m [37m-->[39m [37mDELETE[39m [37m/wd/hub/session/9c0bfe1e-f0ea-436d-aa58-e4177ed7c895[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[W3C (9c0bfe1e)][39m Calling AppiumDriver.deleteSession() with args: ["9c0bfe1e-f0ea-436d-aa58-e4177ed7c895"]
[debug] [35m[BaseDriver][39m Event 'quitSessionRequested' logged at 1545756672754 (22:21:12 GMT+0530 (IST))
[info] [35m[Appium][39m Removing session 9c0bfe1e-f0ea-436d-aa58-e4177ed7c895 from our master session list
[debug] [35m[UiAutomator2][39m Deleting UiAutomator2 session
[debug] [35m[UiAutomator2][39m Deleting UiAutomator2 server session
[debug] [35m[JSONWP Proxy][39m Matched '/' to command name 'deleteSession'
[debug] [35m[JSONWP Proxy][39m Proxying [DELETE /] to [DELETE http://localhost:8200/wd/hub/session/2c2c78d8-96f4-4cd2-b823-089512d6fe17] with no body
[warn] [35m[JSONWP Proxy][39m Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8200}
[warn] [35m[UiAutomator2][39m Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8200
[debug] [35m[ADB][39m Running '/Users/apple/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop com.wb.wbtvdistribution.debug'[debug] [35m[Logcat][39m Stopping logcat capture
[debug] [35m[Logcat][39m Logcat already stopped
[debug] [35m[ADB][39m Removing forwarded port socket connection: 8200 
[debug] [35m[ADB][39m Running '/Users/apple/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp\:8200'
[debug] [35m[ADB][39m Running '/Users/apple/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp\:8200'[warn] [35m[UiAutomator2][39m Unable to remove port forward 'Error executing adbExec. Original error: 'Command '/Users/apple/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp\:8200' exited with code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''
[debug] [35m[ADB][39m Device API level: 26
[debug] [35m[BaseDriver][39m Event 'quitSessionFinished' logged at 1545756675933 (22:21:15 GMT+0530 (IST))
[debug] [35m[W3C (9c0bfe1e)][39m Received response: null
[debug] [35m[W3C (9c0bfe1e)][39m But deleting session, so not returning
[debug] [35m[W3C (9c0bfe1e)][39m Responding to client with driver.deleteSession() result: null
[info] [35m[HTTP][39m [37m<-- DELETE /wd/hub/session/9c0bfe1e-f0ea-436d-aa58-e4177ed7c895 [39m[32m200[39m [90m3180 ms - 14[39m
[info] [35m[HTTP][39m [90m[39m

**Comment by mykola-mokhnach** [comment]
This is an issue of an outdated client. Closed as duplicate (https://github.com/appium/appium/issues?utf8=✓&q=is%3Aissue+%22Locator+Strategy+%27css+selector%27+is+not+supported+for+this+session%22)
