### ISSUE TITLE
build files use async function, only support node version gt 8.0

### ISSUE THREAD

**Issue by mane115** [appium/appium#11904]
## The problem
it seems that build files of the pkg: appium/node-teen_process use async function
![image](https://user-images.githubusercontent.com/14268652/50425240-706bfb00-08ad-11e9-81b6-5c7282cb9b0f.png)

it only support in node version gt 8.0.

## Environment

* appium/node-teen_process version: 1.14.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac os
* Node.js version (unless using Appium.app|exe): 6.x

**Comment by mykola-mokhnach** [comment]
This is expected. Node 6 is not supported anymore by the recent version. Also, the module must be transpiled by babel

**Comment by imurchie** [comment]
Babel leaves `async` functions in because Node 8 supports them.
