### ISSUE TITLE
Original error: Unable to uninstall APK. Original error: Error executing adbExec.

### ISSUE THREAD

**Issue by rajkumar-cp** [appium/appium#11918]
## The problem

Timeout error is being thrown while appium tried to uninstall an application from emulator

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): 8.11.4
* Mobile platform/version under test: Android 6.0
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: CLI

## Details

Appium is trying to reinstall an application from the Emulator but it is not happening as expected.

## Link to Appium logs
] Calling AppiumDriver.createSession() with args: [{"appPackage":"com.mfiles.mobile","app":"C:\\Applications\\develop-2018-12-28_22-39.apk","rotatable":true,"noReset":false,"android:noHistory":true,"deviceName":"emulator-5556","fullReset":true,"appActivity":"com.mfiles.mobile.activity.SplashActivity","platformVersion":"6.0","adbExecTimeout":"180000","autoGrantPermissions":true,"unicodeKeyboard":true,"udid":"emulator-5556","platformName":"Android","LAUNCH_TIMEOUT":"1000000","device":"Android","autoAcceptAlerts":true},null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1546070836224 (10:07:16 GMT+0200 (FLE Standard Time))
[Appium] Consider setting 'automationName' capability to 'UiAutomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.
[Appium] Creating new AndroidDriver (v4.8.0) session
[Appium] Capabilities:
[Appium]   appPackage: com.mfiles.mobile
[Appium]   app: C:\Applications\develop-2018-12-28_22-39.apk
[Appium]   rotatable: true
[Appium]   noReset: false
[Appium]   android:noHistory: true
[Appium]   deviceName: emulator-5556
[Appium]   fullReset: true
[Appium]   appActivity: com.mfiles.mobile.activity.SplashActivity
[Appium]   platformVersion: 6.0
[Appium]   adbExecTimeout: 180000
[Appium]   autoGrantPermissions: true
[Appium]   unicodeKeyboard: true
[Appium]   udid: emulator-5556
[Appium]   platformName: Android
[Appium]   LAUNCH_TIMEOUT: 1000000
[Appium]   device: Android
[Appium]   autoAcceptAlerts: true
[debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {"appPackage":"com.mfiles.m...
[BaseDriver] Capability 'adbExecTimeout' changed from string ('180000') to integer (180000). This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by appium: rotatable, noHistory, LAUNCH_TIMEOUT, device, autoAcceptAlerts.
[BaseDriver] Session created with session id: d1b1b1d4-6886-4f72-b4e9-fd8786bb1384
[AndroidDriver] Java version is: 1.8.0_181
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 2 device(s) connected
[AndroidDriver] Using device: emulator-5556
[debug] [ADB] Setting device id to emulator-5556
[debug] [ADB] Running 'C:\Users\Deva\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5556 shell getprop ro.build.version.sdk'
[debug] [ADB] Current device property 'ro.build.version.sdk': 23
[debug] [ADB] Device API level: 23
[AndroidDriver] Consider setting 'automationName' capability to 'uiautomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.
[BaseDriver] Using local app 'C:\Applications\develop-2018-12-28_22-39.apk'
[debug] [AndroidDriver] Checking whether app is actually present
[AndroidDriver] Starting Android session
[debug] [ADB] Running 'C:\Users\Deva\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5556 wait-for-device'
[debug] [ADB] Running 'C:\Users\Deva\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5556 shell echo ping'
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Getting install status for io.appium.settings
[debug] [ADB] Running 'C:\Users\Deva\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5556 shell dumpsys package io.appium.settings'
[debug] [ADB] 'io.appium.settings' is installed
[debug] [ADB] Getting package info for 'io.appium.settings'
[debug] [ADB] Running 'C:\Users\Deva\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5556 shell dumpsys package io.appium.settings'
[debug] [ADB] The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('2.11.0' >= '2.11.0')
[debug] [ADB] There is no need to install/upgrade 'C:\Users\Deva\AppData\Roaming\npm\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk'
[debug] [ADB] Running 'C:\Users\Deva\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5556 shell ps'[debug] [AndroidDriver] io.appium.settings is already running. There is no need to reset its permissions.
[debug] [ADB] Device API level: 23
[debug] [ADB] Running 'C:\Users\Deva\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5556 shell appops set io.appium.settings android\:mock_location allow'
[debug] [Logcat] Starting logcat capture
[debug] [AndroidDriver] Enabling Unicode keyboard support
[debug] [ADB] Running 'C:\Users\Deva\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5556 shell settings get secure default_input_method'
[debug] [AndroidDriver] Unsetting previous IME io.appium.settings/.UnicodeIME
[debug] [AndroidDriver] Setting IME to 'io.appium.settings/.UnicodeIME'
[debug] [ADB] Running 'C:\Users\Deva\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5556 shell ime enable io.appium.settings/.UnicodeIME'
[debug] [ADB] Running 'C:\Users\Deva\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5556 shell ime set io.appium.settings/.UnicodeIME'
[ADB] Getting device platform version
[debug] [ADB] Running 'C:\Users\Deva\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5556 shell getprop ro.build.version.release'
[debug] [ADB] Current device property 'ro.build.version.release': 6.0
[debug] [ADB] Running 'C:\Users\Deva\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5556 shell wm size'
[debug] [ADB] Running 'C:\Users\Deva\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5556 shell getprop ro.product.model'
[debug] [ADB] Current device property 'ro.product.model': Android SDK built for x86
[debug] [ADB] Running 'C:\Users\Deva\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5556 shell getprop ro.product.manufacturer'
[debug] [ADB] Current device property 'ro.product.manufacturer': unknown
[debug] [ADB] Uninstalling com.mfiles.mobile
[debug] [ADB] Getting install status for com.mfiles.mobile
[debug] [ADB] Running 'C:\Users\Deva\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5556 shell dumpsys package com.mfiles.mobile'
[debug] [ADB] 'com.mfiles.mobile' is installed
[debug] [ADB] Running 'C:\Users\Deva\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5556 shell am force-stop com.mfiles.mobile'
[debug] [ADB] Running 'C:\Users\Deva\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5556 uninstall com.mfiles.mobile'
[debug] [ADB] Running 'C:\Users\Deva\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5556 uninstall com.mfiles.mobile'
[debug] [AndroidDriver] Shutting down Android driver
[debug] [AndroidDriver] Called deleteSession but bootstrap wasn't active
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Running 'C:\Users\Deva\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5556 shell am force-stop io.appium.unlock'
[debug] [AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1546070887455 (10:08:07 GMT+0200 (FLE Standard Time))
[debug] [MJSONWP] Encountered internal error running command: Error: Unable to uninstall APK. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\Deva\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5556 uninstall com.mfiles.mobile' timed out after 20000ms'; Stderr: ''; Code: 'null'
[debug] [MJSONWP]     at ADB.apkUtilsMethods.uninstallApk (C:\Users\Deva\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\lib\tools\apk-utils.js:329:11)
[debug] [MJSONWP]     at <anonymous>
[HTTP] <-- POST /wd/hub/session 500 51246 ms - 422
[HTTP]

**Comment by mykola-mokhnach** [comment]
The emulator seems to be very slow. Try to increase `adbExecTimeout` capability value (the default value is 20000 ms)
