### ISSUE TITLE
XCUITest requires Appium version >= 1.6.0 (Appium::Error::NotSupportedAppiumServer)

### ISSUE THREAD

**Issue by Balamuruganvsb** [appium/appium#11910]
I'm getting "XCUITest requires Appium version >= 1.6.0 (Appium::Error::NotSupportedAppiumServer)" error when execting the test case.

I have updated the appium-lib (Uninstall & reinstall) and appium server(tried both 1.9 and 1.10) but still getting the same error.

When executing the test case, this error occurs after the app is launched and login page is displayed properly. 

* Appium version (or git revision) that exhibits the issue: 1.10.0
* Desktop OS/version used to run Appium: macOS High Sierra (10.13.6)
* Mobile platform/version under test: iOS v11.1
* Real device or emulator/simulator: Simulator 

[Appium Logs.txt](https://github.com/appium/appium/files/2712421/Appium.Logs.txt)

**Comment by imurchie** [comment]
This is an issue with the Ruby client (https://github.com/appium/ruby_lib/issues/838). Please make sure you have upgraded the client libraries.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
