### ISSUE TITLE
Timeout is out befor the istallation of the APK

### ISSUE THREAD

**Issue by kaoutarac** [appium/appium#11917]
## The problem

I try to install my APK that take 3 min in istallation with the commande line "c:\sdk\platform-tools\adb.exe -P 5037 -s 36759a2b install -r E:\AppiumTest\App\myapk.apk"
but with test i can not install it the time out message is displayed " timed out after 90000ms'" , i reconfigure 	 capabilities.setCapability("appWaitDuration", 300000); but it seems that is not taken into account the timeout is always 90000ms
## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Desktop OS/version used to run Appium:windows
* Node.js version (unless using Appium.app|exe):v10.14.2
* Mobile platform/version under test:android  "5.0"
* Real device or emulator/simulator:real device
* Appium CLI or Appium.app|exe:

## Details

my code is as bellow:
`public class AndroidSetup {
	
	protected static AndroidDriver driver;
	 protected static void APKSetup() throws MalformedURLException {

	 File appDir = new File("E:\\AppiumTest\\App");
	 File app = new File(appDir, "myapk.apk");
	 DesiredCapabilities capabilities = new DesiredCapabilities();

	 

	 capabilities.setCapability("deviceName", "Morphotablet2");
	 capabilities.setCapability("udid", "36759a2b"); //Give Device ID of your mobile phone
	 capabilities.setCapability("platformName", "Android");
	 capabilities.setCapability("platformVersion", "5.0");
	 capabilities.setCapability("appWaitDuration", 300000);

 
	  
	 capabilities.setCapability("appWaitPackage", "Morpho.Mims"); 
	
	 capabilities.setCapability("appWaitActivity", "md59df66af248edd832290a5bc6c60cb148.SplashScreen");
		
	 capabilities.setCapability("app", app.getAbsolutePath());
	 try {
		 driver = new AndroidDriver<MobileElement>(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);
		 driver.manage().timeouts().implicitlyWait(9000000, TimeUnit.MINUTES); 
		   } catch (MalformedURLException e) {

			e.printStackTrace();
		   }
	 }
`

## Link to Appium logs

[Appium] Welcome to Appium v1.10.0
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"E:\\AppiumTest\\App\\Morpho.Mims-Signed.apk","platformVersion":"5.0","appWaitActivity":"md59df66af248edd832290a5bc6c60cb148.SplashScreen","appWaitPackage":"Morpho.Mims","platformName":"Android","udid":"36759a2b","deviceName":"Morphotablet2","appWaitDuration":300000},"capabilities":{"alwaysMatch":{"appium:app":"E:\\AppiumTest\\App\\Morpho.Mims-Signed.apk","appium:appWaitActivity":"md59df66af248edd832290a5bc6c60cb148.SplashScreen","appium:appWaitDuration":300000,"appium:appWaitPackage":"Morpho.Mims","appium:deviceName":"Morphotablet2","platformName":"android","appium:platformVersion":"5.0","appium:udid":"36759a2b"},"firstMatch":[{}]}}
[W3C] Calling AppiumDriver.createSession() with args: [{"app":"E:\\AppiumTest\\App\\Morpho.Mims-Signed.apk","platformVersion":"5.0","appWaitActivity":"md59df66af248edd832290a5bc6c60cb148.SplashScreen","appWaitPackage":"Morpho.Mims","platformName":"Android","udid":"36759a2b","deviceName":"Morphotablet2","appWaitDuration":300000},null,{"alwaysMatch":{"appium:app":"E:\\AppiumTest\\App\\Morpho.Mims-Signed.apk","appium:appWaitActivity":"md59df66af248edd832290a5bc6c60cb148.SplashScreen","appium:appWaitDuration":300000,"appium:appWaitPackage":"Morpho.Mims","appium:deviceName":"Morphotablet2","platformName":"android","appium:platformVersion":"5.0","appium:udid":"36759a2b"},"firstMatch":[{}]}]
[BaseDriver] Event 'newSessionRequested' logged at 1546011243458 (16:34:03 GMT+0100 (Afr. centrale Ouest))
[Appium] Creating new AndroidDriver (v4.7.0) session
[Appium] Capabilities:
[Appium]   platformName: android
[Appium]   app: E:\AppiumTest\App\Morpho.Mims-Signed.apk
[Appium]   appWaitActivity: md59df66af248edd832290a5bc6c60cb148.SplashScreen
[Appium]   appWaitDuration: 300000
[Appium]   appWaitPackage: Morpho.Mims
[Appium]   deviceName: Morphotablet2
[Appium]   platformVersion: 5.0
[Appium]   udid: 36759a2b
[BaseDriver] W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP desired capabilities {"app":"E:\\AppiumTest\\App... were provided
[BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"platformNa...
[BaseDriver] Session created with session id: aacc18fc-20ac-40cd-ba9d-5d532a04a728
[AndroidDriver] Java version is: 1.8.0_191
[ADB] Checking whether adb is present
[ADB] Found 2 'build-tools' folders under 'c:\sdk' (newest first):
[ADB]     c:/sdk/build-tools/28.0.0-rc2
[ADB]     c:/sdk/build-tools/27.0.3
[ADB] Using adb.exe from c:\sdk\platform-tools\adb.exe
[AndroidDriver] Retrieving device list
[ADB] Trying to find a connected android device
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[AndroidDriver] Using device: 36759a2b
[ADB] Setting device id to 36759a2b
[ADB] Running 'c:\sdk\platform-tools\adb.exe -P 5037 -s 36759a2b shell getprop ro.build.version.sdk'
[ADB] Current device property 'ro.build.version.sdk': 21
[ADB] Device API level: 21
[BaseDriver] Using local app 'E:\AppiumTest\App\Morpho.Mims-Signed.apk'
[AndroidDriver] Checking whether app is actually present
[AndroidDriver] Starting Android session
[ADB] Running 'c:\sdk\platform-tools\adb.exe -P 5037 -s 36759a2b wait-for-device'
[ADB] Running 'c:\sdk\platform-tools\adb.exe -P 5037 -s 36759a2b shell echo ping'
[AndroidDriver] Pushing settings apk to device...
[ADB] Getting install status for io.appium.settings
[ADB] Running 'c:\sdk\platform-tools\adb.exe -P 5037 -s 36759a2b shell dumpsys package io.appium.settings'
[ADB] 'io.appium.settings' is installed
[ADB] Getting package info for 'io.appium.settings'
[ADB] Running 'c:\sdk\platform-tools\adb.exe -P 5037 -s 36759a2b shell dumpsys package io.appium.settings'
[ADB] Checking whether aapt is present
[ADB] Using aapt.exe from c:\sdk\build-tools\28.0.0-rc2\aapt.exe
[ADB] The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('2.11.0' >= '2.11.0')
[ADB] There is no need to install/upgrade 'C:\Program Files (x86)\Appium\resources\app\node_modules\io.appium.settings\apks\settings_apk-debug.apk'
[ADB] Running 'c:\sdk\platform-tools\adb.exe -P 5037 -s 36759a2b shell ps'
[AndroidDriver] io.appium.settings is already running. There is no need to reset its permissions.
[ADB] Device API level: 21
[ADB] Running 'c:\sdk\platform-tools\adb.exe -P 5037 -s 36759a2b shell settings put secure mock_location 1'
[AndroidDriver] setDeviceLanguageCountry requires language or country.
[AndroidDriver] Got language: 'undefined' and country: 'undefined'
[Logcat] Starting logcat capture
[ADB] Getting device platform version
[ADB] Running 'c:\sdk\platform-tools\adb.exe -P 5037 -s 36759a2b shell getprop ro.build.version.release'
[ADB] Current device property 'ro.build.version.release': 5.0.2
[ADB] Running 'c:\sdk\platform-tools\adb.exe -P 5037 -s 36759a2b shell wm size'
[ADB] Running 'c:\sdk\platform-tools\adb.exe -P 5037 -s 36759a2b shell getprop ro.product.model'
[ADB] Current device property 'ro.product.model': MPH-MB001A
[ADB] Running 'c:\sdk\platform-tools\adb.exe -P 5037 -s 36759a2b shell getprop ro.product.manufacturer'
[ADB] Current device property 'ro.product.manufacturer': Safran Identity & Security
[AndroidDriver] Parsing package and activity from app manifest
[ADB] Using the alternative activity name detection method because of: Could not find apkanalyzer.bat in c:\sdk\platform-tools\apkanalyzer.bat,c:\sdk\emulator\apkanalyzer.bat,c:\sdk\tools\apkanalyzer.bat,c:\sdk\tools\bin\apkanalyzer.bat,c:\sdk\build-tools\28.0.0-rc2\apkanalyzer.bat,c:\sdk\build-tools\27.0.3\apkanalyzer.bat. Do you have the Android SDK installed at 'c:\sdk'?
[ADB] Extracting package and launch activity from manifest
[ADB] Package name: 'Morpho.Mims'
[ADB] Main activity name: 'md59df66af248edd832290a5bc6c60cb148.SplashScreen'
[AndroidDriver] Parsed package and activity are: Morpho.Mims/md59df66af248edd832290a5bc6c60cb148.SplashScreen
[ADB] Getting install status for Morpho.Mims
[ADB] Running 'c:\sdk\platform-tools\adb.exe -P 5037 -s 36759a2b shell dumpsys package Morpho.Mims'
[ADB] 'Morpho.Mims' is not installed
[ADB] Getting install status for Morpho.Mims
[ADB] Running 'c:\sdk\platform-tools\adb.exe -P 5037 -s 36759a2b shell dumpsys package Morpho.Mims'
[ADB] 'Morpho.Mims' is not installed
[ADB] App 'E:\AppiumTest\App\Morpho.Mims-Signed.apk' is not installed
[ADB] Installing 'E:\AppiumTest\App\Morpho.Mims-Signed.apk'
[ADB] Device API level: 21
[ADB] Running 'c:\sdk\platform-tools\adb.exe -P 5037 -s 36759a2b install E\:\\AppiumTest\\App\\Morpho.Mims-Signed.apk'
[ADB] Running 'c:\sdk\platform-tools\adb.exe -P 5037 -s 36759a2b install E\:\\AppiumTest\\App\\Morpho.Mims-Signed.apk'
[AndroidDriver] Shutting down Android driver
[AndroidDriver] Called deleteSession but bootstrap wasn't active
[Logcat] Stopping logcat capture
[ADB] Running 'c:\sdk\platform-tools\adb.exe -P 5037 -s 36759a2b shell am force-stop io.appium.unlock'
[AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[BaseDriver] Event 'newSessionStarted' logged at 1546011426920 (16:37:06 GMT+0100 (Afr. centrale Ouest))
[W3C] Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command 'c\:\\sdk\\platform-tools\\adb.exe -P 5037 -s 36759a2b install E\:\\AppiumTest\\App\\Morpho.Mims-Signed.apk' timed out after 90000ms'; Stderr: ''; Code: 'null'
[W3C]     at execFunc (C:\Program Files (x86)\Appium\resources\app\node_modules\appium-adb\lib\tools\system-calls.js:326:13)
[HTTP] <-- POST /wd/hub/session 500 183513 ms - 1046
[HTTP] 

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
There is `androidInstallTimeout` capability to customise the timeout

**Comment by imurchie** [comment]
The `adbExecTimeout` may also be at play here.

**Comment by mykola-mokhnach** [comment]
@rajkumar-cp The actions are done by adb and it is an adb/device issue if they times out. All you can do in Appium is to increase the timeout and hope for the best.

**Comment by kaoutarac** [comment]
thank you androidInstallTimeout resolve my probleme
