### ISSUE TITLE
Appium close the session after command expired

### ISSUE THREAD

**Issue by sunandy1984** [appium/appium#11928]
## The problem

I am trying to run android app automation testing with Appium (python client). I set newCommandTimeout to 1800 seconds in capability.  But seems the session is closed after only 2 seconds after one command is sent. I met the issue several times but I don't know how to reproduce it.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.10.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: android api 28
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: Appium.app

## Details

I met the issue several times but I can't find what's wrong. sometimes, Appium will close the session incorrectly.  I can't confirm whether this is a bug or my configuration issue. So could you please take a look ?

## Link to Appium logs

I start the emulator at 2019-01-03 11:55:41 around
The session is closed at 2019-01-03 11:56:17 around

log link: https://gist.github.com/sunandy1984/8c34580ed773d58e2ffa598f1ec78318

## Code To Reproduce Issue [ Good To Have ]

Sorry I can't find a way to reproduce it.

**Comment by mykola-mokhnach** [comment]
It looks that there are two parallel sessions and one one of them is killed due to the timeout while the other one is still running. Did you try `--session-override` option?

**Comment by sunandy1984** [comment]
Not yet but I can try this option and observe whether this issue can be resolved.

Thanks.

**Comment by sunandy1984** [comment]
Oh, I see how to do it now. you can close this ticket.

Thanks.
