### ISSUE TITLE
How to test wkwebview on headless

### ISSUE THREAD

**Issue by shiratsu** [appium/appium#11922]
Hi.
I’m trying to test my app which has webpage on wkwebview.

It can be tested on no-headless mode.
But on headless mode it can’t be tested.

appium produce ‘not found element error’.

Language is php.
Does anyone know what this problem is?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mykola-mokhnach** [comment]
Please use Appium forum for asking questions

**Comment by shiratsu** [comment]
sure
I will close this issue.
