### ISSUE TITLE
IOS Debug Proxy does not respond when appium session is running

### ISSUE THREAD

**Issue by debugger89** [appium/appium#11924]
## The problem

IOS debug proxy web service connectivity hangs up when there is a Appium web session up and running. This blocks me inspect the webview in the same device through the chrome debugger when the appium session is up and running using the device. 

## Environment

Mac Os X 10.14.1
Xcode 10.1
Appium Server 1.10 (Through appium desktop for mac & native appium)
IOS Simulator : IPhone 5 - 10.3.1

## Appium logs

[RemoteDebugger] Debugger returned data for message '-17' but we were not waiting for that message! result: '{"result":{"type":"string","value":"980,1409,2"},"wasThrown":false}'; error: 'null'

## Code To Reproduce Issue

1. Start an Appium web session in the simulator. 
```java
DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
desiredCapabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "Safari");
desiredCapabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
desiredCapabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.3");
desiredCapabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, "10000");
desiredCapabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 5");
URL url = new URL("http://127.0.0.1:4723/wd/hub");
driver = new IOSDriver(url, desiredCapabilities);
```
2. Now try to use the debug proxy web service for getting a screenshot. (The websocket message is sent via a 3rd party chrome extension)
```
ws://127.0.0.1:9191/devtools/page/1
```
```json
{
  "id": 1,
  "method": "Page.startScreencast",
  "params": {
    "format": "jpeg"
  }
}
{"id":1,"result":{}}
```
### Expected result : 

The web socket should receive another message with the screenshot base64 image string.
```json
{
  "id": 1,
  "method": "Page.startScreencast",
  "params": {
    "format": "jpeg"
  }
}

{"id":1,"result":{}}

{
  "method": "Page.screencastFrame",
  "params": {
    "data": "iVBORw0KGgoAAAANSUhEUgAAAUAAAAHMCAYAAACk4......",
    "metadata": {
      "pageScaleFactor": 2,
      "offsetTop": 0,
      "deviceWidth": 320,
      "deviceHeight": 460,
      "scrollOffsetX": 0,
      "scrollOffsetY": 0,
      "timestamp": "2019-01-01T08:14:17.433Z"
    },
    "sessionId": 1
  }
}
```

### Observations

Appium remote debugger log suggests that the message is captured by remote debugger but my websocket client never gets the message.

```
[RemoteDebugger] Debugger returned data for message '-17' but we were not waiting for that message! result: '{"result":{"type":"string","value":"980,1409,2"},"wasThrown":false}'; error: 'null'
```

If the appium session is terminated, the above message works without any issue and returns the intended result.

**Comment by mykola-mokhnach** [comment]
Closed as inactive

**Comment by debugger89** [comment]
Can't we keep this open until someone has time to look at the issue?

**Comment by mykola-mokhnach** [comment]
The probability an issue will be resolved after more than one month of waiting is quite close to zero :(

**Comment by mykola-mokhnach** [comment]
In Appium@beta the debug proxy is not used anymore. The custom NodeJS-based protocol client is used instead. Also, there is a possibility this stuff works better/different than before.

**Comment by umutuzgur** [comment]
@mykola-mokhnach We haven't merged the PR yet

**Comment by mykola-mokhnach** [comment]
@umutuzgur Thanks for the update. Feel free to comment this issue when the stuff is merged

**Comment by umutuzgur** [comment]
Sure. Will do

**Comment by umutuzgur** [comment]
@debugger89 You can now try appium@beta. We removed iwdp there and it should more reliable
