### ISSUE TITLE
 Failure getting list of active applications

### ISSUE THREAD

**Issue by AvrahamAtia** [appium/appium#11923]
## The problem
 Failure getting list of active applications
## Environment
Appium server: 1.9.1
Node: v10.4.1
Allure: 2.8.0
xcode-select: 10.1 
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T21:49:05+02:00)
Maven home: /usr/local/Cellar/maven/3.5.3/libexec
Java version: 11.0.1, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk-11.0.1.jdk/Contents/Home
Default locale: en_IL, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.6", arch: "x86_64", family: "mac"

## Details
Parallel execution iOS real devices and simulator.

## Link to Appium logs
[Xcode]     t = 67104.91s Open com.shutterfly.mopho.prototype
[Xcode]     t = 67104.91s     Launch com.shutterfly.mopho.prototype
[Xcode] 
[Xcode]     t = 67104.99s         Wait for accessibility to load
[Xcode] 
[Xcode]     t = 67106.41s         Wait for com.shutterfly.mopho.prototype to idle
[Xcode] 
[Xcode]     t = 67166.42s             App event loop idle notification not received, will attempt to continue.
[Xcode] 
[Xcode]     t = 67166.42s             App animations complete notification not received, will attempt to continue.
[Xcode] 2019-01-01 11:32:16.204292+0200 WebDriverAgentRunner-Runner[23355:193499] Enqueue Failure: Failure to determine system application: (null) /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode] 
[Xcode] 2019-01-01 11:33:21.207391+0200 WebDriverAgentRunner-Runner[23355:193499] Enqueue Failure: Failure fetching attributes for (null): Error Domain=com.apple.XCTestErrorDomain Code=1000 "Timeout waiting for fulfillment of promise for 'Fetching attributes for (null)'." UserInfo={NSLocalizedDescription=Timeout waiting for fulfillment of promise for 'Fetching attributes for (null)'.} /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode] 
[Xcode] 2019-01-01 11:33:21.208218+0200 WebDriverAgentRunner-Runner[23355:193499] Enqueue Failure: Failure getting list of active applications: (null) /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode]

**Comment by AvrahamAtia** [comment]
Sorry, it fixed by "brew upgrade -g carthage"

**Comment by AvrahamAtia** [comment]
The same error appear again!!

**Comment by mykola-mokhnach** [comment]
Please report the issue to https://github.com/facebook/WebDriverAgent
Closed as third party problem.

**Comment by AvrahamAtia** [comment]
Duplicate:  https://github.com/facebook/WebDriverAgent/issues/1054

**Comment by kamaleshrnp** [comment]
**Environment Details :**
MacOs Mojave 10.14.4
Appium Server 1.12.1
Xcode 10.2
Appium Java Client 6.1.0

**Capabilities:**

caps.setCapability("automationName", prop.getProperty("ios.automationName"));
caps.setCapability("platformVersion", prop.getProperty("ios.platformVersion"));
caps.setCapability("platformName", prop.getProperty("ios"));
caps.setCapability("deviceName", prop.getProperty("ios.deviceName"));
caps.setCapability("autoAcceptAlerts", prop.getProperty("ios.autoAcceptAlerts"));
caps.setCapability("showXcodeLog","true");
caps.setCapability("useNewWDA","true");
caps.setCapability("waitForQuietness","false");
caps.setCapability("wdaEventloopIdleDelay","3");
caps.setCapability("eventLoopIdleDelaySec", "1");
caps.setCapability("noReset", prop.getProperty("ios.noReset"));

**Comments**

1) Manually, It works perfectly in appium desktop version 1.12.1
2)I tried with various Xcode Versions ; but nothing helped(got errors like Couldn't identify simulators with particular versions. But they are actually installed)
3)Tried removing capabilities "useNewWDA" and reduce the delay for capabilities("wdaEventloopIdleDelay & eventLoopIdleDelay)

Need help !

**Comment by ishpreetnanda14** [comment]
Any update on this? Was anyone able to resolve this issue?

**Comment by balazs630** [comment]
Had the same error with Appium 1.15.0, testing an iOS app. Solved by reinstalling `Carthage`which is the dependency manager for WebDriverAgent for iOS. Seems like there was a corrupted Carthage cache somewhere, and the reinstall cleaned it up.

If you installed Carthage with Homebrew, simply: 
```
brew uninstall carthage
brew install carthage
```

**Comment by Sha-123** [comment]
Did any one found solution for this error? If found Please share .
