### ISSUE TITLE
Running Expresso Driver in Parallel with Real Devices

### ISSUE THREAD

**Issue by MarkSpencerTan** [appium/appium#11936]
## The problem

When running the automation with real devices in parallel using the Expresso Driver, I am getting an error below after attempting to click/interact with an element:
**An unknown server-side error occurred while processing the command. Original error: Android bootstrap socket crashed: Error: This socket has been ended by the other party.**

I am setting the systemPort differently for each device connected on the capabilities just like how I did it on UiAutomator2; does Expresso support parallel devices yet?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0
* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium: Windows  10
* Node.js version (unless using Appium.app|exe): v8.11.4
* Mobile platform/version under test: Android (version varying but mostly Android 5+)
* Real device or emulator/simulator: Real Devices
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs
[Appium Server Logs](https://gist.github.com/MarkSpencerTan/2a689da90d3498864498c8d1d769837c)

## How To Reproduce Issue [ Good To Have ]
- Specified Expresso as the automationName on capabilities
- incremented the systemPort capability per real device
- Run an Appium test with multiple device in parallel with one appium server (tested between 10-18 devices in parallel)
- Try to click an element for all the devices

**Comment by mykola-mokhnach** [comment]
> [35m[Appium][39m   automationName: Expresso

hm...

**Comment by MarkSpencerTan** [comment]
@mykola-mokhnach omg thank you for pointing that out ... I've been spelling it wrong for days now 🤦‍♂️
