### ISSUE TITLE
iOS App freezes or hangs as soon as launched Appium

### ISSUE THREAD

**Issue by ankit9289** [appium/appium#11930]
## The problem

The app gets hanged as soon as launched by Appium and we are not able to perform any action even manually too.
Click commands are executing if we check logs but nothing happening on app

## Environment
Appium - 1.11.0-beta.3
Xcode - 10.1

## Link to Appium logs

https://gist.github.com/ankit9289/039111d0d7615f03d87b6c085a2759e9#file-appiumlogs-log

**Comment by mykola-mokhnach** [comment]
I don't observe any explicit issues in the log. This looks like a problem with the app itself to me

**Comment by ankit9289** [comment]
The problem is when the app gets launched with Appium it goes in to hang state where as when we manually run it works fine so when the app gets launched with Appium it goes to hang to no events are performing on the app actually.

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing we can do there on Appium side. Try to report your problem to https://github.com/facebook/WebDriverAgent or to Apple.
