### ISSUE TITLE
Collapse menu with accessibilityID, appium return NoSuchElementError

### ISSUE THREAD

**Issue by LayMuiToh** [appium/appium#11938]
## The problem

the element is set with accessibilityID = menu, 
Appium return with a status 200 and NoSuchElementError
when the element is visible on the page/screen
i am able to access and click on other element on the same page but not this collapse menu on the top left hand on the mobile page.

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue v1.9.1
* Desktop OS/version used to run Appium: macOS 10.13.6
* Node.js version (unless using Appium.app|exe): v9.1.0
* Mobile platform/version under test: iphone 6s iOS 12.1
* Real device or emulator/simulator:real device
* Appium CLI or Appium.app|exe: appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/LayMuiToh/3a90dd316da2cbf373e2fd9302679b20

## Code To Reproduce Issue [ Good To Have ]
module.exports = () => {
 describe('Menu test', () => {
    it('should able to select collapse menu icon and go to the Menu page', () => {
      $('~menu').waitForVisible() &&
      $('~menu').click();
....

where the accessibility ID of the collapse menu element is 'menu'

**Comment by mykola-mokhnach** [comment]
The page tree itself is built by WebDriverAgent based on the information from XCTest. There is nothing we can do about it on Appium side. You can also try to raise a bug to Apple or to https://github.com/facebook/WebDriverAgent

Closed as third party issue

**Comment by LayMuiToh** [comment]
HI I got this resolved. I need to use mobile execute command not the webdriverio API directly
http://appium.io/docs/en/commands/mobile-command/
