### ISSUE TITLE
iOS app with multiple web views only has one web view context and one window handle in that context

### ISSUE THREAD

**Issue by jamespizzurro** [appium/appium#11946]
## The problem

There doesn't appear to be a working way to switch contexts or window handles from one iOS web view to another, as there seems to only ever be one web view context (with a name that starts with "WEBVIEW_") and one window handle in that context. Furthermore, attempting to switch window handles in that one context -- which admittedly doesn't make too much sense given there's only one window handle to begin with, and it seems to already be set to that one by default -- hangs Appium Server and the connection eventually times out.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0 (via Appium.app)
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: macOS Mojave 10.14.2
* Node.js version (unless using Appium.app|exe): I'm using Appium.app
* Mobile platform/version under test: iOS 12.1
* Real device or emulator/simulator: Emulator (iPhone XR)
* Appium CLI or Appium.app|exe: Appium.app 1.10.0

## Details

I've got a pretty simple app that has two tabs that contain one view each, where each view per tab contains a single web view (WKWebView) that navigate to different URLs when the app is started. No matter what I do, it seems the only web view context available and its one window handle is always set to the first web view, with seemingly no mention in the logs of the latter web view in the other tab; this behavior holds even when I switch tabs, where the web view from the first tab is the only one with a corresponding context and window handle returned.

Perhaps related: attempting to "switch" to this one window handle times out, i.e. the connection hangs for a long while and nothing happens, but I see in the Appium logs that the request was relayed.

## Link to Appium logs

https://gist.github.com/jamespizzurro/785e9ee58fd09c70c3cdf6cce08a4afa

## Code To Reproduce Issue [ Good To Have ]

This isn't a complete working example, just a Java code snippet, but hopefully it's self-explanatory what I'm trying to do:
```java
// assumption: this.driver is set to a properly-configured instance of IOSDriver

Set<String> contextNames = this.driver.getContextHandles();
// ^ returns only one context
for (String contextName : contextNames) {
    if (!contextName.startsWith("WEBVIEW_")) {
        continue;
    }

    this.driver.context(contextName);

    Set<String> windowNames = this.mobileDriver.getWindowHandles();
    // ^ returns only one window handle
    for (String windowName : windowNames) {
        this.mobileDriver.switchTo().window(windowName);
        // ^ Appium hangs during execution of the line above; this is reflected in the logs I've provided

        // TODO: do stuff with the content of the web view here
    }
}
```

**Comment by pavanbachu06** [comment]
Can you try to debug using safari? Under safari you have an option under developer tools > select the required device and you would see all the webviews on that page.

**Comment by jamespizzurro** [comment]
@pavanbachu06 Great idea. Here's the result:

<img width="744" alt="screen shot 2019-01-04 at 9 36 13 pm" src="https://user-images.githubusercontent.com/1945036/50719354-e53af400-1068-11e9-9c36-60f5e70c9f6f.png">

So unlike what's returned by getContextHandles and getWindowHandles, there are indeed two entries in this list as expected, however you can see the second entry is grayed out, and even when I click around my sample app to expose the web view that corresponds to that grayed out entry, it remains unselectable from within Safari via this menu while the first entry remains selectable even when it isn't in view. Not exactly sure what to make of this.

**Comment by pavanbachu06** [comment]
@jamespizzurro  this is something to do how the app has been built not Appium if the webviews are exposed, appium would be able to read it

**Comment by jamespizzurro** [comment]
@pavanbachu06 That doesn't explain the behavior I'm observing with Appium always only having access to the first web view's context though, right? Even when I switch to make the other web view visible (and hide the first web view)? Do you have any insight into that? I would expect Appium to at least retrieve the context of the second web view when it is visible and the first one is not, per the context I provided.

**Comment by jamespizzurro** [comment]
@pavanbachu06 I've changed the way the web views in the app are presented by moving them into the same view (as opposed to having one in each tabbed view) and retested everything. Now, before I use Appium to set context, Safari seems to see both of the web views and neither are grayed out:

<img width="738" alt="screen shot 2019-01-08 at 2 06 45 pm" src="https://user-images.githubusercontent.com/1945036/50852890-cf6e4d00-134e-11e9-9625-8a923019eb7f.png">

However, just as before, attempting to use the sample Java code I provided causes Appium to hang and the client eventually times out, and from the logs, it seems Appium is still only seeing one web view context and window handler at a time. Full logs here: https://gist.github.com/jamespizzurro/71e0bf061aefc9bfa47ff5fee12d12c9

Given this new information, it seems pretty clear to me that there's a problem here beyond just the way my sample app is built. What's unclear to me is where in the stack the problem is, whether it be Appium or one of the technologies it relies on.

**Comment by mykola-mokhnach** [comment]
Closed as inactive

**Comment by jamespizzurro** [comment]
@mykola-mokhnach I am still having all of the issues described here. Please consider reopening this, as I am still awaiting responses from my comments. This is an ongoing problem. @pavanbachu06

**Comment by kes-295** [comment]
Hey guys, did someone manage to resolve this problem?

**Comment by jamespizzurro** [comment]
This issue still appears to be unresolved; invoking `this.mobileDriver.switchTo().window(windowName);` via the Java client in a Java test results in execution hanging indefinitely. Here's what's output to the log when this happens (which is the same exact behavior I originally observed back in January):
```
[HTTP] --> POST /wd/hub/session/bad6c89f-57e6-488a-9437-1b233c1193fa/window
[HTTP] {"handle":"4501.1"}
[W3C (bad6c89f)] Calling AppiumDriver.setWindow() with args: ["4501.1","4501.1","bad6c89f-57e6-488a-9437-1b233c1193fa"]
[XCUITest] Executing command 'setWindow'
```
And here's are some updated environment details:
> Appium version (or git revision) that exhibits the issue: 1.13.0 (via Appium.app)
> Last Appium version that did not exhibit the issue (if applicable): N/A
> Desktop OS/version used to run Appium: macOS Mojave 10.14.5
> Node.js version (unless using Appium.app|exe): I'm using Appium.app
> Mobile platform/version under test: iOS 12.2
> Real device or emulator/simulator: Emulator (iPhone X)
> Appium CLI or Appium.app|exe: Appium.app 1.13.0

**Comment by jamespizzurro** [comment]
@mykola-mokhnach I am still having all of the issues described here. Please consider reopening this, as I am still awaiting responses for my comments. This is an ongoing problem. Please let me know if I can be of any further assistance. @pavanbachu06 @kes-295

**Comment by mykola-mokhnach** [comment]
Do you use the most recent server version? Are the web views visible in safari remote debugger?

**Comment by imurchie** [comment]
@jamespizzurro I would be happy to try to figure this out. Do you have an app that can reproduce it? Or the skeleton of a reproducing case?

**Comment by jamespizzurro** [comment]
@mykola-mokhnach I'm using the latest stable Appium Desktop version 1.15.1. I am working on testing against 1.17.0, which I understand is still in pre-release status. With regards to the Safari debugger, I am observing the same behavior that I detailed in this previous comment: https://github.com/appium/appium/issues/11946#issuecomment-452419296

@imurchie Thank you! Here's a sample app you can use in conjunction with the Appium Java client code I provided in this issue's initial description (or analogous client code in a different programming language) to reproduce this issue: [example_app.zip](https://github.com/appium/appium/files/4376803/example_app.zip)

**Comment by imurchie** [comment]
Thanks. I'll give it a go.

**Comment by mykola-mokhnach** [comment]
>  I am working on testing against 1.17.0, which I understand is still in pre-release status.

The latest stable is 1.17. It is out of pre-release status

**Comment by jamespizzurro** [comment]
@mykola-mokhnach Ah sorry, I was referring to Appium Desktop, which is still marked as 'pre-release' here: [https://github.com/appium/appium-desktop/releases](https://github.com/appium/appium-desktop/releases). Regardless, I am testing against Appium 1.17.0 (not Appium Desktop 1.17.0, just in case) now and will report my findings soon.

**Comment by jamespizzurro** [comment]
@mykola-mokhnach @imurchie I am no longer able to reproduce this issue in Appium 1.17.0, however in order to test this properly, I had to have Safari open on the same workstation I was using to run my iOS emulator and my Appium Java client code, otherwise getContexts() was returning null like this:
```
[HTTP] --> GET /wd/hub/session/0450a4b7-2bd1-4f1e-9b2e-3f8b5f82531f/contexts
[HTTP] {}
[debug] [W3C (0450a4b7)] Calling AppiumDriver.getContexts() with args: ["0450a4b7-2bd1-4f1e-9b2e-3f8b5f82531f"]
[debug] [XCUITest] Executing command 'getContexts'
[debug] [XCUITest] Getting list of available contexts
[debug] [iOS] Retrieving contexts and views
[debug] [XCUITest] Selecting by url: false 
[RemoteDebugger] Remote Debugger version 8.6.1
[debug] [RemoteDebugger] useNewSafari --> false
[debug] [RemoteDebugger] Checking which communication style to use (non-Safari on platform version '13.3')
[debug] [RemoteDebugger] Platform version equal or higher than '12.2': true
[RemoteDebugger] Setting communication protocol: using full Web Inspector protocol communication
[debug] [RemoteDebugger] Connecting to remote debugger through unix domain socket: '/private/tmp/com.apple.launchd.y1ZzPlAnCT/com.apple.webinspectord_sim.socket'
[debug] [RemoteDebugger] Debugger socket connected
[debug] [RemoteDebugger] Sending connection key request
[debug] [RemoteDebugger] Sending '_rpc_reportIdentifier:' message (id: 0): 'setConnectionKey'
[debug] [RemoteDebugger] Sending to Web Inspector took 7ms
[debug] [RemoteDebugger] Sending connection key request
[debug] [RemoteDebugger] Sending '_rpc_reportIdentifier:' message (id: 1): 'setConnectionKey'
[debug] [RemoteDebugger] Sending to Web Inspector took 3ms
[debug] [RemoteDebugger] Selecting application
[debug] [RemoteDebugger] No applications currently connected.
[debug] [XCUITest] No web frames found.
[debug] [W3C (0450a4b7)] Responding to client with driver.getContexts() result: ["NATIVE_APP"]
[HTTP] <-- GET /wd/hub/session/0450a4b7-2bd1-4f1e-9b2e-3f8b5f82531f/contexts 200 72 ms - 24
```
Is this expected behavior? If not, I can search for that issue or create a new one if I'm not able to find it in the issues list. Regardless, I think this particular issue can now be closed.

**Comment by imurchie** [comment]
That is generally a timing situation. Try polling for the contexts for a moment.

I too was able to get both contexts. I needed to click on the "Accessible" button for the Web Inspector to report the second one.

**Comment by jamespizzurro** [comment]
@imurchie Gotcha, thanks for the help. If it really is just a timing/race condition issue, I can probably work with that, but if I'm somehow able to discern it is not, I'll search for the issue or create a new one if it doesn't already exist, then link it back here for posterity. In the meantime, I'll close this issue!

**Comment by imurchie** [comment]
Sounds good. In 1.17.0 there is also a capability, `webviewConnectTimeout`, to specify a length of time (in ms) to poll on the server side. It will wait up to that long for a webview to be present. Otherwise the endpoint checks with the WebInspector and returns whatever is returned, so it Safari isn't reporting it yet, it won't be returned.

If an issue with webviews comes up, feel free to also mention me in the issue. I check issues but that will flag it to me faster generally speaking.

**Comment by jamespizzurro** [comment]
@imurchie Thank you very much for the `webviewConnectTimeout` suggestion; setting that new capability to 5000 (ms) seems to have done the trick for me and our test app! :)

**Comment by imurchie** [comment]
Awesome! Glad to hear it helps.
