### ISSUE TITLE
Ionic element's onchange= and onfocus= events aren’t triggered when using SendKeys()

### ISSUE THREAD

**Issue by matthew-horrocks** [appium/appium#11955]
## The problem

Afternoon all,

I’m writing some tests for an Ionic app using appium.

When I send text to an Ionic text box using appium / Selenium's `SendKeys()`, the element's `onchange=` and `onfocus=` events aren’t triggered. 

## Details

I’m in the NATIVE_APP context when interacting with the app and the text is displayed in the text box once appium / selenium’s SendKeys() method has been called.

If I manually type text into the text box, the events are triggered correctly.

Is this expected behaviour? Or is there something special about the NATIVE_APP context that stops the onchange= and onfocus= events from being triggered?

The HTML for the textarea is;

```
    <ion-textarea
        id="messageBox"
        clearInput
        [(ngModel)]="messageText"
        [class.moreTextLayout]="moreTextLayout"
        name="messageText"
        ngDefaultControl
        wrap="true"
        placeholder="Aa"
        (ionChange)="keypress()"
        (ionFocus)="onFocused()"
    ></ion-textarea>

```
And it's rendered as;
```
<android.view.View index="2" package="com.netwealth.app" class="android.view.View" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,1470][1080,1638]" displayed="true">
  <android.view.View index="0" package="com.netwealth.app" class="android.view.View" text="" resource-id="MessageInputContainer" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,1470][1080,1638]" displayed="true">
    <android.view.View index="0" package="com.netwealth.app" class="android.view.View" text="" resource-id="messageBox" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[21,1491][921,1617]" displayed="true">
      <android.widget.EditText index="0" package="com.netwealth.app" class="android.widget.EditText" text="" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="true" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[49,1493][918,1614]" displayed="true" />
    </android.view.View>

    <android.view.View index="1" package="com.netwealth.app" class="android.view.View" text="" resource-id="SendMessageButton" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[952,1483][1068,1624]" displayed="true">
      
      <android.widget.Button index="0" package="com.netwealth.app" class="android.widget.Button" text="" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[958,1493][1063,1598]" displayed="true" />
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

**Comment by mykola-mokhnach** [comment]
I would say this is something, that should rather be investigated on ionic side. Appium server simply triggers the standard functions for text input available in UIA framework and it is up to the ionic to interpret the resulting events. I would try switching to a web view context and synthesizing the necessary events manually as a workaround.

**Comment by matthew-horrocks** [comment]
Thanks.

Switching to the web view context and sending text to the element does trigger the events correctly.

Unfortunately we can only switch to the webview context in a debug build of the app... http://appium.io/docs/en/writing-running-appium/web/hybrid/#automating-hybrid-android-apps

**Comment by mykola-mokhnach** [comment]
Another possible workaround might be to use Espresso driver and `mobile:backdoor` call. Otherwise I don't see many possibilities there with UIA2
