### ISSUE TITLE
i am getting the some issue please help me out here

### ISSUE THREAD

**Issue by i24Seven** [appium/appium#11950]
[info] [35m[Appium][39m Welcome to Appium v1.10.0
[info] [35m[Appium][39m Non-default server args:
[info] [35m[Appium][39m   address: 127.0.0.1
[info] [35m[Appium][39m   sessionOverride: true
[info] [35m[Appium][39m Appium REST http interface listener started on 127.0.0.1:4723[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{"desiredCapabilities":{"appActivity":"com.linkedin.android.home.HomeActivity","appPackage":"com.linkedin.android","platformVersion":"7.1.2","browserName":"","platformName":"Android","udid":"a0fde0547d94","deviceName":"Redmi 4"},"capabilities":{"firstMatch":[{"appium:appActivity":"com.linkedin.android.home.HomeActivity","appium:appPackage":"com.linkedin.android","browserName":"","appium:deviceName":"Redmi 4","platformName":"android","appium:platformVersion":"7.1.2","appium:udid":"a0fde0547d94"}]}}[39m
[debug] [35m[W3C][39m Calling AppiumDriver.createSession() with args: [{"appActivity":"com.linkedin.android.home.HomeActivity","appPackage":"com.linkedin.android","platformVersion":"7.1.2","browserName":"","platformName":"Android","udid":"a0fde0547d94","deviceName":"Redmi 4"},null,{"firstMatch":[{"appium:appActivity":"com.linkedin.android.home.HomeActivity","appium:appPackage":"com.linkedin.android","browserName":"","appium:deviceName":"Redmi 4","platformName":"android","appium:platformVersion":"7.1.2","appium:udid":"a0fde0547d94"}]}]
[debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1546741589385 (07:56:29 GMT+0530 (India Standard Time))
[warn] [35m[Appium][39m Consider setting 'automationName' capability to 'UiAutomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.
[info] [35m[Appium][39m Creating new AndroidDriver (v4.8.0) session
[info] [35m[Appium][39m Capabilities:
[info] [35m[Appium][39m   browserName: 
[info] [35m[Appium][39m   platformName: android
[info] [35m[Appium][39m   appActivity: com.linkedin.android.home.HomeActivity
[info] [35m[Appium][39m   appPackage: com.linkedin.android
[info] [35m[Appium][39m   deviceName: Redmi 4
[info] [35m[Appium][39m   platformVersion: 7.1.2
[info] [35m[Appium][39m   udid: a0fde0547d94
[debug] [35m[BaseDriver][39m W3C capabilities {"alwaysMatch":{"browserNam... and MJSONWP desired capabilities {"appActivity":"com.linkedi... were provided
[debug] [35m[BaseDriver][39m Creating session with W3C capabilities: {"alwaysMatch":{"browserNam...
[info] [35m[BaseDriver][39m Session created with session id: b6e76f94-ee9a-4320-83f9-33fdec2f0fa5[info] [35m[AndroidDriver][39m Java version is: 1.8.0_191
[info] [35m[AndroidDriver][39m Retrieving device list
[debug] [35m[ADB][39m Trying to find a connected android device
[debug] [35m[ADB][39m Getting connected devices...[debug] [35m[ADB][39m 1 device(s) connected
[info] [35m[AndroidDriver][39m Using device: a0fde0547d94
[debug] [35m[ADB][39m Setting device id to a0fde0547d94
[debug] [35m[ADB][39m Running 'D:\APPIUMTOOLS\ANDROIDSDK\platform-tools\adb.exe -P 5037 -s a0fde0547d94 shell getprop ro.build.version.sdk'[debug] [35m[ADB][39m Current device property 'ro.build.version.sdk': 25
[debug] [35m[ADB][39m Device API level: 25
[warn] [35m[AndroidDriver][39m Consider setting 'automationName' capability to 'uiautomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.
[info] [35m[AndroidDriver][39m App file was not listed, instead we're going to run com.linkedin.android directly on the device
[debug] [35m[AndroidDriver][39m Checking whether package is present on the device
[debug] [35m[ADB][39m Running 'D:\APPIUMTOOLS\ANDROIDSDK\platform-tools\adb.exe -P 5037 -s a0fde0547d94 shell pm list packages com.linkedin.android'[info] [35m[AndroidDriver][39m Starting Android session
[debug] [35m[ADB][39m Running 'D:\APPIUMTOOLS\ANDROIDSDK\platform-tools\adb.exe -P 5037 -s a0fde0547d94 wait-for-device'[debug] [35m[ADB][39m Running 'D:\APPIUMTOOLS\ANDROIDSDK\platform-tools\adb.exe -P 5037 -s a0fde0547d94 shell echo ping'[debug] [35m[AndroidDriver][39m Pushing settings apk to device...
[debug] [35m[ADB][39m Getting install status for io.appium.settings
[debug] [35m[ADB][39m Running 'D:\APPIUMTOOLS\ANDROIDSDK\platform-tools\adb.exe -P 5037 -s a0fde0547d94 shell dumpsys package io.appium.settings'[debug] [35m[ADB][39m 'io.appium.settings' is not installed
[debug] [35m[ADB][39m App 'C:\Users\Brams\AppData\Local\Programs\Appium\resources\app\node_modules\io.appium.settings\apks\settings_apk-debug.apk' is not installed
[debug] [35m[ADB][39m Installing 'C:\Users\Brams\AppData\Local\Programs\Appium\resources\app\node_modules\io.appium.settings\apks\settings_apk-debug.apk'
[debug] [35m[ADB][39m Device API level: 25
[debug] [35m[ADB][39m Running 'D:\APPIUMTOOLS\ANDROIDSDK\platform-tools\adb.exe -P 5037 -s a0fde0547d94 install -g C\:\\Users\\Brams\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\io.appium.settings\\apks\\settings_apk-debug.apk'
[debug] [35m[ADB][39m Running 'D:\APPIUMTOOLS\ANDROIDSDK\platform-tools\adb.exe -P 5037 -s a0fde0547d94 install -g C\:\\Users\\Brams\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\io.appium.settings\\apks\\settings_apk-debug.apk'[warn] [35m[AndroidDriver][39m Ignored error while installing Appium Settings helper: 'Error executing adbExec. Original error: 'Command 'D\:\\APPIUMTOOLS\\ANDROIDSDK\\platform-tools\\adb.exe -P 5037 -s a0fde0547d94 install -g C\:\\Users\\Brams\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\io.appium.settings\\apks\\settings_apk-debug.apk' exited with code 1'; Stderr: 'adb: failed to install C:\Users\Brams\AppData\Local\Programs\Appium\resources\app\node_modules\io.appium.settings\apks\settings_apk-debug.apk: Security exception: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag
[warn] [35m[AndroidDriver][39m 
[warn] [35m[AndroidDriver][39m java.lang.SecurityException: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag
[warn] [35m[AndroidDriver][39m 	at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:601)
[warn] [35m[AndroidDriver][39m 	at com.android.server.pm.PackageInstallerService.createSession(Package'; Code: '1''. Manually uninstalling the application with package id 'io.appium.settings' may help. Expect some Appium features may not work as expected unless this problem is fixed.
[debug] [35m[ADB][39m Running 'D:\APPIUMTOOLS\ANDROIDSDK\platform-tools\adb.exe -P 5037 -s a0fde0547d94 shell ps'[debug] [35m[ADB][39m Device API level: 25
[debug] [35m[ADB][39m Device API level: 25
[debug] [35m[ADB][39m Running 'D:\APPIUMTOOLS\ANDROIDSDK\platform-tools\adb.exe -P 5037 -s a0fde0547d94 shell am start -W -n io.appium.settings/.Settings -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'[warn] [35m[AndroidDriver][39m Failed to launch settings app: Cannot start the 'io.appium.settings' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Activity name '.Settings' used to start the app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity
[debug] [35m[ADB][39m Device API level: 25
[debug] [35m[ADB][39m Running 'D:\APPIUMTOOLS\ANDROIDSDK\platform-tools\adb.exe -P 5037 -s a0fde0547d94 shell appops set io.appium.settings android\:mock_location allow'[debug] [35m[Logcat][39m Starting logcat capture[info] [35m[ADB][39m Getting device platform version
[debug] [35m[ADB][39m Running 'D:\APPIUMTOOLS\ANDROIDSDK\platform-tools\adb.exe -P 5037 -s a0fde0547d94 shell getprop ro.build.version.release'[debug] [35m[ADB][39m Current device property 'ro.build.version.release': 7.1.2
[debug] [35m[ADB][39m Running 'D:\APPIUMTOOLS\ANDROIDSDK\platform-tools\adb.exe -P 5037 -s a0fde0547d94 shell wm size'[debug] [35m[ADB][39m Running 'D:\APPIUMTOOLS\ANDROIDSDK\platform-tools\adb.exe -P 5037 -s a0fde0547d94 shell getprop ro.product.model'
[debug] [35m[ADB][39m Current device property 'ro.product.model': Redmi 4
[debug] [35m[ADB][39m Running 'D:\APPIUMTOOLS\ANDROIDSDK\platform-tools\adb.exe -P 5037 -s a0fde0547d94 shell getprop ro.product.manufacturer'[debug] [35m[ADB][39m Current device property 'ro.product.manufacturer': Xiaomi
[warn] [35m[AndroidDriver][39m No app sent in, not parsing package/activity
[debug] [35m[AndroidDriver][39m No app capability. Assuming it is already on the device
[debug] [35m[ADB][39m Getting install status for com.linkedin.android
[debug] [35m[ADB][39m Running 'D:\APPIUMTOOLS\ANDROIDSDK\platform-tools\adb.exe -P 5037 -s a0fde0547d94 shell dumpsys package com.linkedin.android'[debug] [35m[ADB][39m 'com.linkedin.android' is installed
[debug] [35m[ADB][39m Running 'D:\APPIUMTOOLS\ANDROIDSDK\platform-tools\adb.exe -P 5037 -s a0fde0547d94 shell am force-stop com.linkedin.android'[debug] [35m[ADB][39m Running 'D:\APPIUMTOOLS\ANDROIDSDK\platform-tools\adb.exe -P 5037 -s a0fde0547d94 shell pm clear com.linkedin.android'[debug] [35m[ADB][39m Running 'D:\APPIUMTOOLS\ANDROIDSDK\platform-tools\adb.exe -P 5037 -s a0fde0547d94 shell pm clear com.linkedin.android'[debug] [35m[AndroidDriver][39m Shutting down Android driver
[debug] [35m[AndroidDriver][39m Called deleteSession but bootstrap wasn't active
[debug] [35m[Logcat][39m Stopping logcat capture
[debug] [35m[ADB][39m Running 'D:\APPIUMTOOLS\ANDROIDSDK\platform-tools\adb.exe -P 5037 -s a0fde0547d94 shell am force-stop io.appium.unlock'[debug] [35m[AndroidDriver][39m Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[debug] [35m[BaseDriver][39m Event 'newSessionStarted' logged at 1546741601967 (07:56:41 GMT+0530 (India Standard Time))
[debug] [35m[W3C][39m Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command 'D\:\\APPIUMTOOLS\\ANDROIDSDK\\platform-tools\\adb.exe -P 5037 -s a0fde0547d94 shell pm clear com.linkedin.android' exited with code 1'; Stderr: 'Error: java.lang.SecurityException: PID 7965 does not have permission android.permission.CLEAR_APP_USER_DATA to clear data of package com.linkedin.android'; Code: '1'
[debug] [35m[W3C][39m     at execFunc (C:\Users\Brams\AppData\Local\Programs\Appium\resources\app\node_modules\appium-adb\lib\tools\system-calls.js:326:13)
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[31m500[39m [90m12588 ms - 1380[39m
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{"desiredCapabilities":{"appActivity":"com.jio.myjio.dashboard.activities.DashboardActivity","appPackage":"com.jio.myjio","platformVersion":"7.1.2","browserName":"","platformName":"Android","udid":"a0fde0547d94","deviceName":"Redmi 4"},"capabilities":{"firstMatch":[{"appium:appActivity":"com.jio.myjio.dashboard.activities.DashboardActivity","appium:appPackage":"com.jio.myjio","browserName":"","appium:deviceName":"Redmi 4","platformName":"android","appium:platformVersion":"7.1.2","appium:udid":"a0fde0547d94"}]}}[39m
[debug] [35m[W3C][39m Calling AppiumDriver.createSession() with args: [{"appActivity":"com.jio.myjio.dashboard.activities.DashboardActivity","appPackage":"com.jio.myjio","platformVersion":"7.1.2","browserName":"","platformName":"Android","udid":"a0fde0547d94","deviceName":"Redmi 4"},null,{"firstMatch":[{"appium:appActivity":"com.jio.myjio.dashboard.activities.DashboardActivity","appium:appPackage":"com.jio.myjio","browserName":"","appium:deviceName":"Redmi 4","platformName":"android","appium:platformVersion":"7.1.2","appium:udid":"a0fde0547d94"}]}]
[debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1546745137251 (08:55:37 GMT+0530 (India Standard Time))
[warn] [35m[Appium][39m Consider setting 'automationName' capability to 'UiAutomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.
[info] [35m[Appium][39m Creating new AndroidDriver (v4.8.0) session
[info] [35m[Appium][39m Capabilities:
[info] [35m[Appium][39m   browserName: 
[info] [35m[Appium][39m   platformName: android
[info] [35m[Appium][39m   appActivity: com.jio.myjio.dashboard.activities.DashboardActivity
[info] [35m[Appium][39m   appPackage: com.jio.myjio
[info] [35m[Appium][39m   deviceName: Redmi 4
[info] [35m[Appium][39m   platformVersion: 7.1.2
[info] [35m[Appium][39m   udid: a0fde0547d94
[debug] [35m[BaseDriver][39m W3C capabilities {"alwaysMatch":{"browserNam... and MJSONWP desired capabilities {"appActivity":"com.jio.myj... were provided
[debug] [35m[BaseDriver][39m Creating session with W3C capabilities: {"alwaysMatch":{"browserNam...
[info] [35m[BaseDriver][39m Session created with session id: 91415de9-f79f-456b-863d-7e3b18fd6a9b[info] [35m[AndroidDriver][39m Java version is: 1.8.0_191
[info] [35m[AndroidDriver][39m Retrieving device list
[debug] [35m[ADB][39m Trying to find a connected android device
[debug] [35m[ADB][39m Getting connected devices...
[debug] [35m[ADB][39m 1 device(s) connected
[info] [35m[AndroidDriver][39m Using device: a0fde0547d94
[debug] [35m[ADB][39m Setting device id to a0fde0547d94
[debug] [35m[ADB][39m Running 'D:\APPIUMTOOLS\ANDROIDSDK\platform-tools\adb.exe -P 5037 -s a0fde0547d94 shell getprop ro.build.version.sdk'[debug] [35m[ADB][39m Current device property 'ro.build.version.sdk': 25
[debug] [35m[ADB][39m Device API level: 25
[warn] [35m[AndroidDriver][39m Consider setting 'automationName' capability to 'uiautomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.
[info] [35m[AndroidDriver][39m App file was not listed, instead we're going to run com.jio.myjio directly on the device
[debug] [35m[AndroidDriver][39m Checking whether package is present on the device
[debug] [35m[ADB][39m Running 'D:\APPIUMTOOLS\ANDROIDSDK\platform-tools\adb.exe -P 5037 -s a0fde0547d94 shell pm list packages com.jio.myjio'[info] [35m[AndroidDriver][39m Starting Android session
[debug] [35m[ADB][39m Running 'D:\APPIUMTOOLS\ANDROIDSDK\platform-tools\adb.exe -P 5037 -s a0fde0547d94 wait-for-device'[debug] [35m[ADB][39m Running 'D:\APPIUMTOOLS\ANDROIDSDK\platform-tools\adb.exe -P 5037 -s a0fde0547d94 shell echo ping'[debug] [35m[ADB][39m 'io.appium.settings' is not installed
[debug] [35m[ADB][39m App 'C:\Users\Brams\AppData\Local\Programs\Appium\resources\app\node_modules\io.appium.settings\apks\settings_apk-debug.apk' is not installed
[debug] [35m[ADB][39m Installing 'C:\Users\Brams\AppData\Local\Programs\Appium\resources\app\node_modules\io.appium.settings\apks\settings_apk-debug.apk'
[debug] [35m[ADB][39m Device API level: 25
[debug] [35m[ADB][39m Running 'D:\APPIUMTOOLS\ANDROIDSDK\platform-tools\adb.exe -P 5037 -s a0fde0547d94 install -g C\:\\Users\\Brams\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\io.appium.settings\\apks\\settings_apk-debug.apk'[debug] [35m[ADB][39m Running 'D:\APPIUMTOOLS\ANDROIDSDK\platform-tools\adb.exe -P 5037 -s a0fde0547d94 install -g C\:\\Users\\Brams\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\io.appium.settings\\apks\\settings_apk-debug.apk'[warn] [35m[AndroidDriver][39m Ignored error while installing Appium Settings helper: 'Error executing adbExec. Original error: 'Command 'D\:\\APPIUMTOOLS\\ANDROIDSDK\\platform-tools\\adb.exe -P 5037 -s a0fde0547d94 install -g C\:\\Users\\Brams\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\io.appium.settings\\apks\\settings_apk-debug.apk' exited with code 1'; Stderr: 'adb: failed to install C:\Users\Brams\AppData\Local\Programs\Appium\resources\app\node_modules\io.appium.settings\apks\settings_apk-debug.apk: Security exception: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag
[warn] [35m[AndroidDriver][39m 
[warn] [35m[AndroidDriver][39m java.lang.SecurityException: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag
[warn] [35m[AndroidDriver][39m 	at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:601)
[warn] [35m[AndroidDriver][39m 	at com.android.server.pm.PackageInstallerService.createSession(Package'; Code: '1''. Manually uninstalling the application with package id 'io.appium.settings' may help. Expect some Appium features may not work as expected unless this problem is fixed.
[debug] [35m[ADB][39m Running 'D:\APPIUMTOOLS\ANDROIDSDK\platform-tools\adb.exe -P 5037 -s a0fde0547d94 shell ps'[debug] [35m[ADB][39m Device API level: 25
[debug] [35m[ADB][39m Device API level: 25
[debug] [35m[ADB][39m Running 'D:\APPIUMTOOLS\ANDROIDSDK\platform-tools\adb.exe -P 5037 -s a0fde0547d94 shell am start -W -n io.appium.settings/.Settings -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'[warn] [35m[AndroidDriver][39m Failed to launch settings app: Cannot start the 'io.appium.settings' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Activity name '.Settings' used to start the app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity
[debug] [35m[ADB][39m Device API level: 25
[debug] [35m[ADB][39m Running 'D:\APPIUMTOOLS\ANDROIDSDK\platform-tools\adb.exe -P 5037 -s a0fde0547d94 shell appops set io.appium.settings android\:mock_location allow'[info] [35m[ADB][39m Getting device platform version
[debug] [35m[ADB][39m Running 'D:\APPIUMTOOLS\ANDROIDSDK\platform-tools\adb.exe -P 5037 -s a0fde0547d94 shell getprop ro.build.version.release'[debug] [35m[ADB][39m Current device property 'ro.build.version.release': 7.1.2
[debug] [35m[ADB][39m Running 'D:\APPIUMTOOLS\ANDROIDSDK\platform-tools\adb.exe -P 5037 -s a0fde0547d94 shell wm size'[debug] [35m[ADB][39m Running 'D:\APPIUMTOOLS\ANDROIDSDK\platform-tools\adb.exe -P 5037 -s a0fde0547d94 shell getprop ro.product.model'[debug] [35m[ADB][39m Current device property 'ro.product.model': Redmi 4
[debug] [35m[ADB][39m Running 'D:\APPIUMTOOLS\ANDROIDSDK\platform-tools\adb.exe -P 5037 -s a0fde0547d94 shell getprop ro.product.manufacturer'[debug] [35m[ADB][39m Current device property 'ro.product.manufacturer': Xiaomi
[warn] [35m[AndroidDriver][39m No app sent in, not parsing package/activity
[debug] [35m[AndroidDriver][39m No app capability. Assuming it is already on the device
[debug] [35m[ADB][39m Getting install status for com.jio.myjio
[debug] [35m[ADB][39m Running 'D:\APPIUMTOOLS\ANDROIDSDK\platform-tools\adb.exe -P 5037 -s a0fde0547d94 shell dumpsys package com.jio.myjio'[debug] [35m[ADB][39m 'com.jio.myjio' is installed
[debug] [35m[ADB][39m Running 'D:\APPIUMTOOLS\ANDROIDSDK\platform-tools\adb.exe -P 5037 -s a0fde0547d94 shell am force-stop com.jio.myjio'[debug] [35m[ADB][39m Running 'D:\APPIUMTOOLS\ANDROIDSDK\platform-tools\adb.exe -P 5037 -s a0fde0547d94 shell pm clear com.jio.myjio'[debug] [35m[ADB][39m Running 'D:\APPIUMTOOLS\ANDROIDSDK\platform-tools\adb.exe -P 5037 -s a0fde0547d94 shell pm clear com.jio.myjio'[debug] [35m[AndroidDriver][39m Shutting down Android driver
[debug] [35m[AndroidDriver][39m Called deleteSession but bootstrap wasn't active
[debug] [35m[Logcat][39m Stopping logcat capture
[debug] [35m[ADB][39m Running 'D:\APPIUMTOOLS\ANDROIDSDK\platform-tools\adb.exe -P 5037 -s a0fde0547d94 shell am force-stop io.appium.unlock'[debug] [35m[AndroidDriver][39m Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[debug] [35m[BaseDriver][39m Event 'newSessionStarted' logged at 1546745149582 (08:55:49 GMT+0530 (India Standard Time))
[debug] [35m[W3C][39m Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command 'D\:\\APPIUMTOOLS\\ANDROIDSDK\\platform-tools\\adb.exe -P 5037 -s a0fde0547d94 shell pm clear com.jio.myjio' exited with code 1'; Stderr: 'Error: java.lang.SecurityException: PID 11363 does not have permission android.permission.CLEAR_APP_USER_DATA to clear data of package com.jio.myjio'; Code: '1'
[debug] [35m[W3C][39m     at execFunc (C:\Users\Brams\AppData\Local\Programs\Appium\resources\app\node_modules\appium-adb\lib\tools\system-calls.js:326:13)
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[31m500[39m [90m12337 ms - 1354[39m
[info] [35m[HTTP][39m [90m[39m

**Comment by mykola-mokhnach** [comment]
closed as duplicate
