### ISSUE TITLE
Unable to register Appium node in grid if using capabilities instead of desiredCapabilities

### ISSUE THREAD

**Issue by xlenz** [appium/appium#11957]
## The problem

Unable to register Appium node in grid if using capabilities instead of desiredCapabilities.

There is list of standard w3c capabilities https://www.w3.org/TR/webdriver/#capabilities
Of course capabilities like deviceName are not standard because of that Appium node cannot be registered on grid.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: ANY
* Node.js version (unless using Appium.app|exe): ANY
* Mobile platform/version under test: ANY
* Real device or emulator/simulator: ANY
* Appium CLI or Appium.app|exe: cli

## Details

Is it possible to add support of https://www.w3.org/TR/webdriver/#dfn-extension-capability for appium?
Example, add prefixed appium:capabilities support: 
```
  capabilities: [{
    maxInstances: 1,
    "appium:capabilities": {
      platformName: 'Android',
      platformVersion: '9.0.0',
      deviceName: 'Pixel 2'
    }
  }]
```

## Link to Appium logs

N/A

## Additional Details

1. Run selenium grid server 3.141.59
2. try register node with capabilities: { deviceName: 'pixel 2' }

Actual Result: not possible.

Linked issues: 
https://github.com/SeleniumHQ/selenium/issues/6823
https://github.com/webdriverio/webdriverio/issues/3252

**Comment by xlenz** [comment]
As a temporary workaround I've created custom capability matcher for selenium server that moves all capabilities from appium:capabilities to root level capabilities, like this:
```
private void parseAppiumCaps(Map<String, Object> requestedCapability) {
        final String APPIUM_CAPS = "appium:capabilities";
        if (!requestedCapability.containsKey(APPIUM_CAPS)) return;

        Map<String, Object> appiumCaps = (Map<String, Object>) requestedCapability.get(APPIUM_CAPS);
        appiumCaps.forEach(requestedCapability::put);
        requestedCapability.remove(APPIUM_CAPS);
    }
```

**Comment by mykola-mokhnach** [comment]
what if you change the cap name to `appium:deviceName`?

**Comment by xlenz** [comment]
@mykola-mokhnach hell yeah, it works!! Thanks!
