### ISSUE TITLE
RelativeLayout vs LinearLayout problem

### ISSUE THREAD

**Issue by 505thzajcev** [appium/appium#11966]
## The problem

I'm testing a mobile app with Rapise. Rapise using Appium as a gateway for mobiles. In the test Android app (almost look like an ApiDemo) what comes with Rapise there are 2 edittext box. The program cannot recognise one of them on play, only one edit box. The only diference betweeen them, besides the name, that the not working textedit is LinearLayouts, the good one is RelativeLayout. Here is the XPATH difference:

//android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[2]/android.widget.RelativeLayout/android.widget.EditText   -  working one
//android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[2]/android.widget.LinearLayout/android.widget.EditText -  not working

Both of them setup are looks likes the same, but only the RelativeLayouts working.
I use UiAutomator2 for this test, because it seems thats the best for most of the case. I tried all the Android driver (UiAutomator1-2, Selendroid, Espresso).

Is this a bug related to Appium? Or is this some limitation?

## Environment

* Appium version: 1.10.0 - latest
* Desktop OS/version used to run Appium: Windows 10 - 1803
* Node.js version: Node.js v10.14.2
* Mobile platform/version under test: Android 8.0
* Real device or emulator/simulator: Samsung J6 real and Android AVD
* Rapise 5.7.14.17

**Comment by mykola-mokhnach** [comment]
closed as third party issue
