### ISSUE TITLE
caught when processing request to {}->http://127.0.0.1:4723: The target server failed to respond

### ISSUE THREAD

**Issue by AvrahamAtia** [appium/appium#11964]
## The problem

09:14:50 Jan 09, 2019 4:14:50 PM org.apache.http.impl.execchain.RetryExec execute
09:14:50 INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://127.0.0.1:4723: The target server failed to respond
09:14:50 Jan 09, 2019 4:14:50 PM org.apache.http.impl.execchain.RetryExec execute
09:14:50 INFO: Retrying request to {}->http://127.0.0.1:4723

## Environment

* Appium server: 1.9.1
* Node: v10.4.1
* Allure: 2.8.0
* real devices iOS 12.1 and 11.3
* Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T21:49:05+02:00)
* Maven home: /usr/local/Cellar/maven/3.5.3/libexec
* Java version: 11.0.1, vendor: Oracle Corporation
* Java home: /Library/Java/JavaVirtualMachines/jdk-11.0.1.jdk/Contents/Home
Default locale: en_IL, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.6", arch: "x86_64", family: "mac"

## Details

Parallel executions for iOS real devices.

**Comment by mykola-mokhnach** [comment]
Do you follow https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/parallel-tests.md ?

**Comment by AvrahamAtia** [comment]
@imurchie Yes, I followed and I did the same as this guide!

**Comment by GaneshvrBhat** [comment]
I see same problem with android emulator as well.

Feb 12, 2019 7:57:59 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:61854
Feb 12, 2019 8:18:01 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://127.0.0.1:61854: The target server failed to respond.

Any idea about routeCause? However on relaunching app it works properly.
