### ISSUE TITLE
Google sign in error

### ISSUE THREAD

**Issue by Gilad-WT** [appium/appium#11960]
## The problem

I am running a test on the android emulator and can't sign in to google from within my application if it's installed via appium. If I install it with the adb or directly the google sign in works.

## Environment

* Appium version (or git revision) that exhibits the issue: appium 1.10
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): using appium desktop
* Mobile platform/version under test: 8.0
* Real device or emulator/simulator: Android Emulator
* Appium CLI or Appium.app|exe: Appium desktop

## Details
This is the Android log for the failed login:

AbstractGoogleClient: Application name is not set. Call Builder#setApplicationName.
chatty  : uid=10014(u0_a14) GoogleApiHandle expire 1 line
Auth    : [GoogleAuthUtil] GoogleAuthUtil
SyncLog : Exception in downSyncHabits
SyncLog : com.google.android.apiary.AuthenticationException: Could not get an auth token

**Comment by mykola-mokhnach** [comment]
Can you attach the whole server log? How the problem is related to Appium?

**Comment by imurchie** [comment]
Also, what command are you running to install it via `adb`?

**Comment by Gilad-WT** [comment]
For adb I use adb install <Path_2_file_on_my_machine>. 
Had to anonymize the log but here it is - https://gist.github.com/Gilad-WT/50dfe3a8ec9cf51c4c2dbf15f3cd2a8b

**Comment by imurchie** [comment]
The app is already installed for the logs provided.

Can you run without the app installed, and get the `adb` command being used to install the app by Appium. Then try manually using that command?

**Comment by mykola-mokhnach** [comment]
what if you set `noSign` to true?

**Comment by Gilad-WT** [comment]
@imurchie reran the test and (made sure to uninstall the app first this time) and updated the logs

**Comment by Gilad-WT** [comment]
@mykola-mokhnach reran with noSign set to true and still can't sign in

**Comment by mykola-mokhnach** [comment]
I don't have any other ideas. Check the debug logs from your component and compare it with the logs from the working state

**Comment by imurchie** [comment]
Can you do the login when you install it manually using the command Appium is using:
```
C:\Users\<user>\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5556 install 'C:\\<dir>\\<app_name> 1.10.8.apk'
```

**Comment by mykola-mokhnach** [comment]
Closed as inactive

**Comment by srishti77** [comment]
I have the same problem, did we find the solution for this issue? I can sign in if I install the app using adb but I cannot sign in if I install the app using Appium.

**Comment by amitsavyasachi** [comment]
I have same problem , I disabled 2 FA for a google account and from my app i am trying to do a google sign in. For my test i am using browserstack+appium but it doesnot work
