### ISSUE TITLE
AppiumDriver.deleteSession is called automatically , resulting in test cases getting failed

### ISSUE THREAD

**Issue by pankajigec26** [appium/appium#11963]
## The problem

I have a Test suite consisting of 10 test cases, After the execution of 1st test case, AppiumDriver.deleteSession is called automatically resulting in failure of other test cases.

## Environment

* Appium version :1.7.1
* Last Appium version that did not exhibit the issue (if applicable):NA
* Desktop OS/version used to run Appium: Windows 7
* Node.js version (unless using Appium.app|exe): 8.9.4
* Mobile platform/version under test: Nokia 5 , ANdroid v8
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: NA

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Please find link to logs
https://gist.github.com/pankajigec26/5dc1f0adea5313400aed453b22187f66

## Code To Reproduce Issue [ Good To Have ]

Can not provide

**Comment by KazuCocoa** [comment]
What about client code?

It seems the delete session command is called by your client code.

```
[HTTP] <-- GET /wd/hub/session/b4b377e8-3d86-45c6-baf7-0203230e0440/screenshot 2
00 1590 ms - 324102
[HTTP] --> DELETE /wd/hub/session/b4b377e8-3d86-45c6-baf7-0203230e0440 {}
[debug] [MJSONWP] Calling AppiumDriver.deleteSession() with args: ["b4b377e8-3d8
6-45c6-baf7-0203230e0440"]
[debug] [BaseDriver] Event 'quitSessionRequested' logged at 1547032613008 (16:46
:53 GMT+0530 (India Standard Time))
[Appium] Removing session b4b377e8-3d86-45c6-baf7-0203230e0440 from our master s
ession list
```

> Appium version :1.7.1

Try out the latest 1.10 if you can
