### ISSUE TITLE
[Espresso] Incorrect package and activity after reopen app

### ISSUE THREAD

**Issue by sanlengjingvv** [appium/appium#11961]
## The problem
Use Espresso driver,  close app, then lanuch app.
The next command can not executed.
Same code works when use UiAutomator2 driver.
## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0
* Desktop OS/version used to run Appium: MacOS 10.13.6
* Mobile platform/version under test: Android 6.0
* Real device or emulator/simulator: Real device Nexus6P
* Appium CLI or Appium.app|exe: Appium.app

## Link to Appium logs

https://gist.github.com/sanlengjingvv/9fca112df1980869c6369cbbbc4cf76c

## Code To Reproduce Issue [ Good To Have ]
```
http://127.0.0.1:4723/wd/hub/session/ee840576-6637-466e-bc56-5760a0986c10/appium/app/close
http://127.0.0.1:4723/wd/hub/session/ee840576-6637-466e-bc56-5760a0986c10/appium/app/launch
```

**Comment by mykola-mokhnach** [comment]
Such behaviour is expected. You need to quit the driver and start it again after the app is terminated.  The Espresso driver is built the way that it is bundled with the application under test, which means that terminating the host application will also kill the driver
