### ISSUE TITLE
Error after update 1.10.0 lower -> android 7 api 24 connect ECONNREFUSED 127.0.0.1:8200

### ISSUE THREAD

**Issue by Shahidsheikh85** [appium/appium#11974]
## The problem

After update to Appium 1.10.0 Android API23 doesn't work anymore. Emulator starts, Appium Settings is installed, there after App will be installed and directly deleted.
Don't know where it went wrong. HELP 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0
* Last Appium version that did not exhibit the issue (if applicable):1.9.0
* Desktop OS/version used to run Appium: Mac OS 10.14.2
* Node.js version (unless using Appium.app|exe):10.13.0
* Mobile platform/version under test: Android Api23 and lower
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"/sandbox/app/myappnl-localhost.apk","noReset":false,"platformVersion":"6.0","automationName":"uiautomator2","platformName":"Android","deviceName":"emulator-5554","fullReset":true,"avd":"Nexus_6P_API_23"},"capabilities":{"firstMatch":[{"appium:app":"/sandbox/app/myappnl-localhost.apk","appium:automationName":"uiautomator2","appium:avd":"Nexus_6P_API_23","appium:deviceName":"emulator-5554","appium:fullReset":true,"appium:noReset":false,"platformName":"android","appium:platformVersion":"6.0"}]}}
[Appium] Creating new AndroidUiautomator2Driver (v1.26.0) session
[Appium] Capabilities:
[Appium]   platformName: android
[Appium]   app: /sandbox/app/myappnl-localhost.apk
[Appium]   automationName: uiautomator2
[Appium]   avd: Nexus_6P_API_23
[Appium]   deviceName: emulator-5554
[Appium]   fullReset: true
[Appium]   noReset: false
[Appium]   platformVersion: 6.0
[BaseDriver] Session created with session id: a5e0ac40-a0b8-4a45-9964-e495963762bd
(node:12117) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[BaseDriver] Using local app '/sandbox/app/myappnl-localhost.apk'
[AndroidDriver] Java version is: 1.8.0_192
[ADB] Checking whether adb is present
[ADB] Found 1 'build-tools' folders under '/Users/user/Library/Android/sdk' (newest first):
[ADB]     /Users/user/Library/Android/sdk/build-tools/28.0.3
[ADB] Using adb from /Users/user/Library/Android/sdk/platform-tools/adb
[ADB] Checking whether emulator is present
[ADB] Using emulator from /Users/user/Library/Android/sdk/emulator/emulator
[AndroidDriver] Using device: emulator-5554
[ADB] Using apkanalyzer from /Users/user/Library/Android/sdk/tools/bin/apkanalyzer
[ADB] Package name: 'com.private.myappnl.localhost'
[ADB] Main activity name: 'com.private.NativeScriptActivity'
[ADB] Checking whether aapt is present
[ADB] Using aapt from /Users/user/Library/Android/sdk/build-tools/28.0.3/aapt
[ADB] Using apksigner from /Users/user/Library/Android/sdk/build-tools/28.0.3/apksigner
[UiAutomator2] Server packages are not going to be (re)installed
[ADB] com.private.myappnl.localhost was not uninstalled, because it was not present on the device
[Logcat] Logcat terminated with code 0, signal null
[ADB] Unable to unroot adb daemon: 'Command '/Users/user/Library/Android/sdk/platform-tools/adb unroot' exited with code 1'. Continuing
[UiAutomator2] Unable to kill the io.appium.uiautomator2.server process, assuming it is already killed
[UiAutomator2] Starting UIAutomator2 server 3.1.1
[UiAutomator2] Using UIAutomator2 server from '/Users/user/.npm-global/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.1.1.apk' and test from '/Users/user/.npm-global/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk'
[UiAutomator2] Running command: 'adb -s emulator-5554 shell am instrument -w io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner'
[UiAutomator2] Waiting up to 20000ms for UiAutomator2 to be online...
[UiAutomator2] [UIAutomator2 Error] Failure: 'device offline'
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8200}
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8200}
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8200}
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8200}
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8200}
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8200}
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8200}
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8200}
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8200}
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8200}
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8200}
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8200}
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8200}
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8200}
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8200}
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8200}
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8200}
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8200}
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8200}
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8200}
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
[ADB] com.private.myappnl.localhost was successfully uninstalled
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command '/Users/user/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp\:8200' exited with code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''
[HTTP] <-- POST /wd/hub/session 500 39698 ms - 587
[HTTP]

**Comment by aleksandrawy** [comment]
I have the same problem, tested on Linux and Mac OS High Sierra, I had to downgrade appium due to that ECONNREFUSED problem. I detected it not only on API 23 but also others. It works randomly. What is going on?

**Comment by Shahidsheikh85** [comment]
Hi @aleksandrawy downgrade is not an option because fingerprint for ios. I hope someone can help!!

**Comment by mykola-mokhnach** [comment]
> [UiAutomator2] [UIAutomator2 Error] Failure: 'device offline'

I think there's some problem with the device connectivity

**Comment by aleksandrawy** [comment]
Why did the problem appear after upgrade Appium to 1.10.0 and on different systems? After downgrading to 1.9.1 everything works fine. 

@Shahidsheikh85 I am using Appium only for Android so I don't need to worry about ios.

**Comment by mykola-mokhnach** [comment]
This issue might be fixed together with https://github.com/appium/appium/issues/11978

**Comment by dpgraham** [comment]
This is happening intermittently on CI: https://dev.azure.com/appiumci/Appium%20CI/_build/results?buildId=1933&view=logs

It follows:
`Unable to unroot -> devices offline -> all subsequent tests fail`

May need retry logic.

**Comment by jgbaylon** [comment]
This is affecting a lot our tests and I've been waiting for a resolution for two months now.

**Comment by Roise0568** [comment]
Hi, I also meet the same prolem with appium 1.14.2
How did you solve this problem?
Or is there any good way to make appium work fine when catch problem?
