### ISSUE TITLE
Unable to launch application (.apk file) on Android 9 using Appium 1.7.1

### ISSUE THREAD

**Issue by rajeev2** [appium/appium#11975]
## The problem

I am unable to launch apk file on Android 9 using Appium 1.7.1. 

## Environment

* Appium version (or git revision) that exhibits the issue:  v1.7.1
* Desktop OS/version used to run Appium: MacOS High Sierra Version 10.13.4 
* Mobile platform/version under test: Android 9
* Real device or emulator/simulator: Real Device
* Xcode Version: 9.4.1

## Details

When I execute my test script to launch apk file on Android 9. It says" [MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Error: read ECONNRESET".
Please find the attached log file.

Note: I am able to launch the apk file on Android 1.7.2 using the same environment but not on Android 9

## Link to Appium logs

https://gist.github.com/rajeev2/38fb1ba4074086e7a4789ca963693415

**Comment by mykola-mokhnach** [comment]
Appium 1.7.1 is out of date. Please upgrade to the most recent version first

**Comment by rajeev2** [comment]
I am able to launch apk on Android 9 by using Appium v1.8.1.

Thanks myKola
