### ISSUE TITLE
Since last version it is necessary to delete app and webDriverAgent from device before starting new test run

### ISSUE THREAD

**Issue by nemue** [appium/appium#11985]
## The problem

I use TestNG and Java client to write tests for iOS and Android. I currently use the Appium version 1.10.0 (1.10.0.20181230.2). Since the version before that, it has become necessary to delete the app and the WebDriverAgent app from the phone between tests or otherwise there will be a WebDriverEcception. In the older Appium version that problem didn't exist either.

## Environment

* Appium version (or git revision) that exhibits the issue: Version 1.10.0 (1.10.0.20181230.2)
* Last Appium version that did not exhibit the issue (if applicable): –
* Desktop OS/version used to run Appium: Mac OS 10.13.6
* Node.js version (unless using Appium.app|exe): v8.11.4
* Mobile platform/version under test: iOS 11.4 (iPhone 6) and iOS 10.3 (iPhone 5)
* Real device or emulator/simulator: iPhone 6S Plus and iPhone 5S
* Appium CLI or Appium.app|exe: Appium.app

## Details

Exception:
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unknown device or simulator UDID: '[correct Id is usually visible here]' (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 933 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'macbook-nele', ip: '[ip]', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '1.8.0_181'

When I run the tests using Gradle, that error does not occur.

**Comment by mykola-mokhnach** [comment]
Please provide the full server log. 

> Build info: version: '2.53.1' 

this looks very old. Make sure the client is up to date

**Comment by nemue** [comment]
Hi @mykola-mokhnach, thanks for your message! I updated all dependencies, but still got the below error. I noticed I had set fullReset capability to true. Changing that solved the issue. 

The error was: 
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8102 Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'macbook-nele', ip: '192.168.100.226', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '1.8.0_181'
Driver info: driver.version: IOSDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8102 Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at getResponseForW3CError (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/lib/protocol/errors.js:826:9)
    at asyncHandler (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/lib/protocol/protocol.js:447:37)
    at <anonymous>
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'macbook-nele', ip: '192.168.100.226', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '1.8.0_181'
Driver info: driver.version: IOSDriver

I put part of the logs that I thought were relevant in a gist: https://gist.github.com/nemue/b7595d874af9af712a91aabe1c6e3102

I had to replace some information with placeholders though. Please let me know, if you need more. It seems the problem is that WebDriverAgent won't start.

**Comment by mykola-mokhnach** [comment]
The recent log is not very useful. Try to enable `showXcodeLog` and `showIOSLog` caps

**Comment by nemue** [comment]
The logs look the same with both capabilities enabled, except that iOSLog started and ended...

**Comment by nemue** [comment]
@mykola-mokhnach, I realized, I had in fact set both reset capabilities `fullReset = true` and `noReset = false` at the same time. Disabling one of them solves the issue.

**Comment by Phoenix124** [comment]
@nemue Hi
You can delete WDA using command  ` xcrun simctl uninstall com.apple.test.WebDriverAgentRunner-Runner`

**Comment by faran** [comment]
Hi, sorry to bump in to already opened issue. But i cannot figure out what is going on. I have similar kind of issue since upgraded to 1.10.0 and 1.10.1
In my suite first test always throw similar kind of error about WDA not configured and the very next test will start working without any problem.
I tried restarting device and removing WDA then it will work for one time but then it will be same from next run onward. Quite frustrating. I tried enabling showXcodeLog and showIOSLog but nothing much coming out. 

This is what i can see
https://gist.github.com/faran/8ab23ec9c054a7347e5c25d1f00d3115

**Comment by nemue** [comment]
@faran, I've noticed, it is the same in my project. Every second test run fails to start. Unfortunately, it seems to have nothing to do with the setting the fullReset capability, @mykola-mokhnach.

**Comment by nemue** [comment]
@mykola-mokhnach, I've noticed that it is not necessary to delete the app or WebDriverAgent between test runs, if I start the tests using Gradle.

**Comment by mykola-mokhnach** [comment]
Closed as inactive

**Comment by nemue** [comment]
@mykola-mokhnach, why did you close this issue? was there any more information that you needed?

**Comment by mykola-mokhnach** [comment]
The probability an issue will be resolved after more than one month of waiting is quite close to zero

**Comment by nemue** [comment]
I see. I have given you all the information that I have. If there is anything else that you need, please let me know.

**Comment by faran** [comment]
@nemue try this solution i found, all info in there let me know if you need to know anything else.
https://github.com/appium/appium/issues/12094

**Comment by nemue** [comment]
@faran, thank you! Which solution worked for you? Removing the WDA or the value of wdaStartupRetries capability?

**Comment by faran** [comment]
@nemue https://github.com/appium/appium/issues/12094#issuecomment-458617816

**Comment by yassinecc** [comment]
@faran how do you delete the WDA within CI tests?

**Comment by faran** [comment]
@yassinecc 
i use ideviceinstaller in beforesuite to uninstall wda.
as uninstalling once in the start works for me but you can uninstall where ever or whenever you want

**Comment by faran** [comment]
or try these caps
        serverCapabilities.setCapability("wdaStartupRetries", "4");
        serverCapabilities.setCapability("iosInstallPause","8000" );
        serverCapabilities.setCapability("wdaStartupRetryInterval", "20000");

**Comment by nemue** [comment]
thanks @faran! i've added removeApp in AfterSuite.
