### ISSUE TITLE
Appium/WDA hangs or becomes unresponsive after launching app

### ISSUE THREAD

**Issue by AvrahamAtia** [appium/appium#11989]
## The problem

[Appium] Creating new XCUITestDriver (v2.84.0) session
[Appium] Capabilities:
[Appium]   app: /Staging/Staging9.0.ipa
[Appium]   noReset: false
[Appium]   platformVersion: 11.3.1
[Appium]   commandTimeout: 60
[Appium]   automationName: XCUITest
[Appium]   udid: *****
[Appium]   platformName: iOS
[Appium]   deviceName: iPhone_6_11.3
[Appium]   privateDevicesOnly: true
[debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {"app":"/Staging/Staging9.0...
[BaseDriver] The following capabilities were provided, but are not recognized by appium: commandTimeout, privateDevicesOnly.
[BaseDriver] Session created with session id: f9cb7b95-ffaf-4409-8717-01950dc8f3df
[debug] [XCUITest] Current user: 'automacus'
[debug] [XCUITest] Xcode version set to '9.4.1' (tools v10.1.0.0.1.1539992718)
[debug] [XCUITest] iOS SDK Version set to '11.4'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1547377561178 (03:06:01 GMT-0800 (Pacific Standard Time))
[debug] [XCUITest] Available devices: ***, ***
[debug] [XCUITest] Creating iDevice object with udid '****'
[XCUITest] Determining device to run tests on: udid: '****', real device: true
[BaseDriver] Using local app '/Staging/Staging9.0.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[BaseDriver] Unzipping local app '/var/folders/cy/dbpksl_x7wg4p_n3brr51qxm0000gn/T/2019013-87744-1uro982.h7uf/appium-app.zip'...
[debug] [BaseDriver] Unzipping /var/folders/cy/dbpksl_x7wg4p_n3brr51qxm0000gn/T/2019013-87744-1uro982.h7uf/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/cy/dbpksl_x7wg4p_n3brr51qxm0000gn/T/2019013-87744-1uro982.h7uf/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/cy/dbpksl_x7wg4p_n3brr51qxm0000gn/T/2019013-87744-1uro982.h7uf/Payload/Enterprisefly.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1547377567850 (03:06:07 GMT-0800 (Pacific Standard Time))
[debug] [XCUITest] Checking whether app '/var/folders/cy/dbpksl_x7wg4p_n3brr51qxm0000gn/T/2019013-87744-1uro982.h7uf/Payload/Enterprisefly.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [iOS] Getting bundle ID from app '/var/folders/cy/dbpksl_x7wg4p_n3brr51qxm0000gn/T/2019013-87744-1uro982.h7uf/Payload/Enterprisefly.app': ****prototype'
[debug] [BaseDriver] Event 'resetStarted' logged at 1547377567866 (03:06:07 GMT-0800 (Pacific Standard Time))
[debug] [XCUITest] Reset: running ios real device reset flow
[debug] [BaseDriver] Event 'resetComplete' logged at 1547377567867 (03:06:07 GMT-0800 (Pacific Standard Time))
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Starting iOS device log capture with: 'idevicesyslog'
[XCUITest] Cannot get the name of the crashes folder for the device with udid '****'. Original error: Command 'idevicename -u ****' exited with code 255
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1547377567931 (03:06:07 GMT-0800 (Pacific Standard Time))
[XCUITest] Setting up real device
[debug] [XCUITest] Verifying application platform
[debug] [XCUITest] CFBundleSupportedPlatforms: ["iPhoneOS"]
[debug] [XCUITest] Installing '/var/folders/cy/dbpksl_x7wg4p_n3brr51qxm0000gn/T/2019013-87744-1uro982.h7uf/Payload/Enterprisefly.app' on device with UUID '****'...
[debug] [XCUITest] The app has been installed successfully.
[debug] [BaseDriver] Event 'appInstalled' logged at 1547377605276 (03:06:45 GMT-0800 (Pacific Standard Time))
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[debug] [XCUITest] No obsolete cached processes from previous WDA sessions listening on port 9013 have been found
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:9013/status] with no body
[debug] [XCUITest] WDA is not listening at 'http://localhost:9013/'
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1547377605350 (03:06:45 GMT-0800 (Pacific Standard Time))
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing running processes 'xcodebuild.****, iproxy 9013' for the device ****...
[debug] [XCUITest] 'pgrep -nif xcodebuild.****' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] 'pgrep -nif iproxy 9013' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] Starting iproxy to forward traffic from local port 9013 to device port 8100 over USB
[debug] [XCUITest] Using Xcode 9.4.1, so fixing WDA codebase
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=**** IPHONEOS_DEPLOYMENT_TARGET=11.3' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged. To change this, use 'showXcodeLog' desired capability
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:9013/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:9013/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:9013/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:9013/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:9013/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:9013/status] with no body
[debug] [XCUITest] Log file for xcodebuild test: /var/folders/cy/dbpksl_x7wg4p_n3brr51qxm0000gn/T/com.apple.dt.XCTest/IDETestRunSession-A428F0FC-20A2-44FA-A268-29D04A3B63DA/WebDriverAgentRunner-2D7D96E9-6861-4D6C-8994-5DCF82A69F75/Session-WebDriverAgentRunner-2019-01-13_30653 AM-N4t3cU.log
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:9013/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:9013/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:9013/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:9013/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:9013/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:9013/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:9013/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:9013/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:9013/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:9013/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:9013/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:9013/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:9013/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:9013/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:9013/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:9013/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:9013/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:9013/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:9013/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:9013/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:9013/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"11.3.1\",\n      \"sdkVersion\" : \"11.3\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"11.3.1\",\n      \"ip\" : \"192.168.2.13\"\n    },\n    \"build\" : {\n      \"time\" : \"Jan 13 2019 03:04:01\"\n    }\n  },\n  \"sessionId\" : \"E719A078-C16B-420E-8FDA-EB5E806F279E\",\n  \"status\" : 0\n}"
[debug] [XCUITest] WebDriverAgent running on ip '192.168.2.13'
[debug] [XCUITest] WebDriverAgent successfully started after 14180ms
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1547377624604 (03:07:04 GMT-0800 (Pacific Standard Time))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:9013/session] with body: {"desiredCapabilities":{"bundleId":"c******.prototype","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
## Environment
Real device:  iPhone 6, 11.3.1
Appium server: 1.8.1
Node: v10.14.2
Allure: 2.8.1
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T11:41:47-07:00)
Maven home: /usr/local/Cellar/maven/3.6.0/libexec
Java version: 11.0.1, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-11.0.1.jdk/Contents/Home
Default locale: en_IL, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.6", arch: "x86_64", family: "mac"

**Comment by mykola-mokhnach** [comment]
Closed as third party issue. 

You could also try to raise an issue to https://github.com/facebook/WebDriverAgent
