### ISSUE TITLE
UiAutomator2 ESOCKETTIMEDOUT while clicking on element

### ISSUE THREAD

**Issue by brandonburgess08** [appium/appium#11983]
## The problem
I have a listview. When searching for the option I want to filter down the list, I am unable to select it. After searching for the code that I want in the list, I am unable to click anything on the page, or get coordinates of an element. This works fine manually testing. It works just fine when changing automationName to appium. This only happens when using automationName = UiAutomator2. 

## Environment

* Appium version 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): Issue has always happened on Android 8 emulator and real device
* Desktop OS/version used to run Appium: Windows 10 
* Node.js version (unless using Appium.app|exe): v8.11.3
* Mobile platform/version under test: Nexus 6P API 26 
* Real device or emulator/simulator: Android Emulator. Also tested on real device
* Appium CLI or Appium.app|exe: CLI

## Details
I am unable to find the element using resource id and xpath. I can even get the text of the element. As soon as I click the element (element.Click()) the app sites there for 4 minutes and then throws an ESOCKETTIMEDOUT  error. 

## Link to Appium logs

https://gist.github.com/brandonburgess08/e006af092f90be66e3af60df164c3d83

## Code To Reproduce Issue [ Good To Have ]
Both click the element instantly when changing automationName to appium instead of UiAutomator2

     var procedure = MobileDriver
                .FindElements(By.Id("resource-id/txtMainItem"))
                .FirstOrDefault(e => e.Text.ToLower().Contains(procOrBundleToSelect.ToLower().Trim()));
                procedure.Click()

OR

IList<IWebElement> pr =             MobileDriver.FindElements(By.XPath($"//android.widget.RelativeLayout[@clickable='true']"));
            
            pr[1].Click();

**Comment by mykola-mokhnach** [comment]
Appium 1.7 is out of date. Try to upgrade to the recent version. 
Also, the logcat output might be useful

**Comment by brandonburgess08** [comment]
Appium 1.9.0 and 1.10.0 gives me the below error. I am not even able to get past the first step in my test.
I am using the resource Id to search. 

[HTTP] {"using":"css selector","value":"#com\\.imbills\\.mobile\\:id\\/login_et_group"}
[debug] [W3C] Calling AppiumDriver.findElement() with args: ["css selector","#com\\.imbills\\.mobile\\:id\\/login_et_group","9d8926c2-32d1-4cfa-ac98-49a411f6d8af"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[W3C] Encountered internal error running command: InvalidSelectorError: Locator Strategy 'css selector' is not supported for this session

**Comment by brandonburgess08** [comment]
So after doing some reading looks like the old way of finding elements will no longer be valid and now i must find elements using:
MobileDriver.FindElement(MobileBy.AndroidUIAutomator("new UiSelector().resourceId(\"textbox:id/login_et_group\").instance(1)"));

**Comment by mykola-mokhnach** [comment]
This is the problem of outdated client: https://github.com/appium/appium/search?q=%22is+not+supported+for+this+session%22&type=Issues

Closed as not an issue
