### ISSUE TITLE
An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.XXX.digital.ot.uat' application. Original error: 'com.XXX.digital.ot.SplashActivity' or 'com.olam.digital.ot.uat.com.olam.digital.ot.SplashActivity' never started.

### ISSUE THREAD

**Issue by ThamaraiSelvi** [appium/appium#11980]
## The problem
Can't able to access SplashActivity. Meantime Splash activity disappears very fast. IS that the reason for the issue.

**Capabilities:**
public static void setCapabilities() {
		File appDir = new File("src/test/resources/");
		File app = new File(appDir, "com.olam.digital.ot.uat.apk");
		capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, AppUtil.BROWSER_NAME);
		capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, AppUtil.PLATFORM_NAME);
		capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, AppUtil.DEVICE_NAME);
		capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AppUtil.AUTOMATION_INSTRUMENTATION);
		capabilities.setCapability(MobileCapabilityType.APP,
				app.getAbsolutePath());
		capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, AppUtil.NEW_COMMAND_TIMEOUT);
		capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, AppUtil.DEVICE_READY_TIMEOUT);
		capabilities.setCapability(MobileCapabilityType.UDID, AppUtil.DEVICE_UDID);
		capabilities.setCapability("autoGrantPermissions", true);
		capabilities.setCapability(MobileCapabilityType.FULL_RESET,"false");
		capabilities.setCapability(MobileCapabilityType.NO_RESET,"false");
}

**Properties:**
explicit.wait=120
default.wait=5
implicit.wait=15
application.path=com.xxx.digital.ot.uat.apk
base.pkg=com.xxx.digital.ot
appium.server.port=4725
application.activity=.SplashActivity
automation.instumentation=appium
browser.name=null
platform.name=Android
device.name=Moto C
#device.udid=359608082591899
device.udid=355629085452636
platform.version=4.4.2
new.command.timeout=1000
device.ready.timeout=300

=======================================================
## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 10
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: 7.0.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium node module

## Link to Appium logs

[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"D:\\Thamarai\\Projects\\OT\\OT\\src\\test\\resources\\com.olam.digital.ot.uat.apk","package":"com.olam.digital.ot","noReset":"false","activity":null,"deviceName":"Moto C","fullReset":"false","newCommandTimeout":"300","automationName":"appium","browserName":"null","autoGrantPermissions":true,"platformName":"Android","udid":null}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"D:\\Thamarai\\Projects\\OT\\OT\\src\\test\\resources\\com.olam.digital.ot.uat.apk","package":"com.olam.digital.ot","noReset":"false","activity":null,"deviceName":"Moto C","fullReset":"false","newCommandTimeout":"300","automationName":"appium","browserName":"null","autoGrantPermissions":true,"platformName":"Android","udid":null},null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1547191199292 (12:49:59 GMT+0530 (India Standard Time))
[Appium] Creating new AndroidDriver (v2.7.0) session
[Appium] Capabilities:
[Appium]   app: D:\Thamarai\Projects\OT\OT\src\test\resources\com.olam.digital.ot.uat.apk
[Appium]   package: com.olam.digital.ot
[Appium]   noReset: false
[Appium]   activity: null
[Appium]   deviceName: Moto C
[Appium]   fullReset: false
[Appium]   newCommandTimeout: 300
[Appium]   automationName: appium
[Appium]   browserName: null
[Appium]   autoGrantPermissions: true
[Appium]   platformName: Android
[Appium]   udid: null
[debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {"app":"D:\\Thamarai\\Proje...
[BaseDriver] Capability 'noReset' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Capability 'fullReset' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Capability 'newCommandTimeout' changed from string ('300') to integer (300). This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by appium: package, activity.
[AndroidDriver] The desired capabilities should generally not include both an app and a browserName
[BaseDriver] Session created with session id: ff2eeb33-fe9c-489a-85e4-ebed08ba7533
[debug] [AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_172
[ADB] Checking whether adb is present
[ADB] Found 1 'build-tools' folders under 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk' (newest first):
[ADB]     C:/Users/thamaraiselvi.k/AppData/Local/Android/Sdk/build-tools/28.0.3
[ADB] Using adb.exe from C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[AndroidDriver] Using device: ZW3226GGPK
[debug] [ADB] Setting device id to ZW3226GGPK
[BaseDriver] Using local app 'D:\Thamarai\Projects\OT\OT\src\test\resources\com.olam.digital.ot.uat.apk'
[debug] [AndroidDriver] Checking whether app is actually present
[AndroidDriver] Starting Android session
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK wait-for-device'
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell echo ping'
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Getting install status for io.appium.settings
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell pm list packages io.appium.settings'
[debug] [ADB] App is installed
[debug] [ADB] Getting package info for 'io.appium.settings'
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell dumpsys package io.appium.settings'
[ADB] Checking whether aapt is present
[ADB] Using aapt.exe from C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\build-tools\28.0.3\aapt.exe
[debug] [ADB] The installed 'io.appium.settings' package does not require upgrade (13 > 5)
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell ps'
[debug] [AndroidDriver] io.appium.settings is already running. There is no need to reset its permissions.
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell getprop ro.build.version.sdk'
[debug] [ADB] Current device property 'ro.build.version.sdk': 24
[debug] [ADB] Device API level: 24
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell appops set io.appium.settings android\:mock_location allow'
[AndroidDriver] setDeviceLanguageCountry requires language or country.
[AndroidDriver] Got language: 'null' and country: 'null'
[debug] [Logcat] Starting logcat capture
[debug] [AndroidDriver] Pushing unlock helper app to device...
[debug] [ADB] Getting install status for io.appium.unlock
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell pm list packages io.appium.unlock'
[debug] [ADB] App is installed
[debug] [ADB] Getting package info for 'io.appium.unlock'
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell dumpsys package io.appium.unlock'
[debug] [ADB] The installed 'io.appium.unlock' package does not require upgrade ('2.0.0' >= '2.0.0')
[ADB] Getting device platform version
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell getprop ro.build.version.release'
[debug] [ADB] Current device property 'ro.build.version.release': 7.0
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell wm size'
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell getprop ro.product.model'
[debug] [ADB] Current device property 'ro.product.model': Moto C
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell getprop ro.product.manufacturer'
[debug] [ADB] Current device property 'ro.product.manufacturer': motorola
[debug] [AndroidDriver] Parsing package and activity from app manifest
[ADB] Using the alternative activity name detection method because of: Could not find apkanalyzer.bat in C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\apkanalyzer.bat,C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\emulator\apkanalyzer.bat,C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\tools\apkanalyzer.bat,C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\tools\bin\apkanalyzer.bat,C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\build-tools\28.0.3\apkanalyzer.bat. Do you have the Android SDK installed at 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk'?
[ADB] Extracting package and launch activity from manifest
[ADB] Package name: 'com.olam.digital.ot.uat'
[ADB] Main activity name: 'com.olam.digital.ot.SplashActivity'
[debug] [AndroidDriver] Parsed package and activity are: com.olam.digital.ot.uat/com.olam.digital.ot.SplashActivity
[debug] [ADB] Getting install status for com.olam.digital.ot.uat
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell pm list packages com.olam.digital.ot.uat'
[debug] [ADB] App is installed
[debug] [ADB] Getting install status for com.olam.digital.ot.uat
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell pm list packages com.olam.digital.ot.uat'
[debug] [ADB] App is installed
[debug] [ADB] Getting package info for 'com.olam.digital.ot.uat'
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell dumpsys package com.olam.digital.ot.uat'
[debug] [ADB] The installed 'com.olam.digital.ot.uat' package does not require upgrade (4 === 4)
[AndroidDriver] Performing fast reset on 'com.olam.digital.ot.uat'
[debug] [ADB] Getting install status for com.olam.digital.ot.uat
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell pm list packages com.olam.digital.ot.uat'
[debug] [ADB] App is installed
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell am force-stop com.olam.digital.ot.uat'
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell pm clear com.olam.digital.ot.uat'
[debug] [ADB] Device API level: 24
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell dumpsys package com.olam.digital.ot.uat'
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell pm dump com.olam.digital.ot.uat'
[debug] [ADB] Got the following command chunks to execute: pm,grant,com.olam.digital.ot.uat,android.permission.CAMERA,;,pm,grant,com.olam.digital.ot.uat,android.permission.GET_ACCOUNTS,;,pm,grant,com.olam.digital.ot.uat,android.permission.READ_CONTACTS,;,pm,grant,com.olam.digital.ot.uat,android.permission.WRITE_CONTACTS,;,pm,grant,com.olam.digital.ot.uat,android.permission.WRITE_EXTERNAL_STORAGE,;,pm,grant,com.olam.digital.ot.uat,android.permission.READ_EXTERNAL_STORAGE,;,pm,grant,com.olam.digital.ot.uat,android.permission.ACCESS_FINE_LOCATION,;,pm,grant,com.olam.digital.ot.uat,android.permission.ACCESS_COARSE_LOCATION,;,pm,grant,com.olam.digital.ot.uat,android.permission.READ_PHONE_STATE,;
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell pm grant com.olam.digital.ot.uat android.permission.CAMERA \; pm grant com.olam.digital.ot.uat android.permission.GET_ACCOUNTS \; pm grant com.olam.digital.ot.uat android.permission.READ_CONTACTS \; pm grant com.olam.digital.ot.uat android.permission.WRITE_CONTACTS \; pm grant com.olam.digital.ot.uat android.permission.WRITE_EXTERNAL_STORAGE \; pm grant com.olam.digital.ot.uat android.permission.READ_EXTERNAL_STORAGE \; pm grant com.olam.digital.ot.uat android.permission.ACCESS_FINE_LOCATION \; pm grant com.olam.digital.ot.uat android.permission.ACCESS_COARSE_LOCATION \; pm grant com.olam.digital.ot.uat android.permission.READ_PHONE_STATE \;'
[debug] [AndroidDriver] Performed fast reset on the installed 'com.olam.digital.ot.uat' application (stop and clear)
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell rm -rf /data/local/tmp/strings.json'
[debug] [AndroidDriver] Extracting strings from apk
[debug] [AndroidDriver] D:\Thamarai\Projects\OT\OT\src\test\resources\com.olam.digital.ot.uat.apk
[debug] [AndroidDriver] null
[debug] [AndroidDriver] C:\Users\THAMAR~1.K\AppData\Local\Temp\com.olam.digital.ot.uat
[debug] [ADB] Extracting strings for language: default
[ADB] Successfully extracted 822 strings from 'D:\Thamarai\Projects\OT\OT\src\test\resources\com.olam.digital.ot.uat.apk' resources for '(default)' configuration
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK push C\:\\Users\\THAMAR~1.K\\AppData\\Local\\Temp\\com.olam.digital.ot.uat\\strings.json /data/local/tmp'
[debug] [AndroidBootstrap] Watching for bootstrap disconnect
[debug] [ADB] Forwarding system: 4724 to device: 4724
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK forward tcp\:4724 tcp\:4724'
[debug] [UiAutomator] Starting UiAutomator
[debug] [UiAutomator] Moving to state 'starting'
[debug] [UiAutomator] Parsing uiautomator jar
[debug] [UiAutomator] Found jar name: 'AppiumBootstrap.jar'
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK push C\:\\Users\\thamaraiselvi.k\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-android-bootstrap\\bootstrap\\bin\\AppiumBootstrap.jar /data/local/tmp/'
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell ps'
[debug] [ADB] Attempting to kill process 8485
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell kill -0 8485'
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell kill -0 8485'
[UiAutomator] Error while killing uiAutomator: Error: Unable to kill uiautomator processes. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\thamaraiselvi.k\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s ZW3226GGPK shell kill -0 8485' exited with code 1'; Stderr: '/system/bin/sh: kill: 8485: Operation not permitted'; Code: '1'
[debug] [UiAutomator] Starting UIAutomator
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","ZW3226GGPK","shell","uiautomator","runtest","AppiumBootstrap.jar","-c","io.appium.android.bootstrap.Bootstrap","-e","pkg","com.olam.digital.ot.uat","-e","disableAndroidWatchers",false,"-e","acceptSslCerts",false]
[debug] [UiAutomator] Moving to state 'online'
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] json loading complete.
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Registered crash watchers.
[AndroidBootstrap] Android bootstrap socket is now connected
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell dumpsys window'
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Client connected
[AndroidDriver] Screen already unlocked, doing nothing
[debug] [ADB] Device API level: 24
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell am start -W -n com.olam.digital.ot.uat/com.olam.digital.ot.SplashActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[debug] [ADB] Waiting up to 20000ms for activity matching pkg: 'com.olam.digital.ot.uat' and activity: 'com.olam.digital.ot.SplashActivity' to be focused
[debug] [ADB] Possible activities, to be checked: 'com.olam.digital.ot.SplashActivity', 'com.olam.digital.ot.uat.com.olam.digital.ot.SplashActivity'
[debug] [ADB] Getting focused package and activity
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell dumpsys window windows'
[debug] [ADB] Found package: 'com.olam.digital.ot.uat' and fully qualified activity name : 'com.olam.digital.ot.authentication.AuthenticatorActivity'
[debug] [ADB] Incorrect package and activity. Retrying.
[debug] [ADB] Getting focused package and activity
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell dumpsys window windows'
[debug] [ADB] Found package: 'com.olam.digital.ot.uat' and fully qualified activity name : 'com.olam.digital.ot.authentication.AuthenticatorActivity'
[debug] [ADB] Incorrect package and activity. Retrying.
[debug] [ADB] Getting focused package and activity
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell dumpsys window windows'
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell dumpsys window windows'
[debug] [ADB] Found package: 'com.olam.digital.ot.uat' and fully qualified activity name : 'com.olam.digital.ot.authentication.AuthenticatorActivity'
[debug] [ADB] Incorrect package and activity. Retrying.
[debug] [ADB] Getting focused package and activity
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell dumpsys window windows'
[debug] [ADB] Found package: 'com.olam.digital.ot.uat' and fully qualified activity name : 'com.olam.digital.ot.authentication.AuthenticatorActivity'
[debug] [ADB] Incorrect package and activity. Retrying.
[debug] [ADB] Getting focused package and activity
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell dumpsys window windows'
[debug] [ADB] Found package: 'com.olam.digital.ot.uat' and fully qualified activity name : 'com.olam.digital.ot.authentication.AuthenticatorActivity'
[debug] [ADB] Incorrect package and activity. Retrying.
[debug] [ADB] Getting focused package and activity
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell dumpsys window windows'
[debug] [ADB] Found package: 'com.olam.digital.ot.uat' and fully qualified activity name : 'com.olam.digital.ot.authentication.AuthenticatorActivity'
[debug] [ADB] Incorrect package and activity. Retrying.
[debug] [ADB] Getting focused package and activity
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell dumpsys window windows'
[debug] [ADB] Found package: 'com.olam.digital.ot.uat' and fully qualified activity name : 'com.olam.digital.ot.authentication.AuthenticatorActivity'
[debug] [ADB] Incorrect package and activity. Retrying.
[debug] [ADB] Getting focused package and activity
'com.olam.digital.ot.authentication.AuthenticatorActivity'
[debug] [ADB] Incorrect package and activity. Retrying.
[debug] [ADB] Getting focused package and activity
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell dumpsys window windows'
[debug] [ADB] Found package: 'com.olam.digital.ot.uat' and fully qualified activity name : 'com.olam.digital.ot.authentication.AuthenticatorActivity'
[debug] [ADB] Incorrect package and activity. Retrying.
[debug] [ADB] Getting focused package and activity
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell dumpsys window windows'
[debug] [ADB] Found package: 'com.olam.digital.ot.uat' and fully qualified activity name : 'com.olam.digital.ot.authentication.AuthenticatorActivity'
[debug] [ADB] Incorrect package and activity. Retrying.
[debug] [ADB] Getting focused package and activity
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell dumpsys window windows'
[debug] [ADB] Found package: 'com.olam.digital.ot.uat' and fully qualified activity name : 'com.olam.digital.ot.authentication.AuthenticatorActivity'
[debug] [ADB] Incorrect package and activity. Retrying.
[debug] [AndroidDriver] Shutting down Android driver
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell am force-stop com.olam.digital.ot.uat'
[debug] [ADB] Pressing the HOME button
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell input keyevent 3'
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"shutdown"}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"shutdown"}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type SHUTDOWN
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [UiAutomator] Shutting down UiAutomator
[debug] [UiAutomator] Moving to state 'stopping'
[debug] [UiAutomator] UiAutomator shut down normally
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell ps'
[debug] [ADB] Attempting to kill process 8485
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell kill -0 8485'
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell kill -0 8485'
[UiAutomator] Error while killing uiAutomator: Error: Unable to kill uiautomator processes. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\thamaraiselvi.k\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s ZW3226GGPK shell kill -0 8485' exited with code 1'; Stderr: '/system/bin/sh: kill: 8485: Operation not permitted'; Code: '1'
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Running 'C:\Users\thamaraiselvi.k\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZW3226GGPK shell am force-stop io.appium.unlock'
[debug] [AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1547191281643 (12:51:21 GMT+0530 (India Standard Time))
[MJSONWP] Encountered internal error running command: Error: Cannot start the 'com.olam.digital.ot.uat' application. Original error: 'com.olam.digital.ot.SplashActivity' or 'co[HTTP] <-- POST /wd/hub/session 500 82378 ms - 323
[HTTP] 
m.olam.digital.ot.uat.com.olam.digital.ot.SplashActivity' never started
[MJSONWP]     at ADB.callee$0$0$ (C:\Users\thamaraiselvi.k\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\lib\tools\apk-utils.js:125:11)
[MJSONWP]     at tryCatch (C:\Users\thamaraiselvi.k\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\thamaraiselvi.k\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\thamaraiselvi.k\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (C:\Users\thamaraiselvi.k\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@6da21078
Tests run: 8, Failures: 1, Errors: 0, Skipped: 6, Time elapsed: 90.163 sec <<< FAILURE!
initializeDriver(com.olamnet.OT.TestSuite.AppiumServerTest)  Time elapsed: 89.863 sec  <<< FAILURE!
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.olam.digital.ot.uat' application. Original error: 'com.olam.digital.ot.SplashActivity' or 'com.olam.digital.ot.uat.com.olam.digital.ot.SplashActivity' never started (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 82.53 seconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'INCHN-LAP960', ip: '10.190.4.15', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_172'
Driver info: io.appium.java_client.android.AndroidDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:40)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:36)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:114)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:132)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:92)
	at com.olamnet.OT.TestSuite.AppUtil.getDriver(AppUtil.java:92)
	at com.olamnet.OT.TestSuite.AppiumServerTest.initializeDriver(AppiumServerTest.java:31)

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md

Also, UIA1 backend is considered obsolete for Android API 23+

Closed as not an issue

**Comment by ThamaraiSelvi** [comment]
@mykola-mokhnach Thanks for sharing the link. Reference worked.
Added appWaitActivity and appWaitDuration  which helped to solve the issue.
