### ISSUE TITLE
appium-doctor fails if fbsimctl is custom built

### ISSUE THREAD

**Issue by sbmehdy** [appium/appium#11986]
## The problem

`brew install fbsimctl` has been [failing for me](https://github.com/facebook/FBSimulatorControl/issues/502) so I decided to do a custom build and to symlink the resulting binary to `/usr/local/bin/fbsimctl` (which is found in any of my shells, interactive or not, by just typing `fbsimctl`).
 
However when running `appium-doctor` with such a setup I encounter the following crash:

```bash
info AppiumDoctor Appium Doctor v.1.7.0
info AppiumDoctor ### Diagnostic for necessary dependencies starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: /Users/automation/.nvm/versions/node/v10.15.0/bin/node
info AppiumDoctor  ✔ Node version is 10.15.0
info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ Xcode Command Line Tools are installed in: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ DevToolsSecurity is enabled.
info AppiumDoctor  ✔ The Authorization DB is set up properly.
info AppiumDoctor  ✔ Carthage was found at: /usr/local/bin/carthage
info AppiumDoctor  ✔ HOME is set to: /Users/automation
{ Error: Command 'brew list --versions fbsimctl' exited with code 1
    at ChildProcess.proc.on.code (/Users/automation/.nvm/versions/node/v10.15.0/lib/node_modules/appium-doctor/node_modules/teen_process/lib/exec.js:94:19)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5) stdout: '', stderr: '', code: 1 }
```

## Environment

* Appium-doctor version: 1.7.0
* Appium version: any
* Desktop OS/version used to run Appium: MacOS x86_64 10.14.2 (on a MacMini)
* Node.js version (unless using Appium.app|exe): 10.15.0

## Code To Reproduce Issue

- FBSimctl [built using the custom instructions](https://github.com/facebook/FBSimulatorControl/blob/master/fbsimctl/Documentation/Installation.md) and symlinked (`ln -s /path/to/fbsimctl /usr/local/bin/fbsimctl`).

- Calling `appium-doctor` latest stable version.

**Comment by mykola-mokhnach** [comment]
Did you install the tool as Facebook recommends it (https://github.com/facebook/FBSimulatorControl/tree/master/fbsimctl):

```
# Get the Facebook Tap.
brew tap facebook/fb
# Install fbsimctl from master
brew install fbsimctl --HEAD
```

**Comment by mykola-mokhnach** [comment]
@KazuCocoa FYI

**Comment by KazuCocoa** [comment]
Ah, I understood.
I'll return another message instead of version number such as you probably install the command via custom install.

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-doctor/pull/55

**Comment by KazuCocoa** [comment]
Has been fixed in doctor's branch. Will release it.
