### ISSUE TITLE
Appium 1.10.0 is not correctly connected / registered to Selenium Grid 3.14 or higher

### ISSUE THREAD

**Issue by butomo1989** [appium/appium#11994]
## The problem

Appium 1.10.0 cannot be connected to Selenium Grid version 3.14 or higher. It shows "Failed to connect xxxx". It works perfectly fine with Appium 1.9.1. I use the same configurations for both versions, thats why I think the issue on Appium side not Selenium. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0
* Last Appium version that did not exhibit the issue (if applicable): 1.9.1
* Desktop OS/version used to run Appium: -
* Node.js version (unless using Appium.app|exe): 1.15.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: -

## Details

the screenshot for Appium 1.9.1 with Selenium Grid 3.14
![appium 1 9 1](https://user-images.githubusercontent.com/22218312/51119367-edd2bd80-1812-11e9-97f4-3a41e9303996.png)

the screenshot for Appium 1.10.0 with Selenium Grid 3.14

![appium 1 10 0](https://user-images.githubusercontent.com/22218312/51119374-f4613500-1812-11e9-8789-662f1740332a.png)

## Link to Appium logs

The logs shows that Appium 1.10.0 is connected to Grid, but if you see the Web-UI from the grid, you can see the error. and if you execute any test, test will be in queue.

**Comment by KazuCocoa** [comment]
Can you share your configuration?
I could establish the connection with below config files.
https://github.com/appium/ruby_lib/tree/master/grid

- current master
![image](https://user-images.githubusercontent.com/5511591/51120083-ae7a9000-1857-11e9-8cad-29e330012d77.png)

- 1.10.0 from npm
![image](https://user-images.githubusercontent.com/5511591/51120112-bc301580-1857-11e9-8660-edb5081dd7a8.png)

It's also helpful to understand the situation sharing the output of grid and appium server's console.

**Comment by butomo1989** [comment]
just checked the configuration and sorry, it seems the issue inside the docker (few config are missing) because it uses the newest Ubuntu version, so I will close the ticket. Thank you for the quick reply.

**Comment by pschroeder89** [comment]
@budtmo What were the config changes you needed to make for Ubuntu 18.04?

**Comment by budtmo** [comment]
Hi @pschroeder89 ,

it is not related to the Appium config (it was related with my own script inside[ Docker-Android project](https://github.com/budtmo/docker-android)). it means the config that you use for previous Ubuntu version should work on Ubuntu 18.04 as well. you can see the [example configurations](https://github.com/appium/ruby_lib/tree/master/grid) that @KazuCocoa posted in this issue.
