### ISSUE TITLE
WebDriverWait doesn't wait for iOS elements

### ISSUE THREAD

**Issue by juria** [appium/appium#11993]
## The problem

I'm automizing tests for Android and iOS apps. Lately (probably after I've updated to iOS 12, appium 1.9.1 (now I'm on 1.10.0 and it's the same) and java-client 6.1.0) I have issues with the tests on iOS.

Many tests fail, because WebElements couldn't be found. To find elements I'm using a custom FieldDecorator, or WebDriverWait like in this example:

`private WebElement getWebElement(By by, int timeOutInSeconds) {
    return (new WebDriverWait(appiumDriver, timeOutInSeconds)).until(ExpectedConditions.presenceOfElementLocated(by));
}`

The issue is that the element is visible on the screen, but I get an exception which says that the element is 'not visible on the screen and thus is not interactable' (see the logs). A weird thing about that (and maybe the source of the problem) is that it does not wait the set time to find the element. Everything's fine on Android.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1, 1.10.0
* Last Appium version that did not exhibit the issue (if applicable): 1.8.1
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): v8.11.1
* Mobile platform/version under test: iOS 12.0
* Real device or emulator/simulator: real device (iPhone 7)
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

https://gist.github.com/juria/b9d895d305097d94fa62856e47ff0272

**Comment by mykola-mokhnach** [comment]
This exception is rather caused by `click` call. Make sure the element is not just present, but also visible before clicking it
