### ISSUE TITLE
find_element_by_accessibility_id method takes very long time with Android

### ISSUE THREAD

**Issue by BoazWarshawsky** [appium/appium#11991]
## The problem
I found that it's taking 10 seconds and more to the driver method find_element_by_accessibility_id to complete this call.

## Environment

* Appium version (or git revision) that exhibits the issue:1.10.0
* Last Appium version that did not exhibit the issue (if applicable): 1.10.0
* Desktop OS/version used to run Appium: Desktop
* Node.js version (unless using Appium.app|exe): v8.12.0
* Mobile platform/version under test: Android platform
* Real device or emulator/simulator: Real device and simulator
* Appium CLI or Appium.app|exe: Appium.app

## Details
In my test we can find 3 calls to find_element_by_accessibility_id, here are the measurements: 
1. 
before find_element_by_accessibility_id 2019-01-14 11:22:17.388600
after find_element_by_accessibility_id 2019-01-14 11:22:20.435123

2. 
before find_element_by_accessibility_id 2019-01-14 11:22:26.046922
after find_element_by_accessibility_id 2019-01-14 11:22:34.774202

3. 
before find_element_by_accessibility_id 2019-01-14 11:22:36.775973
after find_element_by_accessibility_id 2019-01-14 11:22:49.926848

Capabilities:
deviceName = Emulator
appPackage = com.featureapp
appActivity = com.applicaster.componentsapp.IntroActivity
host = http://127.0.0.1:4723/wd/hub
platformName = Android
 

## Link to Appium logs
https://github.com/BoazWarshawsky/iOSAutomationAgent/blob/master/appium.log

**Comment by KazuCocoa** [comment]
What about setting `automationName: uiautomator2` or `espresso`?

> [ADB] Device API level: 28
[AndroidDriver] Consider setting 'automationName' capability to 'uiautomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.
[AndroidDriver] App file was not listed, instead we're going to run com.featureapp directly on the device
[AndroidDriver] Checking whether package is present on the device

**Comment by BoazWarshawsky** [comment]
@KazuCocoa , thanks for the quick response,
When adding this to the capabilities (which I did not have at all before):
`automationName = uiautomator2`

The app failed launching and I am getting this error:
https://github.com/BoazWarshawsky/iOSAutomationAgent/blob/master/appium_log_2

**Comment by KazuCocoa** [comment]
Thanks.
Can you get the logcat?

Below error looked uiautomator2 server failed to launch

```
[UiAutomator2] Waiting up to 20000ms for UiAutomator2 to be online...
[JSONWP Proxy] Matched '/status' to command name 'getStatus'
[JSONWP Proxy] Proxying [GET /status] to [GET http://http://127.0.0.1:4723/wd/hub:8200/wd/hub/status] with no body
[UiAutomator2] [UIAutomator2 Error] getaddrinfo ENOTFOUND http://127.0.0.1:4723/wd/hub http://127.0.0.1:4723/wd/hub:5037
[UiAutomator2] Full error: Error: getaddrinfo ENOTFOUND http://127.0.0.1:4723/wd/hub http://127.0.0.1:4723/wd/hub:5037
[UiAutomator2]     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:50:26)
[JSONWP Proxy] Got an unexpected response: {"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"http","host":"http","port":80}
[JSONWP Proxy] Matched '/status' to command name 'getStatus'
[JSONWP Proxy] Proxying [GET /status] to [GET http://http://127.0.0.1:4723/wd/hub:8200/wd/hub/status] with no body
[JSONWP Proxy] Got an unexpected response: {"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"http","host":"http","port":80}
[JSONWP Proxy] Matched '/status' to command name 'getStatus'
```

**Comment by BoazWarshawsky** [comment]
Does `uiautomator2 server` is something I should turn on? I only start the Appium server before running the test

**Comment by BoazWarshawsky** [comment]
@KazuCocoa 
Here you can find the device log:
https://github.com/BoazWarshawsky/iOSAutomationAgent/blob/master/device_log

**Comment by KazuCocoa** [comment]
Thanks. I read the log, but I could not find any issues...

> Does uiautomator2 server is something I should turn on?

No. In general, the server should launch by Appium server.

Could you follow below?

1. uninstall all of io.appium.uiautomator2.server and io.appium.uiautomator2.server.test manually
2. update to the latest `appium@beta` (it has some improvements for the initialisation)
3. run your app with uiautomator2

And could you share appium log and logcat again if you face the error then?
@BoazWarshawsky

**Comment by BoazWarshawsky** [comment]
Where these installs found? I am using Appium Desktop, you mean to remove this?
Run from CLI?

**Comment by KazuCocoa** [comment]
Ah, I see. yes, from CLI.

http://appium.io/docs/en/about-appium/intro/ 's _Appium Server_ section is helpful to run `@beta`

**Comment by BoazWarshawsky** [comment]
How do I uninstall the `io.appium.uiautomator2` and `io.appium.uiautomator2.server.test`? 
I just upgraded to appium CLI 1.11.0-beta.3 but its still not working.

**Comment by KazuCocoa** [comment]
The easiest way is open installed app list via settings app

**Comment by BoazWarshawsky** [comment]
Still having this error:

debug] [ADB] Checking app cert for null
[debug] [ADB] 'null' does not exist
[debug] [ADB] Getting IDs of all 'uiautomator' processes
[debug] [ADB] Running '/Users/boazwarshawsky/Library/Android/sdk/platform-tools/adb -P 5037 -s FA8211A03831 shell pidof uiautomator'
[debug] [ADB] Running '/Users/boazwarshawsky/Library/Android/sdk/platform-tools/adb -P 5037 -s FA8211A03831 shell am force-stop io.appium.uiautomator2.server'
[UiAutomator2] Starting UIAutomator2 server 3.1.1
[UiAutomator2] Using UIAutomator2 server from '/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.1.1.apk' and test from '/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk'
[UiAutomator2] Running command: 'adb -s FA8211A03831 shell am instrument -w io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner'
[UiAutomator2] Waiting up to 20000ms for UiAutomator2 to be online...
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://http://127.0.0.1:4723/wd/hub:8200/wd/hub/status] with no body
[UiAutomator2] [UIAutomator2 Error] getaddrinfo ENOTFOUND http://127.0.0.1:4723/wd/hub http://127.0.0.1:4723/wd/hub:5037
[debug] [UiAutomator2] Full error: Error: getaddrinfo ENOTFOUND http://127.0.0.1:4723/wd/hub http://127.0.0.1:4723/wd/hub:5037
[debug] [UiAutomator2]     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
[WD Proxy] Got an unexpected response: {"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"http","host":"http","port":80}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://http://127.0.0.1:4723/wd/hub:8200/wd/hub/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"http","host":"http","port":80}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://http://127.0.0.1:4723/wd/hub:8200/wd/hub/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"http","host":"http","port":80}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://http://127.0.0.1:4723/wd/hub:8200/wd/hub/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"http","host":"http","port":80}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://http://127.0.0.1:4723/wd/hub:8200/wd/hub/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"http","host":"http","port":80}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://http://127.0.0.1:4723/wd/hub:8200/wd/hub/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"http","host":"http","port":80}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://http://127.0.0.1:4723/wd/hub:8200/wd/hub/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"http","host":"http","port":80}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://http://127.0.0.1:4723/wd/hub:8200/wd/hub/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"http","host":"http","port":80}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://http://127.0.0.1:4723/wd/hub:8200/wd/hub/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"http","host":"http","port":80}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://http://127.0.0.1:4723/wd/hub:8200/wd/hub/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"http","host":"http","port":80}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://http://127.0.0.1:4723/wd/hub:8200/wd/hub/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"http","host":"http","port":80}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://http://127.0.0.1:4723/wd/hub:8200/wd/hub/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"http","host":"http","port":80}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://http://127.0.0.1:4723/wd/hub:8200/wd/hub/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"http","host":"http","port":80}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://http://127.0.0.1:4723/wd/hub:8200/wd/hub/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"http","host":"http","port":80}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://http://127.0.0.1:4723/wd/hub:8200/wd/hub/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"http","host":"http","port":80}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://http://127.0.0.1:4723/wd/hub:8200/wd/hub/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"http","host":"http","port":80}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://http://127.0.0.1:4723/wd/hub:8200/wd/hub/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"http","host":"http","port":80}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://http://127.0.0.1:4723/wd/hub:8200/wd/hub/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"http","host":"http","port":80}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://http://127.0.0.1:4723/wd/hub:8200/wd/hub/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"http","host":"http","port":80}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://http://127.0.0.1:4723/wd/hub:8200/wd/hub/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"http","host":"http","port":80}
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[debug] [WD Proxy] Matched '/' to command name 'deleteSession'
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
[debug] [ADB] Running '/Users/boazwarshawsky/Library/Android/sdk/platform-tools/adb -P 5037 -s FA8211A03831 shell am force-stop com.featureapp'
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8200
[debug] [ADB] Running '/Users/boazwarshawsky/Library/Android/sdk/platform-tools/adb -P 5037 -s FA8211A03831 forward --remove tcp\:8200'
[UiAutomator2] Restoring hidden api policy to the device default configuration
[debug] [ADB] Running '/Users/boazwarshawsky/Library/Android/sdk/platform-tools/adb -P 5037 -s FA8211A03831 shell settings delete global hidden_api_policy_pre_p_apps'
[debug] [ADB] Running '/Users/boazwarshawsky/Library/Android/sdk/platform-tools/adb -P 5037 -s FA8211A03831 shell settings delete global hidden_api_policy_p_apps'
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1547475615977 (16:20:15 GMT+0200 (IST))
[debug] [W3C] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: getaddrinfo ENOTFOUND http http:80
[debug] [W3C]     at JWProxy.command (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:236:13)
[debug] [W3C]     at <anonymous>
[HTTP] <-- POST /wd/hub/session 500 22053 ms - 590
[HTTP]

**Comment by KazuCocoa** [comment]
I got it. You set `host` capability which does not in http://appium.io/docs/en/writing-running-appium/caps/ . You can see below message in your appium log.

```
[BaseDriver] The following capabilities were provided, but are not recognized by appium: host.
```
 
> [debug] [WD Proxy] Proxying [GET /status] to [GET http://http://127.0.0.1:4723/wd/hub:8200/wd/hub/status] with no body

should be `GET http://localhost:8200/wd/hub/status` without `host` capability.

**Comment by BoazWarshawsky** [comment]
Status is that I managed to run with `uiautomator2` but I am still having the slowness issue, and its even worse (even click takes a very long time), these are the measurements:


1. 
BEFORE VERIFY HOME SCREEN 2019-01-14 16:59:32.924089
AFTER VERIFY HOME SCREEN 2019-01-14 17:00:04.126483

2. 
BEFORE GET FROM MAIN 2019-01-14 17:00:04.126731
AFTER GET FROM MAIN 2019-01-14 17:00:34.651078

3.
BEFORE CLICK FROM MAIN 2019-01-14 17:00:34.651291
AFTER CLICK FROM MAIN 2019-01-14 17:01:04.905675

**Comment by BoazWarshawsky** [comment]
Page resource also takes 10 seconds:
BEFORE PAGE RESOURCE 2019-01-14 17:51:43.639044
AFTER PAGE RESOURCE 2019-01-14 17:51:54.485417

**Comment by BoazWarshawsky** [comment]
@KazuCocoa , I am real stuck with this issue, any advice here?

**Comment by KazuCocoa** [comment]
Did you run with `espresso` driver as I addressed as 3?

**Comment by BoazWarshawsky** [comment]
I am not sure I want to move to `espresso`, that is my only option here?

**Comment by KazuCocoa** [comment]
Not sure for now.
If it is because of Android framework stuff, we cannot do anything in Appium side. (Maybe, you need to improve app side.)

It gives us a hint.
