### ISSUE TITLE
For different Android versions, the same Appium v1.8.1 is showing element text in two different attributes 

### ISSUE THREAD

**Issue by rajeev2** [appium/appium#11997]
## The problem

When using Appium v1.8.1, 
For Android 8 & 9 element value is appearing in "text" attribute(@text) but 
when I am trying to locate the same element on Android 7.1.2, element value is appearing in "content-desc" attribute and not the "text" attribute.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.8.1
* Desktop OS/version used to run Appium: macOS High Sierra (10.13)
* Mobile platform/version under test: Android 8, Android 9, Android 7.1.2
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium.app (mac machine)

## Details

I am facing the main problem while locating the element.
- In Android 8 & 9, When I am trying to locate the element using locator "@text", it does not return any value but 
- In Android 7.1.2, when I am trying to locate the same element using "@content-desc" using the same Appium v1.8.1, I am able to locate the element.

**Note:** I am not using "@content-desc" for Android 8 & 9 because it's value is blank for these android versions in Appium v1.8.1. 

PFA screenshot in gist url.

## Link to Appium logs

https://gist.github.com/rajeev2/fbf928a87c9832897a29cf779c643c35

**Comment by mykola-mokhnach** [comment]
- The most recent Appium version is 1.10, we don't provide any patches to older versions
- The attributes are tasked from what UIA framework provides, so there is nothing much that can be done there. You can try different backends, for example the Espresso one

**Comment by mykola-mokhnach** [comment]
The full server log is missing

**Comment by rajeev2** [comment]
Added the complete logs in the same gist url:

https://gist.github.com/rajeev2/fbf928a87c9832897a29cf779c643c35

**Comment by rajeev2** [comment]
> The full server log is missing

Added the complete logs in the same gist url:

https://gist.github.com/rajeev2/fbf928a87c9832897a29cf779c643c35

**Comment by mykola-mokhnach** [comment]
Try the Espresso driver. I don't have any other suggestions

**Comment by mykola-mokhnach** [comment]
Closed as third party problem
