### ISSUE TITLE
logEntry timestamp is always the same

### ISSUE THREAD

**Issue by notihs** [appium/appium#11998]
## The problem
After calling ´manage().logs().get("server");´ and trying to print the timestamp for each logEntry returned by that call, the timestamp is always the same, when clearly on appium server the timestamp is different.

## Environment

* Appium 1.11.0-beta.2
* Desktop OS/version used to run Appium: MacOS Mojave
* Node.js version (unless using Appium.app|exe): 11.4.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real device

## Appium logs
https://gist.github.com/notihs/fea728dee727273bc847b60635479db5

## Returned timestamp
https://gist.github.com/notihs/ca3cf432c1e802ed2edbfbfc5848f58f

As you can see on logs, after we call that method, the timestamp obtained on logEntry is equal to when we called that method

**Comment by mykola-mokhnach** [comment]
This is expected, since the logger does not collect event timestamps in the buffer, but only the textual content of them. Feel free to push a PR if you'd prefer to change that

**Comment by notihs** [comment]
Actually I don't mind doing that, in my spare time. 
Can someone point me into the right direction? 
Where should I start looking?

**Comment by mykola-mokhnach** [comment]
Sure, you can start here:
https://github.com/appium/appium-android-driver/blob/bea2743dd5d868ab3eac966a08419ba47b29208c/lib/commands/log.js#L42
