### ISSUE TITLE
Navigating to "appium.io" by default instead of the specified URL on Safari browser while running on real device

### ISSUE THREAD

**Issue by DivyaLNarayan** [appium/appium#12006]
## The problem

Navigating to "appium.io" by default instead of the specified URL on Safari browser while running on real device
* Appium version - (1.6.2) that exhibits the issue:
* Real device

Link for the appium log
https://gist.github.com/DivyaLNarayan/e91e1c330641cc6facbe758e6aa7b30e

## Code To Reproduce Issue [ Good To Have ]
driver().navigate().to("https://www.gmail.com");

**Comment by imurchie** [comment]
This is expected. Appium goes to a default url to begin with, during session creation. Once you have a session you would do the navigating to where you want to go.

To go to a specific url during session creation, set the `safariInitialUrl` desired capability, to the url you want.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by DivyaLNarayan** [comment]
@mykola-mokhnach @imurchie : Im still not able to fix the problem even after setting the capabilities it is opening appium.io

**Comment by imurchie** [comment]
Please attach the full logs (as a link to a [gist](https://gist.github.com)) or there is nothing that we can do to help.

**Comment by DivyaLNarayan** [comment]
@mykola-mokhnach  @imurchie : Please find the link to the logs
https://gist.github.com/DivyaLNarayan/e91e1c330641cc6facbe758e6aa7b30e
