### ISSUE TITLE
Cannot switch to chrome custom tab

### ISSUE THREAD

**Issue by twiindan** [appium/appium#12004]
## The problem

I'm trying to switch from native app to a Chrome Custom Tab. When I get contexts I'm retrieving 2 different webviews in the contexts ["NATIVE_APP","WEBVIEW_chrome","WEBVIEW_com.lidl.eci.lidlplus"].

I try to set the context to both webviews but always get an Error with the ChromeDriver  [Chromedriver] Error: unknown error: unable to discover open pages.

Investigating I saw in the logs that the ChromeDriver is not capable to connect to the Chrome Dev Tools but I can access it when I use directly the Google Dev Tools (without ChromeDriver)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MAC / Mojave
* Node.js version (unless using Appium.app|exe): 
* Mobile platform/version under test: Android 8.0 
* Real device or emulator/simulator: Both
* Appium CLI or Appium.app|exe: Appium app

## Link to Appium logs

https://gist.github.com/twiindan/59976186d5d69a3efc25dec6f3f6eddb

**Comment by mykola-mokhnach** [comment]
Closed as inactive
