### ISSUE TITLE
iOS - Unable to locate some elements in subviews

### ISSUE THREAD

**Issue by ChristopherSmit** [appium/appium#12001]
## The problem

Our team recently updated our test framework from Calabash to Appium 1.10.0 and we’re having issues accessing elements via Appium in our native iOS app. The app contains several views for which our accessibility team has specifically requested that only the main view be visible for accessibility purposes - for example, a view that contains separate subviews for an item’s color and size should be handled as a single swipe that reads off both text labels when navigating the app with VoiceOver. When using Calabash, we were able to locate all of the individual views (the parent view and its subviews) by ```accessibility_id```, but with the switch to Appium, we find that the subviews are not visible and we can only select the ‘parent’ view.

Others have submitted similar issues in the past, and the answer given previously is to make sure that the parent container view is NOT labelled as accessible, while the subviews are. This closed issue is often linked as an answer: https://github.com/appium/appium/issues/6517#issuecomment-2980370461. The solution given here won’t work for us, as our accessibility team has requested that only the parent container be accessible when navigating the app via VoiceOver. I posted [this issue](https://discuss.appium.io/t/unable-to-locate-some-elements-in-ios-same-elements-can-be-found-via-calabash/24810) on the appium forum previously, but haven't had any input. Submitting this as a new issue again because:
- There's a valid use case for this scenario
- All of the views/subviews are able to be seen by another test framework

## Environment

- Appium version (or git revision) that exhibits the issue: **1.10.0**
- Last Appium version that did not exhibit the issue (if applicable): **n/a**
- Desktop OS/version used to run Appium: **Mac 10.13.6**
- Node.js version (unless using Appium.app|exe): **11.1.0**
- Mobile platform/version under test: **iOS 12.1.2**
- Real device or emulator/simulator: **real devices**
- Appium CLI or Appium.app|exe: **Appium CLI**

## Details
Here is an example that's representative of the elements we see when viewing the app tree/source in Calabash vs. Appium:

**Calabash ‘tree’:**
```
[UIView]
[UIView] [label: red, XL]
    [UIView]
    [UILabel] [id:color] [label:red] [text:red]
    [UILabel] [id:size] [label:XL] [text:XL]
    [UIImageView] [id:item_img]
    [UIView]
```
**Appium ‘source’:**
```
<XCUIElementTypeOther type="XCUIElementTypeOther enabled="true" visible="true" x="0" y="426" width="375" height="100">
    <XCUIElementTypeButton type="XCUIElementTypeButton" name="red, XL" label="red, XL" enabled="true" visible="true" x="0" y="456" width="375" height="121" />
    <XCUIElementTypeOther type="XCUIElementTypeOther enabled="true" visible="false" x="10" y="536" width="355" height="1"/>
</XCUIElementTypeOther>
```

As shown in the examples, Calabash allows us to access the individual elements (`color`, `size`, `item_img`), but these views are not found in the Appium XML source - only the parent node (`XCUIElementTypeButton`) is available in the page source.

We’re curious if anyone else has encountered a similar problem with Appium, and been able to come up with a solution. Unfortunately, I’m prevented from sharing code/logs by company policy, but please let me know if there’s any other information I can provide.

## Link to Appium logs

Unfortunately, company policy prohibits me from sharing code/logs.

## Code To Reproduce Issue [ Good To Have ]

Unfortunately, company policy prohibits me from sharing code/logs.

**Comment by mykola-mokhnach** [comment]
I don't think we can help here without having all the necessary pieces of the data. Although, you have the source code available, so you could try to compare the WebDriverAgent's approach to get the xml hierarchy with the approach used in the "other test framework" and figure out why it does not work for your particular application.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
