### ISSUE TITLE
how to click using the point options ?

### ISSUE THREAD

**Issue by kaushikbabbi** [appium/appium#12007]
## The problem

I want to use the co ordinates and click an element.
Below is my code
import io.appium.java_client.touch.offset.PointOption;

TouchAction t =new TouchAction(driver);
PointOption point=new PointOption();
new TouchAction(driver).tap(PointOption.point(299,437)).perform();		 

## Environment

* Appium version : v1.10.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test : 5.1
* Real device or emulator/simulator : real device
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by biwkf** [comment]
Try new TouchAction(driver).tap(PointOption.point(299,437))**.release()**.perform();

**Comment by mykola-mokhnach** [comment]
Please use Appium forum for questions
