### ISSUE TITLE
Appium CI

### ISSUE THREAD

**Issue by imurchie** [appium/appium#12012]
## The problem

We have determined that nightly builds, where the Appium bundle is pushed to Sauce Labs and the driver tests are run against that, are the best way to proceed with a more robust CI system. This provides nightly verification of all published code, against a large swath of devices, and does so through the entire mechanism of Appium (instead of just the driver, like the per-PR CI running solely in Travis).

This is currently running for `appium-xcuitest-driver` (simulators... we still need to figure out real devices). While the testing scheme for `appium-ios-driver` and `appium-android-driver` make it impossible to do there (both test suites were written to access the driver directly, without going through the remote interface), this CI strategy can be implemented in `appium-uiautomator2-driver` and `appium-espresso-driver`.

**Comment by mykola-mokhnach** [comment]
Closed as obsolete
