### ISSUE TITLE
Hide keyboard in v.1.10.1 does not work

### ISSUE THREAD

**Issue by Nabywaniec** [appium/appium#12028]
## The problem

Hide keyboard in v.1.10.1 does not work, it works on v.1.10.0

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.1
* Last Appium version that did not exhibit the issue (if applicable): 1.10.0
* Desktop OS/version used to run Appium:  Ubuntu 18.04.1 LTS
* Node.js version (unless using Appium.app|exe): v.8.10.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Huawei MediaPad T3 10
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

[debug] [W3C (de9fcf6e)] Calling AppiumDriver.hideKeyboard() with args: [null,null,null,null,"de9fcf6e-5c0b-47ef-8cf1-1eca243c5196"]
[debug] [ADB] Running '/usr/bin/adb -P 5037 -s 4JPNU18805104589 shell dumpsys input_method'
[debug] [ADB] Running '/usr/bin/adb -P 5037 -s 4JPNU18805104589 shell input keyevent 111'
[debug] [ADB] Running '/usr/bin/adb -P 5037 -s 4JPNU18805104589 shell dumpsys input_method'
[debug] [ADB] Running '/usr/bin/adb -P 5037 -s 4JPNU18805104589 shell dumpsys input_method'
[debug] [ADB] Running '/usr/bin/adb -P 5037 -s 4JPNU18805104589 shell dumpsys input_method'
[debug] [ADB] Running '/usr/bin/adb -P 5037 -s 4JPNU18805104589 shell dumpsys input_method'
[debug] [ADB] Running '/usr/bin/adb -P 5037 -s 4JPNU18805104589 shell dumpsys input_method'
[debug] [W3C (de9fcf6e)] Encountered internal error running command: Error: The software keyboard cannot be closed
[debug] [W3C (de9fcf6e)]     at AndroidDriver.commands.hideKeyboard (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/general.js:82:13)
[debug] [W3C (de9fcf6e)]     at <anonymous>
[HTTP] <-- POST /wd/hub/session/de9fcf6e-5c0b-47ef-8cf1-1eca243c5196/appium/device/hide_keyboard 500 3335 ms - 593

**Comment by mykola-mokhnach** [comment]
This has been addressed in appium@beta Closed as duplicate
