### ISSUE TITLE
The sendkeys method is not working properly on Android

### ISSUE THREAD

**Issue by estefafdez** [appium/appium#12026]
## The problem

I need to create a method to send a text by the sendKeys method to send a text character by character that works on Android and on iOS to check an auto-completion list. 

My logic is the following:

```
protected void sendTextCharByCharToElement(WebElement element, String text) {
      if (text != null) {
           for (char c : text.toCharArray())
          this.driver.findElement(element).sendKeys(Character.toString(c));
        }
...
} 
```

This method works perfectly on iOS but not on Android when I get the following problem:
(please, check the GIF on this URL)

https://imgur.com/a/AKGpnVB

Is there any way to do this method on Android? Thanks. 

## Environment

* Appium version: 1.9.1 
* Node.js version: v10.6.0
* Mobile platform/version under test: Mac OS Mojave 10.14.2 (18C54)
* Real device or emulator/simulator: Android emulator API 27 (Version 8.1.0).
* Appium CLI or Appium.app|exe: Java Client Version

## Capabilities:

[Appium]   platformName: android
[Appium]   app: /Volumes/Seguridad/ProyectosQA/appium-archetype/src/test/resources/files/AndroidBaristaApp.apk
[Appium]   appActivity:
[Appium]   appPackage: com.example.estefafdez.myfirstandroidapp
[Appium]   appWaitActivity:
[Appium]   autoGrantPermissions: true
[Appium]   automationName: Appium
[Appium]   clearSystemFiles: true
[Appium]   deviceName: emulator_27
[Appium]   disableAndroidWatchers: true
[Appium]   fullReset: false
[Appium]   noReset: false
[Appium]   platformVersion: 8.1.0

## Link to Appium logs

Full Appium Log: https://gist.github.com/estefafdez/e070957a4d3fea3e55195b6d9dee24a5

## APK used.

The apk I used is an open source project I created myself to start with Appium. You can download it from here: https://github.com/estefafdez/AndroidBaristaProject

Thank you for your help!

**Comment by estefafdez** [comment]
Note: if I use the method with setValue it works, it's like the auto-complete from the android keyboard is not triggered.

`this.driver.findElement (By.id ("text1")). setValue ("Your text here");`

**Comment by mykola-mokhnach** [comment]
sendKeys won't work for such task. You can try to use the approach described in https://appiumpro.com/editions/46 or https://appiumpro.com/editions/34

**Comment by estefafdez** [comment]
Thank you @mykola-mokhnach :)
