### ISSUE TITLE
While opening Appium Desktop for Android to Inspect :An unknown server-side error occurred while processing the command. Original error: Command 'java -version' exited with code 20

### ISSUE THREAD

**Issue by Bhargavchirumamilla** [appium/appium#12029]
![screenshot 2019-01-18 at 5 24 31 pm](https://user-images.githubusercontent.com/32735310/51385694-08c06d00-1b46-11e9-9410-19d60cdca128.png)
## The problem

While Opening Appium Desktop for Android to identify Locators I am facing issue like :
An unknown server-side error occurred while processing the command. Original error: Command 'java -version' exited with code 20.

## Environment

* Appium version :V1.9.1
* System Os:MAC: macOS Mojave 10.14
* java version "1.8.0_181"
## Link to Appium logs

￼
The server is running

[Appium] Welcome to Appium v1.9.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/sessions
[HTTP] {}
[GENERIC] Calling AppiumDriver.getSessions() with args: []
[GENERIC] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 8 ms - 40
[HTTP] 
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"/Users/7(1).apk","appActivity":"","appPackage":"","automationName":"Appium","deviceName":"Android","platformName":"Android","platformVersion":"7.1.1","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/bhargavdreammapper/Downloads/DreamMapper_2.18.101_Alpha_Jan_07 (1).apk","appActivity":"com.philips.sleepmapper.activity.SplashScreenActivity","appPackage":"com.philips.sleepmapper.root","automationName":"Appium","deviceName":"Android","platformName":"Android","platformVersion":"7.1.1","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1547810573550 (16:52:53 GMT+0530 (IST))
[Appium] Consider setting 'automationName' capability to 'UiAutomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.
[Appium] Creating new AndroidDriver (v4.1.1) session
[Appium] Capabilities:
[Appium]   app: /Users/_Jan_07 (1).apk
[Appium]   appActivity: Activity
[Appium]   appPackage: com.root
[Appium]   automationName: Appium
[Appium]   deviceName: Android
[Appium]   platformName: Android
[Appium]   platformVersion: 7.1.1
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[BaseDriver] Creating session with MJSONWP desired capabilities: {"app":"/Users/...
[BaseDriver] The following capabilities were provided, but are not recognized by appium: connectHardwareKeyboard.
[BaseDriver] Session created with session id: fff3ba67-00d0-44ab-8817-416f86461e3a
[AndroidDriver] Shutting down Android driver
[AndroidDriver] Called deleteSession but bootstrap wasn't active
[BaseDriver] Event 'newSessionStarted' logged at 1547810573614 (16:52:53 GMT+0530 (IST))
[MJSONWP] Encountered internal error running command: Error: Command 'java -version' exited with code 20
[MJSONWP]     at ChildProcess. (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/teen_process/lib/exec.js:94:19)
[MJSONWP]     at emitTwo (events.js:126:13)
[MJSONWP]     at ChildProcess.emit (events.js:214:7)
[MJSONWP]     at maybeClose (internal/child_process.js:925:16)
[MJSONWP]     at Socket.stream.socket.on (internal/child_process.js:346:11)
[MJSONWP]     at emitOne (events.js:116:13)
[MJSONWP]     at Socket.emit (events.js:211:7)
[MJSONWP]     at Pipe._handle.close [as _onclose] (net.js:554:12)
[HTTP] <-- POST /wd/hub/session 500 67 ms - 180
[HTTP] 
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 8 ms - 57
[HTTP] 
[HTTP] --> GET /wd/hub/sessions
[HTTP] {}
[GENERIC] Calling AppiumDriver.getSessions() with args: []
[GENERIC] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 1 ms - 40
[HTTP] 
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"/Users/bhargavdreammapper/Downloads/DreamMapper_2.18.101_Alpha_Jan_07 (1).apk","appActivity":"com.philips.sleepmapper.activity.SplashScreenActivity","appPackage":"com.philips.sleepmapper.root","automationName":"Appium","deviceName":"Android","platformName":"Android","platformVersion":"7.1.1","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/bhargavdreammapper/Downloads/DreamMapper_2.18.101_Alpha_Jan_07 (1).apk","appActivity":"com.philips.sleepmapper.activity.SplashScreenActivity","appPackage":"com.philips.sleepmapper.root","automationName":"Appium","deviceName":"Android","platformName":"Android","platformVersion":"7.1.1","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1547810780667 (16:56:20 GMT+0530 (IST))
[Appium] Consider setting 'automationName' capability to 'UiAutomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.
[Appium] Creating new AndroidDriver (v4.1.1) session
[Appium] Capabilities:
[Appium]   app: /Users7 (1).apk
[Appium]   appActivity: com.Activity
[Appium]   appPackage: com..root
[Appium]   automationName: Appium
[Appium]   deviceName: Android
[Appium]   platformName: Android
[Appium]   platformVersion: 7.1.1
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[BaseDriver] Creating session with MJSONWP desired capabilities: {"app":"/Users/beam...
[BaseDriver] The following capabilities were provided, but are not recognized by appium: connectHardwareKeyboard.
[BaseDriver] Session created with session id: a019b6b4-d64f-46f7-9443-bd26f8bf1409
[AndroidDriver] Shutting down Android driver
[AndroidDriver] Called deleteSession but bootstrap wasn't active
[BaseDriver] Event 'newSessionStarted' logged at 1547810780705 (16:56:20 GMT+0530 (IST))
[MJSONWP] Encountered internal error running command: Error: Command 'java -version' exited with code 20
[MJSONWP]     at ChildProcess. (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/teen_process/lib/exec.js:94:19)
[MJSONWP]     at emitTwo (events.js:126:13)
[MJSONWP]     at ChildProcess.emit (events.js:214:7)
[MJSONWP]     at maybeClose (internal/child_process.js:925:16)
[MJSONWP]     at Socket.stream.socket.on (internal/child_process.js:346:11)
[MJSONWP]     at emitOne (events.js:116:13)
[MJSONWP]     at Socket.emit (events.js:211:7)
[MJSONWP]     at Pipe._handle.close [as _onclose] (net.js:554:12)
[HTTP] <-- POST /wd/hub/session 500 44 ms - 180
[HTTP] 
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 1 ms - 57
[HTTP] 

Note: While Running in Eclipse Code is working fine, While inspect the locators in Android it is failing.

Help me out.

**Comment by imurchie** [comment]
What happens if you run `java -version` in a shell?

**Comment by Bhargavchirumamilla** [comment]
> What happens if you run `java -version` in a shell?

It showing : java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

![screenshot 2019-01-18 at 6 10 32 pm](https://user-images.githubusercontent.com/32735310/51387541-69eb3f00-1b4c-11e9-9cd7-12fe4b246729.png)

**Comment by mykola-mokhnach** [comment]
I have excluded java version verification from the upcoming versions of android drivers as obsolete.

Closed as not an issue
