### ISSUE TITLE
fullReset=true does not delete app on real device

### ISSUE THREAD

**Issue by nemue** [appium/appium#12033]
## The problem

When I set the fullReset capability to true, the app is not deleted from the device. I have seen there have been several tickets concerning that issue, which have already been closed. I read in one that it's probably not supposed to work on real devices. If that's the case, please change the documentation accordingly:
http://appium.io/docs/en/writing-running-appium/other/reset-strategies/

## Environment

* Appium version (or git revision) that exhibits the issue: Version 1.10.0 (1.10.0.20181230.2)
* Last Appium version that did not exhibit the issue (if applicable): –
* Desktop OS/version used to run Appium: Mac OS 10.13.6
* Node.js version (unless using Appium.app|exe): v8.11.4
* Mobile platform/version under test: iOS 11.4 (iPhone 6) and iOS 10.3 (iPhone 5)
* Real device or emulator/simulator: iPhone 6S Plus and iPhone 5S
* Appium CLI or Appium.app|exe: Appium.app

**Comment by mykola-mokhnach** [comment]
When exactly do you expect the app is deleted?

**Comment by nemue** [comment]
@mykola-mokhnach, after the test is finished. It says in the documentation in the fullReset column: "Uninstall app after real device test, destroy Simulator after sim test".

**Comment by mykola-mokhnach** [comment]
It will probably behave different if `resetOnSessionStartOnly` is set to `false`. Although, by default fullReset only uninstalls the app under test before a new sessions starts (it's consistent across all drivers), so it is really an issue with the documentation.

**Comment by dpgraham** [comment]
PR in: https://github.com/appium/appium/pull/12352
