### ISSUE TITLE
Native popup JOIN/CANCEL takes more than a minute to click

### ISSUE THREAD

**Issue by aryalakshmi** [appium/appium#12039]
Hi,

I automate an app which asks user to join WiFi network by popup JOIN/CANCEL.
If I try to click it using its xpath //XCUIElementTypeButton[@name=Join]  the click action takes more than a minute. I could see in appium logs that it is stuck at finding the element during that time .
All other native popups that appear in app are generated by the app and they get accepted by setting capability autoAcceptAlerts to true .
May I know what could be the issue?
I use appium 1.10
iPhone 5s/ iOS 12.1
Also, the popup could not be inspected using appium inspector

**Comment by aryalakshmi** [comment]
Hi,
As i told i am not able to inspect this popup using appium inspector also. 
Now, i changed the path to  xpath //XCUIElementTypeButton[@name=Join], accessibility_id=Join 
but, still issue exists. Not able to attach full appium logs as gist is getting crashed when i do it.
Please find a snippet of the code that takes element find longer.

https://gist.github.com/aryalakshmi/fc4cb8d4153ea4fb4188875d126e3e18

**Comment by aryalakshmi** [comment]
Hi,

I used this one initially and it clicks //XCUIElementTypeButton[@name=Join] but very late. The wrong path you mentioned also clicks . Also the JOIN popup is not inspectable using appium inspector

**Comment by mykola-mokhnach** [comment]
I don't have any other suggestions. Elements location is done by [WebDriverAgent](https://github.com/facebook/WebDriverAgent). Try to report your issue to that project as there is nothing that can be fixed on Appium side.
