### ISSUE TITLE
Appium-doctor on Windows: Command 'npm' not found. Is it installed?

### ISSUE THREAD

**Issue by ThinkDone** [appium/appium#12048]
## The problem

Run "appium-doctor --debug" on Windows 7/10， prompting: "Error: Command 'npm' not found. Is it installed?"

## Environment

* Desktop OS/version used to run Appium: Win10
* Node.js version: 11.2.0
* Appium doctor version: 1.7.0

## Details

I tried to locate the problem and found that the npm command is called npm.cmd under windows. Appium doctor is not compatible with Windows when calling exec in OptionalOpencv4nodejsCommandCheck function.

## Appium-doctor logs

info AppiumDoctor Appium Doctor v.1.7.0
info AppiumDoctor ### Diagnostic for necessary dependencies starting ###
dbug AppiumDoctor Node binary found at: C:\Program Files\nodejs\node.EXE
info AppiumDoctor  ✔ The Node.js binary was found at: C:\Program Files\nodejs\node.EXE
dbug AppiumDoctor Node binary found at: C:\Program Files\nodejs\node.EXE
info AppiumDoctor  ✔ Node version is 11.2.0
dbug AppiumDoctor Error: Command 'npm' not found. Is it installed?
dbug AppiumDoctor     at ChildProcess.proc.on.err (C:\Users\Administrator\AppData\Roaming\npm\node_modules\appium-doctor\node_modules\teen_process\lib\exec.js:39:14)
dbug AppiumDoctor     at ChildProcess.emit (events.js:182:13)
dbug AppiumDoctor     at Process.ChildProcess._handle.onexit (internal/child_process.js:252:12)
dbug AppiumDoctor     at onErrorNT (internal/child_process.js:421:16)
dbug AppiumDoctor     at process.internalTickCallback (internal/process/next_tick.js:72:19)
info AppiumDoctor  ✔ ANDROID_HOME is set to: D:\Android\Sdk
info AppiumDoctor  ✔ JAVA_HOME is set to: C:\Program Files\Java\jdk1.8.0_191
info AppiumDoctor  ✔ adb exists at: D:\Android\Sdk\platform-tools\adb.exe
info AppiumDoctor  ✔ android exists at: D:\Android\Sdk\tools\android.bat
info AppiumDoctor  ✔ emulator exists at: D:\Android\Sdk\tools\emulator.exe
info AppiumDoctor  ✔ Bin directory of %JAVA_HOME% is set
info AppiumDoctor ### Diagnostic for necessary dependencies completed, no fix needed. ###
info AppiumDoctor
info AppiumDoctor ### Diagnostic for optional dependencies starting ###
dbug AppiumDoctor Error: Command 'npm' not found. Is it installed?
dbug AppiumDoctor     at ChildProcess.proc.on.err (C:\Users\Administrator\AppData\Roaming\npm\node_modules\appium-doctor\node_modules\teen_process\lib\exec.js:39:14)
dbug AppiumDoctor     at ChildProcess.emit (events.js:182:13)
dbug AppiumDoctor     at Process.ChildProcess._handle.onexit (internal/child_process.js:252:12)
dbug AppiumDoctor     at onErrorNT (internal/child_process.js:421:16)
dbug AppiumDoctor     at process.internalTickCallback (internal/process/next_tick.js:72:19)
WARN AppiumDoctor  ✖ opencv4nodejs cannot be found.
info AppiumDoctor ### Diagnostic for optional dependencies completed, one fix needed. ###
info AppiumDoctor
info AppiumDoctor ### Optional Manual Fixes ###
info AppiumDoctor The configuration can install optionally. Please do the following manually:
WARN AppiumDoctor  ➜ Why opencv4nodejs is needed and how to install it is: https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/image-comparison.md
info AppiumDoctor
info AppiumDoctor ###
info AppiumDoctor
info AppiumDoctor Bye! Run appium-doctor again when all manual fixes have been applied!
info AppiumDoctor

**Comment by mykola-mokhnach** [comment]
@KazuCocoa FYI

**Comment by KazuCocoa** [comment]
@ThinkDone 
Could you try out below branch?
https://github.com/KazuCocoa/appium-doctor/tree/get-execute-path-to-npm


1. `git clone` && `cd appium-doctor`
2. `npm install`
3. `./appium-doctor.js`

I appreciate if you can try out

**Comment by ThinkDone** [comment]
@KazuCocoa, it works.

**Comment by KazuCocoa** [comment]
Thanks so much! I'll wrap it up and release soon.
