### ISSUE TITLE
Driver.Manage().Window.Size doesn't change when rotating device on iOS

### ISSUE THREAD

**Issue by bart-tricentis** [appium/appium#12042]
## The problem

When calling Driver.Manage().Window.Size before and after a screen rotation returns the same value. The same issue like https://github.com/appium/appium/issues/11656 but this time it's on iOS

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10
* Desktop OS/version used to run Appium: Mac
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Both
* Appium CLI or Appium.app|exe: Appium CLI

**Comment by mykola-mokhnach** [comment]
Thanks for the report. The fix will be merged soon

**Comment by mykola-mokhnach** [comment]
The fix has been published
