### ISSUE TITLE
Getting black screen in Appium Desktop

### ISSUE THREAD

**Issue by tmdtest1234** [appium/appium#12046]
I am testing Direct TV now in my Android TV using Appium. I have connected the TV with ADB using wifi. I am able to see the HomeScreen and all the UI elements of the Android TV but I am seeing blank screen when I switch to Direct TV UI on the TV. Below is the verions of the Appium and Java I am using:
Appium - Appium Desktop v 1.6.3(Attaching snapshot)
Java - v 1.8

Able to connect to Adnroid TV from CMD using below command:
adb connect ip
(wher ip is the IP address of TV over same WiFi)

I am using below desired capabilities in the appium desktop 
{
  "deviceName": "ATV",
  "appPackage": "com.sony.dtv.sonyselect",
  "appActivity": ".activities.LaunchActivity",
  "platformName": "android",
  "autoGrantPermissions": "true"
}
and when click on Start session, I am able to see all the Sony TV UI in Appium Desktop but not the Direct TV UI. It gives me a blank screen on the Appium Desktop. 

On click Start session in APpium Desktop, Appium should show the Direct TV UI in the appium desktop to scan all the elements.
![appium server version](https://user-images.githubusercontent.com/43761728/51504424-c68d6a80-1d95-11e9-975c-2924d2375f15.PNG)
![direct tv ui 1](https://user-images.githubusercontent.com/43761728/51504425-c7260100-1d95-11e9-8cee-74955c790251.jpg)
![home1](https://user-images.githubusercontent.com/43761728/51504426-c7260100-1d95-11e9-90a2-8df41d92367e.png)

**Comment by tmdtest1234** [comment]
I have tried accessing the TV UI with the the below command:
adb shell screencap -p /sdcard/SonyTVHomeScreen.png
It is able to take screenshot for Sony TV Home but when switched to Direct TV UI, it is giving same black screen shot. Image Attached below
Attaching Appium server logs
[appium-server-logs.txt](https://github.com/appium/appium/files/2780901/appium-server-logs.txt)
![dtvhome_blackscreenerror](https://user-images.githubusercontent.com/43761728/51505566-225af200-1d9c-11e9-9d3f-96ae3e3ff27e.png)

**Comment by mykola-mokhnach** [comment]
It might be this screen is not accessible. Then there is no way to automate it using UIA framework.

**Comment by KazuCocoa** [comment]
> [debug] [35m[ADB][39m Device API level: 24
> [warn] [35m[AndroidDriver][39m Consider setting 'automationName' capability to 'uiautomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.

You can try uiautomator2 as automationName capability.

mm, you were able to get page source, but could not screen, according to your log.

I am wondering if the TV has some limitations for developers. What about taking screenshots via UIAutomator2 or espresso driver?

anyway, maybe we cannot help since it is the TV provider's limitation.
(e.g. they would like to protect them from screen capture apps)

**Comment by AycanY** [comment]
how to connect directly from Appium without cabel on Wlan with the ip address ?
