### ISSUE TITLE
Scroll crash

### ISSUE THREAD

**Issue by Gilad-WT** [appium/appium#12043]
## The problem

Trying to scroll will cause an unknown error 
## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0
* Desktop OS/version used to run Appium: Windows 10
* Mobile platform/version under test: Android 8.0
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Appium desktop

## Appium logs

[HTTP] --> POST /wd/hub/session/08cfa81c-a953-47bb-955b-45c99e0cd43d/touch/scroll
[HTTP] {"xoffset":0,"yoffset":50}
[W3C (08cfa81c)] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [POST /wd/hub/session/08cfa81c-a953-47bb-955b-45c99e0cd43d/touch/scroll] to [POST http://localhost:8200/wd/hub/session/7f577eda-38de-4a13-82e0-3ac1d48ec75f/touch/scroll] with body: {"xoffset":0,"yoffset":50}
[JSONWP Proxy] Got an unexpected response: {"sessionId":"7f577eda-38de-4a13-82e0-3ac1d48ec75f","status":13,"value":"com.jayway.jsonpath.InvalidPathException: invalid path\n\tat com.jayway.jsonpath.internal.filter.FieldFilter.filter(FieldFilter.java:59)\n\tat com.jayway.jsonpath.JsonPath.read(JsonPath.java:191)\n\tat com.jayway.jsonpath.Js...
[W3C (08cfa81c)] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: 500 - {"sessionId":"7f577eda-38de-4a13-82e0-3ac1d48ec75f","status":13,"value":"com.jayway.jsonpath.InvalidPathException: invalid path\n\tat com.jayway.jsonpath.internal.filter.FieldFilter.filter(FieldFilter.java:59)\n\tat com.jayway.jsonpath.JsonPath.read(JsonPath.java:191)\n\tat com.jayway.jsonpath.JsonPath.read(JsonPath.java:211)\n\tat io.appium.uiautomator2.handler.ScrollTo.safeHandle(ScrollTo.java:32)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:37)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:250)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:241)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)\n\tat io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)\n\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)\n\tat io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)\n\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:552)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)\n\tat io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)\n\tat java.lang.Thread.run(Thread.java:764)\n"}
[W3C (08cfa81c)]     at JWProxy.proxy (C:\Users\gilad\AppData\Local\Programs\Appium\resources\app\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:180:13)
[MJSONWP] Matched JSONWP error code 13 to UnknownError
[HTTP] <-- POST /wd/hub/session/08cfa81c-a953-47bb-955b-45c99e0cd43d/touch/scroll 500 46 ms - 7391

**Comment by mykola-mokhnach** [comment]
I assume this endpoint expects different args by looking at its implementation:
https://github.com/appium/appium-uiautomator2-server/blob/20de6220d4d9b888892b8e148a1e16b6aa8b874d/app/src/main/java/io/appium/uiautomator2/handler/ScrollTo.java#L31

The json body there is expected to be a valid [JsonPath](https://github.com/json-path/JsonPath) expression.

Which client library was used to call that?

**Comment by Gilad-WT** [comment]
@mykola-mokhnach Webdriverio

**Comment by mykola-mokhnach** [comment]
I would say this endpoint should not be used anymore and should be replaced by touch actions. java-client, for example, did deprecate it a while ago. @christian-bromann Any thoughts on this?

**Comment by christian-bromann** [comment]
I don't know in which environments this command is still supported but apparently not in the one @Gilad-WT ran his test with. I also recommend to switch to the actions command.

**Comment by Gilad-WT** [comment]
@christian-bromann @mykola-mokhnach 
I tried using touch actions but they don't do anything.
this code:
```
await b.touchAction([
        { action: 'press', x: 540, y: 960 },
        { action: 'moveTo', x: 540, y: 480 },
        'release'])
```
does nothing.  I turned on pointer location so I can see that there is pointer movement but nothing happens (not scrolling).

Any ideas?

**Comment by mykola-mokhnach** [comment]
Feel free to use Appium for for questions. This is the place for issues

**Comment by Gilad-WT** [comment]
@mykola-mokhnach Thanks. I found a solution in the forums. I had to add a wait between the click and the move  
  ```
await b.touchAction([
        { action: 'press', x: 540, y: 960 },
        { action: 'wait', ms: 500},
        { action: 'moveTo', x: 540, y: 480 },
        'release'])
```

**Comment by PHUITesting** [comment]
Seeing this issue using the same function that is still posted in the docs here for webdriverio:

http://appium.io/docs/en/commands/interactions/touch/scroll/

**Comment by Nisthar** [comment]
@Gilad-Shnoor Can you give me a solution for wd? does it work for wd?
