### ISSUE TITLE
Clear Text is not working in appium Android and iOS

### ISSUE THREAD

**Issue by aryalakshmi** [appium/appium#12044]
## The problem

Clear text is not working in Android and IOS with appium version 1.10.0
## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0
* Last Appium version that did not exhibit the issue (if applicable): 1.8
* Desktop OS/version used to run Appium: MACBOOK (High Sierra)  / Windows 7
* Node.js version (unless using Appium.app|exe): npm 6.1.0
* Mobile platform/version under test: iphone 5s 12.1 / Android Oneplus 5 (8.1.0)
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: appium cli in MAC / appium GUI in windows

## Link to Appium logs

https://gist.github.com/aryalakshmi/d09416ed3bc5ec502d6d7bb3e2fb7910

## Code To Reproduce Issue [ Good To Have ]

AppiumLibrary.ClearText ion-input[type=text] > input.text-input.text-input-ios

**Comment by mykola-mokhnach** [comment]
It might be that the application under test defines custom handlers for fields cleanup. I would verify the events called on manual field cleanup and then compare them with ones generated during the automated test. Read https://appiumpro.com/editions/36 for more details on this topic. Unfortunately, there is nothing we can do on Appium side about it.
