### ISSUE TITLE
Session is not getting created while trying to find element using image strategy using  driver.findElementByImage()

### ISSUE THREAD

**Issue by stephenws** [appium/appium#12055]
Appium session is not getting created while trying to find element using image strategy using  driver.findElementByImage()

## Environment
* Desktop OS/version used to run Appium: MacOS 10.13.6 
* Node.js version : 8.9.1
* java-client version:  7.0.0
*selenium version: 3.141.59
* Appium CLI : 1.8.0

## Details
Trying to find element using image locator strategy (driver.findElementByImage()), but appium session is not getting created

**Comment by stephenws** [comment]
@mykola-mokhnach , updated the appium to 1.10.0 still facing the same issue.
No server logs, as session itself is not getting created

**Comment by mykola-mokhnach** [comment]
Sorry, but without server logs we cannot help nothing
