### ISSUE TITLE
Element send keys command expects list of chars but protocol expects a string

### ISSUE THREAD

**Issue by christian-bromann** [appium/appium#12059]
## The problem

There seems to be issues with the element send keys command as described in [this WebdriverIO] thread. It seem to work fine when sending a value property in form of `[ "f", "o", "o" ]` but not in form of `"foo"`. This is against the [WebDriver spec](https://www.w3.org/TR/webdriver1/#element-send-keys) which is expecting a string (also see [here](https://github.com/jlipps/simple-wd-spec#element-send-keys)).

## Environment

* Appium version (or git revision) that exhibits the issue: latest
* Last Appium version that did not exhibit the issue (if applicable): unknown
* Desktop OS/version used to run Appium: all
* Node.js version (unless using Appium.app|exe): all
* Mobile platform/version under test: not sure if relevant
* Real device or emulator/simulator: not sure if relevant
* Appium CLI or Appium.app|exe: not sure if relevant

## Details

See discussion in https://github.com/webdriverio/webdriverio/pull/3347#discussion_r248397613

**Comment by KazuCocoa** [comment]
Is this Chrome driver's one?

```
[Chromedriver] [STDERR] [1547747679.557][DEBUG]: DEVTOOLS RESPONSE Runtime.evaluate (id=38) {
[Chromedriver] [STDERR]    "result": {
[Chromedriver] [STDERR]       "description": "1",
[Chromedriver] [STDERR]       "type": "number",
[Chromedriver] [STDERR]       "value": 1
[Chromedriver] [STDERR]    }
[Chromedriver] [STDERR] }
[Chromedriver] [STDERR] [1547747679.557][INFO]: Done waiting for pending navigations. Status: ok
[Chromedriver] [STDERR] [1547747679.557][INFO]: RESPONSE TypeElement unknown error: 'value' must be a list
[Chromedriver] [STDERR]   (Session info: chrome=71.0.3578.99)
[JSONWP Proxy] Got response with status 200: {"sessionId":"18ab5510595cb190e27d7247699a92f9","status":13,"value":{"message":"unknown error: 'value' must be a list\n  (Session info: chrome=71.0.3578.99)\n  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.16299 x86_64)"}}
[W3C] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: The request to /wd/hub/session/df83aea9-757e-466b-8a1b-962065cc8054/element/0.733588335143198-1/value has failed
[W3C]     at JWProxy.proxy$ (C:\Users\nvarthakavi\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:182:13)
[W3C]     at tryCatch (C:\Users\nvarthakavi\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\nvarthakavi\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\nvarthakavi\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[W3C]     at GeneratorFunctionPrototype.invoke (C:\Users\nvarthakavi\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[W3C]     at 
[MJSONWP] Matched JSONWP error code 13 to UnknownError
```

I thought Appium accept both of format, list and string as `value` and `text` https://github.com/appium/appium-base-driver/blob/master/lib/protocol/routes.js#L180

What version of chrome drive he used? 

> ChromeDriver 2.44
> Fixed Element Send Keys should get "text" property in W3C mode

http://chromedriver.chromium.org/downloads

**Comment by christian-bromann** [comment]
@KazuCocoa you are absolutely right. Thank you for pointing this out.
