### ISSUE TITLE
App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name

### ISSUE THREAD

**Issue by LayMuiToh** [appium/appium#12050]
## The problem

To run automation on iOS Simulator

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 10.13.6
* Node.js version (unless using Appium.app|exe):9.1.0
* Mobile platform/version under test:iOS 12.1
* Real device or emulator/simulator:iOS Simulator
* Appium CLI or Appium.app|exe:appium CLI

## Details

My desired capabilities:
 browserName: '',
        appiumVersion: '1.9.1',
        platformVersion: '12.1',
        platformName: 'iOS',
        deviceName: 'iPhone Simulator',
        udid: '1E7A368D-56EB-448C-850C-EEA19CDC3516',
        app: '/Users/tohlaymui/Desktop/performance_analyst_test/performance_analyst-dev.app',
        bundleId: 'ai.xxx.performanceanalyst-dev',
        automationName: 'XCUITests',
        noReset: false,
        usePrebuiltWDA: true,
        autoLaunch: true,
        newCommandTimeout: 7000,
        printPageSourceOnFindFailure: true

## Link to Appium logs

https://gist.github.com/LayMuiToh/3d80de6e53579b534ea11603d89fed39

## Code To Reproduce Issue [ Good To Have ]

Run appium &
run the test spec
node_modules/.bin/wdio wdio.conf.js --spec ./test/spec/app.ts.noattr.text.cust.spec.js

**Comment by mykola-mokhnach** [comment]
Does the app exist at that path and is accessible?
