### ISSUE TITLE
Error: Process didn't end after 10000ms

### ISSUE THREAD

**Issue by DivyaLNarayan** [appium/appium#12054]
## The problem

Please find the appium logs in the gist below, While im trying to launch the Safari browser i get the error

## Environment

* Appium version - 1.6.2
* Desktop OS/version used to run Appium: mac OS high sierra 10.13.4
* Node.js version: 11.6.0
* Mobile platform: ios 11.2.5
* Real device -  iphone 8
* Appium CLI or Appium.app|exe:

## Link to Appium logs

https://gist.github.com/DivyaLNarayan/d966285903693f2a7317c5b43173fbe6

**Comment by mykola-mokhnach** [comment]
> [XCUITest] Error starting iproxy: 'Command 'iproxy' not found. Is it installed?'

The necessary prerequisites are not installed on the system. iproxy itself is a part of libusbmuxd

**Comment by DivyaLNarayan** [comment]
I have indstalled iproxy, carthage and libimobiledevice

**Comment by deolas** [comment]
I solved this problem by running "brew doctor". This gave me list of issues with my brew and asked me to link "usbmuxd".
