### ISSUE TITLE
Not able to set fps for iOS video recording

### ISSUE THREAD

**Issue by kolyakrasnik** [appium/appium#12067]
## The problem

Not able to change fps value during screen recording.

## Environment

appium : 1.10.1
appium client : java appium client 7.0.0
mobile platform : iOS

## Details

It seems like this parameter was removed, so we are not able to change this value from default (default = 25) (removed line: '-r', this.opts.videoFps,)
https://github.com/appium/appium-xcuitest-driver/commit/3a85140ac710604e89932b01ac3619e4825e00c1#diff-0b1b540a11a3485a5dcec9e05ed6f405

## Link to Appium logs

https://gist.github.com/kolyakrasnik/639227e2bc4d785ea1327296779dadab

## Code To Reproduce Issue [ Good To Have ]

https://gist.github.com/kolyakrasnik/927fb8e827a030a395707a926364b8a1

**Comment by mykola-mokhnach** [comment]
The default MJPEG codec works nicely without this option - it simply autodetects the FPS based on the incoming stream performance. Does such approach fail for x264?

**Comment by kolyakrasnik** [comment]
Appium uses mp4 container for the video recording. Standart codec for this container is H.264. So, the main part of mp4 players are not able to play the video with MJPEG codec (including chrome browser, it expects H264 as well).  
Also codec MJPEG has a very big video size compairing with H264 (3 mins video --> about 1Mb (H264) vs 20Mb (MJPEG)). 
So, our choise is H264 codec.
If we don't use '-r' option we get default fps = 25 and for some reasons I see increased speed of the video. To get real time video we need '-r = 10'.  
I hardcoded this parameter currently in appium sources locally and I see real speed video with high quality for iOS real devices.

**Comment by mykola-mokhnach** [comment]
you could create a PR and add that option if the output codec is NOT set to MJPEG. We'll need to mention that in the documentation about it won't be possible to change the FPS dynamically via settings as soon as video recording has been started.

**Comment by mykola-mokhnach** [comment]
Closed as fixed
