### ISSUE TITLE
How can I set remote path in IOS using startRecordingScreen()

### ISSUE THREAD

**Issue by NavdeepSingh09** [appium/appium#12069]
## How can I set remote path in IOS using startRecordingScreen()

I tried with different ways to record screen on iOS simulator, it's recorded to default path but not recorded on remote path. Can any one explain the exact syntax to record screen. 

## Environment

Appium -Version 1.8.1
iOS Simulator v11.4
Appium app.
MAC

## Details
            driver.startRecordingScreen(new IOSStartScreenRecordingOptions().withUploadOptions(ScreenRecordingUploadOptions.uploadOptions().withRemotePath("**PATH**")));

|
|
TEST
|
|
driver.stopRecordingScreen();

## Link to Appium logs

[info] [HTTP] [info] [HTTP] --> POST /wd/hub/session/e7f5e4a9-686b-4cdb-a81b-e0b209b5b4c5/appium/start_recording_screen
[info] [HTTP] {"options":{"remotePath":"**PATH**"}}
[debug] [W3C] Calling AppiumDriver.startRecordingScreen() with args: [{"remotePath":"**PATH"**},"e7f5e4a9-686b-4cdb-a81b-e0b209b5b4c5"]
[debug] [XCUITest] Executing command 'startRecordingScreen'
[info] [XCUITest] Checking if there is/was a previous screen recording. Set 'forceRestart' option to 'true' if you'd like to skip this step.
[debug] [XCUITest] 'pgrep -nif simctl io 494FD0CC-E83A-47C5-AEF9-066B936345E3 recordVideo' didn't detect any matching processes. Return code: 1
[info] [XCUITest] Screen recording is not running. There is nothing to stop.
[debug] [XCUITest] 'pgrep -nif simctl io 494FD0CC-E83A-47C5-AEF9-066B936345E3 recordVideo' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] Beginning screen recording with command: 'xcrun simctl io 494FD0CC-E83A-47C5-AEF9-066B936345E3 recordVideo /var/folders/m1/3m2z0jb93fxfj4x89dr0jclm0000gr/T/2019024-83354-1p8p037.cy4z/appium_196d1f.mp4'Will timeout in 180 s
[debug] [MJSONWP] Responding to client with driver.startRecordingScreen() result: ""
[info] [HTTP] <-- POST /wd/hub/session/e7f5e4a9-686b-4cdb-a81b-e0b209b5b4c5/appium/start_recording_screen 200 80 ms - 74
[info] [HTTP] 
[info] [HTTP] --> POST /wd/hub/session/e7f5e4a9-686b-4cdb-a81b-e0b209b5b4c5/elements
[info] [HTTP] {"using":"id","value":"Allow"}

**Comment by mykola-mokhnach** [comment]
Video recording didn't work properly until the recent Appium versions. Upgrade your server to 1.10

**Comment by NavdeepSingh09** [comment]
I tried with Appium v-Version 1.10.0 (1.10.0.20181230.2). 

Java code:

driver.startRecordingScreen(new IOSStartScreenRecordingOptions().withUploadOptions(uploadOptions().withRemotePath("PATH")));
            objLaunchRegistration.Launch_class();
            driver.stopRecordingScreen();
Video not even saved in default path.

**Appium Server logs:**
**Screenshot start logs:**
[info] [35m[ffmpeg][39m [info] [35m[XCUITest][39m Starting screen capture on the device '494FD0CC-E83A-47C5-AEF9-066B936345E3' with command: 'ffmpeg -f mjpeg -i http://localhost:9100 -vcodec mjpeg -y /var/folders/m1/3m2z0jb93fxfj4x89dr0jclm0000gr/T/2019025-81984-1bj9wav.7d4v/appium_82f0be.mp4'. Will timeout in 180000ms
[debug] [35m[W3C (57737086)][39m Responding to client with driver.startRecordingScreen() result: ""
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session/57737086-8dec-441b-a0ae-132cb8886e5d/appium/start_recording_screen [39m[32m200[39m [90m5028 ms - 12[39m
[info] [35m[HTTP][39m [90m[39m
[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/57737086-8dec-441b-a0ae-132cb8886e5d/elements[39m



**Screenshot end recording:**
[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/57737086-8dec-441b-a0ae-132cb8886e5d/appium/stop_recording_screen[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[W3C (57737086)][39m Calling AppiumDriver.stopRecordingScreen() with args: [null,"57737086-8dec-441b-a0ae-132cb8886e5d"]
[debug] [35m[XCUITest][39m Executing command 'stopRecordingScreen'[info] [35m[ffmpeg][39m Exiting normally, received signal 2.
[info] [35m[ffmpeg][39m 
[debug] [35m[XCUITest][39m The size of the file is 8.62 MB
[debug] [35m[W3C (57737086)][39m Responding to client with driver.stopRecordingScreen() result: "AAAAHGZ0eXBpc29tAAACAGlzb21pc28ybXA0MQAAAAhmcmVlAInga21kYXT/2P/gABBKRklGAAECAADYANgAAP/+ABBMYXZjNTguMzUuMTAwAP/bAEMACA4OEA4QExMTExMTFhUWFxcXFhYWFhcXFxkZGR0dHRkZGRcXGRkcHB0dICEgHh4dHiEhIyMjKiooKDExMjw8SP/EALYAAQEAAwEBAQEAAAAAAAAAAAACBQMEBgcBCAEBAQADAQEBAQAAAAAAAAAAAAIFAwQGBwEIEAEAAgIABAMFBAcFBQQHBwUAAQIDETESBCFBBSJRMlJCE3KSFGKTcWFTglQ0BiMVsqJz0zOBwhZDNdLjs/JV8CSDlOKxwXTRY6HDJaM2EQEBAAIBAwQBAwQCAgICAgMAAgMSBDITIkIzBVIjUxRDFWMBYnNyJDSDEaMGMSFUk/D/wAARCAigBNoDASIAAhEAAxEA/9oADAMBAAIRAxEAPwD30QaUbng+KvUG54L2gBtb5yRy8sVapjxjg1LmqxJ1dFJMkRxji2YprHNNvh9KdTdt/jR6miODVMbbUy5G1EQ2zEa3CBYnW5TrUqbbx7sx4rmfFDQ6ceo7z6mqlJvOnVOscujFPqK+rVPAwRM3rpeXt2/Krpvfq6Yn/wAmJTXSrqaavv2mCk3nUW5XVkj61tVjvzMdeLY+zdnmZ5Pd0/GienUy0rjm3LbmasU8ltteXPTFSv1L1pHxWvyOHF5l0XN26rprT/taf7xx9WTfHCvT5M5klx+Dqm9b13Hqifmq5XPfU2SlsSuWlTVLVMOkiI4rkTFNRzSmbzknckzMtTbV+mU6uqf7qa7r8rl5Oe2pPVede87qRTHXm8XTM7V4+2ivFOWJpxrXu0UiJjSsuSck7c0Iup7vi/JnxbIjduWteaXNO6T+2G/cxO4aO8z3RtOozGLPa7PY8kTHvPIUi3y+lkcc2xR3Zrj8yprycl4nqIVrs4cWSMkbh3PXRU1OzHVLRMS4b0jxZXwc0w48...

**Comment by mykola-mokhnach** [comment]
Did you read the method documentation? 

> public abstract class BaseStartScreenRecordingOptions<T extends BaseStartScreenRecordingOptions<T>>
>         extends BaseScreenRecordingOptions<BaseStartScreenRecordingOptions<T>> {
>     private Boolean forceRestart;
>     private Duration timeLimit;
> 
>     /**
>      * The remotePath upload option is the path to the remote location,
>      * where the resulting video should be uploaded.
>      * The following protocols are supported: http/https (multipart), ftp.
>      * Missing value (the default setting) means the content of the resulting
>      * file should be encoded as Base64 and passed as the endpoint response value, but
>      * an exception will be thrown if the generated media file is too big to
>      * fit into the available process memory.


**>      * This option only has an effect if there is a screen recording session in progress
**>      * and forced restart is not enabled (the default setting).**


>      *
>      * @param uploadOptions see the documentation on {@link ScreenRecordingUploadOptions}
>      *                      for more details.
>      * @return self instance for chaining.
>      */
>     @Override
>     public T withUploadOptions(ScreenRecordingUploadOptions uploadOptions) {
>         //noinspection unchecked
>         return (T) super.withUploadOptions(uploadOptions);
>     }

**Comment by mykola-mokhnach** [comment]
Feel free to use Appium forum to ask howto question. Closed as not an issue.
