### ISSUE TITLE
Please help with instagram app. 

### ISSUE THREAD

**Issue by Abhijith1190** [appium/appium#12068]
Hi there, 
I'm trying to automate the Instagram app. but I get this error. 

**An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.instagram.android' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: The permission to start 'com.instagram.nux.activity.SignedOutFragmentActivity' activity has been denied.Make sure the activity/package names are correct.**

* Appium desktop version (or git revision) that exhibits the issue: 1.10.0

This is my code
{
  "platformName": "Android",
  "deviceName": "AndroidPhone",
  "automationName": "uiautomator2",
  "app": "D:\\Task\\Instagram_v76.0.0.15.395.apk",
  "appPackage": "com.instagram.android",
  "appWaitActivity": "com.instagram.nux.activity.SignedOutFragmentActivity",
  "appActivity": "com.instagram.nux.activity.SignedOutFragmentActivity",
  "noReset": true
}

and mCurrentfocus
**mCurrentFocus=Window{227b073b u0 com.instagram.android/com.instagram.nux.activity.SignedOutFragmentActivity}**

can anyone help me here?

**Comment by karan97saxena** [comment]
@Abhijith1190 : did you find a fix for this?

**Comment by Abhijith1190** [comment]
@karan97saxena yes I did.
