### ISSUE TITLE
Failed to launch com.apple.mobilesafari application on iPhone7Plus (12.1)

### ISSUE THREAD

**Issue by NJewootah** [appium/appium#12062]
## The problem
WebDriverAgent fails to launch com.apple.mobilesafari, I've highlighted the main error but there are more details included in the logs in the Gist file.
```
[debug] [WD Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.apple.mobilesafari","arguments":["-u","http://appium.io"],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[Xcode]     t =     0.91s Open com.apple.mobilesafari
[Xcode]
[Xcode]     t =     0.92s     Launch com.apple.mobilesafari
[Xcode]
[Xcode] 2019-01-03 19:24:20.133068+0000 WebDriverAgentRunner-Runner[981:136736] Enqueue Failure: Failed to launch com.apple.mobilesafari: The operation couldn’t be completed. Application "com.apple.mobilesafari" is installing or uninstalling, and cannot be launched. /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode]
[Xcode] 2019-01-03 19:25:20.153958+0000 WebDriverAgentRunner-Runner[981:136736] Enqueue Failure: Application 'com.apple.mobilesafari' does not have a process ID /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
```

The WebDriverAgent is launching as expected and when I manually open Safari on my device, my scenario runs successfully. Would you be able to investigate please? I've included all the environment, configuration and log details below.

**Starting the appium server**
`appium -U {device_udid} -p4723 --webkit-debug-proxy-port 27753`

**Starting the debugger**
`ios_webkit_debug_proxy -c {device_udid}:27753 -d`

## Environment
* Appium version (or git revision) that exhibits the issue: 1.10.0
* Desktop OS/version used to run Appium: MacOS High Sierra 10.13.6
* Node.js version (unless using Appium.app|exe): 11.6.0
* Mobile platform/version under test: 12.1
* Real device or emulator/simulator: Real device (iPhone7Plus)

## The Appium Server Logs in Gist
https://gist.github.com/NJewootah/dd215e2979d7328c9ea8fe109dd47e4b

## The Desired Capabilities
```
capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 7 PLus");
capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "Safari");
capabilities.setCapability(MobileCapabilityType.UDID, deviceName);
capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");
capabilities.setCapability("showXcodeLog", true);
capabilities.setCapability("startIWDP", true);
capabilities.setCapability("xcodeOrgId", "3******Y7");
capabilities.setCapability("xcodeSigningId", "iPhone Developer");
capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "12.1");
```

**Comment by mykola-mokhnach** [comment]
You just have to set `browser` capability to safari instead of providing the `bundleId` if you want to test a web application

**Comment by mykola-mokhnach** [comment]
I'm afraid this is a [XCTest bug](https://stackoverflow.com/questions/41872848/xctests-failing-to-launch-app-in-simulator-intermittently)

Try to restart the device and see if that helps

**Comment by NJewootah** [comment]
Restarting the device fixed this issue 👍 
Thanks Mykola
