### ISSUE TITLE
start_recording_screen command not work on iOS10.3.3 when use xcuitest-driver

### ISSUE THREAD

**Issue by tangzhengqian** [appium/appium#12060]
## The problem

hello, I have a problem, when use **xcuitest-driver** to test iphone which is **IOS10.3.3**, the **start_recording_screen** command not work. and I see the log from WDA is this:
`2019-01-23 10:33:14.853636+0800 WebDriverAgentRunner-Runner[254:5906] MJPEG server cannot start because the current iOS version is not supported`
What is the reason?  Thanks!

## Environment

* Appium version : 1.10
* Desktop OS/version used to run Appium: maOS 10.14.2
* Node.js version (unless using Appium.app|exe): Appium.app
* Mobile platform/version under test:  iOS10.3.3
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:  Appium.app

**Comment by mykola-mokhnach** [comment]
The reason this that IOS 10 SDK is unable to provide screenshots in acceptable format, so one can create an MJPEG video stream based on it. This feature has only been introduced with Xcode9/iOS 11.
