### ISSUE TITLE
Appium Inspector can’t find element with `position: absolute`

### ISSUE THREAD

**Issue by TesterAllmax** [appium/appium#12064]
## The problem

There’s a `header` in the app, that contains `button back`. Header has prop `headerTransparent: true`, which applies `position: absolute` to header. When `headerTransparent: true`, Appium Inspector can’t find `button back` inside `header`. When `headerTransparent: false`, Appium Inspector is able to find `header` and `button back` in it.

## Environment

* **Appium version** (or git revision) that exhibits the issue: **1.10.0**
* **Desktop OS/version** used to run Appium: **macOS High Sierra v: 10.13.6**
* **Node.js version** (unless using Appium.app|exe): **10.15.0**
* **Mobile platform/version** under test: **iOS 12.1.2**
* **Real device** or emulator/simulator: **real device**

## Code To Reproduce Issue [ Good To Have ]
Sample component code:
`export const CloseButton = ({ onPress, testID }: { onPress: () => void, testID: string }) => (
  <TouchableOpacity style={styles.wrapper} onPress={onPress} testID={testID}>
    <Image source={images.closeButton} />
  </TouchableOpacity>
);`

Sample screen code:
`class UnconnectedLoginScreen extends PureComponent<Props, State> {
  static navigationOptions: (nav: Props) => StackNavigationOptions = ({ navigation }) => ({
    headerTransparent: true,
    headerStyle: { borderBottomWidth: 0 },
    headerRight: <CloseButton onPress={() => navigation.goBack()} testID="button Close" />,
    headerLeft: null,
  });`

**Comment by mykola-mokhnach** [comment]
Please report the issue to React. Appium (actually, not Appium, but XCTest) just uses what the app provides to the accessibility layer.

Closed as not an issue

**Comment by TesterAllmax** [comment]
12

**Comment by jonasrk** [comment]
@TesterAllmax Did you manage to resolve this?
