### ISSUE TITLE
start_recording_screen rest problem

### ISSUE THREAD

**Issue by yusufunlumbvn** [appium/appium#12073]
## The problem
By using appium source code I do some... Version is almost last : 14010b25243a70dafa46b06d1f53e069cc5b47e4
I am trying to make [start_recording_screen](http://appium.io/docs/en/commands/device/recording-screen/start-recording-screen/#appium-server) worked. While I am sending the request from postman response doesn't response immediate. After waiting a bit  it give me error `at IncomingMessage.onAborted (/Users/yusufu/Documents/Projects/appium/node_modules/raw-body/index.js:231:10)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at abortIncoming (_http_server.js:412:9)
    at socketOnClose (_http_server.js:406:3)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at TCP._handle.close [as _onclose] (net.js:554:12)`
************************************************************************
My post query is below : 
http://localhost:4723/wd/hub/session/61221d32-d743-41d7-a9c5-8b8925ecfe3b/start_recording_screen
Body : {"remotePath":"video2.mp4","username":"yusuf", "timeLimit":"5"}

Headers: Host: localhost:4723
Connection: keep-alive
Content-Length: 64
Accept: application/json
Origin: http://localhost:3000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
Content-Type: application/json; charset=UTF-8
Referer: http://localhost:3000/device
Accept-Encoding: gzip, deflate, br
Accept-Language: tr-TR,tr;q=0.9,en-US;q=0.8,en;q=0.7
************************************************************************
I have tried ftp address, username and password also. Didn't work.
I have implemented so many different commands , they work like charm. execute command with followed body {"script":"mobile: shell","args":{"command":"input text trying"}}
Can I give my computer folder path ? which appium works on also. 

## Environment

* Appium git version:14010b25243a70dafa46b06d1f53e069cc5b47e4
* Desktop OS/version used to run Appium: Mac OS High Siearra / 10.13.6
* Node.js version : v8.9.0
* NPM version: 5.5.1
* "appium-android-driver": "^4.0.0" which I haven't changed
* Mobile platform/version under test: Samsung Note 8
* --allow-cors and --relaxed-security enabled on source code: https://gist.github.com/yusufunlumbvn/779c04500ebda36b2295c91f08d40b33

**Comment by KazuCocoa** [comment]
What about wrapping them with `options`?
https://github.com/appium/appium-base-driver/blob/master/lib/protocol/routes.js#L362

e.g.
`{"options": {"remotePath":"video2.mp4","username":"yusuf", "timeLimit":"5"}}`

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium-base-driver/blob/c6a14732b8d896321951515841106e16c285fc43/lib/protocol/routes.js#L362

**Comment by yusufunlumbvn** [comment]
Thanks you. @KazuCocoa  it worked with handling remotepath and timelimit. I am trying to get record stream . Followed log mean continues record ?
[debug] [AndroidDriver] The overall screen recording duration is 180s so far
[debug] [AndroidDriver] There is no need to start the next recording chunk

**Comment by mykola-mokhnach** [comment]
Closed as not an issue. Please use Appium forum for questions

**Comment by KazuCocoa** [comment]
it means you do not need to re-sending start recording call to the server. The server handles it properly.

**Comment by yusufunlumbvn** [comment]
Thank you so much @KazuCocoa . It would be nice to share in a doc or readme some example requests about record screen or  etc... I would like to add my experience if I will be finished with it.
