### ISSUE TITLE
touchPerform actions processed separately: could not do swipe.

### ISSUE THREAD

**Issue by amokmen** [appium/appium#12076]
## The problem

**Basic test - trying to do swipe (from right to left) in Android app (React Native)**:
```javascript
const windowSize = await driver.getWindowSize();

const right2leftSwipeOptions = {
        startX: windowSize.width * 0.9,
        startY: windowSize.height / 2,
        endX: windowSize.width * 0.1,
        endY: windowSize.height / 2
      };

await driver.touchPerform([
        {
          action: "press",
          options: {
            x: right2leftSwipeOptions.startX,
            y: right2leftSwipeOptions.startY
          }
        },
        {
          action: "moveTo",
          options: {
            x: right2leftSwipeOptions.endX,
            y: right2leftSwipeOptions.endY
          }
        },
        { action: "release" }
      ]);
```
All is according to your docs: [sample for WebdriverIO](https://github.com/appium/appium/blob/master/docs/en/commands/interactions/touch/touch-perform.md).
Only 3 actions: **press**, **moveTo**, **release**.

So, nothing happens - no actual swiping!
See [gist#1](https://gist.github.com/amokmen/791fd6840576231747efdb740f4f5ef7) with Appium log.
In log we could see that every action processed separately!
But stop, description for _touchPerform_ clearly says that:
> 'Touch Perform' works similarly to the other singular touch interactions, except that this allows you to chain together more than one touch action as one command. This is useful because Appium commands are sent over the network and there's latency between commands. This latency can make certain touch interactions impossible because some interactions need to be performed in one sequence.

Okay, I spent 2 days to do something useful but not invented nothing more than almost randomly add 1 new action to my _touchPerform_ sequence - **wait**. Now my code looks like this:
```javascript
const windowSize = await driver.getWindowSize();

const right2leftSwipeOptions = {
        startX: windowSize.width * 0.9,
        startY: windowSize.height / 2,
        endX: windowSize.width * 0.1,
        endY: windowSize.height / 2,
        delay: 0
      };

await driver.touchPerform([
        {
          action: "press",
          options: {
            x: right2leftSwipeOptions.startX,
            y: right2leftSwipeOptions.startY
          }
        },
        { action: "wait", options: { mseconds: right2leftSwipeOptions.delay } },
        {
          action: "moveTo",
          options: {
            x: right2leftSwipeOptions.endX,
            y: right2leftSwipeOptions.endY
          }
        },
        { action: "release" }
      ]);
```
And now swipe is working!
Check [gist#2](https://gist.github.com/amokmen/a3aa488722d7841e61ed64b7a5493bd6) with Appium log.
Now Appium works with all actions in 1 sequence! As it should be!

So, there are my questions/remarks:
1. Why first code is not working as 1 sequence?
2. Why in your documentation not working example?
3. Why adding "wait" solved problem? Is it important where exactly put "wait" in sequence order?
4. Why delay is could be any number without any difference in result: 0, 100, 1000, 5000?
Actually there is no delay for 5 seconds - swipe would be done always with same time.
5. Why in gist#1 we could see that Appium "Shutting down because we waited 60 seconds for a command" almost immediately? And in gist#2 all is good: shutting down really comes after 60 seconds?

## Environment

* Appium version: **1.10.0**
* Desktop OS/version used to run Appium: **MAC OS X 10.10.5**
* Mobile platform/version under test: **Android**
* Real device or emulator/simulator: **Real device (Honor 8 Android 7 API 24)**
* Appium CLI or Appium.app|exe: **Appium.app**

## Link to Appium logs

1) [Appium log with Bad reaction to performTouch](https://gist.github.com/amokmen/791fd6840576231747efdb740f4f5ef7)
2) [Appium log with Good reaction to performTouch](https://gist.github.com/amokmen/a3aa488722d7841e61ed64b7a5493bd6)

**Comment by Jonahss** [comment]
Thank you for providing an in-depth explanation of the issue you encountered along with server logs.

When touch actions are sent to Appium, it looks at the actions and for some sets of actions, it uses different methods to automate the gesture. The one which affected you is here:
https://github.com/appium/appium-android-driver/blob/master/lib/commands/touch.js#L139

It's exactly what you experienced. When you have `touch, wait, moveTo, release`, Appium calls the Android [UiDevice.swipe](https://developer.android.com/reference/android/support/test/uiautomator/UiDevice#swipe) method. I think UiAutomator2 doesn't have methods for specific `touch`, `moveTo`, or `release`, so for the actions without the wait, it uses the old UiAutomator touch actions using the UiAutomatorBridge class. The newer swipe method is better supported, which is probably why it works.

It looks like the special case in this code was added 4 years ago. I think we could prevent future users from running into the same issue that you did by recognizing the `press, moveTo, release` commands with no wait, or any combination of waits, and send the `swipe` command.

@imurchie What do you think?


For the 60 second command timeout issue, a couple months ago I saw something similar where the timeout seemed to be counted wrong. @mykola-mokhnach have you noticed the 60 second new command timeout being counted wrong in some cases?

**Comment by mykola-mokhnach** [comment]
> have you noticed the 60 second new command timeout being counted wrong in some cases?

I didn't experienced anything like this myself. The only thing in Android I know about and which might create significant delays is the idle timer, when UIA framework awaits application UI to be in idle state in order to take accessibility hierarchy snapshot

**Comment by amokmen** [comment]
My app rather simple at this stage: SplashScreen for ~3 seconds after start and 3 welcome simple screens (only with text).

By the way: now I could not reproduce this strange "before real 60 seconds" timeout reach... But I swear it was more than a few times - I know it becouse always watch at device's screen and run test with commented `await driver.deleteSession();`.

Also, sometimes (2 or 3 times probably) when I was continuously trying to execute my testing script with "press, moveTo, release" code - there was 3 Internal Server 500 Errors - for each action.

**Comment by mykola-mokhnach** [comment]
> Why in your documentation not working example?

Can you please provide the direct link?

> Why adding "wait" solved problem? Is it important where exactly put "wait" in sequence order?
>Why delay is could be any number without any difference in result: 0, 100, 1000, 5000?
Actually there is no delay for 5 seconds - swipe would be done always with same time.
> Why first code is not working as 1 sequence?

Because this is how Android works. Swipe actions consists of long press-move-release actions. A press in Android (and iOS as well) is considered "long" if it is longer than 500ms. Previously Appium scripts were trying to "fix" erroneous input and now we don't do it.

> Why in gist#1 we could see that Appium "Shutting down because we waited 60 seconds for a command" almost immediately? And in gist#2 all is good: shutting down really comes after 60 seconds?

There is pretty complicated piece of code behind this feature. Feel free to investigate the flow there. A good starting point would be:
https://github.com/appium/appium-base-driver/blob/c6a14732b8d896321951515841106e16c285fc43/lib/basedriver/driver.js#L254
https://github.com/appium/appium-base-driver/blob/c6a14732b8d896321951515841106e16c285fc43/lib/basedriver/driver.js#L310

**Comment by amokmen** [comment]
> Can you please provide the direct link?

In first post was link: [sample for WebdriverIO](https://github.com/appium/appium/blob/master/docs/en/commands/interactions/touch/touch-perform.md)

**Comment by amokmen** [comment]
Guys, I have a bit philosophical question now: Where I did mistake?

I was trying to write simple, almost "hello-world", test for a 2 months (not full time, of course).
I am using Mac Mini as testing "server" with USB connected Android mobile device.
And Ubuntu/NodeJS/Mocha/WD and now WebdriverIO as developing environment.
For that period I got a tons of errors/errors_in_documentation and situations where something going wrong and I just don't know _what to do_.
Of course, some of them from my misunderstanding/misusing, but...

Now I am in deep miserable state of mind - what I am doing wrong?! Why writing test with 3 simplest methods is an endless pain?
I chose wrong language? Probably one should use Java and be rich and healthy :)?
I chose bad frameworks - WD/WebdriverIO are not good for mobile testing?
I chose bad strategy: before even trying to use Appium I should become skilled developer and deeply learn all Appium codebase, all code of Google's and Apple's testing instruments (UiAutomator2 and XCUITest) - to easily understand all inner mechanisms?

**Comment by amokmen** [comment]
More info probably according this issue.

I didn't mention in first post, but I always was running test with option `automationName: "UiAutomator2"` Now, just for experiment, I tried to run test with option `automationName: "Appium"` and Appium used UiAutomator instead UiAutomator2.

And immediately my basic test begun behavior strange: swipe was, but after swipe I am doing screenshot to prove that swipe was and test ends in next screen. So, screenshot with UiAutomator2 was as should be, but screenshot with UiAutomator was strange - It was taken **while** swipe, not **after** swipe! No change in test code, only 1 option.

It seems in case with UiAutomator different mechanism of swiping is working and I need pause test script after touchPerform and before taking screenshot? I am slowly going mad...

Some Appium log for UiAutomator swipe: [gist#3](https://gist.github.com/amokmen/1d24985b90616915d41238ec4f6669f0)

**Comment by amokmen** [comment]
> Nobody said this is going to be easy.

I don't want easy, I want game with **rules** :(
And now only this picture in my head: 
![one does not simply take appium and write test](https://user-images.githubusercontent.com/10855248/51751804-df17c080-20c6-11e9-8aaf-2f84052b0097.jpg)


> Reading some of [Appium Pro](https://appiumpro.com/editions) articles

Thank you, already start a day ago.

**Comment by amokmen** [comment]
@Jonahss First of all, thank you for detailed answer. Really appreciate it.

One should learn, learn and learn again :) And I would.
If I'll have time I could probably summarize all my disappointments. But problem is that there would be all-in-one included: Appium + WebdriverIO + WD + Mocha :)

Btw, I think I know why I had unexpected (for me) "Shutting down because we waited 60 seconds..."!
It was because, as I said, I run script many times with commented `driver.deleteSession()` - so, **previous unclosed session, kills current**.

**Comment by Jonahss** [comment]
Thanks for staying with us :D

Learning new things can be frustrating and hard. It's good to never become too set in one's ways. I'm looking forward to the American release of a new documentary about the Japanese animator Miyazaki, as he learns computer graphics at an old age, after mastering hand-drawn animation through his lifetime.

If a previous unclosed session kills the current, that'd be a great bug! I'll see if I can reproduce.

**Comment by amokmen** [comment]
> I started an Android session and an iOS session

Probably I got it. **There is no bug, only my misunderstanding and psychology.**

For example, I started 2 sessions on *1 same device*. First session and in short time after test script ends, next second session. So, 1st session "frozen" until 60 seconds expire (waiting for new commands, but there would not be any, because test script already ended). And 2nd session "frozen", because test script ended too. So, Appium now have 2 different sessions in 'frozen' state - waiting new commands. When timeout for waiting command for 1st session expires, Appium deletes this 1st session and **closes my app**. And I assuming (wrongfully) that now lifetime only for 2nd session and app should not be closed so fast!

------

Btw, after I want to get Appium log (with webhook) in my developing computer I immediately discover 3 problems/misunderstandings:

1) For using webhook I need Appium Server, because in Desktop version there is no such option in GUI.

2) After installing Appium Server (along with NodeJS) and running it I discovered, that Appium Server 1.10.1 and Appium Desktop 1.10.0, use different versions of UiAutomator2 package! Server is using *appium-uiautomator2-server-v2.7.0.apk* and Desktop is using *appium-uiautomator2-server-v3.1.1.apk*. So, when I trying to switch each other to run test - there was errors - Server could not work with newer Desktop's apk.

I fixed it by 2 commands (so, Server could reinstall what it wants):
```
adb uninstall io.appium.uiautomator2.server.test
adb uninstall io.appium.uiautomator2.server
```

3) Is it normal such **difference in response** when successfully find element?

If I run this code `const elem = await driver.findElement("accessibility id", "carousel-item-1");` while Desktop server running, I get next object as response:
```
{ 'element-6066-11e4-a52e-4f735466cecf': 'ae593f15-eb82-4a49-8e76-ac39c230d96a',
  ELEMENT: 'ae593f15-eb82-4a49-8e76-ac39c230d96a' }
```

But if run same code with Appium Server, I got different response!
```
{ 'element-6066-11e4-a52e-4f735466cecf': '95a46556-8f3f-4a85-8666-2bc60bb121a9' }
```

I mean not hashes of course, in Desktop's variant there is **second key-value**!

**Comment by Jonahss** [comment]
Ah, I'm glad you figured the sessions out! The timeout makes sense that way.

----------------------------

Nice catch on the element response changing, what you're seeing is us removing support for the old JSON Wire Protocol.
The newer W3C Webdriver Protocol defines an element as an object with the key: `element-6066-11e4-a52e-4f735466cecf`. https://www.w3.org/TR/webdriver1/#elements
The older JSON Wire Protocol defined an element as an object with the key `ELEMENT`. https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#webelement-json-object

So there's your answer. Appium Desktop is using a version which supported both, while the newer version of Appium you're using now only supports the W3C standard.

------------------------


> P. S. I have very important advice to all Appium newcomers: You MUST use "--log-level debug" option.

Good advice. You could share this with newcomers on [Appium Discuss](http://discuss.appium.io/)

**Comment by lubbo** [comment]
I'd like to keep the discussion on the topic....
I'm still experiencing problems scrolling.

- Using automationName = UiAutomator2 it doesn't work adding a wait or not it doesn't scroll.

```Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":444,"y":1092}},{"action":"wait","options":{"ms":0}},{"action":"moveTo","options":{"x":446,"y":400}},{"action":"release","options":{}}],"3b53a4e4-0647-4bab-b625-ce6f13b8c8fe"]```

```Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":444,"y":1092}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"x":446,"y":400}},{"action":"release","options":{}}],"3b53a4e4-0647-4bab-b625-ce6f13b8c8fe"]```

```Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":444,"y":1092}},{"action":"moveTo","options":{"x":446,"y":400}},{"action":"release","options":{}}],"3b53a4e4-0647-4bab-b625-ce6f13b8c8fe"]```

- Using automationName = Appium it works



I have the same problem on iOS but I haven't found how to workaround it.

I can't find a working guide on how to scroll on both platforms ... all methods I've found are not working.

I mean ... all Apps need scrolling at least once in a test ... so probably I'm doing it wrong otherwise this means that the earth is flat ...

Can you point me to a proper doc that explain a working updated method to scroll?

Thanks!!!

**Comment by amokmen** [comment]
> I can't find a working guide on how to scroll on both platforms ... all methods I've found are not working.

Welcome to my world of pain :)

> a proper doc that explain

There are no such docs and this is main problem :(

Now I am using for iOS this code:
```js
await driver.executeScript("mobile: swipe", [{ direction: "left" }]);
```
and for Android this one:
```js
await driver.touchPerform([
        {
          action: "press",
          options: {
            x: startX,
            y: startY
          }
        },
        { action: "wait", options: { mseconds: 0 } },
        {
          action: "moveTo",
          options: {
            x: endX,
            y: endY
          }
        },
        { action: "release" }
      ]);
```
And this is rather bad... Because as I could understand - main Appium purpose should be next words: "**One code** for both platforms".

**Comment by lubbo** [comment]
WOW!

The best news is that if in Appium 1.11.1 I've let it works in Android with

- ```automationName = Appium```
- ```{"action":"press","options":{"x":444,"y":1092}},{"action":"wait","options":{"ms":0}},{"action":"moveTo","options":{"x":446,"y":400}},{"action":"release","options":{}}```

now in Appium 1.12.0 ```automationName = Appium``` is not available anymore!!!

```selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a driver for automationName 'Appium' and platformName 'Android'. Please check your desired capabilities.```

and obviously using the good UiAutomator2 the scroll doesn't work!

OMG!

**Comment by lubbo** [comment]
> WOW!
> 
> The best news is that if in Appium 1.11.1 I've let it works in Android with
> 
> * `automationName = Appium`
> * `{"action":"press","options":{"x":444,"y":1092}},{"action":"wait","options":{"ms":0}},{"action":"moveTo","options":{"x":446,"y":400}},{"action":"release","options":{}}`
> 
> now in Appium 1.12.0 `automationName = Appium` is not available anymore!!!
> 
> `selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a driver for automationName 'Appium' and platformName 'Android'. Please check your desired capabilities.`
> 
> and obviously using the good UiAutomator2 the scroll doesn't work!
> 
> OMG!

Removing the ```automationName``` capability seems to work like the previous value ```Appium```

But the use of old UiAutomator is deprecated ...
I really need a good way to scroll with the new UiAutomator2 ....

**Comment by amokmen** [comment]
> is not available anymore

There is **no changelog** for 1.12.0, probably because it's not release... So, ["just smile and wave boys, smile and wave..."](http://media-cache-ec0.pinimg.com/736x/39/ea/a6/39eaa6f4836f2429a45f45155c6a3836.jpg)

> I really need a good way to scroll with the new UiAutomator2

Just checked my code (see my previous post) - **swipe is working** with UiAutomator2.

**Comment by lubbo** [comment]
> > I really need a good way to scroll with the new UiAutomator2
> 
> Just checked my code (see my previous post) - **swipe is working** with UiAutomator2.
It doesn't work for me :(

I'm using python client.
The Appium log is:

```[HTTP] {"actions":[{"action":"press","options":{"x":444,"y":1092}},{"action":"wait","options":{"ms":0}},{"action":"moveTo","options":{"x":446,"y":400}},{"action":"release","options":{}}],"sessionId":"8a099fd3-717c-41b4-a97f-64381c6e8fb1"}
[debug] [W3C (8a099fd3)] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":444,"y":1092}},{"action":"wait","options":{"ms":0}},{"action":"moveTo","options":{"x":446,"y":400}},{"action":"release","options":{}}],"8a099fd3-717c-41b4-a97f-64381c6e8fb1"]
[debug] [WD Proxy] Matched '/touch/perform' to command name 'performTouch'
[debug] [WD Proxy] Proxying [POST /touch/perform] to [POST http://localhost:8204/wd/hub/session/8b088dfe-e23c-4072-9ce1-8c7d066ffcf6/touch/perform] with body: {"startX":444,"startY":1092,"endX":446,"endY":400,"steps":22}

**Comment by amokmen** [comment]
1) According to it `startY: 1092` and `endY: 400` you doing **swipe from bottom to top**? [Screen coordinates X, Y](https://stackoverflow.com/questions/11483345/how-do-android-screen-coordinates-work).
2) What is your screen size? You could get it from device by `driver.getWindowSize()`.

**Comment by lubbo** [comment]
Yes, I’m scrolling a table.
I’ve recorded the script using the appium desktop.
It’s a J5 Samsung ... I don’t rememer the screen size but they should be correct... using old Appium automatorName works...

**Comment by aramana1** [comment]
I was using touchPerform to test pushnotifications (https://appiumpro.com/editions/15) and to toggle wifi on and off in iOS - The below code works with appium 1.9.2-beta.2, but when I upgraded to 1.12.0 the logs show as if the swipe has been done, but on observation it has not happened. Any pointers on whats going wrong?

 .touchPerform([
                                    {
                                        action: 'press',
                                        options: {
                                            x: Math.round(screenWidth / 2),
                                            y: Math.round(screenHeight + 15)
                                        }
                                    },
                                    {action: 'moveTo', options: {x: Math.round(screenWidth / 2), y: 4}},
                                    {action: 'release'}
                                ]);

**Comment by lubbo** [comment]
Adding a wait of 600ms after press?

**Comment by aramana1** [comment]
> Adding a wait of 600ms after press?

that did help. Thanks!

**Comment by PTOB** [comment]
Was having trouble with this myself, where swipe would not work at all across different widgets Adding a wait action of 0ms returned 

> Original error: Cannot read property 'ms' of undefined

but the following works for me every time.

```
browser.touchAction([
      { action: 'press', x: 681, y: 2300 },
      { action: "wait",  ms: 1000 },
      { action: 'moveTo', x: 681, y: 100 },
      'release'
    ]);
```


To answer question 4 in the Original Post 

> Why delay is could be any number without any difference in result: 0, 100, 1000, 5000?
Actually there is no delay for 5 seconds - swipe would be done always with same time.

The wait does not act as you would expect. Rather than act like a pause, it is actually how long it takes for the swipe from point A to point B (speed of swipe)

So a wait of 0ms would be instentanious and probably why it should not be used. 

Try it out with 1ms 500, 1000, 10000 and you will clearly see the difference in swiping speed.

**Comment by mykola-mokhnach** [comment]
touch actions have been deprecated and substituted by w3c actions

**Comment by Jonahss** [comment]
> Learning new things can be frustrating and hard. It's good to never become too set in one's ways. I'm looking forward to the American release of a new documentary about the Japanese animator Miyazaki, as he learns computer graphics at an old age, after mastering hand-drawn animation through his lifetime.

Update: I watched the movie. Miyazaki gives up completely and starts drawing the whole movie by hand.
