### ISSUE TITLE
Appium new version (1.10.0 and 1.10.1) clicks the first button of action style sheet in ios by default

### ISSUE THREAD

**Issue by SanjayDhami** [appium/appium#12077]
## The problem

When action style sheet is opened in (IOS APP), it automatically clicks the first button of action style sheet even there is no command for clicking first button. I don't see these issues in appium 1.9.0

## Environment

* Appium version : 1.10.0 and 1.10.1
* Last Appium version that did not exhibit the issue : 1.9.0
* Desktop OS/version used to run Appium: 1.10.0
* Node.js version (unless using Appium.app|exe): v8.11.3
* Mobile platform/version under test: IOS
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe:

I don't think log will give any insight in this case.
Please help...

**Comment by mykola-mokhnach** [comment]
No logs - no solution

**Comment by SanjayDhami** [comment]
![img_0005](https://user-images.githubusercontent.com/28166259/51758970-b377e480-208c-11e9-8be8-ae218730db94.png)
![img_0006](https://user-images.githubusercontent.com/28166259/51758977-b70b6b80-208c-11e9-9558-e30019978af1.png)


So when i click in Add unassigned Photos(s) buttom , it shows action style sheet with three options.
Once it opened it automatically click camera option even there is no command to click camera.

Please see the above log, if you need more info please let me know.

Thank you

**Comment by mykola-mokhnach** [comment]
Do you have auto accept alerts option enabled? If yes then try to disable it.

**Comment by SanjayDhami** [comment]
Thank you it worked... Appreciate
