### ISSUE TITLE
Upon Navigate, dom has loaded however not displayed.

### ISSUE THREAD

**Issue by marwahaks** [appium/appium#12080]
## The problem
Running Web Tests:

I execute the navigate to method and nothing is displayed on the actual iPad screen

The website is in the address bar and it is finished loaded, however all I see on the screen is the main freq visited sites page. 

I have checked web inspector and PageSource and it seems the page has loaded and the dom has indeed loaded.

Note: When I manually hit the 'View all tabs' within safari, the page appears, and when I  switch back to page mode, the freq visited sites are displayed again.

I know, weird bug..

I do have freq visited sites off within the safari setting, 
Enabled web inspected and enabled ui automation in settings.
## Environment

* Appium version (or git revision) that exhibits the issue: 1.11.3 beta
IOS 10.3.2
iPad Mini4
Real Device

NOTE: I am opening safari manually before navigating as I need to clear cache from the settings app first.

gist: https://gist.github.com/marwahaks/972163f87746dd2e933861fe59a7a1ee

**Comment by mykola-mokhnach** [comment]
Closed as inactive

**Comment by marwahaks** [comment]
Hi, @imurchie  we're still encountering this problem. Do you need any more information from us?
