### ISSUE TITLE
Can we have option to start app without -W

### ISSUE THREAD

**Issue by chaooe** [appium/appium#12081]
I face a problem is when use 'adb shell am start -W -n app/activity -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' on cmd, but it works to start without -W
the command is below
adb shell am start app/activity -a -n android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000
so do we have option to start without -W

**Comment by mykola-mokhnach** [comment]
Currently it is impossible to start activity without providing -W argument to it. Although, there is a possibility to execute custom shell commands via `mobile: shell`

**Comment by chaooe** [comment]
Thanks a lot for your feedback. May i know how to use mobile: shell, is this a capability in Appium client?
![default](https://user-images.githubusercontent.com/12910117/51877342-d402b000-23a6-11e9-820a-a77233441791.png)

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/android-shell.md
