### ISSUE TITLE
Javascript execution to scroll screen towards element does not work

### ISSUE THREAD

**Issue by NavdeepSingh09** [appium/appium#12084]
## The problem

I tried to scroll screen using javascript executer on iOS but it's not work as expected
It's working as expected on Appium Version 1.6.2 (1.6.2)

## Environment

Appium-Version 1.10.0 (1.10.0.20181230.2)
iOS v 11.4-Iphone8 plus-Simulator
Java

## Details

Code:

public void Scroll_screen(WebElement scrollElement){
        JavascriptExecutor js = (JavascriptExecutor) Regression.driver;
        HashMap<String, String> scrollObject = new HashMap<String, String>();
        scrollObject.put("element", ((IOSElement) scrollElement).getId());
        scrollObject.put("toVisible", "not an empty string");
        js.executeScript("mobile:scroll", scrollObject);
    }

## Link to Appium logs

https://gist.github.com/NavdeepSingh09/6acce4ece42dd100dbb5a2a0b3a9bbd6

**Comment by mykola-mokhnach** [comment]
Please report the problem to https://github.com/facebook/WebDriverAgent

Unfortunately there is nothing we can do on Appium side.
