### ISSUE TITLE
Appium crashes on reset if current context is webview

### ISSUE THREAD

**Issue by xlenz** [appium/appium#12083]
## The problem

Appium crashes on reset if current context is webview

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.1
* Desktop OS/version used to run Appium: MacOS
* Node.js version (unless using Appium.app|exe): 10
* Npm or Yarn package manager: 6.7.0
* Mobile platform/version under test: Android 9
* Real device or emulator/simulator: real
* Appium CLI or Appium.app|exe: appium from npm

## Details

Appium crashes on reset if current context is webview

## Link to Appium logs

https://gist.github.com/xlenz/d6fb0d779e8735784a8af4e6148f6342

## Code To Reproduce Issue [ Good To Have ]
code won't be helpful, here is highlevel steps:

1. run tests for some app
2. do something in native context
3. switch to webview
4. do reset
5. switch to native context
6. try find element in native context

**Comment by mykola-mokhnach** [comment]
I think this is the expected behaviour. The correct approach would be to quit the driver and then start it again with noReset option enabled.

**Comment by mgrybyk** [comment]
@mykola-mokhnach not likely.
To workaround this I can switch to native context before doing reset.

It should be possible to switch context after app reset.

**Comment by Jonahss** [comment]
@mgrybyk Hm yeah. I don't think Appium will know which context you are in after the reset. Would it be ok if after reset it switches back to whichever context was the default?

**Comment by mgrybyk** [comment]
Yes!
It doesn't matter much for me which context will be after reset but it should be possible to manually set context to a desired one...

**Comment by mgrybyk** [comment]
@Jonahss thanks a lot!

**Comment by Jonahss** [comment]
here's the PR https://github.com/appium/appium-android-driver/pull/495

**Comment by Jonahss** [comment]
PR merged. Will be in the next release, or [you can run from latest master](https://appiumpro.com/editions/47)
