### ISSUE TITLE
/session/:sessionId/element/:elementId/value crashes in webview if command sent in W3C format

### ISSUE THREAD

**Issue by mgrybyk** [appium/appium#12085]
## The problem

/session/:sessionId/element/:elementId/value crashes in webview if command sent in W3C format

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.1
* Mobile platform/version under test: Android, using **webview**
* Real device or emulator/simulator: real
* Appium CLI or Appium.app|exe:

## Details

/session/:sessionId/element/:elementId/value crashes in webview if command sent in W3C format

## Link to Appium logs

https://gist.github.com/mgrybyk/738ec7bf6bb6abb8698e1074479a6c12

## Code To Reproduce Issue [ Good To Have ]

```
// start with capabilities  "browserName": 'chrome',
// on android real device

browser.url("http://adam.goucher.ca/parkcalc/")
$("#EntryTime").setValue("qwe")
```

// value send in W3C way, however chrome supports jsonwp
`/session/:sessionId/element/:elementId/value`
method: POST
body:
```
{ text: "qwe" }
```

https://github.com/webdriverio/webdriverio/issues/3424

**Comment by mgrybyk** [comment]
Not sure, I think that appium might proxy w3c command as jsonwp command to chromedriver, but my assumption might be wrong

**Comment by mykola-mokhnach** [comment]
The patch has been merged to appium@beta

**Comment by mgrybyk** [comment]
Thanks a lot
