### ISSUE TITLE
An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET

### ISSUE THREAD

**Issue by dineshchakravarthy5** [appium/appium#12090]
## The problem

I am randomly facing this exception during my test executions, 
An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET
 
Also, I have observed incorrect shutdown command received to appium server

## Environment

* Appium version (or git revision) that exhibits the issue: appium server - 1.10.1 / Client -v7.0.0
* Last Appium version that did not exhibit the issue (if applicable): Observed in previous versions as well
* Desktop OS/version used to run Appium: MacOS, High Sierra - 10.13.6 
* Node.js version (unless using Appium.app|exe): v8.12.0
* Npm or Yarn package manager: Npm v6.4.1
* Mobile platform/version under test: Android 7.0 (Honor 6X)
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Details

Observed above exception intermittently, Whenever this issue has occurred, I see inappropriate shutdown command received from baseDriver in appium server logs, Server logs attached along with timestamp

Tried with lower appium versions as well, Still observed issue.
Issue observed in uiAutomator2 only

## Link to Appium logs

Appium server logs:
https://gist.github.com/dineshchakravarthy5/aaf59986b53edbcc6841844828ab2802
adb logcat:
https://gist.github.com/dineshchakravarthy5/ff9436595329a46b095aeee376686eb9

## Code To Reproduce Issue [ Good To Have ]

capabilities used:
capabilities.setCapability("appPackage", appPackage);
				capabilities.setCapability("udid", udid);
				capabilities.setCapability("appActivity", activityName);
				capabilities.setCapability("unicodeKeyboard", true);
				capabilities.setCapability("resetKeyboard", true);
		        capabilities.setCapability("noReset", true);
	            capabilities.setCapability("fullReset", false);
	            capabilities.setCapability("newCommandTimeout", 170);
 capabilities.setCapability("autoGrantPermissions", "true");
 capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.ANDROID_UIAUTOMATOR2);

**Comment by mykola-mokhnach** [comment]
This might an issue with the base driver, but I'll need your help to debug it better. 

Please insert the line
`log.debug('>>> Command timer cancelled');`

into `clearNewCommandTimeout` method of https://github.com/appium/appium-base-driver/blob/master/lib/basedriver/commands/timeout.js

and 

`log.debug(`>>> Command timer started for ${this.newCommandTimeoutMs}ms`);` 

into `startNewCommandTimeout` method (of the same source file) before `this.noCommandTimer` gets initialized for the first time. 

[Here](https://appiumpro.com/editions/47) you can find the tutorial and how to run Appium from source. Please try to run your test with updated source again and provide the resulting log including timestamps.

**Comment by dineshchakravarthy5** [comment]
@mykola-mokhnach , Will try from my end.
Could you please help me running appium from source.

Currently, I have already installed appium installed in my machine. So I tried to change the source in "timeout.js"  from "/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/"  and restarted appium

If that is not how it works,
I will try suggested way from above provided link.

**Comment by mykola-mokhnach** [comment]
> Currently, I have already installed appium installed in my machine. So I tried to change the source in "timeout.js" from "/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/" and restarted appium

This is not so simple. It is necessary to at least execute the transpilation process on the module after the source has been changed otherwise it won't pick up your changes.

**Comment by dineshchakravarthy5** [comment]
> > Currently, I have already installed appium installed in my machine. So I tried to change the source in "timeout.js" from "/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/" and restarted appium
> 
> This is not so simple. It is necessary to at least execute the transpilation process on the module after the source has been changed otherwise it won't pick up your changes.

Let me know for which module I suppose to do transpilation process to pick changes in "timeout.js"
Is it "appium-base-driver" ?

**Comment by mykola-mokhnach** [comment]
Yes, you should transpile the module in which lib folder the changes were made. By the way you could also include the change https://github.com/appium/appium-base-driver/pull/298 to your test and see it it helps to resolve the problem

**Comment by dineshchakravarthy5** [comment]
> Yes, you should transpile the module in which lib folder the changes were made. By the way you could also include the change [appium/appium-base-driver#298](https://github.com/appium/appium-base-driver/pull/298) to your test and see if it helps to resolve the problem

I am facing below issue while starting appium server with latest changes.. can you please look into it.
/Users/dineshsoma/Documents/Automation/appiumSource/appium/node_modules/appium-base-driver/index.js:4
import * as driver from './lib/basedriver/driver';
^^^^^^

SyntaxError: Unexpected token import

**Comment by dineshchakravarthy5** [comment]
> > Yes, you should transpile the module in which lib folder the changes were made. By the way you could also include the change [appium/appium-base-driver#298](https://github.com/appium/appium-base-driver/pull/298) to your test and see if it helps to resolve the problem
> 
> I am facing below issue while starting appium server with your latest changes.. can you please look into it.
> /Users/username/Documents/Automation/appiumSource/appium/node_modules/appium-base-driver/index.js:4
> import * as driver from './lib/basedriver/driver';
> ^^^^^^
> 
> SyntaxError: Unexpected token import

I could able to start server now after proper linking of appium-base-driver module.

Added above-mentioned lines in timout.js, For now I didnt observed the "ECONNRESET" or "inappropriate shutdown command received from baseDriver " issue.

But I encountered, Unable to send text into fields 
I am getting this error -  Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters. below is server logs for the same along with timestamp

https://gist.github.com/dineshchakravarthy5/4d213cd627f1b189e03f9a57816427a1
Using below env:
Appium: v1.11.0-beta.3 with latest appium-base-driver code cloned from git

**Comment by mykola-mokhnach** [comment]
Thanks. I close this issue as fixed. 

Please open another one with a detailed description if you think the described behaviour is a driver issue.
