### ISSUE TITLE
self.driver.reset() is not working on appium version  latest version . could you please have look on this , when ever i am using in my test cases , that test cases not running at all , 

### ISSUE THREAD

**Issue by Dwipro** [appium/appium#12095]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Please provide a proper issue description. Closed as incomplete

**Comment by Dwipro** [comment]
@mykola-mokhnach  i am using appium for mobile automation  with python ,
am trying to reset application using with self.driver.reset() ,this command was working on appium 1.6 version ,but i updated latest version 1.91  appium , same command self.driver.reset() is not working 

this is below code 
 def test_07ConfirmPass(self):
        try:

            time.sleep(3)
            self.driver.reset()
            print " Ruuning 7th test case"
            time.sleep(2)
            self.driver.find_element_by_xpath("//android.widget.EditText[@text='User name']").clear()
            time.sleep(2)
            # User can send any keys from Send_keys ('')#
            self.driver.find_element_by_xpath("//android.widget.EditText[@text='User name']").send_keys("User")
            time.sleep(2)
        except Exception:
            logger.warn("TC07 Fail :Unable to get Enter data in all the fields ")
            time.sleep(2)

**Comment by Dwipro** [comment]
[appium-server-logs.txt](https://github.com/appium/appium/files/2811170/appium-server-logs.txt)
please find server logs of appium.

let me know if you need any thing ?

**Comment by KazuCocoa** [comment]
What about using uiautomator2 as automationName?

> [warn] [35m[AndroidDriver][39m Consider setting 'automationName' capability to 'uiautomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.

**Comment by Dwipro** [comment]
@KazuCocoa  same issue with  uiautomator2  alos , self.driver.reset() doesn't work
@mykola-mokhnach  could you please let me know what details are required , i thing every details i have shared

**Comment by KazuCocoa** [comment]
Where is your `reset` call? When `reset` is called, you can observe below lines relevant to `appium/app/reset`
```

[HTTP] --> POST /wd/hub/session/79cdd702-b1c4-4622-9177-dc1ee5fc2ec4/appium/app/reset
[HTTP] {}
[debug] [W3C (79cdd702)] Calling AppiumDriver.reset() with args: ["79cdd702-b1c4-4622-9177-dc1ee5fc2ec4"]
[debug] [ADB] Getting install status for io.appium.android.apis
[debug] [ADB] Running '/Users/kazu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.android.apis'
[debug] [ADB] 'io.appium.android.apis' is installed
[debug] [ADB] Running '/Users/kazu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop io.appium.android.apis'
[debug] [ADB] Running '/Users/kazu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pm clear io.appium.android.apis'
[debug] [AndroidDriver] Performed fast reset on the installed 'io.appium.android.apis' application (stop and clear)
[debug] [ADB] Running '/Users/kazu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am start -W -n io.appium.android.apis/io.appium.android.apis.ApiDemos -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[debug] [W3C (79cdd702)] Responding to client with driver.reset() result: null
[HTTP] <-- POST /wd/hub/session/79cdd702-b1c4-4622-9177-dc1ee5fc2ec4/appium/app/reset 200 1364 ms - 14
[HTTP]
```


I wonder your log saied your client? calls delete session after finishing create session. Around below lines.

```
{"platformName":"Android","deviceName":"Samsung Galaxy S7","UDID":"5d2556d5","platformVersion":"6.0.1","appPackage":"com.schneiderelectric.eCommissionSmartXIPController.Internal","appActivity":"md5e3e0ca5a61fc8aa16e6e0a6d7e9daa42.SplashScreen"},"platformName":"Android","deviceName":"5d2556d5","UDID":"5d2556d5","platformVersion":"6.0.1","appPackage":"com.schneiderelectric.eCommissionSmartXIPController.Internal","appActivity":"md5e3e0ca5a61fc8aa16e6e0a6d7e9daa42.SplashScreen","deviceUDID":"5d2556d5","deviceScreenSize":"1440x2560","deviceModel":"SM-G930U","deviceManufacturer":"samsung"}}
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[32m200[39m [90m20208 ms - 873[39m
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mDELETE[39m [37m/wd/hub/session/14d8526b-2250-4c79-a616-9a7c5439c225[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[W3C][39m Calling AppiumDriver.deleteSession() with args: ["14d8526b-2250-4c79-a616-9a7c5439c225"]
[debug] [35m[BaseDriver][39m Event 'quitSessionRequested' logged at 1548829758611 (11:59:18 GMT+0530 (India Standard Time))
[info] [35m[Appium][39m Removing session 14d8526b-2250-4c79-a616-9a7c5439c225 from our master session list
```

**Comment by KazuCocoa** [comment]
No.
I meant if you called `reset()` command, then a path like `/appium/app/reset` should have appeared in the server log, but I could not see such path in  https://github.com/appium/appium/issues/12095#issuecomment-458828846 .

Thus, I wonder your python code does not reach to `reset()`.
Could you share your appium log again with uiautomator2? @Dwipro

**Comment by Dwipro** [comment]
[appium-server-logs.txt](https://github.com/appium/appium/files/2826933/appium-server-logs.txt)
    def test_01 test(self):
        try:
            print " Ruunig 1st test case"------------ my print statement reaching till this point after that it's moving second test cases , when i am calling reset() , if not calling reset in my code ,it executing proper my test cases.
            self.driver.reset()
            time.sleep(3)
            self.driver.find_element_by_xpath("//android.widget.Button[@text='Activate']").click()
            time.sleep(2)
            self.driver.find_element_by_xpath("//android.widget.TextView[@text='Information']").click()
            time.sleep(2)
            temp = self.driver.find_element_by_xpath("//android.widget.TextView[@text='Information']")
            text=temp.text
            print(text)
            time.sleep(2)
            self.driver.find_element_by_xpath("//android.widget.Button[@text='Ok']").click()
            time.sleep(3)
            print(text)
            time.sleep(2)
            if text=='Information':
                time.sleep(2)
                logger.info("TC01 Pass :successfully ")
                time.sleep(2)

        except Exception:
            logger.warn("TC01 Fail :Err")
            time.sleep(2)

**Comment by KazuCocoa** [comment]
I assumed the `reset()` command did not issue reset command. But the method probably issued correctly. https://github.com/appium/python-client/pull/326

btw, did you call `send_keys`? (I could not see `send_keys` in your Python script though)

```
[debug] [35m[W3C][39m Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"8d3f16f9-9e17-4855-b805-c6b1ea67a5dd"}
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session/87d16804-22da-4304-820e-c15d95f423ca/element [39m[32m200[39m [90m482 ms - 88[39m
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/87d16804-22da-4304-820e-c15d95f423ca/element/8d3f16f9-9e17-4855-b805-c6b1ea67a5dd/value[39m
[info] [35m[HTTP][39m [90m{"text":"CommissioningTool","id":"8d3f16f9-9e17-4855-b805-c6b1ea67a5dd","value":["C","o","m","m","i","s","s","i","o","n","i","n","g","T","o","o","l"]}[39m
[debug] [35m[W3C][39m Calling AppiumDriver.setValue() with args: [["C","o","m","m","i","s","s","i","o","n","i","n","g","T","o","o","l"],"8d3f16f9-9e17-4855-b805-c6b1ea67a5dd","87d16804-22da-4304-820e-c15d95f423ca"]
[debug] [35m[JSONWP Proxy][39m Matched '/element/8d3f16f9-9e17-4855-b805-c6b1ea67a5dd/value' to command name 'setValue'
[debug] [35m[JSONWP Proxy][39m Proxying [POST /element/8d3f16f9-9e17-4855-b805-c6b1ea67a5dd/value] to [POST http://localhost:8200/wd/hub/session/1ec8cb0c-45db-44ee-85e9-52ab9e536b2a/element/8d3f16f9-9e17-4855-b805-c6b1ea67a5dd/value] with body: {"elementId":"8d3f16f9-9e17-4855-b805-c6b1ea67a5dd","text":"CommissioningTool","replace":false}[debug] [35m[JSONWP Proxy][39m Got response with status 200: {"sessionId":"1ec8cb0c-45db-44ee-85e9-52ab9e536b2a","status":0,"value":""}
```

**Comment by Dwipro** [comment]
@KazuCocoa that was second  dummy test case, immediate it moved , when i called reset() in first test cases

**Comment by KazuCocoa** [comment]
Okay. I see.
I could not see any logs about `/appium/app/reset` in the attached log.
I assume python client does not send any reset command to appium server in your environment.

> this command was working on appium 1.6 version

Do you have a log based on 1.6?

And you are using the latest Python client, right?
The latest version is 0.36.

**Comment by Dwipro** [comment]
@KazuCocoa  1.6 appium i don't have logs , yes i am using python client  0.36 version , as i am using pycharm editor to write the script

**Comment by KazuCocoa** [comment]
Can you call only `self.driver.reset()` after create session and attach the log here?

**Comment by Dwipro** [comment]
@KazuCocoa  i have attached logs after self.driver.reset() 
[appium-only self_driver_reset().txt](https://github.com/appium/appium/files/2827404/appium-only.self_driver_reset.txt)

**Comment by KazuCocoa** [comment]
I'm not sure why `/reset` command does not appear in your appium log, but I guess your Python reset command was not called or did not send `/reset` command to Appium server.
The lates Appium Python client can issue `/reset` command as the above attached test.
