### ISSUE TITLE
The command "xcode-select -p" can no longer represent whether xcode&command line tools is already installed on macOS 10.12+

### ISSUE THREAD

**Issue by ThinkDone** [appium/appium#12093]
## The problem

I got a new MacBook Pro with no xcode installed, but "appium-doctor --ios" checked that xcode and command line tools are already installed. Then when I create a session, appium reports an error:

[simctl] Error: simctl error running 'list': xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

## Environment

* Desktop OS/version used to run Appium: macOS 10.12
* Appium-doctor version: 1.7.0

**Comment by KazuCocoa** [comment]
What about running `xcode-select --install` once?

I saw `invalid active developer path` happened in Mojava. Then, `xcode-select --install` helped to fix the issue.
We can add the checking logic in the doctor If it can fix the issue.

**Comment by ThinkDone** [comment]
@KazuCocoa, I got "xcode-select: error: command line tools are already installed, use "Software Update" to install updates" from "xcode-select --install". After that I ran "softwareupdate -al", no new CLT available.

brew config: 
HOMEBREW_VERSION: 1.8.6
CLT: 7.2.0.0.1.1447826929
Xcode: N/A

**Comment by KazuCocoa** [comment]
What about `xcode-select --reset`?

> Xcode: N/A
mmm...

**Comment by KazuCocoa** [comment]
What about downloading the command line package from https://developer.apple.com/download/more/ and install it via GUI installer?

https://apple.stackexchange.com/questions/321858/xcrun-missing-installing-xcode-command-line-tools-not-fixing-issue

**Comment by ThinkDone** [comment]
I have done some research and found that there are many similar problems and solutions, but only one solution is effective for me. that is to install Xcode from the Mac App Store, then change the location of "Command Line Tools" in preferences.

**Comment by KazuCocoa** [comment]
thanks so much your research.

**Comment by KazuCocoa** [comment]
`xcode-select -p` shows `/Library/Developer/CommandLineTools/` case happens.
Then, `xcrun simctl` fails like the above.

To fix the issue, we must set `xcode-select` path to Xcode.app properly.
We need to add one check in Xcode check process in appium-doctor
