### ISSUE TITLE
unable to install WebDriverAgent because of xcodebuild failure

### ISSUE THREAD

**Issue by sheikhjebran** [appium/appium#12092]
Hi guys, 
I am using MAC machine and appium-desktop latest version 1.10.0

but when i run the object inspector over the mac machine I get the below issue.

An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.

**Comment by mykola-mokhnach** [comment]
Usually such error means that the application under test is not signed properly. Please use Appium forum for questions.

Closed as not an issue.
