### ISSUE TITLE
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: The application at '/Users/macbookpro/eclipse-workspace/CCWMobileTest/⁨src/app-debug1-04-Dec-2018.apk' does not exist or is not accessible (WARNING: The server did not provide any stacktrace information)

### ISSUE THREAD

**Issue by stranger2you** [appium/appium#12091]
## The problem

FAILED CONFIGURATION: @BeforeClass LaunchApp
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: The application at '/Users/macbookpro/eclipse-workspace/CCWMobileTest/⁨src/app-debug1-04-Dec-2018.apk' does not exist or is not accessible (WARNING: The server did not provide any stacktrace information)

## Environment

* Appium version (or git revision) that exhibits the issue: v1.10.0
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: 10.14 (18A391)
* Node.js version (unless using Appium.app|exe): v8.11.3
* Npm or Yarn package manager: Npm 6.7.0
* Mobile platform/version under test:Andoird/7.0
* Real device or emulator/simulator: Emulator and Real device
* Appium CLI or Appium.app|exe: Appium.app

## Details
Verified JAVA_HOME & ANDROID_HOME

## Link to Appium logs

[info] [35m[Appium][39m Welcome to Appium v1.10.0
[info] [35m[Appium][39m Appium REST http interface listener started on 0.0.0.0:4723[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{"desiredCapabilities":{"app":"/Users/macbookpro/eclipse-workspace/CCWMobileTest/⁨src/app-debug1-04-Dec-2018.apk","appActivity":"com.dcrworkforce.mobile.activity.LandingPagewithAutologin","appPackage":"com.dcrworkforce.mobile","newCommandTimeout":"60","VERSION":"7.0","automationName":"UiAutomator2)","autoGrantPermissions":true,"session-override":"true","platformName":"Android","deviceName":"AVD_POC_7.0)","noResetValue":"false"},"capabilities":{"firstMatch":[{"VERSION":"7.0","appium:app":"/Users/macbookpro/eclipse-workspace/CCWMobileTest/⁨src/app-debug1-04-Dec-2018.apk","appium:appActivity":"com.dcrworkforce.mobile.activity.LandingPagewithAutologin","appium:appPackage":"com.dcrworkforce.mobile","appium:autoGrantPermissions":true,"appium:automationName":"UiAutomator2)","appium:deviceName":"AVD_POC_7.0)","appium:newCommandTimeout":"60","noResetValue":"false","platformName":"android","session-override":"true"}]}}[39m
[debug] [35m[W3C][39m Calling AppiumDriver.createSession() with args: [{"app":"/Users/macbookpro/eclipse-workspace/CCWMobileTest/⁨src/app-debug1-04-Dec-2018.apk","appActivity":"com.dcrworkforce.mobile.activity.LandingPagewithAutologin","appPackage":"com.dcrworkforce.mobile","newCommandTimeout":"60","VERSION":"7.0","automationName":"UiAutomator2)","autoGrantPermissions":true,"session-override":"true","platformName":"Android","deviceName":"AVD_POC_7.0)","noResetValue":"false"},null,{"firstMatch":[{"VERSION":"7.0","appium:app":"/Users/macbookpro/eclipse-workspace/CCWMobileTest/⁨src/app-debug1-04-Dec-2018.apk","appium:appActivity":"com.dcrworkforce.mobile.activity.LandingPagewithAutologin","appium:appPackage":"com.dcrworkforce.mobile","appium:autoGrantPermissions":true,"appium:automationName":"UiAutomator2)","appium:deviceName":"AVD_POC_7.0)","appium:newCommandTimeout":"60","noResetValue":"false","platformName":"android","session-override":"true"}]}]
[debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1548677421665 (17:40:21 GMT+0530 (IST))
[warn] [35m[BaseDriver][39m The capabilities ["VERSION","noResetValue","session-override"] are not standard capabilities and should have an extension prefix
[warn] [35m[BaseDriver][39m Number capability passed in as string. Functionality may be compromised.
[info] [35m[Appium][39m Could not parse W3C capabilities: 'automationName' UiAutomator2) not part of Appium,Selendroid,UiAutomator2,XCUITest,YouiEngine,Espresso,Tizen,Fake
[info] [35m[Appium][39m Trying to fix W3C capabilities by merging them with JSONWP caps
[warn] [35m[BaseDriver][39m The capabilities ["VERSION","noResetValue","session-override","app","appActivity","appPackage","autoGrantPermissions","automationName","deviceName","newCommandTimeout"] are not standard capabilities and should have an extension prefix
[warn] [35m[BaseDriver][39m Number capability passed in as string. Functionality may be compromised.
[warn] [35m[Appium][39m Could not parse fixed W3C capabilities: 'automationName' UiAutomator2) not part of Appium,Selendroid,UiAutomator2,XCUITest,YouiEngine,Espresso,Tizen,Fake. Falling back to JSONWP protocol
[info] [35m[Appium][39m Creating new AndroidDriver (v4.8.0) session
[info] [35m[Appium][39m Capabilities:
[info] [35m[Appium][39m   app: /Users/macbookpro/eclipse-workspace/CCWMobileTest/⁨src/app-debug1-04-Dec-2018.apk
[info] [35m[Appium][39m   appActivity: com.dcrworkforce.mobile.activity.LandingPagewithAutologin
[info] [35m[Appium][39m   appPackage: com.dcrworkforce.mobile
[info] [35m[Appium][39m   newCommandTimeout: 60
[info] [35m[Appium][39m   VERSION: 7.0
[info] [35m[Appium][39m   automationName: UiAutomator2)
[info] [35m[Appium][39m   autoGrantPermissions: true
[info] [35m[Appium][39m   session-override: true
[info] [35m[Appium][39m   platformName: Android
[info] [35m[Appium][39m   deviceName: AVD_POC_7.0)
[info] [35m[Appium][39m   noResetValue: false
[debug] [35m[BaseDriver][39m Creating session with MJSONWP desired capabilities: {"app":"/Users/macbookpro/e...
[warn] [35m[BaseDriver][39m Capability 'newCommandTimeout' changed from string ('60') to integer (60). This may cause unexpected behavior
[warn] [35m[BaseDriver][39m The following capabilities were provided, but are not recognized by appium: VERSION, session-override, noResetValue.
[info] [35m[BaseDriver][39m Session created with session id: 47758f54-a9e0-4d2e-9c91-5e82cff1ff74[info] [35m[AndroidDriver][39m Java version is: 1.8.0_181
[info] [35m[AndroidDriver][39m Retrieving device list
[debug] [35m[ADB][39m Trying to find a connected android device
[debug] [35m[ADB][39m Getting connected devices...
[debug] [35m[ADB][39m 1 device(s) connected
[info] [35m[AndroidDriver][39m Using device: emulator-5554
[debug] [35m[ADB][39m Setting device id to emulator-5554
[debug] [35m[ADB][39m Running '/Users/macbookpro/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk'
[debug] [35m[ADB][39m Current device property 'ro.build.version.sdk': 24
[debug] [35m[ADB][39m Device API level: 24
[warn] [35m[AndroidDriver][39m Consider setting 'automationName' capability to 'uiautomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.
[debug] [35m[AndroidDriver][39m Shutting down Android driver
[debug] [35m[AndroidDriver][39m Called deleteSession but bootstrap wasn't active
[debug] [35m[ADB][39m Running '/Users/macbookpro/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop io.appium.unlock'[debug] [35m[AndroidDriver][39m Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[debug] [35m[BaseDriver][39m Event 'newSessionStarted' logged at 1548677422045 (17:40:22 GMT+0530 (IST))
[debug] [35m[MJSONWP][39m Encountered internal error running command: Error: The application at '/Users/macbookpro/eclipse-workspace/CCWMobileTest/⁨src/app-debug1-04-Dec-2018.apk' does not exist or is not accessible
[debug] [35m[MJSONWP][39m     at APPLICATIONS_CACHE_GUARD.acquire (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/lib/basedriver/helpers.js:147:13)
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[31m500[39m [90m382 ms - 277[39m
[info] [35m[HTTP][39m [90m[39m

## Code To Reproduce Issue [ Good To Have ]

public class CCW_Methods {
	AndroidDriver<?> driver;
	 

	@SuppressWarnings("rawtypes")
	@BeforeClass
	public void LaunchApp() throws InterruptedException {

		//File app = new File("‎⁨Untitled⁩/Users⁩/macbookpro⁩/Downloads⁩", "app-debug1-04-Dec-2018.apk");
		File app = new File("⁨src", "app-debug1-04-Dec-2018.apk");

		DesiredCapabilities caps = new DesiredCapabilities();
		 //caps.setCapability("app", "⁨src/app-debug1-04-Dec-2018.apk");

		caps.setCapability("app", app.getAbsolutePath());
		caps.setCapability("platformName", "Android");
		//caps.setCapability("deviceName", "Moto G (4)");
		caps.setCapability("deviceName", "AVD_POC_7.0)");
		caps.setCapability("automationName", "UiAutomator2)");
		caps.setCapability("session-override","true"); 

		//caps.setCapability("deviceName", "OnePlust 5T)");

		caps.setCapability("VERSION", "7.0");
		caps.setCapability("appPackage", "com.dcrworkforce.mobile");
		caps.setCapability("appActivity", "com.dcrworkforce.mobile.activity.LandingPagewithAutologin");
		caps.setCapability("noResetValue","false"); 
		caps.setCapability("autoGrantPermissions", true);
		caps.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, "60");

		
		try {
			driver = new AndroidDriver(new URL("http://0.0.0.0:4723/wd/hub"), caps);
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}
	}

**Comment by stranger2you** [comment]
yes.

**Comment by stranger2you** [comment]
<img width="789" alt="screenshot 2019-01-28 at 6 48 40 pm" src="https://user-images.githubusercontent.com/10287093/51838880-99106600-232d-11e9-8cf9-85acb8b54250.png">

**Comment by mykola-mokhnach** [comment]
You must make sure the path is accessible for the appium process, because it might be executed with privileges which are different from these at your user account.

**Comment by mykola-mokhnach** [comment]
Also, if the server is running on another machine then an URL should be provided instead of a local path

**Comment by stranger2you** [comment]
> You must make sure the path is accessible for the appium process, because it might be executed with privileges which are different from these at your user account.

Tried with all possible ways to access the path for the appium process and could not able to launch the application 
Note: The same code executing without any errors in Windows.

**Comment by stranger2you** [comment]
> Also, if the server is running on another machine then an URL should be provided instead of a local path

Tried but failed again
and the server is running on the same machine.

**Comment by mykola-mokhnach** [comment]
> [debug] �[35m[W3C]�[39m Calling AppiumDriver.createSession() with args: [{"app":"/Users/macbookpro/eclipse-workspace/CCWMobileTest/⁨src/app-debug1-04-Dec-2018.apk","appActivity":"com.dcrworkforce.mobile.activity.LandingPagewithAutologin","appPackage":"com.dcrworkforce.mobile","newCommandTimeout":"60","VERSION":"7.0","automationName":"UiAutomator2)","autoGrantPermissions":true,"session-override":"true","platformName":"Android","deviceName":"AVD_POC_7.0)","noResetValue":"false"},null,{"firstMatch":[{"VERSION":"7.0","appium:app":"/Users/macbookpro/eclipse-workspace/CCWMobileTest/⁨src/app-debug1-04-Dec-2018.apk","appium:appActivity":"com.dcrworkforce.mobile.activity.LandingPagewithAutologin","appium:appPackage":"com.dcrworkforce.mobile","appium:autoGrantPermissions":true,"appium:automationName":"UiAutomator2)","appium:deviceName":"AVD_POC_7.0)","appium:newCommandTimeout":"60","noResetValue":"false","platformName":"android","session-override":"true"}]}]

To me it looks like the passed capabilities might be corrupted. There is, for example, an unexpected line break before `2018`. Also, the device name and automation name caps contain extra parentheses.

**Comment by mykola-mokhnach** [comment]
Also, what happens if you put the app by different path or upload it to some URL and pass this URL as capability value?
