### ISSUE TITLE
Problems running on XCode 10.2(beta) and iOS 12.2(beta)

### ISSUE THREAD

**Issue by drzajwo** [appium/appium#12099]
## The problem

Hi, while trying to run rspec tests using appium i'm facing an issue. Which at the end shows as Xcode build 65 error. The problem is with building WDA project. Details below. 

## Environment

* Appium version - 1.10.1
* Desktop OS/version used to run Appium: macOS Mojave
* Node.js version (unless using Appium.app|exe): tested on 8 and also 10
* Npm or Yarn package manager: npm 6.4.1
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: real device
* appium_lib: 9.18.0
* appium_lib_core: 2.3.3

## Details

Getting error while trying to run test:
`2019-01-30 15:58:55:175 - [JSONWP Proxy] Got an unexpected response: {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}
2019-01-30 15:58:56:177 - [debug] [JSONWP Proxy] Matched '/status' to command name 'getStatus'
2019-01-30 15:58:56:178 - [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
2019-01-30 15:58:56:186 - [JSONWP Proxy] Got an unexpected response: {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}`

which finally gets to error:
> "xcodebuild failed with code 65"

 which is related in building WDA runner. WDA project is signed properly and even trying to build it manually in xcode fails:
`"/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Categories/XCUIElement+FBPickerWheel.m:44:15: Messaging unqualified id"`

## Link to Appium logs

[Full appium logs](https://gist.github.com/drzajwo/63a0bc51d211e54c590d85aeeb47a8b8)

## Additional info
App isn't launched. When trying to run on previous Appium (like 1.9.0) on iOS 12.2 beta the native app webview is only one available. If you need more info please ask.
Thanks in advance ;)

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/facebook/WebDriverAgent

**Comment by mykola-mokhnach** [comment]
You can try to patch the code with https://github.com/appium/appium-xcuitest-driver/pull/866 as a temporary workaround. [Here](https://appiumpro.com/editions/47) is the tutorial on how to build Appium from source.
