### ISSUE TITLE
Is it possible to call android application method directly in Appium?

### ISSUE THREAD

**Issue by yma200** [appium/appium#12102]
## The problem

I want to be able to call a method from my android apk via Appium to expose hidden properties of a custom ui component for automation purposes. One way to do it is to ask the developers to add this info in the content-description. but i see that appium studio by experitest is able to do that if i instrument the apk under test.
**instrumenting the apk:**
https://docs.experitest.com/display/public/TD/SeeTestAutomation+-+Instrumenting+Android+Applications

calling NativeAPICall
https://docs.experitest.com/display/public/TD/SeeTestAutomation-+RunNativeAPICall

## Environment

latest version of appium

**Comment by mykola-mokhnach** [comment]
Yes it is possible, but only with Espresso driver: https://github.com/appium/appium-espresso-driver/blob/9b198680746a8f5f2bd02daf747c57ee31ba8756/lib/commands/general.js#L199
