### ISSUE TITLE
iOS 12.2 Support

### ISSUE THREAD

**Issue by imurchie** [appium/appium#12101]
## The problem

The first beta of Xcode 10.2 is out and needs to be supported.

**Comment by KazuCocoa** [comment]
Just a note. With Xcode 10.2, iOS simulator key name has been updated.
https://github.com/wix/AppleSimulatorUtils/pull/42
But maybe we do not use such JSON format so it should not break us.

**Comment by imurchie** [comment]
We already support that: https://github.com/appium/node-simctl/pull/77

**Comment by KazuCocoa** [comment]
A note. `-Wobjc-messaging-id` does not work for Xcode 9. We cannot add it to prevent objc warnings.
https://github.com/appium/WebDriverAgent/pull/147

**Comment by mykola-mokhnach** [comment]
@imurchie I assume this one can be closed as fixed

**Comment by imurchie** [comment]
It's mostly fixed. Not entirely (web on real devices is still out, and there are some issues with web in general).

**Comment by imurchie** [comment]
But you can build and install, and run tests.
