### ISSUE TITLE
Appium desktop is not able to capture the screenshot  in IOS

### ISSUE THREAD

**Issue by SanjayDhami** [appium/appium#12109]
## The problem

I was trying to inspect the particular module in IOS app using appium desktop, when  i click refresh source and screenshot it close the app 
## Environment

* Appium version (or git revision) that exhibits the issue: Appium Desktop : 1.10.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS High Sierra Version 10.13.6
* Node.js version (unless using Appium.app|exe):v8.11.3
* Npm or Yarn package manager:
* Mobile platform/version under test: IOS
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe:

## Details

Here is log in Appium Server
[HTTP] --> GET /wd/hub/session/fe813392-8a2b-40d1-b1e5-ef5abfc488f0/source
[HTTP] {}
[MJSONWP (fe813392)] Calling AppiumDriver.getPageSource() with args: ["fe813392-8a2b-40d1-b1e5-ef5abfc488f0"]
[XCUITest] Executing command 'getPageSource'
[JSONWP Proxy] Matched '/source' to command name 'getPageSource'
[JSONWP Proxy] Proxying [GET /source] to [GET http://localhost:8100/session/5835C683-18E4-44BE-9E3E-032AEFF28B56/source] with no body
[Xcode]     t =   652.85s Find the Application 'com.homenetauto.DigitalLot'
[Xcode] 
[Xcode]     t =   652.85s     Snapshot accessibility hierarchy for app with pid 331
[Xcode] 
[Xcode] 2019-01-31 13:15:53.464140-0600 WebDriverAgentRunner-Runner[316:32325] Getting the snapshot timed out after 15 seconds
[Xcode] 
[Xcode] 2019-01-31 13:15:53.464305-0600 WebDriverAgentRunner-Runner[316:32325] Internal error: Error Domain=com.apple.dt.xctest.automation-support.error Code=5 "Timed out snapshotting com.apple.testmanagerd, app is either unresponsive or taking too long to snapshot." UserInfo={accessibility-error=-25204, NSLocalizedDescription=Timed out snapshotting com.apple.testmanagerd, app is either unresponsive or taking too long to snapshot.}
[Xcode]     t =   653.21s Snapshot accessibility hierarchy for app with pid 331
[Xcode] 
[Xcode]     t =   653.21s Snapshot accessibility hierarchy for app with pid 331
[Xcode] 
[Xcode]     t =   653.23s Get all elements bound by accessibility element for: Elements matching predicate 'wdUID IN {"04000000-0000-0000-4B01-000000000000", "05000000-0000-0000-4B01-000000000000", "06000000-0000-0000-4B01-000000000000", "07000000-0000-0000-4B01-000000000000"} AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0)'
[Xcode] 
[Xcode]     t =   653.23s     Snapshot accessibility hierarchy for app with pid 331
[Xcode] 
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"\\n\\n\",\n  \"sessionId\" : \"5835C683-18E4-44BE-9E3E-032AEFF28B56\",\n  \"status\" : 0\n}"
[XCUITest] Connection to WDA timed out
[iProxy] recv failed: Operation not permitted
[MJSONWP (fe813392)] Responding to client with driver.getPageSource() result: ""
[HTTP] <-- GET /wd/hub/session/fe813392-8a2b-40d1-b1e5-ef5abfc488f0/source 200 471 ms - 272
[HTTP] 
[HTTP] --> GET /wd/hub/session/fe813392-8a2b-40d1-b1e5-ef5abfc488f0/screenshot
[HTTP] {}
[MJSONWP (fe813392)] Calling AppiumDriver.getScreenshot() with args: ["fe813392-8a2b-40d1-b1e5-ef5abfc488f0"]
[XCUITest] Executing command 'getScreenshot'
[XCUITest] Taking screenshot with WDA
[JSONWP Proxy] Matched '/screenshot' to command name 'getScreenshot'
[JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/5835C683-18E4-44BE-9E3E-032AEFF28B56/screenshot] with no body
[XCUITest] Connection to WDA timed out
[iProxy] recv failed: Operation not permitted
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"iVBORw0KGgoAAAANSUhEUgAAAu4AAAU2CAIAAABFtaRRAAAAAXNSR0IArs4c6QAA\\r\\nABxpRE9UAAAAAgAAAAAAAAKbAAAAKAAAApsAAAKbAAAZ3wzJR5AAABmrSURBVHgB\\r\\n7NAxAQAAAMKg9U9tCy+IQGHAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAED\\r\\nBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwY\\r\\nMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDA\\r\\ngAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAED\\r\\nBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwY\\r\\nMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDA\\r\\ngAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAED\\r\\nBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwY\\r\\nMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDA\\r\\ngAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAED\\r\\nBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwY\\r\\nMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDA\\r\\ngAEDBgwYMGDAgAEDBgwYM...
[MJSONWP (fe813392)] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAAAu4AAAU2CAIAAABFtaRRAAAAAXNSR0IArs4c6QAA\r\nABxpRE9UAAAAAgAAAAAAAAKbAAAAKAAAApsAAAKbAAAZ3wzJR5AAABmrSURBVHgB\r\n7NAxAQAAAMKg9U9tCy+IQGHAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAED\r\nBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwY\r\nMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDA\r\ngAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAED\r\nBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwY\r\nMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDA\r\ngAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAED\r\nBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwY\r\nMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDA\r\ngAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAED\r\nBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwY\r\nMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDA\r\ngAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAEDBgwYMGDAgAED\r\n...
[HTTP] <-- GET /wd/hub/session/fe813392-8a2b-40d1-b1e5-ef5abfc488f0/screenshot 200 59 ms - 18862
[HTTP] 
[HTTP] --> GET /wd/hub/session/fe813392-8a2b-40d1-b1e5-ef5abfc488f0/window/current/size
[HTTP] {}
[MJSONWP (fe813392)] Calling AppiumDriver.getWindowSize() with args: ["current","fe813392-8a2b-40d1-b1e5-ef5abfc488f0"]
[XCUITest] Executing command 'getWindowSize'
[MJSONWP (fe813392)] Responding to client with driver.getWindowSize() result: {"width":375,"height":667}
[HTTP] <-- GET /wd/hub/session/fe813392-8a2b-40d1-b1e5-ef5abfc488f0/window/current/size 200 2 ms - 98
<img width="1810" alt="screen shot 2019-01-31 at 1 17 50 pm" src="https://user-images.githubusercontent.com/28166259/52079247-c55cfa00-255a-11e9-9e78-4a9997f7d1fe.png">

[HTTP]

**Comment by mykola-mokhnach** [comment]
I don't observe any errors in the log. Can you please attach the full log?

**Comment by mykola-mokhnach** [comment]
> [Xcode] 2019-01-31 13:15:53.464140-0600 WebDriverAgentRunner-Runner[316:32325] Getting the snapshot timed out after 15 seconds
> [Xcode]
> [Xcode] 2019-01-31 13:15:53.464305-0600 WebDriverAgentRunner-Runner[316:32325] Internal error: Error Domain=com.apple.dt.xctest.automation-support.error Code=5 "Timed out snapshotting com.apple.testmanagerd, app is either unresponsive or taking too long to snapshot." UserInfo={accessibility-error=-25204, NSLocalizedDescription=Timed out snapshotting com.apple.testmanagerd, app is either unresponsive or taking too long to snapshot.}
> [Xcode] t = 653.21s Snapshot accessibility hierarchy for app with pid 331
> [Xcode]

This one seems to be an XCTest issue. I don't think we can do anything on the Appium side

**Comment by mykola-mokhnach** [comment]
https://forums.developer.apple.com/thread/44701
