### ISSUE TITLE
iOS-HybridApp-WebView: WebView is returned very abnormally

### ISSUE THREAD

**Issue by MarvelCoder** [appium/appium#12104]
## The problem

So we have an Hybrid App being tested on iOS which is using Cordova and has UIWEBView enabled. We wanted to work with the WebView instead of Native context, so we tried to switch the context. Now the real fun begins here.

On Local iOS Device, WebView is not returned but following the steps from https://github.com/appium/appium/issues/9599 mentioned by @MaxDomash, "If I manually start device's Safari then webviews are visible.", we were able to get the WebView.

On BrowserStack, cloud service which uses factory reset real devices, WebView is returned on first execution and then on subsequent executions WebView is not returned.

## Environment
* Appium version (or git revision) that exhibits the issue: Local - 1.70.,1.8.0,19.1,1.11.0-beta.3 ... BrowserStack - 1.6.5, 1.7.0 (default), 1.7.1, 1.7.2, 1.8.0, 1.9.1 
* Desktop OS/version used to run Appium: MAcBook Pro, Mojave/High Sierra
* Node.js version (unless using Appium.app|exe): v10.12.0
* Mobile platform/version under test: iPhone 6, 6s Plus, 7/ iOS 11,11.3,12.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI
* Xcode version: 9.4.1 and 10.1

## Link to Appium logs

Complete Appium (Local Device + BrowserStack) Logs - https://gist.github.com/MarvelCoder/ce332c97084802a47b960e4ffbffb421

**Comment by mykola-mokhnach** [comment]
Please fill out the necessary information and provide the full server log. 

Did you try to detect the webview by just using IWDP tool from the terminal? Did it work?

**Comment by MarvelCoder** [comment]
> Please fill out the necessary information and provide the full server log.
Provided the necessary information. 

> Did you try to detect the webview by just using IWDP tool from the terminal? Did it work?
Not sure how to check that but we did trigger this command, ios_webkit_debug_proxy -d to check if IWDP is having some issues, but it was working fine on local. Can't comment about BrowserStack.

**Comment by mykola-mokhnach** [comment]
> Not sure how to check that but we did trigger this command, ios_webkit_debug_proxy -d to check if IWDP is having some issues, but it was working fine on local.

IWDP allows to list active webviews from the terminal. Make sure it does show the one you need. 

> Can't comment about BrowserStack.

So it works on local, but does not work on BS? Why not to contact their support then?

**Comment by MarvelCoder** [comment]
> IWDP allows to list active webviews from the terminal. Make sure it does show the one you need.

Can you please tell me the steps/commands to achieve this. Many Thanks.

> So it works on local, but does not work on BS? Why not to contact their support then?

We just did get in touch with their support, and they were facing the same issue on their end as well. BS guys mentioned that they were using iProxy instead of IWDP. How different are these two ?

One more doubt, is it mandatory to trigger Safari before the App itself, to get Web_View as mentioned in https://github.com/appium/appium/issues/9599 ?

**Comment by mykola-mokhnach** [comment]
Visit https://github.com/google/ios-webkit-debug-proxy to read more details about what IWDP is and how to use it from the command line. Also we have the Appium forum, where one can ask howto questions.
