### ISSUE TITLE
Can not find TextField1

### ISSUE THREAD

**Issue by yihchu** [appium/appium#12103]
## The problem

I followed 'get start' and there is an error:
 message:
   'An element could not be located on the page using the given search parameters.',
  stacktrace:
   'NoSuchElementError: An element could not be located on the page using the given search parameters.\n    at AndroidUiautomator2Driver.helpers.findElOrEls (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/find.js:75:11)' }

I guess, the apk was updated

## Environment

* Appium 1.10.1
* mac
* node 10.13
* npm
* android 7.0, Galaxy A8
* Real device:

## Code To Reproduce Issue [ Good To Have ]

just the 'get start'

**Comment by mykola-mokhnach** [comment]
Kindly use Appium forum to ask questions. This is the place for issues.
