### ISSUE TITLE
Edited: LogEntries output printed to File is Empty when getting Driver.manage.logs.get("server") when Not Available

### ISSUE THREAD

**Issue by InvisibleExo** [appium/appium#12115]
## The problem

LogEntries collected from Appium Server, then printed to file show the text file empty after flushing the printer.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Desktop OS/version used to run Appium: 1.8.1
* Node.js version (unless using Appium.app|exe): Non-default server
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Emulatoer

## Details

I've been trying to set up a Capture Logs Systems so it can be easy to retrieve issues from test fails and capture stack traces and server logs from Appium to Help get a better picture without having to scroll up and down Appium server during runs. (Edit): Sometimes I see Server as an available logtype: [logcat, bugreport, server, client], and other runs I don't see the logs: [browser, driver, client]
Appium logs have been updated.
If more information is required to help piece it together, please let me know.

## Link to Appium logs

Logs Shown in Appium Server when not an Available Log Type:  https://gist.github.com/InvisibleExo/7369d512108e0c43e90b69a503f49874

Logs Shown in Appium Server when Server is an Available Log Type:
https://gist.github.com/InvisibleExo/03eb25b9f19f9f6a936e03d44f459dfa

## Code To Reproduce Issue [ Good To Have ]
Java Class to Print to File Server Logs: https://gist.github.com/InvisibleExo/f20b5c5c11257139f1366d9e459dde79

Java Class when setting up AppiumDrivers: https://gist.github.com/InvisibleExo/1d62c90f819e6beee73baeb6e63b0ff2

Edits: 
Java Class which causes the issue: 
https://gist.github.com/InvisibleExo/437ad22fcd47ecb767451fa463679db1

Issue 

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
> [MJSONWP] Encountered internal error running command: Error: Appium server must have relaxed security flag set in order to be able to get server logs


What exactly is not clear with the exception?

**Comment by InvisibleExo** [comment]
@mykola-mokhnach thank you for pointing that out. When I was looking into the cause of my problem, there wasn't much mention about the security flags to be set to relaxed as the solution. Now adding: --relaxed-security to my remote server,  resolves the issue  if it's one of the available logs. However, I've noticed that the server logs or the logcat logs aren't always  there when I check the available logs.  

When it exists my server logs exists I get these available logtypes: 
[logcat, bugreport, server, client]
When it doesn't exist as an available log type:
[browser, driver, client]

I'll update the server when server logs are an available log type and when they're not.

**Comment by mykola-mokhnach** [comment]
The feature to retrieve server logs has been added not so long ago, so make sure the server version is up to date. 

Also, the current logic only returns the actual delta since the last getLog call instead of the full records set. Check https://appiumpro.com/editions/53 for more details.

**Comment by InvisibleExo** [comment]
@mykola-mokhnach what is the latest server version to support  retrieving server logs?  I've updated  to appium version 10.1 and npm v is 6.4.1 and I'm not seeing a consistency with server logs available. Are there conditions that I'm not considering when the available logs  are either [logcat, bugreport, server, client]  or [browser, driver, client]? Different view contexts?

**Comment by mykola-mokhnach** [comment]
The recent Appium versions only support Node 8+

Yes, you must be in native context in order to be able to retrieve the server logs
