### ISSUE TITLE
Explore Lerna for package management

### ISSUE THREAD

**Issue by imurchie** [appium/appium#12113]
We currently use [packweb](https://github.com/appium/packweb) to do basic package management. There is much more that can be done, and perhaps [lerna](https://github.com/lerna/lerna) can fulfill some of our needs?

**Comment by christian-bromann** [comment]
@imurchie I definitely recommend Lerna. We have used it successfully in the WebdriverIO project. I am happy to show you the setup if you want.

**Comment by mykola-mokhnach** [comment]
Lerna is currently being used to manage Appium2 monorepo
