### ISSUE TITLE
cannot able to validate appium version while installing through cmd prompt

### ISSUE THREAD

**Issue by rajkumar-cp** [appium/appium#12118]
## The problem

While installation appium was installed successfully without any issue but when i tried to check the appium version installed it throws the below error

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0 (not sure)
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macos

## Code To Reproduce Issue [ Good To Have ]

mactestautomationlap:desktop deva$ appium -v

/usr/local/lib/node_modules/appium/build/lib/main.js:35

async function preflightChecks(parser, args, throwInsteadOfExit = false) {

      ^^^^^^^^

SyntaxError: Unexpected token function

    at createScript (vm.js:56:10)

    at Object.runInThisContext (vm.js:97:10)

    at Module._compile (module.js:542:28)

    at Object.Module._extensions..js (module.js:579:10)

    at Module.load (module.js:487:32)

    at tryModuleLoad (module.js:446:12)

    at Function.Module._load (module.js:438:3)

    at Module.runMain (module.js:604:10)

    at run (bootstrap_node.js:393:7)

    at startup (bootstrap_node.js:150:9)

mactestautomationlap:desktop deva

Could you please let me know how to resolve this issue.

I am able to locate this file in my machine : /usr/local/lib/node_modules/appium/build/lib/main.js:35

**Comment by mykola-mokhnach** [comment]
What is Nodejs version on the machine?

**Comment by rajkumar-cp** [comment]
node version : 6.10.2
npm version : 6.2.0

**Comment by mykola-mokhnach** [comment]
Only Node v. 8+ is supported
