### ISSUE TITLE
I have installed Appium desktop version 1.10.0 and connected the android device. I am getting error as access denied.

### ISSUE THREAD

**Issue by Lalithkumar30** [appium/appium#12120]
## The problem

I have installed Appium desktop version 1.10.0 and connected the android device. I am getting error as access denied.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 7
* Node.js version (unless using Appium.app|exe): 
* Npm or Yarn package manager:
* Mobile platform/version under test: 8.0.0
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Details

 Have node js installed. On clicking the start server. I am getting below error.

I have given follow Desired capabilities

{
  "deviceName": "Galaxy Note8",
  "udid": "x",
  "platformName": "Android",
  "platformVersion": "8.0.0",
  "appPackage": "com.xxx.xxx.xxxxx",
  "appActivity": "com.xxxx.xxx.xx"
}

## Link to Appium logs

<html>
 
 <head><title>Warning: Access Denied</title><meta name="description" content="Access Denied"></head>
 <blockquote><body bgcolor="white"><center>
 
 
 
 <script type="text/javascript"">
 var StatusCode = 401;
 if ((StatusCode>=300 && StatusCode<=400) || (StatusCode==404) || (StatusCode>=407 && StatusCode<=410) || (StatusCode==412) || (StatusCode==416) || (StatusCode==417) || (StatusCode>=500 && StatusCode<=504) || (StatusCode>=506 && StatusCode<=599))
 {
 document.write("<img width=\"100%\" src=\"http://proxypac.nam.nsroot.net/data/Exception_AccessFailed.jpg\"/>");
 }
 else if ((StatusCode==401) || (StatusCode==403) || (StatusCode==405) || (StatusCode==406) || (StatusCode==411) || (StatusCode>=413 && StatusCode<=415) || (StatusCode==505))
 {
 document.write("<img width=\"100%\" src=\"http://proxypac.nam.nsroot.net/data/Exception_AccessDenied.jpg\"/>");
 }
 else
 {
 document.write("<img width=\"100%\" src=\"http://proxypac.nam.nsroot.net/data/Exception_Error.jpg\"/>");
 }
 </script>
 
 
 
 <h3><br><font face="Helvetica" color="red">
 <script type="text/javascript"">
 var StatusCode = 401;
 if ((StatusCode==401) || (StatusCode==403) || (StatusCode>=405 && StatusCode<=406) || (StatusCode==411) || (StatusCode>=413 && StatusCode<=415) || (StatusCode==505))
 {
 document.write("YOUR ATTEMPT TO ACCESS FOLLOWING WEBSITE HAS BEEN DENIED:");
 }
 else if (StatusCode==305)
 {
 document.write("Your attempt to access the following website has been blocked as it has not been accessed by Citi before and has an unknown threat profile.");
 }
 else
 {
 document.write("YOUR ATTEMPT TO ACCESS FOLLOWING WEBSITE HAS FAILED:");
 }
 </script>
 </font><br><font face="Helvetica" color="black">&nbsphttp://localhost:4723/wd/hub/session</font><br><br>
 <font face="Helvetica" color="blue" size="4">Your credentials could not be authenticated: "Credentials are missing.". You will not be permitted access until your credentials can be verified.</font>
 </h3>
 
 
 
 <p><table style="border:solid lightblue;" bgcolor="#F8FFFF"><font face="Helvetica" color="black"><i><TR>
 <TD>URL in question is categorized as:</TD><TD>none</TD><TR>
 <TD>Exception that triggered the event:</TD><TD>authentication_failed</TD><TR>
 <TD>Your IP address has been recorded as:</TD><TD>10.120.48.51</TD><TR>
 <TD>Your user ID has been recorded as:</TD><TD>/</TD><TR>
 <TD>Proxy used for this connection:</TD><TD>wusgtdc-cxc01-900:8080</TD>
 </font></table></p>
 
 
 
 <br><font face="Helvetica" color="black">This is typically caused by an incorrect username and/or password, but could also be caused by network problems.</font>

**Comment by mykola-mokhnach** [comment]
Please attach the proper log
