### ISSUE TITLE
autoGrantPermissions does not seem to work for receiving push notifications

### ISSUE THREAD

**Issue by isabelavieira** [appium/appium#12124]
## The problem

autoGrantingPermissions does not seem to work for receiving push notifications.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable): not sure
* Desktop OS/version used to run Appium: MacOS X Mojave
* Node.js version (unless using Appium.app|exe): v8.11.3
* Npm or Yarn package manager: 5.6.0
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

## Details

When we set autoGrantPermissions = true on our configuration push notifications are not received by the device. If we set it to false and manually accept the Location (yes, Location!) permission popup during app initialization, everything works fine.

## Link to Appium logs

Appium log for autoGrantPermission true
<script src="https://gist.github.com/isabelavieira/c63450aff1233bf0b3ffdf20f72193a4.js"></script>

Appium log for autoGrantPermission false and manually accept the Location permission
<script src="https://gist.github.com/isabelavieira/a1ef1f849ba35ce5bb9fb81b35aba821.js"></script>

**Comment by mykola-mokhnach** [comment]
> [debug] [35m[ADB][39m Running '/Users/isabelavieira/Library/Android/sdk/platform-tools/adb -P 5037 -s 52034bd25010b3d7 shell pm grant br.com.oi.tecnicovirtual android.permission.WRITE_EXTERNAL_STORAGE \; pm grant br.com.oi.tecnicovirtual android.permission.ACCESS_COARSE_LOCATION \; pm grant br.com.oi.tecnicovirtual android.permission.ACCESS_FINE_LOCATION \; pm grant br.com.oi.tecnicovirtual android.permission.READ_PHONE_STATE \; pm grant br.com.oi.tecnicovirtual android.permission.READ_APP_BADGE \; pm grant br.com.oi.tecnicovirtual android.permission.READ_EXTERNAL_STORAGE \;'

These are permissions that are detected and granted by Appium. I see the location permission is there. 

`com.google.android.c2dm.permission.RECEIVE` permission is a "normal" one and does not need to be granted explicitly. 

Please check it with the application developer if anything else needs to be done in the command line in order to enable push notifications for the app.

**Comment by isabelavieira** [comment]
Thanks for the quick answer @mykola-mokhnach !

Which command line do you refer? Android build command line or Appium command line?
The behaviour only happens when we are driving the app through Appium. The same apk works fine (push notifications are received) if we manually accept the Location permission prompt during app initialization.

**Comment by mykola-mokhnach** [comment]
> Which command line do you refer? Android build command line or Appium command line?

I'm taking about `adb shell`. There's no magic there. Appium simply executes a set of adb commands to grant the permissions the app requests from the system. You could repeat the same set of actions manually via terminal and then compare the actual application state with its state while manual testing is being performed. Like I said above developers could help there by adding more debug logging into the app.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by vinigomescunha** [comment]
I'm having the same problem, appium does not grant permission to push notifications

npm run appium -- -p 4723 -bp 4733 --default-capabilities deviceConfig.json

deviceConfig.json
{
                udid": "NC4L2A0049",
                "app": "/home/vinicius/apks/android-debug.apk", 
                "automationName": "UiAutomator2",
                "platformName": "Android",
                "autoGrantPermissions": true,
                "platformVersion": "6.0",
                "fullReset": false,
                "noReset": false,
                "deviceName": "MotoG3",
                "noSign": true
}

When appium opens the application, I need to click to accept the permissions to work.

Appium version:  1.9.1

**Comment by mykola-mokhnach** [comment]
@vinigomescunha Sorry, but we cannot help nothing without the detailed problem description. At first the detailed server log is needed. Also it will be necessary to check the `add dumpsys package` output for different app states.

**Comment by vinigomescunha** [comment]
The problem was solved by upgrading appium from version 1.9.1 to 1.11.0 and factory reset on test phones.

**Comment by sumeetglobalstep** [comment]
Getting the same issue with Appium v1.15

Push Notifications aren't received on the device until Appium session is closed.
