### ISSUE TITLE
In Appium 1.10.0 version,Not able to Inspect elements in IOS Native Reacts apps

### ISSUE THREAD

**Issue by arshamirpeta** [appium/appium#12126]
## The problem

When I launch the app from appium and try to Inspect, Screen takes as one element and cannot able to inspect individually.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.101.1 
<img width="1082" alt="screen shot 2019-02-05 at 3 54 09 pm" src="https://user-images.githubusercontent.com/43751855/52303555-4dc60b00-295e-11e9-8cad-994f50728518.png">

**Comment by mykola-mokhnach** [comment]
There is nothing that can be done on Appium side. Try to change the context to [WEBVIEW](http://appium.io/docs/en/writing-running-appium/web/hybrid/)
