### ISSUE TITLE
Test execution get freeze with Android 9 and using Appium 1.9.1 with UIAutomator2

### ISSUE THREAD

**Issue by githubdilip** [appium/appium#12122]
## The problem

I am using Appium 1.9.1 version to automate Android native app. With Android version 5 to 8, i don't face any issue in execution. With Android 9 the test execution is starting, but in the middle it get stuck and it get freeze. No errors shown in logs. Kindly assist to get it resolved

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1 with android 9
* Last Appium version that did not exhibit the issue (if applicable): New issue
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): v8.11.3
* Npm or Yarn package manager:
* Mobile platform/version under test: Android
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe:Both

## Details

Capabilities:
[Appium]   udid: xxxxx
[Appium]   platformName: android
[Appium]   version: 9
[Appium]   appActivity: com.xx.xxx.xxxx
[Appium]   appPackage: com.xx.xxx
[Appium]   autoDismissAlerts: true
[Appium]   automationName: uiAutomator2
[Appium]   deviceName: xxxxxxx
[Appium]   fullReset: false
[Appium]   newCommandTimeout: 0
[Appium]   noReset: true
[Appium]   platformVersion: 9
[Appium]   systemPort: 8200

**Comment by githubdilip** [comment]
After some time of freeze getting error as "[debug] [W3C (088caa01)] Calling AppiumDriver.findElement() with args: ["id","android:id/progress","088caa01-94a4-47fe-8c07-25e2da782239"]
[JSONWP Proxy] Got an unexpected response: {"code":"ESOCKETTIMEDOUT","connect":false}"

**Comment by mykola-mokhnach** [comment]
1. Try Appium@beta
2. Please attach both the logcat and the server logs for the moment when the freeze happens

**Comment by githubdilip** [comment]
@mykola-mokhnach I have tried with appium@beta , the test are failing unexpedly and with appium 1.10, the script get freeze PFB the server log:

[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8200/wd/hub/session/31e62dcb-67fd-4224-bbc5-9a7d2272971f/element] with body: {"strategy":"id","selector":"com.xxx.xxx.android.int:id/textViewHeading","context":"","multiple":false}
[JSONWP Proxy] Got an unexpected response: {"sessionId":"31e62dcb-67fd-4224-bbc5-9a7d2272971f","status":7,"value":"An element could not be located on the page using the given search parameters."}
[debug] [MJSONWP] Matched JSONWP error code 7 to NoSuchElementError
[debug] [W3C (66221f0f)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[debug] [W3C (66221f0f)]     at AndroidUiautomator2Driver.helpers.findElOrEls (C:\Users\XXXX\AppData\Roaming\npm\node_modules\appium\node_modules\appium-android-driver\lib\commands\find.js:75:11)
[debug] [W3C (66221f0f)]     at <anonymous>
[HTTP] <-- POST /wd/hub/session/66221f0f-7c64-4c02-9878-b6cd6e3ca92f/element 404 938 ms - 449
[HTTP]
[HTTP] --> POST /wd/hub/session/66221f0f-7c64-4c02-9878-b6cd6e3ca92f/element
[HTTP] {"using":"id","value":"com.xxx.xxx.android.int:id/textViewHeading"}
[debug] [W3C (66221f0f)] Calling AppiumDriver.findElement() with args: ["id","com.xxx.xxx.android.int:id/textViewHeading","66221f0f-7c64-4c02-9878-b6cd6e3ca92f"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Matched '/element' to command name 'findElement'
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8200/wd/hub/session/31e62dcb-67fd-4224-bbc5-9a7d2272971f/element] with body: {"strategy":"id","selector":"com.xxx.xxx.android.inte:id/textViewHeading","context":"","multiple":false}
[HTTP] <-- POST /wd/hub/session/66221f0f-7c64-4c02-9878-b6cd6e3ca92f/element - - ms - -
[HTTP]
[HTTP] --> POST /wd/hub/session/66221f0f-7c64-4c02-9878-b6cd6e3ca92f/element
[HTTP] {"using":"id","value":"com.xxx.xxx.android.int:id/textViewHeading"}
[debug] [W3C (66221f0f)] Calling AppiumDriver.findElement() with args: ["id","com.xxx.xxx.android.inte:id/textViewBulletItem","66221f0f-7c64-4c02-9878-b6cd6e3ca92f"]

**Comment by mykola-mokhnach** [comment]
I need the full log along with logcat output
