### ISSUE TITLE
Appium can't find java version

### ISSUE THREAD

**Issue by nsalin** [appium/appium#12125]
## The problem

I cannot run Android test using the latest appium version.

## Environment

* Appium version - 7.0.0
* Selenium version - 3.141.5
* Desktop OS/version used to run Appium: v1.10.0
* Node.js version : 6.5.0
* Mobile platform/version under test: Android 8.0.0
* Real device or emulator/simulator: Real device

## Details

When I try to run the test class Appium seems to can't get the java version

## Link to Appium logs

https://gist.github.com/nsalin/068ffad5ea4c264c929cb81c483f9859
Appium desktop logs:
https://gist.github.com/nsalin/58b5960f4e97723b7067651fbc99f3e0

Big thanks

**Comment by nsalin** [comment]
I got the same error using the UIAutomator2 and appium@beta

**Comment by nsalin** [comment]
My JAVA_HOME path is  like this in the .bash_profile file
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_201.jdk/Contents/Home
export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$MAVEN_HOME:$ANT_HOME:$JAVA_HOME/bin

**Comment by mykola-mokhnach** [comment]
Make sure the variable is set properly for the appium process. Also, I would be happy to see the updated log

**Comment by nsalin** [comment]
https://gist.github.com/nsalin/9adcc0ca0a3f7cc8ee705d766de863cd

**Comment by mykola-mokhnach** [comment]
Are you sure it's the beta version? The recent UIA2 driver version is 1.28.1

**Comment by nsalin** [comment]
The problem was solved, big thanks. Yes it was the latest, but idk why the Appium Desktop is using other UIA2 driver version than the one which is installed via npm. I've started the appium server on command line and it worked. I couldn't see that without your help, big thanks
