### ISSUE TITLE
SessionNotCreatedError: A new session could not be created. Details: Appium's IosDriver does not support Xcode version 9.1. Apple has deprecated UIAutomation. Use the "XCUITest" automationName capability instead.

### ISSUE THREAD

**Issue by stranger2you** [appium/appium#12131]
## The problem

SessionNotCreatedError: A new session could not be created. Details: Appium's IosDriver does not support Xcode version 9.1. Apple has deprecated UIAutomation. Use the "XCUITest" automationName capability instead.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 10.14 (18A391)
* Node.js version (unless using Appium.app|exe): v11.8.0
* Npm or Yarn package manager: 6.7.0
* Mobile platform/version under test: iOS/ 10.2
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: appium desktop

## Details

same error noticed with Xcode 10.1. So downgraded to 9.1
## Link to Appium logs

[info] [35m[Appium][39m Welcome to Appium v1.10.0
[info] [35m[Appium][39m Appium REST http interface listener started on 0.0.0.0:4723[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{"desiredCapabilities":{"app":"/Users/macbookpro/eclipse-workspace/CCWMobileTest/Smart Track.app","bundleId":"com.launchship.DevSTTest","session-override":"true","deviceName":"iPhone 6)","platform":"MAC","newCommandTimeout":20000,"VERSION":"10.2","automationName":"XCUITest)","autoGrantPermissions":true,"platformName":"iOS","udid":"DE54FB19-617C-452F-9C1F-78EFE8261C71","noResetValue":"false"},"capabilities":{"firstMatch":[{"VERSION":"10.2","appium:app":"/Users/macbookpro/eclipse-workspace/CCWMobileTest/Smart Track.app","appium:autoGrantPermissions":true,"appium:automationName":"XCUITest)","appium:bundleId":"com.launchship.DevSTTest","appium:deviceName":"iPhone 6)","appium:newCommandTimeout":20000,"noResetValue":"false","platform":"MAC","platformName":"ios","session-override":"true","appium:udid":"DE54FB19-617C-452F-9C1F-78EFE8261C71"}]}}[39m
[debug] [35m[W3C][39m Calling AppiumDriver.createSession() with args: [{"app":"/Users/macbookpro/eclipse-workspace/CCWMobileTest/Smart Track.app","bundleId":"com.launchship.DevSTTest","session-override":"true","deviceName":"iPhone 6)","platform":"MAC","newCommandTimeout":20000,"VERSION":"10.2","automationName":"XCUITest)","autoGrantPermissions":true,"platformName":"iOS","udid":"DE54FB19-617C-452F-9C1F-78EFE8261C71","noResetValue":"false"},null,{"firstMatch":[{"VERSION":"10.2","appium:app":"/Users/macbookpro/eclipse-workspace/CCWMobileTest/Smart Track.app","appium:autoGrantPermissions":true,"appium:automationName":"XCUITest)","appium:bundleId":"com.launchship.DevSTTest","appium:deviceName":"iPhone 6)","appium:newCommandTimeout":20000,"noResetValue":"false","platform":"MAC","platformName":"ios","session-override":"true","appium:udid":"DE54FB19-617C-452F-9C1F-78EFE8261C71"}]}]
[debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1549450286217 (16:21:26 GMT+0530 (IST))
[warn] [35m[BaseDriver][39m The capabilities ["VERSION","noResetValue","platform","session-override"] are not standard capabilities and should have an extension prefix
[info] [35m[Appium][39m Could not parse W3C capabilities: 'automationName' XCUITest) not part of Appium,Selendroid,UiAutomator2,XCUITest,YouiEngine,Espresso,Tizen,Fake
[info] [35m[Appium][39m Trying to fix W3C capabilities by merging them with JSONWP caps
[warn] [35m[BaseDriver][39m The capabilities ["VERSION","noResetValue","platform","session-override","app","autoGrantPermissions","automationName","bundleId","deviceName","newCommandTimeout","udid"] are not standard capabilities and should have an extension prefix
[warn] [35m[Appium][39m Could not parse fixed W3C capabilities: 'automationName' XCUITest) not part of Appium,Selendroid,UiAutomator2,XCUITest,YouiEngine,Espresso,Tizen,Fake. Falling back to JSONWP protocol
[info] [35m[Appium][39m Creating new IosDriver (v2.13.2) session
[info] [35m[Appium][39m Capabilities:
[info] [35m[Appium][39m   app: /Users/macbookpro/eclipse-workspace/CCWMobileTest/Smart Track.app
[info] [35m[Appium][39m   bundleId: com.launchship.DevSTTest
[info] [35m[Appium][39m   session-override: true
[info] [35m[Appium][39m   deviceName: iPhone 6)
[info] [35m[Appium][39m   platform: MAC
[info] [35m[Appium][39m   newCommandTimeout: 20000
[info] [35m[Appium][39m   VERSION: 10.2
[info] [35m[Appium][39m   automationName: XCUITest)
[info] [35m[Appium][39m   autoGrantPermissions: true
[info] [35m[Appium][39m   platformName: iOS
[info] [35m[Appium][39m   udid: DE54FB19-617C-452F-9C1F-78EFE8261C71
[info] [35m[Appium][39m   noResetValue: false
[debug] [35m[BaseDriver][39m Creating session with MJSONWP desired capabilities: {"app":"/Users/macbookpro/e...
[warn] [35m[BaseDriver][39m The following capabilities were provided, but are not recognized by appium: session-override, platform, VERSION, autoGrantPermissions, noResetValue.
[info] [35m[BaseDriver][39m Session created with session id: 25eebb98-1308-4d62-9bc9-7bfd2b9731a8
[debug] [35m[iOS][39m Xcode version set to 9.1
[error] [35m[iOS][39m SessionNotCreatedError: A new session could not be created. Details: Appium's IosDriver does not support Xcode version 9.1. Apple has deprecated UIAutomation. Use the "XCUITest" automationName capability instead.
[error] [35m[iOS][39m     at IosDriver.createSession (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-ios-driver/lib/driver.js:129:28)
[error] [35m[iOS][39m     at process._tickCallback (internal/process/next_tick.js:68:7)
[debug] [35m[BaseDriver][39m Event 'newSessionStarted' logged at 1549450286226 (16:21:26 GMT+0530 (IST))
[debug] [35m[MJSONWP][39m Encountered internal error running command: SessionNotCreatedError: A new session could not be created. Details: Appium's IosDriver does not support Xcode version 9.1. Apple has deprecated UIAutomation. Use the "XCUITest" automationName capability instead.
[debug] [35m[MJSONWP][39m     at IosDriver.createSession (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-ios-driver/lib/driver.js:129:28)
[debug] [35m[MJSONWP][39m     at process._tickCallback (internal/process/next_tick.js:68:7)
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[31m500[39m [90m11 ms - 243[39m
[info] [35m[HTTP][39m [90m[39m

## Code To Reproduce Issue [ Good To Have ]
public class CCW_iOSPOC {
	IOSDriver<?> driver;
	 

	@SuppressWarnings("rawtypes")
	@BeforeClass
	public void LaunchApp() throws InterruptedException {
				
		File src = new File("/Users/macbookpro/eclipse-workspace/CCWMobileTest");
		File app = new File(src, "Smart Track.app");
		
		DesiredCapabilities caps = new DesiredCapabilities();
		caps.setCapability("app", app.getAbsolutePath());
		caps.setCapability("platformName", "iOS");
                caps.setCapability("platform", "Mac");
		caps.setCapability("deviceName", "iPhone 6)");
		caps.setCapability("VERSION", "10.2");
		caps.setCapability("automationName", "XCUITest)");
		caps.setCapability("session-override","true"); 
		caps.setCapability("udid", "DE54FB19-617C-452F-9C1F-78EFE8261C71");
                 caps.setCapability("bundleId", "com.launchship.DevSTTest");
                 caps.setCapability("noResetValue","false"); 
		caps.setCapability("autoGrantPermissions", true);
		caps.setCapability("newCommandTimeout", 20000);
		
		try {
			driver = new IOSDriver(new URL("http://0.0.0.0:4723/wd/hub"), caps);
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}
	}

**Comment by mykola-mokhnach** [comment]
> 	caps.setCapability("automationName", "XCUITest)");
