### ISSUE TITLE
Webdriveragent runner is failing "Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted""

### ISSUE THREAD

**Issue by SoundaryaBhavanam** [appium/appium#12137]
## The problem

When i build WebDriverAgentRunner though xcode getting succeed response 
When i run appium on terminal like below able to run the tests 
* appium --nodeconfig /Applications/Tapsium/nodeconfig0.json -U UDID -p 4723 
* ios_webkit_debug_proxy -c UDID:27753 -d

When i run appium though jenkins via ssh connection throwing below error

xcodebuild[25407:107429] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted, NSUnderlyingError=0x7faf2472b840 {Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Test runner exited before starting test execution." UserInfo={NSLocalizedDescription=Test runner exited before starting test execution., NSLocalizedRecoverySuggestion=If you believe this error represents a bug, please attach the result bundle at /Users/mposlab/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Test-WebDriverAgentRunner-2019.02.07_17-02-07--0500.xcresult}}}
[35m[Xcode][39m 
[35m[Xcode][39m 
[35m[Xcode][39m Testing failed:
[35m[Xcode][39m 
[35m[Xcode][39m 	Command CodeSign failed with a nonzero exit code
[35m[Xcode][39m 	WebDriverAgentRunner-Runner.app (25722) encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted. Underlying error: Test runner exited before starting test execution.)
[35m[Xcode][39m ** TEST EXECUTE FAILED **
[35m[Xcode][39m 

 

## Environment

* Appium version (or git revision) that exhibits the issue: appium 1.10.0 and 1.10.1
* Last Appium version that did not exhibit the issue (if applicable):1.8.1

* Node.js version (unless using Appium.app|exe):v11.9.0

* Mobile platform/version under test:11.3 and 12.x
* Real device or emulator/simulator:real devices 

Xcode version Version 10.0  and above 

MAC OS : Mojave

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/SoundaryaBhavanam/fa49b293b9c3216d77d0fce741dace5d

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by SoundaryaBhavanam** [comment]
Some one can take a look ?

**Comment by mykola-mokhnach** [comment]
> [35m[Xcode][39m 	Command CodeSign failed with a nonzero exit code

This a problem with codesigning. Nothing we can help from Appium side.

**Comment by SoundaryaBhavanam** [comment]
This is something related To ssh connection

Not code sign in issue

Can you take a look ?

**Comment by mykola-mokhnach** [comment]
Check https://github.com/appium/appium/issues/10554

**Comment by SoundaryaBhavanam** [comment]
Thanks for reply, it’s working  fine when I add apple developer account in
code and wda as false .

**Comment by SoundaryaBhavanam** [comment]
don't close this issue until we get permanent solution.
