### ISSUE TITLE
Appium take to much to find and search for element in one certain view on Android 9

### ISSUE THREAD

**Issue by zuzeac** [appium/appium#12139]
## The problem

Appium take a lot of time to search for the indicated element in a view with a search bar and a list of items when Keyboard is shown. And then throws error.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.11.0-beta.3, 1.10.1, 1.9.1
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: MacOS Mojave 10.14
* Node.js version (unless using Appium.app|exe): 11.6.0
* Npm or Yarn package manager: 6.5
* Mobile platform/version under test: Pixel XL with Android 9
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Details
Scenario: I have a view from where I have to select an item from a list. There is also a search bar to search for specific item and select. When I user sendKeys() to this bar the result are not showing how it happens on Android 7/8. But I have to tap on it first and then send keys.
The problem appears when the keyboard is displayed in this view, it take a lot of time for Appium to execute the commands, tap, send keys, clear, tap and then send keys again.

On Android 7 and 8 with Appium 1.11.0-beta.3, 1.9.1, 1.10.1 everything works fine. Might be a Pie issue.

## Link to Appium logs
https://gist.github.com/zuzeac/6ed7eac98af6c52e731f8a2d32ae6dee

## Code To Reproduce Issue [ Good To Have ]

**Comment by mykola-mokhnach** [comment]
I don't think there's something to change on Appium side. I would try if this works with Espresso driver. Also, you could try alternative key input methods, like these that are described in https://appiumpro.com/editions/46 and https://appiumpro.com/editions/34

**Comment by zuzeac** [comment]
Hi @mykola-mokhnach 
I just tried with espresso driver, my dev team made me an app version so I can user espresso instrumentation.
But I run over other problems which may be from the espresso driver itself.
I need to click/ tap on an element from the tab bar but i get this error:

`[element.click()] Error response status: 10, StaleElementReference - An element command failed because the referenced element is no longer attached to the DOM. Selenium error: io.appium.espressoserver.lib.handlers.exceptions.StaleElementException: The cached element 8974de75-1dfc-450d-bc84-9ea091548d9c no longer exists in the Android View hierarchy. Try to find it using a locator. at io.appium.espressoserver.lib.model.Element.getCachedView(Element.java:147) at io.appium.espressoserver.lib.model.Element.getViewById(Element.java:91) at io.appium.espressoserver.lib.model.Element.getViewInteractionById(Element.java:81) at io.appium.espressoserver.lib.handlers.Click.handle(Click.java:36) at io.appium.espressoserver.lib.handlers.Click.handle(Click.java:31) at io.appium.espressoserver.lib.http.Router.route(Router.java:299) at io.appium.espressoserver.lib.http.Server.serve(Server.java:68) at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945) at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192) at java.lang.Thread.run(Thread.java:764)
`

I get same the error when I tried to use the driver in appium inspector and tried to use tap action on the element, though I have the element in the sourcePage.

**Comment by mykola-mokhnach** [comment]
> Try to find it using a locator. at

Do what the exception text suggests

**Comment by mykola-mokhnach** [comment]
I don't think there's more we can do on this issue. Closed as third party problem
