### ISSUE TITLE
Can't get PageSource or UiSelector().index(0) for Android emulator on Appium 1.10.0

### ISSUE THREAD

**Issue by bart-tricentis** [appium/appium#12138]
## The problem

The commands  driver.PageSource or androidDriver.FindElementByAndroidUIAutomator("new UiSelector().index(0)") timeout on Android emulators but work fine with real devices. 
On Appium 1.8.0 the same code works fine on all configurations.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0
* Last Appium version that did not exhibit the issue (if applicable): 1.8.0
* Desktop OS/version used to run Appium: Windows and Mac
* Node.js version (unless using Appium.app|exe): 7.7.3
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Android
* Real device or emulator/simulator: emulator (Nexus 9 API 27, Pixel C API 27)
* Appium CLI or Appium.app|exe: CLI

[log1100.txt](https://github.com/appium/appium/files/2844546/log1100.txt)
[log180.txt](https://github.com/appium/appium/files/2844544/log180.txt)

## Code To Reproduce Issue [ Good To Have ]

  AppiumDriver<IWebElement> driver = new AndroidDriver<IWebElement>(AndroidServerUri, capabilities);
  string source = driver.PageSource;
  AndroidDriver<IWebElement> androidDriver = driver as AndroidDriver<IWebElement>;
            RemoteWebElement window = (RemoteWebElement) androidDriver.FindElementByAndroidUIAutomator("new UiSelector().index(0)");

**Comment by mykola-mokhnach** [comment]
Can you also attach the logcat output?

**Comment by mykola-mokhnach** [comment]
> * Node.js version (unless using Appium.app|exe): 7.7.3
BTW the recent appium versions only support Node 8+

**Comment by mykola-mokhnach** [comment]
You could also try how it works with appium@beta

**Comment by bart-tricentis** [comment]
It doesn't work with appium@beta (even checked master branch from git and still nothing) 

I will try to get the logcat

**Comment by bart-tricentis** [comment]
And here it is
[logcat.txt](https://github.com/appium/appium/files/2851313/logcat.txt)

**Comment by mykola-mokhnach** [comment]
> ALL: 02-11 11:19:00.762 19173 19253 E AccessibilityInteractionClient: Duplicate node.

I can observe multiple errors like this in the log, which significantly slows down the `/source` call (took 896139ms for a simple tree). Although, I cannot say why such error is happening and whether it is possible workaround it. Maybe, only the person who wrote this piece of the Android system could say more about it.

**Comment by mykola-mokhnach** [comment]
Hopefully something could be fixed if one reports it as a bug to Google

**Comment by bart-tricentis** [comment]
And what about the FindElementByAndroidUIAutomator("new UiSelector().index(0)") ?? (logcat for this bellow) 
[logcat.txt](https://github.com/appium/appium/files/2854420/logcat.txt)

And sorry I don't get it how is it a google thing as I use the same Andorid device with appium 1.10 and 1.8 and the later works fine

**Comment by bart-tricentis** [comment]
Sorry to pile it up but FindElementById also timeouts like the others
[logcat.txt](https://github.com/appium/appium/files/2854673/logcat.txt)

**Comment by mykola-mokhnach** [comment]
> And sorry I don't get it how is it a google thing as I use the same Andorid device with appium 1.10 and 1.8 and the later works fine

A whole lot of things has been changed since Appium 1.8. Maybe there is some regression there, hoverer this regression happens inside the system code and I have no idea on how it affects the actual appium server codebase. I'll mark the problem as bug for now. Maybe, someone could find a better solution to it or at least point out on where to start the investigation.

**Comment by bart-tricentis** [comment]
This is not a bug and can be closed, after deeper investigation I found out that the problem was caused by the app under tests with a newer version (and with other apps) the problem doesn't exist.

Sorry for the commotion and thank you for the support.
