### ISSUE TITLE
Unable to start WebDriverAgent session because of xcodebuild failure using appium v.1.10.1

### ISSUE THREAD

**Issue by LayMuiToh** [appium/appium#12147]
## The problem

When running a webdriverio test on appium v.1.10, it fail with a error 
ERROR: An unknown server-side error occurred while processing the command. Original error: Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.

## Environment

* Appium version (or git revision) that exhibits the issue:1.10.1
* Last Appium version that did not exhibit the issue (if applicable):1.9.1
* Desktop OS/version used to run Appium:macOS High Sierra 10.13.6 
* Node.js version (unless using Appium.app|exe):v10.15.1
* Npm or Yarn package manager:6.4.1
* Mobile platform/version under test:iOS 12.1 
* Real device or emulator/simulator:real device
* Appium CLI or Appium.app|exe:appium.exe

## Details
the webdriverAgentLib and Runner are build with code signing successfully at xcode IDE
and the xcodebuild command is also run successfully to install the WDA to the real device:
 xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=a12510a8c8ec79876d8e10f38da17fb97dc720c3' test

## Link to Appium logs

https://gist.github.com/LayMuiToh/238c7aafe96e2b85c46b02c1944b8399

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Please provide the log with xcodebuild and device logging enabled

**Comment by LayMuiToh** [comment]
thanks mykola. this is ok now :)
