### ISSUE TITLE
iOS simulator hangs after changing language capability

### ISSUE THREAD

**Issue by nkns165** [appium/appium#12144]
## The problem

We have a problem when we try to switch `language` capability in iOS simulator.  When we create and quit a session in one language and then create a session again in another language, the simulator display hangs. For example when changed `language` from `en` to `ja`, the simulator screen is still in English and we cannot do any manipulation. 
While the appium test is executed fine in Japanese and we can even take screenshot, we cannot see any of these on the simulator display.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0
* Desktop OS/version used to run Appium: macOS mojave (10.14.2)
* Node.js version (unless using Appium.app|exe): v10.14.2
* Npm or Yarn package manager: npm 6.4.1
* Mobile platform/version under test: iOS 12.1
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium CLI (Appium.app also acts same)

## Details

- If we shut down the simulator process manually after the first session, the problem doesn't happen.
- Even when the problem happens the simulator dialog once disappears and appears again, but the process doesn't seem to be rebooted.

## Link to Appium logs

[appium log](https://gist.github.com/nkns165/60083e0d0ab5c34b99f0288acf7a0d40)

## Code To Reproduce Issue [ Good To Have ]

[ios-change-languages.test.js](https://gist.github.com/nkns165/9212e41a50ab7e424c7556b9728e9472)

I cloned https://github.com/appium/appium and put this code under `sample-code/javascript-webdriver/io/test/basic`.
After the test passed, you can see the simulator is frozen.

**Comment by mykola-mokhnach** [comment]
Might be a duplicate of https://github.com/appium/appium/issues/11621

**Comment by nkns165** [comment]
@mykola-mokhnach You're right, thank you!
