### ISSUE TITLE
Unable to interact into the element in browser web page when coming back from the App

### ISSUE THREAD

**Issue by logakarthi** [appium/appium#12140]
## The problem

Unable to interact into the web page elements in the mobile browser when coming back from the App. My web page SignUp Elements are found well, but it enters the input in email field only and then automatically exit from the browser and redirects to the app.

"NoSuchElementError" exception throws, but the elements are found well in the page.

Please anyone help me to resolve this issue. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0
* Last Appium version that did not exhibit the issue (if applicable): 1.7.3
* Desktop OS/version used to run Appium: MAC
* Mobile platform/version under test: Android 7.1.1
* Real device or emulator/simulator: Redmi 4

## Link to Appium logs
https://gist.github.com/logakarthi/1b9b60181b37c0724e5340b0e40cc5b9
****
## Code To Reproduce Issue [ Good To Have ]
public DesiredCapabilities setUpAppium() throws MalformedURLException {
final String URL_STRING = "http://127.0.0.1:4723/wd/hub";
        URL url = new URL(URL_STRING);
        //Use a empty DesiredCapabilities object
        DesiredCapabilities capabilities = new DesiredCapabilities();
        File appdir = new File("/Users/apple/Documents/AndroidiOSBuilds/GammaPracticeApp/3.9.0GA/");
        File app = new File(appdir, "CK12-debug-gamma-3.9.0.254815.apk");
        //capabilities.setCapability(CapabilityType.BROWSER_NAME, "Chrome");
        //capabilities.setCapability("automationName", "UIAutomator2");
        capabilities.setCapability("noReset", true);
        capabilities.setCapability("autoWebview", "true");
        capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 1000);
        capabilities.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
        capabilities.setCapability("autoLaunch", Boolean.parseBoolean("autolaunch"));
        capabilities.setCapability("autoLaunch", Boolean.parseBoolean(String.valueOf(true)));
        capabilities.setCapability(MobileCapabilityType.APP_ACTIVITY, "org.ck12.app.practice.MainActivity");
        capabilities.setCapability(MobileCapabilityType.APP_PACKAGE, "org.ck12.app.practice");
        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, MobilePlatform.ANDROID);
        capabilities.setCapability("recreateChromeDriverSessions", true);
        capabilities.setCapability("nativeWebTap", true);
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Nexus5"); // Moto E TA38500ME6
        capabilities.setCapability("chromedriverExecutable", "/Users/apple/Desktop/ChromeDriver/44/chromedriver");
        driver = new AndroidDriver<WebElement>(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
        driver.manage().timeouts().implicitlyWait(80, TimeUnit.SECONDS);
        try {
            Thread.sleep(15000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        switchToWebViewContext("NATIVE_APP");
        System.out.println("switching the context to native");
        try {
            if (driver.findElementById("com.android.packageinstaller:id/permission_allow_button").isDisplayed()) {
                driver.findElementById("com.android.packageinstaller:id/permission_allow_button").click();
            } else {
                System.out.println("Permission popup is not displayed");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        switchToWebViewContext("WEBVIEW");
        System.out.println(driver.getCurrentUrl());
        if (driver.findElement(By.cssSelector("a.sign-btn")).isDisplayed() && driver.findElement(By.cssSelector("span.join-btn-cont")).isDisplayed()) {
          System.out.println("Sign in & join buttons are appears");
        }
        //driver.runAppInBackground(50);
        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        driver.navigate().to("https://gamma.ck12.org/auth/signup?minimalUI=true&returnTo=https%3A%2F%2Fgamma.ck12.org%2Fauth%2Fverify%2Fapp%2Fmember%2Fck12app%3Ftoken%3Db1980577c502b2f36a7c6bb6f72f64d06a6e060b71f8cca6875aab2da4df17cc");
    try {
      Thread.sleep(5000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
        System.out.println(driver.getCurrentUrl());
    switchToWebViewContext("WEBVIEW");
    //switchToWebViewContext("NATIVE_APP");
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    //wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("div.js-signup-join-wrapper")));
        if (driver.findElement(By.cssSelector("div.js-signup-join-wrapper")).isDisplayed()) {
          driver.findElement(By.cssSelector("div.js-signup-join-wrapper div.signup-mail-container a.js-signup-email-button")).click();
          try {
            Thread.sleep(1000);
          } catch (InterruptedException e) {
            e.printStackTrace();
          }
          if (driver.findElement(By.cssSelector("#signup_student_form")).isDisplayed()) {
            if (driver.findElement(By.cssSelector("#name")).isDisplayed() && driver.findElement(By.cssSelector("#birthday")).isDisplayed() &&
                    driver.findElement(By.cssSelector("#email")).isDisplayed() && driver.findElement(By.cssSelector("#password")).isDisplayed()) {
              System.out.println("Signup fields are appears");
            }
          }
        }
                //System.out.println(driver.getPageSource());
               // driver.findElement(By.cssSelector("#name")).sendKeys("Practice App User");
                //driver.hideKeyboard();
                try {
                  Thread.sleep(1000);
                } catch (InterruptedException e) {
                  e.printStackTrace();
                }
                //driver.executeScript("document.getElementById('#birthday').setAttribute('value', '2000-09-12')");
                //driver.findElementByCssSelector("#birthday").sendKeys("2000-09-12");
                //driver.executeScript("arguments[0].setAttribute('value',arguments[1])", "#birthday", "2000-09-12");
                //driver.findElement(By.cssSelector("#signup_student_form div.signup-form-container div.birthdate-wrapper input.birthday-field")).sendKeys("2000-09-12");
                driver.hideKeyboard();
                driver.findElement(By.cssSelector("#email")).sendKeys("**********@gmail.com");
                driver.hideKeyboard();
                //switchToWebViewContext("WEBVIEW");
                driver.findElement(By.cssSelector("#password")).sendKeys("test1234");
                driver.hideKeyboard();
                //switchToWebViewContext("WEBVIEW");
            if (driver.findElement(By.cssSelector("#signup_form_submit")).isDisplayed()) {
              driver.findElement(By.cssSelector("#signup_form_submit")).click();
        }
    try {
      Thread.sleep(5000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    ((AndroidDriver) driver).startActivity("org.ck12.app.practice", "org.ck12.app.practice.MainActivity");
    try {
      Thread.sleep(3000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    switchToWebViewContext("NATIVE_APP");
    try {
      Thread.sleep(5000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    switchToWebViewContext("WEBVIEW");
    try {
      Thread.sleep(5000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    return capabilities;
  }

**Comment by mykola-mokhnach** [comment]
Use UiAutomator2 for Android 6+

**Comment by logakarthi** [comment]
Need "UiAutomator2" mention in the automationName. I'm correct?

**Comment by mykola-mokhnach** [comment]
http://appium.io/docs/en/drivers/android-uiautomator2/

**Comment by parul001** [comment]
> Need "UiAutomator2" mention in the automationName. I'm correct?

yes .
