### ISSUE TITLE
Appium 1.10.1 Deletes the .App from our Local Directory After Test Completion

### ISSUE THREAD

**Issue by benyetra** [appium/appium#12142]
## The problem

Since upgrading from 1.10.0 to 1.10.1 after every test run (no matter result, pass or fail) Appium will remove the .app build from the Local Directory where the test is being run. This is occurring on both Simulators and Real Devices. When tested on 1.9.1 and 1.10.1 this never occurs. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.1
* Last Appium version that did not exhibit the issue (if applicable): 1.10.0
* Desktop OS/version used to run Appium: macOS Mojave (10.14.2)
* Node.js version (unless using Appium.app|exe): 10.8.0
* Npm or Yarn package manager: 6.2.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Both Real Device and Simulator

## Details

Some extra details are that the app is not deleted from the device when it is being deleted from the local directory. 

## Link to Appium logs

Appium 1.10.0 Working Logs: https://gist.github.com/benyetra/8f7feff6af6418dd4c3b8a7837dc2a4a
Appium 1.10.1 Failing Logs: https://gist.github.com/benyetra/b4d4576b1e48ca5a413645ba67f6a614

**Comment by mykola-mokhnach** [comment]
Change to app path to absolute or use appium@beta

**Comment by imurchie** [comment]
This has been fixed, and will be in the next release.

**Comment by benyetra** [comment]
@mykola-mokhnach @imurchie thank you!
