### ISSUE TITLE
Appium is unable to locate and perform action in some of the elements using ID in Android 8 and higher version

### ISSUE THREAD

**Issue by Deepak-merahkee** [appium/appium#12146]
## The problem

I am trying to run an automation code on a android devices, as elements I am using IDs of the elements, The automation works fine in android 6 devices but when I run it in android 8 devices it is giving as unable to locate the elements exception. 

## Environment

* Appium version (or git revision) that exhibits the issue: Server v1.10.0 (I also tried with other versions but it is the same)
* Desktop OS/version used to run Appium: Windows
* Mobile platform/version under test: Android 8 version
* Real device or emulator/simulator: Real devices

## Details

I have created a automation scripts to run on android devices. For Every element I am using element ID, Whenever I run this script on android 6 version it is working fine but if Run it on android 8 the script is failing due unable to locate exception. Why is the code not running in android 8+ while it is running in 6- android versions.

## Link to Appium logs

https://docs.google.com/document/d/1nCnrbEr-WVfMSTg9S0YwxsKSuX7nCufgs-X3cDcnfNU/edit?usp=sharing

//I have just made bold and underlined the logs at the end where the script failing. look at the end of the logs

## Code To Reproduce Issue [ Good To Have ]
MobileElement  menu_icon = driver.findElement(By.id("com.aptener.blurydr:id/iv_menu"));
menu_icon.click();

**Comment by KazuCocoa** [comment]
[AndroidDriver] Consider setting 'automationName' capability to 'uiautomator2' on
Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.

What about specifying uia2 as the above message?

**Comment by Deepak-merahkee** [comment]
No I tried mentionin uia2 as below
capabilities.setCapability("automationName", "uia2");

Still the same issue is happening

**Comment by Deepak-merahkee** [comment]
Please open the issue because all of us are running with the same issue

**Comment by KazuCocoa** [comment]
You should call `capabilities.setCapability("automationName", "uiautomator2");` as the error message said. https://github.com/appium/appium/issues/12146#issuecomment-462247812

**Comment by Deepak-merahkee** [comment]
I was using the same capabilities.setCapability("automationName", "uiautomator2"); before, there also I faced the same issue

**Comment by KazuCocoa** [comment]
Could you share the log? (Hopefully, with gist)
Because the log of `uiautomator2` were different from non UIA2.
If you could, with adb log is prefered to understand the situation.

**Comment by wenbinke** [comment]
why this issue is closed? I am facing the same issue when run code with Android 8. I have tried both uiautomator and uiautomator2.

**Comment by mykola-mokhnach** [comment]
Sorry, but without the detailed log all these comments are useful and don't help even a little

**Comment by wenbinke** [comment]
I can see from the `client.getPageSource()` function, I noticed that some elements are missing on android 8.0.

**Comment by santhoshnanbans** [comment]
I am facing the same issue ,Not able to locate the element in the devices above android 8 .But works fine below version of android 8 .
