### ISSUE TITLE
npm install - g appium fails with "Unexpected token function"

### ISSUE THREAD

**Issue by VenkateshPS** [appium/appium#12145]
## The problem

npm install - g appium fails with "Unexpected token function"

Unable to import install script. Re-run `install appium-chromedriver` manually.

> appium-selendroid-driver@1.13.2 install /usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver
> node ./bin/install.js

/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/build/index.js:38
async function main() {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at doInstall (/usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/bin/install.js:18:26)
    at Object.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/bin/install.js:61:3)
/usr/local/lib
└── (empty)

npm ERR! Darwin 17.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "appium"
npm ERR! node v7.5.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! appium-selendroid-driver@1.13.2 install: `node ./bin/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium-selendroid-driver@1.13.2 install script 'node ./bin/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the appium-selendroid-driver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs appium-selendroid-driver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls appium-selendroid-driver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/venkateshsingh/npm-debug.log

## Environment

* Appium version (or git revision) that exhibits the issue: Latest
* Last Appium version that did not exhibit the issue (if applicable):1.7.2
* Desktop OS/version used to run Appium:High Siera 10.13.4
* Node.js version (unless using Appium.app|exe):v7.5.0
[npm-debug.log](https://github.com/appium/appium/files/2850101/npm-debug.log)

* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Only nodeJS v 8+ is supported in the recent Appium releases
