### ISSUE TITLE
How to access the WPF custom control's elements?

### ISSUE THREAD

**Issue by NeelakandanKannan** [appium/appium#12157]
## The problem
Our custom control is designed in drawing architecture. i.e. every elements in a control are drawn using DeviceContext's Draw methods. We are not arranging elements as UI elements. To provide the accessibility support, we have provided the **AutomationPeer** support for control (not inner elements). 

Can you please let us know how we can provide the testing support for inner elements to read using Appium?

We have tried the followings,

`
AutomationElement datagrid = desktop.FindFirst(TreeScope.Descendants, new PropertyCondition(AutomationElement.AutomationIdProperty, "gridControl"));

if (datagrid == null)
    Assert.Fail("GridControl is null");
else
{
     var pattern = datagrid1.GetCurrentPattern(GridPatternIdentifiers.Pattern) as GridPattern;
     var item = pattern.GetItem(1, 1);
     if (item != null)
     {
        object value = null;
        item.TryGetCurrentPattern(ValuePattern.Pattern, out value);
        var valueProvider = value as ValuePattern;
        var currentValue = valueProvider.Current.Value;
    }
}
`
_[AutomationElement](https://docs.microsoft.com/en-us/dotnet/api/system.windows.automation.automationelement?view=netframework-4.7.2)_ class provides support to access the inner elements. 

While trying to access the WPF custom control, i m getting the following exception,

`WindowsDriver<WindowsElement> session;  

var appiumOptions = new AppiumOptions();  

appiumOptions.AddAdditionalCapability("app", "ApplicationPath");   

session = new WindowsDriver<WindowsElement>(new Uri("http://127.0.0.1:4723"), appiumOptions);  

session.Manage().Timeouts().ImplicitWait = TimeSpan.FromMilliseconds(5000);  

WindowsElement element = session.FindElementByClassName("GridControl");  

session.Dispose();  
`
Exception details,

at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Appium.AppiumDriver`1.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.Appium.AppiumDriver`1.FindElementByClassName(String className)
   at UnitTestProject1.UnitTest1.TestMethod1() in GridControlDemo\UnitTestProject1\UnitTestProject1\UnitTest1.cs:line 37
Result Message:              
Test method UnitTestProject1.UnitTest1.TestMethod1 threw exception: 
OpenQA.Selenium.WebDriverException: An element could not be located on the page using the given search parameters.

As like the above methods, can we get any solution to read the inner elements?

## Environment

* WPF platform

**Comment by mykola-mokhnach** [comment]
Moving to dotnet driver

**Comment by mykola-mokhnach** [comment]
Please consider reporting your question to https://github.com/appium/appium-dotnet-driver

**Comment by NeelakandanKannan** [comment]
Reported to that section also. 
https://github.com/appium/appium-dotnet-driver/issues/312

**Comment by dpgraham** [comment]
https://github.com/Microsoft/WinAppDriver may also be a place to ask.

**Comment by NeelakandanKannan** [comment]
We are getting exception from Appium source. Can you please look onto this and provide the solution for this?

**Comment by dpgraham** [comment]
The exception `An element could not be located on the page using the given search parameters.` means that the locator passed to WinAppDriver didn't find an element.

**Comment by NeelakandanKannan** [comment]
@dpgraham  - Yes. Do you know anything behind reason for this? We need the solution.

**Comment by NeelakandanKannan** [comment]
Also, raised the question in WinAppDriver git,
https://github.com/Microsoft/WinAppDriver/issues/600

**Comment by dpgraham** [comment]
I don't, sorry. We don't maintain WinAppDriver
