### ISSUE TITLE
Not able to uninstall appium v 1.9.1

### ISSUE THREAD

**Issue by vijayasaiatyam** [appium/appium#12152]
Hi All,
I am on mac.

Appium v1.9.1 was installed in my machine. But on trying to uninstall appium version through terminal, its returning as up to date.

Also tried clearing npm cache using npm cache clean

GKs-MacBook-Pro:~ gku3mac011$ npm uninstall appium -g
up to date in 0.041s
GKs-MacBook-Pro:~ gku3mac011$

**Comment by mykola-mokhnach** [comment]
Does `npm list` show the package as installed?

**Comment by vijayasaiatyam** [comment]
GKs-MacBook-Pro:~ ggku3mac011$ npm list
/Users/ggku3mac011
└── (empty)

**Comment by mykola-mokhnach** [comment]
How about `npm list -g`?

**Comment by vijayasaiatyam** [comment]
@mykola-mokhnach 
npm list -g -> Also returned empty list.

This issue is resolved for me now.
Manually I could locate the Appium folder that still exists in my system. Deleted all the folders, and tried again this issue is resolved.
