### ISSUE TITLE
Appium is unable to automate the launcher app

### ISSUE THREAD

**Issue by Suban5** [appium/appium#12154]
## The problem

I am trying to automate the launcher app that is set as the default launcher. When i try to run the app from appium the launcher crashes. 

## Environment

* Appium version : 1.10.1
* Desktop OS/version used to run Appium: macOS mojave
* Mobile platform: android
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: Appium.app

**Comment by parul001** [comment]
@Suban5  your app is  can the cause of problem . Are you sure that app is working fine, if not then  can you more details or logs ?

**Comment by mykola-mokhnach** [comment]
Please attach the full server log
