### ISSUE TITLE
Appium causes ADB server to crash, and then be unable to find devices.

### ISSUE THREAD

**Issue by Jtech42** [appium/appium#12164]
## The problem

After starting a session in appium, a "could not proxy" error occurs after attempting a refresh, and then adb is killed and devices no longer appear in it even after restart. 

## Environment

Device is a Nexus 5x, attached computer is a Mac. Everything else is latest version.

## Link to Appium logs

Cant copy and paste these from the appium server window? The logs just shows appium killing the adb server over and over then complaining it can't find devices.

## Reproduction

Follow this guide for installing all the dependencies and packages and extra bits you need to get started -http://appium.io/docs/en/about-appium/getting-started/?lang=en

Start a server, start inspector, then refresh the view, then this issue occurs. 100% frequency of reproduction.

**Comment by mykola-mokhnach** [comment]
I cannot suggest nothing without the logs. Btw, there is `suppressKillServer` capability, which makes the driver not to execute kill-server on startup if set to `true`.
