### ISSUE TITLE
Android Driver creation fails with error appium-uiautomator2-server-v3.2.1.apk does not exist or is not accessible

### ISSUE THREAD

**Issue by VenkateshPS** [appium/appium#12166]
## The problem

Error: The file at path /usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.2.1.apk does not exist or is not accessible

## Environment

* Appium version (or git revision) that exhibits the issue: 1.11.1-rc.0
* Last Appium version that did not exhibit the issue (if applicable):1.11.0
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):v10.15.1
* Npm or Yarn package manager:
* Mobile platform/version under test:Android
* Real device or emulator/simulator:Real Device
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!
https://gist.github.com/VenkateshPS/1e78f858da322fbb17654b4f564bd70e

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by imurchie** [comment]
Can you show the contents of `/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks`?

**Comment by dpgraham** [comment]
Can you try with rc1? I fixed this.

**Comment by oivzhich** [comment]
@dpgraham , I'm experiencing similar issue with appium-uiautomator2-server-debug-androidTest.apk
System: Ubuntu 18.04.2 LTS
Java: 11.0.2
nodejs: v11.10.0
npm: 6.7.0
appium: 1.11.1-rc.1
Capabilities:
`maxDuration: 2000
[Appium]   platformName: android
[Appium]   app: our_app.apk
[Appium]   appPackage: com.coople.android.worker.debug
[Appium]   appWaitActivity: com.coople.android.worker.screen.*
[Appium]   autoGrantPermissions: true
[Appium]   automationName: UiAutomator2
[Appium]   clearSystemFiles: true
[Appium]   deviceName: Android
[Appium]   newCommandTimeout: 300
[Appium]   resetKeyboard: true
[Appium]   udid: ce07182754f76b0405
[Appium]   unicodeKeyboard: true`

`debug] [ADB] Running '/usr/lib/android-sdk/platform-tools/adb -P 5037 -s ce07182754f76b0405 forward --remove tcp\:8200'
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command '/usr/lib/android-sdk/platform-tools/adb -P 5037 -s ce07182754f76b0405 forward --remove tcp\:8200' exited with code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1550251480038 (20:24:40 GMT+0300 (Moscow Standard Time))
[debug] [W3C] Encountered internal error running command: Error: Could not sign with default certificate. Original error Command '/usr/lib/jvm/java-11-oracle/bin/java -jar /usr/lib/node_modules/appium/node_modules/appium-adb/jars/sign.jar /usr/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk --override' exited with code 1
[debug] [W3C]     at ADB.apkSigningMethods.signWithDefaultCert (/usr/lib/node_modules/appium/node_modules/appium-adb/lib/tools/apk-signing.js:124:13)
[HTTP] <-- POST /wd/hub/session 500 112282 ms - 1139`

**Comment by dpgraham** [comment]
@oivzhich what are the contents of `/usr/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/`?

**Comment by oivzhich** [comment]
@dpgraham 
`-rw-r--r-- 1 jenkins jenkins 0 Feb 15 20:21 1550251479348.tmp`
`-rw-rw-r-- 1 jenkins jenkins 2216912 Oct 26 1985 appium-uiautomator2-server-v3.2.2.apk`

**Comment by dpgraham** [comment]
Ahhh yes, you already posted that. My bad.

Were you able to confirm the before and after of this? That the debug APK was there when it was initially installed and then was deleted?

**Comment by dpgraham** [comment]
Another question @oivzhich ... does this problem happen with 1.11.0 as well?

**Comment by oivzhich** [comment]
@dpgraham 
Yes,
Steps:
1) re-installed appium 
`npm uninstall -g appium && npm i -g appium`
2) ls -l /usr/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/
`-rw-rw-r-- 1 jenkins jenkins  545600 Oct 26  1985 appium-uiautomator2-server-debug-androidTest.apk`
`-rw-rw-r-- 1 jenkins jenkins 2200616 Oct 26  1985 appium-uiautomator2-server-v3.1.1.apk`
3) Launching appium tests using Java11 and getting error:
`[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command '/usr/lib/android-sdk/platform-tools/adb -P 5037 -s ce07182754f76b0405 forward --remove tcp\:8200' exited with code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1550258706807 (22:25:06 GMT+0300 (Moscow Standard Time))
[debug] [W3C] Encountered internal error running command: Error: Could not sign with default certificate. Original error Command '/usr/lib/jvm/java-11-oracle/bin/java -jar /usr/lib/node_modules/appium/node_modules/appium-adb/jars/sign.jar /usr/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk --override' exited with code 1
[debug] [W3C]     at ADB.apkSigningMethods.signWithDefaultCert (/usr/lib/node_modules/appium/node_modules/appium-adb/lib/tools/apk-signing.js:124:13)`

4) Launching tests one more time and getting error
`[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command '/usr/lib/android-sdk/platform-tools/adb -P 5037 -s ce07182754f76b0405 forward --remove tcp\:8200' exited with code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1550258927866 (22:28:47 GMT+0300 (Moscow Standard Time))
[debug] [W3C] Encountered internal error running command: Error: /usr/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk file doesn't exist.
[debug] [W3C]     at ADB.apkSigningMethods.signWithDefaultCert (/usr/lib/node_modules/appium/node_modules/appium-adb/lib/tools/apk-signing.js:106:11)`

**Comment by dpgraham** [comment]
Moved this issue to https://github.com/appium/appium/issues/12180 since it's different from the originally reported issue.

**Comment by dpgraham** [comment]
@oivzhich do you mind sharing the Appium logs with me? I'd like to see where and why the .apk is getting deleted.
