### ISSUE TITLE
Android driver creation throws exception on Appium 1.11.0

### ISSUE THREAD

**Issue by VenkateshPS** [appium/appium#12162]
## The problem

Android Driver creation fails on Appium 1.11.0
 Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: java.lang.NullPointerException: Attempt to invoke virtual method 'io.appium.uiautomator2.model.AccessibilityScrollData io.appium.uiautomator2.mode

## Environment

* Appium version (or git revision) that exhibits the issue:1.11.0
* Last Appium version that did not exhibit the issue (if applicable):1.7.2
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):v10.15.1
* Npm or Yarn package manager:
* Mobile platform/version under test: Android 8.0
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

		service = AppiumDriverLocalService.buildDefaultService();
		service.start();
		if (service == null || !service.isRunning()) {
			throw new AppiumServerHasNotBeenStartedLocallyException(
					"An appium server node is not started!");
		}

		driver = new AndroidDriver(service.getUrl(), androidCapabilities);

**Comment by VenkateshPS** [comment]
[<script src="https://gist.github.com/VenkateshPS/417fa9b0672444d7358ce93f5fc78532.js"></script>](url)

**Comment by VenkateshPS** [comment]
<script src="https://gist.github.com/VenkateshPS/417fa9b0672444d7358ce93f5fc78532.js"></script>

**Comment by VenkateshPS** [comment]
{% gist 417fa9b0672444d7358ce93f5fc78532 %}

**Comment by VenkateshPS** [comment]
https://gist.github.com/VenkateshPS/417fa9b0672444d7358ce93f5fc78532

**Comment by imurchie** [comment]
Is this happening consistently?

**Comment by dpgraham** [comment]
The fix for this is published Appium 1.11.1-rc.0 (release candidate).
