### ISSUE TITLE
iOS: Test speed reduced in times during recording

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#12168]
## The problem
When test record in progress testing speed reducing in times.
Tested with iPhone 6s on macBookPRO(2017). 

## Environment
* Appium version (or git revision) that exhibits the issue: 1.11.0
* Desktop OS/version used to run Appium: MacOS 10.13.6
* Node.js version (unless using Appium.app|exe): v11.10.0
* Npm or Yarn package manager: 6.8.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: iPhone6s with iOS 12.last

## Details
some results:
no record:
fees.myPlanFees myPlanFees [ ]                                                                   - 32 sec / 33 sec

record:
// no any settings: (IOSDriver) driver).startRecordingScreen();
fees.myPlanFees myPlanFees [ ]                                                                   - 49 sec
// codec h264
fees.myPlanFees myPlanFees [ ]                                                                   - 53 sec
// codec mpeg4
fees.myPlanFees myPlanFees [ ]                                                                   - 48 sec

## Link to Appium logs
will add on request

## Code To Reproduce Issue [ Good To Have ]
n/a

**Comment by mykola-mokhnach** [comment]
This behaviour is expected. Try to reduce the frame rate as a workaround.

**Comment by amedvedjev** [comment]
Tried with 10fps with zero rezult. But when i using "flick" running in terminal i have no such effect.
