### ISSUE TITLE
Wrong Location of Elements

### ISSUE THREAD

**Issue by nunessf** [appium/appium#12174]
## The problem

The driver is not locating properly some elements on a mobile hybrid app.
For example, I have this button on the half bottom of the app.
My window dimensions are: Width: 1080 | Height: 1704
It's showing me the button has the coordinates: {'y': 408.0, 'x': 14.0}

If the window has the height of 1704, then the element cannot be at 408, it should be lower, the button is on the bottom half of the app.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): v10.13.0
* Npm or Yarn package manager: npm 6.4.1
* Mobile platform/version under test: Android 8.1.0
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Appium Desktop

## Link to Appium logs

https://gist.github.com/nunessf/2cea576045dc68fe74dd207194ac83a0

**Comment by nunessf** [comment]
Any idea when this issue might be handled?

**Comment by mykola-mokhnach** [comment]
These coordinates are returned by chromedriver and have nothing to do with appium server itself
