### ISSUE TITLE
chromedriver error when swith_to webview

### ISSUE THREAD

**Issue by oscarforever** [appium/appium#12172]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.5
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:1.4.16.1
* Node.js version (unless using Appium.app|exe):v8.2.1
* Npm or Yarn package manager:5.30
* Real device or emulator/simulator:real device
* Appium CLI or Appium.app|exe:

## Details
hi all , This problem has been bothering me for days and has not been solved yet
unable driver.switch_to.context('WEBVIEW_com.main.lxc.lxcgogogo')
error: Chromedriver: Chromedriver exited unexpectedly with code null, signal SIGTERM
please help me! thank you very much!
## Link to Appium logs
> Killed Node Server.
> Appium server process ended
> Launching Appium server with command: D:\Program Files\Appium\node.exe lib\server\main.js --address 127.0.0.1 --port 4723 --platform-name Android --platform-version 23 --automation-name Appium --log-no-color
> info: Welcome to Appium v1.4.16 (REV ae6877eff263066b26328d457bd285c0cc62430d)
> info: Appium REST http interface listener started on 127.0.0.1:4723
> info: [debug] Non-default server args: {"address":"127.0.0.1","logNoColors":true,"platformName":"Android","platformVersion":"23","automationName":"Appium"}
> info: Console LogLevel: debug
> info: --> POST /wd/hub/session {"capabilities":{"firstMatch":[{"platformName":"Android","appium:platformVersion":"7.0","appium:deviceName":"PBV7N16419020079","appium:appPackage":"com.main.lxc.lxcgogogo","appium:appActivity":"com.main.lxc.lxcgogogo.MainActivity","appium:recreateChromeDriverSessions":true}]},"desiredCapabilities":{"platformName":"Android","platformVersion":"7.0","deviceName":"PBV7N16419020079","appPackage":"com.main.lxc.lxcgogogo","appActivity":"com.main.lxc.lxcgogogo.MainActivity","recreateChromeDriverSessions":true}}
> info: Client User-Agent string: appium/python 0.38 (selenium/3.141.0 (python windows))
> info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : recreateChromeDriverSessions
> info: [debug] Didn't get app but did get Android package, will attempt to launch it on the device
> info: [debug] Creating new appium session af4e7205-17cf-49f5-a4a0-a8fd7abfa58d
> info: Starting android appium
> info: [debug] Getting Java version
> info: Java version is: 1.8.0_121
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from D:\Program Files\AppData\Local\Android\android-sdk\platform-tools\adb.exe
> warn: No app capability, can't parse package/activity
> info: [debug] Using fast reset? true
> info: [debug] Preparing device for session
> info: [debug] Not checking whether app is present since we are assuming it's already on the device
> info: Retrieving device
> info: [debug] Trying to find a connected android device
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: "D:\Program Files\AppData\Local\Android\android-sdk\platform-tools\adb.exe" devices
> info: [debug] 1 device(s) connected
> info: Found device PBV7N16419020079
> info: [debug] Setting device id to PBV7N16419020079
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> info: [debug] executing cmd: "D:\Program Files\AppData\Local\Android\android-sdk\platform-tools\adb.exe" -s PBV7N16419020079 wait-for-device
> info: [debug] executing cmd: "D:\Program Files\AppData\Local\Android\android-sdk\platform-tools\adb.exe" -s PBV7N16419020079 shell "echo 'ready'"
> info: [debug] Starting logcat capture
> info: [debug] Getting device API level
> info: [debug] executing cmd: "D:\Program Files\AppData\Local\Android\android-sdk\platform-tools\adb.exe" -s PBV7N16419020079 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 24
> info: Device API level is: 24
> info: [debug] Extracting strings for language: default
> info: [debug] Apk doesn't exist locally
> info: [debug] Could not get strings, but it looks like we had an old strings file anyway, so ignoring
> info: [debug] executing cmd: "D:\Program Files\AppData\Local\Android\android-sdk\platform-tools\adb.exe" -s PBV7N16419020079 shell "rm -rf /data/local/tmp/strings.json"
> info: [debug] Not uninstalling app since server not started with --full-reset
> info: [debug] Skipping install since we launched with a package instead of an app path
> info: [debug] Forwarding system:4724 to device:4724
> info: [debug] executing cmd: "D:\Program Files\AppData\Local\Android\android-sdk\platform-tools\adb.exe" -s PBV7N16419020079 forward tcp:4724 tcp:4724
> info: [debug] Pushing appium bootstrap to device...
> info: [debug] executing cmd: "D:\Program Files\AppData\Local\Android\android-sdk\platform-tools\adb.exe" -s PBV7N16419020079 push "D:\\Program Files\\Appium\\node_modules\\appium\\build\\android_bootstrap\\AppiumBootstrap.jar" /data/local/tmp/
> info: Starting App
> info: [debug] Attempting to kill all 'uiautomator' processes
> info: [debug] Getting all processes with 'uiautomator'
> info: [debug] executing cmd: "D:\Program Files\AppData\Local\Android\android-sdk\platform-tools\adb.exe" -s PBV7N16419020079 shell "ps"| grep uiautomator
> info: [debug] No matching processes found
> info: [debug] Running bootstrap
> info: [debug] spawning: D:\Program Files\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s PBV7N16419020079 shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap -e pkg com.main.lxc.lxcgogogo -e disableAndroidWatchers false
> info: [debug] [UIAUTOMATOR STDOUT] Warning: This version of UI Automator is deprecated. New tests should be written using
> info: [debug] [UIAUTOMATOR STDOUT] UI Automator 2.0 which is available as part of the Android Testing Support Library.
> info: [debug] [UIAUTOMATOR STDOUT] See https://developer.android.com/training/testing/ui-testing/uiautomator-testing.html
> info: [debug] [UIAUTOMATOR STDOUT] for more details.
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
> info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
> info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
> info: [debug] [BOOTSTRAP] [debug] Loading json...
> info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
> info: [debug] Waking up device if it's not alive
> info: [debug] Pushing command to appium work queue: ["wake",{}]
> info: [debug] [BOOTSTRAP] [debug] Client connected
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"wake","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: wake
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
> info: [debug] executing cmd: "D:\Program Files\AppData\Local\Android\android-sdk\platform-tools\adb.exe" -s PBV7N16419020079 shell "dumpsys window"
> info: [debug] Screen already unlocked, continuing.
> info: [debug] Pushing command to appium work queue: ["getDataDir",{}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDataDir","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
> info: [debug] dataDir set to: /data/local/tmp
> info: [debug] Pushing command to appium work queue: ["compressedLayoutHierarchy",{"compressLayout":false}]
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"\/data\/local\/tmp"}
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"compressedLayoutHierarchy","params":{"compressLayout":false}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: compressedLayoutHierarchy
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":false}
> info: [debug] Getting device API level
> info: [debug] executing cmd: "D:\Program Files\AppData\Local\Android\android-sdk\platform-tools\adb.exe" -s PBV7N16419020079 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 24
> info: [debug] executing cmd: "D:\Program Files\AppData\Local\Android\android-sdk\platform-tools\adb.exe" -s PBV7N16419020079 shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n com.main.lxc.lxcgogogo/com.main.lxc.lxcgogogo.MainActivity"
> info: [debug] Waiting for pkg "com.main.lxc.lxcgogogo" and activity "com.main.lxc.lxcgogogo.MainActivity" to be focused
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: "D:\Program Files\AppData\Local\Android\android-sdk\platform-tools\adb.exe" -s PBV7N16419020079 shell "dumpsys window windows"
> info: [debug] executing cmd: "D:\Program Files\AppData\Local\Android\android-sdk\platform-tools\adb.exe" -s PBV7N16419020079 shell "getprop ro.build.version.release"
> info: [debug] Device is at release version 7.0
> info: [debug] Device launched! Ready for commands
> info: [debug] Setting command timeout to the default of 60 secs
> info: [debug] Appium session started with sessionId af4e7205-17cf-49f5-a4a0-a8fd7abfa58d
> info: <-- POST /wd/hub/session 303 2778.061 ms - 74 
> info: --> GET /wd/hub/session/af4e7205-17cf-49f5-a4a0-a8fd7abfa58d {"capabilities":{"firstMatch":[{"platformName":"Android","appium:platformVersion":"7.0","appium:deviceName":"PBV7N16419020079","appium:appPackage":"com.main.lxc.lxcgogogo","appium:appActivity":"com.main.lxc.lxcgogogo.MainActivity","appium:recreateChromeDriverSessions":true}]},"desiredCapabilities":{"platformName":"Android","platformVersion":"7.0","deviceName":"PBV7N16419020079","appPackage":"com.main.lxc.lxcgogogo","appActivity":"com.main.lxc.lxcgogogo.MainActivity","recreateChromeDriverSessions":true}}
> info: [debug] Responding to client with success: {"status":0,"value":{"platform":"LINUX","browserName":"Android","platformVersion":"7.0","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"Android","platformVersion":"7.0","deviceName":"PBV7N16419020079","appPackage":"com.main.lxc.lxcgogogo","appActivity":"com.main.lxc.lxcgogogo.MainActivity","recreateChromeDriverSessions":true},"platformName":"Android","deviceName":"PBV7N16419020079","appPackage":"com.main.lxc.lxcgogogo","appActivity":"com.main.lxc.lxcgogogo.MainActivity","recreateChromeDriverSessions":true},"sessionId":"af4e7205-17cf-49f5-a4a0-a8fd7abfa58d"}
> info: <-- GET /wd/hub/session/af4e7205-17cf-49f5-a4a0-a8fd7abfa58d 200 3.895 ms - 717 {"status":0,"value":{"platform":"LINUX","browserName":"Android","platformVersion":"7.0","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"Android","platformVersion":"7.0","deviceName":"PBV7N16419020079","appPackage":"com.main.lxc.lxcgogogo","appActivity":"com.main.lxc.lxcgogogo.MainActivity","recreateChromeDriverSessions":true},"platformName":"Android","deviceName":"PBV7N16419020079","appPackage":"com.main.lxc.lxcgogogo","appActivity":"com.main.lxc.lxcgogogo.MainActivity","recreateChromeDriverSessions":true},"sessionId":"af4e7205-17cf-49f5-a4a0-a8fd7abfa58d"}
> info: --> POST /wd/hub/session/af4e7205-17cf-49f5-a4a0-a8fd7abfa58d/element {"using":"id","value":"com.main.lxc.lxcgogogo:id/shuwu","sessionId":"af4e7205-17cf-49f5-a4a0-a8fd7abfa58d"}
> info: [debug] Waiting up to 0ms for condition
> info: [debug] Pushing command to appium work queue: ["find",{"strategy":"id","selector":"com.main.lxc.lxcgogogo:id/shuwu","context":"","multiple":false}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"com.main.lxc.lxcgogogo:id/shuwu","context":"","multiple":false}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: find
> info: [debug] [BOOTSTRAP] [debug] Finding com.main.lxc.lxcgogogo:id/shuwu using ID with the contextId:  multiple: false
> info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=com.main.lxc.lxcgogogo:id/shuwu]
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":{"ELEMENT":"1"}}
> info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"1"},"sessionId":"af4e7205-17cf-49f5-a4a0-a8fd7abfa58d"}
> info: <-- POST /wd/hub/session/af4e7205-17cf-49f5-a4a0-a8fd7abfa58d/element 200 21.349 ms - 87 {"status":0,"value":{"ELEMENT":"1"},"sessionId":"af4e7205-17cf-49f5-a4a0-a8fd7abfa58d"}
> info: --> POST /wd/hub/session/af4e7205-17cf-49f5-a4a0-a8fd7abfa58d/element/1/click {"id":"1","sessionId":"af4e7205-17cf-49f5-a4a0-a8fd7abfa58d"}
> info: [debug] Pushing command to appium work queue: ["element:click",{"elementId":"1"}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:click","params":{"elementId":"1"}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: click
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
> info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"af4e7205-17cf-49f5-a4a0-a8fd7abfa58d"}
> info: <-- POST /wd/hub/session/af4e7205-17cf-49f5-a4a0-a8fd7abfa58d/element/1/click 200 362.245 ms - 76 {"status":0,"value":true,"sessionId":"af4e7205-17cf-49f5-a4a0-a8fd7abfa58d"}
> info: --> GET /wd/hub/session/af4e7205-17cf-49f5-a4a0-a8fd7abfa58d/contexts {}
> info: [debug] Getting a list of available webviews
> info: [debug] executing cmd: "D:\Program Files\AppData\Local\Android\android-sdk\platform-tools\adb.exe" -s PBV7N16419020079 shell "cat /proc/net/unix"
> info: [debug] WEBVIEW_22953 mapped to pid 22953
> info: [debug] Getting process name for webview
> info: [debug] executing cmd: "D:\Program Files\AppData\Local\Android\android-sdk\platform-tools\adb.exe" -s PBV7N16419020079 shell "ps"
> info: [debug] Parsed pid: 22953 pkg: com.main.lxc.lxcgogogo
> info: [debug] from: u0_a69,22953,576,3068564,137520,0,0000000000,R,com.main.lxc.lxcgogogo
> info: [debug] returning process name: com.main.lxc.lxcgogogo
> info: [debug] Available contexts: 
> info: [debug] ["WEBVIEW_com.main.lxc.lxcgogogo"]
> info: [debug] Available contexts: NATIVE_APP,WEBVIEW_com.main.lxc.lxcgogogo
> info: [debug] Responding to client with success: {"status":0,"value":["NATIVE_APP","WEBVIEW_com.main.lxc.lxcgogogo"],"sessionId":"af4e7205-17cf-49f5-a4a0-a8fd7abfa58d"}
> info: <-- GET /wd/hub/session/af4e7205-17cf-49f5-a4a0-a8fd7abfa58d/contexts 200 305.238 ms - 119 {"status":0,"value":["NATIVE_APP","WEBVIEW_com.main.lxc.lxcgogogo"],"sessionId":"af4e7205-17cf-49f5-a4a0-a8fd7abfa58d"}
> info: --> GET /wd/hub/session/af4e7205-17cf-49f5-a4a0-a8fd7abfa58d/context {}
> info: [debug] Responding to client with success: {"status":0,"value":"NATIVE_APP","sessionId":"af4e7205-17cf-49f5-a4a0-a8fd7abfa58d"}
> info: <-- GET /wd/hub/session/af4e7205-17cf-49f5-a4a0-a8fd7abfa58d/context 200 0.927 ms - 84 {"status":0,"value":"NATIVE_APP","sessionId":"af4e7205-17cf-49f5-a4a0-a8fd7abfa58d"}
> info: --> GET /wd/hub/session/af4e7205-17cf-49f5-a4a0-a8fd7abfa58d/contexts {}
> info: [debug] Getting a list of available webviews
> info: [debug] executing cmd: "D:\Program Files\AppData\Local\Android\android-sdk\platform-tools\adb.exe" -s PBV7N16419020079 shell "cat /proc/net/unix"
> info: [debug] WEBVIEW_22953 mapped to pid 22953
> info: [debug] Getting process name for webview
> info: [debug] executing cmd: "D:\Program Files\AppData\Local\Android\android-sdk\platform-tools\adb.exe" -s PBV7N16419020079 shell "ps"
> info: [debug] Parsed pid: 22953 pkg: com.main.lxc.lxcgogogo
> info: [debug] from: u0_a69,22953,576,3068564,137748,0,0000000000,S,com.main.lxc.lxcgogogo
> info: [debug] returning process name: com.main.lxc.lxcgogogo
> info: [debug] Available contexts: NATIVE_APP,WEBVIEW_com.main.lxc.lxcgogogo
> info: [debug] ["WEBVIEW_com.main.lxc.lxcgogogo"]
> info: [debug] Available contexts: NATIVE_APP,WEBVIEW_com.main.lxc.lxcgogogo
> info: [debug] Responding to client with success: {"status":0,"value":["NATIVE_APP","WEBVIEW_com.main.lxc.lxcgogogo"],"sessionId":"af4e7205-17cf-49f5-a4a0-a8fd7abfa58d"}
> info: <-- GET /wd/hub/session/af4e7205-17cf-49f5-a4a0-a8fd7abfa58d/contexts 200 307.834 ms - 119 {"status":0,"value":["NATIVE_APP","WEBVIEW_com.main.lxc.lxcgogogo"],"sessionId":"af4e7205-17cf-49f5-a4a0-a8fd7abfa58d"}
> info: --> GET /wd/hub/session/af4e7205-17cf-49f5-a4a0-a8fd7abfa58d/contexts {}
> info: [debug] Getting a list of available webviews
> info: [debug] executing cmd: "D:\Program Files\AppData\Local\Android\android-sdk\platform-tools\adb.exe" -s PBV7N16419020079 shell "cat /proc/net/unix"
> info: [debug] WEBVIEW_22953 mapped to pid 22953
> info: [debug] Getting process name for webview
> info: [debug] executing cmd: "D:\Program Files\AppData\Local\Android\android-sdk\platform-tools\adb.exe" -s PBV7N16419020079 shell "ps"
> info: [debug] Parsed pid: 22953 pkg: com.main.lxc.lxcgogogo
> info: [debug] from: u0_a69,22953,576,3081396,145992,0,0000000000,R,com.main.lxc.lxcgogogo
> info: [debug] returning process name: com.main.lxc.lxcgogogo
> info: [debug] Available contexts: NATIVE_APP,WEBVIEW_com.main.lxc.lxcgogogo
> info: [debug] ["WEBVIEW_com.main.lxc.lxcgogogo"]
> info: [debug] Available contexts: NATIVE_APP,WEBVIEW_com.main.lxc.lxcgogogo
> info: [debug] Responding to client with success: {"status":0,"value":["NATIVE_APP","WEBVIEW_com.main.lxc.lxcgogogo"],"sessionId":"af4e7205-17cf-49f5-a4a0-a8fd7abfa58d"}
> info: <-- GET /wd/hub/session/af4e7205-17cf-49f5-a4a0-a8fd7abfa58d/contexts 200 285.422 ms - 119 {"status":0,"value":["NATIVE_APP","WEBVIEW_com.main.lxc.lxcgogogo"],"sessionId":"af4e7205-17cf-49f5-a4a0-a8fd7abfa58d"}
> info: --> POST /wd/hub/session/af4e7205-17cf-49f5-a4a0-a8fd7abfa58d/context {"name":"WEBVIEW_com.main.lxc.lxcgogogo","sessionId":"af4e7205-17cf-49f5-a4a0-a8fd7abfa58d"}
> info: [debug] Getting a list of available webviews
> info: [debug] executing cmd: "D:\Program Files\AppData\Local\Android\android-sdk\platform-tools\adb.exe" -s PBV7N16419020079 shell "cat /proc/net/unix"
> info: [debug] WEBVIEW_22953 mapped to pid 22953
> info: [debug] Getting process name for webview
> info: [debug] executing cmd: "D:\Program Files\AppData\Local\Android\android-sdk\platform-tools\adb.exe" -s PBV7N16419020079 shell "ps"
> info: [debug] Parsed pid: 22953 pkg: com.main.lxc.lxcgogogo
> info: [debug] from: u0_a69,22953,576,3139340,159556,0,0000000000,S,com.main.lxc.lxcgogogo
> info: [debug] returning process name: com.main.lxc.lxcgogogo
> info: [debug] Available contexts: NATIVE_APP,WEBVIEW_com.main.lxc.lxcgogogo
> info: [debug] ["WEBVIEW_com.main.lxc.lxcgogogo"]
> info: [debug] Available contexts: NATIVE_APP,WEBVIEW_com.main.lxc.lxcgogogo
> info: [debug] Connecting to chrome-backed webview
> info: Chromedriver: Changed state to 'starting'
> info: Chromedriver: Set chromedriver binary as: D:\Program Files\Appium\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe
> info: Chromedriver: Killing any old chromedrivers, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"9515 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I chromedriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %a))
> info: Chromedriver: No old chromedrivers seemed to exist
> info: Chromedriver: Spawning chromedriver with: D:\Program Files\Appium\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe --url-base=wd/hub --port=9515
> info: Chromedriver: [STDOUT] Starting ChromeDriver 2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f) on port 9515
> Only local connections are allowed.
> info: JSONWP Proxy: Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
> info: JSONWP Proxy: Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Windows NT\",\"version\":\"6.1.7601 SP1\"}}}"
> info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.main.lxc.lxcgogogo","androidUseRunningApp":true,"androidDeviceSerial":"PBV7N16419020079"}}}
> info: JSONWP Proxy: Got response with status 200: {"sessionId":"c03810342ff293fad098d7d271048c18","status":13,"value":{"message":"unknown error: Failed to run adb command, is the adb server running?\n  (Driver info: chromedriver=2.33.506120 (e3e53...
> info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.main.lxc.lxcgogogo","androidUseRunningApp":true,"androidDeviceSerial":"PBV7N16419020079"}}}
> info: JSONWP Proxy: Got response with status 200: {"sessionId":"feefe6cedced301b55d592187721a655","status":13,"value":{"message":"unknown error: Failed to run adb command, is the adb server running?\n  (Driver info: chromedriver=2.33.506120 (e3e53...
> info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.main.lxc.lxcgogogo","androidUseRunningApp":true,"androidDeviceSerial":"PBV7N16419020079"}}}
> info: JSONWP Proxy: Got response with status 200: {"sessionId":"1de0979e19bf0a33bdd94e0efaee66c9","status":13,"value":{"message":"unknown error: Failed to run adb command, is the adb server running?\n  (Driver info: chromedriver=2.33.506120 (e3e53...
> info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.main.lxc.lxcgogogo","androidUseRunningApp":true,"androidDeviceSerial":"PBV7N16419020079"}}}
> info: JSONWP Proxy: Got response with status 200: {"sessionId":"727689a8ae86298118afe25ad1fd563a","status":13,"value":{"message":"unknown error: Failed to run adb command, is the adb server running?\n  (Driver info: chromedriver=2.33.506120 (e3e53...
> error: Chromedriver: Chromedriver exited unexpectedly with code null, signal SIGTERM
> info: Chromedriver: Changed state to 'stopped'
> warn: Chromedriver for context WEBVIEW_com.main.lxc.lxcgogogo stopped unexpectedly
> warn: Chromedriver quit unexpectedly, but it wasn't the active context, ignoring
> error: Chromedriver: Error: An unknown server-side error occurred while processing the command. (Original error: unknown error: Failed to run adb command, is the adb server running?
>   (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64))
>     at JWProxy.command$ (lib/proxy.js:133:15)
>     at tryCatch (D:\Program Files\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\regenerator\runtime.js:67:40)
>     at GeneratorFunctionPrototype.invoke [as _invoke] (D:\Program Files\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\regenerator\runtime.js:315:22)
>     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (D:\Program Files\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\regenerator\runtime.js:100:21)
>     at GeneratorFunctionPrototype.invoke (D:\Program Files\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\regenerator\runtime.js:136:37)
>     at bound (domain.js:284:14)
>     at GeneratorFunctionPrototype.runBound (domain.js:297:12)
>     at run (D:\Program Files\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\node_modules\core-js\library\modules\es6.promise.js:89:39)
>     at D:\Program Files\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\node_modules\core-js\library\modules\es6.promise.js:100:28
>     at flush (D:\Program Files\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\node_modules\core-js\library\modules\$.microtask.js:17:13)
>     at process._tickDomainCallback (node.js:381:11)
>  { [Error: An unknown server-side error occurred while processing the command. (Original error: unknown error: Failed to run adb command, is the adb server running?
>   (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64))]
>   status: 13,
>   value: { message: 'unknown error: Failed to run adb command, is the adb server running?\n  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)' },
>   httpCode: 200 }

## Code To Reproduce Issue [ Good To Have ]

from appium import webdriver
from time import sleep
from typing import List
if __name__ == '__main__':
    desired_caps = {
        'platformName' : 'Android',
        'platformVersion':'7.0',
        #'deviceName': '127.0.0.1:62001',
        'deviceName': 'PBV7N16419020079',
        'appPackage' : 'com.main.lxc.lxcgogogo',
        'appActivity': 'com.main.lxc.lxcgogogo.MainActivity',
        #'chromedriverExecutable': 'c:\\chromedriver.exe'
        "recreateChromeDriverSessions" : True
        #"chromedriverExecutable": 'D:\Program Files\Appium\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe'
    }
    remote_url='http://localhost:4723/wd/hub'
    br = webdriver.Remote(remote_url,desired_caps)
    sleep(5)
    br.find_element_by_id('com.main.lxc.lxcgogogo:id/shuwu').click()
    
    sleep(2)

    aa =br.contexts
    print(br.current_context)
    print('fasdfasdfa')
    print(br.contexts)
    itotal = len(br.contexts)
    if itotal > 1:
        #br.switch_to.context('WEBVIEW_com.main.lxc.lxcgogogo')
        br.switch_to.context(aa[1])
        print('current webview:')
        print(br.current_context)

**Comment by mykola-mokhnach** [comment]
Your appium version is out of date. Please upgrade to the recent one
