### ISSUE TITLE
Sometimes I got next error: An unknown server-side error occurred while processing the command. Original error: Cannot start the application

### ISSUE THREAD

**Issue by apoklyak** [appium/appium#12178]
## The problem

Sometimes I got this error when I try start Appium Session to inspect application elements.
Occasionally all is okay and I got elements inspector, but sometimes get this error.

An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.ripl.android' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: 'com.ripl.android.activities.StartupActivity' or 'com.ripl.android.com.ripl.android.activities.StartupActivity' never started. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting

## Environment

* Appium version 1.10.0 (desktop)
* Windows 10
* Node.js 8.12.0 version 
* Npm 5.7.1 version
* Android Studo 3.3.1 version
* I use emulator from Android Studo: 
Nexus 6. Android 9.0

## Details

I will try discribe my issue step by step:

1) I launch desktop Appium and starat server
2) Start Android Studio and launch my device (Nexus 6 with Android 9.0)
2) Then start Appium Instector Session 
3) I fill all fields like so:
{
  "platformName": "Android",
  "platformVersion": "9",
  "deviceName": "Android Emulator",
  "app": "D:\\123.apk",
  "fullReset": false
}
4) And click Start Session button
5) After that on my device I should click on the Agree & Continue button (without click I will get same error):
screenshot: https://i.gyazo.com/3322c76d2fd06b0b94ff964cddc8f5f6.png
6) And after that I will get success of start Elements Inspector or get error.
Screenshot with successful launch of the Elements Inspector: https://i.gyazo.com/d5ea1c3394ff93d2b7ee548cd3d28008.png

So, I don't know how it fix. And I should mention this is my first Appium launch.

## Link to Appium logs

I created a link with logs: https://gist.github.com/apoklyak/8fbd0ada88c481a8681164d3c9415470
Let me know if link doesn't open

## Code To Reproduce Issue [ Good To Have ]

 I don't have any scripts yet

**Comment by mykola-mokhnach** [comment]
Did you read the troubleshooting link?

**Comment by apoklyak** [comment]
> Did you read the troubleshooting link?

I wrote appPackage and appActivity and all works fine already. Thank you.

This is article was useful http://www.automationtestinghub.com/apppackage-and-appactivity-name/

**Comment by suzy-j** [comment]
I have  set appPackage and appActivity already , and  make sure they are correct,but it still shows : Error: Cannot start the 'yuelidata.yuejiaxiao.teacher' application .
The log:
Encountered internal error running command: Error: Cannot start the 'yuelidata.yuejiaxiao.teacher' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Cannot start the 'yuelidata.yuejiaxiao.teacher' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Activity name '.com.yuelidata.parentmeeting.ui.BootstrapActivity' used to start the app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity

**Comment by suzy-j** [comment]
I have set appPackage and appActivity already , and make sure they are correct.But it still shows : Error: Cannot start the 'y.teacher' application .
The log:
Encountered internal error running command: Error: Cannot start the 'y.teacher' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Cannot start the 'yuelidata.yuejiaxiao.teacher' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Activity name '.com.yuelidata.parentmeeting.ui.BootstrapActivity' used to start the app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity

**Comment by NikitaTurakhia** [comment]
I have the same issue. I have added below infomation in the appium inspector, and when I do start session, I get the below error.

![image](https://user-images.githubusercontent.com/21182650/170519266-414c03fb-b38f-4d2f-a367-e6395100ea6f.png)


![image](https://user-images.githubusercontent.com/21182650/170519469-f571b95a-b6b2-49d4-b88c-b28ffda2ce79.png)

**Comment by CarlosAbreuJr** [comment]
> I have the same issue. I have added below infomation in the appium inspector, and when I do start session, I get the below error.
> 
> ![image](https://user-images.githubusercontent.com/21182650/170519266-414c03fb-b38f-4d2f-a367-e6395100ea6f.png)
> 
> ![image](https://user-images.githubusercontent.com/21182650/170519469-f571b95a-b6b2-49d4-b88c-b28ffda2ce79.png)

Enter the initial activity, appium concatenates appPackage/appActivity.
enter "appium:appActivity":"activity"
If you don't know what the correct activity and package is, do the following.
Run the app in the emulator, after that run the command in the terminal any
```
adb shell
dumpsys window windows | grep -E 'mCurrentFocus'
```
the expected result is package/activity (com.xxxx/com.example.xxx.MainActivity)

Hope I helped, this solved my problem

**Comment by Yasithe03** [comment]
Hi, Im also facing this error. can anyone help me with it.
<img width="376" alt="Screenshot 2023-03-30 at 5 46 16 PM" src="https://user-images.githubusercontent.com/128848230/228833103-6423713c-343f-455a-950b-53e7ffaa6f6f.png">

**Comment by farzane-shafiee** [comment]
![image](https://github.com/appium/appium/assets/46108338/bda0b0bc-1ed7-4e9e-9044-658330896aed)
![image](https://github.com/appium/appium/assets/46108338/478eb4e1-d664-417d-a78a-c6b1b08899e9)

**Comment by farzane-shafiee** [comment]
type of appWaitForLaunch should boolean.
![image](https://github.com/appium/appium/assets/46108338/86e80f12-469b-4486-9b67-6a01b474e9f3)
and add "appium:appPackage"

**Comment by Jesus-0311** [comment]
Sigo teniendo el mismo problema

**Comment by Jesus-0311** [comment]
![image](https://github.com/appium/appium/assets/109171861/eb68161c-4993-42d0-8437-ad22d904267c)

**Comment by Arungithubpractise** [comment]
I faced a similar issue but after adding the desired capabilities in appium inspector it worked!

![image](https://github.com/appium/appium/assets/114951911/c86b41ed-e530-4582-a6a1-b502bae2642c)

**Comment by ntlslmnc** [comment]
> "appWaitForLaunch": "false" I just needed to add this capability and tolerate my problem.

Thanks you!

**Comment by massimo-buildroot** [comment]
I discerned the response https://stackdev.space/questions/how-can-i-resolve-the-error-that-occurs-when-clicking-a-button-in-android-studio-using-kotlin
