### ISSUE TITLE
Android logcat result empty.

### ISSUE THREAD

**Issue by AvrahamAtia** [appium/appium#12179]
## The problem
List<LogEntry> logAsAList = getDriver().manage().logs().get("logcat").getAll();
Sometime logAsAList empty and sometime is contain only one line. I want to see full log.
I am using clearDeviceLogsOnStart capability:
capabilities.setCapability("clearDeviceLogsOnStart", true);
## Environment

Automation framework:
Appium server: 1.10.0
Node: v10.5.0
Allure: 2.8.0
Apache Maven 3.5.4 (***; 2018-06-17T21:33:14+03:00)
Maven home: /usr/local/Cellar/maven/3.5.4/libexec
Java version: 11.0.1, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-11.0.1.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.3", arch: "x86_64", family: "mac"

**Comment by mykola-mokhnach** [comment]
Please attach full server log

**Comment by AvrahamAtia** [comment]
Appium server logs: 
https://gist.github.com/AvrahamAtia/0397e84d116816940a0298c509ecdeb5

**Comment by mykola-mokhnach** [comment]
I don't observe any problems in the attached logs. Have you eventually read https://appiumpro.com/editions/53 ?

**Comment by AvrahamAtia** [comment]
For iOS, fail to pull perfomance log: 
[debug] [MJSONWP] Calling AppiumDriver.getLog() with args: ["performance","83ae6ee5-66fa-4e1d-a082-42f1ebf2efea"]
[debug] [XCUITest] Executing command 'getLog'
[debug] [BaseDriver] Retrieving 'performance' logs
[debug] [BaseDriver] Retrieving supported log types
[debug] [MJSONWP] Encountered internal error running command: Error: No logs of type 'performance' found.
[debug] [MJSONWP]     at XCUITestDriver.callee$0$0$ (/usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/lib/commands/logging.js:22:9)
[debug] [MJSONWP]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[debug] [MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[debug] [MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[debug] [MJSONWP]     at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[debug] [MJSONWP]     at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
[debug] [MJSONWP]     at new Promise (<anonymous>)
[debug] [MJSONWP]     at new F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
[debug] [MJSONWP]     at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
[debug] [MJSONWP]     at AsyncI

**Comment by mykola-mokhnach** [comment]
> For iOS, fail to pull perfomance log

This log is only available for web views. Closed as not an issue.
