### ISSUE TITLE
Should updata javascript API document

### ISSUE THREAD

**Issue by ZetaChow** [appium/appium#12183]
javascript API document content is outdated

**Comment by dpgraham** [comment]
Can you try opening a pull request for that?

**Comment by ZetaChow** [comment]
why api document code not work?
`// webdriver.io example
driver.element("~SomeAccessibilityId");`

but simple-code the code for find element like this:
`client.findElement("accessibility id","TextField1"); `

and , driver.element throw  error : element is not a function

**Comment by ZetaChow** [comment]
Most of the Appium simple code found through the Internet are written in Python，very few Javascript, because Appium has more support for Python? or Not

I wanna write Appium test script in JS , Where can I find the latest documentation and examples?

**Comment by KazuCocoa** [comment]
We officially have sample code in https://github.com/appium/appium/tree/master/sample-code
http://appium.io/docs/en/about-appium/intro/ is the doc. But we need to update them which is wrong as https://github.com/appium/appium/issues/12183#issuecomment-464981337
Really happy if you can create a PR to update doc.

**Comment by ZetaChow** [comment]
Thanks for your reply!
After reading the changelog, I see that the current API documentation has not been fully updated to the latest, and I am honored that to create a PR to update the doc.
