### ISSUE TITLE
Unable to launch WebDriverAgent on ios 12.1.3

### ISSUE THREAD

**Issue by nguyenluongtoan** [appium/appium#12182]
## The problem

Unable to launch WebDriverAgent on ios 12.1.3 
I try with 2 environment: iphone 6 ios 12.1.2 it worked
on iphone 6 ios 12.1.3 the WDA can not lauched and was deleted.

## Environment

* Appium version: 1.10
* Last Appium version that did not exhibit the issue 1.10
* Desktop OS/version used to run Appium: MacOS 10.13.6
* Node.js version: 11.4.0
* Npm 6.5.0
* Mobile platform/version under test: ios 12.1.3/12.1.2
* Real device or emulator/simulator: iphone 6
* Appium CLI or Appium.app|exe:

## Details

the WDA is deleted when i run the test script

## Link to Appium logs
short
https://gist.github.com/nguyenluongtoan/aa033097e2f43a9a58540a8c14ec5808
full
https://gist.github.com/nguyenluongtoan/d04dd37a59aef721784fbfb01e0f4d94

**Comment by imurchie** [comment]
Please make sure you delete the WebDriverAgent-Runner app off the device, and delete the folder `/Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy`. Then retry to make sure everything is up-to-date.

**Comment by LyDH2** [comment]
thank you, I have not deleted DeriveData yet, let me try it. 
i've try to run npm install -g appium, and the version up to 11, the newest.
Thanks

> Please make sure you delete the WebDriverAgent-Runner app off the device, and delete the folder `/Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy`. Then retry to make sure everything is up-to-date.

**Comment by LyDH2** [comment]
the issue was fixed, we build WDA from node modules in Appium Client, thanks
