### ISSUE TITLE
Can't set the location on real device iOS

### ISSUE THREAD

**Issue by dron4ik86** [appium/appium#12191]
## The problem
When I try to set geolocation:
`driver.set_location(32.36732761840638, 34.912902299649886, None)`
 I get an error message
`selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Can't set the location on device '14f9e52e7fc70b46d723c28***********'. Original error: Command 'idevicelocation -u 14f9e52e7fc70b46d723c28************ 32.36732761840638 34.912902299649886' exited with code null
`
On Android is work perfect

## Environment
* Appium version (or git revision) that exhibits the issue - 1.11.0
* Desktop OS/version used to run Appium - MACOS
* Node.js version - 8.14.0
* Npm or Yarn package manager - npm
* Mobile platform/version under test - iPhone 5s
* Real device 
* Appium CLI

**Comment by mykola-mokhnach** [comment]
Does the command work if executed manually?

**Comment by dron4ik86** [comment]
> Does the command work if executed manually?

`$ idevicelocation -u 14f9e52e7fc70b46d723c28******** 32.36732761840638 34.912902299649886`
I get Abort trap: 6

**Comment by mykola-mokhnach** [comment]
Then it is hardly a problem with Appium. It is necessary to fix the problem with the utility execution first.

Closed as not an issue
