### ISSUE TITLE
Unhandled endpoint /wda/Siri/activate

### ISSUE THREAD

**Issue by sunnysachdeva** [appium/appium#12197]
## The problem

Upgraded from Appium 1.9.0 to Appium 1.10.1 .

After launching iOS native app, i am firing below code

HashMap<String, String> args = new HashMap<>();
args.put("text", "What's two plus two?");
driver.executeScript("mobile: siriCommand", args);

I am getting below error

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unhandled endpoint: /session/9E173319-958E-481C-BD81-649ECF9D4C54/wda/siri/activate -- http://localhost:7219/ with parameters {
    wildcards =     (
        "session/9E173319-958E-481C-BD81-649ECF9D4C54/wda/siri/activate"
    );
}
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
 os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '1.8.0_171'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities {agentPath: /Users/admin/.npm-global/li..., automationName: XCUITest, bootstrapPath: /Users/admin/.npm-global/li..., browserName: , bundleId: ......, databaseEnabled: false, deviceName: iPhone 7, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: false, newCommandTimeout: 60000, platform: MAC, platformName: iOS, simpleIsVisibleCheck: true, takesScreenshot: true, udid:???..., wdaLocalPort: 7219, webStorageEnabled: false, xcodeConfigFile: /Users/admin/.npm-global/li...}
Session ID: da921d3f-eef1-4d48-92e5-25d63f44316e

**Comment by mykola-mokhnach** [comment]
Make sure the WebDriverAgent binary on the device is up to date

**Comment by sunnysachdeva** [comment]
@mykola-mokhnach thanks for your reply. I did perform entire process of compiling webdriver agent binary but still facing same issue. Can you pls provide some more points here. 
Thanks in advance

**Comment by mykola-mokhnach** [comment]
Where do you get the WDA source? The correct repository is https://github.com/appium/WebDriverAgent
