### ISSUE TITLE
Appium behaiours different in devices(Realme ,8.1.0-not able to lauch browser) while in moto g i am able to lauch

### ISSUE THREAD

**Issue by kecdeep** [appium/appium#12195]
## The problem

i am not able to lauch the chrome brower on my mobile -realme 2 pro android 8.1.0 while
i am able to lauch same code in moto g 4 plus andorid 7.1.1
[AppiumLogs_8.1.1_realmedevices.txt](https://github.com/appium/appium/files/2883032/AppiumLogs_8.1.1_realmedevices.txt)
[AppiumLogs_8.1.1_realmedevices.txt](https://github.com/appium/appium/files/2883033/AppiumLogs_8.1.1_realmedevices.txt)

## Environment

* Appium version (or git revision) that exhibits the issue:1.10
* Last Appium version that did not exhibit the issue (if applicable):1.5
* Desktop OS/version used to run Appium:Window 10
* Node.js version (unless using Appium.app|exe):10.14.2
* Npm or Yarn package manager:
* Mobile platform/version under test: 8.1.0/7.1.1
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe: CLI
[AppiumLogs_8.1.1_realmedevices.txt](https://github.com/appium/appium/files/2883025/AppiumLogs_8.1.1_realmedevices.txt)

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Code To Reproduce Issue [ Good To Have ]

@Before("@Mobile")
	public void setUPMobileChrome(Scenario scenario){
		DesiredCapabilities caps = new DesiredCapabilities();
		caps.setCapability("deviceName", "Chandra");
		caps.setCapability("deviceName", "7c9a8acrrr");
		//caps.setCapability("deviceName", "Moto E(4) Plus");
		//caps.setCapability("udid", "ZH33L2HZRE79"); 
		caps.setCapability("platformName", "Android");
		caps.setCapability("platformVersion", "8.1.0");
		caps.setCapability("browserName", "Chrome");
		//caps.setCapability("noReset", true);
		//caps.setCapability("automationName","uiautomator2");

		//Set ChromeDriver location
	//	System.setProperty("webdriver.chrome.driver","C:\\Users\\dee1\\Desktop\\AppiumAll\\chromedriver_win32\\chromedriver.exe");
		
		//Instantiate Appium Driver
	//	AppiumDriver<MobileElement> driver = null;
		try {
			driver = new AndroidDriver<MobileElement>(new URL("http://0.0.0.0:4723/wd/hub"), caps);
			
		} catch (MalformedURLException e) {
			System.out.println(e.getMessage());
		}
[AppiumLogs_8.1.1_realmedevices.txt](https://github.com/appium/appium/files/2883027/AppiumLogs_8.1.1_realmedevices.txt)

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
There are multiple errors in the log, so I'm not quite sure which one of them is the blocker.

> [debug] [W3C] Encountered internal error running command: Error executing adbExec. Original error: 'Command 'C\:\\Users\\deerai1\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 7c9a8ac shell pm clear com.android.chrome' exited with code 1'; Stderr: 'Error: java.lang.SecurityException: adb clearing user data is forbidden.'; Code: '1'

This one for example is a manufacturer limitation, which has nothing to do with Appium. Please check it manufacturer customer support on how it is possible to disable/workaround these artificial security restriction.

**Comment by Karthiele** [comment]
How to resolve this issue

**Comment by handsongre** [comment]
Facing the same issue in Oppo Ax5s .

**Comment by snevesbarros** [comment]
Just adding the answer here as I faced the same issue (but on an OPPO device), but was able to resolve it by using a new flag that was added to chromedriver (so hopefully this helps a few people):

The issue is that noReset works for native apps, but chromedriver itself also makes the call to clear the user app data before it launches chrome. To prevent this a new argument "androidKeepAppDataDir" was added around 4 months ago.

``` java
        DesiredCapabilities appCapabilities = new DesiredCapabilities();
        appCapabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
        appCapabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "UiAutomator2");
        appCapabilities.setCapability(MobileCapabilityType.NO_RESET, true);
        appCapabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "chrome");
        ChromeOptions options = new ChromeOptions();
        options.setExperimentalOption("androidKeepAppDataDir", true);
        appCapabilities.setCapability(ChromeOptions.CAPABILITY, options);
```

The above works for me on an OPPO device (which originally showed the same error as mentioned above).

Hope this helps.
