### ISSUE TITLE
Screenshot is incorrect for devices that allow different screen resolution

### ISSUE THREAD

**Issue by kamza-tricentis** [appium/appium#12199]
## The problem

Screenshot taken from device by appium is incorrect.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10
* Mobile platform/version under test: Android 8.0
* Real device or emulator/simulator: Samsung Galaxy S9+, Samsung Galaxy S7 Edge

## Details

Problem occurs on devices that allow different screen resolutions:
![image](https://user-images.githubusercontent.com/44870591/53159847-fa42f680-35c6-11e9-83d6-5d98bb101104.png)
On default FHD resolution everything seems fine, but if we go to WQHD the screenshot is being cut from all sides
![image](https://user-images.githubusercontent.com/44870591/53159932-28c0d180-35c7-11e9-9c4e-4395afa75089.png)

If we change to HD it looks as follows
![image](https://user-images.githubusercontent.com/44870591/53159956-37a78400-35c7-11e9-855f-2590d42a5846.png)

Screenshots taken directly by uiautomatorviewer are correct in all cases.

![image](https://user-images.githubusercontent.com/44870591/53160286-e64bc480-35c7-11e9-8c58-2e29c4be89b0.png)

**Comment by mykola-mokhnach** [comment]
which automation backend is used?

**Comment by kamza-tricentis** [comment]
UiAutomator2

**Comment by mykola-mokhnach** [comment]
Do you observe the same problem in Appium@beta?

**Comment by mykola-mokhnach** [comment]
UIA2 uses the standard automation method to take screenshots:
https://github.com/appium/appium-uiautomator2-server/blob/60c069ed612b4147e978902572b8c80e5814bee5/app/src/main/java/io/appium/uiautomator2/utils/ScreenshotHelper.java#L67

I assume this is more an issue with the framework or the firmware rather than something that could be fixed on our side.

**Comment by kamza-tricentis** [comment]
Tested using UiAutomator and it did work, I guess you might be right and the issue might be in UiAutomator2 itself

**Comment by mykola-mokhnach** [comment]
@kamza-tricentis I could try to replace the screenshooting function there with an alternative approach when I have time, but I'll need your help to test it. Would such approach work for you?

**Comment by kamza-tricentis** [comment]
Sure, if you think you can find time to provide an working alternative I'll be glad to help out.

**Comment by mykola-mokhnach** [comment]
Please check if https://github.com/appium/appium-uiautomator2-server/pull/248

All you need is to build the server apks from the given branch and replace them inside your Appium dist

**Comment by kamza-tricentis** [comment]
Tried this one out and the issue still exists.

**Comment by mykola-mokhnach** [comment]
Can you please attach the logcat output? There should be some useful logs.

**Comment by kamza-tricentis** [comment]
https://gist.github.com/kamza-tricentis/d347a96fbf3f34a760c4a43a5498d3f8

**Comment by mykola-mokhnach** [comment]
I've made some fixes. Could you update and try again? Please don't forget to attach the logcat

**Comment by kamza-tricentis** [comment]
This time around it worked perfectly on S9+ device in all resolutions. Tested as well on "normal" other android phone + some emulator just in case and everything seems fine.

Logcat for max resolution S9+ in case you want to look around: https://gist.github.com/kamza-tricentis/d7ac125229792a3b8efae62b20ee1e55

**Comment by mykola-mokhnach** [comment]
Thanks. I'll do some performance optimisations then and merge the PR

**Comment by mykola-mokhnach** [comment]
Please check the stuff with performance optimizations I've made. logcat output is appreciated.

**Comment by kamza-tricentis** [comment]
Checked the new patch, few screenshots done on max resolution s9+. There is visible performance upgrade compared to previous version 👍 . 
https://gist.github.com/kamza-tricentis/bbcfa9d344ea5958f71a80a93006d89a

**Comment by mykola-mokhnach** [comment]
Published to beta
