### ISSUE TITLE
Annotation @iOSXCUITFindBy doesn't work

### ISSUE THREAD

**Issue by AliakseiYarmalchuk** [appium/appium#12190]
Hi there! Could you help me, please, with the following problem?

## The problem

Appium can't locate element via @iOSXCUITFindBy after moving from iOS 11.4 to iOS 12.1. I see, that Appium tries to locate element by id and then name, not by accessibility id. @iOSFindBy works correct, but it doesn't contain iOSNPredicate and iOSClassChain.

I have updated:
xcode 1.9.4 -> 10.1
appium 1.9.1 -> 1.10.0
serenity bdd from 1.7.4 to 2.0.40
java-client from 5.0.4 to 6.1.0 (tried 6.0.0 and 7.0.0 as well)
java 10 -> 11

## Environment

* Appium version (or git revision) that exhibits the issue: Tried on 1.10.0, 1.10.1 ,1.11.0, 1.9.1
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: MacOs High Sierra 10.13.6, 
* Node.js version (unless using Appium.app|exe): v10.5.0
* Npm or Yarn package manager: 6.3.0
* Mobile platform/version under test: iPhone X iOS 12.1
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: 

## Details

Console output:
net.thucydides.core.webdriver.exceptions.ElementShouldBeEnabledException: Expected enabled element was not enabled
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ws-047-61bs-Mac-mini.local', ip: 'fe80:0:0:0:1cdf:ba0c:5754:b0f3%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '11.0.2'
Driver info: driver.version: unknown 

## Link to Appium logs

Start to find by id, not accessibility id:

[debug] [MJSONWP] Matched JSONWP error code 7 to NoSuchElementError
[debug] [BaseDriver] Waited for 2969 ms so far
[debug] [JSONWP Proxy] Matched '/element' to command name 'findElement'
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/B4C47B38-DDC4-4660-AFC7-3FF9A1DCDE23/element] with body: {"using":"id","value":"loginButton"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"using":"id","value":"loginButton","description":"unable to find an element"},"sessionId":"B4C47B38-DDC4-4660-AFC7-3FF9A1DCDE23","status":7}
[JSONWP Proxy] Got an unexpected response: {"value":{"using":"id","value":"loginButton","description":"unable to find an element"},"sessionId":"B4C47B38-DDC4-4660-AFC7-3FF9A1DCDE23","status":7}

In some time start to find by name, not accessibility id as well:

[HTTP] --> POST /wd/hub/session/063adab5-9da2-45c3-99a0-91b5bb809467/element
[HTTP] {"using":"name","value":"loginButton"}
[debug] [W3C (063adab5)] Calling AppiumDriver.findElement() with args: ["name","loginButton","063adab5-9da2-45c3-99a0-91b5bb809467"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Matched '/element' to command name 'findElement'
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/B4C47B38-DDC4-4660-AFC7-3FF9A1DCDE23/element] with body: {"using":"name","value":"loginButton"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"using":"name","value":"loginButton","description":"unable to find an element"},"sessionId":"B4C47B38-DDC4-4660-AFC7-3FF9A1DCDE23","status":7}
[JSONWP Proxy] Got an unexpected response: {"value":{"using":"name","value":"loginButton","description":"unable to find an element"},"sessionId":"B4C47B38-DDC4-4660-AFC7-3FF9A1DCDE23","status":7}
[debug] [MJSONWP] Matched JSONWP error code 7 to NoSuchElementError
[debug] [W3C (063adab5)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[debug] [W3C (063adab5)]     at XCUITestDriver.helpers.doNativeFind (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:130:13)
[HTTP] <-- POST /wd/hub/session/063adab5-9da2-45c3-99a0-91b5bb809467/element 404 89 ms - 387

## Code To Reproduce Issue [ Good To Have ]

Element:

    @iOSXCUITFindBy(accessibility = "LOG IN")
    private WebElement loginButton;

Method:

    public void clickOnLoginButton() {
        element(loginButton).click();
    }

**Comment by mykola-mokhnach** [comment]
Elements lookup is controlled by WebDriverAgent. Please update Appium server to the most recent version and report the issue to https://github.com/facebook/WebDriverAgent/issues if that does not help.
