### ISSUE TITLE
getting java.lang.SecurityException: adb clearing user data is forbidden.'; Code: '1'

### ISSUE THREAD

**Issue by kecdeep** [appium/appium#12196]
## The problem

geeting issue hen launcing app in mobile browser

## Environment

* Appium version (or git revision) that exhibits the issue:1.10
* Last Appium version that did not exhibit the issue (if applicable):1.5
* Desktop OS/version used to run Appium:Window 10
* Node.js version (unless using Appium.app|exe):10.14.2
* Npm or Yarn package manager:
* Mobile platform/version under test: 8.1.0
* Real device or emulator/simulator:Real devices

**Comment by kecdeep** [comment]
Appium Logs=============



The server is running
[Appium] Welcome to Appium v1.10.0
[Appium] Non-default server args:
[Appium]   sessionOverride: true
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"browserName":"Chrome","platformName":"Android","deviceName":"7c9a8ac","platformVersion":"8.1.0"},"capabilities":{"firstMatch":[{"browserName":"Chrome","appium:deviceName":"7c9a8ac","platformName":"android","appium:platformVersion":"8.1.0"}]}}
[W3C] Calling AppiumDriver.createSession() with args: [{"browserName":"Chrome","platformName":"Android","deviceName":"7c9a8ac","platformVersion":"8.1.0"},null,{"firstMatch":[{"browserName":"Chrome","appium:deviceName":"7c9a8ac","platformName":"android","appium:platformVersion":"8.1.0"}]}]
[BaseDriver] Event 'newSessionRequested' logged at 1550641781975 (11:19:41 GMT+0530 (India Standard Time))
[Appium] Consider setting 'automationName' capability to 'UiAutomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.
[Appium] Creating new AndroidDriver (v4.8.0) session
[Appium] Capabilities:
[Appium]   browserName: Chrome
[Appium]   platformName: android
[Appium]   deviceName: 7c9a8ac
[Appium]   platformVersion: 8.1.0
[BaseDriver] W3C capabilities {"alwaysMatch":{"browserNam... and MJSONWP desired capabilities {"browserName":"Chrome","pl... were provided
[BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"browserNam...
[BaseDriver] Session created with session id: cd7a57db-639e-4d8e-91fa-b65bd39c2aac
[AndroidDriver] Java version is: 1.8.0_191
[AndroidDriver] We're going to run a Chrome-based session
[AndroidDriver] Chrome-type package and activity are com.android.chrome and com.google.android.apps.chrome.Main
[AndroidDriver] Retrieving device list
[ADB] Trying to find a connected android device
[ADB] Getting connected devices...
[ADB] 2 device(s) connected
[AndroidDriver] Looking for a device with Android '8.1.0'
[ADB] Setting device id to 7c9a8ac
[ADB] Getting device platform version
[ADB] Running 'C:\Users\deerai1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 7c9a8ac shell getprop ro.build.version.release'
[ADB] Current device property 'ro.build.version.release': 8.1.0
[AndroidDriver] Using device: 7c9a8ac
[ADB] Setting device id to 7c9a8ac
[ADB] Running 'C:\Users\deerai1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 7c9a8ac shell getprop ro.build.version.sdk'
[ADB] Current device property 'ro.build.version.sdk': 27
[ADB] Device API level: 27
[AndroidDriver] Consider setting 'automationName' capability to 'uiautomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.
[AndroidDriver] App file was not listed, instead we're going to run com.android.chrome directly on the device
[AndroidDriver] Checking whether package is present on the device
[ADB] Running 'C:\Users\deerai1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 7c9a8ac shell pm list packages com.android.chrome'
[AndroidDriver] Starting Android session
[ADB] Running 'C:\Users\deerai1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 7c9a8ac wait-for-device'
[ADB] Running 'C:\Users\deerai1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 7c9a8ac shell echo ping'
[AndroidDriver] Pushing settings apk to device...
[ADB] Getting install status for io.appium.settings
[ADB] Running 'C:\Users\deerai1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 7c9a8ac shell dumpsys package io.appium.settings'
[ADB] 'io.appium.settings' is installed
[ADB] Getting package info for 'io.appium.settings'
[ADB] Running 'C:\Users\deerai1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 7c9a8ac shell dumpsys package io.appium.settings'
[ADB] The version code of the installed 'io.appium.settings' is greater than the application version code (17 > 13)
[ADB] There is no need to install/upgrade 'C:\Program Files (x86)\Appium\resources\app\node_modules\io.appium.settings\apks\settings_apk-debug.apk'
[ADB] Running 'C:\Users\deerai1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 7c9a8ac shell ps'
[AndroidDriver] io.appium.settings is already running. There is no need to reset its permissions.
[ADB] Device API level: 27
[ADB] Running 'C:\Users\deerai1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 7c9a8ac shell appops set io.appium.settings android\:mock_location allow'
[Logcat] Starting logcat capture
[ADB] Getting device platform version
[ADB] Running 'C:\Users\deerai1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 7c9a8ac shell getprop ro.build.version.release'
[ADB] Current device property 'ro.build.version.release': 8.1.0
[ADB] Running 'C:\Users\deerai1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 7c9a8ac shell wm size'
[ADB] Running 'C:\Users\deerai1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 7c9a8ac shell getprop ro.product.model'
[ADB] Current device property 'ro.product.model': RMX1801
[ADB] Running 'C:\Users\deerai1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 7c9a8ac shell getprop ro.product.manufacturer'
[ADB] Current device property 'ro.product.manufacturer': OPPO
[AndroidDriver] No app sent in, not parsing package/activity
[AndroidDriver] No app capability. Assuming it is already on the device
[ADB] Getting install status for com.android.chrome
[ADB] Running 'C:\Users\deerai1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 7c9a8ac shell dumpsys package com.android.chrome'
[ADB] 'com.android.chrome' is installed
[ADB] Running 'C:\Users\deerai1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 7c9a8ac shell am force-stop com.android.chrome'
[ADB] Running 'C:\Users\deerai1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 7c9a8ac shell pm clear com.android.chrome'
[ADB] Running 'C:\Users\deerai1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 7c9a8ac shell pm clear com.android.chrome'
[AndroidDriver] Shutting down Android driver
[AndroidDriver] Called deleteSession but bootstrap wasn't active
[Logcat] Stopping logcat capture
[ADB] Running 'C:\Users\deerai1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 7c9a8ac shell am force-stop io.appium.unlock'
[AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[BaseDriver] Event 'newSessionStarted' logged at 1550641794650 (11:19:54 GMT+0530 (India Standard Time))
[W3C] Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\deerai1\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 7c9a8ac shell pm clear com.android.chrome' exited with code 1'; Stderr: 'Error: java.lang.SecurityException: adb clearing user data is forbidden.'; Code: '1'
[W3C]     at execFunc (C:\Program Files (x86)\Appium\resources\app\node_modules\appium-adb\lib\tools\system-calls.js:326:13)
[HTTP] <-- POST /wd/hub/session 500 12676 ms - 1222
[HTTP] 
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"browserName":"Chrome","platformName":"Android","deviceName":"7c9a8ac","platformVersion":"8.1.0"},"capabilities":{"firstMatch":[{"browserName":"Chrome","appium:deviceName":"7c9a8ac","platformName":"android","appium:platformVersion":"8.1.0"}]}}
[W3C] Calling AppiumDriver.createSession() with args: [{"browserName":"Chrome","platformName":"Android","deviceName":"7c9a8ac","platformVersion":"8.1.0"},null,{"firstMatch":[{"browserName":"Chrome","appium:deviceName":"7c9a8ac","platformName":"android","appium:platformVersion":"8.1.0"}]}]
[BaseDriver] Event 'newSessionRequested' logged at 1550642052010 (11:24:12 GMT+0530 (India Standard Time))
[Appium] Consider setting 'automationName' capability to 'UiAutomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.
[Appium] Creating new AndroidDriver (v4.8.0) session
[Appium] Capabilities:
[Appium]   browserName: Chrome
[Appium]   platformName: android
[Appium]   deviceName: 7c9a8ac
[Appium]   platformVersion: 8.1.0
[BaseDriver] W3C capabilities {"alwaysMatch":{"browserNam... and MJSONWP desired capabilities {"browserName":"Chrome","pl... were provided
[BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"browserNam...
[BaseDriver] Session created with session id: c814923c-d95c-403e-8680-913e7646e5c5
[AndroidDriver] Java version is: 1.8.0_191
[AndroidDriver] We're going to run a Chrome-based session
[AndroidDriver] Chrome-type package and activity are com.android.chrome and com.google.android.apps.chrome.Main
[AndroidDriver] Retrieving device list
[ADB] Trying to find a connected android device
[ADB] Getting connected devices...
[ADB] 2 device(s) connected
[AndroidDriver] Looking for a device with Android '8.1.0'
[ADB] Setting device id to 7c9a8ac
[ADB] Getting device platform version
[ADB] Running 'C:\Users\deerai1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 7c9a8ac shell getprop ro.build.version.release'
[ADB] Current device property 'ro.build.version.release': 8.1.0
[AndroidDriver] Using device: 7c9a8ac
[ADB] Setting device id to 7c9a8ac
[ADB] Running 'C:\Users\deerai1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 7c9a8ac shell getprop ro.build.version.sdk'
[ADB] Current device property 'ro.build.version.sdk': 27
[ADB] Device API level: 27
[AndroidDriver] Consider setting 'automationName' capability to 'uiautomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.
[AndroidDriver] App file was not listed, instead we're going to run com.android.chrome directly on the device
[AndroidDriver] Checking whether package is present on the device
[ADB] Running 'C:\Users\deerai1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 7c9a8ac shell pm list packages com.android.chrome'
[AndroidDriver] Starting Android session
[ADB] Running 'C:\Users\deerai1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 7c9a8ac wait-for-device'
[ADB] Running 'C:\Users\deerai1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 7c9a8ac shell echo ping'
[AndroidDriver] Pushing settings apk to device...
[ADB] Getting install status for io.appium.settings
[ADB] Running 'C:\Users\deerai1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 7c9a8ac shell dumpsys package io.appium.settings'
[ADB] 'io.appium.settings' is installed
[ADB] Getting package info for 'io.appium.settings'
[ADB] Running 'C:\Users\deerai1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 7c9a8ac shell dumpsys package io.appium.settings'
[ADB] The version code of the installed 'io.appium.settings' is greater than the application version code (17 > 13)
[ADB] There is no need to install/upgrade 'C:\Program Files (x86)\Appium\resources\app\node_modules\io.appium.settings\apks\settings_apk-debug.apk'
[ADB] Running 'C:\Users\deerai1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 7c9a8ac shell ps'
[AndroidDriver] io.appium.settings is already running. There is no need to reset its permissions.
[ADB] Device API level: 27
[ADB] Running 'C:\Users\deerai1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 7c9a8ac shell appops set io.appium.settings android\:mock_location allow'
[Logcat] Starting logcat capture
[ADB] Getting device platform version
[ADB] Running 'C:\Users\deerai1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 7c9a8ac shell getprop ro.build.version.release'
[ADB] Current device property 'ro.build.version.release': 8.1.0
[ADB] Running 'C:\Users\deerai1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 7c9a8ac shell wm size'
[ADB] Running 'C:\Users\deerai1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 7c9a8ac shell getprop ro.product.model'
[ADB] Current device property 'ro.product.model': RMX1801
[ADB] Running 'C:\Users\deerai1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 7c9a8ac shell getprop ro.product.manufacturer'
[ADB] Current device property 'ro.product.manufacturer': OPPO
[AndroidDriver] No app sent in, not parsing package/activity
[AndroidDriver] No app capability. Assuming it is already on the device
[ADB] Getting install status for com.android.chrome
[ADB] Running 'C:\Users\deerai1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 7c9a8ac shell dumpsys package com.android.chrome'
[ADB] 'com.android.chrome' is installed
[ADB] Running 'C:\Users\deerai1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 7c9a8ac shell am force-stop com.android.chrome'
[ADB] Running 'C:\Users\deerai1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 7c9a8ac shell pm clear com.android.chrome'
[ADB] Running 'C:\Users\deerai1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 7c9a8ac shell pm clear com.android.chrome'
[AndroidDriver] Shutting down Android driver
[AndroidDriver] Called deleteSession but bootstrap wasn't active
[Logcat] Stopping logcat capture
[ADB] Running 'C:\Users\deerai1\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 7c9a8ac shell am force-stop io.appium.unlock'
[AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[BaseDriver] Event 'newSessionStarted' logged at 1550642065677 (11:24:25 GMT+0530 (India Standard Time))
[W3C] Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\deerai1\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 7c9a8ac shell pm clear com.android.chrome' exited with code 1'; Stderr: 'Error: java.lang.SecurityException: adb clearing user data is forbidden.'; Code: '1'
[W3C]     at execFunc (C:\Program Files (x86)\Appium\resources\app\node_modules\appium-adb\lib\tools\system-calls.js:326:13)
[HTTP] <-- POST /wd/hub/session 500 13669 ms - 1222
[HTTP]

**Comment by mykola-mokhnach** [comment]
Duplicate of https://github.com/appium/appium/issues/12195
