### ISSUE TITLE
Can't run tests on some apks unless io.appium.settings is restarted

### ISSUE THREAD

**Issue by MilanJimi** [appium/appium#12193]
So I have this problem where I can not start my app, unless I kill io.appium.settings in adb.
How it woks is: The app will launch and close several times, but no tests will run. Then I get this message:
```
ERROR: An unknown server-side error occurred while processing the command. Original error: Cannot 
start the 'my.app.package' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-
running-appium/android/activity-startup.md for troubleshooting. Original error: Error executing adbExec. 
Original error: 'Command '/home/me/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am 
start -W -n my.app.package/host.exp.exponent.MainActivity -S -a android.intent.action.MAIN -c 
android.intent.category.LAUNCHER -f 0x10200000' exited with code null'; Stderr: ''; Code: 'null'
```

I can work around this by adb shell ps | grep appium and then
```
adb shell
su
kill {PID}
``` 
after which the test will start properly, but that is super annoying to do every time. Another option is by `adb shell am force-stop io.appium.settings`, but this one works only every second time (after a failed startup. Will not work if the test ran propely). Also, appium will NOT run any following tests.

Problem persists even if I run wdio via `adb shell am force-stop io.appium.settings && ./node_modules/.bin/wdio ./path/to/spec.js`. In this case, appium will once work and then once not and than work again - every other time. First time startup will NOT work. I guess this could have something to do with different starting states of io.appium.settings.

Server logs are both the same for running and not running case, until last shared command 
```
[debug] [ADB] Running '/home/me/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell 
am start -W -n my.app.package/host.exp.exponent.MainActivity -S -a android.intent.action.MAIN -c 
android.intent.category.LAUNCHER -f 0x10200000'
```
after which working case will continue as normal while bug case will cease activitiy and will rerun this command three times before exiting. This occurs on multiple computers as well (Ubuntu and Mac)

This has not been an issue with other APKs I have tried. Is there some type of Apks that Appium can't properly read? The one I mention here was created via `Expo.io `.

My capabilities:
```
    automationName: 'UiAutomator2',
    deviceName: 'Nexus_5_8.0',
    platformName: 'Android',
    platformVersion: '8.0',
    app: '/path/to/my.apk',
    appWaitActivity: '*',
    appWaitPackage: 'my.app.package',
```
With the last two having seemingly no impact.

using appium 1.11.0 and wdio 3.0.3

**Comment by mykola-mokhnach** [comment]
Did you read the troubleshooting article? Have you checked which activity is actually running there if the app is started manually with the command above? Have you checked the logcat output to make sure the app does not crash and operates properly?

**Comment by MilanJimi** [comment]
I read the troubleshooting article, none of the two suggestions are relevant.
Logcat says that the app opens the same way for both cases (`ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=sk.spps.skpay/host.exp.exponent.MainActivity} from uid 2000
`). 
App opens properly and is completely functional. Logcat says nothing about crashes.
Maybe UiAutomator can't connect properly to the session for some reason?

**Comment by MilanJimi** [comment]
Example apk with this bug: https://drive.google.com/open?id=1VJTYc_zKGIcanbn503OFIXYJWy3ZT538
This can also be created by building https://github.com/expo/examples/tree/master/with-redux boilerplate expo project with automatic signing
(just add 
```
"android": {
	"package": "my.app.package"
    }
```
to 'app.json')

**Comment by mykola-mokhnach** [comment]
Closed as inactive
