### ISSUE TITLE
Appium can not find ADB

### ISSUE THREAD

**Issue by karbon62** [appium/appium#12201]
## Unable to run Appium due to ADB despite route of the folder is correct 

Each time I run my Appium script it throws an error message that it can not find ADB. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac 10.14.3 
* Node.js version (unless using Appium.app|exe): Node v10.15.1
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: Android 7.0 
* Real device or emulator/simulator: None 
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Error Message throws up every time I run desired capabilities regarding ADB though this has been added correctly into Appium. 

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Please attach the full server log
