### ISSUE TITLE
iOS Predicate class chain - Support on Parent / Ancestor Element

### ISSUE THREAD

**Issue by climbwithme** [appium/appium#12207]
Does Predicate or Class Chain queries support finding parent / ancestor elements of the currently located element? 
Found from here (https://github.com/facebook/WebDriverAgent/wiki/Class-Chain-Queries-Construction-Rules) that finding descendant is possible. 
But couldn't get the details on the parent/ancestor elements.

**Comment by mykola-mokhnach** [comment]
This is not possible to implement, since there's no support from Apple side.

**Comment by climbwithme** [comment]
@mykola-mokhnach Thanks for the confirmation
