### ISSUE TITLE
find by image returns wrong coordinate

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#12209]
## The problem

The result of find_by_image returns wrong coordinate.

https://github.com/appium/appium-base-driver/blob/4eab674f92acfb1dd958fd48c9bbc9399d0d4e74/lib/basedriver/commands/find.js#L211 refers `display size`. The size is not screen size. `windows_rect` returns the size as non-bottom and notification bar. 

```
- @driver.window_rect
=> #<struct Selenium::WebDriver::Rectangle x=0, y=0, width=1080, height=1794> # Used for image
```

below is the actual screen size in an android device.

```
- screen_size
"deviceScreenSize"=>"1080x1920", # this is a part of session_capability
```

iOS case.

The return value is not 

```
@@driver.window_rect
=> #<struct Selenium::WebDriver::Rectangle x=0, y=0, width=375, height=667>
...

   "waitForQuiescence"=>true,
   "reduceMotion"=>true,
   "screenshotQuality"=>2,
   "sdkVersion"=>"11.4",
   "CFBundleIdentifier"=>"com.example.apple-samplecode.UICatalog",
   "pixelRatio"=>2,
   "statBarHeight"=>23.4375,
   "viewportRect"=>{"left"=>0, "top"=>47, "width"=>750, "height"=>1287}}>

# screenshot is `750 × 1334 pixels`
```

return `@@driver.action.move_to_location(109, 188.5).pointer_down(:left).release.perform` , but to tap `button`(test target image) correctly, they should be `@@driver.action.move_to_location(54.5, 94).pointer_down(:left).release.perform`
(The test data comes from ruby_lib_core’s sample) https://github.com/appium/ruby_lib_core/blob/master/test/functional/ios/ios/image_comparison_test.rb

To fix this, we need to calculate the coordinate based on screenshot's width/height and ratio base by `window_rect`

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Code To Reproduce Issue [ Good To Have ]

- Idea

1. Do template matching based on a screenshot size (Get x and y)
2. Scale the _x_ and _y_ to fit `@driver.window_rect`'s _x_.
    - _y_ depends on some elements such as hight of status bar.
    - _x_ is more reliable to consider device size to take an action to.
3. Returns the 2nd step's data
    - `element#rect` also returns the data

**Comment by mykola-mokhnach** [comment]
The window rect on Android is the size of the actual working area, which is available to UIA. It is not possible to perform any actions outside this area even thou the actual screen size is bigger.

**Comment by KazuCocoa** [comment]
Do you mean in below case cannot tap `x=540, y=1900` for example?

```
- @driver.window_rect
=> #<struct Selenium::WebDriver::Rectangle x=0, y=0, width=1080, height=1794> # Used for image
```

```
- screen_size
"deviceScreenSize"=>"1080x1920", # this is a part of session_capability
```

I thought so, but I could tap with w3c actions and `x=540, y=1900` as a home button "○" in below.

<img src='https://user-images.githubusercontent.com/5511591/53283533-4e96d380-378b-11e9-9b41-fed54cb0d246.png' width=200>

---

https://developer.android.com/reference/android/support/test/uiautomator/UiDevice#getdisplayheight is by `window_rect`
https://github.com/appium/appium-uiautomator2-server/blob/ce4b766cf702e9d0b8b2304b06a8fd00aaff8fd6/app/src/main/java/io/appium/uiautomator2/utils/DeviceInfoHelper.java (getRealSize) is by "deviceScreenSize"=>"1080x1920" in session_capabilities (The same as screenshot size.)

find_by_element should use this real size based width/height there.


iOS is another thing tho...

**Comment by mykola-mokhnach** [comment]
UIA2 subtracts the top and the bottom bars from the viewport, so all the element coordinates there are calculated relatively to this viewport. I would assume it is possible to use extended coordinates grid in W3C actions because they call the corresponding system APIs directly without interacting directly to UIA. However it is still a mess %)

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium-uiautomator2-server/pull/184 just FYI

**Comment by KazuCocoa** [comment]
🆗 thanks
I remember the mess...

btw, I found the root cause of the original issue.
In Android case, I can tap expected coordinate commenting out https://github.com/appium/appium-base-driver/blob/4eab674f92acfb1dd958fd48c9bbc9399d0d4e74/lib/basedriver/commands/find.js#L344-L359

We should update ratio calculation =>` if (screenAR === shotAR) {`

**Comment by nunessf** [comment]
Could this be related in any way to this issue I opened? #12174

**Comment by KazuCocoa** [comment]
No, since this is _find by image_ issue
