### ISSUE TITLE
Add ability to disable logcat capture

### ISSUE THREAD

**Issue by sshock** [appium/appium#12203]
Feature request

For performance reasons, e.g., when running appium over adb over tcp over wan with high latency, to reduce traffic it would be nice to have the ability to keep appium from capturing and sending all the logcat messages.

I believe it may be as simple as this patch to appium-android-driver, but I'm not familiar with appium so there could be more pieces involved.

```
diff --git a/lib/android-helpers.js b/lib/android-helpers.js
index d6e8b24..1c87f00 100644
--- a/lib/android-helpers.js
+++ b/lib/android-helpers.js
@@ -671,7 +671,12 @@ helpers.initDevice = async function (adb, opts) {
     await helpers.ensureDeviceLocale(adb, opts.language, opts.locale, opts.localeScript);
   }

-  await adb.startLogcat();
+  if (opts.skipLogCapture) {
+    logger.info(`'skipLogCapture' is set. Not running logcat.`);
+  } else {
+    await adb.startLogcat();
+  }
+
   if (opts.unicodeKeyboard) {
     return await helpers.initUnicodeKeyboard(adb);
   }
diff --git a/lib/desired-caps.js b/lib/desired-caps.js
index 923e91b..0967ede 100644
--- a/lib/desired-caps.js
+++ b/lib/desired-caps.js
@@ -186,6 +186,9 @@ let commonCapConstraints = {
   },
   skipDeviceInitialization: {
     isBoolean: true
+  },
+  skipLogCapture: {
+    isBoolean: true
   }
 };
```

**Comment by jumois** [comment]
@KazuCocoa could same be added for iOS?

See:
https://github.com/appium/appium/issues/10849

**Comment by KazuCocoa** [comment]
`startLogCapture` in:
- https://github.com/appium/appium-xcuitest-driver/blob/632d69710f3e4d6754e79c58a3a46d71e764d7da/lib/driver.js
- https://github.com/appium/appium-ios-driver/blob/5f60d4cb24713dd8ad00132ac9f49296db15b51f/lib/driver.js

let me try disabling them and ran some test cases if they can work without them.

**Comment by KazuCocoa** [comment]
- `skipLogCapture` for iOS
- `skipLogcatCapture` for Android
