### ISSUE TITLE
Connection is lost when calling Airplane mode (iOS)

### ISSUE THREAD

**Issue by DGandalf** [appium/appium#12200]
## The problem

When calling the airplane mode in iOS then the connection get lost.

## Environment

* Appium version (or git revision) that exhibits the issue: 10.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 10.14.3
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: iPhone XR with iOS 12.2 Beta 3
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: Appium exe

## Details

Just open the Preferences and go to the Airplane setting and enable it. Confirm the switch on in the occurring confirmation dialog.
 
After that, the connection is lost.

## Link to Appium logs

Log from Appium app:
Could not obtain source: {"cause":{"sessionId":"d544f515-163c-4082-a091-0ede0d19aa8e","status":13,"value":{"message":"An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up"}},"jsonwire-error":{"detail":"An unknown server-side error occurred while processing the command.","status":13,"summary":"UnknownError"},"message":"[source()] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up","status":13}

And Log of Appium-Interface
[Xcode]     t =    45.55s Find: Identity Binding
[Xcode] 14:39:03.512 WebDriverAgentRunner-Runner[812:118305] Found matches {(
[Xcode]     Button, {{8.0, 740.0}, {398.0, 57.0}}, label: 'Flugmodus aktivieren'
[Xcode] )} with root Application, pid: 815, label: 'Einstellungen'
[Xcode] 14:39:03.513 WebDriverAgentRunner-Runner[812:118305] Computing hit point for Button, {{8.0, 740.0}, {398.0, 57.0}}, label: 'Flugmodus aktivieren'
[Xcode] 14:39:03.513 WebDriverAgentRunner-Runner[812:118305] Creating future for 'Fetching attributes 'XC_kAXXCAttributeVisiblePoint', 'XC_kAXXCAttributeWindowContextId', 'XC_kAXXCAttributeWindowDisplayId' for AX element pid: 815, elementOrHash.elementID: 4341729920.329' with timeout 65.00
[Xcode] 14:39:03.513 WebDriverAgentRunner-Runner[812:118305]  entering wait loop for 65.00s with expectations: `Fetching attributes 'XC_kAXXCAttributeVisiblePoint', 'XC_kAXXCAttributeWindowContextId', 'XC_kAXXCAttributeWindowDisplayId' for AX element pid: 815, elementOrHash.elementID: 4341729920.329`
[Xcode] 14:39:03.517 WebDriverAgentRunner-Runner[812:118323] Got attribute fetch response with values {
[Xcode]     "XC_kAXXCAttributeVisiblePoint" =     {
[Xcode]         X = 207;
[Xcode]         Y = "768.5";
[Xcode]     };
[Xcode]     "XC_kAXXCAttributeWindowContextId" = 3445587756;
[Xcode]     "XC_kAXXCAttributeWindowDisplayId" = 1;
[Xcode] }, error: (null)
[Xcode] 14:39:03.517 WebDriverAgentRunner-Runner[812:118323] : cancelWaiting
[Xcode] 14:39:03.517 WebDriverAgentRunner-Runner[812:118305]  done waiting
[Xcode] 14:39:03.517 WebDriverAgentRunner-Runner[812:118305] Canceling watchdog for .
[Xcode] 14:39:03.517 WebDriverAgentRunner-Runner[812:118305]  cleaning up `Fetching attributes 'XC_kAXXCAttributeVisiblePoint', 'XC_kAXXCAttributeWindowContextId', 'XC_kAXXCAttributeWindowDisplayId' for AX element pid: 815, elementOrHash.elementID: 4341729920.329`
[Xcode] 14:39:03.517 WebDriverAgentRunner-Runner[812:118305] Creating future for 'Getting parameterized attribute XC_kAXXCParameterizedAttributeConvertHostedViewPositionFromContext with parameter (
[Xcode]         {
[Xcode]         X = 207;
[Xcode]         Y = "768.5";
[Xcode]     },
[Xcode]     3445587756,
[Xcode]     1
[Xcode] )' with timeout 65.00
[Xcode] 14:39:03.518 WebDriverAgentRunner-Runner[812:118305]  entering wait loop for 65.00s with expectations: `Getting parameterized attribute XC_kAXXCParameterizedAttributeConvertHostedViewPositionFromContext with parameter (
[Xcode]         {
[Xcode]         X = 207;
[Xcode]         Y = "768.5";
[Xcode]     },
[Xcode]     3445587756,
[Xcode]     1
[Xcode] )`
[Xcode] 14:39:03.519 WebDriverAgentRunner-Runner[812:118324] : cancelWaiting
[Xcode] 14:39:03.519 WebDriverAgentRunner-Runner[812:118305]  done waiting
[Xcode] 14:39:03.519 WebDriverAgentRunner-Runner[812:118305] Canceling watchdog for .
[Xcode] 14:39:03.519 WebDriverAgentRunner-Runner[812:118305]  cleaning up `Getting parameterized attribute XC_kAXXCParameterizedAttributeConvertHostedViewPositionFromContext with parameter (
[Xcode]         {
[Xcode]         X = 207;
[Xcode]         Y = "768.5";
[Xcode]     },
[Xcode]     3445587756,
[Xcode]     1
[Xcode] )`
[Xcode] 14:39:03.629 WebDriverAgentRunner-Runner[812:118324] Handling kAXUserTestingNotification
[Xcode] 14:39:03.635 WebDriverAgentRunner-Runner[812:118324] Handling kAXUserTestingNotification
[Xcode] 14:39:04.078 WebDriverAgentRunner-Runner[812:118324] Handling kAXUserTestingNotification
[Xcode] 14:39:04.246 WebDriverAgentRunner-Runner[812:118305] Creating future for 'Fetching attributes for Device system-wide element' with timeout 65.00
[Xcode] 14:39:04.247 WebDriverAgentRunner-Runner[812:118305]  entering wait loop for 65.00s with expectations: `Fetching attributes for Device system-wide element`
[Xcode] 14:39:04.248 WebDriverAgentRunner-Runner[812:118323] : cancelWaiting
[Xcode] 14:39:04.248 WebDriverAgentRunner-Runner[812:118305]  done waiting
[Xcode] 14:39:04.249 WebDriverAgentRunner-Runner[812:118305] Canceling watchdog for .
[Xcode] 14:39:04.249 WebDriverAgentRunner-Runner[812:118305]  cleaning up `Fetching attributes for Device system-wide element`
[Xcode] 14:39:04.249 WebDriverAgentRunner-Runner[812:118305] Creating future for 'Fetching attributes for AX element pid: 52, elementOrHash.elementID: 0.1' with timeout 65.00
[Xcode] 14:39:04.250 WebDriverAgentRunner-Runner[812:118305]  entering wait loop for 65.00s with expectations: `Fetching attributes for AX element pid: 52, elementOrHash.elementID: 0.1`
[Xcode] 14:39:05.292 WebDriverAgentRunner-Runner[812:118323] : cancelWaiting
[Xcode] 14:39:05.293 WebDriverAgentRunner-Runner[812:118305]  done waiting
[Xcode] 14:39:05.293 WebDriverAgentRunner-Runner[812:118305] Canceling watchdog for .
[Xcode] 14:39:05.293 WebDriverAgentRunner-Runner[812:118305]  cleaning up `Fetching attributes for AX element pid: 52, elementOrHash.elementID: 0.1`
[Xcode] 14:39:05.293 WebDriverAgentRunner-Runner[812:118305] Active application elements: (
[Xcode]     "AX element pid: 815, elementOrHash.elementID: 0.1"
[Xcode] )
[Xcode] 14:39:05.294 WebDriverAgentRunner-Runner[812:118305] Creating future for 'Fetching attributes for Device system-wide element' with timeout 65.00
[Xcode] 14:39:05.296 WebDriverAgentRunner-Runner[812:118305]  entering wait loop for 65.00s with expectations: `Fetching attributes for Device system-wide element`
[Xcode] 14:39:05.296 WebDriverAgentRunner-Runner[812:118428] : cancelWaiting
[Xcode] 14:39:05.297 WebDriverAgentRunner-Runner[812:118305]  done waiting
[Xcode] 14:39:05.297 WebDriverAgentRunner-Runner[812:118305] Canceling watchdog for .
[Xcode] 14:39:05.297 WebDriverAgentRunner-Runner[812:118305]  cleaning up `Fetching attributes for Device system-wide element`
[Xcode] 14:39:05.297 WebDriverAgentRunner-Runner[812:118305] Creating future for 'Fetching attributes for AX element pid: 52, elementOrHash.elementID: 0.1' with timeout 65.00
[Xcode] 14:39:05.298 WebDriverAgentRunner-Runner[812:118305]  entering wait loop for 65.00s with expectations: `Fetching attributes for AX element pid: 52, elementOrHash.elementID: 0.1`
[Xcode] 14:39:05.299 WebDriverAgentRunner-Runner[812:118324] : cancelWaiting
[Xcode] 14:39:05.299 WebDriverAgentRunner-Runner[812:118305]  done waiting
[Xcode] 14:39:05.299 WebDriverAgentRunner-Runner[812:118305] Canceling watchdog for .
[Xcode] 14:39:05.299 WebDriverAgentRunner-Runner[812:118305]  cleaning up `Fetching attributes for AX element pid: 52, elementOrHash.elementID: 0.1`
[Xcode] 14:39:05.299 WebDriverAgentRunner-Runner[812:118305] Active application elements: (
[Xcode]     "AX element pid: 815, elementOrHash.elementID: 0.1"
[Xcode] )
[Xcode] 14:39:05.300 WebDriverAgentRunner-Runner[812:118305] -[UITestingUITests testRunner] started activity  2019-02-21 13:39:05 +0000: Find the Application 'com.apple.Preferences'
[Xcode]     t =    47.34s Find the Application 'com.apple.Preferences'
[Xcode] 14:39:05.296 xcodebuild[17293:3364480] -[UITestingUITests testRunner] will start activity  2019-02-21 13:39:05 +0000: Find the Application 'com.apple.Preferences'
[Xcode] 14:39:05.301 WebDriverAgentRunner-Runner[812:118305] Checking for possible remote query evaluation: hasAutomationSession: NO, supportsRemoteEvaluation: YES
[Xcode] 14:39:05.301 WebDriverAgentRunner-Runner[812:118305] Evaluating query  with transformers (
[Xcode] )
[Xcode] 14:39:05.301 WebDriverAgentRunner-Runner[812:118305] Getting root element snapshot for query 
[Xcode] 14:39:05.301 WebDriverAgentRunner-Runner[812:118305] Getting snapshot for App element pid: 815 for query 
[Xcode]     t =    47.34s     Snapshot accessibility hierarchy for app with pid 815
[Xcode] 14:39:05.301 WebDriverAgentRunner-Runner[812:118305] Query requires snapshot attributes .
[Xcode] 14:39:05.301 WebDriverAgentRunner-Runner[812:118305] -[UITestingUITests testRunner] started activity  2019-02-21 13:39:05 +0000: Snapshot accessibility hierarchy for app with pid 815
[Xcode] 14:39:05.297 xcodebuild[17293:3364480] -[UITestingUITests testRunner] will start activity  2019-02-21 13:39:05 +0000: Snapshot accessibility hierarchy for app with pid 815
[Xcode] 14:39:05.303 WebDriverAgentRunner-Runner[812:118305] Checked support for truncated value on iOS: YES, current version 12 (201), requires 12 (any build)
[Xcode] 14:39:05.303 WebDriverAgentRunner-Runner[812:118305] Fetching snapshot for App element pid: 815 from testmanagerd with attributes XC_kAXXCAttributeElementType, XC_kAXXCAttributeElementBaseType, XC_kAXXCAttributeParent, XC_kAXXCAttributeIdentifier, XC_kAXXCAttributeTraits and parameters {
[Xcode]     maxArrayCount = 2147483647;
[Xcode]     maxChildren = 2147483647;
[Xcode]     maxDepth = 2147483647;
[Xcode]     traverseFromParentsToChildren = 1;
[Xcode] }.
[Xcode] 14:39:05.303 WebDriverAgentRunner-Runner[812:118305] Creating future for 'Fetching snapshot from testmanagerd.' with timeout 65.00
[Xcode] 14:39:05.304 WebDriverAgentRunner-Runner[812:118305]  entering wait loop for 65.00s with expectations: `Fetching snapshot from testmanagerd.`
[Xcode] 14:39:05.436 WebDriverAgentRunner-Runner[812:118428] Got snapshot response from testmanagerd.
[Xcode] 14:39:05.436 WebDriverAgentRunner-Runner[812:118428] : cancelWaiting
[Xcode] 14:39:05.436 WebDriverAgentRunner-Runner[812:118305]  done waiting
[Xcode] 14:39:05.436 WebDriverAgentRunner-Runner[812:118305] Canceling watchdog for .
[Xcode] 14:39:05.436 WebDriverAgentRunner-Runner[812:118305]  cleaning up `Fetching snapshot from testmanagerd.`
[Xcode] 14:39:05.437 WebDriverAgentRunner-Runner[812:118305] -[UITestingUITests testRunner] finished activity  2019-02-21 13:39:05 +0000: Snapshot accessibility hierarchy for app with pid 815 (0.135569s)
[Xcode] 14:39:05.432 xcodebuild[17293:3364480] -[UITestingUITests testRunner] did finish activity  2019-02-21 13:39:05 +0000: Snapshot accessibility hierarchy for app with pid 815 (0.135569s)
[Xcode] 14:39:05.438 WebDriverAgentRunner-Runner[812:118305] Found matches {(
[Xcode]     
[Xcode] )} with root 
[Xcode] 14:39:05.438 WebDriverAgentRunner-Runner[812:118305] -[UITestingUITests testRunner] finished activity  2019-02-21 13:39:05 +0000: Find the Application 'com.apple.Preferences' (0.138636s)
[Xcode] 14:39:05.433 xcodebuild[17293:3364480] -[UITestingUITests testRunner] did finish activity  2019-02-21 13:39:05 +0000: Find the Application 'com.apple.Preferences' (0.138636s)
[Xcode] 14:39:05.775 xcodebuild[17293:3364602] Returning existing connection for AMDevice 0x7fa84f6e3b50 {UDID = 00008020-001911923628002E, device ID = 17, location ID = 0x14310000, product ID = 0x12a8}: : Wired, 0x14310000
[Xcode] 14:39:05.775 xcodebuild[17293:3364480] 📱 ################ HAS DIS CONNECTED ###################
[Xcode] 14:39:05.777 xcodebuild[17293:3364480] 📱 ############## DID EXECUTE #################
[Xcode] 14:39:05.778 xcodebuild[17293:3364480]  finished receiving data from testing launch session
[Xcode] 14:39:05.778 xcodebuild[17293:3364480] : _considerFlushingDelegateBlockQueue - nothing to flush
[Xcode] 14:39:05.778 xcodebuild[17293:3364480] Test operation failure: Encountered a problem with the test runner after launch
[Xcode] 14:39:05.778 xcodebuild[17293:3364480] _finishWithError:Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Encountered a problem with the test runner after launch" UserInfo={NSLocalizedDescription=Encountered a problem with the test runner after launch, NSUnderlyingError=0x7fa84f965100 {Error Domain=com.apple.platform.iphoneos Code=-13 "Lost connection to DTServiceHub" UserInfo={NSLocalizedDescription=Lost connection to DTServiceHub}}}

**Comment by mykola-mokhnach** [comment]
This behaviour is expected. As a workaround you might try to stop driver and then start it again, but there is nothing else that can be done on Appium side.
