### ISSUE TITLE
Get value of input elements is not W3C compliant

### ISSUE THREAD

**Issue by christian-bromann** [appium/appium#12218]
## The problem

With the introduction of the WebDriver spec getting a value from a specific input element is handled via:

```
session/{sessionId}/element/5000/property/value
```

endpoint. However this fails in Appium for iOS and Android (web testing):

- iOS: `Method has not yet been implemented`
- Android: `404 - "unknown command:`

See also webdriverio/webdriverio#3606

## Environment

* Appium version (or git revision) that exhibits the issue: latest
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 10.13
* Node.js version (unless using Appium.app|exe): 10.x
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: iOS and Android
* Real device or emulator/simulator: both
* Appium CLI or Appium.app|exe: cli

## Details

See above.

## Link to Appium logs

Not existing but can provide them if necessary.

**Comment by dpgraham** [comment]
We do have this endpoint implemented on the base driver: https://github.com/appium/appium-base-driver/blob/master/lib/protocol/routes.js#L630

But it's not implemented by any of the drivers. We already have `getAttribute` which retrieves the attribute values of the elements, as they appear in the source XML.

What values would we expect the element properties to return?

**Comment by mykola-mokhnach** [comment]
@dpgraham It is just necessary to setup the W3C<>JSONWP conversion in the base driver. The fact that servers don't have such endpoint is ok, since neither of them supports W3C

**Comment by dpgraham** [comment]
That's what I was thinking. I just wasn't sure if there was a valid implementation of `getProperty` that we should be applying to the drivers.

**Comment by christian-bromann** [comment]
> What values would we expect the element properties to return?

In the web context you need to use [`getProperty`](https://w3c.github.io/webdriver/#get-element-property) to receive the value of e.g. an input element. The endpoints should be implemented in chromedriver or safaridriver.

**Comment by dpgraham** [comment]
@christian-bromann do you mind sharing logs? It's probably a proxying issue.

**Comment by mykola-mokhnach** [comment]
@dpgraham Have you seen https://stackoverflow.com/questions/43627340/what-is-the-difference-between-property-and-attribute-in-selenium-webelement ?

Does it make sense to split `attribute` and `property` definitions for native Appium context? Also, I'm not quite sure about what to do with web contexts. chromedriver and Safari debugger work in MJSONWP mode, so they don't respond to `getProperty` call. Should we simply return the same as we get from getAttribute call?

**Comment by dpgraham** [comment]
@mykola-mokhnach no I'm fine leaving it the way it is, natively, and just not support `getProperty`. I just want to see why it's not working in web.

**Comment by dpgraham** [comment]
@christian-bromann do you have example logs for this?

**Comment by dpgraham** [comment]
I think I understand the issue now.

JSONWP doesn't have a generic `/:value` endpoint. It just has hardcoded attributes: `name`, `location`, `location_in_view`, etc....

I'll just need to adjust the proxy so that the W3C url gets proxied to the equivalent MJSONWP endpoint.
