### ISSUE TITLE
No Simulation SDK version are available in your system. Please install some via XCode Preferences

### ISSUE THREAD

**Issue by sinapsist** [appium/appium#12210]
## The problem

Appium cannot connect to simctl to get list of available simulators. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0
* Desktop OS/version used to run Appium: macOS Mojave 10.14.3
* Node.js version (unless using Appium.app|exe): 10.15.1
* Npm or Yarn package manager: 6.4.1
* Mobile platform/version under test: iOS 12.0 iPhone X (but actually any)
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium.app

## Details

Part of xcrun simctl list showing that right version is there and booted

-- iOS 12.0 --
...

    iPhone X (4D5F7B32-5FAE-4CAA-BD84-ED4E1E80C7C0) (Booted) 

    iPhone XS (E2187303-10EF-4608-8DA8-46517A4942B6) (Shutdown) 
    iPhone XS Max (8B7C8B85-CC5D-4627-8447-8ACAF84AE2C1) (Shutdown) 
    iPhone XR (4B45CC16-29E3-4470-928D-ABC4A0F2CDFA) (Shutdown) 
    iPad Air (4294A820-41AA-409F-AB8E-29BF9ADC5A9D) (Shutdown) 
    iPad Air 2 (7DFE0DF0-9FB3-4525-8A0A-BDB23416D2AE) (Shutdown) 
    iPad (5th generation) (B2F9D74F-6BA6-46A7-8848-090C7FA6DF08) (Shutdown) 
    iPad Pro (9.7-inch) (16E5B4A9-6A87-4470-ABD9-36D210F01B78) (Shutdown) 
    iPad Pro (12.9-inch) (5D00078E-9497-485D-B45A-8FC58B75FF40) (Shutdown) 
    iPad Pro (12.9-inch) (2nd generation) (D5AB13BF-670A-452D-B3E6-5812C1148B94) (Shutdown) 
    iPad Pro (10.5-inch) (3083A857-5457-479A-AC22-DB17F0496EFE) (Shutdown) 
    iPad (6th generation) (02067CC7-266A-4F44-998F-45E0EAB70ADF) (Shutdown)
## Link to Appium logs

[Appium] Welcome to Appium v1.10.0
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"automationName":"XCUITest","browserName":"safari","deviceName":"iPhone X","deviceOrientation":"portait","platformName":"iOS","platformVersion":"12.0","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"automationName":"XCUITest","browserName":"safari","deviceName":"iPhone X","deviceOrientation":"portait","platformName":"iOS","platformVersion":"12.0","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1550895067910 (20:11:07 GMT-0800 (PST))
[Appium] Creating new XCUITestDriver (v2.104.0) session
[Appium] Capabilities:
[Appium]   automationName: XCUITest
[Appium]   browserName: safari
[Appium]   deviceName: iPhone X
[Appium]   platformName: iOS
[Appium]   platformVersion: 12.0
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[BaseDriver] Creating session with MJSONWP desired capabilities: {"automationName":"XCUITest...
[BaseDriver] Session created with session id: 19754db1-9508-42e1-a885-e46fe6e2f89b
[XCUITest] Current user: 'test'
[XCUITest] Error: '12.0' does not exist in the list of simctl SDKs. No Simulator SDK versions are available on your system. Please install some via Xcode preferences.
[XCUITest]     at /Applications/Appium.app/Contents/Resources/app/node_modules/node-simctl/lib/simctl.js:551:13
[XCUITest]     at Generator.next ()
[XCUITest]     at asyncGeneratorStep (/Applications/Appium.app/Contents/Resources/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
[XCUITest]     at _next (/Applications/Appium.app/Contents/Resources/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
[XCUITest]     at run (/Applications/Appium.app/Contents/Resources/app/node_modules/core-js/modules/es6.promise.js:75:22)
[XCUITest]     at /Applications/Appium.app/Contents/Resources/app/node_modules/core-js/modules/es6.promise.js:92:30
[XCUITest]     at flush (/Applications/Appium.app/Contents/Resources/app/node_modules/core-js/modules/_microtask.js:18:9)
[XCUITest]     at process._tickCallback (internal/process/next_tick.js:61:11)
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[BaseDriver] Event 'newSessionStarted' logged at 1550895068111 (20:11:08 GMT-0800 (PST))
[MJSONWP] Encountered internal error running command: Error: '12.0' does not exist in the list of simctl SDKs. No Simulator SDK versions are available on your system. Please install some via Xcode preferences.
[MJSONWP]     at /Applications/Appium.app/Contents/Resources/app/node_modules/node-simctl/lib/simctl.js:551:13
[MJSONWP]     at Generator.next ()
[MJSONWP]     at asyncGeneratorStep (/Applications/Appium.app/Contents/Resources/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
[MJSONWP]     at _next (/Applications/Appium.app/Contents/Resources/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
[MJSONWP]     at run (/Applications/Appium.app/Contents/Resources/app/node_modules/core-js/modules/es6.promise.js:75:22)
[MJSONWP]     at /Applications/Appium.app/Contents/Resources/app/node_modules/core-js/modules/es6.promise.js:92:30
[MJSONWP]     at flush (/Applications/Appium.app/Contents/Resources/app/node_modules/core-js/modules/_microtask.js:18:9)
[MJSONWP]     at process._tickCallback (internal/process/next_tick.js:61:11)
[HTTP] <-- POST /wd/hub/session 500 203 ms - 285
[HTTP] 
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 3 ms - 57
[HTTP] 

## Code To Reproduce Issue [ Good To Have ]
This is my capabilities that I am using and I am using Appium UI in my connection test:
{
  "automationName": "XCUITest",
  "platformVersion": "12.0",
  "platformName": "iOS",
  "deviceName": "iPhone X",
  "browserName": "safari"
}

**Comment by sinapsist** [comment]
Simulator's list 
![components](https://user-images.githubusercontent.com/10706087/53281556-5c8f1a80-36df-11e9-8e3b-be21e61c2e14.png)

**Comment by KazuCocoa** [comment]
Did you try 1.11.x? https://github.com/appium/appium/releases/tag/v1.11.0
That supports Xcode 10.2 simulator list

**Comment by sinapsist** [comment]
I tried to install it thought npm and I am getting this error:

macTest:~ tester$ sudo npm install -g appium

npm WARN deprecated fsevents@2.0.1: Not Ready For Production
/usr/local/bin/appium -> /usr/local/lib/node_modules/appium/build/lib/main.js

> appium-chromedriver@4.10.1 install /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver
> node install-npm.js

(node:9020) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/2019122-9020-1qhji9r.tutli'
(node:9020) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9020) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[21:10:11] [Chromedriver Install] Installing Chromedriver version '2.45' for platform 'mac' and architecture '64'
[21:10:11] [Chromedriver Install] Opening temp file to write 'chromedriver_mac64' to...
Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/2019122-9020-7b56eh.8wvam'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-chromedriver@4.10.1 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium-chromedriver@4.10.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

And if I go to this folder I cannot see appium folder there 
/usr/local/lib/node_modules/

![node_modules](https://user-images.githubusercontent.com/10706087/53282063-52711a00-36e7-11e9-945c-e61bf11ea795.png)

**Comment by sinapsist** [comment]
As a possible solution should I roll back to Xcode 9.3?

**Comment by sinapsist** [comment]
And I am not sure if it make a difference, but my Xcode version is 10.1

![locations](https://user-images.githubusercontent.com/10706087/53282190-3ec6b300-36e9-11e9-8a57-6b9ea0200d2a.png)

**Comment by KazuCocoa** [comment]
I haven't installed `npm` with sudo permission, so I can only say make sure the permission...

What the output of `$ xcrun simctl list devices -j`?
Appium parses the result. The format changes a bit from 10.2. So, 10.1 should work fine if the command returns correct result.

**Comment by sinapsist** [comment]
You actually right, CoreSimulator.framework uses 10.2 version. I replaced it for now with a package from this solution https://github.com/appium/appium/issues/11621 and it works now. Thank you so much!

**Comment by KazuCocoa** [comment]
glad to hear that 👍

**Comment by sinapsist** [comment]
Speaking about appium, I actually tried both with sudo and without sudo. Non of them 
macTest:~ tester$ npm install -g appium
npm WARN deprecated fsevents@2.0.1: Not Ready For Production
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

**Comment by KazuCocoa** [comment]
I guess you should avoid the path like https://stackoverflow.com/questions/14469515/how-to-npm-install-to-a-specified-directory
(Or use npm via nodebrew in user location, for example)

**Comment by sinapsist** [comment]
Got it. Thank you again for support!

**Comment by djangofan** [comment]
I had this same problem, and after fiddling the solution for me was to:
```
brew uninstall carthage --force
brew install carthage
```
