### ISSUE TITLE
MobileBy.AccessibilityId throws invalidOperationException

### ISSUE THREAD

**Issue by caifancito** [appium/appium#12216]
## The problem

Using:

vbnet, appium-dotnet-driver 3.0.0.2, Appium 1.9.1

This is the line of code that is throwing the exception. 

DriverWait.Until(ExpectedConditions.ElementIsVisible(MobileBy.AccessibilityId(fieldName)))

This is the exception:

Exception thrown: ‘System.InvalidOperationException’ : Method is not implemented

## Environment

* Appium version:  Appium 1.9.1
* Desktop OS/version used to run Appium: MacOS High Sierra
* Mobile platform/version under test: iOS and Android
* Real device or emulator/simulator: Simulator and Emulator
* Appium.app
* Using UIautomator2

## Link to Appium logs

https://gist.github.com/caifancito/158b6e8f81e4da3604f6e3a4fa54a11c

## Code To Reproduce Issue [ Good To Have ]

DriverWait.Until(ExpectedConditions.ElementIsVisible(MobileBy.AccessibilityId(fieldName)))

Is there a way to get around this? Thanks!

**Comment by mykola-mokhnach** [comment]
This is a problem of the client itself. Please make sure it is up to date. Closed as not an issue
