### ISSUE TITLE
selectPickerWheel didn't respond to the next value and user's action tap

### ISSUE THREAD

**Issue by LayMuiToh** [appium/appium#12214]
## The problem

The selectPickerWheel didn't move to the next value and also it didn't respond to the mobile: tap on the Done button. see attached screenshot.
 

![image](https://user-images.githubusercontent.com/39483242/53292877-ad4c6380-3804-11e9-8537-9a5dba880316.png)
my code snippet:
 if (MoreFilters.picker.waitForVisible()) {
            browser.execute('mobile: selectPickerWheelValue', 
          { element: MoreFilters.picker.ELEMENT, order: 'next', offset: 0.5});

          if(MoreFilters.done.waitForVisible()){
          const done_x = browser.getLocation('~Done', 'x');
          const done_y = browser.getLocation('~Done', 'y');
          browser.execute('mobile: tap', { element: MoreFilters.done.ELEMENT, x: done_x, y: done_y});
          }

when running the test: it shows this message to appium
An unknown server-side error occurred while processing the command. Original error: Element id is expected to be set for selectPickerWheelValue method

**Comment by LayMuiToh** [comment]
https://gist.github.com/LayMuiToh/2ff2defea7b39672628a6fa97c8d514c

**Comment by mykola-mokhnach** [comment]
The attached log does not seem to be relevant

**Comment by LayMuiToh** [comment]
https://gist.github.com/LayMuiToh/ec7e59f5aaf30763c6111c6288af8fe7

**Comment by LayMuiToh** [comment]
appiumVersion: '1.10.1',
        platformVersion: '10.3',
        platformName: 'iOS',

**Comment by mykola-mokhnach** [comment]
I still don't observe any occurrences of `selectPickerWheelValue` or `/execute` in the log

**Comment by LayMuiToh** [comment]
I have updated the gist above. 
[35m[HTTP][39m [90m{"script":"mobile: selectPickerWheelValue","args":[{"order":"next","offset":0.5}]}[39m
[debug] [35m[MJSONWP (2aaa2e37)][39m Calling AppiumDriver.execute() with args: ["mobile: selectPickerWheelValue",[{"order":"next","offset":0.5}],"2aaa2e37-0da8-4a09-971c-9ce9e46e51f0"]
[debug] [35m[XCUITest][39m Executing command 'execute'
[35m[XCUITest][39m Error: Element id is expected to be set for selectPickerWheelValue method
[35m[XCUITest][39m     at Object.wrappedLogger.errorAndThrow (/Users/tohlaymui/.nvm/versions/node/v10.15.1/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-support/lib/logging.js:78:13)

**Comment by mykola-mokhnach** [comment]
I assume the error message is clear. The id of the element is missing from the arguments

**Comment by LayMuiToh** [comment]
But I have supplied the value:MoreFilters.picker.ELEMENT
 browser.execute('mobile: selectPickerWheelValue', 
            { element: MoreFilters.picker.ELEMENT, order: 'next', offset: 0.5});

**Comment by LayMuiToh** [comment]
what does it mean by id? I used accessibilityLabel and accessibility Inspector, the label is Picker

**Comment by LayMuiToh** [comment]
it works for this command:
 browser.execute('mobile: tap', 
  { element: MoreFilters.filter_by_date, x: filter_by_date_x, y: filter_by_date_y});
          

but not for the selectPickerWheelValue:
          if (MoreFilters.picker.waitForVisible()) {
            console.log('Picker appear');
            browser.execute('mobile: selectPickerWheelValue', 
            { element: MoreFilters.picker.ELEMENT, order: 'next', offset: 0.5});

**Comment by LayMuiToh** [comment]
Is this a bug in appium mobile command in selectPickerWheelValue?
http://appium.io/docs/en/writing-running-appium/ios/ios-xctest-mobile-gestures/index.html#mobile-tap

**Comment by mykola-mokhnach** [comment]
> [35m[HTTP]�[39m �[90m{"script":"mobile: selectPickerWheelValue","args":[{"order":"next","offset":0.5}]}�[39m

You can see here that `element` attribute is missing in the incoming server request, so from Appium perspective the behaviour described above looks correct

**Comment by LayMuiToh** [comment]
it's not this error, I have already set the element: MoreFilters.picker.ELEMENT

it is this ERROR here: 
[35m[XCUITest]�[39m Error: Element id is expected to be set for selectPickerWheelValue method
�[35m[XCUITest]�[39m     at Object.wrappedLogger.errorAndThrow (/Users/tohlaymui/.nvm/versions/node/v10.15.1/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-support/lib/logging.js:78:13)

why does it say Element id is expected when I have already supplied the value 
which is MoreFilters.picker.ELEMENT??

**Comment by mykola-mokhnach** [comment]
I'm just saying what I see in the log. Maybe one would be able find a bug there, but not me.

**Comment by KazuCocoa** [comment]
> element: PickerWheel's internal element id (as hexadecimal hash string) to perform value selection on. The element must be of type XCUIElementTypePickerWheel. Mandatory parameter

http://appium.io/docs/en/writing-running-appium/ios/ios-xctest-mobile-gestures/index.html#mobile-selectpickerwheelvalue

Was `element: MoreFilters.picker.ELEMENT` element id?
e.g.

```ruby
# Ruby
el = driver.find_element :accessibility_id, 'target picker'
@driver.execute_script 'mobile: selectPickerWheelValue', { element: el.ref, order: :next }
```

```java
// Java
JavascriptExecutor js = (JavascriptExecutor) driver;
Map<String, Object> params = new HashMap<>();
params.put("order", "next");
params.put("offset", 0.15);
params.put("element", ((RemoteWebElement) element).getId());
js.executeScript("mobile: selectPickerWheelValue", params);
```

Then, as https://github.com/appium/appium/issues/12214#issuecomment-466771250 addresses, `element` attribute should be in a requet.

**Comment by LayMuiToh** [comment]
Can I know what is the example for Javascript?
I used 
  browser.execute('mobile: selectPickerWheelValue', 
            { element: MoreFilters.picker.ref, order: 'next', offset: 0.5});

it gives me this error: 
An unknown server-side error occurred while processing the command. Original error: Element id is expected to be set for selectPickerWheelValue method
running
Error: An unknown server-side error occurred while processing the command.
    at execute("mobile: selectPickerWheelValue", [object Object]) - index.js:312:3

**Comment by KazuCocoa** [comment]
Not sure what JS client you used. But you can find the way to get element id from the element object.

e.g.
webdriveid is perhapse `element.elementId`
wd is perhapse `element.value.tostring()`

**Comment by LayMuiToh** [comment]
Hi Kazu.
I am using webdriverio
I used  browser.execute('mobile: selectPickerWheelValue', 
            { element: MoreFilters.picker**.elementId,** order: 'next', offset: 0.5});
 I still get the error:
An unknown server-side error occurred while processing the command. Original error: Element id is expected to be set for selectPickerWheelValue method
running
Error: An unknown server-side error occurred while processing the command.
    at execute("mobile: selectPickerWheelValue", [object Object]) - index.js:312:3

**Comment by KazuCocoa** [comment]
> at execute("mobile: selectPickerWheelValue", [object Object]) - index.js:312:3

`[object Object]` is JS _object_.
You probably can get element id which is in the object by somehow, maybe...
My suggestion was current master, v5.6.2. (I glanced the repository and assumed so)

You can ask it to them how to get element id via the element object. Then, I guess you can set element id properly.

**Comment by LayMuiToh** [comment]
Hi Kaza
can you give me the link to the repository?
I am checking with them, they give me ELEMENT but it didn't work

**Comment by KazuCocoa** [comment]
https://github.com/webdriverio/webdriverio

btw, close this issue once since current conversation is for webdriverio usage rather than Appium itself so far

**Comment by LayMuiToh** [comment]
OK thanks 👍

**Comment by LayMuiToh** [comment]
Hi Kaza, can you point me to the exact file in the github link you provided above where the selectPickerWheel is used?

**Comment by KazuCocoa** [comment]
No.

Your problem was you were not able to provide element id properly to `{ element: MoreFilters.picker.ELEMENT, order: 'next', offset: 0.5});` according to your appium log.
So, you need to get element id from element object from webdriverio.
The id should be like `xxxx-xxx-xxxx-xxx`, for example.

Did `MoreFilters.picker.ELEMENT` returns string like  `xxxx-xxx-xxxx-xxx`?
If yes but https://github.com/appium/appium/issues/12214#issuecomment-466771250 happened, maybe webdriverio did not set `element:' xxxx-xxx-xxxx-xxx'` as the argument.
in the case also need to make sure how webdriverio works.

**Comment by LayMuiToh** [comment]
Here what I got from: 
[20:09:45]  COMMAND	POST 	 "/wd/hub/session/36221918-efd5-4a4e-a30a-92d3fd6949be/element"
[20:09:45]  DATA		{"using":"accessibility id","value":"Picker"}
[20:09:45]  RESULT		{"ELEMENT":"39010000-0000-0000-C9CE-000000000000"}
[20:09:45]  COMMAND	POST 	 "/wd/hub/session/36221918-efd5-4a4e-a30a-92d3fd6949be/elements"
[20:09:45]  DATA		{"using":"accessibility id","value":"Picker"}
[20:09:46]  RESULT		[{"ELEMENT":"39010000-0000-0000-C9CE-000000000000"}]
[20:09:46]  COMMAND	GET 	 "/wd/hub/session/36221918-efd5-4a4e-a30a-92d3fd6949be/element/39010000-0000-0000-C9CE-000000000000/displayed"
[20:09:46]  DATA		{}
[20:09:46]  RESULT		true
[20:09:46]  COMMAND	POST 	 "/wd/hub/session/36221918-efd5-4a4e-a30a-92d3fd6949be/element"
[20:09:46]  DATA		{"using":"accessibility id","value":"Picker"}
[20:09:46]  RESULT		{"ELEMENT":"39010000-0000-0000-C9CE-000000000000"}
[20:09:46]  COMMAND	POST 	 "/wd/hub/session/36221918-efd5-4a4e-a30a-92d3fd6949be/execute"
[20:09:46]  DATA		{"script":"mobile: selectPickerWheelValue","args":[{"order":"next","offset":0.5}]}
[20:09:46]  COMMAND	POST 	 "/wd/hub/session/36221918-efd5-4a4e-a30a-92d3fd6949be/execute/sync"
[20:09:46]  DATA		{"script":"mobile: selectPickerWheelValue","args":[{"order":"next","offset":0.5}]}
[20:09:46]  COMMAND	GET 	 "/wd/hub/session/36221918-efd5-4a4e-a30a-92d3fd6949be/screenshot"
[20:09:46]  DATA		{}
[20:09:47]  RESULT		"iVBORw0KGgoAAAANSUhEUgAAAu4AAAU2CAYAAADK1zMGAAAAAXNSR0IArs4c6QAA\r\nABxpRE9UAAAAAgAAAAAAAAKbAAAAKAAAApsAAAKbAAJO+rGzjCoAAEAASURBVHgB\r\n7J13cFzXefaZ6sRpk0z+ySQTO+MknklmEiczSSaZtO+bL5GtTooixV5liWp2lDi ... (360102 more bytes)
[20:09:47]  	Saved screenshot: ERROR_iphonesimulator.ios.10_3_1.performance_analyst_app_2019-02-25T12-09-46.915Z.png

**Comment by LayMuiToh** [comment]
I see it return {"ELEMENT":"3F010000-0000-0000-8CCF-000000000000"}
so this is a bug in webdriverio?

**Comment by KazuCocoa** [comment]
Not sure, unfortunately. It was just a response from a server, I assume.

Did `MoreFilters.picker.ELEMENT` return `3F010000-0000-0000-8CCF-000000000000`?
If webdriverio has no way to get the `3F010000-0000-0000-8CCF-000000000000`, it's better to report webdriverio repository to add an API to get it.

https://github.com/appium/appium/issues/12214#issuecomment-466836136 was my guessing to get it. I'm not familiar with webdriverio though.

**Comment by LayMuiToh** [comment]
Hi Kazu, I did a workaround, by using the mobile: dragFromToForDuration

**Comment by emzubair** [comment]
Hi!
I might be late here, `selectPickerWheelValue` works fine for me when I pass `0.1 or 0.2`, when passed values greater than `0.4` it does nothing.
Any idea why it is happening ?

**Comment by blaxinkun** [comment]
This works for me, JS

driver.execute('mobile: selectPickerWheelValue', { element: selectorIos.yearPickerChecklists, 'order': 'previous' })
