### ISSUE TITLE
Android bootstrap socket crashed: Error: read ECONNRESET

### ISSUE THREAD

**Issue by DBBrando** [appium/appium#12217]
## The problem

Every time I launch a test for any app, whether with a physical device or emulator, appium crashes after starting the app. I tried to reinstall each component but always happens the same thing.

## Environment

Appium v1.11.1
Windows 10
Node v10.15.1
Npm 6.4.1
Any device and emulator
Appium CLI and Appium.app|exe

## Details

From power shell I always read the same error in the logs:
uncaughtException: Android bootstrap socket crashed: Error: read ECONNRESET
Error: Android bootstrap socket crashed: Error: read ECONNRESET
    at Socket.socketClient.on.err 

## Link to Appium logs

https://gist.github.com/DBBrando/579ab3651fb11a76234281aae156a4f7

**Comment by saikrishna321** [comment]
Pls set _automationName: Appium_ as UIAutomator2

**Comment by DBBrando** [comment]
I don't understand.
Where should I add "automationName: UIAutomator2"?

**Comment by mykola-mokhnach** [comment]
Can you also attach the logcat output?

**Comment by DBBrando** [comment]
Is it this?
https://gist.github.com/DBBrando/4099c255d1eb8cf71f4d32a4b989ab3d

**Comment by DBBrando** [comment]
This is the logcat after the clear and then launch the test:
https://gist.github.com/DBBrando/3dc0932b39572648da2a9909f4817461

**Comment by mykola-mokhnach** [comment]
Please make sure you get the logcat ouput within the same time range when the uiautomator exception happens

**Comment by mykola-mokhnach** [comment]
Also I see that closeApp/launchApp calls are used in the client code. Try to replace them with terminateApp/activateApp calls. This will be much faster and should not create any problems

**Comment by DBBrando** [comment]
> Please make sure you get the logcat ouput within the same time range when the uiautomator exception happens
here you go:
https://gist.github.com/DBBrando/a2e7d90858f16c24594fbb8ad9337089

 I can not change closeApp/launchApp functions.

thanks

**Comment by mykola-mokhnach** [comment]
This might be both an issue with the app under test or a bug in the UIA2, but I cannot see anything useful in the attached logs.

**Comment by ArtemDiranov** [comment]
Have the same issue but just on the step of start session on the appium Desktop (inspector mode). 
Only virtual device + Appium desktop are using

Win 10 / 64  version 1809
Appium v1.11.1
Desktop version 1.11.0 
Node 10.15.3
Npm 6.4.1
There weren't any appium logs (see attachment bellow)

[adb logcat.txt](https://github.com/appium/appium/files/2992024/adb.logcat.txt)
![2019-03-21_14h20_00](https://user-images.githubusercontent.com/16308387/54752410-af78c680-4be6-11e9-96fa-b413975d2f8c.png)

**Comment by ArtemDiranov** [comment]
Updated to Appium 1.12.1 - still the same (It run once - just when 12 version was installed and even tried to connect device but unsuccessfully), when I run server again - just ECONNRESET as was before.

**Comment by mykola-mokhnach** [comment]
Closed as inactive
