### ISSUE TITLE
iOS: ScreenRecord: Wrong video saved when running parallel tests

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#12219]
## The problem
Wrong video attached while running parallel tests. Maybe problem cause default:
```
const DEFAULT_MJPEG_SERVER_PORT = 9100;
```
when all recorders use same port... not sure. Why not to add this port into capabilities for iOS?

## Environment
* Appium version (or git revision) that exhibits the issue: 1.11.0
* Desktop OS/version used to run Appium: MacOS 10.13.6
* Node.js version (unless using Appium.app|exe): v11.10.0
* Npm or Yarn package manager: 6.8.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: iPhone6s with iOS 12.last

## Details
configure parallel test execution with iOS devices and video recording. i use testNG with parallel methods and thread count = 3. each device uses it own Appium server with different port. 
make some tests fail. check saved video.
only very few videos matches test steps. most of videos are taken from some other test. 

## Link to Appium logs
example of command from log:
```
'ffmpeg -f mjpeg -i http://localhost:9100 -vf scale=320:-2 -vcodec h264 -y /var/folders/_r/nbsgp9v95gq0ht_43kqc1lqc0000gq/T/2019125-24248-g3a6u.eoc939/appium_03b2c9.mp4'
```

## Code To Reproduce Issue [ Good To Have ]
n/a

**Comment by amedvedjev** [comment]
found "mjpegServerPort" in XCUITests will try to change it. it is absent -> http://appium.io/docs/en/writing-running-appium/caps/

**Comment by mykola-mokhnach** [comment]
Feel free to add it into the docs

**Comment by KazuCocoa** [comment]
Is it in https://github.com/appium/appium-xcuitest-driver#desired-capabilities ?
(The caps page has a link to the repo for xcuites)

**Comment by amedvedjev** [comment]
mjpegServerPort - made it work!
