### ISSUE TITLE
Unable to uninstall APK. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability"

### ISSUE THREAD

**Issue by tbalogh** [appium/appium#12227]
## The problem

We use Appium to test our Android application and some of our tests fail most of the time with the following error:

"UnknownError: An unknown server-side error occurred while processing the command. Original error: Unable to uninstall APK. Original error: Error executing adbExec. Original error: 'Command '/path/to/adb -P 5037 -s emulator-5554 uninstall com.company.appname' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability"

We increased the timeout by setting 'adbExecTimeout' capability to 120000ms. The attached appium log shows that it was set to 120000ms however it still times out after the default 20000ms. We would like to overcome the issue of failing tests because of the inability to uninstall the APK.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.11.1
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: MacOS High Sierra v10.13.6
* Node.js version (unless using Appium.app|exe): v10.10.0
* Npm or Yarn package manager: v6.4.1
* Mobile platform/version under test: Android
* Real device or emulator/simulator:
    Device: Nexus 5X (Google)
    Target: Google Play (Google Inc.)
          Based on: Android API 28 Tag/ABI: google_apis_playstore/x86
    Skin: nexus_5x

    more info (adb shell getprop result): https://gist.github.com/tbalogh/1d02dc25153ab6de58ce2752ef442ba6
* Appium CLI or Appium.app|exe:

## Details

We run 14 tests and we experience the issue mostly with 2 tests that turns on and off the emulator wifi. The attached appium log contains the result of a test run with these 14 tests. The appium server was freshly started before the test run and we uninstalled those applications that package name started with "io.appium" . Please let me know if we can provide further information.

## Link to Appium logs

https://gist.github.com/tbalogh/a409000c90da6bff734dd89d7e38a220

## Code To Reproduce Issue [ Good To Have ]

-

**Comment by KazuCocoa** [comment]
below two items can fix this issue, I think. (the timeout)
https://github.com/appium/appium-android-driver/pull/512
https://github.com/appium/appium-uiautomator2-driver/search?q=uninstallApk&unscoped_q=uninstallApk

**Comment by mykola-mokhnach** [comment]
It might be a problem with the environment. Uninstall cannot last for 20 seconds. @tbalogh Does manual execution of adb uninstall command require so much time as well? How big is the application? Is the computer where the emulator is running very slow?

**Comment by mykola-mokhnach** [comment]
Also I would be happy to see the logcat output

**Comment by mykola-mokhnach** [comment]
@tbalogh Can you provide additional details on the issue? If no details are provided we'd consider the problem as a local environment issue rather than Appium issue.

**Comment by tbalogh** [comment]
@mykola-mokhnach

Thanks for the quick reaction. I didn't have a chance to collect the emulator logcat but I'll do it next week. Beside that the uninstall should take no time let me highlight, that the logs still shows that appium uses the default 20000ms as adbExecTimeout instead of the desired 120000ms. Until the emulator log is attached let me answer some of your questions:

1. _"Uninstall cannot last for 20 seconds. @tbalogh Does manual execution of adb uninstall command require so much time as well?"_

No, manual execution takes no time (just a sec or something). The execution time of the uninstall is normal in most of the test cases (we uses fullReset and only 2 tests have the uninstall issue out of the 14).

2. _"How big is the application?"_

~10 MB

3.  "Is the computer where the emulator is running very slow?"

No, the computer specs is fine for running emulators on it. Don't have the specs now but it's a powerful Mac mini with i5 or i7 proc, 8G or 16G of RAM, ...

Please let me know if you need anything else in the meantime. I'll attach the log next week.

**Comment by mykola-mokhnach** [comment]
> No, manual execution takes no time (just a sec or something). The execution time of the uninstall is normal in most of the test cases (we uses fullReset and only 2 tests have the uninstall issue out of the 14).

I think it might be some problem with ADB itself. Make sure it is up to date. As a workaround, it would be possible to execute `uninstallApp` before quitting the session from the client code and then perform a retry if it fails.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue. We've also added a fix to add, which will make uninstall to respect `adbExecTimeout` value
