### ISSUE TITLE
Unable to pull a file from an iOS device with `Cannot mount the media folder` error

### ISSUE THREAD

**Issue by alexeystrakh** [appium/appium#12220]
## The problem

I have an iOS UIAutomation test powered by Appium and XCUITest Driver to execute certain actions on a device and then pull a file from the device, generated by the app. When I call the [fullFile](http://appium.io/docs/en/commands/device/files/pull-file/) method, I get `Cannot mount the media folder` error. All the permissions for `osxfuse` are verified and enabled.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: macOS Mojave 10.14.2
* Node.js version (unless using Appium.app|exe): v11.5.0
* Npm or Yarn package manager: `npm`
* Mobile platform/version under test: `iPad iOS 11.xx`
* Real device or emulator/simulator: `Device`
* Appium CLI or Appium.app|exe: `appium cli`

## Details

I've installed `osxfuse` and went to System Preferences->Security & Privacy to successfully enabled required permissions (Allow button). Unfortunately, that didn't help. I've tried to reboot the `appium` host and the device with no luck. 

The code is simply to access the file from documents folder in the application isolated storage which has been writter by the app:

```
var session = new IOSDriver<IOSElement>(...);
var base64Content = session.PullFile("/Documents/mycustommetadata.log");
```

Below you can find the stack trace of the error:

```
System.InvalidOperationException
  HResult=0x80131509
  Message=An unknown server-side error occurred while processing the command. Original error: Cannot mount the media folder of the device with UDID 520ec2e9fccd3bd77a53e96dd9d08c54c134248a. Make sure osxfuse plugin has necessary permissions in System Preferences->Security & Privacy. Error code: 1; stderr output: Failed to connect to lockdownd service on the device.
Try again. If it still fails try rebooting your device.
 
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Appium.AppiumDriver`1.PullFile(String pathOnDevice)
   at MyProject.MyTest() in ... :line xxx
```

## Link to Appium logs

[Appium pullFileError Logs](https://gist.github.com/alexeystrakh/49bbe7a9c00e410eaf937f1662b2d673)

**Comment by mykola-mokhnach** [comment]
> Failed to connect to lockdownd service on the device.

In this case Appium acts as a proxy between your code and `ifuse` tool. So if something does not work as expected then it should be resolved on the utility's side first and should be possible to perform manually via the command line. 

I would make sure the ifuse utility and the libs are up to date. The second step would be to ask/search their issues tracker.

Closed as third party issue.

**Comment by alexeystrakh** [comment]
I've downloaded the latest tools for `ifuse` and made sure it's installed correctly. 

Could you please clarify how `appium` is using `ifuse` (when acting as a proxy) so I can try to replicate this issue on my side and submit an issue to the 3d party?

**Comment by mykola-mokhnach** [comment]
All commands are visible in the server log. You can also check the code for more details: https://github.com/appium/appium-xcuitest-driver/blob/master/lib/commands/file-movement.js
