### ISSUE TITLE
Switching to webview-io.appium.java_client.NoSuchContextException: An unknown server-side error occurred while processing the command. Original error: operation timed out  

### ISSUE THREAD

**Issue by GujrathiPooja** [appium/appium#12228]
I am testing Hybrid iOS app on real device, i'm getting both NATIVE_APP and WEBVIEW but when i try to switch to webview using driver.context method it is throwing Exception "io.appium.java_client.NoSuchContextException: An unknown server-side error occurred while processing the command. Original error: operation timed out"

Environment

- appium version: 1.10.1
- Node Js version: v11.8.0
- Mobile platform: iPAD iOS 12.1
- Appium CLI or Appium.app|exe: Appium CLI

Appium log:
[appium-server-logs.txt](https://github.com/appium/appium/files/2909817/appium-server-logs.txt)

**Comment by mykola-mokhnach** [comment]
Are you able to interact with the web view directly using [IWDP](https://github.com/google/ios-webkit-debug-proxy)?

**Comment by GujrathiPooja** [comment]
> Are you able to interact with the web view directly using [IWDP](https://github.com/google/ios-webkit-debug-proxy)?

yes,i can see the web page in safari browser.

**Comment by mykola-mokhnach** [comment]
How about IWDP?

**Comment by GujrathiPooja** [comment]
> How about IWDP?

I'm running IWDP on port 9222.I'm new to appium can you explain me more about it.

**Comment by imurchie** [comment]
Appium expects `ios-webkit-debug-proxy` to be running on port `27753 ` (see https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/ios-webkit-debug-proxy.md).

**Comment by GujrathiPooja** [comment]
> Appium expects `ios-webkit-debug-proxy` to be running on port `27753 ` (see https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/ios-webkit-debug-proxy.md).

I did but it's showing unable to bind device on port 27753.

**Comment by mykola-mokhnach** [comment]
> I did but it's showing unable to bind device on port 27753.

The port might be already occupied by another app or there is a problem in IWDP itself. Either way it has nothing to do with Appium.

**Comment by GujrathiPooja** [comment]
> pp or there is a problem in IWDP itself. Either

can you suggest how to solve these problem and how can i switch to webview?

**Comment by imurchie** [comment]
You can change the port to whatever you want, but you need to tell Appium what the port is, using the `webkitDebugProxyPort` desired capability.

**Comment by GujrathiPooja** [comment]
> `ort` desired capability.

i did but still unable to switch to webview

**Comment by GujrathiPooja** [comment]
Can anyone suggest how to solve this problem?

**Comment by mykola-mokhnach** [comment]
Closing as not an issue. Please use discuss.appium.io for questions
