### ISSUE TITLE
Android appium-uiautomator2-server-debug-androidTest.apk install fails

### ISSUE THREAD

**Issue by cosminstirbu** [appium/appium#12224]
## The problem

Our Android tests fail because the install of appium-uiautomator2-server-debug-androidTest.apk times out.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.11.1 (also reproduces on 1.11.0, didn't reproduce on 1.10.x)
* Last Appium version that did not exhibit the issue (if applicable): 1.10.x
* Desktop OS/version used to run Appium: Mac OS X 10.13.6
* Node.js version (unless using Appium.app|exe): 11.4.0
* Npm or Yarn package manager: 6.4.1
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Our Android tests fail because the install of `appium-uiautomator2-server-debug-androidTest.apk` times out, and it seems that the next tests fail because of `android.util.AndroidException: INSTRUMENTATION_FAILED: io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner`, without attempting to re-install `appium-uiautomator2-server-debug-androidTest.apk` meaning that somehow the installation attempt was partially successful.

The issues happens on a freshly created emulator, so initially it doesn't have any Appium related stuff on it. We create it from scratch before running our tests.

## Link to Appium logs

https://gist.github.com/cosminstirbu/daed157d98ecb1d70301ecae4633a906

**Comment by mykola-mokhnach** [comment]
Fixed in https://github.com/appium/appium-uiautomator2-driver/pull/296

I'll publish the fix today in appium@beta
