### ISSUE TITLE
Browser INFO level logs are not captured on Android

### ISSUE THREAD

**Issue by ckzgraphics** [appium/appium#12223]
🐛 Bug Report
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
## The problem

Console Logs are not captured on Android (**INFO level logs are not captured**)

## Environment

* Appium version: 1.8.0
* System Version (used to run Appium): macOS 10.13.2 (17C88) (Kernel Version: Darwin 17.3.0)
* Jave 1.8.0
* Real device: YES
* Device Name: Nokia 7 Plus
* Android Version: 9

## Details

The browser console logs generated by a website are not captured on Android device. Specfically INFO level logs are not captured.

## Link to Appium logs

[Android_INFO_Level_Logs.log](https://gist.github.com/ckzgraphics/6af37522e0139a829d2184291de175ef)

## Code To Reproduce Issue

[Android_INFO_Level_Logs.java](https://gist.github.com/ckzgraphics/6a24835f053e8bf8d987839292d8e1db)

## Excepted Output

[INFO] console-api 371:40 "This is a LOG"
[SEVERE] console-api 371:40 "This is an ERROR"
[WARNING] console-api 371:40 "This is a WARNING"
[INFO] console-api 371:40 "This is an INFO"

## Actual Output

[SEVERE] console-api 371:40 "This is an ERROR"
[WARNING] console-api 371:40 "This is a WARNING"

**Comment by imurchie** [comment]
Hmm. Yes, this should be enabled by default. I will create a PR to do so.

**Comment by imurchie** [comment]
This functionality should be available in the beta now (`npm install [-g] appium@beta`)
