### ISSUE TITLE
iOS class chain nested locator works wrong

### ISSUE THREAD

**Issue by Invictum** [appium/appium#12221]
## The problem

iOS class chain returns only the first matched element rather than all

## Environment

* Appium version (or git revision) that exhibits the issue: v1.11.0-beta.3
* Last Appium version that did not exhibit the issue (if applicable): n\a
* Desktop OS/version used to run Appium: macOS 10.14
* Node.js version (unless using Appium.app|exe): v11.10.0
* Npm or Yarn package manager: npm 6.7.0
* Mobile platform/version under test: iOS 12.1
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: cli

## Details

I have an application with list view that represented with following source XML
```
<XCUIElementTypeTable type="XCUIElementTypeTable" enabled="true" visible="true" x="0" y="120" width="375" height="609">
   <XCUIElementTypeCell type="XCUIElementTypeCell" enabled="true" visible="true" x="0" y="120" width="375" height="143">
      <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" enabled="true" visible="true" x="15" y="155" width="99" height="24" name="Title 1" label="Title 1" value="Title 1" />      
      <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" enabled="true" visible="true" x="15" y="135" width="80" height="20" name="Data" label="Data" value="Data" />
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="15" y="265" width="840" height="1" />
   </XCUIElementTypeCell>
   <XCUIElementTypeCell type="XCUIElementTypeCell" enabled="true" visible="true" x="0" y="120" width="375" height="143">
      <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" enabled="true" visible="true" x="15" y="155" width="99" height="24" name="Title 2" label="Title 2" value="Title 2" />      
      <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" enabled="true" visible="true" x="15" y="135" width="80" height="20" name="Data" label="Data" value="Data" />
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="15" y="265" width="840" height="1" />
   </XCUIElementTypeCell>
</XCUIElementTypeTable>
```
I am trying to query the first entries of `XCUIElementTypeCell` for all cells with following iOS class chain query `**/XCUIElementTypeCell/XCUIElementTypeStaticText[1]`.

For this request I expect to receive two `XCUIElementTypeStaticText` nodes with `Title 1` and `Title 2`

But instead I got only one `XCUIElementTypeStaticText` node with `Title 1`.

## Appium logs

https://gist.github.com/Invictum/3f15d6f03442825b378eb6227136e05e

**Comment by mykola-mokhnach** [comment]
The described behaviour is expected. You can only achieve that with xpath. For class chain it is necessary to perform at least two separate queries: get all cells and then for each cell find the corresponding text field

**Comment by Invictum** [comment]
@mykola-mokhnach 
Thanks for clarification, I will close this issue.
