### ISSUE TITLE
Appium iOS scroll to top

### ISSUE THREAD

**Issue by kennytean** [appium/appium#12230]
## The problem

1. Is there a way to scroll to the top of the screen?

## Environment

* Appium version (or git revision) that exhibits the issue: v1.9.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: McOS
* Node.js version (unless using Appium.app|exe): python
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI

## Code To Reproduce Issue [ Good To Have ]

Once the screen loaded, it scrolls down about 5 times and next I want to scroll back up to select the first result. During the scroll up, the touch action accidentally taps on the date and the date selector pop up. This break the flow of the application.

Currently I used XPath to search element and used below code to scroll, but it always encounters timeout as the page is huge. Any better way to implement or recommendation?
driver.execute_script("mobile: scroll", {"element": element.id, "toVisible": True})

Would be great if Appium has a feature to scroll to the top screen.

**Comment by mykola-mokhnach** [comment]
The only possible way would be to perform a single swipe in a loop until the target element is visible. XCTest does not provide any methods to make it easier.
