### ISSUE TITLE
get_clipboard Method has not yet been implemented

### ISSUE THREAD

**Issue by zhisays** [appium/appium#12232]
## The problem

APPIUM server return 404, when driver.get_clipboard_text()

## Environment

* 1.10.0
* Win7
* Appium.exe
* Android 5
* Genymotion

## Details

driver.get_clipboard_text()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\ProgramData\Miniconda3\envs\xqidian\lib\site-packages\appium\webdriver\extensions\clipboard.py", line 73, in get_clipboard_text
    return self.get_clipboard(ClipboardContentType.PLAINTEXT).decode('UTF-8')
  File "C:\ProgramData\Miniconda3\envs\xqidian\lib\site-packages\appium\webdriver\extensions\clipboard.py", line 63, in get_clipboard
    'contentType': content_type
  File "C:\ProgramData\Miniconda3\envs\xqidian\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\ProgramData\Miniconda3\envs\xqidian\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
WebDriverException: Message: Method has not yet been implemented

## Link to Appium logs

[HTTP] --> POST /wd/hub/session/04fbd5eb-450f-4e2a-9b2c-ca082456a6d5/appium/device/get_clipboard
[HTTP] {"sessionId":"04fbd5eb-450f-4e2a-9b2c-ca082456a6d5","contentType":"plaintext"}
[W3C (04fbd5eb)] Calling AppiumDriver.getClipboard() with args: ["plaintext","04fbd5eb-450f-4e2a-9b2c-ca082456a6d5"]
[W3C (04fbd5eb)] Encountered internal error running command: NotYetImplementedError: Method has not yet been implemented
[W3C (04fbd5eb)]     at AndroidDriver.executeCommand (C:\Users\chazzhuang\AppData\Local\Programs\Appium\resources\app\node_modules\appium-base-driver\lib\basedriver\driver.js:261:13)
[W3C (04fbd5eb)]     at AppiumDriver.executeCommand (C:\Users\chazzhuang\AppData\Local\Programs\Appium\resources\app\node_modules\appium\lib\appium.js:425:36)
[W3C (04fbd5eb)]     at process._tickCallback (internal/process/next_tick.js:68:7)
[HTTP] <-- POST /wd/hub/session/04fbd5eb-450f-4e2a-9b2c-ca082456a6d5/appium/device/get_clipboard 404 14 ms - 561

## Code To Reproduce Issue [ Good To Have ]

from appium import webdriver

desired_caps = dict()
desired_caps['platformName'] = 'Android'
desired_caps['platformVersion'] = '5'
desired_caps['deviceName'] = 'device'
desired_caps['appPackage'] = 'com.android.calculator2'
desired_caps['appActivity'] = '.Calculator'
desired_caps['newCommandTimeout'] = 600
desired_caps['automationName'] = 'Espresso'

driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)

**Comment by mykola-mokhnach** [comment]
Did you try Appium 1.11?

**Comment by mykola-mokhnach** [comment]
Closed as not issue. I see that clipboard interaction feature is currently present in the Espresso driver.
