### ISSUE TITLE
Typo in `signalStrengh`

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#12234]
The gsmSignal endpoint is accepting `signalStrengh` instead of `signalStrength` as the payload: https://github.com/search?q=org%3Aappium+signalStrengh&unscoped_q=signalStrengh

Will need to correct this typo, but will also need to accept both parameters to maintain backward compatibility with clients....

If both parameters supplied (`signalStrengh` and `signalStrength`, should prefer `signalStrength`)

**Comment by khanhdodang** [comment]
Fixed on 
appium-base-driver https://github.com/appium/appium-base-driver/pull/308
Ruby https://github.com/appium/ruby_lib_core/pull/196
appium https://github.com/appium/appium/pull/12257
webdriverio https://github.com/webdriverio/webdriverio/pull/3678

**Comment by khanhdodang** [comment]
@dpgraham This issue has been fixed, so we can close this ticket right now.

**Comment by dpgraham** [comment]
There are still a few clients to update.... but thats okay. We can let tge maintainers of the clients decide what to do.

**Comment by KazuCocoa** [comment]
i've create a PR to java client
