### ISSUE TITLE
Getting an error while executing the test case with real iPhone 6 (12.1.2) device.

### ISSUE THREAD

**Issue by prat3ik** [appium/appium#12237]
## The problem
When I am executing the test case on real iPhone device my application is getting opening and then abruptly closed and this process is being repeated several times before throwing an error:
> selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.

## The execution Video 
https://drive.google.com/open?id=1azEPtRyMvr277jRM3I7Ei1t3DnzZ7ztg

## Environment
* Appium version (or git revision) that exhibits the issue:
* Desktop OS/version used to run Appium: Mac OS Mojave (10.14)
* Node.js version (unless using Appium.app|exe): v11.4.0
* Npm package manager: 6.4.1
* Mobile platform/version under test: iOS
* Real device or emulator/simulator:  iPhone 6 - v 12.1.2
* Appium CLI: 1.11.0-beta.3  And Appium.app:  1.10.0 ( I have tried on both)

## Details
I have followed steps from https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md in order to setup the execution on real iOS devices. And I have setup it correctly. I verified it by deploying the WebDriverAgent manually from the XCode.

To make sure the successfull installation of provisioning profiles in WebDriverAgent.xcodeproj I have executed below command in the project directory:
```
xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=badded265a19dea8b1258392e6bf649a1ffc60ec IPHONEOS_DEPLOYMENT_TARGET=12.1.2
```
Gist of the above command found here: https://gist.github.com/prat3ik/4cc3cffa0871055073f2837185cd6f39

Also to completely verify, I have accessed the WebDriverAgent server status:
![screenshot 2019-03-01 at 5 49 18 pm](https://user-images.githubusercontent.com/23506005/53637927-8b127580-3c4a-11e9-8490-3d0866c78f43.png)

Moreover I have tried to restart the device and unistalled the WebDriverAgent from my device manually also did restart my machine.

## Link to Appium logs(With Enabled XCode logs)
https://gist.github.com/prat3ik/8d950da78419523be97991220036ccef

## Code To Reproduce Issue
```
import unittest
from appium import webdriver

desired_caps = {}
desired_caps['platformName'] = 'iOS'
desired_caps['platformVersion'] = '12.1'
desired_caps['automationName'] = 'XCuiTest'
desired_caps['deviceName'] = 'iPhone6'
desired_caps['udid'] = 'badded265a19dea8b1258392e6bf649a1ffc60ec'
desired_caps['showXcodeLog'] = 'true'
desired_caps['app'] = 'Settings'


driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
```

**Comment by mykola-mokhnach** [comment]
Please attach the log with xcodebuild and ios system logging enabled. Have you tried to deploy WebDriverAgent manually to the device from Xcode?

**Comment by mykola-mokhnach** [comment]
> [WD Proxy] Got an unexpected response:
> [debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Cannot read property 'sessionId' of undefined). Retrying...

To me it looks like the client code tries to start multiple sessions on the same device at the same time and nothing of these succeeds.

**Comment by prat3ik** [comment]
> Please attach the log with xcodebuild and ios system logging enabled. Have you tried to deploy WebDriverAgent manually to the device from Xcode?

Sorry I forgot to add the more details, so I have edited my questions will all my findings.
Thank you.

**Comment by mykola-mokhnach** [comment]
WDA is built successfully. Double check if iproxy works properly on your machine. Perhaps, it needs to be updated/reinstalled

**Comment by mykola-mokhnach** [comment]
https://github.com/tcurdt/iProxy

**Comment by prat3ik** [comment]
The issue is with my static internet connection and it's configuration, I have purchased static internet connection and **forwarded the port 8080** for jenkins, also I kept the reserved address of my appium machine so that it will get the same IP address(192.168.1.104) every time even if router or machine gets restart.

**_So whenever I disconnect the internet from my appium machine I am not getting any error and execution on real device occurs like a charm!_**

**However I am still not sure why the issue occurs if I am forwarding the port 8080 and retain particular IP address(from router) for my appium machine, Do you have any idea about that? **

And thank you very much for the iproxy hint, since issue has been figured out which is with my network configuration we can close this.
![screenshot 2019-03-04 at 4 08 43 pm](https://user-images.githubusercontent.com/23506005/53728296-69a6c900-3e98-11e9-870c-34f0cb613599.png)
![screenshot 2019-03-04 at 4 08 33 pm](https://user-images.githubusercontent.com/23506005/53728297-69a6c900-3e98-11e9-9bce-1e8131bf19d1.png)

**Comment by prat3ik** [comment]
Issue is due to my machine's network configuration and port forwarding, when I get rid of internet connection I am no longer to reproduce the issue.
