### ISSUE TITLE
io.appium.java_client.remote.AppiumCommandExecutor

### ISSUE THREAD

**Issue by MMCod** [appium/appium#12236]
## The problem
I'm a begginer in test automation, the problem is when i try to reproduce my code always show me the following message in Eclipse io.appium.java_client.remote.AppiumCommandExecutor$1 lambda$0
INFO: Detected dialect: W3C

## Environment

* Appium Desktop version 1.10.0
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Real Device
* Selenium with Eclipse 

## Link to Appium logs
[Appium] Welcome to Appium v1.10.0
[Appium] Non-default server args:
[Appium]   address: 127.0.0.1
[Appium]   sessionOverride: true
[Appium] Appium REST http interface listener started on 127.0.0.1:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"appActivity":"mdxxxxxx.MainActivity","appPackage":"csm.csm","noReset":true,"platformVersion":"7.0","platformName":"Android","udid":"6eXXXXXX","deviceName":"Galaxy Tab S2"},"capabilities":{"firstMatch":[{"appium:appActivity":"mdxxxxxx.MainActivity","appium:appPackage":"csm.csm","appium:deviceName":"Galaxy Tab S2","appium:noReset":true,"platformName":"android","appium:platformVersion":"7.0","appium:udid":"6eXXXXXX"}]}}
[W3C] Calling AppiumDriver.createSession() with args: [{"appActivity":"mdxxxxxx.MainActivity","appPackage":"csm.csm","noReset":true,"platformVersion":"7.0","platformName":"Android","udid":"6eXXXXXX","deviceName":"Galaxy Tab S2"},null,{"firstMatch":[{"appium:appActivity":"mdxxxxxx.MainActivity","appium:appPackage":"csm.csm","appium:deviceName":"Galaxy Tab S2","appium:noReset":true,"platformName":"android","appium:platformVersion":"7.0","appium:udid":"6eXXXXXX"}]}]
[BaseDriver] Event 'newSessionRequested' logged at 1551439243668 (12:20:43 GMT+0100 (Hora estándar romance))
[Appium] Consider setting 'automationName' capability to 'UiAutomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.
[Appium] Creating new AndroidDriver (v4.8.0) session
[Appium] Capabilities:
[Appium]   platformName: android
[Appium]   appActivity: mdxxxxxx.MainActivity
[Appium]   appPackage: csm.csm
[Appium]   deviceName: Galaxy Tab S2
[Appium]   noReset: true
[Appium]   platformVersion: 7.0
[Appium]   udid: 6eXXXXXX
[BaseDriver] W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP desired capabilities {"appActivity":"mdxxxxxx... were provided
[BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"platformNa...
[BaseDriver] Session created with session id: e610aa6c-4432-4c9e-8c5c-cead7f097571
[AndroidDriver] Java version is: 11.0.2
[AndroidDriver] Retrieving device list
[ADB] Trying to find a connected android device
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[AndroidDriver] Using device: 6eXXXXXX
[ADB] Setting device id to 6eXXXXXX
[ADB] Running 'C:\Program Files (x86)\Android\platform-tools\adb.exe -P 5037 -s 6eXXXXXX shell getprop ro.build.version.sdk'
[ADB] Current device property 'ro.build.version.sdk': 24
[ADB] Device API level: 24
[AndroidDriver] Consider setting 'automationName' capability to 'uiautomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.
[AndroidDriver] App file was not listed, instead we're going to run csm.csm directly on the device
[AndroidDriver] Checking whether package is present on the device
[ADB] Running 'C:\Program Files (x86)\Android\platform-tools\adb.exe -P 5037 -s 6eXXXXXX shell pm list packages csm.csm'
[AndroidDriver] Starting Android session
[ADB] Running 'C:\Program Files (x86)\Android\platform-tools\adb.exe -P 5037 -s 6eXXXXXX wait-for-device'
[ADB] Running 'C:\Program Files (x86)\Android\platform-tools\adb.exe -P 5037 -s 6eXXXXXX shell echo ping'
[AndroidDriver] Pushing settings apk to device...
[ADB] Getting install status for io.appium.settings
[ADB] Running 'C:\Program Files (x86)\Android\platform-tools\adb.exe -P 5037 -s 6eXXXXXX shell dumpsys package io.appium.settings'
[ADB] 'io.appium.settings' is not installed
[ADB] App 'C:\Users\m.m\AppData\Local\Programs\Appium\resources\app\node_modules\io.appium.settings\apks\settings_apk-debug.apk' is not installed
[ADB] Installing 'C:\Users\m.m\AppData\Local\Programs\Appium\resources\app\node_modules\io.appium.settings\apks\settings_apk-debug.apk'
[ADB] Device API level: 24
[ADB] Running 'C:\Program Files (x86)\Android\platform-tools\adb.exe -P 5037 -s 6eXXXXXX install -g C\:\\Users\\m.m\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\io.appium.settings\\apks\\settings_apk-debug.apk'
[ADB] Install command stdout: Success
[ADB] Running 'C:\Program Files (x86)\Android\platform-tools\adb.exe -P 5037 -s 6eXXXXXX shell ps'
[ADB] Device API level: 24
[ADB] Device API level: 24
[ADB] Running 'C:\Program Files (x86)\Android\platform-tools\adb.exe -P 5037 -s 6eXXXXXX shell am start -W -n io.appium.settings/.Settings -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[ADB] Device API level: 24
[ADB] Running 'C:\Program Files (x86)\Android\platform-tools\adb.exe -P 5037 -s 6eXXXXXX shell appops set io.appium.settings android\:mock_location allow'
[Logcat] Starting logcat capture
[ADB] Getting device platform version
[ADB] Running 'C:\Program Files (x86)\Android\platform-tools\adb.exe -P 5037 -s 6eXXXXXX shell getprop ro.build.version.release'
[ADB] Current device property 'ro.build.version.release': 7.0
[ADB] Running 'C:\Program Files (x86)\Android\platform-tools\adb.exe -P 5037 -s 6eXXXXXX shell wm size'
[ADB] Running 'C:\Program Files (x86)\Android\platform-tools\adb.exe -P 5037 -s 6eXXXXXX shell getprop ro.product.model'
[ADB] Current device property 'ro.product.model': SM-T819
[ADB] Running 'C:\Program Files (x86)\Android\platform-tools\adb.exe -P 5037 -s 6eXXXXXX shell getprop ro.product.manufacturer'
[ADB] Current device property 'ro.product.manufacturer': samsung
**[AndroidDriver] No app sent in, not parsing package/activity
[AndroidDriver] No app capability. Assuming it is already on the device**
[AndroidBootstrap] Watching for bootstrap disconnect
[ADB] Forwarding system: 4724 to device: 4724
[ADB] Running 'C:\Program Files (x86)\Android\platform-tools\adb.exe -P 5037 -s 6eXXXXXX forward tcp\:4724 tcp\:4724'
[UiAutomator] Starting UiAutomator
[UiAutomator] Moving to state 'starting'
[UiAutomator] Parsing uiautomator jar
[UiAutomator] Found jar name: 'AppiumBootstrap.jar'
[ADB] Running 'C:\Program Files (x86)\Android\platform-tools\adb.exe -P 5037 -s 6eXXXXXX push C\:\\Users\\m.m\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium-android-driver\\bootstrap\\bin\\AppiumBootstrap.jar /data/local/tmp/'
[ADB] Attempting to kill all uiautomator processes
[ADB] Getting all processes with uiautomator
[ADB] Running 'C:\Program Files (x86)\Android\platform-tools\adb.exe -P 5037 -s 6eXXXXXX shell ps'
[ADB] No 'uiautomator' process has been found
[UiAutomator] Starting UIAutomator
[ADB] Creating ADB subprocess with args: ["-P",5037,"-s","6eXXXXXX","shell","uiautomator","runtest","AppiumBootstrap.jar","-c","io.appium.android.bootstrap.Bootstrap","-e","pkg","csm.csm","-e","disableAndroidWatchers",false,"-e","acceptSslCerts",false]
[UiAutomator] Moving to state 'online'
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Registered crash watchers.
[AndroidBootstrap] Android bootstrap socket is now connected
[ADB] Running 'C:\Program Files (x86)\Android\platform-tools\adb.exe -P 5037 -s 6eXXXXXX shell dumpsys window'
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Client connected
[AndroidDriver] Screen is locked, trying to unlock
[AndroidDriver] Using app unlock, this is going to be deprecated!
[AndroidDriver] Unlocking screen
[AndroidDriver] Launching .Unlock
[ADB] Running 'C:\Program Files (x86)\Android\platform-tools\adb.exe -P 5037 -s 6eXXXXXX shell am start -n io.appium.settings/.Unlock -c android.intent.category.LAUNCHER -a android.intent.action.MAIN -f 0x10200000'
[AndroidBootstrap] Emitting alert message...
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Emitting system alert message
[ADB] Device API level: 24
[ADB] Running 'C:\Program Files (x86)\Android\platform-tools\adb.exe -P 5037 -s 6eXXXXXX shell am start -W -n csm.csm/mdxxxxxx.MainActivity -S'
[Appium] New AndroidDriver session created successfully, session e610aa6c-4432-4c9e-8c5c-cead7f097571 added to master session list
[BaseDriver] Event 'newSessionStarted' logged at 1551439259577 (12:20:59 GMT+0100 (Hora estándar romance))
[W3C (e610aa6c)] Cached the protocol value 'W3C' for the new session e610aa6c-4432-4c9e-8c5c-cead7f097571
[W3C (e610aa6c)] Responding to client with driver.createSession() result: {"capabilities":{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"android","appActivity":"mdxxxxxx.MainActivity","appPackage":"csm.csm","deviceName":"Galaxy Tab S2","noReset":true,"platformVersion":"7.0","udid":"6eXXXXXX"},"platformName":"android","appActivity":"mdxxxxxx.MainActivity","appPackage":"csm.csm","deviceName":"6eXXXXXX","noReset":true,"platformVersion":"7.0","udid":"6eXXXXXX","deviceUDID":"6eXXXXXX","deviceScreenSize":"1536x2048","deviceModel":"SM-T819","deviceManufacturer":"samsung"}}
[HTTP] <-- POST /wd/hub/session 200 15913 ms - 788
[HTTP] 
[HTTP] --> GET /wd/hub/session/e610aa6c-4432-4c9e-8c5c-cead7f097571
[HTTP] {}
[W3C (e610aa6c)] Calling AppiumDriver.getSession() with args: ["e610aa6c-4432-4c9e-8c5c-cead7f097571"]
[W3C (e610aa6c)] Responding to client with driver.getSession() result: {"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"android","appActivity":"mdxxxxxx.MainActivity","appPackage":"csm.csm","deviceName":"Galaxy Tab S2","noReset":true,"platformVersion":"7.0","udid":"6eXXXXXX"},"platformName":"android","appActivity":"mdxxxxxx.MainActivity","appPackage":"csm.csm","deviceName":"6eXXXXXX","noReset":true,"platformVersion":"7.0","udid":"6eXXXXXX","deviceUDID":"6eXXXXXX","deviceScreenSize":"1536x2048","deviceModel":"SM-T819","deviceManufacturer":"samsung"}
[HTTP] <-- GET /wd/hub/session/e610aa6c-4432-4c9e-8c5c-cead7f097571 200 2 ms - 720
[HTTP] 
[HTTP] --> GET /wd/hub/session/e610aa6c-4432-4c9e-8c5c-cead7f097571
[HTTP] {}
[W3C (e610aa6c)] Calling AppiumDriver.getSession() with args: ["e610aa6c-4432-4c9e-8c5c-cead7f097571"]
[W3C (e610aa6c)] Responding to client with driver.getSession() result: {"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"android","appActivity":"mdxxxxxx.MainActivity","appPackage":"csm.csm","deviceName":"Galaxy Tab S2","noReset":true,"platformVersion":"7.0","udid":"6eXXXXXX"},"platformName":"android","appActivity":"mdxxxxxx.MainActivity","appPackage":"csm.csm","deviceName":"6eXXXXXX","noReset":true,"platformVersion":"7.0","udid":"6eXXXXXX","deviceUDID":"6eXXXXXX","deviceScreenSize":"1536x2048","deviceModel":"SM-T819","deviceManufacturer":"samsung"}
[HTTP] <-- GET /wd/hub/session/e610aa6c-4432-4c9e-8c5c-cead7f097571 200 2 ms - 720
[HTTP] 
[HTTP] --> DELETE /wd/hub/session/e610aa6c-4432-4c9e-8c5c-cead7f097571
[HTTP] {}
[W3C (e610aa6c)] Calling AppiumDriver.deleteSession() with args: ["e610aa6c-4432-4c9e-8c5c-cead7f097571"]
[BaseDriver] Event 'quitSessionRequested' logged at 1551439259676 (12:20:59 GMT+0100 (Hora estándar romance))
[Appium] Removing session e610aa6c-4432-4c9e-8c5c-cead7f097571 from our master session list
[AndroidDriver] Shutting down Android driver
[ADB] Running 'C:\Program Files (x86)\Android\platform-tools\adb.exe -P 5037 -s 6eXXXXXX shell am force-stop csm.csm'
[ADB] Pressing the HOME button
[ADB] Running 'C:\Program Files (x86)\Android\platform-tools\adb.exe -P 5037 -s 6eXXXXXX shell input keyevent 3'
[AndroidBootstrap] Sending command to android: {"cmd":"shutdown"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"shutdown"}
[AndroidBootstrap] Received command result from bootstrap
[UiAutomator] Shutting down UiAutomator
[UiAutomator] Moving to state 'stopping'
[UiAutomator] UiAutomator shut down normally
[UiAutomator] Moving to state 'stopped'
[ADB] Attempting to kill all uiautomator processes
[ADB] Getting all processes with uiautomator
[ADB] Running 'C:\Program Files (x86)\Android\platform-tools\adb.exe -P 5037 -s 6eXXXXXX shell ps'
[ADB] No 'uiautomator' process has been found
[UiAutomator] Moving to state 'stopped'
[Logcat] Stopping logcat capture
[ADB] Running 'C:\Program Files (x86)\Android\platform-tools\adb.exe -P 5037 -s 6eXXXXXX shell am force-stop io.appium.unlock'
[AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[BaseDriver] Event 'quitSessionFinished' logged at 1551439262573 (12:21:02 GMT+0100 (Hora estándar romance))
[W3C (e610aa6c)] Received response: null
[W3C (e610aa6c)] But deleting session, so not returning
[W3C (e610aa6c)] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/e610aa6c-4432-4c9e-8c5c-cead7f097571 200 2901 ms - 14
[HTTP] 

## Code To Reproduce Issue 

import java.net.MalformedURLException;
import java.net.URL;

import org.openqa.selenium.By;
import org.openqa.selenium.remote.DesiredCapabilities;

import io.appium.java_client.AppiumDriver;

public class CSM_TEST_AUTO{
	
	@SuppressWarnings("rawtypes")
		public static void main (String[] args) throws MalformedURLException, InterruptedException {
		
			AppiumDriver<?> wd = null;
			
			try {
				//Set Capabilities instance
				DesiredCapabilities caps = new DesiredCapabilities();
				
				//Set device Capabilities
				caps.setCapability("deviceName", "Galaxy Tab S2");
				caps.setCapability("udid", "6exxxxxx");
				caps.setCapability("platformName", "Android");
				caps.setCapability("platformVersion", "7.0");
								
				//Set Package Capabilities
				caps.setCapability("appPackage","csm.csm" );
				caps.setCapability("appActivity", "mdxxxx.MainActivity");
				caps.setCapability("noReset", true);
				
				//Create a Session
				//wd = new AndroidDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"), caps);
				wd = new AppiumDriver (new URL("http://127.0.0.1:4723/wd/hub"), caps);
				System.out.println("Ok");
				
			  			
			} catch (MalformedURLException e) {
				System.out.println("No funciono la prueba");
				e.printStackTrace();
			}
			
			
			wd.quit();
			
		}
}

**Comment by mykola-mokhnach** [comment]
What is the actual problem? I don't observe any issues

**Comment by MMCod** [comment]
The actual problem is the message in Eclipse show me this error message 
mar 01, 2019 12:54:57 PM io.appium.java_client.remote.AppiumCommandExecutor$1 lambda$0
INFO: Detected dialect: W3C and i don't know how to fixed and if this error causes me not to be able to find Elements in my app

**Comment by MMCod** [comment]
This is a comment or what ?
[AndroidDriver] No app sent in, not parsing package/activity
[AndroidDriver] No app capability. Assuming it is already on the device

**Comment by mykola-mokhnach** [comment]
> The actual problem is the message in Eclipse show me this error message
> mar 01, 2019 12:54:57 PM io.appium.java_client.remote.AppiumCommandExecutor$1 lambda$0
> INFO: Detected dialect: W3C and i don't know how to fixed and if this error causes me not to be able to find Elements in my app

this is a normal logging message from java client

> [AndroidDriver] No app sent in, not parsing package/activity
> [AndroidDriver] No app capability. Assuming it is already on the device

This means that since no `app` capability has been provided the driver assumes it is already present on the device. 

Please use Appium forum for questions, since this is the place for server issues. 

Closed as not an issue.
