### ISSUE TITLE
iOS :Got an unexpected response accessing NATIVE popup window

### ISSUE THREAD

**Issue by jarkkop** [appium/appium#12238]
## The problem

The script runs fine in NATIVE mode and then does something correctly also in Webview mode, then it return back to NATIVE mode and does also something in NATIVE also. It is at the end of our card enrolment process where this error happens. This dialog, which gives this error is not somehow recognized. The log says: "The element '\"ALOITA\" Button' is not visible on the screen and thus is not interactable" Why?

## Environment
Appium v1.11.1
Mac OS High Sierrra 10.13.6 (17G65)
Nodejs: v10.11.0
npm: 6.8.0
		cap.setCapability("platformName", "iOS");
		cap.setCapability("automationName", "XCUITest"); 
		cap.setCapability("deviceName", "iPhone XR");
		cap.setCapability("platformVersion", "12.0");
Xcode Version 10.0 (10A255) Simulator
Appium CLI

## Link to Appium logs

<script src="https://gist.github.com/jarkkop/73b6f4a717d7f0a607acbabf5ddd3852.js"></script>
## Code To Reproduce Issue [ Good To Have ]
			pinCode.sendKeys("1234");
			MobileElement startUsing = (MobileElement) (new WebDriverWait(driver, 90)).until(
							ExpectedConditions.elementToBeClickable(MobileBy.iOSNsPredicateString("name == 'ALOITA'")));
			startUsing.click();			 
			driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
			 MobileElement startUsing2 = (MobileElement) (new WebDriverWait(driver, 20))
						.until(ExpectedConditions.presenceOfElementLocated(MobileBy.iOSNsPredicateString("type == 'XCUIElementTypeButton' AND label == 'ALOITA'")));

			 startUsing2.click();

**Comment by mykola-mokhnach** [comment]
This happens when XCTest returns an empty rectangle for the target element, so it is not possible to calculate click coordinate for it. There is nothing to be done on Appium side though.

**Comment by jarkkop** [comment]
Is there something that the app developer can do help appium solve this?

**Comment by jarkkop** [comment]
Because there is in the app actual popup window which I can tap

**Comment by mykola-mokhnach** [comment]
Feel free to describe your problem to Apple so they can fix it.

**Comment by jarkkop** [comment]
If I run in just before the error is show
		    	 String pageSource4 = driver.getPageSource();
		    	 System.out.println(pageSource4);
I get valid looking xml structure which seems to describe the page correctly.
Why can't it be used then?
 The line I am interested:
<XCUIElementTypeButton type="XCUIElementTypeButton" name="ALOITA" label="ALOITA" enabled="true" visible="true" x="35" y="431" width="344" height="65"/>

**Comment by mykola-mokhnach** [comment]
This might be a race condition because of `elementToBeClickable` usage. I'll check on what can be done there

**Comment by jarkkop** [comment]
Do you have suggestion if there is another way of trying to locate this button that could work better?

**Comment by mykola-mokhnach** [comment]
Try to change the locator to `"type == 'XCUIElementTypeButton' AND label == 'ALOITA' AND visible == 1"` or `"type == 'XCUIElementTypeButton' AND label == 'ALOITA' AND frame.width > 0 AND  frame.height > 0"`

**Comment by jarkkop** [comment]
It worked.
**The _"type == 'XCUIElementTypeButton' AND label == 'ALOITA' AND visible == 1"_**
line did't give error anymore and the script kept going forward. What happened?

**Comment by mykola-mokhnach** [comment]
The exception above happens if one tries to click an invisible element. Adding `visible == 1` verifies the found element is already visible before clicking it. This might not be visible while doing a test manually, but there might be some delay between an element is created and its clickable area size is changed. Although, this is critical for automated tests where element lookup is fast.
