### ISSUE TITLE
[FeatureRequest] Appium server: Add timestamps while sending log output to webhook

### ISSUE THREAD

**Issue by amokmen** [appium/appium#12249]
## The problem

Appium server currently didn't send timestamps while sending it's log output to webhook.
I could create timestamps on my side, of course. But it's bad by design: there is could be any **network latency** and timestamp become not truthfully.

## Feature request

Add to object which is sending to webhook new `key: value`
```
{
...
timestamp: number,
...
}
```
Where number is **Unix time** in seconds.

**Comment by mykola-mokhnach** [comment]
This all and even more is now present in logs formatted as json
