### ISSUE TITLE
Permission Denial Errors Starting Instrumentation with ComponentInfo{io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner}

### ISSUE THREAD

**Issue by InvisibleExo** [appium/appium#12246]
## The problem

When I attempt to setup a test run with Android after updating to Java 11. I keep getting Permission Denial Error during the setup for my AppiumDriver. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.11.1
* Desktop OS/version used to run Appium: 1.11.1
* Node.js version (unless using Appium.app|exe): 6.4.1
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Emulator
*adb version: 1.0.40 Version 4986621

## Details

I've updated my Java version from Java 8 and Java 11(11.0.2). During my tests to make sure everything is going well, I keep getting errors from Appium server stating that they're getting permission denial when starting instrumentation **ComponentInfo{io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner}.** 
I've tried to uninstall  io.appium.iuautomator2.server and io.appium.iuautomator2.server.test through adb and manually, but I'm still getting Permission errors.
I'm also getting apksigner stdout Errors finding no suitable Java for apks:
**appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v3.2.2.apk
appium-uiautomator2-server\\apks\\appium-uiautomator2-server-debug-androidTest.apk**

At this point, I'm not sure what to resolve first, if it means getting rid of the other half of the issue.
Details of the Appium Server logs are provided in the Gist below. 

## Link to Appium logs

https://gist.github.com/InvisibleExo/49be74a86ac2bd28106f44ddc286746c

## Code To Reproduce Issue [ Good To Have ]

Code to setup Appium Driver: https://gist.github.com/InvisibleExo/1d62c90f819e6beee73baeb6e63b0ff2

**Comment by mykola-mokhnach** [comment]
> 
> [debug] [ADB] ERROR: No suitable Java found. In order to properly use the Android Developer
> [debug] [ADB] Tools, you need a suitable version of Java JDK installed on your system.
> [debug] [ADB] We recommend that you install the JDK version of JavaSE, available here:
> [debug] [ADB]   http://www.oracle.com/technetwork/java/javase/downloads
> [debug] [ADB]
> [debug] [ADB] If you already have Java installed, you can define the JAVA_HOME environment
> [debug] [ADB] variable in Control Panel / System / Avanced System Settings to point to the
> [debug] [ADB] JDK folder.
> [debug] [ADB]
> [debug] [ADB] You can find the complete Android SDK requirements here:
> [debug] [ADB]   http://developer.android.com/sdk/requirements.html
> [debug] [ADB]

**Comment by InvisibleExo** [comment]
@mykola-mokhnach I've double checked if I was missing anything from both Oracle and Android Studio.
 I currently have the 3.3.2 with the latest Android SDK updated. As for Oracle, I've installed Java JDK and set up my Java Home path to get this: Java_Home=C:\Program Files\Java\jdk-11.0.2 Path=%Java_Home%\bin
java version "11.0.2" 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)

I'm still getting the errors when running my tests.
Even with checking any articles/sources for Android SDK support for Java 11 and vise versa, but I'm unable to narrow down what I need to do with either Android SDK or Java. Is there any more information I need to mention to help deduce if I have all the requirements from Android SDK and Java?

**Comment by mykola-mokhnach** [comment]
I'd try to check if JAVA_HOME env [variable](https://github.com/appium/java-client/blob/master/docs/environment.md) is visible to the Appium process first.

**Comment by InvisibleExo** [comment]
What exactly would I be specifically checking to determine if JAVA_HOME is visible to Appium? I'm checking the Process Explorer, and I'm not seeing anything lacking when searching: "npm" "sdk". I did notice when trying to investigate that when checking my SDK Manager in CMD, I get this error:

C:\Users\<username>\AppData\Local\Android\Sdk>sdkmanager
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 5 more

I attempted to fix it with: set JAVA_OPTS=-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee, but I get this error:

Error occurred during initialization of boot layer
java.lang.module.FindException: Module java.se.ee not found

**Comment by mykola-mokhnach** [comment]
Perhaps Android SDK is simply incompatible with newer java versions? So you must downgrade to make it working (or report a feature request to Android)

**Comment by InvisibleExo** [comment]
@mykola-mokhnach, reported this problem to Android Studio. 
Link: https://issuetracker.google.com/issues/127691113

**Comment by mykola-mokhnach** [comment]
Closed as third party issue. There is nothing to do on Appium side if Android SDK is not functioning properly.

**Comment by InvisibleExo** [comment]
@mykola-mokhnach, in case you're interested in the answer from issue tracker. 

"Status: Won't Fix (Infeasible)
Java 11 is not supported  by Android studio and its tools."

**Comment by mykola-mokhnach** [comment]
[java11](https://imgflip.com/i/2vn0ga)

**Comment by InvisibleExo** [comment]
"There's compatibility there that does not exist"
