### ISSUE TITLE
Swipe stops working 

### ISSUE THREAD

**Issue by edisonhmp** [appium/appium#12243]
## The problem

In appium 1.7.2, the swipe function was working fine for me. But once I switch to appium 1.8.1 or above, it stops working properly.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.11.1
* Last Appium version that did not exhibit the issue (if applicable):1.7.2
* Desktop OS/version used to run Appium: Mac 13.6
* Node.js version (unless using Appium.app|exe):11.2.0
* Npm or Yarn package manager:npm
* Mobile platform/version under test: ios 11.4
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:Appium python

## Details

I have automated a test case for swiping on a bottom bar to right/left on my app. It was working properly for me to look for the icon in the bottom bar when I use Appium 1.7.2 . But after I install 1.8.1 or above version, that swipe 
action seems broken and not reliable.
And as I can see, there are code changes from 1.8.1 for swipe function in the file below,
//appium/node_modules/appium-xcuitest-driver/build/lib/commands/execute.js

## Link to Appium logs

https://gist.github.com/edisonhmp/299bbb22bdaa651b09dc46042d94ca3a

## Code To Reproduce Issue [ Good To Have ]
This is the swipe function from appium python webdriver that I'm using
[appium.log](https://github.com/appium/appium/files/2922901/appium.log)

swipe(self, start_x, start_y, end_x, end_y, duration=100)
def swipe(self, start_x, start_y, end_x, end_y, duration=None):
          action = TouchAction(self)
          action \
            .press(x=start_x, y=start_y) \
            .wait(ms=duration) \
            .move_to(x=end_x, y=end_y) \
            .release()
        action.perform()

**Comment by mykola-mokhnach** [comment]
Increase wait duration to 600ms

**Comment by edisonhmp** [comment]
@mykola-mokhnach Thanks your reply, I have tried 600ms duration, but the swipe only works fine for me when swipe to left not swipe to right. That's weird

**Comment by mykola-mokhnach** [comment]
You could also try `mobile: swipe` endpoint.
