### ISSUE TITLE
 iOS 12.2 hybrid tests fail using xcuitest-driver

### ISSUE THREAD

**Issue by sadafyadegari** [appium/appium#12240]
## The problem
hybrid tests are failing in simulators.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.11.2-rc.1 git hash: cb8dbdb4b2b688e32e311ec7be0777d2339651eb
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: 10.14.3 Mojave
* Node.js version (unless using Appium.app|exe):  v8.9.4
* Npm package manager: 5.6.0
* Mobile platform/version under test: iOS 12.2
* Real device or emulator/simulator: N/A
* Appium CLI: 1.11.0-beta.3
* Xcode version: 10.2 beta 2
* simulator version: Version 10.2 (SimulatorApp-880.5 CoreSimulator-587.32)

## Details

Test fail as the connection to the application cannot be established. 
appium-xcuitest-driver git hash: c8e4eabc17361945cc37aa8f4319594cbd7a090d
appium-WebDriverAgent revision: branch xcode 10.2 sha: 9b05749dc2054f162eb2569b22bfa9350b195aa6

## Link to Appium logs

Link to the [Appium logs](https://gist.github.com/sadafyadegari/18c9627af3c0b505e3b824421361bfbd)

## Code To Reproduce Issue [ Good To Have ]

Running a test with runsauce with the following capabilities
```js
{
    "desiredCapabilities": {
        "browserName": "",
        "appiumVersion": "1.11.1",
        "deviceName": "iPhone Simulator",
        "platformVersion": "12.2",
        "launchTimeout": 35000,
        "platformName": "iOS",
        "app": "http://appium.s3.amazonaws.com/FLWebView.app.zip",
        "prevent-requeue": true,
        "name": "Basic ios hybrid test (iPhone Simulator on iOS 12.2)",
        "showXcodeLog": "true"
    }
}
```

(https://github.com/appium/appium/issues/12101)

**Comment by sadafyadegari** [comment]
tested the xcode-10.2 beta 4 that came out on March 4th. Same results happen again. See logs:
https://gist.github.com/sadafyadegari/b42cc574fc65038ed6c2f1c8f61a06ee

**Comment by sadafyadegari** [comment]
the hybrid tests were failing sometimes with `isaac-web- 12.2` branch on xcuitestdriver. It could very well be that tests are flaky, tried increasing the timeout but they still fail sometimes https://gist.github.com/sadafyadegari/68101f74de9cdb93a4289928cbcd0944

**Comment by imurchie** [comment]
Can you have getting contexts on a WebDriverWait or something? It may take a little time for the Web Inspector to start telling us there are webviews available.

**Comment by imurchie** [comment]
@sadafyadegari Can you try the latest of my branch?

**Comment by sadafyadegari** [comment]
@imurchie yes that seems to have resolved the issue. Thank you.
