### ISSUE TITLE
Appium inspect and tests don't work once context is switched from webview to nativeview

### ISSUE THREAD

**Issue by Madhavip3** [appium/appium#12241]
Appium inspect and tests don't work once context is switched from webview to nativeview

* Appium version (or git revision) that exhibits the issue: Version 1.10.0 (1.10.0.20181230.2)
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:Mac os 10.13.6
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:Ipad pro simulator 10.1
* Real device or emulator/simulator:simulator
* Appium CLI or Appium.app|exe:Appium.app

## Details

There is a sign-in webview context in my app.Once signed in, the app becomes unresponsive to click on the element in native view. This happens in inspect as well as when running the tests. 

## Link to Appium logs

https://gist.github.com/Madhavip3/54bc8f7af380fc7334e94b0163d446b9#file-appium-logs

## Code To Reproduce Issue [ Good To Have ]

Set<String> contextNames = GeminiSession.iosSession.getContextHandles();
GeminiSession.iosSession.context((String) contextNames.toArray()[1]);			GeminiSession.iosSession.findElement(By.id("adobeid_username")).sendKeys("xyz@test.com");
GeminiSession.iosSession.findElement(By.id("adobeid_password")).sendKeys("123#");
BaseHelper.click("sign_in");		 
GeminiSession.iosSession.context((String) contextNames.toArray()[0]);

**Comment by mykola-mokhnach** [comment]
> [debug] [35m[JSONWP Proxy][39m Proxying [GET /source] to [GET http://localhost:8100/session/CC9F5535-90A7-4515-B98B-F8920A41315A/source] with no body[info] [35m[Xcode][39m 2019-03-01 17:57:34.404296-0800 WebDriverAgentRunner-Runner[80853:6281744] Internal error: Error Domain=com.apple.dt.xctest.automation-support.error Code=8 "Error getting main window kAXErrorServerNotFound" UserInfo={NSLocalizedDescription=Error getting main window kAXErrorServerNotFound}

To me it looks like something is happened to the app under test. This is anyway an internal XCTest error, which Appium has nothing to do with.

**Comment by Madhavip3** [comment]
The app works fine when building through Xcode. The issue happens only when running tests through appium.

**Comment by Madhavip3** [comment]
@mykola-mokhnach Is there anything I need to update or try from my end? Right now all the tests are failing since the sign in is enabled in my app.

**Comment by mykola-mokhnach** [comment]
I don't think here is anything to do on Appium side. Closed as third party issue
