### ISSUE TITLE
Error in Webdriver agent runner

### ISSUE THREAD

**Issue by moagarwa** [appium/appium#12247]
## The problem

WebDriverAgentRunner-Runner[746:394429] Enqueue Failure: Failure getting list of active applications: (null) /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1

## Environment

* Appium version (or git revision) that exhibits the issue: 1.11.0
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2
* Desktop OS/version used to run Appium: 12.1
* Node.js version (unless using Appium.app|exe): 10.10.0
* Npm or Yarn package manager:6.4.1
* Mobile platform/version under test:ipad 11.4
* Real device or emulator/simulator:real device
* Appium CLI or Appium.app|exe:

## Details

Automation hangs for a while after running few tests with the below error

WebDriverAgentRunner-Runner[746:394429] Enqueue Failure: Failure getting list of active applications: (null) /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1.

After some time, automation again starts by killing and relaunching app

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by moagarwa** [comment]
i think the issue is due to  App animations complete notification not received, will attempt to continue.
I have latest appium and it is told that it is fixed in 1.9.2 and above.
Can you please help me in setting waitForQuiesence:false using command line

**Comment by amokmen** [comment]
### Problem
I think my problem is similar or near.

1) While running basic test I **always** got **~60 seconds pause** after one Appium's log line:
```
...
09:41:29:088 - [debug] [WD Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.MyApp","arguments":[],"environment":{},"shouldWaitForQuiescence":false,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
...
nothing happens here: my app already started and just wait smth, test script also wait, Appium wait smth, I watching device screen and all logs and wait smth too :)
...
09:42:31:473 - [debug] [WD Proxy] Got response with status 200: {"value":{"sessionId":"2455F15E-3C3B-4ED9-849C-47FBD1A0F1EC","capabilities":{"device":"iphone","browserName":"MYAPP","sdkVersion":"12.1.4","CFBundleIdentifier":"com.MyApp"}},"sessionId":"2455F15E-3C3B-4ED9-849C-47FBD1A0F1EC","status":0}
09:42:31:474 - [debug] [BaseDriver] Event 'wdaSessionStarted' logged at 1551768151474
...
```

While there is pause, in iOS log I could see this:
```
...
09:41:32 MyApp <Notice>: nw_connection_report_state_with_handler_locked [C4] reporting state cancelled
09:42:31 WebDriverAgentRunner-Runner(WebDriverAgentLib)[357] <Notice>: Enqueue Failure: Application 'com.MyApp' does not have a process ID /Users/admin/appium/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
...
```
So, it seems that in the end of pause I got this error: `Enqueue Failure ...`.

2) Strange 2 log lines, **after each request from test script**:

`Connection to WDA timed out` and next `recv failed: Operation not permitted`.
```
...
09:42:31:926 - [debug] [WD Proxy] Got response with status 200: {"value":{"ELEMENT":"2A000000-0000-0000-6801-000000000000"},"sessionId":"2455F15E-3C3B-4ED9-849C-47FBD1A0F1EC","status":0}
09:42:31:927 - [debug] [XCUITest] Connection to WDA timed out
09:42:31:927 - [debug] [iProxy] recv failed: Operation not permitted
09:42:31:928 - [debug] [W3C (38d605da)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"2A000000-0000-0000-6801-000000000000","ELEMENT":"2A000000-0000-0000-6801-000000000000"}
...
09:42:32:109 - [debug] [WD Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"width\" : 375,\n    \"height\" : 812\n  },\n  \"sessionId\" : \"2455F15E-3C3B-4ED9-849C-47FBD1A0F1EC\",\n  \"status\" : 0\n}"
09:42:32:110 - [debug] [XCUITest] Connection to WDA timed out
09:42:32:110 - [debug] [iProxy] recv failed: Operation not permitted
...
and so on
```

### Environment
Appium server v1.11.1 running on Mac mini (macOS 10.13.6) with Xcode 10.1 and NodeJS v10.15.1.
Real device iPhone X (iOS 12.1) and iPhone 5SE (iOS 11.3).
AVA 1.2.0 as testrunner (developer environment is Ubuntu).

**Comment by moagarwa** [comment]
I am also facing the issue but these are two separate issues.

**Comment by mykola-mokhnach** [comment]
> WebDriverAgentRunner-Runner[746:394429] Enqueue Failure: Failure getting list of active applications: (null) /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1.

This is a problem of WebDriverAgent/XCTest itself. Please report the issue to https://github.com/facebook/WebDriverAgent
