### ISSUE TITLE
Create automation Windows tests for FrameMaker using appium - probleme with inspection

### ISSUE THREAD

**Issue by ayoublind** [appium/appium#12258]
## The problem

i would like to know if anyone can help me with some isues with inspecting elements using appium to inspect FrameMaker elements to create automation tests for this application.

The probleme is that when i want to get elements in the workspace, menu and text preferences ... i can juste get some of the windows (FrameMaker) elements !

I already use windows SDK inspector and appium inspector, but i get no result !

first Windows Ok : 
[https://i.stack.imgur.com/QWtCz.png](url)

But when i get into the app i cannot see workspace elements ! 
[https://i.stack.imgur.com/IWF4i.png](url)

## I'm trying to write tests automation using java for this application :
`
    import java.net.URL;
    import java.util.List;
    import java.util.concurrent.TimeUnit;

    import org.junit.BeforeClass;
    import org.junit.Test;
    import org.openqa.selenium.WebElement;
    import org.openqa.selenium.remote.DesiredCapabilities;

    import io.appium.java_client.windows.WindowsDriver;

    public class RemoteConnectionTest {

    private static WindowsDriver connexionSession = null;

    @BeforeClass
    public static void setup() {
        try {
            DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities.setCapability("app",
                "D:\\AppsDev\\AdobeFramemaker2019\\Adobe FrameMaker 2019\\FrameMaker.exe");

            capabilities.setCapability("deviceName", "DESKTOP-F7DUTDS");
            // 192.168.1.70
            connexionSession = new WindowsDriver(new URL("http://192.168.0.109:4723/wd/hub"), capabilities);
            connexionSession.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Test
    public void creation_d_un_nouveau_document() throws InterruptedException {
        // j'attends
        Thread.sleep(10 * 1000);
        //
        connexionSession.findElementByName("Fichier").click();
        connexionSession.findElementByName("Fichier").click();
        assertTrue("Je ne peux pas Clicker sur le menu Fichier afin d'utiliser l'application", true);

        // nouveau
        connexionSession.getKeyboard().releaseKey(Keys.chord(Keys.CONTROL, "n"));
        assertTrue("Je ne peut pas clicker sur nouveau pour lancer la création du document", true);
    }
}`
or if any one can help me with windows test automation, i will be so greatfull.

**Comment by mykola-mokhnach** [comment]
I'd try to ask at discuss.appium.io
