### ISSUE TITLE
ERROR webdriver: Request failed due to unknown error: An unknown server-side error occurred while processing the command. Original error: Remote debugger is not connected

### ISSUE THREAD

**Issue by gauravgandhi15** [appium/appium#12251]
## The problem

I have been getting this error when i try to run appium scripts(Web scripts on safari) on iOS device. I don't see this error when i run these tests on simulator.

## Environment

* Appium version : 1.10.0
* OS/version used to run Appium: iOS 12.0
* Node.js version (unless using Appium.app|exe): 8.9.4
* Npm version: 5.6.0
* Real device or emulator/simulator: real device

Appium logs: https://gist.github.com/gauravgandhi15/9bca34b5036539525e2d341503231fe4

Code: ` platformName: "iOS",
            platformVersion: "12.0",
            deviceName: "Gaurav's iPhone",
            browserName: "Safari",
            automationName: "XCUITest",
            udid: "......",
            xcodeOrgId: "......",
            xcodeSigningId: "iPhone Developer",
            startIWDP: true,
            updatedWDABundleId: ".....",`

I am also running this as well: `ios_webkit_debug_proxy -c udid -d`

**Comment by imurchie** [comment]
Appium expects `ios-webkit-debug-proxy` to be running on port `27753`. Please try using the command
```
ios_webkit_debug_proxy -c <udid>:27753 -d
```

**Comment by gauravgandhi15** [comment]
> Appium expects `ios-webkit-debug-proxy` to be running on port `27753`. Please try using the command
> 
> ```
> ios_webkit_debug_proxy -c <udid>:27753 -d
> ```

Getting this error - Unable to bind udid on port 27753-27753

**Comment by imurchie** [comment]
Something else might be on the port. You can use a different port and set the `webkitDebugProxyPort` desired capability with the port chosen.

**Comment by gauravgandhi15** [comment]
> webkitDebugProxyPort

@imurchie It works now. Thanks for your help. Closing this issue

**Comment by imurchie** [comment]
Excellent!

**Comment by gauravgandhi15** [comment]
> Excellent!

@imurchie again seeing this issue - https://gist.github.com/gauravgandhi15/883ce910db4fa1927d38e9ec1b4add0e

**Comment by imurchie** [comment]
Did it disconnect? What is happening in the `ios-webkit-debug-proxy` terminal?

**Comment by gauravgandhi15** [comment]
> Did it disconnect? What is happening in the `ios-webkit-debug-proxy` terminal?

@imurchie  here - https://gist.github.com/gauravgandhi15/d95333c72874595199867b107d22a94f

**Comment by gauravgandhi15** [comment]
> > Did it disconnect? What is happening in the `ios-webkit-debug-proxy` terminal?
> 
> @imurchie here - https://gist.github.com/gauravgandhi15/d95333c72874595199867b107d22a94f

@imurchie Would you be able to help?

**Comment by gauravgandhi15** [comment]
> > > Did it disconnect? What is happening in the `ios-webkit-debug-proxy` terminal?
> > 
> > 
> > @imurchie here - https://gist.github.com/gauravgandhi15/d95333c72874595199867b107d22a94f
> 
> @imurchie Would you be able to help?

@imurchie I just reset my phone and everything worked at first go. But after 2-3 successful runs, it keeps on giving the same error again. And my device reboots as well when i run my scripts.

**Comment by gauravgandhi15** [comment]
> > > > Did it disconnect? What is happening in the `ios-webkit-debug-proxy` terminal?
> > > 
> > > 
> > > @imurchie here - https://gist.github.com/gauravgandhi15/d95333c72874595199867b107d22a94f
> > 
> > 
> > @imurchie Would you be able to help?
> 
> @imurchie I just reset my phone and everything worked at first go. But after 2-3 successful runs, it keeps on giving the same error again. And my device reboots as well when i run my scripts.

@imurchie Please let me know what you think

**Comment by gauravgandhi15** [comment]
> I just reset my phone and everything worked at first go. But after 2-3 successful runs, it keeps on giving the same error again. And my device reboots as well when i run my scripts

@imurchie This is what exactly happening - When i start a new session at new port 27758, everything worked at first go. But after 2-3 successful runs, it keeps on giving the same error again. And then i closed the 27758 and started a new session on 27760 and again everything works fine. So anytime i start a new session on new port, everything works smoothly until 2-3 runs. What do you think, why i this happening?

**Comment by gauravgandhi15** [comment]
> > I just reset my phone and everything worked at first go. But after 2-3 successful runs, it keeps on giving the same error again. And my device reboots as well when i run my scripts
> 
> @imurchie This is what exactly happening - When i start a new session at new port 27758, everything worked at first go. But after 2-3 successful runs, it keeps on giving the same error again. And then i closed the 27758 and started a new session on 27760 and again everything works fine. So anytime i start a new session on new port, everything works smoothly until 2-3 runs. What do you think, why i this happening?

@imurchie Can you please help me out?

**Comment by gauravgandhi15** [comment]
> > > I just reset my phone and everything worked at first go. But after 2-3 successful runs, it keeps on giving the same error again. And my device reboots as well when i run my scripts
> > 
> > 
> > @imurchie This is what exactly happening - When i start a new session at new port 27758, everything worked at first go. But after 2-3 successful runs, it keeps on giving the same error again. And then i closed the 27758 and started a new session on 27760 and again everything works fine. So anytime i start a new session on new port, everything works smoothly until 2-3 runs. What do you think, why i this happening?
> 
> @imurchie Can you please help me out?

@imurchie Can you please help me out on this?

**Comment by imurchie** [comment]
I have no idea why this is happening. Something wrong with the `ios-webkit-debug-proxy`, which Google controls. 

I would add it to the workflow to restart the proxy with each test. Appium can do that for you, if you use the `startIWDP ` desired capability.

**Comment by gauravgandhi15** [comment]
> I have no idea why this is happening. Something wrong with the `ios-webkit-debug-proxy`, which Google controls.
> 
> I would add it to the workflow to restart the proxy with each test. Appium can do that for you, if you use the `startIWDP ` desired capability.

Yes, i have added `startIWDP ` but even it throws same error few times. Does it reset everytime by itself or do i need to add anything to reset it?

**Comment by gauravgandhi15** [comment]
> > I have no idea why this is happening. Something wrong with the `ios-webkit-debug-proxy`, which Google controls.
> > I would add it to the workflow to restart the proxy with each test. Appium can do that for you, if you use the `startIWDP ` desired capability.
> 
> Yes, i have added `startIWDP ` but even it throws same error few times. Does it reset everytime by itself or do i need to add anything to reset it?

@imurchie

**Comment by imurchie** [comment]
It should reset on its own.

**Comment by mykola-mokhnach** [comment]
This should work now with appium@beta
