### ISSUE TITLE
Android: Got an unexpected response in .Sendkeys

### ISSUE THREAD

**Issue by jarkkop** [appium/appium#12250]
## The problem

The script runs fine in NATIVE mode and then does something correctly also in Webview mode, then it return back to NATIVE mode. The error happen first thing in the native mode when it tries to put a string in the field. The log says: "Cannot set the element to '1'. Did you interact with the correct element? "
Page source query just before the error shows that valid looking xml file containing the field I am trying to locate really exists: 'com.foobar.app:id/first_pin'

<android.widget.TextView index="1" package="com.foobar.app" class="android.widget.TextView" text="" resource-id="com.foobar.app:id/first_pin" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="true" bounds="[291,492][396,597]" displayed="true" />

## Environment

Appium v1.11.1
Mac OS High Sierrra 10.13.6 (17G65)
Nodejs: v10.11.0
npm: 6.8.0

		File f = new File("src");
		File fs = new File(f, "com.foobar.app_1.0.0_001.apk");		
			
		cap.setCapability(MobileCapabilityType.DEVICE_NAME, "Android");
		cap.setCapability("platformName", "Android"); // new
		cap.setCapability("automationName", "uiautomator2"); // new
		cap.setCapability(MobileCapabilityType.APP, fs.getAbsolutePath());		
		cap.setCapability("appWaitActivity", "com.foobar.app.login.LoginActivity");

Android Studio 3.3.1
Build #AI-182.5107.16.33.5264788, built on January 29, 2019
JRE: 1.8.0_152-release-1248-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

Appium CLI

## Link to Appium logs

jarkkop / gist:6eb55b1052a87b816d7b5654ad0fdee6

## Code To Reproduce Issue

	     		MobileElement el2 = (MobileElement) driver.findElementById("code");
		el2.sendKeys("1234");
				
		 driver.findElementByXPath("//*[@id=\"form\"]/div[1]/span/input").click();
		 driver.context("NATIVE_APP");
	     try {
			 MobileElement pin = (MobileElement) (new WebDriverWait(driver, 45))
						.until(ExpectedConditions.elementToBeClickable(By.id("com.foobar.app:id/first_pin")));
			 	pin.setValue("1234");
		    	 Set<String> s=driver.getContextHandles();
			     for(String handle : s)
			     {
			    	 System.out.println(handle);
			     }
					System.out.println(driver.getPageSource());
		     } catch (Exception e) {
		    	 Set<String> s=driver.getContextHandles();
			     for(String handle : s)
			     {
			    	 System.out.println(handle);
			     }
					System.out.println(driver.getPageSource());
					MobileElement pini = driver.findElement(By.xpath("//android.widget.TextView[@resource-id='com.foobar.app:id/first_pin']"));
driver.findElementById("com.foobar.app:id/first_pin");
					pini.sendKeys("1");

				}

**Comment by mykola-mokhnach** [comment]
Please attach the correct server log

**Comment by jarkkop** [comment]
gist content updated
<script src="https://gist.github.com/jarkkop/6eb55b1052a87b816d7b5654ad0fdee6.js"></script>

**Comment by mykola-mokhnach** [comment]
This error is thrown if UIA2 framework is unable to invoke setText on the particular element. There is nothing to do there from Appium side. Make sure the correct control is located there.

**Comment by jarkkop** [comment]
I think the older UIAutomator worked just fine with this control and allowed to set this kind of string to it.

**Comment by mykola-mokhnach** [comment]
The old framework uses `adb input text` workaround in order to input text due to legacy issues. this could be simulated by UIA2 by using keyboard [actions](https://appiumpro.com/editions/46), for example.

**Comment by jarkkop** [comment]
The developer said that under the four one digit fields there is one hidden text field that all these four characters go. This was done to reduce parsing of the four different fields. When one clicks any of the four one digit number character field, the focus is set to appropriate place in the hidden field. The developer was surprised that the hidden field is not showing in the xml appium is seeing.  The hidden field was: com.foobar.app:id/hidden_input_field

**Comment by jarkkop** [comment]
Thanks, Actions worked fine in my case. Problem solved
