### ISSUE TITLE
Appium Desktop for Mac Dialog Spelling Error: "immprove"

### ISSUE THREAD

**Issue by patweb** [appium/appium#12254]
## The problem

After installing Appium Desktop 1.11.0 for Mac, a dialog appears asking the user, "Can Appium Desktop collect crash log data from you to help immprove the product?" The word "improve" is spelled wrong.

## Environment
* Appium Desktop for Mac 1.11.0
* OS X 10.14.3

## Screenshot
![immprove-appiumdesktop1 11 0](https://user-images.githubusercontent.com/522434/53763765-67387500-3e80-11e9-97a3-7cc7bdf031cd.png)

**Comment by KazuCocoa** [comment]
yes, thanks
