### ISSUE TITLE
Unable to run multiremote tests against Android emulator using Chrome

### ISSUE THREAD

**Issue by VonRaefels** [appium/appium#12267]
## The problem

Trying to run a test suite using webdriverio and Appium to test against two simultaneous android emulators does not start the browsers on both devices.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.11.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOs Mojave 10.14
* Node.js version (unless using Appium.app|exe): v9.9.0
* Npm or Yarn package manager: 6.5.0
* Mobile platform/version under test: Android, platform version 9
* Real device or emulator/simulator: Nexus_5X_API_28_x86 and Pixel_2_API_28
* Appium CLI or Appium.app|exe: Appium.app

## Details

When running te tests it seems that Appium does not detect multiple capabilities and reports that the device with a particular id is not found; I do not know if this is possible with Appium in the same way it is possible with a single OS and multiple browsers.

## Link to Appium logs

https://gist.github.com/VonRaefels/9bbdef0780ae5c35381b45ddc452bef4

## Code To Reproduce Issue [ Good To Have ]
The udid of the devices was found by using:
```
adb -s  emulator-5554 shell 'settings get secure android_id'
adb -s  emulator-5556 shell 'settings get secure android_id'
```

```The webdriverIO config is the following:
        "browser0": {
          capabilities: {
            browserName: 'chrome',
            udid: '622261989ba942ba',
            appiumVersion: '1.11.1',
            deviceName : 'emulator-5556',
            platformVersion : '9',
            platformName : 'Android'
          }
        },
        "browser1": {
          capabilities: {
            browserName: 'chrome',
            udid: 'c355cff74418c3c0',
            appiumVersion: '1.11.1',
            deviceName : 'emulator-5554',
            platformVersion : '9',
            platformName : 'Android'
          }
        }

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/parallel-tests.md
