### ISSUE TITLE
[Android] Original error: Set the orientation, but app refused to rotate.

### ISSUE THREAD

**Issue by lamquangthanh** [appium/appium#12264]
## The problem

Have a problem with orientation on tablette. Not happen on smartphone.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.11.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: win 10
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: SS Tab S3 -Android 7
* Real device or emulator/simulator: Real devices
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/lamquangthanh/dafdaba054efde7fd692ad218794cd29#file-gistfile1-txt

## Java log

An unknown server-side error occurred while processing the command. Original error: Set the orientation, but app refused to rotate.
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'EVN-D-W-0017', ip: '10.161.206.82', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_171'
Driver info: driver.version: AppiumAndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Set the orientation, but app refused to rotate.
    at errorFromMJSONWPStatusCode

**Comment by mykola-mokhnach** [comment]
I think this is rather a problem with the app under test.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue. There is nothing to do there from appium side.
