### ISSUE TITLE
[Android] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: io.appium.uiautomator2.common.exceptions.UiAutomator2Exception

### ISSUE THREAD

**Issue by nichotined** [appium/appium#12265]
## The problem

I try to interact element such as clicking but I got return 500 with error attached on gist.
In some cases I can interact but only on this page I couldn't do anything except getting the source.

## Environment

* Appium version appium@1.11.0-beta.3
* Desktop OS/version used to run Appium: Mac OS
* Node.js version v9.11.2
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: Android
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details
```
&{APPIUM_CAPS}      platformName=Android
...                 platformVersion=7.1.1
...                 udid=emulator-5554
...                 deviceName=emulator
...                 automationName=UiAutomator2
...                 appPackage=com.xxx.app.staging
...                 appActivity=com.xxx.app.home.HomeActivity
...                 newCommandTimeout=5000
...                 APPIUM_SERVER=http://0.0.0.0:4798/wd/hub
...                 ignoreUnimportantViews=true
...                 normalizeTagNames=true
```

## Link to Appium logs

GIST Appium Log https://gist.github.com/nichotined/b6c98131d4246a6658065ac45b4ddfb4

## Code To Reproduce Issue [ Good To Have ]

```
driver.find_element_by_xpath("//*[@text="xxx"]").click()
```

**Comment by mykola-mokhnach** [comment]
> [WD Proxy] Got an unexpected response: {"sessionId":"459c1392-3432-4fa8-836a-e9f873657d69","status":13,"value":"io.appium.uiautomator2.common.exceptions.UiAutomator2Exception: Error on line 100: At line 100, column 54: not well-formed (invalid token). Try changing the 'normalizeTagNames' driver setting to 'true' in order to workaround...

**Comment by nichotined** [comment]
I have added that to my caps, still got the same error.

**Comment by mykola-mokhnach** [comment]
It is not a capability, but a driver setting

**Comment by nichotined** [comment]
Can you give me an example how to set that?

**Comment by mykola-mokhnach** [comment]
Can you use search to find it yourself?

**Comment by nichotined** [comment]
Got it thanks! 
http://appium.io/docs/en/advanced-concepts/settings/

**Comment by nichotined** [comment]
Thanks @mykola-mokhnach it works!!

**Comment by thouger** [comment]
Thanks @nichotined ,it worked!
