### ISSUE TITLE
Unable to inspect elements of a custom launcher running on a proprietary hardware

### ISSUE THREAD

**Issue by sindhu576** [appium/appium#12263]
## The problem

I am trying to inspect the elements of a custom made launcher with Android 8.0 running on proprietary
hardware. The launcher screen on which i am trying to inspect the elements is not made of single app package or activity. Its a group of windows which as a whole from the launcher with elements

Means "Once a session is launched with a appPackage, i need to launch another appPackage on top of that either by creating a new session or some thing like holding the previous session." Please let me know for any solution you may think possible

## Environment

* Appium Desktop -1.10.0 , 1.11.0
* Linux - ubuntu16.04
* Android 8.0.0
* Real device
* Appium Desktop (.appImage)

## Details

- At first, i tried passing the app package and activity of launcher(which is supposed to be wrong way as a single app package cannot form my launcher screen) and inspected the elements but in vain.

- Then i understood that "All the elements on my launcher screen will not come under the given package name" and so i thought passing multiple appPackages to desired capabilities may solve my problem.

- But am not sure if i can pass multiple app packages

**Comment by mykola-mokhnach** [comment]
This is pretty all we have https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md

**Comment by sindhu576** [comment]
is there a way to give multiple app packages to appium in same session

**Comment by mykola-mokhnach** [comment]
It is impossible to pass multiple packages. Custom solutions require custom automation frameworks
