### ISSUE TITLE
Using driver.findElementsByImage to find black screens in my app but fails

### ISSUE THREAD

**Issue by eyalpartner** [appium/appium#12260]
## The problem

I am using driver.findElementsByImage to compare screenshot that I already took (Full black screen)
with the current screen of the android device, In order ro catch the black screen I must have while loop that will detect the black screen when he's apear and then the loop will break and I will get mail+screenshot and log about the black screen, But I can't get the test to catch black screens.

## Environment

* Appium version: 1.11.1
* OS used to run Appium: Windows 10
* Node.js version: v11.10.1
* Npm version: 6.7.0
*Java version: 10.0.2 2018-07-17
* Mobile Real device: Android 7
* Appium CLI

## Code To Reproduce Issue

byte[] fileContent = FileUtils.readFileToByteArray(new File("C:\\Users\\OSN20933\\Pictures\\sleep_black.png"));
        String encodedString = Base64.encodeBase64String(fileContent);
        boolean el = driver.findElementsByImage(encodedString).size() > 0 ;
        while (el) {
        }
        takeScreenShot();
        Log.info("Black screen just catched !!!");
        Send.email();

**Comment by mykola-mokhnach** [comment]
Image matching is done by OpenCV. Try different image matching options. If these don't work then there's nothing else to do on Appium side.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
