### ISSUE TITLE
uiautomator2 issue in entering the string to a textbox

### ISSUE THREAD

**Issue by anilkn72** [appium/appium#12271]
## The problem is in uiautomator2 not able to enter the string data in a textbox field, instead it getting pasted.

In uiautomator was supporting the typing of letters, however uiautomator2 is not typing instead it is pasting the data in the textbox field. In my test scenario when the data's first 3 letters are entered the full data will display which can be selected by clicking on that which is not happening with the uiautomator2. 

## Environment

* Appium version (or git revision) that exhibits the issue:  1.8.1 with uiautomator2 
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2 without uiautomator2
* Desktop OS/version used to run Appium:Windows 10
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: 6.0.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Details

In uiautomator was supporting the typing of letters, however uiautomator2 is not typing instead it is pasting the data in the textbox field. In my test scenario when the data's first 3 letters are entered the full data will display which can be selected by clicking on that which is not happening with the uiautomator2. 

## Link to Appium logs

https://gist.github.com/anilkn72/99a6a5770352b522a55a4a410cf802d2

## Code To Reproduce Issue [ Good To Have ]

baseClass.getDriver().findElement(By.id("com.hul.humarashop.mobile.stg:id/auto_city"))
						.sendKeys(storeName);
TouchAction touch= new TouchAction(baseClass.getDriver());
				
	            touch.press(526, 931).waitAction(Duration.ofMillis(3000)).release().perform();

**Comment by mykola-mokhnach** [comment]
Such behaviour is expected . You can either use https://appiumpro.com/editions/46 or https://appiumpro.com/editions/34 to emulate keys input with UIA2.

**Comment by anilkn72** [comment]
Thank you, it's working now on my local system.
When i execute the same code in device farm for the google pixel device, elements are not identified.

**Comment by anilkn72** [comment]
[4abaf8d7-b1bd-4847-a262-9ab51a9115e4 (1).txt](https://github.com/appium/appium/files/2956180/4abaf8d7-b1bd-4847-a262-9ab51a9115e4.1.txt)
please find the log file of appium server on device farm, elements are not identifying using UIAutomator2 in device farm, however in local it is working fine.
 The device used in device farm is google pixel, local is redmi note 4.
