### ISSUE TITLE
adb could NOT be found at '/usr/local/share/android-sdk/platform-tools/adb'!

### ISSUE THREAD

**Issue by gnuhub** [appium/appium#12277]
## The problem
* install 
```
brew cask install android-sdk
brew cask install android-platform-tools
```
```
adb could NOT be found at '/usr/local/share/android-sdk/platform-tools/adb'!
```
## check
```
 which adb
/usr/local/bin/adb
```

* https://github.com/appium/appium-doctor/blob/master/lib/android.js#L44

* ppium-doctor just check $ANDROID_HOME/platform-tools/adb

**Comment by KazuCocoa** [comment]
What is the output `ls $ANDROID_HOME` in your env?

Appium also calls adb in `$ANDROID_HOME/platform-tools` first.

https://github.com/appium/appium-adb/blob/d995ddc16395921efbd4da583ad2cd6086bcb19c/lib/tools/system-calls.js#L86-L94

If it has no it, appium calls https://github.com/appium/appium-adb/blob/d995ddc16395921efbd4da583ad2cd6086bcb19c/lib/tools/system-calls.js#L121-L134 as a fallback if the env has no `$ANDROID_HOME`
