### ISSUE TITLE
Unable to hide keyboard with Java Client 7.0.0 and Appium 1.10.1 CLI for iOS real device

### ISSUE THREAD

**Issue by Hashilima** [appium/appium#12279]
## The problem
Unable to hide keyboard with Java Client 7.0.0 and Appium 1.10.1 CLI for iOS real device
## Environment

* Appium version (or git revision) that exhibits the issue:1.10.1
* Desktop OS/version used to run Appium:CLI
* Mobile platform/version under test: iOS Real device
* Real device or emulator/simulator: iOS real device
* Appium CLI or Appium.app|exe: CLI

## Details

I want to hide the device keyboard for a reach native application on iOS. The hide keyboard function is not hide the device keyboard. appium is not giving any error.

## Code To Reproduce Issue [ Good To Have ]

driver.hideKeyboard();

**Comment by mykola-mokhnach** [comment]
Such behaviour is expected, this is known XCTest limitation. You could try to hide the keyboard as a normal application user would do it (for example by clicking Done button). Closed as duplicate.
