### ISSUE TITLE
Unable to install APK. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability"

### ISSUE THREAD

**Issue by IgalKorb** [appium/appium#12287]
## The problem

We use Appium to test our Android application and test fail because:

"[debug] [W3C] Encountered internal error running command: Error executing adbExec. Original error: 'Command '/usr/local/share/android-sdk/platform-tools/adb -P 5037 -s LGH930***** install /usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.2.2.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability"

We increased the timeout by setting 'adbExecTimeout' capability to 120000ms. The attached appium log shows that it was set to 120000ms however it still times out after the default 20000ms. We would like to overcome the issue of failing tests because of the inability to install the APK.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.11.1
* Last Appium version that did not exhibit the issue (if applicable): 1.10
* Desktop OS/version used to run Appium: MacOS/Ubuntu 16.04
* Node.js version (unless using Appium.app|exe): 11.7/11.11
* Npm or Yarn package manager: 6.9
* Mobile platform/version under test: LG V30 - v8.0.0
* Real device or emulator/simulator: real
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

https://gist.github.com/IgalKorb/5c69bc2da71af046d6b89a83134c8723

## Code To Reproduce Issue [ Good To Have ]
python 3.7: (executed with pytest)
    capabilities = {'automationName': 'UiAutomator2',
                    'platformName': 'Android',
                    'deviceName': 'Android',
                    'autoLaunch': False,
                    'skipUnlock': True,
                    'autoGrantPermissions': False,
                    'adbExecTimeout': 120000,
                    'newCommandTimeout': 0,
                    'unlockType': 'pattern;,
                    'unlockKey': 14589,
                    'app': 'app_to_test.apk'
                    }

    url = 'http://localhost:4723/wd/hub'
    driver = webdriver.Remote(url, capabilities)

**Comment by IgalKorb** [comment]
#12227 - was fixed and closed for uninstall functionality - mine is about install functionality

**Comment by KazuCocoa** [comment]
That was a wrong error message fixed in https://github.com/appium/appium-uiautomator2-driver/pull/300 (it will be in next release)

`uiautomator2ServerInstallTimeout` is correct capability name for UIA2 server installation.

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md#uiautomator2-only

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by nikolmarku1** [comment]
hi, a bit confused on this "skipServerInstallation" default value is false so why do we need to set uiautomator2ServerInstallTimeout ?   
ths

**Comment by KazuCocoa** [comment]
Do you mean you got the error message about `uiautomator2ServerInstallTimeout ` while you set `skipServerInstallation` `false`?
The message, `uiautomator2ServerInstallTimeout`,  appears when Appium installs UIA2 servers.

Could you attach the server log?

**Comment by risinek** [comment]
@KazuCocoa `skipServerInstallation` set to `false` means that it **won't** skip the installation. If you want to skip the server installation, you have to set it to `true`

**Comment by ameerhamza6733** [comment]
I was facing same error, appium work fine on my local device but i was trying to connect with AWS genymotion over TCP port 5555, i spend 4 hours to find out i can manually install apk using cmd/terminal and turn of with flag  `skipServerInstallation ` , if you facing same error then 

1)install using adb  C:\Users\LENOVO\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\\appium-uiautomator2-server-v4.27.0.apk 
2)add `skipServerInstallation ` == true to your appium inspector

**Comment by kirbycope** [comment]
Setting this worked for me, `caps["uiautomator2ServerInstallTimeout"] = 60000`
I was trying to run the emulator on GitHub Actions using "reactivecircus/android-emulator-runner@v2".

**Comment by tjoselemonade** [comment]
@kirbycope where did you set the config?

**Comment by kirbycope** [comment]
@tjoselemonade 
https://github.com/kirbycope/cucumber-python/blob/eaad72a43548e75507178c2e3c06e3153686a069/altunity_tester/features/environment.py#L88
