### ISSUE TITLE
Problem with screenshot for the first element on Android in Landscape

### ISSUE THREAD

**Issue by bart-tricentis** [appium/appium#12280]
## The problem

I was trying to get a screenshot for the whole app without the navigation bar, I wanted to achieve this by selecting the very first element with UIAutomator. I was successful with the device in Portrait orientation, but when I switched to Landscape a part of the screenshot is cut. Do you have any idea how come ?

![all](https://user-images.githubusercontent.com/44870697/54106521-ca715c80-43d6-11e9-8648-006b90b89d67.jpg)
![main](https://user-images.githubusercontent.com/44870697/54106541-d65d1e80-43d6-11e9-92d8-ef64bd8e2f3a.jpg)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): v8.11.1
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Andorid 8
* Real device or emulator/simulator: simulator (Google Pixel 3)
* Appium CLI or Appium.app|exe: cli

## Code To Reproduce Issue [ Good To Have ]

            driver.Orientation = ScreenOrientation.Landscape;
            Bitmap bmp = new Bitmap(new MemoryStream(driver.GetScreenshot().AsByteArray));
            bmp.Save("all.jpg", ImageFormat.Jpeg);
            
            AndroidDriver<IWebElement> androidWebDriver = driver as AndroidDriver<IWebElement>;
            RemoteWebElement window =
                (RemoteWebElement) androidWebDriver.FindElementByAndroidUIAutomator("new UiSelector().index(0)");
            bmp = new Bitmap(new MemoryStream(window.GetScreenshot().AsByteArray));
            bmp.Save("main.jpg", ImageFormat.Jpeg);

**Comment by mykola-mokhnach** [comment]
I would consider reporting the problem to Google

**Comment by bart-tricentis** [comment]
Did just that https://issuetracker.google.com/issues/128352531

**Comment by mykola-mokhnach** [comment]
Closing the issue as third party siren there is nothing we can do about it. Feel free to post updates from Google on it if any
