### ISSUE TITLE
Test script is not exiting for 10 min on real device with NosuchElementError in appium console

### ISSUE THREAD

**Issue by himanshu27in** [appium/appium#12282]
## The problem
I am running my test script using appium and python for mobile app testing on  real device and purposefully i am failing my script where it is not able to find element but it is taking 10 min to exit the test case and keep on looking for element and after timeout i will get below msg:
ProtocolError
('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

## Environment

* Appium version (or git revision) that exhibits the issue: Appium: 1.11.1
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: windows 10
* Node.js version (unless using Appium.app|exe): 10.15.0
* Npm or Yarn package manager:
* Mobile platform/version under test: Samsung S9(9.0)
* Real device or emulator/simulator:Real device Samsung S9(9.0)
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'com.example.nativeaudio:id/input_email' using 'ID' with the contextId: '' multiple: false
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=com.example.nativeaudio:id/input_email]
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [MJSONWP] Matched JSONWP error code 7 to NoSuchElementError
[debug] [BaseDriver] Waited for 360941 ms so far
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":7,"value":"No element found"}
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"com.example.nativeaudio:id/input_email","context":"","multiple":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"com.example.nativeaudio:id/input_email","context":"","multiple":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'com.example.nativeaudio:id/input_email' using 'ID' with the contextId: '' multiple: false
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=com.example.nativeaudio:id/input_email]
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Failed to locate element. Clearing Accessibility cache and retrying.
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'com.example.nativeaudio:id/input_email' using 'ID' with the contextId: '' multiple: false
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=com.example.nativeaudio:id/input_email]
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":7,"value":"No element found"}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [MJSONWP] Matched JSONWP error code 7 to NoSuchElementError
[debug] [BaseDriver] Waited for 361767 ms so far

## Code To Reproduce Issue [ Good To Have ]

    def test_00_appLaunch(self):
        self.driver.implicitly_wait(constants.wait_for_app_launch)
        # AppAccessToDevice.device_access(self)
        time.sleep(2)
        AppHomeAndLoginPage.start_exploring(self)
        time.sleep(5)
        copyfile("./personifi_logging.log", run_suite.Failed_Test_Log_Folder + r'\test_00_appLaunch.txt')
        try:
            # loginpage = AppHomeAndLoginPage.email_field(self).is_displayed()
            # assert loginpage
            element = WebDriverWait(self.driver, 10).until(
                EC.presence_of_element_located((By.ID, "com.example.nativeaudio:id/input_email"))
            )

        except NoSuchElementException or ElementNotVisibleException:
            copyfile("./personifi_logging.log", run_suite.Failed_Test_Log_Folder + r'/test_00_appLaunch.txt')
            print("Element not found : Ready icon is not present")
            assert False

**Comment by mykola-mokhnach** [comment]
Use UiAutomator2/Espresso for Android 6+
Closed as not an issue
