### ISSUE TITLE
Pull file from python on iOS device error - The remote file at '...' does not exist

### ISSUE THREAD

**Issue by MildaGenius** [appium/appium#12283]
## The problem

Pull file from python on iOS device return error
`The remote file at '/var/folders/0x/26gf30y158x_tlqkryc8tk800000gp/T/2019211-64195-6b13uo.a0fyv/com.bistudio.AppiumTest/testFile.txt' does not exist`

## Environment

* Appium version: 1.11.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS 10.14.3
* Node.js version (unless using Appium.app|exe): v10.15.1
* Npm package manager: 6.4.1
* Real device or emulator/simulator: iPad 9.7 with OS 11.3
* Appium CLI or Appium.app|exe: Desktop
* xCode: 10.1
* ifuse: 1.1.3

## Details

When try get file from testing application, I got error about non existing file.
`selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: The remote file at '/var/folders/0x/26gf30y158x_tlqkryc8tk800000gp/T/2019211-64195-6b13uo.a0fyv/com.bistudio.AppiumTest/testFile.txt' does not exist`

According to Appium log is problem in non existing mounting directory.
`/var/folders/0x/26gf30y158x_tlqkryc8tk800000gp/T/2019211-64195-6b13uo.a0fyv`

If I try to mount manually, I can see file in iOS device.
`ifuse -u com.bistudio.AppiumTest ~/mnt`

Is possible to get more detailed log from ifuse called from Appium?

## Link to Appium logs

[Python pull file test on iOS with iOSLog](https://gist.githubusercontent.com/MildaGenius/5de8fd74a5e34f04400de9dcec8cc25d/raw/5c9a1b756d9ed5f7158ccc41ef9409a10ec1c6c5/pullFile_iOS_appium-server-logs.txt)
[Python pull file test on iOS without iOSLog](https://gist.github.com/MildaGenius/68cbd4bab820de6cd7e2b387d426add8)

## Code To Reproduce Issue [ Good To Have ]

[Test script for pull file from iOS device over Appium](https://gist.github.com/MildaGenius/a9eaf629880ff83b3410897d0b5b4e7b)

**Comment by mykola-mokhnach** [comment]
I assume the method argument is wrong. If the file is supposed to be pulled from a container then the path format is expected to look like `@bundle.identifier:container_type/relative_path_in_container`. Check https://github.com/appium/appium-xcuitest-driver/blob/e99be8d47eab52519d385b62109773bd63c4c6f2/lib/commands/file-movement.js#L225

**Comment by MildaGenius** [comment]
Thanks,
after changed path, started with @, its work. Didnt find this information in any documentation.

`data = self.appiumdriver.pull_file("@com.bistudio.AppiumTest/Documents/testFile.txt")`

I have access to root of application container, so path to file must be relative.

Its the same to:
`ifuse --container com.bistudio.AppiumTest ~/mnt`

**Comment by mykola-mokhnach** [comment]
I'll mark the problem as documentation issue

**Comment by KazuCocoa** [comment]
a note:

- `brew cask install osxfuse && brew install ifuse --HEAD` to install via brew (`--HEAD` is necessary)
- `ifuse --list-apps` shows available bundle ids
    - We can verify if the applied bundle can mount. example:
    ```
    $ ifuse --list-apps
    com.apple.Keynote, "6383", "Keynote"
    com.amazon.Lassen, "1.0.205581.0.10", "Kindle"
    ```
- below error happens for `--container`
    - `$ ifuse --container com.apple.Keynote ./mnt`
    - `The App 'com.apple.Keynote' is either not present on the device, or the 'UIFileSharingEnabled' key is not set in its Info.plist. Starting with iOS 8.3 this key is mandatory to allow access to an app's Documents folder.`
    - https://github.com/appium/appium-xcuitest-driver/blob/e99be8d47eab52519d385b62109773bd63c4c6f2/lib/commands/file-movement.js#L245
- Can mount document
    ```
    $ ifuse --documents com.apple.Keynote ./mnt
    $ ls mnt/
    Inbox              kazuaki-matsuo.key
    ```
    - thus, maybe we can use `--documents` for specific path like `Documents` for `--documents`
         - It works for without `UIFileSharingEnabled`
    - but the `--documents` also shows `UIFileSharingEnabled` message if the bundle id is not in `ifuse --list-apps`
