### ISSUE TITLE
Type function not working on iOS

### ISSUE THREAD

**Issue by JavonDavis** [appium/appium#12285]
## The problem

When using the type function on an iOS emulator the text doesn't type as expected. See gif,

![out](https://user-images.githubusercontent.com/6520461/54164534-00403080-442b-11e9-9ab5-db32f11cff0f.gif)

## Environment

* appium v1.9.1
* appium cli
* MacOS Mojave
* ios simulator platform version 12.1

## Details

Works perfectly on Android but not iOS, this is using the appium wd client but this also reproducable using appium desktop application

![out](https://user-images.githubusercontent.com/6520461/54165042-17801d80-442d-11e9-9c52-d76e0c64fbb7.gif)

## Link to Appium logs

https://gist.github.com/JavonDavis/0f7e20e3bba0b567778f2a2230b53b22

## Code To Reproduce Issue [ Good To Have ]

`await element.type( str );`

**Comment by mykola-mokhnach** [comment]
Please report to https://github.com/facebook/WebDriverAgent 

Closed as third party issue

**Comment by JavonDavis** [comment]
Thanks @mykola-mokhnach I originally thought to do that but since the issue also happens in Appium Desktop I figured I'd try opening it here... Is it that Appium Desktop also uses https://github.com/facebook/WebDriverAgent?

**Comment by mykola-mokhnach** [comment]
Appium Desktop is just a graphical client to Appium. It does not contain any extra stuff

**Comment by JavonDavis** [comment]
> Appium Desktop is just a graphical client to Appium. It does not contain any extra stuff

Right, so in the gif in my issue when I try to send text via the desktop client it doesn't go through properly, wouldn't that point to an issue with Appium?

**Comment by JavonDavis** [comment]
FYI the application under test is https://github.com/wordpress-mobile/gutenberg-mobile
