### ISSUE TITLE
Only can get one webview on real device but there are two webviews except NATIVE_APP.

### ISSUE THREAD

**Issue by zhangliang1588** [appium/appium#12281]
## The problem

I can only get one webview on real device but there are two webviews except NATIVE_APP. But it's OK on simulator with Appium.

## Environment

* Appium version (or git revision) that exhibits the issue:
* Desktop OS/version used to run Appium:macOS High Sierra/10.13.6
* Mobile platform/version under test:iOS/12.1
* Real device or emulator/simulator:real device
* Appium CLI or Appium.app|exe:Appium.app

## Details

In the application there are two webviews and one is UIWebview and another is WKWebview. And the UIWebview is nested inside of WKWebview.

I am not able to get the UIWEbview on real device whereas in simulator I am easily getting both two webviews, but when I run the same set of scripts on real device it returns only 'NATIVE_APP' and WKWebview.

I can see all webviews  in Safari under develop tab.

## Link to Appium logs

https://gist.github.com/zhangliang1588/9deaa75c89ecddc3910458e6d754a364

## Code To Reproduce Issue [ Good To Have ]

                Set<String> contextNames = ((AppiumDriver) remoteWebDriver).getContextHandles();
                Log.info("Info : Current driver context name - " + ((AppiumDriver) remoteWebDriver).getContext());
                Log.info("Info : Total contexts - " + contextNames.size());
                for (String contextName : contextNames) {
                    if (contextName.toUpperCase().contains("WEBVIEW")) {
                        ((AppiumDriver) remoteWebDriver).context(contextName);
                        Log.info("Info : Trying with context - " + contextName);
                        Log.info("Info : Title - " + remoteWebDriver.getTitle());
                        if (remoteWebDriver.getTitle().contains(title)) {
                            Log.info("Info : Switch Webview to - " + contextName);
                            return true;
                        } else if (remoteWebDriver.getTitle().isEmpty()) {//some SSO WebView's title is empty
                            return true;
                        }
                    }
                }

**Comment by Jonahss** [comment]
Oh wow, the nested webview sounds like it could be tricky.

Have you tried changing context into the WKWebview, and then listing contexts again from there? Even though you don't have to do that on simulator...

Maybe @imurchie would know why the real device is behaving differently than the sim.

**Comment by ciekawy** [comment]
also could it be just another window? 
`browser.driver.getAllWindowHandles()`
