### ISSUE TITLE
Android Real Device testing via Sauce vUSB

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#12288]
Let's start testing on real android devices! Sauce Labs RDC has provisioned us with 6 real devices that we can use for continuous integration testing. Let's get these plugged into our CI pipeline and let's make some gulp tasks that instrument these features so that we can re-use this functionality across 

Acceptance criteria
* [ ] Write a gulp task that starts a real device so that it's visible via `adb devices` (something like `gulp vusb-android <device-name>`
* [ ] Add a CI pipeline to `android-uiautomator2-driver` that runs e2e tests against our devices
* [ ] Add a CI pipeline to `android-espresso-driver` too
* [ ] Try running `appium-adb` tests, and see if that's something we want to add too

**Comment by mykola-mokhnach** [comment]
Closed as obsolete
