### ISSUE TITLE
Issues on Android during long running tests. Session closes mid-way automatically

### ISSUE THREAD

**Issue by gkvappium** [appium/appium#12294]
## The problem
Issues on Android during long running tests. Session closes mid-way automatically

## Environment

* Appium version (or git revision) that exhibits the issue: 1.11.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOSX
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Android 8.0 and 9.0
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

There is a scenario wherein we upgrade the firmware to the connected device from the app. This process takes about 30 odd minutes. During the execution of the scripts, we observe that the driver session closes abruptly causing the tests to fail. 

## Link to Appium logs

    [HTTP] --> GET /wd/hub/session/47f35815-7b00-4799-8412-d2a3b6c513a4/source
[HTTP] {}
[MJSONWP (47f35815)] Driver proxy active, passing request on via HTTP proxy

[debug] [WD Proxy] Matched '/wd/hub/session/47f35815-7b00-4799-8412-d2a3b6c513a4/source' to command name 'getPageSource'

[debug] [WD Proxy] Proxying [GET /wd/hub/session/47f35815-7b00-4799-8412-d2a3b6c513a4/source] to [GET http://localhost:8205/wd/hub/session/9218e5e7-077b-4a4f-a220-d39b12fae01f/source] with body: {}

[HTTP] --> GET /wd/hub/session/47f35815-7b00-4799-8412-d2a3b6c513a4/element/d7677d47-8d07-44e3-8cde-0e4385292d0a/location
[HTTP] {}
[MJSONWP (47f35815)] Driver proxy active, passing request on via HTTP proxy

[debug] [WD Proxy] Got response with status 200: "{\"sessionId\":\"9218e5e7-077b-4a4f-a220-d39b12fae01f\",\"status\":0,\"value\":\"<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>\\r\\n<hierarchy index=\\\"0\\\" class=\\\"hierarchy\\\" rotation=\\\"0\\\" width=\\\"1080\\\" height=\\\"1794\\\">\\r\\n  <android.widget.FrameLayout index=\\\"0\\\" package=\\\"com.test.control\\\" class=\\\"android.widget.FrameLayout\\\" text=\\\"\\\" checkable=\\\"false\\\" checked=\\\"false\\\" clickable=\\\"false\\\" enabled=\\\"true\\\" focusable=\\\"false\\\" focused=\\\"false\\\" long-clickable=\\\"false\\\" password=\\\"false\\\" scrollable=\\\"false\\\" selected=\\\"false\\\" bounds=\\\"[0,0][1080,1794]\\\" displayed=\\\"true\\\">\\r\\n    <android.widget.LinearLayout index=\\\"0\\\" package=\\\"com.test.control\\\" class=\\\"android.widget.LinearLayout\\\" text=\\\"\\\" checkable=\\\"false\\\" checked=\\\"false\\\" clickable=\\\"false\\\" enabled=\\\"true\\\" focusable=\\\"false\\\" focused=\\\"false\\\" long-clickable=\\\"false\\\" password=\\\"f...

[WD Proxy] Replacing sessionId 9218e5e7-077b-4a4f-a220-d39b12fae01f with 47f35815-7b00-4799-8412-d2a3b6c513a4

[HTTP] <-- GET /wd/hub/session/47f35815-7b00-4799-8412-d2a3b6c513a4/source 200 274 ms - 11489
[HTTP] 
[debug] [WD Proxy] Matched '/wd/hub/session/47f35815-7b00-4799-8412-d2a3b6c513a4/element/d7677d47-8d07-44e3-8cde-0e4385292d0a/location' to command name 'getLocation'
[debug] [WD Proxy] Proxying [GET /wd/hub/session/47f35815-7b00-4799-8412-d2a3b6c513a4/element/d7677d47-8d07-44e3-8cde-0e4385292d0a/location] to [GET http://localhost:8205/wd/hub/session/9218e5e7-077b-4a4f-a220-d39b12fae01f/element/d7677d47-8d07-44e3-8cde-0e4385292d0a/location] with body: {}

Killing driver...
 > CALL quit() 
 > DELETE /session/:sessionID 
[HTTP] --> DELETE /wd/hub/session/47f35815-7b00-4799-8412-d2a3b6c513a4

[HTTP] {}

[debug] [MJSONWP (47f35815)] Calling AppiumDriver.deleteSession() with args: ["47f35815-7b00-4799-8412-d2a3b6c513a4"]

[debug] [BaseDriver] Event 'quitSessionRequested' logged at 1552469836596 (15:07:16 GMT+0530 (IST))

[Appium] Removing session 47f35815-7b00-4799-8412-d2a3b6c513a4 from our master session list
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[debug] [WD Proxy] Matched '/' to command name 'deleteSession'
[debug] [WD Proxy] Proxying [DELETE /] to [DELETE http://localhost:8205/wd/hub/session/9218e5e7-077b-4a4f-a220-d39b12fae01f] with no body
[debug] [WD Proxy] Got response with status 200: "{\"sessionId\":\"9218e5e7-077b-4a4f-a220-d39b12fae01f\",\"status\":0,\"value\":{\"x\":53,\"y\":1070}}"
[WD Proxy] Replacing sessionId 9218e5e7-077b-4a4f-a220-d39b12fae01f with 47f35815-7b00-4799-8412-d2a3b6c513a4
[HTTP] <-- GET /wd/hub/session/47f35815-7b00-4799-8412-d2a3b6c513a4/element/d7677d47-8d07-44e3-8cde-0e4385292d0a/location 200 328 ms - 89
[HTTP] 
[debug] [WD Proxy] Got response with status 200: "{\"sessionId\":\"9218e5e7-077b-4a4f-a220-d39b12fae01f\",\"status\":0,\"value\":\"Session deleted\"}"
[debug] [ADB] Running '/Users/testmac/Library/Android/sdk/platform-tools/adb -P 5037 -s FA6AJ0301518 shell am force-stop com.test.control'

 > RESPONSE element.getLocation() {"x":53,"y":1070}
 > CALL waitForElementByXPath("//*[contains(translate(@content-desc,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz'),'installation in progress') or contains(translate(@resource-id,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz'),'installation in progress') or contains(translate(@text,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz'),'installation in progress')]",1000) 
 > CALL elements("xpath","//*[contains(translate(@content-desc,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz'),'installation in progress') or contains(translate(@resource-id,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz'),'installation in progress') or contains(translate(@text,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz'),'installation in progress')]") 
 > POST /session/:sessionID/elements {"using":"xpath","value":"//*[contains(translate(@content-desc,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz'),'installation in progress') or contains(translate(@resource-id,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz'),'installation in progress') or contains(translate(@text,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz'),'installation in progress')]"}
[HTTP] --> POST /wd/hub/session/47f35815-7b00-4799-8412-d2a3b6c513a4/elements

[HTTP] {"using":"xpath","value":"//*[contains(translate(@content-desc,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz'),'installation in progress') or contains(translate(@resource-id,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz'),'installation in progress') or contains(translate(@text,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz'),'installation in progress')]"}

[debug] [MJSONWP (47f35815)] Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started

[debug] [MJSONWP (47f35815)]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:298:15)

[debug] [MJSONWP (47f35815)]     at app.(anonymous function) (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:489:15)

[debug] [MJSONWP (47f35815)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)

[debug] [MJSONWP (47f35815)]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:137:13)

[debug] [MJSONWP (47f35815)]     at Route.dispatch (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:112:3)

[debug] [MJSONWP (47f35815)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)

[debug] [MJSONWP (47f35815)]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:281:22
[debug] [MJSONWP (47f35815)]     at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:354:14)
[debug] [MJSONWP (47f35815)]     at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:365:14)
[debug] [MJSONWP (47f35815)]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:410:3)
[debug] [MJSONWP (47f35815)]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[debug] [MJSONWP (47f35815)]     at logger (/usr/local/lib/node_modules/appium/node_modules/morgan/index.js:144:5)
[debug] [MJSONWP (47f35815)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [MJSONWP (47f35815)]     at trim_prefix (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
[debug] [MJSONWP (47f35815)]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:284:7
[debug] [MJSONWP (47f35815)]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
[debug] [MJSONWP (47f35815)]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[debug] [MJSONWP (47f35815)]     at /usr/local/lib/node_modules/appium/node_modules/body-parser/lib/read.js:130:5
[debug] [MJSONWP (47f35815)]     at invokeCallback (/usr/local/lib/node_modules/appium/node_modules/raw-body/index.js:224:16)
[debug] [MJSONWP (47f35815)]     at done (/usr/local/lib/node_modules/appium/node_modules/raw-body/index.js:213:7)
[debug] [MJSONWP (47f35815)]     at IncomingMessage.onEnd (/usr/local/lib/node_modules/appium/node_modules/raw-body/index.js:273:7)
[debug] [MJSONWP (47f35815)]     at emitNone (events.js:106:13)
[debug] [MJSONWP (47f35815)]     at IncomingMessage.emit (events.js:208:7)
[debug] [MJSONWP (47f35815)]     at endReadableNT (_stream_readable.js:1055:12)
[debug] [MJSONWP (47f35815)]     at _combinedTickCallback (internal/process/next_tick.js:138:11)
[debug] [MJSONWP (47f35815)]     at process._tickCallback (internal/process/next_tick.js:180:9)
[HTTP] <-- POST /wd/hub/session/47f35815-7b00-4799-8412-d2a3b6c513a4/elements 404 71 ms - 131
[HTTP] 

Refetch error: Error: [waitForElementByXPid,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz'),'installation in progress') or contains(translate(@text,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz'),'installation in progress')]",1000)] [elements("xpath","//*[contains(translate(@content-desc,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz'),'installation in progress') or contains(translate(@resource-id,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz'),'installation in progress') or contains(translate(@text,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz'),'installation in progress')]")] Error response status: 6,  Selenium error: A session is either terminated or not started
ERROR: TypeError: Cannot read property 'getSize' of null
[debug] [Logcat] Stopping logcat capture

[debug] [ADB] Removing forwarded port socket connection: 8205 

[debug] [ADB] Running '/Users/testmac/Library/Android/sdk/platform-tools/adb -P 5037 -s FA6AJ0301518 forward --remove tcp\:8205'

[UiAutomator2] Restoring hidden api policy to the device default configuration

[debug] [ADB] Running '/Users/testmac/Library/Android/sdk/platform-tools/adb -P 5037 -s FA6AJ0301518 shell settings delete global hidden_api_policy_pre_p_apps'

[debug] [ADB] Running '/Users/testmac/Library/Android/sdk/platform-tools/adb -P 5037 -s FA6AJ0301518 shell settings delete global hidden_api_policy_p_apps'

[debug] [BaseDriver] Event 'quitSessionFinished' logged at 1552469836997 (15:07:16 GMT+0530 (IST))

[debug] [MJSONWP (47f35815)] Received response: null

[debug] [MJSONWP (47f35815)] But deleting session, so not returning

[debug] [MJSONWP (47f35815)] Responding to client with driver.deleteSession() result: null

Ending your web drivage..

 > RESPONSE quit() 
Driver is dead!
Quit driver!

Stopping server...
Shut down!!!
[HTTP] <-- DELETE /wd/hub/session/47f35815-7b00-4799-8412-d2a3b6c513a4 200 403 ms - 76
[HTTP] 

About to exit with code: exit
Appium terminated due signal: SIGKILL and code: nullath("//*[contains(translate(@content-desc,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz'),'installation in progress') or contains(translate(@resource-
Exited from appium

  4 passing (15m)
  1 pending
  1 failing

       should navigate to update complete screen with progress bar at 100% on successful update of the firmware: CAP-3524,CAP-3521,CAP-3517:
     Error: Timeout of 750000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a

@mykola-mokhnach , can you please look into the issue. I don't see this problem on IOS.

**Comment by mykola-mokhnach** [comment]
This is expected if one tries to reuse a session after it has been already deleted. 

Quit the session before doing the upgrade and start a new one after it is finished

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
