### ISSUE TITLE
SIGINT & SIGTERM does not close Appium when iproxy & XCUITest still active

### ISSUE THREAD

**Issue by mibawo** [appium/appium#12297]
## The problem

Appium does not close on SIGINT or SIGTERM when children processes iproxy and xcodebuild are still running.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.11.1 (npm install -g)
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: MacOS Mojave 10.14.2 (18C54)
* Node.js version (unless using Appium.app|exe): v10.15.0
* Npm or Yarn package manager: npm 6.9.0
* Mobile platform/version under test: iOS 11.2.2
* Real device or emulator/simulator: iPhone 6 real device
* Appium CLI or Appium.app|exe: appium --port 4723 --log-level debug:debug --relaxed-security --log /Users/mibawo/appium.log

## Details

I am launching Appium as part of a Mocha test using `let appium = spawn('appium', [], {options})`. Appium is installed using `npm install -g appium`. The test connects to a real iOS device and one of the `after()` steps close Appium by sending `appium.kill('SIGINT')`. I expected appium to close after a few seconds but the appium node process remains in activity monitor. In the logs I see that the SIGINT (or SIGTERM) is received correctly. If I list children of Appium node process I see these child processes: iproxy, xcodebuild. I think that if Appium receives SIGINT or SIGTERM, it should be able to quit regardless if there are devices connected.

## Link to Appium logs

My setup runs with iOS capability `showIOSLog: true` but I have trimmed [iOSLog] for brevity. [Link](https://gist.github.com/mibawo/c2b86f5e6f54fcae56106fd79ea355b9.js).
This is the tail of the logs wiht my comments where I killed iproxy manually using activity monitor.
```
2019-03-13 14:45:38:048 [BaseDriver] Event 'quitSessionFinished' logged at 1552488338048 (14:45:38 GMT+0000 (Greenwich Mean Time))
2019-03-13 14:45:38:048 [W3C (eb2af09c)] Received response: null
2019-03-13 14:45:38:048 [W3C (eb2af09c)] But deleting session, so not returning
2019-03-13 14:45:38:049 [W3C (eb2af09c)] Responding to client with driver.deleteSession() result: null
2019-03-13 14:45:38:049 [HTTP] <-- DELETE /wd/hub/session/eb2af09c-37fa-4f60-b706-3c0a4a367f80 200 374 ms - 14
2019-03-13 14:45:38:049 [HTTP] 
2019-03-13 14:45:38:050 [XCUITest] Connection to WDA timed out
2019-03-13 14:45:39:069 [Appium] Received SIGINT - shutting down
2019-03-13 14:45:50:108 [Appium] Received SIGTERM - shutting down
2019-03-13 14:53:30:293 [XCUITest] iproxy exited with code 'null'.     <<<<<<<<<< This is where I terminated iproxy manually >>>>>>>>>>
```

## Code To Reproduce Issue [ Good To Have ]
Here is the code that launches the Appium server:
```
const {spawn} = require('child_process');
const async = require('async');
let closing = false;
let appiumServer = null;

   function internalStartAppium(options, done) {
        const cwd = options.appiumPath;
        const env = options.environment;
        const port = options.port || 4723;
        const logLevel = options.logLevel || 'debug:debug';
        appiumServer = spawn('appium', [
            '--port', 4723,
            '--log-level', logLevel,
            '--relaxed-security',
            '--log', '/Users/mibawo/appium.log'
        ], {cwd, env, stdio: 'inherit'});
        appiumServer.on('close', (code) => {
            if (code !== 0 && !closing) {
                console.log(`Appium exited with code ${code}`);
            } else {
                console.log(`Appium exited with code ${code}`);
            }
        });
        done();
    }
```
Here is the code that **should** close Appium:
```
   function internalStopAppium(options, done) {
        closing = true;
        if (appiumServer && !appiumServer.killed) {
            appiumServer.kill('SIGINT');  // Want to kill the server gracefully
            let timeout = 1000;
            let attempts = 10;
            let attempt = 0;
            let closed = false;
            appiumServer.on('close', () => { closed = true; appiumServer = null; });
            async.doWhilst(
                (next) => {
                    setTimeout(() => { next(); }, timeout);
                }, () => {
                    return !closed && (attempt++ < attempts);
                },
                () => {
                    if (appiumServer !== null) {
                        appiumServer.kill('SIGTERM');
                        done();
                    } }
            );
        } else {
            done();
        }
   }
```

**Comment by imurchie** [comment]
Appium will wait for resources on the first SIGINT/SIGTERM. Subsequent signals will cause termination. So just do the `kill` call twice.

**Comment by mibawo** [comment]
Thanks. I tried sending multiple SIGINT's and Appium does close but does not clean up the spawned child processes mentioned (iproxy, xcodebuild). I guess the issue is then that port forwarding is left over after `remote.deleteSession` has been called or `appium.kill('SIGINT')` has been sent. I could use a library to kill the process tree but I think this is something Appium should handle internally. ADB port forwarding may also be left over but I have not tested this.

**Comment by mykola-mokhnach** [comment]
These two processes are deliberately detached from the main Appium process. The reason for this is that xcodebuild must be running in order to make WebDriverAgent caching possible.
