### ISSUE TITLE
Elements are not identifying on device farm with google pixel device, on local it is working fine 

### ISSUE THREAD

**Issue by anilkn72** [appium/appium#12292]
UIAutomator2 in device farm, however in local it is working fine.
The device used in device farm is google pixel, local is redmi note 4.
While installing app itself not identifying the elements, like SKIP button, Allow buttons

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: windows 10
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: 6.0.1
* Real device or emulator/simulator: Real device on device farm(AWS)
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
https://gist.github.com/anilkn72/06f393d1fdcb2f8e527037d1649a0e8d
please find the log file of appium server on device farm, elements are not identifying using Uiautomator2.Please help me in resolving the issue.

**Comment by mykola-mokhnach** [comment]
Please upgrade the server to the most recent version. We do not provide patches to older Appium versions.

**Comment by anilkn72** [comment]
Thank you for the response.
I have upgraded the appium version to 1.11.1 and checked its not identifying the elements in local system now.
I have downgraded the version to 1.9.1 which also gives the same issue as of the version 1.11.1
it's log file is given below. 
https://gist.github.com/anilkn72/6c712eb48ff28d9b2655ec86697f2977.

**Comment by mykola-mokhnach** [comment]
> Locator Strategy 'css selector' is not supported

this is the problem with your client. Check https://github.com/appium/appium/search?q=%22Locator+Strategy+%27css+selector%27+is+not+supported%22&type=Issues

closed as not an issue
