### ISSUE TITLE
Problem on Android 5 after attempt to get application up by startActivity() or restart driver with noReset = true

### ISSUE THREAD

**Issue by lubshilk** [appium/appium#12295]
## The problem

On all our Android devices in the case the application under test is closed from some reason automation tries to get it up firstly using driver.startActivity() and if not succeeded by restarting driver with noReset=true

All devices with Android version 6 and up have no problem with it: usually application is back by driver.startActivity() and all elements of the application are visible and caught by appium

On a device with Android 5.0.1 no problem reported in appium log by running startActivity or driver re-starting, but no element found afterwards - NoSuchElementError returned
Catching screenshot works and shows application up as expected
We tried few devices - the same result for Android 5.0.1

## Environment

* Appium version: spotted the problem with Appium 1.9, now use Appium 1.11.1 - the same problem
* Last Appium version that did not exhibit the issue (if applicable): none
* Desktop OS/version used to run Appium: MAC/Windows
* Mobile platform/version under test: Android 5.0.1
* Real device or emulator/simulator: real device

## Link to Appium logs
StartActivity() on Android5 
https://gist.github.com/lubshilk/11c6d15e9d0afa2825ccaf7e9a6c9e1e#file-appiumstartactivityandroid5-log

StartActivity() on Android8 - the same code, no problem reported
https://gist.github.com/lubshilk/fe9c000750ce1f349755b9927c220439#file-appiumstartactivityandroid8-log

Driver re-start on Android 5 with noReset=true
https://gist.github.com/lubshilk/30fae290a3255b37d2c4a569121a4add#file-appiumrestartdriverandroid5-log

**Comment by mykola-mokhnach** [comment]
UiAutomator2 is supported, although is reported as not very stable and reliable on Android5. Try another automation backend or report the issue to Google. I don't think there's a lot to do there on Appium side

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
