### ISSUE TITLE
After update to v28 of Android support library, TextInputLayout’s and their associated labels no longer appear in the Appium inspector due to the layout being flattened.

### ISSUE THREAD

**Issue by seancoxprosper** [appium/appium#12305]
## The problem

After update to v28 of Android support library, TextInputLayout’s and their associated labels no longer appear in the Appium inspector due to the layout being flattened.

## Environment

* Appium version (or git revision) that exhibits the issue: Version 1.11.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: MacOS 10.14.1. Also reported with Windows 10. 
* Node.js version (unless using Appium.app|exe): Using Appium.app
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: Android Pixel 2XL, API V28, Android 9.0 
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Appium.app

## Details

Our application makes liberal use of TextInputLayouts and EditText. The TextInputLayout contains the label for the field being input, and the EditText is the input field. In version 27 of the Android support library this was how we did the majority of our lookups (ignore the unique id for this example, as this is the only instance of that occurring in the entire app).  (See Screenshot Android Support Library v27.1.1)
![android support library v27 1 1](https://user-images.githubusercontent.com/19481153/54389981-9ad48580-465e-11e9-8b09-5e42de35b2aa.png)

In v28 of the Android support library, the same layout changes and turns the TextInputLayout into a LinearLayout object, which no longer contains the text label. The text label instead moves into the EditText, but it’s removed after an input occurs. (See Screenshot Android Support Library v28). 
![android support library v28](https://user-images.githubusercontent.com/19481153/54389997-a58f1a80-465e-11e9-986f-ae376956fd5e.png)

As a note, the two screenshots are identical code with only the library being changed between the two.

The library under question is here: https://developer.android.com/topic/libraries/support-library/revisions. The issue also occurs with the move over to AndroidX. https://developer.android.com/jetpack/androidx
As far as I’m aware, this is an intended change from the Android team, so I have no reason to suspect the layout updates is a bug on their end.

What my bug is that without those labels being visible in Appium inspector, most of our applications functionality is untestable. Most if not all fields have no unique id since they’re all based off the same base object so we were utilizing locators that found the correct TextInputLayout  via its set Text. (See Screenshot Non-unique v28). This is due to our application reading in what fields are available the user from server side and then displaying only those fields.
![Non-unique V28](https://user-images.githubusercontent.com/19481153/54390004-ab84fb80-465e-11e9-8fae-fc262438d9d5.png)

## Link to Appium logs

There are no Appium logs here since this is an inspector side issue.

## Code To Reproduce Issue

If there’s anything else I can add here please let me know. I was unable to get the sample apps running in inspector.

**Comment by mykola-mokhnach** [comment]
I don't think there's anything to do on Appium side, since it just displays what UIA2 returns to it.

Try if Espresso driver works better for you
