### ISSUE TITLE
can't find a corresponding relation between adb version and appium version when do web test on chrome 

### ISSUE THREAD

**Issue by ZhaoMoMo** [appium/appium#12302]
## The problem
Appium desktop 1.11.0 + Android 8.0.0 + fastboot_adb(1.0.39 or 1.0.40) + Chrome70.0.3538.80 and suitable chromedriver. there will be an error as below:
 Encountered internal error running command: Error: Error getting device platform version. Original error: Error executing adbExec. Original error: 'Command ''C:\\Program Files (x86)\\Android\\android-sdk\\platform-tools\\adb.exe' -P 5037 -s HQLDU18904000025 shell getprop ro.build.version.release' exited with code 3221226356'; Stderr: ''; Code: '3221226356'

If I change fastboot_adb to version 1.0.36, above error will be disappeared, but there will be a new error:
 Error: Failed to start Chromedriver session: An unknown server-side error occurred while processing the command. Original error: unknown error: Failed to forward ports to device HQLDU18904000025. No port chosen: . Perhaps your adb version is out of date. ChromeDriver 2.39 and newer require adb version 1.0.38 or newer.

## Environment

* Appium version (or git revision) that exhibits the issue: 
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:  
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
We neither support nor test fastboot_adb. Feel free to commit a PR if you want it to be supported

**Comment by KazuCocoa** [comment]
The chrome driver error was chrome driver side's requirement
https://chromium.googlesource.com/chromium/src/+/master/chrome/test/chromedriver/chrome/adb_impl.cc#148

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by ZhaoMoMo** [comment]
Sorry to reply so late. As I described in the first graph, there is an error as below, is that because of the Appium try to get the platform version by adb, but Appium desktop 1.11.0 can not work with adb 1.0.38 and later?
So I think due to the version relationship between chrome and adb, and version relationship between Appiium desk and adb, we can't find a way to test chrome by Appium desk 1.11.0.

The error as below:
“Encountered internal error running command: Error: Error getting device platform version. Original error: Error executing adbExec. Original error: 'Command ''C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe' -P 5037 -s HQLDU18904000025 shell getprop ro.build.version.release' exited with code 3221226356'; Stderr: ''; Code: '3221226356'”

**Comment by KazuCocoa** [comment]
Did you configure `chromedriver*` capabilities?
If you can find proper chrome driver working on your device in http://chromedriver.chromium.org/downloads , you can change the version via `chromedriver*` capabilities in Appium.
http://appium.io/docs/en/writing-running-appium/caps/

**Comment by ZhaoMoMo** [comment]
Thank you for your reply.
The chrome driver version is proper(Chrome V70, chromedriver 2.44 or 2.45), and the configuration as below:
{
  "platformName": "Android",
  "platformVersion": "8.0.0",
  "deviceName": "HQLDU189040......",
  "browserName": "Chrome",
  "chromedriverUseSystemExecutable": false,
  "chromedriverExecutableDir": "C:\\Program Files (x86)\\Python37-32"
}
the error is still existing.

**Comment by KazuCocoa** [comment]
ah...
According to https://chromium.googlesource.com/chromium/src/+/master/chrome/test/chromedriver/chrome/adb_impl.cc#148 , Chrome Driver 2.39+ requires adb 1.0.38 or newer.

Appium depends on adb provided by Google. If the error, `3221226356`,  is because of the official adb command error by `shell getprop ro.build.version.release`, currently we have no solution to fix the issue, unfortunately. (If it happens only on fastboot_adb, it probably can fix by using vanilla adb by Google tho). Appium refers to the version to handle logic properly.

Appium provides customising chrome driver by `chromedriver*` capabilities as the above. So, you can fix the version issue if it can solve changing chrome driver versions.

**Comment by ZhaoMoMo** [comment]
Thank you for your reply.
Because of the Chrome version, I can't change chrome driver to low versions.
I will try vanilla adb, and share the result with you.

And if the vanilla adb also not fixed the  shell "getprop ro.build.version.release" issue, can we make a solution that because of the adb issue, we can't use Appium to test Chrome V70 and later version?

**Comment by ZhaoMoMo** [comment]
Thank you for your reply.
 Because of the Chrome version, I can't change chrome driver to low versions.
 I will try vanilla adb, and share the result with you.

And if the vanilla adb also not fixed the shell "getprop ro.build.version.release" issue, can we make a conclusion that because of the adb issue, we can't use Appium to test Chrome V70 and later version?

**Comment by ZhaoMoMo** [comment]
Hi，KazuCocoa,
I can't find vanilla adb, do you know how to get it?
And, I have no sense about the different of fastboot_adb and vanilla adb, could you please give me some introduction?
Thank you.

**Comment by KazuCocoa** [comment]
_vanilla_ means adb you can get when you download https://developer.android.com/studio and its sdk manager.

I'm not familiar with fastboot_adb, but is it maybe like https://androidfilehost.com/?fid=24591000424946469 ?

If you use the official one and `shell getprop ro.build.version.release` raises the issue, we probably cannot test with chrome so far. I haven't met such error, so it perhaps happens only particular devices.
(I ran `shell getprop ro.build.version.release` for Android 8.0 real/emulator devices before. It is not OS version issue, I assume)

**Comment by ZhaoMoMo** [comment]
Hi, if I only install “Android SDK- installer_r24.4.1-windows” on my computer, is that a vanilla adb with it?
I tried on this, it is also can not support.

**Comment by KazuCocoa** [comment]
Maybe yes, if you download dev tools via the Android Studio.

> it is also can not support

Do you mean the `shell getprop ro.build.version.release` raise the same error?

What the output of `adb shell getprop`?
Please run the command directly. I would like to see what data the output has.

If they raise errors, you should report it to Google, too, I think.

**Comment by ZhaoMoMo** [comment]
Hi, I tried again on adb1.0.40 , and the result seems different with you told me.
I can get android platform version by command "adb shell getprop ro.build.version.release"
or "adb -P 5037 -s HQLDU18904000025 shell getprop ro.build.version.release"

but,when I use Appium to start a session, I still get the result：
"Encountered internal error running command: Error: Error getting device platform version. Original error: Error executing adbExec. Original error: 'Command ''C:\\Program Files (x86)\\Android\\android-sdk\\platform-tools\\adb.exe' -P 5037 -s HQLDU18904000025 shell getprop ro.build.version.release' exited with code 3221226356'; Stderr: ''; Code: '3221226356'".

Isn't it a Appium issue?

In additional, when I execute "adb shell getprop", I can get: 
[audio.high.resolution.enable]: [true]
[bastet.service.enable]: [true]
[bg_fsck.pgid]: [344]
[bt.dpbap.enable]: [1]
[bt.max.hfpclient.connections]: [2]
[build.hisi_perf_opt]: [true]
......

**Comment by KazuCocoa** [comment]
Could you share your node version with us?

I could see node related issues about the error code to handle their process on windows env.

**Comment by ZhaoMoMo** [comment]
Hi, the node.js version is v10.15.3. :)

**Comment by SergeySerj** [comment]
I'm getting the same error:

`[W3C] Encountered internal error running command: Error: Error getting device platform version. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\SergeyPolschak\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.release' exited with code 3221226356'; Stderr: ''; Code: '3221226356'
[W3C]     at ADB. (C:\Users\SergeyPolschak\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\adb-commands.js:115:11)
[W3C]     at Generator.throw ()
[W3C]     at asyncGeneratorStep (C:\Users\SergeyPolschak\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
[W3C]     at _throw (C:\Users\SergeyPolschak\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\@babel\runtime\helpers\asyncToGenerator.js:29:9)
[W3C]     at run (C:\Users\SergeyPolschak\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\core-js\modules\es6.promise.js:75:22)
[W3C]     at C:\Users\SergeyPolschak\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\core-js\modules\es6.promise.js:92:30
[W3C]     at flush (C:\Users\SergeyPolschak\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\core-js\modules\_microtask.js:18:9)
[W3C]     at process._tickCallback (internal/process/next_tick.js:61:11)`

Appium desktop server is 1.13.0
nodejs: v10.16.0
adb: 1.0.41

Running `adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.release` returns valid result without errors for several (Android 8.1 and 9) emulators.

**Comment by chumincc** [comment]
hey, have you solved your issue yet? I am still struggling in this issue.

**Comment by KazuCocoa** [comment]
Code: '3221226356' issue?
According to https://github.com/appium/appium/issues/12736#issuecomment-502093453, the latest revision, 29.0.1, works on Windows.
