### ISSUE TITLE
Provisioning profile "iOS Team Provisioning Profile: xxxx" doesn't match the entitlements file's value for the get-task-allow entitlement

### ISSUE THREAD

**Issue by MarkSunPWC** [appium/appium#12301]
## The problem

When following https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md to do appium on IOS real devices, encounter error when xcode auto signing says "Provisioning profile "iOS Team Provisioning Profile: com.whatever.WebDriverAgentRunner" doesn't match the entitlements file's value for the get-task-allow entitlement. (in target 'WebDriverAgentRunner')"

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Please use Appium forum for questions.

**Comment by MarkSunPWC** [comment]
@mykola-mokhnach Sure, so the Appium forum URL will be...

**Comment by mykola-mokhnach** [comment]
discuss.appium.io 
It's present in the issue template
