### ISSUE TITLE
Change from Chrome Browser to NativeApp android.

### ISSUE THREAD

**Issue by pgtoopx** [appium/appium#12317]
## The problem

I'm testing a flow in my app, where it starts from the chrome, then through an intent the application opens to continue with the process, and then return to the browser to finish the process. The problem is that I start the driver with web capabilities, to start the flow with a driver.get (pageurl), but when my application opens I can not continue with the flow since the driver is configured with web capabilities. I tried to start another driver, but it reinitializes my application, and the expected flow is lost. hope you can help me

**Comment by mykola-mokhnach** [comment]
Please fill out the issue reporting form properly and provide the logs. Nothing can be done without this information

**Comment by mykola-mokhnach** [comment]
The idea with two driver won't work for a single device. You need to have one and restart it with different capabilities when the browser need to be started (also having `noReset` enabled makes sense for such scenario).
