### ISSUE TITLE
Android 10 support (formerly Android Q support)

### ISSUE THREAD

**Issue by mykola-mokhnach** [appium/appium#12311]
This issue includes the necessary changes in Appium to add Android Q support.

**Comment by mykola-mokhnach** [comment]
Appium is using below command to check appWaitActivity in Android.
adb shell dumpsys window windows

But from Android “Q” - Now it is changed to below command.
New command: adb shell dumpsys window displays
Refer to my ticket: https://issuetracker.google.com/issues/128560160

If we use appWaitActivity in capabilities then it is not creating session as the adb shell dumpsys window windows command is not working in “Q”.

we can create the session without appWaitActivity as well to over come this issue.
Please fix this issue in next release.

**Comment by KazuCocoa** [comment]
Rouphly ran ruby client tests on Android Q emulator (not fully yet).
I haven't investigated deeper, but below code failed in UIA2
(haven't tried espresso)

```ruby
      def test_clipbord
        input = 'happy testing'

        @driver.set_clipboard(content: input, label: 'Note')

        assert_equal input, @driver.get_clipboard # it returned "" (empty string)
      end
```

```
get_clipboard:              [:post, 'session/:session_id/appium/device/get_clipboard'],
set_clipboard:              [:post, 'session/:session_id/appium/device/set_clipboard'],
```

`app_state` too. The above `windows` affected, maybe.

```
app_state:                  [:post, 'session/:session_id/appium/device/app_state'],
```

**Comment by dpgraham** [comment]
I'm running tests now and will add things I find here.

**Comment by dpgraham** [comment]
This shows up when attempting to run tests.

![Screen Shot 2019-03-15 at 10 51 19 AM](https://user-images.githubusercontent.com/852574/54451599-6faa6e80-4710-11e9-8917-95126af79e79.png)

**Comment by dpgraham** [comment]
@KazuCocoa I think they said something about putting limitations on apps accessing the clipboard in Android Q. Could be related.

**Comment by sridharreddysuram123** [comment]
Please refer to this ticket which I have logged already regarding app permissions. 
https://discuss.appium.io/t/android-q-permission-error-on-launching-appium-unlock-app/25522

We do have a solution to over come this kind of issues. We can use below commands. 

**Install apk along with all permissions as accepted - It will not ask the permissions again:** 
Command: **adb install -g -r <apkfilepath>**
Example: 
- _adb install -g -r abc.apk_


**If the app is already installed, then run below command as per the app permissions.** 
**_adb shell pm grant <packageId> <permissionName>_**
Example: 

- adb shell pm grant com.abc.test android.permission.READ_SMS
- adb shell pm grant com.abc.test android.permission.READ_PHONE_STATE
- adb shell pm grant com.abc.test android.permission.READ_CONTACTS
- adb shell pm grant com.abc.test android.permission.READ_CALL_LOG
- adb shell pm grant com.abc.test android.permission.READ_PHONE_STATE
-

**Comment by KazuCocoa** [comment]
https://www.xda-developers.com/android-q-blocks-background-clipboard-access/ > clipboard manager

**Comment by mykola-mokhnach** [comment]
Perhaps, it will be necessary to move all or some clipboard APIs into Appium Settings, since it's already running in foreground

**Comment by KazuCocoa** [comment]
UIA2 and Espresso worked except for `dumpsys windows` and get clipboard related issue with ruby_lib_core's test suite on Android Q emulator. Demo app was https://github.com/appium/android-apidemos/pull/34 based one. (from clean env)

--

note:
`zipalign` failed in both `29.0.0-rc1` and `28.0.3` with the generated APK by `npm run build` in the apidemos repo with `build-tools 29.0.0-rc1` sdk. When I build it with `build-tools 28.0.3`, `zipalign` worked in both `29.0.0-rc1` and `28.0.3`.

**Comment by KazuCocoa** [comment]
A link about startActivity. maybe, it does not affect us tho.

- https://www.reddit.com/r/androiddev/comments/b0t8np/android_q_to_prevent_startactivity_in_service/
- https://developer.android.com/preview/privacy/background-activity-starts

**Comment by jlipps** [comment]
Ran into the wait for activity issue as well. Looks like we could potentially update the list of regexes to include `mObscuringWindow`?

**Comment by KazuCocoa** [comment]
https://android-developers.googleblog.com/2019/06/android-q-beta-4-and-final-apis.html
RC is coming

**Comment by KazuCocoa** [comment]
current known issue:

- https://github.com/appium/appium/issues/12754#issuecomment-501422323
    - adb forward does not work on Android emulator Q beta 3+
    - https://issuetracker.google.com/issues/132325318

**Comment by yunuskazan81** [comment]
i' m new to use appium. i was using Q. and trying to figure out whats wrong with my system and configuration. i coulnt find it even though searching abouth 2 weeks. because the problem is here, where are you guys. i was looking for you guys. anyway previous version oreo and api level 27 is worked with uiautomator2. thank you so much guys, you let me to get rid of this frustrating big headache.. that's new issue, so that's why i couldnt find out. please keep going us to update.... have a wonderful one. :)

**Comment by KazuCocoa** [comment]
beta 6 has been published.
https://android-developers.googleblog.com/2019/08/final-beta-update-official-android-q.html

https://developer.android.com/preview/overview#timeline

**Comment by KazuCocoa** [comment]
https://android-developers.googleblog.com/2019/09/welcoming-android-10.html

**Comment by mykola-mokhnach** [comment]
https://developer.android.com/guide/topics/media/playback-capture

We that we could finally allow audio recording for Appium tests

**Comment by mykola-mokhnach** [comment]
Closed as fixed

**Comment by ganjarpanji** [comment]
> Rouphly ran ruby client tests on Android Q emulator (not fully yet).
> I haven't investigated deeper, but below code failed in UIA2
> (haven't tried espresso)
> 
> ```ruby
>       def test_clipbord
>         input = 'happy testing'
> 
>         @driver.set_clipboard(content: input, label: 'Note') # worked :ok:
> 
>         assert_equal input, @driver.get_clipboard # it returned "" (empty string)
>       end
> ```
> 
> ```
> get_clipboard:              [:post, 'session/:session_id/appium/device/get_clipboard'],
> ~~set_clipboard:              [:post, 'session/:session_id/appium/device/set_clipboard'],~~
> ```
> 
> `app_state` too. The above `windows` affected, maybe.
> 
> ```
> app_state:                  [:post, 'session/:session_id/appium/device/app_state'],
> ```

i got the same result, the clipboard resulted as empty string "" , do we have workaround for this?

**Comment by KazuCocoa** [comment]
I took a look again. Maybe no workaround for now.

Perhaps, we can add the feature for Android 10+ on Appium IME https://github.com/appium/io.appium.settings/search?q=ime&unscoped_q=ime (I haven't checked yet).

Created a new issue => https://github.com/appium/appium/issues/13466
