### ISSUE TITLE
Issue with taking screenshots using AppiumDriver

### ISSUE THREAD

**Issue by jsa34** [appium/appium#12312]
## The problem

Taking screenshots using the following method results in appium hanging:
            byte[] screenShot = ((TakesScreenshot) DriverManager.getDriver()).getScreenshotAs(OutputType.BYTES);
            Allure.getLifecycle().addAttachment(LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd-MMM-yy_hh:mm:ss")), "image/png", "png", screenShot);

DriverManger.getDriver() returns an instance of AppiumDriver WebElement>.

In the appium logs I get, see Gist provided below.

## Environment

* Appium version (or git revision) that exhibits the issue: **1.11.1**
* Desktop OS/version used to run Appium: **MacOS (Desktop)**
* Node.js version (unless using Appium.app|exe): **latest**
* Npm or Yarn package manager: **latest npm**
* Mobile platform/version under test: **Android 8.1**
* Real device or emulator/simulator: **simulator**
* Appium CLI or Appium.app|exe: **Appium.app**

## Link to Appium logs

`https://gist.github.com/jsa34/8b0121be0d066c38e027363f55a319cc`

**Comment by mykola-mokhnach** [comment]
this is the error message from chrome, so the bug should be reported there. You could also try the nativeWebScreneshot capability as a workaround

Closed as third party issue
