### ISSUE TITLE
Relative path is causing problems when using the installAppOnDevice() method

### ISSUE THREAD

**Issue by gkvappium** [appium/appium#12318]
## The problem

Relative path is causing problems when using the installAppOnDevice() method. When relative path is given the desired capabilities, during the startup flow, app gets installed without any problem. But when this same relative path is used when we use the method, installAppOnDevice(), it deletes the apk from the path automatically. There is also a message saying that absolute path has to be used. I want to use a relative path so that it works on all the systems and not just for me.

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):1.9.1
* Desktop OS/version used to run Appium: MacOSX
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:Npm
* Mobile platform/version under test:Android 8.0
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: CLI

## Code To Reproduce Issue [ Good To Have ]

Have a method something like,
    async reinstallAppWithRelaunch() {
        await this._driver.driver.removeAppFromDevice('com.app.control');
        if (this._driver.isAndroid) {
            await this._driver.driver.installAppOnDevice('/e2e/Android_apk/control.apk');
        }
        else {
            await this._driver.driver.installAppOnDevice('e2e/IOS_ipa/control.ipa');
        }
        await this._driver.driver.launchApp();
        try {
            await this.acceptAlertDialog();
        } catch (error) {
            console.log("No app update alert message is displayed");
        }
    }

Desired cap has,
    "android25": {
        "platformName": "Android",
        "platformVersion": "8.0.0",
        "deviceName": "One Plus3",
        "autoGrantPermissions": true,
        "lt": 60000,
        "appPackage": "com.app.control",
        "newCommandTimeout": 720,
        "noReset": true,
        "noSign": true,
        "automationName": "uiautomator2",
        "fullReset": false,
        "app": "e2e/Android_apk/control.apk"
The thing is during the startup flow, app is picked up from the relative path and is also installed and launched successfully. When i call the method in the TC reinstallAppWithRelaunch(), it complains about relative path. The app is automatically deleted from the folder.

[ADB] com.control.control was successfully uninstalled
[debug] [MJSONWP (d0de95fd)] Responding to client with driver.removeApp() result: true

 > RESPONSE removeAppFromDevice("com.control.control") 
 > CALL installAppOnDevice("e2e/Android_apk/control.apk") 
 > POST /session/:sessionID/appium/device/install_app {"appPath":"e2e/Android_apk/control.apk"}
[HTTP] <-- POST /wd/hub/session/d0de95fd-1f10-46f8-8643-092efdee4763/appium/device/remove_app 200 934 ms - 76
[HTTP] 

[HTTP] --> POST /wd/hub/session/d0de95fd-1f10-46f8-8643-092efdee4763/appium/device/install_app

[HTTP] {"appPath":"e2e/Android_apk/control.apk"}

[debug] [MJSONWP (d0de95fd)] Calling AppiumDriver.installApp() with args: ["e2e/Android_apk/control.apk",null,null,null,"d0de95fd-1f10-46f8-8643-092efdee4763"]

[BaseDriver] Using local app 'e2e/Android_apk/control.apk'

[BaseDriver] The current application path 'e2e/Android_apk/control.apk' is not absolute and has been rewritten to '/Users/macuser/SmartControl/AutomationSuite/e2e/Android_apk/control.apk'. Consider using absolute paths rather than relative
[debug] [ADB] Device API level: 26
[debug] [ADB] Running '/Users/macuser/Library/Android/sdk/platform-tools/adb -P 5037 -s 85b1a8ae install -r /Users/macuser/SmartControl/AutomationSuite/e2e/Android_apk/control.apk'

[debug] [ADB] Install command stdout: Success

[debug] [MJSONWP (d0de95fd)] Responding to client with driver.installApp() result: null

[HTTP] <-- POST /wd/hub/session/d0de95fd-1f10-46f8-8643-092efdee4763/appium/device/install_app 200 7168 ms - 76
[HTTP] 

 > RESPONSE installAppOnDevice("e2e/Android_apk/control.apk") 
 > CALL launchApp() 
 > POST /session/:sessionID/appium/app/launch 
[HTTP] --> POST /wd/hub/session/d0de95fd-1f10-46f8-8643-092efdee4763/appium/app/launch

[HTTP] {}

[debug] [MJSONWP (d0de95fd)] Calling AppiumDriver.launchApp() with args: ["d0de95fd-1f10-46f8-8643-092efdee4763"]

[debug] [ADB] Getting install status for com.control.control
[debug] [ADB] Running '/Users/macuser/Library/Android/sdk/platform-tools/adb -P 5037 -s 85b1a8ae shell dumpsys package com.control.control'

[debug] [ADB] 'com.control.control' is installed

[debug] [ADB] Getting package info for 'com.control.control'
[debug] [ADB] Running '/Users/macuser/Library/Android/sdk/platform-tools/adb -P 5037 -s 85b1a8ae shell dumpsys package com.control.control'

[debug] [MJSONWP (d0de95fd)] Encountered internal error running command: Error: The file at path /Users/macuser/SmartControl/AutomationSuite/e2e/Android_apk/control.apk does not exist or is not accessible

[debug] [MJSONWP (d0de95fd)]     at ADB.apkUtilsMethods.getApkInfo (/usr/local/lib/node_modules/appium/node_modules/appium-adb/lib/tools/apk-utils.js:854:11)
[debug] [MJSONWP (d0de95fd)]     at <anonymous>

Note: The same method works fine for IOS. Relative path is picked up without any problem

@mykola-mokhnach ,Any way to use this with relative path? I am seeing this error only now. Earlier there was no complain about the relative path . It was working fine. Something has changed for sure.

**Comment by mykola-mokhnach** [comment]
Make sure you use the recent server version. Relative paths usage is still not recommended, since it prevents caching logic from working properly on the server side.

**Comment by gkvappium** [comment]
It's the latest version 1.11.1. I haven't seen the issue on older versions of appium. Not atleast on 1.8 and 1.9

**Comment by mykola-mokhnach** [comment]
Try to avoid launchApp usage. There are terminateApp/activateApp methods, which don't reinit the session.
