### ISSUE TITLE
[ANDROID] Appium fails when launching google photos 

### ISSUE THREAD

**Issue by Jiurong-Yang** [appium/appium#12310]
Appium seems to have an issue with the adb bridge when pulling the apk file of the application from the device when starting a driver session with application like google photos 

## Environment

* Appium version: 1.9.1
* Host machine: Ubuntu16.04

Here are the logs:
[debug] [UiAutomator2] Resetting IME to 'io.appium.android.ime/.UnicodeIME'
[debug] [ADB] Running '/opt/android/platform-tools/adb -P 5037 -s LGH870DSfdf2efbf shell ime set io.appium.android.ime/.UnicodeIME'
[debug] [ADB] Running '/opt/android/platform-tools/adb -P 5037 -s LGH870DSfdf2efbf shell am force-stop com.google.android.apps.photos'
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 10302 
[debug] [ADB] Running '/opt/android/platform-tools/adb -P 5037 -s LGH870DSfdf2efbf forward --remove tcp\:10302'
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1552615242202 (19:00:42 GMT-0700 (Pacific Daylight Time))
[debug] [W3C] Encountered internal error running command: Error: Error executing adbExec. **Original error: 'Command '/opt/android/platform-tools/adb -P 5037 -s LGH870DSfdf2efbf pull '/data/app/com.google.android.apps.photos-1/base.apk
[debug] [W3C] package:/data/app/com.google.android.apps.photos-1/split_config.en.apk
[debug] [W3C] package:/data/app/com.google.android.apps.photos-1/split_config.it.apk
[debug] [W3C] package:/data/app/com.google.android.apps.photos-1/split_config.xxxhdpi.apk' /tmp/com.google.android.apps.photos.apk' exited with code 1'; Stderr: ''; Code: '1'**
[debug] [W3C]     at ADB.execFunc$ (/usr/lib/node_modules/appium/node_modules/appium-adb/lib/tools/system-calls.js:327:13)
[debug] [W3C]     at tryCatch (/usr/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[debug] [W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[debug] [W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[debug] [W3C]     at GeneratorFunctionPrototype.invoke (/usr/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 18479 ms - 1975
[HTTP] 

It seems like that Appium is trying to pull multiple apks? And somehow the command didn't get generated properly to cause this crash. I've bold the log in question. 

The server is running fine with all the other apps we test with. Just the google photos is tripping it up somehow. I've also ran the adb commands on the command line against any of those apks and they ran fine. I think Appium is somehow jumbling the commands to create an syntax error. 

Also this behavior exists on multiple devices.

**Comment by KazuCocoa** [comment]
What about with the latest Appium version?
I assume the error is _getting string resources_ in session creation. The logic is handled in the newer one.

**Comment by Jiurong-Yang** [comment]
I'm not sure. We are currently running in a very strict environment. If I know which version fixed this I can make a proposal to bring us up to a newer version of Appium.

**Comment by KazuCocoa** [comment]
if https://github.com/appium/appium-android-driver/commit/156c6e4812488b59d91c395c1f62ec87bb2b6539 , over 1.10 has.

**Comment by Jiurong-Yang** [comment]
Yeah I just verified it. 1.10 fixes this problem. Thank you very much
