### ISSUE TITLE
Android Q sessions get stuck at "com.android.permissioncontroller"

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#12320]
When running a session on Android Q, if you attempt to run a session where the user hasn't granted permissions, it opens an apk called "com.android.permissioncontroller" that prompts the user and asks which permissions to allow.

![Screen Shot 2019-03-15 at 10 51 19 AM](https://user-images.githubusercontent.com/852574/54453192-10e6f400-4714-11e9-8955-05017e6d7118.png)

My recommendation is that we click the "Continue" button by default, to maintain compatibility. But we should have a capability that whitelists the permissions that should be accepted. This is probably a test case users are going to want.

Acceptance Criteria:
* [ ] Decide on how to handle this case
* [ ] Implement the selection of "Continue"
* [ ] Implement the new capability (if necessary)
* [ ] Test this in UiAutomator2 and Espresso

**Comment by mykola-mokhnach** [comment]
I would say this is rather a Feature

**Comment by dpgraham** [comment]
This blocks the AUT from opening.

**Comment by dpgraham** [comment]
And you can't interact with it, it logs this until a timeout:

```
dbug ADB Possible activities, to be checked: 'io.appium.android.apis.ApiDemos', 'io.appium.android.apis.io.appium.android.apis.ApiDemos'
dbug ADB Getting focused package and activity
dbug ADB Running '/Users/danielgraham/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys window windows'
dbug ADB Getting focused package and activity
dbug ADB Running '/Users/danielgraham/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys window windows'
dbug ADB Getting focused package and activity
dbug ADB Running '/Users/danielgraham/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys window windows'
dbug ADB Getting focused package and activity
dbug ADB Running '/Users/danielgraham/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys window windows'
dbug ADB Getting focused package and activity
dbug ADB Running '/Users/danielgraham/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys window windows'
dbug ADB Getting focused package and activity
dbug ADB Running '/Users/danielgraham/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys window windows'
dbug ADB Getting focused package and activity
dbug ADB Running '/Users/danielgraham/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys window windows'
dbug ADB Getting focused package and activity
dbug ADB Running '/Users/danielgraham/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys window windows'
dbug ADB Getting focused package and activity
```

**Comment by KazuCocoa** [comment]
link: https://github.com/appium/appium/issues/12311

**Comment by mykola-mokhnach** [comment]
We keep it as is for now

**Comment by eillouz** [comment]
so what is the best practice for that?
<img width="314" alt="image" src="https://user-images.githubusercontent.com/44848481/94864092-25005c80-0444-11eb-8bfa-ee855cfbce27.png">
