### ISSUE TITLE
Toggle WiFi on Android Q+ via UI

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#12327]
Logs: https://gist.github.com/dpgraham/13ceb58e3f377fb81687f0a45c29a171

`adb shell am broadcast -a io.appium.settings.wifi -n io.appium.settings/.receivers.WiFiConnectionSettingReceiver --es setstatus disable` isn't disabling WiFI.

**Comment by KazuCocoa** [comment]
`2019-03-17 12:08:44.766 1954-4896/system_process I/WifiService: setWifiEnabled not allowed for uid=10115`

```
$ adb shell pm grant io.appium.settings android.permission.CHANGE_WIFI_STATE
Security exception: Permission android.permission.CHANGE_WIFI_STATE requested by io.appium.settings is not a changeable permission type

java.lang.SecurityException: Permission android.permission.CHANGE_WIFI_STATE requested by io.appium.settings is not a changeable permission type
        at com.android.server.pm.permission.BasePermission.enforceDeclaredUsedAndRuntimeOrDevelopment(BasePermission.java:408)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:1898)
        at com.android.server.pm.permission.PermissionManagerService.access$900(PermissionManagerService.java:113)
        at com.android.server.pm.permission.PermissionManagerService$PermissionManagerInternalImpl.grantRuntimePermission(PermissionManagerService.java:2621)
        at com.android.server.pm.PackageManagerService.grantRuntimePermission(PackageManagerService.java:5294)
        at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:1878)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:225)
        at android.os.ShellCommand.exec(ShellCommand.java:103)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:20765)
        at android.os.Binder.shellCommand(Binder.java:887)
        at android.os.Binder.onTransact(Binder.java:771)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4725)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3689)
        at android.os.Binder.execTransactInternal(Binder.java:1026)
        at android.os.Binder.execTransact(Binder.java:999)
```

**Comment by KazuCocoa** [comment]
> This method was deprecated in API level Q. Starting with Build.VERSION_CODES#Q, applications are not allowed to enable/disable Wi-Fi regardless of application's target SDK. This API will have no effect and will always return false.

https://developer.android.com/reference/android/net/wifi/WifiManager.html#setWifiEnabled(boolean)

**Comment by dpgraham** [comment]
This method opens the "Quick Settings": https://developer.android.com/reference/android/support/test/uiautomator/UiDevice#openquicksettings

We can probably use that to toggle the wifi.

**Comment by niuniuliu** [comment]
How about: 
1. adb shell am start -a android.intent.action.MAIN -n com.android.settings/.wifi.WifiSettings
2. adb shell input keyevent 23

**Comment by mandrzejczyk** [comment]
> 
> 
> How about:
> 
>     1. adb shell am start -a android.intent.action.MAIN -n com.android.settings/.wifi.WifiSettings
> 
>     2. adb shell input keyevent 23

This won't work on Samsung devices.

**Comment by KazuCocoa** [comment]
link: https://github.com/appium/appium/issues/12311

**Comment by mykola-mokhnach** [comment]
@dpgraham @KazuCocoa  
We could try to set the `device owner` permissions for the corresponding activity as it is described in https://github.com/steinwurf/adb-join-wifi:

```
Modifying existing Wifi configurations

Note that android apps are not allowed to change the wifi configuration if it was created by another app (for example -- by the user in the Settings app). For this reason, if you try to use this app to join/modify an existing wifi network, this app will not modify it and will join it as-configured.

To get around this for testing purposes and modify any wifi configuration, you can grant this app device owner privileges:

adb shell dpm set-device-owner "com.steinwurf.adbjoinwifi/.AdminReceiver"

```

**Comment by mykola-mokhnach** [comment]
btw, I tried to enable/disable wifi using Android Settings service on the most recent Android 11 emulator and it worked. Perhaps, the issue is only relevant to real devices?

**Comment by KazuCocoa** [comment]
Could be

**Comment by KazuCocoa** [comment]
not perfect, but I tried to run `set-device-owner` as below.
https://github.com/appium/io.appium.settings/compare/deviceadmin?expand=1

```
 % adb shell dpm set-device-owner "io.appium.settings/.receivers.WiFiConnectionSettingReceiver"
usage: dpm [subcommand] [options]
usage: dpm set-active-admin [ --user <USER_ID> | current ] <COMPONENT>
usage: dpm set-device-owner [ --user <USER_ID> | current *EXPERIMENTAL* ] [ --name <NAME> ] <COMPONENT>
usage: dpm set-profile-owner [ --user <USER_ID> | current ] [ --name <NAME> ] <COMPONENT>
usage: dpm remove-active-admin [ --user <USER_ID> | current ] [ --name <NAME> ] <COMPONENT>

dpm set-active-admin: Sets the given component as active admin for an existing user.

dpm set-device-owner: Sets the given component as active admin, and its package as device owner.

dpm set-profile-owner: Sets the given component as active admin and profile owner for an existing user.

dpm remove-active-admin: Disables an active admin, the admin must have declared android:testOnly in the application in its manifest. This will also remove device and profile owners.

dpm clear-freeze-period-record: clears framework-maintained record of past freeze periods that the device went through. For use during feature development to prevent triggering restriction on setting freeze periods.

dpm force-network-logs: makes all network logs available to the DPC and triggers DeviceAdminReceiver.onNetworkLogsAvailable() if needed.

dpm force-security-logs: makes all security logs available to the DPC and triggers DeviceAdminReceiver.onSecurityLogsAvailable() if needed.
usage: dpm mark-profile-owner-on-organization-owned-device: [ --user <USER_ID> | current ] <COMPONENT>


Error: Bad admin: ComponentInfo{io.appium.settings/io.appium.settings.receivers.WiFiConnectionSettingReceiver}
```

But `Bad admin` was raised. I was Android 11 real device. The code change is not enough since the receiver should inherit `DeviceAdminReceiver`, but maybe `set-device-owner` itself does not work well?

----

I've also tried https://github.com/steinwurf/adb-join-wifi as-is, then it needed to make `adb shell pm list users` be one person, and all accounts in `adb shell dumpsys account` be removed, so it must have been `0`.) to get success.
It means users cannot change WiFi preference in the middle of a session if the app under test etc saved their account in accounts. (Google accounts also must be removed). Maybe this way is not reasonable?

```
% adb shell dpm set-device-owner "com.steinwurf.adbjoinwifi/.AdminReceiver"
Success: Device owner set to package ComponentInfo{com.steinwurf.adbjoinwifi/com.steinwurf.adbjoinwifi.AdminReceiver}
Active admin set to component {com.steinwurf.adbjoinwifi/com.steinwurf.adbjoinwifi.AdminReceiver}
```

I haven't checked exactly the admin way can switch WiFi conditions tho.

Btw, my real device still had `I/WifiService: setWifiEnabled not allowed for uid=10115` error in current master way.

**Comment by mykola-mokhnach** [comment]
I don't think there is anything more we could add to this issue. Lets just not hack Android security.
Users can always disable wifi by opening the notifications drawer and clicking the icon there. We cannot implement it this way though as different devices have different UI, so no universal way of finding the wifi icon.

**Comment by margasan** [comment]
Appium settings app ver. 3.4.0 successfully turns off/on WiFi:
`~ % adb shell am broadcast -a io.appium.settings.wifi --es setstatus disable
Broadcasting: Intent { act=io.appium.settings.wifi flg=0x400000 (has extras) }
Broadcast completed: result=-1`
`~ % adb shell am broadcast -a io.appium.settings.wifi --es setstatus enable
Broadcasting: Intent { act=io.appium.settings.wifi flg=0x400000 (has extras) }
Broadcast completed: result=-1`
System OS: Android 12
Notes: newer versions of appium settings and particularly the latest one don't change the state of WiFi
