### ISSUE TITLE
how to tap on coordinates ? (C#)

### ISSUE THREAD

**Issue by afk2zenno** [appium/appium#12323]
I use old version of Appium.WebDriver and use command:
driver.Tap(1,x,y,1);  for  tapping on my phone 

But today i download new version of Appium.WebDriver and this command not works;
I spent 2 hours for solve this easy probleb, but i did not find a solution
May anybody give to me example of code how it works on C# ?

**Comment by mykola-mokhnach** [comment]
Use TouchAction API. 

Please use appium forum for questions.
