### ISSUE TITLE
Update ApiDemos and GPSDemo

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#12321]
The API Demos and GPS Demo app prompt with "This app was built for an older version of Android...."

We need to update these apps to run on later Android

Acceptance Criteria:
* [x] Update apidemos to work in Android 29
* [ ] Update gps demo to work in Android 29
* [ ] Make the apks available from appium.io as download link

**Comment by KazuCocoa** [comment]
link: https://github.com/appium/android-apidemos/pull/34

**Comment by mykola-mokhnach** [comment]
Closed as obsolete
