### ISSUE TITLE
Auto accept permissions in mobile browsers

### ISSUE THREAD

**Issue by albertoacn** [appium/appium#12328]
## The problem

Feature request for auto accepting permissions in mobile browsers, i.e. Safari on iOS and Chrome on Android. Or even a clue if there is a workaround would be great.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.11.1 (in fact all of them)
* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium: MacOS 10.14.3
* Node.js version (unless using Appium.app|exe): 8.8.1
* Npm or Yarn package manager: yarn 1.15.1
* Mobile platform/version under test: Android 8 and iOS 
* Real device or emulator/simulator: emulator and simulator
* Appium CLI or Appium.app|exe: appium service in wdio

## Details

Sorry if this is actually documented and/or implemented, but I could not find a clue about it. I just found solutions for native apps but not for Safari or Chrome already installed in the device. 

The point is, when I am launching a browser and not an app, I cannot interact with the native pop up to accept permissions when interacting with the browser nor using auto-accept permissions property in the desired capabilities since the browser is not an app I am installing.

I even tried installing Chrome on the emulator from desired capabilities, but it does not look to work properly though. Using WebView could be an approach, but it is not the ideal solution.

## Link to Appium logs

n/a

## Code To Reproduce Issue [ Good To Have ]

n/a

**Comment by mykola-mokhnach** [comment]
There is no system API, which allows to workaround browser popups. Please let us know if you find such so then we could implement the feature on top of this finding.
