### ISSUE TITLE
Appium Error: Command failed

### ISSUE THREAD

**Issue by BikramDhall** [appium/appium#12336]
while running automation script on Amazon TV gen3 or amazon fire stirck 4k , got issues as below.

[36minfo[39m: [debug] 1 device(s) connected
[36minfo[39m: Found device G070VM0985051PJE
[36minfo[39m: [debug] Setting device id to G070VM0985051PJE
[36minfo[39m: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
[36minfo[39m: [debug] executing cmd: C:\Users\dhall\AppData\Local\Android\sdk\platform-tools\adb.exe -s G070VM0985051PJE wait-for-device
[36minfo[39m: [debug] executing cmd: C:\Users\dhall\AppData\Local\Android\sdk\platform-tools\adb.exe -s G070VM0985051PJE shell "echo 'ready'"
[36minfo[39m: [debug] Starting logcat capture
[36minfo[39m: [debug] Getting device API level
[36minfo[39m: [debug] executing cmd: C:\Users\dhall\AppData\Local\Android\sdk\platform-tools\adb.exe -s G070VM0985051PJE shell "getprop ro.build.version.sdk"
[36minfo[39m: [debug] Device is at API Level 25
[36minfo[39m: Device API level is: 25
[36minfo[39m: [debug] Extracting strings for language: default
[36minfo[39m: [debug] Apk doesn't exist locally
[36minfo[39m: [debug] Could not get strings, but it looks like we had an old strings file anyway, so ignoring
[36minfo[39m: [debug] executing cmd: C:\Users\dhall\AppData\Local\Android\sdk\platform-tools\adb.exe -s G070VM0985051PJE shell "rm -rf /data/local/tmp/strings.json"
[36minfo[39m: [debug] Not uninstalling app since server not started with --full-reset
[36minfo[39m: [debug] Skipping install since we launched with a package instead of an app path
[36minfo[39m: [debug] Forwarding system:4724 to device:4724
[36minfo[39m: [debug] executing cmd: C:\Users\dhall\AppData\Local\Android\sdk\platform-tools\adb.exe -s G070VM0985051PJE forward tcp:4724 tcp:4724
[36minfo[39m: [debug] Pushing appium bootstrap to device...
[36minfo[39m: [debug] executing cmd: C:\Users\dhall\AppData\Local\Android\sdk\platform-tools\adb.exe -s G070VM0985051PJE push "C:\\Program Files (x86)\\Appium\\node_modules\\appium\\build\\android_bootstrap\\AppiumBootstrap.jar" /data/local/tmp/
[36minfo[39m: [debug] Pushing settings apk to device...
[36minfo[39m: [debug] executing cmd: C:\Users\dhall\AppData\Local\Android\sdk\platform-tools\adb.exe -s G070VM0985051PJE install "C:\Program Files (x86)\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk"
[36minfo[39m: [debug] Pushing unlock helper app to device...
[36minfo[39m: [debug] executing cmd: C:\Users\dhall\AppData\Local\Android\sdk\platform-tools\adb.exe -s G070VM0985051PJE install "C:\Program Files (x86)\Appium\node_modules\appium\build\unlock_apk\unlock_apk-debug.apk"
[36minfo[39m: Starting App
[36minfo[39m: [debug] Attempting to kill all 'uiautomator' processes
[36minfo[39m: [debug] Getting all processes with 'uiautomator'
[36minfo[39m: [debug] executing cmd: C:\Users\dhall\AppData\Local\Android\sdk\platform-tools\adb.exe -s G070VM0985051PJE shell "ps 'uiautomator'"
[36minfo[39m: [debug] Stopping logcat capture
[36minfo[39m: [debug] Logcat terminated with code null, signal SIGTERM
[36minfo[39m: [debug] Sent shutdown command, waiting for UiAutomator to stop...
[33mwarn[39m: UiAutomator did not shut down fast enough, calling it gone
[36minfo[39m: [debug] Cleaning up android objects
[36minfo[39m: [debug] Cleaning up appium session
[31merror[39m: Failed to start an Appium session, err was: Error: Command failed: C:\Users\dhall\AppData\Local\Android\sdk\platform-tools\adb.exe -s G070VM0985051PJE shell "ps 'uiautomator'"

[36minfo[39m: [debug] Error: Command failed: C:\Users\dhall\AppData\Local\Android\sdk\platform-tools\adb.exe -s G070VM0985051PJE shell "ps 'uiautomator'"

    at ChildProcess.exithandler (child_process.js:198:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
[36minfo[39m: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Command failed: C:\\Users\\dhall\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe -s G070VM0985051PJE shell \"ps 'uiautomator'\"\n)","killed":false,"code":1,"signal":null,"cmd":"C:\\Users\\dhall\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe -s G070VM0985051PJE shell \"ps 'uiautomator'\"","origValue":"Command failed: C:\\Users\\dhall\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe -s G070VM0985051PJE shell \"ps 'uiautomator'\"\n"},"sessionId":null}
[36minfo[39m: [37m<-- POST /wd/hub/session [39m[31m500[39m[90m 10031.209 ms - 559[39m [90m[39m
org.openqa.selenium.SessionNotCreatedException: A new session could not be created. (Original error: Command failed: C:\Users\dhall\AppData\Local\Android\sdk\platform-tools\adb.exe -s G070VM0985051PJE shell "ps 'uiautomator'"
) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 10.10 seconds

**Comment by mykola-mokhnach** [comment]
Please use the most recent server version and UIA2 or Espresso backend

**Comment by BikramDhall** [comment]
Thanks a lot Mykola-mokhnach,
using appium 1.8.1 as below
C:\Users\dhall>appium -v
1.8.1
C:\Users\dhall>

Node js
C:\Users\dhall>node -v
v6.11.2

C:\Users\dhall>
Java-client 7.0 and
selenium -server- standalone 3.141.59.

Please let me know how to get UIA2 and how to use it.

**Comment by BikramDhall** [comment]
Hi 
Adding more log for more details
Without uninstalling appium settings apk and Unlock apk from devices, it throws error as below 
[36minfo[39m: [debug] executing cmd: C:\Users\dhall\AppData\Local\Android\sdk\platform-tools\adb.exe -s G070VM0985051PJE install "C:\Program Files (x86)\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk"
[36minfo[39m: [debug] Stopping logcat capture
[36minfo[39m: [debug] Logcat terminated with code null, signal SIGTERM
[36minfo[39m: [debug] Sent shutdown command, waiting for UiAutomator to stop...
[33mwarn[39m: UiAutomator did not shut down fast enough, calling it gone
[31merror[39m: Failed to start an Appium session, err was: Error: Command failed: C:\Users\dhall\AppData\Local\Android\sdk\platform-tools\adb.exe -s G070VM0985051PJE install "C:\Program Files (x86)\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk"
adb: failed to install C:\Program Files (x86)\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk: Failure [INSTALL_FAILED_ALREADY_EXISTS: Attempt to re-install io.appium.settings without first uninstalling.]

[36minfo[39m: [debug] Cleaning up android objects
[36minfo[39m: [debug] Cleaning up appium session
[36minfo[39m: [debug] Error: Command failed: C:\Users\dhall\AppData\Local\Android\sdk\platform-tools\adb.exe -s G070VM0985051PJE install "C:\Program Files (x86)\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk"
adb: failed to install C:\Program Files (x86)\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk: Failure [INSTALL_FAILED_ALREADY_EXISTS: Attempt to re-install io.appium.settings without first uninstalling.]

    at ChildProcess.exithandler (child_process.js:198:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
[36minfo[39m: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Command failed: C:\\Users\\dhall\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe -s G070VM0985051PJE install \"C:\\Program Files (x86)\\Appium\\node_modules\\appium\\build\\settings_apk\\settings_apk-debug.apk\"\nadb: failed to install C:\\Program Files (x86)\\Appium\\node_modules\\appium\\build\\settings_apk\\settings_apk-debug.apk: Failure [INSTALL_FAILED_ALREADY_EXISTS: Attempt to re-install io.appium.settings without first uninstalling.]\r\n)","killed":false,"code":1,"signal":null,"cmd":"C:\\Users\\dhall\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe -s G070VM0985051PJE install \"C:\\Program Files (x86)\\Appium\\node_modules\\appium\\build\\settings_apk\\settings_apk-debug.apk\"","origValue":"Command failed: C:\\Users\\dhall\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe -s G070VM0985051PJE install \"C:\\Program Files (x86)\\Appium\\node_modules\\appium\\build\\settings_apk\\settings_apk-debug.apk\"\nadb: failed to install C:\\Program Files (x86)\\Appium\\node_modules\\appium\\build\\settings_apk\\settings_apk-debug.apk: Failure [INSTALL_FAILED_ALREADY_EXISTS: Attempt to re-install io.appium.settings without first uninstalling.]\r\n"},"sessionId":null}
[36minfo[39m: [37m<-- POST /wd/hub/session [39m[31m500[39m[90m 8432.313 ms - 1283[39m [90m[39m
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: A new session could not be created. (Original error: Command failed: C:\Users\dhall\AppData\Local\Android\sdk\platform-tools\adb.exe -s G070VM0985051PJE install "C:\Program Files (x86)\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk"
adb: failed to install C:\Program Files (x86)\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk: Failure [INSTALL_FAILED_ALREADY_EXISTS: Attempt to re-install io.appium.settings without first uninstalling.]
) (WARNING: The server did not provide any stacktrace information)

**Comment by BikramDhall** [comment]
Hi Mykola-Mokhnach,
while installig appium 1.11.0  using this command npm install -g appium@1.11.0  found below 
Please sugggest me to go with which version of appium.

> appium-selendroid-driver@1.13.3 install C:\Users\dhall\AppData\Roaming\npm\node_modules\appium\node_modules\appium-selendroid-driver
> node ./bin/install.js

C:\Users\dhall\AppData\Roaming\npm\node_modules\appium\node_modules\appium-android-driver\build\index.js:38
async function main() {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at doInstall (C:\Users\dhall\AppData\Roaming\npm\node_modules\appium\node_modules\appium-selendroid-driver\bin\install.js:18:58)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.1 (node_modules\appium\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.6 (node_modules\appium\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.6: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-selendroid-driver@1.13.3 install: `node ./bin/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-selendroid-driver@1.13.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dhall\AppData\Roaming\npm-cache\_logs\2019-03-19T11_13_29_930Z-debug.log

U:\>

**Comment by mykola-mokhnach** [comment]
> async function main() {
This happens because of outdated NodeJS

**Comment by BikramDhall** [comment]
Hi Mykola-Mokhnach,
thanks a lot for your help.
After installation of latest server  1.12.1 and node  v10.15.3 got issue as below. 

_[31merror_[39m: uncaughtException: Cannot find module 'internal/util/types' date=Thu Mar 28 2019 18:17:16 GMT+0530 (India Standard Time), pid=22868, uid=null, gid=null, cwd=C:\Program Files (x86)\Appium\node_modules\appium, execPath=C:\Program Files\nodejs\node.exe, version=v10.15.3, argv=[C:\Program Files\nodejs\node.exe, C:\Program Files (x86)\Appium\node_modules\appium\bin\appium.js, --address, 127.0.0.1, --port, 52125], rss=91463680, heapTotal=73641984, heapUsed=33982592, external=203123, loadavg=[0, 0, 0], uptime=788131, trace=[column=15, file=internal/modules/cjs/loader.js, function=Function.Module._resolveFilename, line=582, method=Module._resolveFilename, native=false, column=25, file=internal/modules/cjs/loader.js, function=Function.Module._load, line=508, method=Module._load, native=false, column=17, file=internal/modules/cjs/loader.js, function=Module.require, line=637, method=require, native=false, column=18, file=internal/modules/cjs/helpers.js, function=require, line=22, method=null, native=false, column=31, file=evalmachine.<anonymous>, function=null, line=44, method=null, native=false, column=1, file=x86)\Appium\node_modules\appium\node_modules\md5calculator\node_modules\unzip\node_modules\fstream\node_modules\graceful-fs\fs.js, function=Object.<anonymous> (C:\Program Files, line=11, method=<anonymous> (C:\Program Files, native=false, column=30, file=internal/modules/cjs/loader.js, function=Module._compile, line=701, method=_compile, native=false, column=10, file=internal/modules/cjs/loader.js, function=Object.Module._extensions..js, line=712, method=Module._extensions..js, native=false, column=32, file=internal/modules/cjs/loader.js, function=Module.load, line=600, method=load, native=false, column=12, file=internal/modules/cjs/loader.js, function=tryModuleLoad, line=539, method=null, native=false, column=3, file=internal/modules/cjs/loader.js, function=Function.Module._load, line=531, method=Module._load, native=false, column=17, file=internal/modules/cjs/loader.js, function=Module.require, line=637, method=require, native=false, column=18, file=internal/modules/cjs/helpers.js, function=require, line=22, method=null, native=false, column=27, file=x86)\Appium\node_modules\appium\node_modules\md5calculator\node_modules\unzip\node_modules\fstream\node_modules\graceful-fs\graceful-fs.js, function=Object.<anonymous> (C:\Program Files, line=3, method=<anonymous> (C:\Program Files, native=false, column=30, file=internal/modules/cjs/loader.js, function=Module._compile, line=701, method=_compile, native=false, column=10, file=internal/modules/cjs/loader.js, function=Object.Module._extensions..js, line=712, method=Module._extensions..js, native=false, column=32, file=internal/modules/cjs/loader.js, function=Module.load, line=600, method=load, native=false, column=12, file=internal/modules/cjs/loader.js, function=tryModuleLoad, line=539, method=null, native=false, column=3, file=internal/modules/cjs/loader.js, function=Function.Module._load, line=531, method=Module._load, native=false, column=17, file=internal/modules/cjs/loader.js, function=Module.require, line=637, method=require, native=false, column=18, file=internal/modules/cjs/helpers.js, function=require, line=22, method=null, native=false, column=10, file=x86)\Appium\node_modules\appium\node_modules\md5calculator\node_modules\unzip\node_modules\fstream\lib\reader.js, function=Object.<anonymous> (C:\Program Files, line=4, method=<anonymous> (C:\Program Files, native=false, column=30, file=internal/modules/cjs/loader.js, function=Module._compile, line=701, method=_compile, native=false, column=10, file=internal/modules/cjs/loader.js, function=Object.Module._extensions..js, line=712, method=Module._extensions..js, native=false, column=32, file=internal/modules/cjs/loader.js, function=Module.load, line=600, method=load, native=false, column=12, file=internal/modules/cjs/loader.js, function=tryModuleLoad, line=539, method=null, native=false, column=3, file=internal/modules/cjs/loader.js, function=Function.Module._load, line=531, method=Module._load, native=false, column=17, file=internal/modules/cjs/loader.js, function=Module.require, line=637, method=require, native=false, column=18, file=internal/modules/cjs/helpers.js, function=require, line=22, method=null, native=false, column=18, file=x86)\Appium\node_modules\appium\node_modules\md5calculator\node_modules\unzip\node_modules\fstream\fstream.js, function=Object.<anonymous> (C:\Program Files, line=2, method=<anonymous> (C:\Program Files, native=false, column=30, file=internal/modules/cjs/loader.js, function=Module._compile, line=701, method=_compile, native=false, column=10, file=internal/modules/cjs/loader.js, function=Object.Module._extensions..js, line=712, method=Module._extensions..js, native=false, column=32, file=internal/modules/cjs/loader.js, function=Module.load, line=600, method=load, native=false, column=12, file=internal/modules/cjs/loader.js, function=tryModuleLoad, line=539, method=null, native=false], stack=[Error: Cannot find module 'internal/util/types',     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15),     at Function.Module._load (internal/modules/cjs/loader.js:508:25),     at Module.require (internal/modules/cjs/loader.js:637:17),     at require (internal/modules/cjs/helpers.js:22:18),     at evalmachine.<anonymous>:44:31,     at Object.<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\md5calculator\node_modules\unzip\node_modules\fstream\node_modules\graceful-fs\fs.js:11:1),     at Module._compile (internal/modules/cjs/loader.js:701:30),     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10),     at Module.load (internal/modules/cjs/loader.js:600:32),     at tryModuleLoad (internal/modules/cjs/loader.js:539:12),     at Function.Module._load (internal/modules/cjs/loader.js:531:3),     at Module.require (internal/modules/cjs/loader.js:637:17),     at require (internal/modules/cjs/helpers.js:22:18),     at Object.<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\md5calculator\node_modules\unzip\node_modules\fstream\node_modules\graceful-fs\graceful-fs.js:3:27),     at Module._compile (internal/modules/cjs/loader.js:701:30),     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10),     at Module.load (internal/modules/cjs/loader.js:600:32),     at tryModuleLoad (internal/modules/cjs/loader.js:539:12),     at Function.Module._load (internal/modules/cjs/loader.js:531:3),     at Module.require (internal/modules/cjs/loader.js:637:17),     at require (internal/modules/cjs/helpers.js:22:18),     at Object.<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\md5calculator\node_modules\unzip\node_modules\fstream\lib\reader.js:4:10),     at Module._compile (internal/modules/cjs/loader.js:701:30),     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10),     at Module.load (internal/modules/cjs/loader.js:600:32),     at tryModuleLoad (internal/modules/cjs/loader.js:539:12),     at Function.Module._load (internal/modules/cjs/loader.js:531:3),     at Module.require (internal/modules/cjs/loader.js:637:17),     at require (internal/modules/cjs/helpers.js:22:18),     at Object.<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\md5calculator\node_modules\unzip\node_modules\fstream\fstream.js:2:18),     at Module._compile (internal/modules/cjs/loader.js:701:30),     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10),     at Module.load (internal/modules/cjs/loader.js:600:32),     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)]

**Comment by mykola-mokhnach** [comment]
@BikramDhall This must be a problem with your local Node setup. Google's first link for such error is https://github.com/remy/nodemon/issues/1124

**Comment by BikramDhall** [comment]
Hi  Mykola-Mokhnach,

Earlier issue is not seen by installing NodeJs v11.13.0 and Appium 1.12.1 but got new issue   uncaughtException: internalBinding is not defined
however by issuing the command "npm install -g natives" does not work. (as suggested in https://github.com/nodejs/node/issues/25132)
attaching the complete log 


[31merror[39m: uncaughtException: internalBinding is not defined date=Fri Mar 29 2019 15:01:23 GMT+0530 (India Standard Time), pid=7884, uid=null, gid=null, cwd=C:\Program Files (x86)\Appium\node_modules\appium, execPath=C:\Program Files\nodejs\node.exe, version=v11.13.0, argv=[C:\Program Files\nodejs\node.exe, C:\Program Files (x86)\Appium\node_modules\appium\bin\appium.js, --address, 127.0.0.1, --port, 50045], rss=87007232, heapTotal=67317760, heapUsed=34913872, external=277978, loadavg=[0, 0, 0], uptime=316, trace=[column=1, file=evalmachine.<anonymous>, function=null, line=25, method=null, native=false, column=1, file=x86)\Appium\node_modules\appium\node_modules\md5calculator\node_modules\unzip\node_modules\fstream\node_modules\graceful-fs\fs.js, function=Object.<anonymous> (C:\Program Files, line=11, method=<anonymous> (C:\Program Files, native=false, column=30, file=internal/modules/cjs/loader.js, function=Module._compile, line=805, method=_compile, native=false, column=10, file=internal/modules/cjs/loader.js, function=Object.Module._extensions..js, line=816, method=Module._extensions..js, native=false, column=32, file=internal/modules/cjs/loader.js, function=Module.load, line=672, method=load, native=false, column=12, file=internal/modules/cjs/loader.js, function=tryModuleLoad, line=612, method=null, native=false, column=3, file=internal/modules/cjs/loader.js, function=Function.Module._load, line=604, method=Module._load, native=false, column=19, file=internal/modules/cjs/loader.js, function=Module.require, line=711, method=require, native=false, column=16, file=internal/modules/cjs/helpers.js, function=require, line=14, method=null, native=false, column=27, file=x86)\Appium\node_modules\appium\node_modules\md5calculator\node_modules\unzip\node_modules\fstream\node_modules\graceful-fs\graceful-fs.js, function=Object.<anonymous> (C:\Program Files, line=3, method=<anonymous> (C:\Program Files, native=false, column=30, file=internal/modules/cjs/loader.js, function=Module._compile, line=805, method=_compile, native=false, column=10, file=internal/modules/cjs/loader.js, function=Object.Module._extensions..js, line=816, method=Module._extensions..js, native=false, column=32, file=internal/modules/cjs/loader.js, function=Module.load, line=672, method=load, native=false, column=12, file=internal/modules/cjs/loader.js, function=tryModuleLoad, line=612, method=null, native=false, column=3, file=internal/modules/cjs/loader.js, function=Function.Module._load, line=604, method=Module._load, native=false, column=19, file=internal/modules/cjs/loader.js, function=Module.require, line=711, method=require, native=false, column=16, file=internal/modules/cjs/helpers.js, function=require, line=14, method=null, native=false, column=10, file=x86)\Appium\node_modules\appium\node_modules\md5calculator\node_modules\unzip\node_modules\fstream\lib\reader.js, function=Object.<anonymous> (C:\Program Files, line=4, method=<anonymous> (C:\Program Files, native=false, column=30, file=internal/modules/cjs/loader.js, function=Module._compile, line=805, method=_compile, native=false, column=10, file=internal/modules/cjs/loader.js, function=Object.Module._extensions..js, line=816, method=Module._extensions..js, native=false, column=32, file=internal/modules/cjs/loader.js, function=Module.load, line=672, method=load, native=false, column=12, file=internal/modules/cjs/loader.js, function=tryModuleLoad, line=612, method=null, native=false, column=3, file=internal/modules/cjs/loader.js, function=Function.Module._load, line=604, method=Module._load, native=false, column=19, file=internal/modules/cjs/loader.js, function=Module.require, line=711, method=require, native=false, column=16, file=internal/modules/cjs/helpers.js, function=require, line=14, method=null, native=false, column=18, file=x86)\Appium\node_modules\appium\node_modules\md5calculator\node_modules\unzip\node_modules\fstream\fstream.js, function=Object.<anonymous> (C:\Program Files, line=2, method=<anonymous> (C:\Program Files, native=false, column=30, file=internal/modules/cjs/loader.js, function=Module._compile, line=805, method=_compile, native=false, column=10, file=internal/modules/cjs/loader.js, function=Object.Module._extensions..js, line=816, method=Module._extensions..js, native=false, column=32, file=internal/modules/cjs/loader.js, function=Module.load, line=672, method=load, native=false, column=12, file=internal/modules/cjs/loader.js, function=tryModuleLoad, line=612, method=null, native=false, column=3, file=internal/modules/cjs/loader.js, function=Function.Module._load, line=604, method=Module._load, native=false, column=19, file=internal/modules/cjs/loader.js, function=Module.require, line=711, method=require, native=false, column=16, file=internal/modules/cjs/helpers.js, function=require, line=14, method=null, native=false, column=14, file=x86)\Appium\node_modules\appium\node_modules\md5calculator\node_modules\unzip\lib\extract.js, function=Object.<anonymous> (C:\Program Files, line=6, method=<anonymous> (C:\Program Files, native=false], stack=[ReferenceError: internalBinding is not defined,     at evalmachine.<anonymous>:25:1,     at Object.<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\md5calculator\node_modules\unzip\node_modules\fstream\node_modules\graceful-fs\fs.js:11:1),     at Module._compile (internal/modules/cjs/loader.js:805:30),     at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10),     at Module.load (internal/modules/cjs/loader.js:672:32),     at tryModuleLoad (internal/modules/cjs/loader.js:612:12),     at Function.Module._load (internal/modules/cjs/loader.js:604:3),     at Module.require (internal/modules/cjs/loader.js:711:19),     at require (internal/modules/cjs/helpers.js:14:16),     at Object.<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\md5calculator\node_modules\unzip\node_modules\fstream\node_modules\graceful-fs\graceful-fs.js:3:27),     at Module._compile (internal/modules/cjs/loader.js:805:30),     at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10),     at Module.load (internal/modules/cjs/loader.js:672:32),     at tryModuleLoad (internal/modules/cjs/loader.js:612:12),     at Function.Module._load (internal/modules/cjs/loader.js:604:3),     at Module.require (internal/modules/cjs/loader.js:711:19),     at require (internal/modules/cjs/helpers.js:14:16),     at Object.<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\md5calculator\node_modules\unzip\node_modules\fstream\lib\reader.js:4:10),     at Module._compile (internal/modules/cjs/loader.js:805:30),     at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10),     at Module.load (internal/modules/cjs/loader.js:672:32),     at tryModuleLoad (internal/modules/cjs/loader.js:612:12),     at Function.Module._load (internal/modules/cjs/loader.js:604:3),     at Module.require (internal/modules/cjs/loader.js:711:19),     at require (internal/modules/cjs/helpers.js:14:16),     at Object.<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\md5calculator\node_modules\unzip\node_modules\fstream\fstream.js:2:18),     at Module._compile (internal/modules/cjs/loader.js:805:30),     at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10),     at Module.load (internal/modules/cjs/loader.js:672:32),     at tryModuleLoad (internal/modules/cjs/loader.js:612:12),     at Function.Module._load (internal/modules/cjs/loader.js:604:3),     at Module.require (internal/modules/cjs/loader.js:711:19),     at require (internal/modules/cjs/helpers.js:14:16),     at Object.<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\md5calculator\node_modules\unzip\lib\extract.js:6:14)]
