### ISSUE TITLE
Encountered internal error running command: TypeError: Class constructor BaseDriver cannot be invoked without 'new'

### ISSUE THREAD

**Issue by coolshree4u** [appium/appium#12338]
## The problem

I am using robot framework for automation in that am using Appium Library While launching am facing error that `Encountered internal error running command: TypeError: Class constructor BaseDriver cannot be invoked without 'new'`
```
Open Application    http://localhost:4723/wd/hub
   platformName=iOS
  platformVersion=12.1
    deviceName=iPhone 6
      app=${build_path}       automationName=appium            bundleId=${BUNDLE_ID}
```

## Environment
* Appium version (or git revision) that exhibits the issue: Appium v1.9.1
* Desktop OS/version used to run Appium: Mac
* Node.js version (unless using Appium.app|exe): v10.15.0
* Npm or Yarn package manager: npm  6.4.1
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

*** Intentionally removed app name and bundle id from stack trace
https://gist.github.com/coolshree4u/d66485579b3e9da1e48ab49be7809065

Same capabilities tried with appium-desktop v1.10.0 and able to launch application without an error.

**Comment by imurchie** [comment]
There has been a version mis-match with the drivers. Please uninstall Appium completely (making sure `/usr/local/lib/node_modules/appium` is gone, and `/usr/local/lib/node_modules` has no `appium-` folders. Then reinstall.

**Comment by dpgraham** [comment]
This could have been one of the past issues we had where `npm-shrinkwrap.json` was being disregarded (`package-lock=false`) and hence it's installing the latest base driver instead of what was supposed to be pinned to 1.9.1

**Comment by coolshree4u** [comment]
@imurchie your solution working fine for me, right now am able to execute ios tests with same configuration after uninstall and install appium 1.9.1. Thanks a lot !!

**Comment by imurchie** [comment]
👍
