### ISSUE TITLE
swipe not working in java client 6.1.0

### ISSUE THREAD

**Issue by anilkn72** [appium/appium#12339]
## The problem

Swipe is not working using java client 6.1.0, it was working fine for java client 5.4.0

## Environment

* Appium version (or git revision) that exhibits the issue:1.9.1
* Last Appium version that did not exhibit the issue (if applicable):1.7.2
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: 6.0
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

new TouchAction(this.getDriver()).press(PointOption.point(startx, starty)).waitAction(waitOptions(ofSeconds(2000))).moveTo(PointOption.point(startx, endy)).release().perform();

Please help me.

**Comment by vjmaiky** [comment]
Wait action is in seconds with 2000 value.

`waitAction(waitOptions(ofSeconds(2000)))`

**Comment by vjmaiky** [comment]
I'm using this (you can customise it as you want):

```
        Dimension screenDim = Drivers.getMobileDriver().manage().window().getSize();
            MyLogger.log.info("Swipe up using android Driver");
            int x = width/2;
            double startY = height * 0.90;
            double finalY = height * 0.20;
            new TouchAction(Drivers.getMobileDriver()).longPress(PointOption.point(x, (int) startY))
                    .moveTo(PointOption.point(x, (int) finalY))
                    .release()
                    .perform();
```

**Comment by vjmaiky** [comment]
or:

`            new TouchAction(Drivers.getMobileDriver()).press(start).waitAction(WaitOptions.waitOptions(Duration.ofSeconds(1))).moveTo(end).release().perform();
`
