### ISSUE TITLE
[debug] [RemoteDebugger] Disconnecting from WebKit remote debugger [debug] [iOSLog] Stopping iOS log capture [debug] [XCUITest] Connection to WDA timed out

### ISSUE THREAD

**Issue by sulbhashrivastava** [appium/appium#12330]
## Appium or Appium Desktop?
Hi Team,
I am having issues in real device safari browser automation using Appium and ios-webkit-debug-proxy. Below is the log file from Appium console. It is launching the testing site and then suddenly closing it.

## Environment

- I am running Appium Desktop version _1.10.0.
- I am on Mac 10.13.6

Appium Logs:
[debug] [RemoteDebugger] Found method 'Network.loadingFinished'
[debug] [RemoteDebugger] Received WebKit data: '{"result":{"result":{"type":"object","value":{"status":0,"value":"interactive"}},"wasThrown":false},"id":5}'
[debug] [RemoteDebugger] Found method 'Runtime.evaluate' for '5' message
[debug] [RemoteDebugger] Received result for atom 'execute_script' execution: "interactive"
[debug] [W3C (be17eb86)] Responding to client with driver.execute() result: "interactive"
[HTTP] <-- POST /wd/hub/session/be17eb86-a0d1-4676-8610-02724e0a5f20/execute/sync 200 93 ms - 23
[HTTP] 
[HTTP] --> DELETE /wd/hub/session/be17eb86-a0d1-4676-8610-02724e0a5f20
[HTTP] {}
[debug] [W3C (be17eb86)] Calling AppiumDriver.deleteSession() with args: ["be17eb86-a0d1-4676-8610-02724e0a5f20"]
[debug] [BaseDriver] Event 'quitSessionRequested' logged at 1546935344761 (13:45:44 GMT+0530 (India Standard Time))
[Appium] Removing session be17eb86-a0d1-4676-8610-02724e0a5f20 from our master session list
[debug] [JSONWP Proxy] Matched '/session/be17eb86-a0d1-4676-8610-02724e0a5f20' to command name 'deleteSession'
[debug] [JSONWP Proxy] Proxying [DELETE /session/be17eb86-a0d1-4676-8610-02724e0a5f20] to [DELETE http://localhost:8100/session/D80D7480-EDE7-4C1D-A2E7-3D0EB1E71B94] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n\n  },\n  \"sessionId\" : \"A840612E-327F-43A2-85BB-9F6D61FE7502\",\n  \"status\" : 0\n}"
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [XCUITest] In a web session. Removing remote debugger
[debug] [RemoteDebugger] Disconnecting from WebKit remote debugger
[debug] [iOSLog] Stopping iOS log capture
[debug] [XCUITest] Connection to WDA timed out
[debug] [RemoteDebugger] WebKit remote debugger socket disconnected
[debug] [BaseDriver] Event 'quitSessionFinished' logged at 1546935345796 (13:45:45 GMT+0530 (India Standard Time))
[debug] [W3C (be17eb86)] Received response: null
[debug] [W3C (be17eb86)] But deleting session, so not returning
[debug] [W3C (be17eb86)] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/be17eb86-a0d1-4676-8610-02724e0a5f20 200 1035 ms - 14
[HTTP] 
[debug] [XCUITest] Connection to WDA timed out

**Comment by gauravgandhi15** [comment]
@sulbhashrivastava Were you able to find any solution? I have been facing this issue for long time. Please help if you have any solution

**Comment by mykola-mokhnach** [comment]
> [HTTP] --> DELETE /wd/hub/session/be17eb86-a0d1-4676-8610-02724e0a5f20

I don't observe any errors in the log. The client did send the delete session command and the session has been closed

**Comment by gauravgandhi15** [comment]
> > [HTTP] --> DELETE /wd/hub/session/be17eb86-a0d1-4676-8610-02724e0a5f20
> 
> I don't observe any errors in the log. The client did send the delete session command and the session has been successfully closed in response to it

@mykola-mokhnach A lot of people are facing this issue may be because of iOS-webkit proxy. And there is no solution available to this.

**Comment by mykola-mokhnach** [comment]
Unfortunately the given information is not sufficient to detect or fix any problems

**Comment by gauravgandhi15** [comment]
> Unfortunately the given information is not sufficient to detect or fix any problems

Here i have one opened issue for long time - https://github.com/appium/appium/issues/12251

**Comment by mykola-mokhnach** [comment]
I don't think opening a duplicated one would help to resolve your issue

**Comment by gauravgandhi15** [comment]
> I don't think opening a duplicated one would help to resolve your issue

@mykola-mokhnach I didn't create a duplicate issue. I opened my issue few weeks ago. This one was created by someone else

**Comment by mykola-mokhnach** [comment]
I'm going to close the report as not an issue if no more information could be provided on it.
