### ISSUE TITLE
Remote debugger not connected error in Appium 1.11.1 in iPad webview

### ISSUE THREAD

**Issue by hsarmah09** [appium/appium#12344]
## The Problem
Unable to start test on iPad safari with Appium 1.11.1 The safari browser is opened but the url which we have in our tests is not opened and test fails throwing the exception that remote debugger is not connected. I tried manually starting the ios-webkit-debug-proxy for the device but still unable to resolve the problem. This problem happens only with iPad and not with iPhone.

## Environment

* Appium version (or git revision) that exhibits the issue:1.11.1
* Last Appium version that did not exhibit the issue (if applicable):1.9
* Desktop OS/version used to run Appium:mac OS High -Sierra version 10.13.6
* Node.js version (unless using Appium.app|exe): v11.11.0
 * Npm or Yarn package manager:6.7.0
* Mobile platform/version under test: iOS 12.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

https://gist.github.com/hsarmah09/cd7a7bb53eb74aaaa2249398bd2dc1ab

**Comment by imurchie** [comment]
Please provide the _full_ logs (as a link to a [gist](https://gist.github.com)).

**Comment by hsarmah09** [comment]
Full log from start of one test
https://gist.github.com/hsarmah09/a99052aac06538e3377a6bfc0bdcbf90

**Comment by imurchie** [comment]
There have been reports of the webkit proxy being unstable. 

Can you try two thing:
1. Set `safariGarbageCollect` desired capability to `false`.
2. Set `showSafariNetworkLog` desired capability to `false`.
