### ISSUE TITLE
[FeatureRequest] running a dockerized Appium with iOS Simulator

### ISSUE THREAD

**Issue by malhussan** [appium/appium#12340]
## The problem

In Appium DesiredCapability, there is a possibility for communicating with a remote Android Emulator by setting the remoteAdbHost. I could not find any similar possibility for iOS Simulator (to allow Appium to communicate with a remote iOS Simulator). 

## Environment

* Appium version: 1.11.2-rc.1
* Desktop OS/version used to run Appium: macOS High Sierra 10.13.5 
* Node.js version: v11.10.1
* Npm or Yarn package manager: Npm 6.7.0
* Mobile platform/version under test: iOS 11.4
* Real device or emulator/simulator: iOS Simulator
* Appium CLI

## Details

To integrate Appium in a CI/CD environment, it is convenient to dockerize Appium. However, when Appium and iOS Simulator are in different machines (have different IP Address), it is not possible for Appium to start the iOS Simulator and communicate with it. It would be perfect to have such feature in Appium.

**Comment by mykola-mokhnach** [comment]
Unfortunately Apple does not provide Mac OS license, which would allow to dockerize it, so even if we had enough resources to make it possible (which we don't), it would still be impossible.
