### ISSUE TITLE
Appium iOS web browser automation opens up "appium.io" first and then goes to the testing URL

### ISSUE THREAD

**Issue by gauravgandhi15** [appium/appium#12350]
## The problem

I have automation scripts set up for iOS safari browser. When i run my tests, appium by default opens up URL "appium.io" and then it goes to the specified test URL. Android doesn't behave the same, it goes straight to the testing URL.

## Environment

* Appium version: 1.11.0
* Mobile platform/version under test: iOS 12.1
* Real device or emulator/simulator: Real device and simulator both

##Capabilities

    `platformName: "iOS",
    platformVersion: "12.1",
    deviceName: "iPhone",
    browserName: "Safari",
    automationName: "XCUITest",
    startIWDP: true,
    udid: "auto",
    webkitResponseTimeout: 10000,
    xcodeOrgId: "......",
    xcodeSigningId: "iPhone Developer"`

Look at the screenshot
![iOS Safari](https://user-images.githubusercontent.com/4743766/54640220-a14f6c80-4a65-11e9-80dd-a7bddc1bc9cc.png)

**Comment by mykola-mokhnach** [comment]
Try `safariInitialUrl` capability
