### ISSUE TITLE
Appium Desktop Client v1.11.1 Won't Launch on iOS 

### ISSUE THREAD

**Issue by Pdubzzz** [appium/appium#12356]
## The problem

Appium desktop client is fails to start on iOS devices while fetching dependencies 

## Environment

* Appium Desktop Version 1.11.0
* Last Appium version that did not exhibit the issue (if applicable): 1.7.1 (last one I've used)
* Desktop OS/version used to run Appium: macOS 10.13.6
* Mobile platform/version under test: iOS 12.1.4 (Android is fine)
* Real device(s): iPhone X, iPhone SE, iPhone 6s

## Details

It looks like new desktop client is using 'ssh' instead of 'http' when fetching dependencies. Specific one that fails for me is 'CocoaAsyncSocket'

```
[XCUITest] A shell task (/usr/bin/env git clone --bare --quiet ssh://git@github.com/robbiehanson/CocoaAsyncSocket.git /Users/poddubnyym/Library/Caches/org.carthage.CarthageKit/dependencies/CocoaAsyncSocket) failed with exit code 128:
[XCUITest] git@github.com: Permission denied (publickey).
[XCUITest] fatal: Could not read from remote repository.
[XCUITest] Please make sure you have the correct access rights
[XCUITest] and the repository exists.
```

Full log is available bellow:

## Link to Appium logs

https://gist.github.com/Pdubzzz/f7790ece4332b5124405c7bb790c5268

**Comment by mykola-mokhnach** [comment]
It is rather a problem with carthage than with Appium

**Comment by Pdubzzz** [comment]
With some help from my coworker we found a solution to my problem:
Workaround would be to use the following capability when setting up your session:
`useCarthageSsl = false`
I'm not sure why carthage was defaulting to use ssh over http on my box but I would really love for contributors of this project to actually contribute to solving issues instead of brushing them off as "ThirdParty" 
¯\_(ツ)_/¯

**Comment by mykola-mokhnach** [comment]
Happy to know that you managed to find a solution. It is impossible to keep all these capabilities in memory. Although, the described problem is really not a bug/issue. It is just a problem of the concrete local setup, which is reflected in that label.
