### ISSUE TITLE
"Could not proxy command to remote server. Original error: Error: read ECONNRESET" error message is displayed while running the script on switching between the appium server, i.e start appium server from Desktop app, run the script and start Appium server in terminal, run the script  or vice versa

### ISSUE THREAD

**Issue by joepreethesh** [appium/appium#12366]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by joepreethesh** [comment]
Summary: "Could not proxy command to remote server. Original error: Error: read ECONNRESET" error message is displayed while running the script on switching between the appium server, i.e start appium server from Desktop app, run the script and start appium server in terminal, run the script  or vice versa

Step to reproduce:
1. Start the appium server form Appium Desktop app
2.Run the script
-> Script execution is successful
3. Quit the desktop app i.e quit the appium server from desktop
4. Now start the appium server from terminal/command prompt
5. Run the script
4. Observe the result

Actual Result:
1. "An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET" error message is displayed 
2. Not even able to launch the app

Expected Result:
Script execution should be successful

Workaround:
Need to delete  the "Appium Settings", "io.appium.uiautomator2.server", "io.appium.uiautomator2.server.test" app from Settings before running the script - only required if user runs the script by switching the servers

appium server version in terminal -  v1.10.1
appium server version within Appium Desktop app- v1.10.0

Note:
Defect not reproducible on stick to one server either form desktop app or terminal

**Comment by joepreethesh** [comment]
[appium-server-logs.txt](https://github.com/appium/appium/files/2995316/appium-server-logs.txt)

**Comment by mykola-mokhnach** [comment]
This has been fixed in 1.11.1. Appium now removes server binaries automatically from the device under test if their versions don't match to the ones included into the current distributive.
