### ISSUE TITLE
Page source dont load the same elements in real device as in emulator

### ISSUE THREAD

**Issue by catluc** [appium/appium#12363]
## The problem

My problem is that am using appium inspector to inspect the an hybrid application on Android with. On Emulator it works fine because i can access all the elements from the inspected view, but in real device in the same view i am not able to see all the elements. Appium is making a webelement tag where it puts all text from my page inside that element, so i am not able to click or to get info from the elements on the page.

## Environment

* Appium version (or git revision) that exhibits the issue: 
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:  MAC Versión 1.11.0 (1.11.0)
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: Android / 7.1.1 , 8.0.0, 9
* Real device or emulator/simulator:  Android / 7.1.1 , 8.0.0, 9
* Appium CLI or Appium.app|exe: App on mac

## Details

....
              <android.view.View index="1" package="com.wtf.whatever" class="android.view.View" text=" **Nueva reserva de parking  Reserva del Cliente  Gestionar reservas"** resource-id="vistaReservaParking" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="true" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,72][1080,2016]" displayed="true" />
...

Those elements are like 3 cardviews inside my app, but in real device the page source make a 
summary in that view element of my view

**Comment by mykola-mokhnach** [comment]
I don't think it is possible to change anything there from Appium side. The code, that6 builds the page tree is completely equal for both devices and emulators and simply displays the structure that the system framework itself generates for us. Try Espresso driver. Or try to only interact with web view elements from inside the web view context.

**Comment by catluc** [comment]
I just tryed out the Espresso and still get the same problem, other thing i just notice is that xpath is changing from emulator and real device for all webelements inside de pageSource, this is a big pitty

**Comment by mykola-mokhnach** [comment]
Then I assume there is nothing to do from Appium side. You should either change your source code or describe the problem to Google.

Closed as third party issue
