### ISSUE TITLE
appium 1.12 started with ANDROID_UIAUTOMATOR2 deletes appium-uiautomator2-server-v3.4.0.apk file

### ISSUE THREAD

**Issue by benfr1** [appium/appium#12368]
## The problem

after a fresh install of appium 1.12 (issue also on 1.11) and starting an appium android test from java :
with ANDROID_UIAUTOMATOR2 deletes appium-uiautomator2-server-v3.4.0.apk,
which in turns throws an blocking error the "appium-uiautomator2-server-v3.4.0.apk' is not writeable. Please grant write permissions to this file or to its parent folder " message.

## Environment

* Appium version (or git revision) that exhibits the issue:1.12, 1.11
* Last Appium version that did not exhibit the issue (if applicable):unknown
* Desktop OS/version used to run Appium:Windows 10
* Node.js version (unless using Appium.app|exe): 8.11.3
* Npm or Yarn package manager:5.6.0
* Mobile platform/version under test:
* Real device or emulator/simulator:both
* Appium CLI or Appium.app|exe:Yes

## Details

N/A

## Link to Appium logs

N/A

## Code To Reproduce Issue [ Good To Have ]

start an appium server with a java client where:
caps.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.ANDROID_UIAUTOMATOR2);
and in debug mode and stop just before the instruction
this.driver = new AppiumDriver<WebElement>( url_ , caps );
after it is executed, the file is deleted.

**Comment by mykola-mokhnach** [comment]
At which stage these files are deleted? Are there any logs? Have you investigated the problem? Maybe these are deleted by some antivirus software running on your computer?

**Comment by benfr1** [comment]
I repeated the process several times to know exactly when it does delete the file, which is : 
this.driver = new AppiumDriver<WebElement>( url_ , caps );

**Comment by mykola-mokhnach** [comment]
I cannot do any assumptions without the additional details. For now it looks more like a local issue to me rather than something on appium side.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue. Feel free to provide more observations on the problem.

**Comment by benfr1** [comment]
investigation : my network admin has deactivated and reactivated symantec antivirus on my machine.
I have done some refactoring of the appium, so can't be sure which did the miracle; the result is now appium works in all 3 cases (espresso/uiautomator2/appium). @mykola-mokhnach thank you for taking the care to look into this. congrats team appium !!

**Comment by benfr1** [comment]
this is DEFINITELY a file based issue. so from installation.
I had a working 1.12, upgraded to 1.14 and the issue magically reoccured !
I will never upgrade appium again !! :)
solution : I had another machine on which a working appium 1.12 was installed.
I copied the whole root node_modules directory of that server to the other, and again eveything worked. pfff
