### ISSUE TITLE
Add Espresso DataMatcher selector to clients

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#12372]
Espresso has a special selector strategy called [Data Matcher](https://github.com/appium/appium/tree/dpgraham-docs-espresso-data-matcher/docs/en/writing-running-appium/android). We need to add this to the clients.

The format is:

`using="-android datamatcher", value="<JSON>"`

Acceptance Criteria:
* [x] Ruby
* [x] Python
* [x] Java
* [x] WebdriverIO
* [ ] C# 
* [x] wd
(cc: @KazuCocoa @SrinivasanTarget @saikrishna321 @akinsolb let me know if you have time to help out with this)

**Comment by SrinivasanTarget** [comment]
Sure will raise it soon for java client @dpgraham

**Comment by SrinivasanTarget** [comment]
@dpgraham we have it [already](https://github.com/appium/java-client/pull/1106) in java client. @mykola-mokhnach has completed it.

**Comment by akinsolb** [comment]
@dpgraham Is there a way to test this in a test app?

**Comment by KazuCocoa** [comment]
- Ruby
    - https://github.com/appium/ruby_lib_core/blob/fd2cbde5466a144ce8dccfc6cf330b969bcc8fd3/lib/appium_lib_core/common/base/search_context.rb#L29
- Python
    - https://github.com/appium/python-client/blob/1c179d2c84c76bbed33e6333f381cc8a86f3bb82/appium/webdriver/common/mobileby.py#L24

@akinsolb you can test like https://github.com/appium/ruby_lib_core/blob/fd2cbde5466a144ce8dccfc6cf330b969bcc8fd3/test/functional/android/android/search_context_test.rb#L47-L56 with real Appium server
