### ISSUE TITLE
FindElementById Method does not get the elements above app

### ISSUE THREAD

**Issue by ArmyMedalMei** [appium/appium#12374]
## Description

When I use the Appium desktop program to check the elements of the page, I can find the elements, but I get an error by calling the FindElementById () method from the .Net program code. Is this a client-driven problem for. net programs? But  I use Python to prompt the same error

## Environment

* .NET client build version or git revision if you use some shapshot:Appium.WebDriver V3.0.0.2
* Appium server version or git revision if you use some shapshot:1.10.0
* Desktop OS/version used to run Appium if necessary:Desktop
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:Appium CLI
* Mobile platform/version under test:Mobile XiaoMi
* Real device or emulator/simulator:Real device

## Details
1.Use Chrome Browser
2.Start Appium Destop Inspector Find the input box element at the top of Google Browser Get the following information:
id | com.android.chrome:id/url_bar
-- | --
xpath | /hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[2]/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.EditText
3.Use .Net Appium.WebDriver Method driver.FindElementById(@"com.android.chrome:id/url_bar").);
4.Nuget:Appium.WebDriver(3.0.0.2)、Selenium.WebDriver（3.0.1）、Selenium.Support（3.0.1）**

## Code To Reproduce Issue [ Good To Have ]

`driver.FindElementById(@"com.android.chrome:id/url_bar");`

## Exception stacktraces

#Matched JSONWP error code 7 to NoSuchElementError

## Link to Appium logs

Appium Destop Start Inspector Session Log:

POST /wd/hub/session/c8b901fe-1a97-4668-acbe-02099f860ac8/elements
[HTTP] {"using":"id","value":"com.android.chrome:id/url_bar"}
[MJSONWP (c8b901fe)] Calling AppiumDriver.findElements() with args: ["id","com.android.chrome:id/url_bar","c8b901fe-1a97-4668-acbe-02099f860ac8"]
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Waiting up to 0 ms for condition
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"com.android.chrome:id/url_bar","context":"","multiple":true}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"com.android.chrome:id/url_bar","context":"","multiple":true}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'com.android.chrome:id/url_bar' using 'ID' with the contextId: '' multiple: true
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[RESOURCE_ID=com.android.chrome:id/url_bar]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements selector:UiSelector[RESOURCE_ID=com.android.chrome:id/url_bar]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Element[] is null: (0)
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements tmp selector:UiSelector[INSTANCE=0, RESOURCE_ID=com.android.chrome:id/url_bar]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Element[] is null: (1)
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements tmp selector:UiSelector[INSTANCE=1, RESOURCE_ID=com.android.chrome:id/url_bar]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":[{"ELEMENT":"1"}]}

.Net Code Run Log:

[HTTP] <-- POST /wd/hub/session 200 14773 ms - 680
[HTTP] 
[HTTP] --> POST /wd/hub/session/26a818b6-989a-48c0-9811-69f9457cdeeb/element
[HTTP] {"using":"id","value":"com.android.chrome:id/url_bar"}
[MJSONWP (26a818b6)] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Matched '/wd/hub/session/26a818b6-989a-48c0-9811-69f9457cdeeb/element' to command name 'findElement'
[JSONWP Proxy] Proxying [POST /wd/hub/session/26a818b6-989a-48c0-9811-69f9457cdeeb/element] to [POST http://127.0.0.1:8000/wd/hub/session/5800119a87008d5cf749241874bb7fe6/element] with body: {"using":"id","value":"com.android.chrome:id/url_bar"}
[JSONWP Proxy] Got response with status 200: {"sessionId":"5800119a87008d5cf749241874bb7fe6","status":7,"value":{"message":"no such element: Unable to locate element: {\"method\":\"id\",\"selector\":\"com.android.chrome:id/url_bar\"}\n  (Session info: chrome=68.0.3440.70)\n  (Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5),platform=Windows NT 10.0.17134 x86_64)"}}
[JSONWP Proxy] Got an unexpected response: {"sessionId":"5800119a87008d5cf749241874bb7fe6","status":7,"value":{"message":"no such element: Unable to locate element: {\"method\":\"id\",\"selector\":\"com.android.chrome:id/url_bar\"}\n  (Session info: chrome=68.0.3440.70)\n  (Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9...
[MJSONWP (26a818b6)] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: The request to /wd/hub/session/26a818b6-989a-48c0-9811-69f9457cdeeb/element has failed
[MJSONWP (26a818b6)]     at JWProxy.proxy (C:\Program Files (x86)\Appium\resources\app\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:180:13)
[MJSONWP] Matched JSONWP error code 7 to NoSuchElementError
[HTTP] <-- POST /wd/hub/session/26a818b6-989a-48c0-9811-69f9457cdeeb/element 500 197 ms - 358

**Comment by mykola-mokhnach** [comment]
Do not use UIAutomator1 for Android 6+. This driver is considered obsolete and is not expected to work properly on these platforms.

**Comment by mykola-mokhnach** [comment]
Also, make sure the destination element is present in the xml page source before locating it.

**Comment by ArmyMedalMei** [comment]
Thank you for your answer. According to your answer, can you use UI Automator 2 to solve this problem? The target element exists in the XML page source

**Comment by mykola-mokhnach** [comment]
If the control is inside a chrome browser then it makes sense to switch to [webview context](http://appium.io/docs/en/writing-running-appium/web/hybrid/).

**Comment by ArmyMedalMei** [comment]
@mykola-mokhnach Thank you for your patience in answering the questions that have plagued me for so many days. Thanks very much. I wish you a happy life.

**Comment by mykola-mokhnach** [comment]
Thanks for the good words.

~~Patience? What's that?~~
