### ISSUE TITLE
Looking forward to index.d.ts declaration file with typescript

### ISSUE THREAD

**Issue by yuchonghua** [appium/appium#12375]
Looking forward to index.d.ts declaration file with typescript
https://github.com/appium/appium-adb/issues/431

**Comment by mykola-mokhnach** [comment]
We don't have plans to use typescript yet.

**Comment by yuchonghua** [comment]
Ok, thank you very much, but I am still very much looking forward to providing typescript, because many documents are not very clear now. In the development process, many variables do not have the convenience of typescript if they are not used.

/ping @mykola-mokhnach
