### ISSUE TITLE
Unable to perform using multiTouchperform in IOS - Appium

### ISSUE THREAD

**Issue by AdarshKumarGM** [appium/appium#12377]
I am using the below versions for Appium and IOS Simulator:

Appium - 11.1
IOS Simulator - 12.1
Device Name - iPhone XS

I have been trying to perform the multiTouchperform in IOS but somehow I am unsuccessful for quite sometime. 

**Problem statement:** I want to click on an element and drag/move it to the desired location  using coordinates at run time

Below is the code I am using as of today:

```
    let x = browser.element("<element1>").getLocation('x')
    let y = browser.element("<element1>").getLocation('y')
    let x1 = browser.element("<element2>").getLocation('x')
    let y1 = browser.element("<element2>").getLocation('y')

browser.touchMultiPerform([
        { action: 'press', options: { x: x, y: y }},
        { action: 'moveTo', options: { x: x1, y: y1 }},
        { action: 'release' }
      ]);
```

When the code runs, it doesn't throw an error nor it performs the required actions in the simulator. What it does is, just go to this functions and that's it i.e. exits doing nothing.

 Can anyone please help.

**Comment by mykola-mokhnach** [comment]
wait after press is required

**Comment by AdarshKumarGM** [comment]
Okay. Is it like if we add as:

`browser.touchMultiPerform([
        { action: 'press', options: { x: x, y: y }},
        {wait:5000},
        { action: 'moveTo', options: { x: x1, y: y1 }},
        { action: 'release' }
      ]);`

will this work? I haven't tried adding wait statements inside. Need your inputs on this please.

**Comment by mykola-mokhnach** [comment]
> will this work?

Try it and see. There is nothing more to add without the server logs

**Comment by AdarshKumarGM** [comment]
Hi @mykola-mokhnach ,

It worked fine. I wrote it like this:

` let x = browser.element("<element1>").getLocation('x')
    let y = browser.element("<element1>").getLocation('y')
    let x1 = browser.element("<element2>").getLocation('x')
    let y1 = browser.element("<element2>").getLocation('y')

browser.touchMultiPerform([
        { action: 'press', options: { x: x, y: y }},
        { action: 'wait', options: {ms:5000}},
        { action: 'moveTo', options: { x: x1, y: y1 }},
        { action: 'release' }
      ]);`

As you had right guessed, it was due to wait only. Thanks for helping out. 

I just had one more. Not related to the code but it is with tool. I am using the version "1.11.0". Today, I got a notification to download "latest 1.10.0". I am wondering why it is being reverted to old version.

**Comment by mykola-mokhnach** [comment]
There was a bug with presets saving, so we had to revert the release until it is fixed.
