### ISSUE TITLE
Could not find a driver for automationName 'uiautomator' and platformName 'Android'

### ISSUE THREAD

**Issue by dron4ik86** [appium/appium#12383]
## The problem

After update to version 1.12.0 get the error:
Could not find a driver for automationName 'uiautomator' and platformName 'Android'
I don't have this problem with version 1.11.1

`
device = {
                'platformName': 'Android',
                'deviceName': 'emulator-5554',
                'app': PATH_TO_ANDROID_APP,
                'unicodeKeyboard': True,
                'resetKeyboard': True,
                'automationName': 'uiautomator',
                'noReset': True,
                'newCommandTimeout': 480,
        }
`

## Environment

* Appium version (or git revision) that exhibits the issue: 1.12.0
* Last Appium version that did not exhibit the issue (if applicable): 1.11.1
* Desktop OS/version used to run Appium: macos mojave 10.14.4
* Node.js version (unless using Appium.app|exe): v11.11.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Android 8
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: Appium CLI

**Comment by mykola-mokhnach** [comment]
does it work for `uiautomator1` ?

**Comment by dron4ik86** [comment]
> does it work for `uiautomator1` ?

Yes, tnx for your answer
