### ISSUE TITLE
Hidekeyboard issue in android pie samsung s8

### ISSUE THREAD

**Issue by MummanaSubramanya** [appium/appium#12385]
## The problem

Driver.hidekeyboard() is not working as expected in android pie. Its going back to the previous screen.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.11.1
* Last Appium version that did not exhibit the issue (if applicable): 1.9.2 beta 3
* Desktop OS/version used to run Appium: win 10
* Mobile platform/version under test: Android pie
* Real device or emulator/simulator: real samsung s8
* Appium CLI or Appium.app|exe: exe

## Details

I recently updated my samsung s8 from Android O to Android P. Tests used to run fine on Android O but started failing in Android P because of hidekeyboard issue. Its going back to the previous screen when HideKeyboard method is called.

## Link to Appium logs
https://gist.github.com/MummanaSubramanya/11758e14db339fb3b4b380d70b248e90

## Code To Reproduce Issue [ Good To Have ]
MobileDriver.HideKeyboard();

**Comment by mykola-mokhnach** [comment]
The logic there is simple. Appium issues key code 111 (ESC) to hide keyboard if it is visible. If the keyboard is still not hidden then key code 4 (Back) is issued.

**Comment by MummanaSubramanya** [comment]
andriodDriver.PressKeyCode(AndroidKeyCode.Keycode_ESCAPE);

goes back to previous screen itself.

**Comment by MummanaSubramanya** [comment]
andriodDriver.PressKeyCode(AndroidKeyCode.Keycode_BACK);  this work around worked for me to hide keyboard.

**Comment by MummanaSubramanya** [comment]
@mykola-mokhnach : Is this issue a device specific? I cannot check as I have only one android P device.

**Comment by mykola-mokhnach** [comment]
I cannot say for sure. Although let us know if there is a better way to handle the keyboard on this particular device

**Comment by mykola-mokhnach** [comment]
> andriodDriver.PressKeyCode(AndroidKeyCode.Keycode_ESCAPE);
> goes back to previous screen itself.

I assume this behaviour depends on how these key codes are handled by the application under test, so there is no universal solution. You may use pressKeyCode as a workaround though
