### ISSUE TITLE
Unable to run automation tests on Android 5.0

### ISSUE THREAD

**Issue by sarasousa** [appium/appium#12396]
I want to run automation tests for a hybrid android application, which uses WEBVIEW and NATIVE contexts.

I'm using an Android emulator with version 5.0 (API 21) and my appium version is 1.9.2-beta.2.
I can install the application and perform the Native actions, but I'm not able to perform the Webview actions.

Initially I tried to use the default browser application which uses another application Android System Webview (by default uses chrome 37). I tried to run with chromedriver 2.10, 2.11 and 2.12 and I always got the following error:

<img width="1370" alt="Screen Shot 2019-03-27 at 11 05 13" src="https://user-images.githubusercontent.com/15266524/55079989-391c0e80-5095-11e9-8ee1-b2bca5ed3637.png">

Then I updated the Android System Webview application to the latest version (73.0) for API 21 and I installed Chrome 72.0 for API 21 and I changed the chromedriver to 2.44 and the following error was displayed:

<img width="1387" alt="Screen Shot 2019-03-27 at 11 10 38" src="https://user-images.githubusercontent.com/15266524/55080144-80a29a80-5095-11e9-8aa4-d3a9c2f874dc.png">

Is there any way to run automation tests in Android 5.0?

**Comment by mykola-mokhnach** [comment]
All these errors are coming from google's chromedriver and not from Appium. I assume you just have to find a matching version.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
