### ISSUE TITLE
Appium 1.12.1 platformVersion needed for real iOS device

### ISSUE THREAD

**Issue by bart-tricentis** [appium/appium#12394]
## The problem

When creating a session to a real iOS device the capabilities platformVersion is needed

## Environment

* Appium version (or git revision) that exhibits the issue: 1.12.1
* Last Appium version that did not exhibit the issue (if applicable): 1.12.0
* Desktop OS/version used to run Appium: macOS 10.14
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs
[log_fail.txt](https://github.com/appium/appium/files/3011884/log_fail.txt)
[log_pass.txt](https://github.com/appium/appium/files/3011885/log_pass.txt)

**Comment by imurchie** [comment]
The `platformVersion` is _always_ required by the specification.

**Comment by Dan-Maor** [comment]
I suspect this PR may have to do with the behavior change:
https://github.com/appium/appium-xcuitest-driver/pull/902

**Comment by imurchie** [comment]
Is there a behavior change? I will not read attached files (there is a reason we ask for logs as [gists](https://gist.github.com)), so I have no idea.

**Comment by Dan-Maor** [comment]
Here is the error from the 1.12.1 log:
> [XCUITest] Error: 'null' cannot be coerced to a valid version number
[XCUITest]     at coerceVersion (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/util.js:241:11)
[XCUITest]     at Object.coerceVersion [as compareVersions] (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/util.js:268:35)
[XCUITest]     at XCUITestDriver.compareVersions [as start] (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:263:14)
[XCUITest]     at <anonymous>

I can confirm that this capability was not required on 1.11.1 to start a session for a real device (did not test 1.12.0).

**Comment by mykola-mokhnach** [comment]
@imurchie I did ask it in #general whether the `platformVersion` cap is the required one. The answer was "yes", so I deliberately didn't add any checks and let it throw if the value is unset/an invalid version number.

**Comment by mykola-mokhnach** [comment]
We have decided to restore the legacy behaviour, so it won't complain anymore if platformVersion is unset for a real device, but some pieces of code might still not work incorrectly in such case. Consider making the capability required in the future appium versions.

https://github.com/appium/appium-xcuitest-driver/pull/912

**Comment by mykola-mokhnach** [comment]
The PR has been published in Appium beta. So, for now the unset platformVersion will not cause an exception if a test is run on a real device and this is a native context, however Appium still requires this cap to be set for web context to work properly there, especially after the recent breaking changes that Apple did in Xcode 10.2 SDK.
