### ISSUE TITLE
On appium 1.10.0 , test cases fails randomly with error "New message: Setup failed: Non-existing index or alias 'WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: No open port found"

### ISSUE THREAD

**Issue by pankajigec26** [appium/appium#12393]
## The problem

I have around 80 Test cases , which runs one by one on windows platform on Samsung S7 Devices. 
Around 27 of the test cases failed with error.

_New message: Setup failed:
Non-existing index or alias 'WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: No open port found_

The capabilties we are using to initiate a session are 

 platformName=android   
 platformVersion=
deviceName
udid
automationName
appPackage
newCommandTimeout
appActivity
autoGrantPermissions
skipUnlock
noReset

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: Windows 7 
* Node.js version (unless using Appium.app|exe): 8.11.3
* Npm or Yarn package manager: 5.6
* Mobile platform/version under test: Samsung S7, Android 8
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Please properly fill out the issue report and attach the log

**Comment by pankajigec26** [comment]
@mykola-mokhnach  could you please help me how can i append the appium logs 

Each test cases on run create appium session one by one , However each time the logs are getting overwrite, is there any option in appium CLI where i can append the logs so that i have log of all the 10 test cases in one single file.

What i tried

**appium -p 4723 --log appium.log**

What i am trying to avoid

**appium -p 4723 --log appium.log>>complete.log**

**Comment by mykola-mokhnach** [comment]
Kindly use Appium forum for question. This is the place for issues
