### ISSUE TITLE
For WKWebViews ,unable to show the  auto population list for drop down widgets

### ISSUE THREAD

**Issue by vutukuriswathi** [appium/appium#12392]
## The problem

I am using a hybrid app.Appium is unable to display the auto population list for drop down widgets inside WKWebview.

## Environment

* Appium version (or git revision) that exhibits the issue:1.10.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:11.4
* Real device or emulator/simulator:simulator and Real device
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/vutukuriswathi/263a0276bab0516db09208cb1985f629

## Code To Reproduce Issue [ Good To Have ]
 toPort().sendKeys("xyz");
Thread.sleep(5000);
toList().click()

**Comment by mykola-mokhnach** [comment]
I assume the application under test is expecting some particular event to happen in order to show that list. Try to emulate the occurrence of that event in `executeScript`. I don't think there is anything to there on Appium side

**Comment by vutukuriswathi** [comment]
yes I tried executing the same thing using executeScript as well but still it is not showing up the auto population list.

Even I tried triggering the onchange () event as well but still the same problem.

Please see the below code I tried.

JavascriptExecutor jsExecutor = (JavascriptExecutor) MobileHelper.getIosDriver();
       jsExecutor.executeScript("document.getElementById('typeahead-input-to').value='perth';");      jsExecutor.executeScript("$(arguments[0]).change();", toPort());

**Comment by mykola-mokhnach** [comment]
Check it with your developers on which event (or events sequence) is expected

**Comment by vutukuriswathi** [comment]
The same webview is working fine on android.I think if there is any problem with the webview event sequence then it should not trigger it on android phones as well.

**Comment by mykola-mokhnach** [comment]
Unlikely. The way Appium interacts with mobile chrome and safari (and browsers themselves) are completely different

**Comment by mykola-mokhnach** [comment]
Closing as not an issue. I don't think there is anything to be done from Appium side.
