### ISSUE TITLE
Android Espresso Not Detecting App Launched

### ISSUE THREAD

**Issue by FerdinandNell** [appium/appium#12409]
## The problem

After installing the Appium Desktop update (1.12.1) - which was shortly removed from the release page thereafter - , none of our Android devices are getting beyond the app installation phase. Espresso is refusing to interact with the application. 

Happening on real devices and emulators

I have tried: 

- Rolling back to the previous version of Appium Desktop (1.12.0)
- Completely removing Appium and reinstalling
- Wiping the emulator and real devices, rebooting etc. 
- Googling
- Praying for a miracle

Environment

Appium version - Latest v1.12.1
MacOS
Appium Desktop 1.12.0 (at least thats the distributable I have installed after removing the updated one - not sure if there is a way to purge local files etc. - I have not seen anyone needing to do this)

Desired Caps: 

{
  "app": "/Users/[redacted]/PycharmProjects/[redacted]/APPS/Android/QA/base.apk",
  "platformName": "Android",
  "automationName": "Espresso",
  "platformVersion": "8.0",
  "deviceName": "device",
  "udid": "23687718740b7ece",
  "disableAndroidWatchers": "true",
  "autoGrantPermissions" : "true",
  "ignoreUnimportantViews" : "true",
  "androidInstallTimeout" : 900000,
  "forceEspressoRebuild": "true",
  "appWaitActivity": "com.[redacted].[redacted].*",
  "appActivity": "com.[redacted].[redacted].presentation.landingpage.LandingPageActivity"
}

Appium Desktop Logs

[Appium] Welcome to Appium v1.12.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"capabilities":{"firstMatch":[{"appium:appActivity":"com.[redacted].[redacted].presentation.landingpage.LandingPageActivity","appium:ignoreUnimportantViews":"true","appium:disableAndroidWatchers":"true","appium:androidInstallTimeout":900000,"appium:autoGrantPermissions":"true","appium:platformVersion":"8.0","appium:appWaitActivity":"com.[redacted].[redacted].*","appium:automationName":"Espresso","appium:app":"/Users/[redacted]/PycharmProjects/[redacted]_TestAutomation_Web/APPS/Android/PP/base.apk","appium:deviceName":"device","appium:forceEspressoRebuild":"true","appium:udid":"23687718740b7ece","platformName":"Android"}]},"desiredCapabilities":{"deviceName":"device","androidInstallTimeout":900000,"autoGrantPermissions":"true","udid":"23687718740b7ece","ignoreUnimportantViews":"true","app":"/Users/[redacted]/PycharmProjects/[redacted]_TestAutomation_Web/APPS/Android/PP/base.apk","appActivity":"com.[redacted].[redacted].presentation.landingpage.LandingPageActivity","disableAndroidWatchers":"true","appWaitActivity":"com.[redacted].[redacted].*"
[W3C] Calling AppiumDriver.createSession() with args: [{"deviceName":"device","androidInstallTimeout":900000,"autoGrantPermissions":"true","udid":"23687718740b7ece","ignoreUnimportantViews":"true","app":"/Users/[redacted]/PycharmProjects/[redacted]_TestAutomation_Web/APPS/Android/PP/base.apk","appActivity":"com.[redacted].[redacted].presentation.landingpage.LandingPageActivity","disableAndroidWatchers":"true","appWaitActivity":"com.[redacted].[redacted].*","platformVersion":"8.0","platformName":"Android","automationName":"Espresso","forceEspressoRebuild":"true"},null,{"firstMatch":[{"appium:appActivity":"com.[redacted].[redacted].presentation.landingpage.LandingPageActivity","appium:ignoreUnimportantViews":"true","appium:disableAndroidWatchers":"true","appium:androidInstallTimeout":900000,"appium:autoGrantPermissions":"true","appium:platformVersion":"8.0","appium:appWaitActivity":"com.[redacted].[redacted].*","appium:automationName":"Espresso","appium:app":"/Users/[redacted]/PycharmProjects/[redacted]_TestAutomation_Web/APPS/Android/PP/base.apk","appium:deviceName":"device","appium:forceEspressoRebuild":"true","appi...
[BaseDriver] Event 'newSessionRequested' logged at 1553852969341 (11:49:29 GMT+0200 (SAST))
[Appium] Appium v1.12.1 creating new EspressoDriver (v1.10.0) session
[Appium] Capabilities:
[Appium]   platformName: Android
[Appium]   appActivity: com.[redacted].[redacted].presentation.landingpage.LandingPageActivity
[Appium]   ignoreUnimportantViews: true
[Appium]   disableAndroidWatchers: true
[Appium]   androidInstallTimeout: 900000
[Appium]   autoGrantPermissions: true
[Appium]   platformVersion: 8.0
[Appium]   appWaitActivity: com.[redacted].[redacted].*
[Appium]   automationName: Espresso
[Appium]   app: /Users/[redacted]/PycharmProjects/[redacted]_TestAutomation_Web/APPS/Android/PP/base.apk
[Appium]   deviceName: device
[Appium]   forceEspressoRebuild: true
[Appium]   udid: 23687718740b7ece
[BaseDriver] W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP desired capabilities {"deviceName":"device","and... were provided
[BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"platformNa...
[BaseDriver] Capability 'forceEspressoRebuild' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Capability 'autoGrantPermissions' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by appium: ignoreUnimportantViews, disableAndroidWatchers.
[BaseDriver] Session created with session id: 46d367db-6021-4f84-a42d-22d8bf56ff2e
[BaseDriver] Using local app '/Users/[redacted]/PycharmProjects/[redacted]_TestAutomation_Web/APPS/Android/PP/base.apk'
[Espresso] Checking whether app is actually present
[Espresso] EspressoDriver version: 1.10.0
[AndroidDriver] Retrieving device list
[ADB] Trying to find a connected android device
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[AndroidDriver] Using device: 23687718740b7ece
[ADB] Setting device id to 23687718740b7ece
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece shell getprop ro.build.version.sdk'
[ADB] Current device property 'ro.build.version.sdk': 28
[ADB] Device API level: 28
[Espresso] Relaxing hidden api policy
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece shell settings put global hidden_api_policy_pre_p_apps 1'
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece shell settings put global hidden_api_policy_p_apps 1'
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece shell settings put global hidden_api_policy 1'
[AndroidDriver] Parsing package and activity from app manifest
[ADB] Starting '/Users/[redacted]/Library/Android/sdk/tools/bin/apkanalyzer' with args ["-h","manifest","print","/Users/[redacted]/PycharmProjects/[redacted]_TestAutomation_Web/APPS/Android/PP/base.apk"]
[ADB] Using the alternative activity name detection method because of: Command '/Users/[redacted]/Library/Android/sdk/tools/bin/apkanalyzer -h manifest print /Users/[redacted]/PycharmProjects/[redacted]_TestAutomation_Web/APPS/Android/PP/base.apk' exited with code 1
[ADB] Extracting package and launch activity from manifest
[ADB] Package name: 'com.[redacted].[redacted].preprod'
[ADB] Main activity name: 'com.[redacted].[redacted].presentation.landingpage.LandingPageActivity'
[AndroidDriver] Parsed package and activity are: com.[redacted].[redacted].preprod/com.[redacted].[redacted].presentation.landingpage.LandingPageActivity
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece wait-for-device'
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece shell echo ping'
[AndroidDriver] Pushing settings apk to device...
[ADB] Getting install status for io.appium.settings
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece shell dumpsys package io.appium.settings'
[ADB] 'io.appium.settings' is installed
[ADB] Getting package info for 'io.appium.settings'
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece shell dumpsys package io.appium.settings'
[ADB] The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('2.14.0' >= '2.14.0')
[ADB] There is no need to install/upgrade '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk'
[ADB] Getting IDs of all 'io.appium.settings' processes
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece shell 'pgrep --help; echo $?''
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece shell pgrep -f \^io\\.appium\\.settings\$'
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece shell am start -W -n io.appium.settings/.Settings -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece shell appops set io.appium.settings android\:mock_location allow'
[Logcat] Starting logcat capture
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece shell settings get global animator_duration_scale'
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece shell settings get global transition_animation_scale'
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece shell settings get global window_animation_scale'
[Espresso] Forwarding Espresso Server port 6791 to 8300
[ADB] Forwarding system: 8300 to device: 6791
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece forward tcp\:8300 tcp\:6791'
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece shell dumpsys window'
[AndroidDriver] Screen already unlocked, doing nothing
[ADB] Checking app cert for /Users/[redacted]/PycharmProjects/[redacted]_TestAutomation_Web/APPS/Android/PP/base.apk
[ADB] Starting '/Users/[redacted]/Library/Android/sdk/build-tools/28.0.3/apksigner' with args '["verify","--print-certs","/Users/[redacted]/PycharmProjects/[redacted]_TestAutomation_Web/APPS/Android/PP/base.apk"]'
[ADB] apksigner stdout: Signer #1 certificate DN: CN=Pre-Production Key, OU=Android Customer App, O=Mr D [redacted], C=ZA
[ADB] Signer #1 certificate SHA-256 digest: d18139ac5761b84bc0426283401128ab0f5abe2e0fd4931b43522bd7730ad603
[ADB] Signer #1 certificate SHA-1 digest: 969438f996c5c334f312e1139664f841e49279bf
[ADB] Signer #1 certificate MD5 digest: d3a2dce1e5351f5e926dfd7c9712824c
[ADB] 
[ADB] '/Users/[redacted]/PycharmProjects/[redacted]_TestAutomation_Web/APPS/Android/PP/base.apk' is signed with non-default certificate
[ADB] /Users/[redacted]/PycharmProjects/[redacted]_TestAutomation_Web/APPS/Android/PP/base.apk' is already zip-aligned. Doing nothing
[ADB] Signing '/Users/[redacted]/PycharmProjects/[redacted]_TestAutomation_Web/APPS/Android/PP/base.apk' with default cert
[ADB] Starting '/Users/[redacted]/Library/Android/sdk/build-tools/28.0.3/apksigner' with args '["sign","--key","/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-adb/keys/testkey.pk8","--cert","/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-adb/keys/testkey.x509.pem","/Users/[redacted]/PycharmProjects/[redacted]_TestAutomation_Web/APPS/Android/PP/base.apk"]'
[ADB] Getting install status for com.[redacted].[redacted].preprod
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece shell dumpsys package com.[redacted].[redacted].preprod'
[ADB] 'com.[redacted].[redacted].preprod' is not installed
[ADB] Getting install status for com.[redacted].[redacted].preprod
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece shell dumpsys package com.[redacted].[redacted].preprod'
[ADB] 'com.[redacted].[redacted].preprod' is not installed
[ADB] App '/Users/[redacted]/PycharmProjects/[redacted]_TestAutomation_Web/APPS/Android/PP/base.apk' is not installed
[ADB] Installing '/Users/[redacted]/PycharmProjects/[redacted]_TestAutomation_Web/APPS/Android/PP/base.apk'
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece shell ls -t -1 /data/local/tmp/appium_cache'
[ADB] The count of applications in the cache: 5
[ADB] Caching the application at '/Users/[redacted]/PycharmProjects/[redacted]_TestAutomation_Web/APPS/Android/PP/base.apk' to '/data/local/tmp/appium_cache/4b28582569ea9043af56f4c281e2931985ecef0b.apk'
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece push /Users/[redacted]/PycharmProjects/[redacted]_TestAutomation_Web/APPS/Android/PP/base.apk /data/local/tmp/appium_cache/4b28582569ea9043af56f4c281e2931985ecef0b.apk'
[ADB] The upload of 'base.apk' (14.59 MB) took 0.746s
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece shell pm install -g /data/local/tmp/appium_cache/4b28582569ea9043af56f4c281e2931985ecef0b.apk'
[ADB] The installation of 'base.apk' took 18.162s
[ADB] Install command stdout: Success
[Espresso] 'forceEspressoRebuild' capability is enabled
[Espresso] Deleting the obsolete Espresso server package '/var/folders/yz/qtd4wdd5425dp0vh60nl8_dh0000gp/T/io.appium.espressoserver.test_1.10.0_com.[redacted].[redacted].preprod.apk'
[Espresso] Repackaging espresso server for: 'com.[redacted].[redacted].preprod'
[Espresso] Creating new manifest: '/var/folders/yz/qtd4wdd5425dp0vh60nl8_dh0000gp/T/AndroidManifest.xml'
[ADB] Found the most recent Android platform: {"platform":"android-28","platformPath":"/Users/[redacted]/Library/Android/sdk/platforms/android-28"}
[ADB] Compiling the manifest: /Users/[redacted]/Library/Android/sdk/build-tools/28.0.3/aapt package -M /var/folders/yz/qtd4wdd5425dp0vh60nl8_dh0000gp/T/AndroidManifest.xml --rename-manifest-package io.appium.espressoserver.test --rename-instrumentation-target-package com.[redacted].[redacted].preprod -I /Users/[redacted]/Library/Android/sdk/platforms/android-28/android.jar -F /var/folders/yz/qtd4wdd5425dp0vh60nl8_dh0000gp/T/AndroidManifest.xml.apk -f
[ADB] Compiled the manifest at '/var/folders/yz/qtd4wdd5425dp0vh60nl8_dh0000gp/T/AndroidManifest.xml.apk'
[ADB] Inserting manifest, src: /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-espresso-driver/espresso-server/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk dst: /var/folders/yz/qtd4wdd5425dp0vh60nl8_dh0000gp/T/io.appium.espressoserver.test_1.10.0_com.[redacted].[redacted].preprod.apk
[ADB] Unzipping '/var/folders/yz/qtd4wdd5425dp0vh60nl8_dh0000gp/T/AndroidManifest.xml.apk' to '/var/folders/yz/qtd4wdd5425dp0vh60nl8_dh0000gp/T'
[ADB] Unzip successful
[ADB] Testing new tmp apk
[ADB] Moving manifest
[ADB] Inserted manifest.
[Espresso] Repackaged espresso server ready: '/var/folders/yz/qtd4wdd5425dp0vh60nl8_dh0000gp/T/io.appium.espressoserver.test_1.10.0_com.[redacted].[redacted].preprod.apk'
[ADB] Checking app cert for /var/folders/yz/qtd4wdd5425dp0vh60nl8_dh0000gp/T/io.appium.espressoserver.test_1.10.0_com.[redacted].[redacted].preprod.apk
[ADB] Starting '/Users/[redacted]/Library/Android/sdk/build-tools/28.0.3/apksigner' with args '["verify","--print-certs","/var/folders/yz/qtd4wdd5425dp0vh60nl8_dh0000gp/T/io.appium.espressoserver.test_1.10.0_com.[redacted].[redacted].preprod.apk"]'
[ADB] Got an error during apksigner execution: Command '/Users/[redacted]/Library/Android/sdk/build-tools/28.0.3/apksigner verify --print-certs /var/folders/yz/qtd4wdd5425dp0vh60nl8_dh0000gp/T/io.appium.espressoserver.test_1.10.0_com.[redacted].[redacted].preprod.apk' exited with code 1
[ADB] apksigner stderr: DOES NOT VERIFY
[ADB] ERROR: JAR signer CERT.RSA: JAR signature META-INF/CERT.SF indicates the APK is signed using APK Signature Scheme v2 but no such signature was found. Signature stripped?
[ADB] 
[ADB] '/var/folders/yz/qtd4wdd5425dp0vh60nl8_dh0000gp/T/io.appium.espressoserver.test_1.10.0_com.[redacted].[redacted].preprod.apk' is not signed with debug cert
[ADB] /var/folders/yz/qtd4wdd5425dp0vh60nl8_dh0000gp/T/io.appium.espressoserver.test_1.10.0_com.[redacted].[redacted].preprod.apk' is already zip-aligned. Doing nothing
[ADB] Signing '/var/folders/yz/qtd4wdd5425dp0vh60nl8_dh0000gp/T/io.appium.espressoserver.test_1.10.0_com.[redacted].[redacted].preprod.apk' with default cert
[ADB] Starting '/Users/[redacted]/Library/Android/sdk/build-tools/28.0.3/apksigner' with args '["sign","--key","/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-adb/keys/testkey.pk8","--cert","/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-adb/keys/testkey.x509.pem","/var/folders/yz/qtd4wdd5425dp0vh60nl8_dh0000gp/T/io.appium.espressoserver.test_1.10.0_com.[redacted].[redacted].preprod.apk"]'
[ADB] Uninstalling io.appium.espressoserver.test
[ADB] Getting install status for io.appium.espressoserver.test
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece shell dumpsys package io.appium.espressoserver.test'
[ADB] 'io.appium.espressoserver.test' is installed
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece shell am force-stop io.appium.espressoserver.test'
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece uninstall io.appium.espressoserver.test'
[ADB] 'adb uninstall io.appium.espressoserver.test' command output: Success
[ADB] io.appium.espressoserver.test was successfully uninstalled
[Espresso] Uninstalled the obsolete Espresso server package from the device under test
[ADB] Getting install status for io.appium.espressoserver.test
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece shell dumpsys package io.appium.espressoserver.test'
[ADB] 'io.appium.espressoserver.test' is not installed
[ADB] App '/var/folders/yz/qtd4wdd5425dp0vh60nl8_dh0000gp/T/io.appium.espressoserver.test_1.10.0_com.[redacted].[redacted].preprod.apk' is not installed
[Espresso] Installing Espresso Test Server apk from the target device (path: '/var/folders/yz/qtd4wdd5425dp0vh60nl8_dh0000gp/T/io.appium.espressoserver.test_1.10.0_com.[redacted].[redacted].preprod.apk')
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece shell ls -t -1 /data/local/tmp/appium_cache'
[ADB] The count of applications in the cache: 6
[ADB] The application at '/var/folders/yz/qtd4wdd5425dp0vh60nl8_dh0000gp/T/io.appium.espressoserver.test_1.10.0_com.[redacted].[redacted].preprod.apk' is already cached to '/data/local/tmp/appium_cache/1259d844cc7966cef8456116ea98f9134a7bbd73.apk'
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece shell pm install /data/local/tmp/appium_cache/1259d844cc7966cef8456116ea98f9134a7bbd73.apk'
[Espresso] Error: Cannot install '/var/folders/yz/qtd4wdd5425dp0vh60nl8_dh0000gp/T/io.appium.espressoserver.test_1.10.0_com.[redacted].[redacted].preprod.apk' because of 'Error executing adbExec. Original error: 'Command '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece shell pm install /data/local/tmp/appium_cache/1259d844cc7966cef8456116ea98f9134a7bbd73.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'androidInstallTimeout' capability'
[Espresso]     at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[Espresso]     at EspressoRunner.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-espresso-driver/lib/espresso-runner.js:77:16)
[Espresso] Deleting espresso session
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece shell am force-stop com.[redacted].[redacted].preprod'
[Logcat] Stopping logcat capture
[Espresso] Restoring hidden api policy to the device default configuration
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece shell settings delete global hidden_api_policy_pre_p_apps'
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece shell settings delete global hidden_api_policy_p_apps'
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece shell settings delete global hidden_api_policy'
[ADB] Removing forwarded port socket connection: 8300 
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece forward --remove tcp\:8300'
[BaseDriver] Event 'newSessionStarted' logged at 1553853015222 (11:50:15 GMT+0200 (SAST))
[W3C] Encountered internal error running command: Error: Cannot install '/var/folders/yz/qtd4wdd5425dp0vh60nl8_dh0000gp/T/io.appium.espressoserver.test_1.10.0_com.[redacted].[redacted].preprod.apk' because of 'Error executing adbExec. Original error: 'Command '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece shell pm install /data/local/tmp/appium_cache/1259d844cc7966cef8456116ea98f9134a7bbd73.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'androidInstallTimeout' capability'
[W3C]     at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[W3C]     at EspressoRunner.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-espresso-driver/lib/espresso-runner.js:77:16)
[HTTP] <-- POST /wd/hub/session 500 45881 ms - 1624
[HTTP]

**Comment by mykola-mokhnach** [comment]
Try to set `adbExecTimeout` capability to a higher value as a workaround until we figure out why `androidInstallTimeout` value has not been picked up properly

**Comment by FerdinandNell** [comment]
New Error: 

[WD Proxy] Proxying [POST /session] to [POST http://localhost:8300/session] with body: {"desiredCapabilities":{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"Android","adbExecTimeout":900000,"ignoreUnimportantViews":"true","disableAndroidWatchers":"true","androidInstallTimeout":900000,"autoGrantPermissions":true,"platformVersion":"8.0","appActivity":"com.[redacted].[redacted].presentation.landingpage.LandingPageActivity","appWaitActivity":"com.[redacted].[redacted].*","udid":"23687718740b7ece","deviceName":"device","forceEspressoRebuild":true,"app":"/Users/[redacted]/PycharmProjects/[redacted]_TestAutomation_Web/APPS/Android/PP/base.apk","automationName":"Espresso"},"platformName":"Android","adbExecTimeout":900000,"ignoreUnimportantViews":"true","disableAndroidWatchers":"true","androidInstallTimeout":900000,"autoGrantPermissions":true,"platformVersion":"8.0","appActivity":"com.[redacted].[redacted].presentation.landingpage.LandingPageActivity","appWaitActivity":...
[WD Proxy] Got an unexpected response: {"id":"d7f54968-1fe1-414c-b38d-14481c907dc3","sessionId":null,"status":33,"value":"io.appium.espressoserver.lib.handlers.exceptions.SessionNotCreatedException: java.lang.IllegalStateException: Activity 'com.[redacted].[redacted].*' was unable to start within 60000ms timeout\n\tat io.appium.espressoserver.lib....
[MJSONWP] Matched JSONWP error code 33 to SessionNotCreatedError
[Espresso] Deleting espresso session
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece shell am force-stop com.[redacted].[redacted].preprod'
[Espresso] [Instrumentation] [STDOUT] io.appium.espressoserver.EspressoServerRunnerTest:INSTRUMENTATION_RESULT: shortMsg=Process crashed.
[Espresso] [Instrumentation] [STDOUT] INSTRUMENTATION_CODE: 0
[Logcat] Stopping logcat capture
[Espresso] Restoring hidden api policy to the device default configuration
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece shell settings delete global hidden_api_policy_pre_p_apps'
[Espresso] Instrumentation process exited with code 0 from signal null
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece shell settings delete global hidden_api_policy_p_apps'
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece shell settings delete global hidden_api_policy'
[ADB] Removing forwarded port socket connection: 8300 
[ADB] Running '/Users/[redacted]/Library/Android/sdk/platform-tools/adb -P 5037 -s 23687718740b7ece forward --remove tcp\:8300'
[BaseDriver] Event 'newSessionStarted' logged at 1553863638142 (14:47:18 GMT+0200 (SAST))
[W3C] Encountered internal error running command: SessionNotCreatedError: A new session could not be created. Details: io.appium.espressoserver.lib.handlers.exceptions.SessionNotCreatedException: java.lang.IllegalStateException: Activity 'com.[redacted].[redacted].*' was unable to start within 60000ms timeout
[W3C] 	at io.appium.espressoserver.lib.handlers.CreateSession.handle(CreateSession.kt:39)
[W3C] 	at io.appium.espressoserver.lib.handlers.CreateSession.handle(CreateSession.kt:26)
[W3C] 	at io.appium.espressoserver.lib.http.Router.route(Router.java:335)
[W3C] 	at io.appium.espressoserver.lib.http.Server.serve(Server.java:69)
[W3C] 	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
[W3C] 	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
[W3C] 	at java.lang.Thread.run(Thread.java:764)
[W3C] Caused by: java.lang.IllegalStateException: Activity 'com.[redacted].[redacted].*' was unable to start within 60000ms timeout
[W3C] 	at io.appium.espressoserver.lib.helpers.ActivityHelper.startActivity(ActivityHelper.java:91)
[W3C] 	at io.appium.espressoserver.lib.handlers.CreateSession.handle(CreateSession.kt:36)
[W3C] 	... 6 more
[W3C] 
[W3C]     at errorFromMJSONWPStatusCode (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:786:12)
[W3C]     at ProxyRequestError.errorFromMJSONWPStatusCode [as getActualError] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:683:14)
[W3C]     at JWProxy.getActualError [as command] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:234:19)
[HTTP] <-- POST /wd/hub/session 500 107703 ms - 2701
[HTTP] 
[HTTP] --> POST /wd/hub/session

**Comment by mykola-mokhnach** [comment]
Ok, this is something different. Please create a separate issue

**Comment by FerdinandNell** [comment]
> Ok, this is something different. Please create a separate issue

Thanks, logged to : https://github.com/appium/appium/issues/12414

**Comment by mykola-mokhnach** [comment]
Please try to merge https://github.com/appium/appium-espresso-driver/pull/425 and check if the patch resolves your issue about activity detection. [Here](https://appiumpro.com/editions/47) You can find more details on running Appium from source

**Comment by FerdinandNell** [comment]
No luck, not sure if I botched the patching but its still not going beyond app launch on my side. Going to revert appium desktop version and see if it works again.

**Comment by mykola-mokhnach** [comment]
Please attach the updated server logs

**Comment by mykola-mokhnach** [comment]
no logs - no luck
