### ISSUE TITLE
UiAutomator Moving to state 'stopped' for second time execution

### ISSUE THREAD

**Issue by shantanuk90** [appium/appium#12403]
## The problem

When I'm running test cases using Appium, I'm able to execute my test cases successfully, on the android device, for the first time. But, if I run the test case again without closing Appium, it returns the error as' UiAutomator exited unexpectedly with code 0, signal null. Moving to state 'stopped'.

I can't even execute after restarting the server. Only if I close the appium application and restart it, then it's working. 

## Environment

* Appium version - 1.11.0, 1.12.0
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): - node-v11.10.0-x64
* Mobile platform/version under test: - Android 6
* Real device or emulator/simulator: Real device - Panasonic

## Link to Appium logs
[appiumLogs.txt](https://github.com/appium/appium/files/3019807/appiumLogs.txt)

**Comment by shantanuk90** [comment]
When I'm running test cases using Appium, I'm able to execute my test cases successfully, on the android device, for the first time. But, if I run the test case again without closing Appium, it returns the error as' UiAutomator exited unexpectedly with code 0, signal null. Moving to state 'stopped'.

I can't even execute after restarting the server. Only if I close the appium application and restart it, then it's working. 
[appiumLogs.txt](https://github.com/appium/appium/files/3019795/appiumLogs.txt)

**Comment by mykola-mokhnach** [comment]
UiAutomator1 is considered obsolete for Android6+ 
Switch to UIA2 or Espresso

**Comment by shantanuk90** [comment]
@mykola-mokhnach Thanks for the reply. I'm using UiAutomator which is present in android sdk/tools/bin folder. Please can you elaborate where will I get UiAutomator2?

**Comment by dpgraham** [comment]
@shantanuk90 there's a capability called `automationName` which needs to be set to `UiAutomator2`. It will work as long as your sdk isn't way out-of-date.

**Comment by shantanuk90** [comment]
Thank you so much @mykola-mokhnach and @dpgraham. I set the capability and it's working now. Thanks for the help
