### ISSUE TITLE
Appium 1.12.0 displays as 1.12.1 Fails to launch inspector on iOS 12.2

### ISSUE THREAD

**Issue by DanSumBoeing** [appium/appium#12405]
## The problem

From a fresh restore on my Mac, I installed Appium 1.12.0 but when I launch it I see the start server displays 1.12.1 and when attempting to run the inspector with the following capabilities on iOS 12.2 prod using Xcode 10.2 (10E125) I get the following error...

The server is running
[Appium] Welcome to Appium v1.12.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/sessions
[HTTP] {}
[GENERIC] Calling AppiumDriver.getSessions() with args: []
[GENERIC] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 5 ms - 40
[HTTP] 
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"automationName":"XCUITest","bundleId":"com.Jeppesen.Aviator","deviceName":"IPADPRO11","platformName":"iOS","sPlatformVersion":"12.2","udid":"00008027-000151C81184002E","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"automationName":"XCUITest","bundleId":"com.Jeppesen.Aviator","deviceName":"IPADPRO11","platformName":"iOS","sPlatformVersion":"12.2","udid":"00008027-000151C81184002E","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1553814894166 (17:14:54 GMT-0600 (MDT))
[Appium] Appium v1.12.1 creating new XCUITestDriver (v2.110.1) session
[Appium] Capabilities:
[Appium]   automationName: XCUITest
[Appium]   bundleId: com.Jeppesen.Aviator
[Appium]   deviceName: IPADPRO11
[Appium]   platformName: iOS
[Appium]   sPlatformVersion: 12.2
[Appium]   udid: 00008027-000151C81184002E
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[BaseDriver] Creating session with MJSONWP desired capabilities: {"automationName":"XCUITest...
[BaseDriver] The following capabilities were provided, but are not recognized by appium: sPlatformVersion.
[BaseDriver] Session created with session id: 2e2908a9-79ef-4322-96f2-43b484980c4b
[XCUITest] Current user: 'yadeansum'
[XCUITest] Error: 'undefined' cannot be coerced to a valid version number
[XCUITest]     at coerceVersion (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/util.js:241:11)
[XCUITest]     at Object.coerceVersion [as compareVersions] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/util.js:268:35)
[XCUITest]     at XCUITestDriver.compareVersions [as start] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:263:14)
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[BaseDriver] Event 'newSessionStarted' logged at 1553814894442 (17:14:54 GMT-0600 (MDT))
[MJSONWP] Encountered internal error running command: Error: 'undefined' cannot be coerced to a valid version number
[MJSONWP]     at coerceVersion (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/util.js:241:11)
[MJSONWP]     at Object.coerceVersion [as compareVersions] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/util.js:268:35)
[MJSONWP]     at XCUITestDriver.compareVersions [as start] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:263:14)
[HTTP] <-- POST /wd/hub/session 500 278 ms - 192
[HTTP] 
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 3 ms - 57
[HTTP] 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.12.0/1.12.1
* Last Appium version that did not exhibit the issue (if applicable):1.10.0
* Desktop OS/version used to run Appium: Mac mohave 10.14.4
* Node.js version (unless using Appium.app|exe): Appium.app
* Npm or Yarn package manager: ?
* Mobile platform/version under test: iOS 12.2 iPad Pro\ 11 inch
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: Appium.app

## Link to Appium logs

The server is running
[Appium] Welcome to Appium v1.12.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/sessions
[HTTP] {}
[GENERIC] Calling AppiumDriver.getSessions() with args: []
[GENERIC] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 5 ms - 40
[HTTP] 
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"automationName":"XCUITest","bundleId":"com.Jeppesen.Aviator","deviceName":"IPADPRO11","platformName":"iOS","sPlatformVersion":"12.2","udid":"00008027-000151C81184002E","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"automationName":"XCUITest","bundleId":"com.Jeppesen.Aviator","deviceName":"IPADPRO11","platformName":"iOS","sPlatformVersion":"12.2","udid":"00008027-000151C81184002E","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1553814894166 (17:14:54 GMT-0600 (MDT))
[Appium] Appium v1.12.1 creating new XCUITestDriver (v2.110.1) session
[Appium] Capabilities:
[Appium]   automationName: XCUITest
[Appium]   bundleId: com.Jeppesen.Aviator
[Appium]   deviceName: IPADPRO11
[Appium]   platformName: iOS
[Appium]   sPlatformVersion: 12.2
[Appium]   udid: 00008027-000151C81184002E
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[BaseDriver] Creating session with MJSONWP desired capabilities: {"automationName":"XCUITest...
[BaseDriver] The following capabilities were provided, but are not recognized by appium: sPlatformVersion.
[BaseDriver] Session created with session id: 2e2908a9-79ef-4322-96f2-43b484980c4b
[XCUITest] Current user: 'yadeansum'
[XCUITest] Error: 'undefined' cannot be coerced to a valid version number
[XCUITest]     at coerceVersion (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/util.js:241:11)
[XCUITest]     at Object.coerceVersion [as compareVersions] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/util.js:268:35)
[XCUITest]     at XCUITestDriver.compareVersions [as start] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:263:14)
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[BaseDriver] Event 'newSessionStarted' logged at 1553814894442 (17:14:54 GMT-0600 (MDT))
[MJSONWP] Encountered internal error running command: Error: 'undefined' cannot be coerced to a valid version number
[MJSONWP]     at coerceVersion (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/util.js:241:11)
[MJSONWP]     at Object.coerceVersion [as compareVersions] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/util.js:268:35)
[MJSONWP]     at XCUITestDriver.compareVersions [as start] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:263:14)
[HTTP] <-- POST /wd/hub/session 500 278 ms - 192
[HTTP] 
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 3 ms - 57
[HTTP] 

## Code To Reproduce Issue [ Good To Have ]

Launch Appium.app inspector

**Comment by mykola-mokhnach** [comment]
Set correct platformVersion in capabilities.

**Comment by spring196** [comment]
i have the same problem ,  this is not bug?

**Comment by DanSumBoeing** [comment]
Not a bug. Set platformVersion to 12.2

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bennid** [comment]
NOTE: This breaks Appium working in a Selenium Grid when you don't care about the platformVersion
