### ISSUE TITLE
Appium job on grid getting stuck

### ISSUE THREAD

**Issue by MamunC** [appium/appium#12416]
## The problem

I am seeing a strange issue since last week running appium job. I have a selenium grid with a appium node and an android device connected to it. I have nightly job executing a number of tests on the android device.

Last week, I noticed the job getting stuck. The logs do not say anything meaningful. On the selenium grid overview page I can see the same job awaiting a slot to be free.

If I kill the appium client and reconnect the node to the hub, the job continues from where it was stuck.

The test suite runs when running locally and not on the grid

## Environment

* Appium version (or git revision) that exhibits the issue: Originally had appium 1.10.1, upgraded to 1.12.1 and 1.13.0-beta.0 - still seeing the issue
* Last Appium version that did not exhibit the issue (if applicable): 1.10.1
* Desktop OS/version used to run Appium: Mac
* Node.js version (unless using Appium.app|exe): 11.2.0
* Npm or Yarn package manager: 6.4.1
* Mobile platform/version under test: Android 8.1.0
* Real device or emulator/simulator: reproducible in both
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Appium logs - https://gist.github.com/MamunC/0f9e3a4bf7bde0f632cbf5446eaf8735

adb logcat *:E  - https://gist.github.com/MamunC/94302a68fd00eec87beeb15f1a1f2259

**Comment by MamunC** [comment]
<img width="1339" alt="Screen Shot 2019-03-31 at 10 56 29 PM" src="https://user-images.githubusercontent.com/38142620/55300985-5be95280-5408-11e9-8ca8-736edd9bb5a5.png">

**Comment by mykola-mokhnach** [comment]
UiAutomator1 is considered obsolete for Android 6+. Use UiAutomator2 or Espresso

**Comment by MamunC** [comment]
Hi @mykola-mokhnach. Thanks for the quick response.

Similar behaviour with UiAutomator2, but seems like there is bit more detail in the logs
Appium logs - https://gist.github.com/MamunC/72c25dc43094b9a2f0aa6875805915bd
Adb logs - https://gist.github.com/MamunC/61aea6bfc28b2012846ff6b05232f489

**Comment by mykola-mokhnach** [comment]
I don't observe any explicit issues there. You could try to get the snapshot of the UIA2 server process using `adb shell am dumpheap` command to know where exactly it is stuck.

**Comment by MamunC** [comment]
[adbdump.zip](https://github.com/appium/appium/files/3030681/adbdump.zip)

Going through the dump filtered by the app process id. I doubt the issue is with the app as I am seeing the same issue on a different app as well which is stable and has no new development being done in it

**Comment by MamunC** [comment]
Hi, I am still stuck on this issue. Tried even changing the device and also adding newCommandTimeout capability but still seeing the same issue.

**Comment by MamunC** [comment]
Resolved the issue. We had made some changes to our test framework which was causing the @AfterClass method to be not reachable. So for the test classes we were not closing the driver and that led to the tests getting stuck after a number of drivers left open
