### ISSUE TITLE
元素等待超过3分钟APPIUM就会卡死，不寻找元素了

### ISSUE THREAD

**Issue by 18070592371** [appium/appium#12412]
您好：
我发现一个BUG，存在于APPIUM1.71、17.2、1.10.0版本
我用显示等待330秒，还没到APPIUM就不去寻找元素了，卡着不动，不知道什么原因
![image](https://user-images.githubusercontent.com/37534431/55229220-58fb3000-5257-11e9-970d-c1529ba0dea6.png)
![image](https://user-images.githubusercontent.com/37534431/55229238-631d2e80-5257-11e9-9917-fda086b6a0ac.png)

**Comment by vjmaiky** [comment]
yes i agree; i totally agree.

**Comment by mykola-mokhnach** [comment]
Please provide the issue description in English.
