### ISSUE TITLE
appium install error

### ISSUE THREAD

**Issue by jade685** [appium/appium#12419]
## The problem

I've installed appium and used it fine before. But when I uninstall it and try install a latest version, I had this error.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.12.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS Mojave 10.14.3
* Node.js version (unless using Appium.app|exe): v10.15.0
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: iPhone7
* Appium CLI or Appium.app|exe:

## Details

N/A

## Link to Appium logs

https://gist.github.com/jade685/bea09909aba3cb3cc00bb6f75fe9ecdd

## Code To Reproduce Issue [ Good To Have ]

N/A

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by imurchie** [comment]
This is a problem with Python. Can you try using Python 2.7?

**Comment by jade685** [comment]
Yes, I tried change npm to python2 and the problem is sloved.
`npm config set python python2.7`
