### ISSUE TITLE
JSONWP error code 13 (Appium 1.12.1)

### ISSUE THREAD

**Issue by aureliendelrue** [appium/appium#12411]
## The problem

We have the following error `Matched JSONWP error code 13 to UnknownError` when interacting with an element on Safari Mobile. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10, 1.11, 1.12 and 1.12.1
* Desktop OS/version used to run Appium: macOS 10.14.1 and 10.14.3
* Node.js version (unless using Appium.app|exe): 8.12.0
* Npm : 6.9.0
* Mobile platform/version under test: iOS 12.*
* Real device or emulator/simulator: real
* Appium CLI or Appium.app|exe: Appium CLI installed with npm
* Others : Appium node connected to Selenium Hub (3.14)

## Details

We tried multiples versions for Appium (1.10, 1.11 and 1.12.*) and Xcode (10.1, 10.2). An issue was opened in [WebDriverAgent gitHub](https://github.com/facebook/WebDriverAgent/issues/1080) where @mykola-mokhnach said that W3C Actions are only supported in native context. Why these actions are send to WDA for web mobile tests ? These test cases are working fine on Android devices.

Capabilities :

- startIWDP: true
- deviceName: iPhone-8
- platform: MAC
- xcodeSigningId: iPhone Developer
- xcodeOrgId: XXXXXXXXX
- showXcodeLog: true
- platformVersion: 12.1.2
- automationName: XCUITest
- udid: f735e978b52fab1055df552736d606248a4b1ba3
- forceMjsonwp: true
- systemPort: 4723
- browserName: safari
- platformName: ios
- server:CONFIG_UUID: 87d48034-c959-42a0-ba20-1bec0377847f
- wdaLocalPort: 8023

## Link to Appium logs

Log Appium : [GIST](https://gist.github.com/aureliendelrue/f0370af489f194c7fab05bddfce2a3c9)

**Comment by paulinedess** [comment]
Hi @aureliendelrue, I got the same issue. Is your issue resolved ??

**Comment by robertarles** [comment]
We're having the same issue in a mobile app when trying to get the login screen. It was broken in 1.9.1, but showed a screenshot. It's not showing the screenshot in 1.21.1 for us.

**Comment by robertarles** [comment]
update: our problem was solved for our Android app. The login screen is displayed fine after adding "automationName":"uiautomator2" to the capabilities.

**Comment by mykola-mokhnach** [comment]
They are sent only for usage convenience purposes, so one does not have to switch context in order to execute a touch action.
