### ISSUE TITLE
Visual Regression Test for native app on IOS

### ISSUE THREAD

**Issue by AdarshKumarGM** [appium/appium#12410]
I have been going back and forth on various websites to automate native app for visual regression. I have had a look at some:
1. Galen
2. Resemble
3. OcularJS

However, all the above 3 are into Web, but not into native app. I was wondering, if this is possible with Appium. I am not looking at screenshot comparison, but something on similar lines to Galen.

Can anyone please provide some inputs for this?

**Comment by mykola-mokhnach** [comment]
Please use Appium Forum for questions
