### ISSUE TITLE
Is it possible to switch from IOS native app to safari browser at run time in Appium ?

### ISSUE THREAD

**Issue by AdarshKumarGM** [appium/appium#12417]
**Appium Version:** 11.0.1
**IOS Simulator**: iPhone XS
**IOS Simulator version**: 12.1
**Framework**: Node Js

I am trying to figure out if there is a way to set the capability at run time. Below is my ask:

My code will run on a native IOS app. During one of the run, we need to verify by hitting the IOS browser i.e. Safari and take the screenshot. Is it possible to perform this? I know we can do this using Java. I am not aware if there is any such for Javascript/Node Js. 

**Problem statement**:  I need my code to perform a switch from current native app to safari browser.

Can anyone please help

**Comment by mykola-mokhnach** [comment]
There is `setContext` API for such purpose. Please use Appium Fortum for questions
