### ISSUE TITLE
Android real device：app need permission（like location、carmera、root... ） every times  for  running  not only frist-run 

### ISSUE THREAD

**Issue by fishasen** [appium/appium#12425]
## The problem

desired_caps['noreset']=True
desired_caps['appPackage']='***'
desired_caps['appActivity']=***"
I got configure  the script like this,also grant the permission like location or root or carmera with hand operation after frist running app.
But,it always need permission when run app for second or third or more times

## Environment

1、Android mobile：Mi 8
2、Appium Docker for Android

## Details
My confused
1、Whatever app have to request the system permission every times for appium automation test with real device？（The app was already installed in the device for hand operation）
2、If the answer is ‘yes’，how can i allow all the permission like root、location、call... with using webdriver Element localization

**Comment by mykola-mokhnach** [comment]
Are you looking for `autoGrantPermissions` capability?

**Comment by fishasen** [comment]
I also add “autoGrantPermissions:True”，but it don 't works @mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
Can you attach the log file with this cap enabled?
Also, the recent appium@beta got a new `mobile: changePermissions` [command](https://github.com/appium/appium-android-driver/pull/514), which allows to change permissions in runtime.

**Comment by fishasen** [comment]
[log.txt](https://github.com/appium/appium/files/3036655/log.txt)
![TIM图片20190403104540](https://user-images.githubusercontent.com/17735370/55449334-ada6fe00-55fd-11e9-9616-bb4271df43bd.png)
The app still request permission！

**Comment by mykola-mokhnach** [comment]
This is a custom dialog unique to MiOS. You must either change the device preferences to disable it, handle it using normal accessibility access (if possible) or change the device model completely. Unfortunately, there is nothing we can do from Appium side.
