### ISSUE TITLE
SetClipboard NotYetImplementedError: Method has not yet been implemented

### ISSUE THREAD

**Issue by ArmyMedalMei** [appium/appium#12429]
Description
When I used the SetClipboard Text method, I reported an exception method that had not yet been implemented.

Environment
.NET client build version or git revision if you use some shapshot:Appium.WebDriver 4.0.0.5-beta
Appium server version or git revision if you use some shapshot:1.10.0
Desktop OS/version used to run Appium if necessary:Desktop
Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:Appium.Exe
Mobile platform/version under test:Andriod 7.0
Real device or emulator/simulator:Real device
Code To Reproduce Issue [ Good To Have ]
driver.SetClipboardText("Hello Word","label");

Link to Appium logs
[HTTP] --> POST /wd/hub/session/6b2ee3c4-3640-4a28-b8a8-c6f64c19b344/context
[HTTP] {"name":"NATIVE_APP"}
[W3C (6b2ee3c4)] Calling AppiumDriver.setContext() with args: ["NATIVE_APP","6b2ee3c4-3640-4a28-b8a8-c6f64c19b344"]
[AndroidDriver] Available contexts: ["NATIVE_APP","CHROMIUM"]
[W3C (6b2ee3c4)] Responding to client with driver.setContext() result: null
[HTTP] <-- POST /wd/hub/session/6b2ee3c4-3640-4a28-b8a8-c6f64c19b344/context 200 4 ms - 14
[HTTP]
[HTTP] --> POST /wd/hub/session/6b2ee3c4-3640-4a28-b8a8-c6f64c19b344/appium/device/set_clipboard
[HTTP] {"content":"5L2g5aW95ZOf","contentType":"plaintext","label":"dfdfdf"}
[W3C (6b2ee3c4)] Calling AppiumDriver.setClipboard() with args: ["5L2g5aW95ZOf","plaintext","dfdfdf",null,null,"6b2ee3c4-3640-4a28-b8a8-c6f64c19b344"]
[W3C (6b2ee3c4)] Encountered internal error running command: NotYetImplementedError: Method has not yet been implemented

**Comment by mykola-mokhnach** [comment]
Please make sure you use the most recent server version. This endpoint has been implemented quite recently. Also, the endpoint should be called from native context.

**Comment by ArmyMedalMei** [comment]
Used UI Automator 2 to solve the problem. Thank you.
