### ISSUE TITLE
Elements can't be identified, inspector gets stuck directly

### ISSUE THREAD

**Issue by willisfeng** [appium/appium#12426]
## The problem

 Elements can't be identified, inspector gets stuck directly。
Environment

 Appium version:1.12.1

Desktop OS/version :10.14
Node.js version :v10.12.0
Mobile platform/version under test:   12.0 
 emulator/simulator:iphone xr  simulator
 

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

[info] ^[[35m[HTTP]^[[39m ^[[90m{}^[[39m
[debug] ^[[35m[MJSONWP (5b0d5bb5)]^[[39m Calling AppiumDriver.getSession() with args: ["5b0d5bb5-195b-4288-b136-94660731e964"]
[debug] ^[[35m[XCUITest]^[[39m Executing command 'getSession'
[info] ^[[35m[XCUITest]^[[39m Merging WDA caps over Appium caps for session detail response
[debug] ^[[35m[MJSONWP (5b0d5bb5)]^[[39m Responding to client with driver.getSession() result: {"udid":"68C00985-0516-4B20-9784-5F3D2AEFD932","app":"/Users/esther/Desktop/JJSHome.app","deviceName":"iPhone XR","noReset":true,"platformName":"IOS","platformVersion":"12.0","preventWDAAttachments":true,"simpleIsVisibleCheck":true,"newCommandTimeout":0,"connectHardwareKeyboard":true,"device":"iphone","browserName":"9;1Hm~Pm~\~I家Debug","sdkVersion":"12.0","CFBundleIdentifier":"com.jjshome.butlerinhouse620","pixelRatio":2,"statBarHeight":48.551724137931,"viewportRect":{"left":0,"top":97,"width":828,"height":1695}}
[info] ^[[35m[HTTP]^[[39m ^[[37m<-- GET /wd/hub/session/5b0d5bb5-195b-4288-b136-94660731e964 ^[[39m^[[32m200^[[39m ^[[90m1 ms - 588^[[39m
[info] ^[[35m[HTTP]^[[39m ^[[90m^[[39m[info] ^[[35m[HTTP]^[[39m ^[[37m-->^[[39m ^[[37mGET^[[39m ^[[37m/wd/hub/session/5b0d5bb5-195b-4288-b136-94660731e964^[[39m
[info] ^[[35m[HTTP]^[[39m ^[[90m{}^[[39m
[debug] ^[[35m[MJSONWP (5b0d5bb5)]^[[39m Calling AppiumDriver.getSession() with args: ["5b0d5bb5-195b-4288-b136-94660731e964"]
[debug] ^[[35m[XCUITest]^[[39m Executing command 'getSession'
[info] ^[[35m[XCUITest]^[[39m Merging WDA caps over Appium caps for session detail response
[debug] ^[[35m[MJSONWP (5b0d5bb5)]^[[39m Responding to client with driver.getSession() result: {"udid":"68C00985-0516-4B20-9784-5F3D2AEFD932","app":"/Users/esther/Desktop/JJSHome.app","deviceName":"iPhone XR","noReset":true,"platformName":"IOS","platformVersion":"12.0","preventWDAAttachments":true,"simpleIsVisibleCheck":true,"newCommandTimeout":0,"connectHardwareKeyboard":true,"device":"iphone","browserName":"21;1Hm~Pm~\~I家Debug","sdkVersion":"12.0","CFBundleIdentifier":"com.jjshome.butlerinhouse620","pixelRatio":2,"statBarHeight":48.55172413793,"viewportRect":{"left":0,"top":97,"width":828,"height":1695}}
[info] ^[[35m[HTTP]^[[39m ^[[37m<-- GET /wd/hub/session/5b0d5bb5-195b-4288-b136-94660731e964 ^[[39m^[[32m200^[[39m ^[[90m2 ms - 588^[[39m
[info] ^[[35m[HTTP]^[[39m ^[[90m^[[39m[info] ^[[35m[HTTP]^[[39m ^[[37m-->^[[39m ^[[37mGET^[[39m ^[[37m/wd/hub/session/5b0d5bb5-195b-4288-b136-94660731e964^[[39m
[info] ^[[35m[HTTP]^[[39m ^[[90m{}^[[39m
[debug] ^[[35m[MJSONWP (5b0d5bb5)]^[[39m Calling AppiumDriver.getSession() with args: ["5b0d5bb5-195b-4288-b136-94660731e964"]
[debug] ^[[35m[XCUITest]^[[39m Executing command 'getSession'
[info] ^[[35m[XCUITest]^[[39m Merging WDA caps over Appium caps for session detail response
[debug] ^[[35m[MJSONWP (5b0d5bb5)]^[[39m Responding to client with driver.getSession() result: {"udid":"68C00985-0516-4B20-9784-5F3D2AEFD932","app":"/Users/esther/Desktop/JJSHome.app","deviceName":"iPhone XR","noReset":true,"platformName":"IOS","platformVersion":"12.0","preventWDAAttachments":true,"simpleIsVisibleCheck":true,"newCommandTimeout":0,"connectHardwareKeyboard":true,"device":"iphone","browserName":"33;1Hm~Pm~\~I家Debug","sdkVersion":"12.0","CFBundleIdentifier":"com.jjshome.butlerinhouse620","pixelRatio":2,"statBarHeight":48.55172413793,"viewportRect":{"left":0,"top":97,"width":828,"height":1695}}
[info] ^[[35m[HTTP]^[[39m ^[[37m<-- GET /wd/hub/session/5b0d5bb5-195b-4288-b136-94660731e964 ^[[39m^[[32m200^[[39m ^[[90m2 ms - 588^[[39m
[info] ^[[35m[HTTP]^[[39m ^[[90m^[[39m[info] ^[[35m[HTTP]^[[39m ^[[37m-->^[[39m ^[[37mGET^[[39m ^[[37m/wd/hub/session/5b0d5bb5-195b-4288-b136-94660731e964^[[39m
[info] ^[[35m[HTTP]^[[39m ^[[90m{}^[[39m
[debug] ^[[35m[MJSONWP (5b0d5bb5)]^[[39m Calling AppiumDriver.getSession() with args: ["5b0d5bb5-195b-4288-b136-94660731e964"]
[debug] ^[[35m[XCUITest]^[[39m Executing command 'getSession'
[info] ^[[35m[XCUITest]^[[39m Merging WDA caps over Appium caps for session detail response
[debug] ^[[35m[MJSONWP (5b0d5bb5)]^[[39m Responding to client with driver.getSession() result: {"udid":"68C00985-0516-4B20-9784-5F3D2AEFD932","app":"/Users/esther/Desktop/JJSHome.app","deviceName":"iPhone XR","noReset":true,"platformName":"IOS","platformVersion":"12.0","preventWDAAttachments":true,"simpleIsVisibleCheck":true,"newCommandTimeout":0,"connectHardwareKeyboard":true,"device":"iphone","browserName":"45;1Hm~Pm~\~I家Debug","sdkVersion":"12.0","CFBundleIdentifier":"com.jjshome.butlerinhouse620","pixelRatio":2,"statBarHeight":48.55172413793,"viewportRect":{"left":0,"top":97,"width":828,"height":1695}}
[info] ^[[35m[HTTP]^[[39m ^[[37m<-- GET /wd/hub/session/5b0d5bb5-195b-4288-b136-94660731e964 ^[[39m^[[32m200^[[39m ^[[90m1 ms - 588^[[39m
[info] ^[[35m[HTTP]^[[39m ^[[90m^[[39m[info] ^[[35m[HTTP]^[[39m ^[[37m-->^[[39m ^[[37mGET^[[39m ^[[37m/wd/hub/session/5b0d5bb5-195b-4288-b136-94660731e964^[[39m
[info] ^[[35m[HTTP]^[[39m ^[[90m{}^[[39m
[debug] ^[[35m[MJSONWP (5b0d5bb5)]^[[39m Calling AppiumDriver.getSession() with args: ["5b0d5bb5-195b-4288-b136-94660731e964"]
[debug] ^[[35m[XCUITest]^[[39m Executing command 'getSession'
[info] ^[[35m[XCUITest]^[[39m Merging WDA caps over Appium caps for session detail response
[debug] ^[[35m[MJSONWP (5b0d5bb5)]^[[39m Responding to client with driver.getSession() result: {"udid":"68C00985-0516-4B20-9784-5F3D2AEFD932","app":"/Users/esther/Desktop/JJSHome.app","deviceName":"iPhone XR","noReset":true,"platformName":"IOS","platformVersion":"12.0","preventWDAAttachments":true,"simpleIsVisibleCheck":true,"newCommandTimeout":0,"connectHardwareKeyboard":true,"device":"iphone","browserName":"54;1Hm~Pm~\~I家Debug","sdkVersion":"12.0","CFBundleIdentifier":"com.jjshome.butlerinhouse620","pixelRatio":2,"statBarHeight":48.55172413793,"viewportRect":{"left":0,"top":97,"width":828,"height":1695}}
[info] ^[[35m[HTTP]^[[39m ^[[37m<-- GET /wd/hub/session/5b0d5bb5-195b-4288-b136-94660731e964 ^[[39m^[[32m200^[[39m ^[[90m1 ms - 588^[[39m
[info] ^[[35m[HTTP]^[[39m ^[[90m^[[39m[info] ^[[35m[HTTP]^[[39m ^[[37m-->^[[39m ^[[37mGET^[[39m ^[[37m/wd/hub/session/5b0d5bb5-195b-4288-b136-94660731e964^[[39m
[info] ^[[35m[HTTP]^[[39m ^[[90m{}^[[39m
[debug] ^[[35m[MJSONWP (5b0d5bb5)]^[[39m Calling AppiumDriver.getSession() with args: ["5b0d5bb5-195b-4288-b136-94660731e964"]
[debug] ^[[35m[XCUITest]^[[39m Executing command 'getSession'
[info] ^[[35m[XCUITest]^[[39m Merging WDA caps over Appium caps for session detail response
[debug] ^[[35m[MJSONWP (5b0d5bb5)]^[[39m Responding to client with driver.getSession() result: {"udid":"68C00985-0516-4B20-9784-5F3D2AEFD932","app":"/Users/esther/Desktop/JJSHome.app","deviceName":"iPhone XR","noReset":true,"platformName":"IOS","platformVersion":"12.0","preventWDAAttachments":true,"simpleIsVisibleCheck":true,"newCommandTimeout":0,"connectHardwareKeyboard":true,"device":"iphone","browserName":"54;1Hm~Pm~\~I家Debug","sdkVersion":"12.0","CFBundleIdentifier":"com.jjshome.butlerinhouse620","pixelRatio":2,"statBarHeight":48.55172413793,"viewportRect":{"left":0,"top":97,"width":828,"height":1695}}
[info] ^[[35m[HTTP]^[[39m ^[[37m<-- GET /wd/hub/session/5b0d5bb5-195b-4288-b136-94660731e964 ^[[39m^[[32m200^[[39m ^[[90m1 ms - 588^[[39m
[info] ^[[35m[HTTP]^[[39m ^[[90m^[[39m[info] ^[[35m[HTTP]^[[39m ^[[37m-->^[[39m ^[[37mGET^[[39m ^[[37m/wd/hub/session/5b0d5bb5-195b-4288-b136-94660731e964^[[39m
[info] ^[[35m[HTTP]^[[39m ^[[90m{}^[[39m
[debug] ^[[35m[MJSONWP (5b0d5bb5)]^[[39m Calling AppiumDriver.getSession() with args: ["5b0d5bb5-195b-4288-b136-94660731e964"]
[debug] ^[[35m[XCUITest]^[[39m Executing command 'getSession'
[info] ^[[35m[XCUITest]^[[39m Merging WDA caps over Appium caps for session detail response
[debug] ^[[35m[MJSONWP (5b0d5bb5)]^[[39m Responding to client with driver.getSession() result: {"udid":"68C00985-0516-4B20-9784-5F3D2AEFD932","app":"/Users/esther/Desktop/JJSHome.app","deviceName":"iPhone XR","noReset":true,"platformName":"IOS","platformVersion":"12.0","preventWDAAttachments":true,"simpleIsVisibleCheck":true,"newCommandTimeout":0,"connectHardwareKeyboard":true,"device":"iphone","browserName":"54;1Hm~Pm~\~I家Debug","sdkVersion":"12.0","CFBundleIdentifier":"com.jjshome.butlerinhouse620","pixelRatio":2,"statBarHeight":48.55172413793,"viewportRect":{"left":0,"top":97,"width":828,"height":1695}}
[info] ^[[35m[HTTP]^[[39m ^[[37m<-- GET /wd/hub/session/5b0d5bb5-195b-4288-b136-94660731e964 ^[[39m^[[32m200^[[39m ^[[90m2 ms - 588^[[39m
[info] ^[[35m[HTTP]^[[39m ^[[90m^[[39m[info] ^[[35m[HTTP]^[[39m ^[[37m-->^[[39m ^[[37mGET^[[39m ^[[37m/wd/hub/session/5b0d5bb5-195b-4288-b136-94660731e964^[[39m
[info] ^[[35m[HTTP]^[[39m ^[[90m{}^[[39m
[debug] ^[[35m[MJSONWP (5b0d5bb5)]^[[39m Calling AppiumDriver.getSession() with args: ["5b0d5bb5-195b-4288-b136-94660731e964"]
[debug] ^[[35m[XCUITest]^[[39m Executing command 'getSession'
[info] ^[[35m[XCUITest]^[[39m Merging WDA caps over Appium caps for session detail response
[debug] ^[[35m[MJSONWP (5b0d5bb5)]^[[39m Responding to client with driver.getSession() result: {"udid":"68C00985-0516-4B20-9784-5F3D2AEFD932","app":"/Users/esther/Desktop/JJSHome.app","deviceName":"iPhone XR","noReset":true,"platformName":"IOS","platformVersion":"12.0","preventWDAAttachments":true,"simpleIsVisibleCheck":true,"newCommandTimeout":0,"connectHardwareKeyboard":true,"device":"iphone","browserName":"54;1Hm~Pm~\~I家Debug","sdkVersion":"12.0","CFBundleIdentifier":"com.jjshome.butlerinhouse620","pixelRatio":2,"statBarHeight":48.55172413793,"viewportRect":{"left":0,"top":97,"width":828,"height":1695}}
[info] ^[[35m[HTTP]^[[39m ^[[37m<-- GET /wd/hub/session/5b0d5bb5-195b-4288-b136-94660731e964 ^[[39m^[[32m200^[[39m ^[[90m1 ms - 588^[[39m
[info] ^[[35m[HTTP]^[[39m ^[[90m^[[39m[info] ^[[35m[HTTP]^[[39m ^[[37m-->^[[39m ^[[37mGET^[[39m ^[[37m/wd/hub/session/5b0d5bb5-195b-4288-b136-94660731e964^[[39m
[info] ^[[35m[HTTP]^[[39m ^[[90m{}^[[39m
[debug] ^[[35m[MJSONWP (5b0d5bb5)]^[[39m Calling AppiumDriver.getSession() with args: ["5b0d5bb5-195b-4288-b136-94660731e964"]
[debug] ^[[35m[XCUITest]^[[39m Executing command 'getSession'
[info] ^[[35m[XCUITest]^[[39m Merging WDA caps over Appium caps for session detail response
[debug] ^[[35m[MJSONWP (5b0d5bb5)]^[[39m Responding to client with driver.getSession() result: {"udid":"68C00985-0516-4B20-9784-5F3D2AEFD932","app":"/Users/esther/Desktop/JJSHome.app","deviceName":"iPhone XR","noReset":true,"platformName":"IOS","platformVersion":"12.0","preventWDAAttachments":true,"simpleIsVisibleCheck":true,"newCommandTimeout":0,"connectHardwareKeyboard":true,"device":"iphone","browserName":"54;1Hm~Pm~\~I家Debug","sdkVersion":"12.0","CFBundleIdentifier":"com.jjshome.butlerinhouse620","pixelRatio":2,"statBarHeight":48.55172413793,"viewportRect":{"left":0,"top":97,"width":828,"height":1695}}
[info] ^[[35m[HTTP]^[[39m ^[[37m<-- GET /wd/hub/session/5b0d5bb5-195b-4288-b136-94660731e964 ^[[39m^[[32m200^[[39m ^[[90m3 ms - 588^[[39m
[info] ^[[35m[HTTP]^[[39m ^[[90m^[[39m[info] ^[[35m[HTTP]^[[39m ^[[37m-->^[[39m ^[[37mGET^[[39m ^[[37m/wd/hub/session/5b0d5bb5-195b-4288-b136-94660731e964^[[39m
[info] ^[[35m[HTTP]^[[39m ^[[90m{}^[[39m
[debug] ^[[35m[MJSONWP (5b0d5bb5)]^[[39m Calling AppiumDriver.getSession() with args: ["5b0d5bb5-195b-4288-b136-94660731e964"]
[debug] ^[[35m[XCUITest]^[[39m Executing command 'getSession'
[info] ^[[35m[XCUITest]^[[39m Merging WDA caps over Appium caps for session detail response
[debug] ^[[35m[MJSONWP (5b0d5bb5)]^[[39m Responding to client with driver.getSession() result: {"udid":"68C00985-0516-4B20-9784-5F3D2AEFD932","app":"/Users/esther/Desktop/JJSHome.app","deviceName":"iPhone XR","noReset":true,"platformName":"IOS","platformVersion":"12.0","preventWDAAttachments":true,"simpleIsVisibleCheck":true,"newCommandTimeout":0,"connectHardwareKeyboard":true,"device":"iphone","browserName":"54;1Hm~Pm~\~I家Debug","sdkVersion":"12.0","CFBundleIdentifier":"com.jjshome.butlerinhouse620","pixelRatio":2,"statBarHeight":48.55172413793,"viewportRect":{"left":0,"top":97,"width":828,"height":1695}}
[info] ^[[35m[HTTP]^[[39m ^[[37m<-- GET /wd/hub/session/5b0d5bb5-195b-4288-b136-94660731e964 ^[[39m^[[32m200^[[39m ^[[90m1 ms - 588^[[39m
[info] ^[[35m[HTTP]^[[39m ^[[90m^[[39m
[debug] ^[[35m[WD Proxy]^[[39m Matched '/session/5b0d5bb5-195b-4288-b136-94660731e964' to command name 'deleteSession'
[debug] ^[[35m[WD Proxy]^[[39m Proxying [DELETE /session/5b0d5bb5-195b-4288-b136-94660731e964] to [DELETE http://localhost:8100/session/B63AC253-0043-4729-A8C1-CB85D406D0D7] with no body[debug] ^[[35m[WD Proxy]^[[39m Got response with status 200: "{\n  \"value\" : {\n\n  },\n  \"sessionId\" : \"7CFA5690-0209-465F-A461-B07B8C3C7EE1\",\n  \"status\" : 0\n}"
[info] ^[[35m[XCUITest]^[[39m There is no /Users/esther/Library/Developer/Xcode/DerivedData/WebDriverAgent-gdkqzxesdriwhtdnvhprbytxcecz/Logs/Test/Attachments folder, so not changing permissions
[debug] ^[[35m[XCUITest]^[[39m Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] ^[[35m[iOSLog]^[[39m Stopping iOS log capture
[debug] ^[[35m[BaseDriver]^[[39m Event 'quitSessionFinished' logged at 1554177260392 (11:54:20 GMT+0800 (CST))
[debug] ^[[35m[MJSONWP (5b0d5bb5)]^[[39m Received response: null
[debug] ^[[35m[MJSONWP (5b0d5bb5)]^[[39m But deleting session, so not returning
[debug] ^[[35m[MJSONWP (5b0d5bb5)]^[[39m Responding to client with driver.deleteSession() result: null
[info] ^[[35m[HTTP]^[[39m ^[[37m<-- DELETE /wd/hub/session/5b0d5bb5-195b-4288-b136-94660731e964 ^[[39m^[[32m200^[[39m ^[[90m1023 ms - 76^[[39m
[info] ^[[35m[HTTP]^[[39m ^[[90m^[[39m[info] ^[[35m[HTTP]^[[39m ^[[37m-->^[[39m ^[[37mGET^[[39m ^[[37m/wd/hub/sessions^[[39m
[info] ^[[35m[HTTP]^[[39m ^[[90m{}^[[39m
[debug] ^[[35m[GENERIC]^[[39m Calling AppiumDriver.getSessions() with args: []
[debug] ^[[35m[GENERIC]^[[39m Responding to client with driver.getSessions() result: []
[info] ^[[35m[HTTP]^[[39m ^[[37m<-- GET /wd/hub/sessions ^[[39m^[[32m200^[[39m ^[[90m1 ms - 40^[[39m
[info] ^[[35m[HTTP]^[[39m ^[[90m^[[39m[info] ^[[35m[HTTP]^[[39m ^[[37m-->^[[39m ^[[37mDELETE^[[39m ^[[37m/wd/hub/session/5b0d5bb5-195b-4288-b136-94660731e964^[[39m
[info] ^[[35m[HTTP]^[[39m ^[[90m{}^[[39m
[debug] ^[[35m[MJSONWP (5b0d5bb5)]^[[39m Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started
[debug] ^[[35m[MJSONWP (5b0d5bb5)]^[[39m     at asyncHandler (/Applications/Appium12.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:298:15)
[debug] ^[[35m[MJSONWP (5b0d5bb5)]^[[39m     at asyncHandler (/Applications/Appium12.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:489:15)
[debug] ^[[35m[MJSONWP (5b0d5bb5)]^[[39m     at Layer.handle [as handle_request] (/Applications/Appium12.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] ^[[35m[MJSONWP (5b0d5bb5)]^[[39m     at next (/Applications/Appium12.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/route.js:137:13)
[debug] ^[[35m[MJSONWP (5b0d5bb5)]^[[39m     at Route.dispatch (/Applications/Appium12.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/route.js:112:3)
[debug] ^[[35m[MJSONWP (5b0d5bb5)]^[[39m     at Layer.handle [as handle_request] (/Applications/Appium12.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)

**Comment by mykola-mokhnach** [comment]
I don't see any issues in the attached log. The session deletion request has been received, so the next getSession command obviously failed, since there is no such session anymore

**Comment by willisfeng** [comment]
There are no errors log in appium.  but inspector can't recognize the elements. Can I give you the installation package for the simulator to debug?

**Comment by mykola-mokhnach** [comment]
Please describe the issue step by step, the actual result you get and the expected one. Screenshots would be useful too.
