### ISSUE TITLE
Until I relaunch my application, element is not getting located.

### ISSUE THREAD

**Issue by SNagaPavan** [appium/appium#12438]
## The problem

Actually, with earlier Appium versions my script used to run successfully. After a long time, I have updated my java-client to 6.0.0-BETA4. Now at few pages until i make my app to go background and front ground element is not getting located. I am making it by using driver.runAppInBackground(Duration.ofSeconds(1));

Why it is not locating the element even it is present? Why it is getting located when I make my app to go background and front ground?

Can someone please tell me what is the reason for it and how to avoid it.

**Comment by mykola-mokhnach** [comment]
Please properly fill out all the requested data and add full server logs.
