### ISSUE TITLE
iMac appium 1.12.1 how to disable uninstall WebDriverAgent

### ISSUE THREAD

**Issue by fengwenni** [appium/appium#12430]
## The problem
Appium uninstall WebDriverAgent every time,
I tried to comment out /usr/local/lib/node_modules/appium/node_modules/_appium-xcuitest-driver@2.110.1@appium-xcuitest-driver/lib/driver.js:488:13 await this.wda.quitAndUninstall() and add logs ,but it takes no effect,and it did not show what i add logs and show the same line 488,in fact it is not 488 .how can i do

## Environment

`iMac appium 1.12.1`

## Link to Appium logs

```
[debug] [W3C]     at quitAndUninstall (/usr/local/lib/node_modules/appium/node_modules/_appium-xcuitest-driver@2.110.1@appium-xcuitest-driver/lib/driver.js:488:13)
```

**Comment by mykola-mokhnach** [comment]
You can set the `webDriverAgentUrl` capability. If this capability is set then the driver assumes you are responsible for the agent management and will never try to install or delete it.

**Comment by fengwenni** [comment]
it works,thank you

**Comment by fengwenni** [comment]
> You can set the `webDriverAgentUrl` capability. If this capability is set then the driver assumes you are responsible for the agent management and will never try to install or delete it.

**Comment by fengwenni** [comment]
rfer3r3r34

**Comment by fengwenni** [comment]
it works .thank you
