### ISSUE TITLE
Appium 1.12.1 : iOS device not supporting - Xcode WDA build fails

### ISSUE THREAD

**Issue by mnagarajappa** [appium/appium#12432]
## The problem

When i try to configure Appium 1.12.1 and XCode v 10.2.  When i try to build WebDriverAgent in XCode, am not able to test the device. 

Error is: 

Testing couldn’t begin on the device “iPhone”: Logic Testing Unavailable**

**Logic Testing on iOS devices is not supported. You can run logic tests on the Simulator.**

## Environment

* Last Appium version that did not exhibit the issue (if applicable): 1.12.1
* Desktop OS/version used to run Appium: MAC OS Mojave 10.14.3
* Node.js version (unless using Appium.app|exe): latest
* Npm or Yarn package manager: Latest
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real Device - iPhone 6
* Appium CLI or Appium.app|exe:Appium Desktop

**Please help us in resolving this issue.
![Screenshot 2019-04-03 at 6 22 11 PM](https://user-images.githubusercontent.com/23394611/55480263-83753080-563d-11e9-9e74-ec7c06cf6eeb.png)
**

**Comment by KazuCocoa** [comment]
Did you try to build _WebDriverAgentRunner_ as test build?
Your attached image looks WebDriverAgentLib.
http://appium.io/docs/en/drivers/ios-xcuitest-real-devices/

**Comment by mykola-mokhnach** [comment]
It is not very clear what you are trying to achieve with that. Please clarify

**Comment by mnagarajappa** [comment]
> It is not very clear what you are trying to achieve with that. Please clarify

Am trying to test/build WedDriverAgent in iOS device. I need to test in iOS device. But failing.
Can you please guide me on how to build xcodebuild -project WebDriverAgent.

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

this is the only tutorial we have. Kindly use Appium forum for question. This is the place for issue.
