### ISSUE TITLE
Does not want app to be closed after test

### ISSUE THREAD

**Issue by rajesh-dhiman** [appium/appium#12436]
## The problem

HI I am testing an Android app, through a .net application

Every thing works fine. only problem is that when i say AndroidDriver.Quit() it closes the android app.

I want the test app to stay ON when my test is done. Do i have to set some DesiredCapabilities ?

Somebody here (https://discuss.appium.io/t/do-not-want-test-app-to-be-closed-after-test/25799) suggested that do not call AndroidDriver.Quit() before setting the driver to null when test is done if you want app to stay on.

Will this cause any dangling issues ? like memory leak

## Environment

My Environment is as follows

Appium.WebDriver v.3.0.0.2

Selenium Support v.3.8.0

Selenuim.WebDriver v3.9.0

SharpADBClient v2.2.16

**Comment by dpgraham** [comment]
You can set `noReset=true`

http://appium.io/docs/en/writing-running-appium/other/reset-strategies/

**Comment by rajesh-dhiman** [comment]
we have already set that . But still it is closing the app

            Capabilities.SetCapability("noReset", true);    
            Capabilities.SetCapability("fullReset", false);   
            Capabilities.SetCapability("dontStopAppOnReset", true);

**Comment by mykola-mokhnach** [comment]
Currently the application under test is always closed in `deleteSession` after the test is finished: https://github.com/appium/appium-uiautomator2-driver/blob/2ec346336c824f5071f71c2e6a8119b0f47cfb09/lib/driver.js#L521 and there are no options to change this behaviour.

Marking as feature request

**Comment by mykola-mokhnach** [comment]
The change has been published in appium@beta
