### ISSUE TITLE
appium hangs on Proxying [POST /session] with ios simulator

### ISSUE THREAD

**Issue by jpita** [appium/appium#12444]
## The problem

Appium hangs on `Proxying [POST /session] to [POST http://localhost:8100/session]`.
iOS emulator.
While debugging the code it never passes over the step of creating the driver. If I pause the execution is shows it's hanged on` SocketInputStream.java,` method `socketRead0`.
The app opens on the emulator and is responsive.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.12.1
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: MacOS 10.14.4
* xcode version: 10.2
* Node.js version (unless using Appium.app|exe): v11.10.1
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: ios
* Real device or emulator/simulator:emulator
* Appium CLI or Appium.app|exe:CLI

## Details

After a few minutes of hanging, on the logs it starts to show
``` [Xcode] 2019-04-05 17:41:13.876613+0200 WebDriverAgentRunner-Runner[22867:10542398] Enqueue Failure: Failure to determine system application: Error Domain=com.apple.dt.XCTest.XCTFuture Code=1000 "Timeout waiting for fulfillment of promise for 'Fetching attributes 'XC_kAXXCAttributeSystemAppApplication' for Device system-wide element'." UserInfo={NSLocalizedDescription=Timeout waiting for fulfillment of promise for 'Fetching attributes 'XC_kAXXCAttributeSystemAppApplication' for Device system-wide element'.} /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1``` 

## Link to Appium logs

https://gist.github.com/jpita/d4b0f4ffe4488c0b57dd72f6bd2781ae

## Code To Reproduce Issue [ Good To Have ]
The only thing I'm doing is trying to start appium with capabilities, don't think any code is needed for this apart from the caps.
If it is needed, feel free to request.
The same thing happens with Appium Desktop just putting the same caps.
https://imgur.com/liQYt2J

**Comment by mykola-mokhnach** [comment]
I don't think this is an issue with Appium itself, but rather XcTest/WebDriverAgent. Try to play with waitForQuiescence/wdaEventloopIdleDelay capabilities, otherwise I don't have any useful suggestions.

**Comment by jpita** [comment]
`waitForQuiescence` set to false and `wdaEventloopIdleDelay` to 3 seems to do the trick.
Funny how `wdaEventloopIdleDelay` set to 5 doesn't work 😄 

thanks!

**Comment by Srinija25** [comment]
Hi, I am also facing the issue when I try to execute scripts on iOS real devices

Error: Enqueue Failure: Failure getting list of active applications: Error Domain=com.apple.dt.XCTest.XCTFuture Code=1000 "Timeout waiting for fulfillment of promise for 'Fetching attributes 'XC_kAXXCAttributeFocusedApplications' for (null)'." UserInfo={NSLocalizedDescription=Timeout waiting for fulfillment of promise for 'Fetching attributes 'XC_kAXXCAttributeFocusedApplications' for (null)'.} /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1

Environment Details:
Xcode: Version 10.2
Mac OS: Mojave 10.14.3
Appium desktop: v1.12.1
Real Device iPhone 6 (12.1 version)

My Capabilities:

capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iphone7-test");
capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "IOS");
capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "12.1.4");
capabilities.setCapability(MobileCapabilityType.APP, fs.getAbsolutePath());
capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME,AutomationName.IOS_XCUI_TEST);
capabilities.setCapability("deviceOrientation", "portrait");
capabilities.setCapability("xcodeOrgId", "");
capabilities.setCapability("xcodeSigningId", "");
capabilities.setCapability("udid", "");
capabilities.setCapability("updateWDABundleId", "");
capabilities.setCapability("waitForQuiescence", false);
capabilities.setCapability("wdaEventloopIdleDelay", 5);
capabilities.setCapability("eventLoopIdleDelaySec", 1);
capabilities.setCapability("useJSONSource", true);
capabilities.setCapability("useNewWDA", false);
capabilities.setCapability("noReset", true);

It's taken almost 6 mins to start the execution. Please let me know anyone is there is any solution for this.

**Comment by jpita** [comment]
For me putting the wdaEventloopIdleDelay to 3 did the trick.

**Comment by Srinija25** [comment]
Thank you, I will try that
