### ISSUE TITLE
Lodash Prototype Pollution vulnerability in version 1.12.1

### ISSUE THREAD

**Issue by thelgevold** [appium/appium#12441]
## The problem

Getting a lodash Prototype Pollution vulnerability reported from npm when installing version 1.12.1 of appium. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.12.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: OSX
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager: npm
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details
Getting a lodash Moderate  Prototype Pollution vulnerability when installing version 1.12.1 of appium. 

Would you be able to publish a new release with an upgraded version of lodash?

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

run an npm install of appium

**Comment by mykola-mokhnach** [comment]
Closed as incomplete

**Comment by thelgevold** [comment]
More details added. Please re-open.

**Comment by dpgraham** [comment]
Will need to wait on: https://github.com/Samsung/appium-tizen-driver/issues/15

It's an external driver that uses it.

**Comment by mykola-mokhnach** [comment]
I think it makes sense to track the issue in Tizen repository rather than here. We anyway cannot change nothing from our side.
