### ISSUE TITLE
Getting "Bad App" error message when using URL in the 'app' capability

### ISSUE THREAD

**Issue by sanyco92** [appium/appium#12446]
Guys, I'm having the issue. Specified link to the .zip file, which contains the .app file inside (for iOS simulator), but unfortunately having the error message:

> Bad app: http://ci-address.local/repository/download/.lastFinished/Project%20Beta.zip. App paths need to be absolute or an URL to a compressed file

When I'm clicking on this link, the zip file is downloading.
Please help!

Note: I'm using Appium with WebdriverIO (wdio 4.14.1, wdio-appium-service 0.2.3).

Appium logs: 
[appium logs.txt](https://github.com/appium/appium/files/3053430/appium.logs.txt)

## Environment

* Appium version 1.11.1
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe): v10.11.0
* Npm or Yarn package manager: npm 6.9.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: iOS simulator 12.1

**Comment by mykola-mokhnach** [comment]
Please properly fill out the necessary information along with the full server log

**Comment by sanyco92** [comment]
Good morning, guys! Updated information in the topic.

**Comment by mykola-mokhnach** [comment]
There was a known bug, which is currently fixed. Just upgrade the server to the most recent version

**Comment by mykola-mokhnach** [comment]
> Cannot send HEAD request to 'http://ci-mobile.project365.local/repository/download/MyMobileIOS_Development_IOSDevelopmentBranchForTests/.lastFinished/project365%20Beta.zip'. Original error: 401 - ""

**Comment by mykola-mokhnach** [comment]
Most likely this happens because of missing credentials. Try to download the file with `curl` or `wget` and see if this is going to work

**Comment by sanyco92** [comment]
I thought, I have hidden the real link:) can we hide it, so other people will not see it? Thanks:)
I'll try to download it with curl or wget

**Comment by sanyco92** [comment]
> Most likely this happens because of missing credentials. Try to download the file with `curl` or `wget` and see if this is going to work

Actually, it's not real link, I have changed some words, because it contains the project name, I'm afraid of NDA :D

**Comment by mykola-mokhnach** [comment]
This does not matter. Only the return code matters: https://httpstatuses.com/401

**Comment by sanyco92** [comment]
Checked now with `curl`, you are right! Credentials required. Thanks!
