### ISSUE TITLE
How to get the IP and Port of the Web Driver Agent service from the command line or other non-manual way

### ISSUE THREAD

**Issue by fengwenni** [appium/appium#12452]
## The problem

IMAC USB connects to the iPad. How to get the IP and Port of the Web Driver Agent service from the command line or other non-manual way? I really want to pass this value into appium capabilities WebDriverAgentUrl.

## Environment
IMac
iPad
Appium version :1.12.1

## Details

I type it on the command line mobiledevice get_device_prop,but it don't works

**Comment by mykola-mokhnach** [comment]
The IP address of the device is present in getStatus output and in the server logs. Although, it is usually, not needed, since iproxy forward all requests to localhost.  The port number is 8100 by default, although it can be changed from capabilities.

Please use Appium forum for questions
