### ISSUE TITLE
The project ‘WebDriverAgent’ is damaged and cannot be opened due to a parse error. Examine the project file for invalid edits or unresolved source control conflicts.

### ISSUE THREAD

**Issue by SoundaryaBhavanam** [appium/appium#12458]
## The problem

When i try to launch WebdriverAgent Runner project in xcode facing below issue 

The project ‘WebDriverAgent’ is damaged and cannot be opened due to a parse error. Examine the project file for invalid edits or unresolved source control conflicts.

## Environment

* Appium Version --1.10.1
*12.x
* Real device or emulator/simulator:Real devices
* Appium CLI or Appium.app|exe:Appium CLI

## Details

When i reinstall appium and Bootstrap.sh it working fine as work around.
But the issue is repeating again on same mac 

Navigate to the "/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj" location ->Show Package contents  and open the "project.pbxproj" file not seeing any content here

**Comment by mmomin** [comment]
sudo and changing networks is  your best bet

**Comment by KazuCocoa** [comment]
> i reinstall appium and Bootstrap.sh it working fine as work around.
But the issue is repeating again on same mac

Was _Bootstrap.sh_ by Appium? (Or by manual?)
If the command issued by different users in the machine, permission stuff might happen, for example.
Appium runs it in the session creation sequence
