### ISSUE TITLE
Unexpected response ECONNREFUSED on 127.0.0.1:8100 when trying to run tests on iOS Simulator

### ISSUE THREAD

**Issue by lucialuzuriaga** [appium/appium#12459]
I am constantly getting this error when trying to run my tests (made on WebdriverIO) on an iOS simulator. I have tried everything, including:
- Different iOS versions and device models
- Erasing content and settings, cleaning derived data folder
- Appium CLI and Desktop
- Different appium versions: 1.12.1, 1.9.0, 1.9.1
- Different desired capabilities (with or without reset, logs, bundle ID)
- I have chosen the same development team for both the app used and the WDA runner. 

The only issue that i haven’t been able to solve is a failure when running bootstrap script on WebDriverAgent folder. However when I open the project manually both lib and runner build successfully. I manually changed the bundle identifier to match the one of my app, but even if I leave it to the default com.facebook.WebDriverAgentRunner it still refuses to connect. 
I reached a point in which I wasn't getting the econnrefused error message, but the session was nevertheless interrupted/stopped immediately after launching the app. 

I have run out of ideas on why this is happening but it is frustrating and entirely blocking me from performing any work.

- node version: 10.15.1
- npm version: 6.9.0
- OS: MacOS 10.14.4 Mojave
- Xcode Version: 10.1
- Appium version: 1.12.1 (also tried 1.9.0 and 1.9.1)

Appium Logs with Xcode logs included:
[appiumlogs1.txt](https://github.com/facebook/WebDriverAgent/files/3056755/appiumlogs1.txt)

Capabilities:

```
config.capabilities = [
    {
        deviceName: 'iPhone 6',
        platformName: 'iOS',
        platformVersion: '12.1',
        orientation: 'PORTRAIT',
        maxInstances: 1,
        automationName: "XCUITest",
        showXcodeLog: true,
        app: join(process.cwd(), './apps/myapp.app'),
        noReset: true,
        newCommandTimeout: 240,
    },
];
```

**Comment by mykola-mokhnach** [comment]
The attached log looks fine to me. the session gets successfully created and then deleted.

**Comment by mykola-mokhnach** [comment]
Try to enable ios logging. It might be that xctest cannot properly start the app.

**Comment by lucialuzuriaga** [comment]
> Try to enable ios logging. It might be that xctest cannot properly start the app.

@mykola-mokhnach here are the logs from today after including iOS logs capability. Still getting the same connection refused message on first attempt, and the app shutting down on the second one.

[appiumios.txt](https://github.com/appium/appium/files/3059152/appiumios.txt)

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
