### ISSUE TITLE
inspector cause app to crash using latest appium

### ISSUE THREAD

**Issue by KevinChan168** [appium/appium#12451]
## The problem

recently I try appium to do some automated tests,  I find a bug

## Details

 1. install wechat on iphone7 (https://itunes.apple.com/cn/app/wechat/id414478124?l=en)
 2. register a account and follow an official account  : pinduoduo   then stick this account on top of the chats page
 3. install and start latest appium server ，run inspector with capabilities:

{
  "platformName": "iOS",
  "platformVersion": "10.2",
  "bundleId": "com.tencent.xin",
  "deviceName": "iphone7",
  "automationName": "XCUITest",
  "udid": "943cd37cfed87375707c0310be6d12eda17a41f8",
  "noReset": "True",
  "newCommandTimeout": "2000"
}

4.  locate the ‘拼多多’ Chinese character， and click ‘tap’ on the right， then wechat app crash on iphone and can't continue test

## Environment

* Appium version that exhibits the issue: 1.12.1
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: Mac OS 10.14.4
* Node.js version (unless using Appium.app|exe): v10.15.3
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: ios 10.2
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: Appium.app
* Xcode version：10.1 (10B61)

## Link to Appium logs

https://gist.github.com/KevinChan168/7a75b850b5d8d6a868ad07a433388a54.js

## Code To Reproduce Issue [ Good To Have ]

here these codes can reproduce the issue:
desired_caps=
{
  "platformName": "iOS",
  "platformVersion": "10.2",
  "bundleId": "com.tencent.xin",
  "deviceName": "iphone7",
  "automationName": "XCUITest",
  "udid": "943cd37cfed87375707c0310be6d12eda17a41f8",
  "noReset": "True",
  "newCommandTimeout": "2000"
}

driver = webdriver.Remote("http://127.0.0.1:4723/wd/hub",desired_caps)
element = driver.find_element_by_accessibility_id('拼多多')
element.click()
element = driver.find_element_by_accessibility_id('进入商城')
element.click()

here the crash happened after 2nd click, which could possibly be the root cause.
I think inspector did something similar to click action

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing to do there from Appium side. Consider reporting the issue to Apple to to application developers
