### ISSUE TITLE
Selenium parallel tests Fail on grid with a single android device

### ISSUE THREAD

**Issue by MaheshGooner** [appium/appium#12456]
## The problem

Unable to run parallel tests on grid android device.

> Caused by: org.openqa.selenium.WebDriverException: Session [3009fb4b-1e45-43f5-a132-01a70e2578c5] was terminated due to BROWSER_TIMEOUT
> 
> org.openqa.selenium.NoSuchSessionException: A session is either terminated or not started (WARNING: The server did not provide any stacktrace information)
>     Command duration or timeout: 0 milliseconds

The tests work perfectly alright when running chrome browsers locally or another device but the issue is only when running the tests on android device with appium in parallel. The tests on android pass if they are not run parallel.

## Environment

Appium - 1.10.1
selenium - 3.141.59

## Logs
 

> org.openqa.selenium.NoSuchSessionException: A session is either terminated or not started (WARNING: The server did not provide any stacktrace information)
>     Command duration or timeout: 0 milliseconds
>     Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
>     System info: host: 'mahesh-thuma', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-47-generic', java.version: '1.8.0_181'
>     Driver info: org.openqa.selenium.remote.RemoteWebDriver
>     Capabilities {CONFIG_UUID: ef95579f-9c49-4e3a-92a0-588..., automationName: UiAutomator, browserName: Chrome, databaseEnabled: false, desired: {CONFIG_UUID: ef95579f-9c49-4e3a-92a0-588..., automationName: UiAutomator, browserName: Chrome, device: xxxx, deviceName: xxxx, platform: ANDROID, platformName: android}, device: xxxx, deviceManufacturer: Google, deviceModel: Pixel 2, deviceName: xxxx, deviceScreenSize: 1080x1920, deviceUDID: HT8611A00992, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, platform: ANDROID, platformName: ANDROID, platformVersion: 9, takesScreenshot: true, warnings: {}, webStorageEnabled: false}
>     Session ID: 3009fb4b-1e45-43f5-a132-01a70e2578c5
>         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
>         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>         at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
>         at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
>         at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
>         at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
>         at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
>         at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
>         at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
>         at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
>         at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:35)
>         at org.openqa.selenium.remote.RemoteLogs.getRemoteEntries(RemoteLogs.java:81)
>         at org.openqa.selenium.remote.RemoteLogs.get(RemoteLogs.java:77)
>         at shared.MockServerService.getLogs(MockServerService.kt:74)
>         at shared.MockServerService.openWidgetPage(MockServerService.kt:33)
>         at shared.MockServerService.openWidgetPage$default(MockServerService.kt:27)
>         at widgets.standings.StepDefs.iNavigateToTheStandingsWidget(StepDefs.kt:25)
>         at ✽.When I navigate to the Standings widget(widgets/standings/Standings.feature:7)
> 
>     org.openqa.selenium.WebDriverException: Session [3009fb4b-1e45-43f5-a132-01a70e2578c5] was terminated due to BROWSER_TIMEOUT

## Node configuration
```
{
 "capabilities": [
     {
 "deviceName": "xxxx",
 "platformName": "Android",
 "version": "9.1",
 "browserName":"Chrome",
 "maxInstances": 5
     }
 ],
 "configuration": {
 "cleanUpCycle": 2000,
 "timeout": 30000,
 "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
 "host": "xx.xx.xx.xx",
 "port": 4728,
 "maxSession": 5,
 "register": true,
 "url": "http://xx.xx.xx.xx:5555/wd/hub",
 "registerCycle": 5000,
 "hubPort": 5555,
 "hubHost": "xx.xx.xx.xx"
 }
}
```
![grid](https://user-images.githubusercontent.com/18375888/55722585-9cdff900-59fe-11e9-90c0-dbb090622ff6.png)

**Comment by ochubey** [comment]
Could you please also share the command that creates instance of Appium Server (node for Selenium Grid)?

**Comment by MaheshGooner** [comment]
`appium --session-override --nodeconfig path/nodeconfig.json -p 4728 --bootstrap-port 2255` is the command.

So any android device would only handle one session at a time ? if that's the limitation my tests work alright. Also to conclude inorder to have parallel tests i need more devices on my grid ?

**Comment by mykola-mokhnach** [comment]
> So any android device would only handle one session at a time ?

Yes, this is the limitation of bible chrome driver. You must execute multiple emulators or have multiple real devices to run parallel tests

**Comment by MaheshGooner** [comment]
Thank you @mykola-mokhnach @ochubey

**Comment by MaheshGooner** [comment]
@mykola-mokhnach @ochubey i got one question reagarding parallel testing on multiple devices. I have couple of android devices under a grid. How do i pool these devices and put common capabilties such that any tests would pick the device which is not in use.

For Ex: a grid with 2 android devices
Repo 1- > triggers tests on android -> picks device 1
Repo 2=> simultaneously triggers tests on android. Then this should pick device 2 as it currently free.

is this handled by grid inbuilt ? if yes how do i manage webdriver capabilities for this setup ?
