### ISSUE TITLE
An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: "Command 'Scripts/bootstrap.sh -d' exited with code 1".

### ISSUE THREAD

**Issue by mmomin** [appium/appium#12457]
## The problem

I am getting this error code and have tried uninstalling carthage and installing it again, I saw multiple issues with this, but none were solved and most are getting duplicated. Is there any solution?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.12.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

**Comment by mykola-mokhnach** [comment]
The provided details are not enough to find a solution. Add -x option to  bootstrap.sh command line and attach the debugging output

**Comment by mmomin** [comment]
WebDriverAgent qtd2168$ ./Scripts/bootstrap.sh -d
Fetching dependencies
*** Checking out CocoaAsyncSocket at "7.6.3"
*** Checking out RoutingHTTPServer at "v1.0.1"
```*** Checking out YYCache at "1.0.5"
Failed to check out repository into /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer: Could not create working directory (Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “RoutingHTTPServer” in the folder “Checkouts”." UserInfo={NSFilePath=/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer, NSUnderlyingError=0x7ff554d6f380 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}})```

**Comment by mmomin** [comment]
@mykola-mokhnach 

WebDriverAgent qtd2168$ ./Scripts/bootstrap.sh -d
Fetching dependencies
*** Checking out CocoaAsyncSocket at "7.6.3"
*** Checking out RoutingHTTPServer at "v1.0.1"
*** Checking out YYCache at "1.0.5"
Failed to check out repository into /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer: Could not create working directory (Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “RoutingHTTPServer” in the folder “Checkouts”." UserInfo={NSFilePath=/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer, NSUnderlyingError=0x7ff554d6f380 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}})

**Comment by mykola-mokhnach** [comment]
What is exactly is unclear with the error message above?

**Comment by mmomin** [comment]
Appium is not launching and giving off the error code as my topic

**Comment by mykola-mokhnach** [comment]
have you tried to grant the asked permissions?

**Comment by mmomin** [comment]
how can I grant the permission to this particular file? Sorry not so much familiar with bash and terminal processes @mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
Kindly ask questions at Appium forum. This is the place for issues.
