### ISSUE TITLE
Require "automationName" for Android automation

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#12464]
## The problem

People who don't set the `automationName` capability for Android are being defaulted to using `UiAutomator1` which is an unsupported driver and uses legacy technology. I don't think we should wait until Appium 2.0 before changing this over.

My question is, should we:
* Make `automationName` a required capability for Android, and announce it will change now
* Make `UiAutomator2` the default capability, also announce it now so people have warning
* Just wait until Appium 2.0

**Comment by dpgraham** [comment]
Here's my proposition:

* (Android only) In Appium 1.13, warn users that Appium 1.14 the default will change to UiAutomator2 so that we can start getting users off of UiAutomator1 without bringing in a breaking change

e.g.: 

```
===============================================================
= ATTENTION: You have not set the "automationName" capability for this session. =
= For next minor version of Appium (1.14.0) "automationName" will default to UiAutomator2 =
= and next major version of Appium (2.0.0) "automationName" will be a required capability =
= For this session, the "automationName" capability will, by default, be set to "UiAutomator1" =
= (for more info visit http://some-shortened-url/info) =
===============================================================
```

* In Appium 1.13+, warn users that "automationName" will become a required capability for Appium 2.0 

e.g.:
```
===============================================================
= ATTENTION: You have not set the "automationName" capability for this session. =
= For next major version of Appium (2.0.0) "automationName" will be a required capability =
= For this session, the "automationName" capability will, by default, be set to "<default>"* =
= (for more info visit http://some-shortened-url/info) =
===============================================================
```

* default is UiAutomator1 for Appium 1.13; UiAutomator2 for Appium 1.14 (unless it's below the minimum UIA2 SDK level, fallback to UiAutomator1); XCUITestDriver for all IOS (unless it's below the minimum IOS version level, fallback to Instruments).

**Comment by dpgraham** [comment]
^ @mykola-mokhnach @imurchie @jlipps @Jonahss @KazuCocoa do you have any thoughts?

**Comment by imurchie** [comment]
I'm good with this, as we discussed. I think the message needs to be formatted such that it will fit into a standard terminal window (i.e., 80 chars).
```
================================================================================
= ATTENTION: You have not set the 'automationName' capability for this         =
= session.                                                                     =
= For next minor version of Appium (1.14.0) 'automationName' will default to   =
= UiAutomator2 and next major version of Appium (2.0.0) 'automationName' will  =
= be a required capability.                                                    =
= For this session, the 'automationName' capability will, by default, be set   =
= to 'UiAutomator1'.                                                           =
= If you wish to keep the current behavior for Appium 1.14 and beyond, please  =
= set the 'automationName' capability to 'UiAutomator1'. However, for best     =
= performance we recommend setting it to 'UiAutomator2' (for more info visit   =
= http://some-shortened-url/info).                                             =
================================================================================
```

**Comment by KazuCocoa** [comment]
I also agree with making UA2 default, and showing the warning message 👍

**Comment by dpgraham** [comment]
Merged
