### ISSUE TITLE
NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

### ISSUE THREAD

**Issue by wangfuwen000** [appium/appium#12460]
## The problem
**the code below as:**

```
desired_caps = {
"deviceName": "860BCMN22FF2",
                "app": app,
                "noReset": True,
                "appWaitPackage": "com.android.packageinstaller, c.l.a, com.samsung.android.packageinstaller, com.google.android.packageinstaller",
                "appWaitActivity":"com.android.packageinstaller.permission.ui.GrantPermissionsActivity, com.example.TestPlugin.MyActivity",
                "appWaitDuration": 30000,
                "newCommandTimeout": 200,
                "platformVersion": "7.0",
                "autoGrantPermissions": True,
                "platformName": "Android"}

driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
el_installOp = driver.find_element_by_id('c.l.a:id/button2')
 print(el_installOp)


```
then run,  
```

Traceback (most recent call last):
  File "/Users/admin/Documents/appiumAutotest/demo/open_app.py", line 88, in <module>
    el_installOp = driver.find_element_by_id('c.l.a:id/button2')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 370, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/appium/webdriver/webdriver.py", line 219, in find_element
    'value': value})['value']
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 331, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/appium/webdriver/errorhandler.py", line 29, in check_response
    raise wde
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

```

## Environment

* Appium version: 1.10.1

## Details

if app target is 22,  did not exhibit the issue
if app target is 28,    the issue happen

## Link to Appium logs
 Calling AppiumDriver.findElement() with args: ["id","c.l.a:id/button2","91ce3c58-5a90-49ea-912c-6f2d2a54aea6"]
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Waiting up to 0 ms for condition
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"c.l.a:id/button2","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"c.l.a:id/button2","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'c.l.a:id/button2' using 'ID' with the contextId: '' multiple: false
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=c.l.a:id/button2]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Failed to locate element. Clearing Accessibility cache and retrying.
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'c.l.a:id/button2' using 'ID' with the contextId: '' multiple: false
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=c.l.a:id/button2]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":7,"value":"No element found"}
[AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Matched JSONWP error code 7 to NoSuchElementError
[W3C (91ce3c58)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[W3C (91ce3c58)]     at AndroidDriver.helpers.findElOrEls (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-driver/lib/commands/find.js:75:11)
[W3C (91ce3c58)]     at process._tickCallback (internal/process/next_tick.js:68:7)
[HTTP] <-- POST /wd/hub/session/91ce3c58-5a90-49ea-912c-6f2d2a54aea6/element 404 8842 ms - 483
[HTTP] 
[Logcat] Logcat terminated with code 1, signal n

**Comment by mykola-mokhnach** [comment]
UiAutomator1 is obsolete for Android 6+. Switch to UIA2/Espresso. Closed as not an issue.
