### ISSUE TITLE
android: screenshot saves the area behind device buttons

### ISSUE THREAD

**Issue by DudaGod** [appium/appium#12467]
## The problem

The area behind device buttons appears on screenshot as a white rectangle. Is this expected behavior? I expect to see in the screenshot only the visible part - viewport.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.12.1
* Node.js version (unless using Appium.app|exe): 8.6.0
* Npm package manager: 6.2.0
* Mobile platform/version under test: Android 6.0
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: cli

## Link to Appium logs

https://gist.github.com/DudaGod/2de9459e20526aace7610ce90def7951

## Code To Reproduce Issue [ Good To Have ]

```js
'use strict';

const webdriverio = require('webdriverio');

const browser = webdriverio.remote({
    host: 'localhost',
    port: '4444',
    path: '/wd/hub',
    desiredCapabilities: {
        browserName: 'chrome',
        platformName: 'Android',
        platformVersion: '6.0',
        deviceName: 'Android Emulator',
        showChromedriverLog: true
    }
});

(async function () {
    try {
        await browser.init();
        await browser.url('https://github.com');
        await browser.saveScreenshot('image.png');
    } catch (err) {
        console.log('ERROR:', err);
    } finally {
        await browser.end();
    }
})();
```

saved screenshot - 
![image png 2019-04-10 10-24-09](https://user-images.githubusercontent.com/5900697/55859485-da699100-5b7a-11e9-82a7-838710e92303.png)

**Comment by mykola-mokhnach** [comment]
This screenshot is returned by ChromeDriver. Appium just acts as a proxy. Please report the issue to Google.
