### ISSUE TITLE
Unable to Turn Off Console Logs in Appium iOS even after setting all Capabilities

### ISSUE THREAD

**Issue by ankit9289** [appium/appium#12466]
## **The problem**

Unable to Turn Off Console Logs in Appium iOS even after setting all Capabilities

## **Environment**

* Appium version - 1.11.0-beta.3
* Desktop OS/version used to run Appium: Mac OS
* Mobile platform/version under test: 12.1
* Real device or emulator/simulator: Simulators

## **Capabilities - Appium Service** 

        AppiumServiceBuilder builder = new AppiumServiceBuilder();
        builder.usingPort(Integer.parseInt(port));
        builder.withIPAddress(GlobalData.APPIUM_LOCAL_MACHINE_IP);
        builder.withArgument(GeneralServerFlag.LOG_LEVEL, LogLevel.ERR.toString());
        AppiumDriverLocalService service = AppiumDriverLocalService.buildService(builder);
        service.start();

## **Capabilities - iOS Driver** 

driverCapabilities.setCapability(MobileCapabilityType.UDID, deviceID);
        driverCapabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 600);
        driverCapabilities.setCapability(MobileCapabilityType.DEVICE_NAME, deviceName);
        driverCapabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, MobilePlatform.IOS);
        driverCapabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, platformVersion);
        driverCapabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.IOS_XCUI_TEST);
        driverCapabilities.setCapability(MobileCapabilityType.NO_RESET, true);
        driverCapabilities.setCapability(IOSMobileCapabilityType.SHOW_XCODE_LOG, false);
        driverCapabilities.setCapability(IOSMobileCapabilityType.USE_NEW_WDA, false);
        driverCapabilities.setCapability(IOSMobileCapabilityType.BUNDLE_ID, GlobalData.APP_BUNDLE_ID);
        driverCapabilities.setCapability(IOSMobileCapabilityType.WDA_LOCAL_PORT, wdaPort);

## **Sample Logs That are Coming :** 
[Xcode]     t =    27.10s Open *****
[Xcode] 
[Xcode]     t =    27.10s     Launch *****
[Xcode] 
[Xcode]     t =    27.10s         Terminate *****
[Xcode] 
[Xcode]     t =    28.15s         Wait for accessibility to load
[Xcode] 
[Xcode]     t =    28.25s         Wait for ***** to idle
[Xcode] 
[Xcode]     t =    30.84s Find the Application *****'
[Xcode] 
[Xcode]     t =    30.84s     Snapshot accessibility hierarchy for app with pid 85379
[Xcode] 
[Xcode]     t =    31.38s Find the Application '*****'
[Xcode] 
[Xcode]     t =    31.39s     Snapshot accessibility hierarchy for app with pid 85379
[Xcode] 
[Xcode]     t =    31.72s Get all elements bound by accessibility element for: Elements matching predicate '"*****" IN identifiers'
[Xcode] 
[Xcode]     t =    31.72s     Snapshot accessibility hierarchy for app with pid 85379
[Xcode] 
[Xcode]     t =    32.15s     Find: Descendants matching type Any
[Xcode] 
[Xcode]     t =    32.15s     Find: Elements matching predicate '"Production" IN identifiers'

**Comment by imurchie** [comment]
Xcode logs show up after there has been an error. Without the full logs it is impossible to tell what is causing the logging to be turned on.

**Comment by mykola-mokhnach** [comment]
In the recent appium@bete Xcode logs will never be shown if `IOSMobileCapabilityType.SHOW_XCODE_LOG` is explicitly set to `false`
