### ISSUE TITLE
Can't close the app with swipe

### ISSUE THREAD

**Issue by blackmar1987** [appium/appium#12479]
## The problem

I want to close the app by simple swipe. I used longpress with moveTo from element to element. But in result the app layout is going up very slow and then just turned back.
I tried to swipe from from element to point, from point to point - nothing heapens.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe):  10.15.0
* Mobile platform/version under test: Android 9.0
* Real device or emulator/simulator: Nexus 5X API 28

## Code To Reproduce Issue [ Good To Have ]
https://github.com/blackmar1987/CloseAppWithSwipe

**Comment by mykola-mokhnach** [comment]
Kindly use Appium forum for questions. 

BTW, W3C actions usage gives more fine-grained control over gestures. Check https://appiumpro.com/editions/29 for more details.
