### ISSUE TITLE
Disable automatic translation on website

### ISSUE THREAD

**Issue by ArthurAttout** [appium/appium#12478]
[appium.io](http://appium.io/) website seems to use an automatic translation tool.

This is an absolute pain to read (on my machine it's translated in french, full of mistakes and horrid sentences), **and there is no way to switch the locale.** 

This should be fixed, because it's a tremendously bad advertising, if someone is visiting the website first. 

![image](https://user-images.githubusercontent.com/18170545/55952945-1e33c780-5c5b-11e9-9935-27b5d1fb13c0.png)

**Comment by dpgraham** [comment]
Agreed. @jlipps do you know how to disable this?

**Comment by KazuCocoa** [comment]
link: https://github.com/appium/appium.io/issues/165

**Comment by ArthurAttout** [comment]
Still no move about this ?

**Comment by KazuCocoa** [comment]
Merged https://github.com/appium/appium.io/pull/233
We hope this will fix this...
