### ISSUE TITLE
Scrolling issue in appium

### ISSUE THREAD

**Issue by abhi2717** [appium/appium#12477]
- I want to select DOB, in which have to scroll on the lists of the year, month as well as day. for that, i am unable to make it through UI scrollable class.
- Below i have attached the screenshot, please give a suggestion.
![12345](https://user-images.githubusercontent.com/43001077/55946192-dbc5b700-5c69-11e9-88bf-8be6b61e793f.png)

**Comment by mykola-mokhnach** [comment]
Please use Appium forum for questions
