### ISSUE TITLE
Appium v1.13.0-beta.2 - WebDriverAgent Build Error

### ISSUE THREAD

**Issue by NirBY** [appium/appium#12471]
## The problem

When try to run the command:
xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' test

## Environment

* Appium version (or git revision) that exhibits the issue: v1.13.0-beta.2
* Last Appium version that did not exhibit the issue (if applicable): 1.12.1
* Desktop OS/version used to run Appium: MAC Mojave
* Node.js version (unless using Appium.app|exe): 10.15.3
* Mobile platform/version under test: IOS 12
* Real device

## Details

When manually building WebDriverAgent I am getting error.

> 'RoutingHTTPServer/RoutingConnection.h' file not found

## Link to Appium logs

https://gist.github.com/NirBY/a3d591f4ff0a53710c75c158a03ae9d5

## Code To Reproduce Issue [ Good To Have ]

xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' test

## Workaround
I have finally copy the last Appium desktop WebDriverAgent code to Appium folder.
Taken from: 
/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent

Into:
/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent

**Comment by mykola-mokhnach** [comment]
This is usually the case if carthage bootstraping hasn't been done or failed. Please attach the full log and make sure all carthage dependencies are in place.

**Comment by vjmaiky** [comment]
had something similar; i updated carthage and it worked after.
