### ISSUE TITLE
appium on indows server 2019

### ISSUE THREAD

**Issue by mrjmCyber** [appium/appium#12472]
im running latest version Appium Desktop  on  WIndows Server2109.
trying to test an App installed On Bluestacks.
ANDROID_HOME and JAVA_HOME Variables Are set.

the Capabilites Works Fine in Local Windows. but on Windows Server When i press Start Session the error message says:
" An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\Administrator\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 shell pm list packages com.sibche.aspardproject.app' exited with code 1'; Stderr: 'error: closed'; Code: '1' "

using cmd the "adb devices" command show the bluestack. but appium can not connect. any help will be appriciated

**Comment by mykola-mokhnach** [comment]
Please fill out the issue reporting form properly and attach the full server log

**Comment by mrjmCyber** [comment]
it seems that bluestack4 added new feature called "enable adb debuging" and its in a beta test and its disabled by default. 
i should enable this feature before trying to use appium. 
it is recomanded not use bluestacks4 because of this issue, it cause some unexpected and unreproducible crashes .
