### ISSUE TITLE
Appium server 1.12.1 - getScreenshot fails for Android 5  and 6

### ISSUE THREAD

**Issue by lubshilk** [appium/appium#12470]
## The problem

After updating to appium server 1.12.1 getScreenshot() fails:
on Android 5 tester (Samsung) - Error: ESOCKETTIMEDOUT
on Android 6 tester (LG) - io.appium.uiautomator2.common.exceptions.TakeScreenshotException: Failed to capture a screenshot. Does the current view have 'secure' flag set?

The same problem with Appium server 1.13.0-beta.2

The same worked with no problems until upgrade

## Environment

* Appium version (or git revision) that exhibits the issue: 1.12.1 and above
* Last Appium version that did not exhibit the issue (if applicable): 1.11.1
* Desktop OS/version used to run Appium: MAC Mojave 
* Node.js version (unless using Appium.app|exe): 10.15.3
* Mobile platform/version under test: Android 5 and 6
* Real device

## Link to Appium logs
For Android 5 https://gist.github.com/lubshilk/5b9a4dc9b38f54582088cefa00b9875c
For Android 6 https://gist.github.com/lubshilk/94c9bd2fba4e9544a98ffb31c509a0db

## Code To Reproduce Issue [ Good To Have ]

String source = ((TakesScreenshot) new Augmenter().augment(driver)).getScreenshotAs(OutputType.BASE64);

**Comment by mykola-mokhnach** [comment]
Is the device set to HighDPI mode? Are you able to take the screenshot of the destination view manually using `adb shell screencap -p` command?

**Comment by lubshilk** [comment]
HighDPI mode - no
The command works

**Comment by mykola-mokhnach** [comment]
The original code only switches to that branch if DPI destiny is not the default one (aka MEDIUM): https://github.com/appium/appium-uiautomator2-server/blob/4985d5734443ae7df81808fc1b5af58e5971bb98/app/src/main/java/io/appium/uiautomator2/utils/ScreenshotHelper.java#L93

And the exception above is thrown if no data is retrieved from `screencap -p` output. 

That is why it would be interesting to know why both conditions pass.

**Comment by lubshilk** [comment]
Really strange

For Android 6 (LG) density info shows defaultMode 1:
> w-cr8:~ cellactqa$ adb -s LGH815f8aa336c shell dumpsys display|grep -i density
>   DisplayDeviceInfo{"Built-in Screen": uniqueId="local:0", 1440 x 2560, modeId 1, defaultModeId 1, supportedModes [{id=1, width=1440, height=2560, fps=60.0}], density 640, 537.882 x 537.388 dpi, appVsyncOff 0, presDeadline 17666667, touch INTERNAL, rotation 0, type BUILT_IN, state ON, FLAG_DEFAULT_DISPLAY, FLAG_ROTATES_WITH_CONTENT, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
>     mBaseDisplayInfo=DisplayInfo{"Built-in Screen", uniqueId "local:0", app 1440 x 2560, real 1440 x 2560, largest app 1440 x 2560, smallest app 1440 x 2560, mode 1, defaultMode 1, modes [{id=1, width=1440, height=2560, fps=60.0}], rotation 0, density 640 (537.882 x 537.388) dpi, layerStack 0, appVsyncOff 0, presDeadline 17666667, type BUILT_IN, state ON, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
>     mOverrideDisplayInfo=DisplayInfo{"Built-in Screen", uniqueId "local:0", app 1440 x 2392, real 1440 x 2560, largest app 2392 x 2296, smallest app 1440 x 1344, mode 1, defaultMode 1, modes [{id=1, width=1440, height=2560, fps=60.0}], rotation 0, density 640 (537.882 x 537.388) dpi, layerStack 0, appVsyncOff 0, presDeadline 17666667, type BUILT_IN, state ON, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}

When running the command there is an output:
![image](https://user-images.githubusercontent.com/20837714/55953039-be8dea00-5c63-11e9-9834-0259e57191be.png)

When running from Appium exception reported on empty output (exactly as you mentioned)
> An unknown server-side error occurred while processing the command. Original error: io.appium.uiautomator2.common.exceptions.TakeScreenshotException: Failed to capture a screenshot. Does the current view have 'secure' flag set? at io.appium.uiautomator2.utils.ScreenshotHelper.takeDeviceScreenshot(ScreenshotHelper.java:104) at... 

Where is the problem?

**Comment by mykola-mokhnach** [comment]
>  type BUILT_IN, state ON, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS

Perhaps the presence of this flag protects the view from being screenshoted

**Comment by lubshilk** [comment]
Re-run on the same tester the same test but with Appium 1.11.1 - no problem with screenshots.
Appium log: https://gist.github.com/lubshilk/c046988d92424f23f77b7a12fe821bb4

**Comment by mykola-mokhnach** [comment]
I think it worked before because in earlier Android version there was a bug in takeScreenshot API which was permitting screenshots even if FLAG_SECURE was set. I could add a fallback to the current algorithm, however such solution looks ugly to me. The right approach would be to remove FLAG_SECURE in the app.

**Comment by lubshilk** [comment]
Hoped it will work with Appium v1.13.0-beta.3, but still the same problem
When the fix will be issued?

BTW, not sure FLAG_SECURE is a cause
On a device with Android 9 there is not problem with screenshot
It's density
> $adb -s HT7AG1A02420 shell dumpsys display|grep -i density
>   DisplayDeviceInfo{"Built-in Screen": uniqueId="local:0", 1080 x 1920, modeId 1, defaultModeId 1, supportedModes [{id=1, width=1080, height=1920, fps=60.000004}], colorMode 0, supportedColorModes [0, 7, 9], HdrCapabilities android.view.Display$HdrCapabilities@413e3a39, density 420, 442.451 x 443.345 dpi, appVsyncOff 2000000, presDeadline 11666666, touch INTERNAL, rotation 0, type BUILT_IN, state ON, FLAG_DEFAULT_DISPLAY, FLAG_ROTATES_WITH_CONTENT, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
>       PhysicalDisplayInfo{1080 x 1920, 60.000004 fps, density 2.625, 442.451 x 443.345 dpi, secure true, appVsyncOffset 2000000, bufferDeadline 11666666}
>     mBaseDisplayInfo=DisplayInfo{"Built-in Screen", uniqueId "local:0", app 1080 x 1920, real 1080 x 1920, largest app 1080 x 1920, smallest app 1080 x 1920, mode 1, defaultMode 1, modes [{id=1, width=1080, height=1920, fps=60.000004}], colorMode 0, supportedColorModes [0, 7, 9], hdrCapabilities android.view.Display$HdrCapabilities@413e3a39, rotation 0, density 420 (442.451 x 443.345) dpi, layerStack 0, appVsyncOff 2000000, presDeadline 11666666, type BUILT_IN, state ON, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS, removeMode 0}
>     mOverrideDisplayInfo=DisplayInfo{"Built-in Screen", uniqueId "local:0", app 1080 x 1794, real 1080 x 1920, largest app 1794 x 1731, smallest app 1080 x 1017, mode 1, defaultMode 1, modes [{id=1, width=1080, height=1920, fps=60.000004}], colorMode 0, supportedColorModes [0, 7, 9], hdrCapabilities android.view.Display$HdrCapabilities@413e3a39, rotation 0, density 420 (442.451 x 443.345) dpi, layerStack 0, appVsyncOff 2000000, presDeadline 11666666, type BUILT_IN, state ON, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS, removeMode 0}

**Comment by mykola-mokhnach** [comment]
The workaround has been published in appium@beta
