### ISSUE TITLE
Unable to perform swipe action on iOS 12 Appium version 1.9.1

### ISSUE THREAD

**Issue by amit-punjabi** [appium/appium#12474]
## The problem

Unable to perform swipe action using Touch action on iOS 12 Appium version 1.9.1. The swipe is performed successfully on iOS 11 Appium version 1.7.0

:red_circle: NOTE- The wait of 1200 ms has already been used as mentioned [here](https://github.com/appium/appium/issues/11181#issuecomment-412884102) 

## Environment

* Appium version (or git revision) that exhibits the issue: v1.9.1
* Last Appium version that did not exhibit the issue (if applicable): v1.7.0
* Mobile platform/version under test: iPhone 6S + OS v12
* Real device or emulator/simulator: Real device

## Link to Appium logs

[Issue_swipe_passed_appium.log](https://gist.github.com/amit-punjabi/b078f4f8ca785dad013b03cecf58ad7a)

[Issue_swipe_failed_appium.log](https://gist.github.com/amit-punjabi/e8c4690a639e6a05b2d3ce25361c68e3)

## Code To Reproduce Issue

[Swipe_ios.java](https://gist.github.com/amit-punjabi/d99d6f9c904f40398937a9183d3c6ef2)

**Comment by mykola-mokhnach** [comment]
Appium 1.9.1 is out of date. Please use the most recent version
