### ISSUE TITLE
WebDriverException while trying to rotate emulator to Landscape

### ISSUE THREAD

**Issue by DmitriyKapeliukh** [appium/appium#12488]
**The problem**

The Appium through exception when I try to rotate emulator.

**Environment**

* Appium version (or git revision) that exhibits the issue: Version 1.12.1 (1.12.1.20190404.1)
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS Mojave 10.14.4
* Node.js version (unless using Appium.app|exe): 11.11.0
* Npm or Yarn package manager:
* Mobile platform/version under test: Android 8.0
* Real device or emulator/simulator: Emulator Pixel XL
* Appium CLI or Appium.app|exe:

**Details**

```
org.openqa.selenium.WebDriverException: The following error occurred: An unknown server-side error occurred while processing the command. Original error: Set the orientation, but app refused to rotate.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Dmytro-Kapeliukh.wnb', ip: 'fe80:0:0:0:cc1:134:c36f:4aed%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.4', java.version: '1.8.0_171'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {app: /Users/d.kapeliukh/RunSimul..., appPackage: com.mypackage, autoGrantPermissions: true, autoLaunch: true, automationName: UiAutomator2, databaseEnabled: false, desired: {app: /Users/d.kapeliukh/RunSimul..., autoGrantPermissions: true, autoLaunch: true, automationName: UiAutomator2, deviceName: Pixel_XL_API_26, fullReset: false, newCommandTimeout: 15000, noReset: true, platformName: android, platformVersion: 8.0, unicodeKeyboard: true}, deviceApiLevel: 26, deviceManufacturer: Google, deviceModel: Android SDK built for x86, deviceName: emulator-5554, deviceScreenDensity: 560, deviceScreenSize: 1440x2560, deviceUDID: emulator-5554, fullReset: false, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, newCommandTimeout: 15000, noReset: true, pixelRatio: 3.5, platform: LINUX, platformName: Android, platformVersion: 8.0.0, statBarHeight: 84, takesScreenshot: true, unicodeKeyboard: true, viewportRect: {height: 2308, left: 0, top: 84, width: 1440}, warnings: {}, webStorageEnabled: false}
```

**Link to Appium logs**

[Appium logs](https://www.dropbox.com/s/knvsd4r4vt56332/appium-server-logs.txt?dl=0)

**Code To Reproduce Issue**

```
public static void rotate(AppiumDriver driver, ScreenOrientation orientation) {
        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        driver.rotate(orientation);
    }
```

**Capabilities**

```
<appium.platformName>Android</appium.platformName>
<appium.platformVersion>8.0</appium.platformVersion>
<appium.deviceName>Pixel_XL_API_26</appium.deviceName>
<appium.autoGrantPermissions>true</appium.autoGrantPermissions>
<appium.automationName>UiAutomator2</appium.automationName>
<appium.autoLaunch>true</appium.autoLaunch>
<appium.fullReset>false</appium.fullReset>
<appium.noReset>true</appium.noReset>
<appium.unicodeKeyboard>true</appium.unicodeKeyboard>
<unicodeKeyboard>true</unicodeKeyboard>
<resetKeyboard>true</resetKeyboard>
<serenity.timeout>15000</serenity.timeout>
                                <webdriver.timeouts.implicitlywait>15000</webdriver.timeouts.implicitlywait>
<webdriver.wait.for.timeout>15000</webdriver.wait.for.timeout>
<appium.newCommandTimeout>15000</appium.newCommandTimeout>
```

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium-uiautomator2-server/blob/4d3ac64025296bd314709df98ba8071364a9c210/app/src/main/java/io/appium/uiautomator2/handler/RotateScreen.java#L140

I don't think this a problem in Appium, but rather the application under test, because such exception is only thrown if the screen orientation is still the same after we tried to change it once

**Comment by DmitriyKapeliukh** [comment]
> https://github.com/appium/appium-uiautomator2-server/blob/4d3ac64025296bd314709df98ba8071364a9c210/app/src/main/java/io/appium/uiautomator2/handler/RotateScreen.java#L140
> 
> I don't think this a problem in Appium, but rather the application under test, because such exception is only thrown if the screen orientation is still the same after we tried to change it once

I see that the application made the rotation and instantly switch rotation back. So that way I got:

```
if (current != desired) {
            return new AppiumResponse(getSessionId(request), WDStatus.UNKNOWN_ERROR, "Set the orientation, but app refused to rotate.");
        }
```

But I want a find the solution to that problem. Has no one ever encountered this problem?

**Comment by mykola-mokhnach** [comment]
Fix the application under test?

**Comment by DmitriyKapeliukh** [comment]
> Fix the application under test?

```
You might have the right. Appium logs say:
Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: 500 - {"sessionId":"b0008422-5b03-4ba3-b3e5-aab8e2bea421","status":13,"value":"Set the orientation, but app refused to rotate."}
```

The are some setting in the android app to allow rotation access?

**Comment by DmitriyKapeliukh** [comment]
I've found the root cause of that issue.
The application what you have to test should have the property:
`android:screenOrientation="fullUser"` in the **AndriodManifest.xml**
