### ISSUE TITLE
where can find button_name for press_button() method

### ISSUE THREAD

**Issue by alexzoo** [appium/appium#12487]
## The problem
In documentation webdriver.py says:

def press_button(self, button_name)

Sends a physical button name to the device to simulate the user pressing. iOS only.
Possible button names can be found in https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Categories/XCUIDevice%2BFBHelpers.h

but there is nothing about button_name

**Comment by KazuCocoa** [comment]
```
buttonName One of the supported button names: volumeUp (real devices only), volumeDown (real device only), home
```
https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Categories/XCUIDevice%2BFBHelpers.h#L90 is. You can get the list as the error message.

The command wraps https://github.com/appium/appium/blob/master/docs/en/commands/mobile-command.md . You can also find it there. (Will add it in the doc)
