### ISSUE TITLE
FR: iOS: Video Record: make start video record asynchronous

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#12486]
## The problem
When we start ios test with video recording we have 10 sec (numbers can vary depending on hardware. current number from macMini i7 model 2019 while executing on 4 phones in parallel) delay while video starting. And after it continues test execution.

when we speak about 1 test it does not matter but e.g. with 100 tests it takes 100x10/60 = 17 min which increase our tests execution from 30 -> 45 min.

If it possible pls make it asynchronous.

## Environment
* Appium version (or git revision) that exhibits the issue: 1.13.0-beta.2
* Desktop OS/version used to run Appium: MacOS 10.14.4
* Mobile platform/version under test: iOS 12.2
* Real device or emulator/simulator: iPhone8

## Link to Appium logs
Example of logs from macBookPro:
2019-04-12 06:57:09:650 - [HTTP] --> POST /wd/hub/session/a6c21474-95d8-45d0-af4e-d9018db7285b/appium/start_recording_screen
....
2019-04-12 06:57:14:716 - [HTTP] <-- POST /wd/hub/session/a6c21474-95d8-45d0-af4e-d9018db7285b/appium/start_recording_screen 200 5065 ms - 12

## Code To Reproduce Issue
((IOSDriver) driver).startRecordingScreen(
                    new IOSStartScreenRecordingOptions()
                            .withFps(30));

**Comment by mykola-mokhnach** [comment]
I think this is the main showstopper: https://github.com/appium/appium-xcuitest-driver/blob/273d9ce89de8c52afba015c40530040688f1f829/lib/commands/recordscreen.js#L76

We need some better feedback from ffmpeg to make sure the video recording has started. I'll check on what can be done

**Comment by mykola-mokhnach** [comment]
Can you also attach the full log with timestamps to see what takes the most of the time?

**Comment by mykola-mokhnach** [comment]
@amedvedjev I did some improvements in https://github.com/appium/appium-xcuitest-driver/pull/932. Could you please merge it to your local source and check if the performance is better? Logs are welcome.

Check https://appiumpro.com/editions/47 for more details about deployment from source

**Comment by amedvedjev** [comment]
@mykola-mokhnach here is Full log (without your changes yet): https://gist.github.com/amedvedjev/9d16e33458cd5d466dc4e9876e0ac0a0

**Comment by mykola-mokhnach** [comment]
The fix has been published in appium@beta
