### ISSUE TITLE
Is there any way to get information about current build using appium? 

### ISSUE THREAD

**Issue by sanyco92** [appium/appium#12490]
## The problem

Hello Everyone! It's not an issue, but I want to ask a question. Tried to ask the same on gitter, but didn't get an answer.

I'm using WebdriverIO + Appium. I want to use build information in reports after my autotests are finished for iOS/Android application. Currently, I'm using a link for "app" capability. Appium downloads the iOS application (zip archive with .app file for iOS Simulator) and automatically installs it on the iOS simulator. Is there any way to get the information about the current build, which is installed on the device with Appium after downloading the application? e.g. I need to get information which is available in Info.plist (in the .app folder), CFBundleShortVersionString and CFBundleVersion. The same I'll need for Android applications (.apk). In the appium logs, I see that after downloading the app by link, Appium unpacks it in some directory, and then it shows the bundle identifier of the application. Maybe it has some methods/commands/functions to retrieve this info from the app builds? Thanks in advance for your answers!

**Comment by mykola-mokhnach** [comment]
I don't think such information is available elsewhere. However on Android (if relaxed security is enabled) you could execute add shell and extract the necessary data for the installed package

**Comment by mykola-mokhnach** [comment]
There is also a possibility to parse system logs, but for that the relaxed security should be enabled as well.

**Comment by sanyco92** [comment]
I noticed that if I send the request to localhost:port/session/XXXXXXXXXXXXXXXXXXXXX/ I'm gettings the response with some information like:
```
{
  "value" : {
    "sessionId" : "2ACD0939-55D9-4107-9D26-04548FDC63A5",
    "capabilities" : {
      "device" : "ipad",
      "browserName" : "Project Name",
      "sdkVersion" : "12.1",
      "CFBundleIdentifier" : "com.projectName.projectBeta"
    }
  },
  "sessionId" : "2ACD0939-55D9-4107-9D26-04548FDC63A5",
  "status" : 0
}
```
Maybe there's some API to get other information about build? Or maybe it's possible to implement? It would be useful.

**Comment by amedvedjev** [comment]
+1 for this feature. Currently we parsing ipa and apk files ourselves.

**Comment by imurchie** [comment]
There are two commands that might be useful here.

The [status command](http://appium.io/docs/en/commands/status/), which on iOS `driver.status()` gives:
```json
{
  "build": {
    "version": "2.111.0"
  },
  "wda": {
    "state": "success",
    "os": {
      "name": "iOS",
      "version": "12.1",
      "sdkVersion": "12.0"
    },
    "ios": {
      "simulatorVersion": "12.1",
      "ip": "192.168.0.25"
    },
    "build": {
      "upgradedAt": "1554211383182",
      "time": "Apr 10 2019 13:43:05",
      "productBundleIdentifier": "com.facebook.WebDriverAgentRunner"
    }
  }
}
```

And the [session capabilities command](http://appium.io/docs/en/commands/session/get/), which on iOS `driver.sessionCapabilities()` gives:
```json
{
  "udid": "1C7AB8B9-94C3-4806-86D7-77C13B483902",
  "app": "/Users/isaac/code/appium-xcuitest-driver/node_modules/ios-uicatalog/build/Release-iphonesimulator/UICatalog-iphonesimulator.app",
  "platformName": "iOS",
  "platformVersion": "12.1",
  "deviceName": "iPhone 6",
  "automationName": "XCUITest",
  "noReset": true,
  "maxTypingFrequency": 30,
  "clearSystemFiles": true,
  "showXcodeLog": false,
  "wdaLaunchTimeout": 240000,
  "wdaConnectionTimeout": 480000,
  "device": "iphone",
  "browserName": "UICatalog",
  "sdkVersion": "12.1",
  "CFBundleIdentifier": "com.example.apple-samplecode.UICatalog",
  "pixelRatio": 2,
  "statBarHeight": 23.4375,
  "viewportRect": {
    "left": 0,
    "top": 47,
    "width": 750,
    "height": 1287
  }
}
```

**Comment by amedvedjev** [comment]
driver.status(); - does not exist with Java client. PLS add.

**Comment by mykola-mokhnach** [comment]
Please create improvement requests in the corresponding client repositories
