### ISSUE TITLE
SendKeys skip characters of an an input string

### ISSUE THREAD

**Issue by Aby-pal** [appium/appium#12498]
I am facing the same issue as 'sendkeys' skip some characters of an input String. Some times entered a character twice and skipped others. It is happening dynamically, any character can be miss in each new run. Any suggestion would be helpful. Please refer the attached appium server logs file for the same.  Thanks.

Configuration
 Appium:- v1.12.1
Android Debug Bridge version 1.0.40
Version 28.0.2-5303910
[appium-server-logs.txt](https://github.com/appium/appium/files/3076504/appium-server-logs.txt)

**Comment by mykola-mokhnach** [comment]
UiAutomator1 is obsolete for Android 6+. Use UIA2 or Espresso
