### ISSUE TITLE
Docs: Broken link for espresso datamatcher

### ISSUE THREAD

**Issue by WillBrock** [appium/appium#12495]
## The problem

The following page can't be displayed on the website.

Writing & Running Tests -> Android -> Espresso Datamatcher Guide

http://appium.io/docs/en/writing-running-appium/android/espresso-datamatcher-selector/

It looks like the markdown file is there and it's also added in toc.js so I'm not sure if the docs need to be regenerated or something.

## Environment

Docs

**Comment by dpgraham** [comment]
I'll have a look thank you

**Comment by dpgraham** [comment]
Closed as fixed.
