### ISSUE TITLE
Issue in Maven - Syntax error

### ISSUE THREAD

**Issue by ssoni001** [appium/appium#12491]
I have created Maven project in Macbook.

I have created classes with package structure in src/main/java and src/test/java.

I am trying to access methods from src/test/java to src/main/java but i am getting syntax error.

What could be the possible reason. Please help.

Note : I have check with project cleanup but its not working.
Same code is working on windows machine.
Attaching screenshot for reference
<img width="1073" alt="Appium" src="https://user-images.githubusercontent.com/47416974/56033399-29155780-5d42-11e9-875a-610c95f55579.png">
.

**Comment by imurchie** [comment]
Perhaps a Maven forum would be better for this?

If you want to keep it in the Appium community, try https://discuss.appium.io/
