### ISSUE TITLE
Using appium-xcuitest-driver version from github

### ISSUE THREAD

**Issue by ddubtsov35** [appium/appium#12492]
I try use appium-xcuitest-driver latest version from github but have error.
I make all actions from https://appiumpro.com/editions/47, for example:

cd Work
git clone https://github.com/appium/appium.git
cd appium
npm install

cd ..
git clone https://github.com/appium/appium-xcuitest-driver.git
cd appium-xcuitest-driver
npm install
npm link
cd ..
cd appium
npm link appium-xcuitest-driver

all actions pass without errors, but after run test, i get error:

Unable to launch WebDriverAgent because of xcodebuild failure: Trying to use WebDriverAgent project at '/WORK/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj' but the file does not exist

**Comment by mykola-mokhnach** [comment]
WebDriverAgent is a submodule and requires additional arguments to be passed to git in order to be downloaded with the main project. 

Regarding error 65 - kindly use search. Usually this is an issue with developer signature (either unset or incorrectly configured)

Closed as duplicate
