### ISSUE TITLE
GetAttribute contentDescription is returning null value for android.widget.ImageView

### ISSUE THREAD

**Issue by sumeetpanjabi** [appium/appium#12500]
## The problem

I'm trying to fetch content description of a locator in Android. it is returning me null values.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Desktop OS/version used to run Appium: Mac OS 10.14 (18A391)
* Node.js version (unless using Appium.app|exe): Node v10.11.0
* Npm or Yarn package manager: NPM 6.4.1
* Mobile platform/version under test: Android 8.0.0
* Real device or emulator/simulator: Real device
uiAutomator2

## Details

I'm trying to fetch content description of a locator in Android. it is returning me null values.

## Link to Appium logs
[appiumLogs-ZF6223G5T8.txt](https://github.com/appium/appium/files/3078603/appiumLogs-ZF6223G5T8.txt)

## Code To Reproduce Issue [ Good To Have ]
List<WebElement> listName = driver.findElements(By.id("partner_image"));
listName.get(i).getAttribute("contentDescription");
<img width="794" alt="Screenshot 2019-04-15 at 11 39 48 AM" src="https://user-images.githubusercontent.com/43846789/56110746-38c7b280-5f73-11e9-91df-5f2464630507.png">

**Comment by mykola-mokhnach** [comment]
Try the most recent Appium version
