### ISSUE TITLE
mobile:installCertificate broken on iOS 12.2 (but fixable)

### ISSUE THREAD

**Issue by Jonahss** [appium/appium#12505]
## The problem

iOS 12.2 changed the alerts and UI for installing downloaded certificates. After downloading, now you need to dismiss an alert and open Settings > General > Profile, and install the profile. Then the step of going into Security and trusting the certificate.

We'll have to automate the settings app differently if ios version >= 12.2

## Environment

* Appium version (or git revision) that exhibits the issue: 1.12.1
* Last Appium version that did not exhibit the issue (if applicable): unrelated, it's iOS version
* Desktop OS/version used to run Appium: MacOS 10.14.4
* Node.js version (unless using Appium.app|exe): 11.6.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: ios
* Real device or emulator/simulator: sim
* Appium CLI or Appium.app|exe: cli

## Code To Reproduce Issue [ Good To Have ]

```java
String IOS_APP = "https://github.com/cloudgrey-io/the-app/releases/download/v1.6.1/TheApp-v1.6.1.app.zip";

DesiredCapabilities caps = new DesiredCapabilities();
        caps.setCapability("platformName", "iOS");
        caps.setCapability("platformVersion", "12.2");
        caps.setCapability("deviceName", "iPhone Xs");
        caps.setCapability("automationName", "XCUITest");
        caps.setCapability("app", IOS_APP);

        driver = new IOSDriver(new URL("http://0.0.0.0:4723/wd/hub"), caps);

        Path certificatePath = Paths.get(System.getProperty("user.home"), ".mitmproxy", "mitmproxy-ca-cert.pem");
        Map<String, Object> args = new HashMap<>();
        byte[] byteContent = Files.readAllBytes(certificatePath);
        args.put("content", Base64.getEncoder().encodeToString(byteContent));
        driver.executeScript("mobile: installCertificate", args);
```

**Comment by imurchie** [comment]
Feel free to fix it, then.

**Comment by Jonahss** [comment]
Alright. Adding to my list.

**Comment by mykola-mokhnach** [comment]
The fix has been published in beta
