### ISSUE TITLE
Xcode 10.1 has a maximum SDK version of 12.1. It does not support iOS version 12.1.2

### ISSUE THREAD

**Issue by devarshgandhi1** [appium/appium#12504]
## The problem

Xcode 10.1 has a maximum SDK version of 12.1. It does not support iOS version 12.1.2

## Environment

* Appium 1.12.1
* macOS Mojave version 10.14.4 (18E226)
* iPhone 7 Plus with iOS 12.1.2
* Real device

## Details

Error message comes from appium-xcuitest-driver.
https://github.com/appium/appium-xcuitest-driver/blob/273d9ce89de8c52afba015c40530040688f1f829/lib/driver.js#L306

## Link to Appium logs

https://gist.github.com/devarshgandhi1/c244f1d9a5b3ed1e29a6a5b6238d1a78

**Comment by mykola-mokhnach** [comment]
Set platformVersion to 12.1 as a workaround

**Comment by mykola-mokhnach** [comment]
The above version verification has been excluded completely from appium@beta
