### ISSUE TITLE
appium is unable to launch application on a real device

### ISSUE THREAD

**Issue by victorBychinski** [appium/appium#12503]
## The problem

Hello,
I followed the manual for Appium configuration for a real iOS device and performed all the steps described. Now I§m trying to launch  Safari browser on the device but getting an error

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0-beta1, Appium-Python-Client: 0.40
* Desktop OS/version used to run Appium: macOS Mojave v.10.14.4
* Mobile platform/version under test: iOS v.12.1.4 
* Real device or emulator/simulator: real device

## Link to Appium logs
<li><a href="https://gist.github.com/victorBychinski/548f339e5fcfb9ffc6b4cb571491b8d3">gist logs</a></li>

## Code To Reproduce Issue [ Good To Have ]
desired_caps = {
        'platformName': 'iOS',
        'platformVersion': '12.1',
        'deviceName': "May iPadMini",
        'browser': 'safari',
        'autoAcceptAlerts': True,
        'startIWDP': True,
        'wdaLaunchTimeout': 240000,
        'wdaConnectionTimeout': 240000,
        'udid': 'd1d7b2dc479b6dd845f7b6e6e47e9aa0846be83d',
        'bundleId': 'com.apple.mobilesafari',
        'showXcodeLog': True
        }

**Comment by mykola-mokhnach** [comment]
> [debug] [WD Proxy] Matched '/status' to command name 'getStatus'
> [debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
> [debug] [WD Proxy] Got response with status 200: ""

It looks like iproxy returns empty responses instead of valid JSON. Double check it works properly on your machine.

**Comment by victorBychinski** [comment]
> It looks like iproxy returns empty responses instead of valid JSON. Double check it works properly on your machine.
sorry for a silly question but do you mean that it something wrong with ios_webkit_debug_proxy? or  did you mean something else.
Regards

**Comment by mykola-mokhnach** [comment]
I mean the iproxy tool (part of libusbmux package), which is used to forward network requests to/from the device via usb

**Comment by imurchie** [comment]
This has been happening on real devices. Using the `useNewWDA` capability (set to `true`) helps, as it installs anew the server.

**Comment by victorBychinski** [comment]
@mykola-mokhnach  thank you for the help!
It seems like the problem was in libusbmuxd package. I re-installed it. Also I ran brew doctor and fixed all the stuff that it showed.
Closing the issue.

**Comment by yadavanand** [comment]
> This has been happening on real devices. Using the `useNewWDA` capability (set to `true`) helps, as it installs anew the server.

@imurchie thanks mate
