### ISSUE TITLE
"await is only valid in async function "Error on  "Running Your First Test"

### ISSUE THREAD

**Issue by fantasyado** [appium/appium#12508]
## The problem

when I run the hello word example I got following error:

node .\hello.js
C:\Users\ndu\workspace_test\raAuto\hello.js:15
  const field = await client.$("~TextField1");
                ^^^^^

SyntaxError: await is only valid in async function
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:282:19)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.12.1
* Desktop OS/version used to run Appium: windows 10
* Node.js version (unless using Appium.app|exe): 10.14.2
* Npm or Yarn package manager: npm ,6.5.0
* Mobile platform/version under test: Android 8.0
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe:  Appium.exe

## Code To Reproduce Issue [ Good To Have ]

source file :
const wdio = require("webdriverio");
const opts = {
    port: 4723,
    capabilities: {
      platformName: "Android",
      platformVersion: "8.0",
      deviceName: "emulator-5554",
      app: "C:\Users\ndu\Downloads\ApiDemos.apk",
      automationName: "UiAutomator2"
    }
  };
  
  const client = wdio.remote(opts);

  const field = await client.$("~TextField1");
  await field.setValue("Hello World!");
  const value = await field.getValue();
  assert.equal(value,"Hello World!");

**Comment by CarlitosDroid** [comment]
What is the solution?? Maybe it's a Javascript topic? Is it possible to test native applications like android and iOS with webdriverio and appium? Can I click a UIButton(iOS) or Button(Android) widget?

**Comment by imurchie** [comment]
The solution is to move the call to `await` into a function (which is marked with `async`). Or else work with promises instead of `async`/`await`.

`await`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await
`async`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function
