### ISSUE TITLE
error: unable to attach DB: error: accessing build database

### ISSUE THREAD

**Issue by FirstAM** [appium/appium#12511]
## The problem

Hello , have a problem with build WDA , when building is more then one Ios device. Sometimes building done is ok , but usually the build fails for one or all devices. In Xcode logs I find this 

**Build system information
 error: unable to attach DB: error: accessing build database "/Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Intermediates.noindex/XCBuildData/build.db": database is locked Possibly there are two concurrent builds running in the same filesystem location.**

But as i know Xcode has a limit on more than 3 parallel builds

And , sometimes this problem is solved by rebooting the device but not always

## Environment

Appium version (or git revision) that exhibits the issue: 1.12.1 / 1.13.0-beta.3
Desktop OS/version used to run Appium: MacOS 10.14.4
Mobile platform/version under test: ios
Real device or emulator/simulator: real
Appium CLI or Appium.app|exe: cli

## Details
Main fail xcode 

` warning: WebDriverAgentRunner isn't code signed but requires entitlements. It is not possible to add entitlements to a binary without signing it. (in target 'WebDriverAgentRunner')
 Build system information
 error: unable to attach DB: error: accessing build database "/Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Intermediates.noindex/XCBuildData/build.db": database is locked Possibly there are two concurrent builds running in the same filesystem location.`

## Link to Appium logs

Full Appium Logs on 3 devices 

[appium_logs_00008020-00063D3611E2002E_99.txt](https://github.com/appium/appium/files/3090506/appium_logs_00008020-00063D3611E2002E_99.txt)
[appium_logs_d8d68dee8fb1ad948cd01175ec725e0c72b15f7c_81.txt](https://github.com/appium/appium/files/3090507/appium_logs_d8d68dee8fb1ad948cd01175ec725e0c72b15f7c_81.txt)
[appium_logs_e1b73121f63bfcd3217308ad8d6556fd42f0d041_59.txt](https://github.com/appium/appium/files/3090508/appium_logs_e1b73121f63bfcd3217308ad8d6556fd42f0d041_59.txt)

In this case fail on second and third devices 
On second device line 468
On third device line 623

**Comment by mykola-mokhnach** [comment]
You can use multiple WebDriverAgent deployments for each to to avoid conflicts. Check on `bootstrapPath` and `derivedDataPath` caps. The first one sets the root folder for your WDA source and the second one sets the DerivedData folder path to be used by this deployment.

**Comment by mykola-mokhnach** [comment]
Other possible solutions might be to use prebuilt WDA or create a predefined xctestrun file (`usePrebuiltWDA`/`useXctestrunFile` caps)

**Comment by FirstAM** [comment]
> You can use multiple WebDriverAgent deployments for each driver instance to avoid conflicts. Check on `bootstrapPath` and `derivedDataPath` caps. The first one sets the root folder for your WDA source and the second one sets the DerivedData folder path to be used by this deployment.

Thanks , understand with first option but 

Im sorry for stupid question , but  how i can use prebuilt WDA if WebDriverAgenRunner is not app , and where can i read how to create  xctestrun file , thanks !

**Comment by mykola-mokhnach** [comment]
Check capabilities description at https://github.com/appium/appium-xcuitest-driver
