### ISSUE TITLE
AndroidDriver is not performing click() or even Touch actions (tap/press).

### ISSUE THREAD

**Issue by javydreamercsw** [appium/appium#12512]
## The problem

AndroidDriver is not performing click() or even Touch actions (tap/press).

## Environment
- Appium version (or git revision) that exhibits the issue: 1.9.1
- Last Appium version that did not exhibit the issue (if applicable): N/A
- Desktop OS/version used to run Appium: macOS Mojave (10.14.4)
- Node.js version (unless using Appium.app|exe): 11.13.0
- Mobile platform/version under test: Android Emulator 8.0
- Real device or emulator/simulator: Emulator
- Appium CLI or Appium.app|exe: CLI

## Details

When using click on the web element it responds with a 200 but nothing is clicked. Tried with touch actions tap/press and on that case it just doesn't call the action at all.

This seems related to #189

## Link to Appium Logs

https://gist.github.com/javydreamercsw/0352add5cf16ab456c5a683092c43b84

## Code To reproduce issue

 N/A

**Comment by mykola-mokhnach** [comment]
This might be related to https://appiumpro.com/editions/36

**Comment by javydreamercsw** [comment]
Yes! That did the trick!

`caps.setCapability("nativeWebTap", true);`

Perhaps this should be part of both:

- DesiredCapabilities.android()

- DesiredCapabilities.iphone()

**Comment by javydreamercsw** [comment]
`nativeWebTap` is exclusive for Safari/iOS combination. Issue still present on Android.

**Comment by mykola-mokhnach** [comment]
This article explains clearly explains why click does not work and what can be done to workaround it. Try to perform click with executeScript snippet instead, which generates events that the application under test expects. There's nothing more to do on Appium side. Closing as not an issue.
