### ISSUE TITLE
Safari not opening with supplied launch argument on real device iOS 12.2

### ISSUE THREAD

**Issue by biwkf** [appium/appium#12517]
## Environment

* Appium version (or git revision) that exhibits the issue: 1.12.1
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: MacOS 10.14.4 
* Node.js version (unless using Appium.app|exe): v10.11.0
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: iOS 12.2
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

## Details

Trying to launch safari app with launch arguments does not open the safari application on that url. Safari opens normally. 

This worked on device running with 12.1. After updating this no longer works on same device. I also tried on another 12.1 device and works fine (opens safari to the url specified in launch arg).

## Link to Appium logs
https://gist.github.com/biwkf/ae3fea3205dd841cbfbe30d6b70d6007

## Code To Reproduce Issue [ Good To Have ]

`List args = new ArrayList();
        args.add("-u");
        args.add("www.github.com");

        Map<String, Object> params = new HashMap<>();
        params.put("bundleId", "com.apple.mobilesafari");
        params.put("arguments", args);

        driver.executeScript("mobile: launchApp", params);`

**Comment by mykola-mokhnach** [comment]
Apple has removed the support of this option since iOS 12.2
Please report the issue to their bug tracker

**Comment by techno129** [comment]
@mykola-mokhnach any workaround to launch safari with a url ?

**Comment by biwkf** [comment]
I replaced with: 
```java
// destinationUrl is target url to visit ie "appium.io"
public void openURL(String destinationUrl) {

        // launch safari
        lanuchApp("com.apple.mobilesafari");
        // Click on url field
        clickOn("URL");
        // Set value in url field to desired url
        setValuetoTextFieldByName(destinationUrl, "URL");
        // Go to this url
        clickOn("Go");
        // Wait for page to finish loading
        waitForDismiss("StopButton");
    }
```
Which manually enters url to safari and hits enter

**Comment by ChiChou** [comment]
> Apple has removed the support of this option since iOS 12.2
> Please report the issue to their bug tracker

Not really. It has been renamed to:
`--U http://test.com`

cc @biwkf

**Comment by imurchie** [comment]
Does that option work for you? In my experience it sets the URL and then the page goes back to what it was, with nothing in the history, as if it never happened.

**Comment by khubaib321** [comment]
> > Apple has removed the support of this option since iOS 12.2
> > Please report the issue to their bug tracker
> 
> Not really. It has been renamed to:
> `--U http://test.com`
> 
> cc @biwkf @techno129

@ChiChou do you know what other arguments can be passed to open safari in new tab? Or maybe an argument that closes all open tabs?

**Comment by jenniferhuang** [comment]
> > Apple has removed the support of this option since iOS 12.2
> > Please report the issue to their bug tracker
> 
> Not really. It has been renamed to:
> `--U http://test.com`
> 
> cc @biwkf @techno129

It doesn't work for me for all the arguments "-u","-U" and "--U" on ios 13.2.3.  Any ideas, thanks.

**Comment by khubaib321** [comment]
@jenniferhuang I was able to open link in Safari (iOS 13.3).
Python code snippet that might help:

`params = { 'bundleId': 'com.apple.mobilesafari', 'arguments': ('--U', 'https://www.apple.com/') }`
`self.driver.execute_script('mobile: launchApp', params)`

**Comment by jenniferhuang** [comment]
Thanks for your reply, It still can't work for me.

![image](https://user-images.githubusercontent.com/5476529/80187181-c12a6a00-8641-11ea-8cae-e93f94329b6b.png)

**Comment by jenniferhuang** [comment]
Do you have the same log with me, I am using the appium 1.17.0.  
@khubaib321   @ChiChou  Any ideas will appreciate.
Log:
"script":"mobile: launchApp","args":[{"bundleId":"com.apple.mobilesafari","arguments":["--U","https://www.apple.com/"]}]}
2020-04-24 15:51:24:140 - [debug] [W3C (3f48910a)] Calling AppiumDriver.execute() with args: ["mobile: launchApp",[{"bundleId":"com.apple.mobilesafari","arguments":["--U","https://www.apple.com/"]}],"3f48910a-ced8-4f8c-a101-e8cb5e21fe7e"]
2020-04-24 15:51:24:141 - [debug] [XCUITest] Executing command 'execute'
2020-04-24 15:51:24:146 - [debug] [WD Proxy] Proxying [POST /wda/apps/launch] to [POST http://127.0.0.1:8881/session/17B43EC6-EDD8-4493-9981-27C782121CCC/wda/apps/launch] with body: {"bundleId":"com.apple.mobilesafari","arguments":["--U","https://www.apple.com/"]}
2020-04-24 15:51:25:456 - [debug] [WD Proxy] Got response with status 200: {"value":null,"sessionId":"17B43EC6-EDD8-4493-9981-27C782121CCC"}
2020-04-24 15:51:25:456 - [debug] [W3C (3f48910a)] Responding to client with driver.execute() result: null

**Comment by khubaib321** [comment]
@jenniferhuang it worked on my first attempt but now it's not opening on any further attempts. Not sure what is the issue. The logs I get are similar to yours. A workaround is to open Safari without any launch arguments, set value in search bar and hide keyboard. That should open the link.
