### ISSUE TITLE
iOS 12.2 XCUITest autoWebview not working

### ISSUE THREAD

**Issue by andrew-lai-bjss** [appium/appium#12510]
## The problem

When trying to run up an iOS 12.2 simulator with autoWebview set to true the following error is returned:

"An unknown server-side error occurred while processing the command. Original error: Remote debugger error with code '-32601': 'Page' domain was not found"

## Environment

* Appium version (or git revision) that exhibits the issue: 1.12.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS Mojave 10.14.2
* Node.js version (unless using Appium.app|exe): v10.13.0
* Npm or Yarn package manager: NPM - 6.4.1
* Mobile platform/version under test: iOS 12.2
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe:

## Details

I run the following in postman (pointing at appium)

```
{
    "desiredCapabilities": {
    	"platformName": "iOS",
	    "platformVersion": "12.2",
        "deviceName": "iPad Pro (10.5-inch)",
        "bundleId": "<BUNDLE_ID_OF_MY_IONIC_CORDOVA_APP>",
        "automationName": "XCUITest",
        "autoWebview": true
    }
}
```

If I set autoWebview to false the application loads but when I try to switch contexts to the Webview I get the same error.
 
## Link to Appium logs

```
{
    "status": 13,
    "value": {
        "message": "An unknown server-side error occurred while processing the command. Original error: Remote debugger error with code '-32601': 'Page' domain was not found"
    },
    "sessionId": null
}
```

## Code To Reproduce Issue [ Good To Have ]

See above

**Comment by andrew-lai-bjss** [comment]
Changing to 
`"platformVersion": "12.1",`
works as expected

**Comment by imurchie** [comment]
Please try updating to the latest beta of Appium (`npm uninstall -g appium && npm install -g appium@beta`).

**Comment by andrew-lai-bjss** [comment]
I still get the same response even with latest beta.

**Comment by andrew-lai-bjss** [comment]
Logs - https://gist.github.com/andrew-lai-bjss/945684c76910688703202c46a44d09e0

**Comment by jamespizzurro** [comment]
I'm able to reproduce this issue in the same environment. I did not check the latest beta though, just v1.12.1. The same error is thrown when you attempt to switch contexts (e.g. in Java: `driver.switchTo().window("WEBVIEW_12078.1");`) manually too with `autoWebview` off.

**Comment by imurchie** [comment]
Yes. If it doesn't work in one place it won't work in the other.

I'm investigating.

**Comment by Phoenix124** [comment]
@imurchie I have the same problem when switching to the WebView

**Comment by imurchie** [comment]
Closing in favor of #12518.
