### ISSUE TITLE
Cannot run Appium Inspector, using UIAutomator2 on Android app(Cannot get source)

### ISSUE THREAD

**Issue by bogatoiucatalin** [appium/appium#12529]
## **The problem**
I have an app, an .apk file on which I am trying to run the inspector and I always get some error. My thinking is that it is an appium bug and it cannot get the source or something like that(I will put logs). I have tried with different environments/appium versions. I have tried running tests directly from Intellij, same errors. 

After I receive the errors, the inspector just runs into an infinite loading screen... nothing more happens.

## **Environment**
* Appium version (or git revision) that exhibits the issue: 1.12.1
* Last Appium version that did not exhibit the issue (if applicable): Also tried with 1.10.0(same error)
* Desktop OS/version used to run Appium: macOS 10.14.3
* Node.js version (unless using Appium.app|exe): I am using Appium Desktop
* Mobile platform/version under test: 9, Android Tablet
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Desktop
* I am using UIAutomator2 but I have also tried with UIAutomator and Espresso and it doesn't work.

Capabilities:
 "platformName": "Android",
  "platformVersion": "9",
  "deviceName": "Pixel",
  "app": "/Users/CENSORED/App/CENSORED/app-debug.apk",
  "automationName": "UIAutomator2"

## **Details**
The app I am trying to run the tests on is like a OS(its an Android Open Source Project, it's build on top of the Android OS) on the emulator, maybe that's the problem, but I do have the .apk file of it which I can run on tablet emulator(Pixel_C) or on a emulator we configured which is like a car auto emulator.

I have also tried to run it using "appPackage and appActivity" but I get the same.

## **Link to Appium logs**
https://gist.github.com/bogatoiucatalin/7c3b5b1868e4569f3b72936c61a15df5

**Comment by mykola-mokhnach** [comment]
Such exception is thrown if UIA2 is unable to retrieve the accessibility source from the system https://github.com/appium/appium-uiautomator2-server/blob/1786d0c84d75fff79fde5255be0a9ec6ea222e42/app/src/main/java/io/appium/uiautomator2/utils/AXWindowHelpers.java#L63

I don't think there is something that can be fixed there on Appium side

**Comment by bogatoiucatalin** [comment]
@mykola-mokhnach do you have any thoughts on what is wrong with the app that it cannot get the accessibility source? No idea.

**Comment by mykola-mokhnach** [comment]
I would check the logcat output first, maybe it has some hints

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
