### ISSUE TITLE
Swipe action not working after upgrading Appium 

### ISSUE THREAD

**Issue by GR3636** [appium/appium#12523]
## The problem
Swipe action used in Appium version 1.7.2 is not working in Appium version 1.12

## Environment
Appium version (or git revision) that exhibits the issue :- 1.12

Last Appium version that did not exhibit the issue :- 1.7.2

Desktop OS/version used to run Appium :- Ubuntu 16.0.4

Node.js version :- 10.12.0

Npm or Yarn package manager :- 6.4.1

Mobile platform/version under test :- Android 7.1.1

emulator/simulator

## Code To Reproduce Issue
TouchAction action = new TouchAction(getDriver());
action.press(basePage.getTitle().getElement()).moveTo(-100, 0).release().perform();

**Comment by KazuCocoa** [comment]
Did you update your code?
1.8.0 had _All moveTo operations in touch actions now take coordinates as absolute_ change
https://github.com/appium/appium/blob/master/CHANGELOG.md#changes-in-version-180-from-172

**Comment by mykola-mokhnach** [comment]
Also a wait is necessary after the press action. There are multiple duplicates of this report, thus closing
