### ISSUE TITLE
Nested arguments not converted to elements

### ISSUE THREAD

**Issue by twalpole** [appium/appium#12522]
## The problem

A user reported an issue using the latest Capybara with appium via saucelabs - https://github.com/teamcapybara/capybara/issues.  

I haven't been able to 100% confirm this, partly due to the original reporter not responding, but I believe the root cause is that while WebDrivers execute_script allows for passing arguments that contain nested web elements, the ios-driver doesn't appear to process these correctly in `convertElementsForAtoms` - https://github.com/appium/appium-ios-driver/blob/fb33c52525ec7e91bffb41072d091008adc2234e/lib/commands/web.js#L389

ie - it works fine if args is 
  
    [{'ELEMENT': 5000}, {'ELEMENT': 5001}] 

but not if args is

    [[{'ELEMENT': 5000}, {'ELEMENT': 5001}]]

Since the WebDriver spec allows for nested elements I think convertElementsForAtoms needs to recurse into at least Arrays (the spec allows for Hashes/Objects too)

**Comment by mykola-mokhnach** [comment]
The fix has been  published in appium@beta
