### ISSUE TITLE
flag --tmp is not respected in some cases

### ISSUE THREAD

**Issue by kazzmir** [appium/appium#12527]
## The problem

Appium downloads apps into a temporary directory of its own choosing, rather than respecting the `--tmp` directory specified by the user.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.12.1
* Desktop OS/version used to run Appium: Linux

## Details

Run appium with the --tmp flag
```
$ appium --tmp /tmp/my-tmp-dir
```
Run a test and give it a url for the apk

```
{'desiredCapabilities': {'app': 'http://my-server/x.apk'}}
```

The app will get downloaded to /tmp/2019321-12345-jasfewf.wei instead of /tmp/my-tmp-dir/something

It looks like downloadApp() is called in appium-base-driver/lib/basedriver/helpers.js with a targetPath derived from `appium-support.tempDir()` where `tempDir()` will create a directory in /tmp with the date in the name. I see that the directory passed to `--tmp` is stored in appium/lib/config, but don't see how it should connect to the `tempDir()` function exactly.

Probably every place in the code that calls `tempDir` should be updated to respect the `config.tmpDir` variable, though.

**Comment by jlipps** [comment]
Looks like this is a matter of code usage hygiene which we have not respected. Recommend updating the appium-support helper methods to take an optional parameter which overrides the base temp dir, and then making sure we use that everywhere.

**Comment by KazuCocoa** [comment]
a note:

I'll apply https://github.com/appium/appium-support/pull/112 to appium-android-driver

**Comment by KazuCocoa** [comment]
will update in this comment:

- appium-uiautomator2-driver
    - `tempDir` is only in `getString`, but the method removes the temporary directory used in the method every time as finally. No need to change the logic, or change to remove a file (not directory)

**Comment by KazuCocoa** [comment]
note:

https://github.com/appium/appium-support/pull/112/commits/fe224c8e9d9bebf49f5a6a0969398be4ecb4816d and adding `process.env.APPIUM_TEMP_DIR = this.opts.tmpDir` in https://github.com/appium/appium-base-driver/blob/d214a0d1f2aa3aecd8fd4033460ce37176ca4c87/lib/basedriver/driver.js#L48 is the safest way to apply the temp config, I think. The safest means we can make the change minimal.

Putting the tempDir param into `process.env` and `appium-support` refers to it. In some places, we should tweak the tempDir logic (set `null`, for example) tho. e.g. `appium-uiautomator2-driver`'s `getString`.

I investigated a couple of repositories and `tempDir` usage. We should add new argument to pass the tempDir param in various places. some of them can pass as `driver.opts.tempDir` easily, but some of them requires new args.

**Comment by KazuCocoa** [comment]
link: https://github.com/appium/appium-android-driver/pull/538

**Comment by KazuCocoa** [comment]
The above links will fix this issue after releasing them.
Each of them does not break existing features.

Our next minor release, 1.14.0, will have them.
Will continue to track.
