### ISSUE TITLE
run 'i -g opencv4nodejs'  error

### ISSUE THREAD

**Issue by Zhanggaoyi92** [appium/appium#12537]
## The problem

when i run 'i -g opencv4nodejs' , it shows error : 
[ 92%] Built target opencv_calib3d
make: *** [all] Error 2
ERR! child process exited with code 2 (for more info, set '--loglevel silly') 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencv-build@0.0.17 install: `node ./install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the opencv-build@0.0.17 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!    ~/.npm/_logs/2019-04-24T00_34_20_261Z-debug.log

what i can do ? thanks a lot.

logs :
845 silly install opencv-build@0.0.17
846 info lifecycle opencv-build@0.0.17~install: opencv-build@0.0.17
847 verbose lifecycle opencv-build@0.0.17~install: unsafe-perm in lifecycle true
848 verbose lifecycle opencv-build@0.0.17~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/local/lib/node_modules/opencv4nodejs/node_modules/opencv-build/node_modules/.bin:/usr/local/lib/node_modules/opencv4nodejs/node_modules/.bin:/usr/local/lib/node_modules/.bin:/usr/sbin/:/usr/local/bin:/bin:/usr/bin:~/flutter/bin
849 verbose lifecycle opencv-build@0.0.17~install: CWD: /usr/local/lib/node_modules/opencv4nodejs/node_modules/opencv-build
850 silly lifecycle opencv-build@0.0.17~install: Args: [ '-c', 'node ./install.js' ]
851 silly lifecycle opencv-build@0.0.17~install: Returned: code: 1  signal: null
852 info lifecycle opencv-build@0.0.17~install: Failed to exec install script
853 timing action:install Completed in 407200ms
854 verbose unlock done using /Users/wudingdeyang/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
855 timing stage:rollbackFailedOptional Completed in 1174ms
856 timing stage:runTopLevelLifecycles Completed in 412482ms
857 verbose stack Error: opencv-build@0.0.17 install: `node ./install.js`
857 verbose stack Exit status 1
857 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
857 verbose stack     at EventEmitter.emit (events.js:193:13)
857 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
857 verbose stack     at ChildProcess.emit (events.js:193:13)
857 verbose stack     at maybeClose (internal/child_process.js:999:16)
857 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
858 verbose pkgid opencv-build@0.0.17
859 verbose cwd /Users/wudingdeyang/Downloads/cmake-3.14.3-Darwin-x86_64/CMake.app/Contents
860 verbose Darwin 18.5.0
861 verbose argv "/usr/local/Cellar/node/11.14.0_1/bin/node" "/usr/local/bin/npm" "i" "-g" "opencv4nodejs"
862 verbose node v11.14.0
863 verbose npm  v6.9.0
864 error code ELIFECYCLE
865 error errno 1
866 error opencv-build@0.0.17 install: `node ./install.js`
866 error Exit status 1
867 error Failed at the opencv-build@0.0.17 install script.
867 error This is probably not a problem with npm. There is likely additional logging output above.
868 verbose exit [ 1, true ]

**Comment by LiebeKrake** [comment]
waiting for workround.

**Comment by Zhanggaoyi92** [comment]
think you.i will try it later.

**Comment by mykola-mokhnach** [comment]
Closed as not an appium issue. Please report the problem to the appropriate place.
