### ISSUE TITLE
Looking for alternative of Touchaction class

### ISSUE THREAD

**Issue by manjunathkonkalmatth** [appium/appium#12530]
Hi,

I have a situation where I have to draw on a canvas of iPad using appium (Java), and the product is developed in a such a way we can draw using only ipencil. I am not able to simulate using touch action class. is there any other way to achieve this.

**Comment by mykola-mokhnach** [comment]
W3C actions API gives more fine-grained control over touch actions. Check https://appiumpro.com/editions/29 for example. Otherwise Apple does not provide any other interfaces for this purpose.

**Comment by manjunathkonkalmatth** [comment]
> W3C actions API gives more fine-grained control over touch actions. Check https://appiumpro.com/editions/29 for example. Otherwise Apple does not provide any other interfaces for this purpose.

I referred it before only but getting error in driver.perform(Arrays.asList(circle)); line.
