### ISSUE TITLE
After run this command xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=deviceid' test getting error Error Domain=com.apple.platform.iphoneos Code=-12 "Unable to launch com.apple.test.WebDriverAgentRunner-Runner"

### ISSUE THREAD

**Issue by nageshc** [appium/appium#12539]
## After running the _xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=deviceid' test_  **getting this error  Error Domain=com.apple.platform.iphoneos Code=-12 "Unable to launch com.apple.test.WebDriverAgentRunner-Runner"**

I have following this https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md document and performing steps. 

## Environment

* Appium version - 1.12.1
* Desktop OS/version used to run Appium: MAC 10.12.0 
* Node.js version (unless using Appium.app|exe): node - v11.14.0
* Npm or Yarn package manager: npm - 6.9.0
* Mobile platform/version under test: iPhone 6s - iOS vesrion 10.1.1
* Real device or emulator/simulator: Real device

## Link to Appium logs
https://gist.github.com/nageshc/babb10610c92eaac699932ebdeabb81e

## Code To Reproduce Issue [ Good To Have ]

I have following this https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md document and performing steps.

for performing this step

Finally, you can verify that everything works. Build the project: 

After run this command xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=deviceid' test getting error Error Domain=com.apple.platform.iphoneos Code=-12 "Unable to launch com.apple.test.WebDriverAgentRunner-Runner"

**Comment by KazuCocoa** [comment]
> Unable to launch com.apple.test.WebDriverAgentRunner-Runner because it has an invalid code signature

Did you ensure your signature was able to install the WDA into your device via Xcode?
https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md#full-manual-configuration probably help the case.

**Comment by nageshc** [comment]
@KazuCocoa 

Thank you for the quick reply.

Yes I am able to install WebDriverAgentRunner on my iPhone 6s device via Xcode.

When I Click on Test option under the Product menu in Xcode to install WDAR it displays one alert to trust it to go General -->Profile and Device Management --> Developer App -->

I am done with trust the app by following steps.

Thank you

**Comment by nageshc** [comment]
Hi @KazuCocoa,
I have attached a screenshot of Xcode:
![xcode](https://user-images.githubusercontent.com/3041187/56653124-99a96600-66aa-11e9-901b-bd256a2d3e27.png)

Thanks

**Comment by nageshc** [comment]
@imurchie, @mykola-mokhnach Guys could you please check this issue.

Thank you

**Comment by KazuCocoa** [comment]
What about below?

1. create a simple app and install the app in your device signed by your personal account
2. Trust your personal account signature following https://github.com/appium/appium/issues/12539#issuecomment-486167137
3. Run Appium with your personal account

I forget the exact message, but if `inadequate entitlements or its profile has not been explicitly trusted by the user.` is because of your personal account has not been trusted on your device because of re-installation, the above steps probably solve it.

**Comment by nageshc** [comment]
Hi @KazuCocoa,

While installing the sample ios app on iPhone from Xcode using Test option under the product menu.

Getting Pop up in Xcode as "A valid provisioning profile for this executable was not found." 

I have attached screenshot

![profile](https://user-images.githubusercontent.com/3041187/56657577-05dd9700-66b6-11e9-8a08-806f0457d55a.png)

Thank you

**Comment by KazuCocoa** [comment]
that is a provisioning issue. sometimes it fixes after cleaning your build env etc.
e.g. https://stackoverflow.com/questions/52424462/xcode-10-a-valid-provisioning-profile-for-this-executable-was-not-found

**Comment by mykola-mokhnach** [comment]
Closed as not an Appium issue
