### ISSUE TITLE
An unknown server-side error occurred while processing the command. Original error: activity and pkg are required to start an application

### ISSUE THREAD

**Issue by chitandacc** [appium/appium#12546]
## The problem

An unknown server-side error occurred while processing the command. Original error: activity and pkg are required to start an application

## Environment
- I am running Appium Desktop version _1.12.1.
- I am on windows10:
  emulator/simulator:

{
  "platformName": "Android",
  "platformVersion": "4.4.2",
  "deviceName": "OPPO R11",
  "appPackage": "com.android.browser",
  "appActivity ": ".BrowserActivity"
}

![image](https://user-images.githubusercontent.com/46182734/56778863-0b98c100-680b-11e9-9814-16bb5fb68b5c.png)

## Link to Appium logs
https://github.com/chitandacc/question/commit/a1e767ddf83ab1b5ec82e10567ad7fc4dc3927d6

**Comment by KazuCocoa** [comment]
Do you have a space in the key of `appActivity `?

**Comment by chitandacc** [comment]
Thank you for the quick reply.
I cannot get at the meaning of this "space",
![image](https://user-images.githubusercontent.com/46182734/56781794-faee4800-6816-11e9-8ab9-4ae42d908557.png)
can you tell me how to check "space"? 

> Do you have a space in the key of `appActivity `?

**Comment by chitandacc** [comment]
> Do you have a space in the key of `appActivity `?

@KazuCocoa
Thank you for the quick reply.
I don't quite understand the meaning of "space",
![image](https://user-images.githubusercontent.com/46182734/56782579-553cd800-681a-11e9-8018-6a9990c62ce9.png)
Can you explain in detail how to check this “space”？
Set the same parameters，A browser on the emulator can be started on pycharm
![image](https://user-images.githubusercontent.com/46182734/56783146-c67d8a80-681c-11e9-8d20-6190abbcbe56.png)

**Comment by mykola-mokhnach** [comment]
> [warn] [35m[BaseDriver][39m The following capabilities were provided, but are not recognized by appium: appActivity , connectHardwareKeyboard.

`appActivity`cap has an extra space at the end and thus is not recognised. Closed as not an issue

**Comment by chitandacc** [comment]
I haven't changed anything. Appium is working again

**Comment by KazuCocoa** [comment]
Did you re-input your json into the desktop? The desktop json has an extra space in the `appActivity ` key. Your pycharm thing was correct.

Anyway, glad to hear it 👍
