### ISSUE TITLE
inspector could not get page source after run app successfully on ios12  Duplicate of #11558

### ISSUE THREAD

**Issue by ShubhamPagarwar** [appium/appium#12540]
I am facing same problem as mentioned in 

https://github.com/appium/appium/issues/11558

@yuesongjie and @mykola-mokhnach
 Request you to provide solution on this issue

iOS 12.2 version.
Xcode Version - 10.2.1
Appium Version - 1.12.1

**Comment by mykola-mokhnach** [comment]
Unfortunately we can do nothing there on Appium side. The page source is returned by WebDriverAgent/XCTest. Appium just acts as a proxy there.

**Comment by ShubhamPagarwar** [comment]
Oh ok, thanks
