### ISSUE TITLE
Forced test session retries when two or more real IOS devices are connected to same grid

### ISSUE THREAD

**Issue by presidenten** [appium/appium#12549]
## The problem

When running appium with one real ios device, all tests run perfect.

When running appium and targeting one real ios device with another real ios device connected to the grid, the tests are executed multiple times. 

Depending on the amount of connected devices there is a random chance of getting a result after a long while or just a timeout error.

The selenium log says that it tries to create a session on the wrong device when this error shows up. Here is an example with only two devices (for simplicity).

```
14:58:16.388 INFO [RequestHandler.process] - Got a request to create a new session: Capabilities 
{
  appium:automationName: XCUITest,
  appium:deviceName: iPad Gen6 #1,     <-----------
  appium:deviceType: iPad,
  appium:platformVersion: 12.2,
  appium:udid: <udid1>,
  appium:wdaLocalPort: 5570,           <-----------
  appium:xcodeOrgId: <org_id>,
  appium:xcodeSigningId: iPhone Developer,
  browserName: safari,
  platformName: ios
}
14:58:16.390 INFO [TestSlot.getNewSession] - Trying to create a new session on test slot 
{
  deviceType=iPad,
  server:CONFIG_UUID=<config_uuid>,
  seleniumProtocol=WebDriver,
  xcodeOrgId=<org_id>,
  deviceName=iPad Gen6 #2,               <-----------
  version=12.2,
  platform=IOS,
  xcodeSigningId=iPhone Developer,
  wdaLocalPort=5671,                     <-----------
  platformVersion=12.2,
  automationName=XCUITest,
  browserName=safari,
  maxInstances=1,
  platformName=IOS,
  udid=<udid2>
}
```

## Environment

* Appium version (or git revision) that exhibits the issue:
1.13.0-beta3
* Selenium version
3.141.59
* Desktop OS/version used to run Appium:
osx mojave 10.14.4
* Node.js version (unless using Appium.app|exe):
8.12.0
* Npm or Yarn package manager:
6.9.0
* Mobile platform/version under test:
Ipad 12.2, Iphone 12.2
* Real device or emulator/simulator:
Real devices
* Appium CLI or Appium.app|exe:
Appium CLI

## Details
ios_debug_webkit_proxy started with
```
ios_webkit_debug_proxy -c <udid1>:5670
ios_webkit_debug_proxy -c <udid2>:5671
```

Appium started with:
```
appium -a "<url-to-appium-server>" --nodeconfig ipad1.json --session-override --allow-cors --webkit-debug-proxy-port 5670 -p 5570
appium -a "<url-to-appium-server>" --nodeconfig ipad2.json --session-override --allow-cors --webkit-debug-proxy-port 5671 -p 5571
```

Contents of ipad1.json. 
(ipad2.json, is the same, except different devicename, udid and all ports ending on 1 instead of 0)
```
{
  "capabilities": [
    {
      "browserName": "safari",
      "version": "12.2",
      "maxInstances": 1,
      "platformName": "IOS",
      "platformVersion": "12.2",
      "automationName": "XCUITest",
      "deviceType": "iPad",
      "deviceName": "iPad Gen6 #1",
      "xcodeOrgId": "<org_id>",
      "xcodeSigningId": "iPhone Developer",
      "udid": "<udid1>",
      "wdaLocalPort": "5670"
    }
  ],
  "configuration": {
    "port": 5570,
    "url":" <http://<appium_server_url>:5570/wd/hub>",
    "host": "<appium_server_url>",
    "hubHost": "<selenium_server_url>",
    "hubPort": 4444,
    "cleanUpCycle": 2000,
    "timeout": 30000,
    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
    "maxSession": 1,
    "register": true,
    "registerCycle": 5000,
    "unregisterIfStillDownAfter": 10000,
    "debug": false,
    "role": "node"
  }
}
```

The desired capabilities in the test: 
```
    {
      maxInstances: 1,
      browserName: 'safari',
      platformName: 'IOS',
      'appium:platformVersion': '12.2',
      'appium:automationName': 'XCUITest',
      'appium:xcodeOrgId': '<org_id>',
      'appium:xcodeSigningId': 'iPhone Developer',
      'appium:udid': '<udid1>',
      'appium:deviceName': 'iPad Gen6 #1',
      'appium:deviceType': 'iPad',
      'appium:wdaLocalPort': 5570,
    },
```

## Link to Appium logs

Logs are in this gist:
https://gist.github.com/presidenten/96ac86ee8e53ad24f086bf5a66f4da40
Files in gist:
- Appium log - ipad1 
- Appium log - ipad2 
- Selenium server log
- Wdio log (client log)

## Discussion

It seems like selenium only checks `browserName` when selecting a browser. 
It ignores all prefixed capabilities. 

I cant change browser name to something unique since appium then wants me to use bundle identifier, and if I use a bundle identifier, Im not allowed to use a browser name

I've noticed "kind of the same behaviour"...ish when using multiple android devices, but then it seems to just work anyways somehow.

**Comment by mykola-mokhnach** [comment]
If this is about selecting the right node on selenium hub then you could try the undocumented `applicationName` [capability](https://medium.com/@mustafayol/selenium-grid-running-test-cases-on-a-particular-node-with-json-files-bd734d5fb24e).

> It seems like selenium only checks browserName when selecting a browser.
> It ignores all prefixed capabilities.

It's how the grid works. Please create an issue to them in order to allow node selection on based additional caps

**Comment by presidenten** [comment]
@mykola-mokhnach 
It didnt work.

What I would actually want is to not have to specify any device at all and have Selenium choose one for me. But with appium I need to specify udid to target a real device (otherwise it tries to spawn a simulator session), and if I specify a udid it seems like I have to find a way to help selenium to target the corresponding node.

Is there anyway to target real devices without specifying udid in the desired capabilities so I can let selenium choose a real device for me? Maybe something to suppress appiums urge to start a simulator?
```
Could not create simulator with name 'appiumTest-B09EA1D8-7891-4E63-8D36-7460D0
A6AE06-iPad Gen6 #1'
```

Anyhow, I got inspired and checked for other capabilities and found `browserVersion` that seems to take any value, so I just listed them as 12.2-ipad1, 12.2-ipad2,12.2- ipad3, etc and it solved the problem.

**Comment by mykola-mokhnach** [comment]
> Is there anyway to target real devices without specifying udid in the desired capabilities so I can let selenium choose a real device for me? Maybe something to suppress appiums urge to start a simulator?

Unfortunately such functionality is not available. There is an improvement request for that though. Feel free to create a PR and implement such functionality

**Comment by presidenten** [comment]
I wish I know how to :-)

Anyways, thanks for the quick input. For future references we now know we can target specific nodes by using `browserVersion` though.
