### ISSUE TITLE
Certain Emulators Are Getting Device Size Returns 0 for both Length and Height

### ISSUE THREAD

**Issue by InvisibleExo** [appium/appium#12544]
## The problem

I'm seeing an issue where emulators return Height and Width return 0 when getting device size.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13.0-beta.3
* AutomationName: Uiautomator2 
* Last Appium version that did not exhibit the issue (if applicable): 1.11.1
* Node.js version (unless using Appium.app|exe): 6.4.1
* Real device or emulator/simulator: Android Emulator (Google Nexus and Google Pixel)

## Details

I'm noticing an issue with certain emulators where getting the device's size, height and width returns 0.  As a result, TouchAction Swipes are performed, but don't move either up or down the screen.  The context is also set to Webview when getting Device's size was performed.  Getting size of MobileElements on the screen does return a value of height and width. 

Other emulator models, such as Samsung Galaxy are able to get device size and Element size without issue and can perform Touch Action swipes.

Let me know if you need more info.

## Link to Appium logs

Link for Google Nexus Emulator returns device size as zero:
https://gist.github.com/InvisibleExo/88d7ba06b5d9a542ee8f423821b22fe3

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

```
void swipeThroughElementVertical(double startPercentage, double endPercentage, int duration,
			MobileElement element) {
		size = element.getSize();
		int width = (int) (size.width/2);
		int startPoint = (int) (size.getHeight() * startPercentage);
		int endPoint = (int) (size.getHeight() * endPercentage);
		new AndroidTouchAction(driver)
			.press(PointOption.point(width, startPoint))
			.waitAction(WaitOptions.waitOptions(Duration.ofMillis(duration)))
			.moveTo(PointOption.point(width, endPoint))
			.release()
			.perform();
	}

```

**Comment by mykola-mokhnach** [comment]
Can you please point out where exactly in the attached log the size is returned as zero?

**Comment by InvisibleExo** [comment]
@mykola-mokhnach, here is a snippnet from the gist link where the calls are made to get the device's size. I also included a bit of what was server logs recorded before making the call to get device dimensions.


[HTTP] {"id":"0.08381544702686639-1","text":"star wars","value":["s","t","a","r"," ","w","a","r","s"]} [W3C (e952e3f8)] Driver proxy active, passing request on via HTTP proxy [debug] [WD Proxy] Matched '/wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/element/0.08381544702686639-1/value' to command name 'setValue' [debug] [WD Proxy] Proxying [POST /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/element/0.08381544702686639-1/value] to [POST http://127.0.0.1:8000/wd/hub/session/25b563385ef671864e4f67eddf813e74/element/0.08381544702686639-1/value] with body: {"id":"0.08381544702686639-1","text":"star wars","value":["s","t","a","r"," ","w","a","r","s"]} [debug] [WD Proxy] Got response with status 200: {"sessionId":"25b563385ef671864e4f67eddf813e74","status":0,"value":null} [WD Proxy] Replacing sessionId 25b563385ef671864e4f67eddf813e74 with e952e3f8-cbd7-4eb7-9245-2f872e742362 [HTTP] <-- POST /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/element/0.08381544702686639-1/value 200 4239 ms - 76 [HTTP] [HTTP] --> GET /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362 [HTTP] {} [W3C (e952e3f8)] Driver proxy active, passing request on via HTTP proxy [debug] [WD Proxy] Matched '/wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362' to command name 'getSession' [debug] [WD Proxy] Proxying [GET /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362] to [GET http://127.0.0.1:8000/wd/hub/session/25b563385ef671864e4f67eddf813e74] with body: {} [debug] [WD Proxy] Got response with status 200: "{\"sessionId\":\"25b563385ef671864e4f67eddf813e74\",\"status\":0,\"value\":{\"acceptInsecureCerts\":false,\"acceptSslCerts\":false,\"applicationCacheEnabled\":false,\"browserConnectionEnabled\":false,\"browserName\":\"chrome\",\"chrome\":{\"chromedriverVersion\":\"2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1)\"},\"cssSelectorsEnabled\":true,\"databaseEnabled\":false,\"goog:chromeOptions\":{\"debuggerAddress\":\"localhost:55317\"},\"handlesAlerts\":true,\"hasTouchScreen\":true,\"javascriptEnabled\":true,\"locationContextEnabled\":true,\"mobileEmulationEnabled\":false,\"nativeEvents\":true,\"pageLoadStrategy\":\"normal\",\"platform\":\"ANDROID\",\"proxy\":{},\"rotatable\":false,\"setWindowRect\":false,\"strictFileInteractability\":false,\"takesHeapSnapshot\":true,\"takesScreenshot\":true,\"timeouts\":{\"implicit\":0,\"pageLoad\":300000,\"script\":30000},\"unexpectedAlertBehaviour\":\"ignore\",\"version\":\"72.0.3626.76\",\"webStorageEnabled\":true}}" [WD Proxy] Replacing sessionId 25b563385ef671864e4f67eddf813e74 with e952e3f8-cbd7-4eb7-9245-2f872e742362 [HTTP] <-- GET /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362 200 77 ms - 888 [HTTP] [HTTP] --> GET /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/context [HTTP] {} [debug] [W3C (e952e3f8)] Calling AppiumDriver.getCurrentContext() with args: ["e952e3f8-cbd7-4eb7-9245-2f872e742362"] [debug] [W3C (e952e3f8)] Responding to client with driver.getCurrentContext() result: "CHROMIUM" [HTTP] <-- GET /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/context 200 18 ms - 20 [HTTP] [HTTP] --> GET /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/context [HTTP] {} [debug] [W3C (e952e3f8)] Calling AppiumDriver.getCurrentContext() with args: ["e952e3f8-cbd7-4eb7-9245-2f872e742362"] [debug] [W3C (e952e3f8)] Responding to client with driver.getCurrentContext() result: "CHROMIUM" [HTTP] <-- GET /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/context 200 65 ms - 20 [HTTP] [HTTP] --> POST /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/element [HTTP] {"using":"class name","value":"Tg7LZd"} [W3C (e952e3f8)] Driver proxy active, passing request on via HTTP proxy [debug] [WD Proxy] Matched '/wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/element' to command name 'findElement' [debug] [WD Proxy] Proxying [POST /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/element] to [POST http://127.0.0.1:8000/wd/hub/session/25b563385ef671864e4f67eddf813e74/element] with body: {"using":"class name","value":"Tg7LZd"} [debug] [WD Proxy] Got response with status 200: {"sessionId":"25b563385ef671864e4f67eddf813e74","status":0,"value":{"ELEMENT":"0.08381544702686639-2"}} [WD Proxy] Replacing sessionId 25b563385ef671864e4f67eddf813e74 with e952e3f8-cbd7-4eb7-9245-2f872e742362 [HTTP] <-- POST /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/element 200 493 ms - 107 [HTTP] [HTTP] --> POST /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/element/0.08381544702686639-2/click [HTTP] {"id":"0.08381544702686639-2"} [W3C (e952e3f8)] Driver proxy active, passing request on via HTTP proxy [debug] [WD Proxy] Matched '/wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/element/0.08381544702686639-2/click' to command name 'click' [debug] [WD Proxy] Proxying [POST /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/element/0.08381544702686639-2/click] to [POST http://127.0.0.1:8000/wd/hub/session/25b563385ef671864e4f67eddf813e74/element/0.08381544702686639-2/click] with body: {"id":"0.08381544702686639-2"} [debug] [WD Proxy] Got response with status 200: {"sessionId":"25b563385ef671864e4f67eddf813e74","status":0,"value":null} [WD Proxy] Replacing sessionId 25b563385ef671864e4f67eddf813e74 with e952e3f8-cbd7-4eb7-9245-2f872e742362 [HTTP] <-- POST /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/element/0.08381544702686639-2/click 200 14530 ms - 76 [HTTP] [HTTP] --> POST /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/execute/sync [HTTP] {"script":"return document.readyState","args":[]} [W3C (e952e3f8)] Driver proxy active, passing request on via HTTP proxy [debug] [WD Proxy] Matched '/wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/execute/sync' to command name 'execute' [Protocol Converter] Rewrote the original URL '/wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/execute/sync' to '/wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/execute' for MJSONWP protocol [debug] [WD Proxy] Proxying [POST /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/execute] to [POST http://127.0.0.1:8000/wd/hub/session/25b563385ef671864e4f67eddf813e74/execute] with body: {"script":"return document.readyState","args":[]} [debug] [WD Proxy] Got response with status 200: {"sessionId":"25b563385ef671864e4f67eddf813e74","status":0,"value":"complete"} [WD Proxy] Replacing sessionId 25b563385ef671864e4f67eddf813e74 with e952e3f8-cbd7-4eb7-9245-2f872e742362 [HTTP] <-- POST /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/execute/sync 200 309 ms - 82 [HTTP] [HTTP] --> POST /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/execute/sync [HTTP] {"script":"return document.readyState","args":[]} [W3C (e952e3f8)] Driver proxy active, passing request on via HTTP proxy [debug] [WD Proxy] Matched '/wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/execute/sync' to command name 'execute' [Protocol Converter] Rewrote the original URL '/wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/execute/sync' to '/wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/execute' for MJSONWP protocol [debug] [WD Proxy] Proxying [POST /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/execute] to [POST http://127.0.0.1:8000/wd/hub/session/25b563385ef671864e4f67eddf813e74/execute] with body: {"script":"return document.readyState","args":[]} [debug] [WD Proxy] Got response with status 200: {"sessionId":"25b563385ef671864e4f67eddf813e74","status":0,"value":"complete"} [WD Proxy] Replacing sessionId 25b563385ef671864e4f67eddf813e74 with e952e3f8-cbd7-4eb7-9245-2f872e742362 [HTTP] <-- POST /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/execute/sync 200 169 ms - 82 [HTTP] [HTTP] --> GET /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/context [HTTP] {} [debug] [W3C (e952e3f8)] Calling AppiumDriver.getCurrentContext() with args: ["e952e3f8-cbd7-4eb7-9245-2f872e742362"] [debug] [W3C (e952e3f8)] Responding to client with driver.getCurrentContext() result: "CHROMIUM" [HTTP] <-- GET /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/context 200 25 ms - 20 [HTTP] [HTTP] --> GET /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/context [HTTP] {} [debug] [W3C (e952e3f8)] Calling AppiumDriver.getCurrentContext() with args: ["e952e3f8-cbd7-4eb7-9245-2f872e742362"] [debug] [W3C (e952e3f8)] Responding to client with driver.getCurrentContext() result: "CHROMIUM" [HTTP] <-- GET /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/context 200 6 ms - 20 [HTTP] [HTTP] --> GET /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/context [HTTP] {} [debug] [W3C (e952e3f8)] Calling AppiumDriver.getCurrentContext() with args: ["e952e3f8-cbd7-4eb7-9245-2f872e742362"] [debug] [W3C (e952e3f8)] Responding to client with driver.getCurrentContext() result: "CHROMIUM" [HTTP] <-- GET /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/context 200 22 ms - 20 [HTTP] [HTTP] --> GET /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362 [HTTP] {} [W3C (e952e3f8)] Driver proxy active, passing request on via HTTP proxy [debug] [WD Proxy] Matched '/wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362' to command name 'getSession' [debug] [WD Proxy] Proxying [GET /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362] to [GET http://127.0.0.1:8000/wd/hub/session/25b563385ef671864e4f67eddf813e74] with body: {} [debug] [WD Proxy] Got response with status 200: "{\"sessionId\":\"25b563385ef671864e4f67eddf813e74\",\"status\":0,\"value\":{\"acceptInsecureCerts\":false,\"acceptSslCerts\":false,\"applicationCacheEnabled\":false,\"browserConnectionEnabled\":false,\"browserName\":\"chrome\",\"chrome\":{\"chromedriverVersion\":\"2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1)\"},\"cssSelectorsEnabled\":true,\"databaseEnabled\":false,\"goog:chromeOptions\":{\"debuggerAddress\":\"localhost:55317\"},\"handlesAlerts\":true,\"hasTouchScreen\":true,\"javascriptEnabled\":true,\"locationContextEnabled\":true,\"mobileEmulationEnabled\":false,\"nativeEvents\":true,\"pageLoadStrategy\":\"normal\",\"platform\":\"ANDROID\",\"proxy\":{},\"rotatable\":false,\"setWindowRect\":false,\"strictFileInteractability\":false,\"takesHeapSnapshot\":true,\"takesScreenshot\":true,\"timeouts\":{\"implicit\":0,\"pageLoad\":300000,\"script\":30000},\"unexpectedAlertBehaviour\":\"ignore\",\"version\":\"72.0.3626.76\",\"webStorageEnabled\":true}}" [WD Proxy] Replacing sessionId 25b563385ef671864e4f67eddf813e74 with e952e3f8-cbd7-4eb7-9245-2f872e742362 [HTTP] <-- GET /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362 200 72 ms - 888 [HTTP] [HTTP] --> GET /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362 [HTTP] {} [W3C (e952e3f8)] Driver proxy active, passing request on via HTTP proxy [debug] [WD Proxy] Matched '/wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362' to command name 'getSession' [debug] [WD Proxy] Proxying [GET /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362] to [GET http://127.0.0.1:8000/wd/hub/session/25b563385ef671864e4f67eddf813e74] with body: {} [debug] [WD Proxy] Got response with status 200: "{\"sessionId\":\"25b563385ef671864e4f67eddf813e74\",\"status\":0,\"value\":{\"acceptInsecureCerts\":false,\"acceptSslCerts\":false,\"applicationCacheEnabled\":false,\"browserConnectionEnabled\":false,\"browserName\":\"chrome\",\"chrome\":{\"chromedriverVersion\":\"2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1)\"},\"cssSelectorsEnabled\":true,\"databaseEnabled\":false,\"goog:chromeOptions\":{\"debuggerAddress\":\"localhost:55317\"},\"handlesAlerts\":true,\"hasTouchScreen\":true,\"javascriptEnabled\":true,\"locationContextEnabled\":true,\"mobileEmulationEnabled\":false,\"nativeEvents\":true,\"pageLoadStrategy\":\"normal\",\"platform\":\"ANDROID\",\"proxy\":{},\"rotatable\":false,\"setWindowRect\":false,\"strictFileInteractability\":false,\"takesHeapSnapshot\":true,\"takesScreenshot\":true,\"timeouts\":{\"implicit\":0,\"pageLoad\":300000,\"script\":30000},\"unexpectedAlertBehaviour\":\"ignore\",\"version\":\"72.0.3626.76\",\"webStorageEnabled\":true}}" [WD Proxy] Replacing sessionId 25b563385ef671864e4f67eddf813e74 with e952e3f8-cbd7-4eb7-9245-2f872e742362 [HTTP] <-- GET /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362 200 86 ms - 888 [HTTP] [HTTP] --> GET /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362 [HTTP] {} [W3C (e952e3f8)] Driver proxy active, passing request on via HTTP proxy [debug] [WD Proxy] Matched '/wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362' to command name 'getSession' [debug] [WD Proxy] Proxying [GET /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362] to [GET http://127.0.0.1:8000/wd/hub/session/25b563385ef671864e4f67eddf813e74] with body: {} [debug] [WD Proxy] Got response with status 200: "{\"sessionId\":\"25b563385ef671864e4f67eddf813e74\",\"status\":0,\"value\":{\"acceptInsecureCerts\":false,\"acceptSslCerts\":false,\"applicationCacheEnabled\":false,\"browserConnectionEnabled\":false,\"browserName\":\"chrome\",\"chrome\":{\"chromedriverVersion\":\"2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1)\"},\"cssSelectorsEnabled\":true,\"databaseEnabled\":false,\"goog:chromeOptions\":{\"debuggerAddress\":\"localhost:55317\"},\"handlesAlerts\":true,\"hasTouchScreen\":true,\"javascriptEnabled\":true,\"locationContextEnabled\":true,\"mobileEmulationEnabled\":false,\"nativeEvents\":true,\"pageLoadStrategy\":\"normal\",\"platform\":\"ANDROID\",\"proxy\":{},\"rotatable\":false,\"setWindowRect\":false,\"strictFileInteractability\":false,\"takesHeapSnapshot\":true,\"takesScreenshot\":true,\"timeouts\":{\"implicit\":0,\"pageLoad\":300000,\"script\":30000},\"unexpectedAlertBehaviour\":\"ignore\",\"version\":\"72.0.3626.76\",\"webStorageEnabled\":true}}" [WD Proxy] Replacing sessionId 25b563385ef671864e4f67eddf813e74 with e952e3f8-cbd7-4eb7-9245-2f872e742362 [HTTP] <-- GET /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362 200 84 ms - 888 [HTTP] [HTTP] --> GET /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/window/rect [HTTP] {} [W3C (e952e3f8)] Driver proxy active, passing request on via HTTP proxy [debug] [WD Proxy] Matched '/wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/window/rect' to command name 'getWindowRect' [debug] [WD Proxy] Proxying [GET /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/window/rect] to [GET http://127.0.0.1:8000/wd/hub/session/25b563385ef671864e4f67eddf813e74/window/rect] with body: {} [debug] [WD Proxy] Got response with status 200: "{\"sessionId\":\"25b563385ef671864e4f67eddf813e74\",\"status\":0,\"value\":{\"height\":0,\"width\":0,\"x\":0,\"y\":0}}" [WD Proxy] Replacing sessionId 25b563385ef671864e4f67eddf813e74 with e952e3f8-cbd7-4eb7-9245-2f872e742362 [HTTP] <-- GET /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/window/rect 200 153 ms - 106 [HTTP] [HTTP] --> POST /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/touch/perform [HTTP] {"actions":[{"action":"press","options":{"x":0,"y":0}},{"action":"wait","options":{"ms":6000}},{"action":"moveTo","options":{"x":0,"y":0}},{"action":"release","options":{}}]} [debug] [W3C (e952e3f8)] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":0,"y":0}},{"action":"wait","options":{"ms":6000}},{"action":"moveTo","options":{"x":0,"y":0}},{"action":"release","options":{}}],"e952e3f8-cbd7-4eb7-9245-2f872e742362"] [debug] [WD Proxy] Matched '/touch/perform' to command name 'performTouch' [debug] [WD Proxy] Proxying [POST /touch/perform] to [POST http://localhost:8200/wd/hub/session/86fb941c-680c-4578-ad2c-13bcb356e646/touch/perform] with body: {"startX":0,"startY":0,"endX":0,"endY":0,"steps":168} [debug] [WD Proxy] Got response with status 200: {"sessionId":"86fb941c-680c-4578-ad2c-13bcb356e646","status":0,"value":true} [debug] [W3C (e952e3f8)] Responding to client with driver.performTouch() result: true [HTTP] <-- POST /wd/hub/session/e952e3f8-cbd7-4eb7-9245-2f872e742362/touch/perform 200 6399 ms - 14 [HTTP]

**Comment by mykola-mokhnach** [comment]
As far as I can see such response is coming from chromedriver and has nothing to do with the native context. You can try to report an issue to them or just remember the screen size taken from the native context or session capabilities as a workaround.

**Comment by InvisibleExo** [comment]
Might store the size value of the device in a global Dimension  variable so I can make calls to that variable rather declare a new size every time.
