### ISSUE TITLE
Appium desktop not reading element/data from modal/popup

### ISSUE THREAD

**Issue by edwardnewbie** [appium/appium#12547]
I’m automating an app with a modal element/popup. It is a mobile banking application. When I am making a payment,i’m selecting for accounts so it’s opening a modal showing the accounts. Inspecting it it Appium desktop, it’s not locating the modal elements, instead, it is still locating the elements of the previous page.

Appium seems not able to read any data from it.

Appium version (or git revision) that exhibits the issue: 1.12.1
Last Appium version that did not exhibit the issue (if applicable):NA
Desktop OS/version used to run Appium: Windows 10
Mobile platform/version under test: Android 9.0
Real device or emulator/simulator: Real device Samsung S8 and Pixel XL API 28 android emulator
Appium CLI or Appium.app|exe: Appium Desktop

![image](https://user-images.githubusercontent.com/41273838/56784207-c12b3a80-6832-11e9-8ce0-842c0eb6913e.png)

I'm using IntelliJ for my IDE and Java.

Anyone who has the workaround on this? I've been stuck on this for three weeks!

Thanks in advance!

**Comment by mykola-mokhnach** [comment]
Please provide the server logs

**Comment by edwardnewbie** [comment]
Hi @mykola-mokhnach,

I don’t have server as I can’t inspect the element and run.

I wasn’t able to add scripts for that modal since appium is not reading it.

**Comment by mykola-mokhnach** [comment]
Sorry, but without the logs we cannot suggest nothing

**Comment by HenryColes** [comment]
@edwardnewbie @mykola-mokhnach @timotiusmargo
I am also stuck with the same issue. I am trying to automate an UWP app developed in XAML and C#.
In the home page of our app, we have a link to an about page which is opened as a modal. I have tried all the suggested tools(inspect, winAppUiRecorder & appium desktop app) to locate the elements in the about page, but no luck so far. Please help me find a solution for this issue.
