### ISSUE TITLE
Unable to set the value in EditText

### ISSUE THREAD

**Issue by srishti77** [appium/appium#12541]
I am trying to test an Android Application using Appium node js. I want to set the EditText view value to some default text. For that, I have tried the following code:
     
      element = await client.findElement('id',"package.example:id/display_name");
      assert.isNotNull(element);

       if (element) {
           const id = element[Object.keys(element)[0]]
           console.log('id is: '+id);

           await client.touchPerform([{
                action: 'tap',
                options: {element: id}
          }]);
       
      // first option that I tried:
         await element.sendkeys("value");

      //second option that I tried::
         await element.setValue("value");
      
     //third:
         await element.setText("value");

     //fourth:
         await element.addValue("value");

None of the options that I tried worked. I am using Appium(v1.12.1), Webdriverio(5.7.14), node(v8.12.0) and npm(6.4.1). Any help will be very much appreciated.

**Comment by mykola-mokhnach** [comment]
Please use Appium forum for asking questions. 

We cannot suggest nothing here without the detailed server log.
