### ISSUE TITLE
Failed test case when calling toggle_airplane_mode on AndroidP

### ISSUE THREAD

**Issue by ki4070ma** [appium/appium#12557]
## The problem

When I implement toggle_airplane_mode on python-client(https://github.com/ki4070ma/python-client/commit/5cdf7c0ed513782f214097ad7061a577ab287110) and just call toggle_airplane_mode(),  test case failed.

Error log : https://gist.github.com/ki4070ma/ec806294af85b6199eae617abdbe2a53

## Environment

* Appium version (or git revision) that exhibits the issue: 1.12.1
* Last Appium version that did not exhibit the issue (if applicable): --
* Desktop OS/version used to run Appium: macOS 10.14.4
* Node.js version (unless using Appium.app|exe): --
* Npm or Yarn package manager: --
* Mobile platform/version under test: Android 9.0
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium.app

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/ki4070ma/ec806294af85b6199eae617abdbe2a53

## Code To Reproduce Issue [ Good To Have ]

* Sample codes
   * https://github.com/ki4070ma/appium-sample/blob/master/mobile/SampleAndroidTest.py

* Python client changes
   * https://github.com/ki4070ma/python-client/commit/5cdf7c0ed513782f214097ad7061a577ab287110

**Comment by ki4070ma** [comment]
As my comments,

* From appium server logs (https://gist.github.com/ki4070ma/ec806294af85b6199eae617abdbe2a53)
   * ```adb shell settings put global airplane_mode_on 1'``` is enough to toggle airplane mode
   * ```adb am broadcast -a android.intent.action.AIRPLANE_MODE --ez state true'``` throws SecurityException

```
[ADB] Running '/Users/atsushimori/Library/Android/sdk/platform-tools/adb -P 5037 -s 13f1fd2c shell settings put global airplane_mode_on 1'
[ADB] Running '/Users/atsushimori/Library/Android/sdk/platform-tools/adb -P 5037 -s 13f1fd2c shell am broadcast -a android.intent.action.AIRPLANE_MODE --ez state true'
```

## Related codes
* https://github.com/appium/appium-android-driver/blob/63ac1732ab8a13366d7a5e7053706f92384a1ce3/lib/commands/network.js#L53

**Comment by mykola-mokhnach** [comment]
This is expected. Airplane mode switching has been disabled by Android OS since API 24

**Comment by ki4070ma** [comment]
@mykola-mokhnach 

> Airplane mode switching has been disabled by Android OS since API 24

Just to confirm, is this reason from Appium side? If possible, could you provide its reason?
In my understanding, ```adb shell settings put global airplane_mode_on 1``` can switch airplane mode even in API 28(AndroidP). So I'd like just to know the reason.

**Comment by mykola-mokhnach** [comment]
You can change the setting, but cannot broadcast the change
