### ISSUE TITLE
Simulator iOS - Second try to launch app failed.

### ISSUE THREAD

**Issue by AvrahamAtia** [appium/appium#12556]
Simulator, iPhone X 12.1
Appium: 1.12.0

08:56:13 Trying again due to the following error: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65
08:56:13 xcodebuild error message:
08:56:13 
08:56:13 2019-04-28 05:55:56.711753-0700 WebDriverAgentRunner-Runner[55328:34765287] Failed to start web server on port 53988 with error Error Domain=com.facebook.WebDriverAgent Code=1 "Unable to start web server on port 53988" UserInfo={NSLocalizedDescription=Unable to start web server on port 53988, NSUnderlyingError=0x600000df8660 {Error Domain=NSPOSIXErrorDomain Code=48 "Address already in use" UserInfo={NSLocalizedDescription=Address already in use, NSLocalizedFailureReason=Error in bind() function}}}
08:56:13 2019-04-28 05:55:56.712308-0700 WebDriverAgentRunner-Runner[55328:34765287] Last attempt to start web server failed with error Error Domain=com.facebook.WebDriverAgent Code=1 "Unable to start web server on port 53988" UserInfo={NSLocalizedDescription=Unable to start web server on port 53988, NSUnderlyingError=0x600000df8660 {Error Domain=NSPOSIXErrorDomain Code=48 "Address already in use" UserInfo={NSLocalizedDescription=Address already in use, NSLocalizedFailureReason=Error in bind() function}}}
08:56:13 2019-04-28 05:55:58.458 xcodebuild[55304:34764993]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
08:56:13 /Users/automacil/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Test-WebDriverAgentRunner-2019.04.28_5-55-51--0700.xcresult/2_Test/Diagnostics/WebDriverAgentRunner-C24757E4-3E6A-4E24-B3B2-40B985F5D8AA/WebDriverAgentRunner-BB2871EE-D78E-42D0-9105-555B62DB52CE/Session-WebDriverAgentRunner-2019-04-28_55558 AM-7qMQSU.log
08:56:13 2019-04-28 05:55:58.458 xcodebuild[55304:34764990] [MT] IDETestOperationsObserverDebug: (8E39B64D-D484-43D6-A6E5-99BB8D4F2733) Beginning test session WebDriverAgentRunner-8E39B64D-D484-43D6-A6E5-99BB8D4F2733 at 2019-04-28 55:55:58.458 AM with Xcode 10B61 on target <DVTiPhoneSimulator: 0x7ffc60d0c660> {
08:56:13 		SimDevice: Simulator_iPhoneX_12.1 (************, iOS 12.1, Booted)
08:56:13 } (12.1 (16B91))
08:56:13 2019-04-28 05:56:02.411172-0700 WebDriverAgentRunner-Runner[55339:34765971] Running tests...
08:56:13 objc[55339]: Class GCDAsyncSocketPreBuffer is implemented in both /Users/automacil/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/WebDriverAgentLib.framework/Frameworks/CocoaAsyncSocket.framework/CocoaAsyncSocket (0x121282738) and /Users/automacil/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer (0x1211f5620). One of the two will be used. Which one is undefined.
08:56:13 objc[55339]: Class GCDAsyncReadPacket is implemented in both /Users/automacil/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/WebDriverAgentLib.framework/Frameworks/CocoaAsyncSocket.framework/CocoaAsyncSocket (0x121282788) and /Users/automacil/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer (0x1211f5670). One of the two will be used. Which one is undefined.
08:56:13 objc[55339]: Class GCDAsyncWritePacket is implemented in both /Users/automacil/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/WebDriverAgentLib.framework/Frameworks/CocoaAsyncSocket.framework/CocoaAsyncSocket (0x1212827d8) and /Users/automacil/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer (0x1211f56c0). One of the two will be used. Which one is undefined.
08:56:13 objc[55339]: Class GCDAsyncSpecialPacket is implemented in both /Users/automacil/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/WebDriverAgentLib.framework/Frameworks/CocoaAsyncSocket.framework/CocoaAsyncSocket (0x121282828) and /Users/automacil/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer (0x1211f5710). One of the two will be used. Which one is undefined.
08:56:13 objc[55339]: Class GCDAsyncSocket is implemented in both /Users/automacil/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/WebDriverAgentLib.framework/Frameworks/CocoaAsyncSocket.framework/CocoaAsyncSocket (0x121282878) and /Users/automacil/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer (0x1211f5760). One of the two will be used. Which one is undefined.
08:56:14 2019-04-28 05:56:02.815950-0700 WebDriverAgentRunner-Runner[55339:34765971] [AXMediaCommon] Unable to look up screen scale
08:56:14 2019-04-28 05:56:02.817005-0700 WebDriverAgentRunner-Runner[55339:34765971] [AXMediaCommon] Unexpected physical screen orientation
08:56:14 2019-04-28 05:56:02.886666-0700 WebDriverAgentRunner-Runner[55339:34765971] [AXMediaCommon] Unable to look up screen scale
08:56:14 2019-04-28 05:56:02.905639-0700 WebDriverAgentRunner-Runner[55339:34765971] [AXMediaCommon] Unable to look up screen scale
08:56:14 2019-04-28 05:56:02.905927-0700 WebDriverAgentRunner-Runner[55339:34765971] [AXMediaCommon] Unexpected physical screen orientation
08:56:14 Restarting after unexpected exit or crash in UITestingUITests/testRunner; summary will include totals from previous launches.
08:56:14 Test Suite 'Selected tests' started at 2019-04-28 05:56:03.333
08:56:14 Test Suite 'WebDriverAgentRunner.xctest' started at 2019-04-28 05:56:03.338
08:56:14 Test Suite 'WebDriverAgentRunner.xctest' failed at 2019-04-28 05:56:03.340.
08:56:14 	 Executed 1 test, with 1 failure (0 unexpected) in 0.000 (0.002) seconds
08:56:14 Test Suite 'WebDriverAgentLib.framework' started at 2019-04-28 05:56:03.343
08:56:14 Test Suite 'WebDriverAgentLib.framework' passed at 2019-04-28 05:56:03.345.
08:56:14 	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.002) seconds
08:56:14 Test Suite 'Selected tests' failed at 2019-04-28 05:56:03.348.
08:56:14 	 Executed 1 test, with 1 failure (0 unexpected) in 0.000 (0.015) seconds
08:56:14 Test session results and logs:
08:56:14 	/Users/automacil/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Test-WebDriverAgentRunner-2019.04.28_5-55-51--0700.xcresult
08:56:14 2019-04-28 05:56:07.300 xcodebuild[55304:34764990] [MT] IDETestOperationsObserverDebug: 13.878 elapsed -- Testing started completed.
08:56:14 2019-04-28 05:56:07.300 xcodebuild[55304:34764990] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
08:56:14 2019-04-28 05:56:07.300 xcodebuild[55304:34764990] [MT] IDETestOperationsObserverDebug: 13.878 sec, +13.878 sec -- end
08:56:14 Failing tests:
08:56:14 	-[UITestingUITests testRunner]
08:56:14 ** TEST EXECUTE FAILED **
08:56:14 Testing started on 'Simulator_iPhoneX_12.1'". (WARNING: The server did not provide any stacktrace information)
08:56:14 Command duration or timeout: 212.68 seconds
08:56:14 Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
08:56:14 System info: host: 'automacus', ip: '172.22.218.104', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '11.0.1'
08:56:14 Driver info: infra.driver.initializations.IOS**Driver

**Comment by mykola-mokhnach** [comment]
Please attach the full log

**Comment by yadavanand** [comment]
@AvrahamAtia Did you manage to find a solution to this problem?

**Comment by abhaygoel** [comment]
I have the same issue. Please advice.

**Comment by yadavanand** [comment]
try using "useNewWDA": "true" in desired capabilities
