### ISSUE TITLE
Appium 1.8.1 time-zone capability does not work on Android 

### ISSUE THREAD

**Issue by raolaks** [appium/appium#12550]
## The problem

Running a test with time-zone capability does not work on Android devices. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable): None
* Desktop OS/version used to run Appium: Linux 
* Node.js version (unless using Appium.app|exe): Using Appium.exe
* Npm or Yarn package manager: -
* Mobile platform/version under test: Android GoogleAPI Emulator
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Appium.exe

## Details

On tests against Android GoogleAPI Emulator using Appium 1.8.1 run against Android emulator on Linux VM, we are noticing the time-zone or timeZone capability setting does not change the device time.

## Link to Appium logs

https://github.com/raolaks/AppiumLogs.git

## Code To Reproduce Issue [ Good To Have ]
            DesiredCapabilities caps = DesiredCapabilities.android();
		  caps.setCapability("appiumVersion", "1.8.1");
		  caps.setCapability("deviceName","Android GoogleAPI Emulator");
		  caps.setCapability("time-zone", "Tunis");
		  caps.setCapability("deviceOrientation", "portrait");
		  caps.setCapability("browserName", "chrome");
		  caps.setCapability("platformVersion","8.1");
		  caps.setCapability("platformName","Android");
		  caps.setCapability("name", "myAppiumTest");*/
	  
	   WebDriver driver = new RemoteWebDriver(new URL(URL), caps);
            driver.get("http://www.google.com");

**Comment by mykola-mokhnach** [comment]
I never knew that such capability exists for Android. Can you please point out where it is documented?

Although, you could still change time on your device using shell commands like it is described at https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/android-shell.md

BTW:

> Consider setting 'automationName' capability to 'uiautomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.

And Appium v1.8.1 is out of date

**Comment by raolaks** [comment]
You are correct. The capability is something that is supported as part of Sauce Lab's testing options on their VMs as documented [here](https://wiki.saucelabs.com/display/DOCS/Test+Configuration+Options#TestConfigurationOptions-CustomTimeZones)

I think it would be accurate to re-classify this as a feature request to add the time zone capability for Appium.

**Comment by mykola-mokhnach** [comment]
I agree that it would be better to describe a new feature request. Closing this one as not an issue
