### ISSUE TITLE
Issue on Original error: io.appium.uiautomator2.common.exceptions.UiAutomator2Exception

### ISSUE THREAD

**Issue by ndeztea** [appium/appium#12555]
## The problem

Since the latest version of Appium and latest version genymotion I always get  similar error like this :
```
  An unknown server-side error occurred while processing the command. Original error: io.appium.uiautomator2.common.exceptions.UiAutomator2Exception: Timed out after 10000 milliseconds waiting for root AccessibilityNodeInfo
```

But this issue only happens after running several  test cases on Continues Integration, I am using GOCD.

I never get this issue on prev appium version

## Environment

* Appium version (or git revision) that exhibits the issue: Version 1.12.1
* Last Appium version that did not exhibit the issue (if applicable):  Version 1.9.x
* Desktop OS/version used to run Appium: MacOS
* Node.js version (unless using Appium.app|exe):  Version 8.2.0
* Npm or Yarn package manager: Npm
* Mobile platform/version under test: Android 7.0 API 24 Genymotion
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: cli

## Link to Appium logs

This is not appium log, hard to trace it since we run it on paralel test, but I hope this log will help : https://gist.github.com/ndeztea/fdc04854613a3593b0e11f7ac4a20d1d

## Code To Reproduce Issue [ Good To Have ]

This is a frequently issues, I get this issue after several test cases cant be replicated from 1 test cases only, maybe related with memory issue, I don't know..Currently, I can solve this issue after I restart genymotion and appium as well

Thank you for the great work!

**Comment by mykola-mokhnach** [comment]
I don't think there is anything we can do on Appium side, since `getRootNode` is a system function call.

**Comment by mykola-mokhnach** [comment]
Just for the context: https://stackoverflow.com/questions/51999425/got-null-root-node-from-accessibility-uiautomator

Also, some people say that rebooting the device sometimes helps to resolve such error

**Comment by ndeztea** [comment]
is it possible to increase this timeout value? 
``
Timed out after 10000 milliseconds waiting for root AccessibilityNodeInfo
``

Because on prev appium version is working fine, I am curious with this issue, caused by appium update or genymotion update

**Comment by mykola-mokhnach** [comment]
No, this value is hardcoded. You can try to build your own server app though. The constant can be changed at https://github.com/appium/appium-uiautomator2-server/blob/320a3a30f48a5a89a8b18d5bcc42d798e9344da2/app/src/main/java/io/appium/uiautomator2/utils/AXWindowHelpers.java#L33
