### ISSUE TITLE
How can i pass parameter from testng.xml

### ISSUE THREAD

**Issue by Amrkamel1** [appium/appium#12551]
How i can pass parameter to baseSetup class from testng.xml file knowing that im using page object model (baseSetup class from initiate android driver and capabilities - page class contains elements and steps - test class )  test class doesnt have any required parameters to be passed 

All the parameters below are required for capabilities and initating appium server progromatically with specific argument (host , port , bootstrap, callback port) that exits in baseSetup class not the test class

The below xml file give me weird behaviour and was sending wrong values even mixing or switching them 

`
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="TestSuite" thread-count="3" >
<parameter name="deviceId" value="192.168.30.19:5555" />
<parameter name="sysPort" value="4000" />
<parameter name="URL_" value="0.0.0.0" />
<parameter name="BootStrap" value="2299" />
<classes>
</class> "src.main.loginTest"
</classes>
</test>
</suite>
`

**Comment by mykola-mokhnach** [comment]
Kindly use appium forum to ask questions
