### ISSUE TITLE
Feature request to add time-zone capability support for Appium

### ISSUE THREAD

**Issue by raolaks** [appium/appium#12567]
## The problem

Currently, there is no way to set time-zone via capability setting as part of automation tests using Appium.

## Environment

* Appium version (or git revision) that exhibits the issue: All
* Last Appium version that did not exhibit the issue (if applicable): None
* Desktop OS/version used to run Appium: Linux
* Node.js version (unless using Appium.app|exe): Using Appium.exe
* Npm or Yarn package manager:
* Mobile platform/version under test: Android GoogleAPI Emulator
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Appium.exe

## Details

Currently, there is no way to set time-zone through capability settings on on any device using Appium.

## Link to Appium logs
None

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]
None exists as this is a feature request. Something along the lines of 
 caps.setCapability("time-zone", "Tunis");
would be helpful.

**Comment by mykola-mokhnach** [comment]
As far as I can see a timezone could be set using adb shell call: https://stackoverflow.com/questions/8062827/how-do-i-change-timezone-using-adb

Is https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/android-shell.md not working for you?

**Comment by raolaks** [comment]
This is a viable workaround if one has access to the physical device or has a dedicated device where adb can be installed. 
Unfortunately, this does not work for us (Sauce Labs) as we execute test automations on devices in cloud and shared between multiple users. We don't install adb for each session or device.

**Comment by KazuCocoa** [comment]
For Android device, we need below permission if we would like to set the timezone via settings apk.
https://developer.android.com/reference/android/Manifest.permission#SET_TIME_ZONE

Unfortunately, the permission does not allow to 3rd party app.
Maybe, only via adb can change it.

**Comment by raolaks** [comment]
In order to accomplish this as part of automation test script, it has to be an Appium capability and implemented as a new feature. There are ways to doing this via adb, but that does'nt work incase of   automation tests using Appium.

**Comment by KazuCocoa** [comment]
> There are ways to doing this via adb

Do you have another idea to change timezone for all OS versions?
(I have not found an idea, so, it's very appreciated if you have it.)


I got below error message on real Android P device and android 8.0 emulators. Maybe, some lower API level devices could though.

```
$ adb shell setprop persist.sys.timezone "America/Los_Angeles"
setprop: failed to set property 'persist.sys.timezone' to 'America/Los_Angeles'
```

I thought two ways were possible to implement it in Appium.

1. Add the adb command in https://github.com/appium/appium-adb and call it via appium-android-driver
    - Got `setprop: failed to set property 'persist.sys.timezone' to 'America/Los_Angeles'` so maybe it's impossible to handle it via `setprop` on newer android OS version
2. Add the feature in https://github.com/appium/io.appium.settings such as changing device locale
    - But maybe it's impossible because of `SET_TIME_ZONE` permission is required to change timezone https://github.com/appium/appium/issues/12567#issuecomment-488183501

---

> We don't install adb for each session or device.

Do you mean adb command such as `adb shell getprop ro.build.version.release` which called in Appium does not work on your environment? (just my curiosity)

**Comment by mykola-mokhnach** [comment]
> Unfortunately, this does not work for us (Sauce Labs) as we execute test automations on devices in cloud and shared between multiple users. We don't install adb for each session or device.

Didn't you say, that Saucelabs already has this feature? Or you mean it exists, but does not work as expected?

**Comment by raolaks** [comment]
Sauce currently has the capability to set timezone only for Desktop Test VMs. 
We don't have this for Appium. Hence this feature request.

**Comment by mrk-han** [comment]
Would be nice to have something like `desiredCapabilities.setCapability("timeZone", "New_York");`

**Comment by mrk-han** [comment]
Also, @mykola-mokhnach just having a workaround for ONLY Android seems a bit lame to try to dismiss this feature request. Is this already supported on iOS?

For more information on what Saucelabs supports: https://support.saucelabs.com/hc/en-us/community/posts/360029193973-Setting-timeZone-on-Android-emulator?page=1#community_comment_360009460433

So, this does NOT work with emulator/simulators

**Comment by nimaiwalsh** [comment]
I concur, this would be an awesome Capability feature. Many tests rely on a specific system timezone. We have run into issues with AWS Device Farm where there has been no consistency with device timezones, we need some form of control to dictate what the system uses.

**Comment by mikhailnersesov** [comment]
Havind the same issue on Experitest-Seetest Device Farm, any new solutions meanwhile?
