### ISSUE TITLE
App is taking too long to launch when using Appium

### ISSUE THREAD

**Issue by ariesranjan** [appium/appium#12566]
**Problem**

App is taking 3-4 minutes to launch for every scenarios for Android real devices. I have already used 'fullReset: false' & 'noReset:true' capabilities, however app launch time is still same.

**Environment Details**

Appium version (or git revision) that exhibits the issue: 1.6.2
Last Appium version that did not exhibit the issue (if applicable): Didn't downgraded/upgraded the version
Desktop OS/version used to run Appium: Windows 10
Node.js version (unless using Appium.app|exe): 8.10.0
Npm or Yarn package manager: npm
Mobile platform/version under test: Android
Real device or emulator/simulator: Real Device
Appium CLI or Appium.app|exe: cli

Please let me know if you need more information.

**Comment by KazuCocoa** [comment]
Can you follow our issue template?
I guess you are addressing iOS and xcuitest driver though. In the case also it's helpful to attach logs in order to understand your situation.

**Comment by ariesranjan** [comment]
@KazuCocoa Thanks for your response. I have updated the issue details. Please let me know if you need more information on this.

**Comment by mykola-mokhnach** [comment]
Version 1.6.2 is out of date, please use the most recent one

Also, the full server log is needed

**Comment by KazuCocoa** [comment]
Newer Appium has re-using existing servers on the device. If the slow is re-installing them every time etc, it should be fixed. Please try out the latest one first.
