### ISSUE TITLE
Explain the usage of elementid in Appium inspector version 1.12.1

### ISSUE THREAD

**Issue by varun-neumtech** [appium/appium#12561]
## The problem

Explain the usage of elementid attribute in Appium inspector

## Environment

* Appium version 1.12.1

**Comment by mykola-mokhnach** [comment]
Please use Appium forum for questions

**Comment by varun-neumtech** [comment]
Appium forum means, where i reach that?

**Comment by KazuCocoa** [comment]
here it is https://discuss.appium.io/ in https://github.com/appium/appium#user-forums
