### ISSUE TITLE
Thanks for answer,but the WebDriverAgent is work in IPhone 6s (IOS 11)  Mac os 9.x  Xcode 9.x  , so I think that the sign/deploy is correct.

### ISSUE THREAD

**Issue by scvjx** [appium/appium#12564]
Thanks for answer,but the WebDriverAgent is work in IPhone 6s (IOS 11)  Mac os 9.x  Xcode 9.x  , so I think that the sign/deploy is correct.
Because I need to use Appium in IPhone xs(IOS12) , the old MacOS Xcode don't support, so I update the mac os to 10.x xcode 10.x  . WDA is dosen't  work.  WDA can install in iPhone xs ,but Xcode test is failure and it doesn't display trust alert when running WDA in iPhone .

_Originally posted by @scvjx in https://github.com/appium/appium/issues/12562#issuecomment-487793646_

**Comment by KazuCocoa** [comment]
> WDA is dosen't work. WDA can install in iPhone xs ,but Xcode test is failure and it doesn't display trust alert when running WDA in iPhone .

Do you mean you should trust the personal sign via settings>general>profile by manual?
