### ISSUE TITLE
Calling getPageSource() works on initial splash screen, but hangs once login fields appear.

### ISSUE THREAD

**Issue by PHUITesting** [appium/appium#12577]
## The problem

We are trying to use appium to log into the app, apparently it cannot see any elements no matter what locator we pass it, including those directly from appium's own inspector. Additionally when using getPageSource() in order to return the exact elements, the function hangs without error message.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.12.1
* Desktop OS/version used to run Appium: Windows 10 Home
* Node.js version (unless using Appium.app|exe): 10.15.3
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Android 8.1.0
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: both

## Link to Appium logs

https://gist.github.com/PHUITesting/422450e72b453f83638122aa42d7d433

## Code To Reproduce Issue [ Good To Have ]

 ``` 
async getPageSource() {
    browser = this.helpers["Appium"].browser;
    console.log(await browser.getPageSource());
    return browser.getPageSource();
  }
```

Trying to automate this app - https://play.google.com/store/apps/details?id=com.yum.pizzahut&hl=en_US

**Comment by KazuCocoa** [comment]
Could you attach logcat as well?
If something happens behind the UIA2 server on the device side, it helps us.

**Comment by mykola-mokhnach** [comment]
@PHUITesting UIAutomator 1 is obsolete and should not be used for Android6+

@KazuCocoa It is not UIA2
