### ISSUE TITLE
Not able to save the screen record video

### ISSUE THREAD

**Issue by parikhparth23** [appium/appium#12578]
I am not able to see the screen record video of ios simulator. Where it is saved?

        @Test(priority = 1)

        public void testScreenRecord() {

         this.init(driver);

         driver.startRecordingScreen();

         driver.findElementByName("click me").click();

         driver.stopRecordingScreen();
      }

**Comment by parikhparth23** [comment]
@KazuCocoa @mykola-mokhnach  any idea how to where it is saved?
any help is a blessing.

**Comment by KazuCocoa** [comment]
Please use appium forum first to ask questions :)
