### ISSUE TITLE
--relaxed_security flag should whitelist features

### ISSUE THREAD

**Issue by jlipps** [appium/appium#12579]
## The problem

Currently, 2 or 3 features require the `--relaxed_security` flag. Let's imagine a scenario where we add a new feature down the road, which requires the flag, but which has drastically different security ramifications than the current set of features. Someone would upgrade Appium, and unwittingly open up a security hole they hadn't considered. 

## The solution

Should probably offer a whitelist of features, so it'd be like:

```
appium --relaxed_security=server_logs
appium --relaxed_security=all
appium --relaxed_security=mobile_shell,server_logs
```

**Comment by imurchie** [comment]
I agree with this. Except the `'all'` option part, which I feel would open the same hole. These should be fully opt-in.

**Comment by mykola-mokhnach** [comment]
Closed as fixed
