### ISSUE TITLE
driver.setLocation() method not working with iOS simulators

### ISSUE THREAD

**Issue by Jagadish4421** [appium/appium#12575]
## The problem
I was trying to set location for simulator iPhone XS (12.1)
Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue: 1..13.0
* Last Appium version that did not exhibit the issue (if applicable): 1.12.1
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: IOS
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe:
*Xcode Version : 10.2.1
## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by KazuCocoa** [comment]
Could you attach the full log?
btw, what about running `idevicelocation` directly like `idevicelocation 0 100` on your machine?

I was able to run it on my iPhone SE 12.2, Xcode 10.2.1.
Appium calls the command internally.

**Comment by Jagadish4421** [comment]
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not complete operation. Make sure Simulator UI is running and the parent Appium application (e. g. Appium.app or Terminal.app) is present in System Preferences > Security & Privacy > Privacy > Accessibility list. If the operation is still unsuccessful then it is not supported by this Simulator. Original error: Command 'osascript -e '
        tell application "System Events"
          tell process "Simulator"
            set frontmost to false
            set frontmost to true
            click (menu item 1 where (its name contains "iPhone XS -" and its name contains "12.1")) of menu 1 of menu bar item "Window" of menu bar 1
          end tell
        end tell
      

        tell application "System Events"
          tell process "Simulator"
            set featureName to "Custom Location"
            set dstMenuItem to menu item (featureName & "…") of menu 1 of menu item "Location" of menu 1 of menu bar item "Debug" of menu bar 1
            click dstMenuItem
            delay 1
            set value of text field 1 of window featureName to "20"
            delay 0.5
            set value of text field 2 of window featureName to "78"
            delay 0.5
            click button "OK" of window featureName
            delay 0.5
            set isInvisible to (not (exists (window featureName)))
          end tell
        end tell
      '' exited with code 1

**Comment by Jagadish4421** [comment]
I have terminal.app and appium.app in my privacy accessibility

**Comment by Jagadish4421** [comment]
I am running on iPhone XS 12.1

**Comment by mykola-mokhnach** [comment]
On simulator the fbsimctl tool might be used in order to set geolocation. Do you have it installed? If not. You can also use appium-doctor to check the necessary dependencies

**Comment by Jagadish4421** [comment]
Even after installing fbsimctl, it says not installed when i run appium-doctor

**Comment by Jagadish4421** [comment]
brew install fbsimctl --HEAD
Updating Homebrew...
==> Installing fbsimctl from facebook/fb
==> Cloning https://github.com/facebook/FBSimulatorControl.git
Updating /Users/jagadishkumar/Library/Caches/Homebrew/fbsimctl--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 117af85 Use stop_wrapper in instruments
==> ./build.sh fbsimctl build /usr/local/Cellar/fbsimctl/HEAD-117af85
Last 15 lines from /Users/jagadishkumar/Library/Logs/Homebrew/fbsimctl/01.build.sh:
./build.sh
fbsimctl
build
/usr/local/Cellar/fbsimctl/HEAD-117af85

using target fbsimctl
using command build
using output directory /usr/local/Cellar/fbsimctl/HEAD-117af85
/usr/local/opt/carthage/bin/carthage
/private/tmp/fbsimctl-20190502-63407-8kyftu/fbsimctl /private/tmp/fbsimctl-20190502-63407-8kyftu
*** Checking out GCDWebServer at "3.3.3"
*** Cloning GCDWebServer
A shell task (/usr/bin/env git clone --bare --quiet https://github.com/swisspol/GCDWebServer.git /Users/jagadishkumar/Library/Caches/org.carthage.CarthageKit/dependencies/GCDWebServer) failed with exit code 1:
/Users/jagadishkumar/Library/Caches/org.carthage.CarthageKit/dependencies/GCDWebServer: Operation not permitted


If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/facebook/homebrew-fb/issues

**Comment by Jagadish4421** [comment]
I got this when i did brew install fbsimctl --HEAD

**Comment by Jagadish4421** [comment]
It did nt help..any other help?

**Comment by KazuCocoa** [comment]
Did you fail to build `fbsimctl` on the 1.0.0 tag? (any logs?)


Apple Script sometimes fails to complete, so we call `fbsimctl` first to make the method stable.

Restarting your host machine might help to work AppleScript.
(I faced similar experiences before and they worked again after rebooting my macOS before...)

**Comment by mykola-mokhnach** [comment]
Closed as not an issue. Please contact Facebook developers about the optimal method of fbsimctl building. This tool is not under our control
