### ISSUE TITLE
Success requests send twice

### ISSUE THREAD

**Issue by ddubtsov35** [appium/appium#12582]
java-client: 6.1.0
selenide-appium: 1.0
selenide: 4.12.3

Part of logs:
[HTTP] --> POST /wd/hub/session/f4466908-2e77-4e42-b8e5-a361c4f65058/element
[HTTP] {"using":"xpath","value":"//XCUIElementTypeCell[XCUIElementTypeStaticText[@value='text']]"}
[HTTP] <-- POST /wd/hub/session/f4466908-2e77-4e42-b8e5-a361c4f65058/element 200 6524 ms - 137
[HTTP]
[HTTP] --> POST /wd/hub/session/f4466908-2e77-4e42-b8e5-a361c4f65058/element/E9000000-0000-0000-5C0F-000000000000/element
[HTTP] {"id":"E9000000-0000-0000-5C0F-000000000000","using":"xpath","value":"XCUIElementTypeStaticText[@value='text']"}
[HTTP] <-- POST /wd/hub/session/f4466908-2e77-4e42-b8e5-a361c4f65058/element/E9000000-0000-0000-5C0F-000000000000/element 200 744 ms - 137
[HTTP]
[HTTP] --> GET /wd/hub/session/f4466908-2e77-4e42-b8e5-a361c4f65058/element/BC000000-0000-0000-5C0F-000000000000/displayed
[HTTP] {}

[W3C (f4466908)] Driver proxy active, passing request on via HTTP proxy
[WD Proxy] Replacing sessionId 824542B6-FF9D-4D00-9FD6-8DCA83404887 with f4466908-2e77-4e42-b8e5-a361c4f65058
[HTTP] <-- GET /wd/hub/session/f4466908-2e77-4e42-b8e5-a361c4f65058/element/BC000000-0000-0000-5C0F-000000000000/displayed 200 331 ms - 76
[HTTP]
[HTTP] --> POST /wd/hub/session/f4466908-2e77-4e42-b8e5-a361c4f65058/element
[HTTP] {"using":"xpath","value":"//XCUIElementTypeCell[XCUIElementTypeStaticText[@value='text']]"}
[HTTP] <-- POST /wd/hub/session/f4466908-2e77-4e42-b8e5-a361c4f65058/element 200 6061 ms - 137
[HTTP]
[HTTP] --> POST /wd/hub/session/f4466908-2e77-4e42-b8e5-a361c4f65058/element/E9000000-0000-0000-5C0F-000000000000/element
[HTTP] {"id":"E9000000-0000-0000-5C0F-000000000000","using":"xpath","value":"XCUIElementTypeStaticText[@value='text']"}
[HTTP] <-- POST /wd/hub/session/f4466908-2e77-4e42-b8e5-a361c4f65058/element/E9000000-0000-0000-5C0F-000000000000/element 200 740 ms - 137

You may see what requests send twice although in first time request is 200

**Comment by mykola-mokhnach** [comment]
There is not enough information to say something for sure, but I cannot understand how exactly the problem is related to Appium server? It is the client who is sending requests

**Comment by ddubtsov35** [comment]
Sorry, i don't know where create this issue and created his in this place and in java-client repo

**Comment by ddubtsov35** [comment]
How info you need?

**Comment by mykola-mokhnach** [comment]
Java client is a better place, but I would rather focus on higher-level frameworks first
