### ISSUE TITLE
UIautomator2 parallel execution issue

### ISSUE THREAD

**Issue by rajkumar-cp** [appium/appium#12589]
## The problem

While i tried to run android devices parallely by adding uiautomator2 as automationname script fails with an random issue.
While running sequentially i am not facing this issue.
PFA the supporting documents

## Environment

* Appium version (or git revision) that exhibits the issue:1.10.0
* Last Appium version that did not exhibit the issue (if applicable):NA
* Desktop OS/version used to run Appium:win 10
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: android 7
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: exe

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/rajkumar-cp/b48e268f33915357ea0cb2a983341f4c
https://gist.github.com/rajkumar-cp/a7bf40bc9ca420e2f0b87da04bfd735c

capabilities:
					capabilities.setCapability("device",platform);
					capabilities.setCapability("deviceName",device);
					capabilities.setCapability("udid", udidvalue);
					capabilities.setCapability("platformName", platform);
					capabilities.setCapability("unicodeKeyboard", true);
					capabilities.setCapability("platformVersion",platformVersion);
					capabilities.setCapability("autoGrantPermissions", true);
					capabilities.setCapability("rotatable", true);				
					capabilities.setCapability("autoAcceptAlerts", true);
					capabilities.setCapability("android:noHistory", true);
					capabilities.setCapability("appPackage","com.mfiles.mobile"); 
					capabilities.setCapability("app", androidAppPath);
					capabilities.setCapability("LAUNCH_TIMEOUT","1000000");				 
  capabilities.setCapability("appActivity","com.mfiles.mobile.activity.SplashActivity");
					capabilities.setCapability("adbExecTimeout", "180000");
					capabilities.setCapability("androidInstallTimeout", "180000");
					capabilities.setCapability("automationName", "uiautomator2");

Appium details:
device 1:
serverport:4723
bootstrapport 100
webdriveragentport: 8100
selendroid port 8080

device2:
serverport:4733
bootstrapport 200
webdriveragentport: 8100
selendroid port 8080

Ambiguity: Could you please let me know what value i should pass for systemport capability. Is tat present in the details i have shared above or it could be random ?

**Comment by mykola-mokhnach** [comment]
> webdriveragentport is for xcuitest. Follow https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/parallel-tests.md to setup capabilities for UIA2

**Comment by rajkumar-cp** [comment]
@mykola-mokhnach 
I have tried that but still the issue persists.
according to that i should pass 3 values
udid - i passed value for this 
chromeDriverPort - i am not using webviews or chrome so i ignored it
systemPort - what should i provide here. I have opened 2 appium ports 4723 and 4733 . Should i pass that values here ?

**Comment by mykola-mokhnach** [comment]
systemPort must not be the same as the appium server port

**Comment by rajkumar-cp** [comment]
@mykola-mokhnach 

Thanks a lot. It worked fine after adding systemPort capability . We are good to close this issue.
