### ISSUE TITLE
Mic is still disabled in my app after allow permission notification

### ISSUE THREAD

**Issue by LayMuiToh** [appium/appium#12580]
## The problem

When I launch the app using the ios simulator (I am using ipad pro 12.9-inch 3rd generation
it will show a my-appname like to access your microphone. which it click Allow
but when I login, the mic icon to access the microphone to speak is disabled

my desired capabilities is set as follow:
capabilities: [{
// maxInstances can get overwritten per capability. So if you have an in-house Selenium
// grid with only 5 firefox instances available you can make sure that not more than
// 5 instances get started at a time.
browserName: ‘’,
appiumVersion: process.env.APPIUMVERSION,
platformVersion: process.env.PLATFORMVERSION,
platformName: ‘iOS’,
deviceName: process.env.DEVICENAME,
udid: process.env.UDID,
app: process.env.APPPATH,
bundleId: process.env.BUNDLEID,
orientation: ‘LANDSCAPE’,
noReset: false,
usePrebuiltWDA: true,
newCommandTimeout: 7000,
printPageSourceOnFindFailure: true,
maxTypingFrequency: 20,
// autoDismissAlerts: true,
autoGrantPermissions: true,
autoAcceptAlerts: true

}],

## Environment

* Appium version (or git revision) that exhibits the issue:1.12.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:macOS Mojave 10.14.4
* Node.js version (unless using Appium.app|exe):10.15.1
* Npm or Yarn package manager:6.4.1
* Mobile platform/version under test:ipad pro (12.9 inch) 3rd generation v.12.2
* Real device or emulator/simulator: iOS simulator
* Appium CLI or Appium.app|exe:appium.exe

## Details

after my test is completed without success since the mic is disabled
I click on the app and relaunch it manually, and the app open with the mic enabled this time.
the question is why is the mic get disabled during the test run?
is there any desired capabilities I need to set or unset?

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
There is no `autoGrantPermissions` capability on iOS. On iOS Simulator, though, the `permissions` capability is supported, which allows to set some iOS specific permissions using WIX tools (should be installed separately, check Appium-doctor output if you need help with that). 

Care to attach the server log?
