### ISSUE TITLE
Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder “WebDriverAgentRunner_iphoneos12.2-arm64.xctestrun” doesn’t exist."

### ISSUE THREAD

**Issue by aryalakshmi** [appium/appium#12581]
## The problem

WebdriverAgent installation is failing on OpenApplication using appium

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13
* Last Appium version that did not exhibit the issue (if applicable): 1.12.1
* Desktop OS/version used to run Appium: NA
* Node.js version (unless using Appium.app|exe): v11.8.0
* Npm or Yarn package manager:npm 6.9.0
* Mobile platform/version under test: iOS 12.2
* Real device or emulator/simulator: Real Device iPhone 5s
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

https://gist.github.com/aryalakshmi/185e25521ec9c11b89e2b5353f130e1c

```
[Appium] Capabilities:
[Appium]   platformName: iOS
[Appium]   deviceName: 'iPhone'
[Appium]   wdaStartupRetryInterval: 20000
[Appium]   xcodeOrgId: xxxxxxxxxxxx
[Appium]   udid: c7b2d2268ef08a51d3a732bd82fc6e5bb9668e35
[Appium]   webkitResponseTimeout: 180000
[Appium]   automationName: XCUITest
[Appium]   noReset: false
[Appium]   autoWebview: true
[Appium]   xcodeSigningId: iPhone Developer
[Appium]   newCommandTimeout: 1200
[Appium]   platformVersion: 12.2
[Appium]   fullReset: false
[Appium]   shouldUseSingletonTestManager: false
[Appium]   waitForQuiescence: false
[Appium]   bundleId: com.xxx.xxxx
```

**Comment by KazuCocoa** [comment]
```
[Xcode] Testing failed:
[Xcode] 
[Xcode] 	"WebDriverAgentRunner" requires a provisioning profile. Select a provisioning profile for the "Debug" build configuration in the project editor. (in target 'WebDriverAgentRunner')
[Xcode] 	WebDriverAgentRunner:
[Xcode] 		WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file. The file doesn’t exist. (Underlying error: The operation couldn’t be completed. No such file or directory)))
[Xcode] 
[Xcode] Test session results and logs:
[Xcode] 	/Users/digitalhome/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Test-WebDriverAgentRunner-2019.05.03_12-17-17-+0530.xcresult
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[Xcode] Testing started on 'PT’s iPhone 5s'
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[XCUITest] Launching WebDriverAgent on the device
```

It looks like a code signing issue.

Can your xcodeOrgId sign the WDA named `com.facebook.WebDriverRunner`?
You can make sure the provisioning sign can work by manual following http://appium.io/docs/en/drivers/ios-xcuitest-real-devices/

You can change the name by `updatedWDABundleId` as a part of capabilities.

**Comment by aryalakshmi** [comment]
Thankyou for the help.
This issue was fixed by the below resolution:
1)use appium 1.13 
2) Change below arguments in OpenApplication
updatedWDABundleId=com.xyz.abc xcodeConfigFile=path
3) Run WDA manually once from below xcode project
/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
4) Remove any existing WDA

**Comment by SebastianSolidwork** [comment]
@aryalakshmi Could you describe step 3 more in detail? I'm troubling with the same issue.
about 3: you mean a normal build? Or what is "run"?

**Comment by AdarshKumarGM** [comment]
@aryalakshmi - Can you please explain where do we get this "OpenApplication" ?. I am trying to install on real device but it always throws error.

**Comment by KazuCocoa** [comment]
It means changing `updatedWDABundleId`  as `com.xyz.abc`, I assume.
If you have a sign valid to `com.yourorg`, then the WDA should be `com.yourorg.WebDriverAgent` (It is Apple's code signing rule)

**Comment by pacchan** [comment]
12.4.1 iOS facing the same issue. using Appium 1.13, Xcode 10.3

**Comment by pacchan** [comment]
Hi @aryalakshmi 
Can you please give more details about where can I find updatedWDABundleId? 

Thanks

**Comment by pacchan** [comment]
I think it causes an error. 

**Sending '_rpc_forwardSocketData:** . It is not getting any response at the stage. 

Is it because it is not stable testing on iOS 13 at the moment? 

It should receive a response if it works perfectly, something like:
![image](https://user-images.githubusercontent.com/30913258/69769165-9cdc7580-11e8-11ea-850a-7fa335b1406e.png)

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-xcuitest-driver and https://github.com/appium/appium/blob/master/docs/en/drivers/ios-xcuitest-real-devices.md for `updatedWDABundleId`. (And you probably need to find documentation about bundle id and the provisioning stuff for Apple iOS app development to help the understanding)

> _rpc_forwardSocketData

It should be fixed in current  `appium@beta` => https://github.com/appium/appium/issues/13603#issuecomment-555209258

**Comment by vallaranga** [comment]
@KazuCocoa Im facing the same issue **2020-06-16 12:05:57.350 xcodebuild[5182:2030617] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder “WebDriverAgentRunner_iphoneos13.5-arm64e.xctestrun” doesn’t exist." UserInfo={NSFilePath=/Users/ranganath.vallakati/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu/Build/Products/WebDriverAgentRunner_iphoneos13.5-arm64e.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7fb72ef05b30 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}**

however, i did lthe following:
1. Launch the WebDriverAgentRunner.xcodeproj in XCode and then assign the correct Team.  
2. using **updatedWDABundleId**, i did change the value to _com.my.org_

I can see that the bundleId is updated. But still fails to launch. This is the error: 

**Testing failed:
	No profiles for '_com.my.org.xctrunne_r' were found: Xcode couldn't find any iOS App Development provisioning profiles matching '_com.my.org.xctrunner_'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
	WebDriverAgentRunner:
		WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file. The file doesn’t exist. (Underlying error: The operation couldn’t be completed. No such file or directory)))**
