### ISSUE TITLE
iOS 12.2 Web Test fails on 1.13.0 because we set "-u" as argument

### ISSUE THREAD

**Issue by umutuzgur** [appium/appium#12590]
## The problem

When -u is set on iOS 12.2 to set the initial url, which is known not to work anyways, WDA times out to launch Safari

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe): 8
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS/12.2
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Details

XCUITest doesn't like it when -u is set. I don't really know reason for it but it acts weird. We observed this with Real Devices but it might be also happening on Simulators

## Code To Reproduce Issue [ Good To Have ]

Just launch Safari using WDA only and you will see the same behaviour. When -u is deleted, everything works well

**Comment by imurchie** [comment]
Interesting. Hadn't seen this happening on my devices. But the -u option was removed for MobileSafari on 12.2, so it makes sense sort of.

**Comment by umutuzgur** [comment]
Closing since @imurchie already fixed this issue with https://github.com/appium/appium-xcuitest-driver/pull/953
