### ISSUE TITLE
Enhancement: Allow Setting JWProxy Keepalive Behavior via a Capability

### ISSUE THREAD

**Issue by Dan-Maor** [appium/appium#12599]
I noticed that as part of https://github.com/appium/appium-base-driver/pull/260 the connection keepalive option (`forever`) was removed from JWProxy's `proxy` function due to a bug concerning ENOBUFS errors (https://github.com/appium/appium/issues/11380).

After running some benchmark tests using an iPhone 8 running iOS 11.0.3 I discovered that by re-adding the `forever` option to keep the connection to WDA alive the execution time was reduced by 15% on average.

Due to the above mentioned bug I don't think that this option should be set again to true by default, however I'm thinking that perhaps we can allow users to customize this option using a desired capability.

I've started looking into implementing it myself in appium-base-driver aiming to create a PR, however I would like some pointers as to where would be the best place to pass the default parameter value to the JWProxy object since I'm still in the process of getting familiar with the appium-base-driver project.

**Comment by imurchie** [comment]
This seems like a good idea!

From the perspective of the base driver, I think it would just be an option passed into the [constructor](https://github.com/appium/appium-base-driver/blob/master/lib/jsonwp-proxy/proxy.js#L19). Then when the proxy is created (e.g., for WDA, https://github.com/appium/appium-xcuitest-driver/blob/master/lib/wda/webdriveragent.js#L255-L269) that would be passed in. If similar performance benefits are had on the Android side, that would need to be implemented in the respective drivers.

**Comment by Dan-Maor** [comment]
Thanks @imurchie :)
If that's the approach, do you think it should be enabled by the users with a capability? Or should we just define WDA proxies to keep the connection alive?

**Comment by imurchie** [comment]
Yes, if this is added as an option, it could just be turned on for proxies that are managed by drivers, I guess. As long as the connections are properly released at the end...

**Comment by Dan-Maor** [comment]
Opened pull requests in appium-base-driver and appium-xcuitest-driver:
https://github.com/appium/appium-base-driver/pull/325
https://github.com/appium/appium-xcuitest-driver/pull/959

**Comment by Dan-Maor** [comment]
Pull requests merged, closing.

**Comment by imurchie** [comment]
@Dan-Maor With this merged are you seeing the kind of performance increase you saw before?

**Comment by Dan-Maor** [comment]
Definitely.
I've ran my test again (1000 iterations of find element in a simple page).
Without the change it took 76 seconds, with the change it took 68 seconds.
With 5000 iterations it took 601 seconds, and after adding the change back the execution took 460 seconds.

**Comment by imurchie** [comment]
Awesome!

Thanks for the experimentation and the solution!
