### ISSUE TITLE
Updated to Appium Desktop 1.13.0 and errors when starting a session

### ISSUE THREAD

**Issue by edwardnewbie** [appium/appium#12596]
Updated to Appium Desktop 1.13.0 and errors when starting a session

I’ve updated my Appium today and when I started a new session, this error message is displayed.
I have my test working perfectly on v1.12.1.

Do I need to change something? See attached for error message.

* Appium version (or git revision) that exhibits the issue: v1.13.0
* Last Appium version that did not exhibit the issue (if applicable): v1.12.1
* Desktop OS/version used to run Appium: Appium Desktop
* Mobile platform/version under test: Native app
* Real device or emulator/simulator: Samsung S8

my desired capabilities:
{
  "udid": "ce041714789604830d",
  "platformName": "Android",
  "platformVersion": "9.0",
  "appPackage": "com.loans.smartmoney",
  "appActivity": "com.loans.smartmoney.MainActivity",
  "automationName": "uiautomator2",
  "deviceName": "Galaxy S8"
}

ERRORS:
Could not sign with default certificate. Original error Command ''C:\\Program Files\\Java\\jdk-12\\bin\\java.exe' -jar 'C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-adb\\jars\\sign.jar' 'C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-debug-androidTest.apk' --override' exited with code 1

https://discuss.appium.io/t/updated-to-appium-desktop-1-13-0-and-errors-when-starting-a-session/26285

![image](https://user-images.githubusercontent.com/41273838/57262329-f2b3c980-70ae-11e9-90dc-68758830f50d.png)

**Comment by mykola-mokhnach** [comment]
Please provide the full server log

**Comment by edwardnewbie** [comment]
Hi @mykola-mokhnach - I've just resolved this issue just now. Thanks!
