### ISSUE TITLE
Appium v1.12.1 makes app slow when retrieving ID's

### ISSUE THREAD

**Issue by CedricD123** [appium/appium#12604]
## The problem

We are trying to scroll in a page with contains a lot of ID's, we use the touchAction to scroll on the page, it takes a long time for Appium to retrieve the ID's.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.12.1
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2
* Desktop OS/version used to run Appium: 10.14.4
* Node.js version (unless using Appium.app|exe): 10.1.0
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: iPhone 8

## Details

We are trying to scroll in a page with contains a lot of ID's, we use the touchAction to scroll on the page, it takes a long time for Appium to retrieve the ID's. When the next touchAction to scroll is being done, Appium is still retrieving the ID's of the previous swipe. Therefore the app gets stuck and the scrolling is really bad. 
My test fails because the app doesn't scroll to the ID requested. 
Then if we start another test in the same appium session, we notice that there are swipes on the screen when there is no swipe action in the code. It seems that appium is still swiping from the previous test.

## Code To Reproduce Issue [ Good To Have ]

This is the code we use to swipe, it loops this code until an specific element is found on the page.
await mobile.touchAction(selector, [
            { action: 'press', x: locationX + mobile.widthElement / 2, y: locationY + mobile.heightElement / 2 },
            { action: 'wait', ms: 2000 },
            { action: 'moveTo', x: locationX + mobile.widthElement  / 2, y: locationY - mobile.heightElement * 0.25 },
            'release'
        ]);

**Comment by mykola-mokhnach** [comment]
elements location and scrolling is done by XCTest/WebDriverAgent. Unfortunately, there is nothing that can be changed on Appium side.

**Comment by CedricD123** [comment]
> elements location and scrolling is done by XCTest/WebDriverAgent. Unfortunately, there is nothing that can be changed on Appium side.

I notice with a lower appium/xcode 1.9.2/10.0 version that this is more stable, still not perfect but more stable. So I assume from the previous comment that mainly the problem is with xcode&webdriveragent

**Comment by mykola-mokhnach** [comment]
In general each new iOS sdk brings new changes, so it is quite possible that the same client code performs differently in different environments.
