### ISSUE TITLE
Appium session times out after a long time waiting to interact with the Chrome browser

### ISSUE THREAD

**Issue by sasasa42** [appium/appium#12603]
## The problem

While the appium session is running on a web view on an Android device, the appium server waits for a long time, say around 10 minutes and finally closes by just logging an error message 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.12.1
* Last Appium version that did not exhibit the issue (if applicable): Not sure, but may be way back like 1.9.0
* Desktop OS/version used to run Appium: mac 10.14.4
* Node.js version (unless using Appium.app|exe): 10.12.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

The below error message appears even if the element is visible and this is quite intermittent.
 TimeoutException: Message: timeout: Timed out receiving message from renderer: 10.000 (Session info: chrome=73.0.3683.90)(Driver info: chromedriver=2.46.628411 (3324f4c8be9ff2f70a05a30ebc72ffb013e1a71e),platform=Mac OS X 10.13.6 x86_64)

## Link to Appium logs

No logs captured at the moment

## Code To Reproduce Issue [ Good To Have ]

No code

**Comment by mykola-mokhnach** [comment]
The error comes from chromedriver. There is nothing we can do on Appium side.
