### ISSUE TITLE
Sauce currently has the capability to set timezone only for Desktop Test VMs.

### ISSUE THREAD

**Issue by raolaks** [appium/appium#12612]
Sauce currently has the capability to set timezone only for Desktop Test VMs. 
We don't have this for Appium. Hence this feature request.

_Originally posted by @raolaks in https://github.com/appium/appium/issues/12567#issuecomment-490897612_

**Comment by mykola-mokhnach** [comment]
I've checked across the internet and people say Android only allows to change timezones via adb in rooted devices (https://stackoverflow.com/questions/35742253/unable-to-change-timezone-on-android-device-using-adb-shell-setprop), so I don't think the feature will be much of use if we add it to Android driver. Please let us know if there is any other good method to do this via terminal.

**Comment by raolaks** [comment]
Hi Mykola,
  Please keep the case open as this is a feature request. I understand this may not be something currently possible through Appium. But we would like to see this implemented as a feature.
