### ISSUE TITLE
When given locator, appium complains no locator was given.

### ISSUE THREAD

**Issue by PHUITesting** [appium/appium#12619]
-- FAILURES:

  1) Test Pizza Menu Items Pricing and Calories
       Validate all menu items, calories and pricing @regression @sanity @validMenuPizza @gg:
     Touch actions like "tap" need at least some kind of position information like "element", "x" or "y" options, you've none given.
  
  Scenario Steps:
  
  - I.tap({"xpath":"/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[2]/android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[2]/android.view.ViewGroup[2]/android.widget.TextView"}) at Test.<anonymous> (features/Pizza/PizzaMenuTests.js:74:5)

**Comment by mykola-mokhnach** [comment]
Please report the issue to the corresponding client you use. I don't see how the described problem might be related to Appium server.
