### ISSUE TITLE
Cannot run Protractor tests on iOS Simulator since update to Xcode 10.2

### ISSUE THREAD

**Issue by Cullima** [appium/appium#12611]
## The problem

I have an Ionic / Cordova hybrid application configured to run Protractor / Jasmine tests on iOS simulator.  This has worked fine until recently updating to Xcode 10.2.  Now, when trying to run tests, the app will launch but hangs indefinitely.  Console logs etc. added to the spec files will run but tests seem to get stuck as soon as any interaction with the app is attempted, e.g. element.click() or element.sendKeys(). I have incremented Appium version to 1.12.1 and 1.13.0 but get the same problem with either.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.12.1, 1.13.0
* Last Appium version that did not exhibit the issue (if applicable): 1.10.1 (with Xcode 10.1 built Ionic app)
* Desktop OS/version used to run Appium: MacOS Mojave 10.14.4
* Node.js version (unless using Appium.app|exe): 9.11.1
* Npm or Yarn package manager: 5.6.0
* Mobile platform/version under test: Ionic v3.9.5
* Real device or emulator/simulator: Apple iPhone 8 Plus simulator, iOS 12.1 or 12.2
* Appium CLI or Appium.app|exe: 

## Link to Appium logs

https://gist.github.com/Cullima/096ecc0dc67dd2cf4c10464d6ecaad45

**Comment by tomevs88** [comment]
+1

**Comment by imurchie** [comment]
Can you post the logs for a successful run (with Xcode 10.1)?

**Comment by Cullima** [comment]
[appium10_1.log](https://github.com/appium/appium/files/3162132/appium10_1.log)

Here is the output from a successful run on another machine running Xcode 10.1. I terminated part way through since the test suite takes quite a while to run. Thanks for the help.

**Comment by imurchie** [comment]
This behavior, it turns out, is expected. CORS handling was changed from defaulting to `true` to defaulting to `false` (see https://github.com/appium/appium-base-driver/commit/f66dadcd6b6d9c5632622f34c2da99e9b70a135f).

You can turn it on by using the `--allow-cors` [server argument](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md).

**Comment by Cullima** [comment]
> This behavior, it turns out, is expected. CORS handling was changed from defaulting to `true` to defaulting to `false` (see [appium/appium-base-driver@f66dadc](https://github.com/appium/appium-base-driver/commit/f66dadcd6b6d9c5632622f34c2da99e9b70a135f)).
> 
> You can turn it on by using the `--allow-cors` [server argument](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md).

Thank you for the quick response and solution. Tests are now running again!
