### ISSUE TITLE
Please treat this as a feature request

### ISSUE THREAD

**Issue by raolaks** [appium/appium#12613]
Hi Mykola,
  Please keep the case open as this is a feature request. I understand this may not be something currently possible through Appium. But we would like to see this implemented as a feature.

_Originally posted by @raolaks in https://github.com/appium/appium/issues/12612#issuecomment-490903900_

**Comment by mykola-mokhnach** [comment]
I don't see a point to keep it if it is not going to be implemented, but whatever
