### ISSUE TITLE
python: posix_spawn: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: Undefined error: 0

### ISSUE THREAD

**Issue by aryalakshmi** [appium/appium#12622]
## The problem

Appium displays below error on OpenApplication
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[XCUITest] Fetching dependencies
[XCUITest] python: posix_spawn: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: Undefined error: 0
[BaseDriver] Event 'wdaStartFailed' logged at 1557469432146 (11:53:52 GMT+0530 (IST))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[XCUITest] Quitting and uninstalling WebDriverAgent

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13 
* Last Appium version that did not exhibit the issue (if applicable): 1.12.1
* Desktop OS/version used to run Appium: OSX Mojave
* Node.js version (unless using Appium.app|exe): 12.2.0
* Npm or Yarn package manager: 6.1.0
* Mobile platform/version under test: iOS 
* Real device or emulator/simulator: Real Device iPhone5s / 12.2 iOS
* Appium CLI or Appium.app|exe: Appium.app

## Details

Digitals-MacBook-Pro-2:WebDriverAgent digitalhome$ pwd
/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
Digitals-MacBook-Pro-2:WebDriverAgent digitalhome$ 
Digitals-MacBook-Pro-2:WebDriverAgent digitalhome$ 
Digitals-MacBook-Pro-2:WebDriverAgent digitalhome$ ls
CONTRIBUTING.md			Configurations			Gemfile.lock			PATENTS				Scripts				WebDriverAgentRunner
Cartfile			Fastlane			Inspector			PrivateHeaders			WebDriverAgent.xcodeproj	WebDriverAgentTests
Cartfile.resolved		Gemfile				LICENSE				README.md			WebDriverAgentLib
Digitals-MacBook-Pro-2:WebDriverAgent digitalhome$ ./Scripts/bootstrap.sh 
Fetching dependencies
python: posix_spawn: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: Undefined error: 0
Digitals-MacBook-Pro-2:WebDriverAgent digitalhome$ 
Digitals-MacBook-Pro-2:WebDriverAgent digitalhome$ which python
/Library/Frameworks/Python.framework/Versions/2.7/bin/python

## Link to Appium logs

https://gist.github.com/aryalakshmi/6de4042f5feedee8e2da120ef96f1ebf

Please help!.

**Comment by mykola-mokhnach** [comment]
It might be your system python installation is broken. Try to install it from brew: `brew install python`. Then make sure `/usr/local/bin` is added to PATH

**Comment by aryalakshmi** [comment]
Thanks a lot. you are a saviour :) i I removed the old python path from PATH variable and brew installed the new python and added /usr/local/bin to PATH. It fixed my issue.
