### ISSUE TITLE
Replace fbsimctl with idb

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#12631]
## The problem

We use `fbsimctl` for iOS simulators.
FB renamed them with https://github.com/facebook/idb

- e.g. `setGeolocation`
    - https://github.com/search?q=org%3Aappium+fbsimctl&type=Code

For now, we can use `fbsimctl` from git repository like https://github.com/appium/appium/pull/12574 since current brew HEAD is already `idb`.

Not sure, but can we build the idb with Xcode 9 env?
(Is there  any concerns??)

**Comment by mykola-mokhnach** [comment]
I'd rather wait for now until the tool is stabilised (FB has only started this project very recently) or until we drop the support of Xcode9 ;) .

**Comment by mykola-mokhnach** [comment]
closed as fixed

**Comment by patchthecode** [comment]
does idb make the appium stack run faster?
