### ISSUE TITLE
Add Appium logo to WebDriverAgent app

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#12638]
## The problem

Add Appium icon to [WebDriverAgent](http://github.com/appium/webdriveragent) app. Right now it uses the default.

## Details

I'd like WDA to show the Appium logo so that it can be easily distinguished from other apps and it just looks nicer.

## Acceptance Criteria
* [ ] Make a PR that adds the Appium icon to WDA
* [ ] Post a screenshot that shows WDA with the Appium icon

**Comment by imurchie** [comment]
I think it'd be good to have the Appium logo on the black screen that is the UI, as well. To distinguish from failure.

**Comment by mykola-mokhnach** [comment]
[Images.xcassets.zip](https://github.com/appium/appium/files/3183459/Images.xcassets.zip)

**Comment by mykola-mokhnach** [comment]
It looks like this is not possible :(
