### ISSUE TITLE
Touch ID pop up handle on iOS application and need to click on cancel

### ISSUE THREAD

**Issue by raaghuler** [appium/appium#12641]
## The problem

After launching my application, The native ios popup get displaying for the Touch ID, Here I need to click on the cancel

I tried to use the existing alert code, But it not able to handle this pop-up

Please help out to handle the pop-up, I have attached the screenshot

## Environment

* Appium version (or git revision) that exhibits the issue:6.1.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:ios
* Real device or emulator/simulator:real device
* Appium CLI or Appium.app|exe:Appium.app 

## Details

After launching my application, The native ios popup get displaying for the Touch ID, Here I need to click on the cancel

I tried to use the existing alert code, But it not able to handle this pop-up

Please help out to handle the pop-up, I have attached the screenshot

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favorite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.
![UNADJUSTEDNONRAW_thumb_6](https://user-images.githubusercontent.com/29144150/57753852-cc270b80-770a-11e9-98e5-fa203757f408.jpg)

**Comment by mykola-mokhnach** [comment]
In case this dialog is not visible in page source then you won't be able to interact with it and this cannot be worked around. A "stupid" workaround would be to click by coordinates if possible. A smarter one is to use Simulator, where it is possible to fake Touch ID match or built a special app version for testing, where this dialog is not shown/can be disabled.
