### ISSUE TITLE
Appium communicate with wrong device when I change my device with the same wdaLocalPort

### ISSUE THREAD

**Issue by jenniferhuang** [appium/appium#12649]
## The problem

Appium communicate with wrong device when I change my device with the same wdaLocalPort  and the "useNewWDA" is set as "false"

## Environment

* Appium version: 1.13.0
* Node.js version: v8.9.1
* Npm version:  6.9.0
* Mobile platform/version under test:  ios12.0
* Real device or emulator/simulator:  real device
* Appium CLI or Appium.app|exe:  Appium CLI

## Details
This issue can always reproduce when the "useNewWDA" is set as "false".
Steps:
1. Started 2 appium server in local:
**appium4426**:   node /usr/local/bin/appium -p 4426
**appium4427**:   node /usr/local/bin/appium -p 4427
2. Have 2 ios devices
**device:**   udid1 (manually remove WDA app on the device)
**device:**   udid2 (manually remove WDA app on the device)
3. Create sessions 
I run **device:  udid1** on **appium4426** with wdaLocalPort=8888
I run **device:  udid2** on **appium4427** with wdaLocalPort=8889
as we know , it will install the WDA on devices, and 
**appium4426** will proxy to http://localhost:8888/session/xxxx
**appium4427** will proxy to http://localhost:8889/session/xxxx
4. Switch the devices to create appium drivers
(don't manually remove WDA app on the devices)
that's I run **device:  udid2** on **appium4426** with wdaLocalPort=8888, we can see the "desiredCapabilities" in the log from **appium4426** that "udid":"udid2" as expected.
5. The issue occurs 
Expected behavior:
The **appium4426**  should communicate with this device: **device:  udid2**
Actual behavior:
 The **appium4426** communicate with this device: **device:  udid1**

**Comment by mykola-mokhnach** [comment]
I would say this is more an issue of iproxy, which does not verify the given udid and the udid of the actually connected device after the connection was made. This, in theory, could be worked around on Appium side, but I'm not quite sure the scenario described above is very likely to happen.

**Comment by jenniferhuang** [comment]
Hi @mykola-mokhnach,  the scenario will be happen when we connected multi-devices on one mac. it will lead to assign device mismatch with given and cause some unexpected test issue.

**Comment by mykola-mokhnach** [comment]
Please try if https://github.com/appium/appium-xcuitest-driver/pull/965 fixes the problem. https://appiumpro.com/editions/47 contains the info on how to run Appium from source

**Comment by mykola-mokhnach** [comment]
Any updates on the fix verification? We won't be able to merge the fix without it being properly verified.

**Comment by jenniferhuang** [comment]
ok, I will try now, don't you have a try.

**Comment by mykola-mokhnach** [comment]
no, I can only test on Simulator. I don't own any iPhones (and this test requires to have two)

**Comment by jenniferhuang** [comment]
it will fail for "Encountered internal error running command: Error: Could not find a driver for automationName 'xcuitest' and platformName 'ios'. Please check your desired capabilities." when I npm link to the new "appium-xcuitest-driver".

**Comment by KazuCocoa** [comment]
Did you link with `appium-xcuitest-driver` instead of `appium-uiautomator2-driver` in  https://appiumpro.com/editions/47 ?

**Comment by jenniferhuang** [comment]
definitely, I can find the linked appium-xcuitest-driver folder under the appium node_modules. I am not sure why it can't find the driver.

**Comment by KazuCocoa** [comment]
another handy way is:

```
$ git clone [appium repo]
$ git clone [appium-xcuitest-driver repo]
$ cd  appium-xcuitest-driver
$ npm install # then `build` dir appears
$ cd ../appium
$ npm install
# Then, copy appium-xcuitest-driver/build into appium/node_modules/appium-xcuitest-driver/build
$ node . # in the top of appium dir
```

what about this way?

**Comment by jenniferhuang** [comment]
@KazuCocoa I follow your provided way, but it is all the same.  I replace the appium-xcuitest-driver with the module that appium 1.13.0's build under the appium repo/node_modules/appium-xcuitest-driver, it works fine. 
So are there any issues in the new appium-xcuitest-driver (clean_obsolete branch)

**Comment by KazuCocoa** [comment]
mm.

I met the same behaviour once, but once I clean my env, it worked.

- My env is node v11.14.0, npm 6.9.0
- $ npm run clean # in the appium-repo and xcuitest-driver repo

and follow my previous comment again.
Could you try again?

**Comment by jenniferhuang** [comment]
thanks @KazuCocoa 
@mykola-mokhnach verified it. it worked fine now.

**Comment by mykola-mokhnach** [comment]
Thanks, merging the fix.

**Comment by mykola-mokhnach** [comment]
The change has been published in beta

**Comment by jenniferhuang** [comment]
good to hear.
