### ISSUE TITLE
Unable to start tests on real iOS devices

### ISSUE THREAD

**Issue by jlee6890** [appium/appium#12640]
## The problem

I'm not able to run tests on my iPhone 7 Plus. And yes, I followed https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

Well, at least up to the Full manual configuration part.

See Appium logs for failures

## Environment

* Appium version (or git revision) that exhibits the issue: **1.13.0**
* Last Appium version that did not exhibit the issue (if applicable): **N/A**
* Desktop OS/version used to run Appium: **macOS Mojave (10.14.4)**
* Node.js version (unless using Appium.app|exe): **10.12.0**
* Npm or Yarn package manager: **Npm**
* Mobile platform/version under test: **iOS 12.2**
* Real device or emulator/simulator: **Real device**
* Appium CLI or Appium.app|exe: **Appium CLI**

## Details

I'm getting an issue when trying to sign WebDriverAgentRunner, which led me to follow the documentation about creating a provisioning profile, but it too has issues with signing:

![Screen Shot 2019-05-14 at 5 03 38 PM](https://user-images.githubusercontent.com/17558033/57740169-4e5ff300-766b-11e9-88ee-7af269b7946d.png)

<img width="1440" alt="Screen Shot 2019-05-14 at 5 03 38 PM (2)" src="https://user-images.githubusercontent.com/17558033/57740175-515ae380-766b-11e9-83a9-f43bfd4fd403.png">

## Link to Appium logs
https://gist.github.com/jlee6890/a5a69f376448c5ed9ca60aacb4c00979

**Comment by KazuCocoa** [comment]
What about running with the latest `appium@beta` installed version?
I hope https://github.com/appium/appium-xcuitest-driver/pull/961 helps...

**Comment by jlee6890** [comment]
@KazuCocoa, didnt seem to work =(. Any other suggestions.

**Comment by KazuCocoa** [comment]
Then, you should set bundle id properly as  https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md
> At this point you have a valid provisioning profile. Make note of the bundle id you associated with it, and add that in the updatedWDABundleId desired capability for your tests. Then follow the initial instructions for automatic configuration.

You set `io.appium.*` bundle id, but it is not valid for your account.
e.g. https://cocoacasts.com/what-are-app-ids-and-bundle-identifiers/

**Comment by jlee6890** [comment]
@KazuCocoa, so to clarify, i shouldn't use io.appium for bundle ID?

**Comment by jlee6890** [comment]
@KazuCocoa nevermind, I got it to work. Thanks!
