### ISSUE TITLE
An unknown server-side error occurred while processing the command. Original error: You must include a platformName capability 

### ISSUE THREAD

**Issue by vovchik9** [appium/appium#12648]
## The problem
I can't launch ui inspector from Appium when I select Start session I get this error: 
An unknown server-side error occurred while processing the command. Original error: You must include a platformName capability

## Environment

* Appium version (1.13)
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Mobile platform/version under test: Galaxy s7
* Real device :
*  Appium.app|exe:

## Link to Appium logs

I get error when I select Start Session with ui inspector on Appium 

{
  "platformName ": "Android",
  "platformVersion": "9.0",
  "appPackage": "com.samsung.android.phonemessage",
  "appActivity": "com.android.phonemessage.ui.dialermessage",
  "deviceName": "Galaxy s7"

Operating System: 
<!macOS Mojave-->

## Actual Behavior
Appium Logs

base-driver/lib/basedriver/driver.js:319:19)
[MJSONWP]     at AppiumDriver.executeCommand (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/lib/appium.js:471:26)
[MJSONWP]     at executeCommand (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:352:34)
[MJSONWP]     at asyncHandler (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:489:15)
[MJSONWP]     at Layer.handle [as handle_request] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[MJSONWP]     at next (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/route.js:137:13)
[MJSONWP]     at Route.dispatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/route.js:112:3)
[MJSONWP]     at Layer.handle [as handle_request] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[MJSONWP]     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:281:22
[MJSONWP]     at Function.process_params (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
[MJSONWP]     at next (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[MJSONWP]     at logger (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/morgan/index.js:144:5)
[MJSONWP]     at Layer.handle [as handle_request] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[MJSONWP]     at trim_prefix (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
[MJSONWP]     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:284:7
[MJSONWP]     at Function.process_params (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
[MJSONWP]     at next (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[MJSONWP]     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/body-parser/lib/read.js:130:5
[MJSONWP]     at invokeCallback (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/raw-body/index.js:224:16)
[MJSONWP]     at done (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/raw-body/index.js:213:7)
[MJSONWP]     at IncomingMessage.onEnd (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/raw-body/index.js:273:7)
[MJSONWP]     at phonemessage.emit (events.js:182:13)
[MJSONWP]     at endReadableNT (_stream_readable.js:1090:12)
[MJSONWP]     at process._tickCallback (internal/process/next_tick.js:63:19)
[HTTP] <-- POST /wd/hub/session 500 5 ms - 179
[HTTP] 
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 1 ms - 57
[HTTP] 

## Code To Reproduce Issue [ Good To Have ]

My Capabilities

{
  "platformName ": "Android",
  "platformVersion": "8.0",
  "appPackage": "com.samsung.android.phonemessage",
  "appActivity": "com.android.phonemessage.ui.dialermessage",
  "deviceName": "Galaxy s7"

**Comment by mykola-mokhnach** [comment]
Please attach the full server log

**Comment by vovchik9** [comment]
i have retype platformName and android every time in order to work.

**Comment by Anum-Zargar** [comment]
I am writing these capabilities in my appium inspector.

{
"platformName":"Android",
"deviceName":"Anum",
 "appPackage":"com.cineplex.storefront",
 "appActivity":"com.cineplex.store.android.main.MainActivity",
"automationName":"uiAutomator2",
"skipUnlock":true,
"noSign":true,
"udid":"emulator-5554"
}



Its throwing an error.Can anyone help me on this.

Error is:- **### An unknown server-side error occurred while processing the command. Original error: You must include a platformName capability**

**Comment by afridig** [comment]
Hello folks,
I am sure the people who had this issue would have solved it by now but i came across it yesterday and after spending at least half a day, i still wasn't able to make much sense of it. For me at the end the answer could have not been simpler that was right there and i couldn't just register it...

So what i did at the end was: adding the app part of the desired capabilities i gave not only the absolute path to the app i wanted installed on the virtual device but also followed it by a slash and the app name. If anyone is still not sure, let me know i will post screenshots.

**Comment by MaheshMoorthi** [comment]
hey guys ..when i am trying to connect my android redmi mobile with appium that time i am getting  #An unknown server-side error occurred while processing the command. Original error: You must include a platformName capability# , can anyone help me how to resolve it,, i am trying to cover manual testing in it.. it is  throwing me error 

here below i mentioned my capapbilities
{
"deviceName":"Redmi",
"platformName":Android",
"platformVersion":"9.0",
"appPackage":"com.olacabs.customer",
"appActivity":"com.olacabs.customer.ui.MainActivity"
}
