### ISSUE TITLE
Update behaviour of `noReset` capability for Android web testing

### ISSUE THREAD

**Issue by clample** [appium/appium#12651]
## The problem

Currently Appium web tests on Android Chrome will have a clear browser at the start of each test session, even if `noReset` is set to true. This occurs because Chromedriver starts Chrome and clears the data.

## Proposed Solution

To avoid clearing Chrome between sessions, Appium could check if Chrome is running. If it is not (for example, it's the first test session), Appium can use Chromedriver to launch Chrome as it normally does. If Chrome is already running and `noReset` is true, Appium could then use [androidUseRunningApp](https://sites.google.com/a/chromium.org/chromedriver/getting-started/getting-started---android).

It looks like `androidUseRunningApp` is broken with Chromedriver before 2.39 ([Chromedriver issue](https://bugs.chromium.org/p/chromedriver/issues/detail?id=2369)). I'm not sure whether it's better to fail explicitly in this case, or fall back to the current behavior.

## Code To Reproduce Issue 
https://gist.github.com/clample/3becb6623d3ceb3eed5da295ee67e4de

**Comment by clample** [comment]
Relates to https://github.com/appium/appium/issues/8399

**Comment by mykola-mokhnach** [comment]
Closed by https://github.com/appium/appium/issues/8399#issuecomment-613959154
