### ISSUE TITLE
Appium Launching  is not selecting chrome as default browser

### ISSUE THREAD

**Issue by VictorPapuc** [appium/appium#12653]
## The problem

Appium Launching  is not selecting chrome as default browser

## Environment

* io.appium:java-client:7.00

* Mobile platform/Android - variouse mobile devices - Testing on Grid

## Details

    @Override
    protected void pageShouldBeOpenedInNewBrowserTab(UIElementLocator buttonLocator) {
        try {
           driver.await()
                                .timeout(10, TimeUnit.SECONDS)
                                .pollInterval(2, TimeUnit.SECONDS)
                                .until(() -> 
driver.getRequiredElement(buttonLocator).isTouchable());
        } catch (ConditionTimeoutException exception) {
            appiumDriver.isAppInstalled(BROWSER_BUNDLE_ID);
            log.info("App is not installed on device");
        }
        setBrowser();
        monosyneDriver.click(buttonLocator);
        browserShouldBeOpened();
        applicationShouldBeOpened();
    }

    private void setBrowser() {
        DesiredCapabilities.android().setCapability(BrowserType.CHROME, true);
        DesiredCapabilities.chrome().setPlatform(Platform.ANDROID);
    }

**Comment by mykola-mokhnach** [comment]
Can you please properly describe the problem: add the steps, the actual and the expected result descriptions plus server logs?

**Comment by VictorPapuc** [comment]
My questions is how can I make appiumDriver select default browser Chrome for every device :

This piece of code should work as setting the default browser ? 
Theoretically the problem is not with Appium is with devices that do not have default selection chrome
So I set this.


private static final String BROWSER_BUNDLE_ID = "com.android.chrome"

appiumDriver.activateApp(BROWSER_BUNDLE_ID); this will only activate the application it won;
t open the desired link

I cannot provide the link ; test is failing in: Link wasn't opened in browser

private void browserShouldBeOpened() {
        await().atMost(30, TimeUnit.SECONDS).untilAsserted(() -> assertThat(getCurrentApplicationState() == RUNNING_IN_FOREGROUND)
                .as("Link wasn't opened in browser.")
                .isTrue());
        log.info("Link was opened in browser.");
    }

  private ApplicationState getCurrentApplicationState() {
        return appiumDriver.queryAppState(BROWSER_BUNDLE_ID);
    }

 private ApplicationState getCurrentApplicationState() {
        return appiumDriver.queryAppState(BROWSER_BUNDLE_ID);
    }


private void setBrowser() {
    DesiredCapabilities.android().setCapability(BrowserType.CHROME, true);
    DesiredCapabilities.chrome().setPlatform(Platform.ANDROID);
}

**Comment by mykola-mokhnach** [comment]
Android OS does not provide a possibility to set default apps via adb. You can only edit the corresponding setting on the system partition if you have root permissions on the phone. Or via the UI, like a normal user would do it.  

For opening arbitrary links you could try https://appiumpro.com/editions/7, https://appiumpro.com/editions/23

Please use Appium forum for questions.
