### ISSUE TITLE
[XCUITest] TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by ognhem** [appium/appium#12650]
## Getting below error:

[XCUITest] TypeError: Cannot read property 'replace' of undefined
[XCUITest] at replace (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/node-simctl/lib/simctl.js:382:61)

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:
![image](https://user-images.githubusercontent.com/50488896/57830811-e6c3b800-77d0-11e9-90d6-3ee7f6a451fa.png)

**Comment by mykola-mokhnach** [comment]
- The full server log is needed
- Is Appium up to date?

**Comment by ognhem** [comment]
Thanks for your quick reply. Yes Appium is up to date(1.13.0). Below is complete log:

[Appium] Welcome to Appium v1.13.0
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"//Users⁩/⁨shyamyadav⁩/⁨Desktop⁩/UICatalog.app","automationName":"XCuiTest","platformName":"iOS","deviceName":"iPhone 6","newCommandTimeout":"12000"},"capabilities":{"firstMatch":[{"appium:app":"//Users⁩/⁨shyamyadav⁩/⁨Desktop⁩/UICatalog.app","appium:automationName":"XCuiTest","appium:deviceName":"iPhone 6","appium:newCommandTimeout":"12000","platformName":"ios"}]}}
[W3C] Calling AppiumDriver.createSession() with args: [{"app":"//Users⁩/⁨shyamyadav⁩/⁨Desktop⁩/UICatalog.app","automationName":"XCuiTest","platformName":"iOS","deviceName":"iPhone 6","newCommandTimeout":"12000"},null,{"firstMatch":[{"appium:app":"//Users⁩/⁨shyamyadav⁩/⁨Desktop⁩/UICatalog.app","appium:automationName":"XCuiTest","appium:deviceName":"iPhone 6","appium:newCommandTimeout":"12000","platformName":"ios"}]}]
[BaseDriver] Event 'newSessionRequested' logged at 1557988412849 (12:03:32 GMT+0530 (IST))
[BaseDriver] Number capability passed in as string. Functionality may be compromised.
[Appium] Appium v1.13.0 creating new XCUITestDriver (v2.113.2) session
[Appium] Capabilities:
[Appium] platformName: ios
[Appium] app: //Users⁩/⁨shyamyadav⁩/⁨Desktop⁩/UICatalog.app
[Appium] automationName: XCuiTest
[Appium] deviceName: iPhone 6
[Appium] newCommandTimeout: 12000
[BaseDriver] W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP desired capabilities {"app":"//Users⁩/⁨shyamyada... were provided
[BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"platformNa...
[BaseDriver] Number capability passed in as string. Functionality may be compromised.
[BaseDriver] Capability 'newCommandTimeout' changed from string ('12000') to integer (12000). This may cause unexpected behavior
[XCUITest] 'platformVersion' capability ('undefined') is not a valid version number. Consider fixing it or be ready to experience an inconsistent driver behavior.
[BaseDriver] Session created with session id: 35a0e1c6-8511-4f87-977c-f516362e12de
[XCUITest] Current user: 'shyamyadav'
[XCUITest] Simulator udid not provided
[XCUITest] Using desired caps to create a new simulator
[XCUITest] TypeError: Cannot read property 'replace' of undefined
[XCUITest] at replace (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/node-simctl/lib/simctl.js:382:61)
[BaseDriver] Event 'newSessionStarted' logged at 1557988414122 (12:03:34 GMT+0530 (IST))
[W3C] Encountered internal error running command: TypeError: Cannot read property 'replace' of undefined
[W3C] at replace (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/node-simctl/lib/simctl.js:382:61)
[HTTP] <-- POST /wd/hub/session 500 1275 ms - 716
[HTTP]

**Comment by mykola-mokhnach** [comment]
Set the correct value to platformVersion cap

**Comment by ognhem** [comment]
give this but still getting same error:
d.setCapability(MobileCapabilityType.PLATFORM_VERSION, "12.2");

**Comment by mykola-mokhnach** [comment]
Can you provide the updated log?

**Comment by ognhem** [comment]
After update that code log is below:
[Appium] Welcome to Appium v1.13.0
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"//Users⁩/⁨shyamyadav⁩/⁨Desktop⁩/UICatalog.app","automationName":"XCuiTest","platformName":"iOS","deviceName":"iPhone 6","newCommandTimeout":"12000"},"capabilities":{"firstMatch":[{"appium:app":"//Users⁩/⁨shyamyadav⁩/⁨Desktop⁩/UICatalog.app","appium:automationName":"XCuiTest","appium:deviceName":"iPhone 6","appium:newCommandTimeout":"12000","platformName":"ios"}]}}
[W3C] Calling AppiumDriver.createSession() with args: [{"app":"//Users⁩/⁨shyamyadav⁩/⁨Desktop⁩/UICatalog.app","automationName":"XCuiTest","platformName":"iOS","deviceName":"iPhone 6","newCommandTimeout":"12000"},null,{"firstMatch":[{"appium:app":"//Users⁩/⁨shyamyadav⁩/⁨Desktop⁩/UICatalog.app","appium:automationName":"XCuiTest","appium:deviceName":"iPhone 6","appium:newCommandTimeout":"12000","platformName":"ios"}]}]
[BaseDriver] Event 'newSessionRequested' logged at 1557994782988 (13:49:42 GMT+0530 (IST))
[BaseDriver] Number capability passed in as string. Functionality may be compromised.
[Appium] Appium v1.13.0 creating new XCUITestDriver (v2.113.2) session
[Appium] Capabilities:
[Appium]   platformName: ios
[Appium]   app: //Users⁩/⁨shyamyadav⁩/⁨Desktop⁩/UICatalog.app
[Appium]   automationName: XCuiTest
[Appium]   deviceName: iPhone 6
[Appium]   newCommandTimeout: 12000
[BaseDriver] W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP desired capabilities {"app":"//Users⁩/⁨shyamyada... were provided
[BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"platformNa...
[BaseDriver] Number capability passed in as string. Functionality may be compromised.
[BaseDriver] Capability 'newCommandTimeout' changed from string ('12000') to integer (12000). This may cause unexpected behavior
[XCUITest] 'platformVersion' capability ('undefined') is not a valid version number. Consider fixing it or be ready to experience an inconsistent driver behavior.
[BaseDriver] Session created with session id: f4855a05-c397-4997-9c72-83474d6a2dda
[XCUITest] Current user: 'shyamyadav'
[XCUITest] Simulator udid not provided
[XCUITest] Using desired caps to create a new simulator
[XCUITest] TypeError: Cannot read property 'replace' of undefined
[XCUITest]     at replace (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/node-simctl/lib/simctl.js:382:61)
[BaseDriver] Event 'newSessionStarted' logged at 1557994783794 (13:49:43 GMT+0530 (IST))
[W3C] Encountered internal error running command: TypeError: Cannot read property 'replace' of undefined
[W3C]     at replace (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/node-simctl/lib/simctl.js:382:61)
[HTTP] <-- POST /wd/hub/session 500 808 ms - 716
[HTTP]

**Comment by mykola-mokhnach** [comment]
> [XCUITest] 'platformVersion' capability ('undefined') is not a valid version number. Consider fixing it or be ready to experience an inconsistent driver behavior.

As you can see the cap is still not there, so the error is expected

**Comment by ognhem** [comment]
Yes i can see, but have given in selenium code platformVersion line. like below:

                DesiredCapabilities d=new DesiredCapabilities();
		String s=app.getAbsolutePath();
		System.out.println(s);
		d.setCapability(MobileCapabilityType.APP, app.getAbsolutePath()); 
		d.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 6");
		d.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
	   d.setCapability(MobileCapabilityType.PLATFORM_VERSION, "12.2");
	   d.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.IOS_XCUI_TEST);
	
		d.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");
		d.setCapability(MobileCapabilityType.APP,"//Users⁩/⁨shyamyadav⁩/⁨Desktop⁩/UICatalog.app");
		d.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, "20000");
		IOSDriver<IOSElement> driver=new IOSDriver<>(new URL("http://127.0.0.1:4723/wd/hub"),d);
    
Please suggest me what's wrong in this code.

**Comment by mykola-mokhnach** [comment]
I'm afraid this is not the correct place for such questions. Please use Appium forum instead.

**Comment by ognhem** [comment]
OK, Thanks.

**Comment by jpshelley** [comment]
I had a similar problem, and uninstalling the application from the simulator and re-launching from the appium server seems to fix the problem. I have to do it every-time though, after I shut down the server too.

**Comment by Karthikvt143** [comment]
try this :
d.setCapability(MobileCapabilityType.PLATFORM_VERSION, "12.4");

**Comment by zayberry** [comment]
This worked for me after I set;

iOS.setCapability(MobileCapabilityType.PLATFORM_VERSION, "12.2");
