### ISSUE TITLE
Result of iOS page source becomes unexpectedly large and time-out happens

### ISSUE THREAD

**Issue by NozomiIto** [appium/appium#12655]
## The problem

When I tries to retrieve the XML tree of my customer's iOS app by `driver.source` command, unexpectedly only the root element is returned. After I changed [AX_TIMEOUT](https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Categories/XCUIElement%2BFBUtilities.m#L77) to `300.` and rebuilt WebDriverAgent by myself, I could retrieve [very large tree](https://gist.githubusercontent.com/NozomiIto/cfd35c6a6281724e731cb1ef036fe20f/raw/ea5e7311037d1ec827a4fda56be401f8020880b1/Large%2520XML%2520tree). It contains about 300 `XCUIElementTypeCell` (most of them are `visible=false`) and I guess it makes the XML tree retrieval slow.

But what is strange is, the actual app does not have such so many TableViewCell elements. When the customer checked the [view hierarchy by Xcode](https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/debugging_with_xcode/chapters/special_debugging_workflows.html#//apple_ref/doc/uid/TP40015022-CH9-SW2), TableViewCells are only about 8.

Why source command returns so many elements..?

## Environment

* Appium 1.13.0. As I described about, I changed AX_TIMEOUT and rebuilt WebDriverAgent.
* Desktop OS/version used to run Appium: MacOS Mojave 10.14.4
* Node.js version: v10.11.0
* Npm or Yarn package manager: 6.4.1
* Mobile platform/version under test: iOS real device. iPad mini2. iOS12.2. (But this is also the same on iPhone8/iOS12.1/simulator)
* Appium CLI

## Details

- The back ground Cell elements continue to move upward slowly, since they contain the background image. This move may be related to the problem.
- I don't have the access right to the customer's app's source code. But I think they can offer necessary app's information to resolve the problem.
- To be exact, the user uses custom component whose name is ***.CollectionTableViewCell
- I attach the image of view hierarchy by Xcode. This is for a little different page than the page I retrieved the XML, but most of TableViewCell's structure and large XML problem is the same.

![MaskedImage](https://user-images.githubusercontent.com/4276719/57908106-2f0ad500-78ba-11e9-821b-fc3f6cf73c00.png)

## Link to Appium logs

https://gist.github.com/NozomiIto/0b529fe6b9ae50ea44d45f02a209023b

**Comment by mykola-mokhnach** [comment]
I don't think there's anything we can do on WDA side, since the page source is generated by XCTest. What you could try is to retrieve the page source in json format, which does not include visibility attributes and thus is quite fast: https://github.com/appium/appium/pull/9338/files

**Comment by NozomiIto** [comment]
Thank you for the quick response!
`description` format returned the whole tree in about 10 seconds! (although it still strangely has more than 300 cells) And maybe it has enough necessary information for me.
I will use it. Thanks!
