### ISSUE TITLE
[XCUITest] Error: Command 'open -Fn /Applications/Xcode_10.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID BD3E71E9-46E6-4C40-BC76-57D7646810C2 -ConnectHardwareKeyboard 0' exited with code 1

### ISSUE THREAD

**Issue by wlmrqz** [appium/appium#12652]
## Background
I don't have a mac, so I opted in using AWS Device Farm because they started supporting Appium + Node JS 

The android counter part of the tests using Appium + Node JS + Android Simulator works perfectly fine.

## Environment

```
AWS Devcice Farm
Appium Server: 1.9.1
Xcode: 10
XCUITEST: 2.94.2
```

##### Capabilities

```js
{
  "deviceName": "iPhone XS Max",
  "platformName": "iOS",
  "platformVersion": "12.1",
  "automationName": "XCUITest",
  "showXcodeLog": true,
  "usePrebuiltWDA": true
}
```

##### Node JS Test

Running the test via `mocha`

```js
const webdriverio = require("webdriverio");
const { expect } = require("chai");

describe("My Example App Test", function () {
  let driver;
  this.timeout(0);

  before(async (done) => {
    try {
      driver = await webdriverio.remote({
        port: config.port,
        capabilities: config.ios,
      });

      setTimeout(done, 1000);
    } catch (error) {
      console.error("HOOKS-ERROR:", error);
    }
  });

  describe("EXAMPLE SPEC", () => {
    it("Should detect Welcome", async () => {
      try {
        const welcome = await driver.$("~Welcome");
        await welcome.waitForExist(10000);
        return expect(welcome).to.exist;
      } catch (error) {
        console.error("TEST-ERROR", error);
      }
    });
  });
});
```

## Details

The goal is to run the an Appium Node JS test using iOS simulator.

As shown in the logs:

- Appium Server started successfully
- Connected to Xcode successfully (I think)

Just fails on the command that supposedly starts the iOS simulator.

I searched and searched for anything that might be related to this error but no dice as far as the problem is concerned.

## Link to Appium logs

[Full Server Logs](https://gist.github.com/wlmrqz/9dedf74f6642adf2d228bdda330c5c90)

**Comment by mykola-mokhnach** [comment]
This seems to be a problem with the Amazon image. Have you tried to contact their customer support?

**Comment by joelmrqz** [comment]
@mykola-mokhnach Thanks for your speedy response. I will do just that. But is it alright to keep this issue open? I will update this issue whatever I will get from AWS Support.

**Comment by mykola-mokhnach** [comment]
We usually keep such issues open for not more than three days to not overflow the queue. Although, it can be reopened if there is an obvious reason to do that.

**Comment by wlmrqz** [comment]
I understand. Alright. Thank you!
