### ISSUE TITLE
UiAutomator2 Could not sign with default certificate issue on mac

### ISSUE THREAD

**Issue by Amrkamel1** [appium/appium#12660]
## The problem
when i add automationName capability "Uiautomator2" test fail and i got the error below, however it works normally from terminal, is there any final solution for this issue 

`org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Could not sign with default certificate. Original error spawn ENOTDIR
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: '192.168.1.5', ip: '192.168.1.5', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.4', java.version: '1.8.0_152-release'
Driver info: driver.version: AndroidDriver`

## Environment
Appium 1.13.0
MacOs Mojave

## Details

> 
[Appium] Welcome to Appium v1.13.0
[Appium] Non-default server args:
[Appium]   address: 127.0.0.1
[Appium]   port: 5500
[HTTP] Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.
[Appium] Welcome to Appium v1.13.0
[Appium] Non-default server args:
[Appium]   address: 127.0.0.1
[Appium]   port: 5500
[Appium] Appium REST http interface listener started on 127.0.0.1:5500
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"appPackage":"com.sarajevo.food.dictionary","clearSystemFiles":true,"deviceName":"SM_N9208","appActivity":"com.sfdmobile.MainActivity","appium:unlockKey":"","platformVersion":"7.0","appium:unlockType":"password","automationName":"uiautomator2","autoGrantPermissions":"true","platformName":"Android","udid":"0715f75124ea0934","appium:uiautomator2ServerInstallTimeout":6000,"systemPort":"8240"},"capabilities":{"firstMatch":[{"appium:appActivity":"com.sfdmobile.MainActivity","appium:appPackage":"com.sarajevo.food.dictionary","appium:uiautomator2ServerInstallTimeout":6000,"appium:unlockKey":"@0122882435abA","appium:unlockType":"password","appium:autoGrantPermissions":"true","appium:automationName":"uiautomator2","appium:clearSystemFiles":true,"appium:deviceName":"SM_N9208","platformName":"android","appium:platformVersion":"7.0","appium:systemPort":"8240","appium:udid":"0715f75124ea0934"}]}}
[W3C] Calling AppiumDriver.createSession() with args: [{"appPackage":"com.sarajevo.food.dictionary","clearSystemFiles":true,"deviceName":"SM_N9208","appActivity":"com.sfdmobile.MainActivity","appium:unlockKey":"","platformVersion":"7.0","appium:unlockType":"password","automationName":"uiautomator2","autoGrantPermissions":"true","platformName":"Android","udid":"0715f75124ea0934","appium:uiautomator2ServerInstallTimeout":6000,"systemPort":"8240"},null,{"firstMatch":[{"appium:appActivity":"com.sfdmobile.MainActivity","appium:appPackage":"com.ssd.food.dictionary","appium:uiautomator2ServerInstallTimeout":6000,"appium:unlockKey":"@","appium:unlockType":"password","appium:autoGrantPermissions":"true","appium:automationName":"uiautomator2","appium:clearSystemFiles":true,"appium:deviceName":"SM_N9208","platformName":"android","appium:platformVersion":"7.0","appium:systemPort":"8240","appium:udid":"0715f75124ea0934"}]}]
[BaseDriver] Event 'newSessionRequested' logged at 1558133501028 (00:51:41 GMT+0200 (CEST))
[Appium] Appium v1.13.0 creating new AndroidUiautomator2Driver (v1.33.1) session
[Appium] Capabilities:
[Appium]   platformName: android
[Appium]   appActivity: com.ssdinActivity
[Appium]   appPackage: com.sarsdsdy
[Appium]   uiautomator2ServerInstallTimeout: 6000
[Appium]   autoGrantPermissions: true
[Appium]   automationName: uiautomator2
[Appium]   clearSystemFiles: true
[Appium]   deviceName: SM_N9208
[Appium]   platformVersion: 7.0
[Appium]   systemPort: 8240
[Appium]   udid: 0715f75124ea0934
[BaseDriver] W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP desired capabilities {"appPackage":"com.sarajevo... were provided
[BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"platformNa...
[BaseDriver] Number capability passed in as string. Functionality may be compromised.
[BaseDriver] Capability 'autoGrantPermissions' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Capability 'systemPort' changed from string ('8240') to integer (8240). This may cause unexpected behavior
[BaseDriver] Session created with session id: 301ad022-23f0-4f95-9695-8c7458e12c0e
[ADB] Found 1 'build-tools' folders under '/users/amrka/library/android/sdk' (newest first):
[ADB]     /users/amrka/library/android/sdk/build-tools/28.0.3
[ADB] Using 'adb' from '/users/amrka/library/android/sdk/platform-tools/adb'
[AndroidDriver] Retrieving device list
[ADB] Trying to find a connected android device
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[AndroidDriver] Using device: 0715f75124ea0934
[ADB] Using 'adb' from '/users/amrka/library/android/sdk/platform-tools/adb'
[ADB] Setting device id to 0715f75124ea0934
[ADB] Running '/users/amrka/library/android/sdk/platform-tools/adb -P 5037 -s 0715f75124ea0934 shell getprop ro.build.version.sdk'
[ADB] Current device property 'ro.build.version.sdk': 24
[ADB] Device API level: 24
[AndroidDriver] No app sent in, not parsing package/activity
[ADB] Running '/users/amrka/library/android/sdk/platform-tools/adb -P 5037 -s 0715f75124ea0934 wait-for-device'
[ADB] Running '/users/amrka/library/android/sdk/platform-tools/adb -P 5037 -s 0715f75124ea0934 shell echo ping'
[AndroidDriver] Pushing settings apk to device...
[ADB] Getting install status for io.appium.settings
[ADB] Running '/users/amrka/library/android/sdk/platform-tools/adb -P 5037 -s 0715f75124ea0934 shell dumpsys package io.appium.settings'
[ADB] 'io.appium.settings' is installed
[ADB] Getting package info for 'io.appium.settings'
[ADB] Running '/users/amrka/library/android/sdk/platform-tools/adb -P 5037 -s 0715f75124ea0934 shell dumpsys package io.appium.settings'
[ADB] Using 'aapt' from '/users/amrka/library/android/sdk/build-tools/28.0.3/aapt'
[ADB] The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('2.14.0' >= '2.14.0')
[ADB] There is no need to install/upgrade '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk'
[ADB] Getting IDs of all 'io.appium.settings' processes
[ADB] Running '/users/amrka/library/android/sdk/platform-tools/adb -P 5037 -s 0715f75124ea0934 shell 'pgrep --help; echo $?''
[ADB] Running '/users/amrka/library/android/sdk/platform-tools/adb -P 5037 -s 0715f75124ea0934 shell pgrep \^appium\\.settings\$'
[ADB] Running '/users/amrka/library/android/sdk/platform-tools/adb -P 5037 -s 0715f75124ea0934 shell am start -W -n io.appium.settings/.Settings -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[ADB] Running '/users/amrka/library/android/sdk/platform-tools/adb -P 5037 -s 0715f75124ea0934 shell appops set io.appium.settings android\:mock_location allow'
[Logcat] Starting logcat capture
[ADB] Getting install status for io.appium.uiautomator2.server
[ADB] Running '/users/amrka/library/android/sdk/platform-tools/adb -P 5037 -s 0715f75124ea0934 shell dumpsys package io.appium.uiautomator2.server'
[ADB] 'io.appium.uiautomator2.server' is installed
[ADB] Getting package info for 'io.appium.uiautomator2.server'
[ADB] Running '/users/amrka/library/android/sdk/platform-tools/adb -P 5037 -s 0715f75124ea0934 shell dumpsys package io.appium.uiautomator2.server'
[ADB] The version name of the installed 'io.appium.uiautomator2.server' is greater or equal to the application version name ('3.5.1' >= '3.5.1')
[UiAutomator2] io.appium.uiautomator2.server installation state: sameVersionInstalled
[ADB] Checking app cert for /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.5.1.apk
[ADB] Using 'apksigner' from '/users/amrka/library/android/sdk/build-tools/28.0.3/apksigner'
[ADB] Starting '/users/amrka/library/android/sdk/build-tools/28.0.3/apksigner' with args '["verify","--print-certs","/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.5.1.apk"]'
[ADB] Got an error during apksigner execution: Command '/users/amrka/library/android/sdk/build-tools/28.0.3/apksigner verify --print-certs /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.5.1.apk' exited with code 20
[ADB] apksigner stderr: Unable to locate an executable at "/usr/libexec/java_home/bin/java" (-1)
[ADB] 
[ADB] Cannot use apksigner tool for signature verification. Original error: Command '/users/amrka/library/android/sdk/build-tools/28.0.3/apksigner verify --print-certs /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.5.1.apk' exited with code 20
[ADB] Defaulting to verify.jar
[ADB] '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.5.1.apk' is not signed with debug cert
[ADB] Using 'zipalign' from '/users/amrka/library/android/sdk/build-tools/28.0.3/zipalign'
[ADB] /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.5.1.apk' is already zip-aligned. Doing nothing
[ADB] Signing '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.5.1.apk' with default cert
[ADB] Starting '/users/amrka/library/android/sdk/build-tools/28.0.3/apksigner' with args '["sign","--key","/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-adb/keys/testkey.pk8","--cert","/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-adb/keys/testkey.x509.pem","/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.5.1.apk"]'
[ADB] Got an error during apksigner execution: Command '/users/amrka/library/android/sdk/build-tools/28.0.3/apksigner sign --key /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-adb/keys/testkey.pk8 --cert /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-adb/keys/testkey.x509.pem /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.5.1.apk' exited with code 20
[ADB] apksigner stderr: Unable to locate an executable at "/usr/libexec/java_home/bin/java" (-1)
[ADB] 
[ADB] Cannot use apksigner tool for signing. Defaulting to sign.jar. Original error: Command '/users/amrka/library/android/sdk/build-tools/28.0.3/apksigner sign --key /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-adb/keys/testkey.pk8 --cert /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-adb/keys/testkey.x509.pem /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.5.1.apk' exited with code 20; StdErr: Unable to locate an executable at "/usr/libexec/java_home/bin/java" (-1)
[ADB] 
[ADB] Resigning apk.
[UiAutomator2] Deleting UiAutomator2 session
[UiAutomator2] Deleting UiAutomator2 server session
[WD Proxy] Matched '/' to command name 'deleteSession'
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
[ADB] Running '/users/amrka/library/android/sdk/platform-tools/adb -P 5037 -s 0715f75124ea0934 shell am force-stop com.sdsdonary'
[Logcat] Stopping logcat capture
[ADB] Removing forwarded port socket connection: 8240 
[ADB] Running '/users/amrka/library/android/sdk/platform-tools/adb -P 5037 -s 0715f75124ea0934 forward --remove tcp\:8240'
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command '/users/amrka/library/android/sdk/platform-tools/adb -P 5037 -s 0715f75124ea0934 forward --remove tcp\:8240' exited with code 1'; Stderr: 'adb: error: listener 'tcp:8240' not found'; Code: '1''
[BaseDriver] Event 'newSessionStarted' logged at 1558133505113 (00:51:45 GMT+0200 (CEST))
[W3C] Encountered internal error running command: Error: Could not sign with default certificate. Original error spawn ENOTDIR
[W3C]     at ADB. (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-adb/lib/tools/apk-signing.js:125:13)
[W3C]     at Generator.throw ()
[W3C]     at asyncGeneratorStep (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
[W3C]     at _throw (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:29:9)
[W3C]     at run (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/core-js/modules/es6.promise.js:75:22)
[W3C]     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/core-js/modules/es6.promise.js:92:30
[W3C]     at flush (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/core-js/modules/_microtask.js:18:9)
[W3C]     at process._tickCallback (internal/process/next_tick.js:61:11)
[HTTP] <-- POST /wd/hub/session 500 4112 ms - 768
[HTTP] 
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"appPackage":"com.sardsonary","clearSystemFiles":true,"deviceName":"SM_N9208","appActivity":"com.sfdmobile.MainActivity","appium:unlockKey":"sd","platformVersion":"7.0","appium:unlockType":"password","automationName":"uiautomator2","autoGrantPermissions":"true","platformName":"Android","udid":"0715f75124ea0934","appium:uiautomator2ServerInstallTimeout":6000,"systemPort":"8240"},"capabilities":{"firstMatch":[{"appium:appActivity":"com.sfdmobile.MainActivity","appium:appPackage":"com.sjevdo.food.dictionary","appium:uiautomator2ServerInstallTimeout":6000,"appium:unlockKey":"sd","appium:unlockType":"password","appium:autoGrantPermissions":"true","appium:automationName":"uiautomator2","appium:clearSystemFiles":true,"appium:deviceName":"SM_N9208","platformName":"android","appium:platformVersion":"7.0","appium:systemPort":"8240","appium:udid":"0715f75124ea0934"}]}}
[W3C] Calling AppiumDriver.createSession() with args: [{"appPackage":"com.ds.dictionary","clearSystemFiles":true,"deviceName":"SM_N9208","appActivity":"com.sfdmobile.MainActivity","appium:unlockKey":sd"platformVersion":"7.0","appium:unlockType":"password","automationName":"uiautomator2","autoGrantPermissions":"true","platformName":"Android","udid":"0715f75124ea0934","appium:uiautomator2ServerInstallTimeout":6000,"systemPort":"8240"},null,{"firstMatch":[{"appium:appActivity":"com.sfdmobile.MainActivity","appium:appPackage":"com.sarajevo.food.dictionary","appium:uiautomator2ServerInstallTimeout":6000,"appium:unlockKey":"@0122882435abA","appium:unlockType":"password","appium:autoGrantPermissions":"true","appium:automationName":"uiautomator2","appium:clearSystemFiles":true,"appium:deviceName":"SM_N9208","platformName":"android","appium:platformVersion":"7.0","appium:systemPort":"8240","appium:udid":"0715f75124ea0934"}]}]
[BaseDriver] Event 'newSessionRequested' logged at 1558133505632 (00:51:45 GMT+0200 (CEST))
[Appium] Appium v1.13.0 creating new AndroidUiautomator2Driver (v1.33.1) session
[Appium] Capabilities:
[Appium]   platformName: android
[Appium]   appActivity: com.sfddsainActivity
[Appium]   appPackage: com.dsctionary
[Appium]   uiautomator2ServerInstallTimeout: 6000
[Appium]   autoGrantPermissions: true
[Appium]   automationName: uiautomator2
[Appium]   clearSystemFiles: true
[Appium]   deviceName: SM_N9208
[Appium]   platformVersion: 7.0
[Appium]   systemPort: 8240
[Appium]   udid: 0715f75124ea0934
[BaseDriver] W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP desired capabilities {"appPackage":"com.sarajevo... were provided
[BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"platformNa...
[BaseDriver] Number capability passed in as string. Functionality may be compromised.
[BaseDriver] Capability 'autoGrantPermissions' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Capability 'systemPort' changed from string ('8240') to integer (8240). This may cause unexpected behavior
[BaseDriver] Session created with session id: 60a5381c-2663-463d-bb52-215f6ba75e9d
[ADB] Using 'adb' from '/users/amrka/library/android/sdk/platform-tools/adb'
[AndroidDriver] Retrieving device list
[ADB] Trying to find a connected android device
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[AndroidDriver] Using device: 0715f75124ea0934
[ADB] Using 'adb' from '/users/amrka/library/android/sdk/platform-tools/adb'
[ADB] Setting device id to 0715f75124ea0934
[ADB] Running '/users/amrka/library/android/sdk/platform-tools/adb -P 5037 -s 0715f75124ea0934 shell getprop ro.build.version.sdk'
[ADB] Current device property 'ro.build.version.sdk': 24
[ADB] Device API level: 24
[AndroidDriver] No app sent in, not parsing package/activity
[ADB] Running '/users/amrka/library/android/sdk/platform-tools/adb -P 5037 -s 0715f75124ea0934 wait-for-device'
[ADB] Running '/users/amrka/library/android/sdk/platform-tools/adb -P 5037 -s 0715f75124ea0934 shell echo ping'
[AndroidDriver] Pushing settings apk to device...
[ADB] Getting install status for io.appium.settings
[ADB] Running '/users/amrka/library/android/sdk/platform-tools/adb -P 5037 -s 0715f75124ea0934 shell dumpsys package io.appium.settings'
[ADB] 'io.appium.settings' is installed
[ADB] Getting package info for 'io.appium.settings'
[ADB] Running '/users/amrka/library/android/sdk/platform-tools/adb -P 5037 -s 0715f75124ea0934 shell dumpsys package io.appium.settings'
[ADB] Using 'aapt' from '/users/amrka/library/android/sdk/build-tools/28.0.3/aapt'
[ADB] The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('2.14.0' >= '2.14.0')
[ADB] There is no need to install/upgrade '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk'
[ADB] Getting IDs of all 'io.appium.settings' processes
[ADB] Running '/users/amrka/library/android/sdk/platform-tools/adb -P 5037 -s 0715f75124ea0934 shell 'pgrep --help; echo $?''
[ADB] Running '/users/amrka/library/android/sdk/platform-tools/adb -P 5037 -s 0715f75124ea0934 shell pgrep \^appium\\.settings\$'
[AndroidDriver] io.appium.settings is already running. There is no need to reset its permissions.
[ADB] Running '/users/amrka/library/android/sdk/platform-tools/adb -P 5037 -s 0715f75124ea0934 shell appops set io.appium.settings android\:mock_location allow'
[Logcat] Starting logcat capture
[ADB] Getting install status for io.appium.uiautomator2.server
[ADB] Running '/users/amrka/library/android/sdk/platform-tools/adb -P 5037 -s 0715f75124ea0934 shell dumpsys package io.appium.uiautomator2.server'
[ADB] 'io.appium.uiautomator2.server' is installed
[ADB] Getting package info for 'io.appium.uiautomator2.server'
[ADB] Running '/users/amrka/library/android/sdk/platform-tools/adb -P 5037 -s 0715f75124ea0934 shell dumpsys package io.appium.uiautomator2.server'
[ADB] The version name of the installed 'io.appium.uiautomator2.server' is greater or equal to the application version name ('3.5.1' >= '3.5.1')
[UiAutomator2] io.appium.uiautomator2.server installation state: sameVersionInstalled
[ADB] Checking app cert for /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.5.1.apk
[ADB] Using 'apksigner' from '/users/amrka/library/android/sdk/build-tools/28.0.3/apksigner'
[ADB] Starting '/users/amrka/library/android/sdk/build-tools/28.0.3/apksigner' with args '["verify","--print-certs","/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.5.1.apk"]'
[ADB] Got an error during apksigner execution: Command '/users/amrka/library/android/sdk/build-tools/28.0.3/apksigner verify --print-certs /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.5.1.apk' exited with code 20
[ADB] apksigner stderr: Unable to locate an executable at "/usr/libexec/java_home/bin/java" (-1)
[ADB] 
[ADB] Cannot use apksigner tool for signature verification. Original error: Command '/users/amrka/library/android/sdk/build-tools/28.0.3/apksigner verify --print-certs /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.5.1.apk' exited with code 20
[ADB] Defaulting to verify.jar
[ADB] '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.5.1.apk' is not signed with debug cert
[ADB] Using 'zipalign' from '/users/amrka/library/android/sdk/build-tools/28.0.3/zipalign'
[ADB] /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.5.1.apk' is already zip-aligned. Doing nothing
[ADB] Signing '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.5.1.apk' with default cert
[ADB] Starting '/users/amrka/library/android/sdk/build-tools/28.0.3/apksigner' with args '["sign","--key","/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-adb/keys/testkey.pk8","--cert","/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-adb/keys/testkey.x509.pem","/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.5.1.apk"]'
[ADB] Got an error during apksigner execution: Command '/users/amrka/library/android/sdk/build-tools/28.0.3/apksigner sign --key /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-adb/keys/testkey.pk8 --cert /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-adb/keys/testkey.x509.pem /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.5.1.apk' exited with code 20
[ADB] apksigner stderr: Unable to locate an executable at "/usr/libexec/java_home/bin/java" (-1)
[ADB] 
[ADB] Cannot use apksigner tool for signing. Defaulting to sign.jar. Original error: Command '/users/amrka/library/android/sdk/build-tools/28.0.3/apksigner sign --key /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-adb/keys/testkey.pk8 --cert /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-adb/keys/testkey.x509.pem /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.5.1.apk' exited with code 20; StdErr: Unable to locate an executable at "/usr/libexec/java_home/bin/java" (-1)
[ADB] 
[ADB] Resigning apk.
[UiAutomator2] Deleting UiAutomator2 session
[UiAutomator2] Deleting UiAutomator2 server session
[WD Proxy] Matched '/' to command name 'deleteSession'
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
[ADB] Running '/users/amrka/library/android/sdk/platform-tools/adb -P 5037 -s 0715f75124ea0934 shell am force-stop com.sarajevo.food.dictionary'
[Logcat] Stopping logcat capture
[ADB] Removing forwarded port socket connection: 8240 
[ADB] Running '/users/amrka/library/android/sdk/platform-tools/adb -P 5037 -s 0715f75124ea0934 forward --remove tcp\:8240'
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command '/users/amrka/library/android/sdk/platform-tools/adb -P 5037 -s 0715f75124ea0934 forward --remove tcp\:8240' exited with code 1'; Stderr: 'adb: error: listener 'tcp:8240' not found'; Code: '1''
[BaseDriver] Event 'newSessionStarted' logged at 1558133507837 (00:51:47 GMT+0200 (CEST))
[W3C] Encountered internal error running command: Error: Could not sign with default certificate. Original error spawn ENOTDIR
[W3C]     at ADB. (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-adb/lib/tools/apk-signing.js:125:13)
[W3C]     at Generator.throw ()
[W3C]     at asyncGeneratorStep (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
[W3C]     at _throw (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:29:9)
[W3C]     at run (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/core-js/modules/es6.promise.js:75:22)
[W3C]     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/core-js/modules/es6.promise.js:92:30
[W3C]     at flush (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/core-js/modules/_microtask.js:18:9)
[W3C]     at process._tickCallback (internal/process/next_tick.js:61:11)
[HTTP] <-- POST /wd/hub/session 500 2209 ms - 768
[HTTP] 
> 

## Code To Reproduce Issue [ Good To Have ]

```
 @BeforeMethod(alwaysRun = true)
    public void setUp() throws MalformedURLException {

        DesiredCapabilities dc = new DesiredCapabilities();
        dc.setCapability(MobileCapabilityType.UDID, "988a1641434e36333130");
       dc.setCapability(MobileCapabilityType.DEVICE_NAME, "Note8");
        dc.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
        dc.setCapability(MobileCapabilityType.PLATFORM_VERSION, "9");
        dc.setCapability("automationName", "uiautomator2");
        dc.setCapability(AndroidMobileCapabilityType.APP_PACKAGE, "com.sec.android.app.music");
        dc.setCapability(AndroidMobileCapabilityType.APP_ACTIVITY, ".common.activity.MusicMainActivity");

        dc.setCapability(MobileCapabilityType.NO_RESET, true);
        dc.setCapability(MobileCapabilityType.FULL_RESET, false);

        dc.setCapability(AndroidMobileCapabilityType.PLATFORM_NAME, "Android");




        driver = new AndroidDriver <WebElement>(new URL("http://0.0.0.0:4723/wd/hub"), dc);


    }
```

**Comment by Amrkamel1** [comment]
@mykola-mokhnach

**Comment by KazuCocoa** [comment]
You have below error.

> [ADB] apksigner stderr: Unable to locate an executable at "/usr/libexec/java_home/bin/java" (-1)

Could you make sure your JAVA_HOME env again?

I found https://stackoverflow.com/questions/10873437/unable-to-locate-an-executable-at-usr-bin-java-bin-java-1 link about the error message.

**Comment by Amrkamel1** [comment]
> You have below error.
> 
> > [ADB] apksigner stderr: Unable to locate an executable at "/usr/libexec/java_home/bin/java" (-1)
> 
> Could you make sure your JAVA_HOME env again?
> 
> I found https://stackoverflow.com/questions/10873437/unable-to-locate-an-executable-at-usr-bin-java-bin-java-1 link about the error message.
thanks so much i have issue with JAVA_HOME 
it was written like this export PATH=$JAVA_HOME/bin=$PATH
insteal of export PATH=$JAVA_HOME/bin**:**$PATH

**Comment by zsamora** [comment]
I solved it, by following the instructions when they say not installing appium with sudo. If you have already installed node as sudo (because of dependencies or whatever) and can't run $ npm install -g appium, this solved it for me https://stackoverflow.com/questions/18088372/how-to-npm-install-global-not-as-root (first answer). After that no more issues (this happened to me because my JAVA_HOME and ANDROID_HOME were set, check if yours are first)

**Comment by MarcSteven** [comment]
The error was still existing. @KazuCocoa

**Comment by Raythode** [comment]
For me what worked is going to Appium desktop configurations and changing the JAVA_HOME from

/usr/java/bin

to

/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home

Hope this works for you.
