### ISSUE TITLE
NotImplementedError: Method  execute/sync Appium App + Python

### ISSUE THREAD

**Issue by JeanCarlosChavarriaHughes** [appium/appium#12661]
## The problem

[W3C] Encountered internal error running command: NotImplementedError: Method is not implemented
This is happening when I tried to set a setting with execute_script endpoint in python.

## Environment

* Appium version : 1.9.1
* Desktop OS/version used to run Appium: Mac Os
Darwin sjo-mpyhm 17.7.0 Darwin Kernel Version 17.7.0: Wed Oct 10 23:06:14 PDT 2018; root:xnu-4570.71.13~1/RELEASE_X86_64 x86_64
* Node.js version: v8.11.4
* Npm : 6.9.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium.app

## Details
What I need is to set the http proxy in the real device. I can do it with adb in command line, what appium is failing with internal error.

## Link to Appium logs

[Appium Logs](https://gist.github.com/JeanCarlosChavarriaHughes/4376e77a11792be3f34455625e09057d) 

## Code To Reproduce Issue [ Good To Have ]

```
    Driver.execute_script('mobile shell', {
        'command': 'settings put global http_proxy',
        'args': httpProxyIpAddress + ':' + httpPort,
        'includeStderr': True,
        'timeout': 5000
    })
```

**Comment by KazuCocoa** [comment]
Are you trying to do http://appium.io/docs/en/commands/mobile-command/ , https://github.com/appium/appium/blob/ff6b3a16f807fe8c7046a27726fe1a54dc85cf3f/docs/en/writing-running-appium/android/android-shell.md ?

What about adding `:` as the mobile command spec?
`'mobile shell'` => `'mobile: shell'`

And make sure your server has `--relaxed-security` flag.

**Comment by JeanCarlosChavarriaHughes** [comment]
@KazuCocoa  Thank you. The issue was fixed with your feedback.
`'mobile shell' => 'mobile: shell'`
