### ISSUE TITLE
xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<de41bf62f204e94bf9a7347734568aecf294ed1d>' test gives an error.

### ISSUE THREAD

**Issue by testfortest06** [appium/appium#12669]
## The problem

xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<de41bf62f204e94bf9a7347734568aecf294ed1d>' test gives an error. 

## Environment

Appium version: 1.13.0
MacOS Sierra: 10.14.5
XCode: 10.2.1
iPhone iOS :12.3

## Details

When I was setting Appium configurations for iOS and running command xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' test  
from the location /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent than getting an error.
However Test Suite and Test case started message should be display.

Please suggest if I am messing something? 

## Link to console logs
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ id:<db81bf62f204e94bf9a7347732313aecf294ed1d> }

	The requested device could not be found because no available devices matched the request.

	Available destinations for the "WebDriverAgentRunner" scheme:
		{ platform:iOS, id:db81bf62f204e94bf9a7347732313aecf294ed1d, name:Sharaddha’s iPhone }
		{ platform:iOS Simulator, id:7C4126D2-5615-4158-B8A0-E34BEA4C882E, OS:12.2, name:iPad (5th generation) }
		{ platform:iOS Simulator, id:D398DAB1-BB1E-40E6-9D80-C1D1F34470C2, OS:12.2, name:iPad (6th generation) }
		{ platform:iOS Simulator, id:B7266DB8-9C81-4C35-B9FF-07CE23274F07, OS:12.2, name:iPad Air }
		{ platform:iOS Simulator, id:6803065C-76AF-459E-95A7-2DBFC1D0A202, OS:12.2, name:iPad Air (3rd generation) }
		{ platform:iOS Simulator, id:A00A48F3-B285-4D9F-AB57-5E6098F2265C, OS:12.2, name:iPad Air 2 }
		{ platform:iOS Simulator, id:AED80D3F-50E5-487D-BA6A-A833F3E639AA, OS:12.2, name:iPad Pro (9.7-inch) }
		{ platform:iOS Simulator, id:BB3C18BD-698E-4F8D-963A-A4BABE914A8B, OS:12.2, name:iPad Pro (10.5-inch) }
		{ platform:iOS Simulator, id:0755A9B9-0E07-42E3-A7B8-98B6AAABCC3E, OS:12.2, name:iPad Pro (11-inch) }
		{ platform:iOS Simulator, id:DBB4C078-7B31-4ADA-A60E-6A7EB886F312, OS:12.2, name:iPad Pro (12.9-inch) }
		{ platform:iOS Simulator, id:00C391B3-C9B0-46CA-AFBB-2345B00FE9C8, OS:12.2, name:iPad Pro (12.9-inch) (2nd generation) }
		{ platform:iOS Simulator, id:CE55606B-6392-480B-BB47-F913D7596B5B, OS:12.2, name:iPad Pro (12.9-inch) (3rd generation) }
		{ platform:iOS Simulator, id:8FC37B0D-8B29-4DA0-978A-95506BBE88D3, OS:12.2, name:iPhone 5s }
		{ platform:iOS Simulator, id:4BBD9F7F-39BE-4DCA-820F-1AEF77E76BEF, OS:12.2, name:iPhone 6 }
		{ platform:iOS Simulator, id:AD27FEBB-C132-4550-AF5F-359C05BF8029, OS:12.2, name:iPhone 6 Plus }
		{ platform:iOS Simulator, id:91579DC5-C75C-470E-ADA8-4CF57498E780, OS:12.2, name:iPhone 6s }
		{ platform:iOS Simulator, id:3A7A23D1-A379-4E17-8B8F-8E2171ED6D24, OS:12.2, name:iPhone 6s Plus }
		{ platform:iOS Simulator, id:902C4D3B-CD29-4FDC-905B-E6C8202F4AB8, OS:12.2, name:iPhone 7 }
		{ platform:iOS Simulator, id:154FE203-8443-4C35-9DE2-318E2F9CF9B8, OS:12.2, name:iPhone 7 Plus }
		{ platform:iOS Simulator, id:7EC35C7E-5EB5-4071-B347-F76AB1875664, OS:12.2, name:iPhone 8 }
		{ platform:iOS Simulator, id:473AC02F-B303-4365-9FC3-6461A1996548, OS:12.2, name:iPhone 8 Plus }
		{ platform:iOS Simulator, id:03542667-430F-4841-9035-2109B5693E35, OS:12.2, name:iPhone SE }
		{ platform:iOS Simulator, id:25AB90BA-C9B6-459E-AE52-675CB6E8F517, OS:12.2, name:iPhone X }
		{ platform:iOS Simulator, id:40F18240-09E6-469E-B51D-BD43DE3E824E, OS:12.2, name:iPhone Xs }
		{ platform:iOS Simulator, id:C27D4437-B7EE-4491-8AF5-4C600FFB1FC2, OS:12.2, name:iPhone Xs Max }
		{ platform:iOS Simulator, id:7EEF14D5-535E-4644-8B0B-884AC660BE4C, OS:12.2, name:iPhone Xʀ }

	Ineligible destinations for the "WebDriverAgentRunner" scheme:
		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Generic iOS Device }
		{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Generic iOS Simulator Device }

**Comment by mykola-mokhnach** [comment]
The described issue has nothing to do with Appium. Please use Appium forum for questions. 

You can also check https://github.com/Carthage/Carthage/issues/950, which looks quite similar
