### ISSUE TITLE
Error executing adbExec - exited with code 255 'Can't open file: /data/local/tmp/appium_cache/a7c3d3f518bf906dfd994f6290dfc7e6c703ccae.apk'

### ISSUE THREAD

**Issue by roddymunro** [appium/appium#12672]
## The problem

I am trying to run a basic Appium test on Android 9, Pixel 3 emulator. When I attempt to run the test, I get an error with exit code 255 (more details below). I am yet to run a successful test on Mac for Android, but I have been fine with running an iOS test on a simulator.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: macOS Mojave V10.14.5
* Node.js version (unless using Appium.app|exe): v12.2.0
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: Android 9
* Real device or emulator/simulator: Pixel 3 emulator
* Appium CLI or Appium.app|exe: Both

## Details

I am trying to run the basic Android demo app on a Pixel 3 emulator, Android 9. When I try to run it, I get the errors seen in the logs that indicate that a file can't be opened. I have got this working fine on Windows, but I can't on Mac. I have also got iOS automation working on a Mac.

I have tried uninstalling all the Appium and Android components from my system, and reinstalling. This didn't fix the issue. I've also tried on multiple Android Pixel emulators.

## Link to Appium logs

*Appium App and Python strack trace logs* - https://gist.github.com/roddymunro/b9e863881968145cd31fddfbd81bcee3

## Code To Reproduce Issue [ Good To Have ]

```
from appium import webdriver

import os

android_caps = {
    "automationName": "UiAutomator2",
    "deviceName": "AndroidPixel",
    "platformName": "Android",
    "platformVersion": "9",
    "app": os.path.join(
        os.path.dirname(__file__),
        "ApiDemos-debug.apk"
    )
}

b = webdriver.Remote('http://127.0.0.1:4723/wd/hub', android_caps)
```

**Comment by mykola-mokhnach** [comment]
This emulator behaves quite strange. Set `remoteAppsCacheLimit` cap to zero to workaround the exception

**Comment by roddymunro** [comment]
@mykola-mokhnach awesome, that seems to fix the issue! Glad it wasn't anything to do with my setup.
