### ISSUE TITLE
Sign in with Google not working

### ISSUE THREAD

**Issue by srishti77** [appium/appium#12676]
I am testing an Android app using Appium v1.13.0. I want to sign in using Google Account. When I click on the Sign in with Google Button. I get the list of Gmail accounts. When I click on one of them, I do not get signed in.

I have seen this issue, but I could not find the solution in the given issue.
https://github.com/appium/appium/issues/11960

My core capabilities is given below:

      const coreCapabilities = {
         platformName: 'Android',
         automationName: 'UiAutomator2',
         deviceName: 'Android',
         autoGrantPermissions: true,
         autoAcceptAlerts: true,
         newCommandTimeout: 9999,
          noReset: true,
          noSign: true,
         gpsEnabled: true
       };

Is there any new functionality implemented to resolve the issue?

**Comment by mykola-mokhnach** [comment]
I'd rather ask in Appium forum.

**Comment by srishti77** [comment]
I have asked in the forum and I saw some previous question related to Google Sign in there with no answer.

**Comment by mykola-mokhnach** [comment]
Probably, then, it's just nobody knows

**Comment by mykola-mokhnach** [comment]
Closed as inactive

**Comment by d-pardo** [comment]
> I have asked in the forum and I saw some previous question related to Google Sign in there with no answer.

I tried with xpath:
`const elementsT = await driver.elements('xpath', '//android.widget.ListView[@index="3"]//android.widget.LinearLayout[2]').click();`

Also: 
```
const elementTwo = await driver.element('id', 'com.google.android.gms:id/account_name');
elementTwo.click();
```
But it doest work.

The only way I found is using pressKeycode, Im sure this is not the best way, but it works (at least for now that Im trying to undestand appium):

//Im working with JavaScript
//driver.sleep(6000) => just to delay and check results

```
test('Button click & select first account', async () => {
  // button <Button/> to call Google SingIng functionality
  expect(await driver.hasElementByAccessibilityId('singInButton')).toBe(true);
  await driver.elementByAccessibilityId('singInButton')
    .click();

    // here a lst of previous loged google accounts are showed
    await driver.sleep(6000); 
    await driver.pressKeycode(61);//TAB to move to firts account

    await driver.sleep(6000); 
    //select first element in list
    await driver.pressKeycode(62);

    await driver.sleep(6000); 
    
    //inside the app
    await driver.elementByAccessibilityId('logoutButton')
    .click();
})
```

**Comment by imurchie** [comment]
@d-pardo Is this the _actual_ code? It seems more likely that there is a `signInButton` than a `singInButton`.

**Comment by d-pardo** [comment]
@imurchie Yes, and yes...
Current code (I dont know why) is a simple <Button/> instead of <GoogleSigninButton/>(according to code history it was implmented), but both buttons call to the same Google event "GoogleSignin.signIn" on their onPress, so I think there isnt a big change on it... or do you think this is my issue?

**Comment by imurchie** [comment]
I honestly have no idea. Without the Appium logs there is little that can be said.
