### ISSUE TITLE
About send_keys 

### ISSUE THREAD

**Issue by bbminer** [appium/appium#12688]
I want to use send_keys to  some  element  to  input word,and I do not hope it clear the old text,but send_keys will clear it,so  how to solve this problem ,thanks

the python code：
add = self.wait.until(
                EC.presence_of_element_located((By.ID, 'com.tencent.mm:id/l3')))
add.send_keys(wchat_id)

**Comment by mykola-mokhnach** [comment]
https://appiumpro.com/editions/46

Please use Appium forum to ask questions.
