### ISSUE TITLE
Cannot record screen on iOS real devices

### ISSUE THREAD

**Issue by tanistra** [appium/appium#12680]
## The problem

I am trying to record a screen using the following command `self.driver.start_recording_screen()`. It is works ok on Android (real and simulator) and iOS simulator as well but on real iOS devices Appium responds with error:

> 

[W3C (3013bf5c)] Calling AppiumDriver.startRecordingScreen() with args: [{"forcedRestart":true},"3013bf5c-ee26-4c74-9077-7c274bf0000e"]
[XCUITest] Executing command 'startRecordingScreen'
[XCUITest] Checking if there is/was a previous screen recording. Set 'forceRestart' option to 'true' if you'd like to skip this step.
[XCUITest] Screen recording is not running. There is nothing to stop.
[WD Proxy] Matched '/appium/settings' to command name 'getSettings'
[WD Proxy] Proxying [GET /appium/settings] to [GET http://localhost:8100/session/D95BAF94-434F-49F2-AAA8-9953B9492414/appium/settings] with no body
[WD Proxy] Got response with status 200: "{\n  \"value\" : \"Unhandled endpoint: \\/session\\/D95BAF94-434F-49F2-AAA8-9953B9492414\\/appium\\/settings -- http:\\/\\/localhost:8100\\/ with parameters {\\n    wildcards =     (\\n        \\\"session\\/D95BAF94-434F-49F2-AAA8-9953B9492414\\/appium\\/settings\\\"\\n    );\\n}\",\n  \"sessionId\" : \"D95BAF94-434F-49F2-AAA8-9953B9492414\",\n  \"status\" : 1\n}"
[MJSONWP] Matched JSONWP error code 1 to UnknownError
[XCUITest] Connection to WDA timed out
[iProxy] recv failed: Operation not permitted
[W3C (3013bf5c)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Unhandled endpoint: /session/D95BAF94-434F-49F2-AAA8-9953B9492414/appium/settings -- http://localhost:8100/ with parameters {
[W3C (3013bf5c)]     wildcards =     (
[W3C (3013bf5c)]         "session/D95BAF94-434F-49F2-AAA8-9953B9492414/appium/settings"
[W3C (3013bf5c)]     );
[W3C (3013bf5c)] }
[W3C (3013bf5c)]     at errorFromMJSONWPStatusCode (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:789:10)
[W3C (3013bf5c)]     at ProxyRequestError.errorFromMJSONWPStatusCode [as getActualError] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:683:14)
[W3C (3013bf5c)]     at JWProxy.getActualError [as command] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:235:19)
[HTTP] <-- POST /wd/hub/session/3013bf5c-ee26-4c74-9077-7c274bf0000e/appium/start_recording_screen 500 23 ms - 1263
[HTTP] 
[HTTP] --> POST /wd/hub/session/3013bf5c-ee26-4c74-9077-7c274bf0000e/appium/start_recording_screen
[HTTP] {"options":{"forcedRestart":true},"sessionId":"3013bf5c-ee26-4c74-9077-7c274bf0000e"}`
> 

## Environment

* Appium version:  1.13.0 (1.13.0.20190505.5)
* OS X: 10.14.3 (18D109)
* Node.js version : v12.1.0
* Mobile platform/version under test: iPhone 7 Plus, os: 12.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: both Appium cli and desktop Appium.app

## Details

I've tried to:
- clear Xcode cache for WebDriverAgent according to instruction: https://stackoverflow.com/questions/5714372/how-to-empty-caches-and-clean-all-targets-xcode-4-and-later
- reinstall Appium
- remove apps from phone
- restart mac and phone
- use new fresh WebDriverAgent 
Nothing helps

Without recording screen my tests work fine.

## Link to Appium logs
full appium logs: https://gist.github.com/tanistra/d3187d48e9656ff55faa787208f0531e

## Code To Reproduce Issue [ Good To Have ]

config_file:
`{
  "app":"myapp.ipa",
  "device":"iOS",
  "platformName":"iOS",
  "browserName":"Chrome",
  "appiumVersion":"1.13.0",
  "deviceOrientation":"portrait",
  "platformVersion":"12.1",
  "deviceName":"iPhone .*",
  "remote":"http:\/\/localhost:4723\/wd\/hub",
  "xcodeOrgId":"MyID",
  "xcodeSigningId":"iPhone Developer",
  "updatedWDABundleId":"com.myorganization.launcher.dev",
  "bundleId":"com.myorganization.launcher.dev",
  "automationName":"XCUITest",
  "udid":"00d6d2e5bcf8fb0251b38b810f0afe91f1618624",
  "agentPath": "/Users/myname/Desktop/WebDriverAgent/WebDriverAgent.xcodeproj",
  "bootstrapPath": "/Users/myname/Desktop/WebDriverAgent"
}`

code

`
desired_caps = {
    'appiumVersion': config_file['appiumVersion'],
    'deviceOrientation': config_file['deviceOrientation'],
    'app': os.path.join(app_dir, config_file['app']),
    'deviceName': config_file['deviceName'],
    'platformName': config_file['platformName'],
    'platformVersion': config_file['platformVersion']}

platform = config_file['platformName'].lower()
if platform == 'ios':
    desired_caps['xcodeOrgId'] = config_file['xcodeOrgId']
    desired_caps['automationName'] = config_file['automationName']
    desired_caps['testFramework'] = config_file['automationName'].lower()
    if config_file.get('udid'):
        desired_caps['updatedWDABundleId'] = config_file[
            'updatedWDABundleId']
        desired_caps['udid'] = config_file['udid']
        desired_caps['agentPath'] = config_file['agentPath']
        desired_caps['bootstrapPath'] = config_file['bootstrapPath']
        desired_caps['xcodeSigningId'] = config_file['xcodeSigningId']
elif platform == 'android':
    desired_caps['appPackage'] = config_file['appPackage']
    desired_caps['appActivity'] = config_file['appActivity']
    desired_caps['unicodeKeyboard'] = config_file['unicodeKeyboard']
    desired_caps['resetKeyboard'] = config_file['resetKeyboard']
    if config_file['platformVersion'] == '6.0':
        desired_caps['browserName'] = config_file['browserName']

environment = config_file["remote"]

log.info(f'Starting appium driver with caps: \n{desired_caps}')
log.info("Config:{}".format(desired_caps))
driver = webdriver.Remote(environment, desired_caps)
driver.start_recording_screen()
`

**Comment by mykola-mokhnach** [comment]
You must use the correct WebDriverAgent binary, which is bundled with the corresponding Appium version. Sorry, but we can help nothing if you are using your own WDA sources: `[info] [35m[Appium][39m   bootstrapPath: /Users/jtanistra/Desktop/WebDriverAgent/`

**Comment by tanistra** [comment]
Right, I've changed WebDriverAgent and this is resolved my problem. @mykola-mokhnach Thanks for you help!
