### ISSUE TITLE
WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec.

### ISSUE THREAD

**Issue by abutizi** [appium/appium#12686]
## The problem
Hi guys, I'm really stuck here. I have tried almost everything, installing different API versions of Android emulators, adb kill-server & start-server, upgrading to latest beta 1.13 beta version of Appium, tried using UiAutomator1, UiAutomator2 and Espresso. But I just can't get past this error and I have no idea what I'm doing wrong. Is it a bug or just me?

This is the error message I'm getting:
`WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/var/www/workspace/androidSDK/platform-tools/adb -P 5037 -s emulator-5554 shell pm list packages com.android.settings' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability
`

## Environment

* Appium version 1.13.0 and latest beta
* Desktop OS/version used to run Appium: Linux Ubuntu head-less server
* Node v12.3.0
* Npm v6.9.0
* Mobile platform/version under test: API level 25 and 27 with google_apis x86
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: CLI

## Details

I cannot run Appium at all on my newly created emulator. I tried almost everything. I tried installing an app into my emulator using appium, yet nothing. I just want to make sure that Appium is running by opening the Settings app on my emulator. Same error. 

I would appreciate any insight, or if anyone experienced something similar?

## Link to Appium logs

`[Appium] Welcome to Appium v1.13.0-beta.3
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"capabilities":{"firstMatch":[{"appium:appActivity":"com.android.settings.Settings$WifiSettingsActivity","appium:noReset":false,"appium:newCommandTimeout":100,"appium:deviceName":"agent001","appium:appPackage":"com.android.settings","platformName":"Android","appium:networkSpeed":"lte"}]},"desiredCapabilities":{"deviceName":"agent001","noReset":false,"newCommandTimeout":100,"appPackage":"com.android.settings","platformName":"Android","appActivity":"com.android.settings.Settings$WifiSettingsActivity","networkSpeed":"lte"}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"deviceName":"agent001","noReset":false,"newCommandTimeout":100,"appPackage":"com.android.settings","platformName":"Android","appActivity":"com.android.settings.Settings$WifiSettingsActivity","networkSpeed":"lte"},null,{"firstMatch":[{"appium:appActivity":"com.android.settings.Settings$WifiSettingsActivity","appium:noReset":false,"appium:newCommandTimeout":100,"appium:deviceName":"agent001","appium:appPackage":"com.android.settings","platformName":"Android","appium:networkSpeed":"lte"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1558644338838 (20:45:38 GMT+0000 (Coordinated Universal Time))
[Appium]
[Appium] ======================================================================
[Appium]   DEPRECATION WARNING:
[Appium]
[Appium]   The 'automationName' capability was not provided in the desired
[Appium]   capabilities for this Android session
[Appium]
[Appium]   Setting 'automationName=UiAutomator1' by default and using the
[Appium]   UiAutomator1 Driver
[Appium]
[Appium]   The next minor version of Appium (1.14.x) will set
[Appium]   'automationName=UiAutomator2' by default and use the UiAutomator2
[Appium]   Driver
[Appium]
[Appium]   The next major version of Appium (2.x) will **require** the
[Appium]   'automationName' capability to be set for all sessions on all
[Appium]   platforms
[Appium]
[Appium]   If you are happy with 'UiAutomator1' and do not wish to upgrade
[Appium]   Android drivers, please add 'automationName=UiAutomator1' to your
[Appium]   desired capabilities
[Appium]
[Appium]   For more information about drivers, please visit
[Appium]   http://appium.io/docs/en/about-appium/intro/ and explore the
[Appium]   'Drivers' menu
[Appium]
[Appium] ======================================================================
[Appium]
[Appium] Setting automation to 'UiAutomator1'.
[Appium] Appium v1.13.0-beta.3 creating new AndroidDriver (v4.16.2) session
[Appium] Capabilities:
[Appium]   platformName: Android
[Appium]   appActivity: com.android.settings.Settings$WifiSettingsActivity
[Appium]   noReset: false
[Appium]   newCommandTimeout: 100
[Appium]   deviceName: agent001
[Appium]   appPackage: com.android.settings
[Appium]   networkSpeed: lte
[debug] [BaseDriver] W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP desired capabilities {"deviceName":"agent001","n... were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"platformNa...
[BaseDriver] Session created with session id: 71af245b-6d5a-437c-8eef-c55c5252a04e
[ADB] Found 1 'build-tools' folders under '/var/www/workspace/androidSDK' (newest first):
[ADB]     /var/www/workspace/androidSDK/build-tools/27.0.0
[ADB] Using 'adb' from '/var/www/workspace/androidSDK/platform-tools/adb'
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[AndroidDriver] Using device: emulator-5554
[ADB] Using 'adb' from '/var/www/workspace/androidSDK/platform-tools/adb'
[debug] [ADB] Setting device id to emulator-5554
[debug] [ADB] Running '/var/www/workspace/androidSDK/platform-tools/adb -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk'
[debug] [ADB] Current device property 'ro.build.version.sdk': 27
[debug] [ADB] Device API level: 27
[AndroidDriver] Consider setting 'automationName' capability to 'uiautomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.
[AndroidDriver] App file was not listed, instead we're going to run com.android.settings directly on the device
[debug] [AndroidDriver] Checking whether package is present on the device
[debug] [ADB] Running '/var/www/workspace/androidSDK/platform-tools/adb -P 5037 -s emulator-5554 shell pm list packages com.android.settings'
[debug] [AndroidDriver] Shutting down Android driver
[debug] [AndroidDriver] Called deleteSession but bootstrap wasn't active
[debug] [ADB] Running '/var/www/workspace/androidSDK/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop io.appium.unlock'
[debug] [AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1558644378148 (20:46:18 GMT+0000 (Coordinated Universal Time))
[debug] [W3C] Encountered internal error running command: Error executing adbExec. Original error: 'Command '/var/www/workspace/androidSDK/platform-tools/adb -P 5037 -s emulator-5554 shell pm list packages com.android.settings' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability
[debug] [W3C] Error: Command '/var/www/workspace/androidSDK/platform-tools/adb -P 5037 -s emulator-5554 shell pm list packages com.android.settings' timed out after 20000ms
[debug] [W3C]     at Timeout._onTimeout (/home/linuxbrew/.linuxbrew/lib/node_modules/appium/node_modules/teen_process/lib/exec.js:106:19)
[debug] [W3C]     at listOnTimeout (internal/timers.js:531:17)
[debug] [W3C]     at processTimers (internal/timers.js:475:7)
`

## Code To Reproduce Issue [ Good To Have ]

I'm using python:
`
self.desired_capabilities = {
          "deviceName": emulatorName,
          "platformName": "Android",
          "newCommandTimeout": 100,
          "networkSpeed": "lte"
        }

self.desired_capabilities['appActivity'] = "com.android.settings.Settings$WifiSettingsActivity"
self.desired_capabilities['appPackage'] = 'com.android.settings'
self.desired_capabilities['noReset'] = False

//error comes in here
self.driver = webdriver.Remote("http://localhost:4723/wd/hub", self.desired_capabilities)
`

**Comment by mykola-mokhnach** [comment]
What is the result if the above command is being executed manually from terminal?

**Comment by mykola-mokhnach** [comment]
Also `com.android.settings` seems to be a system package. I don't think any else cap except of `noReset=true`  would work for it

**Comment by abutizi** [comment]
@mykola-mokhnach 
You mean by executing:
`adb -P 5037 -s emulator-5554 shell pm list packages com.android.settings` ?
In this case, nothing... It just takes a while and the terminal does not show feedback

**Comment by abutizi** [comment]
> 
> 
> Also `com.android.settings` seems to be a system package. I don't think any else cap except of `noReset=true` would work for it

Okay, I will try `noReset=true`. 
Also update, I got the folllowing feedback from the terminal:
`Error: Could not access the Package Manager.  Is the system running?`

**Comment by mykola-mokhnach** [comment]
> Error: Could not access the Package Manager. Is the system running?

This looks like a problem with the emulator itself or the host system. It is too slow, so the mandatory services either cannot start in time or cannot start at all.

**Comment by abutizi** [comment]
> 
> 
> > Error: Could not access the Package Manager. Is the system running?
> 
> This looks like a problem with the emulator itself or the host system. It is too slow, so the mandatory services either cannot start in time or cannot start at all.

Thanks for quick reply btw. 
Do you think it's a permission issue? Because I have Appium server running on my non-root user. Although when I run `adb devides` it works and shows my emulator.

However, if I run this command:
`adb -P 5037 -s emulator-5554 shell pm list packages com.android.settings `
from my root user, it returns: `package:com.android.settings` so it seems like it works?

**Comment by mykola-mokhnach** [comment]
This depends on adb and emulator services. If it is possible to run the command manually the, most likely, Appium will also be able to run it if executed in the same environment.

**Comment by abutizi** [comment]
@mykola-mokhnach 
I've done a complete factory reset of my linux device and installed everything within the same user, within the same environment. 

I still get the very same error:
`WebDriverException: Message: An unknown server-side error occurred while processing the command. WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/var/www/workspace/androidSDK/platform-tools/adb -P 5037 -s emulator-5554 shell pm install /data/local/tmp/appium_cache/56abf1bf10f6562619a2dd8fb060718e27c4cb28.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'uiautomator2ServerInstallTimeout' capability
`

and when I try to run the command directly, it prints:

`Failure [INSTALL_FAILED_ALREADY_EXISTS: Attempt to re-install io.appium.uiautomator2.server without first uninstalling.`

**Comment by mykola-mokhnach** [comment]
It is possible to set `remoteAppsCacheLimit` to zero in order to disable the install cache

**Comment by abutizi** [comment]
`self.desired_capabilities['remoteAppsCacheLimit'] = 0`

Did not help. Same error :(

**Comment by mykola-mokhnach** [comment]
Any logs?

**Comment by abutizi** [comment]
Yes sorry:

`[Appium] Welcome to Appium v1.13.0-beta.3 (REV aee8250641a87535f4b64007a99911835d968475)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"capabilities":{"firstMatch":[{"appium:appActivity":"com.android.settings.Settings$WifiSettingsActivity","appium:noReset":true,"appium:automationName":"UiAutomator2","appium:newCommandTimeout":100,"appium:deviceName":"agent001","appium:remoteAppsCacheLimit":0,"appium:appPackage":"com.android.settings","platformName":"Android","appium:networkSpeed":"lte"}]},"desiredCapabilities":{"deviceName":"agent001","automationName":"UiAutomator2","noReset":true,"remoteAppsCacheLimit":0,"newCommandTimeout":100,"appPackage":"com.android.settings","platformName":"Android","appActivity":"com.android.settings.Settings$WifiSettingsActivity","networkSpeed":"lte"}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"deviceName":"agent001","automationName":"UiAutomator2","noReset":true,"remoteAppsCacheLimit":0,"newCommandTimeout":100,"appPackage":"com.android.settings","platformName":"Android","appActivity":"com.android.settings.Settings$WifiSettingsActivity","networkSpeed":"lte"},null,{"firstMatch":[{"appium:appActivity":"com.android.settings.Settings$WifiSettingsActivity","appium:noReset":true,"appium:automationName":"UiAutomator2","appium:newCommandTimeout":100,"appium:deviceName":"agent001","appium:remoteAppsCacheLimit":0,"appium:appPackage":"com.android.settings","platformName":"Android","appium:networkSpeed":"lte"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1558768954693 (07:22:34 GMT+0000 (UTC))
[Appium] Appium v1.13.0-beta.3 creating new AndroidUiautomator2Driver (v1.33.1) session
[Appium] Capabilities:
[Appium]   platformName: Android
[Appium]   appActivity: com.android.settings.Settings$WifiSettingsActivity
[Appium]   noReset: true
[Appium]   automationName: UiAutomator2
[Appium]   newCommandTimeout: 100
[Appium]   deviceName: agent001
[Appium]   remoteAppsCacheLimit: 0
[Appium]   appPackage: com.android.settings
[Appium]   networkSpeed: lte
[debug] [BaseDriver] W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP desired capabilities {"deviceName":"agent001","a... were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"platformNa...
[BaseDriver] Session created with session id: dfba8e41-1ccf-435a-ae7a-f4a9547ff0ca
[ADB] Found 1 'build-tools' folders under '/var/www/workspace/androidSDK' (newest first):
[ADB]     /var/www/workspace/androidSDK/build-tools/25.0.3
[ADB] Using 'adb' from '/var/www/workspace/androidSDK/platform-tools/adb'
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[AndroidDriver] Using device: emulator-5554
[ADB] Using 'adb' from '/var/www/workspace/androidSDK/platform-tools/adb'
[debug] [ADB] Setting device id to emulator-5554
[debug] [ADB] Running '/var/www/workspace/androidSDK/platform-tools/adb -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk'
[debug] [ADB] Current device property 'ro.build.version.sdk': 25
[debug] [ADB] Device API level: 25
[AndroidDriver] No app sent in, not parsing package/activity
[debug] [ADB] Running '/var/www/workspace/androidSDK/platform-tools/adb -P 5037 -s emulator-5554 wait-for-device'
[debug] [ADB] Running '/var/www/workspace/androidSDK/platform-tools/adb -P 5037 -s emulator-5554 shell echo ping'
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Getting install status for io.appium.settings
[debug] [ADB] Running '/var/www/workspace/androidSDK/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.settings'
[debug] [ADB] 'io.appium.settings' is installed
[debug] [ADB] Getting package info for 'io.appium.settings'
[debug] [ADB] Running '/var/www/workspace/androidSDK/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.settings'
[ADB] Using 'aapt' from '/var/www/workspace/androidSDK/build-tools/25.0.3/aapt'
[debug] [ADB] The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('2.14.0' >= '2.14.0')
[debug] [ADB] There is no need to install/upgrade '/var/www/workspace/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk'
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running '/var/www/workspace/androidSDK/platform-tools/adb -P 5037 -s emulator-5554 shell 'pgrep --help; echo $?''
[debug] [ADB] Running '/var/www/workspace/androidSDK/platform-tools/adb -P 5037 -s emulator-5554 shell pgrep \^appium\\.settings\$'
[debug] [AndroidDriver] Activating 'io.appium.settings'
[debug] [ADB] Running '/var/www/workspace/androidSDK/platform-tools/adb -P 5037 -s emulator-5554 shell monkey -p io.appium.settings -c android.intent.category.LAUNCHER 1'
[debug] [AndroidDriver] Command stdout: Events injected: 1
[debug] [AndroidDriver] ## Network stats: elapsed time=502ms (0ms mobile, 0ms wifi, 502ms not connected)
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running '/var/www/workspace/androidSDK/platform-tools/adb -P 5037 -s emulator-5554 shell pgrep \^appium\\.settings\$'
[debug] [ADB] Running '/var/www/workspace/androidSDK/platform-tools/adb -P 5037 -s emulator-5554 shell appops set io.appium.settings android\:mock_location allow'
[debug] [Logcat] Starting logcat capture
[debug] [ADB] Getting install status for io.appium.uiautomator2.server
[debug] [ADB] Running '/var/www/workspace/androidSDK/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.uiautomator2.server'
[debug] [ADB] 'io.appium.uiautomator2.server' is not installed
[debug] [ADB] App '/var/www/workspace/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.5.1.apk' is not installed
[debug] [UiAutomator2] io.appium.uiautomator2.server installation state: notInstalled
[debug] [ADB] Checking app cert for /var/www/workspace/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.5.1.apk
[ADB] Using 'apksigner' from '/var/www/workspace/androidSDK/build-tools/25.0.3/apksigner'
[debug] [ADB] Starting '/var/www/workspace/androidSDK/build-tools/25.0.3/apksigner' with args '["verify","--print-certs","/var/www/workspace/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.5.1.apk"]'
[debug] [ADB] apksigner stdout: Signer #1 certificate DN: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
[debug] [ADB] Signer #1 certificate SHA-256 digest: a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc
[debug] [ADB] Signer #1 certificate SHA-1 digest: 61ed377e85d386a8dfee6b864bd85b0bfaa5af81
[debug] [ADB] Signer #1 certificate MD5 digest: e89b158e4bcf988ebd09eb83f5378e87
[debug] [ADB]
[debug] [ADB] '/var/www/workspace/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.5.1.apk' is already signed.
[debug] [ADB] Getting install status for io.appium.uiautomator2.server.test
[debug] [ADB] Running '/var/www/workspace/androidSDK/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.uiautomator2.server.test'
[debug] [ADB] 'io.appium.uiautomator2.server.test' is not installed
[debug] [ADB] Checking app cert for /var/www/workspace/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk
[debug] [ADB] Starting '/var/www/workspace/androidSDK/build-tools/25.0.3/apksigner' with args '["verify","--print-certs","/var/www/workspace/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk"]'
[debug] [ADB] apksigner stdout: Signer #1 certificate DN: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
[debug] [ADB] Signer #1 certificate SHA-256 digest: a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc
[debug] [ADB] Signer #1 certificate SHA-1 digest: 61ed377e85d386a8dfee6b864bd85b0bfaa5af81
[debug] [ADB] Signer #1 certificate MD5 digest: e89b158e4bcf988ebd09eb83f5378e87
[debug] [ADB]
[debug] [ADB] '/var/www/workspace/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk' is already signed.
[UiAutomator2] Server packages are going to be (re)installed
[debug] [ADB] Running '/var/www/workspace/androidSDK/platform-tools/adb -P 5037 -s emulator-5554 install /var/www/workspace/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.5.1.apk'
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[debug] [WD Proxy] Matched '/' to command name 'deleteSession'
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
[debug] [ADB] Running '/var/www/workspace/androidSDK/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop com.android.settings'
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8200
[debug] [ADB] Running '/var/www/workspace/androidSDK/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp\:8200'
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command '/var/www/workspace/androidSDK/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp\:8200' exited with code 1'; Stderr: 'adb: error: listener 'tcp:8200' not found'; Code: '1''
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1558768989026 (07:23:09 GMT+0000 (UTC))
[debug] [W3C] Encountered internal error running command: Error executing adbExec. Original error: 'Command '/var/www/workspace/androidSDK/platform-tools/adb -P 5037 -s emulator-5554 install /var/www/workspace/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.5.1.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'uiautomator2ServerInstallTimeout' capability
[debug] [W3C] Error: Command '/var/www/workspace/androidSDK/platform-tools/adb -P 5037 -s emulator-5554 install /var/www/workspace/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.5.1.apk' timed out after 20000ms
[debug] [W3C]     at Timeout.setTimeout (/var/www/workspace/appium/node_modules/teen_process/lib/exec.js:106:19)
[debug] [W3C]     at ontimeout (timers.js:482:11)
[debug] [W3C]     at tryOnTimeout (timers.js:317:5)
[debug] [W3C]     at Timer.listOnTimeout (timers.js:277:5)
[HTTP] <-- POST /wd/hub/session 500 34394 ms - 1257
[HTTP]`

**Comment by mykola-mokhnach** [comment]
It looks more like a problem with adb/emulator itself. There might be more information in the logcat output. Or simply get another more performant machine.

**Comment by abutizi** [comment]
well seems like getting a more performant machine with at least dual core CPU did the job.
However, @mykola-mokhnach you wouldn't know if there's anything you can tweak in the emulator config in order to make it run on a single core CPU by any chance?

**Comment by mykola-mokhnach** [comment]
Nothing I know of. Try to ask Google though.

Closed as not an issue
