### ISSUE TITLE
Appium seems to follow context sometimes iOS 12.2 but didn't on iOS 12.1

### ISSUE THREAD

**Issue by andrew-lai-bjss** [appium/appium#12682]
## The problem

Since trying to switch to iOS 12.2 I have noticed inconsistent behaviour between that and version 12.1 (and earlier) with regards to the way the context changes.

With iOS 12.1 and earlier I was expected to manually switch context to the new webview when the application navigated to the MS ADAL login screen and manually switch context back to the webview for the application.

With iOS 12.2 it appears to switch context automatically to the new webview when the application navigated to the MS ADAL login screen but does not switch context back to the application webview after successful login.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: OSX 10.14.5
* Node.js version (unless using Appium.app|exe): v10.13.0
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: iPad Pro 10.5
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI

## Details

I have reproduced this using postman so it does not appear to be a fault in the test framework.

I have a manual work around in my test framework which switches back to the parent webview (the application) for this scenario.

I can monitor the available contexts and the current context using postman commands.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by imurchie** [comment]
Please provide the _full_ server logs (as a link to a [gist](https://gist.github.com)). We cannot do much without it.

**Comment by andrew-lai-bjss** [comment]
Logs for a test case that logs the user out of the application on both iOS 12.1 and 12.2
https://gist.github.com/andrew-lai-bjss/497871d16ec6430406321b82f97459d1

On 12.1 the test completes successfully as the context of the application is retained and it can click the "Sign in" link to take the user to the MS ADAL login screen

On 12.2 the test times out waiting for the "Sign in" link to appear which is present on the screen (when viewing the Simulator) however the context has switched. The context switches because the logout calls an external URL to logout which the Appium seems to follow but doesn't follow the return back to the main application. iOS 12.1 doesn't appear to follow the context switch and remains on the main application.

I hope that makes sense and helps.

**Comment by imurchie** [comment]
Sorry for the questions, but I'm trying to get a concrete sense of what is happening so I can reproduce and fix on the server side.

The scenario is that 
1. there is a page with a "Logout" button (retrieved with `{"using":"xpath","value":"//button/span/span[contains(text(), \"Logout\")]"}`)
1. the button is clicked and a new page opens (?), which on 12.1 is ignored, on 12.2 is directed to

Perhaps the most pertinent thing to reproduce is, what is the `//button/span/span[contains(text(), \"Logout\")]` doing?

**Comment by andrew-lai-bjss** [comment]
@imurchie The logout button calls the MS ADAL (cordova plugin) logout URL in a hidden in app browser.

**Comment by imurchie** [comment]
By "in-app" browser you mean like https://ionicframework.com/docs/native/in-app-browser?

**Comment by imurchie** [comment]
Ok. Making an app to test this out and see what can be done.

**Comment by imurchie** [comment]
@andrew-lai-bjss Can you give any further information about the context? For a basic Cordova app (just the `blank` app with a button added), I couldn't get it to not follow the opened, but hidden, page on 12.1 or 12.2, using Xcode 10.2.1.

The in-app window is configured as such:
```js
var url = 'https://saucelabs.com';
var target = '_blank';
var options = "location = yes,hidden=yes"
var ref = cordova.InAppBrowser.open(url, target, options);
```

**Comment by imurchie** [comment]
In both cases I can make it work by doing something like what I think you were describing in the original post:
```js
const ctx = await driver.context();

const btn = await driver.elementById('openBrowser');
await btn.click();

if (await driver.context() !== ctx) {
  await driver.context(ctx);
}
```

**Comment by andrew-lai-bjss** [comment]
This is the code for the logout method

`public logout = () => {
    const authenticationContext: AuthenticationContext = this.createAuthContext();
    authenticationContext.tokenCache.clear();

    this.isUserAuthenticated = false;

    const browserOptions: InAppBrowserOptions = {
      hidden: 'yes',
    };

    const browser =
      this.inAppBrowser.create(this.authenticationSettings.logoutUrl, '', browserOptions);

    browser.on('loadstop').subscribe(() => {
      browser.close();
    });

    if (this.appConfig.getAppConfig().logoutClearsTestPersistence) {
      this.testPersistenceProvider.clearPersistedTests();
    }
  }`

**Comment by imurchie** [comment]
Finally able to reproduce, using an Ionic app. I will now begin to try to figure out how to reliably fix it, and not break other functionality.

**Comment by andrew-lai-bjss** [comment]
Thanks @imurchie. It would be good to have them consistent, at the moment I have had to code in special cases to handle this.

**Comment by andrew-lai-bjss** [comment]
Work around implemented and now moved onto iOS 13
