### ISSUE TITLE
Locator Strategy 'css selector' is not supported for this session

### ISSUE THREAD

**Issue by sushkad** [appium/appium#12697]
**Issue** - : Locator Strategy 'css selector' is not supported for this session**

**Please find my below code.**

package com.finacus.app;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebElement;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;
import io.appium.java_client.MobileElement;
import io.appium.java_client.TouchAction;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.android.AndroidElement;
//import io.appium.java_client.ios.IOSDriver;
//import io.appium.java_client.ios.IOSElement;
import io.appium.java_client.remote.MobileCapabilityType;

public class AppTest {

	 public static URL url;
	 public static DesiredCapabilities capabilities;
	 public static AndroidDriver<AndroidElement> d;

	 @BeforeSuite
	 
	 public void SetAppium() throws MalformedURLException, InterruptedException
	 {
		 
		 final String URL_STRING = "http://127.0.0.1:4723/wd/hub";
		 url = new URL(URL_STRING);
		    
		    capabilities = new DesiredCapabilities();
		    capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Lenovo A6020a46");
		    capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
		    capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "5.1.1");
		    capabilities.setCapability(MobileCapabilityType.APP, "E://apkipa/Agent.apk");
		    capabilities.setCapability(MobileCapabilityType.NO_RESET, true);
		    capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "Appium");
		    //capabilities.setCapability("useNewWDA", true);
		    
		    
		    d = new AndroidDriver<AndroidElement>(url, capabilities);
		   // d.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		    
		    System.out.println("Application Launch");
		    Thread.sleep(500);
		    //d.close();
		    //d.resetApp();
		    
	 }
	 
	 		@Test (enabled=true)
	 		public void myFirstTest() throws InterruptedException
	 		{
	 			d.resetApp();
	 			System.out.println("First Test Case");
	 			
	 			Thread.sleep(5000);
	 			d.findElement(By.id("com.rde.agent:id/button_scan")).click();
	 			System.out.println("Scan");
	 			d.findElement(By.className("android.widget.Button")).click();
	 			
	 		        Thread.sleep(50000); 			
		    }
	 		@AfterSuite
	 		public void uninstallApp()
	 		{
	 			d.removeApp("com.rde.agent");
	 			System.out.println("Remove Application");
	 			d.close();
	 		}	 
}

**Comment by mykola-mokhnach** [comment]
Closed as duplicate. The issues happens due to the outdated client library and is not a server problem. Please search for similar issues to get more details.

**Comment by sushkad** [comment]
due to the outdated client library ?
what should i do sir?

**Comment by sushkad** [comment]
Thank you so much.
