### ISSUE TITLE
Appium and sessions using uiautomator2

### ISSUE THREAD

**Issue by caifancito** [appium/appium#12691]
## The problem

1. I encounter this issue in android only. 
2. This happens after I terminate the test run in visual studio using the "Stop Debugging" option. 
3. It appears that the session in the appium server is still alive and waiting for a command after I terminate the test run in visual studio. If I start my tests again, the appium server will terminate the old session and the new session? at what it seems to be a random point in my tests. I suspect that the old session is being terminated after the "newCommandTimeout" value for that session is reached.

How can I terminate the old session? 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13.0
* Desktop OS/version used to run Appium: MacOS Mojave
* Mobile platform/version under test: Android 8.1
* Real device or emulator/simulator: Both
* Appium CLI or Appium.app|exe: Appium Desktop
* .NET Appium.WebDriver 4.0.0.5-beta

## Link to Appium logs
https://gist.github.com/caifancito/e7dc17f7bf8ce13ea519e2b208ea00fd

**Comment by mykola-mokhnach** [comment]
> It appears that the session in the appium server is still alive and waiting for a command after I terminate the test run in visual studio. If I start my tests again, the appium server will terminate the old session and the new session? at what it seems to be a random point in my tests. I suspect that the old session is being terminated after the "newCommandTimeout" value for that session is reached.

The described behaviour is expected. `newCommandTimeout` verification is only triggered when a following command is executed in scope of the same session. The newly created driver knows nothing about the state of the previous session and simply deletes it in order to be able to start properly, because only a single session can run on the same device simultaneously.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
