### ISSUE TITLE
iOS Class Chain returns error

### ISSUE THREAD

**Issue by sebinjoseph1994** [appium/appium#12709]
## The question

I'm using iOS class chain method to find an element and unfortunately, I'm not successful.
Referring to https://github.com/facebookarchive/WebDriverAgent/wiki/Class-Chain-Queries-Construction-Rules, I had created the class chain as
_**/XCUIElementTypeTable/XCUIElementTypeCell[`visible == 1`][$type == XCUIElementTypeStaticText AND name == 'Status'$]/XCUIElementTypeStaticText[2]_

But appium returns  {"value":"The attribute 'XCUIElementTypeStaticText' is unknown. Please help me to figure out what's wrong with my class chain.

## Appium logs

[debug] [W3C (7a905229)] Calling AppiumDriver.findElement() with args: ["-ios class chain","**/XCUIElementTypeTable/XCUIElementTypeCell[`visible == 1`][$type == XCUIElementTypeStaticText AND name == 'Status'$]/XCUIElementTypeStaticText[2]","7a905229-4d9f-40cc-b6a3-885a68fea99a"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/44500B3A-B5A2-4C98-86E0-89A3B68605BE/element] with body: {"using":"class chain","value":"**/XCUIElementTypeTable/XCUIElementTypeCell[`visible == 1`][$type == XCUIElementTypeStaticText AND name == 'Status'$]/XCUIElementTypeStaticText[2]"}
[debug] [WD Proxy] Got response with status 200: {"value":"The attribute 'XCUIElementTypeStaticText' is unknown. Valid attribute names are: (\n    UID,\n    accessibilityContainer,\n    accessible,\n    enabled,\n    frame,\n    label,\n    name,\n    rect,\n    type,\n    value,\n    visible,\n    wdAccessibilityContainer,\n    wdAccessible,\n    wdEnabled,\n    wdFrame,\n    wdLabel,\n    wdName,\n    wdRect,\n    wdType,\n    wdUID,\n    wdValue,\n    wdVisible\n)\n\n(\n\t0   CoreFoundation                      0x0000000101a141bb __exceptionPreprocess + 331\n\t1   libobjc.A.dylib                     0x0000000100fb2735 objc_exception_throw + 48\n\t2   WebDriverAgentLib                   0x000000011876f575 +[FBElementUtils wdAttributeNameForAttributeName:] + 709\n\t3   WebDriverAgentLib                   0x000000011876c373 +[NSExpression(FBFormat) fb_wdExpressionWithExpression:] + 579\n\t4   WebDriverAgentLib                   0x0000000118783f78 __50+[NSPredicate(FBFormat) fb_formatSearchPredicate:]_block_invoke + 216\n\t5   WebDriverAgentLib           ...
[WD Proxy] Got an unexpected response: {"value":"The attribute 'XCUIElementTypeStaticText' is unknown. Valid attribute names are: (\n    UID,\n    accessibilityContainer,\n    accessible,\n    enabled,\n    frame,\n    label,\n    name,\n    rect,\n    type,\n    value,\n    visible,\n    wdAccessibilityContainer,\n    wdAccessible,\n...

**Comment by mykola-mokhnach** [comment]
`type` is of type string, which means the following `XCUIElementTypeStaticText` should be quoted. Closed as not an issue

**Comment by sebinjoseph1994** [comment]
@mykola-mokhnach Thank you. The documentation shows it without quotes. Thanks for your immediate help :)

**Comment by mykola-mokhnach** [comment]
Can you provide the link to the corresponding doc. It may be fixed though

**Comment by mykola-mokhnach** [comment]
but yeah, the doc from facebook rep cannot be fixed since it's locked :(

**Comment by sebinjoseph1994** [comment]
https://github.com/facebookarchive/WebDriverAgent/wiki/Class-Chain-Queries-Construction-Rules

**Comment by sebinjoseph1994** [comment]
:(

**Comment by sebinjoseph1994** [comment]
Hi @mykola-mokhnach,

Is there any way where I can check for the direct child element instead of descendant? I mean instead of $, is there exists any character to specify its the direct child and not a grandchild?

**Comment by mykola-mokhnach** [comment]
No, XCTest does not provide such possibility. Although, if there is an element A and one has to find its children by predicate then something like
```
A/XCUIElementTypeAny[`visible == 1`]
```

should do
