### ISSUE TITLE
Appium can't locate notification 'Allow' Button on iPad 12.1+ 

### ISSUE THREAD

**Issue by jenniferhuang** [appium/appium#12704]
## The problem

Appium can't locate notification 'Allow' Button on iPad 12.1+ 

## Environment

* Appium version: 1.13.0
* Node.js version: v12.3.1
* Npm version: 6.9.0
* Mobile platform/version under test:  ios 12.1.4
* Real device or emulator/simulator:  real device(iPad)
* Appium CLI or Appium.app|exe: Appium CLI

## Details
Appium can't locate notification 'Allow' Button on iPad 12.1+ 
We try to click the allow button by
driver.findElement(By.id("Allow")).click(); but it failed for "NoSuchElementException"

**(It is an occasionally case, sometimes it can be clicked successfully.  
but this mobileElement always can be found very very very slowly on appium desktop inspector.)**

![image](https://user-images.githubusercontent.com/5476529/58624587-288d4c00-8303-11e9-9b07-0d3c41d0fadc.png)

**Comment by mykola-mokhnach** [comment]
Unfortunately elements location is performed by XCTest and there is nothing we can do there on Appium side. Try to explicitly wait until the button is there. Also, the standard Selenium alerts API should work for this purpose.

**Comment by umutuzgur** [comment]
@jenniferhuang Have you tried the `useJSONSource` capability? This speeds up the page source fetching operations especially with iPads. You can also try the `simpleIsVisibleCheck` capability to see if it improves the reliability of the locator operation

**Comment by mykola-mokhnach** [comment]
Closed as third party issue.

**Comment by jenniferhuang** [comment]
12.3.1  works well.

**Comment by jenniferhuang** [comment]
@umutuzgur  both useJSONSource and simpleIsVisibleCheck are true in our appium capability setting. bug 12.1  still has this issue,  12.3.1 works well. thanks.
