### ISSUE TITLE
Could not find 'adb' in PATH. Please set the ANDROID_HOME

### ISSUE THREAD

**Issue by DmitriyKapeliukh** [appium/appium#12703]
**The problem**

Could not find 'adb' in PATH. Please set the ANDROID_HOME environment variable with the Android SDK root directory path.

**Environment**

* Appium version: 1.13.0 running on port 4725
* Desktop OS/version used to run Appium: Mac OS 10.14.5
* Node.js version (unless using Appium.app|exe): 11.7.0
* Npm or Yarn package manager: npm 6.5.0
* Mobile platform/version under test: Android emulator
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe:

**Details**
While running my test i've got exception above.
My ~/.profile:

export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_201.jdk/Contents/Home
export PATH="$JAVA_HOME/bin:${PATH}"
export ANDROID_HOME="${HOME}/Library/Android/sdk"
export PATH="${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools"
export MAVEN_HOME="/usr/local/Cellar/maven/3.6.0/libexec"
export PATH="${PATH}:$MAVEN_HOME/bin"

**Comment by FirstAM** [comment]
Hi, try writing these variables in ~/.bash_profile, and reopen appium

**Comment by DmitriyKapeliukh** [comment]
> Hi, try writing these variables in ~/.bash_profile, and reopen appium

I have no bash_profile, all env variables in the /.profile.
The Appium requires to have bash_profile with variables?

**Comment by FirstAM** [comment]
No , appium does not requests bash_profile.
bash_profile the default file to install env on Mac OS for a user.

**Comment by DmitriyKapeliukh** [comment]
Any new suggestions..?

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/java-client/blob/master/docs/environment.md

**Comment by DmitriyKapeliukh** [comment]
I've run "ps eww <Appium PID>" and did not find any related android env variables, it looks like an issue in my case. 

Sorry, but I do not clearly understand how to fix it.

**Comment by mykola-mokhnach** [comment]
It's an issue with the system environment and has nothing to do with Appium itself. Please ask your system administrator for help. Also, you can always ask questions on Appium forum.
