### ISSUE TITLE
chrome://inspect/#devices shows 2 webviews for hybrid app, appium can only see 1

### ISSUE THREAD

**Issue by roddymunro** [appium/appium#12706]
## The problem

I'm trying to automate my hybrid Android app. When using chrome://inspect/#devices to load up devtools for the app, I can see 2 webviews listed. When I do `driver.contexts`, I can only see the native app, and 1 webview. After switching to the webview context, I run `driver.page_source`, and I am only given the page source for the first webview listed in Chrome (the one I don't want, incidentally). 

Inspecting the 1st webview in Chrome devtools shows the source I see (mentioned above), but doesn't show a mirror of the webview in the emulator. I can access these elements from Appium.

Inspecting the 2nd webview in Chrome devtools shows all the elements that I want to automate, as well as a mirror of the webview I see on the emulator, however these are not reachable from Appium by xpath, css selector, class name, etc..

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: macOS Mojave V10.14.5
* Node.js version (unless using Appium.app|exe): v12.2.0
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: Android 9
* Real device or emulator/simulator: Pixel 3 emulator
* Appium CLI or Appium.app|exe: Both

## Screenshots

List of webviews in chrome://inspect/#devices
![Screenshot 2019-05-30 at 15 02 09](https://user-images.githubusercontent.com/11502253/58639383-b3b01700-82ee-11e9-8701-f89fa2ae3f25.png)

Contexts seen in Appium
![Screenshot 2019-05-30 at 15 02 26](https://user-images.githubusercontent.com/11502253/58639384-b448ad80-82ee-11e9-9a91-76b28be90772.png)

## Link to Appium logs

All requests return 200.

**Comment by imurchie** [comment]
Can you turn on Chromedriver logging (set the `showChromedriverLog` desired capability to `true`) and post the full server logs as a link to a http://gist.github.com?

**Comment by roddymunro** [comment]
After some further research and playing around, it's because the page I wanted was in a second tab (not that it was obvious). 

[This issue](https://github.com/appium/appium/issues/11386) led me to the solution 

Switching the window (tab) to the second one fixed it for me: `driver.switch_to.window(driver.window_handles[1])` - hopefully this helps someone else in the future.

Closing issue. :)

**Comment by KazuCocoa** [comment]
thanks for leaving the solution!
