### ISSUE TITLE
Very slow touch release with UiAutomator2 driver in native android application

### ISSUE THREAD

**Issue by grafoxy** [appium/appium#12707]
## The problem

Very slow touch release with UiAutomator2 driver in native android application. In example delay between press and release is 100ms:
```
--> POST /wd/hub/session/session-id/touch/perform
[HTTP] {"actions":[{"action":"press","options":{"element":null,"x":785,"y":807}},{"action":"wait","options":{"ms":100}},{"action":"release","options":{}}]}
```

With UiAutomator driver delay is about 100ms,  but with UiAutomator2 driver, the delay is more than 1000 ms.

## Environment

* Appium version: 1.13.0 (used Appium.exe)
* Desktop OS: Windows 10, version 1809, 64-bit
* Node.js version: 10.14.2
* Npm package manager
* Mobile platform/version under test: Android 5, Android 8, Android 9
* Real devices: samsung s4, nexus 6p, xiaomi mia1

## Details
```js
desiredCapabilities: {
  'platformName': 'Android',
  'device': 'Android',
  'deviceName': deviceName,
  'newCommandTimeout': 180,
  'noReset': false,
  'autoGrantPermissions': true,
  'automationName': 'UiAutomator2',
  'systemPort': 8201,
}
```

## Link to Appium logs
https://gist.github.com/grafoxy/ee69e7298529a256be2e2bd3ec0dd912
Video - https://mega.nz/#!a1gWXSaS!90m5qf5jjP18XYNmvc7jVxenS-LwFxehtr8fZm51sw8

**Comment by mykola-mokhnach** [comment]
Try W3C [actions](https://appiumpro.com/editions/29) to get more control over gestures

**Comment by imurchie** [comment]
The problem is all the element information stuff that was brought in, in https://github.com/appium/appium-uiautomator2-server/pull/117

Without the event registration the timing returns to that of `appium-android-driver`.

**Comment by mykola-mokhnach** [comment]
@jlipps Would you like to check that?

**Comment by jlipps** [comment]
Sounds like we should make this behavior togglable via a capability, since it has performance ramifications. Something like `dontTrackScrollEvents`?

**Comment by imurchie** [comment]
I agree with a cap (and/or setting). Though I would tend toward a opt-in one (e.g., `trackScrollEvents`).

**Comment by mykola-mokhnach** [comment]
I'd also disable it by default

**Comment by jlipps** [comment]
@mykola-mokhnach @imurchie even though it could be a breaking change for people relying on it to disable it?

**Comment by imurchie** [comment]
@jlipps. That's something to consider. I guess it would be a breaking change for them, so opt-out is the only way to go. :(

**Comment by mykola-mokhnach** [comment]
Linking https://github.com/appium/appium-uiautomator2-server/pull/284

**Comment by imurchie** [comment]
`appium-uiautomator2-server@3.7.0` has been published, and is available in the latest beta. In it a setting, `trackScrollEvents`, can be set to `false` to get the speed improvement. This will mean, however, that the tracking of scroll events is not possible.
