### ISSUE TITLE
Desired Capability "skipUnlock" not work

### ISSUE THREAD

**Issue by rebortyang** [appium/appium#12700]
## The problem

When I create a session, I add "skipUnlock" ："true" to Desired Capabilities, but it doesn't skip unlocking and start activity timeout.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13.0
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): 10.15.3
* Mobile platform/version under test: 8.0.0
* Real device or emulator/simulator: device

## Link to Appium logs

[UiAutomator2] 'skipUnlock' capability set, so skipping device unlock
[UiAutomator2] UiAutomator2 did not start the activity we were waiting for, 'com.kfaraj.notepad/.NotepadActivity'. Starting it ourselves
[ADB] Running 'E:\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZY223MQKGV shell am start -W -n com.kfaraj.notepad/.NotepadActivity -S'
[UiAutomator2] Deleting UiAutomator2 session
[UiAutomator2] Deleting UiAutomator2 server session
[WD Proxy] Matched '/' to command name 'deleteSession'
[WD Proxy] Proxying [DELETE /] to [DELETE http://localhost:8200/wd/hub/session/5c8acc20-3700-44d7-ade3-42a80b7f30d2] with no body
[WD Proxy] Got response with status 200: "{\"sessionId\":\"5c8acc20-3700-44d7-ade3-42a80b7f30d2\",\"status\":0,\"value\":\"Session deleted\"}"
[ADB] Running 'E:\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZY223MQKGV shell am force-stop com.kfaraj.notepad'
[Logcat] Stopping logcat capture
[ADB] Removing forwarded port socket connection: 8200 
[ADB] Running 'E:\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZY223MQKGV forward --remove tcp\:8200'
[BaseDriver] Event 'newSessionStarted' logged at 1559113735830 (15:08:55 GMT+0800 (中国标准时间))
[W3C] Encountered internal error running command: Error: Cannot start the 'com.kfaraj.notepad' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Error executing adbExec. Original error: 'Command 'E\:\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s ZY223MQKGV shell am start -W -n com.kfaraj.notepad/.NotepadActivity -S' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability

## Code To Reproduce Issue [ Good To Have ]
```python
# coding: utf-8
import pytest

from appium import webdriver


@pytest.fixture
def create_android_session():
    url = 'http://127.0.0.1:4723/wd/hub'
    desired_caps = {
        'platformName': 'Android', 'platformVersion': '8.0.0', 'deviceName': 'ZY223MQKGV',
        'automationName': 'UiAutomator2', 'appPackage': 'com.kfaraj.notepad', 'appActivity': '.NotepadActivity',
        'autoGrantPermissions': "true"#, "unlockType": "pattern", "unlockKey": "12589" #, 'adbExecTimeout': 50000
        , "skipUnlock": "true"
    }
    with webdriver.Remote(command_executor=url, desired_capabilities=desired_caps) as driver:
        yield driver
```

**Comment by saikrishna321** [comment]
> Original error: Error executing adbExec. Original error: 'Command 'E:\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZY223MQKGV shell am start -W -n com.kfaraj.notepad/.NotepadActivity -S' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability

Can you please set _adbExecTimeout_ capability

**Comment by rebortyang** [comment]
> > 原始错误：执行adbExec时出错。原始错误：'命令'E：\ Android \ Sdk \ platform-tools \ adb.exe -P 5037 -s ZY223MQKGV shell启动-W -n com.kfaraj.notepad / .NotepadActivity -S'在20000ms后超时'。尝试增加'adbExecTimeout'功能所代表的20000毫秒adb执行超时
> 
> 你能否设置_adbExecTimeout_功能？

hello

I set a timeout of 50s -  'adbExecTimeout': 50000, but the result is still the same.
During the start of the activity, the device screen is lit but locked, so I say that skipUnlock is not working.
Or is there a problem with my configuration?
How can I use “skipUnlock ”?

**Comment by mykola-mokhnach** [comment]
> During the start of the activity, the device screen is lit but locked, so I say that skipUnlock is not working.

I'm not getting it. You've explicitly disabled unlock and now complain about the device screen is locked and thus the app cannot start?

**Comment by rebortyang** [comment]
> > During the start of the activity, the device screen is lit but locked, so I say that skipUnlock is not working.
> 
> I'm not getting it. You've explicitly disabled unlock and now complain about the device screen is locked and thus the app cannot start?

Sorry, I don't understand the meaning of skipUnlock. I want to ask what scene will use it?

**Comment by mykola-mokhnach** [comment]
By default android drivers try to execute special helper activity on init, which is supposed to unlock the devices screen in case it is locked with a simple lock screen (aka dimmed). This operation and the corresponding verification takes time, so there is skipUnlock capability, which disables that to save time on driver init when the device under test is configured to be always awake and does not need to be unlocked every time a new test session starts.

I suppose Appium forum would be a better place for such questions. Here is the place for bugs.

**Comment by rebortyang** [comment]
> By default android drivers try to execute special helper activity on init, which is supposed to unlock the devices screen in case it is locked with a simple lock screen (aka dimmed). This operation and the corresponding verification takes time, so there is skipUnlock capability, which disables that to save time on driver init when the device under test is configured to be always awake and does not need to be unlocked every time a new test session starts.
> 
> I suppose Appium forum would be a better place for such questions. Here is the place for bugs.

thank you,  i will close it.
