### ISSUE TITLE
Caching of Geo Location

### ISSUE THREAD

**Issue by deepng** [appium/appium#12701]
## The problem

I want to simulate a User path on the Map.
For this I am trying to set Location on a real device using setLocation(). This is working for the first 2 location updates, after that the lat/long is being cached and the same location is being set.

## Environment

* Appium version : 1.9.1
* Desktop OS/version used to run Appium: Mac OS X 10.4.4
* Node.js version (unless using Appium.app|exe):v11.5.0
* Npm  package manager: 6.4.1
* Mobile platform/version under test: Android 7 & 8
* Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

https://gist.github.com/deepng/cabfd53001802c794774c3f030ae76c7

## Code To Reproduce Issue [ Good To Have ]

` for(Location newLoc: locationList) {
    appiumDriver.setLocation(newLoc);
   System.out.println("Setting mock location to " + newLoc.toString());
    final Location currentDeviceLocation = appiumDriver.location();
   System.out.println("Current location is -  " + location.toString());
}`

Lat-Long being used. Altitude is 0.0 for all locations.

> lat | long
> -- | --
> 12.928676 | 77.6353383
> 12.9291656 | 77.6337535
> 12.9291667 | 77.6332852
> 12.9269344 | 77.6337084

**Comment by deepng** [comment]
I am setting "appium settings" as the mock location app before hitting setLocation()
Appium client version: 7.0.0
Appium Server version: 1.9.1

> adb shell appops get io.appium.settings android:mock_location
MOCK_LOCATION: allow; time=+5m25s155ms ago

**Comment by mykola-mokhnach** [comment]
The current location preciseness is 5 decimal digits. Such behaviour is expected.

**Comment by deepng** [comment]
What is the expected behavior here? According to me setLocation should set the location. If it can do that once, why not can't it do it twice? I see "NeedsInfo" label, let me know what other info is required. 
I have updated the lat long to use 4 decimal digits. But it's not getting updated even now. 

> Setting mock location to Latitude: 12.9287, Longitude: 77.6354, Altitude: 0.0
Current location is -  Latitude: 12.9264, Longitude: 77.6338, Altitude: 0.0

**Comment by mykola-mokhnach** [comment]
Check the logcat output. Perhaps, Android itself ignores new coordinates if these are sent too often

**Comment by deepng** [comment]
I can resolve this issue by restarting Appium Settings before changing location. As @mykola-mokhnach  said this might be an android issue. I haven't checked the logs for this. But will do that today and get back if I find anything.

**Comment by deepng** [comment]
Code to stop and start Appium Settings, just for future reference.

`adb shell am force-stop io.appium.settings
adb shell am start -n io.appium.settings/io.appium.settings.Settings`

**Comment by mykola-mokhnach** [comment]
Also make sure you use the most recent Appium version. 1.9.1 is out of date

**Comment by umutuzgur** [comment]
@deepng There are some fixes in the newer versions for Geo Location setting. As @mykola-mokhnach suggested, I would try the latest versions

**Comment by deepng** [comment]
I checked logcat but didn't find any issues there. 
I updated Appium to 1.12.1 but now I am getting "Broadcasting: Intent { act=io.appium.settings.location flg=0x400000 cmp=io.appium.settings/.receivers.LocationInfoReceiver }" in the emulator Nexus_5X_API_27

**Comment by mykola-mokhnach** [comment]
Without the detailed logs there is not much we can do there. Please comment her if you can get more information on the described problem.

**Comment by deepng** [comment]
Here are the logs - TestNG trace - https://gist.github.com/deepng/724fbdacf4be20c8299479fbe6992dc2
Appium Server Logs - https://gist.github.com/deepng/bd5bf063a2d26135e152d24f5c956c11

**Comment by mykola-mokhnach** [comment]
Any chance to add the logcat output?

**Comment by deepng** [comment]
@mykola-mokhnach - Appium Logs again -https://gist.github.com/deepng/93c25e5a8cd5fcb268d4ef2602aacb81
And the relevant LogCat output - https://gist.github.com/deepng/56b4302af6256cf90bf965e77a148ac1

I have tried this on Appium version  1.12.1 and 1.13.0  and both fail consistently on the test device which is running Andriod 8.1.

**Comment by mykola-mokhnach** [comment]
> 06-05 12:43:53.673  1590  2673 W ActivityManager: Background start not allowed: service Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=io.appium.settings/.LocationService (has extras) } to io.appium.settings/.LocationService from pid=22327 uid=2000 pkg=com.android.shell

Are you sure the foreground service created by Appium Settings is working and enabled?

**Comment by deepng** [comment]
Yes, Just to make sure of this I run `adb shell  am start -n io.appium.settings/io.appium.settings.Settings` before every setLocation() call.

**Comment by mykola-mokhnach** [comment]
> Yes, Just to make sure of this I run adb shell am start -n io.appium.settings/io.appium.settings.Settings before every setLocation() call.

If the foreground service is working properly, then it shouldn't be necessary to trigger that command. IT might be also a phone shell issue (I see that MiUI is used there). In such case there is nothing we can do there from our side.

**Comment by mykola-mokhnach** [comment]
Might be related to https://github.com/appium/appium/issues/12734
