### ISSUE TITLE
Matched JSONWP error code 13 to UnknownError

### ISSUE THREAD

**Issue by divaashini** [appium/appium#12714]
## The problem

Matched JSONWP error code 13 to UnknownError

## Environment

* Appium version (or git revision) that exhibits the issue:v1.13.0
* Desktop OS/version used to run Appium: v10.14.5
* Mobile platform/version under test: iPhone XS 12.2
* Simulator

## Link to Appium logs

[debug] [35m[XCUITest][39m Sending createSession command to WDA
[debug] [35m[WD Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[WD Proxy][39m Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[warn] [35m[WD Proxy][39m Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [35m[XCUITest][39m Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100). Retrying...[debug] [35m[BaseDriver][39m Event 'wdaSessionAttempted' logged at 1559560824569 (19:20:24 GMT+0800 (+08))
[debug] [35m[XCUITest][39m Sending createSession command to WDA
[debug] [35m[WD Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[WD Proxy][39m Proxying [GET /status] to [GET http://localhost:8100/status] with no body

## Code To Reproduce Issue [ Good To Have ]

info] [35m[Appium][39m Appium v1.13.0 creating new XCUITestDriver (v2.113.2) session
[info] [35m[Appium][39m Capabilities:
[info] [35m[Appium][39m   app: /Users/Divaashini/Desktop/demo.ipa
[info] [35m[Appium][39m   automationName: XCUITest
[info] [35m[Appium][39m   deviceName: iPhone XS
[info] [35m[Appium][39m   platformName: iOS
[info] [35m[Appium][39m   platformVersion: 12.2
[info] [35m[Appium][39m   newCommandTimeout: 0
[info] [35m[Appium][39m   connectHardwareKeyboard: true

**Comment by mykola-mokhnach** [comment]
Please provide the full server log
