### ISSUE TITLE
await is only valid in async function' when running a test in js (webdriverio)

### ISSUE THREAD

**Issue by mbokinala** [appium/appium#12722]
## The problem

I am running the code from the 'Get Started' page of the Appium website and I am running into the following error: 

```
const field = await client.$("~TextField1");
              ^^^^^

SyntaxError: await is only valid in async function
```

## Environment

* Appium version (or git revision) that exhibits the issue: **1.13.0**
* Desktop OS/version used to run Appium: **Windows 10**
* Mobile platform/version under test: **Android 8.0**
* Real device or emulator/simulator: **Android Emulator (Google Pixel 2)**
* Appium CLI or Appium.app|exe: **Appium App**

## Details

I ran the code _exactly_ copied from the Appium website under 'Get Started' and I ran into the error described above.

## Link to Appium logs
[info] [35m[Appium][39m Welcome to Appium v1.13.0
[info] [35m[Appium][39m Appium REST http interface listener started on 0.0.0.0:4723

_Note: the logs don't seem to show a connection to the Appium server running on localhost:4723 ocurring_

## Code To Reproduce Issue [ Good To Have ]

~~~
const wdio = require("webdriverio");

const opts = {
  port: 4723,
  capabilities: {
    platformName: "Android",
    platformVersion: "8.0",
    deviceName: "Pixel 2 Android 8.0",
    app: "./ApiDemos.apk",
    automationName: "UiAutomator2"
  }
};

const client = wdio.remote(opts);

const field = await client.$("~TextField1");
await field.setValue("Hello World!");
const value = await field.getValue();
assert.equal(value,"Hello World!");
~~~

**Comment by dpgraham** [comment]
How are you running the server? Are you installing from npm `npm install -g appium` and then running `appium`?

**Comment by mykola-mokhnach** [comment]
Please follow wdio examples: https://github.com/webdriverio/appium-boilerplate

The error above is expected and means that something like `asyncify` helper should be used on async code in order to call it from the main module. 

Closed as not an issue.

**Comment by mbokinala** [comment]
> How are you running the server? Are you installing from npm `npm install -g appium` and then running `appium`?

I am using the appium desktop app.

**Comment by dpgraham** [comment]
Try running with Node v12

**Comment by imurchie** [comment]
The "Getting Started" page was recently fixed. I guess it hasn't been updated on appium.io.

See https://github.com/appium/appium/blob/master/docs/en/about-appium/getting-started.md
