### ISSUE TITLE
click on elements don't work in landscape mode

### ISSUE THREAD

**Issue by ArtemVarnavskiy** [appium/appium#12729]
**The problem**
I am not getting errors, but clicking on elements does not occur!
I have no problems in portrait mode.

**Environment**

* Appium version (or git revision) that exhibits the issue: 1.13.0-beta.3
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: MAC 10.14.4
* Node.js version (unless using Appium.app|exe): v10.15.3
* Mobile platform/version under test: iOS 11.2
* Real device or emulator/simulator: simulator

**Comment by KazuCocoa** [comment]
Could you attach the full appium log (ideally, showXcodeLog true) as the issue template?
They have much info to understand your situation

**Comment by mykola-mokhnach** [comment]
Might be related to https://github.com/facebookarchive/WebDriverAgent/issues/856

**Comment by ArtemVarnavskiy** [comment]
@KazuCocoa 
Appium log:

[Appium] Welcome to Appium v1.13.0-beta.3
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"platformName":"ios","deviceName":"iPad Air 2","platformVersion":"11.2","app":"/Users/team3/Desktop/Autotests_sfa/applications/dev/HybridContainer.app","automationName":"XCUITest","orientation":"LANDSCAPE"},"capabilities":{"firstMatch":[{"platformName":"ios","appium:deviceName":"iPad Air 2","appium:platformVersion":"11.2","appium:app":"/Users/team3/Desktop/Autotests_sfa/applications/dev/HybridContainer.app","appium:automationName":"XCUITest","appium:orientation":"LANDSCAPE"}]}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"platformName":"ios","deviceName":"iPad Air 2","platformVersion":"11.2","app":"/Users/team3/Desktop/Autotests_sfa/applications/dev/HybridContainer.app","automationName":"XCUITest","orientation":"LANDSCAPE"},null,{"firstMatch":[{"platformName":"ios","appium:deviceName":"iPad Air 2","appium:platformVersion":"11.2","appium:app":"/Users/team3/Desktop/Autotests_sfa/applications/dev/HybridContainer.app","appium:automationName":"XCUITest","appium:orientation":"LANDSCAPE"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1559827812837 (16:30:12 GMT+0300 (GMT+03:00))
[Appium] Appium v1.13.0-beta.3 creating new XCUITestDriver (v2.114.2) session
[Appium] Capabilities:
[Appium]   platformName: ios
[Appium]   deviceName: iPad Air 2
[Appium]   platformVersion: 11.2
[Appium]   app: /Users/team3/Desktop/Autotests_sfa/applications/dev/HybridContainer.app
[Appium]   automationName: XCUITest
[Appium]   orientation: LANDSCAPE
[debug] [BaseDriver] W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP desired capabilities {"platformName":"ios","devi... were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"platformNa...
[BaseDriver] Session created with session id: be6732c1-7bc4-4634-aeb6-4f114a04f713
[debug] [XCUITest] Current user: 'team3'
[XCUITest] iOS SDK Version set to '11.2'
[iOSSim] Constructing iOS simulator for Xcode version 9.2 with udid 'F9E13980-5A65-46F1-905B-804D3422B668'
[XCUITest] Determining device to run tests on: udid: 'F9E13980-5A65-46F1-905B-804D3422B668', real device: false
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1559827813401 (16:30:13 GMT+0300 (GMT+03:00))
[BaseDriver] Using local app '/Users/team3/Desktop/Autotests_sfa/applications/dev/HybridContainer.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1559827813404 (16:30:13 GMT+0300 (GMT+03:00))
[debug] [XCUITest] Checking whether app '/Users/team3/Desktop/Autotests_sfa/applications/dev/HybridContainer.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [iOS] Getting bundle ID from app '/Users/team3/Desktop/Autotests_sfa/applications/dev/HybridContainer.app': 'com.moscow.alfaintranet.SFAQA'
[debug] [BaseDriver] Event 'resetStarted' logged at 1559827813416 (16:30:13 GMT+0300 (GMT+03:00))
[XCUITest] Not scrubbing third party app in anticipation of uninstall
[debug] [BaseDriver] Event 'resetComplete' logged at 1559827813509 (16:30:13 GMT+0300 (GMT+03:00))
[XCUITest] Continuing without capturing device logs: iOS Simulator with udid F9E13980-5A65-46F1-905B-804D3422B668 is not running
[XCUITest] Setting up simulator
[debug] [iOS] No reason to set locale
[debug] [iOS] No iOS / app preferences to set
[debug] [iOSSim] Setting preferences of F9E13980-5A65-46F1-905B-804D3422B668 Simulator to {"SimulatorWindowOrientation":"LandscapeLeft","SimulatorWindowRotationAngle":90,"ConnectHardwareKeyboard":false}
[debug] [iOSSim] Setting common Simulator preferences to {"RotateWindowWhenSignaledByGuest":true,"ConnectHardwareKeyboard":false}
[debug] [iOSSim] Updated F9E13980-5A65-46F1-905B-804D3422B668 Simulator preferences at '/Users/team3/Library/Preferences/com.apple.iphonesimulator.plist' with {"DevicePreferences":{"F9E13980-5A65-46F1-905B-804D3422B668":{"SimulatorWindowOrientation":"LandscapeLeft","SimulatorWindowRotationAngle":90,"ConnectHardwareKeyboard":false}},"RotateWindowWhenSignaledByGuest":true,"ConnectHardwareKeyboard":false}
[iOSSim] Booting Simulator with UDID F9E13980-5A65-46F1-905B-804D3422B668...
[iOSSim] Starting Simulator UI with command: open -Fn /Users/team3/Downloads/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID F9E13980-5A65-46F1-905B-804D3422B668 -ConnectHardwareKeyboard 0
[iOSSim] Simulator with UDID F9E13980-5A65-46F1-905B-804D3422B668 booted in 8 seconds
[debug] [BaseDriver] Event 'simStarted' logged at 1559827822200 (16:30:22 GMT+0300 (GMT+03:00))
[debug] [XCUITest] Starting log capture for iOS Simulator with udid 'F9E13980-5A65-46F1-905B-804D3422B668', using 'xcrun simctl spawn F9E13980-5A65-46F1-905B-804D3422B668 log stream --style compact'
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1559827822664 (16:30:22 GMT+0300 (GMT+03:00))
[debug] [XCUITest] Verifying application platform
[debug] [XCUITest] CFBundleSupportedPlatforms: ["iPhoneSimulator"]
[debug] [XCUITest] Reset requested. Removing app with id 'com.moscow.alfaintranet.SFAQA' from the device
[debug] [XCUITest] Installing '/Users/team3/Desktop/Autotests_sfa/applications/dev/HybridContainer.app' on Simulator with UUID 'F9E13980-5A65-46F1-905B-804D3422B668'...
[debug] [XCUITest] The app has been installed successfully.
[debug] [BaseDriver] Event 'appInstalled' logged at 1559827826906 (16:30:26 GMT+0300 (GMT+03:00))
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[debug] [XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[debug] [XCUITest] Parsed BUILD_DIR configuration value: '/Users/team3/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products'
[debug] [XCUITest] Got derived data root: '/Users/team3/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy'
[debug] [XCUITest] Starting WebDriverAgent initialization with the synchronization key '/Users/team3/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy'
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [XCUITest] WDA is not listening at 'http://localhost:8100/'
[debug] [XCUITest] WDA is currently not running. There is nothing to cache
[debug] [XCUITest] Trying to start WebDriverAgent 2 times with 10000ms interval
[debug] [XCUITest] These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1559827828684 (16:30:28 GMT+0300 (GMT+03:00))
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing running processes 'xcodebuild.*F9E13980-5A65-46F1-905B-804D3422B668, iproxy 8100, F9E13980-5A65-46F1-905B-804D3422B668.*XCTRunner' for the device F9E13980-5A65-46F1-905B-804D3422B668...
[debug] [XCUITest] 'pgrep -nif xcodebuild.*F9E13980-5A65-46F1-905B-804D3422B668' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] 'pgrep -nif iproxy 8100' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] 'pgrep -nif F9E13980-5A65-46F1-905B-804D3422B668.*XCTRunner' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] Using Xcode 9.2, so fixing WDA codebase
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath /Users/team3/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy -destination id=F9E13980-5A65-46F1-905B-804D3422B668 IPHONEOS_DEPLOYMENT_TARGET=11.2 GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will only be logged if any errors are present there. To change this, use 'showXcodeLog' desired capability
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [XCUITest] Log file for xcodebuild test: /var/folders/0t/x4j1ty9d0919z7yn3pkg75v40000gp/T/com.apple.dt.XCTest/IDETestRunSession-D10F3DEE-3620-40DF-9173-1CC8726BAF63/WebDriverAgentRunner-DA282915-3B76-408C-B196-65C76489CF5E/Session-WebDriverAgentRunner-2019-06-06_163030-CzHPKf.log
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [WD Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"11.2\",\n      \"sdkVersion\" : \"11.2\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"11.2\",\n      \"ip\" : \"172.28.70.57\"\n    },\n    \"build\" : {\n      \"upgradedAt\" : \"1558610095686\",\n      \"time\" : \"May 23 2019 15:39:46\",\n      \"productBundleIdentifier\" : \"com.facebook.WebDriverAgentRunner\"\n    }\n  },\n  \"sessionId\" : \"59F3D4B4-3E28-4937-8C51-CD7D4FA33E61\",\n  \"status\" : 0\n}"
[debug] [WD Proxy] Determined that the downstream protocol for proxy is MJSONWP
[debug] [XCUITest] WebDriverAgent information:
[debug] [XCUITest] {
[debug] [XCUITest]   "state": "success",
[debug] [XCUITest]   "os": {
[debug] [XCUITest]     "name": "iOS",
[debug] [XCUITest]     "version": "11.2",
[debug] [XCUITest]     "sdkVersion": "11.2"
[debug] [XCUITest]   },
[debug] [XCUITest]   "ios": {
[debug] [XCUITest]     "simulatorVersion": "11.2",
[debug] [XCUITest]     "ip": "172.28.70.57"
[debug] [XCUITest]   },
[debug] [XCUITest]   "build": {
[debug] [XCUITest]     "upgradedAt": "1558610095686",
[debug] [XCUITest]     "time": "May 23 2019 15:39:46",
[debug] [XCUITest]     "productBundleIdentifier": "com.facebook.WebDriverAgentRunner"
[debug] [XCUITest]   }
[debug] [XCUITest] }
[debug] [XCUITest] WebDriverAgent successfully started after 4572ms
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1559827833332 (16:30:33 GMT+0300 (GMT+03:00))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.moscow.alfaintranet.SFAQA","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[debug] [WD Proxy] Got response with status 200: {"value":{"sessionId":"0E968E46-D22C-4326-AE32-1676344F9F3C","capabilities":{"device":"ipad","browserName":"SFADev","sdkVersion":"11.2","CFBundleIdentifier":"com.moscow.alfaintranet.SFAQA"}},"sessionId":"0E968E46-D22C-4326-AE32-1676344F9F3C","status":0}
[debug] [WD Proxy] Determined that the downstream protocol for proxy is MJSONWP
[debug] [BaseDriver] Event 'wdaSessionStarted' logged at 1559827835537 (16:30:35 GMT+0300 (GMT+03:00))
[debug] [BaseDriver] Event 'wdaStarted' logged at 1559827835537 (16:30:35 GMT+0300 (GMT+03:00))
[debug] [XCUITest] Setting initial orientation to 'LANDSCAPE'
[debug] [WD Proxy] Matched '/orientation' to command name 'setOrientation'
[debug] [WD Proxy] Proxying [POST /orientation] to [POST http://localhost:8100/session/0E968E46-D22C-4326-AE32-1676344F9F3C/orientation] with body: {"orientation":"LANDSCAPE"}
[debug] [WD Proxy] Got response with status 200: {"value":{},"sessionId":"0E968E46-D22C-4326-AE32-1676344F9F3C","status":0}
[debug] [BaseDriver] Event 'orientationSet' logged at 1559827836570 (16:30:36 GMT+0300 (GMT+03:00))
[Appium] New XCUITestDriver session created successfully, session be6732c1-7bc4-4634-aeb6-4f114a04f713 added to master session list
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1559827836572 (16:30:36 GMT+0300 (GMT+03:00))
[debug] [W3C (be6732c1)] Cached the protocol value 'W3C' for the new session be6732c1-7bc4-4634-aeb6-4f114a04f713
[debug] [W3C (be6732c1)] Responding to client with driver.createSession() result: {"capabilities":{"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"platformName":"ios","deviceName":"iPad Air 2","platformVersion":"11.2","app":"/Users/team3/Desktop/Autotests_sfa/applications/dev/HybridContainer.app","automationName":"XCUITest","orientation":"LANDSCAPE","udid":"F9E13980-5A65-46F1-905B-804D3422B668"}}
[HTTP] <-- POST /wd/hub/session 200 23744 ms - 527
[HTTP] 
[HTTP] --> POST /wd/hub/session/be6732c1-7bc4-4634-aeb6-4f114a04f713/timeouts
[HTTP] {"implicit":120000}
[debug] [W3C (be6732c1)] Calling AppiumDriver.timeouts() with args: [null,null,null,null,120000,"be6732c1-7bc4-4634-aeb6-4f114a04f713"]
[debug] [XCUITest] Executing command 'timeouts'
[debug] [BaseDriver] W3C timeout argument: {"implicit":120000}}
[debug] [BaseDriver] Set implicit wait to 120000ms
[debug] [W3C (be6732c1)] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/be6732c1-7bc4-4634-aeb6-4f114a04f713/timeouts 200 39 ms - 14
[HTTP] 
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.13.0-beta.3"}}
[HTTP] <-- GET /wd/hub/status 200 6 ms - 75
[HTTP] 
[HTTP] --> POST /wd/hub/session/be6732c1-7bc4-4634-aeb6-4f114a04f713/element
[HTTP] {"using":"xpath","value":"//XCUIElementTypeOther[contains(@name,'Имя пользователя')]/following-sibling::XCUIElementTypeSecureTextField"}
[debug] [W3C (be6732c1)] Calling AppiumDriver.findElement() with args: ["xpath","//XCUIElementTypeOther[contains(@name,'Имя пользователя')]/following-sibling::XCUIElementTypeSecureTextField","be6732c1-7bc4-4634-aeb6-4f114a04f713"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 120000 ms for condition
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/0E968E46-D22C-4326-AE32-1676344F9F3C/element] with body: {"using":"xpath","value":"//XCUIElementTypeOther[contains(@name,'Имя пользователя')]/following-sibling::XCUIElementTypeSecureTextField"}
[debug] [WD Proxy] Got response with status 200: {"value":{"ELEMENT":"0B000000-0000-0000-C719-000000000000"},"sessionId":"0E968E46-D22C-4326-AE32-1676344F9F3C","status":0}
[debug] [W3C (be6732c1)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"0B000000-0000-0000-C719-000000000000","ELEMENT":"0B000000-0000-0000-C719-000000000000"}
[HTTP] <-- POST /wd/hub/session/be6732c1-7bc4-4634-aeb6-4f114a04f713/element 200 1351 ms - 137
[HTTP] 
[HTTP] --> POST /wd/hub/session/be6732c1-7bc4-4634-aeb6-4f114a04f713/element/0B000000-0000-0000-C719-000000000000/click
[HTTP] {}
[W3C (be6732c1)] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [WD Proxy] Matched '/wd/hub/session/be6732c1-7bc4-4634-aeb6-4f114a04f713/element/0B000000-0000-0000-C719-000000000000/click' to command name 'click'
[debug] [WD Proxy] Proxying [POST /wd/hub/session/be6732c1-7bc4-4634-aeb6-4f114a04f713/element/0B000000-0000-0000-C719-000000000000/click] to [POST http://localhost:8100/session/0E968E46-D22C-4326-AE32-1676344F9F3C/element/0B000000-0000-0000-C719-000000000000/click] with body: {}
[debug] [WD Proxy] Got response with status 200: {"status":0,"id":"0B000000-0000-0000-C719-000000000000","value":"","sessionId":"0E968E46-D22C-4326-AE32-1676344F9F3C"}
[WD Proxy] Replacing sessionId 0E968E46-D22C-4326-AE32-1676344F9F3C with be6732c1-7bc4-4634-aeb6-4f114a04f713
[HTTP] <-- POST /wd/hub/session/be6732c1-7bc4-4634-aeb6-4f114a04f713/element/0B000000-0000-0000-C719-000000000000/click 200 457 ms - 118
[HTTP] 
[HTTP] --> DELETE /wd/hub/session/be6732c1-7bc4-4634-aeb6-4f114a04f713
[HTTP] {}
[debug] [W3C (be6732c1)] Calling AppiumDriver.deleteSession() with args: ["be6732c1-7bc4-4634-aeb6-4f114a04f713"]
[debug] [BaseDriver] Event 'quitSessionRequested' logged at 1559827841449 (16:30:41 GMT+0300 (GMT+03:00))
[Appium] Removing session be6732c1-7bc4-4634-aeb6-4f114a04f713 from our master session list
[debug] [WD Proxy] Matched '/session/be6732c1-7bc4-4634-aeb6-4f114a04f713' to command name 'deleteSession'
[debug] [WD Proxy] Proxying [DELETE /session/be6732c1-7bc4-4634-aeb6-4f114a04f713] to [DELETE http://localhost:8100/session/0E968E46-D22C-4326-AE32-1676344F9F3C] with no body
[debug] [WD Proxy] Got response with status 200: "{\n  \"value\" : {\n\n  },\n  \"sessionId\" : \"782D49F5-6667-4443-A593-3A8681FE010B\",\n  \"status\" : 0\n}"
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [iOSLog] Stopping iOS log capture
[debug] [BaseDriver] Event 'quitSessionFinished' logged at 1559827841667 (16:30:41 GMT+0300 (GMT+03:00))
[debug] [W3C (be6732c1)] Received response: null
[debug] [W3C (be6732c1)] But deleting session, so not returning
[debug] [W3C (be6732c1)] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/be6732c1-7bc4-4634-aeb6-4f114a04f713 200 221 ms - 14
[HTTP]

**Comment by mykola-mokhnach** [comment]
> [iOSSim] Constructing iOS simulator for Xcode version 9.2 with udid 'F9E13980-5A65-46F1-905B-804D3422B668'

Did you try to update Xcode?

**Comment by ArtemVarnavskiy** [comment]
@mykola-mokhnach I can't to update Xcode. Xcode version 9.2 is needed for other purposes on my work(

**Comment by mykola-mokhnach** [comment]
Then, unfortunately, we won't be able to help there much

**Comment by ArtemVarnavskiy** [comment]
@mykola-mokhnach I update Xcode and it helped me. Thank!
