### ISSUE TITLE
Error getting device API level. Original error: Error executing adbExec

### ISSUE THREAD

**Issue by Amrkamel1** [appium/appium#12736]
## Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. **Original error: Error getting device API level**. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\amrka\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk' exited with code 3221226356'; Stderr: ''; Code: '3221226356'

error appears suddenly after latest update from android studio unable me to run any test on real devices or emulator

## Environment

* Appium version 1.13.0
* Desktop win10
* Node.js version: v10.16.0
* Android Debug Bridge version 1.0.41
  Version 29.0.0-5611747
* JDK 1.8.0_211
* java-client 7.0
* testng 6.14.3
* selenium java 3.141.59
* Real device and emulator/simulator

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

[Appium] Welcome to Appium v1.13.0
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"C:\\Users\\amrka\\AndroidStudioProjects\\demo2\\app\\..\\TestingApk\\sfd.apk","appActivity":"com.sfdmobile.MainActivity","appPackage":"com.sarajevo.food.dictionary","clearSystemFiles":true,"platformVersion":"8.1.0","automationName":"uiautomator2","autoGrantPermissions":true,"platformName":"Android","deviceName":"emulator-5554","avd":"myphone"},"capabilities":{"firstMatch":[{"appium:app":"C:\\Users\\amrka\\AndroidStudioProjects\\demo2\\app\\..\\TestingApk\\sfd.apk","appium:appActivity":"com.sfdmobile.MainActivity","appium:appPackage":"com.sarajevo.food.dictionary","appium:autoGrantPermissions":true,"appium:automationName":"uiautomator2","appium:avd":"myphone","appium:clearSystemFiles":true,"appium:deviceName":"emulator-5554","platformName":"android","appium:platformVersion":"8.1.0"}]}}
[W3C] Calling AppiumDriver.createSession() with args: [{"app":"C:\\Users\\amrka\\AndroidStudioProjects\\demo2\\app\\..\\TestingApk\\sfd.apk","appActivity":"com.sfdmobile.MainActivity","appPackage":"com.sarajevo.food.dictionary","clearSystemFiles":true,"platformVersion":"8.1.0","automationName":"uiautomator2","autoGrantPermissions":true,"platformName":"Android","deviceName":"emulator-5554","avd":"myphone"},null,{"firstMatch":[{"appium:app":"C:\\Users\\amrka\\AndroidStudioProjects\\demo2\\app\\..\\TestingApk\\sfd.apk","appium:appActivity":"com.sfdmobile.MainActivity","appium:appPackage":"com.sarajevo.food.dictionary","appium:autoGrantPermissions":true,"appium:automationName":"uiautomator2","appium:avd":"myphone","appium:clearSystemFiles":true,"appium:deviceName":"emulator-5554","platformName":"android","appium:platformVersion":"8.1.0"}]}]
[BaseDriver] Event 'newSessionRequested' logged at 1559923410881 (18:03:30 GMT+0200 (Central European Daylight Time))
[Appium] Appium v1.13.0 creating new AndroidUiautomator2Driver (v1.33.1) session
[Appium] Capabilities:
[Appium]   platformName: android
[Appium]   app: C:\Users\amrka\AndroidStudioProjects\demo2\app\..\TestingApk\sfd.apk
[Appium]   appActivity: com.sfdmobile.MainActivity
[Appium]   appPackage: com.sarajevo.food.dictionary
[Appium]   autoGrantPermissions: true
[Appium]   automationName: uiautomator2
[Appium]   avd: myphone
[Appium]   clearSystemFiles: true
[Appium]   deviceName: emulator-5554
[Appium]   platformVersion: 8.1.0
[BaseDriver] W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP desired capabilities {"app":"C:\\Users\\amrka\\A... were provided
[BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"platformNa...
[BaseDriver] Session created with session id: fa75ac2f-2421-4e77-af55-04f8557d1e62
[BaseDriver] Using local app 'C:\Users\amrka\AndroidStudioProjects\demo2\app\..\TestingApk\sfd.apk'
[UiAutomator2] Checking whether app is actually present
[ADB] Using 'adb.exe' from 'C:\Users\amrka\AppData\Local\Android\sdk\platform-tools\adb.exe'
[ADB] Trying to find 'myphone' emulator
[ADB] Getting connected emulators
[ADB] Getting connected devices...
[ADB] 2 device(s) connected
[ADB] 1 emulator(s) connected
[ADB] Sending telnet command to device: avd name
[ADB] Getting running emulator port
[ADB] Socket connection to device created
[ADB] Socket connection to device ready
[ADB] Telnet command got response: myphone
[ADB] Found emulator 'myphone' on port 5554
[ADB] Setting device id to emulator-5554
[AndroidDriver] Not launching AVD because it is already running.
[AndroidDriver] Using device: emulator-5554
[ADB] Using 'adb.exe' from 'C:\Users\amrka\AppData\Local\Android\sdk\platform-tools\adb.exe'
[ADB] Setting device id to emulator-5554
[ADB] Running 'C:\Users\amrka\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk'
[UiAutomator2] Deleting UiAutomator2 session
[ADB] Running 'C:\Users\amrka\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell am force-stop com.sarajevo.food.dictionary'
[UiAutomator2] Unable to force stop app: Error executing adbExec. Original error: 'Command 'C\:\\Users\\amrka\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 shell am force-stop com.sarajevo.food.dictionary' exited with code 3221226356'; Stderr: ''; Code: '3221226356'
[ADB] Removing forwarded port socket connection: 8200 
[ADB] Running 'C:\Users\amrka\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 forward --remove tcp\:8200'
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command 'C\:\\Users\\amrka\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 forward --remove tcp\:8200' exited with code 1'; Stderr: 'adb.exe: error: listener 'tcp:8200' not found'; Code: '1''
[ADB] Running 'C:\Users\amrka\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk'
[BaseDriver] Event 'newSessionStarted' logged at 1559923415105 (18:03:35 GMT+0200 (Central European Daylight Time))
[W3C] Encountered internal error running command: Error: Error getting device API level. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\amrka\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk' exited with code 3221226356'; Stderr: ''; Code: '3221226356'
[W3C]     at ADB. (C:\Users\amrka\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\adb-commands.js:98:13)
[W3C]     at Generator.throw ()
[W3C]     at asyncGeneratorStep (C:\Users\amrka\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
[W3C]     at _throw (C:\Users\amrka\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\@babel\runtime\helpers\asyncToGenerator.js:29:9)
[W3C]     at run (C:\Users\amrka\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\core-js\modules\es6.promise.js:75:22)
[W3C]     at C:\Users\amrka\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\core-js\modules\es6.promise.js:92:30
[W3C]     at flush (C:\Users\amrka\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\core-js\modules\_microtask.js:18:9)
[W3C]     at process._tickCallback (internal/process/next_tick.js:61:11)
[W3C]     at Object.showMessageBox (C:\Users\amrka\AppData\Local\Programs\Appium\resources\electron.asar\browser\api\dialog.js:278:20)
[W3C]     at showMessageBox (C:\Users\amrka\AppData\Local\Programs\Appium\resources\app\app\main\menus.js:197:14)
[W3C]     at MenuItem.click (C:\Users\amrka\AppData\Local\Programs\Appium\resources\electron.asar\browser\api\menu-item.js:56:9)
[W3C]     at Function.executeCommand (C:\Users\amrka\AppData\Local\Programs\Appium\resources\electron.asar\browser\api\menu.js:31:13)
[HTTP] <-- POST /wd/hub/session 500 4226 ms - 1838
[HTTP] 

## Code To Reproduce Issue [ Good To Have ]

 @BeforeSuite
    public void setUp () throws MalformedURLException {

//        File app = new File("C:\\Users\\amrka\\AndroidStudioProjects\\demo2\\TestingApk\\sfd.apk");
        File app = new File("../TestingApk/sfd.apk");

        DesiredCapabilities dc = new  DesiredCapabilities ();

        dc.setCapability(MobileCapabilityType.APP,app.getAbsolutePath());
//        dc.setCapability(MobileCapabilityType.DEVICE_NAME,"SM_N9208");
        dc.setCapability(MobileCapabilityType.DEVICE_NAME,"emulator-5554");

//        dc.setCapability(MobileCapabilityType.UDID,"0715f75124ea0934");
        dc.setCapability(MobileCapabilityType.PLATFORM_NAME,"Android");
//        dc.setCapability(MobileCapabilityType.PLATFORM_VERSION,"7.0");
        dc.setCapability(MobileCapabilityType.PLATFORM_VERSION,"8.1.0");
        dc.setCapability(MobileCapabilityType.AUTOMATION_NAME,"uiautomator2");

        dc.setCapability("avd","myphone");

        dc.setCapability(AndroidMobileCapabilityType.APP_PACKAGE,"com.sarajevo.food.dictionary");
        dc.setCapability(AndroidMobileCapabilityType.APP_ACTIVITY,"com.sfdmobile.MainActivity");
        dc.setCapability(AndroidMobileCapabilityType.AUTO_GRANT_PERMISSIONS,true);
        dc.setCapability(MobileCapabilityType.CLEAR_SYSTEM_FILES,true);

        driver = new AndroidDriver<MobileElement>(new URL("http://0.0.0.0:4723/wd/hub"),dc);

    }

    @Test
    public void verify_user_can_sign_as_tourist (){
        new WebDriverWait(driver,5).until(ExpectedConditions.visibilityOfAllElementsLocatedBy(By.xpath("//android.widget.TextView[contains(@text, 'Next')]")));
        driver.findElement(By.xpath("//android.widget.TextView[contains(@text, 'Next')]")).click();
        driver.findElement(By.xpath("//android.widget.TextView[contains(@text, 'Next')]")).click();
        driver.findElement(By.xpath("//android.widget.TextView[contains(@text, 'Next')]")).click();
        driver.findElement(By.xpath("//android.widget.TextView[contains(@text, 'Tourist')]")).click();
        driver.findElement(By.xpath("//android.widget.TextView[contains(@text, 'Get Started')]")).click();
        driver.findElements(By.className("android.widget.ImageView")).get(0).click();
        new WebDriverWait(driver,5).until(ExpectedConditions.visibilityOfAllElementsLocatedBy(By.xpath("//android.widget.TextView[contains(@text, 'Settings')]")));
        driver.findElement(By.xpath("//android.widget.TextView[contains(@text, 'Settings')]")).click();
        (new WebDriverWait(driver,5)).until(ExpectedConditions.visibilityOfAllElementsLocatedBy(By.xpath("//android.widget.TextView[contains(@text, 'Tourist')]")));
        Assert.assertEquals(driver.findElement(By.xpath("//android.widget.TextView[contains(@text, 'Tourist')]")).getText(),"Tourist");
    }

    @AfterSuite
    public void tearDown () {
        if (driver != null) {
            driver.quit();

        }
    }

}

**Comment by Amrkamel1** [comment]
@KazuCocoa

**Comment by Amrkamel1** [comment]
@mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
It must be a problem with adb itself. Nothing we can do from Appium side. See https://stackoverflow.com/questions/53181353/adb-keeps-crashing-when-executing-most-commands-like-getprop-ro-build-version-re

**Comment by Amrkamel1** [comment]
@mykola-mokhnach 
but the command work properly through the CMD :
appium log 👍 
 Original error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\amrka\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe -P 5037 -s 988a1641434e36333130 shell getprop ro.build.version.sdk' exited with code 3221226356'; Stderr: ''; Code: '3221226356'
    at getResponseForW3CError (C:\Users\amrka\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:826:9)

![image](https://user-images.githubusercontent.com/32042806/59140187-abb14080-899a-11e9-84c3-d94c53b56841.png)

**Comment by KazuCocoa** [comment]
Was the adb path `C:\Users\amrka\AppData\Local\Android\sdk\platform-tools\adb.exe`?

**Comment by Amrkamel1** [comment]
> Was the adb path `C:\Users\amrka\AppData\Local\Android\sdk\platform-tools\adb.exe`?

no its defined as 
![image](https://user-images.githubusercontent.com/32042806/59140563-d225aa80-899f-11e9-96fa-13c6347bebcf.png)

![image](https://user-images.githubusercontent.com/32042806/59140574-fda89500-899f-11e9-835c-6bc7cb989f7c.png)

![image](https://user-images.githubusercontent.com/32042806/59140585-1f098100-89a0-11e9-9692-c6c4bf0f6a53.png)

![image](https://user-images.githubusercontent.com/32042806/59140591-3ba5b900-89a0-11e9-8bed-65ea75b1a9d9.png)

**Comment by KazuCocoa** [comment]
thanks.
If the root cause is sdk version 29, you should downgrade the adb command (platform-tools).

Appium issues the process via NodeJS. So, potentially, if the cause is related to NodeJS on Windows, updating the node also help.

Or did the command exit error code `3221226356` even if the standard output is '28'?
If so, we can coordinate the error handling in our side (try/catch)

**Comment by Amrkamel1** [comment]
> thanks.
> If the root cause is sdk version 29, you should downgrade the adb command (platform-tools).
> 
> Appium issues the process via NodeJS. So, potentially, if the cause is related to NodeJS on Windows, updating the node also help.
> 
> Or did the command exit error code `3221226356` even if the standard output is '28'?
> If so, we can coordinate the error handling in our side (try/catch)

@KazuCocoa  yes it throws this error code 

Unable to force stop app: Error executing adbExec. Original error: 'Command 'C:\Users\amrka\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell am force-stop com.sarajevo.food.dictionary' exited with code 3221226356'; Stderr: ''; Code: '3221226356'

i think there should be some error handling as u mentioned above since its not best solution to downgrade adb version, anyway im trying now downgrading adb version and will see how it will behave

**Comment by Amrkamel1** [comment]
@KazuCocoa  i have downgraded to adb version Version 28.0.3-5475833 and now its working properly 

conclusion that new adb version is not compatible with appium 1.13, i think some compatibility fix should be done to appium to avoid this issue

**Comment by KazuCocoa** [comment]
Okay. So, the new adb did not work on Windows.

Unfortunately, if adb commands do not work correctly, Appium cannot work correctly even if Appium gets error handlings since Appium commands depend on Google official libraries.

Google should fix the issue for Windows users giving error report them before RC (or official api level 29 release)

**Comment by Amrkamel1** [comment]
> Okay. So, the new adb did not work on Windows.
> 
> Unfortunately, if adb commands do not work correctly, Appium cannot work correctly even if Appium gets error handlings since Appium commands depend on Google official libraries.
> 
> Google should fix the issue for Windows users giving error report them before RC (or official api level 29 release)

yea it makes sense thank you @KazuCocoa

**Comment by SergeySerj** [comment]
I'm getting the same error. [Appium logs](https://gist.github.com/SergeySerj/7d9ec400b0b03335db92559063f99a9e)

Guys what about running ADB directly when no errors raised? That was mentioned above.
I checked - Running `adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.release` returns valid result without errors for several (Android 8.1 and 9) emulators.
So it not ADB problem I suppose.

**Comment by Amrkamel1** [comment]
> I'm getting the same error. [Appium logs](https://gist.github.com/SergeySerj/7d9ec400b0b03335db92559063f99a9e)
> 
> Guys what about running ADB directly when no errors raised? That was mentioned above.
> I checked - Running `adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.release` returns valid result without errors for several (Android 8.1 and 9) emulators.
> So it not ADB problem I suppose.

you are right adb commands working properly with platform tools version 29, but when its interacting with appium it throws the error mentioned above

**Comment by KazuCocoa** [comment]
In my previous comment, I assumed below case happened.
The status code was `3221226356` even it returned `28`. Non-zero status code is something error happens.

What about below?

- Calls directly
```
# please try call as full path like Appium does
> C:\Users\amrka\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037 -s 988a1641434e36333130 shell getprop ro.build.version.sdk
> echo $? # what is the output?
```

The command raises error status, but the output 28 can happen. (In the case, for human, it looks finishing without errors) [note](https://stackoverflow.com/questions/10666035/difference-between-and-lastexitcode-in-powershell)

- Calls via NodeJs like Appium
```
t = require('teen_process');
# Please call the command as full path like Appium does
r = t.exec('C:\Users\amrka\AppData\Local\Android\sdk\platform-tools\adb.exe', ['-P', 5037, '-s', '988a1641434e36333130', 'shell', 'getprop ro.build.version.sdk']);
# wait for a few sec
r.stdout    # 28?
r.stderr     # ?
r.code       # Here is '3221226356',but here should be `0` if  the command works expectedly
```

If you can figure out the cause and how we can improve it, it is very appreciated.

**Comment by SergeySerj** [comment]
Thanks, @KazuCocoa it make sense!
My exit code:
`>adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.release & echo Exit Code is %errorlevel%`
output:
```
9
Exit Code is -1073740940
```

**Comment by SergeySerj** [comment]
Guys, after realized it is ADB related error (thanks to @KazuCocoa), I was able to resolve my issue 

Here is steps I performed to resolve error:

1. Close emulators, go to Android Studio 'SDK Manager', click on 'SDK Tools' tab and review installed components. I found here is 'Android SDK Build-Tools 29' available and unchecked.
2. Install 'Android SDK Build-Tools 29'
3. Restart Android Studio. After restart Android Studio showed tooltip/popup about update available; install that 'Android SDK Platform-Tools (revision: 29.0.1)' update.
4. Start Android 9 emulator again and checked error with command `adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.release & echo Exit Code is %errorlevel%`:
```
9
Exit Code is 0
```
Starting Android emulator 8 and checking version/error code also gives correct results with no error.
The issue is resolved.

BTW here are some question I have no answers yet:

- Previously I have installed Android Emulator 9, SDK Platform 9.0(API Level 28), not sure about Build Tools. And I never noticed any errors. I suppose some version of Build tools were installed as I ran Appium tests through ADB successfully. Later I installed Android Emulator 8.1, SDK Platform 8.1(API Level 27) and started getting errors. It is strange I started getting errors for both Android emulator 9 and 8.1. So that installation broke my working configuration (of Android emulator 9). I wish for Android Studio to be more smart about keeping different SDK/build tools separately to not break working configuration.
- ADB tool error reporting. It is a shame that ADB hide errors in command line. May be the reason for that is that ADB is still able to execute command and return valid results despite internal error.
- Appium: why it does not returns the error code number? Is it because of the node.js mediation? Well, at least we can see a stack trace in Appium logs. Why Appium can't track both valid result from ADB and ADB error code as well?

**Comment by mykola-mokhnach** [comment]
> Appium: why it does not returns the error code number? Is it because of the node.js mediation? Well, at least we can see a stack trace in Appium logs. Why Appium can't track both valid result from ADB and ADB error code as well?

> exited with code 3221226356

isn't this the error code?

>  Why Appium can't track both valid result from ADB and ADB error code as well?

According to the Posix standard the return code which is not zero signals about an erroneous behaviour. How do we know if the actual output is correct or not in such case? Yes, we can add an ugly workaround, which excludes this particular code, but then it would hide the original bug in adb. Also, we don't know if this happens for other commands or for only this particular one and whether other commands would fail with the same code or the other one.

**Comment by SergeySerj** [comment]
> exited with code 3221226356
> 
> isn't this the error code?

You are right @mykola-mokhnach. Sorry, I forgot the Appium logs contained that code.

> According to the Posix standard the return code which is not zero signals about an erroneous behaviour. How do we know if the actual output is correct or not in such case? Yes, we can add an ugly workaround, which excludes this particular code, but then it would hide the original bug in adb. Also, we don't know if this happens for other commands or for only this particular one and whether other commands would fail with the same code or the other one.

It make sense to me. Agree, it is better to throws error instead of silently continue in case we are not sure if result returned from ADB is trustworthy.
Another option is to log a warning about unreliable ADB output and silently consume that result. The logic here is - if ADB still returns something with no crash/explicit error then Appium can do the same, use that ADB result and log a warning.

**Comment by Amrkamel1** [comment]
@SergeySerj @mykola-mokhnach 
issue has been resolved by google and newer version has been released today or yesterday 
adb version 29.0.0., now u dont have to downgrade to 28 just upgrade from server to 29.0.0.1

**Comment by SergeySerj** [comment]
Thanks @Amrkamel1 for info!
I resolved my issue 3 days ago (see my comment about 'Android SDK Platform-Tools (revision: 29.0.1)' update above). So now we know the exact step that helped - it is ADB was upgraded.

**Comment by jpita** [comment]
I'm having this issue now as well, do I need to downgrade adb?
can't find a way to do that with android studio

**Comment by maunigit** [comment]
@mykola-mokhnach I'm having this issue too and downgrade platform-tools to version 29.0.1 doesn't work. Could you help me please?

## Environment

- Appium desktop 1.15.1
- platform-tools 29.0.4
- Adb 1.0.41
- build-tools 29.0.2
- tools 26.1.1 
- OS: Windows 10
- JDK 1.8.0_231
- Node: v10.16.3
- Phone: Xiaomi MI5 with Android 8.0.0

**Comment by Amrkamel1** [comment]
> I'm having this issue now as well, do I need to downgrade adb?
> can't find a way to do that with android studio
> I have platform-tools version 29.0.2

this should be working properly the issue was  with the previous version,
check your environment variables and download the latest appium and try again also it will be good if you add your logs

**Comment by Mynziak** [comment]
Hello! 
Im getting the same error when run test on real device.

 **My environment:**
 MacOS Catalina v. 10.15.1

Appium 1.15.1

Android Debug Bridge version 1.0.41
Version 29.0.5-5949299
Installed as /Users/dmitriyminzyak/Library/Android/sdk/platform-tools/adb

Node.js version = v12.12.0

Appium Log in gist: [https://gist.github.com/Mynziak/aa602e7d92608385bc783e017fef1698](url)

**Comment by AnandChaurasia** [comment]
Any Update how to fix it, I am also getting same error

**Comment by jpita** [comment]
> Any Update how to fix it, I am also getting same error

any details on the software and hardware ur using?
logs?

**Comment by thavamg1** [comment]
Still I am facing this issue . 
Appium:1.15
Selenium Standalone: 3.14
Java client: 7.0
Andriod Platform-tool- 29.0.5
Device: Real device

**Comment by mehtaketan7** [comment]
Facing same issue with
Appium:1.15
AS : 3.6
Java Client : java-client-7.3.0
Device: emulator version 6.0 & 9.0
Android Debug Bridge version 1.0.41

**Comment by KadyrovaEkaterina** [comment]
Hello, I have almost the same issue. I will be very thankful if you could help me out to resolve the issue.
C:\Users\dkady_000>appium
[Appium] Welcome to Appium v1.17.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"C:\\Users\\dkady_000\\eclipse-workspace\\AppiumTutorial\\src\\original.apk","automationName":"uiautomator2","platformName":"Android","deviceName":"Kateemulator"},"capabilities":{"firstMatch":[{"appium:app":"C:\\Users\\dkady_000\\eclipse-workspace\\AppiumTutorial\\src\\original.apk","appium:automationName":"uiautomator2","appium:deviceName":"Kateemulator","platformName":"android"}]}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"app":"C:\\Users\\dkady_000\\eclipse-workspace\\AppiumTutorial\\src\\original.apk","automationName":"uiautomator2","platformName":"Android","deviceName":"Kateemulator"},null,{"firstMatch":[{"appium:app":"C:\\Users\\dkady_000\\eclipse-workspace\\AppiumTutorial\\src\\original.apk","appium:automationName":"uiautomator2","appium:deviceName":"Kateemulator","platformName":"android"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1591209037806 (14:30:37 GMT-0400 (Eastern Daylight Time))
[Appium] Appium v1.17.1 creating new AndroidUiautomator2Driver (v1.44.2) session
[debug] [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {
[debug] [BaseDriver]   "alwaysMatch": {
[debug] [BaseDriver]     "platformName": "android",
[debug] [BaseDriver]     "appium:app": "C:\\Users\\dkady_000\\eclipse-workspace\\AppiumTutorial\\src\\original.apk",
[debug] [BaseDriver]     "appium:automationName": "uiautomator2",
[debug] [BaseDriver]     "appium:deviceName": "Kateemulator"
[debug] [BaseDriver]   },
[debug] [BaseDriver]   "firstMatch": [
[debug] [BaseDriver]     {}
[debug] [BaseDriver]   ]
[debug] [BaseDriver] }
[BaseDriver] Session created with session id: 1d2f6e4c-305f-4895-b7b2-ecbad4ae121e
[BaseDriver] Using local app 'C:\Users\dkady_000\eclipse-workspace\AppiumTutorial\src\original.apk'
[debug] [UiAutomator2] Checking whether app is actually present
[ADB] Found 2 'build-tools' folders under 'C:\Users\dkady_000\AppData\Local\Android\Sdk' (newest first):
[ADB]     C:/Users/dkady_000/AppData/Local/Android/Sdk/build-tools/30.0.0-rc4
[ADB]     C:/Users/dkady_000/AppData/Local/Android/Sdk/build-tools/29.0.3
[ADB] Using 'adb.exe' from 'C:\Users\dkady_000\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] Connected devices: [{"udid":"emulator-5554","state":"device"}]
[AndroidDriver] Using device: emulator-5554
[ADB] Using 'adb.exe' from 'C:\Users\dkady_000\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[debug] [ADB] Setting device id to emulator-5554
[debug] [ADB] Running 'C:\Users\dkady_000\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk'
[debug] [ADB] Current device property 'ro.build.version.sdk': 29
[ADB] Getting device platform version
[debug] [ADB] Running 'C:\Users\dkady_000\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.release'
[debug] [ADB] Current device property 'ro.build.version.release': 10
[debug] [ADB] Device API level: 29
[UiAutomator2] Relaxing hidden api policy
[debug] [ADB] Running 'C:\Users\dkady_000\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell settings put global hidden_api_policy_pre_p_apps 1'
[debug] [UiAutomator2] Deleting UiAutomator2 session
[UiAutomator2] Restoring hidden api policy to the device default configuration
[debug] [ADB] Running 'C:\Users\dkady_000\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell settings delete global hidden_api_policy_pre_p_apps'
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1591209055554 (14:30:55 GMT-0400 (Eastern Daylight Time))
[debug] [W3C] Encountered internal error running command: Error executing adbExec. Original error: 'Command 'C:\\Users\\dkady_000\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 shell settings delete global hidden_api_policy_pre_p_apps' exited with code 20'; Stderr: 'cmd: Can't find service: settings'; Code: '20'
[debug] [W3C] Error: Command 'C:\\Users\\dkady_000\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 shell settings delete global hidden_api_policy_pre_p_apps' exited with code 20
[debug] [W3C]     at ChildProcess.<anonymous> (C:\Users\dkady_000\AppData\Roaming\npm\node_modules\appium\node_modules\teen_process\lib\exec.js:113:19)
[debug] [W3C]     at ChildProcess.emit (events.js:310:20)
[debug] [W3C]     at maybeClose (internal/child_process.js:1021:16)
[debug] [W3C]     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
[debug] [W3C] Destroying socket connection
[HTTP] <-- POST /wd/hub/session 500 18759 ms - 1177
[HTTP]

**Comment by mykola-mokhnach** [comment]
@KadyrovaEkaterina https://stackoverflow.com/questions/42868571/why-is-adb-install-my-apk-triggering-cant-find-service-package
