### ISSUE TITLE
/usr/local/bin/appium: error: Unrecognized arguments: –p 4725

### ISSUE THREAD

**Issue by automationpss** [appium/appium#12733]
I was running following command on Mac Terminal,
**appium –p 4725 --webdriveragent-port 8200**
usage: /usr/local/bin/appium [-h] [-v] [--shell] [--allow-cors] [--reboot]
                             [--ipa IPA] [-a ADDRESS] [-p PORT]
......
......
/usr/local/bin/appium: error: Unrecognized arguments: –p 4725

expected result: no error is returned;
actual result:   error: Unrecognized arguments: –p 4725

But: appium –p 4725 is working as expected with result:
[Appium] Welcome to Appium v1.13.0
[Appium] Non-default server args:
[Appium]   port: 4725
[Appium] Appium REST http interface listener started on 0.0.0.0:4725

## Environment 
* Appium version (or git revision) that exhibits the issue: 1.13.0 
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: MacOS 10.14.5 
* Node.js version (unless using Appium.app|exe):  v11.2.0 
* Npm or Yarn package manager:   6.4.1 
* Mobile platform/version under test:  12.2, 12.1.4 
* Real device or emulator/simulator:  iPhone 6, and iPhone 8 
* Appium CLI or Appium.app|exe:  1.13.0

**Comment by automationpss** [comment]
work around solution: use Appium Desktop.

**Comment by mykola-mokhnach** [comment]
I think there's something wrong with that dash character, so the system cli parser does not recognise it

**Comment by automationpss** [comment]
it cannot explain that appium –p 4725 --webdriveragent-port 8200 is not working, 
while appium –p 4725 is working

**Comment by automationpss** [comment]
can someone check if main.js working correctly?

**Comment by KazuCocoa** [comment]
I could launch as below.

```
$ appium -p 4725 --webdriveragent-port 8200
[Appium] Welcome to Appium v1.13.0
[Appium] Non-default server args:
[Appium]   port: 4725
[Appium]   wdaLocalPort: 8200
[Appium] Appium REST http interface listener started on 0.0.0.0:4725
```

`–p 4725` you commented on https://github.com/appium/appium/issues/12733#issuecomment-499764090 was wrong. Could you make sure `-` again?

**Comment by automationpss** [comment]
appium -p 4725 --webdriveragent-port 8200 is working now. I should not make copy paste. I should type from command line directly. thanks
