### ISSUE TITLE
<./Scripts/bootstrap.sh -d> got nothing on mac terminal command line

### ISSUE THREAD

**Issue by automationpss** [appium/appium#12730]
## The problem
following instruction on - 
https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/wda-custom-server.md
cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
pss-mbp-13150:WebDriverAgent jwang $ ./Scripts/bootstrap.sh -d
expected result: there are some feedback from above execution.
actual result: nothing happend after one day, looks like command hang there forever.

## Environment 
* Appium version (or git revision) that exhibits the issue: 1.13.0 
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: MacOS 10.14.5 
* Node.js version (unless using Appium.app|exe):  v11.2.0 
* Npm or Yarn package manager:   6.4.1 
* Mobile platform/version under test:  12.2, 12.1.4 
* Real device or emulator/simulator:  iPhone 6, and iPhone 8 
* Appium CLI or Appium.app|exe:  1.13.0 

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by imurchie** [comment]
If you have already run it, nothing will happen.

Try running `rm -rf Carthage` and then running `./Scripts/bootstrap.sh -d`.

**Comment by automationpss** [comment]
it works now. thanks
