### ISSUE TITLE
Error androidTest.apk' is not writeable

### ISSUE THREAD

**Issue by VaibhavRepo** [appium/appium#12742]
appium version: Appium v1.14.0-beta.1
OS: ubuntu 18.04

[Appium] Welcome to Appium v1.14.0-beta.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"appActivity":"com.android.gallery3d.app.GalleryActivity","appPackage":"com.android.gallery3d","platformVersion":"7.0","automationName":"uiautomator2","customFindModules":{"ai":"test-ai-classifier"},"shouldUseCompactResponses":false,"platformName":"Android","deviceName":"Pixel_2_API_24"},"capabilities":{"firstMatch":[{"appium:appActivity":"com.android.gallery3d.app.GalleryActivity","appium:appPackage":"com.android.gallery3d","appium:automationName":"uiautomator2","customFindModules":{"ai":"test-ai-classifier"},"appium:deviceName":"Pixel_2_API_24","platformName":"android","appium:platformVersion":"7.0","shouldUseCompactResponses":false}]}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"appActivity":"com.android.gallery3d.app.GalleryActivity","appPackage":"com.android.gallery3d","platformVersion":"7.0","automationName":"uiautomator2","customFindModules":{"ai":"test-ai-classifier"},"shouldUseCompactResponses":false,"platformName":"Android","deviceName":"Pixel_2_API_24"},null,{"firstMatch":[{"appium:appActivity":"com.android.gallery3d.app.GalleryActivity","appium:appPackage":"com.android.gallery3d","appium:automationName":"uiautomator2","customFindModules":{"ai":"test-ai-classifier"},"appium:deviceName":"Pixel_2_API_24","platformName":"android","appium:platformVersion":"7.0","shouldUseCompactResponses":false}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1560079124024 (16:48:44 GMT+0530 (IST))
[BaseDriver] The capabilities ["customFindModules","shouldUseCompactResponses"] are not standard capabilities and should have an extension prefix
[Appium] Appium v1.14.0-beta.1 creating new AndroidUiautomator2Driver (v1.33.1) session
[Appium] Capabilities:
[Appium]   customFindModules: {
[Appium]     ai: test-ai-classifier
[Appium]   }
[Appium]   platformName: android
[Appium]   shouldUseCompactResponses: false
[Appium]   appActivity: com.android.gallery3d.app.GalleryActivity
[Appium]   appPackage: com.android.gallery3d
[Appium]   automationName: uiautomator2
[Appium]   deviceName: Pixel_2_API_24
[Appium]   platformVersion: 7.0
[debug] [BaseDriver] W3C capabilities {"alwaysMatch":{"appium:cus... and MJSONWP desired capabilities {"appActivity":"com.android... were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"appium:cus...
[BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[BaseDriver]   customFindModules
[BaseDriver]   shouldUseCompactResponses
[BaseDriver] Session created with session id: 8506dca6-47b9-4e2a-a5ce-549332727dc7
[ADB] Found 1 'build-tools' folders under '/home/vaibhav/Android/Sdk' (newest first):
[ADB]     /home/vaibhav/Android/Sdk/build-tools/29.0.0
[ADB] Using 'adb' from '/home/vaibhav/Android/Sdk/platform-tools/adb'
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[AndroidDriver] Looking for a device with Android '7.0'
[debug] [ADB] Setting device id to emulator-5554
[ADB] Getting device platform version
[debug] [ADB] Running '/home/vaibhav/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell getprop ro.build.version.release'
[debug] [ADB] Current device property 'ro.build.version.release': 7.0
[AndroidDriver] Using device: emulator-5554
[ADB] Using 'adb' from '/home/vaibhav/Android/Sdk/platform-tools/adb'
[debug] [ADB] Setting device id to emulator-5554
[debug] [ADB] Running '/home/vaibhav/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk'
[debug] [ADB] Current device property 'ro.build.version.sdk': 24
[debug] [ADB] Device API level: 24
[AndroidDriver] No app sent in, not parsing package/activity
[debug] [ADB] Running '/home/vaibhav/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 wait-for-device'
[debug] [ADB] Running '/home/vaibhav/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell echo ping'
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Getting install status for io.appium.settings
[debug] [ADB] Running '/home/vaibhav/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.settings'
[debug] [ADB] 'io.appium.settings' is installed
[debug] [ADB] Getting package info for 'io.appium.settings'
[debug] [ADB] Running '/home/vaibhav/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.settings'
[ADB] Using 'aapt' from '/home/vaibhav/Android/Sdk/build-tools/29.0.0/aapt'
[debug] [ADB] The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('2.14.0' >= '2.14.0')
[debug] [ADB] There is no need to install/upgrade '/usr/local/lib/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk'
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running '/home/vaibhav/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell 'pgrep --help; echo $?''
[debug] [ADB] Running '/home/vaibhav/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pgrep \^appium\\.settings\$'
[debug] [AndroidDriver] Activating 'io.appium.settings'
[debug] [ADB] Running '/home/vaibhav/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell monkey -p io.appium.settings -c android.intent.category.LAUNCHER 1'
[debug] [AndroidDriver] Command stdout: Events injected: 1
[debug] [AndroidDriver] ## Network stats: elapsed time=18ms (0ms mobile, 0ms wifi, 18ms not connected)
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running '/home/vaibhav/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pgrep \^appium\\.settings\$'
[debug] [ADB] Running '/home/vaibhav/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell appops set io.appium.settings android\:mock_location allow'
[debug] [Logcat] Starting logcat capture
[debug] [ADB] Getting install status for io.appium.uiautomator2.server
[debug] [ADB] Running '/home/vaibhav/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.uiautomator2.server'
[debug] [ADB] 'io.appium.uiautomator2.server' is not installed
[debug] [ADB] App '/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.6.0.apk' is not installed
[debug] [UiAutomator2] io.appium.uiautomator2.server installation state: notInstalled
[debug] [ADB] Checking app cert for /usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.6.0.apk
[ADB] Using 'apksigner' from '/home/vaibhav/Android/Sdk/build-tools/29.0.0/apksigner'
[debug] [ADB] Starting '/home/vaibhav/Android/Sdk/build-tools/29.0.0/apksigner' with args '["verify","--print-certs","/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.6.0.apk"]'
[debug] [ADB] apksigner stdout: Signer #1 certificate DN: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
[debug] [ADB] Signer #1 certificate SHA-256 digest: a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc
[debug] [ADB] Signer #1 certificate SHA-1 digest: 61ed377e85d386a8dfee6b864bd85b0bfaa5af81
[debug] [ADB] Signer #1 certificate MD5 digest: e89b158e4bcf988ebd09eb83f5378e87
[debug] [ADB] 
[debug] [ADB] '/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.6.0.apk' is already signed.
[debug] [ADB] Getting install status for io.appium.uiautomator2.server.test
[debug] [ADB] Running '/home/vaibhav/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.uiautomator2.server.test'
[debug] [ADB] 'io.appium.uiautomator2.server.test' is not installed
[debug] [ADB] Checking app cert for /usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk
[debug] [ADB] Starting '/home/vaibhav/Android/Sdk/build-tools/29.0.0/apksigner' with args '["verify","--print-certs","/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk"]'
[debug] [ADB] apksigner stdout: Signer #1 certificate DN: CN=Android Debug, O=Android, C=US
[debug] [ADB] Signer #1 certificate SHA-256 digest: 3e4f2ab66d641bbbd363421151755f8b12b66ea37a5db43c52116596b7392a8e
[debug] [ADB] Signer #1 certificate SHA-1 digest: e24fc8971c0aad07d1df6cc62af7fb0d48b45b60
[debug] [ADB] Signer #1 certificate MD5 digest: 5623d53469c7f7147b52ace9d09901eb
[debug] [ADB] 
[debug] [ADB] '/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk' is signed with non-default certificate
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[debug] [WD Proxy] Matched '/' to command name 'deleteSession'
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
[debug] [ADB] Running '/home/vaibhav/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop com.android.gallery3d'
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8200 
[debug] [ADB] Running '/home/vaibhav/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp\:8200'
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command '/home/vaibhav/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp\:8200' exited with code 1'; Stderr: 'adb: error: listener 'tcp:8200' not found'; Code: '1''
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1560079127020 (16:48:47 GMT+0530 (IST))
[debug] [W3C] Encountered internal error running command: Error: The application at '/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk' is not writeable. Please grant write permissions to this file or to its parent folder '/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks' for the Appium process, so it could sign the application
[debug] [W3C]     at Object.helpers.signApp (/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/lib/helpers.js:23:11)
[debug] [W3C]     at <anonymous>
[HTTP] <-- POST /wd/hub/session 500 3028 ms - 1265

**Comment by mykola-mokhnach** [comment]
What exactly is unclear with the error message above?

**Comment by VaibhavRepo** [comment]
can you check the error messages, what exactly is creating the problem.

trying to use ai-classifier plugin on linux machine
1- used uiautomator1 before, app launched fine though wasn't able to click via plugin.
2- As suggested used uiautomator2, but now app is not launching.

**Comment by VaibhavRepo** [comment]
@mykola-mokhnach below the code, in which I just to launch the application.
appium: 1.13

`DesiredCapabilities capabilities = new DesiredCapabilities();

        capabilities.setCapability("deviceName", "Pixel_2_API_24");
        capabilities.setCapability("platformVersion", "7.0");
        capabilities.setCapability("platformName", "Android");
        //capabilities.setCapability("automationName", "uiautomator2");
        capabilities.setCapability("appPackage", "com.android.gallery3d");
        capabilities.setCapability("appActivity","com.android.gallery3d.app.GalleryActivity")

        driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
        driver.manage().timeouts().implicitlyWait(80, TimeUnit.SECONDS);
        Thread.sleep(10000);
        driver.quit();`

It works fine, but now if I uncomment the uiAutomator2 capability then I am getting below error, which I am unable to get.

[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"appActivity":"com.android.gallery3d.app.GalleryActivity","appPackage":"com.android.gallery3d","platformVersion":"7.0","automationName":"uiautomator2","platformName":"Android","deviceName":"Pixel_2_API_24"},"capabilities":{"firstMatch":[{"appium:appActivity":"com.android.gallery3d.app.GalleryActivity","appium:appPackage":"com.android.gallery3d","appium:automationName":"uiautomator2","appium:deviceName":"Pixel_2_API_24","platformName":"android","appium:platformVersion":"7.0"}]}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"appActivity":"com.android.gallery3d.app.GalleryActivity","appPackage":"com.android.gallery3d","platformVersion":"7.0","automationName":"uiautomator2","platformName":"Android","deviceName":"Pixel_2_API_24"},null,{"firstMatch":[{"appium:appActivity":"com.android.gallery3d.app.GalleryActivity","appium:appPackage":"com.android.gallery3d","appium:automationName":"uiautomator2","appium:deviceName":"Pixel_2_API_24","platformName":"android","appium:platformVersion":"7.0"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1560231647744 (11:10:47 GMT+0530 (IST))
[Appium] Appium v1.13.0 creating new AndroidUiautomator2Driver (v1.33.1) session
[Appium] Capabilities:
[Appium]   platformName: android
[Appium]   appActivity: com.android.gallery3d.app.GalleryActivity
[Appium]   appPackage: com.android.gallery3d
[Appium]   automationName: uiautomator2
[Appium]   deviceName: Pixel_2_API_24
[Appium]   platformVersion: 7.0
[debug] [BaseDriver] W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP desired capabilities {"appActivity":"com.android... were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"platformNa...
[BaseDriver] Session created with session id: b851e1b6-21a8-4842-a2a2-7bfd8ff22e4c
[ADB] Found 1 'build-tools' folders under '/home/vaibhav/Android/Sdk' (newest first):
[ADB]     /home/vaibhav/Android/Sdk/build-tools/29.0.0
[ADB] Using 'adb' from '/home/vaibhav/Android/Sdk/platform-tools/adb'
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[AndroidDriver] Looking for a device with Android '7.0'
[debug] [ADB] Setting device id to emulator-5554
[ADB] Getting device platform version
[debug] [ADB] Running '/home/vaibhav/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell getprop ro.build.version.release'
[debug] [ADB] Current device property 'ro.build.version.release': 7.0
[AndroidDriver] Using device: emulator-5554
[ADB] Using 'adb' from '/home/vaibhav/Android/Sdk/platform-tools/adb'
[debug] [ADB] Setting device id to emulator-5554
[debug] [ADB] Running '/home/vaibhav/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk'
[debug] [ADB] Current device property 'ro.build.version.sdk': 24
[debug] [ADB] Device API level: 24
[AndroidDriver] No app sent in, not parsing package/activity
[debug] [ADB] Running '/home/vaibhav/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 wait-for-device'
[debug] [ADB] Running '/home/vaibhav/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell echo ping'
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Getting install status for io.appium.settings
[debug] [ADB] Running '/home/vaibhav/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.settings'
[debug] [ADB] 'io.appium.settings' is installed
[debug] [ADB] Getting package info for 'io.appium.settings'
[debug] [ADB] Running '/home/vaibhav/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.settings'
[ADB] Using 'aapt' from '/home/vaibhav/Android/Sdk/build-tools/29.0.0/aapt'
[debug] [ADB] The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('2.14.0' >= '2.14.0')
[debug] [ADB] There is no need to install/upgrade '/usr/local/lib/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk'
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running '/home/vaibhav/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell 'pgrep --help; echo $?''
[debug] [ADB] Running '/home/vaibhav/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pgrep \^appium\\.settings\$'
[debug] [AndroidDriver] io.appium.settings is already running. There is no need to reset its permissions.
[debug] [ADB] Running '/home/vaibhav/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell appops set io.appium.settings android\:mock_location allow'
[debug] [Logcat] Starting logcat capture
[debug] [ADB] Getting install status for io.appium.uiautomator2.server
[debug] [ADB] Running '/home/vaibhav/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.uiautomator2.server'
[debug] [ADB] 'io.appium.uiautomator2.server' is not installed
[debug] [ADB] App '/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.5.1.apk' is not installed
[debug] [UiAutomator2] io.appium.uiautomator2.server installation state: notInstalled
[debug] [ADB] Checking app cert for /usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.5.1.apk
[ADB] Using 'apksigner' from '/home/vaibhav/Android/Sdk/build-tools/29.0.0/apksigner'
[debug] [ADB] Starting '/home/vaibhav/Android/Sdk/build-tools/29.0.0/apksigner' with args '["verify","--print-certs","/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.5.1.apk"]'
[debug] [ADB] apksigner stdout: Signer #1 certificate DN: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
[debug] [ADB] Signer #1 certificate SHA-256 digest: a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc
[debug] [ADB] Signer #1 certificate SHA-1 digest: 61ed377e85d386a8dfee6b864bd85b0bfaa5af81
[debug] [ADB] Signer #1 certificate MD5 digest: e89b158e4bcf988ebd09eb83f5378e87
[debug] [ADB] 
[debug] [ADB] '/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.5.1.apk' is already signed.
[debug] [ADB] Getting install status for io.appium.uiautomator2.server.test
[debug] [ADB] Running '/home/vaibhav/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.uiautomator2.server.test'
[debug] [ADB] 'io.appium.uiautomator2.server.test' is not installed
[debug] [ADB] Checking app cert for /usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk
[debug] [ADB] Starting '/home/vaibhav/Android/Sdk/build-tools/29.0.0/apksigner' with args '["verify","--print-certs","/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk"]'
[debug] [ADB] apksigner stdout: Signer #1 certificate DN: CN=Android Debug, O=Android, C=US
[debug] [ADB] Signer #1 certificate SHA-256 digest: 3e4f2ab66d641bbbd363421151755f8b12b66ea37a5db43c52116596b7392a8e
[debug] [ADB] Signer #1 certificate SHA-1 digest: e24fc8971c0aad07d1df6cc62af7fb0d48b45b60
[debug] [ADB] Signer #1 certificate MD5 digest: 5623d53469c7f7147b52ace9d09901eb
[debug] [ADB] 
[debug] [ADB] '/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk' is signed with non-default certificate
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[debug] [WD Proxy] Matched '/' to command name 'deleteSession'
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
[debug] [ADB] Running '/home/vaibhav/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop com.android.gallery3d'
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8200 
[debug] [ADB] Running '/home/vaibhav/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp\:8200'
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command '/home/vaibhav/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp\:8200' exited with code 1'; Stderr: 'adb: error: listener 'tcp:8200' not found'; Code: '1''
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1560231648964 (11:10:48 GMT+0530 (IST))
[debug] [W3C] Encountered internal error running command: Error: The application at '/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk' is not writeable. Please grant write permissions to this file or to its parent folder '/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks' for the Appium process, so it could sign the application
[debug] [W3C]     at Object.helpers.signApp (/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/lib/helpers.js:23:11)
[debug] [W3C]     at <anonymous>
[HTTP] <-- POST /wd/hub/session 500 1268 ms - 1265

**Comment by mykola-mokhnach** [comment]
Again the same question: what is the problem to make the file/folder writeable?

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
