### ISSUE TITLE
Appium server hangs while trying to find 'clear all' notifications button on Android 9 while it works fine on earlier versions.

### ISSUE THREAD

**Issue by anurut** [appium/appium#12743]
## The problem

In my test I need to fetch OTP from notifications panel. Before sending the OTP I want to clear all earlier notifications. What I do is: driver.openNotification();  and try to find the 'clear all' button.
At this point the Appium server hangs and I have to hit back button to make it wake up again.
It does not happen on earlier versions of Android only happens on Android 9

I am Using UIAutomator2

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS 10.14.5
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager: 
* Mobile platform/version under test: Android 9 
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: both

## Link to Appium logs

https://gist.github.com/anurut/71d0e9f4ffa1b702a4049eebf8e764da

##Link to ADB Logcat

https://gist.github.com/anurut/581ef0cdb1351b8f53f530f5a0d5b702

## Code To Reproduce Issue [ Good To Have ]
	// Finding Elements
	@HowToUseLocators(androidAutomation = LocatorGroupStrategy.ALL_POSSIBLE)
	@AndroidFindBy(id = Constants.NOTIFICATION_SCREEN_CLEAR_NOTIFICATION_SAMSUNG_1)
	@AndroidFindBy(id = Constants.NOTIFICATION_SCREEN_CLEAR_NOTIFICATION_MI)
	@AndroidFindBy(id = Constants.NOTIFICATION_SCREEN_CLEAR_NOTIFICATION_SAMSUNG)
	@AndroidFindBy(id = Constants.NOTIFICATION_SCREEN_CLEAR_NOTIFICATION)
	private static List<AndroidElement> clearNotif;

	@AndroidFindBy(className = Constants.NOTIFICATION_SCREEN_MESSAGE_TEXT_CLASS)
	private static List<AndroidElement> messageText;
public void clearNotification() throws InterruptedException {
		openNotifications();
	
		try {

			AndroidElement notif = clearNotif.get(0);
			
			System.out.println(notif.toString());
			if (notif.isEnabled()) {
				
				notif.click();
			
			} else if(!notif.isEnabled()) {
				
				clickBackButton();
			}
		} catch (Exception e) {
			System.out.println(e);
			System.out.println("No notifications to clear, going back");
			clickBackButton();
		}
	}

**Comment by mykola-mokhnach** [comment]
What do you mean under `hangs`? Can you please provide more detailed description on what exactly is happening and when? I don't see any suspicious things in the attached logs. Also, the logcat output might be of use.

**Comment by anurut** [comment]
@mykola-mokhnach This is similar to a previous issue here: https://github.com/appium/appium/issues/10430#issue-309262337

But this time it is with UIAutomator2. I'll attach logcat logs in a while and more information soon.

**Comment by mykola-mokhnach** [comment]
Unfortunately I cannot pull anything useful from the log. Most likely this is Google's framework-specific issue and we cannot do much about it on our side.

**Comment by anurut** [comment]
@mykola-mokhnach Thanks for the time. Could you please look into one more factor before closing this.
I tried this again without the `@HowToUseLocators(androidAutomation = LocatorGroupStrategy.ALL_POSSIBLE)` locator strategy.

Could this issue be happening due to this?

Any help is appreciated.

Regards

**Comment by mykola-mokhnach** [comment]
> I tried this again without the @HowToUseLocators(androidAutomation = LocatorGroupStrategy.ALL_POSSIBLE) locator strategy. And it works fine.

I cannot say nothing for sure, since there are no any useful traces in logs. Perhaps, you can figure out more on your own while debugging the actual source.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
