### ISSUE TITLE
Appium server can't load Instagram but Instagram lite works fine

### ISSUE THREAD

**Issue by karan97saxena** [appium/appium#12748]
## The problem

I am trying to test Instagram android application. However, I receive the following error (attached). Also, It runs perfectly fine on Instagram lite.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): V8
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium app

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Attached image.

## Code To Reproduce Issue [ Good To Have ]

Just load Instagram application.

**Comment by karan97saxena** [comment]
![Screenshot (38)](https://user-images.githubusercontent.com/51530387/59190516-8be86b00-8b9a-11e9-9453-11d81645a05c.png)

**Comment by mykola-mokhnach** [comment]
Please provide the full server log
