### ISSUE TITLE
There is a problem after an input makes focus when writing about it.

### ISSUE THREAD

**Issue by jadcode** [appium/appium#12745]
I am trying to login on the website: **https://201.247.172.70/sslvpn/Login/Login**
using the latest versions of appium and chromedriver, my code is as follows:

DesiredCapabilities caps = new DesiredCapabilities ();
caps.setCapability ("deviceName", "My Phone");
caps.setCapability ("udid", "4df1b558054c9fef");
caps.setCapability ("platformName", "Android");
caps.setCapability ("platformVersion", "4.3");
caps.setCapability ("browserName", "Chrome");
caps.setCapability ("noReset", "true");

System.setProperty ("webdriver.chrome.driver", "C: \\ selenium_drivers \\ chromedriver.exe");
try {
driver = new AndroidDriver <MobileElement> (new URL ("http://127.0.0.1:4723/wd/hub"), caps);

} catch (MalformedURLException e) {
System.out.println (e.getMessage ());
}
driver.get ("https://201.247.172.70/sslvpn/Login/Login");
driver.findElement (By.id ("userName")). sendKeys ("user");
driver.findElement (By.id ("passwordDisplayed")). sendKeys ("pass");
**driver.findElement (By.id ("LoginButton")). click ();**

When I click, it responds that it does not exist. But visually, control is observed even though it is focused on the field. Also using the UI Automator Viewer is observed.

Despite this I have tried to use the following alternatives:

Hide the keyboard after entering the text in the pass field
driver.hideKeyboard ();

Clean the spotlights by means of JS
JavascriptExecutor executor3 = (JavascriptExecutor) driver;
executor3.executeScript ("document.activeElement.blur ();");

Change the site zoom to "force" to see the control.
JavascriptExecutor executor2 = (JavascriptExecutor) driver;
executor2.executeScript ("document.body.style.zoom = '50% ';");

Print the code to validate that there is
System.out.println (driver.getPageSource ());
Where the button is observed:
<! - Submit button ->
<tr>
<td id = "LoginButtonTD" align = "right">
<div id = "submitDiv">
<input type = "submit" id = "LoginButton" name = "Login" value = "Sign In" align = "absmiddle" class = "butt" />
</ div>
</ td>
</ tr> <! - submit button ->

Although control exists, it does not take it. You can confirm if it is a current error and what alternative I can implement to be able to perform the login without problems.

Greetings.

**Comment by mykola-mokhnach** [comment]
Please report the problem to chromedriver. Appium is just a proxy between your code and chromedriver in this case, so there's nothing we can do there.
