### ISSUE TITLE
Bundle WinAppDriver v1.1.1 with Appium

### ISSUE THREAD

**Issue by daalfa** [appium/appium#12758]
Upgrade the appium-windows-driver v1.5.1 module to use the latest WinAppDriver v1.1.1.
WAD_VER and WAD_DL_MD5 would need to change.
Actually do we really need to validate the checksum? The users can check the documentation and see the recommended version.

**Comment by mykola-mokhnach** [comment]
WinAppDriver 1.2rc has been merged recently: https://github.com/appium/appium-windows-driver/commit/71a3a3869710455ffbfb3170bfafe7325954fa70
