### ISSUE TITLE
driver.scroll is not a function.

### ISSUE THREAD

**Issue by PHUITesting** [appium/appium#12755]
This function does not work as described in the docs - http://appium.io/docs/en/commands/interactions/touch/scroll/

**Comment by mykola-mokhnach** [comment]
Please provide the full exception stack trace and the code snippet

**Comment by PHUITesting** [comment]
Code straight from the docs:

// webdriver.io example
driver.touchScroll({
  el: element,
  xOffset: 10,
  yOffset: 100
});

// wd example
await driver.scroll(10, 100);

**Comment by PHUITesting** [comment]
I'll see if I can get another stack trace I think I didnt get one to begin with just the error driver.scroll is not a function.

**Comment by mykola-mokhnach** [comment]
webdriver.io and  wd are two different things. They aren't the same

**Comment by Nisthar** [comment]
@mykola-mokhnach wd is not working for me either.
