### ISSUE TITLE
Connect to the wrong Android device.

### ISSUE THREAD

**Issue by DillionApple** [appium/appium#12753]
## The problem

I have two devices: A and B, both with Android 9.0. They are connected to the same host machine.
But when I config my appium script to run on A (set A's uuid and systemPort), the testing will start on B.

## Environment

* Appium version (or git revision) that exhibits the issue:
1.13.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
Windows 10
* Node.js version (unless using Appium.app|exe):
10.16.0
* Npm or Yarn package manager:
npm 6.9.0
* Mobile platform/version under test:
Android
* Real device or emulator/simulator:
Real device
* Appium CLI or Appium.app|exe:
Appium.exe

## Details

As you can see in the log below. The requested UUID is 5dc1e44f, but the "-s" parameter of adb is 281b4b90cc0d7ece, which is changed.

## Link to Appium logs

https://gist.github.com/DillionApple/656b8d47d1882a5e390b8441e57748e8

## Code To Reproduce Issue [ Good To Have ]

No

**Comment by mykola-mokhnach** [comment]
Please use UiAutomator2. UiAutomator1 is obsolete for Android6+

**Comment by DillionApple** [comment]
my `desired_capabilities` config is below:
```
desired_capabilities = {
            'platformName': 'Android',
            'platformVersion': '9',
            'deviceName': 'vivo',
            'uuid': '5dc1e44f',
            'appPackage': APP_PACKAGE,
            'appActivity': APP_ACTIVITY,
            'autoGrantPermissions': True
            'automationName': 'UiAutomator2',
            'systemPort': 8201,
}
```
When added the `'automationName': 'UiAutomator2'`, the issue still exists.

**Comment by mykola-mokhnach** [comment]
How about that?

> [BaseDriver] The following capabilities were provided, but are not recognized by appium: uuid, systemPort.

**Comment by DillionApple** [comment]
Oh, sorry, there is no `uuid`, but `udid`... Thank you for your time!
