### ISSUE TITLE
Appium launches the iOS native app and start from first screen, every time we execute the code. Can I execute the code on currently opened page directly?

### ISSUE THREAD

**Issue by omkara120** [appium/appium#12769]
I write appium tests for iOS native app. When I execute the code, appium launches the app every time so execution starts from login i.e first screen always. While development of tests, I don't need app to start from first screen always. 

Is there any way to prevent appium from launching the app every time, and execution to start from the currently opened screen ?

Note : here I am not asking about how to prevent appium from installing the app every-time, I am aware of capability "no-rest". I am asking about preventing appium from relaunching app every-time in the context of iOS app.

**Comment by mykola-mokhnach** [comment]
There's a nice set of articles on Appium Pro, which also includes some good proposals about setting the initial app state: https://appiumpro.com/editions/19

Please use Appium forum for questions
