### ISSUE TITLE
Domain=com.facebook.WebDriverAgent Code=1 "Keyboard is not present"  when the simulator is hidden

### ISSUE THREAD

**Issue by FirstAM** [appium/appium#12768]
## The problem

When i hide simulators with  caps "isHeadless" i have old error with keyboard - 

`Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "Keyboard is not present" UserInfo={NSLocalizedDescription=Keyboard is not present}`
 
## Environment

* Appium version (or git revision) that exhibits the issue:  1.13.0
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: MacOS 10.14.3
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: IOS 
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe:

## Details

As now, the problem is shown when the connectHardwareKeyboard parameter is enabled on the simulator

Because simulator is hidden i can't manually disable this parameter, and caps "connectHardwareKeyboard" don't work 

When i disable caps "isHeadless" and manually turn off connectHardwareKeyboard parameter, test work fine.

## Link to Appium logs

[appium_logs_5A95DBD5-2F5E-42B6-892C-169FFA2AD875_25.txt](https://github.com/appium/appium/files/3285676/appium_logs_5A95DBD5-2F5E-42B6-892C-169FFA2AD875_25.txt)

**Comment by mykola-mokhnach** [comment]
You can check if https://github.com/appium/WebDriverAgent/pull/172 improves the situation, but in general we cannot do much about it as the stuff is controlled by iOS internals, which we don't have access to.

**Comment by FirstAM** [comment]
Ok, this version solution in WDA #172, Thanks

**Comment by anujgaba** [comment]
This issue still exists in Appium version 1.13.0. Is there any definite solution to this issue?
