### ISSUE TITLE
iOS app crashes after installing

### ISSUE THREAD

**Issue by manifity** [appium/appium#12767]
## The problem

The app launches and then crashes in virtual mobile iOS device. 

## Environment

* Appium version (or git revision) that exhibits the issue: **1.13.0 (1.13.0.20190505.5)**
* Last Appium version that did not exhibit the issue (if applicable): **current version**
* Desktop OS/version used to run Appium: **macOS Mojave 10.14.3 (18D42)**
* Node.js version (unless using Appium.app|exe): **node - v11.11.0**
* Npm or Yarn package manager: **npm - 6.9.0, yarn - 1.15.2**
* Mobile platform/version under test: **iOS**
* Real device or emulator/simulator: **iPhone 6**
* Appium CLI or Appium.app|exe: **-**

## Details

When I start my auto test or start session in Appium, I see installed/reinstalled my app and web-driver-agent. My app is launching and next it crashes immediately. I use the same desired capabilities but my app isn't worked. For the understanding, the same build is working in real and virtual devices, but not working in Appium.

## Link to Appium logs

https://gist.github.com/manifity/2a41f3bad8c1fb2981632ee154546de5

**Comment by mykola-mokhnach** [comment]
> [warn] [35m[XCUITest][39m Simulator architecture appears to be unsupported by the '/Users/m.barinov/Library/Developer/Xcode/DerivedData/Weakka-ecbboorfpvarnkbbzjmocoonmwca/Build/Products/Debug-iphoneos/Audio.app' application. Make sure the correct deployment target has been selected for its compilation in Xcode.
> [warn] [35m[XCUITest][39m Don't be surprised if the application fails to launch.


Closed as not an issue
