### ISSUE TITLE
Cannot kill the Simulator UI client.

### ISSUE THREAD

**Issue by FirstAM** [appium/appium#12765]
## The problem

Hi, sometimes i meet a bug when start test in ios simulators , when appium try to kill UI simulator. caps(isHeadless: true)

## Environment

* Appium version (or git revision) that exhibits the issue:1.13.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS 10.14.3 
* Node.js version (unless using Appium.app|exe): Тщ
* Npm or Yarn package manager:
* Mobile platform/version under test: IOS 
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: 

## Details

`An unknown server-side error occurred while processing the command. Original error: Cannot kill the Simulator UI client. Original error: Command 'kill 59800' exited with code 1 `

**Comment by mykola-mokhnach** [comment]
Please provide the full server log. 

Also, is the Simulator UI killed after the command is executed or it is still visible?

**Comment by FirstAM** [comment]
Hi, String 134 was first error

[appium_logs_64EA4F22-D02A-4C71-85F6-B0A2E4940033_39.txt](https://github.com/appium/appium/files/3295965/appium_logs_64EA4F22-D02A-4C71-85F6-B0A2E4940033_39.txt)

**Comment by mykola-mokhnach** [comment]
Can you please verify if https://github.com/appium/appium-ios-simulator/pull/227 works for you? 
https://appiumpro.com/editions/47 has the tutorial on how to run appium from source

**Comment by mykola-mokhnach** [comment]
Any feedback?
