### ISSUE TITLE
Chromedriver is closing when context CHROMIUM to NATIVE_APP for Gmail web app

### ISSUE THREAD

**Issue by testingxpertshyd** [appium/appium#12775]
## The problem

Chromedriver is closing when switch context CHROMIUM to NATIVE_APP for Gmail web app

## Environment

* Appium version: 1.9.0
* Real device platform/version: Moto G(6.0) & Redmi Y1 (7.1.2)
* Chrome: 73
* Chromedriver: 2.46  & 73

Capabilities
 "app": "D:\\**********.apk",
  "platformVersion": "7.1.2",
  "automationName": "Appium",
  "platformName": "Android",
  "deviceName": "Moto G",
  "autoGrantPermissions": true,
  "autoAcceptAlerts": true,
  "noReset": true,
  "appWaitDuration": "30000"
RECREATE_CHROME_DRIVER_SESSIONS, true

**Comment by mykola-mokhnach** [comment]
Please try with the most recent Appium version. Also the full server log is required

**Comment by testingxpertshyd** [comment]
Please find the server Logs below.

[JSONWP Proxy] Got response with status 200: {"sessionId":"1cb6b004df069ff3c22ba3627ab39db6","status":0,"value":{"ELEMENT":"0.45148639403503865-4"}}
[JSONWP Proxy] Replacing sessionId 1cb6b004df069ff3c22ba3627ab39db6 with 79ad073e-c0a1-4660-b0b6-aadf57ad1147
[HTTP] <-- POST /wd/hub/session/79ad073e-c0a1-4660-b0b6-aadf57ad1147/element 200 84 ms - 107
[HTTP] 
[HTTP] --> POST /wd/hub/session/79ad073e-c0a1-4660-b0b6-aadf57ad1147/element/0.45148639403503865-4/click
[HTTP] {"id":"0.45148639403503865-4"}
[MJSONWP (79ad073e)] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Matched '/wd/hub/session/79ad073e-c0a1-4660-b0b6-aadf57ad1147/element/0.45148639403503865-4/click' to command name 'click'
[JSONWP Proxy] Proxying [POST /wd/hub/session/79ad073e-c0a1-4660-b0b6-aadf57ad1147/element/0.45148639403503865-4/click] to [POST http://127.0.0.1:8000/wd/hub/session/1cb6b004df069ff3c22ba3627ab39db6/element/0.45148639403503865-4/click] with body: {"id":"0.45148639403503865-4"}
[JSONWP Proxy] Got response with status 200: {"sessionId":"1cb6b004df069ff3c22ba3627ab39db6","status":0,"value":null}
[JSONWP Proxy] Replacing sessionId 1cb6b004df069ff3c22ba3627ab39db6 with 79ad073e-c0a1-4660-b0b6-aadf57ad1147
[HTTP] <-- POST /wd/hub/session/79ad073e-c0a1-4660-b0b6-aadf57ad1147/element/0.45148639403503865-4/click 200 838 ms - 76
[HTTP] 
[HTTP] --> GET /wd/hub/session/79ad073e-c0a1-4660-b0b6-aadf57ad1147/context
[HTTP] {}
[MJSONWP (79ad073e)] Calling AppiumDriver.getCurrentContext() with args: ["79ad073e-c0a1-4660-b0b6-aadf57ad1147"]
[MJSONWP (79ad073e)] Responding to client with driver.getCurrentContext() result: "CHROMIUM"
[HTTP] <-- GET /wd/hub/session/79ad073e-c0a1-4660-b0b6-aadf57ad1147/context 200 4 ms - 82
[HTTP] 
[HTTP] --> GET /wd/hub/session/79ad073e-c0a1-4660-b0b6-aadf57ad1147/contexts
[HTTP] {}
[MJSONWP (79ad073e)] Calling AppiumDriver.getContexts() with args: ["79ad073e-c0a1-4660-b0b6-aadf57ad1147"]
[AndroidDriver] Available contexts: ["NATIVE_APP","CHROMIUM"]
[MJSONWP (79ad073e)] Responding to client with driver.getContexts() result: ["NATIVE_APP","CHROMIUM"]
[HTTP] <-- GET /wd/hub/session/79ad073e-c0a1-4660-b0b6-aadf57ad1147/contexts 200 2 ms - 97
[HTTP] 
[HTTP] --> POST /wd/hub/session/79ad073e-c0a1-4660-b0b6-aadf57ad1147/context
[HTTP] {"name":"NATIVE_APP"}
[MJSONWP (79ad073e)] Calling AppiumDriver.setContext() with args: ["NATIVE_APP","79ad073e-c0a1-4660-b0b6-aadf57ad1147"]
[AndroidDriver] Available contexts: ["NATIVE_APP","CHROMIUM"]
[AndroidDriver] recreateChromeDriverSessions set to true; killing existing chromedrivers
[AndroidDriver] Stopping chromedriver for context CHROMIUM
[Chromedriver] Changed state to 'stopping'
[JSONWP Proxy] Proxying [DELETE /] to [DELETE http://127.0.0.1:8000/wd/hub/session/1cb6b004df069ff3c22ba3627ab39db6] with no body
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"1cb6b004df069ff3c22ba3627ab39db6\",\"status\":0,\"value\":null}"
[Chromedriver] Changed state to 'stopped'
[MJSONWP (79ad073e)] Responding to client with driver.setContext() result: null
[HTTP] <-- POST /wd/hub/session/79ad073e-c0a1-4660-b0b6-aadf57ad1147/context 200 2335 ms - 76
[HTTP]

**Comment by mykola-mokhnach** [comment]
I don't get what's the problem here. `[AndroidDriver] recreateChromeDriverSessions set to true; killing existing chromedrivers` - isn't the above behaviour expected?
