### ISSUE TITLE
Appium Error while trying to transfer an apk file

### ISSUE THREAD

**Issue by bulbaasd** [appium/appium#12774]
## The problem

I am trying to send an apk file from my pc to an emulated device via apm. I have replaced the adb version to 28 from 29, thinking it might solve the problem.

* Appium version (or git revision) that exhibits the issue: 1.13.0
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Pixel3 API25, android v7.1.1
* Real device or emulator/simulator: Emulator

Here is the error message:
 An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\asubramanian_local\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 shell pm install /data/local/tmp/appium_cache/47fa4a5c563b1bf5bfcf16786ea168e516787345.apk' exited with code 1'; Stderr: 'Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]'; Code: '1'

## Link to Appium logs

[Appium] Welcome to Appium v1.13.0
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/sessions
[HTTP] {}
[GENERIC] Calling AppiumDriver.getSessions() with args: []
[GENERIC] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 7 ms - 40
[HTTP] 
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"C:\\Users\\asubramanian\\Downloads\\ProgHub.apk","deviceName":"Android Emulator","platformName":"Android","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"C:\\Users\\asubramanian\\Downloads\\ProgHub.apk","deviceName":"Android Emulator","platformName":"Android","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1560507899545 (15:54:59 GMT+0530 (India Standard Time))
[Appium] 
[Appium] ======================================================================
[Appium]   DEPRECATION WARNING:
[Appium] 
[Appium]   The 'automationName' capability was not provided in the desired 
[Appium]   capabilities for this Android session
[Appium] 
[Appium]   Setting 'automationName=UiAutomator1' by default and using the 
[Appium]   UiAutomator1 Driver
[Appium] 
[Appium]   The next minor version of Appium (1.14.x) will set 
[Appium]   'automationName=UiAutomator2' by default and use the UiAutomator2 
[Appium]   Driver
[Appium] 
[Appium]   The next major version of Appium (2.x) will **require** the 
[Appium]   'automationName' capability to be set for all sessions on all 
[Appium]   platforms
[Appium] 
[Appium]   If you are happy with 'UiAutomator1' and do not wish to upgrade 
[Appium]   Android drivers, please add 'automationName=UiAutomator1' to your 
[Appium]   desired capabilities
[Appium] 
[Appium]   For more information about drivers, please visit 
[Appium]   http://appium.io/docs/en/about-appium/intro/ and explore the 
[Appium]   'Drivers' menu
[Appium] 
[Appium] ======================================================================
[Appium] 
[Appium] Setting automation to 'UiAutomator1'. 
[Appium] Appium v1.13.0 creating new AndroidDriver (v4.15.1) session
[Appium] Capabilities:
[Appium]   app: C:\Users\asubramanian\Downloads\ProgHub.apk
[Appium]   deviceName: Android Emulator
[Appium]   platformName: Android
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[BaseDriver] Creating session with MJSONWP desired capabilities: {"app":"C:\\Users\\asubrama...
[BaseDriver] The following capabilities were provided, but are not recognized by appium: connectHardwareKeyboard.
[BaseDriver] Session created with session id: 2f2f7b9e-ea9e-4c59-b767-4f03f4bead33
[ADB] Found 1 'build-tools' folders under 'C:\Users\asubramanian_local\AppData\Local\Android\Sdk' (newest first):
[ADB]     C:/Users/asubramanian_local/AppData/Local/Android/Sdk/build-tools/29.0.0
[ADB] Using 'adb.exe' from 'C:\Users\asubramanian_local\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[AndroidDriver] Retrieving device list
[ADB] Trying to find a connected android device
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[AndroidDriver] Using device: emulator-5554
[ADB] Using 'adb.exe' from 'C:\Users\asubramanian_local\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[ADB] Setting device id to emulator-5554
[ADB] Running 'C:\Users\asubramanian_local\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk'
[ADB] Current device property 'ro.build.version.sdk': 25
[ADB] Device API level: 25
[AndroidDriver] Consider setting 'automationName' capability to 'uiautomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.
[BaseDriver] Using local app 'C:\Users\asubramanian\Downloads\ProgHub.apk'
[AndroidDriver] Checking whether app is actually present
[AndroidDriver] Starting Android session
[ADB] Running 'C:\Users\asubramanian_local\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 wait-for-device'
[ADB] Running 'C:\Users\asubramanian_local\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell echo ping'
[AndroidDriver] Pushing settings apk to device...
[ADB] Getting install status for io.appium.settings
[ADB] Running 'C:\Users\asubramanian_local\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys package io.appium.settings'
[ADB] 'io.appium.settings' is installed
[ADB] Getting package info for 'io.appium.settings'
[ADB] Running 'C:\Users\asubramanian_local\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys package io.appium.settings'
[ADB] Using 'aapt.exe' from 'C:\Users\asubramanian_local\AppData\Local\Android\Sdk\build-tools\29.0.0\aapt.exe'
[ADB] The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('2.14.0' >= '2.14.0')
[ADB] There is no need to install/upgrade 'C:\Users\asubramanian\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk'
[ADB] Getting IDs of all 'io.appium.settings' processes
[ADB] Running 'C:\Users\asubramanian_local\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell 'pgrep --help; echo $?''
[ADB] Running 'C:\Users\asubramanian_local\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pgrep \^appium\\.settings\$'
[AndroidDriver] io.appium.settings is already running. There is no need to reset its permissions.
[ADB] Running 'C:\Users\asubramanian_local\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell appops set io.appium.settings android\:mock_location allow'
[Logcat] Starting logcat capture
[ADB] Getting device platform version
[ADB] Running 'C:\Users\asubramanian_local\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.release'
[ADB] Current device property 'ro.build.version.release': 7.1.1
[ADB] Running 'C:\Users\asubramanian_local\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell wm size'
[ADB] Running 'C:\Users\asubramanian_local\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.product.model'
[ADB] Current device property 'ro.product.model': Android SDK built for x86
[ADB] Running 'C:\Users\asubramanian_local\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.product.manufacturer'
[ADB] Current device property 'ro.product.manufacturer': Google
[AndroidDriver] Parsing package and activity from app manifest
[ADB] Using the alternative activity name detection method because of: Could not find 'apkanalyzer.bat' in ["C:\\Users\\asubramanian_local\\AppData\\Local\\Android\\Sdk\\platform-tools\\apkanalyzer.bat","C:\\Users\\asubramanian_local\\AppData\\Local\\Android\\Sdk\\emulator\\apkanalyzer.bat","C:\\Users\\asubramanian_local\\AppData\\Local\\Android\\Sdk\\tools\\apkanalyzer.bat","C:\\Users\\asubramanian_local\\AppData\\Local\\Android\\Sdk\\tools\\bin\\apkanalyzer.bat","C:\\Users\\asubramanian_local\\AppData\\Local\\Android\\Sdk\\build-tools\\29.0.0\\apkanalyzer.bat"]. Do you have Android Build Tools installed at 'C:\Users\asubramanian_local\AppData\Local\Android\Sdk'?
[ADB] Extracting package and launch activity from manifest
[ADB] Package name: 'com.freeit.java'
[ADB] Main activity name: 'com.freeit.java.modules.start.OnBoardingActivity'
[AndroidDriver] Parsed package and activity are: com.freeit.java/com.freeit.java.modules.start.OnBoardingActivity
[ADB] Getting install status for com.freeit.java
[ADB] Running 'C:\Users\asubramanian_local\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys package com.freeit.java'
[ADB] 'com.freeit.java' is not installed
[ADB] Getting install status for com.freeit.java
[ADB] Running 'C:\Users\asubramanian_local\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys package com.freeit.java'
[ADB] 'com.freeit.java' is not installed
[ADB] App 'C:\Users\asubramanian\Downloads\ProgHub.apk' is not installed
[ADB] Installing 'C:\Users\asubramanian\Downloads\ProgHub.apk'
[ADB] Running 'C:\Users\asubramanian_local\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell 'ls -t -1 /data/local/tmp/appium_cache 2>&1 || echo _ERROR_''
[ADB] The count of applications in the cache: 5
[ADB] The application at 'C:\Users\asubramanian\Downloads\ProgHub.apk' is already cached to '/data/local/tmp/appium_cache/47fa4a5c563b1bf5bfcf16786ea168e516787345.apk'
[ADB] Running 'C:\Users\asubramanian_local\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pm install /data/local/tmp/appium_cache/47fa4a5c563b1bf5bfcf16786ea168e516787345.apk'
[AndroidDriver] Shutting down Android driver
[AndroidDriver] Called deleteSession but bootstrap wasn't active
[Logcat] Stopping logcat capture
[ADB] Running 'C:\Users\asubramanian_local\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell am force-stop io.appium.unlock'
[AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[BaseDriver] Event 'newSessionStarted' logged at 1560507903572 (15:55:03 GMT+0530 (India Standard Time))
[MJSONWP] Encountered internal error running command: Error executing adbExec. Original error: 'Command 'C\:\\Users\\asubramanian_local\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 shell pm install /data/local/tmp/appium_cache/47fa4a5c563b1bf5bfcf16786ea168e516787345.apk' exited with code 1'; Stderr: 'Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]'; Code: '1'
[MJSONWP] Error: Command 'C\:\\Users\\asubramanian_local\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 shell pm install /data/local/tmp/appium_cache/47fa4a5c563b1bf5bfcf16786ea168e516787345.apk' exited with code 1
[MJSONWP]     at ChildProcess.proc.on.code (C:\Users\asubramanian\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\teen_process\lib\exec.js:94:19)
[MJSONWP]     at ChildProcess.emit (events.js:182:13)
[MJSONWP]     at maybeClose (internal/child_process.js:961:16)
[MJSONWP]     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
[HTTP] <-- POST /wd/hub/session 500 4031 ms - 537
[HTTP] 
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 4 ms - 57
[HTTP]

**Comment by mykola-mokhnach** [comment]
It must be a problem with your apk rather than Appium-related one: https://stackoverflow.com/questions/24572052/install-failed-no-matching-abis-when-install-apk

**Comment by bulbaasd** [comment]
I tried with most of the apks installed from apkpure. Apps i tried - Amazon, Flipkart. 
I have also tried this code in Android Studio- gradle module. Still doesnt work.
android {
  splits {
    abi {
        enable true
        reset()
        include 'x86', 'armeabi-v7a'
        universalApk true
    }
  }

**Comment by bulbaasd** [comment]
Its most porbably an error with adb, because when i try from the cmd and install using adb : i get the following msg:
Performing Streamed Install
adb: failed to install C:\Users\........\apks\AmazonShopping.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by lathaqa16** [comment]
What is the solution please-  getting same error
