### ISSUE TITLE
Appium1.13.0 Element Location Tool Can't Locate Elements in the Wechat Payment Interface

### ISSUE THREAD

**Issue by hagyao520** [appium/appium#12772]
![image](https://user-images.githubusercontent.com/24785603/59479805-d4e93980-8e90-11e9-8b6c-c45db3ac4a6c.png)
Problem: When calling the Wechat Payment Interface in the applet program, the information of the Payment Interface can not be located by Appium1.13.0 Element Search Tool.

**Comment by mykola-mokhnach** [comment]
Elements must be declared as [accessible](https://developer.android.com/guide/topics/ui/accessibility/index.html) in order to be "visible" by UiAutomator framework. Also, if this is a webview then it makes sense to switch to a corresponding context.

**Comment by hagyao520** [comment]
![image](https://user-images.githubusercontent.com/24785603/59586216-fb1f0b80-9114-11e9-8c7d-37326b670611.png)
Appium tests the whole interface of Weichat App from discovery to applet, unable to get elements, and it is useless to try driver. getPageSource ().

**Comment by mykola-mokhnach** [comment]
This is an application issue which has nothing to do with Appium. The stuff might work better with Espresso driver though, since it is based on the actual views hierarchy.

**Comment by hagyao520** [comment]
Is Appium compatible with Wechat's latest version of widget automation testing?

**Comment by KazuCocoa** [comment]
Not sure.
If the view was webview, WebView of UIA2 or espresso driver's https://github.com/appium/appium/pull/12804 also can help.
http://appium.io/docs/en/drivers/android-espresso/ is _The stuff might work better with Espresso driver though_, btw.
