### ISSUE TITLE
Setting API mjpegScalingFactor doesn't have default value

### ISSUE THREAD

**Issue by takeya0x86** [appium/appium#12771]
## The problem

Setting API `mjpegScalingFactor` doesn't have default value. Returning json object does not contain key `mjpegScalingFactor`.
And I try to set value, get message `Didn't know about setting 'mjpegScalingFactor'. Are you sure you spelled it correctly?` on log.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.14.0-beta.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: masOS Mojave 10.14.5
* Node.js version (unless using Appium.app|exe): v10.15.3
* Npm or Yarn package manager: npm 6.9.0
* Mobile platform/version under test: iOS 12.2
* Real device or emulator/simulator: iOS Simulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/takeya0x86/800b6cd091d36ae4be92a08da644706d#file-gistfile1-txt-L127-L150

## Code To Reproduce Issue [ Good To Have ]

```java
IOSDriver driver = new IOSDriver(...);
driver.getSettings().get("mjpegScalingFactor");
```

**Comment by mykola-mokhnach** [comment]
It seems like the WebDriverAgent binary on your device is out of date. Delete it manually from the device and cleanup Xcode caches. Then make sure it is built from the source bundled with XCUITest driver.

**Comment by takeya0x86** [comment]
I deleted WebDriverAgent from the device and uninstalled and re-install appium server. Then the WebDriverAgent was built from source.

https://gist.github.com/takeya0x86/800b6cd091d36ae4be92a08da644706d#file-gistfile2-txt

But I still get same result.

**Comment by mykola-mokhnach** [comment]
From which source you build it?

**Comment by KazuCocoa** [comment]
The setting works in WDA, but xcuitest-driver shows the error message.
No default settings in the returned value are expected so far, since we do not set the value every time in session creation.

**Comment by KazuCocoa** [comment]
you can set the default value as capability like https://github.com/appium/appium/pull/12776/files
@takeya0x86
