### ISSUE TITLE
Error in setLocation for android

### ISSUE THREAD

**Issue by brunoracosta** [appium/appium#12770]
## The problem

I am trying to use setLocation function on Android emulator, but it throw this error:

> An unknown server-side error occurred while processing the command. Original error: Cannot parse the actual location values from the command output: Broadcasting: Intent { act=io.appium.settings.location cmp=io.appium.settings/.receivers.LocationInfoReceiver }
> Broadcast completed: result=0, data=""
> running
> Error: An unknown server-side error occurred while processing the command.
>     at setGeoLocation([object Object]) - at location([object Object]) - setGeoLocation.js:17:15

## Environment

* Appium version (or git revision) that exhibits the issue: 1.11.0
* Desktop OS/version used to run Appium: MAC OS 10.14.5
* Node.js version: v8.11.1
* Npm or Yarn package manager: npm 
* Mobile platform/version under test: Android Emulator API 23
* Real device or emulator/simulator: Android Emulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

I am using node + typescript + wdio + cucumber for this test

## Code To Reproduce Issue

`
(paramLongitude: number, paramLatitude: number) => {
        if (CommonEnum.ISCELULAR === 0) {
            const loc: GeoLocation = {
                latitude: paramLatitude,
                longitude: paramLongitude,
                altitude: 0
            };
            browser.setGeoLocation(loc);
        }
    }
`

**Comment by mykola-mokhnach** [comment]
Please use the most recent server version. Also the full server log is needed
