### ISSUE TITLE
I'm very angry about the default value of `desired_caps.noReset` is `False`,that made all my chatting data in wechat cleaned when I first time trying this appium......

### ISSUE THREAD

**Issue by fightfa** [appium/appium#12785]
## The problem

Why don't you set the default value of  `desired_caps.noReset` be `True`, in order to avoiding that some new users lost their app's data??
Forgive my poor English.

## Environment

* Appium version (or git revision) that exhibits the issue:1.13.0

## Details
What I used:

> desired_caps = {}
> desired_caps['platformName'] = 'Android'
> desired_caps['platformVersion'] = '8.0.0'
> desired_caps['deviceName'] = 'xxxxxxxxxxxxxxxxxx'
> desired_caps['appPackage'] = 'com.tencent.mm'
> desired_caps['appActivity'] = '.ui.LauncherUI'
> driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
> 

So I didn't know must add:
> desired_caps['noReset']='True'

to avoid reseting the existed data in my installed app.

So tERRible!

**Comment by mykola-mokhnach** [comment]
Sorry, but this is the default behaviour and it is not going to be changed. It is normal and expected that application data is reset for each test by default, so the application under test is always in the same state. Feel free to create your own fork and change this behaviour.
