### ISSUE TITLE
Android app does not load in Appium inspector

### ISSUE THREAD

**Issue by Nishant-Taksande** [appium/appium#12784]
## The problem
Start appium server from ui, open appium inspector, set capabilities - click on start session
Infinite loader is displayed, timeout error is displayed after some time.

## Environment
* Appium version: v1.13.0
* Desktop OS/version used to run Appium: OS X, 10.14.5, Windows 10
* Npm or Yarn package manager: 6.4.1
* Mobile platform/version under test: Red Mi Note5 8.1.0, Asus 9.0
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium app

## Details
I am setting below capabilities in Appium Inspector
{
  "deviceName": "badgya",
  "udid": "46f9f070",
  "platformName": "Android",
  "platformVersion": "8.1.0",
  "appPackage": "info.guardianproject.keanuapp",
  "appActivity": "info.guardianproject.keanuapp.MainActivity",
  "noReset": true,
  "adbExecTimeout": 50000,
  "automationName": "UIAutomator2"
}

## Link to Appium logs
https://gist.github.com/Nishant-Taksande/351ec2f9638b6f343a53e266c7e24f5e

## Code To Reproduce Issue [ Good To Have ]
No code, issue is related to appium inspector
**Steps To Reproduce:**
1. Open Appium desktop app
2. Start the sever
3. Open Appium inspector
4. Set capabilities as mentioned above
5. Click on Start Session

**Actual Result:**
Infinite loader is displayed
App is launched successfully in mobile
Appium inspector still shows loader
After some time time out error message is displayed

An unknown server-side error occurred while processing the command. 
Original error: Cannot start the 'info.guardianproject.keanuapp' application. 
Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md 
for troubleshooting. 
Original error: Error executing adbExec. 
Original error: 'Command '/Users/nishanttaksande/Library/Android/sdk/platform-tools/adb -P 5037 -s 46f9f070 shell am start -W -n info.guardianproject.keanuapp/info.guardianproject.keanuapp.MainActivity -S' timed out after 20000ms'. 
Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability

Also tried increasing the timeout till 100000ms

**Comment by mykola-mokhnach** [comment]
Did you try to follow the above troubleshooting document? Does the activity start if executed manually?
