### ISSUE TITLE
appium inspector doesn't catch/recognize custom html properties

### ISSUE THREAD

**Issue by alontrabolski** [appium/appium#12788]
## The problem
appium inspector doesn't catch/recognize custom html properties

## Environment
* appium version: appium desktop. v1.9.0
* Desktop OS/version used to run appium: Windows 10
* Node.js version : v10.15.3
* PlatformVersion under test: 9
* Real device: Samsung S9

## Details

I'm testing my hybrid app on a physical Android device (Samsung S9).
In my tests I need to know when the app is loaded. So one of our app developers added attribute called "initializationstatus" to the app container div.
In my test I'm trying to do this:
WebElement mainContainer = driver.findElement(By.xpath("main container xpath")); // this line works as expected. I'm succeeded to catch the element.
String appLoadingStatus = mainContainer.getAttribute("initializationstatus"); // this line throws exception: Method threw 'org.openqa.selenium.UnsupportedCommandException' exception.
Note that other attributes works as expected for example: mainContainer.getAttribute("selected") return the right value
What is the problem here ?

## Link to Appium logs

https://gist.github.com/alontrabolski/54332f1657d35ffa63453f02cdbcb215

**Comment by mykola-mokhnach** [comment]
The code works as expected. We can only get the attributes which are available to Android accessibility. Try switching to web view context.
