### ISSUE TITLE
Appium failed to respond after opening the native iOS app

### ISSUE THREAD

**Issue by srajkamal84** [appium/appium#12797]
After launching the application, It is not finding the elements and giving an error. WDA installed through code and also application launched after that no reponse, then its not navigating to next line of code and after that im getting the below error

[Xcode] 2019-06-19 14:58:55.305443+0530 WebDriverAgentRunner-Runner[459:53698] Enqueue Failure: Failure to determine system application: Error Domain=com.apple.dt.XCTest.XCTFuture Code=1000 "Timeout waiting for fulfillment of promise for 'Fetching attributes 'XC_kAXXCAttributeSystemAppApplication' for Device system-wide element'." UserInfo={NSLocalizedDescription=Timeout waiting for fulfillment of promise for 'Fetching attributes 'XC_kAXXCAttributeSystemAppApplication' for Device system-wide element'.} /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode] 
[Xcode] 2019-06-19 14:58:55.306230+0530 WebDriverAgentRunner-Runner[459:53698] Enqueue Failure: Failure to determine system application: (null) /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode] 
[Xcode] 2019-06-19 15:00:00.317100+0530 WebDriverAgentRunner-Runner[459:53698] Enqueue Failure: Failure getting list of active applications: Error Domain=com.apple.dt.XCTest.XCTFuture Code=1000 "Timeout waiting for fulfillment of promise for 'Fetching attributes 'XC_kAXXCAttributeFocusedApplications' for (null)'." UserInfo={NSLocalizedDescription=Timeout waiting for fulfillment of promise for 'Fetching attributes 'XC_kAXXCAttributeFocusedApplications' for (null)'.} /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode] 
[Xcode] 2019-06-19 15:00:00.318433+0530 WebDriverAgentRunner-Runner[459:53698] Enqueue Failure: Failure getting list of active applications: (null) /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode] 
[WD Proxy] Got an unexpected response: {"code":"ESOCKETTIMEDOUT","connect":false}
[debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT). Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1560936639172 (15:00:39 GMT+0530 (India Standard Time))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"22J88L6NGX.banca.sella.it","arguments":["-AppleLanguages","(en)","-NSLanguages","(en)"],"environment":{},"eventloopIdleDelaySec":3,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[Xcode] 2019-06-19 15:01:05.427959+0530 WebDriverAgentRunner-Runner[459:53698] Enqueue Failure: Failure to determine system application: Error Domain=com.apple.dt.XCTest.XCTFuture Code=1000 "Timeout waiting for fulfillment of promise for 'Fetching attributes 'XC_kAXXCAttributeSystemAppApplication' for Device system-wide element'." UserInfo={NSLocalizedDescription=Timeout waiting for fulfillment of promise for 'Fetching attributes 'XC_kAXXCAttributeSystemAppApplication' for Device system-wide element'.} /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode] 
[Xcode] 2019-06-19 15:01:05.429043+0530 WebDriverAgentRunner-Runner[459:53698] Enqueue Failure: Failure to determine system application: (null) /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode] 
[Xcode] 2019-06-19 15:02:10.439283+0530 WebDriverAgentRunner-Runner[459:53698] Enqueue Failure: Failure getting list of active applications: Error Domain=com.apple.dt.XCTest.XCTFuture Code=1000 "Timeout waiting for fulfillment of promise for 'Fetching attributes 'XC_kAXXCAttributeFocusedApplications' for (null)'." UserInfo={NSLocalizedDescription=Timeout waiting for fulfillment of promise for 'Fetching attributes 'XC_kAXXCAttributeFocusedApplications' for (null)'.} /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode] 
[Xcode] 2019-06-19 15:02:10.440784+0530 WebDriverAgentRunner-Runner[459:53698] Enqueue Failure: Failure getting list of active applications: (null) /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode] 
[Xcode]     t =   332.52s Unable to monitor event loop
[Xcode] 
[Xcode]     t =   332.52s Open 22J88L6NGX.banca.sella.it
[Xcode] 
[Xcode]     t =   332.53s     Launch 22J88L6NGX.banca.sella.it
[Xcode] 
[Xcode]     t =   332.53s         Terminate 22J88L6NGX.banca.sella.it:467
-----------------------------------------------------------------------
IOS capabilities
Property File
-------------

language=Helpers.userProperties.getProperty("language");
    	screenshot_directory = Helpers.userProperties.getProperty("screenshot_directory");
    	String app_name=Helpers.userProperties.getProperty("app.name");
    	String app_path=Helpers.userProperties.getProperty("app.path");
    	String appium_version=Helpers.userProperties.getProperty("appium.version");
    	String ios_version=Helpers.userProperties.getProperty("ios.version");
    	String device_name=Helpers.userProperties.getProperty("device.name");
    	int command_timeout=Integer.parseInt(Helpers.userProperties.getProperty("command.timeout"));
    	String automation_name=Helpers.userProperties.getProperty("automation.name");
    	String udid=Helpers.userProperties.getProperty("udid");
    	String xcode_configfile=Helpers.userProperties.getProperty("xcode.configfile.path");
    	String appium_server_host=Helpers.userProperties.getProperty("appium.server.host");
    	boolean no_reset="true".equalsIgnoreCase(Helpers.userProperties.getProperty("app_no_reset"))?true:false;
    	String realDeviceLogger_path=Helpers.userProperties.getProperty("realDeviceLogger.path");
    	String localApp = "/Build/appSella.ipa";
    	File app = new File(app_path);
    	DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(MobileCapabilityType.APPIUM_VERSION, appium_version);
        capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, ios_version);
        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, device_name);
        capabilities.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
        capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, command_timeout);
        capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, automation_name);
        capabilities.setCapability(MobileCapabilityType.FULL_RESET, false);
        capabilities.setCapability(MobileCapabilityType.NO_RESET, no_reset);
        capabilities.setCapability(MobileCapabilityType.UDID, udid);
        capabilities.setCapability("updatedWDABundleId", "22J88L6NGX.banca.sella.it");
        capabilities.setCapability("xcodeConfigFile",xcode_configfile);
        capabilities.setCapability("realDeviceLogger", realDeviceLogger_path);
        capabilities.setCapability("startIWDP", true);
        capabilities.setCapability("wdaLocalPort", "8100");
        capabilities.setCapability("waitForQuietness","false");
        capabilities.setCapability("wdaEventloopIdleDelay", 3);
        capabilities.setCapability("useNewWDA", false);
        capabilities.setCapability("wdaLaunchTimeout",240000);
        capabilities.setCapability("wdaConnectionTimeout",240000);

**Comment by srajkamal84** [comment]
Property Details
#============================iPhone XS================================
language=en
app.name=/Build/appSella.ipa
app.path=./Build/appSella.ipa
appium.version=1.13.0
ios.version=12.0
device.model=iPhone Xs
device.name=BSECHENNAI's iPhone
command.timeout=500
automation.name=XCUITest
udid=00008020-001A78EE02D8002E
xcode.configfile.path=/Users/bsechennai/Documents/workspace/appium-mobile-automation_ios/myconfig.xconfig
appium.server.host=http://127.0.0.1:4723/wd/hub
#appium.server.host=http://0.0.0.0:4723/wd/hub
#appium.server.host=http://localhost:4723/wd/hub
app_no_reset=true
#screenshot_directory=/Users/hpeaimia/Documents/Appium_Mobile_automatio/appium-mobile-automation_ios/Mobile_screenshot
screenshot_directory=./OctRelease
common.date.format=MMM d, yyyy

**Comment by jamesvanhorn** [comment]
We get this all the time. It stinks. No clue on a fix.

**Comment by mykola-mokhnach** [comment]
> Unable to monitor event loop

I assume this an XCTest problem, so it cannot retrieve the accessibility information. I don't think there's much we can do on appium side about it. Try to experiment with `wdaEventloopIdleDelay` and `waitForQuiescence` caps, otherwise I don't have any good solutions.

**Comment by jamesvanhorn** [comment]
Yeah, `waitForQuiescence` set to false helps this a little bit (though you pay a larger cost in startup time between app launch and code execution continuing, sometimes 1+ minutes) . Will try and increase `wdaEventloopIdleDelay` as well and see how that does.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by viccky88** [comment]
@srajkamal84 You can use set “commandTimeouts” desired capability to increase the command response timeout. I was facing the same issue and resolved it by setting the aforementioned desired capability.

**Comment by mohamed8681** [comment]
can any one help i faced this issue now >> i can not open app when i use capability .app but when i use bundle id >> it works  

cap.setCapability("waitForQuietness", false);
				cap.setCapability("waitForQuiescence", false);
				cap.setCapability("wdaEventloopIdleDelay", 7);
				cap.setCapability("eventLoopIdleDelaySec", 4);
				cap.setCapability("startIWDP", true);

				cap.setCapability("wdaLaunchTimeout",240000);
				cap.setCapability("wdaConnectionTimeout",240000);
