### ISSUE TITLE
Appium throws exception when using xpath from context of another element

### ISSUE THREAD

**Issue by LoveleenSaini** [appium/appium#12806]
## The problem

Appium throws exception  _An element could not be located on the page using the given search parameters._  when xpath is used from context of another element even when the element is present on screen.

## Environment

* Appium version: 1.10.0
* Desktop OS/version used to run Appium: macOS High Sierra - version 10.13.6
* Node.js version: 8.9.4
* Mobile platform/version under test: iOS - 12.0 / Android - 9.0
* Android emulator / iOS simulator
* Appium CLI

## Link to Appium logs

https://gist.github.com/LoveleenSaini/6c55886f82244fd7036adcb8dab07315

## Code To Reproduce Issue

```
MobileElement item = RunCukesTest.driver.findElement(By.id("itemName"));

MobileElement button = item.findElement(By.xpath(".//following::*[1]"));
or
MobileElement button = item.findElement(By.xpath(".//parent::*"));
or
MobileElement button = item.findElement(By.xpath(".//following-sibling::*[1]"));
```

**Comment by mykola-mokhnach** [comment]
I don't find these xpath expressions correct.

**Comment by LoveleenSaini** [comment]
I am 100% sure these locators work fine when not used from context of another element.

Like this:
driver.findElement(By.xpath("//*[@name='xyz']//following::[1]"));

driver.findElement(By.xpath("//*[@name='xyz']//parent::*"));

driver.findElement(By.xpath("//*[@name='xyz']//following-sibling::*[1]"));

driver.findElement(By.xpath("//*[@name='xyz']/..//[@name='abc']"));

I think problem happens when searching from context of another element using xpath axes or trying to go to its parent.

**Comment by LoveleenSaini** [comment]
I just realised the asterisks (*) in the locators were not showing because they got translated as markups. I have put a white space before them in description and it looks fine now.

**Comment by mykola-mokhnach** [comment]
I'm still not quite sure about axes names should be separated from the target node by double slash. None of the examples have such format.

**Comment by LoveleenSaini** [comment]
Before logging this bug I did try with single slashes too but the result was same error.

**Comment by mykola-mokhnach** [comment]
I think I know what the issue might be. Let say you have an xml

```xml
<book>
  <title>Cool book</title>
</book>
```

if we match the `title` element like `//title` then the xpath parser would only select elements inside the `title` hierarchy (children and descendants, which we have none in our example). The parent and siblings nodes are not going to be included. This is the reason why neither `parent` not `sibling` axes work - they simply don't exist for the given root.

This means you should either execute this kinds of lookup in the `full` tree or broaden the search criteria, so the resulting tree includes parent/sibling elements of the target node.

**Comment by LoveleenSaini** [comment]
You are right! 
I just tried this on one of the pages of our app:

```
MobileElement item = driver.findElement(By.xpath("//*[@text='abc']"));
List<MobileElement> allElementsFromItem = item.findElements(By.xpath(".//*"));
```
and `allElementsFromItem` list only had children and grandchildren of `item`.

Thanks for the clarification.
