### ISSUE TITLE
Can't open iOS app on a simulator

### ISSUE THREAD

**Issue by brunocuratio** [appium/appium#12802]
## The problem

I'm trying to run Appium inspector, but after the app is installed it can't open. It keeps flashing.
It only happens with iOS. With Android, it works fine.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13.0
* Desktop OS/version used to run Appium: Mac High Sierra - 10.13.6
* Mobile platform/version under test: 12.1
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium.app

## Details
Capabilities
{
  "platformName": "iOS",
  "platformVersion": "12.1",
  "deviceName": "iPhone 6s (12.1)",
  "automationName": "XCUITest",
  "noReset": true,
  "app": "/Users/curatio/IdeaProjects/ui_tests/ipa/Curatio.app",
  "udid": "AEF65DF5-CFDE-4667-9DA9-9206A2971E01",
  "waitForQuiescence": false,
  "showIOSLog": true
}

## Link to Appium logs

https://gist.github.com/brunocuratio/c60228652e4e86167f1b4b2bd769b794

**Comment by imurchie** [comment]
Perhaps lines 53-56 of your logs (https://gist.github.com/brunocuratio/c60228652e4e86167f1b4b2bd769b794#file-appium_log_error-L53-L56) are helpful?
```
[warn] [35m[XCUITest][39m *********************************
[warn] [35m[XCUITest][39m Simulator architecture appears to be unsupported by the '/var/folders/s3/ff6krr157v7g45sl5ysfqrs40000gq/T/2019519-19146-5h83yp.c3gxc/ThaliMe.app' application. Make sure the correct deployment target has been selected for its compilation in Xcode.
[warn] [35m[XCUITest][39m Don't be surprised if the application fails to launch.
[warn] [35m[XCUITest][39m *********************************
```
