### ISSUE TITLE
Can't get any occurrences for comparison with openCV  OccurrenceMatchingResult

### ISSUE THREAD

**Issue by arhanechka** [appium/appium#12809]
I'm trying to implement a search of coordinates of partial image in full image from screenshot.  But the problem is I can't find any occurrences when I try to use the partial screenshot I get the error: Cannot find any occurences of the partial image in the full image
When I try to make 2 screenshots from the screen in real time and compare them, the result is ok, but often during taking the screenshot, I get 
Could not proxy command to remote server. Original error: Error: socket hang up

I need to find coordinates of little part of the screen. How can I do it?
java code
     byte[] screenshot = Base64.encodeBase64(driver.getScreenshotAs(OutputType.BYTES));
       BufferedImage bImage = null;
        try {
            bImage = ImageIO.read(new File("assets/images/full.png"));
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        ImageIO.write(bImage, "png", bos );
        partialImage = bos.toByteArray();
             } catch (IOException e) {
                  e.printStackTrace();
        }
        OccurrenceMatchingResult result = driver
                .findImageOccurrence(screenshot, partialImage, new OccurrenceMatchingOptions()
                        .withEnabledVisualization());
        Rectangle rectangle = result.getRect();

**Comment by mykola-mokhnach** [comment]
Please properly fill out the issue reporting form along with the server logs

**Comment by mykola-mokhnach** [comment]
Btw, you can also try to experiment with [threshold](https://github.com/appium/java-client/pull/1060) parameter. This one has only been added recently to the java client

**Comment by KazuCocoa** [comment]
Make sure the partial screenshot has the same DPI as well.
I met a case that a cropped image had twice DPI than the original one and never matching happened.
(In addition to the above comment)

**Comment by arhanechka** [comment]
Thank you. The problem solved with threshold parameter.
