### ISSUE TITLE
UiAutomator exited unexpectedly with code 255, signal null

### ISSUE THREAD

**Issue by chumincc** [appium/appium#12816]
## Environment

* Appium：1.13.0
* Real device 

## Details

There is a AndroidBootstrap.jar in  the /data/local/tmp.
No idea with why java.lang.StackOverflowError in the log
If I annotate the **time.sleep(3)** , the test goes fine

## Link to Appium logs

[HTTP] <-- POST /wd/hub/session 200 11810 ms - 896
[HTTP] 
[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_RESULT: shortMsg=java.lang.StackOverflowError
[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_RESULT: longMsg=stack size 1038KB
[AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_CODE: 0
[UiAutomator] UiAutomator exited unexpectedly with code 255, signal null
[UiAutomator] Moving to state 'stopped'
[AndroidDriver] Shutting down Android driver
[Appium] Closing session, cause was 'UiAUtomator shut down unexpectedly'
[Appium] Removing session 310b0a37-a1fe-478c-9764-d6c0e951ecd6 from our master session list
[ADB] Running 'D:\Program Files\android-sdk\sdk\platform-tools\adb.exe -P 5037 -s P1V630KOALE008460 shell am force-stop com.tencent.mtt'
[ADB] Pressing the HOME button

## Code To Reproduce Issue [ Good To Have ]

![image](https://user-images.githubusercontent.com/52067240/59990435-b4ca2f00-9675-11e9-9c0c-81ce4ca98d2b.png)

**Comment by mykola-mokhnach** [comment]
UiAutomator1 is considered obsolete and is not supported for Android 6+

Please fill out all the requested issue details.
