### ISSUE TITLE
Unable to install appium settings one on device with Android 9.0

### ISSUE THREAD

**Issue by artemmorshchak** [appium/appium#12817]
## The problem

Unable to launch tests on real device, because of appium error on attempt to install appium settings 

## Environment

* Appium version - 1.13.0
* Last Appium version that did not exhibit the issue : haven't tried other devices before
* Desktop OS/version used to run Appium: MacOS  10.14.5 Mojave
* Node.js version: 10.12.0
* Npm: 6.4.1
* Mobile platform/version under test: android 9 PKQ1
* Real device or emulator/simulator: Pocophone F1
* Appium CLI or Appium.app|exe: Appium CLI

## Details
I'm using webdriver.io + appium for UI tests of webapplication on real devices.
I already use 2 samsung devices (S5 with android 6 and S7 with android 7) And haven't encountered any issues with them.  Now i'm trying to add pocophone with android 9 installed. And tests fail because they are unable to install appium settings app. I checked and all permissions are enabled on device.

## Link to Appium logs

https://gist.github.com/artemmorshchak/fd05922ab1e4b2ec499d0e67e4bbb0f2

**Comment by KazuCocoa** [comment]
I assume this is because the settings app cannot install with `-g` option because of the device restriction or you used old android tools...
(I have an Android 9 phone. It works expectedly)

What about trying another Android 9 device?
What about installing it after updating your android tools version?

---

btw, you can set automationName as uiautomator2

> [AndroidDriver] Consider setting 'automationName' capability to 'uiautomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.

**Comment by mykola-mokhnach** [comment]
I was observing some Chinese phones does not properly handle `-g` option. Make sure the Android SDK is up to date first. If this still does not work with updated SDK then there is nothing we can do more - you must contact the phone manufacturer to fix the bug on their side.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by shantanuchandalia** [comment]
You can do that by enabling "USB Debugging (Security Settings)" in Developer Options.
