### ISSUE TITLE
Feature Suggestion: behavior of chromedriverExecutableDir and chromedriverChromeMappingFile on chromedriver 73 or later

### ISSUE THREAD

**Issue by masakazu-k** [appium/appium#12819]
## The problem

I have suggestions for the specifications of chromedriverExecutableDir and chromedriverChromeMappingFile.

### Background
Google has changed the specs on the versions of chrome that chromedriver supports.

see: http://chromedriver.chromium.org/downloads/version-selection

The chromedriverChromeMappingFile was very useful as it used to support multiple major chrome versions before, but now it's a bit inconvenient.
Currently, if I want to test multiple major versions of chrome, I need to write a set of all major versions to chromedriverChromeMappingFile.

It seems that the specification of chromedriverChromeMappingFile does not match the 73 or later chromedriver.

Therefore, I propose the following specification changes.

## Details

Determine minmum chrome version according to the following conditions.

* The chromedriver that matches the version written in chromedriverChromeMappingFile (or the CHROMEDRIVER_CHROME_MAPPING list) uses its minmum chrome version.
* A mismatched  chromedriver that is version 73 or higher determines the minmum chrome version from the ```chromedriver --version``` output.
* Minmum chrome version other than above is "Unknown".

This way, you can use it simply by adding a new chromedriver to chromedriverExecutableDir.
## Code To Reproduce Issue [Good To Have]

My source is [here](https://github.com/masakazu-k/appium-chromedriver/commit/7128f59bd7b58e727cfeaa7bcda7b6875e65d995).

thanks.

**Comment by mykola-mokhnach** [comment]
We have recently added automated chromedrivers download feature: https://github.com/appium/appium-chromedriver/pull/131
https://github.com/appium/appium-android-driver/pull/548

You can provide the `chromedriver_autodownload` feature flag in order to enable it. Please try it in appium@beta and share your feedback
