### ISSUE TITLE
Appium and Xamarin Forms 4.0 UI Elements Issue (iOS)

### ISSUE THREAD

**Issue by noah-mckenzie** [appium/appium#12818]
## The problem

I am experiencing a issue with the UI in my application while using the Inspector in Appium after transitioning from Xamarin Forms 3.6 to Xamarin Forms 4.0. I am experiencing an issue with the UI elements from the login screen being carried over too the next UI screen after logging in. I also cannot access the UI elements after the login screen UI, the UI elements cannot be found. I would like to know if anyone else has experienced this issue or if there will be support for Xamarin Forms 4.0 in the future. 

## Environment

* Appium version (or git revision) that exhibits the issue: v1.13.0 and v1.14.0-beta.1
* Last Appium version that did not exhibit the issue (if applicable): v1.13.0 and v1.14.0-beta.1
* Desktop OS/version used to run Appium: MacOS Sierra 10.12
* Npm or Yarn package manager: npm 6.9.0
* Mobile platform/version under test: iPad Air iOS 12.2
* Real device or emulator/simulator: XCode Simulator
* Appium CLI or Appium.app|exe: Appium.app

## Details

[Appium&XamarinForms.docx](https://github.com/appium/appium/files/3322200/Appium.XamarinForms.docx)

Xamarin Forms 3.6: Allows logging in and is able to locate elements on the login screen. Able to locate elements after the login screen during the inspector session.

Xamarin Forms 4.0: Allows logging in and is able to locate elements on the login screen. Unable to locate elements after the login screen during the inspector session. The login screen UI elements are accessible during the inspector session after login but do nothing when clicked or sent keys.

I am able to use the application in the simulator properly, the inspector session is the issue I am having as well as writing tests to locate certain elements after logging in. 

## Link to Appium logs

Logs available upon request, not sure if they should be included due to the nature of the issue. 

## Code To Reproduce Issue [ Good To Have ]

Appium Inspector problems with Xamarin Forms and Application UI Elements. No real code to reproduce the issue. Just a perceived issue between Appium Inspector and Xamarin Forms 4.0.

If there is anything else I can provide to help, please let me know. Thank you in advance!

**Comment by KazuCocoa** [comment]
I'm not familiar with Xmarin, but if their new UI component does not follow XCUIElement, Appium cannot detect them.
For example, can the view debug via https://developer.apple.com/library/archive/documentation/ToolsLanguages/Conceptual/Xcode_Overview/ExaminingtheViewHierarchy.html ?

**Comment by noah-mckenzie** [comment]
The application is developed in Visual Studio and cant be run in Xcode. The application can be run on the Xcode simulator though. I was able to use Xcode Accessibility Inspector, but achieved the same results as mentioned with Appium Inspector and the "carry-over" UI elements.

**Comment by mykola-mokhnach** [comment]
> I was able to use Xcode Accessibility Inspector, but achieved the same results as mentioned with Appium Inspector and the "carry-over" UI elements.

If the Accessibility inspector cannot read elements then Appium won't be able to do this as well. I'd try to check Xamarin guide on accessible controls development.

**Comment by noah-mckenzie** [comment]
Development of the application and the accessibility controls has not changed since the problems have occured. The application tests work with Xamarin.Forms 3.6 and the elemetns are able to be located properly but after updating to Xamarin.Forms 4.0 problems with UI elements have occurred. The only thing that changed between the tests working and not working was the update to Xamarin.Forms 4.0, I am not expecting that the current version of Appium works with the new version of Xamarin.Forms 4.0, I wanted to make the Appium team aware of a compatibility issue that seems to be present with Xamarin.Forms 4.0 to see if there is something that needs to be changed to work with Xamarin.Forms 4.0

**Comment by mykola-mokhnach** [comment]
I have doubts we ever checked the compatibility between Appium and Xamarin apps. I'm happy, that it worked before, but in general we don't have any resources dedicated to this topic.

**Comment by noah-mckenzie** [comment]
Alright, thank you for your help! I will be sure to bring up the compatibility issue with Xamarin. Is there any other places you would suggest taking a look into for a possible cause of the issue?

**Comment by KazuCocoa** [comment]
What about the result of `@driver.execute_script 'mobile: source', { format: :description }`, which is Ruby syntax tho, for the frame 3.6 and 4.0?
https://github.com/appium/appium/pull/9338/files

The result is debugDescription of XCTest.
We can probably make sure if the element can appear in it (XCTest can detect it) or not, at least.

**Comment by noah-mckenzie** [comment]
How/Where would I run "@driver.execute_script 'mobile: source', { format: :description }" to view the result? Would I run something similar to the usage case in the link you provided? I just want to clarify how to perform the action you are suggesting so I get proper results. Thanks for responding again!

**Comment by KazuCocoa** [comment]
Which client do you use? If it is dotnet, maybe below works

```
driver.ExecuteScript("mobile: source", new Dictionary<string, string> { { "format", "description" } });
```
the mobile command is => http://appium.io/docs/en/commands/mobile-command/
(but this feature is kind of debugging purpose. XML fromat is used by defaultt. JSON is used by useJSONSource capabilities.

**Comment by noah-mckenzie** [comment]
Alright, I will be sure to try and run that and get back to you as soon as possible. Would you like for me to comment the results exactly or rather just a sentence stating the results of the operation?

**Comment by KazuCocoa** [comment]
If you could not find any differences, no the result is fine.
Sharing the result (where you can do or conceal sensitive data for you) with a Gist is helpful if you could find something strange.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
