### ISSUE TITLE
Is there the way to get access to the elements which are displayed as a one-piece view in the uautomatorviewer?

### ISSUE THREAD

**Issue by arhanechka** [appium/appium#12822]
I have a gridview with calendar which is displayed in uautomatorviewer as an one-piece element. I need to get information from different dates and tap on them with different cases. Is it an alternative way to get access for such type of elements? Another way of testing?

**Comment by mykola-mokhnach** [comment]
Perhaps not with uiautomator-based frameworks (unless the target application's source code is modified). You can try Espresso though.

Please use Appium forum to ask questions.
