### ISSUE TITLE
ProtocolError occurs while executing command find_elements

### ISSUE THREAD

**Issue by pavelanihimovsky** [appium/appium#12825]
## The problem

I faced with the error `ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))` on attempt to get the list of elements using command find_elements.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13.0
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: macOS Mojave v10.14.5
* Node.js version (unless using Appium.app|exe): v10.15.3
* Npm or Yarn package manager: npm v6.9.0
* Mobile platform/version under test: iOS 12.0
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: both

## Details

I use Appium-Python-Client==0.44 to develop tests for iOS devices and I faced with this issues on attempt to get the list of elements. I use IOS_CLASS_CHAIN locators to identify elements, but this problem also reproduced with IOS_PREDICATE locators. I noticed that this issue reproduces when there are too many elements should be found by locator (~300). I used different combinations of timeouts (even increased newCommandTimeout up to 1200 seconds and added capability `'commandTimeouts': '{"findElements": 600000}'`) but it does not help. But if I try to get the list with small amount of different elements (1-2) on the same screen it works and works quite fast. 

## Link to Appium logs

Full log - https://gist.github.com/pavelanihimovsky/d4bf87f4485553e38b87b1c958f94185

**Comment by mykola-mokhnach** [comment]
Try to enable ios system logging and see what xctest shows. Also make sure the usbmuxd package is up to date. In general, this looks like xctest issue to me, which we cannot do much about.

**Comment by pavelanihimovsky** [comment]
@mykola-mokhnach 
I have the latest verssions of these packages: libimobiledevice - v1.2.0_3 and usbmuxd - v1.0.10_1
Btw, how can I enabled ios system logging? I've added capability 'showIOSLog': True but nothig has changed in the appium logs.

**Comment by mykola-mokhnach** [comment]
The attached gist does not have `showIOSLog` enabled. Also, you can use Xcode to retrieve the device logs

**Comment by pavelanihimovsky** [comment]
@mykola-mokhnach 
Here is the gist with emabled capability: https://gist.github.com/pavelanihimovsky/d6021e4aee143705f1d991983155d937
I also didn't find any specific issues in Xcode device logs.

**Comment by mykola-mokhnach** [comment]
Yes, not much info to investigate :( The element location is happening on xctest side, and like I said above, there is not much we can change there. Try to describe the problem to Apple

**Comment by pavelanihimovsky** [comment]
@mykola-mokhnach 
Please see this gist https://gist.github.com/pavelanihimovsky/7176b9784a99188c4ac83f8fb5ba5ca8
It looks quite strange. Test fails with error ProtocolError and after 10-15 minutes (rows 27-28) I see the response with the list of elements in Appium logs.

**Comment by mykola-mokhnach** [comment]
if xctest responds properly then the problem should be in usbmuxd/iproxy. Perhaps, there is an internal connection timeout. Although I'm not an expert in this area since this is a third-party component.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
