### ISSUE TITLE
Android: Cannot generate key press event for key code 4

### ISSUE THREAD

**Issue by zengxiaoshi** [appium/appium#12821]
## The problem
    self.driver.press_keycode(4)
  File "G:\Python3.7.2\lib\site-packages\appium\webdriver\webdriver.py", line 698, in press_keycode
    self.execute(Command.PRESS_KEYCODE, data)
  File "G:\Python3.7.2\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "G:\Python3.7.2\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "G:\Python3.7.2\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "G:\Python3.7.2\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot generate key press event for key code 4

## Environment

* Appium version : 1.12.1
* Android

## Details
press_keycode error

**Comment by mykola-mokhnach** [comment]
1. Please attach the logcat output and the full server log
2. Use the most recent server version

**Comment by zengxiaoshi** [comment]
> 1. Please attach the logcat output and the full server log
> 2. Use the most recent server version

It‘s  difficult to get logcat, because of the problem is incidental. And I think "getUiDevice().pressKeyCode(keyCode) return false "  leads to error

**Comment by mykola-mokhnach** [comment]
This is a system function call. If that one fails then I don't think we can do anything on Appium side expect of completely changing the automation backend

**Comment by zengxiaoshi** [comment]
> This is a system function call. If that one fails then I don't think we can do anything on Appium side except of completely changing the automation backend

I know it is a system function. Can you make a issues to Uiautomator? And I think that the code needs to be modified:
        if (!isSuccessful) {
            return new AppiumResponse(getSessionId(request), WDStatus.UNKNOWN_ERROR, String.format(
                    "Cannot generate key press event for key code %s", keyCode));
        }
        return new AppiumResponse(getSessionId(request), WDStatus.SUCCESS, true);
If press_keycode error,  you can "return false" rather than UNKNOWN_ERROR which will block.

**Comment by mykola-mokhnach** [comment]
You are always welcome to propose a pull request.

> Can you make a issues to Uiautomator?

I don't think we have to do that. A correct/reproducible issue description would require the environment details, which are only known to you.

**Comment by zengxiaoshi** [comment]
> You are always welcome to propose a pull request.
> 
> > Can you make a issues to Uiautomator?
> 
> I don't think we have to do that. A correct/reproducible issue description would require the environment details, which are only known to you.

Yeah，This is unreasonable to ask you make a issues to Uiautomator without reasonable cause. 
And do you agree with “ ‘return false’ rather than UNKNOWN_ERROR when press_key_code error”？

**Comment by mykola-mokhnach** [comment]
I'd prefer to review the pull request first
