### ISSUE TITLE
Android 8.1 switch from Wechat Public Number page to APP page and report errors

### ISSUE THREAD

**Issue by rggaoxin** [appium/appium#12823]
## The problem

from webview to apps,click close windows, report error

## Environment

Appium 1.13.0
Android 8.1
WebView 66.0.3359.126

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

log path

https://gist.github.com/rggaoxin/c89fdd4f348cf5a8835aa1c962252717

I'm sorry,my english is so bad.I'm a chinese. 
Please forgive me for using Chinese to express the problem.

我很抱歉，我的英语真的非常糟糕，我是一个中国人，请原谅我使用中文来表述问题。
安卓8.1版本，appium1.13.0，从微信公众号的webview页面切换到微信的app页面上，点击退出当前页面的X建，报错。无法正常切换页面，试过几次，5次会有1次成功，使用debug调试代码未出现问题，怀疑可能是操作过快的问题

**Comment by mykola-mokhnach** [comment]
The exception itself looks like endless recursion loop in UiAutomator2 lib: https://android.googlesource.com/platform/frameworks/uiautomator/+/android-support-test/src/main/java/android/support/test/uiautomator/ByMatcher.java#172

Consider reporting the bug to Google.

Also, you can try to use another locator type or change the automation backend completely as a workaround

**Comment by mykola-mokhnach** [comment]
In case the destination element is located inside a web view then it makes sense to perform the lookup being inside web view context

**Comment by rggaoxin** [comment]
ok，I try to add sleep time to solve the problem，and it's ok。 I think it's too fast to operate，and produce the problem。
我尝试了添加睡眠时间，去解决这个问题，成功解决了。我想可能还是太快的操作导致出现了这个问题

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
