### ISSUE TITLE
Socket hangup error with Appium 1.13.0 on iOS 12.3.1 real device

### ISSUE THREAD

**Issue by VenkateshPS** [appium/appium#12839]
## The problem

Socket hangup error with Appium 1.13.0 on iOS 12.3.1 real device, when send text is called.

## Environment

* Appium version (or git revision) that exhibits the issue:1.13.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):10.15.3
* Npm or Yarn package manager:
* Mobile platform/version under test:12.3.1
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
https://gist.github.com/VenkateshPS/ca153cee16f5b7ec5c238ffbe578fb7f
https://gist.github.com/VenkateshPS/8681884d839930d91ec62fea499e3485

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
This error usually happens if WDA stops responding to requests (e.g. crashes) or there is an issue with iproxy utility. Please attach the device log to see what happens with WDA when the type command is received and make sure the usbmuxd is up to date.

**Comment by VenkateshPS** [comment]
Device log
https://gist.github.com/VenkateshPS/301aae7bbf330c435b6e3d9ceeb0253d

**Comment by VenkateshPS** [comment]
device log at the time of error.
https://gist.github.com/VenkateshPS/81c42cd214c48e4b010759e60d3b9d10

**Comment by mykola-mokhnach** [comment]
I don't observe any issues in the attached logs - are you sure they are taken within correct time periods?

**Comment by VenkateshPS** [comment]
I took another log, take a look

15:58:28.020358 +0530
testmanagerd Error 13: <private>
default
15:58:28.020582 +0530
testmanagerd Found an error for attribute 2001: <private>
default
15:58:28.020788 +0530
testmanagerd Failed to map result for attribute <private>: results dictionary did not contain a value for the numeric attribute
default

https://gist.github.com/VenkateshPS/cb96de8fa7a1d48267f4c49b132db783

**Comment by VenkateshPS** [comment]
I tried on another Mac machine and it worked fine.

**Comment by isuroo** [comment]
@VenkateshPS what seems to be the issue? I'm facing the same issue.

**Comment by VenkateshPS** [comment]
Try This, it worked for me

brew uninstall ideviceinstaller
brew uninstall --ignore-dependencies libimobiledevice
brew uninstall --ignore-dependencies usbmuxd
brew install --HEAD libimobiledevice
brew install usbmuxd --HEAD
brew install --HEAD libimobiledevice
brew unlink libimobiledevice && brew link libimobiledevice
brew install --HEAD ideviceinstaller
brew unlink ideviceinstaller && brew link ideviceinstaller
sudo chmod -R 777 /var/db/lockdown
