### ISSUE TITLE
Do you need Appium Desktop's platformversion 

### ISSUE THREAD

**Issue by jackytallow** [appium/appium#12834]
## The problem
  The verson of Appium Desktop is 1.13.0 which I used
  I find some problems, when i write the platformversion in capacity, it can display the error
    "unable find the android device"
 but I don't write the platformversion, it works fine 
so what ' s the problem in Appium Desktop
## Details
Error: Unable to find an active device or emulator with OS 5.5.1. The following are available: 127.0.0.1:5555 (5.1.1)

**Comment by mykola-mokhnach** [comment]
Please properly fill out the issue report and provide the full server log

**Comment by jackytallow** [comment]
oh thanks
I understand it wrang , it's my computer problem
thanks your solve
