### ISSUE TITLE
A memory leak occurred while running appium for a long time

### ISSUE THREAD

**Issue by xiaochaom** [appium/appium#12838]
## The problem

When I was executing my test case with appium all night, I had an appium service crash.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS 10.14.4 
* Node.js version (unless using Appium.app|exe): v12.4.0
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: iOS 12
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:  Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

[debug] [W3C (b19b74e7)] Calling AppiumDriver.getScreenshot() with args: ["b19b74e7-4963-42ec-bd3a-3a92ca1af3f3"]
[debug] [XCUITest] Executing command 'getScreenshot'
[debug] [XCUITest] Taking screenshot with WDA
[debug] [WD Proxy] Matched '/screenshot' to command name 'getScreenshot'
[debug] [WD Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/A65F74E1-A5A2-40AB-B62A-9EEC16D989D0/screenshot] with no body
[debug] [WD Proxy] Got response with status 200: "{\n  \"value\" : \"iVBORw0KGgoAAAANSUhEUgAABNoAAAigCAIAAABm8NjOAAAAAXNSR0IArs4c6QAA\\r\\nABxpRE9UAAAAAgAAAAAAAARQAAAAKAAABFAAAARQAA9siIP+mM8AAEAASURBVHgB\\r\\n7J0HvF1F1bdvIFQRLK+9kNBs2LBihYBAKEEsIDXlpieAKCAaO6C+9l4RG1g+sDdU\\r\\nEEXEgooUgYSmIvbeO99z7gN\\/hnPOPbm5qfCu+d1M1p5Zs2bNf8+sPWvP7DlDQxUK\\r\\ngUKgECgECoFCoBAoBAqBQqAQKAQKgUKgECgECoFCoBAoBAqBQqAQKAQKgUKgECgE\\r\\nCoFCoBAoBAqBQqAQKAQKgUKgECgECoFCoBAoBAqBQqAQKAQKgUKgECgECoFCoBAo\\r\\nBAqBQqAQKAQKgUKgECgECoFCoBAoBAqBQqAQKAQKgUKgECgECoFCoBAoBAqBQqAQ\\r\\nKAQKgUKgECgECoFCoBAoBAqBQqAQKAQKgUKgECgECoFCoBAoBAqBQqAQKAQKgUKg\\r\\nECgECoFCoBAoBFYLAhMmTECu8QYbbABtvFoqG4NQNDHICx2iTTdxvZHQJZW0rpS6\\r\\nLAQKgVs9AhMnTlx\\/\\/fXbZraXWpLYk5Zt7DRVyLzxxhtLYG1il6zOlLHLLM5CoBAo\\r\\nBFYHApkLxUbFDCaLemPWVocO\\/2dlAnULssiDRle6KessSjQhrUgTVl7btsttsskm\\r\\nCkxFKy+\\/JNxSEWg7wSrscOODIzNINIFu9YFGVVPadCoya3w1VqlCoBC4lSHA067L\\r\\nRPj807x0ZY2l7Xl8ai2JJVKWt3i+yBuH8AgpohAoBAqBlUcg8yhExSJBhCYdC9Ze\\r\\nrnylJSEItM8L57Ej2N+wuBK2dRb\\/tm+gZNdUPPqvDAFEhHRU6JWRVmVvPQjQ+dIt\\r\\naFXXTGutt...

<--- Last few GCs --->

[25594:0x103cad000] 50652888 ms: Mark-sweep 2036.0 (2049.8) -> 2036.0 (2049.8) MB, 90.2 / 0.0 ms  (average mu = 0.970, current mu = 0.007) last resort GC in old space requested
[25594:0x103cad000] 50652986 ms: Mark-sweep 2036.0 (2049.8) -> 2035.9 (2049.8) MB, 97.9 / 0.0 ms  (average mu = 0.950, current mu = 0.000) last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x37eff2d50451 <JSObject>
    0: builtin exit frame: parse(this=0x37eff2d41f51 <Object map = 0x37ef87401449>,0x37ef2d980139 <Very long string[2777636]>,0x37eff2d41f51 <Object map = 0x37ef87401449>)

    1: safeJsonParse [0x37ef79ed2e41] [/usr/local/lib/node_modules/appium/node_modules/appium-support/build/lib/util.js:~116] [pc=0x195b84452f80](this=0x37ef79e87c69 <Object map = 0x37efd540d479>,0x37ef2d980139 <Very long str...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 0x1000784a8 node::Abort() [/usr/local/bin/node]
 2: 0x100078b26 node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0x10016a275 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x10016a217 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x100430765 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 6: 0x10043549e v8::internal::Heap::SetUp(v8::internal::ReadOnlyHeap*) [/usr/local/bin/node]
 7: 0x1004156a3 v8::internal::Factory::AllocateRawWithImmortalMap(int, v8::internal::PretenureFlag, v8::internal::Map, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 8: 0x1004171f1 v8::internal::Factory::NewRawOneByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 9: 0x1004cedcf v8::internal::Handle<v8::internal::String> v8::internal::JsonParser<true>::SlowScanJsonString<v8::internal::SeqOneByteString, unsigned char>(v8::internal::Handle<v8::internal::String>, int, int) [/usr/local/bin/node]
10: 0x1004ce81a v8::internal::JsonParser<true>::ParseJsonString() [/usr/local/bin/node]
11: 0x1004cf60f v8::internal::JsonParser<true>::ParseJsonObject() [/usr/local/bin/node]
12: 0x1004cdec9 v8::internal::JsonParser<true>::ParseJson() [/usr/local/bin/node]
13: 0x1004cdde8 v8::internal::JsonParser<true>::Parse(v8::internal::Isolate*, v8::internal::Handle<v8::internal::String>, v8::internal::Handle<v8::internal::Object>) [/usr/local/bin/node]
14: 0x1001fa3fa v8::internal::Builtin_Impl_JsonParse(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
15: 0x100a9a042 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/usr/local/bin/node]
Abort trap: 6

## Code To Reproduce Issue [ Good To Have ]

I just repeated the process of opening the app, sending the voice, and ending the voice all night

**Comment by mykola-mokhnach** [comment]
Please provide the full heap dump before OOM error happens. Without the memory dump there is not much we can do there to fix the leak.

**Comment by xiaochaom** [comment]
It may be the problem of the screenshot

[Heap-20190628T144424.heaptimeline.zip](https://github.com/appium/appium/files/3337864/Heap-20190628T144424.heaptimeline.zip)
![Uploading image.png…]()

**Comment by mykola-mokhnach** [comment]
This is just a random snapshot. Can you please take it at the time when memory usage is too high and is close to be exceeded?

**Comment by xiaochaom** [comment]
[Heap-20190702T094817.heapsnapshot.zip](https://github.com/appium/appium/files/3347939/Heap-20190702T094817.heapsnapshot.zip)

![image](https://user-images.githubusercontent.com/21215047/60476712-2a09b580-9caf-11e9-9796-de055f716da2.png)

**Comment by mykola-mokhnach** [comment]
Nothing suspicious in the snapshot above. As you can see the heap size does not even reach 100 MB

**Comment by xiaochaom** [comment]
Node V8 takes up about 1.4g of memory by default. Now it looks like it's full?

**Comment by cpj1352** [comment]
[Heap-20190703T145726.zip](https://github.com/appium/appium/files/3353669/Heap-20190703T145726.zip)
We had the same problem. Python script runs for three hours. The heap size exceeds 1G

**Comment by mykola-mokhnach** [comment]
Linking https://github.com/appium/node-teen_process/pull/48

**Comment by mykola-mokhnach** [comment]
@cpj1352 Thanks for the snapshot - it's really useful. 

Please try the most recent appium@beta, - it should leak much less than before (in the ideal world it shouldn't, but our world is not ideal 🐱 )

**Comment by mykola-mokhnach** [comment]
Closing for now. Let us know if you have any similar observations in the recent beta releases.

**Comment by rakhmatullov** [comment]
Hi. I have test runs which take from 6 to 50 hours using Appium. I'm using Mac terminal session to run Appium server. After I upgraded to Appium version v.1.20.2 the memory became leaking from the terminal process (with almost  exactly same test code which didn't lead to leaks in previous versions of Appium). With the version after about 10 hours of test running I get terminal process to grow to about 12Gb in memory which leads to a process hang up (stuck), because no more free memory in the system. This is why I'm downgrading to version 1.19 to confirm this statement.
<img width="861" alt="Знімок екрана 2021-01-24 о 14 32 42" src="https://user-images.githubusercontent.com/5517337/105679047-946bf180-5ef6-11eb-8ac6-ee1e98c0904e.png">

**Comment by mykola-mokhnach** [comment]
@rakhmatullov If there is a memory leak than I would expect the `node` process to allocate it rather than the `Terminal` one. You could take a memory snapshot of the Appium's node process to verify this assumption though and to see what exactly there is leaking.

**Comment by rakhmatullov** [comment]
@mykola-mokhnach running exactly the same code for about 9 hours with v1.19.1 leads to almost none growth in memory consumption. I'll try to find more details when I return back to 1.20...
<img width="865" alt="Знімок екрана 2021-01-25 о 18 29 28" src="https://user-images.githubusercontent.com/5517337/105734470-5513c400-5f3b-11eb-8838-7599e9dfddfa.png">
