### ISSUE TITLE
a problem occur when i use appium-doctor(✖ DevToolsSecurity is NOT enabled!)

### ISSUE THREAD

**Issue by xsj931122** [appium/appium#12830]
## The problem
run appium-doctor and toast me like that

info AppiumDoctor Appium Doctor v.1.9.0
info AppiumDoctor ### Diagnostic for necessary dependencies starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: /usr/local/bin/node
info AppiumDoctor  ✔ Node version is 11.14.0
info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ Xcode Command Line Tools are installed in: /Applications/Xcode.app/Contents/Developer
WARN AppiumDoctor  ✖ DevToolsSecurity is NOT enabled!
info AppiumDoctor  ✔ The Authorization DB is set up properly.
info AppiumDoctor  ✔ Carthage was found at: /usr/local/bin/carthage
info AppiumDoctor  ✔ HOME is set to: /Users/shxia
info AppiumDoctor  ✔ ANDROID_HOME is set to: /Users/shxia/Library/Android/sdk
info AppiumDoctor  ✔ JAVA_HOME is set to: /Library/Java/JavaVirtualMachines/jdk1.8.0_201.jdk/Contents/Home
info AppiumDoctor  ✔ adb exists at: /Users/shxia/Library/Android/sdk/platform-tools/adb
info AppiumDoctor  ✔ android exists at: /Users/shxia/Library/Android/sdk/tools/android
info AppiumDoctor  ✔ emulator exists at: /Users/shxia/Library/Android/sdk/tools/emulator
info AppiumDoctor  ✔ Bin directory of $JAVA_HOME is set

## Environment

mac

**Comment by mykola-mokhnach** [comment]
I don't observe any issues here - the warning is valid. Please use Appium forum if you have additional questions.
