### ISSUE TITLE
facing issue while interacting with the app

### ISSUE THREAD

**Issue by gs-rsrivastav** [appium/appium#12837]
## The problem

Appium is not able to interact with app in emulator
## Environment

* Appium version 1.13.0
* Desktop OS/version used to run Appium: mac
* Node.js version (unless using Appium.app|exe): V12.4.0
* Mobile platform/version under test: Android 9.0
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: appium cli
<img width="1439" alt="Screenshot 2019-06-27 at 2 09 48 PM" src="https://user-images.githubusercontent.com/32387704/60250975-47bcd080-98e5-11e9-84fd-bb963295390e.png">
<img width="1439" alt="Screenshot 2019-06-27 at 2 09 48 PM" src="https://user-images.githubusercontent.com/32387704/60250987-4db2b180-98e5-11e9-98c8-5863f1837e5f.png">

## Details

while interacting with the app i am getting following error

[debug] [ADB] The count of applications in the cache: 6
[ADB] The application at '/Users/rsrivastav/Downloads/Calculator_v7.6_SIGNED_UNALIGNED.apk' is already cached to '/data/local/tmp/appium_cache/2266091c815516a877894c98fd91854f92395a83.apk'
[debug] [ADB] Running '/Users/rsrivastav/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pm install /data/local/tmp/appium_cache/2266091c815516a877894c98fd91854f92395a83.apk'
[debug] [AndroidDriver] Shutting down Android driver
[debug] [AndroidDriver] Called deleteSession but bootstrap wasn't active
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Running '/Users/rsrivastav/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop io.appium.unlock'
[debug] [AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1561621290686 (13:11:30 GMT+0530 (India Standard Time))
[debug] [W3C] Encountered internal error running command: Error executing adbExec. Original error: 'Command '/Users/rsrivastav/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pm install /data/local/tmp/appium_cache/2266091c815516a877894c98fd91854f92395a83.apk' exited with code 1'; Stderr: ''; Code: '1'
[debug] [W3C] Error: Command '/Users/rsrivastav/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pm install /data/local/tmp/appium_cache/2266091c815516a877894c98fd91854f92395a83.apk' exited with code 1
[debug] [W3C]     at ChildProcess.<anonymous> (/Users/rsrivastav/.npm-global/lib/node_modules/appium/node_modules/teen_process/lib/exec.js:94:19)
[debug] [W3C]     at ChildProcess.emit (events.js:200:13)
[debug] [W3C]     at maybeClose (internal/child_process.js:1021:16)
[debug] [W3C]     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
[HTTP] <-- POST /wd/hub/session 500 951 ms - 1069

## Link to Appium logs

Appium log . : https://gist.github.com/gs-rsrivastav/7effdc4439a6d65f74437796cd4a3cc9

adb logcat : https://gist.github.com/gs-rsrivastav/bd7e0666af1dd2d5c90d7e4a99758aae

**Comment by mykola-mokhnach** [comment]
UiAutomator1 is deprecated and should not be used with Android6+

**Comment by gs-rsrivastav** [comment]
this issue is resolved but now i am facing the following issue

not sure what is happening now.
our dev is saying something Appium is doing to our app sue to that it is getting impacted.

please help me here if any solution is there for this.

<img width="357" alt="Screenshot 2019-07-01 at 12 18 58 PM" src="https://user-images.githubusercontent.com/32387704/60416031-7646ee00-9bfa-11e9-828a-f7ebdb087175.png">

**Comment by KazuCocoa** [comment]
> above issue is resolved but now i am facing the following issue

Could you attach the new log (including the logcat)?

You had an apk which was built like `react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/` It could install via `adb install`. It also could launch it via adb like `adb shell am start -n yourpackagename/.activityname`.
But the error happened only via Appium.

hmm

**Comment by mykola-mokhnach** [comment]
Please don't mix different problems in one report. If there is another issue then please describe it separately and provide the necessary details of it
