### ISSUE TITLE
Cannot launch appium with server flags stored in json file

### ISSUE THREAD

**Issue by igalep** [appium/appium#12842]
## The problem
Trying to launch appium server with server flags stored in json file by using --nodeconfig path/to/json

But the default values (for example the default port) remain the same and not being override
 
## Environment
* Appium version - 1.13.0

## Details
the command
appium --nodeconfig flags.json

json file :
{
  "capabilities":[{}]
  ,
    "configuration":{
    "port":1234
  }
}

outcome :
[Appium] Welcome to Appium v1.13.0
[Appium] Non-default server args:
[Appium]   nodeconfig: flags.json
[debug] [Appium] No registration sent (undefined = false)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723

**Comment by KazuCocoa** [comment]
The current behaviour is:

- Appium sets its host/port and url as a request to grid if `nodeconfig` does not have them
- Appium sends a request to grid server without modification if the nodeconfig has host/port and url

So, if you would like to configure port/host, please refer `-a` and `-h` https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md

And set it to nodeconfig (not do not provide it to nodeconfig)


- https://github.com/appium/appium/blob/1d2f4d62ac83cc37eae848c0067722d5727863da/lib/main.js#L131
- https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/grid.md

**Comment by igalep** [comment]
Ok , I'll clarify my self.
The json with port was just an example.

I've several mini macs which running appium server (jenkins slaves)
I'm trying to launch the server on each slave machine with the same server flag, so I'm trying to store them in json file.

**Comment by mykola-mokhnach** [comment]
Consider using Appium forum for questions.

**Comment by igalep** [comment]
tried that, no answer :(

**Comment by mykola-mokhnach** [comment]
create a server startup shell script with necessary command line parameters on each node and execute it by jenkins instead of starting it directly

**Comment by KazuCocoa** [comment]
A Jenkins host, `host1`, starts with `appium -p 4723` <= provide `configuration` of `nodeconfig` as `port: 4723` and `host: host1`

Another Jenkins host, `host2`, starts with  `appium -p 4725`  <= provide `configuration` of `nodeconfig` as `port: 4725` and `host: host2`

then, the grid send requests to `host1:4723` and `host2:4725`

Maybe, it works.
(more concrete example)

**Comment by igalep** [comment]
Thanks for the answer
but the port was just an example, I'm talking about other flags as well (logs for example)
