### ISSUE TITLE
Command 'carthage bootstrap --platform iOS\,tvOS' exited with code 1

### ISSUE THREAD

**Issue by zcmgyu** [appium/appium#12841]
## The problem

Could not install WDA on simulator/real device, because carthage bootstrap command throw error

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.0-beta.2
* Last Appium version that did not exhibit the issue (if applicable): 1.14.0-rc.1
* Desktop OS/version used to run Appium: macOS
* Node.js version (unless using Appium.app|exe): v11.9.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iPhone X iOS 12.2 (Sim) and iPhone 6 iOS 11.0.1 (device)
* Real device or emulator/simulator: both
* Appium CLI or Appium.app|exe: CLI

## Details
I haven't dive in source code but I think that error maybe come from new `appium-webdriveragent` repo

## Link to Appium logs

https://gist.github.com/zcmgyu/51ad5cb03daa30f34b45ea8aebab82b6

## Code To Reprodsuce Issue [ Good To Have ]

> POST {{host}}/session

```
{
    "desiredCapabilities": {
        "platformName": "iOS",
        "platformVersion": "12.2",
        "deviceName": "iPhone X",
        "app": "/Users/zcmgyu/Downloads/BaseReactNative_v3.2.app"
    }
}
```

**Comment by mykola-mokhnach** [comment]
> [WebDriverAgent] Failed to check out repository into /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Checkouts/CocoaAsyncSocket: Could not create working directory (Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “CocoaAsyncSocket” in the folder “Checkouts”." UserInfo={NSFilePath=/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Checkouts/CocoaAsyncSocket, NSUnderlyingError=0x7f9de412e4c0 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}})

I think the error message is clear - it is a problem with local FS permissions.

**Comment by KazuCocoa** [comment]
You can make sure if the command works in the directory like below. (Ensure the running user as mykola's comment)

```
$ cd /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/
$ carthage bootstrap --platform iOS\,tvOS
```

**Comment by zcmgyu** [comment]
Thank you guys.

I gotta reclaim write permission in node_modules directory again. Everything works as expected.

> sudo chown -R $(whoami) /usr/local/lib/node_modules

**Comment by zcmgyu** [comment]
@

**Comment by giri-gonzai** [comment]
> Thank you guys.
> 
> I gotta reclaim write permission in node_modules directory again. Everything works as expected.
> 
> > sudo chown -R $(whoami) /usr/local/lib
> 
> Allow root argument when install appium seems like not work at all.
> 
> > npm install -g appium --unsafe-perm=true --allow-root
> 
> Updated: (Oct 10 2019)
> Remove Appium from your computer and re-install to solve problem.
> 
> > npm uninstall -g appium

Worked for me, without updating appium though. Updating Carthage was enough.

**Comment by psingh-babbel** [comment]
> Thank you guys.
> 
> I gotta reclaim write permission in node_modules directory again. Everything works as expected.
> 
> > sudo chown -R $(whoami) /usr/local/lib
> 
> Allow root argument when install appium seems like not work at all.
> 
> > npm install -g appium --unsafe-perm=true --allow-root
> 
> Updated: (Oct 10 2019)
> Remove Appium from your computer and re-install to solve problem.
> 
> > npm uninstall -g appium

It worked for me, but new error came up. 
**`xcodebuild failed with code 65`**

**Comment by pushprajsingh05** [comment]
> Thank you guys.
> 
> I gotta reclaim write permission in node_modules directory again. Everything works as expected.
> 
> > sudo chown -R $(whoami) /usr/local/lib
> 
> Allow root argument when install appium seems like not work at all.
> 
> > npm install -g appium --unsafe-perm=true --allow-root
> 
> Updated: (Oct 10 2019)
> Remove Appium from your computer and re-install to solve problem.
> 
> > npm uninstall -g appium

It worked for me, but new error came up.
**xcodebuild failed with code 65**

**Comment by eliasmajady** [comment]
> Thank you guys.
> 
> I gotta reclaim write permission in node_modules directory again. Everything works as expected.
> 
> > sudo chown -R $(whoami) /usr/local/lib
> 
> Allow root argument when install appium seems like not work at all.
> 
> > npm install -g appium --unsafe-perm=true --allow-root
> 
> Updated: (Oct 10 2019)
> Remove Appium from your computer and re-install to solve problem.
> 
> > npm uninstall -g appium

Didn't worked for me, any more ideas? I've looked in different posts and blogs but the issue is never resolved, they just put some ideas to handle the issue but not a real solution. Hope that someone can help with this.

**Comment by mattslavin** [comment]
I had two versions of carthage installed that was causing this issue. One was with homebrew the other with npm. There was a global node_modules version and then also the one in the carthage app folder. 

```
npm uninstall carthage
brew uninstall carthage
brew install carthage

brew link --overwrite carthage
```

Hopefully that will help!
