### ISSUE TITLE
opencv4nodejs 5 was released with breaking changes

### ISSUE THREAD

**Issue by imurchie** [appium/appium#12849]
## The problem

Recently [opencv4nodejs](https://github.com/justadudewhohacks/opencv4nodejs) released version 5, which breaks our support. See the build for `appium-support` (https://travis-ci.org/appium/appium-support/jobs/552738161).

I'm not familiar enough with how the image utilities work to fix this.

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

**Comment by mykola-mokhnach** [comment]
I assume the reason is https://github.com/justadudewhohacks/opencv4nodejs/issues/584

**Comment by mykola-mokhnach** [comment]
Merged and published
