### ISSUE TITLE
Connection reset by peer After Calling AppiumDriver.performTouch()

### ISSUE THREAD

**Issue by gerald8** [appium/appium#12844]
## [iProxy] recv failed: Connection reset by peer After Calling AppiumDriver.performTouch()

After running a simple python code to perform swipe action, i got a  error log: '[iProxy] recv failed: Connection reset by peer ,[iProxy] recv failed: Operation not permitted', could anyone  help me ?

## Environment
- macOS : 10.14.5
- Xcode :  10.2.1
- iOS : 12.2 
- WebDriverAgent : master branch of [https://github.com/appium/WebDriverAgent](https://github.com/appium/WebDriverAgent)
- [appium-doctor logs](https://gist.github.com/gerald8/fcd47ee9709a171d61e4278698e933a9)
## Link to Appium logs
[appium server logs](https://gist.github.com/gerald8/cd75cbe4cd2c2746593e28dc6dcefeb9)

## Code To Reproduce Issue [ Good To Have ]
[sample code](https://gist.github.com/gerald8/629b9af5020c309a5e072313fda34e80)

**Comment by mykola-mokhnach** [comment]
I assume it is a usual iproxy logging.
The reason of driver shutdown is 

> [info] [35m[HTTP][39m [90m[39m[warn] [35m[BaseDriver][39m Shutting down because we waited 60 seconds for a command

**Comment by mykola-mokhnach** [comment]
It also makes sense to verify the uxbmuxd package is up to date

**Comment by gerald8** [comment]
@mykola-mokhnach ```caps["newCommandTimeout"] = 240000``` made no sense

**Comment by gerald8** [comment]
@mykola-mokhnach how to verify the uxbmxd's version?
reinstalled usbmuxd using this code:
```shell
brew update
brew uninstall --ignore-dependencies libimobiledevice
brew uninstall --ignore-dependencies usbmuxd
brew install --HEAD usbmuxd
brew unlink usbmuxd
brew link usbmuxd
brew install --HEAD libimobiledevice
brew install ideviceinstaller
```
 not help to me

**Comment by mykola-mokhnach** [comment]
> caps["newCommandTimeout"] = 240000 made no sense

Care to attach the updated log?

**Comment by gerald8** [comment]
@mykola-mokhnach thanks for your patience！finally i find it is a usual iproxy logging as you said.please close this issue.
