### ISSUE TITLE
 UiAutomator2 did not start the activity we were waiting for, 'no.nordicsemi.android.mcp/no.nordicsemi.android.mcp.DeviceListActivity'. Starting it ourselves

### ISSUE THREAD

**Issue by Vanireddy67** [appium/appium#12847]
Getting below error while running after starting mobile recorder from katalon studio.
 UiAutomator2 did not start the activity we were waiting for, 'no.nordicsemi.android.mcp/no.nordicsemi.android.mcp.DeviceListActivity'. Starting it ourselves

**Comment by mykola-mokhnach** [comment]
Can you please properly describe the issue and provide the required information and the server logs?
