### ISSUE TITLE
MobileCapabilityType.PROXY causes an error

### ISSUE THREAD

**Issue by boris779** [appium/appium#12845]
If instancing a webdriver with set the capability 

`capabilities.setCapability(MobileCapabilityType.PROXY, seleniumProxy)`

throws an exception  

`org.openqa.selenium.WebDriverException: Unable to parse remote response: 
14:51:21  	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:115)
14:51:21  	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
14:51:21  	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
14:51:21  	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
14:51:21  	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
14:51:21  	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
14:51:21  	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
14:51:21  	at driverutil.DriverFactory.createWebDriver(DriverFactory.kt:196)
14:51:21  	at driverutil.WebDriverSession$webDriver$2.invoke(WebDriverSession.kt:30)
14:51:21  	at driverutil.WebDriverSession$webDriver$2.invoke(WebDriverSession.kt:16)
14:51:21  	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
14:51:21  	at driverutil.WebDriverSession.getWebDriver(WebDriverSession.kt)
14:51:21  	at cucumber.runtime.step_definitions.AbstractStepDefs.getWebDriverSession(AbstractStepDefs.kt:27)
14:51:21  	at cucumber.runtime.step_definitions.NavigationSteps.dieStartseiteGeladenIst(NavigationSteps.kt:57)
14:51:21  	at ✽.die Startseite ist geladen(file:target/parallel/features/Mobile_scenario001_run001_IT.feature:7)
14:51:21  Caused by: org.openqa.selenium.json.JsonException: Expected to read a START_MAP but instead have: END. Last 0 characters read: 
14:51:21  Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
14:51:21  System info: host: '2ff81209f9af', ip: '10.128.255.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.0-0.bpo.8-amd64', java.version: '12.0.1'`

## Environment

* Appium version (or git revision) that exhibits the issue: 7.0.0
* Real device or emulator/simulator: emulator

**Comment by mykola-mokhnach** [comment]
Please provide the necessary issue details (especially the server log)

**Comment by boris779** [comment]
It seems that appium does not handle the Proxy-Capabilities. This is an old post from 2014

https://groups.google.com/forum/#!topic/appium-discuss/HyZPnz6VmvM

Attached appium server log and the exception while running it locally

[appium_server_log_proxy.txt](https://github.com/appium/appium/files/3345948/appium_server_log_proxy.txt)

[appium_client_exception.txt](https://github.com/appium/appium/files/3345952/appium_client_exception.txt)

**Comment by mykola-mokhnach** [comment]
Yep, there is no proxy support via capabilities

**Comment by boris779** [comment]
@jlipps posted some years ago that appium does not support proxies, is that still valid?

**Comment by boris779** [comment]
Ok any other possibility to use a proxy with a appium-device?

**Comment by umutuzgur** [comment]
@boris779 You can use the `shell` support to set it on Android but there is nothing for iOS as far as I know. You need to enable `--relaxed-security` in order to take advantage of shell support. This is the normal command to set a http proxy on the phone `adb shell settings put global http_proxy <address>:<port>`

**Comment by mykola-mokhnach** [comment]
Consider using Appium forum for questions.
