### ISSUE TITLE
Random failure "Cannot start the 'io.appium.settings'" on Pixel

### ISSUE THREAD

**Issue by lubshilk** [appium/appium#12857]
## The problem

When trying to start driver on Pixel device sometimes receiving an error "Cannot start the 'io.appium.settings' application". The driver not started

The first time we run the script the application is installed. Here is the log:
https://gist.github.com/lubshilk/a6921f401b8c4ad87ba494698585a2cd

After we remove the application using adb uninstall command, Appium installs the application  while starting driver, but the same problem reported:
https://gist.github.com/lubshilk/66e946ebf79eaf273d3694330f0e2963

## Environment

* Appium version (or git revision) that exhibits the issue:  1.13.0-beta.3
* Desktop OS/version used to run Appium: MacOS Mojave 10.14.3
* Mobile platform/version under test: Android 9 on Pixel 
* Real device or emulator/simulator: real device

**Comment by mykola-mokhnach** [comment]
Try the recent beta (14).

**Comment by lubshilk** [comment]
Ok

**Comment by mykola-mokhnach** [comment]
Any updates?

**Comment by lubshilk** [comment]
Not yet.
Was on other tasks. Will check in nearest time

**Comment by grndvl1** [comment]
I get the same issue, on a device the test and Appium was working before.
