### ISSUE TITLE
driver.find_elements maximum size?

### ISSUE THREAD

**Issue by michaelgaras** [appium/appium#12851]
## The problem

Appium driver.find_elements returns an empty array when the XML tree is bigger ( Settings page on iOS ). Is there a hard limit on blocking find_elements from executing when the Tree is too big?

Note that I am able to click elements by specifying their "name" or "xpath" but they don't show up when using find_elements. 

Please suggest what do to get find_elements to work with any XML Tree size ( any page )

## Environment

* Appium version 1.13.0
* MacOS Mojave 10.14.5
* Node.js version 10.14.1
* Npm version: 6.4.1
* Mobile platform/version under test: iOS 12.2
* Real device or emulator/simulator: Real Device

## Details

I am trying to get a list of all elements of a specific class ( XCUIType ) on a given page, so I am using the driver.find_elemenets which returns an array of all elements found using the specified locator ( class_name in my case ). 

This works perfectly fine on pages with smaller XML Trees ( Dialer Page on iOS ) but returns an empty array when the XML tree is bigger ( Settings page on iOS ).

Thanks,

Michael Garas

**Comment by sinestic** [comment]
@mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
Do you observe these elements in page source? Are there any errors in the device log?

**Comment by sinestic** [comment]
Yes I can observe them in the page source and I can also find the same first of those elements if I use find_element instead of find_elements. For instance, I can do `driver.find_element(:class, "XCUIElementTypeCell")` and that would return the first element of type Cell on the page, but `driver.find_elements(:class, "XCUIElementTypeCell")` would return an empty array.

No errors in the device log

**Comment by mykola-mokhnach** [comment]
This is strange. What if you change the locator to predicate or xpath?

**Comment by sinestic** [comment]
@mykola-mokhnach 
It works the same way for name, predicate, xpath and class. find_element returns only the first element found and find_elements returns an empty array.

**Comment by mykola-mokhnach** [comment]
I don't have any more ideas there. The location is done by XCTest, so the problem must be hidden somewhere in the framework logic. Not much we can do on that from Appium side though.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
