### ISSUE TITLE
can't start video on iPhone X (real device)

### ISSUE THREAD

**Issue by romainlouvet** [appium/appium#12856]
## The problem

When start recording screen, ffmpeg return error (only with this mac-mini with iPhone X)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13.1
* Real device or emulator/simulator: real iPhone X (ios 12.3.1)

## Link to Appium logs

https://gist.github.com/romainlouvet/ac72e72d34da3a4fef14ab3064924134

## Code To Reproduce Issue [ Good To Have ]

driver.startRecordingScreen(getRecordOption().withTimeLimit(Duration.ofMinutes(30)));

 private BaseStartScreenRecordingOptions getRecordOption() {
    if (driver instanceof IOSDriver) {
      return new IOSStartScreenRecordingOptions()
          .withVideoType(IOSStartScreenRecordingOptions.VideoType.H264);
    }

    if (driver instanceof AndroidDriver) {
      return new AndroidStartScreenRecordingOptions();
    }

    throw new IllegalStateException(WRONG_PLATFORM_MESSAGE);
  }

**Comment by mykola-mokhnach** [comment]
> [ffmpeg] [libx264 @ 0x7f98fe80f800] width not divisible by 2 (1125x2436)

It looks like x264 encoder does not like when one of video dimensions is not divisible by 2.

**Comment by mykola-mokhnach** [comment]
You can try to set a custom scale to workaround that

https://www.reddit.com/r/linux4noobs/comments/671z6b/width_not_divisible_by_2_error_when_using_ffmpeg/

**Comment by romainlouvet** [comment]
same with this workaround 
ffmpeg -f mjpeg -i http://localhost:9100 -vcodec h264 -y /tmp/appium_6c271a.mp4 -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2"
ffmpeg version 4.1.3 Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple LLVM version 10.0.1 (clang-1001.0.46.4)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.1.3_1 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags='-I/Library/Java/JavaVirtualMachines/adoptopenjdk-11.0.2.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/adoptopenjdk-11.0.2.jdk/Contents/Home/include/darwin' --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-videotoolbox --disable-libjack --disable-indev=jack --enable-libaom --enable-libsoxr
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Trailing options were found on the commandline.
[tcp @ 0x7fb790543c80] Connection to tcp://localhost:9100 failed: Connection refused
http://localhost:9100: Connection refused

**Comment by mykola-mokhnach** [comment]
> Trailing options were found on the commandline.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue.

**Comment by romainlouvet** [comment]
this command works 
ffmpeg -f mjpeg -i http://localhost:9100 -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" -y /tmp/appium_07e011.mp4
is it possible to include this fix on appium ?

**Comment by tanistra** [comment]
I had the same problem with python and iOS simulator. Solution:

options = {
                "videoType": "h264",
                "videoScale": "1280:720"
            } 

driver.start_recording_screen(**options)
