### ISSUE TITLE
While doing appium-xcuitest-driver setup not able to connect to the device.

### ISSUE THREAD

**Issue by gs-rsrivastav** [appium/appium#12853]
## The problem

I did all the setup according to  appium-xcuitest-driver documentation but while executing following command    

 xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' test

getting the following log 

https://gist.github.com/gs-rsrivastav/dfeef21e9a92a0c9994b7848248954c1

**Comment by sergmal** [comment]
having the same problem

**Comment by sergmal** [comment]
How to fix this?

**Comment by gs-nativemobileapp** [comment]
try with following capabilities

{
  "platformName": "iOS",
  "platformVersion": "12.2",
  "deviceName": "iPhone 8",
  "app": {app ipa file path},
  "bundleId": {app bundle name},
  "noReset": true,
  "useNewWDA": true,
  "udid": {get this from xcode devices .  info},
  "xcodeOrgId": {get this from appcenter},
  "xcodeSigningId": "iPhone Developer"
}
