### ISSUE TITLE
While doing appium-xcuitest-driver setup not able to connect to the device. 

### ISSUE THREAD

**Issue by gs-rsrivastav** [appium/appium#12854]
I did all the setup according to[ appium-xcuitest-driver ](https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md)documentation but while executing following command

**xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=' test**

getting the following log

https://gist.github.com/gs-rsrivastav/dfeef21e9a92a0c9994b7848248954c1

**Comment by KazuCocoa** [comment]
Could you give us the full log in Appium server side as well?

And what about the latest beta?
The beta has a fix related to signing which fails in some cases.

**Comment by mykola-mokhnach** [comment]
> Testing failed:
> 	Command CodeSign failed with a nonzero exit code
> 	Testing cancelled because the build failed.

I assume there is a problem with code signing.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
