### ISSUE TITLE
Use idb to launch WDA

### ISSUE THREAD

**Issue by umutuzgur** [appium/appium#12850]
## The problem

`xcodebuild` is quite unreliable and fails unexpectedly sometimes. We should have an option to use idb to launch xcuitest and package WebDriverAgentRunner-Runner.app to avoid xcode versioning issues. This would allow us to build WDA with the latest Xcode and run it on every version of Simulator and Real Device. The signing is an issue on the real device side so we can start with Simulators first

## Details

```
idb install --udid <UDID> WebDriverAgentRunner-Runner.app
idb xctest install --udid <UDID> WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest
idb xctest run ui --udid <UDID> com.facebook.wda.runner com.apple.mobilesafari com.apple.test.WebDriverAgentRunner-Runner
```

**Comment by mykola-mokhnach** [comment]
idb seems to be not very reliable especially if we are talking about newer iOS releases.
