### ISSUE TITLE
Dependency details for the Android Sdk?

### ISSUE THREAD

**Issue by dtboy1995** [appium/appium#12855]
#### Thanks to the author's library
***
Appium relies on the Android SDK for control of Android devices
But I don't want to download the full Android SDK. Could you tell me the details of appium's dependency on Android SDK, such as some directory or some exes?
***
*Any help would be greatly appreciated*

**Comment by umutuzgur** [comment]
@dtboy1995 Appium relies on `build-tools`, `tools` and `build-tools` from the Android sdk. You don't need to download any Android Sources or anything

**Comment by elvisxu** [comment]
@umutuzgur thank you very much!
