### ISSUE TITLE
WARN:osjs.HttpChannel:qtp143110009-15: /wd/hub/session java.io.IOException: org.openqa.grid.common.exception.GridException: Cannot extract a capabilities from the request:

### ISSUE THREAD

**Issue by ThamaraiSelvi** [appium/appium#12868]
**The problem**

I'm trying to execute parallel execution for mobile apps. And while doing the same I'm getting this error.
WARN:osjs.HttpChannel:qtp143110009-15: /wd/hub/session java.io.IOException: org.openqa.grid.common.exception.GridException: Cannot extract a capabilities from the request: in my Selenium grid server log.

**Environment**

* Appium version (or git revision) that exhibits the issue: 1.13.1
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): Nodejs 
* Npm or Yarn package manager: Running appium via bat file
* Mobile platform/version under test: Android 7.0 & 7.1.1
* Real device or emulator/simulator: Both
* Appium CLI or Appium.app|exe:
appium -p 4725 --udid ZW3226GGPK -bp 5556 --chromedriver-port 5645 --nodeconfig "D:\Workspace\fsp-app-automation\all.json" -g "D:\Workspace\fsp-app-automation\appium_1.log" --session-override

**Link to Server logs**
D:\Workspace\fsp-app-automation>java -jar selenium-server-standalone-3.13.0.jar -role hub
11:53:11.800 INFO [GridLauncherV3.launch] - Selenium build info: version: '3.13.0', revision: '2f0d292'
11:53:11.803 INFO [GridLauncherV3$2.launch] - Launching Selenium Grid hub on port 4444
2019-07-08 11:53:12.240:INFO::main: Logging initialized @975ms to org.seleniumhq.jetty9.util.log.StdErrLog
11:53:12.906 INFO [Hub.start] - Selenium Grid hub is up and running
11:53:12.907 INFO [Hub.start] - Nodes should register to http://10.190.50.136:4444/grid/register/
11:53:12.908 INFO [Hub.start] - Clients should connect to http://10.190.50.136:4444/wd/hub
11:53:28.134 INFO [DefaultGridRegistry.add] - Registered a node http://0.0.0.0:4726
11:53:32.296 INFO [DefaultGridRegistry.add] - Registered a node http://0.0.0.0:4725
2019-07-08 11:53:48.888:WARN:osjs.HttpChannel:qtp143110009-16: /wd/hub/session java.io.IOException: org.openqa.grid.common.exception.GridException: Cannot extract a capabilities from the request: {
  "desiredCapabilities": {
    "app": "D:\\Workspace\\fsp-app-automation\\src\\test\\resources\\com.globalagricentral.apk",
    "package": "com.globalagricentral",
    "platformVersion": "7.0",
    "appWaitActivity": "*.LanguageActivity, *.SplashActivity",
    "platformName": "Android",
    "udid": "ZW3226GGPK",
    "deviceName": "ZW3226GGPK"
  },
  "capabilities": {
    "firstMatch": [
      {
        "appium:app": "D:\\Workspace\\fsp-app-automation\\src\\test\\resources\\com.globalagricentral.apk",
        "appium:appWaitActivity": "*.LanguageActivity, *.SplashActivity",
        "appium:deviceName": "ZW3226GGPK",
        "package": "com.globalagricentral",
        "platformName": "android",
        "appium:platformVersion": "7.0",
        "appium:udid": "ZW3226GGPK"
      }
    ]
  }
}
2019-07-08 11:53:48.888:WARN:osjs.HttpChannel:qtp143110009-15: /wd/hub/session java.io.IOException: org.openqa.grid.common.exception.GridException: Cannot extract a capabilities from the request: {
  "desiredCapabilities": {
    "app": "D:\\Workspace\\fsp-app-automation\\src\\test\\resources\\com.globalagricentral.apk",
    "package": "com.globalagricentral",
    "platformVersion": "7.1.1",
    "appWaitActivity": "*.LanguageActivity, *.SplashActivity",
    "platformName": "Android",
    "udid": "emulator-5554",
    "deviceName": "emulator-5554"
  },
  "capabilities": {
    "firstMatch": [
      {
        "appium:app": "D:\\Workspace\\fsp-app-automation\\src\\test\\resources\\com.globalagricentral.apk",
        "appium:appWaitActivity": "*.LanguageActivity, *.SplashActivity",
        "appium:deviceName": "emulator-5554",
        "package": "com.globalagricentral",
        "platformName": "android",
        "appium:platformVersion": "7.1.1",
        "appium:udid": "emulator-5554"
      }
    ]
  }
}

## **Code To Reproduce Issue** 

**_DesiredCapabilities:_**

  System.out.println(portNo+"---"+System.currentTimeMillis());
            System.out.println(device_id + "---" + System.currentTimeMillis());
            capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, secondDeviceName);
            capabilities.setCapability("udid", secondDeviceName);
            capabilities.setCapability("platformVersion", "7.1.1");
            capabilities.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
            //			capabilities.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
            if (AppUtil.prop.containsKey("wait.activity")) {
                capabilities.setCapability("appWaitActivity", AppUtil.WAIT_ACTIVITY);
            } else {
                capabilities.setCapability("appActivity", AppUtil.APP_ACTIVITY);
            }

            capabilities.setCapability("package", AppUtil.BASE_PKG);

**all.json**

{
  "capabilities":
      [
        {
          "browserName": "Chrome",
          "deviceName": "Appium",
          "version":"7.0",
          "maxInstances": 1,
          "platformName":"ANDROID"
        },
        {
          "browserName": "Chrome",
          "deviceName": "Appium",
          "version":"7.1.1",
          "maxInstances": 1,
          "platformName":"ANDROID"
        }
      ],
  "configuration":
  {
        "cleanUpCycle": 5000,
        "registerCycle": 5000,
        "nodeTimeout": 120,
        "timeout": 600000,
        "nodePolling": 2000,
        "hub": "http://localhost:4444/grid/register",
                          "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
                          "maxSession": 10,
                           "port": 5555,
                            "host": "localhost",
                            "register": true,
                           "hubPort": 4444,
                            "hubHost" :"localhost",
           "role": "node"
  }
 
}

**testng.xml**
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Suite" parallel="tests">
  
  <test thread-count="5" name="ZW3226GGPK">
  <parameter name="port" value="4725"></parameter>
    <parameter name="deviceID" value="ZW3226GGPK"></parameter>
    <classes>
      <class name="com.olamnet.fsp.utilities.AppiumServerTest"/>
    </classes>
  </test> 
  
  
  <test thread-count="5" name="emulator-5554">
    <parameter name="port" value="4726"></parameter>
    <parameter name="deviceID" value="emulator-5554"></parameter>
    <classes>
      <class name="com.olamnet.fsp.utilities.AppiumServerTest"/>
    </classes>
  </test> 
  
</suite>

**Comment by mykola-mokhnach** [comment]
Make sure you use the most recent client and grid server versions

**Comment by ThamaraiSelvi** [comment]
@mykola-mokhnach 
I'm using Selenium grid - 3.141.59
Java-client - 7.0.0

**Comment by mykola-mokhnach** [comment]
The problem might also be the `package` cap name. W3C requires all non-standard cap names to start with vendor prefix. It is `appium:` in our case
