### ISSUE TITLE
iOS : video stream throw broken pipe on real device

### ISSUE THREAD

**Issue by skiluo** [appium/appium#12865]
## The problem
When I request http:127.0.0.1:9100, the stream ended by broken pipe in 6s。
`2019-07-07 10:45:25.231742+0800 WebDriverAgentRunner-Runner[2004:740369] screen socket disconnected NSPOSIXErrorDomain, Error Domain=NSPOSIXErrorDomain Code=32 "Broken pipe" UserInfo={NSLocalizedDescription=Broken pipe, NSLocalizedFailureReason=Error in write() function}, Broken pipe`

## Environment

* The latest Appium

## Details

On real device，it looks like GCDAsyncSocket can not works properly in background。Why not use Peertalk

**Comment by KazuCocoa** [comment]
Could you attach the full logs? (maybe, ios system log is also helpful)
Is it happen when you run the server long time etc?

It works on my env (real devices, iOS 12 and tvOS as well).
I haven't run it over 2h, 3h tho

According to https://github.com/facebookarchive/WebDriverAgent/issues/795, they removed the library before. (And it supports only via connected cable? not over the network?)

**Comment by mykola-mokhnach** [comment]
This might be also an issue with usbmuxd's iproxy. Make sure it is up to date.

**Comment by skiluo** [comment]
> Could you attach the full logs? (maybe, ios system log is also helpful)
> Is it happen when you run the server long time etc?
> 
> It works on my env (real devices, iOS 12 and tvOS as well).
> I haven't run it over 2h, 3h tho
> 
> According to [facebookarchive/WebDriverAgent#795](https://github.com/facebookarchive/WebDriverAgent/issues/795), they removed the library before. (And it supports only via connected cable? not over the network?)

Thanks for your response. I found iproxy logs like this:
`iproxy 10900 9100 00008020-000E61E92178002E
waiting for connection
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 1406 (serial: 00008020-000E61E92178002E), port 9100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Operation timed out
accepted connection, fd = 4
waiting for connection
Number of available devices == 1`

So I reinstall usbmuxd and it works well now.

**Comment by skiluo** [comment]
> This might be also an issue with usbmuxd's iproxy. Make sure it is up to date.

It is, Thanks
