### ISSUE TITLE
unable to switch to webview on iphone IOS 12.2

### ISSUE THREAD

**Issue by herolyle** [appium/appium#12869]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:1.13.0
* Desktop OS/version used to run Appium:10.14.5
* Node.js version (unless using Appium.app|exe):v10.15.3
* Npm or Yarn package manager:6.4.1
* Mobile platform/version under test:ios 12.2
* Real device or emulator/simulator: iphone xs ios 12.2
* xcode version : Version 10.2.1 (10E1001)
* ios-webkit-debug-proxy: 1.8.5
* 

## Link to Appium logs
[W3C (4e062c43)] Calling AppiumDriver.setContext() with args: ["WEBVIEW_24","4e062c43-d287-4f09-bbad-5f526de128eb"]
[XCUITest] Executing command 'setContext'
[iOS] Attempting to set context to 'WEBVIEW_24'
[RemoteDebugger] Checking which communication style to use (non-Safari on platform version '12.2')
[RemoteDebugger] Platform version equal or higher than '12.2': true
[RemoteDebugger] Setting communication protocol: using full Web Inspector protocol communication
[RemoteDebugger] Connecting to WebKit socket: 'ws://localhost:27753/devtools/page/24'
[RemoteDebugger] WebKit debugger web socket connected to url: ws://localhost:27753/devtools/page/24
[RemoteDebugger] Starting to listen for JavaScript console
[RemoteDebugger] Sending WebKit data: {"method":"Console.enable","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true}}
[RemoteDebugger] Webkit response timeout: 5000
[RemoteDebugger] Received WebKit data: '{"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"page-24","type":"page"}}}'
[RemoteDebugger] Found method 'Target.targetCreated' 
[RemoteDebugger] Target created: {"targetId":"page-24","type":"page"}
[RemoteDebugger] Received WebKit data: '{"error":{"code":-32601,"message":"'Console' domain was not found","data":[{"code":-32601,"message":"'Console' domain was not found"}]},"id":0}'
[RemoteDebugger] Found method 'Console.enable' 
[RemoteDebugger] Setting communication protocol: using Target-based communication
[RemoteDebugger] Sending WebKit data: {"method":"Target.sendMessageToTarget","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"message":{"method":"Console.enable","params":{}}}}
[RemoteDebugger] Webkit response timeout: 5000
[RemoteDebugger] Received WebKit data: '{"error":{"code":-32000,"message":"Target not found.","data":[{"code":-32000,"message":"Target not found."}]},"id":1}'
[RemoteDebugger] Received receipt for message '1'
[W3C (4e062c43)] Encountered internal error running command: TimeoutError: operation timed out
[W3C (4e062c43)]     at afterTimeout (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/bluebird/js/release/timers.js:46:19)
[W3C (4e062c43)]     at Timeout.timeoutTimeout [as _onTimeout] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/bluebird/js/release/timers.js:76:13)
[W3C (4e062c43)]     at ontimeout (timers.js:427:11)
[W3C (4e062c43)]     at tryOnTimeout (timers.js:289:5)
[W3C (4e062c43)]     at listOnTimeout (timers.js:252:5)
[W3C (4e062c43)]     at Timer.processTimers (timers.js:212:10)
[HTTP] <-- POST /wd/hub/session/4e062c43-d287-4f09-bbad-5f526de128eb/context
## Code To Reproduce Issue [ Good To Have ]

 Object[] contexts = driver.getContextHandles().toArray();
        driver.context((String) contexts[contexts.length - 1]);

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Please use appium@1.14 or appium@beta

**Comment by herolyle** [comment]
> Please use appium@1.14 or appium@beta

I retry ...

**Comment by herolyle** [comment]
> Please use appium@1.14 or appium@beta

/usr/local/bin/appium -> /usr/local/lib/node_modules/appium/build/lib/main.js
/usr/local/bin/authorize-ios -> /usr/local/lib/node_modules/appium/node_modules/.bin/authorize-ios

> appium-selendroid-driver@1.13.4 install /usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver
> node ./bin/install.js

(node:15022) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/201968-15022-cfrou9.2bpcr'
(node:15022) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15022) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[20:31:22] Java version 1.8.0_45 found
[20:31:22] Ensuring /usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/selendroid/download exists
[20:31:22] Selendroid setup files did not yet exist, waiting...

**Comment by mykola-mokhnach** [comment]
> UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/201968-15022-cfrou9.2bpcr'
 
Write permissions must be fixed

**Comment by herolyle** [comment]
> Please use appium@1.14 or appium@beta

Thank you very much fro solving this problem with your help.
now use appium@1.14.0 .
