### ISSUE TITLE
Cannot set altitude by setlocation

### ISSUE THREAD

**Issue by ki4070ma** [appium/appium#12867]
## The problem

Cannot set altitude by setlocation

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.0-beta.2
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: macOS 10.14.5
* Node.js version (unless using Appium.app|exe): v12.4.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Android 9
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

## Details

Just called below codes from python-client, but altitude isn't updated to args.

SampleAndroidTest.py
```
def test_01_test_name(self):
    self.driver.set_location(121.21, 11.56, 10)
    import time
    time.sleep(10)
    print(self.driver.location)
```

Terminal
```
➜  app_apidemo git:(master) ✗ python SampleAndroidTest.py
test_01_test_name (__main__.SimpleTest) ... {'latitude': 121.21, 'longitude': 11.56, 'altitude': 5e-324}
ok

----------------------------------------------------------------------
Ran 1 test in 25.996s

OK
```

I can set altitude by executing below adb commands.

```
➜  app_apidemo git:(master) ✗ adb -P 5037 -s 13f1fd2c shell am startservice -e longitude 11.56 -e latitude 121.21 -e altitude 0 io.appium.settings/.LocationService 
Starting service: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=io.appium.settings/.LocationService (has extras) }
➜  app_apidemo git:(master) ✗ adb -P 5037 -s 13f1fd2c shell am broadcast -n io.appium.settings/.receivers.LocationInfoReceiver -a io.appium.settings.location      
Broadcasting: Intent { act=io.appium.settings.location flg=0x400000 cmp=io.appium.settings/.receivers.LocationInfoReceiver }
Broadcast completed: result=-1, data="121.21000 11.56000 0.00000"

➜  app_apidemo git:(master) ✗ adb -P 5037 -s 13f1fd2c shell am startservice -e longitude 11.56 -e latitude 121.21 -e altitude 10 io.appium.settings/.LocationService
Starting service: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=io.appium.settings/.LocationService (has extras) }
➜  app_apidemo git:(master) ✗ adb -P 5037 -s 13f1fd2c shell am broadcast -n io.appium.settings/.receivers.LocationInfoReceiver -a io.appium.settings.location       
Broadcasting: Intent { act=io.appium.settings.location flg=0x400000 cmp=io.appium.settings/.receivers.LocationInfoReceiver }
Broadcast completed: result=-1, data="121.21000 11.56000 10.00000"
```

## Link to Appium logs

https://gist.github.com/ki4070ma/729244eb37734209fbcbe0d1bae5e9fc

https://gist.github.com/ki4070ma/729244eb37734209fbcbe0d1bae5e9fc#file-appium_logs-L185-186

Although passing `10` as altitude to the server, but `10` isn't used during executing adb.
```
[debug] [W3C (d1034c44)] Calling AppiumDriver.setGeoLocation() with args: [{"latitude":121.21,"longitude":11.56,"altitude":10},"d1034c44-82e4-43cf-a63a-fd0aaa9f8e04"]
[debug] [ADB] Running '/Users/atsushimori/Library/Android/sdk/platform-tools/adb -P 5037 -s 13f1fd2c shell am startservice -e longitude 11.56 -e latitude 121.21 io.appium.settings/.LocationService'
```

## Code To Reproduce Issue [ Good To Have ]

As above.

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium-adb/blob/a9680cdb52ff4d9a19b78c5961240f355273ec0e/lib/tools/adb-commands.js#L909

On emulator we can only set latitude and longitude. Nothing else is supported by `emu geo fix`.
Although, this can be added for real devices where Appium settings wrapper is used.

**Comment by ki4070ma** [comment]
Does it mean it isn't supported yet?
I thought it's supported already.

http://appium.io/docs/en/commands/session/geolocation/set-geolocation/

**Comment by mykola-mokhnach** [comment]
yes, this documentation has to fixed. Altitude support has never been there

**Comment by ki4070ma** [comment]
sorry I deleted.

==

Does it mean it isn't supported yet?
I thought it's supported already.

http://appium.io/docs/en/commands/session/geolocation/set-geolocation/

**Comment by mykola-mokhnach** [comment]
The feature for setting altitude on real devices has been merged to beta

**Comment by ki4070ma** [comment]
I've checked `altitude` can be set via `set_location` (python-client) with appium(`1.14.0-beta.2`).
(Documentation update is unnecessary anymore, right?)

**Comment by mykola-mokhnach** [comment]
We can still mention it only works on real devices
