### ISSUE TITLE
Scroll tracking cap does not work

### ISSUE THREAD

**Issue by grafoxy** [appium/appium#12862]
## The problem

Cap "trackScrollEvents" does not work. Issue described in https://github.com/appium/appium/issues/12707 still present  even when cap "trackScrollEvents":false.

## Environment

* Appium version:  Appium v1.14.0-beta.2 /  Appium v1.14.0
* Desktop OS/version used to run Appium: Ubuntu 19.04
* Node.js: 10.15.2
* Mobile platform/version under test: Android
* Appium CLI:  yes

## Details
Looks like Appium ignores this cap:
>>The following capabilities were provided, but are not recognized by Appium:
>>[BaseDriver] trackScrollEvents

## Link to Appium logs

https://gist.github.com/grafoxy/f5456ec7dc6806ba6aa0d4fff598c9c0

**Comment by mykola-mokhnach** [comment]
This is not a capability, but a setting. If you want to set it in caps then use the following format: `settings[trackScrollEvents]`

**Comment by KazuCocoa** [comment]
note:
`settings[settingsKey]` in https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md
https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/settings.md

**Comment by grafoxy** [comment]
@mykola-mokhnach /  @KazuCocoa as settings it works perfectly.
Thanks
