### ISSUE TITLE
Error on connecting to Appium server 1.11.1

### ISSUE THREAD

**Issue by BoazWarshawsky** [appium/appium#12872]
## The problem
I am getting this error when trying to start the test on Emulator:
`Error: The instrumentation process cannot be initialized. Make sure the application under test does not crash and investigate the logcat output.`

## Environment

* Appium version (or git revision) that exhibits the issue:1.11.1
* Last Appium version that did not exhibit the issue (if applicable): 1.11.1
* Desktop OS/version used to run Appium: macOS-10.13
* Node.js version (unless using Appium.app|exe): 8.12.0
* Npm or Yarn package manager:
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Emulator 
* Appium CLI or Appium.app|exe: Appium CLI

## Details
The test start running in CI machine (Mac high sierra) and the android emulator is installed just before starting the test. I verified that the emulator and the app are installed correctly on the device. 

## Link to Appium logs
http://assets-production.applicaster.com.s3.amazonaws.com/qa/zapp_qa/manual/boaz/appium.log

Error can also be found in lines 196 to 220 several times

## Code To Reproduce Issue [ Good To Have ]
Just run Remote for connecting and starting the test

Capabilities:
[appium]
platformName = Android
appPackage = com.featureapp
appActivity = com.applicaster.componentsapp.IntroActivity
server_host = http://127.0.0.1:4723/wd/hub
deviceName = xamarin_android_emulator
automationName = UiAutomator2

**Comment by herolyle** [comment]
please use appium@1.14  or appium@beta , retry .

**Comment by BoazWarshawsky** [comment]
@herolyle I retried, I might not seeing the previous error but now I am getting this error:
http://assets-production.applicaster.com.s3.amazonaws.com/qa/zapp_qa/manual/boaz/appium_server.log

**Comment by BoazWarshawsky** [comment]
@herolyle I am still getting the error, have an idea why?

**Comment by BoazWarshawsky** [comment]
@mykola-mokhnach, can you help us with the error, I am having it while using Appium 1.14 version

**Comment by BoazWarshawsky** [comment]
More inputs about our issue:
If we focus the adb error in the log above I find these 2:

1. On running: `Running '/Users/vsts/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp\:8200'` I am getting `Unable to remove port forward 'Error executing adbExec. Original error: 'Command '/Users/vsts/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp\:8200' exited with code 1'; Stderr: 'adb: error: listener 'tcp:8200' not found'; Code: '1''`
2. Few lines after I am seeing these errors:
`Encountered internal error running command: Error executing adbExec. Original error: 'Command '/Users/vsts/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pm install /data/local/tmp/appium_cache/fe3aa6662b6c999cf661d7626a50da395fd786f4.apk' exited with code 1'; Stderr: ''; Code: '1'`
`Error: Command '/Users/vsts/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pm install /data/local/tmp/appium_cache/fe3aa6662b6c999cf661d7626a50da395fd786f4.apk' exited with code 1`

I am mentioning above while I checked the `adb` server and on `adb devices` command I am getting back good results:
`* daemon not running; starting now at tcp:5037`
`* daemon started successfully`
`List of devices attached`
`emulator-5554	device`

Appium really trying to connect on port 5037 using `emulator-5554`

What is wrong here?

**Comment by KazuCocoa** [comment]
I could also see below message, `uiautomator2ServerInstallTimeout`.
How about this?

```
/data/local/tmp/appium_cache/fe3aa6662b6c999cf661d7626a50da395fd786f4.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'uiautomator2ServerInstallTimeout' capability
[debug] [35m[W3C][39m Error: Command '/Users/vsts/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pm install /data/local/tmp/appium_cache/fe3aa6662b6c999cf661d7626a50da395fd786f4.apk' timed out after 20000ms
[debug] [35m[W3C][39m     at Timeout.setTimeout (/usr/local/lib/node_modules/appium/node_modules/teen_process/lib/exec.js:112:19)
[debug] [35m[W3C][39m     at ontimeout (timers.js:498:11)
[debug] [35m[W3C][39m     at tryOnTimeout (timers.js:323:5)
[debug] [35m[W3C][39m     at Timer.listOnTimeout (timers.js:290:5)
[35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[31m500[39m [90m61913 ms - 1227[39m
```

Perhaps, getting logcat is also helpful

**Comment by BoazWarshawsky** [comment]
@KazuCocoa Its a run that I am running on cloud, its bit a problem for me to provide the logcat before the test even started, something else you can think of?

**Comment by BoazWarshawsky** [comment]
@KazuCocoa I managed to provide you android logcat:
http://assets-production.applicaster.com.s3.amazonaws.com/qa/zapp_qa/manual/boaz/device_appium_fail.log

**Comment by KazuCocoa** [comment]
Thanks.
The log was probably installation did not succeed...? No instrumentation crash.

Could you try out with much longer `uiautomator2ServerInstallTimeout`?
The installation depends on adb install.

**Comment by BoazWarshawsky** [comment]
I will try, 
I just wonder why does Appium trying to install the app if I added these capabilities:
`noReset = true`
`fullReset = false`
?

**Comment by KazuCocoa** [comment]
> trying to install

Do you mean uninstall and install the app again? (Or only "install"?)
I think noReset does not uninstall the package, basically.
http://appium.io/docs/en/writing-running-appium/other/reset-strategies/index.html

It should be another topic if uninstall/install happened in your case.

**Comment by BoazWarshawsky** [comment]
@KazuCocoa setting timeout of 5000 ms did not solve the problem 
There is the log:
http://assets-production.applicaster.com.s3.amazonaws.com/qa/zapp_qa/manual/boaz/device_appium_fail.log

**Comment by KazuCocoa** [comment]
Thanks.

`20000ms` is the default value. What about increasing more than the default value?
e.g. 120000ms

**Comment by BoazWarshawsky** [comment]
@KazuCocoa seems that setting uiautomator2ServerInstallTimeout to 35000 solved the problem.
I will follow to see we don't have future failures as this one

Thanks
