### ISSUE TITLE
Appium still has memory leaks after Appium upgrades version v1.14.0

### ISSUE THREAD

**Issue by cpj1352** [appium/appium#12876]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:  v1.14.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: win10
* Node.js version (unless using Appium.app|exe): v10.15.1
* Npm or Yarn package manager: 6.4.1
* Mobile platform/version under test: Android 8.0
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Appium v1.13.0 encountered this problem, but upgrading to v1.4.0 is not solve.
Appium runs for two hours. Heap size still exceeds 1G

issues link：https://github.com/appium/appium/issues/12838

[Heap-20190709T133708.zip](https://github.com/appium/appium/files/3371438/Heap-20190709T133708.zip)

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium/blob/1.14/npm-shrinkwrap.json#L11132
The version is not included in 1.14.0.
Could you try with `beta`?

**Comment by cpj1352** [comment]
This heap, I think my local teen_process has used the 1.4.3 branch, what should I do?

<img width="441" alt="20190709151737" src="https://user-images.githubusercontent.com/12081262/60867336-2f41a400-a25d-11e9-8058-9ad88414454c.png">

**Comment by KazuCocoa** [comment]
ah, thanks.  yours looks using 1.14.3

**Comment by mykola-mokhnach** [comment]
It still worth to try appium@beta. If the issue is still relevant there then it is probably an issue in the third party library (aka npm-through). The next step will be to replace it with npm-through2

**Comment by mykola-mokhnach** [comment]
Also, as a temporary workaround you can disable logging in Android (use `skipLogcatCapture` cap)

**Comment by mykola-mokhnach** [comment]
Linking https://github.com/appium/node-teen_process/pull/49

**Comment by cpj1352** [comment]
I tried using appium@beta, but the problem is still the same
[Heap-20190710T100649.zip](https://github.com/appium/appium/files/3375940/Heap-20190710T100649.zip)

**Comment by mykola-mokhnach** [comment]
Please reinstall and appium@beta and try again. The version of node-teen_process should be at 1.15.0+

**Comment by mykola-mokhnach** [comment]
any improvements?

**Comment by xiaochaom** [comment]
I used appium 1.14.0 and teen_process@1.15.0, but the memory is still 200M after 30 minutes。
[Heap-20190719T171339.heapprofile.zip](https://github.com/appium/appium/files/3410385/Heap-20190719T171339.heapprofile.zip)

**Comment by mykola-mokhnach** [comment]
@xiaochaom this is already much better than it was before. We are still working on the further improvements.

**Comment by xiaochaom** [comment]
Thanks!
Long may the sunshine！

**Comment by eyalpartner** [comment]
Reproduce also in Latest Beta

**Comment by shopexdream** [comment]
> skipLogcatCapture

skipLogcatCapture ,let me try

**Comment by troyscl** [comment]
Appium still has memory leaks after Appium upgrades version v1.19.1

**Comment by Isidor2811** [comment]
The same hare with Appium 2.0.0-beta.30
