### ISSUE TITLE
How to do iOS fastReset in Appium 1.9.1 - 1.14.0 ?

### ISSUE THREAD

**Issue by djangofan** [appium/appium#12873]
## The problem

I used to use Appium 1.7.1,  and it used to do a  **fastReset** of the application between each test case in a test class.    But,  between 1.9.1 and up to latest version 1.14.0,  a **fastReset** does not seem to be working on iOS.   **Is there a workaround or was the functionality removed?**     I noticed the option is no longer documented here:  http://appium.io/docs/en/writing-running-appium/other/reset-strategies/index.html    

I've been having to manually reset the app between runs, on my local machine.    Also, this bug forces me to manually reset the app between each individual test run, and so I can no longer run a class of tests with fastReset between each test method.   If fastReset were working, then I could run an entire test suite locally on my machine, with app state reset between each test.

## Environment

**Appium Desktop 1.14.0**
JavaScript
  node               10.13.0      /Users/me/.nvm/versions/node/v10.13.0/bin/node
  npm                6.9.0        /Users/me/.nvm/versions/node/v10.13.0/bin/npm
  yarn               1.16.0       /usr/local/bin/yarn
React Native
  react-native-cli   2.0.1
Ignite
  ignite-cli         3.1.3        /usr/local/bin/ignite
Android
  java               1.8.0_211    /Users/me/.asdf/shims/java
  android home       -            /Users/me/Library/Android/sdk
iOS
  xcode              10.2.1

  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 157.68 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.13.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 25, 26, 27, 28
      Build Tools: 27.0.3, 28.0.3
      System Images: android-26 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 1.8.0_211 - /Users/me/.asdf/shims/javac
    Perl: 5.18.4 - /usr/bin/perl
    PHP: 7.1.23 - /usr/bin/php
    Python: 2.7.10 - /usr/bin/python
    Ruby: 2.5.3 - /Users/me/.asdf/shims/ruby

✔ ~/workspace/FAL/falcon/packages/falcon-app [develop ↓·4|✔]
13:31 $ appium-doctor
info AppiumDoctor Appium Doctor v.1.6.0
info AppiumDoctor ### Diagnostic starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: /Users/me/.nvm/versions/node/v10.13.0/bin/node
info AppiumDoctor  ✔ Node version is 10.13.0
info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode_10.2.1.app/Contents/Developer
info AppiumDoctor  ✔ Xcode Command Line Tools are installed.
info AppiumDoctor  ✔ DevToolsSecurity is enabled.
info AppiumDoctor  ✔ The Authorization DB is set up properly.
info AppiumDoctor  ✔ Carthage was found at: /usr/local/bin/carthage
info AppiumDoctor  ✔ HOME is set to: /Users/me
info AppiumDoctor  ✔ ANDROID_HOME is set to: /Users/me/Library/Android/sdk
info AppiumDoctor  ✔ JAVA_HOME is set to: /Users/me/.asdf/installs/java/oracle-8.211
info AppiumDoctor  ✔ adb exists at: /Users/me/Library/Android/sdk/platform-tools/adb
info AppiumDoctor  ✔ android exists at: /Users/me/Library/Android/sdk/tools/android
info AppiumDoctor  ✔ emulator exists at: /Users/me/Library/Android/sdk/tools/emulator
info AppiumDoctor  ✔ Bin directory of $JAVA_HOME is set

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

* Cannot find documentation that answers my question and so I am submitting a new issue on the appium GitHub.

## Code To Reproduce Issue [ Good To Have ]

Capabilities I am passing to Appium 1.14.0:

_appiumVersion=1.9.1,platformVersion=12.0,deviceName=iPhone X,bundleId=com.me.mine,fastReset=true_

* Cannot find documentation that answers my question and so I am submitting a new issue on the appium GitHub.

**Comment by KazuCocoa** [comment]
The _default_ handles as _fastReset_ internally

> manually reset the app between runs, on my local machine

What do you mean? Do you uninstall the app?

**Comment by djangofan** [comment]
> The _default_ handles as _fastReset_ internally
> > manually reset the app between runs, on my local machine
> What do you mean? Do you uninstall the app?

What I mean by that is that I manually go into my app and I delete data that was generated during previous test WITHOUT re-installing app.

**Comment by KazuCocoa** [comment]
Talking only on simulator environment?
(Your way is the only way on real devices)

Perhaps, `clearAppData ` in https://github.com/appium/appium-ios-driver/blob/75ee47e32295a00fddad56af45d8479b45f5020e/lib/device.js#L45 should be called in  https://github.com/appium/appium-xcuitest-driver/blob/e4cf734fc3e895f4cd061f898ef4f7bf99416fbb/lib/simulator-management.js#L76 

I found https://github.com/appium/appium-xcuitest-driver/issues/205

**Comment by KazuCocoa** [comment]
No, https://github.com/appium/appium-xcuitest-driver/blob/e4cf734fc3e895f4cd061f898ef4f7bf99416fbb/lib/simulator-management.js#L126 does the same thing inside the logic.
Currently, it works only when `bundleId` is provided.

Could you attach your Appium log to track the flow?
@djangofan

**Comment by djangofan** [comment]
When bundleId is provided that code (you linked to above) looks like it will try to UN-install the app when noReset=false  (which is clearly NOT a fastReset behavior) .  Keep in mind that is NOT the behavior I am asking about in this questions.    BUT, when I tried this flag on Appium 1.14.0 and it doesn't uninstall the app when passing that flag.   

Attaching my Appium log from Appium 1.14.0 👍 
[testOutput.txt](https://github.com/appium/appium/files/3374085/testOutput.txt)

**Comment by KazuCocoa** [comment]
> why was it removed/disabled?

Do you mean the fastRest capability? It looks current default behaviour. (fullRest = false, noRest = false). Android behaves as so, and iOS also behaves in https://github.com/appium/appium-xcuitest-driver/blob/e4cf734fc3e895f4cd061f898ef4f7bf99416fbb/lib/simulator-management.js#L76

> appium_ios_driver: this.keepAppToRetainPrefs = false

That was in ios-driver, not xcuitest-driver thing. (sorry that was my wrong.)

---

In the create session, your log said Appium tried to call `device.scrubCustomApp`, but failed because of error had been raised.
ah... sorry it requires `app` => `The "path" argument must be of type string. Received type undefined`

```
debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1562691480977 (09:58:00 GMT-0700 (PDT))
[debug] [BaseDriver] Event 'appConfigured' logged at 1562691480978 (09:58:00 GMT-0700 (PDT))
[debug] [BaseDriver] Event 'resetStarted' logged at 1562691480978 (09:58:00 GMT-0700 (PDT))
[XCUITest] The "path" argument must be of type string. Received type undefined
[XCUITest] Reset: could not scrub application with id "com.newco.newapp". Leaving as is.
[debug] [BaseDriver] Event 'resetComplete' logged at 1562691481358 (09:58:01 GMT-0700 (PDT))
[debug] [XCUITest] Starting log capture for iOS Simulator with udid 'F587A81C-826F-44CD-B327-7EBD115CFF42', using 'xcrun simctl spawn F587A81C-826F-44CD-B327-7EBD115CFF42 log stream --style compact'
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1562691481837 (09:58:01 GMT-0700 (PDT))
[XCUITest] Setting up simulator
```

https://github.com/appium/appium-xcuitest-driver/blob/e4cf734fc3e895f4cd061f898ef4f7bf99416fbb/lib/simulator-management.js#L122-L130

**Comment by KazuCocoa** [comment]
I dug further.
Currently, uninstall happens in fastRest condition, too. I roughly changed the behaviour a bit as https://github.com/appium/appium-xcuitest-driver/compare/master...KazuCocoa:do-not-uninstall-app-fastreset?expand=1
Could you apply the change in your local?


----

note: https://github.com/appium/appium-xcuitest-driver/pull/357/files

`await device.scrubCustomApp(path.basename(opts.app), opts.bundleId);` requires `app`, but never reach here if `opts.app` is provided.

**Comment by djangofan** [comment]
I think I see what you mean: 
1.  By not providing "path" to new app to install, which I am currently not providing, the xcuitest-driver will skip the attempt to re-install app onto device before test runs??
2.  I will try to hack my local simulator-management.js , as you describe and see what happens.

I'll reply again once I have more info.

**Comment by djangofan** [comment]
@KazuCocoa  I managed to get it working and it works for me on Appium 1.14.0, using either your suggested changes above  OR  just using the default 1.14.0 functionality.

The problem was that I was not passing the  `app=`  capability, pointing to my locally built  .app   (not .apk )  file.      When i run with   noRest=false +  fullRest=false,  not I am getting the expected behavior, which is  re-install of the app in between tests without restarting entire emulator.

Thank you for leading me in the right direction here.    Is it possible that a log message could be added when  `app=null`  that says "App cannot be reinstalled on emulator without a pointer to location of a pre-build .app file"   (or a similar message) ?

**Comment by KazuCocoa** [comment]
thanks! and the feedback, too.
