### ISSUE TITLE
Appium is very slow on ios 12.2 real device

### ISSUE THREAD

**Issue by omar-Tickerchart** [appium/appium#12879]
## The problem

Actions takes to long to be done it takes around 1-5 min between action and the other

## Environment

* Appium version (or git revision) that exhibits the issue:1.14
* Last Appium version that did not exhibit the issue (if applicable):it's my first time to use appium
* Desktop OS/version used to run Appium:1.14
* Node.js version (unless using Appium.app|exe):12.5
* Npm or Yarn package manager: NPM
* Mobile platform/version under test:12.2
* Real device or emulator/simulator: real device iphone 8
* Appium CLI or Appium.app|exe: CLI

## Details

Actions takes to long to be done it takes around 1-5 min between action and the other
specially the first action take 5+ to be clicked which is "Allow" for notification permission 
 
## Link to Appium logs

https://gist.github.com/omar-Tickerchart/34629d587f3179a92576cd532e2b0a8d

## Code To Reproduce Issue [ Good To Have ]

		
		driver = new IOSDriver(url,caps);
		
		try {
			driver.findElementByName("Allow").click();
			loginTest();
	
			driver.findElementByName("btn wide iphone").click();
			driver.findElementByName("btn top iphone").click();
			driver.findElementByName("btn bottom iphone").click();
			driver.findElementByName("btn index chart iphone").click();
	
			driver.findElementByName("alert icon iphone").click();
			driver.findElementByName("Add new alert").click();
	                 BufferedWriter writer = null;
			try {
	                      File logFile = new File("elements");
	                     System.out.println(logFile.getCanonicalPath());
	                     writer = new BufferedWriter(new FileWriter(logFile));
	                     writer.write(driver.getPageSource());
	                } catch (Exception e) {
	                    e.printStackTrace();
	                } finally {
	                      writer.close();
	                 }
		} finally {
			driver.quit();
		}
	}
	
	public static void loginTest() {
		driver.getPageSource();

		MobileElement usernameTextField = (MobileElement) 
                driver.findElementByName("usernameInput");
		usernameTextField.click();
		usernameTextField.sendKeys("omardiab");
		
		MobileElement passwordTextField = (MobileElement) 
                driver.findElementByName("passwordInput");
		passwordTextField.click();
		passwordTextField.sendKeys("");
		passwordTextField.sendKeys("qwerty");
		driver.findElementByName("Login").click();
	}
}

**Comment by mykola-mokhnach** [comment]
Does the app have active background animations?

**Comment by omar-Tickerchart** [comment]
> Does the app have active background animations?

Thanks for the fast reply . 
No, no animations  in our app except some flushing color in 1 table .

**Comment by mykola-mokhnach** [comment]
XCUITest requires the app to be in idle state in order to take the UI snapshot. Also, I saw reports that it can be very slow if the UI contains hundreds of graphical elements. In both cases there is nothing we can do about it. Check the system log output as well - there might be more details.

**Comment by omar-Tickerchart** [comment]
but it takes too long and session close by it self from waiting 😅

**Comment by mykola-mokhnach** [comment]
There is nothing more to say without the device logs. All suggestions to Apple please

**Comment by mykola-mokhnach** [comment]
closed as third party issue
