### ISSUE TITLE
ios  webview keyboard ..

### ISSUE THREAD

**Issue by herolyle** [appium/appium#12883]
debug] [WD Proxy] Proxying [POST /actions] to [POST http://localhost:8100/session/1BB1BBB6-8319-4173-AB4D-967386544E6B/actions] with body: {"actions":[{"type":"key","actions":[{"type":"keyDown","value":""},{"type":"keyUp","value":""}],"id":"keyboard"}]}
[debug] [WD Proxy] Got response with status 200: {"value":"Error Domain=com.facebook.WebDriverAgent Code=1 \"Only actions of 'pointer' type are supported. 'key' is given instead for action with id 'keyboard'\" UserInfo={NSLocalizedDescription=Only actions of 'pointer' type are supported. 'key' is given instead for action with id 'keyboard'}","sessionId":"1BB1BBB6-8319-4173-AB4D-967386544E6B","status":13}
[WD Proxy] Got an unexpected response: {"value":"Error Domain=com.facebook.WebDriverAgent Code=1 \"Only actions of 'pointer' type are supported. 'key' is given instead for action with id 'keyboard'\" UserInfo={NSLocalizedDescription=Only actions of 'pointer' type are supported. 'key' is given instead for action with id 'keyboard'}","s...
[debug] [MJSONWP] Matched JSONWP error code 13 to UnknownError
[debug] [W3C (6880a121)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "Only actions of 'pointer' type are supported. 'key' is given instead for action with id 'keyboard'" UserInfo={NSLocalizedDescription=Only actions of 'pointer' type are supported. 'key' is given instead for action with id 'keyboard'}

**Comment by mykola-mokhnach** [comment]
The error is expected. XCTest does not provide any APIs to type generic key codes.

**Comment by asherman-joinpapa** [comment]
@mykola-mokhnach not a helpful response

**Comment by mykola-mokhnach** [comment]
@asherman-joinpapa Which response would you prefer to see?
