### ISSUE TITLE
Sometimes appium close session after several seconds with reason "New Command Timeout expired"

### ISSUE THREAD

**Issue by grafoxy** [appium/appium#12887]
## The problem
Sometimes appium close session after several seconds with reason "New Command Timeout of 180 seconds expired" but  really it happens after several seconds not after timeout.

And looks like the issue is present only when UiAutomator2 used.

## Environment
* Appium version: v1.14.0
* Desktop OS/version used to run Appium: Ubuntu 19.04
* Node.js version: 10.15.2
* Npm package manager: 5.8.0
* Appium CLI

## Link to Appium logs
https://gist.github.com/grafoxy/19dd6b83ac3ceec0fa3b03088fa7887e

**Comment by mykola-mokhnach** [comment]
The problem here might be, that adb requires a lot of time to grant all these requested permissions. You can try to enable `fullReset` and see if it improves the performance. It would be also interesting to see the log with timestamps enabled.

**Comment by mykola-mokhnach** [comment]
@umutuzgur @jlipps I think it does not make much sense to respect the newCommandTimeout setting for the `createSession` command. What do you think?

**Comment by umutuzgur** [comment]
I think there is already a session timeout capability. I also agree that  `newCommandTimeout` should not mix with that capability

**Comment by grafoxy** [comment]
@mykola-mokhnach logs with timestamps https://gist.github.com/grafoxy/476675f2908a7dc06f4193ccf0816c64

**Comment by mykola-mokhnach** [comment]
Something is not ok with the recent log. The capabilities don't contain the `fullReset` key, but there is a line in the log, which says `2019-07-10 15:03:31:854 - [debug] [UiAutomator2] Capability 'fullReset' set to 'true', Uninstalling 'com.wildix'`. Are you sure this is the log from the same session and nothing is mixed there?

**Comment by mykola-mokhnach** [comment]
Any more updates?

**Comment by grafoxy** [comment]
unfortunately no.
you are right in https://github.com/appium/appium/issues/12887#issuecomment-510104900 - issue happens only after several re-start tests executions. If for every test execution restart appium, issue is not reproduced.

I will close this ticket and returns back with more logs / info.

**Comment by mykola-mokhnach** [comment]
Just make sure you quit your tests in the suite properly even if they fail
