### ISSUE TITLE
Swipe up action not working after upgrading Appium server to v1.14

### ISSUE THREAD

**Issue by prashanth-sams** [appium/appium#12888]
## The problem

Currently, there is no swipe method in `appium_capybara`; so, I created the below PR, which actually worked and working fine with Appium server v1.13 (tested in two different osx machines)

https://github.com/appium/appium_capybara/pull/50/files

However, this patch failed to work when my friend upgraded his Appium server to v1.14 from v1.13; and the same happened to me after upgrading the Appium server to v1.14 in my machine.

## Environment

* Appium ruby version: appium_lib v10.3.1
* Desktop OS/version used to run Appium: MacOS Mojave 10.14.5
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: Emulator Pie Android 9.0 (faced in IOS real device - iPhone 6S)
* Appium CLI or Appium.app|exe: v1.14 (only)
* Last Appium Server version that did not exhibit the issue (if applicable): v1.13

## Details

Looks like Appium server v1.14 is faulty on swipe functionality

Log snippet here:
```
[HTTP] --> POST /wd/hub/session/b977b977-98dd-4032-a6cb-8993e6457fb6/touch/perform
[HTTP] {"actions":[{"action":"press","options":{"x":75,"y":500}},{"action":"wait","options":{"ms":500}},{"action":"moveTo","options":{"x":0,"y":0}},{"action":"release"}]}
[W3C (b977b977)] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":75,"y":500}},{"action":"wait","options":{"ms":500}},{"action":"moveTo","options":{"x":0,"y":0}},{"action":"release"}],"b977b977-98dd-4032-a6cb-8993e6457fb6"]
[WD Proxy] Matched '/touch/perform' to command name 'performTouch'
[WD Proxy] Proxying [POST /touch/perform] to [POST http://localhost:8200/wd/hub/session/cc5fead9-5d44-469b-8618-c5befa480a0b/touch/perform] with body: {"startX":75,"startY":500,"endX":0,"endY":0,"steps":14}
[WD Proxy] Got response with status 200: {"sessionId":"cc5fead9-5d44-469b-8618-c5befa480a0b","status":0,"value":true}
[W3C (b977b977)] Responding to client with driver.performTouch() result: true
[HTTP] <-- POST /wd/hub/session/b977b977-98dd-4032-a6cb-8993e6457fb6/touch/perform 200 1025 ms - 14
[HTTP] 
```

## Link to Appium logs

https://gist.github.com/prashanth-sams/806126260bb0745de3dee318e9a054c9

## Code To Reproduce Issue [ Good To Have ]
```
# this works (on swipe down) 
Capybara.current_session.driver.swipe(:start_x => 75, :start_y => 1500, :end_x => 0, :end_y => 0, :duration => 500)

# this doesn't work (on swipe up following the previous swipe down activity)
Capybara.current_session.driver.swipe(:start_x => 75, :start_y => 500, :end_x => 0, :end_y => 0, :duration => 500)
```

Both the above cmds `swipe down` and `swipe up` works fine in Appium server `v1.13`

**Comment by PHUITesting** [comment]
Every single swipe and scrolling touch action method Appium provides has been terribly done so far for me. Not a single one consistently works and most are incorrectly documented.

**Comment by mykola-mokhnach** [comment]
the main difference between this and the previous version is that the default value for automationName is now `uiautomator2` (as you can see the the big warning in the logs). You can either enforce the automation name to `uiautomator1` (which is obsolete) or try to use W3C actions, which should work better.
