### ISSUE TITLE
TouchAction doesn't work

### ISSUE THREAD

**Issue by sunmoondeer** [appium/appium#12884]
## The problem
I want to swipe the page with TouchAction, the following is my code:
actions.press(PointOption.point(sX,sY)).waitAction(WaitOptions.waitOptions(Duration.ofSeconds(1))).moveTo(PointOption.point(eX,eY)).release().perform(); But when the code completed, it does not work for the page. The page does not swipe

## Environment

* Appium version (or git revision) that exhibits the issue:
1.12.0

* Desktop OS/version used to run Appium:
Windows

* Node.js version (unless using Appium.app|exe):
v10.16.0

* Npm or Yarn package manager:
npm

* Mobile platform/version under test:
android 4.4.4

* Real device or emulator/simulator:
real device

* Appium CLI or Appium.app|exe:
appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

 I can not get error info from the appium log
[HTTP] --> POST /wd/hub/session/436c6643-fa2d-48c8-8a1d-c335e413a651/touch/perform
[HTTP] {"actions":[{"action":"press","options":{"x":180,"y":903}},{"action":"moveTo","options":{"x":180,"y":1053}},{"action":"release","options":{}}]}
[debug] [W3C (436c6643)] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":180,"y":903}},{"action":"moveTo","options":{"x":180,"y":1053}},{"action":"release","options":{}}],"436c6643-fa2d-48c8-8a1d-c335e413a651"]
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:touchDown","params":{"x":180,"y":903}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:touchDown","params":{"x":180,"y":903}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: touchDown
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Display bounds: [0,0][1080,1920]
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Performing TouchDown using element? false x: 180, y: 903
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"value":true,"status":0}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:touchMove","params":{"x":180,"y":1053}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:touchMove","params":{"x":180,"y":1053}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: touchMove
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Display bounds: [0,0][1080,1920]
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Performing TouchMove using element? false x: 180, y: 1053
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"value":true,"status":0}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:touchUp","params":{"x":180,"y":1053}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:touchUp","params":{"x":180,"y":1053}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: touchUp
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Display bounds: [0,0][1080,1920]
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Performing TouchUp using element? false x: 180, y: 1053
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"value":true,"status":0}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [W3C (436c6643)] Responding to client with driver.performTouch() result: null

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
```
[HTTP] --> POST /wd/hub/session/436c6643-fa2d-48c8-8a1d-c335e413a651/touch/perform
[HTTP] {"actions":[{"action":"press","options":{"x":180,"y":903}},{"action":"moveTo","options":{"x":180,"y":1053}},{"action":"release","options":{}}]}
```

I don't observe the wait action here

**Comment by sunmoondeer** [comment]
fixed. Transform the start  and end PointOption
