### ISSUE TITLE
Under the webview, the element clicks no response, and the wda log has no abnormality.

### ISSUE THREAD

**Issue by herolyle** [appium/appium#12886]
platform ：ios 12.2
appium：1.14.0

**Comment by mykola-mokhnach** [comment]
Can you please provide a proper issue description?

**Comment by herolyle** [comment]
So sorry, I will provide you tomorrow.

**Comment by herolyle** [comment]
> Can you please provide a proper issue description?

appium log: 

`
[HTTP] {"using":"id","sessionId":"921c7eb5-36f5-454f-9140-d8a611314a21","value":"Alert-ok"}
[debug] [MJSONWP (921c7eb5)] Calling AppiumDriver.findElement() with args: ["id","Alert-ok","921c7eb5-36f5-454f-9140-d8a611314a21"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 20000 ms for condition
[debug] [RemoteDebugger] Executing atom 'find_element'
[debug] [RemoteDebugger] Executing 'find_element' atom in default context
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var k=this;functi...
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"expression":"(function(){return function(){var k=this;functi...
[debug] [RemoteDebugger] Webkit response timeout: 5000
[debug] [RemoteDebugger] Received WebKit data: '{"result":{"result":{"type":"string","value":"{\"status\":0,\"value\":{\"ELEMENT\":\":wdc:1562761543047\"}}"}},"id":2}'
[debug] [RemoteDebugger] Found method 'Runtime.evaluate' for message '2'
[debug] [RemoteDebugger] Received result for atom 'find_element' execution: {"ELEMENT":":wdc:1562761543047"}
[debug] [MJSONWP (921c7eb5)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"5002","ELEMENT":"5002"}
[HTTP] <-- POST /wd/hub/session/921c7eb5-36f5-454f-9140-d8a611314a21/element 200 39 ms - 135
[HTTP] 
[HTTP] --> POST /wd/hub/session/921c7eb5-36f5-454f-9140-d8a611314a21/element/5002/click
[HTTP] {"sessionId":"921c7eb5-36f5-454f-9140-d8a611314a21","id":"5002"}
[debug] [MJSONWP (921c7eb5)] Calling AppiumDriver.click() with args: ["5002","921c7eb5-36f5-454f-9140-d8a611314a21"]
[debug] [XCUITest] Executing command 'click'
[debug] [RemoteDebugger] Executing atom 'click'
[debug] [RemoteDebugger] Executing 'click' atom in default context
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var h,aa=this;fun...
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"expression":"(function(){return function(){var h,aa=this;fun...
[debug] [RemoteDebugger] Webkit response timeout: 5000
[debug] [RemoteDebugger] Received WebKit data: '{"result":{"result":{"type":"string","value":"{\"status\":0,\"value\":null}"}},"id":3}'
[debug] [RemoteDebugger] Found method 'Runtime.evaluate' for message '3'
[debug] [RemoteDebugger] Received result for atom 'click' execution: null
[debug] [MJSONWP (921c7eb5)] Responding to client with driver.click() result: null
[HTTP] <-- POST /wd/hub/session/921c7eb5-36f5-454f-9140-d8a611314a21/element/5002/click 200 68 ms
`


webview element :

![image](https://user-images.githubusercontent.com/1737842/61016360-ec4d1100-a3c1-11e9-9308-d1c607dfd9bb.png)

**Comment by mykola-mokhnach** [comment]
There is an issue about webview alerts cannot be clicked. Try to accept it from native context.

**Comment by mykola-mokhnach** [comment]
any updates?
