### ISSUE TITLE
When the app has animation, it's very slow to perform page operations

### ISSUE THREAD

**Issue by lcxlc** [appium/appium#12891]
## The problem

On an animated page, the response time of the elements on the action page is slow

## Environment

All environments are up to date

## Details
Android apps. On an animated page, it takes a long time for a click event to click,

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
closed as duplicate
