### ISSUE TITLE
When the app has animation, it's very slow to perform page operations

### ISSUE THREAD

**Issue by lcxlc** [appium/appium#12890]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Can you please provide proper issue description?

**Comment by lcxlc** [comment]
In a video preview page, there is an animation similar to loading animation at the top, manipulating the elements of this page, the response time is slow, and. This page is also unreadable on uiautomatorviewer

**Comment by lcxlc** [comment]
> 你能提供适当的问题描述吗？

In a video preview page, there is an animation similar to loading animation at the top, manipulating the elements of this page, the response time is slow, and. This page is also unreadable on uiautomatorviewer

**Comment by mykola-mokhnach** [comment]
There are many things, which I cannot guess from this issue report and thus no precise answer can be provided, for example: platform name, automation backend, capabilities, versions. Without all this information we are talking about abstract things, which don't make much sense.

**Comment by umutuzgur** [comment]
@lcxlc Please follow the correct issue template so we can be helpful faster. The necessary things to investigate an issue are in that template. Otherwise, we will go back and forth to collect that data from you and waste a lot of time

**Comment by lcxlc** [comment]
> There are many things, which I cannot guess from this issue report and thus no precise answer can be provided, for example: platform name, automation backend, capabilities, versions. Without all this information we are talking about abstract things, which don't make much sense.



> 有很多东西，我无法从这个问题报告中猜到，因此无法提供准确的答案，例如：平台名称，自动化后端，功能，版本。没有所有这些信息，我们谈论的是抽象的东西，这些东西没有多大意义。

Android apps. On an animated page, it takes a long time for a click event to click and All configurations are up to date

**Comment by lcxlc** [comment]
> @lcxlc请按照正确的问题模板，以便我们更快地提供帮助。调查问题的必要事项是在该模板中。否则，我们会来回收集您的数据并浪费大量时间

Sorry, I haven't used it before, so I don't know how to do it. The problem is that on an animated page, it takes a long time for things like clicks to happen. Other non-animated pages work quickly

**Comment by mykola-mokhnach** [comment]
UiAutomator framework itself is not optimized to work fast while the application under test is not in idle mode, because it is only possible to take the accessibility snapshot while the app is idling. As a workaround I would try to set the `waitForIdleTimeout` setting to zero, disable window animations (`disableWindowAnimation` capability) with UiAutomator2 backend or switch the backend completely to Espresso. Otherwise such issues have nothing to do with Appium itself.

**Comment by lcxlc** [comment]
> UiAutomator framework itself is not optimized to work fast while the application under test is not in idle mode, because it is only possible to take the accessibility snapshot while the app is idling. As a workaround I would try to set the `waitForIdleTimeout` setting to zero, disable window animations (`disableWindowAnimation` capability) with UiAutomator2 backend or switch the backend completely to Espresso. Otherwise such issues have nothing to do with Appium itself.

thank you
