### ISSUE TITLE
How to create testcase dynamically by way of json

### ISSUE THREAD

**Issue by moshangxiaole** [appium/appium#12896]
## The problem

Well,I mean,people can create testcase and build steps to run it from WebSystem, it build jsondatas and transmit to daemon,the daemon analysis this jsondatas and create testcase dynamically,now, I have a pronlem that  error：Message: An element could not be located on the page using the given search parameters. But I‘m sure the element is exist

## Environment

* Appium version : 1.10
* Python version: 3.7
* Windows: win7 x64

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

![QQ图片20190712110620](https://user-images.githubusercontent.com/26242818/61100847-33a6d080-a49a-11e9-8c41-c9f5b9684c3f.png)

**Comment by mykola-mokhnach** [comment]
Please use Appium forum for questions
