### ISSUE TITLE
UiAutomator2 StackOverflow in AccessibilityNodeInfoHelpers.getVisibleBounds

### ISSUE THREAD

**Issue by tri-fraga** [appium/appium#12892]
## The problem

When automating certain screens result in an StackOverflowException when getting the AccessibilityNodeInfoHelpers.getVisibleBounds. This is called when getting the UiAutomationElement attributes. 

This is also happening when inspecting the app with Appium Desktop Inspector, which results in Appium Desktop loading forever.

I only experience this with UIAutomator2 but UIAutomator1 is working fine.
This bug is similar to #12545 only at a different place.

Again this looks like an application issue but it would be good if UIAutomator2 could catch and handle it.

## Environment

* Appium version (or git revision) that exhibits the issue:  Appium v1.14.0-beta.2 (REV d71fc1857a26a36f0fd5c462d48f5c2b0f9c57b5)
* Desktop OS/version used to run Appium: Windows 10
* Node.js version: v11.14.0
* Npm package manager: 6.10.0
* Mobile platform/version under test: Android
* Real device: One Plus 3
* Appium CLI or Appium.app|exe:

## Link to Appium logs

[UiAutomator2StackOverflowException.log](https://gist.github.com/tri-fraga/0c9eb6615fbbb962ee585a8d4675e3ac)

## Suggested Fix 
Here how I quickly fixed it similar to the resolution of #12545 -> [Avoid stack overlow exception by limiting the maximum recursion depth](https://github.com/appium/appium-uiautomator2-server/commit/9a5f19e2f26db1a1faa21530ba2cddefae605410):

[UiAutomator2StackOverflow.patch](https://gist.github.com/tri-fraga/d508acd82fa4b131e602768fbb74cdc4)

**Comment by mykola-mokhnach** [comment]
I can apply the patch, but it would be interesting to know what prevents you from creating a PR?

**Comment by tri-fraga** [comment]
I am still not fluid in git, should I create a pull request?

**Comment by mykola-mokhnach** [comment]
it worth trying. Simply fork the project, create a branch there, push your changes and there will be a big green button in GitHub to create a PR. Give it a proper title and description and click `create` button.

**Comment by tri-fraga** [comment]
Alright, I created that pull request

**Comment by mykola-mokhnach** [comment]
Cool, added comments

**Comment by mykola-mokhnach** [comment]
The fix has been published in appium@beta.
Thanks for the PR.
