### ISSUE TITLE
Click action does not work if android use React Native framework

### ISSUE THREAD

**Issue by sunmoondeer** [appium/appium#12899]
## The problem

The android that I am testing use the React Native framework。I found the clickable option value is false when use UIactomatorview. The result I canot continue my work, because I can do nothing withou click. Is there any way to resolve this problem?

## Environment

* Appium version (or git revision) that exhibits the issue:
1.12.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
Windows 10
* Node.js version (unless using Appium.app|exe):
10.16.0
* Npm or Yarn package manager:
npm
* Mobile platform/version under test:
4.4.4
* Real device or emulator/simulator:
real
* Appium CLI or Appium.app|exe:
Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
From the log, it does not show error

[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//android.view.View[@index='0']","context":"","multiple":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//android.view.View[@index='0']","context":"","multiple":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding '//android.view.View[@index='0']' using 'XPATH' with the contextId: '' multiple: false
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[CLASS=android.view.View, INSTANCE=0]
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"value":{"ELEMENT":"1"},"status":0}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [W3C (5f6e18af)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"1","ELEMENT":"1"}
## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Try to perform click by coordinates

**Comment by sunmoondeer** [comment]
I used followed code:
new TouchAction(driver)
	    .tap(TapOptions.tapOptions()
	   .withElement(ElementOption.element(element))).waitAction(WaitOptions.waitOptions(Duration.ofSeconds(3))).release().perform();
and it return 

JSONWP error code 13 to UnknownError
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"value":"Failed to execute touch event","status":13}
[debug] [W3C (13b1b0f0)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Failed to execute touch event
[debug] [W3C (13b1b0f0)]     at errorFromMJSONWPStatusCode (C:\Users\Mint\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:789:10)
[debug] [W3C (13b1b0f0)]     at Socket.socketClient.on.data (C:\Users\Mint\AppData\Roaming\npm\node_modules\appium\node_modules\appium-android-driver\lib\bootstrap.js:139:18)
[debug] [W3C (13b1b0f0)]     at Socket.emit (events.js:198:13)
[debug] [W3C (13b1b0f0)]     at addChunk (_stream_readable.js:288:12)
[debug] [W3C (13b1b0f0)]     at readableAddChunk (_stream_readable.js:265:13)
[debug] [W3C (13b1b0f0)]     at Socket.Readable.push (_stream_readable.js:224:10)
[debug] [W3C (13b1b0f0)]     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

**Comment by mykola-mokhnach** [comment]
This is not tap by coordinates ^

**Comment by sunmoondeer** [comment]
followed you suggest, the code is 
TouchAction actions =new TouchAction(driver);
actions.tap(PointOption.point(50,120)).waitAction(WaitOptions.waitOptions(Duration.ofSeconds(1))).perform();

the element bounds is [0,68][136,110] in Uiautomatoerview

And I got 
HTTP] --> POST /wd/hub/session/0851a61f-612c-4385-aec3-610c29e0d54b/touch/perform
[HTTP] {"actions":[{"action":"tap","options":{"x":50,"y":120}},{"action":"wait","options":{"ms":1000}}]}
[debug] [W3C (0851a61f)] Calling AppiumDriver.performTouch() with args: [[{"action":"tap","options":{"x":50,"y":120}},{"action":"wait","options":{"ms":1000}}],"0851a61f-612c-4385-aec3-610c29e0d54b"]
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"click","params":{"x":50,"y":120}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"click","params":{"x":50,"y":120}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: click
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Display bounds: [0,0][720,1208]
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":true}
[debug] [W3C (0851a61f)] Responding to client with driver.performTouch() result: null


It seems linke the performTouch failed.

So could you please offer me an example how to do?
Other question, The appium support react native framework from fackbook? If the app develop with react native, the all resourc-id are missing, it bing so much diffculity to locate the element.

**Comment by mykola-mokhnach** [comment]
> So could you please offer me an example how to do?

The above code is correct (although wait is not needed for a single tap or it should be set less than 100ms to be accepted as a single tap).

> Other question, The appium support react native framework from fackbook? If the app develop with react native, the all resourc-id are missing, it bing so much diffculity to locate the element.

This is the problem of react itself that resource ids cannot be set. Appium is simply a proxy between your code and UiAutomator framework. If this was Android version 5+ then I would recommend switching to UiAutomator2 or Espresso/using W3C actions, but on 4.4 there not many options to choose.

**Comment by sunmoondeer** [comment]
I switch to UiAutomator2 like this:
1、capabilities.setCapability("automationName", "UiAutomator2");
2、import uiautomator-v18-2.1.1-release-no-dep.jar

The log shows that I have found the element correctly.
[debug] [WD Proxy] Proxying [POST /element] to [POST http://localhost:8200/wd/hub/session/2409c71d-6cae-4799-9a91-9f1ff90eb7ff/element] with body: {"strategy":"xpath","selector":"//android.view.ViewGroup[@index='0']","context":"","multiple":false}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"2409c71d-6cae-4799-9a91-9f1ff90eb7ff","status":0,"value":{"ELEMENT":"3797e1ea-6eb3-492b-9e1e-45d0e822632d"}}
[debug] [W3C (cb4356b0)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"3797e1ea-6eb3-492b-9e1e-45d0e822632d","ELEMENT":"3797e1ea-6eb3-492b-9e1e-45d0e822632d"}

But when I perform tap action, it also faield

[HTTP] --> POST /wd/hub/session/cb4356b0-6e9b-45c1-b6f9-e5796ef506ce/touch/perform
[HTTP] {"actions":[{"action":"tap","options":{"x":50,"y":120}},{"action":"wait","options":{"ms":1000}}]}
[debug] [W3C (cb4356b0)] Calling AppiumDriver.performTouch() with args: [[{"action":"tap","options":{"x":50,"y":120}},{"action":"wait","options":{"ms":1000}}],"cb4356b0-6e9b-45c1-b6f9-e5796ef506ce"]
[debug] [WD Proxy] Proxying [POST /appium/tap] to [POST http://localhost:8200/wd/hub/session/2409c71d-6cae-4799-9a91-9f1ff90eb7ff/appium/tap] with body: {"x":50,"y":120}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"2409c71d-6cae-4799-9a91-9f1ff90eb7ff","status":0,"value":true}
[debug] [W3C (cb4356b0)] Responding to client with driver.performTouch() result: null

Why it return null for the  driver.performTouch(), what does it mean for the null?

**Comment by mykola-mokhnach** [comment]
I would enable assistive touch and add additional debug logging to the app under test to see what's happening there and why the click is not accepted.
