### ISSUE TITLE
I have already set PATH Variable for Carthage exist but still getting same error.

### ISSUE THREAD

**Issue by aruvimal** [appium/appium#12904]
I have already set PATH Variable for Carthage exist but still getting same error. 

Below is my bash Profile
**export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home
export M2_HOME=/Users/vz8zw5/apache-maven-3.6.1
export PATH=$PATH:$M2_HOME/bin
export PATH=$PATH:$JAVA_HOME/bin
export ANDROID_HOME=/Users/vz8zw5/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
export PATH=$PATH:/usr/local/bin/carthage
export PATH=$PATH:/usr/bin:/bin:/usr/sbin:/sbin
export PATH=/usr/local/bin:$PATH**

echo $PATH
/usr/local/bin:./node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/vz8zw5/.rvm/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/Users/vz8zw5/apache-maven-3.6.1/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/bin:/Users/vz8zw5/Library/Android/sdk/tools:/Users/vz8zw5/Library/Android/sdk/platform-tools:/usr/local/bin/carthage:/usr/bin:/bin:/usr/sbin:/sbin

_Originally posted by @aruvimal in https://github.com/appium/appium/issues/12903#issuecomment-511119660_

**Comment by KazuCocoa** [comment]
Did Appium process also refer to the PATH?

**Comment by aruvimal** [comment]
yes. In MAC OS,  i have seen that path variable setting in Terminal/ bash profile/ etc/path folder is not available in eclipse or any GUI Application. Is it?

**Comment by aruvimal** [comment]
Value System.out.println(System.getenv("PATH")) also returning /usr/bin:/bin:/usr/sbin:/sbin. Do you know to set value globally.

**Comment by KazuCocoa** [comment]
It depends on your preference. Maybe, your env has its PATH preferences.
You could ask it in https://discuss.appium.io

**Comment by suleymanyukseluk** [comment]
please use :
environment.put("PATH", "PUT THE  OUTPUT OF "ECHO $PATH HERE" + System.getenv("PATH"));
