### ISSUE TITLE
Carthage binary is not found

### ISSUE THREAD

**Issue by aruvimal** [appium/appium#12903]
## The problem

Getting below error though Carthage is installed properly.

### ****35m[XCUITest][39m Error: Carthage binary is not found. Install using `brew install carthage` if it is not installed and make sure the root folder, where carthage binary is installed, is present in PATH environment variable.** The current PATH value: '/usr/bin:/bin:/usr/sbin:/sbin'
[35m[XCUITest][39m     at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[35m[XCUITest][39m     at errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/wda/utils.js:71:9)
[35m[XCUITest][39m Error: Carthage binary is not found. Install using `brew install carthage` if it is not installed and make sure the root folder, where carthage binary is installed, is present in PATH environment variable. The current PATH value: '/usr/bin:/bin:/usr/sbin:/sbin'
[35m[XCUITest][39m     at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[35m[XCUITest][39m     at errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/wda/utils.js:71:9)**

**********************************************************

## Environment
info AppiumDoctor Appium Doctor v.1.11.1
info AppiumDoctor ### Diagnostic for necessary dependencies starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: /usr/local/bin/node
info AppiumDoctor  ✔ Node version is 12.6.0
info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ Xcode Command Line Tools are installed in: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ DevToolsSecurity is enabled.
info AppiumDoctor  ✔ The Authorization DB is set up properly.
info AppiumDoctor  ✔ Carthage was found at: /usr/local/bin/carthage. Installed version is: 0.33.0
info AppiumDoctor  ✔ HOME is set to: /Users/vz8zw5
info AppiumDoctor  ✔ ANDROID_HOME is set to: /Users/vz8zw5/Library/Android/sdk
info AppiumDoctor  ✔ JAVA_HOME is set to: /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home
info AppiumDoctor  ✔ adb exists at: /Users/vz8zw5/Library/Android/sdk/platform-tools/adb
info AppiumDoctor  ✔ android exists at: /Users/vz8zw5/Library/Android/sdk/tools/android
info AppiumDoctor  ✔ emulator exists at: /Users/vz8zw5/Library/Android/sdk/tools/emulator
info AppiumDoctor  ✔ Bin directory of $JAVA_HOME is set
info AppiumDoctor ### Diagnostic for necessary dependencies completed, no fix needed. ###
info AppiumDoctor 
info AppiumDoctor ### Diagnostic for optional dependencies starting ###
WARN AppiumDoctor  ✖ opencv4nodejs cannot be found.
WARN AppiumDoctor  ✖ ffmpeg cannot be found
WARN AppiumDoctor  ✖ mjpeg-consumer cannot be found.
WARN AppiumDoctor  ✖ idb and idb_companion are not installed
WARN AppiumDoctor  ✖ applesimutils cannot be found
WARN AppiumDoctor  ✖ idevicelocation cannot be found
WARN AppiumDoctor  ✖ ios-deploy cannot be found
WARN AppiumDoctor  ✖ ios_webkit_debug_proxy cannot be found
WARN AppiumDoctor  ✖ ifuse cannot be found
WARN AppiumDoctor  ✖ bundletool.jar cannot be found
info AppiumDoctor ### Diagnostic for optional dependencies completed, 10 fixes possible. ###
info AppiumDoctor 
info AppiumDoctor ### Optional Manual Fixes ###
info AppiumDoctor The configuration can install optionally. Please do the following manually:
WARN AppiumDoctor  ➜ Why opencv4nodejs is needed and how to install it: https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/image-comparison.md
WARN AppiumDoctor  ➜ ffmpeg is needed to record screen features. Please read https://www.ffmpeg.org/ to install it
WARN AppiumDoctor  ➜ mjpeg-consumer module is required to use MJPEG-over-HTTP features. Please install it with 'npm i -g mjpeg-consumer'.
WARN AppiumDoctor  ➜ Why idb is needed and how to install it: https://github.com/appium/appium-idb
WARN AppiumDoctor  ➜ Why applesimutils is needed and how to install it: http://appium.io/docs/en/drivers/ios-xcuitest/
WARN AppiumDoctor  ➜ idevicelocation is used to set geolocation for real device. Please read https://github.com/JonGabilondoAngulo/idevicelocation to install it
WARN AppiumDoctor  ➜ ios-deploy is used to install iOS applications to real device. Please read http://appium.io/docs/en/drivers/ios-xcuitest-real-devices/ to install it
WARN AppiumDoctor  ➜ ios_webkit_debug_proxy is used to proxy requests from Appium to MobileSafari running on real device. Please read https://github.com/google/ios-webkit-debug-proxy to install it
WARN AppiumDoctor  ➜ ifuse is used to manage files/folders against a real device. Please read https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios/ios-xctest-file-movement.md to install it
WARN AppiumDoctor  ➜ bundletool.jar is used to handle Android App Bundle. Please read http://appium.io/docs/en/writing-running-appium/android/android-appbundle/ to install it
info AppiumDoctor 
info AppiumDoctor ###
info AppiumDoctor 
info AppiumDoctor Bye! Run appium-doctor again when all manual fixes have been applied!
info AppiumDoctor 

*****************************************
**$ brew install carthage**
Updating Homebrew...
Warning: carthage 0.33.0 is already installed and up-to-date
To reinstall 0.33.0, run `brew reinstall carthage`

**Comment by mykola-mokhnach** [comment]
>  '/usr/bin:/bin:/usr/sbin:/sbin'

As you can see the PATH variable visible to your process does not contain the folder where carthage exists (usually /usr/local/bin). Make sure to fix the environment for your server process. Check https://github.com/appium/java-client/blob/master/docs/environment.md for more details.

Closed as not an issue.

**Comment by aruvimal** [comment]
I have already set PATH Variable for Carthage exist but still getting same error. 

Below is my bash Profile
**export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home
export M2_HOME=/Users/vz8zw5/apache-maven-3.6.1
export PATH=$PATH:$M2_HOME/bin
export PATH=$PATH:$JAVA_HOME/bin
export ANDROID_HOME=/Users/vz8zw5/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
export PATH=$PATH:/usr/local/bin/carthage
export PATH=$PATH:/usr/bin:/bin:/usr/sbin:/sbin
export PATH=/usr/local/bin:$PATH**

echo $PATH
/usr/local/bin:./node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/vz8zw5/.rvm/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/Users/vz8zw5/apache-maven-3.6.1/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/bin:/Users/vz8zw5/Library/Android/sdk/tools:/Users/vz8zw5/Library/Android/sdk/platform-tools:/usr/local/bin/carthage:/usr/bin:/bin:/usr/sbin:/sbin
