### ISSUE TITLE
After upgrade to 1.14.0. Getting error Failed to launch Appium Settings app:

### ISSUE THREAD

**Issue by rajesh-dhiman** [appium/appium#12901]
## The problem
Hi

I upgraded from appium 1.7.2 to 1.14.0
After upgrade i am getting following error
**Failed to launch Appium Settings app: Condition unmet after 5370 ms. Timing out.**
  

## Environment

* Appium version : **1.14.0**
* Last Appium version that did not exhibit the issue (if applicable): **1.7.2**
* Desktop OS/version used to run Appium: **Windows 10**
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager: **Npm**
* Mobile platform/version under test: **Tablet with Android  5.1.1**
* Real device or emulator/simulator: **Real Device**
* Appium CLI or Appium.app|exe: **Appium exe**

## Link to Appium logs

Log File
[ADB-Appium Logs.log](https://github.com/appium/appium/files/3387970/ADB-Appium.Logs.log)

## Code To Reproduce Issue [ Good To Have ]

Capabilities.SetCapability("automationName", "UiAutomator1");
            Capabilities.SetCapability("deviceName", "Android Tablet"); 
            Capabilities.SetCapability("platformName", "Android");
            Capabilities.SetCapability("platformVersion", "5.1.1"); 
            Capabilities.SetCapability("appPackage", "XXXXXXXXXXX"); 
            Capabilities.SetCapability("appActivity", "XXXXXXXXXXX");
            Capabilities.SetCapability("noReset", true);  
            Capabilities.SetCapability("fullReset", false);  
            Capabilities.SetCapability("newCommandTimeout", "5000");
            Capabilities.SetCapability("dontStopAppOnReset", true); 
            Capabilities.SetCapability("intentCategory", "android.intent.category.HOME");

**Comment by mykola-mokhnach** [comment]
Are you able to start settings manually with `adb.exe -P 5037 -s 190339d4eacb3688 shell am start -n io.appium.settings/.Settings -a android.intent.action.MAIN -c android.intent.category.LAUNCHER` command?

Are there any crashes or error present in logcat output?

**Comment by phatle1** [comment]
Faced the same problem but on emulator(bluestacks), any help?

**Comment by rajesh-dhiman** [comment]
Hi 

I can see Appium Settings apps launching on tablet.

I think it is not able the garb the  process by this command

[debug] [ADB] Running 'C:\Users\XXXXXXXXXX\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037 -s 190339d4eacb3688 shell pgrep \^appium\\.settings\$'

**However if I run the above command manually on command prompt it returns the process id.**

It seams it i snot able to grab the process, which is running.

**Comment by mykola-mokhnach** [comment]
How about the logcat output?

**Comment by rajesh-dhiman** [comment]
I do not see anything on Logcat output..

**Comment by mykola-mokhnach** [comment]
Unfortunately without logs there is nothing more we can do there. Try another device as a workaround.

**Comment by rajesh-dhiman** [comment]
I have logcat output.. But This issue is closed... So opening new issue

**Comment by dadiqiu2014** [comment]
请问，大家解决这个问题了吗？

**Comment by verbinpro** [comment]
i have the same issue.

An error occurs on:
appium 1.14.2 + memu emulator (android 5.1.1)

But it works well on
appium 1.14.2 + memu emulator (android 7.1)

**Comment by tykuyh** [comment]
> Unfortunately without logs there is nothing more we can do there. Try another device as a workaround.

The same problem in 1.15.1, Appium can't get the result of command "adb.exe -P 5037 -s 190339d4eacb3688 shell pgrep ^appium\.settings$"
but it works when I manually execute it.
I think may be some problems in the version of sdk?

**Comment by rajesh-dhiman** [comment]
I think  Appium team gave up. They are not able fix it. i am stuck with appium 1.7.2 (where it works)..
@mykola-mokhnach if you guys cannot fix it, please escalate to next level..

**Comment by mykola-mokhnach** [comment]
We are the last level ;)

https://github.com/appium/appium-adb/pull/472, which was merged to appium@beta could be helpful there

**Comment by rajesh-dhiman** [comment]
Thanks @mykola-mokhnach . Yes the android devices we have are 5.1.1 . So As per https://github.com/appium/appium-adb/pull/472 this will get fixed. In which Version of Appium i can expect the fix?
