### ISSUE TITLE
Appium not able to load some page of android application

### ISSUE THREAD

**Issue by abhinavrakesh** [appium/appium#12918]
Appium not able to load some of the page of android application, it keep loading but not able to land.

## Environment

* Appium version (or git revision) that exhibits the issue:
1.13.0, and older
* Last Appium version that did not exhibit the issue (if applicable): 
Still issue is there with latest version
* Desktop OS/version used to run Appium:
1.13.0
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
Android 7.0.1
* Real device or emulator/simulator:
Real device
* Appium CLI or Appium.app|exe:

## Details

The Android application I am testing behaving not well, some of the page is not getting load,
Like page A is login page after completing login it should land to page B but if I try to load page B it keep loading not able to load the page, but it i perform some other manual click on the real device then the page get loaded,

Manually I am able to perform testing but using appium page B not getting loaded until I click manually some other elements on that page B.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by abhinavrakesh** [comment]
Please provide some way-out

**Comment by mykola-mokhnach** [comment]
Please attach the server logs
