### ISSUE TITLE
[iOS] Got 10054 error while try to locate some element sometimes

### ISSUE THREAD

**Issue by shockingqian** [appium/appium#12916]
Hi Team,

In our test lab, we run into an issue that appium will drop http connection random, it make our automation test very unstable.

Issue is 100% to reproduce in this app (Netgear Insight Manager) but it's hard to reproduce if we use other apps.  It's more easy to reproduce on Appium-Python-Client-0.46 then Appium-Python-Client-0.40.

Step to reproduce:
1. Launch app,  click an element to open next windows
2. Check element via find_element_by_accessibility_id **before** new windows stopping render

appium log shows error:
('Connection aborted.', error(10054, 'An existing connection was forcibly closed by the remote host'))

We have captured http request of appium between ios & client, please check wda-reset.pcap
There is no wait/snap time between the frame #17 and #16 (followed at the same time). It seems wda return error while user try to locate this element.

Please kindly advise us how to avoid such issue.
Thank you all for your time.

BR, 

## Environment

* Appium version (or git revision) that exhibits the issue:  1.14
* Desktop OS/version used to run Appium: windows 10
* Mobile platform/version under test: ios12
* Real device or emulator/simulator: real device

[wda-reset.zip](https://github.com/appium/appium/files/3396129/wda-reset.zip)

**Comment by mykola-mokhnach** [comment]
Can you please provide the server log with iOS logging enabled?

**Comment by mykola-mokhnach** [comment]
also make sure the usbmuxd package is up to date. There was a known bug there, which was fixed recently
