### ISSUE TITLE
Can't fine element on page 

### ISSUE THREAD

**Issue by FirstAM** [appium/appium#12910]
## The problem

Hello , Appium can't find element in screen google autorization popup ( I think is it not webview, becouse get_context return only NATIVE_APP) But when i do coommand "get_source" i see all this elements , which appium can't find, and elements do not invisible
Driver Uiautomation2

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.0
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: appium js 
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager: 
* Mobile platform/version under test: android
* Real device or emulator/simulator: real
* Appium CLI or Appium.app|exe:

## Details

I tried to find elements by id:
Like that 
id => profileIdentifier
or that 
id => com.google.android.gms:id/profileIdentifier

By text :
Like that 
text => "Этот сайт или приложение сможет получить доступ к конфиденциальной информации. Ознакомьтесь с "

I find class elements , but this is bad locators for my case

Appium log 
[appium_logs_fc99d2777d44_86.txt](https://github.com/appium/appium/files/3392808/appium_logs_fc99d2777d44_86.txt)

Response get source 
[get_source.txt](https://github.com/appium/appium/files/3392790/get_source.txt)

What interesting , appium desktop inspector find this elements and use their , but node js appium can't do same

In Appium Desktop i used Uiautomation 1 because start Uiautomator2 with Appium Desktop and Linux - unreal it's a big bucket of problem of problem one by one.

**Comment by mykola-mokhnach** [comment]
Try to find the element by xpath, since the same tree is used for both source output and for xpath search. The native UIA2 lookup implementation is used for other locator types, so either there is an issue in the framework itself, or your automation code should just wait longer for these elements to appear

**Comment by FirstAM** [comment]
I tried to use xpath but for some devices xpath don't work =(

**Comment by mykola-mokhnach** [comment]
I don't think there is anything more we can do from Appium side since elements location is performed by UiAutomator itself. Although, you can also try Espresso driver and see if it performs better.
