### ISSUE TITLE
GET /window/size return unrecognized selector error

### ISSUE THREAD

**Issue by EvanChen1989** [appium/appium#12912]
## The problem

I'm trying to set up a test environment over ios simulator with appium. But it gives unrecognized selector error after I see the application is installed. 

## Environment

* Appium version 1.14 
* MacOS 10.14.5
* Npm manager
* Mobile platform/version under test: iPhone 8 iOS 13.0
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: both

## Details

I can see simulator launched and app uninstalled then reinstalled. But the driver initialization fails just after that. The code fails with "An unknown server-side error occurred while processing the command. Original error: -[XCApplicationQuery elementSnapshotForDebugDescription]: unrecognized selector sent to instance 0x600001b066a0". And I also see some ADB log for Android there, is that expected?
Also tried sample app and my own app, behaves the same.

## Link to Appium logs

https://gist.github.com/EvanChen1989/ea71028164a9da307dcde86b811c5e1b

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

String app = "/Users/evan/Desktop/test.app";
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability("platformName", MobilePlatform.IOS);
capabilities.setCapability("deviceName","iPhone 8");
capabilities.setCapability(MobileCapabilityType.APP, app);
capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");
capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "13.0");
IOSDriver driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);

**Comment by KazuCocoa** [comment]
What about running with `appium@beta`?
It has Xcode 11 support.

**Comment by EvanChen1989** [comment]
> What about running with `appium@beta`?
> It has Xcode 11 support.

It's such a simple cause that I missed it! I just tried with xcode 10 and seems the problem is gone. Thanks for the reply! 

BTW, is there anywhere that I can check for the appium support matrix or suggest version to work with? I was facing similar issue when setting up my android environment with various combinations of appium & selenium java package that with many unexpect behaviors....

**Comment by KazuCocoa** [comment]
👍 

---

> is there anywhere that I can check for the appium support matrix or suggest version to work with? 

So far, we address minimal support version/environment like http://appium.io/docs/en/drivers/ios-xcuitest/ by the latest Appium version. Newer version like Xcode 11 has been mentioned in changelog.

**Comment by EvanChen1989** [comment]
> Do you expect upper version, too?
> (Or each Appium versions also not only the latest one but also previous versions?)

If possible, yes. I think it would be better to mention the upper limit for LTS. Just a mention that xcode 11 or iOS 13.0 should go to appium beta should be sufficient. Tough it's quite quite clear when you get the point of beta :D But it could cost time since there's no explict instruction.

**Comment by KazuCocoa** [comment]
I see. Created an issue as a documentation improvement.

Thanks :)

**Comment by shopexdream** [comment]
I met the same problem,can Appium-mac-1.14.0-beta.1.dmg fix this problem?

**Comment by EvanChen1989** [comment]
> I met the same problem,can Appium-mac-1.14.0-beta.1.dmg fix this problem?

Nope, I fixed this issue by downgrading XCode to 10 since I'd prefer a more stable version. I think it's worth a try since beta version was mentioned specifically.

**Comment by RohithChevvakula** [comment]
@EvanChen1989 , @KazuCocoa 
Hello,
I'm facing the _/window/size return unrecognized selector error_ when try to create an appium session. 
My configuration is as follows:
appium : 1.14.2
xcode : 11
real ipad (ios) : 13.0

My requirement is to automate my tests for my app on ios 13.0 and above.
Please help.
