### ISSUE TITLE
Unable to do a controlled swipe -ios

### ISSUE THREAD

**Issue by fdPoornima** [appium/appium#12917]
## The problem

I am trying to perform an upward swipe on a native ios app so that i can click on an element, but the swipe does not do one page up, the app swipe happens over a few pages so that I miss the element I am trying to click.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.13.0-beta.1
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: MAC OS mojave 10.14.3 
* Node.js version (unless using Appium.app|exe): v8.11.2
* Npm or Yarn package manager: v8.11.2
* Mobile platform/version under test: ios version 12.1.2 
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Details
 I tried to do the same by using touchaction and also swipe from a coordinate to coordinate, none of it seems to work. 

the following code does not move the screen at all 
                    Dimension dimension = driver.manage().window().getSize();
                    Double scrollheightstart = dimension.getHeight()*0.5;
                    int scrollstart = scrollheightstart.intValue();
                    Double scrollheightend = dimension.getHeight()*0.2;
                    int scrollend = scrollheightend.intValue();
                    new TouchAction((PerformsTouchActions)driver)
                            .press(PointOption.point(0,scrollstart))
                            .waitAction(WaitOptions.waitOptions(Duration.ofSeconds(2)))
                            .moveTo(PointOption.point(0,scrollend))
                            .release().perform();

Also tried the following - does not move the screen at all
PointOption location = PointOption.point(170 , 470);
PointOption location2 = PointOption.point(170 , 480);
TouchAction action = (new TouchAction(driver));
                    action.press(location);
                    action.moveTo(location2);
                    action.release();
                    action.perform();

## Link to Appium logs

https://gist.github.com/fdPoornima/3f47ea0cd37ccddcd1801358cbc39a45

## Code To Reproduce Issue [ Good To Have ]

This code does the swipe, but the swipe is uncontrolled, so I am missing the portion of the page that I need as it goes up before the swipe completes

try {
            for (int iSwipeIterator = 0; iSwipeIterator < 5; iSwipeIterator++) {
                if (!(isElementVisible(element))) {
                    JavascriptExecutor js = driver;
                    HashMap<String, String> swipeObject = new HashMap<>();
                    swipeObject.put("direction", direction.toString());
                    js.executeScript("mobile: swipe", swipeObject);

                    try {
                        Thread.sleep(3000);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                } else
                    break;
            }
        }catch(NoSuchElementException e)
        {
            log.info("The element is not found "+e);
        }

**Comment by mykola-mokhnach** [comment]
Closed as incomplete.

**Comment by fdPoornima** [comment]
I was editing it, didnt realize it got created already. WIll raise another one?

**Comment by mykola-mokhnach** [comment]
no need, thanks for the update

**Comment by mykola-mokhnach** [comment]
> Also tried the following - does not move the screen at all

There must be wait after press

**Comment by mykola-mokhnach** [comment]
I don't find `mobile: swipe` or `mobile: scroll` very reliable for you purpose. The approach with TouchActions is ok, although I would do small swipes and verify whether we are on the correct page after each swipe.

**Comment by fdPoornima** [comment]
Thanks for respoding. I will try touchactions in small swipes with wait and post the output.

**Comment by fdPoornima** [comment]
I modified the touchaction with waittime after press as below.

TouchAction action = (new TouchAction(driver));
                    action.press(location);
                    action.waitAction(WaitOptions.waitOptions(Duration.ofSeconds(2)));
                    action.moveTo(location2);
                    action.release();
                    action.perform();

 Still no action happens. Please find the appium logs as https://gist.github.com/fdPoornima/759515b77f65a36af429229c868bd8de

**Comment by fdPoornima** [comment]
is there another method to do small swipes?

**Comment by fdPoornima** [comment]
Doing the swipe on the Appium.app also does not produce any result.

(new TouchAction(driver))
  .press({x: 137, y: 563})
  .moveTo({x: 134: y: 413})
  .release()
  .perform()

Logs as below
[debug] [WD Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"width\" : 375,\n    \"height\" : 667\n  },\n  \"sessionId\" : \"816036DF-D55C-4557-BBA4-63B6F8BAED50\",\n  \"status\" : 0\n}"
[debug] [XCUITest] Connection to WDA timed out
[debug] [XCUITest] Connection to WDA timed out
[debug] [MJSONWP (0adca868)] Responding to client with driver.getWindowSize() result: {"width":375,"height":667}
[HTTP] <-- GET /wd/hub/session/0adca868-995e-4f40-bcac-678bef404100/window/current/size 200 14057 ms - 98
[HTTP] 
[HTTP] --> POST /wd/hub/session/0adca868-995e-4f40-bcac-678bef404100/touch/perform
[HTTP] {"actions":[{"action":"press","options":{"x":137,"y":563}},{"action":"moveTo","options":{"x":134,"y":413}},{"action":"release","options":{}}]}
[debug] [MJSONWP (0adca868)] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":137,"y":563}},{"action":"moveTo","options":{"x":134,"y":413}},{"action":"release","options":{}}],"0adca868-995e-4f40-bcac-678bef404100"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: press(options={"x":137,"y":563})-moveTo(options={"x":134,"y":413})-release(options={})
[debug] [WD Proxy] Proxying [POST /wda/touch/perform] to [POST http://localhost:8100/session/816036DF-D55C-4557-BBA4-63B6F8BAED50/wda/touch/perform] with body: {"actions":[{"action":"press","options":{"x":137,"y":563}},{"action":"moveTo","options":{"x":134,"y":413}},{"action":"release","options":{}}]}
[debug] [XCUITest] Connection to WDA timed out
[debug] [iProxy] recv failed: Operation not permitted
[debug] [WD Proxy] Got response with status 200: {"value":{},"sessionId":"816036DF-D55C-4557-BBA4-63B6F8BAED50","status":0}
[debug] [MJSONWP (0adca868)] Responding to client with driver.performTouch() result: {}

**Comment by fdPoornima** [comment]
I have solved the issue now, the below code works. 

new TouchAction(driver).longPress(PointOption.point(startX, startY))
                    .moveTo(PointOption.point(endX, endY))
                    .release().perform();

so this is longpress rather than press. Appium desktop app ( 1.14.0) still generated code with Press which doesnt work.
