### ISSUE TITLE
Flutter support for Appium

### ISSUE THREAD

**Issue by truongsinh** [appium/appium#12919]
# Update

Prototype available at https://www.npmjs.com/package/appium-flutter-driver but we need support from appium declaration first.

## The problem

Flutter goes with `flutter drive`, the e2e test tool, but it does not work with app that has both flutter view and native view (such as embedding Flutter to existing app), or flutter view with web view (open a webview in Flutter).

Having appium flutter driver would solve both problems above, similar to http://appium.io/docs/en/writing-running-appium/web/hybrid/

Related issues:
- https://github.com/flutter/flutter/issues/36259
- https://github.com/google/EarlGrey/issues/778
- https://github.com/flutter/flutter/issues/32987
- https://github.com/flutter/flutter/issues/25465
- https://github.com/flutter/flutter/issues/17988
- https://github.com/flutter/flutter/issues/32062#issuecomment-489449584
- https://github.com/flutter/flutter/issues/22809

**Comment by umutuzgur** [comment]
Hi @truongsinh. That is a really nice idea but I don't think we have that many resources. Have you contacted the Flutter team to integrate their driver with the Appium project? There are already some drivers which are developed externally from the Appium team but integrated into the Appium project

**Comment by truongsinh** [comment]
@umutuzgur I created https://github.com/flutter/flutter/issues/36259 . Meanwhile, can you show me to some documentation to get started with developing 3rd party Appium driver, and also some examples?

**Comment by truongsinh** [comment]
related threads: https://github.com/google/EarlGrey/issues/778, https://github.com/flutter/flutter/issues/32987

**Comment by truongsinh** [comment]
related threads: https://github.com/flutter/flutter/issues/25465

**Comment by umutuzgur** [comment]
@truongsinh I will ask around where the documentation is for the custom drivers but in the mean time, these are some of the custom drivers [appium-youiengine-driver](https://github.com/YOU-i-Labs/appium-youiengine-driver), [appium-tizen-driver](https://github.com/Samsung/appium-tizen-driver)

**Comment by mykola-mokhnach** [comment]
Linking https://github.com/flutter/flutter/issues/17988

**Comment by KazuCocoa** [comment]
linking https://github.com/flutter/flutter/issues/32062#issuecomment-489449584
Espresso->Flutter like Espresso->Web

**Comment by truongsinh** [comment]
@umutuzgur one more question, does the driver have to be in JS, or it can be in other languages?

**Comment by umutuzgur** [comment]
@truongsinh I should be JS. I don't know if you can transpile Dart to JS but that would also work I think

**Comment by truongsinh** [comment]
@umutuzgur https://www.npmjs.com/package/appium-flutter-driver first prototype, working with both iOS and Android with limited commands (get text and tap only). But we need to declare this package in appium source code.

**Comment by KazuCocoa** [comment]
Awesome, @truongsinh 

It's out of my curiosity.
Do you have any idea about which is better to communicate with DartVM directory or launch an http server for flutter_driver on app like [this](https://github.com/KazuCocoa/proto-flutter-driver-server) and communicate with it like appium-uiautomator2-driver/uiautomator2-server, xcuitest-driver/WebDriverAgent and espresso-driver/espresso-server?

Because flutter_driver has knowledge for flutter like https://github.com/flutter/flutter/blob/b712a172f9694745f50505c93340883493b505e5/packages/flutter_driver/lib/src/driver/driver.dart#L770-L821 

I considered which way was better for them.

**Comment by truongsinh** [comment]
@KazuCocoa at the moment both approaches are highly experimental thus I don't have a strong idea 😁. Though do you think the http server approach can do context-aware commands (some commands sent to native view, some to web view, some to Flutter view), and on iOS real devices (I understand that http server approach install another http server app on device under test, and it's always painful to install anything on iOS real devices).

On the other hand,  Dart VM Service Protocol with extension ext.flutter.driver is undocumented protocol, thus direct communication to Dart VM might have broken changes in the future if the Flutter team refactor their code.

**Comment by KazuCocoa** [comment]
Thanks :)
I was thinking to build it similar to https://github.com/appium/appium-espresso-driver , eventually.
The server communicates with appium-flutter-driver written in JS extends base driver. Clients communicate with the appium-flutter-driver. The appium-flutter-driver handles context, flutter or android/ios in the layer.
I haven't considered iOS real device much yet... As you also addressed _highly experimental_, mine is also very prototype :)

> On the other hand,

yeah...

**Comment by KazuCocoa** [comment]
We can probably catch up with communication protocol with Dart VM between flutter_driver <=> dart vm by their tests => https://github.com/flutter/flutter/tree/180aa0c0b1fc645aa661a9aeedc21ed91c93ad00/packages/flutter_driver/test

here also.
https://github.com/flutter/flutter/blob/4e4b9bd0b1ae094d4c837c8cd6d318d15be7fe40/packages/flutter_driver/lib/src/extension/extension.dart

**Comment by truongsinh** [comment]
Thanks, this really helps, so far I have been doing reverse engineering with `FlutterDriver.connectedTo(printCommunication: true)` 😂

**Comment by truongsinh** [comment]
@KazuCocoa @mykola-mokhnach could you take a look at #12945?

**Comment by KazuCocoa** [comment]
Btw, is there any known limitation for https://github.com/truongsinh/appium-flutter-driver ?

e.g. it can run only debug mode, only on simulator etc...

**Comment by truongsinh** [comment]
> Btw, is there any known limitation for https://github.com/truongsinh/appium-flutter-driver ?
> 
> e.g. it can run only debug mode, only on simulator etc...

Currently the API is very limited, as documented in https://github.com/truongsinh/appium-flutter-driver#finders and at https://github.com/truongsinh/appium-flutter-driver#finders . I have been able to run the examples on Android emulator, Android real device (Pixel 2), iOS emulator.

I haven't run on iOS real device yet. As for mode, do you mean flutter mode or Android/iOS mode? Does it make sense to run test on non-debug mode :-? Anyway, as long as there's `enableFlutterDriverExtension`, we can control the Flutter app.

**Comment by jlipps** [comment]
@truongsinh this is a great idea. If you get me your e-mail somehow I will invite you to the appium developer slack chat, for this kind of thing sometimes real time communication is easier. DM @jlipps on twitter might be a good channel.

**Comment by truongsinh** [comment]
> @truongsinh this is a great idea. If you get me your e-mail somehow I will invite you to the appium developer slack chat, for this kind of thing sometimes real time communication is easier. DM @jlipps on twitter might be a good channel.

DM'ed

**Comment by truongsinh** [comment]
> We should call screenshot via ios/android drivers since flutter 's take screenshot is calling commands outside dart vm. e.g. https://github.com/flutter/flutter/search?p=4&q=screenshot&unscoped_q=screenshot

@KazuCocoa I published [v0.0.5](https://www.npmjs.com/package/appium-flutter-driver/v/0.0.5) with screenshot functionality. Actually we can have screenshot both from Dart VM and via jwproxy, depends on the needs. Screenshot from Dart VM is pure app, while screenshot via jwproxy may have extraneous element like top and bottom bar, as seen from these screenshots

**Comment by KazuCocoa** [comment]
Thanks 👍 https://github.com/appium/appium/issues/12919#issuecomment-513843596

Ah, okay.
Appium has commands like http://appium.io/docs/en/commands/mobile-command/
We can use either way as the command like `mobile:viewportScreenshot`.

--

btw, I was able to do _on iOS real devices (I understand that http server approach install another http server app on device under test, and it's always painful to install anything on iOS real devices)_.

**Comment by umutuzgur** [comment]
@truongsinh Should we close this issue since now we can communicate over slack?

**Comment by truongsinh** [comment]
it's true we are communicating over slack, but if we keep this issue open until (1) Flutter is actually supported in Appium, or (2) we make a decision that Appium would not support Flutter, we can easily see the status.

I don't have a strong opinion, how about others?

**Comment by ahashmi24** [comment]
@truongsinh 
do we reach any conclusion? whether appium will support flutter based application? if yes please guide me with the initial setup for appium-flutter-driver or suggest to me if I can set-up appium-flutter-driver without bothering my existing Appium setup.


Many Thanks,
Ahmer

**Comment by stone20130104** [comment]
@ahashmi24 , you can try this,
https://www.npmjs.com/package/appium-flutter-driver
https://github.com/KazuCocoa/proto-flutter-driver-server

**Comment by stone20130104** [comment]
seems lots of us are waiting for appium-flutter-driver, could you please add flutter support in Appium as soon as possible, we are expecting to use it in Appium. Thanks!!!

**Comment by vijaydeepak-rezi** [comment]
> Thanks 👍 [#12919 (comment)](https://github.com/appium/appium/issues/12919#issuecomment-513843596)
> 
> Ah, okay.
> Appium has commands like http://appium.io/docs/en/commands/mobile-command/
> We can use either way as the command like `mobile:viewportScreenshot`.
> 
> --
> 
> btw, I was able to do _on iOS real devices (I understand that http server approach install another http server app on device under test, and it's always painful to install anything on iOS real devices)_.

How can we Run on IOS Real device using Appium-Flutter-Driver . Do we need to make any specific changes in Desired capability ?

**Comment by mykola-mokhnach** [comment]
Closed as fixed

**Comment by gimnguyen** [comment]
I found out this field in flutter **semanticLabel**

When I add this attribute to element. I can interact with that element by: **MobileBy.AccessibilityId("payment")**
It looks like adding an ID to element, right?
However, Text is not fit. Because you can not get text value by this way.
See screenshot below.

![2020-09-30_14h02_05](https://user-images.githubusercontent.com/14172888/94656835-c98e7b80-032a-11eb-8459-b5ef9f74afc6.png)

**Comment by giangthao** [comment]
Hi, I have another question, I have multiple navigation bar tab can't add key, so how can I find correct tab I want to interact with them
