### ISSUE TITLE
WebDriverAgentRunner-Runner.app” to accept incoming network connections

### ISSUE THREAD

**Issue by aruvimal** [appium/appium#12915]
When I launch a test against the iOS simulator I get this system alert always:

Do you want the application “WebDriverAgentRunner-Runner.app” to accept incoming network connections?

Can you please advise how to ignore this alert.

**Comment by mykola-mokhnach** [comment]
This is a standard Mac OS security alert. You can only accept it manually or disable the system firewall to avoid such messages completely.

Please use Appium forum for questions.

**Comment by aruvimal** [comment]
So we have to accept it manually everytime when we run the script or to disable the system firewall completely.

**Comment by pritom007** [comment]
here is a way to automatically accept it in python or just run the osascript
I found it in stackoverflow.
```
        cmd = """tell application "System Events"
                    set frontmost of process "UserNotificationCenter" to true
                    tell process "UserNotificationCenter"
                        if exists button "Allow" of window 1 then
                            repeat while exists button "Allow" of window 1
                                if exists button "Allow" of window 1 then
                                    click button "Allow" of window 1
                                end if
                            end repeat
                        end if
                    end tell
                end tell"""
        subprocess.run(["osascript", "-e", cmd], capture_output=True)
```
