### ISSUE TITLE
Original error: opencv4nodejs module is required to use OpenCV features. Please install it first (npm i -g opencv4nodejs) and restart Appium

### ISSUE THREAD

**Issue by 13817458995** [appium/appium#12925]
## The problem

I have install opencv4nodejs by npm install -g opencv4nodejs.
Run appium-doctor --ios, return opencv4nodejs is installed at: /usr/local/lib. Installed version is: 5.1.0
Start appium desktop and run the test, still return below error message:
An unknown server-side error occurred while processing the command. Original error: opencv4nodejs module is required to use OpenCV features. Please install it first (npm i -g opencv4nodejs) and restart Appium. Read https://github.com/justadudewhohacks/opencv4nodejs#how-to-install for more details on this topic.

How should I install the opencv4nodejs and anything need to be configured?

Appium desktop :1.14.0
MacOS: 10.14.5
opencv4nodejs:5.1.0

**Comment by mykola-mokhnach** [comment]
Are you running Appium from CLI?

**Comment by AjaySinghMeesho** [comment]
yes
