### ISSUE TITLE
iOS parallel test on ingle appium server

### ISSUE THREAD

**Issue by Julioevm** [appium/appium#12921]
## The problem
Considerations for parallel execution of several devices, more than 4, specifically.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14
* Desktop OS/version used to run Appium: macOS 10.14.4
* Node.js version (unless using Appium.app|exe):10.9.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator:Real Device

## Details

This is not so much an issue, more a matter of comment or clarification that I'm looking for, hopefully from more experienced users on this matter.

Most documentation I could find doesn't contemplate running parallel test of more than 2 devices at once, and I ran through some difficulties setting up a more escalable infrastructure for running test in a larger number of devices. Right now I went from 2 to 4 devices, and I managed to keep things stable, but I'm wondering if this is the best way of achieving it, considering I'm planning on increasing the number of devices over time.

So what I'm currently doing is using a single appium server to launch the tests on all four devices, but what I'm noticing is that every test takes an additional ~15 seconds to start, so with 4 devices the 4th one starts running code approximately a minute after the test begins.
Since appium starts the sessions sequentially this is inevitable. So my question is: since there will be an exponentially longer delay with more devices, Should I contemplate having only a certain number of devices per server? Maybe a single server per device? Whats the best take on this?
Playing with certain capability values, I've managed to avoid timeouts and other such errors, but I wonder if these type of errors will become increasingly difficult to handle with more devices.

Maybe it shouldn't normally take this long?

I appreciate any comment you guys have on this subject.

## Code To Reproduce Issue [ Good To Have ]

This is an example of the capabilities I use for a given test:

automationName: XCuiTest
platformName: iOS
platformVersion: 12.3.1
udid: xxxxxxxxxxx
deviceName: iphone5
bundleId: app name
appium:skipLogCapture: true
xcodeSigningId: "iPhone Developer"
xcodeOrgId=xxxxxxx
wdaLaunchTimeout: 240000
wdaConnectionTimeout: 240000
wdaStartupRetries: 2
newCommandTimeout: 360

**Comment by mykola-mokhnach** [comment]
1. Set unique derived data folders for each device (`derivedDataPath` and `usePrebuiltWDA` caps)
2. Prepare WDA profiles for each devices, so it is not necessary to rebuild WDA for each session (`useXctestrunFile` cap)

In general WDA building is the longest operation on session init, which cannot be executed in parallel. Caching/prebuilding WDA can nicely speed up the tests.

**Comment by mykola-mokhnach** [comment]
https://appiumpro.com/editions/77 might also be in use

**Comment by Julioevm** [comment]
@mykola-mokhnach thanks for the quick reply. 
I just tried setting up the derivedDataPath cap and it's a pretty big improvement. Thanks!
I think with such small overhead for each device now it shouldn't be a problem using a single server.

Is useXctestrunFile equivalent to this or does it offer additional benefits?

**Comment by mykola-mokhnach** [comment]
> Is useXctestrunFile equivalent to this or does it offer additional benefits?

You never know unless you try. I can just point general directions, but exact performance details you should figure out on your own.

**Comment by Julioevm** [comment]
It doesn't seem to speed things up any more than usePrebuiltWDA does. 
Thanks for the help!
