### ISSUE TITLE
Unable to switch handles in webview in hybrid Android app

### ISSUE THREAD

**Issue by Flpjak** [appium/appium#12927]
## The problem

As the title says, I've been struggling to use the driver.switchTo().Window() method in the webview context. I am testing a hybrid android app, that has more than one active handle when testing specific pages. I tried using the native context view, but the accessibility is limited on said page. 

This started 2 weeks ago, but the problem has persisted even since the last chromedriver (75.0.3770.140) update.

## Environment

* Appium version: 1.14.0
* Last Appium version that did not exhibit the issue: 1.12.0
* Desktop OS/version used to run Appium: Windows 10
* Mobile platform/version under test: Android 7 and Android 6.0.1
* Real device or emulator/simulator: Android 7 and Android 6.0.1

## Details
I use the w3c protocol, but when i tried to change to mjsonwp, the message i received was the same invalid argument:
`org.openqa.selenium.InvalidArgumentException: invalid argument: 'name' must be a string`

I can see the page elements in chrome inspect in the correct window, but since the method doesn't work and the previous handle doesn't disappear, I cannot do any further testing.

Could this be an issue with dependencies?
[Here's a link to them.](https://gist.github.com/Flpjak/ac4a9e3c40dfb4cbcda1575490ba8766)

Appium log of switchTo window method call

`[HTTP] {"name":"CDwindow-66693896030E59E24509745AA67CC17D"}
[W3C (6c32ae6a)] Driver proxy active, passing request on via HTTP proxy
[WD Proxy] Matched '/wd/hub/session/6c32ae6a-d7b1-44cb-ac28-af596accb489/window' to command name 'setWindow'
[Protocol Converter] Reassigned 'name' value 'CDwindow-66693896030E59E24509745AA67CC17D' to 'handle' as per W3C spec
[WD Proxy] Proxying [POST /wd/hub/session/6c32ae6a-d7b1-44cb-ac28-af596accb489/window] to [POST http://127.0.0.1:8000/wd/hub/session/220e61cec0adc66260022755ead291dd/window] with body: {"handle":"CDwindow-66693896030E59E24509745AA67CC17D"}
[WD Proxy] Got response with status 200: {"sessionId":"220e61cec0adc66260022755ead291dd","status":61,"value":{"message":"invalid argument: 'name' must be a string\n  (Session info: chrome=75.0.3770.101)\n  (Driver info: chromedriver=75.0.3770.140 (2d9f97485c7b07dc18a74666574f19176731995c-refs/branch-heads/3770@{#1155}),platform=Windows NT 10.0.17134 x86_64)"}}`

[Link to Appium logs](https://gist.github.com/Flpjak/abf8a59f4cd32708bb6ca5a1ad236e0d)

## Code To Reproduce Issue

capabilities = new DesiredCapabilities();
		capabilities.setCapability("automationName", UiAutomator2);
		capabilities.setCapability("platformName", Android);
		capabilities.setCapability("platformVersion", DEVICE_OS_VERSION);
		capabilities.setCapability("deviceName", Test);
		capabilities.setCapability("app", appLocation);
		capabilities.setCapability("appPackage", appPackage);
		capabilities.setCapability("appActivity", ergo.feature.start.StartActivity);
		capabilities.setCapability("unicodeKeyboard", true);
		capabilities.setCapability("resetKeyboard", true);
		capabilities.setCapability("newCommandTimeout", 600);
		capabilities.setCapability("autoGrantPermissions", true);
		capabilities.setCapability("chromedriverExecutable",
				System.getProperty("user.dir") + "\\webdriver\\chromedriver.exe");
		Locale.setDefault(Locale.UK);
try {
			driver = new AndroidDriver<WebElement>(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}
		driver.manage().timeouts().implicitlyWait(120, TimeUnit.SECONDS);
		wait = new FluentWait<WebDriver>(driver).withTimeout(Duration.ofSeconds(100))
.pollingEvery(Duration.ofMillis(500))
.ignoring(NoSuchElementException.class);

public static void switchToWindowHandle(String handleName) {
		Iterable<String> windowHandles = driver.getWindowHandles();
		for (String windowHandle : windowHandles) {
			System.out.println("Window handle: " + windowHandle + " ");
			if (!driver.getCurrentUrl().contains(selectedLanguageShort.toLowerCase() + "/" + handleName)) {
//driver.switchTo().window(windowHandle);
				driver.execute(DriverCommand.SWITCH_TO_WINDOW, ImmutableMap.of("name", windowHandle));
				System.out.println("Switched to handle - " + windowHandle);
				System.out.println(driver.getCurrentUrl());
				break;
			}
			System.err.println(driver.getCurrentUrl());
		}
	}

**Comment by mykola-mokhnach** [comment]
@dpgraham may it happen because chromedriver enforces W3C mode and we still assume we are using jsonwp?

**Comment by mykola-mokhnach** [comment]
Actually, it looks like there is a bug in chromedriver itself. W3C protocol requires the call to POST /window to have `handle` parameter set, but chromedriver still wants `name` as in JSONWP spec: https://w3c.github.io/webdriver/#dfn-switch-to-window

I'll add a workaround to the base driver, but it also makes sense to report the issue to chromedriver.

**Comment by mykola-mokhnach** [comment]
Reported https://bugs.chromium.org/p/chromedriver/issues/detail?id=3024

**Comment by mykola-mokhnach** [comment]
The fix has been published to appium@beta
