### ISSUE TITLE
Appium testing on IOS flutter application

### ISSUE THREAD

**Issue by glassalle59** [appium/appium#12924]
## The problem

Hello,
I want to test a flutter application both on IOS and Android with Appium

I was able to test the Android application by using some element by text. it's not as reliable as ID but the test is still possible.

However on IOS, i see nothing with Appium Inspector. No element are displayed (just the battery, hour, etc...)  :

![image](https://user-images.githubusercontent.com/33724879/61323505-71945380-a810-11e9-8310-a06e3bddfaeb.png)

I also try to use Accessibility Inspector on Xcode but i have no results when clicking on some buttons on the application.

Can you help me please ? 

Thanks per advance,

## Environment

* Appium studio 12.6.5233
* Desktop OS/version used to run Appium: MACOS
* Mobile platform/version under test: IOS
* Real device or emulator/simulator: Real device

**Comment by mykola-mokhnach** [comment]
Unfortunately the problem has nothing to do with Appium. See https://github.com/flutter/flutter/issues/17988

**Comment by glassalle59** [comment]
I should still have the text on elements as on android no? 
How should I build my app? in debug mode with a developer or adhoc certificate ?
