### ISSUE TITLE
Appium not showing WEBVIEW when i navigate from browser to app but showing when i open Android App directly

### ISSUE THREAD

**Issue by samalasivakumar** [appium/appium#12922]
## The problem

SCENARIO 1
========

1. Launch android app 
2. Now i try to get Contexts, it is showing 2 contexts
    A. NATIVE_APP
    B. WEBVIEW

SCENARIO 2
========
1. 1st open URL in chrome browser
2. From browser site i will click one button then i will open android app
3. Now i try to get Contexts, it is showing 2 contexts 
     A. "NATIVE_APP" and 
     B. "CHROMIUM"

When i use SCENARIO 1 I'm getting "WEBVIEW" but when i follow SCENARIO 2 it is not showing "WEBVIEW" instead it is showing "CHROMIUM"

When i navigate from browser to app "WEBVIEW" context is missing, am i doing any thing wrong ?

Could some one help me please. 
Thanks in advance

**Comment by mykola-mokhnach** [comment]
Please fill out the necessary issue details and provide the server log. The current information is not enough to suggest anything

**Comment by samalasivakumar** [comment]
Thanks for reply @mykola-mokhnach 

Please find the below details of environment

## Environment

* Appium version : 1.12:
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): v10.16.0
* Mobile platform/version under test: Android 7 version
* Real device and emulator/simulator:  Both real device and emulator with android 7 
* Appium.exe:

I'm not getting any error for log
Please let me know if still required more details

**Comment by mykola-mokhnach** [comment]
Is the web view available for inspection with chrome remote debugger using the same scenario?

**Comment by samalasivakumar** [comment]
Yes web view is available for inspection with chrome remote debugger. Thanks

**Comment by samalasivakumar** [comment]
Does any know why it is not showing **WEBVIEW** context in **Scenario 2**
Thanks

**Comment by samalasivakumar** [comment]
Haven't face any one this issue till now ?

**Comment by mykola-mokhnach** [comment]
Without logs there is nothing that could be done here. Closed as incomplete.
