### ISSUE TITLE
iOS platform version in Appium 1.14.0 still mandatory for real device

### ISSUE THREAD

**Issue by GrzegorzSidwa** [appium/appium#12937]
## The problem

According to release notes for 1.14.0 :
> platformVersion capability is now mandatory for Simulators and optional for real devices (but only if Appium can determine the version from ideviceinfo output)#954

it should be possible to run test on real device without platformVersion capability. Unfortunately it's not working correctly.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.0
* Last Appium version that did not exhibit the issue (if applicable): 1.12.0
* Desktop OS/version used to run Appium: MacOS
* Node.js version (unless using Appium.app|exe): 11.7.0
* Npm or Yarn package manager: npm 6.5.0
* Mobile platform/version under test: 12.1.4
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: CLI

## Details

Appium still requires platformVersion. I've reviewed @mykola-mokhnach 's PR (https://github.com/appium/appium-xcuitest-driver/pull/954) and I checked how appium extracts platformVersion using deviceinfo. I run command manually and got platform version without any issue. 

Unfortunatly Appium throws error that platformVersion is null.

## Link to Appium logs

https://gist.github.com/GrzegorzSidwa/d9151ae13891bc0ed018b358b3f2dbbf

**Comment by umutuzgur** [comment]
Hi @GrzegorzSidwa. Thanks for reporting the issue. This looks like a bug. We changed the way we get the platformVersion in the master currently. As a workaround, please pass the platformVersion or install appium@beta where this issue should be fixed already

**Comment by GrzegorzSidwa** [comment]
@umutuzgur  when it will be released to stable version? For example 1.14.1. Are there any timelines for this version already?

**Comment by umutuzgur** [comment]
@GrzegorzSidwa We are not in a preparation to release another version at the moment. We will probably release another version in a month. We have some items that we wan't to finalise before we release the next version

**Comment by umutuzgur** [comment]
I'm closing the issue as the bug is fixed on master and there is a workaround for the time being

**Comment by GrzegorzSidwa** [comment]
@umutuzgur in beta version it was available, but in 1.14.1 and 1.14.2 it's still not working. Can you please fix it/add to 1.14.2 or release 1.14.3 very soon with this fix ?
