### ISSUE TITLE
WebDriverError: An unknown server-side error occurred while processing the command. Original error: No targets found, unable to communicate with device

### ISSUE THREAD

**Issue by tejas900** [appium/appium#12935]
## The problem

When 'autoWebview = true' in the desired capabilities, app is installed and launched in the ios simulator but then gives below error

node:48054) UnhandledPromiseRejectionWarning: WebDriverError: An unknown server-side error occurred while processing the command. Original error: No targets found, unable to communicate with device

if i remove the 'autoWebview=true' from the desired capability, i dont get the above error but objects on the app are not getting identified and script fails at first of clicking a simple object saying...'No such element found'

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.0
* Last Appium version that did not exhibit the issue (if applicable): This is my first experience with appium
* Desktop OS/version used to run Appium: MAC Mojave
* Node.js version (unless using Appium.app|exe): 10.16.0
* Npm or Yarn package manager:NPM
* Mobile platform/version under test: ios 12.2
* Real device or emulator/simulator: Simulator iPhoneXR
* Appium CLI or Appium.app|exe: CLI

## Details
This is my first attempt to automate hybrid mobile app on IOS. Setting desired capability 'autoWebView=true' gives error 'No targets found, unable to communicate with device'. If i comment out this capability, engine is unable to even click a simple button within the app giving error, 'No such element found'. We ae using selenium webdriver JS. 

## Link to Appium logs
Attached appium logs as .zip file
[Terminal Saved Output_appiumlogs_July18.zip](https://github.com/appium/appium/files/3404877/Terminal.Saved.Output_appiumlogs_July18.zip)

## Code To Reproduce Issue [ Good To Have ]

Here is the piece of code that clicks on the button

Desired capabilities used:
desiredCapabilities: {
        deviceName: 'iPhone XR', //ENV
        platformVersion: '12.2',         //ENV
        platformName: 'iOS',
        app: '/Users/agentux/Downloads/CXMobileGo.zip',  //ENV
        automationName: 'XCUITest',
        browserName: '',
        autoWebview: true,
        permissions:'{"com.internal.zms.salescloud2": {"calendar": "YES","notifications":"YES"}}'
    }

Code to install and launch the app on simulator:

DriverManager.driver_instance = new wd.Builder()
            .usingServer('http://localhost:4723/wd/hub')
            .withCapabilities(config.desiredCapabilities)
            .build();
        await DriverManager.driver_instance
            .manage()
            .timeouts()
            .implicitlyWait(60000);

Sample code that tries to click on the initial button on the app

try{
        const getStartedBtn = await driver.findElement(
            By.xpath("//*[@id='get-started-btn']"));
        await getStartedBtn.click();
    
    }
    catch(e)
    {
        const getStartedBtn = await driver.findElement(
            By.xpath("//*[@id='get-started-btn']"));
        await getStartedBtn.click();
    }

**Comment by mykola-mokhnach** [comment]
What type of the web view it is? Are you able to debug it via Safari remote debugger?

**Comment by mykola-mokhnach** [comment]
Is the target element present in the page source?

**Comment by c2kos** [comment]
I encounter the exact same problem...

**Comment by tejas900** [comment]
Sorry for the late reply. Yes the element is present in page source and am
able to inspect it via safari.

**Comment by mykola-mokhnach** [comment]
What type of the web view it is? SafariWebView or WKWebView?

**Comment by tejas900** [comment]
hi, please accept my apologies for the late response as due to some unavoidable reasons. 
Can i please reopen the issue?

I am new to mobile automation, how do i determine what type of web view it is?

**Comment by mykola-mokhnach** [comment]
Ask your developers or check the application source

**Comment by tejas900** [comment]
Checked with developer and its WKWebView

**Comment by tejas900** [comment]
hi, is there any update on this issue? We are blocked at this point. Requesting a solution at the earliest.

**Comment by ashishyadav2020** [comment]
I was facing same problem yesterday (failing while switching to webview in hybrid ios app on real device v12.4.1 with appium-1.15.0-beta.0). Though latest appium doesn't have dependencies but I managed to fix this using:

1. Delete/remove existing appium

2. uninstall of dependencies

    -  brew uninstall --force libimobiledevice ios-webkit-debug-proxy
        if it is having dependencies then remove and install those as well

    - assign all permission to 'var/db/lockdownd' using command chmod 777 var/db/lockdownd

    - brew uninstall usbmuxd

3. Now, try installing them

    - brew install --HEAD usbmuxd

    - brew install --HEAD libimobiledevice

    - brew install ideviceinstaller

    - brew install ios-webkit-debug-proxy

4. Now, try installing appium and run '/Scripts/bootstrap.sh' script under appium-webdriveragent
5. Add/update development profile in Xcode for WebDriverAgent.xcodeproj
6. execute 'npm run build' 

@tejas900 Though you might have tried these steps before but for me deleting appium and then re-installing after uninstall-install of dependecies makes difference.

Hope this helps!

**Comment by wswebcreation** [comment]
@mykola-mokhnach and @imurchie 

It looks like it's related to the deprecation of the UIWebview. I'm refactoring the WebdriverIO demo app and it gets the latest version of the react-native-webview module which already has a fix for this, see also https://github.com/react-native-community/react-native-webview/issues/819

When I use my previous version of the App, see https://github.com/webdriverio/native-demo-app/releases/tag/0.2.1, I can automate the webview, but with this version 

[iOS-Simulator-NativeDemoApp-0.3.0.app.zip](https://github.com/appium/appium/files/3617293/iOS-Simulator-NativeDemoApp-0.3.0.app.zip)

I'm getting the same errors as described above, see also [this](https://gist.github.com/wswebcreation/ea4599d7bd5b7981ba93903155a42c54) log (where is now times out). I also tried using the latest 1.15.0-beta.1 but that didn't work.

**Comment by mykola-mokhnach** [comment]
@tejas900 Is the problem fixed for you in appium@beta?
