### ISSUE TITLE
No results when inspecting elements on IOS application 

### ISSUE THREAD

**Issue by glassalle59** [appium/appium#12938]
## The problem

Hello,

I want to test a IOS application with Appium

However, when I want to find xpath elements, I see nothing with Appium Inspector. No element are displayed (just the battery, hour, etc...)  :

![image](https://user-images.githubusercontent.com/33724879/61323505-71945380-a810-11e9-8310-a06e3bddfaeb.png)

I need to see at least the "Text" elements. Not necessarily IDs.

My ipa is a release build with App Store distribution.
=> Is it because of that ? Do I must need a debug build with Development distribution ?  

Thanks per advance,

## Environment

* Appium studio 12.6.5233
* Desktop OS/version used to run Appium: MACOS
* Mobile platform/version under test: IOS
* Real device or emulator/simulator: Real device

**Comment by mykola-mokhnach** [comment]
Appium studio is a commercial product, which has nothing to do with Open Source Appium project. Consider contacting their customer support
