### ISSUE TITLE
After upgrade to 1.14.0. Getting error Failed to launch Appium Settings app

### ISSUE THREAD

**Issue by rajesh-dhiman** [appium/appium#12947]
I did not find to re-open the below issue, so creating new issue
Original issue Link:  https://github.com/appium/appium/issues/12901

As Suggested i tried Another Device I got the Same Error Again
Below are fresh logs and output on another device

**Appium logs**
[Appium logs.txt](https://github.com/appium/appium/files/3418241/Appium.logs.txt)

**Logcat OutPut**
[LogcatOutPut.txt](https://github.com/appium/appium/files/3418245/LogcatOutPut.txt)

**Comment by mindlapse** [comment]
I'm seeing the same `Encountered internal error running command: Error: Failed to launch Appium Settings app: Condition unmet after 5419 ms. Timing out.` error.

I'm attempting this with `system-images;android-23;default;armeabi-v7a`

Here are my installed packages:
```
Installed packages:=====================] 100% Computing updates...             
  Path                                         | Version | Description                    | Location                                     
  -------                                      | ------- | -------                        | -------                                      
  build-tools;28.0.3                           | 28.0.3  | Android SDK Build-Tools 28.0.3 | build-tools/28.0.3/                          
  emulator                                     | 29.0.11 | Android Emulator               | emulator/                                    
  extras;android;m2repository                  | 47.0.0  | Android Support Repository     | extras/android/m2repository/                 
  extras;google;google_play_services           | 49      | Google Play services           | extras/google/google_play_services/          
  extras;google;m2repository                   | 58      | Google Repository              | extras/google/m2repository/                  
  patcher;v4                                   | 1       | SDK Patch Applier v4           | patcher/v4/                                  
  platform-tools                               | 29.0.1  | Android SDK Platform-Tools     | platform-tools/                              
  platforms;android-23                         | 3       | Android SDK Platform 23        | platforms/android-23/                        
  platforms;android-24                         | 2       | Android SDK Platform 24        | platforms/android-24/                        
  platforms;android-28                         | 6       | Android SDK Platform 28        | platforms/android-28/                        
  system-images;android-23;default;armeabi-v7a | 6       | ARM EABI v7a System Image      | system-images/android-23/default/armeabi-v7a/
  system-images;android-24;default;arm64-v8a   | 7       | ARM 64 v8a System Image        | system-images/android-24/default/arm64-v8a/  
  tools                                        | 26.1.1  | Android SDK Tools 26.1.1       | tools/

**Comment by mykola-mokhnach** [comment]
I think it is a problem with the device/firmware, so that pgrep cannot properly detect the running process. The logcat output looks fine, so I don't have another ideas. Simply try  with another device.

**Comment by rajesh-dhiman** [comment]
I don't think, so it is device. Exactly same setup (Same device,Testing Computer) works with appium 1.7.2 the only change in the setup is Appium 1.14.0 upgraded from 1.7.2

Also for confirmation we have tested with multiple devices. All devices has problem with appium 1.14.0, which worked fine with 1.7.2

Please let me know if you need any  other information.

**Comment by mykola-mokhnach** [comment]
> Please let me know if you need any other information.

It makes no sense to discuss the topic without experimenting with the real device (which we don't have). I'd try to figure out why pgrep does not work as expected there

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by a-en** [comment]
We are facing this error pretty regularly. We do not use real devices but rather Genymotion emulators in the cloud. In addition, those emulators are protected by pin code. From my observation, first set of tests that are trying to create session is failing, but after some time they manage to unlock emulator - after that everything is working fine.

In logcat output I see things like

`Background start not allowed: service Intent { act=start cmp=io.appium.settings/.ForegroundService } to io.appium.settings/.ForegroundService from pid=2785 uid=10008 pkg=io.appium.settings startFg?=false`

 and 

`AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{io.appium.settings/io.appium.settings.Settings}: java.lang.IllegalStateException: Not allowed to start service Intent { act=start cmp=io.appium.settings/.ForegroundService }: app is in background uid UidRecord{70ca986 u0a8 TPSL idle change:idle|cached procs:1 seq(0,0,0)}`

As result, emulator stays locked.
So I believe that in my case the error occurs at attempt to start session on locked emulator.

@mykola-mokhnach , do you have any suggestion that might help to deal with that issue?
