### ISSUE TITLE
How to skip "Welcome to Chrome" pop up in Android Emulator

### ISSUE THREAD

**Issue by aruvimal** [appium/appium#12959]
## The problem

Everytime, when i try to run the script in Emulator, im getting "Welcome to Chrome" pop up which i need to avoid on initial screen. Kindly advice whether we have any capabilities to ignore/skip this window on launching any emulator for the first time.

**Comment by KazuCocoa** [comment]
Please ask in https://discuss.appium.io for such questions first.
Not sure, but try to find any options to android chrome driver.
http://chromedriver.chromium.org/
https://chromium.googlesource.com/chromium/src/+/master/chrome/test/chromedriver/capabilities.cc#541
