### ISSUE TITLE
Can't build WebDriverAgent.xcodeproj on ipad with Xcode 10.2

### ISSUE THREAD

**Issue by boan85123** [appium/appium#12952]
## The problem

I can't install app in my iPad(IOS 12.2). The error occurs with the error code 65:

An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65 xcodebuild error message: User defaults from command line: IDEDerivedDataPathOverride = /Users/boan/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs Build settings from command line: COMPILER_INDEX_STORE_ENABLE = NO GCC_TREAT_WARNINGS_AS_ERRORS = 0 IPHONEOS_DEPLOYMENT_TARGET = 12.2 Build settings from configuration file '/var/folders/54/zbr8xwp97w52ln9g6291mm000000gq/T/2019623-5010-oes2ow.ulr9o/appium-temp.xcconfig': CODE_SIGN_IDENTITY = iPhone Developer DEVELOPMENT_TEAM = WPK6X8VFR3 note: Using new build system note: Planning build note: Using build description from disk Build system information error: "WebDriverAgentRunner" requires a provisioning profile. Select a provisioning profile for the "Debug" build configuration in the project editor. (in target 'WebDriverAgentRunner')

## Environment

* Appium version 1.13.0:
* Desktop OS/version used to run Appium: MacOS 10.14.3 (18D109)
* Node.js version (unless using Appium.app|exe): v11.10.0
* Npm or Yarn package manager: npm 6.7.0
* Mobile platform/version under test: IOS 12.2 (16E227)
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Details
I've tested to build the project with command:  
xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' test  

It worked as expected.  

And i also get the successful response after executed following test:
export DEVICE_URL='http://<device IP>:8100'
    export JSON_HEADER='-H "Content-Type: application/json;charset=UTF-8, accept: application/json"'
    curl -X GET $JSON_HEADER $DEVICE_URL/status

But the WebDriverAgent can't be built in my iPad when i use appium desktop to start a new session for iPad.  

## Link to Appium logs
[appuim_log](https://gist.github.com/boan85123/0d162e7be76b7c202df7c0d246e85661)

**Comment by KazuCocoa** [comment]
Did you try out 1.14.0?
https://github.com/appium/appium-xcuitest-driver/pull/961 could fix the provisioning issue.

**Comment by boan85123** [comment]
@KazuCocoa this bug is gone after i use the appium 1.14.0. The steps are as below:
1. Run command in terminal "npm -g update appium";
2. Install the latest appium desktop from [here](https://github.com/appium/appium-desktop/releases/tag/v1.14.0-beta.1);
3. Start new session from latest appium desktop.
Then, the bug is gone.
Thank you very much~~~ It's very helpful for me.
