### ISSUE TITLE
Android Error: No device that matches your criteria error 

### ISSUE THREAD

**Issue by MMooreGitHub** [appium/appium#12954]
I’m receiving the following error message when attempting to Start the Appium Server and Connect to Test Objects.
I verified my capabilities are correct and that the device exists in test objects. Also, I’m able to successfully run iOS tests.
 
How to repeat: I press “Start Server” for the Android Capabilities listed and receive the following  error.
I also attempted to upgrade to Appium Server v1.13.0 but the issue still persists.

![Screen Shot 2019-07-23 at 5 29 42 PM](https://user-images.githubusercontent.com/19997256/61749696-59bd5200-ad71-11e9-93d9-5ea328976acb.png)

**Comment by KazuCocoa** [comment]
Could you contact the support centre, please?
The message looks coming from their service.
