### ISSUE TITLE
Issue in Android Emulator browser launch 

### ISSUE THREAD

**Issue by aruvimal** [appium/appium#12958]
## The problem
i am trying to launch the multiple URLs during execution and perform my validation. In doing so, we have noticed that every-time, when we use driver.get("url"), **it is opening in new tab of emulator browser instead of same tab.** i have to do it in same tab and perform the validation (since we have more than 100 URL for the validation, which will encounter in opening 100 tabs during execution. This has be avoided by launching in same tab.). Please advise. 

## Environment
info AppiumDoctor Appium Doctor v.1.11.1
info AppiumDoctor ### Diagnostic for necessary dependencies starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: node_modules/.bin/node
info AppiumDoctor  ✔ Node version is 12.6.0
info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ Xcode Command Line Tools are installed in: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ DevToolsSecurity is enabled.
info AppiumDoctor  ✔ The Authorization DB is set up properly.
info AppiumDoctor  ✔ Carthage was found at: node_modules/.bin/carthage. Installed version is: 1.0.6
info AppiumDoctor  ✔ HOME is set to: /Users/vz8zw5
info AppiumDoctor  ✔ ANDROID_HOME is set to: /Users/vz8zw5/Library/Android/sdk
info AppiumDoctor  ✔ JAVA_HOME is set to: /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home
info AppiumDoctor  ✔ adb exists at: /Users/vz8zw5/Library/Android/sdk/platform-tools/adb
info AppiumDoctor  ✔ android exists at: /Users/vz8zw5/Library/Android/sdk/tools/android
info AppiumDoctor  ✔ emulator exists at: /Users/vz8zw5/Library/Android/sdk/tools/emulator
info AppiumDoctor  ✔ Bin directory of $JAVA_HOME is set
info AppiumDoctor ### Diagnostic for necessary dependencies completed, no fix needed. ###
info AppiumDoctor 
info AppiumDoctor ### Diagnostic for optional dependencies starting ###
WARN AppiumDoctor  ✖ opencv4nodejs cannot be found.
WARN AppiumDoctor  ✖ ffmpeg cannot be found
WARN AppiumDoctor  ✖ mjpeg-consumer cannot be found.
WARN AppiumDoctor  ✖ idb and idb_companion are not installed
WARN AppiumDoctor  ✖ applesimutils cannot be found
WARN AppiumDoctor  ✖ idevicelocation cannot be found
WARN AppiumDoctor  ✖ ios-deploy cannot be found
WARN AppiumDoctor  ✖ ios_webkit_debug_proxy cannot be found
WARN AppiumDoctor  ✖ ifuse cannot be found
WARN AppiumDoctor  ✖ bundletool.jar cannot be found
info AppiumDoctor ### Diagnostic for optional dependencies completed, 10 fixes possible. ###
info AppiumDoctor 
info AppiumDoctor ### Optional Manual Fixes ###
info AppiumDoctor The configuration can install optionally. Please do the following manually:
WARN AppiumDoctor  ➜ Why opencv4nodejs is needed and how to install it: https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/image-comparison.md
WARN AppiumDoctor  ➜ ffmpeg is needed to record screen features. Please read https://www.ffmpeg.org/ to install it
WARN AppiumDoctor  ➜ mjpeg-consumer module is required to use MJPEG-over-HTTP features. Please install it with 'npm i -g mjpeg-consumer'.
WARN AppiumDoctor  ➜ Why idb is needed and how to install it: https://github.com/appium/appium-idb
WARN AppiumDoctor  ➜ Why applesimutils is needed and how to install it: http://appium.io/docs/en/drivers/ios-xcuitest/
WARN AppiumDoctor  ➜ idevicelocation is used to set geolocation for real device. Please read https://github.com/JonGabilondoAngulo/idevicelocation to install it
WARN AppiumDoctor  ➜ ios-deploy is used to install iOS applications to real device. Please read http://appium.io/docs/en/drivers/ios-xcuitest-real-devices/ to install it
WARN AppiumDoctor  ➜ ios_webkit_debug_proxy is used to proxy requests from Appium to MobileSafari running on real device. Please read https://github.com/google/ios-webkit-debug-proxy to install it
WARN AppiumDoctor  ➜ ifuse is used to manage files/folders against a real device. Please read https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios/ios-xctest-file-movement.md to install it
WARN AppiumDoctor  ➜ bundletool.jar is used to handle Android App Bundle. Please read http://appium.io/docs/en/writing-running-appium/android/android-appbundle/ to install it

## Code To Reproduce Issue [ Good To Have ]

		@Test
		public void manin1 () throws InterruptedException, IOException
		{	
			String proxyPacURL= "10.47.196.150:9191";
			Proxy proxy = new Proxy();
			proxy.setProxyAutoconfigUrl(proxyPacURL);
			
			String mydevice = "Pixel_C_API_28";
					
			oCaps = new DesiredCapabilities();
			oCaps.setCapability("noReset", "true");
			oCaps.setCapability("deviceName", mydevice);
			oCaps.setCapability("platformName", "Android");
			oCaps.setCapability("automationName", "UiAutomator1");
			oCaps.setCapability("appPackage", "com.android.chrome");
			oCaps.setCapability("appActivity", "com.google.android.apps.chrome.Main");
				
			URL url = new URL("http://127.0.0.1:4723/wd/hub");
			
			setupEmulator(mydevice);

			driver = new AndroidDriver<MobileElement> (url,oCaps);
			driver.manage().timeouts().implicitlyWait(Constants.WAIT, TimeUnit.SECONDS);
			
			driver.get("http://www.google.com");
			Thread.sleep(3000);
			driver.get("http://www.facebook.com");
			Thread.sleep(3000);
                         driver.close();		
			}

**Comment by KazuCocoa** [comment]
What about changing webview context? or set `automationName: 'chrome'`  capability instead of appPackage and appActivity.

`driver.get` in native context sends an intent.
If the browser behaved opening a new tab by the intent, the behaviour is expected. (It depends on the app preference)
