### ISSUE TITLE
Distributed Testing Using Selenium Grid

### ISSUE THREAD

**Issue by shaileshugile1990** [appium/appium#12953]
## The problem
I have successfully implemented the selenium gird to run the parallel tests on mobile devices. However, I am trying to run the distributed tests. 

## Sample Code
```
public runner()
{
  @BeforeTest
  public void launchApp()
  {
     // App lanuch code 
  }
  @Test 
  public void firstTest()
  {
     // First test code
  }
  @Test 
  public void secondTest()
  {
     // Second test code
  }
  @Test 
  public void thirdTest()
  {
     // Third test code
  }
  @Test 
  public void fourthTest()
  {
     // Fourth test code
  } 
}
```
# Code result expectations
Suppose, I am having 4 test cases with two connected devices. Then, I want to run 2 tests on one device and remaining 2 tests on another device (The number of tests distribution can be vary on devices). As a end result I should get the result for only four tests with device information.

**So, Is distributed testing on mobiles possible using Appium client with Selenium WebDriver ?**

## Environment
* Appium version (or git revision) that exhibits the issue: 1.12.1
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Ubuntu 14.04 LTS
* Node.js version (unless using Appium.app|exe): 11.13.0
* Npm or Yarn package manager: 6.7.0
* Mobile platform/version under test: Device 1 (v 8.0.0) , Device 2 (v 8.0.1) 
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

**Comment by saikrishna321** [comment]
Please ask for questions here - discuss.appium.io
