### ISSUE TITLE
Alert is not recognized on iOS 13 beat 4

### ISSUE THREAD

**Issue by bearxc** [appium/appium#12956]
iOS 14 beta 4 simulator
appium : latest master branch
java client: 7.1.0

when I try to  get UI dump through    

Context.driver.getPageSource();

I can not find any XCUIElementTypeAlert related info , also  text/buttons inside alert  is missing also .

**Comment by raysurc** [comment]
Hi. I am also seeing this issue. What was the reason that you closed this issue?

**Comment by bearxc** [comment]
check following thread
It looks like  apple framework issue
https://github.com/appium/appium/issues/12965
