### ISSUE TITLE
modal view controller is not detected on  Xcode11 beta4

### ISSUE THREAD

**Issue by bearxc** [appium/appium#12965]
There is style change on  xcode 11 for modal view controllers  , just like  stacked windows.

If there are more stacked windows ,    all UI elements on top screen is invisible.

iPhone 8 sim, iOS13, Xcode 11 beta4

latest master branch for https://github.com/appium/WebDriverAgent.git

reproduce steps

1) launch Health app
2) click "Get Started"
3) scroll down and click "add emergency contact"
4)  there is contact page

try to get source   on this screen,
http://localhost:8100/source

I can not find any contact info .
{
  "value" : "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<XCUIElementTypeApplication type=\"XCUIElementTypeApplication\" name=\"Health\" label=\"Health\" enabled=\"true\" visible=\"false\" x=\"0\" y=\"0\" width=\"375\" height=\"667\">\n  <XCUIElementTypeWindow type=\"XCUIElementTypeWindow\" enabled=\"true\" visible=\"false\" x=\"0\" y=\"0\" width=\"375\" height=\"667\">\n    <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"false\" x=\"0\" y=\"0\" width=\"375\" height=\"667\">\n      <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"false\" x=\"0\" y=\"0\" width=\"375\" height=\"667\"\/>\n      <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"false\" x=\"16\" y=\"30\" width=\"343\" height=\"574\">\n        <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"false\" x=\"16\" y=\"30\" width=\"343\" height=\"574\">\n          <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"false\" x=\"16\" y=\"30\" width=\"343\" height=\"574\">\n            <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"false\" x=\"16\" y=\"30\" width=\"343\" height=\"574\"\/>\n          <\/XCUIElementTypeOther>\n        <\/XCUIElementTypeOther>\n      <\/XCUIElementTypeOther>\n    <\/XCUIElementTypeOther>\n  <\/XCUIElementTypeWindow>\n  <XCUIElementTypeWindow type=\"XCUIElementTypeWindow\" enabled=\"true\" visible=\"false\" x=\"0\" y=\"0\" width=\"375\" height=\"667\">\n    <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"false\" x=\"0\" y=\"0\" width=\"375\" height=\"667\">\n      <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"false\" x=\"0\" y=\"0\" width=\"375\" height=\"667\"\/>\n      <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"false\" x=\"0\" y=\"0\" width=\"375\" height=\"667\">\n        <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"false\" x=\"0\" y=\"0\" width=\"375\" height=\"667\">\n          <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"false\" x=\"0\" y=\"0\" width=\"375\" height=\"667\"\/>\n        <\/XCUIElementTypeOther>\n      <\/XCUIElementTypeOther>\n    <\/XCUIElementTypeOther>\n  <\/XCUIElementTypeWindow>\n  <XCUIElementTypeWindow type=\"XCUIElementTypeWindow\" enabled=\"true\" visible=\"false\" x=\"0\" y=\"0\" width=\"375\" height=\"667\">\n    <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"false\" x=\"0\" y=\"0\" width=\"375\" height=\"667\">\n      <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"false\" x=\"0\" y=\"0\" width=\"375\" height=\"667\">\n        <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"false\" x=\"0\" y=\"0\" width=\"375\" height=\"667\"\/>\n      <\/XCUIElementTypeOther>\n    <\/XCUIElementTypeOther>\n  <\/XCUIElementTypeWindow>\n<\/XCUIElementTypeApplication>\n",
  "sessionId" : "BA7B2A76-43F5-4230-9433-B1B6090F1CBD",
  "status" : 0
}

<img width="471" alt="Screen Shot 2019-07-24 at 3 40 32 PM" src="https://user-images.githubusercontent.com/7198439/61823284-8339b480-ae29-11e9-83c6-bad6fc57c392.png">

**Comment by bearxc** [comment]
on same page, accessibility inspector works fine , I  assume xctest framework  works fine . 

<img width="1155" alt="Screen Shot 2019-07-24 at 5 32 58 PM" src="https://user-images.githubusercontent.com/7198439/61830615-9785ad80-ae39-11e9-8252-d129ed1a27ae.png">

**Comment by KazuCocoa** [comment]
note:
The view has two views. "Medical ID" which is behind the "Contacts" works.

**Comment by bearxc** [comment]
This issue is  a block  issue  for iOS13 now .  

This could be related with  stacked  views  hierarchy  .

If the hierarchy is more than 2 , then the 3rd UI would not work on WDA.

In our own app,   the 3rd is an alert window,  WDA could not detect it also .

**Comment by bearxc** [comment]
Here is  info related with  modal view changes on iOS 13

https://medium.com/@hacknicity/view-controller-presentation-changes-in-ios-13-ac8c901ebc4e

**Comment by KazuCocoa** [comment]
Thanks, but below is the view's debugDescription by XCTest framework. 
XCTest framework could not return elements like "Contents" so far.
I was able to get identifiers in "Medical ID" view as same as current Appium.

mm..

```
Attributes: Window (Main), {{0.0, 0.0}, {375.0, 667.0}}
Element subtree:
 →Window (Main), 0x600000bd5180, {{0.0, 0.0}, {375.0, 667.0}}
    Other, 0x600000bd5260, {{0.0, 0.0}, {375.0, 667.0}}
      Other, 0x600000bd5340, {{0.0, 0.0}, {375.0, 667.0}}
      Other, 0x600000bd4b60, {{0.0, 40.0}, {375.0, 627.0}}
        Other, 0x600000bd4c40, {{0.0, 40.0}, {375.0, 627.0}}
          Other, 0x600000bd4e00, {{0.0, 40.0}, {375.0, 627.0}}
            Other, 0x600000bd4ee0, {{0.0, 40.0}, {375.0, 627.0}}
Path to element:
 →Application, 0x600000bd50a0, pid: 92613, label: 'Health'
  ↳Window (Main), 0x600000bd5180, {{0.0, 0.0}, {375.0, 667.0}}
Query chain:
 →Find: Application 'com.apple.Health'
  Output: {
    Application, pid: 92613, label: 'Health'
  }
  ↪︎Find: Children matching type Any
    Output: {
      Window (Main), {{0.0, 0.0}, {375.0, 667.0}}
      Window, {{0.0, 0.0}, {375.0, 667.0}}
      Window, {{0.0, 0.0}, {375.0, 667.0}}
    }
    ↪︎Find: Identity Binding
      Output: {
        Window (Main), {{0.0, 0.0}, {375.0, 667.0}}
      }


Attributes: Window, {{0.0, 0.0}, {375.0, 667.0}}
Element subtree:
 →Window, 0x600000bc3100, {{0.0, 0.0}, {375.0, 667.0}}
    Other, 0x600000bc31e0, {{0.0, 0.0}, {375.0, 667.0}}
      Other, 0x600000bc32c0, {{0.0, 0.0}, {375.0, 667.0}}
      RemotePlaceholder, 0x600000bc33a0, pid: 92613, {{0.0, 0.0}, {375.0, 667.0}}
        Other, 0x600000bc3480, {{0.0, 0.0}, {375.0, 667.0}}
          Other, 0x600000bc3560, {{0.0, 0.0}, {375.0, 667.0}}
Path to element:
 →Application, 0x600000bc2a00, pid: 92613, label: 'Health'
  ↳Window, 0x600000bc3100, {{0.0, 0.0}, {375.0, 667.0}}
Query chain:
 →Find: Application 'com.apple.Health'
  Output: {
    Application, pid: 92613, label: 'Health'
  }
  ↪︎Find: Children matching type Any
    Output: {
      Window (Main), {{0.0, 0.0}, {375.0, 667.0}}
      Window, {{0.0, 0.0}, {375.0, 667.0}}
      Window, {{0.0, 0.0}, {375.0, 667.0}}
    }
    ↪︎Find: Identity Binding
      Output: {
        Window, {{0.0, 0.0}, {375.0, 667.0}}
      }


Attributes: Window, {{0.0, 0.0}, {375.0, 667.0}}
Element subtree:
 →Window, 0x600000bd2840, {{0.0, 0.0}, {375.0, 667.0}}
    Other, 0x600000bd25a0, {{0.0, 0.0}, {375.0, 667.0}}
      RemotePlaceholder, 0x600000bd1ce0, pid: 92613, {{0.0, 0.0}, {375.0, 667.0}}
        Other, 0x600000bd2ca0, {{0.0, 0.0}, {375.0, 667.0}}
Path to element:
 →Application, 0x600000bd2060, pid: 92613, label: 'Health'
  ↳Window, 0x600000bd2840, {{0.0, 0.0}, {375.0, 667.0}}
Query chain:
 →Find: Application 'com.apple.Health'
  Output: {
    Application, pid: 92613, label: 'Health'
  }
  ↪︎Find: Children matching type Any
    Output: {
      Window (Main), {{0.0, 0.0}, {375.0, 667.0}}
      Window, {{0.0, 0.0}, {375.0, 667.0}}
      Window, {{0.0, 0.0}, {375.0, 667.0}}
    }
    ↪︎Find: Identity Binding
      Output: {
        Window, {{0.0, 0.0}, {375.0, 667.0}}
      }
=> nil
```

**Comment by bearxc** [comment]
yes, I tired same on  xcode 11  beta4,   debugDescription could not get elements on  top view .

It looks like a XCUITEST framework issue  .

**Comment by bearxc** [comment]
BTW,  how do you make  XCTest run against Health app ?

I think   XCTest framework  only runs  against  source code project , not on 3rd party app .

**Comment by KazuCocoa** [comment]
Good question. The easiest way is calling below command via Appium. Then, Appium simply returns vanilla _debugDescription_ by Xcode framework.

```
@driver.execute_script 'mobile: source', { format: :description }
```

In general, WDA returns xml or json format resolving visibilities etc for each items, but the debugDescription does not have them.

**Comment by bearxc** [comment]
this is good debug method :)

if i run java client , following code is correct ?

JavascriptExecutor js = (JavascriptExecutor) driver;
Map<String, Object> args = new HashMap<>();
args.put("format", "description");
JSONObject source = new JSONObject(js.executeScript("mobile: source", args));

**Comment by KazuCocoa** [comment]
Looks good, and below is also...

```
driver.executeScript("mobile: source", ImmutableMap.of("format", "description"));
```

by http://appium.io/docs/en/commands/mobile-command/

**Comment by mykola-mokhnach** [comment]
Closed as third party issue. I would try to describe the problem to Apple.

**Comment by mykola-mokhnach** [comment]
@bearxc Try the patch https://github.com/appium/WebDriverAgent/pull/205
It might be this controller belongs to a different application, although the current application is still set to your app under test. Now the logic that determines on-screen is different so it might, actually, work.

**Comment by bearxc** [comment]
I tried my own app  on  xcode 11 beta 7 , same issue .

**Comment by bearxc** [comment]
on xcode 11 beta7 ,   debugDescription could  not catch all elements  , but  app.buttons["Id"] still works fine on xcuitest   , even that  button does not appear in debugDescription dump tree.

**Comment by bearxc** [comment]
https://forums.developer.apple.com/thread/122052

**Comment by sahilkamboj334** [comment]
Hi @mykola-mokhnach , @bearxc any update on this?

**Comment by KazuCocoa** [comment]
Please check `includeNonModalElements` in http://appium.io/docs/en/advanced-concepts/settings/

**Comment by sahilkamboj334** [comment]
@KazuCocoa this didn't helped. App popup's are not coming in the appium page source. We are able to get all elements on a simulator using .zip file but on IPA we are unable to get popup's element.

**Comment by KazuCocoa** [comment]
Then, you should report it to Apple.
Appium calls the same XCTest API to get native elements in both simulator and real devices.

**Comment by Somnibyte** [comment]
Hello @sahilkamboj334, and @bearxc. Have you any of you sent a bug report to Apple or know of an existing bug report? If so please post a link here. I would like to keep myself up-to-date on this issue as I'm also experiencing this issue myself.
