### ISSUE TITLE
Legacy accessibility snapshots are no longer supported on  Xcode 11 beat 4 /iOS 13

### ISSUE THREAD

**Issue by bearxc** [appium/appium#12960]
latest   appium/WebDriverAgent

launch WebDriverAgentRunner 

http://localhost:8100/source

WebDriverAgentRunner-Runner[23050:265535] Internal error: Error Domain=XCTDaemonErrorDomain Code=39 "Legacy accessibility snapshots are no longer supported" UserInfo={NSLocalizedDescription=Legacy accessibility snapshots are no longer supported}

**Comment by KazuCocoa** [comment]
note.
When I conducted source command on map app https://github.com/appium/appium/issues/12957#issuecomment-514552962

https://gist.github.com/KazuCocoa/2df08c25fa3751aa558c801e343a6f7f

**Comment by umutuzgur** [comment]
@KazuCocoa It seems like we use an old method to get the snapshot. I took a lit at the class dump. It seems like there are 2 more methods added. We currently use the last one. We can give it a try to use `_XCT_requestSnapshotForElement` since it looks the same as the other one

- (void)_XCT_fetchSnapshotForElement:(XCAccessibilityElement *)arg1 attributes:(NSArray *)arg2 parameters:(NSDictionary *)arg3 reply:(void (^)(XCUIElementSnapshotRequestResult *, NSError *))arg4;
- (void)_XCT_requestSnapshotForElement:(XCAccessibilityElement *)arg1 attributes:(NSArray *)arg2 parameters:(NSDictionary *)arg3 reply:(void (^)(XCElementSnapshot *, NSError *))arg4;
- (void)_XCT_snapshotForElement:(XCAccessibilityElement *)arg1 attributes:(NSArray *)arg2 parameters:(NSDictionary *)arg3 reply:(void (^)(XCElementSnapshot *, NSError *))arg4;

**Comment by KazuCocoa** [comment]
Yes, you're right.
I dumped the header and replaced that to `_XCT_requestSnapshotForElement`. Below is the result. (not warning messages)

```
[HTTP] --> GET /wd/hub/session/e18a5610-8e9d-4a0e-b684-47159c0ad194/source
[HTTP] {}
[debug] [W3C (e18a5610)] Calling AppiumDriver.getPageSource() with args: ["e18a5610-8e9d-4a0e-b684-47159c0ad194"]
[debug] [XCUITest] Executing command 'getPageSource'
[debug] [WD Proxy] Matched '/source?format=json' to command name 'getPageSource'
[debug] [WD Proxy] Proxying [GET /source?format=json] to [GET http://localhost:8100/session/D96FCA00-7B38-49C9-99A9-2A1B94D68998/source?format=json] with no body
[debug] [WD Proxy] Got response with status 200: {
[debug] [WD Proxy]   "value" : {
[debug] [WD Proxy]     "isEnabled" : "1",
[debug] [WD Proxy]     "isVisible" : "0",
[debug] [WD Proxy]     "frame" : "{{0, 0}, {0, 0}}",
[debug] [WD Proxy]     "children" : [
[debug] [WD Proxy]       {
[debug] [WD Proxy]         "isEnabled" : "1",
[debug] [WD Proxy]         "isVisible" : "0",
[debug] [WD Proxy]         "frame" : "{{0, 0}, {0, 0}}",
[debug] [WD Proxy]         "children" : [
[debug] [WD Proxy]           {
[debug] [WD Proxy]             "isEnabled" : "1",
[debug] [WD Proxy]             "isVisible" : "0",
[debug] [WD Proxy]             "frame" : "{{0, 0}, {0, 0}}",
[debug] [WD Proxy]             "children" : [
[debug] [WD Proxy]               {
[debug] [WD Proxy]                 "isEnabled" : "1",
[debug] [WD Proxy]                 "isVisible" : "0",
[debug] [WD Proxy]                 "frame" : "{{0, 0}, {0, 0}}",
[debug] [WD Proxy]                 "children" : [
[debug] [WD Proxy]                   {
[debug] [WD Proxy]                     "isEnabled" : "1",
[debug] [WD Proxy]                     "isVisible" : "0",
[debug] [WD Proxy]                     "frame" : "{{0, 0}, {0, 0}}",
[debug] [WD Proxy]                     "children" : [
[debug] [WD Proxy]                       {
[debug] [WD Proxy]                         "isEnabled" : "1",
[debug] [WD Proxy]                         "isVisible" : "0",
[debug] [WD Proxy]                         "frame" : "{{0, 0}, {0, 0}}",
[debug] [WD Proxy]                         "children" : [
[debug] [WD Proxy]                           {
[debug] [WD Proxy]                             "isEnabled" : "1",
[debug] [WD Proxy]                 ...
[debug] [W3C (e18a5610)] Responding to client with driver.getPageSource() result: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<AppiumAUT>\n  <XCUIElementTypeApplication type=\"XCUIElementTypeApplication\" enabled=\"true\" visible=\"false\" x=\"0\" y=\"0\" width=\"0\" height=\"0\">\n    <XCUIElementTypeWindow type=\"XCUIElementTypeWindow\" enabled=\"true\" visible=\"false\" x=\"0\" y=\"0\" width=\"0\" height=\"0\">\n      <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"false\" x=\"0\" y=\"0\" width=\"0\" height=\"0\">\n        <XCUIElementTypeAlert type=\"XCUIElementTypeAlert\" enabled=\"true\" visible=\"false\" x=\"0\" y=\"0\" width=\"0\" height=\"0\">\n          <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"false\" x=\"0\" y=\"0\" width=\"0\" height=\"0\">\n            <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"false\" x=\"0\" y=\"0\" width=\"0\" height=\"0\">\n              <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"false\" x=\"0\" y=\"0\" width=\"0\...
[HTTP] <-- GET /wd/hub/session/e18a5610-8e9d-4a0e-b684-47159c0ad194/source 200 205 ms - 7726
[HTTP]
```

**Comment by umutuzgur** [comment]
Nice

**Comment by KazuCocoa** [comment]
I found `_XCT_requestSnapshotForElement` has been there from Xcode 9.0. (I dumped headers in Xcode 9.0) Not sure Xcode 8, but Xcode 7 has no it.
We can use `_XCT_requestSnapshotForElement` instead of `_XCT_snapshotForElement`, completely.

If we switched to `_XCT_requestSnapshotForElement` based on `instancesRespondToSelector`, `_XCT_snapshotForElement` probably has never been selected in our supported Xcode after using `_XCT_requestSnapshotForElement`

**Comment by umutuzgur** [comment]
Makes sense @KazuCocoa. You can send me a PR so I would approve directly

**Comment by KazuCocoa** [comment]
note:

Tried to replace the method, but it breaks visibilities/element coordinates etc
https://github.com/appium/WebDriverAgent/pull/190

**Comment by applexiaohao** [comment]
关注

**Comment by mykola-mokhnach** [comment]
Linking to https://github.com/appium/appium/issues/12400

**Comment by raphc43** [comment]
> I'm running into this issue, using appium 1.22.2, when trying to work with an iOS 15.2. My Xcode is 12.4 though. Do I need to update my XCode version in order to get rid of this? If so, what would be the minimum version that would fix this?

At least Xcode 13 I guess. In my case I used trial and error approach to inspect UI elements. And I did all of this in a browser based Appium Inspector which runs faster compared to a local machine.

**Comment by sijncheng** [comment]
I got the same error and updated the Xcode version but nothing was helpful. May I ask if there is any solution?
