### ISSUE TITLE
timeout of adb command / wait parameter

### ISSUE THREAD

**Issue by jjoe64** [appium/appium#12962]
## The problem

My goal is to run end-to-end tests with Appium on an App built with Expo (turtle-cli).
When starting the session, the app launches on the smartphone, but appium throws a timeout error:

`[MJSONWP] Encountered internal error running command: Error: Cannot start the 'com.example.testetoeapplauda' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Error executing adbExec. Original error: 'Command 'adb -P 5037 -s ENU7N15B03007818 shell am start -W -n com.example.testetoeapplauda/host.exp.exponent.MainActivity -S' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability`

The interesting part is the adb shell command. When I run this command manually, the app launches, but the command does not finish - it just hangs forever.

When I remove the parameter -W it is not blocking.

So, how can I change Appium to don't use the **-W** flag on the adb command?

## Environment

* Real device or emulator/simulator:
real device Android 8.1.0
* Appium CLI or Appium.app|exe:
Appium-Desktop 1.13.0

## Code To Reproduce Issue [ Good To Have ]

Here is a link to the APK file to reproduce the problem:
[expo-app-test apk file](https://drive.google.com/open?id=19KtkEqIM5XfhVeUgKAOk9W40e3dpVKiG)

**Comment by KazuCocoa** [comment]
We need to add `waitForLaunch` (false) as `appWaitForLaunch` capability and pass it to 
 https://github.com/appium/appium-uiautomator2-driver/blob/fe94bf0dcc38650616a826508a38deaf204c9d49/lib/driver.js#L474-L484
Need to check other places, too.
Then, we can skip adding `-W`.

note:
(In appium-adb layer, we already have the argument https://github.com/appium/appium-adb/blob/dd926d1a41923234900d9610beabc7095662a2c7/lib/tools/apk-utils.js#L95)

**Comment by KazuCocoa** [comment]
@jjoe64 
From the next version, `appWaitForLaunch: false` will allow avoiding -W option

Thanks

**Comment by jjoe64** [comment]
@KazuCocoa I just tried it and it is not working with the current state of the master branch. It is still using the `-W` flag, even when I set `appWaitForLaunch: false`. Can you please check this?

=> not closed

**Comment by KazuCocoa** [comment]
ah, sorry, I didn't publish the new version.
Will bump the version soon.

**Comment by jjoe64** [comment]
but it's merged, isn't it? Then it should work with the master branch. I cloned this repo and built and ran it from sources

**Comment by KazuCocoa** [comment]
Yes. If you get appium-uiautomator2-driver and run `npm install && npm link` and `npm link  appium-uiautomator2-driver` in appium master, for example, the uia2 driver master should work.
Could you share your log?

**Comment by jjoe64** [comment]
yeah that's working, thanks!

**Comment by KazuCocoa** [comment]
I published the new one as 1.34.0. You can also get it via `appium@beta`.

**Comment by jjoe64** [comment]
I can confirm it's working with appium@beta
