### ISSUE TITLE
How to reduce ESOCKETTIMEDOUT timeout

### ISSUE THREAD

**Issue by zengxiaoshi** [appium/appium#12961]
## The problem

How to reduce ESOCKETTIMEDOUT timeout. It cost 4 minute now. 

## Environment

* Appium version (or git revision) that exhibits the issue:1.14.0
* Mobile platform/version under test: Android 9

## Link to Appium logs
Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT

**Comment by KazuCocoa** [comment]
Please attach the full log and tell us more details.
Considering to ask it in https://discuss.appium.io for more rough questions.

**Comment by zengxiaoshi** [comment]
ESOCKETTIMEDOUT：This timeout sets the amount of time to wait *between* bytes sent from the server once connected.
I want to reduce ESOCKETTIMEDOUT, It cost 4 minute now.

**Comment by mykola-mokhnach** [comment]
Currently it is not possible to explicitly set the socket timeout from the outside. Although, you can change it in your local source, for example in 
https://github.com/appium/appium-base-driver/blob/e0f442f391806f10cc173906df1ffcbab71a9a26/lib/jsonwp-proxy/proxy.js#L14

or by adding the `timeout` argument to https://github.com/appium/appium-uiautomator2-driver/blob/ca2ce0e200665c9b3ceef2122e4055b8c63eab75/lib/uiautomator2.js#L28

https://appiumpro.com/editions/47 has more info on how to transpile Appium from sources

**Comment by zengxiaoshi** [comment]
[ESOCKETTIMEDOUT.zip](https://github.com/appium/appium/files/3445057/ESOCKETTIMEDOUT.zip)
Hello，this is the log of ESOCKETTIMEDOUT。I don't know how to fix it.

**Comment by mykola-mokhnach** [comment]
In the logcat output I can observe that multiple application got socket error at the same time. This might be a sign of network connectivity issues or some problems on the device itself. From Appium's perspective ESOCKETTIMEDOUT means that the remote server on the device has unexpectedly stopped responding to network requests.

**Comment by zengxiaoshi** [comment]
But other applications can use network，and appium will response to network requests, if we restart appium-uiautomator-server when esockettimeout.
restart command: am instrument -w io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner

**Comment by mykola-mokhnach** [comment]
Restarting the server automatically destroys the current session and shifts the driver to an undefined state.

**Comment by zengxiaoshi** [comment]
Restarting the server automatically destroys the current session and shifts the driver to an undefined state.
> En…By restart the server, I think the network is ok on the device itself.

**Comment by mykola-mokhnach** [comment]
Closed as inactive. Feel free to use Appium forum for questions
