### ISSUE TITLE
[Windows] New Command Timeout triggerred on older session even if it was deleted

### ISSUE THREAD

**Issue by cosminstirbu** [appium/appium#12966]
## The problem

In our UWP tests we're deleting the previous session by calling Driver?.Close() (if it existed), then we reinstall the application via a PowerShell script and after that we create a new Driver.

All this because the ResetApp() is not implemented on WDA.

The issue is that even if we delete a previous session, at some point during the test execution, New Command Timeout is triggered on it.

As you can see in the gist https://gist.github.com/cosminstirbu/80341821dd5df91f3301411ea4f9d3bf#file-wda-new-command-timeout on line 9 session EBA4D3AF-CA65-4CD8-95A3-CF89E00DCE7F is deleted, and after a while, on line 2832 it is deleted again due to New Command Timeout of 120 seconds expired.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.0
* Last Appium version that did not exhibit the issue (if applicable): not applicable
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: UWP
* Real device or emulator/simulator: Windows 10 Machine
* Appium CLI or Appium.app|exe: CLI

**Comment by cosminstirbu** [comment]
The major issue is that after that the WDA stops and no longer accepts connections:

```
7/24/2019 11:13:36 AM [debug] [WinAppDriver] WinAppDriver changed state to 'stopping'
7/24/2019 11:13:36 AM [WD Proxy] Got an unexpected response: {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}
```

So none of our tests works any longer.

**Comment by KazuCocoa** [comment]
Could you please create an issue on https://github.com/microsoft/WinAppDriver rather than here so that they can notice it?

**Comment by KazuCocoa** [comment]
thanks!
Let's track the WAD repo first.
