### ISSUE TITLE
WebdriveragentLib not able to set signing Certificate

### ISSUE THREAD

**Issue by nagajyostna-eate** [appium/appium#12976]
WebDriverAgentLib : not able to set the Signing Certificate

but could able to set the Signing Certificate to WebDriverAgentRunner

**Comment by KazuCocoa** [comment]
Please attach the appium logs and explanation following issue template as a new issue.
Or you can also post it to https://discuss.appium.io about more general questions

**Comment by nagajyostna-eate** [comment]
Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device. at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/driver.js:388:13) at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40) at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22) at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21) at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37) at

**Comment by KazuCocoa** [comment]
Thanks!

Is this the latest Xcode?
It is helpful to attach the appium full log since it has much information to understand your situation.
