### ISSUE TITLE
IOS and Android cannot start appium session

### ISSUE THREAD

**Issue by ReyyanArik** [appium/appium#12971]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by ReyyanArik** [comment]
When I run the appium from commandLine, I've got the following logs:

Appium REST http interface listener started on 0.0.0.0:4723
[debug] [W3C]     at XCUITestDriver.determineDevice (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:771:17)
[debug] [W3C]     at XCUITestDriver.start (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:269:40)
[debug] [W3C]     at XCUITestDriver.createSession (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:206:7)
[debug] [W3C]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:342:35)
[debug] [W3C]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:319:13)
[debug] [W3C]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:471:14)
[debug] [W3C]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:352:21)
[HTTP] <-- POST /wd/hub/session 500 
 ms - 649

Xcode: Version 10.2.1 (10E1001)
Appium: v1.13.0
Device: IOS Real Device - 11.4.1

Also, my collegues have the same issues both with Android and IOS. Please help us!

**Comment by imurchie** [comment]
Is that the _entire_ server log? It seems incomplete, and not enough to go on.

**Comment by ReyyanArik** [comment]
Here is my whole log:

REYYAN-ARIK:~ rarik$ appium --allow-cors
[Appium] Welcome to Appium v1.13.0
[Appium] Non-default server args:
[Appium]   allowCors: true
[Appium] You have enabled CORS requests from any host. Be careful not to visit sites which could maliciously try to start Appium sessions on your machine
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"/Users/rarik/Downloads/dev_alfa_7.0.0.507.ipa","simpleIsVisibleCheck":true,"noReset":true,"bundleId":"com.doganonline.NesineAlfa","deviceName":"233c0b37697324bedbd547d50d9984c45959fbb6","fullReset":false,"sendKeyStrategy":"setValue","newCommandTimeout":320,"platformVersion":"11.4.1","automationName":"XCUITest","unicodeKeyboard":true,"platformName":"iOS","udid":"233c0b37697324bedbd547d50d9984c45959fbb6","resetKeyboard":true},"capabilities":{"alwaysMatch":{"appium:app":"/Users/rarik/Downloads/dev_alfa_7.0.0.507.ipa","appium:automationName":"XCUITest","appium:bundleId":"com.doganonline.NesineAlfa","appium:deviceName":"233c0b37697324bedbd547d50d9984c45959fbb6","appium:fullReset":false,"appium:newCommandTimeout":320,"appium:noReset":true,"platformName":"ios","appium:platformVersion":"11.4.1","appium:resetKeyboard":true,"appium:sendKeyStrategy":"setValue","appium:simpleIsVisibleCheck":true,"appium:udid":"233c0b37697324bedbd547d50d9984c45959fbb6","appium:unicode
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"app":"/Users/rarik/Downloads/dev_alfa_7.0.0.507.ipa","simpleIsVisibleCheck":true,"noReset":true,"bundleId":"com.doganonline.NesineAlfa","deviceName":"233c0b37697324bedbd547d50d9984c45959fbb6","fullReset":false,"sendKeyStrategy":"setValue","newCommandTimeout":320,"platformVersion":"11.4.1","automationName":"XCUITest","unicodeKeyboard":true,"platformName":"iOS","udid":"233c0b37697324bedbd547d50d9984c45959fbb6","resetKeyboard":true},null,{"alwaysMatch":{"appium:app":"/Users/rarik/Downloads/dev_alfa_7.0.0.507.ipa","appium:automationName":"XCUITest","appium:bundleId":"com.doganonline.NesineAlfa","appium:deviceName":"233c0b37697324bedbd547d50d9984c45959fbb6","appium:fullReset":false,"appium:newCommandTimeout":320,"appium:noReset":true,"platformName":"ios","appium:platformVersion":"11.4.1","appium:resetKeyboard":true,"appium:sendKeyStrategy":"setValue","appium:simpleIsVisibleCheck":true,"appium:udid":"233c0b37697324bedbd547d50d9984c45959fbb6","appium:unicodeKeyboard":true},"firstMatch":[{}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1564377652210 (08:20:52 GMT+0300 (GMT+03:00))
[Appium] Appium v1.13.0 creating new XCUITestDriver (v2.113.2) session
[Appium] Capabilities:
[Appium]   platformName: ios
[Appium]   app: /Users/rarik/Downloads/dev_alfa_7.0.0.507.ipa
[Appium]   automationName: XCUITest
[Appium]   bundleId: com.doganonline.NesineAlfa
[Appium]   deviceName: 233c0b37697324bedbd547d50d9984c45959fbb6
[Appium]   fullReset: false
[Appium]   newCommandTimeout: 320
[Appium]   noReset: true
[Appium]   platformVersion: 11.4.1
[Appium]   resetKeyboard: true
[Appium]   sendKeyStrategy: setValue
[Appium]   simpleIsVisibleCheck: true
[Appium]   udid: 233c0b37697324bedbd547d50d9984c45959fbb6
[Appium]   unicodeKeyboard: true
[debug] [BaseDriver] W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP desired capabilities {"app":"/Users/rarik/Downlo... were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"platformNa...
[BaseDriver] The following capabilities were provided, but are not recognized by appium: resetKeyboard, unicodeKeyboard.
[BaseDriver] Session created with session id: 315ccf93-5b60-473e-baf2-388047b74982
[debug] [XCUITest] Current user: 'rarik'
[debug] [XCUITest] Available devices: 
[XCUITest] Error: Unknown device or simulator UDID: '233c0b37697324bedbd547d50d9984c45959fbb6'
[XCUITest]     at XCUITestDriver.determineDevice (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:771:17)
[XCUITest]     at XCUITestDriver.start (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:269:40)
[XCUITest]     at XCUITestDriver.createSession (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:206:7)
[XCUITest]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:342:35)
[XCUITest]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:319:13)
[XCUITest]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:471:14)
[XCUITest]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:352:21)
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1564377653420 (08:20:53 GMT+0300 (GMT+03:00))
[debug] [W3C] Encountered internal error running command: Error: Unknown device or simulator UDID: '233c0b37697324bedbd547d50d9984c45959fbb6'
[debug] [W3C]     at XCUITestDriver.determineDevice (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:771:17)
[debug] [W3C]     at XCUITestDriver.start (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:269:40)
[debug] [W3C]     at XCUITestDriver.createSession (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:206:7)
[debug] [W3C]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:342:35)
[debug] [W3C]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:319:13)
[debug] [W3C]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:471:14)
[debug] [W3C]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:352:21)
[HTTP] <-- POST /wd/hub/session 500 1226 ms - 649
[HTTP] 
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"/Users/rarik/Downloads/dev_alfa_7.0.0.507.ipa","simpleIsVisibleCheck":true,"noReset":true,"bundleId":"com.doganonline.NesineAlfa","deviceName":"233c0b37697324bedbd547d50d9984c45959fbb6","fullReset":false,"sendKeyStrategy":"setValue","newCommandTimeout":320,"platformVersion":"11.4.1","automationName":"XCUITest","unicodeKeyboard":true,"platformName":"iOS","udid":"233c0b37697324bedbd547d50d9984c45959fbb6","resetKeyboard":true},"capabilities":{"alwaysMatch":{"appium:app":"/Users/rarik/Downloads/dev_alfa_7.0.0.507.ipa","appium:automationName":"XCUITest","appium:bundleId":"com.doganonline.NesineAlfa","appium:deviceName":"233c0b37697324bedbd547d50d9984c45959fbb6","appium:fullReset":false,"appium:newCommandTimeout":320,"appium:noReset":true,"platformName":"ios","appium:platformVersion":"11.4.1","appium:resetKeyboard":true,"appium:sendKeyStrategy":"setValue","appium:simpleIsVisibleCheck":true,"appium:udid":"233c0b37697324bedbd547d50d9984c45959fbb6","appium:unicode
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"app":"/Users/rarik/Downloads/dev_alfa_7.0.0.507.ipa","simpleIsVisibleCheck":true,"noReset":true,"bundleId":"com.doganonline.NesineAlfa","deviceName":"233c0b37697324bedbd547d50d9984c45959fbb6","fullReset":false,"sendKeyStrategy":"setValue","newCommandTimeout":320,"platformVersion":"11.4.1","automationName":"XCUITest","unicodeKeyboard":true,"platformName":"iOS","udid":"233c0b37697324bedbd547d50d9984c45959fbb6","resetKeyboard":true},null,{"alwaysMatch":{"appium:app":"/Users/rarik/Downloads/dev_alfa_7.0.0.507.ipa","appium:automationName":"XCUITest","appium:bundleId":"com.doganonline.NesineAlfa","appium:deviceName":"233c0b37697324bedbd547d50d9984c45959fbb6","appium:fullReset":false,"appium:newCommandTimeout":320,"appium:noReset":true,"platformName":"ios","appium:platformVersion":"11.4.1","appium:resetKeyboard":true,"appium:sendKeyStrategy":"setValue","appium:simpleIsVisibleCheck":true,"appium:udid":"233c0b37697324bedbd547d50d9984c45959fbb6","appium:unicodeKeyboard":true},"firstMatch":[{}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1564377660320 (08:21:00 GMT+0300 (GMT+03:00))
[Appium] Appium v1.13.0 creating new XCUITestDriver (v2.113.2) session
[Appium] Capabilities:
[Appium]   platformName: ios
[Appium]   app: /Users/rarik/Downloads/dev_alfa_7.0.0.507.ipa
[Appium]   automationName: XCUITest
[Appium]   bundleId: com.doganonline.NesineAlfa
[Appium]   deviceName: 233c0b37697324bedbd547d50d9984c45959fbb6
[Appium]   fullReset: false
[Appium]   newCommandTimeout: 320
[Appium]   noReset: true
[Appium]   platformVersion: 11.4.1
[Appium]   resetKeyboard: true
[Appium]   sendKeyStrategy: setValue
[Appium]   simpleIsVisibleCheck: true
[Appium]   udid: 233c0b37697324bedbd547d50d9984c45959fbb6
[Appium]   unicodeKeyboard: true
[debug] [BaseDriver] W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP desired capabilities {"app":"/Users/rarik/Downlo... were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"platformNa...
[BaseDriver] The following capabilities were provided, but are not recognized by appium: resetKeyboard, unicodeKeyboard.
[BaseDriver] Session created with session id: 0bceaf13-27cc-44b2-b63c-b55c7456b81b
[debug] [XCUITest] Current user: 'rarik'
[debug] [XCUITest] Available devices: 
[XCUITest] Error: Unknown device or simulator UDID: '233c0b37697324bedbd547d50d9984c45959fbb6'
[XCUITest]     at XCUITestDriver.determineDevice (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:771:17)
[XCUITest]     at XCUITestDriver.start (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:269:40)
[XCUITest]     at XCUITestDriver.createSession (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:206:7)
[XCUITest]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:342:35)
[XCUITest]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:319:13)
[XCUITest]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:471:14)
[XCUITest]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:352:21)
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1564377660484 (08:21:00 GMT+0300 (GMT+03:00))
[debug] [W3C] Encountered internal error running command: Error: Unknown device or simulator UDID: '233c0b37697324bedbd547d50d9984c45959fbb6'
[debug] [W3C]     at XCUITestDriver.determineDevice (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:771:17)
[debug] [W3C]     at XCUITestDriver.start (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:269:40)
[debug] [W3C]     at XCUITestDriver.createSession (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:206:7)
[debug] [W3C]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:342:35)
[debug] [W3C]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:319:13)
[debug] [W3C]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:471:14)
[debug] [W3C]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:352:21)
[HTTP] <-- POST /wd/hub/session 500 166 ms - 649
[HTTP]

**Comment by mykola-mokhnach** [comment]
> Unknown device or simulator UDID: '233c0b37697324bedbd547d50d9984c45959fbb6'

Are you sure the device with the given id is connected and is visible in `idevice_id  --list` output?

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
