### ISSUE TITLE
Issue in Appium Main.js

### ISSUE THREAD

**Issue by aruvimal** [appium/appium#12979]
## The problem

i have noticed that appium ### main.js ###  is located in two different path. But not sure which we have to use it and also which is right approach. Please advise

**
#1 
/usr/local/lib/node_modules/appium/build/lib/main.js

#2 
/Users/vz8zw5/node_modules/node/lib/node_modules/appium/build/lib/main.js**

In the script, 

service = AppiumDriverLocalService.buildService (new AppiumServiceBuilder()  
							.withAppiumJS(new File("/usr/local/lib/node_modules/appium/build/lib/main.js"))
							.usingPort(4723).withIPAddress("127.0.0.1"));

i'm getting below error. 

## ERROR

org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: The application at '/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk' is not writeable. Please grant write permissions to this file or to its parent folder '/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks' for the Appium process, so it could sign the application
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'USCHAMNMOG0JK78', ip: '2606:a000:1215:c3b2:c054:5419:4897:3562', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.5', java.version: '1.8.0_91'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: The application at '/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk' is not writeable. Please grant write permissions to this file or to its parent folder '/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks' for the Appium process, so it could sign the application
    at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:826:9)
    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:447:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'

## Environment
info AppiumDoctor Appium Doctor v.1.11.1
info AppiumDoctor ### Diagnostic for necessary dependencies starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: node_modules/.bin/node
info AppiumDoctor  ✔ Node version is 12.6.0
info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ Xcode Command Line Tools are installed in: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ DevToolsSecurity is enabled.
info AppiumDoctor  ✔ The Authorization DB is set up properly.
info AppiumDoctor  ✔ Carthage was found at: node_modules/.bin/carthage. Installed version is: 1.0.6
info AppiumDoctor  ✔ HOME is set to: /Users/vz8zw5
info AppiumDoctor  ✔ ANDROID_HOME is set to: /Users/vz8zw5/Library/Android/sdk
info AppiumDoctor  ✔ JAVA_HOME is set to: /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home
info AppiumDoctor  ✔ adb exists at: /Users/vz8zw5/Library/Android/sdk/platform-tools/adb
info AppiumDoctor  ✔ android exists at: /Users/vz8zw5/Library/Android/sdk/tools/android
info AppiumDoctor  ✔ emulator exists at: /Users/vz8zw5/Library/Android/sdk/tools/emulator
info AppiumDoctor  ✔ Bin directory of $JAVA_HOME is set
info AppiumDoctor ### Diagnostic for necessary dependencies completed, no fix needed. ###
info AppiumDoctor 
info AppiumDoctor ### Diagnostic for optional dependencies starting ###
WARN AppiumDoctor  ✖ opencv4nodejs cannot be found.
WARN AppiumDoctor  ✖ ffmpeg cannot be found
WARN AppiumDoctor  ✖ mjpeg-consumer cannot be found.
WARN AppiumDoctor  ✖ idb and idb_companion are not installed
WARN AppiumDoctor  ✖ applesimutils cannot be found
WARN AppiumDoctor  ✖ idevicelocation cannot be found
WARN AppiumDoctor  ✖ ios-deploy cannot be found
WARN AppiumDoctor  ✖ ios_webkit_debug_proxy cannot be found
WARN AppiumDoctor  ✖ ifuse cannot be found
WARN AppiumDoctor  ✖ bundletool.jar cannot be found
info AppiumDoctor ### Diagnostic for optional dependencies completed, 10 fixes possible. ###
info AppiumDoctor 
info AppiumDoctor ### Optional Manual Fixes ###
info AppiumDoctor The configuration can install optionally. Please do the following manually:
WARN AppiumDoctor  ➜ Why opencv4nodejs is needed and how to install it: https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/image-comparison.md
WARN AppiumDoctor  ➜ ffmpeg is needed to record screen features. Please read https://www.ffmpeg.org/ to install it
WARN AppiumDoctor  ➜ mjpeg-consumer module is required to use MJPEG-over-HTTP features. Please install it with 'npm i -g mjpeg-consumer'.
WARN AppiumDoctor  ➜ Why idb is needed and how to install it: https://github.com/appium/appium-idb
WARN AppiumDoctor  ➜ Why applesimutils is needed and how to install it: http://appium.io/docs/en/drivers/ios-xcuitest/
WARN AppiumDoctor  ➜ idevicelocation is used to set geolocation for real device. Please read https://github.com/JonGabilondoAngulo/idevicelocation to install it
WARN AppiumDoctor  ➜ ios-deploy is used to install iOS applications to real device. Please read http://appium.io/docs/en/drivers/ios-xcuitest-real-devices/ to install it
WARN AppiumDoctor  ➜ ios_webkit_debug_proxy is used to proxy requests from Appium to MobileSafari running on real device. Please read https://github.com/google/ios-webkit-debug-proxy to install it
WARN AppiumDoctor  ➜ ifuse is used to manage files/folders against a real device. Please read https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios/ios-xctest-file-movement.md to install it
WARN AppiumDoctor  ➜ bundletool.jar is used to handle Android App Bundle. Please read http://appium.io/docs/en/writing-running-appium/android/android-appbundle/ to install it

**Comment by KazuCocoa** [comment]
I assume your environment has multiple Appium installed various way.
e.g. `npm install -g`, npm install (locally) etc...
node env installed via brew, view nvm, via nodebrew etc...

Base node command basically decides which path the node uses.
Please post to https://discuss.appium.io about building environment etc.

**Comment by Thevakajan** [comment]
Encountered internal error running command: Error: Process didn't end after 10000ms (cmd: '/home/theva/Downloads/chromedriver --url-base\=wd/hub --port\=8000 --adb-port\=5037 --verbose')
[debug] [W3C]     at Timeout._onTimeout (/usr/local/lib/node_modules/appium/node_modules/teen_process/lib/subprocess.js:231:16)
[debug] [W3C]     at listOnTimeout (internal/timers.js:531:17)
[debug] [W3C]     at processTimers (internal/timers.js:475:7)
[debug] [W3C] Destroying socket connection
[HTTP] <-- POST /wd/hub/session 500 36368 ms - 773
[HTTP]

**Comment by Hemanthdeva** [comment]
Any solution for this?, I am experiencing same issue. I installed appium from npm and appium GUI.

Do i need to uninstall one?
