### ISSUE TITLE
UIAutomatorviewer and Appium interpret a hybrid app hierarchy wrongly

### ISSUE THREAD

**Issue by ElgarEdwards** [appium/appium#12978]
## The problem

A hybrid app that is correctly interpreted by UIAutomatorviewer and Appium (from the hierarchy point of view) suddenly shows a different hierarchy after a Google Play services update by using again UIAutomatorviewer for the elements discovery or by running an script by using Appium.

## Environment

* Appium version that exhibits the issue: 1.7 and beyond
* Desktop OS/version used to run Appium: Windows 10
* Mobile platform/version under test: Android 8.0.0

## Details

Being the Android hybrid app in a pre-failure state (lets call it "A" state) the UIAutomatorviewer interprets the webcode properly: In this case most of the elements are referenced by the resource-id locator and their contents are located in the content-description attribute.
All the scripts designed for that Android hybrid app automation run under Appium properly by using the locators defined by UIAutomatorviewer.

However, the app changes from the A state to a new one (state "B") after a Google Play services update and then the structure showed from UIAutomatorviewer is certainly different: Some elements are not properly assigned to the state A resource-id and the contents that previously where located in the content-description are now located in the text attribute.
In this case those very scripts that run under Appium now don't work since Appium tries to find elements that don't exist any more.

Case A UIAutomator screenshot:
=======================
![case A-github](https://user-images.githubusercontent.com/53319423/61928508-f271ee80-af78-11e9-95d4-0a2bd59187f7.png)

Case B UIAutomator screenshot:
=======================
![case B-github](https://user-images.githubusercontent.com/53319423/61928515-f867cf80-af78-11e9-84d3-91f3aa134678.png)

Note that by using a chrome inspector, in order to know wether the web code changes from A to B, nothing changes. It just changes the structure given by UIAutomatorviewer, which is completely different from A to B. Moreover, UIAutomatorviewer shows elements that are not displayed directly by the app. 

The main question is: Why does the UIAutomator and, consequently, Appium, interpret a different hybrid app structure meanwhile the "source" web code keep its structure after a Google Play services update?

**Comment by KazuCocoa** [comment]
Basically, Appium builds hierarchy from `android.view.accessibility.AccessibilityNodeInfo`.
UIAutomatorviewer also gets data similar method(I forgot exact method tho.)
Espresso is from viewgroup.

If the Google Play services update affects such accessibility stuff, it can happen.
It's better to ask google about if the update affects AccessibilityNodeInfo or any accessibility stuff, I think.
