### ISSUE TITLE
why appium create so much tcp connect for the same devices? and never release tcp port

### ISSUE THREAD

**Issue by mingyanzou** [appium/appium#12982]
## The problem
Appium create so much tcp connect for the same devices, and never release tcp port

<img width="852" alt="屏幕快照 2019-07-26 下午8 53 37" src="https://user-images.githubusercontent.com/40393494/61953005-e7a27280-afe7-11e9-86a1-7a031316b4c9.png">

## Environment

* Appium version (or git revision) that exhibits the issue:1.13.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: ubuntu 
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: ANDROID 8.0
* Real device or emulator/simulator: REAL DEVICE
* Appium CLI or Appium.app|exe: APPIUM - P 

## Details
 Step 1: start appium by command line appium -p 4732 .
 Step 2: do automation test.
 Step 3: kill appium server. and do it again from step 1. but adb tcp port never release, it will be create a new port for the next test case.

**Comment by KazuCocoa** [comment]
mm, maybe something happened in the case...
I could not reproduce it.


```
[debug] [UiAutomator2] Forwarding UiAutomator2 Server port 6790 to 8200
[debug] [ADB] Forwarding system: 8200 to device: 6790
[debug] [ADB] Running '/Users/kazu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward tcp\:8200 tcp\:6790'
[debug] [ADB] Running '/Users/kazu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell settings get global animator_duration_scale'
[debug] [ADB] Running '/Users/kazu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell settings get global transition_animation_scale'
[debug] [ADB] Running '/Users/kazu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell settings get global window_animation_scale'
....
```

The above forward happened every create session.
When `quite` was called, below happened. Calling create session witout `quite` also forward 8200 (forward the same port again)

```
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8200
[debug] [ADB] Running '/Users/kazu/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp\:8200'
[debug] [BaseDriver] Event 'quitSessionFinished' logged at 1564231758170 (21:49:18 GMT+0900 (Japan Standard Time))
[debug] [W3C (7cfcad66)] Received response: null
[debug] [W3C (7cfcad66)] But deleting session, so not returning
[debug] [W3C (7cfcad66)] Responding to client with driver.deleteSession() result: null
```

My env is macOS tho.

Could you attach your Appium log?

**Comment by mykola-mokhnach** [comment]
The forwarded ports should be cleaned after each driver session is deleted. Make sure you quit your driver properly in each test teardown

**Comment by mingyanzou** [comment]
driver.quite() works for me, thanks!
