### ISSUE TITLE
Failed to launch pre-installed (system) App on real device

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#12981]
## The problem

Current appium master failed to launch bundle id like `com.apple.Preferences` (system apps) because of ` Original error: App with bundle identifier 'com.apple.Preferences' unknown` even if Appium 1.14.0 worked. Apps on user-level worked.

This happens only on iOS real device.

## Environment

* Appium version (or git revision) that exhibits the issue: master
* Last Appium version that did not exhibit the issue (if applicable): 1.14.0
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe): 10.16.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: ios 12.4
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

## Details

- appium-ios-device is 0.5.0
- appium-ios-driver is 4.3.0
- appium-xcuitest-driver is 2.123.0

## Link to Appium logs

https://gist.github.com/KazuCocoa/553a6b3e239b89959483af8b444e9c60

**Comment by KazuCocoa** [comment]
Maybe, ios-device search only user level apps
cc @umutuzgur

**Comment by umutuzgur** [comment]
@KazuCocoa You are right. I can change that quickly

**Comment by umutuzgur** [comment]
I published the fix. There are some downsides of listing system apps. It takes 2-3 seconds to list them whereas less then 1 sec for User apps

**Comment by KazuCocoa** [comment]
thanks:)
