### ISSUE TITLE
error starting appium server : listen EADDRINSUE 0.0.0.0:4723

### ISSUE THREAD

**Issue by tahirakhlaaq** [appium/appium#12980]
## The problem

When i start the appium gui i get this "error starting appium server : listen EADDRINSUE 0.0.0.0:4723"

## Environment

* Appium version -v1.13
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: 8.1 and 9
* Real device or emulator/simulator: Both
* Appium CLI or Appium.app|exe: appium.exe

## Details

whenever i start the appium Gui

![image](https://user-images.githubusercontent.com/50105101/61930577-ccaa1100-af9b-11e9-86f3-8844da2eff03.png)

**Comment by umutuzgur** [comment]
@tahirakhlaaq There must be another process listening to port 4723 and it would be most likely another leftover Appium process. Could you kill that process? You can also just restart your computer and try again.

**Comment by LayMui** [comment]
Hi, I restart the PC, still the same error, I am using Appium 1.19.1
