### ISSUE TITLE
Unable to build XCUI WebDriverAgent 

### ISSUE THREAD

**Issue by sebastiandine** [appium/appium#12992]
## The problem

I am facing errors when trying to build the XCUI WebDriver Agent either automatically through Appium or manually.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13.0
* Last Appium version that did not exhibit the issue (if applicable): - 
* Desktop OS/version used to run Appium: Mac OS 10.14.5
* Node.js version (unless using Appium.app|exe): 12.6.0
* Npm or Yarn package manager: npm 6.9.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: 12.1
* Appium CLI or Appium.app|exe: CLI

## Details

I am trying to build the WebDriverAgent by running the following script within the Appium project:
`$ cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent`
`$ ./Scripts/bootstrap.sh`

This is the corresponding terminal output:
```
Fetching dependencies
*** Checking out RoutingHTTPServer at "v1.0.2"
*** Checking out YYCache at "1.1.0"
*** Checking out CocoaAsyncSocket at "7.6.3"
*** xcodebuild output can be found in /var/folders/rb/txhm8kys5fd0b3k5rq55_7400000gp/T/carthage-xcodebuild.0Eifmr.log
*** Downloading CocoaAsyncSocket.framework binary at "Version 7.6.3"
*** Building scheme "RoutingHTTPServer tvOS" in RoutingHTTPServer.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer/RoutingHTTPServer.xcodeproj -scheme RoutingHTTPServer\ tvOS -configuration Release -derivedDataPath /Users/sdine/Library/Caches/org.carthage.CarthageKit/DerivedData/10.3_10G8/RoutingHTTPServer/v1.0.2 -sdk appletvos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/rb/txhm8kys5fd0b3k5rq55_7400000gp/T/RoutingHTTPServer SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/rb/txhm8kys5fd0b3k5rq55_7400000gp/T/carthage-xcodebuild.0Eifmr.log
```

As we can see in the log, there seem to be missing imports.

## Link to Appium logs

https://gist.github.com/sebastiandine/3803f54a2996d3469cdda019a00ee0ca

## Code To Reproduce Issue [ Good To Have ]

-

**Comment by KazuCocoa** [comment]
Can you follow below steps?

```
$ git clone git@github.com:appium/WebDriverAgent.git
$ cd WebDriverAgent
$ ./Scripts/bootstrap.sh
```

**Comment by sebastiandine** [comment]
> Can you follow below steps?
> 
> ```
> $ git clone git@github.com:appium/WebDriverAgent.git
> $ cd WebDriverAgent
> $ ./Scripts/bootstrap.sh
> ```

Still the same result

**Comment by KazuCocoa** [comment]
Thanks.

Something happened on your env, but I could not reproduce it yet on my env even if I switched Xcode versions.
mmm...

**Comment by KazuCocoa** [comment]
Could you run `carthage bootstrap --verbose` in `WebDriverAgent` checked out as `git clone git@github.com:appium/WebDriverAgent.git`?

**Comment by KazuCocoa** [comment]
and could you share the output?

**Comment by sebastiandine** [comment]
[carthage_bootstrap.log](https://github.com/appium/appium/files/3447043/carthage_bootstrap.log)

**Comment by KazuCocoa** [comment]
Not sure the below is the issue, but your environment has interesting environment..

- Your clang
```
/anaconda3/bin/x86_64-apple-darwin13.4.0-clang
```

- My clang
```
/Applications/Xcode_10.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
```

Did anaconda dependency break your clang build environment?


The Xcode 10.3 is below.

```
$ /Applications/Xcode_10.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -v
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
```

**Comment by KazuCocoa** [comment]
```
    /anaconda3/bin/x86_64-apple-darwin13.4.0-ld -arch x86_64 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -L/Users/sdine/Library/Caches/org.carthage.CarthageKit/DerivedData/9.1_9B55/RoutingHTTPServer/v1.0.2/Build/Intermediates.noindex/ArchiveIntermediates/RoutingHTTPServer/BuildProductsPath/Release -F/Users/sdine/Library/Caches/org.carthage.CarthageKit/DerivedData/9.1_9B55/RoutingHTTPServer/v1.0.2/Build/Intermediates.noindex/ArchiveIntermediates/RoutingHTTPServer/BuildProductsPath/Release -filelist /Users/sdine/Library/Caches/org.carthage.CarthageKit/DerivedData/9.1_9B55/RoutingHTTPServer/v1.0.2/Build/Intermediates.noindex/ArchiveIntermediates/RoutingHTTPServer/IntermediateBuildFilesPath/RoutingHTTPServer.build/Release/RoutingHTTPServer.build/Objects-normal/x86_64/RoutingHTTPServer.LinkFileList -install_name @rpath/RoutingHTTPServer.framework/Versions/A/RoutingHTTPServer -Xlinker -rpath -Xlinker @executable_path/../Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -mmacosx-version-min=10.7 -Xlinker -object_path_lto -Xlinker /Users/sdine/Library/Caches/org.carthage.CarthageKit/DerivedData/9.1_9B55/RoutingHTTPServer/v1.0.2/Build/Intermediates.noindex/ArchiveIntermediates/RoutingHTTPServer/IntermediateBuildFilesPath/RoutingHTTPServer.build/Release/RoutingHTTPServer.build/Objects-normal/x86_64/RoutingHTTPServer_lto.o -fobjc-arc -fobjc-link-runtime -lxml2 -single_module -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/sdine/Library/Caches/org.carthage.CarthageKit/DerivedData/9.1_9B55/RoutingHTTPServer/v1.0.2/Build/Intermediates.noindex/ArchiveIntermediates/RoutingHTTPServer/IntermediateBuildFilesPath/RoutingHTTPServer.build/Release/RoutingHTTPServer.build/Objects-normal/x86_64/RoutingHTTPServer_dependency_info.dat -o /Users/sdine/Library/Caches/org.carthage.CarthageKit/DerivedData/9.1_9B55/RoutingHTTPServer/v1.0.2/Build/Intermediates.noindex/ArchiveIntermediates/RoutingHTTPServer/IntermediateBuildFilesPath/UninstalledProducts/macosx/RoutingHTTPServer.framework/Versions/A/RoutingHTTPServer
ld: unknown option: -dynamiclib
```

`-dynamiclib` should work as well

**Comment by KazuCocoa** [comment]
close once since the cause is clang environment for now.

**Comment by sebastiandine** [comment]
Turning off the anaconda environment worked. Now I was able to compile the pure WebDriverAgent project. However, when trying the same within the Appium project, after the compilation of the Xcode projects, further NodeJs tasks are triggered which seem to fail.

Here is what ist prompted on terminal:
`
Fetching dependencies
*** Checking out YYCache at "1.1.0"
*** Checking out CocoaAsyncSocket at "7.6.3"
*** Checking out RoutingHTTPServer at "v1.0.2"
*** xcodebuild output can be found in /var/folders/rb/txhm8kys5fd0b3k5rq55_7400000gp/T/carthage-xcodebuild.wi39QK.log
*** Downloading CocoaAsyncSocket.framework binary at "Version 7.6.3"
*** Building scheme "RoutingHTTPServer tvOS" in RoutingHTTPServer.xcodeproj
*** Building scheme "RoutingHTTPServer iOS" in RoutingHTTPServer.xcodeproj
*** Building scheme "YYCache tvOS" in YYCache.xcodeproj
*** Building scheme "YYCache iOS" in YYCache.xcodeproj
Building Inspector
Creating bundle directory...
Fetching Inspector dependencies...
npm WARN deprecated core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated css-list@0.1.3: Deprecated.
npm WARN deprecated postcss-single-charset@0.3.0: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated browserslist@0.4.0: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated flatten@0.0.1: I wrote this module a very long time ago; you should use something else.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.

> fsevents@1.2.9 install /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" is installed via remote

> core-js@2.6.9 postinstall /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/babel-runtime/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN react-dom@15.6.2 requires a peer of react@^15.6.2 but none is installed. You must install peer dependencies yourself.
npm WARN web-driver-inspector@1.0.0 No repository field.

added 753 packages from 542 contributors and audited 2652 packages in 17.779s
found 20 vulnerabilities (6 low, 13 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
Validating Inspector

Oops! Something went wrong! :(

ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

    eslint --init

ESLint looked for configuration files in /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/js and its ancestors.

If you think you already have a configuration file or if you need more help, please stop by the ESLint chat room: https://gitter.im/eslint/eslint
`

**Comment by KazuCocoa** [comment]
You can ignore `inspector` related build. They have been removed in recent Appium/WDA repo

**Comment by sebastiandine** [comment]
How does the bootstrap script determine the clang binary it is using? When I start the testautomation through Appium, the build of the WebDriverAgent is failing again. The log tells me, that it is now not using Anaconda anymore but a different clang version that I have installed through Xcode.

**Comment by KazuCocoa** [comment]
It calls `xcodebuild` via Node process.
e.g. https://github.com/appium/appium-xcuitest-driver/blob/aa9b6648ef96b5ec9cde86eea93d4ed031fbe4da/lib/wda/xcodebuild.js#L114
clang is handled by xcodebuild.
https://github.com/appium/WebDriverAgent/blob/master/Scripts/bootstrap.sh also calls simply `carthage`, for example.

If your environment hacked some Xcode internals via some dependencies like anaconda stuff, some changes happen inside xcodebuild, I guess.

**Comment by sebastiandine** [comment]
Ok thanks. I now solved this issue via transferring my Anaconda stuff into a Docker container since it caused too much trouble with this. Now WebDriverAgent is building and the app is actually starting via Appium.
