### ISSUE TITLE
When orientation is landscape elements return their size like there are navigation bar

### ISSUE THREAD

**Issue by gyarang** [appium/appium#12993]
## The problem
![MainActivity_LANDSCAPE_LG V30 png_edited](https://user-images.githubusercontent.com/13360457/62117857-b1bb0200-b2f7-11e9-9241-16219f34bd7e.png)

When orientation is 'Landscape' width size of elements are reduced like there are navigation bar.

## Environment

Appium version: 1.13.0
Desktop OS: Windows 10
Test device: LG V30(Android ver.8.0.0), Galaxy S8(Android 9)
Python version: 3.7

## Details

I was trying to take image of application and draw rectangles on elements. It worked well when orientation was portrait, but it doesn't worked well when orientation was landscape.
I measured that empty place and found out it had same size of navigation bar.
This happened on both devices I tested.

## Link to Appium logs

https://gist.github.com/gyarang/7cd6c117f07dcf5b59b719cd18ab47af

## Code To Reproduce Issue [ Good To Have ]

I get elements by 
`self.driver.find_elements_by_android_uiautomator('new UiSelector().focusable(true)')`

and get it's size by
`element.size`

**Comment by mykola-mokhnach** [comment]
It might be that element size is retrieved too fast after changing the orientation, so small delay might help. Also, it can be a problem of UiAutomator itself. You could use any accessibility inspector to verify that. Appium itself does not do any magic and retrieves the data from the accessibility framework. 

One can also try Espresso driver as an alternative. This one has access to the internal views hierarchy and does not depend much on the accessibility.
