### ISSUE TITLE
iOS Appium on BrowserStack Falls Back to MSONWP instead of Using Expected W3C Protocol

### ISSUE THREAD

**Issue by pablopaul** [appium/appium#12991]
## The problem

I try to run a test which sets timeouts (`/timeouts` endpoint) on iOS on BrowserStack through Appium 1.9.1. 
I am using WebdriverIO as client library.

The test looks like:

```
describe('timeouts', () => {
    it('should be configurable', () => {
        browser.setTimeouts(1000, 2000, 3000);
    });
});
```

The test fails with `Error: Parameters were incorrect. We wanted {"required":["type","ms"]} and you sent ["implicit","pageLoad","script"]`.

This is because on BrowserStack Appium detects MSONWP protocol, but the timeout format is only compatible with W3C protocol.

Why does `determineProtocol` (https://github.com/appium/appium-base-driver/blob/master/lib/basedriver/driver.js#L245) gets the wrong protocol on BrowserStack?

How can we fix this?

## Environment

* Appium v 1.9.1 (latest available in BrowserStack)
* Desktop OS/version used to run Appium: not sure, this is happening on BrowserStack
* Node.js version (unless using Appium.app|exe): not sure, this is happening on BrowserStack
* Npm or Yarn package manager: not sure, this is happening on BrowserStack
* Mobile platform/version under test: iOS 11.2
* Real device or emulator/simulator: real device: iPhone X
* Appium CLI or Appium.app|exe: not sure, this is happening on BrowserStack

## Details

Local capabilities set through webdriverio which are working

```
config.capabilities = [
    {
        // The defaults you need to have in your config
        browserName: 'safari',
        platformName: 'iOS',
        maxInstances: 1,
        // For W3C the appium capabilities need to have an extension prefix
        // This is `appium:` for all Appium Capabilities which can be found here
        // http://appium.io/docs/en/writing-running-appium/caps/
        'appium:deviceName': 'iPhone X',
        'appium:platformVersion': '12.0',
        'appium:orientation': 'PORTRAIT',
        // `automationName` will be mandatory, see
        // https://github.com/appium/appium/releases/tag/v1.13.0
        'appium:automationName': 'XCUITest',
        'appium:newCommandTimeout': 240,
    },
];
```

The capabilities for BrowserStack are looking like this:

```
config.capabilities = [
    {   
        platformName: "iOS",
        deviceName: "iPhone X",
        browserName: "safari",
        'appium:automationName': 'XCUITest',
        'bstack:options' : {
            'deviceName' : 'iPhone X',
            'realMobile' : 'true',
        },
    },
];
```

## Link to Appium logs

https://gist.github.com/pablopaul/6c2141d5023e65532ae838da84f15c10

**Comment by wswebcreation** [comment]
@pablopaul 

99,9% sure this is not an Appium issue, but a WebdriverIO/Browserstack issue. WebdriverIO determines, based on the response of Browserstack, if they talk W3C or not. Then WebdriverIO uses that or the JSONWireprotocol to communicate with Browserstack.

Please close this one and file an issue on the WebdriverIO github project and provide the WebdriverIO logs

**Comment by pablopaul** [comment]
Thanks @wswebcreation.

Closed in favour of https://github.com/webdriverio/webdriverio/issues/4273,

**Comment by MoOoG** [comment]
Having the same issue. I reported the issue to BS support and shared documentation, but did not get their response of any solution.
