### ISSUE TITLE
stopRecordingScreen pidof screenrecord incorrectly identify pids for killing and corrupt video recording

### ISSUE THREAD

**Issue by vdelendik** [appium/appium#12994]
## The problem
Getting PIDs of screenrecord incorrectly append adb 5037 port into the PIDs list. As result killing operation can't stop video recording and video in most cases is corrupted.

As workaround I applied such hotfix in:
appium/node_modules/appium/node_modules/appium-adb/build/lib/tools/adb-commands.js

return (yield this.shell(shellCommand)).split(/\s+/).map(x => parseInt(x, 10)).filter(x => _lodash.default.isInteger(x));
changed to
return (yield this.shell(shellCommand)).**replace("5037", "")**.split(/\s+/).map(x => parseInt(x, 10)).filter(x => _lodash.default.isInteger(x));

## Environment
* Appium version (or git revision) that exhibits the issue:
1.13.0
* Last Appium version that did not exhibit the issue (if applicable):
Seems like in 1.12.0 there were no such issues with video recording but not sure
* Desktop OS/version used to run Appium:
Linux Ubuntu 16
* Node.js version (unless using Appium.app|exe):
8.16.0
* Npm or Yarn package manager:
6.4.1
* Mobile platform/version under test:
Android 6-9
* Real device or emulator/simulator:
real devices

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
https://gist.github.com/vdelendik/9c491933ea05813f23350380bf4ad440

**Comment by mykola-mokhnach** [comment]
Do you get the same output if the given shell pidof command executed manually?

**Comment by vdelendik** [comment]
pidof command running via cmd is good:

Server side:
root@d8f25df2cdab:/app# adb -s UDID shell pidof screenrecord
23941
Device side:
payton_sprout:/ $ ps -ef | grep screenrecord
shell        23941  2671 4 15:54:31 ?     00:00:05 screenrecord --time-limit 180 --bugreport /sdcard/1565034835113.mp4

payton_sprout:/ $ pidof screenrecord
23941

Also tested all kind of formats with full adp path, port as argument etc:
root@ddb7ae76754c:/app# adb shell pidof screenrecord
14202
root@ddb7ae76754c:/app# adb -P 5037 shell pidof screenrecord
14202
root@ddb7ae76754c:/app# /opt/android-sdk-linux/platform-tools/adb -P 5037 shell pidof screenrecord
14202

But when the same command is executed via Appium it somehow append 5037 port from "-P 5037"
