### ISSUE TITLE
HideKeyboard fails for numeric keyboard

### ISSUE THREAD

**Issue by KthProg** [appium/appium#12997]
Probably because there is no done or return button. iOS 12.4

**Comment by mykola-mokhnach** [comment]
Unfortunately there is no way to workaround that with xctest. You can only hide the keyboard same way a normal user would do it.

Closed as duplicate

**Comment by KthProg** [comment]
Excuse me what? Appium is the one that's failing here. The keyboard should be hidden in a way that doesn't crash the tests, are you kidding me? I changed my tests to simply click outside of the keyboard and that works fine. Just update Appium to do the same on a numeric keyboard for iOS, how is that a third party problem?

**Comment by imurchie** [comment]
There is no way for Appium to know where on any given app it is appropriate to click outside the keyboard. Choosing a random place to click would, if there were something clickable there, cause potentially awful consequences.
