### ISSUE TITLE
[iOS 13 Beta] Unable to switch context to webview as /contexts call returns only native view when the app is on SafariViewController

### ISSUE THREAD

**Issue by sonamkuk** [appium/appium#12995]
## The problem
I am working on a hybrid app where I need to switch the context from Native view to WebView when the app opens up a SafariViewController, but for the /contexts call, I am getting this response. The issue is ONLY there for iOS 13 Beta devices. This is working FINE in iOS 12 devices

{
  "status": 0,
  "value": [
    "NATIVE_APP"
  ],
  "sessionId": "980c3541-68ec-419e-9475-345c5547d5e7"
}

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.0
* Mobile platform/version under test: iOS 13 Beta. It ran fine with iOS 12.2 devices
* Real device or emulator/simulator: Real Device

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by imurchie** [comment]
This is most likely a problem with `ios-webkit-debug-proxy`. They are still working on iOS 13 support (see https://github.com/google/ios-webkit-debug-proxy/pull/317).

Soon you should be able to try our beta of support for real device webviews without using `iwdp`.

**Comment by umutuzgur** [comment]
@sonamkuk You can try appium@beta. iwdp is no longer a dependency in Appium

**Comment by imurchie** [comment]
You can try running the latest Appium beta (by running `npm uninstall -g appium && npm install -g appium@beta`). In this, `ios-webkit-debug-proxy` should not be necessary.

**Comment by sonamkuk** [comment]
Thanks. I tried with appium@beta on iOS 13 simulator and Its working fine without iwdp

**Comment by mykola-mokhnach** [comment]
Closed as fixed

**Comment by mithunkanchi** [comment]
Hey Guys, I am able to get the context view but not able to set it.

 System.out.println("context view name"+lastestContextView)
The above statement returns context view nameWEBVIEW_7336.1

But it fails in the below statement.
 if (lastestContextView.contains("WEBVIEW_")){
                this.iosDriver.context(lastestContextView);
                break;
 }

Any pointers would be of great help.
