### ISSUE TITLE
Xcode couldn't find any iOS App Development provisioning profiles matching 'com.facebook.Webdriver....

### ISSUE THREAD

**Issue by FirstAM** [appium/appium#12996]
## The problem

Hi , when i try to sign WDA for real device without open xcode i get fail 

` error: No profiles for 'com.facebook.Webdriver.Topface.2019' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.facebook.Webdriver.Topface.2019'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'WebDriverAgentRunner')`

And branch master 6a4c3b97 configure keyboard pref to make tests stable (#172) building fine 

I use xcodeConfigFile and branch WDA  master cd812565 0.5.0

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: IOS 
* Real device or emulator/simulator:  emulator/simulator
* Appium CLI or Appium.app|exe:

## Details

Appium Log 
[appium_logs_257940ddbc658253f24e79b6fd0085e2fbe87813_0.txt](https://github.com/appium/appium/files/3447161/appium_logs_257940ddbc658253f24e79b6fd0085e2fbe87813_0.txt)

**Comment by KazuCocoa** [comment]
Does your provisioning file valid for `com.facebook.*`?
http://appium.io/docs/en/drivers/ios-xcuitest-real-devices/

**Comment by FirstAM** [comment]
> Does your provisioning file valid for `com.facebook.*`?
> http://appium.io/docs/en/drivers/ios-xcuitest-real-devices/

When I try to build from Xcode, the build is fine.
I think the security file is valid.
But just in case, how can I check a valid file or not?

**Comment by FirstAM** [comment]
I found where I was wrong . The Xcode show wrong TEAM ID . I put this ID to xcconfig and have a fail. 
Thank you for your prompt response !
