### ISSUE TITLE
Getting Exception when trying to start appium server programmatically and run Android driver

### ISSUE THREAD

**Issue by Sourabh25** [appium/appium#13006]
## The problem

Getting the below exception when I am trying to start the appium server programmatically and then try to create an instance of IOS Driver.
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: "Carthage binary is not found. Install using `brew install carthage` if it is not installed and make sure the root folder, where carthage binary is installed, is present in PATH environment variable. The current PATH value: '/usr/bin:/bin:/usr/sbin:/sbin'".

## Environment

* Appium version (or git revision) that exhibits the issue: 5.0.4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS mojave
* Node.js version (unless using Appium.app|exe):12.6.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: 12.4
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: appium cli 

## Details

I am getting the above exception only when I am starting the appium Programmatically. If I start the appium manually , the script works fine.

## Code To Reproduce Issue [ Good To Have ]
Code to start appium Server

public class AppiumServerJava {
	AppiumServiceBuilder builder;
	AppiumDriverLocalService service;
	public void startServer() {
    builder = new AppiumServiceBuilder();
		builder.withIPAddress("0.0.0.0");
		builder.usingPort(4723);
//		builder.withCapabilities(cap);
		builder.withArgument(GeneralServerFlag.SESSION_OVERRIDE);
		builder.withArgument(GeneralServerFlag.LOG_LEVEL,"error");
		 service = AppiumDriverLocalService.buildService(builder);
		//Start the server with the builder
		service = AppiumDriverLocalService.buildService(builder);	
		service.start();
	}
	
	public void stopServer() {
		service.stop();
	}
	
}

**Comment by imurchie** [comment]
https://github.com/appium/java-client/issues/967#issuecomment-404123574

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/java-client/blob/master/docs/environment.md

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
