### ISSUE TITLE
An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id

### ISSUE THREAD

**Issue by Elisabeth1762** [appium/appium#13004]
## The problem
install apk sucess,but launch error

## Environment

* Appium version 1.14.1 (or git revision ) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS mac/version used to run Appium:
* Node.js v10.16.0
* Npm is 6.9.0
* Mobile platform android 7.0
* Real device

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"localhost","host":"localhost","port":"8200"}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"localhost","host":"localhost","port":"8200"}
[UiAutomator2] Error: The instrumentation process cannot be initialized within 30000ms timeout. Make sure the application under test does not crash and investigate the logcat output. You could also try to increase the value of 'uiautomator2ServerLaunchTimeout' capability. 
[UiAutomator2]     at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[UiAutomator2]     at UiAutomator2Server.errorAndThrow [as startSession] (/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/lib/uiautomator2.js:192:15)
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[debug] [WD Proxy] Matched '/' to command name 'deleteSession'
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
[debug] [ADB] Running '/users/wuchunyan/Library/Android/sdk/platform-tools/adb -P 5037 -s D1CGAP8720503696 shell am force-stop com.immomo.momo'
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8200 
[debug] [ADB] Running '/users/wuchunyan/Library/Android/sdk/platform-tools/adb -P 5037 -s D1CGAP8720503696 forward --remove tcp\:8200'
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1564576176485 (20:29:36 GMT+0800 (GMT+08:00))
[debug] [W3C] Encountered internal error running command: Error: The instrumentation process cannot be initialized within 30000ms timeout. Make sure the application under test does not crash and investigate the logcat output. You could also try to increase the value of 'uiautomator2ServerLaunchTimeout' capability. 
[debug] [W3C]     at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[debug] [W3C]     at UiAutomator2Server.errorAndThrow [as startSession] (/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/lib/uiautomator2.js:192:15)
[HTTP] <-- POST /wd/hub/session 500 69674 ms - 999
[HTTP] 

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
> [WD Proxy] Got an unexpected response: {"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"localhost","host":"localhost","port":"8200"}

Make sure you `/etc/hosts` file is not corrupted and `localhost` is properly resolved on the machine where the server is running

**Comment by Elisabeth1762** [comment]
Thank you very much, the problem is solved.

**Comment by Elisabeth1762** [comment]
Thank you very much, the problem is solved.

**Comment by Elisabeth1762** [comment]
“127.0.0.1       localhost
255.255.255.255 broadcasthost
::1             localhost”

**Comment by Elisabeth1762** [comment]
“127.0.0.1 localhost
255.255.255.255 broadcasthost
::1 localhost”
Added these to the file /etc/hosts
,solved the problem.

**Comment by Elisabeth1762** [comment]
The problem
import uiautomator2 success，but  the method of uiautomator2 could not be used。
------------
Environment
Appium version 1.14.1 (or git revision ) that exhibits the issue:
Last Appium version that did not exhibit the issue (if applicable):
Desktop OS mac/version used to run Appium:
Node.js v10.16.0
Npm is 6.9.0
Mobile platform android 7.0
Real device
PyCharm PyCharm 2019.2 (Community Edition)
Build #PC-192.5728.105, built on July 24, 2019
Runtime version: 11.0.3+12-b304.10 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 990M
Cores: 4
Registry: 
Non-Bundled Plugins: 
----------
Details
import uiautomator2  version 1.2.3

the code
# coding: utf-8
import time
import uiautomator2 as u2

d = u2.connect()    # this is the problem
d.app_stop("com.immomo.momo")
d.app_start("com.immomo.momo","com.immomo.momo.android.activity.WelcomeActivity") #启动陌陌
time.sleep(4)
--------
Link to PyCharm logs

/Library/Frameworks/Python.framework/Versions/3.7/bin/A/bin/python /Users/wuchunyan/PycharmProjects/A/2222.py
Traceback (most recent call last):
  File "/Users/wuchunyan/PycharmProjects/A/2222.py", line 5, in <module>
    d = u2.connect()
AttributeError: module 'uiautomator2' has no attribute 'connect'

Process finished with exit code 1
