### ISSUE TITLE
This is a question. I need push image file to ios devices,and want to find in album.

### ISSUE THREAD

**Issue by wodeta33** [appium/appium#13000]
### problem
I need push image file to ios devices,and want to find in album. Now，i push the photo to album use appium, but i can't find the photo. what should i do ?  Anybody can help me?

**Comment by KazuCocoa** [comment]
It depends on the album's behaviour.
Appium can only https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios/ios-xctest-file-movement.md 
If the app cannot detect images via the command, maybe it is difficult to find them in photo apps. You can ask it in https://discuss.appium.io if someone already figured out the way
