### ISSUE TITLE
An unknown server-side error occurred while processing the command. Original error: Could not find 'aapt.exe'

### ISSUE THREAD

**Issue by vyomkumar1** [appium/appium#13007]
I am getting hte below error when i try to open an application.

> org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Could not find 'aapt.exe' in ["C:\\Users\\nsingh163\\Desktop\\Naresh Folder\\Automation\\Mobile Automation\\Downloads\\Android-sdk\\platform-tools\\aapt.exe","C:\\Users\\nsingh163\\Desktop\\Naresh Folder\\Automation\\Mobile Automation\\Downloads\\Android-sdk\\emulator\\aapt.exe","C:\\Users\\nsingh163\\Desktop\\Naresh Folder\\Automation\\Mobile Automation\\Downloads\\Android-sdk\\tools\\aapt.exe","C:\\Users\\nsingh163\\Desktop\\Naresh Folder\\Automation\\Mobile Automation\\Downloads\\Android-sdk\\tools\\bin\\aapt.exe"]. Do you have Android Build Tools installed at 'C:\Users\nsingh163\Desktop\Naresh Folder\Automation\Mobile Automation\Downloads\Android-sdk'?
> Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
> System info: host: 'USD4FWTN2', ip: '10.88.4.6', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_171'
> Driver info: driver.version: AndroidDriver

**Comment by vyomkumar1** [comment]
I have reinstalled SDK but still i dont see aapt.exe

**Comment by mykola-mokhnach** [comment]
Appium uses aapt tool, which has been deprecated since SDK 28. You can either install an older SDK or download the aapt binary and copy it to `$ANDROID_HOME/build-tools/<version_number>`

**Comment by vyomkumar1** [comment]
THansk mykola . But i have installed API level 25 and API level 28 both. I am getting errors.

**Comment by mykola-mokhnach** [comment]
platform tools and build tools are different things

**Comment by vyomkumar1** [comment]
mykola this could be a dumb question - but after installation i dont see build tool folder 
![Capture](https://user-images.githubusercontent.com/53364053/62242201-a378ee80-b3a8-11e9-8e42-c33dda80af99.JPG)

not sure if i am missing out some thing. Please help

**Comment by vyomkumar1** [comment]
This issue as been resolved. I was able to to download aapt.exe file and the issue got resolved.
