### ISSUE TITLE
Appium 1.10.0 Tapping on a Button is resulting in Swiping the screen from Notification bar specifically on Android 9 

### ISSUE THREAD

**Issue by DhruvSharma12** [appium/appium#13001]
## The problem

I am automating an App through Appium, This issue persists only for Android 9. Whenever I am trying to click a specific button then the appium is swiping the notification bar from top to bottom. This thing work fines with other Android versions (8.0,8.1) etc.
Attaching a video for reference

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.0
* Desktop OS/version used to run Appium: Mac High Sierra
* Mobile platform/version under test: Android 9
* Real device or emulator/simulator: Real device

[android9_issue.mp4.zip](https://github.com/appium/appium/files/3450042/android9_issue.mp4.zip)

**Comment by mykola-mokhnach** [comment]
Appium 1.10.0 is out of date. Please update to the most recent one. Also the full server log is needed

**Comment by mykola-mokhnach** [comment]
no logs - no luck
