### ISSUE TITLE
Can't connect to android emulator with Got an unexpected response: {"code":"ECONNRESET"}

### ISSUE THREAD

**Issue by mraphael2101** [appium/appium#13018]
## The problem
Hello everyone,
I am attempting to run a mobile web test on an android **emulation** device, on Windows.  
When I run the test, I get the below responses. Please kindly advise if you have the solution. I have tried various things without success, and have followed the example strictly so I suspect that this could be an environment issue.

## Environment

* Appium version 1.14.0
* Desktop OS/version used to run Appium: Windows 10 Professional
* Node.js version : 6.10.2
* Mobile platform/version under test: Andriod version 10
* Real device or emulator/simulator: emulator

## Details

Eclipse Output:
FAILED CONFIGURATION: @BeforeTest setUp
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: The instrumentation process cannot be initialized within 30000ms timeout. Make sure the application under test does not crash and investigate the logcat output. You could also try to increase the value of 'uiautomator2ServerLaunchTimeout' capability. 
Build info: version: '4.0.0-alpha-1', revision: 'd1d3728cae', time: '2019-04-24T13:42:21'
System info: host: 'QT-UK-LT0760', ip: '192.168.12.33', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: AndroidDriver

Logcat Output:
https://gist.github.com/mraphael2101/8ee64d588228332ffa8c3aab57eee781

Appium Server Output:
Can't connect to android emulator with Got an unexpected response: {"code":"ECONNRESET"}

## Code To Reproduce Issue [ Good To Have ]
public class _01_MobileWebBrowserTest {

	public static AndroidDriver driver;
	public static String appiumServerURL = "http://127.0.0.1:4723/wd/hub";
	public static AppiumDriverLocalService service = AppiumDriverLocalService.buildDefaultService();
	
	
	@BeforeTest
	public static void setUp() throws MalformedURLException {
		//service.start();
		
		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
		capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10");
		capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "emulator-5554");
		capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, MobileBrowserType.CHROME);
		capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "UiAutomator2");
		
		driver = new AndroidDriver(new URL(appiumServerURL), capabilities);
		driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);

	}
	
	@AfterTest
	public static void tearDown() {
		driver.quit();
		//service.stop();
	}
	
	@Test
	public static void myFirstTest() {
		driver.get("http://www.google.com");
		driver.findElement(By.name("q")).sendKeys("Hello Appium");
	}

}

**Comment by mykola-mokhnach** [comment]
Duplicate of https://github.com/appium/appium/issues/12754

**Comment by mraphael2101** [comment]
Please re-open this ticket, as my environment configuration is different to ticket #12754.

**Comment by mraphael2101** [comment]
The issue remains open @mykola-mokhnach. Thank you for your cooperation.

**Comment by mykola-mokhnach** [comment]
The provided logcat output does not contain any traces of uiautomator2. Also, the full server log is missing

**Comment by mraphael2101** [comment]
@mykola-mokhnach As you can see I have specified UiAutomator2 in the test script as the automation framework and the device operating system is version 10 which is supported by the framework. So please could you be more specific about what you are asking me?

**Comment by mraphael2101** [comment]
I have tried different :

io.appium
java-client
5.0.4 
with the following Appium Server versions :
1.7.1
1.8
1.13.0

None of them worked.

**Comment by mraphael2101** [comment]
Hi everyone, it's worth pointing out that I have tried running the test script on two different emulation devices, and I am getting the same results, without success.

**Comment by KazuCocoa** [comment]
On Windows case, base revision on emulator and adb version also helpful since recently I saw some issues in them on Windows env.

> with the following Appium Server versions :
> 1.7.1
> 1.8
> 1.13.0

Please try with Android 9 or below emulator versions once.

**Comment by mraphael2101** [comment]
Hi, many thanks for the suggestion. I installed a new device on platform 9 and downgraded the chromedriver; and it worked. Please close the ticket.
