### ISSUE TITLE
appium Cli (Appium v1.14.0) with Ride RobotFrameWork/Selenium Library

### ISSUE THREAD

**Issue by remicharleslageixarena** [appium/appium#13016]
## The problem

Why my Ride/robotFrameWork/libraryAppium test are running fine with APPIUM DESKTOP
and are fail with APPIUM CLI?

when I use Appium desktop (1.13.0) with Ride RobotFrameWork/Selenium Library
the tests are running fine on the real device or virtual device

But when I use the same tests with appium Cli (Appium v1.14.0)
the tests are fail.

Can anyone help me, Please.
Thanks in advance
####################################################################
## Environment
**Ubuntu 18.04
appium desktop  version 1.13.0
appium cli 1.14.0**

* Desktop OS/version used to run Appium: Ubuntu 18.04
* Real device or emulator/simulator:
* Appium CLI (1.14.0) or Appium. Desktop( 1.13.0):
####################################################################
## Details
this is  the  extract log from APPIUM CLI
...
 _Cannot sort build-tools folders ["27.0.1","29.0.1","debian"] by semantic version names.
[ADB] Falling back to sorting by modification date. Original error: Invalid Version: debian
….
'io.appium.uiautomator2.server.test' is not installed
[debug] [ADB] Checking app cert for /home/linuxbrew/.linuxbrew/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk
[debug] [ADB] '/home/linuxbrew/.linuxbrew/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk' does not exist
…..
 Unable to remove port forward 'Error executing adbExec. Original error: 'Command '/usr/lib/android-sdk/platform-tools/adb -P 5037 -s GIKJBE9L795DP7ZS forward --remove tcp\:8200' exited with code 1'; Stderr: 'adb: error: listener 'tcp:8200' not found'; Code: '1''
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1564663368452 (14:42:48 GMT+0200 (heure d’été d’Europe centrale))
[debug] [W3C] Encountered internal error running command: Error: The application at '/home/linuxbrew/.linuxbrew/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk' is not writeable. Please grant write permissions to this file or to its parent folder '/home/linuxbrew/.linuxbrew/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks' for the Appium process, so it could sign the application_

**Comment by remicharleslageixarena** [comment]
appium Cli (Appium v1.14.0) with Ride RobotFrameWork/Appium Library  and not selenium

**Comment by mykola-mokhnach** [comment]
> /home/linuxbrew/.linuxbrew/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk

Is this file present and writeable?

**Comment by remicharleslageixarena** [comment]
hi Mykola
No this file is not present in this directory and not present in the ubuntu box.
I saw this file was missing but I dont' know where I can get it.


Rémi Charles Lageix Aréna
________________________________
De : Mykola Mokhnach <notifications@github.com>
Envoyé : jeudi 1 août 2019 15:58
À : appium/appium <appium@noreply.github.com>
Cc : remicharleslageixarena <remi_charles_lageix_arena@outlook.com>; Author <author@noreply.github.com>
Objet : Re: [appium/appium] appium Cli (Appium v1.14.0) with Ride RobotFrameWork/Selenium Library (#13016)


/home/linuxbrew/.linuxbrew/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk

Is this file present and writeable?

**Comment by mykola-mokhnach** [comment]
Did you install appium via npm? These files should be there after the package is installed.

Also, it is possible to build them from source. Simply follow the README at https://github.com/appium/appium-uiautomator2-server
