### ISSUE TITLE
Init chromedriver session using W3C capabilities format since v75

### ISSUE THREAD

**Issue by mykola-mokhnach** [appium/appium#13014]
chromedriver since v75 fully supports W3C protocol and defaults to it. Although, Appium still sends the desired capabilities formatted for JSONWP, which forces chromedriver to switch the protocol (and which is going to be deprecated at some point of time). We need to update the client to send the desired capabilities using W3C format (aka firstMatch/alwaysMatch + 'goog:' prefixes) for chromedriver above or equal v75 and to keep the current JSONWP format below v75.

**Comment by Sourabh25** [comment]
Will anything above chrome 75 will work in the current state? I am trying to execute with chrome 76 and I am running into error browser but reachable.

**Comment by KazuCocoa** [comment]
I could establish a session with current master (appium@beta).
Could send some commands such as page source with chromedriverVersion, `"76.0.3809.68 (420c9498db8ce8fcd190a954d51297672c1515d5-refs/branch-heads/3809@{#864})"`. Target device was Andrpid 9, Chrome version was 76.0.3809.89.
I haven't tried 1.14.0 tho.

It is helpful to share your env, chrome version and driver version.

**Comment by Sourabh25** [comment]
My env is as below
 Appium - 1.14.0
Chrome version -  76.0.3809.89.
Driver version -  76.0.3809.68

**Comment by mykola-mokhnach** [comment]
Published to appium@beta
