### ISSUE TITLE
Selenium GRID fails with capability derivedDataPath of Xcode

### ISSUE THREAD

**Issue by ryallurkar** [appium/appium#13019]
## The problem
Selenium GRID fails with capability derivedDataPath of Xcode

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.0
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: mac0S Mojave
* Node.js version (unless using Appium.app|exe): NA
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS 11.4.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Details

I am trying to start the iOS driver with 'usePrebuiltWDA' and 'derivedDataPath' capabilities of appium-xcuitest-driver.

I want to launch pre-build WebDriverAgent to save setup time using IOSDriver.

`desiredCapabilities.setCapability("usePrebuiltWDA", true);
            desiredCapabilities.setCapability("derivedDataPath", "/Users/<username>/WebDriverAgent-somerandomnumber/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app");
`

If we follow the documentation on https://github.com/appium/appium-xcuitest-driver, its mentioned that we should use derivedDataPath with usePrebuiltWDA .
When I run the test, I get the following errors in selenium GRID.

`
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: Unable to parse remote response: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 500 Server Error</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /wd/hub/session. Reason:
<pre>    Server Error</pre></p><h3>Caused by:</h3><pre>java.io.IOException: org.openqa.grid.common.exception.GridException: Cannot extract a capabilities from the request: {
  &quot;desiredCapabilities&quot;: {
    &quot;app&quot;: &quot;\u002fUsers\u002fuser\u002fappium\u002fresources\u002fipas\u002fTestDebug.app&quot;,
    &quot;noReset&quot;: false,
    &quot;derivedDataPath&quot;: &quot;\u002fUsers\u002user\u002fWebDriverAgent-brdadhpuduowllgivnnvuygpwhzy\u002fBuild\u002fProducts\u002fDebug-iphoneos\u002fWebDriverAgentRunner-Runner.app&quot;,
    &quot;processArguments&quot;: &quot;{\&quot;args\&quot;:[\&quot;UI-Testing\&quot;]}&quot;,
    &quot;deviceName&quot;: &quot;iPhone 6 HN1077&quot;,
    &quot;fullReset&quot;: false,
    &quot;usePrebuiltWDA&quot;: true,
    &quot;wdaLocalPort&quot;: &quot;5715&quot;,
    &quot;platformVersion&quot;: &quot;11.4.1&quot;,
    &quot;automationName&quot;: &quot;XCUITest&quot;,
    &quot;platformName&quot;: &quot;iOS&quot;,
    &quot;udid&quot;: &quot;7edb346e6b66525252776954706fdc5353313655f494485a8d&quot;
  },
  &quot;capabilities&quot;: {
    &quot;firstMatch&quot;: [
      {
        &quot;appium:app&quot;: &quot;\u002fUsers\u002fuser\u002fappium\u002fresources\u002fipas\u002fTestDebug.app&quot;,
        &quot;appium:automationName&quot;: &quot;XCUITest&quot;,
        &quot;derivedDataPath&quot;: &quot;\u002fUsers\u002fuser.yallurkar\u002fWebDriverAgent-brdadhpuduowllgivnnvuygpwhzy\u002fBuild\u002fProducts\u002fDebug-iphoneos\u002fWebDriverAgentRunner-Runner.app&quot;,
        &quot;appium:deviceName&quot;: &quot;iPhone 6 HN1077&quot;,
        &quot;appium:fullReset&quot;: false,
        &quot;appium:noReset&quot;: false,
        &quot;platformName&quot;: &quot;ios&quot;,
        &quot;appium:platformVersion&quot;: &quot;11.4.1&quot;,
        &quot;appium:processArguments&quot;: &quot;{\&quot;args\&quot;:[\&quot;UI-Testing\&quot;]}&quot;,
        &quot;appium:udid&quot;: &quot;7edb346e6b66525252776954706fdc5353313655f494485a8d&quot;,
        &quot;appium:usePrebuiltWDA&quot;: true,
        &quot;appium:wdaLocalPort&quot;: &quot;5715&quot;
      }
    ]
  }
}

`

**Comment by mykola-mokhnach** [comment]
add `appium:` prefix to the capability name

**Comment by ryallurkar** [comment]
Thanks, @mykola-mokhnach  , adding prefix resolved the issue.

Do you know why this is not documented in https://github.com/appium/appium-xcuitest-driver.

**Comment by mykola-mokhnach** [comment]
> Do you know why this is not documented in https://github.com/appium/appium-xcuitest-driver.

I assume this is a normal W3C caps behaviour, not a bug. Although the error message that Selenium Grid shows is not very helpful or self-descriptive. Perhaps @diemol could add something on that.

**Comment by ryallurkar** [comment]
Exactly, the error message doesn't help at all

**Comment by diemol** [comment]
Yes, some error descriptions in Grid 3.x are not that helpful. We are working in a new Grid 4.x which is currently under development and we will keep in mind these type of things.
