### ISSUE TITLE
setGeoLocation's AppleScript does not work on iOS simulator

### ISSUE THREAD

**Issue by replicat** [appium/appium#13010]
## The problem

On simulator, without fbsimctl/idb, setGeoLocation uses AppleScript as default, which fails to execute.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.0
* Desktop OS/version used to run Appium: macOS Mojave 10.14.5
* Node.js version (unless using Appium.app|exe): 12.2.0
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: iOS 12.1
* Real device or emulator/simulator: Simulator iPhone X (Xcode 10.2.1)
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Upon inspection of the log (see below), it is clear that the AppleScript fails to execute. All related apps have been given permission in macOS's accessibility list.

Copying the AppleScript included in the log and running it separately also does not work. 

With further inspection, I have found that the hyphen(-) in the simulator's title is actually an em dash(—). Making this change, the script executed successfully. Could this be a locale issue?

## Link to Appium logs

https://gist.github.com/replicat/636a41d4ee2e0313ab5a152118c6e962

**Comment by mykola-mokhnach** [comment]
This should be an easy change, however idb is a recommended way of setting the geo location

**Comment by replicat** [comment]
I also wish to use idb, but currently there is a [bug](https://github.com/facebook/idb/issues/539) preventing me from using it, so I will have to use the AppleScript approach at the mean time.

**Comment by KazuCocoa** [comment]
btw, what about installing it as HEAD? (workaround tho)
I heard recently installing 1.0.7 failed and something happened, but the HEAD worked for them.

**Comment by umutuzgur** [comment]
`idb` 1.0.7 also fails to connect running Simulators and that doesn't work with Appium since we boot up the simulators. The HEAD works fine thou

**Comment by replicat** [comment]
> btw, what about installing it as HEAD? (workaround tho)
> I heard recently installing 1.0.7 failed and something happened, but the HEAD worked for them.

Installing idb-companion with --HEAD worked. It allows idb-companion to start up and Appium can call idb to connect to it.
However, idb fails to execute set-location. 
I have tried manually using idb to boot a simulator, booting an idb-companion, connecting to it through idb and execute set-location, which works fine.
I am not sure whether there is a problem with Appium or idb.

Log: https://gist.github.com/replicat/51c1b7f10e986b431839263e7291dc8c
idb: 0.0.6
idb-companion: HEAD-1b34920

**Comment by KazuCocoa** [comment]
thanks.
The log looks idb connection closed...
I also encountered disconnection of idb frequently before. (My case was against real devices case tho) Maybe, something happened in idb side.

**Comment by dpgraham** [comment]
Yeah that happens all the time. Just running `idb kill` seems to fix it. Annoying though.

**Comment by mykola-mokhnach** [comment]
The fix has been published to appium@beta

**Comment by bhadmus** [comment]
> Installing idb-companion with --HEAD

How do I do this? `pip3.7 install --HEAD fb-idb` didn't work
