### ISSUE TITLE
Getting this error- "OpenQA.Selenium.WebDriverException: "Unexpected error. Unimplemented Command: xpath locator strategy is not supported"

### ISSUE THREAD

**Issue by vishnuprakash9845** [appium/appium#13024]
## The problem

Getting the below error when tried to automate the UWP application
1.Successfully able to launch the application
2.But when tried to identify the element in the application getting the error **"OpenQA.Selenium.WebDriverException: "Unexpected error. Unimplemented Command: xpath locator strategy is not supported"**

## Environment

* Appium version (or git revision) that exhibits the issue: 3.0.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Window 10
* Node.js version (unless using Appium.app|exe): Not installed
* Npm or Yarn package manager: Not installed
* Mobile platform/version under test: No
* Real device or emulator/simulator: No
* Appium CLI or Appium.app|exe: 1.13

## Details
Attaching the Screenshot of Error and WinAppdriver log

![image](https://user-images.githubusercontent.com/24207575/62375053-08744600-b55b-11e9-9aff-085456eb5371.png)

![image](https://user-images.githubusercontent.com/24207575/62375083-19bd5280-b55b-11e9-8bdc-f19f0102516c.png)

Please do any one help me on this issue, if any info on this required please mail me @ vishnuprakash9845@gmail.com

**Comment by KazuCocoa** [comment]
Could you ask https://github.com/microsoft/WinAppDriver instead of here?

Potentially, you should try dotnet client 4.x beta out.
They have some W3C implementations.

**Comment by mykola-mokhnach** [comment]
Please attach the full server log
