### ISSUE TITLE
Avoid app auto launch on iOS with XCUITest

### ISSUE THREAD

**Issue by sebastiandine** [appium/appium#13023]
## The problem

I wonder if there is a way to avoid the autostart of the tested app on iOS, like it is possible on Android with the driver capability `'autoLaunch': False` ?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13.0
* Last Appium version that did not exhibit the issue (if applicable): - 
* Desktop OS/version used to run Appium: Mac OS 10.14.5
* Node.js version (unless using Appium.app|exe): 12.6.0
* Npm or Yarn package manager: npm 6.9.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: 12.1
* Appium CLI or Appium.app|exe: CLI

**Comment by KazuCocoa** [comment]
One is launching an app like _mobile safari_ with bundle id and install your app via `install_app`

**Comment by sebastiandine** [comment]
My app is sending requests to a server on startup. I want to configure the listening to this server before the app gets started.

**Comment by KazuCocoa** [comment]
The latest `appium@beta` has the ability, `autoLaunch`. => https://github.com/appium/appium-xcuitest-driver/pull/1026
