### ISSUE TITLE
Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

### ISSUE THREAD

**Issue by kinty-yi** [appium/appium#13021]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

Appium-desktop：1.13.1
Xcode：10.0
iPhone7p：IOS(10.3.3)
Mac：10.13.6
WDA
## Link to Appium logs

[XCUITest] Quitting and uninstalling WebDriverAgent
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 14250)
[XCUITest] iproxy exited with code 'null'
[XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[XCUITest] xcodebuild error message:
[XCUITest] 
[XCUITest] 2019-08-02 14:28:52.030 xcodebuild[14251:497771] Error Domain=com.apple.platform.iphoneos Code=-12 "Unable to launch com.apple.test.WebDriverAgentRunner-Runner" UserInfo={NSLocalizedDescription=Unable to launch com.apple.test.WebDriverAgentRunner-Runner, NSUnderlyingError=0x7fc2a20f3ad0 {Error Domain=DTXMessage Code=2 "Failed to deserialize message" UserInfo={NSLocalizedDescription=Failed to deserialize message, NSUnderlyingError=0x7fc2a18575d0 {Error Domain=NSCocoaErrorDomain Code=4864 "value for key 'NS.objects' was of unexpected class 'NSException'. Allowed classes are '{(
[XCUITest]     NSError,
[XCUITest]     NSDate,
[XCUITest]     NSSet,
[XCUITest]     NSNull,
[XCUITest]     NSURL,
[XCUITest]     NSData,
[XCUITest]     NSDictionary,
[XCUITest]     NSArray,
[XCUITest]     NSString,
[XCUITest]     NSAttributedString,
[XCUITest]     NSNumber,
[XCUITest]     NSValue
[XCUITest] )}'." UserInfo={NSDebugDescription=value for key 'NS.objects' was of unexpected class 'NSException'. Allowed classes are '{(
[XCUITest]     NSError,
[XCUITest]     NSDate,
[XCUITest]     NSSet,
[XCUITest]     NSNull,
[XCUITest]     NSURL,
[XCUITest]     NSData,
[XCUITest]     NSDictionary,
[XCUITest]     NSArray,
[XCUITest]     NSString,
[XCUITest]     NSAttributedString,
[XCUITest]     NSNumber,
[XCUITest]     NSValue
[XCUITest] )}'.}}}}}
[XCUITest] 2019-08-02 14:28:52.030 xcodebuild[14251:497771] Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Failed to install or launch the test runner" UserInfo={NSLocalizedRecoverySuggestion=If you believe this error represents a bug, please attach the result bundle at /Users/liu.man/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2019.08.02_14-28-38-+0800.xcresult, NSLocalizedDescription=Failed to install or launch the test runner, NSUnderlyingError=0x7fc2a24107e0 {Error Domain=com.apple.platform.iphoneos Code=-12 "Unable to launch com.apple.test.WebDriverAgentRunner-Runner" UserInfo={NSLocalizedDescription=Unable to launch com.apple.test.WebDriverAgentRunner-Runner, NSUnderlyingError=0x7fc2a20f3ad0 {Error Domain=DTXMessage Code=2 "Failed to deserialize message" UserInfo={NSLocalizedDescription=Failed to deserialize message, NSUnderlyingError=0x7fc2a18575d0 {Error Domain=NSCocoaErrorDomain Code=4864 "value for key 'NS.objects' was of unexpected class 'NSException'. Allowed classes are '{(
[XCUITest]     NSError,
[XCUITest]     NSDate,
[XCUITest]     NSSet,
[XCUITest]     NSNull,
[XCUITest]     NSURL,
[XCUITest]     NSData,
[XCUITest]     NSDictionary,
[XCUITest]     NSArray,
[XCUITest]     NSString,
[XCUITest]     NSAttributedString,
[XCUITest]     NSNumber,
[XCUITest]     NSValue
[XCUITest] )}'." UserInfo=0x7fc2a2069e20 (not displayed)}}}}}}
[XCUITest] Testing failed:
[XCUITest] 	No profiles for 'com.wemomo.momoappdemo1' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.wemomo.momoappdemo1'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'WebDriverAgentRunner')
[XCUITest] 	WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: Unable to launch com.apple.test.WebDriverAgentRunner-Runner. (Underlying error: Failed to deserialize message. (Underlying error: The data couldn’t be read because it isn’t in the correct format. The data isn’t in the correct format.))))
[XCUITest] ** TEST EXECUTE FAILED **
[XCUITest] Testing started on 'iPhone 7p - lm'. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[XCUITest]     at quitAndUninstall (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:501:15)

**Comment by mykola-mokhnach** [comment]
This is expected. Newer Appium versions don't support iOS 10. You must either downgrade to an older version or use newer iOS version

**Comment by umutuzgur** [comment]
@mykola-mokhnach That is not true. I test with iOS 10.2. It seems to be a signing issue with XCode here

**Comment by KazuCocoa** [comment]
Can you try the desktop 1.14.0? @kinty-yi 

1.13 has an issue which happens a particular case in signing. 1.14.0 has the fix.
If it failed in 1.14.0 as well, please make sure your provisioning profile works checking http://appium.io/docs/en/drivers/ios-xcuitest-real-devices/

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
