### ISSUE TITLE
Switch to webview doesn't work in the real device in iOS Hybrid Application

### ISSUE THREAD

**Issue by metalimangal123** [appium/appium#13036]
## The problem

I am trying to switch to webview in an iOS Hybrid application in the real device. I receive a bluebird timeout error in appium-remote-debugger, and was unsuccessful again. I am using iOS 12.4 real device(iPhone 6s) and iOS 12.3.1. When I run the same code with iOS 11.3.1, it works

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.1
* Desktop OS/version used to run Appium: MacOS Mojave 10.14.5
* Npm or Yarn package manager: npm 6.9.0
* Mobile platform/version under test: iOS 12.4, 12.3.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details
Unable to switch to webview in iOS 12.2 and higher devices.
Used appium-remote-debugger 4.3.0, 4.4.0, 4.4.1
```
/Users/metali/local/lib
└─┬ appium@1.14.1
  ├─┬ appium-ios-driver@4.2.3
  │ └── appium-remote-debugger@4.4.1 
  ├─┬ appium-xcuitest-driver@2.117.0
  │ └── appium-remote-debugger@4.4.1  deduped
  └─┬ appium-youiengine-driver@1.2.1
    └─┬ appium-ios-driver@4.3.0
      └── appium-remote-debugger@4.4.1  deduped
```

## Link to Appium logs

https://gist.github.com/metalimangal123/7df00c86c7ef004b62e8f35713382659

## Code To Reproduce Issue [ Good To Have ]
```
Capabilities used: 
{
    "platformName": "iOS",
    "platformVersion": "12.4",
    "wdaLaunchTimeout": 240000,
    "wdaConnectionTimeout": 240000,
    "preventWDAAttachments": true,
    "clearSystemFiles": true,
    "shouldUseSingletonTestManager": false,
    "simpleIsVisibleCheck": true,
    "automationName": "XCUITest",
    "noReset": false,
    "webviewConnectRetries": 5,
    "webkitResponseTimeout": 50000,
    "startIWDP": true,
    "newCommandTimeout": 100000
  }
```

**Comment by mykola-mokhnach** [comment]
We did a couple of fixes in appium@beta
Please try if it works for you

**Comment by metalimangal123** [comment]
I have tried using beta

/Users/metali/local/lib
└─┬ appium@1.14.0-beta.2
  ├─┬ appium-ios-driver@4.3.0
  │ └── appium-remote-debugger@4.4.1 
  └─┬ appium-xcuitest-driver@2.125.0
    └── appium-remote-debugger@5.1.0 

This is the log which I come across after trying it

[](https://gist.github.com/metalimangal123/80dc3028be86a7cadb3581933d424970)

**Comment by Tasija** [comment]
I faced the same issue

/usr/local/lib
└─┬ appium@1.14.0-beta.2
  ├─┬ appium-ios-driver@4.3.0
  │ └── appium-remote-debugger@4.4.1 
  └─┬ appium-xcuitest-driver@2.127.0
    └── appium-remote-debugger@5.1.4 


Appium version (or git revision) that exhibits the issue: appium@1.14.0-beta.2
Desktop OS/version used to run Appium: MacOS Mojave 10.14.6
Npm or Yarn package manager: npm 10.13
Mobile platform/version under test: iOS 12.4, 12.2
Real device or emulator/simulator: simulator
Appium CLI or Appium.app|exe: Appium CLI
