### ISSUE TITLE
Tests stops after switch to native context

### ISSUE THREAD

**Issue by GerardLarwa** [appium/appium#13032]
## The problem

Execution of tests stops after switch context from WEB_VIEW into NATIVE_APP. Before that, in WEB_VIEW tests are working correctly. 

## Environment

* Appium version that exhibits the issue: 1.14.1 (UiAutoamtor2)
* Last Appium version that did not exhibit the issue : 1.14.1 with UiAutomator
* Desktop OS used to run Appium: Windows 10
* Node.js version : 10.16.0
* Npm package manager: 6.10.2
* Mobile platform under test: Android 8.0
* Real device: Huawei P10
* Appium CLI 
* Java-client 7.1.0

## Details

It's happen only with UiAutomator2, with UiAutomator works good. There is no any exception even with explicit wait. I can't execute any operation after change context (click button, get contexts or page source). After 30 second exception should be occured, but nothing happen. It's seems like appium session is empty. I was trying with other Appium version (1.13.0), other java-client versions. Reinstalled npm, appium. Updated Python, Python Appium Client, Android SDK. Anything didn't help. 

## Link to Appium logs

https://gist.github.com/GerardLarwa/284c79fa84be045774c5feac40055d78

## Link to Logcat logs

https://gist.github.com/GerardLarwa/0654b12cca7e2121c6968e350dd7068f

**Comment by mykola-mokhnach** [comment]
> 08-05 16:52:00.993  1627  1964 I ash     : io.appium.uiautomator2.server { doze duration=10023 UptimeDuration=10022 } transition to: hibernation reason:

I would try to add Appium server to the list of apps, that Doze cannot suspend on the device under test

**Comment by GerardLarwa** [comment]
Now it's working. Thanks !
