### ISSUE TITLE
No connect between Appium and simulation

### ISSUE THREAD

**Issue by Zeguar** [appium/appium#13035]
We try to run auto-tests written in python. 
When starting the auto test
at some point Appium doesn't connect simulation and fails. 
There is no logic in the error because once it occurs the next time the connection works. So it is sporadic.

Details:
"platformName": "iOS",
    "platformVersion": "12.1",
    "deviceName": "iPhone SE",
    "launchTimeout": 240000,
    "app": T_APP,
    "wdaLaunchTimeout": 240000,
    "wdaConnectionTimeout": 240000,
    "newCommandTimeout": 240000,
}

Appium version 1.14.0 version

Screen of the error http://prntscr.com/oox1vs

**Comment by mykola-mokhnach** [comment]
Unfortunately we cannot help nothing without the full server log
