### ISSUE TITLE
scroll up not working for me (iOS)

### ISSUE THREAD

**Issue by dron4ik86** [appium/appium#13038]
## The problem

I try to scroll up after scroll down.
Scroll down works perfect for me, but when I try to scroll up nothing is not happen.
I try to do this process with the sleep of 5 sec, but I got the same result the scroll up is not working.

```
driver.execute_script('mobile: scroll', {'direction': 'down'})
time.sleep(5)
driver.execute_script('mobile: scroll', {'direction': 'up'})

```
## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.0 (I try with 1.12.1 same result)
* Desktop OS/version used to run Appium: macos mojave 10.14.6
* Node.js version (unless using Appium.app|exe): 12.8.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS 12.3.2
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs
https://pastebin.com/ndanYDqH

**Comment by mykola-mokhnach** [comment]
Try to do small swipes in a loop. I would not rely on `scroll` endpoint at all, since it is not very reliable and has very complicated internal logic.

**Comment by dron4ik86** [comment]
> Try to do small swipes in a loop. I would not rely on `scroll` endpoint at all, since it is not very reliable and has very complicated internal logic.

Thanks for your answer
