### ISSUE TITLE
Wildcard appWaitActivity does not work for EspressoDriver

### ISSUE THREAD

**Issue by NozomiIto** [appium/appium#13030]
## The problem

When I launched EspressoDriver with `'appWaitActivity': '*'`, the launch failed with error `Activity 'io.appium.android.apis.*' was unable to start within 60000ms timeout`. 

- Once `'appWaitActivity': '*'` has been removed, the test succeeds.
- It seems wildcard appWaitActivity does not work for EspressoDriver. Wildcard appWaitActivity works well for uiAutomator2 driver on my env.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium1.14.0
* Desktop OS/version used to run Appium: MacOS Mojave,  10.14.6
* Node.js version (unless using Appium.app|exe): v10.16.0
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: Android6.0
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

https://gist.github.com/NozomiIto/b06f83887b6de2aa386b34b0484edabe

**Comment by mykola-mokhnach** [comment]
I think you can try to provide the activity name manually in caps for now to workaround it. I'll check the code about what can be done on it

**Comment by NozomiIto** [comment]
thank you so much!!

**Comment by mykola-mokhnach** [comment]
Please try if appium@beta works for you

**Comment by NozomiIto** [comment]
It worked! Thanks for the quick fix!
