### ISSUE TITLE
Appium 1.13.0 Tapping on a Button is resulting in Swiping the screen from Notification bar specifically on Android 9

### ISSUE THREAD

**Issue by DhruvSharma12** [appium/appium#13039]
The problem
I am automating an App through Appium, This issue persists only for Android 9. Whenever I am trying to click a specific button then the appium is swiping the notification bar from top to bottom. This thing work fines with other Android versions (8.0,8.1) etc.
Attaching a video for reference

Environment
Appium version (or git revision) that exhibits the issue: 1.13.0
Desktop OS/version used to run Appium: Mac High Sierra
Mobile platform/version under test: Android 9
Real device or emulator/simulator: Real device
Appium Logs link:- https://gist.github.com/DhruvSharma12/0746abde6789891cab2af731ea27ad49

[android9_issue.mp4.zip](https://github.com/appium/appium/files/3476231/android9_issue.mp4.zip)

**Comment by mykola-mokhnach** [comment]
Uiautomator1 is considered obsolete for Android6+ and should not be used

**Comment by DhruvSharma12** [comment]
In the attached video, it is reflected that I was using Appium only to inspect elements and perform actions. In the video it was shown that when I was trying to tap on an element then instead of clicking it, it is swiping the screen upside down. Not sure whether Appium is default calling UIautomator1. Can you please elaborate?

**Comment by mykola-mokhnach** [comment]
> Can you please elaborate?

What exactly is unclear? How to change the automation backend?

**Comment by DhruvSharma12** [comment]
Why appium is behaving like this only for Android 9. For other android versions, Appium is able to tap on that button, but for Android 9 specifically it is not tapping on that button but swiping the screen.

**Comment by mykola-mokhnach** [comment]
It is just a coincidence that UiAutomator still worked. Google stopped supporting it years ago, so we don't spend time digging into the obsolete stuff.

**Comment by DhruvSharma12** [comment]
Okay, so can we come up with a solution to fix this issue? Or I have to forfeit using Android 9 for this issue?

**Comment by mykola-mokhnach** [comment]
> Or I have to forfeit using Android 9 for this issue?

Yes, if you want to continue using UiAutomator1 automation backend. There will be more and more issues like that with each new Android version and they are never going to be fixed.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
