### ISSUE TITLE
[IOS]clear method for element object doesn't clear the text field if the default cursur location is at the beginning of the text

### ISSUE THREAD

**Issue by Jiurong-Yang** [appium/appium#13046]
On IOS real device. When you call element.clear() and the default cursor location is at the beginning of the text box then nothing is cleared. Basically you'll have to click the element once to highlight it, and click the element again near the end of the text box to move the cursor to the end of the text in the textbox. Then you can call element.clear() to clear the text box. I think in this method in WDA 

https://github.com/appium/WebDriverAgent/blob/2ea6a8839c15e268459b81cd3be1b8fe98b0bf36/WebDriverAgentLib/Categories/XCUIElement%2BFBTyping.m#L67

If at the beginning of the textToType variable we add the unicode character [end of text](https://www.fileformat.info/info/unicode/char/0003/index.htm) it would fix this issue.

**Comment by mykola-mokhnach** [comment]
Thanks for the suggestion. Feel free to open a PR

**Comment by mykola-mokhnach** [comment]
Unfortunately the trick with EOT didn't work. I've selected more complicated way of fixing it: https://github.com/appium/WebDriverAgent/pull/248

**Comment by mykola-mokhnach** [comment]
Closing as fixed for now. Unfortunately, the current solution won't work if the device locale is not the English one, although XCTest does not provide anything better.
