### ISSUE TITLE
Appium iOS: The network trace file for instruments gets blank

### ISSUE THREAD

**Issue by tomqijianbo** [appium/appium#13048]
The problem
I am running appium for ios real device to record the instruments trace log for network.
But after running the test, i found the .trace file is blank.
If i am running it for "Activity Monitor", the .trace file have the contents.

Environment
* Appium version: 1.14.0 (Appium desktop for mac)
* ios real device: 12.4
* Instrument version: 10.2.1 (10E1001)
* ios network connection: wifi

The sample code:
```
 File traceZip = new File("/tmp/trace.zip");
  HashMap<String, Object> args = new HashMap<>();
  args.put("timeout", 60000);
  args.put("pid", "current");
  args.put("profileName", "Network");
  //args.put("profileName", "Activity Monitor");
  driver.executeScript("mobile: startPerfRecord", args);
  driver.findElementByAccessibilityId("Search").click();
  Thread.sleep(5000);
  String b64Zip = (String)driver.executeScript("mobile: stopPerfRecord", args);
  byte[] bytesZip = Base64.getMimeDecoder().decode(b64Zip);
  FileOutputStream stream = new FileOutputStream(traceZip);
  stream.write(bytesZip);
```

**Comment by mykola-mokhnach** [comment]
What is the output if instruments is started manually? Can you also attach the full server log?

**Comment by tomqijianbo** [comment]
The attached picture is the appium log for recording network instruments trace
![image](https://user-images.githubusercontent.com/42462349/62850044-54ba4580-bd14-11e9-8ce9-3bf90a93daa2.png)

The manual instruments template is network.

**Comment by mykola-mokhnach** [comment]
This is odd. Does the template present in the `instruments -s` output? Have you tried too run the same command manually from terminal?

**Comment by tomqijianbo** [comment]
yes, i can manually run the command from terminal. And the trace file can be opened by instruments
![image](https://user-images.githubusercontent.com/42462349/62913569-3cebcb80-bdbf-11e9-8121-3d9d9d85e86f.png)
![image](https://user-images.githubusercontent.com/42462349/62913629-79b7c280-bdbf-11e9-9e77-98e1ac47e666.png)
Seems only the template for Network has the problem in appium. The custom template also works fine in appium.

**Comment by mykola-mokhnach** [comment]
What if you provide the full path to the network template instead of just the name

**Comment by tomqijianbo** [comment]
yes, it works fine with the full name now.
thank you!
