### ISSUE TITLE
Appium1.14.0-beta.2 does not support chrome '76.0.3809' | Please refer #13040

### ISSUE THREAD

**Issue by shagupta92042** [appium/appium#13042]
## The problem

Appium1.14.0-beta.2 does not support chrome '76.0.3809' but Appium1.14.0 does.
I installed beta version of appium as per suggestion provided in #13040.

**Comment by shagupta92042** [comment]
Any update for this ? Is there any appium version to support '76.0.3809' chrome web browser version.

**Comment by ishanm120** [comment]
As you mentioned appium 1.14.0 supports 76.0.3809 but yes few features of automation are not working on this.
i am also waiting for correct appium version.

**Comment by KazuCocoa** [comment]
I think current appium has no chrome driver for 76. https://github.com/appium/appium-chromedriver/pull/137
Current beta have autodownload feature with relaxed security. =>
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md#automatic-discovery-of-compatible-chromedriver

Or you can use chromedriverExecutable getting chrome driver from http://chromedriver.chromium.org/downloads

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
