### ISSUE TITLE
Android 9 does not return correct XML (elements are missing that do show up in Android 8)

### ISSUE THREAD

**Issue by mikesalvia** [appium/appium#13045]
## The problem

During automation, I went to create a profile for Android 9, after doing so several `Button` type elements were no longer being returned as visible. I thought this odd so I went to get the source. Which produced an XML that the element was completely missing which explains why they are not seen as visible. In Android 8, these elements are present.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13.0 and 1.14.0
* Last Appium version that did not exhibit the issue (if applicable): Unknown (this may be due to a UIAutomator issue)
* Desktop OS/version used to run Appium: macOS
* Node.js version (unless using Appium.app|exe): 12.6
* Npm or Yarn package manager: Yarn
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Emulator running Android 9
* Appium CLI or Appium.app|exe: Appium CLI

## Details

The returned source String in Android 9 is missing elements that are clearly present on screen.

## Link to Appium logs

https://gist.github.com/mikesalvia/b73e146715f1a0f5c41a9e30dbbc76ce Android 9 Appium Logs
https://gist.github.com/mikesalvia/f817a5cc39ca28d186d7b8bbce662b94 Android 9 Appium Android Source

https://gist.github.com/mikesalvia/c7f80d41aa26b551b84b2f32560fca61 Android 8 Appium Logs
https://gist.github.com/mikesalvia/24cb4b4e21b179d5bfb0c9219fbe76e2 Android 8 Appium Android Source

![Screen Shot 2019-08-07 at 12 05 53 PM](https://user-images.githubusercontent.com/6209204/62638575-bdb44e80-b90b-11e9-8fe5-63c1674ebe07.png)
Quick Diff of the 2 XMLs returned by `getSource()` (WDIO's getPageSource())

## Code To Reproduce Issue [ Good To Have ]

Will provide at later date.

**Comment by mykola-mokhnach** [comment]
I would also say this is UiAutomator-specific thing. Appium simply reflects what is receives from this framework. I would describe the issue to Google

**Comment by mikesalvia** [comment]
Should I create this bug in the Appium-related UIAutomator2 repo? Or the direct repository for Android/Google.

**Comment by mykola-mokhnach** [comment]
Directly to Google. They would probably need for more details about how the particular controls are implemented in the source code.

**Comment by mykola-mokhnach** [comment]
You can also verify the thing using any Android accessibility inspector

**Comment by mikesalvia** [comment]
@mykola-mokhnach Not thinking it is UIAutomator2 issue got this when running the `uiautomatorviewer` I get...

<img width="1370" alt="Screen Shot 2019-08-07 at 12 48 42 PM" src="https://user-images.githubusercontent.com/6209204/62641520-be4fe380-b911-11e9-9cd3-741b81a88f87.png">

**Comment by mikesalvia** [comment]
I am going to run my app and set a breakpoint and see what it sees under an Appium test. Could it be a version in https://github.com/appium/appium-uiautomator2-driver or a bug in there?

**Comment by mikesalvia** [comment]
@mykola-mokhnach Unfortunately, that is not working the `uiautomatorviewer` does not allow for polling while under an Appium session it appears.

**Comment by mykola-mokhnach** [comment]
You can try to change the `allowInvisibleElements` setting to `true`. Otherwise I don't have any good solutions

**Comment by mikesalvia** [comment]
OK then I will go to the other repo and reference this there, and eventually maybe back to Google.

**Comment by mikesalvia** [comment]
`allowInvisibleElements` does not work. :-/

**Comment by mikesalvia** [comment]
This may be due to my app I am looking into it I am able to see Buttons in the source when using the demo app.

**Comment by mikesalvia** [comment]
@mykola-mokhnach Definitely a bug in the Appium ecosystem somewhere, I compared my buttons to those in the APIDemos APK that is bundled with Appium and I noticed they all have text assigned to them. After adding text property to my buttons it works. However, that shouldn't be the case IMHO.

```<Button
        android:id="@+id/button_go"
        android:layout_width="24dp"
        android:layout_height="24dp"
        android:layout_gravity="center"
        android:layout_margin="6dp"
        android:background="@drawable/ic_arrow" />
```
vs.
```<Button
        android:id="@+id/button_go"
        android:layout_width="24dp"
        android:layout_height="24dp"
        android:layout_gravity="center"
        android:layout_margin="6dp"
        android:text=" "
        android:background="@drawable/ic_arrow" />```

**Comment by mykola-mokhnach** [comment]
Like I said I don't have any good ideas on it. You could investigate it deeper though. Here is the code, which collects the elements tree:
https://github.com/appium/appium-uiautomator2-server/blob/9c298b34c79bbfa14a60919d97230eaa5f965fcc/app/src/main/java/io/appium/uiautomator2/model/UiAutomationElement.java#L161

**Comment by mikesalvia** [comment]
Thank you!

**Comment by mikesalvia** [comment]
Also, saw in Appium Desktop that the item is missing even though I get it now when accessing source via API.

**Comment by mikesalvia** [comment]
@mykola-mokhnach It appears this is happening due to the fact that we create our own component which contains a text field and a button. When applying a vanilla button to the same page it is accessible, this is definitely a bug and regression somewhere and should be looked at, but I have found a workaround for it to unblock me.

**Comment by Gardosen** [comment]
I have the very same issue on my automation.

would be nice to see this fixed.

**Comment by mykola-mokhnach** [comment]
https://developer.android.com/guide/topics/ui/accessibility/custom-views

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
