### ISSUE TITLE
[Mac/iOS] Appium inspector don't work anymore

### ISSUE THREAD

**Issue by Tygered** [appium/appium#13043]
## The problem

Hi,
I've been using appium and an iPhone simulator (xCode) to create some automated tests. 
Yesterday I wanted to use the Appium's inspector to get some IDs on a new app and it resulted in a lot of errors. 
First, Appium launched 2 more simulator (even though the correct one was already launched), and crashed.
Now it does not launch anything and crash after few minutes, trying to launch the app. 
But the application is still installed on the device. I tried with previous app that worked fine and I have the same issue.

I did not change anything from my previous work on this project with Appium etc. I just updated to 1.13

## Data 

Inspector capabilities : {
  "app": "/Users/ame/Downloads/appium-boilerplate-master/apps/appName.zip",
  "platformName": "iOS",
  "deviceName": "iPhone Xʀ",
  "platformVersion": "12.2",
  "automationName": "XCUITest"
}

I'm using appium 1.13.0 and when I check for update, this is the latest. 
The error I get is the followed : 

An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65 xcodebuild error message: 2019-08-07 11:13:57.283 xcodebuild[10489:297857] Error Domain=IDETestApplcationDependencyMapperErrorDomain Code=2 "The bundle identifier for WebDriverAgentRunner-Runner.app couldn’t be read." UserInfo={NSLocalizedFailureReason=The application may be damaged or incomplete: “/Users/jeremy/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app”., NSURL=file:///Users/jeremy/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app/, NSFilePath=/Users/jeremy/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app, NSLocalizedDescription=The bundle identifier for WebDriverAgentRunner-Runner.app couldn’t be read.} Testing failed: 'YYCache/YYCache.h' file not found Test session results and logs: /Users/jeremy/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2019.08.07_11-13-54-+0300.xcresult ** TEST EXECUTE FAILED ** Testing started on 'iPhone Xʀ'

Here are the Appium logs when trying to launch the inspector [appium-server-logs.txt](https://github.com/appium/appium/files/3477405/appium-server-logs.txt)

**Comment by mykola-mokhnach** [comment]
> [error] [35m[Xcode][39m Testing failed:
> [error] [35m[Xcode][39m 	'YYCache/YYCache.h' file not found

Most likely carthage fails to get dependencies and compile WebDriverAgent. I would try to compile /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj manually and see what the output is.

**Comment by Tygered** [comment]
Thanks for the fast reply
I found this directory, but how do I compile this ? I'm new to MacOS ...

**Comment by mykola-mokhnach** [comment]
Follow https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
