### ISSUE TITLE
Error on starting iOS test when running against appium 1.14.1

### ISSUE THREAD

**Issue by BoazWarshawsky** [appium/appium#13047]
## The problem
After updating to appium 1.14.1 I started seeing errors when calling Remote method to start my test:
[debug] [XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'carthage bootstrap --platform iOS\,tvOS' exited with code 1. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[XCUITest]     at quitAndUninstall (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:516:15)
[XCUITest]     at <anonymous>

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.1
* Last Appium version that did not exhibit the issue (if applicable):1.11.1
* Desktop OS/version used to run Appium:Desktop
* Node.js version (unless using Appium.app|exe):8.12.0
* Npm or Yarn package manager:NPM
* Mobile platform/version under test:iOS 12.2
* Real device or emulator/simulator: Real Device, iPhone X
* Appium CLI or Appium.app|exe: cli

## Link to Appium logs
https://assets-production.applicaster.com.s3.amazonaws.com/qa/zapp_qa/manual/boaz/appium.log## Code To Reproduce Issue [ Good To Have ]

**Comment by KazuCocoa** [comment]
What message can you see when you run below by hand?

```
$ cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver
$ carthage bootstrap --platform iOS,tvOS
```

---

> [debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1565243992959 (08:59:52 GMT+0300 (IDT))
[XCUITest] Launching WebDriverAgent on the device
[WebDriverAgent] Fetching dependencies
[WebDriverAgent] Installing/updating dependencies for platforms 'iOS', 'tvOS'
[XCUITest] Launching WebDriverAgent on the device
[WebDriverAgent] Fetching dependencies
[WebDriverAgent] Installing/updating dependencies for platforms 'iOS', 'tvOS'
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1565243995369 (08:59:55 GMT+0300 (IDT))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: Command 'carthage bootstrap --platform iOS\,tvOS' exited with code 1. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.

**Comment by BoazWarshawsky** [comment]
@KazuCocoa, seeing this:
*** No Cartfile.resolved found, updating dependencies
Failed to read file or folder at /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/Cartfile: Error Domain=NSCocoaErrorDomain Code=260 "The file “Cartfile” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/Cartfile, NSUnderlyingError=0x7fcb43603cb0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

**Comment by KazuCocoa** [comment]
sorry, the place is `$ cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent` ( WebDriverAgent was missed)

**Comment by BoazWarshawsky** [comment]
I don't have the WebDriverAgent there, I installed appium using CLI.
I do have WebDriverAgent somewhere else on my machine, which I run there successfully the *Runner*.
When I run your `cmd` from there I got this:
*** Checking out RoutingHTTPServer at "v1.0.1"
*** xcodebuild output can be found in /var/folders/r6/x6gmkcb171xcpcy6m69z6dk00000gn/T/carthage-xcodebuild.P893q7.log
*** Downloading RoutingHTTPServer.framework binary at "v1.0.1"

**Comment by KazuCocoa** [comment]
I ensured `appium@1.14.1` on my local, and exactly the structure is for 1.15.0's one.
We expect 1.14.1 has `WebDriverAgent ` in xcuitest driver.
https://github.com/appium/appium/blob/1.14/npm-shrinkwrap.json


Can you install 1.14.0 instead of 1.14.1 as a workaround?
1.14.1 is a patch release for YouI Engine. Others should be the same as 1.14.0 (but maybe something wrong unexpectedly in npm package)
https://github.com/appium/appium/pull/13008/files

**Comment by BoazWarshawsky** [comment]
Thanks @KazuCocoa the problem is solved, I am just concern since I updated in 4 different CI machines few days ago from appium `1.11.1` to `1.14.1`, all the CI there is running against Simulators and not Real Devices as in our case above.
Should I downgrade to `1.14.0`? its a real problem doing this now

**Comment by KazuCocoa** [comment]
Yes. 1.14.0 is better.

**Comment by KazuCocoa** [comment]
note:

appium prefix packages in `node_modules` by `npm install -g`. Only appium-webdriveragent affects WDA build by xcuitest-driver. Other changes are no problem.

- 1.14.0
```
appium-adb/                 appium-idb/                 appium-selendroid-driver/   appium-xcode/
appium-android-driver/      appium-ios-driver/          appium-support/             appium-xcuitest-driver/
appium-base-driver/         appium-ios-simulator/       appium-tizen-driver/        appium-youiengine-driver/
appium-chromedriver/        appium-mac-driver/          appium-uiautomator2-driver/
appium-espresso-driver/     appium-remote-debugger/     appium-uiautomator2-server/
appium-fake-driver/         appium-sdb/                 appium-windows-driver/
```

- 1.14.1
```
appium-adb/                 appium-fake-driver/         appium-remote-debugger/     appium-uiautomator2-server/
appium-android-driver/      appium-gulp-plugins/        appium-sdb/                 appium-webdriveragent/
appium-base-driver/         appium-idb/                 appium-selendroid-driver/   appium-windows-driver/
appium-chromedriver/        appium-ios-driver/          appium-support/             appium-xcode/
appium-ci/                  appium-ios-simulator/       appium-tizen-driver/        appium-xcuitest-driver/
appium-espresso-driver/     appium-mac-driver/          appium-uiautomator2-driver/ appium-youiengine-driver/
```

**Comment by dpgraham** [comment]
Can you try installing the release candidate `npm install -g appium@rc` and see if that fixes it?

**Comment by KazuCocoa** [comment]
Installed the rc and took a look at node_modules (below) looks fine.

```
appium-adb/                 appium-idb/                 appium-selendroid-driver/   appium-xcode/
appium-android-driver/      appium-ios-driver/          appium-support/             appium-xcuitest-driver/
appium-base-driver/         appium-ios-simulator/       appium-tizen-driver/        appium-youiengine-driver/
appium-chromedriver/        appium-mac-driver/          appium-uiautomator2-driver/
appium-espresso-driver/     appium-remote-debugger/     appium-uiautomator2-server/
appium-fake-driver/         appium-sdb/                 appium-windows-driver/
```

**Comment by mykola-mokhnach** [comment]
Appium 1.14.2 patch has been released a while ago. Closed as fixed.

**Comment by SaiNiranjan** [comment]
> note:
> 
> appium prefix packages in `node_modules` by `npm install -g`. Only appium-webdriveragent affects WDA build by xcuitest-driver. Other changes are no problem.
> 
> * 1.14.0
> 
> ```
> appium-adb/                 appium-idb/                 appium-selendroid-driver/   appium-xcode/
> appium-android-driver/      appium-ios-driver/          appium-support/             appium-xcuitest-driver/
> appium-base-driver/         appium-ios-simulator/       appium-tizen-driver/        appium-youiengine-driver/
> appium-chromedriver/        appium-mac-driver/          appium-uiautomator2-driver/
> appium-espresso-driver/     appium-remote-debugger/     appium-uiautomator2-server/
> appium-fake-driver/         appium-sdb/                 appium-windows-driver/
> ```
> 
> * 1.14.1
> 
> ```
> appium-adb/                 appium-fake-driver/         appium-remote-debugger/     appium-uiautomator2-server/
> appium-android-driver/      appium-gulp-plugins/        appium-sdb/                 appium-webdriveragent/
> appium-base-driver/         appium-idb/                 appium-selendroid-driver/   appium-windows-driver/
> appium-chromedriver/        appium-ios-driver/          appium-support/             appium-xcode/
> appium-ci/                  appium-ios-simulator/       appium-tizen-driver/        appium-xcuitest-driver/
> appium-espresso-driver/     appium-mac-driver/          appium-uiautomator2-driver/ appium-youiengine-driver/
> ```

May I please know how and where can I find all installed components like yours ? Thanks
