### ISSUE TITLE
iOS - Automatically trust enterprise apps

### ISSUE THREAD

**Issue by rameshgit96** [appium/appium#13058]
I am currently testing numerous builds on a daily basis across number of iOS devices.

Every time my test script installs a new .ipa onto each device, the app does not open because the user would then have to manually go to Settings, General, Device Management in order to trust the app.

Is it possible to do this automatically or perhaps, programmatically?

**Comment by mykola-mokhnach** [comment]
In theory something like this would be possible, but too much pain and instability in reality. Check https://github.com/appium/appium/search?q=enterprise+build&unscoped_q=enterprise+build&type=Issues

Please use Appium forum for question
