### ISSUE TITLE
[IOS] pullFile unable to unmount and delete temporary folder because it is busy 

### ISSUE THREAD

**Issue by Valuuin** [appium/appium#13054]
## The problem

I am trying to pull a file from an ios device using the Appium command pullFile. It sees the file in the temporary folder that it crates but when it tries to clean up the system it gives:

 UnhandledPromiseRejectionWarning: Error: Command 'umount /var/folders/9x/_zsjqcs95231lc3xm6l5tkvs7nbz66/T/201978-19929-dskudl.bgknv' exited with code 1

and

Error: EBUSY: resource busy or locked, rmdir '/var/folders/9x/_zsjqcs95231lc3xm6l5tkvs7nbz66/T/201978-19929-dskudl.bgknv'

NOTES:
After the test is finished i can call these commands again and they both work. 
It successfully pulls the file 20% of the time more so if i unplug the device and plug it back in.
It works every time on another mac with same exact specs and set up.

## Environment

* Appium version: 1.14.1
* Desktop OS/version used to run Appium: macOS Mojave 10.14.6
* Node.js version: 12.5.0
* Npm or Yarn package manager: npm 6.10.3
* Mobile platform/version under test: iPhone XS Max 12.1.4
* Java JVM 1.8.0_221
* Java-client 7.1.0
* osxFuse: 3.10.2

## Link to Appium logs

[Logs](https://gist.github.com/Valuuin/1fab7ba63166d356bd6c46c8ce9f9613)

**Comment by mykola-mokhnach** [comment]
appium@beta does not use osxfuse to pull ios files anymore, so this issue gets obsolete

**Comment by Valuuin** [comment]
@mykola-mokhnach  what is the alternative?

**Comment by mykola-mokhnach** [comment]
Check if appium@beta works for you

**Comment by Valuuin** [comment]
Yup it works thanks.
