### ISSUE TITLE
How to test multiple Android devices on the same computer?

### ISSUE THREAD

**Issue by dtboy1995** [appium/appium#13055]
What configurations should I make?

#### The answer I found was to open multiple Appium Servers. Is that the only correct answer? Can I open only one Appium server and control multiple devices at the same time?

Any help would be appreciated.

**Comment by KazuCocoa** [comment]
http://appium.io/docs/en/advanced-concepts/parallel-tests/ will help it. You should coordinate below port numbers.

> udid the device id
> chromeDriverPort the chromedriver port (if using webviews or chrome)
> systemPort If you are using appium-uiautomator2-driver, set a different system port for each android session, set with systemPort capability since sometimes there can be a port conflict if different ports aren't used, such as in this issue.

https://discuss.appium.io will be helpful for such questions
