### ISSUE TITLE
Remote Debugger can't get the right context for iOS 13 web tests

### ISSUE THREAD

**Issue by sadafyadegari** [appium/appium#13069]
## The problem

When running web tests with Xcode 11 beta 5 and iOS 13, web tests fail. 

## Environment

* Appium version (or git revision) that exhibits the issue: 68981b79b6cf904c0188c72e899c70ea1f9d4d3e
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 
* Node.js version (unless using Appium.app|exe): v12.5.0
* Npm or Yarn package manager: npm 6.9.0
* Mobile platform/version under test: iOS 13 
* Real device or emulator/simulator: iPhone 8 Simulator
* Appium CLI or Appium.app|exe: 

## Details

Remote Debugger can't get the right context for iOS 13 web tests. 

## Link to Appium logs

https://gist.github.com/sadafyadegari/5faa0c10a48ccc313cc63c2b10c7675e

## Code To Reproduce Issue [ Good To Have ]
running iOS web test:
`runsauce -c local -t web  -v 13.0 -d "iPhone 8" -a 1.13.0`
appium 68981b79b6cf904c0188c72e899c70ea1f9d4d3e
WebDriverAgent 2ea6a8839c15e268459b81cd3be1b8fe98b0bf36
appium-xcuitest-driver c0bcf3d6ce88bf3cff6a75a965c4417f136e7f36

Test fails when com.apple.mobilesafari.plist is not copied at /Library/Developer/CoreSimulator/Devices/<device-ID>/data/Library/Preferences/

**Comment by mykola-mokhnach** [comment]
Can you please attach the server logs?

**Comment by mykola-mokhnach** [comment]
BTW, Apple has changed the path to CoreSimulator folder since Xcode11, check https://github.com/appium/appium-ios-simulator/pull/235

**Comment by imurchie** [comment]
@sadafyadegari Can you provide a little more color? What is going on on the screen? What page is changed?

Also, can you get the contexts, after the title failure, so we can see what is loading? Thanks!

**Comment by sadafyadegari** [comment]
@imurchie [this is a screenshot ](https://www.dropbox.com/s/1o73ldj1ewjfcs3/failed-test.png?dl=1) of the simulator before it attempts to navigate to https://saucelabs.github.io/training-test-page. Test times out before loading the page. Here are the contexts that were available:
NATIVE_APP
WEBVIEW_60356.1
WEBVIEW_60356.4
WEBVIEW_60356.5

**Comment by imurchie** [comment]
@sadafyadegari There have been some changes, made by @umutuzgur. With the latest beta of Appium does the issue persist?

**Comment by sadafyadegari** [comment]
@imurchie @umutuzgur I'm seeing with this issue still persists with cold simulators. We have a workaround for this that we used for iOS 12.2, so it is not a blocker. But it would have been nice to have the tests pass without that workaround.

**Comment by imurchie** [comment]
@sadafyadegari I would like to get it to work as well. Unfortunately I still cannot get the bookmarks to report of windows, and cannot reproduce.

Can you provide the server logs with the latest beta, and with getting the contexts after the title failure?

**Comment by imurchie** [comment]
@sadafyadegari Did changing the polling fix this problem?  It seems to work for me, locally, now.

**Comment by sadafyadegari** [comment]
@imurchie it did fix the issue locally. We haven't yet tested this in our VMs though but so far it's looking good

**Comment by imurchie** [comment]
@sadafyadegari Ok. Let us know when things are confirmed, one way or the other, on VMs.

**Comment by mykola-mokhnach** [comment]
@sadafyadegari Can the issue be closed?

**Comment by dpgraham** [comment]
Yep
