### ISSUE TITLE
Appium Desktop (not CLI) doesn't fetch web views from Safari on real iPad device

### ISSUE THREAD

**Issue by pmswatuser** [appium/appium#13060]
The problem

Unable to run mobile web tests on real iOS device or simulator. This could seem similar to #5794 but that issue was locked down due to inactivity.

Environment

Appium version 1.12.1 and 1.13.0
Xcode 10.3
Appium java-client 3.4.1
iOS 12.2 on real iPad 6th gen
Appium server on Mac OS Mojave
Details

Followed all instructions to setup Appium for real iOS device, as found under http://appium.io/docs/en/drivers/ios-xcuitest-real-devices/

The WDA is deployed to the device and the test launches safari but does not navigate to the URL specified in the code or get web views. IWDP was started using all suggested methods.

ios_webkit_debug_proxy returns 9222 for attach A, first device with the UDID

Also tried launching IWDP using ios_webkit_debug_proxy -c :27753 -d and changing the port to 9222. Tried combination of both, keeping both sessions on.

Link to Appium logs

gist log link for Appium and iOS-webkit-debug-proxy logs

https://gist.github.com/pmswatuser/2d5b0428828d2b9b07d25fa223d0c063

Code

Capabilitites used:
capabilities = new DesiredCapabilities();
capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "name-of-device");
capabilities.setCapability(MobileCapabilityType.UDID, "removed");
capabilities.setCapability(MobileCapabilityType.PLATFORM, "iOS");
capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "12.2");
capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "Safari");
capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");

**Comment by pmswatuser** [comment]
If this is a duplicate, please share the issue ticket with the resolution. None of the resolutions seem to work. Old issues are locked down due to inactivity. @imurchie solution

**Comment by pmswatuser** [comment]
@imurchie your suggestion in another issue was also tried. Using a port other than 27753 when starting IWDP. Please help.

**Comment by pmswatuser** [comment]
Update: After Appium launches safari on the device, since IWDP is started, I am able to get to http://localhost:27753/json. But since safari is not navigating to any URL, the json is blank. If I manaully, navigate to a website, http://localhost:27753/json is updated with that web view. driver.get("any url") does not navigate and eventually fails.

Also, why does Appium log always try to navigate to this: Selecting by url: true (expected url: 'http://appium.io')

Where is this URL specified? It seems to be fetching web views from that url, although we have not mentioned it in the code.

**Comment by pmswatuser** [comment]
For your awareness and for the benefit of others that might read this ticket in the future, uninstalling Appium desktop and installing Appium CLI resolved the issue. Using Appium v 1.14.1 now. I had to spend hours chasing this inconsistency & trying out various permutations.

Can someone explain why Webdriver on iOS launches Appium.io URL first, before redirecting to the URL of choice?

**Comment by imurchie** [comment]
`appium.io` is the default URL to which Appium directs real device Safari tests, unless something else is specified with the `safariInitialUrl` desired capability.

**Comment by imurchie** [comment]
What version of ios-webkit-debug-proxy are you using?

**Comment by pmswatuser** [comment]
Thanks for the comment on initial url. proxy version is 1.8.5

**Comment by pmswatuser** [comment]
Proxy was fetching the web views on the device, even with Appium desktop installed. I tried localhost:27753/json and it refreshes based on manual browsing on the device. Appium desktop version just doesn't navigate to the default appium.io url and just stays put after launching a blank safari session.

**Comment by imurchie** [comment]
Can you try a more recent version of Appium? You'll notice in the Changelog, v1.12.1 had support for safari/webviews on iOS 12.2 simulators, while v1.13.0 has support for real devices. v1.14.0 has iteratively better support, as well.

**Comment by pmswatuser** [comment]
v1.13.0 appium desktop also did not work. IWDP is working just fine when I browse localhost:27753/json. Appium desktop version is not able to navigate after launching safari on real iPad.

**Comment by mykola-mokhnach** [comment]
There is `includeSafariInWebviews` capability since Appium 1.15. Setting it to `true` should make Safari web views accessible for Appium scripts.
