### ISSUE TITLE
Appium Folder directory issue. 

### ISSUE THREAD

**Issue by aruvimal** [appium/appium#13075]
## The problem

i can see appium main.js file is located in below two paths. Not use how to remove these two directory and want to install freshly. 

/usr/local/lib/node_modules/appium/build/lib/main.js
/Users/<UserID>/node_modules/node/lib/node_modules/appium/build/lib/main.js

When i try to run the appium server using /usr/local/lib/node_modules/appium/build/lib/main.js, i always getting below issue. Actually when i run in another machine, my script is executed without any issuel.

## Environment

info AppiumDoctor Appium Doctor v.1.11.1
info AppiumDoctor ### Diagnostic for necessary dependencies starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: node_modules/.bin/node
info AppiumDoctor  ✔ Node version is 12.6.0
info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ Xcode Command Line Tools are installed in: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ DevToolsSecurity is enabled.
info AppiumDoctor  ✔ The Authorization DB is set up properly.
info AppiumDoctor  ✔ Carthage was found at: /usr/local/bin/carthage. Installed version is: 0.33.0
info AppiumDoctor  ✔ HOME is set to: /Users/vz8zw5
info AppiumDoctor  ✔ ANDROID_HOME is set to: /Users/vz8zw5/Library/Android/sdk
info AppiumDoctor  ✔ JAVA_HOME is set to: /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home
info AppiumDoctor  ✔ adb exists at: /Users/vz8zw5/Library/Android/sdk/platform-tools/adb
info AppiumDoctor  ✔ android exists at: /Users/vz8zw5/Library/Android/sdk/tools/android
info AppiumDoctor  ✔ emulator exists at: /Users/vz8zw5/Library/Android/sdk/tools/emulator
info AppiumDoctor  ✔ Bin directory of $JAVA_HOME is set
info AppiumDoctor ### Diagnostic for necessary dependencies completed, no fix needed. ###
info AppiumDoctor 
info AppiumDoctor ### Diagnostic for optional dependencies starting ###
WARN AppiumDoctor  ✖ opencv4nodejs cannot be found.
WARN AppiumDoctor  ✖ ffmpeg cannot be found
WARN AppiumDoctor  ✖ mjpeg-consumer cannot be found.
WARN AppiumDoctor  ✖ idb and idb_companion are not installed
WARN AppiumDoctor  ✖ applesimutils cannot be found
WARN AppiumDoctor  ✖ idevicelocation cannot be found
WARN AppiumDoctor  ✖ ios-deploy cannot be found
WARN AppiumDoctor  ✖ ios_webkit_debug_proxy cannot be found
WARN AppiumDoctor  ✖ ifuse cannot be found
WARN AppiumDoctor  ✖ bundletool.jar cannot be found
info AppiumDoctor ### Diagnostic for optional dependencies completed, 10 fixes possible. ###
info AppiumDoctor 
info AppiumDoctor ### Optional Manual Fixes ###
info AppiumDoctor The configuration can install optionally. Please do the following manually:
WARN AppiumDoctor  ➜ Why opencv4nodejs is needed and how to install it: https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/image-comparison.md
WARN AppiumDoctor  ➜ ffmpeg is needed to record screen features. Please read https://www.ffmpeg.org/ to install it
WARN AppiumDoctor  ➜ mjpeg-consumer module is required to use MJPEG-over-HTTP features. Please install it with 'npm i -g mjpeg-consumer'.
WARN AppiumDoctor  ➜ Why idb is needed and how to install it: https://github.com/appium/appium-idb
WARN AppiumDoctor  ➜ Why applesimutils is needed and how to install it: http://appium.io/docs/en/drivers/ios-xcuitest/
WARN AppiumDoctor  ➜ idevicelocation is used to set geolocation for real device. Please read https://github.com/JonGabilondoAngulo/idevicelocation to install it
WARN AppiumDoctor  ➜ ios-deploy is used to install iOS applications to real device. Please read http://appium.io/docs/en/drivers/ios-xcuitest-real-devices/ to install it
WARN AppiumDoctor  ➜ ios_webkit_debug_proxy is used to proxy requests from Appium to MobileSafari running on real device. Please read https://github.com/google/ios-webkit-debug-proxy to install it
WARN AppiumDoctor  ➜ ifuse is used to manage files/folders against a real device. Please read https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios/ios-xctest-file-movement.md to install it
WARN AppiumDoctor  ➜ bundletool.jar is used to handle Android App Bundle. Please read http://appium.io/docs/en/writing-running-appium/android/android-appbundle/ to install it
info AppiumDoctor 
info AppiumDoctor ###
info AppiumDoctor 
info AppiumDoctor Bye! Run appium-doctor again when all manual fixes have been applied!
info AppiumDoctor 

## Error
35m[XCUITest][39m [1mFetching dependencies
[35m[XCUITest][39m *** Checking out CocoaAsyncSocket at "7.6.3"
[35m[XCUITest][39m *** Checking out RoutingHTTPServer at "v1.0.2"
[35m[XCUITest][39m *** Checking out YYCache at "1.1.0"
[35m[XCUITest][39m Failed to check out repository into /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/CocoaAsyncSocket: Could not create working directory (Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “CocoaAsyncSocket” in the folder “Checkouts”." UserInfo={NSFilePath=/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/CocoaAsyncSocket, NSUnderlyingError=0x7fa804f0ecc0 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}})
[35m[XCUITest][39m [1mFetching dependencies
[35m[XCUITest][39m *** Checking out CocoaAsyncSocket at "7.6.3"
[35m[XCUITest][39m *** Checking out RoutingHTTPServer at "v1.0.2"
[35m[XCUITest][39m *** Checking out YYCache at "1.1.0"
[35m[XCUITest][39m Failed to check out repository into /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/CocoaAsyncSocket: Could not create working directory (Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “CocoaAsyncSocket” in the folder “Checkouts”." UserInfo={NSFilePath=/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/CocoaAsyncSocket, NSUnderlyingError=0x7fd1efd3af40 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}})
[35m[XCUITest][39m [1mFetching dependencies
[35m[XCUITest][39m *** Checking out CocoaAsyncSocket at "7.6.3"
[35m[XCUITest][39m *** Checking out RoutingHTTPServer at "v1.0.2"
[35m[XCUITest][39m *** Checking out YYCache at "1.1.0"
[35m[XCUITest][39m Failed to check out repository into /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/YYCache: Could not create working directory (Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “YYCache” in the folder “Checkouts”." UserInfo={NSFilePath=/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/YYCache, NSUnderlyingError=0x7fed5ad68690 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}})
[35m[XCUITest][39m [1mFetching dependencies
[35m[XCUITest][39m *** Checking out CocoaAsyncSocket at "7.6.3"
[35m[XCUITest][39m *** Checking out YYCache at "1.1.0"
[35m[XCUITest][39m *** Checking out RoutingHTTPServer at "v1.0.2"
[35m[XCUITest][39m Failed to check out repository into /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/YYCache: Could not create working directory (Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “YYCache” in the folder “Checkouts”." UserInfo={NSFilePath=/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/YYCache, NSUnderlyingError=0x7fb0af70e2f0 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}})
[35m[XCUITest][39m Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1
[35m[XCUITest][39m     at quitAndUninstall (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:515:15)
[35m[XCUITest][39m     at /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:545:11
[35m[XCUITest][39m     at wrapped (/usr/local/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:35:13)
[35m[XCUITest][39m     at retry (/usr/local/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:18:13)
[35m[XCUITest][39m     at retryInterval (/usr/local/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:45:10)
[35m[XCUITest][39m     at /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:525:7
2019-08-14 13:40:06 ERROR BaseTest:3237 - FAIL : FAIL: WEBIOS browser launch unsuccessful. DETAILS: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'USCHAMNMOG0JK78', ip: '2606:a000:1215:c3b2:74c5:78f2:aa31:1661', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.5', java.version: '1.8.0_91'
Driver info: driver.version: IOSDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1
    at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:826:9)
    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:447:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'USCHAMNMOG0JK78', ip: '2606:a000:1215:c3b2:74c5:78f2:aa31:1661', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.5', java.version: '1.8.0_91'
Driver info: driver.version: IOSDriver
If necessary, describe the problem you have been experiencing in more detail.

**Comment by mykola-mokhnach** [comment]
> Could not create working directory (Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “YYCache” in the folder “Checkouts”." UserInfo={NSFilePath=/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/YYCache, NSUnderlyingError=0x7fed5ad68690 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}})

What exactly is unclear with this error?

**Comment by stephenjg24-git** [comment]
Following, 

my folder /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/  did not have any folder called WebDriverAgent and since it is missing I have not script folder to execute anything from

**Comment by mykola-mokhnach** [comment]
It might be the same problem as in https://github.com/appium/appium/issues/13047

**Comment by stephenjg24-git** [comment]
this issue in #13047 . looks very much like my issue

I ran npm install -g appium@rc and it fixed  the missing folder.

Thanks

**Comment by stephenjg24-git** [comment]
I want to confirm that running npm install -g appium@rc  and then signing the WDA corrected the errors and I am not able to get the AUT installed on the iPhone.

I had been Appium 1.14.1 I do not know if lower versions have the issue or not.

**Comment by KazuCocoa** [comment]
This happens only 1.14.1 since it seemed 1.14.1 had wrong npm deps.
1.14.0 does not have this issue.
