### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by aupong** [appium/appium#13074]
## The problem
When running a test to get the screenshots continuously, there is a Fatal error occur after running for about 100 minutes. The error message as below

<--- Last few GCs --->

[6489:0x562631a6d140]  7182264 ms: Mark-sweep 1394.6 (1422.7) -> 1394.6 (1422.7) MB, 26.8 / 0.0 ms  allocation failure GC in old space requested
[6489:0x562631a6d140]  7182292 ms: Mark-sweep 1394.6 (1422.7) -> 1394.6 (1415.7) MB, 27.4 / 0.0 ms  last resort GC in old space requested
[6489:0x562631a6d140]  7182317 ms: Mark-sweep 1394.6 (1415.7) -> 1394.6 (1415.7) MB, 25.4 / 0.0 ms  last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3dd494298fe1 <JSObject>
    0: builtin exit frame: parse(this=0x3dd4942a9c41 <Object map = 0x2d586b18f251>,0xd896ae82201 <Very long string[1135654]>)

    1: safeJsonParse [/usr/local/lib/node_modules/appium/node_modules/appium-support/build/lib/util.js:118] [bytecode=0xcb1caf95a21 offset=15](this=0x29c5bf108a11 <Object map = 0xf7ac95c4361>,obj=0xd896ae82201 <Very long string[1135654]>)
    2: proxy [/usr/local/lib/nod...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x56262fe3d011 [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewRawOneByteString(int, v8::internal::PretenureFlag) [node]
 6: v8::internal::Handle<v8::internal::String> v8::internal::JsonParser<true>::SlowScanJsonString<v8::internal::SeqOneByteString, unsigned char>(v8::internal::Handle<v8::internal::String>, int, int) [node]
 7: v8::internal::JsonParser<true>::ParseJsonValue() [node]
 8: v8::internal::JsonParser<true>::ParseJsonObject() [node]
 9: v8::internal::JsonParser<true>::ParseJson() [node]
10: 0x56262f7f002b [node]
11: 0x2dbe290996dd
Aborted (core dumped)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.1
* Last Appium version that did not exhibit the issue (if applicable): 1.12.1
* Desktop OS/version used to run Appium: Ubuntu 18.04.3 LTS 
* Node.js version (unless using Appium.app|exe): v8.10.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Android 7.1.2
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: cli

**Comment by mykola-mokhnach** [comment]
Try appium@beta. There are several fixes for OOM issues there. Also, please take the heap snapshot when memory usage is high and attach to to this report

**Comment by mykola-mokhnach** [comment]
Linked https://github.com/appium/appium/issues/12838

**Comment by mykola-mokhnach** [comment]
Also make sure the NodeJS is up to date

**Comment by mykola-mokhnach** [comment]
no snapshots - no luck
