### ISSUE TITLE
Appium 1.13 Unable to Connect Appium to Real iOS Device

### ISSUE THREAD

**Issue by DhruvSharma12** [appium/appium#13073]
## The problem
Appium is unable to connect to real iOS Device

## Configurations setup to reproduce the error
1) Configure Xcode for automatic signing for WDA project:- Provisioning Profile is added. I have done the configuration for Automatic Managing Signing for WebDriverAgent Lib and WebDriverAgent Runner in WebDriverAgent.xcodeproj
2) Run the WDA command to run on real device:- I am switching to my WebDriverAgent folder and building it using these two commands:-
a)  ./Scripts/bootstrap.sh -d
b) xcodebuild build test -project WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id="<id>" test
This command is installing WebDriverAgent in my real iOS device and terminal final line shows 'ServerURLHere->http://192.168.15.125:8100<-ServerURLHere'
3) After running this command if launching appium to connect to real device with deviceconfigurations as:-
{
  "platformName": "iOS",
  "platformVersion": "12.0.1",
  "deviceName": "iPhone",
  "bundleId": "<bundleId>",
  "udid": "<udid>",
  "xcodeOrgId": "<orgid>",
  "xcodeSigningId": "iPhone Developer"
} 

then on terminal it shows ‘Build Interrupted’. On appium following error popups:-

**Error**:- An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65 xcodebuild error message: 2019-08-12 11:50:21.366 xcodebuild[79637:765544] iPhoneConnect: 📱<DVTiOSDevice (0x7f929cd2ee40), iPhone, iPhone, 12.0.1 (16A404), 9d29ab5386f35815871d5bb0baa8ab6a635c7809> failed to install /Users/abhisharsrivastava/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app - error Error Domain=com.apple.dtdevicekit Code=-402620392 "Unable to install "WebDriverAgentRunner-Runner"" UserInfo={NSLocalizedDescription=Unable to install "WebDriverAgentRunner-Runner", NSLocalizedRecoverySuggestion=The certificate used to sign "WebDriverAgentRunner-Runner" has either expired or has been revoked. An updated certificate is required to sign and install the application.} *** If you believe this error represents a bug, please attach the result bundle at /Users/abhisharsrivastava/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2019.08.12_11-50-18-+0530.xcresult 2019-08-12 11:50:21.372 xcodebuild[79637:765429] [MT] IDETestOperationsObserverDebug: 2.364 elapsed -- Testing started completed. 2019-08-12 11:50:21.372 xcodebuild[79637:765429] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start 2019-08-12 11:50:21.372 xcodebuild[79637:765429] [MT] IDETestOperationsObserverDebug: 2.364 sec, +2.364 sec -- end 2019-08-12 11:50:21.376 xcodebuild[79637:765429] Error Domain=com.apple.dtdevicekit Code=-402620392 "Unable to install "WebDriverAgentRunner-Runner"" UserInfo={NSLocalizedDescription=Unable to install "WebDriverAgentRunner-Runner", NSLocalizedRecoverySuggestion=The certificate used to sign "WebDriverAgentRunner-Runner" has either expired or has been revoked. An updated certificate is required to sign and install the application.} 2019-08-12 11:50:21.377 xcodebuild[79637:765429] Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Failed to install or launch the test runner" UserInfo={NSLocalizedRecoverySuggestion=If you believe this error represents a bug, please attach the result bundle at /Users/abhisharsrivastava/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2019.08.12_11-50-18-+0530.xcresult, NSLocalizedDescription=Failed to install or launch the test runner, NSUnderlyingError=0x7f929c928650 {Error Domain=com.apple.dtdevicekit Code=-402620392 "Unable to install "WebDriverAgentRunner-Runner"" UserInfo={NSLocalizedDescription=Unable to install "WebDriverAgentRunner-Runner", NSLocalizedRecoverySuggestion=The certificate used to sign "WebDriverAgentRunner-Runner" has either expired or has been revoked. An updated certificate is required to sign and install the application.}}} Testing failed: WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: Unable to install "WebDriverAgentRunner-Runner")) ** TEST EXECUTE FAILED ** Testing started on 'iPhone'. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.

## Environment

Appium version (or git revision) that exhibits the issue: 1.13.0
Desktop OS/version used to run Appium: Mac High Sierra
Mobile platform/version under test: iOS 12.0.1
Real device or emulator/simulator: Real device

## Link to Appium logs
https://gist.github.com/DhruvSharma12/8775948e1b221d56982759dbfabafc29

**Comment by mykola-mokhnach** [comment]
> The certificate used to sign "WebDriverAgentRunner-Runner" has either expired or has been revoked. An updated certificate is required to sign and install the application

This is for sure a problem with your certificate. Nothing we could do about it

**Comment by DhruvSharma12** [comment]
What type of certificate issue is this? Can you show some light so that I can ask my Developers to provide or fix the same

**Comment by mykola-mokhnach** [comment]
This must be a valid developer certificate (not enterprise)

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by mykola-mokhnach** [comment]
Feel free to use Appium forum if you have more questions
