### ISSUE TITLE
xcode 11 changes the bundle id of WDA

### ISSUE THREAD

**Issue by umutuzgur** [appium/appium#13086]
## The problem

XCode 11 changed the format for building xcuitest runner bundle ids. WDA no longer has the bundle id as `com.apple.test.WebDriverAgentRunner-Runner` but as `com.facebook.WebDriverAgentRunner.xctrunner`

## Details

This causes issues in terms of uninstallation of WDA and we should take a look at it

**Comment by KazuCocoa** [comment]
ah... the bundle id will be `com.customised.WebDriverAgentRunner.xctrunner` when `updatedWDABundleId` is provided with Xcode 11.

**Comment by doganmavuzer** [comment]
If you create your provision profile as wildcard. You don't have to handle with projects bundleId and nothing effects your build.

**Comment by umutuzgur** [comment]
@doganmavuzer This issue is related to uninstallation of WDA since Appium uninstalls it before the session start with certain capabilities

**Comment by tiecongli** [comment]
A silly question: how may I check if my installed appium version 1.15.09 has this fix?

**Comment by KazuCocoa** [comment]
Not sure the version label, 1.15.09, but Appium's 1.15.0 release has this change.
Then, you can see log messages introduced in this PR like https://github.com/appium/appium-xcuitest-driver/pull/1052/files#diff-dd1c1e9a4d2cba48fc21e5d2c50abcafR174

**Comment by JabberYQ** [comment]
I also had this problem in monkey test.
I found it normal on Xcode11.1  and Xcode11.2  will auto add subffix 'xctrunner' to my bundle id.
now I find a way to solve it. go to runner target - build settings-product bundle id and clear it. and then set your bundle id in plist.info - Bundle identifier.

must clear build settings-product bundle id!!

**Comment by crifan** [comment]
as @JabberYQ said, and more details here:

Use `Xcode` open `WebDriverAgent.xcodeproj`, then do changes:

1. `WebDriverAgentRunner/Info.plist`->`Bundle Identifier`
  * change to `com.xxx.wda.runner`
    * ![42D4CC39-7D8D-4DBE-9124-6F0114943740](https://user-images.githubusercontent.com/2750682/74898900-383f4a00-53d6-11ea-88d8-b616b2f818a6.png)
2.`WebDriverAgent -> Targets ->WebDriverAgentRunner -> Info -> Bundle Identifier`
  * change to `com.xxx.wda.runner`
    * ![EC1405A0-39B1-422B-88B1-519CB3005016](https://user-images.githubusercontent.com/2750682/74898963-7472aa80-53d6-11ea-9fa1-f7641cccfaa2.png)
3. `WebDriverAgent -> Targets -> WebDriverAgentRunner -> Build Settings -> Packing -> Product Bundle Identifier`
  * keep empty = clear it
    * ![BD1D2073-DC77-4E68-B75A-61337A170597](https://user-images.githubusercontent.com/2750682/74899018-a08e2b80-53d6-11ea-80fe-63fa15faa3aa.png)

4. =>> `WebDriverAgent -> Targets -> WebDriverAgentRunner -> Signing & Capability`
  * **Team**: `xxx (Personal Team)` or your team
  * **Bundle Identifier**: `com.xxx.wda.runner`
    * will auto change to, no edit by yourself
  * **Signing Certificate**: `Development`
    * will auto `code signing` + `create provisioning file` + ...
    * Makesure **NO** red erros
  * ![113D4E4F-C889-4698-84E7-61E4ED15A4D9](https://user-images.githubusercontent.com/2750682/74899196-27db9f00-53d7-11ea-8313-2e1bf29867f2.png)

all done !

Note: change `xxx` to your organization name.

**Comment by Ibnfarooqvlm** [comment]
The above setup was working for me so far. Just updated xcode to 11.5. There, if we did not provide Bundle Identifier its throwing error message:
![image](https://user-images.githubusercontent.com/6194278/87127900-5be32e00-c2ac-11ea-8e9d-b6d4cd304fc9.png)
![image](https://user-images.githubusercontent.com/6194278/87127826-3eae5f80-c2ac-11ea-9b10-a1dc6a652eb8.png)

I am getting this error message:
![image](https://user-images.githubusercontent.com/6194278/87128330-0fe4b900-c2ad-11ea-8e22-bdb89a846336.png)

Any idea on the same?
