### ISSUE TITLE
iOS 13 beta Webview test fails

### ISSUE THREAD

**Issue by sadafyadegari** [appium/appium#13081]
## The problem

Appium hyrbrid test fails with iOS 13 beta. 

## Environment

* Appium version (or git revision) that exhibits the issue: 68981b79b6cf904c0188c72e899c70ea1f9d4d3e
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS Mojave 10.14.6 
* Node.js version (unless using Appium.app|exe): v12.5.0
* Npm or Yarn package manager: npm 6.9.0
* Mobile platform/version under test: iOS 13
* Real device or emulator/simulator: Phone Xs Max
* Appium CLI or Appium.app|exe:

## Details

Appium hyrbrid test fails with iOS 13 beta as it cannot find the webview context. 

## Link to Appium logs

[Appium logs](https://gist.github.com/sadafyadegari/fa06807c1c560dbf49ead405303d9277)

## Code To Reproduce Issue [ Good To Have ]
test command `./bin/runsauce.js -c local -t ios_hybrid -v 13.0 -d "iPhone Xs Max" -a 1.12.1 -e '{"fullReset":"true"}' `

**Comment by umutuzgur** [comment]
@sadafyadegari It seems like there is a race condition here. The app reports the webview after we respond to getContext call with a failure. I should probably put a delay between the retries and it should fix the issue

**Comment by sadafyadegari** [comment]
@umutuzgur I'm seeing webview tests passing after pulling the latest PR you had merged in appium for this issue.

**Comment by umutuzgur** [comment]
Cool. I'm closing the issue then
