### ISSUE TITLE
Running appium locally and directly can run normally and report errors through Jenkins

### ISSUE THREAD

**Issue by rggaoxin** [appium/appium#13085]
## The problem

Running appium locally and directly can run normally and report errors through Jenkins。
order:  
nohup /root/.nvm/versions/node/v8.7.0/bin/appium --chromedriver-executable /opt/chromedriver_2.40/chromedriver --session-override -a 127.0.0.1 -p 4723 &> /opt/appium_log/appium.log &
## Environment

* Appium version : v1.10.0

## logs

HTTP] --> POST /wd/hub/session
[HTTP] {"capabilities":{"firstMatch":[{"platformName":"Android","appium:deviceName":"2377c413","appium:platformVersion":"8.1","appium:appPackage":"com.jsti.maxbrfix","appium:appActivity":"com.jsti.maxbrfix.MainActivity","appium:resetKeyboard":true,"appium:noReset":true,"appium:newCommandTimeout":6000,"appium:automationName":"UiAutomator2","appium:unicodeKeyboard":true,"appium:chromedriverExecutableDir":"/opt/chromedriver_2.42","appium:recreateChromeDriverSessions":true,"appium:useNewWDA":true}]},"desiredCapabilities":{"platformName":"Android","deviceName":"2377c413","platformVersion":"8.1","appPackage":"com.jsti.maxbrfix","appActivity":"com.jsti.maxbrfix.MainActivity","resetKeyboard":true,"noReset":true,"newCommandTimeout":6000,"automationName":"UiAutomator2","unicodeKeyboard":true,"chromedriverExecutableDir":"/opt/chromedriver_2.42","recreateChromeDriverSessions":true,"useNewWDA":true}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"platformName":"Android","deviceName":"2377c413","platformVersion":"8.1","appPackage":"com.jsti.maxbrfix","appActivity":"com.jsti.maxbrfix.MainActivity","resetKeyboard":true,"noReset":true,"newCommandTimeout":6000,"automationName":"UiAutomator2","unicodeKeyboard":true,"chromedriverExecutableDir":"/opt/chromedriver_2.42","recreateChromeDriverSessions":true,"useNewWDA":true},null,{"firstMatch":[{"platformName":"Android","appium:deviceName":"2377c413","appium:platformVersion":"8.1","appium:appPackage":"com.jsti.maxbrfix","appium:appActivity":"com.jsti.maxbrfix.MainActivity","appium:resetKeyboard":true,"appium:noReset":true,"appium:newCommandTimeout":6000,"appium:automationName":"UiAutomator2","appium:unicodeKeyboard":true,"appium:chromedriverExecutableDir":"/opt/chromedriver_2.42","appium:recreateChromeDriverSessions":true,"appium:useNewWDA":true}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1565922722189 (10:32:02 GMT+0800 (CST))
[Appium] Creating new AndroidUiautomator2Driver (v1.34.0) session
[Appium] Capabilities:
[Appium]   platformName: Android
[Appium]   deviceName: 2377c413
[Appium]   platformVersion: 8.1
[Appium]   appPackage: com.jsti.maxbrfix
[Appium]   appActivity: com.jsti.maxbrfix.MainActivity
[Appium]   resetKeyboard: true
[Appium]   noReset: true
[Appium]   newCommandTimeout: 6000
[Appium]   automationName: UiAutomator2
[Appium]   unicodeKeyboard: true
[Appium]   chromedriverExecutableDir: /opt/chromedriver_2.42
[Appium]   recreateChromeDriverSessions: true
[Appium]   useNewWDA: true
[debug] [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {
[debug] [BaseDriver]   "alwaysMatch": {
[debug] [BaseDriver]     "platformName": "Android",
[debug] [BaseDriver]     "appium:deviceName": "2377c413",
[debug] [BaseDriver]     "appium:platformVersion": "8.1",
[debug] [BaseDriver]     "appium:appPackage": "com.jsti.maxbrfix",
[debug] [BaseDriver]     "appium:appActivity": "com.jsti.maxbrfix.MainActivity",
[debug] [BaseDriver]     "appium:resetKeyboard": true,
[debug] [BaseDriver]     "appium:noReset": true,
[debug] [BaseDriver]     "appium:newCommandTimeout": 6000,
[debug] [BaseDriver]     "appium:automationName": "UiAutomator2",
[debug] [BaseDriver]     "appium:unicodeKeyboard": true,
[debug] [BaseDriver]     "appium:chromedriverExecutableDir": "/opt/chromedriver_2.42",
[debug] [BaseDriver]     "appium:recreateChromeDriverSessions": true,
[debug] [BaseDriver]     "appium:useNewWDA": true
[debug] [BaseDriver]   },
[debug] [BaseDriver]   "firstMatch": [
[debug] [BaseDriver]     {}
[debug] [BaseDriver]   ]
[debug] [BaseDriver] }
[BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[BaseDriver]   useNewWDA
[BaseDriver] Session created with session id: c68c8c50-ed9a-4d98-905f-ade69e9beb26
[ADB] The ANDROID_HOME environment variable is not set to the Android SDK root directory path. ANDROID_HOME is required for compatibility with SDK 23+. Checking along PATH for adb.
[ADB] Using 'adb' from '/test/android/platform-tools/adb'
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[AndroidDriver] Looking for a device with Android '8.1'
[debug] [ADB] Setting device id to 10.60.44.32:5555
[ADB] Getting device platform version
[debug] [ADB] Running '/test/android/platform-tools/adb -P 5037 -s 10.60.44.32\:5555 shell getprop ro.build.version.release'
[debug] [ADB] Current device property 'ro.build.version.release': 8.1.0
[AndroidDriver] Using device: 10.60.44.32:5555
[ADB] The ANDROID_HOME environment variable is not set to the Android SDK root directory path. ANDROID_HOME is required for compatibility with SDK 23+. Checking along PATH for adb.
[ADB] Using 'adb' from '/test/android/platform-tools/adb'
[debug] [ADB] Setting device id to 10.60.44.32:5555
[debug] [ADB] Running '/test/android/platform-tools/adb -P 5037 -s 10.60.44.32\:5555 shell getprop ro.build.version.sdk'
[debug] [ADB] Current device property 'ro.build.version.sdk': 27
[debug] [ADB] Device API level: 27
[AndroidDriver] No app sent in, not parsing package/activity
[debug] [ADB] Running '/test/android/platform-tools/adb -P 5037 -s 10.60.44.32\:5555 wait-for-device'
[debug] [ADB] Running '/test/android/platform-tools/adb -P 5037 -s 10.60.44.32\:5555 shell echo ping'
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Getting install status for io.appium.settings
[debug] [ADB] Running '/test/android/platform-tools/adb -P 5037 -s 10.60.44.32\:5555 shell dumpsys package io.appium.settings'
[debug] [ADB] 'io.appium.settings' is installed
[debug] [ADB] Getting package info for 'io.appium.settings'
[debug] [ADB] Running '/test/android/platform-tools/adb -P 5037 -s 10.60.44.32\:5555 shell dumpsys package io.appium.settings'
[ADB] Cannot extract apk info using apkanalyzer. Falling back to aapt. Original error: Could not find 'apkanalyzer' in ["/root/platform-tools/apkanalyzer","/root/emulator/apkanalyzer","/root/tools/apkanalyzer","/root/tools/bin/apkanalyzer"]. Do you have Android Build Tools installed at ''?
[ADB] The ANDROID_HOME environment variable is not set to the Android SDK root directory path. ANDROID_HOME is required for compatibility with SDK 23+. Checking along PATH for aapt.
[debug] [ADB] Getting install status for io.appium.settings
[debug] [ADB] Running '/test/android/platform-tools/adb -P 5037 -s 10.60.44.32\:5555 shell dumpsys package io.appium.settings'
[debug] [ADB] 'io.appium.settings' is installed
[debug] [ADB] Getting package info for 'io.appium.settings'
[debug] [ADB] Running '/test/android/platform-tools/adb -P 5037 -s 10.60.44.32\:5555 shell dumpsys package io.appium.settings'
[ADB] Cannot extract apk info using apkanalyzer. Falling back to aapt. Original error: Could not find 'apkanalyzer' in ["/root/platform-tools/apkanalyzer","/root/emulator/apkanalyzer","/root/tools/apkanalyzer","/root/tools/bin/apkanalyzer"]. Do you have Android Build Tools installed at ''?
[ADB] The ANDROID_HOME environment variable is not set to the Android SDK root directory path. ANDROID_HOME is required for compatibility with SDK 23+. Checking along PATH for aapt.
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [ADB] Running '/test/android/platform-tools/adb -P 5037 -s 10.60.44.32\:5555 shell am force-stop com.jsti.maxbrfix'
[debug] [ADB] Removing forwarded port socket connection: 8202 
[debug] [ADB] Running '/test/android/platform-tools/adb -P 5037 -s 10.60.44.32\:5555 forward --remove tcp\:8202'
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command '/test/android/platform-tools/adb -P 5037 -s 10.60.44.32\:5555 forward --remove tcp\:8202' exited with code 1'; Stderr: 'adb: error: listener 'tcp:8202' not found'; Code: '1''
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1565922722859 (10:32:02 GMT+0800 (CST))
[debug] [W3C] Encountered internal error running command: Error: Could not find 'aapt' in PATH. Please set the ANDROID_HOME or ANDROID_SDK_ROOT environment variables to the corect Android SDK root directory path.
[debug] [W3C]     at ADB.getBinaryFromPath (/root/.nvm/versions/node/v8.7.0/lib/node_modules/appium/node_modules/_appium-adb@7.12.0@appium-adb/lib/tools/system-calls.js:135:11)
[debug] [W3C]     at <anonymous>
[HTTP] <-- POST /wd/hub/session 500 674 ms - 907

**Comment by mykola-mokhnach** [comment]
> Encountered internal error running command: Error: Could not find 'aapt' in PATH. Please set the ANDROID_HOME or ANDROID_SDK_ROOT environment variables to the corect Android SDK root directory path.

You must set proper environment variables. Check https://github.com/appium/java-client/blob/master/docs/environment.md

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
