### ISSUE TITLE
Appium execution is very slow in android emulator in mac 10.14.6

### ISSUE THREAD

**Issue by JayasriPV** [appium/appium#13097]
## The problem

Appium script execution is very slow in android emulator (taking half an hour to execute simple 7 test cases - means not used lot of xpaths)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.0
* Desktop OS/version used to run Appium: MAC 10.14.6
* Node.js version (unless using Appium.app|exe): 12.8.0
* Npm or Yarn package manager:6.10.3
* Mobile platform/version under test: Android Nexus 9.0
* Real device or emulator/simulator:Emulator (android studio)
* Appium CLI or Appium.app|exe:Java

## Details

Automation script execution is very slow using appium 1.14.1, have installed appium through npm

Let me know if you need any other details

**Comment by mykola-mokhnach** [comment]
Can you be more specific about what exactly is slow? The full Appium log is required as well

**Comment by JayasriPV** [comment]
Whole execution like finding elements , clicking elements, scrolling everything

**Comment by JayasriPV** [comment]
I have attached appium logs while my script is executing:

https://gist.github.com/JayasriPV/4a7ca4cea7f86585e8ac2ba840480a75.js

**Comment by mykola-mokhnach** [comment]
Do you have background animations in your app or anything else which prevents it to be in idle state?

**Comment by JayasriPV** [comment]
No background animation in my app, the app contains google map mainly and some images of the product which is in a different page, its a very simple app

**Comment by mykola-mokhnach** [comment]
In general such issues are directly related to UIA2 framework itself and there is not much to do on Appium side. What yo could try is to play with `waitForIdleTimeout` setting as described in https://github.com/appium/appium-uiautomator2-server/issues/283 or switch the automation backend to Espresso.

**Comment by JayasriPV** [comment]
i tried by adding the settings waitforIdleTimeout as 0 but still didnt worked, how can i change the automation backend to espresso

**Comment by mykola-mokhnach** [comment]
https://www.google.com/search?q=automation+backend+espresso+in+appium

**Comment by JayasriPV** [comment]
i changed the automation name to Espresso in place of uiAutomator2 , but my app itself is not launching

**Comment by JayasriPV** [comment]
Is there any change need to be done from app side by developers

**Comment by mykola-mokhnach** [comment]
> i changed the automation name to Espresso in place of uiAutomator2 , but my app itself is not launching, throwing null pointer exception while initialising pom objects

We cannot help nothing there without the detailed server log

> Is there any change need to be done from app side by developers

This requires further investigation. Perhaps, the logcat output could provide more details.

**Comment by JayasriPV** [comment]
Appium logs:
https://gist.github.com/JayasriPV/1afc8dbee12fe451c549a36e8128addb.js

Logcat logs:
https://gist.github.com/JayasriPV/50cd3fe01904f28fef595abe6b1446fc.js

**Comment by mykola-mokhnach** [comment]
> [debug] [MJSONWP] Encountered internal error running command: Error: java.lang.SecurityException: Permission Denial: starting instrumentation ComponentInfo{io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner} from pid=9413, uid=9413 not allowed because package io.appium.espressoserver.test does not have a signature matching the target com.xome.android.nightly

This exception is expected. The application under test must be signed with the same key as the espresso server, which cannot happen if `noReset` is set to true.

**Comment by mykola-mokhnach** [comment]
> 08-19 17:57:44.101  1954  1982 W ActivityTaskManager: Launch timeout has expired, giving up wake lock!

Regarding the logcat I've found this so far: https://stackoverflow.com/questions/10031624/launch-timeout-has-expired-giving-up-wake-lock-activity-idle-timeout-for-histo
Perhaps, it's something that has to be checked with devs and which could potentially prevent the idle state.

**Comment by JayasriPV** [comment]
> noReset

i have not kept noReset capabilities set to any value

**Comment by JayasriPV** [comment]
> > 08-19 17:57:44.101  1954  1982 W ActivityTaskManager: Launch timeout has expired, giving up wake lock!
> 
> Regarding the logcat I've found this so far: https://stackoverflow.com/questions/10031624/launch-timeout-has-expired-giving-up-wake-lock-activity-idle-timeout-for-histo
> Perhaps, it's something that has to be checked with devs and which could potentially prevent the idle state.

this happens only when i run with Espresso as automation name

**Comment by mykola-mokhnach** [comment]
> [Appium]   noReset: true

I only say what I observe in the attached log. If this log is not the correct one then please provide the right one

**Comment by JayasriPV** [comment]
This is the right one but what i am saying is i had not set any capability as noReset, if i set that to false will it work

**Comment by mykola-mokhnach** [comment]
It will work if both apps have the same signature. Espresso signs both packages automatically if `app` capability is provided

**Comment by mykola-mokhnach** [comment]
This is rather an issue of the framework or the application itself and there is nothing more to do on Appium side. Closed as third party issue.

**Comment by JayasriPV** [comment]
Hi, i added the app key capabilities  to use with framework Espresso and tried starting the server but i am unable to start the server itself.Please find the attached log

**Comment by JayasriPV** [comment]
https://gist.github.com/JayasriPV/9cf34c7f6c31dc6da83c559c202d7836.js

Kindly look into it and assist

**Comment by mykola-mokhnach** [comment]
The log states grid registration error because of syntax error in the config file. It has nothing to do with the problem above

**Comment by JayasriPV** [comment]
but i have validated my config file which is json, it shows no error

**Comment by JayasriPV** [comment]
Hi, Thanks for your response, i resolved the above issue by adding the caps in the java code, and now the app is launching but i am getting the below error in java while creating session:

org.openqa.selenium.SessionNotCreatedException: A new session could not be created. Details: io.appium.espressoserver.lib.handlers.exceptions.SessionNotCreatedException: java.lang.RuntimeException: Could not launch intent Intent { act=android.intent.action.MAIN flg=0x14000000 cmp=com.xome.android.nightly/com.xome.android.home.HomeActivity } within 45 seconds. Perhaps the main thread has not gone idle within a reasonable amount of time? There could be an animation or something constantly repainting the screen. Or the activity is doing network calls on creation? See the threaddump logs. For your reference the last time the event queue was idle before your activity launch request was 1566805788903 and now the last time the queue went idle was: 1566805789997. If these numbers are the same your activity might be hogging the event queue.
	at io.appium.espressoserver.lib.handlers.CreateSession.handle(CreateSession.kt:37)
	at io.appium.espressoserver.lib.handlers.CreateSession.handle(CreateSession.kt:26)
	at io.appium.espressoserver.lib.http.Router.route(Router.java:336)
	at io.appium.espressoserver.lib.http.Server.serve(Server.java:69)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.RuntimeException: Could not launch intent Intent { act=android.intent.action.MAIN flg=0x14000000 cmp=com.xome.android.nightly/com.xome.android.home.HomeActivity } within 45 seconds. Perhaps the main thread has not gone idle within a reasonable amount of time? There could be an animation or something constantly repainting the screen. Or the activity is doing network calls on creation? See the threaddump logs. For your reference the last time the event queue was idle before your activity launch request was 1566805788903 and now the last time the queue went idle was: 1566805789997. If these numbers are the same your activity might be hogging the event queue.
	at androidx.test.runner.MonitoringInstrumentation.startActivitySync(MonitoringInstrumentation.java:453)
	at io.appium.espressoserver.lib.helpers.ActivityHelper.startActivity(ActivityHelper.java:89)
	at io.appium.espressoserver.lib.handlers.CreateSession.handle(CreateSession.kt:34)
	... 6 more

**Comment by mykola-mokhnach** [comment]
The error message is pretty clear. I have nothing more to add

**Comment by JayasriPV** [comment]
HI, please let me know how to resolve the above issue.
