### ISSUE TITLE
Unable To Find the PID in Web View on real devices but working fine With Emulator

### ISSUE THREAD

**Issue by tahirakhlaaq** [appium/appium#13093]
## The problem

I'm trying to perform the actions on webview in android Hybrid app which is built on React native. The same thing working with an emulator but when I'm running it on a real device. Appium is unable to find out the PID.

 Getting Below Error:

**An unknown server-side error occurred while processing the command. Original error: Failed to start Chromedriver session: An unknown server-side error occurred while processing the command. Original error: unknown error: Failed to get PID for the following process: com.traveltriangle.traveller
  (process name must be specified if not equal to package name)**

## Environment

* Appium version that exhibits the issue:  Appium v1.14.0, Appium v1.13.0 and Appium v1.12.1.
* Last Appium version that did not exhibit the issue (if applicable): Appium v1.14.0
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): 10.6
* Npm or Yarn package manager: 6.9
* Mobile platform/version under test: 9
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Both
* APPIUM CHROME DRIVER: LATEST
## Details

On Emulator Its working.On real device giving an Error.
An unknown server-side error occurred while processing the command. Original error: Failed to start Chromedriver session: An unknown server-side error occurred while processing the command. Original error: unknown error: Failed to get PID for the following process: com.traveltriangle.traveller
  (process name must be specified if not equal to package name)

## Link to Appium logs

[https://gist.github.com/tahirakhlaaq/53de659cb5fe89889ab9dec7432c135c](url)

## APK Link
[https://drive.google.com/open?id=1q1UmVID_m89R8B04Pbk03WeaFBO_UXSV](url)
## Code To Reproduce Issue [ Good To Have ]

```
@BeforeMethod
	public void androidCapabilities() throws MalformedURLException {
		File f = new File("src");
		File fs = new File(f, "app-locators.apk");
		DesiredCapabilities cap = new DesiredCapabilities();
		cap.setCapability("automationName", "uiAutomator2");
		cap.setCapability("platformName", "Android");
		cap.setCapability("platformVersion", "9");
		cap.setCapability("deviceName", "OPPO F11 Pro");
		cap.setCapability("appPackage", "com.traveltriangle.traveller");
		cap.setCapability("appActivity", "com.traveltriangle.traveller.MainActivity");
		cap.setCapability("noReset", true);
		String baseURL = "http://0.0.0.0:";
		String minorURL = "/wd/hub";
		String port = "4723";
		driver = new AndroidDriver<AndroidElement>(new URL(baseURL + port + minorURL), cap);
		
	@Test
	public void launch() throws InterruptedException, MalformedURLException {
		WebDriverWait wait = new WebDriverWait(driver, 10);

		Thread.sleep(4000);
	  waitForElementPresent((MobileBy.
		  AccessibilityId("ChatBotView_5343_5_FormButton_903_2, ")), 30);
		  driver.findElement((MobileBy.
		  AccessibilityId("ChatBotView_5343_5_FormButton_903_2, "))).click();
            //    driver.findElement(MobileBy.AccessibilityId("CustomFAB_470_2")).click();
		Thread.sleep(4000);
		Set<String> contextNames = driver.getContextHandles();
		for (String contextName : contextNames) {
			System.out.println(contextName);
			driver.context(contextName);
			if (contextName.contains("WEBVIEW")) {
				driver.context(contextName);
			}
		}
		// System.out.println(driver.getPageSource());
		waitForElementPresent(By.xpath("(//a[@class='rsc-os-option-element sc-bxivhb PUXvG'])[1]"), 30);
		driver.findElement(By.xpath("(//a[@class='rsc-os-option-element sc-bxivhb PUXvG'])[1]")).click();
		waitForElementPresent(By.xpath("(//a[@class='rsc-os-option-element sc-bxivhb PUXvG'])[1]"), 30);
		driver.findElement(By.xpath("(//a[@class='rsc-os-option-element sc-bxivhb PUXvG'])[1]")).click();
		waitForElementPresent(By.xpath("//input[@placeholder='Type your destination...']"), 30);
		driver.findElement(By.xpath("//input[@placeholder='Type your destination...']")).sendKeys("cool");

	}

	public static void waitForElementPresent(final By by, int timeOutInSeconds) {
		WebDriverWait wait = new WebDriverWait(driver, timeOutInSeconds);

		wait.until(new ExpectedCondition<Boolean>() {

			public Boolean apply(WebDriver d) {
				// TODO Auto-generated method stub
				return d.findElement(by).isDisplayed();
			}
		});
	}
	}
```

@mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
Can you list the web view using IWDP console and/or list it using Safari remote debugger?

**Comment by tahirakhlaaq** [comment]
@mykola-mokhnach I'm doing it for the Android and using the chrome

**Comment by mykola-mokhnach** [comment]
I thought it's iOS. then just try the same, but using Chrome remote debugger

**Comment by tahirakhlaaq** [comment]
I already have tried with the Chrome remote debugger but not able to inspect the webview in App.
You can check it I have given the APK link. 
After installation, you can open webview by clicking on Message Icon in the bottom of the screen above notification Tab.

**Comment by mykola-mokhnach** [comment]
If the web view is not visible in Chrome then there is no way to get it visible in Appium. Make sure it is configured properly and is debuggable.

**Comment by tahirakhlaaq** [comment]
@mykola-mokhnach by doing below step, 
WebView debugging should be enabled; developer must enable ‘setWebContentsDebuggingEnabled’ flag in the WebView class. This flag enables debugging of web contents (HTML / CSS / JavaScript) loaded into any WebViews of app.

But now I'm facing the **Failed to start Chromedriver session, Original error: unknown error: Failed to get PID for the following process”**
Please refer to the log, I'm Not Getting any solution now.

[https://gist.github.com/tahirakhlaaq/53de659cb5fe89889ab9dec7432c135c](url)

I also trier this [https://stackoverflow.com/questions/52429593/appium-getting-error-failed-to-start-chromedriver-session-original-error-unk/57554779#57554779](url) but did not get the luck..
Please help with this.

**Comment by tahirakhlaaq** [comment]
@mykola-mokhnach UPDATED The description to reproduce the problem.
@jlipps @Jonahss any suggestion on this???

**Comment by mykola-mokhnach** [comment]
>  is this an issue or configuration problem?

Sorry, but I don't know

**Comment by imurchie** [comment]
To see what, if anything, Chromedriver is doing, you can add the `showChromedriverLog` desired capability (set to `true`). the logs will be inlined into the Appium server logs.

**Comment by tahirakhlaaq** [comment]
Here is the chrome driver Log. @mykola-mokhnach @imurchie 
[https://gist.github.com/tahirakhlaaq/d5ca35ee0be6902f6ac764677a0ecd9d](url)

[appiumServer-ChromeDriver-logs.txt](https://github.com/appium/appium/files/3532933/appiumServer-ChromeDriver-logs.txt)

**Comment by imurchie** [comment]
No idea why it's not finding the PID, which seems to be there.

You could try a more recent version of Chromedriver (you can set the `chromedriverDisableBuildCheck` capability to get around errors in compatibility).

**Comment by tahirakhlaaq** [comment]
Tried with the latest Chromedriver getting the same Logs. The issue still Exists I reinstall all the system.

**Comment by tahirakhlaaq** [comment]
any update here ?

**Comment by mykola-mokhnach** [comment]
I think this is an issue of chrome driver. They have GetPidByName method there, which expects the `ps` output to have either 8 or 9 columns while on your device under test there are 10 columns: https://source.chromium.org/chromium/chromium/src/+/master:chrome/test/chromedriver/chrome/adb_impl.cc;bpv=1;bpt=1;l=245?q=%22Failed%20to%20get%20PID%20for%20the%20following%20process%22&ss=chromium&originalUrl=https:%2F%2Fcs.chromium.org%2F

Consider reporting the issue to the Chromedriver bugtracker.

**Comment by mykola-mokhnach** [comment]
It also confirms the fact that the most of the devices running customized firmwares, that are too different from the stock Android OS (e.g. MiUI), are not good for automated testing.

**Comment by tahirakhlaaq** [comment]
> I think this is an issue of chrome driver. They have GetPidByName method there, which expects the `ps` output to have either 8 or 9 columns while on your device under test there are 10 columns: https://source.chromium.org/chromium/chromium/src/+/master:chrome/test/chromedriver/chrome/adb_impl.cc;bpv=1;bpt=1;l=245?q=%22Failed%20to%20get%20PID%20for%20the%20following%20process%22&ss=chromium&originalUrl=https:%2F%2Fcs.chromium.org%2F
> 
> Consider reporting the issue to the Chromedriver bugtracker.

Okay !! let me try with stock android devices. Thanks for the info!!

**Comment by mykola-mokhnach** [comment]
Closed because of no response
