### ISSUE TITLE
Unable to switchTo().window(...) in Android Chrome

### ISSUE THREAD

**Issue by sljosep** [appium/appium#13106]
## The problem

Switching to a different browser tab isn't working for mobile Chrome browser. 

## Environment

* Appium 1.14.1, also 1.13.0
* MacOS Mojave 10.14.6
* Chrome 76 (chromeDriver76)
* Real device (pixel2)

## Details

I'm opening a website and clicking on a link that will open a second tab in the Mobile Chrome browser. Then I use the code I attached here to go back to the original tab, but it's not working. In the Appium logs I saw this message:

"message":"invalid argument: 'name' must be a string\n  (Session info: chrome=76.0.3809.111)\n  (Driver info: chromedriver=76.0.3809.126 (d80a294506b4c9d18015e755cee48f953ddc3f2f-refs/branch-heads/3809@{#1024}),platform=Mac OS X 10.14.6 x86_64)"

I could find two recent related issues:
https://github.com/appium/appium/issues/13062
which was closed because it was supposed to be solved in the second issue:
https://github.com/appium/appium/issues/12989

That issue was solved by the new Appium version 1.14.1, but I'm not seeing the window switch.

## Link to Appium logs

https://gist.github.com/sljosep/914d5ab85c879473d8b1b23fa200ab8c

## Code To Reproduce Issue [ Good To Have ]

driver.get("https://mariacasino.com");
driver.findElement(By.xpath("//a[@href='https://www.kindredaffiliates.com/']")).click();

ArrayList<String> tabs = new ArrayList<String>(driver.getWindowHandles());
System.out.println(tabs); //shows two tabs
System.out.println("Switching to "+tabs.get(0));
driver.switchTo().window(tabs.get(0));

**Comment by sljosep** [comment]
@mykola-mokhnach Does this include the fix? https://github.com/appium/appium/releases/tag/v1.14.2

The issue persists using this version:
https://gist.github.com/sljosep/c320dddc4a76d089e9e7980793f4498d

**Comment by mykola-mokhnach** [comment]
No, 1.14.2 is the copy of 1.14.1 with just one hot fix for shrinkwrap

**Comment by sljosep** [comment]
Hey sorry about that, find the logs for Appium@beta
https://gist.github.com/sljosep/756880994474c93569e6150deff9ee63

**Comment by sljosep** [comment]
Hey @mykola-mokhnach it actually works now. Thanks for your help!

**Comment by ishanm120** [comment]
I tested on Beta version v1.14.0-beta.2
and it worked successfully on Android.

But when i used the same appium version for iOS, it didn't work.
although its working on 1.14.0

**Comment by sljosep** [comment]
this issue is for chrome, you may wanna open a new issue for Safari, providing logs for successful/failing run on 1.14.0/beta

**Comment by ayazhamiya** [comment]
> > That issue was solved by the new Appium version 1.14.1, but I'm not seeing the window switch.
> 
> Appium 1.14.1 does not contain the mentioned fix. It's only present in appium@beta and will be released in approximately two weeks

@mykola-mokhnach Any update on when new version is going to be released ?

**Comment by ishanm120** [comment]
> this issue is for chrome, you may wanna open a new issue for Safari, providing logs for successful/failing run on 1.14.0/beta

New issue created
https://github.com/appium/appium/issues/13263
