### ISSUE TITLE
Error Domain=com.facebook.WebDriverAgent Code=1 "Keyboard is not present" while sending keys into scrolling element

### ISSUE THREAD

**Issue by DmitriyKapeliukh** [appium/appium#13108]
## The problem

I've got an exception Error Domain=com.facebook.WebDriverAgent Code=1 "Keyboard is not present" while I'm sending keys into select date scrolling element, but other text fields in my app respond normally.

## Environment

* Appium version 1.13
* Desktop OS/version used to run Appium: Mac OS 10.14.6
* Node.js version (unless using Appium.app|exe): 11.11.0
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: IOS 10.2
* Real device or emulator/simulator: Simulator

## Details

`The following error occurred: An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "Keyboard is not present" UserInfo={NSLocalizedDescription=Keyboard is not present}`

Stacktrace:

```
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:231)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at io.appium.java_client.DefaultGenericMobileElement.execute(DefaultGenericMobileElement.java:45)
	at io.appium.java_client.MobileElement.execute(MobileElement.java:1)
	at io.appium.java_client.ios.IOSElement.execute(IOSElement.java:1)
```
<img width="374" alt="Screen Shot 2019-08-22 at 4 20 26 PM" src="https://user-images.githubusercontent.com/12435225/63518039-d8381b80-c4f8-11e9-9ec7-a325441baaa8.png">

**Appium Logs** attached
[appium-server-logs.txt](https://github.com/appium/appium/files/3530334/appium-server-logs.txt)

**Comment by DmitriyKapeliukh** [comment]
<img width="374" alt="Screen Shot 2019-08-22 at 4 20 26 PM" src="https://user-images.githubusercontent.com/12435225/63518011-c787a580-c4f8-11e9-9cbe-07b4d84284b7.png">

**Comment by mykola-mokhnach** [comment]
Please provide the full server log

**Comment by DmitriyKapeliukh** [comment]
> Please provide the full server log

Attached

**Comment by mykola-mokhnach** [comment]
> [info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/bb3c9129-aca3-4777-9b26-d8d7fecfc320/element/880A0000-0000-0000-0506-010000000000/clear[39m
> [info] [35m[HTTP][39m [90m{"id":"880A0000-0000-0000-0506-010000000000"}[39m
> [debug] [35m[W3C (bb3c9129)][39m Calling AppiumDriver.clear() with args: ["880A0000-0000-0000-0506-010000000000","bb3c9129-aca3-4777-9b26-d8d7fecfc320"]
> [debug] [35m[XCUITest][39m Executing command 'clear'
> [debug] [35m[WD Proxy][39m Matched '/element/880A0000-0000-0000-0506-010000000000/clear' to command name 'clear'
> [debug] [35m[WD Proxy][39m Proxying [POST /element/880A0000-0000-0000-0506-010000000000/clear] to [POST http://localhost:8100/session/695F23BC-B95B-403F-96B9-73DC434FC1B6/element/880A0000-0000-0000-0506-010000000000/clear] with no body[debug] [35m[WD Proxy][39m Got response with status 200: "{\n  \"value\" : \"Error Domain=com.facebook.WebDriverAgent Code=1 \\\"Keyboard is not present\\\" UserInfo={NSLocalizedDescription=Keyboard is not present}\",\n  \"sessionId\" : \"695F23BC-B95B-403F-96B9-73DC434FC1B6\",\n  \"status\" : 13\n}"
> [debug] [35m[MJSONWP][39m Matched JSONWP error code 13 to UnknownError

The log says the error happens after `/clear` command is sent. Are you trying to clear the picker wheel?

**Comment by DmitriyKapeliukh** [comment]
Oh, yes. Removed clear(), working fine.
Thanks!
