### ISSUE TITLE
WebDriverAgentRunner not working with Appium Desktop v1.13 but with Appium Server v.1.14.2

### ISSUE THREAD

**Issue by naydn** [appium/appium#13109]
## Description

Hi! I am facing an issue where I can not start my tests with appium desktop but with appium server they are running properly. The log says that there is a signing problem with the WebDriverAgentRunner, but I fixed everything and then it worked from console with Appium v1.14.2 but not for Appium Desktop v1.13. I want to use the inspector session of Appium but I do not have a clue how I solve this problem. Might be a bug?

## Environment

* Appium server version or git revision if you use some shapshot: v1.14.2 
* Desktop OS/version used to run Appium if necessary: v1.13
* Mobile platform/version under test: iOS 12.4
* Real device or emulator/simulator: Real Device (iPhone 8)
* XCode version: 10.3

## Link to Appium logs

https://gist.github.com/naydn/70884b838321c25c5dcfaf2b4bf05863

**Comment by mykola-mokhnach** [comment]
Appium desktop uses its own packages deployment (located in Resources folder) unless you select to connect to the session, which is being executed by CLI version of the software.

**Comment by naydn** [comment]
Thanks for the answer.
How can I connect to the session of the CLI version?

**Comment by mykola-mokhnach** [comment]
Please use Appium forum for questions

**Comment by naydn** [comment]
Okay, I already found a workaround to use Appium Inspector from Appium Desktop with Server running on CLI. I just startet the Desktop Server, clicked on Inspector, stopped the Desktop Server and started the Server with same credentials through CLI.
