### ISSUE TITLE
【Question】How to prevent the deleteSession method from closing the app?

### ISSUE THREAD

**Issue by dtboy1995** [appium/appium#13105]
## The problem
When call 
```
await driver.deleteSession()
```
The app is closed

How to prevent this from happening, or is there any other way to provide it? Any help is very grateful.

**Comment by mykola-mokhnach** [comment]
Please provide more details on the environment and the server log

**Comment by dtboy1995** [comment]
thanks for reply
first，this is not a bug，i just want to know how to keep app opened after call driver.deletesession
i am sure that the deletesession method will close this session’s app
or i am worry with writing the test script
some bootstrap code
const driver = wd.remote({some options})
do something
await driver.deletesession()

**Comment by mykola-mokhnach** [comment]
Appium supports up to 10 different platforms with different backends for each platform. There is no universal solution for all of them

**Comment by dtboy1995** [comment]
@mykola-mokhnach Thank you for your patience.
```js
{
  platformName: 'Android',
  automationName: 'UiAutomator2'
}
```

When executing `await client.deleteSession()`
The app that runs the test is forced to close.
I just want it to not close the app.
Is my understanding of this method wrong (I called deleteSession after running the test script)
Or what should I do?

thanks a lot

**Comment by mykola-mokhnach** [comment]
UiA2 has the `dontStopAppOnReset` capability. Set it to true and the app will not be stopped on session deletion

**Comment by dtboy1995** [comment]
@mykola-mokhnach thank you very much. i am so sorry about caseless to read doc

**Comment by dtboy1995** [comment]
@mykola-mokhnach i add the option to run test scripts
i found that start the test app keep runing...
but i just want to it after `deleteSession` to keep.
not always keeping...
it there any way to solve it? thanks

**Comment by mykola-mokhnach** [comment]
I would try the combination of

```
fullReset:true,
dontStopAppOnReset:true,
skipUninstall:true,
```

or 

```
uninstallOtherPackages: <myapppackage>
dontStopAppOnReset:true,
```
