### ISSUE TITLE
Cannot use APPIUM_SKIP_CHROMEDRIVER_INSTALL with appium + npm

### ISSUE THREAD

**Issue by Volune** [appium/appium#13100]
When installing appium with npm, appium is forcing dependency of `appium-chromedriver@4.11.0` which does not support `APPIUM_SKIP_CHROMEDRIVER_INSTALL`

This is caused by the bundled [npm-shrinkwrap.json](https://cdn.jsdelivr.net/npm/appium@1.14.1/npm-shrinkwrap.json)

Cannot be reproduced with yarn.

**Comment by mykola-mokhnach** [comment]
This is odd. appium@beta should not be shrinkwrapped, right @dpgraham ?

**Comment by dpgraham** [comment]
@mykola-mokhnach no it shouldn't be shrinkwrapped.

@Volune what happens when you run `appium --version` from the command line? Is it the beta?

**Comment by Volune** [comment]
Appium 1.14.1. I'm installing without argument, expecting latest.

(Why does it say beta in the shrinkwrap of 1.14.1 ?)

**Comment by mykola-mokhnach** [comment]
Closed as known issue
