### ISSUE TITLE
Appium@beta often get error:  Could not install app: 'Couldn't push all the files within the timeout 60000ms'

### ISSUE THREAD

**Issue by maggie5750** [appium/appium#13115]
## The problem
Often get error:  Could not install app: 'Couldn't push all the files within the timeout 60000ms'
## Environment

* Appium version (or git revision) that exhibits the issue: appium@beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: mac OS 10.14.4
* Node.js version (unless using Appium.app|exe): 10.13.0
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: IOS 13 beta8
* Real device or emulator/simulator: real device - iPhone SE
* Appium CLI or Appium.app|exe:

## Details

Could not install app: 'Couldn't push all the files within the timeout 60000ms'

## Link to Appium logs

An unknown server-side error occurred while processing the command. Original error: Could not install app: 'Couldn't push all the files within the timeout 60000ms'
    at getResponseForW3CError (/Users/xxx/.nvm/versions/node/v10.13.0/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:826:9)
    at asyncHandler (/Users/xxx/.nvm/versions/node/v10.13.0/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:368:37)

**Comment by mykola-mokhnach** [comment]
Try the most recent nodejs patch, which is 10.16

**Comment by maggie5750** [comment]
@mykola-mokhnach  I have tried node 10.16.3 and this issue still happens.
`An unknown server-side error occurred while processing the command. Original error: Could not install app: 'Couldn't push all the files within the timeout 60000ms'
15:53:12     at getResponseForW3CError (/Users/xxx/.nvm/versions/node/v10.16.3/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:826:9)
15:53:12     at asyncHandler (/Users/xxx/.nvm/versions/node/v10.16.3/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:368:37)`

**Comment by umutuzgur** [comment]
@maggie5750 Is it always happening or sometimes?

**Comment by maggie5750** [comment]
@umutuzgur Sometimes.

**Comment by umutuzgur** [comment]
@maggie5750 How big is the ipa and can you send us all full log? I wonder if there is another error somewhere

**Comment by maggie5750** [comment]
@umutuzgur The ipa about 255M.  The whole appium log is as below:https://gist.github.com/maggie5750/9cccf612a4a7cbc2667d4bde217e86fb.

**Comment by maggie5750** [comment]
@umutuzgur I found this issue happens on iPhone SE

**Comment by hellojanice** [comment]
@umutuzgur not only iPhone SE, There is one iPhone 7 which also has the same issue.

**Comment by umutuzgur** [comment]
I'm enhancing the logs to figure out how to handle this situation. We have parallel fast push to the phone at the moment and I don't want to make it serial without finding more clues

**Comment by umutuzgur** [comment]
I changed our implementation that we push the files serially. If you still encounter issues sometimes, it is Apples problem and there is nothing else we can do. Will close the issue since a remediation is pushed to appium@beta
