### ISSUE TITLE
[IOS real device]  DTDeviceKit: Could not start house arrest service for app identifier com.facebook.WebDriverAgentRunner.xctrunner [Error Domain=com.apple.dtdevicekit Code=-402653093 "Xcode encountered an error" UserInfo={NSLocalizedFailureReason=Too many instances of this service are already running.

### ISSUE THREAD

**Issue by maggie5750** [appium/appium#13116]
## The problem
NSLocalizedFailureReason=Too many instances of this service are already running.
How many instances is limited?

## Environment

- Appium version (or git revision) that exhibits the issue: appium@beta
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: mac OS 10.14.4
- Node.js version (unless using Appium.app|exe): 10.13.0
- Npm or Yarn package manager: 6.9.0
- Mobile platform/version under test: IOS 13 beta8
- Real device or emulator/simulator: real device
- Appium CLI or Appium.app|exe:

## Details

[IOS real device]  DTDeviceKit: Could not start house arrest service for app identifier com.facebook.WebDriverAgentRunner.xctrunner [Error Domain=com.apple.dtdevicekit Code=-402653093 "Xcode encountered an error" UserInfo={NSLocalizedFailureReason=Too many instances of this service are already running.
## Link to Appium logs

`org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
xcodebuild error message:

2019-08-24 16:46:01.902 xcodebuild[50064:5598162]  DTDeviceKit: Could not start house arrest service for app identifier com.facebook.WebDriverAgentRunner.xctrunner [Error Domain=com.apple.dtdevicekit Code=-402653093 "Xcode encountered an error" UserInfo={NSLocalizedFailureReason=Too many instances of this service are already running., com.apple.dtdevicekit.stacktrace=(
	0   DTDeviceKitBase                     0x00000001194772d7 DTDKCreateNSError + 109
	1   DTDeviceKitBase                     0x00000001194779d9 DTDK_AMDErrorToNSError + 792
	2   DTDeviceKitBase                     0x0000000119489057 __70-[DTDKRemoteDeviceConnection startHouseArrestServiceForAppIdentifier:]_block_invoke + 98
	3   DTDeviceKitBase                     0x00000001194880cb __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_3 + 22
	4   DTDeviceKitBase                     0x0000000119479d4f __DTDKExecuteInSession_block_invoke_2 + 35
	5   DTDeviceKitBase                     0x0000000119479183 __DTDKExecuteWithConnection_block_invoke_2 + 473
	6   DTDeviceKitBase                     0x0000000119478f81 __DTDKExecuteWithConnection_block_invoke + 106
	7   libdispatch.dylib                   0x00007fff786f363d _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x00007fff786ff129 _dispatch_lane_barrier_sync_invoke_and_complete + 60
	9   DVTFoundation                       0x0000000109845ac0 DVTDispatchBarrierSync + 208
	10  DVTFoundation                       0x000000010981cee8 -[DVTDispatchLock performLockedBlock:] + 64
	11  DTDeviceKitBase                     0x0000000119478e82 DTDKExecuteWithConnection + 226
	12  DTDeviceKitBase                     0x0000000119479bb9 DTDKExecuteInSession + 376
	13  DTDeviceKitBase                     0x0000000119488000 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_2 + 112
	14  DVTFoundation                       0x000000010984382a __DVT_CALLING_CLIENT_BLOCK__ + 7
	15  DVTFoundation                       0x0000000109844f02 __DVTDispatchAsync_block_invoke + 809
	16  libdispatch.dylib                   0x00007fff786f25f8 _dispatch_call_block_and_release + 12
	17  libdispatch.dylib                   0x00007fff786f363d _dispatch_client_callout + 8
	18  libdispatch.dylib                   0x00007fff786f98e0 _dispatch_lane_serial_drain + 602
	19  libdispatch.dylib                   0x00007fff786fa396 _dispatch_lane_invoke + 385
	20  libdispatch.dylib                   0x00007fff787026ed _dispatch_workloop_worker_thread + 598
	21  libsystem_pthread.dylib             0x00007fff78933611 _pthread_wqthread + 421
	22  libsystem_pthread.dylib             0x00007fff789333fd start_wqthread + 13
), DVTRadarComponentKey=487927, NSLocalizedDescription=Xcode encountered an error}]
2019-08-24 16:46:01.902 xcodebuild[50064:5598210]  iPhoneConnect: ��<DVTiOSDevice (xxx), iPhone 8, iPhone, 13.0 (17A5572a), xxx> error uploading test configuration to app container: Error Domain=com.apple.dtdevicekit Code=-402653093 "Xcode encountered an error" UserInfo={NSLocalizedFailureReason=Too many instances of this service are already running., com.apple.dtdevicekit.stacktrace=(
	0   DTDeviceKitBase                     0x00000001194772d7 DTDKCreateNSError + 109
	1   DTDeviceKitBase                     0x00000001194779d9 DTDK_AMDErrorToNSError + 792
	2   DTDeviceKitBase                     0x0000000119489057 __70-[DTDKRemoteDeviceConnection startHouseArrestServiceForAppIdentifier:]_block_invoke + 98
	3   DTDeviceKitBase                     0x00000001194880cb __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_3 + 22
	4   DTDeviceKitBase                     0x0000000119479d4f __DTDKExecuteInSession_block_invoke_2 + 35
	5   DTDeviceKitBase                     0x0000000119479183 __DTDKExecuteWithConnection_block_invoke_2 + 473
	6   DTDeviceKitBase                     0x0000000119478f81 __DTDKExecuteWithConnection_block_invoke + 106
	7   libdispatch.dylib                   0x00007fff786f363d _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x00007fff786ff129 _dispatch_lane_barrier_sync_invoke_and_complete + 60
	9   DVTFoundation                       0x0000000109845ac0 DVTDispatchBarrierSync + 208
	10  DVTFoundation                       0x000000010981cee8 -[DVTDispatchLock performLockedBlock:] + 64
	11  DTDeviceKitBase                     0x0000000119478e82 DTDKExecuteWithConnection + 226
	12  DTDeviceKitBase                     0x0000000119479bb9 DTDKExecuteInSession + 376
	13  DTDeviceKitBase                     0x0000000119488000 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_2 + 112
	14  DVTFoundation                       0x000000010984382a __DVT_CALLING_CLIENT_BLOCK__ + 7
	15  DVTFoundation                       0x0000000109844f02 __DVTDispatchAsync_block_invoke + 809
	16  libdispatch.dylib                   0x00007fff786f25f8 _dispatch_call_block_and_release + 12
	17  libdispatch.dylib                   0x00007fff786f363d _dispatch_client_callout + 8
	18  libdispatch.dylib                   0x00007fff786f98e0 _dispatch_lane_serial_drain + 602
	19  libdispatch.dylib                   0x00007fff786fa396 _dispatch_lane_invoke + 385
	20  libdispatch.dylib                   0x00007fff787026ed _dispatch_workloop_worker_thread + 598
	21  libsystem_pthread.dylib             0x00007fff78933611 _pthread_wqthread + 421
	22  libsystem_pthread.dylib             0x00007fff789333fd start_wqthread + 13
), DVTRadarComponentKey=487927, NSLocalizedDescription=Xcode encountered an error}
*** If you believe this error represents a bug, please attach the result bundle at /Users/xxx/Library/Developer/Xcode/DerivedData/WebDriverAgent-eeioctgiyfrjruajppfnydegonlw/Logs/Test/Test-WebDriverAgentRunner-2019.08.24_16-45-58-+0800.xcresult
2019-08-24 16:46:01.909 xcodebuild[50064:5598159] [MT] IDETestOperationsObserverDebug: 3.736 elapsed -- Testing started completed.
2019-08-24 16:46:01.909 xcodebuild[50064:5598159] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2019-08-24 16:46:01.909 xcodebuild[50064:5598159] [MT] IDETestOperationsObserverDebug: 3.736 sec, +3.736 sec -- end
2019-08-24 16:46:01.910 xcodebuild[50064:5598159] Error Domain=com.apple.dtdevicekit Code=-402653093 "Xcode encountered an error" UserInfo={NSLocalizedFailureReason=Too many instances of this service are already running., com.apple.dtdevicekit.stacktrace=(
	0   DTDeviceKitBase                     0x00000001194772d7 DTDKCreateNSError + 109
	1   DTDeviceKitBase                     0x00000001194779d9 DTDK_AMDErrorToNSError + 792
	2   DTDeviceKitBase                     0x0000000119489057 __70-[DTDKRemoteDeviceConnection startHouseArrestServiceForAppIdentifier:]_block_invoke + 98
	3   DTDeviceKitBase                     0x00000001194880cb __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_3 + 22
	4   DTDeviceKitBase                     0x0000000119479d4f __DTDKExecuteInSession_block_invoke_2 + 35
	5   DTDeviceKitBase                     0x0000000119479183 __DTDKExecuteWithConnection_block_invoke_2 + 473
	6   DTDeviceKitBase                     0x0000000119478f81 __DTDKExecuteWithConnection_block_invoke + 106
	7   libdispatch.dylib                   0x00007fff786f363d _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x00007fff786ff129 _dispatch_lane_barrier_sync_invoke_and_complete + 60
	9   DVTFoundation                       0x0000000109845ac0 DVTDispatchBarrierSync + 208
	10  DVTFoundation                       0x000000010981cee8 -[DVTDispatchLock performLockedBlock:] + 64
	11  DTDeviceKitBase                     0x0000000119478e82 DTDKExecuteWithConnection + 226
	12  DTDeviceKitBase                     0x0000000119479bb9 DTDKExecuteInSession + 376
	13  DTDeviceKitBase                     0x0000000119488000 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_2 + 112
	14  DVTFoundation                       0x000000010984382a __DVT_CALLING_CLIENT_BLOCK__ + 7
	15  DVTFoundation                       0x0000000109844f02 __DVTDispatchAsync_block_invoke + 809
	16  libdispatch.dylib                   0x00007fff786f25f8 _dispatch_call_block_and_release + 12
	17  libdispatch.dylib                   0x00007fff786f363d _dispatch_client_callout + 8
	18  libdispatch.dylib                   0x00007fff786f98e0 _dispatch_lane_serial_drain + 602
	19  libdispatch.dylib                   0x00007fff786fa396 _dispatch_lane_invoke + 385
	20  libdispatch.dylib                   0x00007fff787026ed _dispatch_workloop_worker_thread + 598
	21  libsystem_pthread.dylib             0x00007fff78933611 _pthread_wqthread + 421
	22  libsystem_pthread.dylib             0x00007fff789333fd start_wqthread + 13
), DVTRadarComponentKey=487927, NSLocalizedDescription=Xcode encountered an error}
Test session results, code coverage, and logs:
	/Users/xxx/Library/Developer/Xcode/DerivedData/WebDriverAgent-eeioctgiyfrjruajppfnydegonlw/Logs/Test/Test-WebDriverAgentRunner-2019.08.24_16-45-58-+0800.xcresult
Testing failed:
	WebDriverAgentRunner:
		WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: Xcode encountered an error. Too many instances of this service are already running.))
** TEST EXECUTE FAILED **
Testing started on 'iPhone 8'. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
Build info: version: '4.0.0-alpha-1', revision: 'd1d3728cae', time: '2019-04-24T13:42:21'
System info: host: 'xxx', ip: 'xxx', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.4', java.version: '1.8.0_181'
Driver info: driver.version: IOSDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
xcodebuild error message:

2019-08-24 16:46:01.902 xcodebuild[50064:5598162]  DTDeviceKit: Could not start house arrest service for app identifier com.facebook.WebDriverAgentRunner.xctrunner [Error Domain=com.apple.dtdevicekit Code=-402653093 "Xcode encountered an error" UserInfo={NSLocalizedFailureReason=Too many instances of this service are already running., com.apple.dtdevicekit.stacktrace=(
	0   DTDeviceKitBase                     0x00000001194772d7 DTDKCreateNSError + 109
	1   DTDeviceKitBase                     0x00000001194779d9 DTDK_AMDErrorToNSError + 792
	2   DTDeviceKitBase                     0x0000000119489057 __70-[DTDKRemoteDeviceConnection startHouseArrestServiceForAppIdentifier:]_block_invoke + 98
	3   DTDeviceKitBase                     0x00000001194880cb __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_3 + 22
	4   DTDeviceKitBase                     0x0000000119479d4f __DTDKExecuteInSession_block_invoke_2 + 35
	5   DTDeviceKitBase                     0x0000000119479183 __DTDKExecuteWithConnection_block_invoke_2 + 473
	6   DTDeviceKitBase                     0x0000000119478f81 __DTDKExecuteWithConnection_block_invoke + 106
	7   libdispatch.dylib                   0x00007fff786f363d _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x00007fff786ff129 _dispatch_lane_barrier_sync_invoke_and_complete + 60
	9   DVTFoundation                       0x0000000109845ac0 DVTDispatchBarrierSync + 208
	10  DVTFoundation                       0x000000010981cee8 -[DVTDispatchLock performLockedBlock:] + 64
	11  DTDeviceKitBase                     0x0000000119478e82 DTDKExecuteWithConnection + 226
	12  DTDeviceKitBase                     0x0000000119479bb9 DTDKExecuteInSession + 376
	13  DTDeviceKitBase                     0x0000000119488000 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_2 + 112
	14  DVTFoundation                       0x000000010984382a __DVT_CALLING_CLIENT_BLOCK__ + 7
	15  DVTFoundation                       0x0000000109844f02 __DVTDispatchAsync_block_invoke + 809
	16  libdispatch.dylib                   0x00007fff786f25f8 _dispatch_call_block_and_release + 12
	17  libdispatch.dylib                   0x00007fff786f363d _dispatch_client_callout + 8
	18  libdispatch.dylib                   0x00007fff786f98e0 _dispatch_lane_serial_drain + 602
	19  libdispatch.dylib                   0x00007fff786fa396 _dispatch_lane_invoke + 385
	20  libdispatch.dylib                   0x00007fff787026ed _dispatch_workloop_worker_thread + 598
	21  libsystem_pthread.dylib             0x00007fff78933611 _pthread_wqthread + 421
	22  libsystem_pthread.dylib             0x00007fff789333fd start_wqthread + 13
), DVTRadarComponentKey=487927, NSLocalizedDescription=Xcode encountered an error}]
2019-08-24 16:46:01.902 xcodebuild[50064:5598210]  iPhoneConnect: ��<DVTiOSDevice (xxx), iPhone 8, iPhone, 13.0 (17A5572a), xxx> error uploading test configuration to app container: Error Domain=com.apple.dtdevicekit Code=-402653093 "Xcode encountered an error" UserInfo={NSLocalizedFailureReason=Too many instances of this service are already running., com.apple.dtdevicekit.stacktrace=(
	0   DTDeviceKitBase                     0x00000001194772d7 DTDKCreateNSError + 109
	1   DTDeviceKitBase                     0x00000001194779d9 DTDK_AMDErrorToNSError + 792
	2   DTDeviceKitBase                     0x0000000119489057 __70-[DTDKRemoteDeviceConnection startHouseArrestServiceForAppIdentifier:]_block_invoke + 98
	3   DTDeviceKitBase                     0x00000001194880cb __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_3 + 22
	4   DTDeviceKitBase                     0x0000000119479d4f __DTDKExecuteInSession_block_invoke_2 + 35
	5   DTDeviceKitBase                     0x0000000119479183 __DTDKExecuteWithConnection_block_invoke_2 + 473
	6   DTDeviceKitBase                     0x0000000119478f81 __DTDKExecuteWithConnection_block_invoke + 106
	7   libdispatch.dylib                   0x00007fff786f363d _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x00007fff786ff129 _dispatch_lane_barrier_sync_invoke_and_complete + 60
	9   DVTFoundation                       0x0000000109845ac0 DVTDispatchBarrierSync + 208
	10  DVTFoundation                       0x000000010981cee8 -[DVTDispatchLock performLockedBlock:] + 64
	11  DTDeviceKitBase                     0x0000000119478e82 DTDKExecuteWithConnection + 226
	12  DTDeviceKitBase                     0x0000000119479bb9 DTDKExecuteInSession + 376
	13  DTDeviceKitBase                     0x0000000119488000 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_2 + 112
	14  DVTFoundation                       0x000000010984382a __DVT_CALLING_CLIENT_BLOCK__ + 7
	15  DVTFoundation                       0x0000000109844f02 __DVTDispatchAsync_block_invoke + 809
	16  libdispatch.dylib                   0x00007fff786f25f8 _dispatch_call_block_and_release + 12
	17  libdispatch.dylib                   0x00007fff786f363d _dispatch_client_callout + 8
	18  libdispatch.dylib                   0x00007fff786f98e0 _dispatch_lane_serial_drain + 602
	19  libdispatch.dylib                   0x00007fff786fa396 _dispatch_lane_invoke + 385
	20  libdispatch.dylib                   0x00007fff787026ed _dispatch_workloop_worker_thread + 598
	21  libsystem_pthread.dylib             0x00007fff78933611 _pthread_wqthread + 421
	22  libsystem_pthread.dylib             0x00007fff789333fd start_wqthread + 13
), DVTRadarComponentKey=487927, NSLocalizedDescription=Xcode encountered an error}
*** If you believe this error represents a bug, please attach the result bundle at /Users/xxx/Library/Developer/Xcode/DerivedData/WebDriverAgent-eeioctgiyfrjruajppfnydegonlw/Logs/Test/Test-WebDriverAgentRunner-2019.08.24_16-45-58-+0800.xcresult
2019-08-24 16:46:01.909 xcodebuild[50064:5598159] [MT] IDETestOperationsObserverDebug: 3.736 elapsed -- Testing started completed.
2019-08-24 16:46:01.909 xcodebuild[50064:5598159] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2019-08-24 16:46:01.909 xcodebuild[50064:5598159] [MT] IDETestOperationsObserverDebug: 3.736 sec, +3.736 sec -- end
2019-08-24 16:46:01.910 xcodebuild[50064:5598159] Error Domain=com.apple.dtdevicekit Code=-402653093 "Xcode encountered an error" UserInfo={NSLocalizedFailureReason=Too many instances of this service are already running., com.apple.dtdevicekit.stacktrace=(
	0   DTDeviceKitBase                     0x00000001194772d7 DTDKCreateNSError + 109
	1   DTDeviceKitBase                     0x00000001194779d9 DTDK_AMDErrorToNSError + 792
	2   DTDeviceKitBase                     0x0000000119489057 __70-[DTDKRemoteDeviceConnection startHouseArrestServiceForAppIdentifier:]_block_invoke + 98
	3   DTDeviceKitBase                     0x00000001194880cb __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_3 + 22
	4   DTDeviceKitBase                     0x0000000119479d4f __DTDKExecuteInSession_block_invoke_2 + 35
	5   DTDeviceKitBase                     0x0000000119479183 __DTDKExecuteWithConnection_block_invoke_2 + 473
	6   DTDeviceKitBase                     0x0000000119478f81 __DTDKExecuteWithConnection_block_invoke + 106
	7   libdispatch.dylib                   0x00007fff786f363d _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x00007fff786ff129 _dispatch_lane_barrier_sync_invoke_and_complete + 60
	9   DVTFoundation                       0x0000000109845ac0 DVTDispatchBarrierSync + 208
	10  DVTFoundation                       0x000000010981cee8 -[DVTDispatchLock performLockedBlock:] + 64
	11  DTDeviceKitBase                     0x0000000119478e82 DTDKExecuteWithConnection + 226
	12  DTDeviceKitBase                     0x0000000119479bb9 DTDKExecuteInSession + 376
	13  DTDeviceKitBase                     0x0000000119488000 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_2 + 112
	14  DVTFoundation                       0x000000010984382a __DVT_CALLING_CLIENT_BLOCK__ + 7
	15  DVTFoundation                       0x0000000109844f02 __DVTDispatchAsync_block_invoke + 809
	16  libdispatch.dylib                   0x00007fff786f25f8 _dispatch_call_block_and_release + 12
	17  libdispatch.dylib                   0x00007fff786f363d _dispatch_client_callout + 8
	18  libdispatch.dylib                   0x00007fff786f98e0 _dispatch_lane_serial_drain + 602
	19  libdispatch.dylib                   0x00007fff786fa396 _dispatch_lane_invoke + 385
	20  libdispatch.dylib                   0x00007fff787026ed _dispatch_workloop_worker_thread + 598
	21  libsystem_pthread.dylib             0x00007fff78933611 _pthread_wqthread + 421
	22  libsystem_pthread.dylib             0x00007fff789333fd start_wqthread + 13
), DVTRadarComponentKey=487927, NSLocalizedDescription=Xcode encountered an error}
Test session results, code coverage, and logs:
	/Users/xxx/Library/Developer/Xcode/DerivedData/WebDriverAgent-eeioctgiyfrjruajppfnydegonlw/Logs/Test/Test-WebDriverAgentRunner-2019.08.24_16-45-58-+0800.xcresult
Testing failed:
	WebDriverAgentRunner:
		WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: Xcode encountered an error. Too many instances of this service are already running.))
** TEST EXECUTE FAILED **
Testing started on 'iPhone 8'. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at getResponseForW3CError (/Users/xxx/.nvm/versions/node/v10.13.0/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:826:9)
    at asyncHandler (/Users/xxx/.nvm/versions/node/v10.13.0/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:368:37)
`

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Unfortunately this is an issue on Apple side that happens after multiple test executions and we cannot do nothing to resolve it. Rebooting the device usually helps

**Comment by nanoscopic** [comment]
I don't think this issue should be closed. If the thing that there are "too many instances of" is a process running on the IOS device, it should be possible to see and kill it.

**Comment by PHUITesting** [comment]
This is occurring for me before any test sessions have run, and rebooting the device does nothing.
