### ISSUE TITLE
Unable to find Android toast element with UIAutomator2

### ISSUE THREAD

**Issue by grafoxy** [appium/appium#13119]
## The problem

Unable to find Android toast element with UIAutomator2
I make following steps:
- generate toast
- print source()
- try to find toast (using xpath //*[@text=\"Please enter your login and password\"] )

Interesting point - I can see toast element in source() output or via Appium Inspector

## Environment

* Appium: 1.14.0
* Desktop OS: Windows
* Npm manager
* Real device:
* Appium CLI / Appium.exe

## Details
--

## Link to Appium logs
Appium logs - https://gist.github.com/grafoxy/84a5b4bba1294a8d680585f7a5f7facc
Source - https://gist.github.com/grafoxy/a6bddc3f09bda70d15ec3fc2e32df5a9

**Comment by grafoxy** [comment]
UPD: issue still present also with appium 1.14.2 (npm)

**Comment by mykola-mokhnach** [comment]
> 2019-08-25 09:22:23:769 [HTTP] --> POST /wd/hub/session/49d1d23a-f756-4b03-b6b5-789dd0da8e47/elements
> 2019-08-25 09:22:23:769 [HTTP] {"using":"xpath","value":"//*[@text=\"Please enter your login and password\"]"}
> 2019-08-25 09:22:23:771 [MJSONWP (49d1d23a)] Calling AppiumDriver.findElements() with args: ["xpath","//*[@text=\"Please enter your login and password\"]","49d1d23a-f756-4b03-b6b5-789dd0da8e47"]
> 2019-08-25 09:22:23:773 [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
> 2019-08-25 09:22:23:773 [BaseDriver] Waiting up to 0 ms for condition
> 2019-08-25 09:22:23:777 [WD Proxy] Matched '/elements' to command name 'findElements'
> 2019-08-25 09:22:23:780 [WD Proxy] Proxying [POST /elements] to [POST http://localhost:8200/wd/hub/session/a57a0b06-18af-4829-81b5-ab2eeaf1665c/elements] with body: {"strategy":"xpath","selector":"//*[@text=\"Please enter your login and password\"]","context":"","multiple":true}
> 2019-08-25 09:22:23:927 [WD Proxy] Got response with status 200: {"sessionId":"a57a0b06-18af-4829-81b5-ab2eeaf1665c","status":0,"value":[{"ELEMENT":"d3e524d0-aeb7-490c-baba-ededf819003a"}]}
> 2019-08-25 09:22:23:929 [MJSONWP (49d1d23a)] Responding to client with driver.findElements() result: [{"element-6066-11e4-a52e-4f735466cecf":"d3e524d0-aeb7-490c-baba-ededf819003a","ELEMENT":"d3e524d0-aeb7-490c-baba-ededf819003a"}]
> 2019-08-25 09:22:23:931 [HTTP] <-- POST /wd/hub/session/49d1d23a-f756-4b03-b6b5-789dd0da8e47/elements 200 162 ms - 201

I can observe that `findElements` does return the result, although the following `isDisplayed` call fails due to stale reference error. Perhaps, this makes sense if the toast is temporary

**Comment by mykola-mokhnach** [comment]
I'd say this is the expected behaviour:
https://github.com/appium/appium-uiautomator2-server/blob/853bae39cc74452ec0856e50f46e8d6d10ab11c3/app/src/main/java/io/appium/uiautomator2/utils/ElementHelpers.java#L225

**Comment by grafoxy** [comment]
@mykola-mokhnach could you provide advice, how I can validate (check) toast with UIAutomator2?

**Comment by mykola-mokhnach** [comment]
You could only validate it exists by finding it. No other operations are supposed to work

**Comment by grafoxy** [comment]
Thank you very much - getAttribute() resolve my issue.

`[HTTP] --> POST /wd/hub/session/e1669c9c-8f67-44df-a68f-4a42bf95aa6a/element
[HTTP] {"using":"xpath","value":"//*[@text=\"Please enter your login and password\"]"}
[MJSONWP (e1669c9c)] Calling AppiumDriver.findElement() with args: ["xpath","//*[@text=\"Please enter your login and password\"]","e1669c9c-8f67-44df-a68f-4a42bf95aa6a"]
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Waiting up to 0 ms for condition
[WD Proxy] Matched '/element' to command name 'findElement'
[WD Proxy] Proxying [POST /element] to [POST http://localhost:8200/wd/hub/session/c16b7379-dcae-4de5-92d5-54ec29ae9ad3/element] with body: {"strategy":"xpath","selector":"//*[@text=\"Please enter your login and password\"]","context":"","multiple":false}
[WD Proxy] Got response with status 200: {"sessionId":"c16b7379-dcae-4de5-92d5-54ec29ae9ad3","status":0,"value":{"ELEMENT":"3e3d7cbc-ae6e-465d-8dce-4faa576431a0"}}
[MJSONWP (e1669c9c)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"3e3d7cbc-ae6e-465d-8dce-4faa576431a0","ELEMENT":"3e3d7cbc-ae6e-465d-8dce-4faa576431a0"}
[HTTP] <-- POST /wd/hub/session/e1669c9c-8f67-44df-a68f-4a42bf95aa6a/element 200 390 ms - 199
[HTTP] 
[HTTP] --> GET /wd/hub/session/e1669c9c-8f67-44df-a68f-4a42bf95aa6a/element/3e3d7cbc-ae6e-465d-8dce-4faa576431a0/attribute/text
[HTTP] {}
[MJSONWP (e1669c9c)] Calling AppiumDriver.getAttribute() with args: ["text","3e3d7cbc-ae6e-465d-8dce-4faa576431a0","e1669c9c-8f67-44df-a68f-4a42bf95aa6a"]
[WD Proxy] Matched '/element/3e3d7cbc-ae6e-465d-8dce-4faa576431a0/attribute/text' to command name 'getAttribute'
[WD Proxy] Proxying [GET /element/3e3d7cbc-ae6e-465d-8dce-4faa576431a0/attribute/text] to [GET http://localhost:8200/wd/hub/session/c16b7379-dcae-4de5-92d5-54ec29ae9ad3/element/3e3d7cbc-ae6e-465d-8dce-4faa576431a0/attribute/text] with body: {}
[WD Proxy] Got response with status 200: "{\"sessionId\":\"c16b7379-dcae-4de5-92d5-54ec29ae9ad3\",\"status\":0,\"value\":\"Please enter your login and password\"}"
[MJSONWP (e1669c9c)] Responding to client with driver.getAttribute() result: "Please enter your login and password"
[HTTP] <-- GET /wd/hub/session/e1669c9c-8f67-44df-a68f-4a42bf95aa6a/element/3e3d7cbc-ae6e-465d-8dce-4faa576431a0/attribute/text 200 135 ms - 110`
