### ISSUE TITLE
Wakelock impedes the device to go to sleep or screensaver

### ISSUE THREAD

**Issue by rodrigomunoz** [appium/appium#13111]
With this change https://github.com/appium/appium-uiautomator2-server/commit/4985d5734443ae7df81808fc1b5af58e5971bb98 , UiAutomator2 always acquires a wakelock for the duration of the session.

See:
https://github.com/appium/appium-uiautomator2-server/blame/775366d15fa61dbc6a09e1e63d206c37772ddcd5/app/src/main/java/io/appium/uiautomator2/server/ServerInstrumentation.java#L83

On device, `adb shell dumpsys power`:
```
ake Locks: size=2
  PARTIAL_WAKE_LOCK              'PhoneWindowManager.mPowerKeyWakeLock' ACQ=-17m27s574ms LONG (uid=1000 pid=3583)
  SCREEN_DIM_WAKE_LOCK           'UiAutomator2:ScreenKeeper' ACQ=-25s647ms (uid=10164 pid=25995)
```

While this works for more test suites, it blocks the execution of test cases where I actually want the device to go to screensaver (Android TVs) or go to sleep.

This issue is a request to make the 'wake lock' configurable so that it can be disabled.

**Comment by mykola-mokhnach** [comment]
The feature has been published in appium@beta. Now it is possible to set the `wakeLockTimeout` setting. If the value of this setting is greater than zero then UIA2 server will try to acquire the wake lock to the given amount of milliseconds. Otherwise the current wake lock will be released.

**Comment by rodrigomunoz** [comment]
I have tested the new feature and it works like a charm. Thank you
