### ISSUE TITLE
Video from Screen Record can't be played (iOS Simulator)

### ISSUE THREAD

**Issue by malhussan** [appium/appium#13113]
## The problem

I am trying to record test execution on iOS Simulator using the "Start Recording Screen" and "Stop Recording Screen" features in Appium. I get the Base64 encoded video, decode it and save it as an mp4 video file. I have issues in video playback when:

1. Using QuickTime (playback works with VLC but with some flakiness; meaning sometimes I have to click on the video scrubber to start at different positions for it to work correctly)
2. Using html `<video>` tag (using the encoded Base64 data without decoding). Playback here does not work.

## Environment

* Appium version: 1.13.0
* Desktop OS/version used to run Appium: MacOS Mojave v10.14.4
* Node.js version: v11.10.1
* Npm: 6.7.0
* Mobile platform/version under test: iOS 11.4
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium CLI

**Comment by mykola-mokhnach** [comment]
The API allows to tune some video encoding options for ffmpeg, which is used under the hood. Your task is to find the combination of these options that works for your purposes. Please use Appium forum for questions.

**Comment by Junting-Liu** [comment]
i meet the same (issue)[https://github.com/webdriverio/webdriverio/issues/4410],  hi malhussan, have you fix it?  @malhussan
