### ISSUE TITLE
iOS install app on a remote real device failed

### ISSUE THREAD

**Issue by maggie5750** [appium/appium#13114]
## The problem

IOS install app on a remote real device failed

## Environment

* Appium version (or git revision) that exhibits the issue: appium@beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS 10.14.4
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: ios13 beta8
* Real device or emulator/simulator: Real Device (The IOS real device is on another computer and I remote connect to it.)
* Appium CLI or Appium.app|exe:

## Details
The IOS real device is on another computer and I remote connect to it.
Logs as below:
`Driver info: driver.version: IOSDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not install app: 'The "path" argument must be of type string. Received type undefined'
    at getResponseForW3CError (/Users/rcadmin/.nvm/versions/node/v10.8.0/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:826:9)
    at asyncHandler (/Users/rcadmin/.nvm/versions/node/v10.8.0/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:368:37)`

## Link to Appium logs
https://gist.github.com/maggie5750/06c6f8a74a83675cc759aa2dc6a2969f

**Comment by mykola-mokhnach** [comment]
Try to update NodeJS

**Comment by maggie5750** [comment]
Yes. NodeJS is too old. Updated and issue is resolved.

**Comment by umutuzgur** [comment]
Cool. I'm closing the issue then
