### ISSUE TITLE
Real iPad requires to be restarted daily

### ISSUE THREAD

**Issue by pmswatuser** [appium/appium#13110]
## The problem

Appium forces us to reboot the iPad real devices connected to the Mac, daily. Appium logs are attached for reference. This issue was noticed consecutively on 3 iPads. Everything works just fine after rebooting the iPad. Not deploying the WDA agent again.

## Environment

* Appium CLI 1.14.1
* Xcode 10.3
* iOS 12.2 and 12.4
* Mac Mojave

**Comment by pmswatuser** [comment]
Gist logs

https://gist.github.com/pmswatuser/12b4f90bee45849d9c9f454c10a74a51

**Comment by pmswatuser** [comment]
Exact error occurs for every iPad that has been running for over 20 hours. Reboot fixes the issue. No other change to the config. Any thoughts on this behavior?

**Comment by umutuzgur** [comment]
Hi @pmswatuser. It is common that the iOS devices become problematic after a certain amount time or certain amount of test executions. It is general a problem on iOS and there is not much Appium can do about it sadly

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
