### ISSUE TITLE
Specify Chrome Desired Capability: pageLoadStrategy

### ISSUE THREAD

**Issue by MarkSpencerTan** [appium/appium#13129]
## The problem

Is there a way to specify chrome desired capabilities with appium? More specifically the pageLoadStrategy Chrome Capability? I need to be able to set it to "eager" or "none" instead of "normal" so that loading the url won't be so strict for native browsers.

Thank you for the support

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.0
* Desktop OS/version used to run Appium: Windows 10
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Both

**Comment by KazuCocoa** [comment]
Did you set `pageLoadStrategy` in your desired capabilities?

It looks https://github.com/appium/appium-android-driver/search?utf8=%E2%9C%93&q=pageLoadStrategy&type= has it

**Comment by KazuCocoa** [comment]
according to https://chromedriver.storage.googleapis.com/index.html?path=77.0.3865.40/ , the eager strategy is available from chromedriver 77

I tried out on my local, then the parameter was certainly passed to Chromedriver.

```
[Chromedriver] Starting MJSONWP Chromedriver session with capabilities: {
[Chromedriver]   "desiredCapabilities": {
[Chromedriver]     "chromeOptions": {
[Chromedriver]       "androidPackage": "com.android.chrome",
[Chromedriver]       "args": [
[Chromedriver]         "--disable-fre",
[Chromedriver]         "--disable-popup-blocking"
[Chromedriver]       ],
[Chromedriver]       "androidDeviceSerial": "emulator-5554"
[Chromedriver]     },
[Chromedriver]     "pageLoadStrategy": "eager",
[Chromedriver]     "loggingPrefs": {
[Chromedriver]       "browser": "ALL"
[Chromedriver]     }
[Chromedriver]   }
[Chromedriver] }
```
