### ISSUE TITLE
Appium version more than 1.8.1 run very slow on my application

### ISSUE THREAD

**Issue by HoLeAnh** [appium/appium#13121]
## The problem

Appium version more than 1.8.1 run very slow on my application

## Environment

Appium 1.14.2
Emulator android 8.0
Window 10
Node version v10.16.0
Npm verion 6.9.0
Java client 7.0.0

## Details

 I used to run my app on android 4.4.4 + appium 1.8.1 + java client 5.0.1, every thing be slow but acceptable. When i update appium to more than version 1.8.1 and current is 1.14.2, Login page action very good but after that, every action very slow. 

## My code when i click a element

public void clickToElement(AndroidDriver driver, By by) {
	WebDriverWait wait = new WebDriverWait(driver, timeWait);
	wait.until(ExpectedConditions.elementToBeClickable(by)).click();
}

## Link to Appium logs

Appium log when click a element

[Appium] Appium v1.14.2 creating new AndroidUiautomator2Driver (v1.33.1) session
[Appium] Capabilities:
[Appium]   platform: ANDROID
[Appium]   platformName: android
[Appium]   appActivity: com.sendoseller.MasterActivity
[Appium]   appPackage: com.sendoseller
[Appium]   autoGrantPermissions: true
[Appium]   chromedriverExecutable: D:\Workspace\maven_appium/src/test/java/resources/chromedriver.exe
[Appium]   deviceName: 192.168.106.101:5555
[Appium]   nativeWebScreenshot: true
[Appium]   platformVersion: 4.4.4
[Appium]   udid: 192.168.106.101:5555
[Appium]   unicodeKeyboard: true
[debug] [BaseDriver] W3C capabilities {"alwaysMatch":{"appium:pla... and MJSONWP desired capabilities {"appActivity":"com.sendose... were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"appium:pla...
[BaseDriver] Capability 'unicodeKeyboard' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[BaseDriver]   platform
[BaseDriver] Session created with session id: d86f1dc8-7d35-4576-9672-0fcb9995b66b
[ADB] Found 3 'build-tools' folders under 'C:\Users\anhhl\AppData\Local\Android\Sdk' (newest first):
[ADB]     C:/Users/anhhl/AppData/Local/Android/Sdk/build-tools/28.0.3
[ADB]     C:/Users/anhhl/AppData/Local/Android/Sdk/build-tools/28.0.2
[ADB]     C:/Users/anhhl/AppData/Local/Android/Sdk/build-tools/27.0.3
[ADB] Using 'adb.exe' from 'C:\Users\anhhl\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[AndroidDriver] Using device: 192.168.106.101:5555
[ADB] Using 'adb.exe' from 'C:\Users\anhhl\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[debug] [ADB] Setting device id to 192.168.106.101:5555
[debug] [ADB] Running 'C:\Users\anhhl\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 192.168.106.101\:5555 shell getprop ro.build.version.sdk'
[debug] [ADB] Current device property 'ro.build.version.sdk': 26
[debug] [ADB] Device API level: 26
[AndroidDriver] No app sent in, not parsing package/activity
[debug] [ADB] Running 'C:\Users\anhhl\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 192.168.106.101\:5555 wait-for-device'
[debug] [ADB] Running 'C:\Users\anhhl\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 192.168.106.101\:5555 shell echo ping'
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Getting install status for io.appium.settings
[debug] [ADB] Running 'C:\Users\anhhl\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 192.168.106.101\:5555 shell dumpsys package io.appium.settings'
.
.
.
.

[HTTP] {"using":"id","value":"com.sendoseller:id/warningFake_btnOK"}
[debug] [W3C (4b2bdc1d)] Calling AppiumDriver.findElement() with args: ["id","com.sendoseller:id/warningFake_btnOK","4b2bdc1d-ac2b-4042-9132-f123d99ce3bf"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://localhost:8200/wd/hub/session/ea0b2e86-2bff-4d1f-aad6-e98b950f9f56/element] with body: {"strategy":"id","selector":"com.sendoseller:id/warningFake_btnOK","context":"","multiple":false}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"ea0b2e86-2bff-4d1f-aad6-e98b950f9f56","status":0,"value":{"ELEMENT":"9691f65f-d00b-4eea-9d8d-fe033f35eb05"}}
[debug] [W3C (4b2bdc1d)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"9691f65f-d00b-4eea-9d8d-fe033f35eb05","ELEMENT":"9691f65f-d00b-4eea-9d8d-fe033f35eb05"}
[HTTP] <-- POST /wd/hub/session/4b2bdc1d-ac2b-4042-9132-f123d99ce3bf/element 200 951 ms - 137
[HTTP]
[HTTP] --> GET /wd/hub/session/4b2bdc1d-ac2b-4042-9132-f123d99ce3bf/element/9691f65f-d00b-4eea-9d8d-fe033f35eb05/displayed
[HTTP] {}
[debug] [W3C (4b2bdc1d)] Calling AppiumDriver.elementDisplayed() with args: ["9691f65f-d00b-4eea-9d8d-fe033f35eb05","4b2bdc1d-ac2b-4042-9132-f123d99ce3bf"]
[debug] [WD Proxy] Matched '/element/9691f65f-d00b-4eea-9d8d-fe033f35eb05/attribute/displayed' to command name 'getAttribute'
[debug] [WD Proxy] Proxying [GET /element/9691f65f-d00b-4eea-9d8d-fe033f35eb05/attribute/displayed] to [GET http://localhost:8200/wd/hub/session/ea0b2e86-2bff-4d1f-aad6-e98b950f9f56/element/9691f65f-d00b-4eea-9d8d-fe033f35eb05/attribute/displayed] with body: {}
[debug] [WD Proxy] Got response with status 200: "{\"sessionId\":\"ea0b2e86-2bff-4d1f-aad6-e98b950f9f56\",\"status\":0,\"value\":\"true\"}"
[debug] [W3C (4b2bdc1d)] Responding to client with driver.elementDisplayed() result: true
[HTTP] <-- GET /wd/hub/session/4b2bdc1d-ac2b-4042-9132-f123d99ce3bf/element/9691f65f-d00b-4eea-9d8d-fe033f35eb05/displayed 200 89 ms - 14
[HTTP]
[HTTP] --> GET /wd/hub/session/4b2bdc1d-ac2b-4042-9132-f123d99ce3bf/element/9691f65f-d00b-4eea-9d8d-fe033f35eb05/enabled
[HTTP] {}
[debug] [W3C (4b2bdc1d)] Calling AppiumDriver.elementEnabled() with args: ["9691f65f-d00b-4eea-9d8d-fe033f35eb05","4b2bdc1d-ac2b-4042-9132-f123d99ce3bf"]
[debug] [WD Proxy] Matched '/element/9691f65f-d00b-4eea-9d8d-fe033f35eb05/attribute/enabled' to command name 'getAttribute'
[debug] [WD Proxy] Proxying [GET /element/9691f65f-d00b-4eea-9d8d-fe033f35eb05/attribute/enabled] to [GET http://localhost:8200/wd/hub/session/ea0b2e86-2bff-4d1f-aad6-e98b950f9f56/element/9691f65f-d00b-4eea-9d8d-fe033f35eb05/attribute/enabled] with body: {}
[debug] [WD Proxy] Got response with status 200: "{\"sessionId\":\"ea0b2e86-2bff-4d1f-aad6-e98b950f9f56\",\"status\":0,\"value\":\"true\"}"
[debug] [W3C (4b2bdc1d)] Responding to client with driver.elementEnabled() result: true
[HTTP] <-- GET /wd/hub/session/4b2bdc1d-ac2b-4042-9132-f123d99ce3bf/element/9691f65f-d00b-4eea-9d8d-fe033f35eb05/enabled 200 57 ms - 14
[HTTP]
[HTTP] --> POST /wd/hub/session/4b2bdc1d-ac2b-4042-9132-f123d99ce3bf/element/9691f65f-d00b-4eea-9d8d-fe033f35eb05/click
[HTTP] {"id":"9691f65f-d00b-4eea-9d8d-fe033f35eb05"}
[debug] [W3C (4b2bdc1d)] Calling AppiumDriver.click() with args: ["9691f65f-d00b-4eea-9d8d-fe033f35eb05","4b2bdc1d-ac2b-4042-9132-f123d99ce3bf"]
[debug] [WD Proxy] Matched '/element/9691f65f-d00b-4eea-9d8d-fe033f35eb05/click' to command name 'click'
[debug] [WD Proxy] Proxying [POST /element/9691f65f-d00b-4eea-9d8d-fe033f35eb05/click] to [POST http://localhost:8200/wd/hub/session/ea0b2e86-2bff-4d1f-aad6-e98b950f9f56/element/9691f65f-d00b-4eea-9d8d-fe033f35eb05/click] with body: {"element":"9691f65f-d00b-4eea-9d8d-fe033f35eb05"}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"ea0b2e86-2bff-4d1f-aad6-e98b950f9f56","status":0,"value":true}
[debug] [W3C (4b2bdc1d)] Responding to client with driver.click() result: true
[HTTP] <-- POST /wd/hub/session/4b2bdc1d-ac2b-4042-9132-f123d99ce3bf/element/9691f65f-d00b-4eea-9d8d-fe033f35eb05/click 200 62 ms - 14
[HTTP]
[HTTP] --> POST /wd/hub/session/4b2bdc1d-ac2b-4042-9132-f123d99ce3bf/element
[HTTP] {"using":"id","value":"com.sendoseller:id/btn_menu"}
[debug] [W3C (4b2bdc1d)] Calling AppiumDriver.findElement() with args: ["id","com.sendoseller:id/btn_menu","4b2bdc1d-ac2b-4042-9132-f123d99ce3bf"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://localhost:8200/wd/hub/session/ea0b2e86-2bff-4d1f-aad6-e98b950f9f56/element] with body: {"strategy":"id","selector":"com.sendoseller:id/btn_menu","context":"","multiple":false}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"ea0b2e86-2bff-4d1f-aad6-e98b950f9f56","status":0,"value":{"ELEMENT":"93ed0817-aa19-413b-9487-c22c557d54a4"}}
[debug] [W3C (4b2bdc1d)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"93ed0817-aa19-413b-9487-c22c557d54a4","ELEMENT":"93ed0817-aa19-413b-9487-c22c557d54a4"}
[HTTP] <-- POST /wd/hub/session/4b2bdc1d-ac2b-4042-9132-f123d99ce3bf/element 200 10135 ms - 137
[HTTP]
[HTTP] --> GET /wd/hub/session/4b2bdc1d-ac2b-4042-9132-f123d99ce3bf/element/93ed0817-aa19-413b-9487-c22c557d54a4/displayed
[HTTP] {}
[debug] [W3C (4b2bdc1d)] Calling AppiumDriver.elementDisplayed() with args: ["93ed0817-aa19-413b-9487-c22c557d54a4","4b2bdc1d-ac2b-4042-9132-f123d99ce3bf"]
[debug] [WD Proxy] Matched '/element/93ed0817-aa19-413b-9487-c22c557d54a4/attribute/displayed' to command name 'getAttribute'
[debug] [WD Proxy] Proxying [GET /element/93ed0817-aa19-413b-9487-c22c557d54a4/attribute/displayed] to [GET http://localhost:8200/wd/hub/session/ea0b2e86-2bff-4d1f-aad6-e98b950f9f56/element/93ed0817-aa19-413b-9487-c22c557d54a4/attribute/displayed] with body: {}
[debug] [WD Proxy] Got response with status 200: "{\"sessionId\":\"ea0b2e86-2bff-4d1f-aad6-e98b950f9f56\",\"status\":0,\"value\":\"true\"}"
[debug] [W3C (4b2bdc1d)] Responding to client with driver.elementDisplayed() result: true
[HTTP] <-- GET /wd/hub/session/4b2bdc1d-ac2b-4042-9132-f123d99ce3bf/element/93ed0817-aa19-413b-9487-c22c557d54a4/displayed 200 20084 ms - 14
[HTTP]
[HTTP] --> GET /wd/hub/session/4b2bdc1d-ac2b-4042-9132-f123d99ce3bf/element/93ed0817-aa19-413b-9487-c22c557d54a4/enabled
[HTTP] {}
[debug] [W3C (4b2bdc1d)] Calling AppiumDriver.elementEnabled() with args: ["93ed0817-aa19-413b-9487-c22c557d54a4","4b2bdc1d-ac2b-4042-9132-f123d99ce3bf"]
[debug] [WD Proxy] Matched '/element/93ed0817-aa19-413b-9487-c22c557d54a4/attribute/enabled' to command name 'getAttribute'
[debug] [WD Proxy] Proxying [GET /element/93ed0817-aa19-413b-9487-c22c557d54a4/attribute/enabled] to [GET http://localhost:8200/wd/hub/session/ea0b2e86-2bff-4d1f-aad6-e98b950f9f56/element/93ed0817-aa19-413b-9487-c22c557d54a4/attribute/enabled] with body: {}
[debug] [WD Proxy] Got response with status 200: "{\"sessionId\":\"ea0b2e86-2bff-4d1f-aad6-e98b950f9f56\",\"status\":0,\"value\":\"true\"}"
[debug] [W3C (4b2bdc1d)] Responding to client with driver.elementEnabled() result: true
[HTTP] <-- GET /wd/hub/session/4b2bdc1d-ac2b-4042-9132-f123d99ce3bf/element/93ed0817-aa19-413b-9487-c22c557d54a4/enabled 200 20233 ms - 14
[HTTP]
[HTTP] --> POST /wd/hub/session/4b2bdc1d-ac2b-4042-9132-f123d99ce3bf/element/93ed0817-aa19-413b-9487-c22c557d54a4/click
[HTTP] {"id":"93ed0817-aa19-413b-9487-c22c557d54a4"}
[debug] [W3C (4b2bdc1d)] Calling AppiumDriver.click() with args: ["93ed0817-aa19-413b-9487-c22c557d54a4","4b2bdc1d-ac2b-4042-9132-f123d99ce3bf"]
[debug] [WD Proxy] Matched '/element/93ed0817-aa19-413b-9487-c22c557d54a4/click' to command name 'click'
[debug] [WD Proxy] Proxying [POST /element/93ed0817-aa19-413b-9487-c22c557d54a4/click] to [POST http://localhost:8200/wd/hub/session/ea0b2e86-2bff-4d1f-aad6-e98b950f9f56/element/93ed0817-aa19-413b-9487-c22c557d54a4/click] with body: {"element":"93ed0817-aa19-413b-9487-c22c557d54a4"}

**Comment by HoLeAnh** [comment]
Anyone help me ? :(

**Comment by mykola-mokhnach** [comment]
try to explicitly set the `automationName` to `uiautomator1`

**Comment by HoLeAnh** [comment]
> try to explicitly set the `automationName` to `uiautomator1`

Like i know Android 8 cannot work with uiautomator1, I tried it and it was

**Comment by mykola-mokhnach** [comment]
I see your platform version is 4.4.4 in the attached log. Otherwise make sure your application might not be designed properly. Check https://github.com/appium/appium/issues/13097 for more details

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
