### ISSUE TITLE
Disable logs from server

### ISSUE THREAD

**Issue by ClassAxion** [appium/appium#13125]
How can I disable logs from server? I have this code to run server:

`
 const server = await startServer(port, '127.0.0.1')   
`

I'm using webdriverio as my driver, and I set `logLevel: 'silent'` which work in appium server, but here it doesn't work because I think that this work only for driver.

I want to disable this logs:
![tHSdoMF](https://user-images.githubusercontent.com/7270946/63692599-5571d200-c812-11e9-9b35-6b23e6ccb42c.png)

**Comment by ClassAxion** [comment]
I found `_TESTING=1` in appium-logger repository, that also works.

**Comment by imurchie** [comment]
That works, yes, but has _absolutely no guarantee of continuing to work_.
