### ISSUE TITLE
Unknow appium server side issues with real android devices

### ISSUE THREAD

**Issue by charan517333** [appium/appium#13126]
I'm trying to run two different ports of appium with different model android devices.

S10: port:1237

S9: port: 1298

Observed behavior: Everytime when I run in multiple real devices. I was able to see unknow service side issue and gets terminated and also all the remaining test cases are skipped.

Environment
Appium server version 1.13
Desktop OS/version used to run Appium if necessary: Running appium in command prompt
Mobile platform/version under test: 9(pie)
Real device or emulator/simulator: Real devices
[Capabilities.txt](https://github.com/appium/appium/files/3541373/Capabilities.txt)
[Appium failure.txt](https://github.com/appium/appium/files/3541374/Appium.failure.txt)

**Comment by HoLeAnh** [comment]
Sometime i also have same issue and i restart simulator and the problem be resolved.

**Comment by mykola-mokhnach** [comment]
1. UiAutomator1 is obsolete and should not be used for Android 6+
2. Follow https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/parallel-tests.md

**Comment by mykola-mokhnach** [comment]
Did you read the document above?

**Comment by charan517333** [comment]
@mykola-mokhnach Yes I've read the above document and followed the process. But able to see sendkeys error
[Appium error.txt](https://github.com/appium/appium/files/3554690/Appium.error.txt)

**Comment by mykola-mokhnach** [comment]
This problem is different from the initially reported one, so I close this ticket.

Regarding stale reference error - make sure you call findElement before entering the text. Most likely the previously cached WebElement instance gets invalidated by the app and there is nothing to do there on Appium side.
