### ISSUE TITLE
add iOS voice control driver

### ISSUE THREAD

**Issue by maguowei** [appium/appium#13123]
## The problem

Start iOS 13 Apple Introduce  the new Voice Control.

- https://www.apple.com/ios/ios-13-preview/features/
- https://www.businessinsider.com/apple-ios-13-voice-control-video-demonstration-2019-6#to-go-back-to-the-home-screen-just-say-exactly-that-5

It is so powerful！

I think it's a good way for UI test.

## Environment

* iOS 13 +

**Comment by mykola-mokhnach** [comment]
Which xctest interfaces are responsible for that? Do you have any test code examples?
