### ISSUE TITLE
How to upgrade the chrome browser at Android 8.1 emulator

### ISSUE THREAD

**Issue by siva90144** [appium/appium#13136]
## The problem
@tomliuxin
followed the steps mentioned in #7179. But in device 

## Environment

* Appium version (or git revision) that exhibits the issue:v1.14.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): 10.15.3
* Npm or Yarn package manager:
* Mobile platform/version under test: Android 8.1
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe:

## Details

Followed below steps:
used the CMD to uninstall it.

adb root
adb remount
adb shell
cd system
cd app
rm Chrome -f -rR

open CMD again
adb root
adb remount
adb shell
cd data
cd data
rm -r com.android.chrome

Its not showing anything and I checked in emulator still chrome browser is there....

is there anything i missed ?

PFA... attached screenshots 
## Code To Reproduce Issue [ Good To Have ]

<img width="250" alt="second-set" src="https://user-images.githubusercontent.com/19613704/63803589-44dd5c80-c8e3-11e9-84da-b00f24280879.PNG">
<img width="216" alt="Uninstall" src="https://user-images.githubusercontent.com/19613704/63803590-44dd5c80-c8e3-11e9-8a1d-50a711b811d1.PNG">

**Comment by mykola-mokhnach** [comment]
Sorry, but this is not the place for howto questions. Please use appium forum for such purpose

**Comment by mykola-mokhnach** [comment]
discuss.appium.io
