### ISSUE TITLE
Reset command "timeout" on iOS real device

### ISSUE THREAD

**Issue by cosminstirbu** [appium/appium#13134]
## The problem

We have a suite of tests that we run on a real device for which we create a single session and we call `reset` before each test.

The issue is that sometimes the server times out when resetting the application - so this occurs intermittently.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 10.14.6
* Node.js version (unless using Appium.app|exe): v12.8.0
* Npm or Yarn package manager: 6.10.2
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

Session creation - https://gist.github.com/cosminstirbu/a5f26bfbfaa2df5fae436def132ca180
Reset command timeout - https://gist.github.com/cosminstirbu/72b897fa12921500524167375036ac9b
Reset command timeout - https://gist.github.com/cosminstirbu/dfeb430a84d41dd37b0a5058daf082ab
Reset command working - https://gist.github.com/cosminstirbu/a72fc72a53b161713192295f1dfc1ceb

**Comment by mykola-mokhnach** [comment]
To me this looks more like imobiledevice issue. It might be appium@beta works better, since it does not depend on this third party library anymore.

**Comment by KazuCocoa** [comment]
I ran `reset` and it worked (both 1.14 and beta)
So, as mykola said, I also assume this issue is imobiledevice layer

**Comment by cosminstirbu** [comment]
Interestingly enough in the latest beta it initially didn't reproduce at all, but minutes ago it reproduced once (out of 30 tests).

I'll keep monitoring it.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
