### ISSUE TITLE
Appium 1.14: Upgrade of Android app fails: INSTALL_FAILED_UPDATE_INCOMPATIBLE

### ISSUE THREAD

**Issue by mirao** [appium/appium#13145]
## The problem
When my test tries to upgrade installed application to a new version (different from old one, with higher internal version), it fails.
It's a regression in Appium 1.14. It works for me with 1.13.

## Steps:
- Have clean Android environment (the app was never installed there)
- Let test install the old application using these capabilities (it succeeds):
```
[Appium] Appium v1.14.2 creating new AndroidUiautomator2Driver (v1.33.1) session
[Appium] Capabilities:
[Appium]   app: http://192.168.1.239/SPORK-old.apk
[Appium]   appWaitActivity: com.spork.android.controllers.activities.ProvisioningSelection
[Appium]   platformName: Android
[Appium]   platformVersion: 8.1
[Appium]   autoGrantPermissions: true
[Appium]   noReset: true
[Appium]   adbExecTimeout: 120000
[Appium]   deviceName: emulator
```
- Upgrade the application to a new version. It fails, this is log from Appium 1.14:
https://gist.github.com/mirao/57eedd1d6e40ee25d370eccf5a4d14f2
- If you do the same steps with Appium 1.13 (also in clean environment), it passes. This is a log from Appium 1.13:
https://gist.github.com/mirao/c31577b6b8268fbbf9053a8bfdfc8d04

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14
* Last Appium version that did not exhibit the issue (if applicable): 1.13
* Desktop OS/version used to run Appium: Ubuntu 18.04/19.04
* Node.js version (unless using Appium.app|exe): v10.16.3
* Npm or Yarn package manager: npm 6.10.2
* Mobile platform/version under test: CodeceptJS [2.1.4](https://codecept.io/changelog/#214) with WebDriverIO [5.7.2](https://github.com/webdriverio/webdriverio/blob/master/CHANGELOG.md#572-2019-03-10)
* Real device or emulator/simulator: Emulator Nexus 9 (Android 8.1) in Android Studio 3.5
* Appium CLI or Appium.app|exe: Appium CLI

**Comment by mykola-mokhnach** [comment]
> Package com.spork.dev signatures do not match the previously installed version

I think the error is expected and it has nothing to do with Appium. You must make sure the previously installed app package and the current one have the same signature. Also note, that by default Appium resigns the package. You can prevent this by setting the `noSign` capability to true

**Comment by mirao** [comment]
@mykola-mokhnach 
Thanks, `noSign: true` helped me in 1.14.
Does it mean that in Appium 1.13 the option `noSign` has value "true" by default ? Because the test passes in 1.13 without `noSign: true`, with the same APK packages I tested in 1.14

**Comment by mykola-mokhnach** [comment]
> Does it mean that in Appium 1.13 the option noSign has value "true" by default ? Because the test passes in 1.13 without noSign: true, with the same APK packages I tested in 1.14

Unlikely. I don't remember significant changes in uia2 between these two minor versions

**Comment by mirao** [comment]
Closing. Solved by adding of capability `noSign: true` into test configuration.
