### ISSUE TITLE
[appium@beta] Elements are not got in page source of some pages

### ISSUE THREAD

**Issue by maggie5750** [appium/appium#13140]
## The problem
[appium@beta] Elements are not got in page source of some pages

## Environment

* Appium version (or git revision) that exhibits the issue: appium@beta
* Last Appium version that did not exhibit the issue (if applicable): appium@1.14.0
* Desktop OS/version used to run Appium: Mac OS 10.14.4
* Node.js version (unless using Appium.app|exe): 10.16.3
* Npm or Yarn package manager:
* Mobile platform/version under test: IOS 13.0 beta 7
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe:

## Details
[appium@beta] Elements are not got in page source of some pages, such as some confirm action sheet, some upper screen. The element shown but can not find it in driver.getPageSource(). appium 1.14.0 + IOS12  doesn't have this issue.

**Comment by mykola-mokhnach** [comment]
It might something has been changed in how xctest generated snapshots since iOS 13 SDK. I don't think we can do much there

**Comment by bearxc** [comment]
This could related with  following known issue 

https://github.com/appium/appium/issues/12965

**Comment by bearxc** [comment]
on xcode 11 beta7 ,   xcode build in function  debugDescription could not catch all elements , but app.buttons["Id"] still works fine on  xcode/xcuitest  , even that button does not appear in debugDescription dump tree.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue.
