### ISSUE TITLE
Getting Error : OpenQA.Selenium.WebDriverException: 'An element could not be located on the page using the given search parameters.'

### ISSUE THREAD

**Issue by AmyB123** [appium/appium#13147]
Hello ,

I am getting the below error :

OpenQA.Selenium.WebDriverException: 'An element could not be located on the page using the given search parameters.'

We are using appium for Desktop automation and trying to write a method as below:

public void IsElementExist(WindowsElement selectorElement, int timeOut)
        {
            var wait = new WebDriverWait(AppiumDriver, new TimeSpan(0, 0, timeOut));
            try
            {
                wait.Until(ExpectedConditions.ElementToBeClickable(selectorElement));
            }
            catch (Exception e)
            {
                Assert.Fail("Element not found " + e.ToString());
            }
        }

Object is declared in Homepage.cs as below 
 public By ByHP_UserID_AID = new ByAccessibilityId("loginNameBox");
        public WindowsElement HP_UserID_AID => AppiumDriver.FindElement(ByHP_UserID_AID);

Calling the method as 
IsElementExist(HP_UserID_AID ,30).

Can anyone help in this.

Thanks,
Amy

**Comment by mykola-mokhnach** [comment]
Please use Appium forum to ask questions
