### ISSUE TITLE
Issue with mobile: launchApp and mobile: activateApp

### ISSUE THREAD

**Issue by stephenjg24-git** [appium/appium#13149]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:  Desktop on Mac 1.13.3 and v1.14.2-rc.0 command line

* Last Appium version that did not exhibit the issue (if applicable): ???
* Desktop OS/version used to run Appium:  MAC OSX
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: IOS 12.4
* Real device or emulator/simulator:  Both
* Appium CLI or Appium.app|exe: Both

## Details

Basic test that should launch an app on the ios device "News App" 
then should launch a different app "Preferences"
then re open "News"
Then reopen "Preferences"

Then the test starts it will launch the New app just fine, it is with it tries to Launch the "Preferences" it creates and error.
ERROR: An unknown server-side error occurred while processing the command. Original error: 'bundleId' is expected to be a valid string. 'undefined' is given instead

I re-created this is Java and it runs as expected.

sample code:
https://gist.github.com/stephenjg24-git/a559619b095624389b04a6d6d74a2141

**Comment by KazuCocoa** [comment]
What about set "bundleId" instead of "app"?
http://appium.io/docs/en/writing-running-appium/ios/ios-xctest-mobile-apps-management/index.html#mobile-launchapp

**Comment by stephenjg24-git** [comment]
@KazuCocoa thanks for pointing out my error in my code, 

Old ==> args.Add("app", PREFERENCES_BUNDLE_ID);
New ==>  args.Add("bundleId", PREFERENCES_BUNDLE_ID);
The new line works

Adding the sample code that works to this.

https://gist.github.com/stephenjg24-git/93cf9dace89d17d11004dcbff12a68b7

Stephen

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
