### ISSUE TITLE
Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: API violation - object is a required parameter

### ISSUE THREAD

**Issue by rdhandapani88** [appium/appium#13146]
## The problem

I have recently downloaded the new Appium version 1.14.2, and trying to execute appium tests in IPad's in horizontal mode. WebDriverAgent is installing in the device, but the automation is not started, It throws error as "[debug] [MJSONWP] Matched JSONWP error code 13 to UnknownError
[debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: API violation - object is a required parameter."

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.2
* Last Appium version that did not exhibit the issue (if applicable): 1.10.0
* Desktop OS/version used to run Appium: MacOS Mojave 10.14.6
* Node.js version (unless using Appium.app|exe): 9.11.1
* Npm - 5.6.0
* Mobile platform/version under test: -12.4, 12.3.1
* Real device  
* Started appium in terminal command

## Details

If necessary, describe the problem you have been experiencing in more detail.

Unknown error - "[debug] [MJSONWP] Matched JSONWP error code 13 to UnknownError
[debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: API violation - object is a required parameter."

## Link to Appium logs

[debug] [MJSONWP] Matched JSONWP error code 13 to UnknownError
[debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: API violation - object is a required parameter.
[debug] [XCUITest] 
[debug] [XCUITest] (
[debug] [XCUITest] 	0   CoreFoundation                      0x00000001af04d9a4 <redacted> + 252
[debug] [XCUITest] 	1   libobjc.A.dylib                     0x00000001ae2269f8 objc_exception_throw + 56
[debug] [XCUITest] 	2   CoreFoundation                      0x00000001aef67098 <redacted> + 0
[debug] [XCUITest] 	3   Foundation                          0x00000001afa2b088 <redacted> + 112
[debug] [XCUITest] 	4   XCTest                              0x00000001009506b8 -[XCTKVOExpectation initWithKeyPath:object:expectedValue:options:] + 644
[debug] [XCUITest] 	5   XCTest                              0x0000000100950720 -[XCTKVOExpectation initWithKeyPath:object:expectedValue:] + 84
[debug] [XCUITest] 	6   XCTest                              0x0000000100957fa4 -[XCUIApplicationImpl _waitForValidPID] + 132
[debug] [XCUITest] 	7   XCTest                              0x0000000100956bbc __42-[XCUIApplicationImpl _launchWithRequest:]_block_invoke + 736
[debug] [XCUITest] 	8   XCTest                              0x0000000100946d3c -[XCTContext _runActivityNamed:type:block:] + 248
[debug] [XCUITest] 	9   XCTest                              0x00000001008e9dd8 -[XCTestCase startActivityWithTitle:type:block:] + 212
[debug] [XCUITest] 	10  XCTest                              0x00000001008e9fa0 -[XCTestCase startActivityWithTitle:block:] + 72
[debug] [XCUITest] 	11  XCTest                              0x00000001009568a0 -[XCUIApplicationImpl _launchWithRequest:] + 220
[debug] [XCUITest] 	12  XCTest                              0x0000000100946d3c -[XCTContext _runActivityNamed:type:block:] + 248
[debug] [XCUITest] 	13  XCTest                              0x00000001008e9dd8 -[XCTestCase startActivityWithTitle:type:block:] + 212
[debug] [XCUITest] 	14  XCTest                              0x00000001008e9fa0 -[XCTestCase startActivityWithTitle:block:] + 72
[debug] [XCUITest] 	15  XCTest                              0x00000001009563a0 -[XCUIApplicationImpl serviceOpenRequest:] + 248
[debug] [XCUITest] 	16  XCTest                              0x00000001009194ac -[XCUIApplication _launchUsingXcode:] + 320
[debug] [XCUITest] 	17  WebDriverAgentLib                   0x000000010446b214 -[FBApplication launch] + 136
[debug] [XCUITest] 	18  WebDriverAgentLib                   0x0000000104459004 +[FBSessionCommands handleCreateSession:] + 1788
[debug] [XCUITest] 	19  WebDriverAgentLib                   0x00000001044329a4 -[FBRoute_TargetAction mountRequest:intoResponse:] + 220
[debug] [XCUITest] 	20  WebDriverAgentLib                   0x00000001044216f8 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 504
[debug] [XCUITest] 	21  RoutingHTTPServer                   0x0000000104596310 -[RoutingHTTPServer handleRoute:withRequest:response:] + 144
[debug] [XCUITest] 	22  RoutingHTTPServer                   0x0000000104596ae0 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 44
[debug] [XCUITest] 	23  libdispatch.dylib                   0x00000001aea8c7d4 <redacted> + 16
[debug] [XCUITest] 	24  libdispatch.dylib                   0x00000001aea3acec <redacted> + 92
[debug] [XCUITest] 	25  libdispatch.dylib                   0x00000001aea8c7d4 <redacted> + 16
[debug] [XCUITest] 	26  libdispatch.dylib                   0x00000001aea3a008 <redacted> + 1068
[debug] [XCUITest] 	27  CoreFoundation                      0x00000001aefdf32c <redacted> + 12
[debug] [XCUITest] 	28  CoreFoundation                      0x00000001aefda264 <redacted> + 1924
[debug] [XCUITest] 	29  CoreFoundation                      0x00000001aefd97c0 CFRunLoopRunSpecific + 436
[debug] [XCUITest] 	30  Foundation                          0x00000001af9a7eac <redacted> + 300
[debug] [XCUITest] 	31  WebDriverAgentLib                   0x0000000104420180 -[FBWebServer startServing] + 440
[debug] [XCUITest] 	32  WebDriverAgentRunner                0x0000000104403be8 -[UITestingUITests testRunner] + 124
[debug] [XCUITest] 	33  CoreFoundation                      0x00000001af055010 <redacted> + 144
[debug] [XCUITest] 	34  CoreFoundation                      0x00000001aef36be0 <redacted> + 292
[debug] [XCUITest] 	35  XCTest                              0x00000001008e200c __24-[XCTestCase invokeTest]_block_invoke_2.200 + 68
[debug] [XCUITest] 	36  XCTest                              0x0000000100949ef8 -[XCTMemoryChecker _assertInvalidObjectsDeallocatedAfterScope:] + 68
[debug] [XCUITest] 	37  XCTest                              0x00000001008ea604 -[XCTestCase assertInvalidObjectsDeallocatedAfterScope:] + 112
[debug] [XCUITest] 	38  XCTest                              0x00000001008e1f98 __24-[XCTestCase invokeTest]_block_invoke.194 + 196
[debug] [XCUITest] 	39  XCTest                              0x0000000100936ed4 -[XCTestCase(Failures) performFailableBlock:testCaseRun:shouldInterruptTest:] + 64
[debug] [XCUITest] 	40  XCTest                              0x0000000100936dec -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] + 108
[debug] [XCUITest] 	41  XCTest                              0x00000001008e1bc8 __24-[XCTestCase invokeTest]_block_invoke + 808
[debug] [XCUITest] 	42  XCTest                              0x000000010093ce8c -[XCUITestContext performInScope:] + 144
[debug] [XCUITest] 	43  XCTest                              0x00000001008e17cc -[XCTestCase testContextPerformInScope:] + 120
[debug] [XCUITest] 	44  XCTest                              0x00000001008e188c -[XCTestCase invokeTest] + 140
[debug] [XCUITest] 	45  XCTest                              0x00000001008e335c __26-[XCTestCase performTest:]_block_invoke_2 + 44
[debug] [XCUITest] 	46  XCTest                              0x0000000100936ed4 -[XCTestCase(Failures) performFailableBlock:testCaseRun:shouldInterruptTest:] + 64
[debug] [XCUITest] 	47  XCTest                              0x0000000100936dec -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] + 108
[debug] [XCUITest] 	48  XCTest                              0x00000001008e3274 __26-[XCTestCase performTest:]_block_invoke.324 + 96
[debug] [XCUITest] 	49  XCTest                              0x0000000100947440 +[XCTContext runInContextForTestCase:block:] + 216
[debug] [XCUITest] 	50  XCTest                              0x00000001008e2a2c -[XCTestCase performTest:] + 644
[debug] [XCUITest] 	51  XCTest                              0x00000001009240e8 -[XCTest runTest] + 60
[debug] [XCUITest] 	52  XCTest                              0x00000001008dd81c __27-[XCTestSuite performTest:]_block_invoke + 280
[debug] [XCUITest] 	53  XCTest                              0x00000001008dd13c -[XCTestSuite _performProtectedSectionForTest:testSection:] + 68
[debug] [XCUITest] 	54  XCTest                              0x00000001008dd3d8 -[XCTestSuite performTest:] + 276
[debug] [XCUITest] 	55  XCTest                              0x00000001009240e8 -[XCTest runTest] + 60
[debug] [XCUITest] 	56  XCTest                              0x00000001008dd81c __27-[XCTestSuite performTest:]_block_invoke + 280
[debug] [XCUITest] 	57  XCTest                              0x00000001008dd13c -[XCTestSuite _performProtectedSectionForTest:testSection:] + 68
[debug] [XCUITest] 	58  XCTest                              0x00000001008dd3d8 -[XCTestSuite performTest:] + 276
[debug] [XCUITest] 	59  XCTest                              0x00000001009240e8 -[XCTest runTest] + 60
[debug] [XCUITest] 	60  XCTest                              0x00000001008dd81c __27-[XCTestSuite performTest:]_block_invoke + 280
[debug] [XCUITest] 	61  XCTest                              0x00000001008dd13c -[XCTestSuite _performProtectedSectionForTest:testSection:] + 68
[debug] [XCUITest] 	62  XCTest                              0x00000001008dd3d8 -[XCTestSuite performTest:] + 276
[debug] [XCUITest] 	63  XCTest                              0x00000001009240e8 -[XCTest runTest] + 60
[debug] [XCUITest] 	64  XCTest                              0x00000001009546a8 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 176
[debug] [XCUITest] 	65  XCTest                              0x0000000100954778 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke.80 + 60
[debug] [XCUITest] 	66  XCTest                              0x00000001008f46d0 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 516
[debug] [XCUITest] 	67  XCTest                              0x0000000100954464 -[XCTTestRunSession runTestsAndReturnError:] + 596
[debug] [XCUITest] 	68  XCTest                              0x00000001008c2704 -[XCTestDriver runTestsAndReturnError:] + 436
[debug] [XCUITest] 	69  XCTest                              0x00000001009438c0 _XCTestMain + 2248
[debug] [XCUITest] 	70  WebDriverAgentRunner-Runner         0x00000001004ffb60 -[_XCTRunnerAppDelegate applicationWillResignActive:] + 0
[debug] [XCUITest] 	71  WebDriverAgentRunner-Runner         0x00000001004ffa68 _XCTRunnerRunTests + 0
[debug] [XCUITest] 	72  CoreFoundation                      0x00000001aefdf578 <redacted> + 20
[debug] [XCUITest] 	73  CoreFoundation                      0x00000001aefdee7c <redacted> + 272
[debug] [XCUITest] 	74  CoreFoundation                      0x00000001aefd9ee0 <redacted> + 1024
[debug] [XCUITest] 	75  CoreFoundation                      0x00000001aefd97c0 CFRunLoopRunSpecific + 436
[debug] [XCUITest] 	76  GraphicsServices                    0x00000001b11da79c GSEventRunModal + 104
[debug] [XCUITest] 	77  UIKitCore                           0x00000001db68cc38 UIApplicationMain + 212
[debug] [XCUITest] 	78  WebDriverAgentRunner-Runner         0x00000001004ffd3c main + 192
[debug] [XCUITest] 	79  libdyld.dylib                       0x00000001aea9d8e0 <redacted> + 4
[debug] [XCUITest] )). Retrying...

**Comment by mykola-mokhnach** [comment]
Please provide the full server log

**Comment by mykola-mokhnach** [comment]
The log does not contain the capabilities list. Also, the bundle identifier does not look good, it contains some unnecessary character: `"bundleId":"com.vzw.pos.posmobile\u0000"`

**Comment by rdhandapani88** [comment]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1567023074023 (16:11:14 GMT-0400 (EDT))
[BaseDriver] The capabilities ["cleanSafari","orientation "] are not standard capabilities and should have an extension prefix
[BaseDriver] Number capability passed in as string. Functionality may be compromised.
[Appium] Appium v1.14.2 creating new XCUITestDriver (v2.116.3) session
[Appium] Capabilities:
[Appium]   cleanSafari: true
[Appium]   orientation : PORTRAIT
[Appium]   platformName: ios
[Appium]   automationName: XCUITest
[Appium]   bundleId: com.vzw.pos.posmobile
[Appium]   clearSystemFiles: true
[Appium]   deviceName: iOS
[Appium]   newCommandTimeout: 360
[Appium]   platformVersion: 11.2.2
[Appium]   startIWDP: true
[Appium]   udid: 88c951a979e9dc20d784f23575ab055e9da29107
[Appium]   useNewWDA: true
[Appium]   wdaConnectionTimeout: 90000
[Appium]   wdaLaunchTimeout: 90000
[debug] [BaseDriver] W3C capabilities {"alwaysMatch":{"appium:cle... and MJSONWP desired capabilities {"udid":"88c951a979e9dc20d7... were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"appium:cle...
[BaseDriver] Number capability passed in as string. Functionality may be compromised.
[BaseDriver] Capability 'useNewWDA' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Capability 'startIWDP' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Capability 'newCommandTimeout' changed from string ('360') to integer (360). This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[BaseDriver]   cleanSafari
[BaseDriver]   orientation

**Comment by rdhandapani88** [comment]
{"bundleId":"com.vzw.pos.mobileposng\u0000" ,  I dont know where the special characters are coming. the bundle id is "com.vzw.pos.mobileposng", but while proxying it is getting this budledid with some space at the end.

"Proxying [POST /session] to [POST http://localhost:6246/session] with body: {"desiredCapabilities":{"bundleId":"com.vzw.pos.mobileposng\u0000","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
"

**Comment by rdhandapani88** [comment]
This issue is Solved. The mistake is mine. I was executing the ipads in parallel, actually the application is in webview, forget to start the IOs-WebKit-Debugproxy. Now i can execute the iPads in parallel in 10.14.2 (Greater and Stable version). Please close the issue
