### ISSUE TITLE
Use ActionChains(driver).send_keys to send chinese causes  java.lang.NullPointerException

### ISSUE THREAD

**Issue by luisxiaomai** [appium/appium#13154]
## The problem

I used ActionChains(driver).send_keys to send Chinese in android edit field, but it got below error. It's ok to send english words. 
````
[WD Proxy] Matched '/actions' to command name 'performActions'
[WD Proxy] Proxying [POST /actions] to [POST http://localhost:8212/wd/hub/session/05f5a156-0461-463b-b8e9-5f858f7f3065/actions] with body: {"actions":[{"type":"pointer","parameters":
{"pointerType":"mouse"},"id":"mouse","actions":[{"type":"pause","duration":0},
{"type":"pause","duration":0},{"type":"pause","duration":0},{"type":"pause","duration":0},
{"type":"pause","duration":0},{"type":"pause","duration":0},{"type":"pause","duration":0},
{"type":"pause","duration":0},{"type":"pause","duration":0},{"type":"pause","duration":0}]},
{"type":"key","id":"key","actions":[{"type":"keyDown","value":"s"},{"type":"keyUp","value":"s"},
{"type":"keyDown","value":"s"},{"type":"keyUp","value":"s"},{"type":"keyDown","value":"s"},
{"type":"keyUp","value":"s"},{"type":"keyDown","value":"你"},{"type":"keyUp","value":"你"},
{"type":"keyDown","value":"好"},{"type":"keyUp","value":"好"}]}]}
[WD Proxy] Got an unexpected response: {"sessionId":"05f5a156-0461-463b-b8e9-
5f858f7f3065","status":13,"value":"java.lang.NullPointerException: Attempt to get length of null array\n\tat 
io.appium.uiautomator2.utils.w3c.ActionsExecutor.injectKeyEvent(ActionsExecutor.java:105)\n\tat io.appium.uiautomator2.utils.w3c.ActionsExecutor.execu...
[MJSONWP] Matched JSONWP error code 13 to UnknownError
[W3C (8f6a811f)] Encountered internal error running command: UnknownError: An unknown 
server-side error occurred while processing the command. Original error: java.lang.NullPointerException: Attempt to get length of null array
[W3C (8f6a811f)] 	at 
io.appium.uiautomator2.utils.w3c.ActionsExecutor.injectKeyEvent(ActionsExecutor.java:105)
````
What I want to do is to send multiple lines into one text fields, my codes likes:
````
 for index, itemText in enumerate(textList):
       ActionChains(driver).send_keys(itemText).perform()
       driver.press_keycode(66)
       driver.press_keycode(66)
````

## Help
Any other way to send multiple lines into one text field is welcome. set_value , set_text or send_keys will all clear previous text in android.

## Environment

* Appium version: 1.13.0

**Comment by mykola-mokhnach** [comment]
What if you construct the custom keys sequence like it is described in https://appiumpro.com/editions/46 ?

**Comment by mykola-mokhnach** [comment]
Actually, it will probably not work, because https://developer.android.com/reference/android/view/KeyCharacterMap.html#getEvents(char[]) cannot properly construct key events for Chinese characters. Patches are welcome

**Comment by luisxiaomai** [comment]
@mykola-mokhnach , thanks for your explanation for my way.
Is there a way to send multiple lines into one text field? set_value function says will append text, but it does not. I also tried send_keys or set_text, both failed.

**Comment by mykola-mokhnach** [comment]
Yep, unfortunately this is the way UIA2 works. I would try to generate the necessary key codes using `pressKey` API. One by one. Or submit a patch to w3c actions.

**Comment by mykola-mokhnach** [comment]
Added the `mobile: type` endpoint to appium@beta, which is supposed to resolve the issue. See https://github.com/appium/appium-uiautomator2-driver/pull/365 for more details.
