### ISSUE TITLE
useXctestrunFile: true is expecting .xcodeproj project in the folder and WebDriverAgent.xcodeproj -showBuildSettings' exited with code 66

### ISSUE THREAD

**Issue by govindu84** [appium/appium#13158]
## The problem

Hello,

Requirement: We want a re usable WDA .xctestrun file to run tests on real device without building and would like to use that in couple of appium installed machines so test cases should run without building.

**Issue:** Previously(appium 1.7), we had created .xctestrun file and placed in separate folder(WDA) and ran it, it worked but in Appium 1.14, if i do same thing appium expecting .xcodeproj project file in WDA folder, giving WebDriverAgent.xcodeproj -showBuildSettings' exited with code 66.

## Environment
* Appium version (or git revision) that exhibits the issue: 1.14
xcode 10.3 
Node latest
Mac OS latest

## Link to Appium logs
LOGS: https://gist.github.com/govindu84/33c23b4e5d51c45684da8762b1225fb0

Things i research:
I see in appium 1.12, fixed following issue, i feel this is causing this issue. 
https://github.com/appium/appium-xcuitest-driver/pull/903

Note: If i tried to copy .xcodeproj to  Custom WDA folder and run the appium, it is working.

**Comment by mykola-mokhnach** [comment]
What is the output of `xcodebuild -project /Applications/Olympus/bin/WDA/WebDriverAgent.xcodeproj -showBuildSettings` when executed from the command line?

**Comment by govindu84** [comment]
It's failing : xcodebuild: error: '/Applications/Olympus/bin/WDA/WebDriverAgent.xcodeproj' does not exist.
Actually, WebDriverAgent.xcodeproj doesn't exist in WDA folder. I am creating prebuild files (Debug-iphoneos folder and WebDriverAgentRunner_iphoneos12.2-arm64.xctestfile files) using  following command and placing in WDA folder, i am expecting appium should use debug-iphones and WebDriverAgentRunner_iphoneos12.2-arm64.xctestfile to run test cases like appium 1.7 version did.

'xcodebuild build-for-testing -project /Users/macminihost05/Downloads/appium-1.14.0/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath /Users/macminihost05/Library/Developer/Xcode/DerivedData/WebDriverAgent-dzrjdozcvxlmxedluyiiqgeemqny -destination ‘platform=iOS ,IOS=12.2’.

**Comment by mykola-mokhnach** [comment]
Why don't you set the custom path as derivedDataPath cap in such case?

**Comment by govindu84** [comment]
As per following capability information, i just need to copy debug-phones folder and .xctestfile from deriveddatapath location so i did copy those 2 files to WDA and ran test.

![Screen Shot 2019-08-29 at 2 37 09 PM](https://user-images.githubusercontent.com/19738768/63978317-ec38cb80-ca6a-11e9-8f2d-e9c665ac0af0.png)

![Screen Shot 2019-08-29 at 2 30 23 PM](https://user-images.githubusercontent.com/19738768/63978361-05da1300-ca6b-11e9-8399-39cf983de5f5.png)

**Comment by govindu84** [comment]
Here is the my custom WDA folder looks like.
![Screen Shot 2019-08-29 at 2 41 53 PM](https://user-images.githubusercontent.com/19738768/63978442-3457ee00-ca6b-11e9-980e-27f2780c8f92.png)

**Comment by mykola-mokhnach** [comment]
The idea is you put these files together with the WDA source not instead of it. Having the build settings information we could better optimise the build process.

**Comment by govindu84** [comment]
Oh I see, Just want to make sure again, if we keep WDA source code along with this files(debug-iphones and .xctestrun), my future test cases won't rebuild right? it just uses already build .xctestrun file to execute test cases. 

Thanks in advance.

**Comment by mykola-mokhnach** [comment]
Yes, no rebuild will be performed if `useXctestrunFile` is set to true

**Comment by govindu84** [comment]
Awesome, Thanks.
