### ISSUE TITLE
OpenCV install problem

### ISSUE THREAD

**Issue by SeakyLuo** [appium/appium#13152]
## The problem

I am using python 3.7.4 and I want to use find_element_by_image.

I have installed open4nodejs (although I got a lot lot lot of warnings) and restarted Appium. But I still get this Exception:

selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: opencv4nodejs module is required to use OpenCV features. Please install it first (npm i -g opencv4nodejs) and restart Appium. Read https://github.com/justadudewhohacks/opencv4nodejs#how-to-install for more details on this topic.

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Do you use Appium from CLI or Appium desktop?

**Comment by imurchie** [comment]
The latest beta (or rc) of Appium ought to fix this.

**Comment by SeakyLuo** [comment]
I ran through command line.

**Comment by SeakyLuo** [comment]
@imurchie Where is the beta version? I am using Appium Desktop 1.13.0.

**Comment by mykola-mokhnach** [comment]
This won't work with Appium Desktop, since it uses its own Appium deployment. You must install Appium from CLI using npm and then install opencv libs using the same approach in order to make this working.

**Comment by mykola-mokhnach** [comment]
> Where is the beta version

beta version can be installed via npm: `npm i -g appium@beta`

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
