### ISSUE TITLE
The element TextView is visible on the screen but is not interactable when acquired again

### ISSUE THREAD

**Issue by newbiexie** [appium/appium#13151]
## The problem

The element TextView is visible on the screen but is not interactable when acquired again

## Environment

Appium version (or git revision) that exhibits the issue: appium@beta
Last Appium version that did not exhibit the issue (if applicable): appium@1.14.0
Desktop OS/version used to run Appium: Mac OS 10.14.4
Node.js version (unless using Appium.app|exe): 10.16.3
Npm or Yarn package manager:
Mobile platform/version under test: IOS 13.0 beta 7
Real device or emulator/simulator: Simulator
Appium CLI or Appium.app|exe:

## Details

The element TextView is visible on the screen and can get success but when I clear the element and sendkeys then it failed to get element and throw exception "The element '" TextView' is not visible on the screen and thus is not interactable"

![image](https://user-images.githubusercontent.com/50436326/63920836-425e3c80-ca74-11e9-8e92-49612b26115e.png)
![image](https://user-images.githubusercontent.com/50436326/63920921-628dfb80-ca74-11e9-9dac-43a702d2ebaa.png)
![image](https://user-images.githubusercontent.com/50436326/63920954-776a8f00-ca74-11e9-87a7-bdb83e4a0ef6.png)

**Comment by mykola-mokhnach** [comment]
Such error is thrown if element frame is empty or an incorrect element is elected as the input target. This might also be a race condition issue while element size is changed during animation. Try to wait for a while before typing the new text and make sure you enter it to the proper element.
