### ISSUE TITLE
WDA IntegrationApp freezes on text input if built with Xcode11-beta

### ISSUE THREAD

**Issue by mykola-mokhnach** [appium/appium#13153]
1. Build WDA with Xcode11-beta
2. Execute `FBTypingTest` integration suite on any Simulator running iOS13 

Actual result:
IntegrationApp freezes as soon as the test tries to type anything into the input field. All other controls there work without issues. Also, the problem is manually reproducible.

Expected result: 
The IntegrationApp should be updated for the Xcode11 SDK compatibility.

**Comment by KazuCocoa** [comment]
let me check

**Comment by KazuCocoa** [comment]
But other test cases haev false.
Let me fix them

**Comment by KazuCocoa** [comment]
https://github.com/appium/WebDriverAgent/pull/225

This type to inputtext looks no problem on current Xcode 11 and iOS 13
