### ISSUE TITLE
Appium 1.14.2: Failed to launch com.apple.mobilesafari application on iPhone5s Device

### ISSUE THREAD

**Issue by skumar1122** [appium/appium#13159]
## The problem
I am unable to launch safari on iPhone5s device. I can see WDA app and Integration apps are cleaning after my tests started but nothing happens after that. I am seeing few errors as below. 

`Failed to launch com.apple.mobilesafari: The operation couldn’t be completed. Application "com.apple.mobilesafari" is installing or uninstalling, and cannot be launched. /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1`

Can someone point me if I am missing anything? More logs attached below.

## Environment
* Appium version (or git revision) that exhibits the issue: 1.14.2
* Last Appium version that did not exhibit the issue (if applicable):
* Node.js version (unless using Appium.app|exe):v12.8.1
* Npm or Yarn package manager: npm
* Mobile platform/version under test:12.4
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

## Details
I saw same tests worked for once and I am seeing error now to launch Safari at all. I have restarted Device and my laptop. even I have uninstall/Install Appium and other packages but no use.

I did this too,
brew update
brew uninstall --ignore-dependencies libimobiledevice
brew uninstall --ignore-dependencies libimobiledevice
brew install --HEAD usbmuxd
brew unlink usbmuxd
brew link usbmuxd
brew install --HEAD libimobiledevice
brew install ideviceinstaller

## Link to Appium logs
Please check this gist logs here,
https://gist.github.com/skumar1122/26a8722c347621c02755728e71591617

## Code To Reproduce Issue [ Good To Have ]
```
case "ios":
                capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
                capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");
                capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "12.4");
                capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 5s");
                capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "Safari");
                capabilities.setCapability(MobileCapabilityType.UDID, "xxxxxxxxxxxxxxxxx");
                capabilities.setCapability("startIWDP", true);
                capabilities.setCapability(MobileCapabilityType.AUTO_WEBVIEW, true);
                //capabilities.setCapability("useNewWDA", true);

                /*
                Optional Dependencies
                */
                capabilities.setCapability("fullReset", true);
                capabilities.setCapability("showXcodeLog", true);
                //capabilities.setCapability("noReset", true);
                try {
                    driver = new AppiumDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
                    driver.manage().timeouts().implicitlyWait(50, TimeUnit.SECONDS);
                    Log.info("IOS Webdriver running");

                } catch (MalformedURLException e) {
                    e.printStackTrace();
                }

```

**Comment by mykola-mokhnach** [comment]
- Disable `fullReset` cap
- Reboot the phone and try again
