### ISSUE TITLE
When the PC which running appium server can ping through the IP address of iphone(using Wifi) under test, fail to launch webdriveragent

### ISSUE THREAD

**Issue by st68390206** [appium/appium#13168]
## The problem

When the Mac which running appium server can ping through the IP address of iphone(using Wifi) under test, fail to launch webdriveragent

## Environment
I've double confirmed this by trying it on another Mac.
I know this could be an issue of WDA, but I don't know which WDA repo is adopted by appium, so I raise issue here.
Please let me know if there is anyway to make the PC running appium server can work with the iphone under test under same local area network.

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Unfortunately Appium does not support iOS testing via WiFi. See

https://github.com/appium/appium/issues/12089
https://github.com/appium/appium/issues/12674

for more details

**Comment by st68390206** [comment]
@mykola-mokhnach, thanks for the reply. So is there any way to forbid appium use WiFi way when appium server and iphone under test are under same local area network?
