### ISSUE TITLE
Session [(null externalkey)] not available and is not among the last 1000 terminated sessions

### ISSUE THREAD

**Issue by RST90** [appium/appium#13166]
I have experienced the same issue with Selenium 3.141.59. Downgraded to 3.6 and it works now. Why is this issue closed? It is not working for newer versions than 3.6 so imho it needs to be fixed.

Please open this issue again

_Originally posted by @RST90 in https://github.com/appium/appium/issues/7677#issuecomment-527161888_

**Comment by RST90** [comment]
Selenium: V 3.141.59
Appium:  Appium.WebDriver V 3.0.0.2
Node.js:  10.16.3 (includes npm 6.9.0)

**Comment by mykola-mokhnach** [comment]
I don't understand what the problem has to do with appium server? Selenium grid throws such exception when one tries to invoke a session command with session id, which is not known to the grid and was either destroyed or not created at all.

**Comment by RST90** [comment]
You are right. This issue seems to be related to the selenium grid and not to appium. I was just confused about the ticket #7677 which has been closed for no explicable reason so I decided to create a new issue here. I will close the issue and open a new one in the selenium grid repo.
