### ISSUE TITLE
ios-webkit-debug-proxy can not start on ios 13 beta

### ISSUE THREAD

**Issue by jovana119** [appium/appium#13165]
## The problem

I tried to run tests on real device with **ios 13** and **iwdp can not be started**. This is the error from appium logs:

```
[debug] [iOS] Starting ios_webkit_debug_proxy at port 27753 on device 20576a73a693e36e604b8dbaa7cc9c700ecee270
[iOS] Error: Timed out waiting for ios_webkit_debug_proxy to open
[iOS]     at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[iOS]     at IWDP.errorAndThrow [as start] (/usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/lib/iwdp.js:67:14)
[iOS]     at <anonymous>
[XCUITest] Error: Could not start ios_webkit_debug_proxy server: Timed out waiting for ios_webkit_debug_proxy to open
[XCUITest]     at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[XCUITest]     at XCUITestDriver.errorAndThrow [as start] (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:449:13)
[XCUITest]     at <anonymous>
```

I also tried to start iwdp through terminal with command: 
`ios_webkit_debug_proxy -c 20576a73a693e36e604b8dbaa7cc9c700ecee270:27753 -d`
and I got the error:
```
Unable to connect to 20576a73a693e36e604b8dbaa7cc9c700ecee270
  Please verify that Settings > Safari > Advanced > Web Inspector = ON
```
but I already set **WebInspector=ON and RemoteAutomation=ON**.
Everything works fine on the device with **ios 12.3.1** (same app, same tests, same environment)

## Environment

* Appium version: 1.14.1
* iwdp: 1.8.5
* libimobiledevice: 1.2.1
* iOS: 13.0

Does anybody know what could be the problem?

**Comment by mykola-mokhnach** [comment]
Unfortunately IWDP is beyond our control. You should report the problem to Google, who develops it. However, appium@beta does not rely on IWDP anymore. You could try it.

**Comment by jovana119** [comment]
Thanks, I successfully launched safari with appium@beta but now I have a new problem :)
In my test, I first do something in the mobile app, than go to safari, do something and through url open again the mobile application. The problem is that after returning to the app, I can not do anything like there is no active session. 
I start mobile driver with next capabilities
```
 DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
 desiredCapabilities.setCapability(MobileCapabilityType.DEVICE_NAME, System.getProperty("deviceName"));
 desiredCapabilities.setCapability(MobileCapabilityType.UDID, System.getProperty("deviceUdid"));
 desiredCapabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, System.getProperty("platformVersion"));
 desiredCapabilities.setCapability(MobileCapabilityType.APP, System.getProperty("appFilePath"));
 desiredCapabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, Settings.IOS_AUTOMATION_NAME);
 desiredCapabilities.setCapability("usePrebuiltWDA", true);
 mobileDriver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), desiredCapabilities);
       
```
and safari driver with
```
DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
desiredCapabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
desiredCapabilities.setCapability(MobileCapabilityType.UDID, System.getProperty("deviceUdid"));
desiredCapabilities.setCapability(MobileCapabilityType.DEVICE_NAME, System.getProperty("deviceName"));
desiredCapabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, System.getProperty("platformVersion"));
desiredCapabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "safari");
desiredCapabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, Settings.IOS_AUTOMATION_NAME);
desiredCapabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 5000);
desiredCapabilities.setCapability("wdaLocalPort", 8200);
safariDriver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), desiredCapabilities);
```
After returning to the mobile app,when I try to find some element, I got the error: 
`[iProxy] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}`

I tried also to restart mobileDriver after returning from safari driver with FULL_RESET=false and NO_RESET=true but then I got the error:
`[XCUITest] Error: Couldn't start port forwarding on port 8100. Please provide a different port using 'wdaLocalPort' capability
[XCUITest]     at WebDriverAgent.createIProxy (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/wda/webdriveragent.js:263:13)
[XCUITest]     at <anonymous>`

What I'm doing wrong?

**Comment by jovana119** [comment]
Ok, I found solution. First I quit mobileDriver, then start safariDriver with the same wdaLocalPort 8100. And after opening the app from safari, through url, I swiched the context on safariDriver to NATIVE_APP. 
 and then everything works fine. If there is a nicer solution, please be free to share with me :)

**Comment by mykola-mokhnach** [comment]
> After returning to the mobile app,when I try to find some element, I got the error:
> [iProxy] Connection was refused to port 8100 [WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}

Can you provide the full log for this failure? This might a bug, but we cannot confirm it without the log

**Comment by KazuCocoa** [comment]
- driver1 (mobileDriver) used port 8100
- driver2 (safariDriver) used port 8200

1. Driver1 established a connection with a real device (port 8100)
2. Driver2 established a connection with the device (port 8200)
    - Then, WDA stopped communication with 8100 in order to talk with safariDriver via port 8200
3. Driver1 re-tried to establish a connection with the device via port 8100
    - Then, the issue happened

If so, https://github.com/appium/appium/issues/13127 is.
You set an available port as  `wdaLocalPort` everytime is the easiest way to avoid it. You can configure another way such as https://github.com/appium/appium/issues/13127#issuecomment-525736558 ...

Anyway, your current way is below.

1. Driver1 established a connection with a real device (port 8100)
2. Driver2 established a connection with the device (port 8200)
    - Then, WDA stopped communication with 8100 in order to talk with safariDriver via port 8200
3. Use Driver2 as NATIVE_APP instead of driver1

You can do as below, too:

1. Driver1 established a connection with a real device (port 8100)
2. Driver1 launches Safari like`@driver.activate_app 'com.apple.mobilesafari'` and do actions to it
3. Continue to work with Driver 1

**Comment by jovana119** [comment]
> > After returning to the mobile app,when I try to find some element, I got the error:
> > [iProxy] Connection was refused to port 8100 [WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
> 
> Can you provide the full log for this failure? This might a bug, but we cannot confirm it without the log

Here are the full logs https://gist.github.com/jovana119/17eda7acfb25171affb4d12e2843ba6b

**Comment by mykola-mokhnach** [comment]
It looks like you are trying to open two different parallel sessions on the same device. It won't work and is not supposed to. The next session can only be opened when the previous one has been terminated

**Comment by jovana119** [comment]
@mykola-mokhnach Thanks, I thought that I can have two sessions on different ports.
@KazuCocoa Thanks for the answer. I tried the way as you suggested with only one driver on port 8100, and I successfully open safari, but on getUrl() call, siri is launched and it can not open my url.

**Comment by mykola-mokhnach** [comment]
Check https://appiumpro.com/editions/84 regarding openUrl functionality
Closed as not an issue
