### ISSUE TITLE
[IOS] Issue with loading huge data in Appium

### ISSUE THREAD

**Issue by rajivkrtest** [appium/appium#13160]
There is an issue with Appium during the fetching of entire XML hierarchy when the screen contains large number of elements. Appium hangs while trying to load the huge data (Again need to restart).

For  UITableViewCell , XML is creating huge number of elements inside it (approx. 400 - 500 times staticText), these elements are not mapped to any of the elements on screen. When these elements are loaded leads to memory issue and hang the Appium application.

The type of elements are static text as given below:
 
 <XCUIElementTypeStaticText type="XCUIElementTypeStaticText".>
 
**Test Environment-**
**Device-** iPad Pro/ iPhoneX
**iOS-** 12.4 or below
**Appium Version-** 1.9.1
**Platform–** Objective C
 
Refer the Screen shot of XML attached below
*PFA for Entire XML file
<img width="1028" alt="issue" src="https://user-images.githubusercontent.com/35500421/64035806-4de25e00-cb6f-11e9-9896-1976721e829d.png">
[AppiumIssue.xml.zip](https://github.com/appium/appium/files/3560710/AppiumIssue.xml.zip)

**Comment by mykola-mokhnach** [comment]
- Appium 1.9.1 is out of date, please use the recent version
- The tree elements are returned by xctest. There is no way to reduce the count of elements there. I newer Appium versions there is `mobile: source` endpoint with `description` parameter, which shows the "native" debugDescription string of the application element. It does not completely replace xpath source, but al least allows to see what's on the screen.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by rajivkrtest** [comment]
Thanks Team for the update.
We will update with new Appium, if any issue can we will let you know.
