### ISSUE TITLE
Inability to successfully terminate com.android.settings on Android 9 (Pie)

### ISSUE THREAD

**Issue by Cory-Berg** [appium/appium#13174]
## The problem
The issue cropped up after updating mobile device testing our framework against to Android 9.
Tried again on other devices @ Android 7 & 8 and am not facing the same issue.
We are only testing against Samsung devices.
The main issue is that I see the settings app being terminated - or the instance we launched - however there seems to be a persistent background settings process that the terminateApp is still witnessing running and rightly throws an exception.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.0
* Last Appium version that did not exhibit the issue (if applicable): Unknown
* Desktop OS/version used to run Appium: Mac OS 10.14.6
* Node.js version (unless using Appium.app|exe): 12.8.1
* Npm or Yarn package manager: npm 6.11.1
* Mobile platform/version under test: Android 9
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Details

It appears that in Android 9 a background task for settings is maintained even through a terminate event.

## Link to Appium logs

[Gist](https://gist.github.com/Cory-Berg/f5bc85fa4a4058b9189157f87b2e8129)

## Code To Reproduce Issue [ Good To Have ]

// Note I set it up for the actual device and targeting the same server that was already running
    @Test()
    public void testCreateSession() {
        String activity = driver.currentActivity();
        String pkg = driver.getCurrentPackage();
        Assert.assertEquals(activity, ".ApiDemos");
        Assert.assertEquals(pkg, "io.appium.android.apis");
        
        String settings = "com.android.settings";
        
        driver.activateApp(settings);
        try {
        	driver.terminateApp(settings, new AndroidTerminateApplicationOptions().withTimeout(Duration.ofMillis(10000)));
        } catch (Exception ex) {
        	System.out.println(ex.getMessage());
        	
        }
        driver.activateApp(settings);
    }

**Comment by mykola-mokhnach** [comment]
I don't observe any bugs there - settings app has services, which are supposed to be running in background. What's the point in terminating it?

**Comment by mykola-mokhnach** [comment]
One can also add its identifier to `uninstallOtherPackages`, so then it won't be present on the device at all.

**Comment by mykola-mokhnach** [comment]
I assume the OS simply restarts the process automatically after it is killed or simply denies the request since it is a system process.

**Comment by Cory-Berg** [comment]
The purpose is to remove previous settings context and to have a consistent entry point into the settings app. I posted the issue because previous versions of android have reported a successful termination though not on Android 9.

Is there a different method of launching the settings app to always restore/activate @ the same activity? Particularly on Samsung devices.

**Comment by mykola-mokhnach** [comment]
I don't know such, however Android 9 added many security improvements, so you could observe one of them. BTW, `startActivety` also tries to terminate running instances of the activity, which is going to be executed (`-S` argument)

**Comment by Cory-Berg** [comment]
So utilizing the startActivity I can successfully perform the action I need.
However, I am wondering if this is still an issue if the settings app is being terminated but restarted by the system, is there a way of comparing the task IDs versus checking the list of task names?

**Comment by mykola-mokhnach** [comment]
It is possible in theory, however IMHO, not needed. When one terminates an app then he wants it to not run, does not matter which PID it uses. 

You are welcome to create a PR and add a possibility to verify app termination also by PID.
