### ISSUE TITLE
Unable to get screenshot of an element

### ISSUE THREAD

**Issue by RonKalian** [appium/appium#13172]
## The problem

Failure to get screenshot of an element in Appium.

## Environment

* Appium version (or git revision) that exhibits the issue:  1.13.0 and 1.14.2
* Last Appium version that did not exhibit the issue (if applicable):  1.14.2
* Desktop OS/version used to run Appium:  
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G95
* Node.js version (unless using Appium.app|exe): 10.14.6
* Npm or Yarn package manager:  NPM 6.10.3
* Mobile platform/version under test:  iPhone
* Real device or emulator/simulator:  Real device
* Appium CLI or Appium.app|exe:

## Details

When attempting to get a screenshot of an element I get this in Appium logger:

`An unknown server-side error occurred while processing the command. Original error: Unable to load Atom 'getElementScreenshot' from file '/usr/local/lib/node_modules/appium/node_modules/appium-remote-debugger/atoms/getElementScreenshot.js'`

This is probably same as https://github.com/appium/appium/issues/11094 which was closed.

I think this should be fixed because:

1. In issue #11094 it was mentioned that XCUITest does not support screenshot of an element, however https://developer.apple.com/documentation/xctest/xcuiscreenshot clearly states it is supported.
2. When examining the Mac's `/usr/local/lib/node_modules/appium/node_modules/appium-remote-debugger/atoms` directory, various .js scripts were found, but not `getElementScreenshot.js`.  Curiously, all the scripts names follow underscored `file_name.js` naming convention rather than `camelCase.js`

## Link to Appium logs

Unable to load Atom 'getElementScreenshot' from file '/usr/local/lib/node_modules/appium/node_modules/appium-remote-debugger/atoms/getElementScreenshot.js'

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
You probably want to take element screenshot being in web context. It won't work there. Only native context supports such operation

**Comment by RonKalian** [comment]
@mykola-mokhnach thank you for your reply.  When you say 'native context' do you mean using XCUITest directly?  
Just to clarify, my (Python) code calls `myElement = webdriver.find_elements(By.CLASS_NAME, myClassName)` then attempts to extract the element screenshot from `myElement.screenshot_as_png`.

**Comment by mykola-mokhnach** [comment]
Native context means that Appium proxies commands to WebDriverAgent rather that to the browser agent/remote debugger

**Comment by RonKalian** [comment]
Yes, it is in web context.

**Comment by mykola-mokhnach** [comment]
Inside ios web context Appium interacts with the web browser using selenium web atoms. These atoms don't provide any possibility for taking element screenshots (and I don't think this is possible using using pure java script). However you could still try to create an enhancement request to their repository.

Closed as not an issue.
