### ISSUE TITLE
iOS app stuck in loader screen when launched with appium desktop

### ISSUE THREAD

**Issue by nyk5073** [appium/appium#13170]
**Summary:**
iOS application screen is stuck at loader image. All the contents of the screen is not loading. 

**Basic Info:**
Host machine: Mac mini (Late 2014)
OS: macOS Mojave version: 10.14.6 (18G87)
Appium-desktop version: Version 1.13.0 (1.13.0.20190505.5)
Real device: iPhone XR, iOS ver: 12.2

**Snapshot of the screen where it is stuck have been attached for clarification purpose:**
![LoaderScreen](https://user-images.githubusercontent.com/24378346/64169177-f98cf600-ce6e-11e9-94c6-4e13069fd7ad.png)

Then after a certain time the app response as failed to connect to internet. However, this doesn't happen when the app is launched/used without appium.

The same phenomenon is observed with appium CLI version 1.14.0.

Please let me know if anything else is required for further investigation. Your prompt response will be highly appreciated.

**Comment by mykola-mokhnach** [comment]
the log does not contain any useful information. I would try to add more internal logging into the application under test and compare the log generated by manual and automated tests to figure out what the difference is. Also, there might be some useful traces in the device system log.

**Comment by nyk5073** [comment]
@mykola-mokhnach - I tried with setting showIOSLog desired caps as boolean true in order to get device system log. Unfortunately, my machine hangs/freezes literally once I start the Appium inspector. I have requested my office staff to add more RAM or add a SSD so that this won't happen. I will reach out to you once I have this under control and provide you with the logs you asked in order to help me debug this issue. Your prompt response has been highly appreciated! 🙇

**Comment by mykola-mokhnach** [comment]
Sure, I can keep this ticket open for a while. However I assume it might be some issue with the app itself or the way how xctest interacts with it, which we cannot influence anyway. Try to gather more logs inside the application itself to get more insights on that.

**Comment by nyk5073** [comment]
Hi @mykola-mokhnach - Due to company restrictions and privacy/security policies, I do not have the privilege to share the entire appium log with device logs. However, I was able to successfully fetch the device log and here is the section where it first encountered error:

>  [error] [35m[Xcode][39m 2019-09-04 10:07:14.045327+0600 WebDriverAgentRunner-Runner[4500:1230620] Getting the snapshot timed out after 15 seconds
> [error] [35m[Xcode][39m 2019-09-04 10:07:14.045441+0600 WebDriverAgentRunner-Runner[4500:1230620] Internal error: Error Domain=com.apple.dt.xctest.automation-support.error Code=5 "Error kAXErrorServerNotFound getting snapshot for element <AXUIElementRef 0x1014ddec0> {pid=4508} {uid=[ID:9999 hash:0x3bfa07e906000000]}" UserInfo={NSLocalizedDescription=Error kAXErrorServerNotFound getting snapshot for element <AXUIElementRef 0x1014ddec0> {pid=4508} {uid=[ID:9999 hash:0x3bfa07e906000000]}}
> [error] [35m[Xcode][39m     t =   102.69s Snapshot accessibility hierarchy for app with pid 4503
> [error] [35m[Xcode][39m 
> [error] [35m[Xcode][39m     t =   102.69s Snapshot accessibility hierarchy for app with pid 4503
> [error] [35m[Xcode][39m 

I have seen that people have encountered this issue before. Some link/refs here:
https://github.com/facebookarchive/WebDriverAgent/issues/1074
https://forums.developer.apple.com/thread/44701

Unfortunately, haven't found any way to resolve this. Some said that this occurred mainly on devices with password locks. I have disabled password lock on the device under test and still no luck. Please let me know if any further information you need from the log that I can fetch and paste it here. Any keywords like [error], failed, exception, warning, etc. you'd like me to copy from the log. I can do that and share it with you.

**Comment by mykola-mokhnach** [comment]
I don't think there is anything we can do on Appium side to resolve that. The problem lies on the lower level of xctest communication with the target application. My guess is that the application might block the event loop queue for too long. You can check it with your developers using Xcode profiling tools. 

Closed as third party issue.

**Comment by ssdev1510** [comment]
@nyk5073 I am facing same issue, app got stuck in loader screen.
How did you fix this problem?
Thanks.

**Comment by nyk5073** [comment]
> @nyk5073 @mykola-mokhnach  I am facing same issue, app got stuck in loader screen.
> How did you fix this problem?
> I am using appium 1.17-1
> Using xcode 11.5 for simulator
> Thanks.

@ssdev1510 - couldn't solve it in the end. This was an AUT issue. Unfortunately, the developer won't fix it as its ok without appium. Sorry!

**Comment by ssdev1510** [comment]
@nyk5073 thanks for reply.
Actually i noticed- issue is because of WDA.. as application works fine without WDA in simulator.

**Comment by sriram289** [comment]
@ssdev1510  were you able to find a solution for this am currently facing this issue.  If I make sure at a certain stage there are no commands being executed by WDA (using browser.pause) app loads in absence of the pause the app is stuck.

**Comment by ashisri18** [comment]
@nyk5073 @ssdev1510 @mykola-mokhnach  As this issue is not fixed yet, then what is another way to find locators of an iOS app, because the app is stuck in appium inspector.

**Comment by KazuCocoa** [comment]
(For many HTTP request behavior)
I remember that I observed XCTest/Accessibility framework in iOS tried to resolve its accessibility items in a view at once if the view had table view long before. I mean if the view had 10 cells in a table view (or list view?) and each item had multiple HTTP requests, iOS tried to load all of them via accessibility framework at the same time. Then, all of API calls also occurred. 

This did not happen without loading accessibility items over Appium/XCTest. (in this case, appium could do nothing. Only Apple could change the iOS/Accessibility's behavior)

**Comment by TataSatish** [comment]
m
