### ISSUE TITLE
Xcode 11 iOS 13... No available web pages: Could not connect to a valid app after 20 tries

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#13175]
## The problem

Running WebView tests using runsauce gives RemoteDebugger error `No available web pages: Could not connect to a valid app after 20 tries` (see https://gist.github.com/dpgraham/9837e5c6a2907d6ff8772766391a95f9#file-webview-failure-logs-L744)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15 branch
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac
* Node.js version (unless using Appium.app|exe): 
* Npm or Yarn package manager:
* Mobile platform/version under test: iOS 13.0 (xcode 11 beta)
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Details

Happens consistently. Tested it on my machine as well as on Sadaf's machine.

## Link to Appium logs

https://gist.github.com/dpgraham/9837e5c6a2907d6ff8772766391a95f9#file-webview-failure-logs-L744

## Code To Reproduce Issue [ Good To Have ]

```
git clone https://github.com/saucelabs/runsauce # Only Saucers can do this 
cd runsauce
./bin/runsauce.js -c local -t ios_hybrid -v 13.0 -d "iPhone 8" -a 1.13.0
```

Run it against the appium 1.15 branch with Xcode set to the 11 beta.

**Comment by dpgraham** [comment]
We've observed that the application does open, but that remote debugger keeps hitting that issue.

**Comment by dpgraham** [comment]
When using Xcode 10.3 and running on iOS 12.4, the problem does not occur:

`./bin/runsauce.js -c local -t ios_hybrid -v 12.4 -d "iPhone 8" -a 1.13.0`

**Comment by imurchie** [comment]
Interesting. In all versions the plist gives `com.floatlearning.FLWebView` as the bundle identifier but on iOS 13 the web inspector is saying it is `www.digicert.com.com.floatlearning.FLWebView`, so the mapping does not work.

**Comment by imurchie** [comment]
@dpgraham Can you try with this branch: https://github.com/appium/appium-remote-debugger/tree/isaac-weird-targets

**Comment by MichaelHuyp** [comment]
What is the solution to this problem?
