### ISSUE TITLE
iOS 13 Basic - Viewport screenshot size test fails

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#13187]
## The problem

The test that verifies that a view image has the same height as the viewport is failing. View Image height is 2436. Viewport height is 1704

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/dpgraham/f53c0186f682610ffd90123607ff087f

## Code To Reproduce Issue [ Good To Have ]

Set the Xcode version to 11

```
git clone https://github.com/appium/appium-xcuitest-driver
git checkout -b ios-13 && git pull origin ios-13
export PLATFORM_VERSION=13.0
export DEVICE_NAME="iPhone X"
```

Go to `safari-ssl-e2e-specs.js` and set `should open pages with untrusted certs if the cert was provided in desired capabilities` to `.only`

```
npm run e2e-test
```

**Comment by dpgraham** [comment]
@mykola-mokhnach I think you have familiarity with this, right?

**Comment by mykola-mokhnach** [comment]
Nope, I didn't work on that. This endpoint was implemented by @jlipps

**Comment by KazuCocoa** [comment]
It looks viewportRect does not get the data expectedly.
https://github.com/search?q=org%3Aappium+getViewportRect&type=Code

- Xcode 11 x iOS 13 x  iPhone Xs Max sim x UIKitCalalog
    ```
    "viewportRect"=>{"left"=>0, "top"=>0, "width"=>1242, "height"=>2688}}>
    ```
- Xcode 10.3 x iOS 12.4 x  iPhone Xs Max sim x UICatalog
    ```
   "viewportRect"=>{"left"=>0, "top"=>132, "width"=>1242, "height"=>2556}}>
    ```

https://github.com/appium/appium-ios-driver/blob/fb33c52525ec7e91bffb41072d091008adc2234e/lib/commands/device.js#L13 ?
