### ISSUE TITLE
iOS 13 Basic - gesture test errors

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#13186]
## The problem

Many of the gestures tests aren't passing. Looks like it's a problem with the tests and that it's not properly calling mobile:scroll in between tests (mobile:scroll is used to scroll back to top of pages)

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/dpgraham/5e185700cb1926ad22b3a94e07ca92a8

## Code To Reproduce Issue [ Good To Have ]

Set the Xcode version to 11

```
git clone https://github.com/appium/appium-xcuitest-driver
git checkout -b ios-13 && git pull origin ios-13
export PLATFORM_VERSION=13.0
export DEVICE_NAME="iPhone X"
```

Go to `gesture-e2e-specs.js` and set `XCUITestDriver - gestures` to `.only`

```
npm run e2e-test
```

**Comment by mykola-mokhnach** [comment]
This endpoint has never been very reliaible
