### ISSUE TITLE
iOS 13: web checkbox test is failing

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#13183]
## The problem

Web test "should say whether an input is selected" is failing (see https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=5095)

Looks like it's not clicking the checkbox

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15 branch
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe): 10.16.0
* Npm or Yarn package manager:
* Mobile platform/version under test: iOS 13 Xcode 11 beta 5
* Real device or emulator/simulator: iPhone 8 Simulator
* Appium CLI or Appium.app|exe

## Link to Appium logs

https://gist.github.com/dpgraham/00bcf5595e37048730551e08bf99819f

## Code To Reproduce Issue [ Good To Have ]

Set the Xcode version to 11

```
git clone https://github.com/appium/appium-xcuitest-driver
git checkout -b ios-13 && git pull origin ios-13
export PLATFORM_VERSION=13.0
export DEVICE_NAME="iPhone X"
```

Go to `safari-basic-e2e-specs.js` and set `should say whether an input is selected` to `.only`

```
npm run e2e-test
```

**Comment by umutuzgur** [comment]
It seems like there is a problem with the coordinate translation after we find the checkbox. The click must be happening somewhere else

**Comment by umutuzgur** [comment]
The test works when we set `nativeWebTap` to false in that test

**Comment by sadase** [comment]
I have the similar issue. I am testing a webview of a hybrid iOS application. I used different ways to click the checkbox
- `driver.findElementByCssSelector("#element_id").click();`
- `driver.findElementByCssSelector("input[value='value'][type='checkbox']")`

-	    public void tapByJsDriver(WebElement element) {
		  JavascriptExecutor js = (JavascriptExecutor) driver;
		  
		  int x = element.getLocation().getX();
		  int addition = (int) (element.getSize().height * 0.5);
		  int fx = x + addition;
		  int y = element.getLocation().getY();
		  
		  Map<String, Object> params = new HashMap<>();
		  params.put("x", fx);
		  params.put("y", y);
		  
		  params.put("fingers", 1);
		  params.put("tapCount", 1);
		  params.put("duration", 0.5);
		  
		  js.executeScript("mobile: tap", params);
	    }

The checkbox was found by Appium successfully with status 200 returned but Appium did not click on the checkbox.

Is there any update?

## Environment
- Appium version: 1.16.0-beta1
- macOS: 10.14.6
- Node.js version: 10.16.3
- npm: 6.9.0
- Mobile platform: iOS 13.1.3, Xcode 11.1 (11A1027)
- Real device: iPad Air 2
