### ISSUE TITLE
iOS 13 Web: Cannot execute async javascript (https only)

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#13184]
## The problem

Web test "should execute async javascript" is failing (see https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=5095)

It's timing out after 300 seconds when attempting to execute async javascript on https://www.google.com

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15 branch
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe): 10.16.0
* Npm or Yarn package manager:
* Mobile platform/version under test: iOS 13 Xcode 11 beta 5
* Real device or emulator/simulator: iPhone 8 Simulator
* Appium CLI or Appium.app|exe

## Link to Appium logs

https://gist.github.com/dpgraham/9408966205a928600b4cced5b7505c3e

## Code To Reproduce Issue [ Good To Have ]

Set the Xcode version to 11

```
git clone https://github.com/appium/appium-xcuitest-driver
git checkout -b ios-13 && git pull origin ios-13
export PLATFORM_VERSION=13.0
export DEVICE_NAME="iPhone X"
```

Go to `safari-execute-e2e-specs.js` and set `should execute async javascript` to `.only`

```
npm run e2e-test
```

This will time out after 300 seconds in HTTPS (will not fail for HTTP)

**Comment by mykola-mokhnach** [comment]
is CORS enabled on the server side?

**Comment by imurchie** [comment]
That shouldn't be necessary anymore.

**Comment by imurchie** [comment]
From the looks of things the browser is not sending anything (we should get an OPTIONS request, then a POST, to the async response url).

**Comment by umutuzgur** [comment]
Do we have https on the appium server? Safari might be not sending the CORS request since the appium endpoint is not https

**Comment by imurchie** [comment]
The endpoint is https
```
dbug iOS Response url for executeAsync: https://localhost:8000/wd/hub/session/e29c2474-bad5-4e23-991b-112a3ec555d4/receive_async_response
```

**Comment by umutuzgur** [comment]
So if we can't add a self signed cert to the device, this can't work

**Comment by imurchie** [comment]
Yeah, that's my thinking. I'm going to explore if the cert just needs to be somewhere else for iOS 13

**Comment by imurchie** [comment]
As a workaround a different https server can be used. It just passes the response along to the right thing on Appium.

**Comment by umutuzgur** [comment]
@dpgraham We can consider changing the implementation and returning the responses over the console. This would allow us to use this feature in real devices and we don't need to deal with http and https differences

**Comment by umutuzgur** [comment]
Or use this instead of `Runtime.evaluate` https://github.com/WebKit/webkit/blob/master/Source/JavaScriptCore/inspector/protocol/Runtime.json#L231

**Comment by dpgraham** [comment]
Confirmed fix on latest build: https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=5152

**Comment by Nesaganesh** [comment]
I have installed Appium 1.15 latest and run tests on iOS 13 and I could not fire the Javascript, is the fix merged in to 1.15 ??

**Comment by imurchie** [comment]
@Nesaganesh Yes, it is there.

What is the issue you are having? Can you provide the _full_ Appium server logs, as a link to a [gist](https://gist.github.com)?

**Comment by Nesaganesh** [comment]
https://gist.github.com/Nesaganesh/85b28739ea809a010d97ac9ddcb096eb

**Comment by imurchie** [comment]
Why does this need to be done asynchronously? It looks like's it's just calling a function?

**Comment by imurchie** [comment]
The way the asynchronous JS calls in Selenium work is that a function is added as a final argument, so your script needs to get that, and run it whenever it is done doing whatever it is doing. A simple example would be something like:
```java
JavascriptExecutor js = (JavascriptExecutor) driver; 
String val = (String) executor.executeAsyncScript("" +
            "var done=arguments[0]; " +
            "setTimeout(function() {" +
            "   done('tada');" +
            "}, 10000);");
```

**Comment by Nesaganesh** [comment]
The same code works fine in Appium 1.15 on iOS 12, wanted to know the difference between ios 12 & 13 

string message = "window.postMessage('" + request + "','*');";
((IJavaScriptExecutor)driver).ExecuteScript(message);

**Comment by imurchie** [comment]
Sorry, I just noticed that you aren't actually running it asynchronously.

This issue does not apply. Please open a new issue with all the information that is requested. Otherwise it makes things very difficult to track.

**Comment by Nesaganesh** [comment]
Sure ok Thanks
