### ISSUE TITLE
iOS 13 Basic - Find tests failing

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#13188]
## The problem

find-e2e-specs.js has issues

I think there's some issue with `mobile:scroll` This is another test where we tests are failing because we're using `mobile:scroll` to move to the top of the page and it isn't working.

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/dpgraham/5e185700cb1926ad22b3a94e07ca92a8

## Code To Reproduce Issue [ Good To Have ]

Set the Xcode version to 11

```
git clone https://github.com/appium/appium-xcuitest-driver
git checkout -b ios-13 && git pull origin ios-13
export PLATFORM_VERSION=13.0
export DEVICE_NAME="iPhone X"
```

Go to `find-e2e-specs.js` and set `XCUITestDriver - find` to `.only`

```
npm run e2e-test
```

**Comment by imurchie** [comment]
These logs are not correct for this issue.

**Comment by imurchie** [comment]
Is this using UICatalog.app or UIKitCatalog.app?

**Comment by imurchie** [comment]
I can get these tests to work with UIKitCatalog and some changes to the tests. I will fix them next week, but the functionality remains working (just the app has changed ids and text).

**Comment by dpgraham** [comment]
@imurchie sure thing... shall we just skip it for now and then add it back when we bring in UiKitCatalog again?
