### ISSUE TITLE
UIAutomator2 driver - Instrumentation crash when using xpath locators in activities with specific chars in xml tree.

### ISSUE THREAD

**Issue by Sitheek** [appium/appium#13190]
## The problem
UIAutomator2 driver - Instrumentation crash when using xpath locators in activities with specific chars in xml tree.

I/System.out( 5372): Calling by::className:YpzYu  MethodName:b
F/art     (18983): art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: il
legal start byte 0xf0
F/art     (18983): art/runtime/check_jni.cc:65]     string: '­čôĚ Wykaz za┼é─ůcznik├│w'
F/art     (18983): art/runtime/check_jni.cc:65]     in call to NewStringUTF
F/art     (18983): art/runtime/check_jni.cc:65]     from java.lang.String org.apache.harmony.xml.ExpatAttributes.getValu
eByIndex(long, int)

## Environment

* Appium version  - tested on versions from  1.12.0 to 1.14.2
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Win7, Win10
* Node.js version (unless using Appium.app|exe): v10.16.2
* Npm or Yarn package manager: npm 6.11.3
* Mobile platform/version under test: 5.1.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: CLI

## Details

I am trying to change standard uiautomator driver to new uiautomator2 driver in order to run tests in paralel. 
We have two types of devices. 

- old : HUAWEI M2-A01L ; android : 5.1.1
- new : Huawei BAH2-L09 ; android : 8.0.0

There are no problems on new devices.

Tests crashes on old devices during "by xpath" element location.
logcat error:

I/System.out( 5372): Calling by::className:YpzYu  MethodName:b
F/art     (18983): art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: il
legal start byte 0xf0
F/art     (18983): art/runtime/check_jni.cc:65]     string: '­čôĚ Wykaz za┼é─ůcznik├│w'
F/art     (18983): art/runtime/check_jni.cc:65]     in call to NewStringUTF
F/art     (18983): art/runtime/check_jni.cc:65]     from java.lang.String org.apache.harmony.xml.ExpatAttributes.getValu
eByIndex(long, int)

## Link to Appium logs
https://gist.github.com/Sitheek/4880f3fbfe2fd56e631ab821372103ed

## Android logcat
https://gist.github.com/Sitheek/02c69af331d6af550fab2df89400f45d

##XML Dump
https://gist.github.com/Sitheek/e84bf47dd09bee8d943697c5962ea7b7

## Code To Reproduce Issue [ Good To Have ]

All you need is to have element with text such as:
:camera: Wykaz załączników
:eyeglasses: Regulamin usługi
:writing_hand: Umowa o Świadczenie Usług Telekomunikacyjnych

with non standard characters in text in yours activity and then call "find by xpath"

**Comment by mykola-mokhnach** [comment]
Sorry, there is nothing to do here without the server log and logcat output

**Comment by mykola-mokhnach** [comment]
Also, for Android 5.1/5.0 internal errors with UIA2 might be expected. This framework is only considered stable on Android 6+. For Android5 you can still use the old UIA1

**Comment by Sitheek** [comment]
OK, I will attach logs and logcat

**Comment by Sitheek** [comment]
Ok, I have been testing this for some time, and i think I know what causes this issue. I have updated description and attached logs.

**Comment by mykola-mokhnach** [comment]
As you can see there the crash happens inside standard Android lib and there is nothing much we can do on Appium side. You can try to either avoid xpath usage or avoid unicode characters to be present in the request string. See for example https://stackoverflow.com/questions/12127817/android-ics-4-0-ndk-newstringutf-is-crashing-down-the-app

**Comment by Sitheek** [comment]
Old Uiautomator driver does not use instrumentation to query xpath?

**Comment by mykola-mokhnach** [comment]
I assume the problem lies in smiles - JNI simply does not properly handle character codes like the first one in `"&#128247; Wykaz załączników"` string.

**Comment by mykola-mokhnach** [comment]
I would say simply use UiAutomator1 on Android5 and UIA2 on newer devices.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by shopexdream** [comment]
I would say simply use UiAutomator1 on Android5 and UIA2 on newer devices.

let me try
