### ISSUE TITLE
Grouped Tableview Headers Elements Inconsistent Throughout List

### ISSUE THREAD

**Issue by ajschwieterman** [appium/appium#13198]
## The problem

Appium will display some elements correctly that are in a custom header object for a grouped tableview.  But as I scroll down through the list, I cannot find the necessary elements in the header anymore; the elements changed from XCUIElementTypeStaticText to XCUIElementTypeOther.  I'm using the Appium Desktop Client to inspect these elements.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.14.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS v10.14.6
* Node.js version (unless using Appium.app|exe): v11.4.0
* Npm or Yarn package manager: v6.9.0
* Mobile platform/version under test: iOS v12.4.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium.app

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Appium Logs - https://gist.github.com/ajschwieterman/5e7ad354aeed4e5fa45ffd570d987d19
iOS Page Source - https://gist.github.com/ajschwieterman/02aec05b8e093203d2e64eba5f4b277a

**Comment by mykola-mokhnach** [comment]
Appium simply reflects what it gets from xctest. Consider reporting the problem to Apple

**Comment by mykola-mokhnach** [comment]
Unfortunately, there is nothing to do here from Appium side. Closed as third party issue.
