### ISSUE TITLE
why I can't find 'startIWDP' in doc of caps.md?

### ISSUE THREAD

**Issue by zhiyuan411** [appium/appium#13191]
why I can't find 'startIWDP' in [/docs/en/writing-running-appium/caps.md](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md)?
any other caps is not in the list? How can I know it?

**Comment by mykola-mokhnach** [comment]
The capability has been removed from the doc as it is not needed anymore since Appium@1.15, which is currently in beta stage

**Comment by zhiyuan411** [comment]
thx for that
