### ISSUE TITLE
"--allow-insecure=adb_shell" doesn't work with Appium 1.14.X

### ISSUE THREAD

**Issue by nkgwj** [appium/appium#13193]
( Please excuse me for my poor English.)

## The problem

The release note of Appium 1.14.0 stated a new server flag `--allow-insecure` is now supported.
but `--allow-insecure=adb_shell` doesn't work correctly with Appium 1.14.X.
if you try to execute adb shell commands in test scripts, it throws exceptions.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.0-1.14.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macos 10.14, ubuntu
* Node.js version (unless using Appium.app|exe): v12.4.0 
* Npm or Yarn package manager: npm 6,11.3
* Mobile platform/version under test: Android 9
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Details

The cause of this issue is that `package.json` in this appium repository was not updated properly and an old version of `appium-android-driver`  which doesn't support yet `--allow-insecure`, is used by accident.
 
The specific version of `appium-android-driver` which is used with Appium 1.14.0 is stated in 
`npm-shrinkwrap.json`.

https://github.com/appium/appium/blob/v1.14.0/npm-shrinkwrap.json#L1504
>>>
    "appium-android-driver": {
      "version": "4.16.3",
>>

so, version 4.16.3 of `appium-android-driver` is used, but it doesn't support `--allow-insecure`. 

The following commit are not included until version 4.17.0, so it means version 4.17.0 or later is required to support `--allow-insecure` and `package.json` should be updated accordingly

https://github.com/appium/appium-android-driver/commit/ebb5efa71dd3fc0a3ef00c5e34f6970f9398fb54#diff-9f51169c22f167a6d3ae9cdddfa7ef98

## Link to Appium logs

`selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Appium server must have relaxed security flag set in order to run any shell commands`

## Code To Reproduce Issue [ Good To Have ]

Step 1. Launch appium 1.14.X with `--allow-insecure=adb_shell` server flag.

`$ appium --allow-insecure=adb_shell`

Step 2. Try to execute adb shell command in a test script.

 (Python3)
`self.driver.execute_script('mobile: shell', {'command': ' getprop ro.product.model'})`

**Comment by mykola-mokhnach** [comment]
Yes, you need to use appium@beta in order to have this feature enabled.

1.14.1 and 1.14.2 are hot fixes for 1.14.0 and don't bump the module versions

**Comment by nkgwj** [comment]
Thanks for quick response.

Then what this means?
> https://github.com/appium/appium/releases/tag/v1.14.0
> --allow-insecure and --deny-insecure server flags are added to deprecate --relaxed-security in the future releases #12778. Please check the documentation for further information`

Does it means "new flags are added but you must not use those flags because it's not supported yet"?

I can't find that kind of description in the linked document.
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/security.md

Will `--allow-insecure` be supported in v1.15.0?

**Comment by mykola-mokhnach** [comment]
The documentation simply includes the list of GitHub commits. At this point of time when 1.14 the implementation was done for base components, but not for all drivers. 1.15 does include the whole implementation in all the affected modules

**Comment by KazuCocoa** [comment]
Yes, some modules have not fully supported the flag yet in 1.14.0.
You can try it out with `appium@beta`
