### ISSUE TITLE
Appium luse page resource 

### ISSUE THREAD

**Issue by FirstAM** [appium/appium#13197]
## The problem

Sometimes Appium cant parse screen . At first i thinked is this bag with element id , but when i debuged this part i saw what appium cant find page resource when i run command get_resource

All resource screen what i get after command 

```
<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
<hierarchy index="0" class="hierarchy" rotation="0" width="1440" height="2712">
  <android.widget.FrameLayout index="0" package="com.mem.app" class="android.widget.FrameLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,0][1440,2712]" displayed="false" />
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.0
* Last Appium version that did not exhibit the issue (if applicable): ~
* Desktop OS/version used to run Appium: Linux Ubuntu 
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator: Google Pixel 2Xl real 
* Appium CLI or Appium.app|exe: appium node 

## Link to Appium logs
[
[appium_logs__89 .txt](https://github.com/appium/appium/files/3584417/appium_logs__89.txt)

**Comment by mykola-mokhnach** [comment]
The screen source is returned by UiAutomator2 framework itself, so there is nothing we can do on Appium side. You could try Espresso as well - perhaps it works better

**Comment by mykola-mokhnach** [comment]
Closed as third party issue.
