### ISSUE TITLE
Executing command 'getWindowHandles' Encountered internal error running command: NotImplementedError: Method is not implemented

### ISSUE THREAD

**Issue by fdPoornima** [appium/appium#13195]
## The problem

Executing command 'getWindowHandles' throws error Encountered internal error running command: NotImplementedError: Method is not implemented.

This is happening after upgrading to appium 1.14.0

## Environment

* Appium version 1.14.0
* Last Appium version that did not exhibit the issue (if applicable): 1.11
* Desktop OS/version used to run Appium: Mac
* Node.js version (unless using Appium.app|exe):v8.11.2
* Npm or Yarn package manager:npm
* Mobile platform/version under test: ios
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: appium cli

## Details

Automating a hybrid ios app, and had the below method to switch to different windows when the window handles changes in the app, this used to work till July end when I last tested it, appium version was 1.11 then. This week I upgraded to v 1.14.0 and now the method AppiumDriver.getWindowHandles() is throwing error

## Link to Appium logs

https://gist.github.com/fdPoornima/23289a0ce8551757885e647a5aa945c5

## Code To Reproduce Issue [ Good To Have ]

    protected void switchtoNextWindow() {
        for (int i = 0; i < 3; i++) {
            try {
                Set windowHandles = driver.getWindowHandles();
                String windowHandle = driver.getWindowHandle();
                if (windowHandles.toArray()[0].toString().equals(windowHandle)) {
                    driver.switchTo().window(windowHandles.toArray()[1].toString());
                } else {
                    driver.switchTo().window(windowHandles.toArray()[0].toString());
                }
            } catch (ArrayIndexOutOfBoundsException | org.openqa.selenium.WebDriverException webDriverException) {
                log.info("Web View not loaded yet");
                driver.manage().timeouts().implicitlyWait(Constants.DEFAULT_WAIT_TIME, MICROSECONDS);
            }
        }
    }

**Comment by mykola-mokhnach** [comment]
can you please attach the full server log? Are you calling this command from web context?

**Comment by fdPoornima** [comment]
sure, will attach. No, I am calling this from a native context. 

- In Native Context
- Click on a hamburger menu button
- try to identify an element inside the hamburger menu -  which does not identify
- so, try to switch window

**Comment by mykola-mokhnach** [comment]
This command will only work from web context, so the error above is expected

**Comment by fdPoornima** [comment]
Ah, I see. Thanks for confirming @mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
