### ISSUE TITLE
Incorrect package and activity. Retrying.

### ISSUE THREAD

**Issue by shivakrishnach31** [appium/appium#13196]
## The problem
My app is getting installed on the phone but driver session is not starting.
Getting below error:

```
Possible activities, to be checked: 'com.mycompany.app.video.SplashActivity', 'com.mycompany.app.video.com.mycompany.app.video.SplashActivity'
[ADB] Getting focused package and activity
[ADB] Running 'C:\Users\chippas\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 192.168.1.23\:5555 shell dumpsys window windows'
[ADB] Found package: 'com.android.systemui' and fully qualified activity name : 'com.android.systemui.usb.UsbPermissionActivity'
[ADB] Incorrect package and activity. Retrying
```

Let me explain you a little bit about my app and it's launching mechanism.
My App is an audio and video recording app with needs access to Mic, File manager, Camera, and Calls.  The Launch and MainActivity of the app is SplashScreen.
So, Whenever the app launched, it launches with SplashScreen and on top of that view the required access permissions alert displays. As we have autoGrantPermissions capability, I have set it to 'true'. So, automatically I have allowed the app to access those four(Camera, File Mangar, Calls, Mic). But there is another access required alert for USB permission. So After launching the app we can only USB permissions alert on the screen. With this launching mechanism, I never faced any issues. 

But recently they changed Splash screen launching behavior. Previously they used the Handler with delay for Splash screen. Now it has been changed to native Android Splash Theme. 

After this change, the Splash screen is showing only for less time(less than a second).
So now by the time USB permission alert displayed the Splash screen is disappeared from the stack. But Appium is still searching for Splash screen as MainActivity.
Please let me know is this an issue from Appium Side? Or Something which we can do from the development side.

Capabilities Used:

```
{
  "platformName": "Android",
  "platformVersion": "9",
  "deviceName": "192.168.1.27:4444",
  "app": "C:\\Users\\chippas\\Documents\\MyCompany.apk",
  "appWaitDuration": 0,
  "automationName": "uiautomator2",
  "autoGrantPermissions": true
}
```

## Environment

* Appium version (or git revision) that exhibits the issue: v1.14.2 and v1.11.1
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): v8.11.3
* Npm or Yarn package manager: 5.6.0
* Mobile platform/version under test: Samsung Galaxy S8+(8.0.0) and Galaxy S10+(9)
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI- 1.14.2 & Appium-Desktop-1.11.1

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
https://gist.github.com/shivakrishnach31/6b36f1dccd2734d02ccc367ce4faf248

**Comment by mykola-mokhnach** [comment]
> [MJSONWP] Encountered internal error running command: Error: Cannot start the 'com.MyCompany.app.video' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: 'com.MyCompany.app.video.SplashActivity' or 'com.MyCompany.app.video.com.MyCompany.app.video.SplashActivity' never started. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting


Have you checked the troubleshooting link ^ ?

**Comment by shivakrishnach31** [comment]
Hi @mykola-mokhnach - Yes I tried before creating this issue. In that case also I have seen this issue happening.

**Comment by mykola-mokhnach** [comment]
What exactly did you try?

**Comment by shivakrishnach31** [comment]
I have added appWaitPackage, appWaitActivity, and appWaitDuration capabilities with "com.MyCompany.app.video", "com.MyCompany.app.video.SplashActivity", and 100 respectively. Why I reducted appWaitDuration was Splash screen is not showing more than half a second(I guess it's less than that) while opening the app. I tried using 'com.MyCompany.app.*' and 'com.MyCompany.* and 'com.android.systemui' and 'com.android.systemui.usb.UsbPermissionActivity' also for 'appWaitActivity'. In these situations, I got the same error.
And when I try to launch the App by starting a session from Appium Desktop by setting these capabilities I got an error like 'com.MyCompany.app.video.SplashActivity' never started. But it started and disappeared quickly.

Please let me know if you need further information.

**Comment by mykola-mokhnach** [comment]
Try to wait for activity, which is really active rather that waiting for the splash screen

**Comment by shivakrishnach31** [comment]
I tried that as well. I have provided appWaitActivity as 'com.android.systemui.usb.UsbPermisssionActivity', which is active on the screen. But got the same error.

**Comment by mykola-mokhnach** [comment]
have you also provided package name to wait to?

**Comment by shivakrishnach31** [comment]
I didn't provide the appPackage name as I am installing and launching the app not launching the existing app.

**Comment by mykola-mokhnach** [comment]
I'm talking about appWaitPackage

**Comment by shivakrishnach31** [comment]
Yes, I have provided. I have tried ''com.android.systemui.usb.UsbPermisssionActivity',  'com.MyCompany.app.video' and  'com.MyCompany.app.*' one after another. None of these work.

**Comment by mykola-mokhnach** [comment]
Although the log says the focused package is `com.android.systemui`

**Comment by shivakrishnach31** [comment]
I didn't add that as I have focused only on the waitActivity.
Now I have added waitAppPackage as you mentioned and it started working. Thank you a lot for replying quickly and helping in fixing the issue.
But here I have once the question, Will script fail again if this alert is not displayed on the screen?

**Comment by mykola-mokhnach** [comment]
yes it will. The script must know which activity (and package) it should wait for.
