### ISSUE TITLE
iOS 13   checkbox  property "value" always return as 0

### ISSUE THREAD

**Issue by bearxc** [appium/appium#13192]
iOS 13 /beta 6

appium server : master branch

 driver.findElementById("switchId").getAttribute("value")  always return as 0  , no matter the switch has been selected or not . 

driver.getPageSource()   return correct info .

**Comment by mykola-mokhnach** [comment]
I don't think such report is somehow useful to address the problem. Works on my machine though

**Comment by bearxc** [comment]
I missed important info.

app: build on xcode 11 beta 6/7
simulator : iOS 12.2 
appium server: master branch


I build app on  xcod

**Comment by bearxc** [comment]
this issue  can  not reproduce on iOS 13 simulators .

**Comment by mykola-mokhnach** [comment]
I tend to think this is a regression issue in xcuitest itself

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
