### ISSUE TITLE
Pixel Android 10 - Unable to create a new remote session when appWaitActivity set

### ISSUE THREAD

**Issue by lubshilk** [appium/appium#13205]
## The problem

After we upgraded  Android version from 9 to 10 on Pixel tester, began to receive error when trying to get application up: "Unable to create a new remote session... Original error: 'com.cellact.secnum.*' or 'com.cellact.secnum.com.cellact.secnum.*' never started"

The capabilities we set:
> platformName: android
>  appActivity: com.cellact.secnum.activity.MainActivity
>  appPackage: com.cellact.secnum
>  appWaitActivity: com.cellact.secnum.*
>  autoGrantPermissions: true
>  automationName: UIAutomator2
>  deviceName: num2_1
>  fullReset: false
>  newCommandTimeout: 0
>  noReset: true
>  platformVersion: 10

When capability appWaitActivity removed, no problem reported and session created 

We didn't experience such a problem on devices with lower Android versions 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.2
* Desktop OS/version used to run Appium: MAC OS Mojave 10.14.3
* Mobile platform/version under test: Android 10
* Real device

## Link to Appium logs

https://gist.github.com/lubshilk/8564eb11deb2db624c0a62ad3bc99b13

**Comment by mykola-mokhnach** [comment]
> 2019-09-08 16:27:27:446 [ADB] Found package: 'com.google.android.permissioncontroller' and fully qualified activity name : 'com.android.packageinstaller.permission.ui.GrantPermissionsActivity'

Have you checked what is shown on the screen after the app is started? It looks like there is some unexpected permission dialog

**Comment by lubshilk** [comment]
I'll check and let you know. Thanks

**Comment by lubshilk** [comment]
Yes, you are right. There was permission pop-up. Thanks
