### ISSUE TITLE
scrollIntoView issue with Table view using Appium 1.1.4.0 iOS 12.x

### ISSUE THREAD

**Issue by sujnatj** [appium/appium#13200]
## The problem

We are facing weird issue where the elementID in the below implementation is returned wrongly. Hence always either wrong cell is clicked or it just tries to scroll beyond the list and times out.

   HashMap<String, String> scrollObject = new HashMap<>();
      scrollObject.put("simpleIsVisibleCheck", "true");
            if (element instanceof WrapsElement) {
                WebElement targetElem = ((WrapsElement) element).getWrappedElement();
                scrollObject.put("element", ((RemoteWebElement)targetElem).getId());
            } else {
                scrollObject.put("element", ((RemoteWebElement)element).getId());
            }
            scrollObject.put("toVisible", "not an empty string");
            executeScript("mobile: scroll", scrollObject);

Is there any work around for this issue?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.0
* Last Appium version that did not exhibit the issue (if applicable):1.9.1
* Desktop OS/version used to run Appium:iOS 12.x
* Real device or emulator/simulator:Real device + Simulator

**Comment by mykola-mokhnach** [comment]
The `mobile: scroll` endpoint is not reliable. Consider using small swipes in a loop instead. See https://github.com/appium/appium/issues/13038 for more details.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
