### ISSUE TITLE
Appium CLI crashed with memory leak: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by eyalpartner** [appium/appium#13207]
## The problem
Appium CLI seems to crash every few minutes,
it reproduce all the time

## Environment
*OS Ubuntu 18.04.3 TLS
* Appium CLI version: 1.14.2
* Node version: 12.10.0
* Npm: 6.10.3
* Mobile platform/version under test: Android 7.0
* Real Device

## Details
F<-A-T-A LL aEsRtR OfRe:w  CGACLsL _-A-N-D>_

R[E3T0R2Y3_:L0AxS2Tf fA1l6l3o0c]a t i1o0n6 4f0a8i8l emds :-  MJaarvka-Sscwreieppt  h2e0a4p3 .o1u t( 2o0f6 1m.e4m)o r-y>
 2043.1 (2054.4) MB, 18.3 / 0.0 ms  (average mu = 0.592, current mu = 0.001) last resort GC in old space requested
[3023:0x2ff1630]  1064109 ms: Mark-sweep 2043.1 (2054.4) -> 2043.0 (2054.4) MB, 20.5 / 0.0 ms  (average mu = 0.432, current mu = 0.001) last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x11078d400919 <JSObject>
    0: builtin exit frame: byteLength(aka byteLengthUtf8)(this=0x37c5e6fed259 <Object map = 0x1668cbf23cc9>,0x17a8456d8549 <Very long string[699469]>,0x37c5e6fed259 <Object map = 0x1668cbf23cc9>)

    1: fromStringFast(aka fromStringFast) [0x37c5e6fea891] [buffer.js:~385] [pc=0x1bb87d18271f](this=0x08caf49c04d1 <undefined>,0x17a8456d8549 <Very long string[699469]>,0x37c5e6fed259 <Object map = 0x...

 1: 0x9bcb80 node::Abort() [/usr/local/bin/node]
 2: 0x9bdd16 node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0xb1948e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0xb19809 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0xcca1f5  [/usr/local/bin/node]
 6: 0xcd9aed v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 7: 0xca9047 v8::internal::Factory::NewRawTwoByteString(int, v8::internal::AllocationType) [/usr/local/bin/node]
 8: 0xedb5f5 v8::internal::String::SlowFlatten(v8::internal::Isolate*, v8::internal::Handle<v8::internal::ConsString>, v8::internal::AllocationType) [/usr/local/bin/node]
 9: 0xb1806f v8::internal::String::Flatten(v8::internal::Isolate*, v8::internal::Handle<v8::internal::String>, v8::internal::AllocationType) [/usr/local/bin/node]
10: 0xb2ca09 v8::String::Utf8Length(v8::Isolate*) const [/usr/local/bin/node]
11: 0x99a6b9  [/usr/local/bin/node]
12: 0xb8466c  [/usr/local/bin/node]
13: 0xb86477 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
14: 0x134e979  [/usr/local/bin/node]
If necessary, describe the problem you have been experiencing in more detail.

**Comment by eyalpartner** [comment]
Happens also now in appium latest Beta:

FA<T-A-L-  ELRaRsOtR :f eCwA LGLC_sA N-D-_-R>E
T
R[Y2_7L8A1S3T: 0Axl3ldoacba7t4i0o]n   f1a0i0l0e6d9 2-  mJsa:v aMSacrrki-pstw eheepa p2 0o4u3t. 4o f( 2m0e6m1o.r7y)
 -> 2043.3 (2054.7) MB, 16.1 / 0.0 ms  (average mu = 0.553, current mu = 0.001) last resort GC in old space requested
[27813:0x3dab740]  1000712 ms: Mark-sweep 2043.3 (2054.7) -> 2043.2 (2054.7) MB, 19.9 / 0.0 ms  (average mu = 0.386, current mu = 0.001) last resort GC in old space requested


<--- JS stackt ra1c:e  0-x-9-b>c
b
8=0= =n=o dJeS: stack trace =========================================

Security context: 0x3e94a6240919 <JSObject>
    0: builtin exit frame: byteLength(aka byteLengthUtf8)(this=0x3520f1fed541 <Object map = 0x212498423cc9>,0x272380ff85e9 <Very long string[748353]>,0x3520f1fed541 <Object map = 0x212498423cc9>)

    1: fromStringFast(aka fromStringFast) [0x3520f1feab79] [buffer.js:~385] [pc=0x3e917fe2d3bf](this=0x1cdbc02c04d1 <undefined>,0x272380ff85e9 <Very long string[748353]>,0x3520f1fed541 <Object map = 0x...

:Abort() [/usr/local/bin/node]
 2: 0x9bdd16 node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0xb1948e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0xb19809 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0xcca1f5  [/usr/local/bin/node]
 6: 0xcd9aed v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 7: 0xca9047 v8::internal::Factory::NewRawTwoByteString(int, v8::internal::AllocationType) [/usr/local/bin/node]
 8: 0xedb5f5 v8::internal::String::SlowFlatten(v8::internal::Isolate*, v8::internal::Handle<v8::internal::ConsString>, v8::internal::AllocationType) [/usr/local/bin/node]
 9: 0xb1806f v8::internal::String::Flatten(v8::internal::Isolate*, v8::internal::Handle<v8::internal::String>, v8::internal::AllocationType) [/usr/local/bin/node]
10: 0xb2ca09 v8::String::Utf8Length(v8::Isolate*) const [/usr/local/bin/node]
11: 0x99a6b9  [/usr/local/bin/node]
12: 0xb8466c  [/usr/local/bin/node]
13: 0xb86477 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
14: 0x134e979  [/usr/local/bin/node]

**Comment by mykola-mokhnach** [comment]
this native traceback is not helpful at all. Please attach the heap snapshot

**Comment by eyalpartner** [comment]
I enable the flag appium --enable-heapdump
How can I take the heapdump ?

**Comment by mykola-mokhnach** [comment]
Since Node12 you can use `--heapsnapshot-signal` CLI option. Check https://github.com/nodejs/node/blob/master/doc/api/cli.md for more details. The snapshot should be taken when memory usage is close to its high limit

**Comment by eyalpartner** [comment]
Still can't understand how can I get the heap dump....
This is very complicated

**Comment by eyalpartner** [comment]
Seems that using the:
Map<String, Object> ADB = ImmutableMap.of("command", "logcat -d", "args", adb);
         String AA = (String) this.driver.executeScript("mobile: shell", ADB);

Cause the memory leak, I called it in a while loop in new Thread to monitor errors in real time from the LogCat, So I replace it with String builder and it seems to be solved, I won't use it anymore...

Thanks
