### ISSUE TITLE
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl1996625501.tmp/base.apk

### ISSUE THREAD

**Issue by ksezen59** [appium/appium#13211]
I have downloaded selendroid test app from selendroid "Getting Started" page and executed the command below.

http://selendroid.io/setup.html

java -jar selendroid-standalone-0.17.0-with-dependencies.jar -app selendroid-test-app-0.17.0.apk

When I try to start a session with the capabilities described below for Android, a problem occurs like 

"An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/Users/digitaloffice/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pm install /data/local/tmp/appium_cache/4da9c5f551680f303c4499bbf3116f818a9beee9.apk' exited with code 1'; Stderr: 'Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl1996625501.tmp/base.apk: Attempt to get length of null array]'; Code: '1'"

{
  "platformName": "Android",
  "platformVersion": "7.0",
  "deviceName": "Nexus 5 API 24",
  "app": "//Users/DigitalOffice/Downloads/selendroid-test-app-0.17.0.apk"
}

## Environment

* Appium v1.13.0
* Mobile platform/version under test: selendroid-test-app-0.17.0.apk

Appium log link : https://gist.github.com/ksezen59/f3da104bf84bb90ddf919060127cc399

**Comment by imurchie** [comment]
This is a problem with Selendroid, not Appium.

And the logs are for and Appium session using XCUITest driver for an Android app? What is it that you are trying to do?

**Comment by ksezen59** [comment]
I am trying to see If I have right configurations fo my Appium infrastructure. I have successfully
done the same thing on Windows but the operation fails on Mac with this problem.

When I add the capability automationName as "XCUITest", it looks for platform and device based on iOS. After deleting automationName, I can get that error.

I couldn't understand what you mean with "And the logs are for and Appium session using XCUITest driver for an Android app?"

**Comment by imurchie** [comment]
I mean the logs you posted (https://gist.github.com/ksezen59/f3da104bf84bb90ddf919060127cc399) are trying to start an iOS test, using the xcuitest framework.

And the original problem is explained as from running the Selendroid server, which is not an Appium problem.

Can you provide the **Appium** server logs where this happens? As a link to a (gist)[https://gist.github.com]?

**Comment by ksezen59** [comment]
When I added automation name as "UIAutomator2", It worked fine only for 1 time and the problem started to occur again.

Since I am a beginner to those kinda things, how can I reach Selenium log files?

**Comment by imurchie** [comment]
The Appium logs are the ones that print out when you're running the server. You posted some at https://gist.github.com/ksezen59/f3da104bf84bb90ddf919060127cc399. They just happen to be the _wrong_ ones, where the problem you're describing does not happen.

**Comment by ksezen59** [comment]
I really don't get it. After writing the comment 25 mins ago, I have done the same thing and it has opened. You can see here : 
<img width="1262" alt="Screen Shot 2019-09-09 at 7 12 30 PM" src="https://user-images.githubusercontent.com/32410200/64547747-f80f7200-d335-11e9-9738-d77d5f4c0236.png">
 

Capabilities :
{
  "platformName": "Android",
  "platformVersion": "7.0",
  "deviceName": "Nexus 5 API 24",
  "automationName": "UIAutomator2",
  "app": "//Users/DigitalOffice/Downloads/selendroid-test-app-0.17.0.apk"
}

**Comment by imurchie** [comment]
I can no longer tell if you're having this problem or not. Or even what the problem is.
