### ISSUE TITLE
Appium v1.13.0 with WinAppDriver (v1.1) - UI Session Inspector - Startup Error

### ISSUE THREAD

**Issue by peteferraro** [appium/appium#13210]
## The problem

I am running Appium v1.13.0 with WinAppDriver (v1.1) - UI Session Inspector - Startup Error,  When I start my session, the application launches fine then hangs.    I am using "Automatic Server".  The Appium log shows:

--- Error ----------------------------------------
[WinAppDriver] [STDOUT] {"status":9,"value":{"error":"unknown command","message":"Command not recognized: POST: /session/33898E20-0F12-49BD-9022-F805DDDBCA58/context"}}
[WD Proxy] Got an unexpected response: {"status":9,"value":{"error":"unknown command","message":"Command not recognized: POST: /session/33898E20-0F12-49BD-9022-F805DDDBCA58/context"}}
[MJSONWP (cba3ed74)] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: 404 - {"status":9,"value":{"error":"unknown command","message":"Command not recognized: POST: /session/33898E20-0F12-49BD-9022-F805DDDBCA58/context"}}
[MJSONWP (cba3ed74)]     at JWProxy.proxy (C:\Users\pferraro\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:181:13)
[W3C] Matched W3C error code 'unknown command' to UnknownCommandError
--------------------------------------------------

More logs:

info] [35m[WinAppDriver][39m [STDOUT] 
[info] [35m[WinAppDriver][39m [STDOUT] 
[info] [35m[WinAppDriver][39m [STDOUT] ==========================================
[info] [35m[WinAppDriver][39m [STDOUT] POST /wd/hub/session/33898E20-0F12-49BD-9022-F805DDDBCA58/context HTTP/1.1
[info] [35m[WinAppDriver][39m [STDOUT] Accept: application/json, */*
[info] [35m[WinAppDriver][39m [STDOUT] Connection: close
[info] [35m[WinAppDriver][39m [STDOUT] Content-Length: 21
[info] [35m[WinAppDriver][39m [STDOUT] Content-Type: application/json; charset=utf-8
[info] [35m[WinAppDriver][39m [STDOUT] Host: 127.0.0.1:4724
[info] [35m[WinAppDriver][39m [STDOUT] User-Agent: appium
[info] [35m[WinAppDriver][39m [STDOUT] 
[info] [35m[WinAppDriver][39m [STDOUT] {"name":"NATIVE_APP"}
[info] [35m[WinAppDriver][39m [STDOUT] ### WinAppDriver::CommandHandler::Session::HandleCommandAsMidPoint - Command context is not recognized
[info] [35m[WinAppDriver][39m [STDOUT] HTTP/1.1 404 Not Found
[info] [35m[WinAppDriver][39m [STDOUT] Content-Length: 144
[info] [35m[WinAppDriver][39m [STDOUT] Content-Type: application/json
[info] [35m[WinAppDriver][39m [STDOUT] 

## Environment

* I am running Appium v1.13.0 with WinAppDriver (v1.1)
* Last Appium version that did not exhibit the issue (if applicable): unknown
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): ???
* Npm or Yarn package manager: ???
* Mobile platform/version under test: Not used.
* Real device or emulator/simulator: ????
* Appium CLI or Appium.app|exe: v1.13.0

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/peteferraro/eb370e4c9797f113609e52231525c225

## Code To Reproduce Issue [ Good To Have ]

{
  "platformName": "Windows",
  "deviceName": "WindowsPC",
  "app": "C:\\Program Files (x86)\\Allscripts Sunrise\\Helios\\8.4\\Gateway\\UIShell.exe",
  "appWorkingDir": "C:\\Program Files (x86)\\Allscripts Sunrise\\Helios\\8.4\\Gateway\\"
}

**Comment by mykola-mokhnach** [comment]
Context switching is not implemented for Windows driver. Consider creating a feature request to Microsoft
