### ISSUE TITLE
Appium 1.13.0 run very slow with my application IOS

### ISSUE THREAD

**Issue by HoLeAnh** [appium/appium#13219]
## The problem

Appium 1.13.0 run very slow with my application IOS

My capability :
{
  "platformName": "ios",
  "platformVersion": "12.3.1",
  "deviceName": "iphone",
  "udid": "0bacf014d5242ebd75a0be5716550e7d4a1c3d12",
  "automationName": "XCUITest",
  "bundleId": "com.sendo.sendobuyer",
  "xcodeOrgId": "D26Q4V3D6W",
  "xcodeSigningId": "iPhone Developer",
  "bootstrapPath": "/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent"
}

## Environment

* Appium version : 1.13.0
* Desktop OS/version used to run Appium: MacOS
* Mobile platform/version under test: ios 12.3.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

## Details

Appium log show error like below, but it still enable click element

## Link to Appium logs

[appium-server-logs.txt](https://github.com/appium/appium/files/3598680/appium-server-logs.txt)

**Comment by mykola-mokhnach** [comment]
Can you please be more specific about what exactly is slow? 

Try to check https://appiumpro.com/editions/19 articles set and see if that helps
