### ISSUE TITLE
iOS 13.0: visibility of elements is not always right

### ISSUE THREAD

**Issue by imurchie** [appium/appium#13223]
## The problem

Sometimes, like after a gesture to scroll, the visibility is not reported to the `visible` endpoint, though it is properly reported in the source.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.0 beta (latest from source)
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS 10.14.6
* Node.js version (unless using Appium.app|exe): 10.16.0
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: iOS 13.0
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Details

Xcode version:
```
Xcode 11.0
Build version 11A419c
```

After the scroll event happens, the source for the element we want to be visible is ([full source](https://gist.github.com/imurchie/0b23a222f0a50f81ff85cc1a26ee9393)):
```xml
<XCUIElementTypeCell type="XCUIElementTypeCell" enabled="true" visible="true" x="0" y="623" width="375" height="44">
  <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="Web View" name="Web View" label="Web View" enabled="true" visible="true" x="16" y="628" width="76" height="21"/>
  <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="WebViewController" name="WebViewController" label="WebViewController" enabled="true" visible="true" x="16" y="648" width="108" height="15"/>
  <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="15" y="666" width="360" height="1"/>
  <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="16" y="666" width="359" height="1"/>
  <XCUIElementTypeButton type="XCUIElementTypeButton" name="chevron" label="chevron" enabled="false" visible="false" x="347" y="638" width="12" height="15"/>
</XCUIElementTypeCell>
```

## Link to Appium logs

https://gist.github.com/imurchie/df3a0959ef758ed1ecc3227080aae7db

## Code To Reproduce Issue [ Good To Have ]

Slight variation on the `'should scroll using touch actions'` test from the [appium-xcuitest-driver suite](https://github.com/appium/appium-xcuitest-driver/blob/master/test/functional/basic/gesture-e2e-specs.js#L130-L145):
```js
it('should scroll using touch actions', async function () {
  let el1 = await driver.elementByAccessibilityId('Alert Views');
  let el2 = await driver.elementByAccessibilityId('Progress Views');

  let el3 = await driver.elementByAccessibilityId('Web Views');
  await el3.isDisplayed().should.eventually.be.false;

  let action = new wd.TouchAction(driver);
  action.press({el: el2}).wait(500).moveTo({el: el1}).release();
  await action.perform();

  await el3.isDisplayed().should.eventually.be.true;

  // go back
  await driver.execute('mobile: scroll', {direction: 'up'});
});
```

**Comment by imurchie** [comment]
This also breaks the `mobile: scroll` functionality.

**Comment by stevechun** [comment]
I've faced the same issue, where the visible elements are returning `isDisplayed` and `visible` states as `false`. It's fine on the first view launched but starts to have problems from the next navigated screens return false. This is currently the major blocker to update our environment.

Appium version (or git revision) that exhibits the issue: **1.15.0.rc3**
Last Appium version that did not exhibit the issue (if applicable): **1.14.2**
Desktop OS/version used to run Appium: MacOS 10.14.6
Node.js version (unless using Appium.app|exe): 11.9.0
Npm or Yarn package manager: 6.9.0
Mobile platform/version under test: iOS 13.0
Real device or emulator/simulator: Simulator
Appium CLI or Appium.app|exe: CLI

**Comment by imurchie** [comment]
Unfortunately the reproduction case above no longer works (which is to say, it works). Looking for another reliable way to reproduce.

**Comment by mykola-mokhnach** [comment]
Fixed by https://github.com/appium/WebDriverAgent/pull/222
