### ISSUE TITLE
Webview with minor chromedriver version difference discoverable but cannot switch to

### ISSUE THREAD

**Issue by brandondjango** [appium/appium#13224]
## The problem
I am on Android 9/real device.

I am attempting to interact with the webview in a hybrid app.  Recently, I have had to update my chromedriver for appium. I have done this by specifying on the command line to version "76.0.3809.68".

My problem is within my app, an outside browser is opened for auth, meaning I need to switch webview contexts. Unfortunately, that webview seems to have a different chromedriver version: "Chrome/76.0.3809.132".

When I attempt to switch webviews, Appium is not able to open it _most of the time_. I am unable to find out why it will work some times, and not others. I can always see the contexts with "available_contexts"

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS
* Node.js version (unless using Appium.app|exe): 11.0
* Mobile platform/version under test: Android 9
* Real device or emulator/simulator: Google Pixel 2

## Details

I need to be able to discover at least any webview with version: 76.0.3809.XX

## Link to Appium logs

https://gist.github.com/brandondjango/6a5de49a365537338cb149505148eb60

## Code To Reproduce Issue [ Good To Have ]

```
  @driver = Appium::Driver.new(options, true)
  @driver.start_driver

  webview = @driver.available_contexts[1]
  @driver.set_context(webview)


```

**Comment by amedvedjev** [comment]
@mykola-mokhnach we have something similar with:
 - Appium: 1.15.0-beta.1
 - ChromeView on phone: Chrome/76.0.3809.132
 - Chromedriver used during install appium server: 76.0.3809.126

Test stops when tries to switch into context. Interesting 2 things:
 - happens only on few webviews in app
 - try-catch does not help to catch problem:
```
                try {
                    ((AppiumDriver) driver).context(context); // stops on this line
                } catch (Exception e) {
                    
                }
```

Reason:
  - The adb command failed. Extra response: <>

I was able successfully debug this screen on phone with Chrome_76 connecting to mac.

Main problem for us is: TRY-CATCH does not work to prevent test stop and do some workaround in test.

**Comment by mykola-mokhnach** [comment]
@amedvedjev I would try to get the newer chromedriver version. Also, I cannot say nothing there without having a detailed server log.

BTW, java client 7.2.0 has known bug working with chromedriver in w3c mode. Consider using the version, which includes https://github.com/appium/java-client/pull/1216 from jitpack

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
