### ISSUE TITLE
Unable to run any Android Emulator Chrome Tests

### ISSUE THREAD

**Issue by Priestime** [appium/appium#13239]
## The problem

Unable to get any Emulator Test working, regardless of how simple the setup. Regardless of the Appium version/chrome version/android emulator version. Tried everything I can find, still cannot get it working.

Most common error is
```
[W3C] Encountered internal error running command: Error: Failed to start Chromedriver session: An unknown server-side error occurred while processing the command. Original error: unknown error: Failed to forward ports to device emulator-5554: . unknown error: The adb command failed. Extra response: <>.
[W3C]   (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17134 x86_64)
[W3C]     at Object.wrappedLogger.errorAndThrow (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:78:13)
[W3C]     at Chromedriver.errorAndThrow [as start] (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-chromedriver\lib\chromedriver.js:441:11)
[HTTP] <-- POST /wd/hub/session 500 57894 ms - 1372
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.0, 1.9.0, 1.10.0, 1.13.0
* Last Appium version that did not exhibit the issue (if applicable): Not sure
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): 6.9.0
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: Android 
* Real device or emulator/simulator: Emulator 
* Appium CLI or Appium.app|exe: Appium CLI and/or Appium.exe

## Details

Appium: 1.13.0
Android Debug Bridge version 1.0.41 Version 29.0.3-5806383
Android: tried 10, 9, 8 & 7 all same issue
ChromeDrivers: 2.44, 2.45, 2.46

## Link to Appium logs

https://gist.github.com/Priestime/8cd75d7a29b2c36d749b5a834dd26847

## Code To Reproduce Issue [ Good To Have ]

I've copied the code from https://github.com/appium-boneyard/sample-code/blob/master/sample-code/examples/java/generic/src/test/java/AndoridBrowserLocalTest.java and run within Intelij. constantly getting the error in the log

**Comment by mykola-mokhnach** [comment]
This might a be a problem in Android SDK or in Google Chrome itself. I don't think there is anything we could do on Appium side to resolve it.

**Comment by Priestime** [comment]
> 
> 
> This might a be a problem in Android SDK or in Google Chrome itself. I don't think there is anything we could do on Appium side to resolve it.

Do you have any suggestions on what combinations might work together? would be greatly appreciated as im at a loss.

**Comment by mykola-mokhnach** [comment]
Nope, no suggestions. I would try to ask chromedriver devs though

**Comment by skumar1122** [comment]
I am facing same issue from last 3 days. I have raised with Chrome dev's but no response yet. I am bit surprised is it even not working if I roll back to older version of chrome with Appium.

**Comment by skumar1122** [comment]
https://github.com/SeleniumHQ/selenium/issues/7564

**Comment by vliubezny** [comment]
I've faced with this issue after update of platform-tools (29.0.2 => 29.0.3)
After update to the latest version (29.0.4) the issue has gone

**Comment by Priestime** [comment]
> 
> 
> I've faced with this issue after update of platform-tools (29.0.2 => 29.0.3)
> After update to the latest version (29.0.4) the issue has gone

Can confirm this has resolved the issue. @vliubezny you've made my entire week! Thank you for letting me know.

**Comment by skumar1122** [comment]
Great ! It works now. i have updated in my android studio and it works.

**Comment by skumar1122** [comment]
> I've faced with this issue after update of platform-tools (29.0.2 => 29.0.3)
> After update to the latest version (29.0.4) the issue has gone

Is this new update causing any errors ?
<img width="670" alt="Screenshot 2019-10-01 at 15 11 30" src="https://user-images.githubusercontent.com/20112173/65970081-c3d33100-e45d-11e9-9dea-db522e10a8cc.png">
