### ISSUE TITLE
Fails to run Android tests with appium beta(1.15.0-beta.1) and new chrome version(77)

### ISSUE THREAD

**Issue by skumar1122** [appium/appium#13231]
## The problem
I have updated to latest appium version today and I can see tests started failing on Android device. It was all working until yesterday with same code and I updated chrome driver and new beta which breaks my tests. 

## Environment
* Appium version (or git revision) that exhibits the issue: 1.15.0-beta.1
* Last Appium version that did not exhibit the issue (if applicable): Release
* Node.js version (unless using Appium.app|exe): v12.8.1
* Npm or Yarn package manager: npm
* Mobile platform/version under test: 8.0
* Real device or emulator/simulator: Samsung S8
* Appium CLI or Appium.app|exe: Appium CLI
* Mobile Chrome Version : 77

## Details

> [Chromedriver] Error: No Chromedriver found that can automate Chrome '77.0.3865'. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md for more details. You could also try to enable automated chromedrivers download server feature

As followed, I have installed chrome like this:
> npm install appium-chromedriver --chromedriver_version="77.0.3865.40"

## Link to Appium logs
https://gist.github.com/skumar1122/fd3220a60b6dd41b5a7a982798c02c72

## Code To Reproduce Issue [ Good To Have ]
My caps:
appium.android.platformName = Android
appium.android.deviceName = QA Galaxy S8
appium.android.browserName = Chrome
appium.android.automationName = UiAutomator2

**Comment by mykola-mokhnach** [comment]
> [debug] [Chromedriver]     '/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver' (version '76.0.3809.126', minimum Chrome version '76.0.3809')

The error is expected. The driver was downloaded, but the path to it has not been provided in capabilities, so Appium uses the default one, which is too old. Please carefully read the documentation.

Closed as not an issue

**Comment by skumar1122** [comment]
Hi @mykola-mokhnach ,

Sorry I am using  this capability to override my local appium chrome driver, I have installed 77 version and pointed to my caps,
> capabilities.setCapability(“chromedriverExecutable”, “/usr/local/bin/chromedriver”);
```
[Appium] Appium v1.14.2 creating new AndroidUiautomator2Driver (v1.33.1) session
[Appium] Capabilities:
[Appium]   browserName: Chrome
[Appium]   platformName: android
[Appium]   automationName: UiAutomator2
[Appium]   chromedriverExecutable: /usr/local/bin/chromedriver
[Appium]   deviceName: QA Galaxy S8
[Appium]   platformVersion: 8.0
[Appium]   udid: xxxxxxxx
```
But I am still getting same errors, Please point me if i miss anything here ?

**Comment by mykola-mokhnach** [comment]
Are you sure `/usr/local/bin/chromedriver` has the correct version? The very first log did not have `chromedriverExecutable` in caps.

**Comment by skumar1122** [comment]
@mykola-mokhnach 
Please check the latest logs here,

https://gist.github.com/skumar1122/2a90ac58c53130e49ef2194dfc6748aa

**Comment by mykola-mokhnach** [comment]
> [debug] [WD Proxy] Got response with status 200: {"sessionId":"fdac66f928757106b922daaff342f4aa","status":13,"value":{"message":"unknown error: Failed to forward ports to device ce10182a6065d91a03: . unknown error: The adb command failed. Extra response: <>.\n  (Driver info: chromedriver=77.0.3865.40 (f484704e052e0b556f8030b65b953dce96503217-refs/branch-heads/3865@{#442}),platform=Mac OS X 10.14.6 x86_64)"}}

This seems to be chromedriver issue. Consider reporting it to chromedriver bug tracker

**Comment by skumar1122** [comment]
@mykola-mokhnach 
The Issue was with SDK tools. 29.0.2  or 29.0.3 version of platform tools has issue with latest browsers. I have now updated my platform tools to **29.0.4** and it works.

**Comment by mykola-mokhnach** [comment]
Thanks for letting us know. I knew it's something third party %)

**Comment by pacchan** [comment]
@mykola-mokhnach 
Hi, Can you pls share the steps how to update platform
