### ISSUE TITLE
Appium freezes trying to establish connection with chromedriver

### ISSUE THREAD

**Issue by sri85** [appium/appium#13237]
## The problem

Currently I am trying to test our cordova app with appium . However I am unable to proceed with the testing as appium freezes trying to establish connection with chromedriver.
My desired capabilities look something like this

```
{
  "platformName": "Android",
  "platformVersion": "8.0",
  "deviceName": "any",
  "app": "<path_to_apk>//android-debug.apk",
  "autoWebview": "true",
}
```

Appium launches the app but then keeps on trying to establish a connection with chromedriver and in the logs I keep seeing 

```
sessionId":"e9f5e25bbe6c11a9eaa6d1feec822ea4","status":100,"value":{"message":"chrome not reachable\n  (Driver info: chromedriver=2.31.488774 (7e15618d1bf16df8bf0ecf2914ed1964a387ba0b),platform=Mac OS X 10.14.3 x86_64)"}}
[debug] [35m[MJSONWP][39m Matched JSONWP error code 100 to UnknownError
[error] [35m[Chromedriver][39m Error: Failed to start Chromedriver session: An unknown server-side error occurred while processing the command. Original error: chrome not reachable
```

More logs can be found [here](https://gist.github.com/sri85/6adfbe5605fc1a14028b4ad9858fa9de)

I am able to inspect the app from chrome devtools however I cannot get appium to interact with the app. If i remove `autoWebview: true` from the capability I am able to get appium to talk to the app.

So going a bit further I tried launching `chromedriver` using the following command
`/chromedriver --url-base=wd/hub --port=8000 --adb-port=5037 --verbose`

and then trying to launch chrome
```curl -X POST http://127.0.0.1:8000/wd/hub/session  -d '{"desiredCapabilities":{"chromeOptions":{"args": ["--disable-fre","--no-sandbox"], "androidPackage":"com.android.chrome","androidDeviceSerial":"emulator-5554"},"loggingPrefs":{"browser":"ALL"}}}'``` 
Chrome is launched how ever the only logs i see is 
```DevTools request: http://localhost:12576/json/version request failed```

logged infinitely and then it dies.

In Android 8.1 I have chrome 58.0.3029.0 and as per this [page](http://appium.io/docs/en/writing-running-appium/web/chromedriver/) i need 2.31 version of chromedriver which I have tried and it fails.

On the same machine I also run web tests on chrome using the same chromedriver and it never complains and it works perfectly.

## Environment

* Appium version: 1.14.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OSX(10.14.3)
* Node.js version (unless using Appium.app|exe): 8.10.0
* Npm package manager: 6.9.0
* Mobile platform/version under test: Android 8 / Android 7.1.2 / Android 8.1
* Real device or emulator/simulator: Emulator/ Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
[Appium Logs](https://gist.github.com/sri85/6adfbe5605fc1a14028b4ad9858fa9de)
[ADB Logs](https://gist.github.com/sri85/6bc8bd8f0e0e193167ad54c9e7a8eda5)
[ChromeDriver Logs](https://gist.github.com/sri85/e0e8f9fa113b046e2274887899b315ce)

## Code To Reproduce Issue [ Good To Have ]

1. Please use the sample app which is [here](https://github.com/asialgearoid/cordova-appium-example)
2. 
```
const wdio = require("webdriverio");
const opts = {
    port: 4723,
    capabilities: {
        platformName: "Android",
        platformVersion: "8.1",
        deviceName: "any",
        app: "<path_to_apk>",
        autoWebview: true,
        autoWebviewTimeout: 20000,
        'chromeOptions': {
            'args': [
                '--no-sandbox'
            ],
        }
    }
};
(async () => {
    const client = await wdio.remote(opts);
 
    let el1 = await client.findElement('css','#showHideButton');
    await el1.click();


})();
```
Run the file using `node test.js` , appium launches the app , keeps trying and eventually fails.

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Any help will be greatly appreciated . Happy to provide more details to keep debugging easier.

**Comment by mykola-mokhnach** [comment]
The error is coming from chromedriver itself. I don't think there is anything we could do on appium side to resolve it. Although, it might a problem about specific cordova framework requirements. I would try to create an issue report to chromedriver and see what developers respond.

**Comment by sri85** [comment]
@mykola-mokhnach I don't think cordova is the suspect here because I am able to reproduce the error
just by doing
```
curl -X POST http://127.0.0.1:8000/wd/hub/session -d '{"desiredCapabilities":{"chromeOptions":{"args": ["--disable-fre","--no-sandbox"], "androidPackage":"com.android.chrome","androidDeviceSerial":"emulator-5554"},"loggingPrefs":{"browser":"ALL"}}}'
```

This launches chrome and then the chromedriver keeps saying `Devtools request failed` and then finally dies citing `chrome not reachable`.

**Comment by mykola-mokhnach** [comment]
Check https://www.bountysource.com/issues/8905280-update-appium-android-driver-to-search-for-correct-webview-regex

**Comment by sri85** [comment]
Thanks for that @mykola-mokhnach , I will try that . H
owever I am seeing lots of similar issues being reported in issue tracker . I have gone ahead and logged an issue in chromium projects to get some insights as to why we are seeing this .
https://bugs.chromium.org/p/chromedriver/issues/detail?id=3130

**Comment by sri85** [comment]
There were couple problems on my side
1. One is i was using a 32 bit version of emulator where as the chromedriver I was using was a 64 bit . I fixed it and then i started seeing port forwarding error , I found the solution https://github.com/appium/appium/issues/13239#issuecomment-531760257 and upgraded my `adb` to 29.0.4-5871666 and I got it working again.
@mykola-mokhnach we can close this issue for now . 
Thanks for the help 👍
