### ISSUE TITLE
iOS 13 every other test fails with  Selenium::WebDriver::Error::InvalidElementStateError:  

### ISSUE THREAD

**Issue by hardik-plume** [appium/appium#13236]
## The problem

Randomly i see tests fail with  "Selenium::WebDriver::Error::InvalidElementStateError:
            The application under test with bundle id <my_app_bundle_id> is not running, possibly crashed"

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.0-beta.1
* Last Appium version that did not exhibit the issue (if applicable): 1.13
* Desktop OS/version used to run Appium: mac OS 10.14.6
* Node.js version (unless using Appium.app|exe): v8.15.0
* Npm or Yarn package manager: 6.4.1
* Mobile platform/version under test: iOS 13 beta
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: cli

**Comment by mykola-mokhnach** [comment]
Maybe the application did really crash? Have you checked its logs?

**Comment by hardik-plume** [comment]
@mykola-mokhnach same action works first time only fails second time, so i didn't think it would be an app issue. Thanks
