### ISSUE TITLE
Appium writes too many logs with Xcode 11

### ISSUE THREAD

**Issue by FirstAM** [appium/appium#13245]
## The problem
Hi 
After update Xcode to 11 i have a problem with write logs 
When i do capability  showXcodeLog-  true , appium logs writes increase from 595kb to 13 Mb for one case ! ( amazing) After test suite i have each appium report no less then 500 mb 

Example log without capability 
[appium_logs_00008020-00063D3611E2002E_73.txt](https://github.com/appium/appium/files/3616340/appium_logs_00008020-00063D3611E2002E_73.txt)

Example log with capability
[appium_logs_00008020-00063D3611E2002E_25_big.txt](https://github.com/appium/appium/files/3616341/appium_logs_00008020-00063D3611E2002E_25_big.txt)

Before updating Xcode this was not

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13.0
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: Mac oS 10.14.5 
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: never mind 
* Appium CLI or Appium.app|exe:

**Comment by imurchie** [comment]
This is, unfortunately, what Xcode 11 logs. I'm not sure what Appium could do about it.

**Comment by FirstAM** [comment]
like an idea, you can filter some xcode logs =)

**Comment by imurchie** [comment]
And what would be filtered? How would we know, _a priori_, what everyone wants to see in order to debug? Filtering out lines _you_ don't care about does not mean that someone else doesn't want to see them. 

I would say the onus ought to be on the consumer of the logs to filter out what they don't want to see. It would be relatively easy to pipe the logs through a filter to get exactly what you need.

**Comment by dpgraham** [comment]
@FirstAM thanks for reporting this issue. Because of this issue, I was able to flag this as a risk at Sauce Labs and this prevented us from shipping our cloud Appium offering with oversized logging. And it helped us find a solution ^
