### ISSUE TITLE
Should provide a way to forbid appium use WiFi to connected WDA, so when appium server and the iphone under test are under same local area network, we don't need to prey for an unofficially supported function to work.

### ISSUE THREAD

**Issue by st68390206** [appium/appium#13243]
Should provide a way to forbid appium use WiFi to connected WDA, so when appium server and iphone under test are under same local area network, we don't need to pray for an unofficially supported function to work.

**Comment by mykola-mokhnach** [comment]
Sorry, but I don't understand what the request is about. Can you please be more specific?

**Comment by st68390206** [comment]
@mykola-mokhnach, you can see specific in issue #13168

**Comment by mykola-mokhnach** [comment]
> fail to launch webdriveragent

does say nothing without the detailed log. Please provide the detailed failure log with xcode logging enabled and run your test using the most recent beta version of the server.

**Comment by st68390206** [comment]
@mykola-mokhnach , I think you have told me that "Unfortunately Appium does not support iOS testing via WiFi. See #12089 #12674 for more details". So, now, I simply want to know if there is a way to forbid appium test iOS via WiFi, since currently, it looks like test via WiFi is default set. But you can still ask me for log if it is key to resolve my current question.

**Comment by KazuCocoa** [comment]
You can disable 'connect via network' on Xcode's devices option in order to ignore them from your xcodebuild. It depends on your Xcode preference.
https://discuss.appium.io is a good place to ask such a question
