### ISSUE TITLE
Not able to Tap on Element placed in Tap Bar 

### ISSUE THREAD

**Issue by Ankit1D987** [appium/appium#13240]
## The problem

I need to tap on a most Imp element of my app called "Order" but I am not able to do that

## Environment

* Appium version (or git revision) that exhibits the issue: 13.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:-**iOS**
* Real device or emulator/**simulator:Simulator**
* Appium CLI or Appium.app|exe:**Appium App**

## Details

I need to click on Element called "Order" .I tried Xpath and findelements by class but its not working. 

## Link to Appium logs

[appium-server-logs copy.txt](https://github.com/appium/appium/files/3613862/appium-server-logs.copy.txt)

## Code To Reproduce Issue [ Good To Have ]

public class EHTest {

	public static void main(String[] args) throws MalformedURLException {

		DesiredCapabilities d = new DesiredCapabilities();

		d.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone X");

		d.setCapability(MobileCapabilityType.PLATFORM_NAME, "IOS");

		d.setCapability(MobileCapabilityType.PLATFORM_VERSION, "12.4");

		d.setCapability("autoGrantPermissions", "true");
		d.setCapability("autoAcceptAlerts", "true");

		d.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.IOS_XCUI_TEST);

		d.setCapability(MobileCapabilityType.APP, "/Users/XXXX
<img width="1622" alt="Screenshot 2019-09-15 at 14 38 53" src="https://user-images.githubusercontent.com/48440936/64923256-75286480-d7d8-11e9-8337-d92ef045325f.png">
<img width="1637" alt="Screenshot 2019-09-15 at 14 38 45" src="https://user-images.githubusercontent.com/48440936/64923262-7e193600-d7d8-11e9-849c-6f3bd8577856.png">

/Desktop/Eclipse/Espresso House.app");

		IOSDriver<IOSElement> driver;
		driver = new IOSDriver<>(new URL("http://127.0.0.1:4723/wd/hub"), d);

		driver.findElementByXPath("//*[@value='Enter mobile number']").sendKeys("46555277538");

		driver.findElementByName("Register").click();

		driver.manage().timeouts().implicitlyWait(3000, TimeUnit.SECONDS);

		driver.findElementByXPath("//*[@value='Enter code']").sendKeys("70428");
		
		driver.manage().timeouts().implicitlyWait(3000, TimeUnit.SECONDS);

		driver.findElementByName("Skip").click();
		
		driver.manage().timeouts().implicitlyWait(6000, TimeUnit.SECONDS);

		driver.findElementsByClassName("XCUIElementTypeButton").get(0).click();

		// driver.findElementByXPath("//XCUIElementTypeButton[@name='Order']").click();

	}

}

**Comment by mykola-mokhnach** [comment]
You can try to tap by coordinates as a workaround. The above error in logs happens when xctest returns zero-size frame for an element, so we cannot determine the location of it.

**Comment by Ankit1D987** [comment]
This worked -driver.findElementByAccessibilityId("Order").click();  :)
