### ISSUE TITLE
Original error: The capabilities ["platFormName"] are standard capabilities and should not have the "appium:" prefix

### ISSUE THREAD

**Issue by Ramikolli** [appium/appium#13242]
## The problem

I am getting error while running the test on the Android emulator with appium and Selenium

FAILED CONFIGURATION: @BeforeTest setUp
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details.

Original error: The capabilities ["platFormName"] are standard capabilities and should not have the "appium:" prefix

Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'ADMIN-PC', ip: '192.168.0.104', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_221'
Driver info: driver.version: AndroidDriver

remote stacktrace: InvalidArgumentError: The capabilities ["platFormName"] are standard capabilities and should not have the "appium:" prefix
at stripAppiumPrefixes (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\capabilities.js:99:11)
at stripAppiumPrefixes (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\capabilities.js:147:3)
at parseCaps (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\capabilities.js:199:43)
at AndroidUiautomator2Driver.createSession (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\commands\session.js:37:14)

## Environment

* Appium version (or git revision) that exhibits the issue:

* Desktop OS/version used to run Appium: Win 7
* Node.js version (unless using Appium.app|exe):

* Npm or Yarn package manager:

* Mobile platform/version under test:

* Real device or emulator/simulator:Android emulator

* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

please do the needful

**Comment by mykola-mokhnach** [comment]
> Create a GIST which is a paste of your full Appium logs, and link them here.

**Comment by Ramikolli** [comment]
> > Create a GIST which is a paste of your full Appium logs, and link them here.

hi mykola, I was buzy with work and could not get time to ass the appium logs. I will do it by week end.Thank you

**Comment by sheikhjebran** [comment]
@Ramikolli  can you share your capabilities and if possible ur nuget packages info?

**Comment by Ramikolli** [comment]
hi
DesiredCapabilities caps = new DesiredCapabilities();

caps.setCapability("platFormName", "Android");
caps.setCapability("platFormVersion","7.1.1");
caps.setCapability("deviceName","Android Emulator");
caps.setCapability("automationName","UiAutomator2");
caps.setCapability("app", "E:\\Appium\\TheApp-v1.10.0.apk");

**Comment by sheikhjebran** [comment]
@Ramikolli , There is an error in your capabilities, luke the "platFormName" it has CAP-"F" similarly your not giving launch activity name, kindly give a try with the below sample capabilities, and fill with the appropriate content and try



`capabilities.SetCapability("platformName", "Android");
                    capabilities.SetCapability("appPackage", "Enter the package name");
                    capabilities.SetCapability("appActivity", "Enter the activity name");
                    capabilities.SetCapability("automationName", "uiautomator2");
                    capabilities.SetCapability("platformVersion", "7.1.1");
                    capabilities.SetCapability("deviceName", "Enter device id Ex:2a99aec9763f7ece");
                    capabilities.SetCapability("app", androidObject.LocalAppPath);
                    capabilities.SetCapability("newCommandTimeout", 1000);
                    capabilities.SetCapability("launchTimeout", 100000);`
