### ISSUE TITLE
Not able to use Webview on iOS due to timeout of no targets found

### ISSUE THREAD

**Issue by wswebcreation** [appium/appium#13248]
## The problem
 I'm refactoring the WebdriverIO demo app and it gets the latest version of the react-native-webview module which has a fix for the deprecated UIWebview API, see also https://github.com/react-native-community/react-native-webview/issues/819. When I use that module in the app the Webview can be selected but **or** throws a `WebDriverError: An unknown server-side error occurred while processing the command. Original error: No targets found, unable to communicate with device` **or** setting of the context of the app times out

When I use my previous version of the App, see https://github.com/webdriverio/native-demo-app/releases/tag/0.2.1, I can automate the webview, but with this version 

[iOS-Simulator-NativeDemoApp-0.3.1.app.zip](https://github.com/appium/appium/files/3619602/iOS-Simulator-NativeDemoApp-0.3.1.app.zip)

I can't get this working

## Environment

* Appium version (or git revision) that exhibits the issue: `1.14.2` and `1.15.0-beta.1`
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: OSX Mojave 10.14.6 (18G95)
* Node.js version (unless using Appium.app|exe): `v10.16.3`
* Npm or Yarn package manager: npm `6.9.0`
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Sim
* Appium CLI or Appium.app|exe: CLI

## Details
It looks like it is related to https://github.com/appium/appium/issues/12935

## Link to Appium logs

https://gist.github.com/wswebcreation/0839c558a26eb67664ea34006c241eff

## Code To Reproduce Issue [ Good To Have ]

1. Clone this project https://github.com/webdriverio/appium-boilerplate
2. install all dependencies with `npm install`
3. Download the app as mentioned above and place it in a folder called `apps` and change this line of code https://github.com/webdriverio/appium-boilerplate/blob/master/config/wdio.ios.app.conf.js#L31 to 

```js
'appium:app': join(process.cwd(), './apps/iOS-Simulator-NativeDemoApp-0.3.1.app.zip'),
```

4. Run the test with this command 

```
npm run ios.app -- --spec=./tests/specs/app.webview.spec.js
```

**Comment by imurchie** [comment]
I've figured out the problem, which is target allocation, and am trying to figure out a workable solution.

**Comment by wswebcreation** [comment]
@imurchie 

I've upgraded to the latest version of the beta, see below

```shell
➜  Git npm -g list appium-remote-debugger
/Users/wimselles/.nvm/versions/node/v10.16.3/lib
└─┬ appium@1.15.0-beta.1
  ├─┬ appium-ios-driver@4.4.0
  │ └── appium-remote-debugger@4.5.0
  └─┬ appium-xcuitest-driver@2.131.1
    └── appium-remote-debugger@5.7.0
```

And it works 🎉 . Thanks. Hope this will released with the new version

**Comment by wswebcreation** [comment]
@imurchie 

As discussed, this works with `1.15.0-rc.4` on iOS `12.2`, but it doesn't work on `13.0`

**Comment by imurchie** [comment]
Can you try the steps outlined here: https://github.com/appium/appium/issues/13285#issuecomment-537210985

**Comment by wswebcreation** [comment]
@imurchie 

I've retested this with Appium `1.15.0`, the stable and the issue is gone on iOS `12.2` and `13.0`. Thanks!
