### ISSUE TITLE
Execute Mobile Command swipe doesn't work on Android

### ISSUE THREAD

**Issue by ania-s** [appium/appium#13249]
## The problem

When trying to execute the mobile command `swipe` on Android webview app using webdriverio & appium-espresso-driver I get the following error:

> An unknown server-side error occurred while processing the command. Original error: java.util.NoSuchElementException: No such element with ID 'afba0efe-6667-41e0-b4de-9357e0a9e6a6'

The commands I tried:
`browser.execute("mobile: swipe", {element: $(card), direction: "left"});`
&
```
const params = {element: $(card), swiper: "SLOW", startCoordinates: 'BOTTOM_RIGHT', endCoordinates: 'BOTTOM_LEFT', precisionDescriber: 'FINGER'};
browser.execute("mobile: swipe", params});
```

http://appium.io/docs/en/commands/mobile-command/ has wrong parameter for both commands as it suggests to use elementId instead of element which fails with 

> An unknown server-side error occurred while processing the command. Original error: The following options are required: ["element"]. You have only provided: ["elementId","swiper","startCoordinates","endCoordinates","precisionDescriber"]

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.2
* Desktop OS/version used to run Appium: Mac OS Mojave
* Node.js version (unless using Appium.app|exe): 10.15.3
* Npm: 6.4.1
* Mobile platform/version under test: Android 7
* Real device or emulator/simulator: Galaxy Tab S2

**Comment by mykola-mokhnach** [comment]
I would say this is a confusion between xctest and espresso, which have command with the same name, but different list of arguments

**Comment by ania-s** [comment]
> I would say this is a confusion between xctest and espresso, which have the command with the same name, but different list of arguments

Documentation on appium side is one thing. But even when `element` is used as a parameter none of the commands works with espresso.

**Comment by KazuCocoa** [comment]
Checked.
The arg name is element and the value should be the element id like below (e.ref is element id in Ruby)
`@driver.execute_script('mobile: swipe', { element: e.ref, direction: 'up' })`

**Comment by ania-s** [comment]
> Checked.
> The arg name is element and the value should be the element id like below (e.ref is element id in Ruby)
> `@driver.execute_script('mobile: swipe', { element: e.ref, direction: 'up' })`

@KazuCocoa any clue what is it in webdrvierio (javascript/typescript)? I tried to get elementId out of the object I want to swipe with no luck :/

**Comment by KazuCocoa** [comment]
https://github.com/webdriverio/webdriverio/search?q=element+id&unscoped_q=element+id
Maybe `e.elementId` or `e.value`...
