### ISSUE TITLE
Is there any automation tool to support for all TV platform like Android TV, Fire TV, LG WebOS TV, Samsung, Roku, Xbox, Vewd, PS4 TV apps ??  or appium tool can be supported for this ?

### ISSUE THREAD

**Issue by jena-madhusmita** [appium/appium#13259]

**Comment by mykola-mokhnach** [comment]
Unfortunately there is no universal solution. Appium drivers support Android OS, Tizen OS and tvOS, so it could potentially automate platforms based on those operating systems. Regarding others you should either consult the SDK documentation or ask the platform developers about which tools they use for automation.

Please use Appium forum to ask questions.

**Comment by jena-madhusmita** [comment]
Thank you for your reply!!
One more question, which tools are you using to automate LG web OS, Roku, Xbox, Vewd, PS4 TV platform?
