### ISSUE TITLE
Unable to switchTo().window(...) in iOS Safari

### ISSUE THREAD

**Issue by ishanm120** [appium/appium#13263]
## The problem

Switching to a different browser tab isn't working for mobile iOS Safari.

## Environment

Appium v1.14.0-beta.2
MacOS Mojave 10.14.4
Real Device iPhone X

## Details

1) open any application 
2) click on some link/tab which opens a new tab in browser.
3) Try to switch to new tab using selenium code.
It's not working and getting error.

Same is working fine in other appium versions like : 1.14.0, 1.14.2 
This case is vice versa for Android chrome (Which is working fine only on v1.14.0-beta.2 but not working on other versions 1.14.0, 1.14.2 )

## Link to Appium logs
https://gist.github.com/ishanm120/90568d9c40af028c407d2a955ab8d587

**Comment by imurchie** [comment]
Ah, yes. This will not work with the new way in which we deal with Safari. 

Working on it.

**Comment by imurchie** [comment]
I'm working on a solution to this, just writing some tests.

But in the meantime, does it work if you use contexts instead of window handles?

**Comment by kartikjain12** [comment]
Also getting this issue, cannot find any work around. Does anyone know of a work around other than downgrading?

**Comment by imurchie** [comment]
Can you try on the latest beta of Appium (`npm uninstall -g appium && npm install -g appium@beta`). v1.16.0-beta.1 should install.

**Comment by ishanm120** [comment]
> Can you try on the latest beta of Appium (`npm uninstall -g appium && npm install -g appium@beta`). v1.16.0-beta.1 should install.

Will it work for both iOS and Android?

**Comment by imurchie** [comment]
This issue has nothing to do with Android, which has en entirely different system for dealing with Web/webviews. I'm not sure what you're referring to here, @ishanm120 .

**Comment by ishanm120** [comment]
> This issue has nothing to do with Android, which has en entirely different system for dealing with Web/webviews. I'm not sure what you're referring to here, @ishanm120 .

Actually everything was working fine with iOS as well on all appium versions (eg: 1.14.2) other than i mentioned in the problem( v1.14.0-beta.2)
and opposite was there for Android(Means v1.14.0-beta.2 version was working for Android and not other versions)
So that's why asking that new version v1.16.0-beta.1  will contain solution for both or just for iOS.

**Comment by imurchie** [comment]
I did not do any testing on Android for this issue, since it was all about iOS. And as I said, they are _completely_ different implementations, so there is little chance that messing with one will affect the other.

Did you get a chance to try out iOS window switching in the latest beta?

**Comment by imurchie** [comment]
Can you please try the latest beta of Appium, ensuring that the installed version of `appium-remote-debugger` is `6.3.0`
```
npm uninstall -g appium
npm install -g appium@beta

npm ls -g appium-remote-debugger
```
The last ought to output something like:
```
$ npm ls -g appium-remote-debugger
/Users/isaacmurchie/.nvm/versions/node/v10.16.3/lib
└─┬ appium@1.16.0-beta.1
  ├─┬ appium-ios-driver@4.4.0
  │ └── appium-remote-debugger@4.5.0
  ├─┬ appium-xcuitest-driver@3.3.0
  │ └── appium-remote-debugger@6.3.0
  └─┬ appium-youiengine-driver@1.2.1
    └─┬ appium-xcuitest-driver@2.133.1
      └── appium-remote-debugger@5.7.0
```
The listing of `appium-remote-debugger` under `appium-xcuitest-driver` should be `6.3.0`.

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by hemank5** [comment]
> ## The problem
> Switching to a different browser tab isn't working for mobile iOS Safari.
> 
> ## Environment
> Appium v1.14.0-beta.2
> MacOS Mojave 10.14.4
> Real Device iPhone X
> 
> ## Details
> 1. open any application
> 2. click on some link/tab which opens a new tab in browser.
> 3. Try to switch to new tab using selenium code.
>    It's not working and getting error.
> 
> Same is working fine in other appium versions like : 1.14.0, 1.14.2
> This case is vice versa for Android chrome (Which is working fine only on v1.14.0-beta.2 but not working on other versions 1.14.0, 1.14.2 )
> 
> ## Link to Appium logs
> https://gist.github.com/ishanm120/90568d9c40af028c407d2a955ab8d587

Is this working still? I am using latest Appium 1.17 beta version with iOS 13.3.1 ~ tried both on simulator and real device, Its not working for me.

**Comment by AlexBravoInostroza01** [comment]
Anyone manage to switch tabs with safari?

**Comment by imtiaz-mAtallshorestaffingDotcom** [comment]
Any update on this issue?
