### ISSUE TITLE
Get rid of WAD_EXE_MD5

### ISSUE THREAD

**Issue by koglerch13** [appium/appium#13261]
WAD_DL_MD5 and WAD_EXE_MD5 do not match after patches to WinAppDriver.exe even if the version stays the same.
Users have to change the value in the downloaded lib manually (https://discuss.appium.io/t/attempts-to-run-appium-windows-driver-fail-with-error-could-not-verify-winappdriver-install-re-run-install/16431/3)

This problem can easily occur again and might not be caught right away. Is it really necessary to couple the WinAppDriver version so tight?

Related to #12758

**Comment by mykola-mokhnach** [comment]
It would be nice to know why this verification has been added initially. @yodurr do you more details on why such decision has been made?

**Comment by mykola-mokhnach** [comment]
Published to appiun@beta
