### ISSUE TITLE
Appium decktop with xcode 11

### ISSUE THREAD

**Issue by Berger1804** [appium/appium#13277]
Hi, I have a problem. after update xcode to xcode 11 the appium desktop the app is launched but the inspector never finished loaded. i cant see the app screen on the inspector.

Thanks !

**Comment by mykola-mokhnach** [comment]
https://twitter.com/wswebcreation/status/1176400408379613184

Closed as duplicate

**Comment by Berger1804** [comment]
Still not working :(

**Comment by KazuCocoa** [comment]
Could you share your logs?
(or create as a new issue with the log)
