### ISSUE TITLE
driver.sessionCapabilities() throwing exception with Xcode 11 

### ISSUE THREAD

**Issue by SvetoslavTsenov** [appium/appium#13279]
## The problem

Trying to get sessionCapabilities 
`
await driver.sessionCapabilities()
`
throws an exception with Xcode 11 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.2
* Node.js version (unless using Appium.app|exe): 10.16.0
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: iOS 13, Xcode 11
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: wd

## Link to Appium logs

https://gist.github.com/SvetoslavTsenov/79de255f28b28352269dc683827fa6d5

## Code To Reproduce Issue [ Good To Have ]

`http://localhost:4723/wd/hub/session/sessionId`
or 
`await driver.sessionCapabilities()`

**Comment by mykola-mokhnach** [comment]
Appium 1.14 does not support iOs 13. One must use appium@beta with it

**Comment by SvetoslavTsenov** [comment]
Hey @mykola-mokhnach, thanks for quick the response.
I have tested it with `appium@rc: 1.15.0-rc.4` and it works!!!
