### ISSUE TITLE
Appium script execution very slow in android virtual device

### ISSUE THREAD

**Issue by sravya-vagalaboina** [appium/appium#13273]
## The problem

Appium script execution is very slow in android virtual device for android app.

## Environment

* Appium version (or git revision) that exhibits the issue:1.10.1
* Last Appium version that did not exhibit the issue (if applicable): not sure
* Desktop OS/version used to run Appium: Windows8
* Node.js version (unless using Appium.app|exe):v10.15.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Android 8.0
* Real device or emulator/simulator: Emulator(Android emulator)
* Appium CLI or Appium.app|exe: Appium CLI

## Details

We are using appium java client library for script creation with appium node server  and android virtual device provided by android studio. But Appium Script execution is very slow on virtual device but same is better on real device. Can you please suggest some resolution to this kind of problem or some best practice to follow.

Please let us know if anything required for further analysis.

Thanks

**Comment by KazuCocoa** [comment]
Does the Android emulator work well by manual?

In general, Android emulators are slower than real devices.
You can use x86 architectured emulators and good power PCs to improve the performance.

**Comment by sravya-vagalaboina** [comment]
We are using x86 emulators  only and my system configuration is - Windows 8 - 64 Bit, RAM - 12GB, Processor- i3 1.90GHz

**Comment by KazuCocoa** [comment]
I have no good experience in the environment, sorry.
You can ask it in https://discuss.appium.io or probably can find articles about android emulators on Windows environment
