### ISSUE TITLE
WDA Get Text Api is returning Empty string if the Element is not enabled.

### ISSUE THREAD

**Issue by santoshkumar-soma** [appium/appium#13272]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

We have observed the issue that Get Text API from WDA is returning Empty String in case of element is not enabled. 

Rest Endpoint: 

http://10.120.9.6:8100/session/26E96D13-377C-4C4A-8DDF-031F67D62A96/element/31000000-0000-0000-D602-000000000000/text

Response:
{
"value": "",
"sessionId": "26E96D13-377C-4C4A-8DDF-031F67D62A96"
}

Note: Attached Screenshot. If the element is enabled then API is working as expected. This was case with latest changes from WDA.  Before W3C Changes in WDA,  This API is working as expected even the element is not enabled.

<img width="364" alt="Screen Shot 2019-09-23 at 6 38 04 PM" src="https://user-images.githubusercontent.com/16301064/65428076-4e4ddc00-de31-11e9-8d8b-83d47bf6a53c.png">

**Comment by mikesalvia** [comment]
<img width="321" alt="Screen Shot 2019-09-30 at 10 25 10 AM" src="https://user-images.githubusercontent.com/6209204/65887847-9ce90200-e36c-11e9-9335-36cde947ab65.png">
👍 I am having this happen even when the element is enabled.

**Comment by mikesalvia** [comment]
#13326 Issues may be linked. Going to try to use different methods to look up my element as a workaround or parse the result of `.getPageSource()` because oddly enough the text is present in the <AppiumAUT> object.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
