### ISSUE TITLE
The pageSource infomation cannot update immediately after the operation of click or other event change.

### ISSUE THREAD

**Issue by studyJavaForLive** [appium/appium#13284]
## The problem

The page infomation of android device cannot respones right now when a click event occur. The  page content is still original. I must use the method of 'driver.getPageSource()' to get the new page clicked infomation.

## Environment

Appium version 4.1.0
Desktop OS/version used to run Appium: Windows10 
Node.js version (unless using Appium.app|exe): v10.16.0
Npm or Yarn package manager: 
{ npm: '6.9.0',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.8.0',
  icu: '64.2',
  modules: '64',
  napi: '4',
  nghttp2: '1.34.0',
  node: '10.16.0',
  openssl: '1.1.1b',
  tz: '2019a',
  unicode: '12.1',
  uv: '1.28.0',
  v8: '6.8.275.32-node.52',
  zlib: '1.2.11' }
Mobile platform/version under test: 6.0
Real device or emulator/simulator: 
Appium CLI or Appium.app|exe:

**Comment by studyJavaForLive** [comment]
What is the function of AndroidDriver.getPageSource()? request appium server again to get the latest pageSource? Please help me,Thinks very much!

**Comment by mykola-mokhnach** [comment]
Please fill out the issue reporting form properly. We need the full server log. Also, server version `4.1.0` does not exist

**Comment by studyJavaForLive** [comment]
Oh so sorry! the appium version is 1.5.3 
<dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>4.1.0</version>
</dependency>
Appium server log:
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getLocation
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":{"x":336,"y":569}}
> info: [debug] Responding to client with success: {"status":0,"value":{"x":336,"y":569},"sessionId":"05401fbc-d239-4780-b893-2e46cbbdb20c"}
> info: <-- GET /wd/hub/session/05401fbc-d239-4780-b893-2e46cbbdb20c/element/72/location 200 256.895 ms - 89 {"status":0,"value":{"x":336,"y":569},"sessionId":"05401fbc-d239-4780-b893-2e46cbbdb20c"}
> info: --> POST /wd/hub/session/05401fbc-d239-4780-b893-2e46cbbdb20c/touch/perform {"actions":[{"action":"press","options":{"x":486,"y":515}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"x":486,"y":188}},{"action":"release","options":{}}]}
> info: [debug] Pushing command to appium work queue: ["swipe",{"startX":486,"startY":515,"endX":486,"endY":188,"steps":28}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"swipe","params":{"startX":486,"startY":515,"endX":486,"endY":188,"steps":28}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: swipe
> info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1024,560]
> info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1024,560]
> info: [debug] [BOOTSTRAP] [debug] Swiping from [x=486.0, y=515.0] to [x=486.0, y=188.0] with steps: 28
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
> info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"05401fbc-d239-4780-b893-2e46cbbdb20c"}
> info: <-- POST /wd/hub/session/05401fbc-d239-4780-b893-2e46cbbdb20c/touch/perform 200 918.788 ms - 76 {"status":0,"value":true,"sessionId":"05401fbc-d239-4780-b893-2e46cbbdb20c"}
> info: --> GET /wd/hub/session/05401fbc-d239-4780-b893-2e46cbbdb20c/element/72/location {}
> info: [debug] Pushing command to appium work queue: ["element:getLocation",{"elementId":"72"}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:getLocation","params":{"elementId":"72"}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getLocation
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":{"x":336,"y":569}}
> info: [debug] Responding to client with success: {"status":0,"value":{"x":336,"y":569},"sessionId":"05401fbc-d239-4780-b893-2e46cbbdb20c"}
> info: <-- GET /wd/hub/session/05401fbc-d239-4780-b893-2e46cbbdb20c/element/72/location 200 55.615 ms - 89 {"status":0,"value":{"x":336,"y":569},"sessionId":"05401fbc-d239-4780-b893-2e46cbbdb20c"}
> info: --> POST /wd/hub/session/05401fbc-d239-4780-b893-2e46cbbdb20c/touch/perform {"actions":[{"action":"press","options":{"x":486,"y":500}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"x":486,"y":188}},{"action":"release","options":{}}]}
> info: [debug] Pushing command to appium work queue: ["swipe",{"startX":486,"startY":500,"endX":486,"endY":188,"steps":28}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"swipe","params":{"startX":486,"startY":500,"endX":486,"endY":188,"steps":28}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: swipe
> info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1024,560]
> info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1024,560]
> info: [debug] [BOOTSTRAP] [debug] Swiping from [x=486.0, y=500.0] to [x=486.0, y=188.0] with steps: 28
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
> info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"05401fbc-d239-4780-b893-2e46cbbdb20c"}
> info: <-- POST /wd/hub/session/05401fbc-d239-4780-b893-2e46cbbdb20c/touch/perform 200 957.268 ms - 76 {"status":0,"value":true,"sessionId":"05401fbc-d239-4780-b893-2e46cbbdb20c"}
> info: --> GET /wd/hub/session/05401fbc-d239-4780-b893-2e46cbbdb20c/element/72/location {}
> info: [debug] Pushing command to appium work queue: ["element:getLocation",{"elementId":"72"}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:getLocation","params":{"elementId":"72"}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getLocation
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":{"x":336,"y":569}}
> info: [debug] Responding to client with success: {"status":0,"value":{"x":336,"y":569},"sessionId":"05401fbc-d239-4780-b893-2e46cbbdb20c"}
> info: <-- GET /wd/hub/session/05401fbc-d239-4780-b893-2e46cbbdb20c/element/72/location 200 60.128 ms - 89 {"status":0,"value":{"x":336,"y":569},"sessionId":"05401fbc-d239-4780-b893-2e46cbbdb20c"}
> info: --> POST /wd/hub/session/05401fbc-d239-4780-b893-2e46cbbdb20c/touch/perform {"actions":[{"action":"press","options":{"x":486,"y":485}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"x":486,"y":188}},{"action":"release","options":{}}]}
> info: [debug] Pushing command to appium work queue: ["swipe",{"startX":486,"startY":485,"endX":486,"endY":188,"steps":28}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"swipe","params":{"startX":486,"startY":485,"endX":486,"endY":188,"steps":28}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: swipe
> info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1024,560]
> info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1024,560]
> info: [debug] [BOOTSTRAP] [debug] Swiping from [x=486.0, y=485.0] to [x=486.0, y=188.0] with steps: 28
> info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"05401fbc-d239-4780-b893-2e46cbbdb20c"}
> info: <-- POST /wd/hub/session/05401fbc-d239-4780-b893-2e46cbbdb20c/touch/perform 200 934.673 ms - 76 {"status":0,"value":true,"sessionId":"05401fbc-d239-4780-b893-2e46cbbdb20c"}
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
> info: --> GET /wd/hub/session/05401fbc-d239-4780-b893-2e46cbbdb20c/element/72/location {}
> info: [debug] Pushing command to appium work queue: ["element:getLocation",{"elementId":"72"}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:getLocation","params":{"elementId":"72"}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getLocation
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":{"x":336,"y":569}}
> info: [debug] Responding to client with success: {"status":0,"value":{"x":336,"y":569},"sessionId":"05401fbc-d239-4780-b893-2e46cbbdb20c"}
> info: <-- GET /wd/hub/session/05401fbc-d239-4780-b893-2e46cbbdb20c/element/72/location 200 62.396 ms - 89 {"status":0,"value":{"x":336,"y":569},"sessionId":"05401fbc-d239-4780-b893-2e46cbbdb20c"}
> info: --> POST /wd/hub/session/05401fbc-d239-4780-b893-2e46cbbdb20c/touch/perform {"actions":[{"action":"press","options":{"x":486,"y":470}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"x":486,"y":188}},{"action":"release","options":{}}]}
> info: [debug] Pushing command to appium work queue: ["swipe",{"startX":486,"startY":470,"endX":486,"endY":188,"steps":28}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"swipe","params":{"startX":486,"startY":470,"endX":486,"endY":188,"steps":28}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: swipe
> info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1024,560]
> info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1024,560]
> info: [debug] [BOOTSTRAP] [debug] Swiping from [x=486.0, y=470.0] to [x=486.0, y=188.0] with steps: 28
> info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"05401fbc-d239-4780-b893-2e46cbbdb20c"}
> info: <-- POST /wd/hub/session/05401fbc-d239-4780-b893-2e46cbbdb20c/touch/perform 200 933.407 ms - 76 {"status":0,"value":true,"sessionId":"05401fbc-d239-4780-b893-2e46cbbdb20c"}
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
> info: --> GET /wd/hub/session/05401fbc-d239-4780-b893-2e46cbbdb20c/element/72/location {}
> info: [debug] Pushing command to appium work queue: ["element:getLocation",{"elementId":"72"}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:getLocation","params":{"elementId":"72"}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getLocation
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":{"x":336,"y":569}}
> info: [debug] Responding to client with success: {"status":0,"value":{"x":336,"y":569},"sessionId":"05401fbc-d239-4780-b893-2e46cbbdb20c"}
> info: <-- GET /wd/hub/session/05401fbc-d239-4780-b893-2e46cbbdb20c/element/72/location 200 60.728 ms - 89 {"status":0,"value":{"x":336,"y":569},"sessionId":"05401fbc-d239-4780-b893-2e46cbbdb20c"}
> info: --> POST /wd/hub/session/05401fbc-d239-4780-b893-2e46cbbdb20c/touch/perform {"actions":[{"action":"press","options":{"x":486,"y":455}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"x":486,"y":188}},{"action":"release","options":{}}]}
> info: [debug] Pushing command to appium work queue: ["swipe",{"startX":486,"startY":455,"endX":486,"endY":188,"steps":28}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"swipe","params":{"startX":486,"startY":455,"endX":486,"endY":188,"steps":28}}
the position of element after swipe always keep [{"x":336,"y":569}] unless I use getPageSource method. the position of element changed after using getPageSource

**Comment by mykola-mokhnach** [comment]
This version is heavily out of date. Please upgrade the server and the client to the most recent version

**Comment by studyJavaForLive** [comment]
Oh, Thinks! I will try it!
