### ISSUE TITLE
iOS TextField `.text` always returns placeholder text on iOS 12.x with Xcode 11

### ISSUE THREAD

**Issue by stevechun** [appium/appium#13289]
## The problem

I have updated my environment with Xcode 11 and Appium 1.15.0.
The `text()` function on iOS TextField still works fine on iOS 13.0, which returns placeholder text when it is empty, but the entered value after typing something, but on 12.x it always returns the placeholder text.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.0
* Last Appium version that did not exhibit the issue (if applicable): 1.14.2
* Desktop OS/version used to run Appium: macOS 10.14.6 with Xcode 11
* Node.js version (unless using Appium.app|exe): 11.9.0
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: iOS 12.2, 13.0
* Real device or emulator/simulator: Simulator and actual devices
* Appium CLI or Appium.app|exe: CLI

**Comment by mykola-mokhnach** [comment]
This returned value is defined by XCTest. Unfortunately there is nothing we can do there on Appium side. Please report the problem to Apple.
