### ISSUE TITLE
iOS TextField `clear` not working on iOS 12.x with Xcode 11

### ISSUE THREAD

**Issue by stevechun** [appium/appium#13288]
## The problem

I have updated my environment with Xcode 11 and Appium 1.15.0.
The `clear` function on iOS TextField still works fine on iOS 13.0, but not anymore on 12.x

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.0
* Last Appium version that did not exhibit the issue (if applicable): 1.14.2
* Desktop OS/version used to run Appium: macOS 10.14.6 with Xcode 11
* Node.js version (unless using Appium.app|exe): 11.9.0
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: iOS 12.2, 13.0
* Real device or emulator/simulator: Simulator and actual devices
* Appium CLI or Appium.app|exe: CLI

**Comment by KazuCocoa** [comment]
Could you share the full Appium log?
It worked on my env, Xcode 11 x iOS 12.1 sim.
Like:
```
> e = @@driver.find_element :class, 'XCUIElementTypeTextField'
> e.send_keys "hello"
> e.clear
```

**Comment by studuffy** [comment]
i seem to also have this issue, running the latest appium beta, running Xcode 11 and on a sim with iOS 12.2.
 i saved the log [here](https://gist.github.com/studuffy/b196b940f19685913b67d994a632d698)

**Comment by mykola-mokhnach** [comment]
There is no magic there - WDA simply tries to enter enough delete/backspace chars into the text field to make its content disappear. This might not working properly if XcTest does not properly return the actual value or if it fails to send the actual keys. In any case there is nothing one can do from Appium side.
As a workaround you could try to perform long tap in the text field and do Select All->Delete or double tap to select the text and then press Delete. Or report the issue to Apple, which I don't think they would care much %)

**Comment by KazuCocoa** [comment]
thanks, but sorry it looks working.
Did it happen on Xcode 10 x iOS 12 with Appium 1.15.0?
I wondered it depended on the Xcode version.

**Comment by arifhussain-nbcuni** [comment]
Hi Steve, I'm trying to update my test devices to iOS 13 and updated appium to 1.15.0. I am trying to follow the instructions from https://github.com/appium/appium/blob/master/docs/en/drivers/ios-xcuitest-real-devices.md to install WebDriverAgent to my device from the new version of Appium but I don't see it in the path anymore. In previous versions of Appium, WebDriver Agent was at /path/where/installed/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent but now it's no longer in the "appium-xcuitest-driver" folder. How did you do this...

**Comment by KazuCocoa** [comment]
ah, forgot to update the page.
https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/wda-custom-server.md is updated. The path has been `node_modules/appium/node_modules/appium-webdriveragent`.

**Comment by stevechun** [comment]
> There is no magic there - WDA simply tries to enter enough delete/backspace chars into the text field to make its content disappear. This might not work properly if XcTest does not properly return the actual value or if it fails to send the actual keys. In any case there is nothing one can do from Appium side.
> As a workaround you could try to perform long tap in the text field and do Select All->Delete or double tap to select the text and then press Delete. Or report the issue to Apple, which I don't think they would care much %)

So, I'm guessing this is happening due to the issue I have found: https://github.com/appium/appium/issues/13289
I actually had to go with long tap > select all > backspace delete manually.

Just to confirm, I ran on Xcode 11, on iPhone SE simulator with iOS 12.2, latest Appium 1.15.0 release.

**Comment by mAiNiNfEcTiOn** [comment]
:) I think it's related with XCode 11's update. As an example, `getText()` only works for iOS 13, but not lower versions.

XCode 11 seems to be breaking a lot of stuff :/

**Comment by mAiNiNfEcTiOn** [comment]
I've installed their latest XCode 11.1 GM Seed, still doesn't fix it ...

One of the things I've noticed is that my PageSource now contains a lot of `XCUIElementTypeOther`... Something like this:

```jsx
<TextInput
                accessible={true}
                accessibilityLabel="BeveilingingscodeTextBox"
                autoCorrect={false}
                placeholder="Vul hier de 8 cijferige code in"
                returnKeyType="done"
                spellCheck={false}
                style={styles.formElementInput}
                keyboardType="number-pad"
                maxLength={this.state.maxLength}
                onChangeText={this.handleResponseCode}
                value={this.state.responseCode}
              />
```

Is generating:

```xml
<XCUIElementTypeOther type="XCUIElementTypeOther" name="BeveilingingscodeTextBox" label="BeveilingingscodeTextBox" enabled="true" visible="true" x="40" y="323" width="295" height="17">
  <XCUIElementTypeTextField type="XCUIElementTypeTextField" value="1234567" name="BeveilingingscodeTextBox" label="BeveilingingscodeTextBox" enabled="true" visible="true" x="40" y="323" width="295" height="17"/>
</XCUIElementTypeOther>
```

So, I was forced to do something like this to select the proper element:
```js
  const fields = await $$(`~${fieldLabel}`);
  const tags = await Promise.all(fields.map((f) => f.getTagName()));
  const field = fields.filter((f, index) => tags[index] !== 'XCUIElementTypeOther').pop();
```

#### On iOS >= 13.0
* Tests pass.

#### On iOS < 13.0
* Downgrading Appium's version does not help.
* `field.clearValue()` does not work
* `field.getText()` / `field.getValue()` return the `placeholder`'s value...
* If I remove the `placeholder` attribute it returns the `label`'s value...

**Comment by KazuCocoa** [comment]
> One of the things I've noticed is that my PageSource now contains a lot of XCUIElementTypeOther... Something like this:

Yeah, I also noticed when I testes on iOS 13. iOS 13 returns more view snapshot than iOS 12.
https://github.com/appium/WebDriverAgent/pull/225/files

btw, does [`includeNonModalElements`](https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/settings.md) setting help? It gets the snapshot from a bit different way which has been introduced in Xcode 11 GM. Update the settings API to true before getting source etc.

**Comment by mAiNiNfEcTiOn** [comment]
@KazuCocoa testing with it on `true` (since default is `false`)

**Comment by mAiNiNfEcTiOn** [comment]
So, I passed a `settings` object in the capabilities, like this:

```js
capabilities: {
  // ...
  settings: {
    includeNonModalElements: true // also tried with false
  }
}
```

This didn't seem to affect my PageSource... should it?

**Comment by mAiNiNfEcTiOn** [comment]
Ah wait... the docs mention `includeNonModalElements`, but it should be `includeNonModalDialogs` according to the PR that adds it.

**Comment by KazuCocoa** [comment]
`'settings[includeNonModalElements] ': true` if you want to add it as caps. "Update settings" section in https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md
Or http://appium.io/docs/en/commands/session/settings/update-settings/

includeNonModalElements is correct. (renamed to it)

**Comment by mAiNiNfEcTiOn** [comment]
Ah you're right... was looking at an outdated file.... Thanks for the link to the docs, testing now...

**Comment by mAiNiNfEcTiOn** [comment]
Don't know exactly how to interpret these differences, but 

#### With _includeNonModalElements_ as `false`:
```xml
<XCUIElementTypeOther type="XCUIElementTypeOther" name="BeveilingingscodeTextBox" label="BeveilingingscodeTextBox" enabled="true" visible="true" x="40" y="267" width="295" height="29">
  <XCUIElementTypeTextField type="XCUIElementTypeTextField" value="12345671" name="BeveilingingscodeTextBox" label="BeveilingingscodeTextBox" enabled="true" visible="true" x="40" y="267" width="295" height="28"/>
</XCUIElementTypeOther>
```

#### With _includeNonModalElements_ as `true`:

```xml
<XCUIElementTypeOther type="XCUIElementTypeOther" name="BeveilingingscodeTextBox" label="BeveilingingscodeTextBox" enabled="true" visible="false" x="40" y="267" width="295" height="29">
  <XCUIElementTypeTextField type="XCUIElementTypeTextField" value="Vul hier de 8 cijferige code in" name="BeveilingingscodeTextBox" label="BeveilingingscodeTextBox" enabled="true" visible="false" x="40" y="267" width="295" height="28"/>
</XCUIElementTypeOther>
```

Apparently if I set it to `true` it reflects what is returned in the `getText()` ?

**Comment by KazuCocoa** [comment]
Thanks 👀 

I hope... but I have no exact answer, sorry. we should know more about the API.
A known issue for it is visibility attribute.  We addressed 
`shouldUseTestManagerForVisibilityDetection` in `includeNonModalElements`'s description.

**Comment by mAiNiNfEcTiOn** [comment]
I've tested with all possible combinations:

```
| includeNonModalElements | shouldUseTestManagerForVisibilityDetection |
| true                    | true                                       |
| false                   | false                                      |
| false                   | true                                       |
| true                    | false                                      |
```

Unfortunately the return value of both getValue() and getText() is still the placeholder value

**Comment by KazuCocoa** [comment]
thanks so much.
It means we cannot get the value even if we use vanilla XCUITest

**Comment by mAiNiNfEcTiOn** [comment]
> I hope... but I have no exact answer, sorry. we should know more about the API.

It doesn't matter, you're giving some of your time to help me, I really appreciate that! 👍 Thank you very much for that...

**Comment by mykola-mokhnach** [comment]
Might be related to https://github.com/appium/appium/issues/13302

**Comment by Siddh010** [comment]
In iOS 13  with Appium 1.15  I am getting ESOCKETTIMEDOUT  exception message  while performing clear command request . After  3 rd request only I am able to get 200 response from server.


[debug] [35m[XCUITest][39m Executing command 'clear'
[debug] [35m[WD Proxy][39m Matched '/element/8C010000-0000-0000-AF02-000000000000/clear' to command name 'clear'
[debug] [35m[WD Proxy][39m Proxying [POST /element/8C010000-0000-0000-AF02-000000000000/clear] to [POST http://localhost:64323/session/E3361CC1-9F13-4974-B26D-19A61BD6E6D1/element/8C010000-0000-0000-AF02-000000000000/clear] with no body
[35m[WD Proxy][39m Got an unexpected response with status undefined: {"code":"ESOCKETTIMEDOUT","connect":false}
[debug] [35m[WD Proxy][39m Matched '/element/8C010000-0000-0000-AF02-000000000000/clear' to command name 'clear'
[debug] [35m[WD Proxy][39m Proxying [POST /element/8C010000-0000-0000-AF02-000000000000/clear] to [POST http://localhost:64323/session/E3361CC1-9F13-4974-B26D-19A61BD6E6D1/element/8C010000-0000-0000-AF02-000000000000/clear] with no body
[35m[WD Proxy][39m Got an unexpected response with status undefined: {"code":"ESOCKETTIMEDOUT","connect":false}
[debug] [35m[WD Proxy][39m Matched '/element/8C010000-0000-0000-AF02-000000000000/clear' to command name 'clear'
[debug] [35m[WD Proxy][39m Proxying [POST /element/8C010000-0000-0000-AF02-000000000000/clear] to [POST http://localhost:64323/session/E3361CC1-9F13-4974-B26D-19A61BD6E6D1/element/8C010000-0000-0000-AF02-000000000000/clear] with no body
[debug] [35m[WD Proxy][39m Got response with status 200: {
[debug] [35m[WD Proxy][39m   "value" : null,
[debug] [35m[WD Proxy][39m   "sessionId" : "E3361CC1-9F13-4974-B26D-19A61BD6E6D1"
[debug] [35m[WD Proxy][39m }

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by borisfernando** [comment]
Saw the same issue with an iPhone X - 12.2, Appium 1.15.1 and Xcode 11.2. After downgrading to Xcode to 10.3, this is working normally.

**Comment by Dkim257** [comment]
> Saw the same issue with an iPhone X - 12.2, Appium 1.15.1 and Xcode 11.2. After downgrading to Xcode to 10.3, this is working normally.

Exactly same with my environment and results.

**Comment by TH2M2Z** [comment]
I have executed element.clear on textfield correctly with iOS 12.4 and the latest release of Xcode 11.4

**Comment by Amrkamel1** [comment]
@KazuCocoa 
having same issue with IOS 13
ele.clear() remove first letter only

**Comment by PHUITesting** [comment]
Seeing the same issue, it fails silently, and tries to go on. It seems to believe it has cleared the field. Also works on android just fine.

**Comment by SharmaKKamal** [comment]
The verified solution for clearing the text in IOS Simulator or device
MobileElement element = driver.findElement(By.id("id_data"));
Rectangle rectangle = element.getRect();
int YAxis = element.getCenter().getY();
int XAxis = rectangle.getWidth();
TouchAction action = new TouchAction(this.getIOSDriver());
action.tap(TapOptions.tapOptions().withPosition(PointOption.point(XAxis, YAxis))).perform();
element.clear();

Verified on Simulator iOS 14.3 with appium 1.21.0
