### ISSUE TITLE
isKeyboardShown() method always returns true, even if keyboard is not visible on ios simulator.

### ISSUE THREAD

**Issue by hadrianjmnz90** [appium/appium#13287]
## The problem

The problem is for ios simulator, always that i launch an app, the keyboard is not present so i have to manually enable it, which makes automation impossible, because the keyboard should be automatically connected, anyways, i am trying to send 'shift' + 'command' + 'K' to connect the keyboard if the keyboard is not shown, but method 'isKeyboardShown' always returns 'true' for me, but the keyboard is not visible on the screen. 
driver.isKeyboardShown();
## Environment

* Appium version 1.14.1
* MacOS Mojave 10.14.5
* Node.js version v12.8.1
* Mobile platform/version under test: IOS 12.2
* Real device or emulator/simulator: simulator iphone 8 plus 
* Appium CLI or Appium.app|exe:

## Code To Reproduce Issue [ Good To Have ]
  System.out.println(driver.isKeyboardShown());
true

**Comment by KazuCocoa** [comment]
Appium asks if `XCUIElementTypeKeyboard` exists to XCTest., so it depends on Apple's implementation.
https://github.com/appium/appium-xcuitest-driver/blob/5077a8d843fc9a2da311810b58033c56fc5f9f37/lib/commands/element.js#L336

BTW, Appium turns _toggle software keyboard_ on when WDA launches to make keyboard stable. Probably, your case was turning the software keyboard off and turning hardware keyboard on.

**Comment by hadrianjmnz90** [comment]
Thanks for the comments, if someone else has this issue, or the issue that the keyboard is not displayed the first time, this is how i finally resolved it, as mentioned by @KazuCocoa  the issue is on the apple side, so these are the steps to enable the keyboard by default on any simulator.
1. Open terminal and type $ 'xcrun simctl list' to get the list of simulators and copy the UDID of your simulator.
2. Navigate to Library/Preferences (Make sure the simulator, xcode, appium, are closed.)
3. Type on the terminal $ open com.apple.iphonesimulator.plist (you can command + f, to make sure the .plist file exists) after typing and hitting enter, a window will open.
4. Click Devices and locate the UDID of your device.
![Screen Shot 2019-09-25 at 5 29 17 PM](https://user-images.githubusercontent.com/52982608/65644571-33f33a00-dfba-11e9-8ae6-cfd80f60b34b.png)
5. Click on the arrow of your device to see the options, there should be an option called 'CaptureKeyboardInput' if it is not there, just click the '+' icon and type it yourself.
![Screen Shot 2019-09-25 at 5 31 41 PM](https://user-images.githubusercontent.com/52982608/65644709-9fd5a280-dfba-11e9-9fdc-96c08a538a45.png)
6. Choose Boolean type and set the value to TRUE.

Thats it, the keyboard should be enabled by default always.

**Comment by KazuCocoa** [comment]
Thanks!
