### ISSUE TITLE
Appium inspector spinning forever with IOS 12.4.1

### ISSUE THREAD

**Issue by KS261187** [appium/appium#13294]
## The problem

I have recently upgraded my Mac to 10.14.6 and also my Xcode to 11. My iPhone is still pointing to 12.4.1. I am using Appium 1.13.0. When I try to inspect the objects using Appium inspector, the inspector keeps on spinning and the screenshot is not obtained. I know there is a similar issue going on with IOS 13 and above but I am not sure if this is the case with 12.4.1. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13.0
* Last Appium version that did not exhibit the issue (if applicable): 1.11.1
* Desktop OS/version used to run Appium:10.14.6
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: 12.4.1
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe: Appium.app

## Details

I also notice this error at the last in my Appium logs
[debug] [35m[MJSONWP (aa3bea25)][39m     at errorFromMJSONWPStatusCode (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:789:10)
[debug] [35m[MJSONWP (aa3bea25)][39m     at ProxyRequestError.errorFromMJSONWPStatusCode [as getActualError] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:683:14)
[debug] [35m[MJSONWP (aa3bea25)][39m     at JWProxy.getActualError [as command] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:235:19)
[info] [35m[HTTP][39m [37m<-- GET /wd/hub/session/aa3bea25-2dc3-46b1-8005-9188c578ec07/window/current/size [39m[31m500[39m [90m109 ms - 7725[39m
[info] [35m[HTTP][39m [90m[39m

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Xcode11 is only supported since Appium 1.15
Closed as duplicate

**Comment by javierfuentesm** [comment]
i got the same error and i have appium 1.15 ,but in the inspector i have Versión 1.13.0 (1.13.0.20190505.5) is there  a newer version for the inspector i couldnt find it in your website
