### ISSUE TITLE
@iOSFindBy() does not work with wait.until() on iOS>10.1

### ISSUE THREAD

**Issue by Mahasemamtan** [appium/appium#13298]
## The problem
I am working on mobile app and using @AndroidFindBy() and @iOSFindBy(). Basically, i have and app that has a HomePage that contains a Logo. Im trying to locate that Logo with a test. Before the HomePage, there is SplashScreen. So, i have to wait for SplashScreen to finish before HomePage with Logo appears. Problem is that on iOS versions higher than 10.1 method wait.until() does not work.

From the code example down below, there is method `getLogoIcon()` which is suppose to wait for Logo to appear up to 15 seconds before it fails the test.
Problem is that it works on Android and iOS 10.1, but it dose not work with iOS versions bigger than that. 
What happens is test starts, waits for Splash Screen to pass, HomePage appears with the Logo on it, but it is still waiting for it. And then it fails as if it did not find it.
What is even more confusing is, if i write method like this: 
```java
 public void getLogoIcon() {
      logoIcon.isDisplayed();
}
```
This will work on iOS 11,12.. So i'm not telling it to wait, but it will wait and it will locate the element and the test will pass.

## Environment

* Appium version (or git revision) that exhibits the issue: **1.14.0**
* Desktop OS/version used to run Appium: **MacOS Mojave, 10.14.6**
* Node.js version (unless using Appium.app|exe): **v12.4.0**
* Npm or Yarn package manager: **6.9.0**
* Mobile platform/version under test:**Simulator, 12.4; iPhone XR 12.0.1; iPhone 6s, 11.4.1; iPhone 7, 10.1.1**
* Real device or emulator/simulator: **Both**
* Appium CLI or Appium.app|exe: **Both**

## Appium logs

> org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of Located by By.chained({By.AccessibilityId: app_logo}) (tried for 15 second(s) with 500 milliseconds interval)

## Code To Reproduce Issue

There is page class with element: 

```java
public class PageClass extends BasePage {
    public PageClass(AppiumDriver driver) {
        this.driver = driver;
        PageFactory.initElements(new AppiumFieldDecorator(driver), this);
        wait = new WebDriverWait(driver, 15);
    }

    @AndroidFindBy(id = "logo")
    @iOSFindBy(accessibility = "app_logo")
    private WebElement logoIcon;
    public void getLogoIcon() {
        wait.until(ExpectedConditions.visibilityOf(logoIcon));
    }
}
```

Then there is test class: 

```java
public class HomePageTest extends BaseTest {

    private PageClass pageClass;

    @BeforeMethod
    public void setUp() throws MalformedURLException {
        super.setUp();
        this.pageClass = new PageClass(getDriver());
    }

    @Test
    public void testAppLogoIsDisplayed() {
        pageClass.getLogoIcon();
    }

    @AfterClass
    public void closeDriver() {
        super.tearDown();
    }
}
```

**Comment by mykola-mokhnach** [comment]
Visibility value is returned by XCTest and we don't have much influence to that. I would rather wait for element existence to make the code more reliable.

**Comment by sheikhjebran** [comment]
You can try with the below code, Hope it solves your problem

```
public static IWebElement FindBy(this By locator,int timeOut=1)
        {
            try
            {
                var wait = new WebDriverWait(Driver, TimeSpan.FromSeconds(timeOut));
                wait.Until(SeleniumExtras.WaitHelpers.ExpectedConditions.ElementExists(locator));
                return Driver.FindElement(locator);
            }
            catch (Exception)
            {
                throw new NoSuchElementException($"Unable to find {locator}");
            }
        }
```

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
