### ISSUE TITLE
Appium works very slowly when video is in background

### ISSUE THREAD

**Issue by ClassAxion** [appium/appium#13308]
## The problem

Appium works very slowly when video is in background and I want to get any element or make any action (like clicking). It takes about ~20 seconds before something happens.

I don't have any warnings / errors. Appium freezes (for about 20s) after sending data to the driver.

What can I do to speed it up or find out what's really wrong?

Thanks for help!

## Environment

Appium 1.14.2
Windows 7 64 bit
Node v10.16.2 with Npm 6.9.0
Android 5.1.1
UiAutomator2 Driver

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing much you can do. Accessibility frameworks require the application to be in idle state in order to perform action. This, most likely, is not happening when there's playing video in the background. What you could try with UIA2 is to explicitly set the `waitForIdleTimeout` setting value and/or switch to Espresso automation backend (this one is more flexible regarding idling detection).

**Comment by ClassAxion** [comment]
So, I can't delete or hide this specyfic element?

**Comment by mykola-mokhnach** [comment]
You can do it in your application source. E.g. create a special edition of it compatible with automation testing.

**Comment by ClassAxion** [comment]
Ok, but I think that I can do this using even adb.
In this case, I will try with Espresso.

I tried with setting `waitForIdleTimeout` for 2000, however still the request take about 20s, exactly on that:

`
[debug] [WD Proxy] Matched '/elements' to command name 'findElements'
[debug] [WD Proxy] Proxying [POST /elements] to [POST http://localhost:8200/wd/hub/session/a9ed8286-a6c8-4e52-b4e4-7bda96aa9481/elements] with body: {"strategy":"-android uiautomator","selector":"CENSORED","context":"","multiple":true}
`

**Comment by mykola-mokhnach** [comment]
I would rather avoid using `-android uiautomator` location strategy where possible. It is not natively supported by UIAutomator2 and is just a legacy leftover since UIA1.

Closed as third party issue
