### ISSUE TITLE
Unable to connect my iPhone.Although the web inspector was on

### ISSUE THREAD

**Issue by allenchann** [appium/appium#13303]
I'm using ios_webkit_debug_proxy to connect my iPhone.But It throw error.
![image](https://user-images.githubusercontent.com/16041349/65737931-ae36d200-e112-11e9-83b5-f0c59b430af1.png)
I'm sure the web inspector was on in my iPhone.
Version of the device is iOS13.1.
Version of the proxy is 1.8.5
![image](https://user-images.githubusercontent.com/16041349/65738037-14bbf000-e113-11e9-8746-38cf7dac541a.png)

**Comment by mykola-mokhnach** [comment]
Please report your problem directly to IWDP project. Unfortunately we cannot help nothing there.
BTW, Appium 1.15+ does not require IWDP anymore
