### ISSUE TITLE
Fail to locate an web element using "findElement" on Android 9 using Appium 1.15.0

### ISSUE THREAD

**Issue by usagikengood** [appium/appium#13306]
## The problem

After updated Appium from 1.14.1 to 1.15.0., "findElement" does not work anymore.
The testing is on android chrome with chromedriver v77.
The log didn't help much, it just responded error code "400"

The same function works again when I rollback Appium back to 1.14.1 OR I use a older chromedriver on older chrome, which I tested 2.46.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.0
* Last Appium version that did not exhibit the issue (if applicable): 1.14.1
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): 10.16.1
* Npm or Yarn package manager: npm
* Mobile platform/version under test: android 9
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

## Details
log when using appium 1.15 with chromedrive v77 and latest chrome stable version
> 2019-09-27 07:10:02:006 [W3C (c7e9fe1a)] Driver proxy active, passing request on via HTTP proxy
> 2019-09-27 07:10:02:007 [WD Proxy] Matched '/wd/hub/session/c7e9fe1a-4796-4337-aaf1-4bd45669340a/element' to command name 'findElement'
> 2019-09-27 07:10:02:007 [WD Proxy] Proxying [POST /wd/hub/session/c7e9fe1a-4796-4337-aaf1-4bd45669340a/element] to [POST http://127.0.0.1:9000/wd/hub/session/7fdd71d865ebf77e4a8fd43b45f21da2/element] with body: {"using":"id","sessionId":"c7e9fe1a-4796-4337-aaf1-4bd45669340a","value":"render-canvas"}
> 2019-09-27 07:10:02:047 [WD Proxy] Got an unexpected response with status 400: {"value":{"error":"invalid argument","message":"invalid argument: invalid locator\n  (Session info: chrome=77.0.3865.92)","stacktrace":"Backtrace:\n\tOrdinal0 [0x009BEB13+1501971]\n\tOrdinal0 [0x0093F6D1+980689]\n\tOrdinal0 [0x008C765F+489055]\n\tOrdinal0 [0x00866D0B+93451]\n\tOrdinal0 [0x00880E00+200192]\n\tOrdinal0 [0x00877A80+162432]\n\tOrdinal0 [0x0087F93E+194878]\n\tOrdinal0 [0x008778EB+162027]\n\tOrdinal0 [0x00860AC7+68295]\n\tOrdinal0 [0x00861B40+72512]\n\tOrdinal0 [0x00861AD9+72409]\n\tOrdinal0 [0x00958F37+1085239]\n\tGetHandleVerifier [0x00A5D7ED+503293]\n\tGetHandleVerifier [0x00A5D580+502672]\n\tGetHandleVerifier [0x00A646AC+531644]\n\tGetHandleVerifier [0x00A5DFFA+505354]\n\tOrdinal0 [0x00950606+1050118]\n\tOrdinal0 [0x0095047F+1049727]\n\tOrdinal0 [0x0095AF9B+1093531]\n\tOrdinal0 [0x0095B103+1093891]\n\tOrdinal0 [0x0095A095+1089685]\n\tBaseThreadInitThunk [0x772A0179+25]\n\tRtlGetAppContainerNamedObjectPath [0x7762662D+237]\n\tRtlGetAppContainerNamedObjectPath [0x776265FD+189]\n"}}
> 2019-09-27 07:10:02:047 [W3C (c7e9fe1a)] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: 400 - {"value":{"error":"invalid argument","message":"invalid argument: invalid locator\n  (Session info: chrome=77.0.3865.92)","stacktrace":"Backtrace:\n\tOrdinal0 [0x009BEB13+1501971]\n\tOrdinal0 [0x0093F6D1+980689]\n\tOrdinal0 [0x008C765F+489055]\n\tOrdinal0 [0x00866D0B+93451]\n\tOrdinal0 [0x00880E00+200192]\n\tOrdinal0 [0x00877A80+162432]\n\tOrdinal0 [0x0087F93E+194878]\n\tOrdinal0 [0x008778EB+162027]\n\tOrdinal0 [0x00860AC7+68295]\n\tOrdinal0 [0x00861B40+72512]\n\tOrdinal0 [0x00861AD9+72409]\n\tOrdinal0 [0x00958F37+1085239]\n\tGetHandleVerifier [0x00A5D7ED+503293]\n\tGetHandleVerifier [0x00A5D580+502672]\n\tGetHandleVerifier [0x00A646AC+531644]\n\tGetHandleVerifier [0x00A5DFFA+505354]\n\tOrdinal0 [0x00950606+1050118]\n\tOrdinal0 [0x0095047F+1049727]\n\tOrdinal0 [0x0095AF9B+1093531]\n\tOrdinal0 [0x0095B103+1093891]\n\tOrdinal0 [0x0095A095+1089685]\n\tBaseThreadInitThunk [0x772A0179+25]\n\tRtlGetAppContainerNamedObjectPath [0x7762662D+237]\n\tRtlGetAppContainerNamedObjectPath [0x776265FD+189]\n"}}

----
when here is the log with v2.46 chromedriver on an older chrome

> 2019-09-27 06:29:31:212 [HTTP] {"using":"id","sessionId":"128164a3-eede-4310-a7a5-4e6f64739942","value":"render-canvas"}
> 2019-09-27 06:29:31:212 [W3C (128164a3)] Driver proxy active, passing request on via HTTP proxy
> 2019-09-27 06:29:31:216 [WD Proxy] Matched '/wd/hub/session/128164a3-eede-4310-a7a5-4e6f64739942/element' to command name 'findElement'
> 2019-09-27 06:29:31:216 [WD Proxy] Proxying [POST /wd/hub/session/128164a3-eede-4310-a7a5-4e6f64739942/element] to [POST http://127.0.0.1:9010/wd/hub/session/e4f34923bcb3c3182d83a04a92f4dfb7/element] with body: {"using":"id","sessionId":"128164a3-eede-4310-a7a5-4e6f64739942","value":"render-canvas"}
> 2019-09-27 06:29:31:580 [WD Proxy] Got response with status 200: {"sessionId":"e4f34923bcb3c3182d83a04a92f4dfb7","status":0,"value":{"ELEMENT":"0.1593976008299811-1"}}
> 2019-09-27 06:29:31:581 [WD Proxy] Replacing sessionId e4f34923bcb3c3182d83a04a92f4dfb7 with 128164a3-eede-4310-a7a5-4e6f64739942

**Comment by mykola-mokhnach** [comment]
This is expected if chromedriver is working in W3C mode. The W3C standard only declares CSS and XPATH locators, where location by ids and names has been dropped as obsolete, since CSS covers them.

There are three possible ways to workaround that:
- Update the unsupported locators
- Enforce chromedriver to JSONWP mode (set `w3c` chromedriver option to `false`)
- Pass the obsolete locator types to a conversion method in the client code, which automatically upgrades them to CSS locators (this is what Selenium lib is currently doing)

**Comment by usagikengood** [comment]
Thanks for the reply. Since I am using python library, maybe I should update to use function "find_element_by_css_selector"

**Comment by fabianaapateanu** [comment]
@mykola-mokhnach we get the error  "Remote stacktrace: InvalidArgumentError: 'chromedriverArgs' must be of type object"
I don't get how we should sent this as desired capabilities: "chromedriverArgs", "{'w3c' : 'false'}"
Maybe I'm missing something. Thanks in advance. P.S. I am using the java client

**Comment by sasasa42** [comment]
@mykola-mokhnach  - How do we pass the chromeOptions desiredCapabilities. I tried the below and it still does not work. I also tried modifying the element id to Xpath, still no change. The issue is still at the invalid argument.
  
              desired_caps['browserName'] = "Chrome"
              desired_caps['chromeOptions'] = "'w3c'=False"
              desired_caps['showChromedriverLog'] = True

**Comment by KazuCocoa** [comment]
Ths output should be like: `chromeOptions: {args: ['--disable-popup-blocking']}`.
Yout case is like: `desired_caps['chromeOptions'] = {'w3c': False}`
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md
https://github.com/search?q=org%3Aappium+chromeOptions&type=Issues

**Comment by sasasa42** [comment]
@KazuCocoa - I even tried the below:
              desired_caps['browserName'] = "Chrome"
              desired_caps['chromeOptions'] = {'w3c': False}
              desired_caps['showChromedriverLog'] = True
No change still

**Comment by chenry35** [comment]
"Pass the obsolete locator types to a conversion method in the client code, which automatically upgrades them to CSS locators (this is what Selenium lib is currently doing)"

Well, the upgrade is already in the appium code, but its commented.

Check the webdriver.py in appium folder

**Comment by sasasa42** [comment]
@chenry35 It works! Thank you! Good that you gave a clue. What I did was, I converted the "id" locator elements to "CSS". But, I tried to uncomment the code for the function "find_element" in webdriver.py and it did not succeed. Even though the "self.w3c" was set to False, the W3C mode was ON. Anyway, it works now with the workaround on Android Chrome backed browsers.

**Comment by mykola-mokhnach** [comment]
> Well, the upgrade is already in the appium code, but its commented.

it is not an upgrade, but rather an ugly workaround. The problem is that in native context we don't want such transformation to happen, but only in web context. Although, it would be very expensive to verify the current context each time element location request is sent.

**Comment by mstrelex** [comment]
> This is expected if chromedriver is working in W3C mode. The W3C standard only declares CSS and XPATH locators, where location by ids and names has been dropped as obsolete, since CSS covers them.
> 
> There are three possible ways to workaround that:
> 
> * Update the unsupported locators
> * Enforce chromedriver to JSONWP mode (set `w3c` chromedriver option to `false`)
> * Pass the obsolete locator types to a conversion method in the client code, which automatically upgrades them to CSS locators (this is what Selenium lib is currently doing)

@mykola-mokhnach So the reason why Appium is not doing it internally for all element finding requests as Selenium does, is the time required to understand what is the context - web or native ? Thanks.

**Comment by mykola-mokhnach** [comment]
@mstrelex exactly

**Comment by Gabriel-LMs** [comment]
@mykola-mokhnach I have a doubt. I have a appium based project and a desktop chrome project. In my appium project i work with a app webview, where the login page is native. In the webview now i am unable to use the ID locator, i understand that this is a W3C standard and i must use CSS. 

My question is, using pure selenium that uses the same chromedriver on desktop, i will have to use CSS or am i still able to use ID?

The android chrome, doesn't support ID either?

If so i use ID in chrome desktop, what is the different between implementations between appium and selenium?

The documentation (http://appium.io/docs/en/commands/element/find-element/index.html) will be updated, so it won't cause misunderstanding?

**Comment by KazuCocoa** [comment]
You should use css for the desktop chromedriver.
Selenium clients convert `id` etc to `css` selector inside them when they behave as W3C as a workaround for OSS/W3C compatibility.
e.g. https://github.com/SeleniumHQ/selenium/blob/62e867b42e503e2171f9792d706e7adba783757e/rb/lib/selenium/webdriver/remote/bridge.rb#L602-L617 

Appium clients do not have such converter since Appium needs selectors like `id` and `class`  for the native context, unlike selenium.

**Comment by Gabriel-LMs** [comment]
Thank you very much for the explanation, it helped and clearly a lot of my doubts.

**Comment by satymaju** [comment]
> @chenry35 It works! Thank you! Good that you gave a clue. What I did was, I converted the "id" locator elements to "CSS". But, I tried to uncomment the code for the function "find_element" in webdriver.py and it did not succeed. Even though the "self.w3c" was set to False, the W3C mode was ON. Anyway, it works now with the workaround on Android Chrome backed browsers.

How did you convert id to css ?

**Comment by SurekhaG123** [comment]
Hi @KazuCocoa ,
Can you plz help me..
I am working on Hybrid App with Android 9 Version where i am not able to identify controls.
Android 6 Version its working perfectly. 
Am i missing somethng.. 
Versions I used.
Appium 1.15.1
Android 9

**Comment by KazuCocoa** [comment]
Did you mean in the WebView context?
I cannot say anything without logs, but probably it depends on chromedriver. Possible thing you can do is update chromedriver/WebView on the device side. Appium itself cannot help anything then.

**Comment by SurekhaG123** [comment]
Hi Kazuaki,
 Thank you for your response.
 I am actually testing an Cordova hybrid app which was working perfectly
for Android 6(which was using webviews). But from android 7 its not
identifying elements, Its neither showing up any error. but taking the
whole object as single element.
Device is having Chrome 85.0.4.138.127
ChromeDriver i installed 85.0.4
I provided the chromedriver path here in capabilities.

     capabilities.setCapability("chromedriverUseSystemExecutable",true);
capabilities.setCapability("chromedriverExecutable","\\Resources\\chromedriver.exe");

But am seeing the same issue, whole page as single object.
Can you plz help me.

**Comment by SurekhaG123** [comment]
Hi Kazuaki,
 Can you please give some suggestions in this case.
Following is what i am using
Appium: 1.18.0(i previously used 1.15.1, its same issue)
Android : 9 version

**Comment by KazuCocoa** [comment]
I haven't worked with Cordova app. If it did not work depending on OS versions, I guess Cordova app has an issue to integrate with apps. e.g. some chrome driver works but some do not.
Asking possibility in Cordova community may be better than here. (then, I guess it is not Appium specific. More Cordova and chromedriver stuff)

**Comment by SurekhaG123** [comment]
Hi Kazuaki Matsuo  ,
Morning.

Can you please clarify few doubts regarding Appium
1. Will appium work same with Android 6 and Android 9(Do we have any
security type things in upgraded versions of devices which is
restricting Appium)
2. If the tags are div tags in app, Appium is not identifying them. When
they are some input tags, then its identifyting perfectly. Is that
anything with appium?

Thank You

**Comment by KazuCocoa** [comment]
1)

> Will appium work same with Android 6 and Android 9

In appium level, yes. But exact behaviour depends on OS versions. For example, if Android 9 had an issue in some Android test framework, the behaviour could be different. WebView as well.
Appium depends on Android native test frameworks (UIAutomator, Espresso, adb etc) and chromedriver for Android.

2)

I don't know Cordova apps can work fully with such native test frameworks and chromedriver (WebViews), but if they cannot, Appium cannot work well.
So, it seems Cordova behaved so for Android frameworks for me. > _the tags are div tags in app_  did not work but _they are some input tags, then its identifyting perfectly_ worked

**Comment by shankar1892** [comment]
> This is expected if chromedriver is working in W3C mode. The W3C standard only declares CSS and XPATH locators, where location by ids and names has been dropped as obsolete, since CSS covers them.
> 
> There are three possible ways to workaround that:
> 
> * Update the unsupported locators
> * Enforce chromedriver to JSONWP mode (set `w3c` chromedriver option to `false`)
> * Pass the obsolete locator types to a conversion method in the client code, which automatically upgrades them to CSS locators (this is what Selenium lib is currently doing)
