### ISSUE TITLE
WebDriverAgent failed to build: Assign property / Could not build RoutingHTTPServer

### ISSUE THREAD

**Issue by faprile** [appium/appium#13307]
Hi all,
I'm trying to configure xcode for ios physical device in katalon mobile test, but I can't build a WebDriverAgent because I have these two error:

1. Semantic issue: 'assign' property of object type may become a dangling reference; consider using 'unsafe_unretained'

2. Parse Issue: Could not build module 'RoutingHTTPServer'

<img width="262" alt="Schermata 2019-09-27 alle 12 09 20" src="https://user-images.githubusercontent.com/43816080/65767434-265ec100-e12e-11e9-966b-47506b624178.png">

**Comment by insidiaGithub** [comment]
Hi, try to execute 'carthage bootstrap --paltform iOS' in folder with WebDriver agent. It helped me

**Comment by faprile** [comment]
Hi, thank you, but for me the result is "unrecognized arguments: --platform", i'm a newbie and i don't know

**Comment by faprile** [comment]
<img width="761" alt="Schermata 2019-09-27 alle 14 23 14" src="https://user-images.githubusercontent.com/43816080/65768845-6758d480-e132-11e9-8bb7-b34fd1de03d5.png">

**Comment by faprile** [comment]
<img width="902" alt="Schermata 2019-09-27 alle 14 24 26" src="https://user-images.githubusercontent.com/43816080/65768901-88212a00-e132-11e9-8559-efa2f6b47a15.png">

**Comment by ochubey** [comment]
@faprile have you tried to navigate to WebDriverAgent folder and run `./Scripts/bootstrap.sh -d`?

**Comment by faprile** [comment]
@ochubey yes, i have

**Comment by mykola-mokhnach** [comment]
Consider contacting Katalon customer support - they should know better about their product (especially if you pay for it)

**Comment by faprile** [comment]
@mykola-mokhnach but the problem is with webdriveragent in xcode.
the build of webdriveragent not run

**Comment by mykola-mokhnach** [comment]
I don't think so - it works for other people, which use Appium

**Comment by faprile** [comment]
I'm at the stage where I have to made the webdriver build, katalon has nothing to do with it now.
now I'm in the "xcode -> webdriver -> build" phase and the build doesn't work, the errors are those and katalon hasn't entered the scene yet. 
I find nothing anywhere. the webdriver I used is this https://github.com/facebookarchive/WebDriverAgent, because appium is not generating it

**Comment by mykola-mokhnach** [comment]
> https://github.com/facebookarchive/WebDriverAgent

This repository has been abandoned a while ago and nobody is going to help there. We maintain our own WDA fork

**Comment by faprile** [comment]
yes, sure, but I execute all steps and not found webdriver in appium node_modules etc

Step 1 : Install Homebrew
   			https://brew.sh/
   			brew -v
   			which brew

Step 2 : Install Node.js 
    			brew install node
    			node -v
    			npm -v
    			which node

Step 3 : Install appium
    			npm install -g appium
    			npm install -g appium@xxx
    			appium -v
    			which appium

Step 4 : Open Katalon Studio
     			Add location of Appium

Step 5 : Get Xcode
    			Xcode - IDE for mac
          xcode-select --install
              
Step 6 : Connect your iOS device / simulator
     			get UDID of your device
    			npm install -g ios-deploy 
    			ios-deploy -c
     			instruments -s devices
    			Xcode - Devices
    			A9F18306-6B22-442B-99F4-F217A5EE8D38


Step 7 : Initialize WebDriverAgent Project

    			brew install carthage


cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
mkdir -p Resources/WebDriverAgent.bundle
sh ./Scripts/bootstrap.sh -d

**Comment by mykola-mokhnach** [comment]
since v 1.15 WDA has been moved to a separate node module

**Comment by faprile** [comment]
what? which?

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/issues/13291

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/issues/13297

**Comment by faprile** [comment]
but the path?

**Comment by faprile** [comment]
build run! thank you very much. 

the new path is: /Users/[name]/node_modules/appium-webdriveragent

**Comment by weiweixun** [comment]
I have the same issue. Can you tell how to solve it， please？  @faprile

**Comment by weiweixun** [comment]
I have the same issue. Can you tell how to solve it， please？ @faprile

**Comment by xuruijy** [comment]
hi .the same issue with you , how do u solve it?

**Comment by Iskra182** [comment]
Hello, I have the same problem too. Even changing the path to: /Users/[name]/node_modules/appium-webdriveragent

**Comment by dber521** [comment]
'assign' change to 'strong'

**Comment by faprile** [comment]
@xuruijy 
@Iskra182 

I solved by updating appium to the latest version and redoing the build. now works

**Comment by Iskra182** [comment]
> 'assign' change to 'strong'

This worked for me really thank you

**Comment by pacchan** [comment]
@faprile 
Is WebDriverAgent in the appium 1.15.1 loacted to appium-youiengine-driver?

**Comment by ufoxshuai** [comment]
> 'assign' change to 'strong'

Amazing! Thank you so much!

**Comment by pkavoo** [comment]
> 'assign' change to 'strong'

Thanks, this worked

**Comment by hadrianjmnz90** [comment]
what was the fix? how do you solve this issue?

**Comment by pkavoo** [comment]
> what was the fix? how do you solve this issue?

For my case changing 'assign' to 'strong' worked

**Comment by antivista** [comment]
> what was the fix? how do you solve this issue?

Even for my case was enough changing 'assign' to 'strong'

**Comment by harshduggall** [comment]
> carthage bootstrap --paltform iOS

Platform is misspelled.
