### ISSUE TITLE
Build WebDriverAgent - test

### ISSUE THREAD

**Issue by faprile** [appium/appium#13309]
Hi all,
I launched the test for the webdriver with the physical device id.
unfortunately it arrives at the "using singleton test manager" item and after a long time it stops.

this is the log, can someone help me?

this is the command from terminal: 

xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=...' test

this is the result

<img width="583" alt="Schermata 2019-09-27 alle 18 09 18" src="https://user-images.githubusercontent.com/43816080/65784660-d7775280-e152-11e9-80ad-1050c7ff6348.png">

this is the log

/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file  the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

#import <XCTest/XCTest.h>

#import <WebDriverAgentLib/FBDebugLogDelegateDecorator.h>
#import <WebDriverAgentLib/FBConfiguration.h>
#import <WebDriverAgentLib/FBFailureProofTestCase.h>
#import <WebDriverAgentLib/FBWebServer.h>
#import <WebDriverAgentLib/XCTestCase.h>

@interface UITestingUITests : FBFailureProofTestCase <FBWebServerDelegate>
@end

@implementation UITestingUITests

+ (void)setUp
{
  [FBDebugLogDelegateDecorator decorateXCTestLogger];
  [FBConfiguration disableRemoteQueryEvaluation];
  [FBConfiguration configureDefaultKeyboardPreferences];
  [super setUp];
}

/**
 Never ending test used to start WebDriverAgent
 */
- (void)testRunner
{
  FBWebServer *webServer = [[FBWebServer alloc] init];
  webServer.delegate = self;
  [webServer startServing];
}

#pragma mark - FBWebServerDelegate

- (void)webServerDidRequestShutdown:(FBWebServer *)webServer
{
  [webServer stopServing];
}

@end

**Comment by faprile** [comment]
<img width="698" alt="Schermata 2019-10-01 alle 09 31 54" src="https://user-images.githubusercontent.com/43816080/65942796-58259f80-e42e-11e9-86bc-dad2b9df66e2.png">

**Comment by faprile** [comment]
Restarting after unexpected exit or crash in UITestingUITests/testRunner; summary will include totals from previous launches.



Test Suite 'Selected tests' started at 2019-09-30 18:31:39.502

Test Suite 'WebDriverAgentRunner.xctest' started at 2019-09-30 18:31:39.502

Test Suite 'WebDriverAgentRunner.xctest' failed at 2019-09-30 18:31:39.502.

Executed 1 test, with 1 failure (0 unexpected) in 0.000 (0.000) seconds

Test Suite 'WebDriverAgentLib.framework' started at 2019-09-30 18:31:39.502

Test Suite 'WebDriverAgentLib.framework' passed at 2019-09-30 18:31:39.502.

Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.000) seconds

Test Suite 'Selected tests' failed at 2019-09-30 18:31:39.502.

Executed 1 test, with 1 failure (0 unexpected) in 0.000 (0.001) seconds

2019-09-30 18:31:39.822 xcodebuild[10970:81846] [MT] IDETestOperationsObserverDebug: 3557.916 elapsed -- Testing started completed.

2019-09-30 18:31:39.822 xcodebuild[10970:81846] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start

2019-09-30 18:31:39.822 xcodebuild[10970:81846] [MT] IDETestOperationsObserverDebug: 3557.916 sec, +3557.916 sec -- end



Test session results, code coverage, and logs:

/Users/francescoaprile/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Test-WebDriverAgentRunner-2019.09.30_17-32-19-+0200.xcresult



Failing tests:

WebDriverAgentRunner:

-[UITestingUITests testRunner]



** TEST FAILED **

**Comment by faprile** [comment]
Failed _shouldMakeReadyForDevelopment check even though device is not locked by passcode."

**Comment by faprile** [comment]
One of the two will be used. Which one is undefined.
Test Suite 'All tests' started at 2019-10-01 09:56:32.974
Test Suite 'WebDriverAgentRunner.xctest' started at 2019-10-01 09:56:32.974
Test Suite 'UITestingUITests' started at 2019-10-01 09:56:32.975
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.00s Start Test at 2019-10-01 09:56:32.988
    t =     0.00s Set Up
2019-10-01 09:56:33.035465+0200 WebDriverAgentRunner-Runner[866:90065] Built at Oct  1 2019 09:52:03
2019-10-01 09:56:33.093848+0200 WebDriverAgentRunner-Runner[866:90065] ServerURLHere->http://192.168.1.44:8100<-ServerURLHere
2019-10-01 09:56:33.095143+0200 WebDriverAgentRunner-Runner[866:90222] Using singleton test manager
  error in connection_block_invoke_2: Connection interrupted

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
