### ISSUE TITLE
Appium 1.15 with IOS 13 not able to fire JavaScript  

### ISSUE THREAD

**Issue by Nesaganesh** [appium/appium#13310]
## The problem

Not able to fire Javascript on iOS 13 with Appium 1.15

The below code works fine in Appium 1.15 on iOS 12 but not with iOS 13 and above

string message = "window.postMessage('" + script + "','*');";
((IJavaScriptExecutor)driver).ExecuteScript(message);

## Environment

Appium Version: 1.15
iOS real device version : 13.1

DriverOptions driverOptions = new AppiumOptions();
driverOptions.AddAdditionalCapability(CapabilityType.BrowserName, "Safari");
driverOptions.AddAdditionalCapability("automationName", "XCUITest");
driverOptions.AddAdditionalCapability(MobileCapabilityType.DeviceName, "*****");
driverOptions.AddAdditionalCapability(MobileCapabilityType.PlatformName, "ios");
driverOptions.AddAdditionalCapability(MobileCapabilityType.PlatformVersion, "13");
driverOptions.AddAdditionalCapability("buldleId", "none");
driverOptions.AddAdditionalCapability("realDeviceLogger", "/usr/local/lib/node_modules/deviceconsole/deviceconsole");
driverOptions.AddAdditionalCapability("safariAllowPopups", false);
driverOptions.AddAdditionalCapability("startIWDP", true);
driverOptions.AddAdditionalCapability("xcodeOrgId", "*****");
driverOptions.AddAdditionalCapability("xcodeSigningId", "iPhone Developer");
driverOptions.AddAdditionalCapability("newCommandTimeout", 90);
driverOptions.AddAdditionalCapability("forceMjsonwp", true);
driverOptions.AddAdditionalCapability("includeSafariInWebviews", true);

## Link to Appium logs
https://gist.github.com/Nesaganesh/85b28739ea809a010d97ac9ddcb096eb

**Comment by imurchie** [comment]
Thanks for making a new issue!

I'm working on setting up a scenario where this can happen. In the meantime, can you set the capability `showSafariConsoleLog` to `true`, just to see if anything is happening in the Console that might point toward a problem?

**Comment by imurchie** [comment]
I can't get it to hang... perhaps that's something weird on your system.

I _can_, however get it to do nothing using the form you are using. Can you try a script where you get the window first, and send the message there?
```js
var w = document.getElementById('idOfWindow').contentWindow;
w.postMessage('hi how are you today', '*');"
```

**Comment by imurchie** [comment]
There have also been some changes to handling webviews/Safari that are particularly useful for iOS 13 and 13.1. If you can, try `appium@beta` (should install version `1.16.0-beta.1`).

**Comment by imurchie** [comment]
My next thing is to try on https, which requires a little more setup on my part.

**Comment by imurchie** [comment]
Hmm. Exact same behavior with https.

Perhaps you can outline what you are doing so I can reproduce?

**Comment by Nesaganesh** [comment]
@imurchie  I tried the very basic javascript command still its not returning anything 

and updated appium with 1.16.0-beta.1 but not able to  detch the dependencies of WDA so not able to build the app with below error message

**Comment by Nesaganesh** [comment]
On appium@1.16..0-beta.1

I managed to resolve the dependency issues and execute javascript and below are the logs.

And sometimes I am getting issues of not able to find element also, dont know why ? 

https://gist.github.com/Nesaganesh/dbe5db74664d5be07160befaba41f5c3

**Comment by imurchie** [comment]
The only JS logs I'm seeing involve some security problems
```
2019-09-30 11:12:46:569 - [SafariConsole] [WARNING][https://m-grumpy-cat.spinsport.ludologic.com/Resources/script/Betway/mobile/en/PushCore?v=8.26.0.1056 2:466016] [blocked] The page at https://m-grumpy-cat.spinsport.ludologic.com/sports_betway_com/en/sports?clienttypeid=1 was not allowed to run insecure content from ws://uipwspidif001:8080/diffusion?ty=WB&v=15&ca=8&r=0.
2019-09-30 11:12:46:569 - [SafariConsole] [WARNING][https://m-grumpy-cat.spinsport.ludologic.com/Resources/script/Betway/mobile/en/PushCore?v=8.26.0.1056 2:466016] 
```
I need to fix the messages for repeated logs, but this one keeps happening.

Did you try finding the element for the window and using that?

**Comment by cschabetsberger-micro-focus** [comment]
I think I am having the same issue. It looks like that sometimes no response is returned after sending _rpc_forwardSocketData when calling the /execute/sync or /execute/async endpoint.

For example:
[HTTP] --> POST /wd/hub/session/5d58aede-f277-474a-a6a5-e9860ab08111/execute/sync
[HTTP] {"script":"!function(e,t,n,r,o){var i;!function(i,a){function s(e){var t=e.length,n=he.type(e);return!he.isWindow(e)&&(!(1!==e.nodeType||!t)||(\"array\"===n||\"function\"!==n&&(0===t||\"number\"==typeof t&&t>0&&t-1 in e)))}function u(e){var t=Le[e]={};return he.each(e.match(ve)||[],function(e,n){t[n]=!0}),t}function l(e,t,n,r){if(he.acceptData(e)){var o,i,s=he.expando,u=e.nodeType,l=u?he.cache:e,c=u?e[s]:e[s]&&s;if(c&&l[c]&&(r||l[c].data)||n!==a||\"string\"!=typeof t)return c||(c=u?e[s]=ae.pop()||he.guid++:s),l[c]||(l[c]=u?{}:{toJSON:he.noop}),\"object\"!=typeof t&&\"function\"!=typeof t||(r?l[c]=he.extend(l[c],t):l[c].data=he.extend(l[c].data,t)),i=l[c],r||(i.data||(i.data={}),i=i.data),n!==a&&(i[he.camelCase(t)]=n),\"string\"==typeof t?(o=i[t],null==o&&(o=i[he.camelCase(t)])):o=i,o}}function c(e,t,n){if(he.acceptData(e)){var r,o,i=e.nodeType,a=i?he.cache:e,s=i?e[he.expando]:he.expando;if(a[s]){if(t&&(r=n?a[s]:a[s].data)){he.isArray(t)?t=t.concat(he.map(t,he.camelCase)):t in r?t=[t]:(
[debug] [W3C (5d58aede)] Calling AppiumDriver.execute() with args: ["!function(e,t,n,r,o){var i;!function(i,a){function s(e){var t=e.length,n=he.type(e);return!he.isWindow(e)&&(!(1!==e.nodeType||!t)||(\"array\"===n||\"function\"!==n&&(0===t||\"number\"==typeof t&&t>0&&t-1 in e)))}function u(e){var t=Le[e]={};return he.each(e.match(ve)||[],function(e,n){t[n]=!0}),t}function l(e,t,n,r){if(he.acceptData(e)){var o,i,s=he.expando,u=e.nodeType,l=u?he.cache:e,c=u?e[s]:e[s]&&s;if(c&&l[c]&&(r||l[c].data)||n!==a||\"string\"!=typeof t)return c||(c=u?e[s]=ae.pop()||he.guid++:s),l[c]||(l[c]=u?{}:{toJSON:he.noop}),\"object\"!=typeof t&&\"function\"!=typeof t||(r?l[c]=he.extend(l[c],t):l[c].data=he.extend(l[c].data,t)),i=l[c],r||(i.data||(i.data={}),i=i.data),n!==a&&(i[he.camelCase(t)]=n),\"string\"==typeof t?(o=i[t],null==o&&(o=i[he.camelCase(t)])):o=i,o}}function c(e,t,n){if(he.acceptData(e)){var r,o,i=e.nodeType,a=i?he.cache:e,s=i?e[he.expando]:he.expando;if(a[s]){if(t&&(r=n?a[s]:a[s].data)){he.isArray(t)?t=t.concat(he.map(t,he.camelCase)):t in r?t=[t]:(t=he.camelCase(t),t=t in r?[t]...
[debug] [XCUITest] Executing command 'execute'
[debug] [RemoteDebugger] Executing atom 'execute_script'
[debug] [RemoteDebugger] Executing 'execute_script' atom in default context
[debug] [RemoteDebugger] Sending javascript command: '(function(){return function(){var e=this;
[debug] [RemoteDebugger] funct...'
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:623', page '1', target 'page-6' (id: 15)

No response is received after this. I think target "page-6" was correctly determined (i.e. the "No target found" message is not in the log output).

I can reproduce this issue 9 of 10 times when executing on an iOS physical device (iPhone XR) running iOS 13.1.2 (Xcode 11.0, MacOS Mojave 10.14.4). It works better on iOS 11.0 Simulators but also fails sometimes. I also tried it with Appium 1.16.0-beta.1 but this did not make any difference. Is there anything else, I could try?

**Comment by imurchie** [comment]
@cschabetsberger-micro-focus Since this is not Javascript I can run, does it reproduce when executing something simple?

**Comment by imurchie** [comment]
I can reproduce this on a real device. I have a way to get it to work but need to experiment a bit to make sure.

**Comment by imurchie** [comment]
Can you try the steps outlined here: https://github.com/appium/appium/issues/13285#issuecomment-537210985

**Comment by fabianaapateanu** [comment]
Hi guys, I am having the same issue on a real iOS device and a mobile hybrid app when trying to executeScript with javascript when being in webview context: the same as @cschabetsberger-micro-focus, hangin after "..._rpc_forwardSocketData"

**Comment by imurchie** [comment]
@fabianaapateanu Did you try what I wrote in the previous comment?

**Comment by fabianaapateanu** [comment]
@imurchie I've read it, but I'll try it tomorrow morning when I'm in the office again :) my macbook battery is running low :)) 
thanks and I'll comment my feedback tomorrow.

**Comment by cschabetsberger-micro-focus** [comment]
@imurchie I executed the steps mentioned but unfortunately it did not help. I don't think it matters which data is sent via _rpc_forwardSocketData. At some point, response is returned anymore. Another example where it definitely fails is the following:

[HTTP] --> GET /wd/hub/session/27418889-f8bd-441d-b201-c5a03abd0ba1/title
[HTTP] {}
[debug] [W3C (27418889)] Calling AppiumDriver.title() with args: ["27418889-f8bd-441d-b201-c5a03abd0ba1"]
[debug] [XCUITest] Executing command 'title'
[debug] [RemoteDebugger] Executing atom 'title'
[debug] [RemoteDebugger] Executing 'title' atom in default context
[debug] [RemoteDebugger] Sending javascript command: '(function(){return function(){var g=this;functi...'
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:1325', page '1', target 'page-6' (id: 14)

I am simply executing webDriver.getTitle() via Appium Java bindings.

**Comment by cschabetsberger-micro-focus** [comment]
I have narrowed down a small example where it is 100% reproducible for me (most of the time at the first iteration):

`public static void main(String[] args) throws MalformedURLException {
    DesiredCapabilities caps = new DesiredCapabilities();
    caps.setCapability("automationName", "XCUITest");
    caps.setCapability("browserName", "safari");
    caps.setCapability("udid", "00008020-000151610C46002E");
    caps.setCapability("deviceName", "Silk iPhone XR");
    caps.setCapability("platformName", "iOS");
    caps.setCapability("platformVersion", "13.1.2");
    caps.setCapability("waitForQuiescence", false);

    IOSDriver driver = new IOSDriver(new URL("http://10.5.11.47:4723/wd/hub"), caps);
    try {
      String webContext = getFirstNonNativeContextHandle(driver);
      driver.context(webContext);
      driver.get("http://www.example.com/");

      for (int i = 0; i < 100; i++) {
        System.out.println("Iteration " + (i + 1));
        System.out.println(driver.getTitle());
      }
    }
    finally {
      driver.quit();
    }
  }

  private static String getFirstNonNativeContextHandle(IOSDriver driver) {
    for (Object context : driver.getContextHandles()) {
      String contextValue = String.valueOf(context);
      if (context != null && !"NATIVE_APP".equals(contextValue)) {
        return contextValue;
      }
    }
    throw new RuntimeException("Unable to find any web context");
  }`

**Comment by cschabetsberger-micro-focus** [comment]
Ok, I started from scratch, updated to Appium 1.16.0-beta.1, ran the example and it seems to work, so something probably went wrong on my first update attempt. I will further investigate this.

**Comment by mykola-mokhnach** [comment]
Closed as fixed
