### ISSUE TITLE
The different two result,one value is real, another value is blank, when I use the same method of getAttribute("name").  

### ISSUE THREAD

**Issue by studyJavaForLive** [appium/appium#13316]
## The problem

Hello,
Dispose the same elment.i use the method of getAttribute("name"), two result appear.
Executed 300 times,return 3 blank values.
please give me a hand.
Thanks!
## Environment

* Appium version (or git revision) that exhibits the issue: 1.4.16.1
* Desktop OS/version used to run Appium: window10
* Node.js version (unless using Appium.app|exe): v10.16.0
* Npm or Yarn package manager:6.9.0
* Mobile platform/version under test: Android 6.0

## Link to Appium logs
the value is blank:
> info: --> GET /wd/hub/session/d944cc49-44f3-4c1a-b12a-f961d0a22612/element/48/attribute/resourceId {}
> info: [debug] Pushing command to appium work queue: ["element:getAttribute",{"elementId":"48","attribute":"resourceId"}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:getAttribute","params":{"elementId":"48","attribute":"resourceId"}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getAttribute
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0}
> info: [debug] Responding to client with success: {"status":0,"value":"","sessionId":"d944cc49-44f3-4c1a-b12a-f961d0a22612"}
> info: <-- GET /wd/hub/session/d944cc49-44f3-4c1a-b12a-f961d0a22612/element/48/attribute/resourceId 200 46.058 ms - 74 {"status":0,"value":"","sessionId":"d944cc49-44f3-4c1a-b12a-f961d0a22612"}
> info: --> GET /wd/hub/session/d944cc49-44f3-4c1a-b12a-f961d0a22612/element/45/attribute/name {}
> info: [debug] Pushing command to appium work queue: ["element:getAttribute",{"elementId":"45","attribute":"name"}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:getAttribute","params":{"elementId":"45","attribute":"name"}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getAttribute
> info: [debug] Responding to client with success: {"status":0,"value":"","sessionId":"d944cc49-44f3-4c1a-b12a-f961d0a22612"}
> info: <-- GET /wd/hub/session/d944cc49-44f3-4c1a-b12a-f961d0a22612/element/45/attribute/name 200 107.324 ms - 74 {"status":0,"value":"","sessionId":"d944cc49-44f3-4c1a-b12a-f961d0a22612"}
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":""}
the value is real:
> info: --> GET /wd/hub/session/544f2b17-facc-4b2c-b802-ec7160150545/element/48/location {}
> info: [debug] Pushing command to appium work queue: ["element:getLocation",{"elementId":"48"}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:getLocation","params":{"elementId":"48"}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getLocation
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":{"x":648,"y":309}}
> info: [debug] Responding to client with success: {"status":0,"value":{"x":648,"y":309},"sessionId":"544f2b17-facc-4b2c-b802-ec7160150545"}
> info: <-- GET /wd/hub/session/544f2b17-facc-4b2c-b802-ec7160150545/element/48/location 200 61.985 ms - 89 {"status":0,"value":{"x":648,"y":309},"sessionId":"544f2b17-facc-4b2c-b802-ec7160150545"}
> info: --> GET /wd/hub/session/544f2b17-facc-4b2c-b802-ec7160150545/element/51/attribute/resourceId {}
> info: [debug] Pushing command to appium work queue: ["element:getAttribute",{"elementId":"51","attribute":"resourceId"}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:getAttribute","params":{"elementId":"51","attribute":"resourceId"}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getAttribute
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0}
> info: [debug] Responding to client with success: {"status":0,"value":"","sessionId":"544f2b17-facc-4b2c-b802-ec7160150545"}
> info: <-- GET /wd/hub/session/544f2b17-facc-4b2c-b802-ec7160150545/element/51/attribute/resourceId 200 57.118 ms - 74 {"status":0,"value":"","sessionId":"544f2b17-facc-4b2c-b802-ec7160150545"}
> info: --> GET /wd/hub/session/544f2b17-facc-4b2c-b802-ec7160150545/element/48/attribute/name {}
> info: [debug] Pushing command to appium work queue: ["element:getAttribute",{"elementId":"48","attribute":"name"}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:getAttribute","params":{"elementId":"48","attribute":"name"}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getAttribute
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"xxxxx"}
> info: [debug] Responding to client with success: {"status":0,"value":"xxxxx","sessionId":"544f2b17-facc-4b2c-b802-ec7160150545"}
> info: <-- GET /wd/hub/session/544f2b17-facc-4b2c-b802-ec7160150545/element/48/attribute/name 200 97.313 ms - 86 {"status":0,"value":"xxxxxx","sessionId":"544f2b17-facc-4b2c-b802-ec7160150545"}

**Comment by mykola-mokhnach** [comment]
Unfortunately we don't provide patches for older server versions. Even if there is a problem, it is not going to be fixed unless you confirm with the most recent software version.
BTW, UIA1 is deprecated and should not be used with Android 6+

**Comment by studyJavaForLive** [comment]
OK, I will try my best to upgrade.Thank you very much!
