### ISSUE TITLE
[XCUITest] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string

### ISSUE THREAD

**Issue by XXOK** [appium/appium#13318]
**The Problem**
Appium Server run to iOS Real device, not running 
and log return
`selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not install app: 'The "path" argument must be of type string'`

**Environment**
Appium Version: 1.15.0
iOS real device version : 11.4.1

        desired_caps = {}
        desired_caps['bundleId'] = ''
        desired_caps['platformName'] = 'ios'
        desired_caps['platformVersion'] = '11.4.1'
        desired_caps['deviceName'] = 'iPhone 8'
        desired_caps['automationName'] = 'XCUITest'
        desired_caps['app'] = '/Users/yeonshin/Library/Developer/Xcode/DerivedData/traveler-bdjcyjbwiyeflagvvnuveopuxftj/Build/Products/Debug-iphoneos/.app'
        desired_caps['udid'] = ''
        desired_caps['xcodeOrgId'] = ''
        desired_caps['xcodeSigningId'] = 'iPhone Developer'
        desired_caps['noReset'] = 'True'
        desired_caps['newCommandTimeout'] = '30000'

**Link to Appium logs**
https://gist.github.com/XXOK/c571a5104ac5c6e3c9ea7690ce7703b2

I'm sorry for my poor English, I will share any information I need

**Comment by mykola-mokhnach** [comment]
This happens because of outdated nodejs. Appium 1.15 supports NodeJS 10+. Closed as duplicate

**Comment by XXOK** [comment]
@mykola-mokhnach 
The node version is node@12.11.0. Why is the issue still occurring?

**Comment by KazuCocoa** [comment]
Mostly such error we got here was older node versions' build issue.
They resolved it when they upgrade to newer versions.

Could you try to re-install once? On my local, the 12.11.0 x Appium 1.15.0 worked.

btw, I think `desired_caps['app'] = '/Users/yeonshin/Library/Developer/Xcode/DerivedData/traveler-bdjcyjbwiyeflagvvnuveopuxftj/Build/Products/Debug-iphoneos/.app'`'s the fine name should be `Debug-iphoneos.app`

**Comment by spaz-one-two** [comment]
@mykola-mokhnach @XXOK @KazuCocoa Hey folks. I am currently observing this very same error when trying to create a session for a real iOS device. The weird thing is that everything was working fine up till this morning when it just stopped working. And no major updates have been installed on my environment. I don't want to dupe this error report so I'm going to dump as much info as I can in here. Sorry about the spam, I been scratching my head real hard with this one.
[1. Logs (with sensitive info edited out)](https://gist.github.com/spaz-one-two/bf6eb9f3b74373edab94a3f0307749f0)
2. Node is `v12.11.1`
3. Appium is `1.15.0`
4. Desired Caps (see logs)
