### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by ptagl** [appium/appium#13321]
## The problem

Hi,

I am currently using Appium for a test application that monitors the status of an Android smartphone. In particular my application runs for many hours and needs to collect many screenshots of the smartphone during the execution (by using the [getScreenshot ](http://appium.io/docs/en/commands/session/screenshot/)function).

After some hours and hundreds of screenshots collected the Appium server crashed with the following error:

**FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory**

In order to reproduce the issue I guess it is enough to put the `getScreenshot `function in an infinite loop.

## Environment

* Appium version: 1.14.2
* Desktop OS/version: Windows 10 1903 64 bit
* Node.js version: 12.6.0
* Npm or Yarn package manager:
* Mobile platform/version under test: Android 9 Pie
* Real device: Samsung S9
* Additional parameters to run Appium: --relaxed-security

## Link to Appium logs

I collected log output from two different crashes:

https://gist.github.com/ptagl/0c189d8343daebc22a8e580e4d02b7a1
https://gist.github.com/ptagl/a33dac0702cf55e6e5dbaeb4ae1190be

**Comment by mykola-mokhnach** [comment]
There was known memory leak issue related to add log collection, which was fixed since Appium 1.15, so try to upgrade first.
If the problem still happens in 1.15 then we need the heap snapshot before the OOM error happens.

**Comment by ptagl** [comment]
Hi, I installed the latest version (1.15) with NPM as you suggested and tried to run a Java application with an infinite loop: after 7500 calls to `getScreenshot` the server crashed.

I don't know exactly how to get the heap snapshot, in any case if you want to try by yourself here is the code that I ran to reproduce the crash:

https://gist.github.com/ptagl/f699166b5f01b9c8377758875b0e09cb

**Comment by ptagl** [comment]
@mykola-mokhnach could you please reopen the issue?

**Comment by mykola-mokhnach** [comment]
I would be happy to do that after heap snapshot is provided. Otherwise we cannot do nothing on the problem

**Comment by ptagl** [comment]
Hi @mykola-mokhnach,

I did not wait until the crash but I guess that this snapshot might be helpful:

[Heap-20191009T185036.zip](https://github.com/appium/appium/files/3708525/Heap-20191009T185036.zip)

Let me know if you need anything else in order to reopen the issue.

Thanks a lot!

**Comment by mykola-mokhnach** [comment]
Please try if https://github.com/appium/appium-base-driver/pull/360 works for you.

Simply get my branch from github, then perform `npm install` and `npm link` on it. More detailed tutorial (it's for different module, but should also work for `appium-base-driver`) can be found at https://github.com/appium/appium/issues/13227#issuecomment-531812534

**Comment by mykola-mokhnach** [comment]
If the problem is still there then please attach the updated snapshot

**Comment by mykola-mokhnach** [comment]
Ok, thanks for checking that. Can you please check two more things:
- run the same stuff with `_TESTING` environment variable set to `1` (this should disable all logging)
- incorporate the fix from https://github.com/appium/appium-support/pull/133

**Comment by ptagl** [comment]
I run the test for some minutes, the first attempt was just with the logs disabled (in addition to the first patch you made to the appium-base-driver):

[TESTING_1.zip](https://github.com/appium/appium/files/3713535/TESTING_1.zip)

Then I tried adding the other patched module (appium-support), still with logs disabled:

[Appium-Support.zip](https://github.com/appium/appium/files/3713536/Appium-Support.zip)

**Comment by mykola-mokhnach** [comment]
I see the problem exists, although it is still unclear how to resolve it. I believe @imurchie knows this part of codebase better than me

**Comment by imurchie** [comment]
I'm having a look.

**Comment by mykola-mokhnach** [comment]
@ptagl Could you please check https://github.com/appium/appium-base-driver/pull/362

**Comment by ptagl** [comment]
@mykola-mokhnach I tried the latest changes to the base driver and it seems much better now! I ran the test for around 3 hours, it started using 300MB or less and then it grew up very slowly reaching 800MB. After few hours I checked again and it was at 500MB, so I'm not sure if there is still some memory leak or not, but it seems like the getScreenshot command is not leaking anymore. I made the heap snapshot in case it is helpful for you.

https://we.tl/t-YPSbxMxkbl

**Comment by mykola-mokhnach** [comment]
Yep, the trace look much better now. Waiting for the PR to be reviewed and polished.
Thank you for the assistance

**Comment by mayureshshirodkar** [comment]
@mykola-mokhnach is this available on the latest beta?

**Comment by mykola-mokhnach** [comment]
@mayureshshirodkar No, the PR is still waiting for a review.

**Comment by mykola-mokhnach** [comment]
Published to appium@beta

**Comment by mayureshshirodkar** [comment]
@ptagl @mykola-mokhnach I am facing a similar issue but its inconsistent.
Could you please list the steps of how you took the heap snapshot? Would be really helpful

**Comment by ptagl** [comment]
The steps I followed to take the snapshot are:

1.  Open the terminal and go to the Appium module folder (in case of Windows OS something like _C:\Users\username\AppData\Roaming\npm\node_modules\appium_).

2. Run the command `node --inspect .` and copy the URL printed on the screen (something like `ws://127.0.0.1:9229/0f2c936f-b1cd-4ac9-aab3-f63b0f33d55e`).

3. Open Edge or Chrome and browse to `edge://inspect` or `chrome://inspect` respectively. Then paste the URL (or wait for the entry to appear automatically) and press "Inspect".

4. In the new window go to the "Memory" tab, select "Allocation instrumentation on timeline" and check "Record allocation stacks", then start the profiling.

5. When you collected enough allocations or the application crashed, stop the profiling, wait for the finalization and then save to file.

6. Optional: if the snapshot file it too big, zip it.

**Comment by mayureshshirodkar** [comment]
Thanks alot @ptagl, Will try this. (y)
