### ISSUE TITLE
Incorrect package and activity. Retrying

### ISSUE THREAD

**Issue by buutuan** [appium/appium#13324]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by buutuan** [comment]
I am getting an error of Incorrect package and activity. Retrying when I first connect to the real device and run my first program. Even though the client does connect to appium but then later timed out due to incorrect pakage and activity... retrying and then it would time out

**Comment by mykola-mokhnach** [comment]
Please provide a proper issue description and the requested data

**Comment by AnandChaurasia** [comment]
Issue description:
Appium is able to launch the application, but immediately log shows Incorrect package and activity . 
[WD Proxy] Got response with status 200: {"sessionId":"780299ed-32b4-4d0c-926d-44eb791ffa26","value":{"androidId":"36ef291161afe52f","manufacturer":"motorola","model":"Moto G (5)","brand":"motorola","apiVersion":"27","platformVersion":"8.1.0","carrierName":"Telekom.de","realDisplaySize":"1080x1920","displayDensity":480,"networks":[{"type":0,"typeName":"MOBILE","subtype":13,"subtypeName":"LTE","isConnected":true,"detailedState":"CONNECTED","state":"CONNECTED","extraInfo":"internet.telekom","isAvailable":true,"isFailover":false,"isRoaming":false,"capabilities":{"transportTypes":"NET_CAPABILITY_MMS","networkCapabilities":"","linkUpstreamBandwidthKbps":51200,"linkDownBandwidthKbps":102400,"signalStrength":-2147483648,"networkSpecifier":"1","SSID":null}},{"type":1,"typeName":"WIFI","subtype":0,"subtypeName":"","isConnected":true,"detailedState":"CONNECTED","state":"CONNECTED","extraInfo":"\"XS4GUEST\"","isAvailable":true,"isFailover":false,"isRoaming":false,"capabilities":{"transportTypes":"NET_CAPABILITY_SUPL","networkCapabilities":"","linkUpstreamBa...
[ADB] Running 'C:\Users\ananchau\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZY3223SLL3 shell dumpsys window'  

after this application is getting started and then
[ADB] Found package: '*******' and fully qualified activity name : '**********'
[ADB] Incorrect package and activity. Retrying.
