### ISSUE TITLE
iOS - Appium ignoring start_recording_screen params

### ISSUE THREAD

**Issue by grant-mccarriagher** [appium/appium#13328]
## The problem

Trying to screen record on iOS real devices. I see the command being sent to the start_recording_screen endpoint with the params I'm using, but none of them seem to be applied.

```
[HTTP] --> POST /wd/hub/session/e055b558-8266-4666-9980-99b898865c5e/appium/start_recording_screen
[HTTP] {"timeLimit":"20000","videoType":"libx264","videoQuality":"medium","videoFps":"30","bitRate":"20"}
[debug] [W3C (e055b558)] Calling AppiumDriver.startRecordingScreen() with args: [null,"e055b558-8266-4666-9980-99b898865c5e"]
[debug] [XCUITest] Executing command 'startRecordingScreen'
```

Further down, we see that ffmpeg isn't being started with the params specified:

```
[XCUITest] Starting screen capture on the device 'bd0f6967af3eee3d526fe3e28ca38d8f50aa7430' with command: 'ffmpeg -f mjpeg -i http://localhost:9100 -vcodec mjpeg -y /var/folders/vl/nnjfrgn940xbp5gddqvcsscw0000gp/T/2019830-82961-1f2uhe4.yw93i/appium_aff202.mp4'. Will timeout in 180000ms
```

## Environment

* Appium version (or git revision) that exhibits the issue: v1.15.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 10.14.5
* Node.js version (unless using Appium.app|exe): v12.10.0
* Npm or Yarn package manager: npm 6.10.3
* Mobile platform/version under test: iOS 13.1
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

https://gist.github.com/grant-mccarriagher/9e3b8aba8b0bbdd37402a8e0f9b2f3fd

## Code To Reproduce Issue [ Good To Have ]

Using webdriverio:
`driver.startRecordingScreen(undefined, undefined, undefined, undefined, undefined, '20000', 'libx264', 'medium', '30', '20');`

**Comment by mykola-mokhnach** [comment]
I think this is the client issue. The server expects `options` argument to be set: https://github.com/appium/appium-base-driver/blob/4f52b1b654f0b3cf069602eea28863802b8b1dd5/lib/protocol/routes.js#L363

**Comment by grant-mccarriagher** [comment]
Thanks, I've verified that the endpoint functions correctly with an `option` argument. I'll close this and open an issue with webdriverio.
