### ISSUE TITLE
getText() or getAttribute('value') returns empty string for iOS platform

### ISSUE THREAD

**Issue by mikesalvia** [appium/appium#13326]
## The problem

Unable to use `getText()` or `getAttribute('value')` they return nothing  in automated tests for iOS platform

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.0
* Last Appium version that did not exhibit the issue (if applicable): 1.14.1 (with older Xcode)
* Desktop OS/version used to run Appium: macOS 10.14.6
* Node.js version (unless using Appium.app|exe): 10.16.3
* Npm or Yarn package manager: Yarn
* Mobile platform/version under test: iOS 12.2
* Real device or emulator/simulator: iPhone X Simulator
* Appium CLI or Appium.app|exe: CLI

## Details

`getText()` and `getAttribute('value')` both successfully execute but return nothing, even though text is present in element. Pretty surprised this was not caught during testing but as I look at it it may have to do with Xcode version or a change in XCUITest cause it still doesn't work when downgrading Appium. Going to try to revert to an older version of Xcode to see if this helps the issue. I don't see any issues open in `appium-xcuitest-driver` for this either.

## Link to Appium logs

To be added if needed.

## Code To Reproduce Issue [ Good To Have ]

To be added if needed.

**Comment by mikesalvia** [comment]
<img width="475" alt="Screen Shot 2019-09-30 at 10 58 08 AM" src="https://user-images.githubusercontent.com/6209204/65890716-5944c700-e371-11e9-843c-5094f06c09f4.png">
Attempting to get the element text using WebDriver protocol (`browser.getElementText`) using `findElement` to determine `ELEMENT` that is passed.

**Comment by mykola-mokhnach** [comment]
Yes, you are right. Unfortunately this is the issue in XCTest itself and we cannot do nothing to change this behaviour on WDA side. 
Related issues:
https://github.com/appium/appium/issues/13288
https://github.com/appium/appium/issues/13272

**Comment by lubshilk** [comment]
With newest Xcode 11.2.1 the same problems
Is there some WA?

**Comment by deepakarorawins** [comment]
Hi Friends,
Did we get any workaround?

**Comment by sebinjqburst** [comment]
@mykola-mokhnach Do you have any idea of some workaround as the issue is a blocker for my tests?
Also, are there any issues reported to apple related to this? It would be great if you could link the issue here so that we could at least track when the same is fixed.
Thanks in advance.

**Comment by mykola-mokhnach** [comment]
the workaround would be to test iOS 12 using Xcode 10 SDK and iOS13 using Xcode 11

**Comment by sebinjqburst** [comment]
@mykola-mokhnach Great. Thank you so much :)

**Comment by nilenth** [comment]
@sebinjqburst @mykola-mokhnach Are there any new updates for this issue or are you guys still using the same workaround?  I'm currently testing an iOS 14.3 app with Xcode 12.3 and came across the same issue.

**Comment by ganjarpanji** [comment]
so basically the machine runner should have 3 different xcode versions to be able to run tests from iOS 12-14 ?
