### ISSUE TITLE
Appium server super slow on real android device while works faster on emulator.

### ISSUE THREAD

**Issue by poojachoudhary13** [appium/appium#13323]
On a few screens in our app i can see the appium is too slow to find elements. There are no animations and app is static. For GET call to findelement i can see a delay in response of 30-45 seconds and that too with resource-id. The same code and same app screen(same app version) is running on android emulator atleast 15 times faster. I am not sure what could be the reason. This is happening for a few screens only. Please help with figuring out what could be the reason.

* Appium version (or git revision) that exhibits the issue: 1.14.2
* Last Appium version that did not exhibit the issue (if applicable): not sure
* Desktop OS/version used to run Appium: mac 10.13.6
* Node.js version (unless using Appium.app|exe): node@10
* Npm or Yarn package manager: 1.13
* Mobile platform/version under test: 8.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: both

**Comment by mykola-mokhnach** [comment]
Please provide the full server log with timestamps
