### ISSUE TITLE
Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE]

### ISSUE THREAD

**Issue by aaratitambe** [appium/appium#13329]
Cannot launch application. Getting error 

[ADB] Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE]
[UiAutomator2] Deleting UiAutomator2 session
[UiAutomator2] Deleting UiAutomator2 server session
[WD Proxy] Matched '/' to command name 'deleteSession'
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
[ADB] Running 'C:\Users\arati.tambe\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 637002913815 shell am force-stop com.smartkargo.latamwarehouse'
[Logcat] Stopping logcat capture
[ADB] Removing forwarded port socket connection: 8200 
[ADB] Running 'C:\Users\arati.tambe\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 637002913815 forward --remove tcp\:8200'
[BaseDriver] Event 'newSessionStarted' logged at 1569911590564 (12:03:10 GMT+0530 (India Standard Time))
[MJSONWP] Encountered internal error running command: Error: pkg: /data/local/tmp/appium_cache/953854e9fd07ed4c860c8f19e2f9decbbe4ade85.apk

[MJSONWP] Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE]
[MJSONWP]     at ADB. (C:\Users\arati.tambe\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\apk-utils.js:524:13)
[MJSONWP]     at Generator.next ()
[MJSONWP]     at asyncGeneratorStep (C:\Users\arati.tambe\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
[MJSONWP]     at _next (C:\Users\arati.tambe\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
[MJSONWP]     at run (C:\Users\arati.tambe\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\core-js\modules\es6.promise.js:75:22)
[MJSONWP]     at C:\Users\arati.tambe\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\core-js\modules\es6.promise.js:92:30
[MJSONWP]     at flush (C:\Users\arati.tambe\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\core-js\modules\_microtask.js:18:9)
[MJSONWP]     at process._tickCallback (internal/process/next_tick.js:61:11)

## Environment

* Appium version (or git revision) that exhibits the issue: 
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: v1.13.0
[appium-server-logs.txt](https://github.com/appium/appium/files/3674746/appium-server-logs.txt)

* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Please upgrade appium to the most recent version

**Comment by mykola-mokhnach** [comment]
There is `enforceAppInstall` [capability](https://github.com/appium/appium/blob/aed49a8d6c81c1bc636ef89006ff15b5949a48be/docs/en/writing-running-appium/caps.md), which always enforces the currently given app version to be installed

**Comment by aaratitambe** [comment]
I have latest version of Appium desktop v1.13.0 
I tried to invoke other (inhouse)apk  and it was invoked successfully but with this particular apk I get above error. 

Is there any issues with apk? if yes, is there any way to figure it out?

**Comment by mykola-mokhnach** [comment]
If you don'r want to upgrade the solution would be to uninstall the previous version of the app from the device under test
