### ISSUE TITLE
[WebDriverAgent] No more Inspector support ?

### ISSUE THREAD

**Issue by hcleldaddonio** [appium/appium#13339]
##I have downloaded the last appium release and found out that there is no inspector.
After checking the commits I saw that you removed it from WebDriverAgent.

So few questions:
1) Why did you remove it?
2) Will it become supported again? if does so when it expected?

**Comment by dpgraham** [comment]
This was a feature the Facebook provided and we won't be bringing it back now that we've forked it. You can inspect a session using Appium Desktop.

**Comment by hcleldaddonio** [comment]
Can you tell the reason you stopped supporting it? Just interested.

**Comment by dpgraham** [comment]
There's no reason for us to continue supporting it.
