### ISSUE TITLE
How to identify the is the driver is alive or not? Appium driver in i

### ISSUE THREAD

**Issue by mirudhubashini** [appium/appium#13332]
@KazuCocoa Kindly let me know if there is any function to get know about the driver's current state in ios and android.

**Comment by mykola-mokhnach** [comment]
Kindly use Appium forum for questions

**Comment by mirudhubashini** [comment]
@mykola-mokhnach and @KazuCocoa I couldn’t find any function to check the alive state of the driver. Kindly help me out.

**Comment by KazuCocoa** [comment]
Your 'driver' means WDA in xcuitest-driver(iOS), for example, the state is checked by xcuitest. (Users have no way to check it via Appium server)
If it is appium server's state, for example, `/status` command would help. If you would like to check if the current session is alive is `get current session` command or send a request to the server will help like `find_element/s`

**Comment by mirudhubashini** [comment]
Okay, Thank u, will try out.
