### ISSUE TITLE
Error while obtain Appium Server logs 

### ISSUE THREAD

**Issue by pavanbachu06** [appium/appium#13337]
## Error message while requesting for Appium Server logs

Trying to obtain the appium server logs at the end of the test case, but throwing an error - 

> org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Potentially insecure feature 'get_server_logs' has not been enabled. If you want to enable this feature and accept the security ramifications, please do so by following the documented instructions at https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/security.md

## Environment

* Appium version (or git revision) that exhibits the issue: NA
* Last Appium version that did not exhibit the issue (if applicable): 1.15.0
* Desktop OS/version used to run Appium: NA
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager: npm 
* Mobile platform/version under test: Android and IOS
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Command used to initiate Appium 
`appium --allow-insecure=get_system_logs`

## Link to Appium logs
[IOS Logs](https://gist.github.com/pavanbachu06/e770e30a88c6def94f4505d9b8a22572)
[Android Logs ](https://gist.github.com/pavanbachu06/d17f4da5573c4c410462e5f0bf67755a)

**Comment by mykola-mokhnach** [comment]
The name of the feature in the error message is `get_server_logs`, although the one, which is enabled from the command line is `get_system_logs`

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
