### ISSUE TITLE
WebDriverAgent test failed on xcode simulator

### ISSUE THREAD

**Issue by faprile** [appium/appium#13333]
Hi all,
I launched the webdriveragent test on xcode simulator, but the test fail

here is the log:

/**

Copyright (c) 2015-present, Facebook, Inc.
All rights reserved.
This source code is licensed under the BSD-style license found in the
LICENSE file in the root directory of this source tree. An additional grant
of patent rights can be found in the PATENTS file in the same directory.
*/
#import <XCTest/XCTest.h>

#import <WebDriverAgentLib/FBDebugLogDelegateDecorator.h>
#import <WebDriverAgentLib/FBConfiguration.h>
#import <WebDriverAgentLib/FBFailureProofTestCase.h>
#import <WebDriverAgentLib/FBWebServer.h>
#import <WebDriverAgentLib/XCTestCase.h>

@interface UITestingUITests : FBFailureProofTestCase
@EnD

@implementation UITestingUITests

(void)setUp
{
[FBDebugLogDelegateDecorator decorateXCTestLogger];
[FBConfiguration disableRemoteQueryEvaluation];
[super setUp];
}
/**
Never ending test used to start WebDriverAgent
*/

(void)testRunner
{
FBWebServer *webServer = [[FBWebServer alloc] init];
webServer.delegate = self;
[webServer startServing];
}
#pragma mark - FBWebServerDelegate

(void)webServerDidRequestShutdown:(FBWebServer *)webServer
{
[webServer stopServing];
}
@EnD

this is the test failed:

xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=7768822F-8671-490A-8EE9-F648F0E11604' test
note: Using new build system
note: Planning build
note: Using build description from disk

Testing started on 'iPhone 8'
2019-10-01 11:06:20.346 xcodebuild[4661:107748] IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/francescoaprile/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Test-WebDriverAgentRunner-2019.10.01_11-06-19-+0200.xcresult/Staging/1_Test/Diagnostics/WebDriverAgentRunner-85660A05-FA07-4347-BBA4-43EF039134CA/WebDriverAgentRunner-299A5321-E7EB-40D8-8882-0D9E0F7BBAE2/Session-WebDriverAgentRunner-2019-10-01_110620-EwiIWV.log
2019-10-01 11:06:20.347 xcodebuild[4661:107678] [MT] IDETestOperationsObserverDebug: (1A251067-E54D-462D-B04C-762696A5374D) Beginning test session WebDriverAgentRunner-1A251067-E54D-462D-B04C-762696A5374D at 2019-10-01 11:06:20.347 with Xcode 11A420a on target <DVTiPhoneSimulator: 0x7ffca13ec410> {
SimDevice: iPhone 8 (7768822F-8671-490A-8EE9-F648F0E11604, iOS 13.0, Booted)
} (13.0 (17A577a))
2019-10-01 11:06:20.443 xcodebuild[4661:107678] [MT] IDETestOperationsObserverDebug: (1A251067-E54D-462D-B04C-762696A5374D) Finished requesting crash reports. Continuing with testing.
2019-10-01 11:06:22.288 xcodebuild[4661:107678] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-14802/IDEiOSSupportCore/DVTiPhoneSimulator.m:1890
Details: [DVTiPhoneSimulator -primaryInstrumentsServer was called from the main thread
Object: <DVTiPhoneSimulator: 0x7ffca13ec410>
Method: -primaryInstrumentsServerWithError:
Thread: <NSThread: 0x7ffc9e5080c0>{number = 1, name = main}
Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
2019-10-01 11:06:22.513058+0200 WebDriverAgentRunner-Runner[4668:107902] Running tests...
objc[4668]: Class GCDAsyncSocketPreBuffer is implemented in both /Users/francescoaprile/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer (0x1097a4a78) and /Users/francescoaprile/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/WebDriverAgentLib.framework/Frameworks/CocoaAsyncSocket.framework/CocoaAsyncSocket (0x109714738). One of the two will be used. Which one is undefined.
objc[4668]: Class GCDAsyncReadPacket is implemented in both /Users/francescoaprile/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer (0x1097a4ac8) and /Users/francescoaprile/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/WebDriverAgentLib.framework/Frameworks/CocoaAsyncSocket.framework/CocoaAsyncSocket (0x109714788). One of the two will be used. Which one is undefined.
objc[4668]: Class GCDAsyncWritePacket is implemented in both /Users/francescoaprile/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer (0x1097a4b18) and /Users/francescoaprile/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/WebDriverAgentLib.framework/Frameworks/CocoaAsyncSocket.framework/CocoaAsyncSocket (0x1097147d8). One of the two will be used. Which one is undefined.
objc[4668]: Class GCDAsyncSpecialPacket is implemented in both /Users/francescoaprile/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer (0x1097a4b68) and /Users/francescoaprile/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/WebDriverAgentLib.framework/Frameworks/CocoaAsyncSocket.framework/CocoaAsyncSocket (0x109714828). One of the two will be used. Which one is undefined.
objc[4668]: Class GCDAsyncSocket is implemented in both /Users/francescoaprile/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer (0x1097a4bb8) and /Users/francescoaprile/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/WebDriverAgentLib.framework/Frameworks/CocoaAsyncSocket.framework/CocoaAsyncSocket (0x109714878). One of the two will be used. Which one is undefined.
Test Suite 'All tests' started at 2019-10-01 11:06:22.972
Test Suite 'WebDriverAgentLib.framework' started at 2019-10-01 11:06:22.973
Test Suite 'WebDriverAgentLib.framework' passed at 2019-10-01 11:06:22.974.
Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.001) seconds
Test Suite 'WebDriverAgentRunner.xctest' started at 2019-10-01 11:06:22.975
Test Suite 'UITestingUITests' started at 2019-10-01 11:06:22.976
Test Case '-[UITestingUITests testRunner]' started.
t = 0.00s Start Test at 2019-10-01 11:06:22.982
t = 0.00s Set Up
2019-10-01 11:06:22.988784+0200 WebDriverAgentRunner-Runner[4668:107902] Built at Oct 1 2019 10:54:26
2019-10-01 11:06:23.010152+0200 WebDriverAgentRunner-Runner[4668:107902] ServerURLHere->http://192.168.1.141:8100<-ServerURLHere
2019-10-01 11:06:23.024436+0200 WebDriverAgentRunner-Runner[4668:107982] Using singleton test manager
^C

*** If you believe this error represents a bug, please attach the result bundle at /Users/francescoaprile/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Test-WebDriverAgentRunner-2019.10.01_11-06-19-+0200.xcresult

2019-10-01 11:13:18.676 xcodebuild[4661:107678] [MT] IDETestOperationsObserverDebug: 418.353 elapsed -- Testing started completed.
2019-10-01 11:13:18.676 xcodebuild[4661:107678] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2019-10-01 11:13:18.676 xcodebuild[4661:107678] [MT] IDETestOperationsObserverDebug: 418.353 sec, +418.353 sec -- end

Test session results, code coverage, and logs:
/Users/francescoaprile/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Test-WebDriverAgentRunner-2019.10.01_11-06-19-+0200.xcresult

** TEST INTERRUPTED **

**Comment by faprile** [comment]
iproxy 8100 8100 7768822F-8671-490A-8EE9-F648F0E11604
waiting for connection
accepted connection, fd = 4
waiting for connection
accepted connection, fd = 5
waiting for connection
Number of available devices == 0
No connected device found, terminating.
Number of available devices == 0
No connected device found, terminating.
accepted connection, fd = 4
waiting for connection
Number of available devices == 0
No connected device found, terminating.
accepted connection, fd = 4
waiting for connection
Number of available devices == 0
No connected device found, terminating.
accepted connection, fd = 4
Number of available devices == 0
No connected device found, terminating.
waiting for connection
accepted connection, fd = 4
waiting for connection
Number of available devices == 0
No connected device found, terminating.
accepted connection, fd = 4
waiting for connection
Number of available devices == 0
No connected device found, terminating.
accepted connection, fd = 4
waiting for connection
Number of available devices == 0
No connected device found, terminating.
accepted connection, fd = 4
waiting for connection
Number of available devices == 0
No connected device found, terminating.

**Comment by faprile** [comment]
iproxy 8100 8100 00008020-00140D5A3686002E
waiting for connection
accepted connection, fd = 4
waiting for connection
Number of available devices == 2
Requesting connecion to device handle == 10 (serial: 00008020-00140D5A3686002E), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
accepted connection, fd = 7
Number of available devices == 2
Requesting connecion to device handle == 10 (serial: 00008020-00140D5A3686002E), port 8100
waiting for connection
run_ctos_loop: fd = 7
run_stoc_loop: fd = 7
recv failed: Resource temporarily unavailable
recv failed: Resource temporarily unavailable
recv failed: Operation not permitted
accepted connection, fd = 4
waiting for connection
Number of available devices == 2
Requesting connecion to device handle == 10 (serial: 00008020-00140D5A3686002E), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
accepted connection, fd = 7
waiting for connection
Number of available devices == 2
Requesting connecion to device handle == 10 (serial: 00008020-00140D5A3686002E), port 8100
run_ctos_loop: fd = 7
run_stoc_loop: fd = 7
recv failed: Resource temporarily unavailable
recv failed: Operation not permitted
recv failed: Resource temporarily unavailable
recv failed: Operation not permitted

**Comment by KazuCocoa** [comment]
```
2019-10-01 11:06:23.010152+0200 WebDriverAgentRunner-Runner[4668:107902] ServerURLHere->http://192.168.1.141:8100<-ServerURLHere
2019-10-01 11:06:23.024436+0200 WebDriverAgentRunner-Runner[4668:107982] Using singleton test manager
^C
```

The runner was working and maybe you killed the process with `ctl+C`...
Did you call the WDA via Appium?

**Comment by faprile** [comment]
-.-
I didn't interrupt anything.  The test remains active for over an hour, then stops on its own.

**Comment by KazuCocoa** [comment]
hm..

I'm not sure who sent SIGINT, but `^C` was in your log.
I typed `^C` after starting WDA, then below happened.

```
2019-10-02 13:40:25.424776+0900 WebDriverAgentRunner-Runner[9332:2842195] ServerURLHere->http://192.168.1.115:8100<-ServerURLHere
2019-10-02 13:40:25.425227+0900 WebDriverAgentRunner-Runner[9332:2842228] Using singleton test manager
^C

*** If you believe this error represents a bug, please attach the result bundle at /Users/kazu/Library/Developer/Xcode/DerivedData/WebDriverAgent-ezumztihszjoxgacuhatrhxoklbh/Logs/Test/Test-WebDriverAgentRunner-2019.10.02_13-40-23-+0900.xcresult

2019-10-02 13:40:29.550 xcodebuild[9326:2841967] [MT] IDETestOperationsObserverDebug: 5.329 elapsed -- Testing started completed.
2019-10-02 13:40:29.550 xcodebuild[9326:2841967] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2019-10-02 13:40:29.550 xcodebuild[9326:2841967] [MT] IDETestOperationsObserverDebug: 5.329 sec, +5.329 sec -- end
** TEST INTERRUPTED **
```

Below is another case I sent `kill -2` to send SIGINT.  if the process killed by signals or crashed, the output will be like this..
```
2019-10-02 13:44:24.395741+0900 WebDriverAgentRunner-Runner[9870:2850751] Built at Oct  2 2019 13:38:14
2019-10-02 13:44:24.422691+0900 WebDriverAgentRunner-Runner[9870:2850751] ServerURLHere->http://192.168.1.115:8100<-ServerURLHere
2019-10-02 13:44:24.423816+0900 WebDriverAgentRunner-Runner[9870:2850810] Using singleton test manager


*** If you believe this error represents a bug, please attach the result bundle at /Users/kazu/Library/Developer/Xcode/DerivedData/WebDriverAgent-ezumztihszjoxgacuhatrhxoklbh/Logs/Test/Test-WebDriverAgentRunner-2019.10.02_13-44-22-+0900.xcresult

2019-10-02 13:45:20.732 xcodebuild[9856:2850302] [MT] IDETestOperationsObserverDebug: 57.990 elapsed -- Testing started completed.
2019-10-02 13:45:20.732 xcodebuild[9856:2850302] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2019-10-02 13:45:20.732 xcodebuild[9856:2850302] [MT] IDETestOperationsObserverDebug: 57.990 sec, +57.990 sec -- end
** TEST INTERRUPTED **
```

**Comment by KiratiBhuva** [comment]
I am getting the same error while trying to build the project with a real ios device. 
using 
Appium 1.15.1
Xcode 11.3.1
ios 13.3
Is there any solution discussed yet or any workaround?
