### ISSUE TITLE
iOS 13 - Appium doesn't recognise iOS keyboard for in app purchase password entry 

### ISSUE THREAD

**Issue by tusharwgames** [appium/appium#13338]
## The problem

Getting "Keyboard is not present" exception while trying to send input to a Password field during an in app purchase on iOS 13+ devices. Keyboard is present and visible on the real device.

## Environment

* Appium version (or git revision) that exhibits the issue: **1.15.0**
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: **MacOS 10.14.5**
* Node.js version (unless using Appium.app|exe): **12.8.1**
* Npm or Yarn package manager: **Npm**
* Mobile platform/version under test: **iOS 13.1.2 (13 onwards)**
* Real device or emulator/simulator: **Real device**
* Appium CLI or Appium.app|exe: **CLI**

## Details

When I try to make an in-app sandbox purchase in our app on a device that is on iOS 13+, I face the password field for which the iOS keyboard comes up and is visible on the real device. But when I use send keys to send an input, I get "Keyboard is not present" exception.

The same code and same setup works for iOS devices with iOS 12.4.x.
All other instances where a keyboard comes up in the app for iOS 13+ are also working, only the instance where it is a password field for in app purchase throws up the exception.

I have checked with Appium inspector as well and verified that the keyboard isn't shown in the elements recognised for iOS 13+. But for iOS 12.4.x, the same keyboard is recognised.

## Link to Appium logs

`Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 “Keyboard is not present” UserInfo={NSLocalizedDescription=Keyboard is not present}`

## Code To Reproduce Issue [ Good To Have ]

driver.findElementByName("element").sendKeys("Password");

**Comment by mykola-mokhnach** [comment]
I assume this is the security limitation for xctest. As a workaround you could try to copy and then paste the password string into the input field. The other idea might be to temporary enable `includeNonModalElements` setting and see if that helps to make the keyboard visible

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by tusharwgames** [comment]
I tried enabling `includeNonModalElements` setting as a runtime capability but it doesn't change anything.
I have also tried long pressing on the text box and using the Paste button to paste the password. But the Paste button isn't recognised either since it's in some way part of the keyboard which in itself isn't being recognised.

**Comment by mykola-mokhnach** [comment]
If the dialog is a web view then to switch to its context. Otherwise I don't see any other possibilities to make its automation possible. Consider then describing the problem to Apple
