### ISSUE TITLE
Original error: Could not install app: '{appPath}/Frameworks/libswiftCore.dylib' within the timeout 30000ms'

### ISSUE THREAD

**Issue by XXOK** [appium/appium#13330]
**The Problem**
Appium Server run to iOS Real device, not running
and log return
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not install app: 'Couldn't push '/Users/yeonshin/Library/Developer/Xcode/DerivedData/traveler-bdjcyjbwiyeflagvvnuveopuxftj/Build/Products/Debug-iphoneos/-test.app/Frameworks/libswiftCore.dylib' within the timeout 30000ms'

**Environment**
Appium Version: 1.15.0
Node Version: 12.11.0
iOS real device version : 11.4.1

    desired_caps = {}
    desired_caps['bundleId'] = 'test.com'
    desired_caps['platformName'] = 'ios'
    desired_caps['platformVersion'] = '11.4.1'
    desired_caps['deviceName'] = 'iPhone 8'
    desired_caps['automationName'] = 'XCUITest'
    desired_caps['app'] = '/Users/yeonshin/Library/Developer/Xcode/DerivedData/traveler-bdjcyjbwiyeflagvvnuveopuxftj/Build/Products/Debug-iphoneos/test.app'
    desired_caps['udid'] = 'xxxx'
    desired_caps['xcodeOrgId'] = 'xxxx'
    desired_caps['xcodeSigningId'] = 'iPhone Developer'
    desired_caps['noReset'] = 'True'
    desired_caps['newCommandTimeout'] = '30000'

**Link to Appium logs**
https://gist.github.com/XXOK/b2453f5691380ac0aa8183df493408d6

I'm sorry for my poor English, I will share any information I need

**Comment by mykola-mokhnach** [comment]
Did you try to reboot the device?

**Comment by XXOK** [comment]
@

> Did you try to reboot the device?


Yes, the same thing happens when you reboot.

**Comment by jasminprajapati** [comment]
Any update on this issue?

We have been facing this error for below configuration

Appium Desktop:  1.15.1 (ios)
Xcode: 11.1
iOS Device:  iphone 8 plus (ios: 12.4.1)

Any fix or workaround is much appreciated.

**Comment by mykola-mokhnach** [comment]
@jasminprajapati Try appium@beta

**Comment by saranya-duraisamy-dev** [comment]
Hi Team,
is there an update on the above issue. Please advise.
We are also facing the issue with the below
Selenium server version: 3.141
appium version: 1.15.1
npm version: 6.12.1
node version: v13.1.0
Xcode version: 11.2
iOS 12.4.1

Steps tried

Rebooted the device
Rebooted the appium server
but it didn't help.

**Comment by xv-dmitry-m** [comment]
Hello, maybe some updates? 
Issue appears on appium@beta also, 
appium: 1.16.0-beta.1
xcode: 11.1 
ios: 13.1

Occured once, we rebooted device, the issue happens again

**Comment by shreyanshp** [comment]
Any reason why this issue is occurring? @mykola-mokhnach 
I think after 1.13.0 we moved away from limobiledevice is the related to that?
