### ISSUE TITLE
Appium through command line not available after downgrading

### ISSUE THREAD

**Issue by AymarN** [appium/appium#13345]
## The problem

While downgrading from 1.14.1 to 1.9.1 , I lost Appium through command line:
-sh Appium command could not be found.
 The installation with npm operates well. The packages are added and Appium is in my environment variables. I switched with Appium Desktop 
 
## Environment

* Appium version (1.9.1) that exhibits the issue:
* Last Appium version that did not exhibit the issue (1.14.1):
* Desktop OS/version used to run Appium: macOS Catalina 10.15
* Node.js version ():
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:iPhone 6
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Unfortunately we don't provide any fixes for older Appim versions. You could still ask your question on Appium forum though.
