### ISSUE TITLE
[macOS Catalina 1.15.0 ] Appium through command line not available after downgrading

### ISSUE THREAD

**Issue by AymarN** [appium/appium#13346]
## The problem`

While downgrading from 1.14.1  to 1.9.1 , I lost Appium through command line:
-sh Appium command could not be found. 
The installation with npm operates well. The packages are added and Appium is in my environment variables.I switch for Appium Desktop 1.15.0

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable): 1.14.1
* Desktop OS/version used to run Appium: macOS Catalina 10.15
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: iOS 12.1
* Real device or emulator/simulator: iPhone 6
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
https://gist.github.com/AymarN/160aefd7b6cb8c0104a10f535346536b

**Comment by KazuCocoa** [comment]
Can your env work with another installed command via npm `-g` option?
It looks npm issue rather than appium since `which appium` also had no output

**Comment by AymarN** [comment]
No, it doesn't.
I created a new issue on npm community.
~ $ ng version
-sh: ng: command not found
~ $ ng --version
-sh: ng: command not found
~ $

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
