### ISSUE TITLE
iOS 13, Xcode 11 WebDriverAgentRunner tests failed: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

### ISSUE THREAD

**Issue by hoangtaiki** [appium/appium#13340]
WebDriverAgentRunner: Testing failed. Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

## Environment
* Appium 1.15.1
* Mac OS 10.14.6
* Node.js version v12.10.0
* Npm 6.11.3
* Simulator iPhone 11 13.0

## Link to Appium logs
https://gist.github.com/hoangtaiki/f37c4c82ceda64d4e801b957a0434a4d

**Comment by mykola-mokhnach** [comment]
> [XCUITest] 		WebDriverAgentRunner-Runner.app (70461) encountered an error (Failed to create a bundle instance representing '/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest'. Check that the bundle exists on disk.)

Does appium have write access to that folder? Is there enough space on the storage?

**Comment by hoangtaiki** [comment]
Yes. I use `chmod -R 777` to grant write access for it. And my storage has enough space for it.
I have a question: Why Xcode build `WebDriverAgentRunner-Runner.app` into `/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/` instead of `/Users/harry.tran/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu/`

**Comment by mykola-mokhnach** [comment]
Can you attach the full log with `showXcodeLog` cap enabled?

**Comment by hoangtaiki** [comment]
Below is full Appium log
https://gist.github.com/hoangtaiki/a7df742fbcd2aae3158edf6444f18450

**Comment by mykola-mokhnach** [comment]
Do you get the same error when you try to build the project with Xcode?

**Comment by hoangtaiki** [comment]
Yes, I get same error when run tests with Xcode.

**Comment by mykola-mokhnach** [comment]
This something might be wrong with Xcode on your machine. Try to clean the project and rebuild it. If that still does not work then try to do it on another machine

**Comment by tuyenlq** [comment]
Flows guide
1. Update Appium ~1.15.0-rc.5
2. Uninstall webdriver agent and rebuild with path  /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent
===========================
work on io simulator IOS 13 and real devices

**Comment by hoangtaiki** [comment]
@tuyenlq @mykola-mokhnach I found problem. Something rename `build` folder to `Build`. I renamed it and it worked well. Thank for your help.

**Comment by aravindanath** [comment]
> @tuyenlq @mykola-mokhnach I found problem. Something rename `build` folder to `Build`. I renamed it and it worked well. Thank for your help.

Hi @hoangtaiki 
I am also facing "webdriverAgentRunner test failed. " Can u pls let me know which "build" u modified to "Build". Pls share more details to fix this issue.

**Comment by suaadBatis** [comment]
i have the same issue

**Comment by ParadeTo** [comment]
> @tuyenlq @mykola-mokhnach I found problem. Something rename `build` folder to `Build`. I renamed it and it worked well. Thank for your help.

The same issue
