### ISSUE TITLE
APPIUM IOS (1.5.0) with XCODE 11 - cant find element on screen

### ISSUE THREAD

**Issue by Berger1804** [appium/appium#13341]
APPIUM IOS (1.5.0) 
XCODE 11 

Hi, When try to click on a button that on screen :

driver.findElement(By.id("Status")).click();

there is an error message :

WD Proxy] Got an unexpected response with status 404: {"value":{"error":"no such element","message":"unable to find an element using 'id', value 'Status'","traceback":"(\n\t0   WebDriverAgentLib                   0x00000001071d4508 FBNoSuchElementErrorResponseForRequest + 312\n\t1   WebDriverAgentLib                   0x00000001071d42d0 +[FBFindElementCommands handleFindElement:] + 448\n\t2   WebDriverAgentLib                   0x00000001071b38e0 -[FBRoute_TargetAction mountRequest:intoResponse:] + 220\n\t3   WebDriverAgentLib                   0x00000001071a1184 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 504\n\t4   RoutingHTTPServer                   0x000000010731e2cc -[RoutingHTTPServer handleRoute:withRequest:response:] + 144\n\t5   RoutingHTTPServer                   0x000000010731ea88 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 44\n\t6   libdispatch.dylib                   0x000000019d7dd00c 6BA026F4-EFBB-3B4B-84DD-E35A085BB663 + 12300\n\t7   libdispatch.dylib                   0x000000019d7e...
[debug] [W3C] Matched W3C error code 'no such element' to NoSuchElementError
[debug] [MJSONWP (d0c94444)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[debug] [MJSONWP (d0c94444)]     at XCUITestDriver.doNativeFind (/Users/gilberger/.npm-global/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:126:11)
[HTTP] <-- POST /wd/hub/session/d0c94444-3e6b-4b01-8db2-1401fd4dcc72/element 500 203 ms - 164

But . . If i do like this :

 List<MobileElement> TypeButton = driver.findElements (MobileBy.className ("XCUIElementTypeButton"));

TypeButton.get(5).click();

its working well .. 

whats is the problem ?? why he cannot found the ID element ?? its exist on the screen

Thanks !!

**Comment by mykola-mokhnach** [comment]
Can you take the page source output before the lookup is executed and attach it to the issue? Does the  target identifier exist there?

**Comment by Berger1804** [comment]
> Can you take the page source output before the lookup is executed and attach it to the issue? Does the target identifier exist there?

Yes, im using appium inspector and i can see the element with the ID

**Comment by mykola-mokhnach** [comment]
Can you please do what I've asked? The hierarchies during the test execution and in the inspector might be different due to race conditions

**Comment by Berger1804** [comment]
> Can you please do what I've asked? The hierarchies during the test execution and in the inspector might be different due to race conditions

Can you please explain how do i  take the page source output before the lookup is executed ? Thanks !

**Comment by mykola-mokhnach** [comment]
This topic does not need to be explained - one can easily google it. Also there is Appium forum for asking questions.

**Comment by hadrianjmnz90** [comment]
> > Can you please do what I've asked? The hierarchies during the test execution and in the inspector might be different due to race conditions
> 
> Can you please explain how do i take the page source output before the lookup is executed ? Thanks !

system.out.println( driver.getPageSource);

**Comment by Berger1804** [comment]
> system.out.println( driver.getPageSource);

Thanks !!!

this is the page source :

INFO: <?xml version="1.0" encoding="UTF-8"?><AppiumAUT><XCUIElementTypeApplication type="XCUIElementTypeApplication" name="[WhatsApp]" label="[WhatsApp]" enabled="true" visible="true" x="0" y="0" width="320" height="568">
  <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" visible="true" x="0" y="0" width="320" height="568">
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="320" height="568">
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="320" height="568">
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="320" height="568">
          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="320" height="568">
            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="320" height="568">
              <XCUIElementTypeNavigationBar type="XCUIElementTypeNavigationBar" name="‎Chats" enabled="true" visible="true" x="0" y="20" width="320" height="91">
                <XCUIElementTypeOther type="XCUIElementTypeOther" name="‎Chats" label="‎Chats" enabled="true" visible="true" x="16" y="66" width="84" height="37"/>
                <XCUIElementTypeButton type="XCUIElementTypeButton" name="‎New Chat" label="‎New Chat" enabled="true" visible="true" x="269" y="20" width="43" height="44"/>
              </XCUIElementTypeNavigationBar>
              <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="320" height="568">
                <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="320" height="568">
                  <XCUIElementTypeTable type="XCUIElementTypeTable" name="‎All of your chats are archived. Tap the    icon to start a new chat." label="‎All of your chats are archived. Tap the    icon to start a new chat." enabled="true" visible="false" x="0" y="0" width="320" height="568">
                    <XCUIElementTypeCell type="XCUIElementTypeCell" enabled="true" visible="false" x="0" y="111" width="0" height="44">
                      <XCUIElementTypeButton type="XCUIElementTypeButton" name="More Info" label="More Info" enabled="false" visible="false" x="-23" y="126" width="8" height="13"/>
                      <XCUIElementTypeImage type="XCUIElementTypeImage" enabled="true" visible="false" x="-18" y="115" width="2" height="36"/>
                      <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="‎Archived Chats" name="‎Archived Chats" label="‎Archived Chats" enabled="true" visible="false" x="-8" y="122" width="0" height="21"/>
                      <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" enabled="true" visible="false" x="0" y="133" width="0" height="0"/>
                      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="154" width="0" height="1"/>
                    </XCUIElementTypeCell>
                  </XCUIElementTypeTable>
                </XCUIElementTypeOther>
              </XCUIElementTypeOther>
            </XCUIElementTypeOther>
          </XCUIElementTypeOther>
        </XCUIElementTypeOther>
        <XCUIElementTypeTabBar type="XCUIElementTypeTabBar" enabled="true" visible="true" x="0" y="519" width="320" height="49">
          <XCUIElementTypeButton type="XCUIElementTypeButton" name="‎Status" label="‎Status" enabled="true" visible="true" x="2" y="520" width="60" height="48"/>
          <XCUIElementTypeButton type="XCUIElementTypeButton" name="‎Calls" label="‎Calls" enabled="true" visible="true" x="66" y="520" width="60" height="48"/>
          <XCUIElementTypeButton type="XCUIElementTypeButton" name="‎Camera" label="‎Camera" enabled="true" visible="true" x="130" y="520" width="60" height="48"/>
          <XCUIElementTypeButton type="XCUIElementTypeButton" value="1" name="‎Chats" label="‎Chats" enabled="true" visible="true" x="194" y="520" width="60" height="48"/>
          <XCUIElementTypeButton type="XCUIElementTypeButton" name="‎Settings" label="‎Settings" enabled="true" visible="true" x="258" y="520" width="60" height="48"/>
        </XCUIElementTypeTabBar>
      </XCUIElementTypeOther>
    </XCUIElementTypeOther>
  </XCUIElementTypeWindow>
  <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" visible="true" x="0" y="0" width="320" height="568">
    <XCUIElementTypeStatusBar type="XCUIElementTypeStatusBar" enabled="true" visible="true" x="0" y="0" width="320" height="20">
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="320" height="20"/>
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="320" height="20">
        <XCUIElementTypeOther type="XCUIElementTypeOther" name="4 of 4 bars, signal strength" label="4 of 4 bars, signal strength" enabled="true" visible="true" x="6" y="0" width="17" height="20"/>
        <XCUIElementTypeOther type="XCUIElementTypeOther" name="HOT mobile network" label="HOT mobile network" enabled="true" visible="true" x="26" y="0" width="67" height="20"/>
        <XCUIElementTypeOther type="XCUIElementTypeOther" name="3 of 3 Wi-Fi bars" label="3 of 3 Wi-Fi bars" enabled="true" visible="true" x="98" y="0" width="15" height="20"/>
        <XCUIElementTypeOther type="XCUIElementTypeOther" name="8:12" label="8:12" enabled="true" visible="true" x="149" y="0" width="26" height="20"/>
        <XCUIElementTypeOther type="XCUIElementTypeOther" name="Orientation Locked" label="Orientation Locked" enabled="true" visible="true" x="262" y="0" width="12" height="20"/>
        <XCUIElementTypeOther type="XCUIElementTypeOther" name="94% battery power, Charging" label="94% battery power, Charging" enabled="true" visible="true" x="280" y="0" width="35" height="20"/>
      </XCUIElementTypeOther>
    </XCUIElementTypeStatusBar>
  </XCUIElementTypeWindow>
</XCUIElementTypeApplication></AppiumAUT>


I need to prees on the button "New Chat". its in the source page but still o get an error message :

WD Proxy] Got an unexpected response with status 404: {"value":{"error":"no such element","message":"unable to find an element using 'name', value 'New Chat'","traceback":"(\n\t0   WebDriverAgentLib                   0x0000000100f442b0 FBNoSuchElementErrorResponseForRequest + 312\n\t1   WebDriverAgentLib                   0x0000000100f44078 +[FBFindElementCommands handleFindElement:] + 460\n\t2   WebDriverAgentLib                   0x0000000100f23240 -[FBRoute_TargetAction mountRequest:intoResponse:] + 220\n\t3   WebDriverAgentLib                   0x0000000100f10828 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 504\n\t4   RoutingHTTPServer                   0x00000001042e22cc -[RoutingHTTPServer handleRoute:withRequest:response:] + 144\n\t5   RoutingHTTPServer                   0x00000001042e2a88 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 44\n\t6   libdispatch.dylib                   0x00000001c2afa484 <redacted> + 16\n\t7   libdispatch.dylib                   0x00000001c2aa76a0 <redacted> + 92\n\t8...
[debug] [W3C] Matched W3C error code 'no such element' to NoSuchElementError
[debug] [MJSONWP (6303f2da)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[debug] [MJSONWP (6303f2da)]     at XCUITestDriver.doNativeFind (/Users/gilberger/.npm-global/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:126:11)
[HTTP] <-- POST /wd/hub/session/6303f2da-e916-4dd2-b204-08f22baa40bd/element 500 134 ms - 164
[HTTP]

**Comment by mykola-mokhnach** [comment]
I see the button with the given name is present in the page source. What if you explicitly wait for it before clicking? And/Or extend the accessibility id locator to predicate or xpath one? Does it help?

**Comment by Berger1804** [comment]
> I see the button with the given name is present in the page source. What if you explicitly wait for it before clicking? And/Or extend the accessibility id locator to predicate or xpath one? Does it help?

Only now I notice that the only thing that helps is using lable (in xpath) not  accessibility id, not name .. only lable ..

**Comment by mykola-mokhnach** [comment]
xpath is slow. I'd rather use predicates

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by vzenzo** [comment]
> xpath is slow. I'd rather use predicates

this does not solve the issue at all

**Comment by Ranadheer88** [comment]
Please share if you have any solution for this?
