### ISSUE TITLE
System prompt is not shown translated when locale is changed by Appium driver

### ISSUE THREAD

**Issue by jungmoku** [appium/appium#13348]
## The problem

For testing translation of our app and using appium driver to change the locale for ios, system prompt is not shown translated on both simulators and physical devices. (When I try changing locale on setting manually on physical devices, I see the translations fine - but not on Simulator)

## Environment

* Appium version: 1.15.0-rc.5
* Desktop OS/version used to run Appium: MacOS Mojave Version 10.14.6
* Node.js version (unless using Appium.app|exe): 6.9.0
* Npm or Yarn package manager: Npm
* Mobile platform/version under test: iOS 13, iOS 12.4
* Real device or emulator/simulator:  Both (device + simulator)

## Link to Appium logs

[debug] [WD Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.weather.TWC","arguments":["-AppleLanguages","(de)","-NSLanguages","(de)","-AppleLocale","de_DE"],"environment":{},"eventloopIdleDelaySec":15,"shouldWaitForQuiescence":false,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":5,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}

## Code To Reproduce Issue [ Good To Have ]

System.setProperty("capability.locale", locale.toString());
System.setProperty("capability.language", locale.getLanguage());
this.initDriver(); // it has DriverManager.start(extraCapabilities);

**Comment by mykola-mokhnach** [comment]
This setting only defined the language of the app. The language of system dialogs are defined by the system locale though

**Comment by jamesvanhorn** [comment]
right, and running it in the simulator does change the sim's system locale. It does correctly translate the prompt for location permission. But it doesn't translate the prompt for push notification permission. I assume this is beyond the scope of anything Appium/WDA can do, but figured it was worth asking. We're trying to gather screenshots of startup flow of our app across a bunch of different languages, and the push notification dialog not being translated is blocking us.

**Comment by mykola-mokhnach** [comment]
iOS driver has `locale` capability, which might be in use for Simulator. Although, it is not used very often, so there is a possibility it might be broken for newer simulator versions.

**Comment by jamesvanhorn** [comment]
yeah we use `language` and `locale` capabilities and they both work well (for Sim and real device surprisingly) for the actual app strings. Just not the system level dialogs. The only other option I can come up with is writing more code to launch the Settings app and change locale there manually. That will take forever though.

**Comment by mykola-mokhnach** [comment]
I mean [this](https://github.com/appium/appium-ios-simulator/blob/c64804196bdd96315b674cc215081bcfa1cb3f12/lib/simulator-xcode-6.js#L740) method. In theory it should modify simulator settings DB and adjust the system locale. Although, such method is hacky and might be easily broken in any new sim versions.
I'll keep this issue as a feature request if someone has time to verify the compatibility of this method with Xcode 11 SDK Simulator.

**Comment by jamesvanhorn** [comment]
I see. Any idea how I can call that directly through Appium's java bindings? Or how I can call it directly otherwise?

**Comment by mykola-mokhnach** [comment]
It is called if locale is set: https://github.com/appium/appium-xcuitest-driver/blob/e2fcb984d3e860f26989cc3c4250615555da7126/lib/driver.js#L366

**Comment by jamesvanhorn** [comment]
ok that makes sense. So it seems like a simulator bug?

**Comment by mwakizaka** [comment]
> ok that makes sense. So it seems like a simulator bug?

hi, I guess yes. just fyi, I've confirmed that push notification prompt gets translated into device language (in this case Japanese) since iOS 16.0 simulator.
<img width="416" alt="Screenshot 2023-04-04 at 10 21 08" src="https://user-images.githubusercontent.com/21286384/229661829-b394312d-6feb-4d5e-80b2-d5d23172bc6f.png">

as for iOS15.5, it does not get translated
<img width="408" alt="Screenshot 2023-04-04 at 10 21 16" src="https://user-images.githubusercontent.com/21286384/229661889-30c0909f-d0c4-4d16-9bcd-ca0b77d990b5.png">

ref: https://openradar.appspot.com/radar?id=5536358726631424
