### ISSUE TITLE
W3C / JSONWP Session

### ISSUE THREAD

**Issue by mstrelex** [appium/appium#13355]
Just a quick question, if a session was initiated as JSONWP session, means that W3C only stuff (like the new Action) will not work? Thanks.

**Comment by mykola-mokhnach** [comment]
According to W3C spec - yes, but this has been relaxed in Appium mobile drivers, so one could execute actions for UIA2/Espresso or Xcuitest driver even being in JSONWP mode

**Comment by mstrelex** [comment]
Tank you so much for the quick answer!
