### ISSUE TITLE
WebDriverAgent failed to build: Assign property / Could not build RoutingHTTPServer Using Appium 1.16.0-beta.1

### ISSUE THREAD

**Issue by tbDebmalya** [appium/appium#13352]
Hi all,
I'm trying to configure WebDriverAgent.xcodeproj for Appium 1.16.0-beta.1 present under appium-webdriveragent foldere, but I can't build a WebDriverAgent because I have these two error:

Semantic issue: 'assign' property of object type may become a dangling reference; consider using 'unsafe_unretained'

Parse Issue: Could not build module 'RoutingHTTPServer'

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.16.0-beta.1
* Last Appium version that did not exhibit the issue (if applicable): Appium 1.15.0
* Desktop OS/version used to run Appium: macOS
* Node.js version (unless using Appium.app|exe): v12.10.0
* Npm or Yarn package manager: npm version 6.11.3
* Mobile platform/version under test: iOS 13.0
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium installed using node.js

## Steps Executed:-

- Downloaded Appium 1.16.0-beta.1

- Navigated to the following directory /usr/local/lib/node_modules/appium/node_modules//usr/local/lib/node_modules/appium/node_modules/

- Since Carthage is already installed using Command : brew install carthage, Executed following command : ./Scripts/bootstrap.sh -d

- Created a new directory as Resources with WebDriverAgent.bundle

- Then opened the WebDriverAgent.xcodeproj in XCode 11 and tried to build it after providing the Signing Credentials for my project.

**Comment by KazuCocoa** [comment]
I've published WDA as 2.0.1 which has the warning fix.
Please update appium-webdriveragent (or re-install the beta)

`Could not build module 'RoutingHTTPServer'` also happened on my local with Xcode 11, but that fixed after reboot the host machine in my case...
Perhaps Xcode 11 has some issues to handle modules...?

**Comment by mykola-mokhnach** [comment]
Apple has added additional warnings to Xcode11, which causes the issue above. Appium adds `GCC_TREAT_WARNINGS_AS_ERRORS=0` arg to xcodebuild, which prevents such issues. You could also do this to compile the project separately or use the recently tagged WDA, which contains a fix for the mentioned warning message
