### ISSUE TITLE
Appium 1.15 version does not have WDA folder under appium-xcuitest-driver folder

### ISSUE THREAD

**Issue by techshashank80** [appium/appium#13357]
## The problem

I uninstalled the appium from my machine and installed the new version 1.15.0.
I didn't find the WDA folder appium-xcuitest-driver folder. Our code did not find the WDA Xcode project.
ThenI installed the previous version 1.14.2 then WDA folder was created under  appium-xcuitest-driver
If I again try to install the latest version 1.15.0 . Its removing the WDA folder.

## Environment

* Appium version (or git revision) that exhibits the issue:1.15.0
* Last Appium version that did not exhibit the issue (if applicable):1.14.2
* Desktop OS/version used to run Appium:10.13.6 (macOS High Sierra)
* Node.js version (unless using Appium.app|exe): 12.10.0
* Npm or Yarn package manager:6.11.3
* Mobile platform/version under test:
* Real device or emulator/simulator:iPhone 6S plus
* Appium CLI or Appium.app|exe:

**Comment by KazuCocoa** [comment]
It was moved to appium-webdriveragent as a separate npm package.
e.g.: https://github.com/appium/appium/blob/b4759c214177b06d9032f627cb8b7f931867605f/docs/en/advanced-concepts/wda-custom-server.md#wda-setup

**Comment by surajsalunkhe** [comment]
you can find path in the below location.
when you download Appium desktop version
/Applications/Appium.app/Contents/Resources/app/node_modules/appium-webdriveragent
