### ISSUE TITLE
Appium 1.15 iOS 13 - failure on installation "Path must be a string. Received undefined"

### ISSUE THREAD

**Issue by lubshilk** [appium/appium#13351]
## The problem
After Appium server upgraded to 1.15.0 and device to iOS 13.1.2 reported "Path must be a string. Received undefined" when trying to install IPA

Path to the IPA file looks fine. All other capabilities didn't change
Please, help

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.0
* Desktop OS/version used to run Appium: MAC Mojave 10.14.6
* Mobile platform/version under test: iOS 13.1.2
* Real device

## Link to Appium logs
https://gist.github.com/lubshilk/3dbdf25395ddabfc47eb504d4b6d911b

**Comment by mykola-mokhnach** [comment]
Closed as duplicate. Kindly use search

**Comment by lubshilk** [comment]
Oh, sorry, after node upgrade this problem not reported
