### ISSUE TITLE
The element is found but when I tap on the element, it highlights somewhere else. Please advise

### ISSUE THREAD

**Issue by Devapal** [appium/appium#13350]
## The problem

I have upgraded from Appium 1.11 to 1.15, On some pages the objects are displayed on the page but when search and selected it clicks somewhere else.  Below are two screenshots here. Basically I search "NEXT arrow_forward" button, the element is found but when I tap on the element, it highlights somewhere else (_highlighted in blue in the screenshot_). 

This is one of the many issues I am facing after upgrading the Appium Version. Previously It used to work correctly.
The weird thing is, I downgraded the Appium and still facing the same issue. Please see attached screenshot of the object and where it actually clicks when tapped on the element.

**Things I have tried:**
I tried to get page resource, 
I tried sending the application to background and bringing it back
I tried using xPath and UIAutomator to identify
I tried Tap instead of Click
I tried swiping, etc

Nothing seems to click the element at its correct coordinates. 

<img width="1421" alt="Screen Shot 2019-10-02 at 8 33 47 PM" src="https://user-images.githubusercontent.com/35826618/66093081-5d7d0a00-e554-11e9-9899-70a747907272.png">
<img width="1439" alt="Screen Shot 2019-10-02 at 8 33 57 PM" src="https://user-images.githubusercontent.com/35826618/66093082-5e15a080-e554-11e9-92f9-a270dd76dca0.png">

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15, 1.13, 1.12.1
* Last Appium version that did not exhibit the issue (if applicable): 1.11
* Desktop OS/version used to run Appium: Mac 10.4.16 and Windows 10 ( tried on both )
* Mobile platform/version under test: ANDROID
* Real device or emulator/simulator: REAL DEVICE
* Appium CLI or Appium.app|exe: 1.15

## Details
Attached Logs:
[appium-server-logs copy.txt](https://github.com/appium/appium/files/3686740/appium-server-logs.copy.txt)

## Code To Reproduce Issue [ Good To Have ]
I tried with Xpath and UIAutomator, both execute the same issue of clicking somewhere else.

//android.widget.Button[@text='NEXT arrow_forward'] - using xPath
new UiSelector().text(\"NEXT arrow_forward\") - using UiAutomatorSelector

**Comment by mykola-mokhnach** [comment]
Please attach the full server log.

**Comment by Devapal** [comment]
Hi, Please see attached logs. 
[appium-server-logs copy.txt](https://github.com/appium/appium/files/3686737/appium-server-logs.copy.txt)

**Comment by mykola-mokhnach** [comment]
Try to perform click by coordinates as a workaround. I assume it is the problem of UIA2 framework or the app itself, since it clicks at the coordinates, which are provided by the application under test to the accessibility layer

**Comment by Devapal** [comment]
@mykola-mokhnach  Thanks for the suggestion. Meanwhile I have conducted some more research into this issue.

I have tested with different apps (ionic, Cordova ), It was all working fine until last week. I am so lost trying to figure out what's happening. So here are a couple of things that seems to work with some objects on some pages.

1. On some pages,  If I logout and log back twice, some objects seems to render fine  and I am able to click on the exact object. 
2. On some pages, If I click on another element before clicking the actual element, the inspector seems to refresh and I am able to click on the right element. 

I have tried downgrading the Appium  but none seems to work. So do we just wait for UIA2 framework to release a fix for this issue ?

**Comment by mykola-mokhnach** [comment]
> So do we just wait for UIA2 framework to release a fix for this issue

There will be no fix. As I said either Google can fix it or ionic, but not us.

If the app is a web view then try to work with it inside web context, not native.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
