### ISSUE TITLE
Switch to Window documentation is outdated

### ISSUE THREAD

**Issue by b1zzu** [appium/appium#13362]
The `/session/:session_id/window` should recive the `handle` arguments and not the `name` as documented in w3c: https://www.w3.org/TR/webdriver/#dfn-switch-to-window

https://github.com/appium/appium/blob/a74c299fbaef67984046b26595e7745fe1fc4261/commands-yml/commands/web/window/set-window.yml#L72

Refer to this issue: #13359

**Comment by rkpatel7** [comment]
I can go ahead and update this documentation.
