### ISSUE TITLE
Feature Request - Xcode Log Predicate Capability

### ISSUE THREAD

**Issue by sauce-tartar** [appium/appium#13366]
## The problem

Problem: Large volume of iOS Simulator log output using ~`showXcodeLog`~ `showIOSLog`

Suggestion: What do you think about an additional Capability that plumbs in a string for a log filter predicate?  The current [appium-xcuitest-driver log stream](https://github.com/appium/appium-xcuitest-driver/blob/7781a6d73a0a0e58cb74e1ed7430c38a29036688/lib/device-log/ios-simulator-log.js#L28) does not use the `--predicate` argument.

Example of noise and log volume removed when using  ~`showXcodeLog`~ `showIOSLog` cap:

```
xcrun simctl spawn booted log stream --style=compact --predicate 'process != "locationd" AND process != "DTServiceHub"'
```

## Environment

* Appium 1.15.0+   
* iOS 13.0+

**Comment by mykola-mokhnach** [comment]
This would probably work for Simulator, but what to do with real devices?

**Comment by vrunoa** [comment]
@mykola-mokhnach that's a good question. This is something we could start by adding for simulators only. 
@umutuzgur do you know if this would work for real devices? We can test this on our side too.

**Comment by mykola-mokhnach** [comment]
Also, which log we would like to filter? the xcodebuild one or the simulator system log? The proposed change would only affect simulator log, which is triggered by `showIOSLog` cap. Although, the `showXcodeLog` cap retrieves the output of xcodebuild process.

**Comment by umutuzgur** [comment]
We can also do this with real devices but it would require a bit of log parsing

**Comment by sauce-tartar** [comment]
You're right, it's the simulator system log stream not the Xcode timings and such.

`showIOSLog` is correct

**Comment by mykola-mokhnach** [comment]
I would rather stick to a common approach for both simulator and real device logging, whenever log filtering system we'd prefer to use

**Comment by dpgraham** [comment]
Added predicate cap: https://github.com/appium/appium-xcuitest-driver/pull/1091
