### ISSUE TITLE
Running iOS WebDriverAgent without xcode

### ISSUE THREAD

**Issue by brummetj** [appium/appium#13365]
## The problem

So it appears i can't ask questions on  http://discuss.appium.io ... But i would like someone to maybe help guide my automation experience. 

Currently, we run automation on Android, iOS, and Browser devices using the appium framework. But we need to connect android and ios devices to hdmi output, which in return requires us to connect the iOS devices through WiFi and Xcode. This is proven to be hard to maintain with network connections, xcode, and having to enable passcodes for the iOS devices. We are currently trying to use Appium for daily automation 12/7 days a week. 

I'm wondering. Is there a way that to build the WebDriverAgent as a running server on the iPhone ( not through xcode / command line ). Allowing automation to be triggered by talking directly to the phone IP/Port. This would eliminate us having to connect to a macos with xcode and wifi, and talk to the appium server on the macos to proxy commands to the device. 

I'm not a iOS developer, so if any iOS developers wanted to chime in here that would be very helpful also. 

Also if there are any tips and tricks for running long lived Appium servers and maintaining them, the devices, and macos for reliable successful automation that would be great.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13.0
* Desktop OS/version used to run Appium: MacOS Mojave 10.14.5
* Node.js version (unless using Appium.app|exe): 6.9.0
* Npm or Yarn package manager: 
* Mobile platform/version under test: iOS - 13.0
* Real device or emulator/simulator: Real Devices ! 
* Appium CLI or Appium.app|exe: Appium CLI

**Comment by mykola-mokhnach** [comment]
Kindly use Appium forum to ask questions
