### ISSUE TITLE
Missing elements in page source for Android UIAutomator2 Appium

### ISSUE THREAD

**Issue by KS261187** [appium/appium#13372]
## The problem

When I open my Android app using Appium 1.15, I see that some of the elements are not getting loaded in the Appium inspector. Also when I looked at the page source, I noticed that the elements are not found. The elements are clearly visible in the UI but not in Appium page source. As you can see in the screenshot Sort By Relevance, Popularity and Catalog number controls are missing in page source. Can some one please advice?

## Environment

* Appium version (or git revision) that exhibits the issue:1.15
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:Mac OS 10.14.6
* Node.js version (unless using Appium.app|exe):10.16.3
* Npm or Yarn package manager:6.9.0
* Mobile platform/version under test:Android 10
* Real device or emulator/simulator:Real Device
* Appium CLI or Appium.app|exe:exe

## Details

If necessary, describe the problem you have been experiencing in more detail.
<img width="1075" alt="Screen Shot 2019-10-06 at 3 55 02 PM" src="https://user-images.githubusercontent.com/26659582/66275901-05dfe680-e853-11e9-9da4-413111cc4e67.png">

When I login to my app, I can search for a product and then filter the facets accordingly. The problem is I am unable to select any of the facets which has radio buttons and checkboxes. But these elements are visible in the UI. I tried getting the page source, but the page source did not return these elements. Not sure what is wrong here. 

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
If the page is a web view than switch to web context.
In case this is a native context then talk to app developers to make the elements [accessible](https://developer.android.com/guide/topics/ui/accessibility/apps) 

Unfortunately, there is nothing we can do about it on Appium side.

**Comment by KS261187** [comment]
This is a hybrid app and so the Id's that are set will be common for both IOS and Android and this one works perfectly fine in IOS and the issue is happening only in Android UIAutomator 2. Please provide me a link to raise the same issue with the UIAutomator 2.

**Comment by mykola-mokhnach** [comment]
https://developers.google.com/issue-tracker
