### ISSUE TITLE
Appium is causing external Instruments command from capturing intended iOS application performance

### ISSUE THREAD

**Issue by irfan-cloudnix** [appium/appium#13376]
## The problem

I'm trying to capture iOS performance using external instruments command bundled with Xcode. So when I run below command alone,

`instruments -t "Activity Monitor" -D performance.trace -w {udid} -v`

Instruments captures all the applications/processes running on the device including the one I'm looking for.

But when I'm running in parallel with Appium and test command, Instruments still captures all the processes except for the one being automated. Below are the commands,

**Appium**
`appium --log-level debug -a 127.0.0.1 -p 10001 --webdriveragent-port 12001 --session-override --default-capabilities '{"platformName": "iOS", "xcodeOrgId":"xxxxxx", "xcodeSigningId":"iPhone Developer", "noReset":"true"}' --log appium.log --relaxed-security`
// --relaxed-security I had added recently for verification, but didn't worked out

**Maven**
`mvn -X -e -f 'project_dir/pom.xml' -Dtest={fully qualified test path} test`

**Instruments** (Same as above)
`instruments -t "Activity Monitor" -D performance.trace -w {udid} -v`

When all three commands are simultaneously executed, Instruments will capture performance for all the applications except for the one being automated.

## Trials 
* Tried waiting for app installation to complete before starting instruments
* Waited for app to launch on device and later started the instruments, still no results.
* Independently started instruments while using the application, was able to notice the required application in the trace file.

## Environment

* Appium version (or git revision) that exhibits the issue: **1.7.2 (Can't upgrade but can try if no other option left)**
* Desktop OS/version used to run Appium: **Mac OSX 10.13.6**
* Node.js version (unless using Appium.app|exe): **v8.11.4**
* Npm or Yarn package manager: **6.4.1**
* Mobile platform/version under test: **iPhone 6 (iOS 11.2.2)**
* Real device or emulator/simulator: **Real Device**
* Appium CLI or Appium.app|exe: **CLI**

**Comment by mykola-mokhnach** [comment]
I have no idea how this might be related to Appium.
Btw, Appium implements the endpoint for perf measurement: https://appiumpro.com/editions/12

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
