### ISSUE TITLE
Appium version 1.15.0_1 not finding application

### ISSUE THREAD

**Issue by kootjart** [appium/appium#13377]
## The problem

I just installed version 1.15.0-1 of appium. After that, I was not able to run my Robot Framework tests because of following error:

`WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: The application at 'fi.dummy.something' does not exist or is not accessible`

I installed back version 1.13.0 (which I know, was working) and now I can again run my tests. "Open app" keyword, didn't seem to work. 

## Environment

* Appium version: 1.15.0-1
* Last Appium version that did not exhibit the issue (if applicable): 1.13.0
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: Android 7 and Android 9 (emulator)
* Real device or emulator/simulator: Huawei P9 Lite Mini
* Appium CLI or Appium.app|exe:

**Comment by mykola-mokhnach** [comment]
Please provide the full server log and proper steps to reproduce the problem

**Comment by kootjart** [comment]
I have been using Appiumin for Robot Framework tests automation for couple of months now, but I have not really needed appium logs. Where are those logs and what logs you would like to see. 

I can not provide you all information what I have, because application that I'm testing is company confidential.

Error is happening, when I'm trying to open application in Robot code:

`Open Application  ${REMOTE_URL}  platformName=${PLATFORM_NAME}  platformVersion=${PLATFORM_VERSION}  deviceName=${DEVICE_NAME}   app=${${ENV}_APP}  automationName=appium  appPackage=${${ENV}_APP_PACKAGE}  appActivity=com.suomifi.viestit.ui.splash.SplashActivity     noReset=True`

As I said earlied, everything started working again, when I uninstalled 1.15.0-1 version and re-installed version 1.13.0 of Appium.

**Comment by mykola-mokhnach** [comment]
Unfortunately we cannot help nothing without the logs

**Comment by idxn** [comment]
> I have been using Appiumin for Robot Framework tests automation for couple of months now, but I have not really needed appium logs. Where are those logs and what logs you would like to see.
> 
> I can not provide you all information what I have, because application that I'm testing is company confidential.
> 
It's actually what is being print in the console that you start the appium.

**Comment by kootjart** [comment]
Hmm. Is this related to _UiAutomator2 Driver_

**Comment by mykola-mokhnach** [comment]
It seems like provided capabilities are incorrect. `app` is expected to be the path/url to an existing app package, not a package id.

**Comment by kootjart** [comment]
Sorry but not quite understood. Could you point me out, what is wrong here. 

As I said earlier, with version 1.13.0 of Appium, everything was working fine (and still is). With this latest version 1.15.0-1 it won't. So I have to change something in my configuration.

**Comment by KazuCocoa** [comment]
> "appium:app":"fi.dummy.some.sa","appium:automationName":"appium","appium:appPackage":"/data/app/fi.dummy.some.sa-M207upJ07VKFxnvX_DPGDQ==/base.apk=fi.dummy.some.sa","appium:appActivity":"com.dummyfi.some.ui.splash.SplashActivity","appium:noReset":"True"}]}

Perhaps, accidentally worked in the previous version.
You provided `appPackage` as `/data/app/fi.dummy.some.sa-M207upJ07VKFxnvX_DPGDQ==/base.apk=fi.dummy.some.sa` (a path to the test app??) and `app` as `fi.dummy.some.sa` (maybe package name?). But we expected the opposit case. Maybe, some code improvements made the capability check correct, then this issue case happened.
So, it probably works after changing `app` and `appPackage`

https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md

**Comment by kootjart** [comment]
I now changed **app** and **appPackage** opposite way, but I think I'm still getting same error:

`
[Appium] Welcome to Appium v1.15.0
[Appium] Non-default server args:
[Appium]   address: 127.0.0.1
[Appium]   allowInsecure: {
[Appium]   }
[Appium]   denyInsecure: {
[Appium]   }
[Appium] Appium REST http interface listener started on 127.0.0.1:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"capabilities":{"firstMatch":[{"platformName":"Android","appium:platformVersion":"7","appium:deviceName":"AEUBB17A17505591","appium:appPackage":"/data/app/fi.dummy.some.qa-M207upJ07VKFxnvX_DPGDQ==/base.apk=fi.dummy.some.qa","appium:automationName":"appium","appium:app":"fi.dummy.some.qa","appium:appActivity":"com.dummyfi.some.ui.splash.SplashActivity","appium:noReset":"True"}]},"desiredCapabilities":{"platformName":"Android","platformVersion":"7","deviceName":"AEUBB17A17505591","appPackage":"/data/app/fi.dummy.some.qa-M207upJ07VKFxnvX_DPGDQ==/base.apk=fi.dummy.some.qa","automationName":"appium","app":"fi.dummy.some.qa","appActivity":"com.dummyfi.some.ui.splash.SplashActivity","noReset":"True"}}
[W3C] Calling AppiumDriver.createSession() with args: [{"platformName":"Android","platformVersion":"7","deviceName":"AEUBB17A17505591","appPackage":"/data/app/fi.dummy.some.qa-M207upJ07VKFxnvX_DPGDQ==/base.apk=fi.dummy.some.qa","automationName":"appium","app":"fi.dummy.some.qa","appActivity":"com.dummyfi.some.ui.splash.SplashActivity","noReset":"True"},null,{"firstMatch":[{"platformName":"Android","appium:platformVersion":"7","appium:deviceName":"AEUBB17A17505591","appium:appPackage":"/data/app/fi.dummy.some.qa-M207upJ07VKFxnvX_DPGDQ==/base.apk=fi.dummy.some.qa","appium:automationName":"appium","appium:app":"fi.dummy.some.qa","appium:appActivity":"com.dummyfi.some.ui.splash.SplashActivity","appium:noReset":"True"}]}]
[BaseDriver] Event 'newSessionRequested' logged at 1570716742264 (17:12:22 GMT+0300 (FLE Daylight Time))
[Appium] Could not parse W3C capabilities: 'noReset' must be of type boolean
[Appium] Trying to fix W3C capabilities by merging them with JSONWP caps
[BaseDriver] The capabilities ["platformVersion","deviceName","appPackage","automationName","app","appActivity","noReset"] are not standard capabilities and should have an extension prefix
[Appium] Could not parse fixed W3C capabilities: 'noReset' must be of type boolean. Falling back to JSONWP protocol
[Appium] 
[Appium] ======================================================================
[Appium]   DEPRECATION WARNING:
[Appium] 
[Appium]   The 'automationName' capability was not provided in the desired 
[Appium]   capabilities for this Android session
[Appium] 
[Appium]   Setting 'automationName=UiAutomator2' by default and using the 
[Appium]   UiAutomator2 Driver
[Appium] 
[Appium]   The next major version of Appium (2.x) will **require** the 
[Appium]   'automationName' capability to be set for all sessions on all 
[Appium]   platforms
[Appium] 
[Appium]   In previous versions (Appium <= 1.13.x), the default was 
[Appium]   'automationName=UiAutomator1'
[Appium] 
[Appium]   If you wish to use that automation instead of UiAutomator2, please 
[Appium]   add 'automationName=UiAutomator1' to your desired capabilities
[Appium] 
[Appium]   For more information about drivers, please visit 
[Appium]   http://appium.io/docs/en/about-appium/intro/ and explore the 
[Appium]   'Drivers' menu
[Appium] 
[Appium] ======================================================================
[Appium] 
[Appium] Appium v1.15.0 creating new AndroidUiautomator2Driver (v1.37.1) session
[BaseDriver] Creating session with MJSONWP desired capabilities: {
[BaseDriver]   "platformName": "Android",
[BaseDriver]   "platformVersion": "7",
[BaseDriver]   "deviceName": "AEUBB17A17505591",
[BaseDriver]   "appPackage": "/data/app/fi.dummy.some.qa-M207upJ07VKFxnvX_DPGDQ==/base.apk=fi.dummy.some.qa",
[BaseDriver]   "automationName": "appium",
[BaseDriver]   "app": "fi.dummy.some.qa",
[BaseDriver]   "appActivity": "com.dummyfi.some.ui.splash.SplashActivity",
[BaseDriver]   "noReset": "True"
[BaseDriver] }
[BaseDriver] Capability 'noReset' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Session created with session id: 0d5cd899-4a0b-4fa0-b000-23d355efd8f0
[UiAutomator2] Deleting UiAutomator2 session
[BaseDriver] Event 'newSessionStarted' logged at 1570716742272 (17:12:22 GMT+0300 (FLE Daylight Time))
[MJSONWP] Encountered internal error running command: Error: The application at 'fi.dummy.some.qa' does not exist or is not accessible
[MJSONWP]     at APPLICATIONS_CACHE_GUARD.acquire (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\helpers.js:158:13)
[HTTP] <-- POST /wd/hub/session 500 9 ms - 213
[HTTP] `

**Comment by kootjart** [comment]
Hmmm. Now I got it working. It was _automationName_ in the Open Application command
`
Open Application  ${REMOTE_URL}  platformName=${PLATFORM_NAME}  platformVersion=${PLATFORM_VERSION}  deviceName=${DEVICE_NAME}  appPackage=${${ENV}_APP_PACKAGE}  automationName=UiAutomator1  app=${${ENV}_APP}  appActivity=com.suomifi.viestit.ui.splash.SplashActivity     noReset=True`

Previous automation name was appium.

**Comment by kootjart** [comment]
I think this is related to thing, that new version of Appium is by default choosing UiAutomator2, if automationName=appium. I don't yet have UiAutomator2 so I have to use UiAutomator1.

**Comment by KazuCocoa** [comment]
Ah, thanks. 
The change happened in 1.14.0 https://github.com/appium/appium/releases/tag/v1.14.0 , but the desktop was not released.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
