### ISSUE TITLE
An Android PWA can't be seen as a separate context and can't be automated

### ISSUE THREAD

**Issue by wswebcreation** [appium/appium#13379]
## The problem
PWA's are _just Webviews_ and we should be able to automate them with Appium. We are able to add the PWA to the home screen but then we are not able to access the _webview_, see also [here](https://github.com/wswebcreation/pwa-example#android-issues)

## Environment

* Appium version (or git revision) that exhibits the issue: `1.15.0`
* Desktop OS/version used to run Appium: Mac OSX `10.14.6 (18G103)`
* Node.js version (unless using Appium.app|exe): `v10.16.3`
* Npm or Yarn package manager: npm
* Mobile platform/version under test: `Android 9.0`
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs / Code To Reproduce Issue

I created a sample repo with the setup and the Android logs which can be found [here](https://github.com/wswebcreation/pwa-example)

**Comment by aku-xima** [comment]
I highly recommend this! As PWA seems to be a BIG innovation step, this is a must have!

**Comment by imurchie** [comment]
@wswebcreation the Android tests in your sample repository work for me, with only the addition of the `chromedriverDisableBuildCheck` capability, set to `true`, so I didn't need to download any different Chromedrivers (my Android 9 emulator has Chrome `69.0.3497` but the latest Appium beta comes with Chromedriver `79.0.3945.36`)

On a wim I downloaded Chromedriver `2.44` and it also works.

**Comment by wswebcreation** [comment]
I've managed to get this working, the repo is updated and this issue can be closed now
