### ISSUE TITLE
Update Desired Capabilities Doc

### ISSUE THREAD

**Issue by pramodKarande** [appium/appium#13370]
As per release note of new version of Appium (https://github.com/appium/appium/releases/tag/v1.15.0) , many new capabilities are introduced.
It will be great if you update all this info with examples here : http://appium.io/docs/en/writing-running-appium/caps/

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium.io
https://appium.io/docs/en/writing-running-appium/caps/
