### ISSUE TITLE
Xcode 11: Simulator: SimRenderServer goes "Out of memory" quickly

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#13378]
## The problem
While executing tests with Simulator (iOS 13.0 tested) with new Xcode 11 - "SimRenderServer" eats 15Gb in 3min easily and cause quickly out of memory issues on machine.

## Environment
* Appium version (or git revision) that exhibits the issue: 1.16.beta.1
* Last Appium version that did not exhibit the issue (if applicable): Xcode 10 and appium 1.15
* Mobile platform/version under test: macOS 10.14.5
* Real device or emulator/simulator: Simulator

## Details
I found in Xcode release notes a bit of it:
```
When running on macOS versions before 10.15 some IOSurface instances are leaked by processes running in Simulator. This shows up as high memory usage by SimRenderServer even when no apps are running in simulators. Simulators running on macOS 10.15 aren’t affected. (50880827)
```

**Comment by mykola-mokhnach** [comment]
How this error might be related to Appium? I assume the best place to report it would be Apple's Radar

**Comment by amedvedjev** [comment]
@mykola-mokhnach  Catalina + latest Xcode = FIXED. 30MB now ;-)
