### ISSUE TITLE
Appium inspector spying on incorrect elements with the android UI Automator 2

### ISSUE THREAD

**Issue by KS261187** [appium/appium#13373]
## The problem

When I tried to spy the elements on Android using Appium inspector, I noticed that it is returning the incorrect element upon spying. In most of the cases the elements are kind of shuffled through out the page and hence when I tap on a right element, Appium is tapping on an incorrect element. In some cases the page source is not returning the objects and in most cases the objects are shuffled. I am using UIAutomator 2 here. If you look at the attached screenshot, I am trying to spy on the object  "Your cart is empty" but it is pointing towards the "Cart button".

## Environment

* Appium version (or git revision) that exhibits the issue:1.15
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS 10.14.6
* Node.js version (unless using Appium.app|exe):10.16.3
* Npm or Yarn package manager:
* Mobile platform/version under test:Android 10
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe:exe

## Details

The elements where getting rendered perfectly fine till last sprint but when I upgraded to Appium 1.15, I started noticing this issue. So I tried going to back to the old Appium and surprisingly I have started seeing the same issue there. Not sure what component got changed. Appreciate if some one can point out the difference, so that for now I can go back to the previous version to make it work. I am kind of stuck here with this issue.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
<img width="1094" alt="Screen Shot 2019-10-06 at 6 54 55 PM" src="https://user-images.githubusercontent.com/26659582/66278061-624f0000-e86b-11e9-891d-13ac190f73fd.png">

If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Please switch to web view context if you are working with web views. Appium simply gets what the app passes to the system accessibility layer and has absolutely no influence to its content.

**Comment by KS261187** [comment]
This is working perfectly fine with IOS and also this is an hybrid app designed using Ionic framework. This issue is happening very specific to android ui automator 2. Also when I log out of the app for the second time and then load the same screen again, the elements are getting aligned perfectly fine. Please look at the issue and let us know what could be possibly wrong. Appreciate your response on the same.

**Comment by mykola-mokhnach** [comment]
Like I said, nothing to check there on Appium side. Consider reporting the problem to ionic or to Google.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
