### ISSUE TITLE
Some elements found via getPageSource cannot be found using xpath/class name on real devices

### ISSUE THREAD

**Issue by jamesvanhorn** [appium/appium#13381]
## The problem

We noticed that some tests were failing intermittently. Found out that on physical devices only, a handful of elements were failing to be found. Notably elements that didn't have IDs so we had to use xpath/class name.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Mac OSX Mojave
* Node.js version (unless using Appium.app|exe): 10
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS 12/13 (Xocde 11)
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Both

## Details

In the attached gist, you'll see an `XCUIElementTypeScrollView` element. Works fine to find it when we find it when the device is a simulator, but not a physical device. 

Of note, Id tried going further up the hierarchy with no luck. As a concrete example //XCUIElementTypeCollectionView is found but //XCUIElementTypeCollectionView/* returns nothing then. It's a static loaded page, so I don't think it's any kind of page loading changing the source. This occurs whether or not I use Appium desktop with the inspector, or just try to run the test normally (where we do things like wait for the page to load etc)

## Link to Appium logs

Snippet of logs showing findElements returning nothing. Not really sure what else i can provide for debugging.

//driver.findElement(By.xpath(//XCUIElementTypeScrollView))
$ [HTTP] --> POST /wd/hub/session/ddcd847c-38fe-4b52-84c3-a2fa7416a280/elements
[HTTP] {"using":"xpath","value":"//XCUIElementTypeScrollView"}
[debug] [MJSONWP (ddcd847c)] Calling AppiumDriver.findElements() with args: ["xpath","//XCUIElementTypeScrollView","ddcd847c-38fe-4b52-84c3-a2fa7416a280"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [MJSONWP (ddcd847c)] Responding to client with driver.findElements() result: []
[HTTP] <-- POST /wd/hub/session/ddcd847c-38fe-4b52-84c3-a2fa7416a280/elements 200 37477 ms - 74

//driver.findElement(By.className(XCUIElementTypeScrollView))
[HTTP] --> POST /wd/hub/session/ddcd847c-38fe-4b52-84c3-a2fa7416a280/elements
[HTTP] {"using":"class name","value":"XCUIElementTypeScrollView"}
[debug] [MJSONWP (ddcd847c)] Calling AppiumDriver.findElements() with args: ["class name","XCUIElementTypeScrollView","ddcd847c-38fe-4b52-84c3-a2fa7416a280"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [WD Proxy] Matched '/elements' to command name 'findElements'
[debug] [WD Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/E4AA5BE6-0CF4-405F-918D-5C4D4F4646EE/elements] with body: {"using":"class name","value":"XCUIElementTypeScrollView"}
[HTTP] --> GET /wd/hub/session/ddcd847c-38fe-4b52-84c3-a2fa7416a280
[HTTP] {}
[debug] [MJSONWP (ddcd847c)] Calling AppiumDriver.getSession() with args: ["ddcd847c-38fe-4b52-84c3-a2fa7416a280"]
[debug] [XCUITest] Executing command 'getSession'
[debug] [WD Proxy] Got response with status 200: {"value":[],"sessionId":"E4AA5BE6-0CF4-405F-918D-5C4D4F4646EE"}
[XCUITest] Merging WDA caps over Appium caps for session detail response
[debug] [MJSONWP (ddcd847c)] Responding to client with driver.findElements() result: []
[HTTP] <-- POST /wd/hub/session/ddcd847c-38fe-4b52-84c3-a2fa7416a280/elements 200 2430 ms - 74

Page source for reference: https://gist.github.com/jamesvanhorn/63b70af1507069722b63f0567a0b65c5

## Code To Reproduce Issue [ Good To Have ]

just a basic drive.findElement(s) for only certain locators. Some xpaths / class names work, but not all.

**Comment by mykola-mokhnach** [comment]
Try to limit the search scope for such elements. E. g. instead of looking for a table cell under the whole page tree, find the parent table element first and then find the cell using it as the parent

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing more to do on this issue unless we are able to reproduce it locally
