### ISSUE TITLE
Appium 1.15 - Force w3c to false on chromedriverArgs capability does not work

### ISSUE THREAD

**Issue by fabianaapateanu** [appium/appium#13385]
## The problem

I am trying to set w3c to false, in order to be able to use ID locator in my hybrid app  - Webview.
I set this on the AndroidDriver with ChromeOptions, and I have tried it in several ways. I still get the error that the locator ID is not supported

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Mac OS Mojave 10.14.6
* Node.js version (unless using Appium.app|exe): 11.13.0
* Npm or Yarn package manager: npm 6.9.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real device, Galaxy Tab A
* Appium CLI or Appium.app|exe: Appium 1.15 CLI
* Chromedriver v. 77
## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

I know the logs says Appium 1.16 beta - this is because I have applied the fix for iOS Javascript execution from here:
https://github.com/appium/appium/issues/13310
But this issue was present on Appium 1.15 as well. 

https://gist.github.com/fabianaapateanu/5c464683ac25565efe410732eebf3637

## Code To Reproduce Issue [ Good To Have ]

I am using Java client and set the capability like this:

`ChromeOptions options = new ChromeOptions();
 options.setCapability("w3c", false);
capabilities.setCapability("chromedriverArgs", options);
 driver = new AndroidDriver(url, capabilities);`

**Comment by mykola-mokhnach** [comment]
Did you check https://github.com/appium/java-client/issues/1242?

**Comment by fabianaapateanu** [comment]
> Did you check [appium/java-client#1242](https://github.com/appium/java-client/issues/1242)?
Hi @mykola-mokhnach,
I have checked it now. I already did everything that is stated there. The java client from master has been used previously.
I want to mention I am on chromedriver version 77 and I am running on a real Android device on a hybrid mobile app.
I have now also used this code, and it still doesn't work:

`                JSONObject jo = new JSONObject();
                jo.put("w3c", "false");
               capabilities.setCapability("appium:chromeOptions", jo);
                driver = new AndroidDriver(url, capabilities);`

**Comment by fabianaapateanu** [comment]
Ok, Finally managed do make it work with:

`ChromeOptions chromeOptions = new ChromeOptions();
   chromeOptions.setExperimentalOption("w3c", false);
   chromeOptions.setCapability("browserName", "");
capabilities.merge(chromeOptions);
driver = new AndroidDriver(url, capabilities);`
This was needed because I also specify appPackage capability.

**Comment by mykola-mokhnach** [comment]
> jo.put("w3c", "false"); 

it must be a boolean value, not a string

Closed as not an issue
