### ISSUE TITLE
Does WebDriverAgent support iOS 13 now?

### ISSUE THREAD

**Issue by zhangdongjia** [appium/appium#13389]
It seems that iOS 13 is not supported yet, when I try to use it to drive app on a real device.
By the way, the Xcode is 11.
I mean this project: https://github.com/appium/WebDriverAgent

**Comment by amedvedjev** [comment]
I have no problem with following config:
 - MacOS Catalina
 - xCode 11
 - iOS 13.1.2 (real device)
 - Appium 1.16.beta1

**Comment by mykola-mokhnach** [comment]
Yes, iOS 13 is supported since Appium 1.15
