### ISSUE TITLE
An iOS PWA can be automated, but loses it's webview after closing the app

### ISSUE THREAD

**Issue by wswebcreation** [appium/appium#13380]
## The problem
PWA's are _just Webviews_ and we should be able to automate them with Appium. We are able to:

- add the PWA to the home screen 
- execute a test in the PWA

but after putting the app to the background and opening it again their is no context anymore, see also [here](https://github.com/wswebcreation/pwa-example#ios-issuess)

## Environment

* Appium version (or git revision) that exhibits the issue: `1.15.0`
* Desktop OS/version used to run Appium: Mac OSX `10.14.6 (18G103)`
* Node.js version (unless using Appium.app|exe): `v10.16.3`
* Npm or Yarn package manager: npm
* Mobile platform/version under test: `iOS 12.2`
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs / Code To Reproduce Issue

I created a sample repo with the setup and the iOS logs which can be found [here](https://github.com/wswebcreation/pwa-example)

**Comment by imurchie** [comment]
@wswebcreation Using your repo I can consistently get the tests to work with the latest beta of Appium. Two things of note:
1. The cookie test will fail if you do not delete the app of the home screen between runs, since the selection process always selects the first app, which will already have been run.
2. I modified the opening function like this:
    ```js
    function openPwa() {
      driver.switchContext('NATIVE_APP');
      // Wait till the app icon is on the screen (this might take a while)
      // Click on it, in our case it is the ~Smashing
      $('~Smashing').waitForDisplayed(15000);
      $('~Smashing').click();

      const context = driver.waitUntil(() => {
        const smashingWebviews = driver.getContexts()
          .filter((wv) => wv.title && wv.title.includes('Smashing Magazine'));
        console.log('smashingWebviews:', smashingWebviews.map((wv) => wv.id));
        for (const wv of smashingWebviews) {
          driver.switchContext(wv.id);
          if ($('#menu-button').isDisplayed()) {
            return wv;
          }
        }

        // nothing was found, so do it all again
        driver.switchContext('NATIVE_APP');
        return false;
      }, DEFAULT_TIMEOUT);

      console.log(`\n\nFINALLY SELECTING: ${JSON.stringify(context)}`);
      // we should already be in the context, but this won't hurt
      driver.switchContext(context.id);
    }
    ````

**Comment by wswebcreation** [comment]
Hi @imurchie 

I've been running this locally with the latest `1.16.0-beta.3` and it works, but only on a clean simulator. If I clean the simulator the amount of webviews is reduced to 1 and this will work. 
If a test is done, remove the PWA from the homescreen and run the test again, then I get this

```log
[0-0] smashingWebviews =  [ { id: 'NATIVE_APP' },
  { id: 'WEBVIEW_4989.1',
    title: 'Smashing Magazine — For Web Designers And Developers',
    url: 'https://www.smashingmagazine.com/',
    bundleId: 'com.apple.SafariViewService' },
  { id: 'WEBVIEW_4989.3',
    title: '',
    url: 'about:blank',
    bundleId: 'com.apple.SafariViewService' },
  { id: 'WEBVIEW_4989.5',
    title: 'Smashing Magazine — For Web Designers And Developers',
    url: 'https://www.smashingmagazine.com/',
    bundleId: 'com.apple.SafariViewService' },
  { id: 'WEBVIEW_4989.7',
    title: 'Smashing Magazine — For Web Designers And Developers',
    url: 'https://www.smashingmagazine.com/',
    bundleId: 'com.apple.SafariViewService' },
  { id: 'WEBVIEW_4989.11',
    title: 'Smashing Magazine — For Web Designers And Developers',
    url: 'https://www.smashingmagazine.com/',
    bundleId: 'com.apple.SafariViewService' } ]
[0-0] smashingWebviews: [ 'WEBVIEW_4989.1',
  'WEBVIEW_4989.5',
  'WEBVIEW_4989.7',
  'WEBVIEW_4989.11' ]
[0-0] 

FINALLY SELECTING: {"id":"WEBVIEW_4989.1","title":"Smashing Magazine — For Web Designers And Developers","url":"https://www.smashingmagazine.com/","bundleId":"com.apple.SafariViewService"}
```

And the tests fail and that was also my initial problem. So I don't know if the issue will be solved with the new version of Appium. Maybe have a call about it?

**Comment by wswebcreation** [comment]
I managed to get this working, see https://github.com/wswebcreation/pwa-example, but.... there is still a challenge with iOS 12 and 13 (not with 14). The webviews are still kept in memory. iOS 12 is getting used less and 13 is also decreasing. I wonder if we should dive into this more or just keep it like this.
What do you think @mykola-mokhnach ?

**Comment by mykola-mokhnach** [comment]
I am ok to close the issue

**Comment by wswebcreation** [comment]
Thanks, closing it then
