### ISSUE TITLE
appium-uiautomator2-server-v3.7.0.apk does not exist or is not accessible

### ISSUE THREAD

**Issue by reply2sagar** [appium/appium#13390]
## The problem

After updating the appium to 1.15.0 I am seeing the error - appium-uiautomator2-server-v3.7.0.apk does not exist or is not accessible

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.0
* Last Appium version that did not exhibit the issue (if applicable):1.14.2
* Desktop OS/version used to run Appium: Windows OS
* Node.js version (unless using Appium.app|exe):10.16.3
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: Android Orio
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium CLI

**Comment by mykola-mokhnach** [comment]
Please provide the full server log
