### ISSUE TITLE
The desired capabilities must include either an app or a bundleId for iOS

### ISSUE THREAD

**Issue by hadrianjmnz90** [appium/appium#13399]
## The problem

I am trying to run a test in iphone real device, which actually worked fine before updating appium server to version 1.15.0, and now i am getting the error "The desired capabilities must include either an app or a bundleId for iOS" 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.0
* Last Appium version that did not exhibit the issue (if applicable): 1.14
* Desktop OS/version used to run Appium: Mac Mojave 10.14.5
* Node.js version (unless using Appium.app|exe): 12.10
* Npm or Yarn package manager: 6.11.3
* Mobile platform/version under test: IOS
* Real device or emulator/simulator: Iphone 8 Plus
* Appium CLI or Appium.app|exe:

## Link to Appium logs
[https://gist.github.com/hadrianjmnz90/bacc64ebf86ec44a49df92fb9bad51b0](url)

**Comment by mykola-mokhnach** [comment]
> [BaseDriver]     "appium:appName": "/Users/hectorjimenez/Desktop/apps/xxxx.ipa",

The error is expected. The path to an app should be provided under `app` capability.
