### ISSUE TITLE
not disjunct servers - browser started on wrong device (iOS)

### ISSUE THREAD

**Issue by SebastianSolidwork** [appium/appium#13392]
## The problem

With 1.15.0 my parallel running appium servers are not fully disjunct any more.
Everytime i run a test against simulator+browser on server 1, in addition server 2 triggers on my real device a browser window to pop up.

We are having an browser application which additionally is packed into an hyprid iOS app.
1. server: simulator with tests in safari browser, port 4723
1. server: real device with an app, port 4724

The start of the app or browser is controlled by the capabilities i choose by the runsetting-file in in Visual Studio.

### Steps to reproduce:
1. Requirement: Run once a test against server 2 with device+app.
    1. Note: A fresh started server without any executed tests isn't a problem
1. Run tests against the server 1 with simulator+browser
    1. Error: With every test execute on the device is the safari browser opened.
    1. Note: The tests on the simulator are running with out a problem.

## Environment

* Appium version : 1.15.0 / 1.16.0-beta1
* Last Appium version that did not exhibit the issue (if applicable): 1.14.2
* Desktop OS/version used to run Appium: macOS 10.14.6
* Node.js version (unless using Appium.app|exe): 
* Npm or Yarn package manager: 
* Mobile platform/version under test: 
* Real device or emulator/simulator: Mixed
* Appium CLI or Appium.app|exe: Both
* Xcode version : 11.0

## Link to Appium logs

server 1 - simulator
https://gist.github.com/SebastianSolidwork/8dceb7cca49253d544d4d9f9e3505051

server 2 - device
https://gist.github.com/SebastianSolidwork/7d64931e364feea451606a4dd8700623
10:27:52:507 Was the last action of the real device test. After that the browser opening starts.

**Comment by mykola-mokhnach** [comment]
Please attach the full server logs

**Comment by SebastianSolidwork** [comment]
@mykola-mokhnach I have done so.

**Comment by mykola-mokhnach** [comment]
I would like to see the session capabilities. Are you sure you set unique ports for each device?

**Comment by SebastianSolidwork** [comment]
@mykola-mokhnach Now i have attached full logs.

server 1 simulator:
- started from console: appium --port 4724
- Url to connect with: http://10.44.157.138:4724/wd/hub
- capabilites:
{
  "platformName": "iOS",
  "platformVersion": "12.2",
  "platform": "Mac",
  "deviceName": "iPad Mini 4",
  "browserName": "Safari",
  "automationName": "XCUITest",
  "autoWebview": "true",
  "useNewWDA": "true"
}

server 2 device:
- started from console: appium --port 4723
- Url to connect with: http://10.44.157.138:4723/wd/hub
- capabilites:
{
  "platformName": "iOS",
  "platformVersion": "12.4",
  "platform": "Mac",
  "deviceName": "ISA*",
  "udid": "DELETED",
  "app": "DELETED",
  "automationName": "XCUITest",
  "xcodeOrgId": "DELETED",
  "xcodeSigningId": "iPhone Developer",
  "updatedWDABundleId": "pd.appium.WebDriverRunner",
  "startIWDP": "true",
  "autoWebview": "true",
  "useNewWDA": "false",
}

**Comment by SebastianSolidwork** [comment]
I let both servers run parallel. This works with 1.14.0.
I have just updated appium. I switched the versions back and forth today.

**Comment by mykola-mokhnach** [comment]
Do you follow https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/parallel-tests.md?

I don't observe that unique ports are being set for each device

**Comment by mykola-mokhnach** [comment]
BTW, IWDP is not needed anymore for Appium 1.15+

**Comment by SebastianSolidwork** [comment]
It works with different wdaLocalPorts ! :-)
I'm a bit confused that it worked without them until now.

Thanks for the tip about IWPD.
