### ISSUE TITLE
Unable to launch WebDriverAgent because of xcodebuild failure: Command 'carthage bootstrap --platform iOS\,tvOS'

### ISSUE THREAD

**Issue by LilySmol** [appium/appium#13396]
## The problem

Unable to launch WebDriverAgent because of xcodebuild failure: Command 'carthage bootstrap --platform iOS\,tvOS'

## Environment

* Appium 1.15.0
* Xcode 11.0
* simulator: iPhone Xs - 12.2
* carthage 0.33.0

## Link to Appium logs

https://gist.github.com/LilySmol/c1e4464b1616b7bff4964414bf14f738

## Capabilities

capabilities.setCapability("deviceName", ParametersProvider.getProperty("deviceName"));
        capabilities.setCapability("udid", udidEmulator);
        capabilities.setCapability("platformName", ParametersProvider.getProperty("platformName"));
        capabilities.setCapability("platformVersion", ParametersProvider.getProperty("platformVersion"));
        capabilities.setCapability("app", System.getProperty("path"));
        capabilities.setCapability("automationName", "XCUITest");
        capabilities.setCapability("wdaLocalPort", wdaLocalPort);
        capabilities.setCapability("newCommandTimeout", 120);
        capabilities.setCapability("connectHardwareKeyboard", false);
        capabilities.setCapability("wdaEventloopIdleDelay", 5);
        capabilities.setCapability("useNewWDA", false);
        capabilities.setCapability("waitForQuiescence", false);
        capabilities.setCapability("noReset", true);
        capabilities.setCapability("wdaLaunchTimeout", 240000);
        capabilities.setCapability("wdaConnectionTimeout", 240000);
        capabilities.setCapability("forceMjsonwp", true);

**Comment by mykola-mokhnach** [comment]
> [debug] [WebDriverAgent] *** Checking out RoutingHTTPServer at "v1.0.2"
> [debug] [WebDriverAgent] *** Checking out YYCache at "1.1.0"
> [debug] [WebDriverAgent] *** Checking out CocoaAsyncSocket at "7.6.3"
> [debug] [WebDriverAgent] A shell task (/usr/bin/env git checkout --quiet --force 1.1.0 (launched in /Users/teamcity/Library/Caches/org.carthage.CarthageKit/dependencies/YYCache)) failed with exit code 128:
> [debug] [WebDriverAgent] fatal: Unable to create '/Users/teamcity/Library/Caches/org.carthage.CarthageKit/dependencies/YYCache/./index.lock': File exists.
> [debug] [WebDriverAgent] Another git process seems to be running in this repository, e.g.
> [debug] [WebDriverAgent] an editor opened by 'git commit'. Please make sure all processes
> [debug] [WebDriverAgent] are terminated then try again. If it still fails, a git process
> [debug] [WebDriverAgent] may have crashed in this repository earlier:
> [debug] [WebDriverAgent] remove the file manually to continue.

**Comment by OmeraWasTaken** [comment]
I have the same issue but is not possible to pass  `HTTPConnection *connection` from `assign` to `weak` it should do the job no ?

**Comment by mykola-mokhnach** [comment]
Closed as third party issue.

This must a problem with local system setup or carthage itself.
