### ISSUE TITLE
Appium can't  fill in the secret field completely

### ISSUE THREAD

**Issue by FirstAM** [appium/appium#13398]
## The problem

When i try write text to secret field appium cant fill in the secret field completely. In my case filled only 1-2 chars , appium log "says" all is ok 
`Got response with status 200: {"value":null,"sessionId":"D3602382-3B75-4ACD-8CDE-25CB75C13EB3"}`

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.0
* Last Appium version that did not exhibit the issue (if applicable): 1.13.0
* Desktop OS/version used to run Appium: Mac OS  10.14.5 
* Node.js version (unless using Appium.app|exe): v10.15.2
* Npm or Yarn package manager: 6.4.1
* Mobile platform/version under test: IOS 
* Real device or emulator/simulator: Iphone XS ( real ) iOS 13.1.2 
* Appium CLI or Appium.app|exe: Appium CLi 

## Details

Full Appium logs 

[appium_logs_42.txt](https://github.com/appium/appium/files/3707952/appium_logs_42.txt)

**Comment by mykola-mokhnach** [comment]
I would try to play with `maxTypingFrequency` setting or locate and click keyboard buttons like normal elements as a possible workaround.

**Comment by FirstAM** [comment]
I think I found a problem when a different keyboard language is enabled on the device, and the ENG keyboard is not the first, appium cannot fill in a secret field, fill in another language, but filling in the numbers is OK.
This problem is solved when I first install the ENG keyboard, maybe you have any possibilities for this case? Thanks

**Comment by KazuCocoa** [comment]
Thanks.

Do you mean  'English' keyboard should be the top of the order as below and be selected? > when I first install the ENG keyboard

<img src=https://user-images.githubusercontent.com/5511591/66622133-8c435200-ebde-11e9-8bb4-b115937d04c4.png width=300>

**Comment by FirstAM** [comment]
> Thanks.
> 
> Do you mean 'English' keyboard should be the top of the order as below and be selected? > when I first install the ENG keyboard

Yes.Apparently for the correct data entry, at the time of data entry, the keyboard with the desired language should be turned on

**Comment by mykola-mokhnach** [comment]
I don't think there is anything here that can be done on Appium side. Closed as third party issue
