### ISSUE TITLE
LaunchApp() Reinstalls the Whole App

### ISSUE THREAD

**Issue by awhisler-nutrien** [appium/appium#13406]
## The problem
webdriverio/Appium using `launchApp()` will reinstall or reset the app which is not what I want to do. I want to closeApp() then launchApp() to see what the state of the app is because that is different from deleting/reinstalling the app

I have tried adding the capability `noReset: true` and `fullReset: false` and it doesn't do anything for my problem

## Environment
- Appium version (or git revision) that exhibits the issue: 1.15.0 (and below)
- Node.js version (unless using Appium.app|exe): 12.6.0
- Yarn package manager: 1.17.3
- Mobile platform/version under test: iOS
- Real device or emulator/simulator: Simulator
- Appium.ap

**Comment by mykola-mokhnach** [comment]
We cannot change the current behaviour of launchApp/closeApp since that would break the backward compatibility. Under the hood they work similarly to start/quit session.

What exactly you are trying to achieve?

**Comment by awhisler-nutrien** [comment]
Basically, if I close and open the app I want to make sure the username is still there is they clicked remember me but we have a business rule that if you delete and reinstall the app, it all resets so I need to just close and open the app to verify but launchApp() seems to be installing/resetting it.

**Comment by KazuCocoa** [comment]
Could http://appium.io/docs/en/commands/device/app/activate-app/ and http://appium.io/docs/en/commands/device/app/terminate-app/ be the solution?

They can change the app state to running in the foreground and not running/
http://appium.io/docs/en/commands/device/app/app-state/

**Comment by awhisler-nutrien** [comment]
@KazuCocoa no because I am using webdriverio and those are not accepted in webdriverio

**Comment by mykola-mokhnach** [comment]
There are `mobile:` synonyms for these endpoints. Although, consider creating a feature request to WebdriverIO then. Nothing we can do here on server side though.

**Comment by awhisler-nutrien** [comment]
@mykola-mokhnach my issue is for Appium though - launchApp() should not reinstall the app. That is a bug.

**Comment by KazuCocoa** [comment]
activate-app and terminate-app were introduced to achieve handling existing apps, start the process/terminate it, over a couple of years ago with keeping the backward compatibility as https://github.com/appium/appium/issues/13406#issuecomment-540769892

btw, it looks they have https://webdriver.io/docs/api/appium.html#activateapp and https://webdriver.io/docs/api/appium.html#terminateapp . Did _Not accepted_ means they did not work or they denied to implement them?

**Comment by jagsme** [comment]
Hi @KazuCocoa @awhisler-nutrien , I am also facing the same problem.

this is the line : wd = new IOSDriver<IOSElement>(new URL(webDriverUrl), devCapabilities); 

iOS 13.1.2 : the app is reset and it is launched from the login page.
iOS 12.3.1:  the app continues from the expected page.

**Comment by jagsme** [comment]
@KazuCocoa @awhisler-nutrien , correction on the above.

The app doesn't reinstalls. It resets all the data. So when the app launches it opens registration page, instead of the login page.

observed that when we put `setCapability("autoLaunch", true); ` it causes the app to reset. when we put `setCapability("autoLaunch", false);` the app doesn't launch.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
