### ISSUE TITLE
Create new release for appium-windows-driver module with https://github.com/appium/appium/issues/13173

### ISSUE THREAD

**Issue by Korop** [appium/appium#13405]
## The problem

We need the https://github.com/appium/appium/issues/13173 already merged feature in a package release.
Not sure how to request this.

## Environment
Windows
## Details

If necessary, describe the problem you have been experiencing in more detail.

## Code To Reproduce Issue [ Good To Have ]
https://github.com/appium/appium/issues/13173
https://github.com/appium/appium-windows-driver/pull/59

**Comment by jlipps** [comment]
WAD has been updated and a new version of the windows driver published.
