### ISSUE TITLE
javascript-wd Sample-code working?

### ISSUE THREAD

**Issue by Funi1234** [appium/appium#13411]
## The problem

Trying to get the javascript-wd sample-code working for iOS and having a very hard time. I updated the config to an iPhone X and version 13.1 from an iPhone 6 and 12.0.

## Environment

* Appium version (or git revision) that exhibits the issue: **1.15.0**
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: **OSX 10.14.6**
* Node.js version (unless using Appium.app|exe): **v12.11.1**
* Npm or Yarn package manager: **npm**
* Mobile platform/version under test: **iOS 13.1**
* Real device or emulator/simulator: **simulator**
* Appium CLI or Appium.app|exe: **CLI**

## Details

I installed everything, Appium-doctor is all green and then I ran what Appium tells me to "Appium & nam test"

## Link to Appium logs

https://gist.github.com/Funi1234/cebabe53f179b3e182f5343d47aed0fa

**Comment by imurchie** [comment]
This appears to be something wrong with the `idb` integration. Can you try without `idb` (unfortunately, at this point that means uninstalling the `idb companion`)?

**Comment by Funi1234** [comment]
@imurchie That worked. I'm still unsure why idb wasn't working but this fix will do for now. Thanks.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
