### ISSUE TITLE
Original error: Could not navigate to webview! Err: Error: connect ECONNREFUSED 127.0.0.1:27753

### ISSUE THREAD

**Issue by ishanm120** [appium/appium#13410]
## The problem

Unable to run test on Real device, It launches safari and closes automatically.

## Environment

* Appium version : 1.14.2
* Desktop OS/version : 10.14.4 (18E227)
* Npm or Yarn package manager: 6.12.0
* Mobile platform/version under test: iOS 12.4
* Real device or emulator/simulator: Real device iphoneX

## Link to Appium logs

https://gist.github.com/ishanm120/28a11ba58b4b76dbc54dd793b2a8cfb1.js

**Comment by mykola-mokhnach** [comment]
Please check if it works in appium@beta

**Comment by ishanm120** [comment]
Tried with v1.16.0-beta.1

Now getting error:
Connection refused

Logs are as follows:

[debug] [XCUITest] Auto-detecting real device udid...
[debug] [XCUITest] Detected real device udid: '6e1acaef924b19db4060ab4a540a2aab37165a7b'
[debug] [XCUITest] Creating iDevice object with udid '6e1acaef924b19db4060ab4a540a2aab37165a7b'
[XCUITest] Determining device to run tests on: udid: '6e1acaef924b19db4060ab4a540a2aab37165a7b', real device: true
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1570790774715 (16:16:14 GMT+0530 (India Standard Time))
[XCUITest] Safari test requested
[debug] [BaseDriver] Event 'appConfigured' logged at 1570790774715 (16:16:14 GMT+0530 (India Standard Time))
[debug] [BaseDriver] Event 'resetStarted' logged at 1570790774715 (16:16:14 GMT+0530 (India Standard Time))
[debug] [XCUITest] Reset: running ios real device reset flow
[debug] [BaseDriver] Event 'resetComplete' logged at 1570790774716 (16:16:14 GMT+0530 (India Standard Time))
[debug] [XCUITest] Crash reports root '/Users/admin/Library/Logs/CrashReporter/MobileDevice/GSPANN_MD_207' does not exist. Got nothing to gather.
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1570790775003 (16:16:15 GMT+0530 (India Standard Time))
[XCUITest] Setting up real device
[RemoteDebugger] Remote Debugger version 6.2.0
[debug] [RemoteDebugger] useNewSafari --> false
[debug] [RemoteDebugger] Checking which communication style to use (Safari on platform version '12.2')
[debug] [RemoteDebugger] Platform version equal or higher than '12.2': true
[RemoteDebugger] Setting communication protocol: using Target-based communication
[debug] [RemoteDebugger] Sending connection key request
[debug] [RemoteDebugger] Sending '_rpc_reportIdentifier:' message (id: 0)
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message (id: 1)
uncaughtException: write EPIPE
Error: write EPIPE
    at WriteWrap.afterWrite (net.js:788:14)
[debug] [RemoteDebugger] Sending to Web Inspector took 13ms
[debug] [RemoteDebugger] Connected to application
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'
[debug] [XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[DevCon Factory] Requesting connection for device 6e1acaef924b19db4060ab4a540a2aab37165a7b on local port 8100, device port 8100
[debug] [DevCon Factory] Cached connections count: 0
[DevCon Factory] Port #8100 is busy
[DevCon Factory] Successfully requested the connection for 6e1acaef924b19db4060ab4a540a2aab37165a7b:8100

**Comment by mykola-mokhnach** [comment]
Are you able to connect to the web view with Safari remote debugger?

**Comment by ishanm120** [comment]
Yes Its working for me.

**Comment by mykola-mokhnach** [comment]
We did several more fixes to apiium@beta. Please reinstall it and try again

**Comment by mykola-mokhnach** [comment]
Closed because of no response
