### ISSUE TITLE
Feature request: close background apps

### ISSUE THREAD

**Issue by MarkSpencerTan** [appium/appium#13415]
## The Feature Request

An API to close all currently opened applications or apps in the background of the devices.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.0
* Desktop OS/version used to run Appium: MacOS & Windows
* Npm or Yarn package manager: npm
* Mobile platform/version under test: both ios/android
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Our testing environment involves testing with real devices and sometimes we find many apps are still running in the background of the devices after a while (could be from runs that did not clean up nicely with driver.quit()) and I was wondering if there is a way we can have that support with appium to close all opened applications that are just sitting in the background.

I know there is support right now to close the currently opened app, but none (i think) for other apps that were not opened by the current session.

We have a way to reboot the devices, but unfortunately, the apps are still there in the background when the devices come back on.

Thanks!

**Comment by mykola-mokhnach** [comment]
There is an endpoint to terminate an app by giving its bundle identifier (terminateApp). Otherwise XCTest API don't provide any possibilities for getting the list of background apps.

**Comment by MarkSpencerTan** [comment]
@mykola-mokhnach , ah I see thank you for that information! We were going to get the list of identifiers for androids using an adb command, but we weren't sure if it was possible with iOS or if there was an easier way with any existing appium tools. But If they don't have an API to get that list of background apps, then I think we can try just maintaining a known list of bundleIds and using that terminate app command you mentioned to close them down one by one if present.
