### ISSUE TITLE
Can`t connect to WDA on clean Appium SetUp iOS. WDA folder not created in Appium installation destination 

### ISSUE THREAD

**Issue by MorozDenys** [appium/appium#13429]
## The problem
My Test Script Worked in BrowserStack and i didn`t change anything in my framework. I`m using VM ware, so to test on real device iOS 13 i was forced to change macOS from highSierra to Mojave (Not update, but installed clean new OS) 

I followed all guidelines to install Appium again. 
I got new node, npm, JAVA_HOME, Appium 
For some reason when install appium from terminal it doesn`t create WDA folder here:  
` /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver` 

I tried to reinstall everything/ update everything but ended up just downloading WebDriverAgent folder from Official GitHub Repo and copying it there 
I ran script 
```
Mac-Admin:WebDriverAgent admin$ cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
Mac-Admin:WebDriverAgent admin$ mkdir -p Resources/WebDriverAgent.bundle
Mac-Admin:WebDriverAgent admin$ sh ./Scripts/bootstrap.sh -d
-e Fetching dependencies
*** Checking out RoutingHTTPServer at "v1.0.1"
*** Cloning RoutingHTTPServer
*** xcodebuild output can be found in /var/folders/l_/rw4xgjj50bb6nkjvty8yb1jh0000gn/T/carthage-xcodebuild.flxfqG.log
*** Downloading RoutingHTTPServer.framework binary at "v1.0.1"
```

Appium-doctor has no problems except I`m missing everything for Android - but i don`t need android  (It used to work without adroid studio and adb" 

My app is launching but in Appium logs i can see that i can`t connect to WDA

So 
## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Desktop OS/version used to run Appium:  10.14.6 MacOS Mojave
* Node.js version (unless using Appium.app|exe): 10.16.3
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: iOS 12/13 any 
* Real device or emulator/simulator:  real device browserstack/ local set up 
* Appium CLI or Appium.app|exe: cli 

## Details
My code 
```
public class IOSDriverManager {
    public static ThreadLocal<IOSDriver<IOSElement>> webDriver = new ThreadLocal<IOSDriver<IOSElement>>();

public static DesiredCapabilities getIOSCaps() {
        DesiredCapabilities caps =  DesiredCapabilities.iphone();
return caps;}

 public static IOSDriver<IOSElement> getThreadLocalDriver() {
        IOSDriver<IOSElement> driver = webDriver.get();
        if (driver == null) {
            createThreadLocalWebDriver();
            driver = webDriver.get();
        }
        return driver;
    }
 public static void createThreadLocalWebDriver() {
        IOSDriver<IOSElement> driver = null;

                try {
                    driver = new IOSDriver<IOSElement>(new URL("http://" + getProperty("accessUser") + ":" + getProperty("accessKey") + "@hub-cloud.browserstack.com/wd/hub"), getIOSCaps());
                } catch (Exception e) {
                    try {
                        driver = new IOSDriver<IOSElement>(new URL("http://" + getProperty("accessUser") + ":" + getProperty("accessKey") + "@hub-cloud.browserstack.com/wd/hub"), getIOSCaps());
                    } catch (MalformedURLException e1) {
                        System.out.println("IOS Driver is not created..!, Please check capabilitis or make sure Appium Server is running.");
                    }
                    return;
                }
                webDriver.set(driver);
            }
```
Then I have BasePo class 
```
public class BasePO {

    public BasePO() {
       loadProperties();
        initElements();
    }
 private void initElements() {

        PageFactory.initElements(new AppiumFieldDecorator(getDriver()), this);
    } 
    
    protected IOSDriver<IOSElement> getDriver() {
        return IOSDriverManager.getThreadLocalDriver();
    }
```
Every Page Ogject extend BasePO

## Link to Appium logs

<script src="https://gist.github.com/MorozDenys/437bfa5cf05f937571408930853f7a36.js"></script>

I know i`m probably making some mistakes, But what i know for sure installing appium won`t automatically create WDA folder in xcuitetest

**Comment by nguyenryan147** [comment]
Btw I previously remember WebDriverAgent being here but found out yesterday it is now
/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver`

Try to locate WebDriver Agent in node_modules instead of appium-xcuitest-driver is should be appium-webdriveragent

This is the path where I found WDA on a fresh install /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent

**Comment by ivantay2003** [comment]
I have similar issue with WDA on a clean machine recently. However , I manage to resolve it . I wrote it in this article

https://medium.com/@ivantay2003/setting-up-appium-in-os-x-ecd9e7108a9c

See Section 6 (under WDA)

**Comment by mykola-mokhnach** [comment]
Please attach the xcodebuild output from the above log. Most likely there are problem with your xcode or carthage setup.

**Comment by MorozDenys** [comment]
@nguyenryan147 
> Btw I previously remember WebDriverAgent being here:
> /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver`
Path you provided is for desctop app. I`m running from terminal 

I have desktop also and checked the path you gave me - no such a directory

**Comment by MorozDenys** [comment]
> Please attach the xcodebuild output from the above log. Most likely there are problem with your xcode or carthage setup.

@mykola-mokhnach  thing is i`m doing it in browserStack and i think there are no way to see logs from xcode
I  made helloWorld app and ran on local host but app is launching just like in browserstack 
But doesn`t return noSuchElement exception for 1st action in test

**Comment by mykola-mokhnach** [comment]
It might be a browserstack issue though if you cannot reproduce the problem locally. I would try to contact their support

**Comment by MorozDenys** [comment]
@mykola-mokhnach 
I ran on local machine with xcode logs . Can you check what is going on ? I`m sorry in advance. Probably my stupidity. I was not seeking any help 3 days, but I`m too tired now 
https://gist.github.com/MorozDenys/e7ffe60f5a41af79014568f4cd12dc14

**Comment by mykola-mokhnach** [comment]
> [Xcode] 2019-10-16 12:02:21.656976-0700 WebDriverAgentRunner-Runner[8184:120786] Enqueue Failure: Failed to get matching snapshot: Error getting main window kAXErrorServerNotFound /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgentRunner/UITestingUITests.m 38 1

It seems like xctest fails to get the snapshot of the app. In general, there is nothing we can do there from Appium side in such case since this is a problem with xctest of the app itself. You could try to change the values of `wdaEventloopIdleDelay`/`waitForQuiescence` capabilities though as a workaround. Check https://github.com/appium/appium/issues?q=is%3Aissue+wdaEventloopIdleDelay+is%3Aclosed

**Comment by MorozDenys** [comment]
> > [Xcode] 2019-10-16 12:02:21.656976-0700 WebDriverAgentRunner-Runner[8184:120786] Enqueue Failure: Failed to get matching snapshot: Error getting main window kAXErrorServerNotFound /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgentRunner/UITestingUITests.m 38 1
> 
> It seems like xctest fails to get the snapshot of the app. In general, there is nothing we can do there from Appium side in such case since this is a problem with xctest or the app itself. You could try to change the values of `wdaEventloopIdleDelay`/`waitForQuiescence` capabilities though as a workaround. Check https://github.com/appium/appium/issues?q=is%3Aissue+wdaEventloopIdleDelay+is%3Aclosed

It solved problem you mentioned. Now it`s getting snapshot and hierarchy  

I'm still facing some errors: 
```
INFO: Detected dialect: W3C
org.testng.TestNGException: 
Cannot instantiate class signUpLoginTestSuite
	at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:30)
	at org.testng.internal.InstanceCreator.instantiateUsingDefaultConstructor(InstanceCreator.java:193)
	at org.testng.internal.InstanceCreator.createInstanceUsingObjectFactory(InstanceCreator.java:113)
	at org.testng.internal.InstanceCreator.createInstance(InstanceCreator.java:79)
	at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:114)
	at org.testng.internal.ClassImpl.getInstances(ClassImpl.java:172)
	at org.testng.TestClass.getInstances(TestClass.java:102)
	at org.testng.TestClass.initTestClassesAndInstances(TestClass.java:82)
	at org.testng.TestClass.init(TestClass.java:74)
	at org.testng.TestClass.<init>(TestClass.java:39)
	at org.testng.TestRunner.initMethods(TestRunner.java:463)
	at org.testng.TestRunner.init(TestRunner.java:342)
	at org.testng.TestRunner.init(TestRunner.java:295)
	at org.testng.TestRunner.<init>(TestRunner.java:181)
	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:618)
	at org.testng.SuiteRunner.init(SuiteRunner.java:196)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:127)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1265)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1093)
	at org.testng.TestNG.runSuites(TestNG.java:1032)
	at org.testng.TestNG.run(TestNG.java:1000)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:23)
	... 23 more
Caused by: java.lang.ExceptionInInitializerError
	at io.appium.java_client.pagefactory.utils.ProxyFactory.getEnhancedProxy(ProxyFactory.java:52)
	at io.appium.java_client.pagefactory.utils.ProxyFactory.getEnhancedProxy(ProxyFactory.java:33)
	at io.appium.java_client.pagefactory.AppiumFieldDecorator.proxyForAnElement(AppiumFieldDecorator.java:217)
	at io.appium.java_client.pagefactory.AppiumFieldDecorator.access$0(AppiumFieldDecorator.java:215)
	at io.appium.java_client.pagefactory.AppiumFieldDecorator$1.proxyForLocator(AppiumFieldDecorator.java:107)
	at org.openqa.selenium.support.pagefactory.DefaultFieldDecorator.decorate(DefaultFieldDecorator.java:62)
	at io.appium.java_client.pagefactory.AppiumFieldDecorator.decorate(AppiumFieldDecorator.java:155)
	at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:113)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
	at pageObjects.BasePO.initElements(BasePO.java:27)
	at pageObjects.BasePO.<init>(BasePO.java:21)
	at pageObjects.loginPage.<init>(loginPage.java:24)
	at signUpLoginTestSuite.<init>(signUpLoginTestSuite.java:17)
	... 29 more
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassVisitor.<init>(ClassVisitor.java:75)
	at net.sf.cglib.core.DebuggingClassWriter.<init>(DebuggingClassWriter.java:49)
	at net.sf.cglib.core.DefaultGeneratorStrategy.getClassVisitor(DefaultGeneratorStrategy.java:30)
```

 I'm looking at this request in logs and something telling me that i have it wrong somewhere here : 
```
[WD Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"denys.WebDriverRunner","arguments":[],"environment":{},"eventloopIdleDelaySec":3,"shouldWaitForQuiescence":false,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
```
shouldUseTestManager... i set it to false since i have explicit wait for every action => may it be a problem ? 
App is still launching but still no interaction

**Comment by mykola-mokhnach** [comment]
> @mykola-mokhnach Thanks a lot for your time. You are crazy productive and helpful. You manage to answer that many questions all over this thread... Super Human

![thank you](https://staffino.com/blog/wp-content/uploads/2016/09/59349318.jpg)

Your caps should be fine. The exception above must be caused by a bug in the client testing code (which has nothing to do with the server side)

**Comment by MorozDenys** [comment]
> > @mykola-mokhnach Thanks a lot for your time. You are crazy productive and helpful. You manage to answer that many questions all over this thread... Super Human
> 
> ![thank you](https://camo.githubusercontent.com/75bb613f27ed64875bdb7d769ab73859ba974640/68747470733a2f2f7374616666696e6f2e636f6d2f626c6f672f77702d636f6e74656e742f75706c6f6164732f323031362f30392f35393334393331382e6a7067)
> 
> Your caps should be fine. The exception above must be caused by a bug in the client testing code (which has nothing to do with the server side)

Strange. It did work before

**Comment by MorozDenys** [comment]
@mykola-mokhnach  Strange, it did work before
And now this line causing something . Has there been any changes in pageFactory implementation ? 

```
private void initElements() {

        PageFactory.initElements(new AppiumFieldDecorator(getDriver()), this);
    }
```

**Comment by amruth963** [comment]
I was able to over come this problem by code signing WDA runner app. In Appium 1.15.1 we can find the WDA folder at "/Applications/Appium-1.15.1.app/Contents/Resources/app/node_modules/appium-webdriveragent" try to open "WebDriverAgent.xcodeproj" in Xcode and select valid certificate for code signing and build the app. This should solve the WDA problem in APPIUM 1.15.1 and its woking for me

FYI....
My device details are as follows:
Mac OS Version: macOS Mojave, Version 10.14.6 (18G95)
Xcode Version: Version 11.1 (11A1027)
Appium Version (Both desktop and Command Line): 1.15.1 (1.15.1.20191013.2)

**Comment by MorozDenys** [comment]
@amruth963 Thank you, you response helped
Solved by opening "WevDriveAgent.xcodeproj" from `cd Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent`

Then in Xcode choose WebDriverAgentRunner => build => change bundle id from  com.WebDriverFacebook  to com.someunique  .  I`m using free dev acc 

Also in same pwd
 ``` 
mkdir -p Resources/WebDriverAgent.bundle
  ./Scripts/bootstrap.sh -d 
```
After this back in xcode i built project : ` product => build for test 
```
I don`t know what am i doing, but fixed somehow. Maybe it will help someone
