### ISSUE TITLE
Android 10: getAppState is not working because of dumpsys change

### ISSUE THREAD

**Issue by broetchenrackete36** [appium/appium#13420]
## The problem

GetAppState is not working correctly on Android 10, because the adb command to get the current/focused App has changed from Android 9.0 to 10.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.0
* Node.js version (unless using Appium.app|exe): 12.6.0
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: Android 10 (API 29)
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: cli

## Details

The command ist executed here:
https://github.com/appium/appium-android-driver/blob/363f4ce1acf5a837f272c550934fa874407197b3/lib/commands/app-management.js#L44

In Android 9 and earlier this command `dumpsys window windows` is correct, but in Android 10 it has to be changed to `dumpsys window displays`.

## Appium logs

The App `com.example.app` was running in foreground, so appState should have been 4 and not 3.

```
[HTTP] --> POST /wd/hub/session/44e9a7d6-3f95-46b5-a276-058c567f6ad3/appium/device/app_state
[HTTP] {"appId":"com.example.app"}
[debug] [W3C (44e9a7d6)] Calling AppiumDriver.queryAppState() with args: ["com.example.app","44e9a7d6-3f95-46b5-a276-058c567f6ad3"]
[AndroidDriver] Querying the state of 'com.example.app'
[debug] [ADB] Getting install status for com.example.app
[debug] [ADB] Running 'C:\Android\SDK\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys package com.example.app'
[debug] [ADB] 'com.example.app' is installed
[debug] [ADB] Getting IDs of all 'com.example.app' processes
[debug] [ADB] Running 'C:\Android\SDK\platform-tools\adb.exe -P 5037 -s emulator-5554 shell 'pgrep --help; echo $?''
[debug] [ADB] Running 'C:\Android\SDK\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pgrep -f com\\.example\\.app'
[debug] [ADB] Running 'C:\Android\SDK\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys window windows'
[debug] [W3C (44e9a7d6)] Responding to client with driver.queryAppState() result: 3
[HTTP] <-- POST /wd/hub/session/44e9a7d6-3f95-46b5-a276-058c567f6ad3/appium/device/app_state 200 334 ms - 11
[HTTP]
```

**Comment by mykola-mokhnach** [comment]
Thanks for the report.
The fix has been published to appium@beta
