### ISSUE TITLE
Safari tests on ios13.1.2 gives SO_Timeout, while ios12.4.1 works

### ISSUE THREAD

**Issue by presidenten** [appium/appium#13425]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

Updated one iphone in our device farm to ios 13.1.2. 
Now tests wont run further than navigating to url. Then it exits with SO_Timeout
`unknown error: Session [26cd9d77-9698-4a2c-a095-8ac8ef4665a7] was terminated due to SO_TIMEOUT`

Tests still work fine on all ios-devices that are left on ios 12.4.1

It is also worth mentioning that I have verified that remote web inspection works with the ios 13.1.2 device from the host mac.

## Environment

* Appium version (or git revision) that exhibits the issue:
1.15.1

* Last Appium version that did not exhibit the issue (if applicable):
n/a

* Desktop OS/version used to run Appium:
macOS 10.14.6

* Node.js version (unless using Appium.app|exe):
10.16.3

* Npm or Yarn package manager:
6.9.0

* Mobile platform/version under test:
ios13.1.2, ios12.4.1

* Real device or emulator/simulator:
real devices

* Appium CLI or Appium.app|exe:
cli

## Details

libimobiledevice and ios_webkit_debug_proxy are installed with brew with --HEAD flag.
They got reinstalled today together with appium 1.15.1, while I was trying to get the updated phone to work.

Latest commit that followed with the installs were:
- libimobiledevice:
  "60823f9idevice: properly handle partial SSL writes"

- ios_webkit_debug_proxy:
  "ba9a3f4 Merge pull request #329 from google/ios_13_support"

## Link to Appium logs

https://gist.github.com/presidenten/89119450fc92dbb7dbf89142619b7799

Note! There is both a log for ios12 (appium-log-ios13) and ios13 (appium-log-ios13) for easy compare between what works and what does not work.

Further down is also webdriver io logs when running against the different ios versions (wdio-0-0-ios12 and wdio-0-0-ios13) just in case its of interest.

## Code To Reproduce Issue [ Good To Have ]

Running the firest test in this repo but with a selenium server hosting the devices:
https://github.com/presidenten/wdio-template

**Comment by mykola-mokhnach** [comment]
Since version 1.15 Appium does not use neither iwdp nor libimobiledevice.

**Comment by mykola-mokhnach** [comment]
cc @umutuzgur

**Comment by presidenten** [comment]
@mykola-mokhnach Very nice! Just saw it in the documentation.

I tried running appium without starting the proxy first. 

Still same result though.ios12 works, SO_TIMEOUT on ios13

**Comment by umutuzgur** [comment]
@presidenten Could you try appium@beta? We added some fixes there for web tests. Apple changed some stuff with the release of iOS 13

**Comment by presidenten** [comment]
Sure, Ill try it when Im back at the office on monday. Thanks for the quick response

**Comment by presidenten** [comment]
@umutuzgur @imurchie 

Sorry for taking some time to run tests in the beta. My kid got sick, so havent been at work.

I got back now and I ran the tests with Appium 1.16.0-beta.1

Ios12 devices seem to still work fine.

Our ios13 device opens safari, navigate to the first url, then manages to snag a screenshot, but it seems it cant click links. The link gets focused, but then timeout and consecutive tests fails as well.
Webdriver io reports:
unknown error: Session [3d3476a6-b768-4b42-93d6-afafbb7bd034] was terminated due to SO_TIMEOUT

Logs from appium and wdio here:
https://gist.github.com/presidenten/d38794895b64b6cf565e1833236b6845


I also tried a test where I just jump to different urls, and that seems to work.

Finally I also tried a test where I just navigated to a page and tried to fill in a text field, that also didnt work.
So interacting in any way with pages seems to lead to SO_TIMEOUT.

**Comment by imurchie** [comment]
The most recent beta of Appium has some changes that are pertinent to this issue. Could you reinstall and try again?

**Comment by presidenten** [comment]
@imurchie @umutuzgur 
Was on vacation last week, but back now and reinstalled appium@beta today around 11 CET (still seems to be version 1.16.0-beta.1, but code seems to be different).

Anyways. Safari tests now work properly again. <3

Verified on real devices running IOS versions:
- 12.4.1
- 13.1.2
- 13.2

Thank you for the quick fix!
