### ISSUE TITLE
Page source does not show android.widget.Spinner dropdown values

### ISSUE THREAD

**Issue by Devapal** [appium/appium#13427]
Hi,

I have an android.widget.Spinner control that has dropdown values. I see the android.widget.Spinner but I do not see the dropdown values in the page source.
Application has dropdown values but Appium inspector fails to inspect them.

I tried to refresh the page but still not able to inspect them through inspector.
Its a hybrid app but I only get Native context handle so switching to web context is not available.  Any advise ?
Please see attached screenshot or Appium server logs for reference.

Device Model: Samsung Tab
Appium Version: 1.15
UIAutomator2
Hybrid App: Cordova
[dd_appium-server-logs.txt](https://github.com/appium/appium/files/3731654/dd_appium-server-logs.txt)
<img width="1423" alt="Screen Shot 2019-10-09 at 6 15 53 PM" src="https://user-images.githubusercontent.com/35826618/66873653-9793d600-ef6e-11e9-9d43-3010d856af45.png">

**Comment by mykola-mokhnach** [comment]
Please switch to web view in order to inspect hybrid apps. In native mode Appium shows what the application returns to the accessibility layer and there is no way to change that from our side.

**Comment by Devapal** [comment]
When I get context handles, I see only Native. 
Is there something that needs to be enabled from code in order to see "web view" context  on a hybrid app ?

**Comment by mykola-mokhnach** [comment]
http://appium.io/docs/en/writing-running-appium/web/hybrid/

**Comment by Devapal** [comment]
Thanks, I am going to try to enable the Webview on my hybrid app and update here if the Webview works.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
