### ISSUE TITLE
activateApp(), LaunchApp() resets the whole app every time - iOS 13.x only

### ISSUE THREAD

**Issue by jagsme** [appium/appium#13421]
## The problem

In iOS 13 - > every time I perform activateApp() or launchApp(), the app resets like it is launching for the first time.

## Environment

* Appium version : 1.15
* Desktop OS/version used to run Appium: OSX Mojave
* Node.js version (unless using Appium.app|exe): 8.9.4
* Npm or Yarn package manager: 8.9.4
* Mobile platform/version under test: iOS 13
* Appium CLI or Appium.app|exe: 1.15

## Link to Appium logs

I have set noReset=True, but still the app is reset

2019-10-14 12:35:03:826 [XCUITest] App is present
2019-10-14 12:35:03:827 [BaseDriver] Event 'resetStarted' logged at 1571056503826 (16:35:03 GMT+0400 (+04))

## Code To Reproduce Issue [ Good To Have ]

1. iOS 13.x
2. Xcode 11
3. Appium 1.15
4. Register an app
5. In a separate test suite -> call launchApp() and perform some profile actions 

Issue:
in Step 5. the app opens registration page

**Comment by mykola-mokhnach** [comment]
Please provide full server logs from the new and the old versions for comparison

**Comment by jagsme** [comment]
pfa logs

iOS 13 logs 
[iOS13_Log.txt](https://github.com/appium/appium/files/3725359/iOS13_Log.txt)

iOS 12 logs 
[iOS12.txt](https://github.com/appium/appium/files/3725361/iOS12.txt)

**Comment by mykola-mokhnach** [comment]
launchApp internally does the same as restarting the driver, so the described behaviour is expected. Although, I don't observe any calls to activeApp in the attached log

**Comment by jagsme** [comment]
@mykola-mokhnach here are the logs with launchApp() calls 

[ios13.txt](https://github.com/appium/appium/files/3727447/ios13.txt)

**Comment by mykola-mokhnach** [comment]
So what is the problem with the recent log? 

> 2019-10-15 05:03:49:391 [HTTP] --> POST /wd/hub/session/d1c16036-839c-4fab-ba8d-105e9286062a/execute/sync
> 2019-10-15 05:03:49:392 [HTTP] {"script":"mobile: launchApp","args":[{"bundleId":"com.xxxxxx.xxxxxxChatiOS"}]}
> 2019-10-15 05:03:49:392 [W3C (d1c16036)] Calling AppiumDriver.execute() with args: ["mobile: launchApp",[{"bundleId":"com.xxxxxx.xxxxxxChatiOS"}],"d1c16036-839c-4fab-ba8d-105e9286062a"]
> 2019-10-15 05:03:49:392 [XCUITest] Executing command 'execute'
> 2019-10-15 05:03:49:396 [WD Proxy] Proxying [POST /wda/apps/launch] to [POST http://localhost:8100/session/063E9964-F012-4229-91ED-92F2178BCA9F/wda/apps/launch] with body: {"bundleId":"com.xxxxxx.xxxxxxChatiOS"}
> 2019-10-15 05:03:50:796 [WD Proxy] Got response with status 200: {"value":null,"sessionId":"063E9964-F012-4229-91ED-92F2178BCA9F"}
> 2019-10-15 05:03:50:796 [W3C (d1c16036)] Responding to client with driver.execute() result: null
> 2019-10-15 05:03:50:797 [HTTP] <-- POST /wd/hub/session/d1c16036-839c-4fab-ba8d-105e9286062a/execute/sync 200 1405 ms - 14
> 2019-10-15 05:03:50:797 [HTTP]

I don't observe any traces of app reset here

**Comment by nguyenryan147** [comment]
"I have set noReset=False, but still the app is reset"

I don't know if I'm reading this right and I'm still very new with using Appium, but I think that should be set to True.

**Comment by jagsme** [comment]
@nguyenryan147 it is set as noReset=True.

@mykola-mokhnach I don't know what is going wrong. But the exact same environment works fine with iOS 12.x and below. As well as Android all OS.

The only thing I am not getting past is on iOS 13.x

**Comment by owlsnakes** [comment]
I've found the following to "work" as a workaround:
```
driver.quit() # I've found you can't change desired_capabilities unless you quit the driver first
driver.desired_capabilities["noReset"] = True # set to true so the following command doesn't reset the app
driver.start_session(driver.desired_capabilities) # start a session
```

**Comment by kulasangeles** [comment]
Hi @mykola-mokhnach do we have an update on this issue? I am getting this for iOS 14 simulators as well.

**Comment by dgimb89** [comment]
Same issue here: `activateApp`, `launchApp` and `reset` apparently ignore `noReset` (which is set to true) and force quit the tested app on iOS 13.6 using Appium 1.17.1.

We did not experience this issue on iOS 13.1.3 using Appium 1.9.1.

[appiumlog.txt](https://github.com/appium/appium/files/5202453/appiumlog.txt)

**Comment by dgimb89** [comment]
I tested some more iOS versions available on Device Farm which might help tracking down the issue.

Appium version: 1.17.1

`noReset=true` working as expected:
- iOS 12.4.1
- iOS 13.1.3
- iOS 13.3.1

`noReset=true` **not** working as expected:
- iOS 13.6

**Comment by jagsme** [comment]
any updates or workaround for the above issue?

**Comment by owlsnakes** [comment]
@jagsme I just use this:

```python3
driver.terminate_app(bundle_id)
driver.activate_app(bundle_id)
```

with the following capabilities:
```json
{
    "fullReset": true,
    "resetOnSessionStartOnly":true
}
```

@jagsme

**Comment by jagsme** [comment]
Thanks @owlsnakes trying it now

**Comment by jagsme** [comment]
@owlsnakes I tried with {
    "fullReset": true,
    "resetOnSessionStartOnly":true
}

still no success, it seems to reset on iOSDriver initialization

**Comment by owlsnakes** [comment]
@jagsme so it should reset on the driver initialization, but only at the very start. Is it resetting every time?

**Comment by jagsme** [comment]
Yes it resets every time

**Comment by jagsme** [comment]
issue reproducible on iOS 13.4.1

**Comment by owlsnakes** [comment]
> Yes it resets every time

so this line
```python3
driver.activate_app(bundle_id)
```

is causing the app to reset, even with those desired capabilities? that doesn't match what I was seeing before.
under the hood, XCUITest will reinstall/reset the app, depending on if it is backgrounded/foregrounded/terminated when the call is made.

I'd be curious if `terminate_app` is working properly.

I wish I could be more help, my team ditched appium in favor of XCUITest because of issues like this.

Here are some of my old notes WRT the workaround I suggested:

----

Desired caps:
```
"fullReset": True
"resetOnSessionStartOnly": True
```

to close and restart the app without reinstalling:
```python3
driver.terminate_app("com.hiroad.mobile.ios")
driver.activate_app("com.hiroad.mobile.ios")
```

to reinstall the app
```python3
driver.reset()
```
to background indefinitely
```python3
driver.background_app(-1) 
```
to background for given time, and bring back pass a positive integer
```python3
driver.background_app(5) # background for 5 seconds, the foreground
```
Other notes:
```python3
driver.close_app() # this will end the driver session, seems to the same as driver.quit()
driver.launch_app() # this will re install the app, and then launch it. I think its a wrapper for the XUIApplication method.
```

**Comment by jagsme** [comment]
@owlsnakes 

Thanks a lot for your help, this issue is resolved. Tried a workaround and bunch of other things. 
1. Changed xcode - 10.2.1
2. Added 13.x support files
3. Perform appium-doctor --ios and install all **optional dependencies** as well

resets only first time and then runs smoothly

**Comment by koralaa** [comment]
I have the same issue with Android. driver.launchApp() and driver.activateApp("package name")  both resets the app to home page. Any solution?

**Comment by KazuCocoa** [comment]
Our appium/WDA's final endpoint to launch an app is https://developer.apple.com/documentation/xctest/xcuiapplication/1500467-launch?language=objc
So, only Apple knows how they handle app internally. According to the documentation, they addresses as:

> If the application is already running, this call will terminate the existing instance, to ensure a clean launch state for the newly launched instance.

afaik, it could depend on Xcode/iOS versions though....
One possible idea is you can pass launch arguments/environments like https://github.com/appium/appium-xcuitest-driver#mobile-launchapp and your app handle some states internally.

**Comment by nanoscopic** [comment]
Wouldn't it be good to add a specific call to simply check if the app is running?

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
