### ISSUE TITLE
setWindow will reconnect application and set appIdKey/pageIdKey to null

### ISSUE THREAD

**Issue by bswhb** [appium/appium#13424]
## The problem

We're testing web site over iOS 13 + Safari , on a real device iPhone XR, based on remote web driver. When we called Selenium command switchToWindow (aka AppiumDriver.setWindow()), we found it will try to re-connect the application and then set the appIdKey and pageIdKey to null. Thus, the internal error will be thrown out as below:
```
Encountered internal error running command: Error: appIdKey,pageIdKey
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: MacOS 10.15
* Node.js version (unless using Appium.app|exe): 12.11.1
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: iPhone XR with iOS 13
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Details

* According to the logs below, firstly we issue a switch to window command, we could see the log `[debug] [RemoteDebugger] Connected to application` which will reset the appIdKey and pageIdKey.
* When the next command switch to default content was trigger, an internal error would be thrown out because the two keys are null.

## Link to Appium logs

[Logs](https://gist.github.com/bswhb/e177fdb59b8f4bc1f57859396def1d24)

**Comment by mykola-mokhnach** [comment]
Does this work with appium@beta?

**Comment by bswhb** [comment]
Hi @mykola-mokhnach , beta works, thanks for your information. May I know when it will be released officially? Thanks a lot!

**Comment by mykola-mokhnach** [comment]
Unfortunately we don't have any fixed dates yet.
