### ISSUE TITLE
Set Android Location mode accuracy to "high"

### ISSUE THREAD

**Issue by Johanneke** [appium/appium#13436]
## The problem

Our app needs location services enabled, and location mode set to "high accuracy" (see screenshot). There currently seems no way to achieve this at runtime through the Appium Java client. On the AndroidDriver there is a method toggleLocationServices, but this only enables/disables the location services. It doesn't change the accuracy setting.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15
* Desktop OS/version used to run Appium: MacOS Mojave (10.14.6)
* Node.js version (unless using Appium.app|exe): 10.15.0
* Npm or Yarn package manager: 6.4.1
* Mobile platform/version under test: Android 21+ (and iOS 11+ but no issue there)
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: Appium Java client

## Details

This is the popup we get after successfully enabling location services:
![Screenshot 2019-10-16 at 13 52 19](https://user-images.githubusercontent.com/5793090/66920290-42fe6280-f023-11e9-98ae-1ad551f17c88.png)

This is the setting we need to set to "high accuracy":
<img width="374" alt="Screenshot 2019-10-16 at 14 43 23" src="https://user-images.githubusercontent.com/5793090/66920348-60cbc780-f023-11e9-950c-18c60f7d12ae.png">

**Comment by mykola-mokhnach** [comment]
Unfortunately Android API does not allow to change this setting via adb due to security limitations. If you know a way to implement such functionality then please let us know
