### ISSUE TITLE
切换webview点击元素超时

### ISSUE THREAD

**Issue by fengzhen2009** [appium/appium#13433]
## The problem
切换webview点击元素超时

## Environment

* Appium version (or git revision) that exhibits the issue:1.15.0-1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:win10
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Link to Appium logs

 Webview version: 'Chrome/74.0.3729.136'
[WD Proxy] Got response with status 200: {"sessionId":"8fe3af459c91c81e2bc7700c4896162d","status":0,"value":{"acceptInsecureCerts":false,"acceptSslCerts":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"browserName":"chrome","chrome":{"chromedriverVersion":"74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29})"},"cssSelectorsEnabled":true,"databaseEnabled":false,"goog:chromeOptions":{"debuggerAddress":"localhost:54095"},"handlesAlerts":true,"hasTouchScreen":true,"javascriptEnabled":true,"locationContextEnabled":true,"mobileEmulationEnabled":false,"nativeEvents":true,"pageLoadStrategy":"normal","platform":"ANDROID","proxy":{},"rotatable":false,"setWindowRect":false,"strictFileInteractability":false,"takesHeapSnapshot":true,"takesScreenshot":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unexpectedAlertBehaviour":"ignore","version":"74.0.3729.136","webStorageEnabled":true}}
[WD Proxy] Determined the downstream protocol as 'MJSONWP'
[Chromedriver] Changed state to 'online'
[W3C (bfef1e74)] Responding to client with driver.setContext() result: null
[HTTP] <-- POST /wd/hub/session/bfef1e74-c31e-42f5-9bae-7b035176347e/context 200 4912 ms - 14
[HTTP] 
[HTTP] --> POST /wd/hub/session/bfef1e74-c31e-42f5-9bae-7b035176347e/elements
[HTTP] {"using":"xpath","value":"//*[contains(@text,\"登录\")]"}
[W3C (bfef1e74)] Driver proxy active, passing request on via HTTP proxy
[WD Proxy] Matched '/wd/hub/session/bfef1e74-c31e-42f5-9bae-7b035176347e/elements' to command name 'findElements'
[WD Proxy] Proxying [POST /wd/hub/session/bfef1e74-c31e-42f5-9bae-7b035176347e/elements] to [POST http://127.0.0.1:8001/wd/hub/session/8fe3af459c91c81e2bc7700c4896162d/elements] with body: {"using":"xpath","value":"//*[contains(@text,\"登录\")]"}
[WD Proxy] Got response with status 200: {"sessionId":"8fe3af459c91c81e2bc7700c4896162d","status":0,"value":[]}
[WD Proxy] Replacing sessionId 8fe3af459c91c81e2bc7700c4896162d with bfef1e74-c31e-42f5-9bae-7b035176347e
[HTTP] <-- POST /wd/hub/session/bfef1e74-c31e-42f5-9bae-7b035176347e/elements 200 90 ms - 63
[HTTP] 
[HTTP] --> GET /wd/hub/session/bfef1e74-c31e-42f5-9bae-7b035176347e/screenshot
[HTTP] {}
[W3C (bfef1e74)] Driver proxy active, passing request on via HTTP proxy
[WD Proxy] Matched '/wd/hub/session/bfef1e74-c31e-42f5-9bae-7b035176347e/screenshot' to command name 'getScreenshot'
[WD Proxy] Proxying [GET /wd/hub/session/bfef1e74-c31e-42f5-9bae-7b035176347e/screenshot] to [GET http://127.0.0.1:8001/wd/hub/session/8fe3af459c91c81e2bc7700c4896162d/screenshot] with body: {}
[WD Proxy] Got response with status 200: {"sessionId":"8fe3af459c91c81e2bc7700c4896162d","status":21,"value":{"message":"timeout: Timed out receiving message from renderer: 10.000\n  (Session info: chrome=74.0.3729.136)\n  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.17763 x86_64)"}}

**Comment by mykola-mokhnach** [comment]
> [WD Proxy] Got response with status 200: {"sessionId":"8fe3af459c91c81e2bc7700c4896162d","status":21,"value":{"message":"timeout: Timed out receiving message from renderer: 10.000\n (Session info: chrome=74.0.3729.136)\n (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.17763 x86_64)"}}

This is the error, which is coming from chromedriver itself. Please report it to their bugtracker.

You could also set the `nativeWebScreenshot` capability to true in order to get screenshots from UIAutomation rather than from chromedriver as a workaround

**Comment by fengzhen2009** [comment]
我想问一下，appium支持判断手机的webview驱动版本吗？然后能否自动选择本地对应的驱动？

**Comment by mykola-mokhnach** [comment]
![i-hear-you-but-still-dont-understand](https://user-images.githubusercontent.com/7767781/66903606-14708f80-f003-11e9-9bd0-28c93bb16767.jpg)

**Comment by fengzhen2009** [comment]
I want to ask the  appium does support judging the WebView driver version of mobile phones? Can the local driver be selected automatically?

**Comment by mykola-mokhnach** [comment]
I still cannot understand the original question. http://appium.io/docs/en/writing-running-appium/web/hybrid/ contains the documentation on how to setup testing of hybrid apps.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
