### ISSUE TITLE
safariConsole stays empty

### ISSUE THREAD

**Issue by SebastianSolidwork** [appium/appium#13431]
## The problem

I'm trying to get the safariConsole but it stays always empty. I'm trying it with Safari itself and a hyprid app with a webview.
Accordingly to this article i prototyped the implementation: https://appiumpro.com/editions/37

I’m having C# with Nunit, Appium.WebDriver is 3.0.0.2

    [Test]
    public void testLogging()
    {
        driver.Url = ("https://appiumpro.com/test");
        driver.ExecuteScript("window.onerror=console.error.bind(console)");
        driver.ExecuteScript("console.log('foo.');");
        driver.ExecuteScript("console.warn('bar?');");
        driver.FindElementById("jsErrLink").Click();

        foreach (var line in driver.Manage().Logs.GetLog("safariConsole"))
        {
            Console.WriteLine(line.ToString());
        };
    }

## Environment

* Appium version (or git revision) that exhibits the issue: 15.0, 14.0
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: macOS 10.14.6
* Mobile platform/version under test: Simulator = 12.2, 13.0 / Device = 12.4
* Real device or emulator/simulator: both
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/SebastianSolidwork/198984844b0596a0a20b9acb3d200258

## Code To Reproduce Issue [ Good To Have ]

    [Test]
    public void testLogging()
    {
        driver.Url = ("https://appiumpro.com/test");
        driver.ExecuteScript("window.onerror=console.error.bind(console)");
        driver.ExecuteScript("console.log('foo.');");
        driver.ExecuteScript("console.warn('bar?');");
        driver.FindElementById("jsErrLink").Click();

        foreach (var line in driver.Manage().Logs.GetLog("safariConsole"))
        {
            Console.WriteLine(line.ToString());
        };
    }

**Comment by imurchie** [comment]
I can reproduce this. Looking into it.
