### ISSUE TITLE
Can appium start service instead of activity?

### ISSUE THREAD

**Issue by zhengyu88** [appium/appium#13437]
## The problem
I am trying to use appium to test one background application which has no interface on android.
I find the following command works:

    adb shell am startservice -n com.abc.xxx/com.abc.xxx.Service

However, via appium, it tries this command:

    adb shell am start -W -n com.abc.xxx/com.abc.xxx.Service -S

This command throws error:

    Error type 3
    Error: Activity class {com.abc.xxx/com.abc.xxx.Service} does not exist

How to make appium use the first command or is there any way to work this around?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.0-1
* Desktop OS/version used to run Appium: Windows 10
* ADB version: 1.0.41

## Link to Appium logs

    [UiAutomator2] Starting 'com.abc.xxx/com.abc.xxx.Service and waiting for 'com.abc.xxx/com.abc.xxx.Service'
    [ADB] Running 'E:\Android\SDK\platform-tools\adb.exe -P 5037 -s 111 shell am start -W -n com.abc.xxx/com.abc.xxx.Service -S'
    [ADB] We tried to start an activity that doesn't exist, retrying with '.com.abc.xxx.Service' activity name
    [ADB] Running 'E:\Android\SDK\platform-tools\adb.exe -P 5037 -s 111 shell am start -W -n com.abc.xxx/.com.abc.xxx.Service -S'
    [UiAutomator2] Deleting UiAutomator2 session
    [UiAutomator2] Deleting UiAutomator2 server session
    [WD Proxy] Matched '/' to command name 'deleteSession'
    [WD Proxy] Proxying [DELETE /] to [DELETE http://localhost:8271/wd/hub/session/2218b00f-4b2d-42fa-ba41-bc205960cd80] with no body
    [WD Proxy] Got response with status 200: {"sessionId":"2218b00f-4b2d-42fa-ba41-bc205960cd80","value":null}
    [ADB] Running 'E:\Android\SDK\platform-tools\adb.exe -P 5037 -s 111 shell am force-stop com.abc.xxx'
    [Instrumentation] .
    [Instrumentation] Time: 5.029
    [Instrumentation] 
    [Instrumentation] OK (1 test)
    [Instrumentation] The process has exited with code 0
    [Logcat] Stopping logcat capture
    [ADB] Removing forwarded port socket connection: 8271 
    [ADB] Running 'E:\Android\SDK\platform-tools\adb.exe -P 5037 -s 111 forward --remove tcp\:8271'
    [BaseDriver] Event 'newSessionStarted' logged at 1571221550333 (18:25:50 GMT+0800 (中国标准时间))
    [W3C] Encountered internal error running command: Error: Cannot start the 'com.abc.xxx' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Cannot start the 'com.abc.xxx' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Activity name '.com.abc.xxx.Service' used to start the app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity
    [W3C]     at ADB.startApp (C:\Users\jzy\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-android-driver\node_modules\appium-adb\lib\tools\apk-utils.js:153:11)
    [HTTP] <-- POST /wd/hub/session 500 24113 ms - 1808

**Comment by mykola-mokhnach** [comment]
Unfortunately such scenario is currently impossible. As a workaround one could start UiAutomator2 without an app (this feature has been added since v. 1.15) and then start the service using `mobile: shell` helper
