### ISSUE TITLE
can not find validate.js@0.13.1

### ISSUE THREAD

**Issue by liftting** [appium/appium#13430]
1, npm install -g appium
error info:
npm ERR! code ETARGET
npm ERR! notarget No matching version found for validate.js@0.13.1
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'appium'
npm ERR! notarget
2, npm install -g validate.js
npm install -g validate.js
+ validate.js@0.13.0
updated 1 package in 0.337s

where validate.js@0.13.1?

**Comment by mykola-mokhnach** [comment]
Please try to uninstall appium completely first to make sure there are no leftovers from previous installations. Btw, do you use a custom repository for npm packages or the global one?
