### ISSUE TITLE
Is Element Selected - "Unhandled endpoint" for iOS

### ISSUE THREAD

**Issue by lewie9021** [appium/appium#13441]
## The problem

Unable to request the selected status of an element on iOS. When I make the request to `/session/:sessionId/element/:elementId/selected`, I get a response status of 9 with a "unhandled endpoint" message. The [docs state that this has been supported since 1.6.0](http://appium.io/docs/en/commands/element/attributes/selected/)?

Testing this on Android with a switch element appears to work, though it looks like it focuses on the [accessibility state](https://facebook.github.io/react-native/docs/accessibility#accessibilitystates-ios-android) (this is in a React Native app - I'm not exactly sure what this corresponds to in Android) instead of its value. Is this intended behaviour?

## Environment

* Appium version (or git revision) that exhibits the issue: `1.15.1`
* Desktop OS/version used to run Appium: `macOS Mojave 10.14.6`
* Node.js version: `10.13.0`
* Yarn package manager: `1.19.1`
* Mobile platform/version under test: `iOS 12.4 (via Xcode 10.3)`
* Real device or emulator/simulator: `Simulator`
* Appium CLI or Appium.app|exe: `Appium CLI`

## Link to Appium logs

https://gist.github.com/lewie9021/4e3d1a2ac60ea721c885d8ecc1eb7926

To provide some context, the logs above are a refection of the following steps:
- Launch simulator session.
- Wait for "menu-screen" to be visible.
- Tap "list-item-form-screen".
- Wait for "form-screen" to be visible.
- Retrieve selected status of "switch".
- Close session.

**Comment by mykola-mokhnach** [comment]
Yes, the described behaviour is expected. The native context does not have a handler for `/selected` endpoint. You could use `/value` endpoint to get the state of an element (it would return `true` or `false`) or switch to web view context (recommended).

**Comment by mykola-mokhnach** [comment]
> Is this a limitation of XCUITest? I noticed there's a selected attribute for Android (UiAutomator2), but not for iOS?

In theory it should not be a big problem to implement such endpoint

**Comment by mykola-mokhnach** [comment]
The feature has been published to appium@beta

**Comment by maros24** [comment]
@mykola-mokhnach I have the same problem. How can I change to /value endpoint?
