### ISSUE TITLE
Chrome Opening up Home Page on launch

### ISSUE THREAD

**Issue by MarkSpencerTan** [appium/appium#13446]
## The problem

Whenever I run tests on multiple android devices in parallel (20-30 devices), there are a few devices that would open up Chrome with an initialUrl of "data:," and some launch their default Home page.

I was wondering why the second case is happening for some of the devices since we do NOT want the devices to start launching the default home page before the start of the test.

Is there a way we can force this "data:," initial url so that the default home page never comes up similar to iOS's initialUrl capability?

I've already tried setting "--homepage=data:," or "--incognito" chrome options capabilities to try and work around this but it doesn't seem to work on mobile devices, only on computer browsers with selenium

Also what I've noticed is that I don't see the issue if I only run it on one device. I'm wondering if parallel devices could be a cause of this issue.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Desktop OS/version used to run Appium: Windows/Mac OS
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: Cli
* Chrome Version: v77

**Comment by mykola-mokhnach** [comment]
I would rather ask which preference/capability is responsible for that at Chromedriver forum. Appium simply acts as a proxy between CD and the client code and does not add any new features.
