### ISSUE TITLE
I can't test for ios13 with appium real device and simulator.

### ISSUE THREAD

**Issue by a25max** [appium/appium#13449]
## The problem

I want to test for ios13 with appium. But I can't this.
I tried use simulator and real device. But I can't that.

I confirmed install WebDriverAgent and test app. 

## Environment

* Appium version (or git revision) that exhibits the issue: 10.4.1(appium-lib)
* Last Appium version that did not exhibit the issue (if applicable): 10.3.1
* Desktop OS/version used to run Appium: Mac OS 10.14.4（18E226）
* Node.js version (unless using Appium.app|exe): 10.15.3
* Npm or Yarn package manager: 6.4.1
* Mobile platform/version under test: ios13.1
* Real device or emulator/simulator: both
* Appium CLI or Appium.app|exe: CLI
* Xcode 11.1

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/a25max/cc63cb9b5b36eb4cd6543e8f4878db4b

**Comment by mykola-mokhnach** [comment]
> `10.4.1(appium-lib)`

I cannot say nothing about this product
iOS13 support has been added to Appium since v. 1.15

**Comment by a25max** [comment]
@mykola-mokhnach Sorry, this pull-request is closed.
