### ISSUE TITLE
Could not install app: 'Unexpected data: {"Error":"PackageInspectionFailed","ErrorDescription":"Failed to load Info.plist from bundle 

### ISSUE THREAD

**Issue by meruga92** [appium/appium#13447]
Unable to install iOS app 

When i try to run appium script it is throwing error when installing the app on real device and it dint appeared until today and last time it ran couple of days back it worked fine for the same version

## Environment

* Appium version : 1.15.0 or 1.15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS
* Node.js version (unless using Appium.app|exe): 10.16.3
* Npm or Yarn package manager: 
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real device version 1.13.2
* Appium CLI:

## Link to Appium logs

https://gist.github.com/meruga92/522c7b1f340901301d58e55ea0ccbbd1

My Capabilities:
  capabilities: [{
    platformVersion: '13.0',
    deviceName: 'iPhone X',
    app: appPath,
    platformName: 'iOS',
    useNewWDA: true,
    xcodeOrgId: 'XXXXXXX',
    xcodeSigningId: 'iPhone Developer',
    updatedWDABundleId: 'com.nm.nm.ios',
    automationName: "XCUITest",
    udid: '00008020-0013759E2261002E',
  }],

**Comment by mykola-mokhnach** [comment]
It looks like the application package is broken. Have you tried to install it manually?

**Comment by meruga92** [comment]
It works fine when I install it through xcode or by using ios-deploy command it works fine

Application is installed correctly and works fine

**Comment by wbulba** [comment]
have the same error after upgrade appium to 1.15.1

**Comment by meruga92** [comment]
Hey @mykola-mokhnach the issue got resolved after dev pushed some changes.
Closing this issue

**Comment by pacchan** [comment]
@meruga92 
I have the same issue, Dev pushed some changes?

**Comment by ahmad-sulehari** [comment]
The same issue is randomly happening with iOS 15.1, Xcode13 and appium 1.22.0. After restarting appium the app gets installed successfully. And not just happing with one device this issue has been noted regularly on more than 10 different iPhones with OS 15 and two iPads. other forms of error include applicationVerificationFailed with message could not install path_to_.app
