### ISSUE TITLE
Got Error when starting session on Appium

### ISSUE THREAD

**Issue by narendhb** [appium/appium#13442]
## The problem

I got this error massage when i try to start session on Appium 1.15.0-1

> An unknown server-side error occurred while processing the command. Original error: Could not find 'adb.exe' in ["C:\Users\ROG\AppData\Local\Android\Sdk\platform-tools\platform-tools\adb.exe","C:\Users\ROG\AppData\Local\Android\Sdk\platform-tools\emulator\adb.exe","C:\Users\ROG\AppData\Local\Android\Sdk\platform-tools\tools\adb.exe","C:\Users\ROG\AppData\Local\Android\Sdk\platform-tools\tools\bin\adb.exe"]. Do you have Android Build Tools installed at 'C:\Users\ROG\AppData\Local\Android\Sdk\platform-tools'?

![image](https://user-images.githubusercontent.com/15611413/66989301-4dd1f980-f0ee-11e9-8eab-ee18d2a01a7c.png)

![image](https://user-images.githubusercontent.com/15611413/66989323-5b877f00-f0ee-11e9-8d96-fd047834b415.png)

Already find on Google the same problem but still can't fix my problem, thankyou

**Comment by mykola-mokhnach** [comment]
Make sure adb.exe is available in one of folders, which are included into PATH env variable passed to Appium process. Check https://github.com/appium/java-client/blob/master/docs/environment.md for more details.

**Comment by narendhb** [comment]
> Make sure adb.exe is available in one of folders, which are included into PATH env variable passed to Appium process. Check https://github.com/appium/java-client/blob/master/docs/environment.md for more details.

adb.exe already in one folders, i attach the picture of that in my post. and the PATH alrady passed to Appium process

**Comment by mykola-mokhnach** [comment]
Did you read the tutorial above? The fact that PATH is set to the correct value in system settings does not necessarily mean that Appium process gets the same value.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by narendhb** [comment]
> Did you read the tutorial above? The fact that PATH is set to the correct value in system settings does not necessarily mean that Appium process gets the same value.

Fixed, thankyou
