### ISSUE TITLE
W3C capabilities for real device is not recognized by appium

### ISSUE THREAD

**Issue by alessandronoceraspx** [appium/appium#13445]
## The problem

Impossible to set w3c to false inside appium capabilities for real device used on test object

## Environment

* Appium version (or git revision) that exhibits the issue: **1.5.0 and 1.5.1**
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: **Windows 10 x64**
* Node.js version (unless using Appium.app|exe): **v10.16.3**
* Npm or Yarn package manager: **6.9.0**
* Mobile platform/version under test: **android 8.0 and 9.0**
* Real device or emulator/simulator: **samsung galaxy s8**
* Appium CLI or Appium.app|exe: **provided from test object**

## Details

I'm using webdriverIO v5.15.1 (js language of course) in order to run spec files and use Jasmine to have assertions. Reporter is Allure. The aut is hybrid app, use chrome (>75) as webview. Automation is fine but when the pipeline ends and result appear, the error message is the next:

`Error: unknown command: Cannot call non W3C standard command while in W3C mode`

So I thought to find on google if other peoples has verified this issue but I've found that the only possible solution is set the w3c key to false inside appium caps, but I don't find anything releated to appium with chrome automation.  Seems that the error is releated to json wire protocol used by appium. 

The only little thing that I've founded also is to set the `chromedriverArgs` inside the capabilities but on the official appium site I haven't found nothing.

If you need other information about my platform, please tell me. 

Can anyone help me to resolve this? The reporter in this way is unusable.

Thanks a lot, I'm searching and trying again in meantime.

Alex

**Comment by MarkSpencerTan** [comment]
@alessandronoceraspx I fixed this issue by setting chromeOptions capability to this:

desired_capabilities["chromeOptions"] = {"w3c": False}

**Comment by KazuCocoa** [comment]
Yes, `chromeOptions` is the capability to send options to the chromedriver.
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md

Please ask test object if they require another method to pass chrome options.

**Comment by alessandronoceraspx** [comment]
> @alessandronoceraspx I fixed this issue by setting chromeOptions capability to this:
> 
> desired_capabilities["chromeOptions"] = {"w3c": False}

Thank you Mark, I've seen that but to pass the chromeOptions as caps with json file (I've created dynamic core in order to build my device capabilities to have a mutiple run with one command) I only found (in javascript, my framework is composed by nodeJS and blabla) this below command:

in example:
`chromeOptions: {args: ['--disable-popup-blocking']`

So, I think that the command should be like:
`chromeOptions: {args: ['--disable-w3c']`

but my sensation tell me that don't work. Otherwise the method to pass args is different? 

Thanks!

**Comment by alessandronoceraspx** [comment]
Hi all, little update from my side. I've added to my device caps this lines:

```
samsungGalaxyS8_Public: {
      ...
      'goog:chromeOptions': {
        w3c: false,
      }
    },
```

Now, inside the spec reporter, the assert explanation is shown correctly. I have updated to the all available versions of packages but I don't know if this situation is a "case" otherwise the caps really fix the w3c issue (or the new updated packages fix it).

Anyway, I'm still on testing from pipeline and if I have other news, I'll be able to share with all you.

Meantime, if anyone has some new "tricks" or some info to fix this w3c issue, please share. Thank you!

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
