### ISSUE TITLE
ChromeDriver not working for chrome browser version 77.

### ISSUE THREAD

**Issue by afreen07** [appium/appium#13456]
I am trying to run the scripts on Android device, but I am not able to launch chrome browser, and getting following error on real device.

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: No Chromedriver found that can automate Chrome '77.0.3865'. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md for more details. You could also try to enable automated chromedrivers download server feature

## Environment
Device Name: Samsung Galaxy S7 Edge
Android version: 8.0.0
Chrome version: 77.0.3865.116
Appium Version: 1.15.1

## Link to Appium logs

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: No Chromedriver found that can automate Chrome '77.0.3865'. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md for more details. You could also try to enable automated chromedrivers download server feature

**Comment by mykola-mokhnach** [comment]
Did you read the tutorial link above?

**Comment by afreen07** [comment]
appium --chromedriver-executable /path/to/my/chromedriver setting worked for me also referred https://github.com/appium/java-client/issues/1242 for resolving this issue.Thanks for your help and sorry for late reply.
