### ISSUE TITLE
iOS 13 - Appium:  SendKeys issue with slowness

### ISSUE THREAD

**Issue by Devapal** [appium/appium#13455]
## The problem

So until iOS 12.4.1 "send keys" was working fine, the moment I updated the iPhone to iOS 13, the "sendkeys" command sends one letter for every six seconds, it is very very slow. I downgraded to 12.4.1 and send keys works normally. I tried sending keys from Appium inspector as well as from my code.

I tried with different Appium versions ( 1.1.5.1, 1.15.0, 1.12, 1.8.0 ),
I tried with different devices iPhoneX, iPhone 7
[sendkeys_appium-server-logs.txt](https://github.com/appium/appium/files/3745720/sendkeys_appium-server-logs.txt)

I have also attached Appium server logs.

Any advise ?

**Comment by rafaelcs** [comment]
Try to use `set_value("string here")`

**Comment by Devapal** [comment]
I did try with setValue and I see the same slowness.

**Comment by KazuCocoa** [comment]
Similar to https://github.com/appium/appium/issues/13444 ?

I could not replicate it on iOS 13.1.2 and 13.1.3 against some apps such as Apple Maps, our test apps.
If you have a good example to replicate it, we will be able to take a look further...

**Comment by KazuCocoa** [comment]
I found an app that had this issue. (Got it from AppStore, so not sure the source code)

A key was typed, but the completion block waited 5s.

https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Utilities/FBKeyboard.m#L34-L51

```
     _XCT_sendString:text
     maximumFrequency:frequency
     completion:^(NSError *typingError){
       didSucceed = (typingError == nil);
       innerError = typingError;
       completion();
     }];
```


```
[IOSDeviceLog] Oct 19 12:04:56 kazu DTServiceHub(DVTInstrumentsFoundation)[344] <Notice>: Heartbeat
[IOSDeviceLog] Oct 19 12:04:56 kazu testmanagerd[338] <Error>: Timed out after waiting 5.0s for KeyEventComplete, event will be implicitly confirmed with no error other than this log message.
[IOSDeviceLog] Oct 19 12:04:56 kazu testmanagerd[338] <Notice>: Registering for user testing event KeyEventComplete
[IOSDeviceLog] Oct 19 12:04:56 kazu testmanagerd[338] <Notice>: Key event '<private>' sent.
[IOSDeviceLog] Oct 19 12:04:56 kazu testmanagerd[338] <Notice>: Waiting up to 5.0s for KeyEventComplete to confirm Synthesize unicode event for 'a'.
[IOSDeviceLog] Oct 19 12:04:56 kazu DocuSignIt-v2(CoreFoundation)[436] <Notice>: -[UIThreadSafeNode _axResetFKAFocusToFirstResponder]: unrecognized selector sent to instance 0x2833cc680
```

**Comment by KazuCocoa** [comment]
The text field was inside `XCUIElementTypeWebView`.

I implemented a test case on pure XCUITest like `app.textFields.element(boundBy: 1).typeText("kazu")`, but it did not work. Appium was able to type as `send_keys` with delay.
Only typing keyboard directly worked without delay on both XCUITest and Appium. 

It meant:

- appium
```
find_element(:name, 'k').click
find_element(:name, 'a').click
```

- pure xcuitest
```
app.textFields.element(boundBy: 1).tap()
app.keys["k"].tap()
app.keys["a"].tap()
```

**Comment by KazuCocoa** [comment]
@Devapal Was your target element inside webview type?

**Comment by mykola-mokhnach** [comment]
@KazuCocoa Does the standard https://developer.apple.com/documentation/xctest/xcuielement/1500968-typetext?language=objc call show the same behaviour in pure xctest?

**Comment by KazuCocoa** [comment]
Yes, I finally succeeded to do `typeText` for the element.
https://gist.github.com/KazuCocoa/e90738298d8409bb0acbf44720a44f0b

The behaviour was the same as Appium's one.
Each type took almost 5s.

**Comment by mykola-mokhnach** [comment]
Thanks.
So, yeah, Apple gives no s$%t ;)

**Comment by Devapal** [comment]
@KazuCocoa  Yes the XCUIElementTypeTextField is under  XCUIElementTypeWebView.
I have attached a screenshot of the tree hierarchy.  

Is there an apple support to reach out to regarding this issue ? 
I tried with another ionic app and it sendkeys  fine but on my app (Cordova) I face this issue.

![Screen Shot 2019-10-21 at 9 46 47 AM](https://user-images.githubusercontent.com/35826618/67215961-01d1ce00-f3e8-11e9-8ad2-eb3085301a07.png)

**Comment by Devapal** [comment]
@mykola-mokhnach  Is this specific to iOS 13 & above ?
very weird!

**Comment by Devapal** [comment]
@jlipps Looks like we reached a dead-end at this point. Any advise you could provide to deal with this issue ? This issue is blocking us from running tests on all iOS 13 & greater os versions.

**Comment by KazuCocoa** [comment]
> Is there an apple support to reach out to regarding this issue ?

Only we can do is reporting this issue to Apple, unfortunately

**Comment by Devapal** [comment]
Too bad :(
@KazuCocoa 
Do we do it here reportaproblem.apple.com or is there a support site for Appium-Apple related issues ?

**Comment by KazuCocoa** [comment]
bugreport.apple.com is @Devapal

**Comment by Devapal** [comment]
Thanks @KazuCocoa Appreciate you looking into this.

**Comment by cschabetsberger-micro-focus** [comment]
I had the same issue, that send keys took ~5 seconds per character to type. What helped in my case was to switch from UIWebView to WKWebView (UIWebView is deprecated anyway, see https://developer.apple.com/documentation/uikit/uiwebview).

**Comment by Devapal** [comment]
@cschabetsberger-micro-focus ah! I see. Appreciate the response :)
So after adding "WebKit" framework to the app class. Is there anything else you had to change from your test code before sendKeys? like switching context handles ?

**Comment by cschabetsberger-micro-focus** [comment]
@Devapal No, I just modified my hybrid app by switching from UIWebView to WKWebView. After that, the delay was gone. No change was necessary in my test code.

**Comment by Devapal** [comment]
@cschabetsberger-micro-focus Got it, thank you.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by suman-cherukuri** [comment]
Seems like maximumFrequency in 
`_XCT_sendString:maximumFrequency:completion:`
is completely ignored and simulator is taking about 6 seconds between each character.

**Comment by EstevanBR** [comment]
> UIWebView to WKWebView
possible that this is the culprit behind all this ios 13 slowness? apps with the deprecated webview are slow?

totally `out there` theory I know :)

**Comment by michaeltranlong** [comment]
I have a workaround for this issue.  The iOS clipboard can be loaded with desired string then pasted into a text field element.  Here's how I did this in Ruby.

```
def set_field(elem, value)
     # NOTE: Workaround for slow send_keys https://github.com/appium/appium/issues/13455
      elem.click # Bring up soft keyboard

      set_clipboard content: value
      sleep 1
      pos_x = elem.location.x + (elem.size.width * 0.50).to_i
      pos_y = elem.location.y + (elem.size.height * 0.50).to_i

      # NOTE: Paste directly from clipboard: https://stackoverflow.com/questions/54487973/get-clipboard-from-real-ios-device
      Appium::TouchAction.new.press(x: pos_x, y: pos_y).release.perform # Bring up iOS Paste button
      elem_paste = find_element(class: 'XCUIElementTypeMenuItem')
      elem_paste.click
end
```
