### ISSUE TITLE
Appium does not work with windows app driver 1.1

### ISSUE THREAD

**Issue by anunay1** [appium/appium#13457]
## The problem
Appium does not work with windows application driver 1.1 

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

I ran appium from command line and trying to execute the test cases using visual studio

## Environment
Windows 10 PC

* Appium version (or git revision) that exhibits the issue:  1.15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: WIN10
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details
Please find the below snap shot: 
![image](https://user-images.githubusercontent.com/7989610/67147440-6c80ed80-f2b2-11e9-9738-fb362077c849.png)

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
You can provide some non-empty string as `deviceName` capability to workaround the problem for now

**Comment by anunay1** [comment]
Thanks, it works.
