### ISSUE TITLE
Appium 1.16.0-beta.1 failed to install app

### ISSUE THREAD

**Issue by bennid** [appium/appium#13453]
## The problem

Same app that works on appium 1.15.0 isn't installing on 1.16.0-beta.1

> 2019-10-18 20:26:57:914 - [debug] [W3C (108a9c04)] Calling AppiumDriver.installApp() with args: ["http://myserver.com:8000/files/myapp.ipa",null,null,null,"108a9c04-766e-490a-886e-83d4b5e195cc"]
> 2019-10-18 20:26:57:914 - [debug] [XCUITest] Executing command 'installApp'
> 2019-10-18 20:26:57:915 - [BaseDriver] Using downloadable app 'http://myserver.com:8000/files/myapp.ipa'
> 2019-10-18 20:26:57:919 - [debug] [BaseDriver] App Last-Modified: Fri, 18 Oct 2019 12:37:26 GMT
> 2019-10-18 20:26:57:920 - [BaseDriver] The application at '/var/folders/r3/c1fz8xvj78557t5tj1vw_kmc0000gp/T/2019918-5851-e7w82w.cd6p5/Payload/MyApp.app' does not exist anymore. Deleting it from the cache
> 2019-10-18 20:26:57:921 - [debug] [BaseDriver] Content-Type: application/octet-stream
> 2019-10-18 20:26:57:921 - [debug] [BaseDriver] Content-Disposition: attachment; filename="myapp.ipa"
> 2019-10-18 20:26:58:967 - [debug] [BaseDriver] 'http://myserver.com:8000/files/myapp.ipa' (115.44 MB) has been downloaded to '/var/folders/r3/c1fz8xvj78557t5tj1vw_kmc0000gp/T/2019918-5851-fqh5xz.v96xj/myapp.ipa' in 1.045s
> 2019-10-18 20:26:59:205 - [debug] [BaseDriver] Unzipping '/var/folders/r3/c1fz8xvj78557t5tj1vw_kmc0000gp/T/2019918-5851-fqh5xz.v96xj/myapp.ipa'
> 2019-10-18 20:27:02:649 - [HTTP] --> GET /wd/hub/status
> 2019-10-18 20:27:02:650 - [HTTP] {}
> 2019-10-18 20:27:02:651 - [debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
> 2019-10-18 20:27:02:652 - [debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.16.0-beta.1"}}
> 2019-10-18 20:27:02:656 - [HTTP] <-- GET /wd/hub/status 200 5 ms - 75
> 2019-10-18 20:27:02:656 - [HTTP] 
> 2019-10-18 20:27:06:930 - [debug] [BaseDriver] Extracted 8587 item(s) from '/var/folders/r3/c1fz8xvj78557t5tj1vw_kmc0000gp/T/2019918-5851-fqh5xz.v96xj/myapp.ipa'
> 2019-10-18 20:27:07:461 - [debug] [BaseDriver] Matched 8586 item(s) in the extracted archive. Assuming 'Payload/MyApp.app' is the correct bundle
> 2019-10-18 20:27:07:475 - [BaseDriver] Unzipped local app to '/var/folders/r3/c1fz8xvj78557t5tj1vw_kmc0000gp/T/2019918-5851-1hw9a5d.gozm/Payload/MyApp.app'
> 2019-10-18 20:27:07:475 - [XCUITest] Installing '/var/folders/r3/c1fz8xvj78557t5tj1vw_kmc0000gp/T/2019918-5851-1hw9a5d.gozm/Payload/MyApp.app' to the real device with UDID 7090eac95fe26e87ec013646c75a289c235003c7
> 2019-10-18 20:28:33:194 - [XCUITest] Error was thrown during the installation process
> 2019-10-18 20:28:33:195 - [XCUITest] Error: Unexpected data: {"Error":"ApplicationVerificationFailed","ErrorDetail":-1,"ErrorDescription":"Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.T2PUKK/extracted/MyApp.app : 0xe8008017 (A signed resource has been added, modified, or deleted.)"}
> 2019-10-18 20:28:33:195 - [XCUITest]     at InstallationProxyService._isFinished (/Directory/XXXXXXXXXX/node_modules/appium-ios-device/lib/installation-proxy/index.js:132:13)
> 2019-10-18 20:28:33:195 - [XCUITest]     at InstallationProxyService._isFinished [as _waitMessageCompletion] (/Directory/XXXXXXXXXX/node_modules/appium-ios-device/lib/installation-proxy/index.js:124:16)
> 2019-10-18 20:28:33:195 - [XCUITest]     at InstallationProxyService.installApplication (/Directory/XXXXXXXXXX/node_modules/appium-ios-device/lib/installation-proxy/index.js:24:12)
> 2019-10-18 20:28:33:195 - [XCUITest]     at IOSDeploy.installApplication (/Directory/XXXXXXXXXX/node_modules/appium-xcuitest-driver/lib/ios-deploy.js:52:7)
> 2019-10-18 20:28:33:195 - [XCUITest]     at IOSDeploy.install (/Directory/XXXXXXXXXX/node_modules/appium-xcuitest-driver/lib/ios-deploy.js:37:7)
> 2019-10-18 20:28:33:195 - [XCUITest]     at IOSDeploy.installApp (/Directory/XXXXXXXXXX/node_modules/appium-xcuitest-driver/lib/ios-deploy.js:104:5)
> 2019-10-18 20:28:33:195 - [XCUITest]     at XCUITestDriver.mobileInstallApp (/Users/bdouglas/build_tools/ios_phone/7090eac95fe26e87ec013646c75a289c235003c7/node_modules/appium-xcuitest-driver/lib/commands/app-management.js:28:5)
> 2019-10-18 20:28:33:195 - [XCUITest]     at XCUITestDriver.installApp (/Directory/XXXXXXXXXX/node_modules/appium-xcuitest-driver/lib/commands/app-management.js:90:3)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0-beta.1
* Last Appium version that did not exhibit the issue (if applicable): 1.15.0
* Desktop OS/version used to run Appium: OSX 10.14.6
* Node.js version (unless using Appium.app|exe): v12.10.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS 13.1.2
* Real device or emulator/simulator: iPhone 7
* Appium CLI or Appium.app|exe: Appium CLI

**Comment by mykola-mokhnach** [comment]
This must have been fixed in the recent appium@beta

**Comment by furmanjmx** [comment]
@mykola-mokhnach today i have the same issue( 

[debug] [MJSONWP] Encountered internal error running command: Error: Could not install app: 'Unexpected data: {"Error":"ApplicationVerificationFailed","ErrorDetail":-1,"ErrorDescription":"Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.akUTLj/extracted/ds-chat-ios.app : 0xe8008018 (The identity used to sign the executable is no longer valid.)"}'
[debug] [MJSONWP]     at IOSDeploy.install (/usr/local/Cellar/node/12.5.0/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/ios-deploy.js:41:13)


Appium 1.15.1

**Comment by mykola-mokhnach** [comment]
@furmanjmx Sorry, but we are talking about appium@beta here.

**Comment by furmanjmx** [comment]
@mykola-mokhnach  i see but on 1.15.1 same issue. maybe the similar problem

**Comment by bennid** [comment]
When are we going to be able to have 1.16.0-beta.2 available on npm?  It's been 2 months since 1.16.0-beta.1 was out, and iOS 13.2 was released 21 days ago, so our iPhones are quite behind now.

**Comment by bennid** [comment]
@mykola-mokhnach This is still broken in 1.16.0-beta.2.

The phone has been updated to iOS 13.2.3 and XCode is 11.2

**Comment by mykola-mokhnach** [comment]
@bennid Can you provide the logs?

**Comment by bennid** [comment]
NOTE: We startup the Settings app, then uninstall all other versions of our app (they use shared data), then install the ipa from a local server.

https://gist.github.com/bennid/1229cd1f8c51e196c40724e5052d4c54

**Comment by mykola-mokhnach** [comment]
@bennid Can you please check what is the actual xcuitest driver version in the packages? To me it looks like the recent improvements I did to it are not present in Appium

**Comment by mykola-mokhnach** [comment]
Actually, it is the case there. The current xcuitest driver version is 3.7.0 and your log shows
> Appium v1.16.0-beta.2 creating new XCUITestDriver (v3.2.0) session

**Comment by bennid** [comment]
So can we either get an update to beta.2 or get a beta.3 with the newer xcuitest driver in it?

**Comment by mykola-mokhnach** [comment]
beta versions of appium are not shrinkwrapped. This means that each reinstall always installs the recent module versions

**Comment by bennid** [comment]
So would I have to specify npm to install that version?

**Comment by bennid** [comment]
@mykola-mokhnach I've updated all the other packages on top of appium 1.16.0-beta.2, and have had a SLEW of provision profile errors etc... but even when using xcodebuild  with "-allowProvisioningUpdates" there's a compile error:

/Users/username/build_tools/ios_phone/UDID/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgentLib/Routing/FBTCPSocket.h:10:9: fatal error: 'RoutingHTTPServer/GCDAsyncSocket.h' file not found

**Comment by mykola-mokhnach** [comment]
Make sure you did bootstrap properly on WDA and that carthage downloaded the most recent dependencies there. Like I said before make sure there are no cached entities from previous installations before installing the new beta.

**Comment by bennid** [comment]
It seemed to have worked this time... going to try to reproduce the setup now.  The signing has always been a painpoint in our setup, and every time xcode is upgraded we hit issues.

**Comment by bennid** [comment]
I removed the whole parent node_modules directory before installing
1.16.0-beta.2 again and Carthage is already at 0.34.0.
