### ISSUE TITLE
Not able to execute tests using appium ui-automator driver with API version 28 or higher

### ISSUE THREAD

**Issue by lakshmi-236** [appium/appium#13467]
## The problem

hi ,
i am running selenium tests using Emulator with appium ui-automator 2 driver. upto api version 27 tests are running without issues. 
but when i upgraded it to api 28 tests are not running. Below is the capabilities used

capabilities: {
'chromeOptions': {
args: [
'incognito',
'disable-extensions',
]
},
browserName: '',
app: path.join(__dirname,'../../../platforms/android/app/build/outputs/apk/debug/app-debug.apk'),
appActivity: '.MainActivity',
automationName: 'uiautomator2',
platformName: 'Android',
platformVersion: '10',
deviceName: 'Android Emulator',
autoWebview: true,
autoWebviewTimeout: 20000,
autoAcceptAlerts: true,
deviceReadyTimeout: 120,
avd: 'PIxel_2_API_29',
avdArgs: '-dns-server 8.8.8.8,8.8.4.4',
noReset: false
}

## Environment

* Appium version (or git revision) that exhibits the issue:1.14.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10 
* Node.js version (unless using Appium.app|exe):10.14.0
* Npm or Yarn package manager: npm(latest)
* Mobile platform/version under test: API 29
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: Appium.exe

## Details
we are executing tests using ngapimock as backend for test execution.

## Link to Appium logs

https://gist.github.com/lakshmi-236/d3973150413ca91da2d88df31b0674ec

**Comment by mykola-mokhnach** [comment]
Please fill out the issue reporting form and provide the required data

**Comment by lakshmi-236** [comment]
Added details as mentioned

**Comment by mykola-mokhnach** [comment]
I don't observe any issues in the attached log. What exactly does not work?

**Comment by lakshmi-236** [comment]
i am having a test automation framework with protractor . We are using emulator for running tests. If API version of emulator is <28 tests are executing. if it is higher version, not even login to application is happening.
