### ISSUE TITLE
Add get clipboard feature in settings apk (Appium IME) for Android 10+ changes

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#13466]
## The problem

Set clipboard works but get clipboard doesn't in Android 10 https://github.com/appium/appium/issues/12311#issuecomment-473514300 because of the new security limitation.

https://developer.android.com/about/versions/10/privacy/changes#clipboard-data

> Unless your app is the default input method editor (IME) or is the app that currently has focus, your app cannot access clipboard data on Android 10 or higher.

Maybe we can add getting clipboard feature on Appium IME in the settings apk.
(I haven't evaluated if we exactly can do so)

**Comment by mykola-mokhnach** [comment]
@KazuCocoa Could you please check the implementation on a phone running Android 10, if you have it, before I merge the changed?

**Comment by KazuCocoa** [comment]
okay 🆗

**Comment by mykola-mokhnach** [comment]
The changes have been published to beta
