### ISSUE TITLE
Android Default Web Browser

### ISSUE THREAD

**Issue by ajschwieterman** [appium/appium#13465]
## The problem

I'm testing an app that uses the default web browser to open webviews in the app or new browser tabs outside of the app.  Is there a way to set the default browser app before a test?  I don't want the window to pop up that forces me to choose which browser to set as the default browser during testing.

The setting I'm looking to change programmatically is navigated manually in Settings --> Apps & Notifications --> Advanced --> Default apps --> Browser app

**Comment by mykola-mokhnach** [comment]
Android security does not allow to set defaults apps via ADB. Please use Appium forum to ask questions
