### ISSUE TITLE
How to set to True the setWebContentsDebuggingEnabled property on the android.webkit.WebView element? 

### ISSUE THREAD

**Issue by Devapal** [appium/appium#13468]
Source: appium.io/docs/en/writing-running-appium/web/hybrid

How do I set to set to true the setWebContentsDebuggingEnabled property on the android.webkit.WebView element. 

From the documentation at appium.io/docs/en/writing-running-appium/web/hybrid , I see that the method setWebContentsDebuggingEnabled is accountable for debugging web contents and is default set to false. 
**But I do NOT see any setWebContentsDebuggingEnabled method, where is it located** ? 
How do I set this to true for a Cordova Mobile App (hybrid) project ? 

Can someone provide the steps to enable the WebView for a Cordova Hybrid App ?
**Is there a setting in project files that enables the WebView** ? Please advise.

Purpose of this query:
I am trying to get context handles for this Hybrid Mobile App ( Cordova ) and I see only native. I need to be able to get WebView to interact with the mobile elements for UI testing using Appium.

**Comment by KazuCocoa** [comment]
https://developers.google.com/web/tools/chrome-devtools/remote-debugging/webviews#configure_webviews_for_debugging is it. (The link is also there in the appium.io/docs/en/writing-running-appium/web/hybrid)

For Cordova app, it is better to ask it to the team.
Maybe https://github.com/apache/cordova-android/blob/master/framework/src/org/apache/cordova/engine/SystemWebViewEngine.java#L224-L231 ?

**Comment by mykola-mokhnach** [comment]
@dpgraham Do we want to have such information in our documentation?

**Comment by shibupanda** [comment]
@mykola-mokhnach is it good share the instrumentation process for Cordova app. 
Recently I cracked it. You want me share those.

Or if the source code is there then they can directly enable some setting which will show the webview.

**Comment by Devapal** [comment]
@shibupanda That would be great if you can.

**Comment by shibupanda** [comment]
@Devapal Below worked for me. Please try it.
Android (Cordova-app):
In manifest.xml **android:debuggable="true"** should be true. if not please ask the dev to make this true.

iOS (Cordova-app):
In config.xml **<preference name="WKWebViewOnly" value="true"/>** make this true. if not please ask the dev to make this true.

**Comment by shibupanda** [comment]
@Devapal 
Could you please update if you can able to find the mentioned one for Cordova app.

**Comment by BalajiKalai** [comment]
@shibupanda if developer set debuggable="true" then can we able to interact with the mobile elements for UI testing using Appium.

**Comment by zaphodikus** [comment]
Is this hint added to the Appium documentation yet. Thanks in advance.  (I'm using Flutter in my case, and I have a embedded web thingy to deal with.) I will update if I get any joy.

**Comment by monkeytronics** [comment]
One last note on this topic, it's important to set the build flag to --debug, not --release if you plan to do debugging in a remote location. I found that I was able to debug locally, with the `"WKWebViewOnly" value="true"` , but could not run on Browserstack, until I changed the cordova build command to `$ ionic cordova build android --prod --debug`.
