### ISSUE TITLE
Appium remote session cannot be created due to "Cannot read property 'quitAndUninstall' of null" error

### ISSUE THREAD

**Issue by aveeveng** [appium/appium#13464]
## The problem

After updating our iOS devices to 13.1.3 and Appium to 1.15.1 (desktop and npm), tests fail to start due to "cannot read property 'quitAndUninstall' of null".

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): 1.13
* Desktop OS/version used to run Appium: 1.15.1
* Node.js version (unless using Appium.app|exe): 10.16.3
* Npm or Yarn package manager: 6.11.3
* Mobile platform/version under test: iOS 13.1.3
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: 1.15.1

## Details

At the start of execution, app gets installed and previous WDA gets uninstalled and then a new WDA is installed. Despite WDA installing, session doesn't get created and eventually fails.

## Link to Appium logs

https://gist.github.com/aveeveng/89a343b54c54ebab87700ac3180b4f49

**Comment by mykola-mokhnach** [comment]
> [error] [XCUITest] Error: Appium did not get any response from 'createSession' command in 20000 ms

This is the main problem source, although the requirement of 20000 ms is set explicitly in the capabilities, so the error is expected

**Comment by aveeveng** [comment]
Timing out was not the root cause. I figured it out; I was using an incorrect bundle id in my capabilities and Appium timed out trying to find a nonexistent app..
