### ISSUE TITLE
Not seeing WebDriverAgent folder 

### ISSUE THREAD

**Issue by SoundaryaBhavanam** [appium/appium#13473]
Not seeing WebDriverAgent folder in the below location

/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/
 
## Environment

* Appium version (or git revision) that exhibits the issue:+ appium@1.15.1

* Npm or Yarn package manager:6.11.3

npm install -g appium
/usr/local/bin/appium -> /usr/local/lib/node_modules/appium/build/lib/main.js
/usr/local/bin/authorize-ios -> /usr/local/lib/node_modules/appium/node_modules/.bin/authorize-ios

> fsevents@1.2.9 install /usr/local/lib/node_modules/appium/node_modules/chokidar/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "/usr/local/lib/node_modules/appium/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" is installed via remote

> appium-windows-driver@1.6.0 install /usr/local/lib/node_modules/appium/node_modules/appium-windows-driver
> node install-npm.js

Not installing WinAppDriver since did not detect a Windows system

> pre-commit@1.2.2 install /usr/local/lib/node_modules/appium/node_modules/pre-commit
> node install.js

> wd@1.11.4 install /usr/local/lib/node_modules/appium/node_modules/wd
> node scripts/build-browser-scripts

> core-js@2.6.9 postinstall /usr/local/lib/node_modules/appium/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> spawn-sync@1.0.15 postinstall /usr/local/lib/node_modules/appium/node_modules/spawn-sync
> node postinstall

> appium-chromedriver@4.16.0 postinstall /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver
> node install-npm.js

[16:44:19] [Chromedriver Install] Installing Chromedriver version '76.0.3809.126' for platform 'mac' and architecture '64'
[16:44:19] [Chromedriver Install] Opening temp file to write 'chromedriver_mac64' to...
[16:44:19] [Chromedriver Install] Opened temp file '/var/folders/hp/9gsgl5qn0xq1vjdbc11r6fpr0000gr/T/2019922-39897-7a4rb4.a1thp/chromedriver_mac64.zip'
[16:44:19] [Chromedriver Install] Downloading https://chromedriver.storage.googleapis.com/76.0.3809.126/chromedriver_mac64.zip...
[16:45:11] [Chromedriver Install] Writing binary content to /var/folders/hp/9gsgl5qn0xq1vjdbc11r6fpr0000gr/T/2019922-39897-7a4rb4.a1thp/chromedriver_mac64.zip...
[16:45:11] [Chromedriver Install] Extracting /var/folders/hp/9gsgl5qn0xq1vjdbc11r6fpr0000gr/T/2019922-39897-7a4rb4.a1thp/chromedriver_mac64.zip to /var/folders/hp/9gsgl5qn0xq1vjdbc11r6fpr0000gr/T/2019922-39897-7a4rb4.a1thp/chromedriver_mac64
[16:45:11] [Chromedriver Install] Creating /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac...
[16:45:11] [Chromedriver Install] Copying unzipped binary, reading from /var/folders/hp/9gsgl5qn0xq1vjdbc11r6fpr0000gr/T/2019922-39897-7a4rb4.a1thp/chromedriver_mac64/chromedriver...
[16:45:11] [Chromedriver Install] Writing to /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver...
[16:45:11] [Chromedriver Install] /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver successfully put in place
+ appium@1.15.1
added 1458 packages from 1651 contributors and updated 1 package in 70.568s
:~$ cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/:appium-xcuitest-driver$ ls
LICENSE		build		lib		package.json
README.md	index.js	node_modules:appium-xcuitest-driver$ cd node_modules/:node_modules$ ls
appium-ios-device	appium-remote-debugger:node_modules$ cd ..
:appium-xcuitest-driver$ cd lib:lib$ ls
commands			logger.js
desired-caps.js			real-device-management.js
device-connections-factory.js	server.js
device-log			simulator-management.js
driver.js			utils.js
ios-deploy.js			wda
ios-generic-simulators.js

**Comment by juandg** [comment]
It was moved on Appium 1.15 and now you should be able to find it at:
 
/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent

**Comment by SoundaryaBhavanam** [comment]
Sure thanks for update

Where to install bootstrap?

**Comment by juandg** [comment]
Not sure what you mean by "install bootstrap" but if what you're trying to do is follow the instructions from the [Appium XCUITest Driver Real Device Setup](http://appium.io/docs/en/drivers/ios-xcuitest-real-devices/) page, you can just use the new path instead.
```bash
$ cd /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent
$ mkdir -p Resources/WebDriverAgent.bundle
$ ./Scripts/bootstrap.sh -d
...
```

**Comment by mykola-mokhnach** [comment]
Closed as not an issue (also duplicate)

**Comment by LakshmananKuppan** [comment]
Hi @mykola-mokhnach I am facing the same issue. I unable to see the appium-webdriveragent folder under "/usr/local/lib/node_modules/appium/node_modules/" path.

I have installed Appium 2.0 using command line like.
npm install -g appium@next

And installed flowing package too.
brew install Carthage
npm install -g appium-doctor
appium --base-path /wd/hub
appium driver install xcuitest
appium plugin install images 
appium plugin install execute-driver
appium plugin install relaxed-caps

But I am unable to see any folder name starts with "appium" under "/usr/local/lib/node_modules/appium/node_modules/" path. 

I am struggling a lot to automate the IOS device because I am getting below error because of this issue.
**Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65**

Please Please Please Please help me.

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md#appium-2x
