### ISSUE TITLE
Full manual configuration in Appium XCUITest Driver Real Device Setup references invalid directory

### ISSUE THREAD

**Issue by kacy-weakley** [appium/appium#13474]
## The problem

In the `Full manual configuration` section of https://github.com/appium/appium/blob/v1.15.0-rc.5/docs/en/drivers/ios-xcuitest-real-devices.md, the `appium-xcuitest-driver/WebDriverAgent` directory, which no longer exists in Appium 1.15, is referenced for setup:

> Given this installation location, `/path/where/installed/bin/appium`, `WebDriverAgent` will be found in `/path/where/installed/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent`. Open a terminal and go to that location, then run the following in order to set the project up:

In the appium website documentation, http://appium.io/docs/en/drivers/ios-xcuitest-real-devices/, it references the correct `appium-webdriveragent ` directory, but it still incorrectly references the non-existent `WebDriverAgent` sub-directory:

> Given this installation location, /path/where/installed/bin/appium, WebDriverAgent will be found in /path/where/installed/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent. Open a terminal and go to that location, then run the following in order to set the project up:

Both of those need to be updated to `/path/where/installed/lib/node_modules/appium/node_modules/appium-webdriveragent` for Appium 1.15.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.0-rc.5

**Comment by KazuCocoa** [comment]
Thanks.

The path has been updated in the current master and website.

https://github.com/appium/appium/blob/master/docs/en/drivers/ios-xcuitest-real-devices.md
http://appium.io/docs/en/drivers/ios-xcuitest-real-devices/

**Comment by kacy-weakley** [comment]
It isn't updated in current master or on the website. They both still reference WebDriverAgent directory. That directory doesn't exist.

**Comment by KazuCocoa** [comment]
ah, I see.https://github.com/appium/appium/pull/13475

btw, welcome to creating a PR to update docs :)
