### ISSUE TITLE
Not able to inspect iOS widgets in iPhone X or latest versions 

### ISSUE THREAD

**Issue by vky26** [appium/appium#13478]
## The problem

Not able to inspect the widgets in iPhone versions from iPhone X ( XS, XR) (OS 13) 
We are able to inspect in iPhone 8 though ( OS 12.1) using Appium UI Automator. 

Steps to reproduce the issue: 

1. Open Appium UI inspector for any native app, minimise and go to dashboard in phone
2. Swipe to the left most screen, where we can see widgets present. 
3. Refresh the Appium UI Inspector and try to inspect and locate elements for widgets. 

## Environment

* Appium version: 1.15.0
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Mac Mini - 10.14.5 (18F132)
* Node.js version (unless using Appium.app|exe): v10.16.3
* Npm or Yarn package manager: 6.10.3
* Mobile platform/version under test: iOS / 13.1.1
* Real device or emulator/simulator: iPhone XS (OS 13.1.1)
* Appium CLI or Appium.app|exe: Appium App (1.15.0)

## Details
Open Appium Inspector, navigate to left most screen of iPhone X and latest models. Try to inspect the widgets. 

Attached screenshot of the issue, where we couldn't identify the widget lists
![Screenshot 2019-10-23 at 11 51 37](https://user-images.githubusercontent.com/30401839/67385777-a3ddeb80-f58b-11e9-8ab7-37a65c872a88.png)

## Code To Reproduce Issue [ Good To Have ]

UI Inspector not showing widget elements on latest iPhone model or iPhone X versions

Any pointers on this, would be helpful.

PS: Might not really issue with Appium but apple, but would like to get some insights. Thank you.

**Comment by mykola-mokhnach** [comment]
> PS: Might not really issue with Appium but apple, but would like to get some insights. Thank you.

you are right - the page source is built by xctest, so in case an element is not accessible then no hierarchy would be shown for it

**Comment by mayureshshirodkar** [comment]
I have seen this happening since iPhone update to iOS 13 update.
There is no hierarchy or accesibility ids available anymore for the apps that worked fine with ios 12.
(Apps- Apple Maps)

**Comment by KazuCocoa** [comment]
Does `includeNonModalElements` help?
http://appium.io/docs/en/advanced-concepts/settings/

**Comment by KazuCocoa** [comment]
Yes. Our end gets data from the vanilla XCTest framework

BTW, I was able to get elements, e.g. 'edit', on iOS 13.1.3 (iPhone SE tho) x Xcode 11 x Appium 1.15. So, potentially it depends on devices...?
