### ISSUE TITLE
Not able to read .ipa file from NFS server

### ISSUE THREAD

**Issue by kolyakrasnik** [appium/appium#13472]
We use NFS network share for .ipa files. The same approach works fine for other machines with appium version 1.14.2.  I see shared folder on the machine, able to create file in the shared folder and this file becomes visible on other machines. I tried to deploy the app from shared folder directly with ios-deploy and it works fine ```ios-deploy -i <udid> -b /path/to/share/build.ipa```

* Appium version (or git revision) that exhibits the issue: 1.15.0
* Last Appium version that did not exhibit the issue (if applicable): 1.14.2
* Desktop OS/version used to run Appium: MacOS 10.14.4 Mojave
* Node.js version (unless using Appium.app|exe): v12.11.1
* Npm or Yarn package manager: 6.11.3
* Mobile platform/version under test: iOS 
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: cli 

## Link to Appium logs
https://gist.github.com/kolyakrasnik/e11eae661d172edbb540494a91615641

**Comment by mykola-mokhnach** [comment]
This error happens before the app is installed and is caused by the fact that Appium process has no access to the file.

**Comment by kolyakrasnik** [comment]
The issue was with incorrect set up for npm. To resolve the issue ```npm cache clean --force```  ```npm install -g npm@latest --force``` ```npm cache clean --force```
