### ISSUE TITLE
Error: UIAutomation2 is only supported since Android 5.0 (Lollipop)

### ISSUE THREAD

**Issue by mindarchitect** [appium/appium#13471]
## The problem

I am trying to reload Appium configuration in order to perofrm the test on different Android platfrom version. Appium throws an error which at least can be confusing:

Error: UIAutomation2 is only supported since Android 5.0 (Lollipop). You could still use other supported backends in order to automate older Android versions.

First: There is no such automation as UIAutomation2. Istead it is UIAutomator2 or?
Second: While loading the Appium automator I see server is showing me correct automator for old version (Appium) but tries to use UIAutomation2 ???

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): 1.14.0
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: Android 4.4
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/mindarchitect/6868f07b1b9706d3426ea9949623e9df

**Comment by imurchie** [comment]
Yikes! That's a major slip. Thanks for pointing it out!
