### ISSUE TITLE
Can't launch iOS app on real device using Appium Inspector and the latest Xcode 11.1

### ISSUE THREAD

**Issue by viktorgogulenko** [appium/appium#13484]
## The problem

I've tried to launch new Appium Inspector session with old capability set (which was working in past with previous version of Xcode) and it fails with error:

> [iProxy@00008...] Connection was refused to port 8122
> [WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
> [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up). Retrying...
> [XCUITest] UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up
> [XCUITest]     at JWProxy.command (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:261:13)
> [XCUITest] Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.

## Environment

* Appium version: 1.15.1 (Desktop, Mac)
* Desktop OS/version used to run Appium: Mac OS Mojave 10.14.6
* Node.js version (unless using Appium.app|exe): 11.0.0
* Npm or Yarn package manager: 6.4.1
* Mobile platform/version under test: iOS 13.1.3
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: Appium.app

## Details

I've tried to reboot device, Mac, I can successfully build and run WDA which is going with Appium using Xcode itself (made before all steps from http://appium.io/docs/en/drivers/ios-xcuitest-real-devices/), but it doesn't work when I'm trying to use Appium Inspector and to install&launch my ipa file on device.

## Link to Appium logs
[GIST WITH LOGS](https://gist.github.com/viktorgogulenko/94b7c004b27ad670ccbb35affbc8f529)

**Comment by mykola-mokhnach** [comment]
The provided information is not enough. Pleas provide the full server log including iOS and Xcode logs enabled.

**Comment by viktorgogulenko** [comment]
@mykola-mokhnach After deeper investigation I've found that seems I have the same issue which was already posted #13330 . You can close this one. Sorry

**Comment by viktorgogulenko** [comment]
Added Xcode logging - [UPD: GIST WITH LOGS](https://gist.github.com/viktorgogulenko/9266f3a0d23cd869389191b82acaa864)

**Comment by mykola-mokhnach** [comment]
> [error] [Xcode] 18:12:32.491 xcodebuild[29873:130683] <XCTTestRunnerSession: 0x7faf97754c00> lost its connection.
> [error] [Xcode] 18:12:32.491 xcodebuild[29873:130592] Lost connection to test process
> [error] [Xcode] 18:12:32.492 xcodebuild[29873:130673] 📱<DVTiOSDevice (0x7faf973de110), iPhone XR, iPhone, 13.1.3 (17A878), 00008020-0004248A3645002E> notified that pid 327 died
> [error] [Xcode] 18:12:32.492 xcodebuild[29873:130592] 📱<DVTiOSDevice (0x7faf973de110), iPhone XR, iPhone, 13.1.3 (17A878), 00008020-0004248A3645002E> ############## DID EXECUTE #################
> [error] [Xcode] 18:12:32.493 xcodebuild[29873:130592] Launch session expired.

It looks like XCTest fails to start the session

**Comment by mykola-mokhnach** [comment]
Check https://github.com/appium/appium/issues?q=is%3Aissue+wdaEventloopIdleDelay+is%3Aclosed, perhaps some solutions there could help

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
