### ISSUE TITLE
Appium 1.15.x No Longer matching Connected UDID of Real Device

### ISSUE THREAD

**Issue by hcastro** [appium/appium#13486]
## The problem

UDID of real device using Appium 1.15.0 no longer contains a "-". This is causing the following error: 

> 2019-10-24 18:04:58:609 - [debug] [35m[MJSONWP][39m Encountered internal error running command: Error: Unknown device or simulator UDID: '00008020-001C650A2288002E'
2019-10-24 18:04:58:609 - [debug] [35m[MJSONWP][39m     at XCUITestDriver.determineDevice (/usr/local/avm/versions/1.15.0/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:806:17)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15
* Last Appium version that did not exhibit the issue (if applicable): 1.14
* Node.js version (unless using Appium.app|exe): 10.16.0
* Npm or Yarn package manager: yarn
* Mobile platform/version under test:  iOS
* Real device or emulator/simulator: Real

## Details

Appium retrieves the connected device with a UDID of: `00008020001C650A2288002E`
Actual UDID of connected device: `00008020-001C650A2288002E`

Devices used: `iPhone XS Max (12.1)`, `iPhone XR (12.4.1)`

I am using AWS Device Farm to access their pool of real devices, so I don't have control over their device UDID's. I've also tried Appium 1.15.1 to no avail.

## Link to Appium logs

https://gist.github.com/hcastro/0ec6d2f7c86466971efbaecacd049217

**Comment by imurchie** [comment]
Interesting. Can you try without the hyphen? So the `udid` would be `00008020001C650A2288002E`.

**Comment by hcastro** [comment]
> Interesting. Can you try without the hyphen? So the `udid` would be `00008020001C650A2288002E`.

I can't. The `udid` of the device is accessed through an environment variable on the Device Farm host and I don't know which device will be used until the host is spun up and the device gets allocated.

**Comment by imurchie** [comment]
But you could do something like `udid = process.env.AWS_UDID.replace('-', '')` or whatever is the case in the language you're using.

We can make this work on the server side, but it will take a while to get into place, so temporarily doing it on the test side would be useful for now.

**Comment by hcastro** [comment]
Giving it a shot, but it looks like exactly what I need to do.

**Comment by imurchie** [comment]
Since it seems like only one `udid` is made available through the system interface (not sure what AWS is doing) you can also use `'auto'` as the `udid` capability and it will pick that.

**Comment by hcastro** [comment]
It worked @imurchie! Thanks a lot~

**Comment by Bruno-ornelas** [comment]
Como você conseguiur iniciar o appium 1.15 no aws device farm?
