### ISSUE TITLE
'Wait for com.xxxxxx.com to idle'执行每一步操作都需要等待很久，最后报错；

### ISSUE THREAD

**Issue by qxmingsj** [appium/appium#13482]
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'

appium1.15.1出现这个问题；
appium1.14之前一直是好的；

**Comment by mykola-mokhnach** [comment]
Sorry, but we only speak English
closed as incomplete
