### ISSUE TITLE
WebDriverAgentRunner-Runner.app encountered an error (Failed to establish communication with the test runner. (Underlying error: Unable to connect to test manager on d3506727a5#####1. (Underlying error: Could not connect to the device.))) Appium IOS could not connect with real devices

### ISSUE THREAD

**Issue by dragon11111** [appium/appium#13487]
## The problem

Got this error like below: WebDriverAgentRunner-Runner.app encountered an error (Failed to establish communication with the test runner. (Underlying error: Unable to connect to test manager on d3506727ae53d74e5a8e59fac3b86198ccaa0071. (Underlying error: Could not connect to the device.)))

I am pretty new for IOS Appium. Currently I could build up and connect appium server on simulators successfully, but do not know why could not build up with real devices. 

## Environment

* Appium version : v.1.15.1
* Desktop OS/version used to run Appium: macOS Mojava Version 10.14.4
* Node.js version (unless using Appium.app|exe): v10.16.3
* Npm or Yarn package manager: 6.11.3
* Mobile platform/version under test: IOS 11.4.1
* Real device or emulator/simulator: Real device iphone 7
* Appium CLI or Appium.app|exe: Appium desktop

## Details

Was trying to start session by appium desktop to connect with real devices, then got following error like the logs shown.

## Link to Appium logs

MJSONWP] Calling AppiumDriver.createSession() with args: [{"automationName":"XCuiTest","bundleId":"com.test.123","deviceName":"iPhone","noReset":true,"platformName":"IOS","platformVersion":"11.4.1","udid":"d3506######caa0071","updatedWDABundleId":"com.test.webdriveragent","useNewWDA":true,"xcodeOrgId":"#####","xcodeSigningId":"iPhone Developer","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1571945262274 (15:27:42 GMT-0400 (EDT))
[Appium] Appium v1.15.1 creating new XCUITestDriver (v2.133.1) session
[BaseDriver] Creating session with MJSONWP desired capabilities: {
[BaseDriver]   "automationName": "XCuiTest",
[BaseDriver]   "bundleId": "com.lenovo.Help",
[BaseDriver]   "deviceName": "iPhone",
[BaseDriver]   "noReset": true,
[BaseDriver]   "platformName": "IOS",
[BaseDriver]   "platformVersion": "11.4.1",
[BaseDriver]   "udid": "d3506727#######aa0071",
[BaseDriver]   "updatedWDABundleId": "com.test.webdriveragent",
[BaseDriver]   "useNewWDA": true,
[BaseDriver]   "xcodeOrgId": "####",
[BaseDriver]   "xcodeSigningId": "iPhone Developer",
[BaseDriver]   "newCommandTimeout": 0,
[BaseDriver]   "connectHardwareKeyboard": true
[BaseDriver] }
[BaseDriver] Session created with session id: 61568738-d9c1-4fdc-8a88-f1644551041e
[XCUITest] Current user: '####'
[XCUITest] Available devices: d3506#######ccaa0071
[XCUITest] Creating iDevice object with udid 'd3506$$######8ccaa0071'
[XCUITest] Determining device to run tests on: udid: 'd3506#######8ccaa0071', real device: true
[XCUITest] Normalized platformVersion capability value '11.4.1' to '11.4'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1571945263765 (15:27:43 GMT-0400 (EDT))
[BaseDriver] Event 'appConfigured' logged at 1571945263766 (15:27:43 GMT-0400 (EDT))
[BaseDriver] Event 'resetStarted' logged at 1571945263766 (15:27:43 GMT-0400 (EDT))
[XCUITest] Reset: fullReset not set. Leaving as is
[BaseDriver] Event 'resetComplete' logged at 1571945263766 (15:27:43 GMT-0400 (EDT))
[XCUITest] Crash reports root '/Users/#####/Library/Logs/CrashReporter/MobileDevice/iPhone' does not exist. Got nothing to gather.
[BaseDriver] Event 'logCaptureStarted' logged at 1571945264060 (15:27:44 GMT-0400 (EDT))
[XCUITest] Setting up real device
[XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-webdriveragent'
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'
[XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[DevCon Factory] Requesting connection for device d3506727ae53d74e5a8e59fac3b86198ccaa0071 on local port 8100, device port 8100
[DevCon Factory] Cached connections count: 0
[DevCon Factory] Port #8100 is busy
[DevCon Factory] Successfully requested the connection for d3506727ae53d74e5a8e59fac3b86198ccaa0071:8100
[XCUITest] Starting WebDriverAgent initialization with the synchronization key 'XCUITestDriver'
[XCUITest] Capability 'useNewWDA' set to true, so uninstalling WDA before proceeding
[XCUITest] Shutting down sub-processes
[XCUITest] No WDAs on the device.
[BaseDriver] Event 'wdaUninstalled' logged at 1571945265047 (15:27:45 GMT-0400 (EDT))
[XCUITest] Trying to start WebDriverAgent 1 times with 10000ms interval
[XCUITest] These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
[BaseDriver] Event 'wdaStartAttempted' logged at 1571945265049 (15:27:45 GMT-0400 (EDT))
[XCUITest] Launching WebDriverAgent on the device
[WebDriverAgent] Fetching dependencies
[WebDriverAgent] Dependencies up-to-date
[XCUITest] Killing running processes 'xcodebuild.*d350#####aa0071' for the device d3####aa0071...
[XCUITest] 'pgrep -ifn xcodebuild.*d35####a0071' didn't detect any matching processes. Return code: 1
[XCUITest] Successfully updated '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj/project.pbxproj' with bundle id 'com.test.webdriveragent'
[XCUITest] Generating xcode config file for orgId '####' and signingId 'iPhone Developer'
[XCUITest] Writing xcode config file to /var/folders/94/0pm75_gd0bd76k_5xz5d_jy80000gn/T/2019924-48460-kfiqtk.5s1h/appium-temp.xcconfig
[XCUITest] Using Xcode configuration file: '/var/folders/94/0pm75_gd0bd76k_5xz5d_jy80000gn/T/2019924-48460-kfiqtk.5s1h/appium-temp.xcconfig'
[XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=d3506727ae53d74e5a8e59fac3b86198ccaa0071 IPHONEOS_DEPLOYMENT_TARGET=11.4 -xcconfig /var/folders/94/0pm75_gd0bd76k_5xz5d_jy80000gn/T/2019924-48460-kfiqtk.5s1h/appium-temp.xcconfig GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-webdriveragent'
[XCUITest] Output from xcodebuild will only be logged if any errors are present there. To change this, use 'showXcodeLog' desired capability
[XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@d3506...] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@d3506...] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@d3506...] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[XCUITest] Log file for xcodebuild test: /Users/####/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz/Logs/Test/Test-WebDriverAgentRunner-2019.10.24_15-27-47--0400.xcresult/Staging/2_Test/Diagnostics/WebDriverAgentRunner-F9AED89E-E04C-438B-892C-292A03B848DE/WebDriverAgentRunner-BEE8B0B1-9C07-49BF-ADA3-D47314C07828/Session-WebDriverAgentRunner-2019-10-24_152748-YERt7L.log
[Xcode] 2019-10-24 15:27:49.149 xcodebuild[48502:2198169] [MT] IDETestOperationsObserverDebug: (4D195495-56CD-4F06-AE52-86571FB3A0FD) Failed to make test runner session:
[Xcode] Error Domain=com.apple.dt.xctest.error Code=9 "Unable to connect to test manager on d3506727ae53d74e5a8e59fac3b86198ccaa0071" UserInfo={NSLocalizedDescription=Unable to connect to test manager on d3506727ae53d74e5a8e59fac3b86198ccaa0071, NSUnderlyingError=0x7fd2c6fe4ca0 {Error Domain=XCTMobileDeviceFramework Code=101 "Could not connect to the device." UserInfo={NSLocalizedDescription=Could not connect to the device.}}}
[Xcode] 
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@d3506...] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[Xcode] 2019-10-24 15:27:49.420 xcodebuild[48502:2198169] [MT] DTDKRemoteDeviceConnection: Failed to start Instruments daemon on device “d35067#####a0071”: Error Domain=com.apple.dtdevicekit Code=-402653083 "Xcode encountered an error" UserInfo={NSLocalizedFailureReason=Could not connect to the device., com.apple.dtdevicekit.stacktrace=(
[Xcode] 	0   DTDeviceKitBase                     0x000000011f876047 DTDKCreateNSError + 109
[Xcode] 	1   DTDeviceKitBase                     0x000000011f876749 DTDK_AMDErrorToNSError + 792
[Xcode] 	2   DTDeviceKitBase                     0x000000011f88766c __63-[DTDKRemoteDeviceConnection startFirstServiceOf:unlockKeybag:]_block_invoke + 301
[Xcode] 	3   DTDeviceKitBase                     0x000000011f886e3b __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_3 + 22
[Xcode] 	4   DTDeviceKitBase                     0x000000011f878abf __DTDKExecuteInSession_block_invoke_2 + 35
[Xcode] 	5   DTDeviceKitBase                     0x000000011f877ef3 __DTDKExecuteWithConnection_block_invoke_2 + 473
[Xcode] 	6   DTDeviceKitBase                     0x000000011f877cf1 __DTDKExecuteWithConnection_block_invoke + 106
[Xcode] 	7   libdispatch.dylib                   0x00007fff5d48b63d _dispatch_client_callout + 8
[Xcode] 	8   libdispatch.dylib                   0x00007fff5d497478 _dispatch_sync_invoke_and_complete_recurse + 65
[Xcode] 	9   libdispatch.dylib                   0x00007fff5d496fe6 _dispatch_sync_f_slow + 195
[Xcode] 	10  DVTFoundation                       0x000000010fa42c60 DVTDispatchBarrierSync + 208
[Xcode] 	11  DVTFoundation                       0x000000010fa1a088 -[DVTDispatchLock performLockedBlock:] + 64
[Xcode] 	12  DTDeviceKitBase                     0x000000011f877bf2 DTDKExecuteWithConnection + 226
[Xcode] 	13  DTDeviceKitBase                     0x000000011f878929 DTDKExecuteInSession + 376
[Xcode] 	14  DTDeviceKitBase                     0x000000011f886d70 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_2 + 112
[Xcode] 	15  DVTFoundation                       0x000000010fa409ca __DVT_CALLING_CLIENT_BLOCK__ + 7
[Xcode] 	16  DVTFoundation                       0x000000010fa420a2 __DVTDispatchAsync_block_invoke + 809
[Xcode] 	17  libdispatch.dylib                   0x00007fff5d48a5f8 _dispatch_call_block_and_release + 12
[Xcode] 	18  libdispatch.dylib                   0x00007fff5d48b63d _dispatch_client_callout + 8
[Xcode] 	19  libdispatch.dylib                   0x00007fff5d4918e0 _dispatch_lane_serial_drain + 602
[Xcode] 	20  libdispatch.dylib                   0x00007fff5d492396 _dispatch_lane_invoke + 385
[Xcode] 	21  libdispatch.dylib                   0x00007fff5d49a6ed _dispatch_workloop_worker_thread + 598
[Xcode] 	22  libsystem_pthread.dylib             0x00007fff5d6c5611 _pthread_wqthread + 421
[Xcode] 	23  libsystem_pthread.dylib             0x00007fff5d6c53fd start_wqthread + 13
[Xcode] ), DVTRadarComponentKey=487927, NSLocalizedDescription=Xcode encountered an error}
[Xcode] 
[Xcode] 2019-10-24 15:27:49.423 xcodebuild[48502:2198169] [MT] IDETestOperationsObserverDebug: 0.461 elapsed -- Testing started completed.
[Xcode] 2019-10-24 15:27:49.423 xcodebuild[48502:2198169] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
[Xcode] 2019-10-24 15:27:49.423 xcodebuild[48502:2198169] [MT] IDETestOperationsObserverDebug: 0.461 sec, +0.461 sec -- end
[Xcode] 
[Xcode] 
[Xcode] 
[Xcode] *** If you believe this error represents a bug, please attach the result bundle at /Users/###/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz/Logs/Test/Test-WebDriverAgentRunner-2019.10.24_15-27-47--0400.xcresult
[Xcode] 
[Xcode] 
[Xcode] 
[Xcode] Test session results, code coverage, and logs:
[Xcode] 	/Users/####/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz/Logs/Test/Test-WebDriverAgentRunner-2019.10.24_15-27-47--0400.xcresult
[Xcode] 
[Xcode] 
[Xcode] Testing failed:
[Xcode] 	WebDriverAgentRunner:
[Xcode] 		WebDriverAgentRunner-Runner.app encountered an error (Failed to establish communication with the test runner. (Underlying error: Unable to connect to test manager on d3506727####0071. (Underlying error: Could not connect to the device.)))
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[Xcode] Testing started on 'iPhone'
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[XCUITest] Launching WebDriverAgent on the device
[WebDriverAgent] Fetching dependencies
[WebDriverAgent] Dependencies up-to-date
[XCUITest] Killing running processes 'xcodebuild.*d3506727ae53d74e5a8e59fac3b86198ccaa0071' for the device d3506727ae53d74e5a8e59fac3b86198ccaa0071...
[XCUITest] 'pgrep -ifn xcodebuild.*d3506727ae53d74e5a8e59fac3b86198ccaa0071' didn't detect any matching processes. Return code: 1
[XCUITest] Successfully reset '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj/project.pbxproj' with bundle id 'com.facebook.WebDriverAgentRunner'
[XCUITest] Successfully updated '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj/project.pbxproj' with bundle id 'com.test.webdriveragent'
[XCUITest] Using Xcode configuration file: '/var/folders/94/0pm75_gd0bd76k_5xz5d_jy80000gn/T/2019924-48460-kfiqtk.5s1h/appium-temp.xcconfig'
[XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=d3506727ae53d74e5a8e59fac3b86198ccaa0071 IPHONEOS_DEPLOYMENT_TARGET=11.4 -xcconfig /var/folders/94/0pm75_gd0bd76k_5xz5d_jy80000gn/T/2019924-48460-kfiqtk.5s1h/appium-temp.xcconfig GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-webdriveragent'
[XCUITest] Output from xcodebuild will only be logged if any errors are present there. To change this, use 'showXcodeLog' desired capability
[XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@d3506...] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@d3506...] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@d3506...] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@d3506...] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[XCUITest] Log file for xcodebuild test: /Users/#####/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz/Logs/Test/Test-WebDriverAgentRunner-2019.10.24_15-27-51--0400.xcresult/Staging/2_Test/Diagnostics/WebDriverAgentRunner-CFAC8CB5-3945-4EBE-BCD2-62CF7865D478/WebDriverAgentRunner-945B81B4-5D79-4F2D-BB1A-D1E78515B321/Session-WebDriverAgentRunner-2019-10-24_152751-wJHilJ.log
[Xcode] 2019-10-24 15:27:52.053 xcodebuild[48514:2198424] [MT] IDETestOperationsObserverDebug: (243F9FE1-5574-401A-B26B-4D8634993166) Failed to make test runner session:
[Xcode] Error Domain=com.apple.dt.xctest.error Code=9 "Unable to connect to test manager on d3506727ae53d74e5a8e59fac3b86198ccaa0071" UserInfo={NSLocalizedDescription=Unable to connect to test manager on d3506727ae53d74e5a8e59fac3b86198ccaa0071, NSUnderlyingError=0x7ffe0c17ce80 {Error Domain=XCTMobileDeviceFramework Code=101 "Could not connect to the device." UserInfo={NSLocalizedDescription=Could not connect to the device.}}}
[Xcode] 
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@d3506...] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[Xcode] 2019-10-24 15:27:52.335 xcodebuild[48514:2198424] [MT] DTDKRemoteDeviceConnection: Failed to start Instruments daemon on device “d3506727ae53d74e5a8e59fac3b86198ccaa0071”: Error Domain=com.apple.dtdevicekit Code=-402653083 "Xcode encountered an error" UserInfo={NSLocalizedFailureReason=Could not connect to the device., com.apple.dtdevicekit.stacktrace=(

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
This seems to be a [problem](https://stackoverflow.com/questions/48158225/xcode-9-test-target-x-encountered-an-error-unable-to-connect-to-test-manager) with the device

**Comment by dragon11111** [comment]
Thank you Mykola! Now it is working fine:D

**Comment by stidch** [comment]
@dragon11111 what was the problem finally?

**Comment by Juice007** [comment]
Restart my iPhone works
