### ISSUE TITLE
By default fullRest was set to true on real device when only bundleId was provided

### ISSUE THREAD

**Issue by sjrjanardhana** [appium/appium#13480]
## The problem

I was trying to launch pre-installed app using below capabilities
{
        "platformName": "iOS",
        "platformVersion": "12.2",
        "browserName": "",
        "deviceName": "iPhone",
        "automationName": "XCUITest",
        "bundleId": "com.xxxxx.xxxxx"
 }

but following capabilities have been passed to appium server

[BaseDriver] The capabilities ["udid","fullReset"] are not standard capabilities and should have an extension prefix
[Appium] Appium v1.14.0 creating new XCUITestDriver (v2.116.3) session
[Appium] Capabilities:
[Appium]   platformName: iOS
[Appium]   browserName: 
[Appium]   udid: 356ba906dd8158a9fa418c94e5f7efbd3b03b4da
[Appium]   fullReset: true
[Appium]   platformVersion: 12.2
[Appium]   deviceName: iPhone
[Appium]   automationName: XCUITest
[Appium]   bundleId: com.xxxxx.xxxxx

Due to this application was getting uninstalled and fails launch app as there is no app with bundleId available

[debug] [BaseDriver] W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP desired capabilities {"udid":"356ba906dd8158a9fa... were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"platformNa...
[BaseDriver] Session created with session id: 095c1f25-236c-47f5-95ec-0434aa5f9866
[debug] [XCUITest] Current user: 'janardhana'
[debug] [XCUITest] Available devices: 356ba906dd8158a9fa418c94e5f7efbd3b03b4da
[debug] [XCUITest] Creating iDevice object with udid '356ba906dd8158a9fa418c94e5f7efbd3b03b4da'
[XCUITest] Determining device to run tests on: udid: '356ba906dd8158a9fa418c94e5f7efbd3b03b4da', real device: true
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1571840840885 (19:57:20 GMT+0530 (India Standard Time))
[debug] [BaseDriver] Event 'appConfigured' logged at 1571840840885 (19:57:20 GMT+0530 (India Standard Time))
[debug] [BaseDriver] Event 'resetStarted' logged at 1571840840885 (19:57:20 GMT+0530 (India Standard Time))
[debug] [XCUITest] Reset: running ios real device reset flow
[debug] [XCUITest] Reset: fullReset requested. Will try to uninstall the app 'com.xxxxx.xxxxxx'.
[debug] [XCUITest] Calling: 'ios-deploy --exists --id 356ba906dd8158a9fa418c94e5f7efbd3b03b4da --bundle_id com.xxxxx.xxxxx'
[debug] [XCUITest] Stdout: '[....] Waiting for iOS device to be connected
[debug] [XCUITest] [....] Using 356ba906dd8158a9fa418c94e5f7efbd3b03b4da (J97AP, iPad mini 4 (GSM), iphoneos, arm64) a.k.a. 'dayakar’s iPad (4)'.
[debug] [XCUITest] true
[debug] [XCUITest] '
[debug] [XCUITest] Reset: removed 'com.xxxxx.xxxxx'
[debug] [BaseDriver] Event 'resetComplete' logged at 1571840841808 (19:57:21 GMT+0530 (India Standard Time))
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Starting iOS device log capture with: 'idevicesyslog'
[debug] [XCUITest] Crash reports root '/Users/janardhana/Library/Logs/CrashReporter/MobileDevice/dayakar’s iPad (4)' does not exist. Got nothing to gather.
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1571840842133 (19:57:22 GMT+0530 (India Standard Time))
[XCUITest] Setting up real device
[debug] [XCUITest] Calling: 'ios-deploy --exists --id 356ba906dd8158a9fa418c94e5f7efbd3b03b4da --bundle_id com.xxxxx.xxxxx
[XCUITest] Error: App with bundle identifier 'com.xxxxx.xxxxx' unknown
[XCUITest]     at Object.wrappedLogger.errorAndThrow (/Users/janardhana/.nvm/versions/node/v11.10.0/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[XCUITest]     at XCUITestDriver.errorAndThrow [as start] (/Users/janardhana/.nvm/versions/node/v11.10.0/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:416:13)
[XCUITest] Error: App with bundle identifier 'com.xxxxxx.xxxxxx' unknown
[XCUITest]     at Object.wrappedLogger.errorAndThrow (/Users/janardhana/.nvm/versions/node/v11.10.0/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[XCUITest]     at XCUITestDriver.errorAndThrow [as start] (/Users/janardhana/.nvm/versions/node/v11.10.0/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:416:13)
[debug] [iOSLog] Stopping iOS log capture
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1571840842761 (19:57:22 GMT+0530 (India Standard Time))
[debug] [W3C] Encountered internal error running command: Error: App with bundle identifier 'com.xxxxx.xxxxxx' unknown
[debug] [W3C]     at Object.wrappedLogger.errorAndThrow (/Users/janardhana/.nvm/versions/node/v11.10.0/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[debug] [W3C]     at XCUITestDriver.errorAndThrow [as start] (/Users/janardhana/.nvm/versions/node/v11.10.0/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:416:13)

## Environment

* Appium version v1.14.0
* Desktop OS/version used to run Appium:Mac
* Node.js version (unless using Appium.app|exe): v11.10.0
* Npm or Yarn package manager:
* Mobile platform/version under test:iOS 12.2
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

**Comment by KazuCocoa** [comment]
hm... it's weird. The below line, too.

> [BaseDriver] The capabilities ["udid","fullReset"] are not standard capabilities and should have an extension prefix


Could you share the full log, especially the above of:

```
[BaseDriver] The capabilities ["udid","fullReset"] are not standard capabilities and should have an extension prefix
[Appium] Appium v1.14.0 creating new XCUITestDriver (v2.116.3) session
[Appium] Capabilities:
[Appium] platformName: iOS
```

?

**Comment by sjrjanardhana** [comment]
[HTTP] {"capabilities":{"firstMatch":[{"platformName":"iOS","appium:platformVersion":"12.2","browserName":"","appium:deviceName":"iPhone","appium:automationName":"XCUITest","appium:bundleId":"com.xxxx.xxxxx"}]},"desiredCapabilities":{"platformName":"iOS","platformVersion":"12.2","browserName":"","deviceName":"iPhone","automationName":"XCUITest","bundleId":"com.xxxx.xxxxx"}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","platformVersion":"12.2","browserName":"","deviceName":"iPhone","automationName":"XCUITest","bundleId":"com.xxxx.xxxxx"},null,{"firstMatch":[{"platformName":"iOS","appium:platformVersion":"12.2","browserName":"","appium:deviceName":"iPhone","appium:automationName":"XCUITest","appium:bundleId":"com.xxxx.xxxxx"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1571844290821 (20:54:50 GMT+0530 (India Standard Time))
[BaseDriver] The capabilities ["udid","fullReset"] are not standard capabilities and should have an extension prefix
[Appium] Appium v1.14.0 creating new XCUITestDriver (v2.116.3) session
[Appium] Capabilities:
[Appium]   platformName: iOS
[Appium]   browserName: 
[Appium]   udid: 5d6891d87b1d70d23414096d05e9b93ee7be9326
[Appium]   fullReset: true
[Appium]   platformVersion: 12.2
[Appium]   deviceName: iPhone
[Appium]   automationName: XCUITest
[Appium]   bundleId: com.xxxx.xxxxx
[debug] [BaseDriver] W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP desired capabilities {"udid":"5d6891d87b1d70d234... were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"platformNa...
[BaseDriver] Session created with session id: a8de0cc3-81f3-47c3-82fa-2978fbe1c580
[debug] [XCUITest] Current user: 'janardhana'
[debug] [XCUITest] Available devices: 5d6891d87b1d70d23414096d05e9b93ee7be9326
[debug] [XCUITest] Creating iDevice object with udid '5d6891d87b1d70d23414096d05e9b93ee7be9326'
[XCUITest] Determining device to run tests on: udid: '5d6891d87b1d70d23414096d05e9b93ee7be9326', real device: true
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1571844290843 (20:54:50 GMT+0530 (India Standard Time))
[debug] [BaseDriver] Event 'appConfigured' logged at 1571844290843 (20:54:50 GMT+0530 (India Standard Time))
[debug] [BaseDriver] Event 'resetStarted' logged at 1571844290843 (20:54:50 GMT+0530 (India Standard Time))
[debug] [XCUITest] Reset: running ios real device reset flow
[debug] [XCUITest] Reset: fullReset requested. Will try to uninstall the app 'com.xxxx.xxxxx'.
[debug] [XCUITest] Calling: 'ios-deploy --exists --id 5d6891d87b1d70d23414096d05e9b93ee7be9326 --bundle_id com.xxxx.xxxxx'
[debug] [XCUITest] Stdout: '[....] Waiting for iOS device to be connected
[debug] [XCUITest] [....] Using 5d6891d87b1d70d23414096d05e9b93ee7be9326 (D22AP, D22AP, uknownos, unkarch) a.k.a. 'iPhone'.
[debug] [XCUITest] true
[debug] [XCUITest] '
[debug] [XCUITest] Reset: removed 'com.xxxx.xxxxx'
[debug] [BaseDriver] Event 'resetComplete' logged at 1571844291722 (20:54:51 GMT+0530 (India Standard Time))
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Starting iOS device log capture with: 'idevicesyslog'
[debug] [XCUITest] Crash reports root '/Users/janardhana/Library/Logs/CrashReporter/MobileDevice/iPhone' does not exist. Got nothing to gather.
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1571844291825 (20:54:51 GMT+0530 (India Standard Time))
[XCUITest] Setting up real device
[debug] [XCUITest] Calling: 'ios-deploy --exists --id 5d6891d87b1d70d23414096d05e9b93ee7be9326 --bundle_id com.xxxx.xxxxx'
[XCUITest] Error: App with bundle identifier 'com.xxxx.xxxxx' unknown
[XCUITest]     at Object.wrappedLogger.errorAndThrow (/Users/janardhana/.nvm/versions/node/v11.10.0/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[XCUITest]     at XCUITestDriver.errorAndThrow [as start] (/Users/janardhana/.nvm/versions/node/v11.10.0/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:416:13)
[XCUITest] Error: App with bundle identifier 'com.xxxx.xxxxx' unknown
[XCUITest]     at Object.wrappedLogger.errorAndThrow (/Users/janardhana/.nvm/versions/node/v11.10.0/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[XCUITest]     at XCUITestDriver.errorAndThrow [as start] (/Users/janardhana/.nvm/versions/node/v11.10.0/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:416:13)
[debug] [iOSLog] Stopping iOS log capture
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1571844292137 (20:54:52 GMT+0530 (India Standard Time))
[debug] [W3C] Encountered internal error running command: Error: App with bundle identifier 'com.xxxx.xxxxx' unknown
[debug] [W3C]     at Object.wrappedLogger.errorAndThrow (/Users/janardhana/.nvm/versions/node/v11.10.0/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[debug] [W3C]     at XCUITestDriver.errorAndThrow [as start] (/Users/janardhana/.nvm/versions/node/v11.10.0/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:416:13)
[HTTP] <-- POST /wd/hub/session 500 1317 ms - 687
[HTTP] 
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.14.0"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 68
[HTTP] 
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.14.0"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 68

**Comment by KazuCocoa** [comment]
ah, did you provide `--full-reset` and `--udid`  as server arguments?
http://appium.io/docs/en/writing-running-appium/server-args/

Then, such `[BaseDriver] The capabilities ["udid","fullReset"] are not standard capabilities and should have an extension prefix` error appears.

**Comment by mykola-mokhnach** [comment]
yep, fullReset uninstalls the app by default and setting bundleId only expects the app to be already installed on the device when the session starts, so the described behaviour is expected.

**Comment by sjrjanardhana** [comment]
Got it thanks
