### ISSUE TITLE
Cannot Get Page Source

### ISSUE THREAD

**Issue by ajschwieterman** [appium/appium#13485]
## The problem

Appium returns an error when attempting to get the page source of the tested app.  Appium is able to launch the app on the phone, but cannot access any of the elements on the page.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.15.1
* Mobile platform/version under test: Android v6.0.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

https://gist.github.com/ajschwieterman/b10a0b8253d2fc5779295f74a8ce310a

## Code To Reproduce Issue [ Good To Have ]

driver.getPageSource();

**Comment by mykola-mokhnach** [comment]
> 2019-10-24 18:02:10:851 - [debug] [35m[WD Proxy][39m Got response with status 500: {"sessionId":"4ea530b1-76a8-43ea-9b09-9c845f926bcb","value":{"error":"unknown error","message":"Timed out after 10000 milliseconds waiting for root AccessibilityNodeInfo","stacktrace":"io.appium.uiautomator2.common.exceptions.UiAutomator2Exception: Timed out after 10000 milliseconds waiting for root AccessibilityNodeInfo\n\tat io.appium.uiautomator2.utils.AXWindowHelpers.getActiveWindowRoot(AXWindowHelpers.java:78)\n\tat io.appium.uiautomator2.utils.AXWindowHelpers.getCachedWindowRoots(AXWindowHelpers.java:114)\n\tat io.appium.uiautomator2.core.AccessibilityNodeInfoDumper.toStream(AccessibilityNodeInfoDumper.java:169)\n\tat io.appium.uiautomator2.core.AccessibilityNodeInfoDumper.dumpToXml(AccessibilityNodeInfoDumper.java:189)\n\tat io.appium.uiautomator2.handler.Source.safeHandle(Source.java:38)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:38)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:252)\n\tat io.appium.uiautomator...

Unfortunately this error is coming from UIAutomator2 and we cannot do nothing to change that on Appium side

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
