### ISSUE TITLE
Could not get Xcode version. /Library/Developer/Info.plist does not exist on disk.

### ISSUE THREAD

**Issue by SeakyLuo** [appium/appium#13498]
## The problem

> selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not determine iOS SDK version: Could not get Xcode version. /Library/Developer/Info.plist does not exist on disk.

## Environment

Mac OS 10.14.4
Python 3.8
Appium 1.14
Xcode 11.1(11A1027)

## Details

I looked at this post: https://stackoverflow.com/questions/32724616/appium-error-could-not-get-xcode-version, tried the following code and restarted Appium but it is still not working.

`sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`

And I also have xcode installed on my Mac but when I run appium doctor it says no. Would this be a problem?

**Comment by KazuCocoa** [comment]
What the result of appium-doctor?
It checks `xcode-select -p` and the CLI tool with `xcrun simctl help`.

**Comment by SeakyLuo** [comment]
Never mind I think the above code works. I guess I just need to wait for a while.
