### ISSUE TITLE
iOS: Appium consumes large amount of disk space in /var/folders location

### ISSUE THREAD

**Issue by lidongdabie** [appium/appium#13493]
We use Appium to run our cucumber tests on iPhone devices on our CI (Jenkins).

We’ve noticed, that while running, the Appium (node process in particular) seems to write HUGE amounts of disk space (writing something to /var directory).

It results into the fact , that the Mac eventually (in 1-2 days) runs out of disc space (which was ~100 Gb after the Mac was restarted).

Does anyone encounter the same problem and/or knows the solution for it ?

The Appium server version is 1.9.0

P.S. we also tried the clearSystemFiles => true capability and it seems that it doesn’t help

Would be glad to have any feedback,
Thanks in advance

**Comment by mykola-mokhnach** [comment]
- Appium 1.9 is out off date. Please use the most recent server version
- How do you know the temp files are created by Appium? These can be created by other binaries used for automation (I saw such problems with iOS Simulators, for example). 

Long story short - without the analysis of the actual data that occupies disk space (which files it contains, what is the pattern there)  it is impossible to do any assumptions.

**Comment by lidongdabie** [comment]
our case is about the “/var/folders/{floody_dir}*” directory that gets flooded and has dynamic name, rather than DerivedData, so not so easy to clean automatically each time.
For example ：
![20191026110348](https://user-images.githubusercontent.com/20069525/67613471-835a9f00-f7e0-11e9-8d13-d481790b83ab.jpg)
<img width="1128" alt="7015728C-74FF-4A7C-A4C9-C754D4154DA3" src="https://user-images.githubusercontent.com/20069525/67613511-f95f0600-f7e0-11e9-8c71-f1bd97d76570.png">
I think the space is not released after the process occupation folder is deleted

**Comment by lidongdabie** [comment]
Process space has been increasing 
<img width="785" alt="1BE35D25-2D8F-475E-8CDB-1BFC432B863E" src="https://user-images.githubusercontent.com/20069525/67613622-265fe880-f7e2-11e9-973c-b046717d968b.png">

**Comment by lidongdabie** [comment]
![20191026113902](https://user-images.githubusercontent.com/20069525/67613874-49d86280-f7e5-11e9-81ba-fefe4d6d19e5.jpg)

**Comment by mykola-mokhnach** [comment]
Newer Appium versions properly cache extracted apps, so the problem shouldn't be there after upgrade

**Comment by mykola-mokhnach** [comment]
Regarding derived data folder - it is recommended to set a unique path to it explicitly in capabilities for each parallel instance.

**Comment by lidongdabie** [comment]
We really appreciate your help : )
