### ISSUE TITLE
Could not create simulator with name 'appiumTest-33C73E50-54EC-4FAD-BA3E-8C2EC2231AEA-iPad Pro'

### ISSUE THREAD

**Issue by SeakyLuo** [appium/appium#13499]
## The problem

> selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not create simulator with name 'appiumTest-33C73E50-54EC-4FAD-BA3E-8C2EC2231AEA-iPad Pro', device type id 'iPad Pro' and runtime id 'com.apple.CoreSimulator.SimRuntime.iOS-13-1'. Reason: 'simctl error running 'create': Invalid device type: iPad Pro'

## Environment

Mac OS 10.14.4
Python 3.8
Appium 1.14
Xcode 11.1(11A1027)

## Capabilities
```
{
    "platformName": "iOS",
    "platformVersion": "13.1",
    "deviceName": "iPad Pro",
    "automationName": "XCUITest",
    "browserName": "Safari"
}
```

This is my device return by `instruments -s devices`: Seaky's iPad Pro (11) (13.1.3) [00008027-000868310A39002E]. It is a real device.

I have also tried `Seaky's iPad Pro`, `iPad 8`, and the full name. But none of them is good.

**Comment by SeakyLuo** [comment]
Am I missing udid?

**Comment by SeakyLuo** [comment]
Are "xcodeOrgId" and "xcodeSigningId" mandatory?

**Comment by aduait** [comment]
Can you tell what changes you did ? What deviceName you provided for it to work ?

**Comment by deremakif** [comment]
> Can you tell what changes you did ? What deviceName you provided for it to work ?


You will run **instruments -s devices** in your command line. Get a list of simulator like :
...
iPhone 8 Plus (13.6) [0C674E19-79A6-4526-B030-3C2DB8DB486E] (Simulator)
iPhone SE (2nd generation) (13.5) [477F8822-48D0-4D74-A651-93A684020AE5] (Simulator)
...

And set "udid" of related deviceName like:

    capabilities.setCapability("deviceName", "iPhone SE");
    capabilities.setCapability("udid", "477F8822-48D0-4D74-A651-93A684020AE5");

or like :

{
    "platformName": "iOS",
    "platformVersion": "13.1",
    "deviceName": "iPhone SE",
     "udid": "477F8822-48D0-4D74-A651-93A684020AE5"
    "automationName": "XCUITest",
    "browserName": "Safari"
}

**Comment by ptmkenny** [comment]
For newer versions of Xcode, instead of `instruments -s devices`, use  `xctrace list devices`.
