### ISSUE TITLE
Keep the original APK when it is signed with non-default certificate

### ISSUE THREAD

**Issue by nguyenvulong** [appium/appium#13502]
## The problem

For APK that _is signed with non-default certificate_, I am aware that Appium will re-sign the APK . This step directly modifies the APK in-place. 
Is there any option that makes Appium copy the APK to other location e.g, **/temp** directory, then modifies it there instead of repackaging the APK directly?
Reason: I want to keep the original APK intact.

Update: I added my comment to elaborate more about the option **noSign**

what are the limitations if I use **noSign** option instead of re-signing the APK? As far as I know it may limit the interaction between appium server and the app under test, but not sure what are the limitations exactly.

Also, in the [documentation ](http://appium.io/docs/en/writing-running-appium/caps/#uiautomator2-only)it said that **noSign** option can only work with UiAutomator, turned out it worked with UiAutomator2 too - I have just tested the option **noSign** with the app.
**Update:** I am aware of this answer by bootstraponline, he also stated that noSign option would not work with UiAutomator2.  https://github.com/appium/appium/issues/5969

## Environment

appium version: 1.15.1
OS version: Ubuntu 18.04
Node.js version: v10.17.0
NPM version: 6.11.3
Mobile platform: Android 9.0

Thank you.

**Comment by KazuCocoa** [comment]
No such copying feature for now.
`noSign` https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md keeps your sign.

**Comment by nguyenvulong** [comment]
Thanks KazuCocoa, do you know what are the limitations if I use **noSign** option instead of re-signing the APK? As far as I know it may limit the interaction between appium server and the app under test, but not sure what are the limitations exactly.


Also, in the documentation it said that **noSign** option can only work with UiAutomator, turned out it worked with UiAutomator2 too!

![image](https://user-images.githubusercontent.com/1311412/67730825-94eab380-fa39-11e9-820b-efbc4c2d520a.png)

**Comment by KazuCocoa** [comment]
noSign should work for almost commands of UIA2 since we cannot re-sign for existing apps, but UIA2 can handle them. I ran tests with noSign option before.

Appium Espresso driver requires the signing.

**Comment by nguyenvulong** [comment]
I see, looks like the documentation needs to be updated then

**Comment by mykola-mokhnach** [comment]
Since v 1.17 Appium will keep the original app certificate by default if it it is valid. Resigning will only happen if the app is not signed or its certificate is damaged
