### ISSUE TITLE
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"::1","port":8200}

### ISSUE THREAD

**Issue by RiarioRovere** [appium/appium#13509]
## The problem

When your localhost is ipv6 or both ipv4 and ipv6 you would experience connection refused.
ADB is ipv4 only and listen on 8200 port while UIAutomator resolved localhost:8200 as ::1:8200. Thats why UIautomator2 gets "ECONNREFUSED".

root@emulators-1:/# netstat -tl
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 **localhost:8200**          0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:5900            0.0.0.0:*               LISTEN
tcp        0      0 localhost:5037          0.0.0.0:*               LISTEN
tcp        0      0 localhost:5554          0.0.0.0:*               LISTEN
tcp        0      0 localhost:5555          0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:6099            0.0.0.0:*               LISTEN
tcp6       0      0 [::]:4444               [::]:*                  LISTEN
tcp6       0      0 [::]:5900               [::]:*                  LISTEN
tcp6       0      0 localhost:5555          [::]:*                  LISTEN
tcp6       0      0 [::]:6099               [::]:*                  LISTEN
tcp6       0      0 [::]:22                 [::]:*                  LISTEN

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.0
* Last Appium version that did not exhibit the issue (if applicable): not existed
* Desktop OS/version used to run Appium: ubuntu: Ubuntu 18.04.3 LTS
* Node.js version (unless using Appium.app|exe): v10.17.0
* Npm or Yarn package manager: 6.11.3
* Mobile platform/version under test: android
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: CLI

## Details

My host is ipv6 only, so I cant disable ipv6 to solve this problem.

## Link to Appium logs

https://gist.github.com/RiarioRovere/545615fa533823c9e4b99020d8f70b3c

[paste this for better search]
2019-10-29 15:23:00:783 - [debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8202/wd/hub/status] with no body
2019-10-29 15:23:00:787 - [WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"::1","port":8202}
2019-10-29 15:23:01:789 - [debug] [WD Proxy] Matched '/status' to command name 'getStatus'

## Code To Reproduce Issue [ Good To Have ]

```
appium -a :: -p 4444
be sure your localhost resolved also as ::1
root@emulators-1# nslookup localhost
Server: hidden
Address:	hidden

Non-authoritative answer:
Name:	localhost
Address: 127.0.0.1
Name:	localhost
Address: ::1

```

appium with emulator are running on remote ipv6 host. 
When all setup placed locally in my Mac OS everything works perfect!

**Comment by mykola-mokhnach** [comment]
Try to set either `host` or `remoteAdbHost` capabilities to `127.0.0.1`

**Comment by RiarioRovere** [comment]
If I correctly understand you, host is '--address' option? If so nothing is changed 
`appium --address '127.0.0.1' -p 4444`

**Comment by RiarioRovere** [comment]
It helps, thank you! What do you think about making `127.0.0.1` default value? Because `127.0.0.1` works in all cases when 'localhost' value works, but also on ipv6 hosts.

**Comment by mykola-mokhnach** [comment]
Changed the default value in https://github.com/appium/appium-uiautomator2-driver/pull/343

**Comment by mykola-mokhnach** [comment]
The fix has been published to beta
