### ISSUE TITLE
      org.openqa.selenium.StaleElementReferenceException: The element 'By.clazz: android.widget.ProgressBar' does not exist in DOM anymore

### ISSUE THREAD

**Issue by ddmonteiro** [appium/appium#13505]
## The problem

As title explains the current version of appium 1.15 throws this exception in many scenarios of the code, either when is waiting for the object to load or catching the elements of the screen (check code to reproduce issue below)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.1.5.1
* Last Appium version that did not exhibit the issue (if applicable): 1.13
* Desktop OS/version used to run Appium: MacOs Mojave
* Node.js version (unless using Appium.app|exe): 10.11.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

I need to know if either this is gonna be fixed, or is it a new Exception that needs to be handled in the code?

## Link to Appium logs

 [GIST](https://gist.github.com/ddmonteiro/62f2f34ec5075008b1ccd9edadf9b408) 

## Code To Reproduce Issue [ Good To Have ]

`    /*
     * Automation method for checking element displayed
     *
     * @param driver AppiumDriver
     *
     * @param element MobileElement of element
     */
    public boolean isElementDisplayed(AppiumDriver<MobileElement> appiumDriver, MobileElement Element) {
        try {
            WebDriverWait wait = new WebDriverWait(appiumDriver, DEFAULT_TIMEOUT);
            wait.until(ExpectedConditions.visibilityOf(Element));
            return true;
        } catch (TimeoutException e) {
            return false;
        } catch (NoSuchElementException e) {
            return false;
        }
    }`

`                elements = driver.findElementsByClassName("android.widget.TextView");
                for (int i = 0; i < elements.size(); i++) {
                    if (elements.get(i).getText().equals(text)) {
                        displayElementAndMessage(elements.get(i), " element with" + text + " Found");
                        elements.get(i).click();
                        elementWithTextFound = true;
                        return elementWithTextFound;
                    }
                }`

**Comment by mykola-mokhnach** [comment]
This is a normal exception, where UIA2 cannot locate the cached element, because the reference to it has been invalidated. You must call findElement each time you want to access such entity instead of iterating through the list of cached WebElement entities.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by Narensai03** [comment]
selenium.common.exceptions.StaleElementReferenceException: Message: Cached elements 'By.clazz: android.widget.TextView' do not exist in DOM anymore i am facing this issue
