### ISSUE TITLE
Not able to execute tests using appium ui-automator driver with API version 28 or higher

### ISSUE THREAD

**Issue by lakshmi-236** [appium/appium#13501]
The problem
hi ,
i am running selenium tests using Emulator with appium ui-automator 2 driver. upto api version 27 tests are running without issues.
but when i upgraded it to api 28 tests are not running. Below is the capabilities used

capabilities: {
'chromeOptions': {
args: [
'incognito',
'disable-extensions',
]
},
browserName: '',
app: path.join(__dirname,'../../../platforms/android/app/build/outputs/apk/debug/app-debug.apk'),
appActivity: '.MainActivity',
automationName: 'uiautomator2',
platformName: 'Android',
platformVersion: '10',
deviceName: 'Android Emulator',
autoWebview: true,
autoWebviewTimeout: 20000,
autoAcceptAlerts: true,
deviceReadyTimeout: 120,
avd: 'PIxel_2_API_29',
avdArgs: '-dns-server 8.8.8.8,8.8.4.4',
noReset: false
}

Environment
Appium version (or git revision) that exhibits the issue:1.14.0
Last Appium version that did not exhibit the issue (if applicable):
Desktop OS/version used to run Appium: Windows 10
Node.js version (unless using Appium.app|exe):10.14.0
Npm or Yarn package manager: npm(latest)
Mobile platform/version under test: API 29
Real device or emulator/simulator: emulator
Appium CLI or Appium.app|exe: Appium.exe
Details
i am having a test automation framework with protractor . We are using emulator for running tests. If API version of emulator is <28 tests are executing. if it is higher version, not even login to application is happening.
Link to Appium logs
https://gist.github.com/lakshmi-236/d3973150413ca91da2d88df31b0674ec

**Comment by mykola-mokhnach** [comment]
> [debug] [WD Proxy] Matched '/session' to command name 'createSession'
> [debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"capabilities":{"alwaysMatch":{"goog:chromeOptions":{"androidPackage":"com.apihealthcare.mobileworkforce","androidUseRunningApp":true,"args":["incognito","disable-extensions"],"androidDeviceSerial":"emulator-5554"},"goog:loggingPrefs":{"browser":"ALL"}}}}
> [debug] [Chromedriver] Webview version: 'Chrome/77.0.3865.116'
> [Appium] Received SIGINT - shutting down
> [WD Proxy] Got an unexpected response with status undefined: {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}
> [Chromedriver] Failed to start Chromedriver session: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET
> [debug] [Instrumentation] The process has exited with code 3221225786
> [Chromedriver] Chromedriver exited unexpectedly with code 3221225786, signal null

It looks like chromedrievr freezes while string the session. Please attach the logcat output - it might contain more details.

**Comment by lakshmi-236** [comment]
https://gist.github.com/lakshmi-236/2ad04ea3109ea7e71631c93f4ee682a7

**Comment by mykola-mokhnach** [comment]
I don't observe any calls to chromedriver in the log above. Is it taken at the correct timestamp

**Comment by lakshmi-236** [comment]
this is the entire log while running test,
https://gist.github.com/lakshmi-236/b20ac869e680d2c51b21f49dc628387c

**Comment by mykola-mokhnach** [comment]
Something is still not ok with this log. Is the test running for 1 second? 
Have you tried to inspect the web view using Chrome remote debugger?

**Comment by lakshmi-236** [comment]
no, how to use that

**Comment by mykola-mokhnach** [comment]
> no, how to use that

Kindly use appium forum for howto questions

**Comment by mykola-mokhnach** [comment]
there's nothing more to do in this issue without the logs. Closing as incomplete
