### ISSUE TITLE
Application is corrupted when installed in iOS

### ISSUE THREAD

**Issue by anorimaki** [appium/appium#13515]
## The problem
The application installed by appium crashes because one of its resource files has been pushed to the device with 0 bytes.

## Environment
* Appium version (or git revision) that exhibits the issue: v1.16.0-beta.1 (REV 04a33cf08086a83f33c693ff1df8f5752cce6ce1)
* Desktop OS/version used to run Appium: MacOS
* Node.js version (unless using Appium.app|exe): v12.12.0
* Npm or Yarn package manager: 6.11.3
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: real device

## Details

Application files are pushed in the callback of the `fs.walkDir` method of the `appium-support` library. The callback execution of the last file sent to the device doesn't finish and the content of the file isn't transferred. This happens because the `end` event callback of the walker is executed and resolves the finalization promise before the file callback can end.

Pausing the `walker` stops to emmitting `data` events but not the `end`event (See [readable.pause()](https://nodejs.org/api/stream.html#stream_readable_pause)).

**Comment by mykola-mokhnach** [comment]
Thanks, this is a very good catch

**Comment by mykola-mokhnach** [comment]
The fix has been published
