### ISSUE TITLE
[iOS] The safari browser has crashed when creating new session with Appium 1.16.0-beta.1

### ISSUE THREAD

**Issue by nghiadhd** [appium/appium#13519]
## The problem

I fixed appium-webdriveragent that it can be launched on iOS 9.3.x & 10.x.
However, I got the issue that the Safari has crashed when the appium trying to connect into WebContent process

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0-beta.1 & 2.0 branch
* Last Appium version that did not exhibit the issue (if applicable): 1.15.1
* Desktop OS/version used to run Appium: macOS 10.14.6 (18G103)
* Node.js version (unless using Appium.app|exe): 10.11.0
* Npm or Yarn package manager: 6.4.1
* Mobile platform/version under test: iPhone 6 - 10.1
* Real device or emulator/simulator: realdevice
* Appium CLI or Appium.app|exe: appium cli

## Link to Appium logs

https://gist.github.com/nghiadhd/40b1243ffc79a5c29796345f29eb5e1c

**Comment by imurchie** [comment]
What sort of test run is the log above from? Is this the "loop while creating new session"?

**Comment by nghiadhd** [comment]
@imurchie the above log is from appium 1.16.0-beta.1. It means I just fetched code, npm install, did some modifications on appium-webdriveragent that it can run on iOS 10.
After that, I tried to fetch 2 modules appium-remote-debugger@6.3.0 & appium-ios-device@0.12.0 and see the issue has been resolved. I think we should close this ticket.
Regard to loop, I'll investigate and create new ones
