### ISSUE TITLE
Getting Bad app path though absolute app path was provided for iOS

### ISSUE THREAD

**Issue by sjrjanardhana** [appium/appium#13513]
## The problem

An unknown server-side error occurred while processing the command. Original error: Bad app: paths need to be absolute or an URL to a compressed file

## Environment

* Appium version (or git revision) that exhibits the issue:1.14.0
* Last Appium version that did not exhibit the issue (if applicable):Not tried
* Desktop OS/version used to run Appium:MAC 10.14.3
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:iOS
* Real device or emulator/simulator:Real Device
* Appium CLI or Appium.app|exe:CLI

## Details

I was trying to run some series of test, for each test the app does fullrest and install app and proceed for the test. but for some test it fails with above error, but i do0n't find same login appium server

## Link to Appium logs

[Appium] Welcome to Appium v1.14.0
[Appium] Non-default server args:
[Appium]   port: 1102
[Appium]   bootstrapPort: 1112
[Appium]   nodeconfig: /Users/janardhana/Desktop/BVT_TIP/DeviceCapabilities/iOS/iPad_jenkins.json
[Appium]   defaultCommandTimeout: 300
[Appium]   udid: 356ba906dd8158a9fa418c94e5f7efbd3b03b4da
[Appium]   fullReset: true
[Appium] Deprecated server args:
[Appium]   -U,--udid => --default-capabilities '{"udid":"356ba906dd8158a9fa418c94e5f7efbd3b03b4da"}'
[Appium]   --full-reset => --default-capabilities '{"fullReset":true}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   udid: 356ba906dd8158a9fa418c94e5f7efbd3b03b4da
[Appium]   fullReset: true
[debug] [Appium] Starting auto register thread for grid. Will try to register every 5000 ms.
[Appium] Appium REST http interface listener started on 0.0.0.0:1102
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.14.0"}}
[HTTP] <-- GET /wd/hub/status 200 5 ms - 68
[HTTP] 
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.14.0"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 68
[HTTP] 
[debug] [Appium] Appium successfully registered with the grid on http://10.160.148.125:4055
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.14.0"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 68
[HTTP] 
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.14.0"}}
[HTTP] <-- GET /wd/hub/status 200 2 ms - 68
[HTTP] 
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.14.0"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 68
[HTTP] 
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.14.0"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 68
[HTTP] 
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.14.0"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 68
[HTTP] 
[HTTP] --> POST /wd/hub/session
[HTTP] {"capabilities":{"firstMatch":[{"platformName":"iOS","appium:platformVersion":"12.2","browserName":"","appium:deviceName":"iPad_local","appium:automationName":"XCUITest","appium:app":"/Users/janardhana/Downloads/MediaFirst_cip.ipa"}]},"desiredCapabilities":{"platformName":"iOS","platformVersion":"12.2","browserName":"","deviceName":"iPad_local","automationName":"XCUITest","app":"/Users/janardhana/Downloads/MediaFirst_cip.ipa"}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","platformVersion":"12.2","browserName":"","deviceName":"iPad_local","automationName":"XCUITest","app":"/Users/janardhana/Downloads/MediaFirst_cip.ipa"},null,{"firstMatch":[{"platformName":"iOS","appium:platformVersion":"12.2","browserName":"","appium:deviceName":"iPad_local","appium:automationName":"XCUITest","appium:app":"/Users/janardhana/Downloads/MediaFirst_cip.ipa"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1572424420928 (14:03:40 GMT+0530 (India Standard Time))
[BaseDriver] The capabilities ["udid","fullReset"] are not standard capabilities and should have an extension prefix
[Appium] Appium v1.14.0 creating new XCUITestDriver (v2.116.3) session
[Appium] Capabilities:
[Appium]   platformName: iOS
[Appium]   browserName: 
[Appium]   udid: 356ba906dd8158a9fa418c94e5f7efbd3b03b4da
[Appium]   fullReset: true
[Appium]   platformVersion: 12.2
[Appium]   deviceName: iPad_local
[Appium]   automationName: XCUITest
[Appium]   app: /Users/janardhana/Downloads/MediaFirst_cip.ipa
[debug] [BaseDriver] W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP desired capabilities {"udid":"356ba906dd8158a9fa... were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"platformNa...
[BaseDriver] Session created with session id: 55981ad9-d3fb-4338-bb4a-284c7b6f81c9
[debug] [XCUITest] Current user: 'janardhana'
[debug] [XCUITest] Available devices: 356ba906dd8158a9fa418c94e5f7efbd3b03b4da
[debug] [XCUITest] Creating iDevice object with udid '356ba906dd8158a9fa418c94e5f7efbd3b03b4da'
[XCUITest] Determining device to run tests on: udid: '356ba906dd8158a9fa418c94e5f7efbd3b03b4da', real device: true
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1572424421498 (14:03:41 GMT+0530 (India Standard Time))
[BaseDriver] Using local app '/Users/janardhana/Downloads/MediaFirst_cip.ipa'
[debug] [BaseDriver] Unzipping '/Users/janardhana/Downloads/MediaFirst_cip.ipa'
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.14.0"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 68
[HTTP] 
[debug] [BaseDriver] Extracted 95 item(s) from '/Users/janardhana/Downloads/MediaFirst_cip.ipa'
[debug] [BaseDriver] Matched 94 item(s) in the extracted archive. Assuming 'Payload/MediaFirst.app' is the correct bundle
[BaseDriver] Unzipped local app to '/var/folders/8q/ss410_7x0y590l53qxyn_3sw0000gs/T/2019930-34806-1dymwog.tbds/Payload/MediaFirst.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1572424422109 (14:03:42 GMT+0530 (India Standard Time))
[debug] [XCUITest] Checking whether app '/var/folders/8q/ss410_7x0y590l53qxyn_3sw0000gs/T/2019930-34806-1dymwog.tbds/Payload/MediaFirst.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [iOS] Getting bundle ID from app '/var/folders/8q/ss410_7x0y590l53qxyn_3sw0000gs/T/2019930-34806-1dymwog.tbds/Payload/MediaFirst.app': 'com.ericsson.mediafirst'
[debug] [BaseDriver] Event 'resetStarted' logged at 1572424422117 (14:03:42 GMT+0530 (India Standard Time))
[debug] [XCUITest] Reset: running ios real device reset flow
[debug] [XCUITest] Reset: fullReset requested. Will try to uninstall the app 'com.ericsson.mediafirst'.
[debug] [XCUITest] Calling: 'ios-deploy --exists --id 356ba906dd8158a9fa418c94e5f7efbd3b03b4da --bundle_id com.ericsson.mediafirst'
[debug] [XCUITest] Reset: app not installed. No need to uninstall
[debug] [BaseDriver] Event 'resetComplete' logged at 1572424422605 (14:03:42 GMT+0530 (India Standard Time))
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Starting iOS device log capture with: 'idevicesyslog'
[debug] [XCUITest] Crash reports root '/Users/janardhana/Library/Logs/CrashReporter/MobileDevice/dayakar’s iPad (4)' does not exist. Got nothing to gather.
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1572424422765 (14:03:42 GMT+0530 (India Standard Time))
[XCUITest] Setting up real device
[debug] [XCUITest] Verifying application platform
[debug] [XCUITest] CFBundleSupportedPlatforms: ["iPhoneOS"]
[debug] [XCUITest] Calling: 'ios-deploy --exists --id 356ba906dd8158a9fa418c94e5f7efbd3b03b4da --bundle_id com.ericsson.mediafirst'
[debug] [XCUITest] Installing '/var/folders/8q/ss410_7x0y590l53qxyn_3sw0000gs/T/2019930-34806-1dymwog.tbds/Payload/MediaFirst.app' on device with UUID '356ba906dd8158a9fa418c94e5f7efbd3b03b4da'...
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.14.0"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 68
[HTTP] 
[debug] [XCUITest] The app has been installed successfully.
[debug] [BaseDriver] Event 'appInstalled' logged at 1572424426488 (14:03:46 GMT+0530 (India Standard Time))
[XCUITest] Using WDA path: '/Users/janardhana/.nvm/versions/node/v11.10.0/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Users/janardhana/.nvm/versions/node/v11.10.0/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[debug] [XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.14.0"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 68
[HTTP] 
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.14.0"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 68
[HTTP] 
[debug] [XCUITest] Parsed BUILD_DIR configuration value: '/Users/janardhana/Library/Developer/Xcode/DerivedData/WebDriverAgent-bgjcxsxevwaugvffeqajnfflhlkw/Build/Products'
[debug] [XCUITest] Got derived data root: '/Users/janardhana/Library/Developer/Xcode/DerivedData/WebDriverAgent-bgjcxsxevwaugvffeqajnfflhlkw'
[debug] [XCUITest] Starting WebDriverAgent initialization with the synchronization key '/Users/janardhana/Library/Developer/Xcode/DerivedData/WebDriverAgent-bgjcxsxevwaugvffeqajnfflhlkw'
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [WD Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"12.4\",\n      \"sdkVersion\" : \"12.2\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"12.4\",\n      \"ip\" : \"10.160.172.32\"\n    },\n    \"build\" : {\n      \"upgradedAt\" : \"1567058738371\",\n      \"time\" : \"Oct 25 2019 19:04:47\",\n      \"productBundleIdentifier\" : \"com.facebook.WebDriverAgentRunner\"\n    }\n  },\n  \"sessionId\" : \"1364A7C0-0203-4E30-B841-5B46874411B8\",\n  \"status\" : 0\n}"
[debug] [WD Proxy] Determined that the downstream protocol for proxy is MJSONWP
[debug] [XCUITest] Upgrade timestamp of the currently bundled WDA: 1567058738371
[debug] [XCUITest] Upgrade timestamp of the WDA on the device: 1567058738371
[XCUITest] Will reuse previously cached WDA instance at 'http://localhost:8100/' with 'com.facebook.WebDriverAgentRunner'. Set the wdaLocalPort capability to a value different from 8100 if this is an undesired behavior.
[debug] [XCUITest] Trying to start WebDriverAgent 1 times with 10000ms interval
[debug] [XCUITest] These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1572424430521 (14:03:50 GMT+0530 (India Standard Time))
[XCUITest] Using provided WebdriverAgent at 'http://localhost:8100/'
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [XCUITest] WDA is not listening at 'http://localhost:8100/'
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1572424430530 (14:03:50 GMT+0530 (India Standard Time))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100). Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1572424431544 (14:03:51 GMT+0530 (India Standard Time))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100). Retrying...
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.14.0"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 68
[HTTP] 
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1572424432552 (14:03:52 GMT+0530 (India Standard Time))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100). Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1572424433558 (14:03:53 GMT+0530 (India Standard Time))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100). Retrying...
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.14.0"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 68
[HTTP] 
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1572424434567 (14:03:54 GMT+0530 (India Standard Time))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100). Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1572424435576 (14:03:55 GMT+0530 (India Standard Time))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100). Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1572424436588 (14:03:56 GMT+0530 (India Standard Time))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100). Retrying...
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.14.0"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 68
[HTTP] 
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1572424437592 (14:03:57 GMT+0530 (India Standard Time))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100). Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1572424438601 (14:03:58 GMT+0530 (India Standard Time))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100). Retrying...
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.14.0"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 68
[HTTP] 
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1572424439606 (14:03:59 GMT+0530 (India Standard Time))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100). Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1572424440615 (14:04:00 GMT+0530 (India Standard Time))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100). Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1572424441623 (14:04:01 GMT+0530 (India Standard Time))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100). Retrying...
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.14.0"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 68
[HTTP] 
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1572424442628 (14:04:02 GMT+0530 (India Standard Time))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100). Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1572424443637 (14:04:03 GMT+0530 (India Standard Time))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100). Retrying...
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.14.0"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 68
[HTTP] 
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1572424444643 (14:04:04 GMT+0530 (India Standard Time))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100). Retrying...
[debug] [XCUITest] UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100
[debug] [XCUITest]     at JWProxy.command (/Users/janardhana/.nvm/versions/node/v11.10.0/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:239:13)
[debug] [XCUITest] Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100 Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[XCUITest] Quitting and uninstalling WebDriverAgent
[XCUITest] Shutting down sub-processes
[debug] [XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100 Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[XCUITest]     at quitAndUninstall (/Users/janardhana/.nvm/versions/node/v11.10.0/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:515:15)
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [iOSLog] Stopping iOS log capture
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1572424445811 (14:04:05 GMT+0530 (India Standard Time))
[debug] [W3C] Encountered internal error running command: Error: Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100 Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[debug] [W3C]     at quitAndUninstall (/Users/janardhana/.nvm/versions/node/v11.10.0/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:515:15)
[HTTP] <-- POST /wd/hub/session 500 24901 ms - 1545

Test Logs:

---------------------------------------------------------------------------------------------
STARTED EXECUTION OF SCENARIO: Verify LIVE Playback Start Time and End Time
Tags: ['2ftiOS']
Filename: features/modules/LivePlayback/LivePlayback.feature
Line: 14
---------------------------------------------------------------------------------------------
Initializing the appium driver..
/Users/janardhana/Downloads/MediaFirst_cip.ipa
Desired Capabilities sent to hub : {'platformName': 'iOS', 'platformVersion': '12.2', 'browserName': '', 'deviceName': 'iPad_local', 'automationName': 'XCUITest', 'app': '/Users/janardhana/Downloads/MediaFirst_cip.ipa'}
HOOK-ERROR in before_scenario: WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Bad app: /Users/janardhana/Downloads/MediaFirst_cip.ipa. App paths need to be absolute or an URL to a compressed file

**Comment by mykola-mokhnach** [comment]
The attached log reflects another error related to the session initialisation. Is it the correct one?

**Comment by sjrjanardhana** [comment]
Yes, that is what i was wondering.... I am not finding the same log in server logs
I have double checked before pasting the logs

**Comment by mykola-mokhnach** [comment]
Unfortunately we cannot help you until you help us to get the proper logs

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing more to do here without the appropriate log. closed as incomplete.
