### ISSUE TITLE
Appium 1.15.1 Getting error Incorrect package and activity. Retrying.

### ISSUE THREAD

**Issue by AnandChaurasia** [appium/appium#13517]
## The problem

Appium is able to launch application but after launching it start retrying. below is appium log:
AndroidDriver] Performing fast reset on 'Activity'
[ADB] Getting install status for Activity
[ADB] Running 'C:\Users\ananchau\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZY3223SLL3 shell dumpsys package Activity'
[ADB] 'Activity' is installed
[ADB] Running 'C:\Users\ananchau\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZY3223SLL3 shell am force-stop Activity'
[ADB] Running 'C:\Users\ananchau\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZY3223SLL3 shell pm clear Activity'
[ADB] Running 'C:\Users\ananchau\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZY3223SLL3 shell dumpsys package Activity'
[ADB] Retrieving requested permissions
[ADB] Retrieved 19 permission(s) from ["requested"] group(s)
[ADB] Retrieving granted permissions
[ADB] Retrieved 7 permission(s) from ["install","runtime"] group(s)
[ADB] Granting permissions ["android.permission.ACCESS_FINE_LOCATION","android.permission.WRITE_EXTERNAL_STORAGE","android.permission.GET_ACCOUNTS","android.permission.ACCESS_COARSE_LOCATION","android.permission.READ_EXTERNAL_STORAGE"] to 'Activity'
[ADB] Got the following command chunks to execute: [["pm","grant","Activity","android.permission.ACCESS_FINE_LOCATION",";","pm","grant","Activity","android.permission.WRITE_EXTERNAL_STORAGE",";","pm","grant","Activity","android.permission.GET_ACCOUNTS",";","pm","grant","Activity","android.permission.ACCESS_COARSE_LOCATION",";","pm","grant","Activity","android.permission.READ_EXTERNAL_STORAGE",";"]]
[ADB] Running 'C:\Users\ananchau\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZY3223SLL3 shell pm grant Activity android.permission.ACCESS_FINE_LOCATION \; pm grant Activity android.permission.WRITE_EXTERNAL_STORAGE \; pm grant Activity android.permission.GET_ACCOUNTS \; pm grant Activity android.permission.ACCESS_COARSE_LOCATION \; pm grant Activity android.permission.READ_EXTERNAL_STORAGE \;'
[AndroidDriver] Performed fast reset on the installed 'Activity' application (stop and clear)
[UiAutomator2] Performing shallow cleanup of automation leftovers
[UiAutomator2] No obsolete sessions have been detected (Error: socket hang up)
[ADB] Running 'C:\Users\ananchau\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZY3223SLL3 shell am force-stop io.appium.uiautomator2.server.test'
[UiAutomator2] Starting UIAutomator2 server 4.3.0
[UiAutomator2] Using UIAutomator2 server from 'C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.3.0.apk' and test from 'C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk'
[UiAutomator2] Waiting up to 30000ms for UiAutomator2 to be online...
[ADB] Creating ADB subprocess with args: ["-P",5037,"-s","ZY3223SLL3","shell","am","instrument","-w","io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner"]
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[Instrumentation] io.appium.uiautomator2.server.test.AppiumUiAutomator2Server:
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[WD Proxy] Got response with status 200: {"sessionId":"None","value":{"ready":true,"message":"UiAutomator2 Server is ready to accept commands"}}
[UiAutomator2] The initialization of the instrumentation process took 5418ms
[WD Proxy] Matched '/session' to command name 'createSession'
[WD Proxy] Proxying [POST /session] to [POST http://localhost:8200/wd/hub/session] with body: {"capabilities":{"firstMatch":[{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"app":"D:\\Posche-2019\\Application\\park-starter-release2510.apk","appPackage":"Activity","appActivity":"Activity","appWaitActivity":"Activity","bundleID":"Activity","autoGrantPermissions":true,"platformName":"Android","udid":"ZY3223SLL3","deviceName":"Moto G (5)"},"app":"D:\\Posche-2019\\Application\\park-starter-release2510.apk","appPackage":"Activity","appActivity":"Activity","appWaitActivity":"Activity","bundleID":"Activity","autoGrantPermissions":true,"platformName":"Android","udid":"ZY3223SLL3","deviceName":"ZY3223SLL3","deviceUDID":"ZY3223SLL3"}],"alwaysMatch":{}}}
[WD Proxy] Got response with status 200: {"sessionId":"424085e9-3208-41fe-ba2e-71ad67bd5f0a","value":{"sessionId":"424085e9-3208-41fe-ba2e-71ad67bd5f0a","capabilities":{"firstMatch":[{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"app":"D:\\Posche-2019\\Application\\park-starter-release2510.apk","appPackage":"Activity","appActivity":"Activity","appWaitActivity":"Activity","bundleID":"Activity","autoGrantPermissions":true,"platformName":"Android","udid":"ZY3223SLL3","deviceName":"Moto G (5)"},"app":"D:\\Posche-2019\\Application\\park-starter-release2510.apk","appPackage":"Activity","appActivity":"Activity","appWaitActivity":"Activity","bundleID":"Activity","autoGrantPermissions":true,"platformName":"Android","udid"...
[WD Proxy] Determined the downstream protocol as 'W3C'
[WD Proxy] Proxying [GET /appium/device/info] to [GET http://localhost:8200/wd/hub/session/424085e9-3208-41fe-ba2e-71ad67bd5f0a/appium/device/info] with no body
[WD Proxy] Got response with status 200: {"sessionId":"424085e9-3208-41fe-ba2e-71ad67bd5f0a","value":{"androidId":"36ef291161afe52f","manufacturer":"motorola","model":"Moto G (5)","brand":"motorola","apiVersion":"27","platformVersion":"8.1.0","carrierName":"Telekom.de","realDisplaySize":"1080x1920","displayDensity":480,"networks":[{"type":0,"typeName":"MOBILE","subtype":13,"subtypeName":"LTE","isConnected":true,"detailedState":"CONNECTED","state":"CONNECTED","extraInfo":"internet.telekom","isAvailable":true,"isFailover":false,"isRoaming":false,"capabilities":{"transportTypes":"NET_CAPABILITY_MMS","networkCapabilities":"","linkUpstreamBandwidthKbps":51200,"linkDownBandwidthKbps":102400,"signalStrength":-2147483648,"networkSpecifier":"1","SSID":null}},{"type":1,"typeName":"WIFI","subtype":0,"subtypeName":"","isConnected":true,"detailedState":"CONNECTED","state":"CONNECTED","extraInfo":"\"XS4GUEST\"","isAvailable":true,"isFailover":false,"isRoaming":false,"capabilities":{"transportTypes":"NET_CAPABILITY_SUPL","networkCapabilities":"","linkUpstreamBa...
[ADB] Running 'C:\Users\ananchau\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZY3223SLL3 shell dumpsys window'
[AndroidDriver] Screen is locked, trying to unlock
[AndroidDriver] Using app unlock, this is going to be deprecated!
[AndroidDriver] Unlocking screen
[AndroidDriver] Launching .Unlock
[ADB] Running 'C:\Users\ananchau\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZY3223SLL3 shell am start -n io.appium.settings/.Unlock -c android.intent.category.LAUNCHER -a android.intent.action.MAIN -f 0x10200000'
[UiAutomator2] Starting 'Activity/Activity and waiting for 'Activity/Activity'
[ADB] Running 'C:\Users\ananchau\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZY3223SLL3 shell am start -W -n Activity/Activity -S'
[ADB] Waiting up to 20000ms for activity matching pkg: 'Activity' and activity: 'Activity' to be focused
[ADB] Possible activities, to be checked: 'Activity', 'Activity.Activity'
[ADB] Getting focused package and activity
[ADB] Running 'C:\Users\ananchau\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZY3223SLL3 shell dumpsys window windows'
[ADB] Found package: 'Activity' and fully qualified activity name : 'Activity'
[ADB] Incorrect package and activity. Retrying.
[ADB] Getting focused package and activity
[ADB] Running 'C:\Users\ananchau\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZY3223SLL3 shell dumpsys window windows'
[ADB] Found package: 'Activity' and fully qualified activity name : 'Activity'
[ADB] Incorrect package and activity. Retrying.
[ADB] Getting focused package and activity
[ADB] Running 'C:\Users\ananchau\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZY3223SLL3 shell dumpsys window windows'
[ADB] Found package: 'Activity' and fully qualified activity name : 'Activity'
[ADB] Incorrect package and activity. Retrying.

**capabalities  I used is :**
"deviceName": "Moto G (5)",
      "platformName": "Android",
      "udid": "ZY3223SLL3",
      "app": "",
      "appWaitActivity": "",
      "appPackage": "",
      "appActivity": "",
      "bundleID": ""

**Comment by mykola-mokhnach** [comment]
Did you read https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md?

**Comment by AnandChaurasia** [comment]
I gave these data in my code but cant disclose :)
"app": "",
"appWaitActivity": "",
"appPackage": "",
"appActivity": "",
"bundleID": ""

**Comment by mykola-mokhnach** [comment]
I mean it might the values that you provided don't work for the app and should be changed

**Comment by mykola-mokhnach** [comment]
this only means that package name has been set properly, although the activity name could still be wrong - the tutorial above describes it in more details

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by eliezercazares** [comment]
broken link pls update
