### ISSUE TITLE
Unable to install Appium over Mac terminal

### ISSUE THREAD

**Issue by whitew0lf5** [appium/appium#13511]
## The problem

I just got a new Mac mini (Catalina) and have been trying to get Appium going on it for iOS devices. I was getting a "A valid provisioning profile for this executable was not found" error when trying to run inspector and found a page that looks like it might help. During its tutorial it told me:
```
Open Xcode and open the project WebDriverAgent.xcodeproj.

The project is located either in the usr or opt directory, where you can find it under /local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent.
```
When I get to node_modules there is no appium folder within it, just an npm folder. I assumed this wa sbecause i hadn't installed appium over terminal yet so I:
1) brew install node
2) npm install -g appium
3) npm install wd
4) appium
But running appium in terminal just yields command not found. Even appium-doctor yields the same reply in terminal. What do I need to do in order to get appium to install correctly over terminal?

The page I mentioned above:
https://documentation.tricentis.com/en/1130/content/engines_3.0/mobile/tbox_mobileweb_ios.htm

## Environment

* Appium version (or git revision) that exhibits the issue:
Appium Verison = 1.15.1
* Last Appium version that did not exhibit the issue (if applicable):
N/A
* Desktop OS/version used to run Appium:
Mac Catalina 10.15
* Node.js version (unless using Appium.app|exe):
Node version 12.12.0
* Npm or Yarn package manager:
NPM verison 6.12.0
* Mobile platform/version under test:
iOS v12.3.1
* Real device or emulator/simulator:
Ipad 6th gen
* Appium CLI or Appium.app|exe:
CLI

## Details

Trying to set up Appium for iOS device testing, but when trying to open WebDriverAgent from:
```
/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
```
But there is no Appium folder in lib/node_modules/... Only an npm folder.
Doing "npm install -g appium" and then "appium" in terminal results in:
```
-bash: appium: command not found
```

## Link to Appium logs

Can't get appium installed over terminal so I if there are logs I'll need to be guided

## Code To Reproduce Issue [ Good To Have ]
Havent run code. Only previously mentioned terminal commands.

**Comment by mykola-mokhnach** [comment]
The tutorial above is out of date. Now WebDriverAgent is a separate node module. Check https://github.com/appium/appium/issues/13327

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
