### ISSUE TITLE
Appium 1.16 beta, Could not proxy command to remote server / socket hang up

### ISSUE THREAD

**Issue by grant-mccarriagher** [appium/appium#13525]
## The problem

When running tests using Appium v1.16.0-beta.1 against real iOS devices, we sometimes get sock hang ups in Appium (I assume between Appium and WebDriverAgent). When this happens, our test suite can't seem to recover and all subsequent tests fail. The Appium process itself does not appear to crash.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.16.0-beta.1
* Last Appium version that did not exhibit the issue (if applicable): Unsure, I can try to get a testing environment set up with 1.15.1 if desired, but we can't go further back than that due to iOS 13 compatibility
* Desktop OS/version used to run Appium: macOS 10.14.5
* Node.js version (unless using Appium.app|exe): v12.10.0
* Npm or Yarn package manager: 6.10.3
* Mobile platform/version under test: iOS 13.1
* Real device or emulator/simulator: Real iPhone Xs
* Appium CLI or Appium.app|exe: CLI

## Details

The specific error we are seeing for this issue is `An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up`. We are using WebdriverIO as our test runner, so apologies if this error doesn't come directly from Appium. I will include a full Appium log below (with iOS logging enabled). We have made sure that we're using the latest version of WebDriverAgent by manually uninstalling it from our build phones before these tests were ran.

## Link to Appium logs

This log is extremely verbose due to iOS logging being on, so it is truncated from a bit before the above error started to appear, to the very end of the test run.
https://gist.github.com/grant-mccarriagher/761f9f584b74250c5580fc92111709f9

**Comment by KazuCocoa** [comment]
Could you include around the log which happened the `Could not proxy command to remote server.` error?
(Or is https://gist.github.com/grant-mccarriagher/761f9f584b74250c5580fc92111709f9#file-appium-L5639 the request which happened the error?)

**Comment by grant-mccarriagher** [comment]
@KazuCocoa https://gist.github.com/grant-mccarriagher/761f9f584b74250c5580fc92111709f9 is truncated since it's so long. To see the full file, you have to look at it raw: https://gist.githubusercontent.com/grant-mccarriagher/761f9f584b74250c5580fc92111709f9/raw/46690d4b8dc9bd85c8ffe93836bfac8499a2264c/appium

Looks like line 17831 is the first instance of `Original error: Could not proxy command to remote server. Original error: Error: socket hang up`.

**Comment by grant-mccarriagher** [comment]
Digging into this, it looks like the most recent command that failed was installing the app, which was recently changed here: https://github.com/appium/appium-xcuitest-driver/commit/cfbd4690de9d566297b5af0d81f619a2e34942e4#diff-aedbcb2865a6aa45e4b096f30c094992 . Looking at stack trace in the log, I believe the version of appium@beta we're using does not have these changes, even though I installed it from npm on Tuesday?

If the changes to `ios-deploy.js` are indeed supposed to be published on the beta channel, I'll update our appium@beta tomorrow, attempt to get these changes local, and then try to reproduce this issue again.

**Comment by KazuCocoa** [comment]
Thanks the log and your digging further.
The change is in appium-xcuitest-drvier `3.4.0`. You can ensure if the version is in your env like:

```
$ npm ls -g appium-xcuitest-driver
/usr/local/lib
├─┬ appium@1.16.0-beta.1
│ ├── appium-xcuitest-driver@3.4.0
│ └─┬ appium-youiengine-driver@1.2.1
│   └── appium-xcuitest-driver@2.133.1
```

The above is the version I installed just now. It looks has 3.4.0.

**Comment by mykola-mokhnach** [comment]
@grant-mccarriagher Any updates on this issue or it can be closed?

**Comment by grant-mccarriagher** [comment]
We have not seen this issue since implementing the WDA strategy documented here: https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/wda-custom-server.md , and limiting our app removals/installs during testing. I will close this for now, and open a new issue if/when we attempt to dig into this further.
