### ISSUE TITLE
POST request timeout and response '500' on iOS device ver 13.1.2 Hybrid app

### ISSUE THREAD

**Issue by havoanhnguyen** [appium/appium#13528]
## The problem

The response for POST request on iOS web is 500 and makes the automation scripts failed.

## Environment

Appium version: 1.14.2
Mobile platform/version under test: iOS Hybrid app
Real device: iPhone X - iOS 13.1.2

## Link to Appium logs

https://gist.github.com/havoanhnguyen/96b72906156fc350a8b295b3172e3e10

## Code To Reproduce Issue:

```
const contexts = await driver.contexts()
await driver.context(contexts[1])
await driver.waitForElementByClassName('input', waitingTime).sendKeys('test hybrid app')
await driver.waitForElementByXPath("//option[@value='1']", waitingTime).click()
```

**Comment by mykola-mokhnach** [comment]
Appium 1.14 is not compatible to iOS 13. Please try appium@beta
