### ISSUE TITLE
WebDriverAgent cannot find tab button in Safari iOS13

### ISSUE THREAD

**Issue by giganpv** [appium/appium#13526]
## The problem
WebDriverAgent cannot find tab button in Safari on iOS 13.2
on iOS 12.4 it is works

## Environment

├─┬ appium@1.16.0-beta.1
│ ├─┬ appium-ios-driver@4.4.0
│ │ └── appium-remote-debugger@4.5.0 
│ ├─┬ appium-xcuitest-driver@3.4.0
│ │ └── appium-remote-debugger@6.4.0 
│ └─┬ appium-youiengine-driver@1.2.1
│   └─┬ appium-xcuitest-driver@2.133.1
│     └── appium-remote-debugger@5.7.0 
└── appium-remote-debugger@6.4.0

iOS 13.2
 Real device Phone 6 plus

## Link to Appium logs
https://gist.github.com/giganpv/d1f36e83364fe9d1ed948826ac634fe5

error from iOS 13.2:

[HTTP] {"using":"-ios predicate string","sessionId":"5a14cca7-d795-45cc-80e4-31cd8802b163","value":"name == 'Tabs' OR name == 'Pages'"}
[debug] [W3C (5a14cca7)] Calling AppiumDriver.findElement() with args: ["-ios predicate string","name == 'Tabs' OR name == 'Pages'","5a14cca7-d795-45cc-80e4-31cd8802b163"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 10000 ms for condition
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://localhost:8110/session/6F87B3FE-C712-407C-9663-3C2BD2FD3202/element] with body: {"using":"predicate string","value":"name == 'Tabs' OR name == 'Pages'"}
[debug] [RemoteDebugger] Checking document readyState
[debug] [RemoteDebugger] Sending javascript command: '(function (){ return document.readyState; })()'
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:7394', page '1', target 'page-6' (id: 28)
[debug] [RemoteDebugger] Received data response from send (id: 28): '"complete"'
[debug] [RemoteDebugger] Sending to Web Inspector took 21ms
[debug] [RemoteDebugger] Document readyState is 'complete'
[debug] [RemoteDebugger] Page is ready
[WD Proxy] Got an unexpected response with status 404: {"value":{"error":"no such element","message":"unable to find an element using 'predicate string', value 'name == 'Tabs' OR name == 'Pages''","traceback":"(\n\t0   WebDriverAgentLib                   0x00000001046cb494 FBNoSuchElementErrorResponseForRequest + 312\n\t1   WebDriverAgentLib                   0x00000001046cb25c +[FBFindElementCommands handleFindElement:] + 448\n\t2   WebDriverAgentLib                   0x00000001046aa2b8 -[FBRoute_TargetAction mountRequest:intoResponse:] + 220\n\t3   WebDriverAgentLib                   0x0000000104697a80 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 504\n\t4   RoutingHTTPServer                   0x0000000104816394 -[RoutingHTTPServer handleRoute:withRequest:response:] + 144\n\t5   RoutingHTTPServer                   0x0000000104816b50 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 44\n\t6   libdispatch.dylib                   0x00000001c2f87184 B7EED4C7-560D-3DA6-9B50-ED52A150AAC6 + 377220\n\t7   libdispa...
[debug] [W3C] Matched W3C error code 'no such element' to NoSuchElementError
[debug] [BaseDriver] Waited for 437 ms so far
[debug] [WD Proxy] Matched '/element' to command name 'findElement'

## code
in python keyword:

 def ios_click_element(self, locator, timeout=10):
        """ click on ios element using predicates"""
        self._current_application().implicitly_wait(timeout)
        self._info("Clicking element '%s'." % locator)
        self._current_application().find_element_by_ios_predicate(locator).click()

in robotframework:

${safariTabs}                   name == 'Tabs'  OR  name == 'Pages'
${closeSafariTab}               name == 'closeTabButton' AND visible == true
Close All Safari Tabs
    APMAppiumLibrary.Open Application  http://${macosHost}:${iosappiumport}/wd/hub  platformName=iOS  platformVersion=@{platformVersion}[0]  deviceName=@{deviceName}[0]  udid=${udid}   keepKeyChains=true  xcodeOrgId=57P38MF5GS  xcodeSigningId=iPhone Developer  newCommandTimeout=1800  wdaLocalPort=${wdaport}  startIWDP=true  browserName=Safari    useNewWDA=false    usePrebuiltWDA=true    webkitResponseTimeout=20000
    APMAppiumLibrary.Switch To Context    NATIVE_APP
    APMAppiumLibrary.Ios Click Element    ${safariTabs}
    :FOR    ${n}    IN RANGE    10
    \    @{closeTabs}=    APMAppiumLibrary.Ios Find Elements    ${closeSafariTab}
    \    ${numberOfTabs}=    BuiltIn.Get Length    ${closeTabs}
    \    ${noTabs}=    BuiltIn.Set Variable If    ${numberOfTabs} == 0    True    False
    \    Exit For Loop If    ${noTabs}
    \    Close Visible Tabs    @{closeTabs}
    \    APMAppiumLibrary.Swipe By Percent    50    10    50    90    1000

**Comment by mykola-mokhnach** [comment]
The error is expected. Search by predicates only works in native iOS context and is not supported in web context

**Comment by giganpv** [comment]
> The error is expected. Search by predicates only works in native iOS context and is not supported in web context

But why it works in iOS 12.4. version?

**Comment by mykola-mokhnach** [comment]
> But why it works in iOS 12.4. version?

I only say what I can observe from the provided information. If there is more information, which has not been provided then please attach it as well.

**Comment by giganpv** [comment]
Logs form iOS 12.4

[HTTP] {"using":"-ios predicate string","sessionId":"9e5860ac-b6d9-4749-9614-c133d8a30e97","value":"name == 'Tabs' OR name == 'Pages'"}
[debug] [W3C (9e5860ac)] Calling AppiumDriver.findElement() with args: ["-ios predicate string","name == 'Tabs' OR name == 'Pages'","9e5860ac-b6d9-4749-9614-c133d8a30e97"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 10000 ms for condition
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://localhost:8110/session/94B87D0E-3E7F-4743-94F7-B01D43E92E0E/element] with body: {"using":"predicate string","value":"name == 'Tabs' OR name == 'Pages'"}
[debug] [RemoteDebugger] Checking document readyState
[debug] [RemoteDebugger] Sending javascript command: '(function (){ return document.readyState; })()'
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:1410', page '1', target 'page-1' (id: 24)
[debug] [RemoteDebugger] Received data response from send (id: 24): '"complete"'
[debug] [RemoteDebugger] Sending to Web Inspector took 18ms
[debug] [RemoteDebugger] Document readyState is 'complete'
[debug] [RemoteDebugger] Page is ready
[debug] [WD Proxy] Got response with status 200: {"value":{"ELEMENT":"35000000-0000-0000-8205-000000000000","element-6066-11e4-a52e-4f735466cecf":"35000000-0000-0000-8205-000000000000"},"sessionId":"94B87D0E-3E7F-4743-94F7-B01D43E92E0E"}
[debug] [W3C (9e5860ac)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"35000000-0000-0000-8205-000000000000","ELEMENT":"35000000-0000-0000-8205-000000000000"}
[HTTP] <-- POST /wd/hub/session/9e5860ac-b6d9-4749-9614-c133d8a30e97/element 200 510 ms - 137
[HTTP] 
[HTTP] --> POST /wd/hub/session/9e5860ac-b6d9-4749-9614-c133d8a30e97/element/35000000-0000-0000-8205-000000000000/click
[HTTP] {"sessionId":"9e5860ac-b6d9-4749-9614-c133d8a30e97","id":"35000000-0000-0000-8205-000000000000"}
[W3C (9e5860ac)] Driver proxy active, passing request on via HTTP proxy

**Comment by mykola-mokhnach** [comment]
This is fine - in the recent log the current context is native, so the locator worked properly. Simply make sure you are in the right context

**Comment by giganpv** [comment]
I changed context to wrong and try to pass test on 12.4, and see the same error. So looks like apple changed context for buttons. Where can find new context for iOS 13?

[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://localhost:8110/session/BC1D9C97-A3AC-4F10-8DE2-88CF4558AE72/element] with body: {"using":"predicate string","value":"name == 'Tabs1' OR name == 'Pages1'"}
[WD Proxy] Got an unexpected response with status 404: {"value":{"error":"no such element","message":"unable to find an element using 'predicate string', value 'name == 'Tabs1' OR name == 'Pages1''","traceback":"(\n\t0   WebDriverAgentLib                   0x0000000107af6b70 FBNoSuchElementErrorResponseForRequest + 312\n\t1   WebDriverAgentLib                   0x0000000107af6938 +[FBFindElementCommands handleFindElement:] + 460\n\t2   WebDriverAgentLib                   0x0000000107ad5538 -[FBRoute_TargetAction mountRequest:intoResponse:] + 220\n\t3   WebDriverAgentLib                   0x0000000107ac2a44 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 504\n\t4   RoutingHTTPServer                   0x0000000107c42394 -[RoutingHTTPServer handleRoute:withRequest:response:] + 144\n\t5   RoutingHTTPServer                   0x0000000107c42b50 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 44\n\t6   libdispatch.dylib                   0x00000001c1ea97d4 <redacted> + 16\n\t7   libdispatch.dylib                   ...

**Comment by mykola-mokhnach** [comment]
> Where can find new context for iOS 13?

Sorry, I don't understand the question

**Comment by giganpv** [comment]
I connect to device thru appium desktop program, observe Safari and found that Tabs name was changed to TabsButton.
Fix cod in automation script and now WebDriver can find and open this button
