### ISSUE TITLE
Appium 1.16 beta, Could not proxy command to remote server / Error: connect ECONNREFUSED 127.0.0.1:8100

### ISSUE THREAD

**Issue by grant-mccarriagher** [appium/appium#13524]
## The problem

When running tests using Appium v1.16.0-beta.1 against real iOS devices, we sometimes get disconnects in Appium (I assume between Appium and WebDriverAgent). When this happens, our test suite can't seem to recover and all subsequent tests fail. The Appium process itself does not appear to crash.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.16.0-beta.1
* Last Appium version that did not exhibit the issue (if applicable): Unsure, I can try to get a testing environment set up with 1.15.1 if desired, but we can't go further back than that due to iOS 13 compatibility
* Desktop OS/version used to run Appium: macOS 10.14.5
* Node.js version (unless using Appium.app|exe): v12.10.0
* Npm or Yarn package manager: 6.10.3
* Mobile platform/version under test: iOS 13.1
* Real device or emulator/simulator: Real iPhone Xs
* Appium CLI or Appium.app|exe: CLI

## Details

The specific error we are seeing for this issue is `An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100`. We are using WebdriverIO as our test runner, so apologies if this error doesn't come directly from Appium. I will include a full Appium log below (with iOS logging enabled). We have made sure that we're using the latest version of WebDriverAgent by manually uninstalling it from our build phones before these tests were ran.

## Link to Appium logs

This log is extremely verbose due to iOS logging being on, so it is truncated from a bit before the above error started to appear, to the very end of the test run.
https://gist.github.com/grant-mccarriagher/2c5b1c87506e1324be2b21d239519e4f

**Comment by grant-mccarriagher** [comment]
Note that the appium log above is truncated, to see the full log, you must look at it raw: https://gist.githubusercontent.com/grant-mccarriagher/2c5b1c87506e1324be2b21d239519e4f/raw/53265522be701e8716494beeea03bc01b4a79d00/appium

**Comment by KazuCocoa** [comment]
I could not find any good point, but what about sending `status` command etc not to idle WDA over 60s between them?
Before the `ECONNREFUSED` happened, it tool over 60s after getting the previous command.
iOS 13 kills background tasks frequently according to some articles. I'm not sure this affects to xcuitest process, but I could not find other points which could be the cause for now,,

```
...
[HTTP] --> POST /wd/hub/session/e330634d-d0c0-4681-98e3-af8963e71586/element
[HTTP] {"using":"accessibility id","value":"emailAddress"}
[debug] [W3C (e330634d)] Calling AppiumDriver.findElement() 
...
[IOSDeviceLog] Oct 30 13:33:04 ACV-Auctions-iPhone-X testmanagerd[238] <Notice>: Preparing screenshot for <private>
[WD Proxy] Got an unexpected response with status 404: {"value":{"error":"no such element","message":"unable to find an element using 'accessibility id', value 'emailAddress'","traceback":"(\n\t0   WebDriverAgentLib                   0x00000001056b6ac8 FBNoSuchElementErrorResponseForRequest + 312\n\t1   WebDriverAgentLib                   0x00000001056b6890 +[FBFindElementCommands handleFindElement:] + 460\n\t2   WebDriverAgentLib                   0x0000000105695490 -[FBRoute_TargetAction mountRequest:intoResponse:] + 220\n\t3   WebDriverAgentLib                   0x000000010568299c __37-[FBWebServer registerRouteHandlers:]_block_invoke + 504\n\t4   RoutingHTTPServer                   0x000000010987e2c4 -[RoutingHTTPServer handleRoute:withRequest:response:] + 144\n\t5   RoutingHTTPServer                   0x000000010987ea80 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 44\n\t6   libdispatch.dylib                   0x0000000190e8a184 3A5DB4E0-BC24-375D-897E-51E6CF7D6304 + 377220\n\t7   libdispatch.dylib            ...
[debug] [W3C] Matched W3C error code 'no such element' to NoSuchElementError
[debug] [W3C (e330634d)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[debug] [W3C (e330634d)]     at XCUITestDriver.doNativeFind (/usr/local/Cellar/node/11.6.0/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:126:11)
[HTTP] <-- POST /wd/hub/session/e330634d-d0c0-4681-98e3-af8963e71586/element 404 161 ms - 398
[HTTP]
....
after 60s...
....
[IOSDeviceLog] Oct 30 13:34:14 ACV-Auctions-iPhone-X testmanagerd[238] <Notice>: Preparing screenshot for <private>
[IOSDeviceLog] Oct 30 13:34:14 ACV-Auctions-iPhone-X testmanagerd[238] <Notice>: Got screenshot, rotating to orientation 0
[HTTP] --> POST /wd/hub/session/e330634d-d0c0-4681-98e3-af8963e71586/touch/perform
[HTTP] {"actions":[{"action":"press","options":{"x":188,"y":122}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"x":188,"y":690}},{"action":"release"}]}
[debug] [W3C (e330634d)] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":188,"y":122}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"x":188,"y":690}},{"action":"release"}],"e330634d-d0c0-4681-98e3-af8963e71586"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: press(options={"x":188,"y":122})-wait(options={"ms":1000})-moveTo(options={"x":188,"y":690})-release
[debug] [WD Proxy] Proxying [POST /wda/touch/perform] to [POST http://localhost:8100/session/814BBE5A-3CF2-4C65-98A9-66F7F00A4927/wda/touch/perform] with body: {"actions":[{"action":"press","options":{"x":188,"y":122}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"x":188,"y":690}},{"action":"release"}]}
[WD Proxy] Got an unexpected response with status undefined: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[IOSDeviceLog] Oct 30 13:34:14 ACV-Auctions-iPhone-X acv(CFNetwork)[673] <Notice>: Task <93747C01-85DD-456F-AFFF-2E89E51B9A17>.<17> received response, status 200 content K
```

**Comment by grant-mccarriagher** [comment]
@KazuCocoa Is that a known issue with WDA? The implementation at https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/wda-custom-server.md seems to start an xcodebuild process and keep it up and running as long as possible for CI purposes. There's nothing in there that pings `/status` as some sort of keep-alive.

If it was just an idea though, I can certainly try to limit our waits in the test and see if that helps.

**Comment by KazuCocoa** [comment]
No. We expect iOS has no such limitation for xcodebuild process.

I could not find xcodebuild disconnection and crash etc on your log, so this is just my idea which might happen on iOS 13.

**Comment by grant-mccarriagher** [comment]
We have not seen this issue since implementing the WDA strategy documented here: https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/wda-custom-server.md , and limiting our app removals/installs during testing. I will close this for now, and open a new issue if/when we attempt to dig into this further.

**Comment by maggie5750** [comment]
> We have not seen this issue since implementing the WDA strategy documented here: https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/wda-custom-server.md , and limiting our app removals/installs during testing. I will close this for now, and open a new issue if/when we attempt to dig into this further.

@grant-mccarriagher  I have this issue too. I want to know what changes you have done on WDA?
