### ISSUE TITLE
Unable to change language to french or to send apostrophe in a wpf textBox 

### ISSUE THREAD

**Issue by Francis300** [appium/appium#13538]
## The problem

Unable to change language to french or to send apostrophe in a wpf textBox.
Exemple  : tbxOrigine.SendKeys("L'Isle")); => "LùIsle"

## Environment

* Appium version (or git revision) that exhibits the issue: 1.0.1-Preview
* Desktop OS/version used to run Appium: Windows 10

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

tbxOrigine.SendKeys("L'Isle")); => "LùIsle"

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Please attach the full server log

**Comment by Francis300** [comment]
The program does not crash, therefore there is no log.

Basically, the problem is that I have to create special cases in a switch, to manually convert the QWERTY keys into AZERTY keys, because I could not change the keyboard language.

I tried to change the keyboard language with the below code:
  appCapabilities.SetCapability("locale", "fr_CA");
   appCapabilities.SetCapability("language", "fr");

but it does not work (the language does not change).

**Comment by mykola-mokhnach** [comment]
> The program does not crash, therefore there is no log.

The server always produces logs. Without the logs it is not possible to do the diagnostics

> I tried to change the keyboard language with the below code:
> appCapabilities.SetCapability("locale", "fr_CA");
> appCapabilities.SetCapability("language", "fr");

Are you sure these capabilities are supported by Windows driver? Is this mentioned somewhere in the docs?
