### ISSUE TITLE
Appium 1.15.0+ WDA seems to crash when hitting the /click endpoint

### ISSUE THREAD

**Issue by gdimitris** [appium/appium#13536]
## The problem
I am getting hanged sessions from Appium when calling click() on an element

## Environment

* Appium version (or git revision) that exhibits the issue: 
Appium 1.15.0, 1.15.1, 1.16.0-beta
* Last Appium version that did not exhibit the issue (if applicable): 
Appium 1.14.2
* Desktop OS/version used to run Appium: 
Mac OS X Mojave 10.14.6
* Node.js version (unless using Appium.app|exe): 
v11.9.0
* Npm or Yarn package manager:
`npm -v`
6.5.0
* Mobile platform/version under test:
iOS 13.1.2, iOS 13.1.3
* Real device or emulator/simulator:
iPhone 6, iPhone SE, iPhone 8 (real devices)
* Appium CLI or Appium.app|exe:
Appium CLI
## Details
There are some instances (flaky) during runtime that hitting the `/click` endpoint on the following elements cause appium session to freeze:
`//XCUIElementTypeTabBar
//XCUIElementTypeButton
`
The same flaky behaviour I get when checking for element visibility on the following element:
`//XCUIElementTypeActivityIndicator
`

## Link to Appium logs
Running in Selenium grid mode by launching appium this way:
```
appium_1.16.0-beta --default-capabilities='{"useJSONSource": true,"wdaStartupRetryInterval": 1500, "wdaStartupRetries":30,"shouldUseSingletonTestManager": false,"wdaLocalPort": 8900, "showIOSLog": false}' --nodeconfig ./path/to/node/config/iphone6.json --port 4751
```
iphone6.json
```
{
    "capabilities": [
        {
            "deviceName": "iPhone",
            "platformName": "iOS",
            "browserName": "iPhone 6",
            "platformVersion": "13.1.2",
            "maxInstances": 1,
            "udid": "xxx"
        }
    ],
    "configuration": {
        "cleanUpCycle": 2000,
        "timeout": 300,
        "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
        "url": "http://127.0.0.1:4751/wd/hub/",
        "host": "127.0.0.1",
        "port": 4751,
        "maxSession": 1,
        "register": true,
        "registerCycle": 5000,
        "hubPort": 4444,
        "hubHost": "127.0.0.1",
        "unregisterIfStillDownAfter": 60000
    }
}
```
Appium Node Logs: https://gist.github.com/gdimitris/a8d228ac54302d3b52b5566d8f88e58d

If you see in the gist at line 4846(https://gist.github.com/gdimitris/a8d228ac54302d3b52b5566d8f88e58d#file-gistfile1-txt-L4846) there is a POST request to WDA that never gets a response 
`POST http://localhost:8900/session/7D3AA408-C580-4E69-BF65-46AEE49CFB16/element/93080000-0000-0000-B47D-000000000000/click`. At that time, I opened PostMan and issued the same request with the same params and I did not get a response after 4-5 minutes. It looks like the WDA session is frozen and is not terminated after a timeout.

## Possible Workaround (?)

I found a workaround on this, if you use tap() instead of click() on those elements most issues go away. However I am still getting session crashes on polling for the presence/visibility of `//XCUIElementTypeActivityIndicator`

**Comment by mykola-mokhnach** [comment]
I don't think we can do anything about it - `/click` endpoint simply calls `XCUIElement.tap` method under the hood, whose internal implementation can only be changed by Apple. The workaround with tap by coordinates seems reasonable to me

**Comment by gdimitris** [comment]
Hi @mykola-mokhnach , thank you very much for your quick reply. Is there perhaps a workaround for the `//XCUIElementTypeActivityIndicator` element visibility polling ?

**Comment by mykola-mokhnach** [comment]
The visibility value is also calculated by XCTest. There is only `shouldUseTestManagerForVisibilityDetection` setting, which applies alternative (not necessarily better or more performant) visibility detection approach. Otherwise I don't have any good suggestions.

**Comment by gdimitris** [comment]
Thanks @mykola-mokhnach I will give it a try and let you know how it goes!

**Comment by gdimitris** [comment]
Issue seems to be solved with `shouldUseTestManagerForVisibilityDetection`

**Comment by gdimitris** [comment]
Thanks for your help @mykola-mokhnach
