### ISSUE TITLE
Cannot launch WebDriverAgent : error -  'carthage bootstrap --platform iOS\,tvOS'

### ISSUE THREAD

**Issue by mayusn** [appium/appium#13532]
## The problem

I cannot launch WebDriverAgent  due to the following error shown in the Appium server log. 

`[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'carthage bootstrap --platform iOS\,tvOS' exited with code 1
[XCUITest]     at quitAndUninstall (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/driver.js:527:15)`

Could anyone help me please? 

## Environment

Xcode Version 10.1 (10B61)
* Appium version  1.15.1
* Desktop OS/version used to run Appium: Mac
* Mobile platform/version under test: IOS
* Real device or emulator/simulator: simulator

**Comment by mykola-mokhnach** [comment]
Search is always helpful: https://github.com/appium/appium/search?q=%22carthage+bootstrap+--platform%22&type=Issues

**Comment by mayusn** [comment]
I read all other threads and discussions.  None of them helped. 

@KazuCocoa, I tried your suggestion you posted in another thread.  

`$ cd /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/
$ carthage bootstrap --platform iOS\,tvOS`

`Please update to the latest Carthage version: 0.34.0. You currently are on 0.33.0
*** Checking out RoutingHTTPServer at "v1.0.2"
*** Checking out YYCache at "1.1.0"
*** Checking out CocoaAsyncSocket at "7.6.3"
*** xcodebuild output can be found in /var/folders/hb/tfsxt1wd4ds__6zc__xh7tkc0000gn/T/carthage-xcodebuild.IYu7Ie.log
*** Downloading CocoaAsyncSocket.framework binary at "Version 7.6.3"
*** Building scheme "RoutingHTTPServer iOS" in RoutingHTTPServer.xcodeproj
*** Building scheme "RoutingHTTPServer tvOS" in RoutingHTTPServer.xcodeproj
*** Building scheme "YYCache tvOS" in YYCache.xcodeproj
*** Building scheme "YYCache iOS" in YYCache.xcodeproj
MREME17C7176:appium-webdriveragent mayu.kataoka$ cartha`

Are there anything else I can try ?

**Comment by mayusn** [comment]
@mykola-mokhnach , is there a way for me to manually install and launch WebDriverAgent ?

**Comment by KazuCocoa** [comment]
```
    mkdir -p Resources/WebDriverAgent.bundle
    ./Scripts/bootstrap.sh -d
```

in https://github.com/appium/appium/blob/master/docs/en/drivers/ios-xcuitest-real-devices.md#full-manual-configuration is manual steps to build WDA.

---

Could you attach the failure log more? Would like to check around the appium error, especially.

**Comment by gdimitris** [comment]
@mayusn I think I ran into your issue with carthage. Make sure you are running the latest Carthage version 0.4.0. You can confirm this by running `carthage -v` on your machine. After upgrading Carthage then run `carthage bootstrap --platform iOS\,tvOS` on your appium setup to test if it works. Hope this helps!

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by mattslavin** [comment]
I spent quite a long time working out what the problem was here, and for me I had two versions of carthage installed. There was a global node_modules version and then also the one in the carthage app folder. 
```
npm uninstall carthage
brew uninstall carthage
brew install carthage

brew link --overwrite carthage
```
Worked for me.

**Comment by AlfredoBazoCrossvale** [comment]
I am using appium 1.18.0-beta.1 and none of the solution provided works for me. Any idea?
I have tried doing carthage bootstrap --platform iOS\,tvOS but it does not work.

`*** Checking out YYCache at "1.1.0"
*** Checking out CocoaAsyncSocket at "72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc"
*** xcodebuild output can be found in /var/folders/yf/cmjdckl115qgcylj1krb19x40000gn/T/carthage-xcodebuild.phy5x2.log
*** Building scheme "iOS Framework" in CocoaAsyncSocket.xcodeproj
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Users/alfredobazolopez/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8189h/CocoaAsyncSocket/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc/Build/Intermediates.noindex/ArchiveIntermediates/iOS\ Framework/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/CocoaAsyncSocket.framework/CocoaAsyncSocket /Users/alfredobazolopez/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8189h/CocoaAsyncSocket/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc/Build/Products/Release-iphonesimulator/CocoaAsyncSocket.framework/CocoaAsyncSocket -output /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Build/iOS/CocoaAsyncSocket.framework/CocoaAsyncSocket

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/yf/cmjdckl115qgcylj1krb19x40000gn/T/carthage-xcodebuild.phy5x2.log`

**Comment by gdimitris** [comment]
Can you cat on `/var/folders/yf/cmjdckl115qgcylj1krb19x40000gn/T/carthage-xcodebuild.phy5x2.log` and post the output here?

**Comment by AlfredoBazoCrossvale** [comment]
Yes @gdimitris 
https://gist.github.com/AlfredoBazoCrossvale/51ecb8941e1751c9d579f5c14d2196d6

**Comment by gdimitris** [comment]
I did not find anything wrong in the logs you provided. Have you tried removing your DerivedData folder and try a clean build ?

**Comment by AlfredoBazoCrossvale** [comment]
which folder is that one?

**Comment by AlfredoBazoCrossvale** [comment]
I have just all the content of DerivedData folder. What do you want me to build? 
After executing this command, the error persists.
`carthage bootstrap --platform iOS,tvOS`

**Comment by sravanisathavalli** [comment]
AlfredoBazoCrossvale were you able to resolve this issue? I upgraded to iOS 14 and appium 1.18.2. It works when i run the code but when i try to start appium inspector i get this error.

**Comment by AlfredoBazoCrossvale** [comment]
No, I didn't. I finally downgrade the XCode version.

**Comment by sravanisathavalli** [comment]
which version of xcode is working for you.

**Comment by RonitJoardar** [comment]
I am also facing the same issue. Any solution here?

**Comment by jaspreetchagger** [comment]
I am also facing same issue
Appium Desktop: 1.18.0-2
Node.js:12.8.1
Electron: 7.2.4
xcode: 12.0
carthage:0.36.0

error:
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'carthage bootstrap --platform iOS\,tvOS' exited with code 1
[MJSONWP]     at quitAndUninstall (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:532:15)
[MJSONWP]     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:562:11
[MJSONWP]     at wrapped (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:35:13)
[MJSONWP]     at retry (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:18:13)
[MJSONWP]     at retryInterval (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:45:10)
[MJSONWP]     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:542:7

**Comment by cornshuckin** [comment]
I tried to resolve this with https://github.com/appium/appium/issues/14703, but that didn't seem to work.

I installed the non desktop version of Appium via `brew install appium`(I'm on a mac) - which installed v1.18.1.
Once installed, I started the server via command line with `appium` and ran my tests, I no longer ran into the carthage failure.

**Comment by huwangtao123** [comment]
Do we have any update for it?

**Comment by BijjamSuresh** [comment]
Tried all the steps like 
By upgrading Carthage 
reinstalling Appium
Running above comments

But no luck. Can some one help me 

Details:-
Mac OS catalina & Appium version 1.18.2 - 2


**Error Message:-** 
*** Fetching YYCache
*** Fetching CocoaAsyncSocket
*** Checking out CocoaAsyncSocket at "7.6.4"
*** Checking out YYCache at "1.1.2"
*** xcodebuild output can be found in /var/folders/jj/tx5hm9bx641bnkgfbhdqkcnc0000gn/T/carthage-xcodebuild.OvRz0K.log
*** Building scheme "iOS Framework" in CocoaAsyncSocket.xcodeproj
Build Failed
	Task failed with exit code 1:

**Comment by jaspreetchagger** [comment]
I manually installed webdriver agent on iPhoneSimulator using xcodeProject at following location:
https://github.com/appium/WebDriverAgent
and than launched Appium scripts. It worked for me.
This solution was given on following thread https://github.com/appium/appium/issues/14759

I used following command to build webdriver agent
xcodebuild -project WebDriverAgent.xcodeproj \
           -scheme WebDriverAgentRunner \
           -destination 'platform=iOS Simulator,name=iPhone 6' \
           test
given at: https://github.com/facebookarchive/WebDriverAgent/wiki/Starting-WebDriverAgent

**Comment by mike-r-vogel** [comment]
I am also hitting this error, have tried uninstalling/reinstalling appium, have tried uninstalling/reinstalling carthage. This all started happening when I upgraded to XCode 12. Any help would be greatly appreciated!

**Comment by RonitJoardar** [comment]
Please verify whether you have added the correct team id in the
appium.xcconfig file. Doing this solved the issue for me.

**Comment by BijjamSuresh** [comment]
with appium 1.19.0 beta is doing the job but no same beta Appium version for GUI and is waiting for the fix of GUI too. Thanks.

Solution and Work Around
#14703

**Comment by AndrewNaveen** [comment]
@all: What is the exact workaround to fix this? Everyone's suggesting to install Appium@beta and clean the derived data folder. After doing all that still, the build fails. 
Steps I followed:
- Uninstalled all appium versions
- rm -rf ~/Library/Caches/org.carthage.CarthageKit
- rm -rf /Carthage
- brew uninstall --force carthage
- npm uninstall carthage
- Cleaned up derived data folder
- Installed appium@beta
- cd /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent
- brew install carthage
- mkdir -p Resources/WebDriverAgent.bundle
- ./Scripts/bootstrap.sh -d
- carthage bootstrap --platform iOS
xcode version: 12
```
*** Building scheme "iOS Framework" in CocoaAsyncSocket.xcodeproj

Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Users/as1046924/Library/Caches/org.carthage.CarthageKit/DerivedData/12.1_12A7403/CocoaAsyncSocket/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc/Build/Intermediates.noindex/ArchiveIntermediates/iOS\ Framework/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/CocoaAsyncSocket.framework/CocoaAsyncSocket /Users/as1046924/Library/Caches/org.carthage.CarthageKit/DerivedData/12.1_12A7403/CocoaAsyncSocket/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc/Build/Products/Release-iphonesimulator/CocoaAsyncSocket.framework/CocoaAsyncSocket -output /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Build/iOS/CocoaAsyncSocket.framework/CocoaAsyncSocket
```
Because of this error, I'm unable to build wda on any phone/simulator.

**Comment by KazuCocoa** [comment]
If your `appium@beta` had https://github.com/appium/WebDriverAgent/blob/master/Scripts/carthage-wrapper.sh , `./Scripts/bootstrap.sh -d` calls the wrapper. Then, the build should work on Xcode 12 env.

If the lipo issue still exists on you env, probably your situation is different from we found. Then, you need different workaround in the carthage-wrapper.sh or tweak the wrapper, I assume.

**Comment by AndrewNaveen** [comment]
@KazuCocoa Thank you for responding. Yes, under scripts I could find the wrapper.sh.
The build still failed, and the same lipo issue. Do you suggest a different workaround?

**Comment by KazuCocoa** [comment]
No good idea for me. Probably your environment has different(?) issue I haven't seen, unfortunately.
