### ISSUE TITLE
Shake command in real device is not working

### ISSUE THREAD

**Issue by Hendrione-Moka** [appium/appium#13537]
## The problem

I am using appium 1.15.1 and try execute command `driver.shake()` and get the following error:

` org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Shake is not supported on real devices`

## Environment

* Appium version: `1.15.1`
* Desktop OS/version used to run Appium: `MacOS Catalina 10.15`
* Mobile platform/version under test: `ipadOS version 13.1.2 (17A860)`
* Real device or emulator/simulator: `real device (iPad air 6th gen)`
* Driver: `XCUITest`

## Link to Appium logs

Check appium log [here](https://gist.github.com/Hendrione-Moka/7f4df73ae25b9360d293e2d47929dda5)

**Comment by mykola-mokhnach** [comment]
This error is expected. We can only perform this command on Simulators. XCTest does not provide any API to do it on real devices.

**Comment by narasimhanukala** [comment]
@mykola-mokhnach 
i have a requirement to shake iOS real device to enable certain feature in my app.
how do we achieve shake on real device?
is there any alternative?

**Comment by mykola-mokhnach** [comment]
XCTest does not expose any APIs that would allow to do that. I don't know any other possible alternatives.
