### ISSUE TITLE
No possibility to find element by iOSNsPredicate strategy with AND operator

### ISSUE THREAD

**Issue by oyablonskyi** [appium/appium#13546]
## The problem

After updating to Xcode 11.2 I have faced with NoSuchElementException while finding element using iOSNsPredicate with operator AND, in case of only one condition inside of locator it works fine. 
Locator is ` "name CONTAINS 'TableViewCell' AND value MATCHES 'Medical Inquiries'" `
Logs [here](https://gist.github.com/oyablonskyi/a51bf720dc9520ae91fd367a30a0fb5d)
Page source [here](https://gist.github.com/oyablonskyi/f134d3833e872558d49d1d6a094a8f21)

Issue reproduced on iOS 12(any version from 12.1 to 12.4). On iOS 13.2 it works fine with Xcode 11.2, and on Xcode 10.3 with iOS 12.4. I thought that reason could be related to macOS Catalina, but on Mojave I have the same exception.

Also I want to notice that is not only one place in app where I have got simular exception.

## Environment
* Appium version 1.15.1
* Xcode 11.2
* MacOS Catalina
* Node.js version - v12.12.0
* Npm - v6.11.3, Yarn - v1.19.1
* Mobile platform - iOS 12.4
* Simulator

**Comment by mykola-mokhnach** [comment]
This issue is known as XcTest issue. Consider testing iOS 12 and below using Xcode 10 SDK and iOS13 with Xcode 11 SDK as a workaround.

Closed as third party issue.
