### ISSUE TITLE
Android - Sendkeys not working for Amount edittext having 0.00 default value

### ISSUE THREAD

**Issue by sandikumar3** [appium/appium#13552]
## The problem

Android - Sendkeys not working for Amount edittext having 0.00 default value. Able to click inside the field but values not getting entered with sendkeys method.

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:No 
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: 7.0
* Real device or emulator/simulator:emulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Android - Sendkeys not working for Amount edittext having 0.00 default value. Able to click inside the field but values not getting entered with sendkeys method.

**Comment by mykola-mokhnach** [comment]
Please fill out the required issue information and provide the logs

**Comment by sandikumar3** [comment]
Updated the information.

**Comment by mykola-mokhnach** [comment]
Sorry, I don't observe any updates

**Comment by mykola-mokhnach** [comment]
Closed as incomplete
