### ISSUE TITLE
Its not an issue but doubt on the WebDriverAgent 

### ISSUE THREAD

**Issue by vishnuprakash9845** [appium/appium#13551]
## The problem
From the Xcode tried to install the webdriveragent to mobile, but build was successful but webdriveragent was not getting installing. So opening the CommandPrompt and navigating to the webdriver project path and running the below command.

xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid of iphone>' test

Then webdriveragent installs in the mobile and Installed WebDriverAgent when tried to open its opening and getting closed immediately. Not able to understand why?. I am not able to understand which step i am going wrong. Can any one help me to solve this problem or help me the steps for IOS automation set up it would be helpful.

**Steps followed by me for IOS Automation Setup**
1-Installed Xcode
2-Installed Visual Studio
3-Installed appium through npm
4-Opened the webdriveragent project from the appium path and setted the signing (Team=my appled id) for webdriverlib, webdriveragentrunner and inetgrationapp.
5-Selected Integrationapp project and selected the device and clicked on run. Integration app got installed
6-Selected Webdriveragentrunner project and selected the device and clicked on run. Build succeed but WebDriverAgent did not got installed.
7.Opened the Command Prompt and navigated to the webdriver project path and ran the below command     " xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid of iphone>' test "
8-Then webdriveragent installs in the mobile and Installed WebDriverAgent when tried to open its opening and getting closed immediately.

**Comment by KazuCocoa** [comment]
Was the provisioning profile trusted?

> You can go to Settings => General => Device Management on the device to trust the developer and allow the WebDriverAgentRunner app to be run (see Apple documentation for more information).

- http://appium.io/docs/en/drivers/ios-xcuitest-real-devices/
- https://support.apple.com/en-us/HT204460

**Comment by vishnuprakash9845** [comment]
> Was the provisioning profile trusted?
> 
> > You can go to Settings => General => Device Management on the device to trust the developer and allow the WebDriverAgentRunner app to be run (see Apple documentation for more information).
> 
> * http://appium.io/docs/en/drivers/ios-xcuitest-real-devices/
> * https://support.apple.com/en-us/HT204460

When integrationapp was getting installed provising profile trusted popup came up, for webdriveragent i didnt get it.

**Comment by KazuCocoa** [comment]
It could depend on OS versions, xcuitest app like webdriveragent and normal app like integration app.

**Comment by vishnuprakash9845** [comment]
> It could depend on OS versions, xcuitest app like webdriveragent and normal app like integration app.

Appium version: 1.15.1
Desktop OS/version : macOS Catalina V10.15
Mobile platform/version under test: 13.2
XCode version: 11.2

**Comment by vishnuprakash9845** [comment]
> > It could depend on OS versions, xcuitest app like webdriveragent and normal app like integration app.
> 
> Appium version: 1.15.1
> Desktop OS/version : macOS Catalina V10.15
> Mobile platform/version under test: 13.2
> XCode version: 11.2

**For webdriveragent provising profile trusted popup to come up is there anything i can do.**

**Comment by KazuCocoa** [comment]
My iOS 13 device did not show such popup when I installed WDA with a person provisioning before.
Then, I should trust it via "Settings => General => profiles". It happens in every installation.
You can install another app and trust your provisioning profile. Then your profile can keep trust until remove all of apps which is signed by your provisioning profile.
(Only Apple knows what the popup behaviour is correct.)
