### ISSUE TITLE
Cannot installl Appium on Mac

### ISSUE THREAD

**Issue by jpteruel095** [appium/appium#13557]
## The problem

As I'm attempting to install Appium using npm, I'm already encountering this error.

## Environment

* Appium version (or git revision) that exhibits the issue: Beta
* Last Appium version that did not exhibit the issue (if applicable): Never tried it before
* Desktop OS/version used to run Appium: MacOS Catalina 10.15.1
* Node.js version (unless using Appium.app|exe): 6.14.4
* Npm or Yarn package manager: 6.13.0
* Mobile platform/version under test: N/A
* Real device or emulator/simulator: N/A
* Appium CLI or Appium.app|exe: N/A

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

$ npm install -g appium@beta
npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
/usr/local/bin/appium -> /usr/local/lib/node_modules/appium/build/lib/main.js
/usr/local/bin/authorize-ios -> /usr/local/lib/node_modules/appium/node_modules/.bin/authorize-ios

> appium-windows-driver@1.7.0 install /usr/local/lib/node_modules/appium/node_modules/appium-windows-driver
> node install-npm.js

/usr/local/lib/node_modules/appium/node_modules/appium-support/build/lib/tempdir.js:27
async function tempDir() {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/appium-support/index.js:1:1)
npm WARN notsup Unsupported engine for appium@1.16.0-beta.1: wanted: {"node":">=8","npm":">=6"} (current: {"node":"6.14.4","npm":"6.13.0"})
npm WARN notsup Not compatible with your version of node/npm: appium@1.16.0-beta.1
npm WARN notsup Unsupported engine for fsevents@2.1.1: wanted: {"node":"^8.16.0 || ^10.6.0 || >=11.0.0"} (current: {"node":"6.14.4","npm":"6.13.0"})
npm WARN notsup Not compatible with your version of node/npm: fsevents@2.1.1
npm WARN notsup Unsupported engine for which@2.0.1: wanted: {"node":">= 8"} (current: {"node":"6.14.4","npm":"6.13.0"})
npm WARN notsup Not compatible with your version of node/npm: which@2.0.1
npm WARN notsup Unsupported engine for webdriverio@5.16.2: wanted: {"node":">= 8.11.0"} (current: {"node":"6.14.4","npm":"6.13.0"})
npm WARN notsup Not compatible with your version of node/npm: webdriverio@5.16.2
npm WARN notsup Unsupported engine for serialize-error@5.0.0: wanted: {"node":">=8"} (current: {"node":"6.14.4","npm":"6.13.0"})
npm WARN notsup Not compatible with your version of node/npm: serialize-error@5.0.0
npm WARN notsup Unsupported engine for @wdio/logger@5.13.2: wanted: {"node":">= 8.11.0"} (current: {"node":"6.14.4","npm":"6.13.0"})
npm WARN notsup Not compatible with your version of node/npm: @wdio/logger@5.13.2
npm WARN notsup Unsupported engine for webdriver@5.16.2: wanted: {"node":">= 8.11.0"} (current: {"node":"6.14.4","npm":"6.13.0"})
npm WARN notsup Not compatible with your version of node/npm: webdriver@5.16.2
npm WARN notsup Unsupported engine for @wdio/repl@5.16.0: wanted: {"node":">= 8.11.0"} (current: {"node":"6.14.4","npm":"6.13.0"})
npm WARN notsup Not compatible with your version of node/npm: @wdio/repl@5.16.0
npm WARN notsup Unsupported engine for @wdio/utils@5.16.0: wanted: {"node":">= 8.11.0"} (current: {"node":"6.14.4","npm":"6.13.0"})
npm WARN notsup Not compatible with your version of node/npm: @wdio/utils@5.16.0
npm WARN notsup Unsupported engine for @wdio/config@5.16.2: wanted: {"node":">= 8.11.0"} (current: {"node":"6.14.4","npm":"6.13.0"})
npm WARN notsup Not compatible with your version of node/npm: @wdio/config@5.16.2
npm WARN notsup Unsupported engine for type-fest@0.8.1: wanted: {"node":">=8"} (current: {"node":"6.14.4","npm":"6.13.0"})
npm WARN notsup Not compatible with your version of node/npm: type-fest@0.8.1
npm WARN notsup Unsupported engine for fkill@6.2.0: wanted: {"node":">=8"} (current: {"node":"6.14.4","npm":"6.13.0"})
npm WARN notsup Not compatible with your version of node/npm: fkill@6.2.0
npm WARN notsup Unsupported engine for arrify@2.0.1: wanted: {"node":">=8"} (current: {"node":"6.14.4","npm":"6.13.0"})
npm WARN notsup Not compatible with your version of node/npm: arrify@2.0.1
npm WARN notsup Unsupported engine for taskkill@3.0.0: wanted: {"node":">=8"} (current: {"node":"6.14.4","npm":"6.13.0"})
npm WARN notsup Not compatible with your version of node/npm: taskkill@3.0.0
npm WARN notsup Unsupported engine for aggregate-error@3.0.1: wanted: {"node":">=8"} (current: {"node":"6.14.4","npm":"6.13.0"})
npm WARN notsup Not compatible with your version of node/npm: aggregate-error@3.0.1
npm WARN notsup Unsupported engine for indent-string@4.0.0: wanted: {"node":">=8"} (current: {"node":"6.14.4","npm":"6.13.0"})
npm WARN notsup Not compatible with your version of node/npm: indent-string@4.0.0

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-windows-driver@1.7.0 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium-windows-driver@1.7.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jlteruel/.npm/_logs/2019-11-07T01_40_59_330Z-debug.log

**Comment by KazuCocoa** [comment]
Please try out with NodeJS 10+ env

> Appium supports Node 10+

http://appium.io/docs/en/about-appium/getting-started/

**Comment by jpteruel095** [comment]
> Please try out with NodeJS 10+ env
> 
> > Appium supports Node 10+
> 
> http://appium.io/docs/en/about-appium/getting-started/

Hello!!! Thank you very much!!! No wonder I couldn't find any topic regarding this. Your response is a really big help!
