### ISSUE TITLE
Appium does not start the application

### ISSUE THREAD

**Issue by PythonDarkening** [appium/appium#13558]
## The problem
Appium does not start the application

## Environment
* Appium version: 1.15.1
* Node.js version: v12.12.0
* Npm  package manager: 6.11.3
* Mobile platform/version under test: Pixel Emulator API 29

## Details
Looks like that the APK has two activities

1. package.MainActivity
2. package.SplashActivity

The first time Appium launch the first activity and it expected the same activity, the second time Appium launch the second activity and it expected the same activity

The issue is that when in the second time that Appium launched the second activity it always found the first activity and it reports that the app never started

The following are the capabilities that I am using:

        'appPackage': 'com.some.Package',
        'appActivity': 'com.some.Package.MainActivity',
        'appWaitActivity': 'com.some.Package.MainActivity'

## Link to Appium logs
https://gist.github.com/PythonDarkening/1797db2eda3c8f7007268837c7fedeb4

**Comment by mykola-mokhnach** [comment]
> [debug] [ADB] Waiting up to 20000ms for activity matching pkg: 'com.timeclockplus.MobileClock' and activity: 'com.timeclockplus.MobileClock.SplashActivity' to be focused
> [debug] [ADB] Possible activities, to be checked: 'com.timeclockplus.MobileClock.SplashActivity', 'com.timeclockplus.MobileClock.com.timeclockplus.MobileClock.SplashActivity'
> [debug] [ADB] Getting focused package and activity
> [debug] [ADB] Running '/Users/hiperezr/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys window displays'
> [debug] [ADB] Found package: 'com.timeclockplus.MobileClock' and fully qualified activity name : 'com.timeclockplus.MobileClock.MainActivity'
> [debug] [ADB] Incorrect package and activity. Retrying.

I would say the exception is expected. The on-screen activity by the time Appium checks it is 'com.timeclockplus.MobileClock.MainActivity', so I would simply change the wait activity name to `com.timeclockplus.MobileClock.*`

Read https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for more details

**Comment by PythonDarkening** [comment]
after changing the wait activity name Appium still reports the error:
-  Incorrect package and activity. Retrying

since it always found
- Found package: 'com.timeclockplus.MobileClock' and fully qualified activity name : 'com.timeclockplus.MobileClock.MainActivity'

Please check the logs:
- https://gist.github.com/PythonDarkening/cb7a9e2f63003717fe8e221031fe4149

**Comment by mykola-mokhnach** [comment]
I don't observe any errors in the given logs for the case where wait activity name is set to the suggested one

**Comment by PythonDarkening** [comment]
Yes, the activity name was set to the suggested one

**Comment by PythonDarkening** [comment]
any ideas?

**Comment by imurchie** [comment]
Can you provide the logs when the suggested package/activity are specified?

**Comment by PythonDarkening** [comment]
Sure, actually the logs are in my second comment which are:

- https://gist.github.com/PythonDarkening/cb7a9e2f63003717fe8e221031fe4149

**Comment by imurchie** [comment]
What I see going on here is:
1. A session is attempted to be started with the correct capabilities, including the package and activity, and wait activity. This fails because of a timeout on the instrumentation startup (see lines 256-259)
1. Another session is attempted, with the same capabilities. This works (see line 429, and also see package/activity recognition on line 412)
1. Immediately another session is attempted, with the wrong capabilities (see line 431), which fails with the error reported here.

I don't know what is up in your script to send this broken session request.

**Comment by PythonDarkening** [comment]
Thanks, this issue looks like that happens only on my machine, closing this issue since this does not happen in a different machine.
