### ISSUE TITLE
Appium cannot set Location for iOS simulator

### ISSUE THREAD

**Issue by bhadmus** [appium/appium#13559]
## The problem

I am trying to automate my app via the iOS simulator. The app requires a location update so included the `self.instance.set_location()`. This worked on the android Emulator but fails on the iOS

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0-beta.1 (appium on terminal) 1.15.0 (appium desktop client version)
* Last Appium version that did not exhibit the issue (if applicable): Not applicable
* Desktop OS/version used to run Appium: MacOs Catalina 10.15.1
* Node.js version (unless using Appium.app|exe): v12.13.0
* Npm or Yarn package manager: 6.12.0
* Mobile platform/version under test: iOS 13.2
* Real device or emulator/simulator: iOS simulator
* Appium CLI or Appium.app|exe:

## Details
This was the error that I got on PyCharm
`
FAILED                       [100%]
test_main.py:28 (MaxngTestApp.test_book_rider)
self = <test_main.MaxngTestApp testMethod=test_book_rider>

    def setUp(self):
>       self.driver = Driver()

test_main.py:17: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../pageobjects/setup.py:40: in __init__
    self.instance.set_location(3.3792,6.5244)
/Users/bhadmus/.pyenv/versions/3.8.0/lib/python3.8/site-packages/appium/webdriver/extensions/location.py:51: in set_location
    self.execute(Command.SET_LOCATION, data)
/Users/bhadmus/.pyenv/versions/3.8.0/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py:312: in execute
    self.error_handler.check_response(response)
/Users/bhadmus/.pyenv/versions/3.8.0/lib/python3.8/site-packages/appium/webdriver/errorhandler.py:29: in check_response
    raise wde
/Users/bhadmus/.pyenv/versions/3.8.0/lib/python3.8/site-packages/appium/webdriver/errorhandler.py:24: in check_response
    super(MobileErrorHandler, self).check_response(response)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <appium.webdriver.errorhandler.MobileErrorHandler object at 0x10b055580>
response = {'status': 500, 'value': '{"value":{"error":"unknown error","message":"An unknown server-side error occurred while pro...um.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:388:37)"}}'}

    def check_response(self, response):
        """
        Checks that a JSON response from the WebDriver does not have an error.
    
        :Args:
         - response - The JSON response from the WebDriver server as a dictionary
           object.
    
        :Raises: If the response contains an error message.
        """
        status = response.get('status', None)
        if status is None or status == ErrorCode.SUCCESS:
            return
        value = None
        message = response.get("message", "")
        screen = response.get("screen", "")
        stacktrace = None
        if isinstance(status, int):
            value_json = response.get('value', None)
            if value_json and isinstance(value_json, basestring):
                import json
                try:
                    value = json.loads(value_json)
                    if len(value.keys()) == 1:
                        value = value['value']
                    status = value.get('error', None)
                    if status is None:
                        status = value["status"]
                        message = value["value"]
                        if not isinstance(message, basestring):
                            value = message
                            message = message.get('message')
                    else:
                        message = value.get('message', None)
                except ValueError:
                    pass
    
        exception_class = ErrorInResponseException
        if status in ErrorCode.NO_SUCH_ELEMENT:
            exception_class = NoSuchElementException
        elif status in ErrorCode.NO_SUCH_FRAME:
            exception_class = NoSuchFrameException
        elif status in ErrorCode.NO_SUCH_WINDOW:
            exception_class = NoSuchWindowException
        elif status in ErrorCode.STALE_ELEMENT_REFERENCE:
            exception_class = StaleElementReferenceException
        elif status in ErrorCode.ELEMENT_NOT_VISIBLE:
            exception_class = ElementNotVisibleException
        elif status in ErrorCode.INVALID_ELEMENT_STATE:
            exception_class = InvalidElementStateException
        elif status in ErrorCode.INVALID_SELECTOR \
                or status in ErrorCode.INVALID_XPATH_SELECTOR \
                or status in ErrorCode.INVALID_XPATH_SELECTOR_RETURN_TYPER:
            exception_class = InvalidSelectorException
        elif status in ErrorCode.ELEMENT_IS_NOT_SELECTABLE:
            exception_class = ElementNotSelectableException
        elif status in ErrorCode.ELEMENT_NOT_INTERACTABLE:
            exception_class = ElementNotInteractableException
        elif status in ErrorCode.INVALID_COOKIE_DOMAIN:
            exception_class = InvalidCookieDomainException
        elif status in ErrorCode.UNABLE_TO_SET_COOKIE:
            exception_class = UnableToSetCookieException
        elif status in ErrorCode.TIMEOUT:
            exception_class = TimeoutException
        elif status in ErrorCode.SCRIPT_TIMEOUT:
            exception_class = TimeoutException
        elif status in ErrorCode.UNKNOWN_ERROR:
            exception_class = WebDriverException
        elif status in ErrorCode.UNEXPECTED_ALERT_OPEN:
            exception_class = UnexpectedAlertPresentException
        elif status in ErrorCode.NO_ALERT_OPEN:
            exception_class = NoAlertPresentException
        elif status in ErrorCode.IME_NOT_AVAILABLE:
            exception_class = ImeNotAvailableException
        elif status in ErrorCode.IME_ENGINE_ACTIVATION_FAILED:
            exception_class = ImeActivationFailedException
        elif status in ErrorCode.MOVE_TARGET_OUT_OF_BOUNDS:
            exception_class = MoveTargetOutOfBoundsException
        elif status in ErrorCode.JAVASCRIPT_ERROR:
            exception_class = JavascriptException
        elif status in ErrorCode.SESSION_NOT_CREATED:
            exception_class = SessionNotCreatedException
        elif status in ErrorCode.INVALID_ARGUMENT:
            exception_class = InvalidArgumentException
        elif status in ErrorCode.NO_SUCH_COOKIE:
            exception_class = NoSuchCookieException
        elif status in ErrorCode.UNABLE_TO_CAPTURE_SCREEN:
            exception_class = ScreenshotException
        elif status in ErrorCode.ELEMENT_CLICK_INTERCEPTED:
            exception_class = ElementClickInterceptedException
        elif status in ErrorCode.INSECURE_CERTIFICATE:
            exception_class = InsecureCertificateException
        elif status in ErrorCode.INVALID_COORDINATES:
            exception_class = InvalidCoordinatesException
        elif status in ErrorCode.INVALID_SESSION_ID:
            exception_class = InvalidSessionIdException
        elif status in ErrorCode.UNKNOWN_METHOD:
            exception_class = UnknownMethodException
        else:
            exception_class = WebDriverException
        if value == '' or value is None:
            value = response['value']
        if isinstance(value, basestring):
            if exception_class == ErrorInResponseException:
                raise exception_class(response, value)
            raise exception_class(value)
        if message == "" and 'message' in value:
            message = value['message']
    
        screen = None
        if 'screen' in value:
            screen = value['screen']
    
        stacktrace = None
        if 'stackTrace' in value and value['stackTrace']:
            stacktrace = []
            try:
                for frame in value['stackTrace']:
                    line = self._value_or_default(frame, 'lineNumber', '')
                    file = self._value_or_default(frame, 'fileName', '<anonymous>')
                    if line:
                        file = "%s:%s" % (file, line)
                    meth = self._value_or_default(frame, 'methodName', '<anonymous>')
                    if 'className' in frame:
                        meth = "%s.%s" % (frame['className'], meth)
                    msg = "    at %s (%s)"
                    msg = msg % (meth, file)
                    stacktrace.append(msg)
            except TypeError:
                pass
        if exception_class == ErrorInResponseException:
            raise exception_class(response, message)
        elif exception_class == UnexpectedAlertPresentException:
            alert_text = None
            if 'data' in value:
                alert_text = value['data'].get('text')
            elif 'alert' in value:
                alert_text = value['alert'].get('text')
            raise exception_class(message, screen, stacktrace, alert_text)
>       raise exception_class(message, screen, stacktrace)
E       selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not complete operation. Make sure Simulator UI is running and the parent Appium application (e. g. Appium.app or Terminal.app) is present in System Preferences > Security & Privacy > Privacy > Accessibility list. If the operation is still unsuccessful then it is not supported by this Simulator. Original error: Command 'osascript -e '
E             tell application "System Events"
E               tell process "Simulator"
E                 set frontmost to false
E                 set frontmost to true
E                 click (menu item 1 where (its name contains "iPhone 8 " and its name contains "13.2")) of menu 1 of menu bar item "Window" of menu bar 1
E               end tell
E             end tell
E           
E       
E             tell application "System Events"
E               tell process "Simulator"
E                 set featureName to "Custom Location"
E                 set dstMenuItem to menu item (featureName & "…") of menu 1 of menu item "Location" of menu 1 of menu bar item "Debug" of menu bar 1
E                 click dstMenuItem
E                 delay 1
E                 set value of text field 1 of window featureName to 3.3792 as string
E                 delay 0.5
E                 set value of text field 2 of window featureName to 6.5244 as string
E                 delay 0.5
E                 click button "OK" of window featureName
E                 delay 0.5
E                 set isInvisible to (not (exists (window featureName)))
E               end tell
E             end tell
E           '' exited with code 1

/Users/bhadmus/.pyenv/versions/3.8.0/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py:242: WebDriverException

`

## Link to Appium logs

https://gist.github.com/bhadmus/f44fe40bca3156f56fc49581a57a152f

**Comment by mykola-mokhnach** [comment]
The error above is expected. Appium first tries to set location using `idb` tool, which is not installed. After this fails it tries to do the same via Apple Script, which obviously fails. So you either should make idb working or the above Apple Script.

**Comment by bhadmus** [comment]
I have installed idb and the Appium-Desktop crashes immediately

The error on Pycharm is 
`
test_main.py:28 (MaxngTestApp.test_book_rider)
self = <test_main.MaxngTestApp testMethod=test_book_rider>

    def setUp(self):
>       self.driver = Driver()

test_main.py:17: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../pageobjects/setup.py:39: in __init__
    self.instance = webdriver.Remote('http://127.0.0.1:4723/wd/hub', desired_caps)
/Users/bhadmus/.pyenv/versions/3.8.0/lib/python3.8/site-packages/appium/webdriver/webdriver.py:140: in __init__
    super(WebDriver, self).__init__(
/Users/bhadmus/.pyenv/versions/3.8.0/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py:154: in __init__
    self.start_session(desired_capabilities, browser_profile)
/Users/bhadmus/.pyenv/versions/3.8.0/lib/python3.8/site-packages/appium/webdriver/webdriver.py:219: in start_session
    response = self.execute(RemoteCommand.NEW_SESSION, parameters)
/Users/bhadmus/.pyenv/versions/3.8.0/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py:310: in execute
    response = self.command_executor.execute(driver_command, params)
/Users/bhadmus/.pyenv/versions/3.8.0/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py:466: in execute
    return self._request(command_info[0], url, body=data)
/Users/bhadmus/.pyenv/versions/3.8.0/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py:490: in _request
    resp = self._conn.getresponse()
/Users/bhadmus/.pyenv/versions/3.8.0/lib/python3.8/http/client.py:1322: in getresponse
    response.begin()
/Users/bhadmus/.pyenv/versions/3.8.0/lib/python3.8/http/client.py:303: in begin
    version, status, reason = self._read_status()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <http.client.HTTPResponse object at 0x104124460>

    def _read_status(self):
        line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
        if len(line) > _MAXLINE:
            raise LineTooLong("status line")
        if self.debuglevel > 0:
            print("reply:", repr(line))
        if not line:
            # Presumably, the server closed the connection before
            # sending a valid response.
>           raise RemoteDisconnected("Remote end closed connection without"
                                     " response")
E           http.client.RemoteDisconnected: Remote end closed connection without response

/Users/bhadmus/.pyenv/versions/3.8.0/lib/python3.8/http/client.py:272: RemoteDisconnected

Assertion failed
`

This is appium-doctor 

> info AppiumDoctor Appium Doctor v.1.12.1
info AppiumDoctor ### Diagnostic for necessary dependencies starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: /usr/local/bin/node
info AppiumDoctor  ✔ Node version is 12.13.0
info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ Xcode Command Line Tools are installed in: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ DevToolsSecurity is enabled.
info AppiumDoctor  ✔ The Authorization DB is set up properly.
info AppiumDoctor  ✔ Carthage was found at: /usr/local/bin/carthage. Installed version is: 0.34.0
info AppiumDoctor  ✔ HOME is set to: /Users/bhadmus
info AppiumDoctor  ✔ ANDROID_HOME is set to: /Users/bhadmus/Library/Android/sdk
info AppiumDoctor  ✔ JAVA_HOME is set to: /Library/Java/JavaVirtualMachines/jdk-13.0.1.jdk/Contents/Home
info AppiumDoctor  ✔ adb exists at: /Users/bhadmus/Library/Android/sdk/platform-tools/adb
info AppiumDoctor  ✔ android exists at: /Users/bhadmus/Library/Android/sdk/tools/android
info AppiumDoctor  ✔ emulator exists at: /Users/bhadmus/Library/Android/sdk/tools/emulator
info AppiumDoctor  ✔ Bin directory of $JAVA_HOME is set
info AppiumDoctor ### Diagnostic for necessary dependencies completed, no fix needed. ###
info AppiumDoctor 
info AppiumDoctor ### Diagnostic for optional dependencies starting ###
info AppiumDoctor  ✔ opencv4nodejs is installed at: /usr/local/lib. Installed version is: 5.4.0
info AppiumDoctor  ✔ ffmpeg is installed at: /usr/local/bin/ffmpeg. ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
info AppiumDoctor  ✔ mjpeg-consumer is installed at: /usr/local/lib. Installed version is: 2.0.0
info AppiumDoctor  ✔ idb and idb_companion are installed
info AppiumDoctor  ✔ applesimutils is installed at: /usr/local/bin/applesimutils. Installed versions are: applesimutils 0.7.6
WARN AppiumDoctor  ✖ bundletool.jar cannot be found
info AppiumDoctor ### Diagnostic for optional dependencies completed, one fix possible. ###
info AppiumDoctor 
info AppiumDoctor ### Optional Manual Fixes ###
info AppiumDoctor The configuration can install optionally. Please do the following manually:
WARN AppiumDoctor  ➜ bundletool.jar is used to handle Android App Bundle. Please read http://appium.io/docs/en/writing-running-appium/android/android-appbundle/ to install it
info AppiumDoctor 
info AppiumDoctor ###
info AppiumDoctor 
info AppiumDoctor Bye! Run appium-doctor again when all manual fixes have been applied!
info AppiumDoctor

**Comment by bhadmus** [comment]
So how can I make AppleScript work? because I think I should uninstall idb because it is causing Appium to crash

**Comment by mykola-mokhnach** [comment]
>  I think I should uninstall idb because it is causing Appium to crash

this is third party utility. If it crashes then it, probably, means Facebook does not support iOS 13.2 yet.

> So how can I make AppleScript work

Try to debug it manually using Apple Script editor. If it works manually then make sure Appium process has appropriate system permissions for script execution like it is described in the error message above.

Unfortunately Apple does not provide any other APIs which would allow to change location

**Comment by bhadmus** [comment]
Is there  a documentation that I can read that can help me learn how to do this? Or is there a list of steps to follow somewhere? Please advice, I am new to iOS Automation

> Try to debug it manually using Apple Script editor. If it works manually then make sure Appium process has appropriate system permissions for script execution like it is described in the error message above.

Unfortunately Apple does not provide any other APIs which would allow to change location

**Comment by mykola-mokhnach** [comment]
Try to ask at Appium forum

**Comment by bhadmus** [comment]
`
class Driver:

    def __init__(self):
        desired_caps = {}
        desired_caps['platformName'] = 'iOS'
        # desired_caps['build'] = "Python Android"
        # desired_caps["browserstack.gpsLocation"] = "3.3792,6.5244"
        desired_caps['platformVersion'] = '13.2'
        desired_caps['deviceName'] = 'iPhone 8'
        desired_caps["automationName"] = "XCUITest"
        # desired_caps["locationContextEnabled"] = True
        # desired_caps["locationServicesEnabled"] = True
        # desired_caps["locationServicesAuthorized"] = True
        # desired_caps["bundleId"] = "ng.max.go"
        desired_caps["app"] = app


        self.instance = webdriver.Remote('http://127.0.0.1:4723/wd/hub', desired_caps)
        self.instance.set_location(3.3792,6.5244)
`
That is the code that I have and I have also updated my appium to appium@beta and it still wouldn't work

`
[W3C (d6335bef)]       tell application "System Events"
[W3C (d6335bef)]         tell process "Simulator"
[W3C (d6335bef)]           set featureName to "Custom Location"
[W3C (d6335bef)]           set dstMenuItem to menu item (featureName & "…") of menu 1 of menu item "Location" of menu 1 of menu bar item "Debug" of menu bar 1
[W3C (d6335bef)]           click dstMenuItem
[W3C (d6335bef)]           delay 1
[W3C (d6335bef)]           set value of text field 1 of window featureName to 3.3792 as string
[W3C (d6335bef)]           delay 0.5
[W3C (d6335bef)]           set value of text field 2 of window featureName to 6.5244 as string
[W3C (d6335bef)]           delay 0.5
[W3C (d6335bef)]           click button "OK" of window featureName
[W3C (d6335bef)]           delay 0.5
[W3C (d6335bef)]           set isInvisible to (not (exists (window featureName)))
[W3C (d6335bef)]         end tell
[W3C (d6335bef)]       end tell
[W3C (d6335bef)]     '' exited with code 1
[W3C (d6335bef)]     at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-support/lib/logging.js:78:13)
[W3C (d6335bef)]     at errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-ios-simulator/lib/simulator-xcode-6.js:989:13)
[HTTP] <-- POST /wd/hub/session/d6335bef-7efb-49d5-8052-217d48cabd27/location 500 480 ms - 3383
[HTTP] 
`

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing more on Appium side we could do to change this behaviour. Like I said try to debug the Apple Script above and make sure the Appium process has enough permissions to execute it.

Closed as not issue.
