### ISSUE TITLE
Can we have opencv4nodejs as part of appium package?

### ISSUE THREAD

**Issue by sumeetpanjabi** [appium/appium#13550]
## The problem

I am trying to use findElementByImage and running my test on BrowserStack. My project is a Gradle project. Is there any way we can have opencv4nodejs installation as part of the Appium package?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: Android 9.0
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

I'm getting the following error running my Appium tests on BrowserStack real device.
org.openqa.selenium.WebDriverException: Appium error: An unknown server-side error occurred while processing the command. Original error: 'opencv4nodejs' module is required to use OpenCV features. Please install it first ('npm i -g opencv4nodejs') and restart Appium. Read https://github.com/justadudewhohacks/opencv4nodejs#how-to-install for more details on this topic. (WARNING: The server did not provide any stacktrace information)

The option I have is to install opencv4nodejs using 

npm i -g opencv4nodejs , but I don't know I will have the proper rights to install.

Any other work around for this?

**Comment by mykola-mokhnach** [comment]
this is not going to happen because opencv itself is a very big package and requires lot of dependencies. this means that Appium installation could take tens of minutes of not hours if opencv is included there. Consider contacting BS, so they could include the necessary modules into the remote machine.

**Comment by sumeetpanjabi** [comment]
Okay @mykola-mokhnach 
Thanks
