### ISSUE TITLE
Appium server keeps spawing adb proccess

### ISSUE THREAD

**Issue by neoyagami** [appium/appium#13554]
## The problem
Hi 
We use appiu to test apps, its works fine, pur problem happens when the servers keeps runing for a period of time
its keeps spawing adb process until it uses all the ports designed,

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): nevert tryed other version
* Desktop OS/version used to run Appium: centos 7.6
* Node.js version (unless using Appium.app|exe): 12.12.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: 8.0.0
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

After some time the appium says there is no more ports to open adb

we reaced something like 1000 process before the tests stop runing

<img width="962" alt="Captura de Pantalla 2019-11-06 a la(s) 12 59 20" src="https://user-images.githubusercontent.com/3663321/68315043-f6dc9600-0095-11ea-9e30-db2e27070197.png">

**Comment by mykola-mokhnach** [comment]
Are you sure you quit your sessions properly?

**Comment by neoyagami** [comment]
at the end of every run 

            driver.quit();

even the app is closed in the phone/emulator

**Comment by mykola-mokhnach** [comment]
Without server logs it is hard to guess anything

**Comment by mykola-mokhnach** [comment]
Closed as incomplete
