### ISSUE TITLE
Encountered internal error with mjpegScreenshotUrl

### ISSUE THREAD

**Issue by aupong** [appium/appium#13560]
## The problem
Try using the mjpegScreenshotUrl to get the screenshots. But after running for some time, Error occured

## Environment

* Appium version (or git revision) that exhibits the issue: v1.15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Ubuntu 18.04
* Node.js version (unless using Appium.app|exe): 13.0.1
* Npm or Yarn package manager:
* Mobile platform/version under test: Android 7.1.2
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Details
Running the app Screen Stream over HTTP as the mjpeg server to get the screenshots 
After running for some time (30 mins to 50 mins), Internal server error with the following 

Encountered internal error running command: Error: Could not find MIME for Buffer <null>

## Link to Appium logs

https://gist.github.com/aupong/d530c8e1521fde9ed518e1f1bf5f386a#file-gistfile1-txt

**Comment by mykola-mokhnach** [comment]
cc @jlipps

**Comment by mykola-mokhnach** [comment]
This might be a memory leak issue - can you try appium@beta?

**Comment by aupong** [comment]
tried v1.16.0-beta.1
But the same occurred. 
Is it related to the mjpeg server? I tried reducing the frame rate, the error seems to be less often.

**Comment by mykola-mokhnach** [comment]
I could make some fixes there, but I would need your help to test them. Would such approach work for you?

**Comment by aupong** [comment]
Yes, sure
Please provide information on how to test your fixes when you are ready

**Comment by mykola-mokhnach** [comment]
Please apply https://github.com/appium/appium-support/pull/140 to your local source and see if it works. https://github.com/appium/appium/issues/13227#issuecomment-531812534 contains more info on how to do that (it is for xcuitest driver, but the procedure is the same for all modules).

**Comment by aupong** [comment]
Just tested with your code, and run for about 90 minutes, The error is gone.

Will try another test later tonight.

**Comment by mykola-mokhnach** [comment]
The patch has been published to appium@beta

thanks for checking it
