### ISSUE TITLE
Unable to run tests in Appium CLI and Desktop app

### ISSUE THREAD

**Issue by Yurv25** [appium/appium#13564]
## The problem

I tried to run a script but keep getting those errors described in the logs. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 1.15.1
* Node.js version (unless using Appium.app|exe):  6.12.0
* Mobile platform/version under test: Android 9.0
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: both

## Details

If'm just trying to run the script below and getting those issues described in the logs, even If I'm only trying to create a session using the Desktop app. Both command line and desktop give me the same issue. 
Any help appreciated , thanks!

## Link to Appium logs

https://gist.github.com/Yurv25/02ef3976cb87aa43a19db253920e1d81

## Code To Reproduce Issue [ Good To Have ]

public class Main {

    public static void main(String[] args) throws MalformedURLException {
	// write your code here
        DesiredCapabilities dc = new DesiredCapabilities();

        dc.setCapability(MobileCapabilityType.DEVICE_NAME,"emulator-5554");
        dc.setCapability("platformName","android");
        dc.setCapability("appPackage","com.cabify.qabify");
        dc.setCapability("appActivity",".MainActivity");

        AndroidDriver<AndroidElement> ad = new AndroidDriver<AndroidElement>(new URL("http://127.0.0.1:3300/wd/hub"),dc);

        MobileElement e1 = (MobileElement) ad.findElementById("com.cabify.qabify:id/user_name_edit_text");
        e1.sendKeys("user");

        Assert.assertEquals(ad.findElementById("com.cabify.qabify:id/user_name_edit_text").getText(),"user");

    }
}

**Comment by mykola-mokhnach** [comment]
Please try the solutions from https://github.com/appium/appium/issues?q=is%3Aissue+remoteAppsCacheLimit+is%3Aclosed

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
