### ISSUE TITLE
iOSDriver unable to fully launch

### ISSUE THREAD

**Issue by WoodPlank** [appium/appium#13565]
## The problem

I have a hybrid ios app. It successfully opens the Settings app but it fails to get past launching the app when I instantiate the IOSDriver using "http://0.0.0.0:4723/wd/hub/" and my capabilities. In the logs it will say something like the following (Notice how long it takes between lines 3 and 4 - It seems to get stuck on "Setting communication protocol: using Target-based communication"):
```
11:38:08 [iProxy@3c21a...] Connection was refused to port 9119
11:38:23 [RemoteDebugger] Setting communication protocol: using full Web Inspector protocol communication
11:38:23 [RemoteDebugger] Setting communication protocol: using Target-based communication
11:47:02 Tests run: 59, Failures: 2, Errors: 0, Skipped: 57, Time elapsed: 649.856 sec <<< FAILURE! - in TestSuite
11:47:02 setUp(Test.Smoke.Test_Smoke)  Time elapsed: 639.473 sec  <<< FAILURE!
11:47:02 org.openqa.selenium.SessionNotCreatedException: 
11:47:02 Unable to create a new remote session. Original error: unexpected end of stream on Connection{0.0.0.0:4723, proxy=DIRECT hostAddress=/0.0.0.0:4723 cipherSuite=none protocol=http/1.1}
11:47:02 Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
11:47:02 System info: host: 'QAiOSs-iMac.local', ip: '172.31.5.114', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '1.8.0_151'
11:47:02 Driver info: driver.version: IOSDriver
11:47:02 Caused by: java.lang.reflect.InvocationTargetException
11:47:02 Caused by: java.io.IOException: unexpected end of stream on Connection{0.0.0.0:4723, 
proxy=DIRECT hostAddress=/0.0.0.0:4723 cipherSuite=none protocol=http/1.1}
11:47:02 Caused by: java.io.EOFException: \n not found: limit=0 content=…
11:47:02 
11:47:02 tearDown(Test.Smoke.Test_Smoke)  Time elapsed: 0.001 sec  <<< FAILURE!
11:47:02 java.lang.NullPointerException
```

## Environment

* Appium version: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): 1.14.2 I believe
* MacOS version used to run Appium: 10.14.6
* Node.js version: 12.11.1
* Npm version: 6.11.3
* Mobile platform/version under test: 12.4.1
* Real device or emulator/simulator: Real device

## Details

I'm not able to proceed past the instantiation of the iOSDriver to automate my hybrid app. It was working well before I updated a few things to prepare for ios 13 automation. I updated Appium, xcode, iOS OS version, and a few other things after not making any progress (like reinstalling libimobiledevice, ios-webkit-debug-proxy, and I believe 2 other related modules). It seems like it gets stuck on these 2 things for a while and then the automation fails: 

1. Setting communication protocol: using full Web Inspector protocol communication
2. Setting communication protocol: using Target-based communication

## Link to Appium logs
[Link to gist](https://gist.github.com/WoodPlank/b22dab4d80ed07007f836d18bd83b3ff)

## Code To Reproduce Issue [ Good To Have ]
```java
File app = new File(ipaPath);
				
capabilities.setCapability("automationName", "XCUITest");
capabilities.setCapability("xcodeOrgId", "**********");
capabilities.setCapability("xcodeSigningId", "iPhone Developer");
capabilities.setCapability("automationName", "XCUITest");
capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, deviceName);
capabilities.setCapability(MobileCapabilityType.UDID, deviceUdid);
capabilities.setCapability("noReset", true);
capabilities.setCapability("clearSystemFiles", true);
capabilities.setCapability("platformName", platform);
capabilities.setCapability("platformVersion", deviceVersion);
capabilities.setCapability("unicodeKeyboard", true);
capabilities.setCapability("autoWebView", true);
capabilities.setCapability(MobileCapabilityType.AUTO_WEBVIEW, true);
capabilities.setCapability("showIOSLog", true);
capabilities.setCapability("absoluteWebLocations", true);
capabilities.setCapability("startIWDP", true);
capabilities.setCapability("webkitResponseTimeout", 20000);
capabilities.setCapability("webkitDebugProxyPort", webkitDebugProxyPort);
capabilities.setCapability("wdaLocalPort", wdaLocalPort);
capabilities.setCapability("skipLogCapture", true);
capabilities.setCapability("app", app.getAbsolutePath());
capabilities.setCapability("newCommandTimeout", 0); // 15 minutes
				
driver = new IOSDriver(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);
```

**Comment by imurchie** [comment]
Please try the most recent beta of Appium (`npm uninstall -g appium && npm install -g appium@beta`).

If the problem persists, we will need the _full_ Appium server logs (as a link to a [gist](https://gist.github.com)) in order to be of any help.

**Comment by WoodPlank** [comment]
[Link to gist](https://gist.github.com/WoodPlank/b22dab4d80ed07007f836d18bd83b3ff.js)

**Comment by WoodPlank** [comment]
@imurchie Just thought I'd check in. Any update on this? I saw the change in tags. If there's anything you'd like me to provide I can do so.

**Comment by WoodPlank** [comment]
I believe this may be related to https://github.com/appium/appium/issues/13569 because the app I'm referencing is a hybrid app that lists the available contexts. I will try the referenced solution in the ticket I referenced and let you know how it goes.

**Comment by WoodPlank** [comment]
After updating these dependencies:
- appium-xcuitest-driver should be at least v3.6.0
- appium-ios-device should be at least v1.2.1
- appium-remote-debugger should be at least v6.7.0

and removing the IWDP capabilities it is working on iOS 12.X
