### ISSUE TITLE
Individual emulator failed to get process ID

### ISSUE THREAD

**Issue by chenxiaolao** [appium/appium#13567]
## The problem

![image](https://user-images.githubusercontent.com/22992372/68455246-d9dec900-0235-11ea-905b-284bf45844cf.png)

normal：
![image](https://user-images.githubusercontent.com/22992372/68455318-0abefe00-0236-11ea-9854-85642d25236d.png)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): 1.13.0
* Desktop OS/version used to run Appium:  windows 10
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: Android 5.0.1
* Real device or emulator/simulator:  雷电模拟器http://www.leidianmoniqi.com
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

[ADB] Getting IDs of all 'io.appium.settings' processes
[ADB] Running 'E:\android\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pgrep \^appium\\.settings\$'
[ADB] Getting IDs of all 'io.appium.settings' processes
[ADB] Running 'E:\android\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pgrep \^appium\\.settings\$'
[ADB] Getting IDs of all 'io.appium.settings' processes
[ADB] Running 'E:\android\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pgrep \^appium\\.settings\$'
[ADB] Getting IDs of all 'io.appium.settings' processes
[ADB] Running 'E:\android\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pgrep \^appium\\.settings\$'
[AndroidDriver] Failed to launch Appium Settings app: Condition unmet after 5183 ms. Timing out.
[UiAutomator2] Deleting UiAutomator2 session
[ADB] Running 'E:\android\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe -P 5037 -s emulator-5554 shell am force-stop com.android.launcher3'
[ADB] Removing forwarded port socket connection: 8200 
[ADB] Running 'E:\android\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe -P 5037 -s emulator-5554 forward --remove tcp\:8200'
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command 'E:\\android\\android-sdk_r24.4.1-windows\\android-sdk-windows\\platform-tools\\adb.exe -P 5037 -s emulator-5554 forward --remove tcp\:8200' exited with code 1'; Stderr: 'adb.exe: error: listener 'tcp:8200' not found'; Code: '1''
[BaseDriver] Event 'newSessionStarted' logged at 1573184907679 (11:48:27 GMT+0800 (中国标准时间))
[MJSONWP] Encountered internal error running command: Error: Failed to launch Appium Settings app: Condition unmet after 5183 ms. Timing out.
[MJSONWP]     at spin (C:\Users\66\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\asyncbox\lib\asyncbox.js:127:9)
[HTTP] <-- POST /wd/hub/session 500 12850 ms - 217

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by chenxiaolao** [comment]
android 5.1.1
![image](https://user-images.githubusercontent.com/22992372/68457835-3644e700-023c-11ea-94df-01d007f30746.png)

android 6.0.1
![image](https://user-images.githubusercontent.com/22992372/68457869-55437900-023c-11ea-8fed-cde853a22d22.png)

**Comment by mykola-mokhnach** [comment]
yep, a nasty bug there :(
I'll add another condition to the code, so it will always use `ps` output instead of pgrep for process detection if android version is below 6.0

**Comment by mykola-mokhnach** [comment]
The patch has been published to appium@beta
