### ISSUE TITLE
iOS 13: Unable to tap on the back button from webview to app

### ISSUE THREAD

**Issue by J320** [appium/appium#13575]
## The problem

When testing native apps with links that open up on browsers, in order to test the links one could verify them from the web address bar and then tap on the native back button to go back to the app (which would have a back arrow and the name of the app on the right), usually this element could be located with accessibility ID as 'breadcrumb'. 

From iOS 13 onwards, this element is no longer locatable using Appium Inspector and trying to interact with it with the same locator will return `element not found` error. The exact same page inspected with an iOS older than 13 can still locate the button and interact with it if the test is run with a simulator running that older iOS version.

## Environment

* iOS version that exhibits the issue: iOS 13+
* Last iOS version that did not exhibit the issue: iOS 12.4

**Comment by mykola-mokhnach** [comment]
If the element is not present in the page source then it means XCTest does not find it in the accessibility. I don't think there's anything we could do on appium side to solve that

**Comment by EstevanBR** [comment]
the "breadcrumb" is visible to the accessibility inspector, and to xcuitest recording. just not to appium it seems.

the workaround I found, is to just perform a `TouchAction` at x=5,y=5 to click the "Back to FooBar" breadcrumb button.

its not the best, but it got our tests running again.
hope that helps.

**Comment by mykola-mokhnach** [comment]
It would be interesting to compare the `mobile: source` output for `description` and `xml` source types.

**Comment by mykola-mokhnach** [comment]
Unfortunately there's nothing more we can do on this problem from Appium side.
Closed as third party issue.
