### ISSUE TITLE
Unable to tap on element on some devices

### ISSUE THREAD

**Issue by walkeraki** [appium/appium#13578]
## The problem

When having appium inspector open with any app and trying to tap on any element nothing happens. Some devices (tested on 3 samsung devices) have different size of app in regards to actual screen. 
[screenshot1](https://prnt.sc/pv9bja)
With "adb shell dumpsys window" command we see this line
 Surface: shown=true layer=21025 alpha=1.0 rect=(0.0,150.0) 810.0 x 1440.0 transform=(1.3333334, 0.0, 0.0, 1.3333334)
      mGlobalScale=1.0 mDsDx=1.3333334 mDtDx=0.0 mDtDy=0.0 mDsDy=1.3333334

And this is the problem.. Appium is getting wrong location of element. If you multiple that location with 1.3333 then it works.

On appium it can be seen like this:
[screenshot2](https://prnt.sc/pv9bqh)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.0
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Samsung A8, Samsung s10
* Appium CLI or Appium.app|exe: Appium.exe

## Link to Appium logs

https://gist.github.com/walkeraki/e6a0d5ffcd42fc90d63c87bef4feb697

## Code To Reproduce Issue [ Good To Have ]

No code.. Just appium inspector

**Comment by mykola-mokhnach** [comment]
UiAutomator1 is obsolete and should not be used to automate Android 6+

**Comment by walkeraki** [comment]
Also tried with automator 2.. Same thing happens

**Comment by mykola-mokhnach** [comment]
There is no magic. We simply execute the standard `click` handler, which is provided by UIA2 framework. 

What you could do:
- Describe the problem to Google
- Tap custom coordinates on the client side. Coordinates recalculation should be done based on the actual custom scaling
- Try Espresso automation backend. Perhaps, it works better

**Comment by walkeraki** [comment]
But does that click handler take scaling in consideration? Because on all devices with that scaling which by the looks of it are all samsung devices , inspector tap would not work.. All locations of elements are wrong therefor click is not working. Shouldnt appium handle cases like that? Keep in mind i dont do any scaling.. this is all automatically done by device. I could do custom tap with recalculated coordinates but it still would not fix problem where tap is not working in inspector.
I am talking about this button:
[button](https://prnt.sc/pveym4)

**Comment by mykola-mokhnach** [comment]
In my opinion the current implementation of UIA2 server works properly and I don't see anything there, which could be changed in order to supported the described scenario, except of the UIA2 framework itself (which is maintained by Google). 

Although, if you can propose a good way to solve the issue then feel free to create a PR. We are always happy to accept new useful contributions.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
