### ISSUE TITLE
Could not proxy command to remote server. Original error: Error: socket hang up

### ISSUE THREAD

**Issue by monsam** [appium/appium#13576]
## The problem

Appium server crapping out Error: socket hang up when running 20 tests together, running test one after the other has no problem.

please check the log attached bellow

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.14.2
* Last Appium version that did not exhibit the issue (if applicable):NA
* Desktop OS/version used to run Appium: Ubuntu Linux
* Node.js version (unless using Appium.app|exe):NA
* Npm or Yarn package manager:NA
* Mobile platform/version under test: Android 8.0
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

https://gist.githubusercontent.com/monsam/24602b441af44bb6a792daa42af8d57f/raw/047131b9e44127d23075b81f5a140a4a7e7a22ec/appium4729.log

**Comment by mykola-mokhnach** [comment]
I don't observe any errors in the attached server log. Please check the logcat output for the time period where the disconnect happens. Also make sure there are no network issues and Doze mode is disabled for the Appium server app.

**Comment by mykola-mokhnach** [comment]
I don't think this problem has anything to do with Appium itself based on the available logs.

Closed as third party issue
