### ISSUE TITLE
Couldn't push 2GB ipa in timeout(30sec in ios-deploy(appium-xcuitest-driver))

### ISSUE THREAD

**Issue by kkb912002** [appium/appium#13577]
## The problem

Always, timeout occurred on pushing app(2GB).

## Environment

iPhone X

## Details

I changed ITEM_PUSH_TIMEOUT constant to 300sec by editing ios-deploy.js file.
Then, pushing the app was successful.(109sec)
```
[XCUITest] Pushed the app files successfully after 109047ms
```
I think it need to be one of the caps of xcuitest-driver.

thanks

**Comment by mykola-mokhnach** [comment]
The improvement has been published to appium@beta
The capability name is `appPushTimeout`. There is also a fallback to `ios-deploy` in case the push fails.
