### ISSUE TITLE
 Unhandled endpoint: /session/350B4B84-59A7-45A9-BD45-B11E65849D06/frame -- http://localhost:8100/ with parameters 

### ISSUE THREAD

**Issue by tahirakhlaaq** [appium/appium#13581]
## The problem

Getting Below Error after app launched:

value":{"error":"unknown command","message":"Unhandled endpoint: /session/653E2047-8D9C-4515-ADC2-CFFC058D0289/frame -- http://localhost:8100/ with parameters {\n    wildcards =     (\n        \"session/653E2047-8D9C-4515-ADC2-CFFC058D0289/frame\"\n    );\n}","traceback":""},"sessionId":"653E2047-8D9C-4515-ADC2-CFFC058D0289"}
[debug] 

[W3C (c9e6d43f)] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: 404 - {"value":{"error":"unknown command","message":"Unhandled endpoint: /session/653E2047-8D9C-4515-ADC2-CFFC058D0289/frame -- http://localhost:8100/ with parameters {\n    wildcards =     (\n        \"session/653E2047-8D9C-4515-ADC2-CFFC058D0289/frame\"\n    );\n}","traceback":""},

## Environment

* Appium version (or git revision) that exhibits the issue: V1.15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: V1.15.1
* Node.js version (unless using Appium.app|exe): 12.12.0
* Mobile platform/version under test:iOS 13.1
* Real device or emulator/simulator: Real Device iPhone X
* Appium CLI or Appium.app|exe: Appium app

## Details

Getiing this Error one APP get launched and try to find the Element
## Link to Appium logs

[https://gist.github.com/tahirakhlaaq/8f963892f3d7750d5fea8fe0618051ec](url)

**Comment by mykola-mokhnach** [comment]
what are you trying to achieve there?
`/frame` call in native context does not make any sense

**Comment by tahirakhlaaq** [comment]
@mykola-mokhnach I'm performing a simple click on an element, Nothing special so confused with the log.

**Comment by KazuCocoa** [comment]
Appium got below command by your side.
What was your test code? I guess your test client (or framework?) sent it to appium.

```
[info] [HTTP] [info] [HTTP] [37m-->[39m [37mPOST[39m [37m/wd/hub/session/c9e6d43f-9d2f-44dc-a371-a985784b8ffe/frame[39m
```

**Comment by tahirakhlaaq** [comment]
yes!! thanks for help!
