### ISSUE TITLE
Dismissing iOS alerts stopped working after moving to xCode 11.1

### ISSUE THREAD

**Issue by BoazWarshawsky** [appium/appium#13587]
## The problem
I found that the following python method:
`driver.switch_to.alert.dismiss()`
it seems that already `driver.switch_to.alert` is null
stopped working when I upgraded my xCode from` 10.2.0` to `11.1.0`

## Environment

* Appium version (or git revision) that exhibits the issue: 14.0, 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): 14.0
* Desktop OS/version used to run Appium: CLI and Desktop, both not working
* Node.js version (unless using Appium.app|exe): 8.12.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Simulator (iPhone XS Max, OS 12.0)
* Appium CLI or Appium.app|exe: cli and app

## Details
I also tried calling alerts.accept() but it did not work. 

## Link to Appium logs
https://assets-production.applicaster.com/qa/zapp_qa/manual/boaz/appium.log

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by BoazWarshawsky** [comment]
@KazuCocoa can you please help me with this issue? All my CI started failing because of that.

Thanks!

**Comment by KazuCocoa** [comment]
```
[debug] [35m[WD Proxy][39m Matched '/alert/text' to command name 'getAlertText'
[debug] [35m[WD Proxy][39m Proxying [GET /alert/text] to [GET http://localhost:8100/session/A5112821-A7B5-4C66-A6F0-14842A888918/alert/text] with no body
[debug] [35m[WD Proxy][39m Got response with status 200: "{\n  \"value\" : \"-[XCUIElement resolve]: unrecognized selector sent to instance 0x600001ba8fa0\\n\\n(\\n\\t0   CoreFoundation                      0x000000010624c29b __exceptionPreprocess + 331\\n\\t1   libobjc.A.dylib                     0x00000001057e8735 objc_exception_throw + 48\\n\\t2   CoreFoundation                      0x000000010626afa4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132\\n\\t3   CoreFoundation                      0x0000000106250fb6 ___forwarding___ + 1446\\n\\t4   CoreFoundation                      0x0000000106252e88 _CF_forwarding_prep_0 + 120\\n\\t5   WebDriverAgentLib                   0x000000011d0926f5 -[FBAlert alertElement] + 405\\n\\t6   WebDriverAgentLib                   0x000000011d0909ee -[FBAlert text] + 62\\n\\t7   WebDriverAgentLib                   0x000000011d086745 +[FBAlertViewCommands handleAlertGetTextCommand:] + 165\\n\\t8   WebDriverAgentLib                   0x000000011d0638d6 -[FBRoute_TargetAction mountRequest:intoResponse:] + 182\\n\\t9   WebDriv...
[debug] [35m[MJSONWP][39m Matched JSONWP error code 13 to UnknownError
[debug] [35m[W3C (86dcd370)][39m Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: -[XCUIElement resolve]: unrecognized selector sent to instance 0x600001ba8fa0
[debug] [35m[W3C (86dcd370)][39m 
[debug] [35m[W3C (86dcd370)][39m (
[debug] [35m[W3C (86dcd370)][39m 	0   CoreFoundation                      0x000000010624c29b __exceptionPreprocess + 331
[debug] [35m[W3C (86dcd370)][39m 	1   libobjc.A.dylib                     0x00000001057e8735 objc_exception_throw + 48
[debug] [35m[W3C (86dcd370)][39m 	
```

`unrecognized selector`
This error happens on Xcode 11 environment. Appium 1.15 and the WDA should resolve the issue.

Could you attach the log of 1.15.1 version?
Make sure your WDA running on the test device also built by Appium 1.15 source(sometimes npm cache older module. So, it's preferred to uninstall old appium 1.14 before installing 1.15)
Your node environment also should be over 10.x from 1.14.0 https://github.com/appium/appium/releases/tag/v1.14.0
>  Minimum Node version is bumped up to v10

**Comment by BoazWarshawsky** [comment]
@KazuCocoa with Appium `1.15.1` I have other weird issue that the app opens without connectivity, same app.
I am checking now `1.15`

**Comment by BoazWarshawsky** [comment]
@KazuCocoa I am not able to start the test with 1.15.0, application not even launching saying that web agent driver not found.
Logs: https://assets-production.applicaster.com/qa/zapp_qa/manual/boaz/appium_no_wda.log

**Comment by KazuCocoa** [comment]
Carthage failed to get dependencies to build WDA because of a permission problem. Please make sure your permission. (The process hadn't changed from 1.14 though)

```
[35m[XCUITest][39m Launching WebDriverAgent on the device
[35m[WebDriverAgent][39m Fetching dependencies
[35m[WebDriverAgent][39m Installing/updating dependencies for platforms 'iOS', 'tvOS'
[debug] [35m[WebDriverAgent][39m *** Checking out RoutingHTTPServer at "v1.0.2"
[debug] [35m[WebDriverAgent][39m *** Checking out YYCache at "1.1.0"
[debug] [35m[WebDriverAgent][39m *** Checking out CocoaAsyncSocket at "7.6.3"
[debug] [35m[WebDriverAgent][39m Failed to check out repository into /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Checkouts/CocoaAsyncSocket: Could not create working directory (Error Domain=NSCocoaErrorDomain Code=513 "You donâ€™t have permission to save the file â€œCocoaAsyncSocketâ€ in the folder â€œCheckoutsâ€." UserInfo={NSFilePath=/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Checkouts/CocoaAsyncSocket, NSUnderlyingError=0x7f8e0d72aac0 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}})
[35m[XCUITest][39m Launching WebDriverAgent on the device
[35m[WebDriverAgent][39m Fetching dependencies
```

**Comment by BoazWarshawsky** [comment]
Thanks @KazuCocoa , you are a star :) the alert issue I had **solved** with **Appium version 1.15.0.**

But on the other had, I have an issue that is happening only when the application launches from appium test:
**On the first launch of the app (after install), the app loading like it was without network**
This is something that is not happening to me when I am launching the app for the first time "manually", like a real user.

Can you please take a look into the logs to see if there is something wrong:
https://assets-production.applicaster.com/qa/zapp_qa/manual/boaz/appium_white_screen.log

Thank You!

**Comment by KazuCocoa** [comment]
The log looked no issue.
Appium launches apps via XCTest API internally. So, the issue probably happened in your test app side. (For example, some SDKs failed to initialise by launching via XCTest API...)

As another workaround, you can start Appium with `autoLaunch: false` and call http://appium.io/docs/en/commands/device/app/activate-app/ to launch the app.
Not sure it works well, but you can try it out.

**Comment by BoazWarshawsky** [comment]
Thanks, even that its weird, opening it manually I can't see an issue.

**Comment by KazuCocoa** [comment]
Yes. I met similar issue long before. That was an ad SDK issue.
(I forgot the detail, but It perhaps resolved with changing initialise steps a bit in product code)

**Comment by BoazWarshawsky** [comment]
Do you might remember what was changed? more or less

**Comment by KazuCocoa** [comment]
No, unfortunately.

---

Close this issue once since this title issue has been resolved on Apium 1.15.0.

I suggested a workaround you possibly can do on Appium.
Feel free to create a new issue if the network issue might be Appium issue 🆗

**Comment by BoazWarshawsky** [comment]
@KazuCocoa What is the flow exacly?

`self.driver = webdriver.Remote(appium_server_url, self.desired_caps)`
`self.driver. activate_app('my.app.id')`
?

**Comment by KazuCocoa** [comment]
yes
