### ISSUE TITLE
Unable to run 2 sessions on the same IOS device - socket hang up

### ISSUE THREAD

**Issue by lubshilk** [appium/appium#13586]
## The problem

We try to run 2 sessions at the same time on IOS device (we have 2 applications running and need to switch from one to another)
We install the first application starting Appium server with port 4737 and IOS driver with wdaLocalPort 8101 and the second application starting Appium server with port 4738 and IOS driver with wdaLocalPort 8100. Both we run with newCommandTimeout=0 (as suggested https://github.com/appium/appium/issues/5341) to avoid the session shutdown.
When after installation we try to use the first application and find an element and catch screenshot, reported the exception "An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up" 

Note: we are able to run 2 Android sessions on the same Android device with no problems. So we expect the same is possible on IOS as well

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): didn't try it before
* Desktop OS/version used to run Appium: macOS Mojave
* Node.js version (unless using Appium.app|exe): 10.16.3
* Mobile platform/version under test: IOS 13.2.2
* Real device
* Xcode 11.2

## Link to Appium logs
https://gist.github.com/lubshilk/77de022314eaff64f43ba635f432e4ac

**Comment by mykola-mokhnach** [comment]
Unfortunately such scenario is not possible. You need to have two separate drivers for each app and quit one of them in order to start the other one in order to maintain the consistency.

Closed as not an issue.
