### ISSUE TITLE
Measuring UI Response Time on Real Devices

### ISSUE THREAD

**Issue by rameshgit96** [appium/appium#13596]
Hi, 

I asked this question on discuss.appium.io. However, I have not received any reply.

I am trying to capture the response time of a screen on a native app in Android and iOS (from the moment a user clicks on a button to when the screen is displayed).
In one example scenario, when a user clicks on a tab and navigates to a screen, it takes 2 seconds manually. However, by means of automating through Appium scripts, it shows 3 to 4 seconds. I have a start clock after clicking element and end clock after verifying element.
Is there a way to determine the time between requests or perhaps “how long” it takes to verify an element using the locator strategy? Because I am not receiving the accurate response time.
Also, how long does it take for an element to be verified by the Appium driver for each locator strategy, including XPath, ID, Accessibility ID, iOS-Predicate Strings, etc.?
This applies both to Android and iOS. I would like to capture the accurate response time when a user navigates between screens on a native app in both Android and iOS.
Thanks for your support.

**Comment by mykola-mokhnach** [comment]
In case you need precise measurement values then I wouldn't do any measurements on the client side (the HTTP communication itself and proxy stuff take a lot of time). Appium allows to retrieve the logs directly from the device even in runtime (see https://appiumpro.com/editions/55).

Both XCUITest and UIA2 have internal logging for each received command, so you can just parse there retried log chunks and extract the actual time different between the log records

**Comment by rameshgit96** [comment]
Thanks @mykola-mokhnach so much for your help.
In terms of retrieving the logs from the device during runtime, are these logs directly written to command line if I am triggering my scripts from command line? In other words, are these logs written to exactly where the regular appium logs are written?

I have written driver.executeScript("mobile:startLogsBroadcast); and driver.executeScript("mobile:stopLogsBroadcast"). However, I noticed that there are no logs being written specifically for this. Only after receiving these logs, I would then be able to parse them and extract the time.

**Comment by mykola-mokhnach** [comment]
You get the same device system logs as you would normally get with driver.getLogs endpoint. Although, I find this approach more effective, since it uses passive pooling rather than active and therefore have much less latency and in general less performance impact.

> Only after receiving these logs, I would then be able to parse them and extract the time.

Yes, you need to parse and interpret the actual log chunks like it was mentioned above.

**Comment by rameshgit96** [comment]
Thank you. Does "driver.executeScript" only for web app testing or also for native app testing on Android/iOS?

**Comment by rameshgit96** [comment]
I read somewhere online that automating a real device has a built in delay of one second between every action. Can you please confirm if this is true for android and ios native app testing?

Is there a fixed approximate delay between when Appium performs the execute command and when it is executed on the device?

**Comment by mykola-mokhnach** [comment]
> Can you please confirm if this is true for android and ios native app testing?

Nothing I know of

> Is there a fixed approximate delay between when Appium performs the execute command and when it is executed on the device?

Nothing I know of

**Comment by Jeby5jb** [comment]
@rameshgit96 Were u able to measure the UI response time with solution suggested.? I am also currently checking the same. If you find any solution please comment. It would be helpful
