### ISSUE TITLE
chromedriverExecutableDir and chromedriverChromeMappingFile do not work

### ISSUE THREAD

**Issue by yuruotong1** [appium/appium#13593]
## The problem

when i set chromedriverChromeMappingFile and chromedriverExecutableDir ，appium Partial support for chromedriver
## Environment

* Appium version (or git revision) that exhibits the issue: v1.14.0

**Comment by mykola-mokhnach** [comment]
Please provide a proper problem description with steps, actual and expected results and the full server log
