### ISSUE TITLE
Appium can't run IOS simulator, others can

### ISSUE THREAD

**Issue by zhoukai0203** [appium/appium#13599]
## The problem

Appium can't run IOS simulator, others can

## Environment

* Appium version (or git revision) that exhibits the issue:1.15.1
* Last Appium version that did not exhibit the issue (if applicable):none
* Desktop OS/version used to run Appium:10.14.6
* Node.js version (unless using Appium.app|exe):10.9.0
* Npm or Yarn package manager:6.2.0
* Mobile platform/version under test:iPhone 6s
* Real device or emulator/simulator:simulator
* Appium CLI or Appium.app|exe:both

## Details

Appium can't run IOS simulator, others can,For example:iOS real machine

## Link to Appium logs

[Appium] Welcome to Appium v1.15.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"capabilities":{"firstMatch":[{"platformName":"iOS","appium:platformVersion":12.2,"appium:deviceName":"iPhone 6s","appium:udid":"47628A17-8A97-4156-A44A-9D5DCB635B2F","appium:bundleId":"com.juzhou.cloud.im","appium:automationName":"XCUITest","appium:app":"/Users/kyle/work/xyre/project/mobile/python/test/cloud/app/XGiantBeta.app","appium:noReset":true}]},"desiredCapabilities":{"platformName":"iOS","platformVersion":12.2,"deviceName":"iPhone 6s","udid":"47628A17-8A97-4156-A44A-9D5DCB635B2F","bundleId":"com.juzhou.cloud.im","automationName":"XCUITest","app":"/Users/kyle/work/xyre/project/mobile/python/test/cloud/app/XGiantBeta.app","noReset":true}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","platformVersion":12.2,"deviceName":"iPhone 6s","udid":"47628A17-8A97-4156-A44A-9D5DCB635B2F","bundleId":"com.juzhou.cloud.im","automationName":"XCUITest","app":"/Users/kyle/work/xyre/project/mobile/python/test/cloud/app/XGiantBeta.app","noReset":true},null,{"firstMatch":[{"platformName":"iOS","appium:platformVersion":12.2,"appium:deviceName":"iPhone 6s","appium:udid":"47628A17-8A97-4156-A44A-9D5DCB635B2F","appium:bundleId":"com.juzhou.cloud.im","appium:automationName":"XCUITest","appium:app":"/Users/kyle/work/xyre/project/mobile/python/test/cloud/app/XGiantBeta.app","appium:noReset":true}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1573716126968 (15:22:06 GMT+0800 (GMT+08:00))
[Appium] Appium v1.15.1 creating new XCUITestDriver (v2.133.1) session
[debug] [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {
[debug] [BaseDriver]   "alwaysMatch": {
[debug] [BaseDriver]     "platformName": "iOS",
[debug] [BaseDriver]     "appium:platformVersion": 12.2,
[debug] [BaseDriver]     "appium:deviceName": "iPhone 6s",
[debug] [BaseDriver]     "appium:udid": "47628A17-8A97-4156-A44A-9D5DCB635B2F",
[debug] [BaseDriver]     "appium:bundleId": "com.juzhou.cloud.im",
[debug] [BaseDriver]     "appium:automationName": "XCUITest",
[debug] [BaseDriver]     "appium:app": "/Users/kyle/work/xyre/project/mobile/python/test/cloud/app/XGiantBeta.app",
[debug] [BaseDriver]     "appium:noReset": true
[debug] [BaseDriver]   },
[debug] [BaseDriver]   "firstMatch": [
[debug] [BaseDriver]     {}
[debug] [BaseDriver]   ]
[debug] [BaseDriver] }
[BaseDriver] Session created with session id: a007a55a-b07b-4b81-9dd2-8518b5aeaa44
[debug] [XCUITest] Current user: 'kyle'
[debug] [XCUITest] Available devices: 
[iOSSim] Constructing iOS simulator for Xcode version 10.2.1 with udid '47628A17-8A97-4156-A44A-9D5DCB635B2F'
[XCUITest] Determining device to run tests on: udid: '47628A17-8A97-4156-A44A-9D5DCB635B2F', real device: false
[XCUITest] Normalized platformVersion capability value '12.2' to '12.2'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1573716128243 (15:22:08 GMT+0800 (GMT+08:00))
[BaseDriver] Using local app '/Users/kyle/work/xyre/project/mobile/python/test/cloud/app/XGiantBeta.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1573716128246 (15:22:08 GMT+0800 (GMT+08:00))
[debug] [XCUITest] Checking whether app '/Users/kyle/work/xyre/project/mobile/python/test/cloud/app/XGiantBeta.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [BaseDriver] Event 'resetStarted' logged at 1573716128247 (15:22:08 GMT+0800 (GMT+08:00))
[debug] [XCUITest] Reset: noReset is on. Leaving simulator as is
[debug] [BaseDriver] Event 'resetComplete' logged at 1573716128247 (15:22:08 GMT+0800 (GMT+08:00))
[debug] [IOSSimulatorLog] Starting log capture for iOS Simulator with udid '47628A17-8A97-4156-A44A-9D5DCB635B2F', using 'xcrun simctl spawn 47628A17-8A97-4156-A44A-9D5DCB635B2F log stream --style compact'
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1573716128791 (15:22:08 GMT+0800 (GMT+08:00))
[XCUITest] Setting up simulator
[debug] [iOS] No reason to set locale
[debug] [iOS] No iOS / app preferences to set
[debug] [iOS] Setting did not need to be updated
[debug] [iOSSim] Setting preferences of 47628A17-8A97-4156-A44A-9D5DCB635B2F Simulator to {"ConnectHardwareKeyboard":false}
[debug] [iOSSim] Setting common Simulator preferences to {"RotateWindowWhenSignaledByGuest":true,"ConnectHardwareKeyboard":false}
[debug] [iOSSim] Updated 47628A17-8A97-4156-A44A-9D5DCB635B2F Simulator preferences at '/Users/kyle/Library/Preferences/com.apple.iphonesimulator.plist' with {"DevicePreferences":{"47628A17-8A97-4156-A44A-9D5DCB635B2F":{"ConnectHardwareKeyboard":false}},"RotateWindowWhenSignaledByGuest":true,"ConnectHardwareKeyboard":false}
[debug] [iOSSim] Got Simulator UI client PID: 71382
[iOSSim] Both Simulator with UDID 47628A17-8A97-4156-A44A-9D5DCB635B2F and the UI client are currently running
[debug] [IDB] Connecting idb service to '47628A17-8A97-4156-A44A-9D5DCB635B2F'
[debug] [IDB] Disconnecting idb service from '47628A17-8A97-4156-A44A-9D5DCB635B2F'
[Appium] Received SIGTERM - shutting down
[debug] [IDB] idb daemon started on port 9889
[debug] [IDB] Could not connect to 47628A17-8A97-4156-A44A-9D5DCB635B2F:None.
[debug] [IDB]             Make sure both host and port are correct and reachable
[debug] [IDB] 
[debug] [IDB] Disconnecting idb service from '47628A17-8A97-4156-A44A-9D5DCB635B2F'
Terminated: 15

## Code To Reproduce Issue [ Good To Have ]

neither can appium.app

**Comment by mykola-mokhnach** [comment]
It seems like idb service is not doing well. Make sure it is up to date or uninstall it if it still does not work

**Comment by zhoukai0203** [comment]
I tried many times, but it didn't work

brew tap facebook/fb
brew install idb-companion
pip install fb-idb

Android simulator and real machine are good, IOS real machine is also good.
My colleagues have the same problem
@mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
>  uninstall it if it still does not work

didn't work as well?

**Comment by zhoukai0203** [comment]
It doesn't work very well. Both appium and appium desktop versions have been tried. They have been reinstalled two or three times @mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
I was talking about complete uninstall, not reinstall

**Comment by zhoukai0203** [comment]
pip uninstall fb-idb 
brew uninstall idb-companion
it's no use

**Comment by mykola-mokhnach** [comment]
Make sure `which idb` and `which idb_companion ` show no output. If they do then probably brew does not uninstall everything properly

**Comment by zhoukai0203** [comment]
Uninstalling /usr/local/Cellar/idb-companion/1.0.9... (248 files, 24.3MB)
zhoukaideMacBook-Pro:/ kyle$ which idb
zhoukaideMacBook-Pro:/ kyle$ which idb_companion
zhoukaideMacBook-Pro:/ kyle$ pip install fb-idb
It's been a couple of days. I'm going to break down

**Comment by zhoukai0203** [comment]
the mac appium.app crash:
/Applications/Appium.app/Contents/MacOS/Appium(/usr/lib/libnetwork.dylib)
nw_path_close_fd Failed to close guarded necp fd 35 [9: Bad file descriptor]

This is all the logs,I hope you can help me.

**Comment by KazuCocoa** [comment]
> I was talking about complete uninstall, not reinstall

He meant you should not have called `$ pip install fb-idb` in https://github.com/appium/appium/issues/13599#issuecomment-553837863

**Comment by zhoukai0203** [comment]
Already called @KazuCocoa

**Comment by KazuCocoa** [comment]
Sorry, I confused.

Our suggestion was uninstalling `idb` since the error was probably idb did not work on your environment and it blocked following process.
In your comment https://github.com/appium/appium/issues/13599#issuecomment-553837863 , you installed idb again (it was **not** our suggestion). Then, the error happened.


Below error message section will not appear if you successfully uninstall `idb` (and not install again).

```
[debug] [IDB] Connecting idb service to '47628A17-8A97-4156-A44A-9D5DCB635B2F'
[debug] [IDB] Disconnecting idb service from '47628A17-8A97-4156-A44A-9D5DCB635B2F'
[Appium] Received SIGTERM - shutting down
[debug] [IDB] idb daemon started on port 9889
[debug] [IDB] Could not connect to 47628A17-8A97-4156-A44A-9D5DCB635B2F:None.
[debug] [IDB] Make sure both host and port are correct and reachable
[debug] [IDB]
[debug] [IDB] Discon
```

**Comment by zhoukai0203** [comment]
thank you so much @KazuCocoa
