### ISSUE TITLE
Pull file from iOS device with appium 1.15.1 timeouted

### ISSUE THREAD

**Issue by MildaGenius** [appium/appium#13597]
## The problem

After upgrade to Appium 1.15.1 pull file from iOS device timeouted. On Android devices still works.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): 1.14.1
* Desktop OS/version used to run Appium: Mac OS 10.14.6 (18G103)
* Node.js version (unless using Appium.app|exe): v10.15.1
* Npm or Yarn package manager: 6.4.1
* Mobile platform/version under test: iOS/iPad/12.4
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: both

## Details
Whe try to pull file from real device from python, timeout accurs and fill is not pulled. The file has 62 bytes.

` Message: An unknown server-side error occurred while processing the command. Original error: Couldn't pull the file 'Documents/testFile.txt' within the given timeout 30000ms`

## Link to Appium logs
[GIST](https://gist.github.com/MildaGenius/7d640c0fa1395819c07b01bdd4a1a3b2)

## Code To Reproduce Issue [ Good To Have ]
[GIST](https://gist.github.com/MildaGenius/972fa7d4746dd3408055310cca9b4b89)

**Comment by KazuCocoa** [comment]
@MildaGenius Could you get the log again with the latest `appium@beta`? (Please uninstall appium once to clean the dependencies)
`appium-xcuitest-driver@3.5.0` will print the original error which will help us.

**Comment by MildaGenius** [comment]
@KazuCocoa here is log from Appium 1.16.0-beta.1

[Gist](https://gist.github.com/MildaGenius/167ca7eda55f35763fe137412421b9b5)

**Comment by KazuCocoa** [comment]
@MildaGenius Thanks.


---

> The file has 62 bytes.

```
[HTTP] --> POST /wd/hub/session/55057b5b-7a17-4e71-a5e2-d510d5382680/appium/device/pull_file
[HTTP] {"path":"@com.bistudio.AppiumTest/Documents/testFile.txt","sessionId":"55057b5b-7a17-4e71-a5e2-d510d5382680"}
[debug] [W3C (55057b5b)] Calling AppiumDriver.pullFile() with args: ["@com.bistudio.AppiumTest/Documents/testFile.txt","55057b5b-7a17-4e71-a5e2-d510d5382680"]
[debug] [XCUITest] Executing command 'pullFile'
[debug] [W3C (55057b5b)] Encountered internal error running command: Error: Couldn't pull the file 'Documents/testFile.txt' within the given timeout 30000ms. Original error: operation timed out
[debug] [W3C (55057b5b)]     at pullFileFromRealDevice (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/file-movement.js:82:11)
[HTTP] <-- POST /wd/hub/session/55057b5b-7a17-4e71-a5e2-d510d5382680/appium/device/pull_file 500 31300 ms - 731
[HTTP] 
```

@umutuzgur Do you have any idea about the operation timeout?

**Comment by umutuzgur** [comment]
I would try it with the latest node version again

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by MildaGenius** [comment]
After update to Node v13.1.0 works pull file on iOS with Appium 1.15.1 and 1.16.0-beta.1

[iOS pullFile Appium 1.16.0-beta.1 with Node v13.1.0](https://gist.github.com/MildaGenius/8b1a33c5fc62ef73ffeff08232aeef6b)
[iOS pullFile Appium 1.15.1 with Node v13.1.0](https://gist.github.com/MildaGenius/386d7707e35d66dafe96549646a1d01e)

One problem after upgrade was appium link, which I fixed with.
`
ln -fs /usr/local/lib/node_modules/node/lib/node_modules/appium/build/lib/main.js /usr/local/bin/appium
chmod +x /usr/local/bin/appium
`

**Comment by MohithMedasani** [comment]
@MildaGenius any command to upgrade the node version?
