### ISSUE TITLE
Appium with Espresso Driver

### ISSUE THREAD

**Issue by Selvam-N** [appium/appium#13601]
Am new to use the espresso driver in Appium. 
I just added the Automation name as espresso and included all the other capability required to start the session. Am getting the following error when I run the code 
'package io.appium.espressoserver.test does not have a signature matching the target'

Am not sure what should be done to resolve it.
Am using Java 8, Appium version 1.15.1 and Android Studio 3.5.2

whether Appium@beta needs to be installed ? 
Can anyone please help me. I don't have any idea. since am newbie

**Comment by mykola-mokhnach** [comment]
Kindly use Appium forum (discuss.appium.io) to ask questions. This is the place for issues.

Also, search is always the first place to check: https://github.com/search?q=org%3Aappium+%22does+not+have+a+signature+matching+the+target%22&type=Issues
