### ISSUE TITLE
Appium fails on travis CI with ios app

### ISSUE THREAD

**Issue by mandelmonkey** [appium/appium#13604]
## The problem

I am trying to use Travis CI and appium to install and run basic tests on an ios app, however when starting the mocha tests appium seems to hang then spend ages building webdriveragent, webdriveragent then spills out loads of logs and then mocha or travis timesout

I confirmed that my setup works on my macos, just not my travis macos, any ideas? I have included code and set up below 

## Environment

* Appium version (or git revision) that exhibits the issue:
1.15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
travis VM (macos)
* Node.js version (unless using Appium.app|exe):
v12.13.0
* Npm or Yarn package manager:
npm v6.4.1
* Mobile platform/version under test:
ios
* Real device or emulator/simulator:
simulator
* Appium CLI or Appium.app|exe:
Appium CLI 

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/mandelmonkey/11fae2ce1a9f50b2c0a195c87aab05d4

## Code To Reproduce Issue [ Good To Have ]
run the repo here on travis
https://github.com/mandelmonkey/travisTest

**Comment by mykola-mokhnach** [comment]
I don't observe any Appium errors in the provided logs. We run internal tests on Travis and that works (albeit being pretty slow): https://github.com/appium/appium-xcuitest-driver/blob/master/.travis.yml

**Comment by mandelmonkey** [comment]
thanks
here is another gist
https://gist.github.com/mandelmonkey/fa60dbb2f6b860883d582b6b65a2bc3b#file-appium-ios-travis-L138

the tests often timeout, and the appium and mocha process create a lot of logs which often end up in travis terminating the job for creating too many logs

is this expected behaviour for an ios build on travis?

**Comment by mykola-mokhnach** [comment]
Yes, such behaviour is expected. First-time build of WebDriverAgent is usually a long operation, which could require more than 60 seconds (the default mocha timeout, also customisable) to complete, that is why it would be usually a good practice to precompile (aka warm-up driver creation) it in suite setup. Regarding logs amount - this can be always limited using capabilities and server settings.

**Comment by mandelmonkey** [comment]
ok thanks for clarifying that, I guess the travis VM is slow which is why it takes so long, will close

**Comment by mandelmonkey** [comment]
do you know how one might warm up the webdriveragent with mocha?

**Comment by mykola-mokhnach** [comment]
Simply start a new session and then quit it.

**Comment by imurchie** [comment]
You can also do something like we do in our Travis test suite
(https://github.com/appium/appium-xcuitest-driver/blob/master/.travis.yml#L194-L198) or Azure nightly build (https://github.com/appium/appium/blob/master/ci-jobs/templates/bundle-template.yml#L18-L22)

**Comment by mandelmonkey** [comment]
this uses appium-webdriveragent and not 'wd', is that recommened?

**Comment by imurchie** [comment]
@mandelmonkey Not sure what you mean. `wd` is a WebDriver client. `appium-webdriveragent` is the internal tool Appium uses to automation iOS, and is also the thing which takes a long time to initially download and build.

**Comment by mandelmonkey** [comment]
@imurchie sorry I misunderstood, I thought you meant adding pushed node_modiles/appium-webdriveragent is what I should do
` 
      pushd node_modules/appium-webdriveragent;
      carthage bootstrap --no-use-binaries;
      cp Cartfile.resolved Carthage;
      mkdir -p ./Resources/WebDriverAgent.bundle;
      popd;    `

**Comment by imurchie** [comment]
What I'm saying is the your test times out while downloading the dependencies that Appium needs in order to communicate with an iOS device/simulator (https://gist.github.com/mandelmonkey/11fae2ce1a9f50b2c0a195c87aab05d4#file-appium-travis-logs-L8997-L9033). I pointed out how we got around precisely the same timeout issue by going into the directory where the dependencies are updated, and doing the downloading/building before the tests begin (in the Travis config I linked to, we also get around the rate limiting you see in your logs).

**Comment by mandelmonkey** [comment]
got you thanks, ill play around with it
