### ISSUE TITLE
Appium Inspector doesn't display Entering camera mode message on Android emulator

### ISSUE THREAD

**Issue by srakhmanova** [appium/appium#13609]
## The problem
I'm trying to automate testing using Android emulator camera. For the first launch emulator shows alerts to allow access to camera and a popup with instructions. Appium Inspector can't catch this popup message, in fact it is impossible to close it using appium in test
<img width="1081" alt="Screenshot 2019-11-18 at 13 41 39" src="https://user-images.githubusercontent.com/26973860/69054079-e9bb9180-0a1b-11ea-9f65-1395810ce50b.png">
.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0-beta.1
* Desktop OS/version used to run Appium: Mac OS Mojave version 10.14.6
* Node.js version (unless using Appium.app|exe): v12.12.0
* Npm or Yarn package manager: npm 
* Mobile platform/version under test: Android Pixel 3 API 27
* Real device or emulator/simulator:Emulator
* Appium CLI or Appium.app|exe: Appium.app

**Comment by mykola-mokhnach** [comment]
Try to set the `enableMultiWindows` driver setting to `true`

**Comment by mykola-mokhnach** [comment]
[Here](http://appium.io/docs/en/advanced-concepts/settings/) you can find more information about settings API. The option above has been added to Appium quite recently (and that is why it is not listed in the documents yet) and should be available in appium@beta.

> There are not multiple windows, in the right part of screenshot is Android emulator and in the left part - is how it is shown in Appium Inspector.

Appium simply shows what is visible to the accessibility inspector. We are not in control of the content there. Although, by default, the server is set to only limit the output to the content of the currently active window (for Android OS things like toolbars and popups are descendants of separate system windows). So, there is a possibility the given control might be visible with the setting above set to `true`. In case the dialog is still not present in the page source then the only option I see is to create a problem report to Google.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
