### ISSUE TITLE
chromedriver_autodownload does not work

### ISSUE THREAD

**Issue by mcopjan** [appium/appium#13602]
## The problem

- Start appium --allow-insecure chromedriver_autodownload
- Create a new session with chromedriverChromeMappingFile and chromedriverExecutableDir capabilitites

Expected result:
Corresponding chromedriver should be downloaded into the chromedriverExecutableDir and chromedriverChromeMappingFile updated

Actual result: 
[debug] [Chromedriver] Attempting to use Chromedriver-Chrome mapping from '/Users/martinco/Testing/chromeDriversMapping.json'
[debug] [Chromedriver] Found 0 executables in '/Users/martinco/Testing/chromedrivers/'
[Chromedriver] Error: No Chromedrivers found in '/Users/martinco/Testing/chromedrivers/'

## Environment

* Appium version 1.15.1
* Mojave

## Link to Appium logs

[appiumLogs.txt](https://github.com/appium/appium/files/3850913/appiumLogs.txt)

**Comment by mykola-mokhnach** [comment]
Yes, this looks a bug. You can put any valid chromedriver binary into that folder for now in order to workaround it

**Comment by mykola-mokhnach** [comment]
The patch has been published to appium@beta

**Comment by Mrlilili** [comment]
have some error  No Chromedriver found that can automate Chrome '45.0.2454'.

**Comment by imurchie** [comment]
@Mrlilili This is an entirely different error. Please search the closed issues to see if previous answers solve your problem. If you feel they do not, please open a new issue with _all_ the information asked for in the template.
