### ISSUE TITLE
[main] ERROR net.thucydides.core.webdriver.WebDriverFacade - FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE class io.appium.java_client.AppiumDriver: Could not instantiate new WebDriver instance of type class io.appium.java_client.AppiumDriver (An unknown server-side error occurred while processing the command. Original error: The protocol 'sauce-storage:' used in 'sauce-storage:WordPress.zip' is not supported. Only http: and https: protocols are supported Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:01:39.354Z

### ISSUE THREAD

**Issue by kanojiyanviod** [appium/appium#13608]
Hi, I am trying to connect test object instance of saucelab where i am connecting testObject with testobject key, using below serenity property file :

webdriver.driver= appium
#appium.hub = http://localhost:4723/wd/hub
saucelabs.test.name=AppiumWordPressWithSauce
saucelabs.target.platform=Windows
saucelabs.testobjectApiKey=27E3B8CC6BDF4ABHH8ACA578124FCDA4C

#appium.hub = http://127.0.0.1:4723/wd/hub
appium.platformName = Android
appium.platformVersion = 5.1.1
appium.deviceName = Samsung_Galaxy_A5_2017_real
#appium.browserName = Chrome
appium.app=sauce-storage:WordPress.zip

appium.appPackage=com.ombiel.campusm.unsw

Running From IDE
#saucelabs.url=http://<sauce_username>:<sauce_access_key>@ondemand.saucelabs.com:80/wd/hub
#saucelabs.user.id=<sauce_username>
#saucelabs.access.key=<sauce_access_key>

getting error as

ERROR net.thucydides.core.webdriver.WebDriverFacade - FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE class io.appium.java_client.AppiumDriver: Could not instantiate new WebDriver
instance of type class io.appium.java_client.AppiumDriver (The browser under test or path to the app needs to be provided in the appium.app or appium.browserName property.
net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate new WebDriver instance of type class io.appium.java_client.AppiumDriver (The browser under test or path to
the app needs to be provided in the appium.app or appium.browserName property.

please help

4.0.0

<groupId>net.serenity-bdd.appium.integration</groupId>
<artifactId>serenity-appium</artifactId>
<version>1.0-SNAPSHOT</version>
<packaging>jar</packaging>

<name>Serenity Appium Integration Test Cases</name>

<properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <serenity.version>1.7.4</serenity.version>
    <serenity.cucumber.version>1.6.3</serenity.cucumber.version>
    <serenity.maven.version>1.7.4</serenity.maven.version>
</properties>

<repositories>
    <repository>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
        <id>central</id>
        <name>bintray</name>
        <url>http://jcenter.bintray.com</url>
    </repository>
</repositories>
<pluginRepositories>
    <pluginRepository>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
        <id>central</id>
        <name>bintray-plugins</name>
        <url>http://jcenter.bintray.com</url>
    </pluginRepository>
</pluginRepositories>

<dependencies>
    <dependency>
        <groupId>net.serenity-bdd</groupId>
        <artifactId>serenity-core</artifactId>
        <version>${serenity.version}</version>
    </dependency>
    <dependency>

        <groupId>net.serenity-bdd</groupId>
        <artifactId>serenity-junit</artifactId>
        <version>${serenity.version}</version>
    </dependency>
    <dependency>
        <groupId>net.serenity-bdd</groupId>
        <artifactId>serenity-cucumber</artifactId>
        <version>${serenity.cucumber.version}</version>
    </dependency>
    <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-simple</artifactId>
        <version>1.7.7</version>
    </dependency>
    <dependency>
        <groupId>junit</groupId>
        <artifactId>junit</artifactId>
        <version>4.12</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>org.assertj</groupId>
        <artifactId>assertj-core</artifactId>
        <version>1.7.0</version>
    </dependency>
</dependencies>

<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>2.20.1</version>
            <configuration>
                <skip>false</skip>
            </configuration>
        </plugin>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.2</version>
            <configuration>
                <source>1.8</source>
                <target>1.8</target>
            </configuration>
        </plugin>
        <plugin>
            <groupId>net.serenity-bdd.maven.plugins</groupId>
            <artifactId>serenity-maven-plugin</artifactId>
            <version>${serenity.maven.version}</version>
            <executions>
                <execution>
                    <id>serenity-reports</id>
                    <phase>post-integration-test</phase>
                    <goals>
                        <goal>aggregate</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>

**Comment by mykola-mokhnach** [comment]
Please report the problem to Sauce Labs customer support. It has nothing to do with Appium server
