### ISSUE TITLE
iOS 13: Appium 1.16.0-beta.1 gets timed out at Sending '_rpc_forwardSocketData:' 

### ISSUE THREAD

**Issue by patrjam** [appium/appium#13603]
Hi,

I have problem with Sending '_rpc_forwardSocketData, so I uninstalled 1.15.0 version and installed  v1.16.0-beta.1, but it did not fix the issue. (this was discussed in ticket [https://github.com/appium/appium/issues/13270](url).
 Running of tests is veeery slow because of these timeouts.

### The problem:

```
2019-11-14 12:26:35:813 [HTTP] --> POST /wd/hub/session/57ca9e5b-6e17-4114-8b65-ee432ff7d553/elements

2019-11-14 12:26:35:813 [HTTP] {"using":"css selector","value":".input--hp-search"}

2019-11-14 12:26:35:814 [W3C (57ca9e5b)] Calling AppiumDriver.findElements() with args: ["css selector",".input--hp-search","57ca9e5b-6e17-4114-8b65-ee432ff7d553"]

2019-11-14 12:26:35:814 [XCUITest] Executing command 'findElements'

2019-11-14 12:26:35:814 [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id

2019-11-14 12:26:35:815 [BaseDriver] Waiting up to 0 ms for condition

2019-11-14 12:26:35:815 Executing atom 'find_elements'

2019-11-14 12:26:35:815 Executing 'find_elements' atom in default context

2019-11-14 12:26:35:815 Sending javascript command: '(function(){return function(){var k=this;functi...'

2019-11-14 12:26:35:817 Sending '_rpc_forwardSocketData:' message to app 'PID:5399', page '1', target 'page-6' (id: 41)

2019-11-14 12:28:35:813 [HTTP] <-- POST /wd/hub/session/57ca9e5b-6e17-4114-8b65-ee432ff7d553/elements - - ms - -
```

### Environment:
Mobile platform/version under test: iOS 13.2
Real device or emulator/simulator: iPad 2
npm version 6.11.3 
CodeceptJS Appium 

### Code To Reproduce Issue

```
Feature('The Internet example test');

Scenario('Home page', (I) => {

    I.amOnPage('http://www.seznam.cz')
    I.fillField('.input--hp-search', 'dog')
    I.click('.button--with-input')
    I.seeElement('.ZooCardAnimal')
});
```

**Comment by jniosdeveloper** [comment]
How do you support appium running on the iPhone？ Is the webdriver agent used?

**Comment by patrjam** [comment]
Yes, webdriver is used. ProjectWebdriverAgent is used, successfully built and installed into devices.
Integration app is correctly running.

**Comment by jniosdeveloper** [comment]
Facebook does not maintain WebdriverAgent. I cloned his project and compiled it with Xcode 11.2, but an error was reported. The error prompt is:Could not build module 'RoutingHTTPServer'.I want to know why? I have set up the relevant configuration, including modifying the bundleid and setting the developer certificate, but when compiling (#import < routinghttpserver / routingconnection. H >), this file cannot be found

**Comment by jniosdeveloper** [comment]
What's the version number of the mobile phone where you installed webdrivertagent and Xcode？

**Comment by patrjam** [comment]
Tests will be running on Ipad 2 with iOS 13.2, it was also tested on iPhone 7 Plus (also iOS 13.2) with the same result.

> What's the version number of the mobile phone where you installed webdrivertagent and Xcode？

**Comment by jniosdeveloper** [comment]
Are you using this (https://github.com/facebook/webdriveragent.git) path to download the demo? Did you encounter any error after compiling?

**Comment by patrjam** [comment]
Yes, it is a part of appium, which was downloaded in a 1.16.0-beta.1 version

**Comment by jniosdeveloper** [comment]
Hello, I'd like to ask you, are you the download of appium1.16.0 beta, and then use the included webdriver agent project to test the real machine？ if so, can you give me the download address of appium1.16.0

**Comment by mykola-mokhnach** [comment]
Appium maintains its own fork of WebDriverAgent: https://github.com/appium/WebDriverAgent

The original one from Facebook is abandoned.

**Comment by jniosdeveloper** [comment]
Now I am directly cloning (https://github.com/facebookerchive/webdriveragent.git) the project of this link, but the compilation times (could not build module 'routinghttpserver') is wrong. Are you using the webdriveragent project of appium 1.16.0beta？

**Comment by jniosdeveloper** [comment]
Brother, thank you very much. The new project we downloaded can be compiled and passed at present. We are in the process of IOS automation test. If there are any related problems in the future, I hope you can consult or we can exchange and learn. Thanks again！！！

**Comment by patrjam** [comment]
Appium 1.16.0-beta.1 was installed with command `npm uninstall -g appium && npm install -g appium@beta`

Today we updated webdriverAgent to version from yesterday (2.3.1 - from https://github.com/appium/WebDriverAgent).

It did not fix the problem.

**Comment by imurchie** [comment]
I have published, in the latest Appium beta, the results of all of my experimentation. For my tests things are much better, hopefully for others as well.

- `appium-xcuitest-driver` should be at least v3.6.0
- `appium-ios-device` should be at least v1.2.1
- `appium-remote-debugger` should be at least v6.7.0

**Comment by patrjam** [comment]
> I have published, in the latest Appium beta, the results of all of my experimentation. For my tests things are much better, hopefully for others as well.
> 
> * `appium-xcuitest-driver` should be at least v3.6.0
> * `appium-ios-device` should be at least v1.2.1
> * `appium-remote-debugger` should be at least v6.7.0

-------------
We reinstalled npm, also appium, because we found many older versions of packages with dependencies, which did not match versions you mentioned.

Clear everything and install appium@beta solved our problem, and it works now.

**Comment by mykola-mokhnach** [comment]
Closed as fixed

**Comment by pacchan** [comment]
Hi all.

I tried various version of appium but have no luck.  Sometimes it stops here and there because of not receiving a response. Since this is closed I have create a ticket 
https://github.com/appium/appium/issues/13644
