### ISSUE TITLE
Not able to get element by name using appium, even tough name property exists

### ISSUE THREAD

**Issue by vishnuprakash9845** [appium/appium#13600]
## The problem

In the UWP application inspected an text element having name "No" using inspect.
Then using the below code
 **IList<WindowsElement> ele = _session.FindElementsByName("No");**
Getting the zero elements, so why i am not able to get the element, tough the name property for the text element exists

## Environment

* Appium version (or git revision) that exhibits the issue: 4.0
* Desktop OS/version used to run Appium: Windows 10
## Details

Attaching the screenshot inspected element
<img width="296" alt="WindowsElementsHireachy" src="https://user-images.githubusercontent.com/24207575/68854587-55db8400-0702-11ea-8540-4ff88fe0c685.png">

Can anyone help me on this issue.

**Comment by mykola-mokhnach** [comment]
I think this is a server issue. Consider reporting it to https://github.com/jonstoneman/WinAppDriver

**Comment by vishnuprakash9845** [comment]
> I think this is a server issue. Consider reporting it to https://github.com/jonstoneman/WinAppDriver

Reported to Microsoft/WinAppDriver
https://github.com/microsoft/WinAppDriver/issues/966#issue-522837809

**Comment by mykola-mokhnach** [comment]
Closing the issue here. Let it be tracked by MS tracker
