### ISSUE TITLE
Issue while send the text in alert textbox

### ISSUE THREAD

**Issue by shibupanda** [appium/appium#13616]
## The problem
Getting error while trying to send text to alert textBox.
"Encountered internal error running command: BadParametersError: Parameters were incorrect. We wanted {"required":["text"]} and you sent ["value"]"

Java-client: 7.0.0, 7.1.0, 7.2.0, 7.3.0

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Mobile platform/version under test: tested on iOS 10, 11, 12 ,13 
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs
https://gist.github.com/shibupanda/3fbf67c6efa24fc598ad189231082b37

**Comment by mykola-mokhnach** [comment]
The patch has been published to appium@beta
