### ISSUE TITLE
Android getText returning the hint text

### ISSUE THREAD

**Issue by sme81** [appium/appium#13618]
## The problem

Wanting to confirm that text fields are empty during a test at certain points.

The EditTexts have hint text on them, eg Username and Password. When a getText is done on these elements it is returning the hint text, not the expected blank string.

Appium doesn't have access to the 'hint' attribute

Is there a way to exclusively pull the text NOT the hint, when the field is blank

![image](https://user-images.githubusercontent.com/48491431/69161224-bb54b980-0ae2-11ea-9b51-264384c0253c.png)
Example above: 

- getText on the empty 'Username' field displaying the hint will return 'Username'

- getText on the selected 'Password' field displaying the hint now as a title will return 'Password'

## Environment

* Appium version : 1.15.1
* Desktop OS/version used to run Appium: mac and windows, both desktop and CLI
* Mobile platform/version under test: Android 7,8,9
* Real device or emulator/simulator: Emulator

## Details

![image](https://user-images.githubusercontent.com/48491431/69161636-5f3e6500-0ae3-11ea-935c-50abd498a4bf.png)

When the fields have actual text in them the getText() returns text as expected, ie "testUsername" and "testPassword"

## Code To Reproduce Issue

Some of the element code below

`<com.google.android.material.textfield.TextInputLayout
    android:id="@+id/passwordTextViewLabel"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_below="@id/usernameTextViewLabel"
    android:layout_margin="10dp"
    android:hint="Password">
    <EditText
        android:id="@+id/passwordTextView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:enabled="@{!safeUnbox(viewModel.actionLoading)}"
        android:imeOptions="actionGo|flagNoExtractUi"
        android:inputType="textPassword"
        android:singleLine="true"
        android:text="" />
</com.google.android.material.textfield.TextInputLayout>`

**Comment by mykola-mokhnach** [comment]
This is the value returned by UIA2 framework, we don't have a control over it: https://github.com/appium/appium-uiautomator2-server/blob/d3f2418324b47a4a78505ac9801433055398b7f8/app/src/main/java/io/appium/uiautomator2/core/AccessibilityNodeInfoHelpers.java#L70

You could try to use Espresso, where one has access to the original Views hierarchy in order to get more precise distinction between element attributes

**Comment by sme81** [comment]
Will look into this thanks.

**NOTE**: This has only began pulling the hint from a blank text field after out app was updated to use to androidX, and switched from compileVersion 26 to 29
