### ISSUE TITLE
 "Could not find 'adb.exe'" error even though I have set ANDROID_HOME in environment vairable

### ISSUE THREAD

**Issue by Shebeok** [appium/appium#13612]
## The problem
I am trying to launch Chrome browser using the below code and I am getting "Could not find 'adb.exe'" error even though I have set ANDROID_HOME in environment vairable and have added it in the path variable.
( ;%ANDROID_HOME%\platform-tools;%ANDROID_HOME%\tools;%ANDROID_HOME%\tools\bin).

```

DesiredCapabilities capabilities =  new DesiredCapabilities();
		capabilities.setJavascriptEnabled(true);
		capabilities.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
		capabilities.setCapability(CapabilityType.ACCEPT_INSECURE_CERTS, true);
		capabilities.setCapability(CapabilityType.ForSeleniumServer.ENSURING_CLEAN_SESSION, true);
		capabilities.setCapability("takesScreenshot", true);

ThreadLocal<AndroidDriver<WebElement>> androidDriver = new ThreadLocal<>();
			capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, MobilePlatform.ANDROID);
			// For Android Emulator
			capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Android Emulator");
			capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "4.4");
			capabilities.setCapability(CapabilityType.BROWSER_NAME, "Chrome");
			androidDriver.set(new AndroidDriver<WebElement>(capabilities));


```

## Environment

* Appium version:7.2.0
* Desktop OS/version used to run Appium: Windows 7
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Android Emulator
* Appium CLI or Appium.app|exe: Using appium as a maven dependency.

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

java.lang.RuntimeException: org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Could not find 'adb.exe' in PATH. Please set the ANDROID_HOME or ANDROID_SDK_ROOT environment variables to the corect Android SDK root directory path.

**Comment by mykola-mokhnach** [comment]
Make sure the adb executable is present in PATH visible to Appium process: https://github.com/appium/java-client/blob/master/docs/environment.md

**Comment by mykola-mokhnach** [comment]
closed as not an issue
