### ISSUE TITLE
appActivity clears Emergency alert history 

### ISSUE THREAD

**Issue by magden** [appium/appium#13615]
## The problem

I want to get to the Emergency alert history page, without using UI.
I found the way to get there by using:
 appPackage=com.android.cellbroadcastreceiver
and
appActivity= com.android.cellbroadcastreceiver.CellBroadcastSettings
But when I run it, it takes me to desired page but before deletes all the history.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.15.1 and earlier...
* Desktop OS/version used to run Appium: Windows 10
* Mobile platform/version under test: OnePlus, Android 9.0.9
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: both

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

[](https://gist.githubusercontent.com/magden/e48ae9ebf55dd94005933be5b41995aa/raw/bb96835234bef4fbc1bc1fa19b7b5f2b0ecf7f77/appium_logs
)

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.
![after](https://user-images.githubusercontent.com/10567777/69142638-e71a7400-0acf-11ea-8423-253e657d9bd6.png)
![appActivity](https://user-images.githubusercontent.com/10567777/69142639-e7b30a80-0acf-11ea-86c5-7c2854c55ebe.png)
![before](https://user-images.githubusercontent.com/10567777/69142644-eaadfb00-0acf-11ea-87cc-93841831b5dc.png)

**Comment by magden** [comment]
Link appium logs:
https://gist.githubusercontent.com/magden/e48ae9ebf55dd94005933be5b41995aa/raw/bb96835234bef4fbc1bc1fa19b7b5f2b0ecf7f77/appium_logs

**Comment by KazuCocoa** [comment]
How about `noReset: true`?
http://appium.io/docs/en/writing-running-appium/other/reset-strategies/

```
[debug] [35m[ADB][39m 'com.android.cellbroadcastreceiver' is installed
[debug] [35m[ADB][39m Running 'C:\Testspan\Smartphone_Control\android_sdk_tools\platform-tools\adb.exe -P 5037 -s 57bcba92 shell am force-stop com.android.cellbroadcastreceiver'
[debug] [35m[ADB][39m Running 'C:\Testspan\Smartphone_Control\android_sdk_tools\platform-tools\adb.exe -P 5037 -s 57bcba92 shell pm clear com.android.cellbroadcastreceiver'
[debug] [35m[AndroidDriver][39m Performed fast reset on the installed 'com.android.cellbroadcastreceiver' application (stop and clear)
[debug] [35m[UiAutomator2][39m Performing shallow cleanup of automation leftovers
```

**Comment by magden** [comment]
Thank you!
