### ISSUE TITLE
Can't locate xpath element shorter xpath?

### ISSUE THREAD

**Issue by vladbelo** [appium/appium#13613]
## The problem

My resourcee id and there is no text is dynamic and always changes. Here is the element. xpath= /hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View/android.view.View[1]/android.view.View/android.view.View/android.view.View/android.view.View[3]/android.view.View/android.view.View/android.view.View/android.view.View[2]/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[3]/android.view.View/android.view.View/android.view.View/android.view.View[1]/android.view.View.

I tried: 
 @AndroidFindBy(uiAutomator = "new UiSelector().className(\"android.view.View\")
@AndroidFindBy(xpath = "//android.view.ViewView/android.widget.FrameLayout")
Does not work?

**Comment by mykola-mokhnach** [comment]
Please use Appium forum for questions
