### ISSUE TITLE
building WebDriverAgent is asking for a .xctrunner bundle ID

### ISSUE THREAD

**Issue by owlsnakes** [appium/appium#13610]
Hi so I've been using the same provisioning profile with Appium 1.14 and 1.15, and I'm getting this error when following [full manual configuration](https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md#full-manual-configuration)
```
Provisioning profile "match Development com.foobar.appium.WebDriverAgentRunner"
has app ID
"com.foobar.appium.WebDriverAgentRunner",
which does not match the bundle ID 
"com.foobar.appium.WebDriverAgentRunner.xctrunner".
```

## Environment

* Appium version (or git revision) that exhibits the issue: v1.16.0-beta.1
* Last Appium version that did not exhibit the issue (if applicable): v.1.15
* Desktop OS/version used to run Appium: macOS Mojave 10.14.6
* Node.js version (unless using Appium.app|exe): v12.1.0
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: iOS 12
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: CLI

## Details

So I used to be able to build the web driver agent without needing to provide a provisioning profile with `"com.foobar.appium.WebDriverAgentRunner.xctrunner"` just `"com.foobar.appium.WebDriverAgentRunner"` was sufficient.

I don't know if this is a change with xcode 11.2.1, or with latest appium beta.

**Comment by owlsnakes** [comment]
ok so this happens in 1.15 as well, I think its actually related to Xcode 11.2, in which case, the documentation probably just needs to be updated.

**Comment by owlsnakes** [comment]
possibly related: https://github.com/appium/appium/issues/13086

**Comment by owlsnakes** [comment]
For a real device, is it now expected to have `com.foobar.appium.WebDriverAgentRunner.xctrunner` and not `com.foobar.appium.WebDriverAgentRunner` ?

**Comment by KazuCocoa** [comment]
hm, thanks.

On my env, I could sign with personal/enterprise profile as `Product Bundle Identifier = xxxx.WebDriverAgentRunner` (no need `. xctrunner`) as _Test run_ on Xcode 11.2.1.
Need to understand Xcode internal more, but potentially we could assume in some profile requires `.xctrunner` suffix.

**Comment by owlsnakes** [comment]
@KazuCocoa is the change in bundle id due to something apple changed, or is this a change caused by appium? Thanks

**Comment by KazuCocoa** [comment]
Apple side. They change the rule from Xcode 11.

**Comment by Ibnfarooqvlm** [comment]
Yeah, I too faced this issue while using the Provisioning Profile. So, I changed to 'Automatically Manage Signing'. Now its working fine. But, I would like to know is there any workaround to use Provisioning Profile in Xcode 11.2.1?

**Comment by KazuCocoa** [comment]
it's my guess, but potentially if a provisioning profile allows only one full package id, `.xctest` name will fail to sign while using `.*` can work well...

**Comment by Niv-K** [comment]
I am getting error Communication with Apple failed: Your maximum App ID limit has been reached. You may create up to 10 App IDs every 7 days. along with  I never could build the project. to begin with.
Showing Recent Messages
No profiles for 'com.facebook.IntegrationApp' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.facebook.IntegrationApp'.
I also tried with 'com.nk.IntegrationApp' changed the bundle id to unique one. 
and then left the onld one tried to build it. Nothing worked for me.
No profiles for 'com.facebook.IntegrationApp' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.facebook.IntegrationApp'.

**Comment by ashokchhetri7** [comment]
> I am getting error Communication with Apple failed: Your maximum App ID limit has been reached. You may create up to 10 App IDs every 7 days. along with I never could build the project. to begin with. I don't have apple's paid developer account, and neither am i planning to buy one. Showing Recent Messages No profiles for 'com.facebook.IntegrationApp' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.facebook.IntegrationApp'. I also tried with 'com.nk.IntegrationApp' changed the bundle id to unique one. and then left the onld one tried to build it. Nothing worked for me. No profiles for 'com.facebook.IntegrationApp' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.facebook.IntegrationApp'.

Try more unique ids, it will work, add numbers at random.
If your id limit is reached, you can use another Apple ID to make new ones, or wait for a week to do again.

**Comment by ashokchhetri7** [comment]
> Hi so I've been using the same provisioning profile with Appium 1.14 and 1.15, and I'm getting this error when following [full manual configuration](https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md#full-manual-configuration)
> 
> ```
> Provisioning profile "match Development com.foobar.appium.WebDriverAgentRunner"
> has app ID
> "com.foobar.appium.WebDriverAgentRunner",
> which does not match the bundle ID 
> "com.foobar.appium.WebDriverAgentRunner.xctrunner".
> ```
> 
> ## Environment
> * Appium version (or git revision) that exhibits the issue: v1.16.0-beta.1
> * Last Appium version that did not exhibit the issue (if applicable): v.1.15
> * Desktop OS/version used to run Appium: macOS Mojave 10.14.6
> * Node.js version (unless using Appium.app|exe): v12.1.0
> * Npm or Yarn package manager: 6.9.0
> * Mobile platform/version under test: iOS 12
> * Real device or emulator/simulator: real device
> * Appium CLI or Appium.app|exe: CLI
> 
> ## Details
> So I used to be able to build the web driver agent without needing to provide a provisioning profile with `"com.foobar.appium.WebDriverAgentRunner.xctrunner"` just `"com.foobar.appium.WebDriverAgentRunner"` was sufficient.
> 
> I don't know if this is a change with xcode 11.2.1, or with latest appium beta.

I faced the same issue with Xcode 16. Any work around? Do I need to make the provision profile with .xctrunner bundle?

**Comment by saikrishna321** [comment]
@ashokchhetri7 Yes, if your using a personal account.

**Comment by radyhaggag** [comment]
> @ashokchhetri7 Yes, if your using a personal account.

Do you mean should add the suffix xctrunner to the bundle id?

i have the same issue, i need to manage it with ci/cd.

But the test documentation didn't mention this.
