### ISSUE TITLE
Open app, APP crash

### ISSUE THREAD

**Issue by zhoukai0203** [appium/appium#13611]
## The problem

app can be opened by itself. Use appium to open app.App crashes

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): 1.15.1
* Desktop OS/version used to run Appium: 10.15.1
* Node.js version (unless using Appium.app|exe): 10.9.0
* Npm or Yarn package manager:6.2.0
* Mobile platform/version under test: 13.2.2
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: all

## Details

This problem always exists. If you set autolaunch = false to manually open the app,you can view the elements
## Link to Appium logs

Got an unexpected response with status 400: {"value":{"error":"invalid element state","message":"The application under test with bundle id 'com.juzhou.cloud.im' is not running, possibly crashed","traceback":"(\n\t0   CoreFoundation                      0x00007fff23c4f02e __exceptionPreprocess + 350\n\t1   libobjc.A.dylib                     0x00007fff50b97b20 objc_exception_throw + 48\n\t2   CoreFoundation                      0x00007fff23c4ebf9 -[NSException raise] + 9\n\t3   WebDriverAgentLib                   0x00000001056b1b58 -[FBSession activeApplication] + 728\n\t4   WebDriverAgentLib                   0x00000001056bd7b7 +[FBSessionCommands currentCapabilities] + 87\n\t5   WebDriverAgentLib                   0x00000001056bd689 +[FBSessionCommands sessionInformation] + 233\n\t6   WebDriverAgentLib                   0x00000001056bacae +[FBSessionCommands handleCreateSession:] + 2958\n\t7   WebDriverAgentLib                   0x0000000105690e06 -[FBRoute_TargetAction mountRequest:intoResponse:] + 182\n\t8   WebDriverAgentLib                   0x...
[W3C] Matched W3C error code 'invalid element state' to InvalidElementStateError
[XCUITest] Failed to create WDA session (The application under test with bundle id 'com.juzhou.cloud.im' is not running, possibly crashed). Retrying...

**Comment by mykola-mokhnach** [comment]
Consider investigating the application logs. The server log simply confirms the fact the app crashed.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
