### ISSUE TITLE
Cannot recognize webview context on iOS 13

### ISSUE THREAD

**Issue by trinhpham** [appium/appium#13622]
## The problem

I saw that @imurchie published his code into latest beta version in #13285 , but I'm still stuck at switching into the webview context.
I managed to see the webview on Safari developer menu
![image](https://user-images.githubusercontent.com/9128061/69224554-59ae5100-0baf-11ea-83c0-0dd6148dc764.png)

## Environment

* appium@beta
```bash
% npm list -g appium-remote-debugger
/usr/local/lib
`-- appium@1.16.0-beta.1
  +-- appium-ios-driver@4.4.0
  | `-- appium-remote-debugger@4.5.0 
  +-- appium-xcuitest-driver@3.6.1
  | `-- appium-remote-debugger@6.7.0 
  `-- appium-youiengine-driver@1.2.1
    `-- appium-xcuitest-driver@2.133.1
      `-- appium-remote-debugger@5.7.0 

% npm --versions
{
  npm: '6.13.0',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.8.0',
  icu: '64.2',
  llhttp: '1.1.4',
  modules: '72',
  napi: '5',
  nghttp2: '1.39.2',
  node: '12.12.0',
  openssl: '1.1.1d',
  tz: '2019a',
  unicode: '12.1',
  uv: '1.32.0',
  v8: '7.7.299.13-node.12',
  zlib: '1.2.11'
}
```

* Mac 10.15.1 & Xcode Version 11.2.1 (11B500)
* iOS 13.2.3 (iPhone 6s)

## Link to Appium logs
See this [gist log](https://gist.github.com/trinhpham/ea4ee9ee37155443ca0676d408ed6993)

## Code To Reproduce Issue
Just call to get the available contexts (see more in log)
```bash
GET /wd/hub/session/54f250eb-5274-4a3a-92f9-0a6b1e65d5e5/contexts
```

**Comment by mykola-mokhnach** [comment]
What is the web view type you are trying to inspect?

**Comment by mykola-mokhnach** [comment]
I can also observe that
>  isAutomationEnabled: false

**Comment by trinhpham** [comment]
> What is the web view type you are trying to inspect?

Honestly, I don't know, since the application source code is not available at my end. Any documents or suggestion for me to figure it out?

> I can also observe that
>> isAutomationEnabled: false

I don't know this too, and I cannot find any document about this. Could you please share, @mykola-mokhnach ?

**Comment by mykola-mokhnach** [comment]
Our documentation is available at http://appium.io/docs/en/writing-running-appium/web/hybrid/

**Comment by trinhpham** [comment]
Look like on new iOS version, we cannot get enough information of the webview, such as: name, bundleId.
I've ran successful with a device that still under iOS 11.4, the log can be found in [this gist](https://gist.github.com/trinhpham/ad8956a1b49cbc0ef4da0f25b8f3aa71)

Comparing these two logs, I found a different. Hope this would be helpful:

iOS 13.2.3                                                                                        | iOS 11.4       
-------------------------------------------------------------- | ----------
Current applications available: | Current applications available:
Application: 'PID:649' |     Application: 'PID:2527'
id: "PID:649" | id: "PID:2527"
isProxy: false |   isProxy: false
name: "rhorunner" | name: "MyAppName"
bundleId: "*" | bundleId: "com.hlvtrinh.testApp"
hostId: undefined | hostId: undefined
isActive: 2 | isActive: 2
isAutomationEnabled: false | isAutomationEnabled: false
pageArray: | pageArray:
\- id: 1 | - id: 1
title: "" | title: ""
url: "http://127.0.0.1:65533/app/AgentReg/login" | url: "http://127.0.0.1:53056/app/AgentReg/login"
isKey: false | isKey: false

**Comment by trinhpham** [comment]
@mykola-mokhnach as release notes of 1.15.0, I assume that I don't need the IWDP (like your given document) anymore.
And I did read again this document, there's no information on my questions:
- What does `isAutomationEnabled` stand for? How to set it to true? Seems that on older iOS version, I don't need it.
- The document tells me about three types of webview, but doesn't show me the way to identify which type is displayed on my App. Since my app can be tested on older version of iOS, I can assume that it is either WkWebView or UIWebView. Am I correct?

**Comment by mykola-mokhnach** [comment]
yes, IWDP is not needed since 1.15 - this part of the doc needs to be updated

UIWebView has been deprecated by Apple, so one might expect it to not work as expected in the recent iOS releases. It is recommended to use WkWebView whenever possible.

**Comment by imurchie** [comment]
`isAutomationEnabled` is reported by Safari, there is nothing that you can do about it.

Is the line `bundleId: "*"` what is being reported? Or is the `"*"` part in place of something removed by you? Is it is what Safari s reporting, then that is the problem. I have never seen this, and Appium chooses the webview based on the bundle identifier, so this will, clearly, not match.

**Comment by trinhpham** [comment]
> `isAutomationEnabled` is reported by Safari, there is nothing that you can do about it.
> 
> Is the line `bundleId: "*"` what is being reported? Or is the `"*"` part in place of something removed by you? Is it is what Safari s reporting, then that is the problem. I have never seen this, and Appium chooses the webview based on the bundle identifier, so this will, clearly, not match.

I can assure that I didn't remove that bundleId

**Comment by imurchie** [comment]
@trinhpham Can you try re-installing the beta? 
```
$ npm ls -g appium-remote-debugger
/Users/isaacmurchie/.nvm/versions/node/v10.16.3/lib
└─┬ appium@1.16.0-beta.1
  ├─┬ appium-ios-driver@4.4.0
  │ └── appium-remote-debugger@4.5.0
  └─┬ appium-xcuitest-driver@3.7.0
    └── appium-remote-debugger@7.0.0
```

**Comment by trinhpham** [comment]
Thank @mykola-mokhnach , latest beta can recognize my webview.
You can see the log [here](https://gist.github.com/trinhpham/3c9ccbb72acfeb37d145b028f9122377)

```bash
% npm list -g appium-remote-debugger
/usr/local/lib
`-- appium@1.16.0-beta.2
  +-- appium-flutter-driver@0.0.20
  | `-- appium-xcuitest-driver@2.133.1
  |   `-- appium-remote-debugger@5.7.0 
  +-- appium-ios-driver@4.4.0
  | `-- appium-remote-debugger@4.5.0 
  `-- appium-xcuitest-driver@3.7.0
    `-- appium-remote-debugger@7.0.0 
```
