### ISSUE TITLE
Element does not exist in cache

### ISSUE THREAD

**Issue by apulido15** [appium/appium#13625]
Hi, i am executing a test in iOS Safari with appium and it show me this error:

Capabilities {autoGrantPermissions: true, automationName: XCuiTest, browserName: safari, databaseEnabled: false, deviceName: iPhone 7, dontStopAppOnReset: true, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: false, platform: MAC, platformName: ios, platformVersion: 12.2, takesScreenshot: true, udid: ..., webStorageEnabled: false}
Session ID: c98d2fd2-8d05-4a81-b75f-6d9d73609bd7
*** Element info: {Using=xpath, value=//*[contains(text(),'El campo es de obligatorio diligenciamiento.')]}
An unknown server-side error occurred while processing the command. Original error: Error: Remote debugger error with code 'undefined': StaleElementReferenceError: Element does not exist in cache
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: '', ip: '', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_202'
Driver info: io.appium.java_client.AppiumDriver

someone knows why?

thaks

**Comment by mykola-mokhnach** [comment]
StaleElementReferenceError is a normal selenium exception which appears when one tries to use a cached element instance when this element does not exist in DOM anymore. A solution might be to locate the element again in the client code.

Please fill out the issue report according to the requested form

**Comment by climbwithme** [comment]
@mykola-mokhnach I see the same behaviour. It is happening for a JS loaded Web Elements like "Draggable" Menu items. 

Tested in iOS 13.x iPads
Appium Version: 1.15.1 and latest beta 1.16.0-beta.1
Fails only in Safari Browser. Works in Android Chrome Tablets.

Attached the sample DOM of a hyperlink that are giving Stale Element Exceptions even after the page is completely loaded, 

> StaleElementReferenceError is a normal selenium exception which appears when one tries to use a cached element instance when this element does not exist in DOM anymore. A solution might be to locate the element again in the client code.
> 
> Please fill out the issue report according to the requested form

<img width="1382" alt="Screenshot 2019-11-25 at 5 46 33 PM" src="https://user-images.githubusercontent.com/45451867/69540132-f2780e80-0fab-11ea-9387-f48fca41d3ca.png">

**Comment by mykola-mokhnach** [comment]
@climbwithme Are you able to provide the url and an example client code to reproduce the problem?

**Comment by apulido15** [comment]
@mykola-mokhnach 

hi, i have the next client code where the error is throws

![image](https://user-images.githubusercontent.com/8889535/69557653-f9cff580-0f74-11ea-86fc-4508029cccfb.png)

**Comment by mykola-mokhnach** [comment]
@apulido15 Unfortunately the info above is not enough to be able to reproduce or investigate the problem

**Comment by climbwithme** [comment]
> @climbwithme Are you able to provide the url and an example client code to reproduce the problem?

@mykola-mokhnach Unfortunately I wouldn't be able to share the access for the site. But, will page source help?

**Comment by mykola-mokhnach** [comment]
@climbwithme No, not much. There should be a stable way to reproduce the problem in local env in order to confirm this is really a bug, which is possible to fix

**Comment by apulido15** [comment]
> @apulido15 Unfortunately the info above is not enough to be able to reproduce or investigate the problem

what info or code do you need?

**Comment by mykola-mokhnach** [comment]
>> what info or code do you need?

> the url and an example of the client code to reproduce the problem

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing more to do on this issue without the possibility to investigate and reproduce it locally.
