### ISSUE TITLE
Appium beta version 1.16.1 unable to recognize drawer menu elements for CIBC app for  iOS 13 and above

### ISSUE THREAD

**Issue by Ruksharpatel** [appium/appium#13624]
Appium inspector is unable to recognize individual elements available under the drawer menu of the CIBC application available on app store.

The Appium inspector which i tried was for the desktop version of 1.15.1, however the server version which i was using was 1.16.1@beta

Appium server version: 1.16.1@beta
Xcode: 11.2.1
MACOS: Mojave
App: CIBC app from app store

**Comment by mykola-mokhnach** [comment]
Are the elements visible in Xcode Accessibility inspector?

**Comment by Ruksharpatel** [comment]
No, it does not work with Xcode accessibility inspector either.

**Comment by mykola-mokhnach** [comment]
I wouldn't expect a miracle from Appium then, because it takes the data from the Accessibility inspector. Consider changing the application under test to make it more accessible.

**Comment by Ruksharpatel** [comment]
Hi mokhanch, i think i made a mistake earlier where i did not gave permissions to use Automator under permissions, however after doing that, it seems to identify those elements using Xcode Accessibility inspector.

**Comment by mykola-mokhnach** [comment]
What you could also try is to check which page source is returned by vanilla XCTest. Although, I still don't think there is anything we can do in Appium to change this behaviour.

**Comment by Ruksharpatel** [comment]
can u please elaborate more on how can i do that?

**Comment by mykola-mokhnach** [comment]
https://developer.apple.com/documentation/xctest?language=objc

There are plenty tutorials in the Internet on how to setup application testing with XCTest

**Comment by Ruksharpatel** [comment]
I am not sure how it will help me though, because it looks like its a completely different thing that Appium...

**Comment by Ruksharpatel** [comment]
Also, one more thing i would like to mention here is, that we have also tried with devices that is not iOS 13 and it seems to be good. Therefore, this seems to be a compatibility issue with IOS 13 and Appium.

**Comment by mykola-mokhnach** [comment]
Appium is just a proxy. All the hard lifting (e.g. page source generation) is done by XCTest. So, if you say it worked in iOS 12 and stopped working in iOS 13 then, most likely, only Apple is capable of fixing the problem.

**Comment by mykola-mokhnach** [comment]
Unfortunately, there's nothing more here we could do on Appium side.
Closed as third party issue.
