### ISSUE TITLE
Starting an app within just intentAction and URL

### ISSUE THREAD

**Issue by vikki** [appium/appium#13628]
Hi there,
I originally posted this on [stackoverflow](https://stackoverflow.com/questions/58980877/appium-starting-an-android-app-using-an-intent) and the [appium gitter](https://gitter.im/appium/appium?at=5dcbee0f4adf071a8420724b) but no answer so I wanted to check if I'm going about this wrong or if not, then you might take a PR to support it? :)

## The problem
I'm trying to start an android app with appium using just the intentAction and URL as optionalIntentArguments, and I couldn't get it to work out of the box with appium, though optionalIntentAction is supported. It looks like this is because the appPackage and appActivity are mandatory but seem to override the intent when passed to `adb`. This is to test against an expo app in local dev mode running in the Expo client app; I am basically copying what the expo-cli does, but in appium/webdriver tests.

I can launch expo cli dev app directly,  via adb (e.g.` adb shell am start -a "android.intent.action.VIEW" -d "exp://127.0.0.1:19000"` but I have to leave out the appPackage and appActivity, which are (I think!) mandatory with appium desktop app at least. I actually hacked in changing appium's validation to not require an appPackage and appActivity when the intent is provided, and then leave that out of the subsequent adb command (in `appium-adb`), which works, but was wondering if there was an intended/official way to do it? I'm happy to PR what I have if not, but figured someone else might be trying to do the same thing.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: OSX Catalina (10.15.1)
* Node.js version (unless using Appium.app|exe): v12.12.0
* Npm or Yarn package manager: npm 6.11.3
* Mobile platform/version under test: Nexus 5x Emulator - Android 10/API 29 
* Real device or emulator/simulator: n/a/
* Appium CLI or Appium.app|exe: appium CLI but I've also been using Appium desktop with similar results

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Code To Reproduce Issue [ Good To Have ]

Any test or Appium Desktop connection with desired capabilities like : 
{
  "platformName": "Android",
  "platformVersion": "10",
  "deviceName": "Nexus_5X_API_29_x86",
  "automationName": "Appium",
  "appActivity": ".experience.HomeActivity",
  "appPackage": "host.exp.exponent",
  "intentAction": "android.intent.action.VIEW",
  "optionalIntentArguments": "-d exp://<YOUR_IP>:<EXPO_SERVER_PORT>"
}

**Comment by mykola-mokhnach** [comment]
Recently UIA2 has received a possibility to be started without providing the application package and/or activity name: https://github.com/appium/appium-uiautomator2-driver/pull/337

I would start the driver in such mode and then use either `mobile: shell` call above or `mobile: deepLink` (see https://appiumpro.com/editions/84 and https://github.com/appium/appium-adb/blob/3a171c6b5866860819b86c2cadbf0f2c57b56518/lib/tools/apk-utils.js#L57)

**Comment by vikki** [comment]
Thanks so much for the alternative way of doing it, I'm trying that out now, and it seems to be working for me.

The only issue with this is that I was hoping to run the same tests against the full build of our app *and* the expo dev build, which means that we have different set up paths for each (e.g. the full build app can just be started via desired capabilities, but the dev build needs the extra intent/mobile-shell logic for mobile shell, and then also the iOS version of that). I managed to get the app to open from an intent with just the dev capabilities, basically by modifying the validation in appium-adb, which would mean I don't need to special case that codepath. Would you consider a PR along those lines?

**Comment by mykola-mokhnach** [comment]
We would be happy to review a PR from you. You also got a nice possibility to test it locally.

**Comment by mykola-mokhnach** [comment]
Closed as fixed
