### ISSUE TITLE
【switch to webview】Failed to get PID for the following process

### ISSUE THREAD

**Issue by lynnchma** [appium/appium#13621]
# The problem
switch to webview Failed ，but chrome inspect OK

[W3C (d5d964db)] Encountered internal error running command: Error: An unknown server-side error occurred while processing the command. Original error: unknown error: Failed to get PID for the following process: com.whty.xtjk
[W3C (d5d964db)]   (process name must be specified if not equal to package name)
[W3C (d5d964db)]   (Driver info: chromedriver=74.0.3729.6 

# ENV

hybrid APP （ionic）
android 9
android system webview (74.0.3729.136)
appium-desktop：1.15.1
Appium-Python-Client： 0.47

# Des
how can I fixed it？？？
 
# Details
[fail.txt](https://github.com/appium/appium/files/3867834/fail.txt)

**Comment by mykola-mokhnach** [comment]
Please use appium@beta

**Comment by mykola-mokhnach** [comment]
Also, make sure the web view itself is debuggable and you can inspect it via Chrome remote debugger

**Comment by mykola-mokhnach** [comment]
https://stackoverflow.com/questions/52429593/appium-getting-error-failed-to-start-chromedriver-session-original-error-unk could also be helpful

**Comment by mykola-mokhnach** [comment]
Possible duplicate of https://github.com/appium/appium/issues/13093

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by lynnchma** [comment]
useless reply

**Comment by imurchie** [comment]
You can get more information by specifying the `showChromedriverLog` capability (set to `true`), which will turn on Chromedriver verbose logging, to see what it is trying to do and what it is seeing.

**Comment by wanghengkun** [comment]
> Also, make sure the web view itself is debuggable

How to verify debugability？
