### ISSUE TITLE
Element details are not stored when the element goes out of scope

### ISSUE THREAD

**Issue by karthikmsctcs** [appium/appium#13639]
## The problem
I have a task in automating the window(B) which will be opened from base application (A). I have the saved the the A-Window object in a variable var1, i do few operations and close the window B.
Again i re open the Window and do operation with var1, it shows error.

## Environment
Appium 4.0, WinAppDriver 1.1, Windows environment.

## Code To Reproduce Issue [ Good To Have ]
var ele = windriver.FindElementByName("Window");
            ///Do few operations on the window opened
            var closebut=ele.FindElementByName("Close");
            closebut.Click();
            //Again Open the window by clicking button
            closebut.Click(); ///Shows error ':"An element command could not be completed because the element is not pointer- or keyboard interactable."'

**Comment by mykola-mokhnach** [comment]
Please report the problem to https://github.com/microsoft/WinAppDriver/issues

Unfortunately there is nothing we can do there from Appium side
