### ISSUE TITLE
Appium default temporary folder for Mac OS Catalina doesn't work

### ISSUE THREAD

**Issue by Vicropht** [appium/appium#13633]
## The problem

With the new MacOS, Catalina has a surprise change: it won't allow changes to the root directory

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.16.0-beta.1,
* Desktop OS/version used to run Appium: Mac OS Catalina 10.15.1

## Details

Unfortunately, this is not spelled out explicitly in Apple's Catalina release notes, other than a brief mention in Catalina features:

> macOS Catalina runs in a dedicated, read-only system volume

This affectes Appium in a way that it writes its files (at least in my case) to /data/local/tmp/appium_cache/, since it cannot access this directory it timesout the app installation because there is no temporary app to install.

My workaround was to set the tmp folder in Appium CLI with the argument --tmp somewhere it can read and write files, like Home.

**Comment by mykola-mokhnach** [comment]
`/data/local/tmp/appium_cache/` is the directory name on the remote device. What it has to do with the host operating system?

**Comment by Vicropht** [comment]
I see, that explains why I wasn't finding it in my Mac, well, never mind this then
