### ISSUE TITLE
How to connect an running windows app instance

### ISSUE THREAD

**Issue by wzlsquall** [appium/appium#13638]
## The problem

Now I want to use appium to connect my windows app, but this app allows multiple instance an one time. Is it posible that use appium to connect an running app, not a new instance?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1 desktop
* Desktop OS/version used to run Appium: Windows 10 pro

Thanks ~

**Comment by mykola-mokhnach** [comment]
Please use Appium forum for questions
