### ISSUE TITLE
Unable to launch Appium beta v1.16.0-beta.2

### ISSUE THREAD

**Issue by KS261187** [appium/appium#13632]
## The problem
I updated my Appium to beta version through npm and when I tried to launch my app, I started to get the below error. 

WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file. The file doesn’t exist. (Underlying error: The operation couldn’t be completed. No such file or directory)))

I am able to perfectly build the project from Xcode. So I don't think so it is related to code signing.

## Environment

* Appium version (or git revision) that exhibits the issue:1.16.0-beta 2
* Last Appium version that did not exhibit the issue (if applicable): 1.16.0-beta1
* Desktop OS/version used to run Appium:Mac OS
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:IOS
* Real device or emulator/simulator:Real Device
* Appium CLI or Appium.app|exe:CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Please fill out the report properly and provide the requested information

**Comment by EdulaSuryaKiranReddy** [comment]
I faced the same issue by configuring the WebDriverAgent project at location (../appium/node_modules/appium-webdriveragent).

Configure WebDriverAgent project at location **(../appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj).**

Thats where appium is trying to fetch the WebDriverAgent.

**Comment by KS261187** [comment]
Thank you, that did the trick. Not sure why they changed the path. I used to configure this from "./appium/node_modules/appium-webdriveragent" and now this got to changed to (../appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj). Appreciate your help on resolving this issue.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
