### ISSUE TITLE
uncaughtException: Android bootstrap socket crashed: Error: connect ECONNREFUSED 127.0.0.1:4724

### ISSUE THREAD

**Issue by mindarchitect** [appium/appium#13642]
## The problem

When trying to run Appium in docker image using different session, android bootstrap is crashing.

## Environment

* Appium 1.15.1:
* Windows 10:
* Android API 19
* Docker

## Details

When trying to run second test session using different capabilities inside docker image (UiAutomator1), bootstrap socket is crashing trying to connect to localhost of the image. I tried to change address and callback addres but it still uses 127.0.0.1 to connect using port 4724. I assume, this should be the host with emulator or device and it should be configured.

IMPORTANT: When running the same system configuration using normal appium instance (not from docker container) on localhost, everything works fine.

## Link to Appium logs

https://gist.github.com/mindarchitect/ff325462b38a7945a32011f38650b5f8

**Comment by KazuCocoa** [comment]
Does the test target work well inside the docker env?
(Or did you ran the appium inside docker and tried to connect to devices outside docker?)

I guess the logcat will help the investigation...

**Comment by mindarchitect** [comment]
Could you please clarify what "test target" is? Emulator? I did not run any emulators inside docker image, only appium. I am running appium only inside docker container.
Sorry I have this feeling that questions are being asked without actually understanding the issue...
Again, the problem is: all localhost references inside appium instance should be **configurable** to avoid referencing docker container host.
And again, running appium instance normally (not inside docker) on the same mashine works without any issues...
This is the second time I am facing the issues with this app. And considering the amount of bugs reported in issues list here **for the app that is the core component for quality assurance**, with all due respect questions should be a little bit more relevant...

**Comment by mykola-mokhnach** [comment]
>  all localhost references inside appium instance should be configurable to avoid referencing docker container host

I'll mark it as an improvement request

> Sorry I have this feeling that questions are being asked without actually understanding the issue...

Actually, nobody is obliged to even answer. People with different technical background do their best to help. I'm simply grateful to them for spending their time for free doing this.


Although, feel free to create a pull request. We'd be happy to review it

**Comment by mindarchitect** [comment]
> I'll mark it as an improvement request

Thank you.

> Actually, nobody is obliged to even answer. People with different technical background do their best to help. I'm simply grateful to them for spending their time for free doing this.

Really? Do you really think this is the strategy for the open source project and overall project success? Nobody is obliged??? Yes, why not. I am not obliged as well spending 2 days of my time (instead of 5 minutes dumb question) figuring out the problems of the app which is far from production ready...

If today you are not obliged to answer the question for free, tommorow there will be nobody to pay you for the this app, Mykola.....

**Comment by KazuCocoa** [comment]
Ah, thanks.
I misunderstood the situation (I imagined the UIA2 architecture)
