### ISSUE TITLE
An unknown server-side error occurred while processing the command. Original error: 'app' option is required for reinstall

### ISSUE THREAD

**Issue by dob730** [appium/appium#13643]
## The problem
while i am launching an app with appium m getting blow error

Exception in appium desktop Encountered internal error running command: Error: 'app' option is required for reinstall

and I have written below code---

from appium import webdriver

desired_caps = {}
desired_caps['platformName'] = 'Android'
desired_caps['platformVersion'] = '10.0'
desired_caps['deviceName'] = 'Android Emulator'
desired_caps['appPackage'] = 'com.android.calculator2'
desired_caps['appActivity'] = '.Calculator'

driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)

driver.find_element_by_name("1").click()
driver.find_element_by_name("5").click()
driver.find_element_by_name("9").click()
driver.find_element_by_name("delete").click()
driver.find_element_by_name("9").click()
driver.find_element_by_name("5").click()
driver.find_element_by_name("+").click()
driver.find_element_by_name("6").click()
driver.find_element_by_name("=").click()

driver.quit()

**Comment by KazuCocoa** [comment]
Could you attache the full appium server log?

**Comment by mykola-mokhnach** [comment]
I would guess that if the app is already installed on the device then noReset capability is necessary to tell Appium not to reset it on the session startup

**Comment by dob730** [comment]
I think the app have not installed on the device.
