### ISSUE TITLE
Cannot get 'xml' source of the current application

### ISSUE THREAD

**Issue by ansvijay** [appium/appium#13645]
## The problem
Appium is not able to find element on the native app. 

The code throws exception  like 'Cannot get 'xml' source of the current application'
[iPhoneXs.log](https://github.com/appium/appium/files/3896262/iPhoneXs.log)
 for iPhoneXs but the same code works on iPhone 8

## Environment
Appium 1.14
iPhone Xs (13.1.2) and iPhone 8 (12.2)

## Details

Code to find a element is not working for iPhone Xs with OS 13.1.2 but the same code works for iPhone 8 (12.2)

## Link to Appium logs
Attached 2 logs - iPhone8.log and iPhoneXs.log
At the bottom of the log you see the text "Search by Name or Username"
[iPhone8.log](https://github.com/appium/appium/files/3896201/iPhone8.log)
[iPhoneXs.log](https://github.com/appium/appium/files/3896274/iPhoneXs.log)

## Code To Reproduce Issue [ Good To Have ]
I am using the flowing code line 
`driver.findElement(By.xpath("//XCUIElementTypeTextField[@value='Search by Name or Username']"));
`
Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Appium 1.14 does not support iOS 13. Consider updating it to the most recent version (preferably appium@beta)

**Comment by ansvijay** [comment]
Issue is resolved after upgrading to Appium 1.15.1
