### ISSUE TITLE
Calling to url scheme not working 

### ISSUE THREAD

**Issue by BoazWarshawsky** [appium/appium#13647]
## The problem
I am trying to launch my app inside the test with URL Scheme address, but application not getting anywhere and test is stopped.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): None
* Desktop OS/version used to run Appium: Desktop
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Link to Appium logs

https://assets-production.applicaster.com/qa/zapp_qa/manual/boaz/appium_server.log

## Code To Reproduce Issue [ Good To Have ]
`self.driver.get('featureapp://present?rivers_configuration_id=b8c33237-9a06-467b-9bcd-67513c55fb60')`

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by BoazWarshawsky** [comment]
@mykola-mokhnach hi, can you please assist me with this ticket?
Thank You!

**Comment by KazuCocoa** [comment]
Can your app launch with `/Users/boazwarshawsky/Library/Android/sdk/platform-tools/adb -P 5037 -s FA8211A03831 shell am start -W -a android.intent.action.VIEW -d featureapp\://present\?rivers_configuration_id\=b8c33237-9a06-467b-9bcd-67513c55fb60 com.featureapp`?

**Comment by BoazWarshawsky** [comment]
@KazuCocoa Thanks for your answer.
Yes, I can open it in that way.

**Comment by KazuCocoa** [comment]
Then, you should wait for the launching by yourself.
Appium calls the intent, but does not wait for the command

**Comment by BoazWarshawsky** [comment]
You mean I should call to a CMD line above my self?

What about iOS? I don't have there reliable tools like ADB.

**Comment by KazuCocoa** [comment]
Yes, you can check the app status using https://appium.io/docs/en/commands/device/app/app-state/, for example.
I cannot remember about iOS for now, but I did checking the target app status using app state or find element with wait for both Android/iOS before.

**Comment by BoazWarshawsky** [comment]
@KazuCocoa according to this line: 
`/Users/boazwarshawsky/Library/Android/sdk/platform-tools/adb -P 5037 -s FA8211A03831 shell am start -W -a android.intent.action.VIEW -d featureapp\://present\?rivers_configuration_id\=b8c33237-9a06-467b-9bcd-67513c55fb60 com.featureapp`

I see that all the work is done with having this: 
`-d featureapp\://present\?rivers_configuration_id\=b8c33237-9a06-467b-9bcd-67513c55fb60 com.featureapp`

My question is if there is a way in Appium to send for launch this param of `-d ....`?

Thanks

**Comment by KazuCocoa** [comment]
`optionalIntentArguments` probably help you to set `-d xxxxx`
https://appium.io/docs/en/writing-running-appium/caps/

If it did not work, you also can call `mobile:shell` mobile option to send an arbitrary adb shell command to the device. https://appium.io/docs/en/commands/mobile-command/
(It need to relax security configuration https://appium.io/docs/en/writing-running-appium/security/ )

**Comment by BoazWarshawsky** [comment]
@KazuCocoa amazing, the above solved my problem for **Android**, the app launched as expected.

What about iOS? do we have a way sedding this param also there?

**Comment by KazuCocoa** [comment]
Only openUrl command and https://github.com/appium/appium/issues/13647#issuecomment-566015389 is my idea for iOS.

Potentially, `safariInitialUrl` caps might help, but I haven't launched a scheme with the capability.

You also can ask general questions in https://discuss.appium.io/

**Comment by BoazWarshawsky** [comment]
Thanks @KazuCocoa we can close the ticket.
