### ISSUE TITLE
An unknown server-side error occurred while processing the command. Original error: 'bundleId' desired capability not provided

### ISSUE THREAD

**Issue by omeluhin89** [appium/appium#13646]
## The problem
When i run tests, i have error: An unknown server-side error occurred while processing the command. Original error: 'bundleId' desired capability not provided
In Xcode build succeeded.
## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Desktop OS/version used to run Appium: macOS Mojave 10.14.6
* Mobile platform/version under test: iOS 12.4.3
* Real device: iPhone 6
* Xcode: Version 11.2.1 (11B500)

## Link to Appium logs
[AppiumLogs](https://gist.github.com/omeluhin89/16ef86415f536501b953acd494a3c04d)
[WDAlogs](https://gist.github.com/omeluhin89/df66a016773c5e004c4e72a4abac6668)
[ErrorTest](https://gist.github.com/omeluhin89/41b5db4b6189aa9fbdeb3d6670959f12)

**Comment by mykola-mokhnach** [comment]
Is the attached log correct. Then error there is different from the one in the issue title:
```
[debug] [XCUITest] Available devices: d28f22f9003281fc3af0f3ce8a97e30204a3a610
[XCUITest] Error: Unknown device or simulator UDID: 'f325b6bc5fe21a3fc9657ed75a28df4c438c3c83'
```

**Comment by omeluhin89** [comment]
Sorry. Now update logs [AppiumLogs](https://gist.github.com/omeluhin89/16ef86415f536501b953acd494a3c04d)

**Comment by mykola-mokhnach** [comment]
It looks like WebDriverAgent got cached from previous installations on the device. Remove it manually and make sire there are no other leftovers from previous stuff in Xcode derived data

**Comment by mykola-mokhnach** [comment]
Btw, I would recommend switching to appium@beta for browser automation. We did many fixes there recently

**Comment by mykola-mokhnach** [comment]
Also, combining fullReset and bundleId caps seems odd to me. Usually providing `bundleId` means the app is already preinstalled, so we don't want to reset anything (reset there means full app reinstall)

**Comment by omeluhin89** [comment]
> It looks like WebDriverAgent got cached from previous installations on the device. Remove it manually and make sire there are no other leftovers from previous stuff in Xcode derived data


Better to delete a project in Xcode and do it again?

**Comment by omeluhin89** [comment]
> Btw, I would recommend switching to appium@beta for browser automation. We did many fixes there recently


You can give a link to the repository with the installation

**Comment by mykola-mokhnach** [comment]
> Better to delete a project in Xcode and do it again?

Make sure to cleanup the project first

> You can give a link to the repository with the installation?

`npm i -g appium@beta`

**Comment by omeluhin89** [comment]
> Похоже, что WebDriverAgent был кэширован из предыдущих установок на устройстве. Удалите его вручную и сделайте так, чтобы в исходных данных XCode не было других остатков от предыдущего материала

**Comment by omeluhin89** [comment]
[appium@beta](https://gist.github.com/omeluhin89/a3a78bdd2b6cd885b32fe8468993d5d2)
[WDA](https://gist.github.com/omeluhin89/06cb8ca6356d673f3058687889fd56ad)
[test](https://gist.github.com/omeluhin89/70bc908d4ab6880b42fb2755630a6eab)

I deleted the WDA project, installed appium @ beta instead of appium 1.15. I deleted the WDA application from the device, but still the tests fail with the same error.(

**Comment by omeluhin89** [comment]
life is pain(

**Comment by mykola-mokhnach** [comment]
I see your tests use `noReset` option. Try to provide `fullReset: true` instead once and restart the test

**Comment by mykola-mokhnach** [comment]
or set `useNewWDA` to `true` in order to make sure the WDA build is replaced

**Comment by omeluhin89** [comment]
> or set `useNewWDA` to `true` in order to make sure the WDA build is replaced
When changed to true, the error falls
[Test](https://gist.github.com/omeluhin89/3bdd6794141adb7156e9111d56a2eb2f)

**Comment by omeluhin89** [comment]
> I see your tests use `noReset` option. Try to provide `fullReset: true` instead (at least once) and restart the test

same mistake

**Comment by mykola-mokhnach** [comment]
Please attach the updated log

**Comment by omeluhin89** [comment]
> Пожалуйста, приложите обновленный журнал с установленным значением true

[appium](https://gist.github.com/omeluhin89/c5dd9991084d55e13f93288f67ce4835)
[WDA](https://gist.github.com/omeluhin89/9c6a41363e5fc1375175e44ae3456721)

**Comment by mykola-mokhnach** [comment]
> [debug] [MJSONWP] Testing failed:
> [debug] [MJSONWP] 	No profiles for 'com.facebook.WebDriverAgentRunner.xctrunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.facebook.WebDriverAgentRunner.xctrunner'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
> [debug] [MJSONWP] 	No signing certificate "iOS Development" found: No "iOS Development" signing certificate matching team ID "79C4Q93M59" with a private key was found.
> [debug] [MJSONWP] 	WebDriverAgentRunner:
> [debug] [MJSONWP] 		WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file. The file doesn’t exist. (Underlying error: The operation couldn’t be completed. No such file or directory)))

Now the correct WDA binary is selected. Although, because this is a new source, it requires to be properly signed. Check https://github.com/appium/appium/issues?utf8=✓&q=is%3Aissue+%22No+signing+certificate%22+is%3Aclosed+ and/or https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

**Comment by omeluhin89** [comment]
> > [debug] [MJSONWP] Testing failed:
> > [debug] [MJSONWP] 	No profiles for 'com.facebook.WebDriverAgentRunner.xctrunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.facebook.WebDriverAgentRunner.xctrunner'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
> > [debug] [MJSONWP] 	No signing certificate "iOS Development" found: No "iOS Development" signing certificate matching team ID "79C4Q93M59" with a private key was found.
> > [debug] [MJSONWP] 	WebDriverAgentRunner:
> > [debug] [MJSONWP] 		WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file. The file doesn’t exist. (Underlying error: The operation couldn’t be completed. No such file or directory)))
> 
> Now the correct WDA binary is selected. Although, because this is a new source, it requires to be properly signed. Check [https://github.com/appium/appium/issues?utf8=✓&q=is%3Aissue+%22No+signing+certificate%22+is%3Aclosed+](https://github.com/appium/appium/issues?utf8=%E2%9C%93&q=is%3Aissue+%22No+signing+certificate%22+is%3Aclosed+) and/or https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

[WDA](https://gist.github.com/omeluhin89/a4bc59e19706501928e87fd4c3775cb8)
[appium](https://gist.github.com/omeluhin89/c66ea65f1abccfb0a643858e30b3bc72)

**Comment by omeluhin89** [comment]
I corrected the data, but now the test just hangs, this is only part of the appium log. WDA terminates immediately ((

**Comment by omeluhin89** [comment]
It works!!!

**Comment by omeluhin89** [comment]
Thank you very much))

**Comment by aelam** [comment]
@omeluhin89  How did you fix it
