### ISSUE TITLE
An unknown server-side error occurred while processing the command

### ISSUE THREAD

**Issue by pacchan** [appium/appium#13644]
## The problem
An unknown server-side error occurred while processing the command. Original error: Did not get any response after 300s

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.0/1.15.1/beta 1.16.02
* Desktop OS/version used to run Appium: mac OS 10.15.1
* Node.js version (unless using Appium.app|exe): v13.2.0
* Npm or Yarn package manager: 6.13.1
* Mobile platform/version under test: iOS 13.1.2
* Real device or emulator/simulator: iPhone X 

## Details

I run web testing on iOS 13.1.2. The previous steps can be implemented without error. while it implemented CLICK command. It took about 10 mins and reported the error above. 

I used to use Appium 1.15.1 and now downgrade to 1.15.0. I also tried to upgraded and downgraded the Katalon Studio Version but the issue still occurs.

## Link to Appium logs

Please refer to [logd code](https://gist.github.com/pacchan/d662889b4ad4d6c4be3f5980c968a224) 

![image](https://user-images.githubusercontent.com/30913258/69693674-13229e80-113b-11ea-978f-dfaaef53dd32.png)

**Comment by pacchan** [comment]
Try on another test case. Return the same result with different command
![image](https://user-images.githubusercontent.com/30913258/69694507-e8861500-113d-11ea-91e8-529e14f1c144.png)

**Comment by mykola-mokhnach** [comment]
Please try appium@beta

**Comment by mykola-mokhnach** [comment]
Also, the attached log is useless. Please attach the full appium server instead

**Comment by pacchan** [comment]
> Please try appium@beta

Which version of appium?

**Comment by pacchan** [comment]
I think it causes an error. 

**Sending '_rpc_forwardSocketData:** . It is not getting any response at the stage. 

Is it because it is not stable testing on iOS 13 at the moment? 

It should receive a response if it works perfectly, something like:
![image](https://user-images.githubusercontent.com/30913258/69769165-9cdc7580-11e8-11ea-850a-7fa335b1406e.png)

**Comment by mykola-mokhnach** [comment]
> Hi @mykola-mokhnach . I tried the Beta but it doesn't help

Can you provide the updated log?

**Comment by pacchan** [comment]
> > Hi @mykola-mokhnach . I tried the Beta but it doesn't help
> 
> Can you provide the updated log?

I have updated the appium log. Please check

**Comment by mykola-mokhnach** [comment]
> [35m[Appium][39m Welcome to Appium v1.15.0

Where is appium@beta there?

**Comment by pacchan** [comment]
@mykola-mokhnach 
1.16.3Beta causes the code signing issue [logd code](https://gist.github.com/pacchan/d662889b4ad4d6c4be3f5980c968a224)

**Comment by KazuCocoa** [comment]
Did you configure the below again?
https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

**Comment by pacchan** [comment]
> Did you configure the below again?
> https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

Yes, I did. I checked many times

**Comment by pacchan** [comment]
Updated: I reverted Appium back to 1.15.1. Signing issue resolved. but still facing the same issue as the topic.

does not get any response

**Comment by KazuCocoa** [comment]
What is the output of below command?

> xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=0f040a74e28d16c7291dcc3eca2b9e01fbb15113 IPHONEOS_DEPLOYMENT_TARGET=13.2 GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent

---

If it works well, like below lines will appear (I installed and ran as v1.16.0-beta.3 module now)

> 2019-11-29 11:13:53.368921+0900 WebDriverAgentRunner-Runner[752:128998] Built at Nov 29 > 2019 11:13:36
> 2019-11-29 11:13:53.387967+0900 WebDriverAgentRunner-Runner[752:128998] ServerURLHere->http://192.168.1.103:8100<-ServerURLHere
> 2019-11-29 11:13:53.389014+0900 WebDriverAgentRunner-Runner[752:129006] Using singleton test manager

Please make sure the webdriveragent is 2.3.3.

```
$ npm -g ls | grep "webdriveragent"
│ │ ├─┬ appium-webdriveragent@2.3.3
```

**Comment by pacchan** [comment]
> webdriveragent

Hi I did get the
**Using singleton test manager** but not getting **listening to USB**
I have reverted Appium to 1.15.1 and face the not getting response issue.

For the command **$ npm -g ls | grep "webdriveragent"** does not work to me

**Comment by pacchan** [comment]
@mykola-mokhnach 
1. If I update to Appium beta. I experience a sematic issue which is the same as https://github.com/appium/appium/issues/13307. The desired solution in the ticket is to use the latest Appium which is 1.15.1
2. This is also the reason why I did not use Appium Beta. It not only causes a sematic issue but also causes Xcode 65 signing issue when I run the test, no matter if I used developer account or free account. I am finally shown with "Using singleton test manager" and success on Xcode though.
3. So I have to use 1.15.1 where leads an issue as I reported in this ticket. Not getting a response at certain point, sometimes on steps 3/7/10/etc. 


Can you please advise a workaround?

**Comment by mykola-mokhnach** [comment]
Unfortunately I don't have any more good ideas on how to make the beta version working on your machine.

**Comment by KazuCocoa** [comment]
> not getting **listening to USB**

I have no idea where the message comes. (Maybe Katalon studio shows it?)

But if `Using singleton test manager` appeared on your console by 

> xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=0f040a74e28d16c7291dcc3eca2b9e01fbb15113 IPHONEOS_DEPLOYMENT_TARGET=13.2 GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent

 without 65 error, Appium script should have worked since appium issued the command.

I thought you installed appium as `npm -g` option but did not, i see. > `npm -g ls | grep "webdriveragent"` does not work
I would have liked to ensure the webdriveragent version you installed as the beta then, but maybe the Katalon environment was 

hm, I'm not familiar with Katalon environment, so if they handled something inside their IDE, I have no idea to resolve the beta issue, sorry.
(Technically, we have not changed sign stuff on Xcode project between Appium 1.15 and current beta)

**Comment by pacchan** [comment]
Hi @mykola-mokhnach , @KazuCocoa 
Thank you for your patient response.

I have found out this after clearing up all the Xcode driven data and reinstall everything. It seems Core.js corrupted. Although it is not a key requirement for building up WDA I would like to ask if this causes any issue? 
![image](https://user-images.githubusercontent.com/30913258/69957167-ef11f380-1566-11ea-9693-64e242e24d60.png)

After I found out this warning alerts, I have followed #7051 and run **npm install --save core-js@^3** in terminal.  

**Would it be the cause?** Can I just leave it like it or Can you please advise a workaround to solve this? 

But there are certain bundles do not update accordingly. Please refer to [Terminal code](https://gist.github.com/pacchan/964daac26ad200524976462b3a83fa5f)

Kindly Regards,

**Comment by pacchan** [comment]
> > not getting **listening to USB**
> 
> I have no idea where the message comes. (Maybe Katalon studio shows it?)
> 
> But if `Using singleton test manager` appeared on your console by
> 
> > xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=0f040a74e28d16c7291dcc3eca2b9e01fbb15113 IPHONEOS_DEPLOYMENT_TARGET=13.2 GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent
> 
> without 65 error, Appium script should have worked since appium issued the command.
> 
> I thought you installed appium as `npm -g` option but did not, i see. > `npm -g ls | grep "webdriveragent"` does not work
> I would have liked to ensure the webdriveragent version you installed as the beta then, but maybe the Katalon environment handled it differently
> 
> hm, I'm not familiar with Katalon environment, so if they handled something inside their IDE, I have no idea to resolve the beta issue, sorry.
> (Technically, we have not changed sign stuff on Xcode project between Appium 1.15 and current beta)


Hi @KazuCocoa .

Update: I think I just got what you after. 

Yes, Version is 2.3.3. Hope it gives you more infomation here.
![image](https://user-images.githubusercontent.com/30913258/69957911-90e61000-1568-11ea-9669-3e27e1aa4fa4.png)

**Comment by mykola-mokhnach** [comment]
The terminal output is totally fine. The only issue there is to built WebDriverAgent in your environment

**Comment by pacchan** [comment]
@mykola-mokhnach , Beta 1.16.03 cause this semantic issue while building up WDA Lib on real device. Would it be a cause?

![image](https://user-images.githubusercontent.com/30913258/70020014-3b554600-15f0-11ea-889a-1ba605c10afe.png)

**Comment by pacchan** [comment]
Update : 

I have fixed this by following #13352
But code signing issue 65 persists........

**Comment by pacchan** [comment]
Hi @mykola-mokhnach  @KazuCocoa 

Platform section on MacOS does not indicate provisioning Profile and particular Signing Certificate as iOS above. Will it be the cause and is it expected? 

![image](https://user-images.githubusercontent.com/30913258/70188485-b5eba600-1755-11ea-9a3e-2a0b48c48526.png)

Thanks

**Comment by KazuCocoa** [comment]
it looks okay, but you probably should have changed the bundle identifier since your provisioning profile was not for `com.facebook` account.

**Comment by pacchan** [comment]
**Update:**

I find an iOS 12.4.1 device and just ran the same test script on it. The test is implemented nicely without any issue with Appium 1.15.1, Xcode 11.2.1

I assume it is iOS 13 issue?

**Comment by KazuCocoa** [comment]
hm, I was able to run tests on my iOS 13 environment, but it might happen, unfortunately.


btw, I always use `xcodeOrgId`, `xcodeSigningId` and `updatedWDABundleId` instead of changing preferences directly.

**Comment by pacchan** [comment]
> hm, I was able to run tests on my iOS 13 environment, but it might happen, unfortunately.
> 
> btw, I always use `xcodeOrgId`, `xcodeSigningId` and `updatedWDABundleId` instead of changing preferences directly.

I also did some research Will this require to install the Appium application? 
because I have limited storage left on Hard Drive :(

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing more we could do here on Appium side.The code signing works properly for other people, so it is most likely an issue with local environment setup.
