### ISSUE TITLE
appium timezone

### ISSUE THREAD

**Issue by mirudhubashini** [appium/appium#13655]
@KazuCocoa kindly help me to the process of getting a connected device timezone and it's time with am/pm. want to get the time for both real and cloud devices.

**Comment by mirudhubashini** [comment]
There is a function called getDeviceTime but it's not giving am/pm format thing and the device timezone as well. Kindly help me.

**Comment by KazuCocoa** [comment]
Since 1.15.0, `mobile:deviceInfo` http://appium.io/docs/en/commands/mobile-command/  returns the device timezone. You should convert the format in your side. Appium returns like `2018-06-12T11:13:31+02:00`

**Comment by mirudhubashini** [comment]
Yeah, it's fine but how do I know that returned time PM/AM format?

**Comment by KazuCocoa** [comment]
Do you mean how to convert the time to am/pm format from `'YYYY-MM-DDTHH:mm:ssZ'` ?https://github.com/appium/appium-android-driver/blob/c0b6fb64483601c710f7afbfbb8e0230e7b19f52/lib/commands/general.js#L37

It depends on your language.
```ruby
# Ruby
DateTime.parse('2018-06-12T11:13:31+02:00').strftime('%I:%M:%S %p') #=> "11:13:31 AM"
```

**Comment by mirudhubashini** [comment]
I've been using Java language so can you provide the format to get the time to am/pm. It would be better since I've tried so many ways.

**Comment by KazuCocoa** [comment]
I guess like below.

```java
String d="2018-06-12T15:13:31+02:00";
SimpleDateFormat isoFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss");
Date date = isoFormat.parse(d);
System.out.println(new SimpleDateFormat("hh:mm:ss").format(date)); // "03:13:31"
````

Please ask further questions in https://discuss.appium.io/

**Comment by mirudhubashini** [comment]
Thank you for sharing the code but it's not **returning am/pm** thing with the parsed time when I print it. As u mentioned it's returned - (For Eg:)  "04:29:21" alone.  I want am/pm thing with the parsed time. Kindly help me out.

**Comment by mirudhubashini** [comment]
@KazuCocoa  I just want to know the am/pm when I retrieve the device time. Kindly provide the details as I mentioned above.

**Comment by KazuCocoa** [comment]
You can simply detect AM/PM by yourself with `SimpleDateFormat("HH").format(iso.parse(d))` and control flow to build data format you want to get if Java libraries did not have a feature to print AM/PM. I don't know Java libraries which returns AM/PM.

BTW, you can also call https://appium.io/docs/en/commands/device/system/system-time/ and an argument like the python client's example to customisie the format.
The available format is https://momentjs.com/docs/  as https://github.com/appium/appium-android-driver/blob/692c06f2946d90dfa484ef2991dc0b0c864c0575/lib/commands/general.js#L31-L35
