### ISSUE TITLE
Installing Appium server cli tool takes 21 minutes instead of max 2.5 minutes

### ISSUE THREAD

**Issue by BoazWarshawsky** [appium/appium#13656]
## The problem

I am running UI tests in CircleCI Mac machine and using there Appium server cli tool.
It seems that it takes the Mac machine to install the cli tool using npm 21 minutes.
When I am running this install from local machine it takes in average 2.5 minutes max.

The bash commands I am calling in order to install are:
npm install -g appium@1.15.1
npm install wd

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable): 0.14
* Desktop OS/version used to run Appium:CLI
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
Link to the install process prints:
https://assets-production.applicaster.com/qa/zapp_qa/manual/boaz/install_appium_server.log

## Code To Reproduce Issue [ Good To Have ]

npm install -g appium@1.15.1
npm install wd

**Comment by imurchie** [comment]
This is probably better asked of the Circle-CI folks.

The only thing from the logs that jumps out at me is that Appium 1.15.1 does not support Node 8.

**Comment by BoazWarshawsky** [comment]
Sorry for not updating the ticket, 
the problem was because of network connectivity when installing Appium on Circle CI cloud machine
