### ISSUE TITLE
[Feature] Do not stop video recording with "driver.resetApp()"

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#13659]
## The problem
When we use video recording feature and executing app reset - video stops recording. Later trying to save video cause "0" byte file.
Capabilities:  fullReset: false, noReset: false

## Environment
* Appium version (or git revision) that exhibits the issue: 1.16.0-beta.1
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Simulator

**Comment by mykola-mokhnach** [comment]
Please attache the full server log

**Comment by amedvedjev** [comment]
@mykola-mokhnach here it is: https://gist.github.com/amedvedjev/496b5e6c79769866197cbe78dfc5ac69

```
// test code is
        log("driver.resetApp(): start -----------------------------------");
        sleep(10000);
        driver.resetApp();
        sleep(10000);
        log("driver.resetApp(): end -------------------------------------");
        Assert.assertTrue(false, "failed");
```

see in logs while trying to stop video after test: "_Screen recording is not running. There is nothing to stop._"

**Comment by mykola-mokhnach** [comment]
I don't think it would be easy to make such feature possible without applying ugly hacks, since reset internally calls delete/create session. Can you avoid calling reset in the client code?

**Comment by amedvedjev** [comment]
@mykola-mokhnach 
test includes login with another user.
for a while we have 2 choices:
1) i do record stop before and save it. after reset restart record (i am on this now)
2) we need ask dev to RESET client after sending some command with parameter.

**Comment by mykola-mokhnach** [comment]
So your task is actually to reset Safari browser while running the test (aka stop it, clear caches/data, start again), right?  
In general, the resetApp call is quite ineffective and slow. I would be happy to remove it at all, but cannot because of legacy reasons.

**Comment by amedvedjev** [comment]
no native app. valid for iOS mostly as far as it closes session while with android Appium does it on the fly.

**Comment by mykola-mokhnach** [comment]
you can reinstall iOS app in order to reset it without calling resetApp. 
Use the following sequence of calls:
- terminateApp
- uninstallApp
- installApp
- activateApp

**Comment by amedvedjev** [comment]
thanks! will try and return...

**Comment by mykola-mokhnach** [comment]
@amedvedjev Do you have any updates on the issue?

**Comment by mykola-mokhnach** [comment]
Closed because of no response
