### ISSUE TITLE
Unable to remove port forward 'Error executing adbExec. 

### ISSUE THREAD

**Issue by sinnanje** [appium/appium#13652]
## The problem

Unable to remove port forward 'Error executing adbExec. 

## Environment

* Appium version  - 1.15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: windows 10

* Mobile platform/version under test: android
* Real device or emulator/simulator: bluestacks
* Appium CLI or Appium.app|exe: appium.exe

## Details

I tried appium.io with android studio emulator on windows and it works fine but android emulator is slow and buggy.

I was trying to connect to bluestacks simulator using appium.io but it gives me this error:

An unknown server-side error occurred while processing the command. Original error: Failed to launch Appium Settings app: Condition unmet after 5202 ms. Timing out.

Appium settings being used:

{
  "deviceName": "emulator-5554",
  "platformName": "android",
  "appPackage": "com.google.android.apps.translate",
  "appActivity": ".TranslateActivity",
  "noReset": true
}

## Link to Appium logs

[AndroidDriver] Failed to launch Appium Settings app: Condition unmet after 
5460 ms. Timing out.
[UiAutomator2] Deleting UiAutomator2 session
[ADB] Running 'C:\Users\SARAH\AppData\Local\Android\Sdk\platform- 
tools\adb.exe -P 5037 -s localhost\:5555 shell am force-stop 
com.google.android.apps.translate'
[ADB] Removing forwarded port socket connection: 8200 
[ADB] Running 'C:\Users\SARAH\AppData\Local\Android\Sdk\platform- 
tools\adb.exe -P 5037 -s localhost\:5555 forward --remove tcp\:8200'
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. 
Original error: 'Command 
'C:\\Users\\SARAH\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 
5037 -s localhost\:5555 forward --remove tcp\:8200' exited with code 1'; 
Stderr: 'adb.exe: error: listener 'tcp:8200' not found'; Code: '1''
[BaseDriver] Event 'newSessionStarted' logged at 1574930252123 (00:37:32 
GMT-0800 (Pacific Standard Time))
[MJSONWP] Encountered internal error running command: Error: Failed to 
launch Appium Settings app: Condition unmet after 5460 ms. Timing out.
[MJSONWP] at spin Appium\resources\app\node_modules\appium\node_modules\asyncbox\lib\asyncbox.js:127:9
 [HTTP] <-- POST /wd/hub/session 500 8789 ms - 217
 [HTTP] 
 [HTTP] --> DELETE /wd/hub/session
 [HTTP] {}
 [HTTP] No route found. Setting content type to 'text/plain'
 [HTTP] <-- DELETE /wd/hub/session 404 1 ms - 57
 [HTTP]

**Comment by mykola-mokhnach** [comment]
Have you tried to run Appium settings manually on that emulator? Does its process stay in running state after the app is closed?

**Comment by mykola-mokhnach** [comment]
What is the Android API version?

**Comment by sky7st** [comment]
I think I have a similar problem.
[AndroidDriver] Failed to launch Appium Settings app: Condition unmet after 5267 ms. Timing out.

desire_caps = {
    'platformName': 'Android',
    'deviceName': 'emulator-5556',
    'platformVersion': '5.1.1',
    'appPackage': myPackage,
    'appActivity': mtActivity,
    'noReset': True,
    'fullReset': False
}

the api version is 22
The Appium Settings app did crash

**Comment by KazuCocoa** [comment]
> The Appium Settings app did crash

Do you have the crash log? @sky7st 
I could launch the app on the same version's emulator. So I wondered what error message appeared.

**Comment by sky7st** [comment]
[https://gist.github.com/sky7st/6417b1532dd6a95e6ab3e57c70ba4543](The server log)

[https://gist.github.com/sky7st/bf5362377b9dc77c6eb1b60a90679178](logcat)

**Comment by mykola-mokhnach** [comment]
Please try appium@beta. Android 5 has known issue with running process detection, which has been fixing in beta

**Comment by sky7st** [comment]
Is it available to change the appium version in the appium desktop by the beta source?

**Comment by mykola-mokhnach** [comment]
yes, it is [possible](https://github.com/appium/appium-desktop/issues/970#issuecomment-517935891)

**Comment by sky7st** [comment]
```python
from appium  import webdriver

desire_caps = {
    'platformName': 'Android',
    'deviceName': 'emulator-5556',
    'platformVersion': '5.1.1',
    'appPackage': 'com.tencent.mm',
    'appActivity': '.ui.LauncherUI',
    'noReset': True,
    'fullReset': False
}

driver = webdriver.Remote('http://127.0.0.1:4723/wd/hub', desire_caps)
```
when using these code, it opens the activity.
But it also raised an error so the driver object has not be returned.
```
Encountered internal error running command: TypeError: driver.onUnexpectedShutdown is not a function
```

**Comment by KazuCocoa** [comment]
Probably https://github.com/appium/appium/issues/13660 ?

**Comment by sky7st** [comment]
In my case, it's the appium-uiautomator2-driver?

**Comment by sky7st** [comment]
I've changed dependencies version of "appium-android-driver" and "appium-base-driver" in the package.json.
But after rebuilding it, it still raised the same error.

**Comment by mykola-mokhnach** [comment]
Simply remove everything and install appium@beta

**Comment by sky7st** [comment]
Thanks for you replies.
by using
`npm install -g appium@beta`
it works
