### ISSUE TITLE
Not able to launch application in ios 

### ISSUE THREAD

**Issue by rajkumar-cp** [appium/appium#13651]
## The problem

When we try to install application the application is not launching properly. It throws an error saying  “Application name” is damaged and cannot be opened. You should move it to the bin

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: mac os (10.15.1)
* Node.js version (unless using Appium.app|exe): 
* Npm or Yarn package manager: 6.4.1
* Mobile platform/version under test: 13.0
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: .app

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/rajkumar-cp/daa46dbc4c68443d421e910d6594b278

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Have you tried to install the application manually to the simulator? Did it work?

**Comment by rajkumar-cp** [comment]
@mykola-mokhnach 

Yeah i tried but installation is not happening by that way too. Any clue on why that was the case ? Am i missing to install any certificate or something ? Do i need to ask for anything from my developer ?

**Comment by mykola-mokhnach** [comment]
You probably got a damaged application. Ask the developers to provide a fixed build
