### ISSUE TITLE
Upgrade to uiAutomator2 not working

### ISSUE THREAD

**Issue by walkeraki** [appium/appium#13657]
## The problem

When capability uiAutomator2 is set findElement, screenshot and similar stuff dont work anymore.
Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8200
## Environment

* Appium version (or git revision) that exhibits the issue: v1.13.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: windows 10
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: android
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

## Details

I ran appium inspector and launched my app.. I found an element and pressed click on it.. Everything worked as it should.. With automator2.. But when running from my code crash happens when first findelement is called.. I tried with screenshot as well. I checked logs from inspector run and my run and arent really much different.. they both use same client version.. java code appium version is 6.1.0

## Link to Appium logs

This one is not working one from code
https://gist.github.com/walkeraki/d2ceb07b2693629e802ca8464772ebd5

This is one from inspector that works
https://gist.github.com/walkeraki/dce00fea743d3ccbef0a26bf8dab0315

**Comment by mykola-mokhnach** [comment]
Appium 1.13 is out of date. Please upgrade it to the most recent version

**Comment by walkeraki** [comment]
did that already.. same thing happened

**Comment by mykola-mokhnach** [comment]
Could you provide the logcat output then?

**Comment by walkeraki** [comment]
https://gist.github.com/walkeraki/56b5159d0b069f90f6fd531b95f91c4c

**Comment by mykola-mokhnach** [comment]
This is the server log. The logcat one is different

**Comment by mykola-mokhnach** [comment]
https://appiumpro.com/editions/53

**Comment by walkeraki** [comment]
https://gist.github.com/walkeraki/da728f95f5441e1c6f0a73d75b32b8af

**Comment by mykola-mokhnach** [comment]
Is the attached log correct?

> [2019-12-02T09:44:53+0100] [ALL] 12-02 09:42:58.561 13611 13630 I appium  : channel read invoked!
> [2019-12-02T09:44:53+0100] [ALL] 12-02 09:42:58.561 13611 13630 I appium  : channel read: GET /wd/hub/sessions
> [2019-12-02T09:44:53+0100] [ALL] 12-02 09:42:58.561 13611 13630 I appium  : AppiumResponse: {"sessionId":"None","value":[{"id":"c500e0ef-88fd-4d08-b24f-bbde2b8cb882","capabilities":{"fullReset":true,"webStorageEnabled":false,"platformName":"android","desired":"{platformName=android, app=C:\\JureL\\sampleApp.apk, deviceName=Android Device, fullReset=true}","appPackage":"com.outfit7.at.sampleapp","networkConnectionEnabled":true,"warnings":"{}","app":"C:\\JureL\\sampleApp.apk","takesScreenshot":true,"platform":"LINUX","databaseEnabled":false,"deviceUDID":"YOGA30BF8E90","deviceName":"YOGA30BF8E90","locationContextEnabled":false,"javascriptEnabled":true}}]}
> [2019-12-02T09:44:53+0100] [ALL] 12-02 09:42:58.565  3214  3227 D InputMethodManagerService: defaultImiId = com.google.android.inputmethod.latin/com.android.inputmethod.latin.LatinIME
> [2019-12-02T09:44:53+0100] [ALL] 12-02 09:42:58.566  5101  5147 I AccountTypeManager: the AuthenticatorDescription [] auths = [Landroid.accounts.AuthenticatorDescription;@d34439c
> [2019-12-02T09:44:53+0100] [ALL] 12-02 09:42:58.566  5101  5147 I AccountTypeManager: the   type is com.google.android.gm.exchange the auth is = AuthenticatorDescription {type=com.google.android.gm.exchange}
> [2019-12-02T09:44:53+0100] [ALL] 12-02 09:42:58.572 13611 13631 I appium  : channel read invoked!
> [2019-12-02T09:44:53+0100] [ALL] 12-02 09:42:58.572 13611 13631 I appium  : channel read: DELETE /wd/hub/session/c500e0ef-88fd-4d08-b24f-bbde2b8cb882
> [2019-12-02T09:44:53+0100] [ALL] 12-02 09:42:58.573 13611 13631 I appium  : Delete session command

I observe no errors there - the session is started and then immediately deleted. No calls to other endpoints so far

**Comment by walkeraki** [comment]
I think we have found the issuse.. We were messing with the ports at some point and it seems automator2 needed some that 1 didnt need... Thanks anyways
