### ISSUE TITLE
send keys persian text

### ISSUE THREAD

**Issue by yz1992** [appium/appium#13665]
hi,
i want to input  persian text with appium but i cannot 
for emaple :
self.driver.find_element_by_xpath("//*[@id='input_text_content_type_et_first']").send_keys('سلام')
but in input text dont type سلام

**Comment by mykola-mokhnach** [comment]
Please fill out the issue report properly and attach the server log

**Comment by yz1992** [comment]
03:31:27 PM	Waiting for element: xpath=(//*[@id='input_text_content_type_et_first'])[1]

03:31:27 PM	Element found, (360,714). Total search time is 0 sec.

03:31:27 PM	Waiting for element: xpath=(//*[@id='input_text_content_type_et_first'])[1]

03:31:27 PM	Element found, (360,714). Total search time is 0 sec.

03:31:28 PM	Waiting for element: xpath=(//*[@id='input_text_content_type_et_first'])[1]

03:31:28 PM	Element found, (360,444). Total search time is 0 sec.

03:31:28 PM	Waiting for element: xpath=(//*[@id='input_text_content_type_et_first'])[1]

03:31:28 PM	Element found, (360,444). Total search time is 0 sec.

**Comment by yz1992** [comment]
please just say to me appium  send_keys  support arabic or persian letter or not ?
if yes how?

**Comment by mykola-mokhnach** [comment]
> please just say to me appium send_keys support arabic or persian letter or not ?
if yes how?

Sorry, but it does not work like that. Appium is a set of different drivers (for Android there are at least 3 native drivers), where text sending works differently in each of them. Also, the testing platform and its version matters.

**Comment by yz1992** [comment]
self.dc['reportDirectory'] = self.reportDirectory
        self.dc['reportFormat'] = self.reportFormat
        self.dc['testName'] = self.testName
        self.dc['udid'] = 'LGK430JRDAZ94L'
        self.dc['deviceName'] = 'LG'
        self.dc['appPackage'] = 'cab.snapp.passenger'
        self.dc['appActivity'] = '.activities.launcher.LauncherActivity'
        self.dc['platformName'] = 'android'
        self.dc['unicodeKeyboard'] = True
        #self.dc['resetKeyboard'] = True
        self.driver = webdriver.Remote('http://localhost:4723/wd/hub', self.dc)

**Comment by mykola-mokhnach** [comment]
no really. I would prefer the standard issue reporting form to be filled up properly as it contains all the necessary fields

**Comment by amedvedjev** [comment]
how about add capability ->
```
unicodeKeyboard | Enable Unicode input, default false | true or false
```

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing more to do here without the requested details. Closed as incomplete
