### ISSUE TITLE
Can not set appWaitDuration shorter than 20000 ms 

### ISSUE THREAD

**Issue by camillake** [appium/appium#13663]
## The problem

Can not set appWaitDuration shorter than 20000 ms 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): not sure
* Desktop OS/version used to run Appium: MacOS 10.13.6
* Node.js version (unless using Appium.app|exe): v11.6.0
* Npm or Yarn package manager:  6.11.2
* Mobile platform/version under test: Android 8.0
* Real device or emulator/simulator: Real device / Samsung
* Appium CLI or Appium.app|exe: Appium-Python-Client==0.48

## Detail
I found there is a 20000 ms in appium-adb apk-utils.js (https://github.com/appium/appium-adb/blob/3a171c6b5866860819b86c2cadbf0f2c57b56518/lib/tools/apk-utils.js).

 if (_.isInteger(startAppOptions.waitDuration) && startAppOptions.waitDuration > 20000) {
      shellOpts.timeout = startAppOptions.waitDuration;
    }

**Comment by mykola-mokhnach** [comment]
Please fill out the issue reporting form properly and provide the requested info

**Comment by mykola-mokhnach** [comment]
Is there anything preventing you from creating a PR?

**Comment by mykola-mokhnach** [comment]
Now in appium@beta it is possible to set any values >=0
