### ISSUE TITLE
Encountered internal error running command: Error: Could not determine iOS SDK version: Command 'xcrun --sdk iphonesimulator --show-sdk-version' timed out after 15000ms

### ISSUE THREAD

**Issue by LavanyaReddy-Idamakanti** [appium/appium#13664]
## The problem

Error: Encountered internal error running command: Error: Could not determine iOS SDK version: Command 'xcrun --sdk iphonesimulator --show-sdk-version' timed out after 15000ms

while I'm trying to Automate Application which is already installed in my mobile, unable to open the application using appium. Facing below issue.

"desiredCapabilities":{"automationName":"XCUITest","bundleId":"com.AAAA.BBBB","clearSystemFiles":true,"deviceName":"iPhone","platformName":"iOS","platformVersion":"13.2","udid":"DSFGDSGSDG.......","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"automationName":"XCUITest","bundleId":"com.AAAAA.BBBBB","clearSystemFiles":true,"deviceName":"iPhone","platformName":"iOS","platformVersion":"13.2","udid":"SGFDSGSDAFDASF.......","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1575280171581 (15:19:31 GMT+0530 (IST))
[Appium] Appium v1.12.1 creating new XCUITestDriver (v2.110.1) session
[Appium] Capabilities:
[Appium]   automationName: XCUITest
[Appium]   bundleId: com.AAAA.BBBB
[Appium]   clearSystemFiles: true
[Appium]   deviceName: iPhone
[Appium]   platformName: iOS
[Appium]   platformVersion: 13.2
[Appium]   udid: SGFDSGSDAFDASF.......
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[BaseDriver] Creating session with MJSONWP desired capabilities: {"automationName":"XCUITest...
[BaseDriver] Session created with session id: d936282f-d6db-4485-ab6b-db4581fc7f1b
[XCUITest] Current user: 'LAVANYA-mac'
[XCUITest] Available devices: SGFDSGSDAFDASF.......
[XCUITest] Creating iDevice object with udid 'SGFDSGSDAFDASF.......'
[XCUITest] Determining device to run tests on: udid: 'SGFDSGSDAFDASF......., real device: true
[XCUITest] Xcode version set to '11.2.1' (tools v11.2.0.0.1.1571444319)
[XCUITest] Error: Could not determine iOS SDK version: Command 'xcrun --sdk iphonesimulator --show-sdk-version' timed out after 15000ms
[XCUITest]     at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[XCUITest]     at errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/utils.js:75:9)
[XCUITest]     at process._tickCallback (internal/process/next_tick.js:68:7)
[XCUITest] Error: Could not determine iOS SDK version: Command 'xcrun --sdk iphonesimulator --show-sdk-version' timed out after 15000ms
[XCUITest]     at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[XCUITest]     at errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/utils.js:75:9)
[XCUITest]     at process._tickCallback (internal/process/next_tick.js:68:7)
[XCUITest] No WebDriverAgent derived data available, so unable to clear system files
[BaseDriver] Event 'newSessionStarted' logged at 1575280172292 (15:19:32 GMT+0530 (IST))
[MJSONWP] Encountered internal error running command: Error: Could not determine iOS SDK version: Command 'xcrun --sdk iphonesimulator --show-sdk-version' timed out after 15000ms
[MJSONWP]     at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[MJSONWP]     at errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/utils.js:75:9)
[MJSONWP]     at process._tickCallback (internal/process/next_tick.js:68:7)
[HTTP] <-- POST /wd/hub/session 500 713 ms - 254
[HTTP] 
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 1 ms - 57

Note: I have executed belowe  commands through terminal. But yet issue not get resolved.
1. sudo /usr/bin/xcode-select -switch /Applications/Xcode.app/Contents/Developer
2. When I run "xcrun --sdk iphonesimulator --show-sdk-version" this command  through the terminal I'm getting '13.2' 
3. And then restarted the Mac and appium session

## Environment

* Appium version (or git revision) that exhibits the issue:1.12.1
* Last Appium version that did not exhibit the issue (if applicable):No Sure
* Desktop OS/version used to run Appium:10.15.1 
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:6.13.1
* Mobile platform/version under test:13.2
* Real device or emulator/simulator:real device
* Appium CLI or Appium.app|exe:appium.app

## Code To Reproduce Issue [ Good To Have ]
I didn't use any sample code. I'm just trying to open the application using Appium Desktop.

Below are the capabilities which I have used in appium:
{
  "platformName": "iOS",
  "automationName": "XCUITest",
  "bundleId": "application bundle id,
  "deviceName": "iPhone",
  "clearSystemFiles": true,
  "udid": "valid udid of my mobile",
  "platformVersion": "13.2"
}

**Comment by mykola-mokhnach** [comment]
iOS 13 is only supported since Appium 1.15 (preferably use appium@beta )

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
