### ISSUE TITLE
Unable to scroll in android application in Appium using Python

### ISSUE THREAD

**Issue by rguptaankit** [appium/appium#13666]
I am trying to scroll a screen of android application in appium using python but scrolling is not working. Looks like scrollable part is web element. Please help me out to resolve this problem. Please suggest what to do for scrolling Native & Web element. Also, if there is need to switch from Native to Webview, please suggest how to do it.

**Comment by mykola-mokhnach** [comment]
Kindly use Appium forum to ask questions
