### ISSUE TITLE
Unable to click on a button using Content-desc in appium

### ISSUE THREAD

**Issue by knsaicharan** [appium/appium#13661]
I'm new to testing in Appium. I was able to set everything up and to run the test. I used UiAutomatorViewer to get access to some Buttons, now I need to Click on a Button, but I just got the Cont-desc. I tried the following XPaths but I ended up getting an error. Any Help would be nice.

1. @findby(xpath = "//*[@contentDescription='SIGN IN log in ']")
2. driver.FindElement(By.XPath("//android.widget.Button[@content-desc='SIGN IN log in ']")).Click();
3. driver.FindElement(By.Name('SIGN IN log in ')).Click();
4. driver.FindElement(By.Xpath(//*[@Class='android.view.View' OR @content-desc='SIGN IN log in '])).Click();

![Annotation](https://user-images.githubusercontent.com/54312560/69935199-2a2a0d80-14fa-11ea-8b5e-b500165e6462.jpg)

**Comment by mykola-mokhnach** [comment]
Kindly use Appium Forum to ask questions.

Closed as not an issue
