### ISSUE TITLE
Appium Inspector Showing Different Element Attribute Values in Emulator and Real Device

### ISSUE THREAD

**Issue by kariasbolster** [appium/appium#13671]
## The problem

Hi, I am using appium-desktop and i have an issue with the selector. It is giving me different element attribute values in emulator and real device.

## Environment

* Appium version (or git revision) that exhibits the issue: Version 1.15.1 
* Desktop OS/version used to run Appium: MacOs Catalina 10.15.1
* Mobile platform/version under test: Android 8.1
* Real device or emulator/simulator: Both
* Appium CLI or Appium.app|exe: Appium.app

## Details

I am using the appium inspector so that I can get the attribute values i will be using in my test. However, when I ran the test in the real device it fails. Upon investigation, it turns out that the element attribute values in emulator is not the same in real device.

**Comment by mykola-mokhnach** [comment]
These attributes are returned by UIAutomator itself. We cannot do nothing from Appium side to change this behaviour

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
