### ISSUE TITLE
How to test android application with google v8 engine? 

### ISSUE THREAD

**Issue by yuzhijun** [appium/appium#13678]
## The problem

My android application embeded with v8 engine, I want to test app through v8 inspector which provided by google[https://github.com/v8/v8/tree/master/src/inspector], but found issues ChromeDriver seems not work well with v8 inspector，do you have any recommendation?    

## Details
 desired_caps = {
        "platformName": "Android",
        "platformVersion": "7.1.1",
        "udid": "19897078",
        "automationName": "UiAutomator2",
        "deviceName": "Smartisan OD103",
        "newCommandTimeout": 10000,
        "appWaitPackage":"com.bilibili.lib.fasthybrid.example",
        "appWaitActivity":"com.bilibili.lib.fasthybrid.example.MainActivity",
        "unicodeKeyboard":True,
        "resetKeyboard": True,
        "autoGrantPermissions": True,
        "noReset": True,
        "showChromedriverLog": True,
        "recreateChromeDriverSessions":False,
        "chromeOptions":{
            "androidPackage":"com.bilibili.lib.fasthybrid.example", 
            "androidProcess":"com.bilibili.lib.fasthybrid.example:web"
        }
    }

**Comment by yuzhijun** [comment]
Appium v1.16.0-beta.1
chromeDriver 74.0.3729.6

======================================================================
ERROR: test_a_utFrame (__main__.AndroidTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "sample-code/python/test/android_main.py", line 106, in test_a_utFrame
    self.driver.switch_to.context(item)
  File "/usr/local/lib/python3.7/site-packages/appium/webdriver/switch_to.py", line 30, in context
    self._driver.execute(MobileCommand.SWITCH_TO_CONTEXT, {'name': context_name})
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/appium/webdriver/errorhandler.py", line 29, in check_response
    raise wde
  File "/usr/local/lib/python3.7/site-packages/appium/webdriver/errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: A new session could not be created. Details: session not created
from javascript error: HTMLAllCollection is not defined
  (Session info: =)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Mac OS X 10.14.4 x86_64)

**Comment by mykola-mokhnach** [comment]
I would assume such functionality is just not supported and has never been supported. Try asking at chromedriver forum

**Comment by yuzhijun** [comment]
> I would assume such functionality is just not supported and has never been supported. Try asking at chromedriver forum

Now, I modified v8inspector resources  in order to cooperate with chromedriver, but following with below issues，do you have any idea？

[HTTP] <-- GET /wd/hub/session/38a783cb-c3aa-4fcf-b5ee-399e86d24a7e/title - - ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/38a783cb-c3aa-4fcf-b5ee-399e86d24a7e/title
[HTTP] {}
[W3C (38a783cb)] Driver proxy active, passing request on via HTTP proxy
[WD Proxy] Got an unexpected response with status undefined: {"code":"ESOCKETTIMEDOUT","connect":false}
[debug] [WD Proxy] Matched '/wd/hub/session/38a783cb-c3aa-4fcf-b5ee-399e86d24a7e/title' to command name 'title'
[debug] [WD Proxy] Proxying [GET /wd/hub/session/38a783cb-c3aa-4fcf-b5ee-399e86d24a7e/title] to [GET http://127.0.0.1:8000/wd/hub/session/cc8b33ff5c0818a9c89b352d7478ad2a/title] with body: {}
[debug] [W3C (38a783cb)] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT
[debug] [W3C (38a783cb)]     at doJwpProxy (/Users/bilibili/Desktop/appium/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:490:13)
[Chromedriver] [STDERR] [1575461759.320][SEVERE]: Timed out receiving message from renderer: 300.000
[Chromedriver] [STDERR] [1575461759.320][INFO]: Timed out. Stopping navigation...
[Chromedriver] [STDERR] [1575461759.320][DEBUG]: DevTools WebSocket Command: Page.stopLoading (id=12) 1 {
[Chromedriver] [STDERR] }
[Chromedriver] [STDERR] [1575461759.326][DEBUG]: DevTools WebSocket Response: Page.stopLoading (id=12) 1 {"code":-32000,"message":"Protocol command not supported."}
[Chromedriver] [STDERR] [1575461759.327][DEBUG]: DevTools WebSocket Command: Runtime.evaluate (id=13) 1 {
[Chromedriver] [STDERR]    "expression": "1"
[Chromedriver] [STDERR] }
[Chromedriver] [STDERR] [1575461759.327][SEVERE]: Timed out receiving message from renderer: -0.007
[Chromedriver] [STDERR] [1575461759.327][INFO]: Done waiting for pending navigations. Status: timeout
[Chromedriver] [STDERR] [1575461759.327][INFO]: [cc8b33ff5c0818a9c89b352d7478ad2a] RESPONSE GetTitle ERROR timeout

**Comment by yuzhijun** [comment]
Allow me to provide additional details：

{"value":{"error":"unknown command","message":"unknown command: unknown command: session/01a60063337a57faf949c003c109bdf5/title%5D","stacktrace":"0   chromedriver                        0x000000010e528309 chromedriver + 3748617\n1   chromedriver                        0x000000010e4bc943 chromedriver + 3307843\n2   chromedriver                        0x000000010e24c44f chromedriver + 750671\n3   chromedriver                        0x000000010e1d3406 chromedriver + 254982\n4   chromedriver                        0x000000010e1d3097 chromedriver + 254103\n5   chromedriver                        0x000000010e19ad79 chromedriver + 23929\n6   chromedriver                        0x000000010e4eb3ef chromedriver + 3498991\n7   chromedriver                        0x000000010e4f7fed chromedriver + 3551213\n8   chromedriver                        0x000000010e4f7d78 chromedriver + 3550584\n9   chromedriver                        0x000000010e4ca499 chromedriver + 3363993\n10  chromedriver                        0x000000010e4f8848 chromedriver + 3553352\n11  chromedriver                        0x000000010e4deea7 chromedriver + 3448487\n12  chromedriver                        0x000000010e1985e0 chromedriver + 13792\n13  libdyld.dylib                       0x00007fff792a83d5 start + 1\n"}}

**Comment by algu1984** [comment]
@yuzhijun Did you managed to get it work?
