### ISSUE TITLE
UiSelector is depricated

### ISSUE THREAD

**Issue by lokoArt** [appium/appium#13670]
## The problem

UiSelector is deprecated and the package has been moved to AndroidX.  More info here https://developer.android.com/reference/android/support/test/uiautomator/UiSelector

Will Appium team upgrade to the new SDK? When should we expect this?

**Comment by KazuCocoa** [comment]
Do you mean https://github.com/appium/appium-uiautomator2-server/search?q=UiSelector&unscoped_q=UiSelector ?


```
import androidx.test.uiautomator.UiSelector;
```

Newer UIA2 already has androidx.
Espresso also has androidx https://github.com/appium/appium-espresso-driver/blob/master/espresso-server/app/build.gradle

**Comment by lokoArt** [comment]
@KazuCocoa  oh really, That's cool!
