### ISSUE TITLE
The HTTP request to the remote WebDriver server for URL http://127.0.0.1:4723/wd/hub/session timed out after 60 seconds.   ----> System.Net.WebException : The operation has timed out.

### ISSUE THREAD

**Issue by Fabinho12** [appium/appium#13673]
The problem

Hi, I installed the latest version of Appium (1.15.1), but I am having trouble connecting to the server. The only version I have no problem with is 1.13.0

Environment

* Appium version (or git revision) that exhibits the issue: Version 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): 1.13.0
* Desktop OS/version used to run Appium: Windows 10
* Mobile platform/version under test: Android 8.1
* Real device or emulator/simulator: both

Details

If necessary, describe the problem you have been experiencing in more detail.

Link to Appium logs

https://gist.github.com/Fabinho12/e7bcad0063e0a2d2ca747ccafa84f4f0

**Comment by mykola-mokhnach** [comment]
> [warn] [35m[WD Proxy][39m Got an unexpected response: <HTML><TITLE>503 Service Unavailable</TITLE>

It looks like there is some proxy on your machine, which is intercepting requests to uiautomator server. Have you tried to run the suite on some other machine?

**Comment by mykola-mokhnach** [comment]
> [debug] [35m[ADB][39m Creating ADB subprocess with args: ["-P",5037,"-s","0031036166","shell","am","instrument","-w","io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner"][debug] [35m[Instrumentation][39m INSTRUMENTATION_RESULT: shortMsg=Process crashed.

I can also observe that instrumentation process crashed. Perhaps, logcat output contains more details

**Comment by Fabinho12** [comment]
The proxy problem only happens in versions above 1.13.0, has there been any change in the way you communicate with the server?

**Comment by mykola-mokhnach** [comment]
There were many changes

**Comment by mykola-mokhnach** [comment]
Closed as not an issue. Without any additional information there is nothing more to be done on this report.
