### ISSUE TITLE
io.appium.uiautomator2.server is killed because it occupies high memory in Android OS 5.1.1 device. Which results in Error: socket hang up.

### ISSUE THREAD

**Issue by rajavinodh** [appium/appium#13680]
## The problem

I am trying to run my tests in OS 5 device. After some time in the execution app shuts down abruptly and I see an error from Appium logs saying "Error: socket hang up". 

And from ADB logs I see io.appium.uiautomator2.server and io.appium.setting is killed due to usage of high memory.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.0 v
* Desktop OS/version used to run Appium: MacOS Mojave (10.14.1 v)
* Node.js version (unless using Appium.app|exe): v11.8.0
* Mobile platform/version under test: Android/5.1.1 - API 22
* Mobile Manufacturer: OPPO - A37fw
* RAM of the device: 2GB 
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

The same setup works for all other OS versions like 6.0.1, 7.1.1, 8 and 9. Also one of the devices is having 2GB RAM in which the execution is smooth. But this happens very often in OS 5 also sometimes happens when the app itself is launched. 

If the device is rebooted/restarted the execution goes smooth for a while say like 15-20 tests are executed before same failure happens. 

## Link to Appium logs

Below is the gist link for both Appium and ADB logs:
https://gist.github.com/rajavinodh/c44f58300fc2469472515698bd52f2a9

**Comment by mykola-mokhnach** [comment]
Unfortunately we cannot help much there without the process memory dumps

**Comment by rajavinodh** [comment]
@mykola-mokhnach Please find the following link for memory dump of io.appium.uiautomator2.server : https://gist.github.com/rajavinodh/6f0fc56805eb6a3e10aa08318db6b56a

**Comment by mykola-mokhnach** [comment]
Can you please take the memory snapshot according to [this](https://dzone.com/articles/how-to-capture-heap-dump-from-android-app) tutorial?

**Comment by rajavinodh** [comment]
@mykola-mokhnach Following is the link for hprof file and also a snapshot is attached.
https://drive.google.com/open?id=17VT_eJZSe2TfR00OuDzwxkG9U9_ES-Gb

<img width="1679" alt="uiautomator_snapshot" src="https://user-images.githubusercontent.com/47104114/70142199-b71dc400-16be-11ea-81ca-10b2ced1309e.png">

**Comment by mykola-mokhnach** [comment]
Was the snapshot taken when memory usage is too high or at some random time stamp? In order to make it useful it should be taken when uia2 server process is close to be terminated

**Comment by rajavinodh** [comment]
@mykola-mokhnach It is hard to predict the point of termination, Let me record a video and share it with you.

**Comment by mykola-mokhnach** [comment]
> It is hard to predict the point of termination

This is not needed. Just make sure the app takes enough memory before taking the snapshot (the log shows it is killed when memory usage is at 54 MB, so you can try to get the snapshot if the current usage is close to 40-50 MB)

**Comment by mykola-mokhnach** [comment]
I would be happy to reopen the issue as soon as the proper heap snapshot is available

**Comment by pranay2611** [comment]
Facing same issue with OS5 emulator

> Environment

Appium version (or git revision) that exhibits the issue: 1.19.0 v
Mobile platform/version under test: Android/5.1.1 - API 22
Real device or emulator/simulator: simulator


io.appium.uiautomator2.server is crashing with below error

`    --------- beginning of crash
11-20 18:09:23.386 31332-31372/io.appium.uiautomator2.server A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 31372 (nioEventLoopGro)
11-20 18:09:23.658 492-492/? E/memtrack: Couldn't load memtrack module (No such file or directory)
11-20 18:09:23.658 492-492/? E/android.os.Debug: failed to load memtrack module: -2
11-20 18:09:23.824 1549-1811/system_process E/ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ id=25, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]
11-20 18:09:23.975 1184-20273/? E/audio_hw_generic: Error opening input stream format 1, channel_mask 0010, sample_rate 16000
11-20 18:09:24.055 2485-25300/com.google.android.gms.persistent E/SQLiteLog: (2067) abort at 31 in [INSERT INTO pending_ops(source,tag,requires_charging,target_package,source_version,required_network_type,flex_time,target_class,runtime,retry_strategy,last_runtime,period,task_type,job_id,user_
11-20 18:09:24.056 2485-25300/com.google.android.gms.persistent E/SQLiteDatabase: Error inserting source=16 tag=Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG requires_charging=0 target_package=com.google.android.gms source_version=200414000 required_network_type=0 flex_time=0 target_class=com.google.android.gms.measurement.PackageMeasurementTaskService runtime=1605875963979 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}} last_runtime=0 period=2000 task_type=0 job_id=-1 user_id=0
    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: pending_ops.tag, pending_ops.target_class, pending_ops.target_package, pending_ops.user_id (code 2067)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1471)
        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1341)
        at aoht.a(:com.google.android.gms@200414013@20.04.14 (020700-294335909):76)
        at aohi.b(:com.google.android.gms@200414013@20.04.14 (020700-294335909):54)
        at aohi.a(:com.google.android.gms@200414013@20.04.14 (020700-294335909):124)
        at aoef.run(:com.google.android.gms@200414013@20.04.14 (020700-294335909):16)
        at sgc.b(:com.google.android.gms@200414013@20.04.14 (020700-294335909):14)
        at sgc.run(:com.google.android.gms@200414013@20.04.14 (020700-294335909):9)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at slv.run(:com.google.android.gms@200414013@20.04.14 (020700-294335909):0)
        at java.lang.Thread.run(Thread.java:818)`
