### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by RoyalFlushever** [appium/appium#13689]
## The problem

http://appium.io/docs/en/about-appium/getting-started/?lang=en#running-your-first-test

I am running this on Mac. I encountered webdriverio option issue.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 1.15.1
* Node.js version (unless using Appium.app|exe): 1.15.1
* Npm or Yarn package manager: Npm
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: real device samsung galaxy s6 
* Appium CLI or Appium.app|exe: Appium CLI

## Details

A week ago, I successfully run the sample code in the latest appium version.
However, today I created the new repo, write the sample code again and run, I encountered webdriverio issue.

I stuck here for several hours. Only difference is webdriverio version.
Appium version is same.

## Link to Appium logs
https://gist.github.com/RoyalFlushever/b0b6f93171a82e08f49f7cb2fc90ebea#file-appium_started-log

## Code To Reproduce Issue [ Good To Have ]

const wdio = require("webdriverio")
const assert = require("assert");

const opts = {
  port: 4723,
  capabilities: {
    platformName: "Android",
    platformVersion: "7.0",
    deviceName: "05157df5e162600b",
    // app: "/Volumes/Data/Workspace/appium/appium-master/sample-code/apps/ApiDemos-debug.apk",
    appPackage: "io.appium.android.apis",
    appActivity: ".view.TextFields",
    automationName: "UiAutomator2"
  }
}

async function main() {
  const client = await wdio.remote(opts);

  const field = await client.$("android.widget.EditText");
  await field.setValue("Hello World!");
  const value = await field.getText();
  assert.equal(value, "Hello World!");

  await client.deleteSession();
}

main();

**Comment by mykola-mokhnach** [comment]
I don't observe any Appium issues in the attached logs. To me it looks like an issue in the client code

**Comment by RoyalFlushever** [comment]
@mykola-mokhnach 
Could you run the http://appium.io/docs/en/about-appium/getting-started/?lang=en#running-your-first-test with latest version webdriverio (appium client) on your side?

I want to make sure if the Appium sample code in the offical site works with the latest appium client.

FYI, webdriverio v5.16.12 was released 12 hrs ago.

Thanks

**Comment by RoyalFlushever** [comment]
I fixed the issue by installing previous webdriverio @5.16.10.
