### ISSUE TITLE
'RoutingHTTPServer/RoutingConnection.h' file not found 

### ISSUE THREAD

**Issue by AdityaRawat23** [appium/appium#13687]
## The problem

'RoutingHTTPServer/RoutingConnection.h' file not found.

I have gone through these steps:-

mkdir -p Resources/WebDriverAgent.bundle
./Scripts/bootstrap.sh -d

On executing command:-  ./Scripts/bootstrap.sh -d
Error Description:-

`Vikass-MacBook-Pro:appium-webdriveragent himanshug$ ./Scripts/bootstrap.sh -d`

`Fetching dependencies
*** Checking out CocoaAsyncSocket at "7.6.3"
*** Checking out RoutingHTTPServer at "v1.0.2"
*** Checking out YYCache at "1.1.0"
*** xcodebuild output can be found in /var/folders/5z/0p24p7t93qg9qm1kfqsksm6m0000gp/T/carthage-xcodebuild.09o1Z5.log
*** Downloading CocoaAsyncSocket.framework binary at "Version 7.6.3"
*** Building scheme "RoutingHTTPServer tvOS" in RoutingHTTPServer.xcodeproj
Failed to write to /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Build/tvOS/RoutingHTTPServer.framework: Error Domain=NSCocoaErrorDomain Code=260 "The file “RoutingHTTPServer.framework” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Checkouts/RoutingHTTPServer/build/ArchiveIntermediates/RoutingHTTPServer%20tvOS/BuildProductsPath/Release-appletvos/RoutingHTTPServer.framework, NSFilePath=/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Checkouts/RoutingHTTPServer/build/ArchiveIntermediates/RoutingHTTPServer tvOS/BuildProductsPath/Release-appletvos/RoutingHTTPServer.framework, NSUnderlyingError=0x7f8bbd53a800 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}`
`Vikass-MacBook-Pro:appium-webdriveragent himanshug$ pwd
/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent`

Also I tried the following solution :- [https://github.com/appium/appium/issues/11982](url)

carthage bootstrap --no-use-binaries
cp Cartfile.resolved Carthage
./Scripts./bootstrap.sh -d

The first command of the above gives this error:

`Vikass-MacBook-Pro:appium-webdriveragent himanshug$ pwd
/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent`

`Vikass-MacBook-Pro:appium-webdriveragent himanshug$ carthage bootstrap --no-use-binaries`

`*** Checking out RoutingHTTPServer at "v1.0.2"
*** Checking out CocoaAsyncSocket at "7.6.3"
*** Checking out YYCache at "1.1.0"
*** xcodebuild output can be found in /var/folders/5z/0p24p7t93qg9qm1kfqsksm6m0000gp/T/carthage-xcodebuild.NCajDO.log
*** Building scheme "Mac Framework" in CocoaAsyncSocket.xcodeproj
Failed to write to /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Build/Mac/CocoaAsyncSocket.framework: Error Domain=NSCocoaErrorDomain Code=260 "The file “CocoaAsyncSocket.framework” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Checkouts/CocoaAsyncSocket/build/ArchiveIntermediates/Mac%20Framework/BuildProductsPath/Release/CocoaAsyncSocket.framework, NSFilePath=/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Checkouts/CocoaAsyncSocket/build/ArchiveIntermediates/Mac Framework/BuildProductsPath/Release/CocoaAsyncSocket.framework, NSUnderlyingError=0x7f80de660a80 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}`

How do i get the RoutingHTTPServer/RoutingConnection.h file to build my webdriveragent project.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Desktop OS/version used to run Appium: macOS high sierra, version 10.13.4
* Node.js version (unless using Appium.app|exe): node v9.6.1
* Npm or Yarn package manager: npm version 6.13.1
* Mobile platform/version under test: iphone 6
* Real device 
* Appium CLI or Appium.app|exe: Appium installed through npm

**Comment by mykola-mokhnach** [comment]
Make sure Carthage binary is up to date and cleanup the leftovers before downloading dependencies

**Comment by AdityaRawat23** [comment]
brew upgraded:-

`Vikass-MacBook-Pro:appium-webdriveragent himanshug$ brew upgrade carthage
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
wireshark

Warning: carthage 0.34.0 already installed`

Used this command to clean carthage:-
rm -rf ~/Library/Caches/org.carthage.CarthageKit

Still getting error:
Vikass-MacBook-Pro:appium-webdriveragent himanshug$ ./Scripts/bootstrap.sh -d
Fetching dependencies
*** Checking out YYCache at "1.1.0"
*** Checking out RoutingHTTPServer at "v1.0.2"
*** Checking out CocoaAsyncSocket at "7.6.3"
*** Cloning CocoaAsyncSocket
*** Cloning RoutingHTTPServer
*** Cloning YYCache
*** xcodebuild output can be found in /var/folders/5z/0p24p7t93qg9qm1kfqsksm6m0000gp/T/carthage-xcodebuild.XHvTr9.log
*** Downloading CocoaAsyncSocket.framework binary at "Version 7.6.3"
*** Building scheme "RoutingHTTPServer tvOS" in RoutingHTTPServer.xcodeproj
Failed to write to /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Build/tvOS/RoutingHTTPServer.framework: Error Domain=NSCocoaErrorDomain Code=260 "The file “RoutingHTTPServer.framework” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Checkouts/RoutingHTTPServer/build/ArchiveIntermediates/RoutingHTTPServer%20tvOS/BuildProductsPath/Release-appletvos/RoutingHTTPServer.framework, NSFilePath=/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Checkouts/RoutingHTTPServer/build/ArchiveIntermediates/RoutingHTTPServer tvOS/BuildProductsPath/Release-appletvos/RoutingHTTPServer.framework, NSUnderlyingError=0x7fe7b865f400 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}


am i missing something .

**Comment by mykola-mokhnach** [comment]
Does it work if you comment out [this](https://github.com/appium/WebDriverAgent/blob/48adb77808ed5fe4108ad8ce77bc05b8a6689047/Scripts/bootstrap.sh#L55) line is the bootstrap.sh script?

**Comment by KazuCocoa** [comment]
What about building the wda in `appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent`? The path's one is outdated since the checked out versions were old.

**Comment by AdityaRawat23** [comment]
`if echo "$runtimes_with_devices" | grep -q tvOS; then
      echo "commenting out next line"
#platforms+=(tvOS)
    else
      echo "tvOS platform will not be included into Carthage bootstrap, because no Simulator devices have been created for it"`

error description:


`Vikass-MacBook-Pro:appium-webdriveragent himanshug$ ./Scripts/bootstrap.sh -d
Fetching dependencies
commenting out next line
*** Checking out YYCache at "1.1.0"
*** Checking out CocoaAsyncSocket at "7.6.3"
*** Checking out RoutingHTTPServer at "v1.0.2"
*** xcodebuild output can be found in /var/folders/5z/0p24p7t93qg9qm1kfqsksm6m0000gp/T/carthage-xcodebuild.2Z8Nd3.log
*** Downloading CocoaAsyncSocket.framework binary at "Version 7.6.3"
*** Building scheme "RoutingHTTPServer iOS" in RoutingHTTPServer.xcodeproj
Failed to write to /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Build/iOS/RoutingHTTPServer.framework: Error Domain=NSCocoaErrorDomain Code=260 "The file “RoutingHTTPServer.framework” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Checkouts/RoutingHTTPServer/build/ArchiveIntermediates/RoutingHTTPServer%20iOS/BuildProductsPath/Release-iphoneos/RoutingHTTPServer.framework, NSFilePath=/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Checkouts/RoutingHTTPServer/build/ArchiveIntermediates/RoutingHTTPServer iOS/BuildProductsPath/Release-iphoneos/RoutingHTTPServer.framework, NSUnderlyingError=0x7faff0c27920 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}`

**Comment by AdityaRawat23** [comment]
> What about building the wda in `appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent`? The path's one is outdated since the checked out versions were old.

Don't have appium-webdriveragent at the mentioned location.

![image](https://user-images.githubusercontent.com/12389734/70223938-6798d000-1772-11ea-8231-17895ca0fe06.png)

**Comment by KazuCocoa** [comment]
oh, it was my wrong.

Was there any error messages in `/var/folders/5z/0p24p7t93qg9qm1kfqsksm6m0000gp/T/carthage-xcodebuild.2Z8Nd3.log`?

**Comment by mykola-mokhnach** [comment]
> Don't have appium-webdriveragent at the mentioned location.

How about `appium/node_modules/appium-webdriveragent`?

**Comment by AdityaRawat23** [comment]
> How about appium/node_modules/appium-webdriveragent?
Yes I am using the appium/node_modules/appium-webdriveragent .

**Comment by AdityaRawat23** [comment]
Tried with appium v1.12.0: I was able to install the dependencies :- RoutingHTTPServer, YYCache, CocoaAsyncSocket.
Tried with appium v1.13.0: 

`Vikass-MacBook-Pro:WebDriverAgent himanshug$ ./Scripts/bootstrap.sh -d
Fetching dependencies
*** Checking out RoutingHTTPServer at "v1.0.2"
*** Checking out YYCache at "1.1.0"
*** Checking out CocoaAsyncSocket at "7.6.3"
*** xcodebuild output can be found in /var/folders/5z/0p24p7t93qg9qm1kfqsksm6m0000gp/T/carthage-xcodebuild.5yLzcD.log
*** Downloading CocoaAsyncSocket.framework binary at "Version 7.6.3"
*** Building scheme "RoutingHTTPServer tvOS" in RoutingHTTPServer.xcodeproj
Failed to write to /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/tvOS/RoutingHTTPServer.framework: Error Domain=NSCocoaErrorDomain Code=260 "The file “RoutingHTTPServer.framework” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer/build/ArchiveIntermediates/RoutingHTTPServer%20tvOS/BuildProductsPath/Release-appletvos/RoutingHTTPServer.framework, NSFilePath=/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer/build/ArchiveIntermediates/RoutingHTTPServer tvOS/BuildProductsPath/Release-appletvos/RoutingHTTPServer.framework, NSUnderlyingError=0x7f9a4bc54ff0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
Vikass-MacBook-Pro:WebDriverAgent himanshug$ `

Tried with appium v1.14.0: Similar to v1.13.0

**Comment by AdityaRawat23** [comment]
Failed to write to /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/tvOS/RoutingHTTPServer.framework: Error Domain=NSCocoaErrorDomain Code=260 "The file “RoutingHTTPServer.framework” couldn’t be opened because there is no such file."

I browsed through the directory :- 

![image](https://user-images.githubusercontent.com/12389734/70770787-bfe45900-1d94-11ea-884d-6bba62a88e10.png)

**Comment by KazuCocoa** [comment]
I remember.
Newer carthage had the logic to check iOS simulators including tvOS. (When I read their code before, I could not find the way to control it from outside of carthage)

If you did not have tvOS simulator device, how about creating it and run again?

**Comment by AdityaRawat23** [comment]
![image](https://user-images.githubusercontent.com/12389734/70771601-b1e40780-1d97-11ea-9976-2aafdaf39f9a.png)

@KazuCocoa  I do have tvOS simulator devices. If this is what you meant.

**Comment by KazuCocoa** [comment]
Yes, it is.
Removing carthage cache also might help

**Comment by AdityaRawat23** [comment]
> Yes, it is.
> Removing carthage cache also might help

 Already tried this way

**Comment by AdityaRawat23** [comment]
@KazuCocoa @mykola-mokhnach  can we use older wda on latest appium?
example : I am able to build my wda for appium 1.12.1, so can i copy that wda onto the latest appium folder  path.

**Comment by mykola-mokhnach** [comment]
No, older WDA versions won't work with both new xcuitest drivers and new iOS releases

**Comment by AdityaRawat23** [comment]
Is there a way to manually provide the missing dependencies?
i.e.: can i provide RoutingHTTPServer and YYCache manually to appium-webdriveragent?

**Comment by KazuCocoa** [comment]
You can get below repositories and build them.

- https://github.com/appium/RoutingHTTPServer
- https://github.com/appium/YYCache

Then, you can find `.framework` binaries in `Developer/Xcode/DerivedData/Xxxxx/Build/Products`.

btw, if your environment has a write permission issue, `npm install -g appium --unsafe-perm=true --allow-root` will help after uninstalling appium, I remember.

**Comment by mykola-mokhnach** [comment]
Closed as not an appium issue.

**Comment by markrickert** [comment]
A coworker encountered this issue (only tangentially related to appium) and we got it working properly by opening the `WebDriverAgent.xcodeproj` file in `~/.nvm/versions/node/v13.12.0/lib/node_modules/appium/node_modules/appium-webdriveragent` and cleaning the build folder (`CMD`+`K`) and then building (`CMD`+`B`). Delete the cache file here: `~/Library/Caches/org.carthage.CarthageKit` then try the `bootstrap` command again.

Still have no clue why his machine didn't work but mine did. This was a tough one. Good luck!

**Comment by rajshah** [comment]
> A coworker encountered this issue (only tangentially related to appium) and we got it working properly by opening the `WebDriverAgent.xcodeproj` file in `~/.nvm/versions/node/v13.12.0/lib/node_modules/appium/node_modules/appium-webdriveragent` and cleaning the build folder (`CMD`+`K`) and then building (`CMD`+`B`). Delete the cache file here: `~/Library/Caches/org.carthage.CarthageKit` then try the `bootstrap` command again.
> 
> Still have no clue why his machine didn't work but mine did. This was a tough one. Good luck!

still banging my head! :(

**Comment by rajshah** [comment]
Finally worked for me after upgrading appium to 1.18.3.

Environment - 
Xcode 12.2
Appium 1.18.3
Node 12.4.0
npm 6.9.0
CLI ASDF
