### ISSUE TITLE
no such file or directory on running ./Scripts/bootstrap.sh -d

### ISSUE THREAD

**Issue by rajkumar-cp** [appium/appium#13682]
## The problem

After appium installation i want to run the below 2 commands in this folder
 /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent
1) $ mkdir -p Resources/WebDriverAgent.bundle
2) $ ./Scripts/bootstrap.sh -d

After running command 2 i am recieving this below error in the console
zsh: no such file or directory ./Scripts/bootstrap.sh

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 10.15.1 (mac)
* Node.js version (unless using Appium.app|exe): 13.2.0
* Npm or Yarn package manager: 6.13.1
* Mobile platform/version under test: 13.0
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Installed through command line as well as app file was also installed.

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by rajkumar-cp** [comment]
This issue can be closed as i was trying to give the commands from wrong directory.

**Comment by anushkmittal** [comment]
@rajkumar-cp what was the right directory for you?

**Comment by tcthiagocezar** [comment]
@rajkumar-cp was right directory you?

**Comment by koralaa** [comment]
I am getting the same error as described in here.
cd /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent
mkdir -p Resources/WebDriverAgent.bundle

qa.testing@QAs-Mac-mini appium-webdriveragent % ./Scripts/bootstrap.sh -d
zsh: no such file or directory: ./Scripts/bootstrap.sh

Please help
