### ISSUE TITLE
 Original error: Unknown device or simulator UDID error 

### ISSUE THREAD

**Issue by rajkumar-cp** [appium/appium#13686]
## The problem

Not able to launch simulators via appium.

## Environment

Appium version (or git revision) that exhibits the issue: 1.15.1
Last Appium version that did not exhibit the issue (if applicable):
Desktop OS/version used to run Appium: 10.15.1 (mac)
Node.js version (unless using Appium.app|exe): 13.2.0
Npm or Yarn package manager: 6.13.1
Mobile platform/version under test: 13.0
Real device or emulator/simulator: Simulator
Appium CLI or Appium.app|exe: Installed through command line as well as app file was also installed.

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/rajkumar-cp/55c46aecce2eb82b3a41a66286be41f1

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
> [debug] [XCUITest] Available devices: [error] [XCUITest] Error: Unknown device or simulator UDID: '2a8979ba8f0f45dc8a6976abfa85e4b4'

For a Simulator it is enough to set correct device name and platform version. uuid will be detected automatically

**Comment by rajkumar-cp** [comment]
@mykola-mokhnach 

I have removed that capability and it seems to be working fine for iPhone but for iPad it fails with the below error. Could you please take a look and advise

https://gist.github.com/rajkumar-cp/832263801f265897a4599de089b8f6bf

**Comment by mykola-mokhnach** [comment]
The error is expected. There is no device named "iPad Pro" in the list above (the content in parentheses is also counted as the valid part of the device name)

Closed as not an issue
