### ISSUE TITLE
[iOS] /attribute/value always "0"

### ISSUE THREAD

**Issue by margasan** [appium/appium#13691]
## The problem

```
$ curl 127.0.0.1:8107/source
...
<XCUIElementTypeSwitch
     type="XCUIElementTypeSwitch" enabled="true" visible="true" x="327" y="237" width="51" height="32" name="SIM Wi-Fi Prompt Enabled" label="SIM Wi-Fi Prompt Enabled" value="1">
</XCUIElementTypeSwitch>
...

```
But:
```
$ curl 127.0.0.1:4738/wd/hub/session/45a76eb4-5442-4f17-a784-855d903b932d/element/A3000000-0000-0000-140E-000000000000/attribute/value
{"value":"0"}
```

## Environment

- appium 1.15.1
- node v13.2.0
- npm 6.13.2
- MacOS 10.14.6 (18G95)
- iOS 12.3
- xCode 10.2.1

## Code To Reproduce Issue [ Good To Have ]
Try to get /attribute/value of any XCUIElementTypeSwitch element

## Notes
```
func testElement()  {
        let app = XCUIApplication(bundleIdentifier: "com.test.dev")
        app.activate()
        
        sleep(1)

        let wifiSwitch = app.switches["SIM Wi-Fi Prompt Enabled"]
        
        XCTAssert(wifiSwitch.exists)

        let currentValue = wifiSwitch.value as! String
        print("_______________Value is: " + currentValue + " ________________")
    }
}
```

   ```
 t =     0.00s Start Test at 2019-12-06 16:39:22.668
    t =     0.02s Set Up
    t =     3.56s Open com.test.dev
    t =     3.58s     Activate com.test.dev
    t =     3.68s         Wait for com.test.dev to idle
    t =     4.72s Checking existence of `"SIM Wi-Fi Prompt Enabled" Switch`
    t =     4.73s     Snapshot accessibility hierarchy for app with pid 3604
    t =     4.94s     Find: Descendants matching type Switch
    t =     4.95s     Find: Elements matching predicate '"SIM Wi-Fi Prompt Enabled" IN identifiers'
    t =     4.95s Find the "SIM Wi-Fi Prompt Enabled" Switch
    t =     4.95s     Snapshot accessibility hierarchy for app with pid 3604
    t =     5.13s     Find: Descendants matching type Switch
    t =     5.13s     Find: Elements matching predicate '"SIM Wi-Fi Prompt Enabled" IN identifiers'
_______________Value is: 1 ________________
    t =     5.13s Tear Down
tearDown
```
![Screen Shot 2019-12-06 at 3 30 55 PM](https://user-images.githubusercontent.com/18184847/70325082-3687d080-1842-11ea-813b-b8245237d22f.png)

**Comment by mykola-mokhnach** [comment]
The value is returned by XCTest, so there is not much we can do there.

Although appium@beta got the support of `isSelected` attribute, which could be in use there. Also, you could try to find the target element in scope of its window rather than the top page root - I was observing the situation when XcTest was returning different attributes based on what the search root was

**Comment by margasan** [comment]
@mykola-mokhnach if we use native test script on Swift which utilizes XCTest we get correct attribute value (see Notes in the description of the issue).

**Comment by mykola-mokhnach** [comment]
I don't observe any specific issues in the WDA [code](https://github.com/appium/WebDriverAgent/blob/48adb77808ed5fe4108ad8ce77bc05b8a6689047/WebDriverAgentLib/Categories/XCUIElement%2BFBWebDriverAttributes.m#L117). Please let us know if you can find one

**Comment by margasan** [comment]
The issue doesn't appear in case of using appium 1.14.2

**Comment by mykola-mokhnach** [comment]
I don't think I would be able to help much without having the actual application to test on (Simulator build)

**Comment by HlebHalkouski** [comment]
@mykola-mokhnach I think this issue are actual for XCUIElementTypeSwitch in any applications. 
Maybe we can try to parse value as string [here](https://github.com/appium/WebDriverAgent/blob/48adb77808ed5fe4108ad8ce77bc05b8a6689047/WebDriverAgentLib/Categories/XCUIElement%2BFBWebDriverAttributes.m#L117) and check returned value? Maybe `value = @([value boolValue]);` return `nil` and 'FBTransferEmptyStringToNil' set value as 0?
That do you think? Or maybe another suggestions?

**Comment by mykola-mokhnach** [comment]
I did try to reproduce the issue with our catalog application and the returned value was ok

**Comment by KazuCocoa** [comment]
I tried below section. Then, I could get `"0"` or `"1"` correctly via `.value`. (And source command)

```
<XCUIElementTypeSwitch type="XCUIElementTypeSwitch" enabled="true" visible="true" x="343" y="149" width="51" height="32" name="AutoFill Passwords" label="AutoFill Passwords" value="1">
```
<img src="https://user-images.githubusercontent.com/5511591/70372977-462e1480-1929-11ea-82b3-ad49bfd0902e.png" width=400>

I tried:

Xcode 11.2 x iOS 13.2 (real device), iOS 13.2 (simulator)
Xcode 10.2.1 x iOS 12.4,  iOS 12.1 (simulators)

Appium 1.15 and 1.16 beta.

I have an iOS 13 real device, so if you can share the app on the store, maybe I can try to check. (I cannot on iOS 12 though)

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing more to do on this issue without having the actual app to test on

**Comment by HlebHalkouski** [comment]
@mykola-mokhnach unfortunately, due to other activities, we postponed this issue. 
Next steps: we want to try reproduce this issue on Appium test app.

**Comment by Cory-Berg** [comment]
> Unfortunately there is nothing more to do on this issue without having the actual app to test on

The same values returned issue exists if you reference the settings app. I am not certain if you can access that within your simulator, but if you have a real device @ iOS 12.1.* you should be able to replicate the issue.

**Comment by friend8628** [comment]
I am facing same issue on iOS 12.1 (real device) Appium 1.15.0 and xcode 11.3
For me it's working fine on iOS 13.0 (real device) Appium 1.15.0 and xcode 11.3

Please someone can take a look in this issue

**Comment by pocoyo-coder** [comment]
This issue persists with appium 1.17.0 and easy to reproduce just open settings app and try to detect toggle switch enabled. the return value will always be 0.

- xcode 11.3.1 

- appium-xcuitest-driver@3.17.0

- appium-webdriveragent@2.7.4

- real devices 

- any IOS 11, 12, 13

**Comment by KazuCocoa** [comment]
hm... 
I cannot reproduce yet with Appium 1.17.0 
The target switch is the same as https://github.com/appium/appium/issues/13691#issuecomment-562839160
(My device was iPhone SE)

```ruby
> e = @@driver.find_elements :name, 'AutoFill Passwords'
> e.each { |e| puts e.value }
AutoFill Passwords
1
AutoFill Passwords
1

## after turn the button off

> e = @@driver.find_elements :name, 'AutoFill Passwords'
> e.each { |e| puts e.value }
AutoFill Passwords
0
AutoFill Passwords
0
```

page source: on
```
<XCUIElementTypeCell type="XCUIElementTypeCell" enabled="true" visible="true" x="0" y="99" width="320" height="49" name="AutoFill Passwords" label="AutoFill Passwords" value="1">
  <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" enabled="true" visible="true" x="15" y="112" width="143" height="23" name="AutoFill Passwords" label="AutoFill Passwords" value="AutoFill Passwords">
  </XCUIElementTypeStaticText>
  <XCUIElementTypeSwitch type="XCUIElementTypeSwitch" enabled="true" visible="true" x="254" y="108" width="51" height="31" name="AutoFill Passwords" label="AutoFill Passwords" value="1">
  </XCUIElementTypeSwitch>
</XCUIElementTypeCell>
```

page source: off

```
<XCUIElementTypeCell type="XCUIElementTypeCell" enabled="true" visible="true" x="0" y="99" width="320" height="49" name="AutoFill Passwords" label="AutoFill Passwords" value="0">
  <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" enabled="true" visible="true" x="15" y="112" width="143" height="23" name="AutoFill Passwords" label="AutoFill Passwords" value="AutoFill Passwords">
  </XCUIElementTypeStaticText>
  <XCUIElementTypeSwitch type="XCUIElementTypeSwitch" enabled="true" visible="true" x="254" y="108" width="51" height="31" name="AutoFill Passwords" label="AutoFill Passwords" value="0">
  </XCUIElementTypeSwitch>
</XCUIElementTypeCell>
```

it is appreciated to create a PR if someone can debug.
https://github.com/appium/appium/issues/13691#issuecomment-562798763 is probably a good entry point.

**Comment by pocoyo-coder** [comment]
I'm running on python with find_element(ios_predicate='"XCUIElementTypeSwitch" in wdType and "Airplane Mode" in wdLabel').get_attribute('value')

I always get 0. this code works perfectly with appium 1.14.0 and xcode 10.2

**Comment by KazuCocoa** [comment]
Thanks, but my device worked well.

```
> e = @driver.find_elements :predicate, '"XCUIElementTypeSwitch" in wdType and "Airplane Mode" in wdLabel'
=> [#<Selenium::WebDriver::Element:0x..fc3fe14eeb2f3e07c id="78010000-0000-0000-9507-000000000000">]
> e.each { |e| puts e.value }
1
=> [#<Selenium::WebDriver::Element:0x..fc3fe14eeb2f3e07c id="78010000-0000-0000-9507-000000000000">]
> e = @driver.find_elements :predicate, '"XCUIElementTypeSwitch" in wdType and "Airplane Mode" in wdLabel'
=> [#<Selenium::WebDriver::Element:0x..fc3fe14eeb2f3e07c id="78010000-0000-0000-9507-000000000000">]
> e.each { |e| puts e.value }
0
=> [#<Selenium::WebDriver::Element:0x..fc3fe14eeb2f3e07c id="78010000-0000-0000-9507-000000000000">]
```

**Comment by pocoyo-coder** [comment]
@KazuCocoa thanks for checking, I seriously don't know then why isn't it working for me.
sorry for asking but what syntax are you using? what is your setup?

**Comment by pocoyo-coder** [comment]
here is my appium log if you see the issue please let me know:

2020-03-26 18:44:51:545 [HTTP] {"using":"-ios predicate string","sessionId":"4aedd606-2ccc-42e8-b7a3-6f92426ca13b","value":"\"XCUIElementTypeSwitch\" in wdType and \"Airplane Mode\" in wdLabel"}
2020-03-26 18:44:51:549 [WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:21778/session/83341759-12D1-46EC-8F43-9152CC7C7E1D/element] with body: {"using":"predicate string","value":"\"XCUIElementTypeSwitch\" in wdType and \"Airplane Mode\" in wdLabel"}
2020-03-26 18:44:52:074 [Xcode]     t =  1030.78s Get all elements bound by accessibility element for: Elements matching predicate '("XCUIElementTypeSwitch" IN wdType AND "Airplane Mode" IN wdLabel) AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0 OR selected == 0)'
2020-03-26 18:44:52:478 [Xcode]     t =  1031.18s     Find: Elements matching predicate '("XCUIElementTypeSwitch" IN wdType AND "Airplane Mode" IN wdLabel) AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0 OR selected == 0)'
2020-03-26 18:44:52:941 [Xcode]     t =  1031.64s     Find: Elements matching predicate '("XCUIElementTypeSwitch" IN wdType AND "Airplane Mode" IN wdLabel) AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0 OR selected == 0)'
2020-03-26 18:44:53:375 [Xcode]     t =  1032.08s Find: Elements matching predicate '("XCUIElementTypeSwitch" IN wdType AND "Airplane Mode" IN wdLabel) AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0 OR selected == 0)'
2020-03-26 18:44:53:407 [WD Proxy] Got response with status 200: {"value":{"ELEMENT":"8B000000-0000-0000-3D01-000000000000","element-6066-11e4-a52e-4f735466cecf":"8B000000-0000-0000-3D01-000000000000"},"sessionId":"83341759-12D1-46EC-8F43-9152CC7C7E1D"}
2020-03-26 18:44:53:412 [HTTP] --> GET /wd/hub/session/4aedd606-2ccc-42e8-b7a3-6f92426ca13b/element/8B000000-0000-0000-3D01-000000000000/attribute/value
2020-03-26 18:44:53:413 [HTTP] {"sessionId":"4aedd606-2ccc-42e8-b7a3-6f92426ca13b","name":"value","id":"8B000000-0000-0000-3D01-000000000000"}
2020-03-26 18:44:53:413 [W3C (4aedd606)] Calling AppiumDriver.getAttribute() with args: ["value","8B000000-0000-0000-3D01-000000000000","4aedd606-2ccc-42e8-b7a3-6f92426ca13b"]
2020-03-26 18:44:53:413 [WD Proxy] Matched '/element/8B000000-0000-0000-3D01-000000000000/attribute/value' to command name 'getAttribute'
2020-03-26 18:44:53:413 [WD Proxy] Proxying [GET /element/8B000000-0000-0000-3D01-000000000000/attribute/value] to [GET http://127.0.0.1:21778/session/83341759-12D1-46EC-8F43-9152CC7C7E1D/element/8B000000-0000-0000-3D01-000000000000/attribute/value] with no body
2020-03-26 18:44:54:357 [Xcode]     t =  1033.05s     Find: Elements matching predicate '("XCUIElementTypeSwitch" IN wdType AND "Airplane Mode" IN wdLabel) AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0 OR selected == 0)'
2020-03-26 18:44:54:792 [Xcode]     t =  1033.50s     Find: Elements matching predicate '("XCUIElementTypeSwitch" IN wdType AND "Airplane Mode" IN wdLabel) AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0 OR selected == 0)'
2020-03-26 18:44:54:871 [Xcode]     t =  1033.57s Find: Elements matching predicate '("XCUIElementTypeSwitch" IN wdType AND "Airplane Mode" IN wdLabel) AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0 OR selected == 0)'
2020-03-26 18:44:54:892 [WD Proxy]   "value" : "0",
2020-03-26 18:44:54:893 [HTTP] <-- GET /wd/hub/session/4aedd606-2ccc-42e8-b7a3-6f92426ca13b/element/8B000000-0000-0000-3D01-000000000000/attribute/value 200 1480 ms - 13

**Comment by KazuCocoa** [comment]
I guess something was different in XCTest framework/iOS side...
What the result of `mobile: source` command with https://github.com/appium/appium/issues/14056#issuecomment-597969821 ?
You can see the vanilla returned value by XCTest for Appium's page source to check the element's value

**Comment by pocoyo-coder** [comment]
I have a suspicion as page source is only showing time/date/battery but not the details of the settings app.

XCTest comes with xcode, how can I change it?

here is the page source I am getting:
<?xml version="1.0" encoding="UTF-8"?><AppiumAUT><XCUIElementTypeApplication type="XCUIElementTypeApplication" name="Settings" label="Settings" enabled="true" visible="true" x="0" y="0" width="375" height="667">\n  <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" visible="false" x="0" y="0" width="375" height="667">\n    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="375" height="667"/>\n  </XCUIElementTypeWindow>\n  <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" visible="true" x="0" y="0" width="375" height="667">\n    <XCUIElementTypeStatusBar type="XCUIElementTypeStatusBar" enabled="true" visible="true" x="0" y="0" width="375" height="20">\n      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="375" height="20"/>\n      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="375" height="20">\n        <XCUIElementTypeOther type="XCUIElementTypeOther" name="Airplane mode on" label="Airplane mode on" enabled="true" visible="true" x="6" y="0" width="14" height="20"/>\n        <XCUIElementTypeOther type="XCUIElementTypeOther" name="4:08" label="4:08" enabled="true" visible="true" x="175" y="0" width="29" height="20"/>\n        <XCUIElementTypeOther type="XCUIElementTypeOther" name="Orientation Locked" label="Orientation Locked" enabled="true" visible="true" x="283" y="0" width="12" height="20"/>\n        <XCUIElementTypeOther type="XCUIElementTypeOther" name="100% battery power, On AC Power" label="100% battery power, On AC Power" enabled="true" visible="true" x="301" y="0" width="69" height="20"/>\n        <XCUIElementTypeOther type="XCUIElementTypeOther" name="100% battery power" label="100% battery power" enabled="true" visible="false" x="301" y="0" width="31" height="20"/>\n      </XCUIElementTypeOther>\n    </XCUIElementTypeStatusBar>\n  </XCUIElementTypeWindow>\n</XCUIElementTypeApplication></AppiumAUT>

**Comment by pocoyo-coder** [comment]
update:

so I enabled UI Automation in my ios 12.2 under developer in settings app and the page source has arrived in hole just once... after toggling the switch I was back to square one.

**Comment by KazuCocoa** [comment]
ah, thanks. I see.

https://appium.io/docs/en/drivers/ios-xcuitest-real-devices/ addresses the UI Automation preference as troubleshooting, and Apple also addresses it. (I forgot which page is..)

I did not notice it since it was always enabled for a while...
I guess Appium has been replacing tricky implementation to vanilla XCTest framework based one as possible to improve performance/reduce complicated implementation inside WDA since XCTest framework also has been matured. So. potentially, it affected...

**Comment by pocoyo-coder** [comment]
well it is nice to know.

another update:

while entering settings app didn't provided a full page source in its initial landing page.
scrolling a bit down and trying page source has brought the full source successfully.

But the my first issue persists! after seeing that when running page source the value is 1, i run the command get attribute and still get 0!

now here I think we can solve the issue. what causes WD proxy to return 0 when asking for an element or a value while in page source it is showing the correct value?

**Comment by MarkSpencerTan** [comment]
Still seeing this issue today after updating to the latest Xcode & Appium. Was working before that. Any solution or workarounds to this? We need to be able to get the value of the switch element on the Wifi Settings page, but is very inconsistent on anything less than iOS 13
