### ISSUE TITLE
On the Android system，when appium 1.15.1 runs a use case with a lot of steps, the service will be terminated when it executes step 60. The prompt: ESOCKETTIMEOUT

### ISSUE THREAD

**Issue by liyaoyao6342** [appium/appium#13690]
## The problem
When appium 1.15.1 runs a use case with a lot of steps, the service will be terminated when it executes step 60. The prompt: ESOCKETTIMEOUT

On the Android system, I started appium to establish a session, and then performed a series of click input return events. When the execution reached the 60th click event, the execution was not continued, and the appium service was terminated after an error was reported.

## Environment

* Appium version (or git revision) that exhibits the issue:1.15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:mac os 10.14.6
* Node.js version (unless using Appium.app|exe):13.1
* Npm or Yarn package manager:
* Mobile platform/version under test:android 9
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe:Command line appium

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

`[debug] [W3C (429c57dc)] Calling AppiumDriver.click() with args: ["65dfbde9-cea1-432f-a2dc-19f7da52d029","429c57dc-6468-4c49-ac02-a6719209577d"]
[debug] [WD Proxy] Matched '/element/65dfbde9-cea1-432f-a2dc-19f7da52d029/click' to command name 'click'
[debug] [WD Proxy] Proxying [POST /element/65dfbde9-cea1-432f-a2dc-19f7da52d029/click] to [POST http://localhost:8224/wd/hub/session/c39d40ed-1a28-4b26-a6e9-ccf4e10d3c24/element/65dfbde9-cea1-432f-a2dc-19f7da52d029/click] with body: {"element":"65dfbde9-cea1-432f-a2dc-19f7da52d029"}
[WD Proxy] Got an unexpected response with status undefined: {"code":"ESOCKETTIMEDOUT","connect":false}
[debug] [W3C (429c57dc)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT
[debug] [W3C (429c57dc)]     at JWProxy.command (/usr/local/homebrew/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:261:13)
[HTTP] <-- POST /wd/hub/session/429c57dc-6468-4c49-ac02-a6719209577d/element/65dfbde9-cea1-432f-a2dc-19f7da52d029/click 500 240022 ms - 541
[HTTP]`

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Could you also attach the logcat output?

**Comment by mykola-mokhnach** [comment]
Closed because of no response
