### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Failed to start Chromedriver session: An unknown server-side error occurred while processing the command. Original error: unknown error: Failed to get PID for the following process: WEBVIEW_com.XXX.XXXX

### ISSUE THREAD

**Issue by journey1989** [appium/appium#13696]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Please fill out the issue report form properly

**Comment by journey1989** [comment]
The problem
Native switch H5 error：selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Failed to start Chromedriver session: An unknown server-side error occurred while processing the command. Original error: unknown error: unable to discover open pages
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Windows NT 10.0.18362 x86_64)


Environment
Appium version (or git revision) that exhibits the issue: 1.13.0
Last Appium version that did not exhibit the issue (if applicable):
Desktop OS/version used to run Appium:window 64
Node.js version (unless using Appium.app|exe):v10.14.2
Npm or Yarn package manager:
Mobile platform/version under test:android/8.1.0 or android/9
Real device or emulator/simulator:emulator
Appium CLI or Appium.app|exe:Appium.app
Details

Executive order:self.driver.switch_to.context('WEBVIEW_com.putao.abc') error：selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Failed to start Chromedriver session: An unknown server-side error occurred while processing the command. Original error: unknown error: unable to discover open pages
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Windows NT 10.0.18362 x86_64)，                 
  I don't know what caused it


Link to Appium logs
Create a GIST which is a paste of your full Appium logs, and link them here.
Do NOT paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, always include Appium logs!

Code To Reproduce Issue [ Good To Have ]

class Report(Common):
    passbutton = (By.ID, 'com.putao.abc:id/login_to_password_tv')  # 密码登录
    sendphone = (By.ID, 'com.putao.abc:id/loginpassword_editphone')  # 输入手机号
    sendpass = (By.ID, 'com.putao.abc:id/loginpassword_editpsw')  # 输入密码
    clicklogin = (By.ID, 'com.putao.abc:id/loginpassword_btn')  # 点击登录
    major = (By.ID, 'com.putao.abc:id/major_bottom_btn')   #首页进入课程
    thins = (By.XPATH, "//android.widget.TextView[@text='2.School Things']")   #2.1.2
    inreport = (By.ID,'com.putao.abc:id/iv_report')  #课程步骤的课程报告
    classname = (By.CLASS_NAME, "footer")
    def rep(self):
        #self.getLogins()
        self.meetClose()
        self.myButton()
        logging.info('=====密码登录=====')
        self.driver.find_element(*self.passbutton).click()
        time.sleep(3)
        logging.info('=======点击手机号栏，输入手机号=========')
        time.sleep(2)
        data=self.get_phone(self.csv_file,3)
        self.driver.find_element(*self.sendphone).send_keys(data[0])
        time.sleep(2)
        self.driver.find_element(*self.sendpass).send_keys(data[1])
        time.sleep(3)
        self.driver.find_element(*self.clicklogin).click()
        time.sleep(3)
        self.driver.find_element(*self.major).click()
        time.sleep(3)
        #self.getScreenshot('课程路径')
        time.sleep(4)
        logging.info('======点击课程路径课icon=====')
        self.driver.find_element(*self.thins).click()
        time.sleep(2)
        logging.info('======课程步骤——课程报告=====')
        self.driver.find_element(*self.inreport).click()

        #WebDriverWait(self.driver,10).until(lambda x:x.find_element_by_class_name("android.view.View"))
        time.sleep(3)
        contexts = self.driver.contexts
        print('context=', contexts)
        time.sleep(10)
        self.driver.switch_to.context('WEBVIEW_com.putao.abc')

        logging.info('=====点击立即分享=====')
        self.driver.find_element_by_class_name("footer").click()

**Comment by journey1989** [comment]
h5 ：x5_webview
