### ISSUE TITLE
Appium v1.16.0-beta.3 crashes when connection to real iOS 12.4.1 device

### ISSUE THREAD

**Issue by broetchenrackete36** [appium/appium#13692]
## The problem

When running the 1.16 beta 3 the appium server crashes (the process just stops) when trying to create a new session on an iPhone XR with iOS 12.4.1. This didn't happen in 1.15.1 and it is also not happening on iOS 13...

## Environment

* Appium version (or git revision) that exhibits the issue: v1.16.0-beta.3
* Last Appium version that did not exhibit the issue (if applicable): 1.15.1
* Desktop OS/version used to run Appium: Mac OS 10.15
* Node.js version (unless using Appium.app|exe): 13.2.0
* Npm or Yarn package manager: 6.13.1
* Mobile platform/version under test: iOS 12.4.1
* Real device or emulator/simulator: real iPhone XR
* Appium CLI or Appium.app|exe: cli

## Details

While looking through the logs the first difference i found was that appium 1.16 tries to start [Remote Debugger] instead of trying to use WDA?

## Link to Appium logs

[Logs to success on 1.15.1 and failure on 1.16.0-beta3](https://gist.github.com/broetchenrackete36/21aae141d6420b67eb09aba7241b1957)

**Comment by broetchenrackete36** [comment]
Just to prevent any misunderstandings: I'm not testing mobile Safari but my own app that is already installed on the device.

**Comment by mykola-mokhnach** [comment]
Could you please attach logs with `logAllCommunicationHexDump` cap enabled?

**Comment by broetchenrackete36** [comment]
[Log with Cap enabled](https://gist.github.com/broetchenrackete36/d0a04a52d208869f29007c4b30c5dc66)

**Comment by broetchenrackete36** [comment]
BTW I get the same error when I try to automate something like the Preferences App or even when I try to automate MobileSafari through browserName-Cap.

**Comment by mykola-mokhnach** [comment]
cc @imurchie 

Is there any reason to establish a debugger connection for native tests?

**Comment by mykola-mokhnach** [comment]
@broetchenrackete36 Please reinstall appium@beta - now the script does no try to connect to the remote debugger if this is not needed

**Comment by broetchenrackete36** [comment]
My first tests seemed fine but when i tried to use it in my full test-setup it failed again. I'm trying to reproduce and post logs here...

**Comment by broetchenrackete36** [comment]
I thought my tests where fine but I must have made a mistake.

I uninstalled and reinstalled appium@beta and xcuitest-driver is at 3.10.0 but the remote-debugger still tries to start and appium crashes.

**Comment by imurchie** [comment]
What is the output of `npm ls -g appium-xcuitest-driver` (or `npm ls appium-xcuitest-driver` if you have a local install)?

**Comment by broetchenrackete36** [comment]
```
/usr/local/lib
-- appium@1.16.0-beta.3
  +-- appium-flutter-driver@0.0.20
  | -- appium-xcuitest-driver@2.133.1
  +-- appium-xcuitest-driver@3.10.0
  -- appium-youiengine-driver@1.2.3
    -- appium-xcuitest-driver@3.10.0  deduped

```

**Comment by imurchie** [comment]
Can you post the logs, as a link to a [gist](https://gist.github.com)?

**Comment by broetchenrackete36** [comment]
[New log](https://gist.github.com/broetchenrackete36/0ba6bb77ba49a5ee68f075dcfb2fe871)
Looks the same to me...

**Comment by imurchie** [comment]
Crap. I totally messed up. I'll fix this and let you know.

**Comment by imurchie** [comment]
@broetchenrackete36 My apologies. I missed the key part in fixing this. It should work now, if you update Appium. `appium-xcuitest-driver` ought to be version `3.10.1`.

**Comment by broetchenrackete36** [comment]
Now it seems to be working! Thanks :)

**Comment by chuklov** [comment]
Hi  @imurchie I have exactly the same issue with the driver :
Mac-mini-2:appium-webdriveragent chuklova$ npm ls -g appium-xcuitest-driver
/usr/local/lib
└─┬ appium@1.16.0
  ├─┬ appium-flutter-driver@0.0.20
  │ └── appium-xcuitest-driver@2.133.1 
  ├── appium-xcuitest-driver@3.10.1 
  └─┬ appium-youiengine-driver@1.2.3
    └── appium-xcuitest-driver@3.10.1  deduped

When I starting appium it is loading my app and closes. How I can collect logs to upload it here? 

Thanks

**Comment by imurchie** [comment]
@chuklov Please post the Appium server logs, as a link to a [gist](https://gist.github.com).
