### ISSUE TITLE
Appium Responding very slow in specific app

### ISSUE THREAD

**Issue by ahmadsayeed3** [appium/appium#13694]
## The problem

I am trying to automate an application called Zomato. 
I am strange to see that only with this APK appium server is responding very slow. The find-element is taking 20 to 30 seconds. The full appium logs are attached.

I am trying to know what is so special on this APK which is making the Appium server slow?

**Things I have tried** 

- Tried with different Appium v1.15.1, v1.12.1 and v1.13.0
- Added uiautomato2 in the capability.
- Tried uninstalling uiautomator server appium setting from the device.
- Tried on different devices Android V9 and Android V8.1
- Checked page source is not big in comparison to other working fine APKs.
- A tried different version of this APK

Page Source: https://gist.github.com/ahmadsayeed3/e9aa5f0e783b64d461fd39637d416d66
APK: https://apkpure.com/zomato-restaurant-finder-and-food-delivery-app/com.application.zomato.
## Environment

* Appium version: v1.15.1, 1.12.1 and v1.13.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): v10.16.3
* Npm or Yarn package manager: Npm 
* Mobile platform/version under test: Android V8.1 and V9
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI
* Java-CLient Version: 7.2.0

## Link to Appium logs
https://gist.github.com/ahmadsayeed3/b05b740eb91fa7fc840542c134c4d012

## Code To Reproduce Issue [ These are the capabilities I am using: ]

```
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability("deviceName", "PL2GAR4832302659");
capabilities.setCapability("automationName", "uiautomator2");
capabilities.setCapability("adbExecuteTimeout", 90000);
capabilities.setCapability("platformVersion", "8.1.0");
capabilities.setCapability("newCommandTimeout", 600);
capabilities.setCapability("launchTimeout", 90000);
capabilities.setCapability("platformName", "Android");
capabilities.setCapability("rotatable", true);
capabilities.setCapability("noSign", true);
capabilities.setCapability("appPackage", "com.application.zomato");
capabilities.setCapability("appActivity", "com.application.zomato.activities.Splash");
capabilities.setCapability("app", "E:\\Opkey-Code-Base\\AppiumProject\\Zomato1.apk");
capabilities.setCapability("noReset", false);
capabilities.setCapability("fullReset", true);
URL endpointURL = new URL("http://127.0.0.1:4723/wd/hub");
AppiumDriver<WebElement> driver =  new AndroidDriver<WebElement>(endpointURL, capabilities);
		
WebElement faceBookEle = driver.findElement(By.xpath("//android.widget.Button[@resource-id='com.application.zomato:id/layout_connect_using_facebook']"));
System.out.println("Is Facebook button there: " + faceBookEle.isDisplayed());
		
WebElement googleButton = driver.findElement(By.xpath("//android.widget.Button[@resource-id='com.application.zomato:id/layout_connect_using_google']"));
System.out.println("Is Google button there: " + googleButton.isDisplayed());
		
WebElement emailButton = driver.findElement(By.xpath("//android.widget.Button[@resource-id='com.application.zomato:id/layout_signup']"));
System.out.println("Is Email button there: " + emailButton.isDisplayed());
		
emailButton.click();
		
driver.quit();
```

What can I do to find out the root cause?

**Comment by mykola-mokhnach** [comment]
It might be the app is never in idle state, so the UIA2 framework is unable to snapshot its accessibility structure. See https://github.com/appium/appium/issues?q=is%3Aissue+waitforidletimeout+is%3Aclosed

**Comment by ahmadsayeed3** [comment]
Hi Mykola,

Thanks for sharing that useful link. And yes it was the idle state issue. Even when I stop the animation manually it started working. 

This code worked for me.
`driver.setSetting(Setting.WAIT_FOR_IDLE_TIMEOUT, 500);`
