### ISSUE TITLE
ERROR: Got an unexpected response with status undefined: {"errno":"econnreset","code":"econnreset","syscall":"read"}"

### ISSUE THREAD

**Issue by Fabinho12** [appium/appium#13706]
The problem

Hello, I have a problem running on my device, in the logs it gives me the following error: "got an unexpected response with status undefined: {"errno":"econnreset","code":"econnreset","syscall":"read"}"

Environment

Appium version (or git revision) that exhibits the issue: Version 1.15.1
Desktop OS/version used to run Appium: Windows 10
Mobile platform/version under test: Android 7.0
Real device or emulator/simulator: both
Details

If necessary, describe the problem you have been experiencing in more detail.

Link to Appium logs

https://gist.github.com/Fabinho12/d26fa2b4a33f639f2cca7e513d1aef13

**Comment by mykola-mokhnach** [comment]
> [debug] [35m[W3C][39m Encountered internal error running command: Error: Cannot start the 'goova.sofisa.client.v2' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Error executing adbExec. Original error: 'Command ''C:\\Program Files (x86)\\Android\\android-sdk\\platform-tools\\adb.exe' -P 5037 -s LGM250LRYHNR6HCICI shell am start -W -n goova.sofisa.client.v2/md58f38b8a3bd4f6c92c152b7a330ce4586.MainActivity -S' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability

Have you checked the tutorial above?

**Comment by syamsundarjana** [comment]
> The problem
> 
> Hello, I have a problem running on my device, in the logs it gives me the following error: "got an unexpected response with status undefined: {"errno":"econnreset","code":"econnreset","syscall":"read"}"
> 
> Environment
> 
> Appium version (or git revision) that exhibits the issue: Version 1.15.1
> Desktop OS/version used to run Appium: Windows 10
> Mobile platform/version under test: Android 7.0
> Real device or emulator/simulator: both
> Details
> 
> If necessary, describe the problem you have been experiencing in more detail.
> 
> Link to Appium logs
> 
> https://gist.github.com/Fabinho12/d26fa2b4a33f639f2cca7e513d1aef13

**Comment by syamsundarjana** [comment]
Hi,
i have same problem while running same script on parallel devices.
in one device the script run and on other device it gives below error. Please check and help me


[debug] [WD Proxy] Proxying [GET /element/725b25ce-eafb-48c8-a
a81-415aa4684a61/attribute/displayed] to [GET http://localhost
:8201/wd/hub/session/2a4a45ad-8ac5-4a1b-9f4c-de38a43ed130/elem
ent/725b25ce-eafb-48c8-aa81-415aa4684a61/attribute/displayed]
with body: {}
[WD Proxy] Got an unexpected response with status undefined: {
"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}
[debug] [W3C (5cce8dbf)] Encountered internal error running co
mmand: UnknownError: An unknown server-side error occurred whi
le processing the command. Original error: Could not proxy com
**mand to remote server. Original error: Error: read ECONNRESET**
[debug] [W3C (5cce8dbf)]     at JWProxy.command (C:\Users\jsya
msundar\AppData\Roaming\npm\node_modules\appium\node_modules\a
ppium-base-driver\lib\jsonwp-proxy\proxy.js:261:13)
[HTTP] <-- GET /wd/hub/session/5cce8dbf-d555-4f02-9a2c-ead381e
67423/element/725b25ce-eafb-48c8-aa81-415aa4684a61/displayed 5
00 58 ms - 570
[HTTP]

**Comment by syamsundarjana** [comment]
Some more log lines ..
[debug] [W3C (5cce8dbf)] Calling AppiumDriver.findElement() wi
th args: ["xpath","//android.widget.EditText","5cce8dbf-d555-4
f02-9a2c-ead381e67423"]
[debug] [BaseDriver] Valid locator strategies for this request
: xpath, id, class name, accessibility id, -android uiautomato
r
[debug] [BaseDriver] Waiting up to 3000000 ms for condition
[debug] [WD Proxy] Matched '/element' to command name 'findEle
ment'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://lo
calhost:8201/wd/hub/session/2a4a45ad-8ac5-4a1b-9f4c-de38a43ed1
30/element] with body: {"strategy":"xpath","selector":"//andro
id.widget.EditText","context":"","multiple":false}
[debug] [WD Proxy] Got response with status 200: {"sessionId":
"2a4a45ad-8ac5-4a1b-9f4c-de38a43ed130","value":{"ELEMENT":"5b2
0b648-a2b4-4433-98f5-310592e1340e","element-6066-11e4-a52e-4f7
35466cecf":"5b20b648-a2b4-4433-98f5-310592e1340e"}}
[debug] [W3C (5cce8dbf)] Responding to client with driver.find
Element() result: {"element-6066-11e4-a52e-4f735466cecf":"5b20
b648-a2b4-4433-98f5-310592e1340e","ELEMENT":"5b20b648-a2b4-443
3-98f5-310592e1340e"}
[HTTP] <-- POST /wd/hub/session/5cce8dbf-d555-4f02-9a2c-ead381
e67423/element 200 694 ms - 137
[HTTP]
[HTTP] --> POST /wd/hub/session/5cce8dbf-d555-4f02-9a2c-ead381
e67423/element/5b20b648-a2b4-4433-98f5-310592e1340e/click
[HTTP] {"id":"5b20b648-a2b4-4433-98f5-310592e1340e"}
[debug] [W3C (5cce8dbf)] Calling AppiumDriver.click() with arg
s: ["5b20b648-a2b4-4433-98f5-310592e1340e","5cce8dbf-d555-4f02
-9a2c-ead381e67423"]
[debug] [WD Proxy] Matched '/element/5b20b648-a2b4-4433-98f5-3
10592e1340e/click' to command name 'click'
[debug] [WD Proxy] Proxying [POST /element/5b20b648-a2b4-4433-
98f5-310592e1340e/click] to [POST http://localhost:8201/wd/hub
/session/2a4a45ad-8ac5-4a1b-9f4c-de38a43ed130/element/5b20b648
-a2b4-4433-98f5-310592e1340e/click] with body: {"element":"5b2
0b648-a2b4-4433-98f5-310592e1340e"}
[debug] [WD Proxy] Got response with status 200: {"sessionId":
"2a4a45ad-8ac5-4a1b-9f4c-de38a43ed130","value":null}
[debug] [W3C (5cce8dbf)] Responding to client with driver.clic
k() result: null
[HTTP] <-- POST /wd/hub/session/5cce8dbf-d555-4f02-9a2c-ead381
e67423/element/5b20b648-a2b4-4433-98f5-310592e1340e/click 200
135 ms - 14
[HTTP]
[HTTP] --> POST /wd/hub/session/5cce8dbf-d555-4f02-9a2c-ead381
e67423/element
[HTTP] {"using":"xpath","value":"//android.widget.EditText"}
[debug] [W3C (5cce8dbf)] Calling AppiumDriver.findElement() wi
th args: ["xpath","//android.widget.EditText","5cce8dbf-d555-4
f02-9a2c-ead381e67423"]
[debug] [BaseDriver] Valid locator strategies for this request
: xpath, id, class name, accessibility id, -android uiautomato
r
[debug] [BaseDriver] Waiting up to 3000000 ms for condition
[debug] [WD Proxy] Matched '/element' to command name 'findEle
ment'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://lo
calhost:8201/wd/hub/session/2a4a45ad-8ac5-4a1b-9f4c-de38a43ed1
30/element] with body: {"strategy":"xpath","selector":"//andro
id.widget.EditText","context":"","multiple":false}
[debug] [WD Proxy] Got response with status 200: {"sessionId":
"2a4a45ad-8ac5-4a1b-9f4c-de38a43ed130","value":{"ELEMENT":"725
b25ce-eafb-48c8-aa81-415aa4684a61","element-6066-11e4-a52e-4f7
35466cecf":"725b25ce-eafb-48c8-aa81-415aa4684a61"}}
[debug] [W3C (5cce8dbf)] Responding to client with driver.find
Element() result: {"element-6066-11e4-a52e-4f735466cecf":"725b
25ce-eafb-48c8-aa81-415aa4684a61","ELEMENT":"725b25ce-eafb-48c
8-aa81-415aa4684a61"}
[HTTP] <-- POST /wd/hub/session/5cce8dbf-d555-4f02-9a2c-ead381
e67423/element 200 1091 ms - 137
[HTTP]
[HTTP] --> GET /wd/hub/session/5cce8dbf-d555-4f02-9a2c-ead381e
67423/element/725b25ce-eafb-48c8-aa81-415aa4684a61/displayed
[HTTP] {}
[debug] [W3C (5cce8dbf)] Calling AppiumDriver.elementDisplayed
() with args: ["725b25ce-eafb-48c8-aa81-415aa4684a61","5cce8db
f-d555-4f02-9a2c-ead381e67423"]
[debug] [WD Proxy] Matched '/element/725b25ce-eafb-48c8-aa81-4
15aa4684a61/attribute/displayed' to command name 'getAttribute
'
[debug] [WD Proxy] Proxying [GET /element/725b25ce-eafb-48c8-a
a81-415aa4684a61/attribute/displayed] to [GET http://localhost
:8201/wd/hub/session/2a4a45ad-8ac5-4a1b-9f4c-de38a43ed130/elem
ent/725b25ce-eafb-48c8-aa81-415aa4684a61/attribute/displayed]
with body: {}
[WD Proxy] Got an unexpected response with status undefined: {
"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}
[debug] [W3C (5cce8dbf)] Encountered internal error running co
mmand: UnknownError: An unknown server-side error occurred whi
le processing the command. Original error: Could not proxy com
mand to remote server. Original error: Error: read ECONNRESET
[debug] [W3C (5cce8dbf)]     at JWProxy.command (C:\Users\jsya
msundar\AppData\Roaming\npm\node_modules\appium\node_modules\a
ppium-base-driver\lib\jsonwp-proxy\proxy.js:261:13)
[HTTP] <-- GET /wd/hub/session/5cce8dbf-d555-4f02-9a2c-ead381e
67423/element/725b25ce-eafb-48c8-aa81-415aa4684a61/displayed 5
00 58 ms - 570
[HTTP]
