### ISSUE TITLE
UiAutomator2 can find element; Espresso can't.

### ISSUE THREAD

**Issue by blane1988** [appium/appium#13707]
## The problem
With UiAutomator2, I am able to find an element by xpath. Once I switch to using Espresso, however, it gets stuck trying to find the same element. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS Mojave - 10.14.6
* Node.js version (unless using Appium.app|exe): 12.13.1
* Npm or Yarn package manager: yarn 1.16.0
* Mobile platform/version under test: Android 9
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

When spying on elements via Appium Studio, I can get xpaths just fine. UiAutomator2 can then detect elements using those xpaths, but Espresso can't. When I use an xpath as a selector such as `const environment = await driver.$("//*[@tag='Primary_Button_Login']");`, it just hangs there, waiting to find it. It also hangs when I use this selector strategy:  `driver.$("~Primary_Button_Login")`. Espresso can't seem to see anything.

Here are my capabilities:
```
capabilities: {
    platformName: "Android",
    platformVersion: "9",
    deviceName: "Android Phone",
    app: "/Users/blane/Documents/Development/appium/[AppNameRedacted].apk",
    appPackage: "com.[AppNameRedacted].mobile.enterprise",
    appActivity: "com.[AppNameRedacted].mobile.MainActivity",
    automationName: "Espresso",
    forceEspressoRebuild: "true",
    newCommandTimeout: 10,
    appWaitDuration: 60000,
    autoGrantPermissions: "true"
  }
```
## Link to Appium logs

[Appium log](https://gist.github.com/blane1988/e4cdba3e51be13c67c688269dafe4179)

## Source code of test

```
"use strict"
const wdio = require("webdriverio");
jest.setTimeout(100000);

// Android testing for emulator and device.
const opts = {
  port: 4723,
  capabilities: {
    platformName: "Android",
    platformVersion: "9",
    deviceName: "Android Phone",
    app: "/Users/blane/Documents/Development/appium/[AppNameRedacted].apk",
    appPackage: "com.[AppNameRedacted].mobile.enterprise",
    appActivity: "com.[AppNameRedacted].mobile.MainActivity",
    // automationName: "UiAutomator2",
    automationName: "Espresso",
    forceEspressoRebuild: "true",
    newCommandTimeout: 10,
    appWaitDuration: 60000,
    autoGrantPermissions: "true",
    clearDeviceLogsOnStart: "true"
  }
};

it('should show login screen using Espresso driver', async () => {
  const driver = await wdio.remote(opts);
  await driver.setImplicitTimeout(30000);

  // const environment = await driver.$("//*[@tag='Midway (Local Proxy)']");
  // const environment = await driver.$("//*[@text='Midway (Local Proxy)']");

  // Test flow hangs at next line.
  const environment = await driver.$("~Midway (Local Proxy)");
  await environment.touchAction('tap');

  const logIn = await driver.$("//*[@text='LOG IN']");
  // const logIn = await driver.$("//*[@tag='PrimaryButton_Login']");
  await logIn.touchAction('tap');

  const username = await driver.$("//*[@text='Card User ID']");
  await username.addValue("ASYS12345");

  const password = await driver.$("//*[@text='Password']");
  await password.addValue("Discover01");

  const loginButton = await driver.$("//*[@text='LOG IN']");
  await loginButton.touchAction('tap');
});
```

**Comment by mykola-mokhnach** [comment]
Is the element present in the page source? Are there any errors in the logcat output?

**Comment by blane1988** [comment]
Logcat output doesn't seem to show any errors. Mainly just system/device stuff. As for page source, the element appears in Appium Studio when using the spy.  Now, does it make a difference that Appium Studio uses UiAutomator to spy on elements? Below is what I am able to see of the element. If I can see these properties here, then Espresso should be able to pick up on them, right? Thanks.
<img width="638" alt="Screen Shot 2019-12-12 at 9 48 00 AM" src="https://user-images.githubusercontent.com/42759546/70727381-387be480-1cc5-11ea-9372-f671a954458f.png">

**Comment by imurchie** [comment]
"Should" is a loaded word here. What is _actually_ seen by Espresso is important. Can you get the source, in your test script, right before you are trying to find the element?

**Comment by mykola-mokhnach** [comment]
Appium Studio is a third party commercial product, which has nothing to do with Appium itself

**Comment by blane1988** [comment]
Hi guys, thanks for quick replies. Here is the source. Very simple; just to prove things out.
```
"use strict"
const wdio = require("webdriverio");
jest.setTimeout(100000);

// Android testing for emulator and device.
const opts = {
  port: 4723,
  capabilities: {
    platformName: "Android",
    platformVersion: "9",
    deviceName: "Android Phone",
    app: "/Users/blane/Documents/Development/appium/[AppNameRedacted].apk",
    appPackage: "com.[AppNameRedacted].mobile.enterprise",
    appActivity: "com.[AppNameRedacted].mobile.MainActivity",
    // automationName: "UiAutomator2",
    automationName: "Espresso",
    forceEspressoRebuild: "true",
    newCommandTimeout: 10,
    appWaitDuration: 60000,
    autoGrantPermissions: "true",
    clearDeviceLogsOnStart: "true"
  }
};

it('should show login screen using Espresso driver', async () => {
  const driver = await wdio.remote(opts);
  await driver.setImplicitTimeout(30000);

  // const environment = await driver.$("//*[@tag='Midway (Local Proxy)']");
  // const environment = await driver.$("//*[@text='Midway (Local Proxy)']");

  // Test flow hangs at next line.
  const environment = await driver.$("~Midway (Local Proxy)");
  await environment.touchAction('tap');

  const logIn = await driver.$("//*[@text='LOG IN']");
  // const logIn = await driver.$("//*[@tag='PrimaryButton_Login']");
  await logIn.touchAction('tap');

  const username = await driver.$("//*[@text='Card User ID']");
  await username.addValue("ASYS12345");

  const password = await driver.$("//*[@text='Password']");
  await password.addValue("Discover01");

  const loginButton = await driver.$("//*[@text='LOG IN']");
  await loginButton.touchAction('tap');
});
```

**Comment by imurchie** [comment]
Sorry, we meant the source of the view. Using https://webdriver.io/docs/api/webdriver.html#getpagesource

**Comment by blane1988** [comment]
Thanks for that strategy tip. Since this is a mobile app, I used `let source = await driver.getPageSource();`. Being a simple screen, there isn't much XML to begin with. After viewing the source content, there is no reference to my element, or any other element of interest for that matter. Most of it is just boilerplate elements, like `</android.widget.FrameLayout>`.  If my element is not even in the XML tree, I wonder how UiAutomator2 is able to find it. Investigating further....

**Comment by blane1988** [comment]
Okay, I put the `getPageSource()` call a bit later in the script and switched back to UiAutomator2, and now I see a huge XML tree with my desired elements. So maybe there is some synchronization issue going on. I will try to code the script to obtain page source at a different spot when using Espresso.

**Comment by imurchie** [comment]
Ok. Seems like Espresso does not like the structure for some reason. Unfortunately there is not much we can do. If you know _where_ the element are, you can interact with them based on position, but that's brittle and hard to maintain.

**Comment by mykola-mokhnach** [comment]
There is, actually, a big difference between how Espresso and UIA2 retrieve the page source. UIA2 uses accessibility manager for this purpose while Espresso is based on the framework integrated into the application hierarchy.

**Comment by blane1988** [comment]
Is there a spy tool that can see the source structure like Espresso does? Because Appium Studio uses UiAutomator for structure parsing. What do other developers (who are using Espresso) use for finding elements? Thanks.

**Comment by imurchie** [comment]
In Appium Desktop if you start the session with `automationName = 'espresso'` you ought be able to inspect what Espresso is returning.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
