### ISSUE TITLE
使用npm install -g appium 会提示权限不足

### ISSUE THREAD

**Issue by tutuyeah** [appium/appium#13719]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by tutuyeah** [comment]
报错如下：
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules/appium/node_modules/_adbkit-apkreader@3.1.2@adbkit-apkreader/node_modules/bluebird
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/appium/node_modules/_adbkit-apkreader@3.1.2@adbkit-apkreader/node_modules/bluebird'
npm ERR!  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules/appium/node_modules/_adbkit-apkreader@3.1.2@adbkit-apkreader/node_modules/bluebird'] {
npm ERR!   stack: "Error: EACCES: permission denied, access '/usr/local/lib/node_modules/appium/node_modules/_adbkit-apkreader@3.1.2@adbkit-apkreader/node_modules/bluebird'",
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/appium/node_modules/_adbkit-apkreader@3.1.2@adbkit-apkreader/node_modules/bluebird'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:

**Comment by mykola-mokhnach** [comment]
It looks like there is an issue with file system permissions on your system. Make sure the node modules root folder is readable/writeable to npm process.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
