### ISSUE TITLE
Adding process arguments to switch to dark mode creates issue

### ISSUE THREAD

**Issue by rajkumar-cp** [appium/appium#13714]
## The problem

Not able to switch to dark mode in appium by using process arguments processArguments: { args: ['test_darkmode'] }
We were using sauce labs environment for testing.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.0
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: NA
* Node.js version (unless using Appium.app|exe): NA
* Npm or Yarn package manager: NA
* Mobile platform/version under test: iOS 13
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium.app

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/rajkumar-cp/c29599a6245deb2ca4deff9b60b504d1

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by imurchie** [comment]
You're sending in the cap as a string, so it needs to be valid JSON. Try 

`"{\"args\": [\"test_darkmode\"]}"`.

**Comment by rajkumar-cp** [comment]
Hi @imurchie 

I tried providing the same this time the app launched but still only in light mode and not dark mode. Am i missing something here ?

PFA the appium logs here.

https://gist.github.com/rajkumar-cp/8d5d38e0b804c379f78b518f2568b288

**Comment by imurchie** [comment]
Does that process argument make it dark mode locally? I've never tried and have no idea if it does anything,

**Comment by rajkumar-cp** [comment]
@imurchie 

How to check the same locally?

**Comment by KazuCocoa** [comment]
How to handle the arguments inside the app?
You can handle the arguments like below. If the 'test_darkmode' exists in `ProcessInfo.processInfo.arguments`, the processArguments capability works as Appium side.
Please make sure the app under test process was closed before launching by the arguments since iOS has no method to apply process arguments against running app.

```swift
// swift
if ProcessInfo.processInfo.arguments.contains("test_darkmode") {
    window.overrideUserInterfaceStyle = .dark
}
```

**Comment by mykola-mokhnach** [comment]
I don't observe any Appium issues here. Please check the stuff with your application developer

**Comment by rajkumar-cp** [comment]
@KazuCocoa 

Do you know where exactly we need to add that piece of code in app file. How it will fetch the capability that we were passing using appium ?

**Comment by KazuCocoa** [comment]
`mobile:activeAppInfo` in https://appium.io/docs/en/commands/mobile-command/ is the easiest way to check it

It depends on your application > Do you know where exactly...
I'd recommend you to ask app developers for it. (I guess the easiest way is in AppDelegate, but it also depends on your app structure.)

**Comment by prabhus06** [comment]
@rajkumar-cp - any luck on this ? were you able to set the mode to dark or light?
