### ISSUE TITLE
[FBApplication resolve]: unrecognized selector sent to instance 0x2831bd2d0

### ISSUE THREAD

**Issue by VTDuyen1** [appium/appium#13727]
## The problem

When I updated the xcode version to 11.2, I had the following problem:
FBApplication resolve]: unrecognized selector sent to instance 0x2831bd2d0\n\n(\n\t0   CoreFoundation                      0x0000000213e03198 <redacted> + 252\n\t1   libobjc.A.dylib                     0x0000000212fdb9f8 objc_exception_throw + 56\n\t2   CoreFoundation                      0x0000000213d1f9bc <redacted> + 0\n\t3   CoreFoundation                      0x0000000213e089c8 <redacted> + 1408\n\t4   CoreFoundation                      0x0000000213e0a65c _CF_forwarding_prep_0 + 92\n\t5   WebDriverAgentLib                   0x0000000102a88e14 -[XCUIElement(FBUtilities) fb_snapshotWithAttributes] + 96\n\t6   WebDriverAgentLib                   0x0000000102a5a854 +[FBXPath writeXmlWithRootElement:indexPath:elementStore:includedAttributes:writer:] + 912\n\t7   WebDriverAgentLib                   0x0000000102a59c58 +[FBXPath xmlRepresentationWithRootElement:writer:elementStore:query:] + 436\n\t8   WebDriverAgentLib                   0x0000000102a59278 +[FBXPath matchesWithRootElement:forQuery...
[WD Proxy] The response has an unknown format

Appium can open the application, but all methods to retrieve the element have an error.

## Environment

* Appium version : 1.15.1
* Desktop OS/version used to run Appium: macos
* Node.js version (unless using Appium.app|exe): v12.10.0
* Npm or Yarn package manager: 6.11.3
* Mobile platform/version under test: 12.4.2
* Real device or emulator/simulator: Real device

## Link to Appium logs

This is the log from the Appium inspector: 
https://gist.github.com/VTDuyen1/46c3c8833e264494bf89ecca5b30af59

**Comment by mykola-mokhnach** [comment]
Make sure no WebDriverAgent leftovers are present on the device under test. It make sense to remove the WebDriverAgent runner from the device manually and clear the Xcode caches.

**Comment by VTDuyen1** [comment]
@mykola-mokhnach Thanks a lot, after I manually deleted WebDriverAgent runner and clear the Xcode caches, I got rid of this problem.
