### ISSUE TITLE
Continue test before disconnect wifi 

### ISSUE THREAD

**Issue by Alexander-Tkachev** [appium/appium#13726]
## The problem

I have several real devices connected to appium via wifi. One of the steps of the test involves disabling Wi-Fi and checking the operability of the device. But at the same time, the test loses touch and crashes, because the test device is no longer visible to the appium. Is there any solution for this?

**Comment by mykola-mokhnach** [comment]
Please provide the detailed info on your environment.

I assume the problem is that while terminating the connection on the device the connection to the server running there is terminates as well, which breaks the automation session. A possible workaround might be to quit the session after the connection state is changed and create a new one (possibly with `noReset` option enabled) when the network connectivity is restored.

**Comment by Alexander-Tkachev** [comment]
> Please provide the detailed info on your environment.
> 
> I assume the problem is that while terminating the connection on the device the connection to the server running there is terminated as well, which breaks the automation session. A possible workaround might be to quit the session after the connection state is changed and create a new one (possibly with `noReset` option enabled) when the network connectivity is restored.

Through adb, I established a wireless connection with my test device. All appppium test commands pass fine until I execute context.driver.toggle_wifi (). After that, my test does not go any further.

The following is written in the appium's terminal:

>`[HTTP] <-- GET /wd/hub/session/4c4a64d0-8a4e-40ac-ab36-d81d22e4c0fd/screenshot 200 5667 ms - 1937792
[HTTP] 
[HTTP] --> POST /wd/hub/session/4c4a64d0-8a4e-40ac-ab36-d81d22e4c0fd/appium/device/toggle_wifi
[HTTP] {}
[debug] [W3C (4c4a64d0)] Calling AppiumDriver.toggleWiFi() with args: ["4c4a64d0-8a4e-40ac-ab36-d81d22e4c0fd"]
[debug] [ADB] Running '/home/atkachev/Android/Sdk/platform-tools/adb -P 5037 -s 192.168.61.40\:5555 shell settings get global wifi_on'
[AndroidDriver] Turning WiFi off
[debug] [ADB] Running '/home/atkachev/Android/Sdk/platform-tools/adb -P 5037 -s 192.168.61.40\:5555 shell am broadcast -a io.appium.settings.wifi -n io.appium.settings/.receivers.WiFiConnectionSettingReceiver --es setstatus disable'
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.15.1"}}
[HTTP] <-- GET /wd/hub/status 200 4 ms - 68
[HTTP] 
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.15.1"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 68
[HTTP] 
[HTTP] --> GET /wd/hub/status
[HTTP] <-- GET /wd/hub/session/4c4a64d0-8a4e-40ac-ab36-d81d22e4c0fd/screenshot 200 5667 ms - 1937792
[HTTP] 
[HTTP] --> POST /wd/hub/session/4c4a64d0-8a4e-40ac-ab36-d81d22e4c0fd/appium/device/toggle_wifi
[HTTP] {}
[debug] [W3C (4c4a64d0)] Calling AppiumDriver.toggleWiFi() with args: ["4c4a64d0-8a4e-40ac-ab36-d81d22e4c0fd"]
[debug] [ADB] Running '/home/atkachev/Android/Sdk/platform-tools/adb -P 5037 -s 192.168.61.40\:5555 shell settings get global wifi_on'
[AndroidDriver] Turning WiFi off
[debug] [ADB] Running '/home/atkachev/Android/Sdk/platform-tools/adb -P 5037 -s 192.168.61.40\:5555 shell am broadcast -a io.appium.settings.wifi -n io.appium.settings/.receivers.WiFiConnectionSettingReceiver --es setstatus disable'
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.15.1"}}
[HTTP] <-- GET /wd/hub/status 200 4 ms - 68
[HTTP] 
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.15.1"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 68
[HTTP] 
[HTTP] --> GET /wd/hub/status`

**Comment by mykola-mokhnach** [comment]
>  I established a wireless connection with my test device

Disabling WiFi also disables adb connectivity in such case. There must be then an alternative path to enable it then (for example, connect via USB). Otherwise I don't see any possibilities to automate such scenario
