### ISSUE TITLE
A session is either terminated or not started

### ISSUE THREAD

**Issue by shivani-rana** [appium/appium#13728]
## Environment

* Appium version (or git revision) that exhibits the issue:1.15.0-beta.1/1.16.0-beta.1
* Last Appium version that did not exhibit the issue (if applicable): 1.14
* Desktop OS/version used to run Appium :MAC OS . 10.14.6
* Node.js version (unless using Appium.app|exe): appium.app
* Npm or Yarn package manager:npm
* Mobile platform/version under test:ios 13.3
* Real device or emulator/simulator: real device/simulator both
* Appium CLI or Appium.app|exe: both

## Details

[debug] [W3C (46f892e3)] Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started
[debug] [W3C (46f892e3)]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:252:15)
[debug] [W3C (46f892e3)]     at /usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:432:15
[debug] [W3C (46f892e3)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [W3C (46f892e3)]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:137:13)
[debug] [W3C (46f892e3)]     at Route.dispatch (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:112:3)
[debug] [W3C (46f892e3)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [W3C (46f892e3)]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:281:22
[debug] [W3C (46f892e3)]     at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:354:14)
[debug] [W3C (46f892e3)]     at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:365:14)
[debug] [W3C (46f892e3)]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:410:3)
[debug] [W3C (46f892e3)]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[debug] [W3C (46f892e3)]     at logger (/usr/local/lib/node_modules/appium/node_modules/morgan/index.js:144:5)
[debug] [W3C (46f892e3)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [W3C (46f892e3)]     at trim_prefix (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
[debug] [W3C (46f892e3)]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:284:7
[debug] [W3C (46f892e3)]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
[debug] [W3C (46f892e3)]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[debug] [W3C (46f892e3)]     at jsonParser (/usr/local/lib/node_modules/appium/node_modules/body-parser/lib/types/json.js:110:7)
[debug] [W3C (46f892e3)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [W3C (46f892e3)]     at trim_prefix (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
[debug] [W3C (46f892e3)]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:284:7
[debug] [W3C (46f892e3)]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
[HTTP] <-- GET /wd/hub/session/46f892e3-21ab-4168-873e-3c708a90cf04 404 56 ms - 2525

**Comment by mykola-mokhnach** [comment]
Please provide the full server log

**Comment by shivani-rana** [comment]
i restarted the server many times and now it starts working. Strange!

Thanks

**Comment by shivani-rana** [comment]
However, while inspecting iOS 13.3 elements, while doing page refresh getting this error :

Matched '/source' to command name 'getPageSource'
[debug] [WD Proxy] Proxying [GET /source] to [GET http://localhost:8100/session/6E9991CD-47DA-4C4B-9890-B63933A4FA01/source] with no body
[debug] [WD Proxy] Got response with status 500: {
[debug] [WD Proxy] "value" : {
[debug] [WD Proxy] "error" : "unknown error",
[debug] [WD Proxy] "message" : "Cannot get 'xml' source of the current application",
[debug] [WD Proxy] "traceback" : ""
[debug] [WD Proxy] },
[debug] [WD Proxy] "sessionId" : "6E9991CD-47DA-4C4B-9890-B63933A4FA01"
[debug] [WD Proxy] }
[debug] [W3C] Matched W3C error code 'unknown error' to UnknownError
[debug] [XCUITest] Taking screenshot with WDA
[debug] [WD Proxy] Matched '/screenshot' to command name 'getScreenshot'
[debug] [WD Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/6E9991CD-47DA-4C4B-9890-B63933A4FA01/screenshot] with no body
[debug] [MJSONWP (73907e02)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot get 'xml' source of the current application
[debug] [MJSONWP (73907e02)] at errorFromW3CJsonCode (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:802:25)
[debug] [MJSONWP (73907e02)] at ProxyRequestError.errorFromW3CJsonCode [as getActualError] (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:685:14)
[debug] [MJSONWP (73907e02)] at JWProxy.getActualError [as command] (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:259:19)

**Comment by shivani-rana** [comment]
server logs 👍 

[debug] [BaseDriver] Event 'newSessionRequested' logged at 1576506653636 (20:00:53 GMT+0530 (India Standard Time))
[Appium] Appium v1.15.0-beta.1 creating new XCUITestDriver (v2.133.1) session
[debug] [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {
[debug] [BaseDriver]   "alwaysMatch": {
[debug] [BaseDriver]     "platformName": "ios",
[debug] [BaseDriver]     "appium:app": “xxxX”,
[debug] [BaseDriver]     "appium:automationName": "XCUITest",
[debug] [BaseDriver]     "appium:deviceName": "iPad",
[debug] [BaseDriver]     "appium:fullReset": false,
[debug] [BaseDriver]     "appium:locationServicesAuthorized": true,
[debug] [BaseDriver]     "appium:newCommandTimeout": 24000000,
[debug] [BaseDriver]     "appium:noReset": true,
[debug] [BaseDriver]     "appium:platformVersion": "13.3",
[debug] [BaseDriver]     "appium:udid": “XXXX”,
[debug] [BaseDriver]     "appium:xcodeOrgId": “XXXX”,
[debug] [BaseDriver]     "appium:xcodeSigningId": "iPhone Developer"
[debug] [BaseDriver]   },
[debug] [BaseDriver]   "firstMatch": [
[debug] [BaseDriver]     {}
[debug] [BaseDriver]   ]
[debug] [BaseDriver] }
[BaseDriver] Session created with session id: 24289537-662c-47b9-899a-c2e9b7ecb2b0
[debug] [XCUITest] Current user: 'shivani.rana'
[debug] [XCUITest] Available devices: XXXX
[debug] [XCUITest] Creating iDevice object with udid ‘XXXX’
[XCUITest] Determining device to run tests on: udid: ‘XXXX’, real device: true
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1576506653654 (20:00:53 GMT+0530 (India Standard Time))
[BaseDriver] Using local app ‘XXXX’
[debug] [BaseDriver] Event 'appConfigured' logged at 1576506653655 (20:00:53 GMT+0530 (India Standard Time))
[debug] [XCUITest] Checking whether app ‘XXXX’ is actually present on file system
[debug] [XCUITest] App is present
[debug] [iOS] Getting bundle ID from app ‘XXXX’: 'com.accenture.cas.ngm.cloud'
[debug] [BaseDriver] Event 'resetStarted' logged at 1576506653655 (20:00:53 GMT+0530 (India Standard Time))
[debug] [XCUITest] Reset: fullReset not set. Leaving as is
[debug] [BaseDriver] Event 'resetComplete' logged at 1576506653656 (20:00:53 GMT+0530 (India Standard Time))
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1576506653923 (20:00:53 GMT+0530 (India Standard Time))
[XCUITest] Setting up real device
[debug] [XCUITest] Verifying application platform
[debug] [XCUITest] CFBundleSupportedPlatforms: ["iPhoneOS"]
[debug] [XCUITest] App ‘XXXX’ is already installed. No need to reinstall.
[debug] [BaseDriver] Event 'appInstalled' logged at 1576506654144 (20:00:54 GMT+0530 (India Standard Time))
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'
[debug] [XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[DevCon Factory] Requesting connection for device XXXX on local port 8100, device port 8100
[debug] [DevCon Factory] Cached connections count: 0
[DevCon Factory] Port #8100 is busy
[DevCon Factory] Successfully requested the connection for XXXX:8100
[debug] [XCUITest] Parsed BUILD_DIR configuration value: ‘/XXXX/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu/Build/Products'
[debug] [XCUITest] Got derived data root: '/Users/shivani.rana/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu'
[debug] [XCUITest] Starting WebDriverAgent initialization with the synchronization key XXXX/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu'
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [WD Proxy] Got response with status 200: {
[debug] [WD Proxy]   "value" : {
[debug] [WD Proxy]     "message" : "WebDriverAgent is ready to accept commands",
[debug] [WD Proxy]     "state" : "success",
[debug] [WD Proxy]     "os" : {
[debug] [WD Proxy]       "name" : "iOS",
[debug] [WD Proxy]       "version" : "13.3",
[debug] [WD Proxy]       "sdkVersion" : "13.0"
[debug] [WD Proxy]     },
[debug] [WD Proxy]     "ios" : {
[debug] [WD Proxy]       "simulatorVersion" : "13.3",
[debug] [WD Proxy]       "ip" : "192.168.1.25"
[debug] [WD Proxy]     },
[debug] [WD Proxy]     "ready" : true,
[debug] [WD Proxy]     "build" : {
[debug] [WD Proxy]       "upgradedAt" : "1576501932096",
[debug] [WD Proxy]       "time" : "Dec 16 2019 19:46:35",
[debug] [WD Proxy]       "productBundleIdentifier" : "com.facebook.WebDriverAgentRunner"
[debug] [WD Proxy]     }
[debug] [WD Proxy]   },
[debug] [WD Proxy]   "sessionId" : "395F6463-8E19-446C-8495-649C989AF579"
[debug] [WD Proxy] }
[debug] [XCUITest] Upgrade timestamp of the currently bundled WDA: 1576501932096
[debug] [XCUITest] Upgrade timestamp of the WDA on the device: 1576501932096
[XCUITest] Will reuse previously cached WDA instance at 'http://localhost:8100/' with 'com.facebook.WebDriverAgentRunner'. Set the wdaLocalPort capability to a value different from 8100 if this is an undesired behavior.
[debug] [XCUITest] Trying to start WebDriverAgent 1 times with 10000ms interval
[debug] [XCUITest] These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1576506656353 (20:00:56 GMT+0530 (India Standard Time))
[XCUITest] Using provided WebdriverAgent at 'http://localhost:8100/'
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [WD Proxy] Got response with status 200: {
[debug] [WD Proxy]   "value" : {
[debug] [WD Proxy]     "message" : "WebDriverAgent is ready to accept commands",
[debug] [WD Proxy]     "state" : "success",
[debug] [WD Proxy]     "os" : {
[debug] [WD Proxy]       "name" : "iOS",
[debug] [WD Proxy]       "version" : "13.3",
[debug] [WD Proxy]       "sdkVersion" : "13.0"
[debug] [WD Proxy]     },
[debug] [WD Proxy]     "ios" : {
[debug] [WD Proxy]       "simulatorVersion" : "13.3",
[debug] [WD Proxy]       "ip" : "192.168.1.25"
[debug] [WD Proxy]     },
[debug] [WD Proxy]     "ready" : true,
[debug] [WD Proxy]     "build" : {
[debug] [WD Proxy]       "upgradedAt" : "1576501932096",
[debug] [WD Proxy]       "time" : "Dec 16 2019 19:46:35",
[debug] [WD Proxy]       "productBundleIdentifier" : "com.facebook.WebDriverAgentRunner"
[debug] [WD Proxy]     }
[debug] [WD Proxy]   },
[debug] [WD Proxy]   "sessionId" : "395F6463-8E19-446C-8495-649C989AF579"
[debug] [WD Proxy] }
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1576506656368 (20:00:56 GMT+0530 (India Standard Time))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.accenture.cas.ngm.cloud","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[debug] [WD Proxy] Got response with status 200: {"value":{"sessionId":"F7A858A9-0ADE-4B90-B553-C246739C458D","capabilities":{"device":"ipad","browserName":"Accenture Cloud","sdkVersion":"13.3","CFBundleIdentifier":"com.accenture.cas.ngm.cloud"}},"sessionId":"F7A858A9-0ADE-4B90-B553-C246739C458D"}
[WD Proxy] Determined the downstream protocol as 'W3C'
[debug] [BaseDriver] Event 'wdaSessionStarted' logged at 1576506659012 (20:00:59 GMT+0530 (India Standard Time))
[debug] [BaseDriver] Event 'wdaStarted' logged at 1576506659012 (20:00:59 GMT+0530 (India Standard Time))
[XCUITest] Skipping setting of the initial display orientation. Set the "orientation" capability to either "LANDSCAPE" or "PORTRAIT", if this is an undesired behavior.
[debug] [BaseDriver] Event 'orientationSet' logged at 1576506659013 (20:00:59 GMT+0530 (India Standard Time))
[Appium] New XCUITestDriver session created successfully, session 24289537-662c-47b9-899a-c2e9b7ecb2b0 added to master session list
(node:11206) TimeoutOverflowWarning: 24000000000 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1576506659013 (20:00:59 GMT+0530 (India Standard Time))
[debug] [W3C (24289537)] Cached the protocol value 'W3C' for the new session 24289537-662c-47b9-899a-c2e9b7ecb2b0
[debug] [W3C (24289537)] Responding to client with driver.createSession() result: {"capabilities":{"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"platformName":"ios","app”:”XXXX”,”automationName":"XCUITest","deviceName":"iPad","fullReset":false,"locationServicesAuthorized":true,"newCommandTimeout":24000000,"noReset":true,"platformVersion":"13.3","udid”:”XXXX”,”xcodeOrgId”:”XXXX”,”xcodeSigningId":"iPhone Developer"}}
[HTTP] <-- POST /wd/hub/session 200 5381 ms - 673
[HTTP] 
[BaseDriver] Shutting down because we waited 24000000 seconds for a command
[DevCon Factory] Releasing connections for XXXX device on any port number
[DevCon Factory] Found cached connections to release: [“XXXX:8100"]
[DevCon Factory] Releasing the listener for ‘XXXX:8100'
[debug] [DevCon Factory] Cached connections count: 0
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[Appium] Closing session, cause was 'New Command Timeout of 24000000 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
[Appium] Removing session 24289537-662c-47b9-899a-c2e9b7ecb2b0 from our master session list
[HTTP] --> GET /wd/hub/session/24289537-662c-47b9-899a-c2e9b7ecb2b0
[HTTP] {}
[debug] [W3C (24289537)] Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started
[debug] [W3C (24289537)]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:252:15)
[debug] [W3C (24289537)]     at /usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:432:15
[debug] [W3C (24289537)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [W3C (24289537)]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:137:13)
[debug] [W3C (24289537)]     at Route.dispatch (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:112:3)
[debug] [W3C (24289537)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [W3C (24289537)]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:281:22
[debug] [W3C (24289537)]     at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:354:14)
[debug] [W3C (24289537)]     at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:365:14)
[debug] [W3C (24289537)]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:410:3)
[debug] [W3C (24289537)]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[debug] [W3C (24289537)]     at logger (/usr/local/lib/node_modules/appium/node_modules/morgan/index.js:144:5)
[debug] [W3C (24289537)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [W3C (24289537)]     at trim_prefix (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
[debug] [W3C (24289537)]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:284:7
[debug] [W3C (24289537)]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
[debug] [W3C (24289537)]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[debug] [W3C (24289537)]     at jsonParser (/usr/local/lib/node_modules/appium/node_modules/body-parser/lib/types/json.js:110:7)
[debug] [W3C (24289537)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [W3C (24289537)]     at trim_prefix (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
[debug] [W3C (24289537)]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:284:7
[debug] [W3C (24289537)]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
[HTTP] <-- GET /wd/hub/session/24289537-662c-47b9-899a-c2e9b7ecb2b0 404 3 ms - 2525
[HTTP]

**Comment by mykola-mokhnach** [comment]
> (node:11206) TimeoutOverflowWarning: 24000000000 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
> [BaseDriver] Shutting down because we waited 24000000 seconds for a command

The error is expected. You need an appropriate timeout value (by 0 no timeout for new commands is applied)

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
