### ISSUE TITLE
Appium taking long time for test execution 

### ISSUE THREAD

**Issue by rajkumar-cp** [appium/appium#13735]
## The problem

Test scripts were taking too long time for execution in iOS simulators. Could you please check and let me know if this is an issue from appium end. If not can you please guide me to a proper channel for this issue.

Could you please take a look at the logs and let me know if this is an issue with respect to appium or app file or xcode .

## Environment

* Appium version (or git revision) that exhibits the issue:1.15.1
* Last Appium version that did not exhibit the issue (if applicable): 1.12.0
* Desktop OS/version used to run Appium: mac OS catalina 10.15.12
* Node.js version (unless using Appium.app|exe): 13.2.0
* Npm or Yarn package manager: Npm
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium.exe

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/rajkumar-cp/7d51dc5e92b0e48fd2890ae7cedad628

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
There might be many things, which cause slowness. Please read though the [set](https://appiumpro.com/editions/19) of articles on Appium Pro and update your client code according to these recommendations.

**Comment by rajkumar-cp** [comment]
@mykola-mokhnach 

For an ipa file the existing strategy seems to be working fine without any issue. Were you not able to find any weird or disturbing messages in the logs i have attached above w.r.t appium. If you could help me with this i will change my focus to xcode because we recently updated our xcode version too.

**Comment by mykola-mokhnach** [comment]
It is impossible to make any conclusions by only having the log. You should investigate and "extract" the problematic parts, which take the most of the execution time, fins common patterns there and try the proposed workarounds/optimisations.

**Comment by mykola-mokhnach** [comment]
Closing the issue for now. Will reopen it after we can get more details on the topic described above
