### ISSUE TITLE
Cannot start session on android real device

### ISSUE THREAD

**Issue by gpiszczek** [appium/appium#13736]
## The problem

When trying to start new session on Android 9 real device appium gets stuck waiting for `io.appium.settings` app to start, waiting in a loop calling `adb shell pgrep io\\.appium\\.settings`. It happens always after phones reboot.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): 1.11.1
* Desktop OS/version used to run Appium: macOS mojave
* Node.js version (unless using Appium.app|exe): v13.3.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Xiaomi Mi A1, Android 9
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: cli

## Details

It happed that io.appium.settings cannot start due to exception (shown in logs) thrown when trying to start Foreground service (commit https://github.com/appium/io.appium.settings/commit/9f0f96078fd005009e755f968f09700f3f76e747). It manages to start session from time to time but it seems that it is strictly because of race condition between `am start` and `pgrep` invocations.

## Link to Appium logs

I am attaching appium logs and logcat showing mentioned exception 
https://gist.github.com/gpiszczek/45fb0aa6c665a1b5775777508f69d040

**Comment by mykola-mokhnach** [comment]
I assume there are some security limitations on this particular phone, which make the process crashing. Perhaps, the miOS itself requires some additional setup to allow the app to run in foreground on top of what `adb` allows.

Try to run the test on another phone type as a possible workaround.

**Comment by gpiszczek** [comment]
I am in no way android developer but looking at https://developer.android.com/guide/components/services , especially:
> Note: If your app targets API level 26 or higher, the system imposes restrictions on using or creating background services unless the app itself is in the foreground. If an app needs to create a foreground service, the app should call startForegroundService(). That method creates a background service, but the method signals to the system that the service will promote itself to the foreground. Once the service has been created, the service must call its startForeground() method within five seconds.

makes me think that it is not specific to the phone I am using (API version 28). I will test with io.appium.settings using startForegoundService() instead of startService() and report back my findings.

**Comment by mykola-mokhnach** [comment]
The Settings app does provide the foreground service: https://github.com/appium/io.appium.settings/blob/master/app/src/main/java/io/appium/settings/ForegroundService.java

Although, it only works if allowed explicitly

**Comment by gpiszczek** [comment]
That's ok but shouldn't the app use `startForegroundService()` instead of `startService()` to run it?

As for permissions io.appium.settings has `android.permission.FOREGROUND_SERVICE` granted, gist follow: https://gist.github.com/gpiszczek/ba716b8c955c26c272bd39c3c3c0dc86 .

What can I do to help get it fixed?

**Comment by mykola-mokhnach** [comment]
> That's ok but shouldn't the app use startForegroundService() instead of startService() to run it?

https://github.com/appium/io.appium.settings/blob/81fe9aaee3fe57361e55ceaf291e43c4c79ef367/app/src/main/java/io/appium/settings/ForegroundService.java#L64

> What can I do to help get it fixed?

You have the source code. Feel free to debug and fix it if there are bugs. I would be happy to answer your questions (of course if I can).

**Comment by gpiszczek** [comment]
Tested with startForegroundService() instead of startService() and works for me.

**Comment by KazuCocoa** [comment]
hm, okay, thanks. @gpiszczek 

Internally, the `startForegroundService` also calls startService, but it could be customised by manufactures. (Current logic works no issue on my phone (Nokia, Android 9), so it might happen in some manufactures)

Did you change https://github.com/appium/io.appium.settings/blob/master/app/src/main/java/io/appium/settings/Settings.java#L64 to `startForegroundService(ForegroundService.getForegroundServiceIntent(Settings.this))`?

**Comment by gpiszczek** [comment]
@KazuCocoa exactly. As I mentioned in https://github.com/appium/appium/issues/13736#issuecomment-566963955 it looks like proper method to start foreground service on android >= O. Provided that I'm little suprised that I'm first to encounter this problem. In my setup the problem happened only after phone reboot (with io.appium.settings app not running). The funny thing was that despite of exception, it occasionally passed the `pgrep io\.appium\.settings` check due to race between `am start` and `pgrep` calls.

Have you checked on some phone with O or greater that it actually worked as intented with startService() (not throwing the exception and keeping `io.appium.settings` running)?

**Comment by KazuCocoa** [comment]
Yes, so we merged and released the change. (I did not have Xiaomi device, so I hadn't tested the behaviour on Xiaomi though)

It seems the behaviour depends on devices (manufactures). 
https://github.com/appium/io.appium.settings/pull/51#issuecomment-568227797
