### ISSUE TITLE
how to close App?

### ISSUE THREAD

**Issue by sky205** [appium/appium#13733]
## Environment

* Appium version (or git revision) that exhibits the issue: appium-mac-driver 1.7.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS
* Node.js version (unless using Appium.app|exe): v10.15.3
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: Mac Application test
* Real device or emulator/simulator: --
* Appium CLI or Appium.app|exe: Appium CLI

## Details

I was trying close application, but the driver haven't similar method or function can use.
what i only found is deleteSession, but it can't close app but only close appium session
I think closeApp() is basic function, is there have any way in appium-mac-driver?

## Code To Reproduce Issue [ Good To Have ]
actually, I just extends MacDriver, then write my own closeApp() as below code:

```
const { MacDriver } = require('appium-mac-driver') 
const _appiumSupport = require('appium-support')

class BaseDriver extends MacDriver {
  async closeApp() {
    await _appiumSupport.process.killProcess(this.caps.app);
  }
}

exports.BaseDriver = BaseDriver
```

**Comment by mykola-mokhnach** [comment]
We've recently added a possibility to execute any shell command from Mac OS driver.

Install the most recent appium@beta and use the following client code for command execution:

```python

script = """
echo hello
"""
result = driver.execute_script(script)
assert result['stdout'].strip() == 'hello'
assert result['code'] == 0
```

See https://github.com/appium/appium-mac-driver/blob/89bef72207152a9c22800f25482b11b8fc6668f4/lib/commands/execute.js#L12 for more details on the supported options and https://github.com/appium/appium-mac-driver/blob/89bef72207152a9c22800f25482b11b8fc6668f4/lib/commands/execute.js#L23 on the returned result structure

**Comment by mykola-mokhnach** [comment]
Also you need to make sure the `system_shell` server [feature](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/security.md) is enabled.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
