### ISSUE TITLE
Click failed at (x, y) coordinates, though the coordinates are within screen size.

### ISSUE THREAD

**Issue by liviudanu-ellation** [appium/appium#13737]
## The problem

When trying to perform a tap by coordinates, i get the following exception:
`org.openqa.selenium.InvalidElementStateException: Click failed at (1102, 1107) coordinates`, though screen size returned by appium is (1440, 2560)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.0, 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): 1.14.2
* Desktop OS/version used to run Appium: MacOS Mojave v10.14.6
* Node.js version (unless using Appium.app|exe): v11.10.0
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: Android 6, 8, 9
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: Both

## Link to Appium logs

https://gist.github.com/liviudanu-ellation/dd591579b2fca81f28966e680537dd44

**Comment by mykola-mokhnach** [comment]
Unfortunately this is the limitation of UIA2 framework, which we cannot influence. Also, the screen size of (1440, 2560) is the absolute size in pixels. For applications it might be scaled and cut due to toolbars presence.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
