### ISSUE TITLE
Appium VS DRM scrrendhot: need help 

### ISSUE THREAD

**Issue by bouabdaldam** [appium/appium#13730]
Hello, 
in our application, a DRM content is played continuously and we are not able de select our elements as appium is not able de detect them. we are using an ID selector. getelementbyaccessibility_id(ressource_id).
what we understood, is that Appium need in order to detect elements to make a screenshot, but when DRM content is played screenshot are not authorized.
what can we do pls. thanks for advices

**Comment by mykola-mokhnach** [comment]
Please provide proper issue description according to the given template, including the full server log. We cannot help nothing without having this information
