### ISSUE TITLE
getPerformanceData() for networkinfo returning same timestamp stats for every call. 

### ISSUE THREAD

**Issue by Eshakk** [appium/appium#13746]
## The problem

I'm expecting it to return network stats in the bucket interval that it is querying. But when I call this API, I'm getting the same timestamps and values of stats until I restart my android emulator. Is this intentional ? How can we query at different timestamps ?

## Environment

* Appium version (or git revision) that exhibits the issue:
Appium 1.15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
MacOS Catalina 10.15.2
* Node.js version (unless using Appium.app|exe):
13.3.0
* Npm or Yarn package manager:
* Mobile platform/version under test:
Android 10
* Real device or emulator/simulator:
Emulated Nexus 5
* Appium CLI or Appium.app|exe:

## Details
I'm trying to automate an app in which audio and video content is exchanged.

## Link to Appium logs

https://gist.github.com/Eshakk/bfb86de4c6d780e588f4ac444c276f8a

**Comment by mykola-mokhnach** [comment]
Do you get different results if the dumpsys command above is executed manually?

**Comment by Eshakk** [comment]
I have run dumpsys netstats command two times and the results match of same timestamp:
```
ident=[{type=WIFI, subType=COMBINED, networkId="AndroidWifi", metered=false, defaultNetwork=true}] uid=10137 set=DEFAULT tag=0x0
    NetworkStatsHistory: bucketDuration=7200
      st=1576706400 rb=2280 rp=57 tb=2320 tp=58 op=0
  ident=[{type=WIFI, subType=COMBINED, networkId="AndroidWifi", metered=false, defaultNetwork=true}] uid=10137 set=FOREGROUND tag=0x0
    NetworkStatsHistory: bucketDuration=7200
      st=1576706400 rb=3923155 rp=7505 tb=1064875 tp=6538 op=0
```
and
```
ident=[{type=WIFI, subType=COMBINED, networkId="AndroidWifi", metered=false, defaultNetwork=true}] uid=10137 set=DEFAULT tag=0x0
    NetworkStatsHistory: bucketDuration=7200
      st=1576706400 rb=2280 rp=57 tb=2320 tp=58 op=0
  ident=[{type=WIFI, subType=COMBINED, networkId="AndroidWifi", metered=false, defaultNetwork=true}] uid=10137 set=FOREGROUND tag=0x0
    NetworkStatsHistory: bucketDuration=7200
      st=1576706400 rb=3923155 rp=7505 tb=1064875 tp=6538 op=0
```

**Comment by mykola-mokhnach** [comment]
There is no magic there - android driver calls the same command. Let us know if there is any way to enforce data refresh for it

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
