### ISSUE TITLE
Appium 1.15.1, java.lang.IllegalStateException: UiAutomation not connected! on Android Devices

### ISSUE THREAD

**Issue by udaykittu** [appium/appium#13741]
Getting an error while trying to automate Android apps with Appium UI Automator 2

Appium Server: Command line logs

[debug] [UiAutomator2] No app capability. Assuming it is already on the device
[debug] [UiAutomator2] Performing shallow cleanup of automation leftovers
[debug] [UiAutomator2] The following obsolete sessions are still running: ["b596fa07-ff7e-4a8d-9008-c0c5da1fa3d6"]
[debug] [UiAutomator2] Cleaning up the obsolete sessions
[debug] [UiAutomator2] No obsolete sessions have been detected (500 - "{\"sessionId\":\"b596fa07-ff7e-4a8d-9008-c0c5da1fa3d6\",\"value\":{\"error\":\"unknown error\",\"message\":\"java.lang.IllegalStateException: UiAutomation not connected!\",\"stacktrace\":\"java.lang.IllegalStateException: UiAutomation not connected!\\n\\tat android.app.UiAutomation.throwIfNotConnectedLocked(UiAutomation.java:1043)\\n\\tat android.app.UiAutomation.getServiceInfo(UiAutomation.java:399)\\n\\tat androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:115)\\n\\tat androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)\\n\\tat io.appium.uiautomator2.utils.Device.getUiDevice(Device.java:25)\\n\\tat io.appium.uiautomator2.core.UiAutomatorBridge.getUiAutomation(UiAutomatorBridge.java:52)\\n\\tat io.appium.uiautomator2.core.UiAutomation.<init>(UiAutomation.java:32)\\n\\tat io.appium.uiautomator2.core.UiAutomation.getInstance(UiAutomation.java:37)\\n\\tat io.appium.uiautomator2.model.NotificationListener.<init>(NotificationListener.java:42)\\n\\tat io.appium.uiautomator2.model.NotificationListener.getInstance(NotificationListener.java:47)\\n\\tat io.appium.uiautomator2.handler.DeleteSession.safeHandle(DeleteSession.java:36)\\n\\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:38)\\n\\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:252)\\n\\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:242)\\n\\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\\n\\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\\n\\tat io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)\\n\\tat io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)\\n\\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)\\n\\tat io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\\n\\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\\n\\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)\\n\\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)\\n\\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)\\n\\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:552)\\n\\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466)\\n\\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)\\n\\tat io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)\\n\\tat io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)\\n\\tat java.lang.Thread.run(Thread.java:764)\\n\"}}")
[debug] [ADB] Running '/Users/udaykumarraju.s/Library/Android/sdk/platform-tools/adb -P 5037 -s ce091609d9348f3101 shell am force-stop io.appium.uiautomator2.server.test'
[UiAutomator2] Starting UIAutomator2 server 4.3.0
[UiAutomator2] Using UIAutomator2 server from '/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.3.0.apk' and test from '/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk'
[UiAutomator2] Waiting up to 30000ms for UiAutomator2 to be online...
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","ce091609d9348f3101","shell","am","instrument","-w","io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner"]
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[debug] [Instrumentation] io.appium.uiautomator2.server.test.AppiumUiAutomator2Server:
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[debug] [WD Proxy] Got response with status 200: {"sessionId":"None","value":{"ready":true,"message":"UiAutomator2 Server is ready to accept commands"}}
[debug] [UiAutomator2] The initialization of the instrumentation process took 3170ms
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://localhost:8200/wd/hub/session] with body: {"capabilities":{"firstMatch":[{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"android","appActivity":"","appPackage":"","automationName":"UIAutomator2","deviceName":"OnePlus 6","noReset":true,"platformVersion":"9","udid":"ce091609d9348f3101"},"platformName":"android","appActivity":"","appPackage":"","automationName":"UIAutomator2","deviceName":"ce091609d9348f3101","noReset":true,"platformVersion":"9","udid":"ce091609d9348f3101","deviceUDID":"ce091609d9348f3101"}],"alwaysMatch":{}}}
[WD Proxy] Got an unexpected response with status 500: {"sessionId":null,"value":{"error":"session not created","message":"java.lang.IllegalStateException: UiAutomation not connected!","stacktrace":"io.appium.uiautomator2.common.exceptions.SessionNotCreatedException: java.lang.IllegalStateException: UiAutomation not connected!\n\tat io.appium.uiautomator2.handler.NewSession.safeHandle(NewSession.java:59)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:38)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:252)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:242)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannel...
[debug] [W3C] Matched W3C error code 'session not created' to SessionNotCreatedError
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[debug] [WD Proxy] Matched '/' to command name 'deleteSession'
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
[debug] [ADB] Running '/Users/udaykumarraju.s/Library/Android/sdk/platform-tools/adb -P 5037 -s ce091609d9348f3101 shell am force-stop '
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8200 
[debug] [ADB] Running '/Users/udaykumarraju.s/Library/Android/sdk/platform-tools/adb -P 5037 -s ce091609d9348f3101 forward --remove tcp\:8200'
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1576664354749 (15:49:14 GMT+0530 (IST))
[debug] [W3C] Encountered internal error running command: A new session could not be created. Details: java.lang.IllegalStateException: UiAutomation not connected!
[debug] [W3C] io.appium.uiautomator2.common.exceptions.SessionNotCreatedException: java.lang.IllegalStateException: UiAutomation not connected!
[debug] [W3C] 	at io.appium.uiautomator2.handler.NewSession.safeHandle(NewSession.java:59)
[debug] [W3C] 	at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:38)
[debug] [W3C] 	at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:252)
[debug] [W3C] 	at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:242)
[debug] [W3C] 	at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)
[debug] [W3C] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [W3C] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [W3C] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[debug] [W3C] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[debug] [W3C] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [W3C] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [W3C] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[debug] [W3C] 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
[debug] [W3C] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
[debug] [W3C] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
[debug] [W3C] 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
[debug] [W3C] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [W3C] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [W3C] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[debug] [W3C] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
[debug] [W3C] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [W3C] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [W3C] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
[debug] [W3C] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
[debug] [W3C] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
[debug] [W3C] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:552)
[debug] [W3C] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466)
[debug] [W3C] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
[debug] [W3C] 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
[debug] [W3C] 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
[debug] [W3C] 	at java.lang.Thread.run(Thread.java:764)
[debug] [W3C] Caused by: java.lang.IllegalStateException: UiAutomation not connected!
[debug] [W3C] 	at android.app.UiAutomation.throwIfNotConnectedLocked(UiAutomation.java:1043)
[debug] [W3C] 	at android.app.UiAutomation.getServiceInfo(UiAutomation.java:399)
[debug] [W3C] 	at androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:115)
[debug] [W3C] 	at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
[debug] [W3C] 	at io.appium.uiautomator2.utils.Device.getUiDevice(Device.java:25)
[debug] [W3C] 	at io.appium.uiautomator2.core.UiAutomatorBridge.getUiAutomation(UiAutomatorBridge.java:52)
[debug] [W3C] 	at io.appium.uiautomator2.core.UiAutomation.<init>(UiAutomation.java:32)
[debug] [W3C] 	at io.appium.uiautomator2.core.UiAutomation.getInstance(UiAutomation.java:37)
[debug] [W3C] 	at io.appium.uiautomator2.model.NotificationListener.<init>(NotificationListener.java:42)
[debug] [W3C] 	at io.appium.uiautomator2.model.NotificationListener.getInstance(NotificationListener.java:47)
[debug] [W3C] 	at io.appium.uiautomator2.handler.NewSession.safeHandle(NewSession.java:52)
[debug] [W3C] 	... 30 more
[debug] [W3C] 
[HTTP] <-- POST /wd/hub/session 500 8198 ms - 4342
[HTTP]

**Comment by mykola-mokhnach** [comment]
This seems to be the problem with the device itself, because the exception is coming from the downstream framework. Could you also attach the logcat output?

**Comment by mykola-mokhnach** [comment]
You could also try the solution from https://github.com/appium/appium/issues/7377#issuecomment-469989240

**Comment by udaykittu** [comment]
Duplicate of #7377
