### ISSUE TITLE
add viewmatcher selector to clients

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#13747]
Support `using="-android viewmatcher", value="<JSON>"`

https://github.com/appium/appium-espresso-driver/pull/516

like https://github.com/appium/appium/issues/12372

Acceptance Criteria:
* [x] Ruby
* [x] Python
* [x] Java
* [x] C# 
* [x] WebdriverIO ?
* [ ] wd ?

**Comment by o-x-y-g-e-n** [comment]
@KazuCocoa Almost done with the python implementation. Still kinda new here and trying to figure out how internal works, so I wanted to write functional test cases for viewmatcher, and appium version(1.15.1) & Espresso Server(v.1.16.0), it doesn't have the code for viewmatcher, i guess.

So what to do to get latest espresso server (master)? 
Thanks.

**Comment by mykola-mokhnach** [comment]
The corresponding changes in espresso driver have been published in version 1.19.0

**Comment by o-x-y-g-e-n** [comment]
Working on python client

**Comment by o-x-y-g-e-n** [comment]
Don't really understand the need to implement this method below
https://github.com/appium/python-client/blob/a2b9440af4dbb07bcb395a7631754844142e34cd/appium/webdriver/extensions/search_context/android.py#L59

`onData()` or `onView()` will throw an exception, if it finds multiple elements matching the same criteria. 

Let me know what you guys think? @KazuCocoa @mykola-mokhnach

**Comment by KazuCocoa** [comment]
_find elements_ returns elements as List and does not throw an exception unlike find element. _find element_ should throw an exception if no element found, but _find elements_ returns an empty list.

**Comment by mykola-mokhnach** [comment]
Link https://github.com/appium/appium-dotnet-driver/pull/408

**Comment by mykola-mokhnach** [comment]
I believe we have it where needed
