### ISSUE TITLE
Increment image diff

### ISSUE THREAD

**Issue by BrightHai** [appium/appium#13742]
Hi appium team, i read [two blogs](https://appiumpro.com/editions/98) about image diff provided by appium pro, we developed a [increment image diff](https://github.com/Meituan-Dianping/vision-diff) algorithm, it changes our mobile testing, wish it will be included by appium

**Comment by mykola-mokhnach** [comment]
Hi @BrightHai 
Do you have any concrete architecture proposals we could review?

**Comment by mykola-mokhnach** [comment]
Closed because of no response
