### ISSUE TITLE
Unable to find displayedElement and visible is false even when it is true.

### ISSUE THREAD

**Issue by hokyungh** [appium/appium#13745]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0-beta.3
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: macOS 10.14.6
* Node.js version (unless using Appium.app|exe): 10.17.0
* Npm or Yarn package manager: 6.4.1
* Mobile platform/version under test:  iOS 12.4
* Real device or emulator/simulator: Real Device IPhone 6s plus
* Appium CLI or Appium.app|exe: Appium Desktop

## Details

If necessary, describe the problem you have been experiencing in more detail.
In the appium Desktop it is able to inspect the element, but with class chain I was not able to find out with 
```
**/XCUIElementTypeButton[`name == "Cancel" AND visible == true`]
```
Even though the inspector says it is true.
However, I was able to find the element with 
```
**/XCUIElementTypeButton[`name == "Cancel" AND visible == false`]
```
See the attached screenshots
[inspector](https://github.com/hokyungh/appium/blob/master/Screen%20Shot%202019-12-18%20at%201.28.09%20PM.png)
[class chain query true](https://github.com/hokyungh/appium/blob/master/Screen%20Shot%202019-12-18%20at%201.28.29%20PM.png)
[not found](https://github.com/hokyungh/appium/blob/master/Screen%20Shot%202019-12-18%20at%201.28.52%20PM.png)
[class chain query false](https://github.com/hokyungh/appium/blob/master/Screen%20Shot%202019-12-18%20at%202.06.29%20PM.png)
[elements found](https://github.com/hokyungh/appium/blob/master/Screen%20Shot%202019-12-18%20at%202.06.36%20PM.png)

## Link to Appium logs
```
[BaseDriver] Waiting up to 0 ms for condition
[WD Proxy] Matched '/elements' to command name 'findElements'
[WD Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/B4F14AD1-EB54-47CE-B41D-0CFE5B17AD48/elements] with body: {"using":"class chain","value":"**/XCUIElementTypeButton[`name == \"Cancel\" AND visible == true`]"}
[Xcode]     t =  3757.87s Get all elements bound by accessibility element for: Elements matching predicate '(wdName == "Cancel" AND isWDVisible == 1) AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0)'
[Xcode] 
[Xcode]     t =  3757.88s     Requesting snapshot of accessibility hierarchy for app with pid 52
[Xcode] 
[Xcode]     t =  3758.10s     Find: Descendants matching type Button
[Xcode] 
[Xcode]     t =  3758.11s     Find: Elements matching predicate '(wdName == "Cancel" AND isWDVisible == 1) AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0)'
[Xcode] 
[WD Proxy] Got response with status 200: {"value":[],"sessionId":"B4F14AD1-EB54-47CE-B41D-0CFE5B17AD48"}
[MJSONWP (d4297697)] Responding to client with driver.findElements() result: []
[HTTP] <-- POST /wd/hub/session/d4297697-f6aa-496a-8092-ace43d2642d0/elements 200 289 ms - 74
[HTTP] 
```
## Code To Reproduce Issue [ Good To Have ]
This is hard since I can't share the app, but on certain places one of button is visible,  but it is not able to find with that flag.

**Comment by KazuCocoa** [comment]
How was the page source?

**Comment by mykola-mokhnach** [comment]
> Mobile platform/version under test: iOS 12.4

It is recommended to test iOS 12 with Xcode 10 SDK. There were already several reports about XCTest bugs if the test is being perform using Xcode 11 SDK.

**Comment by ki4070ma** [comment]
[FYI] I could reproduce this.

https://github.com/appium/python-client/pull/477

[Case] test_find_element_by_isvisible
https://github.com/appium/python-client/blob/master/test/functional/ios/search_context/find_by_ios_predicate_tests.py

**Comment by hokyungh** [comment]
I have rebuilt my project with XCode 10.3 and command line tool of Xcode 10.3. However, it seems that issue still appears. I was able to find the element, but it doesn't seem to think that element is visible. 
@KazuCocoa here is page source for that button
```
<XCUIElementTypeButton type="XCUIElementTypeButton" name="Cancel" label="Cancel" enabled="true" visible="true" x="12" y="31" width="51" height="22"/>
```
However, still I can't find it with 
```
**/XCUIElementTypeButton[`name == "Cancel" AND visible == true`]
```

**Comment by KazuCocoa** [comment]
Perhaps,  it needs to debug with https://github.com/appium/WebDriverAgent via Xcode to track the process, unfortunately, if the cause is return value by XCTest framework or Appium's internal tweaks.

btw, what about turning `simpleIsVisibleCheck` capability on?

**Comment by hokyungh** [comment]
@KazuCocoa  It works with simpleIsVisibleCheck. Is this supposed to be the recommended way? Thanks for the solution though!

**Comment by KazuCocoa** [comment]
It strongly depends on your environment.
WDA has some workaround to fix visibilities for older OS versions, but XCTest also has been improved. So, if the `simpleIsVisibleCheck` worked for you, you can use it. But I cannot say the capability is always true, unfortunately.

**Comment by tulasikrishan89** [comment]
visible == 1 not working for iphone 12 pro using predicate text

**Comment by ganjarpanji** [comment]
visible == 1 or visible == 'true' none of this work on predicate locator. any insight to solve this @mykola-mokhnach  ? tried add `simpleIsVisibleCheck` capability but its remain not work.

**Comment by vzenzo** [comment]
This still does not work at all, even "simpleIsVisibleCheck" set to true
