### ISSUE TITLE
 Appium unexpectedly ended the connection. It may have quit abnormally.

### ISSUE THREAD

**Issue by rajkumar-cp** [appium/appium#13740]
## The problem

On performing click operation the exception occurs.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.51.1
* Last Appium version that did not exhibit the issue (if applicable): 1.14.0
* Desktop OS/version used to run Appium: NA
* Node.js version (unless using Appium.app|exe): NA
* Npm or Yarn package manager: NA
* Mobile platform/version under test: 13.0
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: NA

## Details

We were using sauce environment for test execution.

## Link to Appium logs

For 1.15.1 version: https://gist.github.com/rajkumar-cp/b36bb215e82f82e4bf1932ebcf71b47f

For 1.14.0 version: https://gist.github.com/rajkumar-cp/4f70ff6bc2236820eb3b6f686e051d5e

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
At which line of the attached log the issue occurs?

**Comment by rajkumar-cp** [comment]
Last line while performing the click action

**Comment by mykola-mokhnach** [comment]
> 07:47:34	VERBOSE:	[HTTP] 
> 07:47:34	VERBOSE:	[HTTP] --> POST /wd/hub/session/5584cfdf-157f-43ef-910a-c42f8487b4e4/element/0B020000-0000-0000-DC02-000000000000/click
> 07:47:34	VERBOSE:	[HTTP] {"id":"0B020000-0000-0000-DC02-000000000000"}
> 07:47:34	VERBOSE:	[MJSONWP (5584cfdf)] Driver proxy active, passing request on via HTTP proxy
> 07:47:34	VERBOSE:	[debug] [XCUITest] Executing command 'proxyReqRes'
> 07:47:34	VERBOSE:	[debug] [WD Proxy] Matched '/wd/hub/session/5584cfdf-157f-43ef-910a-c42f8487b4e4/element/0B020000-0000-0000-DC02-000000000000/click' to command name 'click'
> 07:47:34	VERBOSE:	[debug] [WD Proxy] Proxying [POST /wd/hub/session/5584cfdf-157f-43ef-910a-c42f8487b4e4/element/0B020000-0000-0000-DC02-000000000000/click] to [POST http://127.0.0.1:5701/session/F02A2D7D-E8A3-49BF-B686-0813092D317E/element/0B020000-0000-0000-DC02-000000000000/click] with body: {"id":"0B020000-0000-0000-DC02-000000000000"}

These are the last lines and I don't observe any errors so far

**Comment by rajkumar-cp** [comment]
@mykola-mokhnach 

Yeah immediately after this operation we were receiving an exception. Please do not close this issue. I have placed one execution if any case fails with the same exception i will try to provide more clarity on this issue later today.

**Comment by mykola-mokhnach** [comment]
> Yeah immediately after this operation we were receiving an exception

Which exception, where to see it?

**Comment by rajkumar-cp** [comment]
java.lang.Exception: Exception at ObjectListingPage.clickItem : Appium unexpectedly ended the connection. It may have quit abnormally. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 120.21 seconds
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'Aspire1931', ip: '10.8.19.187', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_161'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{testobject_user_id=mfilesit, testobject_app_id=120, testobject_platform_name=iOS, noReset=true, testobject_test_report_url=https://app.testobject.com/#/mfilesit/mfilesios/appium/executions/13896, testobjectApiKey=abcde, testobject_device_name=iPad Air 2, testobject_session_creation_timeout=900000, testobject_suite_name=19.12.8578.6 IOS, testobject_device_session_id=f5e2892e-d154-49c9-95d2-478e6f21cb80, deviceName=e43aa539e8d4bf6186afe4e9056c57fba24bff8e, platform=MAC, webDriverAgentUrl=http://127.0.0.1:5705, cacheId=16e8cd64f08, testobject_test_report_id=13896, noReset =true, testobject_appium_version=1.15.1, platformVersion=13.1.2, webStorageEnabled=false, automationName=XCUITest, browserName=, takesScreenshot=true, additionalWebviewBundleIds=[4W9U94HF9P.4W9U94HF9P*], javascriptEnabled=true, platformName=iOS, udid=e43aa539e8d4bf6186afe4e9056c57fba24bff8e, deviceContextId=81058a6d-a2f4-42e4-9dc7-808cb64f4ead, networkConnectionEnabled=false, orientation=PORTRAIT, realDevice=true, testobject_test_name=MFiles 19.12.8578.6 AddExternalObjectToOffline-iPad, commandTimeouts={default=60000}, appiumVersion=1.15.1, testobject_device=iPad_Air_2_13_real, bundleId=com.m-files.M-Files, databaseEnabled=false, processArguments={args=[test_darkmode]}, usedCachedDevice=false, testobject_project_id=mfilesios, testobject_test_report_api_url=https://app.testobject.com/api/rest/v2/reports/13896, locationContextEnabled=false, name=test, recordDeviceVitals=true, autoGrantPermissions=true, deviceOrientation=portrait, testobject_api_key=AD28A26636EE415CA5A7762CE73791B8, testobject_cache_device=true, testobject_test_live_view_url=https://app.testobject.com/#/mfilesit/mfilesios/appium/view/13896?dc=EU}]
Session ID: cc192736-1426-4580-925f-11449b7d4d52
	at MFMA.Factories.ObjectListingPage.clickItem(ObjectListingPage.java:202)
	at MFMA.Tests.SmokeTestCases.AddExternalObjectToOffline(SmokeTestCases.java:3225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.openqa.selenium.WebDriverException: Appium unexpectedly ended the connection. It may have quit abnormally. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 120.21 seconds
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'Aspire1931', ip: '10.8.19.187', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_161'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{testobject_user_id=mfilesit, testobject_app_id=120, testobject_platform_name=iOS, noReset=true, testobject_test_report_url=https://app.testobject.com/#/mfilesit/mfilesios/appium/executions/13896, testobjectApiKey=xxxxx, testobject_device_name=iPad Air 2, testobject_session_creation_timeout=900000, testobject_suite_name=19.12.8578.6 IOS, testobject_device_session_id=f5e2892e-d154-49c9-95d2-478e6f21cb80, deviceName=e43aa539e8d4bf6186afe4e9056c57fba24bff8e, platform=MAC, webDriverAgentUrl=http://127.0.0.1:5705, cacheId=16e8cd64f08, testobject_test_report_id=13896, noReset =true, testobject_appium_version=1.15.1, platformVersion=13.1.2, webStorageEnabled=false, automationName=XCUITest, browserName=, takesScreenshot=true, additionalWebviewBundleIds=[4W9U94HF9P.4W9U94HF9P*], javascriptEnabled=true, platformName=iOS, udid=e43aa539e8d4bf6186afe4e9056c57fba24bff8e, deviceContextId=81058a6d-a2f4-42e4-9dc7-808cb64f4ead, networkConnectionEnabled=false, orientation=PORTRAIT, realDevice=true, testobject_test_name=MFiles 19.12.8578.6 AddExternalObjectToOffline-iPad, commandTimeouts={default=60000}, appiumVersion=1.15.1, testobject_device=iPad_Air_2_13_real, bundleId=com.m-files.M-Files, databaseEnabled=false, processArguments={args=[test_darkmode]}, usedCachedDevice=false, testobject_project_id=mfilesios, testobject_test_report_api_url=https://app.testobject.com/api/rest/v2/reports/13896, locationContextEnabled=false, name=test, recordDeviceVitals=true, autoGrantPermissions=true, deviceOrientation=portrait, testobject_api_key=AD28A26636EE415CA5A7762CE73791B8, testobject_cache_device=true, testobject_test_live_view_url=https://app.testobject.com/#/mfilesit/mfilesios/appium/view/13896?dc=EU}]
Session ID: cc192736-1426-4580-925f-11449b7d4d52
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:51)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:327)
	at io.appium.java_client.DefaultGenericMobileElement.execute(DefaultGenericMobileElement.java:46)
	at io.appium.java_client.MobileElement.execute(MobileElement.java:1)
	at io.appium.java_client.ios.IOSElement.execute(IOSElement.java:1)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:85)
	at MFMA.Factories.ObjectListingPage.clickItem(ObjectListingPage.java:194)
	... 13 more

**Comment by mykola-mokhnach** [comment]
> java.lang.Exception: Exception at ObjectListingPage.clickItem : Appium unexpectedly ended the connection. It may have quit abnormally.

This exception is coming from TestObject/SauceLabs. Please contact their customer support and provide the necessary job details there, so they can extract the internal debugging data. Unfortunately, we cannot do much from Appium side without having this data.

**Comment by NSDInesh30** [comment]
HI RajKumar,

Is this issue fixed for you. I am also facing similar issue.
Could you please let me your insight on this issue and fix which solved this issue

I have raised this issue saucelabs/testObject, but still not able to find the root cause and solution for this
