### ISSUE TITLE
Cannot start appium server programmatically

### ISSUE THREAD

**Issue by G-prog** [appium/appium#13749]
I am trying to build a Test Appium Framework
The last stage is to make the server launch programmatically in JAVA
I tried to implement every solution i could find but didn't work.
I need to know if this an issue with the latest version of Appium or there is a fix available for this

## Environment

* Appium version (or git revision) that exhibits the issue: v1.7.0
* Desktop OS/version used to run Appium:MacOSX(10.14.6)
* Node.js version (unless using Appium.app|exe):12.12.0
* Mobile platform/version under test:Android
* Real device or emulator/simulator:Emulator
* Appium CLI or Appium.app|exe:Appium CLI
*TestNG :7.0.0
*JAVA:1.8

## Code To Reproduce Issue
https://github.com/G-prog/Appium-Framework.git

**Comment by mykola-mokhnach** [comment]
- Appium 1.7 is out of date. Please use the most recent server version
- Please provide the actual server logs and errors stacktrace(s)

**Comment by G-prog** [comment]
- I updated the appium version to 1.15.1
- Also please check this code, it includes the code to start the server programmatically
https://github.com/G-prog/Appium-Framework.git
-I cannot see any traces when i run the testng.xml in eclipse with a code to start the server programmatically 

<img width="612" alt="Screen Shot 2019-12-20 at 10 44 23" src="https://user-images.githubusercontent.com/54137657/71223148-60e38e80-2316-11ea-9c5b-63e4c4098a93.png">

**Comment by mykola-mokhnach** [comment]
> I cannot see any traces when i run the testng.xml in eclipse with a code to start the server programmatically

The log output is normally written to the process stdout. Also the log level should be set to DEBUG. Unfortunately, we cannot help nothing without this information.

**Comment by mykola-mokhnach** [comment]
Closed as incomplete

**Comment by G-prog** [comment]
For this issue I found a solution that worked well for me:
Here is the piece of code:


`public class Driver_init {

	public static AndroidDriver<AndroidElement>driver;
    public static AppiumDriverLocalService appiumService;
    public static String appiumUrl;
  
@Before
	public static AndroidDriver<AndroidElement> capabilities(String appName) throws IOException, InterruptedException {
	
		startServer();

		FileInputStream fis=new FileInputStream(System.getProperty("user.dir")+"/src/main/java/resources/global.properties");
		//Access the file global.properties through a java object
		Properties prop=new Properties();
		prop.load(fis);	//this step reads the 'fis' object->loads the file
		
		File appDir = new File("src/main/java/resources");
		File app=new File (appDir,(String)prop.get(appName));//prop.get fetches the key argument(name of the app in this case)
		DesiredCapabilities capabilities=new DesiredCapabilities();
		capabilities.setCapability(MobileCapabilityType.DEVICE_NAME,"Android Device");
		//capabilities.setCapability(MobileCapabilityType.DEVICE_NAME,(String)prop.get("device"));
		capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME,"uiautomator2");
		capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT,"60");
		capabilities.setCapability(MobileCapabilityType.APP,app.getAbsolutePath());
		driver=new AndroidDriver<AndroidElement>(new URL("http://127.0.0.1:4723/wd/hub"),capabilities);
		driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
		return driver ;	
	}


public static void startServer()
{
	 appiumService = AppiumDriverLocalService.buildDefaultService();
     appiumService.start();
     appiumUrl = appiumService.getUrl().toString();
     System.out.println("Appium Service URL Address : - "+ appiumUrl);

}


@After
public void End() {
              
               driver.quit();
               appiumService.stop();
}
`
