### ISSUE TITLE
DOS command to start Appium with success, but you can not perform a lookup element

### ISSUE THREAD

**Issue by zengguidong** [appium/appium#13744]
DOS command to start Appium with success, but you can not perform a lookup element：
    driver.find_element_by_xpath("//*[@text='ticket']").click()

Source code：
def start_appium(port=4723, udid=""):
    a = os.popen('netstat -ano | findstr "%s" '% port)
    time.sleep(2)
    t1 = a.read()
    if "LISTENING" in t1:
        print("appium start：%s" % t1)
    else:
        os.system("appium -a 127.0.0.1 -p %s -U %s --no-reset" % (port, udid))

def get_desired_caps(devicesName='Samsung'):
    curpath = os.path.dirname(os.path.realpath(__file__))
    yamlpath = os.path.join(curpath, "wingon.yaml")
    f = open(yamlpath, "r", encoding="utf-8")
    a = f.read()
    f.close()
    d = yaml.load(a,Loader=yaml.FullLoader)
    for i in d:
        if devicesName in i["desc"]:
            devicesName = i['desired_caps']['udid']
            start_appium(port=i['port'], udid=devicesName)
            return (i['desired_caps'], i['port'])

@threads(3)
def run_app(devicesName):
    desired_caps = get_desired_caps(devicesName)
    print(desired_caps)

    driver = webdriver.Remote('http://127.0.0.1:%s/wd/hub' % desired_caps[1], desired_caps[0])
    time.sleep(2)
    driver.find_element_by_xpath("//*[@text='ticket']").click()

if __name__ == "__main__":
    devices = ["Samsung"]
    for i in devices:
        run_app(devicesName=i)

**Comment by mykola-mokhnach** [comment]
Please provide proper issue description according to the reporting template along with the full server log

**Comment by zengguidong** [comment]
Environmental：
Appium 1.15 
Android 7.0，8.0

problem：
start Appium with success，app has been opened，bug cannot locate element

**Comment by mykola-mokhnach** [comment]
Which element cannot be located? We'd also need the page source and the server log

**Comment by zengguidong** [comment]
problem：
Lower version 1.4 of appium can locate elements, and upgrading to 1.15 will not locate elements

A simple example：
from appium import webdriver
import time
desired_caps = {}
desired_caps['platformName'] = 'Android'
desired_caps['platformVersion'] = '9.0'
desired_caps['deviceName'] = '3ST0218B09004547' #GSL0217619001615 192.168.254.101:5555
desired_caps['automationName'] = 'Appium'
desired_caps['appPackage'] = 'com.wingontravel.m'
desired_caps['appActivity'] = 'com.wingontravel.m.Splash'
desired_caps['appWaitActivity']='com.wingontravel.m.MainActivity'
desired_caps['appWaitDuration']='60000'
print('aa')
time.sleep(2)
driver = webdriver.Remote('http://127.0.0.1:4723/wd/hub', desired_caps)
time.sleep(6)
driver.find_element("xpath","//*[@text='火車票']").click()
time.sleep(2)
driver.quit()

server log：
D:\Python3\python.exe I:/Automation/APP_Wingontravel/cases/frbs/test33.py
aa
Traceback (most recent call last):
  File "I:/Automation/APP_Wingontravel/cases/frbs/test33.py", line 18, in <module>
    driver.find_element("xpath","//*[@text='火車票']").click()
  File "D:\Python3\lib\site-packages\appium\webdriver\webdriver.py", line 276, in find_element
    'value': value})['value']
  File "D:\Python3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\Python3\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "D:\Python3\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "D:\Python3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: A session is either terminated or not started

**Comment by mykola-mokhnach** [comment]
If one carefully read through the server log than he would see that now UiAutomator2 is the default automation backend for Android instead of UIA1. It is possible it generates slightly different page source, which requires updates on the client side.

You could still enforce the usage of the old backend by setting `automationName` to `UiAutomator1`, although this is not recommended on Android 6+ and will lead to another issues, which cannot be resolved.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
