### ISSUE TITLE
Appium cant doesent worh with latest Android System Webview

### ISSUE THREAD

**Issue by FirstAM** [appium/appium#13758]
## The problem

Hello. Having problems with devices that have Android 9+ and the latest version of Android
When Android System Webview is updated to version 79.0.3945.93, there is no way to work with any WebView pages, but when I lower the version of Android System Webview to 74.0.3729.186, everything works fine, as before
I cannot use the Webview context, because I have only one NativaApp context

I think many Appium users may soon encounter this problem.

Have any idea how to fix this?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.0
* Last Appium version that did not exhibit the issue (if applicable):  1.15.0
* Desktop OS/version used to run Appium: Ubuntu 18.04
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI 

## Details

Responce get source 
[get_source.txt](https://github.com/appium/appium/files/3991438/get_source.txt)

## Link to Appium logs

[appium_logs_77.txt](https://github.com/appium/appium/files/3991439/appium_logs_77.txt)

**Comment by mykola-mokhnach** [comment]
Where exactly the error is in the attached log? I don't observe any calls to context switch API

**Comment by FirstAM** [comment]
Perhaps you didn’t understand me correctly, I didn’t mean that there was an error during context switching, the problem is that I can’t interact with WebView in any way. 

The available_contexts method returns only NativeApp, this is not a WebView context to switch the context and work with it, that's why I touched on this side of the question

The main problem is that now I can not work with the new version of  Android System Webview , 
I used to work without changing the context with WebView, indicating the index of class elements as necessary locators, but now i cant switch context and can't work with this WebView page like i done this early

**Comment by mykola-mokhnach** [comment]
Is the web view debuggable via Chrome remote debugger?

**Comment by FirstAM** [comment]
> Is the web view debuggable via Chrome remote debugger?

 Chrome remote debugger - No browsers detected.

**Comment by mykola-mokhnach** [comment]
It might be that the web view is not configured properly for debugging. If Chrome debugger does not see it then we would not be able to do it for sure.

**Comment by FirstAM** [comment]
> It might be that the web view is not configured properly for debugging. If Chrome debugger does not see it then we would not be able to do it for sure.

When I go through the Chrome browser, the remote debugger correctly detects the webview.

The strange thing is that the old version of WebView appium worked correctly, perhaps you have not yet met with the new version of the Android System Webview application. 

Can I clarify how appium looked for elements in Webview without switching contexts?

**Comment by mykola-mokhnach** [comment]
> Chrome remote debugger - No browsers detected.
> When I go through the Chrome browser, the remote debugger correctly detects the webview.

So, it is detected or not? 
As far as I remember Google has changed the name of the web view process recently, so it makes sense to try it with appium@beta and/or check the `ps` output in general while the web view is active

**Comment by FirstAM** [comment]
Webview not detected in testing Appp , and detected in Mobile Chrome App

**Comment by mykola-mokhnach** [comment]
Did you try appium@beta?

**Comment by oka-saputra** [comment]
Hi mykola, I'm facing those webview issue relate to org.openqa.selenium.NoSuchElementException. 

Below are capability setting of my environment
        dc.setCapability("noReset", "true");
        dc.setCapability("fullReset", "false");
        dc.setCapability("reportDirectory", reportDirectory);
        dc.setCapability("reportFormat", reportFormat);
        dc.setCapability("testName", testName);
        dc.setCapability(MobileCapabilityType.UDID, "RR8M50AK3YL");
        dc.setCapability(MobileCapabilityType.DEVICE_NAME, "A50");
        dc.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
        dc.setCapability(MobileCapabilityType.AUTOMATION_NAME, 
         AutomationName.ANDROID_UIAUTOMATOR2);
        dc.setCapability(AndroidMobileCapabilityType.APP_PACKAGE, "com.grabtaxi.passenger");
        dc.setCapability(AndroidMobileCapabilityType.APP_ACTIVITY, 
        "com.grab.pax.newface.presentation.newface.NewFace");
        driver = new AndroidDriver<>(new URL("http://localhost:4724/wd/hub"), dc);
        driver.setLogLevel(Level.INFO);

FYI, this case is used to work before by using following xpath code         driver.findElement(By.xpath("//android.view.View[@text='Get Health Consultation']")).click();  
and its accessible on the element by using UI Automator as well
![image](https://user-images.githubusercontent.com/56011424/71659560-a1152900-2d7a-11ea-9b9e-b5b0254d3b1d.png)
however the code is suddenly stop working and attached the log from appium server for your reference. 
[appium-server-logs.txt](https://github.com/appium/appium/files/4015356/appium-server-logs.txt)

**Comment by mykola-mokhnach** [comment]
@oka-saputra Your issue is unrelated. Please create a new report for it (if there are no duplicates)

**Comment by mykola-mokhnach** [comment]
Closed because of no response
