### ISSUE TITLE
Appium 1.15.1 is unable to identify the Xamarin elements

### ISSUE THREAD

**Issue by reply2sagar** [appium/appium#13753]
## The problem

iOS app is built using Xamarin library. But When we use Appium XCUITest inspector to identify the elements, it does not identify some elements in app. Elements that are shown in Xamarin form pop up are not being identified. Other elements (not on pop up) are being identified. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Mac OS 10.15
* Node.js version (unless using Appium.app|exe): 10.5
* Npm or Yarn package manager:NPM
* Mobile platform/version under test: iOS 12, iOS 13
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Both

## Details
Xamarin Nuget Package version - 4.8

We tried 2 xamarin controls - Picker and Table. But both did not work

Picker - 
The picker that appium fails to identify is using below UI components.
"ContentView" => "StackLayout" => "Picker"

Table- 
Appium identifies the table but fails to identify rows in it. 
 <XCUIElementTypeTable type="XCUIElementTypeTable" name="Empty list" label="Empty list" enabled="true" visible="true" x="30" y="143" width="354" height="110"/>

**Comment by mykola-mokhnach** [comment]
Appium simply reflects what is visible to the iOS accessibility. This means the corresponding fixes should be done either on your app side or Xamarin framework itself.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
