### ISSUE TITLE
iOS 13.3 : send keys method entering given text twice

### ISSUE THREAD

**Issue by shivani-rana** [appium/appium#13756]
## Environment

* Appium version (or git revision) that exhibits the issue: 1.15 beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:10.14.6
* Node.js version (unless using Appium.app|exe):appium.app
* Npm or Yarn package manager:npm
* Mobile platform/version under test: ios 13.3
* Real device or emulator/simulator: real device and simultor
* Appium CLI or Appium.app|exe: appium CLI and appium.app

## Details

while entering text through send keys method in appium project, given text is getting entered twice. no issue is coming in logs as well. it worked absolutely fine with previous ios versions

**Comment by mykola-mokhnach** [comment]
Please attach the server log

**Comment by mykola-mokhnach** [comment]
Closed as incomplete
