### ISSUE TITLE
`driver.toggle_location_services()` fails to toggle location

### ISSUE THREAD

**Issue by gillett-hernandez** [appium/appium#13755]
## The problem

i was calling `driver.toggle_location_services()`, and the keycode sequence failed to toggle the location.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Mac OS 10.15.2
* Node.js version (unless using Appium.app|exe): 12.9.1
* Npm or Yarn package manager: 6.10.3
* Mobile platform/version under test: android 9
* Real device or emulator/simulator: samsung galaxy s8
* Appium CLI or Appium.app|exe: appium cli

## Details

i'm testing on a samsung galaxy s8, with android 9.0 installed
i inspected the keycode sequence being sent to the device when i call the method, and it might be incorrect.
based on the code at:
https://github.com/appium/appium-android-driver/blob/master/lib/commands/network.js#L173

it sends `22` -> `22` -> `19`, then `23`
which correspond to
`right`, `right`, `up`, then `center`
the last `right` and `up` before clicking center are unnecessary however, because on android 9.0 the location toggle is already selected by sending `right` only once.
i'm not sure the best fix, maybe filtering by api level again, with api_level >= 28 and changing the `seq` variable to be just [`22`].

strangely enough, the toggle_location_services method works for the most part on android 10, though the back press code isn't enough to take you back to the app.

## Link to Appium logs

https://gist.github.com/gillett-hernandez/36143845c26dc447cba8501c25860a23

## Code To Reproduce Issue [ Good To Have ]

```
from appium.webdriver.webdriver import WebDriver
from appium import webdriver

EXECUTOR = "192.168.1.150:4723/wd/hub"

desired_capabilities = {
    "app": "redacted",
    "platformName": "Android",
    "platformVersion": "9.0",
    "automationName": "UIAutomator2",
    "deviceName": "Android",
    "appWaitActivity": "redacted",
    "adbExecTimeout": 90000,
    "newCommandTimeout": 600,
}

driver = webdriver.Remote(command_executor=EXECUTOR, desired_capabilities=desired_capabilities, direct_connection=True)


driver.toggle_location_services()
```

**Comment by mykola-mokhnach** [comment]
This piece of code has never been particularly reliable. I'd rather send the key codes on the client side.
Thanks for the PR though.
