### ISSUE TITLE
appium use "chromeDriverPort" instead of "chromedriverPort" when argument "--chromedriver-port" is added

### ISSUE THREAD

**Issue by usagikengood** [appium/appium#13767]
It's a minor issue, and easy to find out:

command to start: "appium --chromedriver-port 8100"
[Appium] Welcome to Appium v1.16.0
[Appium] Non-default server args:
[Appium]   **chromeDriverPort**: 8100
[Appium] Appium REST http interface listener started on 0.0.0.0:4723

and the log:
[AndroidDriver] The 'chromeDriverPort' capability is deprecated. Please use 'chromedriverPort' instead

**Comment by mykola-mokhnach** [comment]
Could you please explain what is wrong there?

**Comment by imurchie** [comment]
Understood. The capability that it sets is really `chromedriverPort` but it sets `chromeDriverPort`, so it does not have an effect.

**Comment by imurchie** [comment]
Hmm. That is more dire than it needs to sound. The mis-cased option is handled.

https://github.com/appium/appium-android-driver/blob/d8685916a452a2f205d4d945d806015cc29bb4d8/lib/commands/context.js#L344-L347
