### ISSUE TITLE
[WDA][XCTest] Siri Service has issue on real device iOS 13.x.x

### ISSUE THREAD

**Issue by hieupd** [appium/appium#13768]
## Environment
* Mobile platform/version under test: iOS 13.1.3 and 13.3
* Real device or emulator/simulator: Real device
* Xcode version : Xcode 11.2

## Details

This problem occurs when we call api @"/url" then WDA was suspended. . when we investigating and debugging, WDA hangs up at this line (on class XCUIDevice+FBHelpers.m) 

**[siriService performSelector:NSSelectorFromString(@"activateWithVoiceRecognitionText:")
  withObject:text]**

##Note: 
We do not have this problem with iOS version lower than 13.0

**Comment by mykola-mokhnach** [comment]
The Siri call for `/url` endpoint is anyway an ugly workarourd for the known XCTest bug related to `openUrl` functionality. Feel free to propose a PR if you have a better workaround for it.

**Comment by hieupd** [comment]
I noticed iOS 13 currently has an issue with Siri on real device.  When we double touch home button to open Siri then the number of Siri app , it can open 2/3 . We think this is a bug in the core of Apple's iOS 13 and waiting Apple fix issue this

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing more that can be done here on Appium side.
Closed as third party issue.
