### ISSUE TITLE
Not able to Find Status Bar ( XCUIElementTypeStatusBar ) not present in PageSource.

### ISSUE THREAD

**Issue by rahulcode** [appium/appium#13764]
## The problem

Not able to Find Status Bar ( XCUIElementTypeStatusBar ) not present in PageSource.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): 1.13.0
* Desktop OS/version used to run Appium: 10.14.6 (18G87) / Xcode Version 11.2.1 (11B500)
* Node.js version (unless using Appium.app|exe): 1.15.1
* Npm or Yarn package manager: 6.2.0
* Mobile platform/version under test: iOS 13.2.2
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

**LOGS ::** https://gist.github.com/rahulcode/730f12e2cd68e7486f97ed3e19f5ade2
**Page Source :** https://gist.github.com/rahulcode/b9adc79fcfdbfeaf31eb6c91e33aa780

Steps

1) Just inspect the elements or use any XPath having  //XCUIElementTypeStatusBar

Behavior: Not able to find element with any xpath like above.

Question 
Is this a XCUITest issue ?
If yes, Please can you share steps or learning resource to find and debug this issues so that I myself can put full observaations ?
Thanks

**Comment by mykola-mokhnach** [comment]
> Is this a XCUITest issue ?

Yes, it is. WebDriverAgent fully relies on XCTest output while building the page source

> If yes, Please can you share steps or learning resource to find and debug this issues so that I myself can put full observaations ?

I usually perform WebDriverAgent debugging on Simulator (you'll need to get a Simulator build for that). 

The code responsible for snapshots retrieval can be found in https://github.com/appium/WebDriverAgent/blob/07dbb5ff721021bc298e5406da20d3a428e00b4f/WebDriverAgentLib/Categories/XCUIElement%2BFBUtilities.m#L84

The code that builds XML page source from the given snapshot:
https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Utilities/FBXPath.m

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by gromanas** [comment]
Hello @mykola-mokhnach ! I have faced the same issue today. I saw that with iOS 11.4 I was able to locate `XCUIElementTypeStatusBar` with Appium desktop v1.16.0 but on with iOS 12 and above I wasn't able to locate that element. Please check also in the screenshots below: 
**iOS11.4**
<img width="1228" alt="iOS11 4" src="https://user-images.githubusercontent.com/48865319/79890426-23982600-8408-11ea-9ccd-de4c948a0d37.png"> 
**iOS12 and above e.g.(13.0)**
<img width="1211" alt="iOS13 0" src="https://user-images.githubusercontent.com/48865319/79890968-f5671600-8408-11ea-8b91-3fd80ca164dd.png">

**Comment by mykola-mokhnach** [comment]
Since iOS 12 Apple made the status bar is the part of system application. You could switch between applications using `defaultActiveApplication` setting
