### ISSUE TITLE
iOS 13: getContexts Does Not Wait for Remote Debugger Applications to Connect

### ISSUE THREAD

**Issue by Dan-Maor** [appium/appium#13770]
## The problem

Reproducible on iOS 13.3.1 (multiple devices), could not reproduce on iOS 12.4.
When attempting to get the list of contexts for the first time after starting to test a hybrid application only NATIVE_APP is returned on the first attempt. 

The contexts list is returned correctly after requesting first (only NATIVE_APP is returned), sleeping for a second and then requesting them again.

Happens with both UIWebView and WKWebView objects.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: MacOS 10.14.6
* Node.js version (unless using Appium.app|exe): v10.15.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Details

It looks like there is a delay in receiving the _rpc_applicationConnected event when the remote debugger is started, and when the first request to the remote debugger to list the contexts is received the applications list is not ready, and thus an empty array is returned.

## Link to Appium logs

https://gist.github.com/Dan-Maor/149ad6377e8f2d465748ff1bf587ea97

**Comment by mykola-mokhnach** [comment]
cc @imurchie

**Comment by mykola-mokhnach** [comment]
I would say the `getContexts` call itself should not be blocking. Although, for the very first invocation in scope of the current session it probably makes sense to wait for remote debugger initialisation.

**Comment by imurchie** [comment]
What does "WAITING MANUALLY" mean?

It is entirely possible that when the first request is sent, the Web Inspector has nothing to return, so it will return nothing. Nothing in the logic on Appium's side has changed in this regard, and we've always recommended using something like (taken directly from the `appium-xcuitest-driver` [test suite](https://github.com/appium/appium-xcuitest-driver/blob/master/test/functional/basic/basic-e2e-specs.js#L300-L330)):
```js
const contexts = await retryInterval(100, 1000, async function () {
  // on some systems (like Travis) it takes a while to load the webview
  const contexts = await driver.contexts();
  contexts.length.should.be.at.least(2);
  return contexts;
});
```

This happens on some systems more than others. You can see a run on Travis, with iOS 12.2, at https://travis-ci.org/appium/appium-xcuitest-driver/jobs/627738701#L2345-L2475

**Comment by Dan-Maor** [comment]
"WAITING MANUALLY" means either adding a sleep in the script before retrying or debugging a script and waiting for the applications list to be received before the second attempt.

**Comment by jzaratei** [comment]
Hi, I'm getting the same issue with IOS v.13.3 and appium 1.16.0-beta.3

**Environment**
Appium version (or git revision) that exhibits the issue: 1.16.0-beta.3
Last Appium version that did not exhibit the issue (if applicable): N/A
Desktop OS/version used to run Appium: MacOS catalina 10.15.2
Node.js version (unless using Appium.app|exe): 12.12.0
Npm or Yarn package manager: npm
Mobile platform/version under test: iOS
Real device or emulator/simulator: Real Device
Appium CLI or Appium.app|exe: CLI

**Link to Appium logs**
https://gist.github.com/jzaratei/59fc95879efe70ac28b90a5842a90159

Thanks for the support.

**Comment by imurchie** [comment]
I can only say that this is normal. The client code should be polling for the connection to the Web Inspector. Waiting on the server side has _never_ happened and would be a bad idea in the general case.

**Comment by jzaratei** [comment]
> What does "WAITING MANUALLY" mean?
> 
> It is entirely possible that when the first request is sent, the Web Inspector has nothing to return, so it will return nothing. Nothing in the logic on Appium's side has changed in this regard, and we've always recommended using something like (taken directly from the `appium-xcuitest-driver` [test suite](https://github.com/appium/appium-xcuitest-driver/blob/master/test/functional/basic/basic-e2e-specs.js#L300-L330)):
> 
> ```js
> const contexts = await retryInterval(100, 1000, async function () {
>   // on some systems (like Travis) it takes a while to load the webview
>   const contexts = await driver.contexts();
>   contexts.length.should.be.at.least(2);
>   return contexts;
> });
> ```
> 
> This happens on some systems more than others. You can see a run on Travis, with iOS 12.2, at https://travis-ci.org/appium/appium-xcuitest-driver/jobs/627738701#L2345-L2475

Hi, I'm having this issue with the command `getContextHandles()` from io.appium.java_client. I usually do something like this, to retrieve all the context available in a real device test:

`Set contextsAvailable =AppiumDriverManager.getDriver().getContextHandles();`

But, like it's been report by Dan-Maor,  I'm always getting only "NATIVE_APP" the first time I run this line.  If I run it a second time, then I got the webview context needed.
So, I think it must be an issue related to the latest IOS OS version, 13.3 in my case, because this is not happening for versions 12.4 and below.

Let me know if I have to report this issue to the java-client github.
Thanks for the support.

**Comment by mykola-mokhnach** [comment]
Closed because of https://github.com/appium/appium-xcuitest-driver/pull/1135
