### ISSUE TITLE
Appium support to Roku-Webdriver

### ISSUE THREAD

**Issue by tom20c** [appium/appium#13775]
Since, Roku has released their official driver Roku-WebDriver to automating UI tests for Roku apps.

https://developer.roku.com/docs/developer-program/dev-tools/automated-channel-testing/web-driver.md

Is there any plan for Appium, to implement Roku WebDriver apis, in near future.

**Comment by mykola-mokhnach** [comment]
Unfortunately we don't have such plans for the future since the Appium team is quite limited in resources. Although, we are always happy to accept pull requests if anyone wants to contribute.
