### ISSUE TITLE
driver.execute is not available in driver list. 

### ISSUE THREAD

**Issue by waqaszulfiqar** [appium/appium#13788]
## Issue 
I want to implement the scroll down the page and using this command

driver.execute('mobile: scroll', {direction: 'down'});

## Error 
ReferenceError: element is not defined

But driver.execute is not showing up in the list. 
Should I have to import any library or something? 
I have just started the mobile automation. 

## Environment

* Appium Android
* Webdriver.io

**Comment by mykola-mokhnach** [comment]
The error is expected. This endpoint requires the `element` argument to be provided. Please use appium forum to ask questions
