### ISSUE TITLE
Chrome driver auto download is not working properly

### ISSUE THREAD

**Issue by YoLo9803** [appium/appium#13781]
## The problem

Appium chrome driver auto-download feature is failing to find the corresponding version of chrome driver in Android 6.0

## Environment

* Appium version :1.15.1, 1.16.0
* Desktop OS/version used to run Appium: Windows 1903
* Node.js version (unless using Appium.app|exe): 12.13.1
* Npm or Yarn package manager: latest
* Mobile platform/version under test: Android 6.0/Googl APIs(API 23)
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: CLI

## Details

Appium failed to find the corresponding version of chrome driver in Android 6.0(chrome version 44.0.2403).
I've tried to copy the chrome driver 2.20(which support chrome 43.0.2357) to the appium-chromedriver directory, but it still didn't work.
At last, I specified the chromedriver-executable path to the path of chrome driver 2.20, it worked.

But what i want is support android 6.0 to Android Q dynamically, and Android 6.0(API 23) is the only version that is not proper functioning, i don't know if it is a bug.

## Link to Appium logs

https://gist.github.com/YoLo9803/23d34115b1f24e470df73afa69cf3511

## Code To Reproduce Issue

appium -a 127.0.0.1 -p 4723 --allow-insecure chromedriver_autodownload --chromedriver-port 9515

Using robotFramework to run any script

[4723.txt](https://github.com/appium/appium/files/4014801/4723.txt)

**Comment by mykola-mokhnach** [comment]
It looks like Chrome 44 is an intermediate browser version, which is covered by an older chromedriver build. This does not match to the current logic, where all the newer chrome versions have the corresponding drivers. I'll add the support of such combination

**Comment by YoLo9803** [comment]
Ok, thanks for answering!

**Comment by mykola-mokhnach** [comment]
Please keep the issue open to track the progress

**Comment by mykola-mokhnach** [comment]
The change has been pushed to appium@beta
