### ISSUE TITLE
Console Domain was Not Found Error displaying on switching Contexts(Native-->Webview) in Hybrid App

### ISSUE THREAD

**Issue by Phaneendhr** [appium/appium#13780]
## The problem
We automated Hybrid App , where we were able to successfully Perform Switching the Contexts between Native and Webview and Vice Versa in iOS Platform

We are using Corporate VPN setup configuration to Launch the APP and perform actions in App
We are using Mobile Iron and Pulse Secure as VPN and SSO as Single Sign on for Authentication in the Mobile App

Recently our Organisation Moved from Mobile Iron to VMWare Citrix Intelligent Hub (Workspace One) , when we are executing the same Scripts

It is showing both the Contexts , but Unfortunately while switching it throws below Error

**selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'Console' domain was not found**

This is Happening only in New Configuration Setup, even we tried with c#,python different language bindings to understand its an Langaguge Binding Issue or any other

Appium Version we tried is : 12.1,12.2,12.0, 1.11.1 even lower version also

These Scripts we are running on Headspin Cloud Platform

**Comment by mykola-mokhnach** [comment]
Please attach the full server log. also make sure you use the most recent server version (preferably appium@beta)
