### ISSUE TITLE
[FLUTTER] Unable to connect with Dart Observatory when doing automation on real iOS device

### ISSUE THREAD

**Issue by ahashmi24** [appium/appium#13783]
## Failing to make a connection with Dart Observatory due to error TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14)

**Note:**  I am able to run my test on the iOS simulator by using same setup and on the same environment.

## Environment

Appium verison: 1.16.0
iOS verison:  13.1.2
xcode version: 11.1

## Link to Appium logs
https://gist.github.com/ahashmi24/bf77b21e30ba2e509e421e4442883842

## Using the below capabilities:
capabilities.setCapability(IOSMobileCapabilityType.BUNDLE_ID, "com.example.datePicket");
		   capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "Flutter");
		    capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
		    capabilities.setCapability(MobileCapabilityType.ORIENTATION, "PORTRAIT");
		   // capabilities.setCapability("connectHardwareKeyboard", false);
		    capabilities.setCapability(MobileCapabilityType.UDID, "*********************");
		    capabilities.setCapability("includeSafariInWebviews", true);
		    capabilities.setCapability("platformVersion", "13.1.2");
		    capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 8 plus");
		    capabilities.setCapability("noReset", true);
		    driver = new IOSDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);

**Comment by mykola-mokhnach** [comment]
Please report the issue to https://github.com/truongsinh/appium-flutter-driver
