### ISSUE TITLE
Appium getting started works, but client.remote hangs on with my activity that has a login

### ISSUE THREAD

**Issue by MagicPoulp** [appium/appium#13786]
## The problem

I have run with success the getting started using the Android emulator. It works 100%.
http://appium.io/docs/en/about-appium/getting-started/?lang=en

But if I use my commercial app that has a login during the startup activity, the client.remote() command never returns.

I need to enter the letters for the login. I need interaction. But I cannot since the remote() never returns.

Do I have to not block on remote and do things in parallel?

## Environment

* Appium version (or git revision) that exhibits the issue:
appium 1.15.1
webdriverio: 5.18.2

* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
android 9

* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

**Comment by mykola-mokhnach** [comment]
Please describe your problem properly (steps to reproduce, the actual and the expected result) and attach the full server log

**Comment by MagicPoulp** [comment]
In the appium log it did not know which activity to pick and kept retrying.
I specified the activity manually and it worked.

This is annoying since the name of the activity has a generated hash. I wish to pick the first activity it finds.

**Comment by MagicPoulp** [comment]
It looks like this:

> Possible activities, to be checked: 'md5d0db2e8cfc61ece45132f7cc44405c09.SplashActivity', 'com.company.product.md5d0db2e8cfc61ece45132f7cc44405c09.SplashActivity'
> [debug] [ADB] Getting focused package and activity
> [debug] [ADB] Running '/home/homer/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys window windows'
> [debug] [ADB] Found package: 'com.company.product' and fully qualified activity name : 'md5819db72dd063416097553592a197be56.MainActivity'
> [debug] [ADB] Incorrect package and activity. Retrying.

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md

Appium allows to use wildcards in activity names. For example, you could set `appWaitActivity` to `com.company.product.*.SplashActivity`

**Comment by MagicPoulp** [comment]
OK thanks.

my guess is that the MainActivity that is found by default is said invalid because the name does not start with a dot.

And the wildcard does not work for the same reason.
I tried *.SplashActivity and it says that .*.SplashActivity was not found which is true since my activitty doesn ot start with a dot.

Still searching.

**Comment by MagicPoulp** [comment]
I reopened, maybe somone nice understands why the wildcard is not accepted by the raw adb command.

BUt it works if I replace the star with the hash present in the manifest.

**Comment by MagicPoulp** [comment]
I added the appWaitActivity with *.SplashActivity, and I get this:

[UiAutomator2] Starting 'com.company.product/md5d0db2e8cfc61ece45132f7cc44405c09.SplashActivity and waiting for 'com.company.product/*.SplashActivity'
[debug] [ADB] Running '/home/homer/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am start -W -n com.company.product/md5d0db2e8cfc61ece45132f7cc44405c09.SplashActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[debug] [ADB] Waiting up to 20000ms for activity matching pkg: 'com.company.product and activity: '*.SplashActivity' to be focused
[debug] [ADB] Possible activities, to be checked: '*.SplashActivity', 'com.company.product.*.SplashActivity'
[debug] [ADB] Getting focused package and activity
[debug] [ADB] Running '/home/homer/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys window windows'
[debug] [ADB] Found package: 'com.company.product and fully qualified activity name : 'md5819db72dd063416097553592a197be56.MainActivity'
[debug] [ADB] Incorrect package and activity. Retrying.
[debug] [ADB] Getting focused package and activity

**Comment by MagicPoulp** [comment]
It seems to me that it finds possible activities to wait for and since the one it finds does not have  a prefix dot, it loops retrying indefinitely.

This is my interpretation. Perhaps I am wrong.

**Comment by mykola-mokhnach** [comment]
Try to set the wait activity to a single star and nothing else

**Comment by MagicPoulp** [comment]
Thanks. I will try. In the meantimes, I found the following. If I specify the appActivity with the hash (and not the wait one), it wil say it will wait for package/ZZZ. And it works If I specify the appWaitActivity with a wildcard, it will say the same but with a dot and not a slash.

[debug] [ADB] Possible activities, to be checked: 'md5d0db2e8cfc61ece45132f7cc44405c09.SplashActivity', 'com.generosales.striker.md5d0db2e8cfc61ece45132f7cc44405c09.SplashActivity'

**Comment by MagicPoulp** [comment]
I tried your suggestion with a star. It worked. However, it handshakes on the other activity. I mean it waits for MainActivity and not the login activity. It is a very small nuance and it should not really matter for my test. It is still better than having to hard-code the right hash or to change the build from a multi-platform framework.

[debug] [ADB] Running '/home/homer/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am start -W -n com.company.product/md5d0db2e8cfc61ece45132f7cc44405c09.SplashActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[debug] [ADB] Waiting up to 20000ms for activity matching pkg: 'com.company.product' and activity: '*' to be focused
[debug] [ADB] Possible activities, to be checked: '*', 'com.company.product.*'
[debug] [ADB] Getting focused package and activity
[debug] [ADB] Running '/home/homer/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys window windows'
[debug] [ADB] Found package: 'com.company.product and fully qualified activity name : 'md5819db72dd063416097553592a197be56.MainActivity'

**Comment by tiecongli** [comment]
I am using wildcard but I got "Waiting up to 20000ms for activity matching pkg: 'com.company.project' and activity: 'com.company.*' to be focused"
Appium does find the control after wait but the 20s wait time is not trivial. Is it possible to boost up speed?
