### ISSUE TITLE
Why does findElement returns a list without functions?

### ISSUE THREAD

**Issue by MagicPoulp** [appium/appium#13787]
## The problem

Thank you to help me with this. I found the element but the n I cannot run setValue on it. ANd I don't understand why there are no functions at all to call. I just have a string with an id. But in the getting started tutorial, it used the returned element to run setValue on it.

see here the doc for using webdriverio in Javascript:
http://appium.io/docs/en/about-appium/getting-started/?lang=en
```
const field = await client.$("android.widget.EditText");
await field.setValue("Hello World!");
const value = await field.getText();
assert.equal(value, "Hello World!");
```

ANd here see my code that does not work:

```
const userElement = await this.driver.findElement('accessibility id', 'UserName');
 console.log(">>>>>>>>>>>>>>>", Object.getOwnPropertyNames(userElement))
await userElement.setValue('appium');
```

```
Error userElement.setValue is not a function
and the console output gives this:
2020-01-02T17:41:00.138Z INFO webdriver: COMMAND findElement("accessibility id", "UserName")
2020-01-02T17:41:00.138Z INFO webdriver: [POST] http://localhost:4723/wd/hub/session/9e21b6d7-5d7d-484a-8499-3f565ed11977/element
2020-01-02T17:41:00.138Z INFO webdriver: DATA { using: 'accessibility id', value: 'UserName' }
2020-01-02T17:41:00.874Z INFO webdriver: RESULT { 'element-6066-11e4-a52e-4f735466cecf': '80b47bad-f959-4755-b4cb-8d6fbd32f0f5',
  ELEMENT: '80b47bad-f959-4755-b4cb-8d6fbd32f0f5' }
```

(arrow tab) [ 'element-6066-11e4-a52e-4f735466cecf', 'ELEMENT' ]

## Environment

* Appium version (or git revision) that exhibits the issue:
last (1.4)
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
android
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

**Comment by mykola-mokhnach** [comment]
Kindly use Appium [forum](discuss.appium.io) to ask questions. This is the place for server issues

**Comment by MagicPoulp** [comment]
I tried but the forum is broken. It requires an email confirmation. And after 48 hours I still do not have it. I tried to ask to resend it several times with no result. If you don't believe me make a new account and you will see the problem.

Therefore, it is very nice that one cannot ask a question here.

Should I make an issue that one cannot register a new user on the appium forum? Please tell me.
https://discuss.appium.io/
