### ISSUE TITLE
Appium suddenly can't detect element for android webview apps

### ISSUE THREAD

**Issue by oka-saputra** [appium/appium#13785]
## The problem

Hi, I've an issue relate to no such element exception with following error 

[Java code error.txt](https://github.com/appium/appium/files/4015433/Java.code.error.txt)

FYI, this case is used to work for clicking Get Health Consultation by using following xpath code driver.findElement(By.xpath("//android.view.View[@text='Get Health Consultation']")).click();
and its accessible on the element by using UI Automator as well

![image](https://user-images.githubusercontent.com/56011424/71660687-72994d00-2d7e-11ea-84a3-aa4070d539de.png)

however the code is suddenly stop working, attached the log from appium server for your reference.
[appium-server-logs.txt](https://github.com/appium/appium/files/4015446/appium-server-logs.txt)

Appium inspector fail to detect element as well with following screen capture
![image](https://user-images.githubusercontent.com/56011424/71661014-6c57a080-2d7f-11ea-8a61-b1a61f1d6d11.png)

## Environment
Below are capability setting of my environment
dc.setCapability("noReset", "true");
dc.setCapability("fullReset", "false");
dc.setCapability("reportDirectory", reportDirectory);
dc.setCapability("reportFormat", reportFormat);
dc.setCapability("testName", testName);
dc.setCapability(MobileCapabilityType.UDID, "RR8M50AK3YL");
dc.setCapability(MobileCapabilityType.DEVICE_NAME, "A50");
dc.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
dc.setCapability(MobileCapabilityType.AUTOMATION_NAME,
AutomationName.ANDROID_UIAUTOMATOR2);
dc.setCapability(AndroidMobileCapabilityType.APP_PACKAGE, "com.grabtaxi.passenger");
dc.setCapability(AndroidMobileCapabilityType.APP_ACTIVITY,
"com.grab.pax.newface.presentation.newface.NewFace");
driver = new AndroidDriver<>(new URL("http://localhost:4724/wd/hub"), dc);
driver.setLogLevel(Level.INFO);

* Appium version :  1.15.1

**Comment by mykola-mokhnach** [comment]
the control is located inside a web view. Try to switch the context to find the element. Appium simp[ly shows what UIA2 framework returns to it - we have no control over elements returned to  the page source request

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by oka-saputra** [comment]
I found workaround for this case by uninstall chrome on smartphone and it works now.
