### ISSUE TITLE
Unable to launch Work Profile Android Application using UIAutomator2 

### ISSUE THREAD

**Issue by rahuljadhav981** [appium/appium#13782]
## The problem
Unable to launch Work Profile Android Application using UIAutomator2, but when we use value UIAutomator1 in capability automationName it is working through Appium Inspector as well as automation script.

## Environment
* Appium version (or git revision) that exhibits the issue: 1.16.0
* Desktop OS/version used to run Appium: Mac OS High Sierra v 10.13.6
* Node.js version : v12.14.0
* Npm or Yarn package manager: 6.13.4
* Mobile platform/version under test: Real Device Samsung Galaxy S8/ Android Version 9

## Details

Identified work profiles in Android device using below command:
**adb shell pm list users**
This is giving two userProfiles as below
UserInfo{0:Infyqa:13} running
UserInfo{11:Workspace:50100030} running.

For Launching application used below capabilities in Appium Inspector:
{
  "deviceName": "Samsung S8",
  "platformName": "android",
  "platformVersion": "9",
  "appPackage": "com.package.Mobile",
  "userProfile": "11",
  "appActivity": "com.package.Mobile.MainActivity",
  "automationName": "UiAutomator2"
}
When We use automationName as "UiAutomator2" this will launch application from userProfile 0 i.e. default user even we already set value of userProfile to 11 .
Where as when we change automationName to the "UiAutomator1" this will launch correct application from User profile 11 i.e. Work Profile

## Link to Appium logs
Attached Appium logs with both UIAutomator1 and UIAutomator2
[appium-server-logs_UIAutomator2.txt](https://github.com/appium/appium/files/4015017/appium-server-logs_UIAutomator2.txt)
[appium-server-logs_UIAutomator1.txt](https://github.com/appium/appium/files/4015018/appium-server-logs_UIAutomator1.txt)

## Code To Reproduce Issue [ Good To Have ]
We can use appium inspector to reproduce this issue.

**Comment by mykola-mokhnach** [comment]
It looks like this capability has not been added to UIA2 yet.

**Comment by mykola-mokhnach** [comment]
The update has been merged to appium@beta

**Comment by climbwithme** [comment]
@mykola-mokhnach  Thanks for this quick response

**Comment by pvsantosh** [comment]
is this still not available in UIAutomator2? Im trying to open app from work profile but it is opening app from personal profile. When I use the capability `userProfile: "11"` or any INT, it is throwing error saying 

[debug] [W3C] Encountered internal error running command: Error: Cannot start the 'com.pwc.us.mobility.wsone.stg.astro' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Cannot start the 'com.pwc.us.mobility.wsone.stg.astro' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Activity name '.com.pwc.us.mobility.wsone.stg.astro.MainActivity' used to start the app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity

Looking for suggestions.
My capability object:
const capabilities = {
  path: '/wd/hub',
  port: 4723,
  capabilities: {
    platformName: "Android",
    platformVersion: "10",
    deviceName: "Android Emulator",
    app: "/Users/userAccount/Downloads/app-debug.apk",
    userProfile: "11",
    appPackage: "com.my.comp.app.name",
    automationName: "UiAutomator2"
  }
};

**Comment by KazuCocoa** [comment]
Which version did you use? It should be in 1.18.x at least.
If you use newer versions, could you share the full Appium log?
