### ISSUE TITLE
appium support forum broken: requires email confirmation and says it disabled email

### ISSUE THREAD

**Issue by MagicPoulp** [appium/appium#13789]
## The problem

A new user on the support forum cannot confirm her email. And without confirmation, one cannot register a new user.

https://discuss.appium.io/

At the top of the page it says something that indicates emails are disabled on the server:
"All outgoing email has been globally disabled by an administrator. No email notifications of any kind will be sent."

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Try to create a new user.

**Comment by mykola-mokhnach** [comment]
The outgoing emails are not only sent for notifications. Email confirmations should work. Have you checked the Spam folder? Provide the name of your account there, I'll see what could be done.

**Comment by MagicPoulp** [comment]
OK thanks. I checked the spam folder. Sorry I did not mention that earlier.

Account name: MagicPoulp

**Comment by MagicPoulp** [comment]
Can I ask questions in the issue tracker until the forum works again?

**Comment by mykola-mokhnach** [comment]
I have manually activated your account. Enjoy

**Comment by MagicPoulp** [comment]
Ok thanks. Since you did not close, I guess you fixed it for me so I don't wanit but you need to fix it for all other people.

**Comment by davenh0000** [comment]
Hello, I am new here. I am trying to learn Appium. I tried to sign up for a new account, but received the same error MagicPoulp has. It said "All outgoing email has been globally disabled by an administrator. No email notifications of any kind will be sent." Can you help me activate my account please. Thanks.

**Comment by NicoAtTangelo** [comment]
Hello there, exact same issue here. The mail is never received. I tried in 2 different email address, same issue. Can you please help ?

**Comment by jlipps** [comment]
I have adjusted the discourse settings so that e-mail is no longer disabled. Hopefully this resolves any issues.

**Comment by NicoAtTangelo** [comment]
Let's see !!

**Comment by NicoAtTangelo** [comment]
Working like a charm ;) Thx guys !

**Comment by khemalathaa** [comment]
Not getting confirmation email to activate my account in https://discuss.appium.io/. I checked it in inbox, spam of my email. Please help me.

**Comment by khemalathaa** [comment]
> I have manually activated your account. Enjoy

It seems the issue is happening again, could you please help me?
