### ISSUE TITLE
Support remote WebDriverAgent debug on windows

### ISSUE THREAD

**Issue by Handsome2734** [appium/appium#13791]
## The problem

We have an iPhone with customized WDA installed, which can be accessed remotely via host and port. When I debug my case on Windows laptop, the server throws an exception and quit.

```
[debug] [XCUITest] Current user: 'xxx\xxx'
uncaughtException: connect ENOENT /var/run/usbmuxd
Error: connect ENOENT /var/run/usbmuxd
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): 10.9.0
* Npm or Yarn package manager: npm v6.10.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI installed via npm

## Details

After some debug, I found the `createSession` faild in `appium-xcuitest-driver/lib/driver.js`.
``` javascript
async determinDevice () {
//...
        // make sure it is a connected device. If not, the udid passed in is invalid
        const devices = await getConnectedDevices();
        log.debug(`Available devices: ${devices.join(', ')}`);
        if (!devices.includes(this.opts.udid)) {
          // check for a particular simulator
          if (await simExists(this.opts.udid)) {
            const device = await getSimulator(this.opts.udid);
            return {device, realDevice: false, udid: this.opts.udid};
          }

          throw new Error(`Unknown device or simulator UDID: '${this.opts.udid}'`);
        }
//...
}
```
Since I've passed a WDA address via `webDriverAgentUrl`, maybe it's ok to skip the check.

## Code To Reproduce Issue [ Good To Have ]

``` java
public class RemoteDeviceDemo {
  private IOSDriver driver = null;

  @BeforeClass
  public void setup() throws MalformedURLException {
    String REMOTE_URL = "http://10.5.147.87:10040";
    String VERSION = "12.0";
    String UDID = "xxx";
    String DEVICE_NAME = "XSMAX+002E+12.0";

    DesiredCapabilities capabilities = new DesiredCapabilities();
    capabilities.setCapability("webDriverAgentUrl", REMOTE_URL);
    capabilities.setCapability("platformName", "iOS");
    capabilities.setCapability("platformVersion", VERSION);
    capabilities.setCapability("deviceName", DEVICE_NAME);
    capabilities.setCapability("app", "http://some.ipa");
    capabilities.setCapability("udid", UDID);
    capabilities.setCapability("automationName", "XCUITest");

    this.driver = new IOSDriver(new URL("http://localhost:4723/wd/hub/"),capabilities);   // where exception happens
  }

  @Test
  public void test() {
    IOSElement element = (IOSElement)this.driver.findElementById("my");
    element.click();
  }
}
```

**Comment by mykola-mokhnach** [comment]
Unfortunately such scenario is not possible. Communication with i-devices requires special libs from Xcode SDK, which don't not exist for Windows. Please let us know when Apple makes such instrumentation available for Windows.

**Comment by Handsome2734** [comment]
Regardless of windows, it's also not possible to automate remote iPhone with checking for local connected devices on Mac.

**Comment by mykola-mokhnach** [comment]
Like I said we would be happy to make such feature possible if the vendor would provide instruments for it. Apple does not have anything similar to `adb` for iPhone. Moreover the protocol specs it uses for devices communication are private and it's already a miracle we have libs which allow to communicate with local devices thanks to people that spends months of their free time to investigate some protocol implementation details and implement them under OpenSource license.

**Comment by markhuangext359** [comment]
The company experitest(Appium studio) already implement the spec(test iOS device on WinOS) but no openSource license and no source code.
