### ISSUE TITLE
Unable to get element attribute and execute script - iOS-Safari, Appium-1.14.2.

### ISSUE THREAD

**Issue by ahmadsayeed3** [appium/appium#13797]
## The problem

I would like to explain the question with the Appium request and response.

**Request**
**-->** GET /wd/hub/session/a975b172-d7d8-4066-8901-33510de3ca5d/element/5021/attribute/Class

**Response**
Encountered internal error running command: Error: Did not get any response after 90s
at XCUITestDriver.waitForAtom (/Users/radmin/.npm-packages/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/web.js:273:13)
**<--** GET /wd/hub/session/a975b172-d7d8-4066-8901-33510de3ca5d/element/5021/attribute/Class 500 90011 ms - 205

It's also random. Sometimes it often comes while getting id, class attribute or executing javascript.

With Appium 1.15.1, I was only able to launch the safari browser but not able to perform any other actions like finding or click. But with Appium 1.14.2 It randomly occurring this issue.

Any suggestion would help to prevent this.

## Environment

* Appium version: Appium 1.14.2, 1.15.1
* Last Appium version that did not exhibit the issue (Appium 1.12):
* Desktop OS/version used to run Appium: Ubuntu
* Node.js version (unless using Appium.app|exe): 10.x
* Npm or Yarn package manager: Npm
* Mobile platform/version under test: IOS
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs
https://gist.github.com/ahmadsayeed3/b56062b95c34280bf365f44750c3b43e

**Comment by mykola-mokhnach** [comment]
try Appium 1.16 or appium@beta

**Comment by mykola-mokhnach** [comment]
Closed because of no response
