### ISSUE TITLE
Basic login tests taking extremely long to run on OS 13 iPhone vs. OS 12 iPhone

### ISSUE THREAD

**Issue by shivanisrivastava** [appium/appium#13792]
## The problem

While running testNG tests on a real device, I noticed that basic actions of login and sign up are taking up to 25 mins on OS 13 iPhone XS Max when the same flows run on OS 12 iPhone take only 3 mins. Accessibility IDs and code is exactly the same. iOS app code is in Swift and we write tests in Java (run via testng.xml)

## Environment

* Appium version (or git revision) that exhibits the issue: Appium version 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: MacOS v10.14.4
* Node.js version (unless using Appium.app|exe): N/A (using Appium.app)
* Npm or Yarn package manager: NPM v6.12.0
* Mobile platform/version under test: iPhone OS 12 and OS 13 comparison
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium.app

There are no error logs since tests don't fail. Just that they take exponentially longer. 
Any known solutions I can try out?

**Comment by mykola-mokhnach** [comment]
Unfortunately we cannot help much having the provided information. The issue must be investigated deeper to isolate possible bottle necks. Check https://appiumpro.com/editions/19 and further articles to optimise the tests.

**Comment by amedvedjev** [comment]
+1. totally agree. specially with latest 13.3. same test code runs 30% falster on iOS 12.

**Comment by jmehtaebates** [comment]
@mykola-mokhnach  the only difference in our tests is the OS version of the device/simulator

For the same code, iOS 12 takes 3 mins whereas iOS 13 takes 30 mins. What info should we provide you here to help you debug this ?

**Comment by mykola-mokhnach** [comment]
I don't see there is anything to do there from Appium side. The codebase is totally equal for both iOS versions, which means that only XCTest itself might affect the actual performance, which is under Apple's control. Although we are always open to PRs if you could find any issues in the current code.

Consider moving the topic to Appium forum if you have further questions
