### ISSUE TITLE
Appium server is struck while switching webviews in iOS real device

### ISSUE THREAD

**Issue by gcsharathbabu** [appium/appium#13799]
## The problem
The Appium server is struck while setting webview context in the iOS real device. i.e: driver.context(contextName). Upon quitting the app the call back received and the contexts are retrieved. Refer the sample code below used to switch context.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: MacOS 10.14.6 
* Node.js version (unless using Appium.app|exe): v13.5.0
* Npm or Yarn package manager: 6.13.4
* Mobile platform/version under test: IOS
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details
The output from the sample code run is as below:

[testng] Retry = 3  ===  ContextName = NATIVE_APP
   [testng] Retry = 3  ===  ContextName = WEBVIEW_4852.1
   [testng] Getting the current Url

Appium is struck in the above line. After qutting appium the below lines are printed:

Retry = 3  ===  ContextName = WEBVIEW_4852.2
   [testng] Getting the current Url
   [testng] Retry = 3  ===  ContextName = WEBVIEW_4852.11
   [testng] Getting the current Url

## Link to Appium logs

https://gist.github.com/gcsharathbabu/94f82aaede0f878c421c49abeb054984

## Code To Reproduce Issue [ Good To Have ]

```java
public void switchToWebViewContext(final String url) {
        Set<String> contextNames;
        boolean foundWebView = false;
        int retryCount = WEBVIEW_RETRY_COUNT;
        while (!(contextNames = this.getAvailableViews()).isEmpty() && !foundWebView) {
            int webviewCount = 0;
            for (String contextName : contextNames) {
                LOGGER.debug("Retry : {} : contextName : {}", retryCount, contextName);
                System.out.println("Retry = " + retryCount + "  ===  ContextName = " + contextName);
                if (contextName.contains(ContextView.WEBVIEW.getContextView())) {
                   System.out.println("Getting the current Url");
                   try {
                       Thread.sleep(5000);
                       driver.context(contextName);
                       System.out.println("==================================================================");
                       System.out.println("Current context = " + driver.getContext());
                       String url2 = driver.context(contextName).getCurrentUrl();
                       System.out.println("Page title = " + driver.context(contextName).getTitle());
                       System.out.println("Page Url = " + url2);
                       System.out.println("Window handle = " + driver.context(contextName).getWindowHandle());
                       System.out.println("==================================================================");
                   } catch(Exception e) {
                       //Ignore this exception
                   }
                }
                /*
                if (contextName.contains(ContextView.WEBVIEW.getContextView()) &&
                        driver.context(contextName).getCurrentUrl().contains(url)) {
                    LOGGER.debug("Current context url : {}", driver.context(contextName).getCurrentUrl());
                    driver.context(contextName);
                    LOGGER.debug("Web view context set to context handle : {}", contextName);
                    foundWebView = true;
                    break;
                }
                */
            }
            if (retryCount-- <= 0 && !foundWebView) {
                throw new TestException(
                        String.format("Unable to switch to webview after '%d' retries. " +
                                "Current context : %s", WEBVIEW_RETRY_COUNT, driver.getContext()));
            }
        }
    }
```

**Comment by gcsharathbabu** [comment]
@mykola-mokhnach I wrote a different method to handle webviews and this seems to be working. I get totally 3 webviews, the problem seems to appear while switching to a page that isn't active. Instead of checking the webview url by settting the context (i.e: driver.context(<web context>). I'm using driver.executeScript("mobile: getContexts", ImmutableMap.of("waitForWebviewMs", 30000)). Which gets all the available contexts including url & page title. I believe if driver.getContexts() method can list the output that "mobile: getContexts" does. The overall problem of switching to a stale webview can be solved to an extent. Refer the below code.


`    public void switchToWebViewContext(final String url) {
        try {
            Thread.sleep(10000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        ArrayList contexts = (ArrayList) driver.executeScript("mobile: getContexts",
                ImmutableMap.of("waitForWebviewMs", 30000));
        System.out.println("====Available contexts====");
        contexts.forEach(context -> System.out.println(context));
        System.out.println("==========================");
        Pattern pattern = Pattern.compile("WEBVIEW_\\d*.\\d");
        contexts.forEach(context -> {
            if(context.toString().contains(url)) {
                Matcher matcher = pattern.matcher(context.toString());
                driver.context(matcher.find() ? matcher.group(0): null);
            }
        });
    }`

**Comment by imurchie** [comment]
With the latest code in the Appium beta this ought to be working now.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
