### ISSUE TITLE
Xamarin controls found by Appium Inspector are not found by PageSource method

### ISSUE THREAD

**Issue by reply2sagar** [appium/appium#13798]
iOS app is built using Xamarin library. When we use Appium XCUITest inspector to identify the elements, it identifies pickercontrol elements in app. But when I print the pagesource, those pickerelements are not being shown. These controls are shown with class as XCUIElementTypeOther
instead of XCUIElementTypeTextField(as found in inspector)

Environment
Appium version (or git revision) that exhibits the issue: 1.15.1
Last Appium version that did not exhibit the issue (if applicable): NA
Desktop OS/version used to run Appium: Mac OS 10.15
Node.js version (unless using Appium.app|exe): 10.5
Npm or Yarn package manager:NPM
Mobile platform/version under test: iOS 12, iOS 13
Real device or emulator/simulator: Simulator
Appium CLI or Appium.app|exe: Both
Details
Xamarin Nuget Package version - 4.8

**Comment by mykola-mokhnach** [comment]
Please attach the page source output, the actual query samples and the device logs while these queries are being executed

**Comment by mykola-mokhnach** [comment]
Closed because of no response
