### ISSUE TITLE
iOS: Wrong Context Selected When App Has Multiple WebViews

### ISSUE THREAD

**Issue by Dan-Maor** [appium/appium#13804]
## The problem

In some of our use cases we test apps with multiple webviews in a single screen, and it appears that in some cases attempting to select a context before the second webview is loaded causes the wrong one to be selected.

Reproduced on iOS 11.0.3, 12.4 and 13.3.1 (with an additional getContextHandles() call before loading the first page to work around https://github.com/appium/appium/issues/13770).

Attempting to set the context again to the same one immediately after the incorrect one has been selected causes the correct one to be selected.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: MacOS 10.14.6
* Node.js version (unless using Appium.app|exe): v10.15
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs and code to reproduce

https://gist.github.com/Dan-Maor/fea2f29fe030f62795498e36e023ad04
(the script fails when attempting to find `//div` in the first webview, sometimes it fails to recognize the first webview at all.

## Sample app:
https://github.com/Dan-Maor/multiwebview

**Comment by imurchie** [comment]
It appears to be getting the notification about the second webview and treating it as a redirect, so choosing the new one (which is how the system handles new windows being opened. I'll look into what can be done about this.

**Comment by imurchie** [comment]
@Dan-Maor Are you comfortable trying out a branch for a sub-package of Appium?

**Comment by Dan-Maor** [comment]
Of course, no problem.

**Comment by imurchie** [comment]
Excellent! I have a change that makes your test situation work consistently _on my system_.

https://github.com/imurchie/appium-remote-debugger/tree/isaac-empty

I'm still checking if it breaks other stuff, so we will see. But if you could try it, that would be great!

**Comment by Dan-Maor** [comment]
I took the change from the branch to my local installation and it appears to have solved the issue, the contexts are now selected correctly and the flow works as expected :)

**Comment by imurchie** [comment]
Excellent!

This should be available now in the beta of Appium, with `appium-remote-debugger@7.4.0`.

**Comment by Dan-Maor** [comment]
I can confirm that on appium@beta with the latest `appium-remote-debugger` version my test works correctly.

Thanks a lot for your assistance with this issue.
