### ISSUE TITLE
Android start activity failing for certain apps

### ISSUE THREAD

**Issue by Jiurong-Yang** [appium/appium#13803]
## The problem
Using start_activity method call fails and reports incorrect package/activity 

## Environment

* Appium version: 1.15.1
* OS Version: Ubuntu 16.04
* Mobile OS: Android 10, 9, 8, 7
* Real device
* Appium CLI

## Details
The start_activty method will start the app in question (adobe reader). But then will throw an exception that appium cannot start the app. Even though the app did start. 
I think depends on how certain app is coded the current start_activity method is unable to recognize that the app actually started so it returns that appium cannot start the app. 

## Link to Appium logs
[Appium Log] (https://gist.github.com/Jiurong-Yang/22d9d37abd66ec0ab203af8592d2e922)

## Code To Reproduce Issue [ Good To Have ]
Python:
driver.start_activity("com.adobe.reader", ".AdobeReader", wait_app_activity="com.adobe.reader*")
NOTE: Tried using "*" as the wait activity or not passing one in. All ended with the same failure.

**Comment by mykola-mokhnach** [comment]
> 2020-01-06 18:52:45:126 - [debug] [W3C (8a010757)] Calling AppiumDriver.startActivity() with args: ["com.adobe.reader",".AdobeReader",null,null,null,null,null,null,null,"8a010757-d1f5-497c-a626-711ecb163a53",null,"8a010757-d1f5-497c-a626-711ecb163a53"]
> 2020-01-06 18:52:45:127 - [debug] [AndroidDriver] Starting package 'com.adobe.reader' and activity '.AdobeReader'
> 2020-01-06 18:52:45:128 - [debug] [ADB] Running '/opt/android/platform-tools/adb -P 5037 -s HT71D0203842 shell am start -W -n com.adobe.reader/.AdobeReader -S'
> 2020-01-06 18:52:46:474 - [debug] [ADB] Waiting up to 20000ms for activity matching pkg: 'com.adobe.reader' and activity: '.AdobeReader' to be focused
> 2020-01-06 18:52:46:475 - [debug] [ADB] Possible activities, to be checked: 'com.adobe.reader.AdobeReader'
> 2020-01-06 18:52:46:475 - [debug] [ADB] Getting focused package and activity
> 2020-01-06 18:52:46:476 - [debug] [ADB] Running '/opt/android/platform-tools/adb -P 5037 -s HT71D0203842 shell dumpsys window displays'
> 2020-01-06 18:52:46:523 - [debug] [ADB] Found package: 'com.adobe.reader' and fully qualified activity name : 'com.adobe.reader.home.ARHomeActivity'
> 2020-01-06 18:52:46:524 - [debug] [ADB] Incorrect package and activity. Retrying.

It looks for exactly the activity name that has been provided as the argument. Although, the other one seems to be active

**Comment by Jiurong-Yang** [comment]
I'm not sure I understand. The code is launching the app with the package name and an activity name. But I am passing in the wait_app_activity argument with a wildcard. Which in the documentation is supported. isn't "com.adobe.reader*" suppose to match anything with prefix com.adobe.reader?

**Comment by mykola-mokhnach** [comment]
> 2020-01-06 18:52:45:126 - [debug] [W3C (8a010757)] Calling AppiumDriver.startActivity() with args: ["com.adobe.reader",".AdobeReader",null,null,null,null,null,null,null,"8a010757-d1f5-497c-a626-711ecb163a53",null,"8a010757-d1f5-497c-a626-711ecb163a53"]

I don't see any wildcards in this command. Should it be something else?

**Comment by Jiurong-Yang** [comment]
Yeah I realized that on the client side the wrong parameter name is used (python start_activity) and the wait activity wasn't passed in properly. I'm going to fix the client call and verify again to see if the problem persists.

**Comment by Jiurong-Yang** [comment]
Yeah it was due to the bad client method call.
