### ISSUE TITLE
Unable to use the visible property with the IOS class chain or NS Predicate

### ISSUE THREAD

**Issue by KS261187** [appium/appium#13801]
## The problem

When trying to spy the objects in IOS using IOS class chain or NS predicate along with the visible property, it returns 0 result. However when I do the same with xpath, it works fine. For eg: **/XCUIElementTypeButton[`label CONTAINS 'Home' AND visible==true`]. If I do the same with the xpath like //XCUIElementTypeButton[@label='Home'][@visible='true']
[appium-server-logs.txt](https://github.com/appium/appium/files/4027270/appium-server-logs.txt)
, it works.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS 10.15.2
* Node.js version (unless using Appium.app|exe):v11.8.0
* Npm or Yarn package manager:
* Mobile platform/version under test: IOS
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium.exe

## Details

As mentioned, the visible property is not getting identified with IOS NS predicate or IOS class chain. This used to work before but after updating the Mac OS and Xcode, I am facing this issue.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by amedvedjev** [comment]
@KS261187 try with:
iOSNsPredicate = "type == 'XCUIElementTypeButton' AND name CONTAINS[cd] 'Home' AND visible == 1"

**Comment by KS261187** [comment]
No that did not work. This used to work fine before not sure what happened suddenly.

**Comment by mykola-mokhnach** [comment]
You could try to set `simpleIsVisibleCheck` to `true` as a workaround

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
