### ISSUE TITLE
Connection was refused to port 8100 with 1.16.0

### ISSUE THREAD

**Issue by romainlouvet** [appium/appium#13800]
## The problem
[XCUITest] WDA is not listening at 'http://localhost:8100/

Fail to launch my test with appium 1.16.0, if I downgrade to 1.15.1 it's good. 
my provisioning profile is good with this command
xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=70148ea96d19df1839ee10435c9db0e2d953e8fa' clean build test 
-> 
2020-01-06 16:38:14.879815+0100 WebDriverAgentRunner-Runner[415:30769] Built at Jan  6 2020 16:36:56
2020-01-06 16:38:14.893552+0100 WebDriverAgentRunner-Runner[415:30769] ServerURLHere->http://192.168.185.52:8100<-ServerURLHere
2020-01-06 16:38:14.894009+0100 WebDriverAgentRunner-Runner[415:30788] Using singleton test manager

here my appium log https://gist.github.com/romainlouvet/518e3389e544e10b0170a82c14915a33

## Environment

* Appium version : 1.16.0
* Mobile platform/version under test: ios 13.3
* Real device

**Comment by mykola-mokhnach** [comment]
> [debug] [WebDriverAgent] *** Skipped downloading RoutingHTTPServer.framework binary due to the error:
> [debug] [WebDriverAgent]        "API rate limit exceeded for 193.164.196.145. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"
> [debug] [WebDriverAgent] *** Skipped downloading YYCache.framework binary due to the error:
> [debug] [WebDriverAgent]        "API rate limit exceeded for 193.164.196.145. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"

Most likely Carthage is unable to download the necessary submodules from GitHub. Try to execute the bootstrap script manually or use appium@beta, where Carthage [does not try](https://github.com/appium/WebDriverAgent/pull/261) to get binaries by default

**Comment by romainlouvet** [comment]
I can download manualy `appium-webdriveragent mkdir -p Resources/WebDriverAgent.bundle
➜  appium-webdriveragent sh ./Scripts/bootstrap.sh -d
-e Fetching dependencies
*** Checking out CocoaAsyncSocket at "7.6.3"
*** Checking out RoutingHTTPServer at "v1.0.2"
*** Checking out YYCache at "1.1.0"
*** xcodebuild output can be found in /var/folders/mb/84j6wccx1m72h594ny26lpr80000gn/T/carthage-xcodebuild.v1zWWQ.log
*** Downloading CocoaAsyncSocket.framework binary at "Version 7.6.3"
*** Building scheme "RoutingHTTPServer tvOS" in RoutingHTTPServer.xcodeproj
*** Building scheme "RoutingHTTPServer iOS" in RoutingHTTPServer.xcodeproj
*** Building scheme "YYCache iOS" in YYCache.xcodeproj
*** Building scheme "YYCache tvOS" in YYCache.xcodeproj`

**Comment by romainlouvet** [comment]
same problem with appium@beta 1.16.0-beta.3

> [debug] [XCUITest] Starting WebDriverAgent initialization with the synchronization key 'XCUITestDriver'
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@70148ea9] Error: Connection was refused to port 8100
[iProxy@70148ea9]     at Usbmux.connect (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-ios-device/lib/usbmux/index.js:207:13)
[iProxy@70148ea9]     at Object.connectPort (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-ios-device/lib/utilities.js:163:12)
[iProxy@70148ea9]     at Server.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/device-connections-factory.js:23:30)
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[debug] [WebDriverAgent] WDA is not listening at 'http://localhost:8100/'
[debug] [WebDriverAgent] WDA is currently not running. There is nothing to cache
[debug] [XCUITest] Trying to start WebDriverAgent 1 times with 10000ms interval
[debug] [XCUITest] These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1578385702646 (09:28:22 GMT+0100 (heure normale d’Europe centrale))
[WebDriverAgent] Launching WebDriverAgent on the device
[WebDriverAgent] Fetching dependencies
[WebDriverAgent] Installing/updating dependencies for platforms 'iOS', 'tvOS'
[debug] [WebDriverAgent] *** Checking out RoutingHTTPServer at "v1.2.2"
[debug] [WebDriverAgent] *** Checking out YYCache at "1.1.0"
[debug] [WebDriverAgent] *** xcodebuild output can be found in /var/folders/mb/84j6wccx1m72h594ny26lpr80000gn/T/carthage-xcodebuild.kyfBBw.log
[HTTP] --> GET /wd/hub/status

**Comment by mykola-mokhnach** [comment]
Please enable showing of the xcodebuild logs and attach the updated server log

**Comment by romainlouvet** [comment]
it's work after launch this command 

> security unlock-keychain -p ****
