### ISSUE TITLE
Can't play iOS screen recording

### ISSUE THREAD

**Issue by gfioretti** [appium/appium#13806]
## The problem

I'm trying to implement screen record on my tests and after implementing on Android with ease I'm facing some issues on iOS, namely I can't play iOS screen record videos. File produced after stop recording seems to have data but can't be played (maybe it is corrupted?).

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable): /
* Desktop OS/version used to run Appium: MacOS 10.15.1
* Node.js version (unless using Appium.app|exe): v13.5.0
* Npm or Yarn package manager: Npm 6.13.4
* Mobile platform/version under test: iOS 13.2
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI v1.16.0
ffmpeg version 4.2.2
Java client 7.3.0

## Details

Trying to open produced file on Quicktime returns error: The file isn’t compatible with QuickTime Player.
Trying on VLC file contains 0 seconds. However, file has over 1mb, meaning that it contains data.
I've tried tried using different VideoType codecs, with/out IOSStartScreenRecordingOptions and result is pretty much the same.

## Link to Appium logs

https://gist.github.com/gfioretti/02c153c0f904cbcf205b7ebd3a546026

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
The log looks fine. Have you tried to connect to the stream with a browser? Simply navigate to http://localhost:9100 while your test is running.

**Comment by gfioretti** [comment]
Yes - forgot to add this info - whilst troubleshooting I successfully connected to the stream via browser.

**Comment by mykola-mokhnach** [comment]
Then it might be some issue with ffmpeg. Make sure it is up to date, try different encoder

**Comment by mykola-mokhnach** [comment]
I don't observe any issues there from Appium side.

Closed as third party issue

**Comment by ajschwieterman** [comment]
Go to Issue [#13113](https://github.com/appium/appium/issues/13113).  Change the VideoType to "h264".

**Comment by hbanafal** [comment]
This works for me 

```
((CanRecordScreen) mobileDriver).startRecordingScreen(
                    new IOSStartScreenRecordingOptions().withTimeLimit(Duration.ofSeconds(1200)).withVideoType("h264")
                            .withVideoFilters("scale=trunc(iw/2)*2:trunc(ih/2)*2").enableForcedRestart());
```
