### ISSUE TITLE
Platform name android not found 

### ISSUE THREAD

**Issue by donmezburak** [appium/appium#13814]
## The problem
platformName android not found.

## Environment

* Appium version 1.16.0:
* Ubuntu 16.04:

## Code To Reproduce Issue [ Good To Have ]

commad line 
> node . --platform-name Android --app app_file.apk --device-name 8 --udid xxx

from postman:

>localhost:4723/wd/hub/session

Post data:

{"desiredCapabilities": {
	"platformName" : "android"
}}

server answer:
{
    "status": 13,
    "value": {
        "message": "An unknown server-side error occurred while processing the command. Original error: Could not find a driver for platformName 'android'. Please check your desired capabilities."
    },
    "sessionId": null
}

**Comment by mykola-mokhnach** [comment]
the exception is expected. Please provide the capabilities in the format requested by the driver: https://github.com/appium/appium-uiautomator2-driver

**Comment by mykola-mokhnach** [comment]
Also such exception could arise if the corresponding driver package has been corrupted and/or could not be loaded by the umbrella driver. See https://github.com/appium/appium/blob/5ecd5a4790b7d4a9ca97c473022e9ac5590538f3/lib/appium.js#L216
https://github.com/appium/appium/blob/5ecd5a4790b7d4a9ca97c473022e9ac5590538f3/lib/appium.js#L37
for more details

**Comment by donmezburak** [comment]
android driver package has been damaged. Problem occurs due to that. Thanks for attention.
