### ISSUE TITLE
does the chromedriver of appium/selenium automate the android app's webview through/by android system webview?

### ISSUE THREAD

**Issue by zhizunbao84** [appium/appium#13812]
i use appium 1.15.1 on win7 x64.
i want to  automate  android browser app,  my android phone is CM 13(android 6.0.1).
the version of android system webview is 57, and the version of the android browser app webview is 42.
my python code:
`driver._switch_to.context('WEBVIEW_org.cyanogenmod.gello.browser')`
1. i just download the chromedriver 2.16 (for webview 42), the appium shows error:
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: No Chromedriver found that can automate Chrome '57.0.2987'.

2. i just download the chromedriver 2.29 (for webview 57), the appium shows error:
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Unable to automate Chrome version because it is too old for this version of Chromedriver.
Chrome version on the device: Chrome/42.0.2311.154
Visit 'https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md' to troubleshoot the problem.
A new session could not be created. Details: session not created exception: Chrome version must be >= 56.0.2884.0
  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 6.1.7601 SP1 x86_64)

3. i download chromedriver 2.29 and chromedriver 2.16. it is the same as above.

what should i do?!!

**Comment by zhizunbao84** [comment]
i upload the appium-server-log
[appium-server-log222.txt](https://github.com/appium/appium/files/4034172/appium-server-log222.txt)

**Comment by mykola-mokhnach** [comment]
Please follow https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md for the troubleshooting. Also, newer Appium releases have a feature that allows to automatically download a matching chromedriver version.

Kindly use [Appium forum ](discuss.appium.io) to ask questions. 
Closed as not an issue

**Comment by zhizunbao84** [comment]
i follow https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md, but i don't know how to get it work.
in my question, i have downloaded the correct chromedriver version.

**Comment by mykola-mokhnach** [comment]
> [Chromedriver] Found Chrome bundle 'com.google.android.webview' version '57.0.2987'
> [Chromedriver] Found 1 Chromedriver executable capable of automating Chrome '57.0.2987'.
> [Chromedriver] Choosing the most recent, 'D:/bolanqunshu/python/xuexiqiangguo/webview/a808t/chromedriver_2.29.exe'.
> [Chromedriver] If a specific version is required, specify it with the `chromedriverExecutable`desired capability.
> [Chromedriver] Set chromedriver binary as: D:/bolanqunshu/python/xuexiqiangguo/webview/a808t/chromedriver_2.29.exe
> [Chromedriver] Killing any old chromedrivers, running: wmic process where "commandline like '%chromedriver.exe%--port=8000%'" delete
> [Chromedriver] No old chromedrivers seem to exist
> [Chromedriver] Cleaning any old adb forwarded port socket connections
> [ADB] List forwarding ports
> [ADB] Running 'D:\bolanqunshu\android_dev\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 750ABLJTYPA9 forward --list'
> [ADB] Removing forwarded port socket connection: 12701 
> [ADB] Running 'D:\bolanqunshu\android_dev\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 750ABLJTYPA9 forward --remove tcp\:12701'
> [Chromedriver] Spawning chromedriver with: D:/bolanqunshu/python/xuexiqiangguo/webview/a808t/chromedriver_2.29.exe --url-base=wd/hub --port=8000 --adb-port=5037 --verbose
> [Chromedriver] Chromedriver version: '2.29.461591'
> [Chromedriver] Chromedriver v. 2.29.461591 does not fully support W3C protocol. Defaulting to MJSONWP
> [WD Proxy] Matched '/status' to command name 'getStatus'
> [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
> [WD Proxy] Got response with status 200: {"sessionId":"","status":0,"value":{"build":{"version":"alpha"},"os":{"arch":"x86_64","name":"Windows NT","version":"6.1.7601 SP1"}}}
> [Chromedriver] Starting MJSONWP Chromedriver session with capabilities: {
> [Chromedriver]   "desiredCapabilities": {
> [Chromedriver]     "chromeOptions": {
> [Chromedriver]       "androidPackage": "org.cyanogenmod.gello.browser",
> [Chromedriver]       "androidUseRunningApp": true,
> [Chromedriver]       "androidDeviceSerial": "750ABLJTYPA9"
> [Chromedriver]     },
> [Chromedriver]     "loggingPrefs": {
> [Chromedriver]       "browser": "ALL"
> [Chromedriver]     }
> [Chromedriver]   }
> [Chromedriver] }
> [WD Proxy] Matched '/session' to command name 'createSession'
> [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"org.cyanogenmod.gello.browser","androidUseRunningApp":true,"androidDeviceSerial":"750ABLJTYPA9"},"loggingPrefs":{"browser":"ALL"}}}
> [Chromedriver] Webview version: 'Chrome/42.0.2311.154'

The log shows that the actual chrome version in the web view is different from the default web view version available on the device. Try to provide the direct path to the matching driver binary rather than the folder path.

**Comment by imurchie** [comment]
If you provide the Chromedriver executable through the `chromedriverExecutable` capability it ought to skip the local check for compatibility. So if Chromedriver can figure things out (you can set `showChromedriverLog` to `true` to see what it is doing) then it ought to work.

**Comment by afathonih** [comment]
I started to see similar issue recently. Basically it happens when the chrome version is different from webview version. Appium will stick to what ever chrome driver it wasalready running instead of spawning new chromedriver process to match the requested web context.
In this log snippet, Appium correctly identifies insstalled chrome version and spawns correct chromedriver
```
[Chromedriver@97f6] Browser version in the supplied details: Chrome/90.0.4430.210
[Chromedriver@97f6] Found Chrome bundle 'undefined' version '90.0.4430'
[Chromedriver@97f6] Found 1 executable capable of automating Chrome '90.0.4430'.
```
 In the following log, Appium correctly detected the webview version but does not use it to choose the correct chromedriver.
```
Webview version: 'Chrome/129.0.6668.9'
[Chromedriver@97f6] [STDERR] [1724651210.090][DEBUG]: DevTools HTTP Response: {
[Chromedriver@97f6] [STDERR]    "Android-Package": "com.company.app",
[Chromedriver@97f6] [STDERR]    "Browser": "Chrome/129.0.6668.9",
[Chromedriver@97f6] [STDERR]    "Protocol-Version": "1.3",
[Chromedriver@97f6] [STDERR]    "User-Agent": "Mozilla/5.0 (Linux; Android 11; ) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/129.0.6668.9 Mobile Safari/537.36",
[Chromedriver@97f6] [STDERR]    "V8-Version": "12.9.202.2",
[Chromedriver@97f6] [STDERR]    "WebKit-Version": "537.36 (@ab04602ab643c38e287ed0f49d486307a125c6b8)",
[Chromedriver@97f6] [STDERR]    "webSocketDebuggerUrl": "ws://localhost:55754/devtools/browser"
[Chromedriver@97f6] [STDERR] }
[Chromedriver@97f6] [STDERR] [1724651210.090][DEBUG]: Sending adb command: host-serial:004401230448108:killforward:tcp:55754
[Chromedriver@97f6] [STDERR] [1724651210.090][DEBUG]: ADB server responded with "OKAYOKAY" instead of "OKAY".
[Chromedriver@97f6] [STDERR] [1724651210.090][DEBUG]: Received adb response: 
[Chromedriver@97f6] [STDERR] [1724651210.090][INFO]: [c22ace0c0417c0fd71bb5420e2a52ef3] RESPONSE InitSession ERROR session not created: This version of ChromeDriver only supports Chrome version 90
[Chromedriver@97f6] [STDERR] Current browser version is 129.0.6668.9 with package name com.company
[Chromedriver@97f6] [STDERR] [1724651210.090][DEBUG]: Log type 'driver' lost 0 entries on destruction
[Chromedriver@97f6] [STDERR] [1724651210.090][DEBUG]: Log type 'browser' lost 0 entries on destruction
[Chromedriver@97f6] Got response with status 500: {"value":{"error":"session not created","message":"session not created: This version of ChromeDriver only supports Chrome version 90
```

**Comment by afathonih** [comment]
Current getChromeVersion implementation in appium chromedriver package is using adb dumpsys package to get version info from android webview package. Apparently this command works for other packages like chrome but not for android webview. To get webview the command to use is `shell dumpsys webviewupdate`. This will give us:
```

shell dumpsys webviewupdate | grep version
  Current WebView package (name, version): (com.google.android.webview, 127.0.6533.103)
  Minimum WebView version code: 500512533
  Preferred WebView package (name, version): (com.google.android.webview, 127.0.6533.103)
    Valid package com.google.android.webview (versionName: 127.0.6533.103, versionCode: 653310333, targetSdkVersion: 35) is  installed/enabled for all users

```

**Comment by KazuCocoa** [comment]
Could you share the appium server log and the result of `mobile:getContexts` on your target page was shown? https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#mobile-getcontexts

If you haven't tried auto chromedriver download, https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#automatic-discovery-of-compatible-chromedriver could help.

Btw, was what you found the same as `adb shell dumpsys package com.android.webview` result of https://github.com/appium/appium-chromedriver/blob/2d58123b55aa679770c70d755a13f49a33693264/lib/chromedriver.js#L257-L262 ?

**Comment by afathonih** [comment]
@KazuCocoa 
getContexts logs:
```
[91f281d0][AndroidUiautomator2Driver@f133] Calling AppiumDriver.getContexts() with args: ["91f281d0-e945-4050-b09b-87856f1c5a87"]
[91f281d0][AppiumDriver@41e0] Clearing new command timeout pre-emptively since plugin(s) will handle this command
[91f281d0][AppiumDriver@41e0] Plugins which can handle cmd 'getContexts': images
[91f281d0][AppiumDriver@41e0] Plugin images is now handling cmd 'getContexts'
[91f281d0][AppiumDriver@41e0] Executing default handling behavior for command 'getContexts'
[91f281d0][AndroidDriver] Getting a list of available webviews
[91f281d0][ADB] Running '/Users/ci/Library/Android/sdk/platform-tools/adb -P 5037 -s d82f22e6 shell cat /proc/net/unix'
[91f281d0][AndroidDriver] Parsed 1 active devtools socket: ["@webview_devtools_remote_19100"]
[91f281d0][AndroidDriver] Collecting CDP data of 1 webview
[91f281d0][AndroidDriver] Forwarding remote port webview_devtools_remote_19100 to a local port in range 10900..11000
[91f281d0][AndroidDriver] You could use the 'webviewDevtoolsPort' capability to customize the starting port number
[91f281d0][ADB] Running '/Users/ci/Library/Android/sdk/platform-tools/adb -P 5037 -s d82f22e6 forward tcp:10900 localabstract:webview_devtools_remote_19100'
[91f281d0][ADB] Removing forwarded port socket connection: 10900 
[91f281d0][ADB] Running '/Users/ci/Library/Android/sdk/platform-tools/adb -P 5037 -s d82f22e6 forward --remove tcp:10900'
[91f281d0][AndroidDriver] CDP data collection completed
[91f281d0][AndroidDriver] WEBVIEW_19100 mapped to pid 19100
[91f281d0][AndroidDriver] Getting process name for webview 'WEBVIEW_19100'
[91f281d0][ADB] Running '/Users/ci/Library/Android/sdk/platform-tools/adb -P 5037 -s d82f22e6 shell ps --help'
[91f281d0][ADB] Running '/Users/ci/Library/Android/sdk/platform-tools/adb -P 5037 -s d82f22e6 shell ps -A'
[91f281d0][AndroidDriver] Got process name: 'com.company.app.debug'
[91f281d0][AndroidDriver] Found 1 webview: ["WEBVIEW_com.company.app.debug"]
[91f281d0][AndroidUiautomator2Driver@f133] Available contexts: ["NATIVE_APP","WEBVIEW_com.company.app.debug"]

```
To get the version of system webview I use the following command:
```
 adb shell dumpsys webviewupdate
```
Which will return:
```
Current WebView Update Service state
  Fallback logic enabled: false
  Multiprocess enabled: true
  Current WebView package (name, version): (com.google.android.webview.canary, 130.0.6680.0)
  Minimum targetSdkVersion: 29
  Minimum WebView version code: -1
  Number of relros started: 2
  Number of relros finished: 2
  WebView package dirty: false
  Any WebView package installed: true
  Preferred WebView package (name, version): (com.google.android.webview.canary, 130.0.6680.0)
  WebView packages:
    Valid package com.google.android.webview (versionName: 127.0.6533.103, versionCode: 653310333, targetSdkVersion: 35) is  installed/enabled for all users
    com.google.android.webview.beta is NOT installed.
    com.google.android.webview.dev is NOT installed.
    Valid package com.google.android.webview.canary (versionName: 130.0.6680.0, versionCode: 668000033, targetSdkVersion: 35) is  installed/enabled for all users
    com.google.android.webview.debug is NOT installed.
    com.android.webview is NOT installed.
```
The above matches the Webview setting under developer options

**Comment by KazuCocoa** [comment]
Thanks. Could you share the result of `mobile:getContexts` and the full of appium server log as GIST with `chromedriver_autodownload` as well? So your appium server would run with `appium server --allow-insecure chromedriver_autodownload`.
https://github.com/appium/appium/issues/13812#issuecomment-2311695701

**Comment by afathonih** [comment]
@KazuCocoa let me spend some time to scrub and upload the log. Meanwhile, I have been running with chromedriver auto download option turned on as follows:
```
appium --debug  --relaxed-security --allow-insecure chromedriver_autodownload,execute_driver_script,adb_shell -pa=wd/hub --use-plugins images
```

**Comment by KazuCocoa** [comment]
Sure. This is my example. The emulator had chrome v128 and the webview (`com.google.android.webview`) was 113 with our sample app (https://github.com/appium/android-apidemos). Then, the context switch to WebView succeeded as below:

```
[Chromedriver@53bf] Spawning chromedriver with: /Users/kazu/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver_mac_arm64_v113.0.5672.63 --port=50201 --adb-port=5037 --verbose
[Chromedriver@53bf] ChromeDriver version: '113.0.5672.63'
[Chromedriver@53bf] Matched '/status' to command name 'getStatus'
[Chromedriver@53bf] Proxying [GET /status] to [GET http://127.0.0.1:50201/status] with no body
[Chromedriver@53bf] connect ECONNREFUSED 127.0.0.1:50201
[Chromedriver@53bf] Matched '/status' to command name 'getStatus'
[Chromedriver@53bf] Proxying [GET /status] to [GET http://127.0.0.1:50201/status] with no body
[Chromedriver@53bf] Got response with status 200: {"value":{"build":{"version":"113.0.5672.63 (0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912})"},"message":"ChromeDriver ready for new sessions.","os":{"arch":"arm64","name":"Mac OS X","version":"14.5.0"},"ready":true}}
[Chromedriver@53bf] Starting W3C Chromedriver session with capabilities: {
  "capabilities": {
    "alwaysMatch": {
      "goog:chromeOptions": {
        "androidPackage": "io.appium.android.apis",
        "androidUseRunningApp": true,
        "androidProcess": "io.appium.android.apis",
        "androidDeviceSerial": "emulator-5554"
      },
      "goog:loggingPrefs": {
        "browser": "ALL"
      }
    }
  }
}
[Chromedriver@53bf] Matched '/session' to command name 'createSession'
[Chromedriver@53bf] Proxying [POST /session] to [POST http://127.0.0.1:50201/session] with body: {"capabilities":{"alwaysMatch":{"goog:chromeOptions":{"androidPackage":"io.appium.android.apis","androidUseRunningApp":true,"androidProcess":"io.appium.android.apis","androidDeviceSerial":"emulator-5554"},"goog:loggingPrefs":{"browser":"ALL"}}}}
[Chromedriver@53bf] Webview version: 'Chrome/113.0.5672.136'
```

Possibly creating a new issue with logs would be better since your case could be a new pattern.

**Comment by AfLosada** [comment]
Hey I'm having the same error, and my case is pretty similar. I'm running a test on a real device that has chrome 80, but everything breaks when the test tries to navigate to the webview. 80 is the version detected by appium when it calls getContexts and lists the webview, but when I switch the context the chrome version that it tries to use is 137. 
This is the command I'm using to run appium server:

`appium server -ka 800 --allow-insecure chromedriver_autodownload,execute_driver_script,adb_shell --relaxed-security --use-plugins=device-farm --config ./server-config.json --log=appium-log.txt --plugin-device-farm-device-availability-timeout-ms=30000 -pa /wd/hub --plugin-device-farm-wda-bundle-id=com.xx.showCase`

**Comment by KazuCocoa** [comment]
Could you create a new bug ticket with the required logs by the template?

**Comment by AfLosada** [comment]
Hey Kazu after spending the last days working on it I found out it was just having a different WebView chromedriver in my phone than the one the phone supported. My phone is an old xiaomi that was using chrome driver v 80.x, but I somehow installed the 137.x chromedriver for the webview. Once I uninstalled it (by manually uninstalling the Webdriver app) stuff works now.
