### ISSUE TITLE
Performance issue while editing text fields [iOS, WebDriverAgent]

### ISSUE THREAD

**Issue by 4ndrey** [appium/appium#13819]
## The problem

I noticed strange performance issue with Appium / WebDriverAgent running on iPhone 6s and iPhone 8+ while editing text fields. In average text field edit action on iPhone 8+ takes 1 sec longer in comparison to iPhone 6s. The same situation happens while comparing iPhone XR / Xs Max with iPhone 6s.

From my point of view UI tests on faster devices (iPhone 8 / iPhone XR) should usually be quicker in comparison to iPhone 6 or at least executed within the same time.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Desktop OS/version used to run Appium: macOS 10.14.6
* Node.js version (unless using Appium.app|exe): v13.3.0
* Npm or Yarn package manager: npm 6.13.2
* Mobile platform/version under test: iOS 13.3
* Real device or emulator/simulator: real devices: iPhone 6s & iPhone 8plus

## Details

Firstly, I wrote simple test which opens system's Settings app, then navigates to Device Name, and repeating this action 10 times.
Execution times are almost the same, iPhone 8+ is slightly faster. [Expected behavior]
iPhone 6s = 42.12 sec vs iPhone 8+ = 41.85 sec

Secondly, I added new action to edit Device Name using text field. And now iPhone 6s executes test way faster, depending on number of editing actions (iPhone 8+ runs approx 1 sec longer per each edit action): 
iPhone 6s = 62.7 sec vs iPhone 8+ = 71.80 sec for 10 text edit actions.

Do you have any ideas or suggestions, why it is happening?

## Link to Appium logs

Full logs with showXcodeLog: true & showIOSLog: true:

https://github.com/4ndrey/appium-logs/blob/master/appium_iPhone6s_without_editing.log
https://github.com/4ndrey/appium-logs/blob/master/appium_iPhone6s_without_editing_xcode.log

https://github.com/4ndrey/appium-logs/blob/master/appium_iPhone6s_with_editing.log
https://github.com/4ndrey/appium-logs/blob/master/appium_iPhone6s_with_editing_xcode.log

---

https://github.com/4ndrey/appium-logs/blob/master/appium_iPhone8plus_without_editing.log
https://github.com/4ndrey/appium-logs/blob/master/appium_iPhone8plus_without_editing_xcode.log

https://github.com/4ndrey/appium-logs/blob/master/appium_iPhone8plus_with_editing.log
https://github.com/4ndrey/appium-logs/blob/master/appium_iPhone8plus_with_editing_xcode.log

## Code To Reproduce Issue

https://github.com/4ndrey/appium-logs/blob/master/test.py

**Comment by KazuCocoa** [comment]
https://gist.github.com/KazuCocoa/8cbd178dae1be9259ee47f76ac4bd14a

Picked up section between tap to send keys. It perhaps took time in clear action on iPhone 8+ than iPhone 6s. (Compared the time based on XCTest framework (testmanaged) timestamp)
Perhaps, XCTest framework has different performance between devices..

**Comment by 4ndrey** [comment]
@KazuCocoa I just have tried to comment out text field clear action and left only appending new text, but results are the same 6s is still ~N seconds faster (where N - number of edits). I also reviewed WDA's code and noticed some delays like: `[[NSRunLoop currentRunLoop] runUntilDate:[NSDate dateWithTimeIntervalSinceNow:1]];` or `[[[[FBRunLoopSpinner new] timeout:timeout] timeoutErrorMessage:@"Keyboard is not present"] spinUntilTrue:keyboardIsVisible error:error];` in text field editing related methods. Could it be a reason of such behavior?

**Comment by KazuCocoa** [comment]
Yes, could be.
All method performance depends on XCTest framework, but WDA tries to take care of some actions with checking its presence (for example) before conducting them to reduce XCTest flakiness.

**Comment by KazuCocoa** [comment]
Close once since it looks depending on XCTest side.
We're happy to reopen (or open another issue) this to improve performance in Appium side if we have the method
