### ISSUE TITLE
org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)

### ISSUE THREAD

**Issue by Akhila666** [appium/appium#13810]
Hi 
i am new to appium while running automation appium script  i am facing below issue can u pls help me. 
org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)

**Comment by mykola-mokhnach** [comment]
Kindly use [Appium forum](discuss.appium.io) to ask questions
