### ISSUE TITLE
Unable to pullFile - timeout

### ISSUE THREAD

**Issue by walkeraki** [appium/appium#13826]
## The problem

After upgrading appium to 1.15.1 I can no longer pull file from iOS device.
I resolved this problem on 2 macs by updating node and npm version to 12.13.1 and 6.12.1 and after doing same on 2 others computers did not help.

I also updated node to latest version 13.6.0 and it did not help

ifuse pull file works normally

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): 1.14
* Desktop OS/version used to run Appium: macOS
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real device

## Link to Appium logs

https://gist.github.com/walkeraki/173ba9960750442e222b461b759cc7b5

## Code To Reproduce Issue [ Good To Have ]

`    @Override
    public String saveApplicationLog(String outPath) {
        String logPath = socketDriver.getLogPath();
        String logFileName = FilenameUtils.getBaseName(logPath);
        File logFile = new File(outPath + File.separator + logFileName);
        String remoteFolder = "@" + appiumDriver.getSessionDetails().get("CFBundleIdentifier") + 
        "/Documents/";
        String fileNameWithExtension = FilenameUtils.getName(logPath);
        logPath = remoteFolder + fileNameWithExtension;
        byte[] logData = appiumDriver.pullFile(logPath);

        try {
            writeByteArrayToFile(logFile, logData);
        } catch (IOException e) {
            throw new FileException("Couldn't save log to file", e);
        }
        return logPath;
    }`

**Comment by walkeraki** [comment]
It worked with same code before upgrading appium to 1.15.1

**Comment by KazuCocoa** [comment]
Does increasing the pull timeout help?
https://github.com/appium/appium-xcuitest-driver/blob/master/lib/commands/file-movement.js#L17

**Comment by mykola-mokhnach** [comment]
Linking https://github.com/appium/appium-xcuitest-driver/pull/1140

**Comment by walkeraki** [comment]
> Does increasing the pull timeout help?
> https://github.com/appium/appium-xcuitest-driver/blob/master/lib/commands/file-movement.js#L17

No, it does not help.. I tried with 60000 but it doesn't work.. Wouldn't think it would need more then 30s to pull txt file anyway :)

**Comment by KazuCocoa** [comment]
What about the latest beta?
(Please make sure the beta has `appium-xcuitest-driver@3.12.1`)

**Comment by walkeraki** [comment]
It works on latest beta
