### ISSUE TITLE
TouchAction not working with CoordinatorLayout

### ISSUE THREAD

**Issue by vzenzo** [appium/appium#13828]
## The problem

TouchActions such as swipe, scroll or drag and drop do not work on CoordinatorLayout

## Environment

* Appium 1.16.0
* Windows/iOS
* Node.js v12.13.1
* Npm 6.13.1
* Android 9/ iOS 13
* Samsung A70, iPhone X, Emulators

## Details

The app I am trying to test has a part of screen that needs to be pulled upwards so you can enter data. The problem is appium sees the pull action as done but in reality no action is taken.

I have made a simple method for pulling the CoordinatorLayout up

```
public void drag(WebElement el1, String direction) {

    TouchAction drag = new TouchAction(d);
        int startX = el1.getLocation().getX();
        int startY = el1.getLocation().getY();
        int endY = startY - 500;
        drag.longPress(PointOption.point(startX,startY)).waitAction(waitOptions(ofMillis(2000))).moveTo(PointOption.point(startX, endY)).perform().release();
```

Now this works everywhere, and I mean everywhere in the app except on that one place with CoordinatorLayout. Just nothing happens and it continues to next steps. 

Is there a way to switch focus on that layout? Or frame? I have seen these kinda issues around on internet but no one answered them yet

Pls help, tyvm

**Comment by mykola-mokhnach** [comment]
Try to add more debugging to the application under test in order to see which actions are being generated by the automated script and compare them with the actions generated by the manual interaction.

**Comment by vzenzo** [comment]
In Appium logs it shows that it cannot find the element from the next step. 
So it seems like the pull up action is done, but it seems like it does it in some other frame layout

![pull](https://user-images.githubusercontent.com/52910214/72332699-caa74c00-36ba-11ea-9c15-c62339003676.png)

I've tried even with appium recorded but it doesn't work whatever I do

**Comment by mykola-mokhnach** [comment]
I'm not talking about appium logs, but rather the application under test. You'll need to add corresponding event handlers into the source code to see the difference

**Comment by mykola-mokhnach** [comment]
Consider moving the topic to Appium [forum](discuss.appium.io)
Closed as not an issue
