### ISSUE TITLE
iOS 13.3: Failure to Start Safari Test Session when Certain Pages are Loaded

### ISSUE THREAD

**Issue by Dan-Maor** [appium/appium#13824]
## The problem

During our testing we've noticed that sometimes Safari test session fails to start on devices running iOS 13.3 (doesn't appear to happen on 13.2.x and below).

Upon further investigation it seems that some pages cause Appium to fail to start a web testing session when they are the currently loaded page.

I've narrowed down a sample page to a minimum where the issue happens (see in https://gist.github.com/Dan-Maor/ce6a97832988094bb205ec89594203b7 the file test1.html). When commenting out or removing the `<input>` line the issue does not appear.

To reproduce the issue:

1. Open the attached web page from the GIST in Safari.
2. **Press the Home button to minimize Safari** (if Safari is killed or when a session is started when it is the front app, a blank page is loaded as the front page and the issue does not occur).
3. Attempt to start a Safari testing session.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0 (with remote debugger 7.5.1)
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: MacOS 10.14.6
* Node.js version (unless using Appium.app|exe): v10.15.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

https://gist.github.com/Dan-Maor/ce6a97832988094bb205ec89594203b7

**Comment by mykola-mokhnach** [comment]
Please try if https://github.com/appium/WebDriverAgent/pull/273 fixes the problem

**Comment by Dan-Maor** [comment]
Looks like it does. Initially I thought these were not related as it appeared to be something with the remote debugger not choosing a page, however this seems to do the trick.

Thanks!
