### ISSUE TITLE
Automation not supported on iOS 13.3

### ISSUE THREAD

**Issue by goyalbhavesh** [appium/appium#13820]
I am trying to run automation on iOS 13.3 with the following details:

Appium version: 1.15.1
XCode: 10.1 
Device support files for iOS 13.3 added

The automation fails on the sign up page on sendkeys. Does anyone has any idea on why its happening?

**Comment by KazuCocoa** [comment]
Please fill out the issue template, especially the full log as GIST

**Comment by KazuCocoa** [comment]
Close as no logs.
Potentially, like https://github.com/appium/appium/issues/13455 could happen if the issue was on WebView.
