### ISSUE TITLE
After updating to new Appium, it fails to recognise Webview content in both iOS 12 & 13 devices

### ISSUE THREAD

**Issue by rakurati7** [appium/appium#13821]
## The problem

I have a test case which goes through multiple web pages and verify element is present in the webpage. This use to work fine before but it stopped after moving to latest Appium. 

Appium is able to find the content of few webpages (wikipedia.org, youtube.com) and fails to find few like (nytimes.com, ebay.com, amazon.com)

## Environment

* Appium version : 1.16 Beta 3
* Last Appium version: 1.13
* Desktop OS: 10.14.6 also happening 10.15.2
* Node.js version: 13.5.0
* Npm : 6.13.4
* Mobile platform/version under test: 13.3.1, 12
* Real device or emulator/simulator: iPhone, iPad
* Appium CLI or Appium.app|exe: Both

## Details

I have followed all the issues so far reported with webview (13361, 13285). I am unable to resolve my issue yet. The webview using is WKwebview.

## Link to Appium logs

[Appium logs](https://gist.github.com/rakurati7/b644fbf0e2ff83dcb7dbf4dd56d2b3a8)

ios-webkit-debug-proxy 1.8.5_2
appium-xcuitest-driver@3.12.0
appium-ios-device@1.2.1
appium-remote-debugger@6.7.0

<img width="1560" alt="yahoo_webview_content" src="https://user-images.githubusercontent.com/28534128/72167092-7cf7be80-33f0-11ea-9a29-8255917ecce8.png">

**Comment by imurchie** [comment]
I do not understand what you are trying to do. There seems to be no accessing the web in your logs.

**Comment by amedvedjev** [comment]
As i understood before we where able to see web elements without switching to webView. With latest Appium we cant any more. And this is true for ios.

**Comment by imurchie** [comment]
I guess this might be affected by https://github.com/appium/WebDriverAgent/pull/273

**Comment by rakurati7** [comment]
@imurchie 

> I do not understand what you are trying to do. There seems to be no accessing the web in your logs.

it

**Comment by mykola-mokhnach** [comment]
The mentioned fix has been published to appium@beta

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by jineshqa** [comment]
@rakurati7 could you please share how to use new settings mentioned in https://github.com/appium/WebDriverAgent/pull/273? A example gist would be ideal. Thanks in advance.
