### ISSUE TITLE
iOS 10.x: Unable to Start Safari Tests - webinspectord Crashes

### ISSUE THREAD

**Issue by Dan-Maor** [appium/appium#13825]
## The problem

It seems that on the latest version of Appium attempting to start a Safari test session on iOS 10 devices causes webinspectord to crash on the device (verified on iOS 10.1.1 to 10.3.2).

It seems that the issue started occurring after the IWDP dependency was dropped. Verified that Safari tests work on v1.14.2.

Attached GIST with syslog, appium server log and crash report.
https://gist.github.com/Dan-Maor/61025618dfb0f55d8d1c18681f3a3f3f

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0 beta (with the latest remote debugger)
* Last Appium version that did not exhibit the issue (if applicable): 1.14.2
* Desktop OS/version used to run Appium: MacOS 10.14.6
* Node.js version (unless using Appium.app|exe): v10.15.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs
https://gist.github.com/Dan-Maor/61025618dfb0f55d8d1c18681f3a3f3f

**Comment by mykola-mokhnach** [comment]
I would say we should officially state iOS 10 and below is not supported by Appium 1.16+
It is just too much pain to keep the backward compatibility

**Comment by Dan-Maor** [comment]
Looks like webinspectord in iOS 10 can't handle receiving blank messages (such messages are sent after every message (https://github.com/appium/appium-ios-device/pull/60).

Going to create a PR with a fix (preventing sending a blank message after every message for iOS < 11).
