### ISSUE TITLE
Jenkins appium android test

### ISSUE THREAD

**Issue by morkovkin** [appium/appium#13822]
## The problem
Hello! i try to start my test in jenkins ci. In my application i wanna test facebook login. 

## Environment
* Appium v1.16.0
* Operating System: Ubuntu 16.04.6 LTS
            Kernel: Linux 4.15.0-74-generic
      Architecture: x86-64
* Mobile platform/version under test: Android api 29
* Real device or emulator/simulator: emulator

## Details

I read about context and my test code look like this.

```        
        checkoutToWebContext();
        driver.findElement(By.id("m_login_email")).sendKeys(login);
        driver.findElement(By.id("m_login_password")).sendKeys(password);
        driver.findElement(By.id("u_0_4")).click();

        wait.until(ExpectedConditions.elementToBeClickable(
            By.name("__CONFIRM__"))).click();

        checkoutToNativeContext();

....
 private void checkoutToWebContext() {
        for (final String s : driver.getContextHandles()) {
            System.out.println("Context " + s);
            if (s.contains("WEBVIEW")) {

                driver.context(s);
            }
        }
    }

    private void checkoutToNativeContext() {
        for (final String s : driver.getContextHandles()) {
            if (s.contains("NATIVE_APP")) {
                System.out.println("Context2 " + s);
                driver.context(s);
            }
        }
    }

```

When i run test in my mac all it's ok. I see 2 contexts (Native and Web)  in log, but when i run test in ci i see only one context ( Native ). 

My shell script:
```
set -e
set -v

adb kill-server || true
adb start-server

# start AVD
$ANDROID_HOME/emulator/emulator @AppiumDevice -ports 5554,5555 -no-audio -no-window -no-snapshot > ~/emulator.log 2>&1 &
sleep 1
adb -s emulator-5554 wait-for-device shell getprop dev.bootcomplete

# start Appium
appium > ~/appium.log 2>&1 &
sleep 1

adb -s emulator-5554 uninstall com.test.test || true
adb -s emulator-5554 install openplay/build/outputs/apk/app/release/app.apk

./gradlew appiumtests:testReleaseUnitTest

# stop AVD
adb -s emulator-5554 emu kill
```

Is it possible that appium can't find web context because my emulator run without display? I don't shore because when i run seem configuration in my laptop it's fine (with out display too)

How can i run appium test in ci? What can affect the application server after which it starts to process only 1 context?

I read about chromedriver but it's not help... Please help me :)

**Comment by mykola-mokhnach** [comment]
Please attach the full server log. Is the web view accessible with Chrome remote debugger?

**Comment by morkovkin** [comment]
I check accessible in appium ui.. I find ids in chrome inspector. Here is log https://drive.google.com/open?id=1lC_7tEXIHZJ51n3M_0hXvMHwNyhUsX4y

**Comment by morkovkin** [comment]
i don't know it's help or not but here is my local (success) log https://drive.google.com/open?id=1r-3XysCXTN8-4qqvuAulnY1dl8eCVdBA

**Comment by mykola-mokhnach** [comment]
Since Android 10 Google has changed some internal web view identifiers. Try if appium@beta works there. Also make sure the same build is used locally and remotely. It might also be that the emulator is slightly slower on the remote machine. Check if the client script has appropriate timeouts.

**Comment by morkovkin** [comment]
Yes code and build are seem, environment is seem too. I try to get elements in native context like  driver.findElement(By.xpath("//android.widget.EditText")).sendKeys(login); but i can't wait event when webview change content. It's problem becouse i cant (from test code) understand when button driver.findElement(By.xpath("//android.widget.Button")) confirm or it's steel login. But i wanna use web context to make my test more stable. Why i get only native context?

**Comment by mykola-mokhnach** [comment]
It looks like nobody here knows the answer. Consider moving the topic to Appium [forum](discuss.appium.io).
