### ISSUE TITLE
How to run appium from my python code?

### ISSUE THREAD

**Issue by FormationGrowthHacking** [appium/appium#13830]
Hi,

Sorry for posting my question here but we can’t register in appium forum as notifications mails are not sent anymore. So I can’t activate my account on forum.

I am using python 3.7 for my test on android real devices.

I’d like to detect from my python code the connected real devices, and then detect the desired capabilities In order to run appium from my code.... and then run the code on several real devices.

The idea is to handle everything from python code:

detect devices,
detect platform, name, serial, etc (the desired caps)
start appium
and then start the test code on 2 connected real devices.
Anyone has already done that in the past? Do you know any tuto?

**Comment by mykola-mokhnach** [comment]
Please provide your nickname on the forum, so we could activate your account manually. Somehow the forum engine recognises several email addresses as non valid and does not send activation emails, although for other email addresses it works smoothly.

**Comment by FormationGrowthHacking** [comment]
Thanks for quick reply.
 
I forgot which username I filled. It should be fgh or formationgrowthhacking  
 

 
I registered with an email ....@formationgrowthhacking.com
 

 
Kind regards
 
 
 
>  
>
>

**Comment by mykola-mokhnach** [comment]
Your account has been activated. Please move the topic to the forum

**Comment by FormationGrowthHacking** [comment]
Thanks
