### ISSUE TITLE
closing session unexpected, Shutting down because we waited 60 seconds for a command

### ISSUE THREAD

**Issue by chenchengyuan** [appium/appium#13839]
### my second session was closed unexpected
Hello, actions here:
```
16:59:53 use caps1 creat first session on localhost:4723
  no action
17:00:00 use caps2(just 'noReset' diff with caps1) creat second session on localhost:4723
  action_1  success
  action_2  success
...
...
17:00:53 action_x success
17:00:53 
2020-01-15 17:00:53:899 - [BaseDriver] Shutting down because we waited 60 seconds for a command
2020-01-15 17:00:53:899 - [Appium] Closing session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'

action_x+1  fail
action_x+2  fail
```

## Environment

* Appium version (or git revision) that exhibits the issue: v1.16.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:  osx 10.15.1
* Node.js version (unless using Appium.app|exe):  v8.16.2
* Npm or Yarn package manager:
* Mobile platform/version under test: android 10 / huawei_emui 10.0
* Real device or emulator/simulator: real
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs
[log here](https://gist.github.com/chenchengyuan/10bc502e874df3e80ebf2cb1a193d15b)

**Comment by chenchengyuan** [comment]
need close session

**Comment by NihaoRay** [comment]
Hi, you can refer this blog https://www.jianshu.com/p/728cb9ffc7dc. It means you should prolang the new command timeout.

in my code
`capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, "3000");`

**Comment by YukiSou** [comment]
Since the `newCommandTimeout` in desired capabilities default to 60 and may cause problems, why not set it to zero or just remove it from the desired capabilities?
Is there any use scenario for this option?
