### ISSUE TITLE
Cannot get 'xml' source of the current application

### ISSUE THREAD

**Issue by shibupanda** [appium/appium#13831]
## The problem
Not able to get page source in a particular page and the error we are getting is "Cannot get 'xml' source of the current application"

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MAC
* Node.js version (unless using Appium.app|exe): 10.16.3
* Npm or Yarn package manager: npm
* Mobile platform/version under test: 13.*
* Real device or emulator/simulator: Realdevice
* Appium CLI or Appium.app|exe: Appium CLI

## Details

When we have tried with the same application on 12.* ios series devices we are able to get the page source but same is not happening on 13.* series of iOS devices in one particular page there we stuck.

## Link to Appium logs
https://gist.github.com/shibupanda/868a5b9260971fc0eba86e65702b4cf7
https://gist.github.com/shibupanda/e16f3645e05bb1c2eb5c45f34f61a085

## Code To Reproduce Issue [ Good To Have ]
driver.getPageSource()

**Comment by shibupanda** [comment]
Even we have tried the closed issue.
https://github.com/appium/appium/issues/13595

**Comment by mykola-mokhnach** [comment]
Check if appium@beta works. If it does not help then the problem lies somewhere on XCTest side and we would not be able to address it

**Comment by veeravnkt7** [comment]
@shibupanda  and I are facing this issue. To add some information on this, issue is observed in the device OS of version 13.3 (upgraded from v13.1.3 to v13.3). Didn't see any of this type of issues in v13.1.3.

**Comment by shibupanda** [comment]
@veeravnkt7 
I have tried to build Webdriveragent from master branch and it worked for me. Please apply the same.
