### ISSUE TITLE
Error: Connection was refused to port 8100

### ISSUE THREAD

**Issue by georgekucher** [appium/appium#13836]
## The problem

Getting this message multiple times until timeout. Reproduces only on appium console for quite a long time ~(1.13-1.16).
Appium Desktop (1.15.1) works well.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16
* Last Appium version that did not exhibit the issue (if applicable):  not sure
* Desktop OS/version used to run Appium: macOS Mojave 10.14.6
* Node.js version (unless using Appium.app|exe): 13.6.0
* Npm package manager: 6.13.4
* Mobile platform/version under test: 13.3
* Real device: iPhone 8 Plus
* Appium CLI

## Details

Checked all existing issues. Suggested solutions didn’t help.
Please help.

## Link to Appium logs

Bad and Good 

https://gist.github.com/georgekucher/64cc8c677a86f76aaca26542b4f0aab2

**Comment by mykola-mokhnach** [comment]
> 2020-01-14 11:17:03:678 [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

This is the source of the problem. The exception is thrown because there is no connection to the WDA server as it is not running on the device under test

You could get more information on the error if you enable Xcodebuild logging from capabilities

**Comment by georgekucher** [comment]
This is build machine (CI)
On my local macbook all works fine
I did everything following the instructions many times.

Going to enable Xcodebuild logging.
Thanks.

**Comment by margasan** [comment]
1. this article is outdated - [http://appium.io/docs/en/drivers/ios-xcuitest-real-devices/]
2. I have found an interesting thing that appium 1.16 has two different places in which we have to sign WebDriverAgent.xcodeproj 
```
/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj
/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj 
```
In my opinion, these discrepancies should be emphasized in docs or removed to prevent such situation

**Comment by georgekucher** [comment]
> 1. this article is outdated - [http://appium.io/docs/en/drivers/ios-xcuitest-real-devices/]
> 2. I have found an interesting thing that appium 1.16 has two different places in which we have to sign WebDriverAgent.xcodeproj
> 
> ```
> /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj
> /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj 
> ```
> 
> In my opinion, these discrepancies should be emphasized in docs or removed to prevent such situation

Yes.
The second place is the right one.

**Comment by mykola-mokhnach** [comment]
Only `node_modules/appium-webdriveragent/` should be the right root folder for WDA for Appium 1.16

The other one should be deleted if exists

**Comment by mykola-mokhnach** [comment]
it actually depends on npm which folder is put to the modules root and which one is put under `appium-xcuitest-driver`

**Comment by georgekucher** [comment]
> Only `node_modules/appium-webdriveragent/` should be the right root folder for WDA for Appium 1.16
> 
> The other one is probably used by other drivers (most likely Flutter)

If the second place is not signed it fails

**Comment by georgekucher** [comment]
[1appium-port-4728.log.txt](https://github.com/appium/appium/files/4059613/1appium-port-4728.log.txt)
here is the log

**Comment by mykola-mokhnach** [comment]
In the log it is clearly visible which WDA path is used:

> 2020-01-13 11:54:33:666 [XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent'

**Comment by mykola-mokhnach** [comment]
And this is the original cause:

> 2020-01-13 11:55:34:037 [XCUITest] 	Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the Signing & Capabilities editor.

**Comment by georgekucher** [comment]
@mykola-mokhnach enabling Xcodebuild logging from capabilities needs to make changes to the Core of our framework which is not belongs to me (it will take some time)
Do you have any other suggestions?

**Comment by georgekucher** [comment]
> In the log it is clearly visible which WDA path is used:
> 
> > 2020-01-13 11:54:33:666 [XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent'

Why then??

![image](https://user-images.githubusercontent.com/14803952/72352876-bd568580-36eb-11ea-9475-578c5e3ca4f2.png)

**Comment by mykola-mokhnach** [comment]
> it actually depends on npm which folder is put to the modules root and which one is put under appium-xcuitest-driver

Although you are right, the documentation should be updated to reflect this case

**Comment by georgekucher** [comment]
@mykola-mokhnach Please provide an exact name of Xcode logging capability

**Comment by mykola-mokhnach** [comment]
`showXcodeLog`

**Comment by mykola-mokhnach** [comment]
The documentation has been updated. Closed as not an issue

**Comment by jackeymason** [comment]
Hello, 
The WebdriverAgent isn't running on a simulator for me. I'm working through the Appium Pro Workshop and on the Appium Sessions section. Everything works as expected with an Android Simulator. With IOS, the WDA and application get installed, but the Appium Server can't connect to the WebdriverAgent. 

[debug] [XCUITest] Starting WebDriverAgent initialization with the synchronization key 'XCUITestDriver'
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response with status undefined: {"errno":-61,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}

Appium tries repeatedly but fails to connect. I verified nothing is running on port 8100 before during or after I run the IOSCapabilitiesTest.

I know this bug is marked as closed but I don't see a workaround or fix submitted above.
Any help would be much appreciated. Thank you.

**Comment by PHUITesting** [comment]
Is there anyway to change where http://localhost:8100/status or 127.0.0.1","port":8100 are going? My appium server says 0.0.0.0:4723 so I think a problem might be reaching out to the wrong port/ip.

Eventually it errors out with:

[info] [35m[WD Proxy][39m Got response with unknown status: {"code":"ECONNRESET"}[error] [35m[Xcode][39m 2020-08-11 09:45:21.348 xcodebuild[22597:58545]  DTDeviceKit: Could not start house arrest service for app identifier com.facebook.WebDriverAgentRunner.xctrunner [Error Domain=com.apple.dtdevicekit Code=-402653093 "Xcode encountered an error" UserInfo={NSLocalizedFailureReason=Too many instances of this service are already running.

**Comment by jaspreetch** [comment]
I also faced this issue . In my situation, I have installed appium both via npm as well as Appium Desktop.
I was running Appium server via Appium Desktop and was constantly getting this error.

I checked logs and found that WebDriverAgent.xcodeproj was located at **/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent/** in case of **Appium Desktop** and at  **/Users/_username_/.nvm/versions/node/v_nodeversion_/lib/node_modules/appium/node_modules/appium-webdriveragent** (I installed node via nvm) for **appium installed via node**.

I followed steps given in https://appium.io/docs/en/drivers/ios-xcuitest-real-devices/#full-manual-configuration  for both locations and automation worked for me.  ( Note: App signing was done using Apple developer account).
