### ISSUE TITLE
Android bootstrap socket crashed.

### ISSUE THREAD

**Issue by chetanJTH** [appium/appium#13838]
## The problem

I am trying to run Test on multiple device in parallel. but i am getting error on one device but other run fine.
I have added my project on git.
Please find project and help me to set up parallel testing. 

https://github.com/chetanJTH/parallel/issues

**Comment by mykola-mokhnach** [comment]
Please fill out the issue report properly.
Refer https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/parallel-tests.md to setup parallel sessions

**Comment by chetanJTH** [comment]
**The problem**
I have an already working appium test for single device. but when i try for more than one device it gives below mentioned Error.

Android bootstrap socket crashed: Error: connect ECONNREFUSED

I am using driver.quit() at end of test so sometime one driver get fail just after loading on device where another device work without any problem.

error : org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Android bootstrap socket crashed: Error: This socket has been ended by the other party (WARNING: The server did not provide any stacktrace information)  

**Environment**
Appium version: 1.13.0. 
Last Appium version that did not exhibit the issue (if applicable): Not applicable.
Desktop OS/version used to run Appium: Window 7
Node.js version (unless using Appium.app|exe): 10.15.3
Mobile platform/version under test: Andorid 8 and Android 9
Real device or emulator/simulator: 
Appium CLI or Appium.app|exe: Appium CLI
**Details**
Been stuck on this for a few days. I am new with appium and know basic thing with java so hard to code for it. i'm learning appium and want to resolve above issue and want to run same test on more than 1 device.
I have developed test suite and i want to run them with separate device.

**Comment by mykola-mokhnach** [comment]
Please use the most recent Appium version. Also the UiAutomator1 automation backend is obsolete on Android6+

**Comment by chetanJTH** [comment]
@mykola-mokhnach : I'm not using UiAutomator1.

**Comment by chetanJTH** [comment]
@mykola-mokhnach : After installing appium v 1.16.0-beta.3 i'm getting same problem. sometime it work fine but sometime it don't even start and gives error mentioned below.

connect ECONNREFUSED
Ill-formed XML document

**Comment by mykola-mokhnach** [comment]
> I don't use UiAutomator1

According to this log line you do

>  sometime it work fine but sometime it don't even start and gives error mentioned below.

Sorry, there is nothing to say there without the detailed server log. Did you follow the document mentioned above to setup your test?

**Comment by chetanJTH** [comment]
@mykola-mokhnach  

I'm not using two cap for different device and i'm using parameters in  'TestNG.xml' file for parallel test.

**Comment by mykola-mokhnach** [comment]
> Sorry, there is nothing to say there without the detailed server log

**Comment by chetanJTH** [comment]
@mykola-mokhnach 

 I don't know how to capture server log when appium start programmatically.

**Comment by mykola-mokhnach** [comment]
We have the [forum](discuss.appium.io). Feel free to ask your questions there.

**Comment by chetanJTH** [comment]
@mykola-mokhnach  : achieved parallel test by starting appium manually on two different port. now just want it to start programmatically.

**Comment by mykola-mokhnach** [comment]
Please use the forum for questions. Closed as not an issue
