### ISSUE TITLE
Error "io.appium.java_client.NoSuchContextException: No such context found." when try switch on ads in native app android

### ISSUE THREAD

**Issue by morkibka** [appium/appium#13834]
## The problem

I use "driver.context("WEBVIEW")" to switch on interstitial ads in android native app to try close it, but get error "NoSuchContextError: No such context found."

## Environment

* Appium  1.16.0
* macOS Catalina 10.15
* Npm 6.13.4
* Android 7.0
* Real device 
* Appium.app

## Link to Appium logs

https://gist.github.com/morkibka/35fa1c7a8b69eb11c8ab68a07616e9e7

## Code To Reproduce Issue [ Good To Have ]

https://gist.github.com/morkibka/ebe32b6d6ac8b1447912050cb382a41b

**Comment by imurchie** [comment]
Are the ads in a webview? The system does not think there are any.

**Comment by morkibka** [comment]
> Are the ads in a webview? The system does not think there are any.
yes, fullscreen interstitial in webview, why system can't see it, have any idea?

**Comment by mykola-mokhnach** [comment]
Does chrome remote debugger detect the web views?

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by Dheeerazzz** [comment]
Het, I have the same issue. I am not being able to interact with the close button in the interstitial ads. Can you help me.
