### ISSUE TITLE
Can't run Android tests on emulator

### ISSUE THREAD

**Issue by maros24** [appium/appium#13848]
## The problem

When I try to run tests on emulator I got this error. When I run the same code for iOS test, it works correctly,

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Desktop OS/version used to run Appium: macOS 10.14.6
* Node.js version (unless using Appium.app|exe):10.15.0
"platformName": "Android",
  "platformVersion": "8.1",
  "deviceName": "emulator-5554",
  "automationName": "UiAutomator2",

## Link to Appium logs

[BaseDriver] The capabilities ["allowTestPackages"] are not standard capabilities and should have an extension prefix
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
13:15:17.147 [main] INFO  com.configuration.driverConfiguration.driver.DriverRunner - Running on: android Address: http://127.0.0.1:4723/wd/hub
[BaseDriver] The capabilities ["allowTestPackages"] are not standard capabilities and should have an extension prefix
[HTTP] Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.
Fatal Error: listen EADDRINUSE: address already in use 127.0.0.1:4723
    at Server.setupListenHandle [as _listen2] (net.js:1290:14)
    at listenInCluster (net.js:1338:12)
    at doListen (net.js:1471:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id

**Comment by mykola-mokhnach** [comment]
> [HTTP] Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.
> Fatal Error: listen EADDRINUSE: address already in use 127.0.0.1:4723

I assume the error message is pretty clear there. Just select some other non-busy port

**Comment by maros24** [comment]
> > [HTTP] Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.
> > Fatal Error: listen EADDRINUSE: address already in use 127.0.0.1:4723
> 
> I assume the error message is pretty clear there. Just select some other non-busy port

When I select another port I have the same problem with selected port

**Comment by mykola-mokhnach** [comment]
Perhaps there is an issue in how the server and session startup is configured. Although, I cannot say nothing there, because no relevant information has been provided
