### ISSUE TITLE
(Appium 1.16.0) is taking long a time to stop the debugging process on Visual studio 2019  

### ISSUE THREAD

**Issue by Basha1** [appium/appium#13843]
## The problem

(Appium 1.16.0) is taking long a time to stop the debugging process on Visual studio 2019  

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable): **1.15.1**
* Desktop OS/version used to run Appium: **1.16.0**
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: **Android**
* Real device or emulator/simulator: **Real Devices**
* Appium CLI or Appium.app|exe:

## Details

When running Unit-test and in debug mode the test takes at least 2 minutes to stop the process.

**Comment by mykola-mokhnach** [comment]
Unfortunately the given information does not help much. Please try to figure out what exactly is slow (the reason can also be the client side)

**Comment by mykola-mokhnach** [comment]
Closed because of no response
