### ISSUE TITLE
[Android 10] accept_alert dismisses the alert instead.

### ISSUE THREAD

**Issue by mharis05** [appium/appium#13842]
## The problem

`alert.accept` dismisses the alert instead of accepting it on Android 10, however, on older versions, it accepts the alert properly.

## Environment

* Appium version: 1.15.1
* Desktop OS/version used to run Appium: MacOS 10.15.2
* Mobile platform/version under test: Android 10
* Real device or emulator/simulator: Real Device

## Details

I am handling Location permissions pop-up with alerts. After switching to the alert, I expect `alert.accept` to tap on allowing the permission. However, the statement results in rejecting permission (Deny).

<img width="325" alt="Screenshot 2020-01-15 at 16 07 06" src="https://user-images.githubusercontent.com/33764343/72445145-8c408880-37b1-11ea-909a-b8f514c2909b.png">

## Link to Appium logs
[Appium Logs](https://gist.github.com/mharis05/fe62cabd20cf21e16e4a949e736ca09d)

## Code To Reproduce Issue [ Good To Have ]

```
alert = driver.switch_to.alert
alert.accept
```

**Comment by mykola-mokhnach** [comment]
Could you also attach the page source output when this alert is shown? I assume since Android10 the controls ids/alert structure has been changed

**Comment by mharis05** [comment]
> Could you also attach the page source output when this alert is shown? I assume since Android10 the controls ids/alert structure has been changed

Sure.

[Here](https://gist.github.com/mharis05/7d899161829886f57487b98e4a6b14d3)

**Comment by mykola-mokhnach** [comment]
I'll add some changes to the server code, but this stuff is anyway not very reliable, because it could be changed depending on what application developers decide. The best way to properly detect alert buttons is to use the `mobile: acceptAlert` or `mobile: dismissAlert`, which support `buttonLabel` argument. There you could simply assign the text of the actual button to be pressed.

**Comment by mharis05** [comment]
Yes, that's also what I was wondering about, because of the variation in how alert appears like the number of buttons. I will use the label to resolve this in my own code. Thank you!

**Comment by mykola-mokhnach** [comment]
The change has been published to appium@beta
