### ISSUE TITLE
Appium forces ListView (Xamarin) to create view for all items

### ISSUE THREAD

**Issue by nikolai-mazurkevich** [appium/appium#13849]
## The problem
Appium forces ListView to create view for all items. This can hang up the app when the ListView contains a lot of items. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium:  macOS Catalina 10.15.2
* Node.js version (unless using Appium.app|exe): -
* Mobile platform/version under test: iOS 13.3
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium.app
* Xcode 11.3
* Visual Studio 2019

## Details
![AppiumDesktop](https://user-images.githubusercontent.com/59954746/72532224-0f321380-3884-11ea-9d53-bfc5f4198460.png)

For comparison, the hierarchy receiving from appium and the real hierarchy of visible elements:
[pageSource_appium.txt](https://github.com/appium/appium/files/4071803/pageSource_appium.txt)
[UIHierarchy.txt](https://github.com/appium/appium/files/4071804/UIHierarchy.txt)

## Link to Appium logs
[appium-server-logs.txt](https://github.com/appium/appium/files/4071740/appium-server-logs.txt)

## Code To Reproduce Issue
[App1.zip](https://github.com/appium/appium/files/4071745/App1.zip)

### Expected behavior
   Appium creates a hierarchy for visible items only

**Comment by amedvedjev** [comment]
It is iOS XCUTest feature to see not only elements that are on screen. You can see same in xCode layout viewer.

**Comment by mykola-mokhnach** [comment]
Appium cannot not "force" anything - it only reflects what XCTest and the accessibility framework are returning to it

**Comment by nikolai-mazurkevich** [comment]
Is there any way to avoid this behavior?

**Comment by mykola-mokhnach** [comment]
Nothing I know of

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
