### ISSUE TITLE
[iOS] Simulator crashes when XCUITests is parsing the DOM of the app.

### ISSUE THREAD

**Issue by Markaleth** [appium/appium#13841]
## The problem

The app crashes whenever the automation framework opens a specific app activity. This issue cannot be reproduced by manually accessing the screen in question. 

## Environment

* Appium version: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): 1.15.1
* Desktop OS/version used to run Appium: Mac OS Catalina 10.15.2
* Node.js version: v10.5.0
* Mobile platform/version under test: iOS13.3 
* Simulator
* Appium CLI
* Xcode 11.3

## Details

This issue occurred as a result of compiling the app under test with Xcode 11.3. 
Appium, the Appium Java bindings, Selenium or anything else were not changed between tests and did not exhibit this issue while the app was compiled with Xcode 10.2.1. 

The only reference i found to this issue is https://forums.developer.apple.com/thread/122972 . 

I was wondering if anyone else encountered any similar issues with native apps after switching to Xcode 11.3 .

## Link to Appium logs
Link to the error message i managed to catch that had any meaningful info on the cause of the crash:
https://gist.github.com/Markaleth/d4ece56461f187b31f5a14edc13e1413

EDIT: Reproduced with Xcode 11.3.1 as well. :(

**Comment by Markaleth** [comment]
EDIT 2: 
I know it's been marked as a 3rd party issue (XCUITest issue) but i'm gonna update the ticket in case anyone else came across this and has been wondering what the cause is.


The crash appears to occur when XCUITests is parsing the DOM of the app. If i dodge the screen where i usually reproduce it (it's a modal screen that gets called if users don't have some data filled in), the app still crashes because it's the screen under the modal that's causing the parsing exception to happen.

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing we can do there from Appium side. Consider reporting the issue to Apple
