### ISSUE TITLE
 [Xcode] testRunner encountered an error (Encountered a problem with the test runner after launch. (Underlying error: Lost connection to DTServiceHub))

### ISSUE THREAD

**Issue by shibupanda** [appium/appium#13844]
## The problem
WebDriverAgentRunner: [Xcode] testRunner encountered an error (Encountered a problem with the test runner after launch. (Underlying error: Lost connection to DTServiceHub))

Difficult to upgrade to latest version. Is there any workaround or solution to avoid these issue with same configuration.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.12.1
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: Mac Mojave
* Node.js version (unless using Appium.app|exe): 10.*
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS 12.0.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI
* Xcode: 10.3

## Details
Getting WebDriverAgentRunner: [Xcode] testRunner encountered an error (Encountered a problem with the test runner after launch. (Underlying error: Lost connection to DTServiceHub))
after few minutes of run

## Link to Appium logs
https://gist.github.com/shibupanda/a268b50ff0fe0518785d95fc3ae82bc8

**Comment by shibupanda** [comment]
@mykola-mokhnach Any update on the above or any suggestions to overcome these issues.

**Comment by mykola-mokhnach** [comment]
Update Appium server

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing more we could do there. Closed as third party issue
