### ISSUE TITLE
How long can appium tests run without crashing or misbehaving?

### ISSUE THREAD

**Issue by hadrianjmnz90** [appium/appium#13856]
## The problem

I want to know if there are any time restrictions on running appium tests, i have noticed that the longer the tests the easier tests start to fail, for example i can run some tests over and over for 1-2  hrs without a problem, but after that time  i start getting the following errors: 
1. An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up
2.  Original error: The instrumentation process cannot be initialized within 30000ms timeout. Make sure the application under test does not crash and investigate the logcat output. You could also try to increase the value of 'uiautomator2ServerLaunchTimeout' capability. 
3. org.openqa.selenium.WebDriverException: org.apache.http.conn.HttpHostConnectException: Connection refused (Connection refused)

As i mentioned the only variable that makes sense to me is the time that appium runs without being closed, because all the test pass as expected but after some time, could be 2 hrs, sometimes less sometimes more, i got the mentioned errors. i would appreciate any help on this.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Desktop OS/version used to run Appium: macos mojave 10.14.5
* Node.js version (unless using Appium.app|exe): 12.11.1
* Npm or Yarn package manager: 6.12.0
* Mobile platform/version under test: IOS and ANDROID
* Real device or emulator/simulator: any, i have tried with iphone 8, X, 7, Android sammsung galaxy, lg, nexus, motorola with android 5.1 - android 9.0 

## Code To Reproduce Issue [ Good To Have ]
    public AndroidDriver<MobileElement> installedAppCaps(String deviceName, String platformVersion, Integer port, Integer port2, String appName) throws Exception {
        System.out.println("START SERVER");
        service = new AppiumServiceBuilder().usingPort(port).
                withArgument(GeneralServerFlag.LOG_LEVEL, "error").withArgument(GeneralServerFlag.LOG_LEVEL, "warn").build();
        service.start();
        if (service == null || !service.isRunning()) {
            throw new AppiumServerHasNotBeenStartedLocallyException("Appium service node not started");
        }

        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
        capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, platformVersion);
        capabilities.setCapability(MobileCapabilityType.APPLICATION_NAME, appName);
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, deviceName);
        capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "uiautomator2");
        capabilities.setCapability(AndroidMobileCapabilityType.DONT_STOP_APP_ON_RESET, true);
        capabilities.setCapability("appium:uiautomator2ServerLaunchTimeout", 20000);
        capabilities.setCapability(MobileCapabilityType.NO_RESET, true);
        capabilities.setCapability(MobileCapabilityType.FULL_RESET, false);
        capabilities.setCapability(AndroidMobileCapabilityType.DEVICE_READY_TIMEOUT, 5000);
        capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 6000);
        capabilities.setCapability(MobileCapabilityType.CLEAR_SYSTEM_FILES, true);;

        driver = new AndroidDriver(service.getUrl(), capabilities);
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
        return driver;
    }

**Comment by mykola-mokhnach** [comment]
In theory the tests could run an unlimited period of time. Of course, the `unlimited` term does not exist in the engineering world, so when we set constants then we aim to at least 24 hours per test.

Regarding your issue in Android the reason could be anything. See https://github.com/appium/appium/issues/13807 for more details. 

I would try to extract the logcat output for the time period the above error happens and check for possible error messages there.

**Comment by samm52** [comment]
I've had tests run for 3.5 days straight, every 2 hours, with about 7 tests running each time. Appium isn't stopped in between and its all running from a timer on Jenkins. I've seen problems 1 and 3 more when running locally or over WiFi and wrote about that in [#13807](https://github.com/appium/appium/issues/13807).

**Comment by hadrianjmnz90** [comment]
> In theory the tests could run an unlimited period of time. Of course, the `unlimited` term does not exist in the engineering world, so when we set constants then we aim to at least 24 hours per test.
> 
> Regarding your issue in Android the reason could be anything. See #13807 for more details.
> 
> I would try to extract the logcat output for the time period the above error happens and check for possible error messages there.

got it, thanks

**Comment by mykola-mokhnach** [comment]
Consider moving the topic to Appium forum is you have more questions.
