### ISSUE TITLE
[iOS] Unable to find an element when `includeNonModalElements:true` 

### ISSUE THREAD

**Issue by mwakizaka** [appium/appium#13859]
## The problem
After updating appium setting `includeNonModalElements` to `true`, in Appium 1.16.0 it cannot find an element which exists in the following red rectangle. Whereas it's possible to find the element in Appium 1.15.0.
<img width="300" alt="Screen Shot 2020-01-21 at 18 20 46" src="https://user-images.githubusercontent.com/21286384/72791641-fefea780-3c7a-11ea-9811-785c88c1e40b.png">

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0
* Last Appium version that did not exhibit the issue (if applicable): 1.15.0
* Desktop OS/version used to run Appium: macOS Catalina(10.15.2)
* Node.js version: v12.13.1
* Npm version: 6.12.1
* Mobile platform/version under test: iOS 13.3 or iOS 13.1
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium CLI
* Xcode version: 11.3

## FYI
- After setting `includeNonModalElements` to `true`, I couldn't get the entire page of source. The following is the result of [Get Page Source](http://appium.io/docs/en/commands/session/source/).
```
<?xml version="1.0" encoding="UTF-8"?><AppiumAUT><XCUIElementTypeApplication type="XCUIElementTypeApplication" name="UIKitCatalog" label="UIKitCatalog" enabled="true" visible="true" x="0" y="0" width="375" height="667"/></AppiumAUT>
```
- I think it might not be possible to find some other elements as well (I haven't tried). 

## Link to Appium logs

[GIST](https://gist.github.com/mwakizaka/7fd32fcd119f21b690fcf382c69efc22)

## Code To Reproduce Issue [ Good To Have ]

- [code](https://gist.github.com/mwakizaka/23283752b0465c4cb2d0bbe69aa4fe0c)
- Please prepare [UIKitCatalog app](https://github.com/appium/ios-uicatalog)

**Comment by mykola-mokhnach** [comment]
Only XCTest itself defines what could be found and what not. The `includeNonModalElements` is just a workaround from our perspective. That is why it is made to a setting, so one can disable and enable it whenever needed. Also, it looks like Apple has deprecated it since Xcode SDK 13.3

**Comment by mwakizaka** [comment]
I see. I understand `includeNonModalElements` is not a long-term one. Maybe I should remove `includeNonModalElements` . But let me ask a question. 

I saw the compared result and I'm curious why Appium 1.15.0 and Xcode 11.3 still works fine.
I have read [here](https://github.com/appium/appium/pull/13837) and I assume
1. The appium setting `includeNonModalElements` is made for Xcode 11.0 to 11.2.
2. In Xcode 11.3, an API (`self.query.includingNonModalElements.rootElementSnapshot`?) which Appium uses inside is deprecated. 

So I think it should not succeed finding the element when Appium 1.15.0 and Xcode 11.3 as well.
Why does it succeed?

**Comment by KazuCocoa** [comment]
Simply, appium 1.15.0 returned non-includeNonModalElements value when it returned `nil` as a fallback. (But the fallback was perhaps not a good idea since users cannot notice `includingNonModalElements` did not work.)
