### ISSUE TITLE
Appium wait slow on specific devices

### ISSUE THREAD

**Issue by pokeahontas** [appium/appium#13854]
## The problem

I have a question regarding performance on different devices. I developed my tests on a Samsung S8(Android 9) where tests are running smoothly, but when running them on any other devices like Samsung S10(Android 9) or Huawei P20 Lite (Android 9)there is the weird problem that the first text field takes extremely long to be found(it's like the wait method somehow freezes, the server log output as well). Once the the field is found entering text is fast. 

What could be the reasons for this? I'm aware that this is a question, but unfortunately I could not find anything useful on this issue.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Desktop OS/version used to run Appium: MacOS

## I use this method to wait for elements

`public boolean waitForElement(MobileElement element) {
        try {
            wait.until(ExpectedConditions.visibilityOf(element));
            return true;
        } catch (Exception ex) {
            throw new RuntimeException(ex);
        }
    }`
## Logcat during test run

https://gist.github.com/pokeahontas/41d885d382522f4869d93d94a533709b

**Comment by mykola-mokhnach** [comment]
It might be the application under test is not in idle state, so uia framework has to wait unit all app animations are finished. Try to get the logcat output for that period - maybe it has some useful info

**Comment by pokeahontas** [comment]
@mykola-mokhnach I added logcat gist above

**Comment by mykola-mokhnach** [comment]
At which time the wait starts and when it ends in the attached log? Please provide the line numbers

**Comment by pokeahontas** [comment]
@amedvedjev thx! unfortunately didn't solve my issue.
@mykola-mokhnach I will provide you with line numbers tomorrow

**Comment by pokeahontas** [comment]
@mykola-mokhnach I updated the gist now. It only contains the logcat output while one of the long waits. 
So basically it waits really long to enter something in the first text field. When it does, it enters quickly in the first and second textfield and then also immediately finds the "next" button.

**Comment by mykola-mokhnach** [comment]
> 01-21 13:22:56.982  6921  6961 W QueryController: Could not detect idle state.

**Comment by pokeahontas** [comment]
Yes I also noticed this. How can I set `waitForIdleTimeout` in java(did not find any documentation on this and `driver.setSetting(Setting.WAIT_FOR_IDLE_TIMEOUT, Duration.ofSeconds(5));` did not work for me)

**Comment by mykola-mokhnach** [comment]
I'd try to ask at https://github.com/appium/java-client or Appium forum.

Closed as not an issue

**Comment by pokeahontas** [comment]
Thanks for your help!

I was able to fix this now with 
```
HasSettings settingsDriver = ((HasSettings) driver);
            settingsDriver.setSetting(Setting.WAIT_FOR_IDLE_TIMEOUT, Duration.of(2, ChronoUnit.SECONDS).toMillis());
```
btw
