### ISSUE TITLE
Original error: *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]

### ISSUE THREAD

**Issue by abhisqa** [appium/appium#13861]
## The problem

Unable to drag and drop an element using specific start and end point coordinates.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: Mac 10.14.6
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: iOS 
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/abhisqa/b92c40d41e2c36fe32214bbabeb3d984

## Code To Reproduce Issue [ Good To Have ]

Dimension windowSize = idriver.manage().window().getSize();
    int startX = 200;
    int startY = 250;
    int endX = 200;
    int endY = 400; 
    touchAction.press(PointOption.point(startX, startY)).waitAction(WaitOptions.waitOptions(Duration.ofMillis(3000))).perform().moveTo(PointOption.point(endX, endY)).waitAction(WaitOptions.waitOptions(Duration.ofMillis(3000))).release().perform();

**Comment by mykola-mokhnach** [comment]
Please use the most recent Appium version

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by abhisqa** [comment]
@mykola-mokhnach this issue is resolved.
