### ISSUE TITLE
Appium: Error when trying to install app on IOS device

### ISSUE THREAD

**Issue by lior052** [appium/appium#13862]
## The problem

App isn't install on IOS device and there is an error in appium log.

## Environment

XCode: 11.3
* Appium version (or git revision) that exhibits the issue: 1.15.0
* Desktop OS/version used to run Appium: MAC 
* Node.js version (unless using Appium.app|exe): 10.18.0
* Mobile platform/version under test: IOS 12.4.4
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details
[debug] [XCUITest] Pushed the app files successfully after 15238ms
[XCUITest] Error was thrown during the installation process
[XCUITest] Error: Unexpected data: {"Error":"ApplicationVerificationFailed","ErrorDetail":-1,"ErrorDescription":"Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.EhzCkP/extracted/ClickMobile.app : 0xe8008015 (A valid provisioning profile for this executable was not found.)"}
[XCUITest]     at InstallationProxyService._isFinished (/usr/local/lib/node_modules/appium/node_modules/appium-ios-device/lib/installation-proxy/index.js:132:13)
[XCUITest]     at InstallationProxyService._isFinished [as _waitMessageCompletion] (/usr/local/lib/node_modules/appium/node_modules/appium-ios-device/lib/installation-proxy/index.js:124:16)
[XCUITest] Error: Could not install app: 'Unexpected data: {"Error":"ApplicationVerificationFailed","ErrorDetail":-1,"ErrorDescription":"Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.EhzCkP/extracted/ClickMobile.app : 0xe8008015 (A valid provisioning profile for this executable was not found.)"}'
[XCUITest]     at IOSDeploy.install (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/ios-deploy.js:41:13)
[DevCon Factory] Releasing connections for d79ae1e8deb1bd977fbe807523a2cb9250948278 device on any port number
[DevCon Factory] No cached connections have been found
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1579683892426 (11:04:52 GMT+0200 (Israel Standard Time))
[debug] [W3C] Encountered internal error running command: Error: Could not install app: 'Unexpected data: {"Error":"ApplicationVerificationFailed","ErrorDetail":-1,"ErrorDescription":"Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.EhzCkP/extracted/ClickMobile.app : 0xe8008015 (A valid provisioning profile for this executable was not found.)"}'
[debug] [W3C]     at IOSDeploy.install (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/ios-deploy.js:41:13)
[HTTP] <-- POST /wd/hub/session 500 18680 ms - 1205
[HTTP]

**Comment by mykola-mokhnach** [comment]
Try to upgrade the server to the most recent version (1.16.0)
Also make sure the app is properly signed with a development profile and the device you are trying to install it to has been added to this profile

**Comment by lior052** [comment]
Thanks for your answer.
I'm using the same app and the same ipad device but just new mac.
I set everything but got this error.
I upgrade the appium but the same error.
Anything else?

**Comment by mykola-mokhnach** [comment]
> I upgrade the appium but the same error.

Please provide the new log

> I set everything but got this error.

Are you able to install the app manually using `ios-deploy` command line utility?

**Comment by lior052** [comment]
I get the same error with IOS-deploy:
2020-01-22 12:07:34.460 ios-deploy[67026:505471] [ !! ] Error 0xe8008015: A valid provisioning profile for this executable was not found. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)

**Comment by mykola-mokhnach** [comment]
This means the binary itself must be fixed. Check it with your developers. Nothing we could do from Appium side.

Closed as not an issue

**Comment by lior052** [comment]
But it worked on previous computer

**Comment by mykola-mokhnach** [comment]
I would also check the system keychain. As far as I remember the dev key should also be present there

**Comment by lior052** [comment]
I thought I upgrade to appium 1.16 but from some reason it didn't update.
I ran: npm install appium -g and it's looks like it upgraded but when checking the version by appium -v it's says again version 1.15
There is another option to upgrade or do you know why it's happened?
