### ISSUE TITLE
Failed to get matching snapshot: No matches found for Identity Binding from input

### ISSUE THREAD

**Issue by venkatraman91g** [appium/appium#13865]
## The problem
We are seeing the above message in IOSDeviceLog followed by the list of elements matching with the identifier passed in by Appium. I'm still not sure why WebdriverAgentRunner shows this message
Wherever this message is thrown, appium fails to get element text of the object although element is found

## Environment

* Appium version: 1.15.0
* Last Appium version that did not exhibit the issue (if applicable): 1.15.0
* Desktop OS/version used to run Appium: MacOS/10.14.6
* Mobile platform/version under test: iOS/13.1
* Real device or emulator/simulator: Real

Logs:
[IOSDeviceLog] Jan 22 18:43:58 iPad-Air-2 WebDriverAgentRunner-Runner(WebDriverAgentLib)[2667] <Notice>: Enqueue Failure: Failed to get matching snapshot: No matches found for Identity Binding from input {(
[IOSDeviceLog]     StaticText, {{275.0, 245.0}, {30.0, 17.5}}, identifier: 'customIdentifier', label: 'customlabel', value: elementText,
[IOSDeviceLog]     StaticText, {{276.5, 313.0}, {28.5, 17.5}}, identifier: 'customIdentifier', label: 'customlabel', value: elementText,
[IOSDeviceLog]     StaticText, {{269.5, 381.0}, {35.5, 17.5}}, identifier: 'customIdentifier', label: 'customlabel', value: elementText,
[IOSDeviceLog]

**Comment by mykola-mokhnach** [comment]
The error is coming is from Apple's xctest, whose source is closed. This means it is hardly possible to figure out the reason for such message and/or a way to address it. If someone could do it then feel free to pop a PR

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
