### ISSUE TITLE
unable to locate elements after opening the application in windows application automation using winappdriver

### ISSUE THREAD

**Issue by aadinagesh** [appium/appium#13868]
i am automating the windows application using winappdriver.
it is able to launch the application, but unable to perform operations on the opened application

my code:
public class FirstTest {

		 public static void main(String [] args) throws IOException {
		 try {
		 DesiredCapabilities capabilities = new DesiredCapabilities();
		 capabilities.setCapability("platformName", "Windows");
		 capabilities.setCapability("deviceName", "ELIDTS21");
       		 capabilities.setCapability("app", "C:\\Program Files\\HunterLab\\EasyMatchQC\\EasyMatchQC.exe");
	
		 
        WindowsDriver driver = new WindowsDriver(new URL("http://127.0.0.1:4723/"), capabilities);
        driver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);
             System.out.println("opened application");
        //click on New job using Runtime ID
        driver.findElementById("[2A.30EF4.3.80000001.30EF4.FFFFFFFC.1]").click();
       // QCSession.close();
       // System.out.println("close application");
        
      // QCSession.quit();
       // System.out.println("quit application");
      //  Thread.sleep(5000);
 
	 }
		 catch(Exception e) {
			 e.printStackTrace();
		 }
	 }
}

output/error:

Jan 23, 2020 3:02:51 PM io.appium.java_client.remote.AppiumCommandExecutor$1 lambda$0
INFO: Detected dialect: OSS
opened application
org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'ELIDTS21', ip: '10.33.50.130', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_151'
Driver info: io.appium.java_client.windows.WindowsDriver
Capabilities {app: C:\Program Files\HunterLab\..., javascriptEnabled: true, platform: WINDOWS, platformName: Windows}
Session ID: A287DAC2-FFC7-472A-9E05-9ED49C654A43

**Comment by mykola-mokhnach** [comment]
Please report Windows-related issues to https://github.com/microsoft/WinAppDriver

This driver is not being under maintenance by Appium team
