### ISSUE TITLE
Safari does not closes tab on close() on iOS devices

### ISSUE THREAD

**Issue by DavidGangel** [appium/appium#13879]
## The problem

1. Navigate to a website.
2. Click on a link which opens a new tab
3. Switch to this new tab and print out some text elements.
5. Close this tab with driver.close()

Expected result:
Tab get's closed.

Actual results:
Nothing happens.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.x-1.16.0
* Last Appium version that did not exhibit the issue (if applicable): 1.12.0
* Real device or emulator/simulator: TestObject real device running iOS 13.x.x

**Comment by imurchie** [comment]
Can you provide the Appium server logs, as a link to a [gist](https://gist.github.com)?

**Comment by DavidGangel** [comment]
@mykola-mokhnach can you please reopen?

Here are the requested gists:
iPhone:
https://gist.github.com/DavidGangel/138f6d44ed47468cc806c004b2790f5c

iPad:
https://gist.github.com/DavidGangel/e7671d73280b4f34d154c02aa3d371d7

**Comment by imurchie** [comment]
Can you try locally with the Appium beta? This works with the latest code

**Comment by DavidGangel** [comment]
Hi,

I tried with the latest 1.17.0 release of appium and the issue is still present.

**Comment by imurchie** [comment]
Once again, the logs from running against the latest code would be useful. Especially since the old logs are deleted.

**Comment by hemank5** [comment]
@DavidGangel Were you able to figure out, I have similar issue 
Pages which opens on new tab/window on click and then verifying the contents on the new tab and then switching back to Parent tab for operations or closing the tab isn't working. 
I am using latest 1.17.1 Appium with Protractor.

**Comment by DavidGangel** [comment]
@hemank5 unfortunately, no. We are still affected by this issue.

**Comment by mymtak** [comment]
Similar things are happening.
Since the tab cannot be closed, it has affected subsequent tests.
## Environment
Appium version 1.17.1
real device iOS 13.5.1

**Comment by enriquegh** [comment]
Looks like this happens when the new tab doesn't have the same domain as the old tab.
https://gist.github.com/enriquegh/410591e9423024a4ba4b439fdeffcd1d

Used iOS 14.0 Simulator w/ Appium 1.18.3 but also seen on other iOS versions and Appium 1.19.0

**Comment by dlobban** [comment]
> @DavidGangel Were you able to figure out, I have similar issue
> Pages which opens on new tab/window on click and then verifying the contents on the new tab and then switching back to Parent tab for operations or closing the tab isn't working.
> I am using latest 1.17.1 Appium with Protractor.
> #14341

@hemank5, we are experiencing the same issue as you have explained and it is proving to be a major issue as we set up our testing in Browserstack which uses Appium for testing on mobile devices.
I hope a solution is found soon.

**Comment by jlipps** [comment]
Does a regular javascript `window.close()` work? If not, it's not going to work in Appium either. The workaround would be to do what a user would do to navigate or close a tab (go back into Native mode and find/interact with native UI elements just like a user would)

**Comment by dlobban** [comment]
Thanks for the suggestions @jlipps, we have tried the regular javascript 'window.close()' and it did not work, but we will look into the workaround you have suggested.

**Comment by mykola-mokhnach** [comment]
This looks like a Safari issue. Nothing we could do from Appium side though

**Comment by zcmgyu** [comment]
It's worked on iOS 15
