### ISSUE TITLE
Query:- [iOS Safari Shadow DOM] - Unable to work on element with appium and Javascript.

### ISSUE THREAD

**Issue by ahmadsayeed3** [appium/appium#13874]
## The problem

I am able to find the ShadowDom element using JavaScript but whenever trying to getText using Appium or even with JavaScript, getting StaleElementException. The same script is able to work on Android Phones.

In 1.16 release history, It has Shadow DOM support for iOS Safari. 
I haven't found any documentation how I can use that. 
Suggestions would help to perform automation on Shadow DOM Element.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): none
* Desktop OS/version used to run Appium: Mac
* Node.js version (unless using Appium.app|exe): 10.x
* Npm or Yarn package manager: Npm
* Mobile platform/version under test: iOS 11.3.1, 12.2.0, 12.0.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

**Comment by mykola-mokhnach** [comment]
Does it work for you in appium@beta?

**Comment by ahmadsayeed3** [comment]
Haven't tried yet. I Will try and come back. Is anything additional steps I need to add for newly added support in appium 16

**Comment by ahmadsayeed3** [comment]
Thanks, Mykola for the suggestion. With Appium 1.16 I am able to find and sendkeys. 
I am stuck at clicking a button. The shadow root is so nested. I am figuring out whether it's my script issue or something from Appium. 

Please don't close this issue now. Allow me some time to come back and update.

**Comment by ahmadsayeed3** [comment]
Closing this issue, as able work on Shadow DOM with Appium 1.16.

**Comment by ahmadsayeed3** [comment]
Hi I am able to find the 'Log in' button element and also able to get the text but not clicking.
Appium click does fake pass and JavaScript throws error. 

Opkeys-Mac-mini.local
--> POST /wd/hub/session/bf4f885f-8385-4e90-be48-808406fe7c62/execute/sync
[HTTP] {"script":"arguments[0].setAttribute('style','border:')","args":[{"ELEMENT":"5057","element-6066-11e4-a52e-4f735466cecf":"5057"}]}
[debug] [W3C (bf4f885f)] Calling AppiumDriver.execute() with args: ["arguments[0].setAttribute('style','border:')",[{"ELEMENT":"5057","element-6066-11e4-a52e-4f735466cecf":"5057"}],"bf4f885f-8385-4e90-be48-808406fe7c62"]
[debug] [XCUITest] Executing command 'execute'
[debug] [RemoteDebugger] Executing atom 'execute_script'
[debug] [RemoteDebugger] Executing 'execute_script' atom in default context
[debug] [RemoteDebugger] Sending javascript command: '(function(){return function(){var e=this;
[debug] [RemoteDebugger] funct...'
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:433', page '1', target 'page-6' (id: 365)
[debug] [RemoteDebugger] Received data response from send (id: 365): '{"status":10,"value":{"message":"Element does not exist in cache"}}'
[debug] [RemoteDebugger] Sending to Web Inspector took 112ms
[debug] [MJSONWP] Matched JSONWP error code 10 to StaleElementReferenceError
[debug] [W3C (bf4f885f)] Encountered internal error running command: StaleElementReferenceError: Element does not exist in cache
[debug] [W3C (bf4f885f)]     at errorFromMJSONWPStatusCode (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:764:12)
[debug] [W3C (bf4f885f)]     at convertResult (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-remote-debugger/lib/helpers.js:244:11)
[debug] [W3C (bf4f885f)]     at RemoteDebuggerRealDevice.execute (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-remote-debugger/lib/remote-debugger.js:713:12)

To reproduced the issue 
This is the URL **https://www.pfizerpro.com/** after launch please click on **Sign In**.
**<span class="grv-button__label">Log in</span>** This element I m trying to click.

Please Suggestions would help.

**Comment by ahmadsayeed3** [comment]
Hi.

I also tried to tap by element location x,y but didn't work.
