### ISSUE TITLE
Received New Command Timeout expired error before the specified time and then follow up with ECONNREFUSED

### ISSUE THREAD

**Issue by oldstone** [appium/appium#13873]
## The problem

I noticed in the logs that frequently I will receive a New Command Timeout error (e.g. 'New Command Timeout of 600 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability') and then follow up with an ECONNREFUSED error (e.g. [debug] [35m[W3C (2edbc58b)][39m Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:30520)

The issue is, I can see from the timestamps in the logs that the command definitely didn't take more than the 600 seconds I specified in the desired capabilities.
For example, in my linked gist, the time between the POST request and this error was only around 2 seconds (line 560 - line 562).

I have tried changing the newCommandTimeout value but it makes no difference.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: CentOS 7
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: Android 8
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Link to Appium logs
https://gist.github.com/oldstone/de16d03d05f1fc5dce8da81406520baa

**Comment by mykola-mokhnach** [comment]
It looks like this message is coming from the other parallel session, which has not been closed properly before. The id of the currently running session is `8cab0362-f61c-4dfd-9453-7cbf9dd77546`, although the DELETE command has been sent to the session with identified by `21daefae-028a-45aa-9bdf-e1d9bca32f3e`.

Simply make sure you always quit your sessions.

**Comment by oldstone** [comment]
Ah, I missed that it's a different session. I still need help though.
So I originally thought the timeout error was the cause of the `ECONNREFUSED` error happened at line 585 (it's for the current session `8cab0362-f61c-4dfd-9453-7cbf9dd77546`), but now it seems they're not related. Or can the `ECONNREFUSED` caused by a different lingering session?

**Comment by mykola-mokhnach** [comment]
This is expected. The previous session was running on the same device and was not closed properly. Now when a new session is running, the old one receives the DELETE command because of the unexpected shutdown. This terminates the connection to the device under test for the PREVIOUS session, but since the old session used the SAME device, this means that the current session loses connection to it as well.

**Comment by mykola-mokhnach** [comment]
Btw, Appium server has a possibility to run in `single-session` mode by providing the `--session-override` command line arg. This will automatically enforce all active sessions to be deleted before starting a new one.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by BoazWarshawsky** [comment]
@mykola-mokhnach, regarding above,
Do you advice doing on every end of test `driver.quit()` or connect to appium server once and just `activate()` & `terminate()` on every start and end of the test?
