### ISSUE TITLE
[perfomance][appium-xcuitest-driver][webview]Cannot find elements inside webview with JS on iOS13

### ISSUE THREAD

**Issue by margasan** [appium/appium#13870]
## The problem
Cannot find elements inside webview with JS on iOS13

## Environment
* appium-xcuitest-driver 3.12.1
* appium 1.16.0
* node v13.6.0
* npm 6.13.6

* iOS 13.3
* Xcode 11.3 (11C29)
* OS macOS Catalina 10.15.2 (19C57)

##Caps
automationName: XCUITest, browserName: , databaseEnabled: false, deviceName: iPhone, enablePerformanceLogging: true, eventTimings: true, fullReset: false, iosInstallPause: 20, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: false, newCommandTimeout: 500, noReset: true, platform: MAC, platformName: iOS, platformVersion: 13.3, screenshotWaitTimeout: 10, shouldUseSingletonTestManager: false, showSafariConsoleLog: true, showXcodeLog: true, simpleIsVisibleCheck: false, snapshotTimeout: 100, takesScreenshot: true, udid: 07c4107d44aebea8c8d78f1736b..., useJSONSource: true, useNewWDA: false, usePrebuiltWDA: true, waitForQuiescence: false, wdaLaunchTimeout: 60000, wdaLocalPort: 8101, webStorageEnabled: false

## Details
This problem appears on web view page with content that uses JS. It doesn't appear on iOS12/Xcode10. In my opinion, this is perf issue on appium-xcuitest-driver, because a native test successfully finds necessary elements.

## Link to Appium logs
Appium logs:
https://gist.github.com/margasan/dcf1bbe8fd7f3406d69053094a70b3f9
page source using .executeScript("mobile: source", ImmutableMap.of("format", "description"))
https://gist.github.com/margasan/f8ad573049ced531b914186cb86b8e9d

## Code To Reproduce Issue
1. Install WebView application from the AppStore
2. Unpack the archive attached and make these files available through any local webserver (Nginx, apache etc.)
2. Via WebView application open file terms_conditions.html
3. Try to find buttons "Accept" or "Cancel" on the page:
`.findElementByIosNsPredicate("name IN {'ACCEPT', 'Accept', 'AKZEPTIEREN', 'Akzeptieren', 'ACCEPTER', 'ACCEPTTA', 'Jetzt registrieren'} AND type =='XCUIElementTypeLink' AND visible == true").isDisplayed()`
[terms.zip](https://github.com/appium/appium/files/4108049/terms.zip)

#Notes 
These elements (Accept and Decline) 100% are found using native XCUITest test like this:
`func testID(){
        let settingsApp = XCUIApplication(bundleIdentifier: "")
        settingsApp.launch()
        let tablesQuery = settingsApp.webViews
        let start = CFAbsoluteTimeGetCurrent()
        XCTAssertTrue(tablesQuery.staticTexts["Accept"].isEnabled)
        let diff = CFAbsoluteTimeGetCurrent() - start
        print("Finding element took \(diff)seconds")
    }`
It takes ~11seconds to find these elements.
#Screenshots 
<img width="1027" alt="Screen Shot 2020-01-24 at 1 52 44 PM" src="https://user-images.githubusercontent.com/18184847/73066373-d4009780-3eb6-11ea-81df-03486b19271d.png">

**Comment by mykola-mokhnach** [comment]
Please check if it works better with appium@beta (which contains the https://github.com/appium/WebDriverAgent/pull/273 workaround)

**Comment by amedvedjev** [comment]
welcome to the party of iOS 13.3 slowness.

@mykola-mokhnach as far as request in NATIVE view i think this does not work. But when switch to WebView -> then speed will be fast.

**Comment by mykola-mokhnach** [comment]
If the web view is based on UIWebView (which is considered deprecated) then no wonder it is slow.

**Comment by margasan** [comment]
> If the web view is based on UIWebView (which is considered deprecated) then no wonder it is slow.
We are using WKWebview, so that's not a reason.

**Comment by mykola-mokhnach** [comment]
Does the stuff work better with appium@beta?

**Comment by margasan** [comment]
> Does the stuff work better with appium@beta?

Will check soon.

**Comment by margasan** [comment]
No luck with 1.16.0-beta.3. The native test successfully finds the elements but no success with appium.

**Comment by mykola-mokhnach** [comment]
What if you try to find the element without checking the `visible` attribute? This one is very expensive

**Comment by margasan** [comment]
> What if you try to find the element without checking the `visible` attribute? This one is very expensive

It doesn't make sense because we cannot obtain the right (with all elements) page source using appium. If you would like to debug the problem page I can share it via public web - you only need to install WebView application from the AppStore and paste url I'll provide.

**Comment by Aubbles01** [comment]
I am experiencing a similar, although slightly different issue.  I am using Appium Desktop 1.15.1 and have also tried the current Appium beta and I see the same behavior in both.  With iOS 13.3, Appium is not able to find elements on the page, exactly as described in the original poster's info. 

However, with iOS 13.2, Appium appears to be able to find the elements but cannot correctly interact with them.  Appium logs report that it performs the click action on the found element, but the application under test does not actually seem to receive the command as the tap does not happen, even though no errors are thrown in Appium.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by Aubbles01** [comment]
Do you guys have any suggestions for a workaround here besides changing the type of webview that is being used?  Our application uses Auth0 for authentication so we have no control over what types of controls they use in their libraries.  If you have any suggestions on how to make appium work with JS pages in iOS 13, it would be greatly appreciated.

**Comment by mykola-mokhnach** [comment]
>  Our application uses Auth0 for authentication so we have no control over what types of controls they use in their libraries

Why not to ask the developers of that instrument on how do they recommend to run the automated end to end testing? Perhaps it just needs to be justified properly instead of trying to find workarounds? Especially if it is not free...

**Comment by imurchie** [comment]
I'm confused. Is this happening in the Native context? Or upon switching to the webview?

**Comment by mykola-mokhnach** [comment]
@imurchie The original issue is about the native context

**Comment by imurchie** [comment]
Folks should try switching to the webview, then. The fact that it sometimes works through the native context is fortuitous at best.

**Comment by jineshqa** [comment]
@imurchie @mykola-mokhnach My app is like wrapper around web view so it only shows native_app context. Also I tried following steps [here](https://github.com/appium/WebDriverAgent/pull/273#issuecomment-573360683) but it does not show any snapshot parameter.

**Comment by imurchie** [comment]
Is the content inside a webview? It should be accessible as a webview context, then, and that is the proper place to interact with it.

**Comment by jineshqa** [comment]
It has something to do with old type of WebViews, dev on time had to make changes to WebView and it all started working. Thanks for taking out time and looking into this.
