### ISSUE TITLE
[W3C] Matched W3C error code 'unknown command' to UnknownCommandError for click action

### ISSUE THREAD

**Issue by shibupanda** [appium/appium#13878]
## The problem
Getting "[W3C] Matched W3C error code 'unknown command' to UnknownCommandError" for
"POST /wd/hub/session/9aa2ed34-fc11-4a68-927e-03af072dc98c/click
{"button":0}" request. Please find the attached logs.

## Environment

* Appium version (or git revision) that exhibits the issue: tried with both 1.15.1 and 1.16.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac
* Node.js version (unless using Appium.app|exe): 10.*
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS 12.*
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

We have two setup having same appium version 1.15.1. In one moveToElement and click perform work fine but same is not working in another setup. There is one difference I found i.e. 
Working one: W3C (b5e1ac9b)] Cached the protocol value 'W3C' for the new session b5e1ac9b-8e15-4c4f-a6e5-ccd831926740
Not Working one: [MJSONWP (9aa2ed34)] Cached the protocol value 'MJSONWP' for the new session 9aa2ed34-fc11-4a68-927e-03af072dc98c 

Endpoints are also different with the same code:
Not Working one: 
==============
1st request --> POST /wd/hub/session/9aa2ed34-fc11-4a68-927e-03af072dc98c/moveto 200
2nd request --> POST /wd/hub/session/9aa2ed34-fc11-4a68-927e-03af072dc98c/click 500 with 
[W3C] Matched W3C error code 'unknown command' to UnknownCommandError error.

Working One:
===========
Only one request to perform complete action:
POST /wd/hub/session/b5e1ac9b-8e15-4c4f-a6e5-ccd831926740/actions 200

## Link to Appium logs
https://gist.github.com/shibupanda/856729ef5dede5ede709f7f69829e1c6
https://gist.github.com/shibupanda/5b57271cb991f4ce55284310e25fa173

## Code To Reproduce Issue [ Good To Have ]

int width=  tripType.first().getSize().getWidth();
Actions act = new Actions(driver);
act.moveToElement(tripType.first()).moveByOffset(width/2, 0).click().perform();

**Comment by mykola-mokhnach** [comment]
The error is expected, because such endpoint is not implemented. 

What are you trying to achieve with the code above?

**Comment by shibupanda** [comment]
@mykola-mokhnach 
We are trying to move to element and try to click on one element using offset.
But the query is why the same code is running on one setup?

please suggest anything needs to done.

**Comment by mykola-mokhnach** [comment]
Try to replace click with press-release

**Comment by mykola-mokhnach** [comment]
Closed because of no response
