### ISSUE TITLE
Unable to scroll to an element 

### ISSUE THREAD

**Issue by Amrkamel1** [appium/appium#13881]
## The problem

im running test against hybrid app in android device, im trying to scroll to an element and all tries has failed however i was always using scrolling feature with no any problem in many different apps before

when i use uiautomator to scroll to an element by text appium see the element without scrolling to it also it will click on the element but no real action will be done

if i change the element to some element that doesn't exist appium keep scrolling up and down searching for it.

## Environment

* Appium version1.15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:c1.15.1
* Node.js version (unless using Appium.app|exe): 12
* Npm or Yarn package manager: N/A
* Mobile platform/version under test: android 10
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: app.exe

## Details

here are some sample of the methods i used

`
    @AndroidFindBy(uiAutomator = "new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().text(\"SAFGFDGVE\"))")
    MobileElement saveButton;

    @AndroidFindBy(uiAutomator = "new UiScrollable(new UiSelector()).scrollIntoView("
            + "new UiSelector().className(\"android.widget.Button\").index(3))")
    MobileElement saveButton;

    @AndroidFindBy(uiAutomator = "new UiScrollable(new UiSelector().className(\"android.view.View\").index(1).instance(2)).scrollIntoView("
            + "new UiSelector().className(\"android.widget.Button\").index(3).instance(0))")
    MobileElement saveButton;
`

## Link to Appium logs
[debug] [W3C (64fa1544)] Responding to client with driver.getCurrentContext() result: "NATIVE_APP"
[HTTP] <-- GET /wd/hub/session/64fa1544-e8f7-4c0b-a9b5-97068306170f/context 200 3 ms - 22
[HTTP]
[HTTP] --> POST /wd/hub/session/64fa1544-e8f7-4c0b-a9b5-97068306170f/element
[HTTP] {"using":"-android uiautomator","value":"new UiScrollable(new UiSelector().className(\"android.view.View\").index(1).instance(2)).scrollIntoView(new UiSelector().className(\"android.widget.Button\").index(2))"}
[debug] [W3C (64fa1544)] Calling AppiumDriver.findElement() with args: ["-android uiautomator","new UiScrollable(new UiSelector().className(\"android.view.View\").index(1).instance(2)).scrollIntoView(new UiSelector().className(\"android.widget.Button\").index(2))","64fa1544-e8f7-4c0b-a9b5-97068306170f"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 5000 ms for condition
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8205/wd/hub/session/6c06b813-e601-4bff-8dbc-9d4ffd2c7853/element] with body: {"strategy":"-android uiautomator","selector":"new UiScrollable(new UiSelector().className(\"android.view.View\").index(1).instance(2)).scrollIntoView(new UiSelector().className(\"android.widget.Button\").index(2))","context":"","multiple":false}
[WD Proxy] Got an unexpected response with status 404: {"sessionId":"6c06b813-e601-4bff-8dbc-9d4ffd2c7853","value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters","stacktrace":"io.appium.uiautomator2.common.exceptions.ElementNotFoundException: An element could not be located on the page using the given search parameters\n\tat io.appium.uiautomator2.handler.FindElement.safeHandle(FindElement.java:78)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:38)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:252)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:242)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:51)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.chann...
[debug] [W3C] Matched W3C error code 'no such element' to NoSuchElementError
[debug] [W3C (64fa1544)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[debug] [W3C (64fa1544)]     at AndroidUiautomator2Driver.findElOrEls (C:\Users\warrior\AppData\Roaming\npm\node_modules\appium\node_modules\appium-android-driver\lib\commands\find.js:75:11)

![image](https://user-images.githubusercontent.com/32042806/73225945-a5ace180-416e-11ea-9d9b-dfd90087a810.png)

![image](https://user-images.githubusercontent.com/32042806/73225973-b9584800-416e-11ea-8a7d-69577ad18c5c.png)

**Comment by mykola-mokhnach** [comment]
I don't think we could help anything there. The locator itself is handled by UiAutomator framework. Appium acts as a proxy there.

As a workaround you could try to swipe down using touch actions

**Comment by amedvedjev** [comment]
i met same. 
1) why it does not scroll? in mine case as far as all elements that downscreen they are present! in page source BUT have very small size (few pixels height). this can be used while do swipe yourself with touch. 
2) problem met using this that with some webViews after scroll UIAutomator does not see correctly elements location. and as result tap happens in wrong place if it needed.

the only solution was for me ->  switch to WebView. all problems gone.

**Comment by mykola-mokhnach** [comment]
Maybe this was the reason for [deprecating](https://developer.android.com/reference/android/support/test/uiautomator/UiSelector) UiSelector. So it's up to you to still use it even though the vendor dropped its support

**Comment by amedvedjev** [comment]
@mykola-mokhnach is it? -> https://developer.android.com/reference/androidx/test/uiautomator/UiSelector

**Comment by mykola-mokhnach** [comment]
True, I thought it was not ported to Androidx. Then it looks like an issue with UiSelector functionality itself

**Comment by amedvedjev** [comment]
in mine case issue was that elements were available thus scroll not happened.
while if i swipe with touch and element appears on screen and it height increasing to correct. i used this (swipe and check element height > some value) until met with problem 2.

**Comment by mykola-mokhnach** [comment]
> problem met using this that with some webViews after scroll UIAutomator does not see correctly elements location. and as result tap happens in wrong place if it needed.

Do you cache that element into WebElement instance? What if you try to locate it again and only read its height after that? Element location requests force UIAutomator to refresh the accessibility tree.

**Comment by amedvedjev** [comment]
i use only appium annotations without cache. e.g.
```
    @iOSXCUITFindBy(id = "SET1ListView")
    @AndroidFindBy(id = "siv_language")
    private MobileElement mainContainer;
```
and each access to element do refresh. is it?

**Comment by mykola-mokhnach** [comment]
nope, the AndroidFindBy proxy only executes lookup lazily when you access the variable for the first time. Next time the cached instance is used and you don't have any control over that process

**Comment by amedvedjev** [comment]
found old screenshot in chat ->
![image (1)](https://user-images.githubusercontent.com/2756856/73252455-707eae80-41c3-11ea-87c7-5bd6753f00bd.png)

**Comment by mykola-mokhnach** [comment]
Try the trick above and let me know if it changed anything

**Comment by amedvedjev** [comment]
did i understand correctly lazily lookup and following should happen with element:
```
    @iOSXCUITFindBy(id = "SET1ListView")
    @AndroidFindBy(id = "siv_language")
    private MobileElement mainContainer;
```
 1) open page with element above and try search for element e.g. with "mainContainer.getId()" = FOUND
 2) now open any other screen with phone client and try again search same "mainContainer.getId()" = FOUND again?

**Comment by mykola-mokhnach** [comment]
not necessarily. This depends on the internal `getId` implementation. If this involves the backend then StaleElementException will be returned (most likely). If no backend calls are needed then everything would work as in p2

**Comment by amedvedjev** [comment]
result i have is: 
`2020-01-28 10:30:12:242 - [debug] [W3C (1b3a211c)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.`
= it did search again

so i cant understand what 'lazily lookup' means :-(.
i can try experiment with get element location -> manually scroll and again el.getLocation().getX(). but i sure for 99.99% it will return correct values with new location.

**Comment by Amrkamel1** [comment]
> i met same.
> 
> 1. why it does not scroll? in mine case as far as all elements that downscreen they are present! in page source BUT have very small size (few pixels height). this can be used while do swipe yourself with touch.
> 2. problem met using this that with some webViews after scroll UIAutomator does not see correctly elements location. and as result tap happens in wrong place if it needed.
> 
> the only solution was for me -> switch to WebView. all problems gone.

could you elaborate more, do u mean you were able to scroll to element in webContext with no problem if yes can you provide samples since i almost tried everything and nothing is working

**Comment by amedvedjev** [comment]
@Amrkamel1 did try switch to webView and click element without scrolling? works for me! the only difference that instead of native now we can use pure web search e.g. by css
```
@FindBy(css = ".calendar-table")
List<MobileElement> calendarTable;
```

**Comment by Amrkamel1** [comment]
> 
> 
> @Amrkamel1 did try switch to webView and click element without scrolling? works for me! the only difference that instead of native now we can use pure web search e.g. by css
> 
> ```
> @FindBy(css = ".calendar-table")
> List<MobileElement> calendarTable;
> ```

issue has been resolved as u mentioned in webContext i have used FindBy Xpath, but no way to scroll in native_app context.
it seems uiAutomator sees all element in dom by default no matter if you see it or not but when it click it will not be interceptable thats why when using uiAutomator to scrolll to element that doesnt exist , it will keep scrolling up and down searching for it which mean it sees all element thats why its not scrolling

**Comment by mykola-mokhnach** [comment]
I don't think there's anything more we could do from Appium side.

Closed as third party issue.
