### ISSUE TITLE
Default capabilities always overriden by desired capabilities

### ISSUE THREAD

**Issue by VitorJeremias** [appium/appium#13885]
## Description

I'm using command line to start appium server and using the --default-capabilities flag. Apparently it starts correctly:
`appium --session-override --default-capabilities '{ "device-name":"SCx 98 Huawei", "udid":"KBT7N19213000312", "platform-name":"Android", "platform-version":"9", "app-pkg":"com.my.app", "app-activity":"com.my.app.activity" }'`

When starting a new AppiumDriver<MobileElement> I cannot do it without passing DesiredCapabilities as a parameter, which override the default capabilities.

## Environment
* Java client build version or git revision if you use some snapshot:
```
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
```
* Appium server version or git revision if you use some snapshot:
1.16.0

* Desktop OS/version used to run Appium if necessary:
macOS Mojave Version 10.14.6 (18G2022)

* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
v13.5.0

* Mobile platform/version under test:
Android 9

* Real device or emulator/simulator:
Real device

## Code To Reproduce Issue

`
public void setup(String deviceName, String udid, String platformName, String platformVersion, String appPackage, String appActivity, String unlockType, String unlockKey)
			throws MalformedURLException {

		DesiredCapabilities cap = new DesiredCapabilities();
		cap.setCapability("deviceName", deviceName); 
		cap.setCapability("udid", udid); 
		cap.setCapability("platformName", platformName);
		cap.setCapability("platformVersion", platformVersion);
		cap.setCapability("appPackage", appPackage);
		cap.setCapability("appActivity", appActivity);
		cap.setCapability("unlockType", unlockType);
		cap.setCapability("unlockKey", unlockKey);
		cap.setCapability("skipDeviceInitialization", true);
		cap.setCapability("skipServerInstallation", true);
		URL url = new URL("http://127.0.0.1:4723/wd/hub");
		driver = new AppiumDriver<MobileElement>(url, cap); //instantiating the AppiumDriver asks for the DesiredCapabilities, which will override the ones passed via command line
	}
`

**Comment by mykola-mokhnach** [comment]
> When starting a new AppiumDriver I cannot do it without passing DesiredCapabilities as a parameter, which override the default capabilities.

Is it mandatory to include all the capabilities? I think the client side code only checks the presence of the platform one

**Comment by VitorJeremias** [comment]
I managed to do it by passing an empty DesiredCapabilities instance along with the URL. I don't know if there's a better way to do that, but that solved the case. 
The setup method ended up like this:

    public void setup(String deviceName, String udid, String platformName, String platformVersion, String appPackage, String appActivity, String unlockType, String unlockKey)
			throws MalformedURLException {

		DesiredCapabilities cap = new DesiredCapabilities();

		URL url = new URL("http://127.0.0.1:4723/wd/hub");

		driver = new AppiumDriver<MobileElement>(url, cap);
	}

It would be a cool enhancement to be able to instantiate the AppiumDriver without the capabilities, because passing an empty parameter doesn't seem to do a lot. Issue resolved nonetheless, thanks for your time!
