### ISSUE TITLE
Setting the text using a UiSelector that uses text fails with UiObjectNotFoundException

### ISSUE THREAD

**Issue by bogdancucosel** [appium/appium#13886]
## The problem

In UiAutomator2, we create a UiSelector for a text element like this:
UiSelector[TEXT=aaaa, CLASS=android.widget.EditText, INSTANCE=0]

If we set the text of this element, we will get an exception:
Encountered internal error running command: io.appium.uiautomator2.common.exceptions.ElementNotFoundException: androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[TEXT=aaaa, CLASS=android.widget.EditText, INSTANCE=0]

This is probably due to the fact that the element is not directly cleared, but instead there is a command invoked in :
https://github.com/appium/appium-uiautomator2-server/blob/ba3c81b9c888dc6bdf3b5720f47be2879c0b2edb/app/src/main/java/io/appium/uiautomator2/handler/SendKeysToElement.java#L80

new Clear("/wd/hub/session/:sessionId/element/:id/clear").handle(request);

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0
* Last Appium version that did not exhibit the issue (if applicable): I 
* Desktop OS/version used to run Appium: Windows 10
* Real device or emulator/simulator: anything

**Comment by mykola-mokhnach** [comment]
Good catch, thanks. You're welcome to push a PR next time .

**Comment by bogdancucosel** [comment]
Will do, thank you very much

**Comment by mykola-mokhnach** [comment]
The fix has been published to appium@beta

**Comment by bogdancucosel** [comment]
Unfortunately I was assuming stuff.
The fix did not solve the problem.
After clear, when we do getText, the node would still have the old selector (I was assuming there was a cache somewhere, but actually it seems that whenever we do somthing with the element, the selector is used to retrieve it).

So , it seems that the reason "clear" is needed is because we cannot know if getText returns an actual text or it returns a hint and the actual value is empty.

I am now looking into a fix.
I was thinking that if I would select the entire text (you know , with ACTION_ARGUMENT_SELECTION_START_INT and ACTION_ARGUMENT_SELECTION_END_INT) , and I would find a way to retrieve the actual selected text, then we would not need the clear method.

Again, I am assuming that, if I find a way to retrieve the selected text , then that would not contain the hint if the EditText is empty.

What do you think ?

**Comment by mykola-mokhnach** [comment]
The next is not necessary selected when one starts typing. How about changing the locator itself? Or avoid replacement (I'm talking about the `replace` flag that the endpoint supports)

**Comment by bogdancucosel** [comment]
Yes I agree with you, we should almost never use the text in a locator.
However, we have some scenarios where we should allow this. Most specific is when you have a form with several edit fields, and, when pristine, the edit boxes would be differentiated by their hint. 

I think the solution you propsed is good for most cases.
The case where replace is true works out of the box.
The case where replace is false, would still not work, but, there are simple workarounds; like getting the text before calling the set text.

Looking through the code, it seems that what I wanted to do is a somewhat complicated. What I wanted to do was to , instead of clearing the field , try to select all characters in the text field and , afterwards retrieve the selected text, if possible. Then I would know if the edit field would actually contain some characters, and use that string for the case when we needed to append the text; if this would work there would not be a need for clear, even in the case where replace is false.

The AndroidElement interface does not contain things that would make that possible. I guess a proper place for this would be the ElementHelpers class. But even there we would need to have code that gets to the AccessibilityNodeInfo of the UiObject or UiObject2 .

Anyway , I think the solution you proposed is very good for now.
Thank you
