### ISSUE TITLE
Android: Page source is returning only partial hierarchy.

### ISSUE THREAD

**Issue by Devapal** [appium/appium#13882]
**OS**: ANDROID

**Desktop OS/version used to run Appium**: Mac OS 10.14.6
**Node.js version** : v13.6.0
**Npm version**: 6.13.4
**Mobile platform/version under test**: Android 9 & 10
**Real device or emulator/simulator**: Real Device
**Appium CLI or Appium.app|exe**: Both

**Desired Capabilities:**
{
  "deviceName": "S9 Plus",
  "udid": "3544384d4a573398",
  "app": "/Users/devannapureddy/Desktop/ArclightUAT.apk",
  "platformName": "Android",
  "automationName": "UiAutomator2"
}

**Issue**: The page source is not returning the elements on the page. It is only returning a partial hierarchy. I have also attached the screenshot when I spy using Appium inspector. I have tried waiting, sending app to the background and brining it back but nothing works.

Please note that I have automated this app a year ago and it used to render the elements correctly but all of a sudden for the past month I am seeing this partially rendering issues. Not sure what's happening here.

**App**: It is a hybrid app developed with Cordova. If I switch to WebView, the elements are loaded perfectly but the test cloud we are using to run Appium tests does not support WebView. **I am confused as to why after a year of correctly working am I seeing these partial rendering issues with Native view now ?**. Any insight into this would help.

**Appium Version**: 1.15 ( I also tried with 1.16 beta version )

**Temporary Work around I found**: If I factory reset the device, I am seeing the elements are loading correctly in Native view. When I run my tests on test cloud, factory reset is not an option.

<img width="1411" alt="Screen Shot 2020-01-27 at 8 49 32 PM" src="https://user-images.githubusercontent.com/35826618/73231726-b6e1f800-4146-11ea-8c56-bab6b59c82ef.png">

**Below is the page source which returns partial heirarchy**.
<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
<hierarchy index="0" class="hierarchy" rotation="0" width="1080" height="2076">
  <android.widget.FrameLayout index="0" package="com.arclightuat.mobile" class="android.widget.FrameLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,0][1080,2076]" displayed="true">
    <android.widget.LinearLayout index="0" package="com.arclightuat.mobile" class="android.widget.LinearLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,0][1080,2076]" displayed="true">
      <android.widget.FrameLayout index="0" package="com.arclightuat.mobile" class="android.widget.FrameLayout" text="" resource-id="android:id/content" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,72][1080,2076]" displayed="true">
        <android.webkit.WebView index="0" package="com.arclightuat.mobile" class="android.webkit.WebView" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,72][1080,2076]" displayed="true">
          <android.webkit.WebView index="0" package="com.arclightuat.mobile" class="android.webkit.WebView" text="Arclight UAT" checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="true" long-clickable="false" password="false" scrollable="true" selected="false" bounds="[0,72][1080,2076]" displayed="true" />
        </android.webkit.WebView>
      </android.widget.FrameLayout>
    </android.widget.LinearLayout>
  </android.widget.FrameLayout>
</hierarchy>

**Comment by mykola-mokhnach** [comment]
Appium simply shown what UIAutomator returns to it and UIAutomator retrieves the tree from the system accessibility inspector.

Maybe, enabling the `enableMultiWindows` setting (only available in the recent server release) could show more elements. But otherwise there is more nothing we could do on the server side.

**Comment by Devapal** [comment]
@mykola-mokhnach enableMultiWindows = true enables windows objects (like home button, side arrow etc) but not the objects on the app.  
Now here is the thing that makes me think, it may not be UIAutomator,  When I do a factory reset on the device, all the objects are made visible.  If it is a UIAutomator issue, it should not work with or without factory reset right ?

Is there a UIAutomator Cache or some Appium Cache that needs to be cleared to make the objects detectable ? I tried Getpagesource, Click, Swipe to refresh the DOM but it does not cut it.

**Comment by mykola-mokhnach** [comment]
> Is there a UIAutomator Cache or some Appium Cache that needs to be cleared to make the objects detectable?

Nothing I know about

**Comment by Devapal** [comment]
@mykola-mokhnach Is there an active UIAutomator forum you know of to discuss this issue ?

**Comment by mykola-mokhnach** [comment]
I would try Google groups

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
