### ISSUE TITLE
ios_webkit_debug_proxy timing out and hence no web view

### ISSUE THREAD

**Issue by sasasa42** [appium/appium#13884]
## The problem

Having problems while trying to open a web  in Safari.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.0
* Last Appium version that did not exhibit the issue (if applicable):1.14.0
* Desktop OS/version used to run Appium: High Sierra
* Node.js version (unless using Appium.app|exe): 8.11.3
* Npm or Yarn package manager: 6.1.0
* Mobile platform/version under test: iOS 11.2.6
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium

## Details

When trying to open the application(web view), it fails. PFA the logs

## Link to Appium logs

https://gist.github.com/sasasa42/84c53faf41b4e4386aed87b269235522

**Comment by imurchie** [comment]
Can you set the `showIWDPLog` capability to `true`, to get some visibility into what `ios-webkit-debug-proxy` is up to?

**Comment by mykola-mokhnach** [comment]
Please use the most recent Appium server version

**Comment by sasasa42** [comment]
@mykola-mokhnach . I have tried with 1.15.1. It works fine. But still, let's keep this under monitoring for some time. Thanks

**Comment by mykola-mokhnach** [comment]
The webkit debug proxy is a third party tool, which we don't have any control on. Also, because of insufficient resources, the team does not provide any patches to older Appium releases. That is why it is always the best to use the latest and the greatest version of the product.

**Comment by imurchie** [comment]
Recent versions also do not have any dependency on `ios-webkit-debug-proxy`.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
