### ISSUE TITLE
Appium 1.16.0 installs wrong version of appium-webdriveragent

### ISSUE THREAD

**Issue by RonKalian** [appium/appium#13880]
## The problem

When installing Appium 1.16.0, the version of appium-webdriveragent was not the latest - tests were failing on `Did not get any response after 300 seconds`

## Environment

* Appium version (or git revision) that exhibits the issue:  1.16.0
* Last Appium version that did not exhibit the issue (if applicable):  Didn't test with earlier versions
* Desktop OS/version used to run Appium:  MacOS Catalina 10.15.2
* Node.js version (unless using Appium.app|exe):  13.7.0
* Npm or Yarn package manager:  NPM 6.13.6
* Mobile platform/version under test:  iOS/iPadOS 13.3
* Real device or emulator/simulator:  Real device
* Appium CLI or Appium.app|exe:
* Xcode:   11.3.1

## Details

With above versions, Appium on iOS 13.3 was failing with `Did not get any response after 300 seconds` bug.  It was not possible to use earlier version of Xcode for iOS 13.3.  Same happens with iPadOS 13.3.  

## Proposed Fix

After investigation, it was found that version of `appium-webdriveragent` installed in `/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent` was 2.3.3.  Latest is 2.5.4.  When upgraded manually to 2.5.4 problem was resolved.  This requires a fix to Appium 1.16.0 installer (or perhaps, just the `requirements.txt` file used for `appium-xcuitest-driver`) so that correct version is used.

## Link to Appium logs

N/A

## Code To Reproduce Issue [ Good To Have ]

The `300 second` bug was happening with any test I was running.  It stopped when `appium-webdriveragent` was upgraded to latest as described above.

**Comment by mykola-mokhnach** [comment]
Appium 1.16.0 installs exactly the version that has been shrinkwrapped to it. Please install appium@beta to get the version with most recent available fixes.

Closed as not an issue
