### ISSUE TITLE
Error: Failed to parse APK file

### ISSUE THREAD

**Issue by BLOPESLO** [appium/appium#13888]
## The problem

Sometimes I have an error uninstalling the apk and installing it again.
But most of the time I don't have this error.

Log error:

[debug] [W3C] Encountered internal error running command: Error executing adbExec. Original error: 'Command 'C:\\Users\\******\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 shell pm install -g /data/local/tmp/appium_cache/59767b953ea9760a.apk' exited with code 255'; Stderr: 'Error: Failed to parse APK file: /data/local/tmp/appium_cache/59767b953ea.apk

[debug] [W3C] 

[debug] [W3C] Exception occurred while executing:

[debug] [W3C] java.lang.IllegalArgumentException: Error: Failed to parse APK file: /data/local/tmp/appium_cache/59767b953ea9760a9dd45266792f786130f731f8.apk

## Environment

* Appium version (or git revision) that exhibits the issue:15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:Windows
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:6.7.0
* Mobile platform/version under test:Android 8.0;9; and 10
* Real device or emulator/simulator:Pixel API
* Appium CLI or Appium.app|exe:Appium.exe

**Comment by mykola-mokhnach** [comment]
Please provide the full log. Have you also tried to install the apk manually?

**Comment by BLOPESLO** [comment]
Hi, yes and woks fine.

[debug] [W3C] Encountered internal error running command: Error executing adbExec. Original error: 'Command 'C:\\Users\\******\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 shell pm install -g /data/local/tmp/appium_cache/59767b953ea9760a9dd4526679.apk' exited with code 255'; Stderr: 'Error: Failed to parse APK file: /data/local/tmp/appium_cache/59767b953ea9760a9dd4526679.apk

[debug] [W3C] 

[debug] [W3C] Exception occurred while executing:

[debug] [W3C] java.lang.IllegalArgumentException: Error: Failed to parse APK file: /data/local/tmp/appium_cache/59767b953ea9760a9.apk

[debug] [W3C] 	at com.android.server.pm.PackageManagerShellCommand.setParamsSize(PackageM
anagerShellCommand.java:338)

[debug] [W3C] 	at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:906)

[debug] [W3C] 	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:158)

[debug] [W3C] 	at android.os.ShellCommand.exec(ShellCommand.java:103)

[debug] [W3C]2020-01-29 10:52:16 INFO  MenoresSteps - 


 Menores OK for Test
 	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21328)

[debug] [W3C] 	at android.os.Binder.shellCommand(Binder.java:634)

[debug] [W3C] 	at android.os.Binder.onTransact(Binder.java:532)

[debug] [W3C] 	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2821)

[debug] [W3C] 	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3856)

[debug] [W3C] 	at android.os.Binder.execTransact(Binder.java:731)

[debug] 2020-01-29 10:52:16 INFO  MundoSteps - 


 Mundo 123 OK for Test
[W3C] Caused by: android.content.pm.PackageParser$PackageParserException: Failed to parse /data/local/tmp/appium_cache/59767b953ea9760a9dd4526679.apk

[debug] [W3C] 	at android.content.pm.PackageParser.parseApkLiteInner(PackageParser.java:1590)

[debug] [W3C] 	at android.content.pm.PackageParser.p2020-01-29 10:52:16 INFO  TransferenciasSteps - Transferencia OK for Test
arseApkLite(PackageParser.java:1575)

[debug] [W3C] 	at com.android.server.pm.PackageManagerShellCommand.setParamsSize(PackageManagerShellCommand.java:331)

[debug] [W3C] 	... 9 more'; Code: '255'
[debug] [W3C] Error: Command 'C:\\Users\\******\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 shell pm install -g /data/local/tmp/appium_cache/59767b953ea9760a9.apk' exited with code 255
[debug] [W3C]     at ChildProcess.proc.on.code (C:\Users\******\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\teen_process\lib\exec.js:113:19)
[debug] [W3C]     at ChildProcess.emit (events.js:198:13)
[debug] [W3C]     at maybeClose (internal/child_process.js:982:16)
[debug] [W3C]     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
[HTTP] <-- POST /wd/hub/session 500 37535 ms - 4375
[HTTP]

**Comment by mykola-mokhnach** [comment]
This looks like an issue with package manager itself. Try to disable the internal cache by setting `remoteAppsCacheLimit` capability to zero

**Comment by BLOPESLO** [comment]
It worked.
Thanks

**Comment by surajl11** [comment]
This looks like an issue with package manager itself. Try to disable the internal cache by setting remoteAppsCacheLimit capability to zero ,

how to do that ,please help

**Comment by dgrcode** [comment]
what if you're using an actual phone instead of an emulator? How do you clear all data but for the specific app without breaking everything else?

**Comment by KazuCocoa** [comment]
What is the log? It seems something package manager issue if your environment had no cache like `/data/local/tmp/appium_cache/` in the device that discussed in this thread.
