### ISSUE TITLE
Observing cached connection issue where the test case do not continue to run in iOS real devices

### ISSUE THREAD

**Issue by Pavithra24x7** [appium/appium#13891]
## The problem

I am currently running iOS Automation on a hybrid application where my test cases were passing for a few days. But after a while, the test cases were getting stuck at "Cached Connection: 1". I have tried running the same test cases on other devices and systems, and have observed that the same behaviour pattern appears there as well. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:10.15.2 (19C57) , 10.14.4
* Node.js version (unless using Appium.app|exe):13.1.0
* Npm or Yarn package manager:6.12.1
* Mobile platform/version under test: iOS Platform 12.0(16A366)
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Details
I have executed the test case for Hybrid application on iOS platform few days back successfully the same test case isn't executing now and observed there is an  issue  'Cached connection count: 1' then the test cases are stuck not even failing or stoping the execution just stuck over there itself. 
Scenario 1: Switching from Native to Webview then later switch from Webview to Native. 
Here I could switch from Native to webview but later couldn't switch from Webview to native (Failing to locate the element " [debug] [XCUITest] Executing command 'findElement'
    [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
    [debug] [BaseDriver] Waiting up to 10000 ms for condition
    [debug] [RemoteDebugger] Executing atom 'find_element'
    [debug] [RemoteDebugger] Executing 'find_element' atom in default context
    [debug] [RemoteDebugger] Sending javascript command: '(function(){return function(){var k=this;functi...'
    [debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:2223', page '1' (id: 42)
    [iProxy@5e5e7...] Error: read ECONNRESET
    [iProxy@5e5e7...]     at TCP.onStreamRead (internal/stream_base_commons.js:201:27)
    [ffmpeg] Exiting normally, received signal 2.
    [ffmpeg] 
    [DevCon Factory] Releasing connections for 5e5e74b9cc32526ace85c52cd8abb30cab00e52a device on 9100 port number
    [DevCon Factory] Found cached connections to release: ["5e5e74b9cc32526ace85c52cd8abb30cab00e52a:9100"]
    [DevCon Factory] Releasing the listener for '5e5e74b9cc32526ace85c52cd8abb30cab00e52a:9100'
    [debug] [DevCon Factory] Cached connections count: 1
    [debug] [W3C (aac8da43)] Encountered internal error running command: Error: Did not get any response after 300s
    [debug] [W3C (aac8da43)]     at XCUITestDriver.waitForAtom (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/web.js:280:13)
    [HTTP] <-- POST /wd/hub/session/aac8da43-9972-4017-a20e-70ec531df0e4/element 500 300038 ms - 567" showing the above logs.
Scenario 2: Failed to Switch from Native to Webview and getting WebdriverException.

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/Pavithra24x7/94ab4b15fb43246e10a6b7a41deac4cb

**Comment by mykola-mokhnach** [comment]
Please use the most recent server version appium@beta

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by Pavithra24x7** [comment]
This has been fixed in the Appium 1.17.0
