### ISSUE TITLE
unable to get udid from session detail for web

### ISSUE THREAD

**Issue by sandaliqbal1** [appium/appium#13897]
## The problem

I'm running web automation on android using appium but getSessionDetails doesnt show the udid of the device.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MAC Mojave 10.14.6 
* Node.js version (unless using Appium.app|exe): v13.6.0
* Npm or Yarn package manager: npm version 6.13.4
* Mobile platform/version under test: android 9
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: CLI

## Details

Run any web automation using appium and call getSessionDetail("udid"). It is null.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Where in the documentation it is stated that `getSessionDetail` should include device id? Also this endpoint is not part of W3C spec

**Comment by sandaliqbal1** [comment]
Well it works very well for mobile app and returns the device id correctly so I believe the behavior should be the same for mobile web as well? If not how can I get the udid of the current device on which web automation is running?

**Comment by mykola-mokhnach** [comment]
perhaps from session capabilities?

**Comment by sandaliqbal1** [comment]
Yes getCapabilities().getCapability("udid") seems to work as well.
