### ISSUE TITLE
Appium/Android Emulator/app: Unable to hide softkeyboard using driver.hideKeyboard();

### ISSUE THREAD

**Issue by SeemaT123** [appium/appium#13896]
## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Appium Desktop
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: Android Platform V28
* Real device or emulator/simulator:emulator
* Appium CLI or Appium.app|exe: appium.app

## Details

@Test(priority= 2) 
	public void login_to_GurkhaApp(){
		GurkhaLogin L = new GurkhaLogin(driver);
		L. Adding_Scty(driver);
	//	driver.navigate().back();
		driver.hideKeyboard();
		L.Add_Scty_btn.click();
		
		
	}
## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Please fill out the reporting form properly and provide the full server log

**Comment by SeemaT123** [comment]
hi @mykola-mokhnach  just now i solved the issue using define desired capabilities
capabilities.setCapability("unicodeKeyboard", true);
capabilities.setCapability("resetKeyboard", true);
My concern was when for test Java project, used driver.hideKeyboard(); to hide softkeyboard & it worked, now I'm designing test framework using TestNG & Page factory(POM). Its not working Appium server log is 200 response bu Eclipse IDE was failing my test cases showing unable to locate element.
Current Info: using JAVA-Maven Project
POM- <project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.appium.demo</groupId>
	<artifactId>AppiumProj</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<dependencies>
		
		<dependency>
			<groupId>io.appium</groupId>
			<artifactId>java-client</artifactId>
			
			<version>7.3.0</version>
		</dependency>
		
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>3.141.59</version>
		</dependency>
		
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>7.0.0</version>
			<scope>test</scope>
		</dependency>
		  <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-math3</artifactId>
                <version>3.6.1</version>
     </dependency>

	</dependencies>

</project>

**Comment by mykola-mokhnach** [comment]
> My concern was when for test Java project, used driver.hideKeyboard(); to hide softkeyboard & it worked, now I'm designing test framework using TestNG & Page factory(POM). Its not working Appium server log is 200 response bu Eclipse IDE was failing my test cases showing unable to locate element.

Kindly report your issue to https://github.com/appium/java-client if you think this is an issue of java client lib. Also, we have [Appium forum](discuss.appium.io) for any sort of questions. 

Closed as not an issue

**Comment by SeemaT123** [comment]
Thanks @mykola-mokhnach
