### ISSUE TITLE
Google Maps Not Displaying on Android Emulator After Including "noSign" Capability

### ISSUE THREAD

**Issue by SeanMcQuaidCFA** [appium/appium#13892]
## The problem

As it stands, when I load up my company's application via Appium, the screen that includes Google Maps on the page just displays a blank area where the map should be. 

## Environment

* Appium version that exhibits the issue: 1.16.0
* Desktop OS/version used to run Appium: macOS Mojave - 10.14.6 (18G2022)
* Node.js version :12.2.0
* Npm or Yarn package manager: Npm
* Mobile platform/version under test: Android 10.0
* Real device or emulator/simulator: Pixel 2
* Appium CLI or Appium.app|exe: CLI

## Details

After doing some research, I speculated that this might be because Appium resigns the apk. So I implemented the "noSign" desired capability and set it to true. However, Google Maps is still displaying as a blank screen. I am unsure how to go about fixing this and prevent resigning or even taking next steps.

## Code To Reproduce Issue

Here are my desired capabilities that I am using : 

appium.automationName=UIAutomator2
appium.noSign = true
appium.deviceName=Android
appium.platformVersion=10
appium.platformName=Android
appium.app = appNameHere.apk

**Comment by mykola-mokhnach** [comment]
I would try to enable the debug logs for the component and see what it wants in the logcat output
