### ISSUE TITLE
Appium GUI 1.15.1 and 1.16.0 - Installs WebDriverAgentRunner on real iOS device - Installs ipa on real device - then removes them an throws bundleId error 

### ISSUE THREAD

**Issue by crhoads1024** [appium/appium#13894]
## The problem
Attempting to load ipa file on physical device via Appium GUI launch or running my smoke test runner launch which currently is just loading desired caps trying to get the app to launch on the phone. 

- Installs the WDA to the phone, Installs the ipa to the phone, then removes the WDA and throws a 'desired capability: bundleId' not provided error, despite the logs showing it extracted he bundleId just fine. It throws the bundleId error even if I send the desiredCap: bundleId.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0 and 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): N/A - Fresh Install On New Macbook Pro
* Desktop OS/version used to run Appium: OSX Catalina 10.15.2
* Node.js version (unless using Appium.app|exe): v13.6.0
* Npm: 6.13.4
* Mobile platform/version under test: iOS 13.3
* Real device: Physical iPhone 6s
* Appium CLI: 1.16.0
* Appium.app|exe: 1.15.1

## Details

Trying to launch from tests in cli or with the Appium GUI I see the WDA get loaded on the phone, I see the app get loaded on the phone, then I see the WDA get removed from the phone and the test or GUI app launch results in the same error:

- [debug] [MJSONWP] Encountered internal error running command: Error: Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: 'bundleId' desired capability not provided Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.

It is removed, I have rebooted... nothing seems to work.

running  xcodebuild -project WebDriverAgent.xcodeproj -allowProvisioningUpdates -scheme WebDriverAgentRunner -destination 'id=myUDID' test
builds without a problem.

As I said before, It even loads the WDA as seen here from the logs

- [debug] [XCUITest] WebDriverAgent successfully started after 8510ms

And app on the phone successfully as seen here

- [debug] [BaseDriver] Event 'appInstalled' logged at 1580408849916 (12:27:29 GMT-0600 (CST))

Then it strips them and leaves a confusing no bundleId error in the logs in various forms... I have used caps with and without the bundleId and it makes no difference.
Seen Here:

- [debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: 'bundleId' desired capability not provided). Retrying...

- [debug] [XCUITest] UnknownError: An unknown server-side error occurred while processing the command. Original error: 'bundleId' desired capability not provided

## Link to Appium logs

- https://gist.github.com/crhoads1024/b1b796bf325df7334c6bc5258977a6cd

## Code To Reproduce Issue [ Good To Have ]

The only code I have was setting the desired caps to launch the app just to test running it from the cli. I haven't gotten far enough to actually write any test code since i began installing on this new machine.

- Same result comes from using the GUI to launch as it does the cli and/or code

**Comment by mykola-mokhnach** [comment]
It seems like you have an older WebDriverAgent version cached on your device. Remove it manually from the device, clear the xcode caches and then rerun the test

**Comment by crhoads1024** [comment]
Investigating.

**Comment by crhoads1024** [comment]
@mykola-mokhnach Is this WDA cached load shown in the logs? 
I was under the impression that setting "useNewWDA" : "true" and "fullReset" : "true" would clear any WDA and ipa's on the device and watching them load and be stripped seemed to illustrate that assumption.

Is this not the case?

Does WDA look for and load a cached version first if its available? 
When it clears the WDA does it just remove the WDARunner.app and not clear any caches?
Just trying to understand the flow of how this process is handled.

Will clear caches on phone and xcode and report back.
Thank you for your quick response!

**Comment by crhoads1024** [comment]
Clearing Xcode cache enabled the device to clear the above stated bundleId error.
Thank you very much for this resolution.

The error encountered now is that when I run the test, the app under test and the developer trust setting for the signed App is removed from the Profile section.

How can we make the developer trust persist between tests? 
I have the orgId and am a member of the developer team, is this an incorrect provision profile, certificate issue?
I do not remember ever dealing with the developer trust setting disappearing when the app is removed.

Thank you again for your help in this matter.

**Comment by crhoads1024** [comment]
@mykola-mokhnach 
 I have resolved the issue, and it's my total oversight.

I was able to discover the issue when I turned on the server capability "showXcodeLog": "true".
Prior to this I was only using "showiOSLog": "true", so I was only able to see the WebDriverAppRunner error "incorrect bundleId".

When I turned on the Xcode log, I was able to see the specific path from which the error originated.
I opened up that WebDriverAppRunner.xcodeproj in xcode and set the proper bundleId for WebDriverRunnerLib and WebDriverRunner.App and clicked build and it failed.
The Xcode error cited the Integration app bundleId mismatch. So I set the bundleId for the integration app to the launch app bundleId <--- DONT DO THAT!! lol

When I did that, then the app would load and then the integration app would load and they would launch simultaneously.
To remedy this, I deleted the integration app in Xcode, cleared the xcode build cache, clicked build and it succeeded!

I then opened the Appium GUI, and watched in delight as the app successfully launched on my iPhone.
Thank goodness I turned on the Xcode log!

The path to the Appium GUI 1.15.1 is installed by default at /Applications/Appium.app/Contents/Resources/app/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj

The path to the Appium CLI 1.16.0 is installed at /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj

Why? 

The CLI was installed by Homebrew on this mac.
The GUI was installed by a downloaded .dmg application installer.

I hope this information helps someone else with this configuration issue.

**Comment by mykola-mokhnach** [comment]
> The path to the Appium GUI 1.15.1 is installed by default at /Applications/Appium.app/Contents/Resources/app/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj
> 
> The path to the Appium CLI 1.16.0 is installed at /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj
> 
> Why? 

This is usually decided by NodePackageManager based on which dependencies the other modules have and whether these dependencies are duplicated or not. See https://github.com/appium/appium/issues/13836
