### ISSUE TITLE
How to scroll using wd in javascript?

### ISSUE THREAD

**Issue by Nisthar** [appium/appium#13900]
why is this issue closed? https://github.com/appium/appium/issues/6282

**Comment by mykola-mokhnach** [comment]
The issue was closed because `mobile: scroll` method is only available for xcuitest driver.

Kindly use Appium forum to ask questions.

**Comment by Nisthar** [comment]
@mykola-mokhnach So how can i scroll using appium wd driver?

**Comment by mykola-mokhnach** [comment]
No idea, I've never tried that

**Comment by Nisthar** [comment]
@mykola-mokhnach so whys the issue closed?

**Comment by mykola-mokhnach** [comment]
because it is not a server issue and for questions there is more appropriate place

**Comment by Nisthar** [comment]
@mykola-mokhnach Are you sure about that? it looks like a server issue to me
This is the error i am getting on server:
```
[HTTP] --> POST /wd/hub/session/5d8de3de-6084-4a10-ac7b-0ebd470e2249/touch/scroll
[HTTP] {"xoffset":10,"yoffset":200}
[MJSONWP (5d8de3de)] Driver proxy active, passing request on via HTTP proxy
[WD Proxy] Proxying [POST /wd/hub/session/5d8de3de-6084-4a10-ac7b-0ebd470e2249/touch/scroll] to [POST http://localhost:8207/wd/hub/session/ae0d684e-bdf3-4f30-85ac-0eaea3b622ff/touch/scroll] with body: {"xoffset":10,"yoffset":200}
[WD Proxy] Got an unexpected response with status 500: {"sessionId":"ae0d684e-bdf3-4f30-85ac-0eaea3b622ff","value":{"error":"unknown error","message":"com.jayway.jsonpath.InvalidPathException: invalid path","stacktrace":"com.jayway.jsonpath.InvalidPathException: invalid path\n\tat com.jayway.jsonpath.internal.filter.FieldFilter.filter(FieldFilter.java:59)\n\tat com.jayway.jsonpath.JsonPath.read(JsonPath.java:191)\n\tat com.jayway.jsonpath.JsonPath.read(JsonPath.java:211)\n\tat io.appium.uiautomator2.handler.ScrollTo.safeHandle(ScrollTo.java:40)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:38)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:252)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:242)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext...
```

**Comment by mykola-mokhnach** [comment]
yes, I'm sure about that. The server expects different arguments, so the exception is expected: https://github.com/appium/appium/issues/12043#issuecomment-456105305

**Comment by Nisthar** [comment]
@mykola-mokhnach ok, do you know the correct arguments? or where to look for?

**Comment by mykola-mokhnach** [comment]
Acceptable parameters could be found in the appropriate handler code: https://github.com/appium/appium-uiautomator2-server/blob/b9eb11f2101fffa95728b8c7ba78747eeea3a7c4/app/src/main/java/io/appium/uiautomator2/handler/ScrollTo.java#L36

**Comment by Nisthar** [comment]
@mykola-mokhnach I got the client code from appium doc site here: https://appium.readthedocs.io/en/latest/en/commands/interactions/touch/scroll/

`await driver.scroll(10, 100);`

I am not good with java code. Can you tell me the parameters required for the command?
Also, The error didn't mention anything about missing parameters.
