### ISSUE TITLE
Upgrading apk with driver.installApp fails with adb error INSTALL_FAILED_UPDATE_INCOMPATIBLE

### ISSUE THREAD

**Issue by eleni-salamani** [appium/appium#13908]
## The problem

I am trying to implement a testcase, that would allow us to test the upgrade of the same app. The flow generally goes like this:
- initiate driver 
- first test installs v.1 and logs in the user
- second test calls driver.installApp to upgrade the app

When the test including driver.installApp is called, it fails with:
_An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/Users/elenasalamani/Library/Android/sdk/platform-tools/adb -P 5037 -s LGH850c35a2ef4 shell pm install -r -t -g /data/local/tmp/appium_cache/9c80ed1f2464b420a86f0b17f6cd3397225bffb9.apk' exited with code 1'; Stderr: 'Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.ef.core.engage.corporate signatures do not match the previously installed version; ignoring!]'; Code: '1'_

When I call directly the command mentioned in the output, I get the same error
/Users/elenasalamani/Library/Android/sdk/platform-tools/adb -P 5037 -s LGH850c35a2ef4 shell pm install -r -t -g /data/local/tmp/appium_cache/9c80ed1f2464b420a86f0b17f6cd3397225bffb9.apk
Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.ef.core.engage.corporate signatures do not match the previously installed version; ignoring!]

However, manual installation of the second apk on top of the original one works directly on the device.

## Environment

* Appium version (or git revision) that exhibits the issue:
appium --version
1.15.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
MacOS Mojave 10.14.6
* Node.js version (unless using Appium.app|exe):
node --version
v13.1.0
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
LG G8 running Android 9
LG G5 running Android 7
Any of the two devices is connected via USB to the laptop and has
- developer options with USB debugging enabled
- verify apps over USB option disabled
- Play Protect check disabled
* Appium CLI or Appium.app|exe:
* adb version
adb --version
Android Debug Bridge version 1.0.41
Version 29.0.4-5871666

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
https://gist.github.com/eleni-salamani/8446dc3d9e5de1948a46dcd3cad443ec

## Code To Reproduce Issue [ Good To Have ]
- check the gist for the desired capabilities set during driver creation
- the test to re-install the app is as follows
private static final String newAppPath = "/Users/elenasalamani/Documents/install-tests/engage-corporate-live-debug_350.apk";

 @Test(priority = 2)
    public void update_app_and_remain_logged_in() {
        LOGGER.info("Starting test: update_app_and_remain_logged_in");
        driver.terminateApp(testRunProperties.getAppPackage());
        AndroidInstallApplicationOptions androidInstallationOptions = new AndroidInstallApplicationOptions();
        androidInstallationOptions.withGrantPermissionsEnabled();
        androidInstallationOptions.withReplaceEnabled();
        androidInstallationOptions.withAllowTestPackagesEnabled();
        androidInstallationOptions.withUseSdcardDisabled();
        androidInstallationOptions.withTimeout(Duration.ofSeconds(50));
        driver.installApp(newAppPath, androidInstallationOptions);
        LOGGER.info("Ending test: update_app_and_remain_logged_in");
    }

Is there anything additional that needs to be set up so that upgrade via appium works?
Please note that I also included NO_RESET = true for one round of tests but nothing changed, the same error occurred.

**Comment by mykola-mokhnach** [comment]
This error is thrown by adb if it cannot confirm the already installed and the current packages are instances of the same application, so the error is expected.

I would make sure the packages are built on the same server and that they have the same signature (note, that Appium overrides the default package signature by default, this can be changed by setting the `noSign` cap to true)

**Comment by eleni-salamani** [comment]
Many thanks for the prompt reply. To be honest the original apks were signed with the same keystore, so the error seemed unjustified. However, your hint for the capability **noSign**, made all the difference. I noticed that after some runs the apks had different signatures, my understanding is that appium was signing the original one I was setting in the capability app so when I was calling driver.installApp, the comparison was failing.
By restoring the original apks and setting the capability noSign to true, the installation worked for me. Many thanks!

**Comment by ranjanashish00** [comment]
Hi @eleni-salamani ,

I could not understand this part.
> By restoring the original apks

I have two apks(v1 & v2). I am setting v1 in capabilities with `noSign` to `true`.
And after performing few actions on v1, I am calling `driver.installApp(v2)`.
Still I am facing same issue.
