### ISSUE TITLE
Chromedriver auto download switches around key and value in the mapping file

### ISSUE THREAD

**Issue by aberx1** [appium/appium#13912]
## The problem

I am using the appiumDriverLocalService with the auto chromedriver autodownload argument
`AppiumDriverLocalService service = AppiumDriverLocalService.buildService(new AppiumServiceBuilder().usingAnyFreePort().withArgument(() -> "--allow-insecure","chromedriver_autodownload"));`

With the capability "chromedriverChromeMappingFile" defined, this should fill up the mapping file with the required versions and automatically download any required versions to execute the tests.

The issue: it fills up the mapping file but switches around keys and values so when the chromedriver goes to look for the correct driver file to use it cannot find a suitable version.

Manually switching key and value makes the test execute so i'm sure this is the issue.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.16.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows
* Node.js version (unless using Appium.app|exe): v8.11.4
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Android (hybrid app)
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: not sure, using AppiumDriverLocalService included in Appium dependency 7.3.0 on Maven Central

used desiredCapabilities:
`{"desiredCapabilities":{"appActivity":"","appPackage":"","chromedriverChromeMappingFile":"C:\\projects\\doccle-qa\\testautomation\\src\\test\\resources\\Doccle\\utilities\\chromedriver\\chromedriverChromeMappingFile","newCommandTimeout":300,"platformName":"Android","deviceName":"*","platform":"ANDROID"},"capabilities":{"firstMatch":[{"appium:appActivity":"","appium:appPackage":"","appium:chromedriverChromeMappingFile":"C:\\projects\\censored\\testautomation\\src\\test\\resources\\censored\\utilities\\chromedriver\\chromedriverChromeMappingFile","appium:deviceName":"*","appium:newCommandTimeout":300,"platform":"ANDROID","platformName":"android"}]}}`

chromedriverChromeMappingFile:
{
  "79.0.3945.16": "79",
  "79.0.3945.36": "79"
}

should be:

{
  "79": "79.0.3945.16",
  "79": "79.0.3945.36"
}

## Link to Appium logs

https://gist.github.com/aberx1/fe313617dbdf0a9254fe51bb01e0614c

**Comment by mykola-mokhnach** [comment]
> [Chromedriver] Cannot retrieve version number from 'chromedriver_win32_v79.0.3945.16.exe' Chromedriver binary. Make sure it returns a valid version string in response to '--version' command line argument. spawn EBUSY
> [Chromedriver] Cannot retrieve version number from 'chromedriver_win32_v79.0.3945.36.exe' Chromedriver binary. Make sure it returns a valid version string in response to '--version' command line argument. spawn EBUSY

There are some things that don't work properly there, but I don't like these logs. It looks like the OS is blocking the downloaded drivers from being executed and thus the code cannot determine their versions

**Comment by aberx1** [comment]
I have no idea why it is unable to retrieve the --version. I tried it manually and the versions are returned. When i swap the key and value in the chromedriverChromeMappingFile manually these logs are still produced but the tests are run. 
logs with the keys and values switched manually (included bad locator to stop test and reduce logs): https://gist.github.com/aberx1/907d06a8f1d1d494e88acd9e94f977cf

**Comment by aberx1** [comment]
I just realised that after running with the chromedriverChromeMappingFile manually set to
`{
"79": "79.0.3945.16",
"79": "79.0.3945.36"
}`

the file was automatically changed to:
`{
  "79": {
    "options": {},
    "loose": false,
    "raw": "79.0.3945",
    "major": 79,
    "minor": 0,
    "patch": 3945,
    "prerelease": [],
    "build": [],
    "version": "79.0.3945"
  },
  "79.0.3945.36": "79",
  "79.0.3945.16": "79"
}`

**Comment by mykola-mokhnach** [comment]
> I just realised that after running with the chromedriverChromeMappingFile manually set to
> { "79": "79.0.3945.16", "79": "79.0.3945.36" }
> 
> the file was automatically changed to:
> { "79": { "options": {}, "loose": false, "raw": "79.0.3945", "major": 79, "minor": 0, "patch": 3945, "prerelease": [], "build": [], "version": "79.0.3945" }, "79.0.3945.36": "79", "79.0.3945.16": "79" }

Thanks, this is already something to work on

> I have no idea why it is unable to retrieve the --version
EBUSY is most likely thrown because the file is being locked by some antivirus/malware scanning service. Make sure all such stuff is disabled on the machine where your tests are running

**Comment by mykola-mokhnach** [comment]
The patch has been published to appium@beta

**Comment by mykola-mokhnach** [comment]
Also regarding the format of the mapping file: its keys should be valid chromedriver version strings. Exact match is applied here. Values are minmum chrome browser version numbers supported by corresponding chromedrivers. These values can also consist of single numbers, because we only consider the major browser version for matching.
