### ISSUE TITLE
multiple appium instances on same machine for parallel automation run

### ISSUE THREAD

**Issue by komissar2007** [appium/appium#13914]
## The problem

Im running multiple instances of appium in parallel on iOS simulator and there is also a possibility of running this processes for different OS versions (iOS 11 and iOS 13) which require different xCode versions .
changing xcode versions with xcode-select will impact all my running instances.
so the issue comes from node-simctl/lib/[simctl.js](https://github.com/appium/node-simctl/blob/master/lib/simctl.js)

in simctl.js there is command for simctl bin file which defined by xcode-select.
instead of direct call to simctl from /usr/bin folder I need to call simctl from desired xcode version giving absolute path.

## Environment

* Appium version 1.16
* macOS mojave
* Node.js 8.x:
* Npm 
* Mobile platform/version under test:
iOS 12.2, iOS 13.2
* Real device or emulator/simulator:
iOS simulators
* Appium CLI

**Comment by mykola-mokhnach** [comment]
@komissar2007 Have you tried to set DEVELOPER_DIR per process instead of using xcode-select? See https://macops.ca/developer-binaries-on-os-x-xcode-select-and-xcrun/

**Comment by komissar2007** [comment]
will try and update,
thank you !

**Comment by komissar2007** [comment]
thank you!
it works
