### ISSUE TITLE
[XCUITest] Error: Command 'idevice_id -l' errored out: Error: spawn idevice_id ENOENT

### ISSUE THREAD

**Issue by abhisqa** [appium/appium#13919]
## The problem
[XCUITest] Error: Command 'idevice_id -l' errored out: Error: spawn idevice_id ENOENT error appearing when trying to execute my tests using updated Appium version (1.14.0)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.0
* Last Appium version that did not exhibit the issue (if applicable): 1.8.1
* Desktop OS/version used to run Appium: Mac OS 10.14.6
* Node.js version (unless using Appium.app|exe):  13.7.0
* Npm or Yarn package manager: 6.13.6
* Mobile platform/version under test: iOS 13.2.2
* Real device or emulator/simulator: simulator iPhone 8
* Appium CLI or Appium.app|exe: Apple CLI

## Details

I am facing configuration related error while updating to new appium and xcode version
current Appium version: 1.8.1
New Appium version : 1.14.0
current xcode version: 9.4.1
New xcode version: 11.2.1
Current iOS version for Simulator (iPhone 8) : 11.4
New iOS version for Simulator (iPhone 8) :  13.2.2

Note: 1 - xcodebuild - WebDriverAgent.xdoceproj - scheme WebDriverAgentRunner - destination 'id=XXXXXXXX-XXXX-XXXX-XXXXX-XXXXXXXXXXXXX’ test command is not executed during last step of set up process. (as i redo the appium set up process from scratch)

Note: 2. I have currently 2 xcode projects in my Application folder
1 - Xcode 9.4.1 (named as Xcode 9.4.1)
2 - Xcode 11.2.1 (named as Xcode)

i also tried to fix it by runnning 'brew install libimobiledevice --HEAD' mentioned in
https://github.com/appium/appium/issues/8031 , it didn't worked for me also.

**Though i am able to run my test using Appium Desktop v1.15.1**

## Link to Appium logs
https://gist.github.com/abhisqa/b8ee6990fb6a0dc3ffcda75e2d28a36c

## Code To Reproduce Issue [ Good To Have ]

Not Applicable.

**Comment by mykola-mokhnach** [comment]
Appium 1.14 does not support iOS13. Consider updating the server to the most recent version

**Comment by mykola-mokhnach** [comment]
Unfortunately we don't provide patches to older versions

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
