### ISSUE TITLE
Safari browser stuck on iOS 13.3. Appium version 1.16.0

### ISSUE THREAD

**Issue by dips22221990** [appium/appium#13917]
## The problem

When I run my test case for the first time when there is no tab test case works fine.
If I run the same test case 2nd time it opens the same tab with the last URI and stucks.

Log Message:
we are in the middle of selecting a page, ignoring appium

## Environment

* Appium version : 1.16.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac
* Node.js version (unless using Appium.app|exe): 13.5.0
* Npm or Yarn package manager: 6.13.4
* Mobile platform/version under test: iPhone 6 iOS 13.3
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe:

## Link to Appium logs

Appium Log Link: https://gist.github.com/dips22221990/24fc4040c6cb5101e9dc9eeecb213cac

## Code To Reproduce Issue 

I am opening a Safari Browser on iPhone 13.3.

And navigating to URl.

And trying to click on a button.

**Comment by mykola-mokhnach** [comment]
Please try appium@beta

**Comment by dips22221990** [comment]
@mykola-mokhnach : Its working with beta version. But when this will be released ?

And If I use beta version will the existing test cases that I have automated work?

Is there any workaround for appium 1.16.0 that I can use ?

**Comment by mykola-mokhnach** [comment]
> But when this will be released ?

I don't know

> And If I use beta version will the existing test cases that I have automated work?

They should work, we do our best to keep the beta stable. Please let us know if you find any more issues there

> Is there any workaround for appium 1.16.0 that I can use ?

You could try to update the appium-xcuitest-driver package and its dependencies manually, hoverer it might be a pain.

**Comment by mykola-mokhnach** [comment]
Closed as fixed
