### ISSUE TITLE
[iOS 13.2.2] Unable to use ActionChain commands in iOS WebView

### ISSUE THREAD

**Issue by clifford-polarr** [appium/appium#13924]
## The problem

Getting an error when attempting to use ActionChain commands in iOS WebView

## Environment

* Appium version 1.16.0
* Desktop OS: macOS 10.15.2
* MobileOS: iOS 13.2.2
* Real device
* Appium CLI

## Details

I'm getting the following error in my logs:
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "Unsupported origin type '{
          ELEMENT = 5005;
          "element-6066-11e4-a52e-4f735466cecf" = 5005;
      }' is set for '{
          duration = 250;
          origin =     {
              ELEMENT = 5005;
              "element-6066-11e4-a52e-4f735466cecf" = 5005;
          };
          type = pointerMove;
          x = 0;
          y = 0;
      }' action item. Supported origin types: (
          pointer,
          viewport
      ) or an element instance" UserInfo={NSLocalizedDescription=Unsupported origin type '{
          ELEMENT = 5005;
          "element-6066-11e4-a52e-4f735466cecf" = 5005;
      }' is set for '{
          duration = 250;
          origin =     {
              ELEMENT = 5005;
              "element-6066-11e4-a52e-4f735466cecf" = 5005;
          };
          type = pointerMove;
          x = 0;
          y = 0;
      }' action item. Supported origin types: (
          pointer,
          viewport
      ) or an element instance}

## Link to Appium logs

https://gist.github.com/clifford-polarr/da68e84c76fa92c1f91a464d578e6a11

## Code To Reproduce Issue [ Good To Have ]

slide = context.driver.find_element(By.XPATH, '//div[@name="slider"]')
action_chain.move_to_element(slide)
action_chain.click_and_hold()
action_chain.move_by_offset(x_offset, 0)
action_chain.release()
action_chain.perform()

**Comment by mykola-mokhnach** [comment]
This is by design. In web view mode it is only possible to use absolute coordinates for touch actions. Otherwise consider emulating them via custom javascript as a workaround.

**Comment by clifford-polarr** [comment]
I'm not using touch actions though, I'm using click actions, which I thought was allowed in webview.  It works on android, just not iOS.

**Comment by mykola-mokhnach** [comment]
It does not matter, action chains only support native elements because they are executed in native context. Elements found in web view context won't work there

**Comment by clifford-polarr** [comment]
Thank you very much for your time and clearing up my misconceptions on the subject.
