### ISSUE TITLE
What is the correct units for Android screen recording bitrate parameter.

### ISSUE THREAD

**Issue by kolyakrasnik** [appium/appium#13921]
We are using java with appium. There are some mismatch in documentation for android video bitrate parameter. In appium.io this parameter (options.bitRate) is listed like 4 Mbp/s http://appium.io/docs/en/commands/device/recording-screen/start-recording-screen/
`
options.bitRate --> (Android Only) The video bit rate for the video, in megabits per second. 4 Mbp/s(4000000) is by default for Android API level below 27. 20 Mb/s(20000000) for API level 27 and above.
`
In java client comments I see 
` The default value is 4000000 (4 Mb/s) for Android API level below 27 and 20000000 (20 Mb/s) for API level 27 and above.`
https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/android/AndroidStartScreenRecordingOptions.java

In appium code I see 
`@property  bitRate - The video bit rate for the video, in megabits per second.
The default value is 4. You can increase the bit rate to improve video quality,
but doing so results in larger movie files.`
https://github.com/appium/appium-android-driver/blob/aea08d0e2fedc796a93ee86ce5211f2dd7dd8564/lib/commands/recordscreen.js

The question is which units is correct? Should we use bitRate=4 or bitRate=4000000 for this parameter in our code?

**Comment by mykola-mokhnach** [comment]
the correct value would be 4000000 (bits per second). There is a typo in the docs
