### ISSUE TITLE
WDA issue with iOS 13.3.1 - fails with error code 65

### ISSUE THREAD

**Issue by tusharwgames** [appium/appium#13927]
## The problem

After updating my iOS devices to 13.3.1, WebDriverAgentRunner is not launching during tests and throws. Same setup works with iOS 13.3.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0 (also in 1.15.1/1.15.0)
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS Mojave 10.14.6
* Node.js version (unless using Appium.app|exe):v12.8.1
* Npm or Yarn package manager: npm 
* Mobile platform/version under test: iOS 13.3.1
* Real device or emulator/simulator: Real device 
* Appium CLI or Appium.app|exe: CLI

## Details

Test for WDA also fails when done through terminal using `xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' test`.

`Testing failed:
	WebDriverAgentRunner:
		WebDriverAgentRunner-Runner.app (401) encountered an error (Failed to load the test bundle. (Underlying error: The bundle “WebDriverAgentRunner” couldn’t be loaded because it is damaged or missing necessary resources. The bundle is damaged or missing necessary resources. dlopen_preflight(/var/containers/Bundle/Application/8E2FE945-0283-4FC9-9EE1-882E297CBF43/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner): no suitable image found.  Did find:
	/var/containers/Bundle/Application/8E2FE945-0283-4FC9-9EE1-882E297CBF43/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner: code signature invalid for '/var/containers/Bundle/Application/8E2FE945-0283-4FC9-9EE1-882E297CBF43/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner'
))
`

## Link to Appium logs

https://gist.github.com/tusharwgames/8e6b43b7620de6cafce82c9c06242966

**Comment by imurchie** [comment]
Try removing the existing derived data (`rm -rf /Users/wgamesqa/Library/Developer/Xcode/DerivedData/WebDriverAgent-*`)

Then see what happens when running 
```
xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=62ee9a100df99b304e6974bef73b0f1804236e4c IPHONEOS_DEPLOYMENT_TARGET=13.3 -xcconfig /var/folders/3k/9ncq39y93cq2kr0svmxjx9ww0000gn/T/202017-41698-fs3gsk.wboel/appium-temp.xcconfig GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO
```
In directory `/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent`

**Comment by tusharwgames** [comment]
It still ends with the following error:
```Testing failed:
	WebDriverAgentRunner:
		WebDriverAgentRunner-Runner.app (366) encountered an error (Failed to load the test bundle. (Underlying error: The bundle “WebDriverAgentRunner” couldn’t be loaded because it is damaged or missing necessary resources. The bundle is damaged or missing necessary resources. dlopen_preflight(/var/containers/Bundle/Application/38DFC3C6-A2B1-4662-AD15-369E619D4C86/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner): no suitable image found.  Did find:
	/var/containers/Bundle/Application/38DFC3C6-A2B1-4662-AD15-369E619D4C86/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner: code signature invalid for '/var/containers/Bundle/Application/38DFC3C6-A2B1-4662-AD15-369E619D4C86/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner'
))```

Full logs: https://gist.githubusercontent.com/tusharwgames/fb57050009e336abddd637c0a4187381/raw/3a6bf323bf7218fac2582837256bf87555d9cfa7/terminallogs.txt

**Comment by mykola-mokhnach** [comment]
> Did find: /var/containers/Bundle/Application/38DFC3C6-A2B1-4662-AD15-369E619D4C86/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner: code signature invalid for '/var/containers/Bundle/Application/38DFC3C6-A2B1-4662-AD15-369E619D4C86/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner' ))

Problems with the codesigning? Does the build pass if done manually?

**Comment by tusharwgames** [comment]
Even if done through Xcode, the test fails.
But it passes for iOS 13.3 either way.

The only change was that I updated to iOS 13.3.1.

**Comment by mykola-mokhnach** [comment]
This looks like a bug in Xcode to me

**Comment by tusharwgames** [comment]
I've tried updating to Xcode 11.3.1 from 11.3 to see if it would help but it's still the same.

**Comment by thenishant** [comment]
Same here as well

**Comment by annabutenko** [comment]
Same issue. Tests were working with iOS 13.3 but the issue started to occur after I updated iOS up to 13.3.1

**Comment by KazuCocoa** [comment]
It looks Xcode has an issue.
I faced an error with a personal account only on iOS 13.3.1. https://github.com/appium/appium/issues/13890

Perhaps this issue is not the same, but Xcode 11.3 and iOS 13.3.1 probably has an issue.

**Comment by unrealwzg** [comment]
This maybe an Xcode signing issue, after I making iOS allow unsigned IPA via jailbreak tweak, this issue has gone.

**Comment by lajoli94** [comment]
Exact same problem with 13.3.1, Worked fine with 13.3

**Comment by amedvedjev** [comment]
ios 13.3.1
latest 1.16 Appium
all good.

**Comment by annabutenko** [comment]
@amedvedjev Could you please share your caps?

**Comment by amedvedjev** [comment]
@annabutenko here it is (details hidden a bit)
```
[16:53:29.204] Capabilities {app: /Users/xxxxx/Doc..., automationName: XCuiTest, bundleId: com.xxxx.dev, clearSystemFiles: true, deviceName: iPhone 8, fullContextList: true, fullReset: false, mjpegServerPort: 6200, nativeWebTap: true, newCommandTimeout: 180, noReset: true, platformName: iOS, platformVersion: 13.3, processArguments: {"args":["-featureFlag.CB: ..., sendKeyStrategy: grouped, skipDeviceInitialization: true, skipServerInstallation: true, useJSONSource: true, usePrebuiltWDA: true, wdaLaunchTimeout: 120000, wdaLocalPort: 8000, wdaStartupRetries: 4}

```

**Comment by tusharwgames** [comment]
@amedvedjev Are you signing with a paid account? I have the exact same setup after even updating macOS but it isn't working.

**Comment by amedvedjev** [comment]
@tusharwgames yes. i am signing WDA with paid company developer account which used by many iOS dev in our company (my account just included into company developer profile). app under test signed with same certificate.

**Comment by nethajiprabhu-gunasekaran** [comment]
Same problem here, works fine on other iOS versions but not on 13.3.1 and xcode Version 11.3.

**Comment by lajoli94** [comment]
Rollbacked to 13.3, working fine. Something's up with xcode probably.

**Comment by NirBY** [comment]
@lajoli94 how did you rollback?
Is there a way rolling back to non-jailbroken iPhone?

**Comment by tusharwgames** [comment]
@NirBY I used this guide (h/t @annabutenko) to rollback one of my iPads. No jailbreak needed. https://www.redmondpie.com/downgrade-ios-13.3.1-to-ios-13.3-for-checkra1n-jailbreak-heres-how/

**Comment by lajoli94** [comment]
https://www.tomsguide.com/us/how-to-downgrade-ios,review-6519.html

You download your iOS file from https://ipsw.me/ on your Mac and upload it to the phone in restore mode.

**Comment by juandg** [comment]
I'm having the same issue and was planning to downgrade the device, but I just read that Apple has stopped signing iOS 13.3 so the downgrade is not possible anymore:
https://9to5mac.com/2020/02/12/apple-blocks-ios-13-3-downgrade-jailbreak/

Any suggestions on how to work around this XCode issue or force the downgrade?

**Comment by terry-jp** [comment]
I am experiencing the same issue too and cannot down grade now either due to signing stopped.

Any workaround would be much appreciated!

**Comment by annabutenko** [comment]
> @tusharwgames yes. i am signing WDA with paid company developer account which used by many iOS dev in our company (my account just included into company developer profile). app under test signed with same certificate.

How did you add dev team's ID from a paid account to Signing & Caps section? I added the email address from dev paid account, but Xcode displays it as a Personal Team with a different ID than it is mentioned on the paid account...

**Comment by galaninaa** [comment]
So, Is this Xcode or iOS 13.3 problem?

**Comment by KazuCocoa** [comment]
Yes, could be, so far.

**Comment by Hoang-Minh** [comment]
Is there any update on this issue ? Thanks

**Comment by is** [comment]
> Is there any update on this issue ? Thanks

The problem is related with iOS 13.3.1, Many applications affected.
https://github.com/flutter/flutter/issues/49504

**Comment by mykola-mokhnach** [comment]
Thanks for the mention @is 

It is mentioned there Apple has addressed the issue in iOS 13.4 beta: https://github.com/flutter/flutter/issues/49504#issuecomment-592223977

**Comment by Hoang-Minh** [comment]
Thank you. I have tried the set up below and verify that it works:
- IOS 13.4 beta
- XCode 11 with the supported files for IOS 13.4 from here: [](https://github.com/iGhibli/iOS-DeviceSupport/blob/master/DeviceSupport/13.4.zip)
- Appium 1.6

**Comment by taeyeonssupdate** [comment]
Same problem here.........

**Comment by tusharwgames** [comment]
Closing this issue as it has been resolved for me after updating to 13.4 beta.

Listing all the other workarounds for this issue as mentioned in https://github.com/flutter/flutter/issues/49504#issuecomment-592767041

> Install the beta profile on your test device and install iOS 13.4 beta 3 or higher.
> Wait for iOS 13.4 to be released.
> Use a non-Personal Team provisioning profile. Personal Team provisioning profile says "Personal Team" in the Xcode build settings Runner Target > General > Signing and Capabilities > Team dropdown.
> Run in the simulator.
> Test on a iOS device running 13.3 or lower.

**Comment by jiaxiaozil** [comment]
god！I try everything I can，and find it is a bug at last !!!

**Comment by eliaspardo** [comment]
Thanks to this thread, I also managed to get rid of this issue by upgrading my device to iOS 13.5
