### ISSUE TITLE
Appium desktop — Android native app testing — Issue linked to brings to the next screen by click button

### ISSUE THREAD

**Issue by narbekov** [appium/appium#13936]
## The problem

Can’t go to next screen by clicking on the "Next" button.

## Environment

* appium desktop Version 1.14.0-beta.1
* Android SDK
* Intellij IDEA
* Android Virtual Device Android TV (720p) API 28
* Installed app on emulator
* java version "1.8.0_212"

## Details

Hi guys, I am QA and trying integrate the Appium into my pet-project in the first time, I trying to click on the Next button programmatically using appium library. This button should brings me to the next screen, but nothing happens. Please, take a look at the code, will you have any ideas about why it doesn’t work, Thanks)

**MyCode:** 
[MyCode.txt](https://github.com/appium/appium/files/4192574/MyCode.txt)

**Appium-server-logs:** 
[appium-server-logs.txt](https://github.com/appium/appium/files/4192580/appium-server-logs.txt)

**Elements tree looks:** 
[AppSource.txt](https://github.com/appium/appium/files/4192585/AppSource.txt)

**How element tree looks in UIAutomatorViewer:** 
[dump.txt](https://github.com/appium/appium/files/4192589/dump.txt)

**pom:** 
[pom.txt](https://github.com/appium/appium/files/4192592/pom.txt)

I discussed with familiar developer, and he said that Next button is located in the different activity named AppConfiguratorActivity.
So, when I switch to this activity (AppConfiguratorActivity) and tried click on the Next button, I receive error:
**My new code:** 
[CodeWithAddition.txt](https://github.com/appium/appium/files/4192595/CodeWithAddition.txt)

**appium-server-logs_part2:** 
[appium-server-logs_part2.txt](https://github.com/appium/appium/files/4192597/appium-server-logs_part2.txt)

**Comment by amedvedjev** [comment]
change:
```
MobileElement el1 = (MobileElement) _driver.findElement(MobileBy
                .AndroidUIAutomator("new UiSelector().resourceIdMatches(\".*guidedactions_item_title\").text(\"Next\")"));
```

**Comment by mykola-mokhnach** [comment]
I only observe one Next button in the page source and this one has the `guidedactions_item_title` identifier. Although, I don't observe any log record about this identifier being located anywhere. These long (possible autogenerated) xpath locators are terrible - try to avoid them as much as possible. 

Also, it is possible to enable touches tracked in Android developer settings, so it would be visible where exactly on the screens all actions are being performed.

**Comment by narbekov** [comment]
> I only observe one Next button in the page source and this one has the `guidedactions_item_title` identifier.

 Thanks boys) Tell me please, how did you understand that this is a "guidedactions_item_title" locator for "Next" button?

**Comment by mykola-mokhnach** [comment]
From the page source

**Comment by mykola-mokhnach** [comment]
Closed as not an issue. Please use Appium forum to ask questions

**Comment by narbekov** [comment]
Thanks for your replies!
