### ISSUE TITLE
App freezes with the Appium 1.16 but works with 1.16.0-beta.3

### ISSUE THREAD

**Issue by KS261187** [appium/appium#13932]
## The problem

App freezes with Appium 1.16.0 but works with 1.16.0-beta.3. Which one is the latest Appium version?. Can you please confirm?. We are using app center device farm and they have recently upgraded it to Appium 1.16.0 but we are having issues with the app freezing with the iOS 13.3.1. However when I run locally with the Appium beta which is 1.16.0-beta.3, it works perfectly fine. The release notes says that the Appium 1.16.0 is released on Dec 23, 2019. Do we constantly update the Appium beta?

## Environment

* Appium version (or git revision) that exhibits the issue:1.16.0
* Last Appium version that did not exhibit the issue (if applicable): Appium beta
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Appium@beta is the most recent version and contains the most recent tagged module versions. also different cloud providers might add their own changes on top of the original Appium codebase, so the actual server behaviour there could be different from what one observes with the local deployment. Consider containing their customer support in such case.
