### ISSUE TITLE
Failing to take screenshot via getScreenshot

### ISSUE THREAD

**Issue by tomrenshaw** [appium/appium#13935]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue: **1.16.0**
* Last Appium version that did not exhibit the issue (if applicable): _**Unknown**_
* Desktop OS/version used to run Appium: **Mac Catalina v10.15.2**
* Node.js version (unless using Appium.app|exe): **6.13.4**
* Npm or Yarn package manager: **NPM**
* Mobile platform/version under test: **Android / 9 & 10**
* Real device or emulator/simulator: **Emulator**
* Appium CLI or Appium.app|exe: **I've tried CLI & App, both the same**

## Details

Attempting to Take a Screenshot at specific points. But when the command is sent to Appium, nothing happens and the error message within the gist link below is output. 

## Link to Appium logs

https://gist.github.com/tomrenshaw/451ef89d55c0d7b6fb314ea513a9f65a

## Code To Reproduce Issue [ Good To Have ]

`      File scrFile = ((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);
        FileUtils.copyFile(scrFile, new File("./screenshot.png"));`

**Comment by mykola-mokhnach** [comment]
> [debug] [WD Proxy] Got response with status 200: {"sessionId":"c90297854c429656e877d958c9e23d94","status":21,"value":{"message":"timeout: Timed out receiving message from renderer: 10.000\n  (Session info: chrome=69.0.3497.100)\n  (Driver info: chromedriver=2.44.609545 (c2f88692e98ce7233d2df7c724465ecacfe74df5),platform=Mac OS X 10.15.2 x86_64)"}}

This error is coming from the chromedriver itself and, unfortunately, there is nothing we can do about it on Appium side.
You could try to enable the `nativeWebScreenshot` capability as a workaround

**Comment by tomrenshaw** [comment]
@mykola-mokhnach Enabling nativeWebScreenshot is a viable workaround solution. 
Thank you for getting back to me so quickly.
