### ISSUE TITLE
How could I set up proxy for simulator

### ISSUE THREAD

**Issue by Ripppah** [appium/appium#13931]
## The problem

I am running the my automation behind proxy. So the webapp that I am going to test need proxy to access. I have proxy set up properly on my mac as I am able to access that website on mac. But when I running it on the ios simulator, it's accessing the website, but its javascript/css is not loading at all. I wonder if it's because of the proxy issue.

## Environment

* Appium version: 1.15
* Desktop OS/version: mojav
* Node.js version: 13.6.0
* Mobile platform/version under test: iPhone 10 / ios 12.1

Any idea would be welcome as I have no idea to this.

**Comment by mykola-mokhnach** [comment]
Unfortunately Appium does not support automation via proxy.
Kindly use Appium forum for questions.
