### ISSUE TITLE
Chrome v80 is not starting on Android 10 

### ISSUE THREAD

**Issue by ckurban** [appium/appium#13930]
## The problem

After upgrading my Samsung S9 to v10 which comes with Chrome 80 automatically then chrome is not working on my device. It was working perfectly before upgrading it to  Android v10 

Here is the error : 

```
[0-0] 2020-02-10T16:24:38.549Z WARN webdriver: Request failed due to An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.android.chrome' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: 'com.google.android.apps.chrome.Main' or 'com.android.chrome.com.google.android.apps.chrome.Main' never started. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting
```

## Environment

* Appium version (or git revision) that exhibits the issue: @wdio/appium-service@5.18.2
* Last Appium version that did not exhibit the issue (if applicable): @wdio/appium-service@5.18.2
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe): 10.15.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Samsung S9 v10
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: WebdriverIO Appium Service

## Details

Here is my package.json : 

```
  "dependencies": {
    "@babel/cli": "^7.7.0",
    "@babel/core": "^7.7.2",
    "@babel/preset-env": "^7.7.1",
    "@babel/register": "^7.7.0",
    "@babel/traverse": "^7.7.2",
    "@babel/types": "^7.7.2",
    "@wdio/allure-reporter": "^5.16.16",
    "@wdio/appium-service": "^5.16.5",
    "@wdio/browserstack-service": "^5.16.10",
    "@wdio/cli": "^5.16.6",
    "@wdio/cucumber-framework": "^5.16.6",
    "@wdio/jasmine-framework": "^5.16.5",
    "@wdio/local-runner": "^5.16.6",
    "@wdio/spec-reporter": "^5.16.5",
    "@wdio/sync": "^5.16.5",
    "appium-chromedriver": "^4.18.0",
    "await-to-js": "^2.1.1",
    "axios": "^0.19.2",
    "babel-eslint": "^10.0.2",
    "browserstack-local": "^1.4.2",
    "chai": "^4.2.0",
    "cucumber-tag-expressions": "^1.1.1",
    "deepmerge": "latest",
    "dotenv": "^8.2.0",
    "eslint": "^5.16.0",
    "eslint-config-standard": "^12.0.0",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-node": "^7.0.1",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.1",
    "eslint-plugin-wdio": "^5.12.1",
    "fs": "0.0.1-security",
    "gmail-tester": "1.1.5",
    "googleapis": "^47.0.0",
    "i18n": "^0.8.4",
    "js-base64": "^2.5.1",
    "moment": "^2.24.0",
    "node-fetch": "^2.3.0",
    "node-html-parser": "^1.1.16",
    "qs": "^6.9.1",
    "request-promise": "^4.2.5",
    "wdio-native-app-compare-service": "^1.1.0",
    "wdio-screenshots-cleanup-service": "0.0.7",
    "webdriverio": "^5.16.6",
    "winston": "^3.2.1"
  }
```

## Config To Reproduce Issue

![image](https://user-images.githubusercontent.com/987277/74170288-94f77380-4c24-11ea-952e-27323e2fc6a9.png)

Gist : https://gist.github.com/ckurban/36a710d43d71230f4054b420c6d6b42f

**Comment by imurchie** [comment]
Please turn on Chromedriver console logging (set the `showChromedriverLog` capability to `true`) and provide the Appium server logs as a link to a [gist](https://gist.github.com).

**Comment by ckurban** [comment]
> Please turn on Chromedriver console logging (set the `showChromedriverLog` capability to `true`) and provide the Appium server logs as a link to a [gist](https://gist.github.com).

GIST => https://gist.github.com/ckurban/36a710d43d71230f4054b420c6d6b42f

**Comment by mykola-mokhnach** [comment]
The attached log does not look like an Appium server log

**Comment by ckurban** [comment]
> The attached log does not look like an Appium server log

`    appium: {
        // For options see
        // https://github.com/webdriverio/webdriverio/tree/master/packages/wdio-appium-service
        args: {
            showChromedriverLog:true,
        },
        command: 'appium'
    },
`

**Comment by mykola-mokhnach** [comment]
It looks like you have a custom solution and we cannot help there. Custom solutions require custom advices. Perhaps, hiring a consultant would help.

**Comment by imurchie** [comment]
This is a webdriver.io test. I'm not sure how to make the Appium logs get added to the output, but their forums are supposedly very good.
