### ISSUE TITLE
iOS 13.4: Unable to Start Safari/Hybrid Test Session

### ISSUE THREAD

**Issue by Dan-Maor** [appium/appium#13948]
## The problem
With the latest beta (using appium-remote-debugger 8.2.0) and with the official 1.16.0 release we are unable to create a Safari test session against real devices running the iOS 13.4 beta.

It appears that the web inspector no longer sends the WIRConnectionIdentifierKey as part of the page change dictionary, in which case the remote debugger does not consider it as a valid page change event.

It should be noted that I am able to inspect pages using Safari's native inspector.

## Environment

* Appium version (or git revision) that exhibits the issue: latest 1.16.0 beta from npm
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: MacOS 10.14.6
* Node.js version (unless using Appium.app|exe): N/A
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs
https://gist.github.com/Dan-Maor/052eef6c495f3b440f18736a4e3af6de

**Comment by mykola-mokhnach** [comment]
Thanks for the report @Dan-Maor 
Could you please attach the log with `safariLogAllCommunicationHexDump` cap enabled?

**Comment by Dan-Maor** [comment]
Of course. I've updated the GIST with an additional log containing the hex output.

**Comment by imurchie** [comment]
I will be home tomorrow, with access to a device I can get the beta on.

**Comment by imurchie** [comment]
This happens on sims, too. Seems that the "type" of page has been changed from `WIRTypeWeb` to `WIRTypeWebPage`.

A fix is on the way.

**Comment by imurchie** [comment]
You may also run into the problem noted here: https://github.com/appium/appium-remote-debugger/pull/204

**Comment by imurchie** [comment]
@Dan-Maor If you update so you're using `appium-remote-debugger@8.4.0` you ought to see better results. I still need to run the tests with a real device, but your logs look the same as a sim's logs so it ought to be somewhat the same.

**Comment by imurchie** [comment]
Xcode 11.4 beta 2 works on sims, too.

**Comment by imurchie** [comment]
Our full Safari test suite works with iOS 13.4 real devices now, with the latest Appium beta.
