### ISSUE TITLE
Waiting up to 30000ms for UiAutomator2 to be online  .... Proxying [GET /status] to [GET http://127.0.0.1:8200/wd/hub/status] with no body

### ISSUE THREAD

**Issue by michalD-qa** [appium/appium#13942]
## The problem

When run protractor tests towards appium server, appium is Waiting up to 30000ms for UiAutomator2 to be online but it never happen it gets 404 instead all the time.

[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8200/wd/hub/status] with no body.

When I open the browser manually on the url http://127.0.0.1:8200/wd/hub/status during test execution it shows response:
{"sessionId":"None","value":{"ready":true,"message":"UiAutomator2 Server is ready to accept commands"}}
 
## Environment

* Appium version: 1.16.0
* Node.js: 10.14.1
* Npm version: 6.4.1
* Mobile platform/version under test: Android 9-10
* Emulator and real device: the same problem

## Details

I start Appium  with command:  Appium -a 127.0.0.1
Then start protractor test
protractor protractor.conf.js:

exports.config = {
  seleniumAddress: 'http://localhost:4723/wd/hub',
  capabilities: {
    browserName: 'Chrome',
    platformName: 'Android',
    deviceName: 'emulator-5554',
    automationName: 'UiAutomator2',
    platformVersion: '9'
  },

## Link to Appium logs
https://gist.github.com/michalD-qa/651bad565d5d06f802732805b64756d1

## Link to Logcat logs
https://gist.github.com/michalD-qa/ea196f2db85e2b74e37821d74d066720

**Comment by mykola-mokhnach** [comment]
```
[35m[WD Proxy][39m Got an unexpected response with status 404: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">

[35m[WD Proxy][39m <HTML><HEAD><TITLE>Not Found</TITLE>

[35m[WD Proxy][39m <META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>

[35m[WD Proxy][39m <BODY><h2>Not Found</h2>

[35m[WD Proxy][39m <hr><p>HTTP Error 404. The requested resource is not found.</p>

[35m[WD Proxy][39m </BODY></HTML>

[35m[WD Proxy][39m 
```

It looks like there is some proxy on your machine, which intercepts Appium's request. Make sure it is shut down or run the test on a clean machine.

**Comment by michalD-qa** [comment]
You are right.

I did 2 commands in cmd before running Appium server and it fixed this issue
- set http_proxy=
- set https_proxy=

Thank you @mykola-mokhnach

**Comment by WangGuox1n** [comment]
I hava same error, is this because the proxy setting?

this is my bash_profile

```
# clashX
export https_proxy=http://127.0.0.1:7890
export http_proxy=http://127.0.0.1:7890
export all_proxy=socks5://127.0.0.1:7891

alias setproxy="export https_proxy=http://127.0.0.1:7890;export http_proxy=http://127.0.0.1:7890;export all_proxy=socks5://127.0.0.1:7891;echo \"Set proxy successfully\" "
alias unsetproxy="unset http_proxy;unset https_proxy;unset all_proxy;echo \"Unset proxy successfully\" "
alias ipcn="curl myip.ipip.net"
alias ip="curl ip.sb"
```

but after I unset the proxy, still not working
