### ISSUE TITLE
Error executing adbExec

### ISSUE THREAD

**Issue by ps4523** [appium/appium#13943]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Details
I am new to coding and learning Appium. I have installed an apk HostelWorld on my Android 7.1.1 device. I got the appPackage and appActivity from the adb shell
When I open the app on the emulated device, it works fine. When I try to open it thru Appium I run into issues.

## Code To Reproduce Issue 
    DesiredCapabilities cap = new DesiredCapabilities();
    cap.setCapability("deviceName", "Pixel3Test");
    cap.setCapability("platformName", "Android");
    cap.setCapability("platformVersion", "7.1.1");
    cap.setCapability("appPackage", "com.hostelworld.app");
    cap.setCapability("appActivity", 
    "com.hostelworld.app.feature.common.view.BottomNavBaseActivity");
    //cap.setCapability("appWaitDuration", 3000);
    AndroidDriver<MobileElement> driver = new AndroidDriver<MobileElement>(new 
    URL("http://127.0.0.1:4723/wd/hub"),cap);
 
## Link to Appium logs
https://gist.github.com/ps4523/6dc6cb47b7a053c364d9e9df964c4896.js"

**Comment by mykola-mokhnach** [comment]
> [W3C] Encountered internal error running command: Error: Cannot start the 'com.hostelworld.app' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\*****\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 shell am start -W -n com.hostelworld.app/com.hostelworld.app.feature.common.view.BottomNavBaseActivity -S' exited with code 1'; Stderr: 'java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=com.hostelworld.app/.feature.common.view.BottomNavBaseActivity } from null (pid=7990, uid=2000) not exported from uid 10086


Did you check the link from the error message?

**Comment by ps4523** [comment]
yes I did. Same error that app not found

**Comment by mykola-mokhnach** [comment]
The error is thrown by adb itself and most likely means the app's main activity name is different from the one which is provided. I don't observe any issues there on the server side.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
