### ISSUE TITLE
org.openqa.selenium.UnsupportedCommandException: Method is not implemented

### ISSUE THREAD

**Issue by Anuskur** [appium/appium#13955]
## The problem

When using the getClipboard() method, i am always getting an error as UnsupportedCommandException.
My automationName is UiAutomator2, but still i can see my tests failing.
Can someone please help me in resolving this issue.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.15.1
* Mobile platform/version under test:Android/10
* Real device or emulator/simulator:REAL DEVICE

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
https://gist.github.com/Anuskur/6d5967089b44cfbf3bb58d4d480d1916

## Code To Reproduce Issue [ Good To Have ]

String result =  ((HasClipboard) driver).getClipboard(ClipboardContentType.PLAINTEXT) System.out.println(result);

Capabiliyties used:
caps.setCapability("automationName", "UiAutomator2");

Please do let me know if this the wrong way of using UiAutomator2.

**Comment by mykola-mokhnach** [comment]
The method can currently only be called from native context

**Comment by Anuskur** [comment]
Yes mine is a Native Context

**Comment by mykola-mokhnach** [comment]
it _might_ be if someone would implement such feature

**Comment by Anuskur** [comment]
@mykola-mokhnach If my context is webview context.Does this method work for iOS??

**Comment by mykola-mokhnach** [comment]
On iOS it is impossible to get the content of real device's clipboard due to Apple's security limitations

**Comment by imurchie** [comment]
Can you try the latest Appium version? This seems to be fixed there.

**Comment by Anuskur** [comment]
@imurchie I dont find the new release anywhere, i can still see the new release as 1.15.1. Can you please confirm.

**Comment by mykola-mokhnach** [comment]
You should use NPM to install the server from command line interface.

**Comment by Anuskur** [comment]
@mykola-mokhnach  Thanks, i have installed... One more question..Does this method now works on both NATIVE and WEBVIEW contexts?

**Comment by Anuskur** [comment]
@mykola-mokhnach Its working for me now. Thank you

**Comment by happy1610** [comment]
hi @mykola-mokhnach I face same issue in my machine (WindowOS), pls help, thanks in advance
