### ISSUE TITLE
[iOS] PickerWheelElement.sendKeys(value) doesn't work when value contains a whitespace.

### ISSUE THREAD

**Issue by Jasper11** [appium/appium#13968]
## Environment
* Appium version: 1.15.0
* Desktop OS/version used to run Appium: macOS Mojave, 10.14.6
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: real device

## Details
[iOS] PickerWheelElement.sendKeys(value) doesn't work when value contains a whitespace (e.g value = "Fri 21 Feb").

**Comment by mykola-mokhnach** [comment]
Please report the issue to Apple. Appium simply passes the value to the appropriate XCTest API: https://github.com/appium/WebDriverAgent/blob/212da021fa3ad84ce323156be82158eb3c6f94fa/WebDriverAgentLib/Commands/FBElementCommands.m#L221

Closed as third party issue
