### ISSUE TITLE
Appium: Unable to switch to IOS Webview in Cordova App Developed in Outsystems

### ISSUE THREAD

**Issue by jserra-stratpoint** [appium/appium#13962]
## The problem

To give a brief overview on what I am automating. The product is a hybrid IOS application (Apache Cordova application developed in Outsystems). Trying to automate the said app with Appium in a real device but I have encountered a blocker in the process during switching to Webview.

## Environment

- Appium (1.16.0)
- Desktop OS/version used to run Appium: MAC OS Mojave (10.14.6)
- Appium Version: Appium Desktop Version (1.15.1)
- NPM or Yarn package manager: NPM
- Mobile platform/version under test: IOS (12.2)

- Real device or emulator/simulator: Real Device
- Appium CLI or Appium.app|exe: Appium app

## Details

- Below is the Java Code Snippet which switches native to Webview.

```java
public void switchToWebView() {
	Set<String> availableContexts = driver.getContextHandles();
	System.out.println("Total No of Context Found After we reach to WebView = " + availableContexts.size());
	for (String context : availableContexts) {
		if (context.contains("WEBVIEW")) {
			System.out.println("Context Name is " + context);
			driver.context(context);
			break;
		}
	}
}
```

- The above code outputted the following in console and found a WebView in the application

```
[RemoteTestNG] detected TestNG version 6.14.3
Feb 20, 2020 11:27:41 AM io.appium.java_client.remote.AppiumCommandExecutor$1 lambda$0
INFO: Detected dialect: W3C
Total No of Context Found After we reach to WebView = 2
Context Name is WEBVIEW_1596.2
```

- As for the full logs see uploaded gist link [Appium Logs Gist](https://gist.github.com/jserra-stratpoint/91e542d14684b720c5b09cc44f365940)

**Comment by mykola-mokhnach** [comment]
Does it work with appium@beta?

**Comment by OleksiyKlimov** [comment]
Have the same problem with app on simulator, tried last release appium and on last 1.16.0-beta.3, tried to use ""safariGarbageCollect", true" in capabilities. And still can't normal switch contexts - from time ti time it can switch it and in other case no - just randomly.

**Comment by jserra-stratpoint** [comment]
> Does it work with appium@beta?

@mykola-mokhnach tried it on appium 1.16.0-beta.3, still no luck got the same result after switching to webview

**Comment by mykola-mokhnach** [comment]
cc @imurchie

**Comment by imurchie** [comment]
@jserra-stratpoint I am concerned about some of the logs here, which I find confusing.

I've updated things to better display the errors. Can you update the beta again so that you have `appium-remote-debugger@8.5.0`, and repost the logs (the full logs would be great, including those from a previous run if they happen one after the other)?

**Comment by jserra-stratpoint** [comment]
Hi @imurchie 

see this gist for the appium logs with the appium-remote-debugger@8.5.0

[gist link](https://gist.github.com/jserra-stratpoint/0f8c45de762b9b2e3e9006815e77b34b)

**Comment by mykola-mokhnach** [comment]
Are you sure the dist has been updated to beta properly. In the log I can observe:

> [info] [35m[Appium][39m Welcome to Appium v1.15.1

**Comment by imurchie** [comment]
Also
```
[info] [RemoteDebugger] Remote Debugger version 5.7.0
```

**Comment by pmangal78** [comment]
I am also having the same issue with the switch to Webview and don't see any solution yet. Does anyone have any solution for it?

**Comment by imurchie** [comment]
@pmangal78 Is this with the latest beta of Appium? There have been significant fixes to support.

**Comment by pmangal78** [comment]
We are using v1.16.0 and still seeing the issue.

**Comment by imurchie** [comment]
Please at least _try_ it on the latest beta of Appium (`npm uninstall appium && npm install appium@beta`).

**Comment by pmangal78** [comment]
we tried this solution as well, but it is unable to get the context of the Webview page and failing.

**Comment by mykola-mokhnach** [comment]
> we tried this solution as well, but it is unable to get the context of the Webview page and failing.

Unfortunately there is no way to help there without detailed server logs

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by jserra-stratpoint** [comment]
Sorry for the late reply, was able to switch to Webview now, but now encountered a new issue in element interactions. 

was able to find the element and click but no action was reflected on the device

see the logs for details [appium logs](https://gist.github.com/jserra-stratpoint/fc99ab8da32f09f991b5838751657b4b)

**Comment by mykola-mokhnach** [comment]
Consider describing a separate issue for the newly observed behaviour. Also check https://appiumpro.com/editions/36 regrading the click
