### ISSUE TITLE
Wrong windows size for iPhone 11

### ISSUE THREAD

**Issue by yusunan** [appium/appium#13964]
## The problem
In some conditions we have to click by coordinates,And from one device to another device, We should use the window size to calculated coordinates.
But in iPhone 11, Use "driver.manage().window().getSize()" to get the window size。
It will return width = 375, height = 812.
This is not the correct  size，We can get the mark size from Apple (width = 828, height = 1792),And the developer size should be width = 414, height = 896.
I'm not sure it's a issue about appium,But I would like to know how does the driver set this size for different devices.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* WebDriver version:java-client-7.3.0
* Selenium:selenium-remote-driver-4.0.0-
* Mobile platform/version under test: iPhone 11,iOS 13.1.3
* Real device or emulator/simulator:Real device

**Comment by mykola-mokhnach** [comment]
the window size is the size of the application's frame itself without the toolbar and other additional system areas: https://github.com/appium/WebDriverAgent/blob/212da021fa3ad84ce323156be82158eb3c6f94fa/WebDriverAgentLib/Commands/FBElementCommands.m#L556

**Comment by yusunan** [comment]
@mykola-mokhnach Thanks for reply,And by this API, I can make sure this is a issue in APP.
Thanks and closed
