### ISSUE TITLE
Trying to transfer a file to a remote WindowsDriver node

### ISSUE THREAD

**Issue by swooqy** [appium/appium#13960]
@harshit2 the way to accomplish this is to use `pushFile` to get a file into the device's library, then automate the UI of the app when it's requesting a file upload. i.e., do it the way a user would do it.

_Originally posted by @jlipps in https://github.com/appium/appium/issues/8719#issuecomment-318493104_

pushFile option doesn't exist for WindowsDriver and LocalFileDetector option isn't working either. Is there any possible solution to this?

**Comment by mykola-mokhnach** [comment]
Appium team does not own the Windows driver. Consider asking your question at Appium forum or at https://github.com/microsoft/WinAppDriver
