### ISSUE TITLE
Error forwarding the new session Empty pool of VM for setup Capabilities

### ISSUE THREAD

**Issue by Prashanth63** [appium/appium#13961]
<img width="1280" alt="Screenshot 2020-02-19 at 7 15 03 PM" src="https://user-images.githubusercontent.com/34087091/74840812-a5f36380-534d-11ea-8d4d-8267b2364dd0.png">

Appium desktop version: v1.15.1
node version: v10.15.3
Facing this issue while trying to inspect the element from Appium desktop server

**Comment by mykola-mokhnach** [comment]
Please provide the full server log

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by Prashanth63** [comment]
<img width="651" alt="Screenshot 2020-02-25 at 11 10 13 AM" src="https://user-images.githubusercontent.com/34087091/75218164-67cbc900-57bf-11ea-93dd-3c97beea3553.png">

1. opened Appium desktop server
2.Start server v1.15.1
3. Tapped on the search icon
4. Tapped on Saved capability sets
5. Start Session

got this error: https://user-images.githubusercontent.com/34087091/74840812-a5f36380-534d-11ea-8d4d-8267b2364dd0.png

**Comment by mykola-mokhnach** [comment]
@Prashanth63 Such error is coming from your cloud provider. Consider contacting their customer support

**Comment by Prashanth63** [comment]
@mykola-mokhnach We are not having any cloud provider.
We just now setup the iOS automation to our project.
We can able to run the automation script in the same device but when we try to inspect the element from Appium desktop server we are getting this issue. 
-We tried changing different iPhone
and done all the setup over again it is not working.  

Kindly help us!

**Comment by mykola-mokhnach** [comment]
https://github.com/search?q=org%3Aappium+%22empty+pool+of%22&type=Issues
