### ISSUE TITLE
Appium v 1.15.0 doesn't open any URL on mobile safari on real device 

### ISSUE THREAD

**Issue by annabutenko** [appium/appium#13975]
## The problem

Appium doesn't open any URL in mobile Safari 13.3. Previously it was opening all URLs with no issues, but now I don't know what goes wrong. 
 
## Environment

* Appium version (or git revision) that exhibits the issue: v1.15.0
* Desktop OS/version used to run Appium: macOS Catalina v 10.15.3
* Node.js version (unless using Appium.app|exe): v12.6.0
* Npm package manager: 6.13.7
* Mobile platform/version under test: iOS 13.3
* Real device: iPhone X
* Appium CLI: v1.15.0

## Link to Appium logs

https://gist.github.com/annabutenko/f158326533ae1c2d2b415307d0443db5

## Code To Reproduce Issue [ Good To Have ]
I have tests written in Page Object Pattern.

import io.appium.java_client.ios.IOSDriver;
import io.appium.java_client.remote.MobileCapabilityType;
import org.junit.After;
import org.junit.Before;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;
import pages.HomePage;
import java.net.MalformedURLException;
import java.net.URL;

public class TestBase {

    private static IOSDriver driver;
    protected static HomePage homePage;
    protected static VisualTest visualTest;

    @Before
    public void setUpAppium() throws MalformedURLException {
        URL url = new URL("http://127.0.0.1:4723/wd/hub");
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
        capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "13.3");
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone X");
        capabilities.setCapability("xcodeSigningId", "iPhone Developer");
        capabilities.setCapability("udid", "583b1972dddb94ab17c331f2XXXXXXXXXX");
        capabilities.setCapability("updatedWDABundleId","com.qtf.WebDriverAgentRunner");
        capabilities.setCapability("bundleId","com.apple.mobilesafari");
        capabilities.setCapability("useNewWDA", false);
        capabilities.setCapability("newCommandTimeout", 10000);
        capabilities.setCapability("showXcodeLog", true);
        capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");
        capabilities.setCapability("startIWDP", true);

        driver = new IOSDriver(url, capabilities);

        homePage = new HomePage(driver);
        visualTest = new VisualTest(driver);
    }

 @After
    public void closeWebApp(){
        switchToWebContext();
        driver.quit();
    }

    @Test
    public void openWebApp() {
        // Navigate to google.com
        driver.get("https://www.google.com");
    }
}

Will appreciate your help here!

**Comment by mykola-mokhnach** [comment]
Please try appium@beta

**Comment by annabutenko24** [comment]
> Please try appium@beta

Hi :) I try with beta and the behaviour is same (appium doesn't open the url) but with a new failure:
```
[Xcode]     t =     5.94s Activate Siri with voice recognition text: Open {https://vatom.com/2.1.64/#/autologin?email=st@yopmail.com&otp=1111}
[Xcode] 
[Xcode] 2020-02-24 10:41:18.840889+0100 WebDriverAgentRunner-Runner[1517:796126] Enqueue Failure: Timed out waiting for Siri to activate /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgentRunner/UITestingUITests.m 38 1

```

**Comment by annabutenko** [comment]
> Please try appium@beta

Hi :) I try with beta and the behaviour is same (appium doesn't open the url) but with a new failure:

```
[Xcode]     t =     5.94s Activate Siri with voice recognition text: Open {https://vatom.com/2.1.64/#/autologin?email=st@yopmail.com&otp=1111}
[Xcode] 
[Xcode] 2020-02-24 10:41:18.840889+0100 WebDriverAgentRunner-Runner[1517:796126] Enqueue Failure: Timed out waiting for Siri to activate /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgentRunner/UITestingUITests.m 38 1
```

Is it an issue with WDA itself?

**Comment by mykola-mokhnach** [comment]
This is the issue with XCTest. Siri service is used as an ugly workaround for a known [bug](https://github.com/appium/WebDriverAgent/blob/212da021fa3ad84ce323156be82158eb3c6f94fa/WebDriverAgentLib/Categories/XCUIDevice%2BFBHelpers.m#L211) and does not always work. 
A possible workaround might be to start Safari in the test and type the given link there.
Closed as third party issue.
