### ISSUE TITLE
Remote Apps Cache can cause INSTALL_FAILED_INSUFFICIENT_STORAGE error

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#13970]
## The problem

* When remoteAppsCache is set (above 0) the order of actions for installing an app are
  * Cache the apk in device storage
  * Install the apk from device storage `adb pm install <sdcard_path_to_apk>`
* When remoteAppsCache is not set (<= 0) the apk is installed from filepath using `adb install <file_path_to_apk>`
* For reference: https://github.com/appium/appium-adb/blob/413bb259d29f28481a216d15ddca0b065f31abcc/lib/tools/apk-utils.js#L447
* The problem is that if the storage is limited, this can cause `INSTALL_FAILED_INSUFFICIENT_STORAGE` error, because it's storing the APK in two places
* I recommend that we keep the behaviour as it is, except that if we get the `INSTALL_FAILED_INSUFFICIENT_STORAGE` error during app installation then we:
  * Catch the error and log a message
  * Delete the apk from device storage
  * Fall back to installing using `adb install <file_path_to_apk>`

NOTE: I'll assign this to myself for now, I may have time to do this on my own.

**Comment by mykola-mokhnach** [comment]
> The problem is that if the storage is limited, this can cause INSTALL_FAILED_INSUFFICIENT_STORAGE error, because it's storing the APK in two places

What are these two places? Normally, in order to install an app adb must anyway upload it to the device first: https://android.googlesource.com/platform/sdk/+/eclair-sholes-release2/ddms/libs/ddmlib/src/com/android/ddmlib/Device.java#426

**Comment by mykola-mokhnach** [comment]
what we could do is to clear enough older cache items in order to fit the package (actually, the amount of free space should be at least twice as bigger as the app package)

**Comment by dpgraham** [comment]
@mykola-mokhnach this was happening in Sauce Labs VM's. We couldn't install apps > 100 mb, and then when we fell back to `adb install ...` (by setting `remoteAppsCache=0`) it was working again. Since the VM's are fresh, there's nothing to clear out.

Not sure why though, looking at the code you sent me, it does seem like it's doing it the same way as you did it on JS. 👀

**Comment by dpgraham** [comment]
https://android.googlesource.com/platform/tools/base/+/master/ddmlib/src/main/java/com/android/ddmlib/Device.java#1147

^ maybe it streams the apk from `/data/local/tmp`.

**Comment by mykola-mokhnach** [comment]
The patch has been merged to appium@beta

**Comment by wulfihm** [comment]
Hi, I believe there needs to be another folder/file that needs to be deleted.
See https://stackoverflow.com/questions/4709137/solution-to-install-failed-insufficient-storage-error-on-android

This is the only thing that helped me with my issue.
Everytime I quit the driver I am deleting all APKs of my package in /data/app/

```
       List<String> args = Arrays.asList(
                "-rf",
                " /data/app/[package_name]-*"
        );
        Map<String, Object> cmd = ImmutableMap.of(
                "command", "rm",
                "args", args
        );
        this.executeScript("mobile: shell", cmd);
```
