### ISSUE TITLE
Appium v1.16.0-Need Info: Any way to find which browser is opened?

### ISSUE THREAD

**Issue by Anuskur** [appium/appium#13977]
## The problem

Currently, in my application , i need to click on a link which will redirect to chromebrowser for Android and Safari for IOS.
Is there any way to identify using Appium which browser has been opened?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0
* Node.js version (unless using Appium.app|exe):v12.14.0
* Mobile platform/version under test:Android/IOS
* Real device or emulator/simulator:Real Device

**Comment by mykola-mokhnach** [comment]
Appium has an endpoint, which allows to retrieve the current state for the given application bundle id (queryAppState) and to detect whether it is running on foreground.

Kindly use Appium forum for questions
