### ISSUE TITLE
disconnected: unable to connect to renderer when attempting to interact with elements in a window during a parallel test.

### ISSUE THREAD

**Issue by rubinshteyn89** [appium/appium#13972]
## The problem
When running a parallel test against multiple(in my case 3+) devices/emulators where there are webviews with multiple windows, some of the devices/emulators will error due to "disconnected: unable to connect to renderer" error when attempting to interact with elements within the windows.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0
* Last Appium version that did not exhibit the issue (if applicable): Have not found one.
* Node.js version (unless using Appium.app|exe): v12.11.1
* Npm or Yarn package manager: 6.11.3
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real Device and Emulator
* Appium CLI or Appium.app|exe: CLI

## Details
What I am experiencing is when I run a parallel test with 3 or more Android devices or emulators against my application which has a WebView with multiple Windows in it, 2 of the 3 devices/emulators seems to error out when attempting to switch to the web context with the error "disconnected: unable to connect to renderer" when attempting to interact with elements within the windows.

## Link to Appium logs
https://gist.github.com/rubinshteyn89/376be16287ff6cb82971287925519fd2

**Comment by mykola-mokhnach** [comment]
The error itself is coming from chromedriver. I don't there's anything that could be done on Appium side.

**Comment by jlipps** [comment]
hmm, this reminds me of something i thought we made a capability for.

**Comment by rubinshteyn89** [comment]
@mykola-mokhnach, @jlipps so do I need to report this issue somewhere else?

**Comment by rubinshteyn89** [comment]
@mykola-mokhnach ok I logged defect to chromedriver team: https://bugs.chromium.org/p/chromedriver/issues/detail?id=3366

**Comment by mykola-mokhnach** [comment]
Closed as third party issue.
