### ISSUE TITLE
"Special characters" issue with Actions send_keys in python 3.7

### ISSUE THREAD

**Issue by gauthierbuttez** [appium/appium#13976]
Hi,

I posted my issue on forum and stackoverflow but I didn't get answers.
I am sorry to bother you here, but my development is completly block because of this Appium error.

I am trying to send a text in an input field of an application.
The text is in French with special characters “éèà…etc…”

My code managed to type character by character, one by one, but when it arrives to a special character with accent “é”, it bugs! Here is error message:

Encountered internal error running command: io.appium.uiautomator2.common.exceptions.InvalidArgumentException: KeyCharacterMap.getEvents is unable to synthesize KeyEvent sequence out of ‘233’ key code. Consider applying a patch to UiAutomator2 server code or try to synthesize the necessary key event(s) for it manually

I read the doc and forum and I added this capability:
desired_caps['unicodeKeyboard'] ='true'

But it didn’t change anything. I still have same issue.

I’ve seen many people had this issue but noone never posted a solution.

Can anyone help please?

**Comment by mykola-mokhnach** [comment]
Unfortunately there's currently no good solution for that.

See https://github.com/appium/appium/issues/13154 for more details.
