### ISSUE TITLE
UIAutomator2 setValue bug right after clear

### ISSUE THREAD

**Issue by kkb912002** [appium/appium#13973]
## The problem

setValue command immediately after clear makes malfunction(text double pushed) sometimes.

## Environment

* Appium version (or git revision) that exhibits the issue:
  * appium: ?
  * appium-uiautomator2-driver: 1.37.2
  * appium-uiautomator2-server: 4.3.0 (4.3.0 apk installed to device)
* Desktop OS/version used to run Appium
  * Windows 10
* Node.js version (unless using Appium.app|exe)
  * 10.x
* Mobile platform/version under test:
  * Android/9(maybe) or 10
* Real device or emulator/simulator:
  * Real device(Samsung Galaxy Note10+)
* Appium CLI or Appium.app|exe:
  * CLI

## Details

Python script
```python3
elem.clear()
elem.set_value('abcd@efgh.com')
```
After the code executed, The field includes `abcd@efgh.comabcd@efgh.com` when malfunction occurred.(`abcd@efgh.com` is placed on the field before clear.)
The clear command worked properly. But set_value command pushed the text 2 times.
I checked in recorded screen(video, I'm sorry I cannot share the video because of security).
The malfunction occurred 2 times in 500 tests.

## Link to Appium logs

https://gist.github.com/kkb912002/df28eb61e02ec32d27e83affb6a3b4b7

Thanks.

**Comment by mykola-mokhnach** [comment]
Please try appium@beta

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by kkb912002** [comment]
Not occurred in 5000 tests.
thanks.
