### ISSUE TITLE
Can't set chrome experimental flag by appium

### ISSUE THREAD

**Issue by DStryuts** [appium/appium#13974]
## The problem

I am trying to set flag “android-setup-search-engine” to disable chrome start screen on real device.
Found chrome driver solution here https://groups.google.com/d/msg/chromedriver-users/cI8hj7eihRo/At6OQV4bAwAJ
I set up chrome options and capabilities this way:
`              ChromeOptions chromeOptions = new ChromeOptions();
                HashMap<String, Object> chromeLocalStatePrefs = new HashMap<String, Object>();
                List<String> experimentalFlags = new ArrayList<String>();
                experimentalFlags.add("android-setup-search-engine@0");
                chromeLocalStatePrefs.put("browser.enabled_labs_experiments", experimentalFlags);
                chromeOptions.setExperimentalOption("localState", chromeLocalStatePrefs);
                capabilities.setCapability(ChromeOptions.CAPABILITY, chromeOptions);
                capabilities.setCapability(PLATFORM_NAME, "Android");
                capabilities.setCapability(PLATFORM_VERSION, "9.0");
                capabilities.setCapability(DEVICE_NAME, "asus ZB602KL");
                capabilities.setCapability(BROWSER_NAME, "Chrome");
                capabilities.setCapability(AUTOMATION_NAME, "Appium");`
and started appium driver
`driver = new AppiumDriver(url, capabilities);`
but webdriver started with error
`invalid argument: cannot parse capability: goog:chromeOptions
from invalid argument: unrecognized chrome option: localState`
But according to https://sites.google.com/a/chromium.org/chromedriver/capabilities localState is a part of chromeOptions.

Did I do something wrong or it doesn't work in appium?
## Environment

* Appium version (or git revision) that exhibits the issue:
v1.16.0
* Desktop OS/version used to run Appium:
macOS 10.15.3
* Node.js version (unless using Appium.app|exe):
v10.9.0
* Npm or Yarn package manager:
Npm
* Mobile platform/version under test:
Android 9.0
* Real device or emulator/simulator:
Real device, Asus ZB602KL
* Appium CLI or Appium.app|exe:
CLI

## Link to Appium logs

https://gist.github.com/DStryuts/865ab185222eb3d6a39d5c80905ce5c5

**Comment by mykola-mokhnach** [comment]
Unfortunately not all options which are supposed to work for Desktop Chrome would work for the mobile one. Consider asking that question at Chromedriver forums

**Comment by DStryuts** [comment]
Thanks for the answer.
