### ISSUE TITLE
Device iOS auto restart

### ISSUE THREAD

**Issue by VTDuyen1** [appium/appium#13988]
## The problem

When I was running the test for about 1 hour, my device kept restarting automatically.

I tried update software, reset all settings, remove sim card, hard reset, restore iphone use iTunes... but it all didn't work, the device still automatically rebooted while running the test.

The appium log is nothing special except a notification of device disconnection.
## Environment

* Appium version : 1.15.1
* Desktop OS/version used to run Appium: 1.15.1
* Node.js version (unless using Appium.app|exe): v12.1.0
* Mobile platform/version under test: 12.4.4
* Real device or emulator/simulator: Real device (iPhone 6+)
* Appium CLI or Appium.app|exe: CLI and Appium.app

**Comment by mykola-mokhnach** [comment]
Try to use another device for automated testing. Perhaps, this one has defects

**Comment by VTDuyen1** [comment]
Hi @mykola-mokhnach 
I have tried 5 different devices, but all have the same problem. Some devices happen within 1 hour, others can run for 4 hours continuously even for a few days, after which they will reboot automatically.

**Comment by mykola-mokhnach** [comment]
Appium does not do anything special to cause the reboot. I'd try to investigate the device logs. Perhaps, iOS does log what is happening there

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
