### ISSUE TITLE
SendKeys To Slider Does Not Reach End Of Slider

### ISSUE THREAD

**Issue by ajschwieterman** [appium/appium#13980]
## The problem

I'm using _element.setValue()_ to set the value of a XCUIElementTypeSlider element.  When I set the value of the slider to 0, the slider is set at 1%, and when I set the value of the slider to 1, the slider is set at 98%.  I would expect the 

## Environment

* Appium version (or git revision) that exhibits the issue: v1.16.0
* Desktop OS/version used to run Appium: Mac OS Catalina v10.15.3
* Node.js version (unless using Appium.app|exe): v13.7.0
* Npm or Yarn package manager: v6.13.7
* Mobile platform/version under test: iOS v13.3.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

https://gist.github.com/ajschwieterman/4fea6e37a36cea0f6bcf69f0e3707755

## Code To Reproduce Issue [ Good To Have ]

element.setValue("0");
element.setValue("1");

**Comment by mykola-mokhnach** [comment]
Appium does not do any changes to the original slider via, it is passed directly to XCTest: https://github.com/appium/WebDriverAgent/blob/212da021fa3ad84ce323156be82158eb3c6f94fa/WebDriverAgentLib/Commands/FBElementCommands.m#L230

Consider reporting the issue to Apple if the slider is not changed the way it is expected to be changed.

**Comment by mykola-mokhnach** [comment]
Also:

> The adjustment is a “best effort” to move the indicator to the desired position; absolute fidelity is not guaranteed.

https://developer.apple.com/documentation/xctest/xcuielement/1501022-adjusttonormalizedsliderposition?language=objc
