### ISSUE TITLE
Appium not able to automate webview within iOS native app

### ISSUE THREAD

**Issue by parikhparth23** [appium/appium#13982]
**Appium UI version**: Version 1.15.1 (1.15.1.20191013.2)

**Device**: iPhone 11

**OS**: 13.3.1

Appium inspector just try to load the screen but does not show anything.

My **code** to change to web view.

    Set<String> contextNames = driver.getContextHandles();
    System.out.println(contextNames.size());
    for (String contextName : contextNames) {
           System.out.println(contextName);
     }
    driver.context((String) contextNames.toArray()[1]);
    driver.findElement(By.name(getPaypalWebView())).click();

**Appium logs**:

> [HTTP] <-- POST /wd/hub/session/bff6b3f2-3256-419a-92c5-2b03e51ae2f3/element 200 701 ms - 137
[HTTP] 
[HTTP] --> POST /wd/hub/session/bff6b3f2-3256-419a-92c5-2b03e51ae2f3/element/F6020000-0000-0000-5A26-000000000000/click
[HTTP] {"id":"F6020000-0000-0000-5A26-000000000000"}
[W3C (bff6b3f2)] Driver proxy active, passing request on via HTTP proxy
[XCUITest] Executing command 'proxyReqRes'
[WD Proxy] Matched '/wd/hub/session/bff6b3f2-3256-419a-92c5-2b03e51ae2f3/element/F6020000-0000-0000-5A26-000000000000/click' to command name 'click'
[WD Proxy] Proxying [POST /wd/hub/session/bff6b3f2-3256-419a-92c5-2b03e51ae2f3/element/F6020000-0000-0000-5A26-000000000000/click] to [POST http://localhost:8100/session/36EFC521-36E8-48E4-9A3B-D36548C388AA/element/F6020000-0000-0000-5A26-000000000000/click] with body: {"id":"F6020000-0000-0000-5A26-000000000000"}
[WD Proxy] Got response with status 200: {"value":null,"sessionId":"36EFC521-36E8-48E4-9A3B-D36548C388AA"}
[WD Proxy] Replacing sessionId 36EFC521-36E8-48E4-9A3B-D36548C388AA with bff6b3f2-3256-419a-92c5-2b03e51ae2f3
[HTTP] <-- POST /wd/hub/session/bff6b3f2-3256-419a-92c5-2b03e51ae2f3/element/F6020000-0000-0000-5A26-000000000000/click 200 983 ms - 76
[HTTP] 
[HTTP] --> GET /wd/hub/session/bff6b3f2-3256-419a-92c5-2b03e51ae2f3/contexts
[HTTP] {}
[W3C (bff6b3f2)] Calling AppiumDriver.getContexts() with args: ["bff6b3f2-3256-419a-92c5-2b03e51ae2f3"]
[XCUITest] Executing command 'getContexts'
[iOS] Getting list of available contexts
[iOS] Retrieving contexts and views
[XCUITest] Selecting by url: false 
[RemoteDebugger] Remote Debugger version 5.7.0
[RemoteDebugger] useNewSafari --> false
[RemoteDebugger] Checking which communication style to use (non-Safari on platform version '13.3')
[RemoteDebugger] Platform version equal or higher than '12.2': true
[RemoteDebugger] Setting communication protocol: using full Web Inspector protocol communication
[RemoteDebugger] Sending connection key request
[RemoteDebugger] Sending '_rpc_reportIdentifier:' message (id: 0)
[iProxy@00008...] Error: read ECONNRESET
[iProxy@00008...]     at TCP.onread (net.js:657:25)
[ffmpeg] Exiting normally, received signal 2.
[ffmpeg] 
[DevCon Factory] Releasing connections for 00008030-001A50AA2150802E device on 9100 port number
[DevCon Factory] Found cached connections to release: ["00008030-001A50AA2150802E:9100"]
[DevCon Factory] Releasing the listener for '00008030-001A50AA2150802E:9100'
[DevCon Factory] Cached connections count: 1
[HTTP] <-- GET /wd/hub/session/bff6b3f2-3256-419a-92c5-2b03e51ae2f3/contexts - - ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/bff6b3f2-3256-419a-92c5-2b03e51ae2f3/contexts
[HTTP] {}
[W3C (bff6b3f2)] Calling AppiumDriver.getContexts() with args: ["bff6b3f2-3256-419a-92c5-2b03e51ae2f3"]
[XCUITest] Executing command 'getContexts'

![IMG_473DCD794E7A-1](https://user-images.githubusercontent.com/10181201/75100049-a4a87d80-557d-11ea-8439-db9380d0cf28.jpeg)

**Comment by parikhparth23** [comment]
@KazuCocoa do you have any idea?

**Comment by KazuCocoa** [comment]
Please try the latest appium@beta out

**Comment by parikhparth23** [comment]
ui or command line?

**Comment by KazuCocoa** [comment]
CLI which is available by `npm install -g appium@beta`

**Comment by parikhparth23** [comment]
let me try...thanks @KazuCocoa

**Comment by parikhparth23** [comment]
when i run through terminal it uninstall the web driver agent and throws this error:

> WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file. The file doesn’t exist. (Underlying error: The operation couldn’t be completed. No such file or directory)))

**Comment by KazuCocoa** [comment]
Could you share the full log as GIST?
Possible duplicate of https://github.com/appium/appium/issues/13927

**Comment by parikhparth23** [comment]
sorry @KazuCocoa  for late reply.
here is the gist: https://gist.github.com/parikhparth23/e58488cdc39f209f1d4c21531f982182

**Comment by mykola-mokhnach** [comment]
> [Xcode] 	Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the Signing & Capabilities editor.

There's a problem with WDA signing. Please make sure the bundle is signed properly with a development signature and can be built from the command line

**Comment by mykola-mokhnach** [comment]
Might be related to https://github.com/appium/appium/issues/13927

**Comment by parikhparth23** [comment]
@mykola-mokhnach bundle is signed properly when i run through the mac application.
it does not work with appium@beta command line

**Comment by parikhparth23** [comment]
@mykola-mokhnach  i was able to build it....let me run and try again

**Comment by parikhparth23** [comment]
@mykola-mokhnach @KazuCocoa  here is the gist https://gist.github.com/parikhparth23/f82b006765f9c72662aa60e37d9f14a9

it fails when it opens the webview ...same code no change

**Comment by parikhparth23** [comment]
from the console log looks like it is failing at this line:
            driver.context((String) contextNames.toArray()[1]);

**Comment by mykola-mokhnach** [comment]
> [debug] [W3C (911745ce)] Calling AppiumDriver.getContexts() with args: ["911745ce-6340-492c-8b44-5b46d8a87184"]
> [debug] [XCUITest] Executing command 'getContexts'
> [debug] [XCUITest] Getting list of available contexts
> [debug] [iOS] Retrieving contexts and views
> [debug] [XCUITest] Selecting by url: false 
> [RemoteDebugger] Remote Debugger version 8.5.0
> [debug] [RemoteDebugger] useNewSafari --> false
> [debug] [RemoteDebugger] Checking which communication style to use (non-Safari on platform version '13.3')
> [debug] [RemoteDebugger] Platform version equal or higher than '12.2': true
> [RemoteDebugger] Setting communication protocol: using full Web Inspector protocol communication
> [debug] [RemoteDebugger] Sending connection key request
> [debug] [RemoteDebugger] Sending '_rpc_reportIdentifier:' message (id: 0): 'setConnectionKey'
> [debug] [RemoteDebugger] Sending to Web Inspector took 6ms
> [debug] [RemoteDebugger] Sending connection key request
> [debug] [RemoteDebugger] Sending '_rpc_reportIdentifier:' message (id: 1): 'setConnectionKey'
> [debug] [RemoteDebugger] Sending to Web Inspector took 5ms
> [debug] [RemoteDebugger] Selecting application
> [debug] [RemoteDebugger] No applications currently connected.
> [debug] [XCUITest] No web frames found.
> [debug] [W3C (911745ce)] Responding to client with driver.getContexts() result: ["NATIVE_APP"]

Are you sure the web view is available for debugging in general? Is it visible in the Safari remote debugger?

**Comment by imurchie** [comment]
This is possibly a timing issue. By default Appium does not wait for a webview to be visible before returning that there are none, since in the negative case this would wait the maximum time.

With the beta, you can try setting the `webviewConnectTimeout` capability to some number larger than `0` (the default), which will wait for that amount of milliseconds for a webview to be reported by the Web Inspector.

Alternatively, you can try polling from the client side or a little bit.

**Comment by parikhparth23** [comment]
@imurchie correct ... sorry for late reply but yes i fixed it by adding "wait for"
