### ISSUE TITLE
Appium server cannot connect to emulators/devices running Android R (11.0)

### ISSUE THREAD

**Issue by arditshala** [appium/appium#13983]
## The problem
I am trying to connect appium with android devices that are running android R.

At first, I tried to set the ‘platformVersion’ capability to '11.0', but then, after I tried to start the session, an error was thrown that no device with 'platformVersion'='11.0' is connected.

However, after I executed the following command:
`~$ adb -s emulator-5556 shell getprop ro.build.version.release`
`~$ R`

But when I try to use 'R' as a value for ‘platformVersion’ key, this error is thrown by the server:
`An unknown server-side error occurred while processing the command. Original error: The provided platform version value 'null' cannot be coerced to a valid version number`

How can I overcome this issue and be able to connect appium with android devices running Android 11 R ?

## Environment
* Appium version 1.16.0
* Last Appium version that did not exhibit the issue (if applicable):
* OS/version used to run Appium: MacOS Catalina 10.15.2
* Node.js version (unless using Appium.app|exe): 12.14.1
* Npm or Yarn package manager: 6.13.6
* Mobile platform/version under test: Android R (11.0)
* Real device or emulator/simulator: Both
* Appium CLI or Appium.app|exe: Both

**Comment by mykola-mokhnach** [comment]
Please attach the full server log

**Comment by arditshala** [comment]
@mykola-mokhnach  Here are the logs when I tried with 'R' and '11.0'. [android-R-appium-logs.txt](https://github.com/appium/appium/files/4244386/android-R-appium-logs.txt)

**Comment by KazuCocoa** [comment]
When Android Q, the preview (and beta) version returned `ro.build.version.release` as the code name like `Q`. It returned `10` after the beta. So, I assume R also will be the same.
(We should decide if Appium will have a workaround for `adb -s emulator-5556 shell getprop ro.build.version.release` is `R` case during the preview/beta version). `adb -s emulator-5556 shell getprop ro.build.version.adk` is also `29` which is Android Q on Android R preview host.

As a workaround, you can specify `udid` like `emulator-5556` in the capability. (I could establish a connection against an Android R preview emulator with `udid`)

---

btw, we'd recommend you to set `uiautomator2` to `automationName` as the attached log

**Comment by KazuCocoa** [comment]
a side note:

I got below error when the build tool version was 30 in Java 1.8 runtime.

```
[ADB] Exception in thread "main" java.lang.UnsupportedClassVersionError: com/android/apksigner/ApkSignerTool has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

Then, I added `buildToolsVersion: '29'` capability and chose build version 29. Perhaps the build tool 30 will require Java 1.9 env.

**Comment by mykola-mokhnach** [comment]
The patch has been published to appium@beta
