### ISSUE TITLE
Appium: Unable to get WebView context and automate WebView for iOS app

### ISSUE THREAD

**Issue by ayush-shta** [appium/appium#13985]
## The problem

I have an iOS hybrid application that includes a webview login page for Okta authorization. However, during the automation process, after app opens the "okta" webview, I am unable to get the webview context and automate the webview.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0
* Desktop OS/version used to run Appium: macOS Mojave Version 10.14.6
* Node.js version: v10.15.3
* Npm or Yarn package manager: npm
* Mobile platform/version under test: 13.3
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Details
Below is the JS code that I used for Appium automation:

```
const wd = require('wd');
const driver = wd.promiseChainRemote('http://localhost:4723/wd/hub');
const asserters = wd.asserters;
const capabilities = {
  'platformName': 'iOS',
  'platformVersion': '13.3',
  'automationName': 'XCUITest',
  'deviceName': 'iPhone 8',
  'app': '/Users/usernam/Documents/DEV.app',
  'autoAcceptAlerts': true,
  'deviceReadyTimeout': 5,
  'locationServicesEnabled': true,
  'startIWDP': true,
  'WebViewDebuggingEnabled': true
};

async function main() {
  await driver.init(capabilities);

  await sleep(2000).then(() => _oktaAuthorization());

  await sleep(5000).then(() => automateWebView());
}

async function _oktaAuthorization() {
  await driver.elementByAccessibilityId('Authorize with Okta').click();
  await driver.waitForElement('accessibility id', 'Continue', asserters.isDisplayed, 4000, 200);
}

function automateWebView() {
  setTimeout(() => {
    driver
    .contexts().then(contexts => {
      console.log('context', contexts);
      
      return driver.context(contexts[1]);
    })
    .elementsByCss('#okta-signin-submit').click()
    .quit();
  }, 3000);
}

function sleep(time) {
  return new Promise((resolve) => {
    setTimeout(resolve, time);
  });
}

main().catch(console.log);

```

## Link to Appium logs
https://gist.github.com/ayush-shta/bae896daa803d9eac6dd9277e169b71b

**Comment by imurchie** [comment]
Please try using the latest appium beta. Much has been updated in it.

**Comment by mykola-mokhnach** [comment]
Also make sure the web view is debuggable via Safari

**Comment by kirillbilchenko** [comment]
Having the same issue with ios 13m when new appium release is planned?

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by kirillbilchenko** [comment]
@mykola-mokhnach yes, web view is debuggable in my case and test is working on ios 11/12 but fail to find web view on ios 13, if you need logs I can provide.

**Comment by imurchie** [comment]
Logs would be great, with Appium 1.17.0 beta. As a link to a [gist](https://gist.github.com).

**Comment by kirillbilchenko** [comment]
@imurchie @mykola-mokhnach works on 1.17.0 as expected, thanks guys

**Comment by ayush-shta** [comment]
@mykola-mokhnach sorry for the late response. I tried the new beta 1.17.0 but was unable to get the web view context. Tried it in a real device iOS 13.3 and a simulator. Here is the gist of logs after using 1.17.0 beta: [appiumLogs]( https://gist.github.com/ayush-shta/05309042d99bb5e4a4bbbfab421bb09e)

**Comment by mykola-mokhnach** [comment]
@ayush-shta 

> Also make sure the web view is debuggable via Safari

Is is actually debuggable?

**Comment by imurchie** [comment]
@ayush-shta  This is most likely a timing issue. Appium just checks the Web Inspector for applications present, and if none are there, returns that. Either use the `webviewConnectTimeout` capability, set to some number which is the milliseconds to wait. Or poll from the client side for a while.

**Comment by ayush-shta** [comment]
@mykola-mokhnach Sorry, I'm not sure how to check that if it is.
