### ISSUE TITLE
AppiumDriver.performTouch does not work on webview page with Appium 1.16.0

### ISSUE THREAD

**Issue by helenren** [appium/appium#13993]
## The problem

In our test, we hit following error for tap via touchaction on a webview page:
```
[debug] [MJSONWP (d753ae85)] Calling AppiumDriver.performTouch() with args: [[{"action":"tap","options":{"x":12,"y":478}}],"d753ae85-b09c-49b9-9768-3064b4f84963"]
539804:33:21 V [debug] [XCUITest] Executing command 'performTouch'
539904:33:21 V [debug] [XCUITest] Received the following touch action: tap(options={"x":12,"y":478})
540004:33:21 V [debug] [XCUITest] Setting custom timeout to 60000 ms for 'performTouch' command
540104:33:21 V [debug] [WD Proxy] Proxying [POST /wda/touch/perform] to [POST http://127.0.0.1:5711/session/284DFBB3-967E-49F8-9C7F-9BDF137C6887/wda/touch/perform] with body: {"actions":[{"action":"tap","options":{"x":12,"y":478}}]}
540204:33:21 V [WD Proxy] Got an unexpected response with status undefined: {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}
540304:33:21 V [XCUITest] The Touch API is aimed for usage in NATIVE context. Consider using "execute" API with custom events trigger script to emulate touch events being in WEBVIEW context. Original error: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET
540404:33:21 V [debug] [MJSONWP (d753ae85)] Encountered internal error running command: Error: The Touch API is aimed for usage in NATIVE context. Consider using "execute" API with custom events trigger script to emulate touch events being in WEBVIEW context. Original error: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET
540504:33:21 V [debug] [MJSONWP (d753ae85)]     at Object.errorAndThrow (/root/appium/appium/1.16.0/node_modules/appium/node_modules/appium-support/lib/logging.js:74:35)
540604:33:21 V [debug] [MJSONWP (d753ae85)]     at XCUITestDriver.performTouch (/root/appium/appium/1.16.0/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/gesture.js:76:9)
```

## Environment

* Appium version (or git revision) that exhibits the issue: v1.16.0-beta.3
* Last Appium version that did not exhibit the issue (if applicable): 1.14.0
* Mobile platform/version under test: ios 13.3.1
* Real device or emulator/simulator: ios real devcie, iphone plus

With this error, does that mean on ios 13 with appium 1.16, touchaction only support to work on native page? We can use it on webview page on ios 12 with appium 1.14 even.

**Comment by mykola-mokhnach** [comment]
> With this error, does that mean on ios 13 with appium 1.16, touchaction only support to work on native page?

exactly. Touch actions are always executed in native context even if the current context is not set to native.

> We can use it on webview page on ios 12 with appium 1.14 even.

ECONNRESET means that WebDriverAgent server stopped responding to the driver commands. The device log might contain more details about why this is happening.

**Comment by helenren** [comment]
Attach the device log here:

[Uploading SauceLabs_Log_iPhone_8_Plus_SF_us_25-02-2020_11-41-19.txt…]()

**Comment by mykola-mokhnach** [comment]
Unfortunately the link above is not valid

**Comment by imurchie** [comment]
The full Appium logs might show if/how/why WDA isn't responding (if it crashed or something).

**Comment by helenren** [comment]
@mykola-mokhnach attach them again. 

[SauceLabs_Log_iPhone_8_Plus_SF_us_25-02-2020_11-41-19.txt](https://github.com/appium/appium/files/4257330/SauceLabs_Log_iPhone_8_Plus_SF_us_25-02-2020_11-41-19.txt)

The full appium log:
[SauceLabs_Appium_iPhone_8_Plus_SF_us_26-02-2020_09-49-47.txt](https://github.com/appium/appium/files/4257337/SauceLabs_Appium_iPhone_8_Plus_SF_us_26-02-2020_09-49-47.txt)

**Comment by helenren** [comment]
@imurchie the last command before hitting this issue, seems WDA still works there:

04:33:20	VERBOSE:	[HTTP] --> GET /wd/hub/session/d753ae85-b09c-49b9-9768-3064b4f84963/element/5017/location
04:33:20	VERBOSE:	[HTTP] {}
04:33:20	VERBOSE:	[debug] [MJSONWP (d753ae85)] Calling AppiumDriver.getLocation() with args: ["5017","d753ae85-b09c-49b9-9768-3064b4f84963"]
04:33:20	VERBOSE:	[debug] [XCUITest] Executing command 'getLocation'
04:33:20	VERBOSE:	[debug] [RemoteDebugger] Executing atom 'get_top_left_coordinates'
04:33:20	VERBOSE:	[debug] [RemoteDebugger] Executing 'get_top_left_coordinates' atom in default context
04:33:20	VERBOSE:	[debug] [RemoteDebugger] Sending javascript command: '(function(){return function(){var h,l=this;func...'
04:33:20	VERBOSE:	[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:359', page '8', target 'page-38' (id: 243)
04:33:20	VERBOSE:	[debug] [RemoteDebugger] Received data response from send (id: 243): '"{\"status\":0,\"value\":{\"x\":12,\"y\":447,\"toString\":\"function (){return\\\"(\\\"+this.x+\\\", \\\"+this.y+\\\")\\\"}\",\"ceil\":\"function (){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y...'
04:33:20	VERBOSE:	[debug] [RemoteDebugger] Sending to Web Inspector took 16ms
04:33:20	VERBOSE:	[debug] [RemoteDebugger] Received result for atom 'get_top_left_coordinates' execution: {"x":12,"y":447}
04:33:20	VERBOSE:	[debug] [MJSONWP (d753ae85)] Responding to client with driver.getLocation() result: {"x":12,"y":447,"toString":"function (){return\"(\"+this.x+\", \"+this.y+\")\"}","ceil":"function (){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this}","floor":"function (){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this}","round":"function (){this.x=Math.round(this.x);this.y=Math.round(this.y);return this}","scale":"function (a,b){b=aa(b)?b:a;this.x*=a;this.y*=b;return this}"}
04:33:20	VERBOSE:	[HTTP] <-- GET /wd/hub/session/d753ae85-b09c-49b9-9768-3064b4f84963/element/5017/location 200 19 ms - 481

And attach the full appium log above. Thanks.

**Comment by imurchie** [comment]
That is all through the Web Inspector, so not affecting WDA at all. But there is a call to get a screenshot afterwards, which succeeds so WDA is still functioning after the failure.

**Comment by helenren** [comment]
@imurchie the wda log may be helpful here? Not use that log often.

**Comment by mykola-mokhnach** [comment]
I don't observe any issues in the attached device log. Perhaps the issue has to do with the network connectivity between the device and the server. Consider contacting SauceLabs customer support

**Comment by mykola-mokhnach** [comment]
I have deleted the comment with logs, because they contain your API keys, which should not be publicly available. Please make sure there is no sensitive info in the shared logs before publishing them

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
