### ISSUE TITLE
tvOS tests cannot find text on screen on the first test run only

### ISSUE THREAD

**Issue by BoazWarshawsky** [appium/appium#13995]
## The problem
I am running a simple test that searching for a text on the screen, I have found that I am **not** able to find this text on-screen on the first run of the test after a **fresh install of the app**, but I am able to find the text on the 2nd, 3rd,... runs of the exact same test. 

The way I am searching for this text is in the following ways (python syntax):

- `self.driver.find_element(MobileBy.IOS_PREDICATE, "name == '" + text + "'")`
- `self.driver.find_element_by_xpath('//*[contains(@name, "%s")]' % text)`
- `self.driver.find_element_by_name(text)`

None of them succeeds 

I must mention that starting the app manually after a fresh install succeeds. 

## Environment

* Appium version (or git revision) that exhibits the issue: tried with 1.16.0 and 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): not found.
* Desktop OS/version used to run Appium: Mac Catalina 
* Node.js version (unless using Appium.app|exe): 8.16.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: tvOS
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
Logs: https://assets-secure.applicaster.com/qa/zapp_qa/manual/boaz/appium_text_issue.log

## Code To Reproduce Issue [ Good To Have ]
1. Install fresh tvOS app on your Apple TV Simulator using OS 13.3
2. Launch the test and search for some text on the screen.

**Comment by BoazWarshawsky** [comment]
@mykola-mokhnach @imurchie, can you please help me with that issue? I am really stuck here for a few days :-( 
Thanks!

**Comment by KazuCocoa** [comment]
What about the result of `source` command?
If you could not get the correct source, I assume the root cause is in XCTest framework side. 

https://gist.github.com/KazuCocoa/3450dd6218ec70eb94f8a8f33b56d5ac is a log I ran https://github.com/appium/ruby_lib_core/blob/master/test/functional/ios/tv_driver_test.rb#L39 on my local from a fresh simulator. It could find elements.

**Comment by BoazWarshawsky** [comment]
@KazuCocoa, sorry, what do you mean by saying `source` command?

**Comment by KazuCocoa** [comment]
https://appium.io/docs/en/commands/session/source/ here is.

**Comment by BoazWarshawsky** [comment]
@KazuCocoa 
**### I am not able to reach the source:**
`
self = <appium.webdriver.errorhandler.MobileErrorHandler object at 0x10abe6f50>
response = {'status': 500, 'value': '{"value":{"error":"unknown error","message":"An unknown server-side error occurred while pro...cal/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:259:19)\\n    at <anonymous>"}}'}

    def check_response(self, response):
        """
        Checks that a JSON response from the WebDriver does not have an error.
    
        :Args:
         - response - The JSON response from the WebDriver server as a dictionary
           object.
    
        :Raises: If the response contains an error message.
        """
        status = response.get('status', None)
        if status is None or status == ErrorCode.SUCCESS:
            return
        value = None
        message = response.get("message", "")
        screen = response.get("screen", "")
        stacktrace = None
        if isinstance(status, int):
            value_json = response.get('value', None)
            if value_json and isinstance(value_json, basestring):
                import json
                try:
                    value = json.loads(value_json)
                    if len(value.keys()) == 1:
                        value = value['value']
                    status = value.get('error', None)
                    if status is None:
                        status = value["status"]
                        message = value["value"]
                        if not isinstance(message, basestring):
                            value = message
                            message = message.get('message')
                    else:
                        message = value.get('message', None)
                except ValueError:
                    pass
    
        exception_class = ErrorInResponseException
        if status in ErrorCode.NO_SUCH_ELEMENT:
            exception_class = NoSuchElementException
        elif status in ErrorCode.NO_SUCH_FRAME:
            exception_class = NoSuchFrameException
        elif status in ErrorCode.NO_SUCH_WINDOW:
            exception_class = NoSuchWindowException
        elif status in ErrorCode.STALE_ELEMENT_REFERENCE:
            exception_class = StaleElementReferenceException
        elif status in ErrorCode.ELEMENT_NOT_VISIBLE:
            exception_class = ElementNotVisibleException
        elif status in ErrorCode.INVALID_ELEMENT_STATE:
            exception_class = InvalidElementStateException
        elif status in ErrorCode.INVALID_SELECTOR \
                or status in ErrorCode.INVALID_XPATH_SELECTOR \
                or status in ErrorCode.INVALID_XPATH_SELECTOR_RETURN_TYPER:
            exception_class = InvalidSelectorException
        elif status in ErrorCode.ELEMENT_IS_NOT_SELECTABLE:
            exception_class = ElementNotSelectableException
        elif status in ErrorCode.ELEMENT_NOT_INTERACTABLE:
            exception_class = ElementNotInteractableException
        elif status in ErrorCode.INVALID_COOKIE_DOMAIN:
            exception_class = InvalidCookieDomainException
        elif status in ErrorCode.UNABLE_TO_SET_COOKIE:
            exception_class = UnableToSetCookieException
        elif status in ErrorCode.TIMEOUT:
            exception_class = TimeoutException
        elif status in ErrorCode.SCRIPT_TIMEOUT:
            exception_class = TimeoutException
        elif status in ErrorCode.UNKNOWN_ERROR:
            exception_class = WebDriverException
        elif status in ErrorCode.UNEXPECTED_ALERT_OPEN:
            exception_class = UnexpectedAlertPresentException
        elif status in ErrorCode.NO_ALERT_OPEN:
            exception_class = NoAlertPresentException
        elif status in ErrorCode.IME_NOT_AVAILABLE:
            exception_class = ImeNotAvailableException
        elif status in ErrorCode.IME_ENGINE_ACTIVATION_FAILED:
            exception_class = ImeActivationFailedException
        elif status in ErrorCode.MOVE_TARGET_OUT_OF_BOUNDS:
            exception_class = MoveTargetOutOfBoundsException
        elif status in ErrorCode.JAVASCRIPT_ERROR:
            exception_class = JavascriptException
        elif status in ErrorCode.SESSION_NOT_CREATED:
            exception_class = SessionNotCreatedException
        elif status in ErrorCode.INVALID_ARGUMENT:
            exception_class = InvalidArgumentException
        elif status in ErrorCode.NO_SUCH_COOKIE:
            exception_class = NoSuchCookieException
        elif status in ErrorCode.UNABLE_TO_CAPTURE_SCREEN:
            exception_class = ScreenshotException
        elif status in ErrorCode.ELEMENT_CLICK_INTERCEPTED:
            exception_class = ElementClickInterceptedException
        elif status in ErrorCode.INSECURE_CERTIFICATE:
            exception_class = InsecureCertificateException
        elif status in ErrorCode.INVALID_COORDINATES:
            exception_class = InvalidCoordinatesException
        elif status in ErrorCode.INVALID_SESSION_ID:
            exception_class = InvalidSessionIdException
        elif status in ErrorCode.UNKNOWN_METHOD:
            exception_class = UnknownMethodException
        else:
            exception_class = WebDriverException
        if value == '' or value is None:
            value = response['value']
        if isinstance(value, basestring):
            if exception_class == ErrorInResponseException:
                raise exception_class(response, value)
            raise exception_class(value)
        if message == "" and 'message' in value:
            message = value['message']
    
        screen = None
        if 'screen' in value:
            screen = value['screen']
    
        stacktrace = None
        if 'stackTrace' in value and value['stackTrace']:
            stacktrace = []
            try:
                for frame in value['stackTrace']:
                    line = self._value_or_default(frame, 'lineNumber', '')
                    file = self._value_or_default(frame, 'fileName', '<anonymous>')
                    if line:
                        file = "%s:%s" % (file, line)
                    meth = self._value_or_default(frame, 'methodName', '<anonymous>')
                    if 'className' in frame:
                        meth = "%s.%s" % (frame['className'], meth)
                    msg = "    at %s (%s)"
                    msg = msg % (meth, file)
                    stacktrace.append(msg)
            except TypeError:
                pass
        if exception_class == ErrorInResponseException:
            raise exception_class(response, message)
        elif exception_class == UnexpectedAlertPresentException:
            alert_text = None
            if 'data' in value:
                alert_text = value['data'].get('text')
            elif 'alert' in value:
                alert_text = value['alert'].get('text')
            raise exception_class(message, screen, stacktrace, alert_text)
>       raise exception_class(message, screen, stacktrace)
E       selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot get 'xml' source of the current application

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py:242: WebDriverException

Assertion failed

Assertion failed
`

**Comment by KazuCocoa** [comment]
Could you share the appium server full log with `showIOSLog` and `showXcodeLog` as GIST?
I assume appium/WDA could not get data from XCTest framework.

**Comment by BoazWarshawsky** [comment]
As thin as possible: https://assets-secure.applicaster.com/qa/zapp_qa/manual/boaz/xcode_logs.log

Thanks @KazuCocoa

**Comment by KazuCocoa** [comment]
It looks XCTest framework raised an error, unfortunately. So nothing we can do in Appium side.

```
[35m[IOSSimulatorLog][39m [IOS_SYSLOG_ROW]     1102
[35m[IOSSimulatorLog][39m [IOS_SYSLOG_ROW] ), got values (
[35m[IOSSimulatorLog][39m [IOS_SYSLOG_ROW]         (
[35m[IOSSimulatorLog][39m [IOS_SYSLOG_ROW]         "<AXUIElementRef 0x7f8737e0b870> {pid=94012} {uid=[ID:1 hash:0x0]}"
[35m[IOSSimulatorLog][39m [IOS_SYSLOG_ROW]     )
[35m[IOSSimulatorLog][39m [IOS_SYSLOG_ROW] )
[35m[IOSSimulatorLog][39m [IOS_SYSLOG_ROW] 2020-02-27 15:48:33.431 Df testmanagerd[85554:45acf4] [com.apple.dt.xctest:Default] Got attributes, transferring to dictionary for return.
[35m[IOSSimulatorLog][39m [IOS_SYSLOG_ROW] 2020-02-27 15:48:33.434 Df testmanagerd[85554:45acf4] [com.apple.dt.xctest:Default] XCTPerformOnMainRunLoop[not MT]: about to CFRunLoopPerform
[35m[IOSSimulatorLog][39m [IOS_SYSLOG_ROW] 2020-02-27 15:48:33.434 Df testmanagerd[85554:45acf4] [com.apple.dt.xctest:Default] XCTPerformOnMainRunLoop[not MT]: waiting with 30.00s responsiveness timeout
[35m[IOSSimulatorLog][39m [IOS_SYSLOG_ROW] 2020-02-27 15:48:33.434 Df testmanagerd[85554:412cbe] [com.apple.dt.xctest:Default] XCTPerformOnMainRunLoop[MT]: inside CFRunLoopPerform
[35m[IOSSimulatorLog][39m [IOS_SYSLOG_ROW] 2020-02-27 15:48:33.434 Df testmanagerd[85554:412cbe] [com.apple.dt.xctest:Default] XCTPerformOnMainRunLoop[MT]: MT responded in time (won the race to the busy flag)
[35m[IOSSimulatorLog][39m [IOS_SYSLOG_ROW] 2020-02-27 15:48:33.434 Df testmanagerd[85554:45acf4] [com.apple.dt.xctest:Default] XCTPerformOnMainRunLoop[not MT]: waiting 60.00s for work to complete
[35m[IOSSimulatorLog][39m [IOS_SYSLOG_ROW] 2020-02-27 15:48:33.435 E  testmanagerd[85554:412cbe] [com.apple.dt.xctest:Default] XCTAS Error: XCTAutomationSupportErrorUnknownElement: Error getting main window kAXErrorServerNotFound
[35m[IOSSimulatorLog][39m [IOS_SYSLOG_ROW] 2020-02-27 15:48:33.435 E  testmanagerd[85554:412cbe] [com.apple.dt.xctest:Default] XCTAS Error: Error Domain=com.apple.dt.xctest.automation-support.error Code=8 "Error getting main window kAXErrorServerNotFound" UserInfo={NSLocalizedDescription=Error getting main window kAXErrorServerNotFound}
[35m[IOSSimulatorLog][39m [IOS_SYSLOG_ROW] 2020-02-27 15:48:33.435 E  testmanagerd[85554:45acf4] [com.apple.dt.xctest:Default] XCTAS Error: Error Domain=com.apple.dt.xctest.automation-support.error Code=8 "Error getting main window kAXErrorServerNotFound" UserInfo={NSLocalizedDescription=Error getting main window kAXErrorServerNotFound}
[35m[IOSSimulatorLog][39m [IOS_SYSLOG_ROW] 2020-02-27 15:48:33.439 Df testmanagerd[85554:45acf4] [com.apple.dt.xctest:Default] XCTPerformOnMainRunLoop[not MT]: about to CFRunLoopPerform
[35m[IOSSimulatorLog][39m [IOS_SYSLOG_ROW] 2020-02-27 15:48:33.439 Df testmanagerd[85554:45acf4] [com.apple.dt.xctest:Default] XCTPerformOnMainRunLoop[not MT]: waiting with 30.00s responsiveness timeout
[35m[IOSSimulatorLog][39m [IOS_SYSLOG_ROW] 2020-02-27 15:48:33.439 Df testmanagerd[85554:412cbe] [com.apple.dt.xctest:Default] XCTPerformOnMainRunLoop[MT]: inside CFRunLoopPerform
[35m[IOSSimulatorLog][39m [IOS_SYSLOG_ROW] 2020-02-27 15:48:33.439 Df testmanagerd[85554:412cbe] [com.apple.dt.xctest:Default] XCTPerformOnMainRunLoop[MT]: MT responded in time (won the race to the busy flag)
[35m[IOSSimulatorLog][39m [IOS_SYSLOG_ROW] 2020-02-27 15:48:33.439 Df testmanagerd[85554:45acf4] [com.apple.dt.xctest:Default] XCTPerformOnMainRunLoop[not MT]: waiting 60.00s for work to complete
[35m[IOSSimulatorLog][39m [IOS_SYSLOG_ROW] 2020-02-27 15:48:33.439 E  testmanagerd[85554:412cbe] [com.apple.dt.xctest:Default] XCTAS Error: XCTAutomationSupportErrorUnknownElement: Error getting main window kAXErrorServerNotFound
[35m[IOSSimulatorLog][39m [IOS_SYSLOG_ROW] 2020-02-27 15:48:33.439 E  testmanagerd[85554:412cbe] [com.apple.dt.xctest:Default] XCTAS Error: Error Domain=com.apple.dt.xctest.automation-support.error Code=8 "Error getting main window kAXErrorServerNotFound" UserInfo={NSLocalizedDescription=Error getting main window kAXErrorServerNotFound}
[35m[IOSSimulatorLog][39m [IOS_SYSLOG_ROW] 2020-02-27 15:48:33.440 E  testmanagerd[85554:45acf4] [com.apple.dt.xctest:Default] XCTAS Error: Error Domain=com.apple.dt.xctest.automation-support.error Code=8 "Error getting main window kAXErrorServerNotFound" UserInfo={NSLocalizedDescription=Error getting main window kAXErrorServerNotFound}
[35m[IOSSimulatorLog][39m [IOS_SYSLOG_ROW] 2020-02-27 15:48:33.441 Df WebDriverAgentRunner_tvOS-Runner[93933:45a399] (WebDriverAgentLib_tvOS) Enqueue Failure: Failed to get matching snapshots: Error getting main window kAXErrorServerNotFound /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgentRunner/UITestingUITests.m 38 1
[35m[WD Proxy][39m Got an unexpected response with status 404: {"value":{"error":"no such element","message":"unable to find an element using 'predicate string', value 'name == 'Home''","traceback":"(\n\t0   WebDriverAgentLib_tvOS              0x000000010ddfe13d FBNoSuchElementErrorResponseForRequest + 301\n\t1   WebDriverAgentLib_tvOS              0x000000010ddfdee1 +[FBFindElementCommands handleFindElement:] + 433\n\t2   WebDriverAgentLib_tvOS              0x000000010dddecb6 -[FBRoute_TargetAction mountRequest:intoResponse:] + 182\n\t3   WebDriverAgentLib_tvOS              0x000000010ddd0e0b __37-[FBWebServer registerRouteHandlers:]_block_invoke + 555\n\t4   RoutingHTTPServer                   0x000000010df438bd -[RoutingHTTPServer handleRoute:withRequest:response:] + 136\n\t5   RoutingHTTPServer                   0x000000010df441d0 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 47\n\t6   libdispatch.dylib                   0x00007fff409ca7b9 _dispatch_client_callout + 8\n\t7   libdispatch.dylib                   0x00007f...
[debug] [35m[W3C][39m Matched W3C error code 'no such element' to NoSuchElementError
[debug] [35m[W3C (ac6ef73f)][39m Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[debug] [35m[W3C (ac6ef73f)][39m     at XCUITestDriver.doNativeFind (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:126:11)
[debug] [35m[W3C (ac6ef73f)][39m     at <anonymous>
[35m[HTTP][39m [37m<-- POST /wd/hub/session/ac6ef73f-d054-40e2-98eb-059a826fd0ae/element [39m[33m404[39m [90m30 ms - 399[39m
```

**Comment by BoazWarshawsky** [comment]
I see, last question, from your experience, what can have a cause that?
Assuming that it's happening only after a fresh install of the app.

Thanks!

**Comment by KazuCocoa** [comment]
We cannot dig XCTest internal.
If XCTest framework works so, Appium also works as same since appium send requests to XCTest framework and return the result to clients. Thus, I have no good idea about the cause, unfortunately.

One workaround is probably 1) install the app, 2) delete the session once and create a session again in a scenario.
Or if it can resolve you terminate the app once, you can try 1) create a session, 2) terminate the app process with https://appium.io/docs/en/commands/device/app/terminate-app/ , 3) activate the app with http://appium.io/docs/en/commands/device/app/activate-app/

**Comment by KazuCocoa** [comment]
We cannot dig XCTest internal.
If XCTest framework works so, Appium also works as same since appium send requests to XCTest framework and return the result to clients. Thus, I have no good idea about the cause, unfortunately.

One workaround is probably 1) install the app, 2) delete the session once and create a session again in a scenario.
Or if it can resolve you terminate the app once, you can try 1) create a session, 2) terminate the app process with https://appium.io/docs/en/commands/device/app/terminate-app/ , 3) activate the app with http://appium.io/docs/en/commands/device/app/activate-app/

**Comment by KazuCocoa** [comment]
Updating the Xcode version or switch to older Xcode versions also might help sometimes

**Comment by BoazWarshawsky** [comment]
Good idea, something I will check.
We can close the ticket.
