### ISSUE TITLE
Appium 1.16.0 Android sendKeys is not working

### ISSUE THREAD

**Issue by ljupcob** [appium/appium#13997]
## The problem

When keyboard is open, sendKeys is not working. 

## Environment

* Appium version (or git revision) that exhibits the issue: **1.16.0**
* Last Appium version that did not exhibit the issue (if applicable): **1.9.1**
* Desktop OS/version used to run Appium: MAC 10.14.6
* Node.js version (unless using Appium.app|exe): **v11.10.1**
* Npm or Yarn package manager: **npm**
* Mobile platform/version under test: **Android**
* Real device or emulator/simulator: **Real Device**
* Appium CLI or Appium.app|exe: **Appium CLI**

## Details

Issue reproduced on Pixel 2, OS 10, Android. When keyboard is open, sendKeys is not working. If I try to send text through adb it is working but sendKeys is not working.
Usage in the code: driver.getKeyboard().sendKeys(text);

## Link to Appium logs

https://gist.github.com/ljupcob/1b9b926b6196b3f7cf09c7de38d1d856

## Code To Reproduce Issue [ Good To Have ]

driver.getKeyboard().sendKeys(text);

**Comment by mykola-mokhnach** [comment]
The exception in the log seems like an expected one. Are you sure there is an active element to send keys to?

**Comment by ljupcob** [comment]
Keyboard is up on device and is waiting for an input, if I change sendKey with adb shell input text it is working. BTW i just checked it on Samsung S6 with OS 7.0 also is not working, while for iOS is ok

**Comment by ljupcob** [comment]
Update: Just downgraded to 1.12.0 and it is working, so it is not working currently in latest version 1.16.0

**Comment by mykola-mokhnach** [comment]
I don't observe any issues here. Perhaps, you were using UIA1 backend before (currently deprecated). Try https://appiumpro.com/editions/46 to emulate direct sending of text. Also, the recently appium@beta got the `mobile: type` endpoint, which could do the same, but also supports unicode chars

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
