### ISSUE TITLE
Appium v1.16.0: uncaughtException: write EPIPE

### ISSUE THREAD

**Issue by shibupanda** [appium/appium#13998]
## The problem
Getting "uncaughtException: write EPIPE" while running script on Appium version 1.16.0

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0
* Last Appium version that did not exhibit the issue (if applicable): 1.15.1
* Desktop OS/version used to run Appium: Mac
* Node.js version (unless using Appium.app|exe): 10.17.*
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS v10.1.1(iPhone 6s)
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Details
Getting "uncaughtException: write EPIPE" while running script on Appium version 1.16.0

## Link to Appium logs

https://gist.github.com/shibupanda/611cd6bea6b6f611013e7dae29d73b40

## Code To Reproduce Issue [ Good To Have ]
IOS driver initialisation code in v1.16.0

**Comment by mykola-mokhnach** [comment]
Please try appium@beta

**Comment by mykola-mokhnach** [comment]
Closed because of no response
