### ISSUE TITLE
[Chromedriver] Error: Failed to start Chromedriver session: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: 302 - undefined

### ISSUE THREAD

**Issue by CrazyMunda** [appium/appium#13991]
## The problem

I am trying to run few bdd test on my **android Galaxy 8** device and while Appium is trying to establish a connection through my phone I am getting error
"
Failed to start Chromedriver session: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: 302 - undefined "

## Environment

* Appium version (1.13)
*Window 10
* Node.js version (v13.9):
*  Mobile platform/version under test: Chrome(80.0.3987)
*android Galaxy 8 

## Details

**[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[WD Proxy] Got response with status 200: "\n\n\n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n**

Log is showing As

[debug] [35m[WD Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[WD Proxy][39m Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body[debug] [35m[WD Proxy][39m Got response with status 200: "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"utf-8\">\n  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n  <meta name=\"description\" content=\"General Electric Captcha Page\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n  <link href=\"https://static.gecirtnotification.com/captcha/images/apple-touch-icon-72px.png\" rel=\"apple-touch-icon-precomposed\" sizes=\"72x72\" />\n  <link rel=\"preconnect\" href=\"https://static.gecirtnotification.com\" />\n  <link rel=\"shortcut icon\" href=\"https://static.gecirtnotification.com/captcha/images/favicon-bluesteel-72px.png\" type=\"image/png\" />\n  <link href=\"https://static.gecirtnotification.com/captcha/images/apple-touch-icon-114px.png\" rel=\"apple-touch-icon-precomposed\" sizes=\"114x114\" />\n  <link href=\"https://static.gecirtnotification.com/captcha/images/apple-touch-icon-144px.png\" rel=\"apple-touch-icon-precomposed\" sizes=\"144x144\" />\n  <title>Block page</title>\n  <link rel=\"styleshee...
[debug] [35m[WD Proxy][39m Determined that the downstream protocol for proxy is undefined
[debug] [35m[WD Proxy][39m Matched '/session' to command name 'createSession'
[debug] [35m[WD Proxy][39m Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","androidDeviceSerial":"988e16304351333151"},"loggingPrefs":{"browser":"ALL"}}}[warn] [35m[WD Proxy][39m Got an unexpected response: 
[error] [35m[Chromedriver][39m Error: Failed to start Chromedriver session: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: 302 - undefined
[error] [35m[Chromedriver][39m     at Object.wrappedLogger.errorAndThrow (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:78:13)
[error] [35m[Chromedriver][39m     at errorAndThrow (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-chromedriver\lib\chromedriver.js:493:13)[debug] [35m[WD Proxy][39m Matched '/session' to command name 'createSession'
[debug] [35m[WD Proxy][39m Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","androidDeviceSerial":"988e16304351333151"},"loggingPrefs":{"browser":"ALL"}}}
[warn] [35m[WD Proxy][39m Got an unexpected response:

**Comment by mykola-mokhnach** [comment]
> http://127.0.0.1:8000/wd/hub/status] with no body[debug] �[35m[WD Proxy]�[39m Got response with status 200: "\n<html lang="en">\n\n <meta charset="utf-8">\n <meta http-equiv="X-UA-Compatible" content="IE=edge">\n <meta name="description" content="General Electric Captcha Page">\n <meta name="viewport" content="width=device-width, initial-scale=1">\n <link href="https://static.gecirtnotification.com/captcha/images/apple-touch-icon-72px.png" rel="apple-touch-icon-precomposed" sizes="72x72" />\n <link rel="preconnect" href="https://static.gecirtnotification.com" />\n <link rel="shortcut icon" href="https://static.gecirtnotification.com/captcha/images/favicon-bluesteel-72px.png" type="image/png" />\n <link href="https://static.gecirtnotification.com/captcha/images/apple-touch-icon-114px.png" rel="apple-touch-icon-precomposed" sizes="114x114" />\n <link href="https://static.gecirtnotification.com/captcha/images/apple-touch-icon-144px.png" rel="apple-touch-icon-precomposed" sizes="144x144" />\n <title>Block page</title>\n <link rel="styleshee...

There's a local proxy on the machine, which intercepts Appium requests. Please contact your system administrator to resolve the problem.

Closed as not an issue.
