### ISSUE TITLE
Session wait timeout 10 mins

### ISSUE THREAD

**Issue by kolyakrasnik** [appium/appium#13994]
Was noticed, that for some reasons we are getting too long timeout during session start up. 
`org.openqa.selenium.WebDriverException: Error forwarding the new session Error forwarding the request unexpected end of stream on Connection{host:port, proxy=DIRECT hostAddress=/host:port cipherSuite=none protocol=http/1.1}
Command duration or timeout: **600.23 seconds**`
I tried to set parameter `capabilities.newSessionWaitTimeout=60` but no success. How can I change this timeout?

Environment:
 - iOS real devices;
 - appium 1.16.0;
 - using selenium hub for automation.

**Comment by mykola-mokhnach** [comment]
Unfortunately it is totally unclear what we are talking here about. Pleas provide the full server logs and describe the steps to reproduce the issue

**Comment by kolyakrasnik** [comment]
We are running our tests on iOS real devices using selenium hub. And sometimes we are getting `org.openqa.selenium.WebDriverException : Error forwarding the new session Error`  with timeout 
`Command duration or timeout:  600.23 seconds`. The session had not been even started for this timeout `600.23 seconds` This issue is temporary and appears from time to time, so I'm trying to catch logs, but no success for now. 
My question is  - how can I adjust this timeout, is it appium node config parameter or we can adjust this parameter on driver level?  
The issue is only with long freeze - 10mins.

**Comment by mykola-mokhnach** [comment]
I cannot understand what the issue has to do with Appium. For me it looks like a thing in Selenium hub

**Comment by kolyakrasnik** [comment]
Thanks @mykola-mokhnach,  I'm thinking the same, just decided to clarify, might there is some appium timeout config. Will dig deeper with Selenium hub config.
