### ISSUE TITLE
VoiceAutoamtion with IOS

### ISSUE THREAD

**Issue by apiautoamtion** [appium/appium#14007]
## The problem

I want to Automate Google Voice with Appium, but don't have proper solution

## Environment

Using latest version of Appium
Real devices 
## Details

Now i am able to process with freetts Text to Voice play java code

My application is developed with Google Voice commands 

Siri process wont work for me 
https://appiumpro.com/editions/45

But problem is, we are using more than 50 devices into the Grid with microphone play option is not accurate with the freetts. 

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Unfortunately, XCTest does not provide any API we know about to make that possible. Consider raising a feature request for Apple.
