### ISSUE TITLE
Original error: No targets found, unable to communicate with device

### ISSUE THREAD

**Issue by ishanm120** [appium/appium#14009]
Getting error Original error: No targets found, unable to communicate with device when running automation script on real iphone device

## Environment
* Device: iPhone X (12.1.1)
* Appium: 1.14.2
* XCode: 10.3
* Mac OS : Mojave 10.14.4 

## Link to Appium logs

https://gist.github.com/ishanm120/f7444494776ffaca56b01065c140a9e0

**Comment by imurchie** [comment]
Please try the latest Appium.

**Comment by ishanm120** [comment]
> Please try the latest Appium.

I tried with other device as well and they are working fine with same appium version

**Comment by imurchie** [comment]
Be that as it may, there is little that can be done for an error on an old version, that was fixed in code.

**Comment by ishanm120** [comment]
It worked after updating appium to 1.16.0 and also changing webdriverAgent directory.
Thank you guys.
