### ISSUE TITLE
APPIUM 1.15 . :     Error: Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET

### ISSUE THREAD

**Issue by vaibhav107raj** [appium/appium#14016]
## The problem

My entire automation was working fine on emulator for iOS versions. However , the same code is failing with this error and webDriver Agent runner is not able to get installed properly in emulator.

## Environment

* Appium version that exhibits the issue: 1.15 [Appium Desktop]
* Desktop OS/version used to run Appium: mac iOS [10.15]
* Node.js version (unless using Appium.app|exe): 13.6
* Npm or Yarn package manager: 6.11.3
* Mobile platform/version under test: iOS [emulator]
* Real device or emulator/simulator: emulator

## Details

The same emulator and code was working all good till yesterday. And, it gave an issue today as attached logs. 
The app is also getting installed on the emulator, but the WebDriverAgentRunner is not getting launched.

## Link to Appium logs

logs [https://gist.github.com/vaibhav107raj/88c9d83e26ff7cacbda9658abaacf336](url)

## Code To Reproduce Issue [ Good To Have ]

code : [https://gist.github.com/vaibhav107raj/8bc670420451e7e36561de1f09914f28](url)

**Comment by mykola-mokhnach** [comment]
Unfortunately the provided gist link is not accessible. I would also try the most recent server version first.

**Comment by vaibhav107raj** [comment]
Appium Logs : (https://gist.github.com/vaibhav107raj/88c9d83e26ff7cacbda9658abaacf336)

code to reproduce issue : (https://gist.github.com/vaibhav107raj/88c9d83e26ff7cacbda9658abaacf336)

**Comment by mykola-mokhnach** [comment]
Please attach the log with `showXcodeLog` cap enabled

**Comment by vaibhav107raj** [comment]
@mykola-mokhnach  can you please let me know from where to get the log with showXcodeLog cap enabled ?

Already shared the appium logs of version 1.13 and 1.15

**Comment by vaibhav107raj** [comment]
@mykola-mokhnach  sharing in few minutes

**Comment by vaibhav107raj** [comment]
@mykola-mokhnach  here is the log with showXcodeLog cap enabled 👍 
[](https://gist.github.com/vaibhav107raj/b7bc664967c5b200a40bb458b128aea0)

**Comment by mykola-mokhnach** [comment]
It looks like xcodebuild did succeed, although Appium proxy cannot reach it. I'd rather make sure the `localhost` is resolved properly on that machine. Another solution might be to upgrade the server to the recent version, where it explicitly uses IP address instead of the domain name by default.

**Comment by vaibhav107raj** [comment]
I will check that. Thanks for your suggestions and time :-)
