### ISSUE TITLE
[Launch app with arguments]Activate app seems not launch with arguments after terminate app

### ISSUE THREAD

**Issue by maggie5750** [appium/appium#14019]
## The problem

App launch with capability "processArguments"  e.g. "appium:processArguments": "{"args":["-TestingMode"]}", then terminated app and activateApp using 
driver.terminateApp(bundleId)
driver.activateApp(bundleId)
After that app actually is not launch with args:["-TestingMode"]

## Environment

* Appium version (or git revision) that exhibits the issue:1.16.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:  10.14.4
* Node.js version (unless using Appium.app|exe): 10.13.0
* Npm or Yarn package manager: npm 6.9.0
* Mobile platform/version under test: iOS 13.3
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

**Comment by KazuCocoa** [comment]
Please try http://appium.io/docs/en/writing-running-appium/ios/ios-xctest-mobile-apps-management/index.html#mobile-launchapp

**Comment by mykola-mokhnach** [comment]
It works as designed. ActiveApp endpoints supports passing arguments - it should not pick up them automatically from capabilities.
