### ISSUE TITLE
Appium- IOS:Failed to check out repository ....Code=13 "Permission denied"

### ISSUE THREAD

**Issue by u546012** [appium/appium#14013]
Can u help to resolve this issue on iOS,

## The problem

Failed to check out repository into /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer: Could not create working directory (Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “RoutingHTTPServer” in the folder “Checkouts”." UserInfo={NSFilePath=/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer, NSUnderlyingError=0x7f916141e8b0 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}})

## Environment

* Appium version (or git revision) that exhibits the issue:1.12.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:mac
* Node.js version (unless using Appium.app|exe):v11.9.0
* Npm or Yarn package manager:6.5.0
* Mobile platform/version under test:ios
* Real device or emulator/simulator:simulator
* Appium CLI or Appium.app|exe:Appium Desktop

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]
Eclipse code:

DesiredCapabilities d = new DesiredCapabilities();
d.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 8");
d.setCapability(MobileCapabilityType.PLATFORM_NAME,"IOS");
d.setCapability(MobileCapabilityType.PLATFORM_VERSION, "13.2");
d.setCapability(MobileCapabilityType.AUTOMATION_NAME,"XCUITest");
d.setCapability(MobileCapabilityType.APP, "/Users/980163/Desktop/UICatalog.app");
IOSDriver<IOSElement>driver = new IOSDriver<>(new URL("http://127.0.0.1:4723/wd/hub"),d);

**Comment by mykola-mokhnach** [comment]
> {NSFilePath=/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer, NSUnderlyingError=0x7f916141e8b0 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}})

What exactly is unclear in the `Permission denied` error?

**Comment by u546012** [comment]
> > {NSFilePath=/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer, NSUnderlyingError=0x7f916141e8b0 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}})
> 
> What exactly is unclear in the `Permission denied` error?

This is what i am getting in Appium console

[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[XCUITest] Fetching dependencies
[XCUITest] *** Checking out YYCache at "1.0.5"
[XCUITest] *** Checking out RoutingHTTPServer at "v1.0.1"
[XCUITest] *** Checking out CocoaAsyncSocket at "7.6.3"
[XCUITest] *** Cloning CocoaAsyncSocket
[XCUITest] *** Cloning YYCache
[XCUITest] 2020-03-02 13:34:00.377 carthage[835:14311] *** WARNING: CFMachPortSetInvalidationCallBack() called on a CFMachPort with a Mach port (0x3403) which does not have any send rights.  This is not going to work.  Callback function: 0x7fff2c57e744
[XCUITest] Failed to check out repository into /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer: Could not create working directory (Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “RoutingHTTPServer” in the folder “Checkouts”." UserInfo={NSFilePath=/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer, NSUnderlyingError=0x7f916141e8b0 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}})
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[XCUITest] Fetching dependencies
[XCUITest] *** Checking out CocoaAsyncSocket at "7.6.3"
[XCUITest] *** Checking out YYCache at "1.0.5"
[XCUITest] *** Checking out RoutingHTTPServer at "v1.0.1"
[XCUITest] *** Cloning CocoaAsyncSocket
[XCUITest] *** Cloning YYCache
[XCUITest] 2020-03-02 13:34:00.976 carthage[852:14402] *** WARNING: CFMachPortSetInvalidationCallBack() called on a CFMachPort with a Mach port (0x4903) which does not have any send rights.  This is not going to work.  Callback function: 0x7fff2c57e744
[XCUITest] Failed to check out repository into /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer: Could not create working directory (Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “RoutingHTTPServer” in the folder “Checkouts”." UserInfo={NSFilePath=/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer, NSUnderlyingError=0x7ff1ff63e6f0 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}})
[BaseDriver] Event 'wdaStartFailed' logged at 1583136241278 (13:34:01 GMT+0530 (IST))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: "Command 'Scripts/bootstrap.sh -d' exited with code 1".
[XCUITest] Quitting and uninstalling WebDriverAgent
[XCUITest] Shutting down sub-processes
[XCUITest] Removing WDA application from device
[BaseDriver] Event 'wdaStartAttempted' logged at 1583136252365 (13:34:12 GMT+0530 (IST))
[XCUITest] Retrying WDA startup (2 of 2)
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[XCUITest] Fetching dependencies
[XCUITest] *** Checking out RoutingHTTPServer at "v1.0.1"
[XCUITest] *** Checking out YYCache at "1.0.5"
[XCUITest] *** Checking out CocoaAsyncSocket at "7.6.3"
[XCUITest] *** Cloning CocoaAsyncSocket
[XCUITest] *** Cloning YYCache
[XCUITest] 2020-03-02 13:34:12.687 carthage[880:15170] *** WARNING: CFMachPortSetInvalidationCallBack() called on a CFMachPort with a Mach port (0x4d03) which does not have any send rights.  This is not going to work.  Callback function: 0x7fff2c57e744
[XCUITest] Failed to check out repository into /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer: Could not create working directory (Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “RoutingHTTPServer” in the folder “Checkouts”." UserInfo={NSFilePath=/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer, NSUnderlyingError=0x7f9fca424bf0 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}})
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[XCUITest] Fetching dependencies
[XCUITest] *** Checking out CocoaAsyncSocket at "7.6.3"
[XCUITest] *** Checking out RoutingHTTPServer at "v1.0.1"
[XCUITest] *** Checking out YYCache at "1.0.5"
[XCUITest] *** Cloning CocoaAsyncSocket
[XCUITest] *** Cloning YYCache
[XCUITest] 2020-03-02 13:34:13.305 carthage[893:15231] *** WARNING: CFMachPortSetInvalidationCallBack() called on a CFMachPort with a Mach port (0x4c03) which does not have any send rights.  This is not going to work.  Callback function: 0x7fff2c57e744
[XCUITest] Failed to check out repository into /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer: Could not create working directory (Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “RoutingHTTPServer” in the folder “Checkouts”." UserInfo={NSFilePath=/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer, NSUnderlyingError=0x7fce50446280 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}})
[BaseDriver] Event 'wdaStartFailed' logged at 1583136253560 (13:34:13 GMT+0530 (IST))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: "Command 'Scripts/bootstrap.sh -d' exited with code 1".
[XCUITest] Quitting and uninstalling WebDriverAgent
[XCUITest] Shutting down sub-processes
[XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: "Command 'Scripts/bootstrap.sh -d' exited with code 1".
[XCUITest]     at quitAndUninstall (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:488:13)
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[iOSLog] Stopping iOS log capture
[BaseDriver] Event 'newSessionStarted' logged at 1583136254648 (13:34:14 GMT+0530 (IST))
[W3C] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: "Command 'Scripts/bootstrap.sh -d' exited with code 1".
[W3C]     at quitAndUninstall (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:488:13)
[HTTP] <-- POST /wd/hub/session 500 26783 ms - 870
[HTTP]

**Comment by mykola-mokhnach** [comment]
I understand. I mean it is obvious that if something is complaining about missing permissions then the right way to fix it would be to grant these missing permissions.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
