### ISSUE TITLE
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8200} 

### ISSUE THREAD

**Issue by keerthanK** [appium/appium#14029]
Hello, I have a problem running on my device, in the logs it gives me the following error: 

```[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8200} [debug] [W3C (ee54c772)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8200 [debug] [W3C (ee54c772)]     at JWProxy.command ```

## Environment

* Appium version : v1.15.1
* Desktop OS/version used to run Appium: macOS mojave
* Node.js version (unless using Appium.app|exe): v8.10.0
* Npm version : v5.6.0
* Android version : v9

Note:
[raw.txt](https://github.com/appium/appium/files/4291167/raw.txt)
 logs attached

**Comment by mykola-mokhnach** [comment]
In the log I can observe that 

```
[35m[HTTP][39m [37m<-- GET /wd/hub/session/ee54c772-1c5c-4092-ac57-a89523e1c776/screenshot [39m[32m200[39m [90m502 ms - 36886[39m
[35m[HTTP][39m [90m[39m
2020-03-05 11:07:10 INFO  OptimusController:193 - cucumber.runtime.ScenarioImpl@78c1372d---BOT registered successfully for -- 8a3a24e
ChangeName
[35m[Logcat][39m Logcat terminated with code 0, signal null
[debug] [35m[Instrumentation][39m The process has exited with code 0
```

Which means the connrefused error is the expected one here. Although it is not clear why the instrumentation process has been terminated. The logcat output might contain more details though.

**Comment by mykola-mokhnach** [comment]
Also Appium requires node10 since v1.15

**Comment by keerthanK** [comment]
I upgraded node to v10.13.0
appium to v1.160

Still same issue

app will just install and uninstall with the error 

``` Got an unexpected response with status undefined: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8200}```

**Comment by mykola-mokhnach** [comment]
I'm still expecting to see the logcat output

**Comment by keerthanK** [comment]
```[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8200}
[debug] [W3C (95a9730b)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8200
[debug] [W3C (95a9730b)]     at JWProxy.command (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:239:13)
[HTTP] <-- POST /wd/hub/session/95a9730b-c72b-4648-a7bf-79bdfceb7357/element 500 24 ms - 572
[HTTP] 

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8200
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'ip-192-168-5-58.ap-south-1.compute.internal', ip: '192.168.5.58', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.3', java.version: '1.8.0_202'
Driver info: io.appium.java_client.android.AndroidDriver```


is this any capability issue?

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing more to do on this issue report without the logcat output. I would be happy to reopen it as soon as it is available.

**Comment by aomegax** [comment]
I have the same problem:

Appium 1.17.1
Desktop OS/version used to run Appium: Ubuntu
Node.js version (unless using Appium.app|exe): v10.19.0
Npm version : v6.14.5
Android version : v6 / v9

and the error is the following:
`
Process: io.appium.uiautomator2.server, PID: 32108
06-11 15:19:59.373 32108 32122 E AndroidRuntime: java.lang.IllegalStateException: UiAutomation not connected!
06-11 15:19:59.373 32108 32122 E AndroidRuntime: 	at android.app.UiAutomation.throwIfNotConnectedLocked(UiAutomation.java:971)
06-11 15:19:59.373 32108 32122 E AndroidRuntime: 	at android.app.UiAutomation.disconnect(UiAutomation.java:237)
06-11 15:19:59.373 32108 32122 E AndroidRuntime: 	at android.app.Instrumentation.finish(Instrumentation.java:199)
06-11 15:19:59.373 32108 32122 E AndroidRuntime: 	at androidx.test.runner.MonitoringInstrumentation.finish(MonitoringInstrumentation.java:364)
06-11 15:19:59.373 32108 32122 E AndroidRuntime: 	at androidx.test.runner.AndroidJUnitRunner.finish(AndroidJUnitRunner.java:412)
06-11 15:19:59.373 32108 32122 E AndroidRuntime: 	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:401)
06-11 15:19:59.373 32108 32122 E AndroidRuntime: 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1886)
06-11 17:04:36.690  3360  3360 E AndroidRuntime: FATAL EXCEPTION: main
`

The error occurs when I execute findElements using UiSelector(). In particular from Appium log:
`
[debug] [W3C (8718ae99)] Calling AppiumDriver.findElements() with args: ["-android uiautomator","new UiSelector().packageName(\"it.app.my\")","8718ae99-0bf0-43ce-9eb0-45e6ed57663c"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [WD Proxy] Matched '/elements' to command name 'findElements'
[debug] [WD Proxy] Proxying [POST /elements] to [POST http://127.0.0.1:8200/wd/hub/session/81dcaad7-b31f-4c04-a756-9b50a4ab3a52/elements] with body: {"strategy":"-android uiautomator","selector":"new UiSelector().packageName(\"it.app.my\")","context":"","multiple":true}
[WD Proxy] Got response with unknown status: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8200}
[debug] [W3C (8718ae99)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8200
[debug] [W3C (8718ae99)]     at JWProxy.command (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:266:13)
[HTTP] <-- POST /wd/hub/session/8718ae99-0bf0-43ce-9eb0-45e6ed57663c/elements 500 47 ms - 572
`

After connection I executed screenshot without any problems.

Thanks.
