### ISSUE TITLE
Clear text function is not working with iOS 13.x

### ISSUE THREAD

**Issue by agammishra12** [appium/appium#14025]

**Comment by VenkateshPS** [comment]
put more details (environment and Appium logs). Works fine for me tested on iOS 13.x with Xcode 11 latest appium@beta

**Comment by mykola-mokhnach** [comment]
Closed as incomplete

**Comment by Nishant-Taksande** [comment]
@VenkateshPS  its working fine with Appium v1.17.0-beta.1

**Comment by Nishant-Taksande** [comment]
Thanks @VenkateshPS

**Comment by agammishra12** [comment]
@VenkateshPS Its working fine with Appium v1.17.0-beta.1

**Comment by agammishra12** [comment]
Thanks @VenkateshPS
