### ISSUE TITLE
Webview not available for iOS hybrid app for real device and also for xcode iOS simulator

### ISSUE THREAD

**Issue by shagupta92042** [appium/appium#14024]
## The problem

We are automating a hybrid iOS using appium and running it on a real device iPhone.
Webview is not available for iOS hybrid app for real device , it is showing only Native view . Therefore i tried to execute the same test on iOS simulator ( iphone 11 pro max - 13.3 ) as we don't IWDP for the same but we could not find the webview in simulator as well . 
Whereas we can see the webview in safari for iOS and also our automation is running fine on android device and we can identify the webview for android device . 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0
* Last Appium version that did not exhibit the issue (if applicable): 1.8.0-beta4
* Desktop OS/version used to run Appium: macOS catalina 10.15.3
* Node.js version (unless using Appium.app|exe): 13.8.0
* Npm or Yarn package manager:
* Mobile platform/version under test: 13.3 ( simulator )
* Real device or emulator/simulator: simulator iphone 11 pro max
* Appium CLI or Appium.app|exe: Appium CLI 1.16.0
* Appium Java Client : 7.1.0
## Link to Appium logs

https://gist.github.com/shagupta92042/3cc7b1beebe199f34aedcc1b850da8a1

## Code To Reproduce Issue [ Good To Have ]

DesiredCapabilities capabilities = new DesiredCapabilities();

			 capabilities.setCapability("platformName", "iOS");
			 capabilities.setCapability("automationName", "XCUITest");
			 capabilities.setCapability("deviceName", "ION's iPhone");
			 capabilities.setCapability("deviceName", "iPhone 11 Pro Max");
capabilities.setCapability("bundleId","com.iontrading.ionweb.agt");
capabilities.setCapability("platformVersion", "12.4.5");
capabilities.setCapability("udid", "EE33F4B2-08FF-4A40-A5DF-EAD7B0B47C1B");
 capabilities.setCapability("app","/Users/webtrading/ATP/ios shell distributable/ionweb 2020-02-13 15-57-16_Pats_test_Resolver/ionweb.ipa");
			 capabilities.setCapability("noReset","true");
			 capabilities.setCapability("setValue",true);
			 capabilities.setCapability("useJSONSource","true");
 mobileDriver = new AppiumDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);

**Comment by mykola-mokhnach** [comment]
Pleas try appium@beta

**Comment by mykola-mokhnach** [comment]
Closed because of no response
