### ISSUE TITLE
Element id is missing on the same screen in different context

### ISSUE THREAD

**Issue by deepu451** [appium/appium#14027]
## The problem

Element id is missing on the same screen in different context.

## Environment

* Appium version 1.16.0
* Last Appium version that did not exhibit the issue (if applicable):1.14.2
* Desktop OS/version used to run Appium: MAC OS 10.15.3
* Node.js version :10.15.3
* Npm or Yarn package manager:npm version 6.9.0
* Mobile platform/version under test: iOS App
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

## Details

Scenario 1:
if the the logged user has some date associated with patients, navigate to the patients screen it will show the toggle button of the user associated patients and the id of toggle button is visible.
scenario 2:
if the the logged user has no date associated with patients, navigate to the patients screen it will show all the patients list and toggle button for all patient is not visible. and when we click on the all patient toggle button it will go to My patient toggle button and its id is missing, where as in the scenario  1 it is visible.

## Link to Appium logs

https://github.com/deepu451/Appium-issues/blob/master/Appium%20log

driver. get page source on the issue screen:
https://github.com/deepu451/Appium-issues/blob/master/driverPage%20source
i have used the emoji "👉🏼" in the pagesource, the element id where it is showing and not showing.
## Code To Reproduce Issue [ Good To Have ]

<img width="1680" alt="Screenshot 2020-03-04 at 11 23 27 PM" src="https://user-images.githubusercontent.com/27261343/75910523-ff8e7e80-5e73-11ea-9b03-16d781b9dcfd.png">
<img width="1680" alt="Screenshot 2020-03-04 at 11 23 59 PM" src="https://user-images.githubusercontent.com/27261343/75910528-03220580-5e74-11ea-94e0-e239f9875366.png">

**Comment by mykola-mokhnach** [comment]
Appium simply reflects what it gets from XCTest (and XCTest gets the data from the accessibility framework). Consider reporting the issue to Apple.

Closed as third party issue

**Comment by VenkateshPS** [comment]
https://feedbackassistant.apple.com/feedback/7615883
