### ISSUE TITLE
Unable to create a new remote session: Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec

### ISSUE THREAD

**Issue by p0well493** [appium/appium#14031]
## The problem
I am still new to Appium and trying to run a few native applications on my mobile. I executed the calculator application successfully earlier BUT encountered the issue below after a few days. Kindly help with the issue and let me know what action or changes should I need to do. Thank you and good day. Please see the issue below. Thanks

## Environment

Appium version : v.1.16.0
Desktop OS/version used to run Appium: Windows 10 Pro 64-bit(10.0, Build 17763)
Node.js version : v10.16.3
Npm : 6.9.0
Mobile platform/version under test: Android/v6.0
Real device or emulator/simulator: Huawei 
Appium CLI or Appium : Appium desktop

## Details

AppiumDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\mycv21cg\\android-sdk\\platform-tools\\adb.exe -P 5037 -s LHTDU17601000834 shell pm install -r /data/local/tmp/appium_cache/0cc1725a60a05dbb5d0d09256f2fc6ece7e3b10f.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'uiautomator2ServerInstallTimeout' capability

## Link to Appium logs

Please see the Appium Log attached
[appium-server-logs March 5.txt](https://github.com/appium/appium/files/4291715/appium-server-logs.March.5.txt)

## Code To Reproduce Issue [ Good To Have ]

package appiumtest;

import java.net.URL;

import org.openqa.selenium.By;
import org.openqa.selenium.remote.DesiredCapabilities;

import io.appium.java_client.AppiumDriver;
import io.appium.java_client.MobileElement;

public class CalculatorTest {

	static AppiumDriver<MobileElement>driver;
	
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		try {
			openCalculator();
		} catch (Exception exp) {
			// TODO Auto-generated catch block
			
			System.out.println(exp.getCause());
			System.out.println(exp.getMessage());
			exp.printStackTrace();
			
		}

	}
	
	public static void openCalculator() throws Exception {
		
		DesiredCapabilities cap = new DesiredCapabilities();
		
		cap.setCapability("deviceName", "CAM-L21");
		cap.setCapability("udid", "LHTDU17601000834");
		cap.setCapability("platformName", "Android");
		cap.setCapability("platformVersion", "6.0");
		cap.setCapability("automationName", "UiAutomator2");
		cap.setCapability("appPackage", "com.android.calculator2");
		cap.setCapability("appActivity", "com.android.calculator2.Calculator");
		
		URL url = new URL("http://127.0.0.1:4723/wd/hub");
		
		driver = new AppiumDriver<MobileElement>(url, cap);
		
		System.out.println("Application Test Started...");
		
		MobileElement nine = driver.findElement(By.id("com.android.calculator2:id/digit9"));
		MobileElement plus = driver.findElement(By.id("com.android.calculator2:id/plus"));
		MobileElement eight = driver.findElement(By.id("com.android.calculator2:id/digit8"));
		MobileElement equals = driver.findElement(By.id("com.android.calculator2:id/equal"));
		
		MobileElement result = driver.findElement(By.className("android.widget.EditText"));
		
		nine.click();
		plus.click();
		eight.click();
		equals.click();
		
		String reslt = result.getText();
		System.out.println("\n Result is : "+reslt);
		System.out.println("\n Completed Testing Automation");
								
		
	}
	
	

}

**ECLIPSE LOGS:**
java.lang.reflect.InvocationTargetException
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\mycv21cg\\android-sdk\\platform-tools\\adb.exe -P 5037 -s LHTDU17601000834 shell pm install -r /data/local/tmp/appium_cache/0cc1725a60a05dbb5d0d09256f2fc6ece7e3b10f.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'uiautomator2ServerInstallTimeout' capability
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'MYCV21CG_NB', ip: '172.20.10.8', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
Driver info: driver.version: AppiumDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\mycv21cg\\android-sdk\\platform-tools\\adb.exe -P 5037 -s LHTDU17601000834 shell pm install -r /data/local/tmp/appium_cache/0cc1725a60a05dbb5d0d09256f2fc6ece7e3b10f.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'uiautomator2ServerInstallTimeout' capability
    at getResponseForW3CError (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'MYCV21CG_NB', ip: '172.20.10.8', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
Driver info: driver.version: AppiumDriver
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\mycv21cg\\android-sdk\\platform-tools\\adb.exe -P 5037 -s LHTDU17601000834 shell pm install -r /data/local/tmp/appium_cache/0cc1725a60a05dbb5d0d09256f2fc6ece7e3b10f.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'uiautomator2ServerInstallTimeout' capability
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'MYCV21CG_NB', ip: '172.20.10.8', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
Driver info: driver.version: AppiumDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\mycv21cg\\android-sdk\\platform-tools\\adb.exe -P 5037 -s LHTDU17601000834 shell pm install -r /data/local/tmp/appium_cache/0cc1725a60a05dbb5d0d09256f2fc6ece7e3b10f.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'uiautomator2ServerInstallTimeout' capability
    at getResponseForW3CError (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'MYCV21CG_NB', ip: '172.20.10.8', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
Driver info: driver.version: AppiumDriver
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:323)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:86)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:96)
	at appiumtest.CalculatorTest.openCalculator(CalculatorTest.java:45)
	at appiumtest.CalculatorTest.main(CalculatorTest.java:19)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
	... 13 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\mycv21cg\\android-sdk\\platform-tools\\adb.exe -P 5037 -s LHTDU17601000834 shell pm install -r /data/local/tmp/appium_cache/0cc1725a60a05dbb5d0d09256f2fc6ece7e3b10f.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'uiautomator2ServerInstallTimeout' capability
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'MYCV21CG_NB', ip: '172.20.10.8', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
Driver info: driver.version: AppiumDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\mycv21cg\\android-sdk\\platform-tools\\adb.exe -P 5037 -s LHTDU17601000834 shell pm install -r /data/local/tmp/appium_cache/0cc1725a60a05dbb5d0d09256f2fc6ece7e3b10f.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'uiautomator2ServerInstallTimeout' capability
    at getResponseForW3CError (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	... 18 more

**Comment by mykola-mokhnach** [comment]
Have you actually tried to do what's advised in the error message? How much time the apk installation takes if done manually from the terminal?

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by De254030** [comment]
Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)'

i am also getting this issue

**Comment by shibupanda** [comment]
>Error executing adbExec. Original error: 'Command 'C:\\Users\\mycv21cg\\android-sdk\\platform-tools\\adb.exe -P 5037 -s LHTDU17601000834 forward --remove tcp\:8200' exited with code 1'; Stderr: 'adb.exe: error: listener 'tcp:8200' not found'; Code: '1''

@p0well493 
Your issue seems because of port(8200) conflict as uiautomator2 use 8200 as default port.
Could you please use systemPort = <use some free port>

@De254030 
Could you please share the complete appium server logs using gist.

**Comment by De254030** [comment]
@shibupanda how to use system port , can you please let me know

**Comment by Ranjith1140** [comment]
> ## The problem
> I am still new to Appium and trying to run a few native applications on my mobile. I executed the calculator application successfully earlier BUT encountered the issue below after a few days. Kindly help with the issue and let me know what action or changes should I need to do. Thank you and good day. Please see the issue below. Thanks
> 
> ## Environment
> Appium version : v.1.16.0
> Desktop OS/version used to run Appium: Windows 10 Pro 64-bit(10.0, Build 17763)
> Node.js version : v10.16.3
> Npm : 6.9.0
> Mobile platform/version under test: Android/v6.0
> Real device or emulator/simulator: Huawei
> Appium CLI or Appium : Appium desktop
> 
> ## Details
> AppiumDriver
> remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\Users\mycv21cg\android-sdk\platform-tools\adb.exe -P 5037 -s LHTDU17601000834 shell pm install -r /data/local/tmp/appium_cache/0cc1725a60a05dbb5d0d09256f2fc6ece7e3b10f.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'uiautomator2ServerInstallTimeout' capability
> 
> ## Link to Appium logs
> Please see the Appium Log attached
> [appium-server-logs March 5.txt](https://github.com/appium/appium/files/4291715/appium-server-logs.March.5.txt)
> 
> ## Code To Reproduce Issue [ Good To Have ]
> package appiumtest;
> 
> import java.net.URL;
> 
> import org.openqa.selenium.By;
> import org.openqa.selenium.remote.DesiredCapabilities;
> 
> import io.appium.java_client.AppiumDriver;
> import io.appium.java_client.MobileElement;
> 
> public class CalculatorTest {
> 
> ```
> static AppiumDriver<MobileElement>driver;
> 
> public static void main(String[] args) {
> 	// TODO Auto-generated method stub
> 	
> 	try {
> 		openCalculator();
> 	} catch (Exception exp) {
> 		// TODO Auto-generated catch block
> 		
> 		System.out.println(exp.getCause());
> 		System.out.println(exp.getMessage());
> 		exp.printStackTrace();
> 		
> 	}
> 
> }
> 
> public static void openCalculator() throws Exception {
> 	
> 	DesiredCapabilities cap = new DesiredCapabilities();
> 	
> 	cap.setCapability("deviceName", "CAM-L21");
> 	cap.setCapability("udid", "LHTDU17601000834");
> 	cap.setCapability("platformName", "Android");
> 	cap.setCapability("platformVersion", "6.0");
> 	cap.setCapability("automationName", "UiAutomator2");
> 	cap.setCapability("appPackage", "com.android.calculator2");
> 	cap.setCapability("appActivity", "com.android.calculator2.Calculator");
> 	
> 	URL url = new URL("http://127.0.0.1:4723/wd/hub");
> 	
> 	driver = new AppiumDriver<MobileElement>(url, cap);
> 	
> 	System.out.println("Application Test Started...");
> 	
> 	MobileElement nine = driver.findElement(By.id("com.android.calculator2:id/digit9"));
> 	MobileElement plus = driver.findElement(By.id("com.android.calculator2:id/plus"));
> 	MobileElement eight = driver.findElement(By.id("com.android.calculator2:id/digit8"));
> 	MobileElement equals = driver.findElement(By.id("com.android.calculator2:id/equal"));
> 	
> 	MobileElement result = driver.findElement(By.className("android.widget.EditText"));
> 	
> 	nine.click();
> 	plus.click();
> 	eight.click();
> 	equals.click();
> 	
> 	String reslt = result.getText();
> 	System.out.println("\n Result is : "+reslt);
> 	System.out.println("\n Completed Testing Automation");
> 							
> 	
> }
> ```
> 
> }
> 
> **ECLIPSE LOGS:**
> java.lang.reflect.InvocationTargetException
> org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\Users\mycv21cg\android-sdk\platform-tools\adb.exe -P 5037 -s LHTDU17601000834 shell pm install -r /data/local/tmp/appium_cache/0cc1725a60a05dbb5d0d09256f2fc6ece7e3b10f.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'uiautomator2ServerInstallTimeout' capability
> Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
> System info: host: 'MYCV21CG_NB', ip: '172.20.10.8', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
> Driver info: driver.version: AppiumDriver
> remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\Users\mycv21cg\android-sdk\platform-tools\adb.exe -P 5037 -s LHTDU17601000834 shell pm install -r /data/local/tmp/appium_cache/0cc1725a60a05dbb5d0d09256f2fc6ece7e3b10f.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'uiautomator2ServerInstallTimeout' capability
> at getResponseForW3CError (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
> at asyncHandler (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
> at process._tickCallback (internal/process/next_tick.js:68:7)
> Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
> System info: host: 'MYCV21CG_NB', ip: '172.20.10.8', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
> Driver info: driver.version: AppiumDriver
> at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
> at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
> Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\Users\mycv21cg\android-sdk\platform-tools\adb.exe -P 5037 -s LHTDU17601000834 shell pm install -r /data/local/tmp/appium_cache/0cc1725a60a05dbb5d0d09256f2fc6ece7e3b10f.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'uiautomator2ServerInstallTimeout' capability
> Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
> System info: host: 'MYCV21CG_NB', ip: '172.20.10.8', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
> Driver info: driver.version: AppiumDriver
> remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\Users\mycv21cg\android-sdk\platform-tools\adb.exe -P 5037 -s LHTDU17601000834 shell pm install -r /data/local/tmp/appium_cache/0cc1725a60a05dbb5d0d09256f2fc6ece7e3b10f.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'uiautomator2ServerInstallTimeout' capability
> at getResponseForW3CError (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
> at asyncHandler (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
> at process._tickCallback (internal/process/next_tick.js:68:7)
> Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
> System info: host: 'MYCV21CG_NB', ip: '172.20.10.8', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
> Driver info: driver.version: AppiumDriver
> at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
> at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
> at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
> at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
> at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
> at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:323)
> at org.openqa.selenium.remote.RemoteWebDriver.(RemoteWebDriver.java:131)
> at io.appium.java_client.DefaultGenericMobileDriver.(DefaultGenericMobileDriver.java:37)
> at io.appium.java_client.AppiumDriver.(AppiumDriver.java:86)
> at io.appium.java_client.AppiumDriver.(AppiumDriver.java:96)
> at appiumtest.CalculatorTest.openCalculator(CalculatorTest.java:45)
> at appiumtest.CalculatorTest.main(CalculatorTest.java:19)
> Caused by: java.lang.reflect.InvocationTargetException
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> at java.lang.reflect.Method.invoke(Unknown Source)
> at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
> ... 13 more
> Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\Users\mycv21cg\android-sdk\platform-tools\adb.exe -P 5037 -s LHTDU17601000834 shell pm install -r /data/local/tmp/appium_cache/0cc1725a60a05dbb5d0d09256f2fc6ece7e3b10f.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'uiautomator2ServerInstallTimeout' capability
> Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
> System info: host: 'MYCV21CG_NB', ip: '172.20.10.8', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
> Driver info: driver.version: AppiumDriver
> remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\Users\mycv21cg\android-sdk\platform-tools\adb.exe -P 5037 -s LHTDU17601000834 shell pm install -r /data/local/tmp/appium_cache/0cc1725a60a05dbb5d0d09256f2fc6ece7e3b10f.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'uiautomator2ServerInstallTimeout' capability
> at getResponseForW3CError (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
> at asyncHandler (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
> at process._tickCallback (internal/process/next_tick.js:68:7)
> at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
> at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
> at java.lang.reflect.Constructor.newInstance(Unknown Source)
> at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
> at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
> at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
> at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
> at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
> at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
> at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
> at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
> at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
> at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
> at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
> at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
> at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
> ... 18 more

im also facing same issue plzz help me nd thank you.

**Comment by Jagadambika** [comment]
I'm also facing the same issue almost like the one you specified i got post which i added an extra dependency for the same calculator prgm
 <dependency>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.7.0</version>
    </dependency>

but then i got a new error java,lang.reflect.InvocationTargetException,Unable to create a new remote session......
Even I'm new to this,hope someone comes up with a solution to resolve it

**Comment by prince-baweja-tivo** [comment]
Hi everyone,
I was also facing this issue -  An unknown server-side error occurred while processing the command. Original error: Error executing adbExec.

**The solution that worked for me.** 

My device storage was almost full. Only ( ~200 MB) space was free. So, I freed up some space. And then tried. 
And then - Appium worked fine for me.

PS : My senior suggested this solution to me.

**Comment by mehtaanish01** [comment]
Hey! I just got it resolved.
Please enable USB debugging(security).

For redmi mobile.
Settings-->aditional settings-->developer options-->enable USB debugging(security){Allow granting permission and simulating input via usb debugging}
