### ISSUE TITLE
IOS/MAC/APPIUM_Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

### ISSUE THREAD

**Issue by u546012** [appium/appium#14038]
## The problem

Tried to run appium code in real device,
Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
2020-03-06 12:36:36.852 xcodebuild[32489:1245406] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/980163/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fb7bf5bdda0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

## Environment

* Appium version (or git revision) that exhibits the issue:1.15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:mac 10.14.5
* Node.js version (unless using Appium.app|exe):11.9
* Npm or Yarn package manager:6.5
* Mobile platform/version under test:ios 12.2
* Real device or emulator/simulator:real device
* Appium CLI or Appium.app|exe:appium.app

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
[HTTP] {"desiredCapabilities":{"app":"/Users/980163/Library/Developer/Xcode/DerivedData/UICatalog-enmuviheleajsocklcjtdcyfvbro/Build/Products/Debug-iphoneos/UICatalog.app","platformVersion":"12.2","xcodeOrgId":"PQK5J86Z5Z","bundleId":"com.tcs.mobility.UICatalog","useNewWDA":"true","platformName":"IOS","udid":"84889a161bc6c9ae83195656a6b52dae237b4b31","deviceName":"iPhone38","xcodeSigningId":"iPhone Developer"},"capabilities":{"firstMatch":[{"appium:app":"/Users/980163/Library/Developer/Xcode/DerivedData/UICatalog-enmuviheleajsocklcjtdcyfvbro/Build/Products/Debug-iphoneos/UICatalog.app","appium:bundleId":"com.tcs.mobility.UICatalog","appium:deviceName":"iPhone38","platformName":"ios","appium:platformVersion":"12.2","appium:udid":"84889a161bc6c9ae83195656a6b52dae237b4b31","appium:useNewWDA":"true","appium:xcodeOrgId":"PQK5J86Z5Z","appium:xcodeSigningId":"iPhone Developer"}]}}
[W3C] Calling AppiumDriver.createSession() with args: [{"app":"/Users/980163/Library/Developer/Xcode/DerivedData/UICatalog-enmuviheleajsocklcjtdcyfvbro/Build/Products/Debug-iphoneos/UICatalog.app","platformVersion":"12.2","xcodeOrgId":"PQK5J86Z5Z","bundleId":"com.tcs.mobility.UICatalog","useNewWDA":"true","platformName":"IOS","udid":"84889a161bc6c9ae83195656a6b52dae237b4b31","deviceName":"iPhone38","xcodeSigningId":"iPhone Developer"},null,{"firstMatch":[{"appium:app":"/Users/980163/Library/Developer/Xcode/DerivedData/UICatalog-enmuviheleajsocklcjtdcyfvbro/Build/Products/Debug-iphoneos/UICatalog.app","appium:bundleId":"com.tcs.mobility.UICatalog","appium:deviceName":"iPhone38","platformName":"ios","appium:platformVersion":"12.2","appium:udid":"84889a161bc6c9ae83195656a6b52dae237b4b31","appium:useNewWDA":"true","appium:xcodeOrgId":"PQK5J86Z5Z","appium:xcodeSigningId":"iPhone Developer"}]}]
[BaseDriver] Event 'newSessionRequested' logged at 1583478376417 (12:36:16 GMT+0530 (IST))
[Appium] DeprecationWarning: 'automationName' capability was not provided. Future versions of Appium will require 'automationName' capability to be set for iOS sessions.
[Appium] Requested iOS support with version >= 10, using 'XCUITest' driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Appium v1.15.1 creating new XCUITestDriver (v2.133.1) session
[BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[BaseDriver] Creating session with W3C capabilities: {
[BaseDriver]   "alwaysMatch": {
[BaseDriver]     "platformName": "ios",
[BaseDriver]     "appium:app": "/Users/980163/Library/Developer/Xcode/DerivedData/UICatalog-enmuviheleajsocklcjtdcyfvbro/Build/Products/Debug-iphoneos/UICatalog.app",
[BaseDriver]     "appium:bundleId": "com.tcs.mobility.UICatalog",
[BaseDriver]     "appium:deviceName": "iPhone38",
[BaseDriver]     "appium:platformVersion": "12.2",
[BaseDriver]     "appium:udid": "84889a161bc6c9ae83195656a6b52dae237b4b31",
[BaseDriver]     "appium:useNewWDA": "true",
[BaseDriver]     "appium:xcodeOrgId": "PQK5J86Z5Z",
[BaseDriver]     "appium:xcodeSigningId": "iPhone Developer"
[BaseDriver]   },
[BaseDriver]   "firstMatch": [
[BaseDriver]     {}
[BaseDriver]   ]
[BaseDriver] }
[BaseDriver] Capability 'useNewWDA' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Session created with session id: 5ea6949d-386c-4676-9a1c-8f31520de549
[XCUITest] Current user: '980163'
[XCUITest] Available devices: 84889a161bc6c9ae83195656a6b52dae237b4b31
[XCUITest] Creating iDevice object with udid '84889a161bc6c9ae83195656a6b52dae237b4b31'
[XCUITest] Determining device to run tests on: udid: '84889a161bc6c9ae83195656a6b52dae237b4b31', real device: true
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1583478376457 (12:36:16 GMT+0530 (IST))
[BaseDriver] Using local app '/Users/980163/Library/Developer/Xcode/DerivedData/UICatalog-enmuviheleajsocklcjtdcyfvbro/Build/Products/Debug-iphoneos/UICatalog.app'
[BaseDriver] Event 'appConfigured' logged at 1583478376459 (12:36:16 GMT+0530 (IST))
[XCUITest] Checking whether app '/Users/980163/Library/Developer/Xcode/DerivedData/UICatalog-enmuviheleajsocklcjtdcyfvbro/Build/Products/Debug-iphoneos/UICatalog.app' is actually present on file system
[XCUITest] App is present
[BaseDriver] Event 'resetStarted' logged at 1583478376461 (12:36:16 GMT+0530 (IST))
[XCUITest] Reset: running ios real device reset flow
[BaseDriver] Event 'resetComplete' logged at 1583478376461 (12:36:16 GMT+0530 (IST))
[XCUITest] Crash reports root '/Users/980163/Library/Logs/CrashReporter/MobileDevice/iPhone38' does not exist. Got nothing to gather.
[BaseDriver] Event 'logCaptureStarted' logged at 1583478387232 (12:36:27 GMT+0530 (IST))
[XCUITest] Setting up real device
[XCUITest] Verifying application platform
[XCUITest] CFBundleSupportedPlatforms: ["iPhoneOS"]
[XCUITest] Reset requested. Removing app with id 'com.tcs.mobility.UICatalog' from the device
[XCUITest] Installing '/Users/980163/Library/Developer/Xcode/DerivedData/UICatalog-enmuviheleajsocklcjtdcyfvbro/Build/Products/Debug-iphoneos/UICatalog.app' on device with UUID '84889a161bc6c9ae83195656a6b52dae237b4b31'...
[XCUITest] Pushed the app files successfully after 3441ms
[XCUITest] Installation is successful after 4160ms
[XCUITest] The app has been installed successfully.
[BaseDriver] Event 'appInstalled' logged at 1583478391983 (12:36:31 GMT+0530 (IST))
[XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-webdriveragent'
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'
[XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[DevCon Factory] Requesting connection for device 84889a161bc6c9ae83195656a6b52dae237b4b31 on local port 8100, device port 8100
[DevCon Factory] Cached connections count: 1
[DevCon Factory] Found cached connections on port #8100: ["EBCF7DB6-50C1-4F2B-94DF-C55DC17DC37A:8100"]
[DevCon Factory] Port #8100 is busy
[DevCon Factory] Successfully requested the connection for 84889a161bc6c9ae83195656a6b52dae237b4b31:8100
[XCUITest] Parsed BUILD_DIR configuration value: '/Users/980163/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz/Build/Products'
[XCUITest] Got derived data root: '/Users/980163/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz'
[XCUITest] Starting WebDriverAgent initialization with the synchronization key '/Users/980163/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz'
[XCUITest] Capability 'useNewWDA' set to true, so uninstalling WDA before proceeding
[XCUITest] Shutting down sub-processes
[XCUITest] No WDAs on the device.
[BaseDriver] Event 'wdaUninstalled' logged at 1583478393590 (12:36:33 GMT+0530 (IST))
[XCUITest] Trying to start WebDriverAgent 1 times with 10000ms interval
[XCUITest] These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
[BaseDriver] Event 'wdaStartAttempted' logged at 1583478393590 (12:36:33 GMT+0530 (IST))
[XCUITest] Launching WebDriverAgent on the device
[WebDriverAgent] Fetching dependencies
[WebDriverAgent] Dependencies up-to-date
[XCUITest] Killing running processes 'xcodebuild.*84889a161bc6c9ae83195656a6b52dae237b4b31' for the device 84889a161bc6c9ae83195656a6b52dae237b4b31...
[XCUITest] 'pgrep -ifn xcodebuild.*84889a161bc6c9ae83195656a6b52dae237b4b31' didn't detect any matching processes. Return code: 1
[XCUITest] Generating xcode config file for orgId 'PQK5J86Z5Z' and signingId 'iPhone Developer'
[XCUITest] Writing xcode config file to /var/folders/gt/hnb185t90kl1nq7nfqgt8jfsz_2nc5/T/202026-24010-1dkc8c3.bc95k/appium-temp.xcconfig
[XCUITest] Using Xcode configuration file: '/var/folders/gt/hnb185t90kl1nq7nfqgt8jfsz_2nc5/T/202026-24010-1dkc8c3.bc95k/appium-temp.xcconfig'
[XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath /Users/980163/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz -destination id=84889a161bc6c9ae83195656a6b52dae237b4b31 IPHONEOS_DEPLOYMENT_TARGET=12.2 -xcconfig /var/folders/gt/hnb185t90kl1nq7nfqgt8jfsz_2nc5/T/202026-24010-1dkc8c3.bc95k/appium-temp.xcconfig GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-webdriveragent'
[XCUITest] Output from xcodebuild will only be logged if any errors are present there. To change this, use 'showXcodeLog' desired capability
[XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@84889...] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@84889...] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[XCUITest] Log file for xcodebuild test: /Users/980163/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz/Logs/Test/Test-WebDriverAgentRunner-2020.03.06_12-36-34-+0530.xcresult/Staging/2_Test/Diagnostics/WebDriverAgentRunner-E6BC06E8-97B8-4064-93B9-B362BEC76E06/WebDriverAgentRunner-E72CAD82-05AB-46F4-8518-9CB7047A49C4/Session-WebDriverAgentRunner-2020-03-06_123635-iFk36p.log
[Xcode] 2020-03-06 12:36:35.227 xcodebuild[32483:1245296] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/980163/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fee0b904630 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode] 
[Xcode] 
[Xcode] Test session results, code coverage, and logs:
[Xcode] 	/Users/980163/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz/Logs/Test/Test-WebDriverAgentRunner-2020.03.06_12-36-34-+0530.xcresult
[Xcode] 
[Xcode] 
[Xcode] Testing failed:
[Xcode] 	No profiles for 'com.facebook.WebDriverAgentRunner.xctrunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.facebook.WebDriverAgentRunner.xctrunner'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
[Xcode] 	WebDriverAgentRunner:
[Xcode] 		WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file. The file doesn’t exist. (Underlying error: The operation couldn’t be completed. No such file or directory)))
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[Xcode] Testing started on 'iPhone38'
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[XCUITest] Launching WebDriverAgent on the device
[WebDriverAgent] Fetching dependencies
[WebDriverAgent] Dependencies up-to-date
[XCUITest] Killing running processes 'xcodebuild.*84889a161bc6c9ae83195656a6b52dae237b4b31' for the device 84889a161bc6c9ae83195656a6b52dae237b4b31...
[XCUITest] 'pgrep -ifn xcodebuild.*84889a161bc6c9ae83195656a6b52dae237b4b31' didn't detect any matching processes. Return code: 1
[XCUITest] Using Xcode configuration file: '/var/folders/gt/hnb185t90kl1nq7nfqgt8jfsz_2nc5/T/202026-24010-1dkc8c3.bc95k/appium-temp.xcconfig'
[XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath /Users/980163/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz -destination id=84889a161bc6c9ae83195656a6b52dae237b4b31 IPHONEOS_DEPLOYMENT_TARGET=12.2 -xcconfig /var/folders/gt/hnb185t90kl1nq7nfqgt8jfsz_2nc5/T/202026-24010-1dkc8c3.bc95k/appium-temp.xcconfig GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-webdriveragent'
[XCUITest] Output from xcodebuild will only be logged if any errors are present there. To change this, use 'showXcodeLog' desired capability
[XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@84889...] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@84889...] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@84889...] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[XCUITest] Log file for xcodebuild test: /Users/980163/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz/Logs/Test/Test-WebDriverAgentRunner-2020.03.06_12-36-36-+0530.xcresult/Staging/2_Test/Diagnostics/WebDriverAgentRunner-79ACD006-F966-4475-B627-114FE64750B1/WebDriverAgentRunner-9FBE332C-935A-41E2-A706-05EE917E363A/Session-WebDriverAgentRunner-2020-03-06_123636-Xs5nSG.log
[Xcode] 2020-03-06 12:36:36.852 xcodebuild[32489:1245406] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/980163/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fb7bf5bdda0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode] 
[Xcode] 
[Xcode] Test session results, code coverage, and logs:
[Xcode] 	/Users/980163/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz/Logs/Test/Test-WebDriverAgentRunner-2020.03.06_12-36-36-+0530.xcresult
[Xcode] 
[Xcode] 
[Xcode] Testing failed:
[Xcode] 	No profiles for 'com.facebook.WebDriverAgentRunner.xctrunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.facebook.WebDriverAgentRunner.xctrunner'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
[Xcode] 	WebDriverAgentRunner:
[Xcode] 		WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file. The file doesn’t exist. (Underlying error: The operation couldn’t be completed. No such file or directory)))
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[Xcode] Testing started on 'iPhone38'
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[BaseDriver] Event 'wdaStartFailed' logged at 1583478396904 (12:36:36 GMT+0530 (IST))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[XCUITest] xcodebuild error message:
[XCUITest] 
[XCUITest] 2020-03-06 12:36:36.852 xcodebuild[32489:1245406] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/980163/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fb7bf5bdda0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[XCUITest] Test session results, code coverage, and logs:
[XCUITest] 	/Users/980163/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz/Logs/Test/Test-WebDriverAgentRunner-2020.03.06_12-36-36-+0530.xcresult
[XCUITest] Testing failed:
[XCUITest] 	No profiles for 'com.facebook.WebDriverAgentRunner.xctrunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.facebook.WebDriverAgentRunner.xctrunner'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
[XCUITest] 	WebDriverAgentRunner:
[XCUITest] 		WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file. The file doesn’t exist. (Underlying error: The operation couldn’t be completed. No such file or directory)))
[XCUITest] ** TEST EXECUTE FAILED **
[XCUITest] Testing started on 'iPhone38'. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[XCUITest] Quitting and uninstalling WebDriverAgent
[XCUITest] Shutting down sub-processes
[XCUITest] No WDAs on the device.
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[XCUITest] xcodebuild error message:
[XCUITest] 
[XCUITest] 2020-03-06 12:36:36.852 xcodebuild[32489:1245406] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/980163/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fb7bf5bdda0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[XCUITest] Test session results, code coverage, and logs:
[XCUITest] 	/Users/980163/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz/Logs/Test/Test-WebDriverAgentRunner-2020.03.06_12-36-36-+0530.xcresult
[XCUITest] Testing failed:
[XCUITest] 	No profiles for 'com.facebook.WebDriverAgentRunner.xctrunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.facebook.WebDriverAgentRunner.xctrunner'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
[XCUITest] 	WebDriverAgentRunner:
[XCUITest] 		WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file. The file doesn’t exist. (Underlying error: The operation couldn’t be completed. No such file or directory)))
[XCUITest] ** TEST EXECUTE FAILED **
[XCUITest] Testing started on 'iPhone38'. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[XCUITest]     at quitAndUninstall (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/driver.js:527:15)
[DevCon Factory] Releasing connections for 84889a161bc6c9ae83195656a6b52dae237b4b31 device on any port number
[DevCon Factory] Found cached connections to release: ["84889a161bc6c9ae83195656a6b52dae237b4b31:8100"]
[DevCon Factory] Releasing the listener for '84889a161bc6c9ae83195656a6b52dae237b4b31:8100'
[DevCon Factory] Cached connections count: 1
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[BaseDriver] Event 'newSessionStarted' logged at 1583478397128 (12:36:37 GMT+0530 (IST))
[W3C] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[W3C] xcodebuild error message:
[W3C] 
[W3C] 2020-03-06 12:36:36.852 xcodebuild[32489:1245406] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/980163/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fb7bf5bdda0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[W3C] Test session results, code coverage, and logs:
[W3C] 	/Users/980163/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz/Logs/Test/Test-WebDriverAgentRunner-2020.03.06_12-36-36-+0530.xcresult
[W3C] Testing failed:
[W3C] 	No profiles for 'com.facebook.WebDriverAgentRunner.xctrunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.facebook.WebDriverAgentRunner.xctrunner'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
[W3C] 	WebDriverAgentRunner:
[W3C] 		WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file. The file doesn’t exist. (Underlying error: The operation couldn’t be completed. No such file or directory)))
[W3C] ** TEST EXECUTE FAILED **
[W3C] Testing started on 'iPhone38'. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[W3C]     at quitAndUninstall (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/driver.js:527:15)
[HTTP] <-- POST /wd/hub/session 500 20713 ms - 4280
[HTTP] 

## Code To Reproduce Issue [ Good To Have ]

DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone38");
capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME,"IOS");
capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "12.2");
capabilities.setCapability(MobileCapabilityType.UDID, "XXXXXX");
capabilities.setCapability("useNewWDA","true");
capabilities.setCapability("bundleId", "XXXXXX");
capabilities.setCapability("xcodeOrgId", "XXXXXX");
capabilities.setCapability("xcodeSigningId", "iPhone Developer");
capabilities.setCapability(MobileCapabilityType.APP, "/Users/980163/Library/Developer/Xcode/DerivedData/UICatalog-enmuviheleajsocklcjtdcyfvbro/Build/Products/Debug-iphoneos/UICatalog.app");
IOSDriver<IOSElement>driver = new IOSDriver<>(new URL("http://0.0.0.0:4723/wd/hub"),capabilities);

**Comment by mykola-mokhnach** [comment]
> [Xcode] No profiles for 'com.facebook.WebDriverAgentRunner.xctrunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.facebook.WebDriverAgentRunner.xctrunner'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.

This is a signing issue. Make sure you follow the signing [tutorial](https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md) from the error message above.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
