### ISSUE TITLE
[help request] out of screen element click fail in IOS 12.4.1

### ISSUE THREAD

**Issue by cheffey** [appium/appium#14030]
## The problem
Out of screen element could be detected, but when click it instead of scroll element into view and click, it scroll to the top.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16 and 1.10
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator: 
iPhone Xs Max IOS 12.4.1 real device and Simulator
iPhone X IOS 11.4.1 real device and Simulator
* Appium CLI or Appium.app|exe:

## Details
It seems that WDA have different logistic for IOS 13.0+. I'm not sure if this is a third party issue. But I can't request help from WDA, if this problem is as common as it appear to be. Is there a way to work around that issue?
<img width="1440" alt="Screen Shot 2020-03-05 at 3 51 02 PM" src="https://user-images.githubusercontent.com/56681567/75959882-0fe93c80-5efa-11ea-864f-6c8bf335c92c.png">

## Link to Appium logs
https://gist.github.com/cheffey/ca304149ea72dd24a5216389ce33440e

## Code To Reproduce Issue [ Good To Have ]
out of screen element find by accessibilityId then element.click();

**Comment by cheffey** [comment]
If I alter WDA code:
  if (SYSTEM_VERSION_GREATER_THAN_OR_EQUAL_TO(@"13.0")) {
to
  if (SYSTEM_VERSION_GREATER_THAN_OR_EQUAL_TO(@"11.0")) {
the click could work for my app. But it's not best solution for me when I use cloud testing

**Comment by KazuCocoa** [comment]
Do you have a chance to run it with Xcode 10.x?

```
[iOSSim] Constructing iOS simulator for Xcode version 11.1 with udid 'C5B1B593-478D-4DC3-9C2A-70E0482EE9EC'
```

**Comment by mykola-mokhnach** [comment]
The reason to have this workaround were XCTest bugs related to element coordinates resolution (simply said the `tap` method was not tapping at the proper coordinates). Apple has addressed this bug recently, so that we could switch back to the native tap implemntation. As a workaround I would try `mobile: mobileTouchAndHold` endpoint. By giving the duration value of 100-125ms (0.1-0.125) it would behave same as `tap`

**Comment by cheffey** [comment]
> Do you have a chance to run it with Xcode 10.x?
> 
> ```
> [iOSSim] Constructing iOS simulator for Xcode version 11.1 with udid 'C5B1B593-478D-4DC3-9C2A-70E0482EE9EC'
> ```
Thanks for your sugestion. But I don't think that would help even xcode 10.x works.
The problem would still remains for cloud testing, which their xcode version I have no control over.

**Comment by cheffey** [comment]
> The reason to have this workaround were XCTest bugs related to element coordinates resolution (simply said the `tap` method was not tapping at the proper coordinates). Apple has addressed this bug recently, so that we could switch back to the native tap implementation. As a workaround I would try `mobile: mobileTouchAndHold` endpoint. By giving the duration value of 100-125ms (0.1-0.125) it would behave same as `tap`

Thanks for your help. I take your suggestion and use following code to mimic click:
        JavascriptExecutor js = (JavascriptExecutor) context.device.driver;
        Map<String, Object> args = new HashMap<>();
        args.put("element", ((MobileElement) element).getId());
        args.put("duration", 0.5);//could try 0.1-0.2
        js.executeScript("mobile: touchAndHold", args);

Addtional to that, I test when element A is overlapped and covered by other element B, then touch and hold A would click B.
This could solve most of the case, but for reason I don't know when touch and hold some out-of-screen element it still could mis click other element instead.

**Comment by mykola-mokhnach** [comment]
> This could solve most of the case, but for reason I don't know when touch and hold some out-of-screen element it still could mis click other element instead.

this must be an XCTest issue then. WDA does not do anything on top of calling the touchAndHold methods

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by cheffey** [comment]
hello

**Comment by cheffey** [comment]
> The reason to have this workaround were XCTest bugs related to element coordinates resolution (simply said the `tap` method was not tapping at the proper coordinates). Apple has addressed this bug recently, so that we could switch back to the native tap implementation. As a workaround I would try `mobile: mobileTouchAndHold` endpoint. By giving the duration value of 100-125ms (0.1-0.125) it would behave same as `tap`

I'm not sure what you mean by that. Do you mean you added the alternative click route for IOS 12 because the native api have bug? In my case, in IOS 12 it use "fb_performAppiumTouchActions" to click which in my case won't perform click, is a bug. But when I switch to native api by altering WDA code, it works. How could I keep my eyes on the agenda of possibility of switching back to the native api?
