### ISSUE TITLE
Query: Web-View- UiAutomator1 working as native but not with UiAutomator2

### ISSUE THREAD

**Issue by ahmadsayeed3** [appium/appium#14033]
## The problem

I am trying to automate an application which contains web-view. Unfortunately it has only one context **NATIVE** and do not contains web-view context. I don't have access to modify anything in the build(application).

So I inspected the web-view as native using uiAutomatorViewer created XPath and ran with automationName **uiAutomator1**. It worked. But I am not able to perform the same with uiAutomator2. 

With uiautomator1 I am getting complete page source as XML but with uiAutomator2 not getting.

**is It possible to get the same result with uiAutomator2???**

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows
* Node.js version (unless using Appium.app|exe): 10.x
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Android > 6
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

**Comment by mykola-mokhnach** [comment]
Please attach the required information: server logs with both automation backends, and page source snapshots

**Comment by ahmadsayeed3** [comment]
Please find page source and Appium logs with both uiAutomator1 and uiAutomator2

**UiAutomator2-Appium-Logs**
https://gist.github.com/ahmadsayeed3/c2142964ab43ca29379f1086e050b0cc


**UIAutomator2-Page-Source**
https://gist.github.com/ahmadsayeed3/82c6fa58ce45cab45f3d1b2da8ded51a

**UiAutomator1-Appium-logs**
https://gist.github.com/ahmadsayeed3/9c5f4ffae99dd294c510c6d8cd88b3dd

**UiAutomator1-Page-Source**
https://gist.github.com/ahmadsayeed3/f25723efb5d1d01e86bd483c60f2d11b

**Comment by mykola-mokhnach** [comment]
I don't see any possibilities that could change the page source generation procedure from Appium side. It is built from what UIA2 returns to us
Consider switching to web view context to make that working or reporting the issue to Google.

One more thing you could try is to set the `enableMultiWindows` setting to `true` and check what page source would be generated then

**Comment by ahmadsayeed3** [comment]
Hi Mykola, thank you for the quick response. I could find how to implement "**enableMultiWindows**" setting,

But using this piece of snippet It is working.
**driver.setSetting(Setting.ALLOW_INVISIBLE_ELEMENTS, true);**

No need to observe the impact.
Thank you for your guidance.
