### ISSUE TITLE
Could not set value # in field

### ISSUE THREAD

**Issue by Phoenix124** [appium/appium#14036]
## The problem

Could not enter value # in field due daemon error

## Environment

* Appium: 1.16.0
* MacOS 10.14.5
* Node - 10.15
* Npm - 6.13.7
* ios 12.4
* Emulator
* Appium cli

## Details
Try to set value `#` in field and got error
```
Error Domain=XCTDaemonErrorDomain Code=14 "Timed out after waiting 1.0s for KeyEventCompleted after sending event for '#'." UserInfo={NSLocalizedDescription=Timed out after waiting 1.0s for KeyEventCompleted after sending event for '#'.} (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: '', ip: 'f, os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.5', java.version: '1.8.0_131'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities {acceptSslCerts: true, app: /Users/user/builds/K6MygzXy..., applicationCacheEnabled: true, autoWebview: false, automationName: XCUITest, browserName: , commandTimeouts: 600000, databaseEnabled: true, deviceName: iPhone 8 Plus, disableWindowAnimation: false, ensureCleanSession: false, fullReset: false, isHeadless: false, javascriptEnabled: true, language: ru_RU, launchTimeout: 600000, locale: ru_RU, locationContextEnabled: false, mjpegServerPort: 9105, networkConnectionEnabled: true, newCommandTimeout: 600, noReset: false, pageLoadStrategy: eager, permissions: {".., platform: MAC, platformName: iOS, platformVersion: 12.4, proxyEverything: false, safariGarbageCollect: false, shouldUseSingletonTestManager: false, showIOSLog: true, showXcodeLog: false, skipLogCapture: true, takesScreenshot: true, udid: 923EA4D1-5CE8-4EFD-836E-E84..., useJSONSource: true, useNewWDA: true, usePrebuiltWDA: true, version: 12.4, waitForQuiescence: false, wdaLocalPort: 8105, webStorageEnabled: true, xcodeOrgId: }
Session ID: 9ab4b320-9ecc-4ef0-8750-19b2f59d504d
```

**Comment by mykola-mokhnach** [comment]
> Error Domain=XCTDaemonErrorDomain Code=14 "Timed out after waiting 1.0s for KeyEventCompleted after sending event for '#'." UserInfo={NSLocalizedDescription=Timed out after waiting 1.0s for KeyEventCompleted after sending event for '#'.} (WARNING: The server did not provide any stacktrace information)

As you can see from the message the error is returned by XCTest. I don't think we can do something about it from Appium side.With mentioning that before I've seen several issues related to text input into web view being in native mode and/or when the application under test was not up to date with the recent Xcode SDK.

**Comment by Phoenix124** [comment]
> > Error Domain=XCTDaemonErrorDomain Code=14 "Timed out after waiting 1.0s for KeyEventCompleted after sending event for '#'." UserInfo={NSLocalizedDescription=Timed out after waiting 1.0s for KeyEventCompleted after sending event for '#'.} (WARNING: The server did not provide any stacktrace information)
> 
> As you can see from the message the error is returned by XCTest. I don't think we can do something about it from Appium side. Worth mentioning that before I've seen several issues related to text input into a web view being in native mode and/or when the application under test was not up to date with the recent Xcode SDK.

Well, thanks, but i work with native app
Probably it caused by some parallel execution, because on the single device mode - it's ok

**Comment by mykola-mokhnach** [comment]
> Probably it caused by some parallel execution, because on the single device mode - it's ok

Most likely it is. I would try to limit the concurrence or consider more powerful hardware.

Closed as third party issue
