### ISSUE TITLE
Driver.getDeviceTime() gives different output for iOS and Android

### ISSUE THREAD

**Issue by sara1710** [appium/appium#14039]
## The problem

Driver.getDeviceTime() gives different output for iOS and Android

## Details

Driver.getDeviceTime() gives different output for iOS and Android

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Please provide an appropriate issue description, which includes the required information
