### ISSUE TITLE
Test Flight distribution profile apps will it work with appium?  

### ISSUE THREAD

**Issue by apiautoamtion** [appium/appium#14037]
I am trying to automate hybrid app from TestFlight which is enabled with distribution profile. I am able to download the app from TestFlight but not seeing web views. Can anyone help me here?

Capabilities uses:
cap.setCapability("app", "TestFlightURL");

Note: I am trying automation without provisioning profile devices.

**Comment by imurchie** [comment]
Can you post the Appium server logs (as a link to a [gist](https://gist.github.com)? "Not seeing web views" is too vague to say anything at all.

**Comment by mykola-mokhnach** [comment]
Are you sure the web views are debuggable? Are they visible in Safari remote debugger?

**Comment by apiautoamtion** [comment]
Safari remote debugger is enabled, but not seeing webviews in safari ->develop options

**Comment by mykola-mokhnach** [comment]
> Safari remote debugger is enabled, but not seeing webviews in safari ->develop options

if Safari does not see it then there unfortunately is no way to make it visible in Appium. Make sure the web view is properly configured for debugging

**Comment by apiautoamtion** [comment]
Here I need help to understand with destruction signed cert apps can't we automate though Appium?

**Comment by amedvedjev** [comment]
Problem not in certificate. Problem that developers distributing RELEASE version of your app where debug is closed and thus you can see webView of your app.

**Comment by apiautoamtion** [comment]
Can you please help me to understand ?

**Comment by amedvedjev** [comment]
There are different versions of application can build for. Release or debug. In your case it looks like it is release. You cant do anything with it with webView. Ask your app developers for help.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
