### ISSUE TITLE
Is it possible to get Simulator time, cause the Driver.getDeviceTime() is returning different time when running in Browserstack than the time present in the Screen

### ISSUE THREAD

**Issue by sara1710** [appium/appium#14040]

**Comment by imurchie** [comment]
Any further info? What is the server time? What is the time on the sim? What is the time returned?

Please attach the full logs as a link to a [gist](https://gist.github.com) so we have something to go on.

**Comment by imurchie** [comment]
For simulators Appium just pulls the time of the machine the simulator is running on. If BS is doing something to make them not the same, they need to provide a patch to get the correct date/time.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
