### ISSUE TITLE
(Appium v1.17.0-beta.1) Multiple Devices bug

### ISSUE THREAD

**Issue by ranv1r** [appium/appium#14044]
## The problem

Running Appium v1.17.0-beta.1 with multiple devices throws error. Details mentioned below.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.17.0-beta.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-141-generic x86_64)
* Node.js version (unless using Appium.app|exe): v12.14.1
* Npm or Yarn package manager: 6.13.4
* Mobile platform/version under test: Android SDK 26
* Real device or emulator/simulator: Real Device LGE Nexus 5x
* Appium CLI or Appium.app|exe: Appium CLI

## Details

I am using the Appium Python Client to create driver using `webdriver.Remote(url, desired_caps)`

I think the problem lies in the fact that  'error: more than one device/emulator' is not handled for android devices in this version.

This command throws following error:
`selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error getting device API level. Original error: Error executing adbExec. Original error: 'Command '/home/hs/headspinio-pboxagent/android/platform-tools/adb -P 5037 shell getprop ro.build.version.sdk' exited with code 1'; Stderr: 'error: more than one device/emulator'; Code: '1'`

## Link to Appium logs

https://gist.github.com/ranv1r/92be75b70878ed0a6d215ba8aff8230a

**Comment by mykola-mokhnach** [comment]
Linking https://github.com/appium/appium-adb/pull/505

**Comment by mykola-mokhnach** [comment]
cc @imurchie

**Comment by mykola-mokhnach** [comment]
The patch has been published to appium@beta
