### ISSUE TITLE
unable to use execute_script run JavaScript on android device

### ISSUE THREAD

**Issue by KevinChan168** [appium/appium#14047]
## The problem

from appium import webdriver
init the driver,then use:
driver.execute_script("alert('shit')")
it returned :
appdata\local\programs\python\python37\lib\site-packages\selenium\webdriver\remote\webdriver.py:636: in execute_script
    'args': converted_args})['value']
appdata\local\programs\python\python37\lib\site-packages\selenium\webdriver\remote\webdriver.py:321: in execute
    self.error_handler.check_response(response)
appdata\local\programs\python\python37\lib\site-packages\appium\webdriver\errorhandler.py:29: in check_response
    raise wde
appdata\local\programs\python\python37\lib\site-packages\appium\webdriver\errorhandler.py:24: in check_response
    super(MobileErrorHandler, self).check_response(response)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <appium.webdriver.errorhandler.MobileErrorHandler object at 0x000001A1F121A8D0>
response = {'status': 405, 'value': '{"value":{"error":"unknown method","message":"Method is not implemented","stacktrace":"NotIm...nCallback (timers.js:696:18)\\n    at tryOnImmediate (timers.js:667:5)\\n    at processImmediate (timers.js:649:5)"}}'}

>       raise exception_class(message, screen, stacktrace)
E       selenium.common.exceptions.WebDriverException: Message: Method is not implemented

## Environment

* Appium version (or git revision) that exhibits the issue:1.15.1
* Desktop OS/version used to run Appium: windows 10
* Node.js version (unless using Appium.app|exe): 10.15.3
* Npm or Yarn package manager: 6.4.1
* Mobile platform/version under test: android 10
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: appium desktop verison

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/KevinChan168/ba949cfb738326080b0d39069af70203

**Comment by mykola-mokhnach** [comment]
The error is expected. Javascript execution is not supported in native context and makes no sense.

**Comment by KevinChan168** [comment]
> The error is expected. Javascript execution is not supported in native context and makes no sense.

I need to switch to webview then use execute_script to run javascript?
how about ios? seems ios does not have driver.switch_to.context(context_name)

**Comment by mykola-mokhnach** [comment]
both android and iOS drivers have a possibility to switch contexts. Simply make sure the web view is debuggable and that you are running the most recent server version (preferably appium@beta)

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
