### ISSUE TITLE
Empty Source Code (getSourceCode) on iOS 13.3 (vs. 13.2) (cannot find element)

### ISSUE THREAD

**Issue by mdblr** [appium/appium#14056]
## The problem

Having issues locating elements on iOS 13.3 device. When querying the source code, it appears that the XML is shell-like compared when running on iOS 13.2 (real devices). For this reason, the element I am searching for is not found, despite verifying the opposite.

## Environment
```
appium: v1.15.0 // Samd occurs on 1.16.0
appium-xcuitest-driver: v3.17.0 // Same occurs on older versions as well
node: v10.16.3
desktop: Mac OS Mojave / Cent OS
iOS: 13.3
```
## Link to Appium logs

[Page Source XML on iOS 13.3](https://gist.github.com/mdblr/6c3f2151b2929cea3d97fd628ede70b1)
[Page Source XML on iOS 13.2](https://gist.github.com/mdblr/4efbd60f5549b994fb80627461689d6e)
[Error in Appium logs](https://gist.github.com/mdblr/cb808a544bfc0216a6a57c74054872cb)

**Comment by dpgraham** [comment]
@mdblr the source xml is _different_ but are you sure that it's _wrong_? The source of iOS Applications sometimes changes between iOS versions.

**Comment by mdblr** [comment]
Thanks for your help and quick response!

Yes, I am saying that the XML is incorrect.

I am not sure what you mean here:
> Applications sometimes changes between iOS versions.

I am running the same ipa so, in this way, the build did not change from device to device. Does that answer your question or can you elaborate more?

**Comment by dpgraham** [comment]
Not the application, but rather the application source can change. It's hard to tell without screenshots if the source is being reported incorrectly.

**Comment by mdblr** [comment]
Oh, I see, thanks.

So there are multiple measures taken to ensure that the last page has disappeared, the page transition is complete, and the new page is ready to interact with. This last condition waits for the element, in this case, a form input. In the video and screenshots, everything appears normal. But, after 30s, 60s, 120s, etc., the appium logs continue to throw the error that I attached above. Despite what is visually available after these long timeouts, the shell-like XML does not reflect it when running on iOS 13.3 for some reason.

**Comment by KazuCocoa** [comment]
What the result of `mobile: source` with `{"format":"description"}` argument? example: https://github.com/appium/appium/issues/13595#issuecomment-553298730

If the result is the same, I guess the root cause is in XCTest framework

**Comment by mdblr** [comment]
@KazuCocoa It appears the same as the xml error result: [json gist](https://gist.github.com/mdblr/20e9137c2720cd9f5a5770d40a0a00dd).

I found a [possibly relevant thread](https://forums.developer.apple.com/thread/127246) on apple forums.

**Comment by KazuCocoa** [comment]
Thanks for the check
