### ISSUE TITLE
TypeError: androidHelpers.getJavaVersion is not a function

### ISSUE THREAD

**Issue by jknanda78** [appium/appium#14058]
## The problem

Encountered `TypeError` as `getJavaVersion` helper function is removed from `appium-android-driver` package. 
```
  androidHelpers.getJavaVersion(false).then(function tryInstall (version) {
                 ^
TypeError: androidHelpers.getJavaVersion is not a function
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.12.1
* Desktop OS/version used to run Appium: Mac
* Node.js version (unless using Appium.app|exe): v11.4.0
* Npm or Yarn package manager: Yarn

## Details

Here is the PR that removed `getJavaVersion` helper function https://github.com/appium/appium-android-driver/pull/610/files/ce5fff780ce65893b0eb6a594dafb456df32ade8#diff-97eeab6ebf462ba97a11ee0221ddaf13L86.

## Code To Reproduce Issue [ Good To Have ]
`yarn add appium@1.12.1`

**Comment by mykola-mokhnach** [comment]
it looks like yarn does not respect shrinkwrap rules and we don't support it officially. Please install Appium with npm. Also, it is recommended to use the most recent server version. v 1.12  is old and out of date

**Comment by jknanda78** [comment]
Thanks @mykola-mokhnach. I saw that just wanted to confirm.
