### ISSUE TITLE
Unable to launch app after  Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":xx

### ISSUE THREAD

**Issue by siddhantraut** [appium/appium#14057]
## The problem
Unable to launch app , need to trust again and again.

WDA signing successful, no error while launching 

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version 1.13 command line . MAC os 10.13
* Last Appium version that did not exhibit the issue (if applicable): same on MAC os 10.13
* Desktop OS/version used to run Appium: MAC OS 10.14
* Node.js version (unless using Appium.app|exe): 6.14.2
* Npm or Yarn package manager:
* Mobile platform/version under test: iOS 12.3.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

## Details

Unable to launch app after success WDA started successfully. Need to Trust app manually again and again to run test

## Link to Appium logs

[debug] [XCUITest] WebDriverAgent information:
[debug] [XCUITest] {
[debug] [XCUITest]   "state": "success",
[debug] [XCUITest]   "os": {
[debug] [XCUITest]     "name": "iOS",
[debug] [XCUITest]     "version": "12.3.1",
[debug] [XCUITest]     "sdkVersion": "12.0"
[debug] [XCUITest]   },
[debug] [XCUITest]   "ios": {
[debug] [XCUITest]     "simulatorVersion": "12.3.1",
[debug] [XCUITest]     "ip": "169.254.197.244"
[debug] [XCUITest]   },
[debug] [XCUITest]   "build": {
[debug] [XCUITest]     "upgradedAt": "1583972407873",
[debug] [XCUITest]     "time": "Mar 11 2020 20:35:31",
[debug] [XCUITest]     "productBundleIdentifier": "com.facebook.WebDriverAgentRunner"
[debug] [XCUITest]   }
[debug] [XCUITest] }
[debug] [XCUITest] WebDriverAgent successfully started after 7539ms
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1583973918786 (20:45:18 GMT-0400 (Eastern Daylight Time))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":

**Comment by KazuCocoa** [comment]
>. Unable to launch app after success WDA started successfully. Need to Trust app manually again and again to run test

Apple requires it.

You can install an app with the signature and trust it once before running Appium/WDA. Then, the signature can keep trust status on your device until you uninstall all of the apps signed by the signature. Or you can avoid the requirement using a paid account.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by siddhantraut** [comment]
I was uninstalling app   @aftermethod, app certificate also getting removed every time.
