### ISSUE TITLE
iOS/WDA - wrong elements coordinates for system popups while in landscape orientation

### ISSUE THREAD

**Issue by mstrelex** [appium/appium#14055]
## The problem

App in **landscape** orientation displays a system popup (e.g. location access).
Elements coordinates obtained from DOM are wrong - as if the app would be displayed in **portrait**.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16 / 1.17
* Device : iPad 5th gen (MP2G2CL/A) v13.2.2
* Last Appium version that did not exhibit the issue (if applicable): N/A

## Details

Built an empty app that works only in **Landscape** mode.
Added a button that requests location authorization and triggers a system popup:

```
var locationManager = CLLocationManager()
locationManager.requestAlwaysAuthorization() 
```

The problem is with **WDA**
It returns the coordinates of the elements in popup as if the app would be in landscape orientation.

DOM XMLs (extracted from WDA via http://localhost:8100/source):

App DOM: https://gist.github.com/mstrelex/6c5da82eec3d8a0c00158b28cd1d87ae
App DOM + Popup: https://gist.github.com/mstrelex/e58c6118df0c0abf2a20c3ca6379d37f

Server Log: https://gist.github.com/mstrelex/ab105269988c7b0de2f2c500ccca72e9

Images from Appium Desktop Inspector:

https://ibb.co/fCCB2b7

**Comment by mykola-mokhnach** [comment]
These coordinates are returned by XCTest. Unfortunately there is nothing we can do about it from Appium side.

**Comment by mstrelex** [comment]
Got it, thanks @mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
YW. It's a very old XCTest bug, but nobody cares. I've reported it 4 years ago for the first time: https://github.com/facebookarchive/WebDriverAgent/issues/300
