### ISSUE TITLE
Appium Deep linking getting error: for driver.get() method

### ISSUE THREAD

**Issue by Soham05** [appium/appium#14064]
## The problem

I am trying to implement deep linking and access deep links via driver.get() method using Appium java.
I am getting an exception 
Exception in thread "main" org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: URI and package arguments are required.
Please can someone help me out to resolve the same.

## Environment

* Appium version that exhibits the issue: 1.5.1
* Last Appium version that did not exhibit the issue (if applicable): - 
* Desktop OS/version used to run Appium: Mac Desktop Appium server
* Node.js version (unless using Appium.app|exe): 
* Npm or Yarn package manager:
* Mobile platform/version under test: Android emulator version 9
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Appium App

## Details

I tried the same code on my Ubuntu VM and ran into the same issue.
## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!
Here is my log file:
https://gist.github.com/Soham05/b5664a0bae92d5f37abd34f7cf9d1105

## Code To Reproduce Issue [ Good To Have ]

import io.appium.java_client.AppiumDriver;
import io.appium.java_client.MobileElement;
import io.appium.java_client.android.Activity;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.android.AndroidElement;
import io.appium.java_client.remote.MobileCapabilityType;
import optimizations.ProductMapping;
import org.openqa.selenium.By;
import org.openqa.selenium.html5.Location;
import org.openqa.selenium.remote.DesiredCapabilities;

import java.io.IOException;
import java.net.URL;
import java.util.HashMap;
import java.util.concurrent.TimeUnit;

public class AutomationTest {

    private AndroidDriver<AndroidElement> driver;

    //private AppiumDriver driver;
    private final String HOME_ACTIVITY = "com.thehomedepot.home.activities.HomeActivity";
    private final String PACKAGE = "com.thehomedepot";

    private Double longitude;
    private Double latitude;
    private String query;

    private boolean hasDeepLink;

    /**
     * Default Constructor
     * @param query
     * @param longitude
     * @param latitude
     */
    public AutomationTest(String query, Double longitude, Double latitude, Boolean hasDeepLink){
        this.query = query;
        this.latitude = latitude;
        this.longitude = longitude;
        this.hasDeepLink = hasDeepLink;
    }

    /**
     * Setup for the Appium Test
     * @throws IOException
     */
    public void setUp() throws IOException {
        System.out.println("Search Query::" + query);
        System.out.println("Latitude::" + latitude);
        System.out.println("Longitude::" + longitude);
        DesiredCapabilities desiredCapabilities = new DesiredCapabilities();

        desiredCapabilities.setCapability("platformName", "Android");
        desiredCapabilities.setCapability("deviceName", "emulator-5554");
        desiredCapabilities.setCapability("platformVersion", "9");
        desiredCapabilities.setCapability("autoGrantPermissions", "true");
        desiredCapabilities.setCapability("noResetValue", "true");

        // Ensures Appium does not reset the screen if no command is received
        desiredCapabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 300);

        URL url = new URL("http://127.0.0.1:4723/wd/hub");

        driver = new AndroidDriver<AndroidElement>(url, desiredCapabilities);
        System.out.println("Setup Completed successfully");
        HashMap<String, String> map = new HashMap<>();
        map.put("url","https://www.homedepot.com/p/Korky-Beehive-Max-Toilet-Plunger-99-12A/203765220&ved=2ahUKEwjYmrnhhJHoAhVbGTQIHY7_AZ8Q0gIoADAAegQIBhAH&usg=AOvVaw0rrboarSYniq0zqL55V4Pk");
        map.put("package","com.thehomedepot");

        //driver.get("https://www.homedepot.com/p/Korky-Beehive-Max-Toilet-Plunger-99-12A/203765220&ved=2ahUKEwjYmrnhhJHoAhVbGTQIHY7_AZ8Q0gIoADAAegQIBhAH&usg=AOvVaw0rrboarSYniq0zqL55V4Pk");
        **driver.get("https://google.com");**  
}
}

**Comment by KazuCocoa** [comment]
Could you share the full appium server log as GIST?
