### ISSUE TITLE
All outgoing email has been globally disabled by an administrator. No email notifications of any kind will be sent.

### ISSUE THREAD

**Issue by davenh0000** [appium/appium#14068]
Hi, I am new here. I am trying to create an account or Sign up on https://discuss.appium.io/. After signing up I saw this message All outgoing email has been globally disabled by an administrator. No email notifications of any kind will be sent. Please help me as I am trying to learn appium with lots of questions thanks.

**Comment by mykola-mokhnach** [comment]
> All outgoing email has been globally disabled by an administrator. No email notifications of any kind will be sent

The forum is set up this way not to annoy users with unnecessary email spam.

Closed as not an issue
