### ISSUE TITLE
 [XCUITest] No available web pages: Could not connect to a valid app after 20 tries. [debug] [XCUITest] No web frames found

### ISSUE THREAD

**Issue by siddhantraut** [appium/appium#14069]
## The problem
[debug] [XCUITest] No available web pages: Could not connect to a valid app after 20 tries. [debug] [XCUITest] No web frames found

## Environment

* Appium version (or git revision) that exhibits the issue:1.17.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MAC 10.14.5
* Node.js version (unless using Appium.app|exe): 
* Npm or Yarn package manager:6.9.0
* Mobile platform/version under test:12.4
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

**ios_webkit_debug_proxy 1.8.6
Built with libimobiledevice v1.2.1, libplist v2.1.0**

## Details

- Launch app successfully
- Click on Login in link [Native_App] **[able to interact with native_app provision profile is ok]**
- Login page display [WebView]
- Unable to getContext for WebView - getting o/p No Web frame found

## Link to Appium logs
```
[debug] [RemoteDebugger] Checking for bundle identifiers: process-SafariViewService, com.apple.SafariViewService, *, com.xxxxxx.xxxxxxxxx.xxxxxxxx
[debug] [RemoteDebugger] Found app id key 'PID:306' for bundle 'process-SafariViewService'
[debug] [RemoteDebugger] Found app id key 'PID:306' for bundle 'com.apple.SafariViewService'
[debug] [RemoteDebugger] Found app id key 'PID:306' for bundle '*'
[debug] [RemoteDebugger] Found app id key 'PID:306' for bundle 'com.mobileApp.myaccount.enterprise'
[debug] [RemoteDebugger] Trying out the possible app ids: PID:306 (try #1 of 20)
[debug] [RemoteDebugger] Skipping app 'PID:306' because it is not active
[debug] [RemoteDebugger] Current applications available:
[debug] [RemoteDebugger]     Application: 'PID:306'
[debug] [RemoteDebugger]         id: "PID:306"
[debug] [RemoteDebugger]         isProxy: true
[debug] [RemoteDebugger]         name: "com.apple.WebKit.WebContent"
[debug] [RemoteDebugger]         bundleId: "com.apple.WebKit.WebContent"
[debug] [RemoteDebugger]         hostId: "PID:302"
[debug] [RemoteDebugger]         isActive: 0
[debug] [RemoteDebugger]         isAutomationEnabled: false
[debug] [RemoteDebugger]     Application: 'PID:302'
[debug] [RemoteDebugger]         id: "PID:302"
[debug] [RemoteDebugger]         isProxy: false
[debug] [RemoteDebugger]         name: "Safari"
[debug] [RemoteDebugger]         bundleId: "com.apple.mobilesafari"
[debug] [RemoteDebugger]         hostId: undefined
[debug] [RemoteDebugger]         isActive: 0
[debug] [RemoteDebugger]         isAutomationEnabled: false
[debug] [RemoteDebugger]     Application: 'PID:303'
[debug] [RemoteDebugger]         id: "PID:303"
[debug] [RemoteDebugger]         isProxy: true
[debug] [RemoteDebugger]         name: "com.apple.WebKit.WebContent"
[debug] [RemoteDebugger]         bundleId: "com.apple.WebKit.WebContent"
[debug] [RemoteDebugger]         hostId: "PID:302"
[debug] [RemoteDebugger]         isActive: 0
[debug] [RemoteDebugger]         isAutomationEnabled: false
[debug] [RemoteDebugger] Checking for bundle identifiers: process-SafariViewService, com.apple.SafariViewService, *, com.xxxxxxx.xxxxxxx.xxxxxxx
[debug] [RemoteDebugger] Found app id key 'PID:306' for bundle 'process-SafariViewService'
[debug] [RemoteDebugger] Found app id key 'PID:306' for bundle 'com.apple.SafariViewService'
[debug] [RemoteDebugger] Found app id key 'PID:306' for bundle '*'
[debug] [RemoteDebugger] Found app id key 'PID:306' for bundle 'com.xxxxxxx.xxxxx.xxxxxx'
[debug] [RemoteDebugger] Trying out the possible app ids: PID:306 (try #1 of 20)
[debug] [RemoteDebugger] Skipping app 'PID:306' because it is not active
[RemoteDebugger] Could not connect to a valid app after 20 tries.
**[debug] [XCUITest] No available web pages: Could not connect to a valid app after 20 tries.
[debug] [XCUITest] No web frames found.**
[debug] [W3C (e54a2231)] Responding to client with driver.getContexts() result: ["NATIVE_APP"]
```
## Code To Reproduce Issue [ Good To Have ]
```
desiredCapabilities.setCapability("platformName", "iOS"); desiredCapabilities.setCapability("automationName","XCUITest");
desiredCapabilities.setCapability("deviceName", globalProp.getProperty("iosDeviceName"));
desiredCapabilities.setCapability("udid", globalProp.getProperty("udid"));
desiredCapabilities.setCapability("xcodeOrgId", globalProp.getProperty("xcodeOrgId"));
desiredCapabilities.setCapability("xcodeSigningId", globalProp.getProperty("xcodeSigningId")); desiredCapabilities.setCapability("locale",globalProp.getProperty("language").toLowerCase().toLowerCase()+"_CA");
```

**Comment by mykola-mokhnach** [comment]
> [debug] [RemoteDebugger] Skipping app 'PID:306' because it is not active

Are you able to interact with the web view using Safari?

**Comment by siddhantraut** [comment]
> > [debug] [RemoteDebugger] Skipping app 'PID:306' because it is not active
> 
> Are you able to interact with the web view using Safari?

No, Native app webView not able to inspect.

Yes, If I opened web app from iPhone Safari  browser then I can inspect it Safari.

**Comment by KazuCocoa** [comment]
Then, how about enabling _Settings > Safari > Advanced . Web Inspector_ as https://appium.io/docs/en/writing-running-appium/web/mobile-web/ 's _Setup for an iOS real device_ section ?

**Comment by siddhantraut** [comment]
> Then, how about enabling _Settings > Safari > Advanced . Web Inspector_ as https://appium.io/docs/en/writing-running-appium/web/mobile-web/ 's _Setup for an iOS real device_ section ?

It's enabled @KazuCocoa.

**Comment by imurchie** [comment]
> > > [debug] [RemoteDebugger] Skipping app 'PID:306' because it is not active
> > 
> > 
> > Are you able to interact with the web view using Safari?
> 
> No, Native app webView not able to inspect.
> Yes, If I opened web app from iPhone Safari browser then I can inspect it Safari.
> 
> [Additional info:
> webView is actually flexlayout in iframe,
> for Android its worked.]

I'm not sure I'm clear here. When you open your app on an iPhone, and then go to the webview in it, are you able to to inspect from Desktop Safari?

**Comment by siddhantraut** [comment]
> > > > [debug] [RemoteDebugger] Skipping app 'PID:306' because it is not active
> > > 
> > > 
> > > Are you able to interact with the web view using Safari?
> > 
> > 
> > No, Native app webView not able to inspect.
> > Yes, If I opened web app from iPhone Safari browser then I can inspect it Safari.
> > [Additional info:
> > webView is actually flexlayout in iframe,
> > for Android its worked.]
> 
> I'm not sure I'm clear here. When you open your app on an iPhone, and then go to the webview in it, are you able to to inspect from Desktop Safari?

No i'm not able to inspect, that exactly the issue.  :( 
also not getting webView context other than Native_App from getContextHandles();

**Comment by imurchie** [comment]
Unfortunately, if you cannot inspect it with Safari there is _literally_ nothing Appium can do about it.

What are the details of the view? What type of webview is it? Is it configured in some non-standard way?

Also, it might be of help, for diagnostic purposes, to add the `safariLogAllCommunication` capability (set to `true`), and post the logs (as a link to a [gist](https://gist.github.com)). There may be some information in the exchange that could prove helpful.

**Comment by siddhantraut** [comment]
@imurchie Its WkwebView

https://gist.github.com/siddhantraut/fc609674278ecf5d454f8499037de998

**Comment by siddhantraut** [comment]
@mykola-mokhnach liked gist isn't sufficient ?

**Comment by mykola-mokhnach** [comment]
The gist is fine, however it is clearly visible that the remote debugger does not return any webviews. Which only confirms the above fact: if Safari remote debugger does not see it then Appium won't be able to make it as well.

**Comment by imurchie** [comment]
@siddhantraut The gist does not start getting any information. Could you allow it to poll more for the contexts? The original logs have some reports from the Web Inspector but the latest do not, yet.

**Comment by siddhantraut** [comment]
@imurchie updated gist , shared end to end log , please let me know if more info required.

https://gist.github.com/siddhantraut/fc609674278ecf5d454f8499037de998

**Comment by imurchie** [comment]
Sorry, I meant that you ought to give it more time. For checking's sake, perhaps 30-60 seconds of polling for contexts. Something like
```java
long msStarted = System.currentTimeMillis();
while (System.currentTimeMillis() - msStarted <= 30000) {
    String handle = driver.getContextHandles();
    Thread.sleep(500);
}
```
This would just give the system on MobileSafari some time to respond with everything it knows. If there is something odd going on I might be able to see it, then.

**Comment by siddhantraut** [comment]
Unfortunately no sucess @imurchie 

================================================
          long msStarted = System.currentTimeMillis();
          while (System.currentTimeMillis() - msStarted <= 50000) {
           System.out.println(System.currentTimeMillis() - msStarted + "########### Poll For Context ###############");
          ProjectUtilities.iWait(1);
            Set<String> contextNames = driver.getContextHandles();
            for (String contextName1 : contextNames) {
            //prints out something like NATIVE_APP \n WEBVIEW_1
             System.out.println(contextName1);  }
================================================
[HTTP] 
NATIVE_APP
47624########### Poll For Context ###############
[HTTP] --> GET /wd/hub/session/895665a1-a24a-4fa8-9b05-51663f7cc14a/contexts
[HTTP] {}
[debug] [W3C (895665a1)] Calling AppiumDriver.getContexts() with args: ["895665a1-a24a-4fa8-9b05-51663f7cc14a"]
[debug] [XCUITest] Executing command 'getContexts'
[debug] [XCUITest] Getting list of available contexts
[debug] [iOS] Retrieving contexts and views
[debug] [XCUITest] Selecting by url: false 
[debug] [RemoteDebugger] Sending connection key request
[debug] [RemoteDebugger] Sending '_rpc_reportIdentifier:' message (id: 48): 'setConnectionKey'
[debug] [ios-device] Sending message to Web Inspector:
[debug] [ios-device] {
[debug] [ios-device]   "__argument": {
[debug] [ios-device]     "WIRConnectionIdentifierKey": "fd42963a-64b5-4b97-92e0-4c736f0f388a"
[debug] [ios-device]   },
[debug] [ios-device]   "__selector": "_rpc_reportIdentifier:"
[debug] [ios-device] }
[debug] [RemoteDebugger] Sending to Web Inspector took 1ms
[debug] [RemoteDebugger] Selecting application
[debug] [RemoteDebugger] No applications currently connected.
[debug] [XCUITest] No web frames found.
[debug] [W3C (895665a1)] Responding to client with driver.getContexts() result: ["NATIVE_APP"]
[HTTP] <-- GET /wd/hub/session/895665a1-a24a-4fa8-9b05-51663f7cc14a/contexts 200 4 ms - 24
[HTTP] 
NATIVE_APP
48636########### Poll For Context ###############
[HTTP] --> GET /wd/hub/session/895665a1-a24a-4fa8-9b05-51663f7cc14a/contexts
[HTTP] {}
[debug] [W3C (895665a1)] Calling AppiumDriver.getContexts() with args: ["895665a1-a24a-4fa8-9b05-51663f7cc14a"]
[debug] [XCUITest] Executing command 'getContexts'
[debug] [XCUITest] Getting list of available contexts
[debug] [iOS] Retrieving contexts and views
[debug] [XCUITest] Selecting by url: false 
[debug] [RemoteDebugger] Sending connection key request
[debug] [RemoteDebugger] Sending '_rpc_reportIdentifier:' message (id: 49): 'setConnectionKey'
[debug] [ios-device] Sending message to Web Inspector:
[debug] [ios-device] {
[debug] [ios-device]   "__argument": {
[debug] [ios-device]     "WIRConnectionIdentifierKey": "fd42963a-64b5-4b97-92e0-4c736f0f388a"
[debug] [ios-device]   },
[debug] [ios-device]   "__selector": "_rpc_reportIdentifier:"
[debug] [ios-device] }
[debug] [RemoteDebugger] Sending to Web Inspector took 2ms
[debug] [RemoteDebugger] Selecting application
[debug] [RemoteDebugger] No applications currently connected.
[debug] [XCUITest] No web frames found.
[debug] [W3C (895665a1)] Responding to client with driver.getContexts() result: ["NATIVE_APP"]
[HTTP] <-- GET /wd/hub/session/895665a1-a24a-4fa8-9b05-51663f7cc14a/contexts 200 5 ms - 24
[HTTP] 
NATIVE_APP
49645########### Poll For Context ###############
[HTTP] --> GET /wd/hub/session/895665a1-a24a-4fa8-9b05-51663f7cc14a/contexts
[HTTP] {}
[debug] [W3C (895665a1)] Calling AppiumDriver.getContexts() with args: ["895665a1-a24a-4fa8-9b05-51663f7cc14a"]
[debug] [XCUITest] Executing command 'getContexts'
[debug] [XCUITest] Getting list of available contexts
[debug] [iOS] Retrieving contexts and views
[debug] [XCUITest] Selecting by url: false 
[debug] [RemoteDebugger] Sending connection key request
[debug] [RemoteDebugger] Sending '_rpc_reportIdentifier:' message (id: 50): 'setConnectionKey'
[debug] [ios-device] Sending message to Web Inspector:
[debug] [ios-device] {
[debug] [ios-device]   "__argument": {
[debug] [ios-device]     "WIRConnectionIdentifierKey": "fd42963a-64b5-4b97-92e0-4c736f0f388a"
[debug] [ios-device]   },
[debug] [ios-device]   "__selector": "_rpc_reportIdentifier:"
[debug] [ios-device] }
[debug] [RemoteDebugger] Sending to Web Inspector took 1ms
[debug] [RemoteDebugger] Selecting application
[debug] [RemoteDebugger] No applications currently connected.
[debug] [XCUITest] No web frames found.
[debug] [W3C (895665a1)] Responding to client with driver.getContexts() result: ["NATIVE_APP"]
[HTTP] <-- GET /wd/hub/session/895665a1-a24a-4fa8-9b05-51663f7cc14a/contexts 200 4 ms - 24
[HTTP] 
NATIVE_APP
[HTTP] --> GET /wd/hub/session/895665a1-a24a-4fa8-9b05-51663f7cc14a/contexts
[HTTP] {}

**Comment by siddhantraut** [comment]
@imurchie @mykola-mokhnach do i need any get any additional input from dev team ?

**Comment by mykola-mokhnach** [comment]
The dev should make sure the web view is debuggable in the build that you receive from them.

**Comment by siddhantraut** [comment]
requested dev to check and provide debuggable build if not enabled.  Will check and post update to close this thread.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by txinhua** [comment]
long msStarted = System.currentTimeMillis();
      while (System.currentTimeMillis() - msStarted <= 50000) {
          System.out.println(System.currentTimeMillis() - msStarted + "########### Poll For Context ###############");
          ProjectUtilities.iWait(1);
          Set<String> contextNames = driver.getContextHandles();
          for (String contextName1 : contextNames) {
             System.out.println(contextName1);  
           }
     }

**Comment by txinhua** [comment]
that is useful
