### ISSUE TITLE
Server side error while executing the script in appium

### ISSUE THREAD

**Issue by chandu2508** [appium/appium#14062]
I was trying to execute the appium script in an virtual emulator.But while executing i am getting this below error.In emulator the app is launched but it doesn't perform any action gets closed.

Error:- [16:52:46] E/launcher - An unknown server-side error occurred while processing the command. Original error: No Chromedriver found that can automate Chrome '77.0.3865'. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md for more details. You could also try to enable automated chromedrivers download server feature [16:52:46] E/launcher - WebDriverError: An unknown server-side error occurred while processing the command. Original error: No Chromedriver found that can automate Chrome '77.0.3865'. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md for more details. You could also try to enable automated chromedrivers download server feature [16:52:46] E/launcher - Process exited with error code 199

Conf File:-

<const { SpecReporter } = require('jasmine-spec-reporter');

exports.config = {
  allScriptsTimeout: 300000,
  seleniumAddress: 'http://localhost:4723/wd/hub',
  specs: [
    './e2e/**/login.mobile.ts',

  ],
  useAllAngular2AppRoots: true,
  //chromeDriver: './node_modules/chromedriver/lib/chromedriver/chromedriver.exe',

  capabilities: {
    platformName: 'Android',
    platformVersion: '9', 
    deviceName: 'emulator-5554', 
    browserName: '', 
    appiumVersion:'1.16.0',
    autoWebview: true,
    autoWebviewTimeout: 10000,
    autoacceptalerts: true,
    autoGrantPermissions: true,
    clearSystemFiles: true,

    app: './platforms/android/build/outputs/apk/android-debug.apk

  },

  //baseUrl: 'http://10.0.2.2:8000',

  plugins: [
    {
      path: require.resolve('protractor-console'),
      logLevels: ['severe'],
      package: 'jasmine2-protractor-utils',
      disableHTMLReport: false,
      disableScreenshot: false,
      screenshotPath: './screenshots',
      screenshotOnExpectFailure: true,
      screenshotOnSpecFailure: true,
      clearFoldersBeforeTest: true
    }
  ],

  // directConnect: true, //enable for desktop
  //baseUrl: 'http://localhost:4723/wd/hub',
  framework: 'jasmine2',
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 300000,
    print: function() {}
  },
  beforeLaunch: function() {
    require('ts-node').register({
      project: 'e2e/tsconfig.e2e.json'
    });
  },
  onPrepare() {
    var jasmineReporters = require('jasmine-reporters');
    jasmine.getEnv().addReporter(
      new jasmineReporters.JUnitXmlReporter({
        consolidateAll: true,
        savePath: './report/mobile',
        filePrefix: 'xmlresults'
      })
    );
    var wd = require('wd'),
      protractor = require('protractor'),
      wdBridge = require('wd-bridge')(protractor, wd);
    wdBridge.initFromProtractor(exports.config);
  },

  onComplete: function() {
    var browserName, browserVersion;
    var capsPromise = browser.getCapabilities();

    capsPromise.then(function(caps) {
      browserName = caps.get('browserName');
      browserVersion = caps.get('version');

      var HTMLReport = require('protractor-html-reporter');

      testConfig = {
        reportTitle: 'CVM Test Execution Report',
        outputPath: './report/mobile', //relative path
        screenshotPath: './screenshots',
        testBrowser: 'Mobile',
        browserVersion: browserVersion,
        modifiedSuiteName: false,
        screenshotsOnlyOnFailure: true
      };
      new HTMLReport().from('./report/mobile/xmlresults.xml', testConfig);
    });
  }
};>

**Comment by KazuCocoa** [comment]
Please attach the full log as GIST.

`chromedriverExecutable` in caps https://appium.io/docs/en/writing-running-appium/caps/ also could help to set a particular Chromedriver version.

**Comment by chandu2508** [comment]
> Please attach the full log as GIST.
> 
> `chromedriverExecutable` in caps https://appium.io/docs/en/writing-running-appium/caps/ also could help to set a particular Chromedriver version.

hey..i have tried by adding the chromedriverExecutable..But its not working

**Comment by KazuCocoa** [comment]
Please share the full log as GIST since we cannot track what happened

**Comment by mykola-mokhnach** [comment]
Closed because of no reponse
