### ISSUE TITLE
Appium Server crashes unexpectedly on FindByImage

### ISSUE THREAD

**Issue by guptapunit** [appium/appium#14060]
## The problem

When using FindByImage for IOS the server crashes with the following error logs...

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OSX Catalina 10.15.1
* Node.js version (unless using Appium.app|exe):V12.13.0
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: IOS
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

[Link To Appium Logs](https://gist.github.com/guptapunit/f23a56c2414c4fc93983990cfde034a5)

## Code To Reproduce Issue

__Standard FindByImage code__
`MobileElement el2 = (MobileElement) oDriver.findElementByImage(encodedString1);`

**Comment by mykola-mokhnach** [comment]
> [BaseDriver] When trying to find an element, determined that the screen aspect ratio and screenshot aspect ratio are different. Screen is 0x0 whereas screenshot is 750x1624.
> [BaseDriver] Resizing screenshot to InfinityxInfinity to match screen aspect ratio so that image element coordinates have a greater chance of being correct.


The screen size is returned as 0x0, which should not be happening. Although, the scaling algorithm should anyway be smart enough to handle such cases.

**Comment by mykola-mokhnach** [comment]
the workaround has been published to appium@beta
