### ISSUE TITLE
Appium could not able to recognise the Accessibility id of Element type UIImageView

### ISSUE THREAD

**Issue by deepu451** [appium/appium#14063]
## The problem

Appium does not recognise the accessibility id of  element type UIImageView

## Environment

* Appium version (or git revision) that exhibits the issue:1.16.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:MAC OS 10.15.3
* Node.js version (unless using Appium.app|exe):10.15.3
* Npm or Yarn package manager:6.9.0
* Mobile platform/version under test:iOS 13
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

## Details

My app was being build by Xcode 10 and using objective c for app development.
i have set accessibility id for the UIImageView element.
Installed the app on iOS 12 and above devices,
 appium page source didn't show the the accessibility of UIImageView elements. 
 

## Link to Appium logs

<?xml version="1.0" encoding="UTF-8"?><AppiumAUT><XCUIElementTypeApplication type="XCUIElementTypeApplication" name="Vocera" label="Vocera" enabled="true" visible="true" x="0" y="0" width="375" height="667">
  <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" visible="true" x="0" y="0" width="375" height="667">
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="375" height="667">
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="375" height="667">
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="375" height="667">
          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="375" height="667">
            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="375" height="667">
              <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="375" height="667">
                <XCUIElementTypeNavigationBar type="XCUIElementTypeNavigationBar" name="New Secure Text" enabled="true" visible="true" x="0" y="20" width="375" height="44">
                  <XCUIElementTypeButton type="XCUIElementTypeButton" enabled="true" visible="true" x="16" y="20" width="44" height="44">
                    <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" enabled="true" visible="false" x="16" y="20" width="0" height="0"/>
                  </XCUIElementTypeButton>
                  <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="New Secure Text" name="New Secure Text" label="New Secure Text" enabled="true" visible="true" x="120" y="32" width="135" height="21"/>
                </XCUIElementTypeNavigationBar>
                <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="375" height="667">
                  <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="375" height="667">
                    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="64" width="375" height="603">
                      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="64" width="375" height="154">
                        <XCUIElementTypeImage type="XCUIElementTypeImage" enabled="true" visible="false" x="0" y="64" width="375" height="40"/>
                        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="66" width="375" height="36">
                          <XCUIElementTypeImage type="XCUIElementTypeImage" enabled="true" visible="false" x="0" y="66" width="375" height="36"/>
                          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="66" width="375" height="36">
                            <XCUIElementTypeSearchField type="XCUIElementTypeSearchField" name="Search" label="Search" enabled="true" visible="true" x="8" y="66" width="359" height="36"/>
                          </XCUIElementTypeOther>
                        </XCUIElementTypeOther>
                        <XCUIElementTypeCell type="XCUIElementTypeCell" enabled="true" visible="true" x="0" y="108" width="375" height="44">
                          <XCUIElementTypeButton type="XCUIElementTypeButton" enabled="true" visible="true" x="0" y="108" width="375" height="44"/>
                          <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="New Text" name="New Text" label="New Text" enabled="true" visible="true" x="15" y="108" width="333" height="44"/>
                          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="15" y="151" width="360" height="1"/>
                          <XCUIElementTypeButton type="XCUIElementTypeButton" name="chevron" label="chevron" enabled="false" visible="false" x="356" y="123" width="11" height="14"/>
                        </XCUIElementTypeCell>
                        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="170" width="375" height="44">
                          <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="TEMPLATES" name="TEMPLATES" label="TEMPLATES" enabled="true" visible="true" x="10" y="175" width="375" height="44"/>
                        </XCUIElementTypeOther>
                      </XCUIElementTypeOther>
                      <XCUIElementTypeTable type="XCUIElementTypeTable" enabled="true" visible="true" x="0" y="218" width="375" height="449">
                        <XCUIElementTypeCell type="XCUIElementTypeCell" name="UITableViewCell(A_Template)" label="UITableViewCell(A_Template)" enabled="true" visible="true" x="0" y="218" width="375" height="58">
                          <XCUIElementTypeButton type="XCUIElementTypeButton" enabled="true" visible="true" x="0" y="218" width="44" height="58"/>
                          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="275" width="375" height="1"/>
                          **<XCUIElementTypeImage type="XCUIElementTypeImage" enabled="true" visible="false" x="8" y="235" width="26" height="24"/>**
                          <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="A_Template" name="A_Template" label="A_Template" enabled="true" visible="true" x="49" y="218" width="292" height="58"/>
                          <XCUIElementTypeButton type="XCUIElementTypeButton" name="chevron" label="chevron" enabled="false" visible="false" x="349" y="240" width="11" height="14"/>
                        </XCUIElementTypeCell>
                        <XCUIElementTypeCell type="XCUIElementTypeCell" name="UITableViewCell(BA_Template)" label="UITableViewCell(BA_Template)" enabled="true" visible="true" x="0" y="276" width="375" height="58">
                          <XCUIElementTypeButton type="XCUIElementTypeButton" enabled="true" visible="true" x="0" y="276" width="44" height="58"/>
                          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="333" width="375" height="1"/>
                          <XCUIElementTypeImage type="XCUIElementTypeImage" enabled="true" visible="false" x="8" y="293" width="26" height="24"/>
                          <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="BA_Template" name="BA_Template" label="BA_Template" enabled="true" visible="true" x="49" y="276" width="292" height="58"/>
                          <XCUIElementTypeButton type="XCUIElementTypeButton" name="chevron" label="chevron" enabled="false" visible="false" x="349" y="298" width="11" height="14"/>
                        </XCUIElementTypeCell>
                      </XCUIElementTypeTable>
                    </XCUIElementTypeOther>
                  </XCUIElementTypeOther>
                </XCUIElementTypeOther>
                <XCUIElementTypeImage type="XCUIElementTypeImage" enabled="true" visible="false" x="175" y="55" width="25" height="5"/>
              </XCUIElementTypeOther>
            </XCUIElementTypeOther>
          </XCUIElementTypeOther>
        </XCUIElementTypeOther>
      </XCUIElementTypeOther>
    </XCUIElementTypeOther>
  </XCUIElementTypeWindow>
  <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" visible="false" x="0" y="0" width="375" height="667">
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="375" height="667">
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="375" height="667"/>
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="667" width="375" height="216"/>
    </XCUIElementTypeOther>
  </XCUIElementTypeWindow>
</XCUIElementTypeApplication></AppiumAUT>

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing we can do here on Appium side. The page source is generated by XCTest based on what the app provides to the Accessibility manager. Consider reporting the issue to Apple.

Closed as third party issue
