### ISSUE TITLE
WinAppDriver + findByImage

### ISSUE THREAD

**Issue by jsa34** [appium/appium#14073]
## The problem

Trying to call driver.findByImage() with WinAppDriver results in InvalidSelectorError thrown.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): 13.11.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Windows
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: cli

## Details

Example code used (using java-client for appium):
    DesiredCapabilities capabilities = new DesiredCapabilities();
    capabilities.setCapability("deviceName", "WindowsPC");
    capabilities.setCapability("app", "Root");
    capabilities.setCapability("ms:experimental-webdriver", true);
WindowsDriver<WindowsElement> driver = new WindowsDriver<WindowsElement>(currentDriver.getRemoteAddress(), capabilities);
    WebDriverWait wait = new WebDriverWait(driver, 10L);
wait.until(ExpectedConditions.presenceOfElementLocated(MobileBy.image(ImageManager.getImage(imageName))));

## Link to Appium logs

https://gist.github.com/jsa34/acab1d65931ee9606bf656ecc3b84dde

**Comment by mykola-mokhnach** [comment]
The PR has been published to appium@beta. Thanks for your assistance @jsa34

**Comment by Liqun-Ma** [comment]
Hello, I am using  v2.0.0-beta.57. I use Appium.WebDriver(5.0.0-beta03) library in C#. My problem is I cannot find ImageManager anymore. @jsa34  do you know what to input?

**Comment by Liqun-Ma** [comment]
ok, I need change the image to ToBase64String
