### ISSUE TITLE
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Could not determine iOS SDK version: Could not get Xcode version. /Library/Developer/Info.plist does not exist on disk.

### ISSUE THREAD

**Issue by jgonzalezalbisu** [appium/appium#14078]
## The problem
I'm trying to start an appium iosDriver and I'm getting the following error:
`org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Could not determine iOS SDK version: Could not get Xcode version. /Library/Developer/Info.plist does not exist on disk.`

## Environment

* Appium version 7.3.0 (Maven dependency)
* Appium desktop 1.15.1
* MacOS 10.15.3
* Emulator

## Details
I've tried doing `sudo xcode-select --switch /Applications/Xcode.app` with no success....even though my Xcode.app is installed on the Applications folder.

**The full error is:**
`[RemoteTestNG] detected TestNG version 7.0.1
FAILED CONFIGURATION: @BeforeMethod startMobileDriver
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Could not determine iOS SDK version: Could not get Xcode version. /Library/Developer/Info.plist does not exist on disk.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'hostinfo', ip: 'IP', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.3', java.version: '13.0.2'
Driver info: driver.version: IOSDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not determine iOS SDK version: Could not get Xcode version. /Library/Developer/Info.plist does not exist on disk.
    at getResponseForW3CError (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
    at asyncHandler (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:388:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'mbp-tabu.lan', ip: 'fe80:0:0:0:c0:3875:1ed8:651d%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.3', java.version: '13.0.2'`

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]
`iOSDriver = new IOSDriver<IOSElement>(getServerURL(), setiOSCapabilities());

`
private static DesiredCapabilities setiOSCapabilities() {
		DesiredCapabilities cap = new DesiredCapabilities();
			cap.setCapability(MobileCapabilityType.DEVICE_NAME, JGAConstants.IOS_DEVICE_NAME);
		}

		cap.setCapability(MobileCapabilityType.PLATFORM_NAME, Platform.IOS);
		cap.setCapability(MobileCapabilityType.APP, JGAConstants.IOS_APP_PATH.getAbsolutePath());
		cap.setCapability(AndroidMobileCapabilityType.AUTO_GRANT_PERMISSIONS, true);

		cap.setCapability(MobileCapabilityType.NO_RESET, true);
		cap.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.IOS_XCUI_TEST);

		return cap;
	}

`

**Comment by KazuCocoa** [comment]
How about `sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer`?

https://appium.io/docs/en/advanced-concepts/multiple-xcode-versions/
https://stackoverflow.com/questions/9600615/xcode-stops-working-after-set-xcode-select-switch

**Comment by jgonzalezalbisu** [comment]
> sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

Same thing Kazu :/

**Comment by KazuCocoa** [comment]
What the result of:
```
xcode-select -p
````

Most case is your env has no xcode command line tools. You can install it via:

```
xcode-select --install
```

**Comment by jgonzalezalbisu** [comment]
`xcode-select -p

/Applications/Xcode.app/Contents/Developer`

And 
`xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
`

I'm out of ideas

**Comment by jgonzalezalbisu** [comment]
@KazuCocoa FYI, I have the latest Xcode version

**Comment by jgonzalezalbisu** [comment]
Also after doing `sudo xcode-select --switch /Applications/Xcode.app`, and then `xcode-select -p`, I'm still seeing `/Applications/Xcode.app/Contents/Developer`. Is this correct?

**Comment by KazuCocoa** [comment]
Yes. Forgot but old Xcode was pointed `/Applications/Xcode.app/` when `sudo xcode-select --switch /Applications/Xcode.app`, but `/Applications/Xcode.app/Contents/Developer` was correct. Maybe newer xcode-select command can treat the `Contents/Developer` part well

I assume this is Xcode/the CLI tool layer's error, but no good idea for now.
How about restarting your machine?

**Comment by jgonzalezalbisu** [comment]
Thanks @KazuCocoa , after rebooting the mac I got another error (making progress)
`AILED CONFIGURATION: @BeforeMethod startMobileDriver
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: '13.2' does not exist in the list of simctl SDKs. Only the following Simulator SDK versions are available on your system: 13.3, 6.1, 10.3
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'mbp-tabu.lan', ip: 'fe80:0:0:0:875:1b37:bbef:7cd0%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.3', java.version: '13.0.2'
Driver info: driver.version: IOSDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: '13.2' does not exist in the list of simctl SDKs. Only the following Simulator SDK versions are available on your system: 13.3, 6.1, 10.3
    at getResponseForW3CError (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
    at asyncHandler (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:388:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

Any ideas?

**Comment by KazuCocoa** [comment]
```
Only the following Simulator SDK versions are available on your system: 13.3, 6.1, 10.3
```

Your Xcode can generate simulators only the above versions. You must specify platformVersion as them

**Comment by jgonzalezalbisu** [comment]
perfect, solved it. Now I've got this error:
`Original error: Unable to launch WebDriverAgent because of xcodebuild failure: not found: carthage`

**Comment by KazuCocoa** [comment]
Did you finish the basic steps in https://appium.io/docs/en/drivers/ios-xcuitest/ ?
Please install necessary tools

**Comment by jgonzalezalbisu** [comment]
Working perfectly. Thanks @KazuCocoa !
