### ISSUE TITLE
io.appium.java_client.NoSuchContextException: An unknown server-side error occurred while processing the command. Original error: Trying to use a chromedriver binary at the path ./APPIUM_BROWSER_DRIVERS/, but it doesn't exist!

### ISSUE THREAD

**Issue by jgonzalezalbisu** [appium/appium#14079]
## The problem

I came across a problem which I haven't been able to solve in the past 3 days.

Basically I'm creating a new framework for Appium tests, and I'm trying to handle hybrid apps. Thing is, chromedriver is giving me headaches.

I've read that you can configure Appium to auto download the chrome version you need for this, but couldn't get around the problem using that, as the documentation I found is not clear on how to do it, so I went with specifying the binary. But, when specifying the binary directory, I get the following error:

`\io.appium.java_client.NoSuchContextException: An unknown server-side error occurred while processing the command. Original error: Trying to use a chromedriver binary at the path ./APPIUM_BROWSER_DRIVERS/, but it doesn't exist!`

## Environment
* Appium version 7.3.0 (Maven dependency)
* Appium desktop 1.15.1
* MacOS 10.15.3
* Emulator

## Code To Reproduce Issue [ Good To Have ]

androidDriver = new AndroidDriver<AndroidElement>(getServerURL(), setAndroidCapabilities());

	private static DesiredCapabilities setAndroidCapabilities() {

		DesiredCapabilities cap = new DesiredCapabilities();

		if (JGAConstants.ANDROID_EXECUTION_ON_PHYSICAL_DEVICE == true) {
			cap.setCapability(MobileCapabilityType.DEVICE_NAME, JGAConstants.ANDROID_PHYSICAL_DEVICE_NAME);
		} else {
			cap.setCapability(MobileCapabilityType.DEVICE_NAME, JGAConstants.ANDROID_DEVICE_NAME);
		}

		cap.setCapability(MobileCapabilityType.PLATFORM_NAME, Platform.ANDROID);
		cap.setCapability(MobileCapabilityType.APP, JGAConstants.ANDROID_APP_PATH.getAbsolutePath());
		cap.setCapability(AndroidMobileCapabilityType.AUTO_GRANT_PERMISSIONS, true);

		cap.setCapability(MobileCapabilityType.NO_RESET, true);
		cap.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.ANDROID_UIAUTOMATOR2);

		/*
		 * This is for the chromedriver.
		 */
                 cap.setCapability("chromedriverExecutableDir", JGAConstants.BROWSER_DRIVERS_PATH);
		cap.setCapability(MobileCapabilityType.BROWSER_NAME, BrowserType.CHROME);

		return cap;
	}`

JGAConstants.BROWSER_DRIVERS_PATH is the correct path to the folder that contains the chromedriver, but basically the path is: **./projectFolder/APPIUM_BROWSER_DRIVERS/**

**Comment by mykola-mokhnach** [comment]
Please provide the absolute folder path to this capability

**Comment by jgonzalezalbisu** [comment]
I've specified the absolute path and got this error:
`Original error: No Chromedrivers found in '/Users/Jorge/repos-personal/course-appium-android/Appium-Course/APPIUM_BROWSER_DRIVERS`

**Comment by mykola-mokhnach** [comment]
hm, does the folder actually contain any drivers?

![Fry](https://imgflip.com/s/meme/Futurama-Fry.jpg)

**Comment by jgonzalezalbisu** [comment]
I can confirm that yes
![image](https://user-images.githubusercontent.com/23585745/76978836-f989aa80-6915-11ea-98f8-3294641a0b57.png)

**Comment by mykola-mokhnach** [comment]
What is in the server log?

**Comment by jgonzalezalbisu** [comment]
https://gist.github.com/jgonzalezalbisu/99f6370ed0f8d8a13bb79d805196af7a

**Comment by mykola-mokhnach** [comment]
> [warn] [Chromedriver] Cannot retrieve version number from 'chromedriver' Chromedriver binary. Make sure it returns a valid version string in response to '--version' command line argument. Command '/Users/Jorge/repos-personal/course-appium-android/Appium-Course/APPIUM_BROWSER_DRIVERS/chromedriver --version' errored out: Error: spawn /Users/Jorge/repos-personal/course-appium-android/Appium-Course/APPIUM_BROWSER_DRIVERS/chromedriver EACCES

**Comment by jgonzalezalbisu** [comment]
Not sure to be honest what is the problem

**Comment by mykola-mokhnach** [comment]
Appium process cannot access the file or it is not executable

**Comment by jgonzalezalbisu** [comment]
Ok that I understood, but it's the binary downloaded from https://chromedriver.storage.googleapis.com/index.html?path=81.0.4044.69/ for Mac.

**Comment by mykola-mokhnach** [comment]
Do `chmod` and `chown` words ring the bell?

**Comment by jgonzalezalbisu** [comment]
Yes, I've tried that before but I got the same problem (no drivers found). Here is the folder's permissions.
![image](https://user-images.githubusercontent.com/23585745/77001614-f653e600-6938-11ea-8591-92838fd5fc84.png)
I'm aware this is not an appium issue, so you can close it if you prefer, but I haven't found the solution anywhere.

Thanks again for your time

**Comment by mykola-mokhnach** [comment]
Simply make sure the downloaded chromedriver is [readable and executable](http://learn.leighcotnoir.com/wp-content/uploads/2016/08/POSIX-file-permissions.pdf) to the same user, who owns the Appium server process.

Closed as not an issue

**Comment by mykola-mokhnach** [comment]
The first link Google returns for spawn EACCES: https://www.edwardbeazer.com/how-to-fix-this-error-spawn-eacces/
