### ISSUE TITLE
xpath.clear is not working for latest Xcode?

### ISSUE THREAD

**Issue by mahendra1999** [appium/appium#14070]
## The problem

I can't able to clear the text fields in latest Xcode. Give me a solution

## Environment

Appium Vs : 1.15.1
IOS 12.4.3
Xcode 11.3.1

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mahendra1999** [comment]
Text filed of Xpath was //XCUIElementTypeTextField[@name="EmailID"]

**Comment by mykola-mokhnach** [comment]
Please try the most recent server version and attach the full log

**Comment by mahendra1999** [comment]
<img width="268" alt="Screenshot 2020-03-16 at 12 56 55 PM" src="https://user-images.githubusercontent.com/50740648/76732891-b00a5580-6785-11ea-98d6-48ee30d160e9.png">
in That screen my first data was onboard@gmail.com and second data was stguser@gmail.com. Not Clear the first data. I used my code before sending I clear text command.

**Comment by mykola-mokhnach** [comment]
> Please try the most recent server version and attach the full log

Still waiting for the requested information

**Comment by Dan-Maor** [comment]
Does it work when using Xcode 10.3?

**Comment by mahendra1999** [comment]
> work

yes, it's working fine on Xcode 10.2.1

**Comment by mykola-mokhnach** [comment]
Closed as incomplete
