### ISSUE TITLE
autoGrantPermissions failed because i have car permission needed

### ISSUE THREAD

**Issue by chaooe** [appium/appium#14076]
## The problem

Can't grant all permission, My android device which need car information

## Environment

Appuim V17.

## Details

Adb dumpsys for packege

requested permissions:
      android.permission.INTERNET
      android.permission.ACCESS_NETWORK_STATE
      android.permission.ACCESS_WIFI_STATE
      android.permission.BLUETOOTH
      android.permission.BLUETOOTH_ADMIN
      android.permission.ACCESS_COARSE_LOCATION
      android.permission.ACCESS_FINE_LOCATION
      android.car.permission.CAR_VENDOR_EXTENSION
      android.car.permission.CAR_CABIN
      android.car.permission.CAR_CHARGE
      android.car.permission.CAR_MILEAGE
      android.car.permission.CAR_HVAC
      android.car.permission.CAR_CONTROL_AUDIO_VOLUME
      android.car.permission.CAR_CONTROL_AUDIO_SETTINGS
      android.permission.WAKE_LOCK
      android.permission.WRITE_EXTERNAL_STORAGE
      android.permission.READ_EXTERNAL_STORAGE
    install permissions:
      android.permission.BLUETOOTH: granted=true
      android.permission.INTERNET: granted=true
      android.permission.BLUETOOTH_ADMIN: granted=true
      android.permission.ACCESS_NETWORK_STATE: granted=true
      android.permission.ACCESS_WIFI_STATE: granted=true
      android.permission.WAKE_LOCK: granted=true

## Code To Reproduce Issue [ Good To Have ]

under appium-adb/lib/helper.js
`const extractMatchingPermissions = function (dumpsysOutput, groupNames, grantedState = null) {
  const groupPatternByName = (groupName) => new RegExp(`^(\\s*${_.escapeRegExp(groupName)} permissions:[\\s\\S]+)`, 'm');
  const indentPattern = /\S|$/;
  const permissionNamePattern = /android\.\w*\.permission\.\w+/; 
  const grantedStatePattern = /\bgranted=(\w+)/;
  const result = [];`
After i changed the permissionNamePattern to above, it should be ok. Could you help to check if it is ok for future used.

**Comment by mykola-mokhnach** [comment]
Please push a PR to appium-adb. We will review it ASAP

**Comment by mykola-mokhnach** [comment]
The changes have been published in appium@beta. Thanks for your contribution @chaooe
