### ISSUE TITLE
driver.manage().deleteAllCookies() does not working on iOS >13 versions

### ISSUE THREAD

**Issue by Pavithra24x7** [appium/appium#14072]
## The problem

I am working on Hybrid application on iOS platform (Real device), where I need to do social login 'Register With Facebook' so I need to **delete the browsing data on safari browser** after completion of the login each & every time through automation. **On iOS version > 13 getting the WebDriverException**. 

## Environment

* Appium version (or git revision) that exhibits the issue: **1.16.0**
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: **10.15.2 macOS catalina**
* Node.js version (unless using Appium.app|exe):**13.1.0**
* Npm or Yarn package manager: **Npm - 6.12.1**
* Mobile platform/version under test: **iPhone X - v13.3.1**
* Real device or emulator/simulator: **Real device**
* Appium CLI or Appium.app|exe: **appium.exe**

## Details
Launching the app & clicks on Register with facebook &
1.Switching into webview (Switching to webview has been done)
**2.Clearing safari cache by calling driver.manage().deleteAllCookies() function
 which is working fine for me if the iOS version is < 13. But facing issue & getting WebDriverException while executing the scripts on iOS version >=13.**
while processing the command on iOS > 13 getting exception **org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 400 - undefined**

## Link to Appium logs
The logs are attached here (https://gist.github.com/Pavithra24x7/1e29d0b1317abf719addf3aa6e855c14)

**Comment by imurchie** [comment]
Thanks for the report. I will look into this.

**Comment by imurchie** [comment]
The problem is that you are not in the Webview context. Deleting cookies only works there.

**Comment by Pavithra24x7** [comment]
@imurchie  Your correct , Safari is not loading in webcontext.
It is showing Native only. But switching is happening in below 13 version phones.

**Comment by imurchie** [comment]
@Pavithra24x7 Can you give Appium 1.17.0 a try?

**Comment by Pavithra24x7** [comment]
Yes. Tried with appium 1.17.0 version
Its worked for me.
Safari webview switching is working fine & safari cache has been cleared by calling driver.manage().deleteAllCookies() function

**Comment by imurchie** [comment]
Excellent!
