### ISSUE TITLE
Unable to run iOS tests after upgrading from Appium 1.16.0 to 1.17.0

### ISSUE THREAD

**Issue by LoveleenSaini** [appium/appium#14077]
## The problem

Appium server throws errors when trying to create new session.

## Environment

* Appium version that exhibits the issue: 1.17.0
* Last Appium version that did not exhibit the issue: 1.16.0
* Mac OS version used to run Appium: macOS Catalina 10.15.3
* Node.js version: 8.9.4
* Mobile platform/version under test: iOS 13.3
* Real device or emulator/simulator: Simulator

## Link to Appium logs
https://gist.github.com/LoveleenSaini/8abaf5c2a35119a22ad9a889965f7b02#file-appium_server_1_17_0_errors

**Comment by KazuCocoa** [comment]
Could you reinstall appiunm after upgrading the NodeJS env to 10+?
We already require NodeJS 10 from https://github.com/appium/appium/releases/tag/v1.14.0
https://github.com/appium/appium#requirements

**Comment by LoveleenSaini** [comment]
Upgrading NodeJS has resolved the issue. 
Thanks :)
