### ISSUE TITLE
Could the appium support the browser base on the chrome kernel in android device?

### ISSUE THREAD

**Issue by RyanLiuF** [appium/appium#14071]
## The problem

I could easily use the appium with selenium to auto-control the web element through the chrome browser on android device. But now I want to use the others browser like 360se or UC base on chrome kernel to achieve this requirement.  Could the appium support the browser base on the chrome kernel in android device ??
Very thanks!!

## Environment
python version: 3.7.4
windows: 10
Appium: 1.12.1

**Comment by mykola-mokhnach** [comment]
Currently we don't have any plans regarding such functionality. Although, you're always welcome to create a PR.
