### ISSUE TITLE
Element not found 404, but appium is still passing the testcase

### ISSUE THREAD

**Issue by waqaszulfiqar** [appium/appium#14081]
## The problem
I have tried different things just to check if the element is not visible on the page. but it's still passing.

## Environment

* Appium version:  1.15.1
* Node.js version: v12.13.1
* Npm: 5.6.0
* Mobile platform/version: Google pixel 2(9.0) 
* Real device or emulator/simulator: Android Simulator

## Appium log
```
[debug] [BaseDriver] Waited for 9390 ms so far
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://localhost:8201/wd/hub/session/29cf780d-7902-4217-859a-1c35cd68a879/element] with body: {"strategy":"xpath","selector":"//android.widget.TextView[@text=\"asflnaksjfhhfosah\"]","context":"","multiple":false}
[WD Proxy] Got an unexpected response with status 404: {"sessionId":"29cf780d-7902-4217-859a-1c35cd68a879","value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters","stacktrace":"io.appium.uiautomator2.common.exceptions.ElementNotFoundException: An element could not be located on the page using the given search parameters\n\tat io.appium.uiautomator2.handler.FindElement.findElement(FindElement.java:102)\n\tat io.appium.uiautomator2.handler.FindElement.safeHandle(FindElement.java:72)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:38)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:252)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:242)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerCon...
[debug] [W3C] Matched W3C error code 'no such element' to NoSuchElementError
[debug] [W3C (4950e230)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[debug] [W3C (4950e230)]     at AndroidUiautomator2Driver.findElOrEls (C:\Users\waqas\AppData\Roaming\npm\node_modules\appium\node_modules\appium-android-driver\lib\commands\find.js:75:11)
[HTTP] <-- POST /wd/hub/session/4950e230-f5d2-4d8d-acd2-56e604e560b9/element 404
```

## Code To Reproduce Issue
```
//XPath for the field
selector{
yourTip: '//android.widget.TextView[@text="asflnaksjfhhfosah"]', }
```

// this filed is not present on a particular page but and 5-sec appium passes my script. I changed the text just to confirm if it picks it up or not
and here is the expected result. 

expect(Ticket.yourTip.isDisplayed());

**Comment by mykola-mokhnach** [comment]
Please describe the issue properly and provide the steps, the actual and the expected results. I don't observe any server issues in the current report.

**Comment by waqaszulfiqar** [comment]
**Code To Reproduce Issue**
//XPath for the field

selector{
yourTip: '//android.widget.TextView[@text="asflnaksjfhhfosah"]', }

// this filed is not present on a particular page but and 5-sec appium passes my script. I changed the text just to confirm if it picks it up or not
and here is the expected result.
**Expected Result:**
expect(Ticket.yourTip.isDisplayed());

**Comment by mykola-mokhnach** [comment]
So, the element is expected to be not found. Although in the attached server log everything looks just fine - it returns the expected `no such element` exception. Your issue seems to be the client side.

**Comment by waqaszulfiqar** [comment]
Nope, the issue is, it just passes only the expected part. But if something is not found in the method or function than it fails it. But pass the expected thing.  So I don't think its client-side issue.

**Comment by waqaszulfiqar** [comment]
@mykola-mokhnach Mate, any suggestion that can help me out with this. this is so wired

**Comment by imurchie** [comment]
Do you have a minimal example that fails in this way? Something that can be run?

**Comment by mykola-mokhnach** [comment]
> @mykola-mokhnach Mate, any suggestion that can help me out with this. this is so wired

Sorry, I think I cannot help nothing here

**Comment by waqaszulfiqar** [comment]
@imurchie I just wanted to test if my test case is failing or not. So I just change the text "Done" to this "asflnaksjfhhfosah" and appium could not find that XPath and continuously giving 404, element not found but when it finishes that script it just marked the test case as Passed. 
It's really wired behavior.  


{yourTip: '//android.widget.TextView[@text="asflnaksjfhhfosah"]', }

**Comment by imurchie** [comment]
Test passing or failing is entirely on the client side. Something is wrong there.

**Comment by waqaszulfiqar** [comment]
@imurchie is there any way that I can get the network response that when its throw 404 it fails the test. Because I have searched a lot but can't find it in Appium. But cypress is giving this option and that works pretty awesome on web.

**Comment by imurchie** [comment]
I'm not sure what you mean. This is not a network 404 error, but rather it is how Selenium/Appium respond when an element is not found.

**Comment by waqaszulfiqar** [comment]
Okay. Can we set this Selenium/Appium response in way that if they can't find any element then fail the test?

**Comment by mykola-mokhnach** [comment]
Consider fixing the client side script. Closed as not an issue.
