### ISSUE TITLE
Element lookup in IOS webview takes 5-10x longer after updating to 1.17.0 from 1.16.0

### ISSUE THREAD

**Issue by aakacenoks** [appium/appium#14082]
## The problem

Element lookup time in iOS webview has increased to about 1 second (on version 1.17.0) instead of approx 50ms (version 1.16.0). 
Also, clicking takes 3 seconds instead of  <1 second like it was on 1.16.0.

## Environment

* Appium version that exhibits the issue: 1.17.0
* Last Appium version that did not exhibit the issue: 1.16.0
* Desktop OS/version used to run Appium: macOS 10.15.3
* Node.js version: 13.6.0
* Npm package manager: 6.13.4
* Mobile platform/version under test: iOS 13.3
* Real device or emulator/simulator: Read device
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

Logs for 1.17.0: https://gist.github.com/aakacenoks/50ad0e5e3512d8c77163c20c56adfcd6#file-1-17-0-log
Logs for 1.16.0: https://gist.github.com/aakacenoks/327bbdfbe45819b5e76ec19b71188b15#file-1-16-0-log

**Comment by mykola-mokhnach** [comment]
Please attach the logs with timestamps enabled. Also, please enable the `safariLogAllCommunication` capability for 1.17.0

**Comment by aakacenoks** [comment]
@mykola-mokhnach Gists have been updated with timestamps and `safariLogAllCommunication` cap enabled.

**Comment by mykola-mokhnach** [comment]
It looks like v 1.17 adds 500ms delay between these two log lines:

> 020-03-18 09:17:39:445 - [debug] [RemoteDebugger] Received result for atom 'is_displayed' execution: true
> 2020-03-18 09:17:39:862 - [debug] [W3C (8b6a7490)] Responding to client with driver.elementDisplayed() result: true

cc @imurchie

**Comment by mykola-mokhnach** [comment]
The patch has been published to appium@beta. Please try it out @aakacenoks

**Comment by usagikengood** [comment]
Hi @mykola-mokhnach, I have same problem, and I tried appium@beta, at least my testrun is good now.

**Comment by mykola-mokhnach** [comment]
Closed as fixed
