### ISSUE TITLE
Unable to click on an element in bluetooth screen of iOS device

### ISSUE THREAD

**Issue by iamabilash** [appium/appium#14089]
## The problem
WDA was not able to perform press action in some iterations on "More Info" element for a paired device on Bluetooth Screen. 

## Environment

* Appium version (or git revision) that exhibits the issue:   Latest
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Mac OS Catalina/Xcode 11.3.1
* Node.js version (unless using Appium.app|exe): N/A
* Npm or Yarn package manager: N/A
* Mobile platform/version under test:  iOS/13.3.1
* Real device or emulator/simulator: Real Device (iPhone XR)

## Details
Paired a device using bluetooth and tried to click on "More Info" button using WDA.It worked for some iterations. But in some cases, WDA was not able to press the button.However the response was always the same.

Response: { "value" : null, "sessionId" : "B95282F5-8096-4882-92B4-073D918E4453" }

## Link to Appium logs

Snippet of logs for finding & pressing on "More Info" element  taken from Xcode :

 t =    66.57s         Find: Descendants matching type Alert
    t =    66.57s     Synthesize event
    t =    68.75s Find the Application 'com.apple.Preferences'
    t =    68.75s     Requesting snapshot of accessibility hierarchy for app with pid 321
    t =    68.88s Get all elements bound by accessibility element for: Elements matching predicate '"More Info" IN identifiers'
    t =    68.88s     Requesting snapshot of accessibility hierarchy for app with pid 321
    t =    68.96s     Find: Descendants matching type Any
    t =    68.96s     Find: Elements matching predicate '"More Info" IN identifiers'
    t =    68.97s Find the "More Info" Button
    t =    68.98s     Requesting snapshot of accessibility hierarchy for app with pid 321
    t =    69.05s     Find: Descendants matching type Any
    t =    69.06s     Find: Elements matching predicate '"More Info" IN identifiers'
    t =    69.06s     Find: Identity Binding
    t =    71.29s Find the "More Info" Any
    t =    71.29s     Requesting snapshot of accessibility hierarchy for app with pid 321
    t =    71.42s     Find: Descendants matching type Any
    t =    71.42s     Find: Elements matching predicate '"More Info" IN identifiers'
    t =    71.43s     Find: Identity Binding
    t =    72.44s     Find the "More Info" Any (retry 1)
    t =    72.45s         Requesting snapshot of accessibility hierarchy for app with pid 321
    t =    72.56s         Find: Descendants matching type Any
    t =    72.56s         Find: Elements matching predicate '"More Info" IN identifiers'
    t =    72.57s         Find: Identity Binding
    t =    73.58s     Find the "More Info" Any (retry 2)
    t =    73.59s         Requesting snapshot of accessibility hierarchy for app with pid 321
    t =    73.69s         Find: Descendants matching type Any
    t =    73.69s         Find: Elements matching predicate '"More Info" IN identifiers'
    t =    73.70s         Find: Identity Binding
    t =    73.70s     Collecting extra data to assist test failure triage
    t =    73.70s         Requesting snapshot of accessibility hierarchy for app with pid 321
    t =    73.83s         Requesting snapshot of accessibility hierarchy for app with pid 321
    t =    73.94s         Find: Descendants matching type Any
    t =    73.95s         Find: Elements matching predicate '"More Info" IN identifiers'
    t =    73.96s         Find: Identity Binding
2020-03-19 11:19:04.625081+0530 WebDriverAgentRunner-Runner[312:13820] Enqueue Failure: Failed to get matching snapshot: No matches found for Identity Binding from input {(
    label: 'More Info'
)} /Users/abilash/Documents/Projects/Appium/WebDriverAgentRunner/UITestingUITests.m 38 1
    t =    73.99s Find the "More Info" Button
    t =    73.99s     Requesting snapshot of accessibility hierarchy for app with pid 321
    t =    74.06s     Find: Descendants matching type Any
    t =    74.06s     Find: Elements matching predicate '"More Info" IN identifiers'
    t =    74.06s     Find: Identity Binding
    t =    75.07s     Find the "More Info" Button (retry 1)
    t =    75.08s         Requesting snapshot of accessibility hierarchy for app with pid 321
    t =    75.21s         Find: Descendants matching type Any
    t =    75.22s         Find: Elements matching predicate '"More Info" IN identifiers'
    t =    75.22s         Find: Identity Binding
    t =    76.23s     Find the "More Info" Button (retry 2)
    t =    76.24s         Requesting snapshot of accessibility hierarchy for app with pid 321
    t =    76.38s         Find: Descendants matching type Any
    t =    76.38s         Find: Elements matching predicate '"More Info" IN identifiers'
    t =    76.39s         Find: Identity Binding
    t =    76.40s     Collecting extra data to assist test failure triage
    t =    76.40s         Requesting snapshot of accessibility hierarchy for app with pid 321
    t =    76.53s         Requesting snapshot of accessibility hierarchy for app with pid 321
    t =    76.65s         Find: Descendants matching type Any
    t =    76.66s         Find: Elements matching predicate '"More Info" IN identifiers'
    t =    76.66s         Find: Identity Binding
2020-03-19 11:19:07.297958+0530 WebDriverAgentRunner-Runner[312:13820] Enqueue Failure: Failed to get matching snapshot: No matches found for Identity Binding from input {(
    label: 'More Info'
)} /Users/abilash/Documents/Projects/Appium/WebDriverAgentRunner/UITestingUITests.m 38 1
    t =    76.77s Find the "More Info" Button
    t =    76.78s     Requesting snapshot of accessibility hierarchy for app with pid 321
    t =    76.92s     Find: Descendants matching type Any
    t =    76.92s     Find: Elements matching predicate '"More Info" IN identifiers'
    t =    76.93s     Find: Identity Binding
    t =    77.94s     Find the "More Info" Button (retry 1)
    t =    77.94s         Requesting snapshot of accessibility hierarchy for app with pid 321
    t =    78.08s         Find: Descendants matching type Any
    t =    78.09s         Find: Elements matching predicate '"More Info" IN identifiers'
    t =    78.09s         Find: Identity Binding
    t =    79.10s     Find the "More Info" Button (retry 2)
    t =    79.11s         Requesting snapshot of accessibility hierarchy for app with pid 321
    t =    79.25s         Find: Descendants matching type Any
    t =    79.26s         Find: Elements matching predicate '"More Info" IN identifiers'
    t =    79.26s         Find: Identity Binding
    t =    79.27s     Collecting extra data to assist test failure triage
    t =    79.27s         Requesting snapshot of accessibility hierarchy for app with pid 321
    t =    79.39s         Requesting snapshot of accessibility hierarchy for app with pid 321
    t =    79.52s         Find: Descendants matching type Any
    t =    79.53s         Find: Elements matching predicate '"More Info" IN identifiers'
    t =    79.53s         Find: Identity Binding
2020-03-19 11:19:10.166765+0530 WebDriverAgentRunner-Runner[312:13820] Enqueue Failure: Failed to get matching snapshot: No matches found for Identity Binding from input {(
    label: 'More Info'
)} /Users/abilash/Documents/Projects/Appium/WebDriverAgentRunner/UITestingUITests.m 38 1
    t =    79.53s Tap "More Info" Button
    t =    79.53s     Find the "More Info" Button
    t =    79.54s         Requesting snapshot of accessibility hierarchy for app with pid 321
    t =    79.62s         Find: Descendants matching type Any
    t =    79.62s         Find: Elements matching predicate '"More Info" IN identifiers'
    t =    79.63s         Find: Identity Binding
    t =    80.63s         Find the "More Info" Button (retry 1)
    t =    80.64s             Requesting snapshot of accessibility hierarchy for app with pid 321
    t =    80.78s             Find: Descendants matching type Any
    t =    80.78s             Find: Elements matching predicate '"More Info" IN identifiers'
    t =    80.79s             Find: Identity Binding
    t =    81.79s         Find the "More Info" Button (retry 2)
    t =    81.80s             Requesting snapshot of accessibility hierarchy for app with pid 321
    t =    81.94s             Find: Descendants matching type Any
    t =    81.95s             Find: Elements matching predicate '"More Info" IN identifiers'
    t =    81.96s             Find: Identity Binding
    t =    81.96s         Collecting extra data to assist test failure triage
    t =    81.96s             Requesting snapshot of accessibility hierarchy for app with pid 321
    t =    82.08s             Requesting snapshot of accessibility hierarchy for app with pid 321
    t =    82.20s             Find: Descendants matching type Any
    t =    82.21s             Find: Elements matching predicate '"More Info" IN identifiers'
    t =    82.22s             Find: Identity Binding
2020-03-19 11:19:12.851526+0530 WebDriverAgentRunner-Runner[312:13820] Enqueue Failure: Failed to get matching snapshot: No matches found for Identity Binding from input {(
    label: 'More Info'
)} 

## Code To Reproduce Issue [ Good To Have ]
Find & Press on "More Info" Element on paired device in  bluetooth Screen.

**Comment by mykola-mokhnach** [comment]
Clicks are performed by XCTest. I don't think there is anything we could change on Appium side. You could try to click by coordinates as a workaround.

**Comment by iamabilash** [comment]
Is there any way to get the error response if WDA fails to click on the element because it always gives the same response for the click?

Also, I have tried to debug the issue and found out that while resolving the query, resolveOrRaiseTestFailure method doesn't throw any exception for Enqueue failure. Is there any way to handle this exception?

**Comment by mykola-mokhnach** [comment]
Nothing I know of. Please let us know if you find one.

**Comment by mykola-mokhnach** [comment]
...Or push a PR directly to WDA

**Comment by mykola-mokhnach** [comment]
I would also try to play with `defaultActiveApplication` and `activeAppDetectionPoint` settings. It might be that control belongs to a different application whose UI is built via IPC. In such case setting a proper application for lookup might help.

**Comment by iamabilash** [comment]
I will try it but I don't think it is related to it. Issue seems to be occurred because of the continuous scan in the bluetooth screen.

One more thing, When I update the elements extract query from allElementsBoundByAccessibilityElement to allElementsBoundByIndex failure occurrence is quite low. Do you think playing around it could fix the issue?

**Comment by mykola-mokhnach** [comment]
yes, it always makes sense to do that until you find the most stable solution. At the end we could add another setting to make this logic more configurable in WDA or have better errors handling

**Comment by iamabilash** [comment]
okay, I will try to look more into it. Thank you for the help.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
