### ISSUE TITLE
Unable to launch Avd when integrating appium with jenkins

### ISSUE THREAD

**Issue by Amrkamel1** [appium/appium#14087]
## The problem
Unable to launch AVD when integrating appium test with jenkins, appium session is starting programatically 

## Environment

* Appium version 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Window 10
* Node.js version (unless using Appium.app|exe): 12.14.1
* Npm or Yarn package manager: 6.13.6
* Mobile platform/version under test: android
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: CLI

## Details
I'm  integrating appium with Jenkins trying to execute mobile automation test running against emulator, everything is working fine locally but with Jenkins, it's not, however, when I'm running same test but running appium manually from CLI , test executed fine with Jenkins

## Link to Appium logs

    `[debug] [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided

     [debug] [BaseDriver] Creating session with W3C capabilities: {

     [debug] [BaseDriver]   "alwaysMatch": {
 
     [debug] [BaseDriver]     "platformName": "android",

     [debug] [BaseDriver]     "appium:app": "C:\\Program Files (x86)\\Jenkins\\workspace\\SafeApp-  MobileAutomationFrameWork\\src\\main\\resources\\Safe.apk",

    [debug] [BaseDriver]     "appium:appActivity": "com.trackerproducts.mobile.MainActivity",

    [debug] [BaseDriver]     "appium:appPackage": "com.trackerproducts.mobile",

    [debug] [BaseDriver]     "appium:autoGrantPermissions": true,

    [debug] [BaseDriver]     "appium:automationName": "uiautomator2",

    [debug] [BaseDriver]     "appium:avd": "Pixel",

    [debug] [BaseDriver]     "appium:avdLaunchTimeout": 15000,

    [debug] [BaseDriver]     "appium:clearSystemFiles": true,

    [debug] [BaseDriver]     "appium:deviceName": "emulator-5554",

    [debug] [BaseDriver]     "appium:nativeWebScreenshot": true,

    [debug] [BaseDriver]     "appium:platformVersion": "10"

    [debug] [BaseDriver]   },

    [debug] [BaseDriver]   "firstMatch": [

    [debug] [BaseDriver]     {}

    [debug] [BaseDriver]   ]

    [debug] [BaseDriver] }

    [BaseDriver] Session created with session id: 2545be3c-1361-4c8d-96ca-0c508aa4035d

    [BaseDriver] Using local app 'C:\Program Files (x86)\Jenkins\workspace\SafeApp-    MobileAutomationFrameWork\src\main\resources\Safe.apk'

    [debug] [UiAutomator2] Checking whether app is actually present

    [ADB] Found 3 'build-tools' folders under 'C:\users\warrior\appData\local\Android\Sdk' (newest first):

    [ADB]     C:/users/warrior/appData/local/Android/Sdk/build-tools/29.0.3

    [ADB]     C:/users/warrior/appData/local/Android/Sdk/build-tools/29.0.2

    [ADB]     C:/users/warrior/appData/local/Android/Sdk/build-tools/28.0.3

    [ADB] Using 'adb.exe' from 'C:\users\warrior\appData\local\Android\Sdk\platform-tools\adb.exe'

    [debug] [ADB] Trying to find 'Pixel' emulator

    [debug] [ADB] Getting connected emulators

    [debug] [ADB] Getting connected devices...

    [debug] [ADB] No connected devices have been detected

    [debug] [ADB] 0 emulator(s) connected

    [debug] [ADB] Emulator 'Pixel' not running

    [debug] [ADB] Launching Emulator with AVD Pixel, launchTimeout 15000ms and readyTimeout 60000ms

    [ADB] Using 'emulator.exe' from 'C:\users\warrior\appData\local\Android\Sdk\emulator\emulator.exe'

    [debug] [UiAutomator2] Deleting UiAutomator2 session

    [debug] [BaseDriver] Event 'newSessionStarted' logged at 1584569044394 (23:04:04 GMT+0100 (Central European Standard Time))

    [debug] [W3C] Encountered internal error running command: Error: Avd 'Pixel' is not available.     please select your avd name from one of these: '()'

    [debug] [W3C]     at ADB.checkAvdExist (C:\Users\warrior\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:802:11)

    [debug] [W3C]     at ADB.launchAVD (C:\Users\warrior\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:695:3)

    [debug] [W3C]     at Object.prepareEmulator (C:\Users\warrior\AppData\Roaming\npm\node_modules\appium\node_modules\appium-android-driver\lib\android-helpers.js:127:3)

    [debug] [W3C]     at Object.getDeviceInfoFromCaps (C:\Users\warrior\AppData\Roaming\npm\node_modules\appium\node_modules\appium-android-driver\lib\android-helpers.js:189:5)

    [debug] [W3C]     at AndroidUiautomator2Driver.startUiAutomator2Session (C:\Users\warrior\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:286:26)

    [debug] [W3C]     at AndroidUiautomator2Driver.createSession (C:\Users\warrior\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:208:7)

    [debug] [W3C]     at AppiumDriver.createSession (C:\Users\warrior\AppData\Roaming\npm\node_modules\appium\lib\appium.js:358:35)

    [HTTP] <-- POST /wd/hub/session 500 293 ms - 727

[HTTP] 

    Starting test suite for Adding Case Functionality Test Cases
`

## Code To Reproduce Issue [ Good To Have ]

    ` private void createAppiumInstance() {
         service = AppiumDriverLocalService
                .buildService(new AppiumServiceBuilder()
                        .usingDriverExecutable(new File("C:\\Program Files\\nodejs\\node.exe"))
                        .withAppiumJS(new File("C:\\Users\\warrior\\AppData\\Roaming\\npm\\node_modules\\appium\\build\\lib\\main.js"))
                        .usingAnyFreePort()
                        .withArgument(AppiumArgs.ALLOWINSECURE, "adb_shell"));
        service.start();
    }

    @BeforeSuite(alwaysRun = true)
    @Parameters({"deviceName","platformName","platformVersion","avd","automationName","URL_","port"})
    public void setUp (String deviceName, String platformName, String platformVersion, String avd, String automationName, String URL_, String port) throws MalformedURLException, InterruptedException {
        System.out.println("==> Driver Is Initiating <==");

        DesiredCapabilities dc = new DesiredCapabilities();

    //      Mobile Config Setup
        dc.setCapability(MobileCapabilityType.DEVICE_NAME, deviceName);
        dc.setCapability("platformName",platformName);
        dc.setCapability("platformVersion",platformVersion);
        dc.setCapability("avd",avd);
        dc.setCapability("avdLaunchTimeout",15000);
        dc.setCapability("avdReadyTimeout",15000);
        dc.setCapability(MobileCapabilityType.AUTOMATION_NAME,automationName);

    //        dc.setCapability("isHeadless",true);

        //Application Config Setup
        dc.setCapability(MobileCapabilityType.APP, new File("src/main/resources/Test.apk").getAbsolutePath());
        dc.setCapability(AndroidMobileCapabilityType.APP_PACKAGE,"com.trest.mobile");
        dc.setCapability(AndroidMobileCapabilityType.APP_ACTIVITY,"com.trtests.mobile.MainActivity");
        dc.setCapability(AndroidMobileCapabilityType.AUTO_GRANT_PERMISSIONS,true);
        dc.setCapability(MobileCapabilityType.CLEAR_SYSTEM_FILES,true);
    //        dc.setCapability("showGradleLog",true);
            dc.setCapability(AndroidMobileCapabilityType.NATIVE_WEB_SCREENSHOT,true);

        createAppiumInstance();
    //        driver = new AndroidDriver(new URL("http://"+URL_+":"+port+"/wd/hub"),dc);
        driver = new AndroidDriver(service.getUrl(),dc);

        driver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);

        Map<String, Object> firstArgs = new HashMap<>();
        Map<String, Object> SecondArgs = new HashMap<>();
        Map<String, Object> ThirdArgs = new HashMap<>();

        firstArgs.put("command", "settings");
        SecondArgs.put("command", "settings");
        ThirdArgs.put("command", "settings");

        firstArgs.put("args", Lists.newArrayList("put global window_animation_scale 0.0"));
        SecondArgs.put("args", Lists.newArrayList("put global animator_duration_scale 0.0"));
        ThirdArgs.put("args", Lists.newArrayList("put global transition_animation_scale 0.0"));

        driver.executeScript("mobile: shell", firstArgs);
        driver.executeScript("mobile: shell", SecondArgs);
        driver.executeScript("mobile: shell", ThirdArgs);

        LoginPage start = new LoginPage();
        start.createPentestDomain();

        //driver.startRecordingScreen();

    }
`

**Comment by KazuCocoa** [comment]
Does the machine has `Pixel` named emulator instance?
If the Jenkins machine does not support x86 architecture, the emulator is very slow. 15s timeout is not enough, I believe.

---

`disableWindowAnimation` capability works as same as `put global window_animation_scale 0.0`, btw.

**Comment by Amrkamel1** [comment]
> Does the machine has `Pixel` named emulator instance?
> If the Jenkins machine does not support x86 architecture, the emulator is very slow. 15s timeout is not enough, I believe.
> 
> `disableWindowAnimation` capability works as same as `put global window_animation_scale 0.0`, btw.

Jenkins is on same local machine, and yes there is pixel emulator, when i am running the test through intellij its working fine , and when im running it throw Jenkins that is running on same machine it timeouts

what i have notices that when im executing the test from intellij appium keep searching for the emulator for many times and locating it, but in jenkins appium search for once then break right away

**Comment by KazuCocoa** [comment]
I see. Can you launch emulator via Jenkin process?

https://github.com/appium/appium-adb/blob/251494a7a1dcaa10c39b57b70ba6cd5e388f3264/lib/tools/system-calls.js#L778-L807

https://github.com/appium/appium-adb/blob/251494a7a1dcaa10c39b57b70ba6cd5e388f3264/lib/tools/system-calls.js#L690-L737

I mean how about calling emulator command directly in Jenkins script.
e.g.
```
$ emulator -list-avds
```

**Comment by Amrkamel1** [comment]
@KazuCocoa 
im not quite sure what i should do ?

**Comment by KazuCocoa** [comment]
Calling emulator command appium does internally via Jenkins process.
I wondered if such command via Jenkins process did not work.

Maybe `C:\users\warrior\appData\local\Android\Sdk\emulator\emulator.exe -list-avds` does not have `Pixel`, according to your attached log.
https://github.com/appium/appium-adb/blob/251494a7a1dcaa10c39b57b70ba6cd5e388f3264/lib/tools/system-calls.js#L778-L807

**Comment by amedvedjev** [comment]
@Amrkamel1  to check  "emulator -list-avds" with jenkins add "Execute Shell" before test and enter this line there.
How you configure your job in jenkins?

**Comment by Amrkamel1** [comment]
> 
> 
> Calling emulator command appium does internally via Jenkins process.
> I wondered if such command via Jenkins process did not work.
> 
> Maybe `C:\users\warrior\appData\local\Android\Sdk\emulator\emulator.exe -list-avds` does not have `Pixel`, according to your attached log.
> https://github.com/appium/appium-adb/blob/251494a7a1dcaa10c39b57b70ba6cd5e388f3264/lib/tools/system-calls.js#L778-L807

it shown, the different between running appium throw jenkins and without jenkins 
that without jenkins appium keep trying to find the emulator for many times unlike appium from jenkins after first try it terminate the build
![image](https://user-images.githubusercontent.com/32042806/77107731-6c337c80-6a21-11ea-9c98-dadbb3a15efc.png)

**Comment by Amrkamel1** [comment]
> 
> 
> @Amrkamel1 to check "emulator -list-avds" with jenkins add "Execute Shell" before test and enter this line there.
> How you configure your job in jenkins?

its basic configuation, execute maven clean test with each push to the repo
i have added this lshell command if that what u mean but no use 

![image](https://user-images.githubusercontent.com/32042806/77108072-e5cb6a80-6a21-11ea-8f0f-f0456d1be3de.png)

**Comment by Amrkamel1** [comment]
@KazuCocoa @amedvedjev 
it seems that Jenkins cant see the emulators 

![image](https://user-images.githubusercontent.com/32042806/77112180-d996db80-6a28-11ea-9a37-8323f64672d7.png)

**Comment by Amrkamel1** [comment]
The update issue has been resolved.

by setting global variables for Jenkins, it won't be able to execute the commands no matter if you are in some root or not i have fixe that as shown below

![image](https://user-images.githubusercontent.com/32042806/77123345-2afe9500-6a40-11ea-9e7b-a22b0189b5e5.png)

After that I encountered another issue, however, Jenkins detects the emulator but couldn't run it as e Jenkins itself running as a service in the OS (windows) doesn't have the ability to use the GPU and emulate the device, so the only way to make emulator works with Jenkins is to set headless cap in you script .

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
