### ISSUE TITLE
App elements tree is not fully seen on React Native tvOS apps

### ISSUE THREAD

**Issue by BoazWarshawsky** [appium/appium#14086]
## The problem
I have a tvOS react native app that I am testing.
I am having a problem that not all the elements on the screen are accessible, when I am launching the app with the Appium Elements Inspector I am seeing that in some node the elements tree stop showing the elements under it.  

Since my project based on React Native, I can also confirm that the same problem is happening when running the iOS Mobile app.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): None
* Desktop OS/version used to run Appium: Desktop
* Node.js version (unless using Appium.app|exe): 8.16.0
* Npm or Yarn package manager: yarn
* Mobile platform/version under test: tvOS (and iOS)
* Real device or emulator/simulator: Apple TV Simulator (and iPhone X Simulator) 
* Appium CLI or Appium.app|exe: Appium.app

## Details
Since my app is a React Native app, I took care to add to all the views `testID` with the expected value.

As you can see in the following image, all the elements that under the element `667c74d-09...` are not accessible and I cannot dig inside the tree in the Elements Inspector tool:
<img width="1189" alt="Screen Shot 2020-03-18 at 21 41 00" src="https://user-images.githubusercontent.com/32813176/77000526-39c24a80-6961-11ea-8371-b24bffbd7622.png">

## Link to Appium logs
https://assets-secure.applicaster.com/qa/zapp_qa/manual/boaz/tvOS.log

**Comment by BoazWarshawsky** [comment]
@mykola-mokhnach @imurchie Hi!
Can you please advise with this issue I have?

Thanks!

**Comment by KazuCocoa** [comment]
What the output of `mobile: source`  with `format: description`?
https://github.com/appium/appium/issues/13595#issuecomment-553298730

If the result was the same, I assume XCTest framework can not get them.
(Perhaps nothing can do in Appium side)

**Comment by BoazWarshawsky** [comment]
@KazuCocoa 
I tried getting the source with my Python test `self.driver.page_source` and also there the tree I get stops "digging"-in in the same node.

My question is, is there anything I can do on the client-side of the react native in order XCTest would be able to see the whole tree? After all, XCTest does supporting react native apps.

**Comment by KazuCocoa** [comment]
I have no much RN experience, unfortunately.
You could see articles/posts about RN and XCTest. Some of them had a workaround. For example, adding/removimg elements, for example.

https://www.google.com/search?biw=1872&bih=1099&sxsrf=ALeKk00uSDyXpeReMXmmLzskDEMCoxBu_Q%3A1584864107030&ei=axt3XsLBAaOzmAWVq4OQCg&q=xcuitest+react+native+element+cannot+find+element&oq=xcuitest+react+native+element+cannot+find+element&gs_l=psy-ab.3..33i160.10077.12494..12607...0.3..0.122.1977.6j13......0....1..gws-wiz.......0i71j33i21.ppVhn97RTg4&ved=0ahUKEwiCo_fwzq3oAhWjGaYKHZXVAKI4ChDh1QMICw&uact=5

One possible case is if the view has webview context, you can try get elements on WebView context

**Comment by BoazWarshawsky** [comment]
@KazuCocoa I did not solve my issue yet, but I do understand why it's on XCUITests side issue.
Thanks for trying to help
:-(

**Comment by KazuCocoa** [comment]
Okay, thanks.
It will be appreciated leaving a message here if you can find a solution.

**Comment by BoazWarshawsky** [comment]
@KazuCocoa I am currently using python-client version 40.0.0, do you think that upgrading to the latest 50.0.0, might help here?
https://github.com/appium/python-client

**Comment by KazuCocoa** [comment]
No, I don't think so. This kind of issue is Appium server side.

**Comment by jcerrutti** [comment]
Did you find a solution for this?
