### ISSUE TITLE
http://appium.io/ certificate is broken

### ISSUE THREAD

**Issue by renannprado** [appium/appium#14093]
![image](https://user-images.githubusercontent.com/2359543/77189290-9f384780-6ad7-11ea-8c8b-8e4c2f68b1ae.png)

**Comment by mykola-mokhnach** [comment]
I don't observe any issues though:

<img width="578" alt="cert" src="https://user-images.githubusercontent.com/7767781/77192721-4bc8f800-6add-11ea-9536-4c92f0459532.png">

**Comment by KazuCocoa** [comment]
I checked Chrome, Brave, Edge, Safari and Firefox but they worked well

**Comment by renannprado** [comment]
Sorry, stupid me. I opened in HTTP and since there's no redirect to HTTPS (very common nowadays), I didn't realize that and thought the certificate was broken.

My bad.
