### ISSUE TITLE
unable to do scroll down in Android

### ISSUE THREAD

**Issue by SonaliGupta6** [appium/appium#14095]
I need to file the form. and certain element will be visible if we do scroll down 

Below are the pattern which i have used for scroll down but nothing is working for native application.
1.  public boolean accessElementsUsingJavaScript(String action, MobileElement ele) {
		boolean result = false;
		try {
			if (action.equalsIgnoreCase("focus")) {

				String javaScript = "argument[0].scrollIntoView()";
				driver.executeScript(javaScript, ele);
				result = true;
			}
		} catch (Exception e) {
			System.out.println("<<Exception>>" + e.getMessage());
			result = false;
		}
		return result;

	}

2.  	TouchActions action = new TouchActions(driver);
		//action.press(new PointOption().withCoordinates(207, 1400));
		//action.moveToElement(target, xOffset, yOffset)
		//action.moveTo(new PointOption().withCoordinates(207, 1400));
		//action.moveToElement((MobileElement) driver.findElementByXPath(path));
		//action.down(15, 1099);
		action.scroll(15, 1503);

3. recently post 
Designing a Cross-Platform Swipe/Scroll Helper

Nothing is working for me

**Comment by mykola-mokhnach** [comment]
Kindly use Appium [forum](discuss.appium.io) to ask questions
