### ISSUE TITLE
IOS react native cannot move slider

### ISSUE THREAD

**Issue by chocowhiskey** [appium/appium#14090]
## The problem

Cannot move slider in IOS Simulator

## Environment

* Appium version: Version 1.15.1 (1.15.1.20191013.2)
* Desktop OS/version used to run Appium: Macos Catalina
* Real device or emulator/simulator: IOS simulator, iphone 11 13.1 

## Details

Tried to move the slider with press(coordinates).moveto(coordinates).release and element.sendkeys('0.8'), also trying with id and xpath but nothing works. Someone got a solution for this? Slider is not moving at all :-/

## Link to Appium logs

[Xcode] 2020-03-19 16:04:23.810900+0100 WebDriverAgentRunner-Runner[9175:49677] Enqueue Failure: Failed to synthesize event: Failed to scroll to visible (by AX action) Other, {{218.0, 618.5}, {20.0, 20.0}}, error: Error kAXErrorCannotComplete performing AXAction 2003 on element AX element pid: 22576, elementOrHash.elementID: 140240694663488.390 /Applications/Appium.app/Contents/Resources/app/node_modules/appium-webdriveragent/WebDriverAgentRunner/UITestingUITests.m 38 1
[Xcode] 
[Xcode]     t = 26845.21s Checking existence of `Keyboard`
[Xcode] 
[Xcode]     t = 26845.21s     Requesting snapshot of accessibility hierarchy for app with pid 22576
[Xcode] 
[Xcode]     t = 26845.28s     Find: Descendants matching type Keyboard
[Xcode] 
[Xcode]     t = 26845.38s Checking existence of `Keyboard`
[Xcode] 
[Xcode]     t = 26845.38s     Requesting snapshot of accessibility hierarchy for app with pid 22576
[Xcode] 
[Xcode]     t = 26845.44s     Find: Descendants matching type Keyboard
[Xcode] 
[Xcode]     t = 26845.55s Checking existence of `Keyboard`
[Xcode] 
[Xcode]     t = 26845.55s     Requesting snapshot of accessibility hierarchy for app with pid 22576
[Xcode] 
[Xcode]     t = 26845.61s     Find: Descendants matching type Keyboard
[Xcode] 
[Xcode]     t = 26845.72s Checking existence of `Keyboard`
[Xcode] 
[Xcode]     t = 26845.72s     Requesting snapshot of accessibility hierarchy for app with pid 22576
[Xcode] 
[Xcode]     t = 26845.78s     Find: Descendants matching type Keyboard
[Xcode] 
[Xcode]     t = 26845.89s Checking existence of `Keyboard`
[Xcode] 
[Xcode]     t = 26845.89s     Requesting snapshot of accessibility hierarchy for app with pid 22576
[Xcode] 
[Xcode]     t = 26845.95s     Find: Descendants matching type Keyboard
[Xcode] 
[Xcode]     t = 26846.06s Checking existence of `Keyboard`
[Xcode] 
[Xcode]     t = 26846.06s     Requesting snapshot of accessibility hierarchy for app with pid 22576
[Xcode] 
[Xcode]     t = 26846.12s     Find: Descendants matching type Keyboard
[Xcode] 
[WD Proxy] Got an unexpected response with status 500: {"value":{"error":"unknown error","message":"Error Domain=com.facebook.WebDriverAgent Code=1 \"Keyboard is not present\" UserInfo={NSLocalizedDescription=Keyboard is not present}","traceback":""},"sessionId":"977B8AD1-3102-4DD5-8F7A-18359D746714"}
[W3C] Matched W3C error code 'unknown error' to UnknownError

## Code To Reproduce Issue [ Good To Have ]

slider.setValue('0.8')

**Comment by mykola-mokhnach** [comment]
> press(coordinates).moveto(coordinates).release

In order to synthesise swipe action a delay of about 0.5 seconds must be added after press

> element.sendkeys('0.8') 

Are you sure the correct element is being located? I see XCTest is trying to raise the keyboard, which should not be happening if the element is a slider. It is impossible to say more without the full server log

**Comment by imurchie** [comment]
You may also need to update to the latest Appium, which has some fixes for React controlled components.

**Comment by chocowhiskey** [comment]
Thanks guys for the help.
I figured out, that it was just longPress instead of press 👍🏽
