### ISSUE TITLE
Can not double_click twice in maximize screen mode.

### ISSUE THREAD

**Issue by lpeter218065** [appium/appium#14092]
## The problem

Can not double_click twice in maximize screen mode.

Steps:

1. maximize the native window using `app_driver.maximize_window()`
2. double click the element that found by name - (this step worked fine)
3. double click another element that found by name - (the step failed,  the element can not be found)
Note:  if I do not maxmize the window,  double click worked fine for both step 2 an step 3

## Environment

* Appium version (or git revision) that exhibits the issue: try two versions  v1.15.1 v1.17.x
* Desktop OS/version used to run Appium: Win 10 OS
* Node.js version (unless using Appium.app|exe): v12.14.0
* Npm or Yarn package manager:  yarn run v1.12.3

**Comment by mykola-mokhnach** [comment]
Please provide the proper environment description and attach the full server log

**Comment by lpeter218065** [comment]
@mykola-mokhnach updated the environment
btw how to get the full server log

**Comment by lpeter218065** [comment]
I follow the step http://appium.io/docs/en/commands/session/logs/get-log/#appium-server 

but getting error
![image](https://user-images.githubusercontent.com/4799347/77165758-e6c9ce00-6aed-11ea-88cf-2209211549a2.png)

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing we can do there from Appium side, since appium driver is maintained by Microsoft. Consider reporting your issue to https://github.com/microsoft/WinAppDriver
