### ISSUE TITLE
Unable to interact with 2 simulators

### ISSUE THREAD

**Issue by 13817458995** [appium/appium#14099]
## The problem

Start 2 Appium drivers, after driver2 is started, session1 is not exist

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: 12.4
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe: Appium CLI

## Code

AppiumDriver driver = null;
		AppiumDriver driver2=null;

		DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
		desiredCapabilities.setCapability("automationName", "XCUITest");
		desiredCapabilities.setCapability("platformName", "iOS");
		desiredCapabilities.setCapability("platformVersion", "12.4");
		desiredCapabilities.setCapability("deviceName", "test");
		desiredCapabilities.setCapability("udid", "7511DBA1-204C-48C5-902E-EF00E27F7BFD");
		desiredCapabilities.setCapability("bundleId","XXXXXXXX");
		driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), desiredCapabilities);
		
		DesiredCapabilities desiredCapabilities2 = new DesiredCapabilities();
		desiredCapabilities2.setCapability("automationName", "XCUITest");
		desiredCapabilities2.setCapability("platformName", "iOS");
		desiredCapabilities2.setCapability("platformVersion", "12.4");
		desiredCapabilities2.setCapability("deviceName", "test2");
		desiredCapabilities2.setCapability("bundleId","XXXXXXXX");
		desiredCapabilities2.setCapability("udid", "004C51D5-CA8E-4895-B514-8F31F80B938F");
		driver2 = new IOSDriver(new URL("http://127.0.0.1:4725/wd/hub"), desiredCapabilities2);
		Thread.sleep(10000);
		
		driver.findElement(MobileBy.xpath("//XCUIElementTypeTextField[1]")).click();
		driver.findElement(MobileBy.xpath("//XCUIElementTypeTextField[1]")).sendKeys("122");
		
		driver2.findElement(MobileBy.xpath("//XCUIElementTypeTextField[1]")).click();
		driver2.findElement(MobileBy.xpath("//XCUIElementTypeTextField[1]")).sendKeys("122");
		
		driver.findElement(MobileBy.xpath("//XCUIElementTypeSecureTextField")).click();
		driver.findElement(MobileBy.xpath("//XCUIElementTypeSecureTextField")).sendKeys("111");
		
		driver2.findElement(MobileBy.xpath("//XCUIElementTypeSecureTextField")).click();
		driver2.findElement(MobileBy.xpath("//XCUIElementTypeSecureTextField")).sendKeys("111");

## Link to Appium logs
Calling AppiumDriver.findElement() with args: ["xpath","//XCUIElementTypeTextField[1]","2bd0c512-1afc-4caa-b944-686cf87eea20"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/BF8613AA-E196-4C22-AD52-0A60694C64A9/element] with body: {"using":"xpath","value":"//XCUIElementTypeTextField[1]"}
[debug] [WD Proxy] Got response with status 200: {"value":"Session does not exist","sessionId":"13241C02-564F-47BE-A473-C4F69F02B1A9","status":6}
[WD Proxy] Got an unexpected response: {"value":"Session does not exist","sessionId":"13241C02-564F-47BE-A473-C4F69F02B1A9","status":6}
[debug] [MJSONWP] Matched JSONWP error code 6 to NoSuchDriverError
[debug] [W3C (2bd0c512)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[debug] [W3C (2bd0c512)]     at XCUITestDriver.doNativeFind (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:130:13)
[HTTP] <-- POST /wd/hub/session/2bd0c512-1afc-4caa-b944-686cf87eea20/element 404 28 ms - 379
[HTTP] 
[Xcode] 2020-03-24 17:56:52.769 xcodebuild[12930:315611]  IDETestOperationsObserverDebug: Failed to move logarchive from /Users/admin/Library/Developer/CoreSimulator/Devices/7511DBA1-204C-48C5-902E-EF00E27F7BFD/data/tmp/test-session-systemlogs-2020.03.24_17-56-09-+0800.logarchive to diagnostics location /Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Test-WebDriverAgentRunner-2020.03.24_17-56-08-+0800.xcresult/Staging/2_Test/Diagnostics/iPad (6th generation)_7511DBA1-204C-48C5-902E-EF00E27F7BFD/test-session-systemlogs-2020.03.24_17-56-09-+0800.logarchive: Error Domain=NSCocoaErrorDomain Code=4 "“test-session-systemlogs-2020.03.24_17-56-09-+0800.logarchive” couldn’t be moved to “iPad (6th generation)_7511DBA1-204C-48C5-902E-EF00E27F7BFD” because either the former doesn’t exist, or the folder containing the latter doesn’t exist." UserInfo={NSSourceFilePathErrorKey=/Users/admin/Library/Developer/CoreSimulator/Devices/7511DBA1-204C-48C5-902E-EF00E27F7BFD/data/tmp/test-session-systemlogs-2020.03.24_17-56-09-+0800.logarchive, NSUserStringVariant=(
[Xcode]     Move
[Xcode] ), NSDestinationFilePath=/Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Test-WebDriverAgentRunner-2020.03.24_17-56-08-+0800.xcresult/Staging/2_Test/Diagnostics/iPad (6th generation)_7511DBA1-204C-48C5-902E-EF00E27F7BFD/test-session-systemlogs-2020.03.24_17-56-09-+0800.logarchive, NSFilePath=/Users/admin/Library/Developer/CoreSimulator/Devices/7511DBA1-204C-48C5-902E-EF00E27F7BFD/data/tmp/test-session-systemlogs-2020.03.24_17-56-09-+0800.logarchive, NSUnderlyingError=0x7ff9a091ac70 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode] 
[Xcode] 2020-03-24 17:56:52.770 xcodebuild[12930:315611]  IDETestOperationsObserverDebug: Failure collecting logarchive: “test-session-systemlogs-2020.03.24_17-56-09-+0800.logarchive” couldn’t be moved to “iPad (6th generation)_7511DBA1-204C-48C5-902E-EF00E27F7BFD” because either the former doesn’t exist, or the folder containing the latter doesn’t exist.
[Xcode] 
[Xcode] 2020-03-24 17:56:52.770 xcodebuild[12930:315604] [MT] IDETestOperationsObserverDebug: 42.901 elapsed -- Testing started completed.
[Xcode] 2020-03-24 17:56:52.771 xcodebuild[12930:315604] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
[Xcode] 2020-03-24 17:56:52.771 xcodebuild[12930:315604] [MT] IDETestOperationsObserverDebug: 42.901 sec, +42.901 sec -- end
[Xcode] 
[Xcode] 
[Xcode] Test session results, code coverage, and logs:
[Xcode] 	/Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Test-WebDriverAgentRunner-2020.03.24_17-56-08-+0800.xcresult
[Xcode] 
[Xcode] 
[Xcode] Failing tests:
[Xcode] 	WebDriverAgentRunner:
[Xcode] 		-[UITestingUITests testRunner]
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[Xcode] Testing started on 'iPad (6th generation)'
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'

**Comment by mykola-mokhnach** [comment]
Make sure you follow https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/parallel-tests.md

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
