### ISSUE TITLE
 Appium: Connecting Android Device : <— POST /wd/hub/session

### ISSUE THREAD

**Issue by Junaid1034** [appium/appium#14096]
Unable to connect a real devices with appium. Every time face same error " 

Appium: Connecting Android Device : <— POST /wd/hub/session
--

"

**Comment by mykola-mokhnach** [comment]
Please provide a proper issue description according to the given template. Closed as incomplete

**Comment by Junaid1034** [comment]
App gave me this error when I run the app on OPPO F11. When I run on another device then It’s working.

[Appium] Welcome to Appium v1.15.1
[Appium] Non-default server args:
[Appium] allowInsecure: {
[Appium] }
[Appium] denyInsecure: {
[Appium] }
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {“desiredCapabilities”:{“appActivity”:“com.finja.business.ui.activity.SplashActivity”,“appPackage”:“com.finja.business”,“BROWSER_NAME”:“Android”,“VERSION”:“9”,“platformName”:“Android”,“deviceName”:“6D7D4SSCSCQGV8V8”},“capabilities”:{“firstMatch”:[{“BROWSER_NAME”:“Android”,“VERSION”:“9”,“appium:appActivity”:“com.finja.business.ui.activity.SplashActivity”,“appium:appPackage”:“com.finja.business”,“appium:deviceName”:“6D7D4SSCSCQGV8V8”,“platformName”:“android”}]}}
[W3C] Calling AppiumDriver.createSession() with args: [{“appActivity”:“com.finja.business.ui.activity.SplashActivity”,“appPackage”:“com.finja.business”,“BROWSER_NAME”:“Android”,“VERSION”:“9”,“platformName”:“Android”,“deviceName”:“6D7D4SSCSCQGV8V8”},null,{“firstMatch”:[{“BROWSER_NAME”:“Android”,“VERSION”:“9”,“appium:appActivity”:“com.finja.business.ui.activity.SplashActivity”,“appium:appPackage”:“com.finja.business”,“appium:deviceName”:“6D7D4SSCSCQGV8V8”,“platformName”:“android”}]}]
[BaseDriver] Event ‘newSessionRequested’ logged at 1584993704557 (01:01:44 GMT+0500 (Pakistan Standard Time))
[BaseDriver] The capabilities [“BROWSER_NAME”,“VERSION”] are not standard capabilities and should have an extension prefix
[Appium]
[Appium] ======================================================================
[Appium] DEPRECATION WARNING:
[Appium]
[Appium] The ‘automationName’ capability was not provided in the desired
[Appium] capabilities for this Android session
[Appium]
[Appium] Setting ‘automationName=UiAutomator2’ by default and using the
[Appium] UiAutomator2 Driver
[Appium]
[Appium] The next major version of Appium (2.x) will require the
[Appium] ‘automationName’ capability to be set for all sessions on all
[Appium] platforms
[Appium]
[Appium] In previous versions (Appium <= 1.13.x), the default was
[Appium] ‘automationName=UiAutomator1’
[Appium]
[Appium] If you wish to use that automation instead of UiAutomator2, please
[Appium] add ‘automationName=UiAutomator1’ to your desired capabilities
[Appium]
[Appium] For more information about drivers, please visit
[Appium] http://appium.io/docs/en/about-appium/intro/ and explore the
[Appium] ‘Drivers’ menu
[Appium]
[Appium] ======================================================================
[Appium]
[Appium] Appium v1.15.1 creating new AndroidUiautomator2Driver (v1.37.2) session
[BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[BaseDriver] Creating session with W3C capabilities: {
[BaseDriver] “alwaysMatch”: {
[BaseDriver] “appium:BROWSER_NAME”: “Android”,
[BaseDriver] “appium:VERSION”: “9”,
[BaseDriver] “platformName”: “android”,
[BaseDriver] “appium:appActivity”: “com.finja.business.ui.activity.SplashActivity”,
[BaseDriver] “appium:appPackage”: “com.finja.business”,
[BaseDriver] “appium:deviceName”: “6D7D4SSCSCQGV8V8”
[BaseDriver] },
[BaseDriver] “firstMatch”: [
[BaseDriver] {}
[BaseDriver] ]
[BaseDriver] }
[BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[BaseDriver] BROWSER_NAME
[BaseDriver] VERSION
[BaseDriver] Session created with session id: a7bbe427-c0cd-4b99-831c-d215d984a44c
[UiAutomator2] Starting ‘com.finja.business’ directly on the device
[ADB] Using ‘adb.exe’ from ‘F:\Sdk\platform-tools\adb.exe’
[AndroidDriver] Retrieving device list
[ADB] Trying to find a connected android device
[ADB] Getting connected devices…
[ADB] Connected devices: [{“udid”:“6D7D4SSCSCQGV8V8”,“state”:“device”}]
[AndroidDriver] Using device: 6D7D4SSCSCQGV8V8
[ADB] Using ‘adb.exe’ from ‘F:\Sdk\platform-tools\adb.exe’
[ADB] Setting device id to 6D7D4SSCSCQGV8V8
[ADB] Running ‘F:\Sdk\platform-tools\adb.exe -P 5037 -s 6D7D4SSCSCQGV8V8 shell getprop ro.build.version.sdk’
[ADB] Current device property ‘ro.build.version.sdk’: 28
[ADB] Running ‘F:\Sdk\platform-tools\adb.exe -P 5037 -s 6D7D4SSCSCQGV8V8 shell getprop ro.build.version.release’
[ADB] Current device property ‘ro.build.version.release’: 9
[ADB] Device API level: 28
[UiAutomator2] Relaxing hidden api policy
[ADB] Running ‘F:\Sdk\platform-tools\adb.exe -P 5037 -s 6D7D4SSCSCQGV8V8 shell settings put global hidden_api_policy_pre_p_apps 1’
[UiAutomator2] Deleting UiAutomator2 session
[ADB] Running ‘F:\Sdk\platform-tools\adb.exe -P 5037 -s 6D7D4SSCSCQGV8V8 shell am force-stop com.finja.business’
[ADB] Removing forwarded port socket connection: 8200
[ADB] Running ‘F:\Sdk\platform-tools\adb.exe -P 5037 -s 6D7D4SSCSCQGV8V8 forward --remove tcp:8200’
[UiAutomator2] Unable to remove port forward ‘Error executing adbExec. Original error: ‘Command ‘F:\Sdk\platform-tools\adb.exe -P 5037 -s 6D7D4SSCSCQGV8V8 forward --remove tcp:8200’ exited with code 1’; Stderr: ‘adb.exe: error: listener ‘tcp:8200’ not found’; Code: ‘1’’
[UiAutomator2] Restoring hidden api policy to the device default configuration
[ADB] Running ‘F:\Sdk\platform-tools\adb.exe -P 5037 -s 6D7D4SSCSCQGV8V8 shell settings delete global hidden_api_policy_pre_p_apps’
[BaseDriver] Event ‘newSessionStarted’ logged at 1584993706008 (01:01:46 GMT+0500 (Pakistan Standard Time))
[W3C] Encountered internal error running command: Error executing adbExec. Original error: ‘Command ‘F:\Sdk\platform-tools\adb.exe -P 5037 -s 6D7D4SSCSCQGV8V8 shell settings delete global hidden_api_policy_pre_p_apps’ exited with code 255’; Stderr: ‘Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
[W3C]
[W3C] java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
[W3C] at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2055)
[W3C] at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1113)
[W3C] at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1096)
[W3C] at com.android.providers.settings.SettingsProvider.delete(SettingsProvider.java:678)
[W3C] at android.content.ContentProvider$Transport.delete(ContentProvider.java:404)
[W3C] at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:406)
[W3C] at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:289)
[W3C] at android.os.ShellCommand.exec(ShellCommand.java:103)
[W3C] at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:51)
[W3C] at android.os.Binder.shellCommand(Binder.java:634)
[W3C] at android.os.Binder.onTransact(Binder.java:532)
[W3C] at android.os.Binder.execTransact(Binder.java:731)’; Code: ‘255’
[W3C] Error: Command ‘F:\Sdk\platform-tools\adb.exe -P 5037 -s 6D7D4SSCSCQGV8V8 shell settings delete global hidden_api_policy_pre_p_apps’ exited with code 255
[W3C] at ChildProcess.proc.on.code (C:\Users\junai\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\teen_process\lib\exec.js:113:19)
[W3C] at ChildProcess.emit (events.js:182:13)
[W3C] at maybeClose (internal/child_process.js:961:16)
[W3C] at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
[HTTP] <-- POST /wd/hub/session 500 1456 ms - 3644
[HTTP]

**Comment by mykola-mokhnach** [comment]
This device model is probably not good for automated testing. See https://github.com/appium/appium-desktop/issues/1265
