### ISSUE TITLE
[Question] is it possible to use Appium on Ubuntu 18.04 to simulate iOS?

### ISSUE THREAD

**Issue by gil-opplane** [appium/appium#14103]
Hi all,

I'm trying to integrate iOS testing on a node.js environment where I'm already using Appium to test Android applications.

Following [this](https://github.com/appium/appium-xcuitest-driver) repo, it seems to be possible to use iOS simulators with Ubuntu. I'm checking for some kind of validation regarding this, as a lot of other pages seem to indicate this isn't possible ([for](https://stackoverflow.com/questions/2406151/can-you-run-xcode-in-linux) [example](https://stackoverflow.com/questions/33529495/is-it-possible-to-run-appium-ios-automated-tests-on-ubuntu)). I have this doubt mainly because, on the repo I've linked (and that links to Appium's issue tracker), its `package.json` file points to a `appium-xcode` dependency (along with multiple iOS libraries). The only related issue I've found was [this one](https://github.com/appium/appium/issues/11092) but the `appium-xcuitest-driver` repo seems to contradict this.

Furthermore, it seems that documentation regarding this type of testing is kinda thin. If anyone could give me some pointers as to integrate this on the environment I've stated, that would be helpful.

Of course, if I'm absolutely wrong regarding all of this, I'd much appreciate a walkthrough on how this actually works.

Thanks

**Comment by imurchie** [comment]
No, it is not possible. Simulators will not run on Ubuntu, so there is no way for Appium to automate them there.

What in https://github.com/appium/appium-xcuitest-driver makes it seem possible? This needs to be changed to stop giving that impression.

**Comment by gil-opplane** [comment]
@imurchie 

Thanks for the quick response.

What gave that impression was the fact that a dependency called `appium-xcode` exists there. I started making questions on whether it would actually be possible to create simulators through XCode on Appium.

Thanks

**Comment by imurchie** [comment]
You _can_ create simulators through Appium, but only as a front-end to Xcode. `appium-xcode` is just a bunch of utilities for dealing with Xcode, which are extracted out because they are needed in a number of places.
