### ISSUE TITLE
iOS 13.3 Element "value" is not displayed. Value is displayed correctly on devices with iOS versions < 13

### ISSUE THREAD

**Issue by Devapal** [appium/appium#14105]
## The problem
Using Appium inspector when I spy on an element, I do not see the "value". The element has a value "**test**" but the value field in the inspector shows "**OBJ**".
 Up until iOS 13, I see the correct "value" but on devices with iOS 13 or greater, I see "**OBJ**" for "value" field. Please find the attached screenshots and page source.

Attached are 2 screenshots of the Appium inspector ( one with iOS 12.4.6 and one with 13.3.1)
**12.4.6** shows the "value" for the element I selected where as **13.3.1** return some junk value ***OBJ***

![12 4 6](https://user-images.githubusercontent.com/35826618/77592089-64f7ed00-6ebf-11ea-9e02-9cc43742dc0e.png)
![13 3 1](https://user-images.githubusercontent.com/35826618/77592090-65908380-6ebf-11ea-99df-2526a66b0ecc.png)
[PageSource.txt](https://github.com/appium/appium/files/4383994/PageSource.txt)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17
* Last iOS version that did not exhibit the issue (if applicable): 12.4.6
* Desktop OS/version used to run Appium: Mac OS Catalina 10.15.4
* Node.js version (unless using Appium.app|exe): 13.6.0
* Npm or Yarn package manager: 6.13.7
* Mobile platform/version under test: iOS Phone
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: exe

## Link to Appium logs
Attached Page Source on 13.3.1

**Comment by Devapal** [comment]
If you need to reproduce, the app is available on App Store by the name "Arclight"

**Comment by KazuCocoa** [comment]
Can you get the page source with command? I think the source by XCTest has the value.
Appium does not modify anything the returned value by XCTest.

I forgot which issue, but we got the same question in this repository before.
iOS 13 has different source structure than iOS 12-.

**Comment by mykola-mokhnach** [comment]
This is expected. Since iOS 13 Apple did some security adjustments for the accessibility manager, so now the content of secure fields in hidden from reading.

Please report this to Apple if you thing it is a bug.

**Comment by KS261187** [comment]
> Can you get the page source with command? I think the source by XCTest has the value.
> Appium does not modify anything the returned value by XCTest.
> 
> I forgot which issue, but we got the same question in this repository before.
> iOS 13 has different source structure than iOS 12-.

Can you please let me know the command to get the page source from XCTest?. Do you mean Appium.GetPageSource()?

**Comment by Devapal** [comment]
@KazuCocoa The attached page source is from Appium.GetPageSource() command. Please let me know if there is  a different command.

**Comment by KazuCocoa** [comment]
Sorry, i missed the attached one. @Devapal 
The source has a below line. Definitely the `value` has a blank? item. It is XCTest framework side thing since Appium does not modify the result.

```
<XCUIElementTypeSecureTextField type="XCUIElementTypeSecureTextField" value=" " enabled="true" visible="true" x="16" y="234" width="343" height="53"/>
```

@KS261187 
`Appium.GetPageSource()` is.
