### ISSUE TITLE
WinAppDriver Implicit Wait Timeout is not waiting for element

### ISSUE THREAD

**Issue by ForsakenService** [appium/appium#14106]
## The problem

Using WinAppDriver, and try running Implicit Wait Timeout in C# doesn't work, the program does not wait for the element to show up. The code I used is: 

this.driver.Manage().Timeouts().ImplicitWait=TimeSpan.FromSeconds(30); 
this.driver.FindElementByXPath("/Window/Window/Button[1]").Click();

The program ends in 6 seconds instead of at least running for more then 30 seconds for the element to show up.

## Environment

Windows 10
WinAppDriver
C# code

**Comment by mykola-mokhnach** [comment]
Please try appium@beta

**Comment by mykola-mokhnach** [comment]
If the feature does not there then please report it to https://github.com/microsoft/WinAppDriver, since the documentation there does declare the support of implicit waits.
