### ISSUE TITLE
Matched W3C error code 'no such element' to NoSuchElementError: Original error: 404 

### ISSUE THREAD

**Issue by p0well493** [appium/appium#14101]
## The problem
I have coded my Appium Webview for our Hybrid app on my mobile device using Eclipse Java as shown below and received no such element error.

driver.findElement(By.xpath("//android.view.View[@text=‘R navigation icon Regular Current Account Your payment and trading activities are made easy’ and @index=‘11’]")).click();

## Environment

Appium version : v.1.16.0
Desktop OS/version used to run Appium: Windows 10 Pro 64-bit(10.0, Build 17763)
Node.js version : v10.16.3
Npm : 6.9.0
Mobile platform/version under test: Android/v6.0
Real device or emulator/simulator: Huawei
Appium CLI or Appium : Appium desktop

## Details
Error Encountered:
Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: 404 - {"value":{"error":"no such element","message":"no such element: Unable to locate element.
Matched W3C error code 'no such element' to NoSuchElementError

Set<String> contexts = driver.getContextHandles();
				
		for(String contextName: contexts)
		{
			
			System.out.println(contextName);
			System.out.println(driver.getPageSource());
		}
				
		driver.context("WEBVIEW_com.cimb.ekyc");
		Thread.sleep(6000);		
		driver.executeScript("window.scrollTo(0,1200);");
		Thread.sleep(15000);
		driver.findElement(By.xpath("//android.view.View[@textContains='R navigation icon Regular Current Account Your payment and trading activities are made easy']")).click();

Thread.sleep(5000);
		driver.quit();
    }

}

## Link to Appium logs
[appium-server-logs March 25.txt](https://github.com/appium/appium/files/4378897/appium-server-logs.March.25.txt)

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]
		driver.findElement(By.className("android.widget.Button")).click();		
		
		Thread.sleep(5000);			
		Set<String> contexts = driver.getContextHandles();
			
		for(String contextName: contexts)
		{
			
			System.out.println(contextName);
			System.out.println(driver.getPageSource());
		}
					
		driver.context("WEBVIEW_com.cimb.ekyc");
		Thread.sleep(6000);	
		driver.executeScript("window.scrollTo(0,1200);");
		Thread.sleep(15000);
		driver.findElement(By.xpath("//android.view.View[@textContains='R navigation icon Regular Current Account Your payment and trading activities are made easy' and @index='11']")).click();
	
		
		Thread.sleep(5000);
		driver.quit();

**Comment by mykola-mokhnach** [comment]
> 	driver.findElement(By.xpath("//android.view.View[@textContains='R navigation icon Regular Current Account Your payment and trading activities are made easy' and @index='11']")).click();

The xpath query does not look correct. It only supports double quotes. Also, have you checked the page source whether it contains the target element?

**Comment by p0well493** [comment]
Hi @mykola-mokhnach ,

I have changed now the page source to follow after the code below:
driver.context("WEBVIEW_com.cimb.ekyc");
and element is showing on the html/xml now. 

But I am not familiar with Selenium, how will I able to click on it using Appium Webview ??
![webview march25](https://user-images.githubusercontent.com/61822569/77517333-eac36a80-6eb6-11ea-864a-285df1f77a80.JPG)

**Comment by mykola-mokhnach** [comment]
> But I am not familiar with Selenium, how will I able to click on it using Appium Webview ?? I want to select the "Regular Current Account"

Then this is probably a wrong place to ask. Kindly use Appium forum for howto questions
