### ISSUE TITLE
Android emulator not able to boot through appium

### ISSUE THREAD

**Issue by wulfihm** [appium/appium#14109]
## The problem

I am trying to launch an android emulator through Appium using AVD.
The emulator starts but gets stuck on the Google logo screen. Logs several openGL errors.

I found a similar issue here in the appium-desktop repo: https://github.com/appium/appium-desktop/issues/1043
However it was closed due to it not being a appium-desktop problem.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0
* Desktop OS/version used to run Appium: Windows10
* Mobile platform/version under test: Android 8.1
* Real device or emulator/simulator: Android emulator version 29.3.4.0 (build_id 6110076)
* Appium CLI or Appium.app|exe: Appium Desktop

## Details
Running the avd manually through the command line works fine:

```
PS C:\Users\myrocast> C:\Users\myrocast\AppData\Local\Android\Sdk\emulator\emulator.exe -avd emuA
Failed to open /qemu.conf, err: 2
HAX is working and emulator runs in fast virt mode.
dsound: Could not initialize DirectSound
dsound: Reason: No sound driver is available for use, or the given GUID is not a valid DirectSound device ID
audio: Could not init `dsound' audio driver
emulator: INFO: boot completed
emulator: INFO: boot time 23712 ms
emulator: Increasing screen off timeout, logcat buffer size to 2M.
emulator: Revoking microphone permissions for Google App.
emulator: Saving state on exit with session uptime 54521 ms
PS C:\Users\myrocast>
```
Afterwards my ui tests are also performed successfully.

## Link to Appium logs
https://gist.github.com/wulfihm/13cd59ed9cd2dbca57829eae1b125201

## Code To Reproduce Issue [ Good To Have ]

Simply using the "avd" capability set to the emulator I want to start.
https://gist.github.com/wulfihm/217aa4232241e3bda11cccefdaf1ecba

**Comment by mykola-mokhnach** [comment]
https://stackoverflow.com/questions/48061593/emulator-glclear466-gl-err-0x502

**Comment by mykola-mokhnach** [comment]
Appium has nothing to do with how Emulator starts. It simply executes the predefined command  and then the startup depends on the actual environment settings. There is also a possibility to provide custom emulator args in capabilities.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
