### ISSUE TITLE
Failed to unhide archs in executable file:///private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp

### ISSUE THREAD

**Issue by yanchunhuo** [appium/appium#14100]
## The problem

I can't use appium desktop to install ". IPA" package to the real device by setting the app of capability, but I can install it normally by using ideviceinstaller - I ". IPA". When I use ideviceinstaller - I ". IPA" to install, I can use bundleid to start the app

## Environment

* Appium version (or git revision) that exhibits the issue: appium1.15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 10.15.3
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: iOS12.4
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: appium-desktop

## Details
I can't use appium desktop to install ". IPA" package to the real device by setting the app of capability, but I can install it normally by using ideviceinstaller - I ". IPA". When I use ideviceinstaller - I ". IPA" to install, I can use bundleid to start the app

## Link to Appium logs
[error] [XCUITest] Error: Unexpected data: {"Error":"APIInternalError","ErrorDescription":"Failed to unhide archs in executable file:///private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.T1ia91/extracted/aaa.app/%E6%8E%8C%E9%80%9A%E5%AE%B6%E5%9B%AD%E5%9B%AD%E4%B8%81"}
[error] [XCUITest]     at InstallationProxyService._isFinished (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-ios-device/lib/installation-proxy/index.js:132:13)
[error] [XCUITest]     at InstallationProxyService._isFinished [as _waitMessageCompletion] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-ios-device/lib/installation-proxy/index.js:124:16)
[error] [XCUITest] Error: Could not install app: 'Unexpected data: {"Error":"APIInternalError","ErrorDescription":"Failed to unhide archs in executable file:///private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.T1ia91/extracted/aaa.app/%E6%8E%8C%E9%80%9A%E5%AE%B6%E5%9B%AD%E5%9B%AD%E4%B8%81"}'
[error] [XCUITest]     at IOSDeploy.install (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/ios-deploy.js:41:13)

**Comment by mykola-mokhnach** [comment]
It looks like the application bundle has some resources inside it that are named weirdly. Make sure the file names inside the app bundle only contain ASCII characters.

**Comment by yanchunhuo** [comment]
> 
> 
> It looks like the application bundle has some resources inside it that are named weirdly. Make sure the file names inside the app bundle only contain ASCII characters.

@mykola-mokhnach Is it because of these filenames
![1](https://user-images.githubusercontent.com/14889037/77445638-498dd300-6e28-11ea-95f9-57c6a4de667d.png)

**Comment by yanchunhuo** [comment]
> 
> 
> It looks like the application bundle has some resources inside it that are named weirdly. Make sure the file names inside the app bundle only contain ASCII characters.

@mykola-mokhnach Is it because of these filenames
![filenames](https://user-images.githubusercontent.com/14889037/77445745-6f1adc80-6e28-11ea-83de-339955ae6433.png)

**Comment by mykola-mokhnach** [comment]
I assume these file names must be fixed in order to make it working with appium. In general, zip archives are not very happy about unicode chars in file names.

**Comment by yanchunhuo** [comment]
> 
> 
> I assume these file names must be fixed in order to make it working with appium. In general, zip archives are not very happy about unicode chars in file names.
@mykola-mokhnach These file names are in Chinese. Can appium support them? But the same ". IPA" package, why can I use ideviceinstaller to install.
![filenames](https://user-images.githubusercontent.com/14889037/77489510-394f1580-6e73-11ea-8a2c-52fbf74267a7.jpg)

**Comment by mykola-mokhnach** [comment]
> @mykola-mokhnach These file names are in Chinese. Can appium support them? But the same ". IPA" package, why can I use ideviceinstaller to install.

Because this might take too much effort to make it working. I have proposed an easy and fast workaround though. Feel free to commit a PR to Appium if you have any good ideas.

**Comment by yanchunhuo** [comment]
> 
> 
> > @mykola-mokhnach These file names are in Chinese. Can appium support them? But the same ". IPA" package, why can I use ideviceinstaller to install.
> 
> Because this might take too much effort to make it working. I have proposed an easy and fast workaround though. Feel free to commit a PR to Appium if you have any good ideas.

@mykola-mokhnach I have modified the file names of Chinese characters. All file names are ASCII characters, but they cannot be installed。

## Link to Appium logs

Error: Unexpected data: {"Error":"APIInternalError","ErrorDescription":"Failed to unhide archs in executable file:///private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.l0isN7/extracted/ztjyyd.app/%E6%8E%8C%E9%80%9A%E5%AE%B6%E5%9B%AD%E5%9B%AD%E4%B8%81"

**Comment by KazuCocoa** [comment]
Copied app already had wrong file name. The `µùÑµ£¼Φ¬₧.png` should be `日本語.png`.

```
$ ls /var/folders/y6/524wp8fx0xj5q1rf6fktjrb00000gn/T/202064-53753-11msanj.01vrk/Payload/kazu-sample.app/
Assets.car               Info.plist               _CodeSignature           kazu-sample
Base.lproj               PkgInfo                  embedded.mobileprovision µùÑµ£¼Φ¬₧.png
```

**Comment by mykola-mokhnach** [comment]
This is most likely related to https://github.com/maxogden/extract-zip/issues/74

Long things short - `Zip files officially support charset encodings other than CP437 and UTF-8, but the zip file spec does not specify how it works. This library makes no attempt to interpret the Language Encoding Flag.`

**Comment by KazuCocoa** [comment]
Yeah, I read the same place.
As another workaround, users can do:

1) Rename `test.ipa` to `test.zip`
2) Unzip it to `Payload/test.app`
3) Set `test.app` as app capability

**Comment by mykola-mokhnach** [comment]
@KazuCocoa  I would say this is an issue of MacOS ZIP library itself. See https://stackoverflow.com/questions/13261347/correctly-decoding-zip-entry-file-names-cp437-utf-8-or

In theory zip libraries that use UTF-8 to encode file names must trigger the General Purpose Unicode flag for such archive. yauzl properly handles files and [defaults](https://github.com/thejoshwolfe/yauzl/issues/42) to CP437 if the flag is not set. A possible solution could be to repack the archive manually and set the necessary flag.

Another solution would be to guess file names encoding upon file extraction as it is stated in https://github.com/thejoshwolfe/yauzl/issues/42#issuecomment-252801137. This could potentially bring new issues, since file names parsing will be completely on [our](https://github.com/thejoshwolfe/yauzl/commit/cc7455ac789ba84973184e5ebde0581cdc4c3b39#diff-04c6e90faac2675aa89e2176d2eec7d8R95) side (currently the https://github.com/maxogden/extract-zip wrapper over yauzl is used to for zip extraction)

**Comment by KazuCocoa** [comment]
thanks.
I toyed `entry.fileName` a bit, but I finally thought giving troubleshooting was the most reasonable

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-base-driver/pull/418 may fix this without the workaround...

**Comment by KazuCocoa** [comment]
unzipper did not work, but the below could be the next item.

https://github.com/appium/appium-support/blob/master/lib/zip.js#L25-L27

`decodeStrings` is true by default. So, potentially we can handle the file name encode in our side with setting it `false` and trap it with `entry.fileName` (and make it configurable via capabilities)

**Comment by mykola-mokhnach** [comment]
The patch has been published to appium@beta
