### ISSUE TITLE
Unable to find webview context after execution launchApp() command on iOS

### ISSUE THREAD

**Issue by sasha943** [appium/appium#14108]
## The problem

After run two tests on one Simulator I have problem with finding Webview context. Between tests I execute launchApp() command. 

## Environment

* appium --version: 1.17.0-beta.1
* MacOS version: 10.14.6 (18G95)
* Xcode version: 10.3
* npm --version: 6.13.7
* node --version: v13.10.1
* Mobile platform: iOS 12.4 Model: iPad Pro (12.9-inch)
* Real device or emulator/simulator: Simulator
## Details

If I create new simulator for each test everything works good. But it much more slowly.
**Also Webview available in Safary Dev mode.**

## Link to Appium logs
[Link to appium logs](https://gist.github.com/sasha943/314c9732af8840f5aa45defbfb4c1dbf)
[Xcodelogs](https://gist.github.com/sasha943/6ca335679414da3027851c82deed541b)

Please advice

**Comment by mykola-mokhnach** [comment]
It might be that you need to [wait](https://github.com/appium/appium/issues/11946#issuecomment-603456907) for a while until web view is visible to the remote debugger

**Comment by sasha943** [comment]
@mykola-mokhnach  Thanks for answer. I already have wait for webview. Also added to caps
        `capabilities.setCapability( "webviewConnectTimeout", 10000 );` 
and no changes

**Comment by sasha943** [comment]
hmm, very strange, but after set cap 'fullReset' to 'false' I can find webview and everything works

**Comment by mykola-mokhnach** [comment]
I wouldn't recommend using lauchApp/closeApp apis at all. They are hacky and implicit and must die

**Comment by sasha943** [comment]
I think this issue can be closed. @mykola-mokhnach  thanks for advice
