### ISSUE TITLE
mobile: sensorSet doesn't work with Appium 1.16.0

### ISSUE THREAD

**Issue by pako88** [appium/appium#14116]
## The problem
I tried to use the newly introduced feature (in Appium 1.16.0) `mobile: sensorSet` but unfortunately it didn't work:  
```
2020-03-26T16:46:25.122Z INFO webdriver: COMMAND executeScript("mobile: sensorSet", <object>)
2020-03-26T16:46:25.122Z INFO webdriver: [POST] https://ondemand.eu-central-1.saucelabs.com:443/wd/hub/session/d7c8256b74ab41c6a122e2f0464ef033/execute/sync
2020-03-26T16:46:25.122Z INFO webdriver: DATA {
  script: 'mobile: sensorSet',
  args: [ { sensorType: 'acceleration', value: '0:9.77631:0.812349' } ]
}
2020-03-26T16:46:25.236Z DEBUG webdriver: request failed due to status 9
2020-03-26T16:46:25.237Z WARN webdriver: Request failed due to Unknown mobile command "sensorSet". Only shell,scrollBackTo,viewportScreenshot,deepLink,startLogsBroadcast,stopLogsBroadcast,acceptAlert,dismissAlert,batteryInfo,deviceInfo,changePermissions,getPermissions,performEditorAction commands are supported.
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0
* Last Appium version that did not exhibit the issue (if applicable): - 
* Desktop OS/version used to run Appium: -
* Node.js version (unless using Appium.app|exe): -
* Npm or Yarn package manager: -
* Mobile platform/version under test: Capabilities on Sauce Labs `{ "desiredCapabilities": { "deviceName": "Android GoogleAPI Emulator", "enablePerformanceLogging": true, "platformVersion": "10.0", "platformName": "Android", } }`
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: -

## Details

-

## Link to Appium logs

-

## Code To Reproduce Issue [ Good To Have ]

in wdio:  
`browser.execute('mobile: sensorSet', { sensorType: 'acceleration', value: '0:9.77631:0.812349' });`

**Comment by pako88** [comment]
Investigation from Wim Selles (somehow can't link him here):
This is a bug in Appium (will also fail locally). This endpoint currently only works in the UIAutomator(1)-driver of Android (http://appium.io/docs/en/drivers/android-uiautomator/), this is the deprecated one. It looks like it was never published to the other drivers. So what you can do is add `automationName: "UIAutomator"` to the capabilities and see if it works. Keep in mind that it is the deprecated driver and:

- might not work with the latest versions of Android
- is much slower

The Appium team will pick this up but I can't tell you when this will be fixed by the Appium team and secondly will be deployed to Sauce. To keep track of it you might want to submit a bug on the Appium GitHub and provide the same logs as you already did here.

**Comment by mykola-mokhnach** [comment]
cc @vrunoa

**Comment by mykola-mokhnach** [comment]
The patches have been published to appium@beta
