### ISSUE TITLE
Getting error ECONNREFUSED while running in CirclCI.

### ISSUE THREAD

**Issue by vishalpaliwal1** [appium/appium#14118]
## The problem

[WD Proxy] Got response with unknown status: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}

## Environment

* Appium version (or git revision) that exhibits the issue: v1.17.0
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: MacOS circleci
* Node.js version (unless using Appium.app|exe):  v0.35.0
* Npm or Yarn package manager: 10.16.3
* Mobile platform/version under test: iOS iPhone 11 OS:13.0
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/vishalpaliwal1/29688df16825b26d5d32a97ab99687ea

## Code To Reproduce Issue [ Good To Have ]
```
[Appium] Appium v1.17.0 creating new XCUITestDriver (v3.17.0) session
 W3C capabilities and MJSONWP desired capabilities were provided
Creating session with W3C capabilities: {
"alwaysMatch": {
"appium:deviceName": "iPhone 11",
   "appium:automationName": "XCUITest",
"appium:autoWebview": false,
"appium:newCommandTimeout": 3600,
  "appium:platformVersion": "13.0",
   "appium:fullReset": false,
    "appium:noReset": true,
    "appium:isHeadless": true,
  "appium:locationServicesEnabled": true,
 "appium:locationServicesAuthorized": true,
 "appium:calendarAccessAuthorized": true,
   "appium:app": "/tmp/workspace/artifacts/kaddra.app",
"platformName": "iOS"
},
"firstMatch": [
    {}
   ]
}
```

**Comment by mykola-mokhnach** [comment]
I can observe the client is sending multiple session creation request, which intercept each other, so the resulting error is expected. Nothing we can do on the server side though.

**Comment by vishalpaliwal1** [comment]
Hi, Thanks for responding, 
I am running same setup in MAC...Its handling properly...I am starting Appium server..and then running codecept with headless appium as dependency...
But when I try to run it on circleci ..its giving error...

Is there any other way i can handle it properly? Does it require appium to start? or codecept can start it automatically ?

**Comment by mykola-mokhnach** [comment]
I assume the CI node is just too slow, so it does not respond for too long, which makes the client think the request has timed out and must be retried. The request timeout value for java client, for example, is 10 minutes

**Comment by vishalpaliwal1** [comment]
its `MacOS Medium 4 CPU / 8 GB RAM` ..I dont think this is the issue... I saw attempting connections many time before also..
I was starting appium before starting codecept ...may be i skip this step...
```#- run:
      #    name: Start Appium server
      #    working_directory: ~/cem-qa/cem-qa-mobile
      #    command: npx appium
      #    background: true```

**Comment by mykola-mokhnach** [comment]
> its MacOS Medium 4 CPU / 8 GB RAM ..I dont think this is the issue... I saw attempting connections many time before also..

I would try to enable log timestamps first to make sure.

**Comment by vishalpaliwal1** [comment]
Its working on Macbook.... please see the attached logs... But same steps are not working in CI...

https://gist.github.com/vishalpaliwal1/562a4f15121fba8f5f7f9cce1ea68603

**Comment by mykola-mokhnach** [comment]
Unfortunately it's not the log I'd like to see. I need the one from CI with timestamps enabled

**Comment by vishalpaliwal1** [comment]
Hi @mykola-mokhnach ,

I have generated logs with timestamps...please have a look....

https://gist.github.com/vishalpaliwal1/990802e2f29fec6bedd171664e764207

**Comment by mykola-mokhnach** [comment]
It's clearly visible from the log that the client terminates session creation connection after exactly 90 seconds even though the response has not been received. Please make sure you use the most recent client version and the HTTP timeouts are configured properly there.

Unfortunately, there is nothing more we could here from the server side. 
Closed as not an issue.

**Comment by vishalpaliwal1** [comment]
@mykola-mokhnach 

Getting same error with appium-desktop... please have a look...

https://gist.github.com/vishalpaliwal1/14e30c3e39661e04d807fc5b1615fc23
