### ISSUE TITLE
WebDriverAgent problem

### ISSUE THREAD

**Issue by walkeraki** [appium/appium#14125]
## The problem

On random devices at random times there is webDriverAgent error. We cannot figure out pattern when it happens but so far only thing that stands out is ios 13 version.

```
[35m[Xcode][39m Testing failed:
[35m[Xcode][39m 	unable to attach DB: error: accessing build database "/Users/Shared/Jenkins/Library/Developer/Xcode/DerivedData/WebDriverAgent-flutjgoporxrkvcfvzeptjtwmylo/Build/Intermediates.noindex/XCBuildData/build.db": database is locked Possibly there are two concurrent builds running in the same filesystem location.
[35m[Xcode][39m 	WebDriverAgentRunner:
[35m[Xcode][39m 		WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: Failed to write updated test configuration to /Users/Shared/Jenkins/Library/Developer/Xcode/DerivedData/WebDriverAgent-flutjgoporxrkvcfvzeptjtwmylo/Logs/Test/Test-WebDriverAgentRunner-2020.03.26_13-20-54-+0100.xcresult/Staging/2_Test/Diagnostics/WebDriverAgentRunner-2A67C4AC-32EA-455D-A5FE-0A08FDFB407B/WebDriverAgentRunner-501F8E85-FAA0-4DD5-A866-946CE1BB71EC/LaunchSessions/65E2EB4B-87A0-4293-A5D9-764B5C460D78/remote-container/tmp/WebDriverAgentRunner-65E2EB4B-87A0-4293-A5D9-764B5C460D78.xctestconfiguration. (Underlying error: The file “WebDriverAgentRunner-65E2EB4B-87A0-4293-A5D9-764B5C460D78.xctestconfiguration” doesn’t exist. The file doesn’t exist. (Underlying error: The operation couldn’t be completed. No such file or directory))))
[35m[Xcode][39m 
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15
* Desktop OS/version used to run Appium: Mac os
* Mobile platform/version under test: ios
* Real device or emulator/simulator: real device

## Link to Appium logs

I am linking log from same device when it works and when it doesnt
https://gist.github.com/walkeraki/534813f95f3b6b160e02d7504704a654  -- error
https://gist.github.com/walkeraki/0e7af875dc06106932255658a7f4e549 -- working

## Code To Reproduce Issue [ Good To Have ]

Capabilities we use
```
  addCapability("deviceName", "iOS Phone");
  addCapability("automationName", "XCUITest");
  addCapability("platformName", "iOS");
  addCapability("platformVersion", 9.3);
  addCapability("waitForQuiescence", false);
```

**Comment by KazuCocoa** [comment]
> [35m[Xcode][39m 	unable to attach DB: error: accessing build database "/Users/Shared/Jenkins/Library/Developer/Xcode/DerivedData/WebDriverAgent-flutjgoporxrkvcfvzeptjtwmylo/Build/Intermediates.noindex/XCBuildData/build.db": database is locked Possibly there are two concurrent builds running in the same filesystem location.

Did the environment have parallel `xcodebuild build` possibility?
Xcode seemed to get the concurrent build issue

**Comment by walkeraki** [comment]
We run tests on multiple devices at the same time so yes there is parallel xcode build.. 
Also this started to happen as of late, what would change? And what can be done to fix this?
thanks

**Comment by mykola-mokhnach** [comment]
Set unique `derivedDataPath` capability for each parallel session

**Comment by walkeraki** [comment]
Ok i found my path to derivedData but i see 4 different WebdriverAgent folders in there.. Each has some random long string by its name. Which one do i have to use? I guess it doesnt make any difference which one? Also is there a way to get that path to my java code? This random string in directory name will change i pressume?

**Comment by mykola-mokhnach** [comment]
Simply do what is written above. The only precondition is that each folder should already exist on the file system, should be empty and should be accessible for Appium.

**Comment by walkeraki** [comment]
DerivedDataPath should point to empty folder anywhere on os?

**Comment by KazuCocoa** [comment]
It depends on your requirement.
If you would like to re-use them (the behaviour depends on Xcode thou), you can specify the path every time. If you'd like to build from clean environment, you can specify the path to a new one.

**Comment by walkeraki** [comment]
Setting derivedDataPath to something like "/usr/something/"+deviceID made it work. Now every device uses its own folder and we no longer get that error.
Thanks
