### ISSUE TITLE
Did you interact with the correct element?

### ISSUE THREAD

**Issue by liuchengxu11** [appium/appium#14122]
Continue with the previous question
https://github.com/appium/appium/issues/14114#issue-589052947

If there is no problem with element positioning, this error will be reported！ 
Positioning is as follows
![image](https://user-images.githubusercontent.com/33363646/77903984-59893500-72b6-11ea-92e8-f028f91ed0cb.png)

[111.txt](https://github.com/appium/appium/files/4402215/111.txt)

**Comment by mykola-mokhnach** [comment]
> 2020-03-30 10:46:57:239 [WD Proxy] Proxying [POST /element] to [POST http://localhost:8200/wd/hub/session/1ba9282b-39ba-467b-bf5c-7127075a5c2e/element] with body: {"strategy":"xpath","selector":"/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.widget.ImageView","context":"","multiple":false}
> 2020-03-30 10:46:57:383 [WD Proxy] Got response with status 200: {"sessionId":"1ba9282b-39ba-467b-bf5c-7127075a5c2e","value":{"ELEMENT":"1b3bd41c-d22c-4a77-8f53-7e820ca9aaa9","element-6066-11e4-a52e-4f735466cecf":"1b3bd41c-d22c-4a77-8f53-7e820ca9aaa9"}}
> 2020-03-30 10:46:57:383 [MJSONWP (17cd5be2)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"1b3bd41c-d22c-4a77-8f53-7e820ca9aaa9","ELEMENT":"1b3bd41c-d22c-4a77-8f53-7e820ca9aaa9"}
> 2020-03-30 10:46:57:384 [HTTP] <-- POST /wd/hub/session/17cd5be2-a7b0-4c86-ad56-7c565a2b8aed/element 200 148 ms - 199
> 2020-03-30 10:46:57:384 [HTTP] 
> 2020-03-30 10:46:57:385 [HTTP] --> POST /wd/hub/session/17cd5be2-a7b0-4c86-ad56-7c565a2b8aed/element/1b3bd41c-d22c-4a77-8f53-7e820ca9aaa9/value
> 2020-03-30 10:46:57:386 [HTTP] {"text":"刘程旭好帅","value":["刘","程","旭","好","帅"],"id":"1b3bd41c-d22c-4a77-8f53-7e820ca9aaa9","sessionId":"17cd5be2-a7b0-4c86-ad56-7c565a2b8aed"}

I don't see any issues there. You are trying to edit text into an image view and that fails, which is expected.

**Comment by liuchengxu11** [comment]
I suspect it's about   uiautomatorviewer2    Element is OK

**Comment by mykola-mokhnach** [comment]
> I suspect it's about uiautomatorviewer2 Element is OK

Sorry, I don't understand this comment

**Comment by mykola-mokhnach** [comment]
Closed because of no response
