### ISSUE TITLE
Appium launches the app and then restarts over and over in iOS Simulator

### ISSUE THREAD

**Issue by endlessred** [appium/appium#14127]
## The problem

I have been running automation tests for a while, but across multiple computers I'm having an issue where appium runs through the session setup process and gets all the way to launching the app, but then closes the app and starts all over again until it times out and fails. Any help would be appreciated, thanks!

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Desktop OS/version used to run Appium: macOS Catalina 10.15.4
* Node.js version (unless using Appium.app|exe): 8.11.1 (used for compatibility with webdriverio v4)
* Npm or Yarn package manager: Npm
* Mobile platform/version under test: iOS 12.1
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: both

## Link to Appium logs

https://gist.github.com/endlessred/78cafffd34db5fde766828e827ca252d

**Comment by mykola-mokhnach** [comment]
Please use the most recent server version

**Comment by mykola-mokhnach** [comment]
if it is critical for you to keep the older server version then change the local `etc/hosts`, so the localhost is pointing to `127.0.0.1` (ipv4) instead of `::1` (ipv6)

**Comment by mykola-mokhnach** [comment]
Also I can observe a mess in the log related to parallel sessions init. Please follow https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/parallel-tests.md to setup parallel sessions properly.

**Comment by endlessred** [comment]
Thanks for following up! I tried updating appium to latest, but I'm getting a brand new error now where it can't find iOS as a platform and XCUITest as an automationname:

https://gist.github.com/endlessred/27d879aed8f2961446e8ea3d1c95a2e6

**Comment by mykola-mokhnach** [comment]
> [debug] [MJSONWP] Encountered internal error running command: Error: Could not load a driver for automationName 'XCUITest' and platformName 'iOS'. Please verify your Appium installation


The hint is in the message - the package deployment is broken or corrupted

**Comment by mykola-mokhnach** [comment]
Closed because of no response
