### ISSUE TITLE
UIBarButtonItem not found by inspector in page source

### ISSUE THREAD

**Issue by YukiSou** [appium/appium#14128]
## The problem

UIBarButtonItem not found by inspector

## Environment

* Appium version: 1.17.0
* Desktop OS/version used to run Appium: MacOS 10.15.3
* Node.js version (unless using Appium.app|exe): v13.11.0
* Npm or Yarn package manager: 6.13.7
* Mobile platform/version under test: iOS 13.3.1
* Real device or emulator/simulator: iPhone7 real device
* Appium CLI or Appium.app|exe: cli as server and  Appium.app for insepect

## Details

other three buttons(back, share, more) can't be found in page source
![image](https://user-images.githubusercontent.com/4012069/77983224-fdb7be00-7340-11ea-825d-895d86f3d161.png)

## Code To Reproduce Issue [ Good To Have ]

![image](https://user-images.githubusercontent.com/4012069/77983564-edeca980-7341-11ea-85f9-e8b6ed213d86.png)

**Comment by mykola-mokhnach** [comment]
Is the control resolved properly in the Xcode Accessibility inspector? Possible duplicate of https://github.com/appium/appium/issues/6517

**Comment by YukiSou** [comment]
Hi mykola mokhnach

Thanks for the redirection, I've found mistakes in the implementation of my container and ready to fix them. It's very helpful!

Regards
