### ISSUE TITLE
Action `pointerMove` payload is not consistent with spec.

### ISSUE THREAD

**Issue by yashLadha** [appium/appium#14130]
## The problem

When using selenium client binding to execute a `pointerMove` action on a real IOS device. It gives a validation error of invalid origin type. 

## Environment

* Appium version (or git revision) that exhibits the issue: `1.16.0`
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: `iPhone X, os_version: 11`
* Real device or emulator/simulator: `Real Device`
* Appium CLI or Appium.app|exe: `CLI`

## Details

So the payload that is being sent from the selenium client binding is marking the value of the webElement object to some elementID, but as mentioned in the API docs for appium, we can see that following are the only supported values:

```
For 'pointerMove', this tells the input source what x,y are relative to. Can be 'viewport', 'pointer' or {'element-6066-11e4-a52e-4f735466cecf': ''}
```

If it gets any value that is not among them, it gives an error. For example reference payload that gave error:

```json
[
  {
    "type": "pointer",
    "parameters": { "pointerType": "mouse" },
    "id": "mouse",
    "actions": [
      {
        "type": "pointerMove",
        "duration": 250,
        "x": 0,
        "y": 0,
        "origin": { "element-6066-11e4-a52e-4f735466cecf": "5000" }
      },
      { "type": "pointerDown", "duration": 0, "button": 0 },
      {
        "type": "pointerMove",
        "duration": 250,
        "x": -128,
        "y": -2,
        "origin": { "element-6066-11e4-a52e-4f735466cecf": "5000" }
      },
      { "type": "pointerUp", "duration": 0, "button": 0 }
    ]
  },
  {
    "type": "key",
    "id": "key",
    "actions": [
      { "type": "pause", "duration": 0 },
      { "type": "pause", "duration": 0 },
      { "type": "pause", "duration": 0 },
      { "type": "pause", "duration": 0 }
    ]
  }
]
```

## Link to Appium logs

https://gist.github.com/yashLadha/0707bd05aff5366ccd9aafe78acfda12

## Code To Reproduce Issue [ Good To Have ]

Used selenium python client bindings for the test-script.

```python
        print(f"Is W3C: {driver.w3c}")
        driver.get("https://google.com")
        search = driver.find_element_by_name("q")
        print(f"Location {search.location}")
        ActionChains(driver).move_to_element(search).click_and_hold().move_to_element_with_offset(search, 10, 10).release().perform()
        print('Doing some stuff')
```

Python dependencies:

```bash
selenium==3.141.0
urllib3==1.25.8
```

### Possible Workaround

1. The approach towards handling this payload is either to strip the value from the web-element object and then forwards the payload because of a hard check on the type of origin next commands like `buttond_down` and `button_up` cannot be executed.
0. Use a default fallback mechanism in other commands that depends on the pointerMove command for execution.

**Comment by mykola-mokhnach** [comment]
This is expected. Only `pointer` input type is supported. No mouse support on iOS. 
You could use the low-level constructor like it is described in https://appiumpro.com/editions/29 or create a PR to Selenium to be able to change the default input tool

**Comment by mykola-mokhnach** [comment]
it errors out because the given element id is the web element id and touch actions only work in native context (and with native element ids). There is nothing we could do about it.
Try to provide absolute coordinates as a workaround
