### ISSUE TITLE
iOS (iPad): Text Getting entered twice in text fields

### ISSUE THREAD

**Issue by udit-jaiswal** [appium/appium#14137]
I am automating a native app and when I'm entering field using `.sendKeys` and `.setValue`, value is getting entered twice. For e.g. when trying to enter `abcd`, the output is `abcdabcd`. 

## Environment

* Appium version: 1.15.1
* Desktop OS/version used to run Appium: macOS 10.14.6
* Mobile platform/version under test: iPad Air(13.3)
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium.exe

[GIST](https://gist.github.com/udit-jaiswal/7335a137a370cdef8b0952556eaf06a4)

## Code To Reproduce Issue

driver.findElementByAccessibilityId("someId").sendKeys("test");

**Comment by mykola-mokhnach** [comment]
> [info] [HTTP] [37m-->[39m [37mPOST[39m [37m/wd/hub/session/28c07099-5ec0-40c5-9e35-d4dc1ad13f65/element/5E000000-0000-0000-7E20-010000000000/value[39m
> [info] [HTTP] {"id":"5E000000-0000-0000-7E20-010000000000","text":"test","value":["t","e","s","t"]}
> [debug] [W3C (28c07099)] Calling AppiumDriver.setValue() with args: [["t","e","s","t"],"5E000000-0000-0000-7E20-010000000000","28c07099-5ec0-40c5-9e35-d4dc1ad13f65"]
> [debug] [XCUITest] Executing command 'setValue'
> [debug] [WD Proxy] Matched '/element/5E000000-0000-0000-7E20-010000000000/value' to command name 'setValue'
> [debug] [Protocol Converter] Added 'text' property "test" to 'setValue' request body
> [debug] [WD Proxy] Proxying [POST /element/5E000000-0000-0000-7E20-010000000000/value] to [POST http://localhost:8100/session/8D809894-DE07-4B6B-A9DD-E69167A4BB6A/element/5E000000-0000-0000-7E20-010000000000/value] with body: {"value":["t","e","s","t"],"text":"test"}[info] [HTTP] <-- POST /wd/hub/session/28c07099-5ec0-40c5-9e35-d4dc1ad13f65/element/5E000000-0000-0000-7E20-010000000000/value - - ms - -
> [info] [HTTP] 
> [info] [HTTP] [37m-->[39m [37mPOST[39m [37m/wd/hub/session/28c07099-5ec0-40c5-9e35-d4dc1ad13f65/element/5E000000-0000-0000-7E20-010000000000/value[39m
> [info] [HTTP] {"id":"5E000000-0000-0000-7E20-010000000000","text":"test","value":["t","e","s","t"]}
> [debug] [W3C (28c07099)] Calling AppiumDriver.setValue() with args: [["t","e","s","t"],"5E000000-0000-0000-7E20-010000000000","28c07099-5ec0-40c5-9e35-d4dc1ad13f65"]
> [debug] [XCUITest] Executing command 'setValue'[debug] [WD Proxy] Got response with status 200: {"value":null,"sessionId":"8D809894-DE07-4B6B-A9DD-E69167A4BB6A"}
> [debug] [WD Proxy] Matched '/element/5E000000-0000-0000-7E20-010000000000/value' to command name 'setValue'
> [debug] [Protocol Converter] Added 'text' property "test" to 'setValue' request body
> [debug] [WD Proxy] Proxying [POST /element/5E000000-0000-0000-7E20-010000000000/value] to [POST http://localhost:8100/session/8D809894-DE07-4B6B-A9DD-E69167A4BB6A/element/5E000000-0000-0000-7E20-010000000000/value] with body: {"value":["t","e","s","t"],"text":"test"}
> [debug] [W3C (28c07099)] Responding to client with driver.setValue() result: null[debug] [WD Proxy] Got response with status 200: {"value":null,"sessionId":"8D809894-DE07-4B6B-A9DD-E69167A4BB6A"}
> [debug] [W3C (28c07099)] Responding to client with driver.setValue() result: null
> [info] [HTTP] <-- POST /wd/hub/session/28c07099-5ec0-40c5-9e35-d4dc1ad13f65/element/5E000000-0000-0000-7E20-010000000000/value 200 7412 ms - 14
> [info] [HTTP]

The client retries the request because it does not get the response from the server, so such result is expected.

Please update Appium to the most recent version and try again

**Comment by udit-jaiswal** [comment]
@mykola-mokhnach I'm on the latest appium version as of today and I don't see any reason why it is not getting response from the server.

**Comment by mykola-mokhnach** [comment]
The latest stable one is current 1.17 and the recent one is appium@beta.

Version 1.15 is quite old and might not support web view features in iOS 13.3

**Comment by udit-jaiswal** [comment]
I'm automating a native_app not web view.

**Comment by mykola-mokhnach** [comment]
It still makes sense to upgrade the server. Many fixes have been done since then

**Comment by udit-jaiswal** [comment]
cool. will try and update here.

**Comment by udit-jaiswal** [comment]
@mykola-mokhnach working with 1.17.0. Closing this issue. Thanks for the help.
