### ISSUE TITLE
Unable to launch/load certain page in appium inspector(1.15.1)

### ISSUE THREAD

**Issue by Vaishnavi-s** [appium/appium#14138]
## The problem

while inspecting our application if i go to next page it does not load in the inspector. It keeps loading and come back to the previous page.

## Environment

* Appium version :1.15.1
* Mac OS/version used to run Appium:1 0.14.5
* Mobile platform/version under test: iOS (13.3)
* Real device or emulator/simulator: Both real device and Simulator
* Application: Nativescript 3.1

**Comment by mykola-mokhnach** [comment]
Please provide the full server log and describe the issue properly (aka steps, actual and expected results). Also you need to upgrade to the recent server version first.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
