### ISSUE TITLE
Throwing errors while installng the treminal 

### ISSUE THREAD

**Issue by harshavardhannaidudasari** [appium/appium#14131]
kindly give me a solution, step by step.

![Screen Shot 2020-03-31 at 6 53 36 PM](https://user-images.githubusercontent.com/52112234/78031328-0b8d3380-7381-11ea-9d64-83040193d195.png)

npm install -g appium
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules'] {
npm ERR!   stack: "Error: EACCES: permission denied, access '/usr/local/lib/node_modules'",
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/a1/.npm/_logs/2020-03-31T12_42_08_168Z-debug.log

**Comment by imurchie** [comment]
You can change the permissions on MacOS in various ways. This page is as good as any in discussing it: https://www.macinstruct.com/node/415

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
