### ISSUE TITLE
appium-doctor reporting 'android' and 'emulator' can't be found inside 'tools' directory

### ISSUE THREAD

**Issue by majdukovic** [appium/appium#14144]
## The problem

After installing latest Android Studio (3.6.2) on Mac Mojave and setting ANDROID_HOME I've ran "appium-doctor --android" to check if everything is fine, but I saw this:

"android could NOT be found at '/Users/username/Library/Android/sdk/tools/android'!
emulator could NOT be found at '/Users/username/Library/Android/sdk/tools/emulator'!"

Which is indeed true, when I go to '/Users/username/Library/Android/sdk/' I see there is no 'tools' directory. After some googling and searching, I've found out Android Studio decided to deprecate "SDK Tools" package: 
"Note: This SDK Tools package is deprecated and no longer receiving updates. Instead, please use the new command-line tools package." (https://developer.android.com/studio/releases/sdk-tools)

So, it is not installed by default when installing Android Studio and appium-doctor will give an error.

I think this should be corrected in "appium-doctor" as "SDK tools" package is obsolete now.

One way to solve it is to go to: "Android Studio" -> "Preferences" -> "Appearance & Behaviour" -> "System Settings" -> "Android SDK" -> "SDK Tools" -> Uncheck "Hide Obsolete Packages" -> "Android SDK Tools (obsolete)" package will appear, once downloaded and installed 'tools' directory will be available in 'sdk' directory and running "appium-doctor --android" will report this issue is fixed.

## Environment
Android Studio 3.6.2
Build #AI-192.7142.36.36.6308749, built on March 18, 2020
Runtime version: 1.8.0_212-release-1586-b4-5784211 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

MacBook Pro - macOS 10.14.6 (Mojave)

Appium Doctor v.1.15.0

**Comment by KazuCocoa** [comment]
Thanks.
appium-doctor should print an error message to the tools for newer version case.

https://github.com/appium/appium-doctor/blob/9c53017c89a69504677f7fd2b4026cb4fbf2e48c/lib/android.js#L32-L62

https://developer.android.com/studio#cmdline-tools

**Comment by majdukovic** [comment]
Great, thank you Kazuaki.

**Comment by josh-m-sharpe** [comment]
Seems like `android` is no longer included in the cmdline tools?I installed them through the sdk manager in android studio as well as checked the zip here: https://developer.android.com/studio#cmdline-tools - basically the same thing.  No `android` cmd.  Anyone know if that is no longer a thing?

**Comment by josh-m-sharpe** [comment]
Also, android-octor seems to think they should be in $SDK_PATH/tools, but Android studio is installing `emulator` to $SDK_PATH/cmdline-tools now.  Should that be updated as well?

**Comment by KazuCocoa** [comment]
Thanks. I've updated the path in `appium@beta` to search binaries.
https://github.com/appium/appium-adb/pull/529

About emulator.
I removed libraries from my local and got new versions. Then, `emulator` was still not in `cmdline-tools` (1.0 and 2.0-rc) as https://github.com/appium/appium-adb/pull/529, they were in `$SDK_PATH/emulator`.

Do you have any screenshot or evidence about it?

---

btw, doctor logic will update soon
https://github.com/appium/appium-doctor/pull/101

**Comment by josh-m-sharpe** [comment]
looks like `emulator` is right in the root of the sdk path for me: ~/Library/Android/sdk/emulator`

**Comment by Cristiano-Lobo** [comment]
Obrigado majdukovic. Tive o mesmo problema e agora foi resolvido.

**Comment by Tigrulla** [comment]
@majdukovic 
The Android SDK download is now half the size than it was before. One thing that has disappeared is the android.bat file.

This Link will give you a Android SDK that will install.
http://dl-ssl.google.com/android/repository/sdk-tools-windows-4333796.zip

It is not the latest but it will work.
