### ISSUE TITLE
Not able to achieve PRESS--WAIT--MOVE--RELEASE

### ISSUE THREAD

**Issue by vjvishjn** [appium/appium#14148]
## Environment

* Appium 1.17.0
* macOS 10.15.4
* Node.js version 13.12.0
* iPad Pro
* Real device
* Appium CLI

### What I want to achieve
Finger 1 | 
------------ | 
Press down at (start_x, start_y) | 
Wait for 5000ms |
Move to (end_x, end_y) |
Release |

### What I wrote to achieve that
```
    actionBuilder = ActionBuilder(appium_session.get_driver())
    finger1 = actionBuilder.add_pointer_input(POINTER_TOUCH, 'finger 1')
    finger1.create_pointer_move(x=start_x, y=start_y, origin='viewport')
    finger1.create_pointer_down(MouseButton.LEFT)
    finger1.create_pause(pause_duration=5)
    finger1.create_pointer_move(x=end_x, y=end_y, origin='viewport')
    finger1.create_pointer_up(MouseButton.LEFT)
    actionBuilder.perform()
```

### What is happening
Finger 1 | 
------------ | 
Press down at (start_x, start_y) | 
Moves to (end_x, end_y) with 5000ms duration|
Release |

## Link to Appium logs

https://gist.github.com/vjvishjn/d7873a1ded4a3599c1503200945bc0f6

**Comment by mykola-mokhnach** [comment]
Unfortunately no one here knows the answer. Try to ask at Appium forum
