### ISSUE TITLE
Can't open app on real device (default app)

### ISSUE THREAD

**Issue by reebostar** [appium/appium#14143]
## The problem

I'm trying to set up my testing real device for automated testing. But so far I'm trying to open default Google Maps app, I'm getting following error:

java.lang.SecurityException: Permission Denial: starting instrumentation ComponentInfo{io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner} from pid=17901, uid=17901 not allowed because package io.appium.uiautomator2.server.test does not have a signature matching the target io.appium.uiautomator2.server

## Environment

* Appium version (or git revision) that exhibits the issue: v1.14.0
* Desktop OS/version used to run Appium: Windows 10
* Mobile platform/version under test: Android 8.0.0
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: APP

## Details

Trying to run Appium on real Android Device (8.0.0). So far I'm ending on the same error all the time. Tried to downgrade from 1.15.1 to 1.14 aswell as Android Studio Build Tools and Platform-tools to version 25.0.3... nothing helps sadly.

My capabilities on run:
`{
  "deviceName": "ce011711384398bb0c",
  "platformName": "Android",
  "platformVersion": "8.0.0",
  "appPackage": "com.google.android.apps.maps",
  "appActivity": "com.google.android.maps.MapsActivity"
}`

Tried to uninstall uiautomator2 server before runs...

```
adb uninstall io.appium.uiautomator2.server.test
adb uninstall io.appium.uiautomator2.server
```

Still getting this error:

> java.lang.SecurityException: Permission Denial: starting instrumentation ComponentInfo{io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner} from pid=23643, uid=23643 not allowed because package io.appium.uiautomator2.server.test does not have a signature matching the target io.appium.uiautomator2.server

## Link to Appium logs
https://github.com/reebostar/reeborepo/blob/master/AppiumSecurityIssue.log

**Comment by mykola-mokhnach** [comment]
Duplicate of https://github.com/appium/appium/issues/14001

Please upgrade the server and try again

**Comment by reebostar** [comment]
I tried upgrade whole Appium (to 1.15.1), the server buildin is 4.3.0 but still same error occurs...

https://github.com/reebostar/reeborepo/blob/master/ApimSecurityIssue_430.log

**Comment by reebostar** [comment]
> Duplicate of #14001
> 
> Please upgrade the server and try again

I tried upgrade whole Appium (to 1.15.1), the server buildin is 4.3.0 but still same error occurs...

https://github.com/reebostar/reeborepo/blob/master/ApimSecurityIssue_430.log

**Comment by mykola-mokhnach** [comment]
The recent stable version is 1.17 though

**Comment by reebostar** [comment]
Is there a desktop version of it? I would like to use with GUI sofar I'm newbie in this at all. Thanks

> The recent stable version is 1.17 though

**Comment by mykola-mokhnach** [comment]
It is not mandatory to use the same Appium server version, that is bundled with the UI client. You can connect to any server version using the same UI client.

**Comment by reebostar** [comment]
Ahh thanks, actually upgrading to 1.17 Appium Desktop version with its server helped.
The previous version worked aswell, but only for UiAutomator1.. UiAutomator2 has the following issue with server...
