### ISSUE TITLE
Problems with Json syntaxe at HTTP 

### ISSUE THREAD

**Issue by vladikstyle** [appium/appium#14140]
Hello to all. I using HTTP requests to control the appium server. After reading the documentation, I do not understand how I should use "" or '' or something else . I saw at cmd appium the request like http://127.0.0.1:4723/wd/hub/session/[[SESSION_ID]]/elements  POST DATA : {"using" : "id","value" : "myidappelement"}  . That working OK . But when i want use it and send next request with parameters => 
URL : http://127.0.0.1:4723/wd/hub/session/[[SESSION_ID]]/touch/down
POST DATA : {"x" : "48","y" : "1032"} 
i had error 
"message":"org.json.JSONException: No value for params" . 
Please if anyone can add examples to Appium API documentation in HTTP EXAMPLES . PLEASE
Thank you!

**Comment by mykola-mokhnach** [comment]
Please use Appium [forum](discuss.appium.io) to ask questions. This is the place for issues.

**Comment by vladikstyle** [comment]
Not Found link

**Comment by mykola-mokhnach** [comment]
https://discuss.appium.io

**Comment by vladikstyle** [comment]
thank you . friend
