### ISSUE TITLE
Appium 17.0 hanging on webview (iOS 13)

### ISSUE THREAD

**Issue by tking16** [appium/appium#14149]
## The problem

I have a test where I open a Facebook Webview to log in, but simply trying to find an element once you switch to said Webview has Appium hanging forever!

The breaking code:
webview = self._driver.contexts[-1]
self._driver.switch_to.context(webview)
self._driver.find_element(facebook_locators.EMAIL_FIELD)

after this I won't get an error, nothing will happen. Maybe if I left it for an hour something might eventually fall over
## Environment

Tried and failed on Appium 16.0 and 17.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS
* Node.js version (unless using Appium.app|exe): v13.8.0
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: iOS 13.3
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

[Please find the logs here](https://gist.github.com/tking16/3ad38d9ebb7d3ed6d1c4be66f52dfb87)

**Comment by imurchie** [comment]
Please try the latest beta. This is the alert checking logic failing.

**Comment by tking16** [comment]
The beta resolved the issue, thanks. Roughly when will this be officially released?

**Comment by jzaratei** [comment]
Hi @imurchie ,
I got the same issue even using the latest 1.17.1-beta.0
When I switch to a webview and then trying to get the page title my test gets stuck for several minutes In the logs you can see a continuously "NosuchAlert":

Please take a look at the las 5 min in the logs. Thanks for your support.

### Code to reproduce
```
Set<String> availableContexts = getContextHandles();
        for (String context : availableContexts) {
            if (context.contains("WEBVIEW")){
                AppiumDriverManager.getDriver().context(context);
                if (!AppiumDriverManager.getDriver().getTitle().isEmpty()) validWebViews.add(context);
            }
        }
```
       

```
2020-04-09 15:54:32:954 - [debug] [W3C (77e62a85)] Calling AppiumDriver.title() with args: ["77e62a85-39e9-4df9-aaf3-2c7e701d103b"]
2020-04-09 15:54:32:954 - [debug] [XCUITest] Executing command 'title'
2020-04-09 15:54:32:955 - [debug] [RemoteDebugger] Executing atom 'title'
2020-04-09 15:54:32:955 - [debug] [RemoteDebugger] Executing 'title' atom in default context
2020-04-09 15:54:32:955 - [debug] [RemoteDebugger] Sending javascript command: '(function(){return function(){var g=this;functi...'
2020-04-09 15:54:32:956 - [debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:4975', page '6', target 'page-23' (id: 744): 'Runtime.evaluate'
2020-04-09 15:54:33:966 - [debug] [WD Proxy] Matched '/alert/text' to command name 'getAlertText'
2020-04-09 15:54:33:967 - [debug] [WD Proxy] Proxying [GET /alert/text] to [GET http://127.0.0.1:49934/session/B66730EB-7272-48F3-A9F0-2FEE2B650DF2/alert/text] with no body
2020-04-09 15:54:34:192 - [WD Proxy] Got response with status 404: {
2020-04-09 15:54:34:192 - [WD Proxy]   "value" : {
2020-04-09 15:54:34:193 - [WD Proxy]     "error" : "no such alert",
2020-04-09 15:54:34:193 - [WD Proxy]     "message" : "An attempt was made to operate on a modal dialog when one was not open",
2020-04-09 15:54:34:193 - [WD Proxy]     "traceback" : ""
2020-04-09 15:54:34:193 - [WD Proxy]   },
2020-04-09 15:54:34:193 - [WD Proxy]   "sessionId" : "B66730EB-7272-48F3-A9F0-2FEE2B650DF2"
2020-04-09 15:54:34:193 - [WD Proxy] }
```

### Environment
Appium 1.17.1-beta.0
Desktop OS/version used to run Appium: Mac OS
Node.js version (unless using Appium.app|exe): v12.16
Npm or Yarn package manager: NPM
Mobile platform/version under test: iOS 13.3
Real device or emulator/simulator: real device
Appium CLI or Appium.app|exe: CLI

### Link to Appium logs
https://gist.github.com/jzaratei/224e732e0f5831e906cda4ebdb60e5dd

**Comment by imurchie** [comment]
@jzaratei Is there an alert blocking the page?

What is happening in the JavaScript sent to the browser is not returning. Usually this means that there is an alert. Otherwise there is something going wrong with the atom.

If there is no alert, try adding the `safariLogAllCommunication` capability, set to `true`.

**Comment by jzaratei** [comment]
There' no alert that I can see in my app. Here is the logs with the additional cap.

https://gist.github.com/jzaratei/88324afaebb6fef583be13e944006d87

Basically, what I'm trying to do is get "valid" webviews. I realize that when getContextsHandles is executed, I get two webviews. One with the actual html and another one containing only this:

```
<html><head></head><body></body></html>
<body></body>
<head></head>
<html><head></head><body></body></html>
```
So, to get my actual webview I get into it and search for a title tag. This works fine until one last page that I get that alert error.

If you know, any tips for getting rid off invalid webviews that would be really helpfull.

**Comment by imurchie** [comment]
If that is the case, try using the `fullContextList` capability (set to `true`), which will make the call to `getContexts` return `id`, `url`, `title`, and `bundleId` for each webview. Alternatively, you can use the `mobile: getContexts` execute command to get the same information without the capability. This would let you check which one you want without needing to hit the server at all.

**Comment by jzaratei** [comment]
Hi @imurchie, thanks for the fullContextList tip, even it was kind of tricky to map the json string, now I'm using it and it works like a charm. But  getting back to the original issue. I'm still getting the "alert error".
So, it seems that this error occurs while I'm looking for an element from a Webview context, during a certain time period, but then my app loads a native page.

Like in this scenario: Starting from a webview context, I'm waiting for a loader-spinner to be not displayed  in order to check the next page is loaded (native page).

```
public static void waitUntilElementDisappear(WebElement element, int timeOut) {
 ExpectedCondition<Boolean> elementIsDisplayed = arg0 -> {
            try {
                element.isDisplayed();
                return false;
            } catch (Exception e) {
                return true;
            }
        };
        Wait(element, timeOut).until(elementIsDisplayed);
}
```
So, I'm expecting a _"notElementException"_ if the native page is loaded while I'm looking for the webview element.

Here is the gist with safariLogAllCommunication cap set to true
https://gist.github.com/jzaratei/766e5ad0e9b668675b353ef67754b05e

Thanks for your support.

**Comment by mykola-mokhnach** [comment]
From the testing perspective I'd rather wait for positive events. In this particular case it makes sense to wait for the native view to appear rather for the web view (or its elements) to disappear.

**Comment by jzaratei** [comment]
@mykola-mokhnach yeah you're right, if I change the logic of the scenario, as you suggest, my test passes. Even though, I think in both ways should do it. Anyway, thank you for your advice.

**Comment by mwakizaka** [comment]
I've encountered a similar issue. In my case, it takes around 60 seconds to set a web context and then find a web element. While finding a web element, I got a `no such alert` error.

As far as I checked, the following lines cause the issue. 
```
await await driver.elementByClassName("XCUIElementTypeWebView");
const contexts = await driver.contexts();
await driver.context(contexts[2]);
```
For further steps to reproduce, please take a look at the code to reproduce issue.

## Environment

* Appium version: **1.17.1**
* Desktop OS/version used to run Appium: **Mac OS**
* Node.js version: **v12.13.1**
* Npm: **6.12.1**
* Mobile platform/version under test: **iOS 13.4** 
* Real device or emulator/simulator: **Simulator**
* Appium CLI or Appium.app|exe: **Appium CLI**


## Link to Appium logs

[GIST](https://gist.github.com/mwakizaka/775bec155e60c1e0cc7a12b2386bc2df#file-appium_server-log)

## Code To Reproduce Issue

[GIST](https://gist.github.com/mwakizaka/775bec155e60c1e0cc7a12b2386bc2df#file-code_to_reproduce-js)

**Comment by KazuCocoa** [comment]
Thanks.
Hm, the below message probably meant the target WebView could not handle the message correctly. I assume Safari side got trouble...

```
[debug] [RemoteDebugger] Sending to Web Inspector took 1ms
[debug] [RemoteDebugger] Sending '_rpc_forwardIndicateWebView:' message to app 'PID:46544', page '2' (id: 6): 'indicateWebView'
[debug] [RemoteDebugger] Sending to Web Inspector took 0ms
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketSetup:' message to app 'PID:46544', page '2' (id: 7): 'setSenderKey'
[debug] [RemoteDebugger] Sending to Web Inspector took 1ms
[debug] [RemoteDebugger] Sender key set
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:46544', page '2' (id: 8): 'Inspector.enable'
[debug] [RemoteDebugger] Sending to Web Inspector took 1ms
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:46544', page '2' (id: 9): 'Page.enable'
[debug] [RemoteDebugger] Sending to Web Inspector took 1ms
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:46544', page '2' (id: 10): 'Network.enable'
[debug] [RemoteDebugger] Sending to Web Inspector took 0ms
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:46544', page '2' (id: 11): 'Runtime.enable'
[debug] [RemoteDebugger] Sending to Web Inspector took 0ms
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:46544', page '2' (id: 12): 'Heap.enable'
[debug] [RemoteDebugger] Sending to Web Inspector took 0ms
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:46544', page '2' (id: 13): 'Debugger.enable'
[debug] [RemoteDebugger] Sending to Web Inspector took 0ms
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:46544', page '2' (id: 14): 'Console.enable'
[debug] [RemoteDebugger] Sending to Web Inspector took 1ms
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:46544', page '2' (id: 15): 'Inspector.initialized'
[debug] [RemoteDebugger] Sending to Web Inspector took 1ms
[debug] [RemoteDebugger] Checking document readyState
[debug] [RemoteDebugger] Sending javascript command: 'document.readyState;'
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:46544', page '2' (id: 16): 'Runtime.evaluate'
[debug] [RemoteDebugger] Target created for app 'PID:46544' and page '2': {"targetId":"page-16","type":"page"}
[debug] [RemoteDebugger] Handling message (id: '8')
[RemoteDebugger] Received error from send that is not being waited for (id: 8): '{"code":-32601,"message":"'Inspector' domain was not found","data":[{"code":-32601,"message":"'Inspector' domain was not found"}]}'
[debug] [RemoteDebugger] Handling message (id: '9')
[RemoteDebugger] Received error from send that is not being waited for (id: 9): '{"code":-32601,"message":"'Page' domain was not found","data":[{"code":-32601,"message":"'Page' domain was not found"}]}'
[debug] [RemoteDebugger] Handling message (id: '10')
[RemoteDebugger] Received error from send that is not being waited for (id: 10): '{"code":-32601,"message":"'Network' domain was not found","data":[{"code":-32601,"message":"'Network' domain was not found"}]}'
[debug] [RemoteDebugger] Handling message (id: '11')
[RemoteDebugger] Received error from send that is not being waited for (id: 11): '{"code":-32601,"message":"'Runtime' domain was not found","data":[{"code":-32601,"message":"'Runtime' domain was not found"}]}'
[debug] [RemoteDebugger] Handling message (id: '12')
[RemoteDebugger] Received error from send that is not being waited for (id: 12): '{"code":-32601,"message":"'Heap' domain was not found","data":[{"code":-32601,"message":"'Heap' domain was not found"}]}'
[debug] [RemoteDebugger] Handling message (id: '13')
[RemoteDebugger] Received error from send that is not being waited for (id: 13): '{"code":-32601,"message":"'Debugger' domain was not found","data":[{"code":-32601,"message":"'Debugger' domain was not found"}]}'
[debug] [RemoteDebugger] Handling message (id: '14')
[RemoteDebugger] Received error from send that is not being waited for (id: 14): '{"code":-32601,"message":"'Console' domain was not found","data":[{"code":-32601,"message":"'Console' domain was not found"}]}'
[debug] [RemoteDebugger] Handling message (id: '15')
[RemoteDebugger] Received error from send that is not being waited for (id: 15): '{"code":-32601,"message":"'Inspector' domain was not found","data":[{"code":-32601,"message":"'Inspector' domain was not found"}]}'
[debug] [RemoteDebugger] Handling message (id: '16')
[RemoteDebugger] Setting communication protocol: using Target-based communication
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:46544', page '2', target 'page-16' (id: 17): 'Runtime.evaluate'
[debug] [RemoteDebugger] Page changed: {
```

**Comment by shibupanda** [comment]
@KazuCocoa It might be issue with the appium-remote-debugger lower version.
As @imurchie fixed some for 13.4. Please have look.
fix: do not send Target.exists on iOS 13.4 (#219)

**Comment by mwakizaka** [comment]
@shibupanda 

I'm afraid, but I think Appium 1.17.1 contains the fix according to the release note.
https://github.com/appium/appium/releases/tag/v1.17.1

**Comment by shrey126** [comment]
I am facing similar issue for Android Chrome browser as well. Here is the details:

- Appium version: 1.17.1
- Browser: Chrome
- Node: 12.10.0
- Platform: Android 
- Device and OS: Samsung Galaxy M31s(10) & Galaxy S9(9.0)

@mwakizaka , Can you please take a look?

**Comment by shibupanda** [comment]
@shrey126 
Could you please share Appium logs using GIST.

**Comment by shrey126** [comment]
@shibupanda , please refer Appium logs here: https://gist.github.com/shrey126/7b103c43be6bc887900500eb278b7198

**Comment by mwakizaka** [comment]
@shrey126 

I saw your Appium log. I think that you need to switch to an appropriate context before getting window handles.
http://appium.io/docs/en/commands/context/set-context/
You may already know but I think [this page](http://appium.io/docs/en/writing-running-appium/web/hybrid/) can help.

**Comment by shrey126** [comment]
@mwakizaka , yes exactly but for that I need to use switch action and it's hang when use this.

**Comment by mwakizaka** [comment]
> https://github.com/appium/appium/issues/14149#issuecomment-640065342

FYI. I've found that Safari does not hang any more on iOS14.2. (I couldn't find related info on Safari release note though.) 

## Environment

* Appium version: **1.19.0**
* Desktop OS/version used to run Appium: **Mac OS**
* Node.js version: **v12.13.1**
* Npm: **6.12.1**
* Mobile platform/version under test: **iOS 14.2** 
* Real device or emulator/simulator: **Simulator**
* Appium CLI or Appium.app|exe: **Appium CLI**


## Link to Appium logs

[GIST](https://gist.github.com/mwakizaka/d19d70cb5ec9a2bd9cbcdfe6098e98c2#file-ios14_2_appium_server-log)

## Code `Used` To Reproduce Issue

[GIST](https://gist.github.com/mwakizaka/d19d70cb5ec9a2bd9cbcdfe6098e98c2#file-reproduce_hang_issue-js)

**Comment by mykola-mokhnach** [comment]
Closed as resolved
