### ISSUE TITLE
Delay in response for first get alert text request in iOS 

### ISSUE THREAD

**Issue by iamabilash** [appium/appium#14159]
## The problem

WDA gives delay of around 1 minute for the first request to get alert text. 

## Environment

* Appium version (or git revision) that exhibits the issue: Latest
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Mac OS Catalina/Xcode 11.4
* Node.js version (unless using Appium.app|exe):N/A
* Npm or Yarn package manager: N/A
* Mobile platform/version under test: iOS/13.3.1
* Real device or emulator/simulator:Real Device (iPhone XS Max)
* Appium CLI or Appium.app|exe: N/A

## Details
When WDA tries to check for text alert  for first time, It gives a delay of around 1 minute in the response. This happens in the first alert request only and only seen in devices with iOS 13 and above.
The response time is quite fast for same next requests and works fine with device below iOS 13.

## Link to Appium logs
N/A

## Code To Reproduce Issue [ Good To Have ]
Create a session and tries to get the alert text with WDA.

**Comment by mykola-mokhnach** [comment]
Please provide both the server and xctest logs

**Comment by mykola-mokhnach** [comment]
Closed because of no response
