### ISSUE TITLE
Appium Android very long finding elements on the few pages

### ISSUE THREAD

**Issue by ddubtsov35** [appium/appium#14155]
Appium Android very long finding elements(~10 seconds) on the few pages, but he finding elements fast(less 1 second) on the other pages. Count elements equals on the this pages. 
I want communicate with dev team about this situation, but i dont know what say him. 
What parameter elements may be reason this result?

**Comment by mykola-mokhnach** [comment]
I would first investigate the logcat output. Regarding what to discuss with developers - is the application in idle state while visiting these pages or there's something, that constantly hugs the main thread?

**Comment by ddubtsov35** [comment]
@mykola-mokhnach  Thread sleep. Log (first element from other page and finding for 29 ms, second element - 10156 ms): 

_[HTTP] --> POST /wd/hub/session/a1296265-b3dc-4297-9d2b-c81edb48d64a/element
[HTTP] {"using":"id","value":"dev:id/send"}
[HTTP] <-- POST /wd/hub/session/a1296265-b3dc-4297-9d2b-c81edb48d64a/element 200 29 ms - 137
[HTTP] 
[HTTP] --> GET /wd/hub/session/a1296265-b3dc-4297-9d2b-c81edb48d64a/element/aa4e1446-df5c-4ef3-8221-67f2219364ce/displayed
[HTTP] {}
[HTTP] <-- GET /wd/hub/session/a1296265-b3dc-4297-9d2b-c81edb48d64a/element/aa4e1446-df5c-4ef3-8221-67f2219364ce/displayed 200 13 ms - 14
[HTTP] 
[HTTP] --> POST /wd/hub/session/a1296265-b3dc-4297-9d2b-c81edb48d64a/element/aa4e1446-df5c-4ef3-8221-67f2219364ce/click
[HTTP] {"id":"aa4e1446-df5c-4ef3-8221-67f2219364ce"}
[HTTP] <-- POST /wd/hub/session/a1296265-b3dc-4297-9d2b-c81edb48d64a/element/aa4e1446-df5c-4ef3-8221-67f2219364ce/click 200 25 ms - 14
[HTTP] 
[HTTP] --> POST /wd/hub/session/a1296265-b3dc-4297-9d2b-c81edb48d64a/element
[HTTP] {"using":"id","value":"dev:id/include_layout_toolbar"}
[HTTP] <-- POST /wd/hub/session/a1296265-b3dc-4297-9d2b-c81edb48d64a/element 200 10156 ms - 137
[HTTP] 
[HTTP] --> GET /wd/hub/session/a1296265-b3dc-4297-9d2b-c81edb48d64a/element/e69ca416-a5ff-44cf-8895-e9cfc857b74d/name
[HTTP] {}
[HTTP] <-- GET /wd/hub/session/a1296265-b3dc-4297-9d2b-c81edb48d64a/element/e69ca416-a5ff-44cf-8895-e9cfc857b74d/name 200 20179 ms - 14
[HTTP]_ 


Same situation and for Appium Desktop inspector:
_[HTTP] --> GET /wd/hub/session/3c05eeba-2a8f-423f-ba38-bc4505e8fe28/screenshot
[HTTP] {}
[MJSONWP (3c05eeba)] Calling AppiumDriver.getScreenshot() with args: ["3c05eeba-2a8f-423f-ba38-bc4505e8fe28"]
[HTTP] --> GET /wd/hub/session/3c05eeba-2a8f-423f-ba38-bc4505e8fe28/window/current/size
[HTTP] {}
[MJSONWP (3c05eeba)] Driver proxy active, passing request on via HTTP proxy
[HTTP] --> GET /wd/hub/session/3c05eeba-2a8f-423f-ba38-bc4505e8fe28/source
[HTTP] {}
[MJSONWP (3c05eeba)] Driver proxy active, passing request on via HTTP proxy
[WD Proxy] Matched '/screenshot' to command name 'getScreenshot'
[WD Proxy] Proxying [GET /screenshot] to [GET http://localhost:8200/wd/hub/session/e6bc41b4-1a01-4e38-8fe3-68f01e3da064/screenshot] with no body
[WD Proxy] Got response with status 200: {"sessionId":"e6bc41b4-1a01-4e38-8fe3-68f01e3da064","value":"iVBORw0KGgoAAAANSUhEUgAAAwAAAAUACAYAAADwUTW0AAAABHNCSVQICAgIfAhkiAAAIABJREFU\neJzs3Xd8VFXaB\/DfvdPTe++NJLQAQekqoAKCFXXdV0F3sa7rrn11dde2lnV1FfurroplVfC1IlhA\n6SgJPQkkpPcyqdPLve8fk0xmMjPJzGRKyvP9fPhIZm45cxPD85zznHOYeYsv5EEIIYQQQgiZFFh\/\nN4AQQgghhBDiO5QAEEIIIYQQMolQAkAIIYQQQsgkQgkAIYQQQgghkwglAIQQQgghhEwilAAQQggh\nhBAyiQj9cVOWZcFxHKbm5+L22zYgJysTYrEILCsAAHCcETqdHpVV1Xj5tbdx\/ESJ+RxCCCGEEEKI\n+xhf7gPAMAxCQ0Ow8bknkZmZAYYxvTYcnufB80BVdQ3uvOev6JB3+qi1hBBCCCGETDw+SwBEIhFe\nfuFpTJ+WP2LQ7wjH8Vh18dXo6e31cOs8IyUlCQBQV9fg55a4ZvasGeB5534MFEoVKioqvdwiQggh\nhEw0f3\/oPmSkpw57zPrf\/8FHrZncvF4CxLIMZkyfhlc3\/tPtwN\/yWtev+w02vvImeJ4HwzBOB66e\nFhoSggvOPw9LFs1H4ZwCu8cUFR\/F7r0H8P0PP43ZpOXhB+\/GqhXnu3SOQqHA4089j9179nupVYQQ\nQsjYFB8Xi+ysDGRnZ2J2wQwAQE52BoKCgszHKBQKlFdUAQAOHz2OiopKVJypQnNLq1\/a7IrYmGi0\ntrV75doZ6anIyc70yrWJa7w6AsAwDNZefjH+\/MebwbKemW+sUqmxbMVlkEmluHjNSny65QufJgGh\nISG4ft1vcPHqlQgIkDl1jkqlxlffbMO7mz4eU4nARSvPx0MP3O3WuQqFApdddT0UCoWHW0UIIYSM\nLdnZmbhoxXIsW...
[WD Proxy] Matched '/wd/hub/session/3c05eeba-2a8f-423f-ba38-bc4505e8fe28/window/current/size' to command name 'getWindowSize'
[WD Proxy] Proxying [GET /wd/hub/session/3c05eeba-2a8f-423f-ba38-bc4505e8fe28/window/current/size] to [GET http://localhost:8200/wd/hub/session/e6bc41b4-1a01-4e38-8fe3-68f01e3da064/window/current/size] with body: {}
[MJSONWP (3c05eeba)] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAAAwAAAAUACAYAAADwUTW0AAAABHNCSVQICAgIfAhkiAAAIABJREFU\neJzs3Xd8VFXaB/DfvdPTe++NJLQAQekqoAKCFXXdV0F3sa7rrn11dde2lnV1FfurroplVfC1IlhA\n6SgJPQkkpPcyqdPLve8fk0xmMjPJzGRKyvP9fPhIZm45cxPD85zznHOYeYsv5EEIIYQQQgiZFFh/\nN4AQQgghhBDiO5QAEEIIIYQQMolQAkAIIYQQQsgkQgkAIYQQQgghkwglAIQQQgghhEwilAAQQggh\nhBAyiQj9cVOWZcFxHKbm5+L22zYgJysTYrEILCsAAHCcETqdHpVV1Xj5tbdx/ESJ+RxCCCGEEEKI\n+xhf7gPAMAxCQ0Ow8bknkZmZAYYxvTYcnufB80BVdQ3uvOev6JB3+qi1hBBCCCGETDw+SwBEIhFe\nfuFpTJ+WP2LQ7wjH8Vh18dXo6e31cOs8IyUlCQBQV9fg55a4ZvasGeB5534MFEoVKioqvdwiQggh\nhEw0f3/oPmSkpw57zPrf/8FHrZncvF4CxLIMZkyfhlc3/tPtwN/yWtev+w02vvImeJ4HwzBOB66e\nFhoSggvOPw9LFs1H4ZwCu8cUFR/F7r0H8P0PP43ZpOXhB+/GqhXnu3SOQqHA4089j9179nupVYQQ\nQsjYFB8Xi+ysDGRnZ2J2wQwAQE52BoKCgszHKBQKlFdUAQAOHz2OiopKVJypQnNLq1/a7IrYmGi0\ntrV75doZ6anIyc70yrWJa7w6AsAwDNZefjH+/MebwbKemW+sUqmxbMVlkEmluHjNSny65QufJgGh\nISG4ft1vcPHqlQgIkDl1jkqlxlffbMO7mz4eU4nARSvPx0MP3O3WuQqFApdddT0UCoWHW0UIIYSM\nLdnZmbhoxXIsWbwA8XGxbl+nuaUVu/fsx9btP47J0fTYmGhkZ2di776DXrn+e2+/MmICMH/JCq/c\nm1jzWg...
[HTTP] <-- GET /wd/hub/session/3c05eeba-2a8f-423f-ba38-bc4505e8fe28/screenshot 200 438 ms - 62964
[HTTP] 
[WD Proxy] Got response with status 200: {"sessionId":"e6bc41b4-1a01-4e38-8fe3-68f01e3da064","value":{"height":1184,"width":768}}
[WD Proxy] Replacing sessionId e6bc41b4-1a01-4e38-8fe3-68f01e3da064 with 3c05eeba-2a8f-423f-ba38-bc4505e8fe28
[HTTP] <-- GET /wd/hub/session/3c05eeba-2a8f-423f-ba38-bc4505e8fe28/window/current/size 200 478 ms - 99
[HTTP] 
[WD Proxy] Matched '/wd/hub/session/3c05eeba-2a8f-423f-ba38-bc4505e8fe28/source' to command name 'getPageSource'
[WD Proxy] Proxying [GET /wd/hub/session/3c05eeba-2a8f-423f-ba38-bc4505e8fe28/source] to [GET http://localhost:8200/wd/hub/session/e6bc41b4-1a01-4e38-8fe3-68f01e3da064/source] with body: {}
[WD Proxy] Got response with status 200: {"sessionId":"e6bc41b4-1a01-4e38-8fe3-68f01e3da064","value":"\r\n\r\n  \r\n    \r\n      
[WD Proxy] Replacing sessionId e6bc41b4-1a01-4e38-8fe3-68f01e3da064 with 3c05eeba-2a8f-423f-ba38-bc4505e8fe28
[HTTP] <-- GET /wd/hub/session/3c05eeba-2a8f-423f-ba38-bc4505e8fe28/source 200 10744 ms - 30612
[HTTP]_

**Comment by mykola-mokhnach** [comment]
I was taking about logcat logs, not the server logs

**Comment by ddubtsov35** [comment]
@mykola-mokhnach Thanks. In the log i see

**Comment by ddubtsov35** [comment]
Yes, driver.setSetting(Setting.WAIT_FOR_IDLE_TIMEOUT, 100) helped me! Thanks for help!

**Comment by amedvedjev** [comment]
just wonder why not to set it by default to some small value? @mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
10000 ms is the default value in the UiAutomator framework itself. I assume Google developers know what they are doing (most likely :) )

**Comment by nageshc** [comment]
Hi @mykola-mokhnach,

How to use in Webdriver IO
broswer.updateSettings( { "waitForIdleTimeout": 10000 } ) ;

Is this correct way to use in Webdriver iO Javascript

Thanks in Advance

**Comment by pedrobrossmann** [comment]
Hi!

driver.setSetting(Setting.WAIT_FOR_IDLE_TIMEOUT, 100) works for me!
