### ISSUE TITLE
Vertical scroll doesn't work in Appium

### ISSUE THREAD

**Issue by abhi8130** [appium/appium#14158]
## I created a function for vertical scroll from bottom to top on android application. But it doesn't do any action on the app and also print the coordiantes on the console & pass the testcase. Below attached  Appium Serve Logs and function:
* [ ] Bug report
* [ .] Question
* [ ] Freature Request

## Summary
***CODE***
public void swipevertical() {
		Dimension size = driver.manage().window().getSize();
		System.out.println("Size" + size);
		int height = size.getHeight();
		int width = size.getWidth();
		int x = width/2;
		int top_y = (int) (height*0.80);
		int bottom_y = (int) (height*0.20);
		
		System.out.println("Cooridnates: " + "X: " + x + "top_y: " + top_y +"bottom_y: " + bottom_y);
		
		TouchAction ts = new TouchAction(driver);
		ts.longPress(PointOption.point(x,bottom_y)).moveTo(PointOption.point(x, top_y)).release().perform();
			
	}
	
## Environment
* Appium version (or git revision): 1.17
* `ruby_lib` version:
* Mobile platform/version/device under test: Android 9, 

## Actual behaviour and steps to reproduce
- While running the below code, it executes the code successfully but didn't do any action on the [app](url)
## Expected behaviour
 Should scroll vertically
## Link to Appium/Ruby logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 

## Any additional comments
![image](https://user-images.githubusercontent.com/40349857/78820639-c78bd580-79f5-11ea-9ba7-a7ab7a123c88.png)
![appium script console](https://user-images.githubusercontent.com/40349857/78820790-091c8080-79f6-11ea-813b-0926fa318d38.png)
![appium log](https://user-images.githubusercontent.com/40349857/78820798-0ae64400-79f6-11ea-91f4-a0d0512e2c0b.png)

**Comment by abhi8130** [comment]
On the logcat of the eclipse, it doesn't show any exception or error. it simply executes the code and prints "executed touchscreen" on the console and all the test cases. are passed. above I attached the screenshot for the same as well.


**- the only thing which is bothering me is that on the appium log  i.e. Responding to the client with the driver.performTouch(): null**

I am trying to automate Tik Tok like  Application. Any suggestion would really get me out of this

**Comment by mykola-mokhnach** [comment]
https://appiumpro.com/editions/107

**Comment by mykola-mokhnach** [comment]
The touch action itself looks good. Try to enable touch pointer tracking on the device and observe the actual touch action behaviour. Also, add more debugging into the application under test to see if correct events are generated there in response to the triggered touch action.
Unfortunately there is nothing more that could be done from the Appium side.

**Comment by abhi8130** [comment]
mykola-mokhnach 

- Thanks for the link

**Comment by abhi8130** [comment]
I am able to scroll down by this logic :
 MobileElement element = driver.findElement(MobileBy
		  .AndroidUIAutomator("new UiScrollable(new UiSelector().resourceId(\"com.getyovo:id/texture_view\"))"
		  + ".setMaxSearchSwipes(3).scrollIntoView(" +
		  "new UiSelector().text(\"Unblock Me FREE\"))"));
		 
- Could you please tell how do i scroll up by using the  UiScrollable & UiSelector class
- Appium v1.17.2
- Appium client (java) v7.3.0

As all the swipe and scroll methods are deprecated, please suggest how to achieve it

**Comment by mykola-mokhnach** [comment]
Kindly use Appium forum to ask questions.

Closed as not an issue

**Comment by abhi8130** [comment]
Find the solution using TouchAction_Class:
		TouchAction action = new TouchAction(driver);
		action.press(PointOption.point(x1, y1)).moveTo(PointOption.point(x2, y2)).release().perform();
