### ISSUE TITLE
tap/click on button not working in real device iOS 12.4 version.

### ISSUE THREAD

**Issue by ishanm120** [appium/appium#14157]
## The problem

Tap/Click on button not working in iOS version 12.4.
Tried the same of different appium versions

## Environment

* Appium 1.17.1-beta.0 , 1.14, 1.15
* iPhone Real device X  OS version 12.4
* Mac OS 10.14.4 (18E227)
* Npm 6.14.3

```
/usr/local/lib
└─┬ appium@1.17.1-beta.0
  ├─┬ appium-ios-driver@4.6.2
  │ └── appium-remote-debugger@4.5.0 
  └─┬ appium-xcuitest-driver@3.20.0
    └── appium-remote-debugger@8.9.0 
```

## Details

I am trying to click on button using my selenium script, but it's not working.
Tried with different appium versions but result is failure.

**But With same appium version(mentioned above) it works fine when i try to get mobile coordinates and click.**
as per one of the solution mentioned in [https://github.com/appium/appium/issues/13512](url)

When i try the same code on **iphone OS version 12.1.1** , i get a browser pop up with message
**This site is attempting to open a pop-up window**

Ref: [https://github.com/appium/appium/issues/14091](url)

This issue is also persists.

## Link to Appium logs
https://gist.github.com/ishanm120/8b8400bc375bef37d35faf1c6cc70a2f

**Comment by KazuCocoa** [comment]
It looks related to the below preferences on your device since the attached log was JS related.
https://stackoverflow.com/questions/59273376/safari-show-pop-up-on-window-open
https://kb.wisc.edu/helpdesk/page.php?id=40874

**Comment by imurchie** [comment]
Some versions of Safari require native web tapping, which can be affected by using the `nativeWebTap` capability (set to `true`).

Do other buttons and links (that do not open a new window) work? If so, it may be an issue with opening new windows. I don't know what you've set for `safariAllowPopups`, since we do not have the full logs.

**Comment by ishanm120** [comment]
> Some versions of Safari require native web tapping, which can be affected by using the `nativeWebTap` capability (set to `true`).
> 
> Do other buttons and links (that do not open a new window) work? If so, it may be an issue with opening new windows. I don't know what you've set for `safariAllowPopups`, since we do not have the full logs.

Yes all other buttons and links are working fine.but new window opening creating issue.

**Comment by hemank5** [comment]
iOS Simulator - iPhone 11 on 13.3
Appium Desktop - 1.15.1

I am having the same issue it doesn't do anything though it **highlights** the element which has to be clicked.
But If I send this capability  **safariAllowPopups**: 'true'
Then it clicks the element but then I get this pop up message - 

<img width="342" alt="Screen Shot 2020-04-21 at 6 17 11 PM" src="https://user-images.githubusercontent.com/15861858/79930058-550af480-83fc-11ea-9905-5db2207bda07.png">
If I try to intervene this pop-up manually I can see it is opening the new tab/window (expected)

In Real Scenario without automation this pop-up never comes only while executing automation I am seeing this pop-up message.

How can I auto accept this pop-up message or disable this?
Currently I just want the link to open in new window(expected  behavior)

**Comment by hemank5** [comment]
> > Some versions of Safari require native web tapping, which can be affected by using the `nativeWebTap` capability (set to `true`).
> > Do other buttons and links (that do not open a new window) work? If so, it may be an issue with opening new windows. I don't know what you've set for `safariAllowPopups`, since we do not have the full logs.
> 
> Yes all other buttons and links are working fine.but new window opening creating issue.
> Please check if this can help you
> https://gist.github.com/ishanm120/3548bea173425d58271560911c4b6468

use these capabilities , mine worked after changing to this 

safariAllowPopups: 'true',
safariIngoreFraudWarning: 'true',
autoAcceptAlerts: 'true',
nativeWebTap: 'true'

**Comment by hemank5** [comment]
> Some versions of Safari require native web tapping, which can be affected by using the `nativeWebTap` capability (set to `true`).
> 
> Do other buttons and links (that do not open a new window) work? If so, it may be an issue with opening new windows. I don't know what you've set for `safariAllowPopups`, since we do not have the full logs.

If I keep nativeWebTap to true, it is creating problem with the other test, it is doing some random clicks but it does solve the problem of opening a link in new window. Let me know what's the fix for this without enabled this webtap how can I make sure it opens the new window without any prompt

**Comment by ishanm120** [comment]
> > Some versions of Safari require native web tapping, which can be affected by using the `nativeWebTap` capability (set to `true`).
> > Do other buttons and links (that do not open a new window) work? If so, it may be an issue with opening new windows. I don't know what you've set for `safariAllowPopups`, since we do not have the full logs.
> 
> If I keep nativeWebTap to true, it is creating problem with the other test, it is doing some random clicks **but it does solve the problem** of opening a link in new window. Let me know what's the fix for this without enabling this webtap how can I make sure it opens the new window without any prompt

@hemank5 

Did you try this?
https://kb.wisc.edu/helpdesk/page.php?id=40874

**Comment by hemank5** [comment]
> > > Some versions of Safari require native web tapping, which can be affected by using the `nativeWebTap` capability (set to `true`).
> > > Do other buttons and links (that do not open a new window) work? If so, it may be an issue with opening new windows. I don't know what you've set for `safariAllowPopups`, since we do not have the full logs.
> > 
> > 
> > If I keep nativeWebTap to true, it is creating problem with the other test, it is doing some random clicks **but it does solve the problem** of opening a link in new window. Let me know what's the fix for this without enabling this webtap how can I make sure it opens the new window without any prompt
> 
> @hemank5
> 
> Did you try this?
> https://kb.wisc.edu/helpdesk/page.php?id=40874

safariAllowPopups: 'true' 
this flag is doing that which the link says , without that it doesn't even click the link( it stays highlighted), when running automation. 
If I keep this flag safariAllowPopups to true then I see the same message - 'This site is attempting to open a pop-up window'

**Comment by ishanm120** [comment]
> > > > Some versions of Safari require native web tapping, which can be affected by using the `nativeWebTap` capability (set to `true`).
> > > > Do other buttons and links (that do not open a new window) work? If so, it may be an issue with opening new windows. I don't know what you've set for `safariAllowPopups`, since we do not have the full logs.
> > > 
> > > 
> > > If I keep nativeWebTap to true, it is creating problem with the other test, it is doing some random clicks **but it does solve the problem** of opening a link in new window. Let me know what's the fix for this without enabling this webtap how can I make sure it opens the new window without any prompt
> > 
> > 
> > @hemank5
> > Did you try this?
> > https://kb.wisc.edu/helpdesk/page.php?id=40874
> 
> safariAllowPopups: 'true'
> this flag is doing that which the link says , without that it doesn't even click the link( it stays highlighted), when running automation.
> If I keep this flag safariAllowPopups to true then I see the same message - 'This site is attempting to open a pop-up window'

try latest beta version of appium.

**Comment by hemank5** [comment]
> > > > > Some versions of Safari require native web tapping, which can be affected by using the `nativeWebTap` capability (set to `true`).
> > > > > Do other buttons and links (that do not open a new window) work? If so, it may be an issue with opening new windows. I don't know what you've set for `safariAllowPopups`, since we do not have the full logs.
> > > > 
> > > > 
> > > > If I keep nativeWebTap to true, it is creating problem with the other test, it is doing some random clicks **but it does solve the problem** of opening a link in new window. Let me know what's the fix for this without enabling this webtap how can I make sure it opens the new window without any prompt
> > > 
> > > 
> > > @hemank5
> > > Did you try this?
> > > https://kb.wisc.edu/helpdesk/page.php?id=40874
> > 
> > 
> > safariAllowPopups: 'true'
> > this flag is doing that which the link says , without that it doesn't even click the link( it stays highlighted), when running automation.
> > If I keep this flag safariAllowPopups to true then I see the same message - 'This site is attempting to open a pop-up window'
> 
> try latest beta version of appium.

tried still the same.

**Comment by KazuCocoa** [comment]
> If I keep nativeWebTap to true, it is creating problem with the other test, it is doing some random clicks but it does solve the problem of opening a link in new window.

Then, what about updating setting `nativeWebTap` via settings API?
https://appium.io/docs/en/advanced-concepts/settings/

**Comment by mykola-mokhnach** [comment]
Closed because of no response
