### ISSUE TITLE
allowTouchIdEnroll capability is not setting Touch ID Enroll in Simulator

### ISSUE THREAD

**Issue by arpitkup** [appium/appium#14150]
## The problem

I am trying to automate touch ID feature introduced in our app for one for the payment types. I set allowTouchIdEntroll to true using "capability.SetCapability("allowTouchIdEnroll", true);" When I run the test, the simulator and the app starts without Touch Id enabled. 

I am using xCode version 11.3.1, Appium V 1.16.0, Appium.WebDriver 3.0.2  & C# programming. 

I use terminal to launch appium and it is already been added in Accessibility under System Preferences.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.16.0
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium:NA
* Node.js version (unless using Appium.app|exe):10.16.0
* Mobile platform/version under test: iOS 13.3
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
https://gist.github.com/arpitkup/7e2e0f291f0586b74766118ec52a4078

## Code To Reproduce Issue [ Good To Have ]

          capability = new DesiredCapabilities();           
            capability.SetCapability("platformName", platformName);
            capability.SetCapability("platformVersion", platformVersion);
            capability.SetCapability("deviceName", deviceName);
            capability.SetCapability("allowTouchIdEnroll", true);
            capability.SetCapability("automationName", "XCUITest");
            capability.SetCapability("useNewWDA", true);
            capability.SetCapability("startIWDP", true);
            capability.SetCapability("app", app);
            capability.SetCapability("forceMjsonwp", true);

           driver = new IOSDriver<IOSElement>(new Uri(ServerUrl()), capability, 
           TimeSpan.FromSeconds(180));

**Comment by arpitkup** [comment]
<img width="512" alt="Screen Shot 2020-04-06 at 4 41 55 pm" src="https://user-images.githubusercontent.com/46307606/78617158-08c29f00-78a9-11ea-8330-3c8024416bd2.png">

**Comment by arpitkup** [comment]
I use terminal to launch appium and it is already been added in Accessibility under System Preferences.

**Comment by mykola-mokhnach** [comment]
> [BaseDriver] The following capabilities were provided, but are not recognized by Appium:
> [BaseDriver]   allowTouchIdEnroll
> [BaseDriver]   forceMjsonwp

Where it is stated that such capability exists?
Currently the only way to enroll TouchId is to call the `mobile: enrollBiometric` API.

**Comment by arpitkup** [comment]
Hi @mykola-mokhnach I was referring to http://appium.io/docs/en/commands/device/simulator/touch-id/

**Comment by mykola-mokhnach** [comment]
Then it must be a documentation issue

**Comment by arpitkup** [comment]
Thanks @mykola-mokhnach. I will try out mobile: enrollBiometric API.

**Comment by Andrewngabriel** [comment]
Where in the documentation would this need to be updated? Happy to make a contribution and update it.

**Comment by KazuCocoa** [comment]
Thanks very much!

https://github.com/appium/appium/blob/master/commands-yml/commands/device/simulator/toggle-touch-id-enrollment.yml is  http://appium.io/docs/en/commands/device/simulator/touch-id/

https://github.com/appium/appium-xcuitest-driver#mobile-enrollbiometric is `mobile: enrollBiometric`

**Comment by mykola-mokhnach** [comment]
Closed as resolved. Thanks @Andrewngabriel
