### ISSUE TITLE
Unable to uninstall 1.11.0 or install 1.16.0

### ISSUE THREAD

**Issue by QAthulhu** [appium/appium#14153]
## The problem

I keep using npm uninstall and install but no matter what happens, when I enter appium -v I get 1.11.0. I've tried
```
npm uninstall appium
npm uninstall -g appium
npm uninstall appium@1.11.0
npm uninstall -g appium@1.11.0
npm install appium
npm install -g appium
npm install appium@1.16.0
npm install -g appium@1.16.0
```
And after each one I checked my appium version, it's always 1.11.0. I've tried installing version 1.16.0 through avm with avm 1.16.0 but got an error:
```
avm 1.16.0                                                                                                                           1 ↵  1390  10:01:13  
      exists : 1.11.0

avm use 1.16.0                                                                                                                           1389  10:00:49  

  Error: 1.16.0 is not installed
```
I've tried removing 1.11.0 through avm with avm rm 1.11.0. No errors are displayed but still appium -v gives me 1.11.0.

I need 1.16.0 because we're running our tests on App Center
## Environment

* Appium version (or git revision) that exhibits the issue: 1.11.0
* Desktop OS/version used to run Appium: MacOS Mojave
* Node.js version (unless using Appium.app|exe): 12.11.1
* Npm or Yarn package manager: 6.11.3

**Comment by KazuCocoa** [comment]
What is `avm`?
Appium depends on `npm`, but if the command handled npm module its own way, the issue seems the tool's one. I'd recommend you to report it to the tool
