### ISSUE TITLE
Element.getAttribute("value") always returns " " from my java test  but can get value attribute in inspector

### ISSUE THREAD

**Issue by Devapal** [appium/appium#14165]
## The problem

I can get value attribute in inspector when I am using appium deskop to test ipa on iPhone, but [.getAttribute("value")] always returns " " in my test program (Java with Eclipse, Java Client 7.3.0 ).  Even the page source does not show the value.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1 beta
* Desktop OS/version used to run Appium: macOS Catalina, 10.15.4
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real Device (iPhone X 13.3.1)
* Test Program: Java with Eclipse
* Java Client: 7.3.0
* Xcode: 11.4
* Device OS: 13.3.1

## Details
I am able to see the "value" in Appium inspector but from my code when I do element.getattribute("value"),  I get " ". Please advise.

Sample Code for your reference (both returned " "):
element.getAttribute("value");
element.getText();

_Update to my previously posted Question:  4/11/2020
I have updated my iPhone to 13.4 (Previously 13.3.1) in efforts to debug this issue and now I don't see the value in inspector either.
At least, previously with Appium 1.17.1 beta I was able to see the value in the inspector but I was not able to get the value from code but after upgrading to 13.4, I do not see a value neither in inspector nor through code._

**Comment by mykola-mokhnach** [comment]
It is impossible to advice anything without the appropriate issue information. 
Please provide the server log, xctest log, page source output and the description output.

**Comment by cheffey** [comment]
Please provide the server log, xctest log, page source output and the description output
page source acquire method: driver.getPageSource()
Also what is the method you use to find the elements? Are you sure it's targeting the text element?  Getting the page source would really help.

**Comment by Devapal** [comment]
@mykola-mokhnach @cheffey sorry guys for the delay, let me send you the requested details

**Comment by Devapal** [comment]
<img width="1411" alt="Screen Shot 2020-04-11 at 9 47 51 PM" src="https://user-images.githubusercontent.com/35826618/79059402-24c69780-7c3f-11ea-88a2-186592395573.png">
[PageSource13.4.txt](https://github.com/appium/appium/files/4465788/PageSource13.4.txt)

**Comment by Devapal** [comment]
@cheffey I am targeting the "XCUIElementTypeTextField" element and I am using iOS Class chain to find the element.  MobileBy.iOSClassChain(("**/XCUIElementTypeTextField")).  Updated the comments with page source and screenshot. You can download the app from App Store if you would like to download for debugging. App Name: **Arclight**

**Comment by mykola-mokhnach** [comment]
> after upgrading to 13.4, I do not see a value either in inspector or through code

This is clearly a XCTest issue, since there were no changes in Appium related to page source generation or values retrieval. Unfortunately, there is nothing we could do there on the server side.

Closed as third party issue.
