### ISSUE TITLE
Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up

### ISSUE THREAD

**Issue by chanchalsoni123** [appium/appium#14160]
## The problem
Whenever m trying to execute two test cases using testng.xml file, in the middle of the second text execution, "socket hangs up error is getting thrown"  always. Not even executed once. 

## Environment
* Appium version -1.16.0
* Desktop OS/version used to run Appium: Windows 10
* Emulator - pixel 3, android 9
* Node.js version (unless using Appium.app|exe): - v12.14.1
* Npm -6.13.4

Kindly help me to solve the above  mentioned issue.

**Comment by mykola-mokhnach** [comment]
Please provide the full server log and the device logcat log.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
