### ISSUE TITLE
Find element always return none type while page source displays correctly 

### ISSUE THREAD

**Issue by pocoyo-coder** [appium/appium#14167]
## The problem

After upgrading from appium 1.14.2 to 1.17.0 for ios 11/12 real devices - find element seems to return none types instead of the appium object, while in page source everything is showing correctly. 

## Environment

* Appium version (or git revision) that exhibits the issue: v1.17.0
* Last Appium version that did not exhibit the issue (if applicable): v1.14.2
* Desktop OS/version used to run Appium: macOS 10.15.4
* Node.js version (unless using Appium.app|exe): v13.12.0
* Npm or Yarn package manager: v6.14.4
* Mobile platform/version under test: ios 11/12
* Real device or emulator/simulator: real devices
* Appium CLI or Appium.app|exe:  CLI
*current Xcode: 11.4
*Last known working xcode:  10.2

## Details

I have been looking to update our appium setup and to test for the latest stable version of appium (1.17.0), xcuitest driver (3.17.0)  and web driver agent https://github.com/appium/WebDriverAgent master branch.

We are running on ios real devices OS 11/12/13. the 13 are working, but 11 and 12 seemed to have lost their support when trying to find elements. I always get a none type while page source is displaying the correct elements and attributes. 

Let's look at safari for example and trying to set value to a url. when trying to lock on with predicate I get a none type. So how come page source is correct while find element is not?

I am using a working code that we are running for over a year now so no breakage here. what am I missing?

I tried building wda with xcode 10.2 but the issue persists. I also tried lowering the wda tag to 2.7.4 but the issue persists.

## Link to Appium logs

https://gist.github.com/pocoyo-coder/138f1dcbdeebca1fccc874244ae703ca

## Code To Reproduce Issue

this is a code (python) that I wrapped so it is not a "copy paste" scenario, sorry for that:
driver.find_element(ios_predicate='wdlabel="Address" and wdname="URL"').set_value('bla.com')

**Comment by mykola-mokhnach** [comment]
> 2020-04-10 01:31:19:580 [WD Proxy] Matched '/element' to command name 'findElement'
> 2020-04-10 01:31:19:580 [WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:21778/session/5CBA396F-DDFA-438D-A3DC-556F503D8ED0/element] with body: {"using":"predicate string","value":"wdlabel=\"Address\" and wdname=\"URL\""}
> 2020-04-10 01:31:19:588 [Xcode]     t =   108.41s     Find: Descendants matching type Sheet
> 2020-04-10 01:31:19:588 [Xcode] 
> 2020-04-10 01:31:19:599 [WD Proxy] Got response with status 500: {"value":{"error":"unknown error","message":"The attribute 'wdlabel' is unknown. Valid attribute names are: (\n    UID,\n    accessibilityContainer,\n    accessible,\n    enabled,\n    frame,\n    label,\n    name,\n    rect,\n    selected,\n    type,\n    value,\n    visible,\n    wdAccessibilityContainer,\n    wdAccessible,\n    wdEnabled,\n    wdFrame,\n    wdLabel,\n    wdName,\n    wdRect,\n    wdSelected,\n    wdType,\n    wdUID,\n    wdValue,\n    wdVisible\n)","traceback":"(\n\t0   CoreFoundation                      0x000000018478bd50 <redacted> + 148\n\t1   libobjc.A.dylib                     0x0000000183ca0528 objc_exception_throw + 56\n\t2   WebDriverAgentLib                   0x0000000109cc2380 +[FBElementUtils wdAttributeNameForAttributeName:] + 668\n\t3   WebDriverAgentLib                   0x0000000109cbea8c +[NSExpression(FBFormat) fb_wdExpressionWithExpression:] + 576\n\t4   WebDriverAgentLib                   0x0000000109cd5f64 __50+[NSPredicate(FBFormat) fb_formatSearchPredicate:]_block...

What exactly is unclear with this error message?

**Comment by pocoyo-coder** [comment]
Is the 'wd' + attribute changed? is that what causes it?

**Comment by KazuCocoa** [comment]
Perhaps you should specify them as case sensitive like `wdLabel`

**Comment by pocoyo-coder** [comment]
I am closing this none issue as it is shameful by me.
I thank you for your help.
