### ISSUE TITLE
chromedriver_autodownload TypeError: Invalid Version: 69

### ISSUE THREAD

**Issue by chirarobert** [appium/appium#14161]
## The problem

Chrome driver auto download adds invalid chrome version to mapping file. I was running tests on an emulator with chrome version "69.0.3497". After downloading the chromedriver files the chrome version added to the mapping file is "69". Because of this I get the error : "TypeError: Invalid Version: 69"

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.0
* Desktop OS/version used to run Appium: macOS Catalina 10.15.3 (19D76)
* Node.js version (unless using Appium.app|exe): v12.9.1
* Npm or Yarn package manager: 6.10.3
* Mobile platform/version under test: android os 9
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: CLI

## Details

After it autodownload the files the content of the .json file is:
```
{
  "2.43": "69",
  "2.44": "69"
}
```
If I rerun the test with the chromedriver files already downloaded I get the same error. It will only work if the files are downloaded and I change the data in .json from "69" -> "69.0.3497"

## Link to Appium logs

[appium logs](https://gist.github.com/chirarobert/8d718eb257f59b536a5b8fe4b83e6ca3)

**Comment by mykola-mokhnach** [comment]
@chirarobert Could you please check if https://github.com/appium/appium-chromedriver/pull/168 fixes the issue for you?

**Comment by chirarobert** [comment]
@mykola-mokhnach How do update appium with your commit? Should I manually change the file?

**Comment by mykola-mokhnach** [comment]
Follow the tutorial at https://github.com/appium/appium/issues/13227#issuecomment-531812534

Simply replace `appium-webdriveragent` module name with the `appium-chromedriver`

**Comment by chirarobert** [comment]
I tried following the tutorial in the comment but I got 
```Link target resolves to the same directory as link source: /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver``` 
when I tried
```npm install --save appium-chromedriver && npm link appium-chromedriver```

your change was in the file, but I got the same error with invalid version. Not sure if your fix was applied though

**Comment by mykola-mokhnach** [comment]
Please make sure the linked sources have been transpiled properly (the content of `build` folder should be up to date with the content of `lib` one)

**Comment by mykola-mokhnach** [comment]
Also Appium itself should be restarted to pick up the changes

**Comment by chirarobert** [comment]
@mykola-mokhnach I restarted appium and checked the content on the build folder and chromedriver.js in build is different from the one in lib, but I am not familiar enough with node to know why. Sorry about his.

**Comment by mykola-mokhnach** [comment]
no problem. Let me publish the change, so you can try it in appium@beta

**Comment by mykola-mokhnach** [comment]
the patch has been published

**Comment by chirarobert** [comment]
Verified fix on appium@beta and it works fine now, closing ticket. Thanks @mykola-mokhnach
