### ISSUE TITLE
Getting Device model information from WDA 

### ISSUE THREAD

**Issue by brummetj** [appium/appium#14172]
## The problem
 
hello! 

We need to be able to get the iOS model type from WDA endpoints, specifically `"model" : "iPad"` or `"model": "iPhone"` 

I noticed that in the appium webdriveragent there is an endpoint /wda/device/info in FBCustomCommands.m, but it requires a session and doesn't seem to work correctly if i have a session running.... If i add `.withoutSession` to the FBRoute it works fine.

Our iOS devices are connected through Xcode via Wi-Fi ( wireless debugging ) so terminal commands won't work and using the WDA is probably our best bet to get this information. 

Example outputs from endpoints with and without said above changes: 

```
before with 

[[FBRoute GET:@"/wda/device/info"] respondWithTarget:self action:@selector(handleGetDeviceInfo:)],

}jbrumm730 in scripts $ curl -get http://<device_ip>:8100/wda/device/info
{
  "value" : {
    "error" : "unknown command",
    "message" : "Unhandled endpoint: \/wda\/device\/info -- http:\/\/<device_ip>:8100\/ with parameters {\n    wildcards =     (\n        \"wda\/device\/info\"\n    );\n}",
    "traceback" : ""
  },
  "sessionId" : "EC3B34E0-A4D1-4C49-8CA7-50051E544BEA"
}

after adding withoutSession

[[FBRoute GET:@"/wda/device/info"].withoutSession respondWithTarget:self action:@selector(handleGetDeviceInfo:)],

jbrumm730 in scripts $ curl -get http://<device_ip>:8100/wda/device/info
{
  "value" : {
    "timeZone" : "America\/Denver",
    "currentLocale" : "en_US",
    "model" : "iPad",
    "uuid" : "63CC7DC2-5E5D-4E15-842A-421B8D34AF8D",
    "userInterfaceIdiom" : 1,
    "isSimulator" : false,
    "name" : "Brummet, Joshua DMPZP082KD80"
  },
  "sessionId" : "66AA1B5E-4757-4957-9172-DB2A24CFB8FD"
```

Am i just using this endpoint wrong or would there need to be a PR to get this change in there? 

cheers

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0-beta.3
* Desktop OS/version used to run Appium: OSX Catalina v10.15
* Node.js version (unless using Appium.app|exe): 6.13.4
* Npm or Yarn package manager:
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: real devices
* Appium CLI or Appium.app|exe: appium clie

**Comment by mykola-mokhnach** [comment]
Feel free to push a PR. We will review it ASAP.

**Comment by brummetj** [comment]
Sounds good thanks @mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
the PR has been merged
