### ISSUE TITLE
Didn’t generate zip-with-dependencies.zip file on target folder for Appium testNG for AWS Devicefarm

### ISSUE THREAD

**Issue by vaibhav107raj** [appium/appium#14176]
## The problem

All the pre- required configurations were made in pom.xml file, however the " zip-with-dependencies.zip" file did not got generated which is highly required for Appium testNG configuration check on AWS Devicefarm

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15
* Desktop OS/version used to run Appium: mac os
* Mobile platform/version under test: Android

## Details

As per the requirements zip.xml file was generated at the src/main/assembly and pom.xml file was configured as per AWS devicefarm documentation. 

pom.xml file link : [pom](https://gist.github.com/vaibhav107raj/f09a8062fe46da15df2edd920281879c)

Trying to make the zip-with-dependencies.zip file, the logs generated as below:

[logs](https://gist.github.com/vaibhav107raj/d38a2b67296c6a96b5255c954e913ad9)

Kindly suggest the way to generate the zip-with-dependencies.zip file

**Comment by mykola-mokhnach** [comment]
Sorry, the issue is completely unrelated to what is supposed to be posted here. Please forward it to AWS support. 
Also, we have [Appium forum](discuss.appium.io) for different kinds of questions.
