### ISSUE TITLE
failed to click element at the edge of screen on iOS

### ISSUE THREAD

**Issue by KageyamaRuka** [appium/appium#14177]
## The problem

hello again, found a new problem when checking the swipe issue on iOS device, when the element is at the edge of the screen, it can be found by the driver, but failed to click

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.0
* Desktop OS/version used to run Appium: macOS 10.15.3
* Node.js version (unless using Appium.app|exe): v13.11.0
* Npm or Yarn package manager: 6.13.7
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: cli

## Details

![IMG_4505](https://user-images.githubusercontent.com/24635872/79106241-b1d73100-7da4-11ea-93da-d0b80ff9eb33.PNG)

## Link to Appium logs

https://gist.github.com/KageyamaRuka/90237c04a1bf1d3fabe70be6f71828ff

**Comment by mykola-mokhnach** [comment]
This looks like an XCTest issue to me. By tapping an element it calculates a hit point and it might be its coordinates is out of the viewport. You could try to click by coordinates as a workaround. Or scroll the button until is is fully visible.

**Comment by KageyamaRuka** [comment]
@mykola-mokhnach yes, tap by coordinates works as expected, seems that XCTest isn't a well enough libraries under the hood to be depend on...

**Comment by mykola-mokhnach** [comment]
There are no alternatives. This is normal in a closed source commercial ecosystem, which iOS is.

**Comment by amedvedjev** [comment]
@KageyamaRuka it happens as far as click uses center of element. while center on screen exactly on edge and manual tap fails it here also. As workaround use any left corner of element and tap by x,y.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
