### ISSUE TITLE
page source not refreshed after swipe operation on iOS

### ISSUE THREAD

**Issue by KageyamaRuka** [appium/appium#14174]
## The problem

page source not refreshed after swipe operation on iOS

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.0
* Desktop OS/version used to run Appium: macOS 10.15.3
* Node.js version (unless using Appium.app|exe): v13.11.0
* Npm or Yarn package manager: 6.13.7
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: cli

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

[appium.log](https://github.com/appium/appium/files/4464368/appium.log)

## Code To Reproduce Issue [ Good To Have ]

https://github.com/KageyamaRuka/issue_demo/blob/master/ios_demo.py

[swipe_script.log](https://github.com/appium/appium/files/4464369/swipe_script.log)

**Comment by mykola-mokhnach** [comment]
Is the accessibility source changed after the described action in the iOS accessibility inspector?
Appium simply reflects what XCTest provides to it. So, if the original accessibility source in XCTest stays the same then there is no way it could be changed in Appium.

**Comment by KageyamaRuka** [comment]
@mykola-mokhnach Hi mykola-mokhnach, In my opinion, if we take this as an issue, the appium can do a force refresh after a swipe operation, is there any command that can do a page-source refresh on iOS in appium?

**Comment by KazuCocoa** [comment]
How about calling `mobile: source` with `format : description` argument?
https://github.com/appium/appium/issues/13595#issuecomment-553298730

It gets debugDescriptions of each available element by XCTest framework recursively as debug. You can observe the output if element data by XCTest framework changes.
If it did not change, Appium cannot do anything at least.

**Comment by KageyamaRuka** [comment]
> How about calling `mobile: source` with `format : description` argument?
@KazuCocoa how to do this with a python client?

**Comment by KazuCocoa** [comment]
http://appium.io/docs/en/commands/mobile-command/ is

**Comment by KageyamaRuka** [comment]
@mykola-mokhnach 
`[HTTP] --> POST /wd/hub/session/52fc79b9-27d8-43fc-9ba0-c8647659950a/execute/sync
[HTTP] {"script":"mobile: swipe","args":[{"direction":"left","element":"41020000-0000-0000-D427-000000000000","format":"description"}]}
[debug] [W3C (52fc79b9)] Calling AppiumDriver.execute() with args: ["mobile: swipe",[{"direction":"left","element":"41020000-0000-0000-D427-000000000000","format":"description"}],"52fc79b9-27d8-43fc-9ba0-c8647659950a"]
[debug] [XCUITest] Executing command 'execute'
[XCUITest] Proxying to WDA with an unknown route: POST /wda/element/41020000-0000-0000-D427-000000000000/swipe
[debug] [WD Proxy] Proxying [POST /wda/element/41020000-0000-0000-D427-000000000000/swipe] to [POST http://127.0.0.1:8100/session/4404D87C-5F5A-468F-BF48-969A5A43CA57/wda/element/41020000-0000-0000-D427-000000000000/swipe] with body: {"direction":"left"}
[debug] [WD Proxy] Got response with status 200: {"value":null,"sessionId":"4404D87C-5F5A-468F-BF48-969A5A43CA57"}
[debug] [W3C (52fc79b9)] Responding to client with driver.execute() result: null
[HTTP] <-- POST /wd/hub/session/52fc79b9-27d8-43fc-9ba0-c8647659950a/execute/sync 200 1179 ms - 14`

seems get a null response...

**Comment by mykola-mokhnach** [comment]
> Hi mykola-mokhnach, In my opinion, if we take this as an issue, the appium can do a force refresh after a swipe operation, is there any command that can do a page-source refresh on iOS in appium?

There is none I know of. XCTest framework is a black box and only has a couple of public ~~poorly~~ documented APIs. Feel free to dig deeper into WebDriverAgent sources and push a PR.

**Comment by KazuCocoa** [comment]
> The page source in description format didn't change,

Then, Appium cannot do anything, unfortunately. I also have no idea if we can refresh XCTest internal elements so far.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by rakhmatullov** [comment]
That's still an issue with iOS driver or XCTest in the iOS 14.5. The workaround for this is to call page_source as it refreshes the DOM, others are unknown by me yet.
