### ISSUE TITLE
Documentation Issue in parsing yml for mobile-command.yml file

### ISSUE THREAD

**Issue by HarshadSane** [appium/appium#14173]
## The problem

The documentation for mobile-command displays GET instead of POST on the browser

## Environment

* Appium Website

## Details

NA

## Link to Appium logs

NA

## Code To Reproduce Issue [ Good To Have ]
1. Open Browser
2. Enter URL
     http://appium.io/docs/en/commands/mobile-command/
3. The code in mobile-command.yml has method as POST, but it displays GET on the browser.
     https://github.com/appium/appium/edit/master/commands-yml/commands/mobile-command.yml

![GET_displayed_on_browser](https://user-images.githubusercontent.com/7992919/79038678-06ee2980-7b90-11ea-95d6-a3a6161a542d.png)

![POST_in_mobile-command_yml](https://user-images.githubusercontent.com/7992919/79038681-0c4b7400-7b90-11ea-8c2b-744f90499730.png)

**Comment by imurchie** [comment]
This is because the documentation has not been updated in 6 months. Not sure why. @dpgraham Is there a problem with the documentation building?

**Comment by KazuCocoa** [comment]
Afaik, the reason is `npm run serve & npm run crawl` in the appium.io repository fails because of broken links. https://github.com/appium/appium/pull/14067 will fix the issue I found broken links before.
I hope it will fix this issue...

**Comment by KazuCocoa** [comment]
Updated
e.g. http://appium.io/docs/en/commands/mobile-command/ has `mobile:setAppearance` in xcuitest
