### ISSUE TITLE
Cannot highlight controls when device's keyboard is visible

### ISSUE THREAD

**Issue by tuantran2019** [appium/appium#14183]
## The problem

I can't inspect another control in my app after I tap on a textbox control and the iOS's virtual keyboard is visible.

## Environment

* Appium version : 1.15.1
* Desktop OS/version used to run Appium: MacOS 10.15.3
* Mobile platform/version under test: 13.2.3
* Real device: Ipad Air 2

## Details

I often use "Start Inspector Session" in Appium server desktop to get information of the selected element. Unfortunately, I can't access any element in my app via "Appium inspector" when the device's virtual keyboard is opening. Appium inspector only accesses the child element of keyboard, and it only work normally until I close the virtual keyboard manually.

So, is there any solution to this? 
Please help me and let me know what is my wrong? How to inspect the element in my app when the virtual keyboard is visible?

Thanks.

**Comment by mykola-mokhnach** [comment]
Unfortunately there is no way to do that. The keyboard is a part of application accessibility, so everything behind it will be hidden unless the keyboard is hidden.

Consider reporting the issue to Apple if you think this is a bug

**Comment by tuantran2019** [comment]
> Unfortunately there is no way to do that. The keyboard is a part of application accessibility, so everything behind it will be hidden unless the keyboard is hidden.
> 
> Consider reporting the issue to Apple if you think this is a bug

Thank @mykola-mokhnach  so much.
