### ISSUE TITLE
Unable to deploy WebDriverAgent, Test Failed

### ISSUE THREAD

**Issue by promero90** [appium/appium#14182]
## The problem

I cannot deploy the WebDriverAgent in my real device, after a success build, a pop-up is shown with the message "Test Failed". I tried with the master branch of WebDriverAgent project with same result

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.0
* Last Appium version that did not exhibit the issue (if applicable): 1.17.0
* Desktop OS/version used to run Appium: MAC OSX 10.15.2 
* Node.js version (unless using Appium.app|exe): v13.7.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS 13.3.1
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe:

## Details

Additionally, I tried to delete the installed bundle and deploy it again, reboot the phone, updated Xcode with no success.

## Link to Appium logs

https://gist.github.com/promero90/c67393e0468df6d17e6ce38d51a4f16b

**Comment by mykola-mokhnach** [comment]
> 	/var/containers/Bundle/Application/DFDAC96D-5AB4-47B5-9524-9490E9B0AC82/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner: code signature invalid for '/var/containers/Bundle/Application/DFDAC96D-5AB4-47B5-9524-9490E9B0AC82/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner'

This is for sure a problem with signing. Have you tried to build and deploy WDA manually from Xcode?

**Comment by promero90** [comment]
> > /var/containers/Bundle/Application/DFDAC96D-5AB4-47B5-9524-9490E9B0AC82/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner: code signature invalid for '/var/containers/Bundle/Application/DFDAC96D-5AB4-47B5-9524-9490E9B0AC82/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner'
> 
> This is for sure a problem with signing. Have you tried to build and deploy WDA manually from Xcode?

Yes, I faced up to the pop-up with the message "Test Failed".

**Comment by mykola-mokhnach** [comment]
If it is not possible to run WDA from Xcode then Appium would not be able to do it as well. Please check the signing procedure with application developers.

**Comment by promero90** [comment]
I know, it is really strange. Any clue about how to fix it?

Thanks in advance

**Comment by mykola-mokhnach** [comment]
> Please check the signing procedure with application developers.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue. Unfortunately here is nothing that could be done on Appium side.
