### ISSUE TITLE
Unable to open designated application after deploy WebDriverAgent to device

### ISSUE THREAD

**Issue by baopn97** [appium/appium#14187]
## The problem
I have encountered this issue when trying to open application with Appium Desktop, i already tried to create new apple developer account with unique bundle id, and build both WebDriverAgentRunner, WbeDriverAgentLib on test device, and execute this command line:
```
cd /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent 
xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=e93169954da80f9931e96be2ab4280618b6ac764' clean build test
```
And log after trying to open application on appium desktop, but still facing the same error
Solution i have tried so far:
- Change new bundle ID, apple developer account
- Install previous Appium version (1.12, 1.13, 1.14)

## Environment

* Appium version (or git revision) that exhibits the issue: v1.15
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS 10.15.4
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: iOS 11.4.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium Desktop Application

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Log after execute command line: 
[command-execution-log.txt](https://github.com/appium/appium/files/4486055/command-execution-log.txt)

[appium-desktop-log.txt](https://github.com/appium/appium/files/4486092/appium-desktop-log.txt)

**Comment by mykola-mokhnach** [comment]
> Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the Signing & Capabilities editor.

Does the above statement mean it is possible to build WDA manually from Xcode, but the process fails while building from Appium? If this is the case then make sure that:
- WebDriverAgent sources that are build manually are located in the same folder that Appium tries to use (the full path is visible in logs)
- Appium process has access to the system keychain where the signing key is stored. See https://github.com/appium/appium/issues/10866

If it still does not work you may consider rpebuilding WDA and passing it to Appium. See the documentation on `useXctestrunFile` cap for more ddetails

**Comment by mykola-mokhnach** [comment]
Also Appium 1.15 is out of date. The current recent version is 1.17

**Comment by baopn97** [comment]
> Also Appium 1.15 is out of date. The current recent version is 1.17

i have updated Appium 1.17, issue still occured

**Comment by baopn97** [comment]
> If it still does not work then you may consider prebuilding WDA and passing it to Appium. See the documentation on `useXctestrunFile` cap for more ddetails

WebDriverAgentSource

> > Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the Signing & Capabilities editor.
> 
> Does the above statement mean it is possible to build WDA manually from Xcode, but the process fails while building from Appium? If this is the case then make sure that:
> 
> * WebDriverAgent sources that are build manually are located in the same folder that Appium tries to use (the full path is visible in logs)
> * Appium process has access to the system keychain where the signing key is stored. See #10866
> 
> If it still does not work then you may consider prebuilding WDA and passing it to Appium. See the documentation on `useXctestrunFile` cap for more ddetails

Turns out im configuring WDA project which installed by nodeJS, but Appium Desktop trying to install WDA project inside the Appium application itself, thanks for support
