### ISSUE TITLE
Encountered internal error running command: Error: Error attempting to start URI

### ISSUE THREAD

**Issue by shibupanda** [appium/appium#14180]
## The problem
We have more than 300+ test cases written with us. And we are launching chrome browser through appPackage and appActivity and then navigate to the URL. It's working perfectly on 7, 9, and 10 version of device but the issue is on 8 and 6 version of device.

I have tried to increase the adExecTimeout capability still getting the same.
NOTE: It is able to launch the url but in response it is sending 500 which is the cause of failure.

Happy to provide more info if it is required.  

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.0, 1.15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Ubuntu 18
* Node.js version (unless using Appium.app|exe): 10.15
* Npm or Yarn package manager: Npm
* Mobile platform/version under test: 8 and 6
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs
https://gist.github.com/shibupanda/9fec4299b544d00a6081c0ed7532e2ed

## Code To Reproduce Issue [ Good To Have ]
1. Please pick any Android v8.* or 6.* devices
2. Launch chrome using appPackage and appActivity
3. Launch the url will get the same issue

**Comment by mykola-mokhnach** [comment]
I think some steps in this scenario are redundant. The capabilities could be optimised to include the necessary intent action. See https://github.com/appium/appium/issues/13628 for more details. Also, it is possible to set `appWaitForLaunch` cap to `false` in such case if activity manager does not returns the control to adb after the timeout.

**Comment by shibupanda** [comment]
@mykola-mokhnach 
Thanks for the quick response but I am doing the same as per steps I mentioned you can see those in logs.
appWaitForLaunch = false didn't work me here. But manually when I ran those ad command it worked for me.
Any extra debug point need to add in capabilities? I can do that 
Or my last options to handle this error in appium code locally and move forward.

**Comment by mykola-mokhnach** [comment]
Please provide the updated log

**Comment by shibupanda** [comment]
@mykola-mokhnach I will share that.
I think below is the one we should look. Please let me know if I am passing any wrong capability.

2020-04-14 12:47:32:429 [BaseDriver] The following capabilities are not standard capabilities and should have an extension prefix:
2020-04-14 12:47:32:429 [BaseDriver]   appWaitForLaunch

**Comment by shibupanda** [comment]
@mykola-mokhnach Thanks for the info.
I cross verified in appium-adb code it is **waitForLaunch** not **appWaitForLaunch**
@property {?boolean} waitForLaunch [true] - if `false` then adb won't wait

I have gone through the code but there is no such condition for waitForLaunch capabilities which can remove -W from args.
https://github.com/appium/appium-adb/blob/master/lib/tools/apk-utils.js

Hope this info can help you.

**Comment by mykola-mokhnach** [comment]
Any chance to provide the updated logs?

**Comment by shibupanda** [comment]
@mykola-mokhnach Please find the updated logs having appWaitForLaunch = false.
Anyways I have fixed it about to send a rough pull request. Have changed two files.

appium-adb: apk-util.js
uiautomator2: general.js
If you want to have a look I can share those before sending a pull request.

**Comment by mykola-mokhnach** [comment]
Of course it won't work. `appWaitForLaunch` must be supplied in combination with `optionalIntentArguments` and/or `intentAction`

**Comment by shibupanda** [comment]
Could you help me here with some example?
It really help me.

**Comment by mykola-mokhnach** [comment]
Have you checked the linked issue? It has an example and also integration tests in the linked PR

**Comment by shibupanda** [comment]
@mykola-mokhnach I used 3 capabilities waitForLaunch, intentAction and optionalIntentArguments didn't help me. I will update you the logs.
If you can go through the apk-utils.js in appium-adb we can easily understand where the bug is. As there is no condition for startUri() method to skip -W from args.

Let me share you the snippet what I have changed but it not so standard.

**Comment by shibupanda** [comment]
**Added below line in apk-utils.js:**
var args;
  if(waitForLaunch){
    args = ['am', 'start', '-W', '-a', 'android.intent.action.VIEW', '-d', uri.replace(/&/g, '\\&'), pkg];
  }else{
    args = ['am', 'start', '-a', 'android.intent.action.VIEW', '-d', uri.replace(/&/g, '\\&'), pkg];
  }

**Added below line in general.js(uiautomator2):**
commands.setUrl = async function (url) {
  log.info(`Wait ForAppLaunch====================${this.opts.appWaitForLaunch}`)
  await this.adb.startUri(url, this.opts.appPackage, this.opts.appWaitForLaunch);
};

commands.mobileDeepLink = async function (opts = {}) {
  const {url, package: pkg} = opts;
  return await this.adb.startUri(url, pkg, this.opts.appWaitForLaunch);
};
**NOTE**: This changes did the work. 
**OUTPUT**: You can see now -W is not coming. I know it needs refactoring.

2020-04-15 18:18:32:019 [HTTP] --> POST /wd/hub/session/05e873b1-cd83-401e-952a-7b92aaeb8c7a/url
2020-04-15 18:18:32:019 [HTTP] {"url":"https://storefront.qa.acko.com/lp/new-comprehensive"}
2020-04-15 18:18:32:020 [W3C (05e873b1)] Calling AppiumDriver.setUrl() with args: ["https://storefront.qa.acko.com/lp/new-comprehensive","05e873b1-cd83-401e-952a-7b92aaeb8c7a"]
2020-04-15 18:18:32:021 [UiAutomator2] Wait ForAppLaunch====================false
2020-04-15 18:18:32:021 [ADB] Running '/Users/radmin/build/android/platform-tools/adb -P 5037 -s ad0117020eaea88a01 shell am start -a android.intent.action.VIEW -d https\://storefront.qa.acko.com/lp/new-comprehensive com.android.chrome'
2020-04-15 18:18:32:102 [W3C (05e873b1)] Responding to client with driver.setUrl() result: null
2020-04-15 18:18:32:103 [HTTP] <-- POST /wd/hub/session/05e873b1-cd83-401e-952a-7b92aaeb8c7a/url 200 84 ms - 14

**Comment by mykola-mokhnach** [comment]
I don't think we can change setUrl, since this would break the backward compatibility, but it is fine to have the additional argument to mobileDeepLink call

**Comment by mykola-mokhnach** [comment]
Also, like I said above, the test in its current implementation is suboptimal, since it starts chrome first and then executes the deep link (via setUrl), however this everything could be done in a single call on session startup

**Comment by shibupanda** [comment]
So could you please which module this needs to change. As it is taking time for me understand the complete flow. 
It's quite easy for you guys to give a snippet of changes actually. So that I can fix it immediately.

**Comment by mykola-mokhnach** [comment]
> It's quite easy for you guys to give a snippet of changes actually. So that I can fix it immediately.

I would have to test it locally the same way you'd do it, so "easy" is not the best term here.

> So could you please share which module this needs to change. As it is taking time for me understand the complete flow.

Lets do a minimal fix, which is not going to break anything:
- in appium-adb add an `opts` argument to `startUri` call, which could have `waitForLaunch` property
- in uia2 driver change the implementation of `mobileDeepLink` to handle `waitForLaunch` option and pass it to the corresponding adb call

**Comment by shibupanda** [comment]
@mykola-mokhnach 
Yes you can Ignore that word "easy". I am following you to learn from last 3 years. 
I don't want to hurt anybody. 

Thanks for your guidance.

**Comment by mykola-mokhnach** [comment]
@shibupanda Did you got a chance to create a PR?

**Comment by shibupanda** [comment]
@mykola-mokhnach 
Get stuck with some other planning to start on this weekend. Sorry for late update.

**Comment by shibupanda** [comment]
@mykola-mokhnach 
Please review it then I will create a PR. Tested locally with and without "waitForLaunch" worked as expected.
**uiautomator2 side changes**:

commands.setUrl = async function (url) {
  if(!this.opts.waitForLaunch){
    await this.adb.startUri(url, this.opts.appPackage, this.opts.waitForLaunch);
  }else{
    await this.adb.startUri(url, this.opts.appPackage);
  }
};

**appium-adb side changes:**
let args;
  if (!uri || !pkg) {
    throw new Error('URI and package arguments are required');
  }

  if(!waitForLaunch){
    args = [ 'am', 'start', '-a', 'android.intent.action.VIEW', '-d', uri.replace(/&/g, '\\&'), pkg, ];
  }else{
    args = [  'am', 'start', '-W', '-a', 'android.intent.action.VIEW', '-d', uri.replace(/&/g, '\\&'), pkg, ];
  }

**Comment by KazuCocoa** [comment]
You can create a PR to get a review.
BTW. https://github.com/appium/appium-adb/blob/fa02f68000722db20639ac28c78d5e6adb64cdfb/lib/helpers.js#L241 may help to build the command

**Comment by mykola-mokhnach** [comment]
The changes to appium-adb have been published, so you could continue with appium-uiautomator2-driver module now. Everything that needs to be done is to bump appium-adb version in package.json (the version number is the same as in the git tag) and add the corresponding property (`waitForLaunch`) to `mobileDeepLink` call options

**Comment by shibupanda** [comment]
Sure @mykola-mokhnach 
So no need to add anything in "setUrl" instead we can ask people to use "mobileDeepLink" correct?

**Comment by mykola-mokhnach** [comment]
yes if they want to customise its execution

**Comment by mykola-mokhnach** [comment]
The patch has been merged to beta
