### ISSUE TITLE
Failed connecting to appium server with tvOS simulator

### ISSUE THREAD

**Issue by BoazWarshawsky** [appium/appium#14198]
## The problem

I have a nonconsists problem when sometimes I failed connecting to the appium server even before the test starts. 
My test runs when the `autoLaunch` flag is set to False.
My test actually failing in the remote line:
`self.driver_ = webdriver.Remote(self.appium_server_host_, self.desired_capabilities_)`

## Environment

* Appium version (or git revision) that exhibits the issue: both 1.15.1 and 1.16.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS catalina
* Node.js version (unless using Appium.app|exe): 12.16.1
* Npm or Yarn package manager: npm and yarn
* Mobile platform/version under test: tvOS
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: cli

## Details
I can tell about 2 main logs I am seeing, during the test run I am seeing this log:
`[XCUITest] xcodebuild exited with code 'null' and signal 'SIGTERM'
[XCUITest] Error: Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: Active application instance is not expected to be equal to nil
[XCUITest]     at quitAndUninstall (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:519:15)
[XCUITest]     at /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:580:11
[XCUITest]     at wrapped (/usr/local/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:35:13)
[XCUITest]     at retry (/usr/local/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:18:13)
[XCUITest]     at retryInterval (/usr/local/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:45:10)
[XCUITest]     at /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:529:7
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGTERM'`

and the appium server logs are found below

## Link to Appium logs
https://assets-secure.applicaster.com/qa/zapp_qa/manual/boaz/failed_connecting_appium_tv_os.log

## Code To Reproduce Issue [ Good To Have ]
1. connect to appium server when `autoLaunch`=False
Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

**Comment by BoazWarshawsky** [comment]
@mykola-mokhnach can you help me with that issue?

**Comment by KazuCocoa** [comment]
It reproduced. `autoLaunch: false` failed to finish the process on tvOS.
As a workaround, you can do:

1. autoLaunch with `com.apple.TVSettings` bundleId
2. Activate your target app with `activate_app('com.appfeatureapp')`

**Comment by BoazWarshawsky** [comment]
Thanks for answering, but I am not sure I understand #1:` autoLaunch with com.apple.TVSettings bundleId`
sorry, what do you mean?

**Comment by KazuCocoa** [comment]
autoLaunch: true and specify the settings bundle ID as bundleId

**Comment by BoazWarshawsky** [comment]
@KazuCocoa, But that is my whole idea that I am trying to do, 
I do not want to autoLaunch the app, I want to launch it when calling `activate_app` only.
In addition, I do have in my desired_capabilities the `bundleId` value set correctly.

**Comment by KazuCocoa** [comment]
Then, no workaround for now.

My suggestion was launching a system app instead of your the all under test to finish the create session. Then, you can launch your test target with active_app.

**Comment by mykola-mokhnach** [comment]
^ Or use the most recent server version

**Comment by BoazWarshawsky** [comment]
I tried with appium 1.17.0 but fortunately was not able to launch the app, 
can you tell what are the expected `desired_capabilities` for tvOS, when I was following http://appium.io/docs/en/writing-running-appium/ios/ios-tvos/ it did not work.

**Comment by KazuCocoa** [comment]
autoLaunch: false does not work even 1.17 for now

**Comment by mykola-mokhnach** [comment]
@KazuCocoa It makes sense to not provide neither bundleId nor to set autoLaunch.

**Comment by BoazWarshawsky** [comment]
**@KazuCocoa can you confirm that `autoLaunch: false`is not working currently for `tvOS` but does for `iOS`, I can confirm that I did not see issues in my CI with `iOS`.**

In addition, I can tell that having retries in connecting sometimes works for `tvOS` but it's defiantly not reliable. sometimes it works with 5 reties and sometimes it does not.

**Comment by mykola-mokhnach** [comment]
It also makes sense to enable device/xcodebuild logs. WDA does log the list of currently active apps

**Comment by KazuCocoa** [comment]
Started to take a look
https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/FBApplication.m#L130 returned `nil` in tvOS case in `return FBResponseWithObject(FBSessionCommands.sessionInformation);` at the end of `handleCreateSession`

---

> can you confirm that autoLaunch: falseis not working currently for tvOS

It only for tvOS.

> but it's defiantly not reliable.

It depends on what happened in your environment. If the cause was XCTest framework side, only Apple can improve the stability.

**Comment by BoazWarshawsky** [comment]
Thanks @KazuCocoa.

**Comment by mykola-mokhnach** [comment]
@KazuCocoa Could you please try if the patch https://github.com/appium/WebDriverAgent/pull/318 resolves the issue?

**Comment by KazuCocoa** [comment]
https://github.com/appium/WebDriverAgent/pull/318 is in the latest `appium@beta` cc @BoazWarshawsky 

`autoLaunch: false` passed
https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=9141&view=logs&j=5b05e4cb-1b9e-5cec-ae67-62a6adb04306&t=7ac6e1f3-6e81-5a23-8df7-eee56af1c0e5

**Comment by BoazWarshawsky** [comment]
@KazuCocoa my issues is found in appium server 1.16.0 and 1.15.1 from what I checked. 

If there is a fix in a newer version then whine one? and how does the desired_capabilities should be defined for tvOS with appium 1.17.0 and on?

**Comment by KazuCocoa** [comment]
We don't provide patches to lower versions. You can use it with `appium@beta` for now.
https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=9141&view=logs&j=5b05e4cb-1b9e-5cec-ae67-62a6adb04306&t=7ac6e1f3-6e81-5a23-8df7-eee56af1c0e5 is an example.
