### ISSUE TITLE
[BUG] Failed to create snapshot when rendered HTML have pseudo elements in XCode 11.

### ISSUE THREAD

**Issue by kimjg** [appium/appium#14194]
## The problem

Hi.
We are doing an integrated test of the mobile device well using the features you provided. First of all, thank you for this.

We found an issue with Xcode 11.
The problem is below.

Due to some pseudo elements rendered in the WKWebView on iOS built in Xcode 11, it seems that there is an error creating a snapshot.
(rf: pseudo elements: https://www.w3schools.com/css/css_pseudo_elements.asp)

The pseudo elements identified as having problems are **:: after, :: before.**
If the elements are included in the rendered html, snapshot creation fails.
We are temporarily building via Xcode 10, but we hope to fix the problem as soon as possible. Thank you.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS Mojave 10.14.6
* Node.js version (unless using Appium.app|exe): 6.9.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Xcode 11.3.1 / iOS 13.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

Cannot take the snapshot of Window after 15 seconds
2020-04-17 14:01:43.511077+0900 WebDriverAgentRunner-Runner[5069:1155365] Internal error: Error Domain=com.apple.dt.xctest.automation-support.error Code=5 "Error kAXErrorIPCTimeout getting snapshot for element <AXUIElementRef 0x100d5ac40> {pid=5028} {uid=[ID:9999 hash:0x6de2ed5000000000]}" UserInfo={NSLocalizedDescription=Error kAXErrorIPCTimeout getting snapshot for element <AXUIElementRef 0x100d5ac40> {pid=5028} {uid=[ID:9999 hash:0x6de2ed5000000000]}}

## Code To Reproduce Issue [ Good To Have ]

It is returned as an error in the reply block of the code.

https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Categories/XCUIElement%2BFBUtilities.m#L123

**Comment by mykola-mokhnach** [comment]
Unfortunately the snapshotting error itself is thrown by xctest. We cannot do nothing about it. However, it is possible to tune some snapshotting parameters (like `snapshotTimeout` or `snapshotMaxDepth`), which could make snapshotting possible. See 
- https://github.com/appium/appium/issues/13967
- https://github.com/appium/appium/issues/13595

Also, please try it with appium@beta, so we know the most recent fixes are included

**Comment by mykola-mokhnach** [comment]
@kimjg Please share which solution helper in your case, so other people would know what to do

**Comment by kimjg** [comment]
@mykola-mokhnach 
I haven't solved this yet.
Since you said it was a problem with XCTest, so I think I should wait until Apple fixes it.

Should I close the issue after it is resolved?

If so, find out how to fix the issue, or close it later when the modified version is applied to appium@beta you mentioned. :)

**Comment by mykola-mokhnach** [comment]
> Since you said it was a problem with XCTest, so I think I should wait until Apple fixes it.

You would probably have to wait forever :(

Try the apply the workarounds above and let us know if it worked. Also, investigate the resulting device logs. Usually XCTest writes a lot of useful debug info there.

**Comment by kimjg** [comment]
@mykola-mokhnach 
I understand what you said.
I've already applied what you suggested before creating an issue.

However, it is not a snapshotTimeout problem, but a parsing error.
Adjusting the snapshotMaxDepth wasn't what I wanted, because it was processed just before the Depth containing pseudo elements. I want a snapshot containing all elements.

And appium@beta has already tried, but it same too.
As you said, because it is a problem with XCTest, I judged that there is nothing more to check, so I answered it as above.

Thanks for the quick answer, and finally I'll do what you suggested.

> Also, investigate the resulting device logs. Usually XCTest writes a lot of useful debug info there.

But.... I am already figuring out the cause of this issue (it's caused by pseudo elements parsing error). After all, I think it's a problem Apple needs to fix, and I want to send an email to Apple. 

What do you think?

**Comment by mykola-mokhnach** [comment]
Have you tried to exclude the visibility attribute from the snapshot like it is stated in one of the linked issues?

**Comment by mykola-mokhnach** [comment]
Closed because of no response
