### ISSUE TITLE
Value set with SendKeys is not reatined on IOS web view

### ISSUE THREAD

**Issue by githubdhina** [appium/appium#14199]
## The problem

Value set with SendKeys is not reatined on IOS web view

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS Catalina
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: IOS 13.0.
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Details
Running tests on IOS real device with webview
When setting value using sendkeys, the value is shown on UI. However, after submitting the form, the value is not retained on the text box.

## Code To Reproduce Issue [ Good To Have ]

Capabilities:
            dc.AddAdditionalCapability("automationName", "XCUITest");
            dc.AddAdditionalCapability("platformName", "iOS");
            dc.AddAdditionalCapability("platformVersion", "13.0");
            dc.AddAdditionalCapability("deviceName", "iPhone");
            dc.AddAdditionalCapability("udid", appConfigReader.IOSDeviceID);
            dc.AddAdditionalCapability("app", appConfigReader.AppPath);
            dc.AddAdditionalCapability("noReset", appConfigReader.NoRestFlag);
            dc.AddAdditionalCapability("fullReset", appConfigReader.FullResetFlag);
            dc.AddAdditionalCapability("startIWDP", true);
            dc.AddAdditionalCapability("newCommandTimeout", 50000);
            dc.AddAdditionalCapability("autoWebview", true);
            dc.AddAdditionalCapability("webkitResponseTimeout", 30000);
            dc.AddAdditionalCapability("clearSystemFiles", false);

Code:
 IWebElement TextBox = MobDriverProvider.MobDriver.FindElement(By.Id(WTA_Pages.Controls.TextControl1));
                TextBox.SendKeys("Test");

The value was reatined after manually triggering the onchange event using 

IJavaScriptExecutor executor = (IJavaScriptExecutor)MobDriverProvider.MobDriver;
                executor.ExecuteScript($"arguments[0].dispatchEvent(new Event('change'));", TextBox);

**Comment by KazuCocoa** [comment]
What about using W3C actions to type text?

Send keys for WebView is https://github.com/appium/appium-remote-debugger/commits/master/atoms/type.js . Your JS also can be an alternative for the JS type, I think.
https://github.com/appium/appium-remote-debugger/blob/master/atoms/type.js

**Comment by githubdhina** [comment]
@KazuCocoa, Thanks for your response. I have no idea how to consume this. Would you mind providing mode details on how I can use this?.

**Comment by KazuCocoa** [comment]
I hadn't used Java client well, but I wondered use this action command for web context
https://www.selenium.dev/selenium/docs/api/java/org/openqa/selenium/interactions/Actions.html#sendKeys-java.lang.CharSequence...-

**Comment by shibupanda** [comment]
@KazuCocoa and @mykola-mokhnach 
The similar issue I faced and this will happen only on react based app. I fix it in our env by using native sendkeys. This is going to send keys to a focused element. We created an API which will use /setText endpoint of WDA require only one argument i.e the value we want to enter.

**Comment by KazuCocoa** [comment]
Okay, thanks.

On W3C spec, the sending keys to the focused element is replaced to W3C action.
MJSONWP is `/keys` endpoint. I think it depends on clients, but if the client had sending keys to active element API, Apium accepts it.
https://github.com/appium/ruby_lib_core/blob/master/lib/appium_lib_core/common/command/w3c.rb#L47

**Comment by shibupanda** [comment]
Thanks @KazuCocoa I was not aware thanks for the update.
In Java I guess "driver.switchTo().activeElement().sendKeys("Hello");" can use full in this case.
Please correct me if I am wrong.

**Comment by KazuCocoa** [comment]
I haven't used Java well, but it seems good (by the naming)

**Comment by shibupanda** [comment]
looks like I need to stick to my API built using https://github.com/appium/WebDriverAgent/blob/380ef5912f17056bf132092f02478d308bbba970/WebDriverAgentLib/Commands/FBElementCommands.m#L90 for time being as driver.switchTo().activeElement().sendKeys("Hello"); didn't work it's still clear the text box after any action I performed.

I am looking for same if appium already have this.

**Comment by dpburgess** [comment]
Yes I am having this issue when using webdriverio v6.1.17 with browserstack on a react application.

**Comment by shanemc1996** [comment]
Hi, 

I too am having this issue with a maven project using:

io.appium
Java-client
7.3.0 

Does anyone have any workarounds / suggestions? This is a major blocker for me.

Thanks in advance

**Comment by helenren** [comment]
Hit the same issue on java-cleint 7.3.0 and appium 1.17 on ios simulator as well.

**Comment by bwomsm1** [comment]
Hi @KazuCocoa, I am facing the same issue,
I am running a test with iOS real device and my tested application is hybrid `ionic` app.
In general I am able to enter text to `XCUIElementTypeTextField` with no problem, my issues begin with password elements from type `XCUIElementTypeSecureTextField`.

This is what I have being trying (Python syntax):

- `ActionChains(self.__driver).send_keys_to_element(element, text).perform()`
- `ActionChains(self.__driver).move_to_element(element).send_keys(text).perform()`
- `ActionChains(self.__driver).send_keys(text).perform()`, I called this after performing `element.click()`
- `element.send_keys(text)`

Do we have a solution for this?

Thanks!

**Comment by KazuCocoa** [comment]
Note:
It seems good in https://github.com/appium/appium/issues/15647

**Comment by bwomsm1** [comment]
> Note:
> It seems good in #15647

Agree, I solved it as described in: https://github.com/appium/appium/issues/15647

**Comment by mykola-mokhnach** [comment]
Closed as reolved

**Comment by jacksonwen001** [comment]
Here is my solution:
```java
 public void type(String value) {
        ((IOSDriver)driver).setKeyboardAutocorrection(true);
        final KeyInput keyboard = new KeyInput("keyboard");
        Sequence sequence = new Sequence(keyboard, 0);
        for (int i = 0; i < value.length(); i++) {
            char key = value.charAt(i);
            sequence.addAction(keyboard.createKeyDown(key))
                .addAction(keyboard.createKeyUp(key));
        }
        List<?> actions = ImmutableList.of(sequence.toJson());
        logger.info("keyboard: {} ", sequence.toJson());
        ((IOSDriver) driver).execute("actions", ImmutableMap.of("actions", actions));
    }
```
hope it can work for u. BTW, you should click the element first. if can't work. try fullRest() when u start the driver.
