### ISSUE TITLE
Question: Does appium support reactJS Expo iOS app?

### ISSUE THREAD

**Issue by gsai0205** [appium/appium#14192]
## The problem

Unable to install the app in real device iOS device using appium desktop app

## Environment

* Appium version (or git revision) that exhibits the issue: v1.16
* Desktop OS/version used to run Appium: v1.15.1
* Mobile platform/version under test: iPhone X
* Real device or emulator/simulator: Real Device

## Details

Unable to launch the reactJS iOS app neither on real nor simulator device. Issue is with only iOS app which is build using Expo(https://expo.io/)
Android app which is build using Expo works fine both in real device and simulator.

## Link to Appium logs

[Appium] Welcome to Appium v1.15.1
[Appium] Non-default server args:
[Appium]   allowInsecure: {
[Appium]   }
[Appium]   denyInsecure: {
[Appium]   }
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/sessions
[HTTP] {}
[GENERIC] Calling AppiumDriver.getSessions() with args: []
[GENERIC] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 5 ms - 40
[HTTP] 
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"/Users/imsaikrish/Downloads/CareSmart_1.0.17.ipa","automationName":"XCUITest","bundleID":"com.quintech.mpers","deviceName":"iPhone X","platformName":"IOS","platformVersion":"13.3","showIOSLog":false,"udid":"db7ca8adb11e834dca5f6e595efb97a502f30d15","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/imsaikrish/Downloads/CareSmart_1.0.17.ipa","automationName":"XCUITest","bundleID":"com.quintech.mpers","deviceName":"iPhone X","platformName":"IOS","platformVersion":"13.3","showIOSLog":false,"udid":"db7ca8adb11e834dca5f6e595efb97a502f30d15","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1587075580701 (15:19:40 GMT-0700 (PDT))
[Appium] Appium v1.15.1 creating new XCUITestDriver (v2.133.1) session
[BaseDriver] Creating session with MJSONWP desired capabilities: {
[BaseDriver]   "app": "/Users/imsaikrish/Downloads/CareSmart_1.0.17.ipa",
[BaseDriver]   "automationName": "XCUITest",
[BaseDriver]   "bundleID": "com.quintech.mpers",
[BaseDriver]   "deviceName": "iPhone X",
[BaseDriver]   "platformName": "IOS",
[BaseDriver]   "platformVersion": "13.3",
[BaseDriver]   "showIOSLog": false,
[BaseDriver]   "udid": "db7ca8adb11e834dca5f6e595efb97a502f30d15",
[BaseDriver]   "newCommandTimeout": 0,
[BaseDriver]   "connectHardwareKeyboard": true
[BaseDriver] }
[BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[BaseDriver]   bundleID
[BaseDriver] Session created with session id: 6d407a28-e1c6-46f4-85d6-abf6672c9ff5
[XCUITest] Current user: 'imsaikrish'
[XCUITest] Available devices: db7ca8adb11e834dca5f6e595efb97a502f30d15
[XCUITest] Creating iDevice object with udid 'db7ca8adb11e834dca5f6e595efb97a502f30d15'
[XCUITest] Determining device to run tests on: udid: 'db7ca8adb11e834dca5f6e595efb97a502f30d15', real device: true
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1587075581690 (15:19:41 GMT-0700 (PDT))
[BaseDriver] Using local app '/Users/imsaikrish/Downloads/CareSmart_1.0.17.ipa'
[BaseDriver] Unzipping '/Users/imsaikrish/Downloads/CareSmart_1.0.17.ipa'
[BaseDriver] Extracted 647 item(s) from '/Users/imsaikrish/Downloads/CareSmart_1.0.17.ipa'
[BaseDriver] Matched 646 item(s) in the extracted archive. Assuming 'Payload/ExpoKitApp.app' is the correct bundle
[BaseDriver] Unzipped local app to '/var/folders/k2/lxt6n2yd3330ntjzzjkf8chw0000gn/T/2020316-17824-1et8yfz.8aic/Payload/ExpoKitApp.app'
[BaseDriver] Event 'appConfigured' logged at 1587075583904 (15:19:43 GMT-0700 (PDT))
[XCUITest] Checking whether app '/var/folders/k2/lxt6n2yd3330ntjzzjkf8chw0000gn/T/2020316-17824-1et8yfz.8aic/Payload/ExpoKitApp.app' is actually present on file system
[XCUITest] App is present
[iOS] Getting bundle ID from app '/var/folders/k2/lxt6n2yd3330ntjzzjkf8chw0000gn/T/2020316-17824-1et8yfz.8aic/Payload/ExpoKitApp.app': 'com.quintech.mpers'
[BaseDriver] Event 'resetStarted' logged at 1587075583910 (15:19:43 GMT-0700 (PDT))
[XCUITest] Reset: running ios real device reset flow
[BaseDriver] Event 'resetComplete' logged at 1587075583911 (15:19:43 GMT-0700 (PDT))
[BaseDriver] Event 'logCaptureStarted' logged at 1587075584154 (15:19:44 GMT-0700 (PDT))
[XCUITest] Setting up real device
[XCUITest] Verifying application platform
[XCUITest] CFBundleSupportedPlatforms: ["iPhoneOS"]
[XCUITest] Installing '/var/folders/k2/lxt6n2yd3330ntjzzjkf8chw0000gn/T/2020316-17824-1et8yfz.8aic/Payload/ExpoKitApp.app' on device with UUID 'db7ca8adb11e834dca5f6e595efb97a502f30d15'...
[XCUITest] Pushed the app files successfully after 8658ms
[XCUITest] Error was thrown during the installation process
[XCUITest] Error: Unexpected data: {"Error":"ApplicationVerificationFailed","ErrorDetail":-1,"ErrorDescription":"Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.Eq78bZ/extracted/ExpoKitApp.app : 0xe8008015 (A valid provisioning profile for this executable was not found.)"}
[XCUITest]     at InstallationProxyService._isFinished (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-ios-device/lib/installation-proxy/index.js:132:13)
[XCUITest]     at InstallationProxyService._isFinished [as _waitMessageCompletion] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-ios-device/lib/installation-proxy/index.js:124:16)
[XCUITest] Error: Could not install app: 'Unexpected data: {"Error":"ApplicationVerificationFailed","ErrorDetail":-1,"ErrorDescription":"Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.Eq78bZ/extracted/ExpoKitApp.app : 0xe8008015 (A valid provisioning profile for this executable was not found.)"}'
[XCUITest]     at IOSDeploy.install (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/ios-deploy.js:41:13)
[DevCon Factory] Releasing connections for db7ca8adb11e834dca5f6e595efb97a502f30d15 device on any port number
[DevCon Factory] No cached connections have been found
[BaseDriver] Event 'newSessionStarted' logged at 1587075594037 (15:19:54 GMT-0700 (PDT))
[MJSONWP] Encountered internal error running command: Error: Could not install app: 'Unexpected data: {"Error":"ApplicationVerificationFailed","ErrorDetail":-1,"ErrorDescription":"Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.Eq78bZ/extracted/ExpoKitApp.app : 0xe8008015 (A valid provisioning profile for this executable was not found.)"}'
[MJSONWP]     at IOSDeploy.install (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/ios-deploy.js:41:13)
[HTTP] <-- POST /wd/hub/session 500 13338 ms - 490
[HTTP] 
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 3 ms - 57
[HTTP] 

## Code To Reproduce Issue

{
  "automationName": "XCUITest",
  "platformName": "IOS",
  "app": "/Users/imsaikrish/Downloads/CareSmart_1.0.17.ipa",
  "deviceName": "iPhone X",
  "platformVersion": "13.3",
  "udid": "db7ca8adb11e834dca5f6e595efb97a502f30d15",
  "bundleID": "com.quintech.mpers",
  "showIOSLog": false
}

**Comment by KazuCocoa** [comment]
> [XCUITest] Error: Unexpected data: {"Error":"ApplicationVerificationFailed","ErrorDetail":-1,"ErrorDescription":"Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.Eq78bZ/extracted/ExpoKitApp.app : 0xe8008015 (A valid provisioning profile for this executable was not found.)"}

I'm not familiar with Expo framework, but the error message means your build module has a wrong signature. (The message generally comes from xcodebuild or XCTest framework by Apple.)

**Comment by KazuCocoa** [comment]
You could ask the question in http://discuss.appium.io/

**Comment by mykola-mokhnach** [comment]
Only apps signed by a valid developer signature could be used for testing on real devices
