### ISSUE TITLE
Unable to launch the iOS app in Iphone Simulator using Appium Desktop

### ISSUE THREAD

**Issue by gsai0205** [appium/appium#14191]
## The problem

Unable to launch the app using Appium desktop in IPhone Simulator. 

## Environment

* Appium version (or git revision) that exhibits the issue: v1.15.1
* Desktop OS/version used to run Appium: Mojave 10.14.6
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: Iphone 8 with Ios version 13.3
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe:

## Details

I could see the app is installed but app crashes immediately before it starts

## Link to Appium logs

[HTTP] {"desiredCapabilities":{"app":"/Users/imsaikrish/Downloads/CareSmart_1.0.17.ipa","automationName":"XCUITest","deviceName":"iPhone 8","platformName":"IOS","platformVersion":"13.3","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/imsaikrish/Downloads/CareSmart_1.0.17.ipa","automationName":"XCUITest","deviceName":"iPhone 8","platformName":"IOS","platformVersion":"13.3","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1587061085330 (11:18:05 GMT-0700 (PDT))
[Appium] Appium v1.15.1 creating new XCUITestDriver (v2.133.1) session
[BaseDriver] Creating session with MJSONWP desired capabilities: {
[BaseDriver]   "app": "/Users/imsaikrish/Downloads/CareSmart_1.0.17.ipa",
[BaseDriver]   "automationName": "XCUITest",
[BaseDriver]   "deviceName": "iPhone 8",
[BaseDriver]   "platformName": "IOS",
[BaseDriver]   "platformVersion": "13.3",
[BaseDriver]   "newCommandTimeout": 0,
[BaseDriver]   "connectHardwareKeyboard": true
[BaseDriver] }
[BaseDriver] Session created with session id: 46bb14a5-cf44-4616-bdc8-8cd4569c6fb4
[XCUITest] Current user: 'imsaikrish'
[XCUITest] iOS SDK Version set to '13.2'
[iOSSim] Constructing iOS simulator for Xcode version 11.3.1 with udid 'FF5EF6C3-200C-4EAC-AA1A-44E1C7042594'
[XCUITest] Determining device to run tests on: udid: 'FF5EF6C3-200C-4EAC-AA1A-44E1C7042594', real device: false
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1587061086646 (11:18:06 GMT-0700 (PDT))
[BaseDriver] Using local app '/Users/imsaikrish/Downloads/CareSmart_1.0.17.ipa'
[BaseDriver] Unzipping '/Users/imsaikrish/Downloads/CareSmart_1.0.17.ipa'
[BaseDriver] Extracted 647 item(s) from '/Users/imsaikrish/Downloads/CareSmart_1.0.17.ipa'
[BaseDriver] Matched 646 item(s) in the extracted archive. Assuming 'Payload/ExpoKitApp.app' is the correct bundle
[BaseDriver] Unzipped local app to '/var/folders/k2/lxt6n2yd3330ntjzzjkf8chw0000gn/T/2020316-7678-17dujgr.e26n/Payload/ExpoKitApp.app'
[BaseDriver] Event 'appConfigured' logged at 1587061088786 (11:18:08 GMT-0700 (PDT))
[XCUITest] Checking whether app '/var/folders/k2/lxt6n2yd3330ntjzzjkf8chw0000gn/T/2020316-7678-17dujgr.e26n/Payload/ExpoKitApp.app' is actually present on file system
[XCUITest] App is present
[iOS] Getting bundle ID from app '/var/folders/k2/lxt6n2yd3330ntjzzjkf8chw0000gn/T/2020316-7678-17dujgr.e26n/Payload/ExpoKitApp.app': 'com.quintech.mpers'
[BaseDriver] Event 'resetStarted' logged at 1587061088793 (11:18:08 GMT-0700 (PDT))
[XCUITest] Not scrubbing third party app in anticipation of uninstall
[BaseDriver] Event 'resetComplete' logged at 1587061089080 (11:18:09 GMT-0700 (PDT))
[IOSSimulatorLog] Starting log capture for iOS Simulator with udid 'FF5EF6C3-200C-4EAC-AA1A-44E1C7042594', using 'xcrun simctl spawn FF5EF6C3-200C-4EAC-AA1A-44E1C7042594 log stream --style compact'
[BaseDriver] Event 'logCaptureStarted' logged at 1587061089435 (11:18:09 GMT-0700 (PDT))
[XCUITest] Setting up simulator
[iOS] No reason to set locale
[iOS] No iOS / app preferences to set
[iOS] Setting did not need to be updated
[iOSSim] Setting preferences of FF5EF6C3-200C-4EAC-AA1A-44E1C7042594 Simulator to {"ConnectHardwareKeyboard":true}
[iOSSim] Setting common Simulator preferences to {"RotateWindowWhenSignaledByGuest":true,"ConnectHardwareKeyboard":true}
[iOSSim] Updated FF5EF6C3-200C-4EAC-AA1A-44E1C7042594 Simulator preferences at '/Users/imsaikrish/Library/Preferences/com.apple.iphonesimulator.plist' with {"DevicePreferences":{"FF5EF6C3-200C-4EAC-AA1A-44E1C7042594":{"ConnectHardwareKeyboard":true}},"RotateWindowWhenSignaledByGuest":true,"ConnectHardwareKeyboard":true}
[iOSSim] Got Simulator UI client PID: 1530
[iOSSim] Both Simulator with UDID FF5EF6C3-200C-4EAC-AA1A-44E1C7042594 and the UI client are currently running
[IDB] Connecting idb service to 'FF5EF6C3-200C-4EAC-AA1A-44E1C7042594'
[XCUITest] idb will not be used for Simulator interaction. Original error: 'idb' has not been found in PATH. Is it installed? Read https://www.fbidb.io for more details
[BaseDriver] Event 'simStarted' logged at 1587061089645 (11:18:09 GMT-0700 (PDT))
[XCUITest] Verifying application platform
[XCUITest] CFBundleSupportedPlatforms: ["iPhoneOS"]
[XCUITest] *********************************
[XCUITest] Simulator architecture appears to be unsupported by the '/var/folders/k2/lxt6n2yd3330ntjzzjkf8chw0000gn/T/2020316-7678-17dujgr.e26n/Payload/ExpoKitApp.app' application. Make sure the correct deployment target has been selected for its compilation in Xcode.
[XCUITest] Don't be surprised if the application fails to launch.
[XCUITest] *********************************
[XCUITest] Reset requested. Removing app with id 'com.quintech.mpers' from the device
[XCUITest] Cleaning installd cache to save the disk space
[XCUITest] Installing '/var/folders/k2/lxt6n2yd3330ntjzzjkf8chw0000gn/T/2020316-7678-17dujgr.e26n/Payload/ExpoKitApp.app' on Simulator with UUID 'FF5EF6C3-200C-4EAC-AA1A-44E1C7042594'...
[XCUITest] The app has been installed successfully.
[BaseDriver] Event 'appInstalled' logged at 1587061092641 (11:18:12 GMT-0700 (PDT))
[XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-webdriveragent'
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'
[XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[DevCon Factory] Requesting connection for device FF5EF6C3-200C-4EAC-AA1A-44E1C7042594 on local port 8100, device port 8100
[DevCon Factory] Cached connections count: 0
[DevCon Factory] Successfully requested the connection for FF5EF6C3-200C-4EAC-AA1A-44E1C7042594:8100
[XCUITest] Starting WebDriverAgent initialization with the synchronization key 'XCUITestDriver'
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response with status undefined: {"code":"ESOCKETTIMEDOUT","connect":false}
[XCUITest] WDA is not listening at 'http://localhost:8100/'
[XCUITest] WDA is currently not running. There is nothing to cache
[XCUITest] Trying to start WebDriverAgent 2 times with 10000ms interval
[XCUITest] These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
[BaseDriver] Event 'wdaStartAttempted' logged at 1587061095853 (11:18:15 GMT-0700 (PDT))
[XCUITest] Launching WebDriverAgent on the device
[WebDriverAgent] Fetching dependencies
[WebDriverAgent] Dependencies up-to-date
[XCUITest] Killing running processes 'xcodebuild.*FF5EF6C3-200C-4EAC-AA1A-44E1C7042594, FF5EF6C3-200C-4EAC-AA1A-44E1C7042594.*XCTRunner' for the device FF5EF6C3-200C-4EAC-AA1A-44E1C7042594...
[XCUITest] 'pgrep -ifn xcodebuild.*FF5EF6C3-200C-4EAC-AA1A-44E1C7042594' didn't detect any matching processes. Return code: 1
[XCUITest] 'pgrep -ifn FF5EF6C3-200C-4EAC-AA1A-44E1C7042594.*XCTRunner' didn't detect any matching processes. Return code: 1
[XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=FF5EF6C3-200C-4EAC-AA1A-44E1C7042594 IPHONEOS_DEPLOYMENT_TARGET=13.3 GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-webdriveragent'
[XCUITest] Output from xcodebuild will only be logged if any errors are present there. To change this, use 'showXcodeLog' desired capability
[XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response with status undefined: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response with status undefined: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[XCUITest] Log file for xcodebuild test: /Users/imsaikrish/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz/Logs/Test/Test-WebDriverAgentRunner-2020.04.16_11-18-17--0700.xcresult/Staging/2_Test/Diagnostics/WebDriverAgentRunner-149D6625-8F74-41C7-877E-FF8289C2B4E6/WebDriverAgentRunner-C8B906E5-5209-4317-8E99-984B1EAF4338/Session-WebDriverAgentRunner-2020-04-16_111817-KzeYF8.log
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response with status undefined: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got response with status 200: {
[WD Proxy]   "value" : {
[WD Proxy]     "message" : "WebDriverAgent is ready to accept commands",
[WD Proxy]     "state" : "success",
[WD Proxy]     "os" : {
[WD Proxy]       "name" : "iOS",
[WD Proxy]       "version" : "13.3",
[WD Proxy]       "sdkVersion" : "13.0"
[WD Proxy]     },
[WD Proxy]     "ios" : {
[WD Proxy]       "simulatorVersion" : "13.3",
[WD Proxy]       "ip" : "192.168.1.99"
[WD Proxy]     },
[WD Proxy]     "ready" : true,
[WD Proxy]     "build" : {
[WD Proxy]       "upgradedAt" : "1583307069932",
[WD Proxy]       "time" : "Apr 16 2020 09:57:11",
[WD Proxy]       "productBundleIdentifier" : "com.facebook.WebDriverAgentRunner"
[WD Proxy]     }
[WD Proxy]   },
[WD Proxy]   "sessionId" : "0DE785D0-9FA1-46A0-BDEA-A02E43AB6FE3"
[WD Proxy] }
[XCUITest] WebDriverAgent information:
[XCUITest] {
[XCUITest]   "message": "WebDriverAgent is ready to accept commands",
[XCUITest]   "state": "success",
[XCUITest]   "os": {
[XCUITest]     "name": "iOS",
[XCUITest]     "version": "13.3",
[XCUITest]     "sdkVersion": "13.0"
[XCUITest]   },
[XCUITest]   "ios": {
[XCUITest]     "simulatorVersion": "13.3",
[XCUITest]     "ip": "192.168.1.99"
[XCUITest]   },
[XCUITest]   "ready": true,
[XCUITest]   "build": {
[XCUITest]     "upgradedAt": "1583307069932",
[XCUITest]     "time": "Apr 16 2020 09:57:11",
[XCUITest]     "productBundleIdentifier": "com.facebook.WebDriverAgentRunner"
[XCUITest]   }
[XCUITest] }
[XCUITest] WebDriverAgent successfully started after 3628ms
[BaseDriver] Event 'wdaSessionAttempted' logged at 1587061099734 (11:18:19 GMT-0700 (PDT))
[XCUITest] Sending createSession command to WDA
[WD Proxy] Matched '/session' to command name 'createSession'
[WD Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.quintech.mpers","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}

## Code To Reproduce Issue [ Good To Have ]

{
  "automationName": "XCUITest",
  "platformName": "IOS",
  "app": "/Users/imsaikrish/Downloads/CareSmart_1.0.17.ipa",
  "deviceName": "iPhone 8",
  "platformVersion": "13.3"
}

**Comment by mykola-mokhnach** [comment]
> [XCUITest] Simulator architecture appears to be unsupported by the '/var/folders/k2/lxt6n2yd3330ntjzzjkf8chw0000gn/T/2020316-7678-17dujgr.e26n/Payload/ExpoKitApp.app' application. Make sure the correct deployment target has been selected for its compilation in Xcode.
> [XCUITest] Don't be surprised if the application fails to launch.

Closed as not an issue
