### ISSUE TITLE
Cannot start the 'com.useless.counter' application

### ISSUE THREAD

**Issue by DeLuca92** [appium/appium#14205]
Hello, I have this problem.
I don't know How fix this.
All my environment is okay.
I'm using windows.
I'm try open a simple app "Click Counter"
And I'm using the appium aplication for testing to after many a code.
Someone Know how fix this? 
i'm testing in real device.
Appium log : https://pastebin.com/KigF3naw
PS: I tried open a contacts app and works, instagram too
{
  "deviceName": "Lenovo TB-8504F",
  "udid": "HGAH5LL2",
  "platformName": "Android",
  "plataformVersion": "7.1.1",
  "appPackage": "com.useless.counter",
  "appActivity": "com.useless.counter.CounterActivity"
}

An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.useless.counter' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\danie\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s HGAH5LL2 shell am start -W -n com.useless.counter/com.useless.counter.CounterActivity -S' exited with code 1'; Stderr: 'java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=com.useless.counter/.CounterActivity } from null (pid=7990, uid=2000) not exported from uid 10227
 at android.os.Parcel.readException(Parcel.java:1684)
 at android.os.Parcel.readException(Parcel.java:1637)
 at android.app.ActivityManagerProxy.startActivityAndWait(ActivityManagerNative.java:3231)
 at com.android.commands.am.Am.runStart(Am.java:630)
 at com.android.commands.am.Am.onRun(Am.java:388)
 at com.android.internal.os.BaseCommand.run(BaseCommand.java:51)
 at com.android.commands.am.Am.main(Am.java:121)
 at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
 at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)'; Code: '1'

**Comment by KazuCocoa** [comment]
It failed in `C:\Users\danie\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s HGAH5LL2 shell am start -W -n com.useless.counter/com.useless.counter.CounterActivity -S`.
It means the activity does not allow to launch directly by adb command.
Were you able to launch the activity without errors?

**Comment by mykola-mokhnach** [comment]
Have you read the troubleshooting document from the error message above?

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by DeLuca92** [comment]
I discover the problem.
Is the app 
LOL
