### ISSUE TITLE
Cannot find proxy with ID

### ISSUE THREAD

**Issue by ivantay2003** [appium/appium#14200]
## The problem

I have been trying to register appium CLI with selenium grid but it is not working. I have this error: Grid registration error: Cannot find proxy with ID 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.0
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Mac OS X Catalina 10.15.4
* Node.js version (unless using Appium.app|exe): 12.11.1
* Npm or Yarn package manager: 6.14.4
* Mobile platform/version under test: 12.4.5
* Real device or emulator/simulator: Real (does not matter)
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

Tried to register appium with selenium grid but it is not working. I have tested out on selenium with selenium grid and it is working fine. 

I have look at https://github.com/appium/appium/issues/7202. However, it does not help to resolve the issue.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!
Appium log
https://gist.github.com/ivantay2003/f8f3fac52f226a769f2a67914747fb18

Appium node json 
https://gist.github.com/ivantay2003/7677c1256579694e37dec2da43dfdb7f

On Selenium grid , it will show this "WARN [DefaultGridRegistry.removeIfPresent] - Cleaning up stale test sessions on the unregistered node http://0.0.0.0.4722

## Code To Reproduce Issue [ Good To Have ]
1. Have the above json file in your machine
2. appium --port 4722 --nodeconfig config_ios.json

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.
No code . It is just executing Appium .

I like to find out if it is possible to force appium to point to http://192.1.1.2:4722 instead of http://0.0.0.0.4722 . http://0.0.0.0.4722 is invalid.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

No code needed in here. Just execute appium.

**Comment by mykola-mokhnach** [comment]
Try https://discuss.appium.io/t/need-steps-how-to-parallel-appium-on-real-devices-ios/10132/5

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
