### ISSUE TITLE
Receiving adbExec timed out error after a successful run

### ISSUE THREAD

**Issue by QAthulhu** [appium/appium#14201]
## The problem

I am able to successfully run my tests once. But running the tests again causes an adbExec error and the only way to fix it is by doing adk kill-server and adb start-server or disconnecting and reconnecting my device. At which point I can get a successful run again and then run into the same error after. 

However, when I run a single test, it works fine all the time. It's only when running the entire suite or the entire class that I get the timeout error.

The error message:
`Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error getting device API level. Original error: Error executing adbExec. Original error: 'Command '/Users/[my name]/Library/Android/sdk/platform-tools/adb -P 5037 -s c992c6c9 shell getprop ro.build.version.sdk' timed out after 60000ms'`

I already increased the timeout to 60 seconds but it still times out. I tried executing the command in my terminal and it never completes; I enter it and then it never finishes. Upon using kill-server, it works again for any number of times. So there's something happening in my test run that causes the command to stop working.
## Environment

* Appium version: 1.16.0
* Desktop OS/version used to run Appium: MacOS Mojave
* Node.js version (unless using Appium.app|exe): 6.11.3
* Npm or Yarn package manager: Homebrew
* Mobile platform/version under test: Android 9
* Real device or emulator/simulator: Samsung J8
* Appium CLI: Not sure how to get this. Using Appium from terminal

## Details
Unlike the other issues posted, I have a work around for this which is just killing and starting the adb server or disconnecting my device. 

- Run tests on by one using maven `mvn -Dtest=TestClassTests#TestMethod test`: test always passes

- Run tests as a group `mvn -Dtest=TestClassTests test` works the first time. Subsequent runs display the timeout error. Killing and starting the adb server allows another passed run, but all following runs will fail again

I also get this error randomly in the middle of the run. It has appeared at many different lines of code so it doesn't seem tied to any operation:
`Original error: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT`
After this happens, all subsequent test cases and test runs will display the same adbExec error as before
## Link to Appium logs

https://gist.github.com/QAthulhu/9b152f6dc528c0900ab7e56fc81a9c40

## Code To Reproduce Issue [ Good To Have ]
Test fails as soon as I run it. I use maven 

Desired Capabilities:
```
capabilities = new DesiredCapabilities();
		capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, platformName);
		capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, deviceName);
		capabilities.setCapability(MobileCapabilityType.APP, app);
		capabilities.setCapability(MobileCapabilityType.NO_RESET, false);
		capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, automationName);
		capabilities.setCapability(AndroidMobileCapabilityType.ADB_EXEC_TIMEOUT, 60000);
```
I have already included driver.quit() in my @AfterClass method.

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing we could do from Appium side, since this looks like an adb/phone issue. I'd make sure the Android SDK is up to date or replace the device under test

**Comment by QAthulhu** [comment]
Thank you, I'll update and see if I run into this issue again tomorrow

**Comment by QAthulhu** [comment]
Updated my android studio, and now my tests immediately failed upon running. All from a socket hang up. Is this just a device issue?

**Comment by mykola-mokhnach** [comment]
Yes, most likely it is

**Comment by QAthulhu** [comment]
Ok thank you!
