### ISSUE TITLE
Appium version - 1.17, getting error message as "The operation is Insecure error message" while executing  on iOS device 

### ISSUE THREAD

**Issue by anshu1987** [appium/appium#14208]
I have recently upgraded my appium version to v1.17.1-beta.0, test are running fine on android device but while executing on iOS device getting error message "The operation is Insecure"

## Environment

* Appium version (or git revision) that exhibits the issue:  v1.17.1-beta.0
* Last Appium version that did not exhibit the issue (if applicable):1.15
* Desktop OS/version used to run Appium:   macOS Mojave / 10.14.4
* Node.js version (unless using Appium.app|exe): v10.16.3
* Npm or Yarn package manager: c
* Real device or emulator/simulator: Real device iOS 12.4
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

[debug] [XCUITest] Executing command 'execute'
[debug] [RemoteDebugger] Executing atom 'execute_script'
[debug] [RemoteDebugger] Executing 'execute_script' atom in default context
[debug] [RemoteDebugger] Sending javascript command: '(function(){return function(){var f=this;
[debug] [RemoteDebugger] funct...'
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:355', page '1', target 'page-1' (id: 42): 'Runtime.evaluate'
[debug] [RemoteDebugger] Received data response from send (id: 42): '{"status":18,"value":{"message":"The operation is insecure."}}'
[debug] [RemoteDebugger] Sending to Web Inspector took 11ms
[debug] [MJSONWP] Matched JSONWP error code 18 to UnknownError
[debug] [XCUITest] Error received while executing atom: An unknown server-side error occurred while processing the command. Original error: The operation is insecure.
[debug] [W3C (aaf642bf)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: The operation is insecure.
[debug] [W3C (aaf642bf)]     at errorFromMJSONWPStatusCode (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:767:10)
[debug] [W3C (aaf642bf)]     at convertResult (/usr/local/lib/node_modules/appium/node_modules/appium-remote-debugger/lib/utils.js:222:11)
[debug] [W3C (aaf642bf)]     at RemoteDebuggerRealDevice.execute (/usr/local/lib/node_modules/appium/node_modules/appium-remote-debugger/lib/mixins/execute.js:118:10)
[HTTP] <-- POST /wd/hub/session/aaf642bf-6a11-4a81-927f-6da719768863/execute/sync 500 76 ms - 690
[HTTP] 

Capabilities which being used:
[debug] [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {
[debug] [BaseDriver]   "alwaysMatch": {
[debug] [BaseDriver]     "browserName": "safari",
[debug] [BaseDriver]     "browserVersion": "12.2",
[debug] [BaseDriver]     "appium:javascriptEnabled": true,
[debug] [BaseDriver]     "appium:platform": "MAC",
[debug] [BaseDriver]     "platformName": "ios",
[debug] [BaseDriver]     "appium:version": "",
[debug] [BaseDriver]     "appium:automationName": "XCUITest",
[debug] [BaseDriver]     "appium:deviceName": "iPhone",
[debug] [BaseDriver]     "appium:newCommandTimeout": 6000,
[debug] [BaseDriver]     "appium:platformVersion": "12.2",
[debug] [BaseDriver]     "appium:safariInitialUrl": "https://m.google.com",
[debug] [BaseDriver]     "appium:startIWDP": true,
[debug] [BaseDriver]     "appium:udid": "auto"
[debug] [BaseDriver]   },
[debug] [BaseDriver]   "firstMatch": [
[debug] [BaseDriver]     {}
[debug] [BaseDriver]   ]
[debug] [BaseDriver] }

**Comment by KazuCocoa** [comment]
What JS command did you send?
Potentially, the error is from Safari 
https://github.com/WebKit/webkit/blob/89c28d471fae35f1788a0f857067896a10af8974/Source/WebCore/dom/DOMException.cpp#L53

**Comment by anshu1987** [comment]
I am not sending any js command explicitly, just passing this with capabilities.setCapability(CapabilityType.javascriptEnabled, true);

**Comment by KazuCocoa** [comment]
hm, could you attach the full log as GIST?
I wondered the context especially around below.

```
[debug] [XCUITest] Executing command 'execute'
[debug] [RemoteDebugger] Executing atom 'execute_script'
[debug] [RemoteDebugger] Executing 'execute_script' atom in default context
[debug] [RemoteDebugger] Sending javascript command: '(function(){return function(){var f=this;
[debug] [RemoteDebugger] funct...'
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:355', page '1', target 'page-1' (id: 42): 'Runtime.evaluate'
[debug] [RemoteDebugger] Received data response from send (id: 42): '{"status":18,"value":{"message":"The operation is insecure."}}'
```

**Comment by anshu1987** [comment]
here it is : https://gist.github.com/anshu1987/bf90457c66f40aba21d40b4f76e82740

**Comment by KazuCocoa** [comment]
Did you call `return localStorage.clear();` in your side?
Perhaps Safari does not allow the JS method.

```
[HTTP] --> POST /wd/hub/session/5bb4d948-bafe-4b59-8721-fcdd0187b0fe/execute/sync
[HTTP] {"script":"return localStorage.clear();","args":[]}
[debug] [W3C (5bb4d948)] Calling AppiumDriver.execute() with args: ["return localStorage.clear();",[],"5bb4d948-bafe-4b59-8721-fcdd0187b0fe"]
[debug] [XCUITest] Executing command 'execute'
[debug] [RemoteDebugger] Executing atom 'execute_script'
[debug] [RemoteDebugger] Executing 'execute_script' atom in default context
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var e=this;
[debug] [RemoteDebugger] funct...
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Target.sendMessageToTarget","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"message":{"method":"Runtime.evaluate","params":{"e...
[debug] [RemoteDebugger] Webkit response timeout: 5000
[debug] [RemoteDebugger] Received WebKit data: '{"result":{},"id":4}'
[debug] [RemoteDebugger] Received receipt for message '4'
[debug] [RemoteDebugger] Received WebKit data: '{"method":"Target.dispatchMessageFromTarget","params":{"targetId":"page-1","message":"{\"result\":{\"result\":{\"type\":\"object\",\"value\":{\"status\":18,\"value\":{\"message\":\"The operation is...'
[debug] [RemoteDebugger] Found method 'Target.dispatchMessageFromTarget' for message '4'
[debug] [MJSONWP] Matched JSONWP error code 18 to UnknownError
[debug] [W3C (5bb4d948)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: The operation is insecure.
[debug] [W3C (5bb4d948)]     at errorFromMJSONWPStatusCode (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:789:10)
[debug] [W3C (5bb4d948)]     at WebKitRemoteDebugger.convertResult (/usr/local/lib/node_modules/appium/node_modules/appium-remote-debugger/lib/remote-debugger.js:700:13)
[debug] [W3C (5bb4d948)]     at WebKitRemoteDebugger.convertResult (/usr/local/lib/node_modules/appium/node_modules/appium-remote-debugger/lib/webkit-remote-debugger.js:127:18)
[debug] [W3C (5bb4d948)]     at WebKitRemoteDebugger.convertResult [as execute] (/usr/local/lib/node_modules/appium/node_modules/appium-remote-debugger/lib/remote-debugger.js:660:17)
[HTTP] <-- POST /wd/hub/session/5bb4d948-bafe-4b59-8721-fcdd0187b0fe/execute/sync 500 32 ms - 890
[HTTP] 
```

**Comment by mykola-mokhnach** [comment]
The error is thrown by Safari itself. There is nothing we can do there from Appium side.
