### ISSUE TITLE
Able to find an element using Appium desktop but not in Appium CLI

### ISSUE THREAD

**Issue by VenkateshPS** [appium/appium#14217]
## The problem

Able to find an element using Appium desktop but not in Appium CLI
## Environment

* Appium CLI: v1.15.1
    Appium Desktop: v1.15.1
* Last Appium version that did not exhibit the issue (if applicable): Don’t know
* Desktop OS/version used to run Appium: 
* Node.js version (unless using Appium.app|exe): MacOS Mojave- 10.14.5
* Npm: 6.14.4
* Mobile platform/version under test: iOS 13.3.1
* Real device or emulator/simulator: Real device-iPhone 8
* Appium CLI or Appium.app|exe: Both

## Details

Trying to click on an overlay element which appears when tap on a group icon. Attached the screenshot. Able to find and click on that element in Appium desktop but not using appium CLI
Locator xpath -//XCUIElementTypeButton[@name="join"]

## Link to Appium logs

[Appium Desktop Log]
https://gist.github.com/VenkateshPS/bed09a8c26839999aa5b7b6079a9e9d0

[Appium Server console log]
https://gist.github.com/VenkateshPS/66d0f2bb502e173867687959ce4edd22

[Driver Page Source Appium]
https://gist.github.com/VenkateshPS/f060b67028d8af03a1f0d5dc2a31b74e

[Appium Desktop Page Source]
https://gist.github.com/VenkateshPS/1b380ed3dd607868d4603da69db2d55e

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Is the element present in the page source right before the tap is performed?

**Comment by VenkateshPS** [comment]
Element is not present in the page sourre before the tap is performed.

**Comment by mykola-mokhnach** [comment]
Then it might be either a race condition issue or something is wrong with the app itself. If the element is not in page source there is no way it could be found.

**Comment by VenkateshPS** [comment]
As per my understanding element should show up in page source after tap is performed right ?

**Comment by mykola-mokhnach** [comment]
> so after tap is performed

How do you know it is performed and recognised by the app?

**Comment by VenkateshPS** [comment]
Ok, I taped using Appium Desktop on App  and noticed as shown in attached image that locators show up in xml. 

When same tap is done using Appium cli, driver.getPageSource does not have these locators. 

To me looks this looks like problem with Appium CLI. I have noticed same behaviour in other Apps too only on Appium CLI.

**Comment by KazuCocoa** [comment]
hm, AppiumDesktop also uses the same Appium CLI internally.
So, except for the client and timing, Appium desktop and CLI environment should be the same.

Appium desktop uses https://github.com/admc/wd as a webdriver client.
AD calls screenshot and page source command frequently. So, I wondered if some actions affect XCTest internal snapshot process.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by CharbelAbouAzar** [comment]
I am having same issue here, Any solution ?
