### ISSUE TITLE
UWP app not getting launched, when tests are configured to run through Jenkins

### ISSUE THREAD

**Issue by krevathi1912** [appium/appium#14215]
## Problem
Created tests for UWP, that uses WinAppdriver with appium to run the test. App is getting launched and tests are running, if i run manually. When i configure the tests to run through Jenkins job, app is not getting launche, throws 'Failed to locate opened application window with appId: ', tried giving 'createSessionTimeout' (60000 and mote) in desired capabilities, but not use, same issue persist. I am new for appium. Appreciate any help

##Environment
* Appium version: Appium v1.17.0
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe):  v12
* Npm or Yarn package manager: npm@6.14.4
* Mobile platform/version under test: UWP app running in Windows 10 system
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:  appium

## Appium logs
[GIST link  for log](https://gist.github.com/krevathi1912/859f72831786944a5d4d357dbbf33373)

**Comment by mykola-mokhnach** [comment]
Sorry, we cannot help nothing without the data required by the default issue template

**Comment by krevathi1912** [comment]
> Sorry, we cannot help nothing without the data required by the default issue template

Please let me know the provided the details are sufficient. Thanks

**Comment by mykola-mokhnach** [comment]
> 2020-04-22 08:46:12:881 - [35m[WD Proxy][39m Got response with status 500: {"status":13,"value":{"error":"unknown error","message":"Failed to locate opened application window with appId: OSII.Compass_4evby3efaaxbm!App, and processId: 10844"}}


This seems like WinAppDriver issue. This component is being maintained by Microsoft. Consider reporting the issue to their repository: https://github.com/microsoft/WinAppDriver

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing do here from Appium side. Closed as third party issue
