### ISSUE TITLE
Cannot identify context menu after using long press action in android

### ISSUE THREAD

**Issue by phongha1912** [appium/appium#14218]
## The problem

I can't identify the context menu (Paste | Select all | ⋮ ) in my app after I long press on a textbox control.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Desktop OS/version used to run Appium: MacOS 10.14.5
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Emulator Pixel_2
* Appium CLI or Appium.app|exe: Appium.app

## Details

I need to check the context menu work correctly but there is no way to identify them on Android. I also do it on iOS and the Appium desktop can identify this and I can fire event tap on the context menu.
Please help to let me know what I can do to identify this on Android.
Thanks!

**Comment by mykola-mokhnach** [comment]
It might be this menu is not part of application accessibility. You could try to enable the `enableMultiWindows` option (only available since Appium 1.17) or try to perform copy/paste using key actions as a workaround.

**Comment by phongha1912** [comment]
Hi @mykola-mokhnach,
Thank you for your support. It worked correctly.
Regards!
