### ISSUE TITLE
UiAutomator2 unable to remove port forward

### ISSUE THREAD

**Issue by dragancla** [appium/appium#14216]
## The problem

UiAutomator2 is trying to remove the port forwarding from a specific device in a device farm but it's probably passing some wrong arguments to ADB because it looks like it's not filtering through devices properly. 

## Environment

* Appium version (or git revision) that exhibits the issue: v1.17.1-beta.0 
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: MacOS 10.15.4
* Node.js version (unless using Appium.app|exe): v12.6.0
* Npm or Yarn package manager: NPM v6.14.4
* Mobile platform/version under test: Android 9
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI
* Platform Tools version: 29.0.5 

## Details

[0-0] 2020-04-22T15:30:18.032Z ERROR @wdio/runner: Error: Failed to create session.
An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/usr/local/share/android-sdk/platform-tools/adb -P 5037 -s 39V7N19122005910 forward tcp\:8204 tcp\:6790' exited with code 1'; Stderr: 'adb: error: more than one device/emulator'; Code: '1'

## Link to Appium logs

https://gist.github.com/dragancla/bd2f5a458b6636f37b1ffa2bdba26dd1

## Code To Reproduce Issue [ Good To Have ]

Impossible to provide reproducible code without exposing sensitive company data

**Comment by mykola-mokhnach** [comment]
This could only happen if connected devices have duplicated serial numbers. A possible workaround might be to change the serial number for one of them (root required) or keep them connected to different hosts: https://stackoverflow.com/questions/30214744/using-adb-with-multiple-devices-with-the-same-serial-number

**Comment by dragancla** [comment]
I'm pretty sure they don't have conflicts between them, since it was all working up until we updated appium npm modules (haven't done that since November, surprisingly little maintenence needed), so it worked decently for at least 5 months. Here's the capabilities for android devices: https://gist.github.com/dragancla/231c2d8b9ec63e06ba50fbd537ef0a16

**Comment by dragancla** [comment]
Switched to the beta Espresso driver and getting a similar issue regarding port forwarding:

[Appium] Appium v1.17.0 creating new EspressoDriver (v1.23.2) session
[BaseDriver] Session created with session id: 839a07f2-10e6-40d5-a9ab-84be3e2a7c7a
[Espresso] Unable to remove port forward 'Cannot read property 'removePortForward' of undefined'

**Comment by KazuCocoa** [comment]
Could you share your `adb devices -l` which happen the port forward error?

**Comment by dragancla** [comment]
```
2af0f691cd1c7ece       device usb:338771968X product:starltexx model:SM_G960F device:starlte transport_id:3
350442bf963ed526       device usb:338825216X product:gts3lwifixx model:SM_T820 device:gts3lwifi transport_id:1
39V7N19122005910       device usb:338763776X product:POT-LX1 model:POT_LX1 device:HWPOT-H transport_id:5
988a1b375a4156455630   device usb:338759680X product:greatltexx model:SM_N950F device:greatlte transport_id:2
QV702BES1E             device usb:338767872X product:H8266 model:H8266 device:H8266 transport_id:4
```

**Comment by KazuCocoa** [comment]
What happens with:

```
/usr/local/share/android-sdk/platform-tools/adb -P 5037 -s 39V7N19122005910 forward tcp:8204 tcp:6790
```


`Original error: 'Command '/usr/local/share/android-sdk/platform-tools/adb -P 5037 -s 39V7N19122005910 forward tcp:8204 tcp:6790' exited with code 1'; Stderr: 'adb: error: more than one device/emulator'; Code: '1'` means the adb command found more than two the same serial numbers. Not sure, but if the adb command has own cache system, restarting the adb server or the host machine will help.

**Comment by dragancla** [comment]
You might be on to something regarding the ADB. I downgraded the 29.0.5 platform tools to 29.0.0 and now I'm getting a different error:

`[BaseDriver] Session created with session id: 7e1f66d1-54e6-43be-a198-4e2a1170e7a0
[UiAutomator2] We're going to run a Chrome-based session
[UiAutomator2] Chrome-type package and activity are com.android.chrome and com.google.android.apps.chrome.Main
[UiAutomator2] Starting 'com.android.chrome' directly on the device
[ADB] Found 3 'build-tools' folders under '/usr/local/share/android-sdk' (newest first):
[ADB]     /usr/local/share/android-sdk/build-tools/29.0.0
[ADB]     /usr/local/share/android-sdk/build-tools/28.0.0
[ADB]     /usr/local/share/android-sdk/build-tools/27.0.0
[ADB] Using 'adb' from '/usr/local/share/android-sdk/platform-tools/adb'
[AndroidDriver] Retrieving device list
[AndroidDriver] Using device: QV702BES1E
[ADB] Using 'adb' from '/usr/local/share/android-sdk/platform-tools/adb'
[ADB] Getting device platform version
[UiAutomator2] Relaxing hidden api policy
[AndroidDriver] No app sent in, not parsing package/activity
[ADB] Using 'apksigner.jar' from '/usr/local/share/android-sdk/build-tools/29.0.0/lib/apksigner.jar'
[ADB] Cannot use apksigner tool for signature verification. Original error: The JAVA_HOME environment variable must be set for Android Tools to work properly
[ADB] Using 'zipalign' from '/usr/local/share/android-sdk/build-tools/29.0.0/zipalign'
[ADB] Cannot use apksigner tool for signing. Defaulting to sign.jar. Original error: The JAVA_HOME environment variable must be set for Android Tools to work properly
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
[UiAutomator2] Restoring hidden api policy to the device default configuration
[HTTP] <-- POST /wd/hub/session 500 2250 ms - 641
[HTTP] `

which kind of makes no sense to me, since other apps are using that JAVA_HOME path env var and AppiumDoctor clearly says it's set 
`info AppiumDoctor  ✔ ANDROID_HOME is set to: /usr/local/share/android-sdk
info AppiumDoctor  ✔ JAVA_HOME is set to: /Library/Java/JavaVirtualMachines/openjdk-14.jdk/Contents/Home
info AppiumDoctor  ✔ adb exists at: /usr/local/share/android-sdk/platform-tools/adb
info AppiumDoctor  ✔ android exists at: /usr/local/share/android-sdk/tools/android`

**Comment by mykola-mokhnach** [comment]
Check https://github.com/appium/java-client/blob/master/docs/environment.md to troubleshoot environment issues

**Comment by dragancla** [comment]
Reinstalled all dependencies manually, one by one, and did a clean install of Java and android-sdk and made sure everything is pointing to the correct binary. I'm back to square 1, with the "Unable to remove system port forward"

**Comment by mykola-mokhnach** [comment]
I don't see any bugs there from Appium perspective. The problem is caused by ADB itself. Sorry.

**Comment by KazuCocoa** [comment]
Yeah, as Mykola addressed, if the error was in adb command itself, `/usr/local/share/android-sdk/platform-tools/adb -P 5037 -s 39V7N19122005910 forward tcp:8204 tcp:6790`, Appium cannot resolve it, unfortunately.
If the lower tools version resolved the issue, you can try `buildToolsVersion` capability to specify `28.0.0`.

(btw, I could not reproduce the error with 29.0.3 and 28.0.3 on my local.)

**Comment by dragancla** [comment]
Alright, thanks for the help guys. You are right, it was an ADB issue, fixed it by changing the binary and hardcoding some arguments in a separate configuration file.

**Comment by Sendery** [comment]
Execute:

`
adb -s $UDID forward --remove-all
`
just before launching appium and after to ensure that the ports used by the adb are free

[see this response on stackoverflow](https://stackoverflow.com/questions/63238793/appium-error-cannot-find-any-free-port-in-range-8200-8299) or 
see [How do I stop an adb port forward?](https://stackoverflow.com/questions/17817275/how-do-i-stop-an-adb-port-forward)
