### ISSUE TITLE
Appium IOS tests are too slow

### ISSUE THREAD

**Issue by mstepanyan** [appium/appium#14211]
Dear Support Team .
We have an application(IOS - https://apps.apple.com/us/app/vlume/id1325346984, Android - https://play.google.com/store/apps/details?id=com.vlume.app), which is written in React-Native. We using also an UI Automation Tests (Appium XCUITest).
Could you please help us to understand why XCUITest has a big delay for each call from Appium side

find element 1-3min per command
click element after finding 1-2min per command
The same tests are working on Android 5 times faster
BUG - IOS UI source tree is very big and incorrect

We use:

Appium - 1.17.0
Xcode - 11.3
iOS - 13.3.1 , 12.4.4
Real devices - iPhone 7, 6s, 5s
react-native - 0.61.5
io.appium:java_client - 7.0.0(also tried 6.0.0)

**Comment by KazuCocoa** [comment]
Please attach relevant Appium logs.

You can observe XCTest framework log with `showIOSLog` capability. If you could find slow processes such as wait for some actions in XCTest framework side, the root cause is XCTest framework side, unfortunately. Appium strongly depends on XCTest framework, including element source tree.

**Comment by mykola-mokhnach** [comment]
> IOS UI source tree is very big and incorrect

The tree is built by XCTest itself based on the application accessibility. We cannot influence that process. Consider describing your issue to Apple.

**Comment by amedvedjev** [comment]
You did not mention how you looking for elements with iOS? It may cause sugnificant increase...

**Comment by owlsnakes** [comment]
is it slow on both ios 12 and 13?

because slowness on ios 13 has been an issue for many months now.

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by punkuotukas** [comment]
Does this have any follow up anywhere? Cause after 4 years this is still an issue.

**Comment by jlipps** [comment]
@punkuotukas you might consider reporting the slowness to Apple as it is entirely based on how XCUITest works.
