### ISSUE TITLE
Web-view is turning into infinite loop after 3 trials of switching 

### ISSUE THREAD

**Issue by apiautoamtion** [appium/appium#14210]
## The problem

Webkit hybrid IOS app context web view switching is redirecting into infinite loop after 3 trails 
## Environment

* Appium version (or git revision) that exhibits the issue:1.17
* Last Appium version that did not exhibit the issue (if applicable):1.14
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:1.12
* Real device or emulator/simulator:real devices
* Appium CLI or Appium.app|exe:

## Details

I am retrieving all context webivew and try to switch each one of them and finding the element 

problem is if the element not exist in first three web-view and not to move to next webview

## Link to Appium logs
appium console logs
[debug] [RemoteDebugger] Script parsed: {"scriptId":"374","url":","startLine":0,"startColumn":0,"endLine":0,"endColumn":42}
[debug] [RemoteDebugger] Script parsed: {"scriptId":"375","url":","startLine":0,"startColumn":0,"endLine":0,"endColumn":42}
[debug] [RemoteDebugger] Script parsed: {"scriptId":"376","url":"","startLine":0,"startColumn":0,"endLine":328,"endColumn":1}
[debug] [RemoteDebugger] Script parsed: {"scriptId":"377","url":"","startLine":0,"startColumn":0,"endLine":207,"endColumn":1}

Set<String> contextNames = ((IOSDriver) driver).getContextHandles();
				List<String> contextNamesList = new ArrayList<>(contextNames);
				int WebViewAttempts = 0;
				int temp = contextNamesList.size() - 1;
				logger.info("ContextList is: "+contextNamesList);
				for (int i=0;i< contextNamesList.size();i++) {
					loggerInfoSwitch("Current WebView Name is " + contextNamesList.get(i));
					isExpectedWebView = false;
					((IOSDriver) driver).context(contextNamesList.get(i));
					if (contextNamesList.get(i).contains("WEBVIEW")) {
						WebViewAttempts++;
						if (isElementPresent(xpath)) {
							isExpectedWebView = true;
							// logger.debug("Successfully switched to webview of the element " + element.toString());
							break;
						}
						if (WebViewAttempts > temp) {
							break;
						}
					} else if (contextNamesList.get(i).equalsIgnoreCase("NATIVE APP")) {
						isExpectedWebView = false;
						logger.debug("Failed to switch to webview of the element :: " + xpath);
					}

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by apiautoamtion** [comment]
Please help me here, its blocked our execution

**Comment by apiautoamtion** [comment]
Any update ?

**Comment by KazuCocoa** [comment]
Could you share the full log with `safariLogAllCommunication` capability as GITS?
It is appreciated if your issue happens on https://github.com/appium/ios-uicatalog or do you have the minimal app to reproduce it?

I tried like below code with our app quickly, but they worked well. (it only had one webview context)
```ruby
(1..10).each do
        @driver.context = 'WEBVIEW_5910.1'
        begin
          @driver.find_element :xpath, 'no element'
        rescue
          @driver.context = 'NATIVE_APP'
        end
      end
```

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by apiautoamtion** [comment]
not sure how to get these logs

**Comment by KazuCocoa** [comment]
It's the same appium server log you attached with safariLogAllCommunication capability.
(Please share it as GIST)
