### ISSUE TITLE
Unable to find element on iPhone 11

### ISSUE THREAD

**Issue by moagarwa** [appium/appium#14228]
## The problem

I am unable to find the element on iPhone 11 having Os version 13.3. However the element is visible on screen and when I use ios inspector it shows the object. The same script is working fine on other devices like iPhone X. The only element that we are not able to tap is those which are close to status bar

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.0
* Last Appium version that did not exhibit the issue (if applicable): 1.17.0
* Desktop OS/version used to run Appium: 10.15.4
* Node.js version (unless using Appium.app|exe): v10.10.0
* Npm or Yarn package manager: 6.14.3
* Mobile platform/version under test: iphone 11 / iOS 13
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: NA

## Details

I am unable to find the element on iPhone 11 having Os version 13.3. However the element is visible on screen and when I use ios inspector it shows the object. The same script is working fine on other devices like iPhone X. The only element that we are not able to tap is those which are close to status bar. I have tried everything but is not working on iPhone 11.

## Link to Appium logs

Appium Logs - https://gist.github.com/moagarwa/95d28038df96c031602bfc6b5b3f300d

## Code To Reproduce Issue [ Good To Have ]

Simple I am trying to tap using accessibility id.

**Comment by mykola-mokhnach** [comment]
Which element cannot be found? I don't observer any calls to findElement in the attached log

**Comment by mykola-mokhnach** [comment]
Closed because of no response
