### ISSUE TITLE
How to long press certain time a power button using adb  event command in Appium

### ISSUE THREAD

**Issue by vovchik9** [appium/appium#14223]
## The problem
I'm trying to hold power button using adb command key for certain time but does not work first just clicks does not long press and with touchscreen fails.

## Environment

* Appium version 1.17
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: OS Mac
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: Appium
## Details

`I tried: 

public void(int timeToLongPress) {
Runtime.getRuntime().exec("adb shell input keyevent --longpress KEYCODE_POWER")
.wait(timeToLongPress);          // it just clicks does not long press.
  //And

String command = "input keyevent KEYCODE_POWER";
String runScript = String.format("%s", "adb shell " + command;
MobileBy powerElement = (MobileBy) MobileBy.AndroidUIAutomator(runScript);

TouchAction Action = new TouchAction(appiumDriver);
MobileElement powerButton = AppiumDriver.driver.findElement(powerElement);
        Action.longPress(powerButton, timeToLongPress ).release().perform(); 
//fails does not click at all see appium logs
    }

Appium logs:

vlad belo12:50 AM (0 minutes ago)to me[debug] [35m[WD Proxy][39m Proxying [POST /element] to [POST http://localhost:30501/wd/hub/session/d9635808-e069-4215-a651-0abf993b2e0f/element] with body: {"strategy":"-android uiautomator","selector":"adb shell input keyevent KEYCODE_VOLUME_DOWN","context":"","multiple":false}2020-04-24 00:39:53:411 - [35m[WD Proxy][39m Got an unexpected response with status 400: {"sessionId":"d9635808-e069-4215-a651-0abf993b2e0f","value":{"error":"invalid selector","message":"Could not parse expression `new UiSelector().adb shell input keyevent KEYCODE_POWER`: No opening parenthesis after method name at position 17","stacktrace":"io.appium.uiautomator2.common.exceptions.UiSelectorSyntaxException: Could not parse expression `new UiSelector().adb shell input keyevent KEYCODE_POWER`: No opening parenthesis after method name at position 17\n\tat io.appium.uiautomator2.utils.UiExpressionParser.consumeMethodName(UiExpressionParser.java:95)\n\tat io.appium.uiautomator2.utils.UiExpressionParser.consumeMethodCall(UiExpressionParser.java:179)\n\tat io.appium.uiautomator2.utils.UiSelectorParser.parse(UiSelectorParser.java:53)\n\tat io.appium.uiautomator2.utils.UiAutomatorParser.consumeStatement(UiAutomatorParser.java:95)\n\tat io.appium.uiautomator2.utils.UiAutomatorParser.parse(UiAutomatorParser.java:48)\n\tat io.appium.uiautomator2.utils.ElementLocationHelpers.toSelectors(Eleme...2020-04-24 00:39:53:411 - [debug] [35m[W3C][39m Matched W3C error code 'invalid selector' to InvalidSelectorError2020-04-24 00:39:53:442 - [debug] [35m[W3C (87d386a9)][39m Encountered internal error running command: io.appium.uiautomator2.common.exceptions.UiSelectorSyntaxException: Could not parse expression `new UiSelector().adb shell input keyevent KEYCODE_POWER`: No opening parenthesis after method name at position 172020-04-24 00:39:53:442 - [debug] [35m[W3C (87d386a9)][39m 	at io.appium.uiautomator2.utils.UiExpressionParser.consumeMethodName(UiExpressionParser.java:95)

**Comment by mykola-mokhnach** [comment]
Please use appium forum to ask questions. 

UIA2 server provides at least two endpoints to perform long key press: W3C actions (home key code is 0xE011) or `appium/device/long_press_keycode`
