### ISSUE TITLE
package io.appium.uiautomator2.server.test does not have a signature matching the target io.appium.uiautomator2.server

### ISSUE THREAD

**Issue by hazardtony** [appium/appium#14227]
## The problem

Hi.
I've seen some topics 'bout this problem and couldn't find any solution.
Trying to use appium with UiPath Mobile Automation.
Got app installed succesfully via appium server, and then I'm not able to perform anything (that's making me angry).

## Environment

* Appium version (or git revision) that exhibits the issue: Appium Desktop 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): 12.16.2
* Npm or Yarn package manager: npm 6.14.4
* Mobile platform/version under test: Android 10
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: 
SDK build tools: 30.0.0-rc1

## Link to Appium logs

https://gist.github.com/hazardtony/abf85c06909a4275ce74f9442b03767a

**Comment by mykola-mokhnach** [comment]
> I've seen some topics 'bout this problem and couldn't find any solution.

Which solutions did you try?

**Comment by hazardtony** [comment]
1.
adb uninstall io.appium.uiautomator2.server.test
adb uninstall io.appium.uiautomator2.server

2.
in Advanced tab of Appium Desktop checking Allow Session Override and Relaxed Security

3.
upgrading to Appium Desktop 1.17.0 generated new error (Exception in thread "main" java.lang.NoClassDefFoundError)

4.
downgrading SDK to 28.0.3

5.
switching between jdk 1.7 and jdk 1.8

**Comment by mykola-mokhnach** [comment]
> upgrading to Appium Desktop 1.17.0 generated new error (Exception in thread "main" java.lang.NoClassDefFoundError)

Please provide the full server log

**Comment by hazardtony** [comment]
Hmmm.
I did nothing special, just deinstalled 1.15.1 and installed 1.17 - and it just works.

Specs:
SDK 30.0.0-rc1
JDK 1.8
in Advanced tab of Appium Desktop unchecked Allow Session Override and Relaxed Security

My guess is that I never tried to combine 8 Java with 1.17 Appium Desktop.
Sorry for bothering and I wish this may help some seeking answers!

**Comment by mykola-mokhnach** [comment]
Android SDK 30+ has dropped support of Java8 and requires minimum Java9 to be available (and set as default in JAVA_HOME)

**Comment by hazardtony** [comment]
Oh my.
I have SDK 28.0.3 installed alongside with 30.0.0-rc1.

**Comment by iamuseful** [comment]
In my case
i uninstalled:
1. Appium settings 
2. uiautomator2.server.test
3. uiautomator2.server
from my real device.
This was neccesary because i previously installed appium server of another version initially, but had to change the version because of excessive error and compatibility issues.

I began to experience the .SessionNotCreatedException when i installed the new version.
Until i uninstalled the 3 apk from my device, nothing i did solved the problem.

**Comment by akokkinn** [comment]
@iamuseful 
Your solution worked on my case as well.
I didn't actually install any other version of Appium, but I had to uninstall those 3 apks. 

Great suggestion, thanks!
