### ISSUE TITLE
[Feature Request- appium-base-driver] To Introduce, DoubleClick, buttonUp, buttonDown post request in route.js file

### ISSUE THREAD

**Issue by snoopy-peace** [appium/appium#14220]
## The problem
I use the appium-base-driver to create a customised WebDriver and use it for UIAutomation (Nightwatch & WebDriverIO) . What I can see that the POST commands for DoubleClick, ButtonUp, ButtonDown are currently not present in the route.js file. 

Currently I have forked the Appium-base-driver repository at our end and added these API calls but it would be good to have then in a released version as well. 

## Environment

OS  Used Mac 10.15 and Win 10
node version 10.15.2

## Details

The reason I am requesting for this change is that since we use a fork we are doing ssh to that repo which is not suitable for other teams using our Customised WebDriver. 

I have also raised a PullRequest: https://github.com/appium/appium-base-driver/pull/406 
but the tests are failing and one of the reason mentioned is that commands are not updated in between patch version.

**Comment by mykola-mokhnach** [comment]
The PR has been merged
