### ISSUE TITLE
cannot find any right chromedriver version for my device with Android 10 on unbuntu

### ISSUE THREAD

**Issue by huhust** [appium/appium#14230]
## The problem

cannot find any right chromedriver version for my device with Android 10 on unbuntu

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: ubuntu
* Node.js version (unless using Appium.app|exe): 10
* Npm or Yarn package manager: npm
* Mobile platform/version under test: android
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: CLI

## Details

Message: An unknown server-side error occurred while processing the command. Original error: No Chromedriver found that can automate Chrome '79.0.3945'. You could also try to enable automated chromedrivers download server feature. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md for more details

Message: An unknown server-side error occurred while processing the command. Original error: No Chromedriver found that can automate Chrome '76.0.3809'. You could also try to enable automated chromedrivers download server feature. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md for more details

## Link to Appium logs

[debug] [Chromedriver]     '/home//chromedriver' (version '2.39', minimum Chrome version '66.0.3359')
[debug] [ADB] Getting package info for 'com.google.android.webview'
[debug] [ADB] Running '/usr/local/android-sdk-linux/platform-tools/adb -P 5037 -s XX shell dumpsys package com.google.android.webview'
[debug] [Chromedriver] Found Chrome bundle 'com.google.android.webview' version '79.0.3945'
[debug] [Chromedriver] The most recent known Chrome version: 80.0.3987
[debug] [Chromedriver] Error: No Chromedriver found that can automate Chrome '79.0.3945'. You could also try to enable automated chromedrivers download server feature. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md for more details

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by KazuCocoa** [comment]
Did you try automatic download as the error message addressed?

**Comment by huhust** [comment]
> Did you try automatic download as the error message addressed?

Do you mean run with the parameter --allow-insecure chromedriver_autodownload?

Please see my log

omedriverStorageClient] Successfully synchronized 2 chromedrivers
[debug] [Chromedriver] Found 3 executables in '/usr/local/lib/node_modules/appium/node_modules/_appium-chromedriver@4.22.0@appium-chromedriver/chromedriver/linux'
[debug] [Chromedriver] The following Chromedriver executables were found:
[debug] [Chromedriver]     '/usr/local/lib/node_modules/appium/node_modules/_appium-chromedriver@4.22.0@appium-chromedriver/chromedriver/linux/chromedriver_64' (version '80.0.3987.106', minimum Chrome version '80.0.3987')
[debug] [Chromedriver]     '/usr/local/lib/node_modules/appium/node_modules/_appium-chromedriver@4.22.0@appium-chromedriver/chromedriver/linux/chromedriver_linux64_v79.0.3945.36' (version '79.0.3945.36', minimum Chrome version '79')
[debug] [Chromedriver]     '/usr/local/lib/node_modules/appium/node_modules/_appium-chromedriver@4.22.0@appium-chromedriver/chromedriver/linux/chromedriver_linux64_v79.0.3945.16' (version '79.0.3945.16', minimum Chrome version '79')
[debug] [ADB] Getting package info for 'com.google.android.webview'
[debug] [ADB] Running '/usr/local/android-sdk-linux/platform-tools/adb -P 5037 -s CLB0218B12000490 shell dumpsys package com.google.android.webview'
[debug] [Chromedriver] Found Chrome bundle 'com.google.android.webview' version '79.0.3945'
[debug] [Chromedriver] The most recent known Chrome version: 80.0.3987
[debug] [Chromedriver] Found 2 executables capable of automating Chrome '79.0.3945'.
[debug] [Chromedriver] Choosing the most recent, '/usr/local/lib/node_modules/appium/node_modules/_appium-chromedriver@4.22.0@appium-chromedriver/chromedriver/linux/chromedriver_linux64_v79.0.3945.36'.
[debug] [Chromedriver] If a specific version is required, specify it with the `chromedriverExecutable`desired capability.
[Chromedriver] Set chromedriver binary as: /usr/local/lib/node_modules/appium/node_modules/_appium-chromedriver@4.22.0@appium-chromedriver/chromedriver/linux/chromedriver_linux64_v79.0.3945.36
[debug] [Chromedriver] Killing any old chromedrivers, running: pkill -15 -f "/usr/local/lib/node_modules/appium/node_modules/_appium-chromedriver@4.22.0@appium-chromedriver/chromedriver/linux/chromedriver_linux64_v79.0.3945.36.*--port=8000"
[Chromedriver] No old chromedrivers seem to exist
[debug] [Chromedriver] Cleaning any old adb forwarded port socket connections
[debug] [ADB] List forwarding ports
[debug] [ADB] Running '/usr/local/android-sdk-linux/platform-tools/adb -P 5037 -s CLB0218B12000490 forward --list'
[debug] [ADB] Removing forwarded port socket connection: 41641 
[debug] [ADB] Running '/usr/local/android-sdk-linux/platform-tools/adb -P 5037 -s CLB0218B12000490 forward --remove tcp\:41641'
[debug] [ADB] Removing forwarded port socket connection: 36229 
[debug] [ADB] Running '/usr/local/android-sdk-linux/platform-tools/adb -P 5037 -s CLB0218B12000490 forward --remove tcp\:36229'
[debug] [ADB] Removing forwarded port socket connection: 36233 
[debug] [ADB] Running '/usr/local/android-sdk-linux/platform-tools/adb -P 5037 -s CLB0218B12000490 forward --remove tcp\:36233'
[debug] [ADB] Removing forwarded port socket connection: 33303 
[debug] [ADB] Running '/usr/local/android-sdk-linux/platform-tools/adb -P 5037 -s CLB0218B12000490 forward --remove tcp\:33303'
[Chromedriver] Spawning chromedriver with: /usr/local/lib/node_modules/appium/node_modules/_appium-chromedriver@4.22.0@appium-chromedriver/chromedriver/linux/chromedriver_linux64_v79.0.3945.36 --url-base=wd/hub --port=8000 --adb-port=5037 --verbose
[debug] [Chromedriver] Chromedriver version: '79.0.3945.36'
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[debug] [WD Proxy] Got response with status 200: {"value":{"build":{"version":"79.0.3945.36 (3582db32b33893869b8c1339e8f4d9ed1816f143-refs/branch-heads/3945@{#614})"},"message":"ChromeDriver ready for new sessions.","os":{"arch":"x86_64","name":"Linux","version":"5.3.0-28-generic"},"ready":true}}
[Chromedriver] Starting W3C Chromedriver session with capabilities: {
[Chromedriver]   "capabilities": {
[Chromedriver]     "alwaysMatch": {
[Chromedriver]       "goog:chromeOptions": {
[Chromedriver]         "androidPackage": "com.tencent.mm",
[Chromedriver]         "androidUseRunningApp": true,
[Chromedriver]         "androidDeviceSerial": "CLB0218B12000490",
[Chromedriver]         "androidProcess": "com.tencent.mm:appbrand0"
[Chromedriver]       },
[Chromedriver]       "goog:loggingPrefs": {
[Chromedriver]         "browser": "ALL"
[Chromedriver]       }
[Chromedriver]     }
[Chromedriver]   }
[Chromedriver] }
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"capabilities":{"alwaysMatch":{"goog:chromeOptions":{"androidPackage":"com.tencent.mm","androidUseRunningApp":true,"androidDeviceSerial":"CLB0218B12000490","androidProcess":"com.tencent.mm:appbrand0"},"goog:loggingPrefs":{"browser":"ALL"}}}}
[debug] [Chromedriver] Webview version: 'Chrome/66.0.3359.126'
[WD Proxy] Got response with status 500: {"value":{"error":"session not created","message":"session not created: This version of ChromeDriver only supports Chrome version 79","stacktrace":"#0 0x558759568479 <unknown>\n"}}
[debug] [W3C] Matched W3C error code 'session not created' to SessionNotCreatedError
[Chromedriver] Failed to start Chromedriver session: A new session could not be created. Details: session not created: This version of ChromeDriver only supports Chrome version 79
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"capabilities":{"alwaysMatch":{"goog:chromeOptions":{"androidPackage":"com.tencent.mm","androidUseRunningApp":true,"androidDeviceSerial":"CLB0218B12000490","androidProcess":"com.tencent.mm:appbrand0"},"goog:loggingPrefs":{"browser":"ALL"}}}}
[debug] [Chromedriver] Webview version: 'Chrome/66.0.3359.126'
[WD Proxy] Got response with status 500: {"value":{"error":"session not created","message":"session not created: This version of ChromeDriver only supports Chrome version 79","stacktrace":"#0 0x558759568479 <unknown>\n"}}
[debug] [W3C] Matched W3C error code 'session not created' to SessionNotCreatedError
[Chromedriver] Failed to start Chromedriver session: A new session could not be created. Details: session not created: This version of ChromeDriver only supports Chrome version 79
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"capabilities":{"alwaysMatch":{"goog:chromeOptions":{"androidPackage":"com.tencent.mm","androidUseRunningApp":true,"androidDeviceSerial":"CLB0218B12000490","androidProcess":"com.tencent.mm:appbrand0"},"goog:loggingPrefs":{"browser":"ALL"}}}}
[debug] [Chromedriver] Webview version: 'Chrome/66.0.3359.126'
[WD Proxy] Got response with status 500: {"value":{"error":"session not created","message":"session not created: This version of ChromeDriver only supports Chrome version 79","stacktrace":"#0 0x558759568479 <unknown>\n"}}
[debug] [W3C] Matched W3C error code 'session not created' to SessionNotCreatedError
[Chromedriver] Failed to start Chromedriver session: A new session could not be created. Details: session not created: This version of ChromeDriver only supports Chrome version 79
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"capabilities":{"alwaysMatch":{"goog:chromeOptions":{"androidPackage":"com.tencent.mm","androidUseRunningApp":true,"androidDeviceSerial":"CLB0218B12000490","androidProcess":"com.tencent.mm:appbrand0"},"goog:loggingPrefs":{"browser":"ALL"}}}}
[debug] [Chromedriver] Webview version: 'Chrome/66.0.3359.126'
[WD Proxy] Got response with status 500: {"value":{"error":"session not created","message":"session not created: This version of ChromeDriver only supports Chrome version 79","stacktrace":"#0 0x558759568479 <unknown>\n"}}

**Comment by mykola-mokhnach** [comment]
> [debug] [Chromedriver] Webview version: 'Chrome/66.0.3359.126'

It is either necessary to provide the matching Chromedriver version manually (via `chromedriverExecutable` cap), because Appium fails to autodetect the webview version or use appium@beta with `enableWebviewDetailsCollection` capability enabled

**Comment by huhust** [comment]
> > [debug] [Chromedriver] Webview version: 'Chrome/66.0.3359.126'
> 
> It is either necessary to provide the matching Chromedriver version manually (via `chromedriverExecutable` cap), because Appium fails to autodetect the webview version or use appium@beta with `enableWebviewDetailsCollection` capability enabled

The question now is I cannot find any matching chromedriver version.

See this log, I set chromedriver(version:79 because the version of my android webview  is 79). Before create session, It print version '79', then print version '66'?

Spawning chromedriver with: /home/chromedriver --url-base=wd/hub --port=8000 --adb-port=5037 --verbose
[debug] [Chromedriver] Chromedriver version: '79.0.3945.36'
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[debug] [WD Proxy] Got response with status 200: {"value":{"build":{"version":"79.0.3945.36 (3582db32b33893869b8c1339e8f4d9ed1816f143-refs/branch-heads/3945@{#614})"},"message":"ChromeDriver ready for new sessions.","os":{"arch":"x86_64","name":"Linux","version":"5.3.0-28-generic"},"ready":true}}
[Chromedriver] Starting W3C Chromedriver session with capabilities: {
[Chromedriver]   "capabilities": {
[Chromedriver]     "alwaysMatch": {
[Chromedriver]       "goog:chromeOptions": {
[Chromedriver]         "androidPackage": "com.tencent.mm",
[Chromedriver]         "androidUseRunningApp": true,
[Chromedriver]         "androidDeviceSerial": "Q5S5T19404007505",
[Chromedriver]         "androidProcess": "com.tencent.mm:appbrand0"
[Chromedriver]       },
[Chromedriver]       "goog:loggingPrefs": {
[Chromedriver]         "browser": "ALL"
[Chromedriver]       }
[Chromedriver]     }
[Chromedriver]   }
[Chromedriver] }
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"capabilities":{"alwaysMatch":{"goog:chromeOptions":{"androidPackage":"com.tencent.mm","androidUseRunningApp":true,"androidDeviceSerial":"Q5S5T19404007505","androidProcess":"com.tencent.mm:appbrand0"},"goog:loggingPrefs":{"browser":"ALL"}}}}
[debug] [Chromedriver] Webview version: 'Chrome/66.0.3359.126'
[WD Proxy] Got response with status 500: {"value":{"error":"session not created","message":"session not created: This version of ChromeDriver only supports Chrome version 79","stacktrace":"#0 0x561044900479 <unknown>\n"}}
[debug] [W3C] Matched W3C error code 'session not created' to SessionNotCreatedError
[Chromedriver] Failed to start Chromedriver session: A new session could not be created. Details: session not created: This version of ChromeDriver only supports Chrome version 79
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"capabilities":{"alwaysMatch":{"goog:chromeOptions":{"androidPackage":"com.tencent.mm","androidUseRunningApp":true,"androidDeviceSerial":"Q5S5T19404007505","androidProcess":"com.tencent.mm:appbrand0"},"goog:loggingPrefs":{"browser":"ALL"}}}}
[debug] [Chromedriver] Webview version: 'Chrome/66.0.3359.126'
[WD Proxy] Got response with status 500: {"value":{"error":"session not created","message":"session not created: This version of ChromeDriver only supports Chrome version 79","stacktrace":"#0 0x561044900479 <unknown>\n"}}

**Comment by mykola-mokhnach** [comment]
> The question now is I cannot find any matching chromedriver version.

The actual matching for manual CD selection could be found at https://github.com/appium/appium-chromedriver/blob/master/config/mapping.json

79 is the version of the installed chromedriver package, but this is not necessarily the same as the web view version

**Comment by huhust** [comment]
> > The question now is I cannot find any matching chromedriver version.
> 
> The actual matching for manual CD selection could be found at https://github.com/appium/appium-chromedriver/blob/master/config/mapping.json
> 
> 79 is the version of the installed chromedriver package, but this is not necessarily the same as the web view version

Thanks for your replay,  2.39 is OK!!
