### ISSUE TITLE
The application is getting struck at launch screen and not proceeding forward.

### ISSUE THREAD

**Issue by pranav21keshav** [appium/appium#14236]
## The problem

The application is getting struck at launch screen and not proceeding forward.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 10.15.4
* Node.js version (unless using Appium.app|exe): Using Appium.app
* Npm or Yarn package manager:
* Mobile platform/version under test: iOS 12.0, iOS 13.2
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium App

## Details

After launch the application is getting struck at launch screen and not proceeding forward.

## Link to Appium logs

https://gist.github.com/pranav21keshav/aa2dbced2e859a66d936a3be53fea53c

## Code To Reproduce Issue [ Good To Have ]

I am using following capabilities in Appium
{
  "platformName": "iOS",
  "automationName": "XCUITest",
  "deviceName": "iPhone 8",
  "app": "/Users/p0p00sv/Projects/App/WMSwift.app",
  "platformVersion": "13.2"
}

**Comment by mykola-mokhnach** [comment]
> [debug] [XCUITest] Failed to create WDA session (The application under test with bundle id 'com.test.swift' is not running, possibly crashed). Retrying...[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1587988870669 (17:31:10 GMT+0530 (IST))

Are you sure the app can be run at all?

**Comment by pranav21keshav** [comment]
When I build and run through Xcode, it runs fine on simulator

**Comment by mykola-mokhnach** [comment]
If don't think we can do anything from Appium side. I would also check the device logs - perhaps the app logs something useful there

**Comment by KazuCocoa** [comment]
How about launching the app via vanilla XCTest? It also may help to check the app can launch via XCTest framework.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue (also no response)

**Comment by pranav21keshav** [comment]
@KazuCocoa @mykola-mokhnach Thanks for helping me out.
Actually after much debugging I found out that it was an issue with app, where few libraries were not embedded. It was running fine when launched through xcode but was not running when launched through simulator.
