### ISSUE TITLE
driver.getCurrentUrl() is not responding on real iOS device with Webview.

### ISSUE THREAD

**Issue by Pavithra24x7** [appium/appium#14245]
## The problem
I am executing automation scripts on iOS Real device, the testing application is an hybrid application there we need to switch between Native and Webview and vice versa.There are 3 contexts available namely [NATIVE_APP, WEBVIEW_2016.3, WEBVIEW_2016.4], out of the 2 webviews only one Webview is valid webview, I need to find the correct webview and need to switch into the same, but If I call driver.getCurrentUrl() the method is not responding.
## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 10.15.2 (macOS Catalina)
* Node.js version (unless using Appium.app|exe):13.1.0
* Npm or Yarn package manager: 6.12.1
* Mobile platform/version under test:13.3.1
* Real device or emulator/simulator: iOS - Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Details
driver.getCurrentUrl() method is not responding after switching into the webview.
driver.context(webviews.get(i)) method is working fine & able to switch into the webview, after that If I call driver.getCurrentUrl() its not returning the URL of the webview, I am calling this method to check the valid url, if the url is not present in the webview then I need to use other webviews for switching.

## Link to Appium logs

Create a [GIST](https://gist.github.com/Pavithra24x7/ef534b334165e67e12681a0f01b3185e) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

if(webviews.get(i).contains("WEBVIEW")){
                	try {
                		driver.context(webviews.get(i));
                		String cc=driver.getContext();
                   	 if(driver.getCurrentUrl().contains(urlMatch)) {
                   		driver.context(webviews.get(i));
                           flag=5;
                           break; 
                   	 }
                	}catch(Exception e) {
                		log.info("Exception => "+e);
                	}
}

**Comment by mykola-mokhnach** [comment]
Closed as duplicate
