### ISSUE TITLE
driver.getStrings behaviour when requesting default 

### ISSUE THREAD

**Issue by dwightdhooge** [appium/appium#14241]
## The problem

1. Device language is nl 
2. 'nl' is default language of apk, so strings are in /values/strings.xml. 
3. Calling method driver.getAppStringMap("nl"), returns strings from folders /values-nl of external libraries, but not the strings of the app since they are not in 'values-nl' folder
4. Also when using driver.getAppStringMap(), it automatically fallbacks to the devicelanguage nl and so also execute driver.getAppStringMap("nl") which again doesn't return the correct strings 
5. Only for 'en'  i get 
`[debug] [ADB] There is no 'en' configuration. Replacing it with '(default)'`
which redirects to the default values/strings.xml. For other languages like 'es' or 'pt' i don't get this message and it wil download 'es', 'pt' strings from the external libraries 

So very difficult to get the strings out of the default values/strings.xml. Expect that driver.getAppStringMap() would redirect to the default values and not use for example the device language which leads to incorrect results 

## Environment

* Appium version : 1.17 
* Desktop OS/version used to run Appium: macOS Catalina 10.15.1
* Node.js version (unless using Appium.app|exe): v13.11.0
* Npm or Yarn package manager: 6.13.4
* Mobile platform/version under test:  Android 10 
* Real device or emulator/simulator: Real device 

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

device language = en 
```
[HTTP] --> POST /wd/hub/session/dd1cc3bf-3983-4354-af52-d308886ee0e7/appium/app/strings
[HTTP] {"language":"en"}
[debug] [W3C (dd1cc3bf)] Calling AppiumDriver.getStrings() with args: ["en",null,"dd1cc3bf-3983-4354-af52-d308886ee0e7"]
[debug] [ADB] Extracting strings from for language: en
[ADB] Using 'aapt' from '/Users/dwight.dhooge/Library/Android/sdk/build-tools/29.0.2/aapt'
[debug] [ADB] There is no 'en' configuration. Replacing it with '(default)'
```
device language = es 
```[HTTP] --> POST /wd/hub/session/393eacf6-e468-4de5-a0d2-e33d25c3d062/appium/app/strings
[HTTP] {}
[debug] [W3C (393eacf6)] Calling AppiumDriver.getStrings() with args: [null,null,"393eacf6-e468-4de5-a0d2-e33d25c3d062"]
[debug] [ADB] Running '/Users/dwight.dhooge/Library/Android/sdk/platform-tools/adb -P 5037 -s RF8N20HC9QV shell getprop persist.sys.locale'
[debug] [ADB] Current device property 'persist.sys.locale': es-ES
[UiAutomator2] No language specified, returning strings for: es
[debug] [ADB] Extracting strings from for language: es
[ADB] Using 'aapt' from '/Users/dwight.dhooge/Library/Android/sdk/build-tools/29.0.2/aapt'
[ADB] Successfully extracted 626 strings from '/Users/dwight.dhooge/Automation/projects/sdworx-simon-uitests/src/test/resources/app/app.apk' resources for 'es' configuration
```
## Code To Reproduce Issue [ Good To Have ]
```driver.getAppStringMap()```

**Comment by mykola-mokhnach** [comment]
We don't do any magic there. All the actual output is generated by the standard Android SDK aapt utility. 

> Expect that driver.getAppStringMap() would redirect to the default values and not use for example the device language which leads to incorrect results

This would break the backward compatibility, which is not something we'd like to do

**Comment by dwightdhooge** [comment]
So any idea how i can get nl strings out of this apk, without incorrectly defining language 'en'  ?

**Comment by mykola-mokhnach** [comment]
The list of available resource configs could be shown using `appt d configurations <apk>` command

**Comment by dwightdhooge** [comment]
Not really agree this is NotABug. There is no way to download the default values of your apk.

**Comment by mykola-mokhnach** [comment]
Unfortunately we cannot do much there as we completely rely on the aapt tool functionality. Consider reporting your issue to Google.

**Comment by mykola-mokhnach** [comment]
Btw, Google also added aapt2 to the recent SDKs. You could check the configurations dump for both of them and check if the expected data is there. After the configuration name is retrieved the resources could be shown in terminal using the following commands:
- For aapt: `aapt d --values resources <apk>`
- For aapt2: `aapt2 d resources <apk>`

**Comment by mykola-mokhnach** [comment]
Closed because of no response
