### ISSUE TITLE
My session with my.bundle.id is replaced by another session with com.facebook.WebDriverAgentRunner bundleId

### ISSUE THREAD

**Issue by hociungradu** [appium/appium#14252]
## The problem

I tried to open a session using my capabilities, but it was reseted/closed and replaced with a new one containing com.facebook.WebDriverAgentRunner bundleId. 
WDA project was build with xcode 11.4, signed and installed properly on my real device.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 10.15.4
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager: 6.14.4
* Mobile platform/version under test: iphone 7 with iOS 13.3.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: Appium.exe

## Details
Just started Appium inspector and tried to create an session with my desired capabilities:
{
“xcodeOrgId”: “4XGDRF4ETY”,
“xcodeSigningId”: “iPhone Developer”,
“platformName”: “iOS”,
“platformVersion”: “13.3”,
“udid”: “aa69908b1856a4d1cba21bfeabb8a972129…”,
“deviceName”: “iPhone 1”,
“bundleId”: “com.unify.iOSMO”,
“noReset”: true,
“autoAcceptAlerts”: true,
“automationName”: “XCUITest”
}

## Link to Appium logs

https://gist.github.com/hociungradu/a75049cb6e3f625a3fefd3f91713ec88

**Comment by mykola-mokhnach** [comment]
Sorry, I don't quite understand what the issue is. 

There is `updatedWDABundleId` cap if you want to set a custom WDA identifier

**Comment by hociungradu** [comment]
@mykola-mokhnach Thanks, that solve it.
