### ISSUE TITLE
Exception in thread "main" org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Command 'idevice_id -l' errored out: Error: spawn idevice_id ENOENT

### ISSUE THREAD

**Issue by baligit** [appium/appium#14257]
## The problem

I am trying to build my first iOS test using appium.  By running the code I have got unfortunately  an error. 'Command 'idevice_id -l' errored out: Error: spawn idevice_id ENOENT'. I dont know how i can fix it.  

Thanks  

## Environment

* Appium version (or git revision) that exhibits the issue: 1.12.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager: 6.14.4
* Mobile platform/version under test: iOS 
* Real device or emulator/simulator: real device 
* Appium CLI or Appium.app|exe: Appium command-line interface

## Link to Appium logs
https://gist.github.com/baligit/a842d9898776209aba3acd36652b4547

## Code To Reproduce Issue [ Good To Have ]

this my code: 
<img width="819" alt="Bildschirmfoto 2020-04-30 um 13 39 03" src="https://user-images.githubusercontent.com/63911430/80706182-2a015e80-8ae8-11ea-9c1f-c083b11156dc.png">

This is the result by running  $appium-doctor --ios on CLI 
<img width="967" alt="Bildschirmfoto 2020-04-30 um 13 44 19" src="https://user-images.githubusercontent.com/63911430/80706710-10144b80-8ae9-11ea-908b-abc40acd9c51.png">

**Comment by mykola-mokhnach** [comment]
Consider updating to the most recent server version. We don't provide patches to older server versions.

**Comment by baligit** [comment]
Which version is the most recent server version?

**Comment by mykola-mokhnach** [comment]
`npm info appium`
