### ISSUE TITLE
Sendkeys not getting enabled keys in hybrid app

### ISSUE THREAD

**Issue by apiautoamtion** [appium/appium#14259]
## The problem

I have search bar in my application trying to send keys and performing keyboard actions RETURN.

Not seeing the the results 

## Environment

* Appium version (or git revision) that exhibits the issue:1.17.0
* Last Appium version that did not exhibit the issue (if applicable):1.14.0
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

![image](https://user-images.githubusercontent.com/31579747/80744368-8a929a80-8aec-11ea-9505-4bc79d8c0276.png)
flexB2BSearchDeviceSku.sendkeys("");
flexB2BSearchDeviceSku.sendKeys(Keys.RETURN);

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by apiautoamtion** [comment]
As per dev they have onClick() and release methods for latest APPS. so keyboard bring up is must for couple of areas

**Comment by mykola-mokhnach** [comment]
> flexB2BSearchDeviceSku.sendKeys(Keys.RETURN);

This usually does not work for mobile apps. It is necessary to locate the Return button on the on-screen keyboard and tap it.

**Comment by apiautoamtion** [comment]
This is for hybrid app.
First case keyboard not opening while sending keys.

How to open the keyboard in Hybrid app with sendkeys.



to click on return button

**Comment by apiautoamtion** [comment]
When there is native element in the screen its perfectly fine .we can send-keys and keyboard is opening.

But when it comes to hybrid element not able to open keyborad to send keys .


in few pages we are converting hybrid element to native and opening the keys.

but in this case i am not able to convert the element to native

**Comment by apiautoamtion** [comment]
can we introduce openkeyboard action in appium?

**Comment by amedvedjev** [comment]
just tap or click into input. it is your app behavior.

**Comment by mykola-mokhnach** [comment]
> can we introduce openkeyboard action in appium?

Unfortunately this is impossible, since no API is provided for such actions. Consider creating a feature request to Apple

**Comment by apiautoamtion** [comment]
@amedvedjev tried tap and click all the regular BAU trials 
Nothing works for this specific scenario

because onclick method is not calling in the app when we use send keys .

@mykola-mokhnach thanks for the response .

not sure how to tackle this scenario

**Comment by pb0818** [comment]
@apiautoamtion :- how about you switch to native view and interact in native view (this would be slow, but definitely work).

**Comment by apiautoamtion** [comment]
tried that, it's a good solution. we were using the same for other elements where ever we had a issue 

but this particulate element doe't  work the same like others .

And when I get page source not seeing the element tho

**Comment by apiautoamtion** [comment]
IOSTouchAction any examples do u have will it work

**Comment by amedvedjev** [comment]
@apiautoamtion if you manually tap on this input field and keyboard appears = same should happen when you tap in code. You may even find input and tap by it center with coordinates x and y. If even this does not work = you tap wrong place.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
