### ISSUE TITLE
Could not launch “WebDriverAgentRunner”

### ISSUE THREAD

**Issue by xsj931122** [appium/appium#14251]
## The problem

when click on test in xcode ,it can build successfully ,but will toast 
could not launch “WebDriverAgentRunner”
Test11 has denied the launch request.
Internal launch error: process launch failed: Unspecified

## Environment

* Appium version 1.15.0
* Xcode version:11.3.1 (11C504)
* Mobile platform:ios 13.3 iphone 11

## Details
Could not launch “WebDriverAgentRunner”
Domain: IDEDebugSessionErrorDomain
Code: 3
Failure Reason: Test11 has denied the launch request.
Internal launch error: process launch failed: Unspecified
--
process launch failed: Unspecified
Domain: IDEDebugSessionErrorDomain
Code: 3
--

## Code To Reproduce Issue [ Good To Have ]

1.cd /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent
2../Scripts/bootstrap.sh
3.open webdriveragent by using xcode
4.update my personal account in WebDriverAgentLib/WebDriverAgentRunner
5.test

**Comment by mykola-mokhnach** [comment]
- Please use the most recent server version
- Do you follow https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md?

**Comment by mykola-mokhnach** [comment]
Closed because of no response
