### ISSUE TITLE
UiAutomator support for UiScrollable().scrollTextIntoView()

### ISSUE THREAD

**Issue by QAthulhu** [appium/appium#14254]
## The problem

Using `UiScrollable().scrollTextIntoView()` causes the following exception:
`UiSelectorSyntaxException: Could not parse UiSelector argument: Must only call the 'scrollIntoView' method OR methods on UiScrollable which return UiScrollable or UiObject objects`

`scrollIntoView` does not return a UiScrollable/UiObject but instead returns a boolean. If this can be accepted by UiAutomator2 then `scrollTextIntoView` should be as well as it also returns a boolean. Furthermore, its underlying implementation is simply a shortcut of `scrollIntoView(new UiSelector().text("text"))`, so it is essentially a call to `scrollIntoView`.

Here's the code I ran in case anyone needs it: 
`driver.findElement(MobileBy.AndroidUIAutomator("new UiScrollable(new UiSelector().resourceId(\""+ scrollerID +"\")).setMaxSearchSwipes(40).scrollTextIntoView(\"" + elementText + "\")"));`

Additionally, it would be nice if the `flingForward()` and `flingBackward()` methods could also be supported since `scrollIntoView` always goes back to the start of the scrollable element, which may take time (and reach max scrolls going back to the top), especially for pages with infinite scrolling. Just my 2 cents

**Comment by mykola-mokhnach** [comment]
This behaviour has been changed in appium@beta

**Comment by QAthulhu** [comment]
Can't seem to install appium@beta or appium-version-manager, I may not be able to retest this

**Comment by mykola-mokhnach** [comment]
It may be that your npm client is pointing to a custom repository. Try to get it from the other (clean) machine or in the other network. `npm install appium@beta` is the correct command. 
Unfortunately, we don't provide patches to older versions.
