### ISSUE TITLE
getAttribute() not working when running tests on BrowserStack

### ISSUE THREAD

**Issue by QAthulhu** [appium/appium#14253]
## The problem
Calling `getAttribute` on a `MobileElement` when running on BrowserStack returns a `NoAttributeFoundException`. I tested this using `getAttribute("resource-id")` and `getAttribute("class")`

This works fine when running tests on a local emulator or connected device, but once I run the test on BrowserStack devices I get this error:
`io.appium.uiautomator2.common.exceptions.NoAttributeFoundException: This element does not have the 'resource-id' attribute`

I didn't know about `getId()` at the time
## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0
* Desktop OS/version used to run Appium: MacOS Mojave on my machine
* Node.js version (unless using Appium.app|exe): 12.11.1
* Npm or Yarn package manager: NPM 6.11.3
* Mobile platform/version under test: Tried on Android 9 and 10 (Google Pixel 2, 4, Samsung galaxy J8, S8+)
* Real device or emulator/simulator: Pixel 2 = both, Pixel 4 and Samsung all real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
A log for trying to use `getAttribute("resource-id)` 
https://gist.github.com/QAthulhu/5378c2c3d29bf454093aef4f8ae0033d

## Code To Reproduce Issue [ Good To Have ]

Really it's just:
`driver.findElement(locator).getAttribute("class")`

**Comment by mykola-mokhnach** [comment]
Consider reporting your issue to BS support. If it works on local env then there is nothing we can do to change that in the cloud
