### ISSUE TITLE
"processArguments" functionality for a Win32 Application?

### ISSUE THREAD

**Issue by samuelfreiberg** [appium/appium#14273]
## The problem

In order to run my application in the correct state, I need to pass command-line arguments to my Win32 application. I see there's a "processArguments" capability for iOS that allows you to pass arguments to the application. Is there something similar for Windows? How can I achieve passing command-line args to my Win32 app? Any help would be much appreciated!

## Environment

Appium v1.17.0
Node v12.16.1
yarn v.1.22.0

## Details

I was hoping to get more information about this - whether or not this is possible, and how I can accomplish it.

**Comment by mykola-mokhnach** [comment]
Consider asking your questions at https://github.com/microsoft/WinAppDriver

Appium team does not maintain the Windows driver. Also, we have forum for questions.
