### ISSUE TITLE
Unable to detect WebView on Android Real Device

### ISSUE THREAD

**Issue by arpitkup** [appium/appium#14270]
## The problem

I am trying to automate Android app that has Native and Webview. When I run my test on android emulator, I am able to see both native and webview contexts, and able to switch to webview after launching the app and successfully interact with web elements. However, when I run the same test on the Android real device(Android 9, Galaxy S9), when AppiumDriver.getContexts() method is called, I can see only Native context. The Webview context is not detected at all. I am passing the following capabilities. capability.SetCapability("platformName", "Android");
capability.SetCapability("platformVersion", "9.0");
capability.SetCapability("deviceName", "Galaxy S9");
capability.SetCapability("app", "./Documents/myApp.apk");
capability.SetCapability("automationName", "UiAutomator2");

Can you please help ? 

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.16.0
* Node.js version (unless using Appium.app|exe):10.16.0
* Mobile platform/version under test: Android 9
* Real device or emulator/simulator:emulator
* Appium CLI or Appium.app|exe:Appium CLI

## Link to Appium logs

https://gist.github.com/arpitkup/f5a0d428a541364b3dc2228000fd19bb

## Code To Reproduce Issue [ Good To Have ]

 public void SwitchToContext(String contextName)
        {
            List<string> AllContexts = new List<string>();
            foreach (var context in (driver.Contexts))
            {
                AllContexts.Add(context);
            }

            foreach (var context in AllContexts)
            {
                if (context.Contains(contextName))
                {
                    driver.Context = context;
                    WaitForDriverContextChange(contextName);
                    if (driver.Context.Contains(contextName))
                    {
                        break;
                    }
                    else
                    {
                        WaitForDriverContextChange(contextName);
                    }
                }
            }
        }

**Comment by mykola-mokhnach** [comment]
- Is the web view visible in Chrome Remote debugger?
- Could you try the same with appium@beta and attach the updated log?

**Comment by arpitkup** [comment]
- Is the web view visible in Chrome Remote Debugger? - It's a native app with webviews embedded. So couldn't really see in chrome remote debugger. When I launch it via url, I can see it. 

- Could you try the same with appium@beta and attach the updated log?
couldn't update Appium CLI as we are in the middle of execution but updated the Appium desktop to new Appium v1.17.0.  Updated logs : https://gist.github.com/arpitkup/5e2a68461ae11ecd3b22082c87dc2bbd

**Comment by mykola-mokhnach** [comment]
> So couldn't really see in chrome remote debugger.

If the web view is not visible in CRD then there's no way it could be visible in Appium.

> Unfortunately appium@beta != 1.17.0

Please try it with appium@beta, as it contains the most recent changed and writes more useful debugging info.

**Comment by amedvedjev** [comment]
@arpitkup with native app and webViews ask Android dev to check
```
WebView.setWebContentsDebuggingEnabled(true)
```
and you can connect to it webView ->
https://developers.google.com/web/tools/chrome-devtools/remote-debugging/webviews

**Comment by arpitkup** [comment]
Thanks guys, since I am not able to see webview in CRD, I have asked the devs to check if the webview debugging is enabled. Once, I get them to address this, I will give it go again. 

If the debugging is not enabled, would appium be able to detect and switch to webview on Emulators?

**Comment by mykola-mokhnach** [comment]
> If the debugging is not enabled, would appium be able to detect and switch to webview on Emulators?

No this would be not possible

Closed as not an issue

**Comment by Dilipec027** [comment]
@mykola-mokhnach @arpitkup .I am facing same problem. In emulator it’s shows web view but not in real device. Any solution ?

**Comment by nalvelo** [comment]
@mykola-mokhnach @arpitkup Same here, we are unable to find the WebView context when deploying the same APK and running the same Appium capabilities on a physical Pixel 3 Android 11 device versus a Pixel 3 Android 11 emulator (where it succeeds). WebView debugging is enabled on the APK build.
