### ISSUE TITLE
Install of latest appium version fails 

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#14288]
## The problem

with macOS latest Appium fails to install with windows driver problem error. why do we need install windows driver on macOS?

## Environment

* Appium version (or git revision) that exhibits the issue: latest code for 5 May 2020
* Last Appium version that did not exhibit the issue (if applicable): 1.17.1
* Desktop OS/version used to run Appium: MacOS

## Details

Error is:
```
> appium-windows-driver@1.12.1 install /usr/local/lib/node_modules/appium/node_modules/appium-windows-driver
> node install-npm.js

Error: Package exports for '/usr/local/lib/node_modules/appium/node_modules/uuid' do not define a '.' subpath
```

**Comment by mykola-mokhnach** [comment]
appium-windows-driver@1.12.1 is only installed with current appium@beta

Also, I've just tried that on Mac and everything worked as expected: 

```
> appium-windows-driver@1.12.1 install /usr/local/lib/node_modules/appium/node_modules/appium-windows-driver
> node install-npm.js

Not installing WinAppDriver since did not detect a Windows system
```

Are you sure your environment is in a good shape?

**Comment by amedvedjev** [comment]
what you mean? am i on macOS? is 1.17.1 can be install successfully on mine machine?

**Comment by amedvedjev** [comment]
1. update 10.15.3 -> 10.15.4
2. update nodeJS to latest 14.2.0

= issue solved

**Comment by mykola-mokhnach** [comment]
> npm install -g appium@1.17.1 --no-shrinkwrap // problem happens

Either consider installing appium@beta or don't ignore shrinkwrap.
