### ISSUE TITLE
Appium 1.15.1 - Wheel Picker Crash iOS 11 

### ISSUE THREAD

**Issue by ixr0220** [appium/appium#14287]
## My scripts are crashing whenever I have a wheel picker and has over a certain amount of items. It always crashes in the same spot. 

This is only reproducible with my automation scripts, manually the app does not crash. If I test iOs 12 or 13 devices they are ok. 

## Environment

* Appium version: 1.15.1
* Desktop OS/version used to run Appium: 10.14.6
* Npm or Yarn package manager:
* Mobile platform/version under test: iPhone X iOS 11.1.2
* Real device or emulator/simulator: Real device

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.

Appium Logs:
https://gist.github.com/ixr0220/ae8e3d30ba84c5e8b2879915cbc361c3

iOS Crash Log:
https://gist.github.com/ixr0220/d08aa5233de765feb35ebe4a592f9ead

## Code To Reproduce Issue

	public void sendKeysC(MobileElement element, int rotations, String successMessage, String failureMessage, AppiumDriver<?> driver) {
		final long startTime = System.currentTimeMillis();
		try {
			waitforElement(DeviceBucket.getDriver(), element, 50);
			for(int i=0;i<rotations;i++) {
					Map<String, Object> params = new HashMap<>();
					params.put("order", "next");
				if(AppiumUtils.isConnectedDeviceiPad()) {
					params.put("offset", 0.1);
				} else {
					params.put("offset", 0.15);
				}
					params.put("element", ((RemoteWebElement) element).getId());
					driver.executeScript("mobile:selectPickerWheelValue", params);
			}		
			logger.info("Value has been entered after {}{}", (System.currentTimeMillis() - startTime), " milliseconds");
			logger.info(successMessage);
		} catch (Exception exception) {
			catchBlock(element, exception, failureMessage);
		}
	}

**Comment by mykola-mokhnach** [comment]
The exception happens somewhere in iOS accessibility internals. I don't think we could do anything there from WDA side. 
As a workaround I would try to perform swipe by coordinates

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
