### ISSUE TITLE
Take screenshot fails on Appium 1.17.0

### ISSUE THREAD

**Issue by rg-software** [appium/appium#14282]
I am sorry to bring back [this old issue](https://github.com/appium/appium/issues/12470), but it seems it is still with us.

I have an Android 5.1 device, where taking a screenshot fails with the "Does the current view have 'secure' flag set" message. The screen is 1024x600, density 160.

`adb shell screencap -p /sdcard/screen.png
`
produces a correct screenshot. Switching to UIAutomator1 also allows me to take a screenshot (but then I have failures later, so I'd prefer to use UIAutomator2).

So, is there anything I can try?..

**Comment by mykola-mokhnach** [comment]
Does the target view have the secure flag set?

**Comment by rg-software** [comment]
I am  not entirely sure I do it right, but here it is:
`adb shell dumpsys window com.unity3d.player.UnityPlayerActivity
...
mAttrs=WM.LayoutParams{(0,0)(fillxfill) sim=#20 ty=1 fl=#810500 fmt=-3 wanim=0x1030001 vsysui=0x1706 sysuil=true surfaceInsets=Rect(0, 0 - 0, 0) needsMenuKey=2}
`
810500 & (FLAG_SECURE, which is 0x2000) = 0, so apparently not set.

**Comment by mykola-mokhnach** [comment]
Could you please attach the logcat output as well?

**Comment by rg-software** [comment]
Hope there is something relevant there.
[logcat.zip](https://github.com/appium/appium/files/4581844/logcat.zip)

**Comment by mykola-mokhnach** [comment]
Unfortunately the log does not show any useful details. Most likely UiAutomator itself cannot capture the screen and thus returns `null` to us.

**Comment by rg-software** [comment]
Well, I can also confirm the same point as noted in the previous issue: the system worked fine till this Appium update (I had quite an old version installed there before), and it works with UiAutomator1 and adb screencap.

**Comment by mykola-mokhnach** [comment]
Which Android version it is?

**Comment by rg-software** [comment]
5.1.1 (LineageOS-based).
I tried changing DPI settings (it is possible in Lineage), but they had no effect.

**Comment by mykola-mokhnach** [comment]
UiAutomator2 is recommended since Android6. Android5 has several known bugs, so it makes sense to enforce UiAutomator1 usage for it

**Comment by rg-software** [comment]
I see. My problem with UiAutomator1 is strange: when I am trying to tap on the screen, nothing happens! Maybe I'll have to retire that device after all.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
