### ISSUE TITLE
How can i start my tests in the current screen app is in IOS?

### ISSUE THREAD

**Issue by hadrianjmnz90** [appium/appium#14284]
## The problem

I noticed that every time i run a test, the app is sent to the background and then reopened, the problem is let's say that i am in the settings screen, after the app is relaunched, it is relaunched in home screen, but i want to run my test starting in settings screen, is there any way to do that?

## Environment

appium 15.1
ios 13
mac mojave

**Comment by mykola-mokhnach** [comment]
Kindly use Appium forum to ask questions
