### ISSUE TITLE
Exception in thread "main" org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters.

### ISSUE THREAD

**Issue by baligit** [appium/appium#14295]
## The problem
By findElement could not be located on the page using the given search parameters
## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.0
* Desktop OS/version used to run Appium: iPhone 11
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: ios
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe:Appium.app

## Details

I try to access the element on the current page of the app. but the server failed with it.  

## Link to Appium logs

[appium-server-logs.txt](https://github.com/appium/appium/files/4585756/appium-server-logs.txt)

## Code To Reproduce Issue [ Good To Have ]

        AppiumDriver driver = new AppiumDriver(url, capabilities);
        driver.findElement(By.xpath("//XCUIElementTypeStaticText[@name=\"Unit Converter\"[2]")).click();

This is my mavn dependencey: 

 <dependencies>
        <dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>5.0.4</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.14.0</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-api</artifactId>
            <version>3.14.0</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-remote-driver</artifactId>
            <version>3.14.0</version>
        </dependency>
        <dependency>
        <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.7</version>
        </dependency>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>6.14.3</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

**Comment by mykola-mokhnach** [comment]
I don't observe any server issues in the attached log. Does the element present in the page source?

**Comment by baligit** [comment]
yes the element present in the page source:  This is from appium inspecter: 
xpath: (//XCUIElementTypeStaticText[@name="Unit Converter"])[2]

**Comment by mykola-mokhnach** [comment]
> yes the element present in the page source

this is not confirmed. It is necessary to get the page source right before the lookup is performed. The dynamic page source might be different from the static one generated by AD.

**Comment by baligit** [comment]
but if execute (new TouchAction(driver)).tap(115, 160).perform() than it click correctly on the page. That shows that i am on the right page

**Comment by mykola-mokhnach** [comment]
Simply provide the requested information.

**Comment by amedvedjev** [comment]
@baligit you code NOT equal what shows appium inspector.
check again what Appium inspector showed and what you wrote. You should quickly find typo in your code.

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by baligit** [comment]
I write exact the code form inspector. I have got the following error: 

Exception in thread "main" org.openqa.selenium.WebDriverException: Returned value cannot be converted to WebElement: {element-6066-11e4-a52e-4f735466cecf=33000000-0000-0000-D741-000000000000, ELEMENT=33000000-0000-0000-D741-000000000000}

**Comment by mykola-mokhnach** [comment]
^
This is the client issue. make sure it's up to date

**Comment by baligit** [comment]
It works now fine with the latest java-client. Thank you 

  <dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>7.3.0</version>
        </dependency>
