### ISSUE TITLE
Running Appium on port 80

### ISSUE THREAD

**Issue by amirl1086** [appium/appium#14292]
## The problem

Noticed that when running Appium on port 80 with cap: "browserName: Safari" - webdriverio doesn't pass the initialisation step and get stuck, once I change the port to let's say 3000 everything seems to be working fine.
This is producible only when using "browserName: Safari" in the caps, when using "app: com.apple.mobilesafari" on any port everything seems to be working fine.
I might be missing something but when changing the cap "app" to "browserName" it changes the logic of Appium to use the SafariLuncher? I couldn't find any reference that SafariLuncher app uses port 80.

## Environment

* Appium version 1.15.1 (1.15.1.20191013.2)
* Desktop OS/version used to run Appium: macOS Catalina, version 10.15.4
* Node.js version (unless using Appium.app|exe): v12.14.1
* Npm package manager: 6.13.4
* Mobile platform/version under test: 13.3
* Real device or emulator/simulator: iOS simulator
* Appium CLI or Appium.app|exe: N/A

## Link to Appium logs
[Appium with port 4723](https://gist.githubusercontent.com/amirl1086/fed74bddeae648cfa53b2d53b36ff1b3/raw/a931b661b245545cda07472e658a8b1ccff77e81/appium-server-logs-port-4723.txt)
[Appium with port 80](https://gist.githubusercontent.com/amirl1086/fed74bddeae648cfa53b2d53b36ff1b3/raw/a931b661b245545cda07472e658a8b1ccff77e81/appium-server-logs-port-80.txt)
[Node Webdriver-io output](https://gist.githubusercontent.com/amirl1086/fed74bddeae648cfa53b2d53b36ff1b3/raw/caf561c1bfcd8b02ce715915d256db72c6a6f6f2/node%2520webdriverio%2520output)

## Code To Reproduce Issue
const wdio = require('webdriverio');
  const device =  {
    "browserName": "Safari",
    "deviceName": "iPad Pro (9.7-inch)",
    "udid": "80E767D6-1B85-40EC-945B-A61ECE41EC97",
    "platformVersion": "13.3"
    "platformName": "iOS",
    "xcodeOrgId": "***",
    "xcodeSigningId": "iPhone Developer",
    "automationName":"XCUITest",
    "updatedWDABundleId": "WebDriverAgentRunner.jitp.test.run"
  };
const driver = await wdio.remote(device);

**Comment by mykola-mokhnach** [comment]
Ports below 1024 can only be assigned by a user with root permissions. 
Closed as not an issue.

**Comment by amirl1086** [comment]
Thank you @mykola-mokhnach
