### ISSUE TITLE
Failed to get PID for the following process: <packageName> (process name must be specified if not equal to package name)

### ISSUE THREAD

**Issue by praveenngp15** [appium/appium#14293]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Real device or emulator/simulator:  Real Device

## Details

Getting an error Failed to get PID for the following process: com.***.*** (process name must be specified if not equal to package name)

## Link to Appium logs
Same code working fine in emulator. But in a real device, I am getting above error message

                dc.setCapability("appPackage", "***");
		dc.setCapability("appActivity", "***");
		dc.setCapability("deviceName", "Realme5");
		dc.setCapability("platformName", "Android");
		dc.setCapability("noReset", true);
		dc.setCapability("uiautomator2ServerInstallTimeout", 90000); 
		dc.setCapability("showChromedriverLog", true); 
		dc.setCapability("autoWebview", true);
		
Is any other capability needed to fix this issue?

Appium Desktop version: v1.15.1

**Comment by mykola-mokhnach** [comment]
Sorry, we cannot help nothing without the server log

**Comment by praveenngp15** [comment]
Error Message : Error An unknown server-side error occurred while processing the command. Original error: An unknown server-side error occurred while processing the command. Original error: unknown error: Failed to get PID for the following process: com.testleaf.leaforg (process name must be specified if not equal to package name)
[appium-server-logs.txt](https://github.com/appium/appium/files/4588785/appium-server-logs.txt)

**Comment by mykola-mokhnach** [comment]
The error is coming from chromedriver itself. I would try to play with chromeOptions capability to make it working  and/or ask at chromedriver user gropus

**Comment by praveenngp15** [comment]
Can u share the link or chrome driver user group

**Comment by mykola-mokhnach** [comment]
https://groups.google.com/forum/#!forum/chromedriver-users

**Comment by mykola-mokhnach** [comment]
Please let us know if you get a working solution

Closed as third party issue.
