### ISSUE TITLE
Webdriver agent and XCODE build failure while running Appium inspector iOS

### ISSUE THREAD

**Issue by vineetsingh065** [appium/appium#14297]
## The problem

While running Appium inspector for simulator and real device on macOS getting WDA and Xcodebuild failure message.

## Environment

- Appium desktop version: 1.15
- MacOS: 10.15 catalina
- XCODE: 11.4
- iOS: 13

## Desired capabilities
   ```
 {
      "platformName": "ios",
      "platformVersion": "13.4.1",
      "deviceName": "iPhone SE",
      "udid": "E5C0BC6A-6C1E-4424-A94A-072108B1318B",
      "app": "/Users/pas_user/Downloads/pa-111.ipa",
      "automationName": "XCUITest",
    }
```
tried with "useNewWDA": true also did not work.

## Link to Appium logs

https://gist.github.com/vineetsingh065/e2e6527a8b3465411411c46b35de2860

**Comment by mykola-mokhnach** [comment]
> [warn] [XCUITest] Simulator architecture appears to be unsupported by the '/var/folders/v_/8p9x1n5j6h78h7qzxcs99vsh0000gn/T/202046-33258-bg5wo2.nk7v/Payload/abc.app' application. Make sure the correct deployment target has been selected for its compilation in Xcode.
> [warn] [XCUITest] Don't be surprised if the application fails to launch.

Closed as not an issue
