### ISSUE TITLE
iOS simulator won't launch after moving from iOS 12.2 to iOS 13.2

### ISSUE THREAD

**Issue by avrahams1** [appium/appium#14291]
## The problem

Hi,
Up until now, we've been running our tests using Appium 1.13.0 and iOS 12.2.
We're in the process of upgrading to Appium 1.16.0 and iOS 13.2.

For some reason, the iOS simulator can't even be opened when the session is created - I see the Simulator process being active, but the simulator never actually launches.

Furthermore, after a while, I'm just getting an error saying "xcodebuild exited with code '65' and signal 'null".

Not sure if these 2 problems are related or not, I couldn't find a solution online and I'm running the exact same app with the exact same capabilities.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0
* Last Appium version that did not exhibit the issue (if applicable): 1.13.0
* Desktop OS/version used to run Appium: Mac OS Catalina 10.15.4
* Node.js version (unless using Appium.app|exe): 10.9.0
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: 13.2
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Details

I made sure the logs are referring to the correct device ID, the same device I can consistently start from XCode and run my app in, is detected and used by Appium, judging by the logs.

## Link to Appium logs

https://gist.github.com/avrahams1/ae3b2e52b80129b1945a2e24572955c5

## Code To Reproduce Issue [ Good To Have ]

Just starting a session [with the simplest capabilities](https://gist.github.com/avrahams1/19a3337c2fea2bc7c07904b04c7d4754).

**Comment by KazuCocoa** [comment]
>  the simulator never actually launches.

Do you mean you could not see the simulator UI on the machine?
Sometimes Xcode 11 does not show the UI while the simulator instance is running, so it may affect the situation. (I forgot, but it was Xcode side's preference...)

As Appium, the instance seemed working.
> [35m[iOSSim][39m Both Simulator with UDID 7A49B13E-2799-4387-B1CA-B9EFB93641FE and the UI client are currently running


Could you share the log with `showXcodeLog: true`?

> [debug] [35m[XCUITest][39m Output from xcodebuild will only be logged if any errors are present there. To change this, use 'showXcodeLog' desired capability

**Comment by avrahams1** [comment]
>> Do you mean you could not see the simulator UI on the machine?
Yes.
This never happened prior to the iOS upgrade, I've been the latest XCode regardless.
Any idea how to fix that?

>> Could you share the log with showXcodeLog: true?
Sure, [here](https://gist.github.com/avrahams1/5d7e9bd3f6965a59a13f13144f8c10ae).

**Comment by KazuCocoa** [comment]
When I faced the situation, launch simulator via Xcode a couple of times and reboot the host machine. Then, not sure when, but simulators appeared by default.

Thanks for the log. checking

**Comment by KazuCocoa** [comment]
Could you try the latest Appium for the latest Xcode?
1.17.0 has a couple of fixes for Xcode 11.4

**Comment by avrahams1** [comment]
It works!
I upgraded to @latest and it works.

I'm still running into the issue of the simulator opening somewhere off-screen, it happens ONLY when Appium launches it, XCode works just fine.
Any ideas how to deal with that?

**Comment by KazuCocoa** [comment]
Maybe it happens when you launch simulator via CLI.
Probably, if you already launch simulators on screen, then the CLI one also can launch on screen simulator. (Then, maybe the onscreen will be the default behaviour, I guess...)

**Comment by dpgraham** [comment]
This is fixed with a PR to appium-ios-simulator

Will be in next Appium version.
