### ISSUE TITLE
Cannot get page source

### ISSUE THREAD

**Issue by PetrPirozhenko** [appium/appium#14308]
## The problem

Can not get Page source on some desktop pages

## Environment

* Appium version 1.17.1
* Desktop OS/version used to run Appium: MacOS Majave version 10.14.6

## Link to Appium logs

https://gist.github.com/PetrPirozhenko/3503f3a696ff78fb99a9f76ad29b269b

**Comment by KazuCocoa** [comment]
Probably https://github.com/appium/appium-for-mac crashed.
Can we reproduce the error in Apple's official app etc?
Need to dig the cause...

**Comment by jin1ming** [comment]
I encountered the same problem, is there any progress so far?

**Comment by KazuCocoa** [comment]
No, since we do not have a proper app.

>  Can we reproduce the error in Apple's official app etc?

**Comment by kalyan7h** [comment]
I encounter a similar issue. Is there any fix? One observation Seeing it mainly on appium v1.17 or greater & IOS platform version 13 or more.

**Comment by mykola-mokhnach** [comment]
Closed because there is no way to fix the error without the having the actual app under test and exact steps to reproduce it locally
