### ISSUE TITLE
Appium-WinAppDriver missing important capabilities from WinAppDriver?

### ISSUE THREAD

**Issue by samuelfreiberg** [appium/appium#14303]
## The problem

WinAppDriver, the Windows driver for Appium, contains a capability crucial to my project called 'appArguments' ([found here](https://github.com/microsoft/WinAppDriver/blob/master/Docs/AuthoringTestScripts.md)), however, when I try to add this capability with Appium, my app doesn't work and the Appium logs state "The following capabilities were provided, but not recognized by Appium: appArguments".

I then went to the appium/appium-windows-driver GitHub, and the ReadMe says the only WindowsDriver-specific capabilities are "createSessionTimeout". Does this mean that Appium doesn't support most WinAppDriver capabilities? Why is this? Or am I doing something wrong? I'm doing this with WebDriverIO.

## Environment

Appium: v1.17.1
NodeJS: v10.20
WebdriverIO: v5.18.0

## Link to Appium logs

The project I'm working on has special security requirements, unfortunately I cannot post a link to the logs, but I will post the important part here: 
[35m[Appium][39m Appium v1.17.1 creating new WindowsDriver (v1.12.1) session
[debug] [35m[BaseDriver][39m Creating session with MJSONWP desired capabilities: {
[debug] [35m[BaseDriver][39m   "platformName": "windows",
[debug] [35m[BaseDriver][39m   "deviceName": "WindowsPC",
[debug] [35m[BaseDriver][39m   "app": "path",
[debug] [35m[BaseDriver][39m   "appArguments": "args"
[35m[BaseDriver][39m The following capabilities were provided, but are not recognized by Appium:   appArguments

**Comment by mykola-mokhnach** [comment]
This message simply means the capability name is not known to Appium driver (it should be explicitly stated in `desired-caps` module). Although it is still passed to the downstream server

**Comment by mykola-mokhnach** [comment]
Closed because of no response
