### ISSUE TITLE
Configure dependabot to not PR for in-range

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#14304]
## The problem

Dependabot is making pull requests every time an in-range dependency has been updated. This is overwhelming our CI services, because pull requests trigger more comprehensive tests than just a normal branch. 

We should configure it (if it's possible) so that it only makes a PR if an out-of-range update is made. In-range updates should do like greenkeeper and just create a branch that gets deleted once CI passes for it.

**Comment by mykola-mokhnach** [comment]
Looks like this has been fixed in dependabot
