### ISSUE TITLE
Errors running Appium-python pytest, mainly urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session : Failed to establish a new connection:

### ISSUE THREAD

**Issue by jeromedejaegher** [appium/appium#14311]
## The problem

Initially, my scripts are stuck in line :

```
self.driver = webdriver.Remote('http://{}:{}/wd/hub'.format(self.appium_ip_address,
                                                               self.appium_port),
                                       desired_capabilities=desired_caps)
```

Sometimes, it works, and most of the time, Appium desktop succeed in conncting the application, but occasionnaly, Appium desktop says he cannot connect because the app crashed, please see logcat (but the app doesn't launch, for two different apps).

Anyway, this makes me suspect a problem with appium, and I decided to control installation tests ([here](https://github.com/appium/appium/tree/master/sample-code/python)) and I got a 17 errors, 4 failed, which is not so good for 21 tests.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: windows 10/ Anaconda distrib/python 3.7.7
* Node.js version (unless using Appium.app|exe): 12.16.3
* Npm or Yarn package manager: npm 6.14.4
* Mobile platform/version under test: android 10, nexus 5, api 29
* Real device or emulator/simulator: emu
* Appium CLI or Appium.app|exe:

## Details

As most of the log lines refers to errors in urllib3, I tried to upgrade urllib3, but this makes no difference in the result of the test.

I also tried to run the test with and without a emulator running, without difference

Anyway, I would thank you to help me understand what is wrong with my configuration, and help me succeed in running these tests successfully.

## Link to Appium logs

Full log is attached
[log_test.txt](https://github.com/appium/appium/files/4604375/log_test.txt)

## Code To Reproduce Issue [ Good To Have ]

[sample code from appium github](https://github.com/appium/appium/tree/master/sample-code/python)

**Comment by shibupanda** [comment]
Hi @jeromedejaegher 
It seems you have attached console error logs. It's great if you can share complete appium server logs using gist which can help us to debug.

**Comment by jeromedejaegher** [comment]
Hi @shibupanda , thank you for helping.

Here is my appium server log, and thanks to your asking, I have now 5 tests passed over 21.
I guess some tests are "normal to fail", as I don't have an iOS emulator.

Looking at the console log, the 3 abnormal results I find are:
- 'sauce' is not defined
- assert error '3 is not 5' and
- assert error 'True is not False'.

What can I do to debug this ? 
Thanks for your help,

console error logs : 
[console_log_test.txt](https://github.com/appium/appium/files/4604929/console_log_test.txt)

appium server log : 
[appium.log](https://github.com/appium/appium/files/4604930/appium.log)


Jerome.

PS : 
For the beginners like me, to complete [the sample-code page](https://github.com/appium/appium/blob/master/sample-code/python/README.md) : 
to run the tests on windows, we have to : 
- launch appium (cmd : appium --log-timestamp --log C:\Temp\appium.log)
- launch a avd with Android 8 (through Android Studio AVD, for exampleà
- and on another cmd window, launch "py.test test"

**Comment by shibupanda** [comment]
@jeromedejaegher Is this the latest logs you have as I have seen many errors regarding configuration. Let me point out those.
>[W3C] Encountered internal error running command: Error: Could not find a connected Android device in 21705ms.

Looks like device is not dected in adb.
> 2020-05-09 23:52:09:126 [HTTP] <-- DELETE /wd/hub/session/a8dfb2fc-6bd3-455b-9d5d-111ef45b15fd 200 208 ms - 14
2020-05-09 23:52:09:128 [HTTP] 
2020-05-09 23:52:09:254 [Instrumentation] Time: 4.064
2020-05-09 23:52:09:255 [Instrumentation] 
2020-05-09 23:52:09:255 [Instrumentation] OK (1 test)
2020-05-09 23:52:09:281 [Instrumentation] The process has exited with code 0
2020-05-09 23:52:14:123 [HTTP] --> GET /wd/hub/session/a8dfb2fc-6bd3-455b-9d5d-111ef45b15fd/title
2020-05-09 23:52:14:125 [HTTP] {}
2020-05-09 23:52:14:130 [W3C (a8dfb2fc)] Encountered internal error running command: NoSuchDriverError: A session is either terminated or not 

You are trying to get the title after delete the session. You should initiate the driver again.

>[Chromedriver] Error: No Chromedriver found that can automate Chrome '58.0.3029'

Please use compatible version chrome driver.

>[Xcode] Could not find path to Xcode by symlinks located in /var/db/xcode_select_link, or /usr/share/xcode-select/xcode_dir_link

Looks like xocode is not selected use xcode-select to select the required xcode version

**Comment by mykola-mokhnach** [comment]
The log is very messy and big, although I don't observe any server issues there. All the errors are expected reactions to valid issues, which must be fixed on the client side.

**Comment by jeromedejaegher** [comment]
Yes, thank you for your help.
After cleaning a part of the mess, I pass 6 tests from the [appium pytest page](https://github.com/appium/appium/tree/master/sample-code/python).

What I have learnt :
- how to get log from appium server (see my previous answer, thanx  @shibupanda ), how to get logcat from the emulator to debug
- how to configure, start and terminate in a cleaner way the different components (appium, webdriver, emulator/adb)

I have installed chromedriver, but still get the error. Will investigate later, if I need this feature.

Thank you for your time. I upload the last logs, for you to see the improvement, and also because I suspect the two last tests to fail because of the scripts itself (wrong expected exception when connecting an ended session, and wrong number of items in the menubar). And the output directory are created by the tests, but not the output logs/screenshots. Just in case you have to work on it, but I guess you already have other prioritary tasks ;).

Have a nice day.

[console_log_test.txt](https://github.com/appium/appium/files/4606516/console_log_test.txt)
[appium5.log](https://github.com/appium/appium/files/4606521/appium5.log)
