### ISSUE TITLE
Appium page source prints accessibility_id/id as "name"

### ISSUE THREAD

**Issue by NirBY** [appium/appium#14325]
## The problem

Appium page source prints accessibility_id/id has "name".
I also saw you already familiar with this issue since 2017 [https://github.com/appium/appium-desktop/issues/277](url) 

Will you going to fix it?
If you like an examples please let me know.

## Environment

* Appium version (or git revision) that exhibits the issue: V1.17.1
* Last Appium version that did not exhibit the issue (if applicable):none
* Desktop OS/version used to run Appium: MAC
* Node.js version (unless using Appium.app|exe):10.16.3
* Npm or Yarn package manager:Npm
* Mobile platform/version under test:IOS
* Real device or emulator/simulator:Real
* Appium CLI or Appium.app|exe:Appium.app, using Java client ver7.3.0

## Details

Please let me know if examples needed.

## Link to Appium logs

No need page source return successfully, attribute data is incorrect only.

## Code To Reproduce Issue [ Good To Have ]

Happens all the time.

**Comment by mykola-mokhnach** [comment]
No, we are not going to change that, since this is going to break the backward compatibility.

We could add an alias for getAttribute call to return `name` if `id` is requested, but I currently don't see a need in that.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by NirBY** [comment]
I don't understand why adding new attribute to element source (e.g. "accessibility_id"), will risk backward compatibility..

**Comment by mykola-mokhnach** [comment]
Adding a new attribute won't break anything, although I don't see much sense in having two attributes with duplicated values. We've never tried to unify xml/xpath. It's platform dependent and it's fine the actual attribute names are different for different platforms.

@jlipps @KazuCocoa Would you like to comment more on this issue?

**Comment by jlipps** [comment]
I've thought that a better overall solution would be to have a unified set of UI class names, that is opt-in via capability or setting. In this new mode, we would use generic class names and map each of android / ios / etc class names and attributes to one of those generic class names and attributes. It's technically straightforward but just requires some careful thinking to make sure we do the mapping right.
