### ISSUE TITLE
UiScrollable fails after one swipe

### ISSUE THREAD

**Issue by QAthulhu** [appium/appium#14329]
## The problem

I'm running tests on a search page and I'm trying to scroll using UiScrollable, but the scrolling stops after one swipe even if it has not reached the end of the page. This only occurs on one page, all other scrollable elements work fine. It swipes on the screen once, then a NoSuchElementException is thrown because the search text I provided was not found. If the text I provided can be found in one swipe, it will work.

Element class: androidx.recyclerview.widget.RecyclerView
It's the only element on the page with Scrollable = true.

Here is the command I used:
```
String selector = "new UiScrollable(new UiSelector().scrollable(true)).scrollIntoView(new UiSelector().textContains(\"Test Group\"))";
driver.findElementByAndroidUIAutomator(selector);
```

I added a `scrollForward(3)` before the `scrollIntoView`, and it scrolled forward, then backward (which is expected because `scrollIntoView` must start at the beginning of the scrollable object). What was strange was that the scrolling backwards stopped at around the same location where "first swipe" that normally occurs ends, and then started from there. So it looks like there are two scrollable elements on top of each other, but inspecting with UiAutomatorViewer only shows one.

The scrollable element is the androidx.recyclerview.widget.RecyclerView and under it are multiple LinearLayout elements, each acting as a container for each search result. 
## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0
* Desktop OS/version used to run Appium: macOS X Mojave
* Node.js version (unless using Appium.app|exe): 12.11.1
* Npm or Yarn package manager: 6.11.3
* Mobile platform/version under test: Android 9, 10
* Real device or emulator/simulator: Google Pixel emulator and Samsung Galaxy J8
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
Log for failing after one swipe
https://gist.github.com/QAthulhu/8255c6e81f161bbe145d68c25d7af78b

Log for same script but with added scrollForward to "skip" the first swipe
`String selector = "new UiScrollable(new UiSelector().scrollable(true)).scrollForward(3).scrollIntoView(new UiSelector().textContains(\"Test Group\"))";`
https://gist.github.com/QAthulhu/7ad6e53ba0b6dba634a41b5a07201644

Note: the 2nd log also shows a failure because my search text "Test Group" doesn't actually exist on screen, but if I used something that did, it be found successfully in the second log, while the exception would only occur in the first log.

## Code To Reproduce Issue [ Good To Have ]

It's just the UiScrollable/Selector I used.

**Comment by amedvedjev** [comment]
@QAthulhu try to increase "setMaxSearchSwipes()"

**Comment by mykola-mokhnach** [comment]
These swipes are controlled by UiAutomator itself. Make sure your lookup query is correct.

**Comment by QAthulhu** [comment]
I've tried setting max search swipes to 100 but it still fails after the first swipe. 

I'm not sure what else I can change about the selector, it's as simple and straightforward as I could get it to be

**Comment by mykola-mokhnach** [comment]
Consider reporting the issue to Google. 

You could try to perform touch actions as a workaround.

**Comment by QAthulhu** [comment]
Found a work around. I put the my selector in a try-catch for NoSuchElementException, if caught, I run the same selector except with an added scrollForward so it skips the first swipe.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by grebenkovia** [comment]
@QAthulhu can you send your code?

**Comment by QAthulhu** [comment]
@grebenkovia I eventually settled on using TouchAction and a while loop to check if an element is displayed. I'm no longer working on that project but this is pretty much how it went:
```
while(!isElementDisplayed(locator)) {
    swipeUp()
}
```
I found UIScrollable to be very inconsistent and pretty much migrated to TouchAction on all my scroll methods except for a few small lists. My advice, if UIScrollable doesn't work once because of an issue like this, save yourself the time and effort and migrate straight to TouchAction
