### ISSUE TITLE
[Feature request] Select picker wheel by string value for iOS

### ISSUE THREAD

**Issue by idxn** [appium/appium#14322]
## The problem

Using mobile:selectPickerWheelValue is quite a pain if the wheel has plenty of values and the sendKeys does not work. 

## Details
I'm not sure we can leverage adjustToPickerWheelValue from https://developer.apple.com/documentation/xctest/xcuielement/1618672-adjusttopickerwheelvalue?language=objc or not.

**Comment by mykola-mokhnach** [comment]
sendKeys call already does this depending on the target element type. If it does not work then either an incorrect element is selected or the downstream XCTest method is buggy.

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/WebDriverAgent/blob/4d01ba704fd95257c6e25503ba579006acd1c35f/WebDriverAgentLib/Commands/FBElementCommands.m#L221

**Comment by idxn** [comment]
@mykola-mokhnach Thanks @mykola-mokhnach. I'll check my script again.
