### ISSUE TITLE
Some default functions don't work in InteractsWithApps interface

### ISSUE THREAD

**Issue by carrigmore** [appium/appium#14324]
The problem

Several functions defined in InteractsWithApps interface doesn't work while testing app running on iOS 13.3 with Appium 

## Environment

* Appium version 1.17.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: macOS Mojave 10.14.6
* Node.js version (unless using Appium.app|exe): 10.15.0
* Npm or Yarn package manager: 6.4.1
* Mobile platform/version under test: iOS 13.3
* Real device or emulator/simulator: Simulator 11.3.1 
* Appium CLI or Appium.app|exe: 1.15.1

Details

the following functions defined in InteractsWithApps interface doesn't work at all:

default void resetApp() {
        execute(RESET);
    }

default void closeApp() {
        execute(CLOSE_APP);
    }

the following method works but only partly. (App is put to background but never come back to frontend after timeout duration. Had to put a sleep around 1 seconds before calling this function to make it work. 

default void runAppInBackground(Duration duration) {
        execute(RUN_APP_IN_BACKGROUND, ImmutableMap.of("seconds", duration.toMillis() / 1000.0));
    }

## Code To Reproduce Issue [ Good To Have ]

@And("I reset the application")
  public void resetApplication() {
 homePage. resetApplicaton();
  }

// how resetApplication () looks like:
public void resetApplicaton() {
    driver.resetApp();
    logger.info("reset Application");
  }

**Comment by mykola-mokhnach** [comment]
What exactly does not work? Please provide the full server log and point out what is the actual and the expected result there.

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by carrigmore** [comment]
@mykola-mokhnach hi I will add server log and actual expected result here.

**Comment by carrigmore** [comment]
Thanks mokhnach, I will debug the same test again today and attach the server log here.

**Comment by carrigmore** [comment]
log from Appium server while running closeApp()
[HTTP] 
[HTTP] --> POST /wd/hub/session/0178bb0d-8aa2-4d3c-a0fe-15046f619ddc/appium/app/close
[HTTP] {}
[debug] [W3C (0178bb0d)] Calling AppiumDriver.closeApp() with args: ["0178bb0d-8aa2-4d3c-a0fe-15046f619ddc"]
[debug] [XCUITest] Executing command 'closeApp'
[debug] [WD Proxy] Matched '/session/0178bb0d-8aa2-4d3c-a0fe-15046f619ddc' to command name 'deleteSession'
[debug] [WD Proxy] Proxying [DELETE /session/0178bb0d-8aa2-4d3c-a0fe-15046f619ddc] to [DELETE http://127.0.0.1:8100/session/6CBBDEF0-F66C-4EB5-B2E3-E68A5E61DABE] with no body
[debug] [WD Proxy] Got response with status 200: {
[debug] [WD Proxy]   "value" : null,
[debug] [WD Proxy]   "sessionId" : "E82B1882-8F68-4CB0-A284-682AF66E6D72"
[debug] [WD Proxy] }
[DevCon Factory] Releasing connections for 2A9411A8-6406-44C2-ADDB-C0DEF1371144 device on any port number
[DevCon Factory] Found cached connections to release: ["2A9411A8-6406-44C2-ADDB-C0DEF1371144:8100"]
[debug] [DevCon Factory] Cached connections count: 0
[iOS] Successfully closed the 'undefined' app.
[debug] [W3C (0178bb0d)] Responding to client with driver.closeApp() result: null
[HTTP] <-- POST /wd/hub/session/0178bb0d-8aa2-4d3c-a0fe-15046f619ddc/appium/app/close 200 4 ms - 14
[HTTP] 
[HTTP] --> POST /wd/hub/session/0178bb0d-8aa2-4d3c-a0fe-15046f619ddc/appium/app/close
[HTTP] {}
[debug] [W3C (0178bb0d)] Calling AppiumDriver.closeApp() with args: ["0178bb0d-8aa2-4d3c-a0fe-15046f619ddc"]
[debug] [XCUITest] Executing command 'closeApp'
[debug] [WD Proxy] Matched '/session/0178bb0d-8aa2-4d3c-a0fe-15046f619ddc' to command name 'deleteSession'
[debug] [WD Proxy] Proxying [DELETE /session/0178bb0d-8aa2-4d3c-a0fe-15046f619ddc] to [DELETE http://127.0.0.1:8100/session/6CBBDEF0-F66C-4EB5-B2E3-E68A5E61DABE] with no body
[WD Proxy] Got response with status 404: {
[WD Proxy]   "value" : {
[WD Proxy]     "error" : "invalid session id",
[WD Proxy]     "message" : "Session does not exist",
[WD Proxy]     "traceback" : "(\n\t0   CoreFoundation                      0x00007fff23c7127e __exceptionPreprocess + 350\n\t1   libobjc.A.dylib                     0x00007fff513fbb20 objc_exception_throw + 48\n\t2   CoreFoundation                      0x00007fff23c70e49 -[NSException raise] + 9\n\t3   WebDriverAgentLib                   0x000000010ae1dd87 -[FBRoute raiseNoSessionException] + 103\n\t4   WebDriverAgentLib                   0x000000010ae1dca6 -[FBRoute decorateRequest:] + 294\n\t5   WebDriverAgentLib                   0x000000010ae1d0ae -[FBRoute_TargetAction mountRequest:intoResponse:] + 94\n\t6   WebDriverAgentLib                   0x000000010ae0849b __37-[FBWebServer registerRouteHandlers:]_block_invoke + 555\n\t7   RoutingHTTPServer                   0x000000010af0eb8f -[RoutingHTTPServer handleRoute:withRequest:response:] + 136\n\t8   RoutingHTTPServer                   0x000000010af0f4a2 __72-[RoutingHTT...
[debug] [W3C] Matched W3C error code 'invalid session id' to NoSuchDriverError
[debug] [XCUITest] Unable to DELETE session on WDA: 'Session does not exist'. Continuing shutdown.
[DevCon Factory] Releasing connections for 2A9411A8-6406-44C2-ADDB-C0DEF1371144 device on any port number
[DevCon Factory] No cached connections have been found
[iOS] Successfully closed the 'undefined' app.
[debug] [W3C (0178bb0d)] Responding to client with driver.closeApp() result: null
[HTTP] <-- POST /wd/hub/session/0178bb0d-8aa2-4d3c-a0fe-15046f619ddc/appium/app/close 200

**Comment by carrigmore** [comment]
Last login: Wed May 13 09:13:21 on ttys001
C02Z59M8LVCF:dynamo-e2e-ui i741130$ vim




































  9 [debug] [W3C (3e0cc301)]     at Route.dispatch (/Users/ixxxxxx/.npm-packages/lib/node_modules/ap    pium/node_modules/express/lib/router/route.js:112:3)
 10 [debug] [W3C (3e0cc301)]     at Layer.handle [as handle_request] (/Users/ixxxxxx/.npm-packages/l    ib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
 11 [debug] [W3C (3e0cc301)]     at /Users/ixxxxxx/.npm-packages/lib/node_modules/appium/node_module    s/express/lib/router/index.js:281:22
 12 [debug] [W3C (3e0cc301)]     at param (/Users/ixxxxxx/.npm-packages/lib/node_modules/appium/node    _modules/express/lib/router/index.js:354:14)
 13 [debug] [W3C (3e0cc301)]     at param (/Users/ixxxxxx/.npm-packages/lib/node_modules/appium/node    _modules/express/lib/router/index.js:365:14)
 14 [debug] [W3C (3e0cc301)]     at Function.process_params (/Users/ixxxxxx/.npm-packages/lib/node_m    odules/appium/node_modules/express/lib/router/index.js:410:3)
 15 [debug] [W3C (3e0cc301)]     at next (/Users/ixxxxxx/.npm-packages/lib/node_modules/appium/node_    modules/express/lib/router/index.js:275:10)
 16 [debug] [W3C (3e0cc301)]     at logger (/Users/ixxxxxx/.npm-packages/lib/node_modules/appium/nod    e_modules/morgan/index.js:144:5)
 17 [debug] [W3C (3e0cc301)]     at Layer.handle [as handle_request] (/Users/ixxxxxx/.npm-packages/l    ib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
 18 [debug] [W3C (3e0cc301)]     at trim_prefix (/Users/ixxxxxx/.npm-packages/lib/node_modules/appiu    m/node_modules/express/lib/router/index.js:317:13)
 19 [debug] [W3C (3e0cc301)]     at /Users/ixxxxxx/.npm-packages/lib/node_modules/appium/node_module    s/express/lib/router/index.js:284:7
 20 [debug] [W3C (3e0cc301)]     at Function.process_params (/Users/ixxxxxx/.npm-packages/lib/node_m    odules/appium/node_modules/express/lib/router/index.js:335:12)
 21 [debug] [W3C (3e0cc301)]     at next (/Users/ixxxxxx/.npm-packages/lib/node_modules/appium/node_    modules/express/lib/router/index.js:275:10)
 22 [debug] [W3C (3e0cc301)]     at /Users/ixxxxxx/.npm-packages/lib/node_modules/appium/node_module    s/body-parser/lib/read.js:130:5
 23 [debug] [W3C (3e0cc301)]     at invokeCallback (/Users/ixxxxxx/.npm-packages/lib/node_modules/ap    pium/node_modules/raw-body/index.js:224:16)
 24 [debug] [W3C (3e0cc301)]     at done (/Users/ixxxxxx/.npm-packages/lib/node_modules/appium/node_    modules/raw-body/index.js:213:7)
 25 [debug] [W3C (3e0cc301)]     at IncomingMessage.onEnd (/Users/ixxxxxx/.npm-packages/lib/node_mod    ules/appium/node_modules/raw-body/index.js:273:7)
 26 [debug] [W3C (3e0cc301)]     at IncomingMessage.emit (events.js:182:13)
 27 [debug] [W3C (3e0cc301)] Destroying socket connection
 28 [HTTP] <-- POST /wd/hub/session/3e0cc301-3e93-4b49-aae3-54d9c0077261/appium/app/reset 404 13 ms     - 2812
 29 [HTTP]

**Comment by carrigmore** [comment]
Log message when trying to resetApp()

[HTTP] --> POST /wd/hub/session/3e0cc301-3e93-4b49-aae3-54d9c0077261/appium/app/reset
[HTTP] {}
[debug] [W3C (3e0cc301)] Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started
[debug] [W3C (3e0cc301)]     at asyncHandler (/Users/ixxxxxx/.npm-packages/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:255:15)
[debug] [W3C (3e0cc301)]     at app.(anonymous function) (/Users/ixxxxxx/.npm-packages/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:447:15)
[debug] [W3C (3e0cc301)]     at Layer.handle [as handle_request] (/Users/ixxxxxx/.npm-packages/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [W3C (3e0cc301)]     at next (/Users/ixxxxxx/.npm-packages/lib/node_modules/appium/node_modules/express/lib/router/route.js:137:13)
[debug] [W3C (3e0cc301)]     at Route.dispatch (/Users/ixxxxxx/.npm-packages/lib/node_modules/appium/node_modules/express/lib/router/route.js:112:3)
[debug] [W3C (3e0cc301)]     at Layer.handle [as handle_request] (/Users/ixxxxxx/.npm-packages/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [W3C (3e0cc301)]     at /Users/ixxxxxx/.npm-packages/lib/node_modules/appium/node_modules/express/lib/router/index.js:281:22
[debug] [W3C (3e0cc301)]     at param (/Users/ixxxxxx/.npm-packages/lib/node_modules/appium/node_modules/express/lib/router/index.js:354:14)
[debug] [W3C (3e0cc301)]     at param (/Users/ixxxxxx/.npm-packages/lib/node_modules/appium/node_modules/express/lib/router/index.js:365:14)
[debug] [W3C (3e0cc301)]     at Function.process_params (/Users/ixxxxxx/.npm-packages/lib/node_modules/appium/node_modules/express/lib/router/index.js:410:3)
[debug] [W3C (3e0cc301)]     at next (/Users/ixxxxxx/.npm-packages/lib/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[debug] [W3C (3e0cc301)]     at logger (/Users/ixxxxxx/.npm-packages/lib/node_modules/appium/node_modules/morgan/index.js:144:5)
[debug] [W3C (3e0cc301)]     at Layer.handle [as handle_request] (/Users/ixxxxxx/.npm-packages/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [W3C (3e0cc301)]     at trim_prefix (/Users/ixxxxxx/.npm-packages/lib/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
[debug] [W3C (3e0cc301)]     at /Users/ixxxxxx/.npm-packages/lib/node_modules/appium/node_modules/express/lib/router/index.js:284:7
[debug] [W3C (3e0cc301)]     at Function.process_params (/Users/ixxxxxx/.npm-packages/lib/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
[debug] [W3C (3e0cc301)]     at next (/Users/ixxxxxx/.npm-packages/lib/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[debug] [W3C (3e0cc301)]     at /Users/ixxxxxx/.npm-packages/lib/node_modules/appium/node_modules/body-parser/lib/read.js:130:5
[debug] [W3C (3e0cc301)]     at invokeCallback (/Users/ixxxxxx/.npm-packages/lib/node_modules/appium/node_modules/raw-body/index.js:224:16)
[debug] [W3C (3e0cc301)]     at done (/Users/ixxxxxx/.npm-packages/lib/node_modules/appium/node_modules/raw-body/index.js:213:7)
[debug] [W3C (3e0cc301)]     at IncomingMessage.onEnd (/Users/ixxxxxx/.npm-packages/lib/node_modules/appium/node_modules/raw-body/index.js:273:7)
[debug] [W3C (3e0cc301)]     at IncomingMessage.emit (events.js:182:13)
[debug] [W3C (3e0cc301)] Destroying socket connection
[HTTP] <-- POST /wd/hub/session/3e0cc301-3e93-4b49-aae3-54d9c0077261/appium/app/reset 404 2 ms - 2812

**Comment by mykola-mokhnach** [comment]
[Here](https://github.com/appium/appium/issues/14324#issuecomment-627930579) closeApp is called twice and the result is expected. Calling closeApp is internally equal to closing the session completely. Also resetApp closes the session and starts it again. 

In general, my point is these APIs are implicit, legacy and should be avoided at any cost. There are better ways to close an app and start it again without killing the session.

**Comment by carrigmore** [comment]
Hi @mykola-mokhnach, in the Xcode simulator, it doesn't close the app when call the function closeApp, app is still running at front ground. And same with resetApp, app still running at front ground, nothing happens. Would expect the app getting closed/ reset after calling these functions? When calling runAppInBackground, it put app to background as expected but app doesn't come back to front ground after specified time of seconds.

**Comment by mykola-mokhnach** [comment]
Consider calling terminateApp instead

**Comment by carrigmore** [comment]
I can try that one but as those mentioned functions are not working as expected then it is a bug, is my understanding correct? I see you put NotABug label on the issue

**Comment by mykola-mokhnach** [comment]
Marking it as bug does not solve anything. These function are legacy cargo. It would be easier to completely delete them rather than trying to fix that mess.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
