### ISSUE TITLE
Unable to execute webview_chrome context, with waitfor Displayed and click on 81.0.4044.138 chrome browser.

### ISSUE THREAD

**Issue by dipti-code** [appium/appium#14333]
## The problem
Unable to execute webview_chrome context, with waitfor Displayed and click on 81.0.4044.138 chrome browser.

error: 'no such element',
  message: 'no such element: Unable to locate element: {"method":"css selector","selector":"#Username"}\n' +
    '  (Session info: chrome=81.0.4044.138)',

In iOS same code working fine.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac
* Node.js version (unless using Appium.app|exe): 12.12.7
* Npm or Yarn package manager:
* Mobile platform/version under test: Google Pixel 3
* Real device or emulator/simulator: emulator and real , both
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by KazuCocoa** [comment]
Could you attach the full Appium log to understand the context?

**Comment by mykola-mokhnach** [comment]
Have you also checked the actual page source before executing the lookup? Is the destination element present there?

**Comment by dipti-code** [comment]
Yes, i have checked that also but still its not able to enter that username. because am able to do the same thing with android, without any problem.

> Have you also checked the actual page source before executing the lookup? Is the destination element present there?

**Comment by mykola-mokhnach** [comment]
Please provide that source and the server log with the failure

**Comment by dipti-code** [comment]
attached.
[wdio-appium.log](https://github.com/appium/appium/files/4624017/wdio-appium.log)

**Comment by dipti-code** [comment]
> attached.
> [wdio-appium.log](https://github.com/appium/appium/files/4624017/wdio-appium.log)

**Comment by mykola-mokhnach** [comment]
are you sure this is the correct log? I don't see any lookup requests there. Also, I'm still waiting for the page source

**Comment by dipti-code** [comment]
yes you are correct, am going to attached the log tomorrow. as my login servers are down.

**Comment by dipti-code** [comment]
> are you sure this is the correct log? I don't see any lookup requests there. Also, I'm still waiting for the page source

what page source you are refering to. actually i have a page, and if iclick on that page for login, then another chrome page opens up, which has username and password field.

**Comment by mykola-mokhnach** [comment]
I mean the xml page tree generated based on DOM

**Comment by dipti-code** [comment]
i fixed a, error from my side
