### ISSUE TITLE
Unable to accept safari browser alerts with appium#1.17.1

### ISSUE THREAD

**Issue by sunilpatro1985** [appium/appium#14338]
## Issue 
With the Appium 1.17.1, I am trying to  accept the alert, but appium took long time and operation timed out

## Environment

* Appium Java-client : 7.3.0
* MacOS : 10.14.6
* Mobile platform/version under test: iPhone 11 Pro Max, 13.3
* Real device or emulator/simulator: simulator
* Appium CLI :  1.17.1

## Details
I am using a static html site, clicking on an alert button, alert pops up and accepting alert on Mac OS, Appium with Java
I can see the alert text on the logs, but unable to accept the alert, it took around 2-3 minutes and then returned error.
Note - I tried to switch to context NATIVE_APP and identified the element and clicked, but it din't on the alert close button.

![image](https://user-images.githubusercontent.com/5129954/81984132-fb3fc800-9651-11ea-9866-3e4d21d411dd.png)

## Link to Appium logs
[AppiumLogs](https://gist.github.com/sunilpatro1985/3d409343cc0b38f588f99bf43aac2408)

## Code 

    public class SafariTest {

    static DesiredCapabilities cap;
    static IOSDriver<MobileElement> driver;

    public static void main(String []args) throws MalformedURLException, InterruptedException, 
    MalformedURLException {
        cap = new DesiredCapabilities();
        cap.setCapability("platformName", "iOS");
        cap.setCapability("deviceName", "iPhone 11 Pro Max");
        cap.setCapability(MobileCapabilityType.PLATFORM_VERSION, "13.3");
        cap.setCapability("automationName", "XCUITest");
        cap.setCapability("browserName", "safari");
        cap.setCapability("safariAllowPopups", true);

        driver = new IOSDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"), cap);
        AppDriver.setDriver(driver);

        driver.get("https://qavbox.github.io/demo/signup/");

        Thread.sleep(2000);
   
        driver.findElement(By.id("submit")).click();
        Thread.sleep(1000);
        driver.switchTo().alert().accept();

        Thread.sleep(2000);
        driver.quit();
    }
}`

**Comment by KazuCocoa** [comment]
Could you share the page_source, too? Native context and webview context will help.

**Comment by sunilpatro1985** [comment]
Here is the [page source](https://gist.github.com/sunilpatro1985/effb570660ebd2e1a8fe475b7fa3f072)

It's a pure webview context, 

- I am just navigating to a static html site - [BrowserAlert](qavbox.github.io/demo/signup) 
- clicking on the submit button which triggers the alert
- Now accept the alert 

Issue - 
Appium stuck at line 
`driver.switchTo().alert().accept();`

Let me know if you need any other info!

**Comment by KazuCocoa** [comment]
I tried the webpage. How about doing it below command in native context?

```
@driver.find_element(:name, 'Submit').click
@driver.find_element(:name, 'Close').click
```

It seems safari (web inspector) has an issue? since I got like below error on the `submit`. No element found was raised in finding an element, `close`, in web view context. But I could open/close as below on native context.

```
[HTTP] --> POST /wd/hub/session/7ad61cce-107a-4e11-ae9e-9ac4239c5f37/element/5001/click
[HTTP] {}
[debug] [W3C (7ad61cce)] Calling AppiumDriver.click() with args: ["5001","7ad61cce-107a-4e11-ae9e-9ac4239c5f37"]
[debug] [XCUITest] Executing command 'click'
[debug] [RemoteDebugger] Executing atom 'click'
[debug] [RemoteDebugger] Executing 'click' atom in default context
[debug] [RemoteDebugger] Sending javascript command: '(function(){return function(){var h,aa=this;fun...'
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:82730', page '1', target 'page-6' (id: 46): 'Runtime.evaluate'
[debug] [WD Proxy] Matched '/alert/text' to command name 'getAlertText'
[debug] [WD Proxy] Proxying [GET /alert/text] to [GET http://127.0.0.1:8100/session/91449D5C-211B-4CDB-BBC2-6FF6341DED12/alert/text] with no body
[WD Proxy] Got response with status 404: {
[WD Proxy]   "value" : {
[WD Proxy]     "error" : "no such alert",
[WD Proxy]     "message" : "An attempt was made to operate on a modal dialog when one was not open",
[WD Proxy]     "traceback" : ""
[WD Proxy]   },
[WD Proxy]   "sessionId" : "91449D5C-211B-4CDB-BBC2-6FF6341DED12"
[WD Proxy] }
[debug] [W3C] Matched W3C error code 'no such alert' to NoSuchAlertError
[debug] [XCUITest] Error received while executing atom: operation timed out
[debug] [XCUITest] No alert found: Did not get any response for atom execution after 120005ms
[debug] [W3C (7ad61cce)] Encountered internal error running command: Error: Did not get any response for atom execution after 120005ms
[debug] [W3C (7ad61cce)]     at /Users/kazu/GitHub/appium/node_modules/appium-xcuitest-driver/lib/commands/web.js:275:15
[debug] [W3C (7ad61cce)]     at tryCatcher (/Users/kazu/GitHub/appium/node_modules/bluebird/js/release/util.js:16:23)
[debug] [W3C (7ad61cce)]     at Promise._settlePromiseFromHandler (/Users/kazu/GitHub/appium/node_modules/bluebird/js/release/promise.js:547:31)
[debug] [W3C (7ad61cce)]     at Promise._settlePromise (/Users/kazu/GitHub/appium/node_modules/bluebird/js/release/promise.js:604:18)
[debug] [W3C (7ad61cce)]     at Promise._settlePromise0 (/Users/kazu/GitHub/appium/node_modules/bluebird/js/release/promise.js:649:10)
[debug] [W3C (7ad61cce)]     at Promise._settlePromises (/Users/kazu/GitHub/appium/node_modules/bluebird/js/release/promise.js:725:18)
[debug] [W3C (7ad61cce)]     at _drainQueueStep (/Users/kazu/GitHub/appium/node_modules/bluebird/js/release/async.js:93:12)
[debug] [W3C (7ad61cce)]     at _drainQueue (/Users/kazu/GitHub/appium/node_modules/bluebird/js/release/async.js:86:9)
[debug] [W3C (7ad61cce)]     at Async._drainQueues (/Users/kazu/GitHub/appium/node_modules/bluebird/js/release/async.js:102:5)
[debug] [W3C (7ad61cce)]     at Immediate.Async.drainQueues (/Users/kazu/GitHub/appium/node_modules/bluebird/js/release/async.js:15:14)
[debug] [W3C (7ad61cce)]     at runCallback (timers.js:705:18)
[debug] [W3C (7ad61cce)]     at tryOnImmediate (timers.js:676:5)
[debug] [W3C (7ad61cce)]     at processImmediate (timers.js:658:5)
[HTTP] <-- POST /wd/hub/session/7ad61cce-107a-4e11-ae9e-9ac4239c5f37/element/5001/click 500 120015 ms - 595
```

https://github.com/appium/appium-xcuitest-driver/blob/5b7f3af68a838b4f91dcf2d58a5c24aaa4f24793/lib/commands/web.js#L272

page source around the `Close` alert button
```
                         </XCUIElementTypeTextView>
                          </XCUIElementTypeOther>
                          <XCUIElementTypeButton type="XCUIElementTypeButton" enabled="true" visible="false" x="35" y="17" width="29" height="27" name="Close" label="Close">
                          </XCUIElementTypeButton>
                          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="38" width="84" height="53">
                            <XCUIElementTypeButton type="XCUIElementTypeButton" enabled="true" visible="false" x="10" y="48" width="64" height="33" name="Close" label="Close">
                              <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" enabled="true" visible="false" x="20" y="54" width="44" height="21" name="Close" label="Close" value="Close">
                              </XCUIElementTypeStaticText>
                            </XCUIElementTypeButton>
                          </XCUIElementTypeOther>
                        </XCUIElementTypeOther>
```

**Comment by sunilpatro1985** [comment]
I managed to make it work with below workaround [switched to Native_App context and clicked alert Close button], 
But it's taking much longer time to perform, Time from switching to Native_app context and clicking on alert Close button and switching back to "webview_..." context takes around 2-3 minutes...

[Appium log](https://gist.github.com/sunilpatro1985/0c2821cd3d7ee7589df83d9f940825f0)

Workaround Code - 

```
        String context = driver.getContext(); //before alert     
        System.out.println("webview context " + context);
        driver.findElement(By.id("submit")).click(); //click submit to get alert
        driver.context("NATIVE_APP"); //after alert appears, switch to alert
        driver.findElement(By.name("Close")).click(); //close the alert
        driver.context(context); //switch back to webview
```

**Comment by KazuCocoa** [comment]
What about switching the context before `driver.findElement(By.id("submit"))`?
On my case, the command in WebView context took a long time since no response by Safari.

I mean like below.
```
        String context = driver.getContext(); //before alert     
        System.out.println("webview context " + context);
        driver.context("NATIVE_APP"); //after alert appears, switch to alert
        driver.findElement(By.name("submit")).click();
        driver.findElement(By.name("Close")).click();
        driver.context(context); //switch back to webview
```

**Comment by sunilpatro1985** [comment]
Because the "Submit" button is in WEBVIEW_** context, switching to native_app and clicking on "Submit" button doesn't work [error - org.openqa.selenium.NoSuchElementException]

**Comment by KazuCocoa** [comment]
ah, okay. I wondered so since below steps worked on my local in native context. (Sorry, the 'submit' should be 'Submit', case sensitive.)
```
@driver.find_element(:name, 'Submit').click
@driver.find_element(:name, 'Close').click
```

The root cause is probably response of Selenium (about the slow response), but for web context, `driver.switchTo().alert().accept();` seems does not work well in this case on WebView (safari side). Basically, Appium waits for response by Safari in web context.
Probably nothing we can do in Appium side for slow response, unfortunately.
