### ISSUE TITLE
Status bar does not change orientation while changing locale to arabic languages

### ISSUE THREAD

**Issue by lipinskr** [appium/appium#14334]
## The problem

When trying to change device locale to any arabic language via appium executed script, the whole device orientation should change to right-to-left. Every piece of UI changes correctly except the status bar. It stays left-to-right. This is not the case if i change device locale manually via user settings.

## Environment

* Appium version (or git revision) that exhibits the issue:  Appium1.15.1
* Last Appium version that did not exhibit the issue (if applicable): Non applicable
* Desktop OS/version used to run Appium: Windows 10 v1909
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: Android 9.0
* Real device or emulator/simulator: Real device - Samsung Galaxy A6.
* Appium CLI or Appium.app|exe:

**Comment by KazuCocoa** [comment]
Thanks.
We change the locale via configuration of android.app.ActivityManagerNative. But I guess Android OS handles RTL property separately.
https://github.com/appium/io.appium.settings/blob/b84d96f6116125fdc245d206195f6eafabbf842f/app/src/main/java/io/appium/settings/handlers/LocaleSettingHandler.java#L47


I found `debug.force_rtl` in `getprop`, but could not enable it via `setprop` even emulator.
Perhaps, if we can find the way to handle systemwide RTL like locale, we'll be able to add it in our capability

**Comment by KazuCocoa** [comment]
https://github.com/appium/io.appium.settings/pull/57 may fix it.
It reproduced on an emulator.

You could try the PR via adb command like below.

1. clone https://github.com/appium/io.appium.settings/tree/apply-lauyout-directions and build the apk on your device
2. Calls `adb shell pm grant io.appium.settings android.permission.CHANGE_CONFIGURATION` once
3. Calls `adb shell am broadcast -a io.appium.settings.locale --es lang fa --es country AF` (as you want to set)

**Comment by KazuCocoa** [comment]
You can try the fix as `appium@beta` :)
