### ISSUE TITLE
 Error: Appium Settings app is not running after 5000ms

### ISSUE THREAD

**Issue by Saurabhpilankar** [appium/appium#14341]
## The problem

I did setup for mobile app automation using Appium on my windows system and wrote first program in Eclipse using java to install the APK on real device but the log shows error message and I am not able to proceed further.

## Environment

* Appium version (or git revision) that exhibits the issue: **1.17.1**
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Windows 8
* Node.js version (unless using Appium.app|exe):  **v12.16.3.**
* Npm or Yarn package manager: **6.14.4**
* Mobile platform/version under test: `**Android**`
* Real device or emulator/simulator: **Real Device** [ Xiaomi Poco F1]
* Appium CLI or Appium.app|exe: **CLI**

## Details

I was able to run the program in the beginning but when I uninstalled the Appium Settings app from the device this error started appearing. 

## Link to Appium logs

https://gist.github.com/Saurabhpilankar/21635549ff8d1fe363a6d9d650926332

## Code To Reproduce Issue [ Good To Have ]

`import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import org.openqa.selenium.remote.DesiredCapabilities;

import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.android.AndroidElement;
import io.appium.java_client.remote.MobileCapabilityType;

public class Runner {

	public static void main(String[] args) throws MalformedURLException {
		File fl = new File("src");
		File apk = new File(fl, "ApiDemos-debug.apk");

		DesiredCapabilities cap = new DesiredCapabilities();
		cap.setCapability(MobileCapabilityType.DEVICE_NAME, "Android Device");
		cap.setCapability(MobileCapabilityType.APP, apk.getAbsolutePath());
		cap.setCapability(MobileCapabilityType.AUTOMATION_NAME, "uiautomator2");
		AndroidDriver<AndroidElement> ad = new AndroidDriver<AndroidElement>(new URL("http://127.0.0.1:4723/wd/hub"),
				cap);

	}

}
`

**Comment by mykola-mokhnach** [comment]
Can you start Appium Settings on the device under test manually? Does `adb shell pgrep -f io\\.appium\\.settings` output anything if executed manually?

**Comment by mykola-mokhnach** [comment]
Are there any errors in the logcat output?

**Comment by Saurabhpilankar** [comment]
`adb shell pgrep -f io\\.appium\\.settings `does not print anything.

**Comment by Saurabhpilankar** [comment]
Logcat shows following error:
https://gist.github.com/Saurabhpilankar/93f683369f814a4faaa779a462b93d24

**Comment by mykola-mokhnach** [comment]
It looks like you've gotten an incompatible device. Consider replacing it with one, that have non-modified Android firmware.

**Comment by Saurabhpilankar** [comment]
Hi
But I was able to run the program and open the app before uninstalling the Appium Settings app from the device.

**Comment by mykola-mokhnach** [comment]
We cannot do nothing there. Consider contacting the device manufacturer.

**Comment by vigneshgan** [comment]
@Saurabhpilankar : Check the appium settings app still be present in Apps and Notification tab of Device settings(Despite of your Uninstallation). Now do Uninstall for all Users, later run the code , it will work.
