### ISSUE TITLE
Unable to launch WDA by appium

### ISSUE THREAD

**Issue by 13817458995** [appium/appium#14345]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS 10.15.4
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: iOS 11.4.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: appium.app

## Details

The WDA can be built successfully by Xcode manually. But failed to launch by appium.
{
  "platformName": "iOS",
  "platformVersion": "11.4.1",
  "deviceName": "iphonePluse",
  "udid": "82166c045aec814daace69dbd100068024e3ec4f",
  "automationName": "XCUITest",
  "startIWDP": true,
  "bundleId": "com.tencent.mttlite",
  "noReset": false,
  "-allowProvisioningUpdates": true,
  "xcodeOrgId": "xxxx",
  "xcodeSigningId": "iPhone Developer",
  "clearSystemFiles": true
}

## Link to Appium logs
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGTERM'
[XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to start WebDriverAgent session because of xcodebuild failure: A new session could not be created. Details: 'capabilities' is mandatory to create a new session Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[XCUITest]     at quitAndUninstall (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:515:15)
[XCUITest] Started background XCTest logs cleanup: find -E /private/var/folders -regex '.*/Session-WebDriverAgentRunner.*\.log$|.*/StandardOutputAndStandardError\.txt$' -type f -exec sh -c 'echo "" > "{}"' \;
[XCUITest] Cleaning test logs in '/Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs' folder
[iOS] Clearing log files
[iOS] Deleting '/Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs'. Freeing 272K.
[iOS] Finished clearing log files
[iOSLog] Stopping iOS log capture
[BaseDriver] Event 'newSessionStarted' logged at 1589689960083 (12:32:40 GMT+0800 (CST))
[MJSONWP] Encountered internal error running command: Error: Unable to start WebDriverAgent session because of xcodebuild failure: A new session could not be created. Details: 'capabilities' is mandatory to create a new session Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[MJSONWP]     at quitAndUninstall (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:515:15)
[HTTP] <-- POST /wd/hub/session 500 31697 ms - 538
[HTTP] 
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 1 ms - 57
[HTTP] 

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by KazuCocoa** [comment]
It was because the installed WDA had no compatible with the Appium server. Perhaps the installed WDA was for newer Appium.
Please try out the latest version.

**Comment by mykola-mokhnach** [comment]
The error happens because WebDriverAgent server on the device is not compatible with the current Appium server version (perhaps a leftover from previous installs). Consider uninstalling it manually and  make sure the current Appium server builds and installs the binary properly.
Also, consider using the most recent server version.
