### ISSUE TITLE
[debug] [ADB] Incorrect package and activity. Retrying.

### ISSUE THREAD

**Issue by RichardHoOoOo** [appium/appium#14346]
## The problem
When I use Appium to launch the wikipedia app, I keep getting the error "Incorrect package and activity. Retrying."

It is because the launcher activity should be "org.wikipedia.main.MainActivity" according to the manifest but once wikipedia is opened, it will suddenly jumped to another Activity "org.wikipedia.onboarding.InitialOnboardingActivity".

Those are some important logs:
```
[debug] [ADB] Waiting up to 20000ms for activity matching pkg: 'org.wikipedia' and activity: 'org.wikipedia.main.MainActivity' to be focused
[debug] [ADB] Found package: 'org.wikipedia' and fully qualified activity name : 'org.wikipedia.onboarding.InitialOnboardingActivity'
[debug] [ADB] Incorrect package and activity. Retrying.
[debug] [W3C] Encountered internal error running command: Error: Cannot start the 'org.wikipedia' application.
```

As you can see, although I have launched wikipedia, appium still think it is not launched because wikipedia automatically jumped from MainActivity to another one. So is there any way to workaround this or can I say it is a appium bug?

**Comment by mykola-mokhnach** [comment]
Please fill out the issue report form properly and provide the required info.

Have you checked https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md ?

**Comment by RichardHoOoOo** [comment]
Thanks, the link helps.
