### ISSUE TITLE
iOS Safari Switch tab not working 

### ISSUE THREAD

**Issue by hemank5** [appium/appium#14342]
- Node Version: 14.0.0
- Appium Version: 1.17.1
- Browser(s): Safari iOS 12+ (tried multiple on 13.3 as well)
- Real device or emulator/simulator: Both
- Desktop OS/version used to run Appium: MacOS Catalina 10.15.4

**Console Output Error** 
- Failed: Parameters were incorrect. We wanted "we require one of \"name\" or \"handle\" to be set" and you sent {}

**Appium Logs**
https://gist.github.com/hemank5/6f9fb607b893e5c3528867d195060e4f

**Capabilities** 
Using Protractor
```
browserName: 'safari',
platformName: 'iOS',
platformVersion: '13.3',
deviceName: 'iPhone 11',
nativeWebTap: 'true',//If I keep this false then iOS throws Pop up(Allow or Block) whenever I click on a link which opens in new tab.
```

## Code To Reproduce Issue

Steps to reproduce the bug
Pages which opens on new tab/window on click and then verifying the contents on the new tab and then switching back to Parent tab for operations

On any page where target="_blank" for opening a new tab iOS Safari is unable to handle though it works fine on Android Chrome browser

I am using Protractor so below code which works fine on Desktop Chrome and Android Chrome
**Sample Code** 
```
browser.getWindowHandle().then((parentGUID) => {
            // click the link that opens in a new window
            offerPage.privacycenter.click();
            // get the all the session ids of the opened tabs
            browser.getAllWindowHandles().then((allGUID) => {
                //console.log("Number of tabs opened: " + allGUID.length);
                // iterate through the tabs
                for (let guid of allGUID) {
                    //find the new browser tab
                    if (guid != parentGUID) {
                        // switch to the tab
                        browser.switchTo().window(allGUID[2]);
                        // break the loop
                        break;
                    }
                }
                // performing actions needed on the new tab
                commonfunc.waitForPrivacyCenter();
                commonfunc.verifyCurrentURL(offerPage.privacycenterUrl);
                // closing the new tab
                browser.close();
                // switching back to the parent tab
                browser.switchTo().window(allGUID[1]);
            });
        });
```

**Comment by mykola-mokhnach** [comment]
Please attach the full server log

**Comment by hemank5** [comment]
> Please attach the full server log

https://gist.github.com/hemank5/6f9fb607b893e5c3528867d195060e4f

**Comment by mykola-mokhnach** [comment]
> [HTTP] --> POST /wd/hub/session/ce12ac09-c4e3-49b3-a6ef-c952eb7539ec/window
> [HTTP] {}
> [debug] [MJSONWP (ce12ac09)] Encountered internal error running command: BadParametersError: Parameters were incorrect. We wanted "we require one of \"name\" or \"handle\" to be set" and you sent {}
> 

The error is expected. No window handle has been sent in the request body

**Comment by hemank5** [comment]
> > [HTTP] --> POST /wd/hub/session/ce12ac09-c4e3-49b3-a6ef-c952eb7539ec/window
> > [HTTP] {}
> > [debug] [MJSONWP (ce12ac09)] Encountered internal error running command: BadParametersError: Parameters were incorrect. We wanted "we require one of "name" or "handle" to be set" and you sent {}
> 
> The error is expected. No window handle has been sent in the request body

That's what the console also outputs with this error.
Same code I am executing on _Android Chrome Browser_ and _Desktop Chrome_, and works perfectly fine there. I have included the sample code above which I am using to handle window switch.

**Comment by KazuCocoa** [comment]
When I ran `@driver.switch_to.window "75667.1"` against Safari, below log appeared. 
Not sure Protractor's code, but it seems it did not send the expected parameter.

```
[HTTP] --> POST /wd/hub/session/02ba0b5d-e43e-41b7-8b6c-5070e9c35abc/window
[HTTP] {"handle":"75667.1"}
[debug] [W3C (02ba0b5d)] Calling AppiumDriver.setWindow() with args: ["75667.1","75667.1","02ba0b5d-e43e-41b7-8b6c-5070e9c35abc"]
[debug] [XCUITest] Executing command 'setWindow'
[debug] [XCUITest] Attempting to set context to '75667.1' from '75667.1'
[debug] [XCUITest] Already in '75667.1' context. Doing nothing.
[debug] [W3C (02ba0b5d)] Responding to client with driver.setWindow() result: null
[HTTP] <-- POST /wd/hub/session/02ba0b5d-e43e-41b7-8b6c-5070e9c35abc/window 200 2 ms - 14
[HTTP]
```

When you ran the code against chrome, did the parameter appeared expectedly on the log?
(Appium raises an error if no handle or name parameter, so I assume the client sent an expected parameter)

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by hemank5** [comment]
> Closed because of no response

Please open this issue

**Comment by KazuCocoa** [comment]
The Chrome log had the body as below.
The first line of the below log is an incoming request for Appium, so your client did not send the body part for iOS case, I assume.

> [HTTP] --> POST /wd/hub/session/04b48fb8-7eb5-4e81-aff0-e56a72a5a443/window
[HTTP] {"name":"CDwindow-1","handle":"CDwindow-1"}
[MJSONWP (04b48fb8)] Driver proxy active, passing request on via HTTP proxy
[debug] [WD Proxy] Matched '/wd/hub/session/04b48fb8-7eb5-4e81-aff0-e56a72a5a443/window' to command name 'setWindow'
[debug] [WD Proxy] Proxying [POST /wd/hub/session/04b48fb8-7eb5-4e81-aff0-e56a72a5a443/window] to [POST http://127.0.0.1:8000/wd/hub/session/0514e2d46f330db6a89b433cdf3f0f4a/window] with body: {"name":"CDwindow-1","handle":"CDwindow-1"}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"0514e2d46f330db6a89b433cdf3f0f4a","status":0,"value":null}
[WD Proxy] Replacing sessionId 0514e2d46f330db6a89b433cdf3f0f4a with 04b48fb8-7eb5-4e81-aff0-e56a72a5a443
[HTTP] <-- POST /wd/hub/session/04b48fb8-7eb5-4e81-aff0-e56a72a5a443/window 200 14 ms - 76
[HTTP]

**Comment by hemank5** [comment]
> The Chrome log had the body as below.
> The first line of the below log is an incoming request for Appium, so your client did not send the body part for iOS case, I assume.
> 
> > [HTTP] --> POST /wd/hub/session/04b48fb8-7eb5-4e81-aff0-e56a72a5a443/window
> > [HTTP] {"name":"CDwindow-1","handle":"CDwindow-1"}
> > [MJSONWP (04b48fb8)] Driver proxy active, passing request on via HTTP proxy
> > [debug] [WD Proxy] Matched '/wd/hub/session/04b48fb8-7eb5-4e81-aff0-e56a72a5a443/window' to command name 'setWindow'
> > [debug] [WD Proxy] Proxying [POST /wd/hub/session/04b48fb8-7eb5-4e81-aff0-e56a72a5a443/window] to [POST http://127.0.0.1:8000/wd/hub/session/0514e2d46f330db6a89b433cdf3f0f4a/window] with body: {"name":"CDwindow-1","handle":"CDwindow-1"}
> > [debug] [WD Proxy] Got response with status 200: {"sessionId":"0514e2d46f330db6a89b433cdf3f0f4a","status":0,"value":null}
> > [WD Proxy] Replacing sessionId 0514e2d46f330db6a89b433cdf3f0f4a with 04b48fb8-7eb5-4e81-aff0-e56a72a5a443
> > [HTTP] <-- POST /wd/hub/session/04b48fb8-7eb5-4e81-aff0-e56a72a5a443/window 200 14 ms - 76
> > [HTTP]

Since I am using the same code for both, I have verified the configuration as well.
If in iOS it is not sending the required body, so seems to be an issue on iOS Appium driver?
As I have tried with multiple iOS version from 12.0+. 
Let me know what should be the next steps?

**Comment by KazuCocoa** [comment]
The below message you attached before was the most frontend place in Appium.
https://github.com/appium/appium-base-driver/blob/master/lib/protocol/routes.js#L115-L132

> [debug] [MJSONWP (ce12ac09)] Encountered internal error running command: BadParametersError: Parameters were incorrect. We wanted "we require one of "name" or "handle" to be set" and you sent {}

So, I assumed your client did not send the parameter.
It is good to capture requests your code sends. (Not on Appium server)

**Comment by hemank5** [comment]
> The below message you attached before was the most frontend place in Appium.
> https://github.com/appium/appium-base-driver/blob/master/lib/protocol/routes.js#L115-L132
> 
> > [debug] [MJSONWP (ce12ac09)] Encountered internal error running command: BadParametersError: Parameters were incorrect. We wanted "we require one of "name" or "handle" to be set" and you sent {}
> 
> So, I assumed your client did not send the parameter.
> It is good to capture requests your code sends. (Not on Appium server)

On further debugging I am able to **run successfully** on **iOS 11** but iOS 12, 13 version are throwing the same error `Failed: Parameters were incorrect. We wanted "we require one of "name" or "handle" to be set" and you sent {}`

So what I can interpret is the Appium is unable to handle the newer version iOS 12+.

Secondly I didn't quite get the ask for requests my code is sending. As I am basically just sending the required configuration through Protractor which is connected to Appium Server, I can only view logs on Appium Server. Not sure how to capture the request from code.

**Comment by KazuCocoa** [comment]
thanks. the iOS 11 log was expected.

Perhaps we should take a look at Protoractor logic.

**Comment by hemank5** [comment]
> thanks. the iOS 11 log was expected.
> 
> Perhaps we should take a look at Protoractor logic.

Using the below code for handling browser tabs as mentioned in below link as well.
https://developers.perfectomobile.com/display/TT/Protractor%3A+How+to+close+a+link+opened+in+a+new+browser+tab+and+return+to+the+original+parent+tab

```
browser.getWindowHandle().then(function(parentGUID){
    // click the link that opens in a new window
    element(by.id("element-id")).click();
    browser.sleep(5000);
    // get the all the session ids of the opened tabs
    browser.getAllWindowHandles().then(function(allGUID){
        console.log("Number of tabs opened: "+allGUID.length);
        // iterate through the tabs
        for(let guid of allGUID){
            //find the new browser tab
            if(guid !=parentGUID){
                // switch to the tab
                browser.switchTo().window(guid);
                // break the loop
                break;
            }
        }
        // perform here any actions needed on the new tab
        // close the new tab
        browser.close();
        // switch back to the parent tab
        browser.switchTo().window(parentGUID);
    });
});
```

**Comment by KazuCocoa** [comment]
Could you change the log level on the client side?

Perhaps protractor refers below line. If so, you can see what HTTP request was sent by the logic.
https://github.com/SeleniumHQ/selenium/blob/b4e5fe326d1f70061633ef290745f35893178ba5/javascript/webdriver/http/http.js#L105

https://github.com/SeleniumHQ/selenium/blob/df8c0b00426762fcf52d8b50461b0a81d8d6ce2a/javascript/node/selenium-webdriver/lib/webdriver.js#L1733-L1740

**Comment by hemank5** [comment]
> Could you change the log level on the client side?
> 
> Perhaps protractor refers below line. If so, you can see what HTTP request was sent by the logic.
> https://github.com/SeleniumHQ/selenium/blob/b4e5fe326d1f70061633ef290745f35893178ba5/javascript/webdriver/http/http.js#L105
> 
> https://github.com/SeleniumHQ/selenium/blob/df8c0b00426762fcf52d8b50461b0a81d8d6ce2a/javascript/node/selenium-webdriver/lib/webdriver.js#L1733-L1740

Well I am not sure If I can do this, but let me check more details on this.

Before that I am trying to go with this approach but I am stuck at this below, 
If I send `nativeWebTap`: `false` then whenever I run automation I see this message and can't figure out a way to handle this. (when I click on a link which opens in new tab/window)
![Screen Shot 2020-05-20 at 10 21 19 AM](https://user-images.githubusercontent.com/15861858/82477453-5c1d3500-9a84-11ea-9321-1f4c91b44d29.png)
This message never comes manually
even though I am sending these extra capabilities as well but seems it doesn't work
```
safariAllowPopups: 'true',
safariIngoreFraudWarning: 'true',
autoAcceptAlerts: 'true',
autoDismissAlerts:  'true',
```
Appium Log
```
[debug] [WD Proxy] Got response with status 200: {
[debug] [WD Proxy]   "value" : "This site is attempting to open a pop-up window",
[debug] [WD Proxy]   "sessionId" : "6A6C3ED0-0971-444B-BEAF-EC2483028FF2"
[debug] [WD Proxy] }
```

**How can I handle the above pop up and do you think this can resolve the main issue of tab switch?**

**Comment by KazuCocoa** [comment]
The message appeared when a new window open via web inspector or the site. (by 
Safari). So, it probably does not open via click a button by a native click action.
https://stackoverflow.com/questions/59273376/safari-show-pop-up-on-window-open

Perhaps it can handle in native context as a stable way.
https://github.com/appium/appium-xcuitest-driver/pull/1185
https://github.com/appium/WebDriverAgent/pull/297

**Comment by hemank5** [comment]
> The message appeared when a new window open via web inspector or the site. (by
> Safari). So, it probably does not open via click a button by a native click action.
> https://stackoverflow.com/questions/59273376/safari-show-pop-up-on-window-open
> 
> Perhaps it can handle in native context as a stable way.
> [appium/appium-xcuitest-driver#1185](https://github.com/appium/appium-xcuitest-driver/pull/1185)
> [appium/WebDriverAgent#297](https://github.com/appium/WebDriverAgent/pull/297)

Yes when the click on a link , it is opening a new window I am seeing that pop up
`browser.switchTo().alert().accept();` I am sending this, its not working.
Let me know if this is wrong way to accept an alert or if you can please share any sample code to handle this type of alert.


As per the links provided by you, I can see the issue has been fixed in latest version and I am on latest version.

Again I am not sure if resolving this can fix window/tab switching.

**Comment by KazuCocoa** [comment]
Can you get the window elements in the page source in native context? It is appreciated to share the source with us as GIST.
If yes, you can customise the logic to fit your case with `acceptAlertButtonSelector`/`dismissAlertButtonSelector` https://appium.io/docs/en/advanced-concepts/settings/ (the assessing API can also set via caps. https://appium.io/docs/en/writing-running-appium/caps/ )

If no, perhaps we cannot handle the alert in your case since XTest framework also cannot interact with it.
As a workaround, you can probably disable the popup via Settings > Safari > Block pop ups

**Comment by mykola-mokhnach** [comment]
I don't think there is anything that could be done on Appium side.

Closed as not an issue.
