### ISSUE TITLE
How to establish adb server connection between Appium and bluestacks?

### ISSUE THREAD

**Issue by firstsaid0** [appium/appium#14352]
Hello to everyone
How to establish adb server connection between Appium and bluestacks? I had trouble trying to connect. but I have no problem connecting android studio to android emulator and doing operations. I use pyhton as the software language.

Since I cannot connect with the appium interface, I cannot test the pyhton code I wrote with the tests on the android emulator. How can I solve this problem? I am a 1.5 month software developer. I will be very pleased if you write the solution in detail and share it.

thanks

Error message:

ECONNRESET

![a9999999](https://user-images.githubusercontent.com/26346547/82303410-9246b000-99c3-11ea-9ee4-486c8db60f6f.jpg)

**Comment by mykola-mokhnach** [comment]
Please use Appium forum for Howto questions.
