### ISSUE TITLE
Applesimutils don't permit access for contacts (iOS 13.4.1)

### ISSUE THREAD

**Issue by Phoenix124** [appium/appium#14355]
Try to manage access using applesimutils

## Environment

* Appium version: 1.17.1
* Desktop OS/version used to run Appium: Mac os 10.15.4
* Node.js version (unless using Appium.app|exe): 10.20.1
* Npm or Yarn package manager: 6.14.5
* Mobile platform/version under test: iOS 13.4.1
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI

## Details

Try to set permissions automatically with applesimutils,
For 12.4 iOS work correctly but for 13.4.1 - not

## Link to Appium logs
```
[debug] [iOSSim] Setting access for '....': {
[debug] [iOSSim]   "contacts": "yes",
[debug] [iOSSim]   "notifications": "yes",
[debug] [iOSSim]   "microphone": "yes",
[debug] [iOSSim]   "location": "always",
[debug] [iOSSim]   "medialibrary": "yes",
[debug] [iOSSim]   "photos": "yes"
[debug] [iOSSim] }
[iOSSim] The following permissions have not been recognized as native: {
[iOSSim]   "contacts": "yes",
[iOSSim]   "notifications": "yes",
[iOSSim]   "microphone": "yes",
[iOSSim]   "location": "always",
[iOSSim]   "medialibrary": "yes",
[iOSSim]   "photos": "yes"
[iOSSim] }
[debug] [iOSSim] Setting access for '...': {
[debug] [iOSSim]   "notifications": "yes",
[debug] [iOSSim]   "medialibrary": "yes"
[debug] [iOSSim] }
[debug] [iOSSim] Executing: applesimutils --byId 2DC37CB0-59EA-4A8D-B9D5-48FEC2E7DFE1 --bundle ... --setPermissions notifications\=yes\,medialibrary\=yes
[debug] [iOSSim] Command output: 
```

**Comment by mykola-mokhnach** [comment]
What exactly does not work? Since 11.4 SDK Apple added a native way to set permissions via simctl. The code is now trying to set known permissions using native endpoints and only unknown permissions are still set via applesimutils

**Comment by Phoenix124** [comment]
@mykola-mokhnach and how I could check unknown permissions?

**Comment by mykola-mokhnach** [comment]
What do you mean under "unknown permissions"?

**Comment by Phoenix124** [comment]
@mykola-mokhnach I mean which permissions I need to set in capabilities?
Btw, when I execute `applesimutils --byId D7EAE6ED-E637-41E2-916B-1DD48EE7642A --bundle .... --setPermissions contacts=yes` contacts permission is enabled

**Comment by mykola-mokhnach** [comment]
Does it work if `xcrun simctl <sim_id> privacy grant contacts <bundle_id>` is executed instead?

**Comment by Phoenix124** [comment]
@mykola-mokhnach no, it execute successfully but permission not set

**Comment by mykola-mokhnach** [comment]
This seems like a bug in Apple SDK. Does upgrade to iOS 13.5 solve it?

**Comment by Phoenix124** [comment]
@mykola-mokhnach no, still not working

**Comment by mykola-mokhnach** [comment]
What are your exact steps to run this command? Do you run it after the app is installed on a simulator but not launched yet?

**Comment by Phoenix124** [comment]
@mykola-mokhnach no, it installed, launched and after executed command

**Comment by mykola-mokhnach** [comment]
does it change anything if the command is executed before the app?

**Comment by Phoenix124** [comment]
Btw, when I execute launched app, app close
I try to execute before launch - the same state, no contacts permission

**Comment by mykola-mokhnach** [comment]
Could you please describe your issue to Apple?

@KazuCocoa Do you have any simulator apps, where we could verify contacts access?

**Comment by Phoenix124** [comment]
@mykola-mokhnach in which format?
Do you have an example?

**Comment by KazuCocoa** [comment]
https://developer.apple.com/bug-reporting/ is the Apple's bug report

No idea for now.
Perhaps we can find a sample app in Apple's sample code...

**Comment by mykola-mokhnach** [comment]
I did find an app, where I was able to check the majority of options that the `privacy` arg allows to customize and only `microphone` worked out of these that I've tried.

There is for sure a bug somewhere in the Apple's implementation. I'll fallback to WIX tools to handle the stuff for Xcode 11.4+ for now.

FYI @LeoNatan

**Comment by LeoNatan** [comment]
If you see issues in AppleSimUtils, open issues in that project.

**Comment by mykola-mokhnach** [comment]
I just wanted to mention that your AppleSimUtils work properly (which is great) whenever Apple's "native" implementation does not.

**Comment by LeoNatan** [comment]
Thanks! My comment was to the OP.

**Comment by Phoenix124** [comment]
@mykola-mokhnach I think it will be better to use applesimutils for all permissions, not to use native apple utils

**Comment by mykola-mokhnach** [comment]
Switched permissions management back to AppleSimUtils usage in appium@beta
