### ISSUE TITLE
I get an adb server connection error between Appium and BlueStacks.

### ISSUE THREAD

**Issue by firstsaid0** [appium/appium#14353]
Hello to everyone
I get an adb server connection between Appium and bluestacks. I had trouble trying to connect. but I have no problem connecting android studio to android emulator and doing operations. I will be very pleased if you write the solution in detail and share it.

thanks

Error message:

ECONNRESET

![a9999999](https://user-images.githubusercontent.com/26346547/82306526-d936a480-99c7-11ea-83d0-4e7f6d6dbecd.jpg)

**Comment by firstsaid0** [comment]
Error
An unknown server-side error occurred while processing the command. Original error: Failed to launch Appium Settings app: Condition unmet after 5317 ms. Timing out.

![a333](https://user-images.githubusercontent.com/26346547/82310928-b0191280-99cd-11ea-8ba7-b3925c9d9c19.jpg)



and


![a1111111](https://user-images.githubusercontent.com/26346547/82310993-caeb8700-99cd-11ea-9596-ef6189434900.jpg)


Error
An unknown server-side error occurred while processing the command. Original error: Could not find 'aapt.exe' in ["C:\\Users\\Sad\\AppData\\Local\\Android\\Sdk\\platform-tools\\aapt.exe","C:\\Users\\Sad\\AppData\\Local\\Android\\Sdk\\emulator\\aapt.exe","C:\\Users\\Sad\\AppData\\Local\\Android\\Sdk\\tools\\aapt.exe","C:\\Users\\Sad\\AppData\\Local\\Android\\Sdk\\tools\\bin\\aapt.exe"]. Do you have Android Build Tools installed at 'C:\Users\Sad\AppData\Local\Android\Sdk'?

**Comment by KazuCocoa** [comment]
Did your environment have apkanalyzer in `sdk/tools/bin`?
If no, Appium fallbacks to adapt. If your environment had no such commands, perhaps your environment missed android build tools. https://appium.io/docs/en/drivers/android-uiautomator2/index.html

The former was Appium could not find the settings app process with `pgrep`.
Please make sure the settings app can lunch on the environment. (You can find adb command to launch settings app in the log, so please try out the command directly.)

**Comment by firstsaid0** [comment]
![a45](https://user-images.githubusercontent.com/26346547/82419616-58d77880-9a87-11ea-948d-c2eeb3b39f51.jpg)


As in the attached picture, android / sdk / tools / bin, build-platforms, platforms-tools etc. all roads are both loaded and defined. It works seamlessly with appium, android studio, android emulator. but it doesn't work with bluestacks.

I ran appium studio. and I made a sample transaction macro. creates the new macro. but when I say process macro, it doesn't. what could be the problem


error code like this:
----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK



some pyhton source codes:

import unittest
import time
from appium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions


class a1(unittest.TestCase):
    reportDirectory = 'reports'
    reportFormat = 'xml'
    dc = {}
    testName = 'a1'
    driver = None

    def setUp(self):
        self.dc['reportDirectory'] = self.reportDirectory
        self.dc['reportFormat'] = self.reportFormat
        self.dc['testName'] = self.testName
        self.dc['udid'] = '127.0.0.1:5555'
        self.dc['appPackage'] = 'com***********************'
        self.dc['appActivity'] = '.activity.MainTabActivity'
        self.dc['platformName'] = 'android'
        self.driver = webdriver.Remote('http://localhost:5555/wd/hub', self.dc)

------------------------------------------------------------------------ etc.








The emulator panel, which has been added, connected and opened with appium studio, is as in the picture. appium studio can be connected to the device. but the madro source code it generates does not work when run later. externally in pyhton it gives the above error.


How can I solve this problem? When I open the appium program, I cannot access it as in the picture. the result is the same.
please reply to me.

**Comment by KazuCocoa** [comment]
>  It works seamlessly with appium, android studio, android emulator. but it doesn't work with bluestacks.

Ah, so, is this compatibility issue with BlueStack via vanilla Android tools?
I haven't used Appium Studio, but I think it is Eclipse based tool. If it had its own environment variable etc, the situation may happen. Checking the Eclips's paths may help, I assume.

BTW, I have no experience about BlueStack, unfortunately.
Checking https://discuss.appium.io/ also may help.

**Comment by firstsaid0** [comment]
![6666hh](https://user-images.githubusercontent.com/26346547/82505785-ef974a00-9b06-11ea-99b9-5f5e7b89e2a5.jpg)

error message

Error
An unknown server-side error occurred while processing the command. Original error: Failed to launch Appium Settings app: Condition unmet after 5364 ms. Timing out.

**Comment by KazuCocoa** [comment]
Could you share the full Appium log as text on [GIST](https://gist.github.com/)?

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by SergioGLara** [comment]
at the command prompt type adb devices -l

get the bluestacks emulator identifier and use it in your code:


driver = Remote(
     'http://localhost:4723/wd/hub',
     {
         "udid": "emulator-5554",
         "deviceName": "OnePlus5",
         "platformName": "Android"
     }
)
