### ISSUE TITLE
Appium support for Chrome on iOS

### ISSUE THREAD

**Issue by swapnilagarwwal** [appium/appium#14354]
## The problem
I want to test Chrome in iOS devices.
My understanding is that Chrome Chrome for iOS is open source, [here](https://blog.chromium.org/2017/01/open-sourcing-chrome-on-ios.html) is the announcement.

We can install the Chrome app with our developer signed certificate on an iOS device, launch the Chrome App, launch browser, switch context, and run Appium commands. It worked!

## The questions I have is:

1. Is the open-sourced Chrome app [code](https://chromium.googlesource.com/chromium/src.git/+/master/ios/chrome/) same as the App Store version of Chrome app? Am I missing something here?

2. Why Appium doesn't support Chrome on iOS?

**Comment by KazuCocoa** [comment]
For 1)
Not sure. Please ask it Google...

For 2)
What do you mean? Do you mean web context?
You can launch 'com.google.chrome.ios' which is available AppStore and access it as native context. But you need debug app to access web context via Web inspector because of iOS's limitation.

**Comment by swapnilagarwwal** [comment]
For 2)
You are right. We can only debug (run Appium commands) when we run a developer signed IPA file.

My question is simply: Why Appium doesn't support running Chrome on iOS? 
Is it that the Appium community never prioritized this request, or is it because Apple's guidelines don't allow us to automate/debug other third-party apps?

**Comment by KazuCocoa** [comment]
Sorry, what do you mean _running chrome on iOS_?
You can launch com.google.chrome.ios and find elements on it. If you can find pages via Safari inspector (maybe it needs debug build), Appium probably can inspect it.
For example, https://gist.github.com/KazuCocoa/fb8b74ff86c6a5051a003eefff3169dd is page source I got by the chrome which downloaded by AppStore.
