### ISSUE TITLE
Appium get Logcat Exception from Tested App

### ISSUE THREAD

**Issue by wulfihm** [appium/appium#14356]
Hi,

this is not an issue with Appium but a general inquiry how to do it or if it is possible at all.

I am testing an app and recently I found a bug in the app, which causes the tested app to crash producing an Exception output in the Logcat of the Android Emulator. I have to manually go into android studio and the logcat output and look for the exception. So for future tests it would be nice if my tests fail it would automatically look into the logcat for exceptions and then print it or something. I am already using an implementation of an ITestListener for TestNG so doing something after the tests is not an issue. Getting the correct lines in the logcat is the issue.

Essentially what I am doing so far is this:
```
LogEntries logcatOutput = driver.manage().logs().get("logcat");
StreamSupport.stream(logcatOutput.spliterator(), false).filter(s -> s.toString().contains("TESTED_APPNAME")).forEach(System.out::println);
```

It 'works' but fails to gather the output from the tested app.
Essentially what I am getting is something like this (one line of the output above).
`[2020-05-19T13:41:19+0200] [ALL] 05-19 13:39:31.587 11267 11305 I appium  : Find element command using 'id' with selector 'TESTED_APPNAME:id/testView.`

What it looks like in Android Studio.
`2020-05-19 13:41:59.550 17433-17472/io.appium.uiautomator2.server I/appium: Find element command using 'id' with selector 'TESTED_APPNAME:id/testView'.`

It doesn't work because the logcat I get from appium the appname is in bytes or the PID?
So using the example above instead of getting "io.appium.uiautomator2.server" I get "11267 11305", I guess? So I am not able to look for all outputs produced by the tested app.

Another idea I had was to create a listener to the logcat and fail tests as soon as an exception is produced by the tested app or at least print them into the appium log output. But no Idea how to do that at all. I found the interface 'ListensToLogcatMessages' but couldn't find any documentation how it works at all.

Kind regards

**Comment by mykola-mokhnach** [comment]
How about https://github.com/appium/java-client/blob/master/src/test/java/io/appium/java_client/android/AndroidLogcatListenerTest.java ?

**Comment by mykola-mokhnach** [comment]
Regarding the log formatting: it could be customized by providing the corresponding arg to logcat call:

```
  -v <format>     Sets the log print format, where <format> is one of:

                  brief process tag thread raw time threadtime long
```

For now, there is no way to customize that for Appium

**Comment by wulfihm** [comment]
As far as I could see the format option is just there to specify what to display from the existing logcat, which is the output retrieved by not using an format option at all. Without using the format option the logcat output already displays all the information that is there. So no matter what the logcat only reports the PID of the package.

It is possible to get the PID via this command if the app is running:
`adb shell pidof -s PACKAGE_NAME`
And then retrieve all logs by the PID.
`adb logcat --pid=25762`

This actually works very well but this is via ADB.
This issue would probably also persist when using a LogcatListener as it will get exactly the same type of logs.
It is possible to run adb commands with appium if you set the --relaxed-security command line argument when starting the server: http://appium.io/docs/en/writing-running-appium/android/android-shell/index.html

So what I am doing now is this after the server has been started and the app initialized on the device:
```
List<String> args = Arrays.asList(
        "-s",
        "de.android.mycrocast"
);
Map<String, Object> cmd = ImmutableMap.of(
        "command", "pidof",
        "args", args
);
String pid = (String) driver.executeScript("mobile: shell", cmd);
int PackagePid = Integer.parseInt(pid.replace("\n", ""));
```

And then after the test run I retrieve the relevant logs via the TestListener like so:

```
StreamSupport.stream(logcatOutput.spliterator(), false)
        .filter(s -> s.toString()
                .contains(String.valueOf(driver.getPackagePid())))
        .forEach(System.out::println);
```

It works (as of now) as intended.

**Comment by mykola-mokhnach** [comment]
It makes sense to add params for logcat customization, at least the one for log lines format customization plus filter specs

**Comment by mykola-mokhnach** [comment]
I've added two new capabilities to appium@beta: logcatFormat and logcatFilterSpecs. These will allow to file-tune the logcat output. Check https://github.com/appium/appium-adb/blob/37a4931cb4afd08bb99ac28b0cd1f0493cc286e6/lib/tools/adb-commands.js#L983 for more details on supported capabilities formats.
