### ISSUE TITLE
iOS App source not being retrieved properly when certain elements are present.

### ISSUE THREAD

**Issue by Julioevm** [appium/appium#14357]
## The problem

Appium is failing to show the source of the app I'm testing in certain screen, apparently when a table of sizes is present. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.0 and 1.17.1
* Desktop OS/version used to run Appium: mac os catalina 10.15.3
* Node.js version: 13.11.0
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: iOS 13.3.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Tied both appium desktop and appium cli

## Details

According to the developers, this is a regular table with nothing special about it.
Here are a couple of pictures, with and without the table.

![appium-ok](https://user-images.githubusercontent.com/38758281/82334890-e2843900-99e8-11ea-9ff1-b3c072ffba12.png)
Here we can see the source is properly loaded.

![appium-issue](https://user-images.githubusercontent.com/38758281/82334946-f2038200-99e8-11ea-946b-6feb239a848c.png)
After displaying the size table the source doesn't get retrieved properly, only a few elements are loaded.

Also I guessed the id of one of the elements, like "s" and if I click on it it handles it without problem, so it can find an element inside the table even if it cant read the entire source.
Also tried includeNonModalElements capability with no different result.

## Link to Appium logs

https://gist.github.com/Julioevm/5157fc7b0e79950dc3620dc6b21ef26d

**Comment by mykola-mokhnach** [comment]
Appium simply reflects what XCTest sends to it. Consider reporting the issue to Apple

**Comment by mykola-mokhnach** [comment]
It might also be that the view is not accessible. Then https://github.com/appium/appium/issues/6517 could be useful to read

**Comment by Julioevm** [comment]
HI @mykola-mokhnach,
I'd say this is a different issue than #6517 since is not just the cells inside the table that aren't retrieved, but the entire page's elements.
That said, are the errors in the log able to provide any information to you about this issue?
Like here, this seems to be about when it tries to retrieve the source and failing at some point:


```
[debug] [35m[XCUITest][39m Executing command 'getPageSource'
[debug] [35m[WD Proxy][39m Matched '/source' to command name 'getPageSource'
[debug] [35m[WD Proxy][39m Proxying [GET /source] to [GET http://127.0.0.1:8901/session/5BA1657D-929E-446A-A64C-BA0D628F9CDE/source] with no body
[error] [35m[Xcode][39m 2020-05-19 13:38:51.433330+0200 WebDriverAgentRunner-Runner[16820:16168500] The following attributes were requested to be included into the XML: {(
[error] [35m[Xcode][39m     FBYAttribute,
[error] [35m[Xcode][39m     FBWidthAttribute,
[error] [35m[Xcode][39m     FBHeightAttribute,
[error] [35m[Xcode][39m     FBTypeAttribute,
[error] [35m[Xcode][39m     FBValueAttribute,
[error] [35m[Xcode][39m     FBNameAttribute,
[error] [35m[Xcode][39m     FBLabelAttribute,
[error] [35m[Xcode][39m     FBEnabledAttribute,
[error] [35m[Xcode][39m     FBVisibleAttribute,
[error] [35m[Xcode][39m     FBXAttribute
[error] [35m[Xcode][39m )}
[error] [35m[Xcode][39m [error] [35m[Xcode][39m 2020-05-19 13:38:56.439206+0200 WebDriverAgentRunner-Runner[16820:16168500] The applicaion has still not finished animations after 5.00 seconds timeout
[error] [35m[Xcode][39m 
[error] [35m[Xcode][39m     t =  1050.21s Requesting snapshot of accessibility hierarchy for app with pid 16829
[error] [35m[Xcode][39m [error] [35m[Xcode][39m     t =  1050.36s Get all elements bound by accessibility element for: Elements matching predicate 'wdUID IN {"07000000-0000-0000-BD41-000000000000", "08000000-0000-0000-BD41-000000000000"}'
[error] [35m[Xcode][39m 
[error] [35m[Xcode][39m     t =  1050.36s     Requesting snapshot of accessibility hierarchy for app with pid 16829
[error] [35m[Xcode][39m 
[error] [35m[Xcode][39m     t =  1050.44s     Find: Children matching type Window
[error] [35m[Xcode][39m     t =  1050.44s     Find: Elements matching predicate 'wdUID IN {"07000000-0000-0000-BD41-000000000000", "08000000-0000-0000-BD41-000000000000"}'
[error] [35m[Xcode][39m 
[error] [35m[Xcode][39m     t =  1050.46s Find the Window
[error] [35m[Xcode][39m 
[error] [35m[Xcode][39m     t =  1050.46s     Requesting snapshot of accessibility hierarchy for app with pid 16829
[error] [35m[Xcode][39m 
[error] [35m[Xcode][39m     t =  1050.54s     Find: Children matching type Window
[error] [35m[Xcode][39m 
[error] [35m[Xcode][39m     t =  1050.54s     Find: Elements matching predicate 'wdUID IN {"07000000-0000-0000-BD41-000000000000", "08000000-0000-0000-BD41-000000000000"}'
[error] [35m[Xcode][39m     t =  1050.54s     Find: Identity Binding
[error] [35m[Xcode][39m [error] [35m[Xcode][39m 2020-05-19 13:38:59.486871+0200 WebDriverAgentRunner-Runner[16820:16168500] Cannot take the snapshot of Window after 15 seconds
[error] [35m[Xcode][39m 2020-05-19 13:38:59.487039+0200 WebDriverAgentRunner-Runner[16820:16168500] Internal error: Error Domain=com.apple.dt.xctest.automation-support.error Code=5 "Error kAXErrorServerNotFound getting snapshot for element <AXUIElementRef 0x12f172250> {pid=16833} {uid=[ID:9999 hash:0xa056b04000000000]}" UserInfo={NSLocalizedDescription=Error kAXErrorServerNotFound getting snapshot for element <AXUIElementRef 0x12f172250> {pid=16833} {uid=[ID:9999 hash:0xa056b04000000000]}}
[error] [35m[Xcode][39m 2020-05-19 13:38:59.487140+0200 WebDriverAgentRunner-Runner[16820:16168500] Skipping source dump for 'Window' because its snapshot cannot be resolved
[error] [35m[Xcode][39m     t =  1053.25s Find the Window
[error] [35m[Xcode][39m     t =  1053.26s     Requesting snapshot of accessibility hierarchy for app with pid 16829
[error] [35m[Xcode][39m 
[error] [35m[Xcode][39m     t =  1053.33s     Find: Children matching type Window
[error] [35m[Xcode][39m 
[error] [35m[Xcode][39m     t =  1053.33s     Find: Elements matching predicate 'wdUID IN {"07000000-0000-0000-BD41-000000000000", "08000000-0000-0000-BD41-000000000000"}'
[error] [35m[Xcode][39m     t =  1053.33s     Find: Identity Binding
[error] [35m[Xcode][39m [debug] [35m[WD Proxy][39m Got response with status 200: {
[debug] [35m[WD Proxy][39m   "value" : "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<XCUIElementTypeApplication type=\"XCUIElementTypeApplication\" name=\"Oysho\" label=\"Oysho\" enabled=\"true\" visible=\"true\" x=\"0\" y=\"0\" width=\"375\" height=\"667\">\n  <XCUIElementTypeWindow type=\"XCUIElementTypeWindow\" enabled=\"true\" visible=\"false\" x=\"0\" y=\"0\" width=\"375\" height=\"667\">\n    <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"false\" x=\"0\" y=\"0\" width=\"375\" height=\"667\">\n      <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"false\" x=\"0\" y=\"0\" width=\"375\" height=\"667\"\/>\n    <\/XCUIElementTypeOther>\n  <\/XCUIElementTypeWindow>\n<\/XCUIElementTypeApplication>\n",
[debug] [35m[WD Proxy][39m   "sessionId" : "5BA1657D-929E-446A-A64C-BA0D628F9CDE"
[debug] [35m[WD Proxy][39m }
```

If this is specific to XCTest then, I'll report it to them.
Thanks!

**Comment by mykola-mokhnach** [comment]
> [error] �[35m[Xcode]�[39m 2020-05-19 13:38:59.487039+0200 WebDriverAgentRunner-Runner[16820:16168500] Internal error: Error Domain=com.apple.dt.xctest.automation-support.error Code=5 "Error kAXErrorServerNotFound getting snapshot for element <AXUIElementRef 0x12f172250> {pid=16833} {uid=[ID:9999 hash:0xa056b04000000000]}" UserInfo={NSLocalizedDescription=Error kAXErrorServerNotFound getting snapshot for element <AXUIElementRef 0x12f172250> {pid=16833} {uid=[ID:9999 hash:0xa056b04000000000]}}


Yes, this is for sure an XCTest-specific issue.

**Comment by Julioevm** [comment]
One more thing regarding this issue.
Based on this error:
`[error] [35m[Xcode][39m [error] [35m[Xcode][39m 2020-05-19 13:27:18.337353+0200 WebDriverAgentRunner-Runner[16820:16168500] The applicaion has still not finished animations after 5.00 seconds timeout
`

Could the problem arise due to an animation not finishing and the app not being idle? Or in this case the hierarchy should be retrieved regardless of this?

**Comment by mykola-mokhnach** [comment]
Yes it could be. XCTest is only able to take accessibility snapshot when the app under test is idling. If the app si not idling for longer periods of time then snapshotting is not possible.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
