### ISSUE TITLE
Proxy error trying to launch applications via the appium GUI 

### ISSUE THREAD

**Issue by johndlawlor** [appium/appium#14350]
Proxy error when trying to start an Appium session for Notepad. 

I am trying to test a windows application with Appium and WinAppDriver. However i have difficulty starting a session through the Appium UI. For example, i am trying to launch Notepad..
--> POST /session
[HTTP] {"desiredCapabilities":{"app":"C:\\Windows\\System32\\notepad.exe","deviceName":"MYWIN10PC","platformName":"Windows"}}

But our proxy blocks the request:
Rule name: Block Unauthenticated Clients to Unverified Sites
Ruleset: Category Content Filter - Unauthenticated

## Environment
Windows 10.
Appium 1.15.1
WinAppDriver

## Details

When i click 'Start Session' i get this error:

Rule name: Block Unauthenticated Clients to Unverified Sites
Ruleset: Category Content Filter - Unauthenticated
Date: <today>
Host: 127.0.0.1
Requested port: 4723
Client IP: <my ip>
Raw URL: http://127.0.0.1:4723/wd/hub/session
Command or method: POST
Raw user name:
SSL Info:
URL Categories :
URL Destination IP : 127.0.0.1
URL Reputation : Unverified
Media Type:
User-Agent: admc/wd/1.11.1

My environemnt variables have:
NO_PROXY=localhost,127.0.0.*
HTTP_PROXY=http://our-work-proxy.com:8080

I've tried it by adding 'Use Proxy' and using our work proxy as it is specified in the Environemnt variables. 

If i just use the WinAppDriver server and create a project in visual studio to launch notepad with the above desiredCapabilities, it will launch Notepad. 

There is nothing in the logs beyond:
[info] [35m[Appium][39m   address: 127.0.0.1
[info] [35m[Appium][39m   allowInsecure: {
[info] [35m[Appium][39m   }
[info] [35m[Appium][39m   denyInsecure: {
[info] [35m[Appium][39m   }
[info] [35m[Appium][39m Appium REST http interface listener started on 127.0.0.1:4723

**Comment by mykola-mokhnach** [comment]
Consider changing proxy rules on the machine or use one without  proxy. There is nothing we could do from Appium side.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
