### ISSUE TITLE
Appium not detecting device

### ISSUE THREAD

**Issue by tejasrinarmeta** [appium/appium#14351]
## The problem
[ADB] Error killing ADB server, going to see if it's online anyway
[ADB] Getting connected devices...
[ADB] Could not find devices, restarting adb server...
[ADB] Restarting adb
[ADB] Killing adb server on port 5037
[ADB] Error killing ADB server, going to see if it's online anyway
[ADB] Getting connected devices...
[ADB] Could not find devices, restarting adb server...
[ADB] Restarting adb
[ADB] Killing adb server on port 5037
[ADB] Error killing ADB server, going to see if it's online anyway
[UiAutomator2] Deleting UiAutomator2 session
[BaseDriver] Event 'newSessionStarted' logged at 1589817217064 (21:23:37 GMT+0530 (India Standard Time))
[W3C] Encountered internal error running command: Error: Could not find a connected Android device.
[W3C]     at ADB.getDevices$ (C:\Users\admin\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:196:13)
[W3C]     at tryCatch (C:\Users\admin\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\admin\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\admin\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[W3C]     at invoke (C:\Users\admin\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[W3C]     at enqueueResult (C:\Users\admin\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:185:17)
[W3C]     at new Promise (C:\Users\admin\AppData\Local\Programs\Appium\resources\app\webpack:\~\babel-polyfill\~\core-js\modules\es6.promise.js:177:1)
[W3C]     at new F (C:\Users\admin\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\core-js\library\modules\$.export.js:30:36)
[W3C]     at AsyncIterator.enqueue (C:\Users\admin\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:184:12)
[W3C]     at AsyncIterator.prototype.(anonymous function) [as next] (C:\Users\admin\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[W3C]     at Object.runtime.async (C:\Users\admin\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:209:12)
[W3C]     at getDevices (C:\Users\admin\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-adb\build\lib\tools\system-calls.js:409:38)
[W3C]     at ADB.getDevices$ (C:\Users\admin\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:213:20)
[W3C]     at tryCatch (C:\Users\admin\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\admin\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\admin\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[W3C]     at GeneratorFunctionPrototype.invoke (C:\Users\admin\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[W3C]     at run (C:\Users\admin\AppData\Local\Programs\Appium\resources\app\webpack:\~\babel-polyfill\~\core-js\modules\es6.promise.js:75:1)
[W3C]     at C:\Users\admin\AppData\Local\Programs\Appium\resources\app\webpack:\~\babel-polyfill\~\core-js\modules\es6.promise.js:92:1
[W3C]     at flush (C:\Users\admin\AppData\Local\Programs\Appium\resources\app\webpack:\~\babel-polyfill\~\core-js\modules\_microtask.js:18:1)
[W3C]     at process._tickCallback (internal/process/next_tick.js:61:11)
[HTTP] <-- POST /wd/hub/session 500 21884 ms - 20

**Comment by mykola-mokhnach** [comment]
Please fill out the issue report properly.

Is the device visible in `adb devices` list?

**Comment by 8096434212** [comment]
> Please fill out the issue report properly.
> 
> Is the device visible in `adb devices` list?

Yes it is visible in adb devices list.

**Comment by mykola-mokhnach** [comment]
Unfortunately we cannot help nothing without the detailed info about the issue

**Comment by mykola-mokhnach** [comment]
Closed because of no response
