### ISSUE TITLE
Knowledge on switching between apps

### ISSUE THREAD

**Issue by DebojeetB** [appium/appium#14359]
I have written a code in Appium which would open an app (suppose A) and perform some actions in it. I do not quit that app and I switch to another app (suppose B) and perform some actions in it.
Till this point, the code is working as expected.
Now, I want to navigate back to app A and land on the same page where I was there before switching to app B. Will this action be possible in Appium? 
As of now, when I try to navigate back to app A, driver relaunches and app A starts from scratch.
Can anyone please help me on this if this action can be performed in Appium?

**Comment by mykola-mokhnach** [comment]
Unfortunately there is no any mention about the destination environment, so we cannot help much.

In iOS (XCTest) and Android (UIA2) there is a possibility to manage apps. Check http://appium.io/docs/en/writing-running-appium/ios/ios-xctest-mobile-apps-management/ and/or https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/InteractsWithApps.java (the `launchApp`/`closeApp`/`resetApp` methods there are legacy and must not be used)

Please use Appium forum to ask questions
