### ISSUE TITLE
Can't run two simulators in parallel

### ISSUE THREAD

**Issue by XAmenSatanX** [appium/appium#14367]
## The problem

I want to run two simulators in parallel, but instead of loading the second simulator, the application closes and starts again on the first simulator.

## Environment

* Appium version: 1.17.1
* Appium CLI or Appium.app|exe: Appium CLI

## Desired capabilities simulators

**First simulator:**
`{'platformName': 'iOS',
   'noReset': 'true',
   'platformVersion': '13.5',
   'deviceName': 'iPhone X',
   'autoAcceptAlerts': 'true', 'wdaLocalPort': '5042', 'app': '/Users/administrator/aplication.app'}`
**Second simulator:**
`{'platformName': 'iOS',
   'noReset': 'true',
   'platformVersion': '13.5',
   'deviceName': 'iPhone X',
   'autoAcceptAlerts': 'true', 'wdaLocalPort': '5041', 'app': '/Users/administrator/aplication.app'}`
## Link to Appium logs

https://gist.github.com/XAmenSatanX/7ccaab52ffdf6542f71632d5c1446c55

**Comment by mykola-mokhnach** [comment]
Consider selecting different simulators for parallel tests

**Comment by amedvedjev** [comment]
@XAmenSatanX you should provide UDID of simulator to start. Each simulator has it unique UDID like real device.

**Comment by XAmenSatanX** [comment]
@amedvedjev Since I run tests in the container, I have no way to create simulators and get them udid. I need to run two or more iphone X simulators. Previously, appium automatically created simulators with the name 'appiumTest-A2889CBD-0923-4880-BD7A-54BE5CF4EBEE-iPhone X'.

**Comment by mykola-mokhnach** [comment]
Appium only creates a simulator when it cannot fins a device with matching name. Otherwise it prefers an existing one. Your image already has iPhone X@13.5 and it is used by default

**Comment by mykola-mokhnach** [comment]
there is also `enforceFreshSimulatorCreation` capability, which enforces new simulator creation being set to true

**Comment by XAmenSatanX** [comment]
Thanks!
