### ISSUE TITLE
Temporary created .app file is not cleared

### ISSUE THREAD

**Issue by kolyakrasnik** [appium/appium#14366]
## The problem

I'm noticing high disk space usage during last time. We lost about 120Gb in 1-2 days. After investigation I've found, that there are lot of temporary **.app** files in directory ```/System/Volumes/Data/private/var/folders/ts/hw0jgppx7j5d6py3gnzvcfy00000gn/T```
After restarting my system this space is free but after 1-2 days there is no free space again. I tried to set clearSystemFiles=true, no result. Still seeing high disk space usage. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1
* Desktop OS/version used to run Appium: macOS Catalina 10.15.4 (19E287)
* Node.js version (unless using Appium.app|exe): 14.3.0
* Npm or Yarn package manager: npm 6.14.4
* Mobile platform/version under test: iOS 13.2
* Real device or emulator/simulator: real devices
* Appium CLI or Appium.app|exe: appium CLI
* xCode: 11.2

## Details

We are using several devices on one mac server.

## Link to Appium logs

[GIST](https://gist.github.com/kolyakrasnik/b7428724f230aac3d4648a91f9262558)

**Comment by mykola-mokhnach** [comment]
Normally each server instance creates a separate temporary folder where it keeps cached apps. These apps are created as result of archives extraction and/or archives download. You could also the that in the logs:

> 2020-05-22 11:27:32:620 - [BaseDriver] Will reuse previously cached application at '/var/folders/ts/hw0jgppx7j5d6py3gnzvcfy00000gn/T/2020422-33380-cuepdg.6gilh/Payload//*******..app'

These caches are LRU caches and are set to expire after 24 hours e.g. a cached app is deleted automatically after 24 hours of inactivity.  Also, all the cached items are automatically deleted from temp files if the server receives SIGTERM or SIGINT. The cache is designed in such way, that same archives don't get extracted twice and the extracted content is gets reused upon the next session startup. You could see https://github.com/appium/appium-base-driver/blob/master/lib/basedriver/helpers.js for more details about the actual cache implementation. 

This means the cache could grow too big if different archives are sent too often to each driver session or the archives are really large and take a lot of space.

**Comment by kolyakrasnik** [comment]
@mykola-mokhnach We have about 1000 test's execution daily in 7 threads on the mac. Each app is about 120Mb. So it becomes an issue for us now. We use fullReset=true in our testing, but we use the same .ipa file all the time (but from shared with NFS space from another server). So, why we have so many copies of .app file?
Also, I have another server with Mojave system and appium 1.13.0-beta.3, and there is no such issues there.

**Comment by mykola-mokhnach** [comment]
>  7 threads on the Mac

Same server or each thread creates a separate node instance?

> same .ipa file all the time (but from shared with NFS space from another server)

Like I said same ipa should only be extracted once and then reused (the cache stores the actual sha1 hash sum of an archive to avoid duplicates).

**Comment by kolyakrasnik** [comment]
We use the same WDA server. We start it ones and then provide WDA server IP to the appium. useNewWDA=false by default.

**Comment by kolyakrasnik** [comment]
Let me provide more info. We start 7 appium processes, and 7 xcodebuild processes for wda. Each appium process knows related WDA:port  process. 
```/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=**** USE_PORT=20081 MJPEG_SERVER_PORT=20092 test
```
and 

```node /usr/local/lib/node_modules/appium/build/lib/main.js -p 4849 --log-timestamp --device-name iPhone_8 --automation-name=XCUItest --udid *** --default-capabilities {"mjpegServerPort": 20092, "webkitDebugProxyPort": 20093, "clearSystemFiles": "true", "webDriverAgentUrl":"http://***:20081", "preventWDAAttachments": "true", "simpleIsVisibleCheck": "true", "wdaLocalPort": "20081", "usePrebuiltWDA": "true", "useNewWDA": "false", "platformVersion": "13.1.2", "automationName":"XCUITest", "deviceName":"iPhone_8" } --nodeconfig ./configs/***.json```

**Comment by mykola-mokhnach** [comment]
> node /usr/local/lib/node_modules/appium/build/lib/main.js

This means that each thread creates a separate server process (which has its own cache). Let say you have 7 servers and each server is using its own archive, which will result in 120 MB * 7 = 840 MB. It will stay like that if the archive stays the same for the following sessions. If archives differ then the cache will be growing, at least for the next 24 hours or until the server process is killed. Note that if the process is killed forcefully (SIGKILL) then no cleanup is performed.

**Comment by kolyakrasnik** [comment]
I checked logs for all threads and I see that cashed app is reused (at least by logs). But at the same time I see that every minute something generates a new temp file with .app at /var/folders/ts/hw0jgppx7j5d6py3gnzvcfy00000gn/T directory. I changed local appium script to ```const CACHED_APPS_MAX_AGE = 1000 * 60 * 60 * 5```  So, I'd like to check it some cached files will be deleted in 5 hours or not. 
<img width="403" alt="tmp_dir" src="https://user-images.githubusercontent.com/16190512/82695734-584d0680-9c6e-11ea-8d57-dfbfc8784d66.png">
Looks pretty weird to me.

**Comment by mykola-mokhnach** [comment]
I would try to monitor the file system there to know which process does that first: https://apple.stackexchange.com/questions/347040/how-to-determine-which-process-is-creating-a-file

**Comment by mykola-mokhnach** [comment]
Also, like I said, make sure the process gets killed gracefully, so it gets a change to cleanup the cache before exit

**Comment by kolyakrasnik** [comment]
> Also, like I said, make sure the process gets killed gracefully, so it gets a chance to cleanup the cache before exit

I see that new files are being created at the same time appium works. We are not killing appium processes at all. Or do you mean something else?

> I would try to monitor the file system there to know which process does that first: 

I see that **fseventsd** accessing tmp dir and looks like creates this copy. Trying to get clarity what is it.
<img width="919" alt="fsenv" src="https://user-images.githubusercontent.com/16190512/82699579-9ac61180-9c75-11ea-9788-4b6be675f1f0.png">

**Comment by mykola-mokhnach** [comment]
I would try to collect server logs from the running instances and check which temporary paths they use to store binaries. Then stop these instances and make sure the paths don't exist anymore on the local file system.

**Comment by mykola-mokhnach** [comment]
Also, have you checked what exactly takes place inside of these folders?

**Comment by kolyakrasnik** [comment]
> Also, have you checked what exactly takes place inside of these folders?

yep, I've checked these folders. Unzipped .app is stored there
`/T/2020426-11435-1uoc3lg.m4bi/Payload/my.app`

> I would try to collect server logs from the running instances and check which temporary paths they use to store binaries. Then stop these instances and make sure the paths don't exist anymore on the local file system.

I checked logs of appium server and got path to cached .app. Then I stopped appium process with `kill -9 pid`. But cached directory still exists on file system and contails .app file. Should this directory be deleted immediatly? 

Also we are trying this solution now https://apple.stackexchange.com/questions/27034/how-can-i-stop-fseventsd-for-certain-volumes

**Comment by mykola-mokhnach** [comment]
> I checked logs of appium server and got path to cached .app. Then I stopped appium process with kill -9 pid. But cached directory still exists on file system and contails .app file. Should this directory be deleted immediatly?

Yes this is expected. Sending SIGKILL terminates it instantly, so node process does have a chance to call shutdown hooks.

**Comment by kolyakrasnik** [comment]
No result with no_log for .fseventsd. Still seeing high disk space usage. If someone has the same issue and found out a solution - need your help ))

**Comment by mykola-mokhnach** [comment]
I did check the cache implementation and I don't observe any explicit issues on Appium side. The cache leftovers are properly cleaned up as soon as the process exits.

**Comment by kolyakrasnik** [comment]
@mykola-mokhnach Thank you for the help. It might be then an issue from macOS Catalina side. Will reach this thread if get some clarity on it.

**Comment by kolyakrasnik** [comment]
@mykola-mokhnach It seems that I got clarity what can be an issue. We had a list of devices connected to a single mac server. For each device we had each own appium process and we used useNewWda=false. So, we control WDA with our own logic. One of the devices had been updated to iOS 13.4.1 but we did not update xCode to compatible version (we used 10.2). Appium node was working and shown in selenium hub, but during test's execution there were some errors on the step when appium began interact with WDA. So, I guess this combination provided lot of extra cached .ipa files.  I moved this device from the server and I don't see so big disk space usage during the day. About 20Gb had been generated, but during the same time before 100+ Gb had been generated. I'll monitor disk space usage during the next day and reach this thread to confirm, that things are ok.

**Comment by kolyakrasnik** [comment]
@mykola-mokhnach Yes, it was the reason. Two days without restarting the mac and I still see lot of free space. So, can be then some issue from appium side? I see unzipping of an ipa but after error from WDA side these data is not deleted and re-used during the next test. We use the same appium process for execution.

**Comment by mykola-mokhnach** [comment]
Is it possible to provide the server log for two subsequent runs where extracted binaries are not reused?

**Comment by kolyakrasnik** [comment]
@mykola-mokhnach Yep, i didn't delete the log from the server )) https://gist.github.com/kolyakrasnik/2061d480a900958165b9d1cfce3650a6

**Comment by mykola-mokhnach** [comment]
> 2020-06-02 09:27:29:898 - [debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED IP:20061). Retrying...
> 2020-06-02 09:27:37:395 - [Appium] Welcome to Appium v1.17.1

This does not look like the session is started in scope of the same process. The second line is logged when a new instance is started.

**Comment by kolyakrasnik** [comment]
Yep, WDA process is not started due to reasons I mentioned above - updated iOS (13.4.1) and old xCode 10.2 (doesn't support iOS 13.4.1). So, is it possible to delete cached file right after it happens or reuse this cache for the next request? It sensitive for example in our case - we have 1000 tests during the day, so failed node produces Gbs of extra cache. And our retry logic doesn't provide so many failures, that's why can't determine the issue.

**Comment by mykola-mokhnach** [comment]
> So, is it possible to delete cached file right after it happens or reuse this cache for the next request?

No, this is not possible at least on the server side. The client does not close the failed session properly neither close the server process, so there is no way Appium process knows it is time to clear the cache. Consider deleting the caches with a custom external script in such case or change the client logic to handle session failures properly.

**Comment by kolyakrasnik** [comment]
I think this question is answered now. Thanks for your support.
