### ISSUE TITLE
Appium is auto-selecting elements for iOS that are not being explicitly called via SDK

### ISSUE THREAD

**Issue by brummetj** [appium/appium#14364]
## The problem

I'm running into an issue where Appium / WDA is auto-selecting an element from the application that we are automating with iOS platforms. This is happening when there are no explicit driver commands to search and click this element using the python SDK. From the logs it appears that is somehow finding this element and clicking on it, as well as there seems to be some loop going on constantly from the WDA ( which I think is looking for this element constantly )

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.0
* Last Appium version that did not exhibit the issue (if applicable): 1.16.3-beta
* Desktop OS/version used to run Appium: OSX Catalina 10.15
* Node.js version (unless using Appium.app|exe): 6.13.4
* Mobile platform/version under test: iOS v13.4
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: cli

## Details

The weird part is that I have seen the app continue to auto click this button even after I shut down the Appium server. Its almost as if Xcode is still continuing to look for this element and click on it from this loop that is getting initiated. 

From the logs, you can see that I'm requesting to look for an element with the ID tag "Restart" but it goes ahead to search and click on a button called "Episode Details" automatically blocking any other request being made by the WDA. This happens as soon as we click on the "more options" button to bring up these new elements in the DOM. This appears to happen every time, tested across multiple devices, and is a blocker for our automation. 

## Link to Appium logs

https://gist.github.com/brummetj/4b8e4123dbfeb944bfd8c3aa137c0d80
https://gist.github.com/brummetj/034083158dabad31be21ad555813b975

**Comment by mykola-mokhnach** [comment]
Please provide the full log with the commands sent by the client. Also make sure you use the most recent server version (currently 1.17.1)

**Comment by brummetj** [comment]
https://gist.github.com/brummetj/d438394d631bd4eabad791f84127b319

Here is the link to the client logs. I cropped it to only where the part that matters, we look and click on the element "More", then try to find and click on element "Restart" which doesn't happen because another button gets clicked instead.

**Comment by mykola-mokhnach** [comment]
Could you also attach the page source output before the Restart button is clicked?

It might be there is another control with the same id. Also, I saw cases where xctest was not calculating controls coordinates properly and it was necessary to tap bu coordinates instead as a workaround

**Comment by mykola-mokhnach** [comment]
> [Xcode]     t =   523.52s Get all elements bound by index for: Elements matching predicate 'elementType IN {7, 5, 46}'

Btw, log lines like that mean that WDA is looking for possible alerts. This could be happening in background if `autoAcceptAlerts` cap is enabled.

**Comment by brummetj** [comment]
@mykola-mokhnach Thanks for the info you're right we did have the `autoAcceptAlert` Cap enabled. 

I think that was the issue! I turned off that capability and it was no longer auto-clicking that element. 

Just for more information here is the page source 

```
<?xml version="1.0" encoding="UTF-8"?><AppiumAUT><XCUIElementTypeApplication type="XCUIElementTypeApplication" name="Stream QA" label="Stream QA" enabled="true" visible="true" x="0" y="0" width="834" height="1194">
  <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" visible="true" x="0" y="0" width="834" height="1194">
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="834" height="1194">
      <XCUIElementTypeOther type="XCUIElementTypeOther" name="PopoverDismissRegion" label="dismiss popup" enabled="true" visible="true" x="0" y="0" width="834" height="1194"/>
      <XCUIElementTypePopover type="XCUIElementTypePopover" enabled="true" visible="true" x="403" y="651" width="317" height="172">
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="403" y="651" width="317" height="172">
          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="403" y="651" width="317" height="172">
            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="403" y="651" width="317" height="172"/>
            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="403" y="651" width="317" height="172">
              <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="707" y="719" width="13" height="37"/>
            </XCUIElementTypeOther>
          </XCUIElementTypeOther>
        </XCUIElementTypeOther>
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="403" y="651" width="304" height="172">
          <XCUIElementTypeSheet type="XCUIElementTypeSheet" enabled="true" visible="true" x="403" y="651" width="304" height="172">
            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="403" y="651" width="304" height="172">
              <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="403" y="651" width="304" height="172">
                <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="403" y="651" width="304" height="172"/>
                <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="403" y="651" width="304" height="172">
                  <XCUIElementTypeScrollView type="XCUIElementTypeScrollView" enabled="true" visible="true" x="403" y="651" width="304" height="172">
                    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="403" y="651" width="304" height="172">
                      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="403" y="651" width="304" height="172">
                        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="403" y="651" width="304" height="57">
                          <XCUIElementTypeButton type="XCUIElementTypeButton" name="Episode Details" label="Episode Details" enabled="true" visible="true" x="403" y="651" width="304" height="57"/>
                        </XCUIElementTypeOther>
                        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="403" y="708" width="304" height="1">
                          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="403" y="708" width="304" height="1">
                            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="403" y="708" width="304" height="1"/>
                          </XCUIElementTypeOther>
                        </XCUIElementTypeOther>
                        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="403" y="708" width="304" height="58">
                          <XCUIElementTypeButton type="XCUIElementTypeButton" name="Watch Options" label="Watch Options" enabled="true" visible="true" x="403" y="708" width="304" height="58"/>
                        </XCUIElementTypeOther>
                        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="403" y="765" width="304" height="1">
                          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="403" y="765" width="304" height="1">
                            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="403" y="765" width="304" height="1"/>
                          </XCUIElementTypeOther>
                        </XCUIElementTypeOther>
                        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="403" y="766" width="304" height="57">
                          <XCUIElementTypeButton type="XCUIElementTypeButton" name="Restart" label="Restart" enabled="true" visible="true" x="403" y="766" width="304" height="57"/>
                        </XCUIElementTypeOther>
                      </XCUIElementTypeOther>
                    </XCUIElementTypeOther>
                    <XCUIElementTypeOther type="XCUIElementTypeOther" value="0%" name="Vertical scroll bar, 1 page" label="Vertical scroll bar, 1 page" enabled="true" visible="true" x="674" y="651" width="30" height="172"/>
                    <XCUIElementTypeOther type="XCUIElementTypeOther" value="0%" name="Horizontal scroll bar, 1 page" label="Horizontal scroll bar, 1 page" enabled="true" visible="true" x="403" y="790" width="304" height="30"/>
                  </XCUIElementTypeScrollView>
                </XCUIElementTypeOther>
              </XCUIElementTypeOther>
            </XCUIElementTypeOther>
          </XCUIElementTypeSheet>
        </XCUIElementTypeOther>
      </XCUIElementTypePopover>
      <XCUIElementTypeImage type="XCUIElementTypeImage" enabled="true" visible="false" x="253" y="501" width="604" height="472"/>
    </XCUIElementTypeOther>
  </XCUIElementTypeWindow>
  <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" visible="false" x="0" y="0" width="834" height="1194">
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="834" height="1194">
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="834" height="1194"/>
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="1194" width="834" height="282"/>
    </XCUIElementTypeOther>
  </XCUIElementTypeWindow>
</XCUIElementTypeApplication></AppiumAUT>
```

It sounds like there might a bug with that capability, we might want to look into? I'm thinking since its matching any type of element in that predicate some elements for people's applications ( like mine ) elements will get auto-selected by this if it thinks its an alert. Unless you don't think this is a bug and the nature of how it works that's understandable too. None the less turning it off fixed this issue.

**Comment by mykola-mokhnach** [comment]
This is the original logic for alert detection:
https://github.com/appium/WebDriverAgent/blob/071ff0944292fed23478c902e2157bebba9a247c/WebDriverAgentLib/Categories/XCUIApplication%2BFBAlert.m#L70

By default all elements inherited from `XCUIElementTypeSheet` are considered alerts and this behaviour was there from the very beginning. I'm also not a very big fan of how this algorithm works, but changing it might cause legacy issues. Consider tuning `acceptAlertButtonSelector`/`dismissAlertButtonSelector` driver settings to change this behaviour

**Comment by brummetj** [comment]
Got it, thanks for the info. Yeah I'm not sure if I'm a big fan of how that algorithm works as well... It is interesting that it's thinking the "Episode Details" button is an alert. 

I'll look into those driver's settings. thanks, @mykola-mokhnach, feel free to close this out.

**Comment by mykola-mokhnach** [comment]
I suppose it was done this way to automatically handle system alerts that appear as sheets. Something like https://developer.apple.com/design/human-interface-guidelines/ios/images/Action_Sheets_2x.png

**Comment by brummetj** [comment]
This would make sense, I believe on iPhone this element does appear as a list of sheet buttons actually... but it's different with the iPad

**Comment by mariushorvat** [comment]
@brummetj Hi Josh, do you have a workaround for this? I've just stumbled into this myself, too.
The  `autoAcceptAlerts = true` and my Action sheet is considered alert. Thanks!
