### ISSUE TITLE
Getting error while installing appium via command promopt

### ISSUE THREAD

**Issue by localtest143** [appium/appium#14368]
## The problem
I am trying to install appium via command prompt using the command "npm install -g appium" and getting error "npm ERR! code ELIFECYCLE". 

## Environment
* Appium version (or git revision) that exhibits the issue:  
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Windows 8.1
* Node.js version (unless using Appium.app|exe): v14.3.0
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details
I have installed node.js and then wanted to install appium via command prompt got error.

## Link to Appium logs
I am attaching two logs:
1.  The logs as displayed in command prompt.
[Log_Error_installation apppium.txt](https://github.com/appium/appium/files/4670489/Log_Error_installation.apppium.txt)

2. The log generated by the system in the path C:\Users\Amir\AppData\Roaming\npm-cache\_logs
[2020-05-22T19_34_31_568Z-debug.log](https://github.com/appium/appium/files/4670526/2020-05-22T19_34_31_568Z-debug.log)

## Code To Reproduce Issue [ Good To Have ]
npm install -g appium

**Comment by KazuCocoa** [comment]
The postinstall script in appium-chromedriver failed probably because of a permission issue. It could not write downloaded chromedrivers on your environment.
You can skip the installation by `--chromedriver-skip-install` argument for the npm install command.

```
(node:2872) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js
de.
[14:34:05] Error installing Chromedriver: EINVAL: invalid argument, mkdir 'C:\Users\Amir\AppData\Local\Temp;C:\Program Files\Java\jdk1.8.0_111\bin;C:\Program Files\Java
4aawe.3c9om'
[14:34:05] Error: EINVAL: invalid argument, mkdir 'C:\Users\Amir\AppData\Local\Temp;C:\Program Files\Java\jdk1.8.0_111\bin;C:\Program Files\Java\jre1.8.0_111\bin\202042
[14:34:05] Downloading Chromedriver can be skipped by using the '--chromedriver-skip-install' flag or setting the 'APPIUM_SKIP_CHROMEDRIVER_INSTALL' environment variabl
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.x (node_modules\appium\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```

```
18205 verbose lifecycle appium-chromedriver@4.21.0~postinstall: unsafe-perm in lifecycle true
18206 verbose lifecycle appium-chromedriver@4.21.0~postinstall: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Amir\AppData\Roaming\npm\node_modules\appium\node_modules\appium-chromedriver\node_modules\.bin;C:\Users\Amir\AppData\Roaming\npm\node_modules\appium\node_modules\.bin;C:\Users\Amir\AppData\Roaming\npm\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Broadcom\Broadcom 802.11;;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Hewlett-Packard\SimplePass\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Java\jdk1.8.0_111\bin;C:\Program Files\Java\jre1.8.0_144\bin;C:\Android;C:\Windows\System32;C:\Users\Amir\eclipse-workspace\Jars\apache-maven-3.6.3\bin;C:\Program Files (x86)\Micro Focus\Unified Functional Testing\bin;C:\Program Files\nodejs\;C:\Users\Amir\AppData\Roaming\npm
18207 verbose lifecycle appium-chromedriver@4.21.0~postinstall: CWD: C:\Users\Amir\AppData\Roaming\npm\node_modules\appium\node_modules\appium-chromedriver
18208 silly lifecycle appium-chromedriver@4.21.0~postinstall: Args: [ '/d /s /c', 'node install-npm.js' ]
18209 silly lifecycle appium-chromedriver@4.21.0~postinstall: Returned: code: 1  signal: null
18210 info lifecycle appium-chromedriver@4.21.0~postinstall: Failed to exec postinstall script
```

**Comment by mykola-mokhnach** [comment]
> info WinAppDriver Will write to C:\Users\Amir\AppData\Local\Temp;C:\Program Files\Java\jdk1.8.0_111\bin;C:\Program Files\Java\jre1.8.0_111\bin\WinAppDriver.msi

It looks like the environment setup is broken, particularly the path to the temp folder. Consider fixing it, otherwise many other thing are going to be broken, not only this one.

**Comment by localtest143** [comment]
@KazuCocoa : Thanks a lot. It worked.

**Comment by basmalachhab** [comment]
> @KazuCocoa : Merci beaucoup. Ça a marché.

PLEASE, How you solved this problem !!!!!
