### ISSUE TITLE
Appium server error

### ISSUE THREAD

**Issue by tejasrinarmeta** [appium/appium#14360]
[appium-server-logs.txt](https://github.com/appium/appium/files/4655314/appium-server-logs.txt)
Can anyone please help me to get solution for this issue.I have attached logs

**Comment by mykola-mokhnach** [comment]
Please fill out the issue report template properly

**Comment by mykola-mokhnach** [comment]
Regarding the error in logs:
- https://github.com/appium/java-client/blob/master/docs/environment.md
- Use the most recent server version

**Comment by mykola-mokhnach** [comment]
Closed because of no response
