### ISSUE TITLE
Appium desktop pre-release 1.17.1 displays "App" would like to use bluetooth

### ISSUE THREAD

**Issue by anhmainvg** [appium/appium#14365]
## The problem

I have to use the Pre-release appium desktop 1.17.1 version for my app in iOS 13.4.1 because with the version 1.15.1 I cannot install app

## Environment

* Appium version (or git revision) that exhibits the issue: Appium Desktop 1.17.1 Pre-release
* Last Appium version that did not exhibit the issue (if applicable): 1.15.1
* Mobile platform/version under test: 13.4.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium.app Pre-release

## Details

my app is the IONIC Webview app, and just install the app via a new session of appium desktop, the message about Bluetooth is displayed, and it is not nice

## Screenshot

![image](https://user-images.githubusercontent.com/43400649/82642165-b27ea500-9c37-11ea-97f2-c5c8c5985a2e.png)

**Comment by mykola-mokhnach** [comment]
I cannot understand what the issue is. The screenshoted alert is the standard iOS security alert, which is shown for your app under test, because it needs to access Bluetooth service.

**Comment by anhmainvg** [comment]
hi @mykola-mokhnach , with the same IPA file and if I build with Xcode normally or via appium globally 1.17.1, I do not get the issue.

I will get more information from dev team and back to you. Thanks for your looking

**Comment by anhmainvg** [comment]
hi @mykola-mokhnach , sorry I provided the wrong old file, so it issue does not relate to Appium. I close the issue, and please ignore the issue
