### ISSUE TITLE
Find Element very slowly

### ISSUE THREAD

**Issue by 13817458995** [appium/appium#14378]
## The problem

It need at least 2-3 mins to find one element if there are a lot of elements located in the page.
Have any idea to make it faster?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: mac
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: 13.4.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium.app

**Comment by mykola-mokhnach** [comment]
Please provide the full server log with timestamps

**Comment by mykola-mokhnach** [comment]
Closed because of no response
