### ISSUE TITLE
cannot send backspace with send_keys()

### ISSUE THREAD

**Issue by rg-software** [appium/appium#14376]
After upgrading to a new Appium version (1.16 -> 1.17 I believe) I cannot send a backspace character `\b` with `send_keys()` anymore. I use Python bindings for real Android and iOS devices, and this problem occurs on both types.

The call goes through, so I can see  something like

`[debug] [W3C (5956d577)] Calling AppiumDriver.setValue() with args: [["\b"],"bf1ff312-d848-4889-b18b-8302a3cd0dd3","5956d577-89b2-4234-811c-f4cad60be221"]` 

in the Appium log. Other keys work fine. On Android, I tried also `driver.press_keycode(67)`, and it works fine, but I have no idea how to achieve the same functionality on iOS and Windows.

Any suggestions, please?

**Comment by mykola-mokhnach** [comment]
Try to send `\u0008` and/or `\u007F` instead

**Comment by rg-software** [comment]
No difference. In fact, in Python:
```
>>> s = '\b'
>>> s
'\x08'
```

**Comment by mykola-mokhnach** [comment]
what xctest logs show? Does it receive the characters?

**Comment by rg-software** [comment]
Actually, it looks like I was wrong: it works on iOS, but the problem definitely persists on Android. I need to check it in more detail (iOS/Windows), but  probably something should be done with Android `send_keys()` as sending backspaces is expected behavior I think.

**Comment by mykola-mokhnach** [comment]
There's no magic. The downstream code simply calls `ACTION_SET_TEXT` UIAutomator action on the target element.

**Comment by rg-software** [comment]
Well, to sum it up: what is the "official" way to delete a character?
In various sources online (read: stackoverflow) it is suggested to send '`\b'` or `\x08`, and this method indeed worked before. However, it does not work now, and there is no cross platform alternative, I am afraid.

**Comment by mykola-mokhnach** [comment]
Seems like nobody knows. Consider asking question in Appium forum
