### ISSUE TITLE
PickerWheel value not steerable in native context with Appium 1.17.1

### ISSUE THREAD

**Issue by PrzemyslawKusmider** [appium/appium#14379]
## The problem

It is impossible to set value of PickerWheel in mobile native and Xamarin apps. The same issue can be reproduced with Appium Desktop 1.17.1 with SendKeys to PickerWheel.

## Environment

- Appium version: 1.17.1
- iOS version: 13.2.3 / 12.4
- Occured on both real device and simulator
- Native/Xamarin

## Link to Appium logs
SetValue 
https://gist.github.com/PrzemyslawKusmider/690199e6e8703b00e14725167afe6a55

Appium Desktop SendKeys to PickerWheel
https://gist.github.com/PrzemyslawKusmider/bafe05a08479d957657a28c2a0fde339

**Comment by simoreira** [comment]
` The on-screen keyboard must be present to send keys`

I think you need to activate the simulator keyboard

**Comment by mykola-mokhnach** [comment]
There is no magic there. setValue endpoint simply calls the downstream XCTest method and there are several known issues about that only Apple could fix. Check https://github.com/appium/appium/issues?q=is%3Aissue+picker+is%3Aclosed

You could use `mobile: selectPickerWheelValue` as a workaround or perform swipe using touch actions interface.

**Comment by mykola-mokhnach** [comment]
closed as third party issue
