### ISSUE TITLE
[Android]Launch multiple avds failed when adb server is initially not running 

### ISSUE THREAD

**Issue by zethyscythe** [appium/appium#14373]
## The problem

Running multiple instance of avds in single appium server will fail if adb server is not running during initial launch. 

## Environment

* Appium version (or git revision) that exhibits the issue:1.17.1
* Desktop OS/version used to run Appium:Windows 10
* Node.js version (unless using Appium.app|exe): v12.13.1
* Npm or Yarn package manager: npm v6.14.2
* Mobile platform/version under test: Android 28
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: cli

## Details

I run 2 avd instances in single appium server with adb server not running and got error below. This results only 1 avd successfully launched and set up. You can check more detail in the link to appium logs below.
```
[debug] [W3C] Encountered internal error running command: Error: Error getting AVD. Original error: Error getting emulators. Original error: Error while getting connected devices. Original error: Command 'C:\\Users\\root\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 devices' exited with code 1
[debug] [W3C]     at ADB.getRunningAVD (C:\Users\root\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:575:11)

```

## Link to Appium logs

[appium-parallel-no-running-adb ](https://gist.github.com/zethyscythe/0865643e1b98adc25edac86fd0c00307)

## Disclaimer
This is not a major bug and simply can be resolved by starting the adb server first before the test using `adb start-server` ,but it would be nice if it can be fixed.

**Comment by mykola-mokhnach** [comment]
The change has been published to appium@beta
