### ISSUE TITLE
After a click there is no transition to the next screen

### ISSUE THREAD

**Issue by vi-babaeva** [appium/appium#14375]
## The problem

after installing the app, the button is clicked on the onboarding screen -> after this click, the next screen should be redrawn.
but after clicking I stay on the first screen. you can also see this behavior on appium desktop (video steps https://gyazo.com/80f898e720dbe51f05a7419cb8d3642f)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1
* Desktop OS/version used to run Appium: macOS Catalina 10.15.4
* Node.js version (unless using Appium.app|exe): 12.16.3
* Npm or Yarn package manager: 6.14.4
* Mobile platform/version under test: iOS 13.1-13.5 
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: both
* Xcode: 11.5

## Link to Appium logs
https://gist.github.com/vi-babaeva/0328d16495c9e162635c7acc741242d8

## Code To Reproduce Issue [ Good To Have ]
https://github.com/vi-babaeva/JavaAppiumAuto/commit/fc4cd43cda5f828a3156955b72ba8efc796c0f94

**Comment by mykola-mokhnach** [comment]
It might be the target element is located in a web view. Then make sure the context is switched properly before interaction with these elements. Also, sometimes XCTest fails to detect element coordinates properly. Then clicking by absolute coordinates might be a workaround

**Comment by vi-babaeva** [comment]
@mykola-mokhnach
So, before clicking, I check that the element is present on the page. 
I also see that the click was successful because the test crashes when it can't find an item on the second page (that didn't reload after the click).

I also tried clicking by absolute coordinates, the result is the same.

**Comment by mykola-mokhnach** [comment]
The click itself is generated by XCTest, so there is nothing we can change about it. 
Check the web view case as stated above. I don't have any other good suggestions if the app is native though.

**Comment by vi-babaeva** [comment]
@mykola-mokhnach I think I found a strange solution, but I don't understand which side of the problem is in iOS 13.

the only thing I did: I changed the ios version to 12.4. 
after that, appium started showing accessibility id for elements. in version 13 there was only xpath. 
in the test I replaced it with an id and test passed

**Comment by mykola-mokhnach** [comment]
I don't think there is much we could do here from Appium side. 
Closed as third party issue
