### ISSUE TITLE
UIAutomator2 Driver exits unexpectedly - [Instrumentation] The process has exited with code 0

### ISSUE THREAD

**Issue by cosminstirbu** [appium/appium#14372]
## The problem

Hello

We have approx 191 end to end tests that run nightly in Azure Pipelines on macOS hosted agents.

The tests run on an emulator using the `system-images;android-29;google_apis_playstore;x86` (although we've seen similar behavior on `system-images;android-28;google_apis_playstore;x86` as well.

The way we run the tests - we first create the AVD outside the tests themselves (using bash) and then we pass the `avd` capability to when we created the session so it opens the emulator.

Before each test we call `ResetApp` on the driver, and after each failed test we take a screenshot. If taking the screenshot fails, we consider that to be a "fatal" error and we kill the Appium server (which in turn kills the emulator) and then we start the server again (which opens the emulator since we pass the `avd` capability).

**The issue** that we've recently start seeing is that after a while (sometimes approx 20-30 minutes, sometimes 1 hr) the UIAutomator2 server crashes with the following log entry `[Instrumentation] The process has exited with code 0` - shortly after that we see `Got response with unknown status: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8200}`. Whenever this happens, no other command works (including the screenshot command) and we end up killing the server (and the emulator) and re-opening it.

For instance, during the last test execution, during a 4.3153 Hours window, this issue occurred 9 times.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1 and 1.16.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 10.14.6
* Node.js version (unless using Appium.app|exe): 11.13.0
* Npm or Yarn package manager: Npm 6.4.1
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

I'll get back to you with the logs as they some sensitive information and I'll have to clean them up first.

**Comment by KazuCocoa** [comment]
What version of android platform tools did you use?
I heard by a friend of mine that newer one, perhaps 29.0.6, had an issue to be the emulator offline approximately 1 hour.  They resolved the issue downgrading their platform tools.
https://developer.android.com/studio/releases/platform-tools
I wondered your situation is also similar.

**Comment by cosminstirbu** [comment]
`sdkmanager --list` prints the following output: https://gist.github.com/cosminstirbu/f3bfa1969109ae3fb0e8e7ea59c369fe

From what I can tell, the installed version is `30.0.1`

I'll see if I can downgrade it using `sdkmanager`

**Comment by mykola-mokhnach** [comment]
> I'll get back to you with the logs as they some sensitive information and I'll have to clean them up first.

Unfortunately there is nothing much to do here without the server and device logs

**Comment by cosminstirbu** [comment]
I managed to pin platform-tools to version `29.0.5`.

Also I've disabled some of the non-Appium related logs.

The tests will run overnight and I'll get back to you with the results / logs.

**Comment by cosminstirbu** [comment]
It seems that pinning platform-tools to version `29.0.5`.

I'll close the issue and keep monitoring it in case it comes back.

Thank you @KazuCocoa 

Btw - do you know if your friend reported some sort of bug to Google related to this issue? If not, I'll create one myself and I'll give you the link so he can comment on it as well.

**Comment by KazuCocoa** [comment]
> It seems that pinning platform-tools to version 29.0.5 fixed the issue.

Grad to hear that.

I dont know. Let me ask them

**Comment by KazuCocoa** [comment]
@cosminstirbu
He haven't created an issue. Its appreciated you to create it :)

**Comment by cosminstirbu** [comment]
I've logged the issue here https://issuetracker.google.com/issues/157426075

**Comment by KazuCocoa** [comment]
Awesome. Thanks. Will share the link
