### ISSUE TITLE
TAP in appium inspector clicks the button but nothing happens in UI screen

### ISSUE THREAD

**Issue by narendirasha** [appium/appium#14380]
Using TAP in appium inspector (iOS platform) clicks the button (in Green color) but nothing happens in UI screen which support to navigate to different screen. 

I am running appium desktop version 1.17.0 in mac. Launching app in iPad Air Simulator manually.
Tow Particular buttons with green color BG with button text ENTER and CHECK OUT are not working. Meaning when I manually TAP using the appium inspector screen, nothing happens. But when i tap in simulator it works fine and refresh in inspector it reflects.

But in other screens other buttons with green color background is working fine when I hit TAP manually after selecting the button in appium inspector, meaning UI renders in inspector itself.

**NOTE:** 
1.This happens only in Tablet form factor (IPad Air, IPad similators) but works fine in Phone form factor (Iphone 8 simulator). Both have same iOS version 13.3
2.I have double checked the button instance is not repeated. Its only one unique button with text CHECK OUT

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:  MAC OS MOJAVE version 10.14.6
* Node.js version (unless using Appium.app|exe):  Using appium Desktop 
* Npm or Yarn package manager:  npm version 3.10.10
* Mobile platform/version under test: iOS 13.3
* Real device or emulator/simulator: iPad Air Simulator (Please refer Note above)
* Appium CLI or Appium.app|exe: Appium desktop

## Details

{
  "platformName": "iOS",
  "deviceName": "iPad Air",
  "automationName": "XCUITest",
  "app": "/Users/Username/Desktop/XXXX.app",
  "udid": "5517A994-0BC8-41B4-XXXX-7E5FDBDB3E39",
  "platformVersion": "13.3",
  "bundleId": "com.xxxx.app"
}

This happens only in Tablet form factor (IPad Air, IPad similators) but works fine in Phone form factor (Iphone 8 simulator). Both have same iOS version 13.3

![image](https://user-images.githubusercontent.com/5410813/82930707-720a8880-9fa3-11ea-8635-0b8302b1d08b.png)

## Link to Appium logs

https://gist.github.com/narendirasha/969b347c8457a41fe259e325382bdb50

## Code To Reproduce Issue [ Good To Have ]

No code. I am trying to click on TAP in appium inspector after selecting the CHECKOUT button in the view.
![image](https://user-images.githubusercontent.com/5410813/82931240-38864d00-9fa4-11ea-9700-1e72a409150d.png)

[{"key":"elementId","value":"D3000000-0000-0000-820E-010000000000","name":"elementId"},{"key":"type","value":"XCUIElementTypeButton","name":"type"},{"key":"name","value":"CHECK OUT","name":"name"},{"key":"label","value":"CHECK OUT","name":"label"},{"key":"enabled","value":"true","name":"enabled"},{"key":"visible","value":"true","name":"visible"},{"key":"x","value":"230","name":"x"},{"key":"y","value":"602","name":"y"},{"key":"width","value":"130","name":"width"},{"key":"height","value":"50","name":"height"}]

**Comment by mykola-mokhnach** [comment]
Taps are generated by XCTest. There is nothing we could do about it on Appium side.
You could try to tap by coordinates as a workaround.

**Comment by narendirasha** [comment]
Thanks @mykola-mokhnach  Using tap by coordinates working. Our concern is about since we are testing in different platforms with different form factors (Windows RP9 touch screen, iPads of different sizes, ipods, iphones, and android phones), maintaining X,Y co-ordinating for all these in the code will be difficult for us. So we are trying to find any other common work around.

**Comment by mykola-mokhnach** [comment]
Unfortunately, I don't have any good suggestion there. Different issues with tablets was there [forever](https://github.com/facebookarchive/WebDriverAgent/issues/856), but Apple never had time to take care about it.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
