### ISSUE TITLE
UiAutomatorViewer not showing entire UI tree for app on AndroidTV

### ISSUE THREAD

**Issue by iamsethi** [appium/appium#14385]
## The problem

I am trying to analyze the UI components currently displayed on YouTube app in Android TV using UIAutomatorViewer

## Environment

* Appium version : 1-17-0
* Desktop OS/version used to run Appium: MAC
* Node.js version (exe): 12.16.2
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Android TV
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

On Taking UI XML snapshot i am not able to capture entire UI components.The UI which is captured is mentioned in gist

## Link to Appium logs

[UI XML snapshot](https://gist.github.com/iamsethi/994a5c2b7e164b5a5a621f506662db93)

## Code To Reproduce Issue

Install YouTube app on Android TV
Open Ui Automator Viewer
Take UI XML Screenshot

**Comment by mykola-mokhnach** [comment]
Ui Automator Viewer is he tool from Google. Appium has nothing to do with it, so we cannot help much there.
