### ISSUE TITLE
Appium Server logs an error with uiautomator2 when running the server by command line

### ISSUE THREAD

**Issue by AntoData** [appium/appium#14387]
## The problem

I am working in this project to create an appium framework in python (similar to selenium frameworks). The project works fine if I start appium server using the desktop application, but if I try to start the server using the command line "appium" it doesn't start the apk (installed in the device already).

## Environment

* appium client 1.0.0
* Windows 10:
* Node.js '12.16.3':
* Npm 6.14.4:
* Android 10:
* Simulator: Pixel_XL
* Appium CLI or Appium.app|exe:

## Details

I am trying to run a test suite in Python that inherits from unittest.TestCase. If I run the appium desktop application and start the server, everything goes smoothly. However, if I try to start the server using appium command in command line (to be able to extend the framework so both the device and the appium server start programmatically) we get several errors related to uiautomator2 and no instrumentation found.

## Link to Appium logs

https://gist.github.com/AntoData/93d788f56afc1d64d5062e6bf34d8d54

## Code To Reproduce Issue [ Good To Have ]

https://github.com/AntoData/appium-framework/blob/master/test_suites/instagram_suite.py

**Comment by mykola-mokhnach** [comment]
> [debug] [ADB] Running 'C:\Users\ingov\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 install -r C:\\Users\\ingov\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-debug-androidTest.apk'
> [ADB] The installation of 'appium-uiautomator2-server-debug-androidTest.apk' took 103ms
> [debug] [ADB] Install command stdout: Serving...
> [debug] [ADB] Performing Incremental Install
> [debug] [ADB]
> [debug] [ADB] Exception occurred while executing: Incremental installation not allowed.
> [debug] [ADB] java.lang.IllegalArgumentExce...
> [debug] [ADB]   at android.os.Binder.execTransactInternal(Binder.java:1159)
> [debug] [ADB]   at android.os.Binder.execTransact(Binder.java:1123)

This looks like an issue with adb. Try to revert Android SDK to the recent stable version or report the issue to Google

**Comment by AntoData** [comment]
But why does it work if I use the desktop application?

**Comment by AntoData** [comment]
I updated Android Studio, reinstalled Android 10 SDK and same result

**Comment by mykola-mokhnach** [comment]
> But why does it work if I use the desktop application?

Because older versions don't support streamed installs.

> I updated Android Studio, reinstalled Android 10 SDK and same result

You could preinstall server binaries manually as a workaround, but this won't solve the original issue.

**Comment by AntoData** [comment]
@mykola-mokhnach how could I do that?

**Comment by mykola-mokhnach** [comment]
adb has (undocumented yet) `--no-incremental` command line argument, which disables incremental install feature. So you could install server binaries manually using the following commands:
`adb install -r --no-incremental <binary_path>`

The exact locations of both binaries on your system are visible in the server log above.

**Comment by AntoData** [comment]
@mykola-mokhnach  Thank you!!!!!
