### ISSUE TITLE
Automate Touch ID in real device(IOS)

### ISSUE THREAD

**Issue by SherbinKassim** [appium/appium#14383]
## The problem

I am trying to automate touch id in iPhone7 real device. but the capabilities tried is working only in simulators.

## Environment

* Appium version (or git revision) that exhibits the issue:v1.15.1
* Desktop OS/version used to run Appium:10.14
* Mobile platform/version under test:13.2
* Real device or emulator/simulator:real device

## Details

I have used performTouchID, toggleTouchIDEnrollment capabilities for automation, but it is working only in simulators

**Comment by mykola-mokhnach** [comment]
Unfortunately there is no known way for Appium to automate touch id on real devices.

**Comment by SherbinKassim** [comment]
Is it possible to do in android real device?

**Comment by mykola-mokhnach** [comment]
No, it is not. Although I can say that some cloud providers have such feature available (although don't share the implementation details with Open Source)
