### ISSUE TITLE
ECONNREFUSED

### ISSUE THREAD

**Issue by sathishkumarkrishnan** [appium/appium#14391]
## The problem

{"recreateChromeDriverSessions":true,"autoAccept":true,"autoLaunch":false,"newCommandTimeout":"6000","appiumVersion":"1.17.1","platformVersion":"12.4","automationName":"XCUITest","browserName":"","platformName":"iOS","deviceName":"iPhone 6s"},"capabilities":{"firstMatch":[{"appium:appiumVersion":"1.17.1","autoAccept":true,"autoLaunch":false,"appium:automationName":"XCUITest","browserName":"","appium:deviceName":"iPhone 6s","appium:newCommandTimeout":"6000","platformName":"ios","appium:platformVersion":"12.4","appium:recreateChromeDriverSessions":true}]}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"recreateChromeDriverSessions":true,"autoAccept":true,"autoLaunch":false,"newCommandTimeout":"6000","appiumVersion":"1.17.1","platformVersion":"12.4","automationName":"XCUITest","browserName":"","platformName":"iOS","deviceName":"iPhone 6s"},null,{"firstMatch":[{"appium:appiumVersion":"1.17.1","autoAccept":true,"autoLaunch":false,"appium:automationName":"XCUITest","browserName":"","appium:deviceName":"iPhone 6s","appium:newCommandTimeout":"6000","platformName":"ios","appium:platformVersion":"12.4","appium:recreateChromeDriverSessions":true}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1590832986247 (15:33:06 GMT+0530 (India Standard Time))
[BaseDriver] The following capabilities are not standard capabilities and should have an extension prefix:
[BaseDriver]   autoAccept
[BaseDriver]   autoLaunch
[BaseDriver] Number capability passed in as string. Functionality may be compromised.
[Appium] Appium v1.17.1 creating new XCUITestDriver (v3.22.0) session
[debug] [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {
[debug] [BaseDriver]   "alwaysMatch": {
[debug] [BaseDriver]     "appium:autoAccept": true,
[debug] [BaseDriver]     "appium:autoLaunch": false,
[debug] [BaseDriver]     "browserName": "",
[debug] [BaseDriver]     "platformName": "ios",
[debug] [BaseDriver]     "appium:appiumVersion": "1.17.1",
[debug] [BaseDriver]     "appium:automationName": "XCUITest",
[debug] [BaseDriver]     "appium:deviceName": "iPhone 6s",
[debug] [BaseDriver]     "appium:newCommandTimeout": "6000",
[debug] [BaseDriver]     "appium:platformVersion": "12.4",
[debug] [BaseDriver]     "appium:recreateChromeDriverSessions": true
[debug] [BaseDriver]   },
[debug] [BaseDriver]   "firstMatch": [
[debug] [BaseDriver]     {}
[debug] [BaseDriver]   ]
[debug] [BaseDriver] }
[BaseDriver] Number capability passed in as string. Functionality may be compromised.
[BaseDriver] Capability 'newCommandTimeout' changed from string ('6000') to integer (6000). This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[BaseDriver]   autoAccept
[BaseDriver]   appiumVersion
[BaseDriver]   recreateChromeDriverSessions
[XCUITest] The desired capabilities include neither an app nor a bundleId. WebDriverAgent will be started without the default app
[BaseDriver] Session created with session id: 97bb959e-b5d0-4063-95ec-6a042dbc504e
[debug] [XCUITest] Current user: 'root'
[XCUITest] iOS SDK Version set to '13.5'
[iOSSim] Constructing iOS simulator for Xcode version 11.5 with udid 'F5A57963-0777-4EC8-996D-3502E7C19707'
[XCUITest] Determining device to run tests on: udid: 'F5A57963-0777-4EC8-996D-3502E7C19707', real device: false
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1590832989051 (15:33:09 GMT+0530 (India Standard Time))
[debug] [BaseDriver] Event 'appConfigured' logged at 1590832989051 (15:33:09 GMT+0530 (India Standard Time))
[debug] [BaseDriver] Event 'resetStarted' logged at 1590832989052 (15:33:09 GMT+0530 (India Standard Time))
[debug] [BaseDriver] Event 'resetComplete' logged at 1590832989052 (15:33:09 GMT+0530 (India Standard Time))
[XCUITest] Continuing without capturing device logs: iOS Simulator with udid 'F5A57963-0777-4EC8-996D-3502E7C19707' is not running
[XCUITest] Setting up simulator
[debug] [iOS] No reason to set locale
[debug] [iOS] No iOS / app preferences to set
[debug] [iOS] Setting did not need to be updated
[debug] [iOSSim] Setting preferences of F5A57963-0777-4EC8-996D-3502E7C19707 Simulator to {"ConnectHardwareKeyboard":false}
[debug] [iOSSim] Setting common Simulator preferences to {"RotateWindowWhenSignaledByGuest":true,"ConnectHardwareKeyboard":false}
[debug] [iOSSim] Updated F5A57963-0777-4EC8-996D-3502E7C19707 Simulator preferences at '/Users/mac/Library/Preferences/com.apple.iphonesimulator.plist' with {"DevicePreferences":{"F5A57963-0777-4EC8-996D-3502E7C19707":{"ConnectHardwareKeyboard":false}},"RotateWindowWhenSignaledByGuest":true,"ConnectHardwareKeyboard":false}
[debug] [iOSSim] Got Simulator UI client PID: 486
[iOSSim] Booting Simulator with UDID 'F5A57963-0777-4EC8-996D-3502E7C19707'...
[iOSSim] Simulator with UDID F5A57963-0777-4EC8-996D-3502E7C19707 booted in 6.286s
[debug] [BaseDriver] Event 'simStarted' logged at 1590832995738 (15:33:15 GMT+0530 (India Standard Time))
[debug] [IOSSimulatorLog] Starting log capture for iOS Simulator with udid 'F5A57963-0777-4EC8-996D-3502E7C19707' using simctl
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1590832997468 (15:33:17 GMT+0530 (India Standard Time))
[WebDriverAgent] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent'
[WebDriverAgent] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'
[debug] [WebDriverAgent] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[DevCon Factory] Requesting connection for device F5A57963-0777-4EC8-996D-3502E7C19707 on local port 8100, device port 8100
[debug] [DevCon Factory] Cached connections count: 0
[DevCon Factory] Successfully requested the connection for F5A57963-0777-4EC8-996D-3502E7C19707:8100
[debug] [XCUITest] Starting WebDriverAgent initialization with the synchronization key 'XCUITestDriver'
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] Got response with unknown status: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [WebDriverAgent] WDA is not listening at 'http://127.0.0.1:8100/'
[debug] [WebDriverAgent] WDA is currently not running. There is nothing to cache
[debug] [XCUITest] Trying to start WebDriverAgent 2 times with 10000ms interval
[debug] [XCUITest] These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1590832998003 (15:33:18 GMT+0530 (India Standard Time))
[WebDriverAgent] Launching WebDriverAgent on the device
[WebDriverAgent] Fetching dependencies
[WebDriverAgent] Dependencies up-to-date
[debug] [WebDriverAgent] Killing running processes 'xcodebuild.*F5A57963-0777-4EC8-996D-3502E7C19707, F5A57963-0777-4EC8-996D-3502E7C19707.*XCTRunner, xctest.*F5A57963-0777-4EC8-996D-3502E7C19707' for the device F5A57963-0777-4EC8-996D-3502E7C19707...
[debug] [WebDriverAgent] 'pgrep -if xcodebuild.*F5A57963-0777-4EC8-996D-3502E7C19707' didn't detect any matching processes. Return code: 1
[debug] [WebDriverAgent] 'pgrep -if F5A57963-0777-4EC8-996D-3502E7C19707.*XCTRunner' didn't detect any matching processes. Return code: 1
[debug] [WebDriverAgent] 'pgrep -if xctest.*F5A57963-0777-4EC8-996D-3502E7C19707' didn't detect any matching processes. Return code: 1
[debug] [WebDriverAgent] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=F5A57963-0777-4EC8-996D-3502E7C19707 IPHONEOS_DEPLOYMENT_TARGET=12.4 GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent'
[debug] [WebDriverAgent] Output from xcodebuild will only be logged if any errors are present there. To change this, use 'showXcodeLog' desired capability
[debug] [WebDriverAgent] Waiting up to 60000ms for WebDriverAgent to start
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] Got response with unknown status: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 10.5.4 Catalina
* Node.js version (unless using Appium.app|exe): 10.16.3
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: ios 12.4
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: app.ipa

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Please fill out the issue report properly and describe what is the actual and the expected result.

I don't observe any issues in the logs above. The `ECONNREFUSED` response is expected. The driver periodically pings WebDriverAgent server and waits until it is fully started and starts responding to its requests.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
