### ISSUE TITLE
Appium uses wrong device id with extra slash between ip address and port

### ISSUE THREAD

**Issue by kolgenpav** [appium/appium#14397]
## The problem

When I use Appium Server v.1.15.1 with Genymotion virtual device it can not connect to device because of wrong device id  with added extra slash between ip address and port.

## Environment

* Appium version 1.15.1
* Desktop OS/version used to run Appium: Windows 8.1 64 bit
* Node.js version (unless using Appium.app|exe):  Use Appium.exe
* Npm or Yarn package manager: npm
* Mobile platform/version under test:  5.1 - API 22
* Real device or emulator/simulator: Genymotion v.3.1.0
* Appium CLI or Appium.app|exe: Appium.exe

## Details

When I use real device, Appium connects to it and installs app. Device id is 52001a65fe66c45d. From log I see that appium uses adb with device id, for example:
Running 'C:\Users\kgp\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 52001a65fe66c45d shell getprop ro.build.version.sdk'

But when I use Genymotion emulator device id is ip address and port - 192.168.39.101:5555.
And appium uses adb with wring device id (added extra slash between IP address and port), for example:
Running 'C:\Users\kgp\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 192.168.39.101\:5555 shell 'pgrep --help; echo $?''

When I run the command in command prompt I see:
error: device '192.168.39.101\:5555' not found

With slash deleted I connected to the device:
C:\Users\kgp\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 192.168.39.101:5555 shell 'pgrep --help; echo $?

## Link to Appium logs
[appium-server-genymotion-FAILED-log.txt](https://gist.github.com/kolgenpav/5d2eaa40a476b04ad052dbaa642a22cb)

## Code To Reproduce Issue [ Good To Have ]
Used desired capabilities:
```
{
  "platformName": "Android",
  "platformVersion": "5.1",
  "automationName": "UiAutomator2",
  "app": "c:\\Users\\kgp\\Dropbox\\EDU\\YPZT\\HelloAppium\\app\\quikr.apk",
  "newCommandTimeout": 7200,
  "fullReset": true,
  "udid": "192.168.39.101:5555",
  "deviceName": "device"
}
```

**Comment by mykola-mokhnach** [comment]
- Please use the most recent server version
- The provided link to the server log is not valid. Please fix it

**Comment by kolgenpav** [comment]
Thank you for the quick response. 
I fixed link to logfile.
I use the latest release appium-desktop v.1.15.1 from [appium-desktop repository](https://github.com/appium/appium-desktop/releases/tag/v1.15.1).  What most recent server version do You mean?

**Comment by mykola-mokhnach** [comment]
Currently the most stable server version is 1.17.1

**Comment by kolgenpav** [comment]
After upgrading to server version 1.17.1 Inspector session started correctly. 
But in logfile remains extra slash between ip address and port in device id. I think it may be escape character added for Windows paths.

Thank You for Your advice.

**Comment by mykola-mokhnach** [comment]
appium-adb uses https://www.npmjs.com/package/shell-quote library to log command lines, which are originally represented as arrays. This means the logged command line string might differ from what is actually passed to the low level system `exec` call.
