### ISSUE TITLE
unable to detect webcontext after upgrading to chrome 83

### ISSUE THREAD

**Issue by Amrkamel1** [appium/appium#14403]
## The problem

after upgrading chrome to v83 on mobile noticed that appium is detecting no web context, same script was working fine, also chrome remote inspector not detecting the hybrid app 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1
* Last Appium version that did not exhibit the issue (if applicable): 1.71.1
* Desktop OS/version used to run Appium: all
* Node.js version (unless using Appium.app|exe): 12
* Npm or Yarn package manager: 6
* Mobile platform/version under test: android
* Real device or emulator/simulator: real devices.emulator
* Appium CLI or Appium.app|exe:  CLI/desktop

## Details
unable to switch to webcontext, chrome inspector not detecting the app as well

![webcontext](https://user-images.githubusercontent.com/32042806/83447773-3bc08380-a451-11ea-8c75-7c2cd85400de.png)

## Link to Appium logs

```
[debug] [W3C (5b0ceca8)] Calling AppiumDriver.getContexts() with args: ["5b0ceca8-985e-4e30-a921-d1798366ee45"]
[debug] [AndroidDriver] Getting a list of available webviews
[debug] [ADB] Running '/home/amrka/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell cat /proc/net/unix'
[AndroidDriver] Retrieved potential webviews; will filter out ones with no active pages
[debug] [AndroidDriver] Found webviews: []
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP"]
[debug] [W3C (5b0ceca8)] Responding to client with driver.getContexts() result: ["NATIVE_APP"]
[HTTP] <-- GET /wd/hub/session/5b0ceca8-985e-4e30-a921-d1798366ee45/contexts 200 20 ms - 24
```

## Code To Reproduce Issue [ Good To Have ]

```
    protected boolean switchToWebContext() {
        ArrayList<String> contexts = new ArrayList(driver.getContextHandles());
        for (String context : contexts) {
            if (context.contains("WEBVIEW")) {
                driver.context(context);
                return true;
            }
        }
        return false;
    }

    protected boolean switchToNativeContext() {
        ArrayList<String> contexts = new ArrayList(driver.getContextHandles());
        for (String context : contexts) {
            if (context.equals("NATIVE_APP")) {
                driver.context(context);
                return true;
            }
        }
        return false;
    }

```

**Comment by mykola-mokhnach** [comment]
If Chrome cannot detect it then no way Appium could do it :(

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing more we could do about it. 
Closed as not issue
