### ISSUE TITLE
getPerformanceData not work

### ISSUE THREAD

**Issue by windyrain** [appium/appium#14409]
## The problem

getPerformanceData not work

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: mac 10.15.4
* Node.js version (unless using Appium.app|exe): 12.17.0
* Npm or Yarn package manager: yarn
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium.app

## Details

I am use javascript-wd
driver = wd.promiseChainRemote(serverConfig);

## Link to Appium logs

[Log](https://gist.github.com/windyrain/11f1091d13814a15b1ed3e84dbb1c68f)

## Code To Reproduce Issue [ Good To Have ]

const memory = await driver.getPerformanceData('com.ks.test', 'memory', 5);
console.log(memory);

**Comment by mykola-mokhnach** [comment]
The error is expected. This endpoint only works for Android

**Comment by windyrain** [comment]
> The error is expected. This endpoint only works for Android

thank you! how can I get memory after auto operations for iOS，is there any guide?

**Comment by mykola-mokhnach** [comment]
Check `mobile: startPerfRecord`/`mobile: stopPerfRecord`. Although, I've seen instrument APIs had issues in the recent Xcode releases.

**Comment by windyrain** [comment]
> Check `mobile: startPerfRecord`/`mobile: stopPerfRecord`. Although, I've seen instrument APIs had issues in the recent Xcode releases.

thank you !
