### ISSUE TITLE
iOS simulator(safari): how to wait for the page is completely open?

### ISSUE THREAD

**Issue by DudaGod** [appium/appium#14407]
## The problem

I found that page in ios simulator is opened with this code - https://github.com/appium/appium-ios-driver/blob/6cfcbc9b2a22a7b1c8fa0c55f8462f10024f39c9/lib/commands/general.js#L229 inside which is called something like - `xcrun simctl openurl booted https://github.com`. How we know xcrun it is simply binary file which send action to simulator and does not wait anything.

So how we can wait for the page is completely open before execute next command?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0
* Desktop OS/version used to run Appium: MacOS
* Node.js version (unless using Appium.app|exe): 8.6.0
* Npm or Yarn package manager: npm@6.2.0
* Mobile platform/version under test: Safari 13
* Real device or emulator/simulator: iOS simulator
* Appium CLI or Appium.app|exe: cli

## Code To Reproduce Issue [ Good To Have ]

My simple server which is respond after 5 seconds:
```
const Promise = require('bluebird');
var express = require('express');
var app = express();

app.get('/', async function (req, res) {
    await Promise.delay(5000);
    res.send('Hello World!');
});

app.listen(3000, function () {
    console.log('Server listening on port 3000!');
});
```

And my test on wdio:
```
'use strict';

const webdriverio = require('webdriverio');

const browser = webdriverio.remote({
    host: 'localhost',
    port: '4444',
    path: '/wd/hub',
    desiredCapabilities: {
        platformName: 'iOS',
        platformVersion: '13.3',
        version: '13.0',
        deviceName: 'iPhone 11',
        browserName: 'safari',
        automationName: 'XCUITest'
    }
});

browser
    .init()
    .url('http://localhost:3000')
    .getText('body')
    .then((text) => {
        console.log('CURRENT TEXT:', text);
    });
```

In console log I expect to see - `Hello World!` but I get only default text - `Let's browse!`

**Comment by amedvedjev** [comment]
suggestion look at check document.readyState with javaScript executor

**Comment by DudaGod** [comment]
It does not work =(
I get `complete` state even if my page not loaded yet.

@KazuCocoa hello. Do you have any thoughts about this problem?

**Comment by KazuCocoa** [comment]
I only did caling find_element with client side wait in such case. I mean like `wait { driver.find_element :id, 'xxxx' }`.
Unfortunately, xcrun command does not have such wait feature, so I called find_element method repeatedly. The target of find_element was an element that must have appeared on the view for viewers as the app under test.

**Comment by DudaGod** [comment]
Okay, I understand. It was my fallback if there is no other solution.
Thank you.
