### ISSUE TITLE
Appium 17.1 cannot start session with iPhone

### ISSUE THREAD

**Issue by chuklov** [appium/appium#14413]
After the upgrade of Appium from 15 to 17 I cannot connect any iPhone. All project files are the same as were and nothing was changed. Error message is the following:

An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65 xcodebuild error message: 2020-06-04 09:22:02.090 xcodebuild[2408:21227] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/chuklova/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7f93eb6d1e20 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}} Test session results, code coverage, and logs: /Users/chuklova/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu/Logs/Test/Test-WebDriverAgentRunner-2020.06.04_09-22-01-+0300.xcresult Testing failed: WebDriverAgentRunner: WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file. The file doesn’t exist. (Underlying error: The operation couldn’t be completed. No such file or directory))) ** TEST EXECUTE FAILED ** Testing started on 'Alexander’s iPhone'. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.

## Environment

* Appium version 17.1
* Desktop OS/version Mac OS Mojave

## Link to Appium logs

<script src="https://gist.github.com/chuklov/25d9a34d97224aa4fefe1f1ac4ef6a94.js"></script>

## Reproduction of the issue:
I cannot start Inspect session. Non of my projects can work anymore.

**Comment by mykola-mokhnach** [comment]
Did you follow the troubleshooting link above? Is WDA source buildable manually via Xcode?

**Comment by chuklov** [comment]
Did you follow the troubleshooting link above? - it was working for a year and suddenly after the upgrade everything broken. Link shows how to connect at a first time. 

WDA is installed on all devices and installed from Xcode, Integration app works fine. 

Appium doctor shows no issues.

**Comment by mykola-mokhnach** [comment]
>  Link shows how to connect at a first time.

Again, have you tried to deploy the sources manually? This is also described in the tutorial?

**Comment by KazuCocoa** [comment]
and did your environment has the below file? Your capability had `usePrebuiltWDA` option, so Appium expected the WDA app was already there. (The path in DerivedData was managed by your Xcode.)

> /Users/chuklova/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app

**Comment by chuklov** [comment]
I have tried to create it manually from Xcode, from command line and both works fine.

**Comment by mykola-mokhnach** [comment]
I second @KazuCocoa `usePrebuiltWDA` enforces xcodebuild to use prebuilt binaries, but there are none, because a fresh install has been performed after server upgrade.

**Comment by chuklov** [comment]
this is a build folder, it is always created after you launch Xcode or Appium:
drwxr-xr-x   4 chuklova  1044286834   128B Jun  4 09:48 WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp
drwxr-xr-x@ 10 chuklova  1044286834   320B Jun  4 10:36 WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu

Another question is why Appium stopped recognise capabilities?

[BaseDriver] Creating session with MJSONWP desired capabilities: {
[BaseDriver]   "agentPath": "/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj",
[BaseDriver]   "automationName": "XCUITest",
[BaseDriver]   "bootstrapPath": "/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/",
[BaseDriver]   "bundleId": "com.checkpoint.capsuleprotect",
[BaseDriver]   "clearSystemFiles": true,
[BaseDriver]   "deviceName": "iPhone",
[BaseDriver]   "noReset": true,
[BaseDriver]   "platformName": "ios",
[BaseDriver]   "platformVersion": "12.2",
[BaseDriver]   "preventWDAAttachments": true,
[BaseDriver]   "udid": "bd3ccfde1c14ef869656292b0460da522728aedc",
[BaseDriver]   "useNewWDA": false,
[BaseDriver]   "usePrebuiltWDA": true,
[BaseDriver]   "xcodeOrgId": "2ES97B4EP7",
[BaseDriver]   "xcodeSigningId": "iPhone Developer",
[BaseDriver]   "newCommandTimeout": 0,
[BaseDriver]   "connectHardwareKeyboard": true
[BaseDriver] }
[BaseDriver] The following capabilities were provided, but are **not recognized** by Appium:

**Comment by mykola-mokhnach** [comment]
The `preventWDAAttachments` capability has been removed, because Apple has finally added such option to the native xctest config in newer Xcode versions. The one used before was just an ugly workaround.

**Comment by mykola-mokhnach** [comment]
> this is a build folder, it is always created after you launch Xcode or Appium:

Appium is just a proxy. It compiles and executes xcodebuild command line according to the provided capabilities. If the command fails then the first thing to do it to execute the same command manually and figure out what the issue is on Xcode side.

**Comment by chuklov** [comment]
Resolution is the following:
Remove Appium desktop
Remove Appium npm -g uninstall 
Remove all drivers from iPhone 
Install npm Appium
Install Appium desktop 
Sign and change Xcode project (as from clean installation guid)
Install driver on iPhone
Reboot MAC and Phones 

Looks like now it is working
