### ISSUE TITLE
javascript-webdriverio sample code broken after update to webdriverio 6

### ISSUE THREAD

**Issue by euoia** [appium/appium#14415]
## The problem

I tried to run the sample code here:
https://github.com/appium/appium/tree/master/sample-code/javascript-webdriverio

And received an error about the `/session` URL:

```
$ mocha test/basic/ios*.test.js
...
2020-06-04T10:10:34.784Z ERROR webdriver: Request failed with status 404 due to Error: The URL '/session' did not map to a valid resource
```

Reverting commit d5119da, which updated the webdriverio dependency from version 5 to 6, (then running `npm install`) fixed the issue.

## Environment

* Appium version: 220c9aeb
* Desktop OS/version used to run Appium: Mac OS Catalina 10.15.4
* Node.js version (unless using Appium.app|exe): v12.16.3
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS 13.5, iPhone SE (2nd generation)
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium.app

## Link to Appium logs

Logs from running the tests:
https://gist.github.com/euoia/441e10c7d3a298dfa31141b4d2a71a92

Appium logs:
https://gist.github.com/euoia/d7caa6fa8e9b3cede52f4bb2491132e6

## Code To Reproduce Issue [ Good To Have ]

n/a

**Comment by KazuCocoa** [comment]
ah, thanks.
We've only updated getting started. Perhaps this option is needed to add in sample code https://github.com/appium/appium/blob/master/sample-code/javascript-webdriverio/helpers/caps.js, too.
https://github.com/appium/appium/pull/14120/files

**Comment by euoia** [comment]
Ah thanks for looking into it for me. I also have a few comments about the getting started guide (one of them was that it would be nice to have the `path: '/wd/hub'` option documented). Where's the best place to talk about those?

**Comment by KazuCocoa** [comment]
Creating a PR is the best :)

**Comment by khanhdodang** [comment]
cc @KazuCocoa https://github.com/appium/appium/pull/14471
