### ISSUE TITLE
Appium: cant connect the server

### ISSUE THREAD

**Issue by KadyrovaEkaterina** [appium/appium#14411]
Good afternoon,
I have an issue to run the code. I am new to Appium and trying to learn myself.
Below is the code I have to to run to invoke the app.
I would truly appreciate if you could help me out to solve the issue.
Thank you!

               File f = new File ("src");
		File fs= new File (f, "original.apk");
		
		DesiredCapabilities cp = new DesiredCapabilities ();
		cp.setCapability(MobileCapabilityType.DEVICE_NAME, "emulator");
		cp.setCapability(MobileCapabilityType.AUTOMATION_NAME, "uiautomator2");
		cp.setCapability(MobileCapabilityType.APP, fs.getAbsolutePath());
		
		AndroidDriver<AndroidElement> driver =new AndroidDriver<>(new URL ("http://127.0.0.2:4723/wd/hub"), cp);

here are the logs i have:
[Appium] Welcome to Appium v1.17.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"C:\Users\dkady_000\eclipse-workspace\AppiumTutorial\src\original.apk","automationName":"uiautomator2","platformName":"Android","deviceName":"Kateemulator"},"capabilities":{"firstMatch":[{"appium:app":"C:\Users\dkady_000\eclipse-workspace\AppiumTutorial\src\original.apk","appium:automationName":"uiautomator2","appium:deviceName":"Kateemulator","platformName":"android"}]}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"app":"C:\Users\dkady_000\eclipse-workspace\AppiumTutorial\src\original.apk","automationName":"uiautomator2","platformName":"Android","deviceName":"Kateemulator"},null,{"firstMatch":[{"appium:app":"C:\Users\dkady_000\eclipse-workspace\AppiumTutorial\src\original.apk","appium:automationName":"uiautomator2","appium:deviceName":"Kateemulator","platformName":"android"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1591209037806 (14:30:37 GMT-0400 (Eastern Daylight Time))
[Appium] Appium v1.17.1 creating new AndroidUiautomator2Driver (v1.44.2) session
[debug] [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {
[debug] [BaseDriver] "alwaysMatch": {
[debug] [BaseDriver] "platformName": "android",
[debug] [BaseDriver] "appium:app": "C:\Users\dkady_000\eclipse-workspace\AppiumTutorial\src\original.apk",
[debug] [BaseDriver] "appium:automationName": "uiautomator2",
[debug] [BaseDriver] "appium:deviceName": "Kateemulator"
[debug] [BaseDriver] },
[debug] [BaseDriver] "firstMatch": [
[debug] [BaseDriver] {}
[debug] [BaseDriver] ]
[debug] [BaseDriver] }
[BaseDriver] Session created with session id: 1d2f6e4c-305f-4895-b7b2-ecbad4ae121e
[BaseDriver] Using local app 'C:\Users\dkady_000\eclipse-workspace\AppiumTutorial\src\original.apk'
[debug] [UiAutomator2] Checking whether app is actually present
[ADB] Found 2 'build-tools' folders under 'C:\Users\dkady_000\AppData\Local\Android\Sdk' (newest first):
[ADB] C:/Users/dkady_000/AppData/Local/Android/Sdk/build-tools/30.0.0-rc4
[ADB] C:/Users/dkady_000/AppData/Local/Android/Sdk/build-tools/29.0.3
[ADB] Using 'adb.exe' from 'C:\Users\dkady_000\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] Connected devices: [{"udid":"emulator-5554","state":"device"}]
[AndroidDriver] Using device: emulator-5554
[ADB] Using 'adb.exe' from 'C:\Users\dkady_000\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[debug] [ADB] Setting device id to emulator-5554
[debug] [ADB] Running 'C:\Users\dkady_000\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk'
[debug] [ADB] Current device property 'ro.build.version.sdk': 29
[ADB] Getting device platform version
[debug] [ADB] Running 'C:\Users\dkady_000\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.release'
[debug] [ADB] Current device property 'ro.build.version.release': 10
[debug] [ADB] Device API level: 29
[UiAutomator2] Relaxing hidden api policy
[debug] [ADB] Running 'C:\Users\dkady_000\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell settings put global hidden_api_policy_pre_p_apps 1'
[debug] [UiAutomator2] Deleting UiAutomator2 session
[UiAutomator2] Restoring hidden api policy to the device default configuration
[debug] [ADB] Running 'C:\Users\dkady_000\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell settings delete global hidden_api_policy_pre_p_apps'
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1591209055554 (14:30:55 GMT-0400 (Eastern Daylight Time))
[debug] [W3C] Encountered internal error running command: Error executing adbExec. Original error: 'Command 'C:\Users\dkady_000\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell settings delete global hidden_api_policy_pre_p_apps' exited with code 20'; Stderr: 'cmd: Can't find service: settings'; Code: '20'
[debug] [W3C] Error: Command 'C:\Users\dkady_000\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell settings delete global hidden_api_policy_pre_p_apps' exited with code 20
[debug] [W3C] at ChildProcess. (C:\Users\dkady_000\AppData\Roaming\npm\node_modules\appium\node_modules\teen_process\lib\exec.js:113:19)
[debug] [W3C] at ChildProcess.emit (events.js:310:20)
[debug] [W3C] at maybeClose (internal/child_process.js:1021:16)
[debug] [W3C] at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
[debug] [W3C] Destroying socket connection
[HTTP] <-- POST /wd/hub/session 500 18759 ms - 1177
[HTTP]

**Comment by mykola-mokhnach** [comment]
See https://github.com/appium/appium/issues/12736#issuecomment-638412661

this looks like an issue with the local emulator image

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
