### ISSUE TITLE
Could not restart test - some connection active

### ISSUE THREAD

**Issue by Phoenix124** [appium/appium#14417]
## The problem

Try to rerun test but and error occurred

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.0 beta
* Desktop OS/version used to run Appium: macOS 10.15.5
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 13.5
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI

## Details

```
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1591367395041 (17:29:55 GMT+0300 (Moscow Standard Time))
[debug] [MJSONWP] Encountered internal error running command: Error: Command 'ps -p 18173 -o command' exited with code 1
[debug] [MJSONWP]     at ChildProcess.proc.on.code (/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/node_modules/teen_process/lib/exec.js:113:19)
[debug] [MJSONWP]     at ChildProcess.new_callback (/usr/local/lib/node_modules/appium/node_modules/longjohn/dist/longjohn.js:188:25)
[debug] [MJSONWP]     at ChildProcess.emit (events.js:198:13)
[debug] [MJSONWP]     at maybeClose (internal/child_process.js:982:16)
[debug] [MJSONWP]     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
[debug] [MJSONWP] Destroying socket connection
```

**Comment by mykola-mokhnach** [comment]
Please provide the full log

**Comment by Phoenix124** [comment]
@mykola-mokhnach will try to reproduce, when quit simulator and run - it's ok

**Comment by Phoenix124** [comment]
@mykola-mokhnach logs
https://gist.github.com/Phoenix124/0c74b9f97787dbf4b62b4db5371b126b

**Comment by mykola-mokhnach** [comment]
The patch has been published to appium@beta

**Comment by mykola-mokhnach** [comment]
@Phoenix124 By the way, appium@beta supports a feature, which automatically replaces sensitive info in server logs. There is no need to do that manually anymore. Check https://github.com/appium/appium/pull/14239/files for more details

**Comment by Phoenix124** [comment]
@mykola-mokhnach Thanks!

**Comment by mykola-mokhnach** [comment]
closed as fixed
