### ISSUE TITLE
Concerning DevCon Factory output when specifying webDriverAgentUrl

### ISSUE THREAD

**Issue by grant-mccarriagher** [appium/appium#14427]
## The problem

We create/maintain WebDriverAgent connections manually for our pool of real iOS devices. As such, we always pass in the `webDriverAgentUrl` capability in our test sessions. For the most part, this seems to work fine, but I noticed some concerning Appium output while investigating some other issues. When creating a new WDA session, there are a few lines of output that suggest Appium is still trying to create a new WDA test connection on a default port, instead of using the existing WDA server.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1
* Last Appium version that did not exhibit the issue (if applicable): Unknown
* Desktop OS/version used to run Appium: macOS 10.15.4
* Node.js version (unless using Appium.app|exe): 12.13.1
* Npm or Yarn package manager: 6.12.1
* Mobile platform/version under test: iOS 13.3
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: CLI

## Details

Here's the partial output that's concerning:

```
2020-06-08 20:23:24:376 - [WebDriverAgent] Using WDA path: '/Users/jenkins/.nvm/versions/node/v12.13.1/lib/node_modules/appium/node_modules/appium-webdriveragent'
2020-06-08 20:23:24:376 - [WebDriverAgent] Using WDA agent: '/Users/jenkins/.nvm/versions/node/v12.13.1/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'
2020-06-08 20:23:24:376 - [DevCon Factory] Requesting connection for device 00008020-0014359E2E78003A on local port 8100, device port 8100
2020-06-08 20:23:24:376 - [debug] [DevCon Factory] Cached connections count: 0
2020-06-08 20:23:24:377 - [DevCon Factory] Successfully requested the connection for 00008020-0014359E2E78003A:8100
2020-06-08 20:23:24:378 - [debug] [XCUITest] Starting WebDriverAgent initialization with the synchronization key 'XCUITestDriver'
2020-06-08 20:23:24:378 - [debug] [XCUITest] Trying to start WebDriverAgent 1 times with 10000ms interval
2020-06-08 20:23:24:378 - [debug] [XCUITest] These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
2020-06-08 20:23:24:379 - [debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1591662204379 (20:23:24 GMT-0400 (Eastern Daylight Time))
```

I'll also include the rest of the Appium logs in the next section below.

## Link to Appium logs

https://gist.github.com/grant-mccarriagher/8294994affe4834dff22a22d010036c5

**Comment by KazuCocoa** [comment]
It is expected since the port 8100 is for port forward which can customise by `wdaLocalPort`. xcuitest driver handles the connected device via the port such as pushing files to the device.
webDriverAgentUrl is only for communication between WDA and xcuitest-driver.
(I'd like to wait for @mykola-mokhnach 's knowledge, too)

**Comment by mykola-mokhnach** [comment]
This looks like an issue to me. Let me change some stuff

**Comment by mykola-mokhnach** [comment]
@grant-mccarriagher Could you please verify if https://github.com/appium/WebDriverAgent/pull/342 works for you?

**Comment by grant-mccarriagher** [comment]
@mykola-mokhnach I'm still seeing the same output I pasted above, but perhaps I'm not testing correctly. I installed off of `appium@beta`, and also tried just manually making that code change to yarn's installed `appium-webdriveragent` (restarting Appium between tests), neither changed that DevCon output I posted.

Please let me know if there's some other way to grab those changes for testing.

**Comment by grant-mccarriagher** [comment]
Setting `wdaLocalPort` per @KazuCocoa did change the output to the expected port though. Is it recommended to set both `wdaLocalPort` and `webDriverAgentUrl` when using a manually created WDA connection?

**Comment by mykola-mokhnach** [comment]
>  I installed off of appium@beta, and also tried just manually making that code change to yarn's installed appium-webdriveragent (restarting Appium between tests), neither changed that DevCon output I posted.

It won't work like that. You need to clone the module from that branch and `npm link` it to do the testing. Check https://github.com/appium/appium/issues/13227#issuecomment-531812534 for more details

**Comment by grant-mccarriagher** [comment]
Thanks, this is what I see now:

```
[debug] [Support] Traversed 24 directories and 101 files in 1782ms
[debug] [XCUITest] Pushed the app files successfully after 1905ms
[XCUITest] App installation succeeded after 2620ms
[debug] [XCUITest] The app has been installed successfully.
[debug] [BaseDriver] Event 'appInstalled' logged at 1591723399325 (13:23:19 GMT-0400 (Eastern Daylight Time))
[DevCon Factory] Requesting connection for device bd0f6967af3eee3d526fe3e28ca38d8f50aa7430 on local port 8103, device port 8100
[debug] [DevCon Factory] Cached connections count: 0
[DevCon Factory] Successfully requested the connection for bd0f6967af3eee3d526fe3e28ca38d8f50aa7430:8103
[debug] [XCUITest] Starting WebDriverAgent initialization with the synchronization key 'XCUITestDriver'
[debug] [XCUITest] Trying to start WebDriverAgent 1 times with 10000ms interval
[debug] [XCUITest] These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
```

Is `local port 8103, device port 8100` correct? I'm running my WDA connections like so:

```
USE_PORT=8103 xcodebuild clean build test -project "/Users/admin/WebDriverAgent/WebDriverAgent.xcodeproj" -scheme WebDriverAgentRunner -destination id=bd0f6967af3eee3d526fe3e28ca38d8f50aa7430 -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=13.2
```

**Comment by mykola-mokhnach** [comment]
yes, this is better. 

Regarding the remote port - cannot actually retrieve it in such case. I'll change the logs

**Comment by grant-mccarriagher** [comment]
Thanks for the quick turn around. In the meantime, if I don't want to update Appium on my build devices, does using the `wdaLocalPort` capability accomplish the same thing here?

**Comment by mykola-mokhnach** [comment]
the device connection factory is used to track active connections and avoid connecting two parallel sessions to the same port. This means that it is safe to keep everything as is unless it causes issues (except of confusing logs :) )

**Comment by grant-mccarriagher** [comment]
👍
