### ISSUE TITLE
sendkeys or clear is not clearing entire text when using IOS

### ISSUE THREAD

**Issue by Amrkamel1** [appium/appium#14426]
## Appium or Appium Desktop?

whenever im trying to send keys or clear an input text field only first letter removed on the ios 
(v 13)app version while its fine on android version

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

![ios_clear](https://user-images.githubusercontent.com/32042806/84055942-cfe09c80-a9b5-11ea-8226-6e2c0ddbde03.gif)

## Environment

- I am running Appium Desktop version 1.17.1-1.
- I am on (pick one):
    - [ ] Linux

**Comment by Amrkamel1** [comment]
@KazuCocoa 

here is the log 
[log.txt](https://github.com/appium/appium/files/4750693/log.txt)

**Comment by cheffey** [comment]
> @Amrkamel1 
Clear is not a great command, I bypass this command because it's really slow. The way I do it is: element.sendkeys("/b/b/b/b/b/b");
/b will be interpret as BACKSPACE to delete the context.

**Comment by Amrkamel1** [comment]
@cheffey 
> > Clear is not a great command, I bypass this command because it's really slow. The way I do it is: element.sendkeys("/b/b/b/b/b/b");
> > /b will be interpret as BACKSPACE to delete the context.
thanks for the suggestion i will try it 

issue that the the typing pointer is starting from first letter of the text not from the end of the text so i can make backspace

i think even this command will just delete first letter only but will try and see

**Comment by KazuCocoa** [comment]
How about with the latest Appium 1.17.1?

For native context, it has some improvements. For web context, probably Appium cannot do anything since commands for webcontext are handled by Web View (safari) side. Appium only sends commands to them via Web Inspector.

**Comment by Amrkamel1** [comment]
> How about with the latest Appium 1.17.1?
> 
> For native context, it has some improvements. For web context, probably Appium cannot do anything since commands for webcontext are handled by Web View (safari) side. Appium only sends commands to them via Web Inspector.

okay i will try however same code works fine on iphone 8 plus v 11

**Comment by KazuCocoa** [comment]
hm, thanks.

> however same code works fine on iphone 8 plus v 11

Then, it's perhaps nothing we can do as Appium. The difference could happen behind methods by Apple

**Comment by Amrkamel1** [comment]
> hm, thanks.
> 
> > however same code works fine on iphone 8 plus v 11
> 
> Then, it's perhaps nothing we can do as Appium. The difference could happen behind methods by Apple

yes could be, issue is explicitly in iphone 13

**Comment by Jiurong-Yang** [comment]
Is it possible for Appium to work around webview issues by sending java_script commands to clear the text?

**Comment by KazuCocoa** [comment]
Yes. `execute_script` calls https://github.com/appium/appium-remote-debugger/blob/002f0b951258ab10c87beae6ff113b27d2b6369e/lib/mixins/execute.js#L98-L117

**Comment by Jiurong-Yang** [comment]
I understand that we can write our own work around to .clear(). I was wondering if that can be the default behavior for.clear() for when the webdriver is in a webview context, it seems like it would fix this issue for both IOS/Android and possibly windows. 

I'm unsure what the currently .clear() does when the webdriver is in a webview context, just to be clear.

**Comment by KazuCocoa** [comment]
It looks the default clear is in https://github.com/appium/appium-remote-debugger/tree/master/atoms These atoms are originally from selenium project
https://github.com/appium/appium-remote-debugger#selenium-atoms

Potentially, we can probably update these atoms, but https://github.com/SeleniumHQ/selenium/commits/master/javascript/atoms/action.js seems has no update about this.

Android depends on chromedriver, btw.

**Comment by Jiurong-Yang** [comment]
This is very helpful. Next time when one of my team member have issues with clear text, I check against the Atom project. Thank you for the clarification.

**Comment by mykola-mokhnach** [comment]
closed as third party issue
