### ISSUE TITLE
UiAutomation not connected! Appium 1.17.1-1

### ISSUE THREAD

**Issue by sriharimobidev** [appium/appium#14430]
## The problem

We are trying to Appium session using the following capability. 
[debug] [35m[BaseDriver][39m   "deviceName": "8C4Y14QBGA",
[debug] [35m[BaseDriver][39m   "newCommandTimeout": "1800",
[debug] [35m[BaseDriver][39m   "automationName": "UiAutomator2",
[debug] [35m[BaseDriver][39m   "app": "/process/uploads/20200609131058_nqx3Q.apk",
[debug] [35m[BaseDriver][39m   "platformName": "Android",
[debug] [35m[BaseDriver][39m   "platformVersion": "9",
[debug] [35m[BaseDriver][39m   "connectHardwareKeyboard": "true"

## Environment

* Appium version Appium v1.17.1
* Desktop OS/version mac OS Cataline 10.15
* Node.js version: 13.8.0
* Npm or Yarn package manager: 6.13.7
* Mobile platform/version under test: 9.0 
* Real device Goole Pixel 
* Appium.app:

## Details
We are using Java Appium client library to create session with the above capability and we are getting an error while taking a screenshot "UiAutomation not connected!"
## Link to Appium logs

[35m[HTTP][39m [37m<-- POST /wd/hub/session/245ebbe5-8cf8-47ce-bf9f-db14f39151d6/context [39m[32m200[39m [90m1 ms - 76[39m
[35m[HTTP][39m [90m[39m
[35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/session/245ebbe5-8cf8-47ce-bf9f-db14f39151d6/screenshot[39m
[35m[HTTP][39m [90m{}[39m
[debug] [35m[MJSONWP (245ebbe5)][39m Calling AppiumDriver.getScreenshot() with args: ["245ebbe5-8cf8-47ce-bf9f-db14f39151d6"]
[debug] [35m[WD Proxy][39m Matched '/screenshot' to command name 'getScreenshot'
[debug] [35m[WD Proxy][39m Proxying [GET /screenshot] to [GET http://127.0.0.1:8200/wd/hub/session/05b1360a-0b53-4de6-a763-76aa144ceacc/screenshot] with no body
[35m[WD Proxy][39m Got response with status 500: {"sessionId":"05b1360a-0b53-4de6-a763-76aa144ceacc","value":{"error":"unknown error","message":"java.lang.IllegalStateException: UiAutomation not connected!","stacktrace":"java.lang.IllegalStateException: UiAutomation not connected!\n\tat android.app.UiAutomation.throwIfNotConnectedLocked(UiAutomation.java:1112)\n\tat android.app.UiAutomation.takeScreenshot(UiAutomation.java:709)\n\tat io.appium.uiautomator2.utils.ScreenshotHelper.takeDeviceScreenshot(Unknown Source:169)\n\tat io.appium.uiautomator2.utils.ScreenshotHelper.takeScreenshot(Unknown Source:7)\n\tat io.appium.uiautomator2.utils.ScreenshotHelper.takeScreenshot(Unknown Source:1)\n\tat io.appium.uiautomator2.handler.CaptureScreenshot.safeHandle(Unknown Source:11)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(Unknown Source:0)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(Unknown Source:23)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(Unknown Source:57)\n\tat io.appium.uiautomator2.ht...
[debug] [35m[W3C][39m Matched W3C error code 'unknown error' to UnknownError
[debug] [35m[MJSONWP (245ebbe5)][39m Encountered internal error running command: An unknown server-side error occurred while processing the command. Original error: java.lang.IllegalStateException: UiAutomation not connected!
[debug] [35m[MJSONWP (245ebbe5)][39m java.lang.IllegalStateException: UiAutomation not connected!
[debug] [35m[MJSONWP (245ebbe5)][39m 	at android.app.UiAutomation.throwIfNotConnectedLocked(UiAutomation.java:1112)
[debug] [35m[MJSONWP (245ebbe5)][39m 	at android.app.UiAutomation.takeScreenshot(UiAutomation.java:709)
[debug] [35m[MJSONWP (245ebbe5)][39m 	at io.appium.uiautomator2.utils.ScreenshotHelper.takeDeviceScreenshot(Unknown Source:169)
[debug] [35m[MJSONWP (245ebbe5)][39m 	at io.appium.uiautomator2.utils.ScreenshotHelper.takeScreenshot(Unknown Source:7)
[debug] [35m[MJSONWP (245ebbe5)][39m 	at io.appium.uiautomator2.utils.ScreenshotHelper.takeScreenshot(Unknown Source:1)
[debug] [35m[MJSONWP (245ebbe5)][39m 	at io.appium.uiautomator2.handler.CaptureScreenshot.safeHandle(Unknown Source:11)
[debug] [35m[MJSONWP (245ebbe5)][39m 	at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(Unknown Source:0)
[debug] [35m[MJSONWP (245ebbe5)][39m 	at io.appium.uiautomator2.server.AppiumServlet.handleRequest(Unknown Source:23)
[debug] [35m[MJSONWP (245ebbe5)][39m 	at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(Unknown Source:57)
[debug] [35m[MJSONWP (245ebbe5)][39m 	at io.appium.uiautomator2.http.ServerHandler.channelRead(Unknown Source:142)
[debug] [35m[MJSONWP (245ebbe5)][39m 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source:12)
[debug] [35m[MJSONWP (245ebbe5)][39m 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source:15)
[debug] [35m[MJSONWP (245ebbe5)][39m 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Unknown Source:4)
[debug] [35m[MJSONWP (245ebbe5)][39m 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(Unknown Source:38)
[debug] [35m[MJSONWP (245ebbe5)][39m 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source:12)
[debug] [35m[MJSONWP (245ebbe5)][39m 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source:15)
[debug] [35m[MJSONWP (245ebbe5)][39m 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Unknown Source:4)
[debug] [35m[MJSONWP (245ebbe5)][39m 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(Unknown Source:2)

**Comment by mykola-mokhnach** [comment]
There is nothing about it we could do on Appium side, because the exception is thrown by the downstream service. Check https://www.google.com/search?q="UiAutomation+not+connected"

**Comment by sriharimobidev** [comment]
@mykola-mokhnach It's previously working with the same apk with the latest versions of Appium not working.

**Comment by mykola-mokhnach** [comment]
Check the logcat output, perhaps it contains some more details

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
