### ISSUE TITLE
Iphone ios 10 cannot record video.

### ISSUE THREAD

**Issue by SPxiaomin** [appium/appium#14448]
## The problem

I'm trying to record the screen, on Iphone ios 13, it works. but when I try on Iphone ios 10, it don't work.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac os / Mojava
* Node.js version (unless using Appium.app|exe): v10.19.0
* Npm or Yarn package manager: yarn
* Mobile platform/version under test: Iphone / ios 10.
* Real device or emulator/simulator: real device.
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

https://gist.github.com/SPxiaomin/49d17cecf3dfd0fc4f9122f57614a367

## Code To Reproduce Issue [ Good To Have ]

`def appium_ios10():
    print('～ios10 start～')

    desired_caps= {
        'platformName': 'iOS',
        'deviceName': '',
        'udid': '',
        'app': "/Users/bytedance/Library/Developer/Xcode/DerivedData/HelloWorld-gaxmcsiceqodkzdnljfgmfahwdpx/Build/Products/Debug-iphoneos/HelloWorld.app",
        'automationName': "XCUITest",
        'xcodeOrgId': "",
        'xcodeSigningId': "iPhone Developer",
    }

    driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)

    try:
        el1 = driver.find_element_by_accessibility_id('Article')
        el1.click()

        for i in range(5):
            print('ios 10 / ', driver.contexts)
            time.sleep(1)

        driver.start_recording_screen(videoType='h264')

        driver.switch_to.context(driver.contexts[1])

        search = driver.find_element_by_css_selector('input[type="search"]')
        search.set_value('abc')
        submit = driver.find_element_by_css_selector('a[class="iconfont"]')
        submit.click()

        # raise Exception('hahaha')

        driver.switch_to.context(driver.contexts[0])
        time.sleep(4)
        driver.save_screenshot('./screenshot/ios-10.png')

        print('over')

        video_string = driver.stop_recording_screen()
        directory = "/Users/bytedance/PycharmProjects/python-test-ui"
        filepath = os.path.join(directory, "screen_recording.mp4")
        with open(filepath, "wb") as fd:
            fd.write(base64.b64decode(video_string))

        print('video over')

    except Exception as e:
        print('ios 10 / Error', e)
    else:
        a = 1

    driver.quit()

    print('～ios10 over～')`

**Comment by SPxiaomin** [comment]
thx in advance. 👍

**Comment by mykola-mokhnach** [comment]
this is by design. Only iOS above 11+ is supported there. iOS 10 is built on top of SDK v9 whose support was dropped a while ago

**Comment by SPxiaomin** [comment]
@mykola-mokhnach so If I wanna to support ios 10+ screen record, is it possible? or what version of appium should i use?

**Comment by SPxiaomin** [comment]
@mykola-mokhnach and SDK v9? I'm new to Appium. could you please provide me more detail?

**Comment by SPxiaomin** [comment]
you mean the ios sdk?

**Comment by mykola-mokhnach** [comment]
I don't know a way to make it possible, because the old SDK does not contain the necessary primitives. You could fork the project and work on the alternative implementation if iOS 10 support is a hard requirement.

**Comment by SPxiaomin** [comment]
@mykola-mokhnach great thx.
