### ISSUE TITLE
Could not proxy command to remote server. Original error: 400 - "unhandled request"

### ISSUE THREAD

**Issue by JoffreyN** [appium/appium#14443]
## Environment

* Appium version 1.17.1
* Mobile platform/version under test: iOS13.3
* Real device or emulator/simulator:  simulator

## Link to Appium logs

[DevCon Factory] Releasing connections for 8561F506-49B4-4186-A68E-A83DB47C3F76 device on any port number
[DevCon Factory] Found cached connections to release: ["8561F506-49B4-4186-A68E-A83DB47C3F76:8100"]
[debug] [DevCon Factory] Cached connections count: 0
[debug] [IOSSimulatorLog] Stopping iOS log capture
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1591929364394 (10:36:04 GMT+0800 (China Standard Time))
[debug] [W3C] Encountered internal error running command: Error: Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: 400 - "unhandled request"
[debug] [W3C]     at quitAndUninstall (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:514:17)
[debug] [W3C]     at /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:580:17

**Comment by KazuCocoa** [comment]
Could you attach the full server log with `showXcodeLog: true` option as GIST?

**Comment by JoffreyN** [comment]
已解决！指定"webDriverAgentUrl":"http://10.0.2.193:8100"的IP。用127.0.0.1不行
