### ISSUE TITLE
Android: Scrolling is happening very fast in UIAutomator in Landscape mode

### ISSUE THREAD

**Issue by rajkumar-cp** [appium/appium#14444]
## The problem

I'm trying to scroll and locate an object in my mobile application. Scrolling is happening fast and what happens is the element that I want to locate becomes hidden.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): Using exe
* Npm or Yarn package manager: 6.4.1
* Mobile platform/version under test: 9.0
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: exe

## Details

1)User is in a particular screen in mobile application
2) The element which the user wants to locate lies somewhere below in the screen which is currently not visible in landscape mode
3) User scrolls the screen to make it visible using the below piece of code
 AndroidElement list = (AndroidElement) driver.findElement(By.id("fragment_properties_list"));
                    list
                            .findElement(MobileBy
                                    .AndroidUIAutomator("new UiScrollable(new UiSelector()).scrollIntoView("
                                            + "new UiSelector().text(\"" + propertyName.toUpperCase() + "\"));"));
4) Scroll happens and the desired element moves to the top of the screen and becomes hidden and the scroll stops

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
https://gist.github.com/rajkumar-cp/b52f26d2bd5f96bb7e40c9d95eb1ce33

In the attached file keyword is above the text which exists at
<img width="565" alt="isAnyOfOperatorValidation_1591937080998" src="https://user-images.githubusercontent.com/39653778/84468998-aa95ac00-ac9d-11ea-8b4f-4f955e136830.png">
 the beginning of the screenshot.

**Comment by mykola-mokhnach** [comment]
The scrolling is done by UiAutomator. Unfortunately there is nothing that could be done from Appium side here.

As a workaround you could try to swipe step by step using touch actions.

**Comment by amedvedjev** [comment]
Use "scrollForward" it should move exactly one view/screen/page (depends how you call it).

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
