### ISSUE TITLE
 Appium 1.17.1 + Xcode 11.4.1: Simulator app is minimized

### ISSUE THREAD

**Issue by sadafyadegari** [appium/appium#14442]
## The problem

Simulator app is minimized when running tests with Appium 1.17.1 and Xcode 11.4.1.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1
* Last Appium version that did not exhibit the issue (if applicable): 1.16.0
* Desktop OS/version used to run Appium: Mac OS Catalina
* Node.js version (unless using Appium.app|exe): v13.12.0
* Npm or Yarn package manager: npm 3.10.10
* Mobile platform/version under test: iOS 13.4
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: 

## Details

Tests run without a problem but simulator window is minimized by default. You'd have to open the simulator by going to File **>** Open Device **>** iOS <version> **>** <device name>

## Link to Appium logs

[GIST](https://gist.github.com/sadafyadegari/bbd7f08d488a443fe2b0aec9cc24de24)

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by KazuCocoa** [comment]
Similar to https://github.com/appium/appium/issues/14291 ?

**Comment by mykola-mokhnach** [comment]
I was not able to reproduce the issue locally. Perhaps, there is some cached window state. 
I general there is no way to deiconize Simulator windows, except of Apple Script usage (and face Mac OS security limitations).

**Comment by sadafyadegari** [comment]
Using xcode-11.4.1, I'm seeing if you switch order to first call `startUIClient` and then call `bootSimulator` , sim window doesn't start as minimized.  https://github.com/appium/appium-ios-simulator/blob/master/lib/simulator-xcode-9.js#L148-L153

I'd be interested to see why `startUIClient` is called after `bootSimulator` and if switching the order could break things for some xcode and appium combinations.

**Comment by mykola-mokhnach** [comment]
Linking https://github.com/appium/appium-ios-simulator/pull/282

**Comment by dpgraham** [comment]
Resolved and published
