### ISSUE TITLE
when I run webdriveragent  caught  error:"NSInvalidArgumentException"

### ISSUE THREAD

**Issue by Linxi-brave** [appium/appium#14449]
## The problem

When I build webdriveragent ,it success ;but when I run webdriveragent ,it error .

## Environment

* Mobile platform/version under test:
iOS 13.4 simulator 
* Real device or emulator/simulator:
simulator
* Xcode version:
11.6 beta 

## Details

caught "NSInvalidArgumentException", "-[FBSpringboardApplication resolve]: unrecognized selector sent to instance 0x600002593bf0"
(
	0   CoreFoundation                      0x00007fff23e3dcce __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50b3b9b2 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23e5e9f4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff23e426cc ___forwarding___ + 1436
	4   CoreFoundation                      0x00007fff23e449b8 _CF_forwarding_prep_0 + 120
	5   WebDriverAgentLib                   0x00000001089a4cd1 +[FBSpringboardApplication fb_springboard] + 161
	6   WebDriverAgentLib                   0x00000001089bada5 -[FBAlert alertElement] + 133
	7   WebDriverAgentLib                   0x00000001089ba110 -[FBAlert dismissWithError:] + 48
	8   IntegrationTests_1                  0x000000010895b68a -[FBAlertTests tearDown] + 154
	9   XCTest                              0x00000001085c5b38 __51-[XCTestCase _performTearDownSequenceWithSelector:]_block_invoke_2 + 54
	10  XCTest                              0x000000010861edc2 +[XCTestCase(Failures) performFailableBlock:testCase:testCaseRun:shouldInterruptTest:] + 69
	11  XCTest                              0x000000010861ecd4 -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] + 115
	12  XCTest                              0x00000001085c590d __51-[XCTestCase _performTearDownSequenceWithSelector:]_block_invoke + 123
	13  XCTest                              0x00000001086312a7 -[XCTContext _runActivityNamed:type:block:] + 245
	14  XCTest                              0x00000001085cec71 -[XCTestCase startActivityWithTitle:type:block:] + 186
	15  XCTest                              0x00000001085cee39 -[XCTestCase startActivityWithTitle:block:] + 60
	16  XCTest                              0x00000001085c588c -[XCTestCase _performTearDownSequenceWithSelector:] + 81
	17  XCTest                              0x00000001085c3d19 -[XCTestCase invokeTest] + 1986
	18  XCTest                              0x00000001085c5329 __26-[XCTestCase performTest:]_block_invoke_2 + 43
	19  XCTest                              0x000000010861edc2 +[XCTestCase(Failures) performFailableBlock:testCase:testCaseRun:shouldInterruptTest:] + 69
	20  XCTest                              0x000000010861ecd4 -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] + 115
	21  XCTest                              0x00000001085c5260 __26-[XCTestCase performTest:]_block_invoke.359 + 86
	22  XCTest                              0x0000000108631a0d +[XCTContext runInContextForTestCase:block:] + 211
	23  XCTest                              0x00000001085c4b14 -[XCTestCase performTest:] + 566
	24  XCTest                              0x000000010860b38e -[XCTest runTest] + 57
	25  XCTest                              0x00000001085bed50 __27-[XCTestSuite performTest:]_block_invoke + 354
	26  XCTest                              0x00000001085be4a2 __59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke + 24
	27  XCTest                              0x0000000108631a0d +[XCTContext runInContextForTestCase:block:] + 211
	28  XCTest                              0x00000001085be459 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 148
	29  XCTest                              0x00000001085be7be -[XCTestSuite performTest:] + 348
	30  XCTest                              0x000000010860b38e -[XCTest runTest] + 57
	31  XCTest                              0x00000001085bed50 __27-[XCTestSuite performTest:]_block_invoke + 354
	32  XCTest                              0x00000001085be4a2 __59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke + 24
	33  XCTest                              0x0000000108631a0d +[XCTContext runInContextForTestCase:block:] + 211
	34  XCTest                              0x00000001085be459 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 148
	35  XCTest                              0x00000001085be7be -[XCTestSuite performTest:] + 348
	36  XCTest                              0x000000010860b38e -[XCTest runTest] + 57
	37  XCTest                              0x00000001085bed50 __27-[XCTestSuite performTest:]_block_invoke + 354
	38  XCTest                              0x00000001085be4a2 __59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke + 24
	39  XCTest                              0x0000000108631a0d +[XCTContext runInContextForTestCase:block:] + 211
	40  XCTest                              0x00000001085be459 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 148
	41  XCTest                              0x00000001085be7be -[XCTestSuite performTest:] + 348
	42  XCTest                              0x000000010860b38e -[XCTest runTest] + 57
	43  XCTest                              0x0000000108640f14 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 171
	44  XCTest                              0x0000000108641001 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke.100 + 96
	45  XCTest                              0x00000001085d9746 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 682
	46  XCTest                              0x0000000108640c9f -[XCTTestRunSession runTestsAndReturnError:] + 615
	47  XCTest                              0x00000001085a2744 -[XCTestDriver runTestsAndReturnError:] + 456
	48  XCTest                              0x000000010862d64c _XCTestMain + 2496
	49  IntegrationTests_1-Runner           0x00000001083afe1a -[_XCTRunnerAppDelegate applicationWillResignActive:] + 0
	50  IntegrationTests_1-Runner           0x00000001083afd18 _XCTRunnerRunTests + 0
	51  CoreFoundation                      0x00007fff23da1a9c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	52  CoreFoundation                      0x00007fff23da1193 __CFRunLoopDoBlocks + 195
	53  CoreFoundation                      0x00007fff23d9bf83 __CFRunLoopRun + 995
	54  CoreFoundation                      0x00007fff23d9b884 CFRunLoopRunSpecific + 404
	55  GraphicsServices                    0x00007fff38b5ac1a GSEventRunModal + 139
	56  UIKitCore                           0x00007fff48c19220 UIApplicationMain + 1605
	57  IntegrationTests_1-Runner           0x00000001083affd5 main + 183
	58  libdyld.dylib                       0x00007fff519b910d start + 1
)

**Comment by mykola-mokhnach** [comment]
Please use the most recent Appium version

closed as not an issue
