### ISSUE TITLE
it takes a long time to find a element in page with many elements

### ISSUE THREAD

**Issue by Lyuxy** [appium/appium#14445]
## The problem

it takes a long time to find a element in page with many elements

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: iOS 13
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Details

use method “driver.find_element_by_name()”or"driver.find_element_by_ios_predicate("name=='xxx'")" , get the same result. if this page has a small amount of element, it will find the element much quicker than a page with many elements.

**Comment by mykola-mokhnach** [comment]
The lookup speed depends on the low level XCTest implementation. Please report your issue to Apple.

Closed as third party issue
