### ISSUE TITLE
Increasing timeout for slow booting device

### ISSUE THREAD

**Issue by AllanElleuch** [appium/appium#14453]
## The problem

I have android devices emulated in containers that take 40-50 secondes to boot up. My problem is that I got this message before the android device could completely boot.  : 

[AndroidDriver] Error: Appium Settings app is not running after 5000ms
[debug] [AndroidDriver]     at ADB.requireRunningSettingsApp 

The problem  only happen when the device doesn't run in quickboot 

I tried to use those capabilities to increase the waiting time  : 

- "androidInstallTimeout": 120000,
- "newCommandTimeout": 120,
- "appWaitDuration": 60000,
- "avdLaunchTimeout": 180000,

But It didn't solved my problem.

## Environment

* Appium version : 1.17.1
* Desktop OS/version used to run Appium: Centos 7
* Node.js : v8.10
* emulated device : Pixel 2 XL 9.0
* Appium CLI : 6.1.0

## Link to Appium logs

 [Link to appium log](https://gist.github.com/AllanElleuch/09037b9459eba3f33fbeda135d23c6bb) 

## Code To Reproduce Issue [ Good To Have ]

Create a new device and try to start it with appium. The device need to have never been runned ( or run with -wipe-data  so there is no quickboot).

1. create avd
avdmanager  create avd --name nexus_5x-gps-10.0 --abi google_apis_playstore/x86 --package 'system-images;android-29;google_apis_playstore;x86' --device 'Nexus 5X' --sdcard 256M

2. start the device with appium

**Comment by mykola-mokhnach** [comment]
Have you tried to start Appium Settings manually? 
What is the output of 
`/root/platform-tools/adb -P 5037 -s emulator-5554 shell am start -n io.appium.settings/.Settings -a android.intent.action.MAIN -c android.intent.category.LAUNCHER`
and 
`/root/platform-tools/adb -P 5037 -s emulator-5554 shell pgrep -f io\\.appium\\.settings` being executed manually?

What is in the logcat output?

**Comment by AllanElleuch** [comment]
Hi,

## Code

       capabilities.setCapability(CapabilityType.PLATFORM_NAME, Platform.ANDROID);
        capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.0");
        capabilities.setCapability(CapabilityType.BROWSER_NAME, BrowserType.CHROME);
        capabilities.setCapability(AndroidMobileCapabilityType.AVD, "nexus_5x-gps-10.0"); 
        capabilities.setCapability("androidInstallTimeout", 120000); 
        capabilities.setCapability("newCommandTimeout", 120); 
        capabilities.setCapability("acceptInsecureCerts", true); 
        capabilities.setCapability("appWaitDuration", 60000);
        capabilities.setCapability("avdLaunchTimeout", 180000); 
        capabilities.setCapability("avdReadyTimeout", 180000); 
        capabilities.setCapability(AndroidMobileCapabilityType.AVD_ARGS, "-noaudio -gpu auto -verbose -accel on -no-boot-anim -no-snapshot-save -wipe-data");

        ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.setExperimentalOption("w3c", false);
        capabilities.merge(chromeOptions);

        AndroidDriver driver = new AndroidDriver(new URL("http://127.0.0.1:4442/wd/hub"), capabilities);`

## Gif 

![running appium cold boot](https://user-images.githubusercontent.com/19656515/84774526-3da44e00-afde-11ea-925f-0082e44f0d71.gif)



## Log

Appium java client log : https://gist.github.com/AllanElleuch/99e2fe7cbe77b436fe1b86c461ea38f0

Appium log obtained from device with tail -f   /var/log/supervisor/appium.stdout.log :
https://gist.github.com/AllanElleuch/b04cc6ac86546e0a32f0d7c8278a1df2

Log cat obtained from "adb logcat" : https://gist.github.com/AllanElleuch/e36745c6b0950aa0107062d251abc3f6

After running I tried to start Appium Settings manually

```
root@503f8b1f8576:~# /root/platform-tools/adb -P 5037 -s emulator-5554 shell am start -n io.appium.settings/.Settings -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=io.appium.settings/.Settings }

Error type 3

Error: Activity class {io.appium.settings/io.appium.settings.Settings} does not exist.
```


```
root@503f8b1f8576:~# /root/platform-tools/adb -P 5037 -s emulator-5554 shell pgrep -f io\\.appium\\.settings

root@503f8b1f8576:~# 

```

**Comment by mykola-mokhnach** [comment]
> Error: Activity class {io.appium.settings/io.appium.settings.Settings} does not exist.

It looks like the settings helper was not installed properly. This might be an emulator bug though:

> [ADB] The application at '/data/appium/lib/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk' will not be cached, because the device under test has confirmed the support of streamed installs
> [debug] [ADB] Running '/root/platform-tools/adb -P 5037 -s emulator-5554 install -g /data/appium/lib/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk'
> [ADB] [AVD OUTPUT] emulator: onGuestClose: [0x7613e00] Adb closed by guest
> [ADB] [AVD OUTPUT] emulator: onGuestClose: [0x7614800] Adb closed by guest
> [debug] [ADB] Getting install status for io.appium.settings
> [debug] [ADB] Running '/root/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.settings'

Try to start your test with already running emulator. Also, it makes sense to try appium@beta, since it uses an alternative approach for emulator boot detection.

I would also try to report the https://gist.github.com/AllanElleuch/e36745c6b0950aa0107062d251abc3f6#file-logcat-from-adb-logcat-when-starting-the-device-L2066 exception to Google

**Comment by AllanElleuch** [comment]
I tried with appium@beta I got a different error. It seems that the android driver set the device to null and then crash when trying to get the api level of the device.


```
[AndroidDriver] Using device: null

....

[debug] [BaseDriver] Event 'newSessionStarted' logged at 1592325536686 (18:38:56 GMT+0200 (heure d’été d’Europe centrale))

[debug] [W3C] Encountered internal error running command: Error: Error getting device API level. Original error: Error executing adbExec. Original error: 'Command '/home/poop/Android/Sdk/platform-tools/adb -P 5037 -s null shell getprop ro.build.version.sdk' exited with code 1'; Stderr: 'adb: device 'null' not found'; Code: '1'

[debug] [W3C]     at ADB.getApiLevel (/usr/local/lib/node_modules/appium/node_modules/appium-adb/lib/tools/adb-commands.js:112:13)

```

If I use a proper device id the command succeed : 

```
$ /home/poop/Android/Sdk/platform-tools/adb -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk`

29
```


Log : https://gist.github.com/AllanElleuch/5e2e264c43f0d11114c8bcffc3ca297a

I found a similar issue that was caused by the version of the sdk (https://github.com/appium/appium/issues/12736)

I am using the following sdk : 

  Path                                               | Version | Description                             | Location                                           
  -------                                            | ------- | -------                                 | -------                                            
  build-tools;29.0.1                                 | 29.0.1  | Android SDK Build-Tools 29.0.1          | build-tools/29.0.1/                                
  build-tools;29.0.3                                 | 29.0.3  | Android SDK Build-Tools 29.0.3          | build-tools/29.0.3/                                
  emulator                                           | 30.0.12 | Android Emulator                        | emulator/                                          
  patcher;v4                                         | 1       | SDK Patch Applier v4                    | patcher/v4/                                        
  platform-tools                                     | 30.0.2  | Android SDK Platform-Tools              | platform-tools/                                    
  platforms;android-29                               | 4       | Android SDK Platform 29                 | platforms/android-29/                              
  system-images;android-29;google_apis_playstore;x86 | 8       | Google Play Intel x86 Atom System Image | system-images/android-29/google_apis_playstore/x86/
  tools                                              | 26.1.1  | Android SDK Tools 26.1.1                | tools/

**Comment by mykola-mokhnach** [comment]
Thanks for the detailed logs. The recent one looks like a bug. Let me fix it.

**Comment by mykola-mokhnach** [comment]
I've pushed the fix to master. Please reinstall appium@beta

**Comment by AllanElleuch** [comment]
Hey, 

I tried quickly and it solved the issue. The device was able to boot and run a test even with the cold boot. Thank you very much !
