### ISSUE TITLE
Error: Could not determine iOS SDK version: Command 'xcrun --sdk iphonesimulator --show-sdk-version' timed out after 15000ms

### ISSUE THREAD

**Issue by drapostolos** [appium/appium#14458]
## The problem

I occasionally get the above error, when running tests in AWS Device Farm. I believe the error is due to that command sometimes take longer than 15 seconds to execute. Similar as in this (rather old) issue: https://github.com/appium/appium/issues/6743

If my test (when running in AWS Device Farm) executes the above command before starting appium, you can see in the log below that the first time takes longer than 15 seconds, but subsequent executions are much faster.
```
2020-06-16 05:22:17.596 DEBUG ->[1] /bin/bash -c xcrun --sdk iphonesimulator --show-sdk-version; exit 
2020-06-16 05:22:41.801 DEBUG <-[1] 12.4 
2020-06-16 05:22:41.833 DEBUG ->[2] /bin/bash -c xcrun --sdk iphonesimulator --show-sdk-version; exit 
2020-06-16 05:22:42.024 DEBUG <-[2] 12.4 
2020-06-16 05:22:42.080 DEBUG ->[3] /bin/bash -c xcrun --sdk iphonesimulator --show-sdk-version; exit 
2020-06-16 05:22:42.234 DEBUG <-[3] 12.4 
```

According to this PR (https://github.com/appium/appium-xcode/pull/20), the timeout was extended. 

But was the timeout ever made configurable? I have looked through the docs and could not find any capability to configure this.

Is it configurable? If so, is it documented anywhere?

Thanks
Alex

**Comment by mykola-mokhnach** [comment]
Without the server log it is impossible to guess which particular function is called, but in general I don't think these timeouts are configurable on the client side anywhere. xcuitest driver calls them with default parameters.

**Comment by drapostolos** [comment]
Here is the server log:
https://gist.github.com/drapostolos/0cb2091e97d5e4ed2518477bc2285b61

**Comment by mykola-mokhnach** [comment]
v 1.12.1 is a very old one, but in the recent one I could also observe appium-xcode methods are called with default values

**Comment by drapostolos** [comment]
Is there a recommended workaround, if timeout can not be extended?
Other than have the test call `xcrun --sdk iphonesimulator --show-sdk-version` before starting the appium client.

**Comment by KazuCocoa** [comment]
No idea from my side.
The issue seems their infrastructure side, so I think their improvements or making the timeout configurable are necessary.
(But Appium does not apply changes to older versions though)

**Comment by lfalkner** [comment]
I'm seeing the same error running tests against saucelabs.
