### ISSUE TITLE
Appium unable to identify Button elements which are visible

### ISSUE THREAD

**Issue by bibinroy** [appium/appium#14456]
I am using Android Studio Emulator for mobile automation. For elements with android.widget.EditText or android.widget.View i am able to view those element through scripts and functionality works fine. But if there are elements android.widget.Button none of the elements i could click. Throwing element not visible. But 100 percent sure the elements are visible on the page. Please check

[WD Proxy] Proxying [POST /element] to [POST http://localhost:8200/wd/hub/session/ab0c643d-909f-4b70-bd42-8c13f4e3c104/element] with body: {"strategy":"xpath","selector":"//android.widget.Button[@text='SALES']","context":"","multiple":false}
[WD Proxy] Got an unexpected response: {"sessionId":"ab0c643d-909f-4b70-bd42-8c13f4e3c104","status":7,"value":"An element could not be located on the page using the given search parameters."}
[MJSONWP] Matched JSONWP error code 7 to NoSuchElementError
[W3C (f495d027)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[W3C (f495d027)]     at AndroidUiautomator2Driver.helpers.findElOrEls (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-android-driver\lib\commands\find.js:75:11)
[W3C (f495d027)]     at process._tickCallback (internal/process/next_tick.js:68:7)
[HTTP] <-- POST /wd/hub/session/f495d027-25a2-45a3-9b46-f0f794129a19/element 404 90361 ms - 496

**Comment by mykola-mokhnach** [comment]
Please fill out the issue reporting form properly and attach the page source output before the actual lookup is executed

**Comment by bibinroy** [comment]
Detailed logs attached

[appium-server-logs.txt](https://github.com/appium/appium/files/4785162/appium-server-logs.txt)

**Comment by bibinroy** [comment]
Detailed logs

[appium-server-logs1.txt](https://github.com/appium/appium/files/4785172/appium-server-logs1.txt)

**Comment by mykola-mokhnach** [comment]
- Appium 1.12 is old. Consider upgrading to the latest
- I still don't see the page source

**Comment by mykola-mokhnach** [comment]
Closed because of no response
