### ISSUE TITLE
question: how to remove appium setting notification ?

### ISSUE THREAD

**Issue by selenUser** [appium/appium#14459]
appium version: 1.14.2
java-client version: 7.2

there is a way to not showing appium setting notification ?

**Comment by mykola-mokhnach** [comment]
This is impossible, because the app has foreground services and Android OS requires them to stay in background.

Please use Appium forum to ask questions

**Comment by irjayjay** [comment]
Go to the app's settings in the OS and force stop it. It'll be back the next time you run Appium though.
