### ISSUE TITLE
Enter button not working on lower API versions (arm CPU/ABI)

### ISSUE THREAD

**Issue by bibinroy** [appium/appium#14451]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by bibinroy** [comment]
Appium version : 1.13.0

Tried different codes for Enter but none worked

driver.pressKey(new KeyEvent(AndroidKey.NUMPAD_ENTER));
driver.pressKey(new KeyEvent(AndroidKey.ENTER));
driver.pressKey(new KeyEvent(AndroidKey.ENTER)
	                .withFlag(KeyEventFlag.SOFT_KEYBOARD)
	                .withFlag(KeyEventFlag.KEEP_TOUCH_MODE)
	                .withFlag(KeyEventFlag.EDITOR_ACTION));

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/android-ime.md

**Comment by bibinroy** [comment]
Tried with the above link. Thats not working either. Please reopen the issue. The code works on other API. My system supports only arm API. In this API this code is not working

**Comment by mykola-mokhnach** [comment]
There is nothing that could be done on this issue without having the logs (both server and logcat). Also, the most recent server version must be used. "Not working" is hardly enough to fix anything

**Comment by bibinroy** [comment]
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session/f99183bb-62ec-43fb-95ec-5169275c3bc4/element/2daffc10-4fac-483e-a098-37f40ced3230/value [39m[32m200[39m [90m201 ms - 12[39m
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/f99183bb-62ec-43fb-95ec-5169275c3bc4/appium/device/press_keycode[39m
[info] [35m[HTTP][39m [90m{"keycode":66}[39m
[debug] [35m[W3C (f99183bb)][39m Calling AppiumDriver.pressKeyCode() with args: [66,null,null,null,null,"f99183bb-62ec-43fb-95ec-5169275c3bc4"]
[debug] [35m[WD Proxy][39m Matched '/appium/device/press_keycode' to command name 'pressKeyCode'
[debug] [35m[WD Proxy][39m Proxying [POST /appium/device/press_keycode] to [POST http://localhost:8201/wd/hub/session/0a68546b-8cc9-4421-8770-059c56b9ff4e/appium/device/press_keycode] with body: {"keycode":66,"metastate":null,"flags":null}[debug] [35m[WD Proxy][39m Got response with status 200: {"sessionId":"0a68546b-8cc9-4421-8770-059c56b9ff4e","status":0,"value":true}
[debug] [35m[W3C (f99183bb)][39m Responding to client with driver.pressKeyCode() result: true
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session/f99183bb-62ec-43fb-95ec-5169275c3bc4/appium/device/press_keycode [39m[32m200[39m [90m213 ms - 14[39m

**Comment by bibinroy** [comment]
This issue happens only in arm emulators. Other high api this code is working fine. Since my system supports only arm emulator i am unable to proceed.

**Comment by mykola-mokhnach** [comment]
I don't observe any calls to the mobile method mentioned above.

**Comment by bibinroy** [comment]
[appium-server-logs.txt](https://github.com/appium/appium/files/4779433/appium-server-logs.txt)


Detailed logs

**Comment by mykola-mokhnach** [comment]
The action has been executed successfully in the log. Check with your developer which particular action that control expects, since there are a couple of them

**Comment by bibinroy** [comment]
Hi the same code for click enter works fine on API version 28 x86 CPU/ABI

**Comment by KazuCocoa** [comment]
Did you check the logcat? Or do you have any idea which Android (UiAutomator) API works on the Arm environment?

Appium depends on APIs by Android toolchain, so if the issue was inside Android API, Appium can not do anything, unfortunately.

> click enter works fine on API version 28 x86 CPU/ABI

I wondered the cause was Android API internal. So, even the command got succeeded as a receiver, the internal had an issue.

**Comment by bibinroy** [comment]
I am not sure on those. But as per your comments can i confirm this issue is not related to appium?

**Comment by mykola-mokhnach** [comment]
You will only be able to confirm anything after logcat and application's logs are investigated.
