### ISSUE TITLE
iOS 13.5 ,xcode 11.5,appium 1.17 Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: +[XCAXClient_iOS sharedClient]: unrecognized selector 

### ISSUE THREAD

**Issue by Linxi-brave** [appium/appium#14457]
## The problem
When I using appium to test iOS mobile, after running webdriveragent in xcode,it build success.  ip address: http://127.0.0.1:8100/status  display device information, but the address: http://127.0.0.1:8100/inspector shows nothing. 
After running the test code, the app repeatedly restarts and flashes back. The error code displayed is:
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: +[XCAXClient_iOS sharedClient]: unrecognized selector sent to class 0x106731218

(
	0   CoreFoundation                      0x0000000106f8cf0e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x0000000106df89b2 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000106fadb34 +[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x0000000106f9190c ___forwarding___ + 1436
	4   CoreFoundation                      0x0000000106f93bf8 _CF_forwarding_prep_0 + 120
	5   WebDriverAgentLib                   0x0000000128b8e6e7 __37+[FBApplication fb_activeApplication]_block_invoke + 39
	6   WebDriverAgentLib                   0x0000000128b66322 -[FBRunLoopSpinner spinUntilTrue:error:] + 130
	7   WebDriverAgentLib                   0x0000000128b66271 -[FBRunLoopSpinner spinUntilTrue:] + 65
	8   WebDriverAgentLib                   0x0000000128b8e44a +[FBApplication fb_activeApplication] + 106
	9   WebDriverAgentLib                   0x0000000128b78de4 -[FBSession application] + 308
	10  WebDriverAgentLib                   0x0000000128b8034a +[FBSessionCommands currentCapabilities] + 90
	11  WebDriverAgentLib                   0x0000000128b80219 +[FBSessionCommands sessionInformation] + 233
	12  WebDriverAgentLib                   0x0000000128b7f80b +[FBSessionCommands handleCreateSession:] + 1419
	13  WebDriverAgentLib                   0x0000000128b64e46 -[FBRoute_TargetAction mountRequest:intoResponse:] + 182
	14  WebDriverAgentLib                   0x0000000128b5a6b8 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 536
	15  RoutingHTTPServer                   0x0000000128c26c18 -[RoutingHTTPServer handleRoute:withRequest:response:] + 136
	16  RoutingHTTPServer                   0x0000000128c274fa __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 47
	17  libdispatch.dylib                   0x000000010cc068cb _dispatch_client_callout + 8
	18  libdispatch.dylib                   0x000000010cc13940 _dispatch_async_and_wait_invoke + 109
	19  libdispatch.dylib                   0x000000010cc068cb _dispatch_client_callout + 8
	20  libdispatch.dylib                   0x000000010cc12cdb _dispatch_main_queue_callback_4CF + 1042
	21  CoreFoundation                      0x0000000106ef0909 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	22  CoreFoundation                      0x0000000106eeb459 __CFRunLoopRun + 2041
	23  CoreFoundation                      0x0000000106eea944 CFRunLoopRunSpecific + 404
	24  Foundation                          0x000000010685ac71 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 211
	25  WebDriverAgentLib                   0x0000000128b5952a -[FBWebServer startServing] + 330
	26  WebDriverAgentRunner                0x0000000128b4ae82 -[UITestingUITests testRunner] + 82
	27  CoreFoundation                      0x0000000106f93e8c __invoking___ + 140
	28  CoreFoundation                      0x0000000106f91071 -[NSInvocation invoke] + 321
	29  XCTest                              0x0000000106611037 __24-[XCTestCase invokeTest]_block_invoke_2 + 52
	30  XCTest                              0x0000000106610fe3 __24-[XCTestCase invokeTest]_block_invoke.206 + 320
	31  XCTest                              0x000000010666bdc2 +[XCTestCase(Failures) performFailableBlock:testCase:testCaseRun:shouldInterruptTest:] + 69
	32  XCTest                              0x000000010666bcd4 -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] + 115
	33  XCTest                              0x00000001066109f6 -[XCTestCase invokeTest] + 1183
	34  XCTest                              0x0000000106612329 __26-[XCTestCase performTest:]_block_invoke_2 + 43
	35  XCTest                              0x000000010666bdc2 +[XCTestCase(Failures) performFailableBlock:testCase:testCaseRun:shouldInterruptTest:] + 69
	36  XCTest                              0x000000010666bcd4 -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] + 115
	37  XCTest                              0x0000000106612260 __26-[XCTestCase performTest:]_block_invoke.359 + 86
	38  XCTest                              0x000000010667ea0d +[XCTContext runInContextForTestCase:block:] + 211
	39  XCTest                              0x0000000106611b14 -[XCTestCase performTest:] + 566
	40  XCTest                              0x000000010665838e -[XCTest runTest] + 57
	41  XCTest                              0x000000010660bd50 __27-[XCTestSuite performTest:]_block_invoke + 354
	42  XCTest                              0x000000010660b4a2 __59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke + 24
	43  XCTest                              0x000000010667ea0d +[XCTContext runInContextForTestCase:block:] + 211
	44  XCTest                              0x000000010660b459 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 148
	45  XCTest                              0x000000010660b7be -[XCTestSuite performTest:] + 348
	46  XCTest                              0x000000010665838e -[XCTest runTest] + 57
	47  XCTest                              0x000000010660bd50 __27-[XCTestSuite performTest:]_block_invoke + 354
	48  XCTest                              0x000000010660b4a2 __59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke + 24
	49  XCTest                              0x000000010667ea0d +[XCTContext runInContextForTestCase:block:] + 211
	50  XCTest                              0x000000010660b459 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 148
	51  XCTest                              0x000000010660b7be -[XCTestSuite performTest:] + 348
	52  XCTest                              0x000000010665838e -[XCTest runTest] + 57
	53  XCTest                              0x000000010660bd50 __27-[XCTestSuite performTest:]_block_invoke + 354
	54  XCTest                              0x000000010660b4a2 __59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke + 24
	55  XCTest                              0x000000010667ea0d +[XCTContext runInContextForTestCase:block:] + 211
	56  XCTest                              0x000000010660b459 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 148
	57  XCTest                              0x000000010660b7be -[XCTestSuite performTest:] + 348
	58  XCTest                              0x000000010665838e -[XCTest runTest] + 57
	59  XCTest                              0x000000010668df14 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 171
	60  XCTest                              0x000000010668e001 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke.100 + 96
	61  XCTest                              0x0000000106626746 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 682
	62  XCTest                              0x000000010668dc9f -[XCTTestRunSession runTestsAndReturnError:] + 615
	63  XCTest                              0x00000001065ef744 -[XCTestDriver runTestsAndReturnError:] + 456
	64  XCTest                              0x000000010667a64c _XCTestMain + 2496
	65  WebDriverAgentRunner-Runner         0x00000001063cae1a -[_XCTRunnerAppDelegate applicationWillResignActive:] + 0
	66  WebDriverAgentRunner-Runner         0x00000001063cad18 _XCTRunnerRunTests + 0
	67  CoreFoundation                      0x0000000106ef0b5c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	68  CoreFoundation                      0x0000000106ef0253 __CFRunLoopDoBlocks + 195
	69  CoreFoundation                      0x0000000106eeb043 __CFRunLoopRun + 995
	70  CoreFoundation                      0x0000000106eea944 CFRunLoopRunSpecific + 404
	71  GraphicsServices                    0x00000001109f8c1a GSEventRunModal + 139
	72  UIKitCore                           0x0000000108b889ec UIApplicationMain + 1605
	73  WebDriverAgentRunner-Runner         0x00000001063cafd5 main + 183

## Environment

* Appium version (or git revision) that exhibits the issue:  appium server  1.17
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:1.13
* Node.js version (unless using Appium.app|exe):v12.4.0
* Npm or Yarn package manager:6.9.0
* Mobile platform/version under test: iOS 8  13.5
* Real device or emulator/simulator: simulator

## Link to Appium logs
https://gist.github.com/Linxi-brave/071a6d47c83b68783ac34e2cb8636001

**Comment by KazuCocoa** [comment]
> Welcome to Appium v1.13.0

The attached log was by Appium 1.13.0. Please use the latest Appium version correctly.
The 1.13.0 does not work well on Xcode 11

**Comment by mykola-mokhnach** [comment]
^ To be more precise it does not work at all with Xcode 11

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
