### ISSUE TITLE
Clicking on tab label whose content is set via Intent cause ESOCKETTIMEDOUT error

### ISSUE THREAD

**Issue by kuptsouv** [appium/appium#14461]
## The problem

Appium fails to click on tab label element in tabs bar when tab content is set via Intent. However, finding such elements and getting their displaying state works fine.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: MacOS 10.15.3
* Node.js version: 14.4.0
* Npm or Yarn package manager: Npm
* Mobile platform/version under test: Android
* Devices: 
    * Samsung Galaxy S8 (Android 9.0), 
    * OnePlus 3 (Android 9.0)
    * Pixel 3 (Android 10.0) -- emulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

This issue can be reproduced via [ApiDemosApplication](https://github.com/appium/appium/blob/master/sample-code/apps/ApiDemos-debug.apk) app (Java test code provided):

1. Go to `Views/Tabs/3. Content By Intent` screen
2. Try to switch the tab by clicking "PHOTO LIST" tab label

**Result**: ESOCKETTIMEDOUT 4 minutes after click is issued

## Link to Appium logs

[Appium log](https://gist.github.com/kuptsouv/bfebaa6d0a6b570db410d1546d45f935)
[Logcat](https://gist.github.com/kuptsouv/40a93f9d1b8c538c0bdada46c3981db8)

## Code To Reproduce Issue [ Good To Have ]
```java
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.service.local.AppiumDriverLocalService;
import io.appium.java_client.service.local.AppiumServiceBuilder;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.annotations.*;

import java.io.File;
import java.net.URL;
import java.util.Objects;

public class AndroidTest {

    private AppiumDriverLocalService service;
    private AndroidDriver<WebElement> driver;

    @BeforeSuite
    public void globalSetup() {
        AppiumServiceBuilder serviceBuilder = new AppiumServiceBuilder()
                .usingPort(4447)
                .withArgument(() -> "--log-timestamp");
        service = AppiumDriverLocalService.buildService(serviceBuilder);

        service.start();
    }

    @AfterSuite
    public void globalTearDown() {
        service.stop();
    }

    @BeforeClass
    public void setUp() {
        ClassLoader classLoader = getClass().getClassLoader();
        URL apkUrl = Objects.requireNonNull(classLoader.getResource("ApiDemos-debug.apk"));
        String apkAbsolutePath = new File(apkUrl.getFile()).getAbsolutePath();

        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("automationName", "UiAutomator2");
        capabilities.setCapability("udid", "emulator-5554");
        capabilities.setCapability("app", apkAbsolutePath);
        driver = new AndroidDriver<>(service.getUrl(), capabilities);
    }

    @AfterClass
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void test() {
        driver.findElementByAndroidUIAutomator(".text(\"Views\")").click();

        String tabsItemSelector = "new UiSelector().text(\"Tabs\")";
        driver.findElementByAndroidUIAutomator("new UiScrollable(new UiSelector().scrollable(true).instance(0))"
                + ".scrollIntoView(" + tabsItemSelector + ".instance(0))");
        driver.findElementByAndroidUIAutomator(tabsItemSelector).click();

        driver.findElementByAndroidUIAutomator(".text(\"3. Content By Intent\")").click();
        driver.findElementByAndroidUIAutomator(".text(\"PHOTO LIST\")").click();
    }
}
```

**Comment by mykola-mokhnach** [comment]
https://gist.github.com/kuptsouv/40a93f9d1b8c538c0bdada46c3981db8#file-tabs_content_by_intent_esockettimedout_logcat-log-L228

I don't observe anything in the logcat output, which could help to figure out why the connection refusal happens. 
Try to change element locator type or click by coordinates as a workaround.

**Comment by mykola-mokhnach** [comment]
I assume the issue could be an internal UiAutomator bug. ESOCKETTIMEDOUT simply means the that the call to the downstream UiAutomator APIs freezes and does not return the control to the caller after the timeout.

**Comment by kuptsouv** [comment]
@mykola-mokhnach 
I tried different locators and locator types -- result is the same unfortunately.
As for click by coordinates -- yes, it works, but it turned out that all elements on this screen have the same problem, not just tab labels.

**Comment by mykola-mokhnach** [comment]
You could try to describe the issue to Google and see what they respond or check Espresso driver as a possible alternative

**Comment by kuptsouv** [comment]
@mykola-mokhnach I tried Espresso driver and the issue is gone. Thanks for help! 🙂
