### ISSUE TITLE
Appium@beta doesn't detect device boot up when quickboot happen

### ISSUE THREAD

**Issue by AllanElleuch** [appium/appium#14468]
## The problem

If I run a device from appium@beta with quickboot the appium driver load forever because it doesn't detected that the device booted up. However the problem doesn't happen when the device run with -wipe-data.

## Environment

* Appium version (or git revision) that exhibits the issue: last appium@beta
* Desktop OS/version used to run Appium: Ubuntu 20.04
* Node.js version (unless using Appium.app|exe): 10.19
* Mobile platform/version under test: Android 10 - device Pixel_2_API_R - chrome driver 83
* Appium CLI or Appium.app|exe:  7.3.0

## Link to Appium logs

https://gist.github.com/AllanElleuch/d5cdd67e9c290416d53e8bbe68e7d12d

## Code To Reproduce Issue [ Good To Have ]

```
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(CapabilityType.PLATFORM_NAME, Platform.ANDROID);
        capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.0");
        capabilities.setCapability(CapabilityType.BROWSER_NAME, BrowserType.CHROME);
        capabilities.setCapability(AndroidMobileCapabilityType.AVD, "Pixel_2_API_R");
        capabilities.setCapability(AndroidMobileCapabilityType.AVD_ARGS, "-noaudio -gpu auto -verbose -accel on -no-boot-anim -no-snapshot-save");

        AndroidDriver driver = new AndroidDriver(new URL("http://localhost:4442/wd/hub"), capabilities);

```

**Comment by mykola-mokhnach** [comment]
It looks like your emulator needs more time to complete booting. I could usually observe `boot completed` record in the emulator log when the booting is fully completed, which is not the case here

**Comment by mykola-mokhnach** [comment]
Closed because of no response
