### ISSUE TITLE
defaultAlertAction: "accept" is being registered but not handled on tvOS

### ISSUE THREAD

**Issue by lukeyoui** [appium/appium#14460]
## The problem

Including the capability autoAcceptAlerts: true is setting defaultAlertAction: "accept" on tvOS, however it is not accepting any OS level Alerts. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.0-beta.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Catalina 10.15.2 
* Node.js version (unless using Appium.app|exe): 10.19.0
* Npm or Yarn package manager: 6.13.4
* Mobile platform/version under test: tvOS 13.4.5
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: Appium CLI

## Details

On tvOS, the XCUITest driver is not auto-accepting alerts if the capability is set. This may be due to the fact that tvOS is not officially supported in the WebdriverAgent to the same extent that iOS is, so this issue may be more of a feature request.

To provide more context, the alert used to reproduce this case is a triple option location services prompt, with the options: "Don't Allow", "Allow While Using App", and "Allow Once". 

Note: It is still possible to manually accept the alerts, just not automatically using a capability.

## Link to Appium logs
[GIST](https://gist.github.com/lukeyoui/a91b2ef0625c2404f18902dce980963e)

## Code To Reproduce Issue [ Good To Have ]

Can be reproduced with including the following capabilities:
 "automationName": "XCUITest",
 "platformName": "tvos",
 "autoAcceptAlerts": "true"

**Comment by mykola-mokhnach** [comment]
Could you please share the page source where the alert is shown?

**Comment by lukeyoui** [comment]
Absolutely,
Here is the [Page Source](https://gist.github.com/lukeyoui/13315e2f5a7b32d518e226a34995e48f) when the alert is displayed

**Comment by mykola-mokhnach** [comment]
yep, in the page source it this is a simple `XCUIElementTypeCollectionView`. I don't think there is a reliable way to distinguish this type of alerts from other controls.

**Comment by KazuCocoa** [comment]
Thanks. Hm, it was not `XCUIElementTypeAlert`

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing more we could do on this issue.

**Comment by lukeyoui** [comment]
Thanks for looking into it. I will continue using running a test to manually accept the prompt.
