### ISSUE TITLE
accessibility id not working for react-navigation header on IOS

### ISSUE THREAD

**Issue by saikats5** [appium/appium#14469]
I am trying to write automation test cases using Appium for my react-native application where I am using react-navigation header, the test cases were able to access the accessibleId/TestID earlier but now it stopped working, it is because I have added backgroundImage to my react-navigation header due to which I have to use headerTransparent property and as per the below thread, it will not work.

Not sure if there is any fix for it, we have to make it work in our application

It's working on Android but stopped working on IOS.

link:- https://github.com/react-navigation/react-navigation/issues/5521

**Comment by mykola-mokhnach** [comment]
Please fill out the issue reporting template properly and provide the required info

**Comment by saikats5** [comment]
> Please fill out the issue reporting template properly and provide the required info

not getting, could you please elaborate?

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium/blob/master/.github/ISSUE_TEMPLATE.md should be the default value when you open https://github.com/appium/appium/issues/new

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by KiratiBhuva** [comment]
@saikats5 Did you able to find any solution or workaround?
