### ISSUE TITLE
selected elements don't work 

### ISSUE THREAD

**Issue by tianyao1111** [appium/appium#14470]
## The problem

我在mac上用appium录制脚本时，用selected elements 无法定位元素，上面老是出现一个遮罩层

## Environment
mac：osx 10.11
appium：1.17.1
node：v14.4.0
npm:6.14.4
xcode:9.0
xcode-simulator:iPhone X(11.0)

## Details
问题图片：
<img width="960" alt="appium_issue1" src="https://user-images.githubusercontent.com/24905236/85128739-781f1c80-b264-11ea-9541-b353b21a0478.png">
<img width="960" alt="appium_issue2" src="https://user-images.githubusercontent.com/24905236/85128761-84a37500-b264-11ea-882f-c16e1678bab0.png">

## Link to Appium logs

`[error] [35m[Xcode][39m     t =  3449.9[info] [35m[WD Proxy][39m Got response with status 500: {"value":{"error":"unknown error","message":"-[XCElementSnapshot hitPoint:]: unrecognized selector sent to instance 0x604000b99a50","traceback":"(\n\t0   CoreFoundation                      0x000000010a0621cb __exceptionPreprocess + 171\n\t1   libobjc.A.dylib                     0x00000001099c4f41 objc_exception_throw + 48\n\t2   CoreFoundation                      0x000000010a0e2914 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132\n\t3   CoreFoundation                      0x0000000109fe5178 ___forwarding___ + 1432\n\t4   CoreFoundation                      0x0000000109fe4b58 _CF_forwarding_prep_0 + 120\n\t5   WebDriverAgentLib                   0x0000000124698aa2 -[XCElementSnapshot(FBHitPoint) fb_hitPoint] + 66\n\t6   WebDriverAgentLib                   0x000000012467733f -[FBBaseGestureItem hitpointWithElement:positionOffset:error:] + 847\n\t7   WebDriverAgentLib                   0x000000012464bbe4 -[FBAppiumGestureItem coordinatesWithOptions:error:] + 1284\n\t8   WebDriverAgentLib               ...`

**Comment by mykola-mokhnach** [comment]
Unfortunately Xcode 9 SDK is not supported anymore. Consider downgrading your Appium version

**Comment by tianyao1111** [comment]
> 不幸的是，不再支持Xcode 9 SDK。考虑降级您的Appium版本

但是我还是不知道该降级为哪个版本？您能告诉我吗？

**Comment by KazuCocoa** [comment]
Perhaps Appium 1.14 or Appium 1.15, but iOS 11.0 works Xcode 10, I think.
Then, you can use Xcode 10 with the latest Appium.

**Comment by tianyao1111** [comment]
> 我认为可能是Appium 1.14或Appium 1.15，但iOS 11.0可以使用Xcode 10。
> 然后，您可以将Xcode 10与最新的Appium一起使用。

谢谢
