### ISSUE TITLE
The text is encoded when getting a log from Appium

### ISSUE THREAD

**Issue by thinhtranquoc** [appium/appium#14476]
## The problem
I have using  driver.manage().logs().get("syslog").getAll()  to get log in my device. Some Unicode text is encoded.  I have checked with the console tool of MAC, the text is show correct. 

## Environment

* Appium version : 1.17.1-1
* Desktop OS/version used to run Appium:  Mac OS Catalina, 10.15.5
* Node.js version (unless using Appium.app|exe): 12.8.1
* Npm or Yarn package manager: 6.11.3
* Mobile platform/version under test: iOS 13
* Real device or emulator/simulator:  Real

## Details
**Log console tool of Mac**
`EVENTLOG: {"properties":{"tk_dimension1":"Có Thể Bạn Quan Tâm","action_name":"custom_event","tk_dimension2":"[\"22611034\",\"192412\",\"55502648\",\"7718734\",\"1694079\",\"11232443\",\"15415623\",\"52597664\"]","tk_action":"glance_view","device_token":"ehhmhdBbWk-YnodvEGL64c:APA91bGnxW5UTRls6-AZxACs2JsrWuXPMaPTF7cYKTh7lZpns2r6qOBHGzrr8lmdsgrMJklYw","tk_category":"widget_listing","source_screen_data":"[{\"time\":1592818326641.407,\"name\":\"home\"}]","screen_data":"{\"name\":\"home\"}","client_id":"2167039c-a95","screen_class":"Home","device_idfv":"2167039c-a950-402d-a65aw","sanitized_at":"2020-06-22T16:32:10+07:00"},"channel":"Trackity","event_name":"custom_event"}`

**Log Appium**
`EVENTLOG: {"properties":{"tk_dimension1":"C\M-C\M-3 Th\M-a\M-;\M^C B\M-a\M-:\M-!n Quan T\M-C\M-"m","action_name":"custom_event","tk_dimension2":"[\134"22611034\134",\134"192412\134",\134"55502648\134",\134"7718734\134",\134"1694079\134",\134"11232443\134",\134"15415623\134",\134"52597664\134"]","tk_action":"glance_view","device_token":"ehhmhdBbWk-YnodvEGL64c:APA91bGnxW5UTRls6-AZxACs2JsrWuXPMaPTF7cYKTh7lZpns2r6qOBHGzrr8lmdsgrMJklYw","tk_category":"widget_listing","source_screen_data":"[{\134"time\134":1592818326641.407,\134"name\134":\134"home\134"}]","screen_data":"{\134"name\134":\134"home\134"}","client_id":"2167039c-a95","screen_class":"Home","device_idfv":"2167039c-a950-402d-a65aw","sanitized_at":"2020-06-22T16:32:10+07:00"},"channel":"Trackity","event_name":"custom_event"}`

**The text-encode**:  "tk_dimension1":"C\M-C\M-3 Th\M-a\M-;\M^C B\M-a\M-:\M-!n Quan T\M-C\M-"m"

## Link to Appium logs
https://gist.github.com/thinhtranquoc/e3aa0335b54a9433da4d5d9eaafa9b02

**Comment by mykola-mokhnach** [comment]
Related to https://github.com/appium/appium/issues/14100

I assume there is an issue with encoding inside of appium-ios-device lib. Is there anyone capable of fixing it?

**Comment by KazuCocoa** [comment]
hm, okay
Let me take a look

**Comment by KazuCocoa** [comment]
https://www.npmjs.com/package/appium-ios-device/v/1.6.0
It is available via `appium@beta`
