### ISSUE TITLE
Appium stops working under virtual Windows 10 using real devices

### ISSUE THREAD

**Issue by Joisan007** [appium/appium#14477]
## The problem

Appium Server stops responding after 3-5 minutes of execution

## Environment

* Appium version (or git revision) that exhibits the issue:1.15.1
* Last Appium version that did not exhibit the issue (if applicable):NA
* Desktop OS/version used to run Appium: Windows 10 x64 virtual machine hosted on HP G9 ESXI 6.7
* Node.js version (unless using Appium.app|exe): 11.0
* Npm or Yarn package manager: 6.13.0
* Mobile platform/version under test: Android 6, Android 9
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: java-client 7.3.0

## Details

I have tests written in Java, to run them I use IntelliJ IDE or gradle task. My whole environment is setup on the Windows 10 virtual machine. I setup only once Appium Server for each real device I have connected to execute the whole test suite (about 120 tests). When I run these tests I can see that after some time ~3-5 minutes the whole execution get stuck. It looks like Appium server stops responding, after some time 2-5 hours I got an error message Caused by: java.net.SocketTimeoutException: Read timed out , Caused by: java.net.SocketTimeoutException: timeout.
This issue doesn't reproduce on the Windows 10 x64 installed on the PC. 
Also if I create Appium server and Android Driver before each test it is executing fine but the time that is added to the execution time is not acceptable as I am using 4 real devices. 

## Link to Appium logs
https://gist.github.com/Joisan007/997c85a0bdc2b3472247ab395571c122/63a3e8dfe81e25d6859d29e6ed6190d8592cdb7e#file-appium_logs_socket_exception

**Comment by mykola-mokhnach** [comment]
I don't think this has anything to do with Appium itself. The disconnect happens on the higher levels. Check the device logcat output - it may contain more details.

**Comment by Joisan007** [comment]
Well I'm not sure of that because if I run curl http://localhost:39825/wd/hub/status it returns nothing, the cmd waits for any answer but nothing comes. 
But if I check if there is anything listening on this port netstat -a -n -b 39825 I can see the port is in use
https://gist.github.com/Joisan007/d16e135328dabf290138b40bce82f04f#file-port_status

**Comment by Joisan007** [comment]
One more update about this issue:
1) VM Windows 10:
a) if I create one **appium server** using:
private AppiumServiceBuilder builder = new AppiumServiceBuilder();
        builder.usingAnyFreePort();
        String home = System.getProperty("user.home");
        builder.withAppiumJS(new File(home + "/AppData/Roaming/npm/node_modules/appium/build/lib/main.js").getAbsoluteFile());
        builder.withArgument(SUPPRESS_ADB_KILL_SERVER);
        builder.withArgument(SESSION_OVERRIDE);
        builder.withArgument(LOG_LEVEL, "debug");
        builder.withArgument(LOG_TIMESTAMP);
        builder.withArgument(LOCAL_TIMEZONE);
private AppiumDriverLocalService service= AppiumDriverLocalService.buildService(builder);

and based on that I create **AndroidDriver**:
private URL appiumServerUrl = service.getUrl();
private DesiredCapabilities desiredCapabilities = new DesiredCapabilities();

        desiredCapabilities.setCapability(NO_RESET, true);
        desiredCapabilities.setCapability(FULL_RESET, false);
        desiredCapabilities.setCapability(PLATFORM_NAME, "Android");
        desiredCapabilities.setCapability(APPLICATION_NAME, "testAppium");
        desiredCapabilities.setCapability(APP, new File("C://application.apk").getAbsolutePath());
        desiredCapabilities.setCapability(APP_PACKAGE, "com.application");
        desiredCapabilities.setCapability(APP_ACTIVITY, "com.application.MainActivity");
        desiredCapabilities.setCapability(AUTO_GRANT_PERMISSIONS, true);
        desiredCapabilities.setCapability(UNICODE_KEYBOARD, true);
        desiredCapabilities.setCapability(DONT_STOP_APP_ON_RESET, true);
        desiredCapabilities.setCapability("unlockType", UNLOCK_TYPE_PIN);
        desiredCapabilities.setCapability("unlockKey", "1234);
        desiredCapabilities.setCapability("autoLaunch", true);
        desiredCapabilities.setCapability(NEW_COMMAND_TIMEOUT, 120);
        desiredCapabilities.setCapability(EVENT_TIMINGS, true);
        desiredCapabilities.setCapability("actionAcknowledgmentTimeout", "10000");
        desiredCapabilities.setCapability(UDID, "YYYYYY");
        desiredCapabilities.setCapability(DEVICE_NAME, "Device_Name");
        desiredCapabilities.setCapability(DEVICE_MODEL, "Device_Model");
        desiredCapabilities.setCapability(DEVICE_READY_TIMEOUT, "10");

AndroidDriver androidDriver = new AndroidDriver(appiumServerUrl, desiredCapabilities);

then based on this driver I create my application under test 

ApplicationUnderTest applicationUnderTest1 = new ApplicationUnderTest(androidDriver);

simple methods to use it:
applicationUnderTest1.launchApplication(); // here my application will be open in foreground

I run many appium servers as I have more than one device, at some point the execution hangs as mentioned above. 
To verify if it also reproduce for single appium server I also created only one server and run some basic tests, it also hanged.

b) If I do not create appium server but I only create AndroidDriver:
        AndroidDriver androidDriver = new AndroidDriver(desiredCapabilities);
so I'm using default builder of AppiumDriverLocalService and defult port, no modification are done by me to the appium server.
I run tests only on the one device as I can run only one appium server like that, the execution does not hang. I checked my all available devices to get rid of the potential issue that there is some problem with my devices and in all cases the tests passed without any hangs.

2) PC with Windows 10 installed
Multiple instances of appium server mentioned in 1.a) are working fine, I can tests many devices in parallel

Maybe now someone could help me where to look for any solution? Maybe there is a need to set some specific settings on the virtual Windows 10 machine?

**Comment by mykola-mokhnach** [comment]
Sorry, without the requested logcat output we cannot help nothing

**Comment by mykola-mokhnach** [comment]
Also, it makes sense to check how it works with appoim@beta first

**Comment by Joisan007** [comment]
Please find here logs: https://gist.github.com/Joisan007/40cb752079367caeedaf8ab38f2ac194 https://gist.github.com/Joisan007/109765ed185721f422f212ce2200fa9c

**Comment by mykola-mokhnach** [comment]
the log is very big and thus hard to read. I would prefer to get something, that is limited to the time range where the disconnect happens.

**Comment by mykola-mokhnach** [comment]
Also it looks like there are some older sessions that were not closed properly, so they affect the current ones. See https://github.com/appium/appium/issues/13873 for more details.

**Comment by Joisan007** [comment]
Please find here another logs, I set up appium server with sessionOverride: true.
The execution got stuck on the session: 3044af4f-99a2-40c1-9a9b-94773344fe7a that should be replaced by bec2fd3b-82e1-4da8-b2a5-94d5972a31bc but I do not see any bec2fd3b-82e1-4da8-b2a5-94d5972a31bc in the logcat logs.
Here is a log from Appium Server and Android Driver creation: https://gist.github.com/Joisan007/bd2db368b15e0eceed10dbe1c15f142a
Here is an IDE log from test execution: 
https://gist.github.com/Joisan007/964f260932b2bff5d6df407c071d61c8
Here is a logcat log from the device with mentioned session: 
https://gist.github.com/Joisan007/5fdbbf17f3e965df11552c381bc60c76

The timestamp of the execution hang: 10:50:47 (IDE log)
I had to stop the execution manually.

**Comment by mykola-mokhnach** [comment]
I don't observe any explicit errors in the provided logs. I would also try the most recent server version (preferably appium@beta). Otherwise I don't have any other ideas

**Comment by Joisan007** [comment]
I only suspect that this virtual environment can cause some problems with sockets. I do not have any prove of course. Only this behavior when the execution hangs and then request for Appium server status also hangs.
I was also thinking maybe the issue occurs because I create Appium Server and Android Driver only once for the whole execution, no matter how many tests are to be run, so at some point I have the same Appium Server and the same Android Driver for about 150 tests, one test can take up to 15 minutes. I am testing many applications on the one device and some interactions between several devices and this applications. And finally I do not close any session. Until I wanted to migrate to virtual environment everything was fine so maybe Virtual Windows can cause it?

**Comment by mykola-mokhnach** [comment]
> After update I could see them in the IDE, the execution process stopped hanging. Anyway I'm a little bit confused if this is related with UiAutomator version? I was thinking Appium 1.16 will support only UIAutomator2 but I had version 1.15.1 so I wasn't expecting issues related to that.

It's hard to say which change between the version numbers helped, because there were many. In general I could say that not closing the test sessions is not a recommended approach.
