### ISSUE TITLE
Catalina OSX XProtect Change Critical Bug!!! Appium IOS WebDriverAgent on IOS Simulators

### ISSUE THREAD

**Issue by sergydimitrov** [appium/appium#14473]
## The problem

Critical issue for IOS Simulators running Appium tests on **Catalina OS**. 
**Catalina** major security changes for XProtect Service added XProtect rules under XProtect bundle as XProtect.yara extension. The new malware rules are adding a verfication phase to appium test runs on target IOS Simulators. 

Clearing quarantine flags through **xattr** no longer works for Catalina based on the new XProtect rules.

After the initial upload phase When target app and appium web driver agent is uploaded to any specific IOS Simulator. During the target mobile application startup **Catalina XProtect** Service initiates a Verification stage. A Verifying Popup is shown and app is verified and popup closes automatically.

At that time interval we get a WDA session creation error status 500 from Appium XCUIT Test driver. The error is "**Failed to create WDA session ... unable to find process id 0 ..... Retrying...**"

Appium XCUIT Test driver the second time retry to open WDA Session and got 200 status from the server and target app to be tested boots on the IOS Simulator.

But it stays **completely frozen** on the main screen and **test does not proceed**. A very simple Verification Popup in Catalina based on the XProtect Service rules crashes Appium WebDriver Agent.

Even the WDA session created the second time, the first time that response 500 for WDA Session creation breaks the whole test cycle. Appium tests do not proceed and Simulator stays on the target mobile application main screen.

The issue is highly critical it can be classified as major Catalina flow. The security changes

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Catalina 10.15.X 
* Node.js version (unless using Appium.app|exe): 12.18.1
* Npm or Yarn package manager: 6.14.5
* Mobile platform/version under test: IOS 12.4 and XCode 11.3.1
* Real device or emulator/simulator: Iphone 6s Plus IOS 12.4
* Appium CLI or Appium.app|exe: Both Appium CLI and Appium Desktop App

## Details

The critical issue only happens on the new OS Catalina environment based on the security changes.
The issue is only specific to Catalina and IOS Simulators. Catalina Verifies the app during the boot time on the IOS Simulator after app and web driver is installed.

Verification stage comes from the major security changes of Catalina. Appium must be robust for this stage. **A very simple short duration verification popup in the application boot interval crashed the Apium Test Driver completely.** 

## Link to Appium logs

https://gist.github.com/sergydimitrov/d082cdfbddcc8bf725809a85332f7f24

## Code To Reproduce Issue [ Good To Have ]

Reproduce steps is very simple.  
1) Write a small applium test in Java or Javascript or etc... for a particular IOS application.
2) Build the application for IOS Simulator only. (app extension)
3) Run Appium test through CLI  
4) Simulator will boot and then app will be installed for the first time and Appium Web Agent driver will be installed. When app opens Catalina Verification popup appear and in a very short duration verification popup closes. After that app opens but stays idle and test will not proceed. 
5) If you run the same test in full reset mode same steps will repeat. App open stay idle and test will not proceed.

**Comment by mykola-mokhnach** [comment]
Please attach the properly formatted server log. The current one is impossible to read

**Comment by sergydimitrov** [comment]
@mykola-mokhnach Hello, I editted the server log which was taken from Appium server. 
https://gist.github.com/sergydimitrov/d082cdfbddcc8bf725809a85332f7f24
Could you please help?

**Comment by sergydimitrov** [comment]
Hi MyKola

Thank you very much for your interest on this serious issue.
I am seeing couple of differences in your test. 
First of all why did you build **iPA** for IOS Simulator? Did you build it for Generic Device? Is it an ARM Build?
Or Did you download an **ipa** sample from the web? 
Your application must be built for Simulator only .app file extension. Try to test it with .app and see.

The other thing is the mobile application that you are testing might be too simple and narrow. Maybe it may not contain default Catalina XProtect Malware rules. Maybe it is not containing the dependencies we have. We are talking about an enterprise mobile application here. XProtect yara rules are getting activated. And when app boots on the simulator Verification popup will show.

This issue is very much reproducible. All enterprise appium customers will face this issue. 
The problem is the verfication popup. It fails to create the WDA session because it sees Catalina Scheduler process id 0. Second try appium creates the WDA session but it is too late test stops proceeding.

I am 100% sure this is a BUG and it is inside the WebDriverAgent. I can not tell what is happening but it preserves a state related with this WDA Session and it won't take any commands further.

I will repeat, this is a very serious issue. Catalina OS blocking the whole test automation process.

**Comment by mykola-mokhnach** [comment]
We have the test app in Appium called iOS catalog. The .ipa file contains .app bundle built for Simulator. The same result I get when I simply extract the archive and provide a direct path to the .ipa file.

> I am 100% sure this is a BUG and it is inside the WebDriverAgent. I can not tell what is happening but it preserves a state related with this WDA Session and it won't take any commands further.

I did add https://github.com/appium/WebDriverAgent/pull/355 from what I saw in the stack trace, but this is just a pure guess. I cannot do more there without the ability to reproduce it. Feel free to provide your own patch to WDA if necessary.

**Comment by sergydimitrov** [comment]
Thank you very much MyKola,
Let us check if that patch will work or not. I totally agree you need to reproduce the issue.
We will try to see if we can add more to this patch and also try give you a clear path to reproduce the issue using the IOS Catalog test application.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
