### ISSUE TITLE
iPhone’s iOS 13.5.1 doesn’t match WebDriverAgentRunner’s iOS 13.15 deployment target

### ISSUE THREAD

**Issue by arhanechka** [appium/appium#14487]
Trying to run app on the real iOS device. App installed but WDA can not run
xcodebuild: error: Failed to build project WebDriverAgent with scheme WebDriverAgentRunner.
[debug] [W3C] 	Reason: Cannot test target “WebDriverAgentRunner” on “Hanna’s iPhone”: Hanna’s iPhone’s iOS 13.5.1 doesn’t match WebDriverAgentRunner’s iOS 13.15 deployment target.. 
Full log:
[Appium] Welcome to Appium v1.17.1
[Appium] Non-default server args:
[Appium]   relaxedSecurityEnabled: true
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"appPackage”:”’**’”,”noReset":"","connectHardwareKeyboard":"","locationServicesEnabled":"true","deviceName":"iPhone8AQA","fullReset":"","xcodeSigningId":"iPhone Developer","androidInstallTimeout":"60000","locationServicesAuthorized":"true","showXcodeLog":"true","newCommandTimeout":"","platformVersion":"13.15.1","automationName":"XCUITEST","platformName":"iOS","udid”:”**”,”app":"/Users/**/Downloads/adhoc_4.63.7.791.ipa","xcodeOrgId”:”**”,”bundleId":"","launchTimeout":"","updatedWDABundleId":"","appActivity":"'com.**’”,”wdaStartupRetryInterval":"","autoLaunch":"","adbExecTimeout":"30000","autoGrantPermissions":"true","autoAcceptAlerts":""},"capabilities":{"firstMatch":[{"adbExecTimeout":"30000","appium:androidInstallTimeout":"60000","appium:app":"/Users/**/Downloads/**.ipa","appium:appActivity":"'com.**’”,”appium:appPackage":"'com.&’**,”app
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"appPackage”:”’**’”,”noReset":"","connectHardwareKeyboard":"","locationServicesEnabled":"true","deviceName":"iPhone8AQA","fullReset":"","xcodeSigningId":"iPhone Developer","androidInstallTimeout":"60000","locationServicesAuthorized":"true","showXcodeLog":"true","newCommandTimeout":"","platformVersion":"13.15.1","automationName":"XCUITEST","platformName":"iOS","udid”:”**”,”app":"/Users/**/Downloads/**.ipa","xcodeOrgId”:”**”,”bundleId":"","launchTimeout":"","updatedWDABundleId":"","appActivity":"'com.**’”,”wdaStartupRetryInterval":"","autoLaunch":"","adbExecTimeout":"30000","autoGrantPermissions":"true","autoAcceptAlerts":""},null,{"firstMatch":[{"adbExecTimeout":"30000","appium:androidInstallTimeout":"60000","appium:app":"/Users/**/Downloads/**.ipa","appium:appActivity":"'com.**’”,”appium:appPackage":"'com.**’”,”appium:autoAcceptAlerts":"","appium:autoGrantPermissions...
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1593153745406 (09:42:25 GMT+0300 (Eastern European Summer Time))
[BaseDriver] The following capabilities are not standard capabilities and should have an extension prefix:
[BaseDriver]   adbExecTimeout
[BaseDriver]   autoLaunch
[BaseDriver] Number capability passed in as string. Functionality may be compromised.
[Appium] Appium v1.17.1 creating new XCUITestDriver (v3.22.0) session
[Appium] Applying relaxed security to 'XCUITestDriver' as per server command line argument. All insecure features will be enabled unless explicitly disabled by --deny-insecure
[debug] [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {
[debug] [BaseDriver]   "alwaysMatch": {
[debug] [BaseDriver]     "appium:adbExecTimeout": "30000",
[debug] [BaseDriver]     "appium:autoLaunch": "",
[debug] [BaseDriver]     "platformName": "ios",
[debug] [BaseDriver]     "appium:androidInstallTimeout": "60000",
[debug] [BaseDriver]     "appium:app": "/Users/**/Downloads/**.ipa",
[debug] [BaseDriver]     "appium:appActivity": “’**’”,
[debug] [BaseDriver]     "appium:appPackage": “’**’”,
[debug] [BaseDriver]     "appium:autoAcceptAlerts": "",
[debug] [BaseDriver]     "appium:autoGrantPermissions": "true",
[debug] [BaseDriver]     "appium:automationName": "XCUITEST",
[debug] [BaseDriver]     "appium:bundleId": "",
[debug] [BaseDriver]     "appium:connectHardwareKeyboard": "",
[debug] [BaseDriver]     "appium:deviceName": "iPhone8AQA",
[debug] [BaseDriver]     "appium:fullReset": "",
[debug] [BaseDriver]     "appium:launchTimeout": "",
[debug] [BaseDriver]     "appium:locationServicesAuthorized": "true",
[debug] [BaseDriver]     "appium:locationServicesEnabled": "true",
[debug] [BaseDriver]     "appium:newCommandTimeout": "",
[debug] [BaseDriver]     "appium:noReset": "",
[debug] [BaseDriver]     "appium:platformVersion": "13.15.1",
[debug] [BaseDriver]     "appium:showXcodeLog": "true",
[debug] [BaseDriver]     "appium:udid": “**”,
[debug] [BaseDriver]     "appium:updatedWDABundleId": "",
[debug] [BaseDriver]     "appium:wdaStartupRetryInterval": "",
[debug] [BaseDriver]     "appium:xcodeOrgId": “**”,
[debug] [BaseDriver]     "appium:xcodeSigningId": "iPhone Developer"
[debug] [BaseDriver]   },
[debug] [BaseDriver]   "firstMatch": [
[debug] [BaseDriver]     {}
[debug] [BaseDriver]   ]
[debug] [BaseDriver] }
[BaseDriver] Number capability passed in as string. Functionality may be compromised.
[BaseDriver] Number capability passed in as string. Functionality may be compromised.
[BaseDriver] Capability 'showXcodeLog' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Capability 'locationServicesEnabled' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Capability 'locationServicesAuthorized' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Capability 'newCommandTimeout' changed from string ('') to integer (NaN). This may cause unexpected behavior
[BaseDriver] Capability 'wdaStartupRetryInterval' changed from string ('') to integer (NaN). This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[BaseDriver]   adbExecTimeout
[BaseDriver]   androidInstallTimeout
[BaseDriver]   appActivity
[BaseDriver]   appPackage
[BaseDriver]   autoGrantPermissions
[BaseDriver] Session created with session id: 9da8a70b-bc82-4350-a033-fe744a6cc14c
[debug] [XCUITest] Current user: ‘**’
[debug] [XCUITest] Available devices: **
[debug] [XCUITest] Creating iDevice object with udid ‘**’
[XCUITest] Determining device to run tests on: udid: ‘**’, real device: true
[XCUITest] Normalized platformVersion capability value '13.15.1' to '13.15'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1593153746416 (09:42:26 GMT+0300 (Eastern European Summer Time))
[BaseDriver] Using local app '/Users/**/Downloads/**.ipa'
[debug] [BaseDriver] Unzipping '/Users/**/Downloads/**.ipa'
[debug] [Support] Traversed 1470 directories and 3614 files in 250ms
[debug] [BaseDriver] Extracted 5084 item(s) from '/Users/**/Downloads/**ipa'
[debug] [Support] Traversed 1470 directories and 3614 files in 244ms
[debug] [BaseDriver] Matched 5082 item(s) in the extracted archive. Assuming 'Payload/**.app' is the correct bundle
[BaseDriver] Unzipped local app to '/var/folders/0v/wcg3q99x0zd4g8rbzr_7gwgw00r2xh/T/2020526-50359-21maw2.794tpg/Payload/**.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1593153751445 (09:42:31 GMT+0300 (Eastern European Summer Time))
[debug] [XCUITest] Checking whether app '/var/folders/0v/wcg3q99x0zd4g8rbzr_7gwgw00r2xh/T/2020526-50359-21maw2.794tpg/Payload/**.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [iOS] Getting bundle ID from app '/var/folders/0v/wcg3q99x0zd4g8rbzr_7gwgw00r2xh/T/2020526-50359-21maw2.794tpg/Payload/**.app': 'com.**.iphone'
[debug] [BaseDriver] Event 'resetStarted' logged at 1593153751448 (09:42:31 GMT+0300 (Eastern European Summer Time))
[debug] [XCUITest] Reset: running ios real device reset flow
[debug] [BaseDriver] Event 'resetComplete' logged at 1593153751448 (09:42:31 GMT+0300 (Eastern European Summer Time))
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1593153751648 (09:42:31 GMT+0300 (Eastern European Summer Time))
[XCUITest] Setting up real device
[debug] [XCUITest] Verifying application platform
[debug] [XCUITest] CFBundleSupportedPlatforms: ["iPhoneOS"]
[debug] [XCUITest] Reset requested. Removing app with id 'com.**iphone' from the device
[debug] [XCUITest] Installing '/var/folders/0v/wcg3q99x0zd4g8rbzr_7gwgw00r2xh/T/2020526-50359-21maw2.794tpg/Payload/**.app' on device with UUID ‘**’…
[debug] [Support] Traversed 1468 directories and 3614 files in 27834ms
[debug] [XCUITest] Pushed the app files successfully after 27955ms
[XCUITest] App installation succeeded after 29237ms
[debug] [XCUITest] The app has been installed successfully.
[debug] [BaseDriver] Event 'appInstalled' logged at 1593153781376 (09:43:01 GMT+0300 (Eastern European Summer Time))
[WebDriverAgent] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent'
[WebDriverAgent] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'
[debug] [WebDriverAgent] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[DevCon Factory] Requesting connection for device ** on local port 8100, device port 8100
[debug] [DevCon Factory] Cached connections count: 0
[DevCon Factory] Successfully requested the connection for **:8100
[debug] [WebDriverAgent] Parsed BUILD_DIR configuration value: '/Users/**/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu/Build/Products'
[debug] [WebDriverAgent] Got derived data root: '/Users/**/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu'
[debug] [XCUITest] Starting WebDriverAgent initialization with the synchronization key '/Users/**/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu'
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[debug] [iProxy@6007c008:8100] Connection was refused to port 8100
[WD Proxy] Got response with unknown status: {"code":"ECONNRESET"}
[debug] [WebDriverAgent] WDA is not listening at 'http://127.0.0.1:8100/'
[debug] [WebDriverAgent] WDA is currently not running. There is nothing to cache
[debug] [XCUITest] Trying to start WebDriverAgent 1 times with 10000ms interval
[debug] [XCUITest] These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1593153784836 (09:43:04 GMT+0300 (Eastern European Summer Time))
[WebDriverAgent] Launching WebDriverAgent on the device
[WebDriverAgent] Fetching dependencies
[WebDriverAgent] Dependencies up-to-date
[debug] [WebDriverAgent] Killing running processes 'xcodebuild.***’ for the device **…
[debug] [WebDriverAgent] 'pgrep -if xcodebuild.***’ didn't detect any matching processes. Return code: 1
[debug] [WebDriverAgent] Generating xcode config file for orgId ‘**’ and signingId 'iPhone Developer'
[debug] [WebDriverAgent] Writing xcode config file to /var/folders/0v/wcg3q99x0zd4g8rbzr_7gwgw00r2xh/T/2020526-50359-187f62h.54o3/appium-temp.xcconfig
[debug] [WebDriverAgent] Using Xcode configuration file: '/var/folders/0v/wcg3q99x0zd4g8rbzr_7gwgw00r2xh/T/2020526-50359-187f62h.54o3/appium-temp.xcconfig'
[debug] [WebDriverAgent] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath /Users/**/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu -destination id=** IPHONEOS_DEPLOYMENT_TARGET=13.15 -xcconfig /var/folders/0v/wcg3q99x0zd4g8rbzr_7gwgw00r2xh/T/2020526-50359-187f62h.54o3/appium-temp.xcconfig GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent'
[debug] [WebDriverAgent] Output from xcodebuild will be logged. To change this, use 'showXcodeLog' desired capability
[Xcode] Command line invocation:
[Xcode]     
[debug] [WebDriverAgent] Waiting up to 60000ms for WebDriverAgent to start
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[Xcode] /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath /Users/**/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu -destination id=** IPHONEOS_DEPLOYMENT_TARGET=13.15 -xcconfig /var/folders/0v/wcg3q99x0zd4g8rbzr_7gwgw00r2xh/T/2020526-50359-187f62h.54o3/appium-temp.xcconfig GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO
[Xcode] 
[Xcode] User defaults from command line:
[Xcode]     IDEDerivedDataPathOverride = /Users/**/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu
[Xcode] 
[Xcode] Build settings from command line:
[Xcode]     COMPILER_INDEX_STORE_ENABLE = NO
[Xcode]     GCC_TREAT_WARNINGS_AS_ERRORS = 0
[Xcode]     IPHONEOS_DEPLOYMENT_TARGET = 13.15
[Xcode] 
[Xcode] Build settings from configuration file '/var/folders/0v/wcg3q99x0zd4g8rbzr_7gwgw00r2xh/T/2020526-50359-187f62h.54o3/appium-temp.xcconfig':
[Xcode]     CODE_SIGN_IDENTITY = iPhone Developer
[Xcode]     DEVELOPMENT_TEAM = **
[Xcode] 
[Xcode] 
[debug] [iProxy@6007c008:8100] Connection was refused to port 8100
[WD Proxy] Got response with unknown status: {"code":"ECONNRESET"}
[Xcode] 2020-06-26 09:43:05.778 xcodebuild[50443:6783936]  DTDeviceKit: deviceType from ** was NULL
[Xcode] 
[Xcode] 2020-06-26 09:43:05.867 xcodebuild[50443:6783928]  DTDeviceKit: deviceType from ** was NULL
[Xcode] 
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[debug] [iProxy@6007c008:8100] Connection was refused to port 8100
[WD Proxy] Got response with unknown status: {"code":"ECONNRESET"}
[Xcode] note: Using new build system
[Xcode] 
[Xcode] note: Building targets in parallel
[Xcode] 
[Xcode] note: Planning build
[Xcode] 
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[debug] [iProxy@6007c008:8100] Connection was refused to port 8100
[WD Proxy] Got response with unknown status: {"code":"ECONNRESET"}
[Xcode] note: Using build description from disk
[Xcode] 
[Xcode] warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 13.15, but the range of supported deployment target versions is 8.0 to 13.5.99. (in target 'WebDriverAgentLib' from project 'WebDriverAgent')
[Xcode] warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 13.15, but the range of supported deployment target versions is 8.0 to 13.5.99. (in target 'WebDriverAgentRunner' from project 'WebDriverAgent')
[Xcode] 
[Xcode] 
[Xcode] 
[Xcode] ** TEST BUILD SUCCEEDED **
[Xcode] 
[Xcode] 
[Xcode] xcodebuild: error: Failed to build project WebDriverAgent with scheme WebDriverAgentRunner.
[Xcode] 	Reason: Cannot test target “WebDriverAgentRunner” on “**”: **’s iOS 13.5.1 doesn’t match WebDriverAgentRunner’s iOS 13.15 deployment target.
[Xcode] 
[WebDriverAgent] xcodebuild exited with code '70' and signal 'null'
[WebDriverAgent] Launching WebDriverAgent on the device
[WebDriverAgent] Fetching dependencies
[WebDriverAgent] Dependencies up-to-date
[debug] [WebDriverAgent] Killing running processes 'xcodebuild.***' for the device **...
[debug] [WebDriverAgent] 'pgrep -if xcodebuild.***' didn't detect any matching processes. Return code: 1
[debug] [WebDriverAgent] Using Xcode configuration file: '/var/folders/0v/wcg3q99x0zd4g8rbzr_7gwgw00r2xh/T/2020526-50359-187f62h.54o3/appium-temp.xcconfig'
[debug] [WebDriverAgent] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath /Users/**/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu -destination id=** IPHONEOS_DEPLOYMENT_TARGET=13.15 -xcconfig /var/folders/0v/wcg3q99x0zd4g8rbzr_7gwgw00r2xh/T/2020526-50359-187f62h.54o3/appium-temp.xcconfig GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent'
[debug] [WebDriverAgent] Output from xcodebuild will be logged. To change this, use 'showXcodeLog' desired capability
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[Xcode] Command line invocation:
[Xcode]     /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath /Users/**/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu -destination id=** IPHONEOS_DEPLOYMENT_TARGET=13.15 -xcconfig /var/folders/0v/wcg3q99x0zd4g8rbzr_7gwgw00r2xh/T/2020526-50359-187f62h.54o3/appium-temp.xcconfig GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO
[Xcode] 
[Xcode] User defaults from command line:
[Xcode]     IDEDerivedDataPathOverride = /Users/**/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu
[Xcode] 
[Xcode] Build settings from command line:
[Xcode]     COMPILER_INDEX_STORE_ENABLE = NO
[Xcode]     GCC_TREAT_WARNINGS_AS_ERRORS = 0
[Xcode]     IPHONEOS_DEPLOYMENT_TARGET = 13.15
[Xcode] 
[Xcode] Build settings from configuration file '/var/folders/0v/wcg3q99x0zd4g8rbzr_7gwgw00r2xh/T/2020526-50359-187f62h.54o3/appium-temp.xcconfig':
[Xcode]     CODE_SIGN_IDENTITY = iPhone Developer
[Xcode]     DEVELOPMENT_TEAM = **
[Xcode] 
[Xcode] 
[debug] [WebDriverAgent] Waiting up to 60000ms for WebDriverAgent to start
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[debug] [iProxy@6007c008:8100] Connection was refused to port 8100
[debug] [iProxy@6007c008:8100] Connection was refused to port 8100
[WD Proxy] Got response with unknown status: {"code":"ECONNRESET"}
[WD Proxy] Got response with unknown status: {"code":"ECONNRESET"}
[Xcode] note: Using new build system
[Xcode] 
[Xcode] note: Building targets in parallel
[Xcode] 
[Xcode] note: Planning build
[Xcode] 
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[debug] [iProxy@6007c008:8100] Connection was refused to port 8100
[debug] [iProxy@6007c008:8100] Connection was refused to port 8100
[WD Proxy] Got response with unknown status: {"code":"ECONNRESET"}
[WD Proxy] Got response with unknown status: {"code":"ECONNRESET"}
[Xcode] note: Using build description from disk
[Xcode] 
[Xcode] warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 13.15, but the range of supported deployment target versions is 8.0 to 13.5.99. (in target 'WebDriverAgentRunner' from project 'WebDriverAgent')
[Xcode] 
[Xcode] warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 13.15, but the range of supported deployment target versions is 8.0 to 13.5.99. (in target 'WebDriverAgentLib' from project 'WebDriverAgent')
[Xcode] 
[Xcode] 
[Xcode] 
[Xcode] ** TEST BUILD SUCCEEDED **
[Xcode] 
[Xcode] 
[Xcode] xcodebuild: error: Failed to build project WebDriverAgent with scheme WebDriverAgentRunner.
[Xcode] 	Reason: Cannot test target “WebDriverAgentRunner” on “**”: **’s iOS 13.5.1 doesn’t match WebDriverAgentRunner’s iOS 13.15 deployment target.
[Xcode] 
[WebDriverAgent] xcodebuild exited with code '70' and signal 'null'
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1593153790316 (09:43:10 GMT+0300 (Eastern European Summer Time))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70
[debug] [XCUITest] xcodebuild error message:
[debug] [XCUITest] 
[debug] [XCUITest] Command line invocation:
[debug] [XCUITest]     /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath /Users/**/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu -destination id=** IPHONEOS_DEPLOYMENT_TARGET=13.15 -xcconfig /var/folders/0v/wcg3q99x0zd4g8rbzr_7gwgw00r2xh/T/2020526-50359-187f62h.54o3/appium-temp.xcconfig GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO
[debug] [XCUITest] User defaults from command line:
[debug] [XCUITest]     IDEDerivedDataPathOverride = /Users/**/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu
[debug] [XCUITest] Build settings from command line:
[debug] [XCUITest]     COMPILER_INDEX_STORE_ENABLE = NO
[debug] [XCUITest]     GCC_TREAT_WARNINGS_AS_ERRORS = 0
[debug] [XCUITest]     IPHONEOS_DEPLOYMENT_TARGET = 13.15
[debug] [XCUITest] Build settings from configuration file '/var/folders/0v/wcg3q99x0zd4g8rbzr_7gwgw00r2xh/T/2020526-50359-187f62h.54o3/appium-temp.xcconfig':
[debug] [XCUITest]     CODE_SIGN_IDENTITY = iPhone Developer
[debug] [XCUITest]     DEVELOPMENT_TEAM = **
[debug] [XCUITest] note: Using new build system
[debug] [XCUITest] note: Building targets in parallel
[debug] [XCUITest] note: Planning build
[debug] [XCUITest] note: Using build description from disk
[debug] [XCUITest] warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 13.15, but the range of supported deployment target versions is 8.0 to 13.5.99. (in target 'WebDriverAgentRunner' from project 'WebDriverAgent')
[debug] [XCUITest] warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 13.15, but the range of supported deployment target versions is 8.0 to 13.5.99. (in target 'WebDriverAgentLib' from project 'WebDriverAgent')
[debug] [XCUITest] ** TEST BUILD SUCCEEDED **
[debug] [XCUITest] xcodebuild: error: Failed to build project WebDriverAgent with scheme WebDriverAgentRunner.
[debug] [XCUITest] 	Reason: Cannot test target “WebDriverAgentRunner” on “**”: **’s iOS 13.5.1 doesn’t match WebDriverAgentRunner’s iOS 13.15 deployment target.. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[XCUITest] Quitting and uninstalling WebDriverAgent
[WebDriverAgent] Shutting down sub-processes
[debug] [WebDriverAgent] No WDAs on the device.
[XCUITest] {}
[DevCon Factory] Releasing connections for ** device on any port number
[DevCon Factory] Found cached connections to release: ["**:8100"]
[DevCon Factory] Releasing the listener for '**:8100'
[debug] [iProxy@6007c008:8100] Closing the connection
[debug] [DevCon Factory] Cached connections count: 0
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[iProxy@6007c008:8100] The connection has been closed
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1593153790545 (09:43:10 GMT+0300 (Eastern European Summer Time))
[debug] [W3C] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70
[debug] [W3C] xcodebuild error message:
[debug] [W3C] 
[debug] [W3C] Command line invocation:
[debug] [W3C]     /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath /Users/**/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu -destination id=** IPHONEOS_DEPLOYMENT_TARGET=13.15 -xcconfig /var/folders/0v/wcg3q99x0zd4g8rbzr_7gwgw00r2xh/T/2020526-50359-187f62h.54o3/appium-temp.xcconfig GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO
[debug] [W3C] User defaults from command line:
[debug] [W3C]     IDEDerivedDataPathOverride = /Users/**/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu
[debug] [W3C] Build settings from command line:
[debug] [W3C]     COMPILER_INDEX_STORE_ENABLE = NO
[debug] [W3C]     GCC_TREAT_WARNINGS_AS_ERRORS = 0
[debug] [W3C]     IPHONEOS_DEPLOYMENT_TARGET = 13.15
[debug] [W3C] Build settings from configuration file '/var/folders/0v/wcg3q99x0zd4g8rbzr_7gwgw00r2xh/T/2020526-50359-187f62h.54o3/appium-temp.xcconfig':
[debug] [W3C]     CODE_SIGN_IDENTITY = iPhone Developer
[debug] [W3C]     DEVELOPMENT_TEAM = **
[debug] [W3C] note: Using new build system
[debug] [W3C] note: Building targets in parallel
[debug] [W3C] note: Planning build
[debug] [W3C] note: Using build description from disk
[debug] [W3C] warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 13.15, but the range of supported deployment target versions is 8.0 to 13.5.99. (in target 'WebDriverAgentRunner' from project 'WebDriverAgent')
[debug] [W3C] warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 13.15, but the range of supported deployment target versions is 8.0 to 13.5.99. (in target 'WebDriverAgentLib' from project 'WebDriverAgent')
[debug] [W3C] ** TEST BUILD SUCCEEDED **
[debug] [W3C] xcodebuild: error: Failed to build project WebDriverAgent with scheme WebDriverAgentRunner.
[debug] [W3C] 	Reason: Cannot test target “WebDriverAgentRunner” on “**”: **’s iOS 13.5.1 doesn’t match WebDriverAgentRunner’s iOS 13.15 deployment target.. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[debug] [W3C]     at quitAndUninstall (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:528:15)
[debug] [W3C]     at /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:558:11
[debug] [W3C]     at wrapped (/usr/local/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:35:13)
[debug] [W3C]     at retry (/usr/local/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:18:13)
[debug] [W3C]     at retryInterval (/usr/local/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:45:10)
[debug] [W3C]     at /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:538:7
[debug] [W3C] Destroying socket connection
[HTTP] <-- POST /wd/hub/session 500 45178 ms - 5421
[HTTP]

**Comment by mykola-mokhnach** [comment]
This is the first time I see the platform version "13.15.1". Could you please link us to the corresponding Apple release notes?

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by ranchor** [comment]
https://support.apple.com/en-us/HT211214

**Comment by KazuCocoa** [comment]
It is 13.5.1, not 13.15.1.
This issue was about 13.15.1 as `"appium:platformVersion": "13.15.1"` (So, maybe typo?)
