### ISSUE TITLE
Could not find a connected Android device

### ISSUE THREAD

**Issue by ashokkumarg** [appium/appium#14480]
The Emulator is properly created with below inputs and it is properly listed with **adb devices** command

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): 12.4.1
* Npm: 6.13.4
* Mobile platform/version under test: Android 9 - System image - 28
* Real device or emulator/simulator: Emulator 
* Appium.app|exe:

## Emulator Information
Name: tablet
Device: 10.1in WXGA (Tablet) (Generic)
Path: C:\Users\Ashok Kumar\.android\avd\tablet.avd
Target: Google APIs (Google Inc.)
Based on: Android API 28 Tag/ABI: google_apis/x86_64

![image](https://user-images.githubusercontent.com/7566850/85526595-c6973700-b627-11ea-8906-f80ebc90323e.png)

**adb devices**

![image](https://user-images.githubusercontent.com/7566850/85515726-115e8200-b61b-11ea-9ef7-218303cd50ef.png)

**Appium Code**

```
	public static void spirit() throws MalformedURLException {
		DesiredCapabilities caps = new DesiredCapabilities();
		System.out.println("Start");
		caps.setCapability("deviceName", "tablet");
		caps.setCapability("udid", "emulator-5554");
		caps.setCapability("platformName", "Android");
		caps.setCapability("platformVersion", "9");
		caps.setCapability("appPackage", "com.google.android.apps.nexuslauncher");
		caps.setCapability("appActivity", "com.google.android.apps.nexuslauncher.NexusLauncherActivity");
		URL url = new URL("http://0.0.0.0:4723/wd/hub");
		appiumDriver = new AppiumDriver<MobileElement>(url,caps);
		System.out.println("Application Launched");
	}
```

**Eclipse Console:**

> Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 21272ms.
> Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
> System info: host: 'ASHOK', ip: '192.168.1.4', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
> Driver info: driver.version: AppiumDriver
> remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 21272ms.
>     at getResponseForW3CError (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
>     at asyncHandler (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:392:37)
> Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
> System info: host: 'ASHOK', ip: '192.168.1.4', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
> Driver info: driver.version: AppiumDriver

**Appium Console:**

> 
> [Appium] Welcome to Appium v1.17.1
> [Appium] Non-default server args:
> [Appium]   allowInsecure: {
> [Appium]   }
> [Appium]   denyInsecure: {
> [Appium]   }
> [Appium] Appium REST http interface listener started on 0.0.0.0:4723
> [HTTP] --> POST /wd/hub/session
> [HTTP] {"desiredCapabilities":{"appActivity":"com.android.calculator2.Calculator","appPackage":"com.android.calculator2","platformVersion":"9","platformName":"Android","udid":"emulator-5554","deviceName":"tablet"},"capabilities":{"firstMatch":[{"appium:appActivity":"com.android.calculator2.Calculator","appium:appPackage":"com.android.calculator2","appium:deviceName":"tablet","platformName":"android","appium:platformVersion":"9","appium:udid":"emulator-5554"}]}}
> [W3C] Calling AppiumDriver.createSession() with args: [{"appActivity":"com.android.calculator2.Calculator","appPackage":"com.android.calculator2","platformVersion":"9","platformName":"Android","udid":"emulator-5554","deviceName":"tablet"},null,{"firstMatch":[{"appium:appActivity":"com.android.calculator2.Calculator","appium:appPackage":"com.android.calculator2","appium:deviceName":"tablet","platformName":"android","appium:platformVersion":"9","appium:udid":"emulator-5554"}]}]
> [BaseDriver] Event 'newSessionRequested' logged at 1592989219712 (14:30:19 GMT+0530 (India Standard Time))
> [Appium] 
> [Appium] ======================================================================
> [Appium]   DEPRECATION WARNING:
> [Appium] 
> [Appium]   The 'automationName' capability was not provided in the desired 
> [Appium]   capabilities for this Android session
> [Appium] 
> [Appium]   Setting 'automationName=UiAutomator2' by default and using the 
> [Appium]   UiAutomator2 Driver
> [Appium] 
> [Appium]   The next major version of Appium (2.x) will **require** the 
> [Appium]   'automationName' capability to be set for all sessions on all 
> [Appium]   platforms
> [Appium] 
> [Appium]   In previous versions (Appium <= 1.13.x), the default was 
> [Appium]   'automationName=UiAutomator1'
> [Appium] 
> [Appium]   If you wish to use that automation instead of UiAutomator2, please 
> [Appium]   add 'automationName=UiAutomator1' to your desired capabilities
> [Appium] 
> [Appium]   For more information about drivers, please visit 
> [Appium]   http://appium.io/docs/en/about-appium/intro/ and explore the 
> [Appium]   'Drivers' menu
> [Appium] 
> [Appium] ======================================================================
> [Appium] 
> [Appium] Appium v1.17.1 creating new AndroidUiautomator2Driver (v1.44.2) session
> [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
> [BaseDriver] Creating session with W3C capabilities: {
> [BaseDriver]   "alwaysMatch": {
> [BaseDriver]     "platformName": "android",
> [BaseDriver]     "appium:appActivity": "com.android.calculator2.Calculator",
> [BaseDriver]     "appium:appPackage": "com.android.calculator2",
> [BaseDriver]     "appium:deviceName": "tablet",
> [BaseDriver]     "appium:platformVersion": "9",
> [BaseDriver]     "appium:udid": "emulator-5554"
> [BaseDriver]   },
> [BaseDriver]   "firstMatch": [
> [BaseDriver]     {}
> [BaseDriver]   ]
> [BaseDriver] }
> [BaseDriver] Session created with session id: 242f49d2-f8fc-475a-8e07-d991cf26a908
> [UiAutomator2] Starting 'com.android.calculator2' directly on the device
> [ADB] Found 1 'build-tools' folders under 'C:\Users\Ashok Kumar\Downloads\android-sdk' (newest first):
> [ADB]     C:/Users/Ashok Kumar/Downloads/android-sdk/build-tools/28.0.0
> [ADB] Using 'adb.exe' from 'C:\Users\Ashok Kumar\Downloads\android-sdk\platform-tools\adb.exe'
> [AndroidDriver] Retrieving device list
> [ADB] Trying to find a connected android device
> [ADB] Getting connected devices...
> [ADB] No connected devices have been detected
> [ADB] Could not find devices, restarting adb server...
> [ADB] Restarting adb
> [ADB] Killing adb server on port '5037'
> [ADB] Running 'C:\Users\Ashok Kumar\Downloads\android-sdk\platform-tools\adb.exe -P 5037 kill-server'
> [ADB] Getting connected devices...
> [ADB] No connected devices have been detected
> [ADB] Could not find devices, restarting adb server...
> [ADB] Restarting adb
> [ADB] Killing adb server on port '5037'
> [ADB] Running 'C:\Users\Ashok Kumar\Downloads\android-sdk\platform-tools\adb.exe -P 5037 kill-server'
> [ADB] Getting connected devices...
> [ADB] No connected devices have been detected
> [ADB] Could not find devices, restarting adb server...
> [ADB] Restarting adb
> [ADB] Killing adb server on port '5037'
> [ADB] Running 'C:\Users\Ashok Kumar\Downloads\android-sdk\platform-tools\adb.exe -P 5037 kill-server'
> [ADB] Getting connected devices...
> [ADB] No connected devices have been detected
> [ADB] Could not find devices, restarting adb server...
> [ADB] Restarting adb
> [ADB] Killing adb server on port '5037'
> [ADB] Running 'C:\Users\Ashok Kumar\Downloads\android-sdk\platform-tools\adb.exe -P 5037 kill-server'
> [ADB] Getting connected devices...
> [ADB] No connected devices have been detected
> [ADB] Could not find devices, restarting adb server...
> [ADB] Restarting adb
> [ADB] Killing adb server on port '5037'
> [ADB] Running 'C:\Users\Ashok Kumar\Downloads\android-sdk\platform-tools\adb.exe -P 5037 kill-server'
> [ADB] Getting connected devices...
> [ADB] No connected devices have been detected
> [ADB] Could not find devices, restarting adb server...
> [ADB] Restarting adb
> [ADB] Killing adb server on port '5037'
> [ADB] Running 'C:\Users\Ashok Kumar\Downloads\android-sdk\platform-tools\adb.exe -P 5037 kill-server'
> [ADB] Getting connected devices...
> [ADB] No connected devices have been detected
> [ADB] Could not find devices, restarting adb server...
> [ADB] Restarting adb
> [ADB] Killing adb server on port '5037'
> [ADB] Running 'C:\Users\Ashok Kumar\Downloads\android-sdk\platform-tools\adb.exe -P 5037 kill-server'
> [ADB] Getting connected devices...
> [ADB] No connected devices have been detected
> [ADB] Could not find devices, restarting adb server...
> [ADB] Restarting adb
> [ADB] Killing adb server on port '5037'
> [ADB] Running 'C:\Users\Ashok Kumar\Downloads\android-sdk\platform-tools\adb.exe -P 5037 kill-server'
> [ADB] Getting connected devices...
> [ADB] No connected devices have been detected
> [ADB] Could not find devices, restarting adb server...
> [ADB] Restarting adb
> [ADB] Killing adb server on port '5037'
> [ADB] Running 'C:\Users\Ashok Kumar\Downloads\android-sdk\platform-tools\adb.exe -P 5037 kill-server'
> [ADB] Getting connected devices...
> [ADB] No connected devices have been detected
> [ADB] Could not find devices, restarting adb server...
> [ADB] Restarting adb
> [ADB] Killing adb server on port '5037'
> [ADB] Running 'C:\Users\Ashok Kumar\Downloads\android-sdk\platform-tools\adb.exe -P 5037 kill-server'
> [UiAutomator2] Deleting UiAutomator2 session
> [BaseDriver] Event 'newSessionStarted' logged at 1592989242608 (14:30:42 GMT+0530 (India Standard Time))
> [W3C] Encountered internal error running command: Error: Could not find a connected Android device in 21207ms.
> [W3C]     at getDevices (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:211:13)
> [W3C]     at getDevices (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:224:18)
> [W3C]     at getDevices (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:224:12)
> [W3C]     at getDevices (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:224:12)
> [W3C]     at getDevices (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:224:12)
> [W3C]     at getDevices (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:224:12)
> [W3C]     at getDevices (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:224:12)
> [W3C]     at getDevices (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:224:12)
> [W3C]     at getDevices (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:224:12)
> [W3C]     at getDevices (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:224:12)
> [W3C]     at getDevices (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:224:12)
> [W3C]     at ADB.getDevicesWithRetry (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:226:10)
> [W3C]     at Object.getDeviceInfoFromCaps (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-android-driver\lib\android-helpers.js:180:19)
> [W3C]     at AndroidUiautomator2Driver.startUiAutomator2Session (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:290:26)
> [W3C]     at AndroidUiautomator2Driver.createSession (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:212:7)
> [W3C]     at AppiumDriver.createSession (C:\Program Files\Appium\resources\app\node_modules\appium\lib\appium.js:358:35)
> [W3C] Destroying socket connection
> [HTTP] <-- POST /wd/hub/session 500 22985 ms - 671

**Comment by mykola-mokhnach** [comment]
Please provide the full server log

**Comment by ashokkumarg** [comment]
@mykola-mokhnach  I have updated the full server log by editing the question

**Comment by mykola-mokhnach** [comment]
I don't observe any issues in the log. adb simply does not return any devices when called by the server. This could also be an environment issue

**Comment by ashokkumarg** [comment]
The device is identified in the command prompt and not on the appium server. Environment issue means Windows 10?

**Comment by mykola-mokhnach** [comment]
> Environment issue means Windows 10?

This means the environment of the appium server process might be different from the system cmd env

**Comment by ashokkumarg** [comment]
Any way to fix this?

**Comment by ashokkumarg** [comment]
Ahhh! I installed the appium now as global and it works now
`npm install appium -g`
Thank you
