### ISSUE TITLE
Unable to query XCUIElementTypePickerWheel items on appium 1.17.1

### ISSUE THREAD

**Issue by Invictum** [appium/appium#14486]
## The problem

There is a simple iOS application with following page sources
```
<?xml version="1.0" encoding="UTF-8"?><AppiumAUT><XCUIElementTypeApplication type="XCUIElementTypeApplication" name="ui-polygone" label="ui-polygone" enabled="true" visible="true" x="0" y="0" width="375" height="667">
  <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" visible="true" x="0" y="0" width="375" height="667">
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="375" height="667">
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="375" height="667">
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="375" height="667">
          <XCUIElementTypePicker type="XCUIElementTypePicker" enabled="true" visible="true" x="28" y="367" width="320" height="162">
            <XCUIElementTypePickerWheel type="XCUIElementTypePickerWheel" value="One" enabled="true" visible="true" x="28" y="329" width="320" height="238">
              <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="0" height="0"/>
              <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="0" height="0"/>
              <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="0" height="0"/>
              <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="0" height="0"/>
              <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="0" height="0"/>
            </XCUIElementTypePickerWheel>
          </XCUIElementTypePicker>
        </XCUIElementTypeOther>
      </XCUIElementTypeOther>
    </XCUIElementTypeOther>
  </XCUIElementTypeWindow>
  <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" visible="false" x="0" y="0" width="375" height="667">
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="375" height="667">
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="375" height="667"/>
    </XCUIElementTypeOther>
  </XCUIElementTypeWindow>
</XCUIElementTypeApplication></AppiumAUT>
```

I'm trying to query items under `XCUIElementTypePickerWheel` with iOS chain query `**/XCUIElementTypePickerWheel/XCUIElementTypeOther` and expecting to receive a list of 5 items, but empty list is returned instead.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1
* Last Appium version that did not exhibit the issue (if applicable): 1.17.0
* Desktop OS/version used to run Appium: Mac OS 10.15.4
* Node.js version (unless using Appium.app|exe): v14.4.0
* Npm or Yarn package manager: NPM 6.14.5
* Mobile platform/version under test: iOS 13.2
* Real device or emulator/simulator:  iPhone 7 Simulator
* Appium CLI or Appium.app|exe: N/A

## Details

Issue is reproduced only with appium 1.17.1, but page source looks the same for both 1.17.0 and 1.17.1

## Link to Appium logs

1.17.1 - https://gist.github.com/Invictum/2a3539f3889999047954a381aafcb410
1.17.0 - https://gist.github.com/Invictum/ebe4c396e8b4721294fbb3e88087cc34

**Comment by mykola-mokhnach** [comment]
I don't think there's anything we could do without having the actual app to test with. You could try to write a simple native XCTest and check what the selector would return there

**Comment by Invictum** [comment]
@mykola-mokhnach 
I'm not really experienced with XCTest, but I can attach synthetic app I've made to reproduce this issue.

**Comment by mykola-mokhnach** [comment]
Thanks @Invictum 

This is really helpful

**Comment by mykola-mokhnach** [comment]
I did some testing on the app above and it looks like XCTest fails to bind these `Other` elements after they were found. I've created https://github.com/appium/WebDriverAgent/pull/357

Apply this patch to your local WDA sources and set the `boundElementsByIndex` [setting](http://appium.io/docs/en/advanced-concepts/settings/) to `true` before performing the lookup of the target elements. Also make sure WDA gets rebuilt properly (`useNewWDA` capability could be used to ensure that).

**Comment by Invictum** [comment]
@mykola-mokhnach 
Thanks for the fast response and fix

**Comment by mykola-mokhnach** [comment]
Have you verified the patch?

**Comment by Invictum** [comment]
Yes, it works as expected - all items were found.

**Comment by mykola-mokhnach** [comment]
the patch has been published to appium@beta
