### ISSUE TITLE
Siri Opening on driver.get(url) on iOS Safari Real Device

### ISSUE THREAD

**Issue by ankitgupta9289** [appium/appium#14497]
Siri Opening on driver.get(URL) on iOS Safari Real Device ?? How to open SAFARI browser and open our mobile site URL to automate?

![image](https://user-images.githubusercontent.com/52029195/86019266-03a66380-ba44-11ea-858b-eaaa9b1d65ed.png)

**Comment by mykola-mokhnach** [comment]
This is expected. The openUrl API does not work in xctest and this is a known bug, which apple simply ignores. As a workaround we try to pass the url to Siri, which does not always work.

Closed as not an issue.

**Comment by heychirag** [comment]
I am trying to open a Deeplink in an app and Siri is opening up. Is there a workaround for Native apps?
