### ISSUE TITLE
iOS: Driver meets "[WD Proxy] socket hang up" problem while starting multiple instances

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#14495]
## The problem

Driver start meets with "[WD Proxy] socket hang up" more and more times

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.18.0-beta.0
* Desktop OS/version used to run Appium: MacOS
* Mobile platform/version under test: iOS 13.5.1
* Real device or emulator/simulator: Real Devices

## Details

We have multiple appium instances and iphone devices. Driver start meet more and more often mentioned problem. After some time 5-10min appium driver finally starting with subsequent retry. Any ideas for fix? 

## Link to Appium logs

Logs of two different appium servers attached. With re-start we trying to change WDA port (actually this does not help much)
https://gist.github.com/amedvedjev/a94a2c7686f2d8cc034ce6b236e90d88

**Comment by amedvedjev** [comment]
**update:** if i synchronize that ONLY ONE driver starts at the same time = no problems.

**Comment by KazuCocoa** [comment]
`derivedDataPath` may help, I guess. You can specify different path for each device.
https://github.com/appium/appium-xcuitest-driver

The cause was xcodebuild referred the same driverdData in parallel, but they had an issue to handle properly.

**Comment by amedvedjev** [comment]
@KazuCocoa @mykola-mokhnach thanks! but no luck. just same happens.
what i did:
 1) before all tests i copy derivedData folder "WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu" to local "target/wda/iphoneX" where "X" is some number from 1 to 9.
```
[16:41:32.401] [main]     AppiumManager:              |  makeDerivedDataPaths(): deviceName: 'iphone8_1' path: '/Users/qa/Documents/jenkins-work/workspace/iOS/target/wda/iphone8_1' 
[16:41:35.244] [main]     AppiumManager:              |  makeDerivedDataPaths(): deviceName: 'iphone8_2' path: '/Users/qa/Documents/jenkins-work/workspace/iOS/target/wda/iphone8_2' 
...
```
2) during driver start I set "derivedDataPath" to this folder. different with each device.
```
[16:41:51.853] [resetClient]     AppiumDriverFactory:        |  configureLocalAppium(): derivedDataPath: '/Users/qa/Documents/jenkins-work/workspace/iOS/target/wda/iphone8_1' 
[16:41:51.943] [resetClient]     AppiumDriverFactory:        |  configureLocalAppium(): derivedDataPath: '/Users/qa/Documents/jenkins-work/workspace/iOS/target/wda/iphone8_2' 
...
```

Result: just same log -> https://gist.github.com/amedvedjev/a109c58f6881f0b4bcb541b4b81a9ea2

**Comment by mykola-mokhnach** [comment]
Please attach the log with Xcodebuild looging enabled

**Comment by amedvedjev** [comment]
@mykola-mokhnach you mean enable "showXcodeLog" ?

**Comment by KazuCocoa** [comment]
Yes, we should track each xcodebuild process

**Comment by amedvedjev** [comment]
is it something different from build wda app? cause i use:
```
capabilities.setCapability(IOSMobileCapabilityType.USE_PREBUILT_WDA, true);
```

**Comment by KazuCocoa** [comment]
prebuild capability expects the `derivedDataPath` already has the built modules. So, perhaps you should run once without the prebuilt capability to complete building modules.

**Comment by amedvedjev** [comment]
Original folder "WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu"  already has build and used before multiple times to start driver. Logs with xcode soon...

**Comment by amedvedjev** [comment]
ok https://gist.github.com/amedvedjev/99aed22b7ba60b19b17237591e22dda0

first file log - NO custom derivedDataPath
second file log - custom derivedDataPath of copied "WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu"

**Comment by mykola-mokhnach** [comment]
I assume the problem here lies in `usePrebuiltWDA: true` capability. The WDA app does not get built properly for a newly set derived data folder and then fails with code 65:

> 2020-06-30 08:52:22:023 [Xcode] 2020-06-30 11:52:22.022 xcodebuild[49440:2084651]  iPhoneConnect: 📱<DVTiOSDevice (0x7fc660fe1910), iPhone QA1, iPhone, 13.5.1 (17F80), device_1> failed to install /Users/qa/Documents/jenkins-work/workspace/iOS_Nightly_jobs/iOS_AnyTier/target/wda/iphone8_1/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app - error Error Domain=com.apple.platform.iphoneos Code=-1 "Unable to install “WebDriverAgentRunner-Runner”" UserInfo={NSLocalizedDescription=Unable to install “WebDriverAgentRunner-Runner”, NSLocalizedRecoverySuggestion=WebDriverAgentRunner-Runner.app does not contain a valid Info.plist, so it cannot be installed on iPhone QA1

**Comment by amedvedjev** [comment]
@mykola-mokhnach you was right!
trying to fix/manage this with our project cause more problems comparing with benefits:

**PLUS:**
1) synchro driver start cause save time of run

**MINUS:**
1) first driver start increases from 35sec to more than 1min (+ build time)
2) need to manage every automation QA to make first start with building derived_data for each device under test
3) time benefit from PLUS not much as far as later drivers start randomly (depends on test length) and in most time start lock does not affect (current driver start time we have - 3 sec and 35 sec first time with reinstall). so we are losing only 35*(number_of_devices - 1) - build_time*number_of_devices

closing....
