### ISSUE TITLE
[Android Mobile] Unable to find elements in android.webkit.WebView component

### ISSUE THREAD

**Issue by BoazWarshawsky** [appium/appium#14499]
## The problem
I am running testings on a React Native application.
Inside that app I have a WebView component, I am trying find a certain element inside this WebView but with no success. 
The Appium API I tried using are:

- `find_element_by_xpath`
- `find_element_by_id`
- `find_elements_by_class_name`
- `find_element_by_accessibility_id`

The elements inspector does showing me correctly the element:
<img width="643" alt="Screen Shot 2020-06-30 at 8 32 40" src="https://user-images.githubusercontent.com/32813176/86087206-4b60d580-baac-11ea-8dc6-a4e0a369fa2b.png">

The element view in the app found in the following image, at the bottom: 
<img width="319" alt="Screen Shot 2020-06-30 at 8 43 53" src="https://user-images.githubusercontent.com/32813176/86087966-105fa180-baae-11ea-9ba3-c5fd7c8415ec.png">

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0 and 1.17.1
* Last Appium version that did not exhibit the issue (if applicable):None
* Desktop OS/version used to run Appium:CLI
* Node.js version (unless using Appium.app|exe):12.16.0
* Npm or Yarn package manager:npm
* Mobile platform/version under test: Android
* Real device or emulator/simulator:Emulator
* Appium CLI or Appium.app|exe:CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
https://assets-production.applicaster.com/qa/zapp_qa/manual/boaz/html_appium.log

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by BoazWarshawsky** [comment]
@mykola-mokhnach can you please help me with that issue?

**Comment by KazuCocoa** [comment]
> find_element_by_xpath
find_element_by_id
find_elements_by_class_name
find_element_by_accessibility_id

Could you share the server log when you tried the above methods and the page source as GIST?

**Comment by BoazWarshawsky** [comment]
sorry, what do you mean by saying "the page source as GIST"?

**Comment by KazuCocoa** [comment]
https://appium.io/docs/en/commands/session/source/ and https://gist.github.com/

**Comment by BoazWarshawsky** [comment]
@KazuCocoa I uploaded the logs to some server, if that is ok too:

Page source XML: https://assets-production.applicaster.com/qa/zapp_qa/manual/boaz/page_source.xml
Appium server log: https://assets-production.applicaster.com/qa/zapp_qa/manual/boaz/appium_server_with_page_source.log

Thanks

**Comment by KazuCocoa** [comment]
How about `find_element_by_id 'title_1_id'`?
You probably tried to find elements by the elementId as accessibility id.

```
<android.webkit.WebView index="0" package="com.appfeatureapp" class="android.webkit.WebView" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[16,412][304,480]" displayed="true">
<android.webkit.WebView index="0" package="com.appfeatureapp" class="android.webkit.WebView" text="Automation Dummy HTML" checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="true" long-clickable="false" password="false" scrollable="true" selected="false" bounds="[16,412][304,480]" displayed="true">
<android.view.View index="0" package="com.appfeatureapp" class="android.view.View" text="title_1" resource-id="title_1_id" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[18,414][301,425]" displayed="true"/>
<android.view.View index="1" package="com.appfeatureapp" class="android.view.View" text="title_2" resource-id="title_2_id" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[18,431][301,443]" displayed="true"/>
<android.view.View index="2" package="com.appfeatureapp" class="android.view.View" text="title_3" resource-id="title_3_id" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[18,449][301,460]" displayed="true"/>
<android.view.View index="3" package="com.appfeatureapp" class="android.view.View" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[18,466][301,467]" displayed="true"/>
<android.view.View index="4" package="com.appfeatureapp" class="android.view.View" text="google" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[18,469][32,475]" displayed="true"/>
<android.view.View index="5" package="com.appfeatureapp" class="android.view.View" text="is a link to another nifty site" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[32,469][91,475]" displayed="true"/>
<android.view.View index="6" package="com.appfeatureapp" class="android.view.View" text="This is a new paragraph!" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[18,479][301,480]" displayed="true"/>
</android.webkit.WebView>
</android.webkit.WebView>
```

**Comment by BoazWarshawsky** [comment]
@KazuCocoa it did not solve the problem, just tried again.


What did work for me is doing that:
```
views = self.driver_.find_elements_by_class_name('android.view.View')
                for view in views:
                    if view.text == text:
                        return view
```
But I am not sure its the best practice, 
our issue here is that the element that I am trying to access is inside a `android.webkit.WebView`, and **all** the find element method not working in that case. 


I think we should keep this ticket. the issue still exits. my suggestion is just a workaround.

**Comment by KazuCocoa** [comment]
I don't think Appium can do much take care of them for now since the root depends on how Android framework handles WebView components. So, potentially your workaround could be the only current solution until Google modify the logic.
(Or React Native side??)

https://github.com/appium/appium-uiautomator2-server/blob/c0d2d45740a2f9d05cf0e6c3b7b1a19e2f85d1b1/app/src/main/java/io/appium/uiautomator2/handler/FindElement.java#L88-L112

https://github.com/appium/appium-uiautomator2-server/blob/c0d2d45740a2f9d05cf0e6c3b7b1a19e2f85d1b1/app/src/main/java/io/appium/uiautomator2/model/internal/CustomUiDevice.java#L52

```
import androidx.test.uiautomator.By;
import androidx.test.uiautomator.BySelector;
import androidx.test.uiautomator.UiDevice;
import androidx.test.uiautomator.UiObject;
import androidx.test.uiautomator.UiObject2;
import androidx.test.uiautomator.UiSelector;
```

Potentially, espresso driver handles them better than uiautomator.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
