### ISSUE TITLE
Can't Enter URL on Safari on Real Device

### ISSUE THREAD

**Issue by seagunz** [appium/appium#14493]
## The problem

I’m trying to input URL on Safari on real iPhone device but got this error
`InvalidElementStateException: Message: Error Domain=com.facebook.WebDriverAgent Code=1 "The on-screen keyboard must be present to send keys" UserInfo={NSLocalizedDescription=The on-screen keyboard must be present to send keys}`

## Environment

* Appium version :1.17.1-1
* Desktop OS used to run Appium: macOS 10.14.6
* Mobile platform/version under test:iPhone 7 13.3
* Real device or emulator/simulator: Real device

## Link to Appium logs
https://gist.github.com/seagunz/2d304de70d20a93a6f1d5bde17dee1c5

## Detail
1.I don't have any third party keyboard installed.

2.I don't want to use browserName=Safari because I want to click Safari Tab and other stuff on app.

3.Input problem only happen on Safari.

## Code To Reproduce Issue [ Good To Have ]
```
**** Settings ****
Library    Selenium2Library
Library    Collections
Library    requests
Library    AppiumLibrary

**** Test Cases ****
Test_case_sample
    Open application    http://127.0.0.1:4723/wd/hub    alias=Phone    platformName=iOS    platformVersion=13.3    deviceName=iPhone    bundleId=com.apple.mobilesafari
    ...    udid=**********************    nativeWebTap=true    automationName=XCUITest    noReset=false    wdaLocalPort=8145    useNewWDA=true
    AppiumLibrary.Input Text    xpath=//XCUIElementTypeButton[@name="URL"]    https://www.google.com/
    Hide Keyboard    Go
```

**Comment by mykola-mokhnach** [comment]
XCTest is unable to input test if the keyboard is not shown. I don't think there is anything we could do from Appium side

**Comment by seagunz** [comment]
The keyboard has shown, but it doesn't type anything and got error.

The problem only happen on Safari, other apps work fine.

**Comment by mykola-mokhnach** [comment]
You could try appium@beta. It had some changes in the send keys handler. Otherwise I don't have any other good ideas

**Comment by seagunz** [comment]
Thank you, I managed to fix it by change xpath to accessibility_id
