### ISSUE TITLE
An unknown server-side error occurred while processing the command, during screenshot on iOS

### ISSUE THREAD

**Issue by LukaszTutur** [appium/appium#14498]
## The problem

Getting:
`>       raise exception_class(message, screen, stacktrace)
E       selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100

/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py:242: WebDriverException
`

When trying to get a device screenshot.

The script without screenshot is working, it is also working with video_recording, it fails ONLY while I try to make a screenshot (both save_screenshot() and get_screenshot_as_base64()) (Please check attached code for more information)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: macOS Catalina 10.15.5
* Node.js version (unless using Appium.app|exe): v14.4.0 (also tried on 12, and 8)
* Npm or Yarn package manager: 6.14.4
* Mobile platform/version under test: 13.5.1 (XCode code 11.5 Build version 11E608c, also tried with 11.1)
* Real device or emulator/simulator: RealDevice
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

cli output in attached file
[cli.log](https://github.com/appium/appium/files/4848221/cli.log)

## Code To Reproduce Issue [ Good To Have ] (Python, tested with Python2 appium python client client version 052, and python3 client vertsion 1.0.1)

`
import unittest
from appium import webdriver
from selenium.webdriver.common.keys import Keys
import logging
import time
import base64
logging.basicConfig(filename="log.txt", level=logging.INFO)

TIMEOUT=1
TIMEOUTPOST=2

class TestExamples(unittest.TestCase):
    #@classmethod
    def setUp(self):
        self.driver  = webdriver.Remote(
        command_executor="http://xxx.xxx.xxx.xxx:80/wd/hub",
        desired_capabilities={

            "browserName":"Safari",
            "platformName":"iOS",
            "platformVersion":"13.5.1",
            "deviceName":"iPhone",
            #"automationName": "XCUITest",
            #"safariInitialUrl":"about:blank",
            #"noReset":True,
            "webDriverAgentUrl":"http://localhost:8100"
            
        })
        self.driver.implicitly_wait(40)
        #self.driver.reset()
            
    def test_one1(self):

        try:
           driver = self.driver
           #driver.start_recording_screen()
           time.sleep(TIMEOUT)
           driver.get("https://www.google.com")
           time.sleep(TIMEOUTPOST)
           #time.sleep(10)
           #video = driver.stop_recording_screen()
           #driver.save_screenshot("screenshot_ios_1.png")
           #screenshotBase64 = driver.get_screenshot_as_base64()

        finally:
            logging.info("Test: " + driver.session_id)
            #save video locally
            #with open("ios_video_test_one.mjp", "wb") as fh:
            #    fh.write(base64.b64decode(video))

    #@classmethod
    def tearDown(self):
        #self.driver.get("about:blank")
        #self.driver.delete_all_cookies()
        #self.driver.close()
        self.driver.quit()

if __name__ == "__main__":
    unittest.main()
`

**Comment by KazuCocoa** [comment]
Could you attach the appium server side log?

**Comment by mykola-mokhnach** [comment]
The device log would be useful as well

**Comment by LukaszTutur** [comment]
Yeah, took me some time to grab device log.

[appium.log](https://github.com/appium/appium/files/4853615/appium.log)
[device.log](https://github.com/appium/appium/files/4853617/device.log)

**Comment by mykola-mokhnach** [comment]
Unfortunately I cannot find any explicit issues in the logs. Have you tried to run the test on another device?

**Comment by LukaszTutur** [comment]
Ok, I was finally able to get my hands on second device, updated it to 13.5.1 and here are the logs from appium, and device.

[appium_2.log](https://github.com/appium/appium/files/4860348/appium_2.log)
[device_2.log](https://github.com/appium/appium/files/4860345/device_2.log)

Let me know if there are some other things, I can provide/check!

**Comment by mykola-mokhnach** [comment]
This looks like an internal issue of iOS itself. I don't have a real device to try, but everything works as expected on Simulator for me. Also, there's nothing interesting in logs

**Comment by KazuCocoa** [comment]
I was able to capture screen with safari browserName on https://www.google.com. The OS version was 13.5.1 and iPhone SE.
I tried out with Xcode 11.4.1 and 12 beta (with latest `appium@beta`).
https://gist.github.com/KazuCocoa/26b476339dd93cb909191557bec88c30

mm...

**Comment by LukaszTutur** [comment]
hmmmm, im using:
`
testuser$ xcodebuild -version
Xcode 11.5
Build version 11E608c
`
maybe this is the issue?
Will try the appium@beta as well.

**Comment by KazuCocoa** [comment]
Xcode 11.5 also worked on my local...
Please remove your `DerivedData` in `/Users/<user>/Library/Developer/Xcode/DerivedData` once to clear building stuff if you didn't customise derivedData

**Comment by LukaszTutur** [comment]
Clearing `DerivedData` did not help, still the same issue with appium@1.17.1

Also tried to npm install appium@beta but encountered `ENOENT: no such file or directory, chmod '/Users/testuser/node_modules/appium/node_modules/.bin/authorize-ios'` and none of the fixes from https://github.com/appium/appium/issues/6574 helped, Ill try to wipe my mac and start from scratch.

**Comment by mykola-mokhnach** [comment]
Unfortunately we cannot help nothing there.
Closed as third party issue
