### ISSUE TITLE
ms:waitForAppLaunch is not recognized by appium

### ISSUE THREAD

**Issue by krevathi1912** [appium/appium#14490]
## The problem

I am automating UWP app using appium+winappdriver. The app launch time is more, so i am using "ms:waitForAppLaunch" capability. Appium is not recognizing this capability and takes the capability as "waitForAppLaunch". Below is the code and log. I am using python language

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows OS
* Node.js version (unless using Appium.app|exe): v10.16.1
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: Windows UWP app
* Real device or emulator/simulator: Windows 10 Laptop
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

https://gist.github.com/krevathi1912/4f62f9042052e4f7cbd260b14c80ccc5

## Code To Reproduce Issue [ Good To Have ]

        desired_caps['platformName'] = "Windows"
        desired_caps['deviceName'] = "WindowsPC"
        desired_caps['app'] = "..................!App"
        desired_caps["ms:ms:waitForAppLaunch"] = 50
        self.driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)

**Comment by mykola-mokhnach** [comment]
This issue is that WAD only works in JWP mode, while prefixes are defined as a part of W3C spec. Everything is mixed around. You could add `appium:` prefix to the capability name as a workaround: `appium:ms:waitForAppLaunch`

**Comment by mykola-mokhnach** [comment]
I've also added a PR to avoid stripping third party prefixes from cap names: https://github.com/appium/appium/pull/14492, but it will only be present in the next Appium release

**Comment by krevathi1912** [comment]
@mykola-mokhnach  Thanks for the response. I have tried using the workaround appium:ms:waitForAppLaunch, still appium says ms:waitForAppLaunch as not recognized. Also the WinAppDriver did not wait for 50 secs after an app launch is initiated prior to attaching to the application session. Attached the log

https://gist.github.com/krevathi1912/4c56d992e774fa44acf028f2af870df5

**Comment by mykola-mokhnach** [comment]
Appium's job is to only send session capabilities. Everything else is up to WAD, which is maintained by Microsoft. Unfortunately, we cannot help anything more there

**Comment by krevathi1912** [comment]
ok, thank you very much for the response

**Comment by mykola-mokhnach** [comment]
> Where as when i run winappdriver seperately and start tests, the WAD is waiting 50 secs to attach the app session.

Are you also sure the version of WAD that you start in standalone mode is the same that is bundled with Appium?

**Comment by krevathi1912** [comment]
@mykola-mokhnach 
Yes, it's same WinAppDriver 1.2 RC

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
