### ISSUE TITLE
Test testID/accessibilityLabel can't be found when position is absolute

### ISSUE THREAD

**Issue by MichelBahl** [appium/appium#14491]
A testId can't be found when item containers position is absolute and item position itself is shifted by coordinate attributes like left or top. 

* Appium version 1.17.1
* MAC OS 10.15.4 
* Node.js 14:
* react-native-cli: 2.0.1
* react-native: 0.62.2
* emulator: Pixel_3_API_29

Here you can find a minimal expo sample -> [example](https://snack.expo.io/@m.bahl/appium-inaccesible-test-id)
Maybe this is related to -> [closed issue](https://github.com/appium/appium/issues/12064) 

[![Video Sample](https://img.youtube.com/vi/h4iPLlxYaBA/0.jpg)](https://www.youtube.com/watch?v=h4iPLlxYaBA&feature=youtu.be)

**Comment by mykola-mokhnach** [comment]
How this is different from the closed issue?  It's up to react and the app under test to expose its views to accessibility manager. Consider switching to web view context.

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by MichelBahl** [comment]
What do you mean by switching to web view context ?

As far as I can see, the test id's are exposed -> 
<img width="1157" alt="uiautomator" src="https://user-images.githubusercontent.com/11231563/86611237-ae6fd200-bfae-11ea-848e-a80544eacde5.png">

**Comment by mykola-mokhnach** [comment]
I mean http://appium.io/docs/en/writing-running-appium/web/hybrid/

**Comment by nuvolarmobileteam** [comment]
We are having the exact same issue in our project. When the style of an element is position:absolute Appium can not find the element. Any news?

**Comment by uniquejava** [comment]
I got to know that: 

> Avoid position=”absolute” for container's views
> 
> There is a problem that appium doesn’t see elements inside absolutely positioned views. So you can’t interact with. [Learn more](http://www.wswebcreation.nl/clicking-on-an-element-with-appium-that-cant-be-found-in-the-ui-tree/).
> 

So I think this might be a bug?  @mykola-mokhnach , I am using react native.


And the tip is from here: https://petrlz63.medium.com/appium-tips-for-react-native-apps-d869d68921db

**Comment by alexhernandez** [comment]
Was there a fix for this? Latest version still seems to have this issue

**Comment by Hanuman-Ghawade** [comment]
I am also facing same issue.

**Comment by alexhernandez** [comment]
I found a workaround. 

If you have elements that are not visible to Appium add both a `testId` and `accessibilityLabel` and this should help resolve the issue.
