### ISSUE TITLE
how to perform touchAction using Selenium-webdriver on mobile apps

### ISSUE THREAD

**Issue by JSRMOHIT** [appium/appium#14503]
## The problem
touchAction is not working in code 

## Environment
* Appium:1.17.1
* Node.js version v13.8.0
* Npm 
* Mobile platform/version under test: Android 9
* Real device 
I used the phonepe payment app

## Details
How to use  TouchAction in javascript in selenium -webdriver
which npm module to include in package.json and which one to import in javscript code so that 
TouchAction works fine

 "use strict";

var wd = require("selenium-webdriver"),
    By = wd.By,
    until = wd.until;
var desiredCaps =
{
    platformName: "Android",
    platformversion: "9",
    devicename: "xxxxxxx",
    automationName: "UiAutomator2",
    noReset:"true",
    appPackage:"com.sec.android.app.launcher",
    appActivity:"com.sec.android.app.launcher.activities.LauncherActivity",
    browserName: '',
    
};
async function phonepe()
{ 
let driver = await new wd.Builder().usingServer("http://127.0.0.1:4723/wd/hub").withCapabilities(desiredCaps).build();
driver.touchAction([
    { action: 'press', x: 404, y: 658 },
    { action: 'moveTo', x: 404, y: 50 },
    'release'
])
driver.touchPerform([ { action: 'press', options: { x: 100, y: 250 }}, { action: 'moveTo', options: { x: 300, y: 100 }}, { action: 'release' } ]);

await driver.close();
}
phonepe();

errors logs----------------------------------------

(node:40512) UnhandledPromiseRejectionWarning: TypeError: driver.touchAction is not a function
    at phonepe (c:\Users\Mohit\Desktop\new\touchActions.js:24:8)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by mykola-mokhnach** [comment]
Kindly use Appium Forum to ask questions.
