### ISSUE TITLE
Does Automotive device supported in Appium

### ISSUE THREAD

**Issue by Wahed45** [appium/appium#14502]
## Automotive Support in Appium

Does Appium support Automotive devices for automating?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager: NPM 6.13.4
* Mobile platform/version under test:
* Real device or emulator/simulator: Automotive Emulator based on Android P & Q version
* Appium CLI or Appium.app|exe:

Regards,
Wahed

**Comment by mykola-mokhnach** [comment]
Appium has multiple drivers from different platforms, for example Android, iOS, Windows, MacOS, Tizen, tvOS. If your automotive device is built on top of one of the supported platforms then it is probably supported.

Please use Appium Forum to ask questions
