### ISSUE TITLE
WPF and Chrome | Inside a Windows Desktop application

### ISSUE THREAD

**Issue by jjbright** [appium/appium#14506]
## The problem

I've a desktop application that contains some windows controls and inbuilt browser [Chrome] that renders the html content. The user interaction will start by launching the application and firt few clicks in the windows controls[WPF] and the following actions/clicks to happen in the browser control.

I'm facing issues during automation as the windows control automation works well, but unable to smoothly move with the following user actions in the browser control.  Many controls are not getting detected correctly by inspect.exe.

## Environment

* OS : Windows 10
* Language : Python 3.7 64bit

## Details

Can this problem be solved using Appium?
If yes, how to do that?

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing that could be done here from Appium side. Native controls location is performed by Windows Driver, which is maintained by Microsoft. 

Regarding Electron - consider connecting to its remote debugger. This way it would be possible to automate its content as a normal web page using chromedriver. And the native stuff could still be controlled with Windows driver.

**Comment by mykola-mokhnach** [comment]
Kindly use Appium forum for howto questions
