### ISSUE TITLE
how to skip the setting,server,server_test installation during init the driver

### ISSUE THREAD

**Issue by KevinChan168** [appium/appium#14507]
## The problem

I encounter the problem that using appium on vivo and oppo android phone, when using 'adb install xxx.apk', there will be a popup dialog require to input the password of account registerd on the device in order to proceed installation,  this blocks the installation of appium setting, server and server.test and causes the installation command timeout

Is there a way to skip these 3 install during init driver?
Manually download the latest apks or using the existing apks in appium file path and install should work?
please kindly help, thanks in advance

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1
* Last Appium version that did not exhibit the issue (if applicable): no
* Desktop OS/version used to run Appium: windows10

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/usr/bin/adb -P 5037 -s 1d2a9531 shell pm install -r /data/local/tmp/appium_cache/0cc1725a60a05dbb5d0d09256f2fc6ece7e3b10f.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'uiautomator2ServerInstallTimeout' capability

**Comment by mykola-mokhnach** [comment]
uiautomator2 has `skipServerInstallation` capability being set to true skips server and server-test installation. Appium Settings does not get reinstalled if it is already there and is up to date.

Consider using a device from another manufacturer for automated testing.

Kindly use Appium forum for questions.

**Comment by KevinChan168** [comment]
> uiautomator2 has `skipServerInstallation` capability being set to true skips server and server-test installation. Appium Settings does not get reinstalled if it is already there and is up to date.
> 
> Consider using a device from another manufacturer for automated testing.
> 
> Kindly use Appium forum for questions.

where to find the latest apk of server and server-test ?
