### ISSUE TITLE
Appium server is freezing when find an nonexistent element

### ISSUE THREAD

**Issue by dlc9113** [appium/appium#14508]
## The problem

Enter a new page, find an nonexistent element, then appium server is freezing.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS Catalina 10.15.5
* Node.js version (unless using Appium.app|exe): v10.21.0
* Npm or Yarn package manager:
* Mobile platform/version under test: iOS 13.5
* Real device or emulator/simulator: Simulator (Real device also have similar issue)
* Appium CLI or Appium.app|exe: CLI

## Details

1. Tap a "Profile" button, then go to a new page successfully, refer [appium.txt:L354](https://gist.github.com/dlc9113/052533221021e48823977a7c009c0f9d#file-appium-txt-L354)
2. Assert an element is not found, find this element by _{"using":"-ios predicate string","value":"label == \"Sign Up for More Features\""}_, refer [appium.txt:L376](https://gist.github.com/dlc9113/052533221021e48823977a7c009c0f9d#file-appium-txt-L376)
3. Then next lookups are all failed, and every lookup takes 30 seconds which is _wdaConnectionTimeout_. 

## Link to Appium logs

https://gist.github.com/dlc9113/052533221021e48823977a7c009c0f9d

**Comment by dlc9113** [comment]
Here is the Xcode exception output after executed this test multiple times. Hope it can help! https://gist.github.com/dlc9113/052533221021e48823977a7c009c0f9d#gistcomment-3362293

**Comment by mykola-mokhnach** [comment]
This is a bug on Apple side. I would try to limit the maximum lookup depth (`snapshotMaxDepth` setting) as a workaround.

**Comment by dlc9113** [comment]
@mykola-mokhnach Thanks for you reply! Yes, this issue is caused by the big snapshotMaxDepth.
Some elements cannot be found by the default snapshotMaxDepth 50, so I try to change it to 100. Now I found it works by snapshotMaxDepth 60.
