### ISSUE TITLE
Unable to launch WebDriverAgent because of xcodebuild failure:

### ISSUE THREAD

**Issue by Johny-appium-nz** [appium/appium#14515]
## The problem

I am getting below error on launching the app on the real device 

An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65 xcodebuild error message: 2020-07-05 23:06:17.880 xcodebuild[25764:784480] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder “WebDriverAgentRunner_iphoneos13.5-arm64.xctestrun” doesn’t exist." UserInfo={NSFilePath=/Users/devtester/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Build/Products/WebDriverAgentRunner_iphoneos13.5-arm64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7f90bd311b30 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}} ** TEST BUILD FAILED ** 2020-07-05 23:06:17.916 xcodebuild[25764:784316] IDETestOperationsObserverDebug: Writing diagnostic log for test session to: /Users/devtester/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Logs/Test/Test-WebDriverAgentRunner-2020.07.05_23-06-15-+1200.xcresult/Staging/2_Test/Diagnostics/WebDriverAgentRunner-961F698B-07C9-435C-94A8-25036B4C997C/WebDriverAgentRunner-AEC1B356-C1AB-42B0-96A6-25312F863215/Session-WebDriverAgentRunner-2020-07-05_230617-DUcTGX.log 2020-07-05 23:06:17.921 xcodebuild[25764:784256] [MT] IDETestOperationsObserverDebug: (4C9C9FA2-F989-4B7A-BDB9-B306D9C542E5) Beginning test session WebDriverAgentRunner-4C9C9FA2-F989-4B7A-BDB9-B306D9C542E5 at 2020-07-05 23:06:17.917 with Xcode 11E608c on target 📱<DVTiOSDevice (0x7f90bd843810),  iPhone X, iPhone, 13.3.1 (1a7D50), 635d8683ecdc7f65d7634ce685f18fac4d5529a3> { deviceSerialNumber: GHLXJ3NJJCLF identifier: 635d8683ecdc7f65d7634ce685f18fac4d5529a3 deviceClass: iPhone deviceName: iPhone X deviceIdentifier: 635d8683ecdc7f65d7634ce685f18fac4d5529a3 productVersion: 13.3.1 buildVersion: 17D50 deviceSoftwareVersion: 13.3.1 (17D50) deviceArchitecture: arm64 deviceTotalCapacity: 55382990848 deviceAvailableCapacity: 48654184448 deviceIsTransient: NO ignored: NO deviceIsBusy: NO deviceIsPaired: YES deviceIsActivated: YES deviceActivationState: Activated isPasscodeLocked: NO deviceType: <DVTDeviceType:0x7f90bd1a2490 Xcode.DeviceType.iPhone> supportedDeviceFamilies: ( 1 ) applications: (null) provisioningProfiles: (null) hasInternalSupport: NO hasWritableSystem: NO isSupportedOS: YES bootArgs: (null) nextBootArgs: (null) connected: YES isWirelessEnabled: NO connectionType: direct hostname: (null) bonjourServiceName: c4:98:80:4c:6c:55@fe80::c698:80ff:fe4c:6c55._apple-mobdev2._tcp.local. activeProxiedDevice: (null) } (13.3.1 (17D50)) 2020-07-05 23:06:18.141 xcodebuild[25764:784256] [MT] IDETestOperationsObserverDebug: (4C9C9FA2-F989-4B7A-BDB9-B306D9C542E5) Finished requesting crash reports. Continuing with testing. *** If you believe this error represents a bug, please attach the result bundle at /Users/devtester/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Logs/Test/Test-WebDriverAgentRunner-2020.07.05_23-06-15-+1200.xcresult 2020-07-05 23:06:18.206 xcodebuild[25764:784256] [MT] IDETestOperationsObserverDebug: 0.299 elapsed -- Testing started completed. 2020-07-05 23:06:18.206 xcodebuild[25764:784256] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start 2020-07-05 23:06:18.207 xcodebuild[25764:784256] [MT] IDETestOperationsObserverDebug: 0.299 sec, +0.299 sec -- end 2020-07-05 23:06:18.208 xcodebuild[25764:784256] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/devtester/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7f90bcae0370 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}} Test session results, code coverage, and logs: /Users/devtester/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Logs/Test/Test-WebDriverAgentRunner-2020.07.05_23-06-15-+1200.xcresult Testing failed: Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the Signing & Capabilities editor. WebDriverAgentRunner: WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file. The file doesn’t exist. (Underlying error: The operation couldn’t be completed. No such file or directory))) ** TEST EXECUTE FAILED ** Testing started on ' iPhone X'. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.

## Environment
App capabilities 

{
  "udid": "635d8683ecdc7f65d7634ce685f18fac4d5529a3",
  "deviceName": "iPhone X",
  "platformVersion": "13.3",
  "app": "/Users/devtester/Downloads/tester.ipa",
  "platformName": "iOS"
}
Appium version: V1.17.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Desktop on Mac OS version  10.15.5 
* Node.js version : v14.4.0
* Npm or Yarn package manager:
* Mobile platform:iOS 13.3.1 
* Real device : iPHONE X
* Appium CLI or Appium.app|exe:

**Comment by mykola-mokhnach** [comment]
Have you tried to build WebDriverAgent manually according to the troubleshooting doc above?

Please attach the full server log with xcodebuild logging enabled

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by krischik** [comment]
> Have you tried to build WebDriverAgent manually according to the troubleshooting doc above?

No. I never had to before and I don't know to do it.

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md does describe how to do that
