### ISSUE TITLE
Chromedriver version is always 73 and its not working 

### ISSUE THREAD

**Issue by chuklov** [appium/appium#14514]
Can someone please explain me how it works. 
[Chromedriver] Spawning chromedriver with: **/Users/chuklova/.m2/repository/webdriver/chromedriver/mac64/83/chromedriver** --url-base=wd/hub --port=58155 --adb-port=5037 --verbose
[debug] [Chromedriver] **Chromedriver version: '73.0.3683.20'**
[debug] [Chromedriver] Chromedriver v. 73.0.3683.20 does not fully support W3C protocol. Defaulting to MJSONWP

$ pwd
**/Users/chuklova/.m2/repository/webdriver/chromedriver/mac64/83**
$ chromedriver -v
**ChromeDriver 83.0.4103.39** (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103@{#416})

My Chromedriver in all directories is 83, however, Appium is still complain that I have version 73 and my tests are not working. 

[debug] [W3C] Encountered internal error running command: Error: Unable to automate Chrome version because it is too old for this version of Chromedriver.
[debug] [W3C] Chrome version on the device: Chrome/83.0.4103.106
[debug] [W3C] Visit 'https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md' to troubleshoot the problem.
[debug] [W3C] A new session could not be created. Details: session not created: Chrome version must be between 70 and 73
[debug] [W3C]   (Driver info: chromedriver=73.0.3683.20 (8e2b610813e167eee3619ac4ce6e42e3ec622017),platform=Mac OS X 10.14.6 x86_64)
[debug] [W3C]     at Object.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:87:35)
[debug] [W3C]     at Chromedriver.start (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/lib/chromedriver.js:589:11)
[debug] [W3C]     at AndroidUiautomator2Driver.setupNewChromedriver (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/context.js:429:3)
[debug] [W3C]     at AndroidUiautomator2Driver.startChromeSession (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/context.js:245:23)
[debug] [W3C]     at AndroidUiautomator2Driver.startUiAutomator2Session (/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/lib/driver.js:379:7)
[debug] [W3C]     at AndroidUiautomator2Driver.createSession (/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/lib/driver.js:212:7)
[debug] [W3C]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:358:35)
[debug] [W3C] Destroying socket connection
[HTTP] <-- POST /wd/hub/session 500 11960 ms - 1503
[HTTP] 
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Unable to automate Chrome version because it is too old for this version of Chromedriver.
Chrome version on the device: Chrome/83.0.4103.106
Visit 'https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md' to troubleshoot the problem.
A new session could not be created. Details: session not created: Chrome version must be between 70 and 73
  (Driver info: chromedriver=73.0.3683.20 (8e2b610813e167eee3619ac4ce6e42e3ec622017),platform=Mac OS X 10.14.6 x86_64)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Mac-mini-2.lan', ip: 'fe80:0:0:0:100a:a1b4:369f:6101%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '1.8.0_241'
Driver info: driver.version: AndroidDriver

Any thoughts on this matter?

**Comment by mykola-mokhnach** [comment]
Have you checked the troubleshooting link?

**Comment by chuklov** [comment]
Yes, did all suggested and the result is the same.
I do not get where it takes the version from.

**Comment by chuklov** [comment]
Solution for this is to add path to the driver you want to use: 

chromedriverExecutable | The absolute local path to webdriver executable (if Chromium embedder provides its own webdriver, it should be used instead of original chromedriver bundled with Appium) | /abs/path/to/webdriver
-- | -- | --

My question was, where it initially take the information from? My MAC doesn't have chromedriver version 73.
