### ISSUE TITLE
Test execution slow on Appium 1.17.1 and iOS 13.5.1

### ISSUE THREAD

**Issue by 63bandersson** [appium/appium#14529]
## The problem

Upgraded Appium version to the latest 1.17.1 and upgraded iOS to 13.5.1 on my test device.
Test execution is very slow compare to iOS 12. 
I have tried different version of iOS from / Appium but it's still very slow on all versions.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS Catalina Version: 10.15.5
* Node.js version (unless using Appium.app|exe): v10.21.0
* Npm or Yarn package manager: npm 6.14.4
* Mobile platform/version under test: 13.5.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

## Details
Since upgrading iOS versions and also upgrading Appium version I have found that the test runs really slow.
Some objects takes really long time to find. In the added logs you can see that finding objects such as:
[39m Calling AppiumDriver.findElement() with args: ["-ios predicate string","type == 'XCUIElementTypeButton' AND name == 'Agenda'","xxxx"] 
and
[39m Calling AppiumDriver.findElement() with args: ["-ios predicate string","type == 'XCUIElementTypeNavigationBar' AND name == 'More'","xxxx"]
takes very long time to find.

## Link to Appium logs
https://gist.github.com/63bandersson/559090c153cb0eaa8e996b6c78aaf71c

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by KazuCocoa** [comment]
I think the root cause is XCTest internal.
We observed some slowness issues on iOS 13 thank iOS 12 like https://github.com/appium/appium/issues/13503

Could you get a log with `showIOSLog: true` capability? It prints more info.
I assume XCTest side took time to proceed the request since the predicate strategy calls https://developer.apple.com/documentation/foundation/nspredicate

**Comment by 63bandersson** [comment]
Gist with showIOSLog: https://gist.github.com/63bandersson/06a6fbec4e437d5c8762970f98e2c0e8

**Comment by mykola-mokhnach** [comment]
> [35m[IOSDeviceLog][39m Jul  9 11:39:38 Bjorns-iPhone testmanagerd(XCTAutomationSupport)[5448] <Error>: Uncaptured runtime issue reported: <private>
> [35m[IOSDeviceLog][39m Jul  9 11:39:38 Bjorns-iPhone testmanagerd(XCTAutomationSupport)[5448] <Notice>: <private> is not actually a child of <private>, including at this point anyway (rdar://problem/20738636)

This for sure does look like as XCTest internal issue. I have doubts there's anything to there on Appium side. 

From the application side I would also make sure it does not "overload" the main loop, so the XCTest daemon has enough time to do its job.

**Comment by 63bandersson** [comment]
Thanks!
