### ISSUE TITLE
Wanted to fetch the current url of my mobile chrome browser.

### ISSUE THREAD

**Issue by Gauravsinghania54** [appium/appium#14520]
#The Exception which i am getting while executing

[HTTP] {}
[debug] [W3C (06629d85)] Calling AppiumDriver.getUrl() with args: ["06629d85-8b08-42e6-af38-4cbd1ce8f77b"]
[debug] [W3C (06629d85)] Encountered internal error running command: NotYetImplementedError: Method has not yet been implemented
[debug] [W3C (06629d85)]     at AndroidUiautomator2Driver.executeCommand (C:\Users\gaura\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\driver.js:323:13)
[debug] [W3C (06629d85)]     at AppiumDriver.executeCommand (C:\Users\gaura\node_modules\appium\lib\appium.js:534:36)
[debug] [W3C (06629d85)]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[debug] [W3C (06629d85)]     at asyncHandler (C:\Users\gaura\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:309:21)
[HTTP] <-- GET /wd/hub/session/06629d85-8b08-42e6-af38-4cbd1ce8f77b/url 405 99 ms - 622

## Environment and Exception while Executing in Java
org.openqa.selenium.UnsupportedCommandException: Method has not yet been implemented
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'P44-GSINGHANIA', ip: '192.168.0.4', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.7'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {appActivity: com.google.android.apps.chr..., appPackage: com.android.chrome, automationName: UiAutomator2, databaseEnabled: false, desired: {appActivity: com.google.android.apps.chr..., appPackage: com.android.chrome, automationName: UiAutomator2, deviceName: appium, noReset: true, platformName: android, platformVersion: 11}, deviceApiLevel: 30, deviceManufacturer: Google, deviceModel: sdk_gphone_x86_arm, deviceName: emulator-5554, deviceScreenDensity: 400, deviceScreenSize: 1080x2160, deviceUDID: emulator-5554, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, noReset: true, pixelRatio: 2.5, platform: LINUX, platformName: LINUX, platformVersion: 11, statBarHeight: 60, takesScreenshot: true, viewportRect: {height: 1980, left: 0, top: 60, width: 1080}, warnings: {}, webStorageEnabled: false}

## Link to Appium logs (Gist) 

https://gist.github.com/Gauravsinghania54/bf6508e29229d1c3176044e2bce2b33d

**Comment by KazuCocoa** [comment]
How about switching to the Web context?
Or you could launch `browserName: chrome` and set the target package name like https://chromedriver.chromium.org/getting-started/getting-started---android via chromeOptions https://appium.io/docs/en/writing-running-appium/caps/
