### ISSUE TITLE
[WebDriverAgent] Support iOS 14 beta or not?

### ISSUE THREAD

**Issue by livc** [appium/appium#14524]
## The problem

After running `Test` I got
```
The iPhone is no available
Please reconnect the iPhone or select a different device and try again.
```

## Environment

* Appium version (or git revision) that exhibits the issue: WebDriverAgent latest version (359537e52046398fb0ee8489efe259a0fe91bc56)
* Desktop OS/version used to run Appium: iOS 14.0 (18A5301v)

**Comment by KazuCocoa** [comment]
Please give us more context and available logs.
Was the message by xcodebuild? If so, could you give us the command line, logs etc?

The message looks Xcode or xcodebuild lost the device, personally.

We ran WDA for iOS 14 simulators, but not for a real device.

**Comment by livc** [comment]
@KazuCocoa 
I just run `Product - Test` in Xcode and got the message.
The build is successful.
I am using a real device, how to provide further info to you?

**Comment by KazuCocoa** [comment]
No log on the bottom console? Or the message appeared there? (If so, I guess xcodebuild lost the device and it failed to install the WDA)

Or how about the output of xcodebuild with the scheme like below? (The log will be large, so please share as GIST)

`xcodebuild build-for-testing test-without-building -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO`

**Comment by livc** [comment]
Yes, no log in bottom console.

https://paste.ubuntu.com/p/tcb6PkqNJ4/

Seems I have to update my macOS? My Xcode version is Version 11.5.

**Comment by KazuCocoa** [comment]
Ah, yes. Xcode 12 can communicate with iOS 14

> Recovery Suggestion: To run on this device, please update to a version of Xcode that supports iOS 14.0. You can download Xcode from the Mac App Store or the Apple Developer website.
