### ISSUE TITLE
Screenshot doesn't reflect actual UI state on iOS 13

### ISSUE THREAD

**Issue by mstrelex** [appium/appium#14531]
# Steps to reproduce

* Happens in any iOS app using Appium.app and the inspector or code on any device.
* Use the `sendKeys` command on a XCUIElementTypeSecureTextField, then grab DOM and screenshot.

## The problem

* Screenshot doesn't reflect the actual UI state - soft keyboard is not shown and element value is empty.
* Same for mirroring via MJPEG server and QuickTime - they do not show the state displayed on the device.
* Action **does** happen on the device and value is there.

It seems like it is some sort of a security feature Apple added recently... as it works fine on iOS 12.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1
* Desktop OS/version used to run Appium: macOS
* Node.js version (unless using Appium.app|exe): Appium.app
* Mobile platform/version under test: 13.4
* Real device or emulator/simulator: iPhone XR
* Appium CLI or Appium.app|exe: Appium.app

**Comment by mykola-mokhnach** [comment]
Yes, this is the security feature that Apple added to iOS 13. Unfortunately, there is absolutely nothing that could be done from Appium side.
