### ISSUE TITLE
App is partially downloaded but continues to attempt to install

### ISSUE THREAD

**Issue by apulverizer** [appium/appium#14534]
## The problem

The appium server seems to only partially down files in some cases and might not be handling errors correctly.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 10.15.5
* Node.js version (unless using Appium.app|exe): 12.16.3
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: Android Pixel 2 Emulator API 28
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: cli

## Details

We are specifying the app as a url to an apk on our build server and expect it install on the emulator and then execute the tests. Sometimes though (seemingly random) the file is only partially downloaded. 

```
[debug] [BaseDriver] 'http://appbuilder.esri.com:8080/userContent/android_LQ/FieldMaps/latest/FieldMaps-qa.apk' (28.34 MB) has been downloaded to '/Users/aaro8157/Documents/tmp/202069-76275-1l5ewgp.p52m/FieldMaps-qa.apk' in 16.400s
[debug] [BaseDriver] Approximate download speed: 1.73 MB/s
```

The actual apk size should be 107 MB though. It does not error as expected and continues to attempt to install. The install fails with this error:

```
[debug] [W3C] Encountered internal error running command: Error: end of central directory record signature not found
```

This is further exacerbated because the invalid apk is then cached so all future requests (until the cache expires or a new build is hosted) fails.

I'm not able to reproduce this deterministically but switching the url to point to different builds while in the same appium server session seems to produce more of these errors.

I'm guessing there is a bug somewhere in in [this function](https://github.com/appium/appium-support/blob/master/lib/net.js#L187) that is not handling an error correctly.

## Link to Appium logs

[Full Logs](https://gist.github.com/apulverizer/164091dbb018df43eeb0af37764465dd) - this contains multiple app downloads/tests. The relevant issue can be found by searching the file for `2020-07-09 23:58:41:756 [BaseDriver] Approximate download speed: 1.73 MB/s` - it's line 9367.

**Comment by mykola-mokhnach** [comment]
This could be happening due to internal network issues (the server drops the connection before the content is fully retrieved). I've added content-length validation there, but this will just allow to fail the flow on the early stage and won't allow a corrupted file to be cached. The original download issue will remain.

**Comment by apulverizer** [comment]
Thanks for looking into this @mykola-mokhnach. I agree the root cause is some network issue. I tested your branch locally and it is working as expected (error logged, and app is not cached). What's the timeline for this to get into the next release?

**Comment by mykola-mokhnach** [comment]
The change has been published to appium@beta
