### ISSUE TITLE
Appium 1.17.1, can't start session

### ISSUE THREAD

**Issue by stuchins** [appium/appium#14532]
## The problem
Appium (many users in the company having this problem after installing 1.17.1) couldn't start session with the error:
Android:
[debug] [W3C] Encountered internal error running command: Error: The instrumentation process cannot be initialized within 30000ms timeout. Make sure the application under test does not crash and investigate the logcat output. You could also try to increase the value of 'uiautomator2ServerLaunchTimeout' capability. 

IOS:
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1593557049556 (18:44:09 GMT-0400 (Eastern Daylight Time))
[debug] [W3C] Encountered internal error running command: Error: Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: 403 - "<!DOCTYPE html><html lang=\"en-US\"><head><meta charset=\"utf-8\"><title>127.0.0.1 - Access Denied</title><meta name=\"viewport\" content=\"width=device-width,initial-scale=1,shrink-to-fit=no\"><link href

## Environment

* Appium 1.17.1
* Last Appium version that did not exhibit the issue 1.15.1:
* Desktop OS/version used to run Appium: Catalina (and on some machines Mojave) Mac machines
* Node.js version (unless using Appium.app|exe): 10.15.0
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: Android -any version have same problem
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: Appium CLI
* Carthage 0.34.0

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
[AndroidAppium.log](https://github.com/appium/appium/files/4898987/AndroidAppium.log)
[ios_appumlogs.txt](https://github.com/appium/appium/files/4898990/ios_appumlogs.txt)

**Comment by mykola-mokhnach** [comment]
> [35m[WD Proxy][39m Got response with status 403: <!DOCTYPE html><html lang="en-US"><head><meta charset="utf-8"><title>127.0.0.1 - Access Denied</title><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"><link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600i,700&display=swap" rel="stylesheet"><style type="text/css">html{height:100%;box-sizing:border-box}*,:after,:before{box-sizing:inherit}@keyframes rotate{to{transform:rotate(360deg)}}body{position:relative;min-height:100%;font-family:"Open Sans",-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol";font-size:.875rem;font-weight:400;color:#333;line-height:1.5;margin:0;background-color:#fff}button{font-family:"Open Sans",-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol"}.container{min-height:100%;padding:0 15px 48px 15px;margin:0 auto -48px auto;width:100%}.image-container{width:100...

There is some proxy or a firewall running in your enterprise network and blocking Appium requests. Consider contacting your system administrator to resolve the issue. There is nothing that could be done from Appium side there

**Comment by adroittamil** [comment]
But this works for Appium 1.15 not on 1.17,we have no issues when running 1.15 version of appium whereas this issue persists when it is 1.17 and above

**Comment by stuchins** [comment]
"There is some proxy or a firewall running in your enterprise network and blocking Appium requests." - request to where? Everything runs on the same machine. If we would know what request Appium makes - we would fix the settings, but Appium doesn't give any clue.

**Comment by KazuCocoa** [comment]
For iOS
Can Appium get a response by GET request to `http://127.0.0.1:8100/status` to communicate with WDA on the device under test?
It returned `Access Denied` HTML, but it should be like below. So, we wondered something your environment blocks them.

```
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] Got response with unknown status: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[debug] [WD Proxy] Got response with status 200: {
[debug] [WD Proxy]   "value" : {
[debug] [WD Proxy]     "message" : "WebDriverAgent is ready to accept commands",
[debug] [WD Proxy]     "state" : "success",
[debug] [WD Proxy]     "os" : {
[debug] [WD Proxy]       "name" : "iOS",
[debug] [WD Proxy]       "version" : "13.3",
[debug] [WD Proxy]       "sdkVersion" : "13.0"
[debug] [WD Proxy]     },
[debug] [WD Proxy]     "ios" : {
[debug] [WD Proxy]       "simulatorVersion" : "13.3",
[debug] [WD Proxy]       "ip" : "192.168.1.124"
[debug] [WD Proxy]     },
[debug] [WD Proxy]     "ready" : true,
[debug] [WD Proxy]     "build" : {
[debug] [WD Proxy]       "upgradedAt" : "1581607939411",
[debug] [WD Proxy]       "time" : "Feb 14 2020 00:32:26",
[debug] [WD Proxy]       "productBundleIdentifier" : "com.facebook.WebDriverAgentRunner"
[debug] [WD Proxy]     }
[debug] [WD Proxy]   },
[debug] [WD Proxy]   "sessionId" : "2F7002AC-0316-49AE-AFDA-AF69075E802B"
[debug] [WD Proxy] }
```

--

your log

```
[debug] [35m[WD Proxy][39m Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[35m[WD Proxy][39m Got response with status 403: <!DOCTYPE html><html lang="en-US"><head><meta charset="utf-8"><title>127.0.0.1 - Access Denied</title><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"><link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600i,700&display=swap" rel="stylesheet"><style type="text/css">html{height:100%;box-sizing:border-box}*,:after,:before{box-sizing:inherit}@keyframes rotate{to{transform:rotate(360deg)}}body{position:relative;min-height:100%;font-family:"Open Sans",-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol";font-size:.875rem;font-weight:400;color:#333;line-height:1.5;margin:0;background-color:#fff}button{font-family:"Open Sans",-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol"}.container{min-height:100%;padding:0 15px 48px 15px;margin:0 auto -48px auto;width:100%}.image-container{width:100...
```

**Comment by adroittamil** [comment]
@mykola-mokhnach  @KazuCocoa : i agree, if it is happening for both 1.15 and 1.17 then there is a chance that its an issue with Some proxy port being blocked, whereas it is blocking only 1.17.

**Comment by mykola-mokhnach** [comment]
The main difference between version 1.15 and 1.17 is that http(s) client has been replaced. Previously it was the deprecated requests module and now we are using axios. I don't know the details of your particular corporate network setup, but the fact is, that axios tries to automatically [guess](https://github.com/axios/axios/blob/fbb5d4d0d1d4dd1cdbb02f30d05738e0b8e5316b/lib/adapters/http.js#L85) proxy parameters from the process env. One could try to set `http_proxy` and/or `https_proxy` environment variables to empty values for appium process if this is an undesired behaviour.

**Comment by danielMayberg** [comment]
@mykola-mokhnach I have this issue as well with iOS simulator, seems that there are several retries to get it running until it gets a successful response. When running Appium desktop it waits for the successful response, but when running from automation project the appium driver fails to initialise. So either it's a timing bug or there is some capability I missed to retry until success. 

log from Appium Desktop:
Got response with unknown status: 
`Got response with unknown status: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] Got response with unknown status: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] Got response with unknown status: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[debug] [WD Proxy] Got response with status 200: {
[debug] [WD Proxy]   "value" : {
[debug] [WD Proxy]     "message" : "WebDriverAgent is ready to accept commands",
[debug] [WD Proxy]     "state" : "success",
[debug] [WD Proxy]     "os" : {
[debug] [WD Proxy]       "name" : "iOS",
[debug] [WD Proxy]       "version" : "13.5",
[debug] [WD Proxy]       "sdkVersion" : "13.4"
[debug] [WD Proxy]     },
[debug] [WD Proxy]     "ios" : {
[debug] [WD Proxy]       "simulatorVersion" : "13.5",
[debug] [WD Proxy]       "ip" : "10.100.102.13"
[debug] [WD Proxy]     },
[debug] [WD Proxy]     "ready" : true,
[debug] [WD Proxy]     "build" : {
[debug] [WD Proxy]       "upgradedAt" : "1589203742630",
[debug] [WD Proxy]       "time" : "Jul  4 2020 19:24:33",
[debug] [WD Proxy]       "productBundleIdentifier" : "com.facebook.WebDriverAgentRunner"`

**Comment by stuchins** [comment]
@mykola-mokhnach - is it possible to list what ports are used by appium by default so we would be able to check if any of them are blocked? Thank you.

**Comment by mykola-mokhnach** [comment]
Appium server uses port #4723 by default for external communication and xcuitest driver uses the port 8100 by default to proxy its requests to a connected device

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by danielMayberg** [comment]
@mykola-mokhnach can you please respond to my comment. thanks

**Comment by mykola-mokhnach** [comment]
@danielMayberg Please describe a separate issue. Your comment has nothing to do with the original one.

**Comment by adroittamil** [comment]
Issue resolved thanks @mykola-mokhnach

**Comment by adroittamil** [comment]
> The main difference between version 1.15 and 1.17 is that http(s) client has been replaced. Previously it was the deprecated requests module and now we are using axios. I don't know the details of your particular corporate network setup, but the fact is, that axios tries to automatically [guess](https://github.com/axios/axios/blob/fbb5d4d0d1d4dd1cdbb02f30d05738e0b8e5316b/lib/adapters/http.js#L85) proxy parameters from the process env. One could try to set `http_proxy` and/or `https_proxy` environment variables to empty values for appium process if this is an undesired behaviour.

This Fixed this issue,
