### ISSUE TITLE
Appium 1.15.1, Connection was refused to port 8100 in IOS 14,

### ISSUE THREAD

**Issue by Rosielover** [appium/appium#14537]
##Connection was refused to port 8100
Hello 
I got an issue when my device is updated from IOS 13.x.1 to 14.0. I were trying with some guides but I cannot by pass the issue. I tried to with Appium 1.17.1, 1.16,1.15.1 , but still got the same issue .Please help to look at my issue and consult how to fix it. 

[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@00008...] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up). Retrying...

## Environment

* Appium version (or git revision) that exhibits the issue:1.15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:Mac 10.15.5
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:6.14.4
* Mobile platform/version under test:14
* Real device or emulator/simulator:Real Device
* Appium CLI or Appium.app|exe:Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
https://gist.github.com/Rosielover/f6a8ea86dee5effcf31dff5cbda516a5

**Comment by mykola-mokhnach** [comment]
You could try appium@beta, but we don't guarantee it is going to work, because the recent iOS beta is constantly being changed

**Comment by Rosielover** [comment]
Thank you very much @mykola-mokhnach . My issue is resolved. You are so wonderful. Thanks
