### ISSUE TITLE
wda server without system dependencies

### ISSUE THREAD

**Issue by balaganes** [appium/appium#14538]
## The problem

I'm trying to build custom wda server. Also planning to remove all dependencies for the same. 

As suggested in [appium-ios-device](https://github.com/appium/appium-ios-device) repository, i've extended the [libimobiledevice](https://github.com/libimobiledevice/libimobiledevice) library in java, almost succeeded with installation and starting the app in real device.  But the wda server is not starting in the device. 

I've attached the console log from device. Please help me to sort out the issue.

## Environment

* Mobile platform/version under test: iOS 13.5.1
* Real device or emulator/simulator: Real Device
* WDA project taken from Appium version : 1.17.1

## Details

WDA server is starting correctly if I use the below command directly. 
But it will depend on XCode, so I can't use this in windows.

`xcodebuild test-without-building -xctestrun WebDriverAgentRunner_iphoneos13.5-arm64e.xctestrun -destination 'platform=iOS,id=<UDID>`

## Link to Console logs

https://gist.github.com/balaganes/51bddbc565c4f677443fc7e00003f56e

## Code To Reproduce Issue

to install libimobiledevice utitilies 
`sudo port install libimobiledevice`

to install app
`ideviceinstaller -i <IPA_FILE_PATH>`

to start wda server
`idevicedebug -d run com.facebook.WebDriverAgentRunner.xctrunner`

**Comment by KazuCocoa** [comment]
I'm not familiar with the `idevicedebug` internal, but if idevicedebug could not launch testmanagerd deamon, the error is expected.
https://github.com/facebookarchive/WebDriverAgent/issues/114 and https://github.com/appium/appium-xcuitest-driver/pull/1030 may help by https://github.com/facebook/idb

**Comment by balaganes** [comment]
Thanks for you references and reply 👍

Initially I too thought "testmanagerd" is not launched by idevicedebug. After analyzing the device log I assume it is launched. I think there may be some configuration part is missing to start actual testing. I will dig further.

**Comment by KazuCocoa** [comment]
Okay.
As Appium, we set below items as process arguments (from the 1030  link)
https://github.com/appium/appium-xcuitest-driver/pull/1030/files#diff-dd1c1e9a4d2cba48fc21e5d2c50abcafR258-R264
They may be relevant.
