### ISSUE TITLE
Appium could not shows WEBVIEW but actually exists on an Android Native App 

### ISSUE THREAD

**Issue by RamSaiMallik** [appium/appium#14539]
## The problem

running Appium on windows to test an Android Native App directly on an Android device. However, when I try to fetch the contexts and switch to the one containing WEBVIEW (When I use UIAutomator Viewer or Chrome DevelopTool Inspector, It does exist named as android.webkit.WebView), But when I try to catch it via driver.switch_to.context('WEBVIEW') it gives me No Such Context...I debug the code on the contexts lists only returns one context, NATIVE_APP.

When I use the inspector, I'm able to see a WebView and a lot of View children appended to it, which relate to each one of the elements inside the app. So, despite it doesn't show the element tree in Web view mode, I'm able to see it's using a WebView, but somehow isn't able to connect to that specific context.

## Environment

* appium java-client 4.1.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: windows10
* Mobile platform/version under test: android
* Real device or emulator/simulator: real device
* Appium studio: 20.6

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

![image](https://user-images.githubusercontent.com/35252454/87185187-f6705b00-c306-11ea-9ba0-72881b0279e4.png)

## Code To Reproduce Issue [ Good To Have ]

AppiumDriver<MobileElement> driver;
	String path;

	public void setUp() {
		System.out.println("Session is creating");
		path = System.getProperty("user.dir");
		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
		capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "GALAXY");
		---------------------------------------------------------------
		capabilities.setCapability("automationName", "uiautomator2");
		capabilities.setCapability("setWebContentsDebuggingEnabled","true");
		try {
			driver = new AndroidDriver<MobileElement>(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);
		} catch (MalformedURLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
		System.out.println("Session is created");
	}

	public void getWebViewText() {
		System.out.println("First Current Context : " + driver.getContext());
		----------------------------------------
                ------------------------------------------------------
                -----------------------------------------------------
		---------------------------------------------
		// Using this method we switch to web view
		switchContext("webview");
		String webViewText = driver.findElementByXPath("//a").getText();
		System.out.println(webViewText);

	}

	/**
	 * This method for switch view
	 * 
	 * @param context
	 */

	public void switchContext(String context) {
		System.out.println("Before Switching : " + driver.getContext());
		Set<String> con = ((AppiumDriver) driver).getContextHandles();
		for (String c : con) {
			System.out.println("Available Context : " + c);
			if (c.contains(context)) {
				driver.context(c);
				break;
			}
		}
		System.out.println("After Switching : " + driver.getContext());
	}

	public void verticalSwipe() {
		Dimension dim = driver.manage().window().getSize();
		int height = dim.getHeight();
		int width = dim.getWidth();
		int x = width / 2;
		int starty = (int) (height * 0.80);
		int endy = (int) (height * 0.20);
		driver.swipe(x, starty, x, endy, 500);

	}

	public void tearDown() {
		driver.quit();
	}

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		poc1 obj = new poc1();
		obj.setUp();
		obj.getWebViewText();
		obj.tearDown();
	}

}

**Console**
Session is creating
Session is created
First Current Context : NATIVE_APP    //     initially checking the view
Before Switching : NATIVE_APP          //      Before clicking the webview link 
Available Context : NATIVE_APP         //       after clicking the webview link , only one Context  is showing
After Switching : NATIVE_APP

**Comment by mykola-mokhnach** [comment]
Please provide the full server log

**Comment by mykola-mokhnach** [comment]
Closed because of no response
