### ISSUE TITLE
iOS: Timeout on WebView when started new driver session without ending current driver session

### ISSUE THREAD

**Issue by omprakashchavan01** [appium/appium#14540]
## The problem

Appium is failing to find element on WebView (kind of goes into loop with multiple timeouts happening between the remote debugger and Appium) when I start a new driver session without waiting for the current driver session to end (specifically without waiting for the driver to end the connection with the remote debugger. I believe it waits for 60 seconds for new command and then quits and only while quitting, it ends the connection with the remote debugger).

**Important note:** 
The only way I could recover from this issue is by manually turning OFF and ON the Web Inspector option in the Safari settings.
If I don't do this, it keeps failing for every new driver session and also messes up the Desktop Safari Web Inspector session. It kind of stops working i.e. fails to show the WebView for the device.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: 10.15.5
* Node.js version (unless using Appium.app|exe): Using Appium Desktop
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: iOS 13.3
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium.app

## Details

Ok so here is what I'm trying to do.
- Launch Uber app
- Click "Or connect using a social account" link
- Select Google login option
- On accounts.google.com page, try to find "Sign In" text

This works perfectly fine for the first time.
But fails to work if I start new driver session before waiting for the current one to end (i.e. before the driver closes connection with the remote debugger).
So here it's able to navigate until accounts.google.com page and able to detect the WebView, but fails to find the element.
It keeps getting "Encountered internal error running command: Error: Did not get any response for atom execution after 120004ms".
This continues for like 5 minutes or so before the execution is terminated.

**Note:** 
If I let the driver quit and let it close the remote debugger session and then I start the new driver session, this works absolutely fine. I have done this like multiple times and quite confident about it.
Also, I've also reproduced the issue every time I created a new driver session without waiting for the current one to end, so I'm quite confident about this too.

## Link to Appium logs

https://gist.github.com/omprakashchavan01/43ef6b1452cc820ace077410b86afea0
## Code To Reproduce Issue [ Good To Have ]

AppiumDriver driver = CreateDriverSession.initializeDriver("iOS");
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);

        driver.findElement(MobileBy.AccessibilityId("Or connect using a social account.")).click();
        driver.findElement(MobileBy.AccessibilityId("Google")).click();
        Thread.sleep(5000);

        Set contextHandles = driver.getContextHandles();
        for(Object contextHandle: contextHandles){
            System.out.println(contextHandle.toString());
        }
        driver.context(contextHandles.toArray()[1].toString());
        System.out.println(driver.findElement(MobileBy.xpath("//*[@id=\"headingText\"]/span")).getText());

**Comment by KazuCocoa** [comment]
BTW, did you quite the session before starting a new session?
https://gist.github.com/omprakashchavan01/43ef6b1452cc820ace077410b86afea0#file-ioswebviewappiumserverlogs-L800 looks a new session starts before quitting the previous session.

**Comment by omprakashchavan01** [comment]
Nope.

**Comment by KazuCocoa** [comment]
Then, the current behaviour is expected since Appium does not close the previous session forcefully by default. The socket connection to the real device for the session should be kept then. `helpers.stopRemote` https://github.com/appium/appium-ios-driver/blob/04caae028e874eb07faf31c80e309c33a14541cc/lib/commands/context.js#L579 works in delete session process.

`--session-override` option https://appium.io/docs/en/writing-running-appium/server-args/ deletes the previous session forcefully before starting a new session.

**Comment by omprakashchavan01** [comment]
Appreciate your quick responses.
Sure, will try session-override and let you know.

Do you think this should be a limitation with WebView as this works
perfectly fine with the native view?

Consider this scenario:
While debugging, we might end the program abruptly or there could be
failure quiting the current driver session. After this, if we run the
program again, it will end up creating a new driver session resulting into
the issue mentioned above.
If we are not aware about this issue, then we will end up spending some
time in figuring out the root cause. This is what happened with me.

May be adding a note about this in the documentation can also help.

Let me know what you think.

**Comment by omprakashchavan01** [comment]
Update: The issue is not observed with session override option.

**Comment by KazuCocoa** [comment]
Ok, thanks

**Comment by KazuCocoa** [comment]
Added a note in create session documentation.
Feel free to create a PR if you have any ideas about this more.
