### ISSUE TITLE
INSTALL_PARSE_FAILED_NO_CERTIFICATES on appium-uiautomator2-server-debug-androidTest.apk

### ISSUE THREAD

**Issue by deltamaster** [appium/appium#14542]
## The problem

```
[ADB] Install command stdout: pkg: /data/local/tmp/appium_cache/8d4156e508daae39c3f4815552e22e311432ff1f.apk
[ADB] Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]

```
## Environment

* Appium version (or git revision) that exhibits the issue: v1.17.1
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Windows 10 r1903
* Node.js version (unless using Appium.app|exe): Appium.exe
* Npm or Yarn package manager:
* Mobile platform/version under test: Android platformVersion 6.0.1
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Appium.exe

## Details

```
[ADB] Install command stdout: pkg: /data/local/tmp/appium_cache/8d4156e508daae39c3f4815552e22e311432ff1f.apk
[ADB] Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]

```
However, apksigner shows that the package was signed:
```
[ADB] Starting apksigner: 'C:\\Program Files\\Java\\jdk-14.0.1\\bin\\java.exe' -Xmx1024M -Xss1m -jar E:\\platform-tools\\platform-tools\\apksigner.jar verify --print-certs C:\\Users\\hansen\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-debug-androidTest.apk
[ADB] apksigner stdout: Signer #1 certificate DN: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
[ADB] Signer #1 certificate SHA-256 digest: a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc
[ADB] Signer #1 certificate SHA-1 digest: 61ed377e85d386a8dfee6b864bd85b0bfaa5af81
[ADB] Signer #1 certificate MD5 digest: e89b158e4bcf988ebd09eb83f5378e87
[ADB] 
[ADB] 'C:\Users\hansen\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk' is signed with the default certificate

```
`[ADB] The application at 'C:\Users\hansen\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk' is already cached to '/data/local/tmp/appium_cache/8d4156e508daae39c3f4815552e22e311432ff1f.apk'
`
The other package appium-uiautomator2-server-v4.5.5.apk works fine.

## Link to Appium logs

https://gist.github.com/deltamaster/aa99b676b2bfa96bf4fbbef1418a6817

## Code To Reproduce Issue [ Good To Have ]

Desired Capabilities:
```
{
  "platformName": "Android",
  "deviceName": "127.0.0.1:7555",
  "platformVersion": "6.0.1",
  "appPackage": "com.tencent.mobileqq",
  "appActivity": "com.tencent.mobileqq.activity.SplashActivity",
  "noSign": false,
  "automationName": "UiAutomator2"
}
```

**Comment by KazuCocoa** [comment]
How about setting below capability and run a couple of times?
`remoteAppsCacheLimit: 0` http://appium.io/docs/en/writing-running-appium/caps/

Or if your cert command by your version's devtools had an issue, change other versions may also help.
(We observed v29 sdk tools for Windows had some issues in our issues.)

**Comment by mykola-mokhnach** [comment]
To me it also looks like a bug in Android SDK

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
