### ISSUE TITLE
WEBDRIVERAGENT: Not Returning Complete Text Value with /Text for TextView Field

### ISSUE THREAD

**Issue by santoshkumar-soma** [appium/appium#14543]
Hello Team,

We are facing strange issue with one of the Test Application. The /text Api from WDA is not returning complete value from TextView in case of multiline String value.

WDA is returning the complete Text value in case if i point to _XCT_snapshotForElement instead of _XCT_requestSnapshotForElement in fb_requestSnapshot method(XCUIElement (FBUtilities)).

Could you please help me what is the difference between these two methods? Do I need to ask my developers to re-build the test application with latest Xcode.

At the same time , We are able to fetch the accessible source with the api(/wda/accessibleSource) but actual source api(/source) is getting failed with the below error.

**Internal error: Error Domain=XCTDaemonErrorDomain Code=39 "Legacy accessibility snapshots are no longer supported" UserInfo={NSLocalizedDescription=Legacy accessibility snapshots are no longer supported}**

Thanks
Santhosh.

**Comment by KazuCocoa** [comment]
Please ask it for Apple. Only they know the detail.

`_XCT_snapshotForElement` raises deprecated log in Xcode 11 so we switched to `_XCT_requestSnapshotForElement` which may have been the alternative.
https://github.com/appium/WebDriverAgent/blob/a44bb179a74e3bf29516e8b72a1fdbe801b9da30/PrivateHeaders/XCTest/XCTestManager_ManagerInterface-Protocol.h

**Comment by Dan-Maor** [comment]
Which iOS / Xcode versions are you using?

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
