### ISSUE TITLE
Appium doesn't detect any element on android when running with react native

### ISSUE THREAD

**Issue by robto09** [appium/appium#14559]
## The problem

Hellow there! I have instaled and configured appium in react native with wdio/cli in last version. Issues its appium is not detecting any alement like buttons,views etc. When the test is finished error appear in this way for example: 

```
Error: Can't call click on element with selector "~login_button" because element wasn't found
``` 

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MACOS
* Node.js version (unless using Appium.app|exe): 12.0.10
* Npm or Yarn package manager: Yarn
* Mobile platform/version under test: Android(React Native)
* Real device or emulator/simulator: Android Emulator
* Appium CLI or Appium.app|exe:

**Comment by mykola-mokhnach** [comment]
Appium can only detect what the app itself makes available to the accessibility manager. Consider using Hybrid mode when testing non-native apps

**Comment by robto09** [comment]
> Appium can only detect what the app itself makes available to the accessibility manager. Consider using Hybrid mode when testing non-native apps

What do you mean by using Hybrid mode? Thanks

**Comment by mykola-mokhnach** [comment]
I mean http://appium.io/docs/en/writing-running-appium/web/hybrid/

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
