### ISSUE TITLE
Error: EACCES: permission denied, scandir '/Users/username/Library/Logs/DiagnosticReports/Retired'

### ISSUE THREAD

**Issue by pbellchambers** [appium/appium#14553]
## The problem

After updating my mac to catalina I am no longer able to run appium against iOS simulators. The following error is displayed shortly after the simulator is first launched:

```
[debug] [IOSSimulatorLog] Starting log capture for iOS Simulator with udid '1286B103-16BD-42CF-8191-797468167D44' using simctl
glob error [Error: EACCES: permission denied, scandir '/Users/username/Library/Logs/DiagnosticReports/Retired'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/Users/username/Library/Logs/DiagnosticReports/Retired'
}
```

My user does not have permission to the directory specified, and I do not have admin rights on this machine in order to chown the directory. This was working before the Catalina update on macOS version 10.14.6, where this specific directory did not exist (confirmed via another mac), so seems it is new with Catalina.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1
* Last Appium version that did not exhibit the issue (if applicable): Worked previously on macOS 10.14.6 with the same version of Appium.
* Desktop OS/version used to run Appium: macOS Catalina 10.15.5
* Node.js version (unless using Appium.app|exe): 14.5.0
* Npm or Yarn package manager: npm 6.14.6
* Mobile platform/version under test: iPhone 11 - iOS 13.4 - Xcode 11.4.1
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI

## Details

Not sure if it is related to this: https://openradar.appspot.com/FB7603295 
Does that mean it's an appium issue or a Mac issue? If it's a Mac issue, does that mean that users without root permission are unable to use Appium at all on Catalina until resolved? I would assume more people would have flagged it as a problem if that were the case.

## Link to Appium logs

[https://gist.github.com/pbellchambers/68bdac1d9838195231df7dbdb3f7c158](https://gist.github.com/pbellchambers/68bdac1d9838195231df7dbdb3f7c158)

## Code To Reproduce Issue [ Good To Have ]

It's reproducible for me regardless of the code used. Here is a gist of the appium logs from running the sample-code/javascript-webdriverio: 

[https://gist.github.com/pbellchambers/81426c1f34032b5a723631bbcbc51330](https://gist.github.com/pbellchambers/81426c1f34032b5a723631bbcbc51330)

**Comment by mykola-mokhnach** [comment]
I think it would be ok to just ignore such errors in this particular case: https://github.com/appium/appium-xcuitest-driver/pull/1217

**Comment by mykola-mokhnach** [comment]
The patch has been published to appium@beta

**Comment by harish091998** [comment]
I am facing the same issue. What is the fix I have to do on my side?

**Comment by gmhcode** [comment]
did you ever find a solution to this?

**Comment by harish091998** [comment]
> did you ever find a solution to this?

Hey, I was able to reach a solution. Not sure if it is right but it worked for me . 

Just set the permissions manually for that particular folder or any folder that it is not able to access. Give it read, write and execute permissions using:
chmod 755 <foldername>

**Comment by lindazha** [comment]
Anyone solved this issue? I don't have sudo access to my MAC (work) and this is blocking my progress. Thanks!
