### ISSUE TITLE
Socket hang up error when running on real devices on SauceLabs (NodeJS)

### ISSUE THREAD

**Issue by IevgenRagulin** [appium/appium#14555]
## The problem

I'm getting "socket hang up" error when running tests on real devices on Saucelabs (about 80% of test runs fail with this error). The issue is almost non-existent when running tests locally (on a real device or a simulator), or when running tests on Bitbar (I get it maybe once in 100 runs locally/on Bitbar). I also haven't seen the issue on AWS Device Farm. Running iOS tests. I use appium 1.17.1. 

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.17.1
* Desktop OS/version used to run Appium: MacOS Catalina 10.15.5
* Node.js version (unless using Appium.app|exe): 12.16.1
* Npm or Yarn package manager: yarn 1.12.3
* Mobile platform/version under test: iPhone XR, 13.4.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Saucelabs server us1.appium.testobject.com

## Details

Test runs for a while and then fails at a seemingly random place with "socket hang up" error. A bit of googling suggested that "socket hang up" error usually means that the server stopped responding to client's requests. How do I prevent that from happening with Saucelabs?

## Link to Appium logs

Client appium logs: 
https://gist.github.com/IevgenRagulin/25273444c0efd4975b43af99ec5e0628
Server appium logs:
https://gist.github.com/IevgenRagulin/a41e0c077e8578edc8244438576dd65c
Device logs:
https://gist.github.com/IevgenRagulin/ef7ad591f8fac4a7bda785429c86d2b7
Webdriver agent logs:
https://gist.github.com/IevgenRagulin/c9d8d1e502f794dbedc619d152585558

Not sure if you have access to my Saucelabs runs, here is the related run:
https://app.testobject.com/#/zhenya_ragulin/life-extend/view/5b2d6476-525e-4b07-aa7d-fa0554a18667?execution=66&dc=US

## Code to reproduce:
This project has all the code (including the dependencies)
https://www.dropbox.com/s/7u1fslaekkl53nm/life-extend-e2e_copy.zip?dl=0

To run the tests on saucelabs, you need to run "yarn sauce:runIOS". This is the app under test signed using dev certificate: https://www.dropbox.com/s/jifby8ogxpzlj4h/life_extend.ipa?dl=0

**Comment by KazuCocoa** [comment]
Please contact to the sauce support. It's the best way, I believe. @IevgenRagulin

**Comment by IevgenRagulin** [comment]
In case someone has this issue: it seems that I have been able to resolve it by providing a custom https agent to webdriver.io:

wdio.ios.rdc.app.conf:
```
// Prevent "socket hang up" errors
 config.agent = {
   https: new https.Agent({timeout: 180000})
 }
```
I'm not sure why things don't work with the default https agent, and what the implications of providing a custom agent are.
