### ISSUE TITLE
IOS(react native)- After call HideKeyboard(), click() function not work.

### ISSUE THREAD

**Issue by benchui2345** [appium/appium#14564]
## The problem

After set the value to textinputview and call hideKeyboard() method to release the page. But the app does not have any response after call the click button. To perform the action, it is required to click twice.

## Environment

Appium Studio 20.4.6801

**Comment by mykola-mokhnach** [comment]
Appium Studio is a third party commercial product and has nothing to do with the current OSS one. Consider contacting the product vendor customer support
