### ISSUE TITLE
Encountered internal error running command: Error: The instrumentation process cannot be initialized within 60000ms timeout. Make sure the application under test does not crash and investigate the logcat output. You could also try to increase the value of 'uiautomator2ServerLaunchTimeout' capability

### ISSUE THREAD

**Issue by harshcse-089** [appium/appium#14579]
## The problem

When running android automation tests using appium getting the error "The instrumentation process cannot be initialized within 60000ms timeout"

## Environment

* Appium version (or git revision) that exhibits the issue: <1.16.0 
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Ubuntu 20.04 LTS
* Node.js version (unless using Appium.app|exe): 14.5.0
* Npm or Yarn package manager: NPM 6.14.5
* Mobile platform/version under test:  Android 10
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: appium CLI and appium app

## Details

I am trying to setup new slave machines for my CI. The system details are provided above. As soon as I run the test the emulator is loaded , but then the app initialization does not happen and the above instrumentation error is thrown.

## Link to Appium logs

[Appium log](https://gist.github.com/harshcse-089/7cb0a77afbda0b2be8ed5a7b8eb9594b)

**Comment by mykola-mokhnach** [comment]
> [35m[WD Proxy][39m Got an unexpected response with status 504: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"

There is some proxy server running on the machine, which is intercepting Appium's requests. Please contact your system administrator to resolve the issue or consider running tests on a clean machine(s).

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
