### ISSUE TITLE
While starting a session by providing app package and app activity info appium is closing the app from background, and also getting logged out from the app when re launching the app.

### ISSUE THREAD

**Issue by arghyamukherjee77** [appium/appium#14575]
![image](https://user-images.githubusercontent.com/53683879/87861985-0ae8cf00-c969-11ea-8008-70b0f8e9757f.png)
![appiumerror](https://user-images.githubusercontent.com/53683879/87862015-3a97d700-c969-11ea-96e4-9b135db7aab9.png)

**Comment by arghyamukherjee77** [comment]
Tried with another app and same scenario occurred

**Comment by pavanbachu06** [comment]
What happens when you are executing that ADB command from the command line?

**Comment by arghyamukherjee77** [comment]
adb devices listing my devices, also I have tried launching chrome of my device its working fine, this scenario is happening with the native apps.

**Comment by pavanbachu06** [comment]
Can you check the appActivity name ? YOu can use _adb shell pm dump PACKAGE_NAME | grep -A 1 MAIN_ for getting the activities

**Comment by arghyamukherjee77** [comment]
Please find below details:
![image](https://user-images.githubusercontent.com/53683879/87862451-dfb4ae80-c96d-11ea-99ec-0f838fc4702c.png)

**Comment by arghyamukherjee77** [comment]
![image](https://user-images.githubusercontent.com/53683879/87862459-fe1aaa00-c96d-11ea-87e9-c0631aaa0246.png)

**Comment by arghyamukherjee77** [comment]
Any help on this? I am stuck because of this.

**Comment by mykola-mokhnach** [comment]
Please fill out the issue reporting form properly and provide the server log. Also it is not clear from the actual issue description what you are trying to achieve. Please describe the actual and the expected results properly.

We cannot help nothing without this information

**Comment by arghyamukherjee77** [comment]
@mykola-mokhnach : Hi mykola, please find the attached file for the details on the server log.
What I want to achieve-
I want to find the locators of the currently focused page, hence I am trying to locate it through Appium inspector and giving the currently focused details alosng with the package info and trying to start the session then I am getting following error on the Appium:
![image](https://user-images.githubusercontent.com/53683879/87879899-11c81e00-ca0b-11ea-8718-ec2a66dfd29c.png)

Also the app which is opened in the devices are automatically getting closed, it has happened with two apps, hence I am unable to use the Appium inspector to locate the elements.
I am new in Appium hence looking for help from your side.

**Comment by arghyamukherjee77** [comment]
[appium-server-logs.txt](https://github.com/appium/appium/files/4944021/appium-server-logs.txt)

Server logs

**Comment by mykola-mokhnach** [comment]
The error is expected. Check the troubleshooting link at https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md and/or talk to your developer to figure out the correct name. Consider setting the `noReset` capability to `true` in case you want to interact with an already running app.

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by arghyamukherjee77** [comment]
Seeting noReset capability to true is not working in my case when I am trying to interact with the already running application.
