### ISSUE TITLE
"org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up" when trying to click/upload image.

### ISSUE THREAD

**Issue by sarabjit-singh** [appium/appium#14576]
## The problem

I am currently on the web-view of an application and trying to upload/click an image from Gallery/Camera. As soon as I click on the upload button I get a popup to choose from camera or gallery at this point the execution hangs and I get the above error after few mins.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1-1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: windows 10 pro
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: Android 9
* Real device or emulator/simulator: Real device (One Plus 5)
* Appium CLI or Appium.app|exe: Appium app

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/sarabjit-singh/7db6d88b395c980b8149240f0169064b

**Comment by mykola-mokhnach** [comment]
> [debug] [Instrumentation] INSTRUMENTATION_RESULT: shortMsg=Process crashed.
> [debug] [Instrumentation] INSTRUMENTATION_CODE: 0
> [WD Proxy] Got response with unknown status: {"code":"ECONNRESET"}
> [debug] [W3C (0953ed4c)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up
> [debug] [W3C (0953ed4c)]     at JWProxy.command (C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:266:13)
> [HTTP] <-- POST /wd/hub/session/0953ed4c-44ea-4230-82d3-039f90ac78b9/elements 500 111286 ms - 559
> [HTTP]
> [debug] [Instrumentation] The process has exited with code 0

The instrumentation process crashed unexpectedly, so the error is expected. You could check the logcat output. Perhaps, it has more details on why the crash happened.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
