### ISSUE TITLE
iOS permissions capability not working with native Xcode 

### ISSUE THREAD

**Issue by jamesvanhorn** [appium/appium#14581]
## The problem

capability.permissions={"blah":{"location-always": "yes"}} was working through Xcode in appium 1.17.0 and 1.17.1. Now with 1.18.0 I get the old error message about applesimutils
```
[debug] [W3C] Encountered internal error running command: Error: applesimutils binary has not been found in your PATH. Please install it ('brew tap wix/brew && brew install wix/brew/applesimutils') to be able to change application permissions
[debug] [W3C]     at execWix (/usr/local/lib/node_modules/appium/node_modules/appium-ios-simulator/lib/permissions.js:41:11)
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.0
* Last Appium version that did not exhibit the issue (if applicable): 1.17.1
* Desktop OS/version used to run Appium: Mac OSX 10.15.5
* Node.js version (unless using Appium.app|exe): v12.14.0
* Npm or Yarn package manager: Npm v6.13.4
* Mobile platform/version under test: iOS 13.5
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI
## Code To Reproduce Issue [ Good To Have ]
Start any session with anything like
```
capability.permissions={"blah":{"location-always": "yes"}}
```

**Comment by mykola-mokhnach** [comment]
Please provide the full server log

**Comment by mykola-mokhnach** [comment]
BTW, is WIX installed on your system?

**Comment by jamesvanhorn** [comment]
Will grab full log. WIX is not installed (and was not when running 1.17.0 or 1.17.1). Previously, it would just not look for/ignore WIX and just set permissions via Xcode automatically.

**Comment by jamesvanhorn** [comment]
Server log: https://gist.github.com/jamesvanhorn/70417aebb694315d72c3cc133fe263d9

**Comment by mykola-mokhnach** [comment]
could you also attach the log from the previous version where it worked?

**Comment by mykola-mokhnach** [comment]
The error is expected. We've recently switched this logic to use native simctl commands, but it turned out these have bugs, so we had to revert back and use WIX, which is stable: https://github.com/appium/appium/issues/14355

**Comment by jamesvanhorn** [comment]
oh that is funny, native Xcode tools were working great for us to grant location/location-always permission, while WIX did not work when we tried to use it in past Appium versions. Bummer. Ill try WIX again

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
