### ISSUE TITLE
After running few tests using appium getting error - Service exited due to SIGABRT

### ISSUE THREAD

**Issue by chirag-farfetch** [appium/appium#14582]
After running few tests using appium getting error- Service exited due to SIGABRT in the simulator logs. I have updated my Xcode and appium but still getting this error. I do not get this error when i reinstall my app using Xcode but get it with appium after running few tests.

```
Jul 20 10:28:03 FFPTD185 com.apple.CoreSimulator.SimDevice.xxxxxx-8DCD-49F0-8A5C-DFE3678FF206[1016] (UIKitApplication:com.xx.xxx.xx[41cc][rb-legacy][1199]): Service exited due to SIGABRT

```

**Comment by KazuCocoa** [comment]
Please fill the issue template out.
I think `showIOSLog: true` and `showXcodeLog: true` in your capability may help

**Comment by mykola-mokhnach** [comment]
Closed as incomplete

**Comment by chirag-farfetch** [comment]
@KazuCocoa , after addding showIOSLog: true and showXcodeLog: true where i can find the logs?

**Comment by KazuCocoa** [comment]
In the Appium logs
