### ISSUE TITLE
Error when run multiple phone at same time

### ISSUE THREAD

**Issue by tangkai123456** [appium/appium#14583]
## The problem
If I run multiple phone at same time.  The webview forward will removed by `Chromedriver.killAll` in `appium-chromedriver`.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.0-beta.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: mac
* Node.js version (unless using Appium.app|exe):10.19.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Android
* Real device or emulator/simulator:  Real device
* Appium CLI or Appium.app|exe:

## Details
https://github.com/appium/appium-chromedriver/pull/183

**Comment by tangkai123456** [comment]
https://github.com/appium/appium-chromedriver/pull/183

**Comment by mykola-mokhnach** [comment]
Closed as fixed
