### ISSUE TITLE
Facing issue regarding context switch in appium i.e. AppiumDriver.setContext()

### ISSUE THREAD

**Issue by rishav-csenitjsr** [appium/appium#14580]
## The problem
For all the basic appium commands like, find element by id, xpath etc, the DEFAULT_REQUEST_TIMEOUT is 240s as can be seen from [here](https://github.com/appium/appium-base-driver/blob/master/lib/jsonwp-proxy/proxy.js#L18). but during app switch context command this default request timeout is not getting honored and appium gets to hang up intermittently for a long time. Is request timeout not implemented for context switch command? @mykola-mokhnach can you help me with this? 

## Environment

* Appium version: 1.16.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: mac
* Node.js version (unless using Appium.app|exe): 10.14.0
* Npm or Yarn package manager:
* Mobile platform/version under test: iPhone 8-13.3
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: appium cli

**Comment by mykola-mokhnach** [comment]
Sorry, I cannot help without the server log

**Comment by mykola-mokhnach** [comment]
Closed because of no response
