### ISSUE TITLE
No real device with udid '00008030-001239D922E8802E'. Looking for simulator

### ISSUE THREAD

**Issue by saurav-lab** [appium/appium#14584]
It was working before, ofsudden with the new version of app, I started getting the failure while running the same script on iOS Simulator.

I was able to launch the Simulator via Appium desktop client, however it was keep on failing via eclipse.

**## Environment**

* Appium version (or git revision) that exhibits the issue: 3.141
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:macOS 10.5
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe:

**## Link to Appium logs**
alling AppiumDriver.createSession() with args: [{"noReset":"true","newCommandTimeout":600,"platformVersion":"13.5","automationName":"XCUITest","bundleId":"com.usbank.OmniMobileApp.dev","platformName":"iOS","udid":"00008030-001239D922E8802E","deviceName":"iPhone 11 Pro","wdaLocalPort":0},null,{"alwaysMatch":{"appium:automationName":"XCUITest","appium:bundleId":"com.usbank.OmniMobileApp.dev","appium:deviceName":"iPhone 11 Pro","appium:newCommandTimeout":600,"appium:noReset":"true","platformName":"ios","appium:platformVersion":"13.5","appium:udid":"00008030-001239D922E8802E","appium:wdaLocalPort":0},"firstMatch":[{}]}]
[BaseDriver] Event 'newSessionRequested' logged at 1595385819062 (22:43:39 GMT-0400 (Eastern Daylight Time))
[Appium] Appium v1.17.1 creating new XCUITestDriver (v3.22.0) session
[BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[BaseDriver] Creating session with W3C capabilities: {
[BaseDriver]   "alwaysMatch": {
[BaseDriver]     "platformName": "ios",
[BaseDriver]     "appium:automationName": "XCUITest",
[BaseDriver]     "appium:bundleId": "com.usbank.OmniMobileApp.dev",
[BaseDriver]     "appium:deviceName": "iPhone 11 Pro",
[BaseDriver]     "appium:newCommandTimeout": 600,
[BaseDriver]     "appium:noReset": "true",
[BaseDriver]     "appium:platformVersion": "13.5",
[BaseDriver]     "appium:udid": "00008030-001239D922E8802E",
[BaseDriver]     "appium:wdaLocalPort": 0
[BaseDriver]   },
[BaseDriver]   "firstMatch": [
[BaseDriver]     {}
[BaseDriver]   ]
[BaseDriver] }
[BaseDriver] Capability 'noReset' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Session created with session id: 92c77cfa-31d0-42e7-bd71-e4293876f9b2
[XCUITest] Current user: 'sxpras7'
[XCUITest] Available devices: 
[XCUITest] No real device with udid '00008030-001239D922E8802E'. Looking for simulator
[XCUITest] {}
[DevCon Factory] Releasing connections for 00008030-001239D922E8802E device on any port number
[DevCon Factory] No cached connections have been found
[BaseDriver] Event 'newSessionStarted' logged at 1595385820311 (22:43:40 GMT-0400 (Eastern Daylight Time))
[W3C] Encountered internal error running command: Error: Unknown device or simulator UDID: '00008030-001239D922E8802E'
[W3C]     at XCUITestDriver.determineDevice (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:804:19)
[W3C] Destroying socket connection
[HTTP] <-- POST /wd/hub/session 500 1294 ms - 685
[HTTP]

**Comment by KazuCocoa** [comment]
> I was able to launch the Simulator via Appium desktop client, however it was keep on failing via eclipse.

So, I guess the Eclipse environment has its own something.
What the result of `xcrun simctl list devices -j` on the Eclipse environment? Can you get the udid in the result?
https://github.com/appium/node-simctl/blob/abfeab8b0d90069489c8d44cff789424561e160b/lib/subcommands/list.js#L105

**Comment by mykola-mokhnach** [comment]
Are you trying to run the test on a real device? Is this device with the given udid visible by Xcode when connected?

**Comment by decolong** [comment]
use command `instruments -s devices` to check whether your device is connected

**Comment by saurav-lab** [comment]
Found the issue, i see UDID was picked up from some properties file.

Seems like it came up with my latest branch. 

Thans for checking quickly.
