### ISSUE TITLE
Appium scripts runs very slow on screen having values changing dynamically with uiAutomator2 on Android.

### ISSUE THREAD

**Issue by shiv-jirwankar** [appium/appium#14594]
## The problem

I am automating one of the screens of my test app. This screen has some numeric values which are changing dynamically. My script is running very slow on this particular screen. After going through the various articles, I got to know that this is the issue with uiAutomator2 itself as the screen elements are not in an idle state. One thing to note is that the numeric values on the screen will keep on changing and hence it will not in the idle state. Is there any way by which I can have my test executed at a good speed with these dynamic elements on the screen?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: Android 10
* Real device or emulator/simulator: Both emulator and real device
* Appium CLI or Appium.app|exe: Appium.exe

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Have you read about [waitForIdleTimeout](https://github.com/appium/appium/issues/14155) setting?

**Comment by shiv-jirwankar** [comment]
@mykola-mokhnach yes, I have read about that. Will setting waitForIdleTimeout value to say 100 solve the speed of execution issue? I guess this timeout will let driver to wait for elements to get idle and then perform the task. In my case, the values on UI will keep on changing in second, so it won't be in idle state.

**Comment by mykola-mokhnach** [comment]
You never know unless you try. I don't know any other possibilities to workaround that limitation.

**Comment by shiv-jirwankar** [comment]
@mykola-mokhnach thank you. Will try this out. :)

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
