### ISSUE TITLE
Android Build-tools 30.0.1 makes ReactNative app crashes after resigning

### ISSUE THREAD

**Issue by trinhpham** [appium/appium#14595]
## The problem

By default, Appium would try to resign the given APK using `apksigner`.
<details><summary>Appium Logs</summary>
<p>

```
[debug] [ADB] Checking app cert for /var/folders/cd/zgfbm06d4jq6glp63_lp51wr0000gn/T/2020624-30208-1ikqlgi.29q7h/gexpenses-1.0.2.apk
[debug] [ADB] Starting apksigner: /Library/Java/JavaVirtualMachines/jdk-11.0.8.jdk/Contents/Home/bin/java -Xmx1024M -Xss1m -jar /Volumes/Data/DevTools/Android/sdk/build-tools/30.0.1/lib/apksigner.jar verify --print-certs /var/folders/cd/zgfbm06d4jq6glp63_lp51wr0000gn/T/2020624-30208-1ikqlgi.29q7h/gexpenses-1.0.2.apk
[debug] [ADB] apksigner stdout: Signer #1 certificate DN: CN=com.logigear.gexpenses, OU=, O=, L=, ST=, C=US
[debug] [ADB] Signer #1 certificate SHA-256 digest: bc2d179bbe654e5f8aa1fc4f255a7abdf7e6b19ab06df4b9da938130e0c1b9ba
[debug] [ADB] Signer #1 certificate SHA-1 digest: 991b4fcd9c74ec7e148eca18e33fc11e80467033
[debug] [ADB] Signer #1 certificate MD5 digest: db4c7371a782b865902c5cefd272772f
[debug] [ADB] 
[debug] [ADB] '/var/folders/cd/zgfbm06d4jq6glp63_lp51wr0000gn/T/2020624-30208-1ikqlgi.29q7h/gexpenses-1.0.2.apk' is signed with a non-default certificate
[ADB] Using 'zipalign' from '/Volumes/Data/DevTools/Android/sdk/build-tools/30.0.1/zipalign'
[debug] [ADB] /var/folders/cd/zgfbm06d4jq6glp63_lp51wr0000gn/T/2020624-30208-1ikqlgi.29q7h/gexpenses-1.0.2.apk' is already zip-aligned. Doing nothing
[debug] [ADB] Signing '/var/folders/cd/zgfbm06d4jq6glp63_lp51wr0000gn/T/2020624-30208-1ikqlgi.29q7h/gexpenses-1.0.2.apk' with default cert
[debug] [ADB] Starting apksigner: /Library/Java/JavaVirtualMachines/jdk-11.0.8.jdk/Contents/Home/bin/java -Xmx1024M -Xss1m -jar /Volumes/Data/DevTools/Android/sdk/build-tools/30.0.1/lib/apksigner.jar sign --key /Users/trinh.pham/.nvm/versions/node/v12.18.2/lib/node_modules/appium/node_modules/appium-adb/keys/testkey.pk8 --cert /Users/trinh.pham/.nvm/versions/node/v12.18.2/lib/node_modules/appium/node_modules/appium-adb/keys/testkey.x509.pem /var/folders/cd/zgfbm06d4jq6glp63_lp51wr0000gn/T/2020624-30208-1ikqlgi.29q7h/gexpenses-1.0.2.apk
```

</p>
</details>

After resigning, my app won't be able to start, logcat shows weird error about x86 vs x64 library compatible.
<details><summary>Logcat</summary>
<p>

```
07-20 21:59:58.433 11002 11002 D SoLoader: Loaded: libfbjni.so
07-20 21:59:58.433 11002 11002 D SoLoader: About to load: libreactnativejni.so
07-20 21:59:58.433 11002 11002 D SoLoader: libreactnativejni.so not found on /data/user/0/com.logigear.gexpenses/lib-main
07-20 21:59:58.433 11002 11002 D SoLoader: libreactnativejni.so found on /data/app/~~eqfeebmPzaOX8IYXzyZx5w==/com.logigear.gexpenses-JOIRs_5g7ILRYi1K8hqLOQ==/lib/x86
07-20 21:59:58.433 11002 11002 D SoLoader: Not resolving dependencies for libreactnativejni.so
07-20 21:59:58.434 11002 11002 W System.err: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/~~eqfeebmPzaOX8IYXzyZx5w==/com.logigear.gexpenses-JOIRs_5g7ILRYi1K8hqLOQ==/lib/x86/libyoga.so" is 64-bit instead of 32-bit
07-20 21:59:58.434 11002 11002 W System.err: 	at java.lang.Runtime.load0(Runtime.java:939)
07-20 21:59:58.434 11002 11002 W System.err: 	at java.lang.System.load(System.java:1628)
07-20 21:59:58.434 11002 11002 W System.err: 	at com.facebook.soloader.SoLoader$1.load(SoLoader.java:19)
07-20 21:59:58.434 11002 11002 W System.err: 	at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:10)
07-20 21:59:58.435 11002 11002 W System.err: 	at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:1)
07-20 21:59:58.435 11002 11002 W System.err: 	at com.facebook.soloader.ApplicationSoSource.loadLibrary(ApplicationSoSource.java:1)
07-20 21:59:58.435 11002 11002 W System.err: 	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:11)
07-20 21:59:58.435 11002 11002 W System.err: 	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:17)
07-20 21:59:58.435 11002 11002 W System.err: 	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:1)
07-20 21:59:58.435 11002 11002 W System.err: 	at com.facebook.soloader.DirectorySoSource.loadDependencies(DirectorySoSource.java:6)
07-20 21:59:58.435 11002 11002 W System.err: 	at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:8)
07-20 21:59:58.435 11002 11002 W System.err: 	at com.facebook.soloader.UnpackingSoSource.loadLibrary(UnpackingSoSource.java:3)
07-20 21:59:58.435 11002 11002 W System.err: 	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:11)
07-20 21:59:58.435 11002 11002 W System.err: 	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:17)
07-20 21:59:58.435 11002 11002 W System.err: 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:19)
07-20 21:59:58.435 11002 11002 W System.err: 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:1)
07-20 21:59:58.435 11002 11002 W System.err: 	at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory(ReactInstanceManagerBuilder.java:2)
07-20 21:59:58.435 11002 11002 W System.err: 	at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:11)
07-20 21:59:58.436 11002 11002 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
07-20 21:59:58.436 11002 11002 W System.err: 	at host.exp.exponent.k.a(RNObject.java:17)
07-20 21:59:58.436 11002 11002 W System.err: 	at host.exp.exponent.k.a(RNObject.java:12)
07-20 21:59:58.436 11002 11002 W System.err: 	at host.exp.exponent.k.b(RNObject.java:6)
07-20 21:59:58.436 11002 11002 W System.err: 	at host.exp.exponent.experience.k.a(ReactNativeActivity.java:78)
07-20 21:59:58.436 11002 11002 W System.err: 	at host.exp.exponent.experience.ExperienceActivity$d.onSuccess(ExperienceActivity.java:1)
07-20 21:59:58.436 11002 11002 W System.err: 	at g.a.a.b.a(Exponent.java:69)
07-20 21:59:58.437 11002 11002 W System.err: 	at host.exp.exponent.experience.ExperienceActivity.l(ExperienceActivity.java:1)
07-20 21:59:58.437 11002 11002 W System.err: 	at host.exp.exponent.experience.k.a(ReactNativeActivity.java:19)
07-20 21:59:58.437 11002 11002 W System.err: 	at host.exp.exponent.experience.ExperienceActivity$c.execute(ExperienceActivity.java:3)
07-20 21:59:58.438 11002 11002 W System.err: 	at host.exp.exponent.v.c.a(AsyncCondition.java:2)
07-20 21:59:58.438 11002 11002 W System.err: 	at host.exp.exponent.experience.ExperienceActivity.b(ExperienceActivity.java:6)
07-20 21:59:58.438 11002 11002 W System.err: 	at host.exp.exponent.experience.ExperienceActivity$b.a(ExperienceActivity.java:1)
07-20 21:59:58.438 11002 11002 W System.err: 	at host.exp.exponent.d.b(AppLoader.java:17)
07-20 21:59:58.438 11002 11002 W System.err: 	at host.exp.exponent.d.d(AppLoader.java:2)
07-20 21:59:58.438 11002 11002 W System.err: 	at host.exp.exponent.d.a(AppLoader.java:1)
07-20 21:59:58.439 11002 11002 W System.err: 	at host.exp.exponent.d$e.onBundleLoaded(AppLoader.java:11)
07-20 21:59:58.439 11002 11002 W System.err: 	at g.a.a.b$b$a.run(Exponent.java:1)
```

</p>
</details>
The issue happens if you update your Android Build-Tools to version 30.0.1 (30.0.0 works fine).
IMO, when the automation name is set to UIAutomator or UIAutomator2, appium should skip the signing process because it isn't necessary. Am I correct? Should I make a pull request for this?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1
* Last Appium version that did not exhibit the issue (if applicable): 1.17.1
* Desktop OS/version used to run Appium: Mac OS 10.15.6
* Node.js version (unless using Appium.app|exe): 12.18.2
* Npm or Yarn package manager: npm: '6.14.7',
* Mobile platform/version under test: Android 10
* Real device or emulator/simulator:  x86 Emulator 
* Appium CLI or Appium.app|exe: CLI

## Details

Above

## Link to Appium logs
Above

## Code To Reproduce Issue [ Good To Have ]
Don't need, just open new session with [this open sourced sample app](https://github.com/LogiGear/GExpense): https://storage.gondolatest.com/public/sample/gexpenses-1.0.2.apk, automationName is UIAutomator2.

_Note_: The APK is built by Expo.io

## Workaround
There are two options:
1. Don't update your Android Build Tools
2. Add `noSign: true` to your capabilities

**Comment by mykola-mokhnach** [comment]
I don't think there is anything we could do about it except of the workarounds you mentioned above. Have you tried to report the issue to Google?

**Comment by mykola-mokhnach** [comment]
> IMO, when the automation name is set to UIAutomator or UIAutomator2, appium should skip the signing process because it isn't necessary. Am I correct? Should I make a pull request for this?

I did not see the full server log, but the signing is only skipped when the target app already has a valid signature. See https://github.com/appium/appium-adb/blob/07ddb4bc1a31955c15d0bab6a726dbd5a29d5af5/lib/tools/apk-signing.js#L255 and https://github.com/appium/appium-uiautomator2-driver/blob/68c2a4919eb840152ac20b5dfb107f9ebe767fb9/lib/driver.js#L495 for more details.

**Comment by trinhpham** [comment]
Thanks for your response @mykola-mokhnach .

> I don't think there is anything we could do about it except of the workarounds you mentioned above. Have you tried to report the issue to Google?

Yes, I've posted an issue to Google at https://issuetracker.google.com/issues/162154417

> > IMO, when the automation name is set to UIAutomator or UIAutomator2, appium should skip the signing process because it isn't necessary. Am I correct? Should I make a pull request for this?
> 
> I did not see the full server log, but the signing is only skipped when the target app already has a valid signature. See https://github.com/appium/appium-adb/blob/07ddb4bc1a31955c15d0bab6a726dbd5a29d5af5/lib/tools/apk-signing.js#L255 and https://github.com/appium/appium-uiautomator2-driver/blob/68c2a4919eb840152ac20b5dfb107f9ebe767fb9/lib/driver.js#L495 for more details.

I've updated the Appium logs above.
As my understanding from reading the source code, `valid signature` means the apk file must be signed by [appium-adb key](https://github.com/appium/appium-adb/tree/master/keys) which would be hard to be applied in real development environment where the organizations/developers prefer using their own keys.

However, the main concern here is: why Appium needs to resign the APK file while using UIAutomator2? Why don't we just remove [this if block](https://github.com/appium/appium-uiautomator2-driver/blob/68c2a4919eb840152ac20b5dfb107f9ebe767fb9/lib/driver.js#L495)? Is there any issues that requires the signing?

**Comment by mykola-mokhnach** [comment]
> As my understanding from reading the source code, valid signature means the apk file must be signed by appium-adb key which would be hard to be applied in real development environment where the organizations/developers prefer using their own keys.

Not really. This depends on the value `requireDefaultCert` argument value. For UiAutomator2 it is false, which means the check passes as soon as `apksigner verify` returns zero exit code.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
