### ISSUE TITLE
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Unknown device or simulator UDID: 'D8C5F45E-0FC9-4396-8043-406D4BEAD55D'

### ISSUE THREAD

**Issue by manojberg** [appium/appium#14591]
## Unable to launch app in iOS simulator

I am able to launch app manually in simulator but not able to launch it using code

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.18.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac Catalina 10.15.3
* Node.js version (unless using Appium.app|exe): 14.5.0
* Npm or Yarn package manager: Npm
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

I run this using eclipse ide please find the log as follows,

### Eclipse Logs

```
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Unknown device or simulator UDID: 'D8C5F45E-0FC9-4396-8043-406D4BEAD55D'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'XMCHEMAC010.corp.xome.com', ip: 'fe80:0:0:0:4df:9252:65bb:3152%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.3', java.version: '1.8.0_162'
Driver info: driver.version: IOSDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Unknown device or simulator UDID: 'D8C5F45E-0FC9-4396-8043-406D4BEAD55D'
    at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:381:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'XMCHEMAC010.corp.xome.com', ip: 'fe80:0:0:0:4df:9252:65bb:3152%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.3', java.version: '1.8.0_162'
Driver info: driver.version: IOSDriver
FAILED CONFIGURATION: @BeforeClass getinstance
```

## Link to Appium logs

https://gist.github.com/manojberg/bd16b7069ba0de4745d5cca2af3f7344

## Code To Reproduce Issue [ Good To Have ]

```
cap = new DesiredCapabilities();
cap.setCapability(MobileCapabilityType.DEVICE_NAME, "D8C5F45E-0FC9-4396-8043-406D4BEAD55D");
cap.setCapability(MobileCapabilityType.UDID, "D8C5F45E-0FC9-4396-8043-406D4BEAD55D");
cap.setCapability(MobileCapabilityType.PLATFORM_VERSION, platformVersion);
cap.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, "100");
cap.setCapability(MobileCapabilityType.BROWSER_NAME, "");
driver = new IOSDriver<>(new URL("http://" + gridURL + ":4444/wd/hub"), cap);
System.out.println("session id is---" + driver.getSessionId());
```

**Comment by KazuCocoa** [comment]
Did your environment have 'D8C5F45E-0FC9-4396-8043-406D4BEAD55D' udid device?
If it had no issue outside Eclipse, maybe it is Eclips environment stuff.

Then, I could not help...

**Comment by mykola-mokhnach** [comment]
Could you also add the output of `xcrun simctl list` command?

**Comment by manojberg** [comment]
> Did your environment have 'D8C5F45E-0FC9-4396-8043-406D4BEAD55D' udid device?
> If it had no issue outside Eclipse, maybe it is Eclips environment stuff.
> 
> Then, I could not help...

Yes my environment has 'D8C5F45E-0FC9-4396-8043-406D4BEAD55D' udid device?  .  I found the did by running instruments -s devices command

**Comment by manojberg** [comment]
> Could you also add the output of `xcrun simctl list` command?
@mykola-mokhnach 
Please find the result  of xcrun simctl list  command

== Device Types ==
iPhone 4s (com.apple.CoreSimulator.SimDeviceType.iPhone-4s)
iPhone 5 (com.apple.CoreSimulator.SimDeviceType.iPhone-5)
iPhone 5s (com.apple.CoreSimulator.SimDeviceType.iPhone-5s)
iPhone 6 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus)
iPhone 6 (com.apple.CoreSimulator.SimDeviceType.iPhone-6)
iPhone 6s (com.apple.CoreSimulator.SimDeviceType.iPhone-6s)
iPhone 6s Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6s-Plus)
iPhone SE (1st generation) (com.apple.CoreSimulator.SimDeviceType.iPhone-SE)
iPhone 7 (com.apple.CoreSimulator.SimDeviceType.iPhone-7)
iPhone 7 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-7-Plus)
iPhone 8 (com.apple.CoreSimulator.SimDeviceType.iPhone-8)
iPhone 8 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-8-Plus)
iPhone X (com.apple.CoreSimulator.SimDeviceType.iPhone-X)
iPhone Xs (com.apple.CoreSimulator.SimDeviceType.iPhone-XS)
iPhone Xs Max (com.apple.CoreSimulator.SimDeviceType.iPhone-XS-Max)
iPhone Xʀ (com.apple.CoreSimulator.SimDeviceType.iPhone-XR)
iPhone 11 (com.apple.CoreSimulator.SimDeviceType.iPhone-11)
iPhone 11 Pro (com.apple.CoreSimulator.SimDeviceType.iPhone-11-Pro)
iPhone 11 Pro Max (com.apple.CoreSimulator.SimDeviceType.iPhone-11-Pro-Max)
iPhone SE (2nd generation) (com.apple.CoreSimulator.SimDeviceType.iPhone-SE--2nd-generation-)
iPad 2 (com.apple.CoreSimulator.SimDeviceType.iPad-2)
iPad Retina (com.apple.CoreSimulator.SimDeviceType.iPad-Retina)
iPad Air (com.apple.CoreSimulator.SimDeviceType.iPad-Air)
iPad mini 2 (com.apple.CoreSimulator.SimDeviceType.iPad-mini-2)
iPad mini 3 (com.apple.CoreSimulator.SimDeviceType.iPad-mini-3)
iPad mini 4 (com.apple.CoreSimulator.SimDeviceType.iPad-mini-4)
iPad Air 2 (com.apple.CoreSimulator.SimDeviceType.iPad-Air-2)
iPad Pro (9.7-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--9-7-inch-)
iPad Pro (12.9-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro)
iPad (5th generation) (com.apple.CoreSimulator.SimDeviceType.iPad--5th-generation-)
iPad Pro (12.9-inch) (2nd generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--12-9-inch---2nd-generation-)
iPad Pro (10.5-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--10-5-inch-)
iPad (6th generation) (com.apple.CoreSimulator.SimDeviceType.iPad--6th-generation-)
iPad (7th generation) (com.apple.CoreSimulator.SimDeviceType.iPad--7th-generation-)
iPad Pro (11-inch) (1st generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--11-inch-)
iPad Pro (12.9-inch) (3rd generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--12-9-inch---3rd-generation-)
iPad Pro (11-inch) (2nd generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--11-inch---2nd-generation-)
iPad Pro (12.9-inch) (4th generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--12-9-inch---4th-generation-)
iPad mini (5th generation) (com.apple.CoreSimulator.SimDeviceType.iPad-mini--5th-generation-)
iPad Air (3rd generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Air--3rd-generation-)
Apple TV (com.apple.CoreSimulator.SimDeviceType.Apple-TV-1080p)
Apple TV 4K (com.apple.CoreSimulator.SimDeviceType.Apple-TV-4K-4K)
Apple TV 4K (at 1080p) (com.apple.CoreSimulator.SimDeviceType.Apple-TV-4K-1080p)
Apple Watch - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-38mm)
Apple Watch - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-42mm)
Apple Watch Series 2 - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-38mm)
Apple Watch Series 2 - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-42mm)
Apple Watch Series 3 - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-3-38mm)
Apple Watch Series 3 - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-3-42mm)
Apple Watch Series 4 - 40mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-4-40mm)
Apple Watch Series 4 - 44mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-4-44mm)
Apple Watch Series 5 - 40mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-5-40mm)
Apple Watch Series 5 - 44mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-5-44mm)
== Runtimes ==
iOS 13.6 (13.6 - 17G64) - com.apple.CoreSimulator.SimRuntime.iOS-13-6 
tvOS 13.4 (13.4 - 17L255) - com.apple.CoreSimulator.SimRuntime.tvOS-13-4 
watchOS 6.2 (6.2.1 - 17T531) - com.apple.CoreSimulator.SimRuntime.watchOS-6-2 
== Devices ==
-- iOS 13.6 --
    iPhone 8 (ACE35CAB-296C-4239-93D2-9837DEA369EE) (Shutdown) 
    iPhone 8 Plus (FAA0591B-D878-48B5-90FD-8839977CC119) (Shutdown) 
    iPhone 11 (51345BE5-29BC-4B9D-A14E-92DA6AAFEAC2) (Shutdown) 
    iPhone 11 Pro (CC76D0D7-BD65-425C-BDD9-5DFE827AE6DC) (Shutdown) 
    iPhone 11 Pro Max (7C43E27A-DDAF-474F-8F65-C3DBA589735D) (Shutdown) 
    iPhone SE (2nd generation) (C9482C0E-3929-4767-8499-5CA8D844D2F9) (Shutdown) 
    iPad Pro (9.7-inch) (D191A979-CCD1-4A78-A958-D327414B43C9) (Shutdown) 
    iPad (7th generation) (088B26D4-1395-49DA-BF8A-516417E70A90) (Shutdown) 
    iPad Pro (11-inch) (2nd generation) (41429412-E237-4635-9FD1-7C8DFA3801FC) (Shutdown) 
    iPad Pro (12.9-inch) (4th generation) (0237BB44-0FE5-4AD9-903A-0BF86B87D4C0) (Shutdown) 
    iPad Air (3rd generation) (43CE0889-E968-462E-9651-0833384030DF) (Shutdown) 
-- tvOS 13.4 --
    Apple TV (BDABBD44-0261-4D11-9FF5-D5051C821C77) (Shutdown) 
    Apple TV 4K (088389C8-CFCC-4855-B71A-2C40D5F1CD17) (Shutdown) 
    Apple TV 4K (at 1080p) (F17EE64E-D46E-441B-AB43-D0F41B8A3340) (Shutdown) 
-- watchOS 6.2 --
    Apple Watch Series 4 - 40mm (FB3244A6-034D-4490-AA00-38B8CAC69168) (Shutdown) 
    Apple Watch Series 4 - 44mm (5109A246-92AA-4478-B5FF-D142E1EAA13B) (Shutdown) 
    Apple Watch Series 5 - 40mm (D65E3FF4-073C-44B4-AC68-FF760C120CB7) (Shutdown) 
    Apple Watch Series 5 - 44mm (F29D6871-6F09-4C51-9484-578B7DCC0666) (Shutdown) 
-- Unavailable: com.apple.CoreSimulator.SimRuntime.iOS-13-0 --
    iPhone 8 Plus (452DE1D3-EBBA-471C-B2F4-5BD68FCD08AD) (Shutdown) (unavailable, runtime profile not found)
    iPhone 11 (DE701D0B-17EB-4856-BE1A-00C7D717C9D3) (Shutdown) (unavailable, runtime profile not found)
    iPhone 11 Pro (29A4BAB7-C1F0-48C8-8CB5-D3A0E86851CA) (Shutdown) (unavailable, runtime profile not found)
    iPhone 11 Pro Max (2A204C18-1A7C-47C9-A525-3FB848D4D31E) (Shutdown) (unavailable, runtime profile not found)
    iPad Pro (9.7-inch) (AECB323C-D6A1-4ADD-B5EB-8BAECB00EAA2) (Shutdown) (unavailable, runtime profile not found)
    iPad Pro (11-inch) (7B3736C5-D937-4DE2-B18E-9B89C47B5D38) (Shutdown) (unavailable, runtime profile not found)
    iPad Pro (12.9-inch) (3rd generation) (A4C02AC5-3229-4F90-BFCD-9B0CE87A31C0) (Shutdown) (unavailable, runtime profile not found)
    iPad Air (3rd generation) (81A89D17-13A5-4648-8184-F05023276A22) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.iOS-13-3 --
    iPhone 8 (A20B31C1-1DFD-4E6B-95FE-56646CF01891) (Shutdown) (unavailable, runtime profile not found)
    iPhone 8 Plus (B969D616-2728-4B3D-A589-868E3427CF9F) (Shutdown) (unavailable, runtime profile not found)
    iPhone 11 (05F2B709-8A16-44C2-9FC8-D25A3C48F726) (Shutdown) (unavailable, runtime profile not found)
    iPhone 11 Pro (6623AF73-780B-423B-BA09-58E99218B394) (Shutdown) (unavailable, runtime profile not found)
    iPhone 11 Pro Max (FEB3E46B-4CAD-4915-BC1A-4675B40E825A) (Shutdown) (unavailable, runtime profile not found)
    iPad Pro (9.7-inch) (5C259C93-38F6-4783-A982-F19F5E45C60B) (Shutdown) (unavailable, runtime profile not found)
    iPad (7th generation) (3FF9CCF8-0101-4FA1-AFC3-66FCB72164C6) (Shutdown) (unavailable, runtime profile not found)
    iPad Pro (11-inch) (B3007027-F4A0-4219-B69B-6DF6F6CFF5E3) (Shutdown) (unavailable, runtime profile not found)
    iPad Pro (12.9-inch) (3rd generation) (21BDF062-61D0-4E03-B580-791AF344284E) (Shutdown) (unavailable, runtime profile not found)
    iPad Air (3rd generation) (CB63B210-22CC-45F4-A8BE-E9939FF2A2F9) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.iOS-13-4 --
    iPhone 8 (29FDF9DA-47F7-4349-8CB5-DB8DDFAF1969) (Shutdown) (unavailable, runtime profile not found)
    iPhone 8 Plus (253E1399-2BDD-4E91-B2E2-748B74AFEFDD) (Shutdown) (unavailable, runtime profile not found)
    iPhone 11 (119BDC7E-D16D-4E67-A1AF-0E28893A1A5E) (Shutdown) (unavailable, runtime profile not found)
    iPhone 11 Pro (155A6223-4001-41DF-90EA-6119D2FC276A) (Shutdown) (unavailable, runtime profile not found)
    iPhone 11 Pro Max (74807CB7-FFA5-4119-B18C-E6770893A9E3) (Shutdown) (unavailable, runtime profile not found)
    iPhone SE (2nd generation) (653B6175-4CA3-467D-83CD-C1F309CA451C) (Shutdown) (unavailable, runtime profile not found)
    iPad Pro (9.7-inch) (D780BDB4-7BF7-4DF6-9BC0-867E55A21158) (Shutdown) (unavailable, runtime profile not found)
    iPad (7th generation) (2885404C-F233-4357-9D01-136CF05A0EC8) (Shutdown) (unavailable, runtime profile not found)
    iPad Pro (11-inch) (C61F94F7-5E60-4761-BBBE-BD1704F2F97E) (Shutdown) (unavailable, runtime profile not found)
    iPad Pro (12.9-inch) (3rd generation) (A8D2FA45-A957-4C3F-996C-8A02CBFC2145) (Shutdown) (unavailable, runtime profile not found)
    iPad Pro (11-inch) (2nd generation) (D06577A9-A266-46E7-AB14-658D54F1D597) (Shutdown) (unavailable, runtime profile not found)
    iPad Pro (12.9-inch) (4th generation) (7468728A-0B9F-439D-B76D-C01FB44180E9) (Shutdown) (unavailable, runtime profile not found)
    iPad Air (3rd generation) (1A4DCB52-56B8-428A-9E48-105F77DC5713) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.iOS-13-5 --
    iPhone 8 (65367AB8-0E76-4E6E-BD43-217EA2B49C99) (Shutdown) (unavailable, runtime profile not found)
    iPhone 8 Plus (6E74B377-E316-4CC3-8A46-78C262FFFC75) (Shutdown) (unavailable, runtime profile not found)
    iPhone 11 (9B261294-FDE5-45E6-BE7D-D378E6EDE700) (Shutdown) (unavailable, runtime profile not found)
    iPhone 11 Pro (1BC12C89-D6E0-4271-894E-04096AA52A3A) (Shutdown) (unavailable, runtime profile not found)
    iPhone 11 Pro Max (EC0CA3E7-7ECA-4C44-8ADB-36CAD2159CBB) (Shutdown) (unavailable, runtime profile not found)
    iPhone SE (2nd generation) (E1983EB0-3526-44ED-8289-68381F2B8294) (Shutdown) (unavailable, runtime profile not found)
    iPad Pro (9.7-inch) (446298A5-A2B1-4534-8D7C-FE9C1FF4956C) (Shutdown) (unavailable, runtime profile not found)
    iPad (7th generation) (1235553C-CEC9-44D7-99B7-BA33F57818D7) (Shutdown) (unavailable, runtime profile not found)
    iPad Pro (11-inch) (09D4A8F5-7298-4060-8D58-0D63DAF30FF8) (Shutdown) (unavailable, runtime profile not found)
    iPad Pro (12.9-inch) (3rd generation) (90EA14C1-A703-45DD-A485-B976974D293D) (Shutdown) (unavailable, runtime profile not found)
    iPad Pro (11-inch) (2nd generation) (F151ABD1-80FB-4DBE-8FED-2089BDDA9BBB) (Shutdown) (unavailable, runtime profile not found)
    iPad Pro (12.9-inch) (4th generation) (3E5347FE-EA7E-4CEC-A123-F591389E7B3F) (Shutdown) (unavailable, runtime profile not found)
    iPad Air (3rd generation) (8C73273F-9991-4E89-93EB-B5736FBE048D) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.tvOS-13-0 --
    Apple TV (85D9CF12-08CC-468C-AD99-1E7283F62132) (Shutdown) (unavailable, runtime profile not found)
    Apple TV 4K (EBD9025B-6029-4154-9E90-E4A49651DF8B) (Shutdown) (unavailable, runtime profile not found)
    Apple TV 4K (at 1080p) (1DAA7047-6DCD-43EE-9411-5D026647C0F0) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.tvOS-13-3 --
    Apple TV (6722730F-098C-4043-8709-2B179F40F079) (Shutdown) (unavailable, runtime profile not found)
    Apple TV 4K (1EEA8D94-9411-4FAE-BCAF-CBF1D3174513) (Shutdown) (unavailable, runtime profile not found)
    Apple TV 4K (at 1080p) (D7CBEAE9-5781-44FF-B902-49FE243F9E2C) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.watchOS-6-0 --
    Apple Watch Series 4 - 40mm (E81B8C10-EA0E-4164-A90F-F9A115FE3467) (Shutdown) (unavailable, runtime profile not found)
    Apple Watch Series 4 - 44mm (C8155131-F740-45C4-B119-A351AB21C8A1) (Shutdown) (unavailable, runtime profile not found)
    Apple Watch Series 5 - 40mm (B21233A4-69F0-4AC1-A20E-9BA1DBCC31B2) (Shutdown) (unavailable, runtime profile not found)
    Apple Watch Series 5 - 44mm (F9F07D0B-A413-4E75-8FC5-F9B3ACBF2DC2) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.watchOS-6-1 --
    Apple Watch Series 4 - 40mm (069E88ED-D3C3-41B9-A226-086C4ECEC052) (Shutdown) (unavailable, runtime profile not found)
    Apple Watch Series 4 - 44mm (D76E8F30-1AAD-4F6B-9A06-7F6329C1B9F5) (Shutdown) (unavailable, runtime profile not found)
    Apple Watch Series 5 - 40mm (3EF4EC62-A172-4ED4-AB27-01ADCA90DCA0) (Shutdown) (unavailable, runtime profile not found)
    Apple Watch Series 5 - 44mm (0CE8E29C-8B5B-4889-B2BF-6D624686F328) (Shutdown) (unavailable, runtime profile not found)
== Device Pairs ==
52078575-43B7-4578-84F7-4EF99474A787 (active, disconnected)
    Watch: Apple Watch Series 5 - 40mm (D65E3FF4-073C-44B4-AC68-FF760C120CB7) (Shutdown)
    Phone: iPhone 11 Pro (CC76D0D7-BD65-425C-BDD9-5DFE827AE6DC) (Shutdown)
BE740B9C-42DD-4785-8088-4A14436EE3A6 (active, disconnected)
    Watch: Apple Watch Series 5 - 44mm (F29D6871-6F09-4C51-9484-578B7DCC0666) (Shutdown)
    Phone: iPhone 11 Pro Max (7C43E27A-DDAF-474F-8F65-C3DBA589735D) (Shutdown)
BE5F1FAB-C988-4A87-A354-579D12BB93AA (unavailable)
    Watch: Apple Watch Series 5 - 44mm (F9F07D0B-A413-4E75-8FC5-F9B3ACBF2DC2) (Shutdown)
    Phone: iPhone 11 Pro (29A4BAB7-C1F0-48C8-8CB5-D3A0E86851CA) (Shutdown)
E3B07BAD-849F-44DA-879C-1506AF13DAB2 (unavailable)
    Watch: Apple Watch Series 5 - 40mm (3EF4EC62-A172-4ED4-AB27-01ADCA90DCA0) (Shutdown)
    Phone: iPhone 11 Pro (6623AF73-780B-423B-BA09-58E99218B394) (Shutdown)
0396F7A4-63BC-493D-9486-8D39EE9A6C6C (unavailable)
    Watch: Apple Watch Series 5 - 44mm (0CE8E29C-8B5B-4889-B2BF-6D624686F328) (Shutdown)
    Phone: iPhone 11 Pro Max (FEB3E46B-4CAD-4915-BC1A-4675B40E825A) (Shutdown)

**Comment by mykola-mokhnach** [comment]
Unfortunately I don't observe the given udid in the above command output. The error is expected

**Comment by manojberg** [comment]
> Unfortunately I don't observe the given udid in the above command output. The error is expected
@mykola-mokhnach  I found the udid by running instruments -s devices command is that not valid

**Comment by mykola-mokhnach** [comment]
Please use the simctl output to define udid. This is the one, that is used by Appium internally.

**Comment by manojberg** [comment]
> Please use the simctl output to define udid. This is the one, that is used by Appium internally.

@mykola-mokhnach Thank you so much I will this one

**Comment by manojberg** [comment]
This Issue got resolved . Now

**Comment by manojberg** [comment]
> > Please use the simctl output to define udid. This is the one, that is used by Appium internally.
> 
> @mykola-mokhnach Thank you so much I will use this one .

The issue got resolved . Now I am able to launch the app using my code . I used the UDID obtained from 'xcrun simctl list' command which solved the issue
