### ISSUE TITLE
setLocation not changing the location on the emulator / device

### ISSUE THREAD

**Issue by juditraj** [appium/appium#14592]
## The problem

setLocation not changing the location on the emulator / device. The location() call shows the newly set location, but internally the location is not being set, that is verified via custom background service.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.15.1 
* Appium java client version: 6.1.0
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): v12.18.2
* Npm or Yarn package manager: 6.14.5
* Mobile platform/version under test: AVD Emulator - Pixel_2_API_28 (google_apis_playstore [Google Play] (API level 28))
* Real device or emulator/simulator: emulator (also tried in browserstack cloud real devices)
* Appium CLI or Appium.app|exe: CLI
* Appium settings app version: 2.14.2

## Details

setLocation not changing the location on the emulator.
Code for setting the location.		

Location location = new Location(28.767659, 77.156085, 10);
androidDriver.setLocation(location);

code for getting the location 
androidDriver.location();
output:
Latitude: 28.767659, Longitude: 77.156085, Altitude: 0.0

But we have a custom background service that fetches the device location and when we observe via log, in the service, we are not seeing this location that is being set via appium. 

## Link to Appium logs

[Appium Server Log GIST](https://gist.github.com/juditraj/9c39e57111237b49b98d52ee05e36f10) 

## io.appium.settings dump

The setting app dump shows, the  android.permission.ACCESS_MOCK_LOCATION is not being enabled.

[Settings app dump Log GIST](https://gist.github.com/juditraj/97c231130de58b177bdaa153b465b295)

**Comment by mykola-mokhnach** [comment]
Please use the most recent server version

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by juditraj** [comment]
Hey @mykola-mokhnach, 
Sorry for the delayed response. I tried with the latest appium server and still problem not solved.
Please let me know, what further details you need from my end, so that we can sort it out.

This is my updated environment.
Node Version: 12.18.3
NPM Version: 6.14.7
Appium Version: 1.18.0

Not getting the updated location.

**Comment by mykola-mokhnach** [comment]
Please provide the server log and the logcat output

**Comment by juditraj** [comment]
Updated Appium Server and Logcat logs:
Node Version: 12.18.3
NPM Version: 6.14.7
Appium Version: 1.18.0
[GeoLocation Appium Server Log GIST](https://gist.github.com/juditraj/4c473ac490505c9c13164a5ee2d6a4ac)
[GeoLocation Logcat Log GIST](https://gist.github.com/juditraj/0edd1ced40ec5f9be926d0d7ea6dd1cd)

**Comment by mykola-mokhnach** [comment]
try to switch to native context before issuing the setLocation command. Currently it is only set to the target webview, which means that the location is not changed per device.

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by juditraj** [comment]
Hi @mykola-mokhnach thank you so much.
Switching to native context before issuing the setLocation command worked.
