### ISSUE TITLE
Appium1.7.1_iOS Simulator keyboard not working

### ISSUE THREAD

**Issue by saurav-lab** [appium/appium#14590]
## The problem

it's showing the on screen keyboard but failed to take input. when I press Command+Shift+K followed by Command+k at the text screen, then only it works for that session.

Next time, I had to repeat the same process when the app was launched for another user.

it's really frustrating as none of website or forum has solid answer for this one. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macoS
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe:

Error Domain=com.facebook.WebDriverAgent Code=1 "The on-screen keyboard must be present to send keys" UserInfo={NSLocalizedDescription=The on-screen keyboard must be present to send keys}
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'WNMMN14GLY8E0N1', ip: '2601:c6:c103:5650:cd18:3e5a:804c:b816%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.5', java.version: '1.8.0_162'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities {automationName: XCUITest, browserName:

**Comment by saurav-lab** [comment]
The process has become manual for me :-)

**Comment by mykola-mokhnach** [comment]
This error is coming from XCTest, which we cannot control. Please report it to Apple.

As a workaround try to run your tests on a clean machine and/or upgrade the Appium server to the most recent version.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
