### ISSUE TITLE
Appium not finding WPF elements

### ISSUE THREAD

**Issue by evansct** [appium/appium#14609]
## The problem

I am working on a team that is creating a WPF application, and I am tasked with doing automated testing on it. For the most part I haven't have any issues at all and work has gone smoothly. However, there are a few elements that appium isn't able to see. Most of them are TextBlock elements, where I am trying to grab the text so that I can confirm that the correct element is selected. When I look inside the visual tree on Appium Desktop, I see this: 
![image](https://user-images.githubusercontent.com/31485935/88707719-ac49f080-d0e0-11ea-9afc-ba33f33948ba.png).

However the actual application also has a TextBlock that should be above and below the ComboBox. 
![image](https://user-images.githubusercontent.com/31485935/88708780-2fb81180-d0e2-11ea-9e7f-6ee4ba6857b3.png)
Even though I have the TextBlocks ID'd in my code, it gives me an exception that says: `OpenQA.Selenium.WebDriverException: An element could not be located on the page using the given search parameters.` 

The elements just seem to be completely invisible to Appium.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1
* Desktop OS/version used to run Appium: Windows 10
* Type of application under test: WPF 

## Code To Reproduce Issue

```
var partNumDropdownTxt = partNumTile.FindElementByAccessibilityId("PartNumberDesc").Text;
```

This is what I'm using to find the element, which exists, but is not seen by appium, leading to the exception given above.

**Comment by KazuCocoa** [comment]
Could you report it to https://github.com/microsoft/WinAppDriver ?
It looks the WAD side issue

**Comment by evansct** [comment]
@KazuCocoa I can definitely do that! I'm curious as to how you can tell that though, just so I know for future things. How can/do you tell when it's Appium or WAD?

**Comment by KazuCocoa** [comment]
Basically Appium works as a proxy to WAD. Commands such as find element, click etc are basically WAD stuff.

Only https://github.com/appium/appium-windows-driver/blob/bd16574dcc097b426a5acc9c1c3fee1622471379/lib/driver.js#L7-L9 commands are related to Appium itself.
Or communication protocol stuff between Appium and WAD. e.g. W3C/MJSONWP protocol stuff
