### ISSUE TITLE
Click does not execute sometimes, but without throwing StaleElementReferenceException

### ISSUE THREAD

**Issue by senchi** [appium/appium#14603]
## The problem

We're writing E2E tests for an Android app, and we noticed that every now and then we're not able to find an element by ID. After further investigation, we've found that the element is not found because the previous screen is still shown on the device, which means that the click on the previous screen did not execute correctly. There are some delays involved as the app is fetching data from the API and re-rendering the screen. We've implemented handling for the StaleElementReferenceException, but still some clicks are being just swallowed, as if they never happened.
Its all in the timing it seems, the screen re-render has to come at pretty much the same time as the click event.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS 10.15.5 and also on Windows 10
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: Android 6.0 and Android 8.0
* Real device or emulator/simulator: LG G4 and LG G6
* Appium CLI or Appium.app|exe: 

## Details

Its all in the timing it seems, the screen re-render has to come at pretty much the same time as the click event.
This makes it difficult to reproduce, so I've built this code base with a sample Android app and a sample Appium testng project to demonstrate. You can play with the numbers in the Android RandomDelay class in Android, or in the TestClickCounter in fluentWait in the Appium testng project.
The sample app and testng project: https://github.com/genijalno-ba/appium-click-test

## Link to Appium logs

https://gist.github.com/senchi/a8cbd6858393a07b97232c5233258699

## Code To Reproduce Issue [ Good To Have ]

https://github.com/genijalno-ba/appium-click-test

**Comment by mykola-mokhnach** [comment]
I assume it is an issue of UiAutomator framework itself, but it is hardly possible to neither confirm nor reject that assumption. I would try to use Espresso driver as a possible alternative

**Comment by senchi** [comment]
@mykola-mokhnach , I've changed the value in my capabilities for the automationName to "Espresso", but when I run it like this I've got two errors:
1. Easy to solve, I've had to add the "INTERNET" permission to my android app manifest
2. Kinda stuck with this strange error where a Resource is missing! Here's the appium log: https://gist.github.com/senchi/fc882ed5e675af91b6eeab1da3311983

I'm reading this thread which seems related, but I'm afraid I don't understand exactly what is required: https://github.com/appium/appium-espresso-driver/issues/449

What is it exactly I have to do to get my example running with Espresso?

Thanks

**Comment by mykola-mokhnach** [comment]
Unfortunately the configuration there depends on the application under test and is different for different cases. It might be that excluding/including some dependencies from the resulting test package fixes the missing resource issue, but I cannot advice much on that topic. Perhaps @uterator or @glebplotnikovring could tell more if they have time.

**Comment by amedvedjev** [comment]
@senchi reconfigure your test in following sequence:
1) wait some screen loaded. all screens should have unique elements.
2) if you need some data on screen to appear before tap add this into screen loaded check.

we had similar problem. while app loads some elements tap does not work. this reproducing also with manual try. automation just makes it too fast. adding isSomeScreenLoaded + wait load some elements on 1-2 our screens solves all similar problems.

**Comment by senchi** [comment]
@amedvedjev , yeah, adding different waits and retries (which we do :) ) helps to overcome the immediate problem, but doesn't solve the issue at hand and makes things often really complex.

@mykola-mokhnach  it would probably help if I could get my [example app](https://github.com/genijalno-ba/appium-click-test) to work with Espresso. It is a small app and it would help me get started with Appium+Espresso.
Also, Espresso is just for Android Testing, right? I.e. you can't test iOS, or even React Native iOS, right?
If so, then Appium+UIAutomator2 would still be my first choice.. if it works correctly that is!
I mean, most apps do what we do, fetch some data, re-render the screen, etc... right?

**Comment by mykola-mokhnach** [comment]
For react stuff in general I would highly recommend to use Hybrid automation approach for both Android and iOS. The app structure exposed to the accessibility and the one exposed to the remote web debugger are two completely different things (where the first one is really poor and suboptimal). 

Your particular case looks more like a race condition to me. Most likely the upstream accessibility framework does its job properly, locates elements and sends the events to them. Although, the downstream app code is not ready to process these events. In such case you'd need some synchronisation primitive, so by checking that you know exactly when to start the interaction. 

For example, one could start application logs monitoring while the app does data exchange with the backend and as soon as there is a record about the data exchange Is completed and the UI is ready to handle it the automation script could resume its interactions.

**Comment by senchi** [comment]
> For example, one could start application logs monitoring while the app does data exchange with the backend and as soon as there is a record about the data exchange Is completed and the UI is ready to handle it the automation script could resume its interactions.

Good idea! That sounds like a neat trick to get more precision, as opposed to just waiting few seconds and hoping for the best :)

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
