### ISSUE TITLE
UIAutomator2 TouchAction. Expected int, Getting decimal.

### ISSUE THREAD

**Issue by sme81** [appium/appium#14601]
Trying to use TouchAction with Appium 1.18.0 throws the following error:

CODE

`new TouchAction((AppiumDriver) getDriver()).longPress(ElementOption.element(element)).release().perform();`

ERROR:

`org.openqa.selenium.InvalidArgumentException: com.google.gson.JsonSyntaxException:java.lang.NumberFormatException: Expected an int but was 797.5 at line 1 column 44 path $.params.y`

Has worked from version 1.15 to 1.17.1. Upgrading to 1.18.0 causes the above above issue.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.0
* Last Appium version that did not exhibit the issue (if applicable): 1.17.1
* Desktop OS/version used to run Appium: MacOS
* Node.js version (unless using Appium.app|exe): 6.14.7
* Npm or Yarn package manager: Npm
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: CLI

**Comment by mykola-mokhnach** [comment]
Please try https://github.com/appium/appium-uiautomator2-server/pull/372

In general it is preferred to use W3C touch actions.

**Comment by mykola-mokhnach** [comment]
@sme81 Did the fix work for you?

**Comment by sme81** [comment]
haven't had a chance to check yet. Will try to get tested by end of day

**Comment by mykola-mokhnach** [comment]
the patch has been merged to appium@beta

**Comment by sme81** [comment]
only got onto this today, fix in beta looks to be working. thanks
