### ISSUE TITLE
iOS Keyboard will appear but page source does not pick it up and send keys will fail

### ISSUE THREAD

**Issue by brummetj** [appium/appium#14618]
## The problem

Hello! I'm running into an issue where I'm unable to get passed a certain provisioning step for our automation. The app will bring up an embedded webview on the iOS device. From here we are trying to simply send keys for the username and password. But appium will fail with the error message 
```
selenium.common.exceptions.InvalidElementStateException: Message: Error Domain=com.facebook.WebDriverAgent Code=1 "The on-screen keyboard must be present to send keys" UserInfo={NSLocalizedDescription=The on-screen keyboard must be present to send keys}
```
The weird thing is that the keyboard is present on the screen, and we can watch it appear but the page source ends up blank when printing it after we get the keyboard to appear. It was working and can work sometimes and sometimes it doesn't.... recently we've been seeing this happen every run lately.

Any ideas? 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.0
* Last Appium version that did not exhibit the issue (if applicable): Not sure
* Desktop OS/version used to run Appium: Mac OSX Catalina 10.15
* Node.js version (unless using Appium.app|exe): 6.13.1
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS 13.4.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: appium cli

## Link to Appium logs

Server logs, page source, and screenshot here... 

https://gist.github.com/brummetj/3918d86b01cad610e25029ad61e20362

**Comment by mykola-mokhnach** [comment]
Please use the most recent Appium version. Apple has changed keyboard behaviour for secure fields since iOS 13.

**Comment by mykola-mokhnach** [comment]
Also, it makes sense to switch into web context while working with web views

**Comment by brummetj** [comment]
@mykola-mokhnach I went ahead and updated to appium version 1.18.0 and now im receiving a new error when trying to send keys to this ID
```
selenium.common.exceptions.InvalidElementStateException: Message: Error Domain=com.facebook.WebDriverAgent Code=1 "'"XFINITY ID" Other' is not ready for a text input. Neither the accessibility element itself nor its accessible descendants have the input focus" UserInfo={NSLocalizedDescription='"XFINITY ID" Other' is not ready for a text input. Neither the accessibility element itself nor its accessible descendants have the input focus}
```

I also checked and i suppose i was wrong about the embedded webview, when i grab the contexts via `driver.contexts` only `['NATIVE_APP']` prints out in the array. 

Any ideas how to move forward? I was able to get the cursor to focus on the text input by trying to just click on sign-in first, then it brings up the keyboard but the page source is still not showing the keyboard elements in the XML

**Comment by brummetj** [comment]
@mykola-mokhnach feel free to close this out. I was able to pull it up on the UI inspector you guys provide, it appears that the actual IDs are reflected as unicode characters, and using the xpath provided with the UI inspector will work, instead of using the IDs.

**Comment by gunjankapoor1985** [comment]
Hi, I am facing the same issue.
my device details are :
 iOS 13.1.2  , Mac OSX Catalina 10.15.6 , Appium 1.17.1. , npm package manager .
Application : Native app. 
Please suggest.

Error : 

org.openqa.selenium.InvalidElementStateException: Error Domain=com.facebook.WebDriverAgent Code=1 "The on-screen keyboard must be present to send keys" UserInfo={NSLocalizedDescription=The on-screen keyboard must be present to send keys}

**Comment by brummetj** [comment]
hey @gunjankapoor1985 ... go ahead and update your appium 1.18.0, then pull up the UI inspector and grab the element Xpath that the UI inspector gives you. I was using the ID's and that was causing the issue, xpaths and the latest appium version seemed to work! Hope that will help...

**Comment by gunjankapoor1985** [comment]
Hi @brummetj  : My same scripts are working fine on iOS 12 for older version of Appium. Issue is not with element as I already check  via Appium desktop and element is working / visible for iOS 12.

**Comment by gunjankapoor1985** [comment]
If issue is with appium version, them I will update but for same version, I am able to use send keys at some other place as well.
Do we need to add some special capabilities ?

**Comment by brummetj** [comment]
Yes this is a iOS 13 issue, just update the appium version and look into using the Xpaths instead of the ID. No special capability needed.

**Comment by jitenderbhatia-tech** [comment]
@gunjankapoor1985 - I faced a similar issue on my iOS device and it was throwing the same error as discussed in chain comments. The solution I figured out is 
1. We need to tap that field with the help of coordinates using locators, as tapping only with coordinates won't help as page layout always changes.
 
Use like this:-
WebElement element = findElement(locator);
		tapByCoordinates(element.getLocation().getX()+(element.getSize().width/2), element.getLocation().getY()+(element.getSize().height/2);
2. Now enter your text using sendkeys(textToType)

Error faced before solution:-
org.openqa.selenium.InvalidElementStateException: Error Domain=com.facebook.WebDriverAgent Code=1 "The on-screen keyboard must be present to send keys" UserInfo={NSLocalizedDescription=The on-screen keyboard must be present to send keys}

Please comment if someone resolves their conflicts/errors using the above workaround. Thanks!
