### ISSUE TITLE
An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8263

### ISSUE THREAD

**Issue by ofirya88** [appium/appium#14610]
## The problem
Hi,
I am running automation on emulators farm (12 emulators) and i got this error message ("An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8263") durring a lot of tests in the middle of the run . 

I made a workaround to recover the device when i face that error message by reboot and init android driver again but i didn't found the root cause of that issue . 

## Environment

* Appium version (or git revision) that exhibits the issue:  1.17.1
* Desktop OS/version used to run Appium: Ubuntu 18.04.01 linux 
* Node.js version (unless using Appium.app|exe): v 12.18.2
* Npm or Yarn package manager: 5.3.0
* Mobile platform/version under test: emulators - OS 8/9 
* Real device or emulator/simulator: emulators

## Link to Appium logs
[userDemographicSelectionAgeQuestionWithLongText_appium_log.log](https://github.com/appium/appium/files/4993519/userDemographicSelectionAgeQuestionWithLongText_appium_log.log)

**Comment by mykola-mokhnach** [comment]
Also it makes sense to update Appium to the most recent version first

**Comment by mykola-mokhnach** [comment]
Closed because of no response
