### ISSUE TITLE
WebDriverAgent session is null in ios device

### ISSUE THREAD

**Issue by sunshinelulu** [appium/appium#14619]
## The problem
WebDriverAgent session is null when i use the WebDriverAgent project maintaned by appium.
`{
  "value" : {
    "message" : "WebDriverAgent is ready to accept commands",
    "state" : "success",
    "os" : {
      "testmanagerdVersion" : 26,
      "name" : "iOS",
      "sdkVersion" : "12.2",
      "version" : "12.4"
    },
    "ios" : {
      "simulatorVersion" : "12.4",
      "ip" : "172.23.60.232"
    },
    "ready" : true,
    "build" : {
      "time" : "Aug  4 2020 14:11:30",
      "productBundleIdentifier" : "com.facebook.WebDriverAgentRunner"
    }
  },
  "sessionId" : null
}`

## Environment

* ios version : 12.1
* xocode version : 10.3
* appium webdriveragent version : latest

**Comment by mykola-mokhnach** [comment]
Sorry, I don't understand what the issue is. Please describe the actual and the expected results properly plus steps to reproduce. Also WDA is operating in W3C mode, where sessionId value is not required by the standard and could have any value.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
