### ISSUE TITLE
App is unresponsive if large table is render in UITableView controller 

### ISSUE THREAD

**Issue by abisen14** [appium/appium#14613]
## The problem

As soon as test lands on a screen that is scrollable and has large set of data to display in UITableView , app hangs/freezes 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Mac OS 10.14.6
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe:

## Details

As soon as test lands on a screen that is scrollable and has large set of data to display in UITableView , app hangs/freezes. I have seen other reporting this problem but havnt seen any solution yet. 

## Link to Appium logs

https://gist.github.com/abisen14/5d336237d8b8c810f325c5a8d8b9fcb2

**Comment by abisen14** [comment]
Actually I will add some more information. I know this is an issue with Third Party tool and probably the way XCUIElement creates tree. What I am looking for is if there is a way I can restrict this element tree creation from WDA side. or any other alternative to solve this problem.

**Comment by mykola-mokhnach** [comment]
There is `snapshotMaxDepth` setting, which might help there. Although, it is mostly used for path-related stuff, like xpath search or XML tree building. Otherwise the lookup is done using native XCTest calls and there is nothing we could possibly do there.

**Comment by abisen14** [comment]
Ahh! Thanks Mykola for your prompt response, I will give snapshotMaxDepth a try. Yes this looks like a issue that would particularly make automating such screens impossible, I see there was a bug opened with Apple long time back but I dont see any action on that. Will also try to see if we can do something from application code side to restrict number of cells getting loaded.
