### ISSUE TITLE
appium module could not read apk files when packged using pkg module

### ISSUE THREAD

**Issue by rsmrahul1** [appium/appium#14615]
## The problem

Used appum module and **packaged it using pkg**. But while running tests, below error occured,

'adb: failed to stat /snapshot/folder/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk: No such file or directory'; Code: '1'

It seems the adb tool could not read the apk file from the package's **snapshot file system**.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.17.1
* Desktop OS/version used to run Appium: Ubuntu 18
* Node.js version (unless using Appium.app|exe): Node 10
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: Appium module

Same issue was asked by someone in pkg module forumn too
https://github.com/vercel/pkg/issues/927

**Comment by mykola-mokhnach** [comment]
Please report the issue to Google, we don't own the adb project and cannot help nothing there.

Closed as not an issue.
