### ISSUE TITLE
Appium Implicit Wait does not work in webview context(hybrid app)

### ISSUE THREAD

**Issue by HavenChen** [appium/appium#14620]
## The problem

Appium implicit wait does not work in webview page, when i tried to find an element that does not exiets in web view page, appium failes immediately without any waiting.

## Environment

* Appium version (or git revision) that exhibits the issue: 1,8
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: window 10  64bit
* Node.js version (unless using Appium.app|exe): 12.13.1
* Npm or Yarn package manager:6.12.1
* Mobile platform/version under test:  Android 5.1
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

script outputs:

contexts: ['NATIVE_APP', 'WEBVIEW_com.ccic.bros']
----start finding element in webview page----
1596528920.8992782
----end finding element in webview page----
1596528920.9262044
Traceback (most recent call last):
  File "C:/Users/LeoCh/PycharmProjects/superAPP/tests/iosTests.py", line 63, in <module>
    driver.find_element_by_id('wrongId').click()
  File "C:\Users\LeoCh\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\LeoCh\AppData\Local\Programs\Python\Python37-32\lib\site-packages\appium\webdriver\webdriver.py", line 284, in find_element
    'value': value})['value']
  File "C:\Users\LeoCh\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\LeoCh\AppData\Local\Programs\Python\Python37-32\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\Users\LeoCh\AppData\Local\Programs\Python\Python37-32\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\Users\LeoCh\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: invalid locator
  (Session info: chrome=77.0.3865.120)

## Link to Appium logs

https://gist.github.com/HavenChen/a20f9d569fe9a8c3616b7b134945b918

## Code To Reproduce Issue [ Good To Have ]

local = 'http://localhost:4723/wd/hub'
driver = webdriver.Remote(
    command_executor=local,
    desired_capabilities=meizu_desired_caps)

time.sleep(10)
contexts = driver.contexts
print('contexts:',contexts)
driver._switch_to.context(contexts[1])

driver.implicitly_wait(20)

try:
    print('----start finding element in webview page----')
    print(time.time())
    driver.find_element_by_id('wrongId').click()
except Exception as EC:
    print('----end finding element in webview page----')
    print(time.time())
    print(traceback.format_exc())

**Comment by mykola-mokhnach** [comment]
Try to set the wait AFTER the context is switched. The wait is applied to the native context in the example above.
Also the server log is needed

**Comment by HavenChen** [comment]
@mykola-mokhnach 
Dear mykola-mokhnach, i have tried set the wait AFTER the context is switched, but same phenomenon,
pls kindly check editted info above and server log here:
https://gist.github.com/HavenChen/a20f9d569fe9a8c3616b7b134945b918
thank you so much.

**Comment by mykola-mokhnach** [comment]
> [info] [35m[W3C (2fa330cb)][39m Driver proxy active, passing request on via HTTP proxy
> [debug] [35m[WD Proxy][39m Matched '/wd/hub/session/2fa330cb-cc1b-41fc-9398-a3653bf336cd/element' to command name 'findElement'
> [debug] [35m[WD Proxy][39m Proxying [POST /wd/hub/session/2fa330cb-cc1b-41fc-9398-a3653bf336cd/element] to [POST http://127.0.0.1:9515/wd/hub/session/0601305bb91ff6745b11e6f99816188d/element] with body: {"using":"id","value":"wrongId"}
> [info] [35m[WD Proxy][39m Got response with status 400: {"value":{"error":"invalid argument","message":"invalid argument: invalid locator\n  (Session info: chrome=77.0.3865.120)","stacktrace":"Backtrace:\n\tOrdinal0 [0x001FEB13+1501971]\n\tOrdinal0 [0x0017F6D1+980689]\n\tOrdinal0 [0x0010765F+489055]\n\tOrdinal0 [0x000A6D0B+93451]\n\tOrdinal0 [0x000C0E00+200192]\n\tOrdinal0 [0x000B7A80+162432]\n\tOrdinal0 [0x000BF93E+194878]\n\tOrdinal0 [0x000B78EB+162027]\n\tOrdinal0 [0x000A0AC7+68295]\n\tOrdinal0 [0x000A1B40+72512]\n\tOrdinal0 [0x000A1AD9+72409]\n\tOrdinal0 [0x00198F37+1085239]\n\tGetHandleVerifier [0x0029D7ED+503293]\n\tGetHandleVerifier [0x0029D580+502672]\n\tGetHandleVerifier [0x002A46AC+531644]\n\tGetHandleVerifier [0x0029DFFA+505354]\n\tOrdinal0 [0x00190606+1050118]\n\tOrdinal0 [0x0019047F+1049727]\n\tOrdinal0 [0x0019AF9B+1093531]\n\tOrdinal0 [0x0019B103+1093891]\n\tOrdinal0 [0x0019A095+1089685]\n\tBaseThreadInitThunk [0x75EA6359+25]\n\tRtlGetAppContainerNamedObjectPath [0x76FF7C24+228]\n\tRtlGetAppContainerNamedObjectPath [0x76FF7BF4+180]\n\t(No symbol) ...
> [debug] [35m[W3C][39m Matched W3C error code 'invalid argument' to InvalidArgumentError

I assume in the recent log above the implicit timeout was set properly, however the lookup failed immediately because of https://github.com/appium/appium/issues/13306

**Comment by HavenChen** [comment]
@mykola-mokhnach
it works when i tried to find a element with css locator, thank you so much.
