### ISSUE TITLE
Chromedriver automatically download is not working properly on Ubuntu

### ISSUE THREAD

**Issue by nguyennguyen6bk** [appium/appium#14629]
## The problem

Can not use Chromedriver from automatically download by Appium. The problem is regarding the access permission after download Chromedriver

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Ubuntu 18.04
* Mobile platform/version under test: Android 9.0
* Real device and emulator/simulator

## Details

**[ChromedriverStorageClient]** Moving the extracted 'chromedriver' to '/tmp/.mount_Appiumz7EA9u/resources/app/node_modules/appium/node_modules/appium-chromedriver/chromedriver/linux/chromedriver_linux64_v84.0.4147.30'
**[Chromedriver]** Cannot synchronize local chromedrivers with the remote storage at https://chromedriver.storage.googleapis.com: EROFS: read-only file system, open '/tmp/.mount_Appiumz7EA9u/resources/app/node_modules/appium/node_modules/appium-chromedriver/chromedriver/linux/chromedriver_linux64_v84.0.4147.30'
**[Chromedriver]** Error: EROFS: read-only file system, open '/tmp/.mount_Appiumz7EA9u/resources/app/node_modules/appium/node_modules/appium-chromedriver/chromedriver/linux/chromedriver_linux64_v84.0.4147.30'
**[Chromedriver]** Error: No Chromedriver found that can automate Chrome '84.0.4147'. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md for more details

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("platformName","Android");
        capabilities.setCapability("deviceName","SAMSUNG Android");
        capabilities.setCapability("platformVersion", "9.0");
        capabilities.setCapability("browserName", "Chrome");
//        capabilities.setCapability("chromedriverExecutable", "/home/nguyen/Documents/Selenium/bin/chromedriver");

        try {
            driver = new AndroidDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);

        } catch (MalformedURLException e) {
            System.out.println(e.getMessage());
        }

**Comment by mykola-mokhnach** [comment]
The error is expected, because the folder where the stuff is mounted is read-only. One could provide a custom path to chrome drivers root folder though by providing the `chromedriverExecutableDir` capability

**Comment by nguyennguyen6bk** [comment]
> The error is expected, because the folder where the stuff is mounted is read-only. One could provide a custom path to chrome drivers root folder though by providing the `chromedriverExecutableDir` capability
Thank you for your reply.
Just one question to clarify why ưe have already mounted chromedriver but we still need to use the custom path
With a custom path, we can run the test smoothly. But from my point of view, Can we use the Chromdriver from the sync folder? Is It more automatically?

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md has all the driver deployment strategies described. Please use Appium forum if you have any additional questions
