### ISSUE TITLE
Suddenly Appium inspector stopped recognizing objects in my mobile app whereas I am able to get the objects from UIAutomator Viewer

### ISSUE THREAD

**Issue by SV3168** [appium/appium#14623]
## The problem

Appium inspector has stopped recognizing objects except the first parent object. For example the Username in the login page is not recognized under edit text category and it is shown as android.view.View.
Previously everything was working fine, but this issue I am facing from 28th July onwards. And this issue is seen only in real android devices. In emulator it is working fine. And with UIAutomator Viewer also I am able to recognize the objects in both real device and emulator. 

AFter I faced the issue with my real device I did the following to trouble shoot. 
-Factory reset my mobile phone and installed the app again
-Uninstalled the appium desktop  1.17 and installed appium desktop 1.18

Getting NoSuch ELement

[WD Proxy] Matched '/element' to command name 'findElement'
[WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8200/wd/hub/session/7c207ee4-8818-4146-a7ba-9ae6d2d5b986/element] with body: {"strategy":"xpath","selector":"//android.widget.EditText[@index = '0']","context":"","multiple":false}
[WD Proxy] Got response with status 404: {"sessionId":"7c207ee4-8818-4146-a7ba-9ae6d2d5b986","value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters","stacktrace":"io.appium.uiautomator2.common.exceptions.ElementNotFoundException: An element could not be located on the page using the given search parameters\n\tat io.appium.uiautomator2.handler.FindElement.findElement(FindElement.java:96)\n\tat io.appium.uiautomator2.handler.FindElement.safeHandle(FindElement.java:71)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:41)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:257)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:247)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:50)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerCont...
[W3C] Matched W3C error code 'no such element' to NoSuchElementError
[BaseDriver] Waited for 14754 ms so far

## Environment

Appium version 1.18.
OS Version : Windows 10
Mobile platform : Android 10
Real device

In the above scenario I am trying to find a Username box in login page.

I am attaching screenshot of UI automator Viewer and Appium inspector
![Appium inspector](https://user-images.githubusercontent.com/69216303/89337538-b5c2f200-d6b8-11ea-9308-ad6fd5cdd699.JPG)
![UIAutomater Viewer](https://user-images.githubusercontent.com/69216303/89337546-b78cb580-d6b8-11ea-855f-f4af501a9023.JPG)

**Comment by mykola-mokhnach** [comment]
Please attach the actual page source before the element lookup is executed

**Comment by mykola-mokhnach** [comment]
Also, I observe there is a web view. Consider switching to web view context to automate it.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
