### ISSUE TITLE
WebDriverAgent not installed on iphone when used appium desktop app

### ISSUE THREAD

**Issue by mohammad-genie** [appium/appium#14622]
## The problem

WebDriverAgent not installed on iphone when used appium desktop app
## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 10.15.6
* Node.js version (unless using Appium.app|exe): 14.4.0
* Npm or Yarn package manager: 6.14.7
* Mobile platform/version under test: 13.5
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

## Details

when run appium in terminal webdriverAgent install in  real device but when run appium desktop WebDriverAgent not installed in real device.

## Link to Appium logs

https://gist.github.com/mohammad-genie/093094dfd73b922fac51cb561856716e

## Code To Reproduce Issue [ Good To Have ]

 It is impossible to create a new session because 'createSession' which takes HttpClient, InputStream and long was not found or it is not accessible.

**Comment by mykola-mokhnach** [comment]
> [Xcode] 	Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the Signing & Capabilities editor.

Please fix WDA signing to make it working as described in https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

**Comment by mohammad-genie** [comment]
Now fixed ,  thank you so much.
