### ISSUE TITLE
Elements in page keeps on flickering through appium but renders correctly when done manually

### ISSUE THREAD

**Issue by rakshithcoradius** [appium/appium#14621]
## The problem

When automated through appium java, elements in some page keeps on flickering and can't proceed further. It fails the automation.
## Environment

* Appium version (Appium-linux-1.17.1-1) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Linux 18.04.4 LTS (Bionic Beaver)
* Node.js version (unless using Appium.app|exe): Node v14.4.0
* Npm or Yarn package manager: NPM v6.14.4
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium Appimage

## Appium logs

[HTTP] 
[HTTP] --> POST /wd/hub/session/80aa443d-2f1e-4df9-8ca2-9408cee10d54/elements
[HTTP] {"using":"accessibility id","value":"variant_root_makeModel-touchableView-0"}
[MJSONWP (80aa443d)] Calling AppiumDriver.findElements() with args: ["accessibility id","variant_root_makeModel-touchableView-0","80aa443d-2f1e-4df9-8ca2-9408cee10d54"]
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Waiting up to 0 ms for condition
[WD Proxy] Matched '/elements' to command name 'findElements'
[WD Proxy] Proxying [POST /elements] to [POST http://127.0.0.1:8200/wd/hub/session/1dd4dfe5-f939-4cdb-b0d5-09831aacbdd4/elements] with body: {"strategy":"accessibility id","selector":"variant_root_makeModel-touchableView-0","context":"","multiple":true}
[WD Proxy] Got response with status 200: {"sessionId":"1dd4dfe5-f939-4cdb-b0d5-09831aacbdd4","value":[{"ELEMENT":"d32b257a-c727-4d8d-aaec-d6a6ca0bf107","element-6066-11e4-a52e-4f735466cecf":"d32b257a-c727-4d8d-aaec-d6a6ca0bf107"}]}
[MJSONWP (80aa443d)] Responding to client with driver.findElements() result: [{"element-6066-11e4-a52e-4f735466cecf":"d32b257a-c727-4d8d-aaec-d6a6ca0bf107","ELEMENT":"d32b257a-c727-4d8d-aaec-d6a6ca0bf107"}]
[HTTP] <-- POST /wd/hub/session/80aa443d-2f1e-4df9-8ca2-9408cee10d54/elements 200 110 ms - 201
[HTTP] 
[HTTP] --> POST /wd/hub/session/80aa443d-2f1e-4df9-8ca2-9408cee10d54/element/d32b257a-c727-4d8d-aaec-d6a6ca0bf107/click
[HTTP] {}
[MJSONWP (80aa443d)] Calling AppiumDriver.click() with args: ["d32b257a-c727-4d8d-aaec-d6a6ca0bf107","80aa443d-2f1e-4df9-8ca2-9408cee10d54"]
[WD Proxy] Matched '/element/d32b257a-c727-4d8d-aaec-d6a6ca0bf107/click' to command name 'click'
[WD Proxy] Proxying [POST /element/d32b257a-c727-4d8d-aaec-d6a6ca0bf107/click] to [POST http://127.0.0.1:8200/wd/hub/session/1dd4dfe5-f939-4cdb-b0d5-09831aacbdd4/element/d32b257a-c727-4d8d-aaec-d6a6ca0bf107/click] with body: {"element":"d32b257a-c727-4d8d-aaec-d6a6ca0bf107"}
[WD Proxy] Got response with status 200: {"sessionId":"1dd4dfe5-f939-4cdb-b0d5-09831aacbdd4","value":null}
[MJSONWP (80aa443d)] Responding to client with driver.click() result: null
[HTTP] <-- POST /wd/hub/session/80aa443d-2f1e-4df9-8ca2-9408cee10d54/element/d32b257a-c727-4d8d-aaec-d6a6ca0bf107/click 200 140 ms - 76
[HTTP] 
[HTTP] --> GET /wd/hub/session/80aa443d-2f1e-4df9-8ca2-9408cee10d54/source
[HTTP] {}
[MJSONWP (80aa443d)] Driver proxy active, passing request on via HTTP proxy
[WD Proxy] Matched '/wd/hub/session/80aa443d-2f1e-4df9-8ca2-9408cee10d54/source' to command name 'getPageSource'
[WD Proxy] Proxying [GET /wd/hub/session/80aa443d-2f1e-4df9-8ca2-9408cee10d54/source] to [GET http://127.0.0.1:8200/wd/hub/session/1dd4dfe5-f939-4cdb-b0d5-09831aacbdd4/source] with body: {}
[WD Proxy] Got response with unknown status: {"code":"ECONNRESET"}
[Instrumentation] INSTRUMENTATION_RESULT: shortMsg=Process crashed.
[Instrumentation] INSTRUMENTATION_CODE: 0
[MJSONWP (80aa443d)] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: socket hang up
[MJSONWP (80aa443d)]     at doJwpProxy (/tmp/.mount_Appiumch0NGo/resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:505:13)
[MJSONWP (80aa443d)]     at runNextTicks (internal/process/task_queues.js:58:5)
[MJSONWP (80aa443d)]     at processImmediate (internal/timers.js:412:9)
[MJSONWP (80aa443d)]     at asyncHandler (/tmp/.mount_Appiumch0NGo/resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:265:9)
[HTTP] <-- GET /wd/hub/session/80aa443d-2f1e-4df9-8ca2-9408cee10d54/source 500 6387 ms - 280
[HTTP] 
[HTTP] --> GET /wd/hub/session/80aa443d-2f1e-4df9-8ca2-9408cee10d54/screenshot
[HTTP] {}
[MJSONWP (80aa443d)] Calling AppiumDriver.getScreenshot() with args: ["80aa443d-2f1e-4df9-8ca2-9408cee10d54"]
[WD Proxy] Matched '/screenshot' to command name 'getScreenshot'
[WD Proxy] Proxying [GET /screenshot] to [GET http://127.0.0.1:8200/wd/hub/session/1dd4dfe5-f939-4cdb-b0d5-09831aacbdd4/screenshot] with no body

## Code To Reproduce Issue [ Good To Have ]

@Test
	 public void sampleTest() throws InterruptedException {
		MobileElement el1 = (MobileElement) driver.findElementByXPath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.webkit.WebView/android.view.View[3]/android.view.View/android.view.View[1]/android.view.View/android.view.View/android.widget.EditText[1]");
	    el1.sendKeys("s");
	    MobileElement el2 = (MobileElement) driver.findElementByXPath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.webkit.WebView/android.view.View[3]/android.view.View/android.view.View[1]/android.view.View/android.view.View/android.widget.EditText[2]");
	    el2.sendKeys("s");
	    MobileElement el3 = (MobileElement) driver.findElementByXPath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.webkit.WebView/android.view.View[3]/android.view.View/android.view.View[1]/android.view.View/android.view.View/android.view.View[3]/android.widget.Button");
	    el3.click();
	    TimeUnit.SECONDS.sleep(8);
	    MobileElement el4 = (MobileElement) driver.findElementByAccessibilityId("leadList-createButton");
	    el4.click();
	    TimeUnit.SECONDS.sleep(3);
	    MobileElement el5 = (MobileElement) driver.findElementByAccessibilityId("picker_root_completeName_title");
	    el5.click();
	    TimeUnit.SECONDS.sleep(3);
	    //MobileElement el6 = (MobileElement) driver.findElements(By.className("android.widget.CheckedTextView")).get(6);
	    MobileElement el6 = (MobileElement) driver.findElementByXPath("//android.widget.CheckedTextView[@index='5']");
	    TimeUnit.SECONDS.sleep(5);
	    el6.click();
        MobileElement el7 = (MobileElement) driver.findElementByAccessibilityId("root_completeName_firstName");
        el7.sendKeys("AAA");
        MobileElement el8 = (MobileElement) driver.findElementByAccessibilityId("root_completeName_middleName");
        el8.sendKeys("BBB");
        MobileElement el9 = (MobileElement) driver.findElementByAccessibilityId("root_completeName_lastName");
        el9.sendKeys("CCC");
        MobileElement el10 = (MobileElement) driver.findElementByAccessibilityId("root_gender_female_1");
        el10.click();
        MobileElement el11 = (MobileElement) driver.findElementByAccessibilityId("root_email");
        el11.sendKeys("c@c.com");
        MobileElement el12 = (MobileElement) driver.findElementByAccessibilityId("mobileMask_root_mobile");
        el12.sendKeys("9999999999");
        MobileElement el13 = (MobileElement) driver.findElementByAccessibilityId("picker_root_insuranceType");
	    el13.click();
	    TimeUnit.SECONDS.sleep(3);
	    MobileElement el14 = (MobileElement) driver.findElementByXPath("//android.widget.CheckedTextView[@index='2']");
	    el14.click();
	    MobileElement el15 = (MobileElement) driver.findElementByAccessibilityId("modalAddButton-createLead");
	    el15.click();
	    TimeUnit.SECONDS.sleep(3);
	    MobileElement el16 = (MobileElement) driver.findElementByAccessibilityId("customRadio-options-continueWithRegistrationNumber-0");
	    el16.click(); 
	    TimeUnit.SECONDS.sleep(3);
	    MobileElement el17 = (MobileElement) driver.findElementByAccessibilityId("customTextInput_root_vehicleRegistrationNumber");
	    el17.sendKeys("KA-05-JJ-1234");
	    MobileElement el18 = (MobileElement) driver.findElementByAccessibilityId("root_registrationDate");
	    el18.sendKeys("2017/02/22");
	    MobileElement el19 = (MobileElement) driver.findElementByAccessibilityId("bikeFormButton-next");
	    el19.click();
	    TimeUnit.SECONDS.sleep(3);
	    MobileElement el20 = (MobileElement) driver.findElementByAccessibilityId("make_root_makeModel-textInput");
	    el20.click();
	    el20.sendKeys("Bajaj");
	    MobileElement el21 = (MobileElement) driver.findElementByAccessibilityId("make_root_makeModel-touchableView-0");
	    el21.click();
	    TimeUnit.SECONDS.sleep(3);
	    MobileElement el22 = (MobileElement) driver.findElementByAccessibilityId("model_root_makeModel-textInput");
	    el22.click();
	    el22.sendKeys("Avenger");
	    MobileElement el23 = (MobileElement) driver.findElementByAccessibilityId("model_root_makeModel-touchableView-0");
	    el23.click();
	    TimeUnit.SECONDS.sleep(3);
	    MobileElement el24 = (MobileElement) driver.findElementByAccessibilityId("fuelType_root_makeModel-textInput");
	    el24.click();
	    el24.sendKeys("Petrol");
	    TimeUnit.SECONDS.sleep(3);
	    MobileElement el25 = (MobileElement) driver.findElementByAccessibilityId("fuelType_root_makeModel-touchableView-0");
	    el25.click();
	    TimeUnit.SECONDS.sleep(3);
	    MobileElement el26 = (MobileElement) driver.findElementByAccessibilityId("variant_root_makeModel-textInput");
	    el26.click();
	    el26.sendKeys("STD");
	    MobileElement el27 = (MobileElement) driver.findElementByAccessibilityId("variant_root_makeModel-touchableView-0");
	    el27.click();
	    }
	    MobileElement el28 = (MobileElement) driver.findElementByAccessibilityId("picker_manufacturingYear_root_makeModel");
	    el28.click();
	    MobileElement el29 = (MobileElement) driver.findElementByXPath("//android.widget.TextView[@index='2']");
	    el29.click();
	    }

Attachments:
APK URL : [https://rb.gy/2ysbkh] (url)
Video of Bug : [https://rb.gy/fthjda]

**Comment by mykola-mokhnach** [comment]
I assume such result is expected, since accessibility interaction thread used by UiAutomator uses the main loop to execute its commands. This is the main reason why it is recommended to disable/postpone all unnecessary app activity (especially animations) in the main thread while automated tests are running.

Unfortunately there is nothing that could be done from Appium side. Please report your issue to Google if you think this is a bug

**Comment by rakshithcoradius** [comment]
But i cant proceed with that
