### ISSUE TITLE
Screenshots get swapped between devices when two instances of AppiumDriver are executed parallely

### ISSUE THREAD

**Issue by iamporus** [appium/appium#14627]
## The problem
I'm using two instances of AppiumDriver in separate threads for automating a mobile app on two Android devices in parallel. When a test case fails on both the devices, I'm trying to capture a screenshot of the devices using the following code snippet.
`((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);`

The screenshots are saved in different directories named after the device names, but sometimes (2 out of 3), the screenshots created get swapped between the devices. That means if I'm using a Tab and a Phone for testing, the screenshot of the Tab gets created inside the directory created for Phone and vice versa.

I'm pretty sure there are two separate instances of AppiumDriver running on different ports as the entire test suit (~100+ tests) runs smoothly on both the devices without a problem. Just the screenshots get swapped between the devices.

Any help or pointers in the right direction are much appreciated.

## Source Code 
Find a very brief (dirty) representation of my code flow [here](https://gist.github.com/iamporus/0660be6a2672951f4c082a8087140585)

## Environment

* Appium version: 1.18.0
* Desktop OS/version: Mac OS Catalina 10.15.5
* Node.js version: v12.16.1
* Npm or Yarn package manager:  Npm (v6.13.4)
* Real device or emulator/simulator: Real Devices 
* Appium CLI or Appium.app|exe: Appium

**Comment by mykola-mokhnach** [comment]
I assume it is the issue in the client code. Could you please provide the server code where you think the issue happens?

**Comment by iamporus** [comment]
@mykola-mokhnach I've updated the question with a very brief representation of my source code. Though I'm not sure what you mean by server or client code. Please let me know if you need any more info.

**Comment by mykola-mokhnach** [comment]
Client code is the code written by you. The server code is the code executed by either appium as a proxy or a corresponding downstream server, like UiAutomator2 server.

this is the tracker for server issues. Consider asking at Appium forum if your topic is unrelated.

**Comment by iamporus** [comment]
Thanks for the clarification. Closing the issue as it is not relevant to appium server implementation.
