### ISSUE TITLE
Cannot find any free port in range 8200..8299 (Appium Android)

### ISSUE THREAD

**Issue by Pr60** [appium/appium#14628]
## The problem
I'm not able to run about 100 Android tests (can run iOS) but I'm able to run less than 100 tests for sure. 

## Environment

* Appium version: 1.18.0
* Desktop OS/version: Mac Os Catalina 10.15.4
* Node.js version: 12.16.3
* Npm: 6.14.7
* Mobile platform/version under test: Android 
* Emulator: PIXEL_3a_API_R 

## Details

ADB seems to not delete the unused active session. In the end, I see 100 active sessions are there. The available port is 8200 -8299 for UIautomator 2 and that's why it seems that I'm not able to run more than 100 tests.

Error:

```
Starting logs capture with command: /Users/username/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 logcat -v threadtime
     E       selenium.common.exceptions.WebDriverException: Message: An unknown server-side
 error occurred while processing the command. Original error: Cannot find any free port in range
 8200..8299}. Please set the available port number by providing the systemPort capability or
 double check the processes that are locking ports within this range and terminate these which
 are not needed anymore
```

## Link to Appium logs

https://gist.github.com/Pr60/9a6c5e010a7f5229285a49dd2d9425ba

## Additional Info

Please note the issue has been mentioned in Stackoverflow too. Here are some more details regarding what has been done to resolve the problem but still didn't work - https://stackoverflow.com/questions/63238793/appium-error-cannot-find-any-free-port-in-range-8200-8299

**Comment by mykola-mokhnach** [comment]
It might be your client code does not close previous appium sessions properly before starting a new ones, so you get the error above if the amount of these unclosed sessions reaches 100.

the session deletion requests are coming from the SIGINT/SIGTERM handler, which the server receives upon terminating its process. E.g. the expected clenup of active sessions is being performed as a part of server shutdown process.

**Comment by Pr60** [comment]
Thanks for your insights @mykola-mokhnach . It could be client code but I am not providing any input to cleanup. Do you know how to close previous appium session using client code?

**Comment by mykola-mokhnach** [comment]
Kindly use Appium forum to ask questions

**Comment by mykola-mokhnach** [comment]
On the server side though there is a possibility to work in single-session mode by providing `--session-override` command line argument.

Closed as not an issue

**Comment by Pr60** [comment]
Thanks, sorry do you mind taking this conversation here https://discuss.appium.io/t/error-taking-screenshot-when-using-session-override-flag/31573 ? I'm actually stuck with this problem for a few days now. `--session-override` did resolve my issue which I described in this ticket but this gave me another problem.

**Comment by mykola-mokhnach** [comment]
I would suggest hiring a consultant to get immediate answers to your questions and properly architect the testing framework solution.

**Comment by SparshGoyal08** [comment]
`--session-override` while starting appium server worked for me
