### ISSUE TITLE
Unable to get pagesource for ios 13 native share popup

### ISSUE THREAD

**Issue by ganjarpanji** [appium/appium#14624]
## The problem

I'm facing error (Webdriver exception) when trying to get pagesource (by `driver.getPageSource`) on iOS 13 native share popup.
![image](https://user-images.githubusercontent.com/1736817/89378240-9a3e0280-d71d-11ea-9119-cff6a164c217.png)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 10.14.6
* Node.js version (unless using Appium.app|exe): 10.16.0
* Npm or Yarn package manager: 6.13.6
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI

## Details

This occurred during test run, or by manually debug and preform driver.pagesource. i also tried manually using macaca inspector but it shows infinite loading

## Link to Appium logs

https://gist.github.com/ganjarpanji/f6cb389830b8bfe7dccc54256fc0fb47

**Comment by mykola-mokhnach** [comment]
This is most likely a bug in XCTest, which should be reported to Apple. Please attach the device log to fetch more details about what is happening .

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by ganjarpanji** [comment]
hi @mykola-mokhnach please guide me how to log the device? I'm currently using simulator
