### ISSUE TITLE
Popup "Unable to boot device in current state: Booted" comes and does not close simulator after tests.

### ISSUE THREAD

**Issue by mukhasir** [appium/appium#14630]
## The problem

Unable to boot device in current state: Booted - When running cucumber tests using appium v1.18.0, Node v10.22.0, Xcode 11.5

## Environment

* Appium version (or git revision) that exhibits the issue: v1.18.0
* Last Appium version that did not exhibit the issue (if applicable): 1.17.1
* Desktop OS/version used to run Appium: 
* Node.js version (unless using Appium.app|exe): v10.22.0
* Npm or Yarn package manager: 6.14.6
* Mobile platform/version under test: ios 12.2
* Real device or emulator/simulator: iphone 6 - simulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

When running the cucumber tests using i am facing issue when this popup comes up but in background the process is running and executing the test cases but the popup remains like that and doesnot go off.
This has started with v1.18.0 version.  
<img width="422" alt="Screen Shot 2020-08-06 at 2 05 49 PM" src="https://user-images.githubusercontent.com/11187451/89583544-603d3100-d7ef-11ea-8760-b62229f6b8d4.png">
I have verified that  simulator is in shutdown mode before starting the tests and when i start the tests the popup comes and the simulator does not die and it keeps simulator in booted state.
I have to click ok on popup and close the simulator to get the simulator to shut down state.

## Code To Reproduce Issue [ Good To Have ]

**Comment by mykola-mokhnach** [comment]
Please provide the full server log

**Comment by mukhasir** [comment]
This is Gist Page with Appium log till it Boots Simulator as I think the (https://github.com/appium/appium-ios-simulator/pull/283) might have solved the issue. Will have to check it.

**Comment by mykola-mokhnach** [comment]
Feel free to push a PR yourself if you could propose a better solution.
