### ISSUE TITLE
Error: The JAVA_HOME location '/Library/Java/JavaVirtualMachine/jdk1.8.0_241.jdk/Contents/Home' must exist

### ISSUE THREAD

**Issue by andikabhaskara** [appium/appium#14641]
## The problem
Hi,
I'm new in this forum so I hope what I want to explain is enough to meet the community guideline. So, I've been using appium since 1.15 and I have no issue using it until I decided to upgrade it into 1.18. After I restart my laptop and the 1.18 appium is applied, when I tried to create a new session from my saved capabilities I got this error Error: The JAVA_HOME location '/Library/Java/JavaVirtualMachine/jdk1.8.0_241.jdk/Contents/Home' must exist. The jdk that I have is jdk1.8.0_251.jdk and the path that I put is export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_251.jdk/Contents/Home. So I was wondering how to resolve this issue?

## Environment

* Appium version : 1.18
* Desktop OS/version used to run Appium: MacOS Catalina Version 10.15.4
* emulator: Android Studio 4.0
* Device: Pixel 3a XL

## Gist
here's the link for [Gist](https://gist.github.com/andikabhaskara/877a6bec2b9a867a0f75cbee0a397082)

## Details

For reference my capabilites:
{
  "platformName": "Android",
  "deviceName": "device",
  "app": "/Users/User/TodoApp.apk",
  "udid": "emulator-5554",
  "automationName": "UIAutomator2"
}

Thank you guys!

**Comment by mykola-mokhnach** [comment]
The error message is pretty clear - the folder either does not exist on the local file system or cannot be accessed by appium process

**Comment by andikabhaskara** [comment]
Yess, I notice the problem is that I have folder JavaVirtualMachines but the appium ask for JavaVirtualMachine, how do I change the source to what I have?

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/java-client/blob/master/docs/environment.md

Please use Appium forum to ask questions. Closed as not an issue
