### ISSUE TITLE
Appium hanging when unzipping the .app.zip file while trying to install to a simulator

### ISSUE THREAD

**Issue by kulasangeles** [appium/appium#14649]
## The problem

We upgraded to Xcode 12 Beta 2 with Appium 1.18.0 and when we are trying to install app.zip applications to an iOS 14 and iOS 13 simulators using either driver.installApp or the capability "app", it is downloading the file locally but hangs in the unzipping part. 

[debug] [Support] http://appium.s3.amazonaws.com/TestApp6.0.app.zip (15.37 KB) has been downloaded to '/var/folders/57/263s1nvs7ssgwf7tjmj2q73c0000gr/T/2020713-53832-112cqe.f5h2xo/TestApp6.0.app.zip' in 0.621s
[debug] [BaseDriver] Unzipping '/var/folders/57/263s1nvs7ssgwf7tjmj2q73c0000gr/T/2020713-53832-112cqe.f5h2xo/TestApp6.0.app.zip'

Note that when we use Appium Desktop for 1.18.0 it works.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.0
* Last Appium version that did not exhibit the issue (if applicable): 1.17, Xcode 11.5
* Desktop OS/version used to run Appium: Mac Catalina

**Comment by mykola-mokhnach** [comment]
I've tried it on my machine and all worked

Local file:
```
[BaseDriver] Using local app '/Users/elf/Downloads/TestApp6.0.app.zip'
[debug] [BaseDriver] Unzipping '/Users/elf/Downloads/TestApp6.0.app.zip'
[debug] [BaseDriver] Extracted 8 items from '/Users/elf/Downloads/TestApp6.0.app.zip' in 61ms
[debug] [BaseDriver] Matched 1 item in the extracted archive. Assuming 'TestApp.app' is the correct bundle
```

Remote file:
```
[BaseDriver] Using downloadable app 'http://appium.s3.amazonaws.com/TestApp6.0.app.zip'
[debug] [BaseDriver] Last-Modified: Tue, 12 Feb 2013 02:38:20 GMT
[debug] [BaseDriver] Cache-Control: undefined
[debug] [BaseDriver] A fresh copy of the application is going to be downloaded from http://appium.s3.amazonaws.com/TestApp6.0.app.zip
[debug] [BaseDriver] Content-Type: application/zip
[debug] [Support] http://appium.s3.amazonaws.com/TestApp6.0.app.zip (15.37 KB) has been downloaded to '/var/folders/4s/4pd60d1j5cj2bkg1lr_s5c100000gn/T/2020713-75846-1viutph.jl1p/TestApp6.0.app.zip' in 16.978s
[debug] [Support] Approximate download speed: 926 B/s
[debug] [BaseDriver] Unzipping '/var/folders/4s/4pd60d1j5cj2bkg1lr_s5c100000gn/T/2020713-75846-1viutph.jl1p/TestApp6.0.app.zip'
[debug] [BaseDriver] Extracted 8 items from '/var/folders/4s/4pd60d1j5cj2bkg1lr_s5c100000gn/T/2020713-75846-1viutph.jl1p/TestApp6.0.app.zip' in 48ms
[debug] [BaseDriver] Matched 1 item in the extracted archive. Assuming 'TestApp.app' is the correct bundle
[BaseDriver] Unzipped local app to '/var/folders/4s/4pd60d1j5cj2bkg1lr_s5c100000gn/T/2020713-75846-al63zg.kdlvj/TestApp.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1597343799856 (20:36:39 GMT+0200 (Central European Summer Time))
```

I'd try to check if nodeJS is up to date and also if there are some third-party software on the machine, that may intercept file operations

**Comment by kulasangeles** [comment]
Updating the NodeJS from 14.0 to 14.8 did the job. Thanks, @mykola-mokhnach!
