### ISSUE TITLE
Not able to identify locators in Appium for a pop up box

### ISSUE THREAD

**Issue by sudhanshuprakash** [appium/appium#14646]
## The problem

I am trying to automate a word application using Appium. I have to insert a line or rectangle using appium. When I click on shapes option I am getting all the required shapes but I am not able to inspect the element. Instead, when I click on the shape icon(line or rectangle), the element which is getting selected is one just behind it. Although using points option I can click on the element but I am not able to click on shape element using any locator. So is there any way I can get the location address. Do I have to switch frames, if so how? I have attached an image for a better understanding of the problem. In this image when I am clicking on an arrow icon I am not able to get the details instead of that the element that is getting selected in the one just behind it. Please copy and paste this link to get the image: "https://i.stack.imgur.com/JPKPL.png"

## Environment

* Appium version (or git revision) that exhibits the issue:  1.18.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): 12.8.1
* Npm or Yarn package manager: 
* Mobile platform/version under test: 7.1.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium.exe

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ includes Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favorite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Element location logic is controlled by Windows App Driver itself, which is maintained by Microsoft and is not open-source. Please report your issue to https://github.com/microsoft/WinAppDriver

Closed as third party issue
