### ISSUE TITLE
Android touchAction moveTo not working

### ISSUE THREAD

**Issue by colinfwren** [appium/appium#14642]
## The problem

I've been automating my app with Appium on iOS with relative ease but I'm now adapting the code to also run on Android and I'm hitting a wall with touchActions.

The touchAction is doing a longPress, moveTo and release in order to carry out a drag and drop and this working fine on iOS but on Android it does the longPress but when it does the moveTo the UI doesn't carry out the drag.

I've run it with the pointers debug option on and I can see that it's doing the moveTo (it's drawing a line at least - see video linked below).

I know it's doing the longPress on the element as the UI updates to indicate that the element is being dragged and this is happening and the release is happening as after the drag the UI updates to indicate the release of the element.

I'm not sure if this is relevant but when the drag and drop happens on iOS the drag is relatively slow where as on Android the drag is almost instantaneous.

I had a similar issue with a navigation Drawer on Android where the swipe to dismiss it wasn't working but I was able to get this working by changing the initial action from `press` to `tap`, I can't follow the same approach here however as the drag and drop requires the `longPress` to start it off.

Any help with understanding why this might be happening on Android only would be great or a work around such as getting a `tap` to act as a `longPress` would help massively.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Ubuntu 20.04
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager: Yarn
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Emulator (Pixel 3a, API 30)
* Appium CLI or Appium.app|exe: Appium Desktop

App is built with React Native and currently running the Expo Client.

Automation framework is Jest with Webdriver.io

## Details

I've uploaded a video of the test run here: https://youtu.be/uKWIDFXa-jo

I've attempted to get this working with `touchPerform` also which yielded the same results.

## Link to Appium logs

https://gist.github.com/colinfwren/3c026cc27b6eb5f8f0344e814d03ed44

## Code To Reproduce Issue [ Good To Have ]

Here's the code I'm using:
```
async dragItem(fromIndex: number, toIndex: number) {
  const handles = await this.element.$$(`~dragHandle`);
  const toHandle = handles[toIndex];
  const fromHandle = handles[fromIndex];
  const fromLoc = await fromHandle.getLocation();
  const toLoc = await toHandle.getLocation();
  const posDelta = this.client.isIOS ? 11 : 30;
  const xPos = Math.abs(fromLoc.x + posDelta);
  const fromYPos = Math.abs(fromLoc.y + posDelta);
  const toYPos = Math.abs(toLoc.y + posDelta);
  await this.client.touchAction([
     { action: 'longPress', x: xPos, y: fromYPos },
     { action: 'wait', ms: 6000},
     { action: 'moveTo', x: xPos, y: toYPos},
     { action: 'wait', ms: 3000},
     { action: 'release' }
  ]);
}
```
This would then be used like `dragItem(2, 0)` which would drag the 3rd item in the list to where the 1st item is.

I've had to resort to using co-ordinates instead of the element (which I had been using for iOS) as I received an error about positions using floats instead of integers.

When this run I can see that it carries out the long press, and with pointers on in the emulator I can see that it carries out the moveTo but on doing so the UI doesn't get updated.

Here's the capabilities I'm running the code using:
```
{
  "platformName": "android",
  "deviceName": "Pixel_3a_API_30",
  "automationName": "UiAutomator2",
  "pkg": "host.exp.exponent",
  "intentAction": "android.intent.action.VIEW",
  "activity": "host.exp.exponent.experience.HomeActivity",
  "appWaitForLaunch": false
}
```

**Comment by mykola-mokhnach** [comment]
Consider switching to W3C actions usage. They are more precise and allow to achieve much more advanced results in comparison to the old TouchAction stuff. 

Read 
- https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/actions.md 
- https://appiumpro.com/editions/29-automating-complex-gestures-with-the-w3c-actions-api
for more details.

Also, for Android the duration of press should be about [400ms](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/view/ViewConfiguration.java#87) to be considered as long press and not a tap

**Comment by colinfwren** [comment]
@mykola-mokhnach Thanks so much for that tip, that did the trick, here's the code that I now have working should anyone need it for reference:
```
await this.client.performActions(
        [
                {
                    type: 'pointer',
                    id: 'finger',
                    parameters: {
                        pointerType: 'touch',
                    },
                    actions: [
                        {
                            type: 'pointerMove',
                            duration: 0,
                            x: xPos,
                            y: fromYPos,
                        },
                        {
                            type: 'pointerDown',
                            button: 0,
                        },
                        {
                            type: 'pause',
                            duration: 6000,
                        },
                        {
                            type: 'pointerMove',
                            duration: 5000,
                            x: xPos,
                            y: toYPos,
                        },
                        {
                            type: 'pointerUp',
                            button: 0,
                        }
                    ]
                }
            ]
        );
```
