### ISSUE TITLE
[Appium 1.18.0]Neither ANDROID_HOME nor ANDROID_SDK_ROOT environment variable was exported

### ISSUE THREAD

**Issue by sasasa42** [appium/appium#14650]
## The problem

After updating to the latest Appium version 1.18.0 from 1.17.1, finding this blocker even though the ANDROID_HOME and ANDROID_SDK_ROOT are defined in the bash_profile. Some issue is definitely there in the latest version.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.0
* Last Appium version that did not exhibit the issue (if applicable): 1.17.1
* Desktop OS/version used to run Appium: 10.14.6
* Node.js version (unless using Appium.app|exe):v12.11.1
* Npm or Yarn package manager:npm
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

I tried switching between the ANDROID_HOME and ANDROID_SDK_ROOT , everything looks perfect, still it complains that the Neither ANDROID_HOME nor ANDROID_SDK_ROOT environment variable was exported. When I reverted back to Appium 1.17.1 version, it works fine perfectly as before. Please check.

## Link to Appium logs

https://gist.github.com/sasasa42/059168fdfade85b96f4c6be6d0bb4365

**Comment by mykola-mokhnach** [comment]
Please follow the troubleshooting document at https://github.com/appium/java-client/blob/master/docs/environment.md

**Comment by sasasa42** [comment]
@mykola-mokhnach I am using the bash shell and to me everything looks perfect as I have already defined the environment variables correctly in the PATH. The moment i revert back to 1.17.1..its perfectly fine. There is some issue still i suspect with the latest 1.18.0 version

**Comment by mykola-mokhnach** [comment]
Have you checked per-process variables as it is described in the document above?

**Comment by sasasa42** [comment]
I was just going through. Not sure how to exactly do it in this case. Do you mean, we have to additionally set the env. variable before in some way? Also, can you provide like how the command should be in this case?

**Comment by mykola-mokhnach** [comment]
I assume the tutorial is pretty straightforward about how to check variable presence in scope of a process. If not then let us know what exactly is unclear and could be improved.

Closed as not a server server issue. Kindly use appium forum to ask questions.

**Comment by hlmichael** [comment]
ANDROID_HOME can be detected on Appium_Desktop v1.18.0 but can't be detected while being launched via command(appium v1.18.2). And I'm pretty sure it has been set,please do not tell me to follow the document. thanks!

**Comment by seanchannel** [comment]
`appium-doctor` did not have these errors before when the prerequisites were correctly installed. Something is wrong.

**Comment by felipebutcher** [comment]
this happened to me. i had opened a terminal and started appium, then in another terminal i was trying to run node index.js and getting this error. i had to go back to the previous terminal, stop appium, export the variables and start appium again, then node index.js worked on the second terminal.

**Comment by farzadso** [comment]
Same issue for me @felipebutcher

**Comment by vjmaiky** [comment]
any updates here on how you managed to fix the issue?

**Comment by farzadso** [comment]
@vjmaiky I followed the steps mentioned by @felipebutcher 

> this happened to me. i had opened a terminal and started appium, then in another terminal i was trying to run node index.js and getting this error. i had to go back to the previous terminal, stop appium, export the variables and start appium again, then node index.js worked on the second terminal.

**Comment by vjmaiky** [comment]
i understand but the variables are in .zshrc

lmihai@192-168-0-113 ~ % echo $SHELL
/bin/zsh
lmihai@192-168-0-113 ~ % echo $ANDROID_HOME
/Users/lmihai/Library/Android/sdk
lmihai@192-168-0-113 ~ % env | grep ANDROID_HOME
ANDROID_HOME=/Users/lmihai/Library/Android/sdk
lmihai@192-168-0-113 ~ %

Do you set them always manually?
