### ISSUE TITLE
Problem with autodownload_chromedriver feature

### ISSUE THREAD

**Issue by Kabellard** [appium/appium#14658]
## The problem

I'm trying to use the autodownlaod_chromedriver feature, to download the matching Chromedriver version to the phone running the test automatically. Appium seems to be able to find the installed version of chrome in the phone, and download the correct Chromedriver (version 84.0.4147.30). However, after the download is done, Appium fails to find the version of Chromedriver it just downloaded, and it says that the most recent known version of chrome is 83.0.4143.

It suggest making sure that the --version of the installed chromedriver returns a valid string, but it does: ChromeDriver 84.0.4147.30 (48b3e868b4cc0aa7e8149519690b6f6949e110a8-refs/branch-heads/4147@{#310}).

After this, Appium enters in an infinite loop.

## Environment

* Appium version (or git revision) that exhibits the issue:    1.18.0
* Desktop OS/version used to run Appium:                          Windows 10
* Node.js version (unless using Appium.app|exe):                10.22.0 - 64bits
* Npm or Yarn package manager:                                         NPM
* Mobile platform/version under test:                                   Android 8
* Real device or emulator/simulator:                                     Real device
* Appium CLI or Appium.app|exe:                                         Appium CLI

## Link to Appium logs

https://gist.github.com/Kabellard/edfae591a5542ae4cd3acd3ca8579ffd 

## Code To Reproduce Issue [ Good To Have ]

Not sure if applicable.

**Comment by mykola-mokhnach** [comment]
Please try appium@beta

**Comment by mykola-mokhnach** [comment]
> [Chromedriver] Cannot retrieve version number from 'chromedriver_win32_v84.0.4147.30.exe' Chromedriver binary. Make sure it returns a valid version string in response to '--version' command line argument. spawn EBUSY

there is probably some anitivirus software on your computer, which blocks access to the downloaded executable, so appium cannot read its version

**Comment by Kabellard** [comment]
Hi, thank you for your reply!

I do not have an antivirus installed (other than windows defender, the one that comes with window) so I don't think that this would be the issue. When I run the command --version command myself, I get a valid string, and when I set the chromedriver.exe manually (using --chromedriver-executable path/to/executable), the tests are able to run, so I do not think that an anti virus is the reason why this is happening.

Furthermore, it wouldn't explain these part of the logs: 
`[debug] [Chromedriver] Found Chrome bundle 'com.android.chrome' version '84.0.4147'
[debug] [Chromedriver] The most recent known Chrome version: 83.0.4103
[debug] [Chromedriver] Error: No Chromedriver found that can automate Chrome '84.0.4147'. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md for more details
[debug] [Chromedriver]     at Chromedriver.getCompatibleChromedriver (C:\Users\Xemploye\git\XXXX_app\node_modules\appium\node_modules\appium-chromedriver\lib\chromedriver.js:360:15)
[Chromedriver] No Chromedriver found that can automate Chrome '84.0.4147'. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md for more details`

**Comment by mykola-mokhnach** [comment]
> When I run the command --version command myself, I get a valid string, and when I set the chromedriver.exe manually (using --chromedriver-executable path/to/executable), the tests are able to run, so I do not think that an anti virus is the reason why this is happening.

It still might be the issue, because the file could be locked for a short period after it is downloaded and unpacked. After a while the system unlocks it, so it is possible for you to get the proper output. 

Regarding the second issue - there was a bug in appium-chromedriver component, that it was trying to download an executable again even though it was already there. This issue must be fixed in appium@beta. See https://github.com/appium/appium-chromedriver/pull/186 for more details.
