### ISSUE TITLE
I am unable to locate an element on device 1 but same element is accessible on device 2

### ISSUE THREAD

**Issue by sunnymittal16** [appium/appium#14654]
## The problem

I am automating a messenger app where i am using 2 device (1 for sender and 1 receiver). i am able to locate an element on device 1. For same element, i got "NoSuchElementError" on device 2.

i tried to access this element using both id and xpath. But i got no success on device 2.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.0
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): v12.14.1
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Android 9
* Real device or emulator/simulator: Emulator 
* Appium CLI or Appium.app|exe:

**Comment by mykola-mokhnach** [comment]
Please provide page sources and server logs for both devices

**Comment by sunnymittal16** [comment]
Issue is rectified so marking this as closed.
