### ISSUE TITLE
Recording parallel runs on iOS (real device) records only the screen of the first device

### ISSUE THREAD

**Issue by Shioriberms** [appium/appium#14668]
## The problem

Recording parallel runs on iOS (real device) records only the screen of the first device

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17 or 1.16
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Mac Catalina
* Mobile platform/version under test: 13.4 
* Real device or emulator/simulator: Real device

## Details

We have 2 devices connected to 2 different appium servers with different appium ports and wdalocalports. I'll call it Device A and Device B. 

When the test runs on Device A, issue command self.driver.start_recording_screen().
While test on Device A is running, start another test on Device B and issue command self.driver.start_recording_screen().
When the test on Device A is over, issue command self.driver.stop_recording_screen(). Save to file A.mp4.
When the test on Device B is over, issue command self.driver.stop_recording_screen(). Save to file B.mp4.

The video A.mp4 is fine. However, the video B.mp4 shows the screen of Device A.
I'm assuming it has to do with the port used for recording (9100). Since the same port is used for both recording, I decided to change the desired cap (mjpegServerPort) of test on B device to 9101 even though it was listed as an UIAutomator2 function. I was able to see the two streams upon navigating to localhost:9100 and localhost:9101. However, there are days that 9101 is not working but 9102 is working. The error I'm getting is a connection refused to port. I check if the ports are free before the runs and they are free.

I can't find anywhere if screen recording on parallel runs is supported or there are other configs that needed to be done.

`[iProxy@00008030:9174] Connection was refused to port 9101
[ffmpeg] http://127.0.0.1:9174: End of file
[ffmpeg]`

**Comment by mykola-mokhnach** [comment]
For parallel execution you should follow https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/parallel-tests.md

In order to split video broadcast for both devices it is necessary to set mjpegServerPort to a unique value for each parallel session. Error might be happening if there are session management issues on the client side (e.g. following sessions are started while active ones are not closed properly.)

**Comment by mykola-mokhnach** [comment]
It is not possible to say anymore without the detailed server logs

**Comment by Kullapat-palo** [comment]
> For parallel execution you should follow https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/parallel-tests.md
> 
> In order to split video broadcast for both devices it is necessary to set mjpegServerPort to a unique value for each parallel session. Error might be happening if there are session management issues on the client side (e.g. following sessions are started while active ones are not closed properly.)

This link doesn't work, So Could you tell me how to solve this problem? or do you have a new link?
