### ISSUE TITLE
Don't launch app in the simulator iOS

### ISSUE THREAD

**Issue by michellebenedetti** [appium/appium#14661]
## The problem
I can't run automated tests on the simulator, because of the problem: 

[MJSONWP] 	Building for iOS Simulator, but the linked framework 'CocoaAsyncSocket.framework' was built for tvOS + tvOS Simulator.
WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: Cannot launch simulated executable: no file found at /Users/michele.benedetti/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app))

## Environment

* Appium version:  v.1.15.1
* Desktop OS/version used to run Appium: macOs Catalina 10.15.6
* Node.js version: v12.13.0
* Npm or Yarn package manager: 6.14.7
* Mobile platform/version under test: iOS 11.5
* Real device or emulator/simulator: iPhone 11 - 13.5
* Appium CLI or Appium.app|exe: Appium Desktop

## Details

Was trying to start session by appium desktop to connect with simulator, then got following error like the logs shown

## Link to Appium logs

[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[MJSONWP] xcodebuild error message:
[MJSONWP] 
[MJSONWP] 2020-08-18 08:29:34.479 xcodebuild[40861:862907] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder “WebDriverAgentRunner_iphonesimulator13.5-x86_64.xctestrun” doesn’t exist." UserInfo={NSFilePath=/Users/michele.benedetti/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz/Build/Products/WebDriverAgentRunner_iphonesimulator13.5-x86_64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7fe32f23bb70 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[MJSONWP] ** TEST BUILD FAILED **
[MJSONWP] 2020-08-18 08:29:34.495 xcodebuild[40861:863030]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
[MJSONWP] /Users/michele.benedetti/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz/Logs/Test/Test-WebDriverAgentRunner-2020.08.18_08-29-32--0300.xcresult/Staging/2_Test/Diagnostics/WebDriverAgentRunner-6EC4659B-956E-464E-9C9A-92BA41835F8D/WebDriverAgentRunner-049E4E15-6E18-4C43-AE7A-B55DA1C67299/Session-WebDriverAgentRunner-2020-08-18_082934-OHwYJ9.log
[MJSONWP] 2020-08-18 08:29:34.495 xcodebuild[40861:862836] [MT] IDETestOperationsObserverDebug: (DB5B5857-AA29-40FE-BF82-F097DC47E050) Beginning test session WebDriverAgentRunner-DB5B5857-AA29-40FE-BF82-F097DC47E050 at 2020-08-18 08:29:34.495 with Xcode 11E608c on target  {
[MJSONWP] 		SimDevice: iPhone 11 (4366FF61-6348-4BC9-B285-A975D8DA65EE, iOS 13.5, Booted)
[MJSONWP] } (13.5 (17F61))
[MJSONWP] 2020-08-18 08:29:34.577 xcodebuild[40861:862836] [MT] IDETestOperationsObserverDebug: (DB5B5857-AA29-40FE-BF82-F097DC47E050) Finished requesting crash reports. Continuing with testing.
[MJSONWP] *** If you believe this error represents a bug, please attach the result bundle at /Users/michele.benedetti/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz/Logs/Test/Test-WebDriverAgentRunner-2020.08.18_08-29-32--0300.xcresult
[MJSONWP] 2020-08-18 08:29:44.229 xcodebuild[40861:862836] [MT] IDETestOperationsObserverDebug: 9.739 elapsed -- Testing started completed.
[MJSONWP] 2020-08-18 08:29:44.229 xcodebuild[40861:862836] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
[MJSONWP] 2020-08-18 08:29:44.229 xcodebuild[40861:862836] [MT] IDETestOperationsObserverDebug: 9.739 sec, +9.739 sec -- end
[MJSONWP] 2020-08-18 08:29:44.230 xcodebuild[40861:862836] Error Domain=IDEFoundationErrorDomain Code=1 "Cannot launch simulated executable: no file found at /Users/michele.benedetti/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app" UserInfo={NSLocalizedDescription=Cannot launch simulated executable: no file found at /Users/michele.benedetti/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app}
[MJSONWP] Test session results, code coverage, and logs:
[MJSONWP] 	/Users/michele.benedetti/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz/Logs/Test/Test-WebDriverAgentRunner-2020.08.18_08-29-32--0300.xcresult
[MJSONWP] Testing started on 'iPhone 11'
[MJSONWP] Testing failed:
[MJSONWP] 	Building for iOS Simulator, but the linked framework 'CocoaAsyncSocket.framework' was built for tvOS + tvOS Simulator.
[MJSONWP] 	WebDriverAgentRunner:
[MJSONWP] 		WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: Cannot launch simulated executable: no file found at /Users/michele.benedetti/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app))
[MJSONWP] ** TEST EXECUTE FAILED **
[MJSONWP]     at quitAndUninstall (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/driver.js:527:15)
[HTTP] <-- POST /wd/hub/session 500 106239 ms - 3940

**Comment by mykola-mokhnach** [comment]
Please use the most server version

**Comment by michellebenedetti** [comment]
@mykola-mokhnach How to use the most recent server version in Macbook?

**Comment by mykola-mokhnach** [comment]
I think there are enough tutorials: https://www.google.com/search?q=how+to+install+appium+on+mac

Please use Appium forum to ask questions. This is the place for server issues.

**Comment by twsheehan** [comment]
I bumped into something similar and it wasn't due to not being on lates versions. I found https://www.mutuallyhuman.com/blog/webdriveragent-getting-started-with-automated-ios-testing/ helpful as well as making sure the desired capability `"derivedDataPath"` was set as described here https://github.com/appium/appium/issues/14102#issuecomment-619824759
