### ISSUE TITLE
Android Mobile.tap doesn't work with appium 1.18.0

### ISSUE THREAD

**Issue by rieota238** [appium/appium#14667]
## The problem

I'm creating tests with Katalon Studio and appium.

`Mobile.tap(findTestObject('Object Repository/HSB/Login_button'), 30)`

Above step shows it was success, but actually it doesn’t work (the button doesn’t be tapped)

It works with appium 1.14.1 but not 1.18.0, so I suspect appium latest version makes this problem.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.0
* Last Appium version that did not exhibit the issue (if applicable): 1.14.1
* Desktop OS/version used to run Appium: macOS Catalina 10.15.6
* Node.js version (unless using Appium.app|exe): v12.2.0
* Npm or Yarn package manager:6.14.7 
* Mobile platform/version under test: Android emulator ‘system-images;android-29;default;x86’ ‘Nexus 5’
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

[appium.log](https://gist.github.com/rieota238/673cb6d4ab18decc98c0645a76fab661)

**Comment by KazuCocoa** [comment]
What action command was expected?

The log gad below command.
```
[35m[HTTP][39m [90m{"actions":[{"action":"tap","options":{"x":1,"y":1,"element":"7ec0c3b4-ca68-4dfb-9059-3d7982ae09bf"}},{"action":"release","options":{}}]}[39m
```

I guessed `[35m[HTTP][39m [90m{"using":"-android uiautomator","value":"new UiSelector().className(\"android.widget.Button\")"}[39m` was different.

**Comment by rieota238** [comment]
Expected : Tapping button and proceed next page
Problem : Tapping button but nothing happen

Completely same code works as expected by just changing appium version.
I attached appium@1.14.1 log to make sure.

[appium_14.log](https://gist.github.com/rieota238/4887b1a11de40b29db4de9b7b855e1dd)

**Comment by KazuCocoa** [comment]
Thanks.
Could you share these logcats, too?
NodeJS layer seems had no issue.

**Comment by rieota238** [comment]
Thank you for your investigation, I attach the catlog

Log that this problem happened
[logcat appium@1.18.0](https://gist.github.com/rieota238/e502c92e6aa93042fbd78e65d278ebaa)

Log that worked well
[logcat appium@1.14.1](https://gist.github.com/rieota238/8e69e03a796f10c504250125490f27e4)

**Comment by mykola-mokhnach** [comment]
Try to tap by absolute coordinates as a workaround. Also, it makes sense to enable touches tracking in Android developer settings. This way you could see of and where exactly the tap happens

**Comment by mykola-mokhnach** [comment]
btw, I assume `tap` action does not require following `release`. It is either `press-wait-release` or just `tap`

**Comment by mykola-mokhnach** [comment]
Closed because of no response
