### ISSUE TITLE
App doesn’t start when there are more than one .e2e.js mock file

### ISSUE THREAD

**Issue by robto09** [appium/appium#14669]
## The problem

Hellow! I have a file called actions.e2e.js which inside has some action(redux) mocked. I added another file called selectors.e2e.js which have 2 mock selector(redux) methods. Idea its to replace selectors.ts file in execution time. Issue is than when add the selector.e2e.js file with 2 mock selectors inside the app get stuck and dont start running..

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1
* Desktop OS/version used to run Appium: Catalina
* Node.js version (unless using Appium.app|exe): 14.5.0
* Npm or Yarn package manager: 6.14.8
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

https://gist.github.com/robto09/5cc9114339a70be3d29a5ed02e0a223f

<img width="962" alt="Screen Shot 2020-08-20 at 1 28 36 AM" src="https://user-images.githubusercontent.com/28666350/90730066-bea0ef80-e284-11ea-957f-9be49c469864.png">

**Comment by mykola-mokhnach** [comment]
Could you please explain how your issue is related to Appium?

**Comment by robto09** [comment]
> Could you please explain how your issue is related to Appium?

Because Appium its the test framework I am using..

**Comment by mykola-mokhnach** [comment]
Unfortunately it is a bit more complicated that it might look like. There are server and client sides and according to the description above it has nothing to do with the server side, whose issues we track here. I would try to rather ask at Appium forum or at the corresponding client repository (no idea which client is used there, I guess wdio)

**Comment by robto09** [comment]
> Unfortunately it is a bit more complicated that it might look like. There are server and client sides and according to the description above it has nothing to do with the server side, whose issues we track here. I would try to rather ask at Appium forum or at the corresponding client repository (no idea which client is used there, I guess wdio)

Undertand, I am using webdriver.io

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
