### ISSUE TITLE
Question about full manual configuration

### ISSUE THREAD

**Issue by AlexeyNovikov** [appium/appium#14663]
How can I archive WebDriverAgentRunner to ship it to testers?
Because they don't have a development certificate and it would be also nice to prepare as much as we can for them.

When I'm trying to do so I get the error:
![A1feJnQkr7w](https://user-images.githubusercontent.com/30009270/90641349-ce471680-e239-11ea-8b65-37d7bd5f3964.jpg)

And yeah, according to "full manual configuration" everything works fine. But it runs "xcodebuild build-for-testing test-without-building" command.

**Comment by mykola-mokhnach** [comment]
The warning above has been addressed by https://github.com/appium/WebDriverAgent/pull/372, which is available in appium@beta. As a workaround to compile the source you could provide `GCC_TREAT_WARNINGS_AS_ERRORS=0` command line arg to xcodebuild

Regarding 

> How can I archive WebDriverAgentRunner to ship it to testers?
> Because they don't have a development certificate and it would be also nice to prepare as much as we can for them.

Please use Appium forum for questions.

**Comment by timetarget** [comment]
> The warning above has been addressed by [appium/WebDriverAgent#372](https://github.com/appium/WebDriverAgent/pull/372), which is available in appium@beta. As a workaround to compile the source you could provide `GCC_TREAT_WARNINGS_AS_ERRORS=0` command line arg to xcodebuild
> 
> Regarding
> 
> > How can I archive WebDriverAgentRunner to ship it to testers?
> > Because they don't have a development certificate and it would be also nice to prepare as much as we can for them.
> 
> Please use Appium forum for questions.

Thank you. Next time I'll ask in the forum.
When I tried to archive last time I found out that Appium itself made a build by running something like this
xcodebuild build-for-testing test-without-building -project `/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath /Users/***/Desktop/WebDriverAgent-474747 -destination id=*** IPHONEOS_DEPLOYMENT_TARGET=13.5 GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO`
And I changed these flags in Xcode to archive, but forgot to do that for WebDriverAgentLib. It's a shame. Now it's working.
