### ISSUE TITLE
An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up

### ISSUE THREAD

**Issue by ofirya88** [appium/appium#14671]
## The problem

Hi,
I am running automation on emulators farm (12 emulators) and i got this error message ("An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up") durring some tests in the middle of the run .

## Environment

Appium version (or git revision) that exhibits the issue: 1.17.1
Desktop OS/version used to run Appium: Ubuntu 18.04.01 linux
Node.js version (unless using Appium.app|exe): v 12.18.2
Npm or Yarn package manager: 5.3.0
Mobile platform/version under test: emulators - OS 8/9
Real device or emulator/simulator: emulators

## Link to Appium logs
[userDemographicTwoStepsDialogEnabled_appium_log.log](https://github.com/appium/appium/files/5102098/userDemographicTwoStepsDialogEnabled_appium_log.log)

**Comment by mykola-mokhnach** [comment]
Usually such error happens if the server stops responding to appium requests. There might be multiple reasons to that. I would try to retrieve the logcat output first for the time period when this error starts happening and investigate it. 

Also upgrade appium to the most recent version

**Comment by mykola-mokhnach** [comment]
Also I was observing incorrect sessions management on the client side as possible cause, e.g. old sessions were not properly closed before new sessions were created

**Comment by ofirya88** [comment]
@mykola-mokhnach thanks for the comemnt !
The problem is that when i face this issue , my logcat didnt save becasue the adb commands didnt work property .. i got "
Failed to get output from process"

**Comment by mykola-mokhnach** [comment]
then it is most likely the problem with the device/adb itself. Appium itself also uses device connection on top of adb

**Comment by ofirya88** [comment]
Can you think about something that i can do to handle that? or to understand what exactly the problem?

**Comment by mykola-mokhnach** [comment]
I would start with android sdk/tools upgrades

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
