### ISSUE TITLE
JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal start byte 0xf0

### ISSUE THREAD

**Issue by eq1984** [appium/appium#14678]
## The problem

Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up

JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal start byte 0xf0

## Environment

Appium version (or git revision) that exhibits the issue:
Appium : 1.18
Last Appium version that did not exhibit the issue (if applicable):
Desktop OS/version used to run Appium:
Ubuntu
Node.js version (unless using Appium.app|exe):
Appium Desktop App
Npm or Yarn package manager:
Mobile platform/version under test:
Android 5.1.1
Real device or emulator/simulator:
Real Device
Appium CLI or Appium.app|exe:
Appium CLI

## Details

2020-08-26 08:20:17:796 [MJSONWP (9e5bd57e)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up
2020-08-26 08:20:17:796 [MJSONWP (9e5bd57e)]     at JWProxy.command (/usr/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:266:13)
2020-08-26 08:20:17:797 [HTTP] <-- POST /wd/hub/session/9e5bd57e-bb13-48ad-a319-2a3510c2f86a/element 500 11592 ms - 250
2020-08-26 08:20:17:798 [HTTP] 
2020-08-26 08:20:17:912 [Instrumentation] INSTRUMENTATION_RESULT: shortMsg=Native crash
2020-08-26 08:20:17:913 [Instrumentation] INSTRUMENTATION_RESULT: longMsg=Native crash: Aborted
2020-08-26 08:20:17:916 [Instrumentation] INSTRUMENTATION_CODE: 0
2020-08-26 08:20:18:130 [Instrumentation] The process has exited with code 0

## LOGCAT

W/QueryController(30620): Could not detect idle state.
W/System.err(  700): java.lang.NullPointerException: Attempt to read from field 'int android.accessibilityservice.AccessibilityServiceInfo.eventTypes' on a null object reference
W/System.err(  700): 	at android.accessibilityservice.AccessibilityServiceInfo.updateDynamicallyConfigurableProperties(AccessibilityServiceInfo.java:533)
W/System.err(  700): 	at com.android.server.accessibility.AccessibilityManagerService$Service.setServiceInfo(AccessibilityManagerService.java:2092)
W/System.err(  700): 	at android.accessibilityservice.IAccessibilityServiceConnection$Stub.onTransact(IAccessibilityServiceConnection.java:60)
W/System.err(  700): 	at android.os.Binder.execTransact(Binder.java:446)
F/art     (30620): art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal start byte 0xf0
F/art     (30620): art/runtime/check_jni.cc:65]     string: '番茄小说免费 番茄小说🔴🔴番茄小说免费，言情小说，校园小说，更多精彩小说，全文免费阅读。 '
F/art     (30620): art/runtime/check_jni.cc:65]     in call to NewStringUTF
F/art     (30620): art/runtime/check_jni.cc:65]     from java.lang.String org.apache.harmony.xml.ExpatAttributes.getValueByIndex(long, int)
F/art     (30620): art/runtime/check_jni.cc:65] "nioEventLoopGroup-3-1" prio=10 tid=19 Runnable
F/art     (30620): art/runtime/check_jni.cc:65]   | group="main" sCount=0 dsCount=0 obj=0x12eedb80 self=0x4000a648
F/art     (30620): art/runtime/check_jni.cc:65]   | sysTid=30787 nice=-8 cgrp=default sched=0/0 handle=0x4000ab48
F/art     (30620): art/runtime/check_jni.cc:65]   | state=R schedstat=( 2966713131 253229514 4172 ) utm=257 stm=39 core=0 HZ=100
F/art     (30620): art/runtime/check_jni.cc:65]   | stack=0x4d30a000-0x4d30c000 stackSize=1036KB
F/art     (30620): art/runtime/check_jni.cc:65]   | held mutexes= "mutator lock"(shared held)
F/art     (30620): art/runtime/check_jni.cc:65]   native: #00 pc 00004f38  /system/lib/libbacktrace_libc++.so (UnwindCurrent::Unwind(unsigned int, ucontext*)+23)
F/art     (30620): art/runtime/check_jni.cc:65]   native: #01 pc 00003705  /system/lib/libbacktrace_libc++.so (Backtrace::Unwind(unsigned int, ucontext*)+8)
F/art     (30620): art/runtime/check_jni.cc:65]   native: #02 pc 00247651  /system/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, char const*, art::mirror::ArtMethod*)+68)
F/art     (30620): art/runtime/check_jni.cc:65]   native: #03 pc 0022b9c5  /system/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+144)
F/art     (30620): art/runtime/check_jni.cc:65]   native: #04 pc 000b0c33  /system/lib/libart.so (art::JniAbort(char const*, char const*)+582)
F/art     (30620): art/runtime/check_jni.cc:65]   native: #05 pc 000b1379  /system/lib/libart.so (art::JniAbortF(char const*, char const*, ...)+60)
F/art     (30620): art/runtime/check_jni.cc:65]   native: #06 pc 000b3803  /system/lib/libart.so (art::ScopedCheck::Check(bool, char const*, ...) (.constprop.129)+882)
F/art     (30620): art/runtime/check_jni.cc:65]   native: #07 pc 000bc281  /system/lib/libart.so (art::CheckJNI::NewStringUTF(_JNIEnv*, char const*)+36)
F/art     (30620): art/runtime/check_jni.cc:65]   native: #08 pc 00018969  /system/lib/libjavacore.so (???)
F/art     (30620): art/runtime/check_jni.cc:65]   native: #09 pc 00269a9b  /data/dalvik-cache/arm/system@framework@boot.oat (Java_org_apache_harmony_xml_ExpatAttributes_getValueByIndex__JI+102)
F/art     (30620): art/runtime/check_jni.cc:65]   at org.apache.harmony.xml.ExpatAttributes.getValueByIndex(Native method)
F/art     (30620): art/runtime/check_jni.cc:65]   at org.apache.harmony.xml.ExpatAttributes.getValue(ExpatAttributes.java:72)
F/art     (30620): art/runtime/check_jni.cc:65]   at org.jdom2.input.sax.SAXHandler.startElement(SAXHandler.java:653)
F/art     (30620): art/runtime/check_jni.cc:65]   at org.apache.harmony.xml.ExpatParser.startElement(ExpatParser.java:143)
F/art     (30620): art/runtime/check_jni.cc:65]   at org.apache.harmony.xml.ExpatParser.appendBytes(Native method)
F/art     (30620): art/runtime/check_jni.cc:65]   at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:513)
F/art     (30620): art/runtime/check_jni.cc:65]   at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:474)
F/art     (30620): art/runtime/check_jni.cc:65]   at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:316)
F/art     (30620): art/runtime/check_jni.cc:65]   at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:279)
F/art     (30620): art/runtime/check_jni.cc:65]   at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:217)
F/art     (30620): art/runtime/check_jni.cc:65]   at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:253)
F/art     (30620): art/runtime/check_jni.cc:65]   at org.jdom2.input.SAXBuilder.build(SAXBuilder.java:1091)
F/art     (30620): art/runtime/check_jni.cc:65]   at io.appium.uiautomator2.core.AccessibilityNodeInfoDumper.findNodes(AccessibilityNodeInfoDumper.java:213)
F/art     (30620): art/runtime/check_jni.cc:65]   at io.appium.uiautomator2.utils.ElementLocationHelpers.getXPathNodeMatch(ElementLocationHelpers.java:86)
F/art     (30620): art/runtime/check_jni.cc:65]   at io.appium.uiautomator2.handler.FindElement.findElement(FindElement.java:100)
F/art     (30620): art/runtime/check_jni.cc:65]   at io.appium.uiautomator2.handler.FindElement.safeHandle(FindElement.java:72)
F/art     (30620): art/runtime/check_jni.cc:65]   at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:38)
F/art     (30620): art/runtime/check_jni.cc:65]   at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:252)
F/art     (30620): art/runtime/check_jni.cc:65]   at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:242)
F/art     (30620): art/runtime/check_jni.cc:65]   at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:51)
F/art     (30620): art/runtime/check_jni.cc:65]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
F/art     (30620): art/runtime/check_jni.cc:65]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
F/art     (30620): art/runtime/check_jni.cc:65]   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
F/art     (30620): art/runtime/check_jni.cc:65]   at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
F/art     (30620): art/runtime/check_jni.cc:65]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
F/art     (30620): art/runtime/check_jni.cc:65]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
F/art     (30620): art/runtime/check_jni.cc:65]   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
F/art     (30620): art/runtime/check_jni.cc:65]   at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
F/art     (30620): art/runtime/check_jni.cc:65]   at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
F/art     (30620): art/runtime/check_jni.cc:65]   at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
F/art     (30620): art/runtime/check_jni.cc:65]   at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
F/art     (30620): art/runtime/check_jni.cc:65]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
F/art     (30620): art/runtime/check_jni.cc:65]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
F/art     (30620): art/runtime/check_jni.cc:65]   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
F/art     (30620): art/runtime/check_jni.cc:65]   at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
F/art     (30620): art/runtime/check_jni.cc:65]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
F/art     (30620): art/runtime/check_jni.cc:65]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
F/art     (30620): art/runtime/check_jni.cc:65]   at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
F/art     (30620): art/runtime/check_jni.cc:65]   at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
F/art     (30620): art/runtime/check_jni.cc:65]   at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
F/art     (30620): art/runtime/check_jni.cc:65]   at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:514)
F/art     (30620): art/runtime/check_jni.cc:65]   at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:468)
F/art     (30620): art/runtime/check_jni.cc:65]   at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
F/art     (30620): art/runtime/check_jni.cc:65]   at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
F/art     (30620): art/runtime/check_jni.cc:65]   at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
F/art     (30620): art/runtime/check_jni.cc:65]   at java.lang.Thread.run(Thread.java:831)
F/art     (30620): art/runtime/check_jni.cc:65] 
F/art     (30620): art/runtime/runtime.cc:290] Runtime aborting...
F/art     (30620): art/runtime/runtime.cc:290]

**Comment by mykola-mokhnach** [comment]
This is known bug of Android5. Use UiAutomator1 as a workaround or upgrade Android to version 6. Closed as duplicate

**Comment by eq1984** [comment]
@mykola-mokhnach thinks
