### ISSUE TITLE
The error occurs on getting geolocation with some Android devices

### ISSUE THREAD

**Issue by flynnwjf** [appium/appium#14670]
## The problem

I try to run getting geolocation (Location location = driver.location();) on Android devices.
It is passed on Samsung Galaxy Note 8 (8.0) but failed on Nexus 5X (7.0). The settings are totally same with each other.

The error is:
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Cannot parse the actual location values from the command output: Broadcasting: Intent { act=io.appium.settings.location cmp=io.appium.settings/.receivers.LocationInfoReceiver }
Broadcast completed: result=0, data=""

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.0
* Last Appium version that did not exhibit the issue (if applicable): N.A.
* Desktop OS/version used to run Appium: Win 10
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: Nexus 5X/7.0
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
https://gist.github.com/flynnwjf/18b17877500fb3fd8cbff505659ebf6a

## Code To Reproduce Issue [ Good To Have ]
public class Android_Debug_Test {
	AndroidDriver driver;
	
        @BeforeTest
	public void setup() throws Exception {
		  
	    DesiredCapabilities cap = new DesiredCapabilities();
	    cap.setCapability("platformName", "Android"); 
	    cap.setCapability("deviceName", "Galaxy Note 8"); 
	    cap.setCapability("platformVersion", "8.0"); 
	    cap.setCapability("app", "C:\\Users\\wangjief\\Android\\UICatalog-3.10.00-SNAPSHOT.apk");
	    cap.setCapability("appPackage", "com.sample.UICatalog");
	    cap.setCapability("appActivity", "com.sample.UICatalog.Menu");
	    cap.setCapability("newCommandTimeout", 360);
	    cap.setCapability("automationName", "UiAutomator2");
	       
	    driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), cap);
	}

	@Test 
	public void test_Debug() throws InterruptedException{
		
		driver.findElement(MobileBy.AndroidUIAutomator("new UiSelector().textContains(\"TextAndButtons\")")).click();	
		Thread.sleep(5000);
		
                //Get Location
		Location location = driver.location();
		System.out.println("Altitude is " + location.getAltitude());
		System.out.println("Latitude is " + location.getLatitude());
		System.out.println("Longitude is " + location.getLongitude());
		  
		//Set Location
		driver.setLocation(new Location(79.2, 29.1, 18)); 
		Thread.sleep(5000);
		  
		System.out.println("Altitude is " + driver.location().getAltitude());
		System.out.println("Latitude is " + driver.location().getLatitude());
		System.out.println("Longitude is " + driver.location().getLongitude());
	}
	  
	@AfterTest
	public void tearDown() throws Exception {   
	    driver.closeApp();
	    driver.quit();	      
	}

**Comment by mykola-mokhnach** [comment]
Please attach the logcat output

**Comment by flynnwjf** [comment]
> Please attach the logcat output

Hi @mykola-mokhnach , thanks for your checking.
I have uploaded logcat output in https://gist.github.com/flynnwjf/73cfa95f59868b14ca5e06e00a10b656

**Comment by mykola-mokhnach** [comment]
There are no traces of location retrieval event in the logs above. Are you sure these are taken within the appropriate time range. Although these lines look suspicious to me:

> 08-21 10:07:52.919   863   863 W PackageManager: Not granting permission android.permission.WRITE_EXTERNAL_STORAGE to package com.hp.mobileweb because it was previously installed without
> 08-21 10:07:52.919   863   863 W PackageManager: Not granting permission android.permission.READ_EXTERNAL_STORAGE to package com.hp.mobileweb because it was previously installed without
> 08-21 10:07:52.919   863   863 W PackageManager: Not granting permission android.permission.READ_PHONE_STATE to package io.appium.settings because it was previously installed without
> 08-21 10:07:52.919   863   863 W PackageManager: Not granting permission android.permission.ACCESS_FINE_LOCATION to package io.appium.settings because it was previously installed without
> 08-21 10:07:52.919   863   863 W PackageManager: Not granting permission android.permission.ACCESS_COARSE_LOCATION to package io.appium.settings because it was previously installed without
> 08-21 10:07:52.919   863   863 W PackageManager: Not granting permission android.permission.ACCESS_MOCK_LOCATION to package io.appium.settings (protectionLevel=2 flags=0x38083e46)

The settings app must be granted all permissions in order to get the location properly. Did you install it manually or revoke some permissions from it?

**Comment by flynnwjf** [comment]
> There are no traces of location retrieval event in the logs above. Are you sure these are taken within the appropriate time range. Although these lines look suspicious to me:
> 
> > 08-21 10:07:52.919   863   863 W PackageManager: Not granting permission android.permission.READ_PHONE_STATE to package io.appium.settings because it was previously installed without
> > 08-21 10:07:52.919   863   863 W PackageManager: Not granting permission android.permission.ACCESS_FINE_LOCATION to package io.appium.settings because it was previously installed without
> > 08-21 10:07:52.919   863   863 W PackageManager: Not granting permission android.permission.ACCESS_COARSE_LOCATION to package io.appium.settings because it was previously installed without
> > 08-21 10:07:52.919   863   863 W PackageManager: Not granting permission android.permission.ACCESS_MOCK_LOCATION to package io.appium.settings (protectionLevel=2 flags=0x38083e46)
> 
> The settings app must be granted all permissions in order to get the location properly. Did you install it manually or revoke some permissions from it?

Hi @mykola-mokhnach , I am sure I collect all logcat output of geolocation execution with correct time range. For settings app, I don't install it manually or change some permissions. To avoid the conflict, I also try to uninstall settings app at first and let it install automatically during execution. 
I compare the permission of settings app with Samsung Galaxy Note 8 which has no problem on running geolocation. They have no difference with each other. 
Please tell me if you need more info/log. Thanks a lot for your support.

**Comment by mykola-mokhnach** [comment]
Could you try to manually run `adb shell am broadcast -n io.appium.settings/.receivers.LocationInfoReceiver -a io.appium.settings.location` and attach the output and the logcat output?

**Comment by flynnwjf** [comment]
Hi @mykola-mokhnach , here is the log https://gist.github.com/flynnwjf/bf88f7a65d8afecc5ecdc8edaaefd569
![image](https://user-images.githubusercontent.com/17724229/90871059-0c287400-e3cd-11ea-9e14-b221e409707b.png)

**Comment by mykola-mokhnach** [comment]
Closed because of no response
