### ISSUE TITLE
[XCPointerEventPath typeText:atOffset:typingSpeed:]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by candialala** [appium/appium#14677]
## The problem
[XCPointerEventPath typeText:atOffset:typingSpeed:]: unrecognized selector sent to instance

## Environment
* Appium 1.18.0
* Xcode12-beta5
* iphone11 14.0 simulater

## Link to Appium logs
![image](https://user-images.githubusercontent.com/22468260/91273039-3acc9300-e7af-11ea-8ce1-9ccfd0e29c87.png)

**Comment by mykola-mokhnach** [comment]
The fix has been published to appium@beta
