### ISSUE TITLE
iOS "autoAcceptAlerts": true - the actionsheet is automatically tap on the first option 

### ISSUE THREAD

**Issue by anhmainvg** [appium/appium#14681]
## The problem

when adding "autoAcceptAlerts": true to the capability file, and running the code, when I call the function **element.isDisplayed(), the action sheet is automatically clicked on the 1st option**

I see this [issue](https://discuss.appium.io/t/issue-at-clicking-on-action-sheet-in-ios/24875) reported, but it's not fixed, and the solution is removing the  **"autoAcceptAlerts": true** out of the capability file which is not nice

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

Does this issue gets fixed in the latest Appium version or any info reported about this issue, please?

![image](https://user-images.githubusercontent.com/43400649/91383416-4d4dd780-e856-11ea-9b62-8393cea8bde4.png)

**Comment by mykola-mokhnach** [comment]
This is the expected behaviour, which has always been there. 
Note, that it is possible to customize alert/dismiss button locators using the corresponding `acceptAlertButtonSelector`/`dismissAlertButtonSelector` settings.

**Comment by mariushorvat** [comment]
@anhmainvg Hi Anh, I'm having the same issue. Have you got the chance to implement the corresponding acceptAlertButtonSelector/dismissAlertButtonSelector settings.? Can you please share how this is done? Thanks!

**Comment by anhmainvg** [comment]
I have to set the "autoAcceptAlerts": false, in the capability file. Where do you store the config appium file? @mariushorvat . Then change this autoAcceptAlerts

**Comment by mariushorvat** [comment]
@anhmainvg I've set `capabilities.autoAcceptAlerts=false` to make this work, but then all the alerts I have to dismiss them manually 😩.
It's quite weird that Appium dev team decided not to fix this. This affects all IOS dev users.

Have you tried `mykola-mokhnach`'s tip to customize alert/dismiss button locators using the corresponding acceptAlertButtonSelector/dismissAlertButtonSelector settings.?  I've tried documentation but it's very vague and I could not figure out, just yet!

**Comment by anhmainvg** [comment]
hi @mariushorvat , yes, manually dismiss the alert is panic. I tried 2 ways, one working, one not working
**First**: 
acceptAlertButtonSelector: **/XCUIElementTypeButton[`label CONTAINS[c] 'accept'`] 
=> see [link](http://appium.io/docs/en/advanced-concepts/settings/) 
but my app not working by this way (hybrid app), might be the native app should work

**Second**:
Create a global method to tap the coordinate x,y of the alert buttons (you can use appium desktop to find the x,y of buttons) and apply any places that need to accept the alert

 

> public static tapAllowPermission(): void {
>         browser.switchContext(Contexts.NativeApp);
>         browser.pause(3000);
> 
>         browser.touchPerform([
>             {
>                 action: 'tap',
>                 options: {
>                     x: 253,
>                     y: 445
>                 }
>             }
>         ]);
>         browser.switchContext(Contexts.WebView);
>     }
>
