### ISSUE TITLE
getScreenshotAs as BASE64 produces string with new line characters

### ISSUE THREAD

**Issue by pashidlos** [appium/appium#14684]
## The problem

String generated by `getScreenshotAs` method is not valid `base64` string

```
((TakesScreenshot) driver).getScreenshotAs(OutputType.BASE64)
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.1
* Last Appium version that did not exhibit the issue (if applicable): don't know ( 
* Desktop OS/version used to run Appium: iOS Catalina 10.15.6
* Node.js version (unless using Appium.app|exe): 12.18.1
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

![1](https://user-images.githubusercontent.com/5182956/91500241-650f7500-e8c3-11ea-9620-0a190f0ab4d8.png)

## Code To Reproduce Issue [ Good To Have ]

https://github.com/pashidlos/appium-issue-14684/blob/master/src/test/java/TestExample.java

**Comment by KazuCocoa** [comment]
The format is valid for format like RFC 2045, while RFC 4648 is not.
(Ruby also has two methods to encode base64. One is `encode64` and another is `strict_encode64`. The former is rfc 2045 compatible style)

Appium encodes data to base64 string with `Buffer.from(data, 'base64')`
https://nodejs.org/api/buffer.html
It seems it has new line per 64 characters.

I'm not sure the exact reason why they keep the style, but maybe some historical reasons to keep the compatibility of older stuff.
https://stackoverflow.com/questions/19952621/is-it-ok-to-remove-newline-in-base64-encoding/20065991#20065991

**Comment by pashidlos** [comment]
thanks for quick response

**Comment by szprutamich** [comment]
How comes it's not a bug, while
```
      <groupId>io.appium</groupId>
      <artifactId>java-client</artifactId>
```
has a dependency to selenium libs and `org.openqa.selenium.OutputType` uses `Base64.getDecoder().decode(base64Png)` which basically fails for `RFC 2045` and `Base64.getMimeDecoder().decode(base64Png)` would work.
The format should be changed to `RFC 4648` if you use a lib which requires it.

**Comment by valfirst** [comment]
Selenium Java client follows RFC4648 starting from `4.5.1`: https://github.com/SeleniumHQ/selenium/pull/11107 (I'm not sure about other clients). Is it something should be handled on Appium server side? Or Appium Java client side?

**Comment by KazuCocoa** [comment]
Could you create an issue in the Java client?
We maybe update server side to not have `\n` but potentially old Android/chrome (for example) needs the old one. WinAppDriver, for example, as well. So, at least Appium client may need to keep the old one still
