### ISSUE TITLE
Once the screen is loaded, driver is not able to locate element until any manual intervention is done.

### ISSUE THREAD

**Issue by mayankshukla94** [appium/appium#14688]
## The problem

Steps to reproduce:
1. Driver launch an application
2. Login to the application via script
3. Once the screen is loaded, driver is unable to locate element
4. Once we minimize the application, and re-visit the same screen from where we minimized, then driver can locate the elements. Or if we manually click on any element of the screen, then driver starts locating the elements again.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.17.1 and v1.18.0
* Last Appium version that did not exhibit the issue (if applicable): v1.15.1
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): v10.14.0
* Npm or Yarn package manager: npm v6.4.1
* Real device or emulator/simulator: Emulator v30.0.12

## Appium logs

[BaseDriver] Waiting up to 0 ms for condition
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//android.widget.TextView[@text='Home']","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//android.widget.TextView[@text='Home']","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding '//android.widget.TextView[@text='Home']' using 'XPATH' with the contextId: '' multiple: false
[HTTP] <-- POST /wd/hub/session/edafb963-b93b-4c4b-b7cc-ed039fddb311/element - - ms - -
[HTTP] 
[HTTP] --> POST /wd/hub/session/edafb963-b93b-4c4b-b7cc-ed039fddb311/element
[HTTP] {"using":"xpath","value":"//android.widget.TextView[@text='Home']"}
[W3C (edafb963)] Calling AppiumDriver.findElement() with args: ["xpath","//android.widget.TextView[@text='Home']","edafb963-b93b-4c4b-b7cc-ed039fddb311"]
[HTTP] <-- POST /wd/hub/session/edafb963-b93b-4c4b-b7cc-ed039fddb311/element - - ms - -
[HTTP]

And in Eclipse > Console, this is the error I get:

unexpected end of stream on Connection{127.0.0.1:4723, proxy=DIRECT hostAddress=/127.0.0.1:4723 cipherSuite=none protocol=http/1.1}
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-T0F15BC', ip: '192.168.43.164', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_191'
Driver info: driver.version: AndroidDriver

**Comment by mykola-mokhnach** [comment]
Using UiAutomator1 for Android 6+ is obsolete. Please switch to UiAutomator2 or Espresso

**Comment by mayankshukla94** [comment]
> Using UiAutomator1 for Android 6+ is obsolete. Please switch to UiAutomator2 or Espresso

I'm getting below error when using uiautomator2

org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: The application at 'com.renatus.helios.qa' does not exist or is not accessible
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-T0F15BC', ip: '192.168.1.68', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_191'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: The application at 'com.renatus.helios.qa' does not exist or is not accessible
    at getResponseForW3CError (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:381:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-T0F15BC', ip: '192.168.1.68', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_191'
Driver info: driver.version: AndroidDriver

**Comment by mykola-mokhnach** [comment]
Unfortunately we cannot help nothing without the server log

**Comment by mayankshukla94** [comment]
@mykola-mokhnach Here is the log
```
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"appName","appActivity":"appActivity","newCommandTimeout":240,"platformVersion":"9.0 (Pie) - API 28","automationName":"UiAutomator2","unicodeKeyboard":true,"platformName":"ANDROID","udid":"emulator-5554","deviceName":"AOSP on IA Emulator"},"capabilities":{"firstMatch":[{"appium:app":"appName","appium:appActivity":"appActivity","appium:automationName":"UiAutomator2","appium:deviceName":"AOSP on IA Emulator","appium:newCommandTimeout":240,"platformName":"android","appium:platformVersion":"9.0 (Pie) - API 28","appium:udid":"emulator-5554","appium:unicodeKeyboard":true}]}}
[W3C] Calling AppiumDriver.createSession() with args: [{"app":"appName","appActivity":"appActivity","newCommandTimeout":240,"platformVersion":"9.0 (Pie) - API 28","automationName":"UiAutomator2","unicodeKeyboard":true,"platformName":"ANDROID","udid":"emulator-5554","deviceName":"AOSP on IA Emulator"},null,{"firstMatch":[{"appium:app":"appName","appium:appActivity":"appActivity","appium:automationName":"UiAutomator2","appium:deviceName":"AOSP on IA Emulator","appium:newCommandTimeout":240,"platformName":"android","appium:platformVersion":"9.0 (Pie) - API 28","appium:udid":"emulator-5554","appium:unicodeKeyboard":true}]}]
[BaseDriver] Event 'newSessionRequested' logged at 1598940011852 (11:30:11 GMT+0530 (India Standard Time))
[Appium] Appium v1.18.0 creating new AndroidUiautomator2Driver (v1.56.1) session
[Appium] Applying relaxed security to 'AndroidUiautomator2Driver' as per server command line argument. All insecure features will be enabled unless explicitly disabled by --deny-insecure
[BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[BaseDriver] Creating session with W3C capabilities: {
[BaseDriver]   "alwaysMatch": {
[BaseDriver]     "platformName": "android",
[BaseDriver]     "appium:app": "appName",
[BaseDriver]     "appium:appActivity": "appActivity",
[BaseDriver]     "appium:automationName": "UiAutomator2",
[BaseDriver]     "appium:deviceName": "AOSP on IA Emulator",
[BaseDriver]     "appium:newCommandTimeout": 240,
[BaseDriver]     "appium:platformVersion": "9.0 (Pie) - API 28",
[BaseDriver]     "appium:udid": "emulator-5554",
[BaseDriver]     "appium:unicodeKeyboard": true
[BaseDriver]   },
[BaseDriver]   "firstMatch": [
[BaseDriver]     {}
[BaseDriver]   ]
[BaseDriver] }
[BaseDriver] Session created with session id: 744ea1e3-8bb2-4f5b-9bc6-136e6b66d28b
[UiAutomator2] Deleting UiAutomator2 session
[BaseDriver] Event 'newSessionStarted' logged at 1598940011870 (11:30:11 GMT+0530 (India Standard Time))
[W3C] Encountered internal error running command: Error: The application at 'appName' does not exist or is not accessible
[W3C]     at C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\helpers.js:235:13
[W3C] Destroying socket connection
[HTTP] <-- POST /wd/hub/session 500 24 ms - 721
[HTTP] 
```

**Comment by mykola-mokhnach** [comment]
>  "appium:app": "appName",

The error is expected. No app exists at the given path

**Comment by mayankshukla94** [comment]
@mykola-mokhnach I replaced the app name for some personal reason. App do exists at the given path

**Comment by mykola-mokhnach** [comment]
Sorry, it is not possible to advice anything without the real log. Consider hiring a consultant if your tests are limited by NDA

**Comment by mayankshukla94** [comment]
@mykola-mokhnach  It’s just app name, sorry if you hurt anyway. I have added details logs now, could you please check?

```
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"com.renatus.helios.qa","appActivity":"com.renatus.helios.views.activities.SplashScreenActivity","newCommandTimeout":240,"platformVersion":"9.0 (Pie) - API 28","automationName":"UiAutomator2","unicodeKeyboard":true,"platformName":"ANDROID","udid":"emulator-5554","deviceName":"AOSP on IA Emulator"},"capabilities":{"firstMatch":[{"appium:app":"com.renatus.helios.qa","appium:appActivity":"com.renatus.helios.views.activities.SplashScreenActivity","appium:automationName":"UiAutomator2","appium:deviceName":"AOSP on IA Emulator","appium:newCommandTimeout":240,"platformName":"android","appium:platformVersion":"9.0 (Pie) - API 28","appium:udid":"emulator-5554","appium:unicodeKeyboard":true}]}}
[W3C] Calling AppiumDriver.createSession() with args: [{"app":"com.renatus.helios.qa","appActivity":"com.renatus.helios.views.activities.SplashScreenActivity","newCommandTimeout":240,"platformVersion":"9.0 (Pie) - API 28","automationName":"UiAutomator2","unicodeKeyboard":true,"platformName":"ANDROID","udid":"emulator-5554","deviceName":"AOSP on IA Emulator"},null,{"firstMatch":[{"appium:app":"com.renatus.helios.qa","appium:appActivity":"com.renatus.helios.views.activities.SplashScreenActivity","appium:automationName":"UiAutomator2","appium:deviceName":"AOSP on IA Emulator","appium:newCommandTimeout":240,"platformName":"android","appium:platformVersion":"9.0 (Pie) - API 28","appium:udid":"emulator-5554","appium:unicodeKeyboard":true}]}]
[BaseDriver] Event 'newSessionRequested' logged at 1598940011852 (11:30:11 GMT+0530 (India Standard Time))
[Appium] Appium v1.18.0 creating new AndroidUiautomator2Driver (v1.56.1) session
[Appium] Applying relaxed security to 'AndroidUiautomator2Driver' as per server command line argument. All insecure features will be enabled unless explicitly disabled by --deny-insecure
[BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[BaseDriver] Creating session with W3C capabilities: {
[BaseDriver]   "alwaysMatch": {
[BaseDriver]     "platformName": "android",
[BaseDriver]     "appium:app": "com.renatus.helios.qa",
[BaseDriver]     "appium:appActivity": "com.renatus.helios.views.activities.SplashScreenActivity",
[BaseDriver]     "appium:automationName": "UiAutomator2",
[BaseDriver]     "appium:deviceName": "AOSP on IA Emulator",
[BaseDriver]     "appium:newCommandTimeout": 240,
[BaseDriver]     "appium:platformVersion": "9.0 (Pie) - API 28",
[BaseDriver]     "appium:udid": "emulator-5554",
[BaseDriver]     "appium:unicodeKeyboard": true
[BaseDriver]   },
[BaseDriver]   "firstMatch": [
[BaseDriver]     {}
[BaseDriver]   ]
[BaseDriver] }
[BaseDriver] Session created with session id: 744ea1e3-8bb2-4f5b-9bc6-136e6b66d28b
[UiAutomator2] Deleting UiAutomator2 session
[BaseDriver] Event 'newSessionStarted' logged at 1598940011870 (11:30:11 GMT+0530 (India Standard Time))
[W3C] Encountered internal error running command: Error: The application at 'com.renatus.helios.qa' does not exist or is not accessible
[W3C]     at C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\helpers.js:235:13
[W3C] Destroying socket connection
[HTTP] <-- POST /wd/hub/session 500 24 ms - 721
[HTTP] 
```

**Comment by mykola-mokhnach** [comment]
> [BaseDriver]     "appium:app": "com.renatus.helios.qa",

The `app` capability must contain a valid path/url to the app binary

**Comment by mayankshukla94** [comment]
@mykola-mokhnach Thanks for pointing me to the right direction. I have corrected the apk path. It is working fine now.

```
String apkpath = "src/main/java/Resources/Helios_QA.apk";
File app = new File(apkpath);
caps.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
```
