### ISSUE TITLE
How do I fetch the CSS values of an element in Native Apps. I see it is done via getCSSValue but only for WebView - any other alternate solution to get css values in NATIVE Apps ?

### ISSUE THREAD

**Issue by parameshvijay** [appium/appium#14691]
## The problem

How do I fetch the CSS values of an element in Native Apps. I see it is done via getCSSValue but only for WebView - any other alternate solution to get css values in NATIVE Apps ?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.0-1
* Desktop OS/version used to run Appium:  Windows 10
* Node.js version (unless using Appium.app|exe): V12.16.3
* Mobile platform/version under test: Honor, Android 9
* Real device or emulator/simulator: Real device

## Details
I'm trying the fetch the BACKGROUND COLOR of a toggle button to confirm the selection by using getCSSValue but WebDriverException error message is displayed as "org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 404 - ""

**Comment by mykola-mokhnach** [comment]
This is impossible in native context. Accessibility manager does not know about any internal element properties.
