### ISSUE TITLE
WebDriverAgent for iOS 14 

### ISSUE THREAD

**Issue by BrightHai** [appium/appium#14696]
## The problem

Trying to build WDA(https://github.com/appium/WebDriverAgent)  with Xcode-12Beta6, got exception

![image](https://user-images.githubusercontent.com/11002329/91928157-e759c800-ed0d-11ea-90cf-3727a3ed6a1b.png)

## Environment

* Desktop OS/version used to run Appium:  MacOS 10.15 Catalina
* Mobile platform/version under test:  iOS 14
* Real device or emulator/simulator:   RealDevice

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by KazuCocoa** [comment]
What version of robbiehanson/CocoaAsyncSocket did your environment have in carthage?
It should be fixed in https://github.com/appium/WebDriverAgent/pull/350
If you manually have built the code since older versions, you should update your carthage build.

**Comment by BrightHai** [comment]
> carthage 
![image](https://user-images.githubusercontent.com/11002329/91931761-ec6f4500-ed16-11ea-857f-e7616ca7b22f.png)
How to get robbiehanson/CocoaAsyncSocket info in carthage?

**Comment by KazuCocoa** [comment]
In `Carthage/Cartfile.resolved`

**Comment by BrightHai** [comment]
cat Cartfile.resolved

github "appium/YYCache" "1.1.0"
github "robbiehanson/CocoaAsyncSocket" "7.6.4"

**Comment by KazuCocoa** [comment]
Your carthage modules were old.
Please up to date as https://github.com/appium/WebDriverAgent/blob/a44bb179a74e3bf29516e8b72a1fdbe801b9da30/README.md#getting-started-on-this-repository

It should be like https://github.com/appium/WebDriverAgent/blob/master/Cartfile.resolved

**Comment by ansonGitHub** [comment]
> Carthage/Cartfile.resolved
what's the path for this file?

**Comment by KazuCocoa** [comment]
It is in appium-webdriveragent module (via npm install case)
