### ISSUE TITLE
Appium server memory leak because image template is not released

### ISSUE THREAD

**Issue by yejianfengblue** [appium/appium#14693]
## The problem

Appium server memory grows up when find by image because the image is never released from memory.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Manjaro 20.1 KDE, kernel 5.7.15-1
* Node.js version (unless using Appium.app|exe): 14.8.0
* Npm or Yarn package manager: npm 6.14.7
* Mobile platform/version under test: Android 6.0, 1280x720
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

When I start appium server from clean and create a `WebDriver`, appium server memory usage is 50MB.
If I run a script which loops finding element by image 20 times, the appium server memory grows up to 200MB. If the script loops for hours, memory reaches GB size. The image template size is 1MB.
From the heap snapshot, 50% of shallow size are strings whose value are similar to image base64 value. 30% of shallow size are "System / JSArrayBufferData".
Find the heap snapshot file in [Github](https://github.com/yejianfengblue/appium-image-not-released-from-memory) or [Google Drive](https://drive.google.com/file/d/1nlo4cQ1qNRaqQs92WoF_vIi5t3t6UMn6/view?usp=sharing). Sorry I got error when upload to gist.

## Link to Appium logs

https://gist.github.com/yejianfengblue/e0552fbb5249e8916e55b5efbfa03ff2

## Code To Reproduce Issue [ Good To Have ]

```python
from appium import webdriver
from selenium.common.exceptions import NoSuchElementException
device = "n2"
udid = device + ":5555"
caps = dict(
            platformName='Android',
            platformVersion='23',
            automationName='uiautomator2',
            deviceName=device,
            udid=udid,
            newCommandTimeout=3600,
            noReset=True
        )
driver = webdriver.Remote('http://localhost:4723/wd/hub', caps)
while True:
    try:
        driver.find_element_by_image('./okabe.png')
        print("okabe.png found")
    except NoSuchElementException :
        print("okabe.png not found")
```
Find the test image `okabe.png` in [Github](https://github.com/yejianfengblue/appium-image-not-released-from-memory)

**Comment by yejianfengblue** [comment]
Remove irrelevant driver setting

**Comment by mykola-mokhnach** [comment]
Please try to apply https://github.com/appium/appium-base-driver/pull/430 and check if it helps to resolve the issue. It is hard to say what exactly is flooding the memory, but the cancellation token is being observed quite often in the heap snapshot.

**Comment by yejianfengblue** [comment]
My appium is installed in `/home/k/.npm-global/lib/node_modules/appium/`. So should I manually comment out the line of `cancelToken` in file `/home/k/.npm-global/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js`? And then restart appium server?
Sorry I have little experience to Node.js. If I'm wrong, is there any reference about how to apply the patch?

**Comment by mykola-mokhnach** [comment]
Check out the patched module sources locally and then link it to your npm deployment similarly to what is described in https://github.com/appium/appium/issues/13227#issuecomment-531812534

**Comment by yejianfengblue** [comment]
After applying patch https://github.com/appium/appium-base-driver/pull/430, the appium server memory stays around 200MB when I connect 2 Android devices using Python. So I think the patch works. Thank you very much. mykola.

**Comment by yejianfengblue** [comment]
Below is how I applied the patch. For reference of anyone who wants to apply also.
```shell
[~]$ mkdir appium-14693 && cd appium-14693
[~/appium-14693]$ git clone https://github.com/mykola-mokhnach/appium-base-driver
[~/appium-14693]$ cd appium-base-driver
[~/appium-14693]$ git checkout -b no_cancel origin/no_cancel
[~/appium-14693]$ npm link
[~/appium-14693]$ cd ~/.npm-global/lib/node_modules/appium  # my original installation
[~/.npm-global/lib/node_modules/appium]$ npm install --save appium-base-driver
[~/.npm-global/lib/node_modules/appium]$ npm link appium-base-driver
[~/.npm-global/lib/node_modules/appium]$ node .  # run appium server
```
