### ISSUE TITLE
Not able to find an element after switching to webView .... -[W3C] Matched W3C error code 'no such element' to NoSuchElementError'

### ISSUE THREAD

**Issue by arvinds97** [appium/appium#14697]
APPIUM LOGCAT :
[W3C] Matched W3C error code 'no such element' to NoSuchElementError
[BaseDriver] Waited for 8888 ms so far
[WD Proxy] Matched '/element' to command name 'findElement'
[WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8202/wd/hub/session/8ff8fa0c-d072-4f82-9602-61fde2c1a6cf/element] with body: {"strategy":"xpath","selector":"//*[contains(@text, 'CANCEL')]","context":"","multiple":false}
[WD Proxy] Got response with status 404: {"sessionId":"8ff8fa0c-d072-4f82-9602-61fde2c1a6cf","value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters","stacktrace":"io.appium.uiautomator2.common.exceptions.ElementNotFoundException: An element could not be located on the page using the given search parameters\n\tat io.appium.uiautomator2.handler.FindElement.findElement(FindElement.java:102)\n\tat io.appium.uiautomator2.handler.FindElement.safeHandle(FindElement.java:72)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:38)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:252)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:242)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:51)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerCon...
_Originally posted by @lock in https://github.com/appium/appium/issues/5180#issuecomment-619337869_

**Comment by mykola-mokhnach** [comment]
Please fill out the issue report properly according to the given template.

Is the target element present in page source?

**Comment by arvinds97** [comment]
CODE SNIPPET  
Android_Settings_Page asp = new Android_Settings_Page(driver);
		 WebDriverWait wait = new WebDriverWait(driver, 120);
		 Thread.sleep(5000);
		 //asp.skipButon().click();
		 driver.findElement(By.id("skip_button")).click();
		 Thread.sleep(5000);
		 driver.findElement(By.id("com.HIDDEN:id/btn_login")).click();
wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("email")));   // where I'm getting the error
		System.out.println("sending email");

**Comment by arvinds97** [comment]
Yes , the Target element is present in the page source. @mykola-mokhnach . I'm able to locate the element and retrieve it's id from Appium Desktop Inspector.

But for some reason , while running it on my emulator, it throws that error , before even the page loads.
I have tried adding a Thread.sleep , didn't work.
I also tried http://appium.io/docs/en/writing-running-appium/web/hybrid/ , but that didn't work too. Tried another emulator too, didn't work.
It surprisingly works in my teammates emulator. It's weird . 
I'm just thinking out loud here, is it related to your java-client version ? Or is something wrong with the findElement function ?

**Comment by mykola-mokhnach** [comment]
Please provide the requested information first (aka server version, env, etc). I don't want to guess anything. 

Try to print the page sauce exactly before the lookup is executed.

**Comment by arvinds97** [comment]
Oh,I"m sorry ! 
Appium Version - 1.17.0
Using Java 
Testing on Android Emulator.
Desktop : Windows
All libraries are up-to-date and this is a maven project.

**Comment by mykola-mokhnach** [comment]
yes. In general only chromedriver is responsible for lookups, Appium is just a proxy there. So I would rather consider reporting an issue to Google

**Comment by mykola-mokhnach** [comment]
Although, I don't see the full log. The stack shows the exception happens in native context. I'm not quite sure what you are trying to achieve there and which context should be set as active for the lookup.

**Comment by arvinds97** [comment]
So this is what is basically happening:
Page 1: Native - A button for logging in.
Page 2 : Page 1 navigates to a webview using chrome.
My code - trying to find the textbox on the page in which I can enter the mail. This is where the error is being thrown.

The complete log   : 
 Cached the protocol value 'MJSONWP' for the new session e0c2adab-bd57-4ced-a819-c6a1fe8f3c20
[MJSONWP (e0c2adab)] Responding to client with driver.createSession() result: {"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"app":"/Users/SudheerA/Documents/AndroidApp/HaloApp-2.24.0-62885-release.apk","appPackage":"com.checkpt.oatmobile","clearSystemFiles":true,"deviceName":"emulator-5554","version":"8.0","appActivity":"com.checkpt.oatmobile.modules.launcher.LauncherViewController","newCommandTimeout":2147482,"autoGrantPermissions":true,"unicodeKeyboard":true,"sessionOverride":true,"udid":"emulator-5554","platformName":"Android","autoAcceptAlerts":true},"**hidden**
[HTTP] <-- POST /wd/hub/session 200 20243 ms - 1451
[HTTP] 
[HTTP] --> POST /wd/hub/session/e0c2adab-bd57-4ced-a819-c6a1fe8f3c20/timeouts/implicit_wait
[HTTP] {"ms":60000}
[MJSONWP (e0c2adab)] Calling AppiumDriver.implicitWait() with args: [60000,"e0c2adab-bd57-4ced-a819-c6a1fe8f3c20"]
[BaseDriver] Set implicit wait to 60000ms
[MJSONWP (e0c2adab)] Responding to client with driver.implicitWait() result: null
[HTTP] <-- POST /wd/hub/session/e0c2adab-bd57-4ced-a819-c6a1fe8f3c20/timeouts/implicit_wait 200 1 ms - 76
[HTTP] 
[HTTP] --> POST /wd/hub/session/e0c2adab-bd57-4ced-a819-c6a1fe8f3c20/element
[HTTP] {"using":"id","value":"skip_button"}
[MJSONWP (e0c2adab)] Calling AppiumDriver.findElement() with args: ["id","skip_button","e0c2adab-bd57-4ced-a819-c6a1fe8f3c20"]
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Waiting up to 60000 ms for condition
[WD Proxy] Matched '/element' to command name 'findElement'
[WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8204/wd/hub/session/a092e8e6-b2fb-43af-a89f-7445506707f4/element] with body: {"strategy":"id","selector":"skip_button","context":"","multiple":false}
[WD Proxy] Got response with status 200: {"sessionId":"a092e8e6-b2fb-43af-a89f-7445506707f4","value":{"ELEMENT":"bedc5e95-17fc-4d64-af1e-4558b947c55d","element-6066-11e4-a52e-4f735466cecf":"bedc5e95-17fc-4d64-af1e-4558b947c55d"}}
[MJSONWP (e0c2adab)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"bedc5e95-17fc-4d64-af1e-4558b947c55d","ELEMENT":"bedc5e95-17fc-4d64-af1e-4558b947c55d"}
[HTTP] <-- POST /wd/hub/session/e0c2adab-bd57-4ced-a819-c6a1fe8f3c20/element 200 55 ms - 199
[HTTP] 
[HTTP] --> POST /wd/hub/session/e0c2adab-bd57-4ced-a819-c6a1fe8f3c20/element/bedc5e95-17fc-4d64-af1e-4558b947c55d/click
[HTTP] {"id":"bedc5e95-17fc-4d64-af1e-4558b947c55d"}
[MJSONWP (e0c2adab)] Calling AppiumDriver.click() with args: ["bedc5e95-17fc-4d64-af1e-4558b947c55d","e0c2adab-bd57-4ced-a819-c6a1fe8f3c20"]
[WD Proxy] Matched '/element/bedc5e95-17fc-4d64-af1e-4558b947c55d/click' to command name 'click'
[WD Proxy] Proxying [POST /element/bedc5e95-17fc-4d64-af1e-4558b947c55d/click] to [POST http://127.0.0.1:8204/wd/hub/session/a092e8e6-b2fb-43af-a89f-7445506707f4/element/bedc5e95-17fc-4d64-af1e-4558b947c55d/click] with body: {"element":"bedc5e95-17fc-4d64-af1e-4558b947c55d"}
[WD Proxy] Got response with status 200: {"sessionId":"a092e8e6-b2fb-43af-a89f-7445506707f4","value":null}
[MJSONWP (e0c2adab)] Responding to client with driver.click() result: null
[HTTP] <-- POST /wd/hub/session/e0c2adab-bd57-4ced-a819-c6a1fe8f3c20/element/bedc5e95-17fc-4d64-af1e-4558b947c55d/click 200 24 ms - 76
[HTTP] 
[HTTP] --> POST /wd/hub/session/e0c2adab-bd57-4ced-a819-c6a1fe8f3c20/element
[HTTP] {"using":"id","value":"com.checkpt.oatmobile:id/btn_login"}
[MJSONWP (e0c2adab)] Calling AppiumDriver.findElement() with args: ["id","com.checkpt.oatmobile:id/btn_login","e0c2adab-bd57-4ced-a819-c6a1fe8f3c20"]
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Waiting up to 60000 ms for condition
[WD Proxy] Matched '/element' to command name 'findElement'
[WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8204/wd/hub/session/a092e8e6-b2fb-43af-a89f-7445506707f4/element] with body: {"strategy":"id","selector":"com.checkpt.oatmobile:id/btn_login","context":"","multiple":false}
[WD Proxy] Got response with status 200: {"sessionId":"a092e8e6-b2fb-43af-a89f-7445506707f4","value":{"ELEMENT":"3d4d1e2e-dee3-48d7-b50d-f66c87f7ad2d","element-6066-11e4-a52e-4f735466cecf":"3d4d1e2e-dee3-48d7-b50d-f66c87f7ad2d"}}
[MJSONWP (e0c2adab)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"3d4d1e2e-dee3-48d7-b50d-f66c87f7ad2d","ELEMENT":"3d4d1e2e-dee3-48d7-b50d-f66c87f7ad2d"}
[HTTP] <-- POST /wd/hub/session/e0c2adab-bd57-4ced-a819-c6a1fe8f3c20/element 200 51 ms - 199
[HTTP] 
[HTTP] --> POST /wd/hub/session/e0c2adab-bd57-4ced-a819-c6a1fe8f3c20/element/3d4d1e2e-dee3-48d7-b50d-f66c87f7ad2d/click
[HTTP] {"id":"3d4d1e2e-dee3-48d7-b50d-f66c87f7ad2d"}
[MJSONWP (e0c2adab)] Calling AppiumDriver.click() with args: ["3d4d1e2e-dee3-48d7-b50d-f66c87f7ad2d","e0c2adab-bd57-4ced-a819-c6a1fe8f3c20"]
[WD Proxy] Matched '/element/3d4d1e2e-dee3-48d7-b50d-f66c87f7ad2d/click' to command name 'click'
[WD Proxy] Proxying [POST /element/3d4d1e2e-dee3-48d7-b50d-f66c87f7ad2d/click] to [POST http://127.0.0.1:8204/wd/hub/session/a092e8e6-b2fb-43af-a89f-7445506707f4/element/3d4d1e2e-dee3-48d7-b50d-f66c87f7ad2d/click] with body: {"element":"3d4d1e2e-dee3-48d7-b50d-f66c87f7ad2d"}
[WD Proxy] Got response with status 200: {"sessionId":"a092e8e6-b2fb-43af-a89f-7445506707f4","value":null}
[MJSONWP (e0c2adab)] Responding to client with driver.click() result: null
[HTTP] <-- POST /wd/hub/session/e0c2adab-bd57-4ced-a819-c6a1fe8f3c20/element/3d4d1e2e-dee3-48d7-b50d-f66c87f7ad2d/click 200 19 ms - 76
[HTTP] 
[HTTP] --> POST /wd/hub/session/e0c2adab-bd57-4ced-a819-c6a1fe8f3c20/element
[HTTP] {"using":"id","value":"email"}
[MJSONWP (e0c2adab)] Calling AppiumDriver.findElement() with args: ["id","email","e0c2adab-bd57-4ced-a819-c6a1fe8f3c20"]
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Waiting up to 60000 ms for condition
[WD Proxy] Matched '/element' to command name 'findElement'
[WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8204/wd/hub/session/a092e8e6-b2fb-43af-a89f-7445506707f4/element] with body: {"strategy":"id","selector":"email","context":"","multiple":false}
[WD Proxy] Got response with status 404: {"sessionId":"a092e8e6-b2fb-43af-a89f-7445506707f4","value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters","stacktrace":"io.appium.uiautomator2.common.exceptions.ElementNotFoundException: An element could not be located on the page using the given search parameters\n\tat io.appium.uiautomator2.handler.FindElement.safeHandle(FindElement.java:78)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:38)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:252)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:242)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:51)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.chann...
[W3C] Matched W3C error code 'no such element' to NoSuchElementError
[BaseDriver] Waited for 850 ms so far
[WD Proxy] Matched '/element' to command name 'findElement'
[WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8204/wd/hub/session/a092e8e6-b2fb-43af-a89f-7445506707f4/element] with body: {"strategy":"id","selector":"email","context":"","multiple":false}
[WD Proxy] Got response with status 404: {"sessionId":"a092e8e6-b2fb-43af-a89f-7445506707f4","value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters","stacktrace":"io.appium.uiautomator2.common.exceptions.ElementNotFoundException: An element could not be located on the page using the given search parameters\n\tat io.appium.uiautomator2.handler.FindElement.safeHandle(FindElement.java:78)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:38)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:252)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:242)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:51)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.chann...
[W3C] Matched W3C error code 'no such element' to NoSuchElementError



But yeah, I get what you are saying, the problem is not with appium I geuss. Thanks !

**Comment by mykola-mokhnach** [comment]
I don't observe the context is switched to web view in the log snippet above. Again make sure the lookup request is being executed in the correct context and print the page source right before the lookup to make sure the element is really there and no race condition is happening.

Closed as not an issue
