### ISSUE TITLE
How to push picture to iOS real device?

### ISSUE THREAD

**Issue by jackwangchs** [appium/appium#14698]
## The problem

Since ifuse was removed from appium, now it always failed pushing picture/file to iOS real devices using PushFile method. Any new method or way to do that now?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1+
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real device

**Comment by mykola-mokhnach** [comment]
Please use Appium forum to ask quesitions
