### ISSUE TITLE
Appium v1.18.0 &  - Unable to identify the elements with xpath - @name attribute or @label specified intermittently

### ISSUE THREAD

**Issue by udaykittu** [appium/appium#14708]
## The problem

While inspecting the elements in Appium Desktop inspector, XPath with @name & @label attributes are displayed. But while executing the code from java framework, it is unable to find the element intermittently

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.0 & 1.17.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS Catalina
* Node.js version (unless using Appium.app|exe): 14.5.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: 13.2.1 & 13.5
* Real device or emulator/simulator: Real Device & Simulators
* Appium CLI or Appium.app|exe: 1.18.0 & 1.17.1

## Details

<img width="1073" alt="Screen Shot 2020-09-04 at 2 22 50 PM" src="https://user-images.githubusercontent.com/25000065/92220874-3ba1ab00-eeba-11ea-9840-51dc994dd22f.png">
<img width="1077" alt="Screen Shot 2020-09-04 at 2 23 09 PM" src="https://user-images.githubusercontent.com/25000065/92220875-3c3a4180-eeba-11ea-89c8-acc52430da6f.png">
<img width="1081" alt="Screen Shot 2020-09-04 at 2 23 19 PM" src="https://user-images.githubusercontent.com/25000065/92220880-3cd2d800-eeba-11ea-934f-e03c5d39917d.png">

## Link to Appium logs

https://gist.github.com/udaykittu/8befee9ccded4f6d2b4fa707257791ce

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
This could be a race condition issue. Try to add wait timers. Also, it makes sense to print the page source right before the lookup is executed to make sure the detonation element(s) is there.

**Comment by jyotiprk991** [comment]
I also faced the same issue, All the Xpath failed to respond, Which results, ClickOnPartialText and isPartialTextPresent failed all over the framework

**Comment by mykola-mokhnach** [comment]
Closed because of no response
