### ISSUE TITLE
appium 1.18.1 - problem with starting appium session, unrecognized chrome option BrowserName

### ISSUE THREAD

**Issue by HasaMatej** [appium/appium#14707]
## The problem

With release of new version 1.18.1 we are not able to start appium session for browser testing or real device as well as on emulator.  Every attempt ends with message: 
_Status Code: 500 - Error while starting appium session: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. Original error: invalid argument: cannot parse capability: chromeOptions\nfrom invalid argument: unrecognized chrome option: BrowserName\n (Driver info: chromedriver=84.0.4147.30 (48b3e868b4cc0aa7e8149519690b6f6949e110a8-refs/branch-heads/4147@{#310}),platform=Linux 4.15.0-64-generic x86_64)"},"sessionId":null}_

We did not change any configuration and we use still the same capabilities. 
`{
  "desiredCapabilities": {
    "testobject_platform_name": "Android",
    "testobject_test_name": "SLTEST_withChromeOptions",
    "deviceName": "HTC_10_real",
    "goog:chromeOptions": {
      "LeaveBrowserRunning": false,
      "Arguments": [
        "no-first-run",
        "disable-features=TranslateUI",
        "disable-notifications",
        "no-default-browser-check",
        "start-maximized",
        "disable-webgl",
        "blacklist-webgl",
        "blacklist-accelerated-compositing",
        "disable-accelerated-2d-canvas",
        "disable-accelerated-compositing",
        "disable-accelerated-layers",
        "disable-accelerated-plugins",
        "disable-accelerated-video",
        "disable-accelerated-video-decode",
        "disable-gpu",
        "disable-infobars",
        "test-type",
        "deny-permission-prompts"
      ],
      "Extensions": [],
      "UseSpecCompliantProtocol": false,
      "BrowserName": "chrome",
      "UnhandledPromptBehavior": 0,
      "PageLoadStrategy": 0
    },
    "nativeWebScreenshot": true,
    "newCommandTimeout": 90,
    "automationName": "UiAutomator2",
    "name": "SLTEST_withChromeOptions",
    "browserName": "Chrome",
    "unicodeKeyboard": true,
    "chromeOptions": {
      "w3c": false
    },
    "platformName": "Android",
    "resetKeyboard": true,
    "testobject_phone_only": true
  }
}`

On version 1.17.1 we do not face such an issue.

## Environment

* Appium version where we face the issue - 1.18.1
* Last Appium version that did not exhibit the issue - 1.17.1
* Using C# and Selenium 3.141
* Happens on real device as well as emulator (Android, v8.0.0)

## Link to Appium log

Please find the appium log here
https://gist.github.com/HasaMatej/5e7c1bd5191c59bc3f3a144b1b4bda83

**Comment by mykola-mokhnach** [comment]
The error is thrown by chromedriver. It looks like Google has made chromeOptions validation more strict, so it now throws an error because of unknown `BrowserName` cap. Please fix your capabilities or report the issue to TO customer support if their system adds such capability automatically.

Closed as not an issue.

**Comment by HasaMatej** [comment]
@mykola-mokhnach Hello and thank you for the reply.

We face the issue on different versions of chromedriver and that is why we reported it as an Appium bug.

Appium v1.17.1 and Chromedriver v78.0.3904.11 -> correct behaviour
Appium v1.17.1 and Chromedriver v84.0.4147.30 -> correct behaviour
Appium v1.17.1 and Chromedriver v85.0.4183.87 -> correct behaviour

Appium v1.18.1 and Chromedriver v78.0.3904.11 -> issue occures as we reported
Appium v1.18.1 and Chromedriver v84.0.4147.30 -> issue occures as we reported
Appium v1.18.1 and Chromedriver v85.0.4183.87 -> issue occures as we reported

It fails for us only with v1.18.1 of appium.
Thanks for any kind of reply and have a nice day.

**Comment by mykola-mokhnach** [comment]
Unfortunately, I don't see how the issue could be resolved from Appium side. The above capability name is unknown for chromedriver and must be removed.

**Comment by KazuCocoa** [comment]
I tried a bit on my local. Your request was only MJSONWP format, then

- with 1.17.1, `goog:chromeOptions` was dropped. Only `chromeOptions` was accepted by Appium
- with 1.18.1, both options were merged as `chromeOptions` to chromedriver, so the paring error happened
