### ISSUE TITLE
Failed to build WebdriverAgentRunner in Appium - 1.15.0

### ISSUE THREAD

**Issue by jyotiprk991** [appium/appium#14711]
## The problem

Failed to build WebdriverAgentRunner in Appium - 1.15.0 
After doing bootstrap.sh
Getting Target Integrity error for CocoAsync.socket.framework error

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS 10.15.5
* Node.js version (unless using Appium.app|exe): 9.9.0
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: 13.5.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

<img width="1131" alt="Screenshot 2020-09-05 at 9 08 15 PM" src="https://user-images.githubusercontent.com/26240702/92308715-7809ff80-efbd-11ea-9e2d-4de1cf36e857.png">

**Comment by mykola-mokhnach** [comment]
Please use the most recent server version. Unfortunately we don't provide patches to older releases.

**Comment by jyotiprk991** [comment]
In the latest Server Version, I am facing Identifier Error (Unable to locate via Xpath)
