### ISSUE TITLE
There is no way to use uiautomator2

### ISSUE THREAD

**Issue by ArmyMedalMei** [appium/appium#14714]
## The problem

Sorry,There is no way to use uiautomator2，See code and log for details

## Environment

* Appium version (or git revision) that exhibits the issue:v1.18.0
* Last Appium version that did not exhibit the issue (if applicable):Yes
* Desktop OS/version used to run Appium:Desktop
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:Npm
* Mobile platform/version under test:Mobile
* Real device or emulator/simulator:Real Device
* Appium CLI or Appium.app|exe:Appium.exe
* Android Version:≥6.0

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

[WD Proxy] socket hang up
[Instrumentation] Error in startServer(io.appium.uiautomator2.server.test.AppiumUiAutomator2Server):
[Instrumentation] java.lang.ExceptionInInitializerError
[Instrumentation] 	at io.appium.uiautomator2.server.mjpeg.MjpegScreenshotServer.(MjpegScreenshotServer.java:41)
[Instrumentation] 	at io.appium.uiautomator2.server.mjpeg.MjpegScreenshotServer.(MjpegScreenshotServer.java:35)
[Instrumentation] 	at io.appium.uiautomator2.server.ServerInstrumentation.startMjpegServer(ServerInstrumentation.java:241)
[Instrumentation] 	at io.appium.uiautomator2.server.test.AppiumUiAutomator2Server.startServer(AppiumUiAutomator2Server.java:31)
[Instrumentation] 	at java.lang.reflect.Method.invoke(Native Method)
[Instrumentation] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[Instrumentation] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[Instrumentation] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[Instrumentation] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[Instrumentation] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
[Instrumentation] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
[Instrumentation] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
[Instrumentation] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[Instrumentation] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[Instrumentation] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[Instrumentation] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[Instrumentation] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[Instrumentation] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[Instrumentation] 	at androidx.test.runner.AndroidJUnit4.run(AndroidJUnit4.java:104)
[Instrumentation] 	at org.junit.runners.Suite.runChild(Suite.java:128)
[Instrumentation] 	at org.junit.runners.Suite.runChild(Suite.java:27)
[Instrumentation] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[Instrumentation] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[Instrumentation] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[Instrumentation] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[Instrumentation] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[Instrumentation] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[Instrumentation] 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[Instrumentation] 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[Instrumentation] 	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
[Instrumentation] 	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
[Instrumentation] 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1886)
[Instrumentation] Caused by: java.lang.IllegalStateException: UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@f9af434already registered!
[Instrumentation] 	at android.os.Parcel.readException(Parcel.java:1628)
[Instrumentation] 	at android.os.Parcel.readException(Parcel.java:1573)
[Instrumentation] 	at android.app.IUiAutomationConnection$Stub$Proxy.connect(IUiAutomationConnection.java:236)
[Instrumentation] 	at android.app.UiAutomation.connect(UiAutomation.java:197)
[Instrumentation] 	at android.app.Instrumentation.getUiAutomation(Instrumentation.java:1865)
[Instrumentation] 	at androidx.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1135)
[Instrumentation] 	at androidx.test.uiautomator.QueryController.(QueryController.java:95)
[Instrumentation] 	at androidx.test.uiautomator.UiDevice.(UiDevice.java:109)
[Instrumentation] 	at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
[Instrumentation] 	at io.appium.uiautomator2.utils.Device.getUiDevice(Device.java:40)
[Instrumentation] 	at io.appium.uiautomator2.model.internal.CustomUiDevice.(CustomUiDevice.java:75)
[Instrumentation] 	at io.appium.uiautomator2.model.internal.CustomUiDevice.getInstance(CustomUiDevice.java:90)
[Instrumentation] 	at io.appium.uiautomator2.server.mjpeg.MjpegScreenshotStream.(MjpegScreenshotStream.java:43)
[Instrumentation] 	... 32 more
[Instrumentation] INSTRUMENTATION_RESULT: shortMsg=java.lang.IllegalStateException
[Instrumentation] INSTRUMENTATION_RESULT: longMsg=java.lang.IllegalStateException: Cannot call disconnect() while connecting!
[Instrumentation] INSTRUMENTATION_CODE: 0
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8200/wd/hub/status] with no body

## Code To Reproduce Issue [ Good To Have ]

 [OneTimeSetUp]
        public void BeforeAll()
        {
            AppiumOptions capabilities = Env.isSauce()
                ? Caps.getAndroid501Caps(Apps.get("androidApiDemos"))
                : Caps.getAndroid19Caps(Apps.get("androidApiDemos"));
            if (Env.isSauce())
            {
                capabilities.AddAdditionalCapability("username", Env.getEnvVar("SAUCE_USERNAME"));
                capabilities.AddAdditionalCapability("accessKey", Env.getEnvVar("SAUCE_ACCESS_KEY"));
                capabilities.AddAdditionalCapability("name", "android - complex");
                capabilities.AddAdditionalCapability("tags", new string[] {"sample"});
            }
            Uri serverUri = Env.isSauce() ? AppiumServers.sauceURI : AppiumServers.LocalServiceURIAndroid;
            driver = new AndroidDriver<AppiumWebElement>(serverUri, capabilities, Env.INIT_TIMEOUT_SEC);
            driver.Manage().Timeouts().ImplicitWait = Env.IMPLICIT_TIMEOUT_SEC;
            driver.CloseApp();
        }

        [SetUp]
        public void SetUp()
        {
            if (driver != null)
            {
                driver.LaunchApp();
            }
        }

        [TearDown]
        public void TearDowwn()
        {
            if (driver != null)
            {
                driver.CloseApp();
            }
        }

        [Test]
        public void StartActivityInThisAppTestCase()
        {
            driver.StartActivity("io.appium.android.apis", ".ApiDemos");

            Assert.AreEqual(driver.CurrentActivity, ".ApiDemos");

            driver.StartActivity("io.appium.android.apis", ".accessibility.AccessibilityNodeProviderActivity");

            Assert.AreEqual(driver.CurrentActivity, ".accessibility.AccessibilityNodeProviderActivity");
        }

**Comment by mykola-mokhnach** [comment]
Try to reboot the device under test or use another one for testing. It looks like UiAutomator service on the device is stuck: https://github.com/appium/appium/issues/1517

**Comment by ArmyMedalMei** [comment]
Thank you very much for your answer. I'll test it on another device

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
