### ISSUE TITLE
Webauthn command routes not found by Appium's WebDriver

### ISSUE THREAD

**Issue by TransmitTomerDavid** [appium/appium#14719]
## Description

Executing a custom HTTP command from Appium throws 404 for a given route, but works on ChromeDriver

## Environment

* Kotlin 14 on Java 11
* Java client build 7.3.0
* Appium server 7.3.0
* Desktop OS/version macOS Catalina v10.15.6
* Node.js 12.18.3
* Mobile platform/version under test: Pixel XL, Android 10.0
* Real device or emulator/simulator: Emulator, Android Studio AVD

## Details

Since Appium doesn't support  the latest (alpha-5) version of Selenium, I needed to mimic a command that was released in this version. It's basically a wrapper around WebAuthn's [Add Virtual Authenticator](https://www.w3.org/TR/webauthn-2/#sctn-automation-add-virtual-authenticator) command. Executing the command from a ChromeDriver worked fine, but when executed from an AndroidDriver it threw an error. I traced it down to the http request and the response code was 404 for the `/session/:sessionId/webauthn/authenticator` resource. If the route exist in ChromeDriver's selenium server, shouldn't it exist in Appium's server?

## Code To Reproduce Issue

Methods to add and execute new commands:

```
fun RemoteWebDriver.defineCustomCommand(name: String, info: CommandInfo) {
    try {
        val defineCommand: Method = HttpCommandExecutor::class.java.getDeclaredMethod("defineCommand", String::class.java, CommandInfo::class.java)
        defineCommand.setAccessible(true)
        defineCommand.invoke(this.commandExecutor, name, info)
    } catch (e: InvocationTargetException) {
        throw RuntimeException(e)
    } catch (e: IllegalAccessException) {
        throw RuntimeException(e)
    } catch (e: NoSuchMethodException) {
        throw RuntimeException(e)
    }
}

fun RemoteWebDriver.executeCustomCommand(commandName: String?, args: Any?): Any? {
    try {
        val execute = RemoteWebDriver::class.java.declaredMethods.find { it.name == "execute" && it.parameterCount == 2 }
        execute?.isAccessible = true
        val res: Response = execute?.invoke(this, commandName, args) as Response
        return res.value
    } catch (e: NoSuchMethodException) {
        throw RuntimeException(e)
    } catch (e: InvocationTargetException) {
        throw RuntimeException(e)
    } catch (e: IllegalAccessException) {
        throw RuntimeException(e)
    }
}
```
This line adds the command:
`driver.defineCustomCommand("addVirtualAuthen", CommandInfo("/session/:sessionId/webauthn/authenticator", HttpMethod.POST))`

The execution:

```
fun RemoteWebDriver.addTemporaryVirtualAuthenticator(): Any? {
    val options: VirtualAuthenticatorOptions = VirtualAuthenticatorOptions()
            .setProtocol(VirtualAuthenticatorOptions.Protocol.CTAP2)
            .setTransport(VirtualAuthenticatorOptions.Transport.INTERNAL)
            .setHasResidentKey(true)
            .setHasUserVerification(true)
            .setIsUserVerified(true)
    return this.executeCustomCommand("addVirtualAuthen", options.toMap())
}
```
Actual request URL:
`http://127.0.0.1:4723/wd/hub/session/3e305b3d-0d43-4caf-9f08-ffa274f2ffd6/webauthn/authenticator`

## Exception Stacktraces

[Stack trace ](https://gist.github.com/TransmitTomerDavid/31132cd2ea3ce3c4514e24494ad8f504)

## Link To Appium Logs

[Appium Logs](https://gist.github.com/TransmitTomerDavid/56b986fd496a1677caf4666e9376c30b)

**Comment by mykola-mokhnach** [comment]
The routes have been added to appium@beta
