### ISSUE TITLE
Unable to trigger appium automation with actual device. But the automation working with emulators. 

### ISSUE THREAD

**Issue by junfu1988** [appium/appium#14715]
## The problem
I was unable to trigger automation on actual device but it works fine with emulators. 

On desiredCapabilities already setup appWaitActivity and appWaitPackage. 

	    desiredCapabilities.setCapability("appWaitActivity", "com.aia.myaia.test.MainActivity");
            desiredCapabilities.setCapability("appWaitPackage", "com.aia.myaia.test");

Some how appium log just keep searching for the package and activity for multiple times until it throw error. 

[ADB] Getting focused package and activity
[ADB] Running 'C:\Users\jun_f\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s DKTUT20526008853 shell dumpsys window windows'

## Environment

* Appium version (or git revision) that exhibits the issue:1.8.2
* Desktop OS/version used to run Appium: Window 10 x64

* Mobile platform/version under test: (Huawei Nova 7i with Android 10) - Not working
* Real device or emulator/simulator: Emulator using Pixel Android 9 - Working Fine

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
https://gist.github.com/junfu1988/14f07051eaa9536cf99126b26d472310

**Comment by mykola-mokhnach** [comment]
> [debug] [35m[W3C][39m Encountered internal error running command: Error: Cannot start the 'com.aia.myaia.test' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Could not get focusPackageAndActivity. Original error: Could not parse activity from dumpsys

Have you checked the troubleshooting document?

**Comment by junfu1988** [comment]
Yup. but the same scripts works fine for emulator from genymotion and android studio AVD :(

**Comment by mykola-mokhnach** [comment]
I assume it is the problem with that particular device. Its firmware might have major differences from the "stock" Android one, so Appium is unable to parse the output. In such case consider using a compatible device for automation or create your own fork, which is compatible to Huawei customized stuff.

**Comment by junfu1988** [comment]
but just what i've observed so far, tested on 3 actual phones (redmi - android 10, huawei - android 10, oppo - android 9) only oppo is able to perform automation.

**Comment by KazuCocoa** [comment]
How about the latest Appium?
Your server is `1.9.1` in the attached log. The version cannot work with newer Android versions, I think
(At least, some feature should not work well)

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
