### ISSUE TITLE
Ruby - send_keys not working for flutter app text fields

### ISSUE THREAD

**Issue by Manojv08** [appium/appium#14713]
**## The problem**

Basically, this issue is occurring for all sorts of flutter app.

I'm trying to automate a flutter app and in the login screen - I'm trying to enter the username/email in the given text field. but facing the below shown error from appium logs as well. So I thought of giving a try from appium inspector and got the same error. It's not that I'm interacting with wrong element - but still error says that.

![image](https://user-images.githubusercontent.com/42680421/92325555-7433b700-f069-11ea-86bc-aba7458ece61.png)

**## Environment**

* Appium version (or git revision) that exhibits the issue: 1.17.1
* Desktop OS/version used to run Appium: Mac OS
* Mobile platform/version under test: Android 9.0
* Real device or emulator/simulator: Real device
* App built language : DART
* App type: Native (Flutter app)

**## Link to Appium logs**

https://gist.github.com/Manojv08/e9e05c34a34d9829dc9e66ef92ffee59

**## Code To Reproduce Issue [ Good To Have ]**

Sample app - https://play.google.com/store/apps/details?id=io.flutter.demo.gallery

Under Materials --> Text fields --> try to write something on the text field using send_keys --> you'll get to see the error as shown in the image below.
![image](https://user-images.githubusercontent.com/42680421/92325779-c7f2d000-f06a-11ea-8018-693cdc5e72aa.png)

**Code which I have tried below for automating my orgs in-house app**

desired_caps = {
      caps: {
        platformName: 'Android',
        deviceName: 'Redmi Note 7 Pro',
        automationName: 'UiAutomator2',
        noReset: true,
        appPackage: 'com.vivriti.android.credavenue.qa',
        appActivity: 'com.vivriti.credavenue.MainActivity',
        udid: @my_device_udid
      },
      appium_lib: {
        wait_timeout: 30,
      }
    }
appium_driver = Appium::Driver.new(desired_caps, true)
appium_driver.start_driver server_url: "http://0.0.0.0:4723/wd/hub"

ele = @driver.find_element(:xpath, "//android.widget.ImageView[@text='EMAIL']")
ele.click
ele.send_keys('jack')

**Comment by mykola-mokhnach** [comment]
I don't see any issues in the server log. One is trying to send a text into android.widget.ImageView component and the accessibility fails to do so

**Comment by mykola-mokhnach** [comment]
Also for flutter-based apps a separate driver could be used: https://github.com/truongsinh/appium-flutter-driver

**Comment by Manojv00087** [comment]
Yeah I tried that "appium_flutter_finder" gem (appium-flutter-driver library for ruby) as well - But I have got some issues on starting the driver itself - that's why I have reverted back to appium and trying to sort out issues.
![image](https://user-images.githubusercontent.com/46107289/92331422-1799c180-f094-11ea-8b3f-6390110f627b.png)

Also, if you see the second snapshot - on a sample flutter gallery app - I'm trying to send a text into android.widget.EditText component only - but still it fails to do so.

**Comment by mykola-mokhnach** [comment]
The exception above looks like a bug in that driver. Please report it to that project.

Regarding the text input - the error is thrown by UiAutomator framework itself. There is nothing we could do there.

As a workaround I would try to send text using [Actions API](https://appiumpro.com/editions/46-sending-arbitrary-keystrokes-with-the-actions-api) or using the `mobile: type` helper.

**Comment by Manojv00087** [comment]
Yeah I have reported that exception in that project as well initially - https://github.com/truongsinh/appium-flutter-driver/issues/99

Regarding the text input - I have tried Actions api as you've suggested - it worked greatly for me. Thanks @mykola-mokhnach for the info...

Sample snippet for reference if someone's looking for it in the future --> <code>@driver.action.send_keys('your_text_here').perform</code>

Above code should work for ruby.
