### ISSUE TITLE
How to run the application with some configuration file on windows platform

### ISSUE THREAD

**Issue by sukekes** [appium/appium#14722]
## The problem

I don't know how to run my applicaion by configuration file  Or Switch Windows

## Environment

* Desktop OS/version used to run Appium:

## Details

I know the appium surpport the windows application through winappdriver. but my application run way is diffrent other app, it has two ways to run the application:
1、by commandline:
`"C:\Program Files\Bentley\OpenBuildings CONNECT Edition\OpenBuildingsDesigner\OpenBuildingsDesigner.exe" -wc"C:\Program Files\Lee\ReStation\\Launch_RSTN.cfg"`
2、by pre-application:
First, I need to run the application Restation.exe, then The Restaion.exe close window and open the OpenBuildingsDesigner.exe window

Now, I don't know how to run the application by the way 1. And by the way 2 I don't know how switch to the OpenBuildingsDesigner.exe Opened Window. Or Can I run the application by Destop shortcut?

## Link to Appium logs

`[info] [35m[Appium][39m Welcome to Appium v1.18.0
[info] [35m[Appium][39m Non-default server args:
[info] [35m[Appium][39m   relaxedSecurityEnabled: true
[info] [35m[Appium][39m   allowInsecure: {
[info] [35m[Appium][39m   }
[info] [35m[Appium][39m   denyInsecure: {
[info] [35m[Appium][39m   }
[info] [35m[Appium][39m Appium REST http interface listener started on 0.0.0.0:4723[info] [35m[WinAppDriver][39m [STDOUT] 
[info] [35m[WinAppDriver][39m [STDOUT] 
[info] [35m[WinAppDriver][39m [STDOUT] ==========================================
[info] [35m[WinAppDriver][39m [STDOUT] POST /wd/hub/session HTTP/1.1
[info] [35m[WinAppDriver][39m [STDOUT] Accept: application/json
[info] [35m[WinAppDriver][39m [STDOUT] Accept-Encoding: identity
[info] [35m[WinAppDriver][39m [STDOUT] Connection: keep-alive
[info] [35m[WinAppDriver][39m [STDOUT] Content-Length: 770
[info] [35m[WinAppDriver][39m [STDOUT] Content-Type: application/json;charset=UTF-8
[info] [35m[WinAppDriver][39m [STDOUT] Host: 127.0.0.1:4724
[info] [35m[WinAppDriver][39m [STDOUT] User-Agent: appium/python 1.0.2 (selenium/3.141.0 (python windows))
[info] [35m[WinAppDriver][39m [STDOUT] X-Idempotency-Key: 89ff6371-1174-4911-b2c1-f2e6af0b95da
[info] [35m[WinAppDriver][39m [STDOUT] 
[info] [35m[WinAppDriver][39m [STDOUT] [info] [35m[WinAppDriver][39m [STDOUT] HTTP/1.1 200 OK
[info] [35m[WinAppDriver][39m [STDOUT] Content-Length: 268
[info] [35m[WinAppDriver][39m [STDOUT] Content-Type: application/json
[info] [35m[WinAppDriver][39m [STDOUT] 
[info] [35m[WinAppDriver][39m [STDOUT] {"sessionId":"A875DD49-7E38-472D-B384-18CF71EE9DF2","status":0,"value":{"app":"C:\\Program Files\\ECIDI\\ReStation\\ReStationStart.exe","appArguments":"1.0创建配筋体、修改配筋体.dgn","appWorkingDir":"C:\\Users\\ecidi\\Desktop\\\\","platformName":"Windows"}}
[info] [35m[WinAppDriver][39m [STDOUT] 
[info] [35m[WinAppDriver][39m [STDOUT] 
[info] [35m[WinAppDriver][39m [STDOUT] ==========================================
[info] [35m[WinAppDriver][39m [STDOUT] POST /wd/hub/session/A875DD49-7E38-472D-B384-18CF71EE9DF2/timeouts/implicit_wait HTTP/1.1
[info] [35m[WinAppDriver][39m [STDOUT] Accept: application/json
[info] [35m[WinAppDriver][39m [STDOUT] Accept-Encoding: identity
[info] [35m[WinAppDriver][39m [STDOUT] Connection: keep-alive
[info] [35m[WinAppDriver][39m [STDOUT] Content-Length: 68
[info] [35m[WinAppDriver][39m [STDOUT] Content-Type: application/json;charset=UTF-8
[info] [35m[WinAppDriver][39m [STDOUT] Host: 127.0.0.1:4724
[info] [35m[WinAppDriver][39m [STDOUT] User-Agent: appium/python 1.0.2 (selenium/3.141.0 (python windows))
[info] [35m[WinAppDriver][39m [STDOUT] 
[info] [35m[WinAppDriver][39m [STDOUT] {"ms": 30000.0, "sessionId": "A875DD49-7E38-472D-B384-18CF71EE9DF2"}
[info] [35m[WinAppDriver][39m [STDOUT] HTTP/1.1 200 OK
[info] [35m[WinAppDriver][39m [STDOUT] Content-Length: 63
[info] [35m[WinAppDriver][39m [STDOUT] Content-Type: application/json
[info] [35m[WinAppDriver][39m [STDOUT] 
[info] [35m[WinAppDriver][39m [STDOUT] {"sessionId":"A875DD49-7E38-472D-B384-18CF71EE9DF2","status":0}[info] [35m[WinAppDriver][39m [STDOUT] 
[info] [35m[WinAppDriver][39m [STDOUT] 
[info] [35m[WinAppDriver][39m [STDOUT] ==========================================
[info] [35m[WinAppDriver][39m [STDOUT] POST /wd/hub/session/A875DD49-7E38-472D-B384-18CF71EE9DF2/window/current/maximize HTTP/1.1
[info] [35m[WinAppDriver][39m [STDOUT] Accept: application/json
[info] [35m[WinAppDriver][39m [STDOUT] Accept-Encoding: identity
[info] [35m[WinAppDriver][39m [STDOUT] Connection: keep-alive
[info] [35m[WinAppDriver][39m [STDOUT] Content-Length: 80
[info] [35m[WinAppDriver][39m [STDOUT] Content-Type: application/json;charset=UTF-8
[info] [35m[WinAppDriver][39m [STDOUT] Host: 127.0.0.1:4724
[info] [35m[WinAppDriver][39m [STDOUT] User-Agent: appium/python 1.0.2 (selenium/3.141.0 (python windows))
[info] [35m[WinAppDriver][39m [STDOUT] 
[info] [35m[WinAppDriver][39m [STDOUT] {"windowHandle": "current", "sessionId": "A875DD49-7E38-472D-B384-18CF71EE9DF2"}
[info] [35m[WinAppDriver][39m [STDOUT] HTTP/1.1 400 Bad Request
[info] [35m[WinAppDriver][39m [STDOUT] Content-Length: 102
[info] [35m[WinAppDriver][39m [STDOUT] Content-Type: application/json
[info] [35m[WinAppDriver][39m [STDOUT] 
[info] [35m[WinAppDriver][39m [STDOUT] {"status":23,"value":{"error":"no such window","message":"Currently selected window has been closed"}}`

## Code To Reproduce Issue [ Good To Have ]
`C:\Software\Python37\python.exe E:/pws/DesktopAPPAutoTest/demo.py
Traceback (most recent call last):
  File "E:/pws/DesktopAPPAutoTest/demo.py", line 42, in <module>
    driver.maximize_window()
  File "C:\Software\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 737, in maximize_window
    self.execute(command, params)
  File "C:\Software\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Software\Python37\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "C:\Software\Python37\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "C:\Software\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: Currently selected window has been closed

Process finished with exit code 1
`

**Comment by mykola-mokhnach** [comment]
Please use Appium Forum to ask questions. Also, the Windows driver itself is maintained by Microsoft. We don't know details of its implementation.
