### ISSUE TITLE
Unable to switch to webview in Simulator where as it working fine in real device.

### ISSUE THREAD

**Issue by prasanna53** [appium/appium#14723]
When iam inspecting WEBView tags are not displaying in the Simulator where as Webview is displaying in the real devices.

* Appium version (or git revision) that exhibits the issue: 1.18
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:IOS
* Node.js version (unless using Appium.app|exe):14.7.0
* Npm or Yarn package manager: NPM 6.14.7
* Mobile platform/version under test: IOS 13 simulator
* Real device or emulator/simulator:Simulator
* Appium CLI or Appium.app|exe: checked both

**Comment by mykola-mokhnach** [comment]
Please fill out the issue reporting template properly

**Comment by prasanna53** [comment]
Updated

**Comment by mykola-mokhnach** [comment]
Sorry, the info is still not full. The server log is needed. Also, did you try to connect to the web view using Safari remote debugger? Is it visible there?

**Comment by prasanna53** [comment]
Webview is displaying in the code iam able to switch and i did print page source to check the webview. When iam trying to click on the element it showing as XCUIElementTypeWebview class not found exception.

**Comment by prasanna53** [comment]
![image](https://user-images.githubusercontent.com/69634380/92881744-e242fa00-f42c-11ea-944e-710773120dc0.png)
Looking like this when i am trying to inspect. Reali device it showing perfectly like Webview and all

**Comment by mykola-mokhnach** [comment]
> Webview is displaying in the code iam able to switch and i did print page source to check the webview. When iam trying to click on the element it showing as XCUIElementTypeWebview class not found exception.

Could you please check Safari remote debugger according to what was mentioned above?

also, the server log is still missing

**Comment by mykola-mokhnach** [comment]
Closed because of no response
