### ISSUE TITLE
Not able to Espresso automation with Appuim

### ISSUE THREAD

**Issue by jaspreetchagger** [appium/appium#14720]
I am not able to Espresso automation with Appuim:

## Environment
Appuim Desktop: 1.18.0
Desktop: Windows 10
Node.js: 12.8.1
Npm: 6.13.4
Electron: 7.2.4
Java JDK:1.8.0_181
Mobile platform: Android (Device API level: 25)
Real Device
issue coming with Appuim Desktop/Appuim cli both

I am using Appuim with automation "Espresso" with the following devices capabilities:

{
"udid": "xxxxx", "deviceName": "xxxx", "platformName": "Android", "platformVersion": "7", "noReset": true, "fullReset": false, "automationName": "Espresso", "app": "D:\Android.SauceLabs.Mobile.Sample.app.2.3.0.apk" }

when I check Appuim server logs , it has built Espresso server successfully and has installed app on my device. But then it shows following error:

[MJSONWP] Error: The process did not start within 30000ms (cmd: **'C:\Users\xxxxxx\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s xxxxxxx shell am instrument -w -e debug false 
io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner')

[MJSONWP] at Timeout._onTimeout (C:\Users\xxxxxx\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\teen_process\lib\subprocess.js:197:18)

[MJSONWP] at listOnTimeout (internal/timers.js:531:17)

[MJSONWP] at processTimers (internal/timers.js:475:7)**

Please help me to resolve this issue.

**Comment by mykola-mokhnach** [comment]
Please attach the full server log and the logcat output. Is the package under test already present on the device while noReset is set to true?

**Comment by jaspreetchagger** [comment]
Thanks for swift reply.

Package under test is not on device. I uninstall it before running any test.

Please find logs in attachment
[AppuimServerLog_Espresso.txt](https://github.com/appium/appium/files/5193169/AppuimServerLog_Espresso.txt)

**Comment by mykola-mokhnach** [comment]
> Package under test is not on device. I uninstall it before running any test.

Then the error is expected.

**Comment by jaspreetchagger** [comment]
I am installing package via  Appuim. 
is it required that package should already be there on device before Appuim session is created as Appuim installs package as well when we  add"app" capability.

Also I have turned off animations on the device  in order to use Espresso
as it is written in Espresso documentation
link: https://developer.android.com/training/testing/espresso/setup

**"Set up your test environment
To avoid flakiness, we highly recommend that you turn off system animations on the virtual or physical devices used for testing. On your device, under Settings > Developer options, disable the following 3 settings:

Window animation scale
Transition animation scale
Animator duration scale**"

**Comment by mykola-mokhnach** [comment]
Please attach the logcat output. The actual exception should be visible there

**Comment by jaspreetchagger** [comment]
[Logcatlog.txt](https://github.com/appium/appium/files/5194428/Logcatlog.txt)

This is what i see in log though
09-09 15:25:13.906  3150  3150 W System.err: android.content.pm.PackageManager$NameNotFoundException: io.appium.espressoserver.test
09-09 15:25:13.906  3150  3150 W System.err:    at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:345)
09-09 15:25:13.906  3150  3150 W System.err:    at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:327)
09-09 15:25:13.906  3150  3150 W System.err:    at com.abxxxccxx.security.autorun.Utils.PackageUtils.isSystemApplication(PackageUtils.java:64)
09-09 15:25:13.906  3150  3150 W System.err:    at com.abxxxccxx.security.autorun.Utils.PackageUtils.isSystemApplication(PackageUtils.java:42)
09-09 15:25:13.907  3150  3150 W System.err:    at com.abxxxccxx.security.autorun.AutoRunBroadcastReceiver.onReceive(AutoRunBroadcastReceiver.java:26)
09-09 15:25:13.907  3150  3150 W System.err:    at android.app.ActivityThread.handleReceiver(ActivityThread.java:3171)
09-09 15:25:13.907  3150  3150 W System.err:    at android.app.ActivityThread.-wrap18(ActivityThread.java)
09-09 15:25:13.907  3150  3150 W System.err:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1636)
09-09 15:25:13.907  3150  3150 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:102)
09-09 15:25:13.907  3150  3150 W System.err:    at android.os.Looper.loop(Looper.java:154)
09-09 15:25:13.907  3150  3150 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6334)
09-09 15:25:13.907  3150  3150 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
09-09 15:25:13.907  3150  3150 W System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
09-09 15:25:13.907  3150  3150 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
09-09 15:25:13.905 16209 13330 I Finsky  : [1125] mhf.run(-1): Frosting DB delete succeeded: false

**Comment by mykola-mokhnach** [comment]
What is the output of `adb shell am instrument -w -e debug false io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner` command being triggered from the command line?

**Comment by jaspreetchagger** [comment]
This command was not sent from command line but triggered by Appuim only

I am getting following output:

Encountered internal error running command: A new session could not be created. Details: The process did not start within 30000ms (cmd: 'C:\\Users\\abxxxccxx\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s abxxxccxx shell am instrument -w -e debug false io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner'). 

Check https://github.com/appium/appium-espresso-driver#troubleshooting regarding advanced session startup troubleshooting.
[W3C] Error: The process did not start within 30000ms (cmd: 'C:\\Users\\abxxxxxxx\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s abxxxccxx shell am instrument -w -e debug false io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner')

**Comment by jaspreetchagger** [comment]
Hi mykola,

when below command is launched from appuim:

C:\Users\abxxxccxx\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s abxxxccxx shell am instrument -w -e debug false io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner

In logcat I see following output:
ActivityManager: Force stopping io.appium.android.apis appid=10184 user=0: start instr

after this there is no  response and Instrumentation process fail to start

**Comment by mykola-mokhnach** [comment]
you mean the command itself just terminates silently or it keeps running? Does it print anything into the console window after 30 seconds or after 1 minute if it is running?

**Comment by jaspreetchagger** [comment]
Hi mykola,

I got following output on logcat after 30 secs:

  **1555  2093 I ActivityManager: Force stopping io.appium.android.apis appid=10184 user=0: from pid 13455
  1555  2093 D EmbryoManager: prepare io.appium.android.apis
 13455 13455 D AndroidRuntime: Shutting down VM
  1555  1699 I ActivityManager: Exiting empty application process 0:io.appium.android.apis/u0a184 (null)
  1555  1699 D ActivityManager: cleanUpApplicationRecord -- 0**

**Comment by mykola-mokhnach** [comment]
I meant not the logcat, but stdout/stderr of instruments command in the console. Anyway, I've published a new driver version to appium@beta where the startup detection is slightly changed. Install it and check if it changes anything for you

**Comment by jaspreetchagger** [comment]
Hi mykola,

I have getting following output from server now:

**Details: Timed out waiting for Espresso server to be online within 45000ms. 
The timeout value could be customized using 'espressoServerLaunchTimeout' capability. 
Check https://github.com/appium/appium-espresso-driver#troubleshooting regarding advanced session startup troubleshooting.**

On logcat
I am getting this which is same as previous error

**09-14 18:36:29.727  1555  2530 I ActivityManager: Force stopping io.appium.android.apis appid=10184 user=0: from pid 7135
09-14 18:36:29.729  7135  7135 D AndroidRuntime: Shutting down VM
09-14 18:36:29.730  1555  1699 I ActivityManager: Exiting empty application process 0:io.appium.android.apis/u0a184 (null)
09-14 18:36:29.731  1555  1699 D ActivityManager: cleanUpApplicationRecord -- 0**

**Comment by mykola-mokhnach** [comment]
It seems like the server fails to start. Unfortunately I don't have any good ideas on the reasons behind it

**Comment by jaspreetchagger** [comment]
Main issue is with Instrumentation on device which io.appium.espressoserver.test, it fails to respond when following command is issued via appuim

C:\Users\abxxxccxx\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s abxxxccxx shell am instrument -w -e debug false io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner

I tried with JAVA 7 as well as given in espresso server documentation
http://appium.io/docs/en/drivers/android-espresso/

**In addition to Appium's general requirements:**

**Java 7 installed and configured correctly for your platform**

But It didn't worked

What is the ideal configuiration for Espresso driver to work

I am using 
Appuim Desktop: Appium v1.12.1 with EspressoDriver (v1.10.0) (downloaded this appuim in reference to ticket #Not able to launch activity with espresso driver version 1.11.0 #439 )
JAVA: jdk1.7.0_80
Android SDK: API 26

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by sfkir** [comment]
@jaspreetchagger Hey, I have the same issue. Have u fixed it somehow?

**Comment by shrutipathak1234** [comment]
Hi @mykola-mokhnach I m using Espresso for automationName and not able to run the test 
Can you please help !
appium version : 1.22.3
