### ISSUE TITLE
Failing to start AndroidDriver method for mobile app automation.

### ISSUE THREAD

**Issue by shamsher786** [appium/appium#14735]
## The problem

I am not able to instantiate the Android Driver method and getting the error.

[RemoteTestNG] detected TestNG version 6.14.3
[TestNGContentHandler] [WARN] It is strongly recommended to add "<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >" at the top of your file, otherwise TestNG may fail or not work as expected.
2020-09-15 14:29:23 [main] INFO :: AppiumTest setup...
2020-09-15 14:29:23 [main] INFO :: Starting Appium service...
2020-09-15 14:29:26 [main] INFO :: Setting up Appium driver and connecting to Appium service...
SERVICE : io.appium.java_client.service.local.AppiumDriverLocalService@72bd06ca
CAB Capabilities {app: D:\Test\showcase_builds\Rel..., autoGrantPermissions: true, deviceName: Pixel, newCommandTimeout: 0, noReset: false, platformName: Android}
[35m[UiAutomator2][39m The instrumentation process cannot be initialized. Make sure the application under test does not crash and investigate the logcat output.
2020-09-15 14:29:46 [main] ERROR:: Encountered a problem starting Appium service! 
It is impossible to create a new session because 'createSession' which takes HttpClient, InputStream and long was not found or it is not accessible
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'MSI', ip: '192.168.99.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '10.0.2'
Driver info: driver.version: AndroidDriver
2020-09-15 14:29:46 [main] INFO :: AppiumTest tearDown...

===============================================
DefaultTestNG
Total tests run: 4, Failures: 0, Skips: 4
Configuration Failures: 2, Skips: 5
===============================================

## Environment

* Appium version (or git revision) that exhibits the issue:  1.16.0
* Last Appium version that did not exhibit the issue (if applicable):  1.14
* Desktop OS/version used to run Appium:  Window 10
* Node.js version (unless using Appium.app|exe):  v12.18.3
* Npm or Yarn package manager:  6.14.8
* Mobile platform/version under test: Android : 9
* Real device or emulator/simulator:  samusung s10
* Appium CLI or Appium.app|exe: 

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

[RemoteTestNG] detected TestNG version 6.14.3
[TestNGContentHandler] [WARN] It is strongly recommended to add "<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >" at the top of your file, otherwise TestNG may fail or not work as expected.
2020-09-15 14:29:23 [main] INFO :: AppiumTest setup...
2020-09-15 14:29:23 [main] INFO :: Starting Appium service...
2020-09-15 14:29:26 [main] INFO :: Setting up Appium driver and connecting to Appium service...
SERVICE : io.appium.java_client.service.local.AppiumDriverLocalService@72bd06ca
CAB Capabilities {app: D:\Test\showcase_builds\Rel..., autoGrantPermissions: true, deviceName: Pixel, newCommandTimeout: 0, noReset: false, platformName: Android}
[35m[UiAutomator2][39m The instrumentation process cannot be initialized. Make sure the application under test does not crash and investigate the logcat output.
2020-09-15 14:29:46 [main] ERROR:: Encountered a problem starting Appium service! 
It is impossible to create a new session because 'createSession' which takes HttpClient, InputStream and long was not found or it is not accessible
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'MSI', ip: '192.168.99.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '10.0.2'
Driver info: driver.version: AndroidDriver
2020-09-15 14:29:46 [main] INFO :: AppiumTest tearDown...

===============================================
DefaultTestNG
Total tests run: 4, Failures: 0, Skips: 4
Configuration Failures: 2, Skips: 5
===============================================

## Code To Reproduce Issue [ Good To Have ]

**congig.properties** 
appium.app=D:\\Test\\showcase_builds\\Release.apk
appium.server=true
appium.server.ip=0.0.0.0
appium.server.port=4723
unium.server.ip= 192.168.1.8
unium.server.port=13000
unium.fowardPorts=true
unium.isEmulated=false

**Appiumserver.java**

public void launch() {
        if (ENABLE_SERVER) {
            startServer();
        } else {
            if (!isServerRunning()) {
                throw new AppiumServerHasNotBeenStartedLocallyException(
                        "Appium disabled and not running locally, set appium.server=true or run Appium cli/GUI.");
            }
        }

        // create and return the interaction driver
        LOGGER.info("Setting up Appium driver and connecting to Appium service...");
        System.out.println("SERVICE : " + service);
        
        System.out.println("CAB " + capabilities);
        
        driver = new AndroidDriver<MobileElement>(service, capabilities);
        System.out.println("%%%%%%%%%%%Drive name is :" + driver);
    }

**Comment by mykola-mokhnach** [comment]
Please provide the server log from the most recent Appium server version. Also, please follow https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md to troubleshoot activity startup issues

**Comment by shamsher786** [comment]
@mykola-mokhnach 

[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"platformName":"Android"},"capabilities":{"alwaysMatch":{"platformName":"android"},"firstMatch":[{}]}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"platformName":"Android"},null,{"alwaysMatch":{"platformName":"android"},"firstMatch":[{}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1600167964742 (16:36:04 GMT+0530 (India Standard Time))
[Appium]
[Appium] ======================================================================
[Appium]   DEPRECATION WARNING:
[Appium]
[Appium]   The 'automationName' capability was not provided in the desired
[Appium]   capabilities for this Android session
[Appium]
[Appium]   Setting 'automationName=UiAutomator2' by default and using the
[Appium]   UiAutomator2 Driver
[Appium]
[Appium]   The next major version of Appium (2.x) will **require** the
[Appium]   'automationName' capability to be set for all sessions on all
[Appium]   platforms
[Appium]
[Appium]   In previous versions (Appium <= 1.13.x), the default was
[Appium]   'automationName=UiAutomator1'
[Appium]
[Appium]   If you wish to use that automation instead of UiAutomator2, please
[Appium]   add 'automationName=UiAutomator1' to your desired capabilities
[Appium]
[Appium]   For more information about drivers, please visit
[Appium]   http://appium.io/docs/en/about-appium/intro/ and explore the
[Appium]   'Drivers' menu
[Appium]
[Appium] ======================================================================
[Appium]
[Appium] Appium v1.16.0 creating new AndroidUiautomator2Driver (v1.40.0) session
[debug] [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {
[debug] [BaseDriver]   "alwaysMatch": {
[debug] [BaseDriver]     "platformName": "android"
[debug] [BaseDriver]   },
[debug] [BaseDriver]   "firstMatch": [
[debug] [BaseDriver]     {}
[debug] [BaseDriver]   ]
[debug] [BaseDriver] }
[BaseDriver] Session created with session id: 8755d896-9855-467b-b6bf-b8ba15227a98
[UiAutomator2] Neither 'app' nor 'appPackage' was set. Starting UiAutomator2 without the target application
[ADB] Found 4 'build-tools' folders under 'D:\sdk' (newest first):
[ADB]     D:/sdk/build-tools/28.0.3
[ADB]     D:/sdk/build-tools/28.0.2
[ADB]     D:/sdk/build-tools/26.0.2
[ADB]     D:/sdk/build-tools/25.0.3
[ADB] Using 'adb.exe' from 'D:\sdk\platform-tools\adb.exe'
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] Connected devices: [{"udid":"RZ8M22NC1KB","state":"device"}]
[AndroidDriver] Using device: RZ8M22NC1KB
[ADB] Using 'adb.exe' from 'D:\sdk\platform-tools\adb.exe'
[debug] [ADB] Setting device id to RZ8M22NC1KB
[debug] [ADB] Running 'D:\sdk\platform-tools\adb.exe -P 5037 -s RZ8M22NC1KB shell getprop ro.build.version.sdk'
[debug] [ADB] Current device property 'ro.build.version.sdk': 29
[debug] [ADB] Device API level: 29
[UiAutomator2] Relaxing hidden api policy
[debug] [ADB] Running 'D:\sdk\platform-tools\adb.exe -P 5037 -s RZ8M22NC1KB shell settings put global hidden_api_policy_pre_p_apps 1'
[debug] [ADB] Running 'D:\sdk\platform-tools\adb.exe -P 5037 -s RZ8M22NC1KB shell settings put global hidden_api_policy_p_apps 1'
[debug] [ADB] Running 'D:\sdk\platform-tools\adb.exe -P 5037 -s RZ8M22NC1KB shell settings put global hidden_api_policy 1'
[AndroidDriver] No app sent in, not parsing package/activity
[debug] [ADB] Running 'D:\sdk\platform-tools\adb.exe -P 5037 -s RZ8M22NC1KB wait-for-device'
[debug] [ADB] Running 'D:\sdk\platform-tools\adb.exe -P 5037 -s RZ8M22NC1KB shell echo ping'
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Getting install status for io.appium.settings
[debug] [ADB] Running 'D:\sdk\platform-tools\adb.exe -P 5037 -s RZ8M22NC1KB shell dumpsys package io.appium.settings'
[debug] [ADB] 'io.appium.settings' is installed
[debug] [ADB] Getting package info for 'io.appium.settings'
[debug] [ADB] Running 'D:\sdk\platform-tools\adb.exe -P 5037 -s RZ8M22NC1KB shell dumpsys package io.appium.settings'
[debug] [ADB] The version code of the installed 'io.appium.settings' is greater than the application version code (27 > 20)
[debug] [ADB] There is no need to downgrade 'io.appium.settings'
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running 'D:\sdk\platform-tools\adb.exe -P 5037 -s RZ8M22NC1KB shell 'pgrep --help; echo $?''
[debug] [ADB] Running 'D:\sdk\platform-tools\adb.exe -P 5037 -s RZ8M22NC1KB shell pgrep -f io\\.appium\\.settings'
[debug] [AndroidDriver] io.appium.settings is already running. There is no need to reset its permissions.
[debug] [ADB] Running 'D:\sdk\platform-tools\adb.exe -P 5037 -s RZ8M22NC1KB shell appops set io.appium.settings android\:mock_location allow'
[debug] [Logcat] Starting logcat capture
[debug] [UiAutomator2] Forwarding UiAutomator2 Server port 6790 to 8200
[debug] [ADB] Forwarding system: 8200 to device: 6790
[debug] [ADB] Running 'D:\sdk\platform-tools\adb.exe -P 5037 -s RZ8M22NC1KB forward tcp\:8200 tcp\:6790'
[debug] [ADB] Getting install status for io.appium.uiautomator2.server
[debug] [ADB] Running 'D:\sdk\platform-tools\adb.exe -P 5037 -s RZ8M22NC1KB shell dumpsys package io.appium.uiautomator2.server'
[debug] [ADB] 'io.appium.uiautomator2.server' is installed
[debug] [ADB] Getting package info for 'io.appium.uiautomator2.server'
[debug] [ADB] Running 'D:\sdk\platform-tools\adb.exe -P 5037 -s RZ8M22NC1KB shell dumpsys package io.appium.uiautomator2.server'
[debug] [ADB] The version name of the installed 'io.appium.uiautomator2.server' is greater or equal to the application version name ('4.5.2' >= '4.5.2')
[debug] [UiAutomator2] io.appium.uiautomator2.server installation state: sameVersionInstalled
[debug] [ADB] Checking app cert for C:\Users\sa_kh\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.5.2.apk
[ADB] Using 'apksigner.bat' from 'D:\sdk\build-tools\28.0.3\apksigner.bat'
[debug] [ADB] Starting 'D:\sdk\build-tools\28.0.3\apksigner.bat' with args '["verify","--print-certs","C:\\Users\\sa_kh\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v4.5.2.apk"]'
[debug] [ADB] apksigner stdout:
[debug] [ADB] ERROR: No suitable Java found. In order to properly use the Android Developer
[debug] [ADB] Tools, you need a suitable version of Java JDK installed on your system.
[debug] [ADB] We recommend that you install the JDK version of JavaSE, available here:
[debug] [ADB]   http://www.oracle.com/technetwork/java/javase/downloads
[debug] [ADB]
[debug] [ADB] If you already have Java installed, you can define the JAVA_HOME environment
[debug] [ADB] variable in Control Panel / System / Avanced System Settings to point to the
[debug] [ADB] JDK folder.
[debug] [ADB]
[debug] [ADB] You can find the complete Android SDK requirements here:
[debug] [ADB]   http://developer.android.com/sdk/requirements.html
[debug] [ADB]
[debug] [ADB]
[debug] [ADB] 'C:\Users\sa_kh\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.5.2.apk' is signed with non-default certificate
[ADB] Using 'zipalign.exe' from 'D:\sdk\build-tools\28.0.3\zipalign.exe'
[debug] [ADB] C:\Users\sa_kh\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.5.2.apk' is already zip-aligned. Doing nothing
[debug] [ADB] Signing 'C:\Users\sa_kh\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.5.2.apk' with default cert
[debug] [ADB] Starting 'D:\sdk\build-tools\28.0.3\apksigner.bat' with args '["sign","--key","C:\\Users\\sa_kh\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-adb\\keys\\testkey.pk8","--cert","C:\\Users\\sa_kh\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-adb\\keys\\testkey.x509.pem","C:\\Users\\sa_kh\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v4.5.2.apk"]'
[debug] [ADB] apksigner stdout:
[debug] [ADB] ERROR: No suitable Java found. In order to properly use the Android Developer
[debug] [ADB] Tools, you need a suitable version of Java JDK installed on your system.
[debug] [ADB] We recommend that you install the JDK version of JavaSE, available here:
[debug] [ADB]   http://www.oracle.com/technetwork/java/javase/downloads
[debug] [ADB]
[debug] [ADB] If you already have Java installed, you can define the JAVA_HOME environment
[debug] [ADB] variable in Control Panel / System / Avanced System Settings to point to the
[debug] [ADB] JDK folder.
[debug] [ADB]
[debug] [ADB] You can find the complete Android SDK requirements here:
[debug] [ADB]   http://developer.android.com/sdk/requirements.html
[debug] [ADB]
[debug] [ADB]
[debug] [ADB] Getting install status for io.appium.uiautomator2.server.test
[debug] [ADB] Running 'D:\sdk\platform-tools\adb.exe -P 5037 -s RZ8M22NC1KB shell dumpsys package io.appium.uiautomator2.server.test'
[debug] [ADB] 'io.appium.uiautomator2.server.test' is installed
[debug] [ADB] Checking app cert for C:\Users\sa_kh\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk
[debug] [ADB] Starting 'D:\sdk\build-tools\28.0.3\apksigner.bat' with args '["verify","--print-certs","C:\\Users\\sa_kh\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-debug-androidTest.apk"]'
[debug] [ADB] apksigner stdout:
[debug] [ADB] ERROR: No suitable Java found. In order to properly use the Android Developer
[debug] [ADB] Tools, you need a suitable version of Java JDK installed on your system.
[debug] [ADB] We recommend that you install the JDK version of JavaSE, available here:
[debug] [ADB]   http://www.oracle.com/technetwork/java/javase/downloads
[debug] [ADB]
[debug] [ADB] If you already have Java installed, you can define the JAVA_HOME environment
[debug] [ADB] variable in Control Panel / System / Avanced System Settings to point to the
[debug] [ADB] JDK folder.
[debug] [ADB]
[debug] [ADB] You can find the complete Android SDK requirements here:
[debug] [ADB]   http://developer.android.com/sdk/requirements.html
[debug] [ADB]
[debug] [ADB]
[debug] [ADB] 'C:\Users\sa_kh\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk' is signed with non-default certificate
[debug] [ADB] C:\Users\sa_kh\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk' is already zip-aligned. Doing nothing
[debug] [ADB] Signing 'C:\Users\sa_kh\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk' with default cert
[debug] [ADB] Starting 'D:\sdk\build-tools\28.0.3\apksigner.bat' with args '["sign","--key","C:\\Users\\sa_kh\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-adb\\keys\\testkey.pk8","--cert","C:\\Users\\sa_kh\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-adb\\keys\\testkey.x509.pem","C:\\Users\\sa_kh\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-debug-androidTest.apk"]'
[debug] [ADB] apksigner stdout:
[debug] [ADB] ERROR: No suitable Java found. In order to properly use the Android Developer
[debug] [ADB] Tools, you need a suitable version of Java JDK installed on your system.
[debug] [ADB] We recommend that you install the JDK version of JavaSE, available here:
[debug] [ADB]   http://www.oracle.com/technetwork/java/javase/downloads
[debug] [ADB]
[debug] [ADB] If you already have Java installed, you can define the JAVA_HOME environment
[debug] [ADB] variable in Control Panel / System / Avanced System Settings to point to the
[debug] [ADB] JDK folder.
[debug] [ADB]
[debug] [ADB] You can find the complete Android SDK requirements here:
[debug] [ADB]   http://developer.android.com/sdk/requirements.html
[debug] [ADB]
[debug] [ADB]
[UiAutomator2] Server packages are going to be (re)installed
[UiAutomator2] Full packages reinstall is going to be performed
[debug] [ADB] Uninstalling io.appium.uiautomator2.server
[debug] [ADB] Getting install status for io.appium.uiautomator2.server
[debug] [ADB] Running 'D:\sdk\platform-tools\adb.exe -P 5037 -s RZ8M22NC1KB shell dumpsys package io.appium.uiautomator2.server'
[debug] [ADB] 'io.appium.uiautomator2.server' is installed
[debug] [ADB] Running 'D:\sdk\platform-tools\adb.exe -P 5037 -s RZ8M22NC1KB shell am force-stop io.appium.uiautomator2.server'
[debug] [ADB] Running 'D:\sdk\platform-tools\adb.exe -P 5037 -s RZ8M22NC1KB uninstall io.appium.uiautomator2.server'
[debug] [ADB] 'adb uninstall io.appium.uiautomator2.server' command output: Success
[ADB] io.appium.uiautomator2.server was successfully uninstalled
[debug] [ADB] Running 'D:\sdk\platform-tools\adb.exe -P 5037 -s RZ8M22NC1KB shell 'ls -t -1 /data/local/tmp/appium_cache 2>&1 || echo _ERROR_''
[debug] [ADB] The count of applications in the cache: 4
[ADB] The application at 'C:\Users\sa_kh\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.5.2.apk' is already cached to '/data/local/tmp/appium_cache/c4d04c1433ecbf8b791b15c7eeb8d8cb0f1b1376.apk'
[debug] [ADB] Running 'D:\sdk\platform-tools\adb.exe -P 5037 -s RZ8M22NC1KB shell pm install -r /data/local/tmp/appium_cache/c4d04c1433ecbf8b791b15c7eeb8d8cb0f1b1376.apk'
[ADB] The installation of 'appium-uiautomator2-server-v4.5.2.apk' took 1.914s
[debug] [ADB] Install command stdout: Success
[debug] [ADB] Uninstalling io.appium.uiautomator2.server.test
[debug] [ADB] Getting install status for io.appium.uiautomator2.server.test
[debug] [ADB] Running 'D:\sdk\platform-tools\adb.exe -P 5037 -s RZ8M22NC1KB shell dumpsys package io.appium.uiautomator2.server.test'
[debug] [ADB] 'io.appium.uiautomator2.server.test' is installed
[debug] [ADB] Running 'D:\sdk\platform-tools\adb.exe -P 5037 -s RZ8M22NC1KB shell am force-stop io.appium.uiautomator2.server.test'
[debug] [ADB] Running 'D:\sdk\platform-tools\adb.exe -P 5037 -s RZ8M22NC1KB uninstall io.appium.uiautomator2.server.test'
[debug] [ADB] 'adb uninstall io.appium.uiautomator2.server.test' command output: Success
[ADB] io.appium.uiautomator2.server.test was successfully uninstalled
[debug] [ADB] Running 'D:\sdk\platform-tools\adb.exe -P 5037 -s RZ8M22NC1KB shell 'ls -t -1 /data/local/tmp/appium_cache 2>&1 || echo _ERROR_''
[debug] [ADB] The count of applications in the cache: 4
[ADB] The application at 'C:\Users\sa_kh\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk' is already cached to '/data/local/tmp/appium_cache/a1376d3266a5723afda7da2573599b54ad3b2cd1.apk'
[debug] [ADB] Running 'D:\sdk\platform-tools\adb.exe -P 5037 -s RZ8M22NC1KB shell pm install -r /data/local/tmp/appium_cache/a1376d3266a5723afda7da2573599b54ad3b2cd1.apk'
[ADB] The installation of 'appium-uiautomator2-server-debug-androidTest.apk' took 1.690s
[debug] [ADB] Install command stdout: Success
[debug] [UiAutomator2] Waiting up to 30000ms for services to be available
[debug] [ADB] Running 'D:\sdk\platform-tools\adb.exe -P 5037 -s RZ8M22NC1KB shell pm list instrumentation'
[debug] [UiAutomator2] Instrumentation target 'io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner' is available
[debug] [UiAutomator2] No app capability. Assuming it is already on the device
[debug] [UiAutomator2] Performing shallow cleanup of automation leftovers
[debug] [UiAutomator2] No obsolete sessions have been detected (Error: socket hang up)
[debug] [ADB] Running 'D:\sdk\platform-tools\adb.exe -P 5037 -s RZ8M22NC1KB shell am force-stop io.appium.uiautomator2.server.test'
[UiAutomator2] Starting UIAutomator2 server 4.5.2
[UiAutomator2] Using UIAutomator2 server from 'C:\Users\sa_kh\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.5.2.apk' and test from 'C:\Users\sa_kh\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk'
[UiAutomator2] Waiting up to 30000ms for UiAutomator2 to be online...
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","RZ8M22NC1KB","shell","am","instrument","-w","io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner"]
[debug] [Instrumentation] java.lang.SecurityException: Permission Denial: starting instrumentation ComponentInfo{io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner} from pid=12305, uid=12305 not allowed because package io.appium.uiautomator2.server.test does not have a signature matching the target io.appium.uiautomator2.server
[debug] [Instrumentation] at android.os.Parcel.createException(Parcel.java:2088)
[debug] [Instrumentation]       at android.os.Parcel.readException(Parcel.java:2056)
[debug] [Instrumentation]       at android.os.Parcel.readException(Parcel.java:2004)
[debug] [Instrumentation]       at android.app.IActivityManager$Stub$Proxy.startInstrumentation(IActivityManager.java:6144)
[debug] [Instrumentation]       at com.android.commands.am.Instrument.run(Instrument.java:512)
[debug] [Instrumentation]       at com.android.commands.am.Am.runInstrument(Am.java:196)
[debug] [Instrumentation]       at com.android.commands.am.Am.onRun(Am.java:80)
[debug] [Instrumentation]       at com.android.internal.os.BaseCommand.run(BaseCommand.java:56)
[debug] [Instrumentation]       at com.android.commands.am.Am.main(Am.java:50)
[debug] [Instrumentation]       at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
[debug] [Instrumentation]       at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:339)
[debug] [Instrumentation] Caused by: android.os.RemoteException: Remote stack trace:
[debug] [Instrumentation]       at com.android.server.am.ActivityManagerService.startInstrumentation(ActivityManagerService.java:17939)
[debug] [Instrumentation]       at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2681)
[debug] [Instrumentation]       at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3293)
[debug] [Instrumentation]       at android.os.Binder.execTransactInternal(Binder.java:1021)
[debug] [Instrumentation]       at android.os.Binder.execTransact(Binder.java:994)
[debug] [Instrumentation] FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x70a7c1b000)
[debug] [Instrumentation] The process has exited with code 1
[UiAutomator2] The instrumentation process has been unexpectedly terminated. Retrying UiAutomator2 startup (#1 of 1)
[debug] [UiAutomator2] Performing strict cleanup of automation leftovers
[debug] [UiAutomator2] No obsolete sessions have been detected (Error: socket hang up)
[debug] [ADB] Running 'D:\sdk\platform-tools\adb.exe -P 5037 -s RZ8M22NC1KB shell am force-stop io.appium.uiautomator2.server.test'
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting IDs of all 'uiautomator' processes
[debug] [ADB] Running 'D:\sdk\platform-tools\adb.exe -P 5037 -s RZ8M22NC1KB shell pgrep -f uiautomator'
[ADB] No 'uiautomator' process has been found
[UiAutomator2] Waiting up to 30000ms for UiAutomator2 to be online...
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","RZ8M22NC1KB","shell","am","instrument","-w","io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner"]
[debug] [Instrumentation] java.lang.SecurityException: Permission Denial: starting instrumentation ComponentInfo{io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner} from pid=12852, uid=12852 not allowed because package io.appium.uiautomator2.server.test does not have a signature matching the target io.appium.uiautomator2.server
[debug] [Instrumentation]       at android.os.Parcel.createException(Parcel.java:2088)
[debug] [Instrumentation]       at android.os.Parcel.readException(Parcel.java:2056)
[debug] [Instrumentation]       at android.os.Parcel.readException(Parcel.java:2004)
[debug] [Instrumentation]       at android.app.IActivityManager$Stub$Proxy.startInstrumentation(IActivityManager.java:6144)
[debug] [Instrumentation]       at com.android.commands.am.Instrument.run(Instrument.java:512)
[debug] [Instrumentation]       at com.android.commands.am.Am.runInstrument(Am.java:196)
[debug] [Instrumentation] INSTRUMENTATION_STATUS: Error=Permission Denial: starting instrumentation ComponentInfo{io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner} from pid=12852, uid=12852 not allowed because package io.appium.uiautomator2.server.test does not have a signature matching the target io.appium.uiautomator2.server
[debug] [Instrumentation] at com.android.commands.am.Am.onRun(Am.java:80)
[debug] [Instrumentation]       at com.android.internal.os.BaseCommand.run(BaseCommand.java:56)
[debug] [Instrumentation]       at com.android.commands.am.Am.main(Am.java:50)
[debug] [Instrumentation]       at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
[debug] [Instrumentation]       at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:339)
[debug] [Instrumentation] Caused by: android.os.RemoteException: Remote stack trace:
[debug] [Instrumentation]       at com.android.server.am.ActivityManagerService.startInstrumentation(ActivityManagerService.java:17939)
[debug] [Instrumentation]       at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2681)
[debug] [Instrumentation]       at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3293)
[debug] [Instrumentation]       at android.os.Binder.execTransactInternal(Binder.java:1021)
[debug] [Instrumentation]       at android.os.Binder.execTransact(Binder.java:994)
[debug] [Instrumentation]
[debug] [Instrumentation] FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x74342ab000)
[debug] [Instrumentation] The process has exited with code 1
[UiAutomator2] The instrumentation process cannot be initialized. Make sure the application under test does not crash and investigate the logcat output.
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[debug] [WD Proxy] Matched '/' to command name 'deleteSession'
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8200
[debug] [ADB] Running 'D:\sdk\platform-tools\adb.exe -P 5037 -s RZ8M22NC1KB forward --remove tcp\:8200'
[UiAutomator2] Restoring hidden api policy to the device default configuration
[debug] [ADB] Running 'D:\sdk\platform-tools\adb.exe -P 5037 -s RZ8M22NC1KB shell settings delete global hidden_api_policy_pre_p_apps'
[debug] [ADB] Running 'D:\sdk\platform-tools\adb.exe -P 5037 -s RZ8M22NC1KB shell settings delete global hidden_api_policy_p_apps'
[debug] [ADB] Running 'D:\sdk\platform-tools\adb.exe -P 5037 -s RZ8M22NC1KB shell settings delete global hidden_api_policy'
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1600167987252 (16:36:27 GMT+0530 (India Standard Time))
[debug] [W3C] Encountered internal error running command: Error: The instrumentation process cannot be initialized. Make sure the application under test does not crash and investigate the logcat output.
[debug] [W3C]     at Object.errorAndThrow (C:\Users\sa_kh\AppData\Roaming\npm\node_modules\appium\node_modules\appium-support\lib\logging.js:74:35)
[debug] [W3C]     at UiAutomator2Server.startSession (C:\Users\sa_kh\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\uiautomator2.js:231:13)
[debug] [W3C]     at AndroidUiautomator2Driver.startUiAutomator2Session (C:\Users\sa_kh\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:362:5)
[debug] [W3C]     at AndroidUiautomator2Driver.createSession (C:\Users\sa_kh\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:208:7)
[debug] [W3C]     at AppiumDriver.createSession (C:\Users\sa_kh\AppData\Roaming\npm\node_modules\appium\lib\appium.js:358:35)
[HTTP] <-- POST /wd/hub/session 500 22636 ms - 835

**Comment by shamsher786** [comment]
Actually my code got stop working as soon as reached to 
**driver = new AndroidDriver<MobileElement>(service, capabilities);**
line

**Comment by mykola-mokhnach** [comment]
1.16.0 is not the recent server version. Also, it is clearly visible in the log, that the build cannot be signed because of apksigner failure:

> [debug] [ADB] ERROR: No suitable Java found. In order to properly use the Android Developer
> [debug] [ADB] Tools, you need a suitable version of Java JDK installed on your system.
> [debug] [ADB] We recommend that you install the JDK version of JavaSE, available here:
> [debug] [ADB] http://www.oracle.com/technetwork/java/javase/downloads

**Comment by shamsher786** [comment]
@mykola-mokhnach 
I have installed java in my system.

C:\Users\sa_kh>java -version
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)

**Comment by shamsher786** [comment]
@mykola-mokhnach sorry I did not get this.
could you please tell me how should I proceed further to resolve my issue ?

**Comment by mykola-mokhnach** [comment]
It is necessary:
- Update server to the recent version
- Fix your environment according to the document above

Also, it makes more sense to move the topic to Appium forum, since it is not an issue

**Comment by shamsher786** [comment]
@mykola-mokhnach 
sure I'll try and let you know.
I'll move this topic to Appium forum as well.
Thank you !

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
