### ISSUE TITLE
Unable to launch simulator through appium code - rror: Could not find path to Xcode by symlinks located in /var/db/xcode_select_link, or /usr/share/xcode-select/xcode_dir_link

### ISSUE THREAD

**Issue by uppalvishal** [appium/appium#14737]
## Environment
Xcode 11.3.1
Appium Desktop 1.15.0
Mac 10.14.6

* Appium version (or git revision) that exhibits the issue: 1.15.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac 10.14.6
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: 
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/uppalvishal/e0616e5f546fdfcd7572b32c7ac3d077#file-gistfile1-txt

## Code To Reproduce Issue [ Good To Have ]

package appiumexample;

import java.net.MalformedURLException;
import java.net.URL;

import org.openqa.selenium.remote.DesiredCapabilities;

import io.appium.java_client.ios.IOSDriver;
import io.appium.java_client.ios.IOSElement;
import io.appium.java_client.remote.AutomationName;
import io.appium.java_client.remote.MobileCapabilityType;

public class base {

	public static void main(String[] args) throws MalformedURLException, InterruptedException {
		// TODO Auto-generated method stub
		
		DesiredCapabilities d = new DesiredCapabilities();
		d.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 11 Pro Max");
		d.setCapability(MobileCapabilityType.UDID, "DE438AB3-7591-481B-8B09-E337B8455B6B");
		d.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
		d.setCapability(MobileCapabilityType.PLATFORM_VERSION, "13.3");
		d.setCapability(MobileCapabilityType.AUTOMATION_NAME , AutomationName.IOS_XCUI_TEST);
		d.setCapability(MobileCapabilityType.APP, "//Users//planittest//Desktop//UICatalog.app");
		//d.setCapability(MobileCapabilityType.APP, "/Users/planittest/Desktop/UICatalog.app");
		IOSDriver<IOSElement> driver= new IOSDriver<>(new URL("http://127.0.0.1:4723/wd/hub"),d);

	}

}

AppiumDoctor check:
info AppiumDoctor Appium Doctor v.1.15.3
info AppiumDoctor ### Diagnostic for necessary dependencies starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: /usr/local/bin/node
info AppiumDoctor  ✔ Node version is 10.11.0
info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ Xcode Command Line Tools are installed in: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ DevToolsSecurity is enabled.
info AppiumDoctor  ✔ The Authorization DB is set up properly.
info AppiumDoctor  ✔ Carthage was found at: /usr/local/bin/carthage. Installed version is: 0.31.0
info AppiumDoctor  ✔ HOME is set to: /Users/planittest
info AppiumDoctor ### Diagnostic for necessary dependencies completed, no fix needed. ###
info AppiumDoctor 
info AppiumDoctor ### Diagnostic for optional dependencies starting ###
WARN AppiumDoctor  ✖ opencv4nodejs cannot be found.
WARN AppiumDoctor  ✖ ffmpeg cannot be found
WARN AppiumDoctor  ✖ mjpeg-consumer cannot be found.
WARN AppiumDoctor  ✖ set-simulator-location is not installed
WARN AppiumDoctor  ✖ idb and idb_companion are not installed
WARN AppiumDoctor  ✖ applesimutils cannot be found
info AppiumDoctor  ✔ ios-deploy is installed at: /usr/local/bin/ios-deploy. Installed version is: 1.11.1
info AppiumDoctor ### Diagnostic for optional dependencies completed, 6 fixes possible. ###
info AppiumDoctor 
info AppiumDoctor ### Optional Manual Fixes ###
info AppiumDoctor The configuration can install optionally. Please do the following manually:
WARN AppiumDoctor  ➜ Why opencv4nodejs is needed and how to install it: https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/image-comparison.md
WARN AppiumDoctor  ➜ ffmpeg is needed to record screen features. Please read https://www.ffmpeg.org/ to install it
WARN AppiumDoctor  ➜ mjpeg-consumer module is required to use MJPEG-over-HTTP features. Please install it with 'npm i -g mjpeg-consumer'.
WARN AppiumDoctor  ➜ set-simulator-location is needed to set location for Simulator. Please read https://github.com/lyft/set-simulator-location to install it
WARN AppiumDoctor  ➜ Why idb is needed and how to install it: https://github.com/appium/appium-idb
WARN AppiumDoctor  ➜ Why applesimutils is needed and how to install it: http://appium.io/docs/en/drivers/ios-xcuitest/
info AppiumDoctor 
info AppiumDoctor ###
info AppiumDoctor 
info AppiumDoctor Bye! Run appium-doctor again when all manual fixes have been applied!
info AppiumDoctor

**Comment by mykola-mokhnach** [comment]
Make sure that `xcode-select --print-path` returns a proper path to the installed Xcode app. If it does not then it is necessary to set one using `sudo xcode-select -s <correct_path>` command

**Comment by mykola-mokhnach** [comment]
Also, version 1.15 is out of date

**Comment by uppalvishal** [comment]
Thanks for your reply mykola. 
I checked xcode-select --print-path and it returns properly the path to xcode.

LP89:~ planittest$ xcode-select --print-path
/Applications/Xcode.app/Contents/Developer

Should I update appium desktop to 1.18 then ?

**Comment by mykola-mokhnach** [comment]
yes try to update

**Comment by uppalvishal** [comment]
updated to 1.18, now getting some different error
Appium logs 
https://gist.github.com/uppalvishal/e0616e5f546fdfcd7572b32c7ac3d077

Original error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'carthage bootstrap --platform iOS\,tvOS' exited with code 1

Note: App builds successfully on xcode.

**Comment by uppalvishal** [comment]
Updated carthage, now not getting error , appium server logs returns 200 , just that the simulator did not launch.  Also put the link to the gist file with the latest comments having the latest logs. 
Do I need to manually start simulator?

**Appium Logs**
{"udid":"DE438AB3-7591-481B-8B09-E337B8455B6B","platformName":"ios","app":"/Users/planittest/Desktop/UICatalog.app","automationName":"XCuiTest","deviceName":"iPhone 11 Pro Max","device":"iphone","browserName":"UICatalog","sdkVersion":"13.3","CFBundleIdentifier":"com.example.apple-samplecode.UICatalog","pixelRatio":3,"statBarHeight":44,"viewportRect":{"left":0,"top":132,"width":960,"height":1572}}
[HTTP] <-- GET /wd/hub/session/96781dd1-7b60-4c92-81a1-ad7f8655be12 200 

**Complete Appium Logs**
https://gist.github.com/uppalvishal/2682d5508f7e3be39ca353c714b108d2

**Below are the capabilities.**

public static void main(String[] args) throws MalformedURLException, InterruptedException {
	// TODO Auto-generated method stub
	
	DesiredCapabilities d = new DesiredCapabilities();
	d.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 11 Pro Max");
	d.setCapability(MobileCapabilityType.UDID, "DE438AB3-7591-481B-8B09-E337B8455B6B");
	d.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
	d.setCapability(MobileCapabilityType.PLATFORM_VERSION, "13.3");
	d.setCapability(MobileCapabilityType.AUTOMATION_NAME , AutomationName.IOS_XCUI_TEST);
	d.setCapability(MobileCapabilityType.APP, "/Users/planittest/Desktop/UICatalog.app");
	IOSDriver<IOSElement> driver= new IOSDriver<>(new URL("http://127.0.0.1:4723/wd/hub"),d);

}

**Comment by uppalvishal** [comment]
Issue is resolved, It was launching the simulator app in the bottom row . I right clicked on simulator app and device and selected my device. Device was somehow hidden. Reran the appium code and my app is launched on the simulator.

Thanks mykola and manifity for your assistance.
