### ISSUE TITLE
Error while starting the appium server 

### ISSUE THREAD

**Issue by yaseenmd** [appium/appium#14747]
## The problem

Starting the server using command "appium -p 5006 --webdriveragent-port 6006". Immediately we get this error response back. 

Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started
[debug] [GENERIC (7ddb92aa)]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:255:15)
[debug] [GENERIC (7ddb92aa)]     at /usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:447:15

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.0
* Desktop OS/version used to run Appium: Mac Catalina 10.15.6
* Node.js version (unless using Appium.app|exe): v12.5.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: ios
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

We are creating multiple instance of appium server with different appium port and webdriveragent port. And we are running test case against multiple real device . Ans assuming that each device will link to specifc server instance based wda port and appium port

## Link to Appium logs

https://gist.github.com/yaseenmd/d0a87d3ef4471fa8b37f2bff1ea2f8fd

## Code To Reproduce Issue [ Good To Have ]

Just start the appium server with this command "appium -p 5006 --webdriveragent-port 6006"

**Comment by mykola-mokhnach** [comment]
I don't observe any issues in the attached log. The client requests a session id, which is not known to the server and thus gets a proper response.

**Comment by yaseenmd** [comment]
appium driver was throwing an exception and unfortunately we did capture the error log. 

And then we start a appium and noticed the attached logs is printing continuously.

my question is : why client is requesting session id ? is there anything i need to do at the ios device side? 
i just started the server and noticed the session id request from the client?

**Comment by mykola-mokhnach** [comment]
> why client is requesting session id ? 

This is rather a question to you. Double check the architecture of your automation solution.

**Comment by yaseenmd** [comment]
The architecture is simple. we instantiate 5 appium server with different appium port and wda port. 
like this , appium -p 5001 --webdriveragent-port 6001
appium -p 5002 --webdriveragent-port 6002
appium -p 5003 --webdriveragent-port 6003
 

Once servers are started with this capabilities, for every test suite while creating a driver we pass , appium url and desired capabilities.(note: we are not passing any info related wda port).

i expect, driver.quit() should send the close session to client as well.  is my understanding correct?

**Comment by KazuCocoa** [comment]
Did you call _create a session_ request from each client to each appium server before calling _delete session_ request?

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
