### ISSUE TITLE
Not able to download appuim via node

### ISSUE THREAD

**Issue by jaspreetchagger** [appium/appium#14740]
I am not able to download appuim via npm

it is giving following error:
**C:\Users\xxxxxxx>npm install -g appuim
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/appuim - Not found
npm ERR! 404
npm ERR! 404  'appuim@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.**

**Comment by azanouski** [comment]
You have a typo in your command. Try: **npm install -g appium**
