### ISSUE TITLE
Feature Suggestion: get details of window handles on Android WebView

### ISSUE THREAD

**Issue by mwakizaka** [appium/appium#14745]
## The problem

Consider a situation where one WebView exists and DevTools shows 2 pages on Android device. In this case, `driver.windowHandles()` returns 2 window handles like `[CDwindow-964655BCD0426A2CC02067414AC2F1D4,CDwindow-9CD11761705EC921B76BF5BCF325F68E]`. Therefore, you need to select one of the window handles.
<img width="1093" alt="スクリーンショット 2020-09-19 10 21 05" src="https://user-images.githubusercontent.com/21286384/93657049-112f2080-fa6a-11ea-832a-0e80a4687479.png">

Sometimes the url and title might help, but it's difficult in this case because they have the same url and title.
Such case might happen when you back and forth in Android app. 

## The suggestion
Does Appium already have a trick to select the correct window handle for this case? If no, I would like to implement a feature to get all available information from CDP via appium. An appium user can use the info to select the correct window handle. 
The info will be something like the following. The info can be obtained by using [collectWebviewsDetails](https://github.com/appium/appium-android-driver/blob/6f1cd4bdd14e97731c0d09672ba7a1306013ad33/lib/webview-helpers.js#L197).
```
[
  {
    "proc": "@webview_devtools_remote_11209",
    "webview": "WEBVIEW_11209",
    "info": {
      (omitted)
    },
    "pages": [
      {
        "description": "{\"attached\":true,\"empty\":false,\"height\":1458,\"screenX\":0,\"screenY\":336,\"visible\":true,\"width\":1080}",
        "id": "964655BCD0426A2CC02067414AC2F1D4",
        (omitted)
      },
      {
        "description": "{\"attached\":false,\"empty\":false,\"height\":1458,\"screenX\":0,\"screenY\":0,\"visible\":true,\"width\":1080}",
        "id": "9CD11761705EC921B76BF5BCF325F68E",
        (omitted)
      }
    ]
  }
]
```
In this case, the correct window handle name will be `"CDwindow-" + pages[0].id` since its `description.attached` is true.
By checking pages[i].description.attached value, an appium user can avoid manipulating over a detached window handle. It will reduce confusion.

## Why not a PR?
- I'm not sure if the explained spec is acceptable for appium.
- I appreciate it if you have any suggestion or question.

## Miscellaneous
- This is similar to `mobile:getContexts` for iOS. So this feature should be named like `mobile:getWindowHandles`?

**Comment by mykola-mokhnach** [comment]
I would say it makes sense to implement an alternative to `mobile:getContexts` endpoint in Android

**Comment by mykola-mokhnach** [comment]
The feature has been published to appium@beta

**Comment by KazuCocoa** [comment]
@mwakizaka You want to add the getContexts command https://github.com/appium/appium/blob/master/commands-yml/commands/mobile-command.yml#L86 :)

**Comment by mwakizaka** [comment]
Ah, sure. I forgot it. Let me add the command there.
