### ISSUE TITLE
Appium 1.18.1 does not auto-accept location permission on iOS 14

### ISSUE THREAD

**Issue by frangipanes** [appium/appium#14741]
## The problem

On iOS 14.0, the autoAcceptAlerts capability does not automatically accept the permission request for location. The appium driver times out waiting for other elements to be visible in the app underneath the permission alert. This previously worked with the same appium version on iOS 13.5.

## Environment

* Appium version that exhibits the issue: 1.18.1
* Desktop OS/version used to run Appium: macOS Catalina Version 10.15.6 (19G2021)
* Node.js version (unless using Appium.app|exe): v14.9.0
* Npm or Yarn package manager: 6.14.8
* Mobile platform/version under test: iOS 14.0
* Real device or emulator/simulator: iPhone SE (2nd Generation), real device
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

https://gist.github.com/frangipanes/bf120de21be9032f4820c61e18ffe273

Please let me know if there is any more information I can provide.

**Comment by mykola-mokhnach** [comment]
Please provide the page source when the alert is visible

**Comment by mykola-mokhnach** [comment]
and the full server log

**Comment by frangipanes** [comment]
I've added the requested information to the description.

**Comment by mykola-mokhnach** [comment]
It looks like the stuff works, but it just does not have enough time to be executed. I would try to increase the delay between element lookup retries to at least 2-3 seconds, so the background thread has time for an alert detection. Also, it makes sense to enable xcodebuild logging in capabilities. When it is enabled then it is possible to see what XCTest is actually doing in the background.

**Comment by amedvedjev** [comment]
note that button sequence of location alert changed:
 - iOS 14: Allow while in use / Always Allow / Not Allow 
 - iOS 13: Always Allow / Allow while in use / Not Allow 

![image](https://user-images.githubusercontent.com/2756856/93516864-4a18a980-f933-11ea-9b12-a1a0a9958d22.png)
![image](https://user-images.githubusercontent.com/2756856/93516633-002fc380-f933-11ea-8dfa-c42a1239e158.png)

**Comment by mykola-mokhnach** [comment]
Button locator could be customised using acceptAlertButtonSelector/dismissAlertButtonSelector settings

**Comment by KazuCocoa** [comment]
settings api: http://appium.io/docs/en/advanced-concepts/settings/

**Comment by frangipanes** [comment]
I'm pleased to say that the workaround suggested using `acceptAlertButtonSelector` works. However I would still expect the bug to be fixed.

**Comment by mykola-mokhnach** [comment]
> However I would still expect the bug to be fixed.

Unfortunately there is nothing else to fix there. Xctest does not provide any information on which button in alert does what, so we just use very simple rules to detect these, which don't always work as expected. I you still think this is a bug then please report it to Apple.

**Comment by prabhus06** [comment]
is there any example on how to use acceptAlertButtonSelector

**Comment by KazuCocoa** [comment]
http://appium.io/docs/en/advanced-concepts/settings/index.html 's `acceptAlertButtonSelector`. The format is class chain, so https://github.com/facebookarchive/WebDriverAgent/wiki/Class-Chain-Queries-Construction-Rules might help as linked from the description.

**Comment by blane1988** [comment]
For those who want to know what the implementation for this looks like (Javascript), see below snippet. For dealing with the aforementioned Settings API, you use `driver.updateSettings()` method. 

I am just updating `acceptAlertButtonSelector` selection strategy in my case. I got the value from Appium Desktop's -ios class chain property for the specific button on that location permission modal.

```
driver.updateSettings({
    acceptAlertButtonSelector: "**/XCUIElementTypeButton[`label == 'Allow While Using App'`]",
});
```

**Comment by PaulosSouza** [comment]
@blane1988 Hi. How to initialize the variable driver?

**Comment by blane1988** [comment]
@PaulosSouza Hello. This is written in Javascript. I don't ever initialize `driver`, like in Java. It is globally available from the start. What is your setup (test language, runner, etc)?

**Comment by PaulosSouza** [comment]
That's weird. I'm using codeceptjs, but when I call the variable, the codecept doesn't recognize. I'm using javascript as well

**Comment by blane1988** [comment]
I see. That might be it. I am using WebdriverIO Runner which handles creating the `driver` object so it can be referenced from anywhere.

**Comment by PaulosSouza** [comment]
Hmm ... I'll see about WebdriverIO Runner. Thanks :)

**Comment by azetaa** [comment]
Why is this closed? the documentation says ```Accept all iOS alerts automatically if they pop up. This includes privacy access permission alerts (e.g., location, contacts, photos). Default is false.```. This does not work for location. When will this be fixed?

**Comment by giovanihoff** [comment]
This problem persists! Please any solution?

**Comment by blane1988** [comment]
What Appium version are you on? We had this issue before, but it went away, and location modal is now successfully accepted via auto-accept.

Regardless, here is a workaround that was slightly slower than the auto-accept. We basically had to do the job ourselves to accept permission:

```
const locationAcceptSelector = `**/XCUIElementTypeButton[\`label = "Allow Once"\`]`;
const locationAcceptClassChain = `-ios class chain:${locationAccept}`;
$(locationAcceptClassChain).touchAction('tap');
```

**Comment by giovanihoff** [comment]
> What Appium version are you on? We had this issue before, but it went away, and location modal is now successfully accepted via auto-accept.
> 
> Regardless, here is a workaround that was slightly slower than the auto-accept. We basically had to do the job ourselves to accept permission:
> 
> ```
> const locationAcceptSelector = `**/XCUIElementTypeButton[\`label = "Allow Once"\`]`;
> const locationAcceptClassChain = `-ios class chain:${locationAccept}`;
> $(locationAcceptClassChain).touchAction('tap');
> ```

Thanks. I'll try. Appium version:1.21.0

**Comment by giovanihoff** [comment]
> > What Appium version are you on? We had this issue before, but it went away, and location modal is now successfully accepted via auto-accept.
> > Regardless, here is a workaround that was slightly slower than the auto-accept. We basically had to do the job ourselves to accept permission:
> > ```
> > const locationAcceptSelector = `**/XCUIElementTypeButton[\`label = "Allow Once"\`]`;
> > const locationAcceptClassChain = `-ios class chain:${locationAccept}`;
> > $(locationAcceptClassChain).touchAction('tap');
> > ```
> 
> Thanks. I'll try. Appium version:1.21.0

driver.setSetting("acceptAlertButtonSelector", "**/XCUIElementTypeButton[`label == 'Allow While Using App'`]");

Thank you!

**Comment by awhisler** [comment]
> For those who want to know what the implementation for this looks like (Javascript), see below snippet. For dealing with the aforementioned Settings API, you use `driver.updateSettings()` method.
> 
> I am just updating `acceptAlertButtonSelector` selection strategy in my case. I got the value from Appium Desktop's -ios class chain property for the specific button on that location permission modal.
> 
> ```
> driver.updateSettings({
>     acceptAlertButtonSelector: "**/XCUIElementTypeButton[`label == 'Allow While Using App'`]",
> });
> ```

Why does this not work for me? It does not not click it at all. 
```"@wdio/appium-service": "^8.29.7",
    "@wdio/cli": "^8.29.7",
    "@wdio/local-runner": "^8.29.7",
    "@wdio/mocha-framework": "^8.29.3",
    "@wdio/spec-reporter": "^8.29.7",
    "allure-commandline": "^2.27.0",
    "appium-xcuitest-driver": "^6.0.0",```

**Comment by DoHue97** [comment]
> > For those who want to know what the implementation for this looks like (Javascript), see below snippet. For dealing with the aforementioned Settings API, you use `driver.updateSettings()` method.
> > I am just updating `acceptAlertButtonSelector` selection strategy in my case. I got the value from Appium Desktop's -ios class chain property for the specific button on that location permission modal.
> > ```
> > driver.updateSettings({
> >     acceptAlertButtonSelector: "**/XCUIElementTypeButton[`label == 'Allow While Using App'`]",
> > });
> > ```
> 
> Why does this not work for me? It does not not click it at all.
> 
> ```
> capabilities: [
>     {
>       // capabilities for local Appium web tests on iOS
>       "appium:app": `${__dirname}/ios/PropertyAssistantStaging.app`,
>       "platformName": "iOS",
>       "appium:udid": "6F898865-257E-43C8-9310-EA03E22A6A31",
>       "appium:deviceName": "iPhone 15",
>       "appium:platformVersion": "17.0",
>       "appium:automationName": "XCUITest",
>       "appium:autoGrantPermissions": true,
>       "appium:locationServicesAuthorized": true,
>       "appium:autoAcceptAlerts": true,
>      "appium:locationServicesEnabled": false
>     },
>   ],
> ```
> 
> ```
>     "@wdio/cli": "^8.29.7",
>     "@wdio/local-runner": "^8.29.7",
>     "@wdio/mocha-framework": "^8.29.3",
>     "@wdio/spec-reporter": "^8.29.7",
>     "allure-commandline": "^2.27.0",
>     "appium-xcuitest-driver": "^6.0.0",```
> ```

Hi do you have any suggest for the auto allow location permission on ios? im having this issue.

**Comment by tvarma-solver** [comment]
Hello, I've come across this issue recently. We're using webdriverio+appium to automate mobile scenarios. As part of this after logging and navigating to particular scene, this location modal is popping up and the autoAcceptAlerts/autoGrantPermissions doesn't seem to work. If anyone have fix for this, pls let me know.

**Comment by tvarma-solver** [comment]
Found a solution for this in other forums
https://discuss.appium.io/t/location-service-popup/34575/4

updated the code from above discussion to typescript - webdriverio+appium and added it in beforeHook, which solved my issue

```
    await driver.updateSettings({
      acceptAlertButtonSelector:
        "**/XCUIElementTypeButton[`label == 'Allow While Using App'`]",
    });

```
