### ISSUE TITLE
appium 1.18.2 - Building scheme "YYCache iOS" in YYCache.xcodeproj - Task failed with exit code 65:

### ISSUE THREAD

**Issue by shaky** [appium/appium#14748]
Hi there, first I want to THANK YOU for all the efforts put into the Xcode 12 update.

I have installed `appium 1.18.2` + `carthage 0.36` and tried to run `./Scripts/bootstrap.sh -d`  and I get this failure 

```
appium-webdriveragent ./Scripts/bootstrap.sh -d                                                    
Fetching dependencies
Applying Carthage build workaround to exclude Apple Silicon binaries. See https://github.com/Carthage/Carthage/issues/3019 for more details
*** Checking out CocoaAsyncSocket at "72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc"
*** Checking out YYCache at "1.1.0"
*** xcodebuild output can be found in /var/folders/41/0dtvw_tx4v11gntm929t_lsm0000gs/T/carthage-xcodebuild.GNEjYl.log
*** Building scheme "tvOS Framework" in CocoaAsyncSocket.xcodeproj
*** Building scheme "iOS Framework" in CocoaAsyncSocket.xcodeproj
*** Building scheme "YYCache iOS" in YYCache.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Checkouts/YYCache/Framework/YYCache.xcodeproj -scheme YYCache\ iOS -configuration Release -derivedDataPath /Users/testuser/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/YYCache/1.1.0 -sdk iphonesimulator -destination platform=iOS\ Simulator,id=B92EA767-3736-486E-AF53-4614BF26EFBA -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Checkouts/YYCache)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/41/0dtvw_tx4v11gntm929t_lsm0000gs/T/carthage-xcodebuild.GNEjYl.log
```

If I manually run 
`/usr/bin/xcrun xcodebuild -project /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Checkouts/YYCache/Framework/YYCache.xcodeproj -scheme YYCache\ iOS -configuration Release -derivedDataPath /Users/testuser/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/YYCache/1.1.0 -sdk iphonesimulator -destination platform=iOS\ Simulator,id=B92EA767-3736-486E-AF53-4614BF26EFBA -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build`

but I replace `ONLY_ACTIVE_ARCH=NO` with `ONLY_ACTIVE_ARCH=YES` then the build is successful.

How can I change that NO to YES value into the bootstrap context? If I re-run `./Scripts/bootstrap.sh -d` it will not skip the YYCache setup so it will fail again.

Thanks!

**Comment by mykola-mokhnach** [comment]
I'm afraid Carthage does not expose any command line arg that allows to change that param: https://github.com/Carthage/Carthage/pull/580

**Comment by shaky** [comment]
thank you so much for the reply @mykola-mokhnach 
what would be the easiest workaround in this case?

**Comment by mykola-mokhnach** [comment]
Create a PR to Carthage and make that arg customisable?

**Comment by shaky** [comment]
thanks @mykola-mokhnach, let me see what I can do.

**Comment by mykola-mokhnach** [comment]
@Dan-Maor Do you know any workarounds to these issues? The most radical solution would be to get rid of carthage at all and connect all modules as static frameworks?

**Comment by Dan-Maor** [comment]
Weird, when I try to run the bootstrap script on my machine with Xcode 12.0 it builds correctly.
@shaky Can you please share the full xcodebuild log from the failed attempt? Maybe we can find a hint there.

**Comment by shaky** [comment]
sure!

Thanks @Dan-Maor 

[excodebuild.log](https://github.com/appium/appium/files/5254887/excodebuild.log)

**Comment by Dan-Maor** [comment]
`error: The linked framework 'UIKit.framework' is missing one or more architectures required by this target: i386. (in target 'YYCache iOS' from project 'YYCache')`
This looks like a problem with the local Xcode installation, can you please try to re-install Xcode and test again?

**Comment by shaky** [comment]
Thanks for reply @Dan-Maor 

I've reinstalled Xcode 12 (downloaded from the Apple developer portal) and executed the following steps:

npm install -g appium --chromedriver-skip-install
brew install carthage
sudo chown -R $USER /usr/local/lib
cd /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent
mkdir -p Resources/WebDriverAgent.bundle
./Scripts/bootstrap.sh -d => 🔥 `same error` 🔥

I have the following environment
macOS Catalina: 10.15.6 (19G2021)
Xcode 12.0 (12A7209)
Carthage 0.36.0
appium-webdriver 6.14.8 or 6.14.5 (I get the same results)

any other workaround please?

Thanks in advance, your reply are highly appreciated.

**Comment by mykola-mokhnach** [comment]
Try to manually edit Cartfile.resolved and change the version of YYCache to 1.1.1

**Comment by shaky** [comment]
thanks @mykola-mokhnach, no error was returned when running the bootstrap.sh, I presume that YYCache version change helped.

Now I get a different type of error


`(venv) ➜  appium-webdriveragent xcodebuild -project WebDriverAgent.xcodeproj \
           -scheme WebDriverAgentRunner \
           -destination 'platform=iOS Simulator,name=iPhone X' \
           test
Command line invocation:
    /usr/local/mobile/developer/tools/ios/Xcode12.app/Contents/Developer/usr/bin/xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination "platform=iOS Simulator,name=iPhone X" test

note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description
error: Building for iOS Simulator, but the linked framework 'XCTAutomationSupport.framework' was built for tvOS. (in target 'WebDriverAgentLib' from project 'WebDriverAgent')
error: Building for iOS Simulator, but the linked framework 'XCTest.framework' was built for iOS. (in target 'WebDriverAgentLib' from project 'WebDriverAgent')


Test session results, code coverage, and logs:
        /Users/testuser/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu/Logs/Test/Test-WebDriverAgentRunner-2020.09.21_19-30-31-+0100.xcresult

Testing failed:
        Building for iOS Simulator, but the linked framework 'XCTAutomationSupport.framework' was built for tvOS.
        Building for iOS Simulator, but the linked framework 'XCTest.framework' was built for iOS.
        Testing cancelled because the build failed.

** TEST FAILED **
`

**Comment by dpgraham** [comment]
@shaky can you try installing the latest RC, we have a fix: `npm install -g appium@1.18.3-rc.1`

**Comment by shaky** [comment]
Thank you for the update @dpgraham 
The bootstrap is fine now but when I'm trying to run a test it fails with the same error I got here https://github.com/appium/appium/issues/14748#issuecomment-696292645

Full log attached.
[appium.log](https://github.com/appium/appium/files/5259515/appium.log)


Many thanks again!

**Comment by shaky** [comment]
Found a workaround:

I noticed that when I run a test the `~/Library/Developer/Xcode/DerivedData` is generating the usual `WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu` (random id) but the `WebDriverAgentRunner-Runner.app` is missing.

So inside `WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu/Build` I manually created a folder called `Products` and inside that another folder called `Debug-iphonesimulator`

Then I copied the `WebDriverAgentRunner-Runner.app` (unziped from `/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgentRunner-Runner.app.zip`)

then I enabled these two capabilities:
'usePrebuiltWDA': 'true',
'derivedDataPath': /Users/testuser/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu

Seems like it's working

**Comment by mykola-mokhnach** [comment]
Something looks really odd on your build machine. We are unable to reproduce any of the mentioned issues neither locally nor in Azure CI. Try to deploy the module on a clean machine. Although the workaround is ok unless it works for you.

**Comment by shaky** [comment]
Thanks for all the help @mykola-mokhnach @dpgraham @Dan-Maor 

I think we can close this ticket now.

**Comment by dpgraham** [comment]
Awesome thanks @shaky 

Nice work @mykola-mokhnach and @Dan-Maor
