### ISSUE TITLE
io.appium.uiautomator2 finds not existent in DOM element using 'MobileBy.AndroidUIAutomator'

### ISSUE THREAD

**Issue by Yachkurynski** [appium/appium#14750]
## The problem

In case we use findElement(MobileBy.AndroidUIAutomator()) from already found webElement it always returns some fake element whether it exists in DOM or not.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS Catalina v10.15.6
* Node.js version (unless using Appium.app|exe): 14.9.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Android 10
* Real device or emulator/simulator: real device 
* Appium CLI or Appium.app|exe: CLI

## Details

In our TAF we want to use MobileBlocks and that's why we have to use some webElements as search context for inner elements. 

Firstly I faced with this issue using FindBySet annotation, when it returns to me the element, which I couldn't use - getText, getAnnotation, etc. methods throw _org.openqa.selenium.StaleElementReferenceException_. The element was 'found' by first locator from set which was wrong for this page (element with first locator wasn't exist in DOM), but it should be found by the second one.

Then issue was reproduced for 
_findElement(MobileBy.AndroidUIAutomator("...")).findElement(MobileBy.AndroidUIAutomator("..."))_ 
simple construction.

This case looks like already fixed for xpath: https://github.com/appium/appium/issues/14586

## Link to Appium logs

[appium_log.txt](https://github.com/appium/appium/files/5259594/appium_log.txt)

## Code To Reproduce Issue [ Good To Have ]

_Just call something like this (first findElement should be called on existent element):_ 

WebElement fakeElement = driver.findElement(MobileBy.AndroidUIAutomator("new UiSelector().resourceIdMatches(\".*outer_existent_element\")"))
                .findElement(MobileBy.AndroidUIAutomator("new UiSelector().resourceIdMatches(\".*inner_nonexistent_element\")")); //will return some element
fakeElement.click(); //will throw org.openqa.selenium.StaleElementReferenceException

**Comment by Yachkurynski** [comment]
## Add appium logs for ApiDemos-debug.apk:

As you can see in logs, webElement was successfully found, but when driver tries to click on it StaleElementReferenceException throws.

### Code

driver
                .findElement(MobileBy.AndroidUIAutomator("new UiSelector().resourceIdMatches(\"android:id/action_bar_container\")"))
                .findElement(MobileBy.AndroidUIAutomator("new UiSelector().resourceIdMatches(\".*inner_element\")")).click();

### Logs

[debugApp_appium_log.txt](https://github.com/appium/appium/files/5259730/debugApp_appium_log.txt)

**Comment by mykola-mokhnach** [comment]
Please check if https://github.com/appium/appium-uiautomator2-server/pull/381/ works for you

**Comment by Yachkurynski** [comment]
> Please check if [appium/appium-uiautomator2-server#381](https://github.com/appium/appium-uiautomator2-server/pull/381) works for you

Ok, I will build apk and check it ASAP.

**Comment by Yachkurynski** [comment]
YEH! It works! 
Thank you, @mykola-mokhnach!

**Comment by mykola-mokhnach** [comment]
The patch has been published to appium@beta

**Comment by chetanJTH** [comment]
@mykola-mokhnach : i am using appium v 1.20 but i have similiar issue. same element is enable in previous test but not present in DOM in next testcase.
