### ISSUE TITLE
Android Setting app not getting launched

### ISSUE THREAD

**Issue by geeethub** [appium/appium#14755]
## The problem

I am trying switch between my AUT and the Settings app for multiple purposes like toggling WiFi ,Toggling VPN,Changing device time etc.I am not able to launch the settings app in my device or emulator

## Environment

* Appium version:1.18.1
* Desktop OS/version used to run Appium:Mac OS (Catalina)
* Mobile platform/version under test:Android
* Real device or emulator/simulator:both
* Appium CLI or Appium.app|exe:Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/geeethub/daaa6d08949d6e45a310e9b1238a0d43

## Code To Reproduce Issue [ Good To Have ]

`if(platformName.equals("Android")){
				((StartsActivity) new DriverManager().getDriver()).startActivity(new Activity("com.android.settings", "com.android.settings.Settings"));`

**Comment by mykola-mokhnach** [comment]
Have you read the troubleshooting link?

**Comment by geeethub** [comment]
> Have you read the troubleshooting link?

yes I have and tried to implement all of it..but the issue still persists

**Comment by mykola-mokhnach** [comment]
What exactly did you try? What is the result if the manual activity execution?

**Comment by mykola-mokhnach** [comment]
Closed because of no response
