### ISSUE TITLE
WDA is currently not running | YYCache/YYCache.h file not found | Cannot start Webdriver agent on real device

### ISSUE THREAD

**Issue by AndrewNaveen** [appium/appium#14759]
## Problem:

Webdriver agent was installed and working on my iPhone until suddenly it stopped working. There were updates to my Xcode which is now at 12.0.
App installation is successful but can't access anything other than that, and trying to get the WDA running on my device has been unsuccessful. 
Pretty much tried every troubleshooting help from the internet. I'm out of options and missing something that I cannot figure out.
PLEASE HELP! 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.2
* Last Appium version that did not exhibit the issue (if applicable): 17
* Desktop OS/version used to run Appium: macOS Catalina 10.15.6
* Node.js version (unless using Appium.app|exe): 
* Npm or Yarn package manager:
* Mobile platform/version under test: ios 13.7
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium desktop 1.18.0-2
* Xcode: 12.0

## Details

I tried following the steps like this in order,

cd /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent
rm -rf ~/Library/Caches/org.carthage.CarthageKit
rm -rf /Carthage
brew uninstall --force carthage
brew install carthage
mkdir -p Resources/WebDriverAgent.bundle
./Scripts/bootstrap.sh -d
carthage bootstrap --platform iOS\,tvOS (Same error output)
## Issue: Failing to compile

Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Users/as1046924/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/CocoaAsyncSocket/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc/Build/Intermediates.noindex/ArchiveIntermediates/tvOS\ Framework/IntermediateBuildFilesPath/UninstalledProducts/appletvos/CocoaAsyncSocket.framework/CocoaAsyncSocket /Users/as1046924/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/CocoaAsyncSocket/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc/Build/Products/Release-appletvsimulator/CocoaAsyncSocket.framework/CocoaAsyncSocket -output /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Build/tvOS/CocoaAsyncSocket.framework/CocoaAsyncSocket

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: 
The logs look like,
** BUILD SUCCEEDED **

## Link to Appium logs
Same logs as above.

## Notes:
I downgraded the xcode to 11.6 and ran the above commands, the compile was successful but met with this error while trying to build WDA.
Could not build module 'CocoaAsyncSocket'.

**Comment by mykola-mokhnach** [comment]
Get the recent WDA sources from master at https://github.com/appium/WebDriverAgent or use appium@beta. Also, you could exclude tvOS platform from bootstrapping if you don't need it

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by tiecongli** [comment]
@mykola-mokhnach 
Do we have a way to work with xcode 12? I knew there is problem of Carthage. Do we have official workaround for appium user to get around that problem. I think it is blocking lots of appium users currently.

**Comment by mykola-mokhnach** [comment]
@tiecongli appium@beta does work with recent xcode release and has all the necessary workarounds. Unfortunately I don't decide myself on the release dates.

**Comment by tiecongli** [comment]
Thank you!

**Comment by Alona-T** [comment]
@mykola-mokhnach i still face the same issue
I have updated appium to beta (v 1.19.0)
Derived data is cleared before executing this command carthage bootstrap --platform iOS
However i still see the same issue author mentioned
