### ISSUE TITLE
Allocation failed - JavaScript heap out of memory in Appium 1.18.2

### ISSUE THREAD

**Issue by sshock** [appium/appium#14766]
## The problem

Seeing this error on my servers that I upgraded to Appium 1.18.2 six days ago:

```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

We ran into this before in Appium 1.18.0 (see #14683), and it got fixed, but sadly it seems to have resurfaced again :(

It's crashing about 6 times, so about once a day.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.2
* Last Appium version that did not exhibit the issue (if applicable): 1.18.0-beta (and 1.18.1 I think)
* Desktop OS/version used to run Appium: Ubuntu 18.04
* Node.js version (unless using Appium.app|exe): 10.22.0
* Npm or Yarn package manager: npm 6.14.8
* Mobile platform/version under test: android
* Real device or emulator/simulator: real
* Appium CLI or Appium.app|exe: cli

## Details

Here is one example that includes a call stack.  More examples can be found in the log file linked to below.

```
<--- Last few GCs --->

[3985:0x416d8d0] 145802907 ms: Mark-sweep 1315.9 (1428.4) -> 1313.9 (1428.4) MB, 2345.9 / 0.0 ms  (average mu = 0.170, current mu = 0.081) allocation failure scavenge might not succeed
[3985:0x416d8d0] 145805522 ms: Mark-sweep 1316.0 (1428.4) -> 1314.1 (1432.9) MB, 2278.0 / 0.0 ms  (average mu = 0.150, current mu = 0.129) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0xeb7e195be1d]
Security context: 0x14d88f79e6c1 <JSObject>
    1: nextTick(aka nextTick) [0x218cc1b47e59] [internal/process/next_tick.js:~96] [pc=0xeb7e6334d8a](this=0x09a59a9826f1 <undefined>,callback=0x1087c5eafbe9 <JSFunction afterWrite (sfi = 0x3a9f24d64d61)>)
    2: arguments adaptor frame: 5->1
    3: onwrite(aka onwrite) [0x1087c5eafba9] [/home/deployer/node_modules/appium/node_modules/winston-transport/node_m...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x8fb090 node::Abort() [node]
 2: 0x8fb0dc  [node]
 3: 0xb033ae v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb035e4 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xef7642  [node]
 6: 0xef7748 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [node]
 7: 0xf03822 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0xf04154 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xf06dc1 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [node]
10: 0xed0244 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [node]
11: 0x117031e v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [node]
12: 0xeb7e195be1d
```

## Link to Appium logs

https://gist.github.com/sshock/3bc6da8fc982b5b1a9eaf4c28d6f1eae

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing much to do there without the heap snapshot. Also, please use appium@beta to make sure the recent fixes are there

**Comment by sshock** [comment]
Here is a screenshot comparing 6 servers running Appium 1.18.2 to six servers running Appium 1.17.1.

![appium mem usage](https://user-images.githubusercontent.com/1693761/94476757-20128300-018e-11eb-83e5-415847134469.png)

**Comment by sshock** [comment]
> Unfortunately there is nothing much to do there without the heap snapshot.

@mykola-mokhnach That's too bad.  Last time I got lucky because you were able to locate and fix the problem without me ever having obtained a heap snapshot.

> Also, please use appium@beta to make sure the recent fixes were applied

I was using appium@beta a week or so ago (which shows up as 1.8.0-beta after installing), but I assumed appium 1.18.2, which was barely released a week ago, would have included all the memory fixes you made that fixed the problem when I was testing it before for #14683.  Does appium 1.18.2 not include all the fixes?

**Comment by mykola-mokhnach** [comment]
> Does appium 1.18.2 not include all the fixes?

No it does not. It is easy to verify that by listing the npm lock-file. The 1.18.2 patch only includes recent fixes needed for iOS14/Xcode14 support 

> That's too bad. Last time I got lucky because you were able to locate and fix the problem without me ever having obtained a heap snapshot.

Yes, it's just a pure luck, because we got another issue, where we had the memory dump.

**Comment by sshock** [comment]
@mykola-mokhnach Ah, that makes sense.  It was just a patch release.  I should have known when I read the description and it didn't say anything about fixing memory leaks.

How soon can I expect a release with the memory leak fixes?

Anyway, I'll install appium@beta now and watch it for a few days to see if the OOM problem goes away.  If so, we can close this.

**Comment by sshock** [comment]
FYI, I've had no memory issues with appium in the last 9 days since installing appium@beta.
