### ISSUE TITLE
Appium firstly navigate to other url on real iOS device on Safary

### ISSUE THREAD

**Issue by RomanShmandrovskyi** [appium/appium#14761]
## The problem

When run tests on real iOS device in Safary browser appium firstly navigate to  http://appium.io

## Details

Found this code lines inside appium sources in `appium/node-modules/appium-xcuitest-driver/lib/driver.js`:

```javascript
this._currentUrl = this.opts.safariInitialUrl || (
    this.isRealDevice()
     ? 'http://appium.io'
     : http://${this.opts.address}:${this.opts.port}/welcome
);
```

Yes, I now that I can set the `safariInitialUrl` in capabilities. But also in driver creation method I write something like:
```javascript
driver.get(System.getProperty("url"));
```
If I set `safariInitialUrl` in capabilities it will load page twice... First time for `safariInitialUrl` and second time from driver command. 
But there is anything like this for Chrome on android... I need to use `get()` driver command to navigate url on Android.

And also, as Apple not provide functionality to clear Safary session (due to [this](https://github.com/appium/appium/issues/7882) issue), it will load it one more time from the previous tests. Three times!

Is this Easter Egg is really needed in Appium code?
Thanks!

**Comment by KazuCocoa** [comment]
How about providing `about:blank` as `safariInitialUrl` for a real device?

I forgot the exact reason, but Appium set a url to Safari by some historical reason.

**Comment by RomanShmandrovskyi** [comment]
@KazuCocoa I try to provide blank String here like: `""` or `" "`. It also not works here...

**Comment by RomanShmandrovskyi** [comment]
@KazuCocoa  or you mean set the value `about:blank` for `safariInitialUrl` parameter?

**Comment by KazuCocoa** [comment]
Yes. For browsers, about:blank has a special meaning

**Comment by mykola-mokhnach** [comment]
Closed because of no response
