### ISSUE TITLE
Unable to switch to web view in xamarin hybrid app on iOS 14

### ISSUE THREAD

**Issue by praveen01t** [appium/appium#14760]
## The problem

Xamarin hybrid app not switching to Webview, driver.getContextHandles returns only "NATIVE_APP" even after page navigate to WebView.

## Environment

* Appium version (or git revision) that exhibits the issue:1.18.2
* Last Appium version that did not exhibit the issue (if applicable):NA
* Desktop OS/version used to run Appium: macOS Catalina version - 10.15.6
* Node.js version (unless using Appium.app|exe): Node -14.5.0
* Npm or Yarn package manager: npm - 6.14.5
* Mobile platform/version under test:IOS 14.0.1
* Real device or emulator/simulator: Real Device (IPhone XS Max)

## Details

Our xamarin app has to open Azure login page, we are using "openURL"  instance method to launch the login page.
https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623073-application?language=objc

When the app navigate to login page driver.getContextHandles returns only NATIVE_APP and it is not switching to webview context. But it works fine if we launch the Safari by default and automate the azure login page using appium.

## Link to Appium logs
[Webview_Failure.txt](https://github.com/appium/appium/files/5279377/Webview_Failure.txt)

**Comment by KazuCocoa** [comment]
I'm afraid I misunderstood, but how about setting `includeSafariInWebviews` https://github.com/appium/appium-xcuitest-driver as the capability to include Safari browser webview in get contexts?

**Comment by mykola-mokhnach** [comment]
Are you able to see the web view via Safari Remote debugger?

**Comment by praveen01t** [comment]
I tried the desired capability "includeSafariInWebViews", it is not working. Still it returns only NATIVE_APP.
cap.SetCapability("includeSafariWebViews", "true")

I am able to see the web view via Safari Remote debugger. I navigated to the web view from app and inspected it from mac machine  (Safari -> Develop -> IPhone XS Max -> login.microsoftonline.com).

**Comment by KazuCocoa** [comment]
Probably Web Inspector fond the page but it did not return the page since you specified `com.apple.DocumentsApp` as the current test target. How about adding your Xamarin app bundle id as `additionalWebviewBundleIds` https://github.com/appium/appium-xcuitest-driver ? It allows Appium to return Web Views in the bundle ids.

```
[debug] [simctl] XCUITest No key id found. Choosing first id from page array
[debug] [simctl] XCUITest Page change not referring to currently selected app, ignoring.
[debug] [simctl] RemoteDebugger Page changed: {
[debug] [simctl] RemoteDebugger   "13": {
[debug] [simctl] RemoteDebugger     "WIRTitleKey": "Sign in to your account",
[debug] [simctl] RemoteDebugger     "WIRTypeKey": "WIRTypeWebPage",
[debug] [simctl] RemoteDebugger     "WIRURLKey": "https://login.microsoftonline.com/common/oauth2/v2.0/authorize?scope=Directory.Read.All+Files.Read.All+offline_access+openid+profile+User.Read&response_type=code&client_id=40ef700f-b021-4fe4-81fe-b2536e9701c3&redirect_uri=msal40ef700f-b021-4fe4-81fe-b2536e9701c3%3A%2F%2Fauth&client-request-id=bdc13ae6-1cd6-4733-9ed0-362cfc1c14ce&x-client-SKU=MSAL.Xamarin.iOS&x-client-Ver=2.1.0.0&x-client-OS=14.0&x-client-DM=iPhone&prompt=select_account&code_challenge=bet25_CtpeDa5SnCPzIFQeEwNXUjLchFs0Ba9MwhLkM&code_challenge_method=S256&state=ee3a4240-fc14-4aa0-9fb8-5ff81cb736f5",
[debug] [simctl] RemoteDebugger     "WIRPageIdentifierKey": 13
[debug] [simctl] RemoteDebugger   },
[debug] [simctl] RemoteDebugger   "54": {
[debug] [simctl] RemoteDebugger     "WIRTitleKey": "Sign in to your account",
[debug] [simctl] RemoteDebugger     "WIRTypeKey": "WIRTypeWebPage",
[debug] [simctl] RemoteDebugger     "WIRURLKey": "https://login.microsoftonline.com/common/oauth2/v2.0/authorize?scope=Directory.Read.All+Files.Read.All+offline_access+openid+profile+User.Read&response_type=code&client_id=40ef700f-b021-4fe4-81fe-b2536e9701c3&redirect_uri=msal40ef700f-b021-4fe4-81fe-b2536e9701c3%3A%2F%2Fauth&client-request-id=f07b59ce-0827-4836-84cc-b85ec84cc174&x-client-SKU=MSAL.Xamarin.iOS&x-client-Ver=2.1.0.0&x-client-OS=14.0&x-client-DM=iPhone&prompt=select_account&code_challenge=jJempqGEhf9AfpcU2GNN1zkXY9kU83GtSkZ2ynrbHts&code_challenge_method=S256&state=5895a30d-d272-4395-8e03-7fc9f1295a85",
[debug] [simctl] RemoteDebugger     "WIRPageIdentifierKey": 54
[debug] [simctl] RemoteDebugger   }
[debug] [simctl] RemoteDebugger }
[debug] [simctl] XCUITest Remote debugger notified us of a new page listing: {"appIdKey":"688","pageArray":[{"id":13,"title":"Sign in to your account","url":"https://login.microsoftonline.com/common/oauth2/v2.0/authorize?scope=Directory.Read.All+Files.Read.All+offline_access+openid+profile+User.Read&response_type=code&client_id=40ef700f-b021-4fe4-81fe-b2536e9701c3&redirect_uri=msal40ef700f-b021-4fe4-81fe-b2536e9701c3%3A%2F%2Fauth&client-request-id=bdc13ae6-1cd6-4733-9ed0-362cfc1c14ce&x-client-SKU=MSAL.Xamarin.iOS&x-client-Ver=2.1.0.0&x-client-OS=14.0&x-client-DM=iPhone&prompt=select_account&code_challenge=bet25_CtpeDa5SnCPzIFQeEwNXUjLchFs0Ba9MwhLkM&code_challenge_method=S256&state=ee3a4240-fc14-4aa0-9fb8-5ff81cb736f5","isKey":false},{"id":54,"title":"Sign in to your account","url":"https://login.microsoftonline.com/common/oauth2/v2.0/authorize?scope=Directory.Read.All+Files.Read.All+offline_access+openid+profile+User.Read&response_type=code&client_id=40ef700f-b021-4fe4-81fe-b2536e9701c3&redirect_uri=msal40ef700f-b021-4fe4-81fe-b2536e9701c3%3A%2F%2Fauth&client-request-id=f07b59ce-0827-4836-84cc-b85ec84cc174&x-client-SKU=MSAL.Xamarin.iOS&x-client-Ver=2.1.0.0&x-client-OS=14.0&x-client-DM=iPhone&prompt=select_account&code_challenge=jJempqGEhf9AfpcU2GNN1zkXY9kU83GtSkZ2ynrbHts&code_challenge_method=S256&state=5895a30d-d272-4395-8e03-7fc9f1295a85","isKey":false}]}
[debug] [simctl] XCUITest No key id found. Choosing first id from page array
[debug] [simctl] XCUITest Page change not referring to currently selected app, ignoring.
[debug] [simctl] RemoteDebugger Notified that new application 'PID:4227' has connected
[simctl] BaseDriver Shutting down because we waited 60 seconds for a command
```

**Comment by praveen01t** [comment]
I tried with the desired capability "additionalWebviewBundleIds", but still it is not working.
Please see the logs.

[Appium2.txt](https://github.com/appium/appium/files/5295974/Appium2.txt)

**Comment by KazuCocoa** [comment]
It seems Appium returned two WebViews as below. `WEBVIEW_688.71` was `https://login.microsoftonline.com/common/oauth2.....`

```
[debug] [simctl] RemoteDebugger         hostId: "PID:5799"
[debug] [simctl] RemoteDebugger         isActive: true
[debug] [simctl] RemoteDebugger         isAutomationEnabled: "Unknown"
[debug] [simctl] RemoteDebugger Finally selecting app PID:688: [{"id":13,"title":"","url":"about:blank","isKey":false},{"id":71,"title":"Sign in to your account","url":"https://login.microsoftonline.com/common/oauth2/v2.0/authorize?scope=Directory.Read.All+Files.Read.All+offline_access+openid+profile+User.Read&response_type=code&client_id=40ef700f-b021-4fe4-81fe-b2536e9701c3&redirect_uri=msal40ef700f-b021-4fe4-81fe-b2536e9701c3%3A%2F%2Fauth&client-request-id=f717f51c-0327-4fad-a261-9b55dd3bc07f&x-client-SKU=MSAL.Xamarin.iOS&x-client-Ver=2.1.0.0&x-client-OS=14.0&x-client-DM=iPhone&prompt=select_account&code_challenge=0VZ0CXOGinecPNmvZ4s9kDSo7RSywtWJUJv9fnr-YSc&code_challenge_method=S256&state=1991c1c1-8637-41da-a06c-144312f82173","isKey":false}]
[debug] [simctl] RemoteDebugger Selected app after 107ms
[debug] [simctl] W3C (1f56d123) Responding to client with driver.getContexts() result: ["NATIVE_APP","WEBVIEW_688.13","WEBVIEW_688.71"]
[simctl] HTTP <-- GET /wd/hub/session/1f56d123-532f-4a59-babb-3724c9b6994d/contexts 200 116 ms - 58
```

**Comment by praveen01t** [comment]
Finally, I am able to switch to webview now after changed the code to iterate through getContextHandles() multiple times. 
Thank you so much for your support to resolve this issue.

 One quick question, I want to copy one .jpeg file from my mac machine to the IPhone path (Files -> On My IPhone).
I tried the below code, but it is not working. What is the correct method to do this?

driver.pushFile("com.apple.DocumentsApp/filename.jpe", imagebytearray)

**Comment by KazuCocoa** [comment]
Okay, glad to hear it.
You also can set `webviewConnectTimeout` https://github.com/appium/appium-xcuitest-driver as caps to add timeout for get context. But it would be generally better as you do now.

https://appium.io/docs/en/writing-running-appium/ios/ios-xctest-file-movement/ may help.
iOS limits file handling. So, you can only do the above link for files.
