### ISSUE TITLE
App is getting closed automatically after successful login

### ISSUE THREAD

**Issue by iKumarAnand** [appium/appium#14767]
App is getting closed after login, not able to perform other operation:

Same code was working fine earlier, but from last 2 days facing issues on that code.
When i logged in to the application and try to perform some operation on home screen after successful login, App is getting closed automatically and throwing below error.

org.openqa.selenium.support.ui.ExpectedConditions findElement
WARNING: WebDriverException thrown by findElement(By.xpath: //*[@content-desc='Acc'])
org.openqa.selenium.NoSuchSessionException: A session is either terminated or not started

Appium 1.17.1
Android Studio 4.0
Node.js 12.18.3
TestNG: 6.9.10

Eclipse: Oxygen.3a Release (4.7.3a)

Your assistance on this would help me tremendously.

Thanks you !

**Comment by mykola-mokhnach** [comment]
Unfortunately we cannot help nothing without the server log. Also, make sure the app itself does not crash

**Comment by iKumarAnand** [comment]
App is not getting crashed
And i have attached the server log. Please have a look.
[appium-server-logs.txt](https://github.com/appium/appium/files/5298330/appium-server-logs.txt)

**Comment by mykola-mokhnach** [comment]
> [info] [35m[HTTP][39m [90m[39m[warn] [35m[BaseDriver][39m Shutting down because we waited 60 seconds for a command
> [warn] [35m[Appium][39m Closing session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
> [info] [35m[Appium][39m Removing session '6e8e76e4-bf12-44f1-beb0-fc34fa8b9b51' from our master session list

The session has been terminated because of command timeout. I don't see any issues there

**Comment by iKumarAnand** [comment]
okay, let me remove the wait time and execute once.
Thanks!

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
