### ISSUE TITLE
In appium-uiautomator2-server FindElement by UiScrollable does not return the correct element anymore

### ISSUE THREAD

**Issue by bogdancucosel** [appium/appium#14775]
## The problem

Previous to appium version 18 a selector with UIScrollable that specifies a target element within the UIScrollable, would return the target element within the UIScrollable.

## Environment

* Appium version (or git revision) that exhibits the issue: **18.1**
* Last Appium version that did not exhibit the issue (if applicable): **17**

## Details

Given a selector like:
new UiScrollable(new UISelector().somethingScrollable...).setMaxSearchSwipes(20).scrollIntoView(new UiSelector().someElementInScrollable...);

The returned element would be the one specified by new UiSelector().someElementInScrollable...

At some point, things changed a bit https://github.com/appium/appium-uiautomator2-server/pull/336 .

Now the code in https://github.com/appium/appium-uiautomator2-server/blob/abbcd6c52331246efa69f35f711cfda996f3db24/app/src/main/java/io/appium/uiautomator2/utils/UiScrollableParser.java#L79
iterates through all the results , and if any of the results is a UIObject, the target selector is updated.

Because of .setMaxSearchSwipes(20) in the above selector, the list would contain the UIScrollable element itself , and the selector would be updated.

If we remove the .setMaxSearchSwipes(20) from the selector, the behavior is the same as before, that is returning the element new UiSelector().someElementInScrollable...
That is because of https://github.com/appium/appium-uiautomator2-server/blob/abbcd6c52331246efa69f35f711cfda996f3db24/app/src/main/java/io/appium/uiautomator2/utils/UiScrollableParser.java#L127

At this point, I would make a fix myself, if this is actually a bug, and not intended, but I am not sure what would be the best way.

I guess the point of iterating through the results would be to support UIScrollable methods that return a UIObject (like getChildByText) ?
Because otherwise I do not know how a UIObject would be returned by the consumeMethod ....

Could a fix be to to modify the condition when iterating through the results to not update the selector if the result is the UIScrollable itself ?

**Comment by mykola-mokhnach** [comment]
Try to change the implementation to make it working the way it was working before and check if all the existing tests still pass. If they do then please add one more test to cover the case above. If they don't then lets continue the discussion in that PR.

**Comment by bogdancucosel** [comment]
So I was on my way to create the PR and I found the findElementUsingUiAutomatorTest test, which seemed like the perfect one to modify. 

The selector used is:

`        By androidUiAutomator = By.androidUiAutomator("new UiSelector().text(\"Radio Group\");" +
                "new UiScrollable(new UiSelector().resourceId(\"android:id/list\"))" +
                ".scrollIntoView(new UiSelector().text(\"Radio Group\"));");`

This still works if I add the setMaxSearchSwipes method, because , after executing the UIScrollable, actually the selector that gets executed is new UiSelector().text(\"Radio Group\").

At this point I am thinking that maybe this is indeed the way UIScrollable should be used; the thing is that all examples I previously found on the net did not have that first UiSelector.

It actually makes a lot more sense now, because I can use any UiScrollable method and still return the item I need.

I think it is better to close this, as it seems that although it does not work exactly like before, I was not using the feature correctly.

Thanks and sorry for misunderstanding

**Comment by mykola-mokhnach** [comment]
No, problems. There are so many possible edge cases that probably no one could cover them all. Thanks for the detailed update.
