### ISSUE TITLE
Unable to create an account on Appium

### ISSUE THREAD

**Issue by NicoAtTangelo** [appium/appium#14778]
## The problem

Hi, This issue is exactly the same as https://github.com/appium/appium/issues/13789
The issue has been closed but is still occuring, at least for me.

Can you please help ? I don't receive any mail. Tried on 2 different address, checked the bin, spam everywhere. There's nothing.

**Comment by KazuCocoa** [comment]
@jlipps do you have any idea about this?

**Comment by jlipps** [comment]
https://github.com/appium/appium/issues/13789#issuecomment-724182998

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium/issues/13789#issuecomment-724182998

**Comment by dgchu21** [comment]
Hi, I'm experiencing a similar issue while creating an account on appium support.

**The issue:** the confirmation e-mail never arrives.

I've tried creating 2 accounts with different e-mails and it is still not working.

Can you please help? Thanks!
