### ISSUE TITLE
Virtual Elements frm QT app are not retrieved by UIAutomator2 Server

### ISSUE THREAD

**Issue by mstrelex** [appium/appium#14771]
## The problem

An App built using QT has some elements that are not retrieved by UIAutomator2 Server.
However using **uiautomatorviewer** from Android SDK - they are:

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17
* Mobile platform/version under test: Android

## Screenshots

![Screen Shot 2020-09-29 at 13 59 16](https://user-images.githubusercontent.com/5516364/94701338-2b86bb00-0302-11eb-8bb3-e47db1932d42.png)
![Screen Shot 2020-09-29 at 14 15 31](https://user-images.githubusercontent.com/5516364/94701349-2d507e80-0302-11eb-9510-b28c6fd5c5c5.png)

## App

App is available in store: https://play.google.com/store/apps/details?id=com.sphere.android.sphereapp

**Comment by mykola-mokhnach** [comment]
Are these "invisible" elements searchable using different locator types? Have you tried to play with `allowInvisibleElements`/`enableMultiWindows` driver settings?

**Comment by mykola-mokhnach** [comment]
> [warn] [35m[BaseDriver][39m The following capabilities were provided, but are not recognized by Appium:
> [warn] [35m[BaseDriver][39m   allowInvisibleElements
> [warn] [35m[BaseDriver][39m   connectHardwareKeyboard
> [warn] [35m[BaseDriver][39m   enableMultiWindows
> [warn] [35m[BaseDriver][39m   uuid

These are settings, not capabilities.

**Comment by mstrelex** [comment]
Sorry, tried those as settings now, but still no luck.
[settings.txt](https://github.com/appium/appium/files/5314893/settings.txt)

**Comment by mykola-mokhnach** [comment]
Unfortunately I don't have any other ideas. Our XML tree is built similarly to what `uiautomator dump` generates (https://android.googlesource.com/platform/frameworks/testing/+/476328047e3f82d6d9be8ab23f502a670613f94c/uiautomator/library/src/com/android/uiautomator/core/AccessibilityNodeInfoDumper.java -> https://github.com/appium/appium-uiautomator2-server/blob/master/app/src/main/java/io/appium/uiautomator2/model/UiElementSnapshot.java).

You could try Espresso driver as a possible workaround

**Comment by mykola-mokhnach** [comment]
I downloaded the app and tried to debug uia2 server on it. The downstream UIA framework returns exactly the same output as you can see in the AD inspector. Also, I've tried to executed elements lookup using different selector types and that failed as well, which means UIAutomator itself does not "see" these controls. I cannot say what makes the dump tool to return different output, because it uses exactly the same API calls that our server is using to build the tree.

**Comment by mstrelex** [comment]
Thanks @mykola-mokhnach, I can't explain this behaviour either... that's why I turned to your expertise.
Will try to investigate how QT builds the UI and perhaps find some clues there.

**Comment by mykola-mokhnach** [comment]
@mstrelex Please let us know if you find any workaround.
Closed as third party issue.

**Comment by bootafoga** [comment]
Hi @mstrelex
I have exactly the same problem.  Have you found any solution?

**Comment by typedefalex** [comment]
you can use `Accessible.name: someName` and then uiautomator2 or appium android could fine this items
https://doc.qt.io/qt-5/qml-qtquick-accessible.html#name-prop
