### ISSUE TITLE
when emulator starts with `-delay-adb` its state shows "offline"

### ISSUE THREAD

**Issue by Abur73** [appium/appium#14773]
## The problem

When Appium tries to open an emulator using `-delay-adb` and such emulator is using a snapshot image to load faster, emulator will launch, but since android's -delay-adb implementation is not yet done to handle snapshots, emulator will stay in state offline, furthermore a Timeout will stop execution on Appium server/client as emulator was never available or in 'device' state.

is there any way to workaround `-delay-adb` usage?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:macOS Catalina 10.15.6
* Node.js version (unless using Appium.app|exe): v12.16.3
* Npm or Yarn package manager: 6.14.4
* Mobile platform/version under test: Android API 28 Tag/ABI: google_apis_playstore/x86
* Android version: 4.0.1
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Details
In order to speed up emulator booting time, an OS snapshot is taken, by setting emulator's Boot up option as Quick boot.
When starting the emulator from AVD manager, `adb devices` command shows emulator is active (device).
When emulator is started using `emulator -avd=Nexus1 &`, also state is set to 'device'
But if one uses command to start emulator `emulator -avd Nexus1 -delay-adb &`, emulator state will stall as 'offline'
If any script is run from appium, emulator will launch, but execution will timeout as emulator's state is offline.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]
```
MACBOOK-PRO:~ $ adb kill-server
MACBOOK-PRO:~ $ adb devices
* daemon not running; starting now at tcp:5037
* daemon started successfully
List of devices attached

MACBOOK-PRO:~ $ emulator -avd Nexus2 &&
> ^C
MACBOOK-PRO:~ $ emulator -avd Nexus2 &
[1] 54789
MACBOOK-PRO:~ $ emulator: WARNING: Ignoring invalid http proxy: Bad format: invalid port number (must be decimal)
checkValid: hw configs not eq

MACBOOK-PRO:~ $ echo emulator: INFO: boot completed
emulator: INFO: boot time 20553 ms
emulator: Increasing screen off timeout, logcat buffer size to 2M.
emulator: Revoking microphone permissions for Google App.

MACBOOK-PRO:~ $ adb devices
List of devices attached
emulator-5554	device

MACBOOK-PRO:~ $ emulator -avd Nexus1 -delay-adb &
[2] 54798
MACBOOK-PRO:~ $ emulator: WARNING: Ignoring invalid http proxy: Bad format: invalid port number (must be decimal)

MACBOOK-PRO:~ $ 
MACBOOK-PRO:~ $ adb devices
List of devices attached
emulator-5554	device
emulator-5556	offline

MACBOOK-PRO:~ $ 
```

**Comment by mykola-mokhnach** [comment]
Have you tried to report the issue to Google?

**Comment by Abur73** [comment]
Hello @mykola-mokhnach, while searching about this issue, I found that `-delay-adb` works only for Cool booted emulators, but not for snapshot (quick boot) as stated onn this linl.
https://androidstudio.googleblog.com/2019/05/emulator-2907-canary.html

**Comment by mykola-mokhnach** [comment]
Added `allowDelayAdb` capability, which being set to `false`, prevents -delay-adb argument to be added to emulator startup args. The change has been published to appium@beta
