### ISSUE TITLE
Running Appium in Windows 10 `uncaughtException: EPERM: operation not permitted appium.log'`

### ISSUE THREAD

**Issue by rido-ramadan** [appium/appium#14770]
## The problem

I try running Appium in Windows with Android Studio cucumber plugin, the process failed and the log should be located in `<projectDir>/appium.log`. However, I got this error:
```
uncaughtException: EPERM: operation not permitted, stat 'C:\Users\<username>\Projects\automation\appium.log'
Error: EPERM: operation not permitted, stat 'C:\Users\<username>\Projects\automation\appium.log'
C:\Users\<username>\AppData\Roaming\npm\node_modules\appium\node_modules\winston\lib\winston\logger.js:307
```

## Environment

* Appium v1.18.2:
* OS: Windows 10 2004
* Node.js v14.13.0 stable (non-LTS)
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Both emulator + device
* Appium CLI

## Link to Appium logs

Unable to provide `appium.log` since file is not permitted to be accessed

**Comment by mykola-mokhnach** [comment]
Have you tried to change the file permissions?

**Comment by rido-ramadan** [comment]
Unable to change permission, since the file access somehow has "UNKNOWN PERMISSION"
I am using the only administrator account in my laptop, and after the restart/shut down, the file missing. It's just that I tried to change the permission from Safe Mode, since it is missing, I can't change the permission at all.

I tried giving whitelist in Windows Defender to `node.exe` to no avail.

**Comment by mykola-mokhnach** [comment]
I would try to change the permissions of the whole parent folder. Also, it is possible to customise the log file path using appropriate server arguments

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
