### ISSUE TITLE
failed to launch settings activity via am but it worked via monkey

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#14780]
## The problem

```
am start -W -n com.android.settings/com.android.settings.Settings -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000
```

was failed, but like below was succeeded.

```
monkey -p com.android.settings -c android.intent.category.LAUNCHER 1
```

We can fallback to the monkey in a case the `am` failed (for only settings?)
Then, probably we can reduce the waiting time to fallback like 1 sec.

(I forgot when, but we tried monkey before...? we can remain it as a secondary method)

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Please attach the actual failure stack trace and the logcat output. Perhaps, it is just necessary to adjust `am` command line arguments, since monkey also uses stuff similar to `am` under the hood to run its scripts: https://android.googlesource.com/platform/development/+/master/cmds/monkey/src/com/android/commands/monkey/Monkey.java#1049
https://android.googlesource.com/platform/development/+/master/cmds/monkey/src/com/android/commands/monkey/MonkeyActivityEvent.java#51

**Comment by KazuCocoa** [comment]
ah, got it. I hadn't dug the issue well yet.
Let me dig it further.

**Comment by kontownik** [comment]
```10:58:34 remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.dummyapp' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Error executing adbExec. Original error: 'Command '/usr/local/Caskroom/android-sdk/4333796/platform-tools/adb -P 5037 -s FFY5T18615000163 shell am start -W -n com.dummyapp/classes.classes -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability
10:58:34     at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
10:58:34     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:381:37)```

**Comment by KazuCocoa** [comment]
@kontownik 
If your case was the app under test, you can tweak the launching argument with `appWaitForLaunch` and some intent arguments https://appium.io/docs/en/writing-running-appium/caps/#uiautomator-1-2

This issue is for Appum's hardcoded settings app

**Comment by mykola-mokhnach** [comment]
@KazuCocoa is the issue still relevant?

**Comment by KazuCocoa** [comment]
i haven't seen this issue recently.
Let me close this for now.
