### ISSUE TITLE
(React-Native) Unable to find WebView on iOS 14.0.1

### ISSUE THREAD

**Issue by thetin95** [appium/appium#14788]
## The problem

(React-Native) Unable to find WebView on iOS 14.0.1

## Environment

* Appium version (or git revision) that exhibits the issue: V1.18.0
* Desktop OS/version used to run Appium: macOs Catalina Version 10.15.6
* Node.js version (unless using Appium.app|exe): v12.18.4
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS 14.0.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium Desktop

## Details

Automated test tool is Robot Framework

## Link to Appium logs

https://gist.github.com/thetin95/c1020aa63e5d32746c631cf0032ca596

Anyone has any suggestion?
Thanks in advance!

**Comment by mykola-mokhnach** [comment]
Possible duplicate of https://github.com/appium/appium/issues/14760

**Comment by mykola-mokhnach** [comment]
Possible duplicate of https://github.com/appium/appium/issues/14760

**Comment by thetin95** [comment]
@mykola-mokhnach My app is developed with react native.
thanks for your advice.

**Comment by mykola-mokhnach** [comment]
Simply try if the solutions from the issue above work for you

**Comment by thetin95** [comment]
It doesn't work for me.

**Comment by mykola-mokhnach** [comment]
Please describe in details what did you try and what did not work

**Comment by thetin95** [comment]
@mykola-mokhnach https://github.com/google/ios-webkit-debug-proxy

**Comment by mykola-mokhnach** [comment]
![Fry](https://imgflip.com/s/meme/Futurama-Fry.jpg)

**Comment by mykola-mokhnach** [comment]
Closed because of no response
