### ISSUE TITLE
[Error: iproxy exited with code '234'] 

### ISSUE THREAD

**Issue by reignsabhi** [appium/appium#14782]
Since last week i have started seeing this issue  
an unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: iproxy exited with code '234'

Xcode : 10.1
Appium : 1.13.0
iOS device : 12.1

PS : it was working fine until last week and once system got restarted and i have started seeing this issue. 
Can any one help on this. 
I tried below : 
Uninstall & install appium 
Uninstall & install webdriver agent and configure
Update carthage 

Still not able to solve the issue. Any lead will be super helpful. 
Thanks,

**Comment by mykola-mokhnach** [comment]
Please use the most recent server version. We don't provide patches to older releases

**Comment by reignsabhi** [comment]
Hi , Thanks for the info . what could be the reason behind this error?

**Comment by mykola-mokhnach** [comment]
No idea. iproxy binary itself is a third party component. Consider asking at iproxy's issues tracker. Or check its source code.

Closed as third party issue

**Comment by reignsabhi** [comment]
Okay thanks i am upgrading my appium and xcode  will update how it goes. thanks for your help

**Comment by jagsme** [comment]
Same here as well. trying for a workaround for reset app issue https://github.com/appium/appium/issues/13421

failure appium logs 

2020-10-05 22:42:24:866 [XCUITest] Killing running processes 'xcodebuild.*XXXXXX, iproxy 8107' for the device XXXXX...
2020-10-05 22:42:24:890 [XCUITest] 'pgrep -nif xcodebuild.*XXXXX' didn't detect any matching processes. Return code: 1
2020-10-05 22:42:24:916 [XCUITest] 'pgrep -nif iproxy 8107' didn't detect any matching processes. Return code: 1
2020-10-05 22:42:24:916 [XCUITest] Starting iproxy to forward traffic from local port 8107 to device port 8100 over USB for the device XXXXX
2020-10-05 22:42:24:928 [XCUITest] iproxy exited with code '234'

**Comment by reignsabhi** [comment]
@mykola-mokhnach : i Hv upgraded my system now facing below issue : 

 An unknown server-side error occurred while processing the command. Original error: Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: 'bundleId' desired capability not provided Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 138.66 seconds

i tried to remove wda from device and reboot it . Still the same. can you please let me know what could be other solution?

**Comment by KazuCocoa** [comment]
Did you ensure your WDA was able to be installed to the device with Xcode as https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md ? Removing caches like DerivedData also may help.

**Comment by reignsabhi** [comment]
@KazuCocoa @mykola-mokhnach  : Thanks for your guidance. i was able to resolve the issue.. 
I newly installed the xcode appium and WDA . . 
For others who phases same issue please try to upgrade the system for all above errors. new servers may resolve this issues Thanks .

**Comment by jagsme** [comment]
@reignsabhi could you tell what version you upgraded to? xcode and appium versions please

**Comment by reignsabhi** [comment]
@jagsme  below is my system configuration 
ios version 10.15.4 (Catalina)
xcode 11.3.1
appium 1.16
I hope it works for you . good luck

**Comment by jagsme** [comment]
This error is gone for me as well. Just updated appium version to 1.15.1
But I am still struggling with  #13421 , need to look for a workaround here as well

**Comment by Ranadheer88** [comment]
jagsme- I am getting the error on appium server 1.13. When i checked the appium version its 1.21. I am getting same error. please help
