### ISSUE TITLE
Scroll view(or Table view) jumps up after scroll/swiping down through half of the scroll view in iOS app.

### ISSUE THREAD

**Issue by ShaharBenAyoon0752** [appium/appium#14790]
## The problem

Scroll view(or Table view) jumps up after scroll/swiping down through half of the scroll view in iOS app.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.2
* Desktop OS/version used to run Appium: MacOS Catalina 10.15.6
* Node.js version (unless using Appium.app|exe): 14.2.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS 14.0.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

This issue only happen when I open the app with appium, when I open the app manually the scroll view works fine.
I used every method such as: driver.swipe(), mobile: swipe, mobile:scroll, TouchActions, etc...
In the appium log there is no indication that something went wrong.

**Comment by mykola-mokhnach** [comment]
These endpoints simply call the corresponding XCTest primitives, so there is not much we could do there from Appium/WDA side. Consider reporting the issue to Apple and/or add more debug logging to your application under test.

**Comment by ShaharBenAyoon0752** [comment]
> These endpoints simply call the corresponding XCTest primitives, so there is not much we could do there from Appium/WDA side. Consider reporting the issue to Apple and/or add more debug logging to your application under test.

I want to make sure that it is an Apple issue. You checked if appium or wda work in the latest version? Maybe apple changed the API or something went wrong in your code? Also l want to know if I am the only one who experiencing this issue or there is others.

**Comment by mykola-mokhnach** [comment]
The API we use for swipe is public: https://developer.apple.com/documentation/xctest/xcuielement/1618668-swipeleft?language=objc, so it's not expected to be changed.

Regarding the WDA code - we have integration tests, that are running on different Xcode versions and these tests pass: https://github.com/appium/WebDriverAgent/tree/master/WebDriverAgentTests/IntegrationTests

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
