### ISSUE TITLE
Xcode 12.0.1 : Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

### ISSUE THREAD

**Issue by rishikhanna1401** [appium/appium#14796]
What I have already tried?

1. I've closely followed 2 tutorials  :   https://github.com/appium/appium/blob/master/docs/en/appium-setup/real-devices-ios.md https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md 
2. wdafile is created with by choosing Team value as actual company name and not (Personal Team )

Environment
* Appium version (or git revision) that exhibits the issue: 1.18.2
* Desktop OS/version used to run Appium: Mac OS + 10.15.6
* Mobile platform/version under test: iPAD  14.0
* Real device or emulator/simulator: Real Device
* Xcode: 12.0.1

Details:
WDA was successfully installed into my connected iPAD but as soon as execution starts it is removed and never gets installed again. 
Before upgrading to xcode 12+ and iOS 14 execution was happening without any issue.
 Below are my set of capabilities that was working for earlier versions:

capabilities.setCapability("platformName", device.getPlatformName());
		capabilities.setCapability("platformVersion", device.getPlatformVersion());
		capabilities.setCapability("noReset", true);
		capabilities.setCapability("bundleId", bundleId);
		capabilities.setCapability("toggleSoftwareKeyboard", true);
		capabilities.setCapability("wdaLocalPort", wdaPort);
		capabilities.setCapability("useNewWDA", true);
		capabilities.setCapability("usePrebuiltWDA", true);
		capabilities.setCapability("newCommandTimeout", 400);
		capabilities.setCapability("autoAcceptAlerts", true);
		capabilities.setCapability("deviceName", device.getName());
		capabilities.setCapability("udid", device.getUdid());
		capabilities.setCapability("xcodeOrgId", "xxxxx");
		capabilities.setCapability("xcodeSigningId", "iPhone Developer");

[appiumlogs.docx](https://github.com/appium/appium/files/5354359/appiumlogs.docx)

**Comment by mykola-mokhnach** [comment]
Please attach the logs as GIST

**Comment by rishikhanna1401** [comment]
@mykola-mokhnach Will below snippet will work?

[simctl] iProxy@00008027:3680 The connection has been closed
[debug] [simctl] BaseDriver Event 'newSessionStarted' logged at 1602237254076 (15:24:14 GMT+0530 (India Standard Time))
[debug] [simctl] W3C Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[debug] [simctl] W3C xcodebuild error message:
[debug] [simctl] W3C . Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[debug] [simctl] W3C     at quitAndUninstall (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:532:15)
[debug] [simctl] W3C     at /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:562:11
[debug] [simctl] W3C     at wrapped (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:35:13)
[debug] [simctl] W3C     at retry (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:18:13)
[debug] [simctl] W3C     at retryInterval (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:45:10)
[debug] [simctl] W3C     at /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:542:7
[debug] [simctl] W3C Destroying socket connection
[simctl] HTTP <-- POST /wd/hub/session 500 9197 ms - 1325
[simctl] HTTP 
org.openqa.selenium.WebDriverException: It is impossible to create a new session because 'createSession' which takes HttpClient, InputStream and long was not found or it is not accessible
Build info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:42:16'
System info: host: 'Somasekhars-MacBook-Pro.local', ip: '2405:201:d001:6043:894c:655e:9cf7:fe8%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.6', java.version: '1.8.0_212'
Driver info: driver.version: IOSDriver
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:182)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:196)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:218)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)

**Comment by mykola-mokhnach** [comment]
Have you tried to build WDA manually via Xcode? What is the actual xcodebuild output there?

**Comment by rishikhanna1401** [comment]
Yes I did. It says build successful..I was able to install WDA through Xcode manually after adding Team and certificate

**Comment by mykola-mokhnach** [comment]
And what is the server output if `showXcodeLog` set to true?

**Comment by rishikhanna1401** [comment]
This is got.


Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
xcodebuild error message:

Command line invocation:
    
"/Users/somasekharmeeniga/Downloads/Xcode 2.app/Contents/Developer/usr/bin/xcodebuild" test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=00008027-001A78DA2E87002E IPHONEOS_DEPLOYMENT_TARGET=14.0 -xcconfig /var/folders/2n/twy_1n9d3vd5l2brbbz_9yzh0000gn/T/202099-12566-q20041.sl11/appium-temp.xcconfig GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO
Build settings from command line:
    COMPILER_INDEX_STORE_ENABLE = NO
    GCC_TREAT_WARNINGS_AS_ERRORS = 0
    IPHONEOS_DEPLOYMENT_TARGET = 14.0
Build settings from configuration file '/var/folders/2n/twy_1n9d3vd5l2brbbz_9yzh0000gn/T/202099-12566-q20041.sl11/appium-temp.xcconfig':
    CODE_SIGN_IDENTITY = iPhone Developer
    DEVELOPMENT_TEAM = 2FF6FTW7JA
2020-10-09 20:01:54.346 xcodebuild[12592:189981]  DTDeviceKit: deviceType from 00008027-001A78DA2E87002E was NULL
2020-10-09 20:01:54.475 xcodebuild[12592:189986]  DTDeviceKit: deviceType from 00008027-001A78DA2E87002E was NULL
2020-10-09 20:01:54.475 xcodebuild[12592:189986]  DTDeviceKit: deviceType from 00008027-001A78DA2E87002E was NULL
2020-10-09 20:01:54.755 xcodebuild[12592:189986]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/somasekharmeeniga/Library/Developer/Xcode/DerivedData/WebDriverAgent-aiaejbhejflmruhkhsmeebmhbaia/Logs/Test/Test-WebDriverAgentRunner-2020.10.09_20-01-54-+0530.xcresult/Staging/1_Test/Diagnostics/WebDriverAgentRunner-C7A20C56-24F8-480A-B4DC-5ECD8D3D83E7/WebDriverAgentRunner-009A6774-128F-4925-A9C9-5100B1B88B79/Session-WebDriverAgentRunner-2020-10-09_200154-xI2cJQ.log
2020-10-09 20:01:54.756 xcodebuild[12592:189921] [MT] IDETestOperationsObserverDebug: (6CC4ABA9-2E82-4764-A303-D5332B85F94F) Beginning test session WebDriverAgentRunner-6CC4ABA9-2E82-4764-A303-D5332B85F94F at 2020-10-09 20:01:54.756 with Xcode 12A7300 on target 📱<DVTiOSDevice (0x7fe55ad556f0), Murali’s iPad, iPad, 14.0 (18A373), 00008027-001A78DA2E87002E> {
		deviceSerialNumber:         DLXZ73YAK7M9
		identifier:                 00008027-001A78DA2E87002E
		deviceClass:                iPad
		deviceName:                 Murali’s iPad
		deviceIdentifier:           00008027-001A78DA2E87002E
		productVersion:             14.0
		buildVersion:               18A373
		deviceSoftwareVersion:      14.0 (18A373)
		deviceArchitecture:         arm64e
		deviceTotalCapacity:        54561189888
		deviceAvailableCapacity:    40324190208
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsPaired:             YES
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		isPasscodeLocked:           NO
		deviceType:                 <DVTDeviceType:0x7fe55a0d5cd0 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1,
    2
)
		applications:              (null)
		provisioningProfiles:      (null)
		hasInternalSupport:        NO
		hasWritableSystem:         NO
		isSupportedOS:             YES
		bootArgs:                  (null)
		nextBootArgs:              (null)
		connected:                 YES
		isWirelessEnabled:         NO
		connectionType:            direct
		hostname:                  (null)
		bonjourServiceName:        ec:2c:e2:d1:fb:2d@fe80::ee2c:e2ff:fed1:fb2d._apple-mobdev2._tcp.local.
		activeProxiedDevice:       (null)
		} (14.0 (18A373))
2020-10-09 20:01:54.932 xcodebuild[12592:189921] [MT] IDETestOperationsObserverDebug: (6CC4ABA9-2E82-4764-A303-D5332B85F94F) Finished requesting crash reports. Continuing with testing.
*** If you believe this error represents a bug, please attach the result bundle at /Users/somasekharmeeniga/Library/Developer/Xcode/DerivedData/WebDriverAgent-aiaejbhejflmruhkhsmeebmhbaia/Logs/Test/Test-WebDriverAgentRunner-2020.10.09_20-01-54-+0530.xcresult
2020-10-09 20:01:54.954 xcodebuild[12592:189921] [MT] IDETestOperationsObserverDebug: 0.207 elapsed -- Testing started completed.
2020-10-09 20:01:54.954 xcodebuild[12592:189921] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2020-10-09 20:01:54.954 xcodebuild[12592:189921] [MT] IDETestOperationsObserverDebug: 0.207 sec, +0.207 sec -- end
Test session results, code coverage, and logs:
	/Users/somasekharmeeniga/Library/Developer/Xcode/DerivedData/WebDriverAgent-aiaejbhejflmruhkhsmeebmhbaia/Logs/Test/Test-WebDriverAgentRunner-2020.10.09_20-01-54-+0530.xcresult
Testing failed:
	WebDriverAgentRunner:
		WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. If you believe this error represents a bug, please attach the result bundle at /Users/somasekharmeeniga/Library/Developer/Xcode/DerivedData/WebDriverAgent-aiaejbhejflmruhkhsmeebmhbaia/Logs/Test/Test-WebDriverAgentRunner-2020.10.09_20-01-54-+0530.xcresult. (Underlying Error: The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file. The file doesn’t exist. (Underlying Error: The operation couldn’t be completed. No such file or directory)))
** TEST EXECUTE FAILED **
Testing started. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
Build info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:42:16'
System info: host: 'Somasekhars-MacBook-Pro.local', ip: '2405:201:d001:6043:f05b:c4be:896e:570f%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.6', java.version: '1.8.0_212'
Driver info: driver.version: IOSDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
xcodebuild error message:

Command line invocation:
    
"/Users/somasekharmeeniga/Downloads/Xcode 2.app/Contents/Developer/usr/bin/xcodebuild" test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=00008027-001A78DA2E87002E IPHONEOS_DEPLOYMENT_TARGET=14.0 -xcconfig /var/folders/2n/twy_1n9d3vd5l2brbbz_9yzh0000gn/T/202099-12566-q20041.sl11/appium-temp.xcconfig GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO
Build settings from command line:
    COMPILER_INDEX_STORE_ENABLE = NO
    GCC_TREAT_WARNINGS_AS_ERRORS = 0
    IPHONEOS_DEPLOYMENT_TARGET = 14.0
Build settings from configuration file '/var/folders/2n/twy_1n9d3vd5l2brbbz_9yzh0000gn/T/202099-12566-q20041.sl11/appium-temp.xcconfig':
    CODE_SIGN_IDENTITY = iPhone Developer
    DEVELOPMENT_TEAM = 2FF6FTW7JA
2020-10-09 20:01:54.346 xcodebuild[12592:189981]  DTDeviceKit: deviceType from 00008027-001A78DA2E87002E was NULL
2020-10-09 20:01:54.475 xcodebuild[12592:189986]  DTDeviceKit: deviceType from 00008027-001A78DA2E87002E was NULL
2020-10-09 20:01:54.475 xcodebuild[12592:189986]  DTDeviceKit: deviceType from 00008027-001A78DA2E87002E was NULL
2020-10-09 20:01:54.755 xcodebuild[12592:189986]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/somasekharmeeniga/Library/Developer/Xcode/DerivedData/WebDriverAgent-aiaejbhejflmruhkhsmeebmhbaia/Logs/Test/Test-WebDriverAgentRunner-2020.10.09_20-01-54-+0530.xcresult/Staging/1_Test/Diagnostics/WebDriverAgentRunner-C7A20C56-24F8-480A-B4DC-5ECD8D3D83E7/WebDriverAgentRunner-009A6774-128F-4925-A9C9-5100B1B88B79/Session-WebDriverAgentRunner-2020-10-09_200154-xI2cJQ.log
2020-10-09 20:01:54.756 xcodebuild[12592:189921] [MT] IDETestOperationsObserverDebug: (6CC4ABA9-2E82-4764-A303-D5332B85F94F) Beginning test session WebDriverAgentRunner-6CC4ABA9-2E82-4764-A303-D5332B85F94F at 2020-10-09 20:01:54.756 with Xcode 12A7300 on target 📱<DVTiOSDevice (0x7fe55ad556f0), Murali’s iPad, iPad, 14.0 (18A373), 00008027-001A78DA2E87002E> {
		deviceSerialNumber:         DLXZ73YAK7M9
		identifier:                 00008027-001A78DA2E87002E
		deviceClass:                iPad
		deviceName:                 Murali’s iPad
		deviceIdentifier:           00008027-001A78DA2E87002E
		productVersion:             14.0
		buildVersion:               18A373
		deviceSoftwareVersion:      14.0 (18A373)
		deviceArchitecture:         arm64e
		deviceTotalCapacity:        54561189888
		deviceAvailableCapacity:    40324190208
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsPaired:             YES
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		isPasscodeLocked:           NO
		deviceType:                 <DVTDeviceType:0x7fe55a0d5cd0 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1,
    2
)
		applications:              (null)
		provisioningProfiles:      (null)
		hasInternalSupport:        NO
		hasWritableSystem:         NO
		isSupportedOS:             YES
		bootArgs:                  (null)
		nextBootArgs:              (null)
		connected:                 YES
		isWirelessEnabled:         NO
		connectionType:            direct
		hostname:                  (null)
		bonjourServiceName:        ec:2c:e2:d1:fb:2d@fe80::ee2c:e2ff:fed1:fb2d._apple-mobdev2._tcp.local.
		activeProxiedDevice:       (null)
		} (14.0 (18A373))
2020-10-09 20:01:54.932 xcodebuild[12592:189921] [MT] IDETestOperationsObserverDebug: (6CC4ABA9-2E82-4764-A303-D5332B85F94F) Finished requesting crash reports. Continuing with testing.
*** If you believe this error represents a bug, please attach the result bundle at /Users/somasekharmeeniga/Library/Developer/Xcode/DerivedData/WebDriverAgent-aiaejbhejflmruhkhsmeebmhbaia/Logs/Test/Test-WebDriverAgentRunner-2020.10.09_20-01-54-+0530.xcresult
2020-10-09 20:01:54.954 xcodebuild[12592:189921] [MT] IDETestOperationsObserverDebug: 0.207 elapsed -- Testing started completed.
2020-10-09 20:01:54.954 xcodebuild[12592:189921] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2020-10-09 20:01:54.954 xcodebuild[12592:189921] [MT] IDETestOperationsObserverDebug: 0.207 sec, +0.207 sec -- end
Test session results, code coverage, and logs:
	/Users/somasekharmeeniga/Library/Developer/Xcode/DerivedData/WebDriverAgent-aiaejbhejflmruhkhsmeebmhbaia/Logs/Test/Test-WebDriverAgentRunner-2020.10.09_20-01-54-+0530.xcresult
Testing failed:
	WebDriverAgentRunner:
		WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. If you believe this error represents a bug, please attach the result bundle at /Users/somasekharmeeniga/Library/Developer/Xcode/DerivedData/WebDriverAgent-aiaejbhejflmruhkhsmeebmhbaia/Logs/Test/Test-WebDriverAgentRunner-2020.10.09_20-01-54-+0530.xcresult. (Underlying Error: The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file. The file doesn’t exist. (Underlying Error: The operation couldn’t be completed. No such file or directory)))
** TEST EXECUTE FAILED **
Testing started. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:381:37)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at processImmediate (internal/timers.js:434:9)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:125)
	... 55 more

**Comment by rishikhanna1401** [comment]
Hi @mykola-mokhnach any solution or any other setting that I can try out?
Is the stated environment combination in the question require changes?

**Comment by mykola-mokhnach** [comment]
Unfortunately I don't have any suggestions based on the provided info

**Comment by rishikhanna1401** [comment]
Okay so any other info I can help with? Or can you help me to route this ticket to concerned channel for solutions?

**Comment by KazuCocoa** [comment]
> And what is the server output if showXcodeLog is set to true?

Could you share the full Appium log with `showXcodeLog` as https://gist.github.com/?

**Comment by rishikhanna1401** [comment]
Here is the gist project:
https://gist.github.com/rishikhanna1401/75dfe6eacd1e8602906c15a1656c4c6e

**Comment by KazuCocoa** [comment]
Probably your device was disconnected in xcodebuild
```
[debug] [simctl] WebDriverAgent Killing running processes 'xcodebuild.*00008027-001A78DA2E87002E' for the device 00008027-001A78DA2E87002E...
[debug] [simctl] WebDriverAgent 'pgrep -if xcodebuild.*00008027-001A78DA2E87002E' didn't detect any matching processes. Return code: 1
[debug] [simctl] WebDriverAgent Generating xcode config file for orgId 'xxxxxxxx' and signingId 'iPhone Developer'
[debug] [simctl] WebDriverAgent Writing xcode config file to /var/folders/2n/twy_1n9d3vd5l2brbbz_9yzh0000gn/T/2020912-13762-na1ycw.z44z/appium-temp.xcconfig
[debug] [simctl] WebDriverAgent Using Xcode configuration file: '/var/folders/2n/twy_1n9d3vd5l2brbbz_9yzh0000gn/T/2020912-13762-na1ycw.z44z/appium-temp.xcconfig'
[debug] [simctl] WebDriverAgent Beginning test with command 'xcodebuild test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=00008027-001A78DA2E87002E IPHONEOS_DEPLOYMENT_TARGET=14.0 -xcconfig /var/folders/2n/twy_1n9d3vd5l2brbbz_9yzh0000gn/T/2020912-13762-na1ycw.z44z/appium-temp.xcconfig GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent'
[debug] [simctl] WebDriverAgent Output from xcodebuild will be logged. To change this, use 'showXcodeLog' desired capability
[debug] [simctl] WebDriverAgent Waiting up to 60000ms for WebDriverAgent to start
[debug] [simctl] WD Proxy Matched '/status' to command name 'getStatus'
[debug] [simctl] WD Proxy Proxying [GET /status] to [GET http://127.0.0.1:24199/status] with no body
[simctl] Xcode Command line invocation:
[simctl] Xcode     
[simctl] Xcode "/Users/somasekharmeeniga/Downloads/Xcode 2.app/Contents/Developer/usr/bin/xcodebuild" test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=00008027-001A78DA2E87002E IPHONEOS_DEPLOYMENT_TARGET=14.0 -xcconfig /var/folders/2n/twy_1n9d3vd5l2brbbz_9yzh0000gn/T/2020912-13762-na1ycw.z44z/appium-temp.xcconfig GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO
[simctl] Xcode 
[simctl] Xcode Build settings from command line:
[simctl] Xcode     COMPILER_INDEX_STORE_ENABLE = NO
[simctl] Xcode     GCC_TREAT_WARNINGS_AS_ERRORS = 0
[simctl] Xcode     IPHONEOS_DEPLOYMENT_TARGET = 14.0
[simctl] Xcode 
[simctl] Xcode Build settings from configuration file '/var/folders/2n/twy_1n9d3vd5l2brbbz_9yzh0000gn/T/2020912-13762-na1ycw.z44z/appium-temp.xcconfig':
[simctl] Xcode     CODE_SIGN_IDENTITY = iPhone Developer
[simctl] Xcode     DEVELOPMENT_TEAM = xxxxxxxx
[simctl] Xcode 
[simctl] Xcode 
[debug] [simctl] iProxy@00008027:24199 Connection was refused to port 24199
[simctl] WD Proxy socket hang up
```


Probably `/Users/somasekharmeeniga/Library/Developer/Xcode/DerivedData/WebDriverAgent-aiaejbhejflmruhkhsmeebmhbaia/Logs/Test/Test-WebDriverAgentRunner-2020.10.12_13-21-01-+0530.xcresult/Staging/1_Test/Diagnostics/WebDriverAgentRunner-54E7AC85-BEDB-4D7C-9AE6-8DD7AA398DF2/WebDriverAgentRunner-BDBCDF81-11AF-4388-A92F-B09AD0E84AAB/Session-WebDriverAgentRunner-2020-10-12_132101-iqRhrG.log` has more information for the result of `[debug] [simctl] WebDriverAgent Beginning test with command 'xcodebuild test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=00008027-001A78DA2E87002E IPHONEOS_DEPLOYMENT_TARGET=14.0 -xcconfig /var/folders/2n/twy_1n9d3vd5l2brbbz_9yzh0000gn/T/2020912-13762-na1ycw.z44z/appium-temp.xcconfig GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent'`

**Comment by rishikhanna1401** [comment]
@KazuCocoa No that's not the case. As I mentioned it was working before upgrading to new xcode and iOS versions. Have tried with 2 separate iPAD's its the same issue

**Comment by KazuCocoa** [comment]
What the output of `/Users/somasekharmeeniga/Library/Developer/Xcode/DerivedData/WebDriverAgent-aiaejbhejflmruhkhsmeebmhbaia/Logs/Test/Test-WebDriverAgentRunner-2020.10.12_13-21-01-+0530.xcresult/Staging/1_Test/Diagnostics/WebDriverAgentRunner-54E7AC85-BEDB-4D7C-9AE6-8DD7AA398DF2/WebDriverAgentRunner-BDBCDF81-11AF-4388-A92F-B09AD0E84AAB/Session-WebDriverAgentRunner-2020-10-12_132101-iqRhrG.log`?

**Comment by rishikhanna1401** [comment]
Assertions: System: Failed to install or launch the test runner. If you believe this error represents a bug, please attach the result bundle at /Users/somasekharmeeniga/Library/Developer/Xcode/DerivedData/WebDriverAgent-aiaejbhejflmruhkhsmeebmhbaia/Logs/Test/Test-WebDriverAgentRunner-2020.10.12_13-21-01-+0530.xcresult. (Underlying Error: The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file. The file doesn’t exist. (Underlying Error: The operation couldn’t be completed. No such file or directory))

**Comment by KazuCocoa** [comment]
I'm not sure which path your older Xcodes referred to, but did `/Users/somasekharmeeniga/Library/Developer/Xcode/DerivedData/WebDriverAgent-aiaejbhejflmruhkhsmeebmhbaia/` have proper files?
You used `usePrebuiltWDA`, so Appium called only `xcodebuild test-without-building` (Did not build WDA).
But different Xcode versions could use a different path in DerivedData. It depends on Xcode internal logic. Appium provides `derivedDataPath` for this case to specify the DerivedData path.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
