### ISSUE TITLE
Could not get image stream from MJPEG_SERVER_PORT since  XCode 12

### ISSUE THREAD

**Issue by yusunan** [appium/appium#14795]
## The problem
Could not get image stream from MJPEG_SERVER_PORT since  XCode 12

It's working well with XCode 11 and XCode 10

## Environment

* WDA version :v2.22.2
* MacOS:10.15.6 
* Xcode version:12.0.0

## Details
We had implement a node server to get image stream from MJPEG_SERVER_PORT since XCode 10
But since we update our device to iOS 14 and using XCode 12 to build with  WDA (v2.22.2)
We can't get the image stream now.

We had check some update of WDA and Appium, it seems the socket implement has been changed
Now after build WDA we can get the screenshots broadcast start info :
"Got screenshots broadcast client connection at 127.0.0.1:55782"
But the image stream is not started
Could you offer some Documents or change logs for us to show what has been changed and how to fix this

**Comment by yusunan** [comment]
WDA start logs:

Command line invocation:
    /Users/utf/Downloads/Xcode-beta.app/Contents/Developer/usr/bin/xcodebuild test-without-building -project /Users/utf/Documents/utf/unieap_utf_mobile/unieap-utf/utf/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=00008020-001134A43650003A -derivedDataPath /Users/utf/Documents/utf/unieap_utf_mobile/unieap-utf/xcode/00008020-001134A43650003A USE_PORT=14643 MJPEG_SERVER_PORT=14642

User defaults from command line:
    IDEDerivedDataPathOverride = /Users/utf/Documents/utf/unieap_utf_mobile/unieap-utf/xcode/00008020-001134A43650003A

Build settings from command line:
    MJPEG_SERVER_PORT = 14642
    USE_PORT = 14643

2020-10-09 17:52:43.129 xcodebuild[3622:28149]  DTDeviceKit: deviceType from 00008020-001134A43650003A was NULL
2020-10-09 17:52:43.260 xcodebuild[3622:28143]  DTDeviceKit: deviceType from 00008020-001134A43650003A was NULL
2020-10-09 17:52:43.260 xcodebuild[3622:28143]  DTDeviceKit: deviceType from 00008020-001134A43650003A was NULL
2020-10-09 17:52:43.459 xcodebuild[3622:28265]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/utf/Documents/utf/unieap_utf_mobile/unieap-utf/xcode/00008020-001134A43650003A/Logs/Test/Test-WebDriverAgentRunner-2020.10.09_17-52-43-+0800.xcresult/Staging/1_Test/Diagnostics/WebDriverAgentRunner-759D9A1A-C765-40F9-BC86-E65BBC22D3BE/WebDriverAgentRunner-1BAE5AB7-ADBB-4590-AE09-84798FEA1C16/Session-WebDriverAgentRunner-2020-10-09_175243-fCeSEQ.log
2020-10-09 17:52:43.460 xcodebuild[3622:28087] [MT] IDETestOperationsObserverDebug: (E3B92886-2E6B-4973-A576-6108B48B57AA) Beginning test session WebDriverAgentRunner-E3B92886-2E6B-4973-A576-6108B48B57AA at 2020-10-09 17:52:43.460 with Xcode 12B5018i on target 📱<DVTiOSDevice (0x7fa18caf91d0), “余苏楠”的 iPhone, iPhone, 14.0 (18A373), 00008020-001134A43650003A> {
		deviceSerialNumber:         C39XF1KJKPFP
		identifier:                 00008020-001134A43650003A
		deviceClass:                iPhone
		deviceName:                 “余苏楠”的 iPhone
		deviceIdentifier:           00008020-001134A43650003A
		productVersion:             14.0
		buildVersion:               18A373
		deviceSoftwareVersion:      14.0 (18A373)
		deviceArchitecture:         arm64e
		deviceTotalCapacity:        55566487552
		deviceAvailableCapacity:    1260609536
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsPaired:             YES
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		isPasscodeLocked:           NO
		deviceType:                 <DVTDeviceType:0x7fa18b0c1dd0 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		hasInternalSupport:        NO
		hasWritableSystem:         NO
		isSupportedOS:             YES
		bootArgs:                  (null)
		nextBootArgs:              (null)
		connected:                 YES
		isWirelessEnabled:         NO
		connectionType:            direct
		hostname:                  (null)
		bonjourServiceName:        e0:33:8e:58:05:5f@fe80::e233:8eff:fe58:55f._apple-mobdev2._tcp.local.
		activeProxiedDevice:       (null)
		} (14.0 (18A373))
2020-10-09 17:52:43.575 xcodebuild[3622:28087] [MT] IDETestOperationsObserverDebug: (E3B92886-2E6B-4973-A576-6108B48B57AA) Finished requesting crash reports. Continuing with testing.
2020-10-09 17:52:44.795224+0800 WebDriverAgentRunner-Runner[11480:3969938] Running tests...
Test Suite 'All tests' started at 2020-10-09 17:52:45.199
Test Suite 'WebDriverAgentRunner.xctest' started at 2020-10-09 17:52:45.199
Test Suite 'UITestingUITests' started at 2020-10-09 17:52:45.200
    t =      nans Suite Set Up
2020-10-09 17:52:45.225045+0800 WebDriverAgentRunner-Runner[11480:3969938] [User Defaults] Couldn't write values for keys (
    KeyboardAutocorrection
) in CFPrefsPlistSource<0x28386b800> (Domain: com.apple.Preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
2020-10-09 17:52:45.232905+0800 WebDriverAgentRunner-Runner[11480:3969938] [User Defaults] Couldn't write values for keys (
    KeyboardPrediction
) in CFPrefsPlistSource<0x28386b800> (Domain: com.apple.Preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
2020-10-09 17:52:45.234975+0800 WebDriverAgentRunner-Runner[11480:3969938] [User Defaults] Couldn't write values for keys (
    DidShowGestureKeyboardIntroduction
) in CFPrefsPlistSource<0x28386b800> (Domain: com.apple.Preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.00s Start Test at 2020-10-09 17:52:45.236
    t =     0.00s Set Up
2020-10-09 17:52:45.242817+0800 WebDriverAgentRunner-Runner[11480:3969938] Built at Oct  9 2020 17:51:04
2020-10-09 17:52:45.251432+0800 WebDriverAgentRunner-Runner[11480:3969938] ServerURLHere->http://169.254.209.67:14643<-ServerURLHere
2020-10-09 17:52:45.251729+0800 WebDriverAgentRunner-Runner[11480:3969946] Using singleton test manager
recv failed: Resource temporarily unavailable
2020-10-09 17:52:46.073754+0800 WebDriverAgentRunner-Runner[11480:3969938] Getting the most recent active application (out of 1 total items)
    t =     0.86s Find the Application 'com.apple.springboard'
    t =     0.96s     Requesting snapshot of accessibility hierarchy for app with pid 60

recv failed: Resource temporarily unavailable
recv failed: Resource temporarily unavailable
recv failed: Resource temporarily unavailable

2020-10-09 17:52:46.627815+0800 WebDriverAgentRunner-Runner[11480:3969946] Got screenshots broadcast client connection at 127.0.0.1:55782

**Comment by mykola-mokhnach** [comment]
@electricbubble Do you have any ideas on this issue?

**Comment by electricbubble** [comment]
I've tried it on both the `iPhone X` and the `iPad Pro`, MJPEG-streamer is working.

However, I have encountered an error on `iPhone X` before: when I execute "screenshot", it will cause `WDA` to crash (I can succeed again when I restart `iPhone X`).
> `iPad Pro` works all the time.

Finally, I tried to reset the `Developer` of `iPhone X`, and it worked all the time.
- Settings ➡️ Developer ➡️ `Clear Trusted Computers` && `Clear Experience Cache`

You can try it. I hope it will help you.

**Comment by yusunan** [comment]
@mykola-mokhnach @electricbubble 
Make my issue more clearly:
The MJPEG_SERVER_PORT still working well when I open it form Chrome browser.
But not work in our Node server which is try to read the image files from MJPEG_SERVER_PORT.The server is not starting same images. 
And I had check this commit :
https://github.com/appium/WebDriverAgent/commit/ca16aae3f312fa197e2010ae6b4fedf31e8b2768#diff-1859ff5152beb5e0fa8126d7a75b0b47
It seems we should some some thing to the server to start the server.
Could you offer some example of the send data for us?

**Comment by mykola-mokhnach** [comment]
You must send some data to the server first after the socket connection is established. Even one byte of random data should be enough. Chrome works, because it uses http communication and sends standard headers
