### ISSUE TITLE
ANDROID_HOME not detected while running appium-doctor via command,but it works fine while launching the Appium-desktop v1.18.0.

### ISSUE THREAD

**Issue by hlmichael** [appium/appium#14803]
ANDROID_HOME not detected while running appium-doctor via command,but it works fine while launching the Appium-desktop 
 v1.18.0.

**Comment by KazuCocoa** [comment]
What's the result of `process.env.ANDROID_HOME` via node console on your environment?

**Comment by mykola-mokhnach** [comment]
Closed because of no response
