### ISSUE TITLE
Need Help on android deeplinks returns 500 error 

### ISSUE THREAD

**Issue by mmohankumar2020** [appium/appium#14808]
## The problem

I tried to open the app using saucelab device on the emulator and I did get this error
 An unknown server-side error occurred while processing the command. Original error: Error attempting to start URI. Original error: Error: Starting: Intent { act=android.intent.action.VIEW 

Capabilities:
Appium -1.18.1
Android version - 9.0
Android manifest do support intent type url's

Does work on android studio emulators and on real device. 

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Code To Reproduce Issue [ Good To Have ]

 execute_script('mobile: deepLink', {'url' => 'team://cast/example',
                                    'package' => 'com.example.android.teams'})

**Comment by mykola-mokhnach** [comment]
If the feature works locally and fails in cloud then consider writing to their customer support. Also, it is impossible to advice anything without the server log
