### ISSUE TITLE
WebDriverAgent not launching on Real device hanging on erverURLHere->http://192.168.225.187:8100<-ServerURLHere

### ISSUE THREAD

**Issue by rajarlm007** [appium/appium#14807]
## The problem

WebDriverAgent not launching on Real device hanging on ServerURLHere->http://192.168.225.187:8100<-ServerURLHere

## Environment

* Appium version (or git revision) that exhibits the issue: **v1.18.3**
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: **10.15.6**
* Node.js version (unless using Appium.app|exe): **12.8.1**
* Npm or Yarn package manager:
* Mobile platform/version under test: **iOS 13.2.2**
* Real device or emulator/simulator: **Real iPhone 7 Plus**
* Appium CLI or Appium.app|exe: **both(CLI & Desktop)**

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/rajarlm007/3228a8e7bf93f3ea0f02ed5f334e06c6

## Code To Reproduce Issue [ Good To Have ]

1. I have installed both Appium 1.18.3 and did provisioning profile
2. WebDriverAgent build got succeeded and IntegrationApp got installed
3.  Executed test on my real device: mohan@ITAdmins-MBP appium-webdriveragent % xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=218378ce99a4e31b410897d526cf6d622810fd35' test
4. WebDriverAgent got installed on device, but not launched and it stays on below line:
        WebDriverAgentRunner-Runner[2511:92235] ServerURLHere->http://192.168.225.187:8100<-ServerURLHere
         WebDriverAgentRunner-Runner[2511:92303] Using singleton test manager
5. Test not completing (Succeeded or Failed), just hanging on above step
6. http://192.168.225.187:8100 gives sessionId; null created like below,
               {
  "value" : {
    "error" : "unknown command",
    "message" : "Unhandled endpoint: \/ -- http:\/\/192.168.225.187:8100\/ with parameters {\n    wildcards =     (\n        \"\"\n    );\n}",
    "traceback" : ""
  },
  "sessionId" : null
}

**Comment by mykola-mokhnach** [comment]
WDA is just a web server. One must communicate to it using webdriver protocol in order to run tests.

Please read Appium documentation to know more on the topic or use Appium forum to ask questions.
