### ISSUE TITLE
Appium 1.18.1 still very slow when find_element_by_xpath(//*[@text=..) although the element has been visible and in xml file also

### ISSUE THREAD

**Issue by wangyuanhong2** [appium/appium#14800]
## The problem

Similiar to Appium 1.8.1 is brutally slow on Android 7+ devices   #10869 -- closed (https://github.com/appium/appium/issues/10869),

## Environment

* Appium version (or git revision) that exhibits the issue:  1.18.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: windows10 
* Node.js version (unless using Appium.app|exe): 12.18.3
* Npm or Yarn package manager: NPM
* Mobile platform/version under test:  Android 7.1.2
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe:  Appium desktop

## Details

uiautomator2
something in the logcat file :
QueryController: Could not detect idle state.  Having tried update_settings({"waitForIdleTimeout": 3000}) but doesn't improve

## Link to Appium logs
https://gist.github.com/wangyuanhong2/69b2a7e8ca25462a35aa6421b3074b70

## Code To Reproduce Issue [ Good To Have ]
WebDriverWait(self._driver, 60, 2).until(lambda x: x.find_element_by_xpath("//*[@text='登录' or contains(@text, '欢迎您')]"))

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing we could do from Appium side. UiAutomator framework requires the app under test to be in idle state in order to retrieve its accessibility elements. Consider changing your app code or report the issue to Google.

Closed as third party issue
