### ISSUE TITLE
Problem with install 1.18.2

### ISSUE THREAD

**Issue by pawelstasiak** [appium/appium#14801]
Error log: 

28014 verbose stack Error: appium-windows-driver@1.13.0 install: `node install-npm.js`
28014 verbose stack Exit status 1
28014 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
28014 verbose stack     at EventEmitter.emit (events.js:305:20)
28014 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
28014 verbose stack     at ChildProcess.emit (events.js:305:20)
28014 verbose stack     at maybeClose (internal/child_process.js:1028:16)
28014 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
28015 verbose pkgid appium-windows-driver@1.13.0
28016 verbose cwd 
28017 verbose Darwin 19.4.0
28018 verbose argv "/usr/local/Cellar/node/13.5.0/bin/node" "/usr/local/bin/npm" "-g" "install" "appium@1.18.2"
28019 verbose node v13.5.0
28020 verbose npm  v6.13.4
28021 error code ELIFECYCLE
28022 error errno 1
28023 error appium-windows-driver@1.13.0 install: `node install-npm.js`
28023 error Exit status 1
28024 error Failed at the appium-windows-driver@1.13.0 install script.
28024 error This is probably not a problem with npm. There is likely additional logging output above.

**Comment by mykola-mokhnach** [comment]
Try to update NodeJS to the most recent version

**Comment by pawelstasiak** [comment]
I downgrade to version 12.19.0 and it was working
