### ISSUE TITLE
Angular Form is not working for IOS

### ISSUE THREAD

**Issue by AlbertRodRod** [appium/appium#14811]
## The problem

We are facing an error in our automated tests. This error appears on the login page and all tests are failing.
Our target test application is built on Angular 8.2.3 version and Node.js 10.16.0 version. This application has a login page with two input fields (user and password).
When we use the selenium sendKeys() method to fill these fields two things happen:
- Field is filled, we can see the input value on the input fields
- Angular form doesn't notice that these fields are not empty and an error message appears (this message only appears when this field is empty).

## Environment

* Appium version: 1.17.0
* Desktop OS/version used to run Appium: MAC
* Mobile platform/version under test: IPhone 11 Pro Ios 13.2
* Real device

## Details
We trfied to use javascript executor to change the input vale. Also we tried to use sendKeys character by character.

We tested this manually, and it works perfectly.

In addition, this behaviour is only happening in IOS devices. In Android devices, the field is filled and the form is working properly (no error message appears).

## Link to Appium logs

https://gist.github.com/AlbertRodRod/7efa0d69d26364a61213fd8ecb42c815

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing much that could be done on Appium side there. Consider synthesising the expected input events for your app under test in order to make the framework to notice the input

**Comment by mykola-mokhnach** [comment]
closed as third party issue
