### ISSUE TITLE
how is it possible to run appium javascript code snippet from java

### ISSUE THREAD

**Issue by arhanechka** [appium/appium#14816]
for very specific reason I need to run javascript wd appium push method from java appium framework.
java sample: 
driver.pushFile("sdcard/test.csv", new File("/resources/test.csv"));
jacascript sample:
await driver.pushFileToDevice ('sdcard/test.csv', data);
Is it possible and how?

**Comment by mykola-mokhnach** [comment]
Please use appium forum to ask questions
