### ISSUE TITLE
Appium can't start. Developer mode has been opened. Do you need root permission?

### ISSUE THREAD

**Issue by liuchengxu11** [appium/appium#14814]
[appium-server-logs.txt](https://github.com/appium/appium/files/5395129/appium-server-logs.txt)

An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.kook.im' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: The permission to start 'com.kook.im.ui.login.LoginActivity' activity has been denied.Make sure the activity/package names are correct.

Can you help me with your questions? Thank you

**Comment by mykola-mokhnach** [comment]
Did you read the troubleshooting tutorial above? What exactly did you try from it?

**Comment by liuchengxu11** [comment]
yes

**Comment by liuchengxu11** [comment]
Tried appactivity, no problem

**Comment by mykola-mokhnach** [comment]
Sorry, I don't understand. What is the command line output of `/Users/liuchengxu/Library/Android/sdk/platform-tools/adb -P 5037 -s 54b22c6a shell am start -W -n com.kook.im/com.kook.im.ui.login.LoginActivity -S` ?

**Comment by liuchengxu11** [comment]
![Uploading image.png…]()


Stopping: com.kook.im
Starting: Intent { cmp=com.kook.im/.ui.login.LoginActivity }
java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=com.kook.im/.ui.login.LoginActivity } from null (pid=18512, uid=2000) not exported from uid 10123
	at android.os.Parcel.readException(Parcel.java:1556)
	at android.os.Parcel.readException(Parcel.java:1509)
	at android.app.ActivityManagerProxy.startActivityAndWait(ActivityManagerNative.java:2733)
	at com.android.commands.am.Am.runStart(Am.java:762)
	at com.android.commands.am.Am.onRun(Am.java:305)
	at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
	at com.android.commands.am.Am.main(Am.java:97)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:362)

**Comment by mykola-mokhnach** [comment]
I don't think this issue has anything to do with Appium. Check with your developer regarding which activity should be used to start the app.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
