### ISSUE TITLE
socket hang up - Connection was refused to port 8100  during IOS automation on real device

### ISSUE THREAD

**Issue by DPAK-IOS** [appium/appium#14813]
Output from xcodebuild will only be logged if any errors are present there. To change this, use 'showXcodeLog' desired capability
[WebDriverAgent] Waiting up to 60000ms for WebDriverAgent to start
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[iProxy@aac14ab4:8100] Connection was refused to port 8100
[WD Proxy] socket hang up
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[iProxy@aac14ab4:8100] Connection was refused to port 8100
[WD Proxy] socket hang up
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[iProxy@aac14ab4:8100] Connection was refused to port 8100
[WD Proxy] socket hang up
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[iProxy@aac14ab4:8100] Connection was refused to port 8100
[WD Proxy] socket hang up
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[iProxy@aac14ab4:8100] Connection was refused to port 8100
[WD Proxy] socket hang up
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[iProxy@aac14ab4:8100] Connection was refused to port 8100
[WD Proxy] socket hang up

**Comment by DPAK-IOS** [comment]
@mykola-mokhnach  please help me in this. I am unable to run my automation in IOS devices. Thanks

**Comment by DPAK-IOS** [comment]
Here is the error log 

FAILED CONFIGURATION: @BeforeSuite setupAppium
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
xcodebuild error message:

2020-10-16 22:10:57.447 xcodebuild[31204:282050] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder “WebDriverAgentRunner_iphoneos14.0-arm64.xctestrun” doesn’t exist." UserInfo={NSFilePath=/Users/d0p03b9/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoapcdpp/Build/Products/WebDriverAgentRunner_iphoneos14.0-arm64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7fe1e44144b0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
** TEST BUILD FAILED **
2020-10-16 22:10:57.461 xcodebuild[31204:282053]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/d0p03b9/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrbbkniqrpcdpp/Logs/Test/Test-WebDriverAgentRunner-2020.10.16_22-10-55-+0530.xcresult/Staging/2_Test/Diagnostics/WebDriverAgentRunner-103F1BC8-22C3-4C3C-B97B-8D2E2E1FD645/WebDriverAgentRunner-290925-7EC6-4E5-A13A-3D306F8E/Session-WebDriverAgentRunner-2020-10-16_221057-vjhUJ3.log

**Comment by mykola-mokhnach** [comment]
Please provide the full server log along with Xcodebuild log. Have you tried to build WDA manually from Xcode as described in https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md? Do you you the most recent server version?

**Comment by DPAK-IOS** [comment]
@mykola-mokhnach  I tried with manual flow through xcode , but getting error 

'RoutingHTTPServer/GCDAsyncSocket.h' file not found


Appium version - v1.17.1-1
code - latest version - Version 12.0.1 (12A7300)

**Comment by mykola-mokhnach** [comment]
> v1.17.1-1

is not compatible to Xcode 12. You must use the most recent sources. 

> 'RoutingHTTPServer/GCDAsyncSocket.h' file not found

Means that carthage was not able to build the dependencies

**Comment by DPAK-IOS** [comment]
@mykola-mokhnach   Now i installed appium thorugh npm install -g appium

And manually tried in XCODE. In xcode build successes .

Now when i run my automation WDA and app is getting installed in real device but getting timed out after some time 


`[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[debug] [WD Proxy] Got response with status 200: {"value":{"message":"WebDriverAgent is ready to accept commands","state":"success","os":{"testmanagerdVersion":28,"name":"iOS","sdkVersion":"14.0","version":"14.0.1"},"ios":{"ip":"192.168.0.140"},"ready":true,"build":{"upgradedAt":"1602924300036","time":"Oct 17 2020 14:20:49","productBundleIdentifier":"com.facebook.WebDriverAgentRunner"}},"sessionId":null}
[debug] [WebDriverAgent] WebDriverAgent information:
[debug] [WebDriverAgent] {
[debug] [WebDriverAgent]   "message": "WebDriverAgent is ready to accept commands",
[debug] [WebDriverAgent]   "state": "success",
[debug] [WebDriverAgent]   "os": {
[debug] [WebDriverAgent]     "testmanagerdVersion": 28,
[debug] [WebDriverAgent]     "name": "iOS",
[debug] [WebDriverAgent]     "sdkVersion": "14.0",
[debug] [WebDriverAgent]     "version": "14.0.1"
[debug] [WebDriverAgent]   },
[debug] [WebDriverAgent]   "ios": {
[debug] [WebDriverAgent]     "ip": "192.168.0.140"
[debug] [WebDriverAgent]   },
[debug] [WebDriverAgent]   "ready": true,
[debug] [WebDriverAgent]   "build": {
[debug] [WebDriverAgent]     "upgradedAt": "1602924300036",
[debug] [WebDriverAgent]     "time": "Oct 17 2020 14:20:49",
[debug] [WebDriverAgent]     **"productBundleIdentifier": "com.facebook.WebDriverAgentRunner"**
[debug] [WebDriverAgent]   }
[debug] [WebDriverAgent] }
[debug] [WebDriverAgent] WebDriverAgent successfully started after 7807ms
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1602925007948 (14:26:47 GMT+0530 (India Standard Time))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.wal.app","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[WD Proxy] Error: timeout of 240000ms exceeded
[WD Proxy]     at createError (/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/node_modules/appium-base-driver/node_modules/axios/lib/core/createError.js:16:15)
[WD Proxy]     at RedirectableRequest.handleRequestTimeout (/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/node_modules/appium-base-driver/node_modules/axios/lib/adapters/http.js:264:16)
[WD Proxy]     at Object.onceWrapper (events.js:286:20)
[WD Proxy]     at RedirectableRequest.emit (events.js:198:13)
[WD Proxy]     at Timeout._onTimeout (/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/node_modules/follow-redirects/index.js:166:13)
[WD Proxy]     at ontimeout (timers.js:436:11)
[WD Proxy]     at tryOnTimeout (timers.js:300:5)
[WD Proxy]     at listOnTimeout (timers.js:263:5)
[WD Proxy]     at Timer.processTimers (timers.js:223:10)
[debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded). Retrying...`

**Comment by DPAK-IOS** [comment]
[debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded). Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1602925248969 (14:30:48 GMT+0530 (India Standard Time))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.wal.app","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[WD Proxy] Got response with status 500: {"value":{"error":"session not created","message":"Failed to launch com.wal.app application","traceback":""},"sessionId":null}
[debug] [W3C] Matched W3C error code 'session not created' to SessionNotCreatedError
[debug] [XCUITest] Failed to create WDA session (A new session could not be created. Details: Failed to launch com.wal.app application). Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1602925441908 (14:34:01 GMT+0530 (India Standard Time))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.wal.app","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[HTTP] <-- POST /wd/hub/session - - ms - -
[HTTP] 
[WD Proxy] Got response with status 500: {"value":{"error":"session not created","message":"Failed to launch com.wal.app application","traceback":""},"sessionId":null}
[debug] [W3C] Matched W3C error code 'session not created' to SessionNotCreatedError
[debug] [XCUITest] Failed to create WDA session (A new session could not be created. Details: Failed to launch com.wal.app application). Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1602925629352 (14:37:09 GMT+0530 (India Standard Time))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.wal.app","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}

**Comment by DPAK-IOS** [comment]
capabilities = new DesiredCapabilities();
    capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone");
    capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
   capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "14.0.1");
    capabilities.setCapability(MobileCapabilityType.APP, "xxxxxxxxxxxx/app_2.93.58_Signed.ipa");
    capabilities.setCapability(MobileCapabilityType.NO_RESET, true);
    capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");
    capabilities.setCapability("useNewWDA", false);
    capabilities.setCapability("xcodeOrgId", "XXXXXXXXX");
    capabilities.setCapability("xcodeSigningId", "iPhone Developer");
    capabilities.setCapability(MobileCapabilityType.UDID, "XXXXXX");
    //4
    driver = new IOSDriver<IOSElement>(url, capabilities);
    driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
    System.out.println("done");
    driver.resetApp();

**Comment by mykola-mokhnach** [comment]
> [WD Proxy] Got response with status 500: {"value":{"error":"session not created","message":"Failed to launch com.wal.app application","traceback":""},"sessionId":null}

This is the issue with the application itself and it has nothing to do with the original issue. Please create a new one and provide the necessary details. Also, I think there is a little we could help there, since the original app refuses to start. WDA starts and works properly though.

Closed as resolved.
