### ISSUE TITLE
Unable to check appium-settings app status, because of recent submission records of appium-adb.

### ISSUE THREAD

**Issue by liuchsh01** [appium/appium#14812]
## The problem

Unable to check appium-settings app status, because of recent submission records of appium-adb.
![image](https://user-images.githubusercontent.com/17928825/96266611-6b83b880-0ff9-11eb-98e3-c1505b760f86.png)

## Environment

* Appium version (or git revision) that exhibits the issue:1.18.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: centos7
* Node.js version (unless using Appium.app|exe): v10.17.0
* Npm or Yarn package manager:npm@6.11.3
* Mobile platform/version under test: huawei mate 30 @ android 10
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:io.appium.java-client@3.4.1

## Details

I install appium@1.18.0 on new mechine, but it didn't work during running UI test.
Error occur while appium check the status of appium-settings.
Because the recent submission records of appium-adb.
![image](https://user-images.githubusercontent.com/17928825/96267419-55c2c300-0ffa-11eb-938c-01209c84510c.png)

error cmd: adb -P 5037 -s 192.168.19.45:5555 shell pgrep -f \(\[\[:blank:\]\]\|\^\)io\.appium\.settings\(\[\[:blank:\]\]\|\$\) 
correct code: adb -P 5037 -s 192.168.19.45:5555 shell pgrep -f \^io\.appium\.settings\$
![image](https://user-images.githubusercontent.com/17928825/96267514-7559eb80-0ffa-11eb-8136-60480ad100e6.png)

**Comment by mykola-mokhnach** [comment]
The pattern is correct and is supported by the stock Android firmware. I assume there could a bug in Huawey's customised code related to command line arguments parsing.  We cannot simply provide a pattern like `^io.appium.settings$`, since such pattern would fail to match processes that have other arguments in their command line, for example `screenrecord /sdcard/target.mp4`.

**Comment by liuchsh01** [comment]
Thank a lot.
After upgrading the ADB version from 1.0.32 to 1.0.41, I solved the problem.
