### ISSUE TITLE
Apm 1.18.1 failed  to connect with wda at first time but success at second time while there is one system notification window

### ISSUE THREAD

**Issue by billychen2014** [appium/appium#14827]
## The problem

Apm 1.18.1 failed  to connect with wda at first time but success at second time while there is one system notification window

## Environment

* Appium 1.18.1
* Desktop OS/version used to run Appium: macOS Catalina 10.15.4
* Node.js version :v10.16.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: both CLI and Appium.app
* client: python client 

## Details

what i did :
1. launch app which contain system notification window such as push notification window
2. i found that it blocked at code  driver = webdriver.Remote(server_url, desired_caps) till time out 

3. i did another testing ,i.e.: launch app without push notification window, the code executed very soon

what's strange is that the driver gotten code executed success after the 240000ms(wda default timeout setting)

## Link to Appium logs

https://gist.github.com/billychen2014/8ba77bcd33b75901e025ce099427351a

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing we could do there. Simply make sure there are no modal dialogs on the device screen when WDA is started. Consider reporting the issue to Apple if you think this is a bug

**Comment by billychen2014** [comment]
thanks .  well ,  it looks like i can't stop the modal dialog while app is launching for push notification function . i can  accept it manually as work around temp.
