### ISSUE TITLE
Element is not generating in xml

### ISSUE THREAD

**Issue by gupatil** [appium/appium#14820]
## Element is not generating in xml file for button

The issue is "I am trying to click on the button which present in windows application through automation, but when I inspect that element I am unable to find the locator for that button and its not generating in xml file also".

## Environment

* Appium version (or git revision) that exhibits the issue:  1.15.1
* Last Appium version that did not exhibit the issue (if applicable): 1.15.1
<img width="116" alt="Capture111111111" src="https://user-images.githubusercontent.com/73107674/96434644-1fb45780-1223-11eb-8c86-ee19790573d9.PNG">
<img width="371" alt="Capture11" src="https://user-images.githubusercontent.com/73107674/96435178-41adda00-1223-11eb-9fe8-206d6b481489.PNG">

* Desktop OS/version used to run Appium: Windows 10
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium app

## Details
For the above issue how we can find the solution

**Comment by mykola-mokhnach** [comment]
Please report your issue to Microsoft. Appium is just a proxy there and we have no access to the server source code.
