### ISSUE TITLE
App is getting crashed when two view controllers are there on screen

### ISSUE THREAD

**Issue by uksahoo** [appium/appium#14821]
## The problem

Click on an element in screen 1, the app should navigate to screen 2. In screen 2 I have a pop up along with a loading indicator (Device progress) which executes in parallel. When the screen is getting loaded with these two parallel actions, Appium is not able handle, App is getting crashed.

I tried executing the test both in my physical device and in Saucelabs with real devices. 

## Environment
The  below details I have provide from Saucelabs.
* Appium version (or git revision) that exhibits the issue: 1.18.1
* XCUITestDriver : v3.25.0
* Desktop OS/version used to run Appium: 
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: 12.4
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

https://gist.github.com/uksahoo/d506bb7f6cc14b46e62821bc5055c611#file-saucelabs_appium_iphone_6_real_19-10-2020_02-28-13-txt

I have partially kept the error log.

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing we could on Appium side. Consider fixing your application source code or reporting the issue to Apple. Also, please make sure the logs are revised prior to being shared, sine they contain your secret API keys.

**Comment by uksahoo** [comment]
@mykola-mokhnach Thanks for your response.
I have checked with the Dev team, they are not getting this exception while building the app. I have tested manually also the issue is not there. Further discussing with developers, they told these two view controllers are dynamic and not related to each other putting any wait condition will impact the performance.
Can we capture this exception in Appium as in the device log it shows uncaught exception '**NSInvalidArgumentException',
reason: '-[_UIAlertControllerAlertPresentationController adaptivePresentationController]**. If we can catch the exception we will be able to handle it.
Please suggest any other solution I can tell to the developers to modify the source code.

**Comment by mykola-mokhnach** [comment]
This could be a race condition issues. E.g. automated tests are fast and manual interaction is slower. That is why you cannot reproduce it. 

I would try to check if other people have similar issues first: https://www.google.com/search?q="adaptivePresentationController+unrecognized+selector+sent+to+instance", but as I said, there is nothing that could be done there from Appium side. 

You could also suggest that your developers try to automate the same UI flow using native XCTest, so it would be possible to debug the app directly from Xcode.

**Comment by uksahoo** [comment]
@mykola-mokhnach thanks for the suggestion.
I will work with my developers to reproduce the scenario in XCTest.

**Comment by uksahoo** [comment]
The issue has been resolved now. Issue was with first view controller now I am bypassing that to access the second view controller.
