### ISSUE TITLE
install multiple apks with install-multiple argument (not apks by aab case)

### ISSUE THREAD

**Issue by valeriyo** [appium/appium#14823]
## The problem

our app is using dynamic feature delivery (https://developer.android.com/guide/app-bundle/dynamic-delivery) - meaning, the app consists of multiple APKs (base + dynamic feature modules)

The `adb` command supports the `install-multiple` command for this use-case. It takes a list of APKs to install:

```
       adb install-multiple [-lrtsdpg] file...
         Push this package file to the device and install it.

       · -l: Forward lock application.

       · -r: Replace existing application.

       · -t: Allow test packages.

       · -s: Install application on sdcard.

       · -d: Allow version code downgrade (debuggable packages only).

       · -p: Partial application install.

       · -g: Grant all runtime permissions.
```

Appium, however, seems to support only one APK (http://appium.io/docs/en/commands/device/app/install-app/). Could the `driver.installApp` command be changed to take a list of strings?

Thanks.

**Comment by KazuCocoa** [comment]
If you provide the app under test as `.apks`, appium will use `install-multiple` to install it.
http://appium.io/docs/en/writing-running-appium/android/android-appbundle/

**Comment by valeriyo** [comment]
The suggested approach:

 1. build `app.aab`
 2. use `bundletool` to convert to `app.apks`
 3. hand `app.apks` to appium
 
is just a workaround for the lack of multi APK support.

Since I have to use `bundletool` anyway, I could feed the `--mode=universal` parameter to generate a single `universal.apk` and hand if off to appium.
 
 What this ticket was about is explicit support for multiple APKs, so that `adb install-multiple` could be used with:
 
 ```
    driver.installApp("app.apk", "app2.apk")
 ```
 or
  ```
    driver.installApp("app.apk;app2.apk")
 ```

**Comment by KazuCocoa** [comment]
Thanks for the details.
I thought AppBundle (aab) stuff like https://github.com/KazuCocoa/AppBundleSample , so I suggested you the way before.

Do you have a good example app we can use for testing like https://github.com/KazuCocoa/AppBundleSample ?
I had an experience with the app bundle, so I implemented it. But haven't experienced in your way.

Appium calls https://github.com/appium/appium-adb/blob/6153bb547a473a477dc10a27affa8acc2cc51c97/lib/tools/apks-utils.js#L184 for `.apks`, so we should add a new mobile command https://appium.io/docs/en/commands/mobile-command/ for your case.

**Comment by KazuCocoa** [comment]
ah, so you just want to call only the below command `install-multiple` directly without Appium's logic to handle `.apks` by [`bundletool.jar` from `.aab`](https://developer.android.com/studio/command-line/bundletool#generate_apks) in https://github.com/appium/appium-adb/blob/6153bb547a473a477dc10a27affa8acc2cc51c97/lib/tools/apks-utils.js#L159-L197

```js
const output = await this.adbExec(['install-multiple', ...installArgs, ...apkPathsToInstall], {
      timeout: options.timeout,
      timeoutCapName: options.timeoutCapName,
    });
```

The interface may be like:

```ruby
# local
execute_script('mobile:installMultipleApks', {apks: ['/path/to/apk1.apk', '/path/to/apk2.apk'], options: '-r'})
# over the internet
execute_script('mobile:installMultipleApks', {apks: ['https://appium-host/path/to/apk1.apk', 'https://appium-host/path/to/apk1.apk/path/to/apk2.apk'], options: '-r'})
```

**Comment by mykola-mokhnach** [comment]
Just as a workaround:

One could push the apks to the device under test with Appium and then execute `pm install-multiple` using [mobile: shell](https://github.com/appium/appium-uiautomator2-driver#mobile-shell) extension.

**Comment by KazuCocoa** [comment]
1.64.0 has https://github.com/appium/appium-uiautomator2-driver#mobile-installmultipleapks
(It is available via `appium@beta`)
