### ISSUE TITLE
appium throw socket hang up exception randomly when execute WebDriverWait(..).until(.. find_element_by_id..) not found

### ISSUE THREAD

**Issue by wangyuanhong2** [appium/appium#14830]
The problem
    when execute WebDriverWait(..).until(..find_element_by_id..), if the element is not on the page and could not be found, sometimes appium will throw out socket hang up exception(sometimes it works with TimeoutException)..
  File "d:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "d:\ProgramData\Anaconda3\lib\site-packages\appium\webdriver\webdriver.py", line 281, in find_element
    'value': value})['value']
  File "d:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\ProgramData\Anaconda3\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "d:\ProgramData\Anaconda3\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "d:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
   I checked th logcat file and found after trying to find element by several times,(channel read: POST /wd/hub/session/f6bda459-aed1-42cb-be16-4171c02adad0/element),   
   " channel read: DELETE /wd/hub/session/555c019a-e08a-451f-892c-be3254908e24
     DeleteSession command
     Stopping uiautomator2 io.appium.uiautomator2.http io.appium.uiautomator2.server" 
   
   

Environment
Appium version (or git revision) that exhibits the issue: 1.18.1
Last Appium version that did not exhibit the issue (if applicable):
Desktop OS/version used to run Appium: windows10
Node.js version (unless using Appium.app|exe): 12.18.3
Npm or Yarn package manager: NPM
Mobile platform/version under test: Android 7.1.2
Real device or emulator/simulator: emulator
Appium CLI or Appium.app|exe: Appium desktop
Details

Link to Appium logs
https://gist.github.com/wangyuanhong2/0da80682c017635f74ddb315071da605
Code To Reproduce Issue [ Good To Have ]
 WebDriverWait(self._driver, 5 ,0.5).until(lambda x: x.find_element_by_id("com.huasheng.stock:id/mainTabLayout"))

**Comment by mykola-mokhnach** [comment]
I don'y observe any issues in the attached log. The server receives the DELETE command and is terminated. Then the following socket hung up exception is expected.

**Comment by wangyuanhong2** [comment]
the issue is that there  is no code in the program sending DELETE command, as you can see in the exception call stack, the code is doing find_element_by_xpath

**Comment by mykola-mokhnach** [comment]
It could be it is sent by some other session on this device that was not closed properly before and eventually times out. Make sure you close all sessions properly or start the server in single-session mode using `--session-override` command line argument

**Comment by wangyuanhong2** [comment]
ok， Thanks！ I'll check it and close this issue first. Will reopen it if the error persist after config change
