### ISSUE TITLE
1.18.3 release

### ISSUE THREAD

**Issue by SMillerDev** [appium/appium#14837]
## The problem

Version 1.18.3 is only a tag but not marked as release. Is it supposed to be a release? Or is it like a RC?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.2
* Desktop OS/version used to run Appium: macOS 10.15
* Node.js version (unless using Appium.app|exe): v14.14.0
* Npm or Yarn package manager: 6.14.8
* Mobile platform/version under test: iOS 14.1
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI

**Comment by mykola-mokhnach** [comment]
cc @dpgraham

**Comment by dpgraham** [comment]
I marked it as a release. Did this actually have any effect though? We don't actually publish any assets to GitHub Releases.

**Comment by SMillerDev** [comment]
For brew I tend to think of tags in this situation as pre-release so I wouldn't add the version to brew. And I'd expect more people see it like this.
