### ISSUE TITLE
Stopped io.appium.settings foreground service is not started again on Android if process is already running

### ISSUE THREAD

**Issue by janmekota** [appium/appium#14841]
## The problem

The foreground service of io.appium.settings was stopped by Doze power-saving feature on Android device (its icon was not visible in the status bar).
However, it was never started again by appium-android-driver in pushSettingsApp.
All subsequent broadcasts to io.appium.settings completed with result=0.
E.g.
adb shell am broadcast -a io.appium.settings.wifi --es setstatus disable
Broadcasting: Intent { act=io.appium.settings.wifi flg=0x400000 (has extras) }
Broadcast completed: result=0

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Linux mobile-ats-appium 5.3.0-62-generic #56~18.04.1-Ubuntu SMP Wed Jun 24 16:17:03 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux 
* Node.js version (unless using Appium.app|exe): v10.16.3
* Npm or Yarn package manager:
* Mobile platform/version under test: Android 8.0.0
* Real device or emulator/simulator: Real device Samsung Galaxy SM-A520F
* Appium CLI or Appium.app|exe: Appium CLI 

## Details

It seems that it is not sufficient only to check whether the process is running in helpers.pushSettingsApp
https://github.com/appium/appium-android-driver/blob/81d293bd791a006ddcea878d7a3477cb54f000e7/lib/android-helpers.js#L553-L559
In my case the process was running, but not the foreground service, which is needed for proper working.
So the helpers.pushSettingsApp was prematurely left and the adb.requireRunningSettingsApp() call was never reached to start the service again.
https://github.com/appium/appium-android-driver/blob/81d293bd791a006ddcea878d7a3477cb54f000e7/lib/android-helpers.js#L572

## Link to Appium logs

[GIST](https://gist.github.com/janmekota/93361999ef183f67d9638665b54953d3)

## Code To Reproduce Issue [ Good To Have ]

I can stop the io.appium.settings foreground service e.g. by
adb shell pm clear io.appium.settings

Then all broadcast calls do not work and complete with result=0, e.g.
adb shell am broadcast -a io.appium.settings.wifi --es setstatus disable
Broadcasting: Intent { act=io.appium.settings.wifi flg=0x400000 (has extras) }
Broadcast completed: result=0

If I run appium test in this phase the io.appium.settings foreground service is not started so the broadcast calls do not work in test.

If I start the io.appium.settings foreground service again e.g. by
adb shell am start -n io.appium.settings/.Settings

The broadcast calls work again and complete with result=-1
adb shell am broadcast -a io.appium.settings.wifi --es setstatus disable
Broadcasting: Intent { act=io.appium.settings.wifi flg=0x400000 (has extras) }
Broadcast completed: result=-1

**Comment by mykola-mokhnach** [comment]
> I can stop the io.appium.settings foreground service e.g. by
> adb shell pm clear io.appium.settings

Why should one stop the foreground service? As for as I can see Appium does not do it on its own. And if a user decides to not run the foreground service on the phone then it is his decision. The label there clearly states that some functionality will not be available without this service running.

**Comment by janmekota** [comment]
Hello Mykola,
thanks for your response. I should have described it better.

I used command `adb shell pm clear io.appium.settings` just to simulate the real situation, which happened to me. 
In my real case the foreground service was stopped by system - probably by Doze power-saving features, because originally I forgot to add the service into whitelist (`adb shell dumpsys deviceidle whitelist '+io.appium.settings'`).

So my tests were repeatedly failing due to stopped service and the system was not able to recover itself from this state.

Since there is already a check of running  io.appium.settings in helpers.pushSettingsApp I supposed it could be more robust and also check whether foreground service is running and eventually start it again if needed.

**Comment by mykola-mokhnach** [comment]
This is a valid point, thanks for the explanation. In such case it makes sense to perform the foreground service check for Android 8+. Do you mind creating a PR? We'd be happy to review it.

**Comment by mykola-mokhnach** [comment]
The second possible option would be to just add service presence into settings-related command, so they fail with a better/cleaner error message that allows one to mitigate the cause, since we initially don't know if the service was disabled deliberately.

**Comment by mykola-mokhnach** [comment]
Or maybe we need to add our processes to the whitelist (not only the settings process, but also both server processes)

**Comment by janmekota** [comment]
You are right that the service could be disabled deliberately.
So the second option with better/cleaner error message on failure seems better to me now.
And if you are able to add your processes to the whitelist then it definitely makes the test environment setup easier and more stable.
So I would really welcome such improvement:-)

**Comment by mykola-mokhnach** [comment]
I'll add a possibility to whitelist server packages. You could work on better error messages.

**Comment by mykola-mokhnach** [comment]
Both PRs for packages whitelisting have been published into beta versions of uia2 and espresso drivers
