### ISSUE TITLE
Appium hang when AUT crashed

### ISSUE THREAD

**Issue by baovu2512** [appium/appium#14847]
## The problem

I'm running Appium using Gitlab Runner, everytime AUT crash, I need to go to CI machine to kill the node process because Appium hang there

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.3
* Desktop OS/version used to run Appium: Window 10
* Node.js version (unless using Appium.app|exe): 12.14.0
* Mobile platform/version under test: Huawei Android 9
* Real device or emulator/simulator: Real device

## Link to Appium logs

https://gist.github.com/baovu2512/dfba3cc2d20f15a14e95762a82cf83c4

**Comment by mykola-mokhnach** [comment]
I don't observe any explicit issues in the attached log. The server stopped responding to requests, so it waits 240 seconds for each following request until the timeout happens.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
