### ISSUE TITLE
Appium version for a session cannot be determined when Appium is behind a device cloud proxy

### ISSUE THREAD

**Issue by AlvinStanescu** [appium/appium#14851]
## The problem

The Appium version used for a session cannot be determined in case Appium is hosted by a device cloud, since they do not expose Appium directly, but instead proxy to different versions of Appium based on certain vendor-specific capabilities.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe): 12.0
* Npm or Yarn package manager: any
* Mobile platform/version under test: any
* Real device or emulator/simulator: any
* Appium CLI or Appium.app|exe: CLI, hosted by a cloud device provider

## Details

When using a device cloud that hosts different Appium versions behind a proxy, it's impossible to use the `/status` endpoint to determine the Appium version for your current session, bar specifying it manually.

It would be useful to be able to do this since these providers usually have a standard default Appium version for each OS version. 

The user can obviously still override it though, but it would make handling some edge scenarios a lot easier if there were a way of easily determining the Appium version, e.g. as part of the session capabilities. Right now, the only way to determine the Appium version for a particular session is to fetch the server logs, which is really slow.

The proposed solution would only involve adding the `appiumVersion` capability (with the `APPIUM_VER` constant as the value) to the `GET /session/:session_id` call, which, I believe, would improve edge case handling in the future.

## Link to Appium logs

N/A

## Code To Reproduce Issue [ Good To Have ]

No code needed to reproduce the issue, and it would have to include a private access key to a device cloud that is behind a proxy.

**Comment by mykola-mokhnach** [comment]
The `GET /session/:session_id` endpoint is not a part of W3C protocol. Also, cloud providers could modify requests and responses the way they want, it does not matter what Appium actually has there. Consider requesting your cloud provider to support this feature.

**Comment by AlvinStanescu** [comment]
@mykola-mokhnach The reason for not requesting it to cloud providers is that they would implement this in a custom manner, with different capability names or custom APIs, and I believe it would be much easier to have a uniform way of determining the version, irrespective of whether your tests are configured to run against a local or cloud (from any vendor) server.

**Comment by mykola-mokhnach** [comment]
"Uniform" means the value name and format should be a part of an official protocol spec. Currently W3C protocol does not offer such possibility (or maybe I don't know about it). @KazuCocoa @jlipps Any thoughts on it?

**Comment by jlipps** [comment]
Yes, this is a nonstandard feature that Appium provides for its users' convenience. The correct path forward here is to contact the cloud providers and ask them to support Appium's semantics for this route in their load balancer.
