### ISSUE TITLE
Desktop Linux apps support

### ISSUE THREAD

**Issue by baptx** [appium/appium#14854]
The project says:
`Appium is an open-source, cross-platform test automation tool for native, hybrid, and mobile web and desktop apps. We support simulators (iOS), emulators (Android), and real devices (iOS, Android, Windows, Mac).`

But it would be nice if desktop Linux apps are supported too.
Is there any plan to do it or an alternative tool?

**Comment by baptx** [comment]
@mykola-mokhnach maybe it is better to keep this issue open to give more visibility in case people are interested to contribute?

**Comment by mykola-mokhnach** [comment]
Ok, lets keep it as feature request

**Comment by baptx** [comment]
@mykola-mokhnach if Qt apps are supported, I guess it would be easier to support desktop Linux apps and even alternative mobile operating systems using Qt like SailfishOS (since Qt is a cross-platform framework that is compatible with Windows, Mac and Linux).

**Comment by agouaillard-cosmo** [comment]
@mykola-mokhnach We would be interesting of doing the heavy lifting for some reasonable linux use case (e.g. limited to ubuntu, ...). Can we talk?

**Comment by mykola-mokhnach** [comment]
@agouaillard-cosmo Sure, join our Appium slack channel

**Comment by davudmurtazin** [comment]
Are there any updates on it? Is it possible to run Appium tests on Linux?

**Comment by jlipps** [comment]
Appium runs on Linux, yes.

But there is no "Linux Desktop" driver for Appium such that you could automate Linux Desktop apps using Appium.

**Comment by davudmurtazin** [comment]
@jlipps Thank you! Does it mean that I can execute Appium tests on emulator in docker image that uses Linux?
Maybe you have some kind of examples or guide?

**Comment by ifeeltiredboss** [comment]
https://github.com/fantonglang/appium-linux-driver
I have never used above and I don't know how it works.

**Comment by jlipps** [comment]
> Does it mean that I can execute Appium tests on android emulator in docker image that uses Linux?.

Yes, that is the point of the https://github.com/appium/appium-docker-android project

**Comment by jlipps** [comment]
> https://github.com/fantonglang/appium-linux-driver

woah awesome! nice work @fantonglang!

**Comment by hurufu** [comment]
Hi! I just want to add that there is an established and widely supported Linux GUI testing framework LDTP: https://github.com/ldtp/ldtp2

They are using AT-SPI interface which is implemented by every major UI framework. Appium can just use the same dbus interfaces, map them to Webdriver protocol, and you are all set.

**Comment by Alper-Celik** [comment]
there is https://invent.kde.org/sdk/selenium-webdriver-at-spi too
also at-spi is the standard accessiblity api of linux

**Comment by jlipps** [comment]
@Alper-Celik nice! Looks like someone would need to write an Appium driver to download/start this server and proxy commands to it, to be usable from within Appium 2

**Comment by mykola-mokhnach** [comment]
For now the recommendation would be to use third party linux driver(s)
We are not going to support them as officially as it also puts the additional maintenance burden on us.
