### ISSUE TITLE
getPage return empty on latest master appium 

### ISSUE THREAD

**Issue by bearxc** [appium/appium#14856]
Tried on latest appium server code
 Appium v1.19.0-beta.0 (REV 6ae2834b23fed9755737aa4e63ca278f82d7217a)

iOS : xcode 12.1
simulator : iPhone 8 -14.1

String page = Context.driver.getPageSource();

we caught following empty xml .

<?xml version="1.0" encoding="UTF-8"?><AppiumAUT><XCUIElementTypeApplication type="XCUIElementTypeApplication" name="Test DEV" label="Test DEV" enabled="true" visible="true" x="0" y="0" width="375" height="667">
    <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" visible="false" x="0" y="0" width="375" height="667">
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="375" height="667">
            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="375" height="667">
                <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="375" height="667">
                    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="375" height="20">
                        <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" name="notification_view_message_label" enabled="true" visible="false" x="8" y="0" width="359" height="20"/>
                    </XCUIElementTypeOther>
                </XCUIElementTypeOther>
            </XCUIElementTypeOther>
        </XCUIElementTypeOther>
    </XCUIElementTypeWindow>
</XCUIElementTypeApplication></AppiumAUT>

 xcuitest dump  could get correct info.
        String source = (String) Context.driver.executeScript("mobile: source", ImmutableMap.of("format", "description"));

Note:
 Appium v1.18.3 works fine  on same app/environment .

**Comment by mykola-mokhnach** [comment]
Would it be possible to provide a simulator build of your app to test it locally? You could also send it to my direct email address

**Comment by bearxc** [comment]
sorry, the app need running on custom data which is not possible to public :(

This is initial java code , let me know any other info you need  

       deviceName = configProperties.getDeviceName();
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("platformVersion", platformVersion);
        capabilities.setCapability("deviceName", deviceName);
        app = configProperties.getApp();
        capabilities.setCapability("app", app);
        capabilities.setCapability("newCommandTimeout", commandTimeOut);
        capabilities.setCapability("automationName", "xcuitest");
        capabilities.setCapability("noReset", true);
        capabilities.setCapability("simpleIsVisibleCheck", true);

**Comment by mykola-mokhnach** [comment]
Unfortunately I cannot do much without having the actual application. Everything works as expected on all apps we use for local testing.

If mobile source shows the expected output then I could try to apply the same hack that works there to xml page generation, but you would need to confirm it locally then

**Comment by mykola-mokhnach** [comment]
closed because of no response
