### ISSUE TITLE
iOS 13.6 or 14 activateApp("appname") failed with timeout

### ISSUE THREAD

**Issue by chuklov** [appium/appium#14863]
## The problem

on iOS 13.6 and 14 method activateApp() works for the first time and if you run it again while app is active you will get the following error:

Method threw 'org.openqa.selenium.WebDriverException' exception.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.3
* Last Appium version that did not exhibit the issue (if applicable): 1.17
* Desktop OS/version used to run Appium: 1.18.2
* Node.js version (unless using Appium.app|exe):  v15.0.1
* Mobile platform/version under test:  iOS 13.6 / 14
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: cli 

## Details

An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded

## Link to Appium logs

[HTTP] --> POST /wd/hub/session/f47a056d-02a3-4a07-9c97-dc6e245319d7/appium/device/activate_app
[HTTP] {"bundleId":"com.checkpoint.capsuleprotect"}
[debug] [W3C (f47a056d)] Calling AppiumDriver.activateApp() with args: ["com.checkpoint.capsuleprotect",null,null,null,"f47a056d-02a3-4a07-9c97-dc6e245319d7"]
[debug] [XCUITest] Executing command 'activateApp'
[debug] [WD Proxy] Proxying [POST /wda/apps/launch] to [POST http://127.0.0.1:53285/session/04118263-2BF0-4F3B-A956-FA8F15C50A84/wda/apps/launch] with body: {"bundleId":"com.checkpoint.capsuleprotect"}
[WD Proxy] Error: timeout of 240000ms exceeded
[WD Proxy]     at createError (/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/node_modules/appium-base-driver/node_modules/axios/lib/core/createError.js:16:15)
[WD Proxy]     at RedirectableRequest.handleRequestTimeout (/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/node_modules/appium-base-driver/node_modules/axios/lib/adapters/http.js:264:16)
[WD Proxy]     at Object.onceWrapper (node:events:434:26)
[WD Proxy]     at RedirectableRequest.emit (node:events:327:20)
[WD Proxy]     at ClientRequest.eventHandlers.<computed> (/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/node_modules/follow-redirects/index.js:13:24)
[WD Proxy]     at ClientRequest.emit (node:events:327:20)
[WD Proxy]     at Socket.emitRequestTimeout (node:_http_client:796:9)
[WD Proxy]     at Object.onceWrapper (node:events:433:28)
[WD Proxy]     at Socket.emit (node:events:339:22)
[WD Proxy]     at Socket._onTimeout (node:net:471:8)
[WD Proxy]     at listOnTimeout (node:internal/timers:555:17)
[WD Proxy]     at processTimers (node:internal/timers:498:7)
[debug] [W3C (f47a056d)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded
[debug] [W3C (f47a056d)]     at JWProxy.command (/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:275:13)
[debug] [W3C (f47a056d)]     at runMicrotasks (<anonymous>)
[debug] [W3C (f47a056d)]     at processTicksAndRejections (node:internal/process/task_queues:93:5)
[debug] [W3C (f47a056d)]     at XCUITestDriver.proxyCommand (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:96:12)
[debug] [W3C (f47a056d)]     at XCUITestDriver.mobileLaunchApp (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/app-management.js:60:10)
[debug] [W3C (f47a056d)]     at XCUITestDriver.activateApp (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/app-management.js:88:10)
[HTTP] <-- POST /wd/hub/session/f47a056d-02a3-4a07-9c97-dc6e245319d7/appium/device/activate_app 500 60033 ms - 1136
[HTTP] 

## Code To Reproduce Issue [ Good To Have ]

driver.activateApp("what ever application");

**Comment by mykola-mokhnach** [comment]
240 seconds is the default timeout for a server response. Which means that in the case above the WDA server stopped responding to proxied commands. The cause for this is not visible from the server logs. Perhaps, there are some exceptions/errors in the device/xcodebuild logs

**Comment by mykola-mokhnach** [comment]
closed because of no response

**Comment by SteeveZanzouri** [comment]
hello @chuklov did you find solution please?

**Comment by chuklov** [comment]
Hi @SteeveZanzouri, 
no, unfortunately, I did not find any solution for this issue, and neither Appium nor Apple accepting that there is an issue.
