### ISSUE TITLE
Javascript Alert Not Working In IOS Simulator

### ISSUE THREAD

**Issue by MadhusudanJayasimha** [appium/appium#14862]
## The problem

I'm automating mobile web app using IOS Simulator Mac. The issue I'm facing is control is not switching to Javascript alert to perform action on that.

I have used  
1. driver.switchTo.alert();
2. DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability(“autoAcceptAlerts”, true);

Both the above solutions are not working . The twist here is driver.switchTo.alert(); works for an alert on one page and it doesn't work on another page. I have used explicit wait as well . But its not working. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16 
* Desktop OS/version used to run Appium: MAC

Thanks.

**Comment by mykola-mokhnach** [comment]
Please use the most recent server version. Also, the server log and the page source are needed if it still does not work there

**Comment by mykola-mokhnach** [comment]
Closed because of no response
