### ISSUE TITLE
Appium-WebdriverAgent response incorrect code

### ISSUE THREAD

**Issue by NgoAnhKhoi** [appium/appium#14868]
## The problem
Calling setValue on non-textbox element.
The appium server that using appium-webdriveragent 2.14.2: response status 400
The appium server that using appium-webdriveragent 2.22.2: response status 200

## Environment

* Appium version: 1.18.3
* MacOS: 10.15.5
* Node: 12.18.2
* IOS 14.1 - Simulator
* Appium CLI
* Appium-webdriveragent: 2.22.2

## Details

I locate an non-textbox element. Calling element.setValue("text").
Expected: Appium response status 400 
Actual observe: Appium response status 200

example code:
 ```
 const element = $('.non-textbox');
 element .setValue('test123');
```

Note:
I test this case on 2 environments below.
1. Mac 10.14.6
    Appium 1.18.3
    appium-webdriveragent 2.14.2

2. Mac 10.15.5
    Appium 1.18.3
    appium-webdriveragent 2.22.2

The first environment, the appium response status 400.
The second environment, the appium response status 200.

Please take a look at the attached file.
## Link to Appium logs

Log of appium-webdriveragent 2.14.2 on Mac 10.14.6
<img width="1680" alt="mac10 14 6" src="https://user-images.githubusercontent.com/25658429/98323515-8657b480-201c-11eb-881d-c4cfd738636e.png">

Log of appium-webdriveragent 2.22.2 on Mac 10.15.5
<img width="1383" alt="mac15 5" src="https://user-images.githubusercontent.com/25658429/98323518-88217800-201c-11eb-9600-ab5ca1a8d8d1.png">

**Comment by mykola-mokhnach** [comment]
In the recent WDA releases we've removed keyboard presence, because it was throwing false positives and rely on XCTest there. This means, if XCTest does not have any errors then we don't raise ones as well. Closed as not an issue
