### ISSUE TITLE
Appium not always able to create a session on iOS Simulator

### ISSUE THREAD

**Issue by kroe761** [appium/appium#14860]
## The problem

I am trying to execute Appium tests on an iOS simulator.  Every time I run the test, I receive some variant of this error:

```
[debug] [simctl] WD Proxy Matched '/status' to command name 'getStatus'
[debug] [simctl] WD Proxy Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[simctl] WD Proxy connect ECONNREFUSED 127.0.0.1:8100
```

Sometimes, after a few seconds of getting this message, the test will successfully start ([gist](https://gist.github.com/kroe761/6fd9358ba5fe82e6a016801749e75fe2)).  However, sometimes, the errors will continue for some time before the appium server throws an exception ([gist](https://gist.github.com/kroe761/4e5be36a9cd0fa754cd190eba573ae9b)).  For the two previous gists, the tests were ran one right after the other with no changes between them.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.2
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: MacOS 10.15.7
* Node.js version: 14.12.0
* Npm or Yarn package manager: 6.14.8
* Mobile platform/version under test: iOS / v14.0
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

I am running these tests using the Ruby bindings.  Here are my caps:

```
caps = {
   platformName: :ios,
   deviceName: "iPhone 11", 
   automationName: "XCUITest",
   app: "/path/to/app", 
   sendKeyStrategy: "setValue",
   clearSystemFiles: true
}
```

Before executing the tests, I am running these commands to build my simulator: 

```
xcrun simctl boot "iPhone 11"
xcrun simctl bootstatus "iPhone 11" # Waits for successful boot
open -a Simulator
appium -p 4723 &
```

**Comment by mykola-mokhnach** [comment]
> [simctl] WebDriverAgent xcodebuild exited with code '65' and signal 'null'

Try to enable xcodebuild logging (`showXcodeLog`) and check why it fails with such error.

**Comment by kroe761** [comment]
@mykola-mokhnach See [gist](https://gist.github.com/kroe761/664a3708985d81f59104faad69f8b37a) with that setting enabled

**Comment by mykola-mokhnach** [comment]
> [simctl] Xcode 2020-11-04 07:18:12.215 xcodebuild[18611:292192] [MT] IDETestOperationsObserverDebug: (52558E31-0E7A-4F62-BDEB-7BE74CED3AEF) Initialization failure for UI testing: Timed out waiting for AX loaded notification

This looks like an [XCTest](https://developer.apple.com/forums/thread/656364) issue. There's nothing we could do

**Comment by kroe761** [comment]
OK.  Who should I reach out too?  Is there another repo I should open an issue at?

**Comment by mykola-mokhnach** [comment]
I would try to report the issue to Apple. Unfortunately XCTest sources are not available publicly, so it is not possible to say why the error happens and what is possible to do in order to mitigate it.

**Comment by kroe761** [comment]
Gotcha, thanks.
