### ISSUE TITLE
Failed to create session with iOS 12.2 after update to Appium 18.3

### ISSUE THREAD

**Issue by chuklov** [appium/appium#14879]
I have an issue with running tests on iOS 12.2 after I have updated to Appium server 18.3 and Appium Desktop 18.2
Appium Desktop works fine and can connect.
New project for Appium also works fine.
Connection to iOS 13.6 and 14 also works fine.
Xcode installation of WebDriver works fine.

This is a copy of the issue I have opened here: [https://github.com/AppiumTestDistribution/AppiumTestDistribution/issues/757](url)

since I'm using their distribution to run tests. 

## Environment

* Appium version (or git revision) that exhibits the issue: 18.3
* Last Appium version that did not exhibit the issue (if applicable): 17.1
* Desktop OS/version used to run Appium: MACOS Catalina
* Node.js version (unless using Appium.app|exe):  v15.0.1
* Npm or Yarn package manager:  7.0.3
* Mobile platform/version under test: iOS 12.2
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe:  Appium CLI

## Details

I am able to connect this device to any test, run it over Appium Desktop, XCode web driver builds fine, the only issue in that project to create a session. 

## Link to Appium logs

[<script src="https://gist.github.com/chuklov/881000ad0540f51277d1737a6e559a35.js"></script>](url)

[<script src="https://gist.github.com/chuklov/a165678e9c0ccd39708085f8264fde42.js"></script>](url)

[<script src="https://gist.github.com/chuklov/d3adbe885fa866bb5b6b8df2c2266d32.js"></script>](url)

**Comment by mykola-mokhnach** [comment]
Duplicate of https://github.com/appium/appium/issues/14805

I have no idea why xcodebuild fails there and I don't think anybody except Apple itself has. Consider keeping an older server version to test older iOS versions.

**Comment by chuklov** [comment]
Xcode doesn't failed from itself. It only in this project.

**Comment by chuklov** [comment]
I do not see this problem anywhere else except this project. All the rest works fine and iOS 12.2 could be connected to any other test env. Also if I run the command itself in Terminal it also works fine, no errors no issue. 
Here I'm trying to understand if Appium sends wrong command or ATD project sends wrong command and it fails, on which stage it fails, as it definitely not Xcode issue.

**Comment by KazuCocoa** [comment]
Could you set `showXcodeLog` in your capability to print xcodebuild log on Appium's log?
Your's one did not match as below in your provided log. 

```
[BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[BaseDriver]   showXCODELog
```

**Comment by chuklov** [comment]
Hi @KazuCocoa  Thanks for the suggestion, I can see in the output the following:

not sure if it is relevant and where it comes from: IPHONEOS_DEPLOYMENT_TARGET = 13.0. In Xcode I set it up for iOS12. 

Command line invocation:
    
/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=bd3ccfde1c14ef869656292b0460da522728aedc IPHONEOS_DEPLOYMENT_TARGET=13.0 -xcconfig /var/folders/4_/y_kblsms2q7_z01z3p84gn_cjbs_9f/T/20201011-4044-1d2ztjy.6pik/appium-temp.xcconfig GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO
Build settings from command line:
    COMPILER_INDEX_STORE_ENABLE = NO
    GCC_TREAT_WARNINGS_AS_ERRORS = 0
    IPHONEOS_DEPLOYMENT_TARGET = 13.0
Build settings from configuration file '/var/folders/4_/y_kblsms2q7_z01z3p84gn_cjbs_9f/T/20201011-4044-1d2ztjy.6pik/appium-temp.xcconfig':
    CODE_SIGN_IDENTITY = iPhone Developer
    DEVELOPMENT_TEAM = 2ES97B4EP7
2020-11-11 11:37:51.580 xcodebuild[4065:64103]  DTDeviceKit: deviceType from bd3ccfde1c14ef869656292b0460da522728aedc was NULL
2020-11-11 11:37:51.725 xcodebuild[4065:64206]  DTDeviceKit: deviceType from bd3ccfde1c14ef869656292b0460da522728aedc was NULL
2020-11-11 11:37:51.725 xcodebuild[4065:64206]  DTDeviceKit: deviceType from bd3ccfde1c14ef869656292b0460da522728aedc was NULL
xcodebuild: error: Failed to build project WebDriverAgent with scheme WebDriverAgentRunner.
	Reason: Cannot test target “WebDriverAgentRunner” on “EP006”: EP006’s iOS 12.2 doesn’t match WebDriverAgentRunner’s iOS 13.0 deployment target.. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Mac-mini-2.lan', ip: 'fe80:0:0:0:1006:ad81:c1cc:933f%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '1.8.0_241'
Driver info: driver.version: IOSDriver


<script src="https://gist.github.com/chuklov/fa462035461b251fdb37201939249c90.js"></script>

**Comment by mykola-mokhnach** [comment]
the deployment target is set baed on 

> [debug] [BaseDriver]     "appium:platformVersion": "13",

capability

**Comment by chuklov** [comment]
Thanks a lot for the help. Indeed this option can be ignored and it will make all devices work as expected.
Thanks again.
