### ISSUE TITLE
Need an advice - problem with third part applications if app was installed by appium

### ISSUE THREAD

**Issue by arhanechka** [appium/appium#14876]
Our app has inbuilt audio apps like Deezer, Spotify etc. Manually evetyrhing is ok. In case installing app by appium we have different problems, which are not understandable - in case Deezer we can connect app, but can not play anything (in does not see any track and can not connect to the deezer library); in case of Spotify we can not even connect to it. Maybe you have a suggestion about the causes of such behaviour
[logs.txt](https://github.com/appium/appium/files/5511877/logs.txt)

**Comment by mykola-mokhnach** [comment]
Please fill out the issue template and provide the required info. I don't really see how the described issues might be related to Appium

**Comment by mykola-mokhnach** [comment]
Usually such SDKs have some options that allow to enable extended debugging and see what is missing in the app logs.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
