### ISSUE TITLE
I want to get all the elements of dual screens.

### ISSUE THREAD

**Issue by candialala** [appium/appium#14875]
## The problem

When I attach a dual screen on an Android device, there will be two different activities on the current interface.
I can only get the elements of a particular screen, I want to get all the elements of both screens, what do I do?

## Environment

* Appium 1.8
* Android

**Comment by mykola-mokhnach** [comment]
With Appium 1.8 you cannot do nothing. With the recent version it is possible to set `enableMultiWindows` setting to `true`. Please use Appium forum to ask questions
