### ISSUE TITLE
Getting Null pointer exception when tried to start uiautomatorviewer.bat for inspecting mobile element

### ISSUE THREAD

**Issue by vishnuprakash9845** [appium/appium#14872]
## The problem

Option list from the dropdown are not getting recognizing using appium inspect. So tried to use the uiautomatorviewer.bat for inspecting the elements. When tried to launch the uiautomatorviewer.bat getting the below error. Can anyone help me on this.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.0-2
* Last Appium version that did not exhibit the issue (if applicable): didnt tried this scenario
* Desktop OS/version used to run Appium: Windows 10 [1903 (10.0.18362)]
* Node.js version (unless using Appium.app|exe):  v10.15.3
* Npm or Yarn package manager: na
* Mobile platform/version under test: Android 10
* Real device or emulator/simulator: Real mobile device
* Appium CLI or Appium.app|exe: Appium.exe

## Details

When tried to launch uiautomatorviewer.bat, it was closing with in a fraction of second, so to view the detail error tried to launch uiautomatorviewer.bat through command prompt.

Error screenshot attached

![image](https://user-images.githubusercontent.com/24207575/98440820-0404e880-2121-11eb-8e55-38fbb180f163.png)

**Is there any other tool to inspect the mobile elements which cannot be identified or inspected through appium inspector?**

**Comment by mykola-mokhnach** [comment]
Please report this issue to Google. We don't maintain this utility.
