### ISSUE TITLE
ECONNRESET Seen Intermittently

### ISSUE THREAD

**Issue by DeVon30135** [appium/appium#14870]
## The problem

We are intermittently facing ECONNRESET for quite some time in our device cloud infrastructure and could use some guidance on how to resolve the issue.
`Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: read ECONNRESET`

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.1
* Desktop OS/version used to run Appium: Ubuntu 18.04.1
* Node.js version (unless using Appium.app|exe): 14.11.0
* Npm version: 6.14.8
* Mobile platform/version under test: Android 9
* Real device or emulator/simulator: Real device -  SM-G950U1
* Appium CLI or Appium.app|exe: CLI

## Details

We have recently made several changes to our automation framework to improve stability of appium tests. These tests in particular are running in parallel:
- Devices are connected remotely via ADB connect
- ~4 automation runs are occurring at the same time on the machine
- Each run has a different system port, MJPEG port, and appium server started on different ports. Verified none are overlapping
- No appium server has multiple sessions started with it
- About after every 5 minutes the appium session is terminated, appium apps are uninstalled from the device, and the session is restarted to make sure uiautomator2 remains in a stable state

A single test suite execution for us takes ~4 hours divided across 4 different appium instances in parallel. Out of that test suite we typically see ECONNRESET 1-2 times (as mentioned we reset appium afterward to ensure tests continue). We have verified ADB connect still has a stable connection when it occurs and port forwarding is still active.
We have faced this issue some time now but have found the more frequent causes of it have been eliminated by some changes we've made to our cloud infrastructure. At this point I'm not quite sure how to proceed with narrowing down the cause of this ECONNRESET and resolving it. Any guidance would be greatly appreciated. I've linked my ADB logcat and Appium logs below.

## Link to Appium logs

https://gist.github.com/DeVon30135/61179d183cfccf7f4a0adc046e525ed4

**Comment by mykola-mokhnach** [comment]
This error means that the server stopped responding to Appium, so no further command could be proxied to it. There might be multiple reasons to it, for example when adb connection dies or some internal device services like Doze kill the running server or network issues. Try to check adb logcat logs for the time period when disconnect happens - perhaps there are some hints

**Comment by mykola-mokhnach** [comment]
Closed because of no response
