### ISSUE TITLE
Appium occasionally hangs and fails when calling send_keys on iOS 13

### ISSUE THREAD

**Issue by aakacenoks** [appium/appium#14883]
## The problem

Calling send_keys for `XCUIElementTypeSearchField` hangs and then fails with error `[WD Proxy] [39m Error: timeout of 240000ms exceeded`.
- The issue doesn't happen on iOS 14, only on iOS 13 or older.
- Tried switching cap `sendKeyStrategy` to all possible values, didn't help.
- Tried different Xcode versions (12.2, 12.1.1, 12.1), didn't help.
- Tried different locator strategies (XPath, class chain), didn't help.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.19.0-rc.3
* Last Appium version that did not exhibit the issue (if applicable): v1.18.1
* Desktop OS/version used to run Appium: macOS Catalina (10.15.7)
* Node.js version (unless using Appium.app|exe): v14.13.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS 13
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs
https://gist.github.com/aakacenoks/39e86a37466e21feb52c06b2570ddb50
Error at `2020-11-12 13:54:06:325`

**Comment by mykola-mokhnach** [comment]
`setValue` simply executes the downstream XCTest function, so there is not much we could change there. The only parameter, which can be controlled is `maxTypingFrequency` capability.

**Comment by mykola-mokhnach** [comment]
You could also try to enable device logging and check if there are any explicit errors visible there

**Comment by mykola-mokhnach** [comment]
Closed because of no response
