### ISSUE TITLE
Save the screen shot of the current element to the PNG image file. the screenshot coordinate is wrong

### ISSUE THREAD

**Issue by YueChen-C** [appium/appium#14880]
## The problem
iOS version：14.0
When using this element.screenshot(). Save the screenshot is not the png of the element.
If the element coordinate value is multiplied by two, the return png is what I want.
This is my temporary solution. Is there any other better way? 
https://github.com/YueChen-C/WebDriverAgent/commit/364bbc8821a515bcf5631899962512706361909e

## Environment

* Appium version (or git revision) that exhibits the issue:  18.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
In theory the `screenshotDataForQuality` call should automatically apply a correct scale to the passed `rect`. This is also true for my local simulator tests (version 14.1). @KazuCocoa Are you able to repro the issue on real devices?

**Comment by KazuCocoa** [comment]
I did not have 14.0, but my iPhone SE (1st Gen) - 14.2 worked well with Xcode 12.2. WDA was with current master and 1.18.3.

**Comment by KazuCocoa** [comment]
I also quickly checked with iPhone SE 2nd Gen with 14.1 as same as the above comment. It worked well.

Potentially it is only on particular devices, OS versions or Xcode versions.

**Comment by mykola-mokhnach** [comment]
Thanks @KazuCocoa 
I think we keep it as is for now.I assume are issues of XCTest itself (it does not apply scale properly). So the workaround above is ok if it works. @YueChen-C also note, you could retrieve the scale value (it might be different for different device models) from XCUIScreen instance without hardcoding it.

**Comment by YueChen-C** [comment]
@mykola-mokhnach @KazuCocoa  Thanks for your suggestion. I tried other phones
iPhone 8  14.1 ;
iPhone 6s 13.3.3 ;
iPhone 8 13.6 ; 

IPhone 6S 10.3.3 is abnormal, others are working well. Indeed only some devices are abnormal

**Comment by mykola-mokhnach** [comment]
iOS 10.3 is based on Xcode 9 SDK, which is not supported by WDA anymore (the current master only supports Xcode 10.2+, which corresponding to iOS 12.2). Also, this SDK does not have modern methods for taking screenshots, so it is surprising to me that such old phones still work there.
