### ISSUE TITLE
using matches() function in xpath 

### ISSUE THREAD

**Issue by Nouxx** [appium/appium#14898]
## The problem

Hi,
I'd like to use `matches()` function from xpath, you can find a reference of it [here](https://stackoverflow.com/a/2893899)
but appium returns an error which seems to be cause `by: org.jaxen.UnresolvableException: No Such Function matches`

Is this linked to appium itself?
Thanks!

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.3
* Desktop OS/version used to run Appium: macOS
* Node.js version (unless using Appium.app|exe): 14.5.0
* Npm or Yarn package manager: 6.14.5
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: ?

## Details

I'm sending this xpath to appium : `.//*[@resource-id="com.oxylane.android.cubeinstore.debug:id/text_customer_name" and matches(@text,'Clément','i')]`

It works fine on [xpather](http://xpather.com) with this [input](https://gist.github.com/Nouxx/5eaaead9d399a2932b888df9a3c864b3)

## Link to Appium logs

[gist here](https://gist.github.com/Nouxx/4c5185a7b245147bae950939824a2bf7)

## Code To Reproduce Issue [ Good To Have ]

N/A

**Comment by mykola-mokhnach** [comment]
This function is a part of XPath 2.0 spec and the lib only supports XPath 1.0, so the behaviour is expected

**Comment by Nouxx** [comment]
Hi, thanks for the quick reply

Why not adding support for XPath 2.0 then?

**Comment by mykola-mokhnach** [comment]
Because there are no libs for java under Apache/BSD-like license that support it. Feel free to add it if you find one (or implement the lib yourself)
