### ISSUE TITLE
Launching Flutter apps on iPhones with iOS 14

### ISSUE THREAD

**Issue by ajschwieterman** [appium/appium#14891]
## The problem

I am trying to launch an iOS app that was developed using Flutter on an iPhone with iOS 14.  However, the iPhone is displaying a splash screen saying it is not possible.  See [this](https://github.com/truongsinh/appium-flutter-driver/issues/115#issue-742734048) for reference.  I'm able to launch the Flutter app on an iPhone with iOS 12 and 13, and I'm able to launch an app developed in Xcode 12.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.19.0
* Appium-flutter-driver version (or git revision) that exhibits the issue: v0.0.26-1
* Desktop OS/version used to run Appium: macOS 11.0.1
* Node.js version (unless using Appium.app|exe):v14.13.0
* Npm or Yarn package manager: v6.14.8
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

**Comment by amedvedjev** [comment]
https://github.com/flutter/flutter/issues/60657

**Comment by mykola-mokhnach** [comment]
This issue has nothing to do with Appium. Please report it to an appropriate issue tracker
