### ISSUE TITLE
in webview page,The coordinate value which get by method "element.getCenter().getX()" is not in accordance with the actual situation

### ISSUE THREAD

**Issue by 1158261925** [appium/appium#14892]
## The problem
In the situation of AppiumAutoTest for webview page, I need to tap an element By coordinate using the class of "TouchAction". But the center coordinate value of the webview element which got by method of "h5Element.getCenter().getX()" and "h5Element.getCenter().getY()" is not in accordance with the actual situation.
## Environment

* Appium version (or git revision) that exhibits the issue:
---------appium version is 1.17.1
* Desktop OS/version used to run Appium:
---------mac OS 0.15.6 (19G73)
* Node.js version (unless using Appium.app|exe):
---------node version is v14.5.0
* Npm or Yarn package manager:
---------npm version 6.14.5
* Mobile platform/version under test:
---------Android
* Real device or emulator/simulator:
---------emulator

## Details

The center coordinate value of webview element which I have got by method mentioned above is (224,477),however the real coordinate is (593,1447), so I can not execute the tap successfully.
## Link to Appium logs
appium log address is bellow:
https://gist.github.com/1158261925/33b87e7c1e87835b4ed8ed4072a9430b

## Code To Reproduce Issue [ Good To Have ]
```
......
MobileElement h5Element = driver.findElementByXPath("//td[@class='numeric-keyboard-key' and @data-icon='5']");
System.out.println("coordinate of center X：---------->>>"+h5Element.getCenter().getX());
System.out.println("coordinate of center Y:---------->>>"+h5Element.getCenter().getY());
System.out.println("value of attribute of 'data-key':-------->>>"+h5Element.getAttribute("data-key"));
System.out.println("current context value:--------->>"+driver.getContext());
h5Element.click();//the click method is not effect
Thread.sleep(8000);
TouchAction touch = new TouchAction(driver);
touch.tap(PointOption.point(h5Element.getCenter().getX(),h5Element.getCenter().getY())).release().perform();
......
```

brief appium log：
coordinate of center X：---------->>>224
coordinate of center Y:---------->>>477
value of attribute of 'data-key':-------->>>5
current context value:--------->>WEBVIEW_com.renmai.easymoney
<img width="446" alt="realCoordinate" src="https://user-images.githubusercontent.com/43469217/99362683-c22d2c80-28ee-11eb-8f8e-f385d503ab39.png">

**Comment by mykola-mokhnach** [comment]
This behaviour is expected. Coordinates in web views are calculated relatively to their elements container. And the web view container itself is not necessarily positioned at [0, 0] in the native context, where touch actions are actually executed. You could either calculate native coordinates in your code or try to use the recently added [safari driver](https://github.com/appium/appium-safari-driver) (only available in 1.19-rc4)

Closed as not an issue

**Comment by 1158261925** [comment]
Thank you very much,I have got it!
But I think use native coordinates in the code is  not a good way, later maintenance inconvenient, if change another device, I should calculate the coordinate one by one repeatly. What do you  think?
And my device is Android, can I use safari driver really? My understanding is that safari driver is used for ios device only。
Look forward to your reply!

**Comment by mykola-mokhnach** [comment]
Oh, I though this was iOS. 

In case of Chrome you could try W3C actions interface (if supported by your chromedriver version), so touches are performed in the same context. Otherwise there are not too many choices.
