### ISSUE TITLE
I’m using appium to manipulate the mobile browser, how can I add ‘"add_experimental_option"’ parameter to the browser?

### ISSUE THREAD

**Issue by tianyao1111** [appium/appium#14897]
I’m using appium to manipulate the mobile browser, how can I add ‘"add_experimental_option"’ parameter to the browser.by the way,I have searched the appium forum and there is no relevant answer

**Comment by KazuCocoa** [comment]
Probably do you want to set chrome options? Then, Appium can pass it via `chromeOptions` or `goog:chromeOptions`.
https://appium.io/docs/en/writing-running-appium/caps/
What parameter works depends on the chrome side
