### ISSUE TITLE
Appium create session error after upgrading 1.18.3

### ISSUE THREAD

**Issue by cicerali** [appium/appium#14894]
After upgrading  appium@1.18.3, our tests failed because of create session error.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.3
* Last Appium version that did not exhibit the issue (if applicable): 1.16.0
* Desktop OS/version used to run Appium: macOS Catalina
* Node.js version (unless using Appium.app|exe): 12.18.4
* Npm or Yarn package manager: npm 6.14.8
* Mobile platform/version under test: IOS 14
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

We are upgraded our appium version 1.16.0 to 1.18.3 because of support IOS 14. After trying a few versions we can able to build WebdriverAgent only 1.18.3 succesfully and decide to use it.

Our test bed configuration based on selenium grid and appium nodes to connected to it.
Test request coming from automated jenkins project.

After upgrading this version we have trouble about our tests. Our test project runs lot of appium test sequentally. After first test successfully completed, other test failed do to create session error(IOS 14 and other IOS versions).

After some investigating found `appium-base-driver` package triggers this situation. Our running nodes using appium-base-driver@5.0.2 and faulty appium 1.18.3 node use appium-base-driver@5.8.1.
After try different appium-base-driver versions found last succesfull version for us v5.1.3. After upgrade it to v5.2.0 error starts coming again.

After check commit found: commit 1d350ebb17d6270c085076e1aa4af941b94ab0a6 triggers this situation.
After disable this commit in newer vesions of this package we don't see any error.

Note: If we use appium desktop to connect our devices, there is no problem.

## Link to Appium logs

Commit disabled:
[83e229c5776218742f0b0a148bdd9b5d4a05940b-disable.log](https://github.com/appium/appium/files/5552417/83e229c5776218742f0b0a148bdd9b5d4a05940b-disable.log)

Commit enabled:
[83e229c5776218742f0b0a148bdd9b5d4a05940b-enable.log](https://github.com/appium/appium/files/5552425/83e229c5776218742f0b0a148bdd9b5d4a05940b-enable.log)

**Comment by mykola-mokhnach** [comment]
I agree this PR should be reverted because it actually corrupts the keepAlive logic. Would you mind creating a PR to the base driver, which reverts it?

**Comment by mykola-mokhnach** [comment]
The fix was pushed to beta
