### ISSUE TITLE
Do you guys have a workaround to flag Appium that Action sheets are not ALERTS when AUTO_ACCEPT_ALERTS’ Capability =TRUE?  

### ISSUE THREAD

**Issue by mariushorvat** [appium/appium#14900]
## The problem

I've set DesiredCapabilities for ‘AUTO_ACCEPT_ALERTS’ Capability to TRUE.
It's been working well for OS level alerts.
The problem is that Action sheet it's also considered  alert and the first item on the sheet is tapped to accept the alert. 
Do you guys have a workaround to somehow flag Appium that this Action sheet is not an ALERT?  or do you have any suggestions how to force NOT to click on any elements? Thanks!

## Environment

IOS

## Details

1. set AUTO_ACCEPT_ALERTS’ Capability =TRUE.
2. Action sheet it's also considered alert and the first item on the sheet is tapped to accept the alert.

## Link to Appium logs

N/A

## Code To Reproduce Issue [ Good To Have ]

Do you guys have a workaround to somehow flag Appium that this Action sheet is not an ALERT?

**Comment by mykola-mokhnach** [comment]
This behaviour was there from the very beginning. Although, it is possible to customize button selection algorithm there using `acceptAlertButtonSelector`/`dismissAlertButtonSelector` settings

**Comment by mariushorvat** [comment]
Do you have some examples to share? Some documentation how to do this? Thanks!

**Comment by KazuCocoa** [comment]
It is in https://appium.io/docs/en/advanced-concepts/settings/

**Comment by mariushorvat** [comment]
@KazuCocoa I'm trying to figure out where to use this `**/XCUIElementTypeButton[`label CONTAINS[c] 'accept'`]`

1. I'm setting capabilities.autoAcceptAlerts=true
2. then I use the FindBy Path **CONTAINS[c]**  to all my Action Sheets?	

@ExtendedFindBy(iosClassChain = "**/XCUIElementTypeButton[`label CONTAINS[c] 'DONE'`]")
protected ExtendedWebElement doneBtn;

**Comment by KazuCocoa** [comment]
Did you set the command `"**/XCUIElementTypeButton[label CONTAINS[c] 'DONE']"` via settings API https://appium.io/docs/en/commands/session/settings/update-settings/index.html ?
You can get the page via https://appium.io/docs/en/advanced-concepts/settings/#update-device-settings 's link, too.

You also can set the settings stuff in capabilities as https://appium.io/docs/en/writing-running-appium/caps/#update-settings

**Comment by mykola-mokhnach** [comment]
Closed because of no response
