### ISSUE TITLE
Getting 'stale element reference' when using 'mobile: scroll' by predicateString

### ISSUE THREAD

**Issue by NirBY** [appium/appium#14903]
## The problem

Getting stale element reference when using 'mobile: scroll' script with 'predicateString' key

## Environment

* Appium version (or git revision) that exhibits the issue:v1.19.0
* Last Appium version that did not exhibit the issue (if applicable):v1.18.0
* Desktop OS/version used to run Appium:iMAC
* Node.js version (unless using Appium.app|exe):V12.19.0
* Npm or Yarn package manager:Npm
* Mobile platform/version under test:iPhone 8 - IOS V14.2
* Real device or emulator/simulator:Real Device
* Appium CLI or Appium.app|exe:Appium via Java (AppiumDriverLocalService.buildService(builder)..)

## Link to Appium logs

Log: [appiumServer.log.txt](https://github.com/appium/appium/files/5580163/appiumServer.log.txt)
page source: [20201122073604_404.txt](https://github.com/appium/appium/files/5580172/20201122073604_404.txt)

## Code To Reproduce Issue [ Good To Have ]
            driver.executeScript("mobile: scroll", new HashMap<String, String>() {{
                put("predicateString", country.getPredicateString());
            }});

**Comment by mykola-mokhnach** [comment]
It looks like the frame has been changed for the bounded element

```
Original error: No matches found for Identity Binding from input {(
2020-11-22 19:35:15:104 [W3C (78a78f43)]     StaticText, {{92.0, 414.0}, {195.0, 44.0}}, label: 'Israel'
2020-11-22 19:35:15:104 [W3C (78a78f43)] )}
```

vs
 
```
StaticText, 0x281349180, {{92.0, 427.5}, {195.0, 44.0}}, label: 'Israel'
```

in the page source.

Try to enable binding by index according to what the error message actually recommends

**Comment by NirBY** [comment]
OK, just found it in [mobile: scroll](http://appium.io/docs/en/writing-running-appium/ios/ios-xctest-mobile-gestures/#mobile-scroll):
`
Although, there is one known limitation there: in case it is necessary to perform too many scroll gestures on parent container to reach the necessary child element (tens of them) then the method call may fail.
`

It would have been nice if one could choose the number of swipes in 'mobile: scroll'.. but again, I cannot.

**Comment by mykola-mokhnach** [comment]
IMHO this method looks like an ugly workaround judging by the amount of source code it requires. By default XCTest should be able to automatically scroll to the destination element as soon as any action, like `tap`, is performed on it.

**Comment by NirBY** [comment]
What I don't understand, is why am I getting "stale element reference" from:
`
driver.executeScript("mobile: scroll", new HashMap<String, String>() {{
            put("predicateString", country.getPredicateString());
        }});
`

Also element clearly show on page when swipe finish, and this is why I am also searching for it again once "executeScript" is done.
But the exception thrown from the "executeScript"..

I can do some workaround, something like [this ](https://developers.perfectomobile.com/pages/viewpage.action?pageId=38011305) or [this](http://appium.io/docs/en/writing-running-appium/tutorial/swipe/ios-mobile-element-search/), but it will be nice if you could fix the original one..

I also found that when searching for the last element in list, the IOS UI move the element back down after swiping all the way down, which probably causing for 'stale element reference', because element coordinate has changed..
E.g.
![swipeToElement-output](https://user-images.githubusercontent.com/9214815/99917297-0a49b600-2d18-11eb-9579-a211ee8e736e.gif)

**Comment by mykola-mokhnach** [comment]
You could try appium@beta. I don't have any ideas on how to solve the list "jumping" there. Feel free to push a PR if you do.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
