### ISSUE TITLE
io.appium.uiautomator2.server is crashed in Android OS 5.1.1 simulator. Which results in Error: socket hang up.

### ISSUE THREAD

**Issue by pranay2611** [appium/appium#14902]
## The problem

while running automation
Facing issue with OS5 simulator
io.appium.uiautomator2.server is crashed in Android OS 5.1.1 simulator. Which results in Error: socket hang up.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.19.0 v
* Mobile platform/version under test: Android/5.1.1 - API 22
* Real device or emulator/simulator: simulator

## Details

io.appium.uiautomator2.server is crashing with below error

`--------- beginning of crash 11-20 18:09:23.386 31332-31372/io.appium.uiautomator2.server A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 31372 (nioEventLoopGro) 11-20 18:09:23.658 492-492/? E/memtrack: Couldn't load memtrack module (No such file or directory) 11-20 18:09:23.658 492-492/? E/android.os.Debug: failed to load memtrack module: -2 11-20 18:09:23.824 1549-1811/system_process E/ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ id=25, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ] 11-20 18:09:23.975 1184-20273/? E/audio_hw_generic: Error opening input stream format 1, channel_mask 0010, sample_rate 16000 11-20 18:09:24.055 2485-25300/com.google.android.gms.persistent E/SQLiteLog: (2067) abort at 31 in [INSERT INTO pending_ops(source,tag,requires_charging,target_package,source_version,required_network_type,flex_time,target_class,runtime,retry_strategy,last_runtime,period,task_type,job_id,user_ 11-20 18:09:24.056 2485-25300/com.google.android.gms.persistent E/SQLiteDatabase: Error inserting source=16 tag=Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG requires_charging=0 target_package=com.google.android.gms source_version=200414000 required_network_type=0 flex_time=0 target_class=com.google.android.gms.measurement.PackageMeasurementTaskService runtime=1605875963979 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}} last_runtime=0 period=2000 task_type=0 job_id=-1 user_id=0 android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: pending_ops.tag, pending_ops.target_class, pending_ops.target_package, pending_ops.user_id (code 2067) at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method) at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782) at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788) at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86) at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1471) at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1341) at aoht.a(:com.google.android.gms@200414013@20.04.14 (020700-294335909):76) at aohi.b(:com.google.android.gms@200414013@20.04.14 (020700-294335909):54) at aohi.a(:com.google.android.gms@200414013@20.04.14 (020700-294335909):124) at aoef.run(:com.google.android.gms@200414013@20.04.14 (020700-294335909):16) at sgc.b(:com.google.android.gms@200414013@20.04.14 (020700-294335909):14) at sgc.run(:com.google.android.gms@200414013@20.04.14 (020700-294335909):9) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) at slv.run(:com.google.android.gms@200414013@20.04.14 (020700-294335909):0) at java.lang.Thread.run(Thread.java:818)`

**Comment by mykola-mokhnach** [comment]
UiAutomator2 is unstable on Android5 and this is known. Try to switch to UiAutomator1 as a workaround on this platform.

**Comment by pranay2611** [comment]
Ok, Now i used UiAutomator1 and got error 
`NotYetImplementedError: Method has not yet been implemented` for `AppiumDriver.performActions()`

Raised another issue, below is the link
https://github.com/appium/appium/issues/14907

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
