### ISSUE TITLE
It looks like an Appium Memory leak?

### ISSUE THREAD

**Issue by Pudge-T** [appium/appium#14908]
## The problem

I used appium to test multiple apps in genymotion and xiaomi mobiel.  After the program started running, the memory of node.js kept growing until it reached the limit of node`s memory,then the node.js crashed.

## Environment

* Appium version --> 1.18.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: windows 10
* Node.js version (unless using Appium.app|exe): 14.10.0
* Npm or Yarn package manager: 6.14.8
* Mobile platform/version under test: Android 8.1
* Real device or emulator/simulator: Genymoiton Android 8.1
* Appium CLI or Appium.app|exe: 

## Details

![EECB2F5E-1C4F-4a53-A278-77BAC69B5DD2](https://user-images.githubusercontent.com/46012309/100042460-71fe1f00-2e46-11eb-84dc-68027f5c0404.png)
![D8F9E14F-D20D-48df-A828-B6AFC0C0F2E2](https://user-images.githubusercontent.com/46012309/100042489-8510ef00-2e46-11eb-9e1b-07d98bb56785.png)
![C5B0BCCA-3A8D-4109-8B86-4D102BF59954](https://user-images.githubusercontent.com/46012309/100042495-87734900-2e46-11eb-921c-38cccb33bddd.png)
![65A2C159-CED5-47fb-9B9C-E74AEA80D09D](https://user-images.githubusercontent.com/46012309/100042504-8c37fd00-2e46-11eb-89a3-58b477538bc2.png)
![6AF9A740-43F9-4ed0-92C0-C7A0CAF5E3DB](https://user-images.githubusercontent.com/46012309/100042509-8e9a5700-2e46-11eb-900c-f18cde92d3ca.png)
![2D76AAF5-99CA-4621-A675-4925D0D1943F](https://user-images.githubusercontent.com/46012309/100042513-90641a80-2e46-11eb-8402-305efc8887fa.png)

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

`DesiredCapabilities cap = new DesiredCapabilities();
        cap.setCapability("skipUnlock", true);
        cap.setCapability("dontStopAppOnReset", true); 
        cap.setCapability("noReset", true); 
        cap.setCapability("newCommandTimeout", 60*60);
        cap.setCapability("clearSystemFiles", true);
        cap.setCapability("ignoreUnimportantViews", true); 
        cap.setCapability("disableAndroidWatchers", true); 
        cap.setCapability("skipLogcatCapture", true); 
        cap.setCapability("androidScreenshotPath", "/sdcard/screenshots/"); 
        cap.setCapability("adbExecTimeout", 60*60*1000); 
        cap.setCapability("disableWindowAnimation", true);
        cap.setCapability("systemPort", systemPort); 
        AppiumServiceBuilder builder = new AppiumServiceBuilder();
        builder.withIPAddress(ip);
        builder.usingPort(port);
        //builder.withLogFile(logFile);
        builder.withCapabilities(cap);
        builder.withArgument(GeneralServerFlag.SESSION_OVERRIDE); //3
        builder.withArgument(GeneralServerFlag.LOG_LEVEL,"error");  //5
        builder.withArgument(GeneralServerFlag.LOG_TIMESTAMP);  // 6
        builder.withArgument(GeneralServerFlag.LOCAL_TIMEZONE); //7

**Comment by mykola-mokhnach** [comment]
Please use the most recent server version. We don't provide patches for older server versions.

Closed as duplicate

**Comment by Pudge-T** [comment]
I upgraded appium`s version to 1.19,the problem was solved.
