### ISSUE TITLE
The new appium 1.19.0 UiAutomator2 gestures dont work

### ISSUE THREAD

**Issue by ShaharBenAyoon0752** [appium/appium#14912]
## The problem

I tried to use the new mobile gestures of the UiAutomator2 with the execute_script function , but I encountered the error: "Message: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource"

## Environment

* Appium version (or git revision) that exhibits the issue: 1.19.0
* Desktop OS/version used to run Appium: macOs Catalina 10.15.7 
* Mobile platform/version under test: Android
* Real device or emulator/simulator: lg v30+
* Appium CLI or Appium.app|exe: cli

**Comment by mykola-mokhnach** [comment]
Please provide the server log and an example of the client code

**Comment by ShaharBenAyoon0752** [comment]
[HTTP] {"script":"mobile: scrollGesture","args":[{"left":100,"top":100,"width":200,"height":200,"direction":"down","percent":3}]}
[debug] [W3C (0172cf20)] Calling AppiumDriver.execute() with args: ["mobile: scrollGesture",[{"left":100,"top":100,"width":200,"height":200,"direction":"down","percent":3}],"0172cf20-9719-4eac-8640-21ad85932266"]
[AndroidDriver] Executing native command 'mobile: scrollGesture'
[debug] [WD Proxy] Proxying [POST /appium/gestures/scroll] to [POST http://127.0.0.1:8200/wd/hub/session/1401f3eb-d6b6-4a64-a2a4-6fadadb798a9/appium/gestures/scroll] with body: {"area":{"left":100,"top":100,"width":200,"height":200},"direction":"down","percent":3}
[WD Proxy] Got response with status 404: {"sessionId":null,"value":{"error":"unknown command","message":"The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource","stacktrace":"io.appium.uiautomator2.common.exceptions.UnknownCommandException: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:75)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandler...
[debug] [W3C] Matched W3C error code 'unknown command' to UnknownCommandError
[debug] [W3C (0172cf20)] Encountered internal error running command: io.appium.uiautomator2.common.exceptions.UnknownCommandException: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource
[debug] [W3C (0172cf20)] 	at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:75)
[debug] [W3C (0172cf20)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [W3C (0172cf20)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [W3C (0172cf20)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[debug] [W3C (0172cf20)] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[debug] [W3C (0172cf20)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [W3C (0172cf20)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [W3C (0172cf20)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[debug] [W3C (0172cf20)] 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
[debug] [W3C (0172cf20)] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
[debug] [W3C (0172cf20)] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
[debug] [W3C (0172cf20)] 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
[debug] [W3C (0172cf20)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [W3C (0172cf20)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [W3C (0172cf20)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[debug] [W3C (0172cf20)] 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
[debug] [W3C (0172cf20)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [W3C (0172cf20)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [W3C (0172cf20)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[debug] [W3C (0172cf20)] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
[debug] [W3C (0172cf20)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [W3C (0172cf20)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [W3C (0172cf20)] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
[debug] [W3C (0172cf20)] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
[debug] [W3C (0172cf20)] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
[debug] [W3C (0172cf20)] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:552)
[debug] [W3C (0172cf20)] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466)
[debug] [W3C (0172cf20)] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
[debug] [W3C (0172cf20)] 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
[debug] [W3C (0172cf20)] 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
[debug] [W3C (0172cf20)] 	at java.lang.Thread.run(Thread.java:764)
[debug] [W3C (0172cf20)] 
[HTTP] <-- POST /wd/hub/session/0172cf20-9719-4eac-8640-21ad85932266/execute/sync 404 78 ms - 3529
[HTTP] 
[HTTP] --> POST /wd/hub/session/0172cf20-9719-4eac-8640-21ad85932266/appium/app/close
[HTTP] {}
[debug] [W3C (0172cf20)] Calling AppiumDriver.closeApp() with args: ["0172cf20-9719-4eac-8640-21ad85932266"]
[debug] [ADB] Running '/Users/vitaliakbarov/Library/Android/sdk/platform-tools/adb -P 5037 -s LGH930e4c1feb5 shell am force-stop com.goldtouch.ynet'
[debug] [W3C (0172cf20)] Responding to client with driver.closeApp() result: null
[HTTP] <-- POST /wd/hub/session/0172cf20-9719-4eac-8640-21ad85932266/appium/app/close 200 244 ms - 14
[HTTP] 
[HTTP] --> DELETE /wd/hub/session/0172cf20-9719-4eac-8640-21ad85932266
[HTTP] {}
[debug] [W3C (0172cf20)] Calling AppiumDriver.deleteSession() with args: ["0172cf20-9719-4eac-8640-21ad85932266"]
[debug] [BaseDriver] Event 'quitSessionRequested' logged at 1606237419633 (19:03:39 GMT+0200 (Israel Standard Time))
[Appium] Removing session 0172cf20-9719-4eac-8640-21ad85932266 from our master session list
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[debug] [WD Proxy] Matched '/' to command name 'deleteSession'
[debug] [WD Proxy] Proxying [DELETE /] to [DELETE http://127.0.0.1:8200/wd/hub/session/1401f3eb-d6b6-4a64-a2a4-6fadadb798a9] with no body
[debug] [WD Proxy] Got response with status 200: {"sessionId":"1401f3eb-d6b6-4a64-a2a4-6fadadb798a9","value":null}
[debug] [ADB] Running '/Users/vitaliakbarov/Library/Android/sdk/platform-tools/adb -P 5037 -s LGH930e4c1feb5 shell am force-stop com.goldtouch.ynet'
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8200 
[debug] [ADB] Running '/Users/vitaliakbarov/Library/Android/sdk/platform-tools/adb -P 5037 -s LGH930e4c1feb5 forward --remove tcp:8200'
[debug] [BaseDriver] Event 'quitSessionFinished' logged at 1606237419737 (19:03:39 GMT+0200 (Israel Standard Time))
[debug] [W3C (0172cf20)] Received response: null
[debug] [W3C (0172cf20)] But deleting session, so not returning
[debug] [W3C (0172cf20)] Responding to client with driver.deleteSession() result: null
[debug] [W3C (0172cf20)] Destroying socket connection
[HTTP] <-- DELETE /wd/hub/session/0172cf20-9719-4eac-8640-21ad85932266 200 105 ms - 14
[HTTP] 
[debug] [Instrumentation] .
[debug] [Instrumentation] Time: 22.176
[debug] [Instrumentation] 
[debug] [Instrumentation] OK (1 test)
[debug] [Instrumentation] The process has exited with code 0

**Comment by mykola-mokhnach** [comment]
The endpoint does exist for sure: https://github.com/appium/appium-uiautomator2-server/blob/35fe391641f8ee84705f87c0fb02ac003f7f39ee/app/src/main/java/io/appium/uiautomator2/server/AppiumServlet.java#L154

Please make sure the device under test is running the correct server binary

**Comment by mykola-mokhnach** [comment]
Closed because of no response
