### ISSUE TITLE
appium can not fully parse elements in webview when datas large in xcuitest ios

### ISSUE THREAD

**Issue by leeyc0704** [appium/appium#14916]
## The problem
Use appium desktop inspect tool，the same page and the same location(a webview)，it's a table，when few lines
,it can parse ，in the tool can see every element,it can expand， but when many lines，only can see a webview,unable to expand，why？need modify mobile configuration？

## Environment
* Appium version (or git revision) that exhibits the issue:1.14.1
* Desktop OS/version used to run Appium:1.14.1
* Mobile platform/version under test:ios 10.3.3
* Real device or emulator/simulator:Real device

**Comment by mykola-mokhnach** [comment]
Duplicate of https://github.com/appium/appium/issues/14825
