### ISSUE TITLE
WDA failed while running with Xcode 12.2

### ISSUE THREAD

**Issue by nhunh585** [appium/appium#14917]
I got an error while running WDA with Xcode 12.2.

![image](https://user-images.githubusercontent.com/25640067/100437486-683d1b80-30d3-11eb-8940-6545ad8d74b7.png)

**Environment**:
- macOS Catalina 10.15.4
- iPhone 6s plus, iOS: 12.1.2
- Lastest WDA
- Xcode 12.2

The other devices is okay: iPhone 11 (iOS 14.2), iPhone XS Max (iOS 13.5.1)

**Comment by mykola-mokhnach** [comment]
This looks like an XCTest issue me. Try to report it to Apple

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
