### ISSUE TITLE
Unable to run tests on IOS simulator 14.2

### ISSUE THREAD

**Issue by mcopjan** [appium/appium#14924]
## The problem

I can see WDA successfully deployed into a simulator and opening initial welcome page in Safari, then it fails on:
 
**Encountered internal error running command: Error: Safari cannot open 'http://10.203.48.150:54890/welcome' after 0.453s because of: Error running 'spawn': An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=405):
2020-12-01 10:52:42:585 [W3C] Invalid device state**

## Environment

* Appium version (or git revision) that exhibits the issue: 1.19.1
* Mobile platform/version under test: IOS 14.2
* Real device or emulator/simulator: iPhone 8 simulator
* Xcode 12.2 (12B45b)
* node v12.18.3

## Link to Appium logs

[26C2AEC4-0D69-423F-AE99-DA712C09F6C9_sim_error.log](https://github.com/appium/appium/files/5622057/26C2AEC4-0D69-423F-AE99-DA712C09F6C9_sim_error.log)

**Comment by mykola-mokhnach** [comment]
What is the version of `appium-ios-simulator` component? (`npm list -g appium-ios-simulator`)

**Comment by mcopjan** [comment]
@mykola-mokhnach 
npm list -g appium-ios-simulator
/usr/local/lib
└─┬ appium@1.19.1
  ├─┬ appium-ios-driver@4.8.0
  │ └── appium-ios-simulator@3.26.1 
  ├─┬ appium-xcuitest-driver@3.31.1
  │ ├── appium-ios-simulator@3.26.1  deduped
  │ └─┬ appium-webdriveragent@2.27.2
  │   └── appium-ios-simulator@3.26.1  deduped
  └─┬ appium-youiengine-driver@1.2.7
    └── appium-ios-simulator@3.26.1  dedupe

**Comment by mykola-mokhnach** [comment]
Try appium@beta. The issue must be fixed in appium-ios-simulator@3.26.2

**Comment by mcopjan** [comment]
@mykola-mokhnach brilliant, thanks for your help, works well with Appium v1.20.0-beta.0
