### ISSUE TITLE
TouchAction doesn't work with ViewPager2

### ISSUE THREAD

**Issue by vzenzo** [appium/appium#14921]
## The problem
My develop team has added ViewPager2 to the application, since then TouchAction is not working anymore

## Environment

* Appium 1.18.0
* Android
* Node.js version 12.18.0
* Npm 6.14.5
* Android 10
* Samsung S9

## Details

The devs implemented the ViewPager2 into the app, now UIAutomator 2 UIScrollable is working perfectly, ToucAction is not working, it acts as it scrolled but it didn't. I was talking to the devs but there isn't much they can do.
I have tried TouchAction, AndroidTouchAction and seleniums TouchActions, none of them work.

In a app version before (without ViewPager2) TouchAction works perfectly fine

```
        AndroidTouchAction swipe = new AndroidTouchAction(d);
                if (direction.equals("right")) {
                    int startX = el1.getLocation().getX();
                    int startY = el1.getLocation().getY();
                    int endX = startX + 1000;
                    swipe.longPress(PointOption.point(startX, startY)).waitAction(waitOptions(ofMillis(500))).moveTo(PointOption.point(endX, startY)).release().perform();

                } else if (direction.equals("left")) {
                    int startX = el1.getLocation().getX();
                    int startY = el1.getLocation().getY();
                    int endX = startX - 1000;
                    swipe.longPress(PointOption.point(startX, startY)).waitAction(waitOptions(ofMillis(500))).moveTo(PointOption.point(endX, startY)).release().perform();
                }
```

**Comment by mykola-mokhnach** [comment]
Try W3C actions or `mobile: gesture` helpers (these were introduced since v 1.19.0)

Also, it makes sense to enable touches tracking and extended app debug logs to see what is happening there.

**Comment by vzenzo** [comment]
As I've said, UiAutomator works fine 
```
d.findElement(MobileBy.AndroidUIAutomator(
                            "new UiScrollable(new UiSelector().scrollable(true)).setAsHorizontalList().scrollIntoView(text(\"" + element + "\"));"));

```

The problem here is having separate code for IOS and Android just because  TouchAction doesn't work with ViewPager2.

**Comment by mykola-mokhnach** [comment]
Unfortunately I don't have any more advices. the code user by Touch actions has ton of legacy stuff and nobody really wants to step into it, especially when there is the modern W3C actions alternative. 

I could provide you with a link to the actual sources, so you could try to fix it yourself.

**Comment by amedvedjev** [comment]
@vzenzo did you enabled in developer menu to see touches and check where actually swipe happens? 
also try -> http://appium.io/docs/en/writing-running-appium/tutorial/swipe-tutorial/ -> Element Swipe

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
