### ISSUE TITLE
Appium for ios devices taking longer time to getPageSource for XML page source lines are 2500 lines

### ISSUE THREAD

**Issue by tulasikrishan89** [appium/appium#14925]
## The problem

Appium for ios devices taking longer time to load while getting getPageSource - XML page source lines are 2500 lines

Taking longer time to get response for "/session/{{SESSSION_ID}}/source" when list elements are 100 and above

Required some attribute to fetch elements that are visible in screen only

## Environment

* Appium version 1.18.1 and above are tested
* Also tested latest version
* Tested in both Desktop version and node version
* Mobile platform : ios tested in all os versions
* Real device 

## Details

Appium for ios devices taking longer time to load while getting getPageSource - XML page source lines are 2500 lines

looks like webdriveragentrunner issue

Taking longer time to get response for "/session/{{SESSSION_ID}}/source" when list elements are 100 and above

Required some attribute to fetch elements that are visible in screen only

## Link to Appium logs

logs are not showing any error but waiting to load all page source

## Code To Reproduce Issue [ Good To Have ]

Required app page with 200+ list elements to test this scenario

**Comment by mykola-mokhnach** [comment]
The page source is retrieved by XCTest. Please report the issue to Apple.
You could also try some workarounds described in https://github.com/appium/appium/issues/13595
