### ISSUE TITLE
iOS 13.6 or 14 activateApp("appname") failed with timeout 

### ISSUE THREAD

**Issue by chuklov** [appium/appium#14923]
## The problem

on iOS 13.6 and 14 method activateApp() works for the first time and if you run it again while app is active you will get the following error:

Method threw 'org.openqa.selenium.WebDriverException' exception.

## Environment

Appium version (or git revision) that exhibits the issue: 1.18.3
Last Appium version that did not exhibit the issue (if applicable): 1.17
Desktop OS/version used to run Appium: 1.18.2
Node.js version (unless using Appium.app|exe): v15.0.1
Mobile platform/version under test: iOS 13.6 / 14
Real device or emulator/simulator: real device
Appium CLI or Appium.app|exe: cli

## Details

An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded

## Link to Appium logs

showIOSLog and showXcodeLog included. 
[GIST]<script src="https://gist.github.com/chuklov/7493dde1bd025815a1bd6e6432ff9d0d.js"></script> 

## Code To Reproduce Issue [ Good To Have ]

driver.activateApp("com.apple.mobilesafari");
driver.activateApp("com.apple.mobilesafari");

**Comment by mykola-mokhnach** [comment]
> [Xcode]     t =    44.08s Open com.checkpoint.capsuleprotect
> [Xcode] 
> [Xcode]     t =    44.08s     Activate com.checkpoint.capsuleprotect
> [Xcode] 
> [Xcode]     t =    44.13s         Wait for com.checkpoint.capsuleprotect to idle
> [Xcode]     t =   104.15s             App animations complete notification not received, will attempt to continue.
> [Xcode] 
> [Xcode]     t = 104.16s Wait for com.checkpoint.capsuleprotect to become Running Foreground

It looks like XCTest is unable to detect the application. Probably, because it is hogging the UI thread with animations.
Unfortunately, there is not much to do from Appium side. Consider reporting the issue to Apple or fixing the app.
You could also try Appium@beta.

**Comment by chuklov** [comment]
Hi @mykola-mokhnach what commands I can run on XCODE to simulate same behaviour as driver.activateApp()  ? 
XCUIApplication().launch() is not expecting to have an application name.

**Comment by mykola-mokhnach** [comment]
you should create an xcuiapplication object with the corresponding bundle id and then call
https://developer.apple.com/documentation/xctest/xcuiapplication/2873317-activate?language=objc
on it

**Comment by chuklov** [comment]
Thanks @mykola-mokhnach 
Last question, is there any possibility to perform the following from Appium:
_In a test you can disable animations by adding in setUp:_
    `app.launchEnvironment = ["animations": "0"]`
_Where app is instance of XCUIApplication._

If there is please let me know how. 
Thanks

**Comment by mykola-mokhnach** [comment]
I don't know any workarounds except of these mentioned above

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
