### ISSUE TITLE
Appium can't see opencv4nodejs

### ISSUE THREAD

**Issue by PavlikVasil** [appium/appium#14933]
## The problem

Appium-doctor show OpenCV not installed, although `npm list opencv4nodejs` gives `opencv4@1.0.0 /Users/pavel
└── opencv4nodejs@5.6.0`
And `npm list -g  opencv4nodejs` gives `/usr/local/lib
└── opencv4nodejs@5.6.0`

## Environment

Appium 1.19.1
npm 7.0.14

**Comment by mykola-mokhnach** [comment]
It looks like the opencv4nodejs library is poorly maintained and it is not compatible with OpenCV 4.4+.
Please make sure you could properly require this module first and no errors happen while importing it separately.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
