### ISSUE TITLE
appium

### ISSUE THREAD

**Issue by NAGAKARTHEEKREDDYDASAREDDY** [appium/appium#14935]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Could not sign with default certificate. Original error Command 'C:\Program Files\Java\jdk1.8.0_45\bin\bin\java.exe' not found. Is it installed?
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LAPTOP-PLAN2V3O', ip: '192.168.254.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_261'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not sign with default certificate. Original error Command 'C:\Program Files\Java\jdk1.8.0_45\bin\bin\java.exe' not found. Is it installed?
    at getResponseForW3CError (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:381:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LAPTOP-PLAN2V3O', ip: '192.168.254.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_261'
Driver info: driver.version: AndroidDriver
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:336)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:88)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:98)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:94)
	at demo.Frist_Test.firstTest(Frist_Test.java:34)
	at demo.Frist_Test.main(Frist_Test.java:19)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
	... 15 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not sign with default certificate. Original error Command 'C:\Program Files\Java\jdk1.8.0_45\bin\bin\java.exe' not found. Is it installed?
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LAPTOP-PLAN2V3O', ip: '192.168.254.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_261'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not sign with default certificate. Original error Command 'C:\Program Files\Java\jdk1.8.0_45\bin\bin\java.exe' not found. Is it installed?
    at getResponseForW3CError (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:381:37)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	... 20 more

**Comment by mykola-mokhnach** [comment]
Closed as incomplete. Please fill out the issue report according to the template.

**Comment by NAGAKARTHEEKREDDYDASAREDDY** [comment]
public class Frist_Test {
       AndroidDriver<WebElement> driver;
public static void main(String[] args) throws Exception {
	firstTest();
}

public static void firstTest() throws Exception{
	try{
	DesiredCapabilities caps = new DesiredCapabilities();
	caps.setCapability("deviceName", "emulator-5554");
	caps.setCapability("UDID", "emulator-5554");
	
	caps.setCapability("platformName", "Android");
	caps.setCapability("platformVersoin", "11");
	caps.setCapability(CapabilityType.BROWSER_NAME,"Chrome");
	URL url = new URL("http://127.0.0.1:4723/wd/hub");

	
	AndroidDriver<WebElement> driver = new AndroidDriver<WebElement>(url, caps);
	}catch (Exception e) {
		e.printStackTrace();
	}
}
}

**Comment by NAGAKARTHEEKREDDYDASAREDDY** [comment]
C:\Users\nagak>appium --version
1.19.1
C:\Users\nagak>node --version
v14.15.1

emulator

**Comment by NAGAKARTHEEKREDDYDASAREDDY** [comment]
The server is running
[Appium] Welcome to Appium v1.18.3
[Appium] Non-default server args:
[Appium]   address: 127.0.0.1
[Appium]   relaxedSecurityEnabled: true
[Appium]   allowInsecure: {
[Appium]   }
[Appium]   denyInsecure: {
[Appium]   }
[Appium] Appium REST http interface listener started on 127.0.0.1:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"browserName":"Chrome","platformVersoin":"11","platformName":"Android","UDID":"emulator-5554","deviceName":"emulator-5554"},"capabilities":{"firstMatch":[{"UDID":"emulator-5554","browserName":"Chrome","appium:deviceName":"emulator-5554","platformName":"android","platformVersoin":"11"}]}}
[W3C] Calling AppiumDriver.createSession() with args: [{"browserName":"Chrome","platformVersoin":"11","platformName":"Android","UDID":"emulator-5554","deviceName":"emulator-5554"},null,{"firstMatch":[{"UDID":"emulator-5554","browserName":"Chrome","appium:deviceName":"emulator-5554","platformName":"android","platformVersoin":"11"}]}]
[BaseDriver] Event 'newSessionRequested' logged at 1607408743848 (11:55:43 GMT+0530 (India Standard Time))
[BaseDriver] The following capabilities are not standard capabilities and should have an extension prefix:
[BaseDriver]   UDID
[BaseDriver]   platformVersoin
[Appium] 
[Appium] ======================================================================
[Appium]   DEPRECATION WARNING:
[Appium] 
[Appium]   The 'automationName' capability was not provided in the desired 
[Appium]   capabilities for this Android session
[Appium] 
[Appium]   Setting 'automationName=UiAutomator2' by default and using the 
[Appium]   UiAutomator2 Driver
[Appium] 
[Appium]   The next major version of Appium (2.x) will **require** the 
[Appium]   'automationName' capability to be set for all sessions on all 
[Appium]   platforms
[Appium] 
[Appium]   In previous versions (Appium <= 1.13.x), the default was 
[Appium]   'automationName=UiAutomator1'
[Appium] 
[Appium]   If you wish to use that automation instead of UiAutomator2, please 
[Appium]   add 'automationName=UiAutomator1' to your desired capabilities
[Appium] 
[Appium]   For more information about drivers, please visit 
[Appium]   http://appium.io/docs/en/about-appium/intro/ and explore the 
[Appium]   'Drivers' menu
[Appium] 
[Appium] ======================================================================
[Appium] 
[Appium] Appium v1.18.3 creating new AndroidUiautomator2Driver (v1.56.1) session
[Appium] Applying relaxed security to 'AndroidUiautomator2Driver' as per server command line argument. All insecure features will be enabled unless explicitly disabled by --deny-insecure
[BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[BaseDriver] Creating session with W3C capabilities: {
[BaseDriver]   "alwaysMatch": {
[BaseDriver]     "appium:UDID": "emulator-5554",
[BaseDriver]     "browserName": "Chrome",
[BaseDriver]     "platformName": "android",
[BaseDriver]     "appium:platformVersoin": "11",
[BaseDriver]     "appium:deviceName": "emulator-5554"
[BaseDriver]   },
[BaseDriver]   "firstMatch": [
[BaseDriver]     {}
[BaseDriver]   ]
[BaseDriver] }
[BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[BaseDriver]   UDID
[BaseDriver]   platformVersoin
[BaseDriver] Session created with session id: 1e15d12d-7621-4230-9803-8dc5d5441072
[UiAutomator2] We're going to run a Chrome-based session
[UiAutomator2] Chrome-type package and activity are com.android.chrome and com.google.android.apps.chrome.Main
[UiAutomator2] Starting 'com.android.chrome' directly on the device
[ADB] Using 'adb.exe' from 'C:\Users\nagak\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[ADB] Running 'C:\Users\nagak\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 start-server'
[AndroidDriver] Retrieving device list
[ADB] Trying to find a connected android device
[ADB] Getting connected devices
[ADB] Connected devices: [{"udid":"emulator-5554","state":"device"}]
[AndroidDriver] Using device: emulator-5554
[ADB] Using 'adb.exe' from 'C:\Users\nagak\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[ADB] Running 'C:\Users\nagak\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 start-server'
[ADB] Setting device id to emulator-5554
[ADB] Running 'C:\Users\nagak\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk'
[ADB] Current device property 'ro.build.version.sdk': 30
[ADB] Getting device platform version
[ADB] Running 'C:\Users\nagak\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.release'
[ADB] Current device property 'ro.build.version.release': 11
[ADB] Device API level: 30
[UiAutomator2] Relaxing hidden api policy
[ADB] Running 'C:\Users\nagak\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell 'settings put global hidden_api_policy_pre_p_apps 1;settings put global hidden_api_policy_p_apps 1;settings put global hidden_api_policy 1''
[AndroidDriver] No app sent in, not parsing package/activity
[ADB] Running 'C:\Users\nagak\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 wait-for-device'
[ADB] Running 'C:\Users\nagak\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell echo ping'
[AndroidDriver] Pushing settings apk to device...
[ADB] Getting install status for io.appium.settings
[ADB] Running 'C:\Users\nagak\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys package io.appium.settings'
[ADB] 'io.appium.settings' is installed
[ADB] Getting package info for 'io.appium.settings'
[ADB] Running 'C:\Users\nagak\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys package io.appium.settings'
[ADB] The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('3.2.0' >= '3.2.0')
[ADB] There is no need to install/upgrade 'C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk'
[ADB] Getting IDs of all 'io.appium.settings' processes
[ADB] Running 'C:\Users\nagak\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell 'pgrep --help; echo $?''
[ADB] Running 'C:\Users\nagak\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pgrep -f io\\.appium\\.settings'
[AndroidDriver] io.appium.settings is already running. There is no need to reset its permissions.
[Logcat] Starting logs capture with command: C:\\Users\\nagak\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 logcat -v threadtime
[UiAutomator2] Forwarding UiAutomator2 Server port 6790 to 8200
[ADB] Forwarding system: 8200 to device: 6790
[ADB] Running 'C:\Users\nagak\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 forward tcp\:8200 tcp\:6790'
[UiAutomator2] Server package at 'C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.12.2.apk' is not writeable. Will copy it into the temporary location at 'C:\Users\nagak\AppData\Local\Temp\2020118-5872-aa018g.2xtbh' as a workaround. Consider making this file writeable manually in order to improve the performance of session startup.
[UiAutomator2] Server package at 'C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk' is not writeable. Will copy it into the temporary location at 'C:\Users\nagak\AppData\Local\Temp\2020118-5872-aa018g.2xtbh' as a workaround. Consider making this file writeable manually in order to improve the performance of session startup.
[ADB] Getting install status for io.appium.uiautomator2.server
[ADB] Running 'C:\Users\nagak\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys package io.appium.uiautomator2.server'
[ADB] 'io.appium.uiautomator2.server' is not installed
[ADB] App 'C:\Users\nagak\AppData\Local\Temp\2020118-5872-aa018g.2xtbh\appium-uiautomator2-server-v4.12.2.apk' is not installed
[UiAutomator2] io.appium.uiautomator2.server installation state: notInstalled
[ADB] Checking app cert for C:\Users\nagak\AppData\Local\Temp\2020118-5872-aa018g.2xtbh\appium-uiautomator2-server-v4.12.2.apk
[ADB] Using 'apksigner.jar' from 'C:\Users\nagak\AppData\Local\Android\Sdk\build-tools\30.0.2\lib\apksigner.jar'
[ADB] Starting apksigner: 'C:\\Program Files\\Java\\jdk1.8.0_45\\bin\\bin\\java.exe' -Xmx1024M -Xss1m -jar C:\\Users\\nagak\\AppData\\Local\\Android\\Sdk\\build-tools\\30.0.2\\lib\\apksigner.jar verify --print-certs C:\\Users\\nagak\\AppData\\Local\\Temp\\2020118-5872-aa018g.2xtbh\\appium-uiautomator2-server-v4.12.2.apk
[ADB] Cannot use apksigner tool for signature verification. Original error: Command 'C:\Program Files\Java\jdk1.8.0_45\bin\bin\java.exe' not found. Is it installed?
[ADB] Defaulting to verify.jar
[ADB] 'C:\Users\nagak\AppData\Local\Temp\2020118-5872-aa018g.2xtbh\appium-uiautomator2-server-v4.12.2.apk' is not signed with the default certificate
[ADB] Command 'C:\Program Files\Java\jdk1.8.0_45\bin\bin\java.exe' not found. Is it installed?
[ADB] Using 'zipalign.exe' from 'C:\Users\nagak\AppData\Local\Android\Sdk\build-tools\30.0.2\zipalign.exe'
[ADB] C:\Users\nagak\AppData\Local\Temp\2020118-5872-aa018g.2xtbh\appium-uiautomator2-server-v4.12.2.apk' is already zip-aligned. Doing nothing
[ADB] Signing 'C:\Users\nagak\AppData\Local\Temp\2020118-5872-aa018g.2xtbh\appium-uiautomator2-server-v4.12.2.apk' with default cert
[ADB] Starting apksigner: 'C:\\Program Files\\Java\\jdk1.8.0_45\\bin\\bin\\java.exe' -Xmx1024M -Xss1m -jar C:\\Users\\nagak\\AppData\\Local\\Android\\Sdk\\build-tools\\30.0.2\\lib\\apksigner.jar sign --key 'C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-adb\\keys\\testkey.pk8' --cert 'C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-adb\\keys\\testkey.x509.pem' C:\\Users\\nagak\\AppData\\Local\\Temp\\2020118-5872-aa018g.2xtbh\\appium-uiautomator2-server-v4.12.2.apk
[ADB] Cannot use apksigner tool for signing. Defaulting to sign.jar. Original error: Command 'C:\Program Files\Java\jdk1.8.0_45\bin\bin\java.exe' not found. Is it installed?
[ADB] Starting sign.jar: 'C:\\Program Files\\Java\\jdk1.8.0_45\\bin\\bin\\java.exe' -jar 'C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-adb\\jars\\sign.jar' C:\\Users\\nagak\\AppData\\Local\\Temp\\2020118-5872-aa018g.2xtbh\\appium-uiautomator2-server-v4.12.2.apk --override
[UiAutomator2] Deleting UiAutomator2 session
[UiAutomator2] Deleting UiAutomator2 server session
[WD Proxy] Matched '/' to command name 'deleteSession'
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
[Logcat] Stopping logcat capture
[ADB] Removing forwarded port socket connection: 8200 
[ADB] Running 'C:\Users\nagak\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 forward --remove tcp\:8200'
[UiAutomator2] Restoring hidden api policy to the device default configuration
[ADB] Running 'C:\Users\nagak\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''
[BaseDriver] Event 'newSessionStarted' logged at 1607408746058 (11:55:46 GMT+0530 (India Standard Time))
[W3C] Encountered internal error running command: Error: Could not sign with default certificate. Original error Command 'C:\Program Files\Java\jdk1.8.0_45\bin\bin\java.exe' not found. Is it installed?
[W3C]     at ADB.signWithDefaultCert (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\apk-signing.js:80:13)
[W3C] Destroying socket connection
[HTTP] <-- POST /wd/hub/session 500 2212 ms - 865
[HTTP]

**Comment by mykola-mokhnach** [comment]
> Command 'C:\Program Files\Java\jdk1.8.0_45\bin\bin\java.exe' not found. Is it installed?

The error is pretty clear. Either java is not installed or JAVA_HOME is not pointing to a correct path. This issue has nothing to do with Appium itself.

**Comment by NAGAKARTHEEKREDDYDASAREDDY** [comment]
Thanks and regards

Naga Kartheek Reddy
Test Engineer
mobile : +91-9059995072
nagakartheek.dasareddy@gmail.com <email%3A-nagakartheekreddy@gmail.com>

**Comment by NAGAKARTHEEKREDDYDASAREDDY** [comment]
this is java path
Thanks and regards

Naga Kartheek Reddy
Test Engineer
mobile : +91-9059995072
nagakartheek.dasareddy@gmail.com <email%3A-nagakartheekreddy@gmail.com>
