### ISSUE TITLE
Difference between 'appium' default automation and UIAutomator 2

### ISSUE THREAD

**Issue by AllanElleuch** [appium/appium#14931]
## The problem

Hi, this is not a technical issue but an question about the documentation. The automationName capability is described as follow : 

`Appium (default), or UiAutomator2, Espresso, or UiAutomator1 for Android, or XCUITest or Instruments for iOS, or YouiEngine for application built with You.i Engine`

Could you describe more about the 'Appium' default automator. Does it have the same functionnality, stability and performance than UIAutomator 2 ? I guess that it is used by default with Android because if it is not specified the method driver.getAutomationName return null. 

Thank you very much !

**Comment by mykola-mokhnach** [comment]
I would say the documentation is outdated there. Putting `appium` as automation name means to select the default automation backend for the given platform. In Android there are 3 automation backends: UIA1, UIA2 and Espresso. UIA1 is obsolete and should be used only until Android API 21. The current flagship is UIA2. Espresso is a viable alternative to UIA2, however the final decision depends on the actual automation scenario.

**Comment by AllanElleuch** [comment]
Thank you for the clear explanation :+1:
