### ISSUE TITLE
UiSelector.textContains() -is case insensitive while API claimes it is case sensitive.

### ISSUE THREAD

**Issue by stuchins** [appium/appium#14932]
## Android. textContains() returns first found on page case insensitive text.

Script has to find the text (for this example) "Continue" but instead it finds another instance of the text that contains "continue" text.

## Environment

* Appium version 1.18.3
* Desktop OS/version used to run Appium: Mac OS 10.15.7 Catalina
* Node.js version (unless using Appium.app|exe): v10.15.0
* Npm or Yarn package manager: NPM v. 6.14.8
* Mobile platform/version under test: Android API 29
* Real device or emulator/simulator: emulatior
* Appium CLI or Appium.app|exe: both

## Details

API: * Set the search criteria to match the visible text in a widget where the visible text must
   * contain the string in your input argument. The matching is case-sensitive.
![Screen Shot 2020-12-04 at 2 48 14 PM](https://user-images.githubusercontent.com/67928502/101397101-1c336900-3881-11eb-9209-5408a4e9f7f7.png)

 ==================================================
Part of the page source:
                                      <android.view.View index="1" package="com.chase.sig.android" class="android.view.View" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[36,627][1044,1221]" displayed="true">
                                        <android.view.View index="0" package="com.chase.sig.android" class="android.view.View" text="Change primary email address?" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[72,627][1008,693]" displayed="true" />
                                        <android.view.View index="1" package="com.chase.sig.android" class="android.view.View" text="If you want to change the email address we use to send you paperless notifications, we need to take you to the Email page in My Profile, and you'll lose any unsaved changes you've made on this page.&#10;&#10;Do you want to continue?" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[72,762][1008,1155]" displayed="true" />
                                      </android.view.View>
                                      <android.view.View index="2" package="com.chase.sig.android" class="android.view.View" text="  " checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,1773][936,1776]" displayed="true" />
                                      <android.view.View index="3" package="com.chase.sig.android" class="android.view.View" text="  " checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,1773][936,1776]" displayed="true" />
                                      <android.view.View index="4" package="com.chase.sig.android" class="android.view.View" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[36,1221][1044,1389]" displayed="true">
                                        <android.view.View index="0" package="com.chase.sig.android" class="android.view.View" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[36,1221][540,1389]" displayed="true">
                                          <android.widget.Button index="0" package="com.chase.sig.android" class="android.widget.Button" text="Cancel" resource-id="updatePrimaryEmailModal-cancel-button" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[72,1245][504,1365]" displayed="true" />
                                        </android.view.View>
                                        <android.view.View index="1" package="com.chase.sig.android" class="android.view.View" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[540,1221][1044,1389]" displayed="true">
                                          <android.widget.Button index="0" package="com.chase.sig.android" class="android.widget.Button" text="Continue" resource-id="updatePrimaryEmailModal-confirm-button" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[576,1245][1008,1365]" displayed="true" />
                                        </android.view.View>
                                      </android.view.View>

==========================================================================================

## Code To Reproduce Issue [ Good To Have ]

Method
driver.findElementByAndroidUIAutomator("new UiScrollable("
        + "new UiSelector().scrollable(true)).scrollIntoView("
        + "new UiSelector().textContains(\"Continue\"));").getText();  returns "If you want to change the email address we use to send you paperless notifications, we need to take you to the Email page in My Profile, and you'll lose any unsaved changes you've made on this page. Do you want to continue?" Instead of "Continue"

**Comment by amedvedjev** [comment]
it i not a problem of Appium but Android. Feel free report to google.
as workaround use better  "textStartsWith" or "textMatches". more to read -> https://developer.android.com/reference/androidx/test/uiautomator/UiSelector

**Comment by mykola-mokhnach** [comment]
there is nothing we could do about it. Please report the issue to Google like @amedvedjev advised.
