### ISSUE TITLE
Different elements tree for different OS for the same app, after updating the app to React Navigation 5 (Android)

### ISSUE THREAD

**Issue by ssvitlyk** [appium/appium#14945]
## The problem

Different elements tree for different OS for the same app, after updating the app to React Navigation 5 (Android)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.0, 1.18.0 
* Desktop OS/version used to run Appium: ubuntu 20.04
* Mobile platform/version under test: 9.0 and less
* Real device or emulator/simulator: real devices and emulators

## Details

I try to find elements on the same app, but on different OS (10.0 and 9.0 and less) and get different trees.
For Android 10.0 I get the normal tree, all elements only for the current screen displayed. (as on screenshot)
![Android 10](https://user-images.githubusercontent.com/60655698/101928524-60ef3500-3bde-11eb-91fe-37cd80f49fab.png)

For Android 9.0 I get a tree for all previous screens. Login, dashboard...(as on screenshot)
![Android 9](https://user-images.githubusercontent.com/60655698/101928511-5d5bae00-3bde-11eb-8f16-85796c8f2b04.png)

Maybe someone had the same problem. In the second variant, I get a problem with detecting elements

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
