### ISSUE TITLE
[Android] screen size information is incorrect in google devices

### ISSUE THREAD

**Issue by cheffey** [appium/appium#14948]
## The problem
Screen size (which get by java client Dimension size = driver.manage().window().getSize();) is incorrect(height is shorter than expected) in real device: pixel 3 XL and some emulator. And this problem lead to other issues like:
tap(java client code: new TouchAction<>(driver).tap(PointOption.point(location.x, location.y)).release().perform();) bottom part will catch illegalArgumentException which tells me it's out of screen bounds, and it's not true just by the screenshot.

## Environment

* Appium version: 19.1 cli
* Node.js version (unless using Appium.app|exe): v12.10.0
* Real device or emulator/simulator: real device(Pixel 3 XL android 11), emulator(pixel 4 android 9 and android 11)
* UIAutomator server version: 4.15.0

## Details
For example in real device pixel 3 XL android 11:
appium info ViewportRect(driver.getSessionDetails().get("viewportRect")): [0, 171, 1440, 2450]
and the size is (1440, 2621)
the screenshot size: 1440x2960

## Link to Appium logs
Do not think it's necessary, contact me if it's needed.

## Code To Reproduce Issue [ Good To Have ]
Use android studio 4.1
make a new AVD with android 9.0(google APIs) and pixel-4 model.
start appium with this device. and run commands:
driver.manage().window().getSize();            I got (1080, 1977)
driver.getSessionDetails().get("viewportRect"); I got [0, 135, 1080, 1842]
take a screenshot. I got with size (1080, 2280)
compare the size and viewPortRect with screenshot size.

**Comment by mykola-mokhnach** [comment]
The size is retrieved directly from [UiAutomator](https://github.com/appium/appium-uiautomator2-server/blob/58828f9488377b603ac16ffc4270950ba9114dc9/app/src/main/java/io/appium/uiautomator2/handler/GetDeviceSize.java#L40). Please report the issue to Google if you think this is a bug.
