### ISSUE TITLE
NullPointerException when trying to find an element

### ISSUE THREAD

**Issue by jpkleemans** [appium/appium#14950]
## The problem

I'm getting the following error when trying to find an element in my Android app: `java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference`

## Environment

* Appium version: **1.19.1**
* Last Appium version that did not exhibit the issue: **None**
* Desktop OS/version used to run Appium: **CentOS 8**
* Node.js version: **12.18.4**
* Npm or Yarn package manager: **Npm**
* Mobile platform/version under test: **android-26;google_apis;x86_64**
* Real device or emulator/simulator: **Emulator**
* Appium CLI or Appium.app|exe: **CLI**

## Link to Appium logs

https://gist.github.com/jpkleemans/88e80aa3251917c1e337e4fae8853f68

**Comment by mykola-mokhnach** [comment]
Please check if the issue is reproducible with appium@beta and provide the full log

**Comment by mykola-mokhnach** [comment]
Closed because of no response
