### ISSUE TITLE
Can not find by xpath (or others) when element is out of screen (not visible)

### ISSUE THREAD

**Issue by mguerrer** [appium/appium#14959]
## The problem

I have the following problem.      I am using Java 15/Appium 6.0.

I am testing an App on Android and a form that is long enough to have elements that in some small phones can not be visible before user swipe or scroll screen.     Given this Appium is not able to find them with xpath when they are not visible, however when visible Appium resolves correctly.        

I understand that this is probably more related to Appium, so please help, because so far I have not found any suitable way to programmatically solve this issue other than use a bigger device like “Samsung Galaxy Tab S7”.   I ran all Google but no solution. 

Can you please help?

## Environment

* Appium version (or git revision) that exhibits the issue: 6.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: Android 10
* Real device or emulator/simulator: Samsung Galaxy A51 (BrowserStack)   Samsung Galaxy S8+ (real)
* Appium CLI or Appium.app|exe: App 1.18.3

## Details

I have tried to solve the issue with Appium Inspector recording a swipe.  However the code for Java/Junit provided can not be compiled.
(new TouchAction(driver))
  .press({x: 493, y: 1999})
  .moveTo({x: 501: y: 511})
  .release()
  .perform()

io.appium.java_client.TouchAction.TouchAction(PerformsTouchActions performsTouchActions)
TouchAction is a raw type. References to generic type TouchAction<T> should be parameterized

## Link to Appium logs

Find elementxpath=/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.webkit.WebView/android.webkit.WebView/android.view.View[2]/android.view.View[2]/android.view.View[2]/android.view.View/android.view.View/android.view.View/android.view.View[2]/android.view.View/android.view.View[3]
usingxpath
value/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.webkit.WebView/android.webkit.WebView/android.view.View[2]/android.view.View[2]/android.view.View[2]/android.view.View/android.view.View/android.view.View/android.view.View[2]/android.view.View/android.view.View[3]
⇒
An element could not be located on the page using the given search parameters.

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
You could try to play with `allowInvisibleElements` and/or `ignoreUnimportantViews` [settings](https://github.com/appium/appium-uiautomator2-driver#settings-api). If the node is still not present in the page source output then this most likely means that Android does not render it to the Accessibility layer and there is no way to do anything to change that from the Appium side.

**Comment by mguerrer** [comment]
Hi Mykola

Thanks a lot!    I used  allowInvisibleElements and worked perfectly!!


Best regards,
Marcos Guerrero W.
Consultor DevOps, Automatización, Metodologías
Padre Hurtado 660 Depto. J72, Viña del mar
(569) 93231694


De: Mykola Mokhnach <notifications@github.com>
Enviado el: viernes, 18 de diciembre de 2020 12:07
Para: appium/appium <appium@noreply.github.com>
CC: mguerrer <marcosguerrerow@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [appium/appium] Can not find by xpath (or others) when element is out of screen (not visible) (#14959)


You could try to play with allowInvisibleElements and/or ignoreUnimportantViews settings<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fappium%2Fappium-uiautomator2-driver%23settings-api&data=04%7C01%7C%7Cea2fd6f1d91b4ec4e64f08d8a366990c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637439008337271391%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Xgd5NU7%2FG%2FDtX1S8afmmml1qCu9gL31CNtHolQOL7%2Fg%3D&reserved=0>. If the node is still not present in the page source output then this most likely means that Android does not render it to the Accessibility layer and there is no way to do anything to change that from the Appium side.

-
