### ISSUE TITLE
WebDriver Agent Runner app failed to Create in iPhone

### ISSUE THREAD

**Issue by narasimhanukala** [appium/appium#14957]
## The problem

Without any apple account mapped in xcode, i have tried to launch safari browser in iPhone 11 on Mac Big Sur machine using appium desktop version 1.19.1, WebDriver Agent Runner app failed to create in iPhone, it failed with error code 65

## Environment

Appium version (or git revision) that exhibits the issue:1.18.3/1.19.1
Desktop OS/version used to run Appium:1.18.1
Node.js version (unless using Appium.app|exe):10.16.3
Npm or Yarn package manager:6.9.0
Mobile platform/version under test: iOS 14.3
Real device or emulator/simulator: Real Device
Appium CLI or Appium.app|exe:both

## Details

While launching safari browser with below capabilities, appium failed to launch the browser with the below specified log.

Capabilities:
{
  "deviceName": "iPhone",
  "udid": "xxxxxxxxxxxxxxxx",
  "platformName": "iOS",
  "platformVersion": "14.3",
  "browserName": "safari",
  "autoLaunch": true,
  "useNewWDA": true,
  "startIWDP": true
}

## Link to Appium logs

{\rtf1\ansi\ansicpg1252\cocoartf2576
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 HelveticaNeue;\f1\fnil\fcharset0 .AppleColorEmojiUI;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;\red255\green255\blue255;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0\c65098;\cssrgb\c100000\c100000\c100000;}
\paperw11900\paperh16840\margl1440\margr1440\vieww28600\viewh18000\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs24 \cf2 \cb3 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65 xcodebuild error message: 2020-12-16 00:01:19.157 xcodebuild[856:10366] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder \'93WebDriverAgentRunner_iphoneos14.2-arm64.xctestrun\'94 doesn\'92t exist." UserInfo=\{NSFilePath=/Users/yadu/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Build/Products/WebDriverAgentRunner_iphoneos14.2-arm64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7f9a398c7060 \{Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"\}\} ** TEST BUILD FAILED ** 2020-12-16 00:01:19.241 xcodebuild[856:10365] IDETestOperationsObserverDebug: Writing diagnostic log for test session to: /Users/yadu/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Logs/Test/Test-WebDriverAgentRunner-2020.12.16_00-01-05-+0800.xcresult/Staging/2_Test/Diagnostics/WebDriverAgentRunner-F16ADBF1-8766-4DDE-88ED-8863C25C43DE/WebDriverAgentRunner-810F75D6-72FA-4CBF-8C69-CACE0939212E/Session-WebDriverAgentRunner-2020-12-16_000119-FgcuTE.log 2020-12-16 00:01:19.255 xcodebuild[856:10308] [MT] IDETestOperationsObserverDebug: (CDF08AE5-3689-4872-A8BA-2F99A07B4950) Beginning test session WebDriverAgentRunner-CDF08AE5-3689-4872-A8BA-2F99A07B4950 at 2020-12-16 00:01:19.252 with Xcode 12B45b on target 
\f1 \uc0\u55357 \u56561 
\f0 <DVTiOSDevice (0x7f9a3a1e53a0), xxxxx\'92s iPhone, iPhone, 14.0 (18A373), 0xxxxxxxxxxxxx> \{ deviceSerialNumber: xxxxxxxxxx identifier: xxxxxxxxxx deviceClass: iPhone deviceName: xxxxxxxx iPhone deviceIdentifier: xxxxxxxxxxxx productVersion: 14.0 buildVersion: 18A373 deviceSoftwareVersion: 14.0 (18A373) deviceArchitecture: arm64e deviceTotalCapacity: 52049379328 deviceAvailableCapacity: 42347786240 deviceIsTransient: NO ignored: NO deviceIsBusy: NO deviceIsPaired: YES deviceIsActivated: YES deviceActivationState: Activated isPasscodeLocked: NO deviceType: <DVTDeviceType:0x7f9a39a2e260 Xcode.DeviceType.iPhone> supportedDeviceFamilies: ( 1 ) applications: (null) provisioningProfiles: (null) hasInternalSupport: NO hasWritableSystem: NO isSupportedOS: YES bootArgs: (null) nextBootArgs: (null) connected: YES isWirelessEnabled: NO connectionType: direct hostname: (null) bonjourServiceName: d8:dc:40:f3:70:62@fe80::dadc:40ff:fef3:7062._apple-mobdev2._tcp.local. activeProxiedDevice: (null) \} (14.0 (18A373)) 2020-12-16 00:01:19.498 xcodebuild[856:10308] [MT] IDETestOperationsObserverDebug: (CDF08AE5-3689-4872-A8BA-2F99A07B4950) Finished requesting crash reports. Continuing with testing. *** If you believe this error represents a bug, please attach the result bundle at /Users/yadu/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Logs/Test/Test-WebDriverAgentRunner-2020.12.16_00-

**Comment by mykola-mokhnach** [comment]
> Without any apple account mapped in xcode, i have tried to launch safari browser in iPhone 11 on Mac Big Sur machine using appium desktop version 1.19.1, WebDriver Agent Runner app failed to create in iPhone, it failed with error code 65

It is not possible to use WebDriverAgent on a real device without a valid developer signature. Please follow https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

**Comment by mykola-mokhnach** [comment]
Also, The recent stable Appium version does not support Xcode 12.3. Check https://github.com/appium/appium/issues/14952 for more details

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
