### ISSUE TITLE
`"autoAcceptAlerts": "true",` is causing Appium to dismiss dialogues within the application

### ISSUE THREAD

**Issue by KotlinIsland** [appium/appium#14956]
## The problem
`"autoAcceptAlerts": "true",` is causing Appium to dismiss dialogues within the application(non system dialogues). Strangely, it only happens when the device is in portrait orientation.

## Environment
* Appium version (or git revision) that exhibits the issue: 1.19.1
* Desktop OS/version used to run Appium: macOS 11.1
* Mobile platform/version under test: iOS 14.2
* Real device or emulator/simulator: iPad 8th generation
* Appium CLI or Appium.app|exe: cli and .app

## Code To Reproduce Issue [ Good To Have ]

```py
desired_capabilities.update(
    {
        "autoAcceptAlerts": "true",
    }
)
```

**Comment by KazuCocoa** [comment]
You can customise the rule to tap as 'accept' or 'dismiss' with `acceptAlertButtonSelector` or `dismissAlertButtonSelector` by https://appium.io/docs/en/advanced-concepts/settings/

Alert/Dismiss buttons depend on OS versions and context, so we provide them to be able to customise by users.

**Comment by KotlinIsland** [comment]
Is it expected to affect _non system_ dialogues? because the documentation reads as only system dialogues.

Even then, it's only happening when the device is in portrait orientation.

**Comment by KazuCocoa** [comment]
Yea. It is expected so far.

Apple does not provide exact system alert information like by XCUIElementType etc, so Appium tries to find possible alerts.
https://github.com/appium/WebDriverAgent/blob/618b0906d64d843413f2f2dd13b465d2f03c523e/WebDriverAgentLib/FBAlert.m#L159-L235
This could be wrong in some cases, so Appium has acceptAlertButtonSelector/dismissAlertButtonSelector.

Probably when the device was landscape, it had a different elements tree as portrait.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue. The behaviour is expected
