### ISSUE TITLE
Logcat empty on some devices since

### ISSUE THREAD

**Issue by senchi** [appium/appium#14955]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

Since Android platform-tools 28.0.1, some devices (i.e. my LG G6), have problems with logcat output.
i.e. "adb logcat" output is empty, while "adb shell logcat" does output the logcat contents.

Is there a way to switch Appium to use the "adb shell" command, or make the shell output default?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10/ OSX
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Device LG G6
* Appium CLI or Appium.app|exe: Appium CLI and/or Appium.app|exe

## Details

If necessary, describe the problem you have been experiencing in more detail.

This thread pretty much describes the problem: https://superuser.com/a/1357929

The behavior is same if used via "driver.manage().logs().get("logcat")" or via WebSocketConnection as described here: https://appiumpro.com/editions/55-using-mobile-execution-commands-to-continuously-stream-device-logs-with-appium

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
There is a possibility for UiAutomator2 driver to explicitly set which build tools version to use (`buildToolsVersion` capability). I don't think we should create workarounds for a bug, that is potentially introduced by a device vendor or adb itself. It makes more sense to report it to Google then

**Comment by senchi** [comment]
@mykola-mokhnach thanks, yes, I agree, Appium should not provide workarounds for OS/Phone Software bugs.
I don't think that LG will tend to fix that since this model is not very recent, so I still need a workaround for that in my e2e tests.
I was looking at [this example](https://appiumpro.com/editions/55-using-mobile-execution-commands-to-continuously-stream-device-logs-with-appium) here which utilizes the `mobile:startLogsBroadcast` command.
Is there a way to modify it in a way so it executes a custom command and then outputs it to the WebSocket client (i.e. `ws://localhost:4723/ws/session/:session_id/appium/device/syslog`)?

The following command does execute for me but it blocks the execution of course. 

```
Map<String, Object> args = new HashMap<>();
args.put("command", "logcat");
args.put("args", Lists.newArrayList());
Object output = driver.executeScript("mobile: shell", args);
LOG.info("Logcat Output - " + output);
```

A WebSocket listener is a great solution, otherwise I'd need to implement my own handling with "from/to" timestamps which complicates this a lot.

What do you think?

Thanks

**Comment by mykola-mokhnach** [comment]
You could change the command locally by modifying server sources for https://github.com/appium/appium-adb/blob/482ca14b18274b3b862f66f605607dbf773d0501/lib/logcat.js#L89

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by senchi** [comment]
PS. The patch with `adb shell -x logcat` works, but use it with caution because it slowed test execution time by a factor of three.
Therefore, in our particular case, we're going to use the adb from 28.0.0 platform-tools which work with this LG model.

Thanks
