### ISSUE TITLE
No Chromedriver found that can automate Chrome '87.0.4280'

### ISSUE THREAD

**Issue by kontownik** [appium/appium#14958]
## The problem
Unable to get data from hybrid app (based on Chrome webview)

## Environment

* Appium version 1.19.1
* Mobile platform/version under test: Android 
* Real device or emulator/simulator: Real device

## Link to Appium logs
`io.appium.java_client.NoSuchContextException: An unknown server-side error occurred while processing the command. Original error: No Chromedriver found that can automate Chrome '87.0.4280'`

## Code To Reproduce Issue [ Good To Have ]
Iterate through context handles e.g. `driver.contextHandles`

**Comment by mykola-mokhnach** [comment]
The error is expected. Consider either downloading the matching chromedriver manually or enabling automatic download of it. Read https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md for more details
