### ISSUE TITLE
Run Error: error: Building for iOS Simulator, but the embedded framework 'CocoaAsyncSocket.framework' was built for iOS + iOS Simulator. (in target 'WebDriverAgentRunner' from project 'WebDriverAgent')

### ISSUE THREAD

**Issue by angelmic** [appium/appium#14962]
## The problem

Hi,
Iam having the same issue getting the error
error: Building for iOS Simulator, but the embedded framework 'CocoaAsyncSocket.framework' was built for iOS + iOS Simulator. (in target 'WebDriverAgentRunner' from project 'WebDriverAgent')
error: Building for iOS Simulator, but the embedded framework 'YYCache.framework' was built for iOS + iOS Simulator. (in target 'WebDriverAgentRunner' from project 'WebDriverAgent')

Could please help me out the resolve

## Environment

* Appium version (or git revision) that exhibits the issue: 1.19.1
* Last Appium version that did not exhibit the issue (if applicable): 1.19.1
* Desktop OS/version used to run Appium: Mac OS Big Sur 11.2
* Node.js version (unless using Appium.app|exe): v10.14.2
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS 14.3
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI

## Details

error: Building for iOS Simulator, but the embedded framework 'CocoaAsyncSocket.framework' was built for iOS + iOS Simulator. (in target 'WebDriverAgentRunner' from project 'WebDriverAgent')
...

## Link to Appium logs
[Appium logs](https://gist.github.com/angelmic/4345832e1789a7fbd396fc74ff11004f)

**Comment by mykola-mokhnach** [comment]
Du0plicate of https://github.com/appium/appium/issues/14952
