### ISSUE TITLE
Images seeded via Appium are not visible on sdcard on phone

### ISSUE THREAD

**Issue by jaspreetchagger** [appium/appium#14966]
I am trying to seed images on Android 3a XL API 30 emulator using below commands

File assetDir = new File(System.getProperty("user.dir")+"/src/test/resources/Assets");
		for(int i=1;i<7;i++)
		{
		File img = new File(assetDir.getCanonicalPath(), "testImage"+i+".jpeg");
		((PushesFiles) getDriver()).pushFile("/sdcard/DCIM/Pictures" + "/" + img.getName(), img);
}  catch(Exception e)
		{
			e.printStackTrace();
		}

## Environment

* Appium Desktop 1.18.0-2
* Node.js version 12.8.1
* Mobile platform/version under test: Android 11
* Real device or emulator/simulator:  Android 3a XL API 30 emulator 
* Automation Name: UiAutomator2

Now if i check emulator and go to sdcard/DCIM/Pictures , i see photos are added to this folder.
But photos don't appear if i try to access them by Choose from Library option in my test native app.
If i go to sdcard/DCIM/Pictures and click on USE THIS FOLDER and cold boot emulator. If reopen app now , i can see photos under Camera folder when i select Choose from Libarary option in my test app.
However if i run my appium script again of seeding photos (as mentioned above), photos disappear from Library and i have to do whole process of USE THIS FOLDER again

Note this issue is not present to API 28 emulator, If i seed photos via above script. Photos are immediately visible in Library

**Comment by mykola-mokhnach** [comment]
Please provide the full server log

**Comment by mykola-mokhnach** [comment]
Closed because of no response
