### ISSUE TITLE
Add Capability for Custom Espresso Driver Repo

### ISSUE THREAD

**Issue by napsta32** [appium/appium#14974]
## The problem

Appium Espresso Driver has many issues that need to be solved by manually changing build.gradle files.
I would prefer to fork the repo and change these things manually, and use my modified espresso driver to test my app.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.19.1
* Desktop OS/version used to run Appium: macOS Catalina 10.15.7
* Mobile platform/version under test: Android 11
* Real device or emulator/simulator: Real Device Pixel 3
* Appium CLI or Appium.app|exe: Appium.app

## Details

In particular I am having this issue right now: https://github.com/appium/appium-espresso-driver/issues/647
I expect more issues to come.

**Comment by mykola-mokhnach** [comment]
I don't quite understand what that new capability is expected to look like. Please provide an example.

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by napsta32** [comment]
@mykola-mokhnach 
I was just checking the code. Looks like you are using package.json to import android/ios driver repos. I forked all the projects to modify them how I would needed them. Still there are some complex issues to solve in Appium Espresso driver. I think I will stick with UIAutomator for now. Thanks anyways. Sorry for the late response.
