### ISSUE TITLE
TextFields getting cleared when trying to fill next textField or selecting any popup, ios app automation. 

### ISSUE THREAD

**Issue by vijayqa** [appium/appium#14970]
## The problem

TextFields are getting cleared automatically when focus moves away. If I select dropdown after filling TextFields, the TextFields are getting cleared. if I fill the textField at the end and submit, its throwing error as TextFields are not filled.
we are trying to automate the ios Application build on objective c for iPad.

## Environment

* Appium version (or git revision) that exhibits the issue:1.19.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:1.19.1
* Node.js version (unless using Appium.app|exe):15.4.0
* Npm or Yarn package manager:7.0.15
* Mobile platform/version under test:14.3 iOS
* Real device or emulator/simulator:Both real device and emulator
* Appium CLI or Appium.app|exe:Both CLI and app behaves same.

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
https://gist.github.com/vijayqa/8ff9577f665e445494c9ad3d43c3b300

**Comment by mykola-mokhnach** [comment]
Please check the issue with your developer or report it to Apple. Appium simply uses the standard XCTest method calls to enter a text. 

Also, what exactly should be checked in the attached log?

**Comment by mykola-mokhnach** [comment]
Closed because of no response
