### ISSUE TITLE
Appium is opening and closing application immediately on simulator until server stops. IOS (I am freshman I need  your help)

### ISSUE THREAD

**Issue by levank707** [appium/appium#14977]
## The problem

I CANT OPEN THE  APP ON SIMULATOR WITH APPIUM 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.19.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS Big Sur  11.1
* Node.js version (unless using Appium.app|exe): 15.4.0
* Npm or Yarn package manager: 6.14.10
* Mobile platform/version under test: IOS 14.2
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: .app 

## Details

When I am trying to run simulator and .app with appium  it is opening and closing application immediately on simulator until servers stops. Than I am trying to run .app manually on simulator with drag and drop and also nothing , there is same issue, but, when I am Erasing all content and settings  on simulator and  trying to run  .app manually with drag and drop, its opening it , its working everything fine. Than I am trying again to run it with appium , but its still opening and closing application.

P.S    I have got an .app file from my dev team.  also, sorry for my English and writing skills. 
I would be very gratefully  if someone response. 

## Link to Appium logs

https://gist.github.com/levank707/34caa1509ba8f6c3410d01d764e81bb5#file-gistfile1-txt

**Comment by mykola-mokhnach** [comment]
Please provide the full server log with `showIOSLog` and `showXcodeLog` capabilities enabled

**Comment by levank707** [comment]
> Please provide the full server log with `showIOSLog` and `showXcodeLog` capabilities enabled

serverlog: https://gist.github.com/levank707/f529ed2979ae7df4eac0c43d9c3addb3   
simulator log: https://gist.github.com/levank707/4495542876a244acf9e652845b752574

**Comment by mykola-mokhnach** [comment]
> Dec 26 02:06:36 Macbooks-MacBook-Pro com.apple.CoreSimulator.SimDevice.D13EAE93-2B96-480B-B6DD-2E49B1A462CD[13618] (UIKitApplication:com.stage.Mobile[169b][rb-legacy][13825]): Service exited due to SIGILL | sent by exc handler[13825]

This looks like a bug in the app itself. Check it with your developer

> [debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {
> [debug] [BaseDriver]   "app": "/Users/macbookpro/eclipse-workspace/iosdemo/src/test/java/Mobile Stage.app",
> [debug] [BaseDriver]   "noReset": "True",
> [debug] [BaseDriver]   "platformVersion": "14.2",
> [debug] [BaseDriver]   "automationName": "XCuiTest",
> [debug] [BaseDriver]   "platformName": "IOS",
> [debug] [BaseDriver]   "deviceName": "iPhone 12 Pro Max"
> [debug] [BaseDriver] }

- Providing noReset means the app should be already installed and running on the device
- noReset must be boolean, not string
- The requested capabilities are still not set

**Comment by levank707** [comment]
> > Dec 26 02:06:36 Macbooks-MacBook-Pro com.apple.CoreSimulator.SimDevice.D13EAE93-2B96-480B-B6DD-2E49B1A462CD[13618] (UIKitApplication:com.stage.Mobile[169b][rb-legacy][13825]): Service exited due to SIGILL | sent by exc handler[13825]
> 
> This looks like a bug in the app itself. Check it with your developer
> 
> > [debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {
> > [debug] [BaseDriver]   "app": "/Users/macbookpro/eclipse-workspace/iosdemo/src/test/java/Mobile Stage.app",
> > [debug] [BaseDriver]   "noReset": "True",
> > [debug] [BaseDriver]   "platformVersion": "14.2",
> > [debug] [BaseDriver]   "automationName": "XCuiTest",
> > [debug] [BaseDriver]   "platformName": "IOS",
> > [debug] [BaseDriver]   "deviceName": "iPhone 12 Pro Max"
> > [debug] [BaseDriver] }
> 
> * Providing noReset means the app should be already installed and running on the device
> * noReset must be boolean, not string
> * The requested capabilities are still not set

First of all  thank you very much for checking logs and your  response, I very appreciate it .  I will set boolean, in noReset, ok. but I have one question, if   app has bug, why I am able to run app manually on simulator, by drag and drop ?  P.S this is happening when I perform  "Erase All Content and Settings...." on simulator

**Comment by levank707** [comment]
> > Dec 26 02:06:36 Macbooks-MacBook-Pro com.apple.CoreSimulator.SimDevice.D13EAE93-2B96-480B-B6DD-2E49B1A462CD[13618] (UIKitApplication:com.stage.Mobile[169b][rb-legacy][13825]): Service exited due to SIGILL | sent by exc handler[13825]
> 
> This looks like a bug in the app itself. Check it with your developer
> 
> > [debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {
> > [debug] [BaseDriver]   "app": "/Users/macbookpro/eclipse-workspace/iosdemo/src/test/java/Mobile Stage.app",
> > [debug] [BaseDriver]   "noReset": "True",
> > [debug] [BaseDriver]   "platformVersion": "14.2",
> > [debug] [BaseDriver]   "automationName": "XCuiTest",
> > [debug] [BaseDriver]   "platformName": "IOS",
> > [debug] [BaseDriver]   "deviceName": "iPhone 12 Pro Max"
> > [debug] [BaseDriver] }
> 
> * Providing noReset means the app should be already installed and running on the device
> * noReset must be boolean, not string
> * The requested capabilities are still not set

The requested capabilities are still not set <<<  what do you mean about this? do I missing some parameters ?

**Comment by mykola-mokhnach** [comment]
> I have one question, if app has bug, why I am able to open app manually on simulator, by drag and drop ? P.S this is happening when I perform "Erase All Content and Settings...." on simulator

No idea. Like I said, check the app logs with your developer.

> what do you mean about this? do I missing some parameters ?

yes, I've asked to enable `showIOSLog` and `showXcodeLog` capabilities above

**Comment by levank707** [comment]
> > I have one question, if app has bug, why I am able to open app manually on simulator, by drag and drop ? P.S this is happening when I perform "Erase All Content and Settings...." on simulator
> 
> No idea. Like I said, check the app logs with your developer.
> 
> > what do you mean about this? do I missing some parameters ?
> 
> yes, I've asked to enable `showIOSLog` and `showXcodeLog` capabilities above

desiredCapabilities.setCapability("showIOSLog", "true");
desiredCapabilities.setCapability("showXcodeLog", "true");

this ?

**Comment by levank707** [comment]
> > I have one question, if app has bug, why I am able to open app manually on simulator, by drag and drop ? P.S this is happening when I perform "Erase All Content and Settings...." on simulator
> 
> No idea. Like I said, check the app logs with your developer.
> 
> > what do you mean about this? do I missing some parameters ?
> 
> yes, I've asked to enable `showIOSLog` and `showXcodeLog` capabilities above

https://gist.github.com/levank707/5ac4c0ffea5d2129a7eefd09e9f4026e here is the IOS and Xcode logs

**Comment by levank707** [comment]
> > I have one question, if app has bug, why I am able to open app manually on simulator, by drag and drop ? P.S this is happening when I perform "Erase All Content and Settings...." on simulator
> 
> No idea. Like I said, check the app logs with your developer.
> 
> > what do you mean about this? do I missing some parameters ?
> 
> yes, I've asked to enable `showIOSLog` and `showXcodeLog` capabilities above

I just add this 2 logs  here is it  https://gist.github.com/levank707/ed64441dcdcd5148beb8e101a3139756

**Comment by mykola-mokhnach** [comment]
The detailed log confirms the same thing about the application crash (SIGILL). Closed as not an issue.
