### ISSUE TITLE
Not able to launch appium inspector on Big sur

### ISSUE THREAD

**Issue by rajudevolla** [appium/appium#14972]
## The problem

on Big sur os, i am trying to start coding for my appium for ios test cases, i am unable to lauch appium inspector session. Getting error for webdriver agent.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.19.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac Big Sur 11.0.1
* Node.js version (unless using Appium.app|exe): 
* Npm or Yarn package manager: 6.14.5
* Mobile platform/version under test: iOS 14.3
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: appium.app

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

<script src="https://gist.github.com/rajudevolla/ac0c74a7d4a9ddf6acb1fc354fda238b.js"></script>

[log_xcresult.zip](https://github.com/appium/appium/files/5738324/log_xcresult.zip)

## Code To Reproduce Issue [ Good To Have ]

Just launch Appium.app on Big sur mac OS. Try to launch inpsector session on iOS 14.3 iphone 11.  Following capabilities are used to launch session.
{
  "platformName": "iOS",
  "deviceName": "iPhone 11",
  "platformVersion": "14.3",
  "app": "/Users/apple_hydstp/Downloads/Learning 2.app"
}

**Comment by KazuCocoa** [comment]
Duplicated of https://github.com/appium/appium/issues/14952

>  "platformVersion": "14.3",

You can try out AD 1.12 beta https://github.com/appium/appium/issues/14952#issuecomment-747990982
