### ISSUE TITLE
getting an error while testing the android application in appium

### ISSUE THREAD

**Issue by omar-666** [appium/appium#14987]
Hello, I am new to appium and i am trying to test my app using appium, after setting the environment variables to their destination and setting up all things i am getting this error message.An unknown server-side error occurred while processing the command. Original error: Cannot verify the signature of '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.15.0.apk'. Original error: Command '/Library/Java/JavaVirtualMachines/jdk-12.0.2.jdk/contents/Home/bin/bin/java' not found. Is it installed?

## Environment

* Desktop OS/version used to run Appium: Mac OS High Sierra
* Node.js version (unless using Appium.app|exe): v12.18.3
* Mobile platform/version under test: Android 8.1 
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: exe

## Details

please help, I think this is not a big issue as i am new to appium thats why it took a lot of my time.

Environment variables path (set in configuration setting): ANDROID_HOME = /Users/myuser/Library/Android/sdk
JAVA_HOME = /Library/Java/JavaVirtualMachines/jdk-12.0.2.jdk/contents/Home/bin

**Comment by mykola-mokhnach** [comment]
The error is expected. JAVA_HOME must be pointing to the `Home` root, not `bin`
