### ISSUE TITLE
why when appium inspect ios app in different mobile，the Page structure will change

### ISSUE THREAD

**Issue by leeyc0704** [appium/appium#14981]
## The problem
the same element in different mobile，the XCUIElement structure and order will change，bellow for example, any way to solve it ? thanks!

## Environment

* Appium version (or git revision) that exhibits the issue:1.20
* Desktop OS/version used to run Appium: macOS
* Mobile platform/version under test:10.3.3  or 12.2 or 13.3
* Real device or emulator/simulator:real device ip6sp ip6s
* Appium CLI or Appium.app|exe:all

## Details
like bellow element, in fact it's the same location in different mobile（ip6s and ip6sp）,i want to get element " i know 1"
use chain , first is **/XCUIElementTypeOther/XCUIElementTypeButton[1]
second is **/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeButton[2]
the structure and order are all change , because my project has many elements, i can't use IOS_PREDICATE or the chain writing of absolute path to get element,i only can get element by ioschain use index, but the problem occur

```
<XCUIElementTypeWindow>
  <XCUIElementTypeOther>
  <XCUIElementTypeOther>
    <XCUIElementTypeStaticText name="">
  <XCUIElementTypeOther>
    <XCUIElementTypeButton name="i know 1">
    <XCUIElementTypeButton name="i know 2">
```

```
<XCUIElementTypeWindow>
  <XCUIElementTypeOther>
    <XCUIElementTypeOther>
      <XCUIElementTypeOther>
        <XCUIElementTypeOther>
          <XCUIElementTypeStaticText name="">
        <XCUIElementTypeOther>
          <XCUIElementTypeButton name=""i know 2>
          <XCUIElementTypeButton name=""i know 1">
```

**Comment by mykola-mokhnach** [comment]
The page tree is generated by XCTest. Please report the issue to Apple as we cannot do nothing about it from Appium side.
