### ISSUE TITLE
Application opens and than it is closing immediately (Real Device, IOS)

### ISSUE THREAD

**Issue by levank707** [appium/appium#14986]
## The problem

mobile application (.ipa file) was installed successfully on the device but when the webdriveragent tried to open it, it was closing immediately, and again. until server was on

## Environment

* Appium version (or git revision) that exhibits the issue:1.19.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macos big sur 11.1
* Node.js version (unless using Appium.app|exe):v 15.4.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: ios 14.2
* Real device or emulator/simulator: real device (iphone XR)
* Appium CLI or Appium.app|exe: both

## Details

mobile application (.ipa file)  was installed successfully on the device but when the webdriveragent tried to open it, it was closing immediately,  and again. until server was on 

## Link to Appium logs

https://gist.github.com/levank707/4308eef4bac3b0bf39e2b51367bf1e82

**Comment by KazuCocoa** [comment]
Probably the app process exited `[IOSDeviceLog] Jan  1 02:24:35 Test-iPhone1 SpringBoard(SpringBoard)[59] <Notice>: Process exited: <FBApplicationProcess: 0x117dc4d10; application<com.stage.Mobile>:369(v3F9)> -> <RBSProcessExitContext| specific, status:<RBSProcessExitStatus| domain:signal(2) code:SIGTRAP(5)>>` by some reasons.

```
...
[IOSDeviceLog] Jan  1 02:24:35 Test-iPhone1 SpringBoard(UserNotificationsServer)[59] <Notice>: [com.stage.Mobile] com.stage.Mobile application state changed to Terminated
[IOSDeviceLog] Jan  1 02:24:35 Test-iPhone1 SpringBoard(UserNotificationsServer)[59] <Notice>: [com.stage.Mobile] Ignore becoming background for application without push registration
[IOSDeviceLog] Jan  1 02:24:35 Test-iPhone1 SpringBoard(SpringBoard)[59] <Notice>: didSelectKeyboardFocusProcess:(null) token:(null)
[IOSDeviceLog] Jan  1 02:24:35 Test-iPhone1 SpringBoard(SpringBoard)[59] <Notice>: updateKeyboardFocusDeferringRules: SpringBoard gets focus for reasons:(noKeyboardFocusProcess)
[IOSDeviceLog] Jan  1 02:24:35 Test-iPhone1 SpringBoard(SpringBoard)[59] <Notice>: Process exited: <FBApplicationProcess: 0x117dc4d10; application<com.stage.Mobile>:369(v3F9)> -> <RBSProcessExitContext| specific, status:<RBSProcessExitStatus| domain:signal(2) code:SIGTRAP(5)>>
[IOSDeviceLog] Jan  1 02:24:35 Test-iPhone1 SpringBoard(SpringBoard)[59] <Notice>: reconfigured lock button: <SBMutableHardwareButtonGestureParameters: 0x2829a3840; maximumPressCount: 2; longPressTimeInterval: 0.40s; multiplePressTimeInterval: 0.40s>
[IOSDeviceLog] Jan  1 02:24:35 Test-iPhone1 SpringBoard(SpringBoard)[59] <Notice>: Application process state changed for com.stage.Mobile: (null)

...


[IOSDeviceLog] Jan  1 02:24:35 Test-iPhone1 locationd[65] <Notice>: {"msg":"#CLIUA Marking change", "clientKey":"com.stage.Mobile", "reason":"Process state from RunningBoard", "assertionLevel":5, "coming":0}

...
...

[IOSDeviceLog] Jan  1 02:24:35 Test-iPhone1 duetexpertd(AppPredictionClient)[232] <Notice>: Finished updating recently engaged cache for client model with id: atx_heuristics
[IOSDeviceLog] Jan  1 02:24:35 Test-iPhone1 symptomsd(SymptomEvaluator)[118] <Notice>: com.stage.Mobile: Foreground: false
[IOSDeviceLog] Jan  1 02:24:35 Test-iPhone1 symptomsd(SymptomEvaluator)[118] <Notice>: call _saveAndUnloadSelectState on com.stage.Mobile exiting foreground state
...
...
[WD Proxy] Got response with status 400: {"value":{"error":"invalid element state","message":"The application under test with bundle id 'com.stage.Mobile' is not running, possibly crashed","traceback":"(\n\t0   CoreFoundation                      0x000000019932888c AF3F8E01-C130-3464-AD40-C5532D273483 + 1202316\n\t1   libobjc.A.dylib                     0x00000001ad87ec50 objc_exception_throw + 60\n\t2   CoreFoundation                      0x00000001992305c8 AF3F8E01-C130-3464-AD40-C5532D273483 + 185800\n\t3   WebDriverAgentLib                   0x00000001096f1430 -[FBSession activeApplication] + 672\n\t4   WebDriverAgentLib                   0x00000001096fd294 +[FBSessionCommands currentCapabilities] + 96\n\t5   WebDriverAgentLib                   0x00000001096fd184 +[FBSessionCommands sessionInformation] + 264\n\t6   WebDriverAgentLib                   0x00000001096fa6b8 +[FBSessionCommands handleCreateSession:] + 2444\n\t7   WebDriverAgentLib                   0x00000001096cf0b0 -[FBRoute_TargetAction mountRequest:intoResponse:] + 212\n\t8...
[debug] [W3C] Matched W3C error code 'invalid element state' to InvalidElementStateError
[debug] [XCUITest] Failed to create WDA session (The application under test with bundle id 'com.stage.Mobile' is not running, possibly crashed). Retrying...
[Xcode]     t =     7.77s Unable to monitor event loop
[Xcode] 
...
```

WDA launches the app via https://developer.apple.com/documentation/xctest/xcuiapplication/1500467-launch at the end, so probably your app got something issue in the launching process by XCTest.

**Comment by levank707** [comment]
> Probably the app process exited `[IOSDeviceLog] Jan 1 02:24:35 Test-iPhone1 SpringBoard(SpringBoard)[59] <Notice>: Process exited: <FBApplicationProcess: 0x117dc4d10; application<com.stage.Mobile>:369(v3F9)> -> <RBSProcessExitContext| specific, status:<RBSProcessExitStatus| domain:signal(2) code:SIGTRAP(5)>>` by some reasons.
> 
> ```
> ...
> [IOSDeviceLog] Jan  1 02:24:35 Test-iPhone1 SpringBoard(UserNotificationsServer)[59] <Notice>: [com.stage.Mobile] com.stage.Mobile application state changed to Terminated
> [IOSDeviceLog] Jan  1 02:24:35 Test-iPhone1 SpringBoard(UserNotificationsServer)[59] <Notice>: [com.stage.Mobile] Ignore becoming background for application without push registration
> [IOSDeviceLog] Jan  1 02:24:35 Test-iPhone1 SpringBoard(SpringBoard)[59] <Notice>: didSelectKeyboardFocusProcess:(null) token:(null)
> [IOSDeviceLog] Jan  1 02:24:35 Test-iPhone1 SpringBoard(SpringBoard)[59] <Notice>: updateKeyboardFocusDeferringRules: SpringBoard gets focus for reasons:(noKeyboardFocusProcess)
> [IOSDeviceLog] Jan  1 02:24:35 Test-iPhone1 SpringBoard(SpringBoard)[59] <Notice>: Process exited: <FBApplicationProcess: 0x117dc4d10; application<com.stage.Mobile>:369(v3F9)> -> <RBSProcessExitContext| specific, status:<RBSProcessExitStatus| domain:signal(2) code:SIGTRAP(5)>>
> [IOSDeviceLog] Jan  1 02:24:35 Test-iPhone1 SpringBoard(SpringBoard)[59] <Notice>: reconfigured lock button: <SBMutableHardwareButtonGestureParameters: 0x2829a3840; maximumPressCount: 2; longPressTimeInterval: 0.40s; multiplePressTimeInterval: 0.40s>
> [IOSDeviceLog] Jan  1 02:24:35 Test-iPhone1 SpringBoard(SpringBoard)[59] <Notice>: Application process state changed for com.stage.Mobile: (null)
> 
> ...
> 
> 
> [IOSDeviceLog] Jan  1 02:24:35 Test-iPhone1 locationd[65] <Notice>: {"msg":"#CLIUA Marking change", "clientKey":"com.stage.Mobile", "reason":"Process state from RunningBoard", "assertionLevel":5, "coming":0}
> 
> ...
> ...
> 
> [IOSDeviceLog] Jan  1 02:24:35 Test-iPhone1 duetexpertd(AppPredictionClient)[232] <Notice>: Finished updating recently engaged cache for client model with id: atx_heuristics
> [IOSDeviceLog] Jan  1 02:24:35 Test-iPhone1 symptomsd(SymptomEvaluator)[118] <Notice>: com.stage.Mobile: Foreground: false
> [IOSDeviceLog] Jan  1 02:24:35 Test-iPhone1 symptomsd(SymptomEvaluator)[118] <Notice>: call _saveAndUnloadSelectState on com.stage.Mobile exiting foreground state
> ...
> ...
> [WD Proxy] Got response with status 400: {"value":{"error":"invalid element state","message":"The application under test with bundle id 'com.stage.Mobile' is not running, possibly crashed","traceback":"(\n\t0   CoreFoundation                      0x000000019932888c AF3F8E01-C130-3464-AD40-C5532D273483 + 1202316\n\t1   libobjc.A.dylib                     0x00000001ad87ec50 objc_exception_throw + 60\n\t2   CoreFoundation                      0x00000001992305c8 AF3F8E01-C130-3464-AD40-C5532D273483 + 185800\n\t3   WebDriverAgentLib                   0x00000001096f1430 -[FBSession activeApplication] + 672\n\t4   WebDriverAgentLib                   0x00000001096fd294 +[FBSessionCommands currentCapabilities] + 96\n\t5   WebDriverAgentLib                   0x00000001096fd184 +[FBSessionCommands sessionInformation] + 264\n\t6   WebDriverAgentLib                   0x00000001096fa6b8 +[FBSessionCommands handleCreateSession:] + 2444\n\t7   WebDriverAgentLib                   0x00000001096cf0b0 -[FBRoute_TargetAction mountRequest:intoResponse:] + 212\n\t8...
> [debug] [W3C] Matched W3C error code 'invalid element state' to InvalidElementStateError
> [debug] [XCUITest] Failed to create WDA session (The application under test with bundle id 'com.stage.Mobile' is not running, possibly crashed). Retrying...
> [Xcode]     t =     7.77s Unable to monitor event loop
> [Xcode] 
> ...
> ```
> 
> WDA launches the app via https://developer.apple.com/documentation/xctest/xcuiapplication/1500467-launch at the end, so probably your app got something issue in the launching process by XCTest.


First of all thanks for your response.

I tried to install and open application(.ipa) manually without WDA , on the device and it was launched successfully. 

I also tried to open (.app) file on the emulator with WDA and it was same as was on the real device, it's opening and closing  immediately.  but, manually  without WDA it is opening successfully also. 

So, When WDA is trying to open app, there is  some problem with it.  and I don'h have no idea what is that :(

**Comment by KazuCocoa** [comment]
Who about launching your app via vanilla XCTest?
https://gist.github.com/KazuCocoa/e90738298d8409bb0acbf44720a44f0b is an example to launch it.
This `app.launch()` is the same as WDA does https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/WebDriverAgentLib/Routing/FBSession.m#L204

**Comment by levank707** [comment]
> Who about launching your app via vanilla XCTest?
> https://gist.github.com/KazuCocoa/e90738298d8409bb0acbf44720a44f0b is an example to launch it.
> This `app.launch()` is the same as WDA does https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/WebDriverAgentLib/Routing/FBSession.m#L204 basically.

hmm. sorry but i don't get it how to make it with apium has support with XCTest?  , I should directly path XCTest in the  run application method ?

**Comment by KazuCocoa** [comment]
XCTest is the background of Appium (XCUITest driver).

I mean you can create a new XCTest(UI) project and launch your installed app via it as my attached one. Then, you can ensure if the `.launch()` command works. If the same situation happens, you should debug your app under test with your developer.

**Comment by KazuCocoa** [comment]
ah, or waitForIdleTimeout and animationCoolOffTimeout (available since next release) will help for this if the app under test hasn't idle. But I'd try the `.launch()` first.

**Comment by levank707** [comment]
> ah, or waitForIdleTimeout (available since next release) will help for this if the app under test hasn't idle. `waitForQuiescence: false` (already available) also could help. But I'd try the `.launch()` first since your log had an exit status code, so probably something happened in the app process.

**Comment by levank707** [comment]
> XCTest is the background of Appium (XCUITest driver).
> 
> I mean you can create a new XCTest(UI) project and launch your installed app via it as my attached one. Then, you can ensure if the `.launch()` command works. If the same situation happens, you should debug your app under test with your developer.

okay but, i don't know how to create new CXTest project and then launch my .ipa or .app file. so, I'll    do some research in the internet , hope soon I'll figure how to make it. man thank you very much for your attention.

**Comment by mykola-mokhnach** [comment]
Try https://www.hackingwithswift.com/read/39/8/user-interface-testing-with-xctest

Closed as third party issue

**Comment by levank707** [comment]
Guys I forget to say, It was application problem, app was throwing some errors on lunch so developer fixed it and its now everything works properly. thank you for your attention and advices.
