### ISSUE TITLE
Appium fails to find element from audio player while content is playing.

### ISSUE THREAD

**Issue by armartinez** [appium/appium#14989]
## The problem

I'm trying to to automate play back controls in a audio player. When appium tries to find element during playback, it hangs and throw No Such Element Exception. Same works, when the content playback is paused.

## Environment

Appium version (or git revision) that exhibits the issue: 1.18.3
Last Appium version that did not exhibit the issue (if applicable):
Desktop OS/version used to run Appium: Mac OS (Sierra) 11.1
Node.js version (unless using Appium.app|exe): v12.8.4
Mobile platform/version under test: Android 11
Real device or emulator/simulator: emulator
Appium CLI or Appium.app|exe: Appium.app

## Details

This is an extension of this closed issue : https://github.com/appium/appium/issues/8525. I've managed to apply the suggested fix of pausing the playback and get the element's coordinates, but it's not consistent, sometimes the click event takes too long and the driver times out. Is there any more reliable solution, like forcing the driver to not wait for the application to be idle ?

**Comment by mykola-mokhnach** [comment]
Try https://github.com/appium/appium/issues/14594

**Comment by mykola-mokhnach** [comment]
In general, element location is controlled by UiAutomator framework itself. There is nothing we could do from Appium side there

**Comment by armartinez** [comment]
@mykola-mokhnach Thanks, waitforIdle worked perfect !!!
