### ISSUE TITLE
Getting ERROR carthage-wrapper.sh: line 5: python3: command not found AND carthage-wrapper.sh bootstrap --platform iOS\,tvOS' exited with code 127

### ISSUE THREAD

**Issue by bhoomi9488** [appium/appium#14982]
## The problem

I am new to mobile automation. getting below error while trying to run automation using iOS simulator

## Environment

* Appium version (or git revision) that exhibits the issue: I tried with appium 1.17; 1.18(desktop version); 1.19. getting issue in all
* Desktop OS/version used to run Appium: Mac OS Mojave
* Node.js version (unless using Appium.app|exe): 12
* Npm or Yarn package manager: 6.4.1
* Mobile platform/version under test: iOS simulator iPhone x OS 12.4

## Link to Appium logs

https://gist.github.com/bhoomi9488/eb425edcf5f57a56aa372437fafd936c

**Comment by mykola-mokhnach** [comment]
Please make sure python3 is present in [PATH](https://github.com/appium/java-client/blob/master/docs/environment.md) or use appium@beta

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
