### ISSUE TITLE
Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded

### ISSUE THREAD

**Issue by sshock** [appium/appium#14998]
## The problem

Recently I seem to be running into this error while attempting to create an appium driver.  Is there any way to fix this or if not at least configure the timeout setting?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.19.0
* Last Appium version that did not exhibit the issue (if applicable): 1.18.2 (probably)
* Desktop OS/version used to run Appium: Ubuntu 18.04
* Node.js version (unless using Appium.app|exe): 10.22.0
* Npm or Yarn package manager: npm 6.14.8
* Mobile platform/version under test: android
* Real device or emulator/simulator: real
* Appium CLI or Appium.app|exe: cli

## Details

I'm not sure why it is happening but I believe appium is somehow in a bad state.  I ran into the error 52 times on one server but it only shows up twice in the appium log.  In the log it shows up as occurring while trying to delete a session, but I believe it is primarily occurring when trying to create a session / start the driver.

## Link to Appium logs

https://gist.github.com/sshock/ae34c717c1b9c555069a826a730d28be

**Comment by mykola-mokhnach** [comment]
240 000 ms  is the default read timeout for the Appium proxy. Currently it is not configurable

**Comment by sshock** [comment]
I'm still curious how appium got into a bad state, but luckily this has only happened on this one occasion afaik and that is after using appium for at least two years, so unless something changed recently like in version 1.19.0, maybe it was just an unlucky fluke.

If support is added to make it configurable, that will be useful to me, thanks!

**Comment by mykola-mokhnach** [comment]
The `uiautomator2ServerReadTimeout ` has been added to appium@beta

**Comment by sshock** [comment]
> The `uiautomator2ServerReadTimeout` capability has been added to appium@beta

Sweet, thanks!

**Comment by vzenzo** [comment]
This error is happening to me when Appium can't find the elements that are on page, visible and enabled.
It stuck at verification of title (which is text) and breaks, it worked fine in v1.18 on Android now on 1.20 it doesn't work at all

**Comment by ammaramja** [comment]
I'm facing the same error when trying to do a context switch from Native to the web on v1.20

**Comment by EoinGorman** [comment]
> I'm facing the same error when trying to do a context switch from Native to the web on v1.20

I'm facing this exact same issue. (Happening on appiums version 1.17 all the way to (and including) 1.20.2)
Setting `uiautomator2ServerReadTimeout` making no difference.

**Comment by sjrjanardhana** [comment]
Facing the same issue with 1.20.2

**Comment by cuongnguyen4285** [comment]
I also face the same issue on 1.23.0. A big thank to who can fix this issue.

**Comment by debasisj** [comment]
has this been fixed? I just used to latest `Appium 2.0.0-beta.56` but still getting the same error .. the `uiautomator2ServerReadTimeout` does not help neither killing Appium servers or uninstalling Appium on the devices 

here is another thread in SOF but seems not helping !! https://stackoverflow.com/questions/65649433/appium-unknownerror-an-unknown-server-side-error-occurred-while-processing-the

**Comment by Jitu1888** [comment]
This one is a permission issue. on some phones, you need to give permission to run in the background.

**Comment by adrianburkard** [comment]
> 

This was exactly the issue I was facing with a Huawei mate 20 pro device. Since Huawei by default handles permissions to start and run apps in the background quite strictly, meaning they do not allow starting in the background for a lot of apps by default (for energy saving reasons I guess). I always run into the 240000 ms timeout because the appium server couldn't proxy the command to the device since the appium client on the device never started. 

Solution for this is on Huawei phones:
1. Open the Optimizer App
2. Touch the Battery icon
3. Find and touch App launch
4. Search for appium in the search bar
5. Toggle off the switch next to the three appium apps (Appium Settings, io.appium.uiautomator2.server, io.appium.uiautomator2.server.test)
6. Make sure all three buttons are toggled (auto-launch, secondary launch, run in background)

Here's the Huawei guide for doing it.
https://consumer.huawei.com/my/support/content/en-gb00778689/

This fixed it for me.

**Comment by 5akda** [comment]
> > This one is a permission issue. on some phones, you need to give permission to run in the background.
> 
> This was exactly the issue I was facing with a Huawei mate 20 pro device. Since Huawei by default handles permissions to start and run apps in the background quite strictly, meaning they do not allow starting in the background for a lot of apps by default (for energy saving reasons I guess). I always run into the 240000 ms timeout because the appium server couldn't proxy the command to the device since the appium client on the device never started.
> 
> Solution for this is on Huawei phones:
> 
> 1. Open the Optimizer App
> 2. Touch the Battery icon
> 3. Find and touch App launch
> 4. Search for appium in the search bar
> 5. Toggle off the switch next to the three appium apps (Appium Settings, io.appium.uiautomator2.server, io.appium.uiautomator2.server.test)
> 6. Make sure all three buttons are toggled (auto-launch, secondary launch, run in background)
> 
> Here's the Huawei guide for doing it. https://consumer.huawei.com/my/support/content/en-gb00778689/
> 
> This fixed it for me.

This is what I was looking for!
Thanks a million!

**Comment by vadimnakonechny** [comment]
Hello, this happened to me while testing iOS

**Comment by pseidonims** [comment]
> Hello, this happened to me while testing iOS, how is that possible?

I have the same issue on iOS simulator (iOS 17.0).

**Comment by tking16** [comment]
Yep this has started happening to me too on iOS Appium v: 2.4.1, XCUITest version: 6.2.0

**Comment by saifulsahim** [comment]
> > This one is a permission issue. on some phones, you need to give permission to run in the background.
> 
> This was exactly the issue I was facing with a Huawei mate 20 pro device. Since Huawei by default handles permissions to start and run apps in the background quite strictly, meaning they do not allow starting in the background for a lot of apps by default (for energy saving reasons I guess). I always run into the 240000 ms timeout because the appium server couldn't proxy the command to the device since the appium client on the device never started.
> 
> Solution for this is on Huawei phones:
> 
> 1. Open the Optimizer App
> 2. Touch the Battery icon
> 3. Find and touch App launch
> 4. Search for appium in the search bar
> 5. Toggle off the switch next to the three appium apps (Appium Settings, io.appium.uiautomator2.server, io.appium.uiautomator2.server.test)
> 6. Make sure all three buttons are toggled (auto-launch, secondary launch, run in background)
> 
> Here's the Huawei guide for doing it. https://consumer.huawei.com/my/support/content/en-gb00778689/
> 
> This fixed it for me.

Thanks a lot

**Comment by banukiran1997** [comment]
> > > This one is a permission issue. on some phones, you need to give permission to run in the background.
> > 
> > 
> > This was exactly the issue I was facing with a Huawei mate 20 pro device. Since Huawei by default handles permissions to start and run apps in the background quite strictly, meaning they do not allow starting in the background for a lot of apps by default (for energy saving reasons I guess). I always run into the 240000 ms timeout because the appium server couldn't proxy the command to the device since the appium client on the device never started.
> > Solution for this is on Huawei phones:
> > 
> > 1. Open the Optimizer App
> > 2. Touch the Battery icon
> > 3. Find and touch App launch
> > 4. Search for appium in the search bar
> > 5. Toggle off the switch next to the three appium apps (Appium Settings, io.appium.uiautomator2.server, io.appium.uiautomator2.server.test)
> > 6. Make sure all three buttons are toggled (auto-launch, secondary launch, run in background)
> > 
> > Here's the Huawei guide for doing it. https://consumer.huawei.com/my/support/content/en-gb00778689/
> > This fixed it for me.
> 
> Thanks a lot



getting the same issue [Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded] in oppo a3x android phone aswell can anyone help me out here.
