### ISSUE TITLE
--version no longer works in Appium 2.0

### ISSUE THREAD

**Issue by olafure** [appium/appium#14994]
--version option seems to have been removed in appium@2.0.0-beta.6

$ npm install -g appium@2.0.0-beta.6
$ appium --version 
usage: appium server [-h] [-ah APPIUMHOME] [--log-filters LOGFILTERS]
                     [--shell] [--plugins PLUGINS] [--allow-cors] [--reboot]
                     [-a ADDRESS] [-p PORT] [-pa BASEPATH]
                     [-ca CALLBACKADDRESS] [-cp CALLBACKPORT]
                     [--session-override] [-g LOGFILE]
                     [--log-level {info,info:debug,info:info,info:warn,info:error,warn,warn:debug,warn:info,warn:warn,warn:error,error,error:debug,error:info,error:warn,error:error,debug,debug:debug,debug:info,debug:warn,debug:error}]
                     [--log-timestamp] [--local-timezone] [--log-no-colors]
                     [-G WEBHOOK] [--nodeconfig NODECONFIG]
                     [--chromedriver-port CHROMEDRIVERPORT]
                     [--chromedriver-executable CHROMEDRIVEREXECUTABLE]
                     [--show-config] [--no-perms-check] [--strict-caps]
                     [--tmp TMPDIR] [--trace-dir TRACEDIR]
                     [--debug-log-spacing] [--suppress-adb-kill-server]
                     [--long-stacktrace]
                     [--webkit-debug-proxy-port WEBKITDEBUGPROXYPORT]
                     [--webdriveragent-port WDALOCALPORT]
                     [-dc DEFAULTCAPABILITIES] [--relaxed-security]
                     [--allow-insecure ALLOWINSECURE]
                     [--deny-insecure DENYINSECURE]
                     
appium server: error: Unrecognized arguments: --version.

**Comment by KazuCocoa** [comment]
How about `appium -v`?

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by olafure** [comment]
I believe this might have been closed in error. 
The --version option is pretty standard and Appium 1.19 does have it. Removing it from Appium is bound to break quite a few CI pipelines when they verify the Appium version/availability.

For the record, -v doesn't work either.

**Comment by KazuCocoa** [comment]
How about with 1.20.0? I just quickly checked as below after re-installing appium with `-g` option:

```
 % appium -v
1.20.0
% appium --version
1.20.0
```

**Comment by mykola-mokhnach** [comment]
@KazuCocoa It looks like there was an issue while porting the argparse changes to Appium 2.0
Appium 1 works properly though

**Comment by KazuCocoa** [comment]
I see. > 2.0

**Comment by KazuCocoa** [comment]
appium@2.0.0-beta.7 should work.
