### ISSUE TITLE
InvalidElementStateException thrown after clicking via TouchAction

### ISSUE THREAD

**Issue by VitorJeremias** [appium/appium#14990]
## The problem

The app I'm testing shows a message popup. I need to close it by clicking outside the panel. I'm trying to use a `new TouchAction((PerformsTouchActions) driver.getAndroidDriver())`. It actually clicks and closes the popup, but then throws an exception right after it.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.18.3
* Desktop OS/version used to run Appium: Linux Mint 20 Cinnamon 
* Node.js version (unless using Appium.app|exe): v10.19.0
* Mobile platform/version under test: Android 9
* Real device or emulator/simulator: Emulator

## Details
The app goes into the expected state after performing the click (it closes the popup), but still throws an exception: `org.openqa.selenium.InvalidElementStateException: Tap at [x=406.0, y=549.0] has failed`

## Link to Appium logs
https://gist.github.com/VitorJeremias/ea7eab85c9a4b31389c0a78ec81efa92

## Code To Reproduce Issue [ Good To Have ]
https://gist.github.com/VitorJeremias/f14dc07fcc6142fcb2f2212bde29cce8

**Comment by mykola-mokhnach** [comment]
This exception is thrown if UiAutomator returns false in response to click action: https://github.com/appium/appium-uiautomator2-server/blob/33f7a10acc2d89d8082cc680365cdf991f8d496c/app/src/main/java/io/appium/uiautomator2/handler/Tap.java#L65

Please report it to Google if you think this is a bug.

Consider switching to W3C actions as a possible workaround.

**Comment by VitorJeremias** [comment]
W3C actions worked just fine, thank you @mykola-mokhnach !
