### ISSUE TITLE
The capbility 'simulatorStartupTimeout' is NOT working

### ISSUE THREAD

**Issue by scnymc-shaxian** [appium/appium#14997]
## The problem

My old mac took a long time to boot a simulator (More than 2 minutes), so I add the capabilities 'simulatorStartupTimeout' and set the value to '240000', but seems like that the capabilities doesn't work, I still got the error message: "_The simulator 6C36049E-A5DB-464F-920A-774851AF191B has failed to finish booting after 120s. Original status: Monitoring boot status for iPhoneMax (6C36049E-A5DB-464F-920A-774851AF191B)_".

My java code is the following:
```
import io.appium.java_client.AppiumDriver;   
import io.appium.java_client.ios.IOSDriver;   
import io.appium.java_client.remote.IOSMobileCapabilityType;   
import io.appium.java_client.remote.MobileCapabilityType;   
import org.openqa.selenium.WebDriver;   
import org.openqa.selenium.WebElement;   
import org.openqa.selenium.remote.DesiredCapabilities; 
...   
DesiredCapabilities capabilities = new DesiredCapabilities();   
capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");
...
capabilities.setCapability("simulatorStartupTimeout",240000);
//Also try adding the prefix 'appium'
//capabilities.setCapability("appium:simulatorStartupTimeout",240000); 
...
```
Any mistakes? 

## Environment

* Appium version : v1.20.0
* Desktop OS/version used to run Appium: Mac OS 11.1
* Node.js version (unless using Appium.app|exe): v10.6.0
* Npm or Yarn package manager: v6.13.1
* Mobile platform/version under test: iOS 14.3
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: java-client 7.4.0

## Link to Appium logs
[appiumLog](https://github.com/scnymc-shaxian/appiumLog/blob/main/appium_4723.log)

**Comment by mykola-mokhnach** [comment]
This is happening because of fullReset is enabled, although this timeout was never working before as well in such scenario. It needs to be added to appium-ios-driver component.

**Comment by mykola-mokhnach** [comment]
Published the improvement to appium@beta

**Comment by scnymc-shaxian** [comment]
It works! Verified on the same scenario with appium@beta (1.20.0-beta.0).
