### ISSUE TITLE
adb install timing out on Android parallel run with Appium 1.19.1

### ISSUE THREAD

**Issue by shaneqa** [appium/appium#15001]
## The problem

adb install timing out on Android parallel run.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.19.1
* Last Appium version that did not exhibit the issue (if applicable): 1.16.0
* Desktop OS/version used to run Appium: macOS Catalina
* Node.js version (unless using Appium.app|exe): v12.20.1
* Npm or Yarn package manager: 6.14.10
* Mobile platform/version under test: Android 9.0.  Android Emulator 30.3.5. Android SDK Platform-Tools 30.0.5 
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Our setup in CI spins up a new Appium server and emulator on unique ports for each set of tests.  On a single Machine there can be up to 4 concurrent CI jobs running in parallel.  This has been working fine with Appium 1.16.0 but since we have upgraded to Appium 1.19.1 we keep experiencing timeouts on some of the adb installs of the apk under test.

`[debug] [35m[W3C][39m Encountered internal error running command: Error executing adbExec. Original error: 'Command '/Users/ssmart/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5556 install -r -g /Users/ssmart/cilocalrun2/apk/testLink-debug.apk' timed out after 240000ms'. Try to increase the 240000ms adb execution timeout represented by 'androidInstallTimeout' capability
[debug] [35m[W3C][39m Error: Command '/Users/ssmart/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5556 install -r -g /Users/ssmart/cilocalrun2/apk/testLink-debug.apk' timed out after 240000ms
[debug] [35m[W3C][39m     at Timeout._onTimeout (/Users/ssmart/.nvm/versions/node/v12.20.1/lib/node_modules/appium/node_modules/teen_process/lib/exec.js:125:19)
[debug] [35m[W3C][39m     at listOnTimeout (internal/timers.js:554:17)
[debug] [35m[W3C][39m     at processTimers (internal/timers.js:497:7)
[debug] [35m[W3C][39m Destroying socket connection`

We have increased the timeout of the 'androidInstallTimeout' capability but any amount of timeout still results in a failure.  I assume that the other parallel executions are interfering with adb now, which they didn't before.

What is interesting is that the next test in the run might go on to succeed after the one with the timeout has failed.  So the emulator is in a usable state.

I'm pretty sure it is an issue with Appium that has been introduced, as the exact same setup (i.e. same tests, same apk, same emulators) works fine with Appium version 1.16.0.

## Link to Appium logs

https://gist.github.com/shaneqa/582170efd92d320593bd6206383b2f2f

## Code To Reproduce Issue [ Good To Have ]

No sample code yet

**Comment by mykola-mokhnach** [comment]
I don't know what could be done there from Appium side. The adb command being executed for app install is correct.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
