### ISSUE TITLE
appium(uiautomator2) got wrong location of element.

### ISSUE THREAD

**Issue by HavenChen** [appium/appium#15004]
## The problem

I have an element at location {'x': 888, 'y': 1776}, after i scrolling the current page up, the location of the element should be upper than before, like {'x': 888, 'y': 800}. but i got the same location values as before({'x': 888, 'y': 1776}). 
This phonomenon just occured in specific device.

I was wondering if you have ever met this kind of issue before.

Thanks.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: windows 10
* Node.js version (unless using Appium.app|exe): 
* Npm or Yarn package manager:
* Mobile platform/version under test: Android 6.0 
* Real device or emulator/simulator: Real devices Model: Vivo x 6
* Appium CLI or Appium.app|exe:

**Comment by mykola-mokhnach** [comment]
Try to update the server to the most recent version.
if the issue is still reproducible then try to find element again before retrieving its coordinates.

**Comment by HavenChen** [comment]
Thank you i will try it right now.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
