### ISSUE TITLE
Android - Appium Settings Detected problems with app native libraries

### ISSUE THREAD

**Issue by mnaoumov** [appium/appium#15006]
## The problem

Getting the following error

![error](https://user-images.githubusercontent.com/735878/104060592-cba48800-51ff-11eb-8fab-a76e0253b0d7.jpg)

> Detected problems with app native libraries
> (please consult log for detail):
> libavcodec.so: text relocations
> libavutil.so: text relocations
> libswresample.so: text relocations

## Environment

* Appium version (or git revision) that exhibits the issue: 1.19.1
* Last Appium version that did not exhibit the issue (if applicable): Not sure, but I didn't see it before
* Desktop OS/version used to run Appium: Windows 10 Version 2004 (OS Build 19041.685)
* Node.js version (unless using Appium.app|exe): 12.8.1
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Android 7.1.2
* Real device or emulator/simulator: emulator Bluestacks
* Appium CLI or Appium.app|exe: Appium.NET

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/mnaoumov/ea013091bcbf8690805cd8f360059df5

## Code To Reproduce Issue [ Good To Have ]

Happens for me every time Appium Server connects to the emulator

**Comment by mykola-mokhnach** [comment]
We don't officially support any other emulators beside of the one provided by Google neither run any tests on them. Feel free to provide a patch to the mentioned issue. We'd be happy to merge it.

Closed as third party issue
