### ISSUE TITLE
WebDriverAgent can't get all page source in some apps such as cmb app and boc app

### ISSUE THREAD

**Issue by rillzhang** [appium/appium#15015]
## The problem
wait the wda and iproxy ok,then open link:
http://127.0.0.1:8100/source?format=json
![理财](https://user-images.githubusercontent.com/75115830/104398745-4c5dde00-558a-11eb-884c-85104de574f4.png)
![社区](https://user-images.githubusercontent.com/75115830/104398750-4e27a180-558a-11eb-8043-eaa104c22c08.png)

WebDriverAgent can't get all page source in these pages，just get the bottom labels。
These pages contains webview。

## Environment

Appium version: 1.19.0
Last Appium version that did not exhibit the issue: 1.18.0
Desktop OS/version used to run Appium: macOs catalina 10.15.7
Node.js version: v14.0.0
Npm: 6.14.4
Mobile platform/version under test: ios 12.5
Real device or emulator/simulator:Real device
Appium CLI or Appium.app|exe:Appium CLI

## Link to Appium logs
log:
2021-01-13 13:49:46.931925+0800 WebDriverAgentRunner-Runner[668:159854] Getting the most recent active application (out of 1 total items)
    t =    93.85s Requesting snapshot of accessibility hierarchy for app with pid 544

source:
{
value: {
isEnabled: "1",
isVisible: "1",
frame: "{{0, 0}, {320, 568}}",
children: [
{
isEnabled: "1",
isVisible: "1",
frame: "{{0, 0}, {320, 568}}",
children: [
{
isEnabled: "1",
isVisible: "1",
frame: "{{0, 0}, {320, 568}}",
children: [
{
isEnabled: "1",
isVisible: "1",
frame: "{{0, 0}, {320, 568}}",
children: [
{
isEnabled: "1",
isVisible: "1",
frame: "{{0, 0}, {320, 568}}",
children: [
{
isEnabled: "1",
isVisible: "1",
frame: "{{0, 0}, {320, 568}}",
children: [
{
isEnabled: "1",
isVisible: "1",
frame: "{{0, 0}, {320, 568}}",
children: [
{
isEnabled: "1",
isVisible: "1",
frame: "{{0, 0}, {320, 568}}",
children: [
{
isEnabled: "1",
isVisible: "1",
frame: "{{0, 0}, {320, 568}}",
children: [
{
isEnabled: "1",
isVisible: "1",
frame: "{{0, 0}, {320, 568}}",
children: [
{
isEnabled: "1",
isVisible: "1",
frame: "{{0, 0}, {320, 568}}",
children: [
{
isEnabled: "1",
isVisible: "1",
frame: "{{0, 0}, {320, 568}}",
children: [
{
isEnabled: "1",
isVisible: "1",
frame: "{{0, 0}, {320, 568}}",
children: [
{
isEnabled: "1",
isVisible: "1",
frame: "{{0, 0}, {320, 568}}",
children: [
{
isEnabled: "1",
isVisible: "1",
frame: "{{0, 0}, {320, 568}}",
children: [
{
isEnabled: "1",
isVisible: "1",
frame: "{{0, 0}, {320, 568}}",
rect: {
y: 0,
x: 0,
width: 320,
height: 568
},
value: null,
label: null,
type: "Other",
name: null,
rawIdentifier: null
}
],
rect: {
y: 0,
x: 0,
width: 320,
height: 568
},
value: null,
label: null,
type: "WebView",
name: null,
rawIdentifier: null
}
],
rect: {
y: 0,
x: 0,
width: 320,
height: 568
},
value: null,
label: null,
type: "Other",
name: null,
rawIdentifier: null
}
],
rect: {
y: 0,
x: 0,
width: 320,
height: 568
},
value: null,
label: null,
type: "Other",
name: null,
rawIdentifier: null
}
],
rect: {
y: 0,
x: 0,
width: 320,
height: 568
},
value: null,
label: null,
type: "Other",
name: null,
rawIdentifier: null
}
],
rect: {
y: 0,
x: 0,
width: 320,
height: 568
},
value: null,
label: null,
type: "Other",
name: null,
rawIdentifier: null
}
],
rect: {
y: 0,
x: 0,
width: 320,
height: 568
},
value: null,
label: null,
type: "Other",
name: null,
rawIdentifier: null
}
],
rect: {
y: 0,
x: 0,
width: 320,
height: 568
},
value: null,
label: null,
type: "Other",
name: null,
rawIdentifier: null
}
],
rect: {
y: 0,
x: 0,
width: 320,
height: 568
},
value: null,
label: null,
type: "Other",
name: null,
rawIdentifier: null
}
],
rect: {
y: 0,
x: 0,
width: 320,
height: 568
},
value: null,
label: null,
type: "Other",
name: null,
rawIdentifier: null
},
{
isEnabled: "1",
isVisible: "1",
frame: "{{0, 519}, {320, 49}}",
children: [
{
isEnabled: "1",
isVisible: "0",
frame: "{{0, 519}, {320, 49}}",
rect: {
y: 519,
x: 0,
width: 320,
height: 49
},
value: null,
label: null,
type: "Image",
name: null,
rawIdentifier: null
},
{
isEnabled: "1",
isVisible: "1",
frame: "{{0, 519}, {320, 49}}",
rect: {
y: 519,
x: 0,
width: 320,
height: 49
},
value: null,
label: null,
type: "Other",
name: null,
rawIdentifier: null
},
{
isEnabled: "1",
isVisible: "1",
frame: "{{2, 520}, {60, 48}}",
rect: {
y: 520,
x: 2,
width: 60,
height: 48
},
value: null,
label: "首页",
type: "Button",
name: "首页",
rawIdentifier: null
},
{
isEnabled: "1",
isVisible: "1",
frame: "{{66, 520}, {60, 48}}",
rect: {
y: 520,
x: 66,
width: 60,
height: 48
},
value: "1",
label: "社区",
type: "Button",
name: "社区",
rawIdentifier: null
},
{
isEnabled: "1",
isVisible: "1",
frame: "{{130, 520}, {60, 48}}",
rect: {
y: 520,
x: 130,
width: 60,
height: 48
},
value: null,
label: "理财",
type: "Button",
name: "理财",
rawIdentifier: null
},
{
isEnabled: "1",
isVisible: "1",
frame: "{{194, 520}, {60, 48}}",
rect: {
y: 520,
x: 194,
width: 60,
height: 48
},
value: null,
label: "生活",
type: "Button",
name: "生活",
rawIdentifier: null
},
{
isEnabled: "1",
isVisible: "1",
frame: "{{258, 520}, {60, 48}}",
rect: {
y: 520,
x: 258,
width: 60,
height: 48
},
value: null,
label: "我的",
type: "Button",
name: "我的",
rawIdentifier: null
}
],
rect: {
y: 519,
x: 0,
width: 320,
height: 49
},
value: null,
label: null,
type: "TabBar",
name: null,
rawIdentifier: null
}
],
rect: {
y: 0,
x: 0,
width: 320,
height: 568
},
value: null,
label: null,
type: "Other",
name: null,
rawIdentifier: null
}
],
rect: {
y: 0,
x: 0,
width: 320,
height: 568
},
value: null,
label: null,
type: "Other",
name: null,
rawIdentifier: null
}
],
rect: {
y: 0,
x: 0,
width: 320,
height: 568
},
value: null,
label: null,
type: "Other",
name: null,
rawIdentifier: null
}
],
rect: {
y: 0,
x: 0,
width: 320,
height: 568
},
value: null,
label: null,
type: "Other",
name: null,
rawIdentifier: null
}
],
rect: {
y: 0,
x: 0,
width: 320,
height: 568
},
value: null,
label: null,
type: "Window",
name: null,
rawIdentifier: null
},
{
isEnabled: "1",
isVisible: "0",
frame: "{{0, 0}, {320, 568}}",
children: [
{
isEnabled: "1",
isVisible: "0",
frame: "{{0, 0}, {320, 568}}",
rect: {
y: 0,
x: 0,
width: 320,
height: 568
},
value: null,
label: null,
type: "Other",
name: null,
rawIdentifier: null
}
],
rect: {
y: 0,
x: 0,
width: 320,
height: 568
},
value: null,
label: null,
type: "Window",
name: null,
rawIdentifier: null
},
{
isEnabled: "1",
isVisible: "1",
frame: "{{0, 0}, {320, 568}}",
children: [
{
isEnabled: "1",
isVisible: "1",
frame: "{{0, 0}, {320, 20}}",
children: [
{
isEnabled: "1",
isVisible: "0",
frame: "{{0, 0}, {320, 20}}",
rect: {
y: 0,
x: 0,
width: 320,
height: 20
},
value: null,
label: null,
type: "Other",
name: null,
rawIdentifier: null
},
{
isEnabled: "1",
isVisible: "1",
frame: "{{0, 0}, {320, 20}}",
children: [
{
isEnabled: "1",
isVisible: "1",
frame: "{{6, 0}, {53, 20}}",
rect: {
y: 0,
x: 6,
width: 53,
height: 20
},
value: null,
label: "无 SIM 卡",
type: "Other",
name: "无 SIM 卡",
rawIdentifier: null
},
{
isEnabled: "1",
isVisible: "1",
frame: "{{64, 0}, {15, 20}}",
rect: {
y: 0,
x: 64,
width: 15,
height: 20
},
value: null,
label: "3 格（共 3 格无线局域网信号）",
type: "Other",
name: "3 格（共 3 格无线局域网信号）",
rawIdentifier: null
},
{
isEnabled: "1",
isVisible: "1",
frame: "{{133, 0}, {58, 20}}",
rect: {
y: 0,
x: 133,
width: 58,
height: 20
},
value: null,
label: "上午10:32",
type: "Other",
name: "上午10:32",
rawIdentifier: null
},
{
isEnabled: "1",
isVisible: "1",
frame: "{{230, 0}, {10, 20}}",
rect: {
y: 0,
x: 230,
width: 10,
height: 20
},
value: null,
label: "区域跟踪已打开",
type: "Other",
name: "GeofenceLocationTrackingOn",
rawIdentifier: "GeofenceLocationTrackingOn"
},
{
isEnabled: "1",
isVisible: "1",
frame: "{{246, 0}, {69, 20}}",
rect: {
y: 0,
x: 246,
width: 69,
height: 20
},
value: null,
label: "电池电量：100%, 正在充电",
type: "Other",
name: "电池电量：100%, 正在充电",
rawIdentifier: null
},
{
isEnabled: "1",
isVisible: "0",
frame: "{{246, 0}, {31, 20}}",
rect: {
y: 0,
x: 246,
width: 31,
height: 20
},
value: null,
label: "电池电量：100%",
type: "Other",
name: "电池电量：100%",
rawIdentifier: null
}
],
rect: {
y: 0,
x: 0,
width: 320,
height: 20
},
value: null,
label: null,
type: "Other",
name: null,
rawIdentifier: null
}
],
rect: {
y: 0,
x: 0,
width: 320,
height: 20
},
value: null,
label: null,
type: "StatusBar",
name: null,
rawIdentifier: null
}
],
rect: {
y: 0,
x: 0,
width: 320,
height: 568
},
value: null,
label: null,
type: "Window",
name: null,
rawIdentifier: null
}
],
rect: {
y: 0,
x: 0,
width: 320,
height: 568
},
value: null,
label: "招商银行",
type: "Application",
name: "招商银行",
rawIdentifier: null
},
sessionId: null
}

**Comment by KazuCocoa** [comment]
Probably XCTest framework itself did not get them.
How about `http://127.0.0.1:8100/source?format=description`?

**Comment by mykola-mokhnach** [comment]
Also, please try the most recent server version

**Comment by rillzhang** [comment]
> Probably XCTest framework itself did not get them.
> How about `http://127.0.0.1:8100/source?format=description`?

if use description can get all page source

**Comment by rillzhang** [comment]
> Also, please try the most recent server version

I have updated the latest WebDriverAgent  version , it is no use

**Comment by KazuCocoa** [comment]
Then, probably increasing `snapshotMaxDepth` or `customSnapshotTimeout` could help.
https://appium.io/docs/en/advanced-concepts/settings/
`excludedAttributes: ['visible']` in `mobile:source` https://appium.io/docs/en/commands/mobile-command/ also might help.

**Comment by rillzhang** [comment]
> Then, probably increasing `snapshotMaxDepth` or `customSnapshotTimeout` could help.
> https://appium.io/docs/en/advanced-concepts/settings/
> `excludedAttributes: ['visible']` in `mobile:source` https://appium.io/docs/en/commands/mobile-command/ also might help.

Thank you,I will try it and tell you result.

**Comment by rillzhang** [comment]
If the ios system are 13.x or 14.x , the same page can get all source.

**Comment by rillzhang** [comment]
> Then, probably increasing `snapshotMaxDepth` or `customSnapshotTimeout` could help.
> https://appium.io/docs/en/advanced-concepts/settings/
> `excludedAttributes: ['visible']` in `mobile:source` https://appium.io/docs/en/commands/mobile-command/ also might help.

in ios 12.x
set snapshotMaxDepth to 100 or set customSnapshotTimeout to 100, it's no use.
xcludedAttributes: ['visible'] in mobile:source yet no use.

**Comment by rillzhang** [comment]
I found another wda branch can get all page source and don't need change capability setting.
https://github.com/AirtestProject/iOS-Tagent

**Comment by KazuCocoa** [comment]
I don't know the difference since they don't open their WDA code.

One possible case between iOS 12 and 13 and greater is the difference endpoint to get elements via XCTest framework.
https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/PrivateHeaders/XCTest/XCAXClient_iOS.h#L57-L60

The older one had deprecated so Appium moved to the new one as a primary way. It could happen the older one works on lower iOS versions. (I don't know when the deprecated one will be removed completely but if so, xcodelog has many warning messages.)

Then, you could use Xcode 10 for iOS 12.

**Comment by mykola-mokhnach** [comment]
Closed s third party issue
