### ISSUE TITLE
Pairing confirmation system popup is not visible in the elements tree

### ISSUE THREAD

**Issue by Hanna-Kokhanava** [appium/appium#15011]
## The problem
When pairing Bluetooth devices with Pixel phone, system pairing confirmation popup appears. But Appium inspector (and UIAutomatorViewer also) doesn't show this popup element in the elements tree. 
![image](https://user-images.githubusercontent.com/11444200/104217476-b87dfc00-543b-11eb-8aa3-6881d6906e5e.png)

What's also interesting, Samsung phones are not affected, I suppose because they have another popup internal implementation (at the bottom of the screen).

I understand that most probably it's not an Appium/UIAutomatorViewer issue and looks like it's brand dependent issue, but just wanted to make sure.

Thanks in advance!

## Environment

* Appium version (or git revision) that exhibits the issue: 1.19
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: Android 10
* Real device or emulator/simulator: Pixel 4
* Appium CLI or Appium.app|exe:

**Comment by KazuCocoa** [comment]
Yes, it seems basically manufacture side issue.
I don't know this help, but potentially `enableMultiWindows` could help if the alert was a different windows as Android OS....
https://github.com/appium/appium-uiautomator2-driver

**Comment by Hanna-Kokhanava** [comment]
Unfortunately, it didn't help, popup is still not visible :(
Anyway, thanks for your answer!

**Comment by Hanna-Kokhanava** [comment]
> Yes, it seems basically manufacture side issue.
> I don't know this helps, but potentially `enableMultiWindows` could help if the alert was a different windows as Android OS....
> https://github.com/appium/appium-uiautomator2-driver

Unfortunately it didn't help, popup is still not present :(
Anyway, thanks for your answer!
