### ISSUE TITLE
Appium 1.20: Selecting by Locator Strategy ID fails, specifying resource-id without package name

### ISSUE THREAD

**Issue by rasim-sitmanbetov** [appium/appium#15013]
## The problem

After updating to Appium 1.20, we faced an issue on Android, that locators with ID strategy don't work anymore, returning next error:
```
[elements("id","logo")] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: Cannot rewrite element locator 'logo' to its complete form, because the current application package name is unknown. Consider providing the app package name or changing the locator to '<package_name>:id/logo' format.
```
At the same time, having our app active, we can successfully get current package name, so it's being resolved without problems.

Also, locator strategy works fine if specifying ID in complete form

We have lot of locators which use ID strategy and not specifying them in complete form, as we need to support tests for different package names.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.20
* Last Appium version that did not exhibit the issue (if applicable): Appium 1.19.1
* Desktop OS/version used to run Appium: `Mac OS X | 10.15.7 | 19H114`
* Node.js version (unless using Appium.app|exe): v14.12.0
* Npm or Yarn package manager: NPM 6.14.8
* Mobile platform/version under test: Android 10 API 29
* Real device or emulator/simulator: Samsung Galaxy S10e
* Appium CLI or Appium.app|exe: Appium.app

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
[Appium log with error](https://gist.github.com/rasim-sitmanbetov/e44e906d0b7e6e705cf25127d29a9f33)
[Full Appium log](https://gist.github.com/rasim-sitmanbetov/d9b861593b2ffa5bb165b31717d6989e)

**Comment by mykola-mokhnach** [comment]
Please provide the full server log. Do you provide the appPackage capability?

**Comment by rasim-sitmanbetov** [comment]
@mykola-mokhnach 
here is the full log
https://gist.github.com/rasim-sitmanbetov/d9b861593b2ffa5bb165b31717d6989e
We don't specify the `appPackage` capability, and so far we didn't require it till 1.19.1 included.

**Comment by rasim-sitmanbetov** [comment]
here is the list of all capabilities used:
```
+--------------------------------------------------------------------------------------+
| Capabilities built                                                                   |
+--------------------------------------------------------------------------------------+
| allowTestPackages = true                                                             |
| app = [path_to_app |
| appWaitActivity = ([first_app]*|[second_app]*)                                            |
| automationName = UIAutomator2                                                        |
| clearSystemFiles = true                                                              |
| fullReset = false                                                                    |
| newCommandTimeout = 3600                                                             |
| noReset = true                                                                       |
| noSign = true                                                                        |
| optionalIntentArguments = [additional_args_for_app]                               |
| orientation = PORTRAIT                                                               |
| platformVersion = 29                                                                 |
| processArguments = {"args":[""],"env":{}}                                            |
| systemPort = 51675                                                                   |
| udid = RF8MC18EZAY                                                                   |
+--------------------------------------------------------------------------------------+
```

**Comment by mykola-mokhnach** [comment]
I'm not quite sure how it was working before, but the original code needs appPackage to be set in order to build a locator:
https://github.com/appium/appium-uiautomator2-server/blob/33f7a10acc2d89d8082cc680365cdf991f8d496c/app/src/main/java/io/appium/uiautomator2/utils/ElementLocationHelpers.java#L60

You could try to replace the server with the patched one from https://github.com/appium/appium-uiautomator2-server/pull/404/files and see if that helps

**Comment by rasim-sitmanbetov** [comment]
@mykola-mokhnach 
I'm not quite sure I'm doing it properly, but here what I did:

1. I've checked out your branch, built it with `gradle clean assembleServerDebug assembleServerDebugAndroidTest`
2. copied built apk from `app/build/outputs/apk/server/debug/` to `/appium/node_modules/appium-uiautomator2-server/apks`
3. started session

With this I got the same error with package name.

If my flow is wrong, could you please assist on this or point me to a proper documentation?

Thank you

**Comment by mykola-mokhnach** [comment]
This looks correct. You also need to delete the server from the device under test to void it being cached. Also, check the logcat output. I've changed the logging there on session creation, so you should see the new log line with session capabilities there if the patched server was properly deployed

**Comment by rasim-sitmanbetov** [comment]
@mykola-mokhnach
thanks. But still no luck. I've made sure the new server app was installed:
`01-12 17:14:17.350 12272 12338 I appium  : Created the new session with id c8bcaca0-a5af-4962-aaaa-a25394970b5a and capabilities {}`
please see full server log: https://gist.github.com/rasim-sitmanbetov/c91b5ef124798d4f5ff0767c928ac956

**Comment by mykola-mokhnach** [comment]
Yep, I think I know what the issue is. Please check out the updated branch

**Comment by rasim-sitmanbetov** [comment]
thank you @mykola-mokhnach !
now works fine, checked both short/complete form for ID locator :-)
https://gist.github.com/rasim-sitmanbetov/505ad5346d512b9bff525827bca695e5

**Comment by mykola-mokhnach** [comment]
Published the fix to appium@beta. Thanks for testing it

**Comment by mykola-mokhnach** [comment]
Appium 1.20.1 containing g the patch has been released
