### ISSUE TITLE
Timeout error coours after implicitlyWait is executed

### ISSUE THREAD

**Issue by flynnwjf** [appium/appium#15012]
## The problem

The following error occurs after driver.manage().timeouts().implicitlyWait(4, TimeUnit.MINUTES); is executed
An unknown server-side error occurred while processing the command. Original error: Timed out after 15604ms waiting for the root AccessibilityNodeInfo in the active window. Make sure the active window is not constantly hogging the main UI thread (e.g. the application is being idle long enough), so the accessibility manager could do its work

## Environment

* Appium version (or git revision) that exhibits the issue: 1.19
* Last Appium version that did not exhibit the issue (if applicable): 1.18
* Desktop OS/version used to run Appium: Windows
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/flynnwjf/8fe21f25104a6f0d38286da50a5a22ad

## Code To Reproduce Issue [ Good To Have ]

	public void test_LongLoadApp() throws InterruptedException{
		
		driver.manage().timeouts().implicitlyWait(4, TimeUnit.MINUTES);
		
		driver.findElement(MobileBy.AndroidUIAutomator("new UiSelector().textContains(\"Hello World!\");"));
	
	}

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing we could do about this issue. The error is thrown by UiAutomator itself. Consider fixing the your application under test

**Comment by jessechen0319** [comment]
@mykola-mokhnach 
just for more information, we can run the test with this script before the upgrade of Appium.
and we track the code, found the `managedDrivers` is empty in timeout.js of base driver.
not sure it is normal or not.
here is the source code of Base driver.
```
helpers.setImplicitWait = function setImplicitWait (ms) { // eslint-disable-line require-await
  this.implicitWaitMs = ms;
  log.debug(`Set implicit wait to ${ms}ms`);
  if (this.managedDrivers && this.managedDrivers.length) {
    log.debug('Setting implicit wait on managed drivers');
    for (let driver of this.managedDrivers) {
      if (_.isFunction(driver.setImplicitWait)) {
        driver.setImplicitWait(ms);
      }
    }
  }
};
```
