### ISSUE TITLE
AndroidDriver driver.installApp() fails no matter there is allowTestPackages set to true in initial DesiredCapabilities

### ISSUE THREAD

**Issue by mstrahinski** [appium/appium#15029]
## The problem

I had to add "allowTestPackages" set to true in the DesiredCapabilities when starting the AndroidDriver in order everything to work as otherwise there was an exception which was not allowing testOnly apps to be installed. That initially solved my problems.

However the same exception appeared afterwards when I tried to reinstall the app by doing the following: driver.removeApp(packageName) in the code, the remove is successful and then when you driver.installApp("path-to-app"); then the same exception is thrown and it can clearly be seen in the DesiredCapabilities that the allowTestPackages is set to true but it does not work for the driver.installApp() method. Probably the installApp() method does not consider that capability in order to add -t as parameter to the adb command. If you take the command from the exception or the server logs and try it out by adding -t next to -r, everything it is successful, but this doesn't make the driver.installApp() method work properly.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.0
* Last Appium version that did not exhibit the issue (if applicable): no idea
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): v14.15.4
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Pixel4XL_API_LEVEL_29, Android 10
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: through the code, the AndroidDriver methods

## Details

Here is the link to the detailed 
https://gist.github.com/mstrahinski/8a22bf192e0ad417a0e064b9ce5a4eb5

## Link to Appium logs

In the exception in the below link it can be clearly seen that allowTestPackages is set to true in the DesiredCapabilities:

Here is a link to the appium server logs: https://gist.github.com/mstrahinski/8a22bf192e0ad417a0e064b9ce5a4eb5

## Code To Reproduce Issue [ Good To Have ]

The code is as simple as:

mobileDriver.removeApp("com.*****************.android");
mobileDriver.installApp(Paths.get("resources/theAndroidapp/app-debug.apk.zip").toAbsolutePath().toString());

**Comment by KazuCocoa** [comment]
Did you try to set `allowTestPackages` as an argument like below?

e.g.:
Java:
https://github.com/appium/java-client/blob/bcca20276191f98d9293974b6430cb97cb5e465c/src/main/java/io/appium/java_client/InteractsWithApps.java#L69
Ruby:
https://www.rubydoc.info/github/appium/ruby_lib_core/Appium/Core/Base/Driver#install_app-instance_method

**Comment by mstrahinski** [comment]
> Did you try to set `allowTestPackages` as an argument like below?
> 
> e.g.:
> Java:
> https://github.com/appium/java-client/blob/bcca20276191f98d9293974b6430cb97cb5e465c/src/main/java/io/appium/java_client/InteractsWithApps.java#L69
> Ruby:
> https://www.rubydoc.info/github/appium/ruby_lib_core/Appium/Core/Base/Driver#install_app-instance_method

Yeap, definitely this works like a charm(and it is a workaround):

mobileDriver.installApp(Paths.get("resources/theAndroidapp/app-debug.apk.zip").toAbsolutePath().toString(), new AndroidInstallApplicationOptions().withAllowTestPackagesEnabled());

but still shouldn't the installApp(String path) overload that accepts only file path consider the allowTestPackages which is already set in the DesiredCapabilities and work properly without throwing an exception.
