### ISSUE TITLE
Upgrade appium-xcuitest-driver to latest (XCode 12.3 is not supported)

### ISSUE THREAD

**Issue by napsta32** [appium/appium#15028]
## The problem

XCode 12.3 is not supported with current version of appium-xcuitest-driver. WebDriverAgent build returns error all the time. See the following log:

```
error: Building for iOS Simulator, but the embedded framework 'CocoaAsyncSocket.framework' was built for iOS + iOS Simulator. (in target 'WebDriverAgentRunner' from project 'WebDriverAgent')
error: Building for iOS Simulator, but the embedded framework 'YYCache.framework' was built for iOS + iOS Simulator. (in target 'WebDriverAgentRunner' from project 'WebDriverAgent')
error: Building for iOS Simulator, but the linked and embedded framework 'YYCache.framework' was built for iOS + iOS Simulator. (in target 'WebDriverAgentLib' from project 'WebDriverAgent')
error: Building for iOS Simulator, but the linked and embedded framework 'CocoaAsyncSocket.framework' was built for iOS + iOS Simulator. (in target 'WebDriverAgentLib' from project 'WebDriverAgent')
```

## Environment

* Appium Desktop: 1.19.1

## Details

Min Required Version: appium-webdriveragent 2.32.0
Actual Version: appium-webdriveragent 2.27.2 (See https://github.com/appium/appium-xcuitest-driver/blob/3.31/package.json)

Appium XCUITest Driver PR: https://github.com/appium/appium-xcuitest-driver/pull/1259

WebDriverAgent Issue: https://github.com/appium/WebDriverAgent/issues/432
WebDriverAgent PR: https://github.com/appium/WebDriverAgent/pull/434

Expected appium-xcode-version: 3.33.1

## Code To Reproduce Issue

Install latest XCode 12.3.
Run latest appium desktop and start an inspector session with any iOS app.

**Comment by KazuCocoa** [comment]
1.19 has the issue. You should get 1.20 https://github.com/appium/appium-desktop/releases/tag/v1.20.0
