### ISSUE TITLE
Appium cannot start flutter app in debug mode in iOS14

### ISSUE THREAD

**Issue by hex0cter** [appium/appium#15021]
## The problem

We are using Appium to test the app built by Flutter. When Appium loads the app built by flutter build ios --flavor=firebase --debug on a real iPhone, the UI only shows:

```
In iOS 14+, debug mode Flutter apps can only be launched from Flutter tooling, IDEs with Flutter plugins or from Xcode. Alternatively, build in profile or release modes to enable launching from the home screen.
Is this due to the reasons above? If so, does it mean there is NO way at all to test flutter apps using Appium on a real device with iOS14+?
```

The flutter documentations (https://flutter.dev/docs/development/ios-14) says:
```
Due to changes in debugger mechanisms, once a Flutter debug application is installed on the device (either by using flutter run a Flutter-enabled IDE, or from Xcode), the application can no longer be re-launched by tapping the application’s icon in the home screen in iOS 14 on physical devices.
```

Is this the reason why I cannot test it in Appium? If so, does it mean there is NO way at all to test flutter apps using Appium on a real device with iOS14+?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS Big Sur
* Node.js version (unless using Appium.app|exe): v12.16.2
* Npm or Yarn package manager: npm 6.14.11
* Mobile platform/version under test: iOS14.3
* Real device or emulator/simulator: Real iPhone XS
* Appium CLI or Appium.app|exe: Both CLI and Appium desktop

## Code To Reproduce Issue [ Good To Have ]
* Build the flutter app with `flutter build ios --flavor=firebase --debug`.
* In Appium, using the following desired capabilities:
```json
{
"platformName": "iOS",
"platformVersion": "14.3",
"deviceName": "iPhone XS",
"automationName": "XCUITest",
"xcodeOrgId": "******",
"xcodeSigningId": "Apple Development",
"udid": "uniq-device-id",
"app": "/Runner.app"
}
```
The app is launched on the phone and shows: 
```
In iOS 14+, debug mode Flutter apps can only be launched from Flutter tooling, IDEs with Flutter plugins or from Xcode. Alternatively, build in profile or release modes to enable launching from the home screen.
```
(PS: the issue was originally reported in the flutter project but closed because the owner thinks it is an Appium issue: https://github.com/flutter/flutter/issues/73935)

**Comment by mykola-mokhnach** [comment]
Try https://github.com/truongsinh/appium-flutter-driver

**Comment by hex0cter** [comment]
Hi @mykola-mokhnach! Yes I have spent a couple of hours with `appium-flutter-driver` now. With `flutter build ios --flavor=firebase --debug` it is still giving the same result. With `flutter build ios --flavor=firebase --profile`, the app does load, but appium is hanging with 
```
2021-01-15 11:18:09:160 - [debug] [BaseDriver] The value of 'elementResponseAttributes' setting did not change. Skipping the update for it
2021-01-15 11:18:09:160 - [debug] [BaseDriver] The value of 'shouldUseCompactResponses' setting did not change. Skipping the update for it
2021-01-15 11:18:09:169 - [FlutterDriver] Attempt #1
2021-01-15 11:18:09:169 - [FlutterDriver] Connecting to Dart Observatory: ws://127.0.0.1:49188/z9m-jhVNBsY=/ws
2021-01-15 11:18:09:173 - [FlutterDriver] [object Object]
2021-01-15 11:18:09:173 - [FlutterDriver] Check Dart Observatory URI ws://127.0.0.1:49188/z9m-jhVNBsY=/ws
2021-01-15 11:18:09:174 - [FlutterDriver] Waiting 300 seconds before trying...
```
I also got the same error when I test the app here: https://github.com/truongsinh/appium-flutter-driver/tree/master/example/flutter_app_under_test

The issue is discussed https://github.com/truongsinh/appium-flutter-driver/issues/39 and https://github.com/truongsinh/appium-flutter-driver/issues/123. I will spend a couple of more hours and see I can find something new.

**Comment by hex0cter** [comment]
Here is the full log:
[appium.log](https://github.com/appium/appium/files/5819909/appium.log)

**Comment by mykola-mokhnach** [comment]
I assume Apple did some breaking changed to iOS 14, which broke the automation. I would try to report the issue to flutter driver repository. We did not change anything related to the application deployment in xcuitest driver.

**Comment by hex0cter** [comment]
I did report the issue in the Flutter project: https://github.com/flutter/flutter/issues/73935 earlier but it got closed because the owner thinks the problem belongs to Appium rather than Flutter.

**Comment by mykola-mokhnach** [comment]
I agree with the comment to that issue. xcuitest driver and flutter driver are different things (e.g. `automationName` cap value). Try to attach the capabilities and the server log you get when you try to run your test with flutter driver. Unfortunately I don't think we could help much to make it working with xcuitest driver though.

**Comment by hex0cter** [comment]
As the log attached above indicated, here is the capabilities I used during the test:

```
01-15 11:16:52:137 - [debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {
2021-01-15 11:16:52:137 - [debug] [BaseDriver]   "platformName": "iOS",
2021-01-15 11:16:52:137 - [debug] [BaseDriver]   "platformVersion": "14.3",
2021-01-15 11:16:52:137 - [debug] [BaseDriver]   "deviceName": "iPhone XS",
2021-01-15 11:16:52:137 - [debug] [BaseDriver]   "automationName": "Flutter",
2021-01-15 11:16:52:137 - [debug] [BaseDriver]   "xcodeOrgId": "YXGU3KK352",
2021-01-15 11:16:52:137 - [debug] [BaseDriver]   "xcodeSigningId": "Apple Development",
2021-01-15 11:16:52:137 - [debug] [BaseDriver]   "app": "/Volumes/case-sensitive/git/scrive-mobile-apps/build/ios/iphoneos/Runner.app",
2021-01-15 11:16:52:137 - [debug] [BaseDriver]   "showXcodeLog": true,
2021-01-15 11:16:52:137 - [debug] [BaseDriver]   "udid": "00008020-001D0D1C0E8800**",
2021-01-15 11:16:52:137 - [debug] [BaseDriver]   "newCommandTimeout": 0
2021-01-15 11:16:52:137 - [debug] [BaseDriver] }
```

**Comment by hex0cter** [comment]
Ah... I see why you were asking. When I raised the issue originally, I was using `XCUITest`. But later on I also tried `Flutter` as in the log of this ticket, but that didn't help.

**Comment by mykola-mokhnach** [comment]
Closing this issue as third party one. Flutter requires their apps to be executed in a hacky way, which is different from the standard one. As a workaround I would probably try to prelaunch the app on the device and then run xcuitest driver with `noReset` option enabled.
