### ISSUE TITLE
Appium driver unable to find android.widget.ImageView 

### ISSUE THREAD

**Issue by ganjarpanji** [appium/appium#15022]
## The problem

im facing an issue that my test assertion for image shall display is failing, after did a getPageSource the android.widget.ImageView element is not found. checked on 1.19.0 version of appium, the android.widget.ImageView is displayed properly on getPageSource. im using uiautomator2

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.0
* Last Appium version that did not exhibit the issue (if applicable): 1.19.0
* Desktop OS/version used to run Appium: macOS
* Node.js version (unless using Appium.app|exe): v10.16.0
* Npm or Yarn package manager: npm@6.13.6
* Mobile platform/version under test: android
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: appium cli

## Details

Im using uiautomator2 driver on the appium.

## Link to Appium logs

Since i debug using getPageSource, not sure how to provide the log.

## Code To Reproduce Issue [ Good To Have ]

- Make sure u have ImageView on your android app
- check using appium the element is displayed
- test will fail, cause the element not included in the UI hierarchy

**Comment by mykola-mokhnach** [comment]
Have you tried if it works with appium@beta?

**Comment by mykola-mokhnach** [comment]
Is the element present in the page source generated by the standard uiautomator viewer tool?

**Comment by ganjarpanji** [comment]
im using `npm install -g appium@beta` is this version correct `1.20.0-beta.0` ?


> Is the element present in the page source generated by the standard uiautomator viewer tool?

pageSource generarted by standard CLI appium, i debug it from my test script.

**Comment by mykola-mokhnach** [comment]
I am talking about https://www.guru99.com/uiautomatorviewer-tutorial.html

**Comment by ganjarpanji** [comment]
could confirm that using `1.20.0-beta.0` not work as well.
i tried using default uiautomator from android SDK, and the imageView is not present.
its strange, cause there is no issue when im using 1.19.0 version.

**Comment by ganjarpanji** [comment]
tried inspec using macaca app-inspector, and could confirm the imageView is present on the UI hierarchy
![image](https://user-images.githubusercontent.com/1736817/104592135-5245e300-56a0-11eb-8761-2fff8aa94aa1.png)

**Comment by mykola-mokhnach** [comment]
I would try to play with `allowInvisibleElements` and/or `ignoreUnimportantViews` settings. Otherwise I don't have any more suggestions

**Comment by ganjarpanji** [comment]
https://github.com/appium/appium-uiautomator2-server/pull/389/files#diff-2e73e7eb3d5add2a08c47cbb2bd1ef86edc4fb496c524f310141b34e1bbd7a23
i saw something like related to `mjpeg` changes on this PR, is there any possibility that would cause this?

**Comment by mykola-mokhnach** [comment]
Any updates?

**Comment by ganjarpanji** [comment]
Thanks! those settings solve it.
i set `allowInvisibleElements = true` and remove the `ignoreUnimportantViews` as its `false` by default.
