### ISSUE TITLE
"TAP" takes no effect in 14.3 XCUIElementTypeButton

### ISSUE THREAD

**Issue by f0rm2l1n** [appium/appium#15031]
## The problem

Helle there, the problem here is I upgrade my iPhone from 14.2 to 14.3 (accidentally). Before this sad thing happens, I write some scripts and successfully automatically help me doing some UI testing staffs. However, things don't work out for now.

## Environment

* Appium version: Old one for 14.2 is 1.18 and I update to the latest 1.20, the problem still remains
* Last Appium version that did not exhibit the issue: 1.18 functions well with 14.2
* Desktop OS/version used to run Appium: macOS 10.15.6 
* Node.js version (unless using Appium.app|exe): v14.15.1
* Npm or Yarn package manager: Npm
* Mobile platform/version under test: iOS 14.3
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: In fact, I use Appium Desktop (dmg) for ease

## Details

I can take a quick example here, like *testflight* apps. I launch the appium desktop with inspector session like below configs (as I always do with 14.2 iOS)
```
{
  "platformName": "iOS",
  "platformVersion": "14.3",
  "deviceName": "iPhone7",
  "udid": "...",
  "bundleId": "com.apple.TestFlight",
  "automationName": "XCUITest",
  "xcodeOrgId": "...",
  "xcodeSigningId": "iPhone Developer"
}
```
The inspector can successfully launch the Testflight. But after that, when I try to search some buttons and tap them. However, though I can find the XCUIElementTypeButton with predicate or XML path. The *tap* is not working out. In my old 14.2, after *tap* the XCUIElementTypeButton will change its color but totally nothing happens with this 14.3 iOS

## Link to Appium logs

=> https://gist.github.com/f0rm2l1n/44e7cfcbe5cb1c87f2b54b50ac69be64
Not really familiar with the log, seems the *click* successfully return 

## Others
I reinstall Appium-desktop for a try but still fails. Wonder anyone also get into trouble like this?

**Comment by mykola-mokhnach** [comment]
Try to click by element coordinates as a workaround. WDA simply forwards the click command to XCUITest, which means it must some issue on Apple side there.

**Comment by f0rm2l1n** [comment]
> Try to click by element coordinates as a workaround. WDA simply forwards the click command to XCUITest, which means it must some issue on the Apple side there.

Thanks for the reply, I have tried to get the coordinates by `el.get_attribute('rect')` using python. 
However, the `driver.tap([(x,y)], duration)` also take no effects. Maybe the coordinates I obtained is wrong? Or How can I do this coordinates based click with Appium desktop?

Appreciate for the help~

**Comment by mykola-mokhnach** [comment]
> Maybe the coordinates I obtained is wrong?

You could verify them using the Accessibility Inspector in Xcode. It could be that the application under test does not handle the event synthesized by XCTest properly. Try to add more debug logging to the app under test itself to see where the click actually happens and why it is not recognized.

**Comment by f0rm2l1n** [comment]
I found and tried the coordinates click in Appium desktop and (finally) get some error feedback, like below

And what is interesting is that the click "magically" shift a distance. Please check this video (https://drive.google.com/file/d/1Eh_lcFXFg6hM9Vr4TMSTXkF5MHUYOypY/view?usp=sharing)

So the reason is the mismatch of coordinates between Appium and iPhone? How can fix this? report to XCUITest or can I fix it myself by doing some shift? Any advice? Thanks!

(P.S. I borrowed an old iPhone with a 13.3 system, everything just goes very well :(

**Comment by mykola-mokhnach** [comment]
The coordinates are returned by XCTest. Only Apple can fix that. For your case the only possible workaround would be to shift coordinates manually in your client code

**Comment by f0rm2l1n** [comment]
Got it😁 thanks for the timely and favorable reply👍
