### ISSUE TITLE
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: 'opencv4nodejs' module is required to use OpenCV features. Please install it first ('npm i -g opencv4nodejs

### ISSUE THREAD

**Issue by Pavithra24x7** [appium/appium#15033]
## The problem
Getting WebDriverException while using opencv feature to click on a text using appium image click feature.OpenCv & opencv4nodejs both have been installed but still not able to click on a text using appium image click feature.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS Catalina(10.15.2 (19C57))
* Node.js version (unless using Appium.app|exe):node v 15.4.0
* Npm or Yarn package manager: npm v6.14.11
* Mobile platform/version under test: iOS13.3.1 / Android 9
* Real device or emulator/simulator: Real devices
* Appium CLI or Appium.app|exe: CLI

## Details
One of the text we have to click, but there was no specific locator given by dev. Trying to use appium image click feature by giving the screenshot of the text. While running appium doctor command, it's showing output as opencv4nodejs is installed at particular location, but while running automation facing issue **"    [Support] Unable to load 'opencv4nodejs': Unable to load package 'opencv4nodejs': Cannot find module '/usr/local/lib/node_modules/opencv4nodejs/build/Release/opencv4nodejs'
"**
## Link to Appium logs

https://gist.github.com/Pavithra24x7/c52ff94671f12292376f57962e1e7e84

**Comment by Pavithra24x7** [comment]
Pavithra-prakasm:~ pavithra-prakasam$ appium -v
1.20.1
Pavithra-prakasm:~ pavithra-prakasam$ node -v
v15.4.0
Pavithra-prakasm:~ pavithra-prakasam$ npm -v
6.14.11
Pavithra-prakasm:~ pavithra-prakasam$ appium-doctor
info AppiumDoctor Appium Doctor v.1.16.0
info AppiumDoctor ### Diagnostic for necessary dependencies starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: /usr/local/bin/node
info AppiumDoctor  ✔ Node version is 15.4.0
info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ Xcode Command Line Tools are installed in: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ DevToolsSecurity is enabled.
info AppiumDoctor  ✔ The Authorization DB is set up properly.
info AppiumDoctor  ✔ Carthage was found at: /usr/local/bin/carthage. Installed version is: 0.36.0
info AppiumDoctor  ✔ HOME is set to: /Users/pavithra-prakasam
info AppiumDoctor  ✔ ANDROID_HOME is set to: /Users/pavithra-prakasam/Library/Android/sdk
info AppiumDoctor  ✔ JAVA_HOME is set to: /Library/Java/JavaVirtualMachines/jdk1.8.0_221.jdk/Contents/Home
info AppiumDoctor    Checking adb, android, emulator
info AppiumDoctor      'adb' is in /Users/pavithra-prakasam/Library/Android/sdk/platform-tools/adb
info AppiumDoctor      'android' is in /Users/pavithra-prakasam/Library/Android/sdk/tools/android
info AppiumDoctor      'emulator' is in /Users/pavithra-prakasam/Library/Android/sdk/emulator/emulator
info AppiumDoctor  ✔ adb, android, emulator exist: /Users/pavithra-prakasam/Library/Android/sdk
info AppiumDoctor  ✔ 'bin' subfolder exists under '/Library/Java/JavaVirtualMachines/jdk1.8.0_221.jdk/Contents/Home'
info AppiumDoctor ### Diagnostic for necessary dependencies completed, no fix needed. ###
info AppiumDoctor 
info AppiumDoctor ### Diagnostic for optional dependencies starting ###
info AppiumDoctor  ✔ opencv4nodejs is installed at: /usr/local/lib. Installed version is: 5.6.0
info AppiumDoctor  ✔ ffmpeg is installed at: /usr/local/bin/ffmpeg. ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
WARN AppiumDoctor  ✖ mjpeg-consumer cannot be found.
WARN AppiumDoctor  ✖ set-simulator-location is not installed
WARN AppiumDoctor  ✖ idb is not installed
WARN AppiumDoctor  ✖ applesimutils cannot be found
info AppiumDoctor  ✔ ios-deploy is installed at: /usr/local/bin/ios-deploy. Installed version is: 1.9.4
WARN AppiumDoctor  ✖ bundletool.jar cannot be found
WARN AppiumDoctor  ✖ gst-launch-1.0 and/or gst-inspect-1.0 cannot be found
info AppiumDoctor ### Diagnostic for optional dependencies completed, 6 fixes possible. ###
info AppiumDoctor 
info AppiumDoctor ### Optional Manual Fixes ###
info AppiumDoctor The configuration can install optionally. Please do the following manually:
WARN AppiumDoctor  ➜ mjpeg-consumer module is required to use MJPEG-over-HTTP features. Please install it with 'npm i -g mjpeg-consumer'.
WARN AppiumDoctor  ➜ set-simulator-location is needed to set location for Simulator. Please read https://github.com/lyft/set-simulator-location to install it
WARN AppiumDoctor  ➜ Why idb is needed and how to install it: https://github.com/appium/appium-idb
WARN AppiumDoctor  ➜ Why applesimutils is needed and how to install it: http://appium.io/docs/en/drivers/ios-xcuitest/
WARN AppiumDoctor  ➜ bundletool.jar is used to handle Android App Bundle. Please read http://appium.io/docs/en/writing-running-appium/android/android-appbundle/ to install it
WARN AppiumDoctor  ➜ gst-launch-1.0 and gst-inspect-1.0 are used to stream the screen of the device under test. Please read https://appium.io/docs/en/writing-running-appium/android/android-screen-streaming/ to install them and for more details
info AppiumDoctor 
info AppiumDoctor ###
info AppiumDoctor 
info AppiumDoctor Bye! Run appium-doctor again when all manual fixes have been applied!
info AppiumDoctor

**Comment by mykola-mokhnach** [comment]
Was the module installed successfully? Is it possible to require it outside of Appium?

**Comment by Pavithra24x7** [comment]
opencv we don't require outside, only using for image click. Here is the log, while installing opencv4nodejs fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/opencv4nodejs/cc/tracking/MultiTracker.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:376:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:284:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/usr/local/Cellar/node/15.4.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--jobs" "max"
gyp ERR! cwd /usr/local/lib/node_modules/opencv4nodejs
gyp ERR! node -v v15.4.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

But, When run appium-doctor it's saying opencv4node js installed at **"info AppiumDoctor  ✔ opencv4nodejs is installed at: /usr/local/lib. Installed version is: 5.6.0
"**

**Comment by mykola-mokhnach** [comment]
appium doctor simply check the module existence, however the fact that it exists does not mean it actually works. Please report your issue to https://github.com/justadudewhohacks/opencv4nodejs as there is nothing we could do there from Appium side if the original module is broken and cannot be loaded
