### ISSUE TITLE
Error uiautomator session not created

### ISSUE THREAD

**Issue by ganjarpanji** [appium/appium#15038]
## The problem
the session not created for uiautomator

## Environment

* Appium version (or git revision) that exhibits the issue:1.20
* Last Appium version that did not exhibit the issue (if applicable):1.19
* Desktop OS/version used to run Appium:macOS
* Node.js version (unless using Appium.app|exe):v10.16.0
* Npm or Yarn package manager:6.13.6
* Mobile platform/version under test:Android
* Real device or emulator/simulator:emulator
* Appium CLI or Appium.app|exe:CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/ganjarpanji/97d6a954894b1000e5c12c203adbed77

## Code To Reproduce Issue [ Good To Have ]

- re install appium with `npm install -g appium`
- when run the test android the issue ocurred

**Comment by mykola-mokhnach** [comment]
Please provide the full server log

**Comment by ganjarpanji** [comment]
updated to full logs @mykola-mokhnach https://gist.github.com/ganjarpanji/97d6a954894b1000e5c12c203adbed77 🙏

**Comment by ganjarpanji** [comment]
i also wondering why appium not recognize these caps?
```
[BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[BaseDriver]   allowInvisibleElements
[BaseDriver]   mjpegScalingFactor
[BaseDriver]   mjpegServerScreenshotQuality
[BaseDriver]   ignoreUnimportantViews

```

**Comment by mykola-mokhnach** [comment]
It looks like the application under test fails to start. Have you tried to start it manually using adb? Could you also attach the logcat output?

**Comment by mykola-mokhnach** [comment]
>i also wondering why appium not recognize these caps?

because they are not capabilities, but settings

**Comment by ganjarpanji** [comment]
ah thanks! its work now. probably its better to give more info regarding the unrecognized caps as settings will help. just my opinion though. Thanks for the solution 🙏  im closing the issue

**Comment by mykola-mokhnach** [comment]
Unfortunately, we don't know which of these are valid settings and which are just invalid/erroneously typed strings. It would also be not good if the warning message was confusing.
