### ISSUE TITLE
I am facing the error,  "Neither ANDROID_HOME nor ANDROID_SDK_ROOT environment variable was exported"

### ISSUE THREAD

**Issue by levank707** [appium/appium#15034]
## The problem
When I am trying to run tests, Neither ANDROID_HOME nor ANDROID_SDK_ROOT environment variable was exported. this error is appears.  I set zprofile, also tried(bash_profile) but it's same.
## Environment

* Appium version (or git revision) that exhibits the issue:1.20.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macos 
* Node.js version (unless using Appium.app|exe):v15.5.1
* Npm or Yarn package manager:
* Mobile platform/version under test: android Pixel 3 api 30
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: both 

## Details
bash_profile
export JAVA_HOME=$(/usr/libexec/java_home)
export ANDROID_HOME=${HOME}/Library/Android/sdk
export PATH="${JAVA_HOME}/bin:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${PATH}"
-----------------------------------------------------------------------------------------------------------
appium doctor
info AppiumDoctor Appium Doctor v.1.15.4
info AppiumDoctor ### Diagnostic for necessary dependencies starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: /usr/local/bin/node
info AppiumDoctor  ✔ Node version is 15.5.1
info AppiumDoctor  ✔ ANDROID_HOME is set to: /Users/macbookpro/Library/Android/sdk
info AppiumDoctor  ✔ JAVA_HOME is set to: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
info AppiumDoctor    Checking adb, android, emulator
info AppiumDoctor      'adb' is in /Users/macbookpro/Library/Android/sdk/platform-tools/adb
info AppiumDoctor      'android' is in /Users/macbookpro/Library/Android/sdk/tools/android
info AppiumDoctor      'emulator' is in /Users/macbookpro/Library/Android/sdk/emulator/emulator
info AppiumDoctor  ✔ adb, android, emulator exist: /Users/macbookpro/Library/Android/sdk
info AppiumDoctor  ✔ 'bin' subfolder exists under '/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home'
info AppiumDoctor ### Diagnostic for necessary dependencies completed, no fix needed. ###

## Link to Appium logs
APPIUM LOG
https://gist.github.com/levank707/a7d4f8948b6c68d05889fb63f3404bcf

JAVA CONSOLE LOG
https://gist.github.com/levank707/a84e1bc34446661c7377179dbcae49c4

**Comment by mykola-mokhnach** [comment]
Please try https://github.com/appium/java-client/blob/master/docs/environment.md

**Comment by mykola-mokhnach** [comment]
also the actual error in the attached log: `Encountered internal error running command: Error: The Android SDK root folder '/Applications/ADT/sdk' does not exist`, which seems valid to me

**Comment by levank707** [comment]
> Please try https://github.com/appium/java-client/blob/master/docs/environment.md

I done it, but it is throwing same error :(

**Comment by levank707** [comment]
> Please try https://github.com/appium/java-client/blob/master/docs/environment.md

I fixed it by setting ANDROID_HOME variable manually in the eclipse run configuration. and it is working fine I am able to run tests on android. but now I am facing new error while trying execute iOS tests here is it -------- An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: not found: carthage 

oh god why ....

**Comment by levank707** [comment]
I removed ANDROID_HOME variable from eclipse and now it is running on IOS but on the android same :/ .....

**Comment by mykola-mokhnach** [comment]
> I done it, but it is throwing same error :(

What exactly have you tried? What is the output of the process environment? Is the desired variable present there? If it is not present then there is nothing that could be done from Appium side and the only thing that could be done is to fix the local env.

**Comment by levank707** [comment]
> > I done it, but it is throwing same error :(
> 
> What exactly have you tried? What is the output of the process environment? Is the desired variable present there? If it is not present then there is nothing that could be done from Appium side and the only thing that could be done is to fix the local env.

ok thanks

**Comment by PrashanthGuvvadi** [comment]
I am facing the same issue:
nknownError: An unknown server-side error occurred while processing the command. Original error: Neither ANDROID_HOME nor ANDROID_SDK_ROOT environment variable was exported. Read https://developer.android.com/studio/command-line/variables for more details
    at getResponseForW3CError (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
    at asyncHandler (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)

**Comment by lovevil7** [comment]
i'm facing the same error. i'm doing a test run.

below is my code from eclipse - 


package appium;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import org.openqa.selenium.remote.DesiredCapabilities;

import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.remote.MobileCapabilityType;


public class Appiumtest {
	
	
	public static void main(String[] args) throws MalformedURLException {
		
		
		File appDir = new File("src");
		File file = new File(appDir, "ApiDemos-debug.apk");
		
		URL url = new URL("http://127.0.0.1:4723/wd/hub");
		
		DesiredCapabilities cp = new DesiredCapabilities();
		
		cp.setCapability(MobileCapabilityType.DEVICE_NAME, "testing");
		
		cp.setCapability(MobileCapabilityType.APP, file.getAbsolutePath());
		
		cp.setCapability(MobileCapabilityType.AUTOMATION_NAME, "uiautomator2");
		
		AndroidDriver driver = new AndroidDriver(url,cp);
		
	
	}
}



error from eclipse log - 


SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: An unknown server-side error occurred while processing the command. Original error: Neither ANDROID_HOME nor ANDROID_SDK_ROOT environment variable was exported. Read https://developer.android.com/studio/command-line/variables for more details
Build info: version: '4.3.0', revision: 'a4995e2c09*'
System info: host: 'shubhams-MacBook-Pro.local', ip: '2405:201:5802:bacc:f831:72d3:dfdd:320e%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '14.0.2'
Driver info: io.appium.java_client.android.AndroidDriver
Command: [null, newSession {capabilities=[{appium:app=/Users/<myuser>/eclipse-workspace/appium/src/ApiDemos-debug.apk, appium:automationName=uiautomator2, appium:deviceName=testing, platformName=ANDROID}], desiredCapabilities=Capabilities {app: /Users/<myuser>/eclipse..., automationName: uiautomator2, deviceName: testing, platformName: ANDROID}}]
Capabilities {}
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:144)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:126)
	at io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:102)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:146)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:180)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:569)
	at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:224)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:179)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:79)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:87)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:116)
	at appium.Appiumtest.main(Appiumtest.java:30)



logs from appium server - 



[debug] [HTTP] Request idempotency key: 116324c1-b5d0-450a-91c3-eae0dfd136f0
[HTTP] --> POST /wd/hub/session
[HTTP] {"capabilities":{"firstMatch":[{}],"alwaysMatch":{"appium:app":"/Users/<myuser>/eclipse-workspace/appium/src/ApiDemos-debug.apk","appium:automationName":"uiautomator2","appium:deviceName":"testing","platformName":"android"}}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [null,null,{"firstMatch":[{}],"alwaysMatch":{"appium:app":"/Users/<myuser>/eclipse-workspace/appium/src/ApiDemos-debug.apk","appium:automationName":"uiautomator2","appium:deviceName":"testing","platformName":"android"}}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1656493769558 (14:39:29 GMT+0530 (India Standard Time))
[Appium] Appium v1.22.3 creating new AndroidUiautomator2Driver (v1.70.1) session
[debug] [BaseDriver] Creating session with W3C capabilities: {
[debug] [BaseDriver]   "alwaysMatch": {
[debug] [BaseDriver]     "platformName": "android",
[debug] [BaseDriver]     "appium:app": "/Users/<myuser>/eclipse-workspace/appium/src/ApiDemos-debug.apk",
[debug] [BaseDriver]     "appium:automationName": "uiautomator2",
[debug] [BaseDriver]     "appium:deviceName": "testing"
[debug] [BaseDriver]   },
[debug] [BaseDriver]   "firstMatch": [
[debug] [BaseDriver]     {}
[debug] [BaseDriver]   ]
[debug] [BaseDriver] }
[BaseDriver] Session created with session id: f4b669c7-c77a-438c-baaa-a63e71f3de98
[BaseDriver] Using local app '/Users/<myuser>/eclipse-workspace/appium/src/ApiDemos-debug.apk'
[debug] [UiAutomator2] Checking whether app is actually present
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1656493769590 (14:39:29 GMT+0530 (India Standard Time))
[debug] [W3C] Encountered internal error running command: Error: Neither ANDROID_HOME nor ANDROID_SDK_ROOT environment variable was exported. Read https://developer.android.com/studio/command-line/variables for more details
[debug] [W3C]     at requireSdkRoot (/usr/local/lib/node_modules/appium/node_modules/appium-adb/lib/helpers.js:36:11)
[debug] [W3C]     at Function.createADB (/usr/local/lib/node_modules/appium/node_modules/appium-adb/lib/adb.js:57:23)
[debug] [W3C]     at Object.createBaseADB (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/android-helpers.js:129:20)
[debug] [W3C]     at Object.getDeviceInfoFromCaps (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/android-helpers.js:214:29)
[debug] [W3C]     at AndroidUiautomator2Driver.startUiAutomator2Session (/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/lib/driver.js:338:40)
[debug] [W3C]     at AndroidUiautomator2Driver.createSession (/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/lib/driver.js:229:18)
[debug] [W3C]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:387:35)
[HTTP] <-- POST /wd/hub/session 500 35 ms - 813
[HTTP]

**Comment by rokuoku** [comment]
Facing the same issue when using `AppiumServiceBuilder`. Environment variables are set in .bashrc and no error occurs when appium is started from command line.
A temporary workaround is to set ANDROID_HOME in IDE.
