### ISSUE TITLE
AppiumDriver.hideKeyboard() takes a long time to execute on some iOS simulator

### ISSUE THREAD

**Issue by lin907597898** [appium/appium#15036]
## The problem

Hi,guys, I encountered some issue using Appium on iOS.
I use hideKeyboard function to hide my iOS simulator keyboard, but this function execute very slowly on the iPad simulator, taking more than a minute to complete.

![image](https://user-images.githubusercontent.com/24429337/105137256-fced5400-5b2d-11eb-9303-4edad7afbeea.png)
![image](https://user-images.githubusercontent.com/24429337/105137384-29a16b80-5b2e-11eb-90f1-2473eaaeceac.png)

![image](https://user-images.githubusercontent.com/24429337/105134765-e0e7b380-5b29-11eb-9dd2-01e28692c2c6.png)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.19.0
* Desktop OS/version used to run Appium: mac os
* Mobile platform/version under test:iOS 14
* Real device or emulator/simulator:Simulator iPad Air (4th generation) 

## Link to Appium logs

Appium log 
https://gist.github.com/lin907597898/afcacca15854aa11bfef679896ef58c7

**Comment by mykola-mokhnach** [comment]
I assume it needs to much time, because it checks the visiblity of Done button, which might be taking a lot of time on some views because of internal XCTest limitations. Try to update Appium to the most recent version first

**Comment by lin907597898** [comment]
> I assume it needs to much time, because it checks the visiblity of Done button, which might be taking a lot of time on some views because of internal XCTest limitations. Try to update Appium to the most recent version first

But in other simulators(such as iPhone 11 simulator), the same function can be executed in just a few seconds.
What are the differences between these simulators.

**Comment by mykola-mokhnach** [comment]
On tables there is a dedicated button, which allows to close the keyboard. Phones don't have it.

**Comment by lin907597898** [comment]
> On tables there is a dedicated button, which allows to close the keyboard. Phones don't have it.

ok, Thank you for your reply. I will try the latest version tomorrow to see if there is the same issue

**Comment by mykola-mokhnach** [comment]
Published an enhanced hideKeyboard helper to appium@beta
