### ISSUE TITLE
Appium Unable to click Video JS player Element  -  Issue seen only in Javascript client Webdriverio

### ISSUE THREAD

**Issue by only4arunkumar** [appium/appium#15039]
## The problem

Attempt to click on a button on Video Js player (nested in div) from android chrome browser was failing when using appium javascript client through webdriverio.  
User was able to interact with the button on desktop chrome browser, but it failed in android chrome.  
checks for visibility and clickable were able to find the element but invoking click on the same element was failing with no such element error.

Later C# client was used to perform the same action successfully

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: **macOS Big Sur Version 11.1**
* Node.js version (unless using Appium.app|exe): **14.15.4**
* Npm or Yarn package manager: **Npm**
* Mobile platform/version under test: **Android 11.0**
* Real device or emulator/simulator:**Emulator**
* Appium CLI or Appium.app|exe: **1.19.1 Electron:7.2.4  Node.js:12.8.1**
*  webdriverio: "^6.7.2"
* @wdio/cli": "^6.1.24",

## Details
The user was attempting to load the video url https://motivation.vudoo.io/embed/12373082862  in mobile chrome browser
and click the play button.The selector used to find the play button was "button.vjs-big-play-button" which is failing to find the element. But it works fine on desktop browser.

## Link to Appium logs

https://github.com/only4arunkumar/Video-JS-Appium/blob/main/javascript-webdriverio/Appium_logs

## Code To Reproduce Issue [ Good To Have ]
https://github.com/only4arunkumar/Video-JS-Appium/tree/main/javascript-webdriverio
https://github.com/only4arunkumar/Video-JS-Appium/blob/main/javascript-webdriverio/test/basic/android-create-web-session.test.js

**Comment by KazuCocoa** [comment]
It seems chromedriver has an issue with mobile chrome. Appium proxies requests to chromedriver, but nothing injects in Appium layer for Web context. The below error message is also by vanilla chromedriver.

```
{"value":{"error":"no such element","message":"no such element: Element_id length is invalid\n  (Session info: chrome=83.0.4103.106)","stacktrace":"0   chromedriver_mac64_v83.0.4103.39    0x000000010c0cee99 chromedriver_mac64_v83.0.4103.39 + 4808345\n1   chromedriver_mac64_v83.0.4103.39    0x000000010c0695f3 chromedriver_mac64_v83.0.4103.39 + 4392435\n2   chromedriver_mac64_v83.0.4103.39    0x000000010bcf529d chromedriver_mac64_v83.0.4103.39 + 770717\n3   chromedriver_mac64_v83.0.4103.39    0x000000010bc5e1c5 chromedriver_mac64_v83.0.4103.39 + 152005\n4   chromedriver_mac64_v83.0.4103.39    0x000000010bc5fdd6 chromedriver_mac64_v83.0.4103.39 + 159190\n5   chromedriver_mac64_v83.0.4103.39    0x000000010bc56dab chromedriver_mac64_v83.0.4103.39 + 122283\n6   chromedriver_mac64_v83.0.4103.39    0x000000010bc7b082 chromedriver_mac64_v83.0.4103.39 + 270466\n7   chromedriver_mac64_v83.0.4103.39    0x000000010bc56c36 chromedriver_mac64_v83.0.4103.39 + 121910\n8   chromedriver_mac64_v83.0.4103.39    0x000000010bc7b...
```

Thus, it would be better to report it to chromedriver side.

**Comment by only4arunkumar** [comment]
Thanks @KazuCocoa  for the inputs and time . But. when i used the C# appium client it started working fine.   The issue was primarily with appium javascript client.   I am not fully aware of the underlaying mechanism. Does both these client libraries call the same chrome driver

**Comment by KazuCocoa** [comment]
> But. when i used the C# appium client it started working fine.

Do you mean both mobile and desktop chrome worked well when you used C# client?

If your JS client and C# client code sent the below command to chromedriver (through Appium), they should work as same ideally.
```
[info] [35m[HTTP][39m [90m{"using":"css selector","value":"button.vjs-big-play-button"}
```
Mobile chrome behaves differently than the desktop one since their internal stuff could be different.

> Should i be raising the issue ...

https://chromedriver.chromium.org/ is the chromedriver root. You can report it to Google.

**Comment by only4arunkumar** [comment]
Thanks @KazuCocoa  shall raise an issue for chrome driver

**Comment by only4arunkumar** [comment]
@KazuCocoa  finally i got a response from chrome driver team. it seems like my code was passing the **css selector**  instead of **element-id** when making json-wp call .

**My code Initial code was.** 
client.elementClick(client.$("button.vjs-big-play-button")) which resulted in  following json-wp  call

wd/hub/session/9ccd19a813efe8c2c11d14cde6fd3b0c/element/button.vjs-big-play-button/click] with body: {}",

**My Code changed to following and its working fine**

 const playButton= client.$("button.vjs-big-play-button");
 client.elementClick((await playButton).**elementId**)

 /wd/hub/session/13365a18-cf1f-40b9-a132-3eae9b7cd86d/element/4254af87-1320-464a-8411-5f29d359e8c3/click
