### ISSUE TITLE
click element ineffective in webview

### ISSUE THREAD

**Issue by chandtler** [appium/appium#15040]
## The problem
Using QAF framework my automation script can be run passed. 
In Appium, I can successfully locate the element in WEBVIEW, but the CLICK action is ineffective.

## Environment

* Appium version: 1.18.0-2
* Desktop OS/version used to run Appium: MacOs
* Mobile platform/version under test: ios 13.6/ ios 14
* Real device or emulator/simulator: real device

## Details

the element's xpath is like this:  //*[@id="product_xxx"]//img

## Link to Appium logs

in Appium it didn't have any error
[quote]
[BaseDriver] "appium:cssSelectorsEnabled": true,

[BaseDriver] "appium:driverClass": "io.appium.java_client.ios.IOSDriver",

[BaseDriver] "appium:javascriptEnabled": true,

[BaseDriver] "platformName": "ios",

[BaseDriver] "appium:takesScreenshot": true,

[BaseDriver] "appium:automationName": "XCUITest",

[BaseDriver] "appium:clearSystemFiles": "true",

[BaseDriver] "appium:deviceName": "iPad (6th generation)",

[BaseDriver] "appium:noReset": "true",

[BaseDriver] "appium:platformVersion": "13.5.1",

[BaseDriver] "appium:startIWDP": "true",

[BaseDriver] "appium:udid": "bfe599b14c15fd50be470f714aee415a196a9317"
[/quote]

**Comment by KazuCocoa** [comment]
Please attach the full appium server log as gist

**Comment by chandtler** [comment]
> Please attach the full appium server log as gist. It helps us to understand your situation and environment.

hi KazuCocoa, I've added environment info of appium server

**Comment by mykola-mokhnach** [comment]
Please attach the full log. the provided information is not enough to understand what the issue is.

Also check https://appiumpro.com/editions/36-using-the-nativewebtap-capability

**Comment by mykola-mokhnach** [comment]
Closed because of no response
