### ISSUE TITLE
Server terminates when Session closes unexpectedly

### ISSUE THREAD

**Issue by TomBAMU** [appium/appium#15046]
## The problem

Since appium 1.20.0 the appium-server terminates when the client session closes unexpectedly. 
is this a expected behavior?

## Environment

* Appium version: 1.20.2 - Java-Client 7.4.1
* Last Appium version that did not exhibit the issue: 1.19.0
* Desktop OS/version used to run Appium: Linux (ubuntu docker image)
* Mobile platform/version under test: Android 6 (Espresso-Driver)
* Real device or emulator/simulator: Emulator or Real Device

**Comment by mykola-mokhnach** [comment]
Please describe the issue properly (steps, actual and the expected result). Also attach the server log

**Comment by mykola-mokhnach** [comment]
Closed because of no response
