### ISSUE TITLE
SetLocation not working in Android emulator running in headless mode

### ISSUE THREAD

**Issue by imablanco** [appium/appium#15055]
## The problem

setLocation method only works when running emulator in window mode.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.19.1
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Android
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: CLI

## Details

The execution running in headless mode results in the location not be set at all.

## Link to Appium logs

```
[HTTP] --> POST /wd/hub/session/d2adfffc-64d3-48fc-b77f-d4e21764f952/location
[HTTP] {"location":{"latitude":40.449866,"longitude":-3.668868,"altitude":75}}
[debug] [W3C (d2adfffc)] Calling AppiumDriver.setGeoLocation() with args: [{"latitude":40.449866,"longitude":-3.668868,"altitude":75},"d2adfffc-64d3-48fc-b77f-d4e21764f952"]
[debug] [ADB] Running '/Users/{user}/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 emu geo fix -3.66886 40.44987'
[debug] [ADB] Running '/Users/{user}/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 emu geo fix -3,66886 40,44987'
[debug] [ADB] Running '/Users/{user}/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am broadcast -n io.appium.settings/.receivers.LocationInfoReceiver -a io.appium.settings.location'
[debug] [ADB] Got geo coordinates: {"latitude":"37.42200","longitude":"-122.08400","altitude":"0.00000"}
[debug] [W3C (d2adfffc)] Responding to client with driver.setGeoLocation() result: {"latitude":37.422,"longitude":-122.084,"altitude":5e-324}
```

Also logs clearly show that returned location is different than requested one.

## Code To Reproduce Issue [ Good To Have ]
  @driver.set_location({:latitude => 40.449866, :longitude => -3.668868})

### Capabilities

caps:
  platformName: Android
  automationName: UiAutomator2
  app: './app/android_app.apk'
  noReset: false
  fullReset: true
  newCommandTimeout: 300
  autoGrantPermissions: true
  appActivity: '{appActivity}'
  appPackage: '{appPackage}'
  avd: 'Nexus_5_API_28_TEST'
  isHeadless: true
  language: 'en'
  locale: 'ES'
  mockLocationApp: 'io.appium.settings'

**Comment by mykola-mokhnach** [comment]
As you could see in the logs Appium simply executes `emu geo fix` commands. Only Google is able to fix this behaviour.

Closed as third party issue
