### ISSUE TITLE
Appium 2.0 Windows Driver Session Routing

### ISSUE THREAD

**Issue by sme81** [appium/appium#15059]
## The problem

Windows driver installed via 'appium driver install windows' (windows@1.18.0)

When attempting to create new session it fails.

## Environment

* Appium CLI version - 2.0.0-beta9
* Desktop OS - Windows 10
* Node.js - v14.15.4
* Npm - 6.14.11
* Mobile platform/version under test: Windows/UWP

## More Info

```
[debug] [HTTP] Request idempotency key: a6f5f6b8-b828-419f-9dc4-c5f04f2bdc60
[HTTP] --> POST /wd/hub/session
[HTTP] {"platformName":"WINDOWS","deviceName":"WINDOWS" ... desiredCapabilities Logged here but redacted}
[debug] [HTTP] No route found for /wd/hub/session
[HTTP] <-- POST /wd/hub/session 404 17 ms - 211
[HTTP]
```

**Comment by KazuCocoa** [comment]
probably i can take a look at this issue tonight

**Comment by KazuCocoa** [comment]
i haven't tested yet, but you could try out `appium server --base-path /wd/hub`

**Comment by sme81** [comment]
Thanks @KazuCocoa . Tried this morning,

- With Appium CLI it runs perfectly

On my Grid however it spits out 

`[debug] [BaseDriver] Event 'newSessionStarted' logged at 1611740514752 (09:41:54 GMT+0000 (Greenwich Mean Time))
[debug] [W3C] Encountered internal error running command: InvalidArgumentError: All non-standard capabilities should have a vendor prefix. The following capabilities did not have one: wdaLocalPort`

**Comment by KazuCocoa** [comment]
The error isexpected.
Appium 2.0 requires W3C spec capabilities, but probably your request does not have it.
So, `wdaLocalPort` should be `appium:wdaLocalPort`.

Appium clients add `appium:` for non-standard capabilities, but probably your grid does not have such behavior.

**Comment by sme81** [comment]
updated various capabilities, works both standalone and grid node. thanks

**Comment by ArsenTabaku** [comment]
I still have this issue. The potential solutions I have tried do not work. Any update?

**Comment by Auto81** [comment]
> I still have this issue. The potential solutions I have tried do not work. Any update?

What appium version are you on? Above comments still work on latest appium 2 for me

**Comment by ArsenTabaku** [comment]
> 



> > I still have this issue. The potential solutions I have tried do not work. Any update?
> 
> What appium version are you on? Above comments still work on latest appium 2 for me

I tried in v1.21.0 and also v1.17.1, but still no results. Could you please share a copy of your wdio file?

**Comment by Auto81** [comment]
I have installed appium 2 via

`npm i -g appium@next`

**Comment by bwomsm1** [comment]
Hi @KazuCocoa I am also facing that problem when I am working with Windows OS

I am not facing the problem with Mac OS,

What I should do with the Windows case?

**Comment by bwomsm1** [comment]
My appium server is launched with the following output:
```
[Appium] Welcome to Appium v2.0.0-beta.25
[Appium] Non-default server args:
[Appium] { basePath: 'C:/Program Files/Git/wd/hub' }
[Appium] Attempting to load driver windows...
[Appium] Attempting to load driver uiautomator2...
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[Appium] Available drivers:
[Appium]   - windows@1.21.0 (automationName 'Windows')
[Appium]   - uiautomator2@2.0.3 (automationName 'UiAutomator2')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
```

I launched appium server as follow:
```
appium --base-path /wd/hub
```

**Comment by KazuCocoa** [comment]
Perhaps Win env handles `/wd/hub` as since root path. We need to investigate it.

**Comment by bwomsm1** [comment]
> Perhaps Win env handles `/wd/hub` as since root path. We need to investigate it.

thanks,
Is there a ticket for this issue that I can follow?

**Comment by KazuCocoa** [comment]
I ran the latest appium as below in powershell on Win 10:
```
(in node_modules/appium by npm install appium@next)
> node . --base-path /wd/hub
[Appium] Welcome to Appium v2.0.0-beta.25
[Appium] Non-default server args:
[Appium] {
[Appium]   basePath: '/wd/hub'
[Appium] }
[Appium] Attempting to load driver windows...
[Appium] Attempting to load driver uiautomator2...
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[Appium] Available drivers:
[Appium]   - windows@2.0.1 (automationName 'Windows')
[Appium]   - uiautomator2@2.0.3 (automationName 'UiAutomator2')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"2.0.0-beta.25"}}
[HTTP] <-- GET /wd/hub/status 304 21 ms - -
```

Could you create an issue with about your environment? @bwomsm1

**Comment by bwomsm1** [comment]
> I ran the latest appium as below in powershell on Win 10:
> 
> ```
> (in node_modules/appium by npm install appium@next)
> > node . --base-path /wd/hub
> [Appium] Welcome to Appium v2.0.0-beta.25
> [Appium] Non-default server args:
> [Appium] {
> [Appium]   basePath: '/wd/hub'
> [Appium] }
> [Appium] Attempting to load driver windows...
> [Appium] Attempting to load driver uiautomator2...
> [Appium] Appium REST http interface listener started on 0.0.0.0:4723
> [Appium] Available drivers:
> [Appium]   - windows@2.0.1 (automationName 'Windows')
> [Appium]   - uiautomator2@2.0.3 (automationName 'UiAutomator2')
> [Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
> [HTTP] --> GET /wd/hub/status
> [HTTP] {}
> [debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
> [debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"2.0.0-beta.25"}}
> [HTTP] <-- GET /wd/hub/status 304 21 ms - -
> ```
> 
> Could you create an issue with about your environment? @bwomsm1

@KazuCocoa I noticed of version appium-windows-driver `2.0.1`,
`Properly set base path for the proxy (https://github.com/appium/appium-windows-driver/issues/122) ([d37f5e3](https://github.com/appium/appium-windows-driver/commit/d37f5e37521a7b6646a45275beb9e688b0aa13bc))` 
Does opening a ticket for the issue is still needed?

**Comment by KazuCocoa** [comment]
ok, then no need. 2.x in Win is for Appium 2, officially.

**Comment by bwomsm1** [comment]
> ok, then no need. 2.x in Win is for Appium 2, officially.

@KazuCocoa I am currently still running with the beta version, I am not aware how to install 2.0.0
Can you please instruct me how to install that 2.0.1 version?

My version list is:
$ appium driver list
- Listing available drivers
√ Listing available drivers
- windows@1.21.1 [installed (NPM)]
- uiautomator2@2.0.3 [installed (NPM)]
- xcuitest [not installed]
- youiengine [not installed]
- mac [not installed]
- mac2 [not installed]
- espresso [not installed]
- tizen [not installed]
- flutter [not installed]
- safari [not installed]
- gecko [not installed]

**Comment by bwomsm1** [comment]
@KazuCocoa I managed to install version `2.0.1` with ` appium driver update installed --unsafe`,
But I am still facing the same problem, my appium server cli is:
` appium --base-path /wd/hub`, I also tried running without the base-path

Not sure what to do here...

**Comment by KazuCocoa** [comment]
Please create an issue with your running environment and appium logs

**Comment by bwomsm1** [comment]
> Please create an issue with your running environment and appium logs

Done:
https://github.com/appium/appium/issues/16489

**Comment by mchasaegh** [comment]
> The error is expected. Appium 2.0 requires W3C spec capabilities, but probably your request does not have it. So, `wdaLocalPort` should be `appium:wdaLocalPort`.
> 
> Appium clients add `appium:` for non-standard capabilities, but probably your grid does not have such behavior.

@KazuCocoa  thanks, the prefix was missing in my case. Any place/docs once can look for such issues at?

**Comment by KazuCocoa** [comment]
we're still working on documentation, but you can find it in https://github.com/appium/appium/blob/2.0/docs/en/advanced-concepts/migrating-to-appium-2.0.md#bangbang-capabilities
