### ISSUE TITLE
Getting io.appium.java_client.NoSuchContextException: when switching from native to webview 

### ISSUE THREAD

**Issue by saurabhbhandari12** [appium/appium#15054]
## The problem

We are faicng io.appium.java_client.NoSuchContextException: whenever we are trying to switch from native to webview .
## Environment

* Appium version (or git revision) that exhibits the issue:v1.20
* Last Appium version that did not exhibit the issue (if applicable):v1.15
* Desktop OS/version used to run Appium: Ubuntu 
* Node.js version (unless using Appium.app|exe):v15.5.0
* Npm or Yarn package manager:6.14.10
* Mobile platform/version under test:Android 10
* Real device or emulator/simulator:emulators
* Appium CLI or Appium.app|exe:Appium CLI
* java - 11

## Details
We are faicng io.appium.java_client.NoSuchContextException: whenever we are trying to switch from native to webview .

## Link to Appium logs
https://gist.github.com/saurabhbhandari12/eedae85be8d841e5b289001beae61c9f

**Comment by mykola-mokhnach** [comment]
> io.appium.java_client.NoSuchContextException: An unknown server-side error occurred while processing the command. Original error: A new session could not be created. Details: session not created: This version of ChromeDriver only supports Chrome version 86

Please refer to https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md and provide a correct matching Chrome driver version to your test

Closed as not an issue
