### ISSUE TITLE
Can't run more than one devices in parallel

### ISSUE THREAD

**Issue by Eloon** [appium/appium#15057]
## The problem

I can only run appium to control one device, but failed on second device with error: 
Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20300ms.

i do follow the instrution : https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/parallel-tests.md ,  use diffrence udid  and systemPort

output of adb devices
List of devices attached
**emulator-5554   device
emulator-5556   device**

**appium server session 1:** 

> appium --session-override -a 127.0.0.1 **-p 4723 -bp 4724** --log-timestamp --local-timezone

> appioumSession numbers 2， name:emulator-5554, userId:0,
> connPort:{'port': '4723', 'bport': '4724'},
> desir_cap：{'platformName': 'Android', 'platformVersion': '7.1.2', **'deviceName': 'emulator-5554'****, 'udid': 'emulator-5554',** 'appPackage': 'com.smile.gifmaker', 'appActivity': 'com.yxcorp.gifshow.HomeActivity', 'newCommandTimeout': 20000, 'androidDeviceReadyTimeout': 10, 'autoLaunch': False, 'noReset': True, 'fullReset': False,
> 'automationName': 'UiAutomator2', 'autoGrantPermissions': True, **'adbPort': 5037, 'systemPort': 8200,** 'ensureWebviewsHavePages': True, 'printPageSourceOnFindFailure': True, 'userProfile': 0, 'optionalIntentArguments': 'text --user 0'}

**appium server session 2:** 

> appium --session-override -a 127.0.0.1 -p 4725 -bp 4726 --log-timestamp --local-timezone

> connPort:{'port': '4725', 'bport': '4726'},
> desir_cap：{'platformName': 'Android', 'platformVersion': '7.1.2'**, 'deviceName': 'emulator-5556', 'udid': 'emulator-5556',** 'appPackage': 'com.smile.gifmaker', 'appActivity': 'com.yxcorp.gifshow.HomeActivity', 'newCommandTimeout': 20000, 'androidDeviceReadyTimeout': 10, 'autoLaunch': False, 'noReset': True, 'fullReset': False,
> 'automationName': 'UiAutomator2', 'autoGrantPermissions': True, **'adbPort': 5041, 'systemPort': 8204,** 'ensureWebviewsHavePages': True, 'printPageSourceOnFindFailure': True, 'userProfile': 0, 'optionalIntentArguments': 'text --user 0'}
> 

## Environment

* Appium version (or git revision) that exhibits the issue:  1.18.3
* Mobile platform/version under test: android 7.1.2
* Real device or emulator/simulator: simulator

## Details

code to connect appium server:

      driver = webdriver.Remote("http://localhost:" + port + "/wd/hub",  desir_cap)

## Link to Appium logs

The appium log for starting the first session: **SUCCESS**

> 
> _2021-01-26 00:34:53:513 - [Appium] Appium v1.18.3 creating new AndroidUiautomator2Driver (v1.56.1) session
> 2021-01-26 00:34:53:513 - [debug] [Appium] There are no active sessions for cleanup
> 2021-01-26 00:34:53:517 - [debug] [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
> 2021-01-26 00:34:53:517 - [debug] [BaseDriver] Creating session with W3C capabilities: {
> 2021-01-26 00:34:53:517 - [debug] [BaseDriver]   "alwaysMatch": {
> 2021-01-26 00:34:53:518 - [debug] [BaseDriver]     "platformName": "Android",
> 2021-01-26 00:34:53:518 - [debug] [BaseDriver]     "appium:platformVersion": "7.1.2",
> 2021-01-26 00:34:53:518 - [debug] [BaseDriver]     "appium:deviceName": "emulator-5554",
> 2021-01-26 00:34:53:518 - [debug] [BaseDriver]     "appium:udid": "emulator-5554",
> 2021-01-26 00:34:53:519 - [debug] [BaseDriver]     "appium:appPackage": "com.smile.gifmaker",
> 2021-01-26 00:34:53:519 - [debug] [BaseDriver]     "appium:appActivity": "com.yxcorp.gifshow.HomeActivity",
> 2021-01-26 00:34:53:519 - [debug] [BaseDriver]     "appium:newCommandTimeout": 20000,
> 2021-01-26 00:34:53:520 - [debug] [BaseDriver]     "appium:androidDeviceReadyTimeout": 10,
> 2021-01-26 00:34:53:520 - [debug] [BaseDriver]     "appium:autoLaunch": false,
> 2021-01-26 00:34:53:520 - [debug] [BaseDriver]     "appium:noReset": true,
> 2021-01-26 00:34:53:520 - [debug] [BaseDriver]     "appium:fullReset": false,
> 2021-01-26 00:34:53:521 - [debug] [BaseDriver]     "appium:automationName": "UiAutomator2",
> 2021-01-26 00:34:53:521 - [debug] [BaseDriver]     "appium:autoGrantPermissions": true,
> 2021-01-26 00:34:53:521 - [debug] [BaseDriver]     "appium:adbPort": 5037,
> 2021-01-26 00:34:53:521 - [debug] [BaseDriver]     "appium:systemPort": 8200,
> 2021-01-26 00:34:53:522 - [debug] [BaseDriver]     "appium:ensureWebviewsHavePages": true,
> 2021-01-26 00:34:53:522 - [debug] [BaseDriver]     "appium:printPageSourceOnFindFailure": true,
> 2021-01-26 00:34:53:522 - [debug] [BaseDriver]     "appium:userProfile": 0,
> 2021-01-26 00:34:53:522 - [debug] [BaseDriver]     "appium:optionalIntentArguments": "text --user 0"
> 2021-01-26 00:34:53:523 - [debug] [BaseDriver]   },
> 2021-01-26 00:34:53:523 - [debug] [BaseDriver]   "firstMatch": [
> 2021-01-26 00:34:53:524 - [debug] [BaseDriver]     {}
> 2021-01-26 00:34:53:524 - [debug] [BaseDriver]   ]
> 2021-01-26 00:34:53:524 - [debug] [BaseDriver] }
> 2021-01-26 00:34:53:533 - [BaseDriver] Session created with session id: eb317824-a261-4246-8a5a-5621f6fc87fd
> 2021-01-26 00:34:53:533 - [UiAutomator2] Starting 'com.smile.gifmaker' directly on the device
> 2021-01-26 00:34:53:541 - [ADB] Found 1 'build-tools' folders under 'c:\Users\xxxx\cmdline-tools\' (newest first):
> 2021-01-26 00:34:53:541 - [ADB]     c:/Users/xxxx/cmdline-tools/build-tools/30.0.2
> 2021-01-26 00:34:53:542 - [ADB] Using 'adb.exe' from 'c:\Users\xxxx\cmdline-tools\platform-tools\adb.exe'
> 2021-01-26 00:34:53:544 - [debug] [ADB] Running 'c:\Users\xxxx\cmdline-tools\platform-tools\adb.exe -P 5037 start-server'
> 2021-01-26 00:34:53:644 - [AndroidDriver] Retrieving device list
> 2021-01-26 00:34:53:644 - [debug] [ADB] Trying to find a connected android device
> 2021-01-26 00:34:53:645 - [debug] [ADB] Getting connected devices
> 2021-01-26 00:34:53:750 - [debug] [ADB] Connected devices: [{"udid":"emulator-5554","state":"device"},{"udid":"emulator-5556","state":"device"}]
> 2021-01-26 00:34:53:751 - [AndroidDriver] Using device: emulator-5554
> 2021-01-26 00:34:53:753 - [ADB] Using 'adb.exe' from 'c:\Users\xxxx\cmdline-tools\platform-tools\adb.exe'
> 2021-01-26 00:34:53:753 - [debug] [ADB] Running 'c:\Users\xxxx\cmdline-tools\platform-tools\adb.exe -P 5037 start-server'
> 2021-01-26 00:34:53:844 - [debug] [ADB] Setting device id to emulator-5554
> 2021-01-26 00:34:53:845 - [debug] [ADB] Running 'c:\Users\xxxx\cmdline-tools\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk'
> 2021-01-26 00:34:53:947 - [debug] [ADB] Current device property 'ro.build.version.sdk': 25
> 2021-01-26 00:34:53:947 - [debug] [ADB] Device API level: 25
> 2021-01-26 00:34:53:948 - [AndroidDriver] No app sent in, not parsing package/activity
> 2021-01-26 00:34:53:948 - [debug] [ADB] Running 'c:\Users\xxxx\cmdline-tools\platform-tools\adb.exe -P 5037 -s emulator-5554 wait-for-device'
> 2021-01-26 00:34:54:045 - [debug] [ADB] Running 'c:\Users\xxxx\cmdline-tools\platform-tools\adb.exe -P 5037 -s emulator-5554 shell echo ping'
> 2021-01-26 00:34:54:147 - [debug] [AndroidDriver] Pushing settings apk to device...
> 2021-01-26 00:34:54:148 - [debug] [ADB] Getting install status for io.appium.settings
> 2021-01-26 00:34:54:148 - [debug] [ADB] Running 'c:\Users\xxxx\cmdline-tools\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys package io.appium.settings'
> 2021-01-26 00:34:54:299 - [debug] [ADB] 'io.appium.settings' is installed
> 2021-01-26 00:34:54:299 - [debug] [ADB] Getting package info for 'io.appium.settings'_

The appium log for starting the second session: **FAIL**

> _2021-01-26 00:31:49:017 - [Appium] Appium v1.18.3 creating new AndroidUiautomator2Driver (v1.56.1) session
> 2021-01-26 00:31:49:019 - [debug] [Appium] There are no active sessions for cleanup
> 2021-01-26 00:31:49:023 - [debug] [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
> 2021-01-26 00:31:49:024 - [debug] [BaseDriver] Creating session with W3C capabilities: {
> 2021-01-26 00:31:49:026 - [debug] [BaseDriver]   "alwaysMatch": {
> 2021-01-26 00:31:49:027 - [debug] [BaseDriver]     "platformName": "Android",
> 2021-01-26 00:31:49:028 - [debug] [BaseDriver]     "appium:platformVersion": "7.1.2",
> 2021-01-26 00:31:49:029 - [debug] [BaseDriver]     "appium:deviceName": "emulator-5556",
> 2021-01-26 00:31:49:030 - [debug] [BaseDriver]     "appium:udid": "emulator-5556",
> 2021-01-26 00:31:49:067 - [debug] [BaseDriver]     "appium:appPackage": "com.smile.gifmaker",
> 2021-01-26 00:31:49:078 - [debug] [BaseDriver]     "appium:appActivity": "com.yxcorp.gifshow.HomeActivity",
> 2021-01-26 00:31:49:079 - [debug] [BaseDriver]     "appium:newCommandTimeout": 20000,
> 2021-01-26 00:31:49:081 - [debug] [BaseDriver]     "appium:androidDeviceReadyTimeout": 10,
> 2021-01-26 00:31:49:083 - [debug] [BaseDriver]     "appium:autoLaunch": false,
> 2021-01-26 00:31:49:084 - [debug] [BaseDriver]     "appium:noReset": true,
> 2021-01-26 00:31:49:085 - [debug] [BaseDriver]     "appium:fullReset": false,
> 2021-01-26 00:31:49:086 - [debug] [BaseDriver]     "appium:automationName": "UiAutomator2",
> 2021-01-26 00:31:49:086 - [debug] [BaseDriver]     "appium:autoGrantPermissions": true,
> 2021-01-26 00:31:49:087 - [debug] [BaseDriver]     "appium:adbPort": 5041,
> 2021-01-26 00:31:49:092 - [debug] [BaseDriver]     "appium:systemPort": 8204,
> 2021-01-26 00:31:49:093 - [debug] [BaseDriver]     "appium:ensureWebviewsHavePages": true,
> 2021-01-26 00:31:49:101 - [debug] [BaseDriver]     "appium:printPageSourceOnFindFailure": true,
> 2021-01-26 00:31:49:102 - [debug] [BaseDriver]     "appium:userProfile": 0,
> 2021-01-26 00:31:49:102 - [debug] [BaseDriver]     "appium:optionalIntentArguments": "text --user 0"
> 2021-01-26 00:31:49:103 - [debug] [BaseDriver]   },
> 2021-01-26 00:31:49:106 - [debug] [BaseDriver]   "firstMatch": [
> 2021-01-26 00:31:49:107 - [debug] [BaseDriver]     {}
> 2021-01-26 00:31:49:112 - [debug] [BaseDriver]   ]
> 2021-01-26 00:31:49:113 - [debug] [BaseDriver] }
> 2021-01-26 00:31:49:139 - [BaseDriver] Session created with session id: 93e526ab-0698-4b41-8f80-40ec5debcc7c
> 2021-01-26 00:31:49:141 - [UiAutomator2] Starting 'com.smile.gifmaker' directly on the device
> 2021-01-26 00:31:49:190 - [ADB] Found 1 'build-tools' folders under 'c:\Users\xxxx\cmdline-tools\' (newest first):
> 2021-01-26 00:31:49:191 - [ADB]     c:/Users/xxxx/cmdline-tools/build-tools/30.0.2
> 2021-01-26 00:31:49:196 - [ADB] Using 'adb.exe' from 'c:\Users\xxxx\cmdline-tools\platform-tools\adb.exe'
> 2021-01-26 00:31:49:205 - [debug] [ADB] Running 'c:\Users\xxxx\cmdline-tools\platform-tools\adb.exe -P 5041 start-server'
> 2021-01-26 00:31:50:585 - [AndroidDriver] Retrieving device list
> 2021-01-26 00:31:50:585 - [debug] [ADB] Trying to find a connected android device
> 2021-01-26 00:31:50:586 - [debug] [ADB] Getting connected devices
> 2021-01-26 00:31:50:709 - [debug] [ADB] No connected devices have been detected
> 2021-01-26 00:31:50:710 - [debug] [ADB] Could not find online devices
> 2021-01-26 00:31:50:710 - [debug] [ADB] Reconnecting adb (target offline)
> 2021-01-26 00:31:50:711 - [debug] [ADB] Running 'c:\Users\xxxx\cmdline-tools\platform-tools\adb.exe -P 5041 reconnect offline'
> 2021-01-26 00:31:51:034 - [debug] [ADB] Getting connected devices
> 2021-01-26 00:31:51:135 - [debug] [ADB] No connected devices have been detected
> 2021-01-26 00:31:51:135 - [debug] [ADB] Could not find online devices
> 2021-01-26 00:31:51:135 - [debug] [ADB] Reconnecting adb (target offline)
> 2021-01-26 00:31:51:136 - [debug] [ADB] Running 'c:\Users\xxxx\cmdline-tools\platform-tools\adb.exe -P 5041 reconnect offline'
> 2021-01-26 00:31:51:431 - [debug] [ADB] Getting connected devices
> 2021-01-26 00:31:51:520 - [debug] [ADB] No connected devices have been detected
> 2021-01-26 00:31:51:520 - [debug] [ADB] Could not find online devices
> 2021-01-26 00:31:51:520 - [debug] [ADB] Reconnecting adb (target offline)_
>

**Comment by mykola-mokhnach** [comment]
Please use `avd` property to provide the emulator name

**Comment by Eloon** [comment]
@mykola-mokhnach  i found the rootcause 

i used difference adbPort in desir_cap, actually all the adbPort should the same. i.e.  'adbPort': 5037 
 
This issue could be closed. thanks your support
