### ISSUE TITLE
Appium 2.0 Windows Driver Install

### ISSUE THREAD

**Issue by sme81** [appium/appium#15056]
## The problem
Can't install windows driver for appium 2.0.x.

Installed latest appium via cmd '_npm i -g appium@next_'

'_appium driver install uiautomator2_' works fine.

'_appium driver install windows_' fails with error _'Encountered an error when installing package: Installed driver did not have an 'appium' section in its package.json file as expected'_.

## Environment

* Appium CLI version - 2.0.0-beta9
* Desktop OS - Windows 10
* Node.js - v14.15.4
* Npm - 6.14.11
* Mobile platform/version under test: Windows/UWP

**Comment by mykola-mokhnach** [comment]
cc @jlipps

**Comment by jlipps** [comment]
Yes, will address.

**Comment by jlipps** [comment]
PR fix up: https://github.com/appium/appium-windows-driver/pull/96
