### ISSUE TITLE
Appium unable to get the page source on native view for hybrid app

### ISSUE THREAD

**Issue by JayasreeA** [appium/appium#15052]
## The problem

Appium unable to get the complete page source on native view . This was working until 10th of December 2020 with same Appium version . 
This issue is found in Microsoft Login page used in a hybrid mobile app. 

NOTE : It works fine when **uiautomator1** is set in the capability  

## Environment

* Appium version (or git revision) that exhibits the issue: 1.19.1
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager: 6.4.1
* Mobile platform/version under test: Android  8, 9,10 (Samsung Galaxy )
* Real device or emulator/simulator:  Real device
* Appium CLI or Appium.app|exe: 1.19.1

## Link to Appium logs

Logs when UIAutomator2 is used by default :  https://gist.github.com/JayasreeA/805c45c6d7f8a7740766aabec958fd58

Logs when UIAuotmator1 is set in the capability : https://gist.github.com/JayasreeA/ad5c9cf35f321cdd47c4e8249eee94bd

## Link to Page source
Page DOM  with UIAutomator2 :  https://gist.github.com/JayasreeA/4b724a9da9619d10fdfbb15f90243dc9

Page DOM with UIAutomator1 : https://gist.github.com/JayasreeA/c5ec94e21f3924e6a687fa0b452b2a78

**Comment by KazuCocoa** [comment]
>  This was working until 10th of December 2020

What does this mean? Different Appium versions?

----

Potentially, androidx.test.uiautomator behaves so in UIA2, while com.android.uiautomator behaves a bit differently in UIA1.
Then, potentially it is Android API internal thing.

**Comment by JayasreeA** [comment]
> > This was working until 10th of December 2020
> 
> What does this mean? Different Appium versions?
> 
@KazuCocoa  with same appium version.
There was web view update on the devices around the same time but I tried with a device having older web view and see the same issue. 
Thanks

**Comment by KazuCocoa** [comment]
Thanks.

May enableMultiWindows capability help?

Afaik, the root windows data in UIA2 is https://github.com/appium/appium-uiautomator2-server/blob/1b96430bd5bf89d17c592c443474bad557985ca3/app/src/main/java/io/appium/uiautomator2/utils/AXWindowHelpers.java#L86 , so one possible cause is the view has multiple views.

-----

notes:

uia1: https://github.com/appium/appium-android-driver/blob/9d120ba76df18ada8c5793af3d42f9b1aa4937cb/bootstrap/src/io/appium/uiautomator/core/AccessibilityNodeInfoDumper.java
uia2: https://github.com/appium/appium-uiautomator2-server/blob/1b96430bd5bf89d17c592c443474bad557985ca3/app/src/main/java/io/appium/uiautomator2/model/UiElementSnapshot.java#L182

**Comment by mykola-mokhnach** [comment]
I would check if `allowInvisibleElements` and/or `ignoreUnimportantViews` [settings](https://github.com/appium/appium-uiautomator2-driver#settings-api) influence the visibility of these views in the page source

**Comment by JayasreeA** [comment]
@mykola-mokhnach  Thanks for your suggestions. I have tried with those capability settings -allowInvisibleElements   (true) and ignoreUnimportantViews (false) . It didn't work
 
@KazuCocoa  Thanks , I tried now with enableMultiWindows set to true but it shows only Android frame widget .

**Comment by mykola-mokhnach** [comment]
I don't have any other ideas to that. You could try to go through the actual server implementation and debug it locally with your application under test: https://github.com/appium/appium-uiautomator2-server/blob/a4aa655238d8cc3e7c064fd3d73037d747939f73/app/src/main/java/io/appium/uiautomator2/model/UiElementSnapshot.java#L219

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
