### ISSUE TITLE
Unable to execute appium webdriverio test on Kobiton resulting in  - Always attempts to connect to local server

### ISSUE THREAD

**Issue by only4arunkumar** [appium/appium#15068]
## The problem

Attempting to execute appium test on Kobiton  is throwing following error , 
     
 ERROR webdriver: RequestError: connect ECONNREFUSED 127.0.0.1:4723.

i dont have local appium running , i am trying to execute the scripts on Kobiton

**Already set the proxy settings to null  in npm config** 

 proxy=null
; https-proxy=null
; noproxy=null

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS Big Sur 11
* Node.js version (unless using Appium.app|exe):14.15.4
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Android -on Kobiton
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe: APPIUM CLI

## Details

The healper/caps.js file in the following [repo](https://github.com/appium/appium/tree/master/sample-code/javascript-webdriverio) was modified to execute the test on Kobiton

const serverConfig = {
  protocol: 'https',
  port: 4723,
  path: '/wd/hub',
  host: 'api.kobiton.com',
  auth: '<<username>>:<<key>>'   --- removed from here for security 
  
}

const androidWebCaps = {
  // The generated session will be visible to you only. In case you want this session available for other users, please assign this device to specific group. 
  sessionName:        'Automation test session',
  sessionDescription: '',
  deviceOrientation:  'portrait',
  captureScreenshots: true,
  browserName:        'chrome',
  deviceGroup:        'KOBITON',
  deviceName:         'Galaxy S7',
  platformVersion:    '8.0.0',
  platformName:       'Android'
} 

const androidWebOptions = Object.assign(
  {
    capabilities: androidWebCaps
  },
  serverConfig

);

## Code To Reproduce Issue [ Good To Have ]

https://github.com/appium/appium/tree/master/sample-code/javascript-webdriverio 
please include the changes mentioned above to caps.js  file 

![image](https://user-images.githubusercontent.com/4882688/106142608-cbc3f200-61c5-11eb-9dae-e2de506aa9f7.png)

**Comment by mykola-mokhnach** [comment]
Please ask at WDIO issues tracker or at Appium forum.

Closed as not an issue
