### ISSUE TITLE
New tools, support Launch WDA without xcodebuild, and can be run in Windows and Linux

### ISSUE THREAD

**Issue by codeskyblue** [appium/appium#15063]
## Why create this issue.
I really do not know where to share my new repo. But I believe this tool can help appium iOS automation.

<https://github.com/alibaba/tidevice>

With tidevice, launch WDA can without xcode. tidevice simulate xcodebuild behavior to communite with iPhone through usbmuxd.

So tidevice only require usbmuxd service running. and Windows can also have usbmuxd service, so it is possible to run on windows.

Screenshot

![image](https://user-images.githubusercontent.com/3281689/105958119-2883b780-60b5-11eb-9de5-b2e5b32cac7f.png)

**Comment by mykola-mokhnach** [comment]
Thanks for the heads-up @codeskyblue 

We are already using [idb](https://github.com/facebook/idb) for similar purpose. We were never targeting Windows as there are a couple of other dependencies on shell utilities and it would be a huge addition to unify these.
Also Appium has its own module for interaction with real devices: https://github.com/appium/appium-ios-device. Would you mind contributing to it?

**Comment by codeskyblue** [comment]
This repo looks great  https://github.com/appium/appium-ios-device

**Comment by codeskyblue** [comment]
Thanks @mykola-mokhnach , can idb support running xctest on real devices?

**Comment by mykola-mokhnach** [comment]
According to the documentation it does, but it only supports macOS. Check the `launchWithIDB` [capability](https://github.com/appium/appium-xcuitest-driver#other) for more details

**Comment by KazuCocoa** [comment]
interesting 👀

**Comment by amedvedjev** [comment]
@mykola-mokhnach latest xCode, ios 14.3, beta appium and `launchWithIDB` enabled - wow. problems of parallel run vanished (no need create WDA for each appium session or synchronize driver start). fast driver start left same 2 sec as with xcode build. thanks!
![image](https://user-images.githubusercontent.com/2756856/106117791-0db84e00-615c-11eb-82e0-8e465eb0b7b7.png)

**Comment by krishtoautomate** [comment]
@amedvedjev do you have code sample to start driver for lauchwithidb capability
