### ISSUE TITLE
Error: timeout of 1000ms

### ISSUE THREAD

**Issue by tranduyminh91** [appium/appium#15067]
## The problem

I open Appium inspector with iOS cloud device and I got this error "Error: timeout of 1000ms"
I tried to increase every kind of timeout but not successful. Please guideline me how to increase it.

My Desired Capabilities:
```
{
  "deviceName": "iphone6s",
  "platformName": "IOS",
  "udid": "abb801b1dbfd14ce0960a50a28d9e7424077b579",
  "bundleId": "xxxxxxxxx",
  "automationName": "XCUITest",
  "wdaConnectionTimeout": 1000000,
  "newCommandTimeout": 15000,
  "wdaLaunchTimeout": 1000000,
  "wdaStartupRetryInterval": 500000,
  "showXcodeLog": true,
  "usePrebuiltWDA": true,
  "wdaLocalPort": 8100,
  "waitForIdleTimeout": 30000,
  "wdaEventloopIdleDelay": 10
}
```

## Environment

* Appium version: 1.19.1
* Desktop OS/version used to run Appium: Mac OS bigger 11.1
* Xcode version: 11.6
* Node.js version (unless using Appium.app|exe): 12.8.1
* Npm or Yarn package manager:
* Mobile platform/version under test: iPhone X version 13.6
* Real device or emulator/simulator: real device on cloud
* Appium CLI or Appium.app|exe: Appium desktop

## Details

I think it is api request timeout

## Link to Appium logs

[https://gist.github.com/tranduyminh91/910d6005742b9656ea22444fa1a1d872](url)

![Image 9 (1)](https://user-images.githubusercontent.com/48478019/106114744-7f0af780-6182-11eb-88c6-77c346ccdec5.png)

**Comment by mykola-mokhnach** [comment]
I don't observe any issues from the Appium server side here. Consider reporting your issue to the appropriate cloud provider's customer support

**Comment by tranduyminh91** [comment]
> I don't observe any issues from the Appium server side here. Consider reporting your issue to the appropriate cloud provider's customer support

I need to increase "1000ms" time that highlighting as red square in attachment. Does Appium have any caps to increase it?

**Comment by mykola-mokhnach** [comment]
This timeout is not configurable. It is hardcoded in https://github.com/appium/WebDriverAgent/blob/651528c5deec9fbbba4decb2b3376900e3d51b10/lib/xcodebuild.js#L375

**Comment by tranduyminh91** [comment]
Hi my kola-mokhnach,

Thank for point out it. Can I change timeout by edit it direct in Xcodebuild.js file
