### ISSUE TITLE
Get command to launch the iOS app on simulator

### ISSUE THREAD

**Issue by ganjarpanji** [appium/appium#15060]
## The problem

Hi sorry if im asking here, i didn't get any reply or help from discuss.appium forum,
Context : i got an issue on my app which always logged out when its launched by appium, but unfortunately its not possible to debug with the xcode itself. my other hypothesis was the command that launch the app from the simulator is the culprit.

my question : can you help guide me what is the command used by appium to launch the app in the ios simulator? i watn to reproduce the launch app by myself manually. THanks!

**Comment by KazuCocoa** [comment]
https://developer.apple.com/documentation/xctest/xcuiapplication/1500467-launch?language=objc is like https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/WebDriverAgentLib/Routing/FBSession.m#L204

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium-xcuitest-driver#mobile-launchapp
