### ISSUE TITLE
Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up 

### ISSUE THREAD

**Issue by chuklov** [appium/appium#15065]
## The problem

I start facing the same error as described in #14645 
Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up

## Environment

Appium version (or git revision) that exhibits the issue: 1.18.3
Last Appium version that did not exhibit the issue (if applicable): 1.18.3
Desktop OS/version used to run Appium: 1.18.3
Node.js version (unless using Appium.app|exe): v15.0.1
Npm or Yarn package manager: npm@7.0.3
Mobile platform/version under test: iOS
Real device or emulator/simulator: Real device
Appium CLI or Appium.app|exe: automation from Intellij IDEA also from Appium desktop

## Details

Starting a few days ago I am getting this error about 10-30 times a day. (I'm running about 60 to 100 tests a day)
I'm not sure which logs are relevant and which flags I need to add in capabilities, so please let me know. 

## Link to Appium logs

`[debug] [W3C (ef8342ad)] Calling AppiumDriver.getPageSource() with args: ["ef8342ad-3d05-4b8e-bc3b-f6ad197e98e1"]
[debug] [XCUITest] Executing command 'getPageSource'
[debug] [WD Proxy] Matched '/source' to command name 'getPageSource'
[debug] [WD Proxy] Proxying [GET /source] to [GET http://127.0.0.1:58018/session/B422BF7F-9DB2-4CA6-8869-831794F220CA/source] with no body
[WD Proxy] socket hang up
[debug] [W3C (ef8342ad)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
[debug] [W3C (ef8342ad)]     at JWProxy.command (/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:275:13)
[debug] [W3C (ef8342ad)]     at XCUITestDriver.proxyCommand (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:96:12)
[debug] [W3C (ef8342ad)]     at XCUITestDriver.getNativePageSource (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/source.js:25:17)
[debug] [W3C (ef8342ad)]     at XCUITestDriver.getPageSource (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/source.js:21:10)
[HTTP] <-- GET /wd/hub/session/ef8342ad-3d05-4b8e-bc3b-f6ad197e98e1/source 500 35 ms - 987
[HTTP] 
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'chuklova-macmin.local', ip: 'fe80:0:0:0:1c7f:c42:cd7f:5eae%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '11.0.9'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities {agentPath: /usr/local/lib/node_modules..., appiumVersion: 1.18.3, automationName: XCUITest, bootstrapPath: /usr/local/lib/node_modules..., browserName: , bundleId: com.apple.mobilesafari, clearSystemFiles: true, databaseEnabled: false, deviceName: iPhone, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: false, newCommandTimeout: 600, noReset: true, platform: MAC, platformName: ios, preventWDAAttachments: true, showIOSLog: false, showXCODELog: false, takesScreenshot: true, udid: bd3ccfde1c14ef869656292b046..., useNewWDA: false, usePrebuiltWDA: true, wdaLocalPort: 58018, webStorageEnabled: false, webkitDebugProxyPort: 58034, xcodeOrgId: 2ES97B4EP7, xcodeSigningId: iPhone Developer}
Session ID: ef8342ad-3d05-4b8e-bc3b-f6ad197e98e1`

## Code To Reproduce Issue [ Good To Have ]

Happens too random and in many different places.

**Comment by chuklov** [comment]
<script src="https://gist.github.com/chuklov/816ebb328ba9c2b1cd4d51b39442a8c4.js"></script>

**Comment by mykola-mokhnach** [comment]
There might be multiple causes to this issue, for example WDA server died, frozen, network communication issues, etc. Sometimes device logs investigation might help. Also make sure you use the most recent server version.

**Comment by chuklov** [comment]
@mykola-mokhnach  With the latest version I have exactly the same issue. 
After the error I can see that the session is still alive, connection to the device is not broken, basically only the test failed and the rest continues. 
In a new log I have run 16 tests and 2 failed with this error. 
[https://gist.github.com/chuklov/b1931c988c824b5883ab97a373faea32](url)

Please let me know if we can find anything relevant regarding this error. 

Thanks

**Comment by mykola-mokhnach** [comment]
Unfortunately I don't have any ideas. If WDA server is still running on the device then it is most likely a networking/client connectivity issue.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
