### ISSUE TITLE
How to open the cloned (dual / twin) app?

### ISSUE THREAD

**Issue by Jesse1321** [appium/appium#15076]
we use the App Twin feature to clone WeChat Work app, but how to open the cloned app via Appium?
the twin app have the same package name, same activity name.

**Comment by KazuCocoa** [comment]
What is _the App Twin_ feature? Android official one? (I haven't heard that, so wondered what it was.)

**Comment by mykola-mokhnach** [comment]
Appium simply uses `adb shell am start` call under the hood. I would try to figure that out with the app developers or by reading the documentation.

Please use Appium forum to ask questions.
