### ISSUE TITLE
how to find element by placeholderValue

### ISSUE THREAD

**Issue by perkele99** [appium/appium#15077]
`iosDriver.executeScript("mobile: source", ImmutableMap.of("format", "description")) `
return 

```
Other, 0x6000014723e0, {{67.0, 342.3}, {280.0, 469.7}}                    
TextField, 0x600001472220, {{67.0, 352.3}, {280.0, 68.0}}, placeholderValue: 'Email or username'
SecureTextField, 0x600001472300, {{67.0, 428.3}, {280.0, 68.0}}, placeholderValue: 'Your password'
Button, 0x600001472ae0, {{67.0, 516.3}, {280.0, 44.0}}, label: 'Login', Disabled
StaticText, 0x600001472a00, {{178.0, 527.0}, {58.0, 23.0}}, label: 'Login'
Other, 0x600001472840, {{0.0, 817.0}, {414.0, 1.0}}
```

how to find element by placeholderValue?
`iosDriver.findElementByIosNsPredicate("placeholderValue == 'Email or username'")` don't work

**Comment by mykola-mokhnach** [comment]
WDA implicitly puts the value of the native `placeholderValue` attribute into `value`: https://github.com/appium/WebDriverAgent/blob/121a7e50cb3c34b2f92bbba08e0f8cbb452388d5/WebDriverAgentLib/Categories/XCUIElement%2BFBWebDriverAttributes.m#L91

**Comment by mykola-mokhnach** [comment]
This is also mentioned in README: https://github.com/appium/appium-xcuitest-driver#element-attributes

**Comment by mmajcherczyk** [comment]
but when I change the value it is possible to find the element by the value of the placeholderValue?

**Comment by perkele99** [comment]
but when I change the value it is possible to find the element by the value of the placeholderValue?

**Comment by mykola-mokhnach** [comment]
As you could see in the sources if the `value` native attribute is defined then it is taken instead of the `placeholderValue` one

**Comment by perkele99** [comment]
thx
