### ISSUE TITLE
Support iOS 14?

### ISSUE THREAD

**Issue by neo-hu** [appium/appium#15072]
Details

Unable to install "IntegrationTests_1-Runner"
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620394
--
The executable was signed with invalid entitlements.
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620394
User Info: {
    DVTRadarComponentKey = 487925;
    MobileDeviceErrorCode = "(0xE8008016)";
    "com.apple.dtdevicekit.stacktrace" = (
	0   DTDeviceKitBase                     0x000000012badcc8f DTDKCreateNSErrorFromAMDErrorCode + 220
	1   DTDeviceKitBase                     0x000000012bb1b241 __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 155
	2   DVTFoundation                       0x000000010a02964b DVTInvokeWithStrongOwnership + 71
	3   DTDeviceKitBase                     0x000000012bb1af82 -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1440
	4   IDEiOSSupportCore                   0x000000012b98ba10 __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.292 + 3513
	5   DVTFoundation                       0x000000010a15817e __DVT_CALLING_CLIENT_BLOCK__ + 7
	6   DVTFoundation                       0x000000010a159da0 __DVTDispatchAsync_block_invoke + 1191
	7   libdispatch.dylib                   0x00007fff201835dd _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x00007fff201847c7 _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00007fff2018a5fe _dispatch_lane_serial_drain + 606
	10  libdispatch.dylib                   0x00007fff2018b0cb _dispatch_lane_invoke + 375
	11  libdispatch.dylib                   0x00007fff20194c5d _dispatch_workloop_worker_thread + 819
	12  libsystem_pthread.dylib             0x00007fff2032c499 _pthread_wqthread + 314
	13  libsystem_pthread.dylib             0x00007fff2032b467 start_wqthread + 15
);
}
--

System Information

macOS Version 11.1 (Build 20C69)
Xcode 12.4 (17801) (Build 12D4e)
Timestamp: 2021-02-01T09:46:17+08:00

**Comment by mykola-mokhnach** [comment]
It looks like the binary you are trying to install is not signed properly or the signature is invalid. Unfortunately there is nothing we could thee from Appium side.

Closed as not an issue
