### ISSUE TITLE
Installation/First Run issues + suggestions

### ISSUE THREAD

**Issue by harman-brar** [appium/appium#15071]
## The problem

1)
When running my first appium-js script, I was receiving an error stating that: `[ADB] 'io.appium.uiautomator2.server' is not installed`. **I resolved this by** checking out the `appium/appium-uiautomator2-driver` repo where I found out that `Android SDK below API 30 requires Java 8. Android SDK 30 and above requires Java 9 or newer`. It may be a good idea to include this in the docs at http://appium.io/docs/en/about-appium/getting-started/?lang=en

2)
I also received the following error: `apksigner.jar cannot be found`. **I was able to fix this by** heading into my android sdk build-tools folder, and copying apksigner.jar into sdk/platform-tools/. 
It would be nice if this could be automated so that the end user doesn't need to do this manually.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2
* 
* Android SDK  version: 4.1.2
* Android Build tools version: 30.0.3
* 
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): v14.15.4
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: Android (10/11)
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: CLI

**Comment by mykola-mokhnach** [comment]
Please do not report all issues at once. It makes sense to create separate reports for each.

Regarding the second case: please provide the server log. By default Appium looks for apksigner.jar in both platform tool and build tools folder (and also some more). Here's the complete logic: https://github.com/appium/appium-adb/blob/d39f647e4af6dbbaa08309875253d13c786a1b8f/lib/tools/system-calls.js#L92

**Comment by harman-brar** [comment]
Unfortunately I'm unable to access the server log anymore. 

After taking a brief look at the logic, it seems possible that having `ANDROID_HOME = {path...}/Sdk/platform-tools` at that point in time may have caused the issue.

**Comment by mykola-mokhnach** [comment]
ANDROID_HOME must be pointing to the root sdk folder (for example `~/Library/Android/sdk`). Folder paths that Appium calculates are visible in the server logs when the session starts.

Please create a new issue about documentation or feel free to add a PR yourself.
