### ISSUE TITLE
driver.getClipboardText() does not work on Google Pixel 4/Android 11

### ISSUE THREAD

**Issue by arhanechka** [appium/appium#15088]
tried:
driver.getClipboard(ClipboardContentType.PLAINTEXT); // get plaintext
driver.getClipboardText();
result - empty string
[debug] [W3C (34d29e57)] Calling AppiumDriver.getClipboard() with args: [“plaintext”,“34d29e57-3a22-402a-8fba-d3bfaaea4497”]

[debug] [ADB] Getting the clipboard content

[debug] [ADB] Running ‘/Users/***/Library/Android/sdk/platform-tools/adb -P 5037 -s 99111FFAZ00CE8 shell settings get secure default_input_method’

[debug] [ADB] Running ‘/Users/***/Library/Android/sdk/platform-tools/adb -P 5037 -s 99111FFAZ00CE8 shell ime set io.appium.settings/.AppiumIME’

[debug] [ADB] Running ‘/Users/***/Library/Android/sdk/platform-tools/adb -P 5037 -s 99111FFAZ00CE8 shell am broadcast -n io.appium.settings/.receivers.ClipboardReceiver -a io.appium.settings.clipboard.get’

[debug] [ADB] Running ‘/Users/***/Library/Android/sdk/platform-tools/adb -P 5037 -s 99111FFAZ00CE8 shell ime set com.google.android.inputmethod.latin/com.android.inputmethod.latin.LatinIME’

[debug] [W3C (34d29e57)] Responding to client with driver.getClipboard() result: “”

[HTTP] <-- POST /wd/hub/session/34d29e57-3a22-402a-8fba-d3bfaaea4497/appium/device/get_clipboard 200 167 ms - 12

[HTTP]

[HTTP] --> POST /wd/hub/session/34d29e57-3a22-402a-8fba-d3bfaaea4497/appium/device/get_clipboard

[HTTP] {“contentType”:“plaintext”}

[debug] [W3C (34d29e57)] Calling AppiumDriver.getClipboard() with args: [“plaintext”,“34d29e57-3a22-402a-8fba-d3bfaaea4497”]

[debug] [ADB] Getting the clipboard content

[debug] [ADB] Running ‘/Users/***/Library/Android/sdk/platform-tools/adb -P 5037 -s 99111FFAZ00CE8 shell settings get secure default_input_method’

[debug] [ADB] Running ‘/Users/***/Library/Android/sdk/platform-tools/adb -P 5037 -s 99111FFAZ00CE8 shell ime set io.appium.settings/.AppiumIME’

[debug] [ADB] Running ‘/Users/***/Library/Android/sdk/platform-tools/adb -P 5037 -s 99111FFAZ00CE8 shell am broadcast -n io.appium.settings/.receivers.ClipboardReceiver -a io.appium.settings.clipboard.get’

[debug] [ADB] Running ‘/Users/***/Library/Android/sdk/platform-tools/adb -P 5037 -s 99111FFAZ00CE8 shell ime set com.google.android.inputmethod.latin/com.android.inputmethod.latin.LatinIME’

[debug] [W3C (34d29e57)] Responding to client with driver.getClipboard() result: “”

**Comment by mykola-mokhnach** [comment]
The log of actions does seem correct to me. Try to fetch the logcat output for this period, perhaps it contains more details.

**Comment by arhanechka** [comment]
[logs.txt](https://github.com/appium/appium/files/5942260/logs.txt)

**Comment by mykola-mokhnach** [comment]
Sorry, this is not the log I've asked for. Device logs are needed rather than Appium logs

**Comment by arhanechka** [comment]
Sorry
[logs.txt](https://github.com/appium/appium/files/5942417/logs.txt)

**Comment by mykola-mokhnach** [comment]
Please only provide the part of the log where the clipboard content is being retrieved

**Comment by arhanechka** [comment]
[logs.txt](https://github.com/appium/appium/files/5943268/logs.txt)

**Comment by mykola-mokhnach** [comment]
> 02-08 10:58:36.452 20015 20015 D ClipboardReceiver: Getting current clipboard content
> 02-08 10:58:36.452  1546  1560 E ClipboardService: Denying clipboard access to io.appium.settings, application is not in focus nor is it a system service for user 0

This seems to be the cause. I would try to manually enter the above adb commands and observe the actual behaviour. Since Android 10 Google has added a security limitation, which only allows to retrieve clipboard content for focused apps or apps that set the input manager. Here we try to set Appium Settings as an input manager in order to get the clipboard content, but somehow it still fails.

**Comment by mykola-mokhnach** [comment]
It also looks like the server version you use is pretty out of date. Please make sure you use the most recent one

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by rosemichaele** [comment]
I was having a similar issue where tests checking the clipboard contents were failing only on Android 11 devices. Solved by running this app (which is the one reading from the clipboard) in the foreground. I’m using the Ruby client library:

```
def get_clipboard_content
    # On Android 11 and higher, the app reading from the clipboard must be in the foreground
    @driver.start_activity(
      app_package: 'io.appium.settings',
      app_activity: '.Settings'
    )
    @driver.get_clipboard
end
```
