### ISSUE TITLE
Appium Device State not detected.

### ISSUE THREAD

**Issue by ttt-t-ttt** [appium/appium#15081]
## The problem

When trying to launch a Simulator appium says it failed to boot but it definitely didn’t.
## Environment

* Appium version :
1.20.2
* Last Appium version that did not exhibit the issue (if applicable):
idk
* Desktop OS/version used to run Appium:
Mac OSX 10.15.7
* Node.js version (unless using Appium.app|exe):
v14.15.2
* Npm or Yarn package manager:
7.4.0
* Mobile platform/version under test:
iOS 10.3
* Real device or emulator/simulator:
simulator
* Appium CLI or Appium.app|exe:
CLI

## Details

When trying to use a iPhone 5 iOS 10.3 Simulator I can See that the simulator booted but Appium says it failed to do so. 
I can see the booted simulator screen and xcrun states the device as booted.
iOS 14.3 works fine(of course not running on iPhone 5)

## Link to Appium logs

https://gist.github.com/ttt-t-ttt/a8585522ff7df572c342728bd6e8382e

## Code To Reproduce Issue [ Python ]
from appium import webdriver
 driver = webdriver.Remote('http://0.0.0.0:4723/wd/hub', dict(platformName='iOS',
                                                             udid='40D29CB1-16C5-4071-8238-254D98417AD3',
                                                             platformVersion='10.3',
                                                             automationName='XCUITest',
                                                             deviceName='iPhone 5',
                                                             app='/Users/testuser/Downloads/test.app',
                                                             sendKeyStrategy="oneByOne",
                                                             clearSystemFiles=False,
                                                             usePrebuiltWDA=False,
                                                             showXcodeLog=True,
                                                             wdaStartupRetries=5,
                                                             newCommandTimeout = '3000'))

print("Session erfolgreich gestartet")
driver.implicitly_wait(5)

edit:markup

**Comment by mykola-mokhnach** [comment]
Appium uses `xcrun simctl bootstatus` command to monitor the Simulator booting progress. From the attached log it seems like this monitor unexpectedly gets killed, so Appium is unable to detect when the progress is completed.

**Comment by ttt-t-ttt** [comment]
https://gist.github.com/ttt-t-ttt/45aa0335a1b2b985b15bae4731689fd4

second run, simply stuck there like forever now most likely will just timeout.
no WDA on Sim
running the given command in the terminal never returns anything (waited 2 minutes)

**Comment by ttt-t-ttt** [comment]
is there anymore information i could provide ?

**Comment by mykola-mokhnach** [comment]
To me it looks more like simctl/Simulator issue. Commands triggered by Appium seem ok.

**Comment by ttt-t-ttt** [comment]
maybe someone could check if the are able to launch an iPhone 5 on iOS 10.3 maybe my setup ist just broken in some way.

**Comment by apple280** [comment]
ok，thankyou


| |
顾涛
|
|
apple280@yeah.net
|
签名由网易邮箱大师定制
On 2/4/2021 03:32，ttt-t-ttt<notifications@github.com> wrote：

maybe someone could check if the are able to launch an iPhone 5 Simulator on iOS 10.3 maybe my setup ist just broken in some way.

**Comment by mykola-mokhnach** [comment]
I would try to run it on a clean machine or with an older Xcode version

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by ttt-t-ttt** [comment]
I Can’t use a previous Release because I need a iOS 14.3 or later SDK. I will try on a clean machine.

**Comment by mykola-mokhnach** [comment]
I mean it would probably make sense to have a separate Xcode SDK deployment to test older iOS version, like 10.3 one, and the current one to test iOS 14.
