### ISSUE TITLE
Cannot enter passwords on iOS 13+

### ISSUE THREAD

**Issue by everythingisbugs** [appium/appium#15089]
## The problem

Attempts to input passwords in SecureTextFields fail on iOS 13+, in various applications (App Store, Settings).

## Environment

* Appium version: 1.20.2
* Desktop OS: Mac 10.15.7, Mac 11.0
* Node.js version: 15.8.0
* Npm version: 7.5.0
* Mobile platform/version under test: iOS 13+
* Real device or emulator/simulator: real devices: iPhone 7, iPhone X
* Appium CLI: yes

## Details

We have a test where we navigate to the iOS App Store to verify the fresh install process for new users. When attempting to install any app, the test normally enters the password for the active account. On iOS 14, the SecureTextField element no longer gets tapped (either via click() or a Touch Action at those coordinates). The keyboard is not visible and send_keys() does nothing.

This happens on multiple iOS 13+ devices and not on previous versions. This does not happen with other TextFields, only the password ones.

## Appium logs

[Section of relevant Appium logs here](https://gist.github.com/everythingisbugs/007d9b309f602bd2bf111dafb5a398f9#file-appium_log-txt). Full logs contain sensitive information, will need to provide additional sections on demand.

## Code To Reproduce Issue (Python)
```
import unittest, os, time
from appium import webdriver
from appium.webdriver.common.touch_action import TouchAction

# Redacted device UDID and signing details
desired_caps = dict(
    platformName='iOS',
    bundleId="com.apple.AppStore",
    automationName="XCUITest"
)

driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)

# Search for any application name and wait for results
driver.find_element_by_name("Search").click()
el = driver.find_element_by_class_name("SearchField")
el.click()
el.send_keys("Lego")
el.send_keys("\uE007")
time.sleep(8)

# Select the first app with a "GET" button
driver.find_element_by_name("get").click()
time.sleep(8)
driver.find_element_by_name("Install").click()
time.sleep(3)

# Enter the password
el = driver.find_element_by_class_name("SecureTextField")
el.click()
el.send_keys("Lego")

# TouchActions also don't work
#TouchAction(driver).tap(None, 222, 591, 1).perform()
```

**Comment by mykola-mokhnach** [comment]
I assume this is some security limitation that Apple might add to XCUITest recently. You could try to perform the same scenario using a "raw" XCTest script to verify if this is still happening. If yes then only Apple could change/fix anything there as WDA is only limited by usage of APIs provided by XCTest.

**Comment by mykola-mokhnach** [comment]
I also saw some cases where the "real" element coordinates where shifted in comparison to coordinates calculated by XCTest, because the element was belonging to a view built by another process. In such case one could try to calculate the coordinates delta manually and click where needed.

**Comment by everythingisbugs** [comment]
> 
> 
> I assume this is some security limitation that Apple might add to XCUITest recently. You could try to perform the same scenario using a "raw" XCTest script to verify if this is still happening. If yes then only Apple could change/fix anything there as WDA is only limited by usage of APIs provided by XCTest.

I've had a look at that and it seems to be the case but I couldn't find the change mentioned anywhere so I'm not sure if it's intentional or meant to be done in some other way. I hope maybe some people here have some insight while I keep investigating, since this use-case is specific to Appium-related scenarios, and I think Apple does not normally expect us to automate behaviors outside or own apps (i.e. in the App Store).

> 
> 
> I also saw some cases where the "real" element coordinates where shifted in comparison to coordinates calculated by XCTest, because the element was belonging to a view built by another process. In such case one could try to calculate the coordinates delta manually and click where needed.

I'm aware of those issues and I made sure to verify the actual coordinates, then attempted to directly tap on them (bypassing XCTest's reporting), same behavior (which is what leads me to think it's a security issue).

**Comment by mykola-mokhnach** [comment]
> I've had a look at that and it seems to be the case but I couldn't find the change mentioned anywhere so I'm not sure if it's intentional or meant to be done in some other way.

Usually such things are mentioned somewhere in Xcode release notes using small-size fonts ;).
Unfortunately I could add nothing more on that. Welcome to the Apple world ¯\_(ツ)_/¯

I'll keep this issue unclosed for a while, so other people could see and comment on it.

**Comment by KazuCocoa** [comment]
Actually, the above behavior happens on my iOS 14 in App Store login as well... Nothing we can do, unfortunately.

As a workaround. you can do something like this:

e.g. in Apple ID sign in App Store app.
```ruby
e = driver.find_element :class, 'XCUIElementTypeTextField'
e.send_keys 'user name'
driver.find_element(:accessibility_id, 'Return').click  # The keyboard focus moves to the next field (secured text field)
driver.swith_to.active_element.send_keys('password')  # Keyboad is keeping in the display, so you can call `send_keys`
driver.find_element(:accessibility_id, 'Done').click
```

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
