### ISSUE TITLE
Swipe doesn't works on IOS 

### ISSUE THREAD

**Issue by levanikhvedelidze** [appium/appium#15086]
## The problem

I'm trying  to perform vertical swipe on my device but it doesn't works,  I think problem is in my code not in Appium but I cant figure what is a problem. :( 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.19.1
* Last Appium version that did not exhibit the issue (if applicable):1.19.1
* Desktop OS/version used to run Appium: macos
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:iOS
* Real device or emulator/simulator: both
* Appium CLI or Appium.app|exe:CLI

## Link to Appium logs

https://gist.github.com/levanikhvedelidze/3c86dd7ab1bd590c1ef1efc041739d90

## Code To Reproduce Issue [ Good To Have ]
Here is my code 

public void swipe() {
	  Dimension size = getDriver().manage().window().getSize();
	  
	  int startX = size.width/2;
	  int endX = startX;
	  int  startY = (int) (size.height * 0.8);
	  int endY = (int) (size.height * 0.2);
	  
 new TouchAction (getDriver())
	  .press(PointOption.point(startX, startY))
	  	.waitAction(WaitOptions.waitOptions(Duration.ofSeconds(15)))
	  	.moveTo(PointOption.point(endX, endY))
	  	.release() 
	  	.perform();
  }

<img width="667" alt="Screenshot 2021-02-06 at 20 06 28" src="https://user-images.githubusercontent.com/76706790/107124085-1bd44000-68bb-11eb-96b3-fcef697ca730.png">

**Comment by levanikhvedelidze** [comment]
I tried to declare start x,y & end x,y, coordinates as a hard code, but it's same

**Comment by KazuCocoa** [comment]
How about W3C actions?
http://appium.io/docs/en/commands/interactions/actions/

**Comment by mykola-mokhnach** [comment]
You could also try mobile gesture extensions: https://github.com/appium/appium-xcuitest-driver#mobile-gesture-commands

Please use Appium forum to ask questions

**Comment by levanikhvedelidze** [comment]
thanks guys
