### ISSUE TITLE
Install a project with a clean slate (npm ci) fails with NPM 7

### ISSUE THREAD

**Issue by fluiddot** [appium/appium#15095]
## The problem

I'm trying to run `npm ci` (Install a project with a clean slate) with NPM version `7.5.3` and it's giving the following error:
```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path <PROJECT_DIR>/node_modules/appium/build/lib/main.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '<PROJECT_DIR>/node_modules/appium/build/lib/main.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```
_Project directory has been replaced in the logs with `<PROJECT_DIR>`._

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: OSX
* Node.js version (unless using Appium.app|exe): v14.15.5
* Npm or Yarn package manager: 7.5.3
* Mobile platform/version under test: N/A
* Real device or emulator/simulator: N/A
* Appium CLI or Appium.app|exe: CLI

## Details

It can be reproduced by running the following commands in a project folder:
1. `npm install -g npm@7.5.3`
2. `npm install appium`
3. `npm ci`

After this the following runs of `npm install` fail with the error described above.

**Comment by mykola-mokhnach** [comment]
I assume this is an npm issue. I don't observe anything suspicious in the package config there. 

@fluiddot Have you tried to report the issue to NPM itself?

**Comment by fluiddot** [comment]
Thanks @mykola-mokhnach for checking it!

>I assume this could be an npm issue.

Yeah most likely. This issue is very similar to another one that was reported a couple months ago (https://github.com/appium/appium/issues/14901). Looks like NPM 7 has a bug regarding how the symlinks are created as explained in this [comment](https://github.com/appium/appium/issues/14901#issuecomment-743762334).

>@fluiddot Have you tried to report the issue to NPM itself?

Yeah, it's already reported in this [issue](https://github.com/npm/cli/issues/2251) in `npm/cli` repository. I was wondering if there could be a workaround for this meanwhile a fix is released from NPM, similar to what was done previously in https://github.com/appium/appium/issues/14901.

**Comment by mykola-mokhnach** [comment]
I assume the workaround would be to downgrade NPM to v6

Closed as third party issue

**Comment by fluiddot** [comment]
> I assume the workaround would be to downgrade NPM to v6

Yes, downgrading to NPM v6 is for now the best option.
