### ISSUE TITLE
Appium iOS safari default opening native youtube application when I load mobile youtube link.

### ISSUE THREAD

**Issue by bandalamudysrikanth** [appium/appium#15094]
## The problem

Appium iOS safari default opening native youtube application when I load mobile youtube link.

## Environment

capabilities = new DesiredCapabilities();
capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "13.1");
capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");
capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone");
capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "Safari");
capabilities.setCapability(MobileCapabilityType.UDID, udid);  

// Initilize the Appium driver
AppiumDriver	driver = new AppiumDriver<WebElement>(new URL("http://" + url + ":" + port + "/wd/hub"), capabilities);

//enable and disable privateBrowsing
privateBrowsingHandler(privateBrowsingMode); 

driver.get(webPageUrl);
 
Is there any way I can prevent to open native youtube. I tried with mobile setting but its not help.

**Comment by KazuCocoa** [comment]
Could you share the appium log?
If your log was like https://gist.github.com/KazuCocoa/45d2a07b4fc7b99aeff44c2898b6ae17 , probably Safari behaves so internally. (I was able to open the youtube.com in Safari with no-youtube app device, but it opened youtube once I installed the youtube app)

As an alternative way, only below works;

1. tap search bar in Safari browser
2. type the URL
3. enter

**Comment by KazuCocoa** [comment]
I mean `Page.navigate` via Web Inspector seems opening mobile app. (Safari via XCUITest)
https://github.com/appium/appium-safari-driver is also an alternative.

**Comment by bandalamudysrikanth** [comment]
@KazuCocoa thanks for info I could try with safari-driver. but my other device able run the youtube link safari its self.  Safari might you using some preference. Let try using browser

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
