### ISSUE TITLE
The bug in appium for any ios testing: complicated layout 's app in autotesing ,appium is timeout or stuck

### ISSUE THREAD

**Issue by woodywang0** [appium/appium#15090]
## The problem
As in Ui automation testing ， Application stuck with complicated layout。

for example：Use Douyin  or Tik Tok app for automated testing，automation script enters the app，then it stuck and timeout。it is works with other apps using the same scripe。so I ask ios Dev，Some people say that the TikTok layout is too complicated and wda will time out。
Does anyone solve this problem

Demo script：
c = wda_USB_init(device)
s = c.session(bundle_id, alert_action="accept")

## Environment

* Appium version  1.19.1
* Desktop OS/version used to run Appium:  ios 14 ios9 ios10
* Node.js version (12.8.1):

**Comment by mykola-mokhnach** [comment]
> XCTPerformOnMainRunLoop work timed out after 60.0s

Such errors usually happen if the application is hogging the main event loop (for example by constantly running continuous animations), so XCTest is unable to do its job. This is XCTest-related issues and we could do nothing on Appium side to workaround it.

Also, it makes sense try the most recent server version.

**Comment by woodywang0** [comment]
the most recent server version,

**Comment by woodywang0** [comment]
What service version does this（”try the most recent server version“） refer to?
XCTest？

**Comment by woodywang0** [comment]
> > XCTPerformOnMainRunLoop work timed out after 60.0s
> 
> Such errors usually happen if the application under test is hogging the main event loop (for example by constantly running continuous animations), so XCTest is unable to do its job. This is XCTest-related issue and we could do nothing on Appium side to workaround it.
> 
> Also, it makes sense to try the most recent server version.

What service version does this（”try the most recent server version“） refer to?
XCTest？

**Comment by mykola-mokhnach** [comment]
You've mentioned that the Appium version used for testing is 1.19.1

Currently the latest server version is 1.20.2 though: https://github.com/appium/appium/releases/tag/v1.20.2

**Comment by woodywang0** [comment]
> You've mentioned that the Appium version used for testing is 1.19.1
> 
> Currently the latest server version is 1.20.2 though: https://github.com/appium/appium/releases/tag/v1.20.2

Thank you, I will download the latest appium version and try again

**Comment by woodywang0** [comment]
> You've mentioned that the Appium version used for testing is 1.19.1
> 
> Currently the latest server version is 1.20.2 though: https://github.com/appium/appium/releases/tag/v1.20.2

i was download appium-desktop :Appium-mac-1.19.1.dmg. but the link you gave is appium source code.

How do I merge the source1.20.2 code into Appium-mac-1.19.1 in mac?

**Comment by woodywang0** [comment]
> > XCTPerformOnMainRunLoop work timed out after 60.0s
> 
> Such errors usually happen if the application under test is hogging the main event loop (for example by constantly running continuous animations), so XCTest is unable to do its job. This is XCTest-related issue and we could do nothing on Appium side to workaround it.
> 
> Also, it makes sense to try the most recent server version.

Why other short video app , like zynn(kuaishou) or instagram it is works?
