### ISSUE TITLE
[Android] On some devices touch action longPress().release().perform() produces InvalidElementStateError if the longPress action triggers UI to go to another view

### ISSUE THREAD

**Issue by alex-i-rybkin** [appium/appium#15100]
## The problem

We have a UI element that triggers mobile UI to move to another view on longPress action. On some real android devices and emulators (i.e. Pixel 3 emulator (API 29)) the code below produces InvalidElementStateError if the touch action has `release()` action on the end.
`new TouchAction(driver).longPress(LongPressOptions.longPressOptions().withPosition(PointOption.point(540,355))).release().perform();`

Removing `release()` action solves the problem, but it does not seem a valid solution. Also, explicit handling of InvalidElementStateError seems to be rather a workaround, than a real solution.

Maybe the root cause is in https://github.com/appium/appium-android-driver itself.

**Important things to reproduce the issue**
- Pixel 3 emulator (API 29)
- longPress UI element that triggers mobile UI to move to another view
- TouchAction has  `longPress()`  and `release()`

## Environment

* Appium version (or git revision) that exhibits the issue: 1.19.1+
* Appium client: io.appium:java-client:7.4.1
* Last Appium version that did not exhibit the issue (if applicable): No info
* Desktop OS/version used to run Appium: MacOS 10.15.7
* Node.js version (unless using Appium.app|exe): v14.9.0
* Npm or Yarn package manager: npm 6.14.7
* Mobile platform/version under test: Android
* Real device or emulator/simulator: real and emulator
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

[GIST](https://gist.github.com/alex-i-rybkin/4640410954f1c74e2b341f29936d257b)

**Comment by mykola-mokhnach** [comment]
The error is returned by UiAutomator API itself. There is nothing we could do about it. Also, the touch actions API itself is considered outdated.

Consider switching to W3C Actions API or use [mobile gesture wrappers](https://github.com/appium/appium-uiautomator2-driver#mobile-gesture-commands)

**Comment by alex-i-rybkin** [comment]
Thank you, for fast feedback
