### ISSUE TITLE
Is using Safari possible? Siri prompt blocking

### ISSUE THREAD

**Issue by GeorgeXCV** [appium/appium#15105]
## The problem
I make an account on application, want to verify the email address. I open Safari, a prompt to enable/disable Siri appears. I can’t dismiss it, no results when findElements. No additional context appears besides “NATIVE_APP” either. Is using safari in automated tests just not possible.

## Environment
* Appium version (or git revision) that exhibits the issue: ^1.17.1
* Desktop OS/version used to run Appium:  macOS Big Sur 11.1
* Node.js version (unless using Appium.app|exe): 14.15.1
* Npm or Yarn package manager: NPM 6.14.8
* Mobile platform/version under test: iOS 13.0
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Details
Using a Real Device on BrowserStack

## Code To Reproduce Issue
```
await this.driver.activateApp("com.apple.mobilesafari");
await this.driver.url(href);
```

**Comment by KazuCocoa** [comment]
It seems it could happen when Siri stuff is called via XCTest framework before turning Siri on by hand on the device.
Not sure when the behavior changed, but Apple changed to behaves so.

btw, Appium opens an URL via Siri because the way was the most relible.

**Comment by mykola-mokhnach** [comment]
closed as not an issue

**Comment by GeorgeXCV** [comment]
I see this prompt just by opening Safari though, before calling driver.url(). So it appears using Safari with Appium isn't possible.
![screenshot-3ac91cd4bb](https://user-images.githubusercontent.com/13811547/107761779-d503a180-6d23-11eb-8f3a-407c544b787a.jpeg)

**Comment by mykola-mokhnach** [comment]
This only means that using deep liking in native context is limited by Apple's security restrictions. 

There are at least 3 different possibilities to interact with Safari in Appium: 
- Using XCUITest driver via XCTest/accessibility 
- Using hybrid mode via Webkit remote debugger
- Using Appium-safari driver via Apple's implementation of W3C webdriver protocol

**Comment by GeorgeXCV** [comment]
Got it working, it was driver.url() triggering Siri. You can avoid this by tapping the address bar and entering the url using SendKeys.
