### ISSUE TITLE
Outdated axios dependencies

### ISSUE THREAD

**Issue by Simon-TechForm** [appium/appium#15102]
Doing a fresh install of Appium makes npm audit throw a tantrum:
`found 153 vulnerabilities (2 low, 151 high)`

All of the found vulnerabilities seems to be caused by old versions of Axios.

I haven't looked into whether or not these vulnerabilities actually affect Appium, but either way it would be nice to not have npm nagging you.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2
* Desktop OS/version used to run Appium: macOS 11.2.1
* Node.js version (unless using Appium.app|exe): v14.15.5
* Npm or Yarn package manager: Npm 6.14.11
* Appium CLI or Appium.app|exe: CLI

## Code To Reproduce Issue [ Good To Have ]

`npm init -y`
`npm i appium`

**Comment by mykola-mokhnach** [comment]
module dependencies are usually not pinned. Simply Make sure you remove the old deployment before installing a new version to always have the most recent dependency versions

**Comment by Simon-TechForm** [comment]
> module dependencies are usually not pinned. Simply Make sure you remove the old deployment before installing a new version to always have the most recent dependency versions

This is happening on a fresh install, so there is no old deployment to remove.

Axios is currently versioning itself as "0.X.X", which means that it will only receive patches when updating (Which you can read more about here: https://docs.npmjs.com/cli/v6/using-npm/semver/#caret-ranges-123-025-004).

There are a handful of references to axios 0.20.X and even one for 0.19.X when doing a fresh install. These will not be updated.

**Comment by mykola-mokhnach** [comment]
Oh, I've missed this npm limitation. It for sure makes sense to change that to `^0.x`

**Comment by Simon-TechForm** [comment]
> Oh, I've missed this npm limitation. It for sure makes sense to change that to `^0.x`

After doing some/quite a lot of digging, I've cleared some things up.

Most of the dependencies already updated axios to the latest version in their source package.json, but for some reason, npm isn't installing the latest version of the dependencies... If someone who is more knowledgeable about npm than me would try to reproduce/explain this to me, I would be graceful. Doing `npm init -y` + `npm i appium` currently installs appium-android-driver v4.41.1 which relies on a vulnerable version of axios, even though v4.41.2 is available on npm. This is just one example, the same thing happens with appium-ios-driver, appium-support and possibly others as well. Installing one of the dependencies directly in a test project (eg. `npm init -y` + `npm i appium-android-driver`) installs the latest version.
I've been able to reproduce this across 3 different machines, all running the latest node@14 and corresponding npm version. I am quite confused :)

Doing the exact same thing with yarn instead (eg. `yarn init -y` + `yarn add appium`) installs all the latest versions and yields: `3 vulnerabilities found - Packages audited: 730
Severity: 2 Low | 1 High`

Disregarding weird npm behaviour, it all boils down to appium-flutter-driver and appium-tizen-driver.
Appium-flutter-driver relies on a vulnerable version of axios, but an update have already been committed to the repo, though it is not yet released on npm. When a new version gets pushed, the high severity vulnerability will be fixed.

The 2 low severity vulnerabilities originates from appium-tizen-driver which indirectly relies on "minimist" and "yargs-parser" which have been found to include low severity vulnerabilities.

**Comment by mykola-mokhnach** [comment]
These two packages are third-party dependencies, which we cannot influence much, their authors decide it on their own when to publish new versions.

Regarding the npm behaviour: it could be it is using a shrinkwrap file, where versions of particular modules are locked, so it does not try to get updated versions of them. This should not be the case for appium@beta though, which is not shrinkwrapped

**Comment by Simon-TechForm** [comment]
> These two packages are third-party dependencies, which we cannot influence much, their authors decide it on their own when to publish new versions.
> 
> Regarding the npm behaviour: it could be it is using a shrinkwrap file, where versions of particular modules are locked, so it does not try to get updated versions of them. This should not be the case for appium@beta though, which is not shrinkwrapped

Yeah, I noticed that. We'll just have to wait.

Ah, there's a shrinkwrap file in appium. I did not notice that. Thank you.

Should we keep this issue open for other npm users to see? Maybe until the huge amount of vulnerabilities are removed from the package?

If not, feel free to close this.
