### ISSUE TITLE
iOS Mobile: Scroll does not work

### ISSUE THREAD

**Issue by zcmgyu** [appium/appium#15114]
## The problem

The "mobile: scroll" API is not executed as expected. I will describe it in detail.
 
## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2
* Last Appium version that did not exhibit the issue (if applicable): I can't remember
* Desktop OS/version used to run Appium: macOS (Big Sur 11.1)
* Node.js version (unless using Appium.app|exe): v15.8.0
* Npm or Yarn package manager: yarn 1.22.5
* Mobile platform/version under test: iOS 14.3
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium Cli 

## Details

1. TheApp

I got the below error message when using "mobile: scroll" API to scroll to a specific element by predicate string, but it seems not to occur in all other applications.

>  Failed to find scrollable visible parent with 2 visible children

I realized that prescrollSnapshot is always invisible.

https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Categories/XCUIElement+FBScrolling.m#L116

```
if (![snapshot isWDVisible]) {
    return NO;
}
```

2. IntegrationApp

It scrolls over the target element until timeout

=> I want to help figure out the bug, but I can't do it yet. If so, please show me some ideas to solve, I will fix it and make a PR.

## Link to Appium logs

https://gist.github.com/zcmgyu/53e859fa6013e64ddaa89117fbc6acbf

## Code To Reproduce Issue [ Good To Have ]

https://github.com/zcmgyu/appium-ios-mobile-scroll-bug

Run below command

1. 

> yarn integration-app

2.

> yarn the-app

**Comment by KazuCocoa** [comment]
What about skipping the visibility check? (Then, does it work expectedly?)

**Comment by zcmgyu** [comment]
@KazuCocoa 

Thanks for your advice.

After ignoring the visibility of snapshot check, visible cells of snapshot just return 0 (I also tested on the home screen of The App application, it returns 1)

```
if (visibleCellSnapshots.count > 1) {
    return YES;
}
```

I've forced the filter callback to always return YES as well to get scroll view, then the fb_isEquivalentElementSnapshotVisible function always returns NO until the limit of the scroll is reached.

One more thing, while executing scroll block it mistakenly clicked on a specific item. (I'm still looking for the cause)

I'm sorry if I have any misunderstanding in the code, this is my first time reading the Objective-C code. 


```
 XCElementSnapshot *scrollView = [prescrollSnapshot fb_parentMatchingOneOfTypes:acceptedParents
      filter:^(XCElementSnapshot *snapshot) {

         if (![snapshot isWDVisible]) {
           return NO;
         }

         cellSnapshots = [snapshot fb_descendantsCellSnapshots];

         visibleCellSnapshots = [cellSnapshots filteredArrayUsingPredicate:[FBPredicate predicateWithFormat:@"%K == YES", FBStringify(XCUIElement, fb_isVisible)]];

         if (visibleCellSnapshots.count > 1) {
           return YES;
         }
         return NO;
      }];
```
https://github.com/appium/WebDriverAgent/blob/4eed2c857b276c1667839b3afd8ca63cf58a6f46/WebDriverAgentLib/Categories/XCUIElement%2BFBScrolling.m#L114

```
[self fb_isEquivalentElementSnapshotVisible:prescrollSnapshot]
```
https://github.com/appium/WebDriverAgent/blob/4eed2c857b276c1667839b3afd8ca63cf58a6f46/WebDriverAgentLib/Categories/XCUIElement%2BFBScrolling.m#L164

**Comment by devstrat** [comment]
Hey guys, any chance this gets addressed? or any known workarounds?

**Comment by devstrat** [comment]
Hey guys, any chance this gets addressed? or any known workarounds?
@mykola-mokhnach  🙏🏻

**Comment by sebinjoseph1994** [comment]
Same issue. Scrolling to an element is not possible. It just keeps on scrolling even after crossing the element.
@mykola-mokhnach @KazuCocoa As this is still open, is it something like you are working on, or is this an issue with XCUITest itself?

**Comment by mykola-mokhnach** [comment]
No, we don't work on it because:
- The current scrolling implementation relies on visibility concept which is not always reliable with XCTest
- We don't have any Simulator app to test the failing scenario with. Scrolling works properly for the WebDriverAgent's app used in integration tests though
- XCTest itself does scroll automatically if one wants to tap an element which is outside of the visible screen area

**Comment by sebinjoseph1994** [comment]
@mykola-mokhnach Thank you so much for the quick response. I had tried to scroll based on the current location of the element, but as you said it is highly unreliable. I could reproduce the issue with the Preferences application in my iPhone 12 Pro 14.5 simulator. I didn't know about XCTest being auto-scrolled on clicking on the element. Thanks for that information :)

**Comment by mykola-mokhnach** [comment]
> https://developer.apple.com/documentation/xctest/xcuielement/1618666-tap?language=objc
> If the element exists within a scrollable view but is offscreen, XCTest will attempt to scroll the element onscreen before performing the tap.

**Comment by mykola-mokhnach** [comment]
Thanks to @dan-maor we got fixes on this issue, which have been published to appium@beta. @zcmgyu Please try if these work for you

**Comment by sebinjoseph1994** [comment]
@mykola-mokhnach It's working for me. Thanks much @Dan-Maor.

**Comment by KazuCocoa** [comment]
The change is currently in latest `appium@rc`

**Comment by mykola-mokhnach** [comment]
Closed because of no response
