### ISSUE TITLE
Double-quoted include "HTTPResponse.h" in framework header, expected angle-bracketed instead.

### ISSUE THREAD

**Issue by appium702** [appium/appium#15111]
**Action Performed 1:** running command ./Scripts/bootstrap.sh -d

**Issue facing 1:**
Building universal frameworks with common architectures is not possible. The device and simulator slices for "RoutingHTTPServer" both build for: arm64
Rebuild with --use-xcframeworks to create an xcframework bundle instead.

**Action Performed 2:** build WebdriverAgentRunner from xcode 12.3.

**Issue facing 2:**
Double-quoted include "HTTPResponse.h" in framework header, expected angle-bracketed instead.
Double-quoted include "HTTPConnection.h" in framework header, expected angle-bracketed instead.
Could not build module "RoutingHTTPServer.

![image](https://user-images.githubusercontent.com/79094193/108166780-acf8b180-711a-11eb-8ec8-82f6a802e9d5.png)

## Environment
Appium version (or git revision) that exhibits the issue: 1.17
Last Appium version that did not exhibit the issue (if applicable): NA
Desktop OS/version used to run Appium: macOS Catalina (Version 10.15.5)
Node.js version (unless using Appium.app|exe): Using Appium.app
Npm or Yarn package manager: npm (7.4.0)
Mobile platform/version under test: iPhone 12 (iOS Version - 14.3)
Real device or emulator/simulator: Real device
Appium CLI or Appium.app|exe: Appium.app

## Details
Tried with following workaround to resolve issue 2:

```
gem install cocopoads,
rm -rf ~/Library/Developer/Xcode/DerivedData/
pod deintegrate
pod update
```
**Issue facing:** While running gem install cocopoads it is showing you don't have permissions for the /library/ruby/gems/2.6.0 directory

**Comment by mykola-mokhnach** [comment]
Please use the most recent server version. It also does not need carthage now.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
