### ISSUE TITLE
Screenshot orientation is not correct on iOS11.4

### ISSUE THREAD

**Issue by n-shu081** [appium/appium#15112]
## The problem
I used iPad(iOS11) in landscape orientation and took screenshot, but I got image of the device in portrait orientation.

## Environment

* Appium version:1.20.1
* Desktop OS/version : macOS/11.0.1 (Xcode12.2)
* Node.js version (unless using Appium.app|exe):12.16.1
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS11.4 
* Real device or emulator/simulator: Real device (iPad)
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs
[AppiumLog](https://gist.github.com/n-shu081/d62e6e7b038e8f1c27d9ce2919f04bc7)

**Comment by KazuCocoa** [comment]
Please set `screenshotOrientation` https://github.com/appium/appium-xcuitest-driver#settings-api via settings api to coordinate the orientation for you.

Appium returns the result of XCTest framework by apple for the value, but the orientation could be wrong.
https://developer.apple.com/documentation/uikit/uiinterfaceorientation 
Then, it is difficult to care about the coordinate automatically in Appium.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by n-shu081** [comment]
> Please set `screenshotOrientation` https://github.com/appium/appium-xcuitest-driver#settings-api via settings api to coordinate the orientation for you.
> 
> Appium returns the result of XCTest framework by apple for the value, but the orientation could be wrong.
> https://developer.apple.com/documentation/uikit/uiinterfaceorientation
> Then, it is difficult to care about the coordinate automatically in Appium.

Thank you for your answer. I'll try it.
