### ISSUE TITLE
Looking for picture-in-picture support? Android and iOS Platforms.

### ISSUE THREAD

**Issue by jbhandari** [appium/appium#15116]
## The problem

I have been scouring appium boards and issues to see if there is picture-in-picture support. Currently I cannot access UI elements that are apart of the picture-in-picture overlay.

https://developer.android.com/guide/topics/ui/picture-in-picture

Are there plans to support access UI elements that fall under picture-in-picture?

Thanks!

## Environment

* Appium version (or git revision) that exhibits the issue: v1.20.2 
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Mac OS 11
* Node.js version (unless using Appium.app|exe): Latest
* Npm or Yarn package manager: Latest
* Mobile platform/version under test: Android and iOS
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Both

## Details

Looking for picture-in-picture support on Android and iOS. 

Ex: https://developer.android.com/guide/topics/ui/picture-in-picture

## Link to Appium logs

N/A

## Code To Reproduce Issue [ Good To Have ]

N/A

**Comment by KazuCocoa** [comment]
We must investigate if XCTest (for iOS), UIA2 and Espresso (for Android) support them first.

For iOS, if the latest Appium could not find the element, I'm afraid XCTest itself does not support it.
(I mean XCTest cannot find elements in picture-in-picture)

How about enabling `enableMultiWindows` via settings API for UIA2?
If picture-in-picture is handled as multiple windows, the settings may help.

**Comment by mykola-mokhnach** [comment]
Yes, there is no magic in appium drivers. If the particular feature is not supported by the downstream native automation technology then we cannot support it as well. For XCUITest and UIA2 drivers this means the target view must be accessible and should be visible via the accessibility inspector. Otherwise I don't see any possibilities to make that working.

**Comment by jbhandari** [comment]
@KazuCocoa Thanks for the idea, will report back!

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
