### ISSUE TITLE
Wrong coordinates in mobile web browser

### ISSUE THREAD

**Issue by SergiyBelevitnevSFLY** [appium/appium#15123]
## The problem

For mobile gestures (such as http://appium.io/docs/en/writing-running-appium/android/android-mobile-gestures/) with chromedriver and safaridriver we have to perform actions by coordinates, but they are shifted down by browser address line.
As we can get y-coordinate of end browser address line (see attached screenshot) can we adjust getting coordinates for mobile web browser? Or at least get height of browser address line. Cause for different devices those are different

## Environment

* Appium version 1.20.2
* MacOS Catalina 10.15.4
* Node.js version 12.8.1
* Npm 6.14.8:
* Mobile platform Android 10.0 iOS 14.4:
* Real device: iPhone 8 /Pixel 3

![image](https://user-images.githubusercontent.com/49680494/108553597-965d8080-72fb-11eb-8cbd-76960504e9df.png)

**Comment by mykola-mokhnach** [comment]
Unfortunately we could do nothing about it. The coordinates are returned by XCTest, so only Apple is able to change that.
You could try to use https://github.com/appium/appium-safari-driver as a possible alternative.

**Comment by SergiyBelevitnevSFLY** [comment]
@mykola-mokhnach but on android i can see the same

**Comment by SergiyBelevitnevSFLY** [comment]
For both platforms (chrome on android and safari on ios) the same behavior.

**Comment by mykola-mokhnach** [comment]
Yes and I assume it is correct. In native mode drivers threat all visible elements as equal accessible controls and they don't care about whether these are located in a browser or not. This it is up to a client to align these coordinates to perform any native actions on them.
In hybrid mode though the only "area" visible to the driver is the browser page itself. That is why it calculates all element positions relatively to its left top corner.

**Comment by SergiyBelevitnevSFLY** [comment]
Ok, thnx for the explanation. I found solution (for both platforms) :
1. Switch to the native view
2. Get browser address line height + Get system bar height (for android getCapability("statBarHeight"), for ios hard calculation). It will be your margin
3. Switch to the webview
4. After getY of you element add margin from step 2. It will be your updated Y-coordinate
