### ISSUE TITLE
appium desktop 1.20.0 could not start session 

### ISSUE THREAD

**Issue by jiangzhenhua688** [appium/appium#15127]
## The problem
when I start session , appium show an error :"could not start session" 
## Environment

* Appium version 1.20.0 desktop
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js v15.9.0
* Npm 7.5.3
* Mobile platform/version under test: android/iOS
* Real device or emulator/simulator:both
* Appium CLI or Appium.app|exe: Appium.app

## Details

I found 2 error by Inspect element
1.React-Hot-Loader: misconfiguration detected, using production version in non-production environment.
2.React-Hot-Loader: Hot Module Replacement is not enabled.

## Link to Appium logs

no log

**Comment by mykola-mokhnach** [comment]
Sorry, we cannot help nothing without the server logs. The provided details seem unrelated to Appium.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
