### ISSUE TITLE
[Xcode] Exiting due to IDE disconnection - after searching by NSPredicate name and label on iOS 14.4 

### ISSUE THREAD

**Issue by uterator** [appium/appium#15122]
## The problem

When the test requests from driver to find an element by "NSPredicate name and value" locator, the WDA crashes and reports 
xcodebuild exited with code '65' and signal 'null'.
But before searching with "NSPredicate name and value", test works as usual with other locators.

Especially:
- works by `wdName`
- fails after searching by `wdName AND wdLabel`

That happens on one device with iOS 14.4, other 2 devices with iOS 13.3 work as usual in the same environment.

The issue started after updating the device from iOS 14.3 to iOS 14.4.
Before that tests were running on it normally. 
After upgrade, every test execution on the mentioned device fails.

## Environment

* Appium version (or git revision) that exhibits the issue: **1.20.0  or  1.21.0-beta.0**
* Last Appium version that did not exhibit the issue (if applicable): **1.20.0** - shouldn't matter
* Desktop OS/version used to run Appium: CLI
* Node.js version (unless using Appium.app|exe): LTS
* Npm or Yarn package manager: LTS
* Mobile platform/version under test that exhibits the issue: **iOS 14.4**
* Mobile platform/version under test did not exhibits the issue: **iOS 14.3**
* Real device or emulator/simulator: **real device iPhone7** 
* Appium CLI or Appium.app|exe: CLI

### Behavior
1) WDA is built correctly in Xcode.
2) when the test is run, the app and WDA are installed on device.
3) after install, the app opens as expected.
4) after app is opened, the test is able to find and click on element which locators are other than NSPredicate `wdName AND wdLabel`
5) then, the test fails when it reaches to the element which locator is NSPredicate `wdName AND wdLabel`.

The failure log starts with:
```
[Xcode] 2021-02-19 07:48:14.032291-0500 WebDriverAgentRunner-Runner[1348:967874] [Default] Exiting due to IDE disconnection.
[XCUITest] Error getting screenshot: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
```

ends with:

```
[WebDriverAgent] xcodebuild exited with code '65' and signal 'null'
```

## Link to Appium logs

In this log, the test goes few steps forward before reaching to NSPredicate `wdName AND wdLabel` locator search.
[Exiting_due_to_IDE_disconnection_2021-02-19](https://gist.github.com/uterator/73e39da9ec431366c763a676ade27345)

In this log, the test tries to search by NSPredicate `wdName AND wdLabel` locator at the very beginning and fails.
[Exiting_due_to_IDE_disconnection_2021-02-17-short](https://gist.github.com/uterator/4ecc4268d942272df49dede7bcdb20ed)

I can provide more logs, but they are very similar to provided logs.

**Comment by mykola-mokhnach** [comment]
It looks like the request crashes test manager daemon. Try to fetch device logs, but in general I don't think one could get much about it, because it is a private Apple stuff :(

**Comment by mykola-mokhnach** [comment]
Try to use xpath as a workaround (never thought I'm gonna say that %))

**Comment by uterator** [comment]
Thank you @mykola-mokhnach for the quick response.
I will provide more logs.

We will try to avoid locator replacements as there are too many of them. We will avoid it until the issue happens on every device and we are blocked by it.

As for xpaths, they were completely cleaned up from iOS tests long time ago because of performance and probably will not be returned back soon.

**Comment by uterator** [comment]
@mykola-mokhnach maybe this is related to the issue or not, I have enabled both `showIOSLog` and `showXcodeLog` but  [IOSDeviceLog] logs are not printed on that issued device. It looks weird to me. 
When I run the same code (my commit) on another device I get [IOSDeviceLog] logs.
Maybe this information can help somehow or maybe you can put light on this how to get device logs if `showIOSLog` is true, I don't know.

This log portion is from the last lines of the already attached gist Exiting_due_to_IDE_disconnection_2021-02-19. Actually it was cut, sorry about that. 


`
2021-02-19 07:52:23:429 - [XCUITest] Error getting screenshot: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
Unable to save screenshot or copy it: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
`
`
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
`
`
System info: host: 'dev27m.lozzo.local', ip: 'fe80:0:0:0:8:8b0:9cd1:69df%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '11.0.2'
`
`
Driver info: io.appium.java_client.ios.IOSDriver
`

`
Capabilities {app: /Users/builder/appium/confi..., autoAcceptAlerts: false, automationName: XCuiTest, browserName: , databaseEnabled: false, deviceName: dev-iphone7, includeDeviceCapsToSessionInfo: false, javascriptEnabled: true, launchTimeout: 300000, locationContextEnabled: false, mjpegServerPort: 9107, networkConnectionEnabled: false, newCommandTimeout: 600, platform: MAC, platformName: iOS, platformVersion: 14.4, showIOSLog: true, showXcodeLog: true, simpleIsVisibleCheck: true, takesScreenshot: true, udid: f77f3e76fd7d727315b5bf8..., useNewWDA: false, usePrebuiltWDA: true, waitForQuiescence: false, wdaConnectionTimeout: 240000, wdaEventloopIdleDelay: 3, wdaLocalPort: 8107, wdaStartupRetries: 3, webStorageEnabled: false}
`


We can see in Capabilities that
```
showIOSLog: true, showXcodeLog: true
```
but [IOSDeviceLog] logs are not printed.

**Comment by mykola-mokhnach** [comment]
You could still try to get the device log with Xcode

**Comment by uterator** [comment]
Hi @mykola-mokhnach
please find test logs + xcode console logs of one test execution which includes the issue.

[xcode-console-logs-txt](https://gist.github.com/uterator/7143f320587e3878714595a1b19bf2c6#file-xcode-console-logs-txt
)
[test-logs-tst](https://gist.github.com/uterator/7143f320587e3878714595a1b19bf2c6#file-test-logs-tst)

I hope they are helpful.
At checking the XCode for getting logs I couldn't find any logs similar to [IOSDeviceLog]. I hope that console logs can help.

Thanks.

**Comment by Dan-Maor** [comment]
I see that you're setting `waitForQuiescence` to `false` and `wdaEventloopIdleDelay` to `3`, is there an issue launching the app without these parameters? Can you run the same flow without these parameters and let us know if it works?

**Comment by uterator** [comment]
Hi @Dan-Maor, thank you for looking at the issue. I have removed mentioned `waitForQuiescence` and `wdaEventloopIdleDelay` parameters.
Unfortunately results are the same.

Please find execution logs below:
[xcode-console-logs-2-txt](https://gist.github.com/uterator/31848d9502705e5d35a97f1f9d07fea1#file-xcode-console-logs-2-txt)
[test-logs-2-txt](https://gist.github.com/uterator/31848d9502705e5d35a97f1f9d07fea1#file-test-logs-2-txt)

**Comment by mykola-mokhnach** [comment]
> default	12:19:39.048110-0500	testmanagerd	Got screenshot, rotating to orientation 0
> error	12:19:39.052222-0500	kernel	Sandbox: testmanagerd(354) deny(1) iokit-get-properties soc-generation
> error	12:19:39.052529-0500	kernel	Sandbox: testmanagerd(354) deny(1) iokit-get-properties platform-name
> default	12:19:39.054809-0500	backboardd	Connection removed: IOHIDEventSystemConnection uuid:BFC9E667-265D-46BE-B2DB-0CFE11CC3E26 pid:354 process:testmanagerd type:Rate Controlled entitlements:0x8 caller:testmanagerd: -[XCTDAutomationServicesProvider initWithAccessibilitySystem:timeout:error:] + 196 attributes:(null) state:0x1 events:0 mask:0x0
> error	12:19:39.063620-0500	prod	Connection to test daemon interrupted.
> default	12:19:39.067823-0500	backboardd	Connection removed: IOHIDEventSystemConnection uuid:EDEDA1BC-3745-494F-858C-D58D612BE84A pid:354 process:testmanagerd type:Rate Controlled entitlements:0x8 caller:testmanagerd: -[XCTDAutomationServicesProvider initWithAccessibilitySystem:timeout:error:] + 196 attributes:(null) state:0x1 events:0 mask:0x0
> default	12:19:39.074491-0500	backboardd	AXS AccessibilityEnabled: (app ax: 1), ax settings: 1, cached: 1
> default	12:19:39.074609-0500	backboardd	Setting automation enabled: 0
> default	12:19:39.075113-0500	SpringBoard	external-presenter:AirPlay[2-7] power mode did idle off
> default	12:19:39.076253-0500	prod	Received update for automation: 0
> default	12:19:39.082909-0500	prod	Received update for automation: 0
> default	12:19:39.084992-0500	SpringBoard	Received update for automation: 0
> default	12:19:39.085279-0500	SpringBoard	Received update for automation: 0
> default	12:19:39.098954-0500	backboardd	AXS AccessibilityEnabled: (app ax: 1), ax settings: 1, cached: 1
> default	12:19:39.101336-0500	backboardd	Application accessibility enabled: 0, (
> 	0   libAccessibility.dylib              0x000000018925930c _AXSApplicationAccessibilitySetEnabled + 88
> 	1   libAccessibility.dylib              0x000000018925e960 _AXSSetAutomationEnabled + 196
> 	2   AXRuntime                           0x00000001a43f698c _AXNotificationObserverClientDied + 788
> 	3   AXRuntime                           0x00000001a43e58f8 EC42B49D-11D1-381C-A64C-E03AD80E1BF7 + 47352
> 	4   AXRuntime                           0x00000001a43f29b8 EC42B49D-11D1-381C-A64C-E03AD80E1BF7 + 100792
> 	5   CoreFoundation                      0x00000001860ca420 F3021642-E3C0-33F8-9911-DD303A6056D0 + 635936
> 	6   CoreFoundation                      0x00000001860c9834 F3021642-E3C0-33F8-9911-DD303A6056D0 + 632884
> 	7   CoreFoundation                      0x00000001860c39f4 F3021642-E3C0-33F8-9911-DD303A6056D0 + 608756
> 	8   CoreFoundation                      0x00000001860c2ba0 CFRunLoopRunSpecific + 572
> 	9   backboardd                          0x000000010403918c backboardd + 53644
> 	10  libdyld.dyli
> default	12:19:39.102782-0500	backboardd	Stored App AX setting: 0
> default	12:19:39.102945-0500	backboardd	AXS AccessibilityEnabled: (app ax: 0), ax settings: 0, cached: 1
> default	12:19:39.104542-0500	backboardd	AXS AccessibilityEnabled: (app ax: 0), ax settings: 0, cached: 0
> default	12:19:39.104793-0500	backboardd	Application accessibility enabled: 0, (
> 	0   libAccessibility.dylib              0x000000018925930c _AXSApplicationAccessibilitySetEnabled + 88
> 	1   AXRuntime                           0x00000001a43f6994 _AXNotificationObserverClientDied + 796
> 	2   AXRuntime                           0x00000001a43e58f8 EC42B49D-11D1-381C-A64C-E03AD80E1BF7 + 47352
> 	3   AXRuntime                           0x00000001a43f29b8 EC42B49D-11D1-381C-A64C-E03AD80E1BF7 + 100792
> 	4   CoreFoundation                      0x00000001860ca420 F3021642-E3C0-33F8-9911-DD303A6056D0 + 635936
> 	5   CoreFoundation                      0x00000001860c9834 F3021642-E3C0-33F8-9911-DD303A6056D0 + 632884
> 	6   CoreFoundation                      0x00000001860c39f4 F3021642-E3C0-33F8-9911-DD303A6056D0 + 608756
> 	7   CoreFoundation                      0x00000001860c2ba0 CFRunLoopRunSpecific + 572
> 	8   backboardd                          0x000000010403918c backboardd + 53644
> 	9   libdyld.dylib                       0x0000000185da1568 0B475C78-3C12-3121-B7F8-2B95B83DAF44 + 5480
> )
> default	12:19:39.108894-0500	backboardd	Stored App AX setting: 0
> default	12:19:39.109178-0500	backboardd	AXS AccessibilityEnabled: (app ax: 0), ax settings: 0, cached: 0
> default	12:19:39.111315-0500	backboardd	Received update for automation: 0
> default	12:19:39.111434-0500	testmanagerd	Failed to copyDeviceTreeProperty(IODeviceTree:/arm-io soc-generation)
> default	12:19:39.111483-0500	backboardd	Received update for automation: 0
> default	12:19:39.111763-0500	testmanagerd	Failed to get current SOC Generation string
> default	12:19:39.112075-0500	backboardd	Connection removed: IOHIDEventSystemConnection uuid:28C2B9E8-9FD1-4E26-B9D9-1F43E38CBF0A pid:462 process:WebDriverAgentRunner-Runner type:Passive entitlements:0x0 caller:BackBoardServices: <redacted> + 284 attributes:{
>     HighFrequency = 0;
>     bundleID = "com.facebook.WebDriverAgentRunner.xctrunner";
>     pid = 462;
> } state:0x1 events:0 mask:0x0
> default	12:19:39.112260-0500	backboardd	HIDAnalytics Unregister Send event com.apple.hid.queueUsage
> default	12:19:39.112524-0500	runningboardd	Invalidating assertion 32-322-471 (target:[application<com.facebook.WebDriverAgentRunner.xctrunner>:462]) from originator [anon<DTServiceHub>:322]
> default	12:19:39.112588-0500	runningboardd	XPC connection invalidated: [anon<testmanagerd>:354]
> default	12:19:39.113996-0500	SpringBoard	[application<com.facebook.WebDriverAgentRunner.xctrunner>:462] Workspace connection invalidated.
> default	12:19:39.114059-0500	SpringBoard	[application<com.facebook.WebDriverAgentRunner.xctrunner>:462] Now flagged as pending exit for reason: workspace client connection invalidated
> error	12:19:39.114166-0500	WebDriverAgentRunner-Runner	Exiting due to IDE disconnection.
> default	12:19:39.118937-0500	prod	Connection from client with pid 462 was invalidated.
> default	12:19:39.119168-0500	backboardd	AXS AccessibilityEnabled: (app ax: 0), ax settings: 0, cached: 0
> default	12:19:39.119240-0500	backboardd	Setting automation enabled: 0
> default	12:19:39.119291-0500	runningboardd	Invalidating assertion 32-322-470 (target:[application<com.facebook.WebDriverAgentRunner.xctrunner>:462]) from originator [anon<DTServiceHub>:322]
> default	12:19:39.120104-0500	SpringBoard	Received update for automation: 0
> default	12:19:39.120188-0500	prod	Received update for automation: 0
> default	12:19:39.120352-0500	backboardd	AXS AccessibilityEnabled: (app ax: 0), ax settings: 0, cached: 0
> default	12:19:39.120733-0500	backboardd	Application accessibility enabled: 0, (
> 	0   libAccessibility.dylib              0x000000018925930c _AXSApplicationAccessibilitySetEnabled + 88
> 	1   libAccessibility.dylib              0x000000018925e960 _AXSSetAutomationEnabled + 196
> 	2   AXRuntime                           0x00000001a43f698c _AXNotificationObserverClientDied + 788
> 	3   AXRuntime                           0x00000001a43e58f8 EC42B49D-11D1-381C-A64C-E03AD80E1BF7 + 47352
> 	4   AXRuntime                           0x00000001a43f29b8 EC42B49D-11D1-381C-A64C-E03AD80E1BF7 + 100792
> 	5   CoreFoundation                      0x00000001860ca420 F3021642-E3C0-33F8-9911-DD303A6056D0 + 635936
> 	6   CoreFoundation                      0x00000001860c9834 F3021642-E3C0-33F8-9911-DD303A6056D0 + 632884
> 	7   CoreFoundation                      0x00000001860c39f4 F3021642-E3C0-33F8-9911-DD303A6056D0 + 608756
> 	8   CoreFoundation                      0x00000001860c2ba0 CFRunLoopRunSpecific + 572
> 	9   backboardd                          0x000000010403918c backboardd + 53644
> 	10  libdyld.dyli
> default	12:19:39.120892-0500	backboardd	Stored App AX setting: 0
> default	12:19:39.121036-0500	backboardd	AXS AccessibilityEnabled: (app ax: 0), ax settings: 0, cached: 0
> default	12:19:39.121148-0500	ReportCrash	Launched ReportCrash to service - com.apple.ReportCrash
> default	12:19:39.121192-0500	ReportCrash	Trying to create CR directory structure as root
> default	12:19:39.122361-0500	backboardd	AXS AccessibilityEnabled: (app ax: 0), ax settings: 0, cached: 0
> default	12:19:39.122661-0500	backboardd	Application accessibility enabled: 0, (
> 	0   libAccessibility.dylib              0x000000018925930c _AXSApplicationAccessibilitySetEnabled + 88
> 	1   AXRuntime                           0x00000001a43f6994 _AXNotificationObserverClientDied + 796
> 	2   AXRuntime                           0x00000001a43e58f8 EC42B49D-11D1-381C-A64C-E03AD80E1BF7 + 47352
> 	3   AXRuntime                           0x00000001a43f29b8 EC42B49D-11D1-381C-A64C-E03AD80E1BF7 + 100792
> 	4   CoreFoundation                      0x00000001860ca420 F3021642-E3C0-33F8-9911-DD303A6056D0 + 635936
> 	5   CoreFoundation                      0x00000001860c9834 F3021642-E3C0-33F8-9911-DD303A6056D0 + 632884
> 	6   CoreFoundation                      0x00000001860c39f4 F3021642-E3C0-33F8-9911-DD303A6056D0 + 608756
> 	7   CoreFoundation                      0x00000001860c2ba0 CFRunLoopRunSpecific + 572
> 	8   backboardd                          0x000000010403918c backboardd + 53644
> 	9   libdyld.dylib                       0x0000000185da1568 0B475C78-3C12-3121-B7F8-2B95B83DAF44 + 5480
> )
> default	12:19:39.123027-0500	backboardd	Stored App AX setting: 0
> default	12:19:39.123327-0500	backboardd	AXS AccessibilityEnabled: (app ax: 0), ax settings: 0, cached: 0
> default	12:19:39.123754-0500	backboardd	Received update for automation: 0
> default	12:19:39.124366-0500	kernel	LQM-WiFi:TX(A6:17:D8:03:04:19) AC<SU MS NB NRS NA CM EX TF FFP MRET FLE> BE<0 0 0 0 0 0 0 0 0 0 0> (5001ms)
> default	12:19:39.124424-0500	kernel	LQM-WiFi:TX(A6:17:D8:03:04:19) AC<SU MS NB NRS NA CM EX TF FFP MRET FLE> BK<0 0 0 0 0 0 0 0 0 0 0> (5001ms)
> default	12:19:39.124463-0500	kernel	LQM-WiFi:TX(A6:17:D8:03:04:19) AC<SU MS NB NRS NA CM EX TF FFP MRET FLE> VO<0 0 0 0 0 0 0 0 0 0 0> (5001ms)
> default	12:19:39.124499-0500	kernel	LQM-WiFi:L3 Control VO TX(A6:17:D8:03:04:19) Success=0 NoACK=0 Expired=0 OtherErr=0
> default	12:19:39.125433-0500	DTServiceHub	Heartbeat
> default	12:19:39.126774-0500	runningboardd	622FED40-462A-42D5-AADE-69E4814CD6B0 monitor: got an update with state 4
> default	12:19:39.126926-0500	ReportCrash	Parsing corpse data for pid 354
> default	12:19:39.127039-0500	ReportCrash	osa_update: Pid 354 'testmanagerd' CORPSE: Parsing KCData
> default	12:19:39.127294-0500	ReportCrash	osa_update: Pid 354 'testmanagerd' CORPSE: Extracting
> default	12:19:39.127593-0500	runningboardd	[anon<testmanagerd>:354] termination reported by launchd (2, 11, 11)
> default	12:19:39.141288-0500	runningboardd	Removing process: [anon<testmanagerd>:354]
> default	12:19:39.141769-0500	runningboardd	removeJobWithInstance called for identity without existing job [anon<testmanagerd>:354]
> default	12:19:39.141896-0500	runningboardd	Removing assertions for terminated process: [anon<testmanagerd>:354]
> default	12:19:39.142057-0500	runningboardd	Removed last relative-start-date-defining assertion for process application<com.facebook.WebDriverAgentRunner.xctrunner>
> error	12:19:39.143035-0500	runningboardd	[application<com.facebook.WebDriverAgentRunner.xctrunner>:462] Error disabling CPU monitoring: 3
> default	12:19:39.143136-0500	runningboardd	393E5156-BD7F-4F92-A099-40ABB1EF44A7 monitor: got an update with state 4
> default	12:19:39.143198-0500	runningboardd	[application<com.facebook.WebDriverAgentRunner.xctrunner>:462] termination reported by launchd (0, 0, 18944)
> default	12:19:39.143249-0500	runningboardd	Calculated state for application<com.facebook.WebDriverAgentRunner.xctrunner>: running-active (role: NonUserInteractive)
> default	12:19:39.143338-0500	SpringBoard	Firing exit handlers for 354 with context <RBSProcessExitContext| specific, status:<RBSProcessExitStatus| domain:signal(2) code:SIGSEGV(11)>>
> default	12:19:39.143409-0500	SpringBoard	[anon<testmanagerd>:354] Now flagged as pending exit for reason: launch failed
> default	12:19:39.143461-0500	powerd	Process runningboardd.32 Released SystemIsActive "application<com.facebook.WebDriverAgentRunner.xctrunner>32-354-476:Developer testing(BackgroundUI)" age:00:00:31  id:51539646299 [System: PrevIdle SysAct]
> default	12:19:39.143651-0500	runningboardd	Removing process: [application<com.facebook.WebDriverAgentRunner.xctrunner>:462]
> default	12:19:39.143872-0500	runningboardd	Released power assertion with ID 38747
> default	12:19:39.144042-0500	SpringBoard	[anon<testmanagerd>:354] Process exited: <RBSProcessExitContext| specific, status:<RBSProcessExitStatus| domain:signal(2) code:SIGSEGV(11)>>.
> default	12:19:39.144092-0500	SpringBoard	[anon<testmanagerd>:354] Setting process task state to: Not Running
> default	12:19:39.144139-0500	SpringBoard	[anon<testmanagerd>:354] Invalidating workspace.
> default	12:19:39.144190-0500	SpringBoard	Removing workspace registration for processHandle: [anon<testmanagerd>:354]
> default	12:19:39.144237-0500	SpringBoard	Removing: <FBProcess: 0x109fdbf60; anon<testmanagerd>:354(v3E1)>
> default	12:19:39.144575-0500	runningboardd	Removing launch job for: [application<com.facebook.WebDriverAgentRunner.xctrunner>:462]
> default	12:19:39.144628-0500	runningboardd	<OSLaunchdJob | handle=393E5156-BD7F-4F92-A099-40ABB1EF44A7>: remove succeeded
> default	12:19:39.144675-0500	runningboardd	Removed job for [application<com.facebook.WebDriverAgentRunner.xctrunner>:462]
> default	12:19:39.144732-0500	runningboardd	Removing assertions for terminated process: [application<com.facebook.WebDriverAgentRunner.xctrunner>:462]
> default	12:19:39.144779-0500	runningboardd	XPC connection invalidated: [anon<testmanagerd>:354]
> error	12:19:39.145524-0500	runningboardd	RBSStateCapture remove item called for untracked item <RBConnectionClient| 354 name:anon<testmanagerd> entitlements:<RBEntitlements| [
> 			com.apple.assertiond.app-state-monitor,
> 			com.apple.multitasking.unlimitedassertions,
> 			com.apple.multitasking.termination
> 			]> inheritanceManager:<RBClientInheritanceManager| >>
> default	12:19:39.146264-0500	runningboardd	Calculated state for application<com.facebook.WebDriverAgentRunner.xctrunner>: none (role: None)
> default	12:19:39.146374-0500	runningboardd	Calculated state for application<com.facebook.WebDriverAgentRunner.xctrunner>: none (role: None)
> default	12:19:39.146437-0500	SpringBoard	Firing exit handlers for 462 with context <RBSProcessExitContext| voluntary>
> default	12:19:39.146522-0500	runningboardd	XPC connection invalidated: [application<com.facebook.WebDriverAgentRunner.xctrunner>:462]
> default	12:19:39.146591-0500	SpringBoard	[application<com.facebook.WebDriverAgentRunner.xctrunner>:462] Process exited: <RBSProcessExitContext| voluntary>.
> default	12:19:39.146641-0500	SpringBoard	[application<com.facebook.WebDriverAgentRunner.xctrunner>:462] Setting process task state to: Not Running
> default	12:19:39.146687-0500	SpringBoard	[application<com.facebook.WebDriverAgentRunner.xctrunner>:462] Setting process visibility to: Unknown
> default	12:19:39.146744-0500	SpringBoard	[application<com.facebook.WebDriverAgentRunner.xctrunner>:462] Invalidating workspace.
> default	12:19:39.146994-0500	SpringBoard	Removing workspace registration for processHandle: [application<com.facebook.WebDriverAgentRunner.xctrunner>:462]
> default	12:19:39.147044-0500	SpringBoard	Removing: <FBApplicationProcess: 0x115cf4c00; application<com.facebook.WebDriverAgentRunner.xctrunner>:462(v516)>
> default	12:19:39.147126-0500	SpringBoard	Updating configuration of monitor <RBSProcessMonitorConfiguration| id:M59-2 qos:25 predicates:[<RBSProcessPredicate <RBSProcessIdentifierPredicate| 465>>, <RBSProcessPredicate <RBSProcessIdentifierPredicate| 327>>] descriptor:<RBSProcessStateDescriptor| values:1> events:0x0>
> default	12:19:39.147219-0500	SpringBoard	Process exited: <FBApplicationProcess: 0x115cf4c00; application<com.facebook.WebDriverAgentRunner.xctrunner>:462(v516)> -> <RBSProcessExitContext| voluntary>
> default	12:19:39.147324-0500	SpringBoard	lock/volume priority is:volume
> default	12:19:39.147368-0500	SpringBoard	reconfigured lock button: <SBMutableHardwareButtonGestureParameters: 0x2821fa980; maximumPressCount: 1; longPressTimeInterval: 2.50s; multiplePressTimeInterval: 0.30s>
> default	12:19:39.147418-0500	SpringBoard	lock/volume priority is:volume
> default	12:19:39.147464-0500	SpringBoard	Application process state changed for com.facebook.WebDriverAgentRunner.xctrunner: (null)
> error	12:19:39.150835-0500	SpringBoard	Ignoring state for untracked process [application<com.facebook.WebDriverAgentRunner.xctrunner>:462]: <RBSProcessState| task:none debug:none>
> default	12:19:39.151633-0500	ReportCrash	osa_update: Pid 354 'testmanagerd' CORPSE: Symbolicating
> default	12:19:39.151750-0500	mediaserverd	-CMSessionMgr- CMSessionMgrHandleApplicationStateChange: Client com.facebook.WebDriverAgentRunner.xctrunner with pid '462' is now Terminated. Background entitlement: NO ActiveLongFormVideoSession: NO WhitelistedLongFormVideoApp NO
> default	12:19:39.151817-0500	ReportCrash	osa_update: Pid 354 'testmanagerd' CORPSE: Symbolicating2
> default	12:19:39.151983-0500	ReportCrash	<private>: [<private>] '(null)'
> default	12:19:39.169145-0500	lockdownd	handle_get_value: <private>
> default	12:19:39.172197-0500	lockdownd	handle_get_value: <private>
> default	12:19:39.175728-0500	lockdownd	handle_get_value: <private>
> default	12:19:39.177982-0500	SpringBoard	[com.facebook.WebDriverAgentRunner.xctrunner] com.facebook.WebDriverAgentRunner.xctrunner application state changed to Terminated


It is clearly visible here that testmanagerd has crashed. Only Apple is capable of fixing that

**Comment by Dan-Maor** [comment]
There's something strange here though - it looks like what caused the crash is actually taking a screenshot rather than the `findElement` operation.

I see that you're capturing video during the session and taking screenshots, can you please try to disable these options and see whether this helps? Just for the sake of verifying, I have a feeling this may be the cause here. Unfortunately however @mykola-mokhnach is right - even if it's the screenshot that's causing the crash, this is something only Apple are able to fix.

**Comment by uterator** [comment]
Disabling screenshots let the test to pass.

Many thanks @Dan-Maor for the wise suggestion.

logs: [worked_without_screenshots](https://gist.github.com/uterator/1181ed712897b151f6486578f973a4d5)

Thank you!

**Comment by Dan-Maor** [comment]
You're most welcome.

Out of curiosity - is there anything different happening in the application at the time of the crash?

**Comment by uterator** [comment]
I will do more observation related to crash moment and let you know.
As for screenshot, both video and screenshots were used.

I am looking for another method to get screenshots as they are mandatory, seems support for idevicescreenshot was [removed](https://github.com/appium/appium-xcuitest-driver/pull/1022).

**Comment by Dan-Maor** [comment]
Maybe that's the problem. 
Can you try to run the test with screenshots but without capturing video?

**Comment by mykola-mokhnach** [comment]
@uterator I've prepared a [pull request](https://github.com/appium/WebDriverAgent/pull/470) to ensure that WDA never tries to send two parallel screenshoting requests to testmanagerd. Please check it out and try if it it helps to resolve your issue.

**Comment by uterator** [comment]
Hi @mykola-mokhnach , sorry but the PR didn't help.

Tested on branch [screen_lock](https://github.com/appium/WebDriverAgent/tree/screen_lock).
Result is the same.

Here are execution logs (missing device logs, please let me know if device logs are needed, and for which scenario)

[passed__15122__screenshot_false__recording_true](https://gist.github.com/uterator/efa188bd26fbceaceb83c725fc621f64#file-passed__15122__screenshot_false__recording_true)

[failed__15122__Screenshot_true__Recording_false](https://gist.github.com/uterator/efa188bd26fbceaceb83c725fc621f64#file-failed__15122__screenshot_true__recording_false)

[failed__15122__screenshot_true__recording_true](
https://gist.github.com/uterator/efa188bd26fbceaceb83c725fc621f64#file-failed__15122__screenshot_true__recording_true)


@Dan-Maor at observing the app behavior at the crash moment, nothing important happens, it opens, then closes.

As WDA's native screenshot fails, maybe it worth to try an alternative screenshoter? Can you advice one that I can run the test with it.

Thanks,

**Comment by mykola-mokhnach** [comment]
I would try to play with the screenshotting settings (e.g. set `screenshotQuality` to `2`) if this also fails with screen recording disabled. Perhaps, the service is simply out of memory.

**Comment by Dan-Maor** [comment]
Just noticed something else from the original log, it seems that at the moment of the crash the screenshot is requested with a `heic` format instead of `jpeg`:

All screenshot requests before the crash look like:
`default	12:19:39.001600-0500	testmanagerd	Test session <XCTestSession: 0x100823090> pid 462 requested screenshot with parameters Screenshot request for screenID 1, rect {{inf, inf}, {0.0, 0.0}}, format UTI public.jpeg, compression quality 0.1000000014901161, orientation 1`

The screenshot that causes the crash looks like:
`default	12:19:39.044302-0500	testmanagerd	Test session <XCTestSession: 0x100823090> pid 462 requested screenshot with parameters Screenshot request for screenID 1, rect {{inf, inf}, {0.0, 0.0}}, format UTI public.heic, compression quality 0.7, orientation 1`

Guess that's the problem, need to dig deeper to figure out how to prevent from `heic` to be used.

**Comment by mykola-mokhnach** [comment]
@Dan-Maor I assume this is the change that Apple did explicitly to XCTest (saw it somewhere in the release notes). We should probably replace `mainScreen screenshotDataForQuality` calls with the `proxy _XCT_requestScreenshotOfScreenWithID` one, where the desired UTI could be set explicitly.

**Comment by uterator** [comment]
Hi @mykola-mokhnach, unfortunately setting `screenshotQuality=2` didn't help, the results are same.
By setting that setting, I see low quality screenshots on another device, however on that upgraded device I see the same crash.
Please let me know if you need more details or if I can test anything else.
Thanks

**Comment by mykola-mokhnach** [comment]
I have recently published the patch https://github.com/appium/WebDriverAgent/pull/474, which prevents HEIC screenshots completely. Try it, otherwise I don't have any more good ideas

**Comment by uterator** [comment]
:1st_place_medal: **BIG THANK YOU** :1st_place_medal:  @Dan-Maor and :1st_place_medal:   @mykola-mokhnach 

You solved the problem :100: 

The `no_heic` patch fixed the WDA crash at screenshoting :+1:

Now tests are passing on mentioned iPhone7 device with 14.4 iOS.

Just one note about screenshot quality:
when it is default `screenshotQuality=1`, I see too many of these messages
```
2021-03-02 16:33:20:432 - [Xcode] 2021-03-02 16:33:20.568470-0500 WebDriverAgentRunner-Runner[2886:2406487] Cannot take a screenshot within 500 ms timeout
2021-03-02 16:33:20:432 - [Xcode]
2021-03-02 16:33:21:011 - [Xcode] 2021-03-02 16:33:21.144729-0500 WebDriverAgentRunner-Runner[2886:2406487] Cannot take a screenshot within 500 ms timeout
2021-03-02 16:33:21:011 - [Xcode]
2021-03-02 16:33:21:585 - [Xcode] 2021-03-02 16:33:21.720322-0500 WebDriverAgentRunner-Runner[2886:2406487] Cannot take a screenshot within 500 ms timeout
2021-03-02 16:33:21:585 - [Xcode]
2021-03-02 16:33:22:132 - [Xcode] 2021-03-02 16:33:22.267819-0500 WebDriverAgentRunner-Runner[2886:2406487] Cannot take a screenshot within 500 ms timeout
2021-03-02 16:33:22:132 - [Xcode]
2021-03-02 16:33:22:672 - [Xcode] 2021-03-02 16:33:22.808284-0500 WebDriverAgentRunner-Runner[2886:2406487] Cannot take a screenshot within 500 ms timeout
2021-03-02 16:33:22:672 - [Xcode]
2021-03-02 16:33:23:247 - [Xcode] 2021-03-02 16:33:23.384327-0500 WebDriverAgentRunner-Runner[2886:2406487] Cannot take a screenshot within 500 ms timeout
2021-03-02 16:33:23:248 - [Xcode]
2021-03-02 16:33:23:798 - [Xcode] 2021-03-02 16:33:23.934492-0500 WebDriverAgentRunner-Runner[2886:2406487] Cannot take a screenshot within 500 ms timeout
2021-03-02 16:33:23:798 - [Xcode]
2021-03-02 16:33:24:370 - [Xcode] 2021-03-02 16:33:24.506803-0500 WebDriverAgentRunner-Runner[2886:2406487] Cannot take a screenshot within 500 ms timeout
2021-03-02 16:33:24:370 - [Xcode]
2021-03-02 16:33:24:944 - [Xcode] 2021-03-02 16:33:25.080646-0500 WebDriverAgentRunner-Runner[2886:2406487] Cannot take a screenshot within 500 ms timeout
...
```

when it is low `screenshotQuality=2`, I see few of them.

With screenshot default quality the test execution took `00:05:37`
With screenshot low quality the test execution took `00:04:24`, more than 1 minute faster.

Screenshots sizes are: 
Normal quality: `304.6 KB`
Low quality: `227.3 KB`
The visual difference is not big but we can save a lot of time at a full run.

Thank you guys once more. You are real savers.

Closing!
