### ISSUE TITLE
The JAVA_HOME location must exist

### ISSUE THREAD

**Issue by tahasaeed96** [appium/appium#15137]
## The problem

I have entered the desired capabilities in appium desktop and when srtarting the session this error occured. I have set the environment variables as well
## Environment

* Appium version =1.19.1
* Desktop OS/version used to run Appium: windows 10
* Node.js version = 12.8.1
* Mobile platform/version under test= Android, 10.0
* Real device or emulator/simulator= emulator ( android  studio)
* Appium CLI or Appium.app= appium,exe

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
[appium-server-logs.txt](https://github.com/appium/appium/files/6037429/appium-server-logs.txt)

An unknown server-side error occurred while processing the command. Original error: Cannot verify the signature of 'C:\Users\RVT-LP-2021-JAN-07\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.15.0.apk'. Original error: The JAVA_HOME location '.;C:\Program Files\Java\jdk-15.0.2\bin;".;C:\Program Files\Java\jdk-15.0.2";C:\Users\RVT-LP-2021-JAN-07\AppData\Local\Android\Sdk\tools;C:\Users\RVT-LP-2021-JAN-07\AppData\Local\Android\Sdk\platform-tools;' must exist

**Comment by mykola-mokhnach** [comment]
It looks like the JAVA_HOME is not set properly for your system. Check https://github.com/appium/java-client/blob/master/docs/environment.md for more details

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
