### ISSUE TITLE
Unable to Login FSM(CRM D365) app using Appium 

### ISSUE THREAD

**Issue by badarmunirr** [appium/appium#15130]
## The problem

When I am trying to login FSM(Field Service Mobile) App using appium I am getting ID3242 Error .

## Environment

* Appium version (or git revision) that exhibits the issue:
Appium Latest with C#

## Code To Reproduce Issue [ Good To Have ]

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/64267888/108853830-fe1c1000-7608-11eb-9e86-727591f5ac71.png)

**Comment by mykola-mokhnach** [comment]
Please fill out the issue report according to the given template. The actual error looks unrelated to Appium

**Comment by mykola-mokhnach** [comment]
Closed because of no response
