### ISSUE TITLE
I cant get tagname from MobileElement

### ISSUE THREAD

**Issue by fleytman** [appium/appium#15142]
## The problem

I'm trying to release the scroll to the end of the screen. To do this, I want to get a list of element tags. But for some reason they are null.

## Environment

* Appium version (or git revision) that exhibits the issue:v1.20.2
* Desktop OS/version used to run Appium: macos
* Mobile platform/version under test: Android API29
* Real device or emulator/simulator: emulator x86
* Appium CLI or Appium.app|exe: App
* Lang: Kotlin

## Details

Algorithm with which I want to implement scrolling:
1. Get the children of the RecyclerView
val childs = driver.findElements(MobileBy.xpath("//androidx.recyclerview.widget.RecyclerView[@resource-id='${BasePage.packageName}parent']/*")) as MutableList<out MobileElement>?
2. Get tagName, for example
childs?.get(0).tagName
3. Make a scroll
4. Check the list of tagName on the page has changed or not

For some reason, in step 2, I always get null. Although in the application code tagName is specified. Perhaps I solve the problem incorrectly, but searches on the Internet did not give anything

## Link to Appium logs

[HTTP] --> GET /wd/hub/session/471db534-a367-40fc-a3fe-15637416cd8d/element/ebb750f3-00e6-4017-b5cf-4f217d1ee0a9/name
[HTTP] {}
[W3C (471db534)] Calling AppiumDriver.getName() with args: ["ebb750f3-00e6-4017-b5cf-4f217d1ee0a9","471db534-a367-40fc-a3fe-15637416cd8d"]
[WD Proxy] Matched '/element/ebb750f3-00e6-4017-b5cf-4f217d1ee0a9/name' to command name 'getName'
[WD Proxy] Proxying [GET /element/ebb750f3-00e6-4017-b5cf-4f217d1ee0a9/name] to [GET http://127.0.0.1:8202/wd/hub/session/c58cc700-8383-4936-b7ac-b20f2ee8b373/element/ebb750f3-00e6-4017-b5cf-4f217d1ee0a9/name] with no body
[WD Proxy] Got response with status 200: {"sessionId":"c58cc700-8383-4936-b7ac-b20f2ee8b373","value":null}
[W3C (471db534)] Responding to client with driver.getName() result: null
[HTTP] <-- GET /wd/hub/session/471db534-a367-40fc-a3fe-15637416cd8d/element/ebb750f3-00e6-4017-b5cf-4f217d1ee0a9/name 200

**Comment by KazuCocoa** [comment]
What the page source?

**Comment by mykola-mokhnach** [comment]
UiAutomator2 does not have access to tags as these are not exposed to the accessibility layer. Only Espresso driver does.

**Comment by fleytman** [comment]
> What the page source?

what do you mean?

**Comment by fleytman** [comment]
> UiAutomator2 does not have access to tags as these are not exposed to the accessibility layer. Only Espresso driver does.

Based on https://appium.io/docs/en/commands/element/attributes/name/, I thought geTagName should work with UiAutomator2.

**Comment by fleytman** [comment]
It seems we managed to find a workaround. Put id instead of tag in the application and use the following code:
childs?.get(0).getAttribute("resourceid")

**Comment by mykola-mokhnach** [comment]
> Based on https://appium.io/docs/en/commands/element/attributes/name/, I thought getTagName should work with UiAutomator2.

Unfortunately it does not. [Here](https://github.com/appium/appium-uiautomator2-driver#element-attributes) is the full list of element attributes available for UIA2 driver element.

**Comment by fleytman** [comment]
Thanks for the tip.
Will you update the documentation at https://appium.io/docs/en/commands/element/attributes/name/?

**Comment by fleytman** [comment]
Going back to my original problem. Is there a way to understand that we are on the border of  RecyclerView and there is no need to scroll anymore? Maybe there is some standard way to solve the problem of scrolling to the end of the screen?

**Comment by mykola-mokhnach** [comment]
There are some workarounds, although they are not always reliable with UiAutomator framework. You could either try scrolling via UiSelector:
- http://appium.io/docs/en/writing-running-appium/android/uiautomator-uiselector/
- https://developer.android.com/reference/androidx/test/uiautomator/UiScrollable
- https://www.youtube.com/watch?v=KbPfi-OVz3g

or via mobile gestures:
- https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/android-mobile-gestures.md#mobile-scrollgesture
- https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/android-mobile-gestures.md#mobile-flinggesture

**Comment by KazuCocoa** [comment]
For https://github.com/appium/appium/issues/15142#issuecomment-786490422 
I meant http://appium.io/docs/en/commands/session/source/ to see available For attributes.
