### ISSUE TITLE
allowInvisibleElements in 1.20.2

### ISSUE THREAD

**Issue by lokoArt** [appium/appium#15143]
## The problem

I've been using appium 1.18 and I liked allowInvisibleElements capability that allowed me to gett the whole page's code without scrolling. After upgrading to the new appium(1.20.2) adding this flag to capability makes the driver fail. So I had to delete it, however I cannot find any substitution for this flag. So how can I get the activity's code without scrolling? Yes, I use it with UIAtomator2

**Comment by KazuCocoa** [comment]
Please fill out the issue template you might see (it addressed the appium logs as well) to fix if something issue was there.

**Comment by mykola-mokhnach** [comment]
This is not capability, but a [setting](https://appium.io/docs/en/advanced-concepts/settings/)
