### ISSUE TITLE
how to install appium using npm install when machine has no internet conenction?

### ISSUE THREAD

**Issue by lovelyplanet2019** [appium/appium#15147]
my machine has no internet connect. I have tried installed appium desktop version but error compatibility with adb , error like cannot kill adb server.

i am thinking to try appium command line version.
I have npm installed but no internet connection to direct download appium over internet when running command 'npm install -g appium'.

how do i proceed to install command version of appium?

**Comment by mykola-mokhnach** [comment]
Copy the deployment from a machine which has a connection and create binary symlinks manually if needed.

Please use Appium forum to ask questions
