### ISSUE TITLE
[IOS] Can't perform screen recording on multiple devices.

### ISSUE THREAD

**Issue by ilushkafi** [appium/appium#15141]
## The problem

IOS. Trying to perform screen recording on multiple physical devices. 
**Expected** : Recording on all connected devices. 
**Actual** : Only one recording session can be created. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS (Catalina 10.15.7)
* Node.js version (unless using Appium.app|exe): v14.16.0
* Npm or Yarn package manager: npm 6.14.11
* Mobile platform/version under test: 13,12
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Working with 2 iOS physical devices. Creating the Appium drivers and trying to start recording session one by one with using deferent drivers instances. Each driver runs on different port. The first recording session is started but the second overrides the first.

## Link to Appium logs

Log : https://gist.github.com/ilushkafi/ce0cda4dca0a7ae3463fbb29fbe88a41

**Comment by mykola-mokhnach** [comment]
> 2021-02-25 16:47:16:871 - [DevCon Factory] Port #9100 is busy. Did you quit the previous driver session(s) properly?
> 2021-02-25 16:47:16:874 - [XCUITest] Cannot forward the local port 9100 to 9100 on the device b7f7570e3d9ea8eaa4df9dd4f9564dfce243ec7e. Set the custom value to 'mjpegServerPort' capability if this is an undesired behavior.

I assume the log message there is pretty clear

**Comment by ilushkafi** [comment]
@mykola-mokhnach Haven't been aware regarding this capability. Thanks a lot!
