### ISSUE TITLE
npm i appium 1.20.2 "document not found"

### ISSUE THREAD

**Issue by Archer456** [appium/appium#15146]
## The problem
 npm install -g appium

npm ERR! 404 Not Found - GET http://registry.npm.taobao.org/@jimp/utils/-/utils-0.16.1.tgz - [not_found] document not found
npm ERR! 404 
npm ERR! 404  '@jimp/utils@http://registry.npm.taobao.org/@jimp/utils/-/utils-0.16.1.tgz' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

## Environment

cmd@legion:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
cmd@legion:~$ node -v
v14.16.0
cmd@legion:~$ npm -v
7.6.0

## Details
 npm install -g appium

npm ERR! code E404
npm ERR! 404 Not Found - GET http://registry.npm.taobao.org/@jimp/utils/-/utils-0.16.1.tgz - [not_found] document not found
npm ERR! 404 
npm ERR! 404  '@jimp/utils@http://registry.npm.taobao.org/@jimp/utils/-/utils-0.16.1.tgz' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cmd/.npm/_logs/2021-03-01T03_08_13_336Z-debug.log

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by KazuCocoa** [comment]
It seems you used your own npm repository.
`registry.npm.taobao.org`

Please ask the org to sync the repository with npm public repository or adding the library to the private repository.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by youngfreeFJS** [comment]
Same here.
`npm ERR! 404  '@jimp/utils@https://registry.npm.taobao.org/@jimp/utils/-/utils-0.16.1.tgz' is not in the npm registry.
`
Doing `npm cache clean --force` fixed the issue for me.

@Archer456
