### ISSUE TITLE
ApplicationVerificationFailed error when start using appuim

### ISSUE THREAD

**Issue by DannnniHuang** [appium/appium#15145]
## The problem

I want to using appium to auto test my company ios app, but I got issue that {"Error":"ApplicationVerificationFailed","ErrorDetail":-1,"ErrorDescription":"Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.XWrBO7/extracted/Helpsy.app : 0xe8008018 (The identity used to sign the executable is no longer valid.)"}

## Environment

* Appium version (or git revision) that exhibits the issue: v1.18.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS 10.15
* Node.js version (unless using Appium.app|exe): v12.18.4
* Npm or Yarn package manager: 6.14.8
* Mobile platform/version under test: ios 14.3
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium.app

## Link to Appium logs

[Appium] Welcome to Appium v1.18.3
[Appium] Non-default server args:
[Appium]   relaxedSecurityEnabled: true
[Appium]   allowInsecure: {
[Appium]   }
[Appium]   denyInsecure: {
[Appium]   }
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"/Users/dannihuang/Documents/HelpsyHealth_Intern/Helpsy 2020-11-18 17-19-07/Apps/Helpsy-0A030C11-3F28-4FD6-91F8-3385E657789E.ipa","bundleId":"com.helpsy.Helpsy","deviceName":"iphone x","platformName":"ios","platformVersion":"14.3","udid":"2a4c35e850e824ee0f6537591aa554d7fd8cfb03","xcodeOrgId":"5DSXGS7UGH","xcodeSigningId":"iPhone Developer","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/dannihuang/Documents/HelpsyHealth_Intern/Helpsy 2020-11-18 17-19-07/Apps/Helpsy-0A030C11-3F28-4FD6-91F8-3385E657789E.ipa","bundleId":"com.helpsy.Helpsy","deviceName":"iphone x","platformName":"ios","platformVersion":"14.3","udid":"2a4c35e850e824ee0f6537591aa554d7fd8cfb03","xcodeOrgId":"5DSXGS7UGH","xcodeSigningId":"iPhone Developer","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1614484513839 (22:55:13 GMT-0500 (Eastern Standard Time))
[Appium] DeprecationWarning: 'automationName' capability was not provided. Future versions of Appium will require 'automationName' capability to be set for iOS sessions.
[Appium] Requested iOS support with version >= 10, using 'XCUITest' driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Appium v1.18.3 creating new XCUITestDriver (v3.29.0) session
[Appium] Applying relaxed security to 'XCUITestDriver' as per server command line argument. All insecure features will be enabled unless explicitly disabled by --deny-insecure
[BaseDriver] Creating session with MJSONWP desired capabilities: {
[BaseDriver]   "app": "/Users/dannihuang/Documents/HelpsyHealth_Intern/Helpsy 2020-11-18 17-19-07/Apps/Helpsy-0A030C11-3F28-4FD6-91F8-3385E657789E.ipa",
[BaseDriver]   "bundleId": "com.helpsy.Helpsy",
[BaseDriver]   "deviceName": "iphone x",
[BaseDriver]   "platformName": "ios",
[BaseDriver]   "platformVersion": "14.3",
[BaseDriver]   "udid": "2a4c35e850e824ee0f6537591aa554d7fd8cfb03",
[BaseDriver]   "xcodeOrgId": "5DSXGS7UGH",
[BaseDriver]   "xcodeSigningId": "iPhone Developer",
[BaseDriver]   "newCommandTimeout": 0,
[BaseDriver]   "connectHardwareKeyboard": true
[BaseDriver] }
[BaseDriver] Session created with session id: 8243fdb7-ed6a-4f24-8e19-39778ca2a31c
[XCUITest] Current user: 'dannihuang'
[XCUITest] Available devices: 2a4c35e850e824ee0f6537591aa554d7fd8cfb03
[XCUITest] Creating iDevice object with udid '2a4c35e850e824ee0f6537591aa554d7fd8cfb03'
[XCUITest] Determining device to run tests on: udid: '2a4c35e850e824ee0f6537591aa554d7fd8cfb03', real device: true
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1614484513869 (22:55:13 GMT-0500 (Eastern Standard Time))
[BaseDriver] Using local app '/Users/dannihuang/Documents/HelpsyHealth_Intern/Helpsy 2020-11-18 17-19-07/Apps/Helpsy-0A030C11-3F28-4FD6-91F8-3385E657789E.ipa'
[BaseDriver] Will reuse previously cached application at '/var/folders/yb/5t6hktk57h16lql1f2w3h96r0000gn/T/2021127-51769-dhke54.9cjr5/Helpsy.app'
[BaseDriver] Event 'appConfigured' logged at 1614484514030 (22:55:14 GMT-0500 (Eastern Standard Time))
[XCUITest] Checking whether app '/var/folders/yb/5t6hktk57h16lql1f2w3h96r0000gn/T/2021127-51769-dhke54.9cjr5/Helpsy.app' is actually present on file system
[XCUITest] App is present
[BaseDriver] Event 'resetStarted' logged at 1614484514030 (22:55:14 GMT-0500 (Eastern Standard Time))
[XCUITest] Reset: running ios real device reset flow
[BaseDriver] Event 'resetComplete' logged at 1614484514030 (22:55:14 GMT-0500 (Eastern Standard Time))
[WebDriverAgent] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent'
[WebDriverAgent] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'
[XCUITest] Crash reports root '/Users/dannihuang/Library/Logs/CrashReporter/MobileDevice/🐿' does not exist. Got nothing to gather.
[BaseDriver] Event 'logCaptureStarted' logged at 1614484514210 (22:55:14 GMT-0500 (Eastern Standard Time))
[XCUITest] Setting up real device
[XCUITest] Verifying application platform
[XCUITest] CFBundleSupportedPlatforms: ["iPhoneOS"]
[XCUITest] Reset requested. Removing app with id 'com.helpsy.Helpsy' from the device
[XCUITest] Installing '/var/folders/yb/5t6hktk57h16lql1f2w3h96r0000gn/T/2021127-51769-dhke54.9cjr5/Helpsy.app' on device with UUID '2a4c35e850e824ee0f6537591aa554d7fd8cfb03'...
[WebDriverAgent] Parsed BUILD_DIR configuration value: '/Users/dannihuang/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Build/Products'
[WebDriverAgent] Got derived data root: '/Users/dannihuang/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp'
[Support] Traversed 1878 directories and 2590 files in 26988ms
[XCUITest] Pushed the app files successfully after 27106ms
[XCUITest] Error installing app: Unexpected data: {"Error":"ApplicationVerificationFailed","ErrorDetail":-1,"ErrorDescription":"Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.vphTbB/extracted/Helpsy.app : 0xe8008018 (The identity used to sign the executable is no longer valid.)"}
[XCUITest] Falling back to 'ios-deploy' usage
[XCUITest] {}
[DevCon Factory] Releasing connections for 2a4c35e850e824ee0f6537591aa554d7fd8cfb03 device on any port number
[DevCon Factory] No cached connections have been found
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[BaseDriver] Event 'newSessionStarted' logged at 1614484585183 (22:56:25 GMT-0500 (Eastern Standard Time))
[MJSONWP] Encountered internal error running command: Error: Could not install '/var/folders/yb/5t6hktk57h16lql1f2w3h96r0000gn/T/2021127-51769-dhke54.9cjr5/Helpsy.app':
[MJSONWP]   - Unexpected data: {"Error":"ApplicationVerificationFailed","ErrorDetail":-1,"ErrorDescription":"Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.vphTbB/extracted/Helpsy.app : 0xe8008018 (The identity used to sign the executable is no longer valid.)"}
[MJSONWP]   - 2021-02-27 22:56:25.171 ios-deploy[57952:4249030] [ !! ] Error 0xe8008018: The identity used to sign the executable is no longer valid. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)
[MJSONWP] 
[MJSONWP]     at IOSDeploy.install (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/ios-deploy.js:56:15)
[MJSONWP] Destroying socket connection
[HTTP] <-- POST /wd/hub/session 500 71348 ms - 785
[HTTP] 
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 7 ms - 57
[HTTP] 
Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

**Comment by mykola-mokhnach** [comment]
- Make sure sure the app is signed with a valid development certificate
- Use the most recent Appium server version

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
