### ISSUE TITLE
INSTRUMENTATION crash randomly

### ISSUE THREAD

**Issue by tranduyminh91** [appium/appium#15154]
## The problem

While i running test suite on cloud device, I got randomly error INSTRUMENTATION_RESULT: shortMsg=Process crashed
I dont know why it happend, please help

## Environment

* Appium version : 1.20.2
* Desktop OS/version used to run Appium: Win10
* Node.js version: 12.8.1
* Mobile platform/version under test: Android 10
* Real device or emulator/simulator: Real device on cloud
* Appium CLI or Appium.app|exe: Appium desktop

## Link to Appium logs

[https://gist.github.com/tranduyminh91/db7ff240333b01d2825ff8f608b8490d](url)

**Comment by mykola-mokhnach** [comment]
Please attach the logcat output for the given time period

**Comment by tranduyminh91** [comment]
hi @mykola-mokhnach ,

This is new appium log and device log cat

[https://gist.github.com/tranduyminh91/6aa1743585b62aa7f2b4b54fb9bf29b1](url)
Thanks,
Minh

**Comment by mykola-mokhnach** [comment]
> 2021-03-03 15:41:14.473 15352-15352/? D/AndroidRuntime: Calling main entry com.android.commands.am.Am
> 2021-03-03 15:41:14.478 1275-2129/? I/ActivityManager: Force stopping io.appium.uiautomator2.server appid=10591 user=0: start instr
> 2021-03-03 15:41:14.479 1275-2129/? I/ActivityManager: Killing 13730:io.appium.uiautomator2.server/u0a591 (adj 0): stop io.appium.uiautomator2.server
> 2021-03-03 15:41:14.480 1275-2129/? W/ActivityManager: Crash of app io.appium.uiautomator2.server running instrumentation ComponentInfo{io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner}
> 2021-03-03 15:41:14.480 1275-2129/? I/ActivityManager: Force stopping io.appium.uiautomator2.server appid=10591 user=0: finished inst
> 2021-03-03 15:41:14.481 1275-15372/? W/Binder: Outgoing transactions from this process must be FLAG_ONEWAY
>     java.lang.Throwable
>         at android.os.BinderProxy.transact(BinderProxy.java:493)
>         at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:205)
>         at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)
> 2021-03-03 15:41:14.481 13707-13728/? W/Binder: Caught a RuntimeException from the binder stub implementation.
>     java.lang.SecurityException: Calling from not trusted UID!
>         at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:541)
>         at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:445)
>         at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
>         at android.os.Binder.execTransactInternal(Binder.java:1021)
>         at android.os.Binder.execTransact(Binder.java:994)
> 2021-03-03 15:41:14.482 13707-13707/? D/AndroidRuntime: Shutting down VM

This looks like an internal Android issue. I don't think we could do much about it. Try to restart the device.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
