### ISSUE TITLE
Appium 1.21.0-beta.0: Cant build WDA

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#15157]
## The problem

```
xxx:appium-webdriveragent xxx$ mkdir -p Resources/WebDriverAgent.bundle
xxx:appium-webdriveragent xxx$ ./Scripts/bootstrap.sh -d
-bash: ./Scripts/bootstrap.sh: No such file or directory
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21 beta
* Last Appium version that did not exhibit the issue (if applicable): 1.20.2
* Desktop OS/version used to run Appium: macOS

Doc:
 http://appium.io/docs/en/drivers/ios-xcuitest-real-devices/

**Comment by mykola-mokhnach** [comment]
This documentation is out of date. The bootstrapping script has recently been removed from WDA as obsolete, since all dependencies are now included directly into its source.

**Comment by mykola-mokhnach** [comment]
Linking https://github.com/appium/appium/pull/15158

**Comment by mykola-mokhnach** [comment]
The documentation has been updated. Thanks @KazuCocoa
