### ISSUE TITLE
Services to be available timeout

### ISSUE THREAD

**Issue by tranduyminh91** [appium/appium#15152]
## The problem

I got appium log:
```
[debug] �[35m[UiAutomator2]�[39m Waiting up to 30000ms for services to be available
```
I need increase this timeout, I tried everytimeout that I know but not successful. Please help

## Environment

* Appium version: 1.20.2
* Desktop OS/version used to run Appium: Window 10
* Mobile platform/version under test: Amdrpod
* Real device or emulator/simulator: Real

**Comment by KazuCocoa** [comment]
Please attach the full Appium server log as GIST to see your environment condition.
logcat also may help.

**Comment by tranduyminh91** [comment]
hi @KazuCocoa,
This is appium log 
[appium-server-logs.txt](https://github.com/appium/appium/files/6074357/appium-server-logs.txt)

Thanks,
Minh

**Comment by mykola-mokhnach** [comment]
I don't observe any errors in the log above. Also, it looks like the device under test is very slow.

**Comment by tranduyminh91** [comment]
Hi @KazuCocoa,

I just update log please check it again

Thanks,
Minh

**Comment by tranduyminh91** [comment]
> I don't observe any errors in the log above. Also, it looks like the device under test is very slow.

I am running on cloud that why I am try to increase all timeout. There is only one timeout that I cant increase that is "Waiting up to 30000ms for services to be available"

**Comment by mykola-mokhnach** [comment]
This timeout is hardcoded and cannot be changed via capabilities:

https://github.com/appium/appium-uiautomator2-driver/blob/6121e34a4f3ce3f6e100b609a6bfe8d55601c9b0/lib/uiautomator2.js#L15

**Comment by tranduyminh91** [comment]
> This timeout is hardcoded and cannot be changed via capabilities:
> 
> https://github.com/appium/appium-uiautomator2-driver/blob/6121e34a4f3ce3f6e100b609a6bfe8d55601c9b0/lib/uiautomator2.js#L15

Thank you so much
