### ISSUE TITLE
A popup message appears on xcode 'iPhone has denied the launch request'

### ISSUE THREAD

**Issue by yasmeenkhan** [appium/appium#15153]
**The Problem**

**We have renewed our apple account recently.** After that, whenever I try to launch the WebDriverAgent runner on my iPhone, i am getting the error popup iPhone has denied the launch request. The details just show the cause as Unspecified

<img width="533" alt="Screenshot 2021-02-26 at 5 46 07 PM" src="https://user-images.githubusercontent.com/41662899/109762340-6e80ed80-7c16-11eb-851c-1c9e7eabbaea.png">

<img width="564" alt="PopupDetails" src="https://user-images.githubusercontent.com/41662899/109762455-9e2ff580-7c16-11eb-9614-3100230b8a6e.png">

**Environment**
Appium : 1.20.2 (getting this error on 1.19 and 1.18 as well)
OS: 10.14.6 and 10.15.7
Node: v14.8.0
NPM: 6.14.7
Mobile: OS-13.3; 13.1; 14.2 (iPhone 7+; iPhone 12; iPhoneX)
Xcode: 11.3; 12.2

**Description**
Once the account was renewed, we build repair the certificate and build the project, and the build is successful. But when we try to test the build on the device, the error pops up. 
When we open the appium desktop app, the following error comes
<img width="868" alt="Screenshot 2021-03-03 at 12 00 33 PM" src="https://user-images.githubusercontent.com/41662899/109763556-3e3a4e80-7c18-11eb-867e-13e1a26ab71c.png">

**Server Logs**
Appium server logs: https://gist.github.com/yasmeenkhan/73b1ab55d410b8a388749a84d52c6c2d

**To reproduce:**
1. Open the webdriveragent project from 
 /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent
2. Enable the Automatic signing
3. Build the project
4. Test the build on a real device

**Comment by mykola-mokhnach** [comment]
Try to get the device logs. Perhaps they have more information. In general it looks like an Apple/signature issue, nothing much we could do there.

**Comment by yasmeenkhan** [comment]
Can you tell me where i can see the device logs. Will xcode logs help?

**Comment by Dan-Maor** [comment]
Can you please try to manually uninstall the old WebDriverAgent from the device and see if it helps?

**Comment by yasmeenkhan** [comment]
> Can you please try to manually uninstall the old WebDriverAgent from the device and see if it helps?

I tried the manual uninstall as well.

> Try to get the device logs. Perhaps they have more information. In general it looks like an Apple/signature issue, nothing much we could do there.

The keychain access has older certificates as well, which were causing a conflict. We removed the older certificates. 
https://developer.apple.com/support/expiration/
we added trust certificates manually. and then the issue was resolved
