### ISSUE TITLE
Android pushFile to app data directory doesn't work when pushing to an existing subdirectory

### ISSUE THREAD

**Issue by luser** [appium/appium#15156]
## The problem

#6692, implemented in https://github.com/appium/appium-android-driver/pull/288, added support for `pushFile` to push to the app data directory on Android for apps marked as `debuggable`. I attempted to use this in a test harness and got an error:

```
unknown error: An unknown server-side error occurred while processing the command. Original error: Cannot access the container of 'com.fullstory.reftest' application. Is the application installed and has 'debuggable' build option set to true? Original error: Error executing adbExec. Original error: 'Command '/Users/ted/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell cp -f /data/local/tmp/com.fullstory.reftest.FS_PREFS.xml /data/data/com.fullstory.reftest/shared_prefs/com.fullstory.reftest.FS_PREFS.xml' exited with code 1'; Stderr: 'cp: /data/data/com.fullstory.reftest/shared_prefs/com.fullstory.reftest.FS_PREFS.xml: Permission denied'; Code: '1'
```

I had previously run the app on this emulator, so that file already exists. Inspecting the file and directory permissions in an `adb shell`, you can see that while the file itself is world-writable, its parent directory is not:

```
generic_x86:/ $ run-as com.fullstory.reftest ls -l /data/data/com.fullstory.reftest/shared_prefs/com.fullstory.reftest/shared_prefs/com.fullstory.reftest.FS_PREFS.xml
-rwxrwxrwx 1 u0_a143 u0_a143 109 2021-03-03 07:44 /data/data/com.fullstory.reftest/shared_prefs/com.fullstory.reftest.FS_PREFS.xml
generic_x86:/ $ run-as com.fullstory.reftest ls -ld /data/data/com.fullstory.reftest/shared_prefs/
drwxrwx--x 2 u0_a143 u0_a143 4096 2021-02-19 11:46 /data/data/com.fullstory.reftest/shared_prefs/
```

The implementation of `pushFile` uses `run-as` to run `mkdir` and `touch`, but not for the `cp` of the file itself:
https://github.com/appium/appium-android-driver/blob/d3ce41fdda0a710970391887dc3e9606487bad91/lib/commands/file-actions.js#L124

Manually using `run-as` to copy the file to the final destination seems to work:

```
generic_x86:/ $ run-as com.fullstory.reftest cp /data/local/tmp/com.fullstory.reftest.FS_PREFS.xml /data/data/com.fullstory.reftest/shared_prefs/com.fullstory.reftest.FS_PREFS.xml
generic_x86:/ $
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.1
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: macOS 10.15.7
* Node.js version (unless using Appium.app|exe): v14.13.1
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Android 10
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/luser/a5838d5b6199e3b4b75355ab77d34f90

## Code To Reproduce Issue [ Good To Have ]

Pretty straightforward, but the situation only arises if the app has previously created the directory. In this case, the app uses `SharedPreferences` to save some preferences, which creates a file under the `shared_prefs` directory.

```typescript
import { remote as wdio } from "webdriverio";

let driver = await wdio({
      platformName: 'Android',
      platformVersion: '10.0',
      automationName: 'UiAutomator2',
      enforceAppInstall: true,
      'appium:autoLaunch': false,
      app: '...',
    };
const pkg = 'com.fullstory.reftest';
await driver.pushFile(`@${pkg}/shared_prefs/${pkg}.FS_PREFS.xml`, 'some data');
```

**Comment by mykola-mokhnach** [comment]
Thanks for the detailed report @luser 
https://github.com/appium/appium-android-driver/pull/680 should address that
