### ISSUE TITLE
PWA App test automation using Appium & Webdriver IO throws error after the app is launched

### ISSUE THREAD

**Issue by manish2788** [appium/appium#15151]
## The problem

While testing a PWA app over Android device using Appium and WebdriverIO (JavaScript), the app is being launched by appium however after few seconds appium throws an error as shown below in logs while launching the subsequent activities.
No issue is observed with a native app though.

## Environment

* Appium version (or git revision) that exhibits the issue: **1.17**
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: **MacOS Catalina 10.15.7**
* Node.js version (unless using Appium.app|exe): **11.13.0**
* Npm or Yarn package manager: **NPM**
* Mobile platform/version under test: **Android 6**
* Real device or emulator/simulator: **Real Device**
* Appium CLI or Appium.app|exe: **Appium CLI**

## Details

Configured the appium with desired capabilities for android, Connected a real android device and started the appium server through CLI. The PWA app package is installed by the appium, app is also launched on device however after sometime appium errors out with following log which seems to be related to Android app activities.
This issue is not observed for a native app rather only for PWA app. Any limitation of Appium with PWA app automation?

## Link to Appium logs
Error Log:

[debug] [W3C] Encountered internal error running command: Error: Cannot start the 'org.chromium.webapk.a579627b86fb57924_v2' application. 
Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. 

Original error: Error executing adbExec. 
**Original error: 'Command '/Users/xyz/Library/Android/sdk/platform-tools/adb -P 5037 -s 1f7734e87d53 shell am start -W -n org.chromium.webapk.a579627b86fb57924_v2/org.chromium.webapk.shell_apk.MainActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER** -f 0x10200000' timed out after 20000ms’. 
Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout’ capability

[debug] [W3C]     at ADB.startApp (xyz/node_modules/appium/node_modules/appium-adb/lib/tools/apk-utils.js:165:11)

## Code To Reproduce Issue 

```
const opts = {
    path: '/wd/hub',
    port: 4723,
    capabilities: {
      platformName: "Android",
      platformVersion: "6",
      deviceName: "Pixel 3",
      automationName: "Appium",
      app: "~/Desktop/pwa.apk"
    }
  };
  
  async function main () {
    const client = await wdio.remote(opts);
  }
  
  main();

```

**Comment by mykola-mokhnach** [comment]
The error is returned by adb itself, it has nothing to do with Appium. Please update Appium to the most recent version and try apply the troubleshooting link

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by AparnaM-QA** [comment]
Hi i am facing the same issue with PWA application, i am sure this error is not related to adb. i have never used adb here getting the app package and activity from apk info app and in this way i used to test native application which never fails. can someone kindly help me on this
