### ISSUE TITLE
Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started

### ISSUE THREAD

**Issue by harshcse-089** [appium/appium#15163]
## The problem

The appium fails with the error "Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started" everytime when the appium tries to perform an action on the app.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2 (Latest)
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Ubuntu 20.04 LTS
* Node.js version (unless using Appium.app|exe): 
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: Android Q
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [Appium Logs](https://gist.github.com/harshcse-089/2821179a6a7fa0eb7c8a787d04fae522)

**Comment by mykola-mokhnach** [comment]
Make sure you properly close previous sessions before starting new ones or enable `--session-override` mode if no parallel sessions are running

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by M1qa** [comment]
＠mykola-mokhnach
I have the same problem. I set enable --session-override and set the newCommandTimeout,but it's not used.How can I fixed it?


Appium logs：
[Appium] Welcome to Appium v1.22.3
[Appium] Non-default server args:
[Appium]   port: 4729
[Appium]   sessionOverride: true
[Appium]   relaxedSecurityEnabled: true
[Appium] Appium REST http interface listener started on 0.0.0.0:4729
[HTTP] --> POST /wd/hub/session/cee7c36d-17aa-4d2d-9dac-ca2e317de69b/element
[HTTP] {"using":"accessibility id","value":"MainScreenFrame","sessionId":"cee7c36d-17aa-4d2d-9dac-ca2e317de69b"}
[debug] [GENERIC (cee7c36d)] Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started
[debug] [GENERIC (cee7c36d)]     at asyncHandler (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:243:15)
[debug] [GENERIC (cee7c36d)]     at c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:423:15
[debug] [GENERIC (cee7c36d)]     at Layer.handle [as handle_request] (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
[debug] [GENERIC (cee7c36d)]     at next (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\route.js:137:13)
[debug] [GENERIC (cee7c36d)]     at Route.dispatch (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\route.js:112:3)
[debug] [GENERIC (cee7c36d)]     at Layer.handle [as handle_request] (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
[debug] [GENERIC (cee7c36d)]     at c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:281:22
[debug] [GENERIC (cee7c36d)]     at param (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:354:14)
[debug] [GENERIC (cee7c36d)]     at param (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:365:14)
[debug] [GENERIC (cee7c36d)]     at Function.process_params (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:410:3)
[debug] [GENERIC (cee7c36d)]     at next (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:275:10)
[debug] [GENERIC (cee7c36d)]     at logger (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\morgan\index.js:144:5)
[debug] [GENERIC (cee7c36d)]     at Layer.handle [as handle_request] (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
[debug] [GENERIC (cee7c36d)]     at trim_prefix (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:317:13)
[debug] [GENERIC (cee7c36d)]     at c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:284:7
[debug] [GENERIC (cee7c36d)]     at Function.process_params (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:335:12)
[HTTP] <-- POST /wd/hub/session/cee7c36d-17aa-4d2d-9dac-ca2e317de69b/element 404 42 ms - 2666
[HTTP]
[HTTP] --> GET /wd/hub/session/cee7c36d-17aa-4d2d-9dac-ca2e317de69b/screenshot
[HTTP] {}
[debug] [GENERIC (cee7c36d)] Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started
[debug] [GENERIC (cee7c36d)]     at asyncHandler (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:243:15)
[debug] [GENERIC (cee7c36d)]     at c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:423:15
[debug] [GENERIC (cee7c36d)]     at Layer.handle [as handle_request] (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
[debug] [GENERIC (cee7c36d)]     at next (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\route.js:137:13)
[debug] [GENERIC (cee7c36d)]     at Route.dispatch (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\route.js:112:3)
[debug] [GENERIC (cee7c36d)]     at Layer.handle [as handle_request] (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
[debug] [GENERIC (cee7c36d)]     at c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:281:22
[debug] [GENERIC (cee7c36d)]     at param (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:354:14)
[debug] [GENERIC (cee7c36d)]     at param (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:365:14)
[debug] [GENERIC (cee7c36d)]     at Function.process_params (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:410:3)
[debug] [GENERIC (cee7c36d)]     at next (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:275:10)
[debug] [GENERIC (cee7c36d)]     at logger (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\morgan\index.js:144:5)
[debug] [GENERIC (cee7c36d)]     at Layer.handle [as handle_request] (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
[debug] [GENERIC (cee7c36d)]     at trim_prefix (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:317:13)
[debug] [GENERIC (cee7c36d)]     at c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:284:7
[debug] [GENERIC (cee7c36d)]     at Function.process_params (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:335:12)
[HTTP] <-- GET /wd/hub/session/cee7c36d-17aa-4d2d-9dac-ca2e317de69b/screenshot 404 16 ms - 2666
[HTTP]
[HTTP] --> POST /wd/hub/session/cee7c36d-17aa-4d2d-9dac-ca2e317de69b/element
[HTTP] {"using":"accessibility id","value":"MainScreenFrame","sessionId":"cee7c36d-17aa-4d2d-9dac-ca2e317de69b"}
[debug] [GENERIC (cee7c36d)] Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started
[debug] [GENERIC (cee7c36d)]     at asyncHandler (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:243:15)
[debug] [GENERIC (cee7c36d)]     at c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:423:15
[debug] [GENERIC (cee7c36d)]     at Layer.handle [as handle_request] (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
[debug] [GENERIC (cee7c36d)]     at next (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\route.js:137:13)
[debug] [GENERIC (cee7c36d)]     at Route.dispatch (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\route.js:112:3)
[debug] [GENERIC (cee7c36d)]     at Layer.handle [as handle_request] (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
[debug] [GENERIC (cee7c36d)]     at c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:281:22
[debug] [GENERIC (cee7c36d)]     at param (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:354:14)
[debug] [GENERIC (cee7c36d)]     at param (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:365:14)
[debug] [GENERIC (cee7c36d)]     at Function.process_params (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:410:3)
[debug] [GENERIC (cee7c36d)]     at next (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:275:10)
[debug] [GENERIC (cee7c36d)]     at logger (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\morgan\index.js:144:5)
[debug] [GENERIC (cee7c36d)]     at Layer.handle [as handle_request] (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
[debug] [GENERIC (cee7c36d)]     at trim_prefix (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:317:13)
[debug] [GENERIC (cee7c36d)]     at c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:284:7
[debug] [GENERIC (cee7c36d)]     at Function.process_params (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:335:12)
[HTTP] <-- POST /wd/hub/session/cee7c36d-17aa-4d2d-9dac-ca2e317de69b/element 404 5 ms - 2666
[HTTP]
[HTTP] --> DELETE /wd/hub/session/cee7c36d-17aa-4d2d-9dac-ca2e317de69b
[HTTP] {}
[debug] [GENERIC (cee7c36d)] Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started
[debug] [GENERIC (cee7c36d)]     at asyncHandler (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:243:15)
[debug] [GENERIC (cee7c36d)]     at c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:423:15
[debug] [GENERIC (cee7c36d)]     at Layer.handle [as handle_request] (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
[debug] [GENERIC (cee7c36d)]     at next (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\route.js:137:13)
[debug] [GENERIC (cee7c36d)]     at Route.dispatch (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\route.js:112:3)
[debug] [GENERIC (cee7c36d)]     at Layer.handle [as handle_request] (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
[debug] [GENERIC (cee7c36d)]     at c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:281:22
[debug] [GENERIC (cee7c36d)]     at param (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:354:14)
[debug] [GENERIC (cee7c36d)]     at param (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:365:14)
[debug] [GENERIC (cee7c36d)]     at Function.process_params (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:410:3)
[debug] [GENERIC (cee7c36d)]     at next (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:275:10)
[debug] [GENERIC (cee7c36d)]     at logger (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\morgan\index.js:144:5)
[debug] [GENERIC (cee7c36d)]     at Layer.handle [as handle_request] (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
[debug] [GENERIC (cee7c36d)]     at trim_prefix (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:317:13)
[debug] [GENERIC (cee7c36d)]     at c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:284:7
[debug] [GENERIC (cee7c36d)]     at Function.process_params (c:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:335:12)
[HTTP] <-- DELETE /wd/hub/session/cee7c36d-17aa-4d2d-9dac-ca2e317de69b 404 6 ms - 2666
[HTTP]
[debug] [HTTP] Request idempotency key: b063d003-90fe-4710-9aec-3a44cebb682e
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"platformName":"Windows","deviceName":"WindowsPC","app":"Root","newCommandTimeout":600}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"Windows","deviceName":"WindowsPC","app":"Root","newCommandTimeout":600},null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1672804914004 (12:01:54 GMT+0800 (中国标准时间))
[Appium] Appium v1.22.3 creating new WindowsDriver (v1.19.1) session
[debug] [Appium] There are no active sessions for cleanup
[Appium] Applying relaxed security to 'WindowsDriver' as per server command line argument. All insecure features will be enabled unless explicitly disabled by --deny-insecure
[debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {
[debug] [BaseDriver]   "platformName": "Windows",
[debug] [BaseDriver]   "deviceName": "WindowsPC",
[debug] [BaseDriver]   "app": "Root",
[debug] [BaseDriver]   "newCommandTimeout": 600
[debug] [BaseDriver] }
[BaseDriver] Session created with session id: 98349a5d-9a1d-4508-a81e-ff9450ea9acd
[WinAppDriver] WinAppDriver exists, but the checksum did not match. Was it replaced manually?
[WinAppDriver] Spawning 'C:\Program Files (x86)\Windows Application Driver\WinAppDriver.exe' with args: ["4724/wd/hub"]
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:4724/wd/hub/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:4724
[debug] [WinAppDriver] Windows Application Driver listening for requests at: http://127.0.0.1:4724/wd/hub
[debug] [WinAppDriver] Press ENTER to exit.
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:4724/wd/hub/status] with no body
[debug] [WinAppDriver] ==========================================
[debug] [WinAppDriver] GET /wd/hub/status HTTP/1.1
[debug] [WinAppDriver] Accept: application/json, */*
[debug] [WinAppDriver] Connection: keep-alive
[debug] [WinAppDriver] Content-Type: application/json; charset=utf-8
[debug] [WinAppDriver] Host: 127.0.0.1:4724
[debug] [WinAppDriver] User-Agent: appium
[debug] [WD Proxy] Got response with status 200: {"build":{"revision":"2003","time":"Wed Aug 26 07:56:06 2020","version":"1.2.2009"},"os":{"arch":"amd64","name":"windows","version":"10.0.19044"}}
[debug] [WinAppDriver] Starting WinAppDriver session. Will timeout in '20000' ms.
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:4724/wd/hub/session] with body: {"desiredCapabilities":{"platformName":"Windows","deviceName":"WindowsPC","app":"Root","newCommandTimeout":600}}
[debug] [WinAppDriver] HTTP/1.1 200 OK
[debug] [WinAppDriver] Content-Length: 146
[debug] [WinAppDriver] Content-Type: application/json
[debug] [WinAppDriver] ==========================================
[debug] [WinAppDriver] POST /wd/hub/session HTTP/1.1
[debug] [WinAppDriver] Accept: application/json, */*
[debug] [WinAppDriver] Connection: keep-alive
[debug] [WinAppDriver] Content-Length: 112
[debug] [WinAppDriver] Content-Type: application/json; charset=utf-8
[debug] [WinAppDriver] Host: 127.0.0.1:4724
[debug] [WinAppDriver] User-Agent: appium
[debug] [WinAppDriver] HTTP/1.1 200 OK
[debug] [WinAppDriver] Content-Length: 111
[debug] [WinAppDriver] Content-Type: application/json
[debug] [WinAppDriver]
[debug] [WinAppDriver] {"sessionId":"CD52309F-D02A-4DD9-8F61-2B25627A6F0A","status":0,"value":{"app":"Root","platformName":"Windows"}}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"CD52309F-D02A-4DD9-8F61-2B25627A6F0A","status":0,"value":{"app":"Root","platformName":"Windows"}}
[WD Proxy] Determined the downstream protocol as 'MJSONWP'
[Appium] New WindowsDriver session created successfully, session 98349a5d-9a1d-4508-a81e-ff9450ea9acd added to master session list
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1672804915706 (12:01:55 GMT+0800 (中国标准时间))
[debug] [MJSONWP (98349a5d)] Cached the protocol value 'MJSONWP' for the new session 98349a5d-9a1d-4508-a81e-ff9450ea9acd
[debug] [MJSONWP (98349a5d)] Responding to client with driver.createSession() result: {"platformName":"Windows","deviceName":"WindowsPC","app":"Root","newCommandTimeout":600}
[HTTP] <-- POST /wd/hub/session 200 1705 ms - 160
[HTTP]
[HTTP] --> POST /wd/hub/session/98349a5d-9a1d-4508-a81e-ff9450ea9acd/execute
[HTTP] {"script":"powerShell","args":[{"command":"Get-Process -Name \"bizcloudroom\" | Format-list -Property ProductVersion"}],"sessionId":"98349a5d-9a1d-4508-a81e-ff9450ea9acd"}
[debug] [MJSONWP (98349a5d)] Calling AppiumDriver.execute() with args: ["powerShell",[{"command":"Get-Process -Name \"bizcloudroom\" | Format-list -Property ProductVersion"}],"98349a5d-9a1d-4508-a81e-ff9450ea9acd"]
[WinAppDriver] Running Power Shell with arguments: -command,Get-Process -Name "bizcloudroom" | Format-list -Property ProductVersion
[debug] [MJSONWP (98349a5d)] Responding to client with driver.execute() result: "\r\n\r\nProductVersion : 3.2.4.55\r\n\r\n\r\n\r\n"
[HTTP] <-- POST /wd/hub/session/98349a5d-9a1d-4508-a81e-ff9450ea9acd/execute 200 599 ms - 123
[HTTP]
[HTTP] --> DELETE /wd/hub/session/98349a5d-9a1d-4508-a81e-ff9450ea9acd
[HTTP] {}
[debug] [MJSONWP (98349a5d)] Calling AppiumDriver.deleteSession() with args: ["98349a5d-9a1d-4508-a81e-ff9450ea9acd"]
[debug] [BaseDriver] Event 'quitSessionRequested' logged at 1672804916316 (12:01:56 GMT+0800 (中国标准时间))
[Appium] Removing session 98349a5d-9a1d-4508-a81e-ff9450ea9acd from our master session list
[debug] [WinAppDriver] Deleting WinAppDriver session
[debug] [WinAppDriver] Deleting WinAppDriver server session
[debug] [WD Proxy] Matched '/session/CD52309F-D02A-4DD9-8F61-2B25627A6F0A' to command name 'deleteSession'
[debug] [WD Proxy] Proxying [DELETE /session/CD52309F-D02A-4DD9-8F61-2B25627A6F0A] to [DELETE http://127.0.0.1:4724/wd/hub/session/CD52309F-D02A-4DD9-8F61-2B25627A6F0A] with no body
[debug] [WinAppDriver] ==========================================
[debug] [WinAppDriver] DELETE /wd/hub/session/CD52309F-D02A-4DD9-8F61-2B25627A6F0A HTTP/1.1
[debug] [WinAppDriver] Accept: application/json, */*
[debug] [WinAppDriver] Connection: keep-alive
[debug] [WinAppDriver] Content-Type: application/json; charset=utf-8
[debug] [WinAppDriver] Host: 127.0.0.1:4724
[debug] [WinAppDriver] User-Agent: appium
[debug] [WD Proxy] Got response with status 200: {"status":0}
[debug] [WinAppDriver] HTTP/1.1 200 OK
[debug] [WinAppDriver] Content-Length: 12
[debug] [WinAppDriver] Content-Type: application/json
[debug] [WinAppDriver]
[debug] [WinAppDriver] {"status":0}
[WinAppDriver] WinAppDriver exited with code null, signal SIGTERM
[debug] [BaseDriver] Event 'quitSessionFinished' logged at 1672804916354 (12:01:56 GMT+0800 (中国标准时间))
[debug] [MJSONWP (98349a5d)] Received response: null
[debug] [MJSONWP (98349a5d)] But deleting session, so not returning
[debug] [MJSONWP (98349a5d)] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/98349a5d-9a1d-4508-a81e-ff9450ea9acd 200 40 ms - 76
[HTTP]

**Comment by M1qa** [comment]
@mykola-mokhnach can you help me?

**Comment by jlipps** [comment]
@M1qa you are doing something strange with your client code. The first command the server receives is a request to find an element, but a session is not active. You must first start a session
