### ISSUE TITLE
[Android] How to get view from floating window: WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY

### ISSUE THREAD

**Issue by jackyxiao126** [appium/appium#15161]
## The problem

I can't get the view from page source via Appium Desktop and UIAutomator. 
There is a floating window: WindowManager.LayoutParams.**TYPE_APPLICATION_OVERLAY**
Is there any settings need to be added in App code in order to get elements?

**Comment by mykola-mokhnach** [comment]
You could try to enable enableMultiWindows [setting](https://github.com/appium/appium-uiautomator2-driver#settings-api)

Please use Appium forum for questions
