### ISSUE TITLE
Screenshot of the entire height not just the view port

### ISSUE THREAD

**Issue by gruckionvit** [appium/appium#15176]
## The problem

I want to take a picture of the entire height of the currently display content not just the content visible in the view port. Example attached.

![screenshotflow com_(iPhone X) (1)](https://user-images.githubusercontent.com/67283459/110488219-2ebe7800-80e6-11eb-8769-3c49db26f1e0.png)

## Environment

* Appium version (or git revision) that exhibits the issue: N/A
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: N/A
* Node.js version (unless using Appium.app|exe): N/A
* Npm or Yarn package manager: N/A
* Mobile platform/version under test: N/A
* Real device or emulator/simulator: N/A
* Appium CLI or Appium.app|exe: N/A

## Details

 N/A

## Link to Appium logs

 N/A

## Code To Reproduce Issue [ Good To Have ]

 http://appium.io/docs/en/commands/session/screenshot/
 
 API only supports screenshot of viewport?

**Comment by mykola-mokhnach** [comment]
Unfortunately XCTest does not provide any APIs which would support that. Please let us know if you find one.

**Comment by gruckionvit** [comment]
Will let you know what I come up with. I am looking for react-native libraries that can capture a screenshot of the entire scroll view. Then trigger it "somehow" as part of our automation pipeline.
