### ISSUE TITLE
[IOS] RunAppInBackground is not working stable on ios 14.4 (Appium v1.20.2)

### ISSUE THREAD

**Issue by lilyushchenko** [appium/appium#15175]
## The problem
We encountered long response for Appium server when trying to background/foreground application, usually it happens after second launch of app.

## Environment

* Appium version (or git revision) that exhibits the issue:  Appium v1.20.2
* Last Appium version that did not exhibit the issue:  Appium v1.20.1 (more precisely, we did not encounter this problem on ios v14.2)
* Desktop OS/version used to run Appium: MacOS Catalina 10.15.4
* Node.js version (unless using Appium.app|exe): v10.16.0
* Mobile platform/version under test: iOS 14.4
* Real device or emulator/simulator: real device

## Details

Test steps:
1) Launch the app
2) Enter the main screen
3) Backgrounding for 7 seconds (using driver.runAppInBackground(Duration.ofSeconds(7));
4) calling driver.activateApp(appPackageName) to foreground on opened screen
-> Expected result: app foregrounds after 7 seconds.
-> Actual result: app foregrounds after 60+ seconds.

We did not encounter this problem on ios v14.2, this issue appeared after upgrading our devices to v14.4.

## Link to Appium logs

https://gist.github.com/lilyushchenko/07e86071774d67dffb3ad6a61fd0fb06

## Code To Reproduce Issue [ Good To Have ]

driver.runAppInBackground(Duration.ofSeconds(7));
<img width="1067" alt="Screen Shot 2021-03-09 at 14 08 46" src="https://user-images.githubusercontent.com/46952839/110472318-4699fa00-80ee-11eb-99c0-5043ec1ab2eb.png">

**Comment by mykola-mokhnach** [comment]
This looks like XCTest issue. Please provide logs with device and xcodebuild logging enabled

**Comment by lilyushchenko** [comment]
hello @mykola-mokhnach 
this is the log with xcodebuild logging enabled: https://gist.github.com/lilyushchenko/97f6fde950e0a91e7c84d3a7f1be59a4

**Comment by mykola-mokhnach** [comment]
I have reenabled the backgrounding test at https://github.com/appium/WebDriverAgent/pull/476 and it does pass for me with Xcode 12.5-beta2 on simulator. 

I can observe that the delay happens while checking the idling state of the springboard app. Perhaps changing `waitForIdleTimeout`/`animationCoolOffTimeout` setting values might help to influence that behaviour

**Comment by lilyushchenko** [comment]
only setting       
  ```
iosDriver.setSetting(Setting.WAIT_FOR_IDLE_TIMEOUT, 0);
iosDriver.setSetting("animationCoolOffTimeout", 0);
```
takes some difference and works, but this is not good practice according to https://github.com/appium/appium-xcuitest-driver#settings-api and may affect other tests i guess

**Comment by mykola-mokhnach** [comment]
You could set the idle timeout only for the part of code where backgroundApp is called and then restore it to the default value

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/WebDriverAgent/pull/477 could also improve the behaviour there

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
