### ISSUE TITLE
In Android Wild characters are not working like //*[@*='SomeText']" since 1.19.0

### ISSUE THREAD

**Issue by yadavsvmx** [appium/appium#15179]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

In Android Wild characters are not working like `//*[@*='SomeText']` in 1.20.2 version
If i use `//*[@content-desc='SomeText']` it is working as expected.
The issue seems to be specific to `@*` wild card format which used to work well prior to 1.20 versions like 1.18.3.

You can try any app and try to find any element in the format `//*[@*='SomeText']` and see that it works in 1.18.3, but does not work with 1.20 versions

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [x ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by mykola-mokhnach** [comment]
Please provide the server and logcat logs

**Comment by yadavsvmx** [comment]
[1.20.2 Android wild card issue logcat.txt](https://github.com/appium/appium/files/6115929/1.20.2.Android.wild.card.issue.logcat.txt)
[1.20.2 Android wild card issueappium-server-logs.txt](https://github.com/appium/appium/files/6115930/1.20.2.Android.wild.card.issueappium-server-logs.txt)

Attaching logs:
xpath = `//*[@*='More']`

**Comment by mykola-mokhnach** [comment]
The fix has been published to appium@beta

**Comment by yadavsvmx** [comment]
@mykola-mokhnach Thanks for the quick fix.
When will this be available in Appium Desktop

**Comment by KazuCocoa** [comment]
It hasn't decided yet.
You will be able to try it out as https://github.com/appium/appium-desktop#connect-to-local-appium-server if you'd like to use the inspector.
