### ISSUE TITLE
[MJSONWP] Encountered internal error running command: Error: Cannot verify the signature when starting inspector/Start Session

### ISSUE THREAD

**Issue by ManthiraMani** [appium/appium#15172]
## The problem

Encountered internal error running command: Error: Cannot verify the signature of 'C:\Users\Salai\AppData\Local\Temp\202129-6344-7pp1iu.ujwxe\appium-uiautomator2-server-v4.17.4.apk'. Original error: Could not find 'apksigner.jar' in ["D:\\Appium_Setup\\tools\\bin\\platform-tools\\platform-tools\\apksigner.jar","D:\\Appium_Setup\\tools\\bin\\platform-tools\\emulator\\apksigner.jar","D:\\Appium_Setup\\tools\\bin\\platform-tools\\cmdline-tools\\latest\\bin\\apksigner.jar","D:\\Appium_Setup\\tools\\bin\\platform-tools\\tools\\apksigner.jar","D:\\Appium_Setup\\tools\\bin\\platform-tools\\tools\\bin\\apksigner.jar","D:\\Appium_Setup\\tools\\bin\\platform-tools\\apksigner.jar"]. Do you have Android Build Tools installed at 'D:\Appium_Setup\tools\bin\platform-tools'?
## Environment
* Appium version (1.20.2) that exhibits the issue:
* Desktop OS/version used to run Appium: Windows 10
* Node version : v14.15.4
* jdk version: 1.8.0_261

## Details
Set Desired Capabalites as follows
{
  "platformName": "Android",
  "androidVersion": "9 PKQ 1.180904.001",
  "deviceName": "Redmi Note 5 Pro",
  "udid": "8b3090af",
  "appPackage": "Provide your app package",
  "appActivity": "Provide your app package"
}

## Link to Appium logs
 https://gist.github.com/ManthiraMani/9a00e06f5bb79fe8b5728f349e2eaa44
## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by KazuCocoa** [comment]
Where did you install Android build tools?

**Comment by ManthiraMani** [comment]
I have used android command line tools alone from this link https://dl.google.com/android/repository/commandlinetools-win-6858069_latest.zip and I have placed in D:\Appium_Setup\tools\bin\platform-tools

**Comment by KazuCocoa** [comment]
Then, can you find `apksigner` in `ndroid_sdk/build-tools/version/` as `Android SDK Build Tools` https://developer.android.com/studio/command-line/ ?
Potentially you should install it via sdkmanager.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
