### ISSUE TITLE
Appium gets wrong screen size of Google Pixel 4/Android 10

### ISSUE THREAD

**Issue by wjnter** [appium/appium#15177]
## The problem
The actual resolution is 1080x2280 but the bounds that appium returns [0,0][1080,1977]
So that, all elements out of 1080x1977 won't be interacted.
See the image for more info
![image](https://user-images.githubusercontent.com/45412202/110567051-79420200-8183-11eb-8c98-9c942fe3da99.png)
Once I interact to tab icons in bottom, I get error like 
`Coordinate [x=231.5, y=2079.5] is outside of element rect: [0,0][1080,1977]`

## Environment

* Appium version: 1.20.2
* Desktop OS/version used to run Appium: Windows 10
* Mobile platform/version under test: Android 10
* Real device or emulator/simulator: Emulator Google pixel 4

**Comment by mykola-mokhnach** [comment]
These dimensions are returned by UiAutomator framework itself. Unfortunately, there is nothing we could do there. Please report the issue to Google.

**Comment by leonardonelson91** [comment]
@wjnter did you manage to solve the issue?
