### ISSUE TITLE
Unable to perform Keyboard actions in iOS(Appium) using Selenium Java

### ISSUE THREAD

**Issue by saipriyanka975** [appium/appium#15178]
## The problem

We have a scenario to clear an input field in iOS. When clear method is used, the method is getting passed but the action is not getting performed. We have tried using Keys.CONTROL,"a", Keys.DELETE methods where for Keys.CONTROL,"a", **a** is getting entered into the input field instead of selecting the entire text and also Keys.DELETE is not deleting value entered. 

## Environment

* Appium version (or git revision) that exhibits the issue: All
* Last Appium version that did not exhibit the issue (if applicable): All iOS versions
* Desktop OS/version used to run Appium: Mac OS 11.0
* Mobile platform/version under test: iOS version 14.3
* Real device or emulator/simulator: Simulator

## Code To Reproduce Issue [ Good To Have ]

Please take any input field and try clearing the field using Keys.CONTROL,"a" and Keys.DELETE methods
driver.findElementById('q').sendKeys("Test");
driver.findElementById('q').sendKeys(Keys.CONTROL,"a");
driver.findElementById('q').sendKeys(Keys.DELETE);

We have also tried using the below code to clear the field but no luck
driver.findElementById('q').sendKeys(Keys.chord(Keys.CONTROL, “a”), Keys.DELETE));

**Comment by mykola-mokhnach** [comment]
Unfortunately iOS does not support sending keys. You could try to tripple tap the input field as a workaround to select the text there. 

Closed as not an issue
