### ISSUE TITLE
[IOS] Appium server crashing when idling (connected to a selenium grid) 

### ISSUE THREAD

**Issue by Jiurong-Yang** [appium/appium#15171]
## The problem

Appium (IOS) seems to be hard crashing when idling and is connected to a selenium grid

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2
* Desktop OS/version used to run Appium:  Mac OS 10.15.7
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Periodically it seems something happens and Appium just throws an uncaughtexception and dies. Even if the server is idle.

## Link to Appium logs
https://gist.github.com/Jiurong-Yang/b51ceda14c6def818a2b20198b0df3ce

As you can see from the log, the server has been idle for over 10 minutes. The only logging message is the periodic (5 seconds) pinging to the grid server. And all of a sudden you get that uncaughtexception and the appium server just dies.

**Comment by mykola-mokhnach** [comment]
https://discuss.appium.io/t/crash-occurred-while-creating-session-in-idempotency-js-of-base-driver/32884/9

Make sure your base driver version is up to date

**Comment by mykola-mokhnach** [comment]
It is always safe to update the base driver unless its major version is changed.
