### ISSUE TITLE
Failed to receive any data within the timeout: 5000

### ISSUE THREAD

**Issue by apulido15** [appium/appium#15187]
## The problem

Hi Everyone, please your help with this

When i try execute my ios automation script, i get the next error

Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Failed to receive any data within the timeout: 5000 Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'

the application doesn't open, immediately i run de script i get this error, i searched this error in the web but i didn't find some solution about this, thanks for your help.

The project was made with Serenity BDD last Release and appium client 7.3.0

## Environment

* Appium Desktop version: 1.18.3
* iOS real device: iPhone X
* Desktop OS/version used to run Appium: Mac Catalina
* Mobile platform/version under test: iOS 13.6

## Link to Appium logs

https://gist.github.com/apulido15/8e1eb43ddfcfc193bed1a82693c803c7

.

**Comment by mykola-mokhnach** [comment]
Try to update your Appium server to the most recent version. The 1.18 one is out of date

**Comment by mykola-mokhnach** [comment]
Closed because of no response
