### ISSUE TITLE
Getting an error as Encountered internal error running command: Error: Appium Settings app is not running after 5000ms

### ISSUE THREAD

**Issue by ManthiraMani** [appium/appium#15180]
## The problem

I have uninstalled the appium debug app by mistake. Is there any way to install it again?

## Environment

* Appium version: 1.20.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

Error: Appium Settings app is not running after 5000ms
[AndroidDriver]     at ADB.requireRunningSettingsApp (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\settings-client-commands.js:70:11)
[UiAutomator2] Deleting UiAutomator2 session
[ADB] Running 'C:\Users\Salai\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 8b3090af shell am force-stop uk.co.lycaremit.lyca_remit'
[UiAutomator2] Restoring hidden api policy to the device default configuration
[ADB] Running 'C:\Users\Salai\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 8b3090af shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''
[BaseDriver] Event 'newSessionStarted' logged at 1615441665737 (11:17:45 GMT+0530 (India Standard Time))
[MJSONWP] Encountered internal error running command: Error: Appium Settings app is not running after 5000ms
[MJSONWP]     at ADB.requireRunningSettingsApp (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\settings-client-commands.js:70:11)
[HTTP] <-- POST /wd/hub/session 500 8625 ms - 184
[HTTP] 

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by KazuCocoa** [comment]
Usually, the apk is installed by appium if no package was in the device under test.
Could you share the full log?

**Comment by ManthiraMani** [comment]
Please find the log 

https://gist.github.com/ManthiraMani/dd07c04f3751697ad80e39edcd250e00

**Comment by ManthiraMani** [comment]
Previously it was installed. But by mistake I have uninstalled the app. After that i am facing this issue.

**Comment by KazuCocoa** [comment]
Hm... the device said the package was in the device. Could you restart the device?

> [debug] [35m[ADB][39m Running 'C:\Users\Salai\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 8b3090af shell dumpsys package io.appium.settings'[debug] [35m[ADB][39m 'io.appium.settings' is installed

**Comment by ManthiraMani** [comment]
After restarting getting the same error

**Comment by KazuCocoa** [comment]
Can you find `io.appium.settings` package name in the device's application list etc?
I don't know well because I haven't used the manufacture's device, but probably the device kept the package somewhere because the device told appium it had `io.appium.settings` v3.2.1 as below.
 
> [debug] [35m[ADB][39m Running 'C:\Users\Salai\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 8b3090af shell dumpsys package io.appium.settings'[debug] [35m[ADB][39m The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('3.2.1' >= '3.2.1')

btw, what result can you get by the below command?

> 'C:\Users\Salai\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 8b3090af shell am start -n io.appium.settings/.Settings -a android.intent.action.MAIN -c android.intent.category.LAUNCHER

**Comment by ManthiraMani** [comment]
I found the apk file in file manager APKs  and installed once again after that it is working fine. Hence it is closed
