### ISSUE TITLE
I need ROOT access 

### ISSUE THREAD

**Issue by tolgatasci** [appium/appium#15182]
## Appium shell root start
Hello, 
When you do this, everything works fine.

`adb root`

When I restart, root permission goes away. Can Appium send this command for me?

like this 

`self.driver.execute_script('mobile: root', {})`

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: 9
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
what exactly you are trying to achieve there? calling `adb root` usually reconnects the server, which might affect other parallel sessions. Much safer way of doing stuff is to use sudo/su

**Comment by tolgatasci** [comment]
su am start -a android.intent.action.REBOOT
Not work 

            result = self.driver.execute_script('mobile: shell', {
                        'command': 'su',
                        'args': [''],
                        'includeStderr': True,
                        'timeout': 5000
                    })
            result = self.driver.execute_script('mobile: shell', {
                        'command': 'am start -a android.intent.action.REBOOT',
                        'args': [''],
                        'includeStderr': True,
                        'timeout': 5000
                    })



Error

`Cannot execute the 'su' shell command. Original error: Command 'D:\\privappdata\\android\\sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 shell su ' timed out after 5000ms. StdOut: . StdErr:`

**Comment by mykola-mokhnach** [comment]
It does not work this way. `su` does not change privileges globally, but only for the current command, which should be passed to it as an argument, for example: `adb shell su 0 pm clear org.mozilla.firefox`

**Comment by tolgatasci** [comment]
I understand, it is nice, thank you.
