### ISSUE TITLE
XCUITest  doesn't   install WDA  on iOS Simulator  but on real device WDA is installing and works fine 

### ISSUE THREAD

**Issue by levank707** [appium/appium#15186]
## The problem

XCUITest  doesn't   install WDA  on iOS Simulator  but on real device WDA is installing and works fine 
## Environment

* Appium version (or git revision) that exhibits the issue:1.20.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: OS
* Node.js version (unless using Appium.app|exe):v15.11.0
* Npm or Yarn package manager:npm
* Mobile platform/version under test: iPhone 12 Pro
* Real device or emulator/simulator: Simulatior
* Appium CLI or Appium.app|exe:both

## Link to Appium logs

https://gist.github.com/levank707/843d65cd8ba72f486950cf5f2aa69837

**Comment by mykola-mokhnach** [comment]
It seems like xcodebuild does not properly build the project for the Simulator arch. Try to clean the project and build it manually for a Slmulator from Xcode.

**Comment by KazuCocoa** [comment]
What about https://github.com/appium/java-client/issues/1444#issuecomment-780785808 or https://github.com/appium/java-client/issues/1444#issuecomment-781078298 ?

**Comment by KazuCocoa** [comment]
oh, you just commented. ^

**Comment by levanikhvedelidze** [comment]
> What about [appium/java-client#1444 (comment)](https://github.com/appium/java-client/issues/1444#issuecomment-780785808) or [appium/java-client#1444 (comment)](https://github.com/appium/java-client/issues/1444#issuecomment-781078298) ?

didn't helped :(  I also have M1 silicon

**Comment by levank707** [comment]
> What about [appium/java-client#1444 (comment)](https://github.com/appium/java-client/issues/1444#issuecomment-780785808) or [appium/java-client#1444 (comment)](https://github.com/appium/java-client/issues/1444#issuecomment-781078298) ?

didn't helped :( I also have M1 silicon

**Comment by levank707** [comment]
over 3 days I'm stuck on this problem, I also tried to install old version of Xcode and Appium but its same :(((

**Comment by KazuCocoa** [comment]
My M1 macOS env worked with current appium/WDA preference for both real/simulator devices before.
`Validate Workspace` and `Build Active Architecture Only` could help other persons.

1.20 no longer has _carthage_ dependencies, so build configuration stuff only depends on `xcodebuild`/Xcode itself.
(Older Appium versions may have some building issues on M1 macOS)
Removing `DerivedData` and clean build env helps sometimes for xcodebuild/Xcode.

I have no good idea for now. Potentially your environment has another preference stuff in xcodebuild/Xcode...

https://github.com/appium/WebDriverAgent is the appium/WDA repository, so you can clone the repository and open it in Xcode, and build it via Xcode.

**Comment by levank707** [comment]
> My M1 macOS env worked with current appium/WDA preference for both real/simulator devices before.
> `Validate Workspace` and `Build Active Architecture Only` could help other persons.
> 
> 1.20 no longer has _carthage_ dependencies, so build configuration stuff only depends on `xcodebuild`/Xcode itself.
> (Older Appium versions may have some building issues on M1 macOS)
> Removing `DerivedData` and clean build env helps sometimes for xcodebuild/Xcode.
> 
> I have no good idea for now. Potentially your environment has another preference stuff in xcodebuild/Xcode...
> 
> https://github.com/appium/WebDriverAgent is the appium/WDA repository, so you can clone the repository and open it in Xcode, and build it via Xcode.

Carthage is no more necessary ? but in the appium-doctor carthage is written as necessary dependencies

**Comment by KazuCocoa** [comment]
I think the latest doctor has a message about it is for lower than Appium 1.20.0 if no carthage env.
The lower ones still need it, so it remains with a bit different messages.

**Comment by levank707** [comment]
> I think the latest doctor has a message about it is for lower than Appium 1.20.0 if no carthage env.
> The lower ones still need it, so it remains with a bit different messages.

Thank you very much. I will delete carthage and build WDA from original repository. wish I fix simulator problem on M1 :(((

**Comment by levank707** [comment]
first I  did  rm -rf /Users/levank/Library/Developer/Xcode/DerivedData/WebDriverAgent-*  as  Mykola said , than I cloned webdriverproj from git and build in xcode. I also set settings  for Build Active Architecture Only to "NO" and Validate Workspace to "YES"  after that I build WDA one more time , but same same and same. on simulator it doesn't install and on real device it does.

**Comment by levank707** [comment]
![Uploading Screenshot 2021-03-14 at 16.18.52.png…]()

**Comment by levank707** [comment]
![Uploading Screenshot 2021-03-14 at 16.18.52.png…]()

**Comment by levank707** [comment]
https://i.ibb.co/7JrjRgd/Screenshot-2021-03-14-at-16-18-52.png here is image

**Comment by KazuCocoa** [comment]
Hm...
I tried out it on my env again. It worked well...
How about Xcode 12.5 beta? Potentially newer ones have some build fixes.

**Comment by levanikhvedelidze** [comment]
> Hm...
> I tried out it on my env again. It worked well...
> How about Xcode 12.5 beta? Potentially newer ones have some build fixes.

I try it now, if it also won't  work , I have no choice, I'll return back to my old mac :( . but I'm little bit confused, because I ordered also Mac mini (M1) for server  and I think there also would be same problem... P.S     when I trie to run programmatically  Appium from java on real device, there was same problem :(

**Comment by KazuCocoa** [comment]
I see..
Btw, my M1 macOS(11.1) environment had only Xcode 12.4 and 12.5-beta, Appium (via npm with NodeJS 12) and Ruby (for Appium client) environment. No Rosetta2 presented on the machine. It did not have other tools like Android development environment.

**Comment by levank707** [comment]
> I see..
> Btw, my M1 macOS(11.1) environment had only Xcode 12.4 and 12.5-beta, Appium (via npm with NodeJS 12) and Ruby (for Appium client) environment. No Rosetta2 presented on the machine. It did not have other tools like Android development environment.

It was same,  so, now I am going to  erase and make factory reset on mac and I'll  install everything   step by step one more time.

**Comment by levank707** [comment]
> I see..
> Btw, my M1 macOS(11.1) environment had only Xcode 12.4 and 12.5-beta, Appium (via npm with NodeJS 12) and Ruby (for Appium client) environment. No Rosetta2 presented on the machine. It did not have other tools like Android development environment.

It was same, so, now I am going to erase and make factory reset on mac and  install everything step by step one more time again.
KazuCocoa one question,  I'm not  familiar with xcode  and just for clarify ,  when I am opening WebDriverAgent.xcodeproj  I'm just  pressing "command + B" to build. and in the scheme is chosen integration.app.  is it ok? am I building it right ?

**Comment by KazuCocoa** [comment]
`WebDriverAgentRunner` scheme and run it as Test is correct way. Then, WDA app will be installed and run on a device (real/simulator). The integration app is for testing on CI.

https://stackoverflow.com/questions/46956639/cant-run-uitest-on-iphone-4s-simulator-with-xcode-9's recent comment might help...?

**Comment by levank707** [comment]
> `WebDriverAgentRunner` scheme and run it as Test is correct way. Then, WDA app will be installed and run on a device (real/simulator). The integration app is for testing on CI.
> 
> https://stackoverflow.com/questions/46956639/cant-run-uitest-on-iphone-4s-simulator-with-xcode-9's recent comment might help...?

I don't have Excluded Architectures in build settings.....  So I tried but still same, thank for your help and effort very much  Kazu, I'll continue work on my old intel mac.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by vjmaiky** [comment]
what to do in cases where appium was installed in other location: /opt/homebrew/lib/node_modules/appium/node_modules/ and not the usual usr/local/..... ?

```
[debug] [W3C] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: Trying to use WebDriverAgent project at '/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj' but the file does not exist. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[debug] [W3C]     at quitAndUninstall (/opt/homebrew/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:556:15)
```

**Comment by mykola-mokhnach** [comment]
@vjmaiky there is `bootstrapPath` capability, which allows to provide a customized path to WDA sources
