### ISSUE TITLE
Cannot find apksigner.jar

### ISSUE THREAD

**Issue by peterwkc85** [appium/appium#15185]
Cannot find apksigner.jar

Original error: Cannot verify the signature of Could not find 'apksigner.jar'

## Environment
Windows

* Appium version (or git revision) that exhibits the issue: 1.20.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Window 10
* Node.js version (unless using Appium.app|exe): C:\Users\nicholaswkc>node Welcome to Node.js v14.15.4.
* Npm or Yarn package manager: 6.14.10
* Mobile platform/version under test: Android 10
* Real device or emulator/simulator: Huawei P20
* Appium CLI or Appium.app|exe: Appium.exe

## Details
When doing automation in appium, facing this error of cannot find apksigner.jar

## Link to Appium logs

UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot verify the signature of 'C:\Users\nicholaswkc\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.17.4.apk'. Original error: Could not find 'apksigner.jar' in ["C:\\Users\\nicholaswkc\\AppData\\Local\\Android\\Sdk\\platform-tools\\apksigner.jar","C:\\Users\\nicholaswkc\\AppData\\Local\\Android\\Sdk\\emulator\\apksigner.jar","C:\\Users\\nicholaswkc\\AppData\\Local\\Android\\Sdk\\cmdline-tools\\latest\\bin\\apksigner.jar","C:\\Users\\nicholaswkc\\AppData\\Local\\Android\\Sdk\\tools\\apksigner.jar","C:\\Users\\nicholaswkc\\AppData\\Local\\Android\\Sdk\\tools\\bin\\apksigner.jar","C:\\Users\\nicholaswkc\\AppData\\Local\\Android\\Sdk\\apksigner.jar"]. Do you have Android Build Tools installed at 'C:\Users\nicholaswkc\AppData\Local\Android\Sdk\'?
    at getResponseForW3CError (C:\Users\nicholaswkc\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\nicholaswkc\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)

## Code To Reproduce Issue [ Good To Have ]

public static void initAndroidDriver() throws MalformedURLException {
        logger.info("********************init Android Driver*******************");
        DesiredCapabilities capabilities = new DesiredCapabilities();

        capabilities.setCapability("deviceName", System.getProperty("APPIUM_DEVICE_NAME", "WCR0218320001804"));
        capabilities.setCapability("platformVersion", System.getProperty("APPIUM_DEVICE_VERSION", "10"));
        capabilities.setCapability("automationName", "Appium");
        capabilities.setCapability("platformName", System.getProperty("APPIUM_PLATFORM", "Android"));
        capabilities.setCapability("appPackage", "com.toyota.oneapp.stage");
        capabilities.setCapability("appActivity", "com.toyota.oneapp.ui.splash.SplashActivity");
        capabilities.setCapability("noReset", true);
        capabilities.setCapability("newCommandTimeout", 7200);
        capabilities.setCapability("unicodeKeyboard", true);
        capabilities.setCapability("resetKeyboard", true);
        //capabilities.setCapability("autoWebview", true);

        capabilities.setCapability("chromedriverChromeMappingFile", Utils.getAbsolutePath("chromdrivermap/map.json"));
        capabilities.setCapability("chromedriverExecutableDir", Utils.getAbsolutePath("chromedriver"));

        ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.setCapability("browserName", "");
        chromeOptions.setExperimentalOption("w3c", false);
        capabilities.merge(chromeOptions);

        /**
         * need to add x right to file
         */
        File file = new File(Utils.getAbsolutePath("chromedriver"));
        List<File> files = Arrays.asList(file.listFiles());

        files.forEach(ele -> {
            try {
                ele.getAbsolutePath();
                Runtime.getRuntime().exec(String.format("chmod +x %s", ele.getAbsolutePath()));
            } catch (IOException ignore) {
                //ignore.printStackTrace();
            }
        });

        try {
            driver = new AndroidDriver(new URL(System.getProperty("APPIUM_URL", "http://127.0.0.1:4723/wd/hub")), capabilities);
        } catch (Exception err) {
            logger.info("Android Driver init failed: ");
            logger.error(err);
            throw err;
        }

        logger.info("Android Driver init successfully");
    }

**Comment by KazuCocoa** [comment]
What about https://github.com/appium/appium/issues/15172#issuecomment-793465935 ?

**Comment by peterwkc85** [comment]
I had installed Android build tools 24.0.3. The lookup folder is different from what adnroid studio is installed as path.

**Comment by KazuCocoa** [comment]
Could you share your ANDROID_HOME?

Potentially Android Studio installs build tools only for itself. You should set path up properly.
https://appium.io/docs/en/drivers/android-uiautomator2/#basic-setup

**Comment by peterwkc85** [comment]
ANDROID_HOME - C:\Users\nicholaswkc\AppData\Local\Android\Sdk\

**Comment by KazuCocoa** [comment]
Thanks. Then, where the build tools?
Potentially we should add additional search path for build tools for Windows environment in Appium's binaries lookup.

**Comment by peterwkc85** [comment]
Android Build Tools - C:\Users\nicholaswkc\AppData\Local\Android\Sdk\platform-tool\build-tools\24.0.3\

**Comment by KazuCocoa** [comment]
It seems recent(?) Windows env has changed to the directory structure. The path had no `platform-tool` before.

What about directories in `C:\Users\nicholaswkc\AppData\Local\Android\Sdk\` and `C:\Users\nicholaswkc\AppData\Local\Android\Sdk\platform-tool\`?

**Comment by mykola-mokhnach** [comment]
Please provide the full server log. It looks like no valid build tools folders have been found the .jar file itself is expected to be located in `./build-tools/<latest_build_tools_version>/lib/apksigner.jar` under $ANDROID_HOME

See https://developer.android.com/studio/command-line for the reference

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
