### ISSUE TITLE
InvalidElementStateException: Cannot set the element to 'xxxxx'. Did you interact with the correct element?

### ISSUE THREAD

**Issue by ManthiraMani** [appium/appium#15184]
## The problem

Getting an error as InvalidElementStateException: Cannot set the element to 'salaimani.89@gmail.com'. Did you interact with the correct element? when sending values to the mobile element

I am able to click on the element. But send keys is not working

## Environment

*{"desiredCapabilities":{"appActivity":"uk.co.lycaremit.lyca_remit.MainActivity","appPackage":"uk.co.lycaremit.lyca_remit","appWaitForLaunch":"false","platformVersion":"9","automationName":"uiautomator2","platformName":"Android","udid":"8b3090af","deviceName":"Redmi Note 5 Pro"},"capabilities":{"firstMatch":[{"appium:appActivity":"uk.co.lycaremit.lyca_remit.MainActivity","appium:appPackage":"uk.co.lycaremit.lyca_remit","appWaitForLaunch":"false","appium:automationName":"uiautomator2","appium:deviceName":"Redmi Note 5 Pro","platformName":"android","appium:platformVersion":"9","appium:udid":"8b3090af"}]}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"appActivity":"uk.co.lycaremit.lyca_remit.MainActivity","appPackage":"uk.co.lycaremit.lyca_remit","appWaitForLaunch":"false","platformVersion":"9","automationName":"uiautomator2","platformName":"Android","udid":"8b3090af","deviceName":"Redmi Note 5 Pro"},null,{"firstMatch":[{"appium:appActivity":"uk.co.lycaremit.lyca_remit.MainActivity","appium:appPackage":"uk.co.lycaremit.lyca_remit","appWaitForLaunch":"false","appium:automationName":"uiautomator2","appium:deviceName":"Redmi Note 5 Pro","platformName":"android","appium:platformVersion":"9","appium:udid":"8b3090af"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1615484292050 (23:08:12 GMT+0530 (India Standard Time))
[BaseDriver] The following capabilit

## Link to Appium logs

https://gist.github.com/ManthiraMani/a51810c4f5d1c617e039d04fbbf4892a

## Code To Reproduce Issue [ Good To Have ]

This is my script
//Click On SignIn/SignUp
		driver.findElementByXPath("//*[contains(@content-desc,'Sign In / Sign Up')]").click();		
		Thread.sleep(3000);
		System.out.println("Test1");
		MobileElement element = (MobileElement) driver.findElementByXPath("//android.widget.EditText[@text='Type in your email']");
		element.sendKeys("salaimani.89@gmail.com");

		 System.out.println("Is element  enabled"+element.isEnabled());
		 System.out.println("This is element size"+element.getSize());
		 driver.findElementByAndroidUIAutomator("text(\"Type in your email\")").sendKeys("salaimani.89@gmail.com");
		
		System.out.println("Test3");
		driver.findElementByXPath("//android.widget.EditText[@text='*******']").click();
		System.out.println("Test4");
		driver.findElementsByClassName("android.widget.EditText").get(1).sendKeys("***********");		
		System.out.println("Test5");
		driver.findElementByXPath("//*[contains(@content-desc,'Sign In')]").click();

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Closed as duplicate: https://github.com/appium/appium/search?q=%22Cannot+set+the+element+to%22&type=issues
