### ISSUE TITLE
Progressive Web App test automation using Appium & WebdriverJS throws error after the app is launched

### ISSUE THREAD

**Issue by manish2788** [appium/appium#15194]
## The problem

While testing a Progressive web app over Android device using Appium and WebdriverIO (JavaScript), the app is being launched by appium however after few seconds appium throws an error as shown below in logs while launching the subsequent activities.
No issue is observed with a native app though.

## Environment

* Appium version (or git revision) that exhibits the issue: **1.20**
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: **MacOS Catalina 10.15.7**
* Node.js version (unless using Appium.app|exe): **11.13.0**
* Npm or Yarn package manager: **NPM**
* Mobile platform/version under test: **Android 10**
* Real device or emulator/simulator: **Emulator**
* Appium CLI or Appium.app|exe: **Appium CLI**

## Details

Configured the appium with desired capabilities for android, Connected a real android device and started the appium server through CLI. The Progressive web app(PWA) package is installed by the appium, app is also launched on device however after sometime appium errors out with following log which seems to be related to Android app activities.
This issue is not observed for a native app rather only for PWA app. Any limitation of Appium with PWA app automation?

## Link to Appium logs

https://gist.github.com/manish2788/dd87057bce80fd8cb714d4f2d5cad464

## Code To Reproduce Issue [ Good To Have ]

```
import {expect, assert} from 'chai';
import {Builder, By, until, WebDriver, Capabilities} from 'selenium-webdriver';

const platformCapabilities = {
    "android": {
        "platformName": "Android",
        "platformVersion": "10",
        "deviceName": "Pixel 3",
        "automationName": "Appium",
        "app": "/Users/kmanikum/Desktop/pwa-demo.apk",
        "browserName": ""
    }
};

const serverAddress = "http://0.0.0.0:4723/wd/hub";
const driver = new Builder().usingServer(serverAddress).withCapabilities(platformCapabilities.android).build();



describe('Test PWA', () => {
  before(async () => {
    
    await driver.get("https://demowebsite.com");
  });
 
  it('can read title text', async () => {
    const titleElement = await driver.findElement(By.id('title'));
    const text = await titleElement.getText();
    console.log(text);
    expect(text).to.equal('DevCoffee');
  });
});
```

**Comment by mykola-mokhnach** [comment]
I don't observe any issues from Appium side there. Try the trouble shooting tutorial at https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
