### ISSUE TITLE
Using 'ios-deploy' to launch iOS apps instead of Springboard

### ISSUE THREAD

**Issue by ajschwieterman** [appium/appium#15197]
## The problem

Flutter debug builds cannot be launched from the Home Screen (springboard) on iOS 14+.  However, I can launch the builds using `ios-deploy`.  Is there a method in Appium or the WebDriverAgent to use `ios-deploy` instead of springboard to launch the app?

## Environment

* Appium version (or git revision) that exhibits the issue: v1.20.1
* Last Appium version that did not exhibit the issue (if applicable): ---
* Desktop OS/version used to run Appium:  macOS Big Sur v11.2.3
* Node.js version (unless using Appium.app|exe): v14.13.0
* Npm or Yarn package manager: v6.14.11
* Mobile platform/version under test: iOS v14.4
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

With the release of iOS 14, Apple changed some of the low-level debugging permissions causing Flutter developers to not be able to launch their debug builds from the Home Screen; a debugger or host computer needs to be attached to the launch.  This is described by the Flutter dev team [here](https://flutter.dev/docs/development/ios-14).  The team has suggested launching the app using `ios-deploy` (see [here](https://github.com/flutter/flutter/issues/60657#issuecomment-688478590)).  I have created an issue in the appium-flutter-driver repo for this problem (see [here](https://github.com/truongsinh/appium-flutter-driver/issues/115)).

**Comment by mykola-mokhnach** [comment]
> Is there a method in Appium or the WebDriverAgent to use ios-deploy instead of springboard to launch the app?

I don't quite understand what you mean. xcuitest driver uses XCTest API to manage the application's life cycle. I don't know what it has to do with Springboard. Also, we don't officially support nor test Flutter apps with this driver. Please let us know if you'd like to contribute to that and maintain the compatibility.
