### ISSUE TITLE
Android "pinchCloseGesture" does not function

### ISSUE THREAD

**Issue by Aubbles01** [appium/appium#15203]
## The problem

From what I can tell, the gesture "pinchCloseGesture" in UIAutomator2 is not functioning.  My code executes this script using the parameters elementId, percent, and speed.  These values are passed into a function that first determines if the test is running on iOS or Android and then executes the appropriate script.  Some example code (java):

`public static void PinchOrZoom(Double scale, Integer velocity, MobileElement elementToPinch)
  {
    try {
      //scale between 0 and 1 is a pinch, greater than 1 is a zoom
      //velocity must be less than 0 if scale is less than one
      String elementId = elementToPinch.getId();
      Map<String, Object> args = new HashMap<>();
      if(Platform() == "iOS")
      {
        args.put("scale", scale);
        args.put("element", elementId);
        args.put("velocity", velocity);
        driver.executeScript("mobile: pinch", args);
      }
      else if(Platform() == "Android")
      {
        Double percent;
        if(scale > 1)
        {
          percent = Double.valueOf(scale/10.00);
        }
        else
        {
          percent = Double.valueOf(scale);
        }
        Integer speed = velocity * 1000;
        args.put("elementId", elementId);
        args.put("percent", percent);
        args.put("speed", speed);
        if(scale > 1)
        {
          driver.executeScript("mobile:pinchOpenGesture", args);
        }
        else
        {
          driver.executeScript("mobile:pinchCloseGesture", args);
        }
      }
      else
      {
        System.out.println("Invalid platform.  Could not perform pinch/zoom");
      }`

So, the code here has to account for both iOS and Android gestures.  That is why we convert the scale to the percent and why the speed is converted as well.

This code works just fine for the pinchOpenGesture, but does not function at all for pinchCloseGesture.  I get no exceptions, but nothing happens.

Speed/percent values that I'm attempting to use right now are:
speed = 2000;
percent = 0.5;

However, I have tried a variety of different percents and speeds (including not including the speed argument at all so that it defaults).  None of them appear to pinch close at all.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Mac OS 11.2.3 (Big Sur)
* Node.js version (unless using Appium.app|exe): Using appium.app
* Npm or Yarn package manager: Npm 6.9.0
* Mobile platform/version under test: Android 
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:  Appium.app

## Details

No more details to add other than what is above.

## Link to Appium logs

This log includes a run of the full test where I am trying to call this code.  
https://gist.github.com/Aubbles01/9661dd79e73f60e90f3a9613a8511244

## Code To Reproduce Issue [ Good To Have ]

Hopefully the above code is enough information to reproduce the issue.

**Comment by mykola-mokhnach** [comment]
This method simply forwards the call to the corresponding primitive of [GestureController]( https://android.googlesource.com/platform/frameworks/uiautomator/+/android-support-test/src/main/java/android/support/test/uiautomator/GestureController.java) class from uiautomator package. I don't see any issues on the Appium side there. Consider reporting the issue to Google. Also you could try to implement pinch gesture using lower-level W3C actions and/or add more logging to the application under test.

Also, it makes sense to read https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/actions.md

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
