### ISSUE TITLE
The location of appium is inaccurate without context switching. Worse still, appium will not update the location, even if the location of the element has changed

### ISSUE THREAD

**Issue by tianyao1111** [appium/appium#15206]
## The problem

On the webview page, use the native app method to locate and click. When the position of the element changes, the x and y values of the element are not updated, causing the click to fail

## Environment

* Appium version (or git revision) that exhibits the issue:1.20.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:win10
* Node.js version (unless using Appium.app|exe):14.16.0
* Npm or Yarn package manager:npm
* Mobile platform/version under test:10
* Real device or emulator/simulator:*Real device
* Appium CLI or Appium.app|exe:

## Details
I want to click "//android.view.View[@text=\"交强险\"]"，But appium did not click on it, and the obtained location={"x":74,"y":333}, but the actual coordinate of this element is [74,403][168,435]

## Link to Appium logs

> [HTTP] {"using":"xpath","value":"//android.view.View[@text=\"交强险\"]"}
> [debug] [W3C (e4d1ef6c)] Calling AppiumDriver.findElement() with args: ["xpath","//android.view.View[@text=\"交强险\"]","e4d1ef6c-96a1-426e-af3c-f3bf478b44f4"]
> [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, css selector, -android uiautomator
> [debug] [BaseDriver] Waiting up to 30000 ms for condition
> [debug] [WD Proxy] Matched '/element' to command name 'findElement'
> [debug] [WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8200/wd/hub/session/4fa3a9ed-3c52-4cfe-81f2-cd9f4e31b717/element] with body: {"strategy":"xpath","selector":"//android.view.View[@text=\"交强险\"]","context":"","multiple":false}
> [debug] [WD Proxy] Got response with status 200: {"sessionId":"4fa3a9ed-3c52-4cfe-81f2-cd9f4e31b717","value":{"ELEMENT":"64d84d1b-7dca-4e42-b491-5055542bcb30","element-6066-11e4-a52e-4f735466cecf":"64d84d1b-7dca-4e42-b491-5055542bcb30"}}
> [debug] [W3C (e4d1ef6c)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"64d84d1b-7dca-4e42-b491-5055542bcb30","ELEMENT":"64d84d1b-7dca-4e42-b491-5055542bcb30"}
> [HTTP] <-- POST /wd/hub/session/e4d1ef6c-96a1-426e-af3c-f3bf478b44f4/element 200 149 ms - 137
> [HTTP]
> [HTTP] --> GET /wd/hub/session/e4d1ef6c-96a1-426e-af3c-f3bf478b44f4/element/64d84d1b-7dca-4e42-b491-5055542bcb30/location
> [HTTP] {}
> [W3C (e4d1ef6c)] Driver proxy active, passing request on via HTTP proxy
> [debug] [WD Proxy] Matched '/wd/hub/session/e4d1ef6c-96a1-426e-af3c-f3bf478b44f4/element/64d84d1b-7dca-4e42-b491-5055542bcb30/location' to command name 'getLocation'
> [debug] [WD Proxy] Proxying [GET /wd/hub/session/e4d1ef6c-96a1-426e-af3c-f3bf478b44f4/element/64d84d1b-7dca-4e42-b491-5055542bcb30/location] to [GET http://127.0.0.1:8200/wd/hub/session/4fa3a9ed-3c52-4cfe-81f2-cd9f4e31b717/element/64d84d1b-7dca-4e42-b491-5055542bcb30/location] with no body
> [debug] [WD Proxy] Got response with status 200: {"sessionId":"4fa3a9ed-3c52-4cfe-81f2-cd9f4e31b717","value":{"x":74,"y":333}}

**Comment by mykola-mokhnach** [comment]
These coordinates are returned bu Google's UiAutomator framework itself. Unfortunately we cannot do nothing from Appium side to change this behaviour. Consider reporting your issue to Google

**Comment by tianyao1111** [comment]
> 这些坐标由Google的UiAutomator框架本身返回。不幸的是，我们不能从Appium方面采取任何措施来改变这种行为。考虑将您的问题报告给Google

Hello, I tested it with different phones.
In the mobile phone, settings-developer options-webview implementation.
If webview implement == google webview, you can click to it;
If webview implementation == Huawei webview, you can also click to it;
But the webview implementation == Android System WebView 77.0.3865.92, the element cannot be clicked
I hope this information can be useful to you

**Comment by mykola-mokhnach** [comment]
Like I said this depends on a third party implementation, which is beyond Appium's control. You could also try the [hybrid](https://appium.io/docs/en/writing-running-appium/web/hybrid/) mode as a possible workaround.
