### ISSUE TITLE
Appium does not show webview context, it only showing native app context. How to get webview context?

### ISSUE THREAD

**Issue by chetanJTH** [appium/appium#15201]
## The problem

I get both context sometimes and sometimes it does not give webview. it's only display native app.

## Environment

* Appium version : 1.20.2
* Last Appium version that did not exhibit the issue (if applicable): i haven't used before
* Desktop OS/version used to run Appium: Mac 10.15.1
* Node.js version (unless using Appium.app|exe): 14.16.0
* Npm or Yarn package manager: 6.14.11
* Mobile platform/version under test: Android 11
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI 7.0.0

## Details

I am using an android native app.
I have a scenario where I need to block some url and need to check in the browser.
so after blocking url I try to change context in webview and try to open chrome.
but it does not open chrome.
when I try to check context available it only displays native app.
but sometimes same code get both context available but test fails as it failed to open the browser.

## Link to Appium logs

https://gist.github.com/chetanJTH/26dfa0042f1ce16f2a415967a7798c7f

## Code To Reproduce Issue [ Good To Have ]

https://github.com/chetanJTH/Hybrid

Please check project and try to reproduce from your end.

**Comment by mykola-mokhnach** [comment]
Is the web context visible through the Chrome remote debugger?

**Comment by chetanJTH** [comment]
i dont know much about remote debugger. but I have attached ss of window with same project.

![image](https://user-images.githubusercontent.com/48850556/111775037-3f38d480-88d6-11eb-8663-b745a9de58aa.png)

**Comment by mykola-mokhnach** [comment]
Unfortunately this information is not very helpful. Please learn how to use the remote debugger if you still need help on this issue

**Comment by chetanJTH** [comment]
it does not display any web view on app unless I open chrome.
![image](https://user-images.githubusercontent.com/48850556/111858986-65f11c80-8963-11eb-864d-ff0bb09b1532.png)

**Comment by mykola-mokhnach** [comment]
if the web view is not visible in Chrome then it won't be available in Appium as well. Please check its settings with your developer

**Comment by chetanJTH** [comment]
ok, thanks for help @mykola-mokhnach
