### ISSUE TITLE
Unable to use appium in windows due to path issue in appium-xcuitest-driver

### ISSUE THREAD

**Issue by vikram-chaitanya** [appium/appium#15216]
## The problem

I am trying appium in windows(coupled with webDriverAgentUrl). But the node_module appium-xcuitest-driver is throwing error with path module since the process.env.HOME is undefined (https://github.com/appium/appium-xcuitest-driver/blob/master/lib/device-log/ios-crash-log.js#L11).

## Environment

* Appium version (or git revision) that exhibits the issue: V1.20.2
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: V1.20.2
* Node.js version (unless using Appium.app|exe): 14.16
* Npm or Yarn package manager: npm
* Mobile platform/version under test: IOS 14
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: appium.exe

## Details

Can you please try to use platform agnostic way of getting home directory - 

``` const homedir = require('os').homedir(); ```

I tried to use this and it worked for me.

**Comment by mykola-mokhnach** [comment]
xcuitest driver is only supposed to run on Mac OS. We don't support any other OS's, because Xcode DevTools are not available there.
