### ISSUE TITLE
Unable to get Webview context by running getContexts()

### ISSUE THREAD

**Issue by thuquynhpham** [appium/appium#15215]
## The problem

I am executing method `driver.getContexts();` in javascript to get all the context on iOS simulator. It should return NATIVE_APP and WEBVIEW, but it returns only NATIVE_APP on my test 

With the desktop version, it works and returns both NATIVE_APP & WEBVIEW on Appium inspector

When I am using the same method in Java, it also works and returns 2 contexts: `driver.getContextHandles()`

## Environment

* Appium version: 1.20.2
* Last Appium version that did not exhibit the issue (if applicable): I started with 1.20.2
* Desktop OS/version used to run Appium: 1.20.0
* Node.js version (unless using Appium.app|exe): 6.14.11
* Npm or Yarn package manager:
* Mobile platform/version under test: iOS 13.4, 14.3
* Real device or emulator/simulator: simulator iPhone XS Max
* Appium CLI or Appium.app|exe:

## Code To Reproduce Issue (Javascripts)
`let contexts = driver.getContexts();
  console.log("All the context: " + contexts)`

**Comment by mykola-mokhnach** [comment]
this could be a race condition issue. Try to request context several times until timeout happens. This could also happen automatically by providing a value to [webviewConnectTimeout capability](https://github.com/appium/appium-xcuitest-driver#web-context). Also, it makes sense to make sure the web view is available in general by connecting to it using Safari remote debugger and to provide the server logs

**Comment by thuquynhpham** [comment]
the issue doesn't happen in Java code with the same app, same simulator, same machine

**Comment by mykola-mokhnach** [comment]
Unfortunately we cannot help more without the requested information

**Comment by mykola-mokhnach** [comment]
Closed because of no response
