### ISSUE TITLE
Can't Select from any PickerWheel

### ISSUE THREAD

**Issue by dkoudrinhc** [appium/appium#15217]
## The problem

I have been trying everything I could possibly find on the web regarding selecting a value from a pickerwheel using appium and nothing seems to be working.
I am seeking urgent help/advice on how to do this, as it shouldn't be that hard!

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: MacOS Big Sur
* Node.js version (unless using Appium.app|exe): v10.16.3
* Npm or Yarn package manager: 6.9.0
* Mobile platform/version under test: iOS 14.4
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: ?

## Details

I am using typescript/javascript for my e2e mobile tests with appium driver. 
Have tried things like sendKeys (to various elements), 'type' method, trying to tap on elements, etc. Nothing works.
One thing I couldn't figure out how to use properly was the "selectPickerWheelValue" script - how do I get the internal id of an element to supply to this method?
e.g.
const pickerWheel = await this.driver.findElementByClassName('UIAPickerWheel');
await this.driver.driver.execute('mobile: selectPickerWheelValue', {
element: pickerWheel   <--- supposed to be a hexadecimal value here but no idea where/how to get this
order: 'next',
offset: 0.5
});

## Link to Appium logs

I don't have any appium logs, no idea how to get those sorry.

## Code To Reproduce Issue [ Good To Have ]

const pickerWheel = await this.driver.findElementByClassName('UIAPickerWheel');
await this.driver.driver.execute('mobile: selectPickerWheelValue', {
element: pickerWheel,
order: 'next',
offset: 0.5
});

**Comment by KazuCocoa** [comment]
It depends on your client.
e.g. (Java tho) https://github.com/appium/appium/blob/ca001513ab16394255a9fd0f32a1309ebf9bead4/docs/en/writing-running-appium/ios/ios-xctest-mobile-gestures.md#usage-examples-8
Most case is probably `element.id` or similar method. The id is originally in the response of `find_element/s` methods.

https://discuss.appium.io/ also may help.

**Comment by dkoudrinhc** [comment]
> It depends on your client.
> e.g. (Java tho) https://github.com/appium/appium/blob/ca001513ab16394255a9fd0f32a1309ebf9bead4/docs/en/writing-running-appium/ios/ios-xctest-mobile-gestures.md#usage-examples-8
> Most case is probably `element.id` or similar method. The id is originally in the response of `find_element/s` methods.
> 
> https://discuss.appium.io/ also may help.

Yes I am using javascript, there is no .id method on a UIElement object or similar that I know about unfortunately.

**Comment by KazuCocoa** [comment]
I don't know you uses which library by JS, but it would be nice to ask the library community about it.

**Comment by dkoudrinhc** [comment]
> I don't know you uses which library by JS, but it would be nice to ask the library community about it.

Nativescript-dev-appium I believe. But the community for that seems to be completely dead.

**Comment by KazuCocoa** [comment]
I don't have any knowledges about it.
Potentially https://discuss.appium.io/ may help.

**Comment by dkoudrinhc** [comment]
> I don't have any knowledges about it.
> Potentially https://discuss.appium.io/ may help.

Okay. I tried signing up to that website but the registration emails aren't coming through.

**Comment by KazuCocoa** [comment]
@jlipps do you have any idea about failing to register the discuss.appium.io?

**Comment by jlipps** [comment]
Hmm I looked into the admin settings but I don't see anything that could be responsible for e-mails not going through. @dkoudrinhc can you try signing up via github SSO instead of via e-mail?

**Comment by dkoudrinhc** [comment]
I got the confirmation email a couple of days later.
