### ISSUE TITLE
Command deleteSession() is failing with status 500 due to An unknown server-side error

### ISSUE THREAD

**Issue by barnie-xero** [appium/appium#15229]
## The problem

This happens on the Bitrise agents and cannot be reproduce locally.
The test steps gets executed successfully. But the app gets closed as soon as the test ends, returning the below error on deleteSession().

```
INFO webdriver: COMMAND deleteSession()
INFO webdriver: [DELETE] http://localhost:4723/session/74d7ce2a-a2e0-46c4-bba9-7b6af9ad5951
WARN webdriver: Request failed with status 500 due to An unknown server-side error occurred while processing the command. Original error: _appiumSupport.logger.warn is not a function
INFO webdriver: [DELETE] http://localhost:4723/session/74d7ce2a-a2e0-46c4-bba9-7b6af9ad5951
ERROR webdriver: Request failed with status 404 due to invalid session id: A session is either terminated or not started
```
## Environment

* Appium version (or git revision) that exhibits the issue: ^1.19.0
* Last Appium version that did not exhibit the issue (if applicable):^1.19.0
* Desktop OS/version used to run Appium: iOS Catalina 10.15.7
* Node.js version (unless using Appium.app|exe): 12.20.1
* Npm or Yarn package manager:6.14.10
* Mobile platform/version under test: 14.4
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: Appium cli

## Details

This issue is happening inconsistently making it harder to troubleshoot the problem.

## Code To Reproduce Issue [ Good To Have ]

```
  "devDependencies": {
    "@wdio/allure-reporter": "^7.0.4",
    "@wdio/cli": "^7.0.7",
    "@wdio/appium-service": "^7.0.7",
    "@wdio/junit-reporter": "^6.8.1",
    "@wdio/local-runner": "^6.9.0",
    "@wdio/spec-reporter": "^7.0.4",
    "@wdio/mocha-framework": "^7.0.7",
    "@wdio/sync": "^7.0.7",
    "appium": "^1.19.0",
    "wdio-json-reporter": "^2.0.0",
    "chromedriver": "^88.0.0",
    "eslint": "^7.3.0",
    "wdio-chromedriver-service": "^6.0.3",
    "dotenv": "^8.2.0",
    "mocha": "^8.2.1"
  }
```

```
config.capabilities = [
    {
        platformName: 'iOS',
        deviceName: 'iPhone 11',
        platformVersion: '14.4',
        automationName: 'XCUITest',
        app: path.resolve('apps/Xero Me.app'),
        noReset: false,
        fullReset: false,
        maxInstances: 1,
        restart: true,
        wdaLaunchTimeout: '12000000',
        wdaConnectionTimeout: '12000000',
        autoAcceptAlerts: true,
        newCommandTimeout: '300'
    }
];

```

**Comment by mykola-mokhnach** [comment]
This issue has been [fixed](https://github.com/appium/appium-xcuitest-driver/commit/27bc045da8ae8f3fa9b94f2ede48519ca7a2ce08) in appium@beta. It might happen on a slow CI machines if they need more time to kill the logger process.

**Comment by barnie-xero** [comment]
Thanks @mykola-mokhnach . How would you suggest me to fix this for now? Should I downgrade appium to a particular version? Or Is the beta version available?

**Comment by mykola-mokhnach** [comment]
You could install beta locally using `npm i -g appium@beta`, although  it probably won't work in the cloud. Consider contacting their customer support.
