### ISSUE TITLE
Enhancement: Provide flag in .npmrc-file to skip chromedriver installation

### ISSUE THREAD

**Issue by RTK** [appium/appium#15220]
## The problem

When I add appium as dependency it will download chromedriver via appium-chromedriver after installation. The appium-chromedriver already provides possibilities to prevent this by using the --chromedriver-skip-install flag on installation. It would be more convenient to have a solution which uses the .npmrc-file because this would handle the prevention in one place and would not require the change of e.g. ci installation scripts. The appium-chromedriver already makes use of the .npmrc when declaring the chromedriver version (chromedriver_version field in .npmrc is applicable).

## Environment

* Appium version (or git revision) that exhibits the issue: Latest (v1.20.2)
* Last Appium version that did not exhibit the issue (if applicable):none
* Desktop OS/version used to run Appium: Mac OS 11.2.1
* Node.js version (unless using Appium.app|exe): v15.9.0
* Npm or Yarn package manager: npm 7.5.3
* Mobile platform/version under test:-
* Real device or emulator/simulator:-
* Appium CLI or Appium.app|exe:-

## Details

The package chromedriver (https://www.npmjs.com/package/chromedriver) provides this feature so I think this makes sense in the appium package as well.

## Code To Reproduce Issue [ Good To Have ]

Add appium as dependency, install and try to prevent the installation of chromedriver via npmrc.

**Comment by mykola-mokhnach** [comment]
Thanks for the suggestion @RTK 
Feel free to push a PR for this

**Comment by RTK** [comment]
I looked into the install script and found out, that the option is already supporting by adding

chromedriver_skip_install=true

into the .npmrc file. I will create a PR that adds this information to the readme file.
