### ISSUE TITLE
Cannot be proxied to Espresso server on Appium 1.20.2

### ISSUE THREAD

**Issue by fjrKurniawan** [appium/appium#15226]
Hello,

After updating the Appium version to 1.20.2, I’m getting error espresso instrumentation crashed if I get only failed test.

> Original error: Could not proxy. Proxy error: 'POST /wd/hub/session/66e82c3c-f131-45d0-bb8b-008fe7802899/element' cannot be proxied to Espresso server because the instrumentation process has crashed.

But, if I tried using Appium **1.18.2** this issue is not happening.

This is for the Appium.log:
https://gist.github.com/fjrKurniawan/a10cf0b00efaf40a04f86ecd48745945

Thanks for the help.

**Comment by mykola-mokhnach** [comment]
This happens because the client code is calling the `reset` endpoint. Consider quitting and opening a new session instead

**Comment by fjrKurniawan** [comment]
Thanks @mykola-mokhnach! Remove `resetApp()` then using `closeApp()` and `launchApp()`
