### ISSUE TITLE
Appium 1.20.2 not inspecting Azure active directory library page for Android

### ISSUE THREAD

**Issue by rajarlm007** [appium/appium#15222]
## The problem

Appium 1.20.2 unable to inspects objects for Azure active directory library(**com.microsoft.aad:adal:3.0.2**) login page for Android
![AppiumLoginObjectsIssue_Android - Copy](https://user-images.githubusercontent.com/45087154/112438624-2022c280-8d6e-11eb-95a5-18dbb04f9867.png)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): 12.8.1
* Mobile platform/version under test: Android 11.0
* Real device or emulator/simulator: Real device and Emulator
* Appium CLI or Appium.app|exe: Desktop

## Details

Using  Azure active directory library(**com.microsoft.aad:adal:3.0.2**) login page for Android. When try to inspect from Appium desktop and not supporting to identify object. Please find attached screenshot for the object hierarchy displayed.

Same It was working for lower version of ADAL.

**Comment by mykola-mokhnach** [comment]
UiAutomator2 only shows elements which are accessible. Make sure these elements are accessible with your developer. You could also try to switch to a web view context In case the control is a part of a web view.

**Comment by rajarlm007** [comment]
Thanks for your support....
I have tried to change the context but throwing following error even I did used latest chromedriver.exe

**Call to 'context' failed
[context("WEBVIEW_chrome")] Error response status: 35 Selenium error: No such context found.**

But in Appium logs exist both context,
[AndroidDriver] Found 1 webview: ["WEBVIEW_chrome"]
[AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_chrome"]

Can you give some solution. Thanks.

**Comment by mykola-mokhnach** [comment]
I cannot help much there without the full server log. 

also, make sure the web view itself is debuggable via Chrome remote debugger

**Comment by rajarlm007** [comment]
[appium-server-logs.txt](https://github.com/appium/appium/files/6205167/appium-server-logs.txt)

PFA, I have attached complete Appium desktop logs. My mobile app has hybrid model... Azure Login page only has web view rest all complete app having Native context.

**Comment by mykola-mokhnach** [comment]
From the logs it looks like the web view is not debuggable. Closing as there is nothing more we could help.
