### ISSUE TITLE
org.openqa.selenium.StaleElementReferenceException: Cached elements do not exist in DOM anymore

### ISSUE THREAD

**Issue by chetanJTH** [appium/appium#15225]
## The problem

I am getting errors whenever I am running my test cases. I never get a similar issue before but now I am getting this error across a project.

## Environment

* Appium version: 1.20
* Last Appium version that did not exhibit the issue (if applicable): I didn't get this issue before with the same version
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): 14.15.5
* Npm: 6.14.11 
* Mobile platform/version under test: Android 10
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

GIST: https://gist.github.com/chetanJTH/2b6db2fa123c3100d807a94067adf9a6

## Code To Reproduce Issue [ Good To Have ]

project repo: https://github.com/chetanJTH/Hybrid
run Suite_ParentalControl file and error will generate while execution of test class: Check_Device_SocialHistory

![image](https://user-images.githubusercontent.com/48850556/112592971-da78ff00-8e2c-11eb-828b-c6874ef4979c.png)

**Comment by mykola-mokhnach** [comment]
This exception is the expected one if the referenced element is stale. See the [duplicated](https://github.com/appium/appium/issues/13505) issue for more details.

**Comment by chetanJTH** [comment]
@mykola-mokhnach how to handle this exception?

**Comment by mykola-mokhnach** [comment]
This depends on what your client code is, what the app state is and what you are trying to achieve. Kindly use Appium  forum to ask questions. 

Closed as not an issue

**Comment by chetanJTH** [comment]
@mykola-mokhnach : please help me there : https://discuss.appium.io/t/org-openqa-selenium-staleelementreferenceexception-cached-elements-do-not-exist-in-dom-anymore/33360
