### ISSUE TITLE
While launching app via appium desktop version it throws "Cannot Extract Manifest from the APK, Is it a valid Android Application ?

### ISSUE THREAD

**Issue by pianoqa** [appium/appium#15223]
## The problem
While launching app via appium desktop version it throws "Cannot Extract Manifest from the APK, Is it a valid Android Application ?"

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: Android 10
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
[BaseDriver] Session created with session id: 43b6d97d-c030-4588-b389-25870ebbf4fe
[BaseDriver] Using local app 'D:\Softwares\APK\eStaff-PDT-OTPSKIP-25-03-2021.apk'
[UiAutomator2] Checking whether app is actually present
[ADB] Using 'adb.exe' from 'C:\Users\Windows\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[ADB] Running 'C:\Users\Windows\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 start-server'
[AndroidDriver] Retrieving device list
[ADB] Trying to find a connected android device
[ADB] Getting connected devices
[ADB] Connected devices: [{"udid":"56d0c056","state":"device"}]
[AndroidDriver] Using device: 56d0c056
[ADB] Using 'adb.exe' from 'C:\Users\Windows\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[ADB] Running 'C:\Users\Windows\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 start-server'
[ADB] Setting device id to 56d0c056
[ADB] Running 'C:\Users\Windows\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 56d0c056 shell getprop ro.build.version.sdk'
[ADB] Current device property 'ro.build.version.sdk': 29
[ADB] Getting device platform version
[ADB] Running 'C:\Users\Windows\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 56d0c056 shell getprop ro.build.version.release'
[ADB] Current device property 'ro.build.version.release': 10
[ADB] Device API level: 29
[UiAutomator2] Relaxing hidden api policy
[ADB] Running 'C:\Users\Windows\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 56d0c056 shell 'settings put global hidden_api_policy_pre_p_apps 1;settings put global hidden_api_policy_p_apps 1;settings put global hidden_api_policy 1''
[AndroidDriver] Parsing package and activity from app manifest
[ADB] Error: end of central directory record signature not found
[ADB]     at C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\yauzl\index.js:187:14
[ADB]     at C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\yauzl\index.js:631:5
[ADB]     at C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\fd-slicer\index.js:32:7
[ADB]     at FSReqCallback.wrapper [as oncomplete] (fs.js:477:5)
[UiAutomator2] Deleting UiAutomator2 session
[UiAutomator2] Restoring hidden api policy to the device default configuration
[ADB] Running 'C:\Users\Windows\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 56d0c056 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''
[BaseDriver] Event 'newSessionStarted' logged at 1616671512985 (16:55:12 GMT+0530 (India Standard Time))
[MJSONWP] Encountered internal error running command: Error: Cannot extract a manifest from 'D:\Softwares\APK\eStaff-PDT-OTPSKIP-25-03-2021.apk'. Is it a valid Android application?
[MJSONWP]     at ADB.packageAndLaunchActivityFromManifest (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\android-manifest.js:38:11)
[HTTP] <-- POST /wd/hub/session 500 1896 ms - 259
![Appium Error](https://user-images.githubusercontent.com/81356506/112466075-705c4d80-8d8b-11eb-9f6f-f4ba09df8694.PNG)

Please Help !

**Comment by mykola-mokhnach** [comment]
> [AndroidDriver] Parsing package and activity from app manifest
> [ADB] Error: end of central directory record signature not found

Most likely the application package is corrupted. Nothing we could do there.

**Comment by pianoqa** [comment]
@mykola-mokhnach Thanks for your Response ! Could you kindly brief me in details, So that i can check this with my developer to fix the same. Thanks in advance!

**Comment by mykola-mokhnach** [comment]
APK file is expected to be a valid ZIP archive. Such error usually means the archive is damaged and is thus invalid

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
