### ISSUE TITLE
[Android 11] Chromedriver 73 is getting picked up though latest chromedriver 83 is the only installed one

### ISSUE THREAD

**Issue by rakshitars** [appium/appium#15233]
## The problem

Appium picks up CD 73 during test execution though it spans CD 83 as per logs but it says chrome versions is not supported for chromedriver.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

Detailed logs are available here - https://gist.github.com/rakshitars/ac83ca35eabc41f797df202a7d437c93

Issue happens only on Android device 11 whereas same works fine in other API versions.

@KazuCocoa @mykola-mokhnach Can you please suggest on this?

**Comment by mykola-mokhnach** [comment]
> [AndroidDriver] Not collecting web view details. Details collection might help to make Chromedriver initialization more precise. Use the 'enableWebviewDetailsCollection' cap to turn it on

I assume the log gives a good hint on what could be done

**Comment by mykola-mokhnach** [comment]
Also, the executable there does not get selected automatically - it is provided in capabilities instead. Make sure the correct/matching binary is used there

**Comment by rakshitars** [comment]
@mykola-mokhnach we are giving chromeDriver executable as 83 in the capabilities file, but the server picks a different one, in this case 73.

**Comment by rakshitars** [comment]
@mykola-mokhnach when i checked it manually i get chromedriver version as 86.0.4240.22. We have used CHROMEDRIVER_EXECULTABLE wherein it automatically picks up the compatible chromedriver version for automating chrome. Here in the logs, it picks up CD 83 as its trying to automate chrome of version 83. But later, the server picks a different one.

**Comment by mykola-mokhnach** [comment]
> But later, the server picks a different one.

Could you please point me out to the line in logs where the server does that?

**Comment by rakshitars** [comment]
`[Chromedriver] Set chromedriver binary as: /Users/rakshitars/.m2/repository/webdriver/chromedriver/mac64/83/chromedriver
[debug] [Chromedriver] Killing any old chromedrivers, running: pkill -15 -f "/Users/rakshitars/.m2/repository/webdriver/chromedriver/mac64/83/chromedriver.*--port=8000"
[Chromedriver] No old chromedrivers seem to exist
[debug] [Chromedriver] Cleaning this device's adb forwarded port socket connections: emulator-5554
[debug] [ADB] List forwarding ports
[debug] [ADB] Running '/Users/rakshitars/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --list'
[Chromedriver] Spawning chromedriver with: /Users/rakshitars/.m2/repository/webdriver/chromedriver/mac64/83/chromedriver --url-base=wd/hub --port=8000 --adb-port=5037 --verbose
[debug] [Chromedriver] Chromedriver version: '73.0.3683.20'
[debug] [Chromedriver] Chromedriver v. 73.0.3683.20 does not fully support W3C protocol. Defaulting to MJSONWP`

**Comment by rakshitars** [comment]
```[Chromedriver] Set chromedriver binary as: /Users/rakshitars/.m2/repository/webdriver/chromedriver/mac64/83/chromedriver
[debug] [Chromedriver] Killing any old chromedrivers, running: pkill -15 -f "/Users/rakshitars/.m2/repository/webdriver/chromedriver/mac64/83/chromedriver.*--port=8000"
[Chromedriver] No old chromedrivers seem to exist
[debug] [Chromedriver] Cleaning this device's adb forwarded port socket connections: emulator-5554
[debug] [ADB] List forwarding ports
[debug] [ADB] Running '/Users/rakshitars/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --list'
[Chromedriver] Spawning chromedriver with: /Users/rakshitars/.m2/repository/webdriver/chromedriver/mac64/83/chromedriver --url-base=wd/hub --port=8000 --adb-port=5037 --verbose
[debug] [Chromedriver] Chromedriver version: '73.0.3683.20'
[debug] [Chromedriver] Chromedriver v. 73.0.3683.20 does not fully support W3C protocol. Defaulting to MJSONWP```

**Comment by mykola-mokhnach** [comment]
> [Chromedriver] Spawning chromedriver with: /Users/rakshitars/.m2/repository/webdriver/chromedriver/mac64/83/chromedriver --url-base=wd/hub --port=8000 --adb-port=5037 --verbose

So here it spawns exactly the same binary that was passed to it in capabilities:

>  [debug] [BaseDriver]     "appium:chromedriverExecutable": "/Users/rakshitars/.m2/repository/webdriver/chromedriver/mac64/83/chromedriver",

I don't understand what is wrong there

**Comment by rakshitars** [comment]
Yes. After spawning, it says the chromedriver version as 73.0.3683.20

**Comment by mykola-mokhnach** [comment]
The code just echoes what the binary returns, still not seeing any issues there:

https://github.com/appium/appium-chromedriver/blob/8371f61dbc9d57bb6c01a58c7c19cc9e9766dc69/lib/chromedriver.js#L486

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
