### ISSUE TITLE
Matched JSONWP error code 6 to NoSuchDriverError

### ISSUE THREAD

**Issue by llpan-github** [appium/appium#15238]
## The problem
ios device start session report errors  《Matched JSONWP error code 6 to NoSuchDriverError》 

## Environment

* Appium 1.20.2
* MAC 10.15.7
* Node.js v13.14.0
* Npm  v6.14.4  Yarn v1.22.5 
* Mobile :iphone se 13.7
* Appium  app

## Details
Desired Capabilities
{
  "automationName": "XCUITest",
  "platformName": "ios",
  "udid": "00008030-000644A80285802E",
  "platformVersion": "13.7",
  "deviceName": "Ly的iPhone",
  " bundleId": "xxxx"
}

## Link to Appium logs

[info] [35m[Appium][39m Welcome to Appium v1.20.2
[info] [35m[Appium][39m Non-default server args:
[info] [35m[Appium][39m   relaxedSecurityEnabled: true
[info] [35m[Appium][39m   allowInsecure: {
[info] [35m[Appium][39m   }
[info] [35m[Appium][39m   denyInsecure: {
[info] [35m[Appium][39m   }
[info] [35m[Appium][39m Appium REST http interface listener started on 0.0.0.0:4723[info] [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/sessions[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[GENERIC][39m Calling AppiumDriver.getSessions() with args: []
[debug] [35m[GENERIC][39m Responding to client with driver.getSessions() result: []
[info] [35m[HTTP][39m [37m<-- GET /wd/hub/sessions [39m[32m200[39m [90m5 ms - 40[39m
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{"desiredCapabilities":{" bundleId":"com.yunzhanghu.topping","automationName":"XCUITest","deviceName":"Ly的iPhone","platformName":"ios","platformVersion":"13.7","udid":"00008030-000644A80285802E","newCommandTimeout":0,"connectHardwareKeyboard":true}}[39m
[debug] [35m[MJSONWP][39m Calling AppiumDriver.createSession() with args: [{" bundleId":"com.yunzhanghu.topping","automationName":"XCUITest","deviceName":"Ly的iPhone","platformName":"ios","platformVersion":"13.7","udid":"00008030-000644A80285802E","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1617156852729 (10:14:12 GMT+0800 (中国标准时间))
[info] [35m[Appium][39m Appium v1.20.2 creating new XCUITestDriver (v3.33.1) session
[info] [35m[Appium][39m Applying relaxed security to 'XCUITestDriver' as per server command line argument. All insecure features will be enabled unless explicitly disabled by --deny-insecure
[debug] [35m[BaseDriver][39m Creating session with MJSONWP desired capabilities: {
[debug] [35m[BaseDriver][39m   " bundleId": "com.yunzhanghu.topping",
[debug] [35m[BaseDriver][39m   "automationName": "XCUITest",
[debug] [35m[BaseDriver][39m   "deviceName": "Ly的iPhone",
[debug] [35m[BaseDriver][39m   "platformName": "ios",
[debug] [35m[BaseDriver][39m   "platformVersion": "13.7",
[debug] [35m[BaseDriver][39m   "udid": "00008030-000644A80285802E",
[debug] [35m[BaseDriver][39m   "newCommandTimeout": 0,
[debug] [35m[BaseDriver][39m   "connectHardwareKeyboard": true
[debug] [35m[BaseDriver][39m }
[warn] [35m[BaseDriver][39m The following capabilities were provided, but are not recognized by Appium:
[warn] [35m[BaseDriver][39m    bundleId
[info] [35m[XCUITest][39m The desired capabilities include neither an app nor a bundleId. WebDriverAgent will be started without the default app
[info] [35m[BaseDriver][39m Session created with session id: e78d02ec-c14e-4ddb-bbd4-ed4aa4a271ae[debug] [35m[XCUITest][39m Current user: 'llpan'
[debug] [35m[XCUITest][39m Available devices: 00008030-000644A80285802E
[debug] [35m[XCUITest][39m Creating iDevice object with udid '00008030-000644A80285802E'
[info] [35m[XCUITest][39m Determining device to run tests on: udid: '00008030-000644A80285802E', real device: true
[debug] [35m[BaseDriver][39m Event 'xcodeDetailsRetrieved' logged at 1617156853652 (10:14:13 GMT+0800 (中国标准时间))
[debug] [35m[BaseDriver][39m Event 'appConfigured' logged at 1617156853653 (10:14:13 GMT+0800 (中国标准时间))
[debug] [35m[BaseDriver][39m Event 'resetStarted' logged at 1617156853653 (10:14:13 GMT+0800 (中国标准时间))
[debug] [35m[XCUITest][39m Reset: running ios real device reset flow
[debug] [35m[BaseDriver][39m Event 'resetComplete' logged at 1617156853653 (10:14:13 GMT+0800 (中国标准时间))
[info] [35m[WebDriverAgent][39m Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent'
[info] [35m[WebDriverAgent][39m Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'[debug] [35m[XCUITest][39m Crash reports root '/Users/llpan/Library/Logs/CrashReporter/MobileDevice/Ly的iPhone' does not exist. Got nothing to gather.
[debug] [35m[BaseDriver][39m Event 'logCaptureStarted' logged at 1617156853861 (10:14:13 GMT+0800 (中国标准时间))
[info] [35m[XCUITest][39m Setting up real device
[debug] [35m[WebDriverAgent][39m No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[info] [35m[DevCon Factory][39m Requesting connection for device 00008030-000644A80285802E on local port 8100, device port 8100
[debug] [35m[DevCon Factory][39m Cached connections count: 0
[info] [35m[DevCon Factory][39m Successfully requested the connection for 00008030-000644A80285802E:8100
[debug] [35m[XCUITest][39m Starting WebDriverAgent initialization with the synchronization key 'XCUITestDriver'
[debug] [35m[WD Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[WD Proxy][39m Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[debug] [35m[WD Proxy][39m Got response with status 200: {"value":{"state":"success","os":{"name":"iOS","version":"13.7"},"ios":{"simulatorVersion":"13.7","ip":"192.168.110.136"},"build":{"time":"Aug 21 2020 14:15:29"}},"sessionId":"11988B01-DF61-4A57-9730-7748EB087427","status":0}
[debug] [35m[WebDriverAgent][39m Upgrade timestamp of the currently bundled WDA: 1612946545000
[debug] [35m[WebDriverAgent][39m Upgrade timestamp of the WDA on the device: undefined
[info] [35m[WebDriverAgent][39m Will reuse previously cached WDA instance at 'http://127.0.0.1:8100/'. Set the wdaLocalPort capability to a value different from 8100 if this is an undesired behavior.
[debug] [35m[XCUITest][39m Trying to start WebDriverAgent 1 times with 10000ms interval
[debug] [35m[XCUITest][39m These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
[debug] [35m[BaseDriver][39m Event 'wdaStartAttempted' logged at 1617156853993 (10:14:13 GMT+0800 (中国标准时间))
[info] [35m[WebDriverAgent][39m Using provided WebdriverAgent at 'http://127.0.0.1:8100/'
[debug] [35m[WD Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[WD Proxy][39m Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[debug] [35m[WD Proxy][39m Got response with status 200: {"value":{"state":"success","os":{"name":"iOS","version":"13.7"},"ios":{"simulatorVersion":"13.7","ip":"192.168.110.136"},"build":{"time":"Aug 21 2020 14:15:29"}},"sessionId":"11988B01-DF61-4A57-9730-7748EB087427","status":0}
[debug] [35m[BaseDriver][39m Event 'wdaSessionAttempted' logged at 1617156854004 (10:14:14 GMT+0800 (中国标准时间))
[debug] [35m[XCUITest][39m Sending createSession command to WDA
[debug] [35m[WD Proxy][39m Matched '/session' to command name 'createSession'
[debug] [35m[WD Proxy][39m Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}[debug] [35m[WD Proxy][39m Got response with status 200: {"value":{"sessionId":"DCEC0EAD-00EF-40B0-A8CF-F3C64C484251","capabilities":{"device":"iphone","browserName":" ","sdkVersion":"13.7","CFBundleIdentifier":"com.apple.springboard"}},"sessionId":"DCEC0EAD-00EF-40B0-A8CF-F3C64C484251","status":0}
[info] [35m[WD Proxy][39m Determined the downstream protocol as 'MJSONWP'
[debug] [35m[BaseDriver][39m Event 'wdaSessionStarted' logged at 1617156854112 (10:14:14 GMT+0800 (中国标准时间))
[debug] [35m[BaseDriver][39m Event 'wdaStarted' logged at 1617156854112 (10:14:14 GMT+0800 (中国标准时间))
[info] [35m[XCUITest][39m Skipping setting of the initial display orientation. Set the "orientation" capability to either "LANDSCAPE" or "PORTRAIT", if this is an undesired behavior.
[debug] [35m[BaseDriver][39m Event 'orientationSet' logged at 1617156854113 (10:14:14 GMT+0800 (中国标准时间))
[debug] [35m[BaseDriver][39m The value of 'elementResponseAttributes' setting did not change. Skipping the update for it
[debug] [35m[BaseDriver][39m The value of 'shouldUseCompactResponses' setting did not change. Skipping the update for it
[info] [35m[Appium][39m New XCUITestDriver session created successfully, session e78d02ec-c14e-4ddb-bbd4-ed4aa4a271ae added to master session list
[debug] [35m[BaseDriver][39m Event 'newSessionStarted' logged at 1617156854114 (10:14:14 GMT+0800 (中国标准时间))
[debug] [35m[MJSONWP (e78d02ec)][39m Cached the protocol value 'MJSONWP' for the new session e78d02ec-c14e-4ddb-bbd4-ed4aa4a271ae
[debug] [35m[MJSONWP (e78d02ec)][39m Responding to client with driver.createSession() result: {"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false," bundleId":"com.yunzhanghu.topping","automationName":"XCUITest","deviceName":"Ly的iPhone","platformName":"ios","platformVersion":"13.7","udid":"00008030-000644A80285802E","newCommandTimeout":0,"connectHardwareKeyboard":true}
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[32m200[39m [90m1389 ms - 495[39m
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/session/e78d02ec-c14e-4ddb-bbd4-ed4aa4a271ae/contexts[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[MJSONWP (e78d02ec)][39m Calling AppiumDriver.getContexts() with args: ["e78d02ec-c14e-4ddb-bbd4-ed4aa4a271ae"]
[debug] [35m[XCUITest][39m Executing command 'getContexts'
[debug] [35m[XCUITest][39m Getting list of available contexts
[debug] [35m[iOS][39m Retrieving contexts and views
[error] [35m[XCUITest][39m Cannot enter web frame without a bundle ID
[debug] [35m[MJSONWP (e78d02ec)][39m Encountered internal error running command: Error: Cannot enter web frame without a bundle ID
[debug] [35m[MJSONWP (e78d02ec)][39m     at Object.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:94:35)
[debug] [35m[MJSONWP (e78d02ec)][39m     at XCUITestDriver.listWebFrames (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/context.js:194:9)
[debug] [35m[MJSONWP (e78d02ec)][39m     at XCUITestDriver.getContextsAndViews (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-ios-driver/lib/commands/context.js:160:29)
[debug] [35m[MJSONWP (e78d02ec)][39m     at XCUITestDriver.getContexts (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/context.js:247:31)
[debug] [35m[MJSONWP (e78d02ec)][39m     at commandExecutor (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:334:9)
[debug] [35m[MJSONWP (e78d02ec)][39m     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/async-lock/lib/index.js:129:12
[debug] [35m[MJSONWP (e78d02ec)][39m     at AsyncLock._promiseTry (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/async-lock/lib/index.js:253:31)
[debug] [35m[MJSONWP (e78d02ec)][39m     at exec (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/async-lock/lib/index.js:128:9)
[debug] [35m[MJSONWP (e78d02ec)][39m     at AsyncLock.acquire (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/async-lock/lib/index.js:144:3)
[debug] [35m[MJSONWP (e78d02ec)][39m     at XCUITestDriver.executeCommand (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:347:39)
[debug] [35m[MJSONWP (e78d02ec)][39m     at XCUITestDriver.executeCommand (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:730:24)
[debug] [35m[MJSONWP (e78d02ec)][39m     at AppiumDriver.executeCommand (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/lib/appium.js:547:36)
[debug] [35m[MJSONWP (e78d02ec)][39m     at processTicksAndRejections (internal/process/task_queues.js:85:5)
[debug] [35m[MJSONWP (e78d02ec)][39m     at asyncHandler (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:297:21)
[info] [35m[HTTP][39m [37m<-- GET /wd/hub/session/e78d02ec-c14e-4ddb-bbd4-ed4aa4a271ae/contexts [39m[31m500[39m [90m72 ms - 213[39m
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/session/e78d02ec-c14e-4ddb-bbd4-ed4aa4a271ae/source[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[MJSONWP (e78d02ec)][39m Calling AppiumDriver.getPageSource() with args: ["e78d02ec-c14e-4ddb-bbd4-ed4aa4a271ae"]
[debug] [35m[XCUITest][39m Executing command 'getPageSource'
[debug] [35m[WD Proxy][39m Matched '/source' to command name 'getPageSource'
[debug] [35m[WD Proxy][39m Proxying [GET /source] to [GET http://127.0.0.1:8100/session/DCEC0EAD-00EF-40B0-A8CF-F3C64C484251/source] with no body
[info] [35m[WD Proxy][39m Got response with status 400: {"value":{"message":"Unknown source format 'xml'. Only (\n    xml,\n    json,\n    description\n) source formats are supported."},"sessionId":"DCEC0EAD-00EF-40B0-A8CF-F3C64C484251","status":6}
[debug] [35m[MJSONWP][39m Matched JSONWP error code 6 to NoSuchDriverError
[debug] [35m[MJSONWP (e78d02ec)][39m Encountered internal error running command: NoSuchDriverError: Unknown source format 'xml'. Only (
[debug] [35m[MJSONWP (e78d02ec)][39m     xml,
[debug] [35m[MJSONWP (e78d02ec)][39m     json,
[debug] [35m[MJSONWP (e78d02ec)][39m     description
[debug] [35m[MJSONWP (e78d02ec)][39m ) source formats are supported.
[debug] [35m[MJSONWP (e78d02ec)][39m     at errorFromMJSONWPStatusCode (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:764:12)
[debug] [35m[MJSONWP (e78d02ec)][39m     at ProxyRequestError.getActualError (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:661:14)
[debug] [35m[MJSONWP (e78d02ec)][39m     at JWProxy.command (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:273:19)
[debug] [35m[MJSONWP (e78d02ec)][39m     at processTicksAndRejections (internal/process/task_queues.js:85:5)
[info] [35m[HTTP][39m [37m<-- GET /wd/hub/session/e78d02ec-c14e-4ddb-bbd4-ed4aa4a271ae/source [39m[33m404[39m [90m25 ms - 192[39m
[info] [35m[HTTP][39m [90m[39m[debug] [35m[WebDriverAgent][39m Parsed BUILD_DIR configuration value: '/Users/llpan/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Build/Products'
[debug] [35m[WebDriverAgent][39m Got derived data root: '/Users/llpan/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp'[info] [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/sessions[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[GENERIC][39m Calling AppiumDriver.getSessions() with args: []
[debug] [35m[GENERIC][39m Responding to client with driver.getSessions() result: [{"id":"e78d02ec-c14e-4ddb-bbd4-ed4aa4a271ae","capabilities":{" bundleId":"com.yunzhanghu.topping","automationName":"XCUITest","deviceName":"Ly的iPhone","platformName":"ios","platformVersion":"13.7","udid":"00008030-000644A80285802E","newCommandTimeout":0,"connectHardwareKeyboard":true}}]
[info] [35m[HTTP][39m [37m<-- GET /wd/hub/sessions [39m[32m200[39m [90m1 ms - 328[39m
[info] [35m[HTTP][39m [90m[39m

**Comment by mykola-mokhnach** [comment]
It looks like the WebDriverAgent version running on the device under test is either wrong or outdated. Please clear the Xcode caches and make sure the recent WDA binary is installed on the device

**Comment by llpan-github** [comment]
> It looks like the WebDriverAgent version running on the device under test is either wrong or outdated. Please clear the Xcode caches and make sure the recent WDA binary is installed on the device

thanks the WebDriverAgent version is wrong
