### ISSUE TITLE
Session not created with io.appium.uiautomator2.common.exceptions.NoSuchDriverException

### ISSUE THREAD

**Issue by bart-tricentis** [appium/appium#15239]
## The problem

Cannot start an android session

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2
* Last Appium version that did not exhibit the issue (if applicable): 1.18.2
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): 12.18.2
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Android 9(emulator) Android 10,11 real device
* Real device or emulator/simulator: both
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

[log.txt](https://github.com/appium/appium/files/6234162/log.txt)

**Comment by mykola-mokhnach** [comment]
This error is happening because `shouldUseCompactResponses` is a setting, not a capability. The error message itself is not very helpful, although this has already been addressed in appium@beta
