### ISSUE TITLE
Native elements in a hybrid app are not found by Appium 

### ISSUE THREAD

**Issue by aryalakshmi** [appium/appium#15234]
## The problem

I am using Robot Framework + Python for my app .
After succesfully opening the app, I see that the native popups cannot be found even though i am in the Native Context
This issue is happening inconsistently. [Worked with same set of capabilities twice in between ]

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.20.0
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: mac OS Big Sur
* Node.js version (unless using Appium.app|exe):v15.12.0
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: iOS 14.4.1
* Real device or emulator/simulator: Real Device / iPhone8
* Appium CLI or Appium.app|exe: Both doesnt work

## Details

Both Appium Cli and Appium Desktop is tried, both shows same issue 

[debug] [W3C (b7a1aa9f)] Calling AppiumDriver.findElements() with args: ["xpath","//XCUIElementTypeButton[@name=“OK”]","b7a1aa9f-bb87-421e-b95b-fe8f9517cdf3"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [WD Proxy] Matched '/elements' to command name 'findElements'
[debug] [WD Proxy] Proxying [POST /elements] to [POST http://127.0.0.1:8100/session/EEF1E38C-F1CC-4702-9188-4D18C634FAD8/elements] with body: {"using":"xpath","value":"//XCUIElementTypeButton[@name=“OK”]"}
[WD Proxy] Got response with status 400: {"value":{"error":"invalid selector","message":"Cannot evaluate results for XPath expression \"//XCUIElementTypeButton[@name=“OK”]\"","traceback":"(\n\t0   CoreFoundation                      0x0000000186e319ec F3021642-E3C0-33F8-9911-DD303A6056D0 + 1157612\n\t1   libobjc.A.dylib                     0x000000019b1b7b54 objc_exception_throw + 56\n\t2   WebDriverAgentLib                   0x0000000102d07200 +[FBXPath xmlStringWithRootElement:excludingAttributes:] + 0\n\t3   WebDriverAgentLib                   0x0000000102d07534 +[FBXPath matchesWithRootElement:forQuery:] + 480\n\t4   WebDriverAgentLib                   0x0000000102d2fde0 -[XCUIElement(FBFind) fb_descendantsMatchingXPathQuery:shouldReturnAfterFirstMatch:] + 172\n\t5   WebDriverAgentLib                   0x0000000102d714f8 +[FBFindElementCommands elementsUsing:withValue:under:shouldReturnAfterFirstMatch:] + 828\n\t6   WebDriverAgentLib                   0x0000000102d703e4 +[FBFindElementCommands handleFindElements:] + 332\n\t7   WebDriverAgentL...
[debug] [W3C] Matched W3C error code 'invalid selector' to InvalidSelectorError
[debug] [W3C (b7a1aa9f)] Responding to client with driver.findElements() result: []

## Link to Appium logs

https://gist.github.com/aryalakshmi/f0bd615eee83a683af32b347d65a5610

## Code To Reproduce Issue [ Good To Have ]

    FOR    ${a}    IN    @{counter}
        Comment    Run keyword and Ignore Error    Remove Application    com.nokia.wifi
        ${status}=    Run Keyword And Return Status    Open Application    http://localhost:4723/wd/hub    platformName=${platform}    platformVersion=${pfversion}    deviceName='iPhone'    autoWebview=true    newCommandTimeout=1200    udid=${udid}    xcodeOrgId=${xcodeOrgId}    xcodeSigningId=iPhone Developer    fullReset=true    bundleId=com.nokia.wifi    app=${mobile_app_path}/${ipa_file}
        Exit For Loop If    '${status}' == 'True'
        Should Be True    ${status}
    END
    Sleep    ${T_ModerateSleep}
    @{context}=    Get Contexts
    ${context0}=    Get From List    ${context}    0
    ${context1}=    Get From List    ${context}    1
    AppiumLibrary.Switch To Context    ${context0}
    AppiumLibrary.Get Current Context
    Sleep    5s
    AppiumLibrary.Start Screen Recording    timeLimit=600s
    ${Status}    Run keyword and return status    AppiumLibrary.Click Element    //XCUIElementTypeButton[@name=“OK”]
    Sleep    5s
    ${Status}    Run keyword and return status    AppiumLibrary.Click Element    //XCUIElementTypeButton[@name=“Allow”]
    Sleep    ${T_NavSleep}
    AppiumLibrary.Switch To Context    ${context1}
    sleep    2s
    Sleep    ${T_NavSleep}

**Comment by mykola-mokhnach** [comment]
The above error is about the invalid selector and it is expected, since the given xpath is invalid (e.g. wrong quite characters are passed)

**Comment by aryalakshmi** [comment]
Thankyou.. the quotes were getting altered in macbook. Worked on copying the selector from appium inspector to Gmail window and then to the RIDE.
