### ISSUE TITLE
Issue in Appium Testcases execution in firefox browser

### ISSUE THREAD

**Issue by PriyankaKeer** [appium/appium#15249]
## The problem

Issue in Appium Testcases execution in firefox browser

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2
* Last Appium version that did not exhibit the issue (if applicable):NA
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): 6.14.8
* Npm or Yarn package manager: npm
* Mobile platform/version under test: R(API 30)
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Appium CLI 

## Details

Unable to execute appium testcases in Firefox browser, though installation of firefox browser is done in emulator and desired capabilities are mentioned.

## Link to Appium logs

[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:5200/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:5200
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:5200/status] with no body
[debug] [WD Proxy] Got response with status 200: {"value":{"message":"","ready":true}}
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:5200/session] with body: {"capabilities":{"firstMatch":[{}],"alwaysMatch":{"browserName":"firefox","platformName":"moz:firefoxoptions"}}}
[WD Proxy] Got response with status 500: {"value":{"error":"session not created","message":"Unable to find a matching set of capabilities","stacktrace":""}}
[debug] [W3C] Matched W3C error code 'session not created' to SessionNotCreatedError
[GeckoDriver] Ending Gecko Driver session
[GeckoDriverServer] geckodriver.exe has exited with code null, signal SIGTERM
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1617605896466 (12:28:16 GMT+0530 (India Standard Time))
[debug] [MJSONWP] Encountered internal error running command: SessionNotCreatedError: A new session could not be created. Details: Unable to find a matching set of capabilities
[debug] [MJSONWP]     at errorFromW3CJsonCode (C:\Users\XXX\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:780:25)
[debug] [MJSONWP]     at ProxyRequestError.getActualError (C:\Users\XXX\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:663:14)
[debug] [MJSONWP]     at GeckoProxy.command (C:\Users\XXX\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:273:19)
[debug] [MJSONWP]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[debug] [MJSONWP]     at GeckoDriverServer.start (C:\Users\XXX\AppData\Roaming\npm\node_modules\appium\node_modules\appium-geckodriver\lib\gecko.js:185:5)
[debug] [MJSONWP]     at GeckoDriver.createSession (C:\Users\XXX\AppData\Roaming\npm\node_modules\appium\node_modules\appium-geckodriver\lib\driver.js:59:7)
[debug] [MJSONWP]     at AppiumDriver.createSession (C:\Users\XXX\AppData\Roaming\npm\node_modules\appium\lib\appium.js:371:35)
[HTTP] <-- POST /wd/hub/session 500 1224 ms - 143
[HTTP]

## Code To Reproduce Issue [ Good To Have ]

Firefox is installed in Emulator but executing Appium testcases in Firefox browser is creating the above issue. 

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

public class TestCase1Firefox {
    static WebDriver driver;        
    DesiredCapabilities capabilities;   
    @Before
    public void setUp() throws MalformedURLException{
        capabilities= new DesiredCapabilities();
        capabilities.setCapability(CapabilityType.BROWSER_NAME, "firefox");
        capabilities.setCapability("platformName","Android");
        capabilities.setCapability("automationName","Gecko");
        JSONObject proxyobj=new JSONObject();
        proxyobj.put("androidPackage","org.mozilla.firefox");
        proxyobj.put("androidDeviceSerial", "emulator-5554");
        capabilities.setCapability("moz:firefoxOptions",proxyobj);       
        capabilities.setCapability("deviceName","sdk_gphone_x86");
        capabilities.setCapability(CapabilityType.VERSION, "11");
    }
    @Test
    public void testCal() throws Exception {
        driver = new RemoteWebDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
        driver.get("https://www.amazon.com");
        System.out.println("INSIDE TEST METHOD");
    
    } 
    @After
    public void teardown(){
        //close the app
        driver.quit();
    }
}

Thanks in Advance!

**Comment by mykola-mokhnach** [comment]
Please provide the full server log. To me it looks like the client library either corrupts the given capabilities or they are initially incorrect, which leads to the expected session creation failure:

> Proxying [POST /session] to [POST http://127.0.0.1:5200/session] with body: {"capabilities":{"firstMatch":[{}],"alwaysMatch":{"browserName":"firefox","platformName":"moz:firefoxoptions"}}}

**Comment by PriyankaKeer** [comment]
> Please provide the full server log. To me it looks like the client library either corrupts the given capabilities or they are initially incorrect, which leads to the expected session creation failure:
> 
> > Proxying [POST /session] to [POST http://127.0.0.1:5200/session] with body: {"capabilities":{"firstMatch":[{}],"alwaysMatch":{"browserName":"firefox","platformName":"moz:firefoxoptions"}}}

Attaching the error logs below, please check.

[AppiumServerLog.txt](https://github.com/appium/appium/files/6257713/AppiumServerLog.txt)
[EclipseError.txt](https://github.com/appium/appium/files/6257716/EclipseError.txt)

**Comment by mykola-mokhnach** [comment]
> [debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:5200/session] with body: {"capabilities":{"firstMatch":[{}],"alwaysMatch":{"browserName":"firefox","moz:firefoxOptions":{"androidDeviceSerial":"emulator-5554","androidPackage":"org.mozilla.firefox"},"platformName":"android"}}}
[WD Proxy] Got response with status 500: {"value":{"error":"session not created","message":"Unable to find a matching set of capabilities","stacktrace":""}}

It seems like Geckodriver does not like the provided platform name. Try `windows` instead

**Comment by PriyankaKeer** [comment]
> > [debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:5200/session] with body: {"capabilities":{"firstMatch":[{}],"alwaysMatch":{"browserName":"firefox","moz:firefoxOptions":{"androidDeviceSerial":"emulator-5554","androidPackage":"org.mozilla.firefox"},"platformName":"android"}}}
> > [WD Proxy] Got response with status 500: {"value":{"error":"session not created","message":"Unable to find a matching set of capabilities","stacktrace":""}}
> 
> It seems like Geckodriver does not like the provided platform name. Try `windows` instead

Tried, but still the same issue :(

**Comment by mykola-mokhnach** [comment]
I cannot help much there. Check the geckodriver [documentation](https://developer.mozilla.org/en-US/docs/Web/WebDriver/Capabilities/firefoxOptions) or create a question at their forum.

**Comment by PriyankaKeer** [comment]
Can it be possible if any format of desired capabilities are provided for testcases execution in firefox?

**Comment by mykola-mokhnach** [comment]
Do you mean you'd like to see some examples?

- https://github.com/appium/appium-geckodriver/blob/master/test/functional/mobile-driver-e2e-specs.js
- https://github.com/mozilla/geckodriver/files/5531147/gecko.txt

**Comment by PriyankaKeer** [comment]
> Do you mean you'd like to see some working examples?
> 
> * https://github.com/appium/appium-geckodriver/blob/master/test/functional/mobile-driver-e2e-specs.js
> * https://github.com/mozilla/geckodriver/files/5531147/gecko.txt

This looks like Firefox Application automation. But, we need to execute appium testcases of our responsive application in firefox browser in emulator
Can you provide working example for this?

**Comment by mykola-mokhnach** [comment]
These examples are for Firefox browser running inside of Android Emulator

**Comment by PriyankaKeer** [comment]
> These examples are for Firefox browser running inside of Android Emulator

Getting below error. Please suggest

[debug] [WD Proxy] Got response with status 200: {"sessionId":"4eaea0a4-41cc-4d89-b483-fec4bfe5fbb6","value":{"height":1977,"width":1080}}
[Appium] New AndroidUiautomator2Driver session created successfully, session 4b6301c2-ea21-4434-9eab-8f29e0e270f7 added to master session list
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1617691885536 (12:21:25 GMT+0530 (India Standard Time))
[debug] [W3C (4b6301c2)] Cached the protocol value 'W3C' for the new session 4b6301c2-ea21-4434-9eab-8f29e0e270f7
[debug] [W3C (4b6301c2)] Responding to client with driver.createSession() result: {"capabilities":{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"browserName":"MozillaFirefox","platformName":"android","deviceName":"Pixel_4_API_30","platformVersion":"11"},"browserName":"MozillaFirefox","platformName":"android","deviceName":"emulator-5554","platformVersion":"11","deviceUDID":"emulator-5554","deviceApiLevel":30,"deviceScreenSize":"1080x2280","deviceScreenDensity":440,"deviceModel":"sdk_gphone_x86","deviceManufacturer":"Google","pixelRatio":2.75,"statBarHeight":135,"viewportRect":{"left":0,"top":135,"width":1080,"height":1842}}}
[HTTP] <-- POST /wd/hub/session 200 7243 ms - 770
[HTTP]
[HTTP] --> POST /wd/hub/session/4b6301c2-ea21-4434-9eab-8f29e0e270f7/url
[HTTP] {"url":"https:www.google.com"}
[debug] [W3C (4b6301c2)] Calling AppiumDriver.setUrl() with args: ["https:www.google.com","4b6301c2-ea21-4434-9eab-8f29e0e270f7"]
[debug] [W3C (4b6301c2)] Encountered internal error running command: **Error: URI and package arguments are required
[debug] [W3C (4b6301c2)]     at ADB.startUri** (C:\Users\XXX\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\lib\tools\apk-utils.js:70:11)
[debug] [W3C (4b6301c2)]     at AndroidUiautomator2Driver.commands.setUrl (C:\Users\XXX\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\commands\general.js:187:18)
[debug] [W3C (4b6301c2)]     at commandExecutor (C:\Users\XXX\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\driver.js:334:9)
[debug] [W3C (4b6301c2)]     at C:\Users\XXX\AppData\Roaming\npm\node_modules\appium\node_modules\async-lock\lib\index.js:129:12
[debug] [W3C (4b6301c2)]     at AsyncLock._promiseTry (C:\Users\XXX\AppData\Roaming\npm\node_modules\appium\node_modules\async-lock\lib\index.js:253:31)
[debug] [W3C (4b6301c2)]     at exec (C:\Users\XXX\AppData\Roaming\npm\node_modules\appium\node_modules\async-lock\lib\index.js:128:9)
[debug] [W3C (4b6301c2)]     at AsyncLock.acquire (C:\Users\XXX\AppData\Roaming\npm\node_modules\appium\node_modules\async-lock\lib\index.js:144:3)
[debug] [W3C (4b6301c2)]     at AndroidUiautomator2Driver.executeCommand (C:\Users\XXX\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\driver.js:347:39)
[debug] [W3C (4b6301c2)]     at AppiumDriver.executeCommand (C:\Users\XXX\AppData\Roaming\npm\node_modules\appium\lib\appium.js:547:36)
[debug] [W3C (4b6301c2)]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[debug] [W3C (4b6301c2)]     at asyncHandler (C:\Users\XXX\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:297:21)
[HTTP] <-- POST /wd/hub/session/4b6301c2-ea21-4434-9eab-8f29e0e270f7/url 500 187 ms - 641

**Comment by mykola-mokhnach** [comment]
I assume it is necessary first for you to understand what you need. The above log comes from UiAutomator2 driver, which has nothing to do with Geckodriver. I can only help with possible issues. Kindly use Appium forum to ask questions

**Comment by PriyankaKeer** [comment]
> I assume it is necessary first for you to understand what you need. The above log comes from UiAutomator2 driver, which has nothing to do with Geckodriver. I can only help with possible issues. Kindly use Appium forum to ask questions

Initially we tried with Automation name as "Gecko" in desired capabilities for which we faced error(logs were shared in the beginning). Later as shared in the working example, automation name capability isn't mentioned, on trying that it is opening UI automation driver and still giving error.

Will seek support from Appium forum

thanks for the support

**Comment by mykola-mokhnach** [comment]
Yep, that error is coming from geckdriver itself, Appium is just a wrapper for it, so we cannot help much there. 

Regarding the UIA2 driver - it interacts with the system accessibility and the hybrid mode only supports Chrome. Unfortunately there is no direct way to interact with Firefox browser except of via accessibility elements.

Closed as not an issue
