### ISSUE TITLE
error: Cannot start the 'com.samsung.android.app.notes' application

### ISSUE THREAD

**Issue by rdas063** [appium/appium#15247]
from appium import webdriver
desired_cap ={
    "platformName": "Android",
    "platformVersion": "11.0",
    "deviceName": "R3CN80DGFMD",
    "appPackage": "com.samsung.android.app.notes",
    "appWaitActivity": "",
    "automationName": "uiautomator2",
    "noReset": "true"
}

webdriver.Remote("http://localhost:4723/wd/hub",desired_cap)

Full ERROR:   selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.samsung.android.app.notes' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\rdas0\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s R3CN80DGFMD shell am start -W -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' exited with code 1'; Stderr: 'Error: Intent matches multiple activities; can't stop: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 }'; Code: '1'

[NOTE]:
the app is preinstalled in device

[appium-server-logs.txt](https://github.com/appium/appium/files/6254917/appium-server-logs.txt)

**Comment by mykola-mokhnach** [comment]
What exactly did you try from the troubleshooting document above?

**Comment by rdas063** [comment]
I just wanted to run the "Samsung Notes" application in real device

**Comment by mykola-mokhnach** [comment]
> I just wanted to run the "Samsung Notes" application in real device

This is great, but what exactly did you try?

**Comment by rdas063** [comment]
I want to automate some testing in Samsung Notes

**Comment by rdas063** [comment]
I tried with below code:

from appium import webdriver
desired_cap ={
    "platformName": "Android",
    "platformVersion": "11",
    "deviceName": "R3CN80DGFMD",
    "app": "C:\\Users\\rdas0\\Downloads\\Samsung Notes.apk",
    "appWaitActivity": "",
    "appPackage": "",
    "automationName": "uiautomator2",
}
# create the driver instance

driver=webdriver.Remote("http://localhost:4723/wd/hub",desired_cap)

**Comment by rdas063** [comment]
getting below:

F:\python.exe "C:/Users/rdas0/PycharmProjects/appum testing/main.py"
Traceback (most recent call last):
  File "C:\Users\rdas0\PycharmProjects\appum testing\main.py", line 13, in <module>
    driver=webdriver.Remote("http://localhost:4723/wd/hub",desired_cap)
  File "F:\lib\site-packages\appium\webdriver\webdriver.py", line 155, in __init__
    super().__init__(
  File "F:\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "F:\lib\site-packages\appium\webdriver\webdriver.py", line 225, in start_session
    response = self.execute(RemoteCommand.NEW_SESSION, parameters)
  File "F:\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "F:\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.samsung.android.app.notes' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: 'com.samsung.android.app.notes.memolist.MemoListActivity' or 'com.samsung.android.app.notes.com.samsung.android.app.notes.memolist.MemoListActivity' never started. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting


Process finished with exit code 1

**Comment by rdas063** [comment]
as of now I just wanted to run the app

**Comment by mykola-mokhnach** [comment]
Sorry for not being clear enough. This troubleshooting document is created exactly to solve such issues. It has a detailed description of possible cases and solutions to them. Please read carefully through it and let us know which solutions you've tried.

**Comment by rdas063** [comment]
Hii,

**Comment by rdas063** [comment]
Hi,

when we run the above code, it should run the Samsung Notes app but I m getting the mentioned error...
kindly help

**Comment by mykola-mokhnach** [comment]
Please use Appium forum to ask questions. 

Closed as not an issue
