### ISSUE TITLE
XPath not working

### ISSUE THREAD

**Issue by HenningL** [appium/appium#15242]
## Environment
Appium Windows Desktop Server 1.20.2 on Win10
[appium-server-logs.txt](https://github.com/appium/appium/files/6241736/appium-server-logs.txt)

I have a XPath:

Java Log: [By.xpath: //*[@content-description = "Let's go!"]]

Appium Log:
http://127.0.0.1:8202/wd/hub/session/c3bc9af4-dd7d-411e-a294-394c9c03736e/elements] with body: {"strategy":"xpath","selector":"//*[@content-description = \"Let's go!\"]","context":"","multiple":true}

Going through Appium server the xpath doesn't find the element (there is no error). Using the AppiumUI on the server the xpath works as expected, see images:

![image](https://user-images.githubusercontent.com/2301825/113250202-5f966500-92c0-11eb-85f8-964f0c22ea1f.png)

![image](https://user-images.githubusercontent.com/2301825/113250279-7f2d8d80-92c0-11eb-9d45-ea015bd5d7c6.png)

![image](https://user-images.githubusercontent.com/2301825/113250308-8c4a7c80-92c0-11eb-9347-ba13883e0422.png)

[page-src.txt](https://github.com/appium/appium/files/6241920/page-src.txt)

**Comment by mykola-mokhnach** [comment]
- Please use the most recent server version
- Please fill out the issue report properly and add the information requested by the template, including the full server log and the destination page source

**Comment by HenningL** [comment]
> * Please use the most recent server version
> * Please fill out the issue report properly and add the information requested by the template, including the full server log and the destination page source

Done

**Comment by mykola-mokhnach** [comment]
The page source is still missing

**Comment by HenningL** [comment]
yep, saw it too. here it is

**Comment by mykola-mokhnach** [comment]
Closed because of no response
