### ISSUE TITLE
[iProxy@00008020:8101] The connection has been closed [WD Proxy] Error: timeout of 240000ms exceeded during app launch

### ISSUE THREAD

**Issue by udaykittu** [appium/appium#15255]
## The problem
Connection has been closed issue occurs while doing the Automation execution on iOS Devices. First test case will execute successfully and during the launch of the second test case & launch app, facing the below error

Launch bundleID
[Xcode] 
[iProxy@00008020:8101] The connection has been closed
[WD Proxy] Error: timeout of 240000ms exceeded
[WD Proxy]     at createError (/usr/local/lib/node_modules/appium/node_modules/axios/lib/core/createError.js:16:15)
[WD Proxy]     at RedirectableRequest.handleRequestTimeout (/usr/local/lib/node_modules/appium/node_modules/axios/lib/adapters/http.js:280:16)
[WD Proxy]     at Object.onceWrapper (node:events:476:26)
[WD Proxy]     at RedirectableRequest.emit (node:events:369:20)
[WD Proxy]     at ClientRequest.eventHandlers.<computed> (/usr/local/lib/node_modules/appium/node_modules/follow-redirects/index.js:13:24)
[WD Proxy]     at ClientRequest.emit (node:events:369:20)
[WD Proxy]     at Socket.emitRequestTimeout (node:_http_client:780:9)
[WD Proxy]     at Object.onceWrapper (node:events:475:28)
[WD Proxy]     at Socket.emit (node:events:381:22)
[WD Proxy]     at Socket._onTimeout (node:net:480:8)
[WD Proxy]     at listOnTimeout (node:internal/timers:557:17)
[WD Proxy]     at processTimers (node:internal/timers:500:7)
[debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded). Retrying...
## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2
* Last Appium version that did not exhibit the issue (if applicable): 1.18.1
* Desktop OS/version used to run Appium: MAC os BigSur
* Node.js version (unless using Appium.app|exe): 15.12.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS 13.5.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Connection has been closed issue occurs while doing the Automation execution on iOS Devices. First test case will execute successfully and during the launch of the second test case & launch app, facing the below error

## Link to Appium logs

https://gist.github.com/udaykittu/cb6e2fe1eaff455892db870bdf81c736

**Comment by mykola-mokhnach** [comment]
> [Xcode] 2021-04-07 18:42:16.514828+0530 WebDriverAgentRunner-Runner[335:18574] Enqueue Failure: activate application '<XCUIApplicationImpl: 0x2837cd9b0 com.apple.store.Jolly>' (current state: Not Running) /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgentRunner/UITestingUITests.m 39 1

From the log it looks like XCTest fails to launch the application in a timely fashion, so Appium's proxy times out because of that. Unfortunately, there is nothing we could do there from Appium side

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
