### ISSUE TITLE
[simctl] Error running 'get_app_container': An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2)

### ISSUE THREAD

**Issue by rafaelcs** [appium/appium#15256]
## The problem

I'm running the tests on **Bitrise** (continuous integration) and when starting the tests, the Appium is showing the error:

```
[debug] [simctl] Error running 'get_app_container': An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
The operation couldn’t be completed. No such file or directory
No such file or directory
```

## Environment

* Appium version (or git revision) that exhibits the issue: **1.20.0** (I also tested with the **beta** version)
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: Server details [here](https://github.com/bitrise-io/bitrise.io/blob/master/system_reports/osx-xcode-11.7.x.log)
* Node.js version (unless using Appium.app|exe): **v12.18.4**
* Npm or Yarn package manager: **npm**
* Mobile platform/version under test: **iOS Simulator 13.7** (I also tried with **iOS Simulator 14.4**)
* Real device or emulator/simulator: **Simulator**
* Appium CLI or Appium.app|exe: **Appium CLI**

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/rafaelcs/2afee02fbcb1fec415caeecbaac99ee1#file-appium_log_from_bitrise-log

## Code To Reproduce Issue [ Good To Have ]

Check my [bitrise.yml](https://gist.github.com/rafaelcs/2afee02fbcb1fec415caeecbaac99ee1#file-bitrise-yml) file for more details

**Comment by mykola-mokhnach** [comment]
The error mentioned in the issue title is just a log message and does not affect the startup. Although, I could observe that the session creation itself simply times out because of, most likely, CI slowness. You could try to enable xcodebuild logging and/or increase startup timeouts as a workaround. Also, consider contacting cloud provider's customer support

Closed as not an issue

**Comment by rafaelcs** [comment]
@mykola-mokhnach Thank you

> You could try to enable xcodebuild logging and increase startup timeouts as a workaround

Are you referring to `wdaStartupRetryInterval` capability?

**Comment by mykola-mokhnach** [comment]
Not only this one. There are several capabilities that allow to customize the session startup. Check https://github.com/appium/appium-xcuitest-driver#capabilities for more details
