### ISSUE TITLE
Unable to retrive the webviews in Unity applications

### ISSUE THREAD

**Issue by metalimangal** [appium/appium#15252]
## The problem

We have two different activities in different process, one (splash screen in main process), and unity player running in child process in the Unity game application. We have observed that the child process' URLs are not accessible in the appium 

## Environment

* Appium version (or git revision) that exhibits the issue:  1.19.0 and below
* Desktop OS/version used to run Appium: Macbook, macOS Catalina
* Npm or Yarn package manager: npm
* Mobile platform/version under test: android
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

In the below screenshots, we can see that:
1. We have two webviews, one main, other child Unity. In chrome inspector, we can clearly see two webview contexts, and one has the parent URL "geo_tutorial", other has child URLs "baf.html"
2. While running appium automation, we are verifying the window handles each of these webview have, and their URLs, they point to the same URL "geo_tutorial"
3. These contexts do not have multiple window handles.

<img width="1440" alt="Screenshot 2021-04-06 at 2 13 36 PM" src="https://user-images.githubusercontent.com/31962950/113724333-df349180-970f-11eb-98da-b1ec89f25fa0.png">
<img width="1440" alt="Screenshot 2021-04-06 at 2 06 11 PM" src="https://user-images.githubusercontent.com/31962950/113724366-e5c30900-970f-11eb-8e55-fe9d6b445b8e.png">
<img width="1440" alt="Screenshot 2021-04-06 at 2 06 05 PM" src="https://user-images.githubusercontent.com/31962950/113724398-ed82ad80-970f-11eb-89e9-f38616f6c738.png">
<img width="1440" alt="Screenshot 2021-04-06 at 2 05 42 PM" src="https://user-images.githubusercontent.com/31962950/113724405-f07d9e00-970f-11eb-8a8d-942872cc90a3.png">
<img width="1440" alt="Screenshot 2021-04-06 at 2 05 35 PM" src="https://user-images.githubusercontent.com/31962950/113724414-f1aecb00-970f-11eb-8644-1f7c2d92ce6a.png">

**Comment by mykola-mokhnach** [comment]
- Please use the most recent server version
- Please attach the full server log
- Please check if web views are accessible from Chrome Remote Debugger

**Comment by mykola-mokhnach** [comment]
Closed because of no response
