### ISSUE TITLE
After updating from Appium 1.2 to 2.0 (Beta), my test is now throwing a "[HTTP] No route found for /wd/hub/session" error

### ISSUE THREAD

**Issue by WhyWontItWorkMan** [appium/appium#15261]
## The problem

My tests use to run fine when I was on Appium 1.2 (release), but I then updated to 2.0 (beta) because I wanted to try out these methods [startPerfRecord/stopPerfRecord](https://appiumpro.com/editions/12-capturing-performance-data-for-native-ios-apps) which are only baked into Appium 1.8 and greater, but on Appium 2.0 my test no longer run and is throwing a "[HTTP] No route found for /wd/hub/session" error immediately when initiating my test. I know it has something to do with the capabilities, but I can't for the life of me figure it out. 

I'm trying to run this test on a physical iPhone. 

Some thing's I've tried:
- Changing some of the capabilities by adding 'appium:' in front of them - E.g. appium:deviceName instead of just deviceName
- Running appium with `--base-path /wd/hub` 
- Using `http://127.0.0.1:4723/` in the client code instead of `http://127.0.0.1:4723/wd/hub`
- Removing a good amount of the capabilities I have set 

## Environment

* Appium version: 2.0.0-beta.12
* Last Appium version that did not exhibit the issue (if applicable): 1.2
* Desktop OS/version used to run Appium: macOS 10.15.7
* Node.js version (unless using Appium.app|exe): v14.15.5
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS 14.4
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

[Appium] Welcome to Appium v2.0.0-beta.12
[Appium] Non-default server args:
[Appium]   tmpDir: /var/folders/l9/hjmf8hz55hqf2dnhjtbzk9r40000gr/T
[Appium] Attempting to load driver uiautomator2...
[Appium] Attempting to load driver xcuitest...
[Appium] Attempting to load driver mac2...
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[Appium] Available drivers:
[Appium]   - uiautomator2@1.64.0 (automationName 'UiAutomator2')
[Appium]   - xcuitest@3.42.0 (automationName 'XCUITest')
[Appium]   - mac2@0.12.0 (automationName 'Mac2')
[Appium] Available plugins:
[Appium]   - images@1.1.5
[Appium] No plugins activated. Use the --plugins flag with names of plugins to activate
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"appium:udid":"auto","appium:xcodeSigningId":"iPhone Developer","appium:bundleId":"com.test.app.dev","platformName":"iOS","appium:deviceName":"doesntmatter","appium:automationName":"XCUITest","appium:updatedWDABundleId":"io.appium.WebDriverAgent"}}
[debug] [HTTP] No route found for /wd/hub/session
[HTTP] <-- POST /wd/hub/session 404 11 ms - 211

## Code To Reproduce Issue [ Good To Have ]

    @BeforeClass
    public static void setUp() throws MalformedURLException {

        DesiredCapabilities capabilities = new DesiredCapabilities();

        capabilities.setCapability("platformName", "iOS");
        capabilities.setCapability("automationName", "XCUITest");
        capabilities.setCapability("deviceName", "doesntmatter");
        capabilities.setCapability("udid", "auto");
        capabilities.setCapability("bundleId", "com.test.app.dev");
        capabilities.setCapability("xcodeSigningId", "iPhone Developer");
        capabilities.setCapability("updatedWDABundleId", "io.appium.WebDriverAgent");

        driver = new IOSDriver<>(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
    }

    @Test
    public void DemoTest123() {
        // navigate to the settings > about page
        driver.findElementByXPath(SETTINGS_BTN_XPATH).click();
        driver.findElementByXPath(ABOUT_OPT_XPATH).click();
    }

**Comment by KazuCocoa** [comment]
Because appium2.0 does not have `/wd/hub`.
You can run appium 2.0 with `-pa /wd/hub` or `-base-path`, or you could provide `http://127.0.0.1:4723/` instead of `http://127.0.0.1:4723/wd/hub` in your client code.

e.g.:
```
% appium  --base-path /wd/hub
[Appium] Welcome to Appium v2.0.0-beta.12
[Appium] Non-default server args:
[Appium]   basePath: /wd/hub
[Appium]   tmpDir: /var/folders/y6/524wp8fx0xj5q1rf6fktjrb00000gn/T
[Appium] Attempting to load driver xcuitest...
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[Appium] Available drivers:
[Appium]   - xcuitest@3.42.0 (automationName 'XCUITest')
```

**Comment by WhyWontItWorkMan** [comment]
> Because appium2.0 does not have `/wd/hub`.
> You can run appium 2.0 with `-pa /wd/hub` or `-base-path`, or you could provide `http://127.0.0.1:4723/` instead of `http://127.0.0.1:4723/wd/hub` in your client code.
> 
> e.g.:
> 
> ```
> % appium  --base-path /wd/hub
> [Appium] Welcome to Appium v2.0.0-beta.12
> [Appium] Non-default server args:
> [Appium]   basePath: /wd/hub
> [Appium]   tmpDir: /var/folders/y6/524wp8fx0xj5q1rf6fktjrb00000gn/T
> [Appium] Attempting to load driver xcuitest...
> [Appium] Appium REST http interface listener started on 0.0.0.0:4723
> [Appium] Available drivers:
> [Appium]   - xcuitest@3.42.0 (automationName 'XCUITest')
> ```

Hi KazuCocoa,

I've actually already tried both fixes you've mentioned and I'm still getting an error, though the error is different now (it's the same error if I run appium with --base-path /wd/hub or if I remove /wd/hub from the client code itself) . The Appium logs is spitting out - 

```
% appium  --base-path /wd/hub
[Appium] Welcome to Appium v2.0.0-beta.12
[Appium] Non-default server args:
[Appium]   basePath: /wd/hub
[Appium]   tmpDir: /var/folders/l9/hjmf8hz55hqf2dnhjtbzk9r40000gr/T
[Appium] Attempting to load driver uiautomator2...
[Appium] Attempting to load driver xcuitest...
[Appium] Attempting to load driver mac2...
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[Appium] Available drivers:
[Appium]   - uiautomator2@1.64.0 (automationName 'UiAutomator2')
[Appium]   - xcuitest@3.42.0 (automationName 'XCUITest')
[Appium]   - mac2@0.12.0 (automationName 'Mac2')
[Appium] Available plugins:
[Appium]   - images@1.1.5
[Appium] No plugins activated. Use the --plugins flag with names of plugins to activate
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"automationName":"XCUITest","bundleId":"com.test.app.dev","platformName":"iOS","udid":"auto","deviceName":"doesntmatter","updatedWDABundleId":"io.appium.WebDriverAgent","xcodeSigningId":"iPhone Developer"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"xcodeOrgId":"94KV3E626L","automationName":"XCUITest","bundleId":"com.amazon.muse.dev","platformName":"iOS","udid":"auto","deviceName":"doesntmatter","updatedWDABundleId":"io.appium.WebDriverAgent","xcodeSigningId":"iPhone Developer"},null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1617904183043 (10:49:43 GMT-0700 (Pacific Daylight Time))
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1617904183045 (10:49:43 GMT-0700 (Pacific Daylight Time))
[debug] [W3C] Encountered internal error running command: Error: W3C capabilities should be provided
[debug] [W3C]     at parseCapsForInnerDriver (/usr/local/lib/node_modules/appium/lib/utils.js:57:14)
[debug] [W3C]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:141:26)
[debug] [W3C]     at commandExecutor (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:332:7)
[debug] [W3C]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:346:15)
[debug] [W3C]     at wrappedCmd (/usr/local/lib/node_modules/appium/lib/appium.js:474:28)
[debug] [W3C]     at AppiumDriver.executeWrappedCommand (/usr/local/lib/node_modules/appium/lib/appium.js:541:22)
[debug] [W3C]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:485:28)
[debug] [W3C]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:285:34)
[debug] [W3C]     at /usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:411:15
[debug] [W3C]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [W3C]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:137:13)
[debug] [W3C]     at Route.dispatch (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:112:3)
[debug] [W3C]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [W3C]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:281:22
[debug] [W3C]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
[debug] [W3C]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[debug] [W3C]     at logger (/usr/local/lib/node_modules/appium/node_modules/morgan/index.js:144:5)
[debug] [W3C]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [W3C]     at trim_prefix (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
[debug] [W3C]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:284:7
[debug] [W3C]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
[debug] [W3C]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[debug] [W3C]     at /usr/local/lib/node_modules/appium/node_modules/body-parser/lib/read.js:130:5
[debug] [W3C]     at invokeCallback (/usr/local/lib/node_modules/appium/node_modules/raw-body/index.js:224:16)
[debug] [W3C]     at done (/usr/local/lib/node_modules/appium/node_modules/raw-body/index.js:213:7)
[debug] [W3C]     at IncomingMessage.onEnd (/usr/local/lib/node_modules/appium/node_modules/raw-body/index.js:273:7)
[debug] [W3C]     at IncomingMessage.emit (events.js:327:22)
[debug] [W3C]     at endReadableNT (internal/streams/readable.js:1327:12)
[debug] [W3C]     at processTicksAndRejections (internal/process/task_queues.js:80:21)
[HTTP] <-- POST /wd/hub/session 500 40 ms - 567
[HTTP]
[HTTP] --> POST /wd/hub/session/null/timeouts/implicit_wait
[HTTP] {"ms":10000}
[debug] [GENERIC (null)] Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started
[debug] [GENERIC (null)]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:231:15)
[debug] [GENERIC (null)]     at /usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:411:15
[debug] [GENERIC (null)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [GENERIC (null)]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:137:13)
[debug] [GENERIC (null)]     at Route.dispatch (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:112:3)
[debug] [GENERIC (null)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [GENERIC (null)]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:281:22
[debug] [GENERIC (null)]     at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:354:14)
[debug] [GENERIC (null)]     at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:365:14)
[debug] [GENERIC (null)]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:410:3)
[debug] [GENERIC (null)]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[debug] [GENERIC (null)]     at logger (/usr/local/lib/node_modules/appium/node_modules/morgan/index.js:144:5)
[debug] [GENERIC (null)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [GENERIC (null)]     at trim_prefix (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
[debug] [GENERIC (null)]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:284:7
[debug] [GENERIC (null)]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
[debug] [GENERIC (null)]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[debug] [GENERIC (null)]     at /usr/local/lib/node_modules/appium/node_modules/body-parser/lib/read.js:130:5
[debug] [GENERIC (null)]     at invokeCallback (/usr/local/lib/node_modules/appium/node_modules/raw-body/index.js:224:16)
[debug] [GENERIC (null)]     at done (/usr/local/lib/node_modules/appium/node_modules/raw-body/index.js:213:7)
[debug] [GENERIC (null)]     at IncomingMessage.onEnd (/usr/local/lib/node_modules/appium/node_modules/raw-body/index.js:273:7)
[debug] [GENERIC (null)]     at IncomingMessage.emit (events.js:327:22)
[debug] [GENERIC (null)]     at endReadableNT (internal/streams/readable.js:1327:12)
[debug] [GENERIC (null)]     at processTicksAndRejections (internal/process/task_queues.js:80:21)
[HTTP] <-- POST /wd/hub/session/null/timeouts/implicit_wait 404 4 ms - 2572
[HTTP]
[HTTP] --> DELETE /wd/hub/session/null
[HTTP] {}
[debug] [GENERIC (null)] Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started
[debug] [GENERIC (null)]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:231:15)
[debug] [GENERIC (null)]     at /usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:411:15
[debug] [GENERIC (null)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [GENERIC (null)]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:137:13)
[debug] [GENERIC (null)]     at Route.dispatch (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:112:3)
[debug] [GENERIC (null)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [GENERIC (null)]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:281:22
[debug] [GENERIC (null)]     at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:354:14)
[debug] [GENERIC (null)]     at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:365:14)
[debug] [GENERIC (null)]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:410:3)
[debug] [GENERIC (null)]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[debug] [GENERIC (null)]     at logger (/usr/local/lib/node_modules/appium/node_modules/morgan/index.js:144:5)
[debug] [GENERIC (null)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [GENERIC (null)]     at trim_prefix (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
[debug] [GENERIC (null)]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:284:7
[debug] [GENERIC (null)]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
[debug] [GENERIC (null)]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[debug] [GENERIC (null)]     at jsonParser (/usr/local/lib/node_modules/appium/node_modules/body-parser/lib/types/json.js:110:7)
[debug] [GENERIC (null)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [GENERIC (null)]     at trim_prefix (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
[debug] [GENERIC (null)]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:284:7
[debug] [GENERIC (null)]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
[debug] [GENERIC (null)]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[debug] [GENERIC (null)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:91:12)
[debug] [GENERIC (null)]     at trim_prefix (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
[debug] [GENERIC (null)]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:284:7
[debug] [GENERIC (null)]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
[debug] [GENERIC (null)]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[debug] [GENERIC (null)]     at methodOverride (/usr/local/lib/node_modules/appium/node_modules/method-override/index.js:65:14)
[debug] [GENERIC (null)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [GENERIC (null)]     at trim_prefix (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
[debug] [GENERIC (null)]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:284:7
[debug] [GENERIC (null)]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
[debug] [GENERIC (null)]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[debug] [GENERIC (null)]     at urlencodedParser (/usr/local/lib/node_modules/appium/node_modules/body-parser/lib/types/urlencoded.js:91:7)
[debug] [GENERIC (null)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [GENERIC (null)]     at trim_prefix (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
[debug] [GENERIC (null)]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:284:7
[debug] [GENERIC (null)]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
[debug] [GENERIC (null)]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[HTTP] <-- DELETE /wd/hub/session/null 404 4 ms - 4476
```

**Comment by KazuCocoa** [comment]
_W3C capabilities should be provided_

It is because your request did not follow W3C spec's one meanwhile the base path worked.

```
[HTTP] {"desiredCapabilities":{"automationName":"XCUITest","bundleId":"com.test.app.dev","platformName":"iOS","udid":"auto","deviceName":"doesntmatter","updatedWDABundleId":"io.appium.WebDriverAgent","xcodeSigningId":"iPhone Developer"}}
```

Should be `{"capabilities": {"firstMatch": [...]}, "alwaysMatch": {...}}`.
I guess your client did not support W3C WebDriver spec or drop W3C capabilities in the new session request.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by monilj** [comment]
@mykola-mokhnach  @KazuCocoa 
I am running appium server programmatically. This is my code

` AppiumServiceBuilder builder = new AppiumServiceBuilder();
        builder.usingAnyFreePort();
        builder.usingDriverExecutable(new File("C:\\Program Files\\nodejs\\node.exe"));
        builder.withAppiumJS(new File("C:\\Users\\<user_name>\\AppData\\Roaming\\npm\\node_modules\\appium"));
        HashMap<String, String> environment = new HashMap();
        environment.put("PATH", "/usr/local/bin:" + System.getenv("PATH"));
        builder.withEnvironment(environment);
        service = AppiumDriverLocalService.buildService(builder);
        service.start();
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("platformName", "Android");
        capabilities.setCapability("deviceName", "Android Emulator");
        capabilities.setCapability("automationName", "UiAutomator2");
        capabilities.setCapability("app", "path to app\\Learn_Android_With_Source_Code.apk");

        androidDriver = new AndroidDriver<AndroidElement>(service.getUrl(), capabilities);
        androidDriver.manage().timeouts().implicitlyWait(3, TimeUnit.SECONDS);
        return androidDriver;`


How can I override URL came from service.start()

**Comment by StephanB75** [comment]
For the builder :
 builder = new AppiumServiceBuilder().withLogFile(new File("appium.log")).withArgument(() -> "--base-path", "/wd/hub").withArgument(() -> "--plugins", "images");

**Comment by mittalri** [comment]
i am tryin start appium code suggested.

AppiumServiceBuilder builder = new AppiumServiceBuilder();	     
	        builder.usingAnyFreePort();
	        // Tell builder where node is installed. Or set this path in an environment variable named NODE_PATH
	        builder.usingDriverExecutable(new File("C:\\Program Files\\nodejs\\node.exe"));
	        // Tell builder where Appium is installed. Or set this path in an environment variable named APPIUM_PATH
	        builder.withAppiumJS(new File("C:\\Users\\Ritesh Mittal\\AppData\\Roaming\\npm\\node_modules\\appium"));


	        HashMap<String, String> environment = new HashMap<String, String>();
	        environment.put("PATH", "/usr/local/bin:" + System.getenv("PATH"));
	        builder.withEnvironment(environment);
	        builder.withArgument(() -> "--base-path", "/wd/hub");


	        service = AppiumDriverLocalService.buildService(builder);
	        service.start();
 
but getting error 
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[35m[Appium][39m Welcome to Appium v1.22.2
[35m[Appium][39m Non-default server args:
[35m[Appium][39m   port: 55175
[35m[Appium][39m Appium REST http interface listener started on 0.0.0.0:55175
[35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/status[39m
[35m[HTTP][39m [90m{}[39m
[debug] [35m[HTTP][39m No route found for /wd/status
[35m[HTTP][39m [37m<-- GET /wd/status [39m[33m404[39m [90m17 ms - 211[39m
[35m[HTTP][39m [90m[39m
[35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/status[39m
[35m[HTTP][39m [90m{}[39m
[debug] [35m[HTTP][39m No route found for /wd/status
[35m[HTTP][39m [37m<-- GET /wd/status [39m[33m404[39m [90m24 ms - 211[39m
