### ISSUE TITLE
Appium recognize "XCUIElementTypeSlider" as a "XCUIElementTypeOther"

### ISSUE THREAD

**Issue by elzhu** [appium/appium#15263]
## The problem
Check the Twitter fleet lines, the element which should be an "XCUIElementTypeSlider" is been recognized as an "XCUIElementTypeOther". In this way, we will not get access to each element inside this slider. However, the iOS accessibility inspector is able to access each one of those elements. Appium should also provide the same access as well. 

## Environment

* Appium version (or git revision) that exhibits the issue:  1.12.2
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: MAC OS Catalina
* Node.js version (unless using Appium.app|exe):v12.18.2
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Iphone 11 with iOS 14.4
* Real device or emulator/simulator: both
* Appium CLI or Appium.app|exe:

## Details

When we try to get a slider element from appium, we used appium inspector to look for this fleet line element. However, it is not giving us access to each fleet and it is recognized as XCUIElementTypeSlider.

If we use the Xcode accessibility inspector, we will be to loop through each fleet element inside this fleet line:
f you enable voice over, you can click and select the element, swipe up through the choices, and within the accessibility inspector, if you click next element, you get to iterate through each element in the fleet line.
![image](https://user-images.githubusercontent.com/11546972/114076165-35621b80-985b-11eb-829d-7d05d4b3cc6f.png)

![image (1)](https://user-images.githubusercontent.com/11546972/114076224-47dc5500-985b-11eb-8678-bf02ab91a909.png)

## Code To Reproduce Issue [ Good To Have ]
Download the Twitter app and inspect it with the appium app to see the fleet line.
<img width="1076" alt="Screen Shot 2021-04-06 at 1 13 51 PM (1)" src="https://user-images.githubusercontent.com/11546972/114076140-2e3b0d80-985b-11eb-8313-a5768d3b87f2.png">

**Comment by mykola-mokhnach** [comment]
The way elements are recognized is not under Appium's control. This is done on a lower level by XCTest.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
