### ISSUE TITLE
WDA Crash when setting high mjpegServerFramerate and high mjpegScalingFactor

### ISSUE THREAD

**Issue by yusunan** [appium/appium#15264]
## The problem

WDA Crashed when we set mjpegServerFramerate(50) and mjpegScalingFactor(70)

## Environment

* Node.js version (unless using Appium.app|exe):v8.11.3
* Mobile platform/version under test: iPhone 11 (14.1) and more devices
* Real device or emulator/simulator:Real device 
* Xcode version:12.2
* WDA version:v3.7.1 and other versions

## Details

1.Using MJPEG server to get images
2. Set mjpegServerFramerate(50) and mjpegScalingFactor(70)
3. Wait for 50s then the MJPEG server stoped 
4. WDA crashed

## Device logs when crash

Apr  1 16:23:06 iPhone-11dai MobileTimer(XCTAutomationSupport)[3177] <Notice>: Connection from client with pid 3198 was invalidated.
Apr  1 16:23:06 iPhone-11dai backboardd(HIDAnalytics)[62] <Notice>: HIDAnalytics Unregister Send event com.apple.hid.queueUsage
Apr  1 16:23:06 iPhone-11dai testmanagerd[761] <Notice>: Got screenshot, rotating to orientation 0
Apr  1 16:23:06 iPhone-11dai symptomsd(SymptomEvaluator)[117] <Notice>: Received (FATAL) CPU usage trigger: 
  WebDriverAgentRunner-Runner[3198] (/private/var/containers/Bundle/Application/7EB98EB5-8168-43C6-981A-85AEF1F6CF1C/WebDriverAgentRunner-Runner.app/WebDriverAgentRunner-Runner) used 48.00s of CPU over 50.95 seconds (averaging 94%), violating a CPU usage limit of 48.00s over 60 seconds.
Apr  1 16:23:06 iPhone-11dai runningboardd(RunningBoard)[29] <Error>: RBSStateCapture remove item called for untracked item <RBProcessMonitorObserver: 0x105871550; <RBProcess: 0x1023585b0; 3198; identity: application<emm.utf.WebDriverAgentRunner.xctrunner>>; configCount: 0>
Apr  1 16:23:06 iPhone-11dai symptomsd(SymptomEvaluator)[117] <Notice>: Fatal RESOURCE_NOTIFY trigger for WebDriverAgentRunner-Runner [3198] (48000358416 nanoseconds of CPU usage over 50.00s seconds, violating limit of 48000000000 nanoseconds of CPU usage over 60.00s seconds)
Apr  1 16:23:06 iPhone-11dai symptomsd(SymptomEvaluator)[117] <Notice>:   Generated RESOURCE_NOTIFY report for WebDriverAgentRunner-Runner within the past 300 seconds (1617265278.4159). Disallow report.
Apr  1 16:23:06 iPhone-11dai runningboardd(RunningBoard)[29] <Notice>: [application<emm.utf.WebDriverAgentRunner.xctrunner>:3198] Death sentinel fired!
Apr  1 16:23:06 iPhone-11dai testmanagerd[761] <Notice>: XCTDAuthorizedProcessTracker has cancelled dispatch source for pid 3198 and removed it from its list of dispatch sources to track

**Comment by yusunan** [comment]
Set mjpegServerFramerate(50) and mjpegScalingFactor(70)

This setting make a high CPU usage almost 90% and WDA will be killed by APPLE

**Comment by mykola-mokhnach** [comment]
Closed s not an issue
