### ISSUE TITLE
uiautomator2 AndroidRuntime: FATAL EXCEPTION

### ISSUE THREAD

**Issue by WuXiaoJun111** [appium/appium#15274]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue: V1.13.0
* Desktop OS/version used to run Appium:V1.13.0
* Npm or Yarn package manager:Npm
* Mobile platform/version under test: Androind6.0
* Real device or emulator/simulator:Real device

## Details
An abnormal operation of u2 appears in the logcat log。But don't know why？
Visiting the website(www.google-analytics.com) appears in the log, I want to know if this operation is related to U2
LogCat log:
**04-12 14:48:56.875  3584  3600 I System.out: entered createSocket(Socket s, host: www.google-analytics.com, port: 443, autoClose: true)**
04-12 14:48:57.005  3584  3600 E AndroidRuntime: FATAL EXCEPTION: Instr: androidx.test.runner.AndroidJUnitRunner

04-12 14:48:57.005  3584  3600 E AndroidRuntime: Process: io.appium.uiautomator2.server, PID: 3584

**Comment by KazuCocoa** [comment]
Probably it is by UIAutomator stuff by Google.

I found `-e disableAnalytics true` https://developer.android.com/reference/androidx/test/runner/AndroidJUnitRunner to disable it.

**Comment by WuXiaoJun111** [comment]
@KazuCocoa thank you for your help。Will this problem affect the stability of adb connection via wlan? We in china,cannot access  google

**Comment by KazuCocoa** [comment]
I don't know well, but potentially yes.

I experienced Appium automation in China hosts machines in my work (i ensured some google url did not work then), but haven't seen such unsuitability so far. So I do not have exact answer.

**Comment by WuXiaoJun111** [comment]
thanks for your hints。About **disableAnalytics true**。Is there this setting in the UIA1 source code? or This problem is only in UIA2？

**Comment by KazuCocoa** [comment]
I don't remember in uia1, but this is AndroidJUnitRunner things. so I guess both.
If you could find like the below PR line in your local appium/node_modules/appium-uiautomator2-driver, you will be able to apply this change directly on your local.
https://github.com/appium/appium-uiautomator2-driver/pull/452

**Comment by KazuCocoa** [comment]
You can try the latest `appium@beta`. It has `-e disableAnalytics true`
