### ISSUE TITLE
Appium desktop inspector cannot take screenshot of Page on IOS 14.7 Xcode 12.5.3 BETA

### ISSUE THREAD

**Issue by nerminezar** [appium/appium#15273]
## The problem

Appium desktop inspector cannot take screenshot of Page on IOS 14.7 Xcode 12.5.3 BETA

## Environment

* Appium version  : 1.20.2

* Desktop OS/version used to run Appium: MacOs big Sur 11.2.3
* Node.js version (unless using Appium.app|exe): v15.14.0
* Npm or Yarn package manager: 7.7.6
* Mobile platform/version under test: ios 14.7 
* Real device or emulator/simulator: real device iphone 7 
* Appium CLI or Appium.app|exe:

## Details

when i launch the inspector to find the locators on login page , the app launches , but the inspector keep loading when i check the logs i get an error 500 
## Link to Appium logs

https://gist.github.com/nerminezar/48e52afa53c7f4702106eff3ddd03420

**Comment by mykola-mokhnach** [comment]
Closed as duplicate. The original issue is pinned to the top. Kindly use search.
