### ISSUE TITLE
ActionChains throws error while automating keyboard shorcuts

### ISSUE THREAD

**Issue by saharana27** [appium/appium#15276]
## The problem

ActionChains throws error while automating keyboard shorcuts

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Mac OS 10.15.6
* Node.js version (unless using Appium.app|exe): v14.13.1
* Npm or Yarn package manager: 6.14.8
* Mobile platform/version under test: iOS 14.4
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

Not able to automate keyboard shortcuts.
action.key_down(Keys.SHIFT).send_keys('E').key_up(Keys.SHIFT).perform() throws error.

Note: No external keyboard attached.

## Link to Appium logs

https://gist.github.com/saharana27/bdfd2b14e538388d1fedf93424f805d0.js

## Code To Reproduce Issue [ Good To Have ]

action = ActionChains(appium_session.get_driver())
action.key_down(Keys.SHIFT).send_keys('E').key_up(Keys.SHIFT).perform()

**Comment by mykola-mokhnach** [comment]
Unfortunately iOS does not support sending of keys at such granularity level by XCTest. There's nothing we could do there on appium side.

**Comment by saharana27** [comment]
how can we automate keyboard shorcuts for iOS?

**Comment by mykola-mokhnach** [comment]
I don't know any way to achieve that. Keyboard bindings are only available for macOS platform in XCTest. Try to ask at Apple forums.
