### ISSUE TITLE
Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up

### ISSUE THREAD

**Issue by udaykittu** [appium/appium#15277]
## The problem
Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2 & 1.21.0-beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS Big Sur / Mac OS Catalina
* Node.js version (unless using Appium.app|exe): 15.12.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS 13.5.1 & iOS 14.4.2
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI & Appium.app

## Details
Socket hang up error while performing the automation execution on real devices - iPad / iPhone

## Link to Appium logs
https://gist.github.com/udaykittu/cea9f17d77d26244c3f484f15739558e

Issue created based on confirmation from @KazuCocoa in the issue https://github.com/appium/appium/issues/15199

https://github.com/appium/appium/issues/15199#issuecomment-821321612

**Comment by mykola-mokhnach** [comment]
I don't observe any issues from Appium side. The issue seems to happen inside of XCTest internals.
Try to replace xpath locators with predicate/class chain as a possible workaround

**Comment by udaykittu** [comment]
I see the below error in IOSDeviceLog - highlighted in bold.....

Is there something that we can do with firewall settings?

[IOSDeviceLog] Apr 16 23:25:58 Automations-iPad SpringBoard(SpringBoard)[55] <Notice>: Enabling home screen icon rotation for reason: SBAppToAppWorkspaceTransaction
[IOSDeviceLog] Apr 16 23:25:58 Automations-iPad runningboardd(RunningBoard)[27] <Notice>: Finished acquiring assertion 27-55-1358 (target:application<com.apple.store.Jolly>(UIScene:com.apple.frontboard.systemappservices::sceneID%3Acom.apple.store.Jolly-default))
[IOSDeviceLog] Apr 16 23:25:58 Automations-iPad SpringBoard(SpringBoard)[55] <Notice>: Root transaction complete: <SBAppToAppWorkspaceTransaction: 0x111f7eb30>
[IOSDeviceLog] Apr 16 23:25:58 Automations-iPad testmanagerd[235] <Notice>: Handling kAXPidStatusChangedNotification from AX element pid: 55, elementOrHash.elementID: 0.0 (0x12bb0d880)
[IOSDeviceLog] Apr 16 23:25:58 Automations-iPad SpringBoard(XCTAutomationSupport)[55] <Error>: Unexpectedly received animationDidStop without a matching animationDidStart. Monitoring for idle animations may no longer function correctly.
[IOSDeviceLog] Apr 16 23:25:58 Automations-iPad testmanagerd[235] <Notice>: Calling handler for AX notification kAXPidStatusChangedNotification from AX element pid: 55, elementOrHash.elementID: 0.0 with payload <private>
[IOSDeviceLog] Apr 16 23:25:58 Automations-iPad SpringBoard(XCTAutomationSupport)[55] <Error>: Unexpectedly received animationDidStop without a matching animationDidStart. Monitoring for idle animations may no longer function correctly.
[IOSDeviceLog] Apr 16 23:25:58 Automations-iPad testmanagerd[235] <Notice>: Handling kAXUserTestingNotification from AX element pid: 55, elementOrHash.elementID: 0.1 (0x12bb0d880)
**_[IOSDeviceLog] Apr 16 23:25:58 Automations-iPad runningboardd(RunningBoard)[27] <Notice>: [xpcservice<com.apple.WebKit.Networking>:627] Shutdown sockets (SVC)_**
[IOSDeviceLog] Apr 16 23:25:58 Automations-iPad SpringBoard(XCTAutomationSupport)[55] <Error>: Unexpectedly received animationDidStop without a matching animationDidStart. Monitoring for idle animations may no longer function correctly.
[IOSDeviceLog] Apr 16 23:25:58 Automations-iPad testmanagerd[235] <Notice>: Got user testing notification with payload <private>
[IOSDeviceLog] Apr 16 23:25:58 Automations-iPad runningboardd(RunningBoard)[27] <Notice>: [xpcservice<com.apple.WebKit.Networking>:627] Error 45 setting darwin role to None: Operation not supported, falling back to setting priority
[IOSDeviceLog] Apr 16 23:25:58 Automations-iPad CommCenter[79] <Notice>: #I FBSDisplayLayoutUpdateHandler: update start

**Comment by KazuCocoa** [comment]
```
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id, css selector
[debug] [BaseDriver] Waiting up to 2000 ms for condition
[debug] [WD Proxy] Matched '/elements' to command name 'findElements'
[debug] [WD Proxy] Proxying [POST /elements] to [POST http://127.0.0.1:8100/session/8C2BD1D8-A03A-41B4-99D3-D98B44DEDE16/elements] with body: {"using":"xpath","value":"//XCUIElementTypeStaticText[@name=\"Loading\"]"}
[debug] [iProxy@00008020:8100] Could not find the expected device 00008020-001A55192113802E
[WD Proxy] socket hang up
[debug] [BaseDriver] Waited for 18 ms so far
[debug] [WD Proxy] Matched '/elements' to command name 'findElements'
[debug] [WD Proxy] Proxying [POST /elements] to [POST http://127.0.0.1:8100/session/8C2BD1D8-A03A-41B4-99D3-D98B44DEDE16/elements] with body: {"using":"xpath","value":"//XCUIElementTypeStaticText[@name=\"Loading\"]"}
[debug] [iProxy@00008020:8100] Connection was refused to port 8100
[WD Proxy] socket hang up
```

Your device was disconnected in the middle of the session.
Did your device allow Xcode to connect over the network? I heard the option might the USB connection unstable. (It may be improved tho)
https://stackoverflow.com/questions/46320600/connect-via-network-wireless-debugging-not-working-xcode-9

**Comment by udaykittu** [comment]
Thanks @KazuCocoa , i will try this and let you know the results

**Comment by insidiaGithub** [comment]
Isn't it a good idea to update my environment to last stable appium if we use real devices?

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
