### ISSUE TITLE
Appium v1.21.0-rc.1 and desktop 1.20.2-4 for IOS React Native app is very slow and taking twice the time of android runs

### ISSUE THREAD

**Issue by yadavsvmx** [appium/appium#15271]
## The problem

Appium v1.21.0-rc.1 and desktop 1.20.2-4 for IOS React Native app is very slow and taking twice the time of android executions.

In appium desktop 1.8.3 versions the execution is equally fast for IOS and android.

## Environment
MAC OS : BigSure
Appium server : v1.21.0-rc.1
OR
Appium desktop : 1.20.2-4

## Details

Appium v1.21.0-rc.1 and desktop 1.20.2-4 for IOS React Native app is very slow and taking twice the time of android executions.

In appium desktop 1.8.3 versions the execution is equally fast for IOS and android.

Tried with the following capabilities to improve speed , but they did not have a impact :
capabilities.setCapability("waitForQuiescence", false);
					
capabilities.setCapability("useJSONSource", true);
					
capabilities.setCapability("simpleIsVisibleCheck",true);

**Comment by mykola-mokhnach** [comment]
It might be the application under test is running some activities that hog the main thread and slow down XCTest. You could try to decrease the default values for animationCoolOffTimeout/waitForIdleTimeout settings and/or switch to web view mode while interacting with web views. In general there is not much to do there from Appium side.

**Comment by yadavsvmx** [comment]
Well, this used to work well in appium 1.18.3 versions, even now it works when i checked. So it has to possibly be an issue with appium newer versions itself.

Attaching the logs for reference 
[Slowness-appium-server-logs.txt](https://github.com/appium/appium/files/6310718/Slowness-appium-server-logs.txt)

**Comment by Dan-Maor** [comment]
Can you please try to set `wdaEventloopIdleDelay` to 0 and disable `simpleIsVisibleCheck` and see if it helps?

**Comment by mykola-mokhnach** [comment]
Closed as third party issue. Also, no response
