### ISSUE TITLE
Unable to retrive the webviews in Unity applications

### ISSUE THREAD

**Issue by metalimangal** [appium/appium#15272]
## The problem

We have two different activities in different process, one (splash screen in main process), and unity player running in child process in the Unity game application. We have observed that the child process' URLs are not accessible in the appium

## Environment

Appium version (or git revision) that exhibits the issue: 1.20 and below
Desktop OS/version used to run Appium: Macbook, macOS Catalina
Npm or Yarn package manager: npm
Mobile platform/version under test: android
Real device or emulator/simulator: real device
Appium CLI or Appium.app|exe: Appium CLI

## Details

In the below screenshots, we can see that:

We have two webviews, one main, other child Unity. In chrome inspector, we can clearly see two webview contexts, and one has the parent URL "geo_tutorial", other has child URLs "baf.html"
While running appium automation, we are verifying the window handles each of these webview have, and their URLs, they point to the same URL "geo_tutorial"
These contexts do not have multiple window handles.
<img width="1440" alt="Screenshot 2021-04-06 at 2 05 35 PM" src="https://user-images.githubusercontent.com/31962950/114721953-0403b700-9d57-11eb-8db7-1afe9cb0af6d.png">
<img width="1440" alt="Screenshot 2021-04-06 at 2 05 42 PM" src="https://user-images.githubusercontent.com/31962950/114721961-06661100-9d57-11eb-810e-ca8a31ed0aa5.png">
<img width="1440" alt="Screenshot 2021-04-06 at 2 06 05 PM" src="https://user-images.githubusercontent.com/31962950/114721969-07973e00-9d57-11eb-8a28-80bef4f48e1a.png">
<img width="1440" alt="Screenshot 2021-04-06 at 2 06 11 PM" src="https://user-images.githubusercontent.com/31962950/114721980-09610180-9d57-11eb-94b1-aa0202e7103b.png">
<img width="1440" alt="Screenshot 2021-04-06 at 2 13 36 PM" src="https://user-images.githubusercontent.com/31962950/114721989-0bc35b80-9d57-11eb-9dae-ec65d9bea651.png">

## Link to Appium logs

https://gist.github.com/metalimangal/75e8541695f58867c3f93978284ae1b6

**Comment by mykola-mokhnach** [comment]
Please attach the log with `enableWebviewDetailsCollection` capability enabled

**Comment by metalimangal** [comment]
@mykola-mokhnach Created second gist https://gist.github.com/metalimangal/c49e488d40d182b929ece69c4c58a356 with enableWebviewDetailsCollection enabled.

**Comment by KazuCocoa** [comment]
You were not able to get expected `CDwindow-` prefix windows (which is vanilla chromedriver/chrome behavior) in neither    `WEBVIEW_apps.rummycircle.com.mobilerummy:Unity` nor and `WEBVIEW_apps.rummycircle.com.mobilerummy` context via like `getWindowHandles( )` (https://www.toolsqa.com/selenium-webdriver/window-handle-in-selenium/)? (Not sure since when, but newer chrome webview requires us to get its pages via `/handles` after switching to webview context)
The attached log did not have API call to `session/:session_id/window/handles` to get `CDwindow-`, so I wondered my current understanding is correct.

**Comment by mykola-mokhnach** [comment]
Please try if the patch https://github.com/appium/appium-android-driver/pull/687 works for you

**Comment by metalimangal** [comment]
@KazuCocoa In this case, I see that both Web views are pointing to same CDwindow-, but I see in Chrome debugger that we have two different processes, which means we are unable to get another CDwindow-, where we have the web URL we want to access.

**Comment by metalimangal** [comment]
@mykola-mokhnach, I have added the patch, the issue is still not resolved. Please see the attached logs:

https://gist.github.com/metalimangal/4be16f0a07b92f4bfd3f6b4a6c4cf70c

**Comment by mykola-mokhnach** [comment]
Thanks for trying it. I see there is a small bug there. Please try try the updated PR

**Comment by metalimangal** [comment]
@mykola-mokhnach The bug is resolved, thank you!
