### ISSUE TITLE
WDA feature request: support long press button

### ISSUE THREAD

**Issue by codeskyblue** [appium/appium#15283]
now https://github.com/appium/WebDriverAgent support pressButton: volumeDown but not support pressButton volumeDown for 1 second.

I found there is such API: `pressButton:forDuration:`

Ref: <https://developer.apple.com/documentation/xctest/xcuiremote/1627475-pressbutton?language=objc>
Can you support expose API of pressButton for Duration.

@mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
Added the [extension](https://github.com/appium/appium-xcuitest-driver#mobile-performiohidevent) to appium@beta
