### ISSUE TITLE
How can I run the integration test for existing native app with embedded Flutter view by using appium?

### ISSUE THREAD

**Issue by Alok81234881** [appium/appium#15281]
I've my application with embedded flutter views and the tests are written in java(appium). I want to add tests for the flutter views but it says that it needs capability "automationName" set to "Flutter". But my "automationName" capability is set to "UiAutomator2". Is there a way to dynamically change the capability to Flutter when my application reaches the flutter views ?

**Comment by mykola-mokhnach** [comment]
> Is there a way to dynamically change the capability to Flutter when my application reaches the flutter views ?

Unfortunately this is impossible. You could probably try to maintain two different drivers from the client side and switch between them, although I cannot confirm this is 100% going to work

Please use Appium forum to ask question
