### ISSUE TITLE
Android: API Demos app fails to launch with a permission screen and a warning

### ISSUE THREAD

**Issue by omprakashchavan01** [appium/appium#15286]
## The problem

From last few days, we are observing that on some Android devices, the API Demos app is not launching. Instead the permission screen is shown where the device is asking what all permissions to be given to the application. Apart from this, when we launch the app again, we get a warning that says "This app was built for an older version of Android and may not work properly. Try checking for updates or contact the developer".

This issue is observed no matter if the app is installed manually or through Appium.
This issue is reported on both the Emulator as well as the real device.

Please refer the attached snapshots of the permission screen and the warning text.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): 14.15.1
* Npm or Yarn package manager: 6.14.8
* Mobile platform/version under test: Android Pixel 2 and 3a [OS versions 10 and 11]
* Real device or emulator/simulator: Both
* Appium CLI or Appium.app|exe: Appium CLI

<Appium server log>
[UiAutomator2] Starting 'io.appium.android.apis/ApiDemos and waiting for 'io.appium.android.apis/ApiDemos'

[debug] [ADB] Running 'C:\Users\xxx\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s xxxx shell am start -W -n io.appium.android.apis/ApiDemos -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'

[debug] [ADB] We tried to start an activity that doesn't exist, retrying with '.ApiDemos' activity name

[debug] [ADB] Running 'C:\Users\xxx\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s xxxx shell am start -W -n io.appium.android.apis/.ApiDemos -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'

[debug] [ADB] Waiting up to 20000ms for activity matching pkg: 'io.appium.android.apis' and activity: 'ApiDemos' to be focused

[debug] [ADB] Possible activities, to be checked: 'ApiDemos', 'io.appium.android.apis.ApiDemos'

[debug] [ADB] Getting focused package and activity

[debug] [ADB] Running 'C:\Users\xxx\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s xxxx shell dumpsys window displays'

[debug] [ADB] Found package: 'com.google.android.permissioncontroller' and fully qualified activity name : 'com.android.packageinstaller.permission.ui.ReviewPermissionsActivity'

[debug] [ADB] Incorrect package and activity. Retrying.

**Comment by omprakashchavan01** [comment]
![APIDemosPermissionScreen](https://user-images.githubusercontent.com/63530610/115574707-7fc5ac80-a2df-11eb-9054-f39b5cb42b83.png)
![APIDemosOldVersionWarning](https://user-images.githubusercontent.com/63530610/115574713-82280680-a2df-11eb-8fdc-91fe08c23061.png)

**Comment by mykola-mokhnach** [comment]
Unfortunately we don't have much resources to keep up with API demos updated for never Android versions. Feel free to raise a PR for that

**Comment by omprakashchavan01** [comment]
I would have loved to. Unfortunately don't have app development expertise.

**Comment by KazuCocoa** [comment]
Did this issue happen on the latest https://github.com/appium/android-apidemos ?
If this error was by Android Q stuff, then https://github.com/appium/android-apidemos/pull/34 or https://github.com/appium/android-apidemos/pull/60 may fix this.

**Comment by omprakashchavan01** [comment]
Nope. We're using this one: https://github.com/appium/appium/blob/master/sample-code/apps/ApiDemos-debug.apk

I'm trying to build the APK from https://github.com/appium/android-apidemos, but the commands listed there seem not working. If you could let me know the command, I can try to build the app and try it out.

**Comment by KazuCocoa** [comment]
`npm run build`, then `./apks/ApiDemos-debug.apk` will be created

**Comment by omprakashchavan01** [comment]
I get below error:

D:\Git\android-apidemos>npm run build

> android-apidemos@3.3.1 build D:\Git\android-apidemos
> ./gradlew clean assembleDebug && npm run move-apk

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! android-apidemos@3.3.1 build: `./gradlew clean assembleDebug && npm run move-apk`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the android-apidemos@3.3.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ompra\AppData\Roaming\npm-cache\_logs\2021-04-21T16_35_51_842Z-debug.log

**Comment by mykola-mokhnach** [comment]
It probably won't work for Windows. You should use either Linux or Mac as a host

**Comment by KazuCocoa** [comment]
You can try https://github.com/appium/ruby_lib_core/blob/master/test/functional/app/api.apk.zip or https://github.com/appium/python-client/blob/master/test/apps/ApiDemos-debug.apk.zip out.

**Comment by omprakashchavan01** [comment]
Update: 
Created the APK from https://github.com/appium/android-apidemos and the issue is no more observed on the build.
Thank you both for all your help.
