### ISSUE TITLE
Error: Appium Settings app is not running after 5000ms

### ISSUE THREAD

**Issue by lvxy-git** [appium/appium#15285]
## The problem

Error: Appium Settings app is not running after 5000ms

## Environment

* Appium version (or git revision) that exhibits the issue:1.20
* Last Appium version that did not exhibit the issue (if applicable):1.17
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: Android 10
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe:

## Details

Appium version 1.17 don't have this issue.

## Link to Appium logs

https://gist.github.com/lvxy-git/129aa72225421735952f096713c05578

**Comment by mykola-mokhnach** [comment]
Please provide the logcat output

**Comment by lvxy-git** [comment]
> Please provide the logcat output
Logcat (It happened around 14:12)：
https://gist.github.com/lvxy-git/1e450ef5fd62c27693ff847c6fdc147c

**Comment by lvxy-git** [comment]
@mykola-mokhnach 
It happened around 14:12：
https://gist.github.com/lvxy-git/1e450ef5fd62c27693ff847c6fdc147c

**Comment by mykola-mokhnach** [comment]
I don't see any explicit crashes or other issues. It could be (actually it is) that most of Chinese devices have modified firmwares, which change the behaviour of standard system utilities, like pgrep ones. Try to experiment with the actual pgrep command line (`D:\Android\Sdk\platform-tools\adb.exe -P 5037 -s e37144dd shell pgrep -f \(\[\[:blank:\]\]\|\^\)io\.appium\.settings\(\[\[:blank:\]\]\|\$\)`), so it could detect the running process properly. I cannot help much there, as the same hardware device model is needed to run such experiments.

**Comment by lvxy-git** [comment]
get result with the command:

G:\logcat>D:\Android\Sdk\platform-tools\adb.exe -P 5037 -s e37144dd shell pgrep -f "\(\[\[:blank:\]\]\|\^\)io\.appium\.settings\(\[\[:blank:\]\]\|\$\)"
/system/bin/sh: \^\)io\.appium\.settings\(\[\[:blank:\]\]\: inaccessible or not found
/system/bin/sh: \$\): inaccessible or not found
pgrep: xregcomp: trailing backslash (\)

It seems the command has something wrong?

**Comment by lvxy-git** [comment]
but i can find io.appium.settings with `adb.exe -P 5037 -s e37144dd shell pgrep -f io.appium.settings`
```
G:\logcat>D:\Android\Sdk\platform-tools\adb.exe -P 5037 -s e37144dd shell pgrep -f io.appium.settings
9471
```

**Comment by mykola-mokhnach** [comment]
does it help if you prefix pipe character with `^` : G:\logcat>D:\Android\Sdk\platform-tools\adb.exe -P 5037 -s e37144dd shell pgrep -f "\(\[\[:blank:\]\]\|\^\)io\.appium\.settings\(\[\[:blank:\]\]\^|\$\)"

**Comment by lvxy-git** [comment]
@mykola-mokhnach  same 
```
G:\logcat>adb.exe -P 5037 -s e37144dd shell pgrep -f "\(\[\[:blank:\]\]\^|\^\)io\.appium\.settings\(\[\[:blank:\]\]\^|\$\)"
/system/bin/sh: \^\)io\.appium\.settings\(\[\[:blank:\]\]\^: inaccessible or not found
/system/bin/sh: \$\): inaccessible or not found
```

**Comment by mykola-mokhnach** [comment]
Execution of `adb.exe shell pgrep -f "\(\[\[:blank:\]\]\|\^\)io\.appium\.settings\(\[\[:blank:\]\]\|\$\)"` command on my test env with Android 11 emulator running passes and returns the process ID. I don't know what else could be done there

**Comment by mykola-mokhnach** [comment]
Maybe the adb version is out of date?

**Comment by lvxy-git** [comment]
@mykola-mokhnach 
mac？ My colleague and I both get the error on win10.

**Comment by lvxy-git** [comment]
i fix it , by update my adb version. thank you.^ ^
