### ISSUE TITLE
Requesting info from app launch arguments when appium session is started

### ISSUE THREAD

**Issue by tulasikrishan89** [appium/appium#15287]
We have used below condition to reset app settings

`if ProcessInfo.processInfo.arguments.contains("appReset") {`

i tested with webdriveragent 
{
    "bundleId" :"bundle id of app", 
    "arguments":["appReset"]
}

How to add these custom arguments to appium capabilities, while starting appium session?

**Comment by mykola-mokhnach** [comment]
Kindly use Appium forum to ask questions. this is the place for issues

**Comment by tulasikrishan89** [comment]
thanks for point it.
