### ISSUE TITLE
[WebDriverAgent] xcodebuild exited with code '65' and signal 'null'

### ISSUE THREAD

**Issue by impuchunchegowda** [appium/appium#15294]
## The problem

[WebDriverAgent] xcodebuild exited with code '65' and signal 'null

## Environment
*Appium version (or git revision) that exhibits the issue: 1.20.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:MacOs Catalina 10.15.7
* Node.js version (unless using Appium.app|exe):12.8.1
* Npm or Yarn package manager:npm
* Mobile platform/version under test: iPad OS 14.4
* Real device or emulator/simulator:Real device iPad
* Appium CLI or Appium.app|exe:Appium desktop

## Details

I downloaded appium desktop and deployed integration app into my ipad from webdriveragent.xcodeproject . 
But I am getting xcode build fail when I add all the desired capabilities and run .

i did trouble shoot using the link -- https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md
created provision file and no errors on xcode while deploying integration app but  still I am getting xcode build fail when i run below desired capabilities.

## Link to Appium logs
![error log for appium](https://user-images.githubusercontent.com/68561768/115786496-83603e80-a386-11eb-807a-2eed9cb67560.png)

https://gist.github.com/impuchunchegowda/3f09f5f9eaa1790d7dd3999b71e1037c

## Code To Reproduce Issue [ Good To Have ]

{
  "platformName": "iOS",
  "platformVersion": "14.4",
  "deviceName": "iPad",
  "automationName": "XCUITest",
  "udid": "0000000",
  "app": "/Users/impuc/IPA/UAT.ipa",
  "xcodeOrgId": "000000",
  "xcodeSigningId": "iPhone Developer",
  "noReset": "true"
}

**Comment by mykola-mokhnach** [comment]
Please provide the log with `showXcodeLog` capability enabled

**Comment by mykola-mokhnach** [comment]
Appium 1.20.2 is not compatible with iOS 14.4
You need to use appium@beta there

**Comment by impuchunchegowda** [comment]
Hi Thanks for looking at my ticket. I tried installing appium Appium v1.20.0-beta.0  and run , still I am getting same error  xcodebuild exited with code '65' and signal 'null' and here is the link for the logs https://gist.github.com/impuchunchegowda/bf3c87608fbb7786964649b0db68cfa3.

Note: I have added "showIOSLog": "true" in my capabilities. Please take a look and advice.

**Comment by mykola-mokhnach** [comment]
> [IOSDeviceLog] Apr 23 12:18:55 tester1 securityd[110] : trustd[119]/1#11 LF=0 copy_parent_certificates Error Domain=NSOSStatusErrorDomain Code=-34018 "Client has neither application-identifier nor keychain-access-groups entitlements" UserInfo={numberOfErrorsDeep=0, NSDescription=Client has neither application-identifier nor keychain-access-groups entitlements}

I assume the webdriveragent is not signed properly. Have you tried to build and deploy it manually from Xcode?

**Comment by impuchunchegowda** [comment]
Hi i did do manual configuration and deployed webdriveragent manually to the iPad see integration app and webdriveragentapp on ipad. But still I see same error when I run.
<img width="1538" alt="Screen Shot 2021-04-23 at 1 56 00 PM" src="https://user-images.githubusercontent.com/68561768/115919705-cf6eba00-a43e-11eb-8c98-67c75ebc2dea.png">

https://gist.github.com/impuchunchegowda/1c2adefc3b93388a97bd26e9c2d98948 THIS IS MY ERROR LOG.

Note: I folllowed this link for manual configuration https://github.com/imurchie/appium-xcuitest-driver/blob/master/docs/real-device-config.md#basic-manual-configuration

**Comment by KazuCocoa** [comment]
How about your configuration addressed as the below line in the basic-manual-configuration site? (it is in `Build Settings` tab)

> This necessitates manually changing the bundle id for the target by going into the "Build Settings" tab, and changing the "Product Bundle Identifier" from com.facebook.WebDriverAgentRunner to something that Xcode will accept:

**Comment by impuchunchegowda** [comment]
<img width="968" alt="Screen Shot 2021-04-23 at 3 33 37 PM" src="https://user-images.githubusercontent.com/68561768/115927197-aacc0f80-a449-11eb-8b4d-51af8bfe17e9.png">
<img width="935" alt="Screen Shot 2021-04-23 at 3 34 11 PM" src="https://user-images.githubusercontent.com/68561768/115927218-b3bce100-a449-11eb-9a5b-d4e1582ea141.png">

I think I have set it right, no issues there

**Comment by KazuCocoa** [comment]
What about your provisioning profile? Xcode 11+ has a new rule about the identifier, so you should allow `.xctrunner` if your provisioning profile did not have `*` to allow subdomains.
https://appium.io/docs/en/drivers/ios-xcuitest-real-devices/#troubleshooting-ideas

**Comment by mykola-mokhnach** [comment]
Are you sure it is a developer account and not an enterprise one?

**Comment by impuchunchegowda** [comment]
Hi it’s an enterprise account , can’t we use enterprise account ?

**Comment by KazuCocoa** [comment]
Yes since someday. Probably the enterprise one does not have _iOS Distribution certificate_

> Make sure the provisioning profile has iOS Distribution certificate
> https://appium.io/docs/en/drivers/ios-xcuitest-real-devices/#troubleshooting-ideas

**Comment by impuchunchegowda** [comment]
Do you mean enterprise account holders can't work on appium. Whats the resolution you suggest?

**Comment by KazuCocoa** [comment]
You can use a developer profile instead of an enterprise one to launch Appium/WDA.

I haven't used enterprise one, so I don't know enterprise account stuff well. But if you were able to launch WDA via Xcode but it did not work via `xcodebuild` command (as Appium did), probably enterprise profile does not allow to run an app on a real device via xcodebuild command by Apple's security design as addressed in the troubleshooting link.
(I heard a case testing an enterprise app via Appium worked, so testing the app by Appium itself may work still.)

This limitation could change by Apple's update, but probably current behavior is so. (We only can assume by observing the behavior)

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by RZahr** [comment]
No one is facing this issue anymore ? I am always receiving this random issue that occurs out of nowhere and sticks. 
I have no idea why and not sure if there are any fixes for this. Running android tests with Appium is super straightforward not sure why on iOS its this difficult
