### ISSUE TITLE
File upload to web using Chrome - ERR_ACCESS_DENIED

### ISSUE THREAD

**Issue by rchougule** [appium/appium#15293]
## The problem

I am trying to upload a file to https://the-internet.herokuapp.com/upload via Chrome using Appium. But it leads to `ERR_ACCESS_DENIED` error all the time.

The file resides in the `Download` folder of my device.

Refer the image below:
![image](https://user-images.githubusercontent.com/22256912/115739020-3478d000-a3ab-11eb-900a-88f1fa433e28.png)

## Environment

* Appium version (or git revision) that exhibits the issue: Tried from 1.10.x to 1.20.x
* Last Appium version that did not exhibit the issue (if applicable): None yet
* Desktop OS/version used to run Appium: Mac OSX Catalina
* Node.js version (unless using Appium.app|exe): 12 LTS
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Android 10
* Real device or emulator/simulator: Real device - Samsung Galaxy S9
* Chromedriver: 90.0.4430.24 (Tried for Chrome 81 as well, same error).
* Appium CLI or Appium.app|exe: I used the `npx appium` command to start appium server.

## Details
- The script attached below works totally fine with desktop browsers (using selenium).
- I have tried the following capabilities as well with different combinations, but it didn't help: `noReset, autoGrantPermissions, fastReset`.
- The script executes fine till the `send_keys` step. But as soon as the `file-submit` click is performed, it leads to the mentioned error. I tried it on https://fileconvoy.com/ as well and it results in the same error.

### What all I have tried:

- Granted permissions via the following command explicitly before starting appium (and also midway through the script in case the permissions get reset), but no luck.
```
adb -P 5037 shell 'pm grant com.android.chrome android.permission.READ_EXTERNAL_STORAGE  android.permission.WRITE_EXTERNAL_STORAGE'
```
- Instead of using `browserName: "Chrome"`, I have also tried specifying `appPackage` and `appActivity` to begin chrome. But no luck.
- Tried the `noReset: true` capability to prevent appium from executing `pm clear com.android.chrome`. (Just in case if running this was resetting the permissions). But even after adding this, it led to the same error.

## Link to Appium logs

1. Appium logs without using `noReset: true` capability: https://gist.github.com/rchougule/2f803f3d8ad81b51d7af0b4ebd3748fb
2. Appium logs with using `noReset: true` capabiity: https://gist.github.com/rchougule/9574b2310794ba1c8e1894c6625aa20e
- Tried this when I explicitly granted permissions to the chrome app before running the session and wanted to prevent appium from running `pm clear com.android.chrome` (which would reset the granted permissions to the app).

## Code To Reproduce Issue [ Good To Have ]

```python
from appium import webdriver
import time

def execute_script():
  driver = webdriver.Remote(
      command_executor='http://0.0.0.0:4723/wd/hub',
      desired_capabilities={
          "platform": "android",
          "platformName": "android",
          "platformVersion": "10",
          "deviceName": "<xxxx>",
          "udid": "<xxxx>",
          "browserName": "chrome",
          "automationName": "UIAutomator2",
          "chromeOptions": {
              "w3c": False
          },
          # "autoGrantPermissions": True,
          # "noReset": True,
          # "fastReset": True,
          # "fullReset": False
      }
  )

  driver.get('https://the-internet.herokuapp.com/upload')

  up = driver.find_element_by_id("file-upload")
  up.send_keys("/sdcard/Download/file.pdf")
  driver.find_element_by_id("file-submit").click()

  driver.quit()

driver = execute_script()
```

Is there anything that I am fundamentally missing?

Let me know if there is anything else that I should share.

Have posted the same on StackOverflow too: https://stackoverflow.com/questions/67213841/appium-file-upload-to-web-using-chrome-err-access-denied

**Comment by mykola-mokhnach** [comment]
I assume this is the limitation of the chromedriver itself. You could try the approach described in https://www.seleniumeasy.com/appium-tutorials/upload-file-using-appium-on-device as a possible workaround

**Comment by rchougule** [comment]
@mykola-mokhnach Thanks for the response.

I have already tried that using Python and Ruby.

According to the article, it clicks on the `button` which results in the file-explorer coming up. Whereas in my case, it leads to the following exception (also tried in `w3c` mode, same error):

```
[HTTP] --> POST /wd/hub/session/9d9d4d73-5f37-4fe4-ba10-77b1bdeea606/element
[HTTP] {"using":"css selector","value":"[name=\"upfile\"]"}
[W3C (9d9d4d73)] Driver proxy active, passing request on via HTTP proxy
[debug] [WD Proxy] Matched '/wd/hub/session/9d9d4d73-5f37-4fe4-ba10-77b1bdeea606/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /wd/hub/session/9d9d4d73-5f37-4fe4-ba10-77b1bdeea606/element] to [POST http://127.0.0.1:8006/wd/hub/session/da072586327a31ddc18fe57569a9c20c/element] with body: {"using":"css selector","value":"[name=\"upfile\"]"}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"da072586327a31ddc18fe57569a9c20c","status":0,"value":{"ELEMENT":"0.8485960799719281-1"}}
[WD Proxy] Replacing sessionId da072586327a31ddc18fe57569a9c20c with 9d9d4d73-5f37-4fe4-ba10-77b1bdeea606
[HTTP] <-- POST /wd/hub/session/9d9d4d73-5f37-4fe4-ba10-77b1bdeea606/element 200 27 ms - 156
[HTTP]
[HTTP] --> POST /wd/hub/session/9d9d4d73-5f37-4fe4-ba10-77b1bdeea606/element/0.8485960799719281-1/click
[HTTP] {"id":"0.8485960799719281-1"}
[W3C (9d9d4d73)] Driver proxy active, passing request on via HTTP proxy
[debug] [WD Proxy] Matched '/wd/hub/session/9d9d4d73-5f37-4fe4-ba10-77b1bdeea606/element/0.8485960799719281-1/click' to command name 'click'
[debug] [WD Proxy] Proxying [POST /wd/hub/session/9d9d4d73-5f37-4fe4-ba10-77b1bdeea606/element/0.8485960799719281-1/click] to [POST http://127.0.0.1:8006/wd/hub/session/da072586327a31ddc18fe57569a9c20c/element/0.8485960799719281-1/click] with body: {"id":"0.8485960799719281-1"}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"da072586327a31ddc18fe57569a9c20c","status":61,"value":{"message":"invalid argument\n  (Session info: chrome=90.0.4430.82)\n  (Driver info: chromedriver=90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429}),platform=Mac OS X 10.15.0 x86_64)"}}
[debug] [W3C (9d9d4d73)] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: The request to /wd/hub/session/9d9d4d73-5f37-4fe4-ba10-77b1bdeea606/element/0.8485960799719281-1/click has failed
[debug] [W3C (9d9d4d73)]     at JWProxy.proxy (/Users/chaugs_rohan/.npm/_npx/50720/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:218:13)
[debug] [W3C (9d9d4d73)]     at ProtocolConverter.convertAndProxy (/Users/chaugs_rohan/.npm/_npx/50720/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/protocol-converter.js:245:12)
[debug] [W3C (9d9d4d73)]     at JWProxy.proxyCommand (/Users/chaugs_rohan/.npm/_npx/50720/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:254:12)
[debug] [W3C (9d9d4d73)]     at JWProxy.proxyReqRes (/Users/chaugs_rohan/.npm/_npx/50720/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:304:36)
[debug] [W3C (9d9d4d73)]     at Chromedriver.proxyReq (/Users/chaugs_rohan/.npm/_npx/50720/lib/node_modules/appium/node_modules/appium-chromedriver/lib/chromedriver.js:675:12)
[debug] [MJSONWP] Matched JSONWP error code 61 to InvalidArgumentError
[HTTP] <-- POST /wd/hub/session/9d9d4d73-5f37-4fe4-ba10-77b1bdeea606/element/0.8485960799719281-1/click 400 38 ms - 970
```

My script:

```python
from appium import webdriver
import time

def execute_script():
  driver = webdriver.Remote(
      command_executor='http://0.0.0.0:4723/wd/hub',
      desired_capabilities={
          "platform": "android",
          "platformName": "android",
          "platformVersion": "10",
          "deviceName": "2a65dd680b057ece",
          "udid": "2a65dd680b057ece",
          "browserName": "chrome",
          "automationName": "UIAutomator2",
          "chromeOptions": {
              "w3c": False
          }
      }
  )

  driver.get("http://cgi-lib.berkeley.edu/ex/fup.html")
  driver.execute_script("window.scrollBy(0, 800)")
  a = driver.find_element_by_name("upfile")
  print(a)
  a.click()
 

  time.sleep(20)

  driver.quit()

driver = execute_script()

```

I also tried performing the `click` operation via execute script. But nothing happens. I get `200` status response but no file-explorer opens up.
```python
driver.execute_script('let a = document.getElementsByName("upfile")[0]; a.click()')
```
```
[HTTP] --> POST /wd/hub/session/b318d32f-8c0d-4169-b194-6713b0890cc8/execute/sync
[HTTP] {"script":"let a = document.getElementsByName(\"upfile\")[0]; a.click()","args":[]}
[debug] [W3C (b318d32f)] Calling AppiumDriver.execute() with args: ["let a = document.getElementsByName(\"upfile\")[0]; a.click()",[],"b318d32f-8c0d-4169-b194-6713b0890cc8"]
[debug] [WD Proxy] Matched '/execute' to command name 'execute'
[debug] [Protocol Converter] Did not know how to rewrite the original URL '/execute' for MJSONWP protocol
[debug] [WD Proxy] Proxying [POST /execute] to [POST http://127.0.0.1:8010/wd/hub/session/c63ba629a0346c65cf5484a839bc20b6/execute] with body: {"script":"let a = document.getElementsByName(\"upfile\")[0]; a.click()","args":[]}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"c63ba629a0346c65cf5484a839bc20b6","status":0,"value":null}
[debug] [W3C (b318d32f)] Responding to client with driver.execute() result: null
[HTTP] <-- POST /wd/hub/session/b318d32f-8c0d-4169-b194-6713b0890cc8/execute/sync 200 18 ms - 14
```

**Comment by mykola-mokhnach** [comment]
Because in the original article the click action is done from native context rather than from web one. Like I said above this is a crhomedriver limitation and there is nothing to do about it from Appium side

**Comment by rchougule** [comment]
I am sorry if I misunderstood the article.

But I think they click on the `button` first (since it's in the webview) and then switch to the native context to be able to interact with the file explorer.

![Screenshot 2021-04-23 at 1 19 22 PM](https://user-images.githubusercontent.com/22256912/115837953-c7ab1780-a436-11eb-9d5f-cd79d570bcd5.png)
![image](https://user-images.githubusercontent.com/22256912/115838068-ea3d3080-a436-11eb-8c63-ee7eac55b6ad.png)

Regarding the limitation, thanks for pointing that out. Will try to create an issue at chromedriver's side.

**So, as far as I understand till now**:
There is no way to select and upload a file in Chrome using Appium? The reason I am a bit surprised is because this seems like a very trivial use-case.

**Comment by KazuCocoa** [comment]
Basically, the error is Android security stuff, I assume.
So, the path to `up.send_keys("/sdcard/Download/file.pdf")`  on the device local was not able to access via chrome (even the permission grant command)
I wondered https://www.seleniumeasy.com/appium-tutorials/upload-file-using-appium-on-device worked only on emulator which had more relaxed security than a real device.

For example, `/data/local/tmp/sample.png` on an emulator worked as the original step https://github.com/appium/appium/issues/15293#issue-865105120 on my local via Appium (automationName chrome)

**Comment by rchougule** [comment]
@KazuCocoa Yes. It seems it's an issue around the permissions.
But even after trying to grant the permissions beforehand, and also while running the test, it resulted in the same issue.

Any suggestions as to where can I start looking for the same?

**Comment by KazuCocoa** [comment]
I tried on my deal device. `/data/local/tmp/sample.png` worked.

So, push a file via Appium's push file API in `/data/local/tmp/sample.png` -> send_key the path -> submit may work.
(But it might depend on devices in real devices case)

I haven't modify permissions.

**Comment by rchougule** [comment]
@KazuCocoa Thanks for the response.

Yeah, it seems like it's a directory permission issue with Chrome. It doesn't have access to `/sdcard/Download/` directory. And neither does it asks for permission while downloading/uploading files to/from that directory.

Have added the detailed findings to the linked StackOverflow question (Refer [here](https://stackoverflow.com/a/67234402/6710750) for the same).

So, it's mostly around how Android 9 (and below) vs 10+ behave with the permissions and access to storage.

Closing the issue since it's not related to Appium.
