### ISSUE TITLE
Test Apple Universal apps with Appium

### ISSUE THREAD

**Issue by insidiaGithub** [appium/appium#15291]
## The problem

Hello!
Is it possible to test iOS apps on mac with M1? I mean test it without simulator. I tried to install our iOS application on mac with m1 and tried to create appium session with mac2 driver. It launches the application but then it throws a timeout exception.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2
* Last Appium version that did not exhibit the issue (if applicable): no
* Desktop OS/version used to run Appium: MacOS Big Sur 11.2.3
* Node.js version (unless using Appium.app|exe): Appium.app
* Npm or Yarn package manager: Npm
* Mobile platform/version under test: ios apps running on m1 without simulator
* Real device or emulator/simulator: ios apps running on m1 without simulator
* Appium CLI or Appium.app|exe: Appium.app

## Link to Appium logs

https://gist.github.com/insidiaGithub/6333f2dbe5830da4409817772abeaa66

## Code To Reproduce Issue [ Good To Have ]
            var appiumOptions = new AppiumOptions();
            appiumOptions.AddAdditionalCapability("automationName", "Mac2");
            appiumOptions.AddAdditionalCapability("platformName" , "mac");
            appiumOptions.AddAdditionalCapability("bundleId", "com.acumatica.ios.client");

            var driver = new MacDriver<MacElement>(new Uri("http://localhost:4723/wd/hub"), appiumOptions);

Exception message: "The HTTP request to the remote WebDriver server for URL http://localhost:4723/wd/hub/session timed out after 60 seconds."

**Comment by mykola-mokhnach** [comment]
Please provide a proper issue description according to the template

**Comment by insidiaGithub** [comment]
> Please provide a proper issue description according to the template

I provided description according to the template, but it is just a question. Has anyone tried to do this at all?

**Comment by mykola-mokhnach** [comment]
Could you please also attach the server log with Xcodebuild logging. enabled (`showServerLogs`)?

**Comment by insidiaGithub** [comment]
> Could you please also attach the server log with Xcodebuild logging enabled (`showServerLogs`)?

Sure https://gist.github.com/insidiaGithub/2ba39d6bbb3d02176796775412067a33

**Comment by mykola-mokhnach** [comment]
> [WebDriverAgentMac] [xcodebuild] /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-mac2-driver/WebDriverAgentMac/WebDriverAgentRunner/WebDriverAgentRunner.m:40: error: -[UITestingUITests testRunner] : Application 'com.acumatica.ios.client' does not have a process ID

I assume it is something on XCTest side. Not my to do from Appium side though

**Comment by insidiaGithub** [comment]
> I assume it is something on XCTest side. Not much to do from Appium side though

Thanks. So we will wait for an update from Apple
