### ISSUE TITLE
''browserName cannot be set together with 'bundleId' capability

### ISSUE THREAD

**Issue by john334596** [appium/appium#15300]
## The problem

I’m trying to launch an native ios app in real device of saucelabs and added below capabilities in my code:

DesiredCapabilities dc=new DesiredCapabilities();
dc.setCapability(“platformName”,“iOS”);
dc.setCapability(“udid”,“0000012GH4”);
dc.setCapability(“platformVersion”,“13.2”);
dc.setCapability(“bundleID”,“com.test”);
IOSDriver driver=new IOSDriver (new URL(URL),dc);

Once the execution starts it gets failed with error - 'browserName cannot be set together with ‘bundleId’ capability" . Although I m not passing the browserName as the capability or tried setting browsername=""; in capability but in both the cases I get the same error and in the test execution logs I can see browserName is itself setting to value ‘safari’. 

Is there any way i can unset or tell the test to not include browsername?

## Environment

- Appium version: 1.19.1
- Real device -iPad
- ios version -13.2

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Please provide the server log

**Comment by john334596** [comment]
@mykola-mokhnach - please find log below
{
"httpMethod": "POST",
"httpPathInfo": "",
"requestBody":"{\"desiredCapabilities\":{\"testobject_platform_name\":iOS\",\"realDevice\":true,\"appiumVersion\":\"1.20.1",
\"bundleId\":\"com.test\",\"testobject_device\":\"iPad 12.9 2018\",\"automationName\":XCUITest\",\"browserName\":\"safari"\",
\"platformName\":\"iOS\",\"udid\":\"0000012GH4\"}}",
"responseBody":"{\status\":13,\"value\":\"message\":\"An unknown server-side error occured while processing the command.Original error: 'browserName' cannot be set together with 'bundleId' capability\",\"sessionId\":null},
"responseStatus":500,
"statusCode":13
}

As you can see the browsername is showing as safari evn though i m not passing the browsername or passing it as empty string.

**Comment by mykola-mokhnach** [comment]
It could be that your client framework adds it implicitly. 

Have you tried to report the issue to SauceLabs?

I don't observe any Appium issues there.

**Comment by john334596** [comment]
what do you mean by client framework? you mean saucelabs is adding this capability implicitely.. they have themselves mention to add this capability as empty string but even in that case it is showing safari in logs.

**Comment by mykola-mokhnach** [comment]
> what do you mean by client framework? you mean saucelabs is adding this capability implicitely

I mean this capability could either be added somewhere in your code or on the cloud provider's side. One could sniff the local traffic and verify the JSON request, sent to the provided, to confirm that correct capabilities are provided locally and the issue lies in the provider's codebase.

> they have themselves mention to add this capability as empty string but even in that case it is showing safari in logs.

Nothing to advice here unless I could see the actual logs with this cap being set to an empty string

**Comment by john334596** [comment]
Logs i have already provided from saucelabs end but I can try executing from appium desktop but if you can tell me where to check the logs or appium capabilities while using appium desktop so i can share then. 

From the code I am passing like this --> dc.setCapability(“browserName”,"”);

**Comment by mykola-mokhnach** [comment]
I assume Sauce simply does not support the given set of capabilities, e.g. `bundleId` without `app` or `browserName`. There is nothing we can do about it from Appium side. Perhaps, they could provide more useful error message though.

Closed as not an issue.
