### ISSUE TITLE
WebDriverAgent.xcodeproj build failed

### ISSUE THREAD

**Issue by wangyuqi7** [appium/appium#15312]
## The problem

WebDriverAgent.xcodeproj build fails after installing WebDriverAgentRunner

## Environment

* Appium version (or git revision) that exhibits the issue:1.20.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 10.15.7
* Mobile platform/version under test: Xcode version: 12.1
* Real device or emulator/simulator:  ios 14.1
* Appium CLI or Appium.app|exe:

## Details

![image](https://user-images.githubusercontent.com/70121135/116676482-9bb10880-a9d9-11eb-952b-1caec7a89f69.png)

## Link to Appium logs

When installed WebDriverAgentRunner and building project on my mobile phone, xcode reported an error "*** Terminating app due to uncaught exception'NSInternalInconsistencyException', reason:'A test configuration must be provided to _XCTestMain.'"

2021-04-30 17:15:30.077482+0800 WebDriverAgentRunner-Runner[321:6362] Running tests...
2021-04-30 17:15:30.078119+0800 WebDriverAgentRunner-Runner[321:6362] *** Assertion failure in void _XCTestMain(XCTestConfiguration *__strong _Nonnull)(), /Library/Caches/com.apple.xbs/Sources/XCTest_iOS/XCTest-16091.4/Sources/XCTestFramework/Harness/XCTestMain.m:240
2021-04-30 17:15:30.079393+0800 WebDriverAgentRunner-Runner[321:6362] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'A test configuration must be provided to _XCTestMain.'
*** First throw call stack:
(0x1a67d65ac 0x1ba8c442c 0x1a66df1b4 0x1a7a93c80 0x100d56b3c 0x100a59674 0x100a59658 0x1a6753564 0x1a67527b8 0x1a674cd34 0x1a674c4bc 0x1bd25e820 0x1a90f9164 0x1a90fe840 0x100a59840 0x1a6413e40)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'A test configuration must be provided to _XCTestMain.'
terminating with uncaught exception of type NSException
(lldb)å

**Comment by mykola-mokhnach** [comment]
I cannot reproduce such issue. Try to upgrade Xcode and WebDriverAgent to the most recent versions

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by wendan52** [comment]
Appium version:1.22.2
Xcode version: 12.4 (12D4e)
device version: iPhone8 plus iOS 13.3.1
I have downloaded WebDriverAgent and replaced /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent
when I run test，xcode reported the same error
