### ISSUE TITLE
Need some info on the usage of app capability

### ISSUE THREAD

**Issue by john334596** [appium/appium#15313]
## The problem

I need some clarity how the 'app' works as a capability for below two cases.

## Environment

Appium version: 1.19.1
Real device -iPad
ios version -13.2

## Details

I’m trying to launch a native ios app in real device of saucelabs and added below capabilities in my code:

DesiredCapabilities dc=new DesiredCapabilities();
dc.setCapability(“platformName”,“iOS”);
dc.setCapability(“udid”,“0000012GH4”);
dc.setCapability(“platformVersion”,“13.2”);
dc.setCapability(“app”, "storage:32423er2838");
IOSDriver driver=new IOSDriver (new URL(URL),dc);

**Case1:** App not installed into device
If I execute the above code then it launches the app into the specified device. I believe that in this case the app is getting installed and then launching itself.

**Case2:** App installed into device
In this case if I execute the above code i see the app is launched but I am confused whether the app is getting launched directly or app is getting installed and then launching it?

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Please constant SauceLabs customer support to get your answers. I believe app installation algorithm works differently in cloud comparison to how it is implemented in "pure" standalone Appium server. 

For the future kindly use Appium forum to ask questions.
