### ISSUE TITLE
Cannot set traditional chinese. Always defaults to simplified chinese

### ISSUE THREAD

**Issue by gkvappium** [appium/appium#15318]
## The problem

I am trying to set traditional Chinese in the desired capabilities. But it always defaults to Simplified Chinese

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOSX
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager: Npm
* Mobile platform/version under test: Android 10/11
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

I've tried with 3 different locales that supports traditional chinese (Desired cap: language = "zh", locale = "HK"/"MO"/"TW"). But when the appium session starts, it is set to Simplified Chinese. In the app we do support both these languages. So it is rather important for me to set traditional chinese explicitly. 

zh_HK [Chinese (Traditional Han,Hong Kong)]
zh_MO [Chinese (Traditional Han,Macau)]
zh_TW [Chinese (Traditional Han,Taiwan)]

**Comment by gkvappium** [comment]
Hi @mykola-mokhnach ,

Please find the link for the appium server log (https://gist.github.com/gkvappium/3b887bf975353db380e5ae6b295f8935)

**Comment by mykola-mokhnach** [comment]
Try to also provide [localeScript](https://github.com/appium/appium-uiautomator2-driver#app-localization) value. I do observe that device locale has been sett properly though according to what was requested in the logs (`Current device property 'persist.sys.locale': zh-TW`). @KazuCocoa do you see any issues there?

**Comment by gkvappium** [comment]
Hello @mykola-mokhnach , thanks for looking into the logs.

Tried adding localeScript :zh-Hant-TW/MO/HK. Get the error that the session is undefined. Also tried by removing language and local and just by passing localeScript: zh-Hant-TW. In this case there is no error but the language didn't change. It retained the previous language which was english

**Comment by mykola-mokhnach** [comment]
The correct script name is `zh-Hans..`. Please attach the updated log containing the error

**Comment by gkvappium** [comment]
@mykola-mokhnach , sorry isn't zh-Hant for Traditional Chinese?

But I gave it a try with zh-Hans-TW and just zh-Hans. But I can't set it to traditional Chinese. I get session undefined when I add localeScript together with locale and language (https://gist.github.com/gkvappium/12cbc6d4419a812d463cec8dd4436abc) 

When I just have localeScript with value zh-Hans or zh-Hans-TW, it retains the old language. Please note that I never had a problem with Simplified Chinese when I set language as zh and locale as CN

**Comment by mykola-mokhnach** [comment]
> [debug] [ADB] Current locale: 'en-US'; requested locale: 'zh-zh-Hans-TW-TW'

Try to provide 

```
{
  language: 'zh' ,
  languageScript: 'Hant',
  country: 'TW',
```

as capabilities

**Comment by KazuCocoa** [comment]
Yes, `languageScript ` is `script` in https://developer.android.com/reference/java/util/Locale.html. `language` and `country`  are `language` and `country (region)` in the same page. So https://github.com/appium/appium/issues/15318#issuecomment-831273821 should be set correctly.

**Comment by gkvappium** [comment]
Hi @mykola-mokhnach @KazuCocoa , thank you for your inputs. On android it worked with the below combination. Phone lang was set to Traditional Chinese and worked fine on the app side. 

{
  language: 'zh' ,
  localeScript: 'Hant',
  locale: 'TW',
}

But the localeScript is specific to Android correct? What can I do on iOS to switch the app language to Traditional Chinese. The usual way of setting language: 'zh' and locale: 'TW' fails on iOS only for Traditional Chinese. It works for all other combinations. I've checked https://github.com/appium/appium-xcuitest-driver#desired-capabilities and couldn't find anything additional for iOS

**Comment by KazuCocoa** [comment]
`-AppleLanguages` and `-AppleLocale` are used https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/TestingYourInternationalApp/TestingYourInternationalApp.html#//apple_ref/doc/uid/10000171i-CH7-SW2 for iOS as `language` and `locale`.

I haven't tried Chinese, but may https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/LanguageandLocaleIDs/LanguageandLocaleIDs.html help? The `Language IDs` is probably `language` and `Locale IDs` is probably `locale`.

**Comment by gkvappium** [comment]
@KazuCocoa , --AppleLanguages and --AppLocale doesn't seem to do anything.  I think Traditional Chinese is not settable on iOS. However, Simplified Chinese works fine (Example locale: CN and language: zh)

**Comment by mykola-mokhnach** [comment]
I would try to set AppleLanguages to `(zh-Hant-CN)` and locale to `zh_CN`

**Comment by gkvappium** [comment]
@mykola-mokhnach , @KazuCocoa ,

Turns out that 1 single combination works for both Android and iOS (language: zh and locale: Hant). So localeScript is not really needed for Android. Also the combination that you suggested for iOS worked as well.

Sorry, I'll the close the bug since it's working fine. Ran into this because of incorrect understanding of the documentation. Thanks a lot for your hints though. It really did help
