### ISSUE TITLE
can not run tests on real ios device: 

### ISSUE THREAD

**Issue by arhanechka** [appium/appium#15327]
Passed all the steps with setting new bundle id for WDA in Xcode and WDA builds successfully on device from it. But when I try to run appium tests, get 
Testing failed:
[Xcode] 	No signing certificate "iOS Development" found: No "iOS Development" signing certificate matching team ID "<my-team-id>" with a private key was found.
[Xcode] 	No profiles for 'WebDriverAgentRunner.<my-team-id>.xctrunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'WebDriverAgentRunner.<my-team-id>.xctrunner'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
Full logs:
[appium logs.pdf](https://github.com/appium/appium/files/6428372/appium.logs.pdf)

**Comment by mykola-mokhnach** [comment]
This is clearly an issue with signing. Are you sure you use the same WebDriverAgent sources to run your automated tests that are used for manual compilation in Xcode? Do you provide correct signing capabilities for the automated test? 
Please fill out the issue report according to the requested template

**Comment by mykola-mokhnach** [comment]
Closed because of no response
