### ISSUE TITLE
[Appium v1.21.0] (node:10286) [DEP0128] DeprecationWarning

### ISSUE THREAD

**Issue by yavgel** [appium/appium#15320]
![image](https://user-images.githubusercontent.com/8123409/116882758-1a4db600-ac25-11eb-8378-8748a56c40f3.png)

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing we could do about it as this is a third-party dependency. Please report the issue to the module author.

**Comment by mykola-mokhnach** [comment]
Actually, I see this import is only used in tests, so it makes sense to move it to development dependencies, which has been done in https://github.com/appium/appium-support/pull/223

**Comment by yavgel** [comment]
> Actually, I see this import is only used in tests, so it makes sense to move it to development dependencies, which has been done in [appium/appium-support#223](https://github.com/appium/appium-support/pull/223)

does it mean that the next release will fix my issue?
