### ISSUE TITLE
WebDriverAgent starts but crashes on iOS 14.5.1 and Xcode 12.5

### ISSUE THREAD

**Issue by sai-tirunagiri** [appium/appium#15329]
## The problem

I am trying to run webdriveragent using the command "xcodebuild test-without-building -xctestrun", the webdriveragent starts but it crashes with the below message, and I am not sure why.

```
** BUILD INTERRUPTED **
zsh: terminated  /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild  -xctestrun
```

## Environment

* Appium version - 1.20.2
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: MACOS BigSur - 11.2.3
* Node.js version (unless using Appium.app|exe): v12.18.3
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: iOS/14.5.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI
* Xcode version: 12.5

## Details

The webdriveragent successfully runs without crashing if I downgrade the Xcode version to 12.4 and iOS version **below** 14.5.

## Link to Appium logs

https://gist.github.com/sai-tirunagiri/83189c2f37cc6c3c11645adb21c9c31b

Please advice.

Thanks.

**Comment by mykola-mokhnach** [comment]
Appium 1.20 is not compatible to iOS 14.5. Consider updating to v 1.21
Also, please attach the log with xcodebuild logging enabled

**Comment by sai-tirunagiri** [comment]
Hi, @mykola-mokhnach I upgraded the appium version to v 1.21 but still no luck, and here is the xcodebuild logs - https://gist.github.com/sai-tirunagiri/967856c19b81a8dd4c0dd1b42f8bba8a

Thanks

**Comment by mykola-mokhnach** [comment]
> [Xcode] ** BUILD INTERRUPTED **

It seems that Webdriveragent building takes more time than allowed on your machine. Try to change the values for wdaStartupRetries/wdaStartupRetryInterval capabilities

**Comment by mykola-mokhnach** [comment]
How much time it takes to build WDA sources manually from Xcode?

**Comment by sai-tirunagiri** [comment]
from Xcode for the first time it took 1 min and 2 sec approx and I tried adding wdaStartupRetries/interval, but still no improvement and I notice this along with "build interrupted"

> Xcode] ** BUILD INTERRUPTED **
> [Xcode]
> [WebDriverAgent] xcodebuild exited with code 'null' and signal 'SIGTERM'

what does exited with code null mean.

**Comment by sai-tirunagiri** [comment]
strange thing is, everything seems to be smooth when I tested the same on the Xcode version to 12.4 and iOS 14.2.1.

**Comment by mykola-mokhnach** [comment]
Build interrupted means that WDA building took more time than allowed by wdaStartupRetryInterval. To which value did you set this capability?

**Comment by sai-tirunagiri** [comment]
This is what I set and tried

"wdaStartupRetryInterval": 2000,
"wdaLaunchTimeout": 120000

**Comment by sai-tirunagiri** [comment]
and here is another interesting thing. I somehow managed to start the wda by using the capability "usePreBuiltWda", the wda starts but after 10 sec in approx, it crashes.

```
[debug] [MJSONWP (35b21ea5)] Calling AppiumDriver.getWindowSize() with args: ["current","35b21ea5-643a-4656-b931-91de91ae6ad5"]
[debug] [XCUITest] Executing command 'getWindowSize'
[debug] [WD Proxy] Proxying [GET /window/size] to [GET http://127.0.0.1:8100/session/AAC379EA-3376-4B70-979D-BD43C274A0C4/window/size] with no body
[Xcode] 2021-05-06 01:51:50.923943+0530 WebDriverAgentRunner-Runner[1665:129531] Getting the most recent active application (out of 1 total items)
[Xcode]
[Xcode]     t =    12.05s Requesting snapshot of accessibility hierarchy for app with pid 1668
[Xcode]
[debug] [WD Proxy] Got response with status 200: {"value":{"width":375,"height":667},"sessionId":"AAC379EA-3376-4B70-979D-BD43C274A0C4"}
[debug] [MJSONWP (35b21ea5)] Responding to client with driver.getWindowSize() result: {"width":375,"height":667}
[HTTP] <-- GET /wd/hub/session/35b21ea5-643a-4656-b931-91de91ae6ad5/window/current/size 200 43 ms - 98
[HTTP]
[Xcode] 2021-05-06 01:51:50.952610+0530 WebDriverAgentRunner-Runner[1665:129531] Getting the most recent active application (out of 1 total items)
[Xcode]
[Xcode] ** BUILD INTERRUPTED **
[Xcode]
[WebDriverAgent] xcodebuild exited with code 'null' and signal 'SIGTERM'
```

**Comment by mykola-mokhnach** [comment]
It looks like the process is terminated. Try to figure out what is killing your process and make sure the session management works properly in your framework (consider enabling `--session-override` option if you don't need to run parallel sessions).

**Comment by sai-tirunagiri** [comment]
I am not using any framework, I am just using appium server and appium desktop with the below capability to test application on real ios device.
```
{
  "deviceName": "5126be31cfff436356a1627c09c9268136513a67",
  "app": "/Users/saiprasadt/Desktop/IntegrationApp-2021-04-29-15-02-32/IntegrationApp.ipa",
  "platformName": "iOS",
  "automationName": "XCUITest",
  "platformVersion": "14.5.1",
  "udid": "5126be31cfff436356a1627c09c9268136513a67",
  "useJSONSource": true,
  "showXcodeLog": true,
  "usePrebuiltWDA": true,
  "wdaLaunchTimeout": 60000,
  "useNewWDA": false
}
```

I will check the process

**Comment by mykola-mokhnach** [comment]
closed because of no response

**Comment by Thuytien** [comment]
I'm facing this issue too. Anyone knows how to fix it?

**Comment by sai-tirunagiri** [comment]
@Thuytien restart your device and try again

**Comment by Thuytien** [comment]
@sai-tirunagiri : thank you. In my case, it works with Appium-desktop v1.21.0

**Comment by JyotiKatiyar** [comment]
i am having mac os: big sur 11.4
Xcode: 13.0 
appium : 1.21.0
 and m not able to launch the app either from automation or appium, getting error like 
Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: connect ECONNREFUSED 127.0.0.1:8100

[](ur
[appium-server-logs.txt](https://github.com/appium/appium/files/7285023/appium-server-logs.txt)
l)
