### ISSUE TITLE
Appium doesn’t see spinner menu in app source

### ISSUE THREAD

**Issue by baselalali** [appium/appium#15330]
## The problem

We want to tap on element of spinner menu, but Appium inspector does not see the element of spinner menu in the page source
## Environment

* Appium version (or git revision) that exhibits the issue: v1.20.2
* Desktop OS/version used to run Appium: Desktop
* Mobile platform/version under test: Android
* Real device or emulator/simulator: real
* Appium CLI or Appium.app|exe: Appium app

Does Appium support the finding of element of spinner menu ?

**Comment by mykola-mokhnach** [comment]
Appium simply reflects what the app provides to the accessibility layer. You could try to play with snapshotMaxDepth setting as described in https://github.com/appium/appium/issues/14825. Otherwise there is not much we could do from Appium's side

**Comment by baselalali** [comment]
How i can edit with snapshotMaxDepth settings? 

the problem is, when i tap on dropdown, the driver could find the elements for android

**Comment by mykola-mokhnach** [comment]
This setting only works for iOS. For Android  the only way is to fix the application under test to make it more accessible.

**Comment by mykola-mokhnach** [comment]
Also if the element is a part of a web view and this web view is debuggable then it could be possible to switch to hybrid mode to interact with it.

**Comment by baselalali** [comment]
For Android the only way is to fix the application under test to make it more accessible. --> How i can fix the app under test

**Comment by baselalali** [comment]
The elements ist not part of web view ..

**Comment by mykola-mokhnach** [comment]
> How i can fix the app under test

No idea, depends on the actual source code. There are some general practices, though: https://developer.android.com/guide/topics/ui/accessibility/apps

**Comment by baselalali** [comment]
We have the content-id for element of spinner, but Appium does not see hem ...
