### ISSUE TITLE
XML source tree is different

### ISSUE THREAD

**Issue by vitalyk** [appium/appium#15339]
## The problem

Can say yet about how many locators are missing for each specific place in the application. But e.g. the following Xpath expression is no longer correct
`"//android.widget.LinearLayout[@resource-id='#{ENV['APP_PACKAGE']}:id/til_email']//android.widget.EditText"`
this part is missing in the source tree `//android.widget.LinearLayout[@resource-id='#{ENV['APP_PACKAGE']}:id/til_email']`
looks like attributes like @resource-id are missing. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable): 1.19.1
* Desktop OS/version used to run Appium: n/a
* Node.js version (unless using Appium.app|exe): 14.16.0
* Npm or Yarn package manager: 6.14.11
* Mobile platform/version under test: Android 10.0 - API 29
* Real device or emulator/simulator: Genymotion Samsung Galaxy S10, size 1080 x 1920, density 420 
* Appium CLI or Appium.app|exe: 1.21.0

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!
https://gist.github.com/vitalyk/d4306499306cccc3baf62837f79a7783

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Could you please provide the page source output from the previous server version and the current one?
Also please provide the page sources taken by raw uiautomator as described in https://stackoverflow.com/questions/39223464/where-to-see-the-xml-file-after-adb-shell-uiautomator-dump-view-xml

**Comment by vitalyk** [comment]
@mykola-mokhnach, thanks for tip. So I've double checked my capabilities (attached in Appium logs above) and tried first to remove `ignoreUnimportantViews`. And it works, at least for the mentioned page. Will need to run the regression on CI to see all results. I think issue can be closed.
