### ISSUE TITLE
Minor doc issue for python client library: 'get_settings' is shown as an attribute rather than a method

### ISSUE THREAD

**Issue by markbearden** [appium/appium#15342]
Summary: There is a **minor** typo in the sample code that documents python scripting of the "Retrieve Device Settings" Appium command (API `GET /session/:session_id/appium/settings`).

The snip of python code for scripting the Appium settings query is:
`self.driver.get_settings`
which suggests there is an attribute named `get_settings`, rather than a method named `get_settings().`

(To belabor the point, but trying to be perfectly clear) If one imitates the documentation and writes a python script containing `str(self.driver.get_settings)`, then this string identifying the method is the output, rather than the result of invoking the method:
`<bound method Settings.get_settings of <appium.webdriver.webdriver.WebDriver (session="....")>`

Source: https://github.com/appium/appium/blob/master/docs/en/commands/session/settings/get-settings.md
Current published: https://appium.io/docs/en/commands/session/settings/get-settings/index.html

**Comment by jlipps** [comment]
Thanks for this report!
