### ISSUE TITLE
ID locator strategy not working for `resource-id` elements generated by React Native 0.64

### ISSUE THREAD

**Issue by fantpmas** [appium/appium#15354]
## The problem

ID locator strategy not working for `resource-id` elements generated by React Native 0.64 using `testID`.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium Desktop 1.19.1, Appium CLI 1.21.0
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: MacOS Big Sur 11.2
* Node.js version (unless using Appium.app|exe): v14.16.1
* Npm or Yarn package manager: NA
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Both
* React Native: 0.64.0

## Details

Since https://github.com/facebook/react-native/pull/29610 has been merged, we can now use `testID` which is exposed via  a view's `resource-id`. However, it is impossible to locate these elements using their ID, both in Appium Desktop and Appium CLI. The elements are simply not found, even though they appear as `id` in Appium Desktop.

![Screen Shot 2021-05-10 at 14 05 10](https://user-images.githubusercontent.com/20792077/117658449-052fd480-b19b-11eb-9089-b73acf2ffaaf.png)

## Link to Appium logs

```
[MJSONWP (71a501f7)] Calling AppiumDriver.findElements() with args: ["id","backButton","71a501f7-6dca-4900-9031-28783ce7577b"]
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, css selector, -android uiautomator
[BaseDriver] Waiting up to 0 ms for condition
[WD Proxy] Matched '/elements' to command name 'findElements'
[WD Proxy] Proxying [POST /elements] to [POST http://127.0.0.1:8200/wd/hub/session/347565f6-94ae-4cd5-922f-9af19084f0da/elements] with body: {"strategy":"id","selector":"backButton","context":"","multiple":true}
[WD Proxy] Got response with status 200: {"sessionId":"347565f6-94ae-4cd5-922f-9af19084f0da","value":[]}
[MJSONWP (71a501f7)] Responding to client with driver.findElements() result: []
[HTTP] <-- POST /wd/hub/session/71a501f7-6dca-4900-9031-28783ce7577b/elements 200 51 ms - 74
```

## Code To Reproduce Issue

```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * Generated with the TypeScript template
 * https://github.com/react-native-community/react-native-template-typescript
 *
 * @format
 */

import React from 'react';
import {
  SafeAreaView,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  useColorScheme,
  View,
  TouchableOpacity
} from 'react-native';

import {
  Colors,
  DebugInstructions,
  Header,
  LearnMoreLinks,
  ReloadInstructions,
} from 'react-native/Libraries/NewAppScreen';

const Section: React.FC<{
  title: string;
}> = ({ children, title }) => {
  const isDarkMode = useColorScheme() === 'dark';
  return (
    <View style={styles.sectionContainer}>
      <Text
        style={[
          styles.sectionTitle,
          {
            color: isDarkMode ? Colors.white : Colors.black,
          },
        ]}>
        {title}
      </Text>
      <Text
        style={[
          styles.sectionDescription,
          {
            color: isDarkMode ? Colors.light : Colors.dark,
          },
        ]}>
        {children}
      </Text>
    </View>
  );
};

const App = () => {
  const isDarkMode = useColorScheme() === 'dark';

  const backgroundStyle = {
    backgroundColor: isDarkMode ? Colors.darker : Colors.lighter,
  };

  return (
    <SafeAreaView style={backgroundStyle}>
      <StatusBar barStyle={isDarkMode ? 'light-content' : 'dark-content'} />
      <ScrollView
        contentInsetAdjustmentBehavior="automatic"
        style={backgroundStyle}>
        <Header />
        <View
          style={{
            backgroundColor: isDarkMode ? Colors.black : Colors.white,
          }}>
          <TouchableOpacity
            accessible={true}
            accessibilityLabel="Go back"
            accessibilityHint="Navigates to the previous screen"
            testID="backButton"
          >
            <Text >Go Back</Text>
          </TouchableOpacity>

        </View>
      </ScrollView>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  sectionContainer: {
    marginTop: 32,
    paddingHorizontal: 24,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '600',
  },
  sectionDescription: {
    marginTop: 8,
    fontSize: 18,
    fontWeight: '400',
  },
  highlight: {
    fontWeight: '700',
  },
});

export default App;
```

**Comment by mykola-mokhnach** [comment]
I don't think there is anything we could do on Appium side about it. The page source is retrieved from the accessibility manager. Consider reporting the issue either to React or to Google

**Comment by mykola-mokhnach** [comment]
It could be you are using wrong location strategy. Have you read https://github.com/appium/appium-uiautomator2-driver#element-location ?

**Comment by mykola-mokhnach** [comment]
Could you also provide the actual page source XML?

**Comment by fantpmas** [comment]
Strange thing is, that both `com.testiddemo:id/action_bar_root` and `android:id/content` work if I look for them by `id`, but not `backButton`.
 
```
<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
<hierarchy index="0" class="hierarchy" rotation="0" width="1080" height="2072">
  <android.widget.FrameLayout index="0" package="com.testiddemo" class="android.widget.FrameLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,0][1080,2072]" displayed="true">
    <android.widget.LinearLayout index="0" package="com.testiddemo" class="android.widget.LinearLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,0][1080,2072]" displayed="true">
      <android.widget.FrameLayout index="0" package="com.testiddemo" class="android.widget.FrameLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,136][1080,2072]" displayed="true">
        <android.widget.LinearLayout index="0" package="com.testiddemo" class="android.widget.LinearLayout" text="" resource-id="com.testiddemo:id/action_bar_root" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,136][1080,2072]" displayed="true">
          <android.widget.FrameLayout index="0" package="com.testiddemo" class="android.widget.FrameLayout" text="" resource-id="android:id/content" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,136][1080,2072]" displayed="true">
            <android.widget.FrameLayout index="0" package="com.testiddemo" class="android.widget.FrameLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,136][1080,2072]" displayed="true">
              <android.view.ViewGroup index="0" package="com.testiddemo" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,136][1080,839]" displayed="true">
                <android.widget.ScrollView index="0" package="com.testiddemo" class="android.widget.ScrollView" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,136][1080,839]" displayed="true">
                  <android.view.ViewGroup index="0" package="com.testiddemo" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,136][1080,839]" displayed="true">
                    <android.view.ViewGroup index="0" package="com.testiddemo" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,136][1080,786]" displayed="true">
                      <android.widget.ImageView index="0" package="com.testiddemo" class="android.widget.ImageView" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,136][1080,786]" displayed="true" />
                      <android.widget.TextView index="1" package="com.testiddemo" class="android.widget.TextView" text="Welcome to&#10;React Native" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[88,400][992,676]" displayed="true" />
                    </android.view.ViewGroup>
                    <android.view.ViewGroup index="1" package="com.testiddemo" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,786][1080,839]" displayed="true">
                      <android.view.ViewGroup index="0" package="com.testiddemo" class="android.view.ViewGroup" text="" content-desc="Go back, Navigates to the previous screen" resource-id="backButton" checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,786][1080,839]" displayed="true">
                        <android.widget.TextView index="0" package="com.testiddemo" class="android.widget.TextView" text="Go Back" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,786][1080,839]" displayed="true" />
                      </android.view.ViewGroup>
                    </android.view.ViewGroup>
                  </android.view.ViewGroup>
                </android.widget.ScrollView>
              </android.view.ViewGroup>
            </android.widget.FrameLayout>
          </android.widget.FrameLayout>
        </android.widget.LinearLayout>
      </android.widget.FrameLayout>
    </android.widget.LinearLayout>
  </android.widget.FrameLayout>
</hierarchy>
```

**Comment by mykola-mokhnach** [comment]
Most likely because `backButton` requires `accessibility id`  locator rather than `id` one (which is internally mapped to resource identifier as described in the readme link above)

**Comment by mykola-mokhnach** [comment]
In theory yes. In reality - such locators are directly mapped to Android's native https://developer.android.com/reference/androidx/test/uiautomator/BySelector#res(java.lang.String) locator and we cannot influence this behavior. I would try to replace the locator to xpath one as a possible workaround

**Comment by mykola-mokhnach** [comment]
Another possible issue: https://github.com/appium/appium-uiautomator2-server/blob/d3cd4a3baa4209d02afcdd2fc0007717890bf138/app/src/main/java/io/appium/uiautomator2/utils/ElementLocationHelpers.java#L75

We automatically add the package identifier to original string if it is not prefixed already. I'm not quite sure why react does not follow this pattern. Shall it be a bug from their side?

**Comment by fantpmas** [comment]
If I use `com.testiddemo:id/backButton` as `testID` it works! I can find the element searching for `com.testiddemo:id/backButton` using the `id` locator strategy.

**Comment by mykola-mokhnach** [comment]
> If I use com.testiddemo:id/backButton as testID it works! I can find the element searching for com.testiddemo:id/backButton using the id locator strategy.

I assume this case should be then simply better documented and the general agreement about resources identifier prefixes should be respected.

**Comment by fantpmas** [comment]
Is it expected that the value before `:id` can be anything and doesn't have to be the actual package id? It still works if I use `sometext:id/backButton`. Bit strange, no?

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by cpdyj** [comment]
I'm faceing the same problem. But when I use `new UiSelector().resourceId("the_simple_id")` it works. Both of use `${pkgName}:id/${resId}` and Android UiAutomator2 selector are ugly way. It breaks the cross-platform ability.
So, are there any better way? I think it's a bug that relates to appium.

**Comment by mykola-mokhnach** [comment]
@cpdyj You could add a new server setting, which would allow to avoid provided ids being overridden if they don't match to `x:id/y` pattern. The way ids are handled in Appium could not be changed because it would break existing user's code.

My concern there is that resource ids must be formatted properly to ensure their uniqueness across different packages. Even though resource names without prefixes are allowed it is against best practices to use them.
Also, some resource name generation code for the reference: https://android.googlesource.com/platform/frameworks/base.git/+/android-4.3_r2.1/core/jni/android_util_AssetManager.cpp#587

**Comment by cpdyj** [comment]
@mykola-mokhnach Sorry, what's the server settings ? I read the docs but get nothing...😅😅😅
Thank you.

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium-uiautomator2-driver#settings-api

**Comment by tuncaulubilge** [comment]
> https://github.com/appium/appium-uiautomator2-driver#settings-api

Hi @mykola-mokhnach , can you share an example on how to handle this? I'd assume this is quite a common pain point for anyone using React Native >= 0.65 and doesn't want to use a helper function all every testID in their code base to add these prefixes.

**Comment by mykola-mokhnach** [comment]
> doesn't want to use a helper function all every testID in their code base to add these prefixes.

Basically I cannot imagine any other workarounds except of that. I'm also not very convinced about adding more workarounds to UIA2 driver, because the actual issue is something that has been broken after the particular React update and was working before. So, a logical solution would be to restore the previous (correct) behaviour there.

**Comment by Almouro** [comment]
Another workaround that seems to work: using `xpath`

```
`//android.view.ViewGroup[contains(@resource-id, "${testID}")]`
```

**Comment by BlackSwan2019** [comment]
> Another workaround that seems to work: using `xpath`
> 
> ```
> `//android.view.ViewGroup[contains(@resource-id, "${testID}")]`
> ```

This unblocked my effort today, thanks. I do wonder though if using `contains` might select an element that you didn't intend. I will test more tomorrow.

**Comment by BlackSwan2019** [comment]
Update: A better selector is: `//*[@resource-id="Some_Element_ID"]`. It has behaved very well and selects for just the element I want vs. using `contains` like in my response above.
