### ISSUE TITLE
No route found for /wb/hub/session while automating windows app with Appium

### ISSUE THREAD

**Issue by BejugamSravan** [appium/appium#15352]
when I ran the tests, I got below response in Appium v1.20.2 server :

[HTTP] --> POST /wb/hub/session
[HTTP] {"desiredCapabilities":{"platformName":"Windows","platformVersion":"10","deviceName":"WindowsPC","app":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App"},"capabilities":{"firstMatch":[{"platformName":"Windows"}]}}
[HTTP] No route found for /wb/hub/session
[HTTP] <-- POST /wb/hub/session 404 1 ms - 211

Desired capabilities in my code

AppiumOptions opt = new AppiumOptions();
opt.AddAdditionalCapability( "platformName","Windows");
opt.AddAdditionalCapability("platformVersion", "10");
opt.AddAdditionalCapability("deviceName", "WindowsPC");
opt.AddAdditionalCapability("app", "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App");
x`calSession = new WindowsDriver(new Uri("http://127.0.0.1:4723/wb/hub"), opt);

![image](https://user-images.githubusercontent.com/39548166/117636001-00205480-b19e-11eb-9edb-082d69b7a134.png)

Is there any way to use appium with WinAppDriver for Automation testing?

**Comment by BejugamSravan** [comment]
@mykola-mokhnach yes, i am using the Appium v1

![image](https://user-images.githubusercontent.com/39548166/117652957-72e6fb00-b1b1-11eb-9057-b55940e5102a.png)

Full server log
[info] [35m[Appium][39m Welcome to Appium v1.20.2
[info] [35m[Appium][39m Non-default server args:
[info] [35m[Appium][39m   address: 127.0.0.1
[info] [35m[Appium][39m   relaxedSecurityEnabled: true
[info] [35m[Appium][39m   allowInsecure: {
[info] [35m[Appium][39m   }
[info] [35m[Appium][39m   denyInsecure: {
[info] [35m[Appium][39m   }
[info] [35m[Appium][39m Appium REST http interface listener started on 127.0.0.1:4723[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wb/hub/session[39m
[info] [35m[HTTP][39m [90m{"desiredCapabilities":{"platformName":"Windows","platformVersion":"10","deviceName":"WindowsPC","app":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App"},"capabilities":{"firstMatch":[{"platformName":"Windows"}]}}[39m
[debug] [35m[HTTP][39m No route found for /wb/hub/session
[info] [35m[HTTP][39m [37m<-- POST /wb/hub/session [39m[33m404[39m [90m36 ms - 211[39m
[info] [35m[HTTP][39m [90m[39m

**Comment by mykola-mokhnach** [comment]
the error is expected: `/wb/hub/session` does not exist. There is most likely a typo there

**Comment by rekhabhaskaran** [comment]
> @mykola-mokhnach yes, i am using the Appium v1
> 
> ![image](https://user-images.githubusercontent.com/39548166/117652957-72e6fb00-b1b1-11eb-9057-b55940e5102a.png)
> 
> **Full server log** [info] �[35m[Appium]�[39m Welcome to Appium v1.20.2 [info] �[35m[Appium]�[39m Non-default server args: [info] �[35m[Appium]�[39m address: 127.0.0.1 [info] �[35m[Appium]�[39m relaxedSecurityEnabled: true [info] �[35m[Appium]�[39m allowInsecure: { [info] �[35m[Appium]�[39m } [info] �[35m[Appium]�[39m denyInsecure: { [info] �[35m[Appium]�[39m } [info] �[35m[Appium]�[39m Appium REST http interface listener started on 127.0.0.1:4723[info] �[35m[HTTP]�[39m �[37m-->�[39m �[37mPOST�[39m �[37m/wb/hub/session�[39m [info] �[35m[HTTP]�[39m �[90m{"desiredCapabilities":{"platformName":"Windows","platformVersion":"10","deviceName":"WindowsPC","app":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App"},"capabilities":{"firstMatch":[{"platformName":"Windows"}]}}�[39m [debug] �[35m[HTTP]�[39m No route found for /wb/hub/session [info] �[35m[HTTP]�[39m �[37m<-- POST /wb/hub/session �[39m�[33m404�[39m �[90m36 ms - 211�[39m [info] �[35m[HTTP]�[39m �[90m�[39m

The GUI shows 1.20 you should check the CLI version of appium
