### ISSUE TITLE
XCUIElementTypeTextView contents are truncated to 512 characters, or are null in Appium 1.20.2

### ISSUE THREAD

**Issue by WilfulTravesty** [appium/appium#15355]
## The problem

XCUIElementTypeTextView with long contents are truncated in Appium 1.91.1 and return null in Appium 1.20.

## Environment

Appium Desktop 1.19.1 - returns truncated contents, 512 characters long
Appium Desktop 1.20.2 - return null
Earlier Appium versions seemed to work fine back when I first wrote the code, but I don't have an exact version.

Note: after re-installing 1.19.1, I forgot to recompile WDA, and Appium was returning null until I recompiled WDA at which point it returned truncated values again, so this may be an issue with WDA.

* Desktop OS/version used to run Appium: MacOS Catalina 10.15.7
* Npm or Yarn package manager: 
* Mobile platform/version under test: iOS 12.4
* Real device or emulator/simulator: iPhone SE

## Details

driver.find_element_by_accessibility_id("eula").get_attribute("value") is truncated to 512 characters in Appium 1.19.1 and returns null in Appium 1.20.2

The Appium log shows a truncated value being returned for the request.

The Appium inspector shows a "value" attribute on the element which matches the truncated contents shown in the log and returned to the client program.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
