### ISSUE TITLE
The application under test with bundle id '' is not running, possibly crashed on Xcode 12.4

### ISSUE THREAD

**Issue by khsarma** [appium/appium#15358]
## The problem

App is installed on IOS simulator. After the launching app thru appium script, app is getting opened and crashed multiple times and finally script fails.

## Environment

- Appium version (or git revision) that exhibits the issue:  Appium CLI 1.21.0-beta (1.21.0 as well)
- Last Appium version that did not exhibit the issue (if applicable): NA
- Desktop OS/version used to run Appium: MacOS Catalina 10.15.7
- Node.js version (unless using Appium.app|exe): v13.8.0
- Npm or Yarn package manager: npm
- Mobile platform/version under test: IOS 14.4 sdk
- Real device or emulator/simulator: Simulator (12.4, 13.3, 14.4)
- Appium CLI or Appium.app|exe: Appium CLI
- XCode: 12.4

## Details

This is happening after upgrading XCode to 12.4. Tried different appium versions (1.21.0 and beta) against different simulator versions (12.4, 13.3, 14.4). Tried different appium capabilities.
Error:

> [35m[WD Proxy][39m Got response with status 400: \{"value":\{"error":"invalid element state","message":"The application under test with bundle id '<app>' is not running, possibly crashed","traceback":"(\\n\\t0   CoreFoundation                      0x00007fff20421af6 __exceptionPreprocess + 242\\n\\t1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48\\n\\t2   CoreFoundation                      0x00007fff20421797 -[NSException init] + 0\\n\\t3   WebDriverAgentLib                   0x000000010e89e24b -[FBSession activeApplication] + 667\\n\\t4   WebDriverAgentLib                   0x000000010e8ce11a +[FBSessionCommands currentCapabilities] + 90\\n\\t5   WebDriverAgentLib                   0x000000010e8cdfe9 +[FBSessionCommands sessionInformation] + 233\\n\\t6   WebDriverAgentLib                   0x000000010e8ca8cf +[FBSessionCommands handleCreateSession:] + 3551\\n\\t7   WebDriverAgentLib                   0x000000010e85cce6 -[FBRoute_TargetAction mountRequest:intoResponse:] + 182\\n\\t8   WebDriverAgentLib                   ...\
>     [debug] [35m[W3C][39m Matched W3C error code 'invalid element state' to InvalidElementStateError\
>     [debug] [35m[XCUITest][39m Failed to create WDA session (The application under test with bundle id '<app> is not running, possibly crashed)

## Link to Appium logs

https://gist.github.com/khsarma/f880900d67db4fa6b627522ed09f3372

## Code To Reproduce Issue [ Good To Have ]
--NA--

**Comment by khsarma** [comment]
Yes - able to launch app manually on simulator.

**Comment by KazuCocoa** [comment]
> We have XCUItests for the app as well. Those tests are working fine without any issues. Its only with Appium we are getting app crashes.

Btw, what about the below steps? I wonder one or two of them work...

1. Establish a session with `autoLaunch: true` in the capabilities
2. Launch the app under test with one of the below:
    - https://github.com/appium/appium-xcuitest-driver#mobile-launchapp
    - https://appium.io/docs/en/commands/device/app/activate-app/ (or https://github.com/appium/appium-xcuitest-driver#mobile-activateapp)

**Comment by youngfreeFJS** [comment]
can you find crash log at "~/Library/Logs/DiagnosticReports" ? 
like: "AppName_2021-xx-xx_xxxMacBook-Pro.crash"
@khsarma

**Comment by khsarma** [comment]
> > We have XCUItests for the app as well. Those tests are working fine without any issues. Its only with Appium we are getting app crashes.
> 
> Btw, what about the below steps? I wonder one or two of them work... (but internally they have no big differences tho...)
> 
> 1. Establish a session with `autoLaunch: true` in the capabilities
> 2. Launch the app under test with one of the below:
>    
>    * https://github.com/appium/appium-xcuitest-driver#mobile-launchapp
>    * https://appium.io/docs/en/commands/device/app/activate-app/ (or https://github.com/appium/appium-xcuitest-driver#mobile-activateapp)

We tried these options and we are still facing app crashes with same error..

**Comment by KazuCocoa** [comment]
hm... then, perhaps actually something occurred in XCTest framework since the end is either below APIs as Appium...

https://developer.apple.com/documentation/xctest/xcuiapplication/1500467-launch
https://developer.apple.com/documentation/xctest/xcuiapplication/2873317-activate

https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/WebDriverAgentLib/Routing/FBSession.m#L204-L206
https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/WebDriverAgentLib/Utilities/FBXCodeCompatibility.m#L84

**Comment by mykola-mokhnach** [comment]
I don't think there is more to do on this issue. Closed as third party
