### ISSUE TITLE
Appium does not see elements if they aren't visible on the screen

### ISSUE THREAD

**Issue by BinaryJava** [appium/appium#15368]
## The problem

If an element is not visible on the emulator screen, Appium cannot see the element. I have tried using scrolling but I can't scroll if Appium doesn't know the element exists. If I manually scroll in the emulator, the element appears in the DOM and can interact with it.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Desktop OS/version used to run Appium: Mac OS Big Sur
* Node.js version (unless using Appium.app|exe): 16.1.0
* Npm or Yarn package manager: npm v7.11.2
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Appium CLI

**Comment by mykola-mokhnach** [comment]
You could try to customize that behavior using [allowInvisibleElements](https://github.com/appium/appium-uiautomator2-driver#settings-api) and/or [ignoreUnimportantViews](https://github.com/appium/appium-uiautomator2-driver#settings-api) settings.

**Comment by jlipps** [comment]
And if you are referring to an element which is not on the screen (i.e. it's below the fold in a scrollable list), then this is a fact about Android apps--list elements do not exist until they are rendered on the screen. So the correct approach to finding them is usually a loop involving scrolling a bit then looking for the element, the continuing to do this until the element is found.

**Comment by BinaryJava** [comment]
If I scroll to the bottom of the page, will the elements then appear in the DOM?

**Comment by KazuCocoa** [comment]
> If I scroll to the bottom of the page, will the elements then appear in the DOM?

Yes in most cases, I hope... (It depends on Android OS side tho)

It depends on the app under test. e.g. ListView or AdapterViews etc
They behave differently as Android OS. I don't remember well for now, but AdapterViews generates view dynamically. so, Android OS cannot know what elements are in the list but invisible. But ListView might be able to know of. `allowInvisibleElements` helps to get invisible elements in ListView case. AdapterViews need scroll to get invisible elements.

**Comment by jlipps** [comment]
> If I scroll to the bottom of the page, will the elements then appear in the DOM?

Yes and no. If you scroll past an element then it will no longer be in the DOM. on Android an element is "in the DOM" only when it's actually being rendered on the screen. So if you want to guarantee finding an element, you'll need to make sure you check for the element at least once on each screen height's worth of scrolling.

**Comment by BinaryJava** [comment]
What's the best way to interact with these elements? I've created a scroll function and said while element is not visible, but this just throws an exception as it isn't in the DOM. Currently I interact with an element and then but the scroll afterwards

**Comment by KazuCocoa** [comment]
It depends on your app under test, but a general use case may be like the below. 

```
10.times.each
  begin
    e = driver.find_element :id, some_id_name
    break if e.displayed?  # end the loop if the element existed and it was visible
  rescue NoSuchElementError
    # ignore
  end
  # scroll with W3C actions
end
```

an example of w3c scroll action:
https://github.com/appium/ruby_lib_core/blob/1632637fd872c0b80dfb97b8514ada6a7164eebf/test/functional/common_w3c_actions.rb#L16


Android OS also provides some interaction APIs, and Appium supports them via mobile commands. But their stability depends on the device under test in my experience.

https://discuss.appium.io/ also helps to find other ways.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
