### ISSUE TITLE
Could not proxy command to the remote server. Original error: connect ECONNREFUSED 127.0.0.1:8100

### ISSUE THREAD

**Issue by TheStrivingWhite** [appium/appium#15361]
The version number of the tool:
1. Appium:1.21
2. Xcode:11.3.1
3. iOS Simulator:11.3.1

Appium Setting:
{
  "platformName": "iOS",
  "platformVersion": "12.0",
  "bundleId": "com.xxx.app",
  "deviceName": "iPhone XS Max",
  "udid": "E2B865FF-5FC6-4273-B586-B25B17A8E5C0"
}

Run the project to the simulator, configure appium parameters, and click start to report an error：

An unknown server-side error occurred while processing the command. Original error: Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: connect ECONNREFUSED 127.0.0.1:8100

The startup output is：

[appium-server-logs.txt](https://github.com/appium/appium/files/6463633/appium-server-logs.txt)

**Comment by mykola-mokhnach** [comment]
> [error] [35m[Xcode][39m 2021-05-12 11:05:24.325 xcodebuild[1016:11654]  iPhoneConnect: 📱<DVTiOSDevice (0x7fa5aee6a610), iPhone, iPhone, 14.2 (18B92), 68299eeb1a97ca9c883f0e9152b1df8a42c31d18> unable to mount developer disk image, (Error Domain=com.apple.dtdevicekit Code=-402653066 "An error was encountered while enabling development on this device." UserInfo={NSLocalizedFailureReason=Please try rebooting and reconnecting the device. (0xE8000076), com.apple.dtdevicekit.stacktrace=(

It could be that your device is broken. Try to run the test on another one.

Did you try to compile and deploy WebDriverAgent manually from xCode as described in https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

**Comment by mykola-mokhnach** [comment]
Also I see an inconsistency in capabilities and actual platform versions. Are you trying to automate simulator or a real device?

**Comment by TheStrivingWhite** [comment]
1. Inconsistency between functionality and actual platform version,Are you talking about the app version? 
2. Running the project on the simulator
3. thank
