### ISSUE TITLE
An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server.

### ISSUE THREAD

**Issue by TheStrivingWhite** [appium/appium#15365]
I try to run the real machine and report an error：

An unknown server-side error occurred while processing the comma nd. Original error: Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/doc s/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the de vice.

The parameter is
{
"platformName": "iOS", 
"platformVersion": "14.4.2", 
"udid": "ac3d6d755980e7c97d15fea7a4ff4ec4999853fd", 
"bundleId": "com.x'x'x.app", 
"xcodeOrgId": "AK4UD86Z2K", 
"deviceName": "ࠈᰎጱ iPhone", 
"app": "/Users/xxx/Desktop/Payload.ipa", 
"xcodeSigningId": "iPhone Developer"
}

appium:1.21
Xcode:12.5
Mac:11.2.3

**Comment by TheStrivingWhite** [comment]
Web driver agent can also run on real machine，Open app is black screen

**Comment by mykola-mokhnach** [comment]
Please provide the full server log with xcodebuild log enabled

> Web driver agent can also run on real machine，Open app is black screen

Do you mean you can build and deploy WDA manually to this device using Xcode?

**Comment by mykola-mokhnach** [comment]
Closed because of no response
