### ISSUE TITLE
the appium server always pick the first device to run testcases when run testcases in parallel

### ISSUE THREAD

**Issue by dvdface** [appium/appium#15373]
## The problem

When I tried to run multiple testcases  in the same machine with multiple devices at the same time, the appium always pick the first device to run the testcases one by one; It should choose the spare devices to run the testcases; by given a udid can fix this problem but It's inconvenient to give a udid in testcasess, usually we don't give that udid in the testcase.

## Environment
* Appium version (or git revision) that exhibits the issue: v1.21.0
* Last Appium version that did not exhibit the issue (if applicable): None
* Desktop OS/version used to run Appium: Windows 10 20H2 19042.964
* Node.js version (unless using Appium.app|exe): Node.js v15.4.0
* Npm or Yarn package manager:  7.11.2
* Mobile platform/version under test: Android 11
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: None

## Details

1. start appium by run appium command in cmd
2. write two testcases with following codes:
    **
    from appium import webdriver
    
    caps  = dict(
        platformName='Android'
    )
    
    driver = webdriver.Remote("http://127.0.0.1:4723/wd/hub", desired_capabilities=caps)
    
    driver.start_activity("com.android.chrome", "com.google.android.apps.chrome.Main")
    
    import time
    time.sleep(10)
    
    driver.quit()
    **
3. run two testcases in seperated cmd windows at the same time
4. the two testcases run at the same device one after the another

## Link to Appium logs

No

## Code To Reproduce Issue [ Good To Have ]

No

**Comment by mykola-mokhnach** [comment]
This is the expected behaviour. Currently UIA2 driver does not contain any logic to track devices given in capabilities and we are not quite sure such logic should be there. See https://github.com/appium/appium/issues/10383 for more details.

Closed as not an issue.

**Comment by dvdface** [comment]
> This is the expected behaviour. Currently UIA2 driver does not contain any logic to track devices given in capabilities and we are not quite sure such logic should be there. See #10383 for more details.
> 
> Closed as not an issue.

That I use Appium + Selenium Grid to run testcases can fix this problem；

But I met another one， with Grid， how can pick a desired phone type to run test cases？

For example， I start up two appium for two phones, one for Pixel4, one for Pixel 5, how can I let testcases run on Pixel4?

**Comment by mykola-mokhnach** [comment]
I would say this is rather a Grid's limitation. It was initially implemented for web/selenium-based testing without Appium "in mind". 
A proper solution could be to improve Grid itself or to have a separate module which is responsible for device management only

**Comment by jlipps** [comment]
Just a note, @dvdface, that there is an Appium 2.0 plugin under development that will adjust Appium's behavior to basically do what you want (keep track of free/used devices and only give you a free device): https://github.com/AppiumTestDistribution/appium-device-farm/
