### ISSUE TITLE
iOS - WebDriverAgent test stuck in Using singleton test manager

### ISSUE THREAD

**Issue by FlintyLemming** [appium/appium#15374]
## The problem

When I test WebDriverAgent by following [Real Device Config](https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md), the test stuck in Using singleton test manager.
<img width="793" alt="CleanShot 2021-05-13 at 14 18 43@2x" src="https://user-images.githubusercontent.com/19165511/118086660-e3cb2480-b3f6-11eb-87a1-aa1eea35d7be.png">

## Environment

* Appium version (or git revision) that exhibits the issue: Appium-mac-1.20.2 and Appium-mac-1.21.0
* Last Appium version that did not exhibit the issue (if applicable): Appium-mac-1.20.2 but on a different version of macOS
* Desktop OS/version used to run Appium: macOS 11.3.1 (tried on both M1 chip and Intel chip)
* Node.js version (unless using Appium.app|exe): v14.16.1
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS 14.5.1 also tried on iOS 13.x
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium.app

## Details

Actually when I first run the test it shows error below
<img width="793" alt="CleanShot 2021-05-13 at 14 14 52@2x" src="https://user-images.githubusercontent.com/19165511/118088303-740a6900-b3f9-11eb-91bc-efa8f36782da.png">
and the log file is [here](https://flintylemming-my.sharepoint.cn/:f:/g/personal/admin_flinty_moe/EodXCWM9KLFOr8AUvRJPoLQBptxCUfb1KWtUoZmad0wb9A?e=I7issy)

When I try again, it stuck in Using singleton test manager just like below
<img width="793" alt="CleanShot 2021-05-13 at 14 18 43@2x" src="https://user-images.githubusercontent.com/19165511/118087591-5983c000-b3f8-11eb-9f88-819f8e845e5a.png">
and the log file is [here](https://flintylemming-my.sharepoint.cn/:f:/g/personal/admin_flinty_moe/El3rEuYCmV1BubdFP3UOhLgBlRT2d6xNgBdOvhYB6-JXdA?e=w8rF53)

This problem cause me can not deduct the test via Appium App.

## Link to Appium logs

https://gist.github.com/FlintyLemming/37e45a2cc788fd7953de8b83d87d3149

**Comment by mykola-mokhnach** [comment]
I don't observe any issues in the provided log. That particular log line is an expected one and is always present on each server startup.

**Comment by FlintyLemming** [comment]
Yes, the log that already shows has nothing wrong, but it can not go on, just stop there.

**Comment by mykola-mokhnach** [comment]
> Yes, the log that already shows has nothing wrong, but it can not go on, just stop there.

What is `it`? Have you tried to send requests to the server URL using curl?

**Comment by FlintyLemming** [comment]
No, actually I'm not running a background task. I just set up the environment and meet this problem by following [this article](https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md).
Basically, the problem is after installed WebDriverAgent it can not call up the app. This problem causes me when I start a section in Appium App, the Appium can't open the installed app.
![image](https://user-images.githubusercontent.com/19165511/118096190-9bfeca00-b403-11eb-9c16-a4cc3cd4ed6a.png)

**Comment by mykola-mokhnach** [comment]
From the log above Appium server cannot connect to the WebDriverAgent instance via iProxy. There might be multiple reasons to this, for example device issues or some firewall software that is blocking localhost communication. Unfortunately it is impossible to get more info based on the provided logs

**Comment by FlintyLemming** [comment]
Yes, I also reinstall macOS but didn't work. Let me think about the reason, thanks a lot.
