### ISSUE TITLE
Encountered internal error running command: Error: zipAlignApk failed. 

### ISSUE THREAD

**Issue by MichalKozlowski1982** [appium/appium#15371]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Dear all., 

I am runing following code:

```
import unittest
from appium import webdriver

desired_caps = {}
desired_caps['platformName'] = 'Android'
desired_caps['platformVersion'] = '9'
desired_caps['automationName'] = "UiAutomator2"
desired_caps['deviceName'] = 'Michal'
desired_caps['appPackage']="com.android.calculator2"
desired_caps['appActivity']="com.android.calculator2.Calculator"
driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
driver.find_element_by_id("com.android.calculator2:id/digit5").click()
driver.find_element_by_id("com.android.calculator2:id/plus").click()
driver.find_element_by_id("com.android.calculator2:id/digit6").click()
driver.find_element_by_id("com.android.calculator2:id/equal").click()
#print(driver.find_element_by_class_name("com.android.calculator2.CalculatorEditText").text)
result=driver.find_element_by_class_name("com.android.calculator2.CalculatorEditText").text
if(result.index("11")>1):
    print("pass")
else:
    print("fail")

```
and I get following  error from Appium:

> [ADB] Using 'zipalign.exe' from 'C:\Users\micha\AppData\Local\Android\Sdk\build-tools\31.0.0-rc3\zipalign.exe'
[ADB] 'C:\Users\micha\AppData\Local\Temp\2021412-17640-ze5ttz.k6a2f\appium-uiautomator2-server-debug-androidTest.apk' is not zip-aligned. Aligning
[UiAutomator2] Deleting UiAutomator2 session
[UiAutomator2] Deleting UiAutomator2 server session
[WD Proxy] Matched '/' to command name 'deleteSession'
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
[ADB] Running 'C:\Users\micha\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell am force-stop com.android.calculator2'
[Logcat] Stopping logcat capture
[ADB] Removing forwarded port socket connection: 8200 
[ADB] Running 'C:\Users\micha\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 forward --remove tcp\:8200'
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command 'C:\\Users\\micha\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 forward --remove tcp\:8200' exited with code 1'; Stderr: 'adb.exe: error: listener 'tcp:8200' not found'; Code: '1''
[UiAutomator2] Restoring hidden api policy to the device default configuration
[ADB] Running 'C:\Users\micha\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell settings delete global hidden_api_policy_pre_p_apps'
[ADB] Running 'C:\Users\micha\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell settings delete global hidden_api_policy_p_apps'
[ADB] Running 'C:\Users\micha\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell settings delete global hidden_api_policy'
[BaseDriver] Event 'newSessionStarted' logged at 1620852900182 (22:55:00 GMT+0200 (Środkowoeuropejski czas letni))
[W3C] Encountered internal error running command: Error: zipAlignApk failed. Original error: Command 'C:\\Users\\micha\\AppData\\Local\\Android\\Sdk\\build-tools\\31.0.0-rc3\\zipalign.exe -f 4 C:\\Users\\micha\\AppData\\Local\\Temp\\2021412-17640-ze5ttz.k6a2f\\appium-uiautomator2-server-debug-androidTest.apk C:\\Users\\micha\\AppData\\Local\\Temp\\2021412-17640-47lkft.m7h9f\\appium.tmp' exited with code 1. Stdout: ''; Stderr: 'Unable to open 'C:\Users\micha\AppData\Local\Temp\2021412-17640-ze5ttz.k6a2f\appium-uiautomator2-server-debug-androidTest.apk' as zip archive
[W3C] '
[W3C]     at ADB.zipAlignApk (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\apk-signing.js:251:11)
[HTTP] <-- POST /wd/hub/session 500 15342 ms - 1778
[HTTP] 

Please help. I have tried reinstaltion, changing the access rights to folder, running appium as admin 

## Environment

- I am running Appium Desktop version 1.15.1
- I am on (pick one):
    - [ ] Mac
    - [ x] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
transferred to appium/appium since presumably this has nothing to do with appium desktop

**Comment by mykola-mokhnach** [comment]
Please use the most recent server version. v 1.15 is out of date

**Comment by MichalKozlowski1982** [comment]
Thanks upgrade of appium solved the issue
