### ISSUE TITLE
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details

### ISSUE THREAD

**Issue by ITester2020** [appium/appium#15372]
Hi all,

I'm new to Appium and try to launch the emulator programmatically. Used same configuration code in this Github and faced below issue
[Run time error.docx](https://github.com/appium/appium/files/6470032/Run.time.error.docx)
[Hooks.docx](https://github.com/appium/appium/files/6470033/Hooks.docx)

But i'm facing below issue:
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: The application at '/Users/{User_name}/repo/Packagename/src/test/resources/{app name}.apk' does not exist or is not accessible
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ITM305500', ip: '2406:e003:11f7:9701:7d21:fc7a:bf3:f2f2%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '1.8.0_242-release'

Attached Appiumserver code as Hooks and run time issue logs.

**Comment by mykola-mokhnach** [comment]
The error looks valid to me. Make sure you provide a correct path to the application binary and that this binary exists on the filesystem and is accessible by Appium process.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
