### ISSUE TITLE
The WDA is not installing automatically and launch during test execution

### ISSUE THREAD

**Issue by viveksoundar** [appium/appium#15377]
## The problem
I used USE_NEW_WDA = true in capabilities, The installed WDA is removed from the simulator but it's not installing again and launch during the time of test exection

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable): 1.20.2
* Desktop OS/version used to run Appium: 10.15.5
* Node.js version (unless using Appium.app|exe):v14.4.0
* Npm or Yarn package manager:
* Mobile platform/version under test: 14.4
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

https://gist.github.com/viveksoundar/2de012090d0dd1af9f5468dab2347a58

#Sample Capabilities

 capabilities.setCapability(MobileCapabilityType.NO_RESET, false);
  capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");
  capabilities.setCapability(IOSMobileCapabilityType.USE_NEW_WDA, true);
  capabilities.setCapability(IOSMobileCapabilityType.WDA_LAUNCH_TIMEOUT, 4000);

**Comment by mykola-mokhnach** [comment]
Possible duplicate of https://github.com/appium/appium/issues/15329

**Comment by viveksoundar** [comment]
@mykola-mokhnach No, I don't think so! If I install the WDA manually from Xcode and run automation with USE_NEW_WDA=false it works for every run. When I kill the emulator and start the automation the emulator launched and the existing WDA got removed and it's not installing a new WDA. Again I need to install WDA manually for the next run.

**Comment by KazuCocoa** [comment]
Could you share appium log with `showXcodeLog: true` capability?

**Comment by viveksoundar** [comment]
@KazuCocoa Sure! [here](https://gist.github.com/viveksoundar/b85be1773fc6a0f0d1e34261684d7b5f#file-wda_with_xcode_log) it is:

**Comment by KazuCocoa** [comment]
Hm... as https://github.com/appium/appium/issues/15377#issuecomment-840506943 , it seems the build took a long time, so the build was interrupted.

```
2021-05-14 04:47:48:072 [Xcode] ** BUILD INTERRUPTED **
```

How long the below command take on your environment?
```
2021-05-14 04:46:51:718 [Xcode] /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=2DD29867-BDF9-45C8-9C3F-4C291E4E4476 IPHONEOS_DEPLOYMENT_TARGET=14.4 GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO
```

**Comment by viveksoundar** [comment]
Sometimes It take more than a minute, should I give more to WDA_LAUNCH_TIMEOUT? or can't it dynamically wait untill the WDA installs? is there any way to overcome the issue?

**Comment by KazuCocoa** [comment]
So far, increasing timeout is the only way I assume, because xcodebuild itself takes time. I haven't met such behavior, but possibly xcodebuild takes a longer time in some environments. `appium:wdaLaunchTimeout`, `appium:wdaStartupRetries` and `appium:wdaStartupRetryInterval` may help to wait such timeout.

Or, you probably can try `appium:usePrebuiltWDA` or `appium:useXctestrunFile` to re-use pre-build module. It may help to skip re-building the code once the build succeedes.
https://github.com/appium/appium-xcuitest-driver

**Comment by viveksoundar** [comment]
Thanks, @KazuCocoa will follow your guidance! After increasing the timeout to 40000 It works reliably.
