### ISSUE TITLE
Update integration tests to use WebDriverIO instead of WD

### ISSUE THREAD

**Issue by mykola-mokhnach** [appium/appium#15382]
WD framework currently used by our end-to-end tests in Appium drivers is not maintained properly and does not have a proper W3C support. This means all these tests are going to be broken as soon as Appium 2.0 is released and JWP protocol support is completely dropped. 

cc @boneskull @jlipps

**Comment by jlipps** [comment]
I agree. It's time to bite the bullet and do this. I am already using wdio in the plugins monorepo tests now too.

**Comment by boneskull** [comment]
...but the integration tests pass now?  why?

**Comment by jlipps** [comment]
clarification note: appium/appium has already been updated to use wdio instead of wd. So it's just all the individual drivers that still need updates.

**Comment by mykola-mokhnach** [comment]
There are separate tasks for each driver, so this common one could be closed
