### ISSUE TITLE
Inspector for iOS infinite loading after OS update. Error 500.

### ISSUE THREAD

**Issue by pink-bunny-23** [appium/appium#15387]
## The problem

Inspector for iOS infinite loading. Error 500. See logs.
Everything worked before few days. I updated real device to OS 14.5.1 and update the latest xCode to 12.5. From that moment I cannot fetch elements from inspector even worked before. 
On Android its working.
Note that automation test is working on iOS and I am able to execute for example login test, but inspector doesn't work at all.

## Environment

* Desktop OS/version used to run Appium: Mac OS Big Sur 11.2.3 (20D91)
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS 
* Real device or emulator/simulator: iPhone 12 (14.5.1)
* Appium CLI or Appium.app|exe: Appium Desktop 1.20.2-4
* XCode: Version 12.5 (12E262)
<img width="269" alt="Screenshot 2021-05-18 at 12 00 11" src="https://user-images.githubusercontent.com/68339340/118632354-9d980b80-b7d0-11eb-8362-4656271ccae1.png">

## Details
<img width="1091" alt="Screenshot 2021-05-18 at 11 54 12" src="https://user-images.githubusercontent.com/68339340/118631972-485bfa00-b7d0-11eb-9c88-e27cc1c5c921.png">
Note that test is working and I am able to execute for example login test, but inspector doesn't work at all.

## Link to Appium logs
https://gist.github.com/pink-bunny-23/8d9e05006425b3e65f170fd84fb32ed8

## Appium capabilities
{
  "platformName": "iOS",
  "automationName": "XCUITest",
  "app": "/Users/.... .ipa",
  "deviceName": "iPhone",
  "xcodeOrgId": "",
  "xcodeSigningId": "iPhone Developer",
  "udid": "",
  "noReset": true
}

**Comment by mykola-mokhnach** [comment]
appium 1.20 does not support iOS 14.5 
Consider updating the server to 1.21
Closed as duplicate
