### ISSUE TITLE
Receiving Neither ANDROID_HOME nor ANDROID_SDK_ROOT environment variable was exported. error

### ISSUE THREAD

**Issue by viveksoundar** [appium/appium#15384]
## The problem

Launching the appium server from java, and trying to get appium driver for android test cases, But receiving Neither ANDROID_HOME nor ANDROID_SDK_ROOT environment variable was exported. error in console. all the env are set properly.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable): NO, trying newly
* Desktop OS/version used to run Appium: 10.15.5
* Node.js version (unless using Appium.app|exe): v14.4.0
* Mobile platform/version under test: 10
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: APPIUM CLI

## Details

Set all the env variables JAVA_HOME, ANDROID_HOME, and the required variables. Launching the appium server from java service builder. And trying to create session of AppiumDriver for android device. for your ref, I attached the env details I receive this error

> org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Neither ANDROID_HOME nor ANDROID_SDK_ROOT environment variable was exported. Read https://developer.android.com/studio/command-line/variables
 for more details

## Link to Appium logs

https://gist.github.com/viveksoundar/c27d306a62fe4dbaac2701c33c9f79a4#file-appium_error_log

<img width="1440" alt="Screen Shot 2021-05-17 at 7 31 00 PM" src="https://user-images.githubusercontent.com/37587895/118501503-6b41cc00-b746-11eb-915c-63e211e1f375.png">

**Comment by mykola-mokhnach** [comment]
Try the troubleshooting at https://github.com/appium/java-client/blob/master/docs/environment.md

**Comment by viveksoundar** [comment]
After adding a line of code "serviceBuilder.withEnvironment(System.getenv());" it works fine. Thanks :-)

**Comment by vjmaiky** [comment]
@viveksoundar i ran into the similar problem. All seems to be ok (appium doctor, zshrc, appium desktop works, terminal recognises adb, etc.)..i also added      .withEnvironment(System.getenv()) into serice creation..still it cannot get the android home...

**Comment by vjmaiky** [comment]
already resolved the problem:
https://github.com/appium/appium/issues/15418
