### ISSUE TITLE
Multiple sessions for one device 

### ISSUE THREAD

**Issue by simonsymhoven** [appium/appium#15381]
## The problem

I am using multiple devices, which are connected to one appium server. During the various tests, it is often noticed that several sessions are created for one and the same device. The test setup is sometimes very unstable, which is why I wonder if this is possibly due to this. Or is this expected behaviour? 

## Environment

* Appium version (or git revision) that exhibits the issue: Python Client: 1.1.0, Appium Server: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable): Don't know.
* Desktop OS/version used to run Appium: Mac OS Bis Sur 11.3.1
* Node.js version (unless using Appium.app|exe): 15.13.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS 14 - 14.5
* Real device or emulator/simulator: Xcode 12.5
* Appium CLI or Appium.app|exe: both

## Details

![b952061c-6b98-4cde-9659-4c07106a9804](https://user-images.githubusercontent.com/26878018/118448763-afa37c80-b6f2-11eb-89bf-e190ed012ca3.png)

**Comment by mykola-mokhnach** [comment]
Sessions are not created by themselves - they are always triggered as a response to a session creation request from a client. I'm not quite sure we could help you there based on the provided information.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
