### ISSUE TITLE
Error An unknown server-side error occurred while processing the command. Original error: Cannot verify the signature of 

### ISSUE THREAD

**Issue by GaboOsorio** [appium/appium#15389]
## The problem

Hello.

When logging into appium it sends an error: 

An unknown server-side error occurred while processing the command. Original error: Cannot verify the signature of 'C:\Users\"yourLocation"\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.17.4.apk'. Original error: The JAVA_HOME location 'C:\Program Files\Java\jre1.8.0_241' must exist

## Environment

* Appium v1.21.0
* Desktop OS: Windows 10
* Node.js version: v12.18.3
* Npm or Yarn package manager: 6.14.7
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Samsung J7 Neo

## Details

When trying to log into appium it sends an error

## Link to Appium logs

https://github.com/GaboOsorio/Error-Appium.git

**Comment by mykola-mokhnach** [comment]
Consider applied troubleshooting steps described at https://github.com/appium/java-client/blob/master/docs/environment.md

**Comment by mykola-mokhnach** [comment]
According to the error above the JAVA_HOME variable is not set to a proper value on the host system

**Comment by GaboOsorio** [comment]
This is my environment variable

![image](https://user-images.githubusercontent.com/49082349/118840766-515ed100-b88d-11eb-968f-26667fe09f3f.png)

**Comment by mykola-mokhnach** [comment]
Appium process though sees some other value: `C:\Program Files\Java\jre1.8.0_241` ¯\_(ツ)_/¯

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
