### ISSUE TITLE
Accessing page content when using deeply nested React Navigation navigators on Android Using Appium

### ISSUE THREAD

**Issue by simran-rajput** [appium/appium#15396]
## The problem

Not able to access the elements above 50. whenever i tried to access the elements on nested page i am getting error "An element could not be located on the page using the given search parameters".  This happens only when i tried to access more than 4 pages. i.e. at the 4th page max depth reaches 50 , When i tried to access the element on 5th page i am getting error. 

On appium inspector i am getting error interaction not available. 

I tried adding testId and accessibilityLabel and also tried to increase DEFAULT_MAX_DEPTH.

I don’t have this issue on IOS as the same structure works perfectly fine, is there just some config I’m missing?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Desktop OS/version used to run Appium:  Mac os
* Node.js version (unless using Appium.app|exe): v16.0.0
* Npm package manager:  7.10.0
* Mobile platform/version under test: Android 11
* Real device or emulator/simulator: Real device

**Comment by mykola-mokhnach** [comment]
Are you able to see the element in the page source generated by uiautomator inspector tool?

**Comment by simran-rajput** [comment]
yes . I am able to see the elements in page source using appium inspector. but when i run the test script i am getting error An element could not be loacted. And in appium inspector i am able to get the xpath of components but i am not able to interact with those elements.

**Comment by mykola-mokhnach** [comment]
This could be a race condition then. Print the actual page source before running the element lookup in your test to make sure it's there or add a lookup timer

**Comment by simran-rajput** [comment]
I printed page source and checked elements where there. But still i am facing the same issue as mentioned.

**Comment by mykola-mokhnach** [comment]
> I printed page source and checked elements where there.

Did you do this exactly before the lookup? Could you please attach this page source and the target xpath locator?

**Comment by simran-rajput** [comment]
[page source.xml.zip](https://github.com/appium/appium/files/6517442/page.source.xml.zip)
This is the page source, in the last commented lines are the elements that i am not able to access. 

Below is the xpath that i am using to find element:
driver.findElementByXPath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[2]/android.view.ViewGroup/android.view.ViewGroup[1]/android.view.ViewGroup/android.view.ViewGroup[2]/android.view.ViewGroup/android.view.ViewGroup[2]/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[2]/android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[1]/android.widget.EditText")

**Comment by amedvedjev** [comment]
there is NO EditText in scroll view! see ->
```
                                                  <android.widget.ScrollView index="0" package="com.abcappdev" class="android.widget.ScrollView" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="true" selected="false" bounds="[0,168][720,958]" displayed="true">
                                                    <android.view.ViewGroup index="0" package="com.abcappdev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,168][720,958]" displayed="true">
                                                      <android.view.ViewGroup index="0" package="com.abcappdev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[80,208][640,288]" displayed="true">
                                                        <!-- <android.widget.EditText index="0" package="com.abcappdev" class="android.widget.EditText" text="Name" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="true" long-clickable="true" password="false" scrollable="false" selected="false" bounds="[104,208][616,288]" displayed="true" /> -->
                                                      </android.view.ViewGroup>
                                                      <android.widget.TextView index="2" package="com.abcappdev" class="android.widget.TextView" text="0/50" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[585,294][640,330]" displayed="true" />
                                                      <android.widget.TextView index="3" package="com.abcappdev" class="android.widget.TextView" text="c/" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[80,372][102,408]" displayed="true" />
                                                      <android.view.ViewGroup index="4" package="com.abcappdev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[122,350][642,430]" displayed="true">
                                                        <!-- <android.widget.EditText index="0" package="com.abcappdev" class="android.widget.EditText" text="id" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="true" password="false" scrollable="false" selected="false" bounds="[146,350][618,430]" displayed="true" /> -->
                                                      </android.view.ViewGroup>
                                                      <android.widget.TextView index="6" package="com.abcappdev" class="android.widget.TextView" text="0/50" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[585,436][640,472]" displayed="true" />
                                                      <android.view.ViewGroup index="7" package="com.abcappdev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[80,492][640,802]" displayed="true">
                                                        <!-- <android.widget.EditText index="0" package="com.abcappdev" class="android.widget.EditText" text="Description" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="true" password="false" scrollable="false" selected="false" bounds="[104,519][616,799]" displayed="true" /> -->
                                                      </android.view.ViewGroup>
                                                      <android.widget.TextView index="9" package="com.abcappdev" class="android.widget.TextView" text="0/250" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[570,808][640,880]" displayed="true" />
                                                    </android.view.ViewGroup>
                                                  </android.widget.ScrollView>
```

see 'android.widget.EditText' is commented out = it not visible or available

**Comment by simran-rajput** [comment]
Its not commented in the code . Just for highlighting it in the XML I comment that part and attached the file. I Just highlighted that so that you can easily identify I am not able to  access that particular component. 
You can check the above comment over there I have written commented code is actually comment that I am not able to access. I just commented that to highlight from rest of the comments

**Comment by simran-rajput** [comment]
Debuging such a long code is not possible  that's why i just commented that so that any one can easily identify which elements are not accessible .  If you want i will attach a original file. 
I am not able to access element at line number 192 , 198, 203 and 207
[page source.xml.zip](https://github.com/appium/appium/files/6518016/page.source.xml.zip)

Can you please check and help ?

**Comment by amedvedjev** [comment]
ok. then simplify it ask mykola said.
example:
```
        List<MobileElement> elements = driver.findElement(MobileBy.className("android.widget.ScrollView"))
                .findElements(MobileBy.className("android.widget.EditText"));
        System.out.println("elements size: " + elements.size());
        // set first input
        elements.get(0).setValue("my_text_1");
        // set second input
        elements.get(1).setValue("my_text_2");
```

**Comment by amedvedjev** [comment]
ask developers to add ids.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
Thanks for your assistance @amedvedjev

**Comment by simran-rajput** [comment]
Thanks for assistance
