### ISSUE TITLE
mobile: scroll in UIAutomator2 always scrolls the first available view even if another scrollable element is passed

### ISSUE THREAD

**Issue by sebinjoseph1994** [appium/appium#15392]
## The problem

On using mobile:scroll in UIAutomator2 for native android application by specifying the id of the parent element to be scrolled,  instead of scrolling the given element, the scrolling is done on the first available view.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS 11.3.1
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: Pixel 4 11.0
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium desktop

## Details

Using the API demo app, https://github.com/appium/appium/blob/master/sample-code/apps/ApiDemos-debug.apk, I'm trying to scroll to one of the elements in the second scrollable view under the screen _Views -> Splitting Touches across View_. The parent element is retrieved correctly and the id is returned., but scrolling happens on the first view.

## Code To Reproduce Issue [ Good To Have ]

appiumDriver.findElement(MobileBy.AccessibilityId("Views")).click();
HashMap<String, String> scrollObject = new HashMap();
scrollObject.put("strategy", "accessibility id");
scrollObject.put("selector", "Splitting Touches across Views");
appiumDriver.executeScript("mobile: scroll", scrollObject);
appiumDriver.findElement(MobileBy.AccessibilityId("Splitting Touches across Views")).click();
scrollObject = new HashMap();
AndroidElement ele = (AndroidElement) appiumDriver.findElement(MobileBy.AndroidUIAutomator("resourceId(\"io.appium.android.apis:id/list2\")"));
scrollObject.put("element", ele.getId());
scrollObject.put("strategy", "-android uiautomator");
scrollObject.put("selector", "text(\"Aragon\")");
appiumDriver.executeScript("mobile: scroll", scrollObject);

**Comment by mykola-mokhnach** [comment]
Please provide the full server log

**Comment by KazuCocoa** [comment]
It probably depends on the index of scrollable instance.
Then, you can try out like the below `uiautomator` find by element to customize more for your environment if this works for you.

e.g.
https://github.com/appium/ruby_lib/blob/2adbb0e03e55f57f0c4001d1577d1577dfd63ae2/lib/appium_lib/android/element/generic.rb#L47

**Comment by sebinjoseph1994** [comment]
> Also, I can observe that scroll method itself simply passed the parameters to the `scrollIntoView` method of the particular UiScrollable instance: https://github.com/appium/appium-uiautomator2-server/blob/2f9d93efd6eaa25d9544d3307f738578dde6d6c8/app/src/main/java/io/appium/uiautomator2/utils/Device.java#L36
> 
> This means that we cannot do much there as this is an issue inside UiAutomator framework.

**Comment by sebinjoseph1994** [comment]
@mykola-mokhnach Please find the logs here. 
https://gist.github.com/sebinjoseph1994/e2a696fc0fe13dfeb4af4ee7889e3c67

**Comment by sebinjoseph1994** [comment]
@mykola-mokhnach While checking the uiautomator2 server code, I could see 
 _String W3C_ELEMENT_ID_KEY_NAME = "element-6066-11e4-a52e-4f735466cecf";_ under ElementConstants class. Is this the value that is expected there?

**Comment by sebinjoseph1994** [comment]
@mykola-mokhnach Sorry for the confusion caused there. It's actually _element_ only, the log I have uploaded was of my trial with ELEMENT as the argument. But I'm having the issue with _element_ as well.

**Comment by mykola-mokhnach** [comment]
I assume the root of your problem lies in https://github.com/SeleniumHQ/selenium/blob/b287e73ce2b148a2eff82539b9860a6237722c02/java/client/src/org/openqa/selenium/remote/RemoteWebDriver.java#L543

As a workaround you could try to call `execute(DriverCommand.EXECUTE_SCRIPT, params).getValue()` directly without unnecessary transformations that are done inside of this selenium function.

**Comment by mykola-mokhnach** [comment]
I'll add a patch to the driver, so it could also accept `elementId` parameter together with `element` to workaround this issue

**Comment by sebinjoseph1994** [comment]
@mykola-mokhnach Thanks much for looking at this. But I have the issue with _execute(DriverCommand.EXECUTE_SCRIPT, params).getValue()_ as well.

**Comment by mykola-mokhnach** [comment]
> But I have the issue with execute(DriverCommand.EXECUTE_SCRIPT, params).getValue() as well.

I don't know what other magic Selenium developers put there. At the end it is just a REST API, so you could use any available instruments to send a http request directly to the server URL. 
Or wait until appium@beta is published containing the patch above

**Comment by mykola-mokhnach** [comment]
Simply read the selenium source code, you have the starting point

**Comment by sebinjoseph1994** [comment]
Okay, let me try :)

**Comment by sebinjoseph1994** [comment]
@mykola-mokhnach The conversion occurs at https://github.com/SeleniumHQ/selenium/blob/b287e73ce2b148a2eff82539b9860a6237722c02/java/client/src/org/openqa/selenium/remote/RemoteWebDriver.java#L621 as well. 
If the _element_ is the culprit, won't similar issues happen with XCUITest mobile commands that use _element_?

**Comment by mykola-mokhnach** [comment]
> If the element is the culprit, won't similar issues happen with XCUITest mobile commands that use element?

Yes, it definitely could happen. It seems like this is only the case with java client so far, although it would also make sense to change `element` to `elementId` there to be on the safe side

> The conversion occurs at ...

This is applied to the response rather than to the request, so not a problem.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue. The patches have been published to appium@beta

**Comment by sebinjoseph1994** [comment]
@mykola-mokhnach Unfortunately, this is not working in the latest beta version as well.

**Comment by mykola-mokhnach** [comment]
Unfortunately "does not work" does not help to solve. Please provide the server logs

**Comment by sebinjoseph1994** [comment]
@mykola-mokhnach Please find the logs here - https://gist.github.com/sebinjoseph1994/8958cdcb4e495c82d4639c3f1666d731

**Comment by mykola-mokhnach** [comment]
> [HTTP] --> POST /wd/hub/session/d98c2fbf-2e94-4cca-9fae-3d480dea775b/execute/sync
> [HTTP] {"script":"mobile: scroll","args":[{"elementId":"00000000-0000-0476-ffff-ffff00000036","strategy":"-android uiautomator","selector":"text(\"Beaufort\")"}]}
> [debug] [W3C (d98c2fbf)] Calling AppiumDriver.execute() with args: ["mobile: scroll",[{"elementId":"00000000-0000-0476-ffff-ffff00000036","strategy":"-android uiautomator","selector":"text(\"Beaufort\")"}],"d98c2fbf-2e94-4cca-9fae-3d480dea775b"]
> [AndroidDriver] Executing native command 'mobile: scroll'
> [debug] [WD Proxy] Proxying [POST /touch/scroll] to [POST http://127.0.0.1:8200/wd/hub/session/c858cca2-1c26-4b2c-bfd9-94febcc1e124/touch/scroll] with body: {"params":{"origin":{"ELEMENT":"00000000-0000-0476-ffff-ffff00000036","element-6066-11e4-a52e-4f735466cecf":"00000000-0000-0476-ffff-ffff00000036"},"strategy":"-android uiautomator","selector":"text(\"Beaufort\")"}}
> [debug] [WD Proxy] Got response with status 200: {"sessionId":"c858cca2-1c26-4b2c-bfd9-94febcc1e124","value":null}
> [debug] [W3C (d98c2fbf)] Responding to client with driver.execute() result: null
> [HTTP] <-- POST /wd/hub/session/d98c2fbf-2e94-4cca-9fae-3d480dea775b/execute/sync 200 6759 ms - 14

I don't observe any issues there, the element identifier is passed properly. Perhaps the scrollable locator itself needs to be changed?

**Comment by sebinjoseph1994** [comment]
@mykola-mokhnach The issue is that instead of the element I have passed, the first scrollable element is being scrolled.

**Comment by mykola-mokhnach** [comment]
You could validate which element has been scrolled from the logcat output. Look for a string that looks like `Using %s as scrolling origin`

**Comment by sebinjoseph1994** [comment]
@mykola-mokhnach I couldn't find a matching text in logcat. The log is attached here https://gist.githubusercontent.com/sebinjoseph1994/d4efb2a453730b88a029d7bf799dfe5b/raw/92635cbe3a0935c2bfa0c3d158764fe0057bcf5f/logcat-15392.
But, based on the logs it looks like a different element is taken for scrolling(io.appium.android.apis:id/list1) instead of the one I have given(io.appium.android.apis:id/list2).

Please find the code to reproduce the issue here https://gist.github.com/sebinjoseph1994/9754089d4e023b95df75b30daba9a93c. I'm using _ApiDemos-debug.apk_ https://github.com/appium/appium/blob/master/sample-code/apps/ApiDemos-debug.apk for testing this.

**Comment by mykola-mokhnach** [comment]
Very handy log it is. Please check if https://github.com/appium/appium-uiautomator2-driver/pull/466 resolves the issue

**Comment by sebinjoseph1994** [comment]
@mykola-mokhnach Perfect. It's working now. Thank you so much Mykola for taking care of this as quickly as possible. We are really grateful for all your contributions to the testing community.

**Comment by jlipps** [comment]
❤️
