### ISSUE TITLE
Can appium open the application in my real iOS device but not install the application every time?

### ISSUE THREAD

**Issue by billylamch** [appium/appium#15405]
## The problem

Since my app needs users to enter the one time password sent to the user's phone every time, I cannot write script to bypass the OTP. If appium does not require users to reinstall the application every time but open the installed application in the phone, it will be convenient for me. If not, is there any methond to bypass it?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21
* Mobile platform/version under test: iOS14.5
* Real device or emulator/simulator: iPhone 6s

**Comment by mykola-mokhnach** [comment]
Unfortunately Appium is unable to provide such functionality. Consider changing the application under test itself to make it better compatible to automation strategies. 

Kindly use Appium forum to ask questions.

**Comment by jlipps** [comment]
You can certainly have appium just open your app without reinstalling. Just use the bundleId capability instead of the app capability.
