### ISSUE TITLE
Unable to download an appropriate version of chromedriver on Android 9

### ISSUE THREAD

**Issue by mwakizaka** [appium/appium#15404]
## The problem

- We happily use `chromedriver_autodownload` feature to test Android webview apps.
- However, since appium 1.21.0, it downloads a wrong version of chromedriver on Android 9.
- I think it is because [this change](https://github.com/appium/appium-chromedriver/pull/203/commits/108c32b04d47b9e3d2865fbf3c48f9cb750c9d18) makes appium 1.21.0 look up a version of Android System WebView, instead of a version of Chrome.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable): 1.20.2
* Desktop OS/version used to run Appium: Mac
* Node.js version (unless using Appium.app|exe): v12.13.1
* Npm or Yarn package manager: 6.12.1
* Mobile platform/version under test: Android 9
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: cli

## Link to Appium logs

- [GIST](https://gist.github.com/mwakizaka/8eb6a057379b2efb135ecfc2fbacf271)

**Comment by mykola-mokhnach** [comment]
> 2021-05-20 18:55:54:404 i [AndroidDriver] Not collecting web view details. Details collection might help to make Chromedriver initialization more precise. Use the 'enableWebviewDetailsCollection' cap to turn it on

I assume there was a good hint on what could be done. Otherwise the code is working as expected. I don't observe any issues there

**Comment by mykola-mokhnach** [comment]
It could also be that Chromedriver v90 is not in the static mapping yet, because it is too fresh. Then providing the updated mapping or installing appium@beta might help

**Comment by mwakizaka** [comment]
I confirmed the problem got resolved by using `enableWebviewDetailsCollection`. Thank you for your advice!
