### ISSUE TITLE
update packages to point to dependencies now living in monorepo, where appropriate

### ISSUE THREAD

**Issue by boneskull** [appium/appium#15402]
Any package in our org which depends on, say, `appium-gulp-plugins` should now depend on `@appium/gulp-plugins`.  

We will need to publish these monorepo packages first.

The sooner we do this, the sooner we can archive the original repo (e.g., `appium/appium-gulp-plugins`) and avoid the codebases diverging.

Packages depending on `appium-base-driver` *cannot* be updated to `@appium/base-driver`, since the monorepo version is the `2.0` branch of `appium/appium-base-driver`.  We'll need to leave those for now, and instead just archive the `2.0` branch in `appium/appium-base-driver`; new development should happen in the monorepo.

**Comment by jlipps** [comment]
NB: for drivers, this update will need to take place upon Appium 1.x EOL

**Comment by boneskull** [comment]
We need to enumerate what's left to do here, because many drivers have switched over to `@appium/*` deps...

**Comment by jlipps** [comment]
time for an org-wide grep!
