### ISSUE TITLE
Issue finding elements by Id for android with webdriverio and nodejs.

### ISSUE THREAD

**Issue by RonaldColyar** [appium/appium#15410]
## The problem

I am trying to use appium to click an android TextView , The documentation provides the following code sample:
```JavaScript
// webdriver.io example
$$("~SomeAccessibilityId");

// wd example
let elementsOne = await driver.elementsByAccessibilityId("SomeAccessibilityID");
let elementsTwo = await driver.elements("id", "SomeID");
```

The Textview that I am trying to click on is marked up with(got with getpagesource) :
``` xml
 <android.widget.TextView index="9" package="com.bamnetworks.mobile.android.ballpark" class="android.widget.TextView" text="Have an account? Log In" resource-id="com.bamnetworks.mobile.android.ballpark:id/welcome_to_login" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[326,1538][754,1673]" displayed="true" />
```
The code: 

``` JavaScript
// javascript

const wdio = require("webdriverio");

const opts = {
  path: '/wd/hub',
  port: 4723,
  capabilities: {
    platformName: "Android",
    deviceName: "Android Emulator",
    app: "C:/SourceCode/AppiumBallpark/ball.apk",
    appPackage: "com.bamnetworks.mobile.android.ballpark",
    automationName: "UiAutomator2"
  }
};

async function main () {
  const client = await wdio.remote(opts);
  const field = await client.$$("welcome_to_login");
  field.click();
}

main();
```

Id found inside of the appium gui inspector:

![appiumgui](https://user-images.githubusercontent.com/35206353/119215568-111d6f80-ba94-11eb-8dec-da307e5fc50c.png)

## Environment

* Appium version (or git revision) that exhibits the issue: Latest
* Desktop OS: Windows 10.
* Node.js version Node.js v14.17.0.
* Npm 
* Mobile platform : Android
* Real device or emulator/simulator:Android emulator for pixel 3a api 30
* Appium CLI or Appium.app|exe:

## Link to Appium logs
https://gist.github.com/RonaldColyar/8a8b439f83cefebb51d52d31aed3ece6

**Comment by jlipps** [comment]
How is one supposed to find an element by ID using webdriverio? the webdriverio usage example you shared above shows how to find using accessibility ID (which is not the same as ID)

**Comment by RonaldColyar** [comment]
@jlipps  This was a misunderstanding on my part. Thanks for your time , resolved my problem.
