### ISSUE TITLE
Can not specify   default-capabilities from command line on Windows

### ISSUE THREAD

**Issue by bearxc** [appium/appium#15412]
I tired following command line on appium server  1.21.0 and latest master branch on windows platform

node . -p 123456  -dc '{"noReset":true}'

 error: argument -dc/--default-capabilities: invalid parseDefaultCaps value: "'{noReset:true}'"

**Comment by KazuCocoa** [comment]
Perhaps the parsing method on Windows needs to coordinate.

**Comment by KazuCocoa** [comment]
macOS:
```
% appium  -dc '{"noReset":true}'
[Appium] Welcome to Appium v1.21.0
[Appium] Non-default server args:
[Appium]   defaultCapabilities: {
[Appium]     noReset: true
[Appium]   }
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   noReset: true
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
^C[Appium] Received SIGINT - shutting down
```

**Comment by mykola-mokhnach** [comment]
I assume Windows's cmd has different escaping rules. See, for example: https://stackoverflow.com/questions/14966989/escaping-curl-command-in-windows

**Comment by jlipps** [comment]
for windows you can't use single quotes if i remember correctly. so you'll need to do this:

```
node . -p 123456 -dc "{\"noReset\":true}"
```

**Comment by bearxc** [comment]
Yes, replace single quotes works fine on command line 

I still have same issue from appium java client  7.5.1 on windows platform

 AppiumServiceBuilder serviceBuilder = new AppiumServiceBuilder();

   ......

  DesiredCapabilities caps = new DesiredCapabilities();

   caps.setCapability("noSign", true);

serviceBuilder.withCapabilities(caps);

 AppiumDriverLocalService server = AppiumDriverLocalService.buildService(serviceBuilder);

  server.start();

appium: error: argument -dc/--default-capabilities: invalid parseDefaultCaps value: '{noReset:true,noSign:true}'
Disconnected from the target VM, address: '127.0.0.1:50313', transport: 'socket'

**Comment by jlipps** [comment]
OK, that would be an issue with the [Java client](https://github.com/appium/java-client) in that case.
