### ISSUE TITLE
[iOS]Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded

### ISSUE THREAD

**Issue by youngfreeFJS** [appium/appium#15422]
## The problem

> 2021-05-25 11:11:36:828 [W3C (ba368a77)] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded

## Environment

* Appium version (or git revision) that exhibits the issue: v1.20.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 10.15.7
* Node.js version (unless using Appium.app|exe): v12.18.3
* Npm or Yarn package manager: npm@6.14.6
* Mobile platform/version under test: iOS13.5(simulator)
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/youngfreeFJS/a72eb5ec8e9d46a380d60398b1135cc0

## Code To Reproduce Issue [ Good To Have ]

 it's not easier to reproduce the bug

**Comment by mykola-mokhnach** [comment]
It looks like WDA/XCTest stopped responding to Appium's requests. You could try to enable `showXcodeLog`/`showIOSLog` to see more details, but usually this is an issue on lower levels of automation stack, which only Apple or an application under test can fix.

**Comment by youngfreeFJS** [comment]
> It looks like WDA/XCTest stopped responding to Appium's requests. You could try to enable `showXcodeLog`/`showIOSLog` to see more details, but usually this is an issue on lower levels of automation stack, which only Apple or an application under test can fix.

I am trying ...

**Comment by youngfreeFJS** [comment]
> enable `showXcodeLog`/`showIOSLog` to see more details

more details with xcode log: https://github.com/appium/appium/issues/15422#issuecomment-847576656

I have set this parameter: `'snapshotMaxDepth': 100`, but it doesn't seem to work.

 Is it in milliseconds or seconds? @mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
> [Xcode] 2021-05-26 12:20:59.110624+0800 WebDriverAgentRunner-Runner[40151:3051982] The application com.meituan.imeituan is still waiting for its animations to finish after 2.000 seconds timeout. Making it to believe there are no animations
> [Xcode] 2021-05-26 12:20:59.110870+0800 WebDriverAgentRunner-Runner[40151:3051982] The timeout value could be customized via 'waitForIdleTimeout'/'animationCoolOffTimeout' settings

> Wed May 26 12:21:57 CST 2021 [Xcode] ) of 'XCUIElementTypeApplication (美团模拟)' after 15.00 seconds
> Wed May 26 12:21:57 CST 2021 [Xcode] 2021-05-26 12:21:41.138171+0800 WebDriverAgentRunner-Runner[40151:2901137] This timeout could be customized via 'customSnapshotTimeout' setting

I assume these log lines have good hints about which capability values one may try to change. But basically there is still not much to be done if these values are big enough and the application under test is hogging the UI thread or if it contains too many accessible elements on a single page.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
