### ISSUE TITLE
Empty HTML source after switching context to webview

### ISSUE THREAD

**Issue by thanhtan27081998** [appium/appium#15421]
## The problem
The automation test worked well but when I switched the context to webview and ran console.log(await driver.source()) commands, the output contained no elements.
```
<html><head></head><body></body></html>
```
## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.1
* Node.js version (unless using Appium.app|exe): 12.22.1
* Npm or Yarn package manager: npm 6.14.12
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real device 

## Link to Appium logs
```
> CALL contexts()
 > GET /session/:sessionID/contexts
 > RESPONSE contexts() ["NATIVE_APP","WEBVIEW_4612.2"]
>>>>>> contexts [ 'NATIVE_APP', 'WEBVIEW_4612.2' ]
 > CALL context("WEBVIEW_4612.2")
 > POST /session/:sessionID/context {"name":"WEBVIEW_4612.2"}
 > RESPONSE context("WEBVIEW_4612.2")
 > CALL source()
 > GET /session/:sessionID/source
 > RESPONSE source() "<html><head></head><body></body></html>"
>>>>>> source <html><head></head><body></body></html>
    ✓ should get text UIKitCatalog (1753ms)
 > CALL quit()
 > DELETE /session/:sessionID
```

## Code To Reproduce Issue [ Good To Have ]
Here is the code that I used for my applicationn
```
<SafeAreaView style={{flex: 1}}>
        <TextInput
          name={'name_text_input'}
          accessibilityLabel={'access_text_input'}
          testID={'text_input'}
          accessible={true}
          autoCapitalize={'none'}
          autoCorrect={false}
          style={{width: Dimensions.get('window').width, height: 100}}
          onChangeText={this.onChangeText}
          placeholder="Enter your URL"
        />
        <Button
          name={'name_button'}
          accessibilityLabel={'access_button'}
          accessible={true}
          onPress={this.onPress}
          title={'GO'}
          testID={'button_go'}
        />
        <WebView
          name={'name_web_view'}
          accessibilityLabel={'access_web_view'}
          testID={'web_view'}
          accessible={true}
          source={{uri: this.state.url}}
        />
      </SafeAreaView>
```

**Comment by jlipps** [comment]
What do you expect the HTML to be?

**Comment by thanhtan27081998** [comment]
I expect the HTML to contain my elements such as my input text field and button as my application code

**Comment by jlipps** [comment]
Are you referring to the TextInput and Button elements in the JSX above? Those are native elements and would not show up in a webview.

**Comment by thanhtan27081998** [comment]
Too bad :( Ok then you can close this ticket for now <3 Thank you

**Comment by jlipps** [comment]
No problem. And a good thing you're using Appium, since those elements should be interacted with in the default native mode!
