### ISSUE TITLE
Socket hang up Error

### ISSUE THREAD

**Issue by kaungkhantsoe** [appium/appium#15429]
## The problem

Getting following socket hang up error trying to run on real device. I am using UIKitCatalog as sample project.

Encountered internal error running command: Error: Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.

Already tried removing application and restarting device, still experiencing the issue.

## Environment

Appium version 1.21.0
Node version 16.2.0
Trying to run on Iphone X(iOS 14.5.1) using CLI

https://gist.github.com/kaungkhantsoe/d4178232e839bb6dc7f94d76d09eb598

**Comment by mykola-mokhnach** [comment]
I don't see any issues in the attached log. Did you follow the tutorial above? Have you tried to deploy WebDriverAgent to the device manually using Xcode?

**Comment by kaungkhantsoe** [comment]
The log doesn't show error code like in the tutorial, instead it says 

xcodebuild exited with code 'null' and signal 'SIGTERM'

Is it not an error? I didn't tried to deploy WDA manually. The app is installed but not launched as expected. I've already tried using emulator and it was deployed and launched successfully. I just have the issue with real device.

**Comment by mykola-mokhnach** [comment]
It won't work on real device just "out of the box" due to Apple's security limitations. The tutorial describes how to properly sign the WDA sources.

**Comment by kaungkhantsoe** [comment]
Ahh... I see. Thank you.
