### ISSUE TITLE
Appium could not access on the element of list | Android | Uiautomator2

### ISSUE THREAD

**Issue by baselalali** [appium/appium#15427]
## The problem

The App displays a suggestion list for place, when the user enter an address. The Problem is, the element on the list could not be founded in the current page source.

![image](https://user-images.githubusercontent.com/82577381/119643530-21c74000-be1c-11eb-8f5b-8e95bb5cdc2c.png)
 
## Environment

* Last Appium version that did not exhibit the issue (if applicable): v.12.2
* Desktop OS/version used to run Appium: Desktop OS
* Mobile platform/version under test: Andorid
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium.app

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Code To Reproduce Issue [ Good To Have ]
This is my current setting of driver
`{"actionAcknowledgmentTimeout":3000,"allowInvisibleElements":false,"autoUpdateImageElementPosition":false,"checkForImageElementStaleness":true,"defaultImageTemplateScale":1,"elementResponseAttributes":"","enableMultiWindows":false,"enableNotificationListener":true,"fixImageFindScreenshotDims":true,"fixImageTemplateScale":false,"fixImageTemplateSize":false,"getMatchedImageResult":false,"ignoreUnimportantViews":false,"imageElementTapStrategy":"w3cActions","imageMatchThreshold":0.4,"keyInjectionDelay":0,"mjpegBilinearFiltering":false,"mjpegScalingFactor":50,"mjpegServerFramerate":10,"mjpegServerPort":7810,"mjpegServerScreenshotQuality":50,"normalizeTagNames":false,"scrollAcknowledgmentTimeout":200,"serverPort":6790,"shouldUseCompactResponses":true,"shutdownOnPowerDisconnect":true,"simpleBoundsCalculation":false,"trackScrollEvents":true,"useResourcesForOrientationDetection":false,"waitForIdleTimeout":10000,"waitForSelectorTimeout":10000,"wakeLockTimeout":85955239}`

**Comment by mykola-mokhnach** [comment]
Make sure the destination element is accessible. If it is not accessible then the described behaviour is expected.

**Comment by baselalali** [comment]
The element is accessible, since i can tap using his coordination the ui. But appium did not display it on the page source.

**Comment by mykola-mokhnach** [comment]
> The element is accessible, since i can tap on it using his coordination the ui.

The original meaning of "accessible" in that context is that the element is available for the Android Accessibility Service. Read 
https://developer.android.com/guide/topics/ui/accessibility/apps
https://developer.android.com/guide/topics/ui/accessibility/principles 
for more details.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
