### ISSUE TITLE
The folder “WebDriverAgentRunner_iphonesimulator14.4-x86_64.xctestrun” doesn’t exist

### ISSUE THREAD

**Issue by rajeev887** [appium/appium#15437]
## The problem

Getting an error while trying to start my IOS app via appium. WDA does not start up.
This is not the same as #12581

## Environment

* Appium version (or git revision) that exhibits the issue: 1.19.1
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: MAC Catalina
* Node.js version (unless using Appium.app|exe): 6.14.10
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: 14.4 & xcode version 12.4
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium.app

## Details

Getting an error while trying to start my IOS app via appium. WDA does not start up.
Entire stack trace in gist.github.com.

XCUITest][39m The app has been installed successfully.
[debug] [35m[BaseDriver][39m Event 'appInstalled' logged at 1622306333641 (11:38:53 GMT-0500 (Central Daylight Time))[info] [35m[WD Proxy][39m connect ECONNREFUSED 127.0.0.1:8100
[debug] [35m[WebDriverAgent][39m WDA is not listening at 'http://127.0.0.1:8100/'
[debug] [35m[WebDriverAgent][39m WDA is currently not running. There is nothing to cache
[debug] [35m[XCUITest][39m Trying to start WebDriverAgent 2 times with 10000ms interval

[error] [35m[Xcode][39m 2021-05-29 11:38:59.750 xcodebuild[46071:1453357] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder “WebDriverAgentRunner_iphonesimulator14.4-x86_64.xctestrun” doesn’t exist." UserInfo={NSFilePath=/Users/rc119/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Build/Products/WebDriverAgentRunner_iphonesimulator14.4-x86_64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7fd691693600 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[error] [35m[Xcode][39m 

## Link to Appium logs

Entire appium stack trace.
https://gist.github.com/rajeev887/0e477543121a3b5e3ec842cd7702cb59

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
- Appium 1.19 won't work with iOS 14.4. Please update to the most recent version
- Please provide the log with showXcodeLog cap enabled

**Comment by rajeev887** [comment]
Thank you @mykola-mokhnach 

- So you are suggesting i update appium desktop to the latest version.?
- Here is the log with showXcodeLog cap enabled -> https://gist.github.com/rajeev887/aa1e15878c191eb27e2fdc29a72581f9

**Comment by rajeev887** [comment]
I updated to the latest version and its fixed. Appium is able to run my IOS app.
