### ISSUE TITLE
How to improve the speed of finding elements when there are a lot of dynamic changes on the page in IOS

### ISSUE THREAD

**Issue by leeyc0704** [appium/appium#15448]
## The problem

My test page is a stock quotation page， Because of market data, the page changes dynamically every second，this caused me to be very slow even if I use accid to get the element position，are there any parameters, these dynamic elements can be ignored after setting, so as to improve the running speed，give some experience, thank you~

**Comment by mykola-mokhnach** [comment]
Kindly use Appium forum to ask questions.
