### ISSUE TITLE
flutter app some elements are offset

### ISSUE THREAD

**Issue by llpan-github** [appium/appium#15444]
## The problem
when i use uiautomator2 in flutter app
Some elements are offset like this picture

![image](https://user-images.githubusercontent.com/69832189/120185027-3fddd780-c244-11eb-9031-7826605ddce1.png)

## Environment
Appium version (or git revision) that exhibits the issue: 1.20.2
Desktop OS/version used to run Appium: MAC OS - BigSur 11.2.3 & MAC OS - Catalina 10.15.7
Node.js version (unless using Appium.app|exe): v15.12.0
Npm or Yarn package manager: Npm
Mobile platform/version under test: android 10
Real device or emulator/simulator: Real Device
Appium CLI or Appium.app|exe: Appium CLI & Appium.app

**Comment by mykola-mokhnach** [comment]
These offsets are defined by the application under test itself and then exposed to the Accessibility manager. There is nothing that could be done on Appium side about it.

Closed as not an issue
