### ISSUE TITLE
App crashing with "Failed to create file - SQLite" error with Xcode 12.4

### ISSUE THREAD

**Issue by khsarma** [appium/appium#15445]
## The problem

App is installed on IOS simulator. After the launching app thru appium script, app is getting opened and crashed multiple times and finally script fails. 
This is wrt. issue: https://github.com/appium/appium/issues/15358
After debugging the crash reports against appium, found that app is crashing due to issue with coredata:
[com.apple.coredata:error] error: addPersistentStoreWithType:configuration:URL:options:error: returned error NSCocoaErrorDomain (512)

## Environment

- Appium version (or git revision) that exhibits the issue: Appium CLI 1.22.0-beta (1.21.0 as well)
- Last Appium version that did not exhibit the issue (if applicable): NA
- Desktop OS/version used to run Appium: MacOS Catalina 10.15.7
- Node.js version (unless using Appium.app|exe): v13.8.0
- Npm or Yarn package manager: npm
- Mobile platform/version under test: IOS 14.4 sdk
- Real device or emulator/simulator: Simulator (12.4, 13.3, 14.4)
- Appium CLI or Appium.app|exe: Appium CLI
- XCode: 12.4

## Details

This is happening after upgrading XCode to 12.4. 

- Tried different appium versions (1.21.0 and beta) against different simulator versions (12.4, 13.3, 14.4). 
- Tried different appium capabilities.
- Able to open app manually
- XCUItests are running fine against the app.
- Once the app crashed using appium, app crashes while opening manually as well. Had to re-install the app.

Original Error:

> �[35m[WD Proxy]�[39m Got response with status 400: {"value":{"error":"invalid element state","message":"The application under test with bundle id '' is not running, possibly crashed","traceback":"(\n\t0 CoreFoundation 0x00007fff20421af6 __exceptionPreprocess + 242\n\t1 libobjc.A.dylib 0x00007fff20177e78 objc_exception_throw + 48\n\t2 CoreFoundation 0x00007fff20421797 -[NSException init] + 0\n\t3 WebDriverAgentLib 0x000000010e89e24b -[FBSession activeApplication] + 667\n\t4 WebDriverAgentLib 0x000000010e8ce11a +[FBSessionCommands currentCapabilities] + 90\n\t5 WebDriverAgentLib 0x000000010e8cdfe9 +[FBSessionCommands sessionInformation] + 233\n\t6 WebDriverAgentLib 0x000000010e8ca8cf +[FBSessionCommands handleCreateSession:] + 3551\n\t7 WebDriverAgentLib 0x000000010e85cce6 -[FBRoute_TargetAction mountRequest:intoResponse:] + 182\n\t8 WebDriverAgentLib ...
> [debug] �[35m[W3C]�[39m Matched W3C error code 'invalid element state' to InvalidElementStateError
> [debug] �[35m[XCUITest]�[39m Failed to create WDA session (The application under test with bundle id ' is not running, possibly crashed)

CoreData error:

> [35m[IOSSimulatorLog][39m [IOS_SYSLOG_ROW] 2021-05-31 14:24:15.488 E  coredataSample[11945:6f5ce] [com.apple.coredata:error] error: addPersistentStoreWithType:configuration:URL:options:error: returned error NSCocoaErrorDomain (512)
> [35m[IOSSimulatorLog][39m [IOS_SYSLOG_ROW] 2021-05-31 14:24:15.488 Df coredataSample[11945:6f5ce] [com.apple.coredata:annotation] annotation: userInfo:
> [35m[IOSSimulatorLog][39m [IOS_SYSLOG_ROW] 2021-05-31 14:24:15.488 Df coredataSample[11945:6f5ce] [com.apple.coredata:annotation] annotation: 	reason : Failed to create file; code = 2
> [35m[IOSSimulatorLog][39m [IOS_SYSLOG_ROW] 2021-05-31 14:24:15.488 Df coredataSample[11945:6f5ce] [com.apple.coredata:annotation] annotation: storeType: SQLite
> [35m[IOSSimulatorLog][39m [IOS_SYSLOG_ROW] 2021-05-31 14:24:15.488 Df coredataSample[11945:6f5ce] [com.apple.coredata:annotation] annotation: configuration: (null)

## Link to Appium logs

https://gist.github.com/khsarma/09d015660cebf09f3a106890abc4ab8f
[coredataSample.zip](https://github.com/appium/appium/files/6570518/coredataSample.zip)

## Code To Reproduce Issue [ Good To Have ]

Attached sample coredata app to reproduce app crash issue - App is supposed to display blank white screen (with coredata features) without crashing.

**Comment by KazuCocoa** [comment]
What about specifying `app` to the app under test like https://gist.github.com/KazuCocoa/a7bffcb147c6b03ca5ada9cb577fe1a0 ?
Then, the session was able to call activate/terminate app without issues on my env. It was able to get the page source.

> XCUItests are running fine against the app.

Do you mean like the below code? I've added the below test code in your attached project on my local.
Then, the app was installed every run like Appium does with `app: 'path/to/.app/file'`
So, I haven't tested exact the same situation when Appium called the app under test with only `bundleId` case with XCTest. It would be helpful how you ensured _XCUItests are running fine against the app._
```swift
    func testExample() throws {
        let app = XCUIApplication(bundleIdentifier: "com.mina.coredataSample")
        app.launch() // app.activate()
    }
```

**Comment by mykola-mokhnach** [comment]
I don't think how WebDriverAgent is related to the mentioned crash. It makes sense to add extended debugging to the app under test and collect the full crash report stack to investigate what exactly is causing the failure

**Comment by khsarma** [comment]
> I don't think how WebDriverAgent is related to the mentioned crash. It makes sense to add extended debugging to the app under test and collect the full crash report stack to investigate what exactly is causing the failure

Attached crash report - will this help?
[coredataSample_crashreport.txt](https://github.com/appium/appium/files/6573441/coredataSample_crashreport.txt)

**Comment by khsarma** [comment]
> What about specifying `app` to the app under test like https://gist.github.com/KazuCocoa/a7bffcb147c6b03ca5ada9cb577fe1a0 ?

I'll try this and let you know..

> Do you mean like the below code? I've added the below test code in your attached project on my local.

We have different set of XCUItests which use bundle id to launch app.

**Comment by mykola-mokhnach** [comment]
> https://stackoverflow.com/questions/14067811/how-to-solve-unable-to-load-persistent-store-at-url-error

SO recommends to reset Simulator in order to workaround such error. And the error itself might be happening because of the schema change. Nevertheless I still cannot imagine how it could be related to WebDriverAgent usage.

**Comment by khsarma** [comment]
@KazuCocoa : using the full path of app worked while its crashing when used bundle id. Thanks for the input..
What's the difference between bundleId and full path from the perspective of launching or coredata?

**Comment by KazuCocoa** [comment]
No, special.
The difference is whether xcuitest-driver installs the app after removing it once (if no noReset: true) or skip the installation process.
https://github.com/appium/appium-xcuitest-driver/blob/5675b01cb18b252e5e8d1688bb51844d47d290ea/lib/real-device-management.js#L45-L66
Launching the app calls the same API end in XCTest framework.

So, I guess the app under test's status get weird situation after stopping the app process(?).

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
