### ISSUE TITLE
iOS WebDriverAgentRunner-Runner process growth high in memory usage and crashes during long test sessions (12+ hours)

### ISSUE THREAD

**Issue by rakhmatullov** [appium/appium#15457]
## The problem
During long test runs iOS WebDriverAgentRunner-Runner process growth from ~20Mb to about 2Gbs of Memory usage in real iPhone XR device. Then the process crashes and no connection retries to WDA work from Appium server side.

## Environment

* Appium version 1.21;
* Last Appium version that did not exhibit the issue (if applicable): 1.19 (at least memory growth didn't lead to the process crash)
* Desktop OS/version used to run Appium: MacOS
* Node.js version (unless using Appium.app|exe): v12.16.1
* Npm or Yarn package manager: npm 
* Mobile platform/version under test: iOS 14.5.1
* Real device or emulator/simulator: real iPhone XR
* Appium CLI or Appium.app|exe: CLI

## Details

After upgrading to Appium version 1.21 we started to experience an issue of WebDriverAgent crashing after 12+ hours of test scenario execution in real device (this was not verified in iOS simulator, but could be the problem there also because the WebDriverAgentRunner-Runner process in the simulator also growth in memory usage highly during hours of execution.

## Link to Appium logs

this is not Appium server problem but the problem with WebDriverAgent. After the iOS WebDriverAgentRunner-Runner process crashes appium continues tries to connect to it but has not success. At that moment after monitoring iOS processes on the device - it's clear that the WebDriverAgentRunner-Runner process isn't there already.

## Code To Reproduce Issue [ Good To Have ]

There is a long iterative app specific test scenario here containing clicks, swipes, page_source calls, on-screen device keyboard interaction, web elements properties requesting (like text, names and others);

# Additional info:
These are just screen-recordings of short intervals during tests execution where it's clearly visible that the process continuously growth in memory usage. The WebDriverAgentRunner-Runner process starts from just 20MiBs on start of the long scenario execution, before it crashed we saw this grown to 1.5+GiBs. I suppose that it crashes on device out-of-memory when reaching 2+ GiBs in memory usage.

https://user-images.githubusercontent.com/5517337/120501806-92e19700-c3ca-11eb-8808-b9fba2190680.mov

https://user-images.githubusercontent.com/5517337/120501995-b99fcd80-c3ca-11eb-9d85-1d0a9f2797b6.mov

https://user-images.githubusercontent.com/5517337/120502882-7abe4780-c3cb-11eb-8ee5-bcb57ec6caf9.mov

Please inform if there is some helpful information which I can provide which may be required for problem resolution.

**Comment by mykola-mokhnach** [comment]
Please provide the process memory dump when the memory usage gets too high

**Comment by rakhmatullov** [comment]
> Please provide the process memory dump when the memory usage gets too high

Ok, I'll do that as soon as I can if that doesn't carry any sensitive information.

**Comment by rakhmatullov** [comment]
@mykola-mokhnach what kind of dump format will be convenient for you? What tool usage for dumping should be good?

**Comment by mykola-mokhnach** [comment]
Basically what I would like to know is which data structure(s) allocate the most space in the heap. Perhaps, the best way to do it would be to instrument the process from Xcode, but I've also seen several more tools (lldb for example) which could help to achieve that.

**Comment by rakhmatullov** [comment]
@mykola-mokhnach Hello.

This is screenshot of Allocations tool when recording WebDriverAgentRunner-Runner process allocations during test run for just about an hour (after that Allocations tool consumed too much memory and the machine became almost unresponsive). The list was sorted by the "Persistent" property having higher on top.
![1623068530286](https://user-images.githubusercontent.com/5517337/121016793-3b19a600-c7a5-11eb-868b-2565f6df694d.jpg)

Is that helpful? What other information can I provide?

**Comment by mykola-mokhnach** [comment]
Thanks, this is something we could start with. The only place where Elements could be cached is FBElementCache. Try to decrease the maximum size of it to 512 items or less in https://github.com/appium/WebDriverAgent/blob/c7f01c839f9f1284e1319ccce096f6ac96153a40/WebDriverAgentLib/Routing/FBElementCache.m#L22 and see it that helps

**Comment by rakhmatullov** [comment]
> Thanks, this is something we could start with. The only place where Elements could be cached is FBElementCache. Try to decrease the maximum size of it to 512 items or less in https://github.com/appium/WebDriverAgent/blob/c7f01c839f9f1284e1319ccce096f6ac96153a40/WebDriverAgentLib/Routing/FBElementCache.m#L22 and see it that helps

I'll try and come back with results.

**Comment by rakhmatullov** [comment]
@mykola-mokhnach 
seems ELEMENT_CACHE_SIZE decrease to 512 didn't help much. As the process still growth in memory usage over time seemingly similar.
<img width="770" alt="Знімок екрана 2021-06-07 о 21 19 18" src="https://user-images.githubusercontent.com/5517337/121069755-8bf5c280-c7d6-11eb-9054-1947f74b1ea4.png">
Does it have sense to try lower value, like 50 or 100? Will that be still workable with 0 value?

**Comment by mykola-mokhnach** [comment]
yes, try setting it to 100 or 50, and observe if the memory usage still growth over time. Setting the cache size to zero won't work as it would not be possible to interact with any previously found element (stale element exception will be always thrown)

**Comment by rakhmatullov** [comment]
@mykola-mokhnach 
Is it implemented like the element cache (like I guess is XCElementSnapshot, XCAccessibilityElement, AXUlement) becomes stale after some interval of time and then becomes cleared and deallocated from memory? In the test even when I do a pause during a long rung I don't see the process allocated memory getting deallocated noticeably even when no interaction with the WDA server is in place, does this mean that there's no mechanism of deallocation of stale element cache? Or there is a chance that this is not the cache which leads to un-reversible memory consumption growth by the process.

**Comment by mykola-mokhnach** [comment]
It is not always clear what exactly is flooding the memory. That is why it is important to figure out which block of code influences that chart. Elements cache is a LRU cache and recycles extra (oldest) elements as soon as its size reaches the limit. Ofc there might be other places in the code which leak objects and it is important to figure out what are they.

**Comment by rakhmatullov** [comment]
@mykola-mokhnach 
I've set the ELEMENT_CACHE_SIZE to 100 and deployed the WDA to the device.
Here's the process memory picture after about an hour tests execution:
<img width="1179" alt="Знімок екрана 2021-06-08 о 19 38 14" src="https://user-images.githubusercontent.com/5517337/121224811-97f28a80-c891-11eb-889f-b2422f8ab2e4.png">

**Comment by mykola-mokhnach** [comment]
This looks good. Try to run it for longer time with that cache size and observe if the memory is not leaking anymore, at least not too fast.

**Comment by rakhmatullov** [comment]
I will. It's just that on the longer interval that's harder to use Allocations as it also tremendously growth in memory when recording during long periods.

**Comment by mykola-mokhnach** [comment]
I feel your pain. Memory leak issues are, probably, the most complicated to solve. Let us know if there are any updates, we could definitely consider to decrease the maximum size of the cache if necessary.

**Comment by rakhmatullov** [comment]
During about 5-6 hours of tests execution the process has grown to ~732 MiB.
<img width="1226" alt="Знімок екрана 2021-06-09 о 08 32 21" src="https://user-images.githubusercontent.com/5517337/121299027-7c24ce00-c8fd-11eb-8dce-39e630c302c2.png">

So the ELEMENT_CACHE_SIZE change doesn't seem to make much difference for memory leakage.
This screenshot was made after several hours of no test activity after the test over - so this seems that no garbage collection cleans the allocated memory over time.

**Comment by mykola-mokhnach** [comment]
I've created a PR which ensures the clueanup of snapshots information from the cache: https://github.com/appium/WebDriverAgent/pull/510/files

You could try to apply it locally and see if that helps to reduce the memory usage

**Comment by rakhmatullov** [comment]
I plan to try the branch mentioned above today-tomorrow.

**Comment by rakhmatullov** [comment]
@mykola-mokhnach Unfortunately it seems that the branch doesn't help much.
Here's a Activity Monitor state of the WebDriverAgentRunner-Runner process after about 6h of execution with the build built from the branch "cache_snap", it's a bit less than 900MiBs in memory. Please be aware that all this time we use the same WDA session with no restarts and reconnections.
<img width="1494" alt="Знімок екрана 2021-06-11 о 20 05 18" src="https://user-images.githubusercontent.com/5517337/121724661-da65d280-caf0-11eb-9a50-0f23b1561f4d.png">

**Comment by mykola-mokhnach** [comment]
It also could be that XCTest itself is leaking memory somewhere. Unfortunately I cannot help more there. Feel free to contribute if you could find more leaks there

**Comment by rakhmatullov** [comment]
@mykola-mokhnach could you please answer couple of questions for me to better understand how that works from WDA side:
1. Does XCTest run as separate process/service/driver or it runs as a part of WebDriverAgentRunner-Runner process as an imported external module?
2. Are XCElementSnapShot, XCAccessibilityElement process substructures utilising XCTest modules? Are they running in own threads?

**Comment by mykola-mokhnach** [comment]
> Does XCTest run as separate process/service/driver or it runs as a part of WebDriverAgentRunner-Runner process as an imported external module?

This is not documented anywhere (internal Apple stuff, yolo). From my observations there is testmanagerd process running on the device and talking to the xctest client using its own special protocol. So basically any test runner is a separate application with its own process (although it is different from other "normal" apps, since it has more privileges and uses XCTest APIs). The whole chain looks like: test runner app process->xctest client->testmanagerd server.

> Are XCElementSnapShot, XCAccessibilityElement process substructures utilising XCTest modules? Are they running in own threads?

Yes, these structures are internal XCTest classes. You could find them if you dump xctest platform headers. Basically all UI interactions must by running on the main UI thread. This is the reason XCTest requires it by be in idle state, at least periodically. The stuff which is not directly related to accessibility interactions might be executed in background threads though.

**Comment by rakhmatullov** [comment]
@mykola-mokhnach in your honoured opinion is it possible to have these classes (XCElementSnapShot, XCAccessibilityElement) or their instances cleared/reloaded when grown high in memory consumption with no breakage of WebDriverAgentRunner session and app session?

**Comment by mykola-mokhnach** [comment]
I don't know. These classes are internal to XCTest and I have no idea how it works from the inside

**Comment by rakhmatullov** [comment]
@mykola-mokhnach good day to you.

I did some tests of "WebDriverAgentRunner-Runner" to find the operation causing high leakage of memory.
For now I've found that script operations
`driver.execute_script('mobile: swipe', {'direction': 'up'})`
`driver.execute_script("mobile: scroll", {"direction": "down"})`
cause rather high memory leakage.
I did 1000 swipes in the app view which is swipable but has just one page so shouldn't lead to DOM changes after swipe. This led to growth of memory consumed by "WebDriverAgentRunner-Runner" process from about 55Mb to about 250Mb.
<img width="1038" alt="start_memory_usage" src="https://user-images.githubusercontent.com/5517337/126283562-881251a3-9edd-4567-bd79-5dee8f95da27.png">
<img width="1005" alt="end_memory_usage" src="https://user-images.githubusercontent.com/5517337/126283571-4bfe079d-987e-41d1-9bd4-7315ab9d21f4.png">

Actually positional point swipes also lead to memory usage growth (again even when 1 page there and no DOM refresh is required).

We do a lot of swipes in the tests - so the swipes leak could be 1 of the highest impacts in the issue mentioned above.
I'll do other operations checks also and report if find something alike. 

@mykola-mokhnach Does this relate to XCTest?
Do you suggest to raise that to Apple?

**Comment by rakhmatullov** [comment]
find_elements by xpath also leads to memory growth but a bit less than script action (like 30% less)
swipes with user actions press -> move -> release also lead to growth but again a bit less than when using script calls (like 30% less).

**Comment by mykola-mokhnach** [comment]
I can only observe one potential API call that may cause a potential memory leak in /swipe. Merged a PR to address it: https://github.com/appium/WebDriverAgent/pull/519

The `scroll` API contains much more stuff and it would be hard to track it.

**Comment by rakhmatullov** [comment]
thank you. I'll try that. Here I pointed 'scroll' by mistake. Usually we use 'swipe'.

**Comment by rakhmatullov** [comment]
> @mykola-mokhnach good day to you.
> 
> I did some tests of "WebDriverAgentRunner-Runner" to find the operation causing high leakage of memory.
> For now I've found that script operations
> `driver.execute_script('mobile: swipe', {'direction': 'up'})`
> `driver.execute_script("mobile: scroll", {"direction": "down"})`
> cause rather high memory leakage.
> I did 1000 swipes in the app view which is swipable but has just one page so shouldn't lead to DOM changes after swipe. This led to growth of memory consumed by "WebDriverAgentRunner-Runner" process from about 55Mb to about 250Mb.
> <img alt="start_memory_usage" width="1038" src="https://user-images.githubusercontent.com/5517337/126283562-881251a3-9edd-4567-bd79-5dee8f95da27.png">
> <img alt="end_memory_usage" width="1005" src="https://user-images.githubusercontent.com/5517337/126283571-4bfe079d-987e-41d1-9bd4-7315ab9d21f4.png">
> 
> Actually positional point swipes also lead to memory usage growth (again even when 1 page there and no DOM refresh is required).
> 
> We do a lot of swipes in the tests - so the swipes leak could be 1 of the highest impacts in the issue mentioned above.
> I'll do other operations checks also and report if find something alike.
> 
> @mykola-mokhnach Does this relate to XCTest?
> Do you suggest to raise that to Apple?

@mykola-mokhnach with the latest source from master which supposedly includes the PR mentioned by you above I got about 20% less memory usage at the end of the scenario mentioned in the quoted passage.
<img width="1049" alt="Знімок екрана 2021-07-26 о 13 09 08" src="https://user-images.githubusercontent.com/5517337/126972487-51dadfe4-fa89-4079-aa93-7dd85bf076a7.png">

I will also try other scenario including horizontal swipes and find_element actions and note here.

**Comment by rakhmatullov** [comment]
about thousand find_elements operations on the same page still leads to rather high process memory growth:
<img width="1050" alt="Знімок екрана 2021-07-26 о 14 25 49" src="https://user-images.githubusercontent.com/5517337/126981555-0f9131a8-5a2d-441d-9ca9-ee9a7bce019f.png">

**Comment by rakhmatullov** [comment]
That's the second result of horizontal swipe in contrast to vertical. From my side that looks better than before in terms of memory consumption.
<img width="971" alt="Знімок екрана 2021-07-26 о 16 27 06" src="https://user-images.githubusercontent.com/5517337/126996727-6d644c52-6aac-4d13-b3c5-431a5a35d656.png">

But the find_elements with the XPath still causes rather high memory footprint after many iterations. I'll try to find more detailed info on that request memory leaking for reporting either here or directly to Apple.

**Comment by mykola-mokhnach** [comment]
Recently we've found an issue in the elements cache implementation. The patch to that issue is already in WebDriverAgent master branch. Feel free to check the current memory consumption there.

**Comment by rakhmatullov** [comment]
@mykola-mokhnach 
That sounds nice. Thank you for informing. I'll try that with the tests which I used before to reproducing and note here as soon as I have a chance.

**Comment by rakhmatullov** [comment]
@mykola-mokhnach seems really nice. In the multiple find_elements case where I got 1.38Gb of memory consumed by the process previously - I now get 219Mb consumed by the process at the end. Thank you for this from me personally and congratulations for achieving such a good result :). Swipe cases also seem to grow memory several times less also (no values I can provide right now, but if needed I'll collect them).

**Comment by rakhmatullov** [comment]
I guess the problem for multi-days runs which we had before because of this leak will now be resolved (at least to no breaking execution). If you wish we can close the item @mykola-mokhnach.

**Comment by mykola-mokhnach** [comment]
It's nice to see that. We'd never achieve such result without your assistance. I was able to find at least a couple of potential memory leaks in the sources.
