### ISSUE TITLE
same method can only find one character 

### ISSUE THREAD

**Issue by billychen2014** [appium/appium#15453]
## The problem

i can use the method driver.find_element_by_ios_predicate(f"name CONTAINS '0'") to find the element '0' , but i can not find the element which value is '10002' in the same app and same page

## Environment

* Appium version (or git revision) that exhibits the issue: v1.18.1
* Desktop OS/version used to run Appium: Mac OS 10.15.4 
* Node.js version (unless using Appium.app|exe): node version: v14.16.1
* Mobile platform/version under test: iOS 13.6
* Real device or emulator/simulator: Real device

## Link to Appium logs

https://gist.github.com/billychen2014/b45aeb42585511297c608c0ae1dbefa9

## Code To Reproduce Issue [ Good To Have ]

the app i used is special which translated from vue to  iOS native ( weex as  Bottom Technology as i konw)

**Comment by billychen2014** [comment]
the page source while issue occurred :
https://gist.github.com/billychen2014/6fc4a2db65ccb692c35700f95e9c5e2a

i tried to use any way to find the same element , and found that 'find_element_by_accessibility_id' works well

**Comment by mykola-mokhnach** [comment]
This is expected. the search must be done by `value` attribute instead: `value CONTAINS '0'`. the fact that the element is found by accessiblity id, while its name is not the same as expected, but the value, is a bug, which was fixed in recent Appium versions.

**Comment by amedvedjev** [comment]
try predicate:
```
"value CONTAINS[cd] '0'"
```

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
