### ISSUE TITLE
Encountered applesimutils binary has not been found in your PATH

### ISSUE THREAD

**Issue by viveksoundar** [appium/appium#15450]
## The problem

Using applesimutils to give permissions to apps during autoamtion. I've installed the applesimutils 0.9.2 package using  brew tap wix/brew && brew install applesimutils. but still, I face the error during the automation started. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: 11.4 Big sur
* Node.js version (unless using Appium.app|exe):v14.17.0
* Npm or Yarn package manager:
* Mobile platform/version under test:14.5
* Real device or emulator/simulator:simulator
* Appium CLI or Appium.app|exe:CLI

## Note
I am running the appium scripts from jenkins pipeline.

## Link to Appium logs

org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: applesimutils binary has not been found in your PATH. Please install it ('brew tap wix/brew && brew install wix/brew/applesimutils') to be able to change application permissions

**Comment by mykola-mokhnach** [comment]
Have you checked the PATH env variable value for the Appium process as described in https://github.com/appium/java-client/blob/master/docs/environment.md ?

**Comment by viveksoundar** [comment]
Yes, I've checked. that works fine for android specific cases. only for iOS, I get this error.

**Comment by mykola-mokhnach** [comment]
Could you please attach the actual env output for the Appium process?

**Comment by viveksoundar** [comment]
Yes, I get this in my environment variables
```
{PATH=/usr/local/bin/applesimutils:/usr/bin:/bin:/usr/sbin:/sbin, RUN_DISPLAY_URL=http://localhost:8080/job/TestPipeline/3/display/redirect, HUDSON_HOME=/Users/vivek/.jenkins, RUN_CHANGES_DISPLAY_URL=http://localhost:8080/job/TestPipeline/3/display/redirect?page=changes, JOB_URL=http://localhost:8080/job/TestPipeline/, HUDSON_COOKIE=5025009f-f7c2-41cc-8a7c-f1f0a8ab9f8f, JENKINS_NODE_COOKIE=4793804e-f603-47f1-8b06-efc3c8f8cb39, ANDROID_HOME=/Users/vivek/Library/Android/sdk, JENKINS_SERVER_COOKIE=durable-2a8157f9f0560ed35711400bd6512597, LOGNAME=vivek, RUN_TESTS_DISPLAY_URL=http://localhost:8080/job/TestPipeline/3/display/redirect?page=tests, PWD=/Users/vivek/.jenkins/workspace/TestPipeline, JENKINS_URL=http://localhost:8080/, JAVA_MAIN_CLASS_434=Main, BUILD_TAG=jenkins-TestPipeline-3, SHELL=/bin/zsh, STAGE_NAME=run automation with params for patient, browsers=ios, JENKINS_HOME=/Users/vivek/.jenkins, TMPDIR=/var/folders/c1/c5nvcncs6nxd_r7x7nsyc9zm0000gp/T/, moduels=diet, NODE_NAME=master, XPC_FLAGS=0x0, BUILD_DISPLAY_NAME=#3, JOB_DISPLAY_URL=http://localhost:8080/job/TestPipeline/display/redirect, __CF_USER_TEXT_ENCODING=0x1F6:0x0:0x0, SHLVL=2, WORKSPACE_TMP=/Users/vivek/.jenkins/workspace/TestPipeline@tmp, JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home, BUILD_ID=3, ANDROID_TOOLS=/Users/vivek/Library/Android/sdk/tools, JOB_NAME=TestPipeline, ANDROID_PLATFORM_TOOLS=/Users/vivek/Library/Android/sdk/platform-tools, NODE_LABELS=master, HUDSON_URL=http://localhost:8080/, WORKSPACE=/Users/vivek/.jenkins/workspace/TestPipeline, XPC_SERVICE_NAME=0, _=/usr/bin/java, ANDROID_BUILD_TOOLS=/Users/vivek/Library/Android/sdk/build-tools/29.0.2, alias emulator=emulator -avd pixel_3a, EXECUTOR_NUMBER=0, HUDSON_SERVER_COOKIE=5dc6f37c67322e25, JOB_BASE_NAME=TestPipeline, USER=vivek, ENV_SIMUTILS=/usr/local/bin/applesimutils, SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.ZOpTPRNval/Listeners, BUILD_NUMBER=3, BUILD_URL=http://localhost:8080/job/TestPipeline/3/, JAVA_MAIN_CLASS_46060=com.testninja.selenium.TestEntry, RUN_ARTIFACTS_DISPLAY_URL=http://localhost:8080/job/TestPipeline/3/display/redirect?page=artifacts, HOME=/Users/vivek, androidBranch=develop}
````

**Comment by viveksoundar** [comment]
@mykola-mokhnach The problem is with my jenkins. It missed the PATH variable ```/usr/local/bin``` After adding it, that works fine. 
Thanks for your time.
