### ISSUE TITLE
PickerWheel Automation iOS 14.1

### ISSUE THREAD

**Issue by nabil-kh-hub** [appium/appium#15458]
## The problem
After the new update from iOS 13.5 to iOS 14.1, the display of the calendar is changed in another format. I tried to automate a test that should select a date from the calendar but it's not working. Any idea, please?

## Environment
* Appium version (or git revision) that exhibits the issue: 1.21
* Last iOS version that did not exhibit the issue : 13.5
* Mobile platform/version under test: iOS 14.1

## Details
![image](https://user-images.githubusercontent.com/84051460/120515028-cb32a680-c3c5-11eb-9afc-551829bbcd9a.png)
![image](https://user-images.githubusercontent.com/84051460/120515044-d08ff100-c3c5-11eb-8677-c4a6220e97ac.png)

## Link to Appium logs
Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]
`driver.findElementByAccessibilityId(this.expiryDate).click();
            driver.findElementByAccessibilityId("Date Picker").click();
            driver.findElementByAccessibilityId("Show year picker").click();
            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
            Date date = (Date)formatter.parse(expiryDate);
            formatter = new SimpleDateFormat("MMMM");
            String month = formatter.format(date);
            formatter = new SimpleDateFormat("dd");
            String day = formatter.format(date);
            formatter = new SimpleDateFormat("yyyy");
            String year = formatter.format(date);
            List<MobileElement> els1 = driver.findElementsByClassName("XCUIElementTypePickerWheel");
           els1.get(0).sendKeys(month);
            els1.get(1).sendKeys(day);
            els1.get(2).sendKeys(year);`

**Comment by mykola-mokhnach** [comment]
The picker wheel interaction behaviour depends on XCTest. Unfortunately there is noting more we could do from Appium side

Kindly use Appium forum to ask questions
