### ISSUE TITLE
Unable to move past input fields on Android 9

### ISSUE THREAD

**Issue by sergius325** [appium/appium#15464]
## The problem
While using the driver.pressKeyCode in order to move around the app; if the focus lands on an input field, driver.pressKeyCode commands won't do anything anymore. There is no error message or log shown, code is executed further to the next steps, as if the pressDown or pressUp was executed, but not on the emulator or device.
The Issue appears only when using Android 9. Worked fine on previous versions.
I am Testing a TV app and need to simulate a remote control.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium version: 1.20.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): Node.js 12.8.1
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator: Android Emulator OS 9.0
* Appium CLI or Appium.app|exe:

**Comment by mykola-mokhnach** [comment]
This endpoint simply triggers the downstream Android event. The actual reaction on this system event is then up to the application under test. Which means there is nothing we could do about it from Appium side. Read https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/actions.md for details on this topic.

You could also add more debug logging to the the app itself and check the logcat output to get more details.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
