### ISSUE TITLE
Intermittent NoSuchElementException at AppiumElementLocator.java:126

### ISSUE THREAD

**Issue by yavgel** [appium/appium#15469]
Having intermittent `org.openqa.selenium.NoSuchElementException at AppiumElementLocator.java:126`

![image](https://user-images.githubusercontent.com/8123409/121009873-f5ed7800-c794-11eb-950e-d48f452290a3.png)

Appium version `1.21.0`

Logs are attached:

[Terminal Saved Output.txt](https://github.com/appium/appium/files/6608474/Terminal.Saved.Output.txt)

**Comment by mykola-mokhnach** [comment]
Please fill out the issue report properly and describe the actual steps, result, and the expected result. Also, it is impossible to find anything in the 20MB log file. Please locate where the issue is and only attach that part.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
