### ISSUE TITLE
Unable to Scroll in UWP app

### ISSUE THREAD

**Issue by krevathi1912** [appium/appium#15466]
I am automating UWP app using appium+winappdriver
Winappdirver version - 1.2 RC

Our app has a page, where certain elements will be loaded only on scrolling down the page. There is a vertical scroll bar element, but it is getting enabled only when mouse cursor is moved over it. I am unable to scroll in the UWP app, Please let me know how to handle scrolling in this case. I am using python language

## Environment

* Appium version : v1.21.0
* Desktop OS/version used to run Appium: Windows 1-
* Node.js version (unless using Appium.app|exe): v12.16.2
* Npm or Yarn package manager:  6.14.4
* Mobile platform/version under test: UWP application
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: Appim CLI

![image](https://user-images.githubusercontent.com/61457037/120912692-0b5c8800-c657-11eb-939b-af31e2b9fba6.png)

**Comment by KazuCocoa** [comment]
It seems https://github.com/microsoft/WinAppDriver is a proper place to report
