### ISSUE TITLE
Impossible to retrieve invisible element even with allowInvisibleElements

### ISSUE THREAD

**Issue by DvorahC** [appium/appium#15460]
## The problem

Hi,

I have read several answers and also the ticket 15368.
But I cannot manage to resolve my issue.
In the app, some elements are set to invisible and then become visible (when we click on another button then 2 buttons appear).
But I cannot see them in Appium desktop.

**Here are all the things I tried without success:**
- Use the allowInvisibleElements. And set it to true + getPageSource 
- Make a scroll
- refresh the page

Below are more info and also the code of the buttons. I am really stuck and would appreciate some help in this. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.18.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS Catalina 10,.15.7
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager: 6.14.8
* Mobile platform/version under test: Android 9
* Real device or emulator/simulator: Real device and Emulator 
* Appium CLI or Appium.app|exe: APPIUM CLI

## Details

I a working with the Android developers and we are trying to see how to solve this issue.
Here is the code of their UI elements just to show you :
the button I am searching is btnResumeRecording 

```
<androidx.constraintlayout.widget.ConstraintLayout
        android:layout_width="wrap_content"
        android:layout_height="85dp"
        android:layout_gravity="center_horizontal"
        android:id="@+id/rootRecordButton">


        <include
            android:visibility="invisible"
            android:id="@+id/btnResumeRecording"
            layout="@layout/record_button_btn_resume"
            android:layout_width="@dimen/record_btn_size"
            android:layout_height="@dimen/record_btn_size"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="@+id/imgRecordingInMap" />

```

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
The page source is basically a reflection of what UiAutomator framework was able to fetch from the Accessibility manager. If elements are not accessible then there is no change one could see them in the page source.

**Comment by DvorahC** [comment]
@mykola-mokhnach thanks a lot ! but how can I see them in the app and not get them from the PageSource ? I need to click on those buttons and I am figuring out how to do it. 
Is there something on the side of the developers that could help? Something they can do with those invisible buttons? thanks for the advice

**Comment by mykola-mokhnach** [comment]
> Is there something on the side of the developers that could help? Something they can do with those invisible buttons? thanks for the advice

Yes, they probably could. Refer to https://developer.android.com/guide/topics/ui/accessibility

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
