### ISSUE TITLE
Device gets disconnect from adb when session is started

### ISSUE THREAD

**Issue by GnubiBORED** [appium/appium#15467]
## The problem

Everytime i try to connect my device ( nox player emulator) to appium and start a session it gets disconnected from

## Environment

* Appium version (or git revision) that exhibits the issue:1.21.0 Appium Desktop
* Mobile platform/version under test: Windows 10
* Real device or emulator/simulator: Android 7.1.2
* Node.js: 12.8.1
* Electron:7.2.4

* Appium CLI or Appium.app|exe: .exe

## Details

I tried from appium desktop UI to start the session and also from python with python appium client, none worked.

## Link to Appium logs

logs : [GIST](https://gist.github.com/GnubiBORED/dda293523d602f30093449855742f7fd) 

## Code To Reproduce Issue [ Good To Have ]

Capabilities from Apium desktop:
`{
  "app": "C:\\Users\\qwert\\Downloads\\Test\\tribalwars.apk",
  "platformName": "Android",
  "platformVersion": "7.1.2"
}`

From python: 
```

import unittest

from appium import webdriver
from applitools.selenium import Eyes

class HelloWorld:

    # Initialize the eyes SDK and set your private API key.
    eyes = Eyes()
    eyes.api_key = 'MY_API_KEY'

    # Desired capabilities.
    desired_caps = dict(
        platformName = 'Android',
        deviceName = 'SM-N950N',
        platformVersion= '7.1.2',
        automationName= 'UiAutomator2',
        app='https://applitools.jfrog.io/artifactory/Examples/eyes-hello-world.apk')

    # Open the app.
    wd = webdriver.Remote('http://127.0.0.1:4723/wd/hub', desired_caps)
    wd.implicitly_wait(60)

    try:

        # Start the test.
        eyes.open(driver=wd, app_name='Contacts', test_name='My first Appium native Python test!')

        # Visual UI testing.
        eyes.check_window('Contact list!')

        # End the test.
        eyes.close()

    finally:

        # Close the app.
        wd.quit()

        # If the test was aborted before eyes.close was called, ends the test as aborted.
        eyes.abort_if_not_closed()




```

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing that could be done from Appium side. Make sure the developer mode is enabled in device settings and its identifier is listed as online in `adb devices -l` output. Otherwise Appium won't be able to run any tests.

**Comment by GnubiBORED** [comment]
Thanks for the response @mykola-mokhnach maybe i was missing something 

When i run adb devices -l i got this
`C:\Users\qwert\AppData\Local\Android\Sdk\platform-tools>adb devices -l
List of devices attached
127.0.0.1:62001        device product:d2que model:SM_N976N device:d2q transport_id:1


C:\Users\qwert\AppData\Local\Android\Sdk\platform-tools>
`

identifier is model? or im missing something?

**Comment by mykola-mokhnach** [comment]
I would try `suppressKillServer` capability if the device is connected wirelessly. Otherwise there is not much to do from the server side.
