### ISSUE TITLE
Got "connect ECONNREFUSED 127.0.0.1:8202" error when parallel run tests on android simulator

### ISSUE THREAD

**Issue by alhu0470** [appium/appium#15461]
## The problem
I run tests on 3 android simulators parallelly, and start an appium instance for every case, i.e. I start an appium server at different port, and kill the server when the case is over.
The problem is, for some case (i encountered this problem about 8 times out of 98 cases), i run into "connect ECONNREFUSED 127.0.0.1:820x" problem when appium is trying to connect to android emulator. I use different "systemPort" for the emulators.
I checked the logcat, seems it does not receive the cmd send from appium on port 6790. 
I attached the appium log and related logcat. 
[logcat_emulator_5556_test_search_no_match_06-03-10-22-04.txt](https://github.com/appium/appium/files/6589651/logcat_emulator_5556_test_search_no_match_06-03-10-22-04.txt)
[appiumlog_emulator_5556_test_search_no_match_06-03-10-22-04.txt](https://github.com/appium/appium/files/6589653/appiumlog_emulator_5556_test_search_no_match_06-03-10-22-04.txt)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MAC 11.2.3 (big sur)
* Node.js version (unless using Appium.app|exe): 16.0.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: android 10 emulator
* Real device or emulator/simulator: emulator, created with android studio
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Pls refer to problem description

## Link to Appium logs

https://gist.github.com/alhu0470/6dae8a4b28025c703c74f05668e93e28

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Try to update the server to the most recent version

**Comment by alhu0470** [comment]
> Try to update the server to the most recent version

Thanks for your reply, but what do you mean by "server"? I see the appium is installing uiautomator on the device.

**Comment by mykola-mokhnach** [comment]
I mean Appium server

**Comment by alhu0470** [comment]
I upgrade the appium 2.0.0-beta.12, but still got problem.
new appium log: https://gist.github.com/alhu0470/5c5e8c18ef9670384f99b5ee20ea846a
new logcat log: https://gist.github.com/alhu0470/093f675096ce6034b4f8bf08b5088016
I added a try catch when craete driver, i found some times it can success after i restart appium.

**Comment by mykola-mokhnach** [comment]
> 06-02 19:30:04.941 W/AdbDebuggingManager( 2052): Read failed with count -1
> 06-02 19:30:04.941 E/AdbDebuggingManager( 2052): Caught an exception opening the socket: java.io.IOException: Connection refused
> --------- beginning of crash
> 06-02 19:30:05.330 E/AndroidRuntime( 8260): FATAL EXCEPTION: Instr: androidx.test.runner.AndroidJUnitRunner
> 06-02 19:30:05.330 E/AndroidRuntime( 8260): Process: io.appium.uiautomator2.server, PID: 8260
> 06-02 19:30:05.330 E/AndroidRuntime( 8260): java.lang.IllegalStateException: Cannot call disconnect() while connecting!
> 06-02 19:30:05.330 E/AndroidRuntime( 8260): 	at android.app.UiAutomation.disconnect(UiAutomation.java:291)
> 06-02 19:30:05.330 E/AndroidRuntime( 8260): 	at android.app.Instrumentation.finish(Instrumentation.java:248)
> 06-02 19:30:05.330 E/AndroidRuntime( 8260): 	at androidx.test.runner.MonitoringInstrumentation.finish(MonitoringInstrumentation.java:367)
> 06-02 19:30:05.330 E/AndroidRuntime( 8260): 	at androidx.test.runner.AndroidJUnitRunner.finish(AndroidJUnitRunner.java:415)
> 06-02 19:30:05.330 E/AndroidRuntime( 8260): 	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:404)
> 06-02 19:30:05.330 E/AndroidRuntime( 8260): 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)
> 06-02 19:30:05.336 I/DropBoxManagerService( 2052): add tag=data_app_crash isTagEnabled=true flags=0x2
> 06-02 19:30:05.344 W/BroadcastQueue( 2052): Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
> 06-02 19:30:05.344 W/BroadcastQueue( 2052): Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
> 06-02 19:30:05.401 I/ActivityManager( 2052): Process io.appium.uiautomator2.server (pid 8260) has died: fore FGS 
> 06-02 19:30:05.404 W/ActivityManager( 2052): Crash of app io.appium.uiautomator2.server running instrumentation ComponentInfo{io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner}
> 06-02 19:30:05.404 I/ActivityManager( 2052): Force stopping io.appium.uiautomator2.server appid=10138 user=0: finished inst

The error is coming from UiAutomator itself. I would try to change the device under test as a possible workaround.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
