### ISSUE TITLE
Not able to connect iOS real device to Appium

### ISSUE THREAD

**Issue by chethanshetty09** [appium/appium#15468]
## The problem

am trying to make real iOS device work with appium. Xcode build is successful when building from Xcode. After adding capabilities to appium and initiating the session, getting below errors. The same set up works as expected with simulator. it successfully installs WDA on simulator but unable to install the same on real iOS device.

## Environment

Xcode: 12.5 beta
Appium:1.19.1
iOS device: 14.4.2

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Appium logs gist file [here](https://gist.github.com/chethanshetty09/9f138286afa87948b3bb60709044bb1e)

**Comment by KazuCocoa** [comment]
Please try out 1.21.0 for Xcode 12.5. https://github.com/appium/appium/releases/tag/v1.21.0

Your log had no `xcodeOrgId`. What org id did you use?
https://appium.io/docs/en/drivers/ios-xcuitest-real-devices/

**Comment by mykola-mokhnach** [comment]
Closed because of no response
