### ISSUE TITLE
"Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: A new session could not be created. Details: session not created: This version of ChromeDriver only supports Chrome version 91 "message displays upon trying to run my Android test case

### ISSUE THREAD

**Issue by khaled9190** [appium/appium#15463]
## The problem

I Can't run my android test case using eclipse as incompatible chrome browser and Chromedriver still displays .

My Chrome version on my device is 90. and Chromedriver is 91 How I can resolve this issue by code without upgrade Chromedriver or Chrome browser 

## Environment

* Appium version: Appium v1.21.0
* Desktop OS/version used to run Appium: Windows 10 Pro
* Mobile platform/version under test: I tried both on simulator and on my Note 7 (Android 9)
* Real device or emulator/simulator: On both

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

[debug] [W3C]     at AppiumDriver.createSession (C:\Users\kibrahim\AppData\Roaming\npm\node_modules\appium\lib\appium.js:387:35)
[HTTP] <-- POST /wd/hub/session 500 35992 ms - 977
[HTTP]
[debug] [Instrumentation] Time: 17.399
[debug] [Instrumentation]
[debug] [Instrumentation] OK (1 test)
[debug] [Instrumentation] The process has exited with code 0

## Code To Reproduce Issue [ Good To Have ]

package appiumBasics;

import java.net.MalformedURLException;

import java.net.URL;

import org.openqa.selenium.By;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.annotations.Test;

import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.remote.MobileCapabilityType;
import io.github.bonigarcia.wdm.WebDriverManager;

public class RunWebApplicationAndroidEmulator {

	
	@Test
	public void OpenWebApplication() throws MalformedURLException {
		
		DesiredCapabilities caps = new DesiredCapabilities();
		caps.setCapability(MobileCapabilityType.BROWSER_NAME, "chrome");
		caps.setCapability(MobileCapabilityType.DEVICE_NAME,"KhaledEmulator");
		
		
		WebDriverManager.chromedriver().setup();
		
		caps.setCapability("chromedriverExecutable",WebDriverManager.chromedriver().getBinaryPath());
		
		
		
	//	System.setProperty("webdriver.chrome.driver", "path/to/downloaded/driver");
		//ChromeOptions chromeOptions = new ChromeOptions();
	
		
		AndroidDriver driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"),caps);
		driver.get("https://google.com");
		String title=driver.getTitle();
		System.out.println(title);
		driver.findElement(By.name(title)).sendKeys("amman");
		
		
		//http://localhost:4723/wd/hub
		//http://127.0.0.1:4723/wd/hub
	}
}

**Comment by Dharin-shah** [comment]
@khaled9190 may i know why cant you try downgrading your [chromedriver](https://chromedriver.storage.googleapis.com/index.html?path=90.0.4430.24/) ?

**Comment by mykola-mokhnach** [comment]
This is Google's requirement that chromedriver version must match to the version of the browser under test. The error is expected unless a proper chromedriver is provided as described in https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md

**Comment by khaled9190** [comment]
Because I think my code will update the ChromeDriver to the latest version  

WebDriverManager.chromedriver().setup();
	
caps.setCapability("chromedriverExecutable",WebDriverManager.chromedriver().getBinaryPath());

and every time a new chrome version and Chrome driver will install 


should I change anything on my code?

**Comment by Dharin-shah** [comment]
can try and set a path by 
```
System.setProperty("webdriver.chrome.driver", "/path/to/chromedriver90");
```
also can  raise a bug here, not an issue with appium
https://github.com/bonigarcia/webdrivermanager

**Comment by khaled9190** [comment]
Thank you but can you please show me exactly in my code and If I should delete any thing

Thanks

**Comment by mykola-mokhnach** [comment]
Kindly use Appium forum to ask questions. Here we only track server issues.

Closed as not an issue

**Comment by khaled9190** [comment]
Can you just give me the link for forum as I can't find

Thanks

**Comment by Dharin-shah** [comment]
with appium you have to start the server with chrome driver ike this
```
appium --chromedriver-executable /path/to/my/chromedriver
```

and remove these lines
```
WebDriverManager.chromedriver().setup();
	
	caps.setCapability("chromedriverExecutable",WebDriverManager.chromedriver().getBinaryPath());
	
	
	
//	System.setProperty("webdriver.chrome.driver", "path/to/downloaded/driver");
	//ChromeOptions chromeOptions = new ChromeOptions();
```

should work. Please use [this](https://discuss.appium.io/) for further discussions
