### ISSUE TITLE
Android - Window 10 :- Which android emulator is working for running Appium test case in java

### ISSUE THREAD

**Issue by cmehta-api** [appium/appium#15474]
## The problem

Hi ,

I tried few emulators like G Pixel 3/4 with version 8/9/10/11 android versions but its automatically killed after launch. Its blocking test execution. Would you some one please advise which emulators are more stable. Thanks

## Environment

* Appium version - 1.18.3
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Window 10 /64 Bit
* Node.js version (unless using Appium.app|exe): v14.15.0
* Npm or Yarn package manager: 6.14.8
* Mobile platform/version under test: Google Pixel   3/4/5  and version 8/9/10 etc
* Real device or emulator/simulator:NA
* Appium CLI or Appium.app|exe: NA

## Details

Emulator getting crash in below scenarios 

1.  As soon as launch the emulator then after few second getting crash  , tries G Nexus all version , G Pixel all version
2.  Emulator crashing during executions as well 
3. Most the time Emulator getting hanged 

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by cmehta-api** [comment]
[emulator.docx](https://github.com/appium/appium/files/6614978/emulator.docx)
please see attached screens

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
