### ISSUE TITLE
Appium bounds not calculated correctly (and differ from correct bounds reported by Flipper)

### ISSUE THREAD

**Issue by haveneersrobin** [appium/appium#15470]
## The problem

The bounds reported for one of our android ViewGroups are not correct. The bounding rectangle is not tall enough which makes our automated tests fail (error: `Error: InvalidArgumentException: Message: Coordinate [x=..,y=..] is outside of elemet rect`). If we compare the bounds to those reported by Flipper (it is a React Native application) we see that, not only are they different (which could be a result of a different choice of units) but Flipper reports the correct bounds. We believe this could have something to do with the display size/font size

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: macOS BigSur 11.4
* Node.js version (unless using Appium.app|exe): 12.8.1
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Oneplus 7, Android 11
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium App

I don't think logs are applicable here?

### Appium Screenshot
![Screenshot 2021-06-07 at 13 51 13](https://user-images.githubusercontent.com/7559898/121013123-be80ca80-c798-11eb-9bc3-4c9a287a9c5d.png)

### Flipper Screenshot
![Screenshot 2021-06-07 at 13 59 50](https://user-images.githubusercontent.com/7559898/121013130-c04a8e00-c798-11eb-9221-6f88235076a9.png)

**Comment by mykola-mokhnach** [comment]
I assume this is expected. Appium simply reflects what the app itself provides to the Accessibility manager. And the inspector below has access to the internal app views hierarchy. In such case it would be more logical to compare its output to the page source generated by Espresso rather than UI2 driver.

**Comment by haveneersrobin** [comment]
@mykola-mokhnach Hmm, I am not that experienced with Appium and its working but when I use TalkBack on my phone (which probably uses the accessibility manager under the hood) the regions are correctly identified...

> I assume this is expected. Appium simply reflects what the app itself provides to the Accessibility manager. And the inspector below (Flipper) has access to the internal app views hierarchy. In such case it would be more logical to compare its output to the page source generated by Espresso rather than UIA2 driver.

**Comment by mykola-mokhnach** [comment]
You could try the native [uiautomatorviewer](https://developer.android.com/training/testing/ui-automator) tool to check what is actually provided to the accessibility manager there. 

Also UIA2 driver provides [simpleBoundsCalculation](https://github.com/appium/appium-uiautomator2-driver#settings-api) setting, which might affect bounds calculation.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
