### ISSUE TITLE
update READMEs for each package in monorepo

### ISSUE THREAD

**Issue by boneskull** [appium/appium#15478]
Repos folded into this repo (2.0 branch) should have READMEs pointed at _this_ repo, then they should be transferred to the archive org as per @jlipps.

Question: given that there may be updates to, e.g., the 1.x-compatible lines of packages for `appium-base-driver` and/or `appium-fake-driver`, should we leave those for now?

**Comment by jlipps** [comment]
> Question: given that there may be updates to, e.g., the 1.x-compatible lines of packages for appium-base-driver and/or appium-fake-driver, should we leave those for now?

I think we should probably leave them for now but put a big deprecation notice plus a link to the new repo/branch so at least people coming to those repos know something is up?
