### ISSUE TITLE
Could not proxy command to the remote server. Original error: socket hang up

### ISSUE THREAD

**Issue by youngfreeFJS** [appium/appium#15479]
## The problem

`WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to the remote server. Original error: socket hang up
`

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 10.15
* Node.js version (unless using Appium.app|exe): v14
* Npm or Yarn package manager:
* Mobile platform/version under test: iPhone11(13.5)
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

https://gist.github.com/youngfreeFJS/2e5ee01ac2433806afb05c630bb265f7

**Comment by mykola-mokhnach** [comment]
I observe some mess in the attached log - the session request must be sent after WDA is successfully initialised. This looks rather as an issue on the client side.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
