### ISSUE TITLE
Application in the iOS Simulator got stuck/frozen

### ISSUE THREAD

**Issue by branko501** [appium/appium#15484]
## The problem

I am running automated tests and application works normally without Appium inside simulator. When I run the tests and init Appium with webdriveragent application got stuck on the same screen every time. Stuck is unusual, there are two buttons on screen. Skip button is not working, not automatically nor by the script. But other button works normally. Skip button does not work even when script is killed and I try to click it manually in Simulator.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Latest MacOS (not M1)
* Node.js version (unless using Appium.app|exe): v16.2.0
* Npm or Yarn package manager: nom
* Mobile platform/version under test: iOS 14.2
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: appium cli

**Comment by jlipps** [comment]
I would look in the system logs for any kind of crash event or simulator problem.

**Comment by branko501** [comment]
> I would look in the system logs for any kind of crash event or simulator problem.

Thank you for your help. If I build the application with Xcode it works just fine. I guess there is something wrong with xcodebuild command line build. So I will close the issue.

**Comment by jlipps** [comment]
Glad to hear you got it to work by building via Xcode! Probably some CLI option for xcodebuild could be tweaked to make things work the same.

**Comment by branko501** [comment]
Do you maybe have any direction? I have tried adding -sdk iphonesimulator14.2 but the build fails as there is also watch extensions...

       xcodebuild \
        -workspace "${WORKSPACE}" \
        -scheme "${SCHEME}" \
        -configuration "${CONFIGURATION}" \
        -derivedDataPath "${NBS_DERIVED_DATA_PATH}" \
        -destination "${DESTINATION}" \
        clean build | tee "${NBS_XCODEBUILDLOG_PATH}" | xcpretty

**Comment by jlipps** [comment]
I'm sorry, I don't know. I would see if there's a way to get the xcodebuild command that xcode itself is running.
