### ISSUE TITLE
Original error: Could not proxy command to the remote server. Original error: socket hang up

### ISSUE THREAD

**Issue by Miyaa95** [appium/appium#15483]
## The problem

I start a session on appium and this is the error message I see - **An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up**
## Environment

* Appium version (or git revision) that exhibits the issue: **Appium Version - 1.20.2**
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS
* Mobile platform/version under test: **Android , Platform version - 11**
* Real device or emulator/simulator: **Simulator Pixel_3a_API_30_x86**

**Comment by Miyaa95** [comment]
[appium-server-logs.txt](https://github.com/appium/appium/files/6633693/appium-server-logs.txt)

**Comment by Miyaa95** [comment]
@mykola-mokhnach Is there any way I can do this without command line and through the Appium app?

**Comment by mykola-mokhnach** [comment]
Appium app is just a UI wrapper over the command line interface. Kindly use Appium forum if you have more questions about how to use it.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
