### ISSUE TITLE
io.appium.uiautomator2.server.test has no version

### ISSUE THREAD

**Issue by sshock** [appium/appium#15486]
## The problem

The `io.appium.uiautomator2.server.test` apk has no versionName or versionCode.  They are both empty as revealed by `aapt dump badging` or `apktool` or `dumpsys package` or whatever you like to use.

This is a problem because it makes it impossible for me to know if the version of that APK that is installed is the right one.

I want to use `skipServerInstallation` and it is my understanding that in order for appium to work with that flag, I need to have both `io.appium.uiautomator2.server` and `io.appium.uiautomator2.server.test` installed beforehand.

The `io.appium.uiautomator2.server` has a version and I can easily check what version is on the device and compare it to what version I want on the device and then install iff it is missing or the version is wrong.

But since `io.appium.uiautomator2.server.test` has no version, I'll have no idea with a given random device whether or not it has the right server.test on there so I'll have no idea if I need to install it or not.

**Comment by jlipps** [comment]
Interesting, we can see if it's possible to add this. Sounds straightforward.

**Comment by KazuCocoa** [comment]
I wonder to add a custom manifest for androidTest, but maybe cannot? 
https://stackoverflow.com/questions/26244998/androidmanifest-in-androidtest-directory-being-ignored

Perhaps what we can do is to replace the initial manifest with new one, added versionName and versionCode, via apksigner etc? (I don't know this works, so need to check first)

**Comment by mykola-mokhnach** [comment]
I don't think it is possible to add versioning info into test packages. This is a limitation from Google and only Google is able to change that. Please reopen this issue if someone could propose a viable workaround/solution
