### ISSUE TITLE
driver.background_app crashes WDA

### ISSUE THREAD

**Issue by WilfulTravesty** [appium/appium#15485]
## The problem

Calling driver.background_app({"timeout": None}) when the app is foreground crashes WDA about 50% of the time

## Environment

* Appium version (or git revision) that exhibits the issue: 1.19.1
* Last Appium version that did not exhibit the issue (if applicable): ??
* Desktop OS/version used to run Appium: MacOS Catalina 10.15.7
* Node.js version (unless using Appium.app|exe): N/A
* Npm or Yarn package manager: 
* Mobile platform/version under test: iOS 12.1.4
* Real device or emulator/simulator: iPhone SE
* Appium CLI or Appium.app|exe: 

## Details

Calling driver.background_app({"timeout": None}) crashes WDA about 50% of the time, as shown in the short Appium log below. The find element command immediately before this command was successful.

## Link to Appium logs

[HTTP] --> POST /wd/hub/session/1007dad5-20b7-4c69-9f2e-7dbc0b34e3c6/appium/app/background
[HTTP] {"seconds":{"timeout":null}}
[W3C (1007dad5)] Calling AppiumDriver.background() with args: [{"timeout":null},"1007dad5-20b7-4c69-9f2e-7dbc0b34e3c6"]
[XCUITest] Executing command 'background'
[XCUITest] Proxying to WDA with an unknown route: POST /wda/homescreen
[XCUITest] Setting custom timeout to 33000 ms for 'Unknown' command
[WD Proxy] Proxying [POST /wda/homescreen] to [POST http://localhost:8104/wda/homescreen] with body: {}
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8104
[W3C (1007dad5)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: connect ECONNREFUSED 127.0.0.1:8104
[W3C (1007dad5)]     at NoSessionProxy.command (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:275:13)
[W3C (1007dad5)]     at runMicrotasks ()
[W3C (1007dad5)]     at processTicksAndRejections (internal/process/task_queues.js:85:5)
[HTTP] <-- POST /wd/hub/session/1007dad5-20b7-4c69-9f2e-7dbc0b34e3c6/appium/app/background 500 5 ms

**Comment by jlipps** [comment]
What does the iOS system log say about the crash?

**Comment by mykola-mokhnach** [comment]
Please make sure you use the most recent server version

**Comment by mykola-mokhnach** [comment]
Closed because of no response
