### ISSUE TITLE
Socket hangup issue with appium using iOS

### ISSUE THREAD

**Issue by ckumar28582** [appium/appium#15499]
## The problem
Im observing an Error socket hang up issue with Econnreset.  My custom app  needs to connect to the external WiFi router. Once the app i connected external router we additionally check  whether its really connected to specific router. So in this 
case we access IPAD wifi settings to confirm the my custom app is connected with intended router . So we initially launch the custom app and then we access the IPAD wifi settings. After this step we need to access the custom app again for further testing.
so when we relaunch the custom app, socket hang up is observed. 

## Environment
appium 1.17.1.
MAC OS : catalina 10.5
iPAD  ver : 13.5.1
Real Device

## Link to Appium logs
[appium-server-logs.txt](https://github.com/appium/appium/files/6642509/appium-server-logs.txt)

## Code To Reproduce Issue [ Good To Have ]
def activate_iPad_WiFiSettings(self):
        try:
            print("activate_iPad_WiFiSettings")
            logging.info("activate_iPad_WiFiSettings")
            time.sleep(1)
            self.desired_caps["bundleId"] = 'com.apple.Preferences'
            self.driver.execute_script('mobile: activateApp', self.desired_caps);
            time.sleep(1)
        except WebDriverException:
            time.sleep(0.5)            
            self.kill_ipad_wifi_settings()
Below function called after the execution of the above  one. Then i see the issue
 def activate_sms_app(self):
        try:
            retry_cnt=0
            time.sleep(1)
            print("activate_sms_app")
            logging.info("Activate SMS App")
            self.desired_caps["bundleId"] = self.data['app_details']['bundleId']
            self.driver.execute_script('mobile: activateApp', self.desired_caps);
            time.sleep(1)            
        except WebDriverException:
            self.sms_kill_ios_app()

**Comment by mykola-mokhnach** [comment]
Appium 1.17 is out of date. Please upgrade to the most recent version.

Do you happen to change network settings during the test?

**Comment by ckumar28582** [comment]
> Appium 1.17 is out of date. Please upgrade to the most recent version.
> 
> Do you happen to change network settings during the test?

**Comment by ckumar28582** [comment]
Hi,
I will update appium and verify the issue.
 Yes I need to access wifi settings.The reason here looks like the iOS doesnt allow to access wifi settings from the custom app. So we access the iPad wifi settings explicitly. 

Can you confirm that socket hang up issue is there appium 1..17. 

Actually hang issue observed when we use to bring the required app to foreground ,using any appium command activate_app or launch_app or  background

**Comment by mykola-mokhnach** [comment]
> Yes I need to access wifi settings.The reason here looks like the iOS doesnt allow to access wifi settings from the custom app. So we access the iPad wifi settings explicitly.

Most likely the issue happens due to that. Changing of network settings on the device causes xctest disconnection from the host. As a possible workaround you might try to start a new test session after the change is done. Otherwise there is nothing we could do about it.

**Comment by ckumar28582** [comment]
Hi,
Thank you. Let me be little more clear. Here is my test flow
 1.open custom app with desired capabilities
2.do necessary actions and try to connect to wifi.
3.To connect to wifi network we call activate_app with bundle id of apple settings
4.connect to network from wifi settings
5.kill the wifi settings
6.come back to custom app using activate_app 
7.here on my custom app screen comes up as expected and it fails to identify object. Because socket hang up issue observed.

As you said if I have to handle with some work around in different session. How can this be achieved. 

As of now all these test flow happens on single real device in one appium session.

**Comment by mykola-mokhnach** [comment]
> connect to network from wifi settings

After this step the test is already dead no matter what. xctest requires the connection to be stable and always available, it does not reconnect automatically. I would try to start a new session without an explicit app here and then activate one if possible.

Kindly use Appium forum to ask questions

**Comment by ckumar28582** [comment]
Thank you.I will post it on forum.

Actually I missed one thing to state. Apologies for that. One last help before I post it on forum
My custom app initially uses the network its connected with and fetches some data from the server and displays.Now after accesing some objects on different screen then again I need to change my network. Means initially app connected with router1 and middle of the test need to connect to router2 .
Whether this can be achieved in a single session. Because my app and wifi settings are handled in one session. If I have to do it in different session on single device .Not sure how this can be done.

This socket hang up occurs 50% time.

**Comment by mykola-mokhnach** [comment]
> Whether this can be achieved in a single session. Because my app and wifi settings are handled in one session. If I have to do it in different session on single device .Not sure how this can be done.

I don't think this could be achieved in scope of a single session. At least it would be impossible to make it stable

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by Hamzastreamwide** [comment]
i have the same issue as u , before it was working fine , after upgrading to beta version i encountred this issue
