### ISSUE TITLE
Amazon AWS : ios devices are unable to install WDA, when running code on AWS devices.

### ISSUE THREAD

**Issue by NavpreetD** [appium/appium#15501]
## The problem

Amazon AWS : ios devices are unable to install WDA, when running code on AWS devices.
## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details
I have started using amazon AWS and running android scripts on AWS device farm. 
Following the steps mentioned on AWS device farm website i am able to achieve the test automation for Android devices.
I am unable to run automation scripts on iOS devices, using the same script as i am using on Android devices.
No special instructions are mentioned on AWS website for ios devices.

* WDA is not installing on the iOS devices. Not sure if that installs on the AWS devices and we are able to see in the videos.
* Here is the .yml file that i am using. 

 yml file : 
`version: 0.1

# Phases are collection of commands that get executed on Device Farm.
phases:
  # The install phase includes commands that install dependencies that your tests use.
  # Default dependencies for testing frameworks supported on Device Farm are already installed.
  install:
    commands:
      # This test execution environment uses Appium version 1.9.1 by default, however we enable you to change it using the Appium version manager (avm)
      # An example "avm" command below changes the version to 1.19.0
      # For your convenience, we have pre-installed the following Appium versions: 1.9.1, 1.10.1, 1.11.1, 1.12.1, 1.13.0, 1.14.1, 1.14.2, 1.15.1, 1.16.0, 1.17.1, 1.18.0, 1.18.1, 1.18.2, 1.18.3, and 1.19.0
      # For iOS Devices on OS version 14.2 and above, please use Appium Version 1.19.0 or higher.
      # For iOS devices on OS version 14.0 and above, please use Appium version 1.18.0 or higher.
      # For iOS devices on OS version 13.4 through 13.7, please use Appium version 1.17.1 or higher.
      # Additionally, for iOS devices on OS version 13.0 through 13.3, please use Appium version 1.16.0 or higher.
      # To use one of these Appium versions, change the version number in the "avm" command below to your desired version:
      - export APPIUM_VERSION=1.19.0
      - avm $APPIUM_VERSION
      - ln -s /usr/local/avm/versions/$APPIUM_VERSION/node_modules/.bin/appium  /usr/local/avm/versions/$APPIUM_VERSION/node_modules/appium/bin/appium.js

      # Device farm provides different pre-built versions of WebDriverAgent, and each is suggested for different versions of Appium:
      # DEVICEFARM_WDA_DERIVED_DATA_PATH_V6: this version is suggested for Appium 1.18.2, 1.18.3, and 1.19.0. V6 is built from the following source code: https://github.com/appium/WebDriverAgent/releases/tag/v2.20.8
      # DEVICEFARM_WDA_DERIVED_DATA_PATH_V5: this version is suggested for Appium 1.18.0 and 1.18.1. V5 is built from the following source code: https://github.com/appium/WebDriverAgent/releases/tag/v2.20.2
      # DEVICEFARM_WDA_DERIVED_DATA_PATH_V4: this version is suggested for Appium 1.17.1. V4 is built from the following source code: https://github.com/appium/WebDriverAgent/releases/tag/v2.14.1
      # DEVICEFARM_WDA_DERIVED_DATA_PATH_V3: this version is suggested for Appium 1.16.0. V3 is built from the following source code: https://github.com/appium/WebDriverAgent/releases/tag/v2.3.2
      # DEVICEFARM_WDA_DERIVED_DATA_PATH_V2: this version is suggested for Appium 1.15.1. V2 is built from the following source code: https://github.com/appium/WebDriverAgent/tree/v1.3.5
      # DEVICEFARM_WDA_DERIVED_DATA_PATH_V1: this version is suggested for Appium 1.9.1 through 1.14.2. V1 is built from the following source code: https://github.com/appium/WebDriverAgent/tree/2dbbf917ec2e4707bae9260f701d43c82b55e1b9
      # We will automatically configure your WebDriverAgent version based on your Appium version using the following code.

      # For users of Appium versions 1.15.0 and higher, your Appium version requires that the UDID of the device not contain any "-" characters
      # So, we will create a new environment variable of the UDID specifically for Appium based on your Appium version
      - >-
        if [ $(echo $APPIUM_VERSION | cut -d "." -f2) -ge 19 ];
        then
          DEVICEFARM_DEVICE_UDID_FOR_APPIUM=$(echo $DEVICEFARM_DEVICE_UDID | tr -d "-");
          DEVICEFARM_WDA_DERIVED_DATA_PATH=$DEVICEFARM_WDA_DERIVED_DATA_PATH_V6;
        elif [ $(echo $APPIUM_VERSION | cut -d "." -f2) -ge 18 ];
        then
          DEVICEFARM_DEVICE_UDID_FOR_APPIUM=$(echo $DEVICEFARM_DEVICE_UDID | tr -d "-");
          DEVICEFARM_WDA_DERIVED_DATA_PATH=$DEVICEFARM_WDA_DERIVED_DATA_PATH_V5;
        elif [ $(echo $APPIUM_VERSION | cut -d "." -f2) -ge 17 ];
        then
          DEVICEFARM_DEVICE_UDID_FOR_APPIUM=$(echo $DEVICEFARM_DEVICE_UDID | tr -d "-");
          DEVICEFARM_WDA_DERIVED_DATA_PATH=$DEVICEFARM_WDA_DERIVED_DATA_PATH_V4;
        elif [ $(echo $APPIUM_VERSION | cut -d "." -f2) -ge 16 ];
        then
          DEVICEFARM_DEVICE_UDID_FOR_APPIUM=$(echo $DEVICEFARM_DEVICE_UDID | tr -d "-");
          DEVICEFARM_WDA_DERIVED_DATA_PATH=$DEVICEFARM_WDA_DERIVED_DATA_PATH_V3;
        elif [ $(echo $APPIUM_VERSION | cut -d "." -f2) -ge 15 ];
        then
          DEVICEFARM_DEVICE_UDID_FOR_APPIUM=$(echo $DEVICEFARM_DEVICE_UDID | tr -d "-");
          DEVICEFARM_WDA_DERIVED_DATA_PATH=$DEVICEFARM_WDA_DERIVED_DATA_PATH_V2;
        else
          DEVICEFARM_DEVICE_UDID_FOR_APPIUM=$DEVICEFARM_DEVICE_UDID;
          DEVICEFARM_WDA_DERIVED_DATA_PATH=$DEVICEFARM_WDA_DERIVED_DATA_PATH_V1;
        fi

  # The pre-test phase includes commands that set up your test environment.
  pre_test:
    commands:
      # Set up environment variables for java
      - export CLASSPATH=$CLASSPATH:$DEVICEFARM_TESTNG_JAR
      - export CLASSPATH=$CLASSPATH:$DEVICEFARM_TEST_PACKAGE_PATH/*
      - export CLASSPATH=$CLASSPATH:$DEVICEFARM_TEST_PACKAGE_PATH/dependency-jars/*
      - adb forward tcp:13000 tcp:13000
      # We recommend starting the appium server process in the background using the command below.
      # Appium server log will go to $DEVICEFARM_LOG_DIR directory.
      # The environment variables below will be auto-populated during run time.
      - echo "Start appium server"
      - >-
        appium --log-timestamp
        --default-capabilities "{\"usePrebuiltWDA\": true, \"derivedDataPath\":\"$DEVICEFARM_WDA_DERIVED_DATA_PATH\",
        \"deviceName\": \"$DEVICEFARM_DEVICE_NAME\", \"platformName\":\"$DEVICEFARM_DEVICE_PLATFORM_NAME\", \"app\":\"$DEVICEFARM_APP_PATH\",
        \"automationName\":\"XCUITest\", \"udid\":\"$DEVICEFARM_DEVICE_UDID_FOR_APPIUM\", \"platformVersion\":\"$DEVICEFARM_DEVICE_OS_VERSION\"}"
        >> $DEVICEFARM_LOG_DIR/appiumlog.txt 2>&1 &

      - >-
        start_appium_timeout=0;
        while [ true ];
        do
            if [ $start_appium_timeout -gt 60 ];
            then
                echo "appium server never started in 60 seconds. Exiting";
                exit 1;
            fi;
            grep -i "Appium REST http interface listener started on 0.0.0.0:4723" $DEVICEFARM_LOG_DIR/appiumlog.txt >> /dev/null 2>&1;
            if [ $? -eq 0 ];
            then
                echo "Appium REST http interface listener started on 0.0.0.0:4723";
                break;
            else
                echo "Waiting for appium server to start. Sleeping for 1 second";
                sleep 1;
                start_appium_timeout=$((start_appium_timeout+1));
            fi;
        done;
  # The test phase includes commands that start your test suite execution.
  test:
    commands:
      # Your test package is downloaded in $DEVICEFARM_TEST_PACKAGE_PATH so we first change directory to that path.
      - echo "Navigate to test package directory"
      - cd $DEVICEFARM_TEST_PACKAGE_PATH

      # By default, the following command is used by Device Farm to run your Appium TestNG test.
      # Note : DeviceFarm is using the TestNG runner to run the TestNG tests.
      # The goal is to run to your tests jar file with all the dependencies jars in the CLASSPATH.
      # Alternatively, You may specify your customized command.
      # Note: For most use cases, the default command works fine.
      # Please refer "http://testng.org/doc/documentation-main.html#running-testng" for more options on running TestNG tests from the command line.
      - echo "Start Appium TestNG test"
      - java -Dappium.screenshots.dir=$DEVICEFARM_SCREENSHOT_PATH org.testng.TestNG -testjar *-tests.jar -d $DEVICEFARM_LOG_DIR/test-output -verbose 10

      # To run your tests with testng.xml file, use the following sequence:
      # Note: you don't have to unzip your test jar unless you have xml file with custom name
      # 1. Your testng.xml is inside the test jar after packaging step. Unzip it using commands:
      # - echo "Unzipping TestNG tests jar"
      # - unzip *-tests.jar
      # 2. Run your TestSuite by specifying the unzipped testng.xml using commands:
      # - echo "Start Appium TestNG test"
      # - java org.testng.TestNG -d $DEVICEFARM_LOG_DIR/test-output testng.xml

  # The post test phase includes commands that are run after your tests are executed.
  post_test:
    commands:

# The artifacts phase lets you specify the location where your tests logs, device logs will be stored.
# And also let you specify the location of your test logs and artifacts which you want to be collected by Device Farm.
# These logs and artifacts will be available through ListArtifacts API in Device Farm.
artifacts:
  # By default, Device Farm will collect your artifacts from following directories
  - $DEVICEFARM_LOG_DIR
`
 

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by jlipps** [comment]
If Appium is not installing WDA on test farm devices, I would reach out to test farm support. The cloud service provider is responsible for making sure that Appium works in their environment. If they have a bug to file with us as a result, it's best for them to do it as they will have the necessary information.

**Comment by NavpreetD** [comment]
@jlipps Thanks for quick response, i will try to reach out AWS test farm support. I am attaching the error i am getting below. In case i need to fix something in my script. 

 `[DeviceFarm] echo "Start Appium TestNG test"
Start Appium TestNG test
[DeviceFarm] java -Dappium.screenshots.dir=$DEVICEFARM_SCREENSHOT_PATH org.testng.TestNG -testjar *-tests.jar -d $DEVICEFARM_LOG_DIR/test-output -verbose 10
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.testng.xml.XMLParser (file:/opt/java-test-runner/testng-6.8.8.jar) to constructor com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl()
WARNING: Please consider reporting this to the maintainers of org.testng.xml.XMLParser
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[TestRunner] Running the tests in 'sampleTest' with parallel mode:none
[RunInfo] Adding method selector: org.testng.internal.XmlMethodSelector@32b260fa priority: 10
[TestClass] Creating TestClass for [ClassImpl class=localTests.sampleTest]
[TestClass] Adding method sampleTest.sampleTest()[pri:0, instance:null] on TestClass class localTests.sampleTest
[XmlMethodSelector] Including method localTests.appLaunchSetup()
[XmlMethodSelector] Including method localTests.sampleTest()
[TestNG] Running:
  /private/tmp/scratchKGWMg9.scratch/test-packagee0GS8s/testng.xml

[SuiteRunner] Created 1 TestRunners
[TestRunner] Running test sampleTest on 1  classes,  included groups:[] excluded groups:[]
===== Test class
localTests.sampleTest
    @Test sampleTest.sampleTest()[pri:0, instance:localTests.sampleTest@2d710f1a]
======
[TestNG] RUNNING: Suite: "sampleTest" containing "1" Tests (config: /private/tmp/scratchKGWMg9.scratch/test-packagee0GS8s/testng.xml)
[Invoker 1101048445] Keeping method sampleTest.appLaunchSetup()[pri:0, instance:localTests.sampleTest@2d710f1a] for class null
[Invoker 1101048445] Invoking @BeforeTest sampleTest.appLaunchSetup()[pri:0, instance:localTests.sampleTest@2d710f1a]
[TestNG] INVOKING CONFIGURATION: "sampleTest" - @BeforeTest localTests.sampleTest.appLaunchSetup()
Test is started
Failed to invoke configuration method localTests.sampleTest.appLaunchSetup:com.google.common.base.Throwables.throwIfUnchecked(Ljava/lang/Throwable;)V
[TestNG] FAILED CONFIGURATION: "sampleTest" - @BeforeTest localTests.sampleTest.appLaunchSetup() finished in 0 ms
[TestNG] java.lang.NoSuchMethodError: com.google.common.base.Throwables.throwIfUnchecked(Ljava/lang/Throwable;)V
[TestNG] 	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:253)
[TestNG] 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
[TestNG] 	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
[TestNG] 	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
[TestNG] 	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
[TestNG] 	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
[TestNG] 	at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:336)
[TestNG] 	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
[TestNG] 	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
[TestNG] 	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:88)
[TestNG] 	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:98)
[TestNG] 	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:90)
[TestNG] 	at utilities.awsDeviceFarmUtils.getIOSDriver(awsDeviceFarmUtils.java:268)
[TestNG] 	at utilities.awsDeviceFarmUtils.launchApp_ExistingUser(awsDeviceFarmUtils.java:33)
[TestNG] 	at localTests.sampleTest.appLaunchSetup(sampleTest.java:150)
[TestNG] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[TestNG] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[TestNG] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[TestNG] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[TestNG] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
[TestNG] 	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
[TestNG] 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
[TestNG] 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
[TestNG] 	at org.testng.TestRunner.beforeRun(TestRunner.java:641)
[TestNG] 	at org.testng.TestRunner.run(TestRunner.java:609)
[TestNG] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
[TestNG] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
[TestNG] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
[TestNG] 	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
[TestNG] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[TestNG] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
[TestNG] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
[TestNG] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
[TestNG] 	at org.testng.TestNG.run(TestNG.java:1057)
[TestNG] 	at org.testng.TestNG.privateMain(TestNG.java:1364)
[TestNG] 	at org.testng.TestNG.main(TestNG.java:1333)
[TestNG] INVOKING: "sampleTest" - localTests.sampleTest.sampleTest()
[TestNG] SKIPPED: "sampleTest" - localTests.sampleTest.sampleTest() finished in 1 ms
[Invoker 1101048445] Keeping method sampleTest.quitApp()[pri:0, instance:localTests.sampleTest@2d710f1a] for class null
[Invoker 1101048445] Invoking @AfterTest sampleTest.quitApp()[pri:0, instance:localTests.sampleTest@2d710f1a]
[TestNG] INVOKING CONFIGURATION: "sampleTest" - @AfterTest localTests.sampleTest.quitApp()
[TestNG] PASSED CONFIGURATION: "sampleTest" - @AfterTest localTests.sampleTest.quitApp() finished in 0 ms`

**Comment by jlipps** [comment]
It does look like you probably need to fix something. The error appears to be related to either your code or the AWS environment. Unfortunately we can't provide support for those things. I hope AWS support is able to provide guidance!
