### ISSUE TITLE
Cannot start the 'io.appium.settings' application.(Error: Appium Settings app is not running after 5000ms)

### ISSUE THREAD

**Issue by youngfreeFJS** [appium/appium#15507]
## The problem

Cannot start the 'io.appium.settings' application.
Error: Appium Settings app is not running after 5000ms

## Environment

* Appium version (or git revision) that exhibits the issue: v1.20.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 10.15
* Node.js version (unless using Appium.app|exe): v12
* Npm or Yarn package manager:
* Mobile platform/version under test: Android9
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

https://gist.github.com/youngfreeFJS/aa41e0219a6eddf873cd24efbd3aa529

**Comment by mykola-mokhnach** [comment]
Have you tried to start the settings app manually? Are there any exceptions in the device logcat?

**Comment by youngfreeFJS** [comment]
it seems an emulator error, close this issue.
