### ISSUE TITLE
Not able to setup WebdriverAgent

### ISSUE THREAD

**Issue by smrtyviks** [appium/appium#15510]
## The problem

When i am trying to run the ./Scripts/bootstrap.sh command i am getting below mentioned error:

code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: web-driver-inspector@1.0.0
npm ERR! Found: react@15.6.1
npm ERR! node_modules/react
npm ERR!   react@"15.6.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.7.0" from react-dom@15.7.0
npm ERR! node_modules/react-dom
npm ERR!   react-dom@"^15.6.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable):NA
* Desktop OS/version used to run Appium: MACOS 
* Node.js version (unless using Appium.app|exe): 14.15.5
* Npm or Yarn package manager: 7.15.1
* Mobile platform/version under test: 14.4
* Real device or emulator/simulator: Real device Iphone XR
* Appium CLI or Appium.app|exe: Appium CLI & App

## Details

I want to setup the XCUI test framework to work with iOS devices, for which i am trying to install webdriveragentrunner and currently not able to do so since i am not able to setup the bootstrap file om my machine.

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
You probably have some old leftovers on your machine. XCUITest driver included into Appium 1.21 neither has the bootstrap script not requires it to be executed: https://github.com/appium/WebDriverAgent/tree/master/Scripts

**Comment by smrtyviks** [comment]
Hi mykola,

I have uninstalled appium and installed it again using the below command:
npm install -g appium

and followed the steps mentioned in the setup link below:

https://appium.io/docs/en/drivers/ios-xcuitest-real-devices/

but when i am running my appium test script i am getting error:

org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70
xcodebuild error message:

Do you have any idea on how to resolve this issue?

**Comment by mykola-mokhnach** [comment]
This error code is coming from Xcodebuild itself. Nothing we can do there. I would try to compile the project manually from Xcode and see what it says

**Comment by smrtyviks** [comment]
Update:

Got it resolved the issue was i was pointing to incorrect platformVersion in Desired capabilities.
