### ISSUE TITLE
Switching to webview of hybrid app returning Failed to get PID

### ISSUE THREAD

**Issue by sebinjoseph1994** [appium/appium#15523]
## The problem

When I switch to a web view from a hybrid app, its returning failed to get PID.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.0-beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 11.4
* Node.js version (unless using Appium.app|exe): 
* Npm or Yarn package manager: 
* Mobile platform/version under test: Android 11 - UIAutomator2
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

## Details

The androidProcess name set on switching to webview looks incorrect. The webview name is taken as _androidProcess_ instead of the package name. I can't use chromeoptions desired capability directly to set processName as it is a hybrid app. 

## Link to Appium logs

https://gist.github.com/sebinjoseph1994/45812c283beda358b1efd7811ef60a9c

**Comment by mykola-mokhnach** [comment]
thanks for the report. Please check if https://github.com/appium/appium-android-driver/pull/698 works for you

**Comment by sebinjoseph1994** [comment]
@mykola-mokhnach Thanks for the very quick response and fix. Is there a way I can try this out in my project now without waiting for the next beta release to be out?

**Comment by mykola-mokhnach** [comment]
The way to apply the patch is similar for all Appium modules and looks like: https://github.com/appium/appium/issues/14693#issuecomment-684878582

**Comment by sebinjoseph1994** [comment]
@mykola-mokhnach Thank you so much. It worked :)

**Comment by mykola-mokhnach** [comment]
Thanks for checking it

**Comment by mykola-mokhnach** [comment]
The patch has been published to appium@beta
