### ISSUE TITLE
Unable to make real device screenshots with iOS 15 Beta

### ISSUE THREAD

**Issue by rakhmatullov** [appium/appium#15527]
## The problem

The error is shown when trying to make a screenshot with iOS 15 Beta real device.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable): 1.21.0
* Desktop OS/version used to run Appium: MacOS
* Node.js version (unless using Appium.app|exe):-
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS 15 Beta
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: CLI

## Details

Taking screenshot fails. Appium shows this message:

[WD Proxy] Got response with status 500: {"value":{"error":"unable to capture screen","message":"A screen capture was made impossible","traceback":""},"sessionId":"EB0BB92A-8D92-475E-A392-E4E5DA23F7F1"}

## Link to Appium logs

https://gist.github.com/rakhmatullov/9c83c6f4bf74e6e4ae19e1f40b680894

## Code To Reproduce Issue [ Good To Have ]
driver.save_screenshot(filename="some/path")

**Comment by mykola-mokhnach** [comment]
This is expected. Try appium@beta instead

**Comment by rakhmatullov** [comment]
Thank you.

**Comment by edwardvallejo05** [comment]
How did you solve the error I cannot see the screen of the real device ios 15 beta in the desktop appium

**Comment by KazuCocoa** [comment]
`npm install -g appium@beta` or `npm install -g appium@rc` to install beta or rc channel in https://www.npmjs.com/package/appium
