### ISSUE TITLE
[Android] Android 10 vs Android 11 inconsistent attribute value

### ISSUE THREAD

**Issue by sahityaPasnoor** [appium/appium#15541]
## The inconsistent attribute value for Android 10 and Android 11

The inconsistent attribute value for Android 10 and Android 11

When testing the options menu on Android 10 and Android 11 appium gives inconsistent results for the view attribute.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium:  1.21.0
* Node.js version (unless using Appium.app|exe): 12.8.1
* Npm or Yarn package manager:
* Mobile platform/version under test: Android 10 and Android 11
* Real device or emulator/simulator: Real Device and Emulator
* Appium CLI or Appium.app|exe: Appium desktop and CLI

## Details

Options menu item is diabled in onPrepareOptionsMenu function.

`menu?.findItem(R.id.edit_col)?.isEnabled = false`

![image](https://user-images.githubusercontent.com/2419750/122598551-9a43aa00-d032-11eb-9352-1dd46a2de5f9.png)
![image](https://user-images.githubusercontent.com/2419750/122598563-9dd73100-d032-11eb-8c4f-8d5fd6c3b3de.png)

**Comment by mykola-mokhnach** [comment]
These values are retrieved from UiAutomator framework. We don't alter them in Appium in any way.
Only Google itself is capable of changing that behaviour.

Closed as third party issue
