### ISSUE TITLE
Appium 2.0 docs planning

### ISSUE THREAD

**Issue by jlipps** [appium/appium#15566]
_This issue tracks the umbrella proposal for how docs of all kinds will work in Appium 2.0. It may be divided into smaller tasks_

## The big picture

At the present time, disregarding Appium 2.0, our docs are a bit confusing and outdated. Some of the main problems are:

* The marketing website hasn't been updated in probably 5-6 years. 
* We have a sophisticated docs generation system that has a bunch of great organization and information, but some of the information is outdated, and it proved to be too much to keep an exhaustive list of every command in every driver updated.
* We have docs translations but in the past we were told it was pretty bad (excepting perhaps the Chinese documentation, which is excellent Chinese but also probably very outdated).
* We have a sample code directory which contains all or mostly non functional code.
* It's difficult to find docs for a specific version of Appium
* Docs are in multiple places (the Appium docs site at appium.io as well as in various driver READMEs). There is a tension between desire not to duplicate and desire to have all the information in one place.

On top of all this, we are now moving to Appium 2.0, which potentially makes the problem worse in that Appium 2.0 allows for (and hopes for) an explosion of new drivers and plugins, each of which would require its own documentation. To list the problems more specifically:

* Some of these extensions might be "officially" supported, and many will not be, but all will need documentation.
* There is currently no documentation for developers that will enable them to build new extensions with confidence, and this is important for growing the ecosystem.
* So far none of Appium 2.0's new features (the driver/plugin CLI, for example) are documented.
* We need a 1.x -> 2.x migration doc that we can keep updated with the current situation, listing all breaking changes and workarounds.

## Design goals

* Prefer stable links over duplication of information (which could easily get stale).
* Clearly differentiate the types of documentation we have: overviews, conceptual articles, how-to guides, articles on specific complex features, API documentation, and contributing/developer docs.
* Keep documentation closer to the source code (i.e., drivers should publish their own documentation rather than syndicating it to the main docs site). This makes it possible to request/update documentation in the same PR as code changes, which in turn makes it more likely that we will keep our docs up to date with reality.
* Optimize for easy localization, using standard i18n frameworks to allow crowd-sourced translations or easy translation PRs

## The proposal

_TODO_

#### Working ideas

* Create a driver/plugin docs framework that any driver/plugin can use simply by implementing a bunch of YAML and MD files. Then each driver/plugin could simply run a script to get beautiful documentation in a style and format consistent with every other Appium driver/plugin.
* Make docs easily navigable
* Push all driver/plugin specific information to docs hosted by that driver/plugin, and simply link to that from a central location.
* Push all command docs to drivers/plugins as API docs

#### Specific new docs we need

* [ ] A new overview homepage that allows people to go to one of several different overviews of appium depending on their background (manual tester, someone familiar with selenium, or app developer, let's say)
* [ ] Appium 2.0 driver overview and CLI docs
* [ ] Appium 2.0 plugin overview and CLI docs
* [x] Migrating from 1.x to 2.0
* [ ] Guide (or at least rough API docs) for developing an Appium 2.0 driver
* [ ] Guide (or at least rough API docs) for developing an Appium 2.0 plugin

#### Specific docs that need updating / removal

* [ ] All the driver-specific guides (iOS predicates, xcuitest gestures, espresso datamatcher, etc...) should migrate to the driver repos or driver-specific docs
* [x] Image matching docs should go to the image plugin

**Comment by jlipps** [comment]
I had a further thought about documenting commands. IMO it would be great if command docs could live in the code alongside commands, and could be extracted and used to generate searchable API documentation for each driver/plugin. I see 3 different kinds of commands:

1. Implementation of a standard Appium command name (defined in Appium's base driver routes.js)
2. Implementation of a new route
3. ExecuteScript overload

For the first category, we already have all the information required to document the command, sans a brief description relativizing the command to the platform.

For the second category, we theoretically also have the information required as part of the static `newMethodMap` property on the driver.

The third category is more ad hoc, but we could standardize it in basedriver for use for other drivers if we want. For example we could allow drivers/plugins to represent which executeScript overloads they support, e.g.:

```js
static executeOverloads = {
    'mobile: swipe': {
        command: 'executeMobile_swipe',
        params: {required: ['direction'], optional: ['element']}
    },
    'mobile: installApp': {
        command: 'executeMobile_installApp',
        params: {required: ['path']}
    }
}
```

If we can do all of these things, then all we need is some kind of custom JSDoc annotation on the actual command functions themselves, for example:

```js
/**
* Click an element
* @param {Object} elementId
* @appiumCommand click
* /
async function click () {...}

/**
* Do a custom swipe
* @param {SwipeArgs} swipe args
* @appiumCommand executeMobile_swipe
*/
async function executeMobile_swipe () {...}
```

With something like this, we could combine the custom JSDoc annotations with our knowledge of Appium base routes and the driver itself, to automatically generate nice API docs for every driver that decides to follow this standard. Each driver could then post the docs to its own github pages, or maybe there'd even be a mode for plain markdown docs in a basic table format.

**Comment by jlipps** [comment]
With reference to my previous comment, I realized there is actually a 4th category of commands too:

4. Command which is not mentioned in the driver codebase but which is enabled via proxy to some other WD server

I'm not quite sure how to handle documenting of these. A couple ideas:

First, the driver could include dummy docstrings, something like:

```js
/**
* @appiumProxyCommand [Chromedriver][POST][/session/:sessionid/element/:elementid/click]
*/
```

Or the driver could simply note in its docs something like the following:

> When in web/hybrid mode, this driver proxies most automation commands to Chromedriver (link). For a full explanation of commands available via Chromedriver, visit their documentation.

**Comment by sakibguy** [comment]
Good job!

**Comment by sakibguy** [comment]
Good Job. Thanks

**Comment by jlipps** [comment]
going to close this in favour of https://github.com/appium/appium/issues/16792, though this can still stay up as a reference for some ideas which might still need to be implemented for https://github.com/appium/appium/issues/16787
