### ISSUE TITLE
[sessionCapabilities()] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command.

### ISSUE THREAD

**Issue by pawelwch** [appium/appium#15560]
## The problem

After test is finished (and no matter if pass or fail) I tried to Refresh Source & Screenshot but every time I do, I got an error: 

> [sessionCapabilities()] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command.

## Environment

* I tried both 7.3.0 and 7.5.1
* Ubuntu 18.04 LTS
* Appium-linux-1.21.0.AppImage
* Npm 6.14.6
* Device under test: Physical device - Xiaomi Mi A2

## Details
![image](https://user-images.githubusercontent.com/33806102/122686588-1d6f2680-d212-11eb-883c-f832ce70a3d0.png)

## Link to Appium logs

At the very end of test, there is logged an issue I encouter each time after running a test, while refreshing the source & screenshot using appium desktop.
https://gist.github.com/pawelwch/8f8625fa2fabf9c3edb505dc3998e36a

## Code To Reproduce Issue [ Good To Have ]

My configuration:

public class BaseClass {

    AndroidDriver<MobileElement> driver;

    @BeforeTest
    public void setCapabilities() throws MalformedURLException {
        String appiumServerURL = "http://127.0.0.1:4723/wd/hub";
        DesiredCapabilities dc = new DesiredCapabilities();
        dc.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
        dc.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10");
        dc.setCapability(MobileCapabilityType.BROWSER_NAME, BrowserType.CHROME);
        dc.setCapability(MobileCapabilityType.DEVICE_NAME, "Xiaomi Mi A2");
        dc.setCapability(MobileCapabilityType.AUTOMATION_NAME, "UiAutomator2");
        dc.setCapability(MobileCapabilityType.NO_RESET, true);
        dc.setCapability("chromedriverExecutable", "/home/maryna/drivers/chromedriver");
        driver = new AndroidDriver<MobileElement>(new URL(appiumServerURL), dc);
    }

//    @AfterClass
//    public void tearDown() {
//        driver.close();
//    }

    @Test
    public void loginWithIncorrectCredentials(){
        driver.get("https://www.saucedemo.com/");
        MobileElement privacyAcceptButton = (MobileElement) new WebDriverWait(driver, 10).until(ExpectedConditions.elementToBeClickable(By.xpath("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.FrameLayout[2]/android.webkit.WebView/android.view.View[2]/android.app.Dialog/android.view.View/android.view.View[2]/android.view.View/android.widget.Button[1]")));
        privacyAcceptButton.click();

    }
}

**Comment by mykola-mokhnach** [comment]
The error there seems to be valid. We could also check the device logcat output to see why the server instrumentation process has been terminated

**Comment by pawelwch** [comment]
@mykola-mokhnach do you mean that after test is finished we are not able to `Refresh Source & Screenshot`  
in order to inspect the current view?

**Comment by mykola-mokhnach** [comment]
Yes, this is correct

**Comment by amedvedjev** [comment]
@pawelwch you need to do this right after test before driver quit.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
