### ISSUE TITLE
[iOS real device]An unknown server-side error occurred while processing the command. Original error: Failed to receive any data within the timeout: 5000

### ISSUE THREAD

**Issue by BraveLittleTapok** [appium/appium#15564]
## The problem
After download the latest version of Appium (1.21.0) I can't run appium inspector or any of my test. When I tried to run appium inspector I get this issue: "An unknown server-side error occurred while processing the command. Original error: Failed to receive any data within the timeout: 5000" 

WebDriverAgent in xcode was successfully built with my real device. And  I rerun appium after build xcode project and still got this issue

![Screenshot 2021-06-22 at 14 34 39](https://user-images.githubusercontent.com/26220551/122919018-6c2ed480-d368-11eb-9daa-ef5b771b9301.png)

Log from Intelligence idea:

Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Failed to receive any data within the timeout: 5000
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'EPRUPETW03A9', ip: 'fe80:0:0:0:18ac:9f8a:632:f8b7%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '11.0.9'
Driver info: driver.version: IOSDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Failed to receive any data within the timeout: 5000
    at getResponseForW3CError (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
    at asyncHandler (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'EPRUPETW03A9', ip: 'fe80:0:0:0:18ac:9f8a:632:f8b7%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '11.0.9'

**Comment by mykola-mokhnach** [comment]
Please fill out the issue template properly and provide the full server log.

**Comment by amedvedjev** [comment]
@BraveLittleTapok you can also try add more details and ask here -> https://discuss.appium.io/

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by reemadaga** [comment]
@mykola-mokhnach - Test runs fine in the simulator but fails in the real device with the following error:
"equest failed with status 500 due to An unknown server-side error occurred while processing the command. Original error: Failed to receive any data within the timeout: 5000"
Using the following
Appium - 1.22.2
NodeJS - 18
Webdriverio 8

**Comment by reemadaga** [comment]
{
  node: '18.18.0',
  acorn: '8.10.0',
  ada: '2.6.0',
  ares: '1.19.1',
  brotli: '1.0.9',
  cldr: '43.1',
  icu: '73.2',
  llhttp: '6.0.11',
  modules: '108',
  napi: '9',
  nghttp2: '1.55.0',
  nghttp3: '0.7.0',
  ngtcp2: '0.8.1',
  openssl: '3.0.10+quic',
  simdutf: '3.2.14',
  tz: '2023c',
  undici: '5.22.1',
  unicode: '15.0',
  uv: '1.46.0',
  uvwasi: '0.0.18',
  v8: '10.2.154.26-node.26',
  zlib: '1.2.13.1-motley'
}

**Comment by eglitise** [comment]
@reemadaga Appium 1 is no longer supported. Please create a new issue if you can still reproduce the problem with Appium 2.
