### ISSUE TITLE
Popup "Unable to boot device in current state: Booted"

### ISSUE THREAD

**Issue by yavgel** [appium/appium#15574]
## The problem

Always has popup "Unable to boot device in current state: Booted" on a session start - so I cannot see an emu until OK button will be clicked.

![image](https://user-images.githubusercontent.com/8123409/123291037-0a11d300-d512-11eb-986e-1bc7997da1d1.png)

Although, before emu start I do 
`xcrun simctl list` and  it shows my device as `Shutdown`:

![image](https://user-images.githubusercontent.com/8123409/123290902-ec446e00-d511-11eb-8a41-87b8e29d2723.png)

## Environment

* Appium v1.20.2 (also reproduced on the latest 1.21.0)
* iOS iPhone 8 emulator

Appium logs are attached:
[appium-server-logs.txt](https://github.com/appium/appium/files/6710448/appium-server-logs.txt)

**Comment by KazuCocoa** [comment]
Did this happen only when you launch the simulator via Appium?
I got the error a few times before with non-appium environment. I guess this is out-of Appium's stuff, unfortunately.

**Comment by yavgel** [comment]
Yes, it happened to me only with the Appium emulator session.
Today I implemented 4 iOS devices parallel mode tests execution. The issue disappeared, no popup presented anymore.
