### ISSUE TITLE
Error: Appium Settings app is not running after 5000ms（'adb: error: listener 'tcp:52185' not found';）

### ISSUE THREAD

**Issue by youngfreeFJS** [appium/appium#15577]
## The problem

**_Error: Appium Settings app is not running after 5000ms（'adb: error: listener 'tcp:52185' not found';）_**

I got the error a few times, but it seems not an Appium fault.

_It failed on the first test, but it worked fine again on the second._

log [here](https://gist.github.com/youngfreeFJS/35fc60452faf2ce9414c7b421a8da025).

## Environment

* Appium version (or git revision) that exhibits the issue: v1.17.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 15
* Node.js version (unless using Appium.app|exe): v12
* Npm or Yarn package manager:
* Mobile platform/version under test: Android 9
* Real device or emulator/simulator: emulator(ARM)
* Appium CLI or Appium.app|exe: CLI

**Comment by youngfreeFJS** [comment]
@mykola-mokhnach @KazuCocoa 
Thanks for any ideas! 🌹

**Comment by mykola-mokhnach** [comment]
You're right, most likely this is happening because of emulator slowness. Unfortunately there is not much we could do from this perspective. If the emulator reports it is alive to our liveness checks and then still fails to install/launch an app then it must be something that Google should address.

Anyway, I would try to update the Appium server to the most recent version first.

**Comment by youngfreeFJS** [comment]
> You're right, most likely this is happening because of emulator slowness. Unfortunately there is not much we could do from this perspective. If the emulator reports it is alive to our liveness checks and then still fails to install/launch an app then it must be something that Google should address.
> 
> Anyway, I would try to update the Appium server to the most recent version first.

Thanks @mykola-mokhnach ❤️. I have been updated the Appium server.

I want to know what the **_systemPort_** is doing. Should I find [this](https://github.com/appium/appium-uiautomator2-driver) repository? I would like to manually invoke the commands, to verify that it is caused by a device problem.

**Comment by KazuCocoa** [comment]
Yes, you can find the port implementation in the repository.
http://appium.io/docs/en/advanced-concepts/parallel-tests/ is the typical usage.

**Comment by mykola-mokhnach** [comment]
The https://github.com/appium/appium-uiautomator2-driver repository is what you need. Just search everything that includes `systemPort` substring
