### ISSUE TITLE
customSnapshotTimeout Capability is not recognised in Appium 1.21.0

### ISSUE THREAD

**Issue by YenikeRaghuRam** [appium/appium#15570]
## The problem

customSnapshotTimeout Capability is not recognised in Appium 1.21.0

## Environment

* Appium version (or git revision) that exhibits the issue:1.21.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 11.4
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium Desktop

## Details

customSnapshotTimeout Capability is not recognised in Appium 1.21.0

## Link to Appium logs

[MJSONWP] Calling AppiumDriver.createSession() with args: [{"automationName":"XCUITest","bundleId":"com.carriertransicold.containerLINK","clearSystemFiles":true,"customSnapshotTimeout":600,"deviceName":"transicold","newCommandTimeout":0,"platformName":"iOS","platformVersion":"14.6","udid":"8c80aefa8edd5aeacd1aee5102c071cd9185ccb8","wdaConnectionTimeout":600000,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1624442612799 (15:33:32 GMT+0530 (India Standard Time))
[Appium] Appium v1.21.0 creating new XCUITestDriver (v3.43.0) session
[Appium] Applying relaxed security to 'XCUITestDriver' as per server command line argument. All insecure features will be enabled unless explicitly disabled by --deny-insecure
[BaseDriver] Creating session with MJSONWP desired capabilities: {
[BaseDriver]   "automationName": "XCUITest",
[BaseDriver]   "bundleId": "com.carriertransicold.containerLINK",
[BaseDriver]   "clearSystemFiles": true,
[BaseDriver]   "customSnapshotTimeout": 600,
[BaseDriver]   "deviceName": "transicold",
[BaseDriver]   "newCommandTimeout": 0,
[BaseDriver]   "platformName": "iOS",
[BaseDriver]   "platformVersion": "14.6",
[BaseDriver]   "udid": "8c80aefa8edd5aeacd1aee5102c071cd9185ccb8",
[BaseDriver]   "wdaConnectionTimeout": 600000,
[BaseDriver]   "connectHardwareKeyboard": true
[BaseDriver] }
**### [BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[BaseDriver]   customSnapshotTimeout**
[BaseDriver] Session created with session id: 6f2770c8-1fdc-48db-bdca-4a9090f9a056

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
this is expected. `customSnapshotTimeout` is a setting, not a capability

**Comment by YenikeRaghuRam** [comment]
@mykola-mokhnach  is there any possibility for having Setting customSnapshotTimeout set in Appium Desktop?
