### ISSUE TITLE
No exception is throwing if element is not found. Appium is keep on searching for the element indefinitely

### ISSUE THREAD

**Issue by SuryaPtester** [appium/appium#15584]
No exception is not throwing if element is not found. Appium is keep on searching for the element indefinitely.

Appium - 1.21.0,
Android -7.1.1,
Binding language - Python,
Emulator

I used 1.17.1 also, in that also faced this issue,

Can see no such element error in appium server desktop, but not returning any value to client(script)

**Comment by mykola-mokhnach** [comment]
Please provide a proper issue description, including actual steps, results and server logs

**Comment by SuryaPtester** [comment]
Thanks @mykola-mokhnach  for response and apologies , it is working fine and closing this issue
