### ISSUE TITLE
How to attach appium to a running app

### ISSUE THREAD

**Issue by lucaswxp** [appium/appium#15581]
Is it possible to attach Appium to a running app? 

Maybe that is already possible, I just can't find any documentation on it. All examples I found makes appium launch the app itself.

I gave a quick look at the W3 protocol, and in theory that is nothing that stops Appium at protocol level to create a new session on top of a running app, but I might be wrong about that.

Can you guys help?

**Comment by KazuCocoa** [comment]
`autoLaunch: false` allow you to establish an appium session without launching apps. When you establish an appium session without app and bundleId (or app and activity in uia2), you can jus establish the session without launching app.

Then, you can interact with existing apps on the device via appium.

> If neither of the app or bundleId capabilities are provided then the driver starts from the Home screen and expects the test to know what to do next.

https://github.com/appium/appium-xcuitest-driver#app
https://github.com/appium/appium-uiautomator2-driver#app

**Comment by KazuCocoa** [comment]
https://discuss.appium.io/ may also help such questions

**Comment by lucaswxp** [comment]
@KazuCocoa Thank you!
