### ISSUE TITLE
An unknown server-side error occurred while processing the command

### ISSUE THREAD

**Issue by eslam101070** [appium/appium#15587]
## The problem
I added required data (JSON Representation) and clicked on start session , the app install and open on device then get this error

`An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.instagram.android' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: 'com.instagram.android.activity.MainTabActivity' or 'com.instagram.android.com.instagram.android.activity.MainTabActivity' never started. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting`

## Link to Appium logs

https://gist.github.com/eslam101070/286c9dbffa7752bc7a698b5ff0705d4a#file-appium-log

## JSON Representation

{
  "platformName": "Android",
  "platformVersion": "11",
  "deviceName": "sdk_gphone_x86_arm",
  "app": "C:\\Users\\Eslam\\Downloads\\right_instagram.apk"
}

**Comment by KazuCocoa** [comment]
Appium tries to guess the start activity reading its manifesto.
It seems your app's launching activity is not `MainTabActivity` which is specified in the manifesto.
Please read https://appium.io/docs/en/writing-running-appium/android/activity-startup/ and coordinate appium capabilities.

**Comment by KazuCocoa** [comment]
close since this is activity startup configuration stuff
