### ISSUE TITLE
An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET

### ISSUE THREAD

**Issue by SrimanPilli** [appium/appium#15593]
## The problem
An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET with Appium version 1.15.0

With Appium version 1.20.2 -- SOCKET HANGUP Error

## Environment

* Appium version 1.15.0 / Tried with 1.20.2
* Last Appium version that did not exhibit the issue (if applicable):  1.15.0 worked sometime ago
* Desktop OS/version used to run Appium: 
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: Android Emulator 7.1 and 8.1
* Real device or emulator/simulator: Emulator

Xamarin Android application with Appium Tests for UI running on AZURE Pipeline against SAUCE Labs.

## Link to Appium logs

https://gist.github.com/SrimanPilli/ed8ad3b79b604c4e7465d9687ed9cce1

## Code To Reproduce Issue [ Good To Have ]

Xamarin android app with basic appium test through Azure ---> SauceLabs

**Comment by mykola-mokhnach** [comment]
Unfortunately the provided logs does not suffice. Please also attach full server and device logs

**Comment by mykola-mokhnach** [comment]
Also, have you tried to context SL customer support?

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by SrimanPilli** [comment]
I do have Remote URL of SAUCE Labs in capabilities and In a RunSettings file which is trying to create two sessions and throwing the error SOCKET HANGUP.
when you have URL twice It throw's this error.
