### ISSUE TITLE
UIAutomator2 support for flag `disableAndroidWatchers`

### ISSUE THREAD

**Issue by eduardoreynoso** [appium/appium#15597]
I see that the flag `disableAndroidWatchers` is only supported by UIAutomator1, I am currently using UIAutomator2 to run my tests but recently the system modal that the app is unresponsive its blocking my tests. The app is not unresponsive and I can see it run in the background. The description of this flag sounds exactly what I need, I cannot find the repository for UIAutomator1 to see how its implemented, I also tried searching for the adb commands and it does not seem to have a flag to disable the watchers.
Any help is appreciated, thanks!

**Comment by mykola-mokhnach** [comment]
Such option is not present in UIA2 driver, because it does not start any watchers. I would try to fetch the device logs and/or get the performance metrics snapshot to figure out why the app gets unresponsive.

**Comment by eduardoreynoso** [comment]
Got it, thanks for the information let me dig further to see why the app is getting marked as unresponsive when its not. Thank you

**Comment by mykola-mokhnach** [comment]
Closing the issue for now as there is nothing more to do on it
