### ISSUE TITLE
remove WIP bot?

### ISSUE THREAD

**Issue by boneskull** [appium/appium#15592]
I believe the WIP bot predates GH's "Draft"  PR implementation.  If it provides similar functionality as the WIP bot, perhaps the latter can be removed.

If you're unfamiliar, a "Draft" pull request is one which is marked as such (via GitHub's UI).  If a PR is in a "Draft" state, it **cannot be merged**.  Otherwise, it behaves as a normal PR.

In a discussion in Slack, @mykola-mokhnach described the "WIP" bot as doing something (what, exactly?) for "unfinished features."  I interpret this to be "features that are not yet ready to be merged," though I may be mistaken.

To differentiate features/fixes/experiments which are _not_ ready for merging, we can _label_ the PR appropriately and use the "draft" functionality.  When something is ready for review, the PR can be moved _out_ of "draft" status.

What does WIP bot provide in addition to draft PRs?  Do we still need it?

**Comment by KazuCocoa** [comment]
I'd like to vote to remove it.

We can convert a PR to a draft mode again without closing the PR.
I think when we introduced this, the draft PR was not able to be the Draft again once the PR had been a PR. GitHub function has been enhanced.

**Comment by jlipps** [comment]
Yes, I also vote to get rid of wip bot

**Comment by KazuCocoa** [comment]
Uninstalled the app : https://github.com/organizations/appium/settings/installations

**Comment by KazuCocoa** [comment]
Let me add the bot again if we needed
