### ISSUE TITLE
Location Speed on Eclipse?

### ISSUE THREAD

**Issue by Lucaru413** [appium/appium#15598]
## THE PROBLEM
Hi guys,
I must simulate a navigation for a driving app. 
I can't use apk to do it because i'm using for the solution Appium+Eclipse and I run it on AppCenter, so i can use only 1 app.

## ENVIRONMENT

I'm using the method set location, it works, and i have simulated a 30 points trip, but my app don't register any speed, and i need it because without that it can't record my trip

Is there a method that can put speed on my locations?

Thanks.

**Comment by mykola-mokhnach** [comment]
Kindly use Appium forum to ask questions
