### ISSUE TITLE
Unable to interact with App after using terminateApp(bundleId) and activateApp(bundleId) on Hybrid App

### ISSUE THREAD

**Issue by Norphy** [appium/appium#15600]
## When I use terminateApp(BundleId) and activateApp(BundleId) to kill the app and getting it from the background

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable): none that I know of (Issue also visible on 1.18.0)
* Desktop OS/version used to run Appium: Mac Mojave version 10.14.6 and Windows 10
* Node.js version (unless using Appium.app|exe):v12.13.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Emulator: Pixel 3 API 29 and Pixel 3 API 30(Also doesn't work on iOS but here I am reporting Android run logs)
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

When I use terminateApp() and activateApp() to kill and reactivate the app, it works but I am no longer able to interact with the App afterwards

## Code To Reproduce Issue:  App has to be a hybrid app (uses a webview)
driver.terminateApp(bundleId);
driver.activateApp(bundleId);
driver.findElement(By.xpath("//div[@id='anyId']")).click();

**Comment by mykola-mokhnach** [comment]
I assume this is expected, because chromedriver is actually attached to the particular process id, which is changed after app restart. I would try to repeat the context switch and see if that helps.

**Comment by Norphy** [comment]
@mykola-mokhnach you're right. Thank you very much! Before I posted, I just checked using getContext() and when I found it was the correct context I assumed that wasn't the issue. After switching to Native and back to the webview context, it worked. Thank you and sorry for wasting time on a small issue.
