### ISSUE TITLE
APK Installation Issue and Launch APK from Python in latest appium 1.21 server

### ISSUE THREAD

**Issue by amitstudent2006** [appium/appium#15603]
Dear Team ,

I am looking to get your great tremendous support as initial stage .When I launch any shopping site from appium inspector window , it is not launching any application and give error as *'Encountered internal error running command: Error: Cannot verify the signature of 'C:\Users\ami\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.21.1.apk'. Original error: The JAVA_HOME location 'C:\Program Files\Java\jdk-16\bin;' must exist'*.

I have proper java setup and able to execute any java program from any place.

When i write basic program with python language for launching application ., it is giving same error .

Could any one team have a look on attachment with above error and  guide me whether it is issue or not .if not ,how to resolve that

your help is highly appreciated in [advance.](![amazonapk installationerror](https://user-images.githubusercontent.com/51488902/124357067-2c54d080-dc37-11eb-8a99-e79bee657274.JPG)
![appium inspector logs](https://user-images.githubusercontent.com/51488902/124357069-2d85fd80-dc37-11eb-99cc-8549384af406.JPG)
![Flipkartappiumlaunch error](https://user-images.githubusercontent.com/51488902/124357070-2eb72a80-dc37-11eb-9cbd-40fc20368a1f.JPG)
![pycharmbasic script error](https://user-images.githubusercontent.com/51488902/124357071-2eb72a80-dc37-11eb-87a9-2a6b5157e684.JPG)
)

Thanks And Regards
Amit Gupta

[](![amazonapk installationerror](https://user-images.githubusercontent.com/51488902/124357067-2c54d080-dc37-11eb-8a99-e79bee657274.JPG))

**Comment by mykola-mokhnach** [comment]
The error about JAVA_HOME is valid. It for sure should not point to the `/bin` subfolder

The above message on top of Android emulator means that the app under test does not support the current Emulator architecture (which is most likely the Intel one).

**Comment by amitstudent2006** [comment]
Dear Team ,

I have checked that the java_home path is set correctly and also not
pointing to the bin folder .I have created two emulators with android 9 and
android 11 but still no luck .It is not supporting the basic application.

Could you please provide some solution for the same

**Comment by mykola-mokhnach** [comment]
Unfortunately we cannot help there as the issue has nothing to do with Appium, but rather with the local environment setup. You could follow the tutorial at https://github.com/appium/java-client/blob/master/docs/environment.md to verify env variable values per server process.

**Comment by mykola-mokhnach** [comment]
> It is not supporting the basic application.

Consider asking your developer to provide a valid build for the given Emulator architecture

**Comment by youngfreeFJS** [comment]
Emulator architecture must include **_x86_**  substring in **_build.grandle.abiFilters_** 

more information here: https://developer.android.com/ndk/guides/abis

**Comment by amitstudent2006** [comment]
Team,

We have an issue in the latest version of appium 1.21 because if i
uninstall appium 1.21 and try to install appium 1.18 or old version ,It is
working fine.

It seems that some team already reported that issue that is verified with
the link below but I don't know why we have an issue or not stable version
with latest appium server 1.21.
https://github.com/appium/appium/issues/14724

Thanks & Regards
Amit G

**Comment by mykola-mokhnach** [comment]
Please create appropriate issue report containing the necessary logs and details if you experience a new issue
Regarding https://github.com/appium/appium/issues/14724 - it is a random apkanalyzer issue, which we cannot figure out the exact reason for. You are welcome to provide a patch if you know how to solve it.

Closed this one as not an issue
