### ISSUE TITLE
azure devops ios build pipeline 

### ISSUE THREAD

**Issue by anilakuzum** [appium/appium#15609]
I'm building ios with azure devops pipeline, I get an error as in the picture, it doesn't show in the error details.
![image](https://user-images.githubusercontent.com/3521437/124463398-81115c00-dd9b-11eb-8bec-a57c3e85983f.png)
![image](https://user-images.githubusercontent.com/3521437/124463419-88d10080-dd9b-11eb-9adb-66e9533e0d9b.png)

**Comment by mykola-mokhnach** [comment]
Please fill out the issue report properly and provide the requested information

**Comment by anilakuzum** [comment]
I entered the requested information, I didn't understand what you mean.

**Comment by mykola-mokhnach** [comment]
We have the issue request template, which must be filled out properly in order to be able to analyse an issue: https://github.com/appium/appium/blob/master/.github/ISSUE_TEMPLATE.md

Unfortunately without this information we cannot help nothing and the issue will be closed as incomplete.

**Comment by mykola-mokhnach** [comment]
Closed as incomplete
