### ISSUE TITLE
Element 'name' and 'label' attributes not visible in XCUIElementTypeButton elements within an XCUIElementTypeNavigationBar

### ISSUE THREAD

**Issue by merrill-kashiwabara-bose** [appium/appium#15619]
## The problem
Element 'name' and 'label' attributes not visible in XCUIElementTypeButton elements within an XCUIElementTypeNavigationBar when using find_element() or the Appium Inspector.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2 (app), 1.21.0 (CLI) 
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS Catalina 10.15.4
* Node.js version (unless using Appium.app|exe):v12.22.1(CLI)
* Npm or Yarn package manager: 6.14.12(CLI)
* Mobile platform/version under test:iOS 13.7, iOS 14.4
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: both

## Details

Given the locator (MobileBy.XPATH, "//XCUIElementTypeButton[@label = 'my_element']")
when running on a simulator with SDK 13.7
element is found. 
Given the same app running on a simulator with SDK 14.4 with the same locator, the element is not found.

In the inspector, when running on 13.7. the element source is:
<XCUIElementTypeButton type="XCUIElementTypeButton" name="settings" label="settings" enabled="true" visible="true" x="316" y="20" width="51" height="44"/>
When running 14.4, the same element is:
<XCUIElementTypeButton type="XCUIElementTypeButton" enabled="true" visible="true" x="316" y="20" width="51" height="44" index="2"/>

Note: The other element within the navigation bar, a static text element, retained its 'name' and 'label' elements in both versions.
Also, other buttons outside the navigation bar retained their 'name' and 'label' elements. 

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Attributes visibility (or invisibility) depends on XCTest and accessibility manager. Unfortunately there is nothing we could do about it from Appium side.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
