### ISSUE TITLE
I got different result from testing with desktop version and  installed with command "npm". The version is the same "1.21.0"

### ISSUE THREAD

**Issue by piaoran100** [appium/appium#15616]
## The problem
I install two appium: Desktop version 1.21.0 and "npm install appium@1.21.0 -g". But when I  run the testing, change the window of webview. The Desktop version passed, successful on change webview. The npm version return error, see it in details as below.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe): v14.13.1
* Npm or Yarn package manager:
* Mobile platform/version under test: android 9
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: two different.

## Details
 [Chromedriver] Changed state to 'starting'
[debug] [Chromedriver] Using the static Chromedriver->Chrome mapping
[debug] [Chromedriver] The most recent known Chrome version: 89.0.4389
[debug] [Chromedriver] Found 1 executable in '/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac'
[debug] [Chromedriver] The following Chromedriver executables were found:
[debug] [Chromedriver]     '/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver_mac64_v89.0.4389.23' (version '89.0.4389.23', minimum Chrome version '89.0.4389')
[debug] [Chromedriver] Browser version in the supplied details: Chrome/77.0.3865.120
[debug] [Chromedriver] Found Chrome bundle 'undefined' version '77.0.3865'
[debug] [Chromedriver] Error: No Chromedriver found that can automate Chrome '77.0.3865'. You could also try to enable automated chromedrivers download server feature. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md for more details
[debug] [Chromedriver]     at Chromedriver.getCompatibleChromedriver (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/lib/chromedriver.js:367:15)
[debug] [Chromedriver]     at Chromedriver.initChromedriverPath (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/lib/chromedriver.js:391:11)
[debug] [Chromedriver]     at Chromedriver.start (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/lib/chromedriver.js:456:7)
[debug] [Chromedriver]     at AndroidUiautomator2Driver.setupNewChromedriver (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/context.js:440:3)
[debug] [Chromedriver]     at AndroidUiautomator2Driver.startChromedriverProxy (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/context.js:189:10)
[debug] [Chromedriver]     at AndroidUiautomator2Driver.switchContext (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/context.js:125:5)
[debug] [Chromedriver]     at AndroidUiautomator2Driver.setContext (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/context.js:60:3)
[Chromedriver] No Chromedriver found that can automate Chrome '77.0.3865'. You could also try to enable automated chromedrivers download server feature. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md for more details

## Code To Reproduce Issue [ Good To Have ]

driver.switchTo().window("xxxxx");

**Comment by KazuCocoa** [comment]
Did the desktop appium use another version of chromedriver?

```
[debug] [Chromedriver] The most recent known Chrome version: 89.0.4389
[debug] [Chromedriver] Found 1 executable in '/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac'
```

**Comment by piaoran100** [comment]
> Did the desktop appium use another version of chromedriver?
> 
> ```
> [debug] [Chromedriver] The most recent known Chrome version: 89.0.4389
> [debug] [Chromedriver] Found 1 executable in '/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac'
> ```

I did not set the chromedriver version. just set enableWebviewDetailsCollection=true

**Comment by KazuCocoa** [comment]
Appium chose chromedriver automatically by default to communicate with web context.

Appium desktop launches appium with `--relaxed-security` option to allow auto downloading chromedriver binaries to choose a proper version. So if appium desktop log had different version, then maybe `--relaxed-security` help for your CLI appium.
http://appium.io/docs/en/writing-running-appium/security/ and `chromedriver_autodownload` section.
The below is default configuration in Appium Desktop.
<img width="627" alt="Screen Shot 2021-07-07 at 22 12 17" src="https://user-images.githubusercontent.com/5511591/124865954-765bf000-df70-11eb-9dcb-e3edf20f23c6.png">

**Comment by piaoran100** [comment]
> Appium chose chromedriver automatically by default to communicate with web context.
> 
> Appium desktop launches appium with `--relaxed-security` option to allow auto downloading chromedriver binaries to choose a proper version. So if your appium desktop log have had different version, the `--relaxed-security` worked.
> Then maybe `--relaxed-security` help for your CLI appium.
> http://appium.io/docs/en/writing-running-appium/security/ and `chromedriver_autodownload` section.
> The below is default configuration in Appium Desktop.
> <img alt="Screen Shot 2021-07-07 at 22 12 17" width="627" src="https://user-images.githubusercontent.com/5511591/124865954-765bf000-df70-11eb-9dcb-e3edf20f23c6.png">

it worked~! Thanks a lot.
