### ISSUE TITLE
Encountered internal error running command: NotImplementedError: Method is not implemented with Appium 1.20.1

### ISSUE THREAD

**Issue by vsadineni1** [appium/appium#15615]
## The problem

On MacOS Big Sur 11.4,
1. installed Xcode - 12.5.1
2. Installed Appium: 1.20.1 (npm install -g appium@1.20.1)
3. From xcode, downloaded the iOS: 14.3

------
**[Appium] Welcome to Appium v1.20.1**
[Appium] Non-default server args:
[Appium]   port: 4444
[Appium]   defaultCommandTimeout: 600
**[Appium] Appium REST http interface listener started on 0.0.0.0:4444**

I am able to launch the appium server successfully from command line. When I try to run a mobile test againsy my iPhone 14.3 iPhone simulator, I get the below error.

The session is created successfully but when appium is clicking on the EULA button on the screen, then I get the below error:

_debug] [XCUITest] Executing command 'execute'
[debug] [W3C (e92c6778)] Encountered internal error running command: NotImplementedError: Method is not implemented
[debug] [W3C (e92c6778)]     at XCUITestDriver.execute (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/execute.js:13:11)
[debug] [W3C (e92c6778)]     at commandExecutor (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:334:9)
[debug] [W3C (e92c6778)]     at /usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:129:12
[debug] [W3C (e92c6778)]     at AsyncLock._promiseTry (/usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:253:31)
[debug] [W3C (e92c6778)]     at exec (/usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:128:9)
[debug] [W3C (e92c6778)]     at AsyncLock.acquire (/usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:144:3)
[debug] [W3C (e92c6778)]     at XCUITestDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:347:39)
[debug] [W3C (e92c6778)]     at XCUITestDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:730:24)
[debug] [W3C (e92c6778)]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:547:36)
[debug] [W3C (e92c6778)]     at runMicrotasks (<anonymous>)
[debug] [W3C (e92c6778)]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[debug] [W3C (e92c6778)]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:297:21)_

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS Bigsur 11.4
* Node.js version (unless using Appium.app|exe): v14.6.0
* Npm or Yarn package manager: 6.14.7
* Mobile platform/version under test: iOS 14.3
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: 1.20.1

## Details

I can create a session with the mobile app on iPhone 14.3 simulator, but when the test tries to click on the "I Agree"(EULA) button, then I see a mehod not implemented error.

## Link to Appium logs

Create a [GIST](https://gist.github.com/vsadineni1/1b93daca104b56b66ae820d4535fd33e)

**Comment by KazuCocoa** [comment]
What command did you send?

```
[HTTP] --> POST /wd/hub/session/e2248fb5-ba63-4b5a-bce3-b2c211c9b1f8/execute/sync
[HTTP] {"script":"return (function(){return function(){var k=this;function l(a){return void 0!==a}function m(a){return\"string\"==typeof a}function aa(a,b){a=a.split(\".\");var c=k;a[0]in c||!c.execScript||c.execScript(\"var \"+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&l(b)?c[d]=b:c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}}\nfunction ba(a){var b=typeof a;if(\"object\"==b)if(a){if(a instanceof Array)return\"array\";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(\"[object Window]\"==c)return\"object\";if(\"[object Array]\"==c||\"number\"==typeof a.length&&\"undefined\"!=typeof a.splice&&\"undefined\"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable(\"splice\"))return\"array\";if(\"[object Function]\"==c||\"undefined\"!=typeof a.call&&\"undefined\"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable(\"call\"))return\"function\"}else return\"null\";\nelse if(\"function\"==b&&\"undefined\"==typeof a.call)return\"object\";return b}function ca(a,b,c){return a.call....
[debug] [W3C (e2248fb5)] Calling AppiumDriver.execute() with args: ["return (function(){return function(){var k=this;function l(a){return void 0!==a}function m(a){return\"string\"==typeof a}function aa(a,b){a=a.split(\".\");var c=k;a[0]in c||!c.execScript||c.execScript(\"var \"+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&l(b)?c[d]=b:c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}}\nfunction ba(a){var b=typeof a;if(\"object\"==b)if(a){if(a instanceof Array)return\"array\";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(\"[object Window]\"==c)return\"object\";if(\"[object Array]\"==c||\"number\"==typeof a.length&&\"undefined\"!=typeof a.splice&&\"undefined\"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable(\"splice\"))return\"array\";if(\"[object Function]\"==c||\"undefined\"!=typeof a.call&&\"undefined\"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable(\"call\"))return\"function\"}else return\"null\";\nelse if(\"function\"==b&&\"undefined\"==typeof a.call)return\"object\";return b}function ca(a,b,c){return a.call.apply(a.b...
[debug] [XCUITest] Executing command 'execute'
[debug] [W3C (e2248fb5)] Encountered internal error running command: NotImplementedError: Method is not implemented
[debug] [W3C (e2248fb5)]     at XCUITestDriver.execute (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/execute.js:13:11)
[debug] [W3C (e2248fb5)]     at commandExecutor (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:334:9)
[debug] [W3C (e2248fb5)]     at /usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:129:12
[debug] [W3C (e2248fb5)]     at AsyncLock._promiseTry (/usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:253:31)
[debug] [W3C (e2248fb5)]     at exec (/usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:128:9)
[debug] [W3C (e2248fb5)]     at AsyncLock.acquire (/usr/local/lib/node_modules/appium/node_modules/async-lock/lib/index.js:144:3)
[debug] [W3C (e2248fb5)]     at XCUITestDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:347:39)
[debug] [W3C (e2248fb5)]     at XCUITestDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:730:24)
[debug] [W3C (e2248fb5)]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:547:36)
[debug] [W3C (e2248fb5)]     at runMicrotasks (<anonymous>)
[debug] [W3C (e2248fb5)]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[debug] [W3C (e2248fb5)]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:297:21)
[HTTP] <-- POST /wd/hub/session/e2248fb5-ba63-4b5a-bce3-b2c211c9b1f8/execute/sync 405 9 ms - 1387
[HTTP]
```

So far, execute_script to native context only expects https://appium.io/docs/en/commands/mobile-command/
I guess you sent non-mobile commands to the native context with execute script command. Then, the error is expected.
https://appium.io/docs/en/commands/web/execute/

error:
https://github.com/appium/appium-xcuitest-driver/blob/aacdd7338a0f1aa77252554d75d93370095c66d1/lib/commands/execute.js#L13

**Comment by mykola-mokhnach** [comment]
Closed as not an issue. also, no response
