### ISSUE TITLE
Button not enabling after Field Validations

### ISSUE THREAD

**Issue by tpasinetti** [appium/appium#15617]
## The problem

I am automating a registration screen and when the user has entered all required fields, the continue button becomes enabled. 
On Android running through Emulator or on real device the button does not become enabled, but when i perform the same thing manually on the emulator or via the appium inspector, it works fine, is this an appium issue or? Everything also works fine for iOS.

Appium can tap/click the element but because the button is greyed out, it doesn't take me to the next screen.

## Environment
Appium v 1.19.1

**Comment by mykola-mokhnach** [comment]
It could be that this buttons reacts to appropriate events from the input field, which are not being triggered while using the automated sendText API. You could try to enter the text using [W3C Actions](https://appiumpro.com/editions/46-sending-arbitrary-keystrokes-with-the-actions-api) or using `mobile: type` extension as a possible workaround. If that still does not work then consider talking to your app developers as there is nothing more that could be done on Appium side to address that.

**Comment by tpasinetti** [comment]
Thank you, I will try those options.
