### ISSUE TITLE
DeprecationWarning  mjpeg-server

### ISSUE THREAD

**Issue by stephenjg24-git** [appium/appium#15610]
info AppiumDoctor Appium Doctor v.1.16.0
info AppiumDoctor ### Diagnostic for necessary dependencies starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: /Users/............/.nvm/versions/node/v16.4.0/bin/node
info AppiumDoctor  ✔ Node version is 16.4.0
info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ Xcode Command Line Tools are installed in: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ DevToolsSecurity is enabled.
info AppiumDoctor  ✔ The Authorization DB is set up properly.
info AppiumDoctor  ✔ Carthage was found at: /usr/local/bin/carthage. Installed version is: 0.38.0
info AppiumDoctor  ✔ HOME is set to: /Users/............
info AppiumDoctor  ✔ ANDROID_HOME is set to: /Users/............/Library/Android/sdk
info AppiumDoctor  ✔ JAVA_HOME is set to: /Users/............/.jenv/versions/1.8.0.292
info AppiumDoctor    Checking adb, android, emulator
info AppiumDoctor      'adb' is in /Users/............/Library/Android/sdk/platform-tools/adb
info AppiumDoctor      'android' is in /Users/............/Library/Android/sdk/tools/android
info AppiumDoctor      'emulator' is in /Users/............/Library/Android/sdk/emulator/emulator
info AppiumDoctor  ✔ adb, android, emulator exist: /Users/............/Library/Android/sdk
info AppiumDoctor  ✔ 'bin' subfolder exists under '/Users/............/.jenv/versions/1.8.0.292'
info AppiumDoctor ### Diagnostic for necessary dependencies completed, no fix needed. ###
info AppiumDoctor 
info AppiumDoctor ### Diagnostic for optional dependencies starting ###
info AppiumDoctor  ✔ opencv4nodejs is installed at: /Users/............/.nvm/versions/node/v16.4.0/lib. Installed version is: 5.6.0
info AppiumDoctor  ✔ ffmpeg is installed at: /usr/local/bin/ffmpeg. ffmpeg version 4.4 Copyright (c) 2000-2021 the FFmpeg developers
info AppiumDoctor  ✔ mjpeg-consumer is installed at: /Users/............/.nvm/versions/node/v16.4.0/lib. Installed version is: 2.0.0
info AppiumDoctor  ✔ set-simulator-location is installed
info AppiumDoctor  ✔ idb and idb_companion are installed
info AppiumDoctor  ✔ applesimutils is installed at: /usr/local/bin/applesimutils. Installed versions are: applesimutils 0.9.2
info AppiumDoctor  ✔ ios-deploy is installed at: /Users/............/.nvm/versions/node/v16.4.0/bin/ios-deploy. Installed version is: 1.11.4
info AppiumDoctor  ✔ bundletool.jar is installed at: /Users/............/Library/Android/sdk/bundle-tool/bundletool.jar
info AppiumDoctor  ✔ gst-launch-1.0 and gst-inspect-1.0 are installed at: /usr/local/bin/gst-launch-1.0 and /usr/local/bin/gst-inspect-1.0
info AppiumDoctor ### Diagnostic for optional dependencies completed, no fix possible. ###
info AppiumDoctor 
info AppiumDoctor Everything looks good, bye!
info AppiumDoctor 

When I launch appium I am getting this message.

(node:6668) [DEP0128] DeprecationWarning: Invalid 'main' field in '/Users/......./.nvm/versions/node/v16.4.0/lib/node_modules/appium/node_modules/mjpeg-server/package.json' of './lib/mpegserver'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)

I then ran ..... this is the package with in appium

node --trace-deprecation /Users/stephen.lichtenberg/.nvm/versions/node/v16.4.0/lib/node_modules/appium/node_modules/mjpeg-server
(node:6772) [DEP0128] DeprecationWarning: Invalid 'main' field in '/Users/......./.nvm/versions/node/v16.4.0/lib/node_modules/appium/node_modules/mjpeg-server/package.json' of './lib/mpegserver'. Please either fix that or report it to the module author
    at tryPackage (node:internal/modules/cjs/loader:358:15)
    at Function.Module._findPath (node:internal/modules/cjs/loader:560:18)
    at resolveMainPath (node:internal/modules/run_main:15:25)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:73:24)
    at node:internal/main/run_main_module:17:47

I then  installed the package outside of the appium packages. 

node --trace-deprecation /Users/........./.nvm/versions/node/v16.4.0/lib/node_modules/mjpeg-server
(node:6903) [DEP0128] DeprecationWarning: Invalid 'main' field in '/Users/stephen.lichtenberg/.nvm/versions/node/v16.4.0/lib/node_modules/mjpeg-server/package.json' of './lib/mpegserver'. Please either fix that or report it to the module author
    at tryPackage (node:internal/modules/cjs/loader:358:15)
    at Function.Module._findPath (node:internal/modules/cjs/loader:560:18)
    at resolveMainPath (node:internal/modules/run_main:15:25)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:73:24)
    at node:internal/main/run_main_module:17:47

I also sent the info the mjpeg-server team as well. 

is node v16.4.0not stable for appium?  do i need to move to a more stable version?

**Comment by mykola-mokhnach** [comment]
Duplicate of https://github.com/appium/appium/issues/15320

**Comment by stephenjg24-git** [comment]
@mykola-mokhnach I reported this to https://github.com/gluxon/node-mjpeg-server. this morning and they have corrected the package and this is resolved.

if  you update this package in the ...../node_modules/appium/node_modules. this will be resolved.

I did this and it corrected the issue.

However I now see that several packages are flaged by npm audit 

\###############\
npm audit
# npm audit report

axios  <0.21.1
Severity: high
Server-Side Request Forgery - https://npmjs.com/advisories/1594
fix available via `npm audit fix`
node_modules/appium-flutter-driver/node_modules/axios
  appium-base-driver  5.8.1 - 7.3.2 || 8.0.0-beta.0
  Depends on vulnerable versions of axios
  node_modules/appium-flutter-driver/node_modules/appium-base-driver

glob-parent  <5.1.2
Severity: moderate
Regular expression denial of service - https://npmjs.com/advisories/1751
fix available via `npm audit fix --force`
Will install gulp@3.9.1, which is a breaking change
node_modules/chokidar/node_modules/glob-parent
node_modules/glob-stream/node_modules/glob-parent
  chokidar  1.0.0-rc1 - 2.1.8
  Depends on vulnerable versions of glob-parent
  node_modules/chokidar
    glob-watcher  >=3.0.0
    Depends on vulnerable versions of chokidar
    node_modules/glob-watcher
      gulp  >=4.0.0
      Depends on vulnerable versions of glob-watcher
      node_modules/gulp
        appium-gulp-plugins  >=3.0.0
        Depends on vulnerable versions of gulp
        Depends on vulnerable versions of gulp-mocha
        node_modules/appium-gulp-plugins
        gulp-debug  >=4.0.0
        Depends on vulnerable versions of gulp
        node_modules/gulp-debug
        gulp-mocha  >=7.0.0
        Depends on vulnerable versions of gulp
        node_modules/gulp-mocha
  glob-stream  >=5.3.0
  Depends on vulnerable versions of glob-parent
  node_modules/glob-stream
    vinyl-fs  >=2.4.2
    Depends on vulnerable versions of glob-stream
    node_modules/vinyl-fs

minimist  <0.2.1 || >=1.0.0 <1.2.3
Prototype Pollution - https://npmjs.com/advisories/1179
No fix available
node_modules/appium-tizen-driver/node_modules/minimist
  mkdirp  0.4.1 - 0.5.1
  Depends on vulnerable versions of minimist
  node_modules/appium-tizen-driver/node_modules/mkdirp
    @jimp/core  <=0.9.6-canary.860.700.0
    Depends on vulnerable versions of mkdirp
    node_modules/appium-tizen-driver/node_modules/@jimp/core
      @jimp/custom  <=0.8.6-canary.818.495.0 || 0.9.2-canary.815.538.0 - 0.9.3-canary.825.599.0 || 0.9.4-canary.832.606.0 - 0.9.4-canary.845.627.0 || 0.9.6-canary.857.681.0 - 0.9.6-canary.860.700.0
      Depends on vulnerable versions of @jimp/core
      node_modules/appium-tizen-driver/node_modules/@jimp/custom
        jimp  0.3.6-alpha.5 - 0.8.6-canary.818.495.0 || 0.9.2-canary.815.538.0 - 0.9.3-canary.825.599.0 || 0.9.4-canary.832.606.0 - 0.9.4-canary.845.627.0 || 0.9.6-canary.857.681.0 - 0.9.6-canary.860.700.0
        Depends on vulnerable versions of @jimp/custom
        node_modules/appium-tizen-driver/node_modules/jimp
          appium-tizen-driver  *
          Depends on vulnerable versions of jimp
          Depends on vulnerable versions of yargs
          node_modules/appium-tizen-driver

yargs-parser  <=13.1.1 || 14.0.0 - 15.0.0 || 16.0.0 - 18.1.1
Prototype Pollution - https://npmjs.com/advisories/1500
No fix available
node_modules/appium-tizen-driver/node_modules/yargs-parser
node_modules/gulp-cli/node_modules/yargs-parser
  yargs  4.0.0-alpha1 - 12.0.5 || 14.1.0 || 15.0.0 - 15.2.0
  Depends on vulnerable versions of yargs-parser
  node_modules/appium-tizen-driver/node_modules/yargs
  node_modules/gulp-cli/node_modules/yargs
    appium-tizen-driver  *
    Depends on vulnerable versions of jimp
    Depends on vulnerable versions of yargs
    node_modules/appium-tizen-driver
    gulp-cli  >=2.0.0
    Depends on vulnerable versions of yargs
    node_modules/gulp-cli

20 vulnerabilities (9 low, 9 moderate, 2 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

**Comment by mykola-mokhnach** [comment]
Releases are shrink-wrapped, so we cannot change anything there. You could check appium@beta though - it always contains the latest and the greatest module versions.
