### ISSUE TITLE
The desired should not include both of an 'appPackage' and a 'browserName'

### ISSUE THREAD

**Issue by AMNA25** [appium/appium#15621]
## The problem
Having the error "The desired should not include both of an 'appPackage' and a 'browserName'" while using both android app and android web browser.

## Environment

* Appium version that exhibits the issue: 1.19.1
* Desktop OS/version used to run Appium: Windows
* Node.js version (unless using Appium.app|exe): 12.18.3
* Mobile platform/version under test: Android v10
* Real device or emulator/simulator: Real device

## Details

I want to login the android app through a magic link.
When I enter an email in input field on my app, it takes me to the new mail (gmail) where a magic link is received and when that link is clicked, it redirects me to the app. I want to automate this flow. I have been able to reach to the magic link but unable to click it to login. One solution that I understand is that I should copy that link and paste it on mobile web browser (Chrome) then it will automatically login the app. But the error I'm receiving is "The desired should not include both of an 'appPackage' and a 'browserName'"

## Link to Appium logs

https://gist.github.com/AMNA25/f4fd1fd1e174f335144569c858d16380

## Desired Capabilities

appium.hub = http://127.0.0.1:4723/wd/hub
appium.automationName = uiautomator2
appium.platformName = Android
appium.deviceName  = Redmi 9
appium.app = D:\\android apks\\app-release (1).apk
appium.appPackage = 
appium.appActivity = 
#appium.browserName = Chrome
appium.platformVersion = 10

**Comment by mykola-mokhnach** [comment]
> [debug] [35m[BaseDriver][39m   "alwaysMatch": {
> [debug] [35m[BaseDriver][39m     "browserName": "Chrome",
> [debug] [35m[BaseDriver][39m     "appium:hub": "http://127.0.0.1:4723/wd/hub",
> [debug] [35m[BaseDriver][39m     "appium:loggingPrefs": {},
> [debug] [35m[BaseDriver][39m     "platformName": "android",
> [debug] [35m[BaseDriver][39m     "appium:app": "D:\\android apks\\app-release (1).apk",
> [debug] [35m[BaseDriver][39m     "appium:appActivity": "",
> [debug] [35m[BaseDriver][39m     "appium:appPackage": "",
> [debug] [35m[BaseDriver][39m     "appium:automationName": "uiautomator2",
> [debug] [35m[BaseDriver][39m     "appium:deviceName": "Redmi 9",
> [debug] [35m[BaseDriver][39m     "appium:platformVersion": "10"
> [debug] [35m[BaseDriver][39m   },

This behaviour is expected. The session must either be initialised as native or a web view one. It cannot include both.

I don't see a reason to start a new session there though.

**Comment by jlipps** [comment]
If you want to load Chrome as a next step in your test, then just launch it the way a user would, or by using startActivity. Don't use the browserName cap.
