### ISSUE TITLE
./Scripts/bootstrap.sh: No such file or directory

### ISSUE THREAD

**Issue by RufusA1** [appium/appium#15623]
## The problem

I was able to run the commands 1 & 2 below successfully but was getting this "./Scripts/bootstrap.sh: No such file or directory" error upon running command 3.

1. cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/webdriveragent
2. mkdir -p Resources/WebDriverAgent.bundle
3. sh ./Scripts/bootstrap.sh -d

## Environment

* Appium version: appium -v1.21.0
* Desktop OS/version: macOS Big Sur/Version 11.2.3
* Node.js version: node -v16.4.2
* Npm: npm -v7.19.1
* Mobile platform/version under test: iOS/XS Max

Please who can help with this issue?

**Comment by RufusA1** [comment]
I also run this: sh ./Scripts/build.sh -d and i got the below attached response:

<img width="528" alt="Screenshot 2021-07-09 at 15 05 40" src="https://user-images.githubusercontent.com/66271051/125090357-280d3500-e0c7-11eb-8109-19228669863a.png">

**Comment by mykola-mokhnach** [comment]
Appium 1.21 does not need to run bootstrap anymore. The bundled WebDriverAgent already includes all the necessary dependencies there

**Comment by KazuCocoa** [comment]
Our doc https://appium.io/docs/en/drivers/ios-xcuitest-real-devices/ also addresses the script is for below 1.20 versions.

**Comment by RufusA1** [comment]
Thank you @KazuCocoa and @mykola-mokhnach
