### ISSUE TITLE
ios toast can't get

### ISSUE THREAD

**Issue by tianyao1111** [appium/appium#15629]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:1.19.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:macOS 11.2.3
* Node.js version (unless using Appium.app|exe):14.15
* Npm or Yarn package manager:npm
* Mobile platform/version under test:ios 14.0.1
* Real device or emulator/simulator:real
* Appium CLI or Appium.app|exe: Appium.exe

## Details
I want to use appium to get the content of the toast pop-up window of ios, but I can’t get it
Get toast code：
```
def get_toast_msg(driver,value):
    '''获取toast弹窗内容'''
    tost_element = (By.IOS_PREDICATE,'name CONTAINS "'+value+'"')
    res=WebDriverWait(driver,global_wait,0.01).until(EC.presence_of_element_located(tost_element)).text.strip()
    return res
```
Note：
1. toast appears for about 1 second。
2. I asked the front-end ios developer, the front-end uses the SVProgressHUD third-party library。
3. The notification permission of the app under test is also turned on。
4. The app to be tested is an enterprise-level certificate app

## Link to Appium logs

my python script code output：
```
E
======================================================================
ERROR: test_case_01 (paramunittest.ET_TB_1LF_case_02_0)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\14221\Desktop\项目\etong LJG IOS\public\MyTestCase.py", line 23, in testPartExecutor
    yield
  File "C:\Users\14221\Desktop\项目\etong LJG IOS\public\MyTestCase.py", line 136, in run
    testMethod()
  File "C:\Users\14221\Desktop\项目\etong LJG IOS\public\common2.py", line 13, in wrapper
    func(self)
  File "ET_TB_1LF_case_02.py", line 90, in test_case_01
    self.assertTrue(RSP.test_share_posters(self.driver,type1=1))
  File "C:\Users\14221\Desktop\项目\etong LJG IOS\test_page\TBRiskSharePage.py", line 18, in test_share_posters
    return get_toast_msg(driver,'成功保存到相册') =='成功保存到相册'
  File "C:\Users\14221\Desktop\项目\etong LJG IOS\public\common.py", line 558, in get_toast_msg
    res=WebDriverWait(driver,global_wait,0.001).until(lambda x:x.find_element_by_ios_predicate(message))
  File "C:\Users\14221\Anaconda3\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


----------------------------------------------------------------------
Ran 1 test in 111.317s

FAILED (errors=1)
```

## Code To Reproduce Issue [ Good To Have ]
```
def get_toast_msg(driver,value):
    '''获取toast弹窗内容'''
    tost_element = (By.IOS_PREDICATE,'name CONTAINS "'+value+'"')
    res=WebDriverWait(driver,global_wait,0.01).until(EC.presence_of_element_located(tost_element)).text.strip()
    return res

def test_share_posters(self,driver,type1=1):
		'''分享海报'''
		if type1==1:
			get_element(driver,'xpath','//XCUIElementTypeButton[@name="NMShareSaveLocal"]').click()
			return get_toast_msg(driver,'成功保存到相册') =='成功保存到相册'

		elif type1==2:
			get_element(driver,'xpath','//XCUIElementTypeButton[@name="MEShareFriend"]').click()
			get_element(driver,'xpath','//XCUIElementTypeButton[@name="发表"]').click()
			return True

		else:
			get_element(driver,'xpath','//XCUIElementTypeButton[@name="NMShareWechat"]').click()
			get_element(driver,'xpath','//XCUIElementTypeSearchField[@name="搜索"]').send_keys('文件传输助手')
			get_element(driver,'xpath','//XCUIElementTypeOther[@name="联系人"]/../XCUIElementTypeCell/XCUIElementTypeStaticText[@name="文件传输助手"]').click()
			get_element(driver,'xpath','//XCUIElementTypeButton[@name="发送"]').click()
			try:
				get_element(driver,'xpath','//XCUIElementTypeStaticText[@name="已发送"]')
			except:
				flag=False
			else:
				flag=True
			get_element(driver,'xpath','//XCUIElementTypeStaticText[@name="返回人保e通"]').click()
			
			return flag

```

**Comment by mykola-mokhnach** [comment]
Is the toast element itself accessible/visible in the page source? This also could be a race condition issue, so I would try to aks the developer to set a longer toast timeout for testing purposes

**Comment by tianyao1111** [comment]
> Is the toast element itself accessible/visible in the page source? This also could be a race condition issue, so I would try to aks the developer to set a longer toast timeout for testing purposes

I compared the difference between SVProgressHUD's toast and ordinary toast in the web source code xml。
Ordinary toast in the webpage source xml：
```
<XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" accessible="false" x="0" y="0" width="414" height="736" index="1">
      <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="请输入正确的车牌号" name="请输入正确的车牌号" label="请输入正确的车牌号" enabled="true" visible="true" accessible="false" x="152" y="361" width="111" height="15" index="0"/>
    </XCUIElementTypeOther>
```
SVProgressHUD's toast in the web source code xml：
`<XCUIElementTypeOther type="XCUIElementTypeOther" name="SVProgressHUD" label="Loading" enabled="true" visible="true" accessible="true" x="0" y="0" width="414" height="736" index="0"/>`

SVProgressHUD's toast has no text message

**Comment by mykola-mokhnach** [comment]
The way elements are structured in the hierarchy is controlled by XCTest. There's nothing we could do about it from Appium side

**Comment by tianyao1111** [comment]
> 另一种做法是使用应用程序的测试版本，而不是测试，而是使用标准警报，因为它们将保留在屏幕上，直到被调查和解除。



> 应用程序的测试版本

I can’t get a test version of the app, I’m trying to use the method'find_element_by_image' to get

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing more we can help there. Closing
