### ISSUE TITLE
Android: Simulator crash while running the group of testcases.

### ISSUE THREAD

**Issue by karnan008** [appium/appium#15627]
## The problem

1. Appium setup for android simulator is fine.
2. Can able to run the testcases fine in simulator.
3. But at some point simulator automatically crashed.

## Environment

* Appium version (or git revision) that exhibits the issue:  **V1.21.0**
* Desktop OS/version used to run Appium: **Windows 10 Pro**
* Mobile platform/version under test: **Android**
* Real device or emulator/simulator: **Simulator**
* Appium CLI or Appium.app|exe:  **Appium.app|exe**

## Details

While the group of testcases running - simulator automatically crashed and then test failed.

**Comment by mykola-mokhnach** [comment]
I'm not sure how Appium itself could be related to the emulator crash.  
Also, we cannot help nothing without the detailed logs

**Comment by mykola-mokhnach** [comment]
Closed because of no response
