### ISSUE TITLE
Not able to launch test app on iOS Simulator 

### ISSUE THREAD

**Issue by ZindalP** [appium/appium#15622]
## The problem

[Xcode 13 Beta, iOS 15] Not able to launch test app on iOS Simulator while doing testing.

## Environment

* Appium version : 1.21.0
* Desktop OS/version used to run Appium: Mac OS BigSur 11.4
* Mobile platform/version under test: iOS 15
* Real device or emulator/simulator: iOS Simulator
* Xcode version : Xcode 13 Beta

## Link to Appium logs

https://gist.github.com/ZindalP/84f747b77885a1504b4c8750408167ce

**Comment by mykola-mokhnach** [comment]
Appium 1.21 does not support Xcode 13. Try appium@beta
