### ISSUE TITLE
Starting a (Multi) Touch action with a delay throws error

### ISSUE THREAD

**Issue by Errors4l** [appium/appium#15624]
## The problem

When the first action of a TouchAction is a delay, the driver throws an error indicating the `touch` field is not present.

## Environment

* Appium version (or git revision) that exhibits the issue:  v1.21.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Windows 10 (19042.1052)
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Android 10.0, OnePlus 6T
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium.exe

## Details

Because of the delays between sending touch events and them happening on screen, I was hoping to buffer multiple touches in a single multi touch call. I'm not sure if this is possible by any means, but my attempts thus far have failed.

Having the first action (of a TouchAction in a MultiTouchAction) be a wait throws the following (Java) error:

```
org.openqa.selenium.InvalidArgumentException: java.lang.IllegalArgumentException: TouchGestureModel: The mandatory field 'touch' is not present in JSON
```

I've reduced the delay by setting `settings[trackScrollEvents]` to `false`, but it still not ideal. My idea was that by bundling touches in a single message, the delay of sending the message from Java > server > phone would be eliminated.

Any (alternative) solutions to have better control over the timing of multi touches would be much appreciated.

## Link to Appium logs

https://gist.github.com/Errors4l/92f321ca84fae27f2ce515742de69c1b

## Code To Reproduce Issue

https://gist.github.com/Errors4l/957228ce6794a8c5d0f3544f8e4a24df

**Comment by mykola-mokhnach** [comment]
Consider using W3C Actions. The current interface is not maintained anymore and considered outdated.

**Comment by mykola-mokhnach** [comment]
Some additional info: https://appiumpro.com/editions/29-automating-complex-gestures-with-the-w3c-actions-api

**Comment by Errors4l** [comment]
> Some additional info: https://appiumpro.com/editions/29-automating-complex-gestures-with-the-w3c-actions-api

Seems very promising for my use case. The example given works out of the box so I'll do some experimenting with it. Thank you!

From the page on actions (http://appium.io/docs/en/commands/interactions/actions/) it seems like a `pause` interaction is also supported, but I can't find the right class/method in Java to create a `pause` `Interaction` to add to the `Sequence`. Do you happen to know how to initiate it? I'm assuming `Sequence.wait(int ms)` is the wrong way to go.
