### ISSUE TITLE
Multiple Nested views in Appium on iOS react-native app

### ISSUE THREAD

**Issue by azetaa** [appium/appium#15635]
## The problem

When trying to load my app into appium and grab element id's, the hierarchal views load and replicate several times over, making searching for elements unbearable/impractical if not impossible. 
![ezgif-6-6c0d389fa3c5](https://user-images.githubusercontent.com/66332691/125813521-5f927432-a0bb-41fa-a4f9-8223f5ca1867.gif)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable): unsure
* Desktop OS/version used to run Appium: Big Sur 11.3.1
* Npm or Yarn package manager: Yarn
* Mobile platform/version under test: iOS 14.4
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium App

**Comment by jlipps** [comment]
This is just how React Native builds out the accessibility information on the element hierarchy by default. There's nothing Appium can do about it. You can adjust the accessibility labels on your RN elements to fix it if you want.

**Comment by azetaa** [comment]
How do i do that? or relay that information to our developer who works on this?

**Comment by jlipps** [comment]
https://reactnative.dev/docs/accessibility#accessibilitylabel
