### ISSUE TITLE
Add socket.io interface for apps to communicate with appium server in real time

### ISSUE THREAD

**Issue by penguinho** [appium/appium#1563]
I was working on integrating the doctor into the .app this weekend and in doing so I had to make a an interface for the doctor to talk to the .app in realtime. I ending up using socket.io and it works pretty well. I was thinking it would be great if we could do the same for the server, so that we could have better integration with the standalone apps.

For the doctor I made a basic protocol with 5 types of events.

1.) welcome - connection to the server was successful
2.) log - here's a line the server posted to the log
3.) question (later renamed alert) - ask the user this question with these choices
4.) answer - answer to a question that the server asked
5.) done - the server is shutting down

If we create a protocol like this this would allow us to better organize log data than just posting colored text to a window. (e.g. toggle verbose on/off, sort by entry type, etc.) The app could also receive states that we aren't able to convey write now, and execute functions on the node server that we don't currently expose via the JSON-wire protocol.

**Comment by jlipps** [comment]
closing as this is sort of a moot point. JSONWP seems to work fine for the GUIs.
