### ISSUE TITLE
JAVA_HOME Path error

### ISSUE THREAD

**Issue by manjugb** [appium/appium#15631]
## The problem

I was trying set JAVA_HOME path in ubuntu 20.04 , getting an error "WARN AppiumDoctor  ✖ Cannot check $JAVA_HOME requirements since the environment variable itself is not set" and even it was already set Java Path

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: android 
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: appium cli

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.
[appium_doctor_logs.txt](https://github.com/appium/appium/files/6813692/appium_doctor_logs.txt)

**Comment by mykola-mokhnach** [comment]
You should make sure the JAVA_HOME environment variable is configured properly for you system environment.

Closed as not an issue. Kindly use Appium forum for questions.
