### ISSUE TITLE
BaseDriver class is not annotated for 3rd party consumption

### ISSUE THREAD

**Issue by jlipps** [appium/appium#15636]
With Appium 2.0 we want people to be building off of BaseDriver, but it is not clear what is public, protected, or private from that class. This makes it hard to know what a breaking change is, or to generate helpful developer docs.

**Comment by boneskull** [comment]
This is fuzzy, but here are my thoughts on it.  

For an API to be public, these should be true:

1. The API is documented. Any documented method, class, etc., on `appium.io` should be considered public.
2. This is not entirely sufficient, as often developers will not refer to this and instead rely on type information, intellisense, and docstrings.  Therefore, anything exported should be either explicitly annotated as public, private, or both.   

JSDoc itself assumes everything not marked `@private` is public.  

We could, in the future, leverage Node.js' package exports to further restrict the modules that consumers can use directly and/or leverage private fields and methods.

**Comment by jlipps** [comment]
👍

**Comment by boneskull** [comment]
As long as we're on the subject, I strongly recommend using [docstrings understandable by TypeScript](https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html).  Paired with a TS language server, this can provide TS-levels of inspection, refactoring, and contextual information...without actually needing to write TS.

**Comment by jlipps** [comment]
I believe this issue is resolved, at least as intended, given that there are now types exported for BaseDriver
