### ISSUE TITLE
Unable to use 

### ISSUE THREAD

**Issue by heychirag** [appium/appium#15634]
## The problem

I am unable to use `UiObject` selector. Appium appends my command to `UiSelector` and throws `UiSelector has no 'new UiObject' method`.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: macOS 11.4
* Node.js version (unless using Appium.app|exe): Appium.app
* Npm or Yarn package manager: Npm
* Mobile platform/version under test: Android 11
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium.app

## Details

I am trying to use `UiObject` selector part of UiAutomator (https://developer.android.com/reference/androidx/test/uiautomator/UiObject)

But appium appends my command to `new UiSelector()` (check below). This is something I don't want. I want to reference an object and then use `UiObject`'s `getChild` method to select another element.

## Link to Appium logs

```
[elements("-android uiautomator","new UiObject()")] Error response status: 32, , InvalidSelector - Argument was an invalid selector (e.g. XPath/CSS). Selenium error: Could not parse selector expression `new UiSelector().new UiObject()`: UiSelector has no `new UiObject` method
```

## Code To Reproduce Issue [ Good To Have ]

Locator Strategy: UIAutomator
```
new UiObject()
```

**Comment by mykola-mokhnach** [comment]
Unfortunately such functionality is not supported, so the error is expected.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
