### ISSUE TITLE
[iOS] Contact permission popup does not display

### ISSUE THREAD

**Issue by sonnh-est** [appium/appium#15632]
## The problem

The app will require access Contact after click a button, it worked when doing manually but permission popup does not display when doing by appium

## Environment

* Appium version : 1.20.0
* iOS : 14

## Link to Appium logs

https://gist.github.com/sonnh-est/ec3b6a3e8b25d4dccbfb719f5dc59f65

**Comment by mykola-mokhnach** [comment]
I don't think this has anything to do with Appium. Try to fetch the app logs and check the returned error code from the API, which is supposed to invoke the Contacts access permission

**Comment by sonnh-est** [comment]
Thanks @mykola-mokhnach for your reply,

In fact, permission popup does display when I perform manually

We have this log in appium.log, however I'm not familiar with the log so could you triple check?
`"id": 220647,
        "time": "09:11:00",
        "level": "VERBOSE",
        "message": "[IOSDeviceLog] Jul 14 02:11:00 iPhone SpringBoard(SpringBoard)[61] <Notice>: Received request to activate alertItem: <SBUserNotificationAlert: 0x12b22a9d0; title: “XXX.stag” Would Like to Access Your Contacts; source: tccd; pid: 42>"
`

**Comment by KazuCocoa** [comment]
> In fact, permission popup does display when I perform manually

how about doing the same step after establishing an appium session?
Appium session is XCTest session via xcodebuild. Potentially the session affects some behavior. (But in the case, only Apple can change the behavior)

**Comment by sonnh-est** [comment]
I have no idea on that since I ran my test cases on saucelabs so cannot create appium session then doing step manually. It worked on my locale device.

**Comment by KazuCocoa** [comment]
I see. If this issue happens only on SauceLabs, I think asking for their support is better.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
