### ISSUE TITLE
Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started is displayed and AUT is closed  

### ISSUE THREAD

**Issue by YenikeRaghuRam** [appium/appium#15643]
## The problem

Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started is displayed and AUT is closed while Appium Desktop is trying to take screenshot(or load elements)

## Environment

* Appium version (or git revision) that exhibits the issue:1.21.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:MacOS BigSur
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:iPhone 14.6
* Real device or emulator/simulator:Real Device
* Appium CLI or Appium.app|exe:Appium.app

## Details

Appium.app desktop app while taking screenshot , AUT is closed and error is displayed

## Link to Appium logs

[debug] [35m[MJSONWP (656069b6)][39m Calling AppiumDriver.getSession() with args: ["656069b6-928e-4052-b654-542468136075"]
[debug] [35m[XCUITest][39m Executing command 'getSession'
[info] [35m[XCUITest][39m Merging WDA caps over Appium caps for session detail response
[debug] [35m[MJSONWP (656069b6)][39m Responding to client with driver.getSession() result: {"udid":"00008030-001C4D243AA1802E","automationName":"XCUITest","bundleId":"com.carriertransicold.containerLINK","clearSystemFiles":true,"deviceName":"Srinivas’s iPhone","newCommandTimeout":0,"platformName":"iOS","platformVersion":"14.6","showXcodeLog":true,"wdaConnectionTimeout":2400000,"connectHardwareKeyboard":true,"device":"iphone","browserName":"ContainerLINK™","sdkVersion":"14.6","CFBundleIdentifier":"com.carriertransicold.containerLINK","pixelRatio":2,"statBarHeight":48,"viewportRect":{"left":0,"top":96,"width":828,"height":1696}}
[info] [35m[HTTP][39m [37m<-- GET /wd/hub/session/656069b6-928e-4052-b654-542468136075 [39m[32m200[39m [90m2 ms - 619[39m
[info] [35m[HTTP][39m [90m[39m
[info] [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/session/656069b6-928e-4052-b654-542468136075/window/current/size[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[MJSONWP (656069b6)][39m Calling AppiumDriver.getWindowSize() with args: ["current","656069b6-928e-4052-b654-542468136075"]
[debug] [35m[XCUITest][39m Executing command 'getWindowSize'
[debug] [35m[WD Proxy][39m Proxying [GET /window/size] to [GET http://127.0.0.1:8100/session/F84C2BB1-AD84-4CE3-BD44-AECFC5DFDF71/window/size] with no body
[error] [35m[Xcode][39m 2021-07-19 14:02:06.528156+0530 WebDriverAgentRunner-Runner[2712:1623950] Getting the most recent active application (out of 1 total items)
[error] [35m[Xcode][39m 
[error] [35m[Xcode][39m     t =  5426.78s Requesting snapshot of accessibility hierarchy for app with pid 2750
[error] [35m[Xcode][39m [debug] [35m[WD Proxy][39m Got response with status 200: {"value":{"width":414,"height":896},"sessionId":"F84C2BB1-AD84-4CE3-BD44-AECFC5DFDF71"}
[debug] [35m[MJSONWP (656069b6)][39m Responding to client with driver.getWindowSize() result: {"width":414,"height":896}
[info] [35m[HTTP][39m [37m<-- GET /wd/hub/session/656069b6-928e-4052-b654-542468136075/window/current/size [39m[32m200[39m [90m1052 ms - 98[39m
[info] [35m[HTTP][39m [90m[39m
[error] [35m[Xcode][39m 2021-07-19 14:02:07.527763+0530 WebDriverAgentRunner-Runner[2712:1623950] Getting the most recent active application (out of 1 total items)
[error] [35m[Xcode][39m 
[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/656069b6-928e-4052-b654-542468136075/execute[39m
[info] [35m[HTTP][39m [90m{"script":"mobile:getContexts","args":[]}[39m
[debug] [35m[MJSONWP (656069b6)][39m Calling AppiumDriver.execute() with args: ["mobile:getContexts",[],"656069b6-928e-4052-b654-542468136075"]
[debug] [35m[XCUITest][39m Executing command 'execute'
[debug] [35m[XCUITest][39m Getting list of available contexts
[debug] [35m[iOS][39m Retrieving contexts and views
[debug] [35m[XCUITest][39m Selecting by url: false 
[debug] [35m[RemoteDebugger][39m Sending connection key request
[debug] [35m[RemoteDebugger][39m Sending '_rpc_reportIdentifier:' message (id: 8): 'setConnectionKey'
[debug] [35m[RemoteDebugger][39m Sending to Web Inspector took 2ms
[debug] [35m[RemoteDebugger][39m Selecting application
[debug] [35m[RemoteDebugger][39m No applications currently connected.
[debug] [35m[XCUITest][39m No web frames found.
[debug] [35m[XCUITest][39m No webviews found in 2ms
[debug] [35m[MJSONWP (656069b6)][39m Responding to client with driver.execute() result: [{"id":"NATIVE_APP"}]
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session/656069b6-928e-4052-b654-542468136075/execute [39m[32m200[39m [90m8 ms - 93[39m
[info] [35m[HTTP][39m [90m[39m
[info] [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/session/656069b6-928e-4052-b654-542468136075/source[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[MJSONWP (656069b6)][39m Calling AppiumDriver.getPageSource() with args: ["656069b6-928e-4052-b654-542468136075"]
[debug] [35m[XCUITest][39m Executing command 'getPageSource'
[debug] [35m[WD Proxy][39m Matched '/source' to command name 'getPageSource'
[debug] [35m[WD Proxy][39m Proxying [GET /source] to [GET http://127.0.0.1:8100/session/F84C2BB1-AD84-4CE3-BD44-AECFC5DFDF71/source] with no body
[error] [35m[Xcode][39m 2021-07-19 14:02:07.576409+0530 WebDriverAgentRunner-Runner[2712:1623950] Getting the most recent active application (out of 1 total items)
[error] [35m[Xcode][39m 
[error] [35m[Xcode][39m 2021-07-19 14:02:07.576790+0530 WebDriverAgentRunner-Runner[2712:1623950] The following attributes were requested to be included into the XML: {(
[error] [35m[Xcode][39m     FBHeightAttribute,
[error] [35m[Xcode][39m     FBAccessibleAttribute,
[error] [35m[Xcode][39m     FBValueAttribute,
[error] [35m[Xcode][39m     FBVisibleAttribute,
[error] [35m[Xcode][39m     FBWidthAttribute,
[error] [35m[Xcode][39m     FBEnabledAttribute,
[error] [35m[Xcode][39m     FBTypeAttribute,
[error] [35m[Xcode][39m     FBYAttribute,
[error] [35m[Xcode][39m     FBLabelAttribute,
[error] [35m[Xcode][39m     FBIndexAttribute,
[error] [35m[Xcode][39m     FBXAttribute,
[error] [35m[Xcode][39m     FBNameAttribute
[error] [35m[Xcode][39m )}
[error] [35m[Xcode][39m 2021-07-19 14:02:07.576898+0530 WebDriverAgentRunner-Runner[2712:1623950] Waiting up to 2s until com.carriertransicold.containerLINK is in idle state (including animations)
[error] [35m[Xcode][39m     t =  5427.83s Wait for com.carriertransicold.containerLINK to idle
[error] [35m[Xcode][39m 
[error] [35m[Xcode][39m     t =  5427.83s Requesting snapshot of accessibility hierarchy for app with pid 2750
[error] [35m[Xcode][39m [error] [35m[Xcode][39m 2021-07-19 14:04:38.548952+0530 WebDriverAgentRunner-Runner[2712:1623950] Cannot take a snapshot with attribute(s) (
[error] [35m[Xcode][39m     "XC_kAXXCAttributeElementBaseType",
[error] [35m[Xcode][39m     "XC_kAXXCAttributeHasNativeFocus",
[error] [35m[Xcode][39m     "XC_kAXXCAttributeTruncatedValue",
[error] [35m[Xcode][39m     "XC_kAXXCAttributeViewControllerTitle",
[error] [35m[Xcode][39m     "XC_kAXXCAttributeUserTestingElements",
[error] [35m[Xcode][39m     "XC_kAXXCAttributeAutomationType",
[error] [35m[Xcode][39m     "XC_kAXXCAttributeBannerIsStickyAttribute",
[error] [35m[Xcode][39m     "XC_kAXXCAttributeIdentifier",
[error] [35m[Xcode][39m     "XC_kAXXCAttributeTraits",
[error] [35m[Xcode][39m     "XC_kAXXCAttributeFrame",
[error] [35m[Xcode][39m     "XC_kAXXCAttributeVerticalSizeClass",
[error] [35m[Xcode][39m     "XC_kAXXCAttributeViewControllerClassName",
[error] [35m[Xcode][39m     "XC_kAXXCAttributeIsUserInteractionEnabled",
[error] [35m[Xcode][39m     "XC_kAXXCAttributeLabel",
[error] [35m[Xcode][39m     "XC_kAXXCAttributeURL",
[error] [35m[Xcode][39m     "XC_kAXXCAttributeParent",
[error] [35m[Xcode][39m     "XC_kAXXCAttributeHorizontalSizeClass",
[error] [35m[Xcode][39m     "XC_kAXXCAttributePlaceholderValue",
[error] [35m[Xcode][39m     "XC_kAXXCAttributeElementType",
[error] [35m[Xcode][39m     "XC_kAXXCAttributeIsVisible"
[error] [35m[Xcode][39m ) of 'XCUIElementTypeAny' after 600.00 seconds
[error] [35m[Xcode][39m 2021-07-19 14:04:38.549114+0530 WebDriverAgentRunner-Runner[2712:1623950] This timeout could be customized via 'customSnapshotTimeout' setting
[error] [35m[Xcode][39m 2021-07-19 14:04:38.549189+0530 WebDriverAgentRunner-Runner[2712:1623950] Internal error: XCTPerformOnMainRunLoop work timed out after 60.0s
[error] [35m[Xcode][39m 2021-07-19 14:04:38.549268+0530 WebDriverAgentRunner-Runner[2712:1623950] Falling back to the default snapshotting mechanism for the element 'XCUIElementTypeAny' (some attribute values, like visibility or accessibility might not be precise though)
[error] [35m[Xcode][39m [error] [35m[Xcode][39m 2021-07-19 14:07:08.576537+0530 WebDriverAgentRunner-Runner[2712:1623950] Cannot retrieve element attribute(s) (
[error] [35m[Xcode][39m     "XC_kAXXCAttributeIsElement"
[error] [35m[Xcode][39m ). Original error: Error Domain=com.apple.dt.xctest.automation-support.error Code=11 "Accessibility error kAXErrorIPCTimeout from AXUIElementCopyMultipleAttributeValues for 2016" UserInfo={accessibility-error=-25216, NSLocalizedDescription=Accessibility error kAXErrorIPCTimeout from AXUIElementCopyMultipleAttributeValues for 2016}
[error] [35m[Xcode][39m [info] [35m[HTTP][39m [37m<-- POST /wd/hub/session/f80b4c3a-8fbc-470a-b614-7d1b95f4073d/elements [39m[32m-[39m [90m- ms - -[39m
[info] [35m[HTTP][39m [90m[39m
[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/f80b4c3a-8fbc-470a-b614-7d1b95f4073d/elements[39m
[info] [35m[HTTP][39m [90m{"using":"xpath","value":"(//XCUIElementTypeStaticText[@name=\"Select All\"])[1]"}[39m
[debug] [35m[MJSONWP (f80b4c3a)][39m **Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started**
[debug] [35m[MJSONWP (f80b4c3a)][39m     at asyncHandler (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:243:15)
[debug] [35m[MJSONWP (f80b4c3a)][39m     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:423:15
[debug] [35m[MJSONWP (f80b4c3a)][39m     at Layer.handle [as handle_request] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [35m[MJSONWP (f80b4c3a)][39m     at next (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/route.js:137:13)
[debug] [35m[MJSONWP (f80b4c3a)][39m     at Route.dispatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/route.js:112:3)
[debug] [35m[MJSONWP (f80b4c3a)][39m     at Layer.handle [as handle_request] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [35m[MJSONWP (f80b4c3a)][39m     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:281:22
[debug] [35m[MJSONWP (f80b4c3a)][39m     at param (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:354:14)
[debug] [35m[MJSONWP (f80b4c3a)][39m     at param (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:365:14)
[debug] [35m[MJSONWP (f80b4c3a)][39m     at Function.process_params (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:410:3)
[debug] [35m[MJSONWP (f80b4c3a)][39m     at next (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[debug] [35m[MJSONWP (f80b4c3a)][39m     at logger (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/morgan/index.js:144:5)
[debug] [35m[MJSONWP (f80b4c3a)][39m     at Layer.handle [as handle_request] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [35m[MJSONWP (f80b4c3a)][39m     at trim_prefix (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
[debug] [35m[MJSONWP (f80b4c3a)][39m     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:284:7
[debug] [35m[MJSONWP (f80b4c3a)][39m     at Function.process_params (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
[debug] [35m[MJSONWP (f80b4c3a)][39m     at next (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[debug] [35m[MJSONWP (f80b4c3a)][39m     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/body-parser/lib/read.js:130:5
[debug] [35m[MJSONWP (f80b4c3a)][39m     at invokeCallback (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/raw-body/index.js:224:16)
[debug] [35m[MJSONWP (f80b4c3a)][39m     at done (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/raw-body/index.js:213:7)
[debug] [35m[MJSONWP (f80b4c3a)][39m     at IncomingMessage.onEnd (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/raw-body/index.js:273:7)
[debug] [35m[MJSONWP (f80b4c3a)][39m     at IncomingMessage.emit (events.js:208:15)
[debug] [35m[MJSONWP (f80b4c3a)][39m     at endReadableNT (_stream_readable.js:1168:12)
[debug] [35m[MJSONWP (f80b4c3a)][39m     at processTicksAndRejections (internal/process/task_queues.js:77:11)
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session/f80b4c3a-8fbc-470a-b614-7d1b95f4073d/elements [39m[33m404[39m [90m25 ms - 131[39m
[info] [35m[HTTP][39m [90m[39m[error] [35m[Xcode][39m 2021-07-19 14:09:36.998475+0530 WebDriverAgentRunner-Runner[2712:1623950] Cannot retrieve element attribute(s) (
[error] [35m[Xcode][39m     "XC_kAXXCAttributeIsElement"
[error] [35m[Xcode][39m ). Original error: Error Domain=com.apple.dt.xctest.automation-support.error Code=11 "Accessibility error kAXErrorCannotComplete from AXUIElementCopyMultipleAttributeValues for 2016" UserInfo={accessibility-error=-25204, NSLocalizedDescription=Accessibility error kAXErrorCannotComplete from AXUIElementCopyMultipleAttributeValues for 2016}
[error] [35m[Xcode][39m 
[error] [35m[Xcode][39m 2021-07-19 14:09:37.004420+0530 WebDriverAgentRunner-Runner[2712:1623950] Cannot retrieve element attribute(s) (
[error] [35m[Xcode][39m     "XC_kAXXCAttributeIsElement"
[error] [35m[Xcode][39m ). Original error: Error Domain=com.apple.dt.xctest.automation-support.error Code=11 "Accessibility error kAXErrorCannotComplete from AXUIElementCopyMultipleAttributeValues for 2016" UserInfo={accessibility-error=-25204, NSLocalizedDescription=Accessibility error kAXErrorCannotComplete from AXUIElementCopyMultipleAttributeValues for 2016}
[error] [35m[Xcode][39m 2021-07-19 14:09:37.010448+0530 WebDriverAgentRunner-Runner[2712:1623950] Cannot retrieve element attribute(s) (
[error] [35m[Xcode][39m     "XC_kAXXCAttributeIsElement"
[error] [35m[Xcode][39m ). Original error: Error Domain=com.apple.dt.xctest.automation-support.error Code=11 "Accessibility error kAXErrorCannotComplete from AXUIElementCopyMultipleAttributeValues for 2016" UserInfo={accessibility-error=-25204, NSLocalizedDescription=Accessibility error kAXErrorCannotComplete from AXUIElementCopyMultipleAttributeValues for 2016}
[error] [35m[Xcode][39m 
[error] [35m[Xcode][39m 2021-07-19 14:09:37.017429+0530 WebDriverAgentRunner-Runner[2712:1623950] Cannot retrieve element attribute(s) (
[error] [35m[Xcode][39m     "XC_kAXXCAttributeIsElement"
[error] [35m[Xcode][39m ). Original error: Error Domain=com.apple.dt.xctest.automation-support.error Code=11 "Accessibility error kAXErrorCannotComplete from AXUIElementCopyMultipleAttributeValues for 2016" UserInfo={accessibility-error=-25204, NSLocalizedDescription=Accessibility error kAXErrorCannotComplete from AXUIElementCopyMultipleAttributeValues for 2016}
[error] [35m[Xcode][39m 
[error] [35m[Xcode][39m 2021-07-19 14:09:37.027483+0530 WebDriverAgentRunner-Runner[2712:1623950] Cannot retrieve element attribute(s) (
[error] [35m[Xcode][39m     "XC_kAXXCAttributeIsElement"
[error] [35m[Xcode][39m ). Original error: Error Domain=com.apple.dt.xctest.automation-support.error Code=11 "Accessibility error kAXErrorCannotComplete from AXUIElementCopyMultipleAttributeValues for 2016" UserInfo={accessibility-error=-25204, NSLocalizedDescription=Accessibility error kAXErrorCannotComplete from AXUIElementCopyMultipleAttributeValues for 2016}
[error] [35m[Xcode][39m 
[error] [35m[Xcode][39m 2021-07-19 14:09:37.033365+0530 WebDriverAgentRunner-Runner[2712:1623950] Cannot retrieve element attribute(s) (
[error] [35m[Xcode][39m     "XC_kAXXCAttributeIsElement"
[error] [35m[Xcode][39m ). Original error: Error Domain=com.apple.dt.xctest.automation-support.error Code=11 "Accessibility error kAXErrorCannotComplete from AXUIElementCopyMultipleAttributeValues for 2016" UserInfo={accessibility-error=-25204, NSLocalizedDescription=Accessibility error kAXErrorCannotComplete from AXUIElementCopyMultipleAttributeValues for 2016}

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing we could do about this error as it happens with XCTest itself. Consider reporting it to Apple.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
