### ISSUE TITLE
Observing increase in execution time in iOS 14.3

### ISSUE THREAD

**Issue by ddvibhashyam** [appium/appium#15651]
## The problem

We are seeing an increase in the execution times of the tests which are executed on iOS 14.3, whereas the same tests taking very less time in iOS 13.2. The only difference between the tests is the appiumVersion used. For iOS 14.3, we are using appiumVersion as 1.20.1 and for iOS 13.2 we are using 1.16.0. We also observed the issue in appiumVersions greater than 1.16.0.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1 and above.
* Last Appium version that did not exhibit the issue (if applicable): 1.16.0
* Desktop OS/version used to run Appium: Safari 14
* Mobile platform/version under test: iOS 14.3
* Real device or emulator/simulator: Emulators

Please confirm if there is an issue with execution times with appiumVersion greater than 1.17.1.

**Comment by mykola-mokhnach** [comment]
Unfortunately the provided information is not enough to solve the performance issue. Please provide more specific information about what exact steps/API calls are slower with logs and timings between the old one and the latest Appium server versions.

**Comment by ddvibhashyam** [comment]
Please find the attached appium log files for the tests executed on iOS 14.3 and iOS 13.2.
[appium-log-iOS-13.2.log](https://github.com/appium/appium/files/6866918/appium-log-iOS-13.2.log)
[appium-log-iOS-14.3.log](https://github.com/appium/appium/files/6866919/appium-log-iOS-14.3.log)

**Comment by mykola-mokhnach** [comment]
I've added some improvements for alert checking logic in https://github.com/appium/appium-xcuitest-driver/pull/1320
You could try if the performance is better now in appium@beta.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
