### ISSUE TITLE
Unknown Error Status 13 displayed when launching WinAppDriver and Session is not created

### ISSUE THREAD

**Issue by YenikeRaghuRam** [appium/appium#15667]
## The problem

Unknown Error Status 13 displayed when launching WinAppDriver and Session is not created

## Environment

* Appium version (or git revision) that exhibits the issue:1.21.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:Windows 10
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:Windows PC
* Real device or emulator/simulator:Real Device
* Appium CLI or Appium.app|exe:Appium.exe

## Details

When winApp Driver starts and about to launch application 
Unknown Error Status 13 displayed when launching WinAppDriver and Session is not created

## Link to Appium logs

Attaching screenshots as unable to copy from console
![1](https://user-images.githubusercontent.com/81166452/127271053-7fb34ee8-192c-4b3c-9309-2ed4badb04c7.PNG)
![2](https://user-images.githubusercontent.com/81166452/127271059-1d939bd2-97ce-4715-988d-8e57d85a92ca.PNG)
![3](https://user-images.githubusercontent.com/81166452/127271062-27fe8f5e-8257-48c5-8d92-bc27c274bcd6.PNG)
![4](https://user-images.githubusercontent.com/81166452/127271063-8eff8ee0-f84f-4eac-a9f3-3793a703e08b.PNG)

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Please report your issue to Microsoft. Appium team does not maintain WinAppDriver.

**Comment by YenikeRaghuRam** [comment]
Reported to Microsoft/WinAppDriver Thanks
Refer https://github.com/microsoft/WinAppDriver/issues/1564
