### ISSUE TITLE
Pulling android notifications test failure

### ISSUE THREAD

**Issue by myralyngarcia** [appium/appium#15669]
## The problem

I am testing push notification and I used this command to pull the android notifications 
`driver.executeScript("mobile: getNotifications");`

and getting the following errors in appium server
[W3C (a59b8cf2)] Calling AppiumDriver.execute() with args: ["mobile: getNotifications",[],"a59b8cf2-30ad-44c3-aeaa-ea63eb037830"]
[AndroidDriver] Executing native command 'mobile: getNotifications'
[ADB] Retrieving notifications
[ADB] Getting IDs of all 'io.appium.settings' processes
[ADB] Running '/Users/myralyngarcia-mbp/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pgrep -f \(\[\[:blank:\]\]\|\^\)io\.appium\.settings\(\[\[:blank:\]\]\|\$\)'
[ADB] Running '/Users/myralyngarcia-mbp/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am broadcast -a io.appium.settings.notifications'
[ADB] Broadcasting: Intent { act=io.appium.settings.notifications flg=0x400000 }
[ADB] Broadcast completed: result=0
[W3C (a59b8cf2)] Encountered internal error running command: Error: Cannot retrieve notifications from the device. Check the server log for more details
[sample_code.txt](https://github.com/appium/appium/files/6894476/sample_code.txt)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacoS Catalina
* Node.js version (unless using Appium.app|exe): v16.3.0
* Npm or Yarn package manager:
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Pixel XL API 30
* Appium CLI or Appium.app|exe:

## Details

When I run testng test to pull the notifications from android status bar I get the following server errors:

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

https://gist.github.com/

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Did you grant the access to notifications from Appium Settings as mentioned in https://github.com/appium/appium-uiautomator2-driver#mobile-getnotifications ?
Could you please attach the logcat output?

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by a-en** [comment]
Hi @mykola-mokhnach,
we are facing the same error. Just to confirm - access to Appium Settings is granted. As for logcat output, there is just one entry that appears after invocation of 'mobile: getNotifications':
`BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver`

Any suggestions would be helpful.
