### ISSUE TITLE
Appium doesn't see Android resource-id

### ISSUE THREAD

**Issue by ZeStassia** [appium/appium#15663]
## The problem

Developer has assigned  resource-id to icon in  Android mobile app. Appium doesn't see this resource-id in the list of elements

## Environment

* Appium version (or git revision) that exhibits the issue:  1.18.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:  Mac 10.15.7 Catalina
* Node.js version (unless using Appium.app|exe):v12.16.3
* Npm or Yarn package manager:
* Mobile platform/version under test: Android 10
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Details

Developer has assigned  resource-id to icon in Android mobile app. Appium doesn't see this resource-id in the list of elements. ID is on separate level as icon jumps through all pages in the app. This level is not visible in Appium.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing we could do about it on Appium side as these values are returned by UiAutomator framework itself. Consider reporting your issue to Google

**Comment by amedvedjev** [comment]
Double check that you can you see this resource id using Android Studio inspector.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
