### ISSUE TITLE
start problem for signed apks

### ISSUE THREAD

**Issue by dilekyldrm** [appium/appium#15660]
Hello,
I have a problem, when starting of the Appium on real device.

I faced with this Error after click Start Sessions.

Error
An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\Users\25200038\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s TQC000200003470401 install -r 'C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.21.1.apk'' exited with code 1'; Stderr: 'adb: failed to install C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.21.1.apk: Failure [INSTALL_FAILED_VERIFICATION_FAILURE]'; Code: '1'

My real device doesn't accept unsigned apk files or something because of security.
When I realized that, I just signed all of the files below to solve the problem.

 settings_apk-debug.apk
 app-debug-androidTest.apk , 
 appium-uiautomator2-server-debug-androidTest.apk
 appium-uiautomator2-server-v4.21.1.apk
and then, I replaced them with the unsigned ones. After that I wrote 'adb install' on Windows Power Shell to check them if they were correct or not.

The Windows Power Shell showed me :

  ''Performing Streamed Install
  Success''
I thought 'this time I succeed on it.' But it was not happened.
When I clicked Start Session with correct information which Appium need ( deviceName, appActivity, appPackage, platformName).
Same Error occurred again.

Error
An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\Users\25200038\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s TQC000200003470401 install -r 'C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.21.1.apk'' exited with code 1'; Stderr: 'adb: failed to install C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.21.1.apk: Failure [INSTALL_FAILED_VERIFICATION_FAILURE]'; Code: '1'

Like I didn't sign any apk. or I didn't change anything.
After got the same error I checked the Windows Power Shell to see the differences. I faced with the same failed massage at the beginning.
I realized that Appium change the signed files with the beginning ones. It replaced files with the unsigned ones.
It didn't let me make some changings.
I don't know why ?????

HOW CAN I FİX THİS PROBLEM?
IS THERE ANYONE COME ACROSS A PROBLEM LİKE THAT ?

screenshots below, 

![screen1](https://user-images.githubusercontent.com/87432156/126942771-034104a4-c4e2-45c9-a87c-2eac6e6bbf04.png)
![screen2](https://user-images.githubusercontent.com/87432156/126942775-7b722f3e-73b7-4d85-9f70-e0ba4cb56a18.png)

**Comment by KazuCocoa** [comment]
Appium usually re-sign the apk by https://github.com/appium/appium-adb/tree/master/keys by default for Android.
`'appium:noSign': true` capability skips it.

**Comment by mykola-mokhnach** [comment]
Just to add on the above: `noSign` option works for the application under test only. In order to keep server binaries with their original signature you could preinstall them on the device manually and set the `skipServerInstallation` capability to `true`.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
