### ISSUE TITLE
Appium cannot start the ios App

### ISSUE THREAD

**Issue by Tianglangxing-89** [appium/appium#15674]
## The problem
I want to do the ios App automated testing, testing the App has been installed to ios true machine, the App "BundleId" is ". Com. Sinosun bizmate. Newace ".
The problem I encountered was that the installed App could not be automatically opened when I used the Inspector session function of Appium.Python automated test scripts also do not automatically start apps.
WebDriverAgent has been installed on iPhone 8 via a personal free developer account and Xcode

Below is Appium's log
[info] [35m[HTTP][39m Waiting until the server is closed
[info] [35m[HTTP][39m Received server close event
[info] [35m[Appium][39m Welcome to Appium v1.21.0
[info] [35m[Appium][39m Non-default server args:
[info] [35m[Appium][39m   relaxedSecurityEnabled: true
[info] [35m[Appium][39m   allowInsecure: {
[info] [35m[Appium][39m   }
[info] [35m[Appium][39m   denyInsecure: {
[info] [35m[Appium][39m   }
[info] [35m[Appium][39m Appium REST http interface listener started on 0.0.0.0:4723[info] [35m[iProxy@b1003e9e:8100][39m The connection has been closed[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{"desiredCapabilities":{"BundleId":"com.sinosun.bizmate.newace","automationName":"XCUITest","deviceName":"iPhone my8","platformName":"iOS","platformVersion":"13.3","udid":"b1003e9e562c147324245fdfde14327f170b2444","xcodeOrgId":"HLG2G5D6K8","xcodeSigningId":"iPhone Developer","newCommandTimeout":0,"connectHardwareKeyboard":true}}[39m
[debug] [35m[MJSONWP][39m Calling AppiumDriver.createSession() with args: [{"BundleId":"com.sinosun.bizmate.newace","automationName":"XCUITest","deviceName":"iPhone my8","platformName":"iOS","platformVersion":"13.3","udid":"b1003e9e562c147324245fdfde14327f170b2444","xcodeOrgId":"HLG2G5D6K8","xcodeSigningId":"iPhone Developer","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1627610798475 (10:06:38 GMT+0800 (中国标准时间))
[info] [35m[Appium][39m Appium v1.21.0 creating new XCUITestDriver (v3.43.0) session
[info] [35m[Appium][39m Applying relaxed security to 'XCUITestDriver' as per server command line argument. All insecure features will be enabled unless explicitly disabled by --deny-insecure
[debug] [35m[BaseDriver][39m Creating session with MJSONWP desired capabilities: {
[debug] [35m[BaseDriver][39m   "BundleId": "com.sinosun.bizmate.newace",
[debug] [35m[BaseDriver][39m   "automationName": "XCUITest",
[debug] [35m[BaseDriver][39m   "deviceName": "iPhone my8",
[debug] [35m[BaseDriver][39m   "platformName": "iOS",
[debug] [35m[BaseDriver][39m   "platformVersion": "13.3",
[debug] [35m[BaseDriver][39m   "udid": "b1003e9e562c147324245fdfde14327f170b2444",
[debug] [35m[BaseDriver][39m   "xcodeOrgId": "HLG2G5D6K8",
[debug] [35m[BaseDriver][39m   "xcodeSigningId": "iPhone Developer",
[debug] [35m[BaseDriver][39m   "newCommandTimeout": 0,
[debug] [35m[BaseDriver][39m   "connectHardwareKeyboard": true
[debug] [35m[BaseDriver][39m }
[warn] [35m[BaseDriver][39m The following capabilities were provided, but are not recognized by Appium:
[warn] [35m[BaseDriver][39m   BundleId
[info] [35m[XCUITest][39m The desired capabilities include neither an app nor a bundleId. WebDriverAgent will be started without the default app
[info] [35m[BaseDriver][39m Session created with session id: 6d24280e-9cef-405f-821e-ab3d684d9731
[debug] [35m[XCUITest][39m Current user: 'sinosun'[debug] [35m[XCUITest][39m Crash reports root '/Users/sinosun/Library/Logs/CrashReporter/MobileDevice/iPhone my8' does not exist. Got nothing to gather.
[debug] [35m[BaseDriver][39m Event 'logCaptureStarted' logged at 1627610798815 (10:06:38 GMT+0800 (中国标准时间))
[info] [35m[XCUITest][39m Setting up real device
[debug] [35m[WebDriverAgent][39m No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[info] [35m[DevCon Factory][39m Requesting connection for device b1003e9e562c147324245fdfde14327f170b2444 on local port 8100, device port 8100
[debug] [35m[DevCon Factory][39m Cached connections count: 0
[info] [35m[DevCon Factory][39m Successfully requested the connection for b1003e9e562c147324245fdfde14327f170b2444:8100
[debug] [35m[XCUITest][39m Starting WebDriverAgent initialization with the synchronization key 'XCUITestDriver'
[debug] [35m[WD Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[WD Proxy][39m Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[debug] [35m[WD Proxy][39m Got response with status 200: {"value":{"message":"WebDriverAgent is ready to accept commands","state":"success","os":{"testmanagerdVersion":28,"name":"iOS","sdkVersion":"14.5","version":"13.3"},"ios":{"ip":"10.2.30.191"},"ready":true,"build":{"upgradedAt":"1620631774000","time":"Jul 30 2021 00:33:34","productBundleIdentifier":"com.facebook.WebDriverAgentRunner"}},"sessionId":null}
[debug] [35m[WebDriverAgent][39m Upgrade timestamp of the currently bundled WDA: 1620631774000
[debug] [35m[WebDriverAgent][39m Upgrade timestamp of the WDA on the device: 1620631774000
[info] [35m[WebDriverAgent][39m Will reuse previously cached WDA instance at 'http://127.0.0.1:8100/' with 'com.facebook.WebDriverAgentRunner'. Set the wdaLocalPort capability to a value different from 8100 if this is an undesired behavior.
[debug] [35m[XCUITest][39m Trying to start WebDriverAgent 1 times with 10000ms interval
[debug] [35m[XCUITest][39m These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
[debug] [35m[BaseDriver][39m Event 'wdaStartAttempted' logged at 1627610798948 (10:06:38 GMT+0800 (中国标准时间))
[info] [35m[WebDriverAgent][39m Using provided WebdriverAgent at 'http://127.0.0.1:8100/'
[debug] [35m[WD Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[WD Proxy][39m Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[debug] [35m[WD Proxy][39m Got response with status 200: {"value":{"message":"WebDriverAgent is ready to accept commands","state":"success","os":{"testmanagerdVersion":28,"name":"iOS","sdkVersion":"14.5","version":"13.3"},"ios":{"ip":"10.2.30.191"},"ready":true,"build":{"upgradedAt":"1620631774000","time":"Jul 30 2021 00:33:34","productBundleIdentifier":"com.facebook.WebDriverAgentRunner"}},"sessionId":null}
[debug] [35m[BaseDriver][39m Event 'wdaSessionAttempted' logged at 1627610798967 (10:06:38 GMT+0800 (中国标准时间))
[debug] [35m[XCUITest][39m Sending createSession command to WDA
[debug] [35m[WD Proxy][39m Matched '/session' to command name 'createSession'
[debug] [35m[WD Proxy][39m Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true,"shouldTerminateApp":true}],"alwaysMatch":{}}}[error] [35m[Xcode][39m 2021-07-30 10:06:39.182984+0800 WebDriverAgentRunner-Runner[1176:118627] Getting the most recent active application (out of 1 total items)
[error] [35m[Xcode][39m     t =  4322.05s Find the Application 'com.apple.Preferences'
[error] [35m[Xcode][39m     t =  4322.06s     Requesting snapshot of accessibility hierarchy for app with pid 968
[error] [35m[Xcode][39m 
[debug] [35m[WD Proxy][39m Got response with status 200: {"value":{"sessionId":"68FC7944-3237-4063-8359-F2E1607EB391","capabilities":{"device":"iphone","browserName":"设置","sdkVersion":"13.3","CFBundleIdentifier":"com.apple.Preferences"}},"sessionId":"68FC7944-3237-4063-8359-F2E1607EB391"}
[info] [35m[WD Proxy][39m Determined the downstream protocol as 'W3C'
[debug] [35m[BaseDriver][39m Event 'wdaSessionStarted' logged at 1627610799155 (10:06:39 GMT+0800 (中国标准时间))
[debug] [35m[BaseDriver][39m Event 'wdaStarted' logged at 1627610799156 (10:06:39 GMT+0800 (中国标准时间))
[info] [35m[XCUITest][39m Skipping setting of the initial display orientation. Set the "orientation" capability to either "LANDSCAPE" or "PORTRAIT", if this is an undesired behavior.
[debug] [35m[BaseDriver][39m Event 'orientationSet' logged at 1627610799156 (10:06:39 GMT+0800 (中国标准时间))
[debug] [35m[BaseDriver][39m The value of 'elementResponseAttributes' setting did not change. Skipping the update for it
[debug] [35m[BaseDriver][39m The value of 'shouldUseCompactResponses' setting did not change. Skipping the update for it
[info] [35m[Appium][39m New XCUITestDriver session created successfully, session 6d24280e-9cef-405f-821e-ab3d684d9731 added to master session list
[debug] [35m[BaseDriver][39m Event 'newSessionStarted' logged at 1627610799157 (10:06:39 GMT+0800 (中国标准时间))
[debug] [35m[MJSONWP (6d24280e)][39m Cached the protocol value 'MJSONWP' for the new session 6d24280e-9cef-405f-821e-ab3d684d9731
[debug] [35m[MJSONWP (6d24280e)][39m Responding to client with driver.createSession() result: {"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"BundleId":"com.sinosun.bizmate.newace","automationName":"XCUITest","deviceName":"iPhone my8","platformName":"iOS","platformVersion":"13.3","udid":"b1003e9e562c147324245fdfde14327f170b2444","xcodeOrgId":"HLG2G5D6K8","xcodeSigningId":"iPhone Developer","newCommandTimeout":0,"connectHardwareKeyboard":true}
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[32m200[39m [90m685 ms - 574[39m
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/session/6d24280e-9cef-405f-821e-ab3d684d9731/contexts[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[MJSONWP (6d24280e)][39m Calling AppiumDriver.getContexts() with args: ["6d24280e-9cef-405f-821e-ab3d684d9731"]
[debug] [35m[XCUITest][39m Executing command 'getContexts'
[debug] [35m[XCUITest][39m Getting list of available contexts
[debug] [35m[iOS][39m Retrieving contexts and views
[error] [35m[XCUITest][39m Cannot enter web frame without a bundle ID
[debug] [35m[MJSONWP (6d24280e)][39m Encountered internal error running command: Error: Cannot enter web frame without a bundle ID
[debug] [35m[MJSONWP (6d24280e)][39m     at Object.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:94:35)
[debug] [35m[MJSONWP (6d24280e)][39m     at XCUITestDriver.listWebFrames (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/context.js:194:9)
[debug] [35m[MJSONWP (6d24280e)][39m     at XCUITestDriver.getContextsAndViews (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-ios-driver/lib/commands/context.js:160:29)
[debug] [35m[MJSONWP (6d24280e)][39m     at XCUITestDriver.getContexts (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/context.js:247:31)
[debug] [35m[MJSONWP (6d24280e)][39m     at commandExecutor (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:335:9)
[debug] [35m[MJSONWP (6d24280e)][39m     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/async-lock/lib/index.js:137:12
[debug] [35m[MJSONWP (6d24280e)][39m     at AsyncLock._promiseTry (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/async-lock/lib/index.js:261:31)
[debug] [35m[MJSONWP (6d24280e)][39m     at exec (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/async-lock/lib/index.js:136:9)
[debug] [35m[MJSONWP (6d24280e)][39m     at AsyncLock.acquire (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/async-lock/lib/index.js:152:3)
[debug] [35m[MJSONWP (6d24280e)][39m     at XCUITestDriver.executeCommand (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:348:39)
[debug] [35m[MJSONWP (6d24280e)][39m     at XCUITestDriver.executeCommand (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:731:24)
[debug] [35m[MJSONWP (6d24280e)][39m     at AppiumDriver.executeCommand (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/lib/appium.js:563:36)
[debug] [35m[MJSONWP (6d24280e)][39m     at processTicksAndRejections (internal/process/task_queues.js:85:5)
[debug] [35m[MJSONWP (6d24280e)][39m     at asyncHandler (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:297:21)
[info] [35m[HTTP][39m [37m<-- GET /wd/hub/session/6d24280e-9cef-405f-821e-ab3d684d9731/contexts [39m[31m500[39m [90m9 ms - 213[39m
[info] [35m[HTTP][39m [90m[39m
[info] [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/session/6d24280e-9cef-405f-821e-ab3d684d9731/source[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[MJSONWP (6d24280e)][39m Calling AppiumDriver.getPageSource() with args: ["6d24280e-9cef-405f-821e-ab3d684d9731"]
[debug] [35m[XCUITest][39m Executing command 'getPageSource'
[debug] [35m[WD Proxy][39m Matched '/source' to command name 'getPageSource'
[debug] [35m[WD Proxy][39m Proxying [GET /source] to [GET http://127.0.0.1:8100/session/68FC7944-3237-4063-8359-F2E1607EB391/source] with no body[error] [35m[Xcode][39m 2021-07-30 10:06:40.217013+0800 WebDriverAgentRunner-Runner[1176:118627] Getting the most recent active application (out of 1 total items)
[error] [35m[Xcode][39m 
[error] [35m[Xcode][39m 2021-07-30 10:06:40.219990+0800 WebDriverAgentRunner-Runner[1176:118627] The following attributes were requested to be included into the XML: {(
[error] [35m[Xcode][39m     FBHeightAttribute,
[error] [35m[Xcode][39m     FBAccessibleAttribute,
[error] [35m[Xcode][39m     FBValueAttribute,
[error] [35m[Xcode][39m     FBVisibleAttribute,
[error] [35m[Xcode][39m     FBWidthAttribute,
[error] [35m[Xcode][39m     FBEnabledAttribute,
[error] [35m[Xcode][39m     FBTypeAttribute,
[error] [35m[Xcode][39m     FBYAttribute,
[error] [35m[Xcode][39m     FBLabelAttribute,
[error] [35m[Xcode][39m     FBIndexAttribute,
[error] [35m[Xcode][39m     FBXAttribute,
[error] [35m[Xcode][39m     FBNameAttribute
[error] [35m[Xcode][39m )}
[error] [35m[Xcode][39m 2021-07-30 10:06:40.220675+0800 WebDriverAgentRunner-Runner[1176:118627] Waiting up to 2s until com.apple.Preferences is in idle state (including animations)
[error] [35m[Xcode][39m     t =  4323.09s Wait for com.apple.Preferences to idle
[error] [35m[Xcode][39m 
[error] [35m[Xcode][39m     t =  4323.11s Requesting snapshot of accessibility hierarchy for app with pid 968
[error] [35m[Xcode][39m [debug] [35m[WebDriverAgent][39m Parsed BUILD_DIR configuration value: '/Users/sinosun/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Build/Products'
[debug] [35m[WebDriverAgent][39m Got derived data root: '/Users/sinosun/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp'[debug] [35m[WD Proxy][39m Got response with status 200: {"value":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<XCUIElementTypeApplication type=\"XCUIElementTypeApplication\" name=\"设置\" label=\"设置\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"375\" height=\"667\" index=\"0\">\n  <XCUIElementTypeWindow type=\"XCUIElementTypeWindow\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"375\" height=\"667\" index=\"0\">\n    <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"375\" height=\"667\" index=\"0\">\n      <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"375\" height=\"667\" index=\"0\">\n        <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"375\" height=\"667\" index=\"0\">\n          <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\"...
[debug] [35m[MJSONWP (6d24280e)][39m Responding to client with driver.getPageSource() result: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><AppiumAUT><XCUIElementTypeApplication type=\"XCUIElementTypeApplication\" name=\"设置\" label=\"设置\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"375\" height=\"667\" index=\"0\">\n  <XCUIElementTypeWindow type=\"XCUIElementTypeWindow\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"375\" height=\"667\" index=\"0\">\n    <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"375\" height=\"667\" index=\"0\">\n      <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"375\" height=\"667\" index=\"0\">\n        <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"375\" height=\"667\" index=\"0\">\n          <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\"...
[info] [35m[HTTP][39m [37m<-- GET /wd/hub/session/6d24280e-9cef-405f-821e-ab3d684d9731/source [39m[32m200[39m [90m3101 ms - 25949[39m
[info] [35m[HTTP][39m [90m[39m
[info] [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/session/6d24280e-9cef-405f-821e-ab3d684d9731/screenshot[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[MJSONWP (6d24280e)][39m Calling AppiumDriver.getScreenshot() with args: ["6d24280e-9cef-405f-821e-ab3d684d9731"]
[debug] [35m[XCUITest][39m Executing command 'getScreenshot'
[debug] [35m[XCUITest][39m Taking screenshot with WDA
[debug] [35m[WD Proxy][39m Matched '/screenshot' to command name 'getScreenshot'
[debug] [35m[WD Proxy][39m Proxying [GET /screenshot] to [GET http://127.0.0.1:8100/session/68FC7944-3237-4063-8359-F2E1607EB391/screenshot] with no body
[debug] [35m[WD Proxy][39m Got response with status 200: {"value":"iVBORw0KGgoAAAANSUhEUgAAAu4AAAU2CAYAAADK1zMGAAAAAXNSR0IArs4c6QAA\r\nAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKAC\r\nAAQAAAABAAAC7qADAAQAAAABAAAFNgAAAACw0axrAAAAHGlET1QAAAACAAAAAAAA\r\nApsAAAAoAAACmwAAApsAAbSqNs1qsAAAQABJREFUeAHsnQeAVsXVhmn2roliL6jY\r\nS9RfEZalY6+JLdYkxpJiookFW6w0xYb0Yq+oiC0ooGIXewUEMVakSYctcP7znLvv\r\nt5dlZSEYFZiB2elnyj0z951zz8xXa/58s6Wz8738f2/nzTNL9sccg3k+3nn7Y9ad\r\n6kq8nngg8UDigcQDiQcSDyw9D8wvd/yasxrTcseV2NIKW+55sPPIW2bucYvfStyW\r\nerDc5jkWJimSwcWeB2wceUl0O89zY0srLDRIV1niSY+IcnfL3OJ6BnAyabhKV3sr\r\n3Tw2+35/LWgsnf3vQXt0hE4n+yOOQVVmSOOf+C/xQOKBxAOJBxIPJB5YtnggD9rx\r\n6/kJuOddQHsA9wDbFeB5fgUEB1R7VB64EwYbA8wjsQJ8C4CTd2HgntHIgDnpTsDr\r\nqyyTA/ZOT+2tdKvis+rDCbivcJuGqoxQyeyVzJPi0lgkHkg8kHgg8UDigcQDP2Me\r\nqADjekblLibH5rUK5s8rc+k51qXrbm3eXEfSczIbaL5CGp4D7gWpexXgHkA9gD9g\r\n3i0ZAebux1taYQP0B+BfOI08pIddCH8u2PZ8P/L+BNwXGjgf0OU6ripjLO/9Tf1b\r\nvvk5Pd/0fBMPJB5IPLBC8sD3APdK8C7QXgnc5wdwdwA/3y0gvAJ4A6QB37KEA5xX\r\n5FHeBVxQuBcAuJO/KnAnHql9Jaif7/7MhtrNQlizKj6rPpyA+0IDt7wvAFU...
[debug] [35m[MJSONWP (6d24280e)][39m Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAAAu4AAAU2CAYAAADK1zMGAAAAAXNSR0IArs4c6QAA\r\nAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKAC\r\nAAQAAAABAAAC7qADAAQAAAABAAAFNgAAAACw0axrAAAAHGlET1QAAAACAAAAAAAA\r\nApsAAAAoAAACmwAAApsAAbSqNs1qsAAAQABJREFUeAHsnQeAVsXVhmn2roliL6jY\r\nS9RfEZalY6+JLdYkxpJiookFW6w0xYb0Yq+oiC0ooGIXewUEMVakSYctcP7znLvv\r\nt5dlZSEYFZiB2elnyj0z951zz8xXa/58s6Wz8738f2/nzTNL9sccg3k+3nn7Y9ad\r\n6kq8nngg8UDigcQDiQcSDyw9D8wvd/yasxrTcseV2NIKW+55sPPIW2bucYvfStyW\r\nerDc5jkWJimSwcWeB2wceUl0O89zY0srLDRIV1niSY+IcnfL3OJ6BnAyabhKV3sr\r\n3Tw2+35/LWgsnf3vQXt0hE4n+yOOQVVmSOOf+C/xQOKBxAOJBxIPJB5YtnggD9rx\r\n6/kJuOddQHsA9wDbFeB5fgUEB1R7VB64EwYbA8wjsQJ8C4CTd2HgntHIgDnpTsDr\r\nqyyTA/ZOT+2tdKvis+rDCbivcJuGqoxQyeyVzJPi0lgkHkg8kHgg8UDigcQDP2Me\r\nqADjekblLibH5rUK5s8rc+k51qXrbm3eXEfSczIbaL5CGp4D7gWpexXgHkA9gD9g\r\n3i0ZAebux1taYQP0B+BfOI08pIddCH8u2PZ8P/L+BNwXGjgf0OU6ripjLO/9Tf1b\r\nvvk5Pd/0fBMPJB5IPLBC8sD3APdK8C7QXgnc5wdwdwA/3y0gvAJ4A6QB37KEA5xX\r\n5FHeBVxQuBcAuJO/KnAnHql9Jaif7/7MhtrNQlizKj6rPpyA+0IDt7wvAFUZYXnv\r\n...
[info] [35m[HTTP][39m [37m<-- GET /wd/hub/session/6d24280e-9cef-405f-821e-ab3d684d9731/screenshot [39m[32m200[39m [90m69 ms - 254722[39m
[info] [35m[HTTP][39m [90m[39m

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS Big Sur 11.4
* Node.js version (unless using Appium.app|exe): 14.17.3
* Npm or Yarn package manager: 6.14.13
* Mobile platform/version under test: iOS 13.3
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium.app|exe

Appium Environment check：
sinosun@SinoSundeMacBook-Air ~ % appium-doctor --ios
info AppiumDoctor Appium Doctor v.1.16.0
info AppiumDoctor ### Diagnostic for necessary dependencies starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: /usr/local/bin/node
info AppiumDoctor  ✔ Node version is 14.17.3
info AppiumDoctor  ✔ Xcode is installed at: /Users/sinosun/Downloads/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ Xcode Command Line Tools are installed in: /Users/sinosun/Downloads/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ DevToolsSecurity is enabled.
info AppiumDoctor  ✔ The Authorization DB is set up properly.
info AppiumDoctor  ✔ Carthage was found at: /usr/local/bin/carthage. Installed version is: 0.38.0
info AppiumDoctor  ✔ HOME is set to: /Users/sinosun
info AppiumDoctor ### Diagnostic for necessary dependencies completed, no fix needed. ###
info AppiumDoctor 
info AppiumDoctor ### Diagnostic for optional dependencies starting ###
WARN AppiumDoctor  ✖ opencv4nodejs cannot be found.
WARN AppiumDoctor  ✖ ffmpeg cannot be found
WARN AppiumDoctor  ✖ mjpeg-consumer cannot be found.
WARN AppiumDoctor  ✖ set-simulator-location is not installed
WARN AppiumDoctor  ✖ idb and idb_companion are not installed
WARN AppiumDoctor  ✖ applesimutils cannot be found
info AppiumDoctor  ✔ ios-deploy is installed at: /usr/local/bin/ios-deploy. Installed version is: 1.11.4
info AppiumDoctor ### Diagnostic for optional dependencies completed, 6 fixes possible. ###
info AppiumDoctor 
info AppiumDoctor ### Optional Manual Fixes ###
info AppiumDoctor The configuration can install optionally. Please do the following manually:
WARN AppiumDoctor  ➜ Why opencv4nodejs is needed and how to install it: https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/image-comparison.md
WARN AppiumDoctor  ➜ ffmpeg is needed to record screen features. Please read https://www.ffmpeg.org/ to install it
WARN AppiumDoctor  ➜ mjpeg-consumer module is required to use MJPEG-over-HTTP features. Please install it with 'npm i -g mjpeg-consumer'.
WARN AppiumDoctor  ➜ set-simulator-location is needed to set location for Simulator. Please read https://github.com/lyft/set-simulator-location to install it
WARN AppiumDoctor  ➜ Why idb is needed and how to install it: https://github.com/appium/appium-idb
WARN AppiumDoctor  ➜ Why applesimutils is needed and how to install it: http://appium.io/docs/en/drivers/ios-xcuitest/
info AppiumDoctor 
info AppiumDoctor ###
info AppiumDoctor 
info AppiumDoctor Bye! Run appium-doctor again when all manual fixes have been applied!
info AppiumDoctor

## Details

When I was driving an ios phone through the Appium Inspector during an ios automation test, the App on the ios phone could not automatically start.
I run the iOS automation script in Python, and the app doesn't automatically start either.
The WebDriverAgent has been built to the iOS server using Xcode_12.5.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
> [warn] [35m[BaseDriver][39m The following capabilities were provided, but are not recognized by Appium:
> [warn] [35m[BaseDriver][39m BundleId

Are you sure correct capabilities are provided? What exactly you are trying to achieve (e.g. is the app under test already installed on the device or not)?

**Comment by Tianglangxing-89** [comment]
I want to do the ios App automated testing, testing the App has been installed to ios true machine, the App "BundleId" is ". Com. Sinosun bizmate. Newace ".
The problem I encountered was that the installed App could not be automatically opened when I used the Inspector session function of Appium.Python automated test scripts also do not automatically start apps.
WebDriverAgent has been installed on iPhone 8 via a personal free developer account and Xcode

**Comment by KazuCocoa** [comment]
what about `bundleId` instead of `BundleId` (case sensitive)?

**Comment by Tianglangxing-89** [comment]
> 怎么样`bundleId`，而不是`BundleId`（区分大小写）？



> > [warn] [35m[BaseDriver][39m The following capabilities were provided, but are not recognized by Appium:
> > [warn] [35m[BaseDriver][39m BundleId
> 
> Are you sure correct capabilities are provided? What exactly you are trying to achieve (e.g. is the app under test already installed on the device or not)?

I want to do the ios App automated testing, testing the App has been installed to ios true machine, the App "BundleId" is ". Com. Sinosun bizmate. Newace ".
The problem I encountered was that the installed App could not be automatically opened when I used the Inspector session function of Appium.Python automated test scripts also do not automatically start apps.
WebDriverAgent has been installed on iPhone 8 via a personal free developer account and Xcode

**Comment by Tianglangxing-89** [comment]
> what about `bundleId` instead of `BundleId` (case sensitive)?

{
  "platformName": "iOS",
  "automationName": "XCUITest",
  "platformVersion": "13.3",
  "deviceName": "iPhone 8",
  "bundleId": "com.sinosun.bizmate.newace",
  "udid": "b1003e9e562c147324245aafde14327f170b6789",
  "xcodeOrgId": "XXXXXXXXXX",
  "xcodeSigningId": "iPhone Developer"
}
After I tried to change the case, Appium could connect to the iOS mobile desktop, but still could not automatically App

**Comment by KazuCocoa** [comment]
The new full log may help us.

**Comment by mykola-mokhnach** [comment]
If the app is already present on the device then you could start Appium without providing any bundle identifiers, but with noReset option set to `true`. Then it would be possible to use [mobile: launchApp](https://github.com/appium/appium-xcuitest-driver#mobile-launchapp)/[mobile: terminateApp](https://github.com/appium/appium-xcuitest-driver#mobile-terminateapp)/[mobile: activateApp](https://github.com/appium/appium-xcuitest-driver#mobile-activateapp) APIs to control the life cycle of your app (or any other app).

**Comment by Tianglangxing-89** [comment]
> The new full log may help us.

I changed the BundleId to bundleId and the app started, because I forgot to change deviceName
thank you！

**Comment by Tianglangxing-89** [comment]
> The new full log may help us.

I changed the Bundleid to bundleid and the app started, because I forgot to change deviceName
thank you！
