### ISSUE TITLE
Click alert button, it need 20s

### ISSUE THREAD

**Issue by candialala** [appium/appium#15677]
## The problem
Click alert button, it need 20s

## Environment

Appium version (or git revision) that exhibits the issue: 1.21.0
Last Appium version that did not exhibit the issue (if applicable): 1.19.0
Desktop OS/version used to run Appium: Mac OS Big Sur 11.5
Mobile platform/version under test: iOS 14.5
Real device or emulator/simulator: Real device/simulator

## Details

The same as this issue, but it only happened on the alert's button click: https://github.com/appium/WebDriverAgent/issues/472
And waitForIdleTimeout/animationCoolOffTimeout doesn't work for me.

## Link to Appium logs

![image](https://user-images.githubusercontent.com/22468260/127771012-3f5f6f06-7d50-4012-9bcb-e44fcf775668.png)

**Comment by mykola-mokhnach** [comment]
Clicks are executed by XCTest itself. Appium acts as a  proxy, - only Apple is capable of changing the behaviour there

**Comment by candialala** [comment]
> Clicks are executed by XCTest itself. Appium acts as a proxy, - only Apple is capable of changing the behaviour there

I think it's the same as this issue, but it only happened on the alert's button click: appium/WebDriverAgent#472

**Comment by mykola-mokhnach** [comment]
Basically all accessibility-based automation frameworks require the main UI thread to not be busy to be able to synthesise any actions there. If the app under test is not idling then I won't be surprised by such delays.

**Comment by candialala** [comment]
> Basically all accessibility-based automation frameworks require the main UI thread to not be busy to be able to synthesise any actions there. If the app under test is not idling then I won't be surprised by such delays.

If set waitForIdleTimeout = 0, it won't have to wait.
But I see the doc https://github.com/appium/appium-xcuitest-driver said "it is not recommended",  I want to know what impact it will have?

**Comment by mykola-mokhnach** [comment]
We basically hack XCTest and enforce it to skip internal waits by setting the value to zero. This MIGHT cause unexpected race condition issues/crashes/deadlocks.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
