### ISSUE TITLE
Installing appium does not pull latest appium-chromedriver version

### ISSUE THREAD

**Issue by goffioul** [appium/appium#15670]
## The problem

After installing appium into a freshly created directory, the version of appium-chromedriver present is not the latest one (same for appium-android-driver).

```
$ npm install appium
[...]

$ npm ls appium-chromedriver
test-appium@ /path/to/test-appium
└─┬ appium@1.21.0
  ├─┬ appium-android-driver@4.43.1
  │ └── appium-chromedriver@4.27.1
  └─┬ appium-uiautomator2-driver@1.65.0
    └── appium-chromedriver@4.27.1 deduped
```

According to npm registry, latest version is `4.27.3`. AFAIK, dependency requirement for appium and appium-android-driver are such that the latest version should be installed. Maybe I'm missing something obvious, but I don't get why the latest published versions of appium-android-driver and appium-chromedriver are not installed.

Note: I already tried deleting ~/.npm before running the install command.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Desktop OS/version used to run Appium: Linux
* Node.js version (unless using Appium.app|exe): v15.11.0
* Npm package manager: 7.6.0

**Comment by mykola-mokhnach** [comment]
Such behaviour is expected, because all Appium releases are shrinkwrapped. Consider installing appium@beta if you need all the latest module versions.
