### ISSUE TITLE
If change contacts permission after app launch, error happened "The application under test with bundle id 'XXX' is not running, possibly crashed"

### ISSUE THREAD

**Issue by candialala** [appium/appium#15673]
## The problem
If change contacts permission after app launch, error happened "The application under test with bundle id 'XXX' is not running, possibly crashed"

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable): 1.19.0
* Desktop OS/version used to run Appium: Mac OS Big Sur 11.5
* Mobile platform/version under test: iOS 14.5
* Real device or emulator/simulator: Real device/simulator

## Details
![image](https://user-images.githubusercontent.com/22468260/127592420-f79563e1-aef3-4780-b7b6-8add2e1792fa.png)

**Comment by mykola-mokhnach** [comment]
This error happens if the the application under test reports it is not running. There is nothing much we could do about it since the detection is done by XCTest

**Comment by candialala** [comment]
> This error happens if the the application under test reports it is not running. There is nothing much we could do about it since the detection is done by XCTest

Because the application permissions changed, I think that it is forced to kill by the system.
![image](https://user-images.githubusercontent.com/22468260/127607509-b4384788-fbd8-4526-ae5f-a1f13860091e.png)
Is it possible to add an external parameter or API to control whether this judgment is performed?

**Comment by mykola-mokhnach** [comment]
You could call the [terminateApp](https://github.com/appium/appium-xcuitest-driver#mobile-terminateapp) API with the actual bundle identifier of the application under test.  This way WDA would know that the app is not expected to run anymore and the above exception would not be thrown.

**Comment by candialala** [comment]
> You could call the [terminateApp](https://github.com/appium/appium-xcuitest-driver#mobile-terminateapp) API with the actual bundle identifier of the application under test. This way WDA would know that the app is not expected to run anymore and the above exception would not be thrown.

but that is work around for me, it means that I must kill app before permissions were changed.

**Comment by mykola-mokhnach** [comment]
This is how WDA was always working. Unfortunately we cannot change it because it would break existing tests.

No you don't have to kill the app before changing the permission. The API call could could be done while the app is not running. In such case instead of killing the app it will just change the internal state of the WDA session. See https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/WebDriverAgentLib/Routing/FBSession.m#L218

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
