### ISSUE TITLE
Error converting element ID for using in WD atoms for iOS hybrid app 

### ISSUE THREAD

**Issue by hemant-janrao** [appium/appium#15683]
## The problem

I am running tests for the hybrid iOS app, they were running without an error a few days back but from the last few weeks since then they started failing with the below reasons.

`unknown error: An unknown server-side error occurred while processing the command. Original error: Error converting element ID for using in WD atoms: ':wdc:1627937674059'`

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable):1.20.0
* Desktop OS/version used to run Appium:  macOS Big Sur
* Node.js version (unless using Appium.app|exe): v14.17.4
* Npm or Yarn package manager: Yarn
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: iOS simulator
* Appium CLI or [Appium.app|exe:]

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
https://gist.github.com/hemant-janrao/6ccd72c6e9c559636ca951c918df9fea

## Code To Reproduce Issue [ Good To Have ]
Run Appium tests for hybrid apps

**Comment by KazuCocoa** [comment]
Could you try out https://github.com/appium/appium-xcuitest-driver/pull/1323 on your local if this helps?

**Comment by hemant-janrao** [comment]
> Could you try out [appium/appium-xcuitest-driver#1323](https://github.com/appium/appium-xcuitest-driver/pull/1323) on your local if this helps?

Hey Sure I will try it today @KazuCocoa Thanks :)

**Comment by mykola-mokhnach** [comment]
I'm currently working on https://github.com/appium/appium-xcuitest-driver/pull/1324
Perhaps, it might also be in use in such case

**Comment by KazuCocoa** [comment]
I also observed `wdc` prefix response by Safari like `:wdc:1628151649325`. appium/appium-xcuitest-driver#1324 should help. So I guess newer Safari? (Then, 14.1.2?) debugger returns the new format.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
