### ISSUE TITLE
Having problems with getting proper child of an element for iOS

### ISSUE THREAD

**Issue by helenkramar** [appium/appium#15682]
I am having the case where I need in runtime detect parent elements and interact with their child elements (my particular situation is the table and cells). And I found out that I am not able to wrap the child in any custom element as I am not able to call methods for corresponding to its index one. 

My issue is super similar to #6700 or #176 or #7415 or #7043 (but my question is about iOS)

So, is this fixed? or is there any "beautiful" workaround?
Please, assist)

**Comment by mykola-mokhnach** [comment]
Closed as nobody here knows an answer. Please try to ask at Appium forum
