### ISSUE TITLE
Accessing Custom UI Components in Android (native).

### ISSUE THREAD

**Issue by abayomiAkanji** [appium/appium#15688]
## The problem

Hi there, we're having an issue accessing Custom components in Android UI. I mean components referenced with XML `<include/>` tag. Some of the suggestions I see online recommend this link https://developer.android.com/guide/topics/ui/accessibility/custom-views.html.
Those suggestions are dated back to 2019.
I want to confirm if Appium now has an in-built feature to access the custom components.

## Error Log
`Using XPath locators is not recommended and can lead to fragile tests. Ask your development team to provide unique accessibility locators instead.`

**Comment by mykola-mokhnach** [comment]
Please provide a proper issue description according to the given template.

Unfortunately the question does not contain enough information to be answered properly. If we are talking about UiAutomator2 driver then all components/views will be reflected in the page source as much as they are available to the system accessibility.

**Comment by abayomiAkanji** [comment]
Many thanks for your response @mykola-mokhnach 

We're performing a UI test automation for an Android app. The automation works fine except for instances where custom designs are being used. A custom design is one that is created to be used/referenced in multiple views.

On that note, we got this error `Using XPath locators is not recommended and can lead to fragile tests. Ask your development team to provide unique accessibility locators instead` from the automation tool.
Apparently, it's repeating the same IDs for all instances where the Custom designs are being used.
What's the way around this?

Appium version: v1.20.2
Device type: Emulator

**Comment by mykola-mokhnach** [comment]
This warning basically means that you should not rely on views hierarchy while building your locators, but rather connect them to unique element identifiers. Also, in general xpath locators are slower that other locator types.

From the app source code perspective it means that custom components/views must be made the way they are properly accessible and have appropriate identifiers. This is not only important for automation frameworks, but also for other services which are based on the system accessibility, for example screen readers and different assistants that tend to help people with disabilities to use the app.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by abayomiAkanji** [comment]
Thank you @mykola-mokhnach 

Because the element' `id` is created at the XML code's child level, the `content-description` property is now being used to identify each custom element (wherever they are referenced dynamically).
