### ISSUE TITLE
Getting huge string from device's clipboard leads to exception

### ISSUE THREAD

**Issue by dulmaganov** [appium/appium#15684]
## The problem
Copying long String from a device's clipboard causes
`org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Cannot parse the actual cliboard content from the command output: Broadcasting: Intent { act=io.appium.settings.clipboard.get flg=0x400000 cmp=io.appium.settings/.receivers.ClipboardReceiver }`

## Environment
* Appium version: 7.5.1
* Android version: 10
Previously worked in pair with Android 9 & 6.1.0

Experienced on:
* AWS Device farm real devices (variety of Samsung, Pixel and other devices)
* Emulators

## Details
In my app there is a button the functionality of which is copy some internal analytics into device's clipboard.
My test script clicks on the button, gets the data with `driver.getClipboardText()`

## Link to Appium logs
[Appium server and logcat](https://gist.github.com/dulmaganov/57e22de260e4cd5feb521ba69e2582b2)
Quick links:
- [logcat](https://gist.github.com/dulmaganov/57e22de260e4cd5feb521ba69e2582b2#file-logcat)
- [appium server](https://gist.github.com/dulmaganov/57e22de260e4cd5feb521ba69e2582b2#file-appium-server)
- [summary](https://gist.githubusercontent.com/dulmaganov/57e22de260e4cd5feb521ba69e2582b2/raw/539dc0037c9d9ad0ebde26b51e7112325846a5b6/summary.txt)

## Code To Reproduce Issue
0. You need a dummy Android app that will produce a huge String (100k characters +). Add functionality into the app to copy this string into the clipboard.
1. Write the testing script that tries to get clipboard from the device: `driver.getClipboard()`

**Comment by mykola-mokhnach** [comment]
Please attach the full server log and the logcat output

**Comment by dulmaganov** [comment]
@mykola-mokhnach updated the links in the description
- [logcat](https://gist.github.com/dulmaganov/57e22de260e4cd5feb521ba69e2582b2#file-logcat)
- [appium server](https://gist.github.com/dulmaganov/57e22de260e4cd5feb521ba69e2582b2#file-appium-server)
- [summary]

**Comment by mykola-mokhnach** [comment]
> [W3C (a12d1bfc)] Calling AppiumDriver.getClipboard() with args: ["plaintext","a12d1bfc-9eb0-420e-b7e6-64312732f7d5"]
> [ADB] Getting the clipboard content
> [ADB] Running '/Users/eduard.dulmaganov/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell settings get secure default_input_method'
> [ADB] Running '/Users/eduard.dulmaganov/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell ime enable io.appium.settings/.AppiumIME'
> [ADB] Running '/Users/eduard.dulmaganov/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell ime set io.appium.settings/.AppiumIME'
> [ADB] Running '/Users/eduard.dulmaganov/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am broadcast -n io.appium.settings/.receivers.ClipboardReceiver -a io.appium.settings.clipboard.get'
> [ADB] Running '/Users/eduard.dulmaganov/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell ime set com.google.android.inputmethod.latin/com.android.inputmethod.latin.LatinIME'
> [W3C (a12d1bfc)] Encountered internal error running command: Error: Cannot retrieve the current clipboard content from the device. Make sure the Appium Settings application is up to date. Original error: Error executing adbExec. Original error: 'Command '/Users/eduard.dulmaganov/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am broadcast -n io.appium.settings/.receivers.ClipboardReceiver -a io.appium.settings.clipboard.get' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability
> [W3C (a12d1bfc)]     at ADB.getClipboard (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-adb/lib/tools/settings-client-commands.js:300:11)
> [HTTP] <-- POST /wd/hub/session/a12d1bfc-9eb0-420e-b7e6-64312732f7d5/appium/device/get_clipboard 500 20132 ms - 1565

What happens if you execute the sequence of the above commands manually? is adb broadcast call also blocked for more than 20 seconds? how long it stays blocked?

**Comment by mykola-mokhnach** [comment]
Closed because of no response
