### ISSUE TITLE
When ios automated tests start the app, each test cannot start from login

### ISSUE THREAD

**Issue by Tianglangxing-89** [appium/appium#15689]
## The problem

I want to do an automated test of ios App. The test App has been installed on the real ios machine, and Appium can start the App.
The problem I encountered was that each time I automated the test, the APP was not started in an initial state, but logged in each time.My requirement is to log in every time I start the app.

Below is my desired capabilities
from appium.webdriver import Remote
caps = {
    "platformName": "iOS",
    "automationName": "XCUITest",
    "platformVersion": "13.3",
    "deviceName": "iPhone my8",
    "bundleId": "com.sinosun.bizmate.newace",
    "udid": "b1003e9e562c147324245fdfde14327f170b2444",
    "xcodeOrgId": "XXXXXXXXXX",
    "xcodeSigningId": "iPhone Developer",
    "preventWDAAttachments": False,
    # "showIOSLog": True,
    "noReset": False
}

driver = Remote(desired_capabilities=caps, command_executor='http://127.0.0.1:4723/wd/hub')
driver.implicitly_wait(10)

Below is Appium's log
[info] [35m[Appium][39m Welcome to Appium v1.21.0
[info] [35m[Appium][39m Non-default server args:
[info] [35m[Appium][39m   relaxedSecurityEnabled: true
[info] [35m[Appium][39m   allowInsecure: {
[info] [35m[Appium][39m   }
[info] [35m[Appium][39m   denyInsecure: {
[info] [35m[Appium][39m   }
[info] [35m[Appium][39m Appium REST http interface listener started on 0.0.0.0:4723[debug] [35m[HTTP][39m Request idempotency key: 09816455-1b0d-47e5-9054-6f9fb555cd26
[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{"capabilities":{"firstMatch":[{"platformName":"iOS","appium:automationName":"XCUITest","appium:platformVersion":"13.3","appium:deviceName":"iPhone my8","appium:bundleId":"com.sinosun.bizmate.newace","appium:udid":"b1003e9e562c147324245fdfde14327f170b2444","appium:xcodeOrgId":"D222W82U7H","appium:xcodeSigningId":"iPhone Developer","appium:preventWDAAttachments":false,"appium:noReset":false}]},"desiredCapabilities":{"platformName":"iOS","automationName":"XCUITest","platformVersion":"13.3","deviceName":"iPhone my8","bundleId":"com.sinosun.bizmate.newace","udid":"b1003e9e562c147324245fdfde14327f170b2444","xcodeOrgId":"D222W82U7H","xcodeSigningId":"iPhone Developer","preventWDAAttachments":false,"noReset":false}}[39m
[debug] [35m[W3C][39m Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","automationName":"XCUITest","platformVersion":"13.3","deviceName":"iPhone my8","bundleId":"com.sinosun.bizmate.newace","udid":"b1003e9e562c147324245fdfde14327f170b2444","xcodeOrgId":"D222W82U7H","xcodeSigningId":"iPhone Developer","preventWDAAttachments":false,"noReset":false},null,{"firstMatch":[{"platformName":"iOS","appium:automationName":"XCUITest","appium:platformVersion":"13.3","appium:deviceName":"iPhone my8","appium:bundleId":"com.sinosun.bizmate.newace","appium:udid":"b1003e9e562c147324245fdfde14327f170b2444","appium:xcodeOrgId":"D222W82U7H","appium:xcodeSigningId":"iPhone Developer","appium:preventWDAAttachments":false,"appium:noReset":false}]}]
[debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1628044519401 (10:35:19 GMT+0800 (中国标准时间))
[info] [35m[Appium][39m Appium v1.21.0 creating new XCUITestDriver (v3.43.0) session
[info] [35m[Appium][39m Applying relaxed security to 'XCUITestDriver' as per server command line argument. All insecure features will be enabled unless explicitly disabled by --deny-insecure
[debug] [35m[BaseDriver][39m W3C capabilities and MJSONWP desired capabilities were provided
[debug] [35m[BaseDriver][39m Creating session with W3C capabilities: {
[debug] [35m[BaseDriver][39m   "alwaysMatch": {
[debug] [35m[BaseDriver][39m     "platformName": "iOS",
[debug] [35m[BaseDriver][39m     "appium:automationName": "XCUITest",
[debug] [35m[BaseDriver][39m     "appium:platformVersion": "13.3",
[debug] [35m[BaseDriver][39m     "appium:deviceName": "iPhone my8",
[debug] [35m[BaseDriver][39m     "appium:bundleId": "com.sinosun.bizmate.newace",
[debug] [35m[BaseDriver][39m     "appium:udid": "b1003e9e562c147324245fdfde14327f170b2444",
[debug] [35m[BaseDriver][39m     "appium:xcodeOrgId": "D222W82U7H",
[debug] [35m[BaseDriver][39m     "appium:xcodeSigningId": "iPhone Developer",
[debug] [35m[BaseDriver][39m     "appium:preventWDAAttachments": false,
[debug] [35m[BaseDriver][39m     "appium:noReset": false
[debug] [35m[BaseDriver][39m   },
[debug] [35m[BaseDriver][39m   "firstMatch": [
[debug] [35m[BaseDriver][39m     {}
[debug] [35m[BaseDriver][39m   ]
[debug] [35m[BaseDriver][39m }
[warn] [35m[BaseDriver][39m The following capabilities were provided, but are not recognized by Appium:
[warn] [35m[BaseDriver][39m   preventWDAAttachments
[info] [35m[BaseDriver][39m Session created with session id: fa7c901f-5730-4328-bd63-1fb65eb80a81[debug] [35m[XCUITest][39m Current user: 'sinosun'
[debug] [35m[XCUITest][39m Available devices: b1003e9e562c147324245fdfde14327f170b2444
[debug] [35m[XCUITest][39m Creating iDevice object with udid 'b1003e9e562c147324245fdfde14327f170b2444'
[info] [35m[XCUITest][39m Determining device to run tests on: udid: 'b1003e9e562c147324245fdfde14327f170b2444', real device: true
[debug] [35m[BaseDriver][39m Event 'xcodeDetailsRetrieved' logged at 1628044521954 (10:35:21 GMT+0800 (中国标准时间))
[debug] [35m[BaseDriver][39m Event 'appConfigured' logged at 1628044521955 (10:35:21 GMT+0800 (中国标准时间))
[debug] [35m[BaseDriver][39m Event 'resetStarted' logged at 1628044521956 (10:35:21 GMT+0800 (中国标准时间))
[debug] [35m[XCUITest][39m Reset: running ios real device reset flow
[debug] [35m[BaseDriver][39m Event 'resetComplete' logged at 1628044521956 (10:35:21 GMT+0800 (中国标准时间))
[info] [35m[WebDriverAgent][39m Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent'
[info] [35m[WebDriverAgent][39m Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'[debug] [35m[XCUITest][39m Crash reports root '/Users/sinosun/Library/Logs/CrashReporter/MobileDevice/iPhone my8' does not exist. Got nothing to gather.
[debug] [35m[BaseDriver][39m Event 'logCaptureStarted' logged at 1628044522235 (10:35:22 GMT+0800 (中国标准时间))
[info] [35m[XCUITest][39m Setting up real device[debug] [35m[WebDriverAgent][39m No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[info] [35m[DevCon Factory][39m Requesting connection for device b1003e9e562c147324245fdfde14327f170b2444 on local port 8100, device port 8100
[debug] [35m[DevCon Factory][39m Cached connections count: 0
[info] [35m[DevCon Factory][39m Successfully requested the connection for b1003e9e562c147324245fdfde14327f170b2444:8100[debug] [35m[WebDriverAgent][39m Parsed BUILD_DIR configuration value: '/Users/sinosun/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Build/Products'
[debug] [35m[WebDriverAgent][39m Got derived data root: '/Users/sinosun/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp'
[debug] [35m[XCUITest][39m Starting WebDriverAgent initialization with the synchronization key '/Users/sinosun/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp'
[debug] [35m[WD Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[WD Proxy][39m Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[debug] [35m[WD Proxy][39m Got response with status 200: {"value":{"message":"WebDriverAgent is ready to accept commands","state":"success","os":{"testmanagerdVersion":28,"name":"iOS","sdkVersion":"14.5","version":"13.3"},"ios":{"ip":"10.2.30.191"},"ready":true,"build":{"upgradedAt":"1620631774000","time":"Aug  4 2021 10:13:40","productBundleIdentifier":"com.facebook.WebDriverAgentRunner"}},"sessionId":null}
[debug] [35m[WebDriverAgent][39m Upgrade timestamp of the currently bundled WDA: 1620631774000
[debug] [35m[WebDriverAgent][39m Upgrade timestamp of the WDA on the device: 1620631774000
[info] [35m[WebDriverAgent][39m Will reuse previously cached WDA instance at 'http://127.0.0.1:8100/' with 'com.facebook.WebDriverAgentRunner'. Set the wdaLocalPort capability to a value different from 8100 if this is an undesired behavior.
[debug] [35m[XCUITest][39m Trying to start WebDriverAgent 1 times with 10000ms interval
[debug] [35m[XCUITest][39m These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
[debug] [35m[BaseDriver][39m Event 'wdaStartAttempted' logged at 1628044527150 (10:35:27 GMT+0800 (中国标准时间))
[info] [35m[WebDriverAgent][39m Using provided WebdriverAgent at 'http://127.0.0.1:8100/'
[debug] [35m[WD Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[WD Proxy][39m Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[debug] [35m[WD Proxy][39m Got response with status 200: {"value":{"message":"WebDriverAgent is ready to accept commands","state":"success","os":{"testmanagerdVersion":28,"name":"iOS","sdkVersion":"14.5","version":"13.3"},"ios":{"ip":"10.2.30.191"},"ready":true,"build":{"upgradedAt":"1620631774000","time":"Aug  4 2021 10:13:40","productBundleIdentifier":"com.facebook.WebDriverAgentRunner"}},"sessionId":null}
[debug] [35m[BaseDriver][39m Event 'wdaSessionAttempted' logged at 1628044527171 (10:35:27 GMT+0800 (中国标准时间))
[debug] [35m[XCUITest][39m Sending createSession command to WDA
[debug] [35m[WD Proxy][39m Matched '/session' to command name 'createSession'
[debug] [35m[WD Proxy][39m Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.sinosun.bizmate.newace","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true,"shouldTerminateApp":true}],"alwaysMatch":{}}}[debug] [35m[WD Proxy][39m Got response with status 200: {"value":{"sessionId":"4162711B-EA92-4A51-960C-F654919DD98C","capabilities":{"device":"iphone","browserName":"BIZMATE","sdkVersion":"13.3","CFBundleIdentifier":"com.sinosun.bizmate.newace"}},"sessionId":"4162711B-EA92-4A51-960C-F654919DD98C"}
[info] [35m[WD Proxy][39m Determined the downstream protocol as 'W3C'
[debug] [35m[BaseDriver][39m Event 'wdaSessionStarted' logged at 1628044529749 (10:35:29 GMT+0800 (中国标准时间))
[debug] [35m[BaseDriver][39m Event 'wdaStarted' logged at 1628044529749 (10:35:29 GMT+0800 (中国标准时间))
[info] [35m[XCUITest][39m Skipping setting of the initial display orientation. Set the "orientation" capability to either "LANDSCAPE" or "PORTRAIT", if this is an undesired behavior.
[debug] [35m[BaseDriver][39m Event 'orientationSet' logged at 1628044529750 (10:35:29 GMT+0800 (中国标准时间))
[debug] [35m[BaseDriver][39m The value of 'elementResponseAttributes' setting did not change. Skipping the update for it
[debug] [35m[BaseDriver][39m The value of 'shouldUseCompactResponses' setting did not change. Skipping the update for it
[info] [35m[Appium][39m New XCUITestDriver session created successfully, session fa7c901f-5730-4328-bd63-1fb65eb80a81 added to master session list
[debug] [35m[BaseDriver][39m Event 'newSessionStarted' logged at 1628044529751 (10:35:29 GMT+0800 (中国标准时间))
[debug] [35m[W3C (fa7c901f)][39m Cached the protocol value 'W3C' for the new session fa7c901f-5730-4328-bd63-1fb65eb80a81
[debug] [35m[W3C (fa7c901f)][39m Responding to client with driver.createSession() result: {"capabilities":{"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"platformName":"iOS","automationName":"XCUITest","platformVersion":"13.3","deviceName":"iPhone my8","bundleId":"com.sinosun.bizmate.newace","udid":"b1003e9e562c147324245fdfde14327f170b2444","xcodeOrgId":"D222W82U7H","xcodeSigningId":"iPhone Developer","preventWDAAttachments":false,"noReset":false}}
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[32m200[39m [90m10358 ms - 573[39m
[info] [35m[HTTP][39m [90m[39m
[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/fa7c901f-5730-4328-bd63-1fb65eb80a81/timeouts[39m
[info] [35m[HTTP][39m [90m{"implicit":10000}[39m
[debug] [35m[W3C (fa7c901f)][39m Calling AppiumDriver.timeouts() with args: [null,null,null,null,10000,"fa7c901f-5730-4328-bd63-1fb65eb80a81"]
[debug] [35m[XCUITest][39m Executing command 'timeouts'
[debug] [35m[BaseDriver][39m W3C timeout argument: {"implicit":10000}}
[debug] [35m[BaseDriver][39m Set implicit wait to 10000ms
[debug] [35m[W3C (fa7c901f)][39m Responding to client with driver.timeouts() result: null
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session/fa7c901f-5730-4328-bd63-1fb65eb80a81/timeouts [39m[32m200[39m [90m4 ms - 14[39m
[info] [35m[HTTP][39m [90m[39m

## Environment

Appium version (or git revision) that exhibits the issue: 1.21.0
Last Appium version that did not exhibit the issue (if applicable):
Desktop OS/version used to run Appium: macOS Big Sur 11.3.1
Node.js version (unless using Appium.app|exe): 16.6.0
Npm or Yarn package manager: 7.19.1
Mobile platform/version under test: iOS 13.3
Real device or emulator/simulator: Real device
Appium CLI or Appium.app|exe:  Appium CLI and Appium.app|exe

## Details

I started the app by driving Appium in Python and failed to start from the login state each time.If I'm already logged in to the App, I'll be logged in to the App every time I automate the test.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by KazuCocoa** [comment]
We have no way to clean local data on iOS. This is iOS's limitation.

you should re-install the app or implement clearing the app local data in the app itself.
For instance, when the app process is launched with a particular environment variables or process argument, the app delete its local data
