### ISSUE TITLE
appium-adb: don't require JAVA_HOME to be set

### ISSUE THREAD

**Issue by Bubu** [appium/appium#15693]
## The problem

Trying to use appium on my system just results in the error message `The JAVA_HOME environment variable must be set for Android Tools to work properly` which is not true, the android tools work fine with the system java installation that can be found in PATH. In general on linux distributions don't use JAVA_HOME but instead you can just rely on `java` being the right thing to run. The shell-script wrappers around the android sdk tools do this correctly and work flawlessly on my system but I can't use appium without patching the internals of appium-adb scripts because I don't have `JAVA_HOME` set.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Desktop OS/version used to run Appium: Archlinux
* Node.js version (unless using Appium.app|exe): v14.17.3
* Npm or Yarn package manager: npm
* Mobile platform/version under test: android
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: cli and desktop app Appium-linux-1.21.0.AppImage

## Details

Patching `appium-adb/build/lib/helpers.js` to return just `java` from `getJavaForOs()` fixes the issue for me. This can ofc also be done as a fallback when JAVA_HOME isn't set for example.

**Comment by mykola-mokhnach** [comment]
Please check if https://github.com/appium/appium-adb/pull/573 works for your case

**Comment by mykola-mokhnach** [comment]
The PR has been merged and published

**Comment by Bubu** [comment]
Thanks a lot for the quick fix. Confirmed to work here. :tada:
