### ISSUE TITLE
appium-adb: no way to read stderr from shell commands that exit with code 0

### ISSUE THREAD

**Issue by dbjorge** [appium/appium#15696]
## The problem

We use `appium-adb` in [Accessibility Insights for Android](https://github.com/microsoft/accessibility-insights-web) to communicate with devices-under-test.

Today, I'm working on a new bit of functionality that's based on the `adb shell content` command. The command communicates errors in a way that's difficult for us to consume using `appium-adb` right now; it reports error information on stderr while returning a 0 exit code. To see an example of this, you can use `adb shell content read --uri content://doesnotexist` against any device/emulator.

Unfortunately, `appium-adb`'s `shell` method (via `adbExec`) currently throws away `stderr` when a command exits with code 0 ([see system-calls.js](https://github.com/appium/appium-adb/blob/290be9038aa5bb4ee16c4935403065ad191a205d/lib/tools/system-calls.js#L409)).

We'd love to have a way to invoke `adb shell` such that we can access `stderr` even if the command exits successfully.

## Environment

* Appium version (or git revision) that exhibits the issue: `appium-adb@8.13.2`
* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium: Windows 21H1 19043.1110
* Node.js version (unless using Appium.app|exe): 14.17.4
* Npm or Yarn package manager: yarn 1.22.11
* Mobile platform/version under test: Android emulator API level 30
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: n/a

## Details

We just want some way to be able to access stderr for this particular shell invocation - we aren't picky about the exact shape/naming of the API to do so. The default output behavior of `shell`/`adbExec` should probably stay as is for backcompat.

One example of an option we'd be happy with might be a new `outputFormat` option to `shell`/`adbExec` that:
* accepts either `stdout` or `full`
* defaults to `stdout`
* is checked during the `adbExec` success path; if `stdout`, `adbExec` matches the existing behavior and returns `stdout`, and if `full`, `adbExec` instead returns the full original output from `await teen_process.exec(...)` (ie, an object with `stdout`, `stderr`, and `code` properties)

## Link to Appium logs

n/a (issue not in full Appium)

## Code To Reproduce Issue [ Good To Have ]

```js
// in an empty node project with appium-adb added as a dependency
const appiumAdb = require('appium-adb');
const adb = new appiumAdb.ADB()
adb.shell('content read --uri content://doesnotexist').then(output => {
    // output is "", but the stderr content we'd like access to is along the lines of:
    //
    // Error while accessing provider:doesnotexist
    // java.lang.IllegalStateException: Could not find provider: doesnotexist
    //         at com.android.commands.content.Content$Command.execute(Content.java:518)
    //         at com.android.commands.content.Content.main(Content.java:727)
    //         at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
    //         at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
    console.log(JSON.stringify(output));
});
```

**Comment by dbjorge** [comment]
We'd be happy to contribute a PR adding this functionality, but I wanted to open an issue first to get your thoughts on

* whether this is functionality you'd be willing to accept
* what shape you'd like the API to be if so

**Comment by mykola-mokhnach** [comment]
I think it is completely fine to have an additional option there. Feel free to add a PR, we'd be happy to review it

**Comment by dbjorge** [comment]
Thanks for the quick followup, @mykola-mokhnach ! Do you have a preference between the `optionFormat` option I described above vs a `failOnStderr` option to throw an Error with stderr/stdout/code properties similar to the existing error path if a nonempty stderr is emitted? Either option is equally usable for us.

**Comment by jlipps** [comment]
The `optionFormat` example seems the simplest modification of the current code, but I'm open to @mykola-mokhnach's thoughts. Thanks for checking in, @dbjorge

**Comment by mykola-mokhnach** [comment]
I would go with `outputFormat` as well. The option seems more straightforward to me

**Comment by mykola-mokhnach** [comment]
The PR has been merged
