### ISSUE TITLE
What security settings in appium side we need to update so that iOS will show both webview and the native view for iOS hybrid app

### ISSUE THREAD

**Issue by vvelusamy1** [appium/appium#15694]
Its an hybrid app where the login page is a webview inside iOS App and the Appium log is here. Any idea why it does not gives me the webview content? any security thing that I need to enable / disable to show this option.?

[RemoteDebugger]     Application: "PID:1977"
[RemoteDebugger]         id: "PID:1977"
[RemoteDebugger]         isProxy: false
[RemoteDebugger]         name: "Safari"
[RemoteDebugger]         bundleId: "com.apple.mobilesafari"
[RemoteDebugger]         hostId: undefined
[RemoteDebugger]         isActive: false
[RemoteDebugger]         isAutomationEnabled: true
[RemoteDebugger] Checking for bundle identifiers: com.apple.WebKit.WebContent, process-com.apple.WebKit.WebContent, process-SafariViewService, com.apple.SafariViewService, *, testApp-bundleid
[RemoteDebugger] Found app id key 'PID:1981' for bundle 'com.apple.WebKit.WebContent'
[RemoteDebugger] Found app id key 'PID:1981' for bundle 'process-com.apple.WebKit.WebContent'
[RemoteDebugger] Found app id key 'PID:821' for bundle 'process-SafariViewService'
[RemoteDebugger] Found app id key 'PID:1981' for bundle 'com.apple.SafariViewService'
[RemoteDebugger] Found app id key 'PID:1981' for bundle '*'
[RemoteDebugger] Found app id key 'PID:1981' for bundle 'testApp-bundleid'
[RemoteDebugger] Trying out the possible app ids: PID:1981, PID:821 (try #1 of 20)
[RemoteDebugger] Skipping app 'PID:1981' because it is not active
[RemoteDebugger] Skipping app 'PID:821' because it is not active
[RemoteDebugger] Could not connect to a valid app after 20 tries.
[XCUITest] No available web pages: Could not connect to a valid app after 20 tries.
[XCUITest] No web frames found.
[MJSONWP (4c42c9eb)] Responding to client with driver.getContexts() result: ["NATIVE_APP"]
[HTTP] <-- GET /wd/hub/session/4c42c9eb-7502-4576-918a-f51a0f153e4d/contexts 200

**Comment by jlipps** [comment]
Is your app using the WKWebView or the old UIWebView?

**Comment by vvelusamy1** [comment]
@jlipps  its WKWebView.

**Comment by jlipps** [comment]
Please link to a gist of the full logs

**Comment by vvelusamy1** [comment]
@jlipps / @KazuCocoa  there are lot of info present in the log file regarding to our app and i removed almost what I know which is important however still i m not much comfortable to attach the full logs. However if you can specify what type of information that you're looking, then I shall try to find it. My apologies for the inconvenience and looking forward for the response.

**Comment by amedvedjev** [comment]
1) did you enable web inspector on phone?
2) can you access your webView with Safari browser from mac?
- connect phone to mac
- open app. open needed webview
- run Safari on mac
- can you access now webView on phone with Safari 'Developer' menu?
https://www.browserstack.com/guide/how-to-debug-on-iphone

**Comment by vvelusamy1** [comment]
> 1. did you enable web inspector on phone?
> 2. can you access your webView with Safari browser from mac?
> 
> * connect phone to mac
> * open app. open needed webview
> * run Safari on mac
> * can you access now webView on phone with Safari 'Developer' menu?
>   https://www.browserstack.com/guide/how-to-debug-on-iphone

my response:
1) iPad -> Settings ->Safari-> Advance -> Web Inspector -> Turned On already.
2) Open some application on safari app say "www.mywebtestapplication.com". Connected to Mac and open Safari-> Develop Menu-> Webview- Yes i can see www.mywebtestapplication.com from iPad safari in the Mac safari develop menu -> selected iPad. This works perfectly fine.

with Hybrid app, I did the following,
1) Opened hybrid app in my iPad thru appium UI.
2) Appium Ui-> refresh the page. Its a native view when it launched and works fine. get context -> Native_app
3) Now navigate my hybrid to webview. Refresh the Appium UI and still it shows Native_App for get all contexts.
4) Now I opened Safari on my Mac -> develop Menu-> selected the iPad and there I did not see anything to select, does not shows up at all. Meaning, there is nothing listed under my ipad option in safari Mac to select and view the webview unlike I done with ipad safari app for my application(refer screenshot)

Summary: Just with Safari App in iPad, I can able to access the webview with develop menu option under Mac but the same webview if i try to use it under hybrid app in iPad, there is nothing shows up to select and view the webview, it says not inspectable application. please refer the screenshot for the same. 
<img width="1090" alt="Screen Shot 2021-08-05 at 1 27 33 PM" src="https://user-images.githubusercontent.com/63931737/128417264-84f649ae-1c65-4ab4-a29a-8de9acf43031.png">

**Comment by jlipps** [comment]
@vvelusamy1 thank you. that means your hybrid webview is not of a kind that Apple developer tools can see. For that reason, Appium will not find it is an available context. The next step is to talk to your developers to figure out why the webview is not debuggable via Safari. Once you can get that resolved, then Appium should also work.

**Comment by vvelusamy1** [comment]
> @vvelusamy1 thank you. that means your hybrid webview is not of a kind that Apple developer tools can see. For that reason, Appium will not find it is an available context. The next step is to talk to your developers to figure out why the webview is not debuggable via Safari. Once you can get that resolved, then Appium should also work.

So, we do not need to have additional settings / Capabilities from Appium side in order to show the webview if the above issue gets resolved by my dev side? Can you please confirm?

**Comment by jlipps** [comment]
Yes. If the webview is available in safari devtools, it will show up in Appium. They use the same technology.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
