### ISSUE TITLE
Screen recording on ios simulator is not working

### ISSUE THREAD

**Issue by anirbandan** [appium/appium#15690]
## The problem

stop_recording_screen method fails for ios simulator

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS big sur 11.2.3
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: iPhone 12, iOS 14.4
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium.app

## Details

stop_recording_screen method fails for ios simulator with error

 ```
Selenium::WebDriver::Error::UnknownError:
       An unknown server-side error occurred while processing the command. Original error: The screen recorder utility has failed to store the actual screen recording at '/var/folders/7t/nmh45xm50fg4c1zcr5ktcp040000gp/T/202174-34782-nnvw9x.btln/appium_86f7be.mp4'
     # UnknownError: An unknown server-side error occurred while processing the command. Original error: The screen recorder utility has failed to store the actual screen recording at '/var/folders/7t/nmh45xm50fg4c1zcr5ktcp040000gp/T/202174-34782-nnvw9x.btln/appium_86f7be.mp4'
     #     at getResponseForW3CError (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
     #     at asyncHandler (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)
```

Here the path "/var/folders/7t/nmh45xm50fg4c1zcr5ktcp040000gp/T/202174-34782-nnvw9x.btln/" is accessible and I can create a file manually

## Link to Appium logs

https://gist.github.com/anirbandan/0ccc2a8f18240dfaa8aebb5652c82636

## Code To Reproduce Issue [ Good To Have ]

ruby code

@driver.start_recording_screen video_type: 'libx264'
recording = @driver.stop_recording_screen

**Comment by mykola-mokhnach** [comment]
It looks like the error is expected because an unexpected session reset has been done before deleting it. Such session reseat also resets the ffmpeg session, so no recording is running when `stop_recording_screen` API is called

**Comment by adan-babbel** [comment]
thanks for pointing it out. you can close the ticket.
