### ISSUE TITLE
Appium2.0 cann't install driver

### ISSUE THREAD

**Issue by lin907597898** [appium/appium#15697]
## The problem

I just installed Appium2.0 locally.But when I want to install the xcuitest/uiautomator2 driver, there encounter a problem

![image](https://user-images.githubusercontent.com/24429337/128451656-4c8870c7-0060-443f-9e82-2bf7384bacb2.png)

## Environment

* Appium version (or git revision) that exhibits the issue: 2.0.0-beta.12
* Desktop OS/version used to run Appium: Mac os 10.15.6 
* Node.js version (unless using Appium.app|exe):v14.5.0
* Npm or Yarn package manager: NPM 6.14.5

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/lin907597898/65795089efd4068e36f1a54de8d9c241

**Comment by jlipps** [comment]
what happens if you install appium globally and then just run `appium driver install` rather than via npx?

**Comment by KazuCocoa** [comment]
Just a note: I had no issue on my local with the same versions:

appium: 2.0.0-beta.12
npm: 6.14.5
node: 14.5.0

Node 14.16.0 and v12.21 also succeeded.

**Comment by lin907597898** [comment]
> what happens if you install appium globally and then just run `appium driver install` rather than via npx?

thanks for your advice.
I tried to install appium globally, and the driver can be installed normally.
Is there any difference between Appium2.0 and Appium1.xx, because according to my experience, partial installation will not have any effect on the version of Appium1.xx

**Comment by KazuCocoa** [comment]
No. Appium 2.0 can manage each driver, but others are the same.

Then, what about installing `appium@beta`? appium 2.0 installs the latest package version when it has no specific version in the installation command. `appium@beta` can install the same latest versions.

**Comment by lin907597898** [comment]
> No. Appium 2.0 can manage each driver, but others are the same.
> 
> Then, what about installing `appium@beta`? appium 2.0 installs the latest package version when it has no specific version in the installation command. `appium@beta` can install the same latest versions.

I have installed appium@beta and the corresponding version is appium@1.22.0-beta, and everything seems works well.

And one more thing I want to confirm, my project is preparing to use Appium 2.0, as long as the driver is installed correctly, are the corresponding capabilities and client startup way the same as Appium 1.xx?

**Comment by jlipps** [comment]
Hi @lin907597898 not everything will be the same. There's not a huge list of differences but for example capabilities will need to have the `appium:` prefix (though clients usually add this automatically), and the `appium:automationName` capability will be required. All the drivers themselves are basically working the same.

My suggestion is to just give it a go, and let us know if you run into anything unexpected. I'm working on a migration doc that will be ready in some time.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
