### ISSUE TITLE
Appium UiAutomator2 doesn't see Android resource-id, works fine with UiAutomator

### ISSUE THREAD

**Issue by NnikK** [appium/appium#15709]
## The problem

Appium UiAutomator2 doesn't see Android resource-id, works fine with UiAutomator:
`driver.find_elements_by_id("backText")`

## Environment

* Desktop OS/version used to run Appium: 1.21.0
* Mobile platform/version under test: Android 
* Real device or emulator/simulator:Real device 

## Link to Appium logs
uiautomator2 appium log: https://gist.github.com/NnikK/3579215009102bdaa73787f96632c07c#file-uiautomator2-log
uiautomator appium log: https://gist.github.com/NnikK/4112b0358b6769ba31339beba1f4ac22#file-uiautomator-log

## Source XML
source-xml: https://gist.github.com/NnikK/b0e698d93af8686e782ad793e5f1e50f#file-source-xml

## Code To Reproduce Issue
` <Text  testID="backText" >Go Back</Text>`

**Comment by mykola-mokhnach** [comment]
Possible duplicate of https://github.com/appium/appium/issues/15354

**Comment by mykola-mokhnach** [comment]
Closed because of no response
