### ISSUE TITLE
npm ERR! request to https://registry.cnpmjs.org/appium-doctor failed, reason: Hostname/IP does not match certificate's altnames: Host: registry.cnpmjs.org. is not in the cert's altnames: DNS:r.cnpmjs.org

### ISSUE THREAD

**Issue by macro-c** [appium/appium#15707]
run "npm install appium-doctor -g"

error raise.

**Comment by KazuCocoa** [comment]
Sorry, what is the registry? Probably https://github.com/cnpm/cnpmjs.org ?
Then, please ask the private repository's administrator.
