### ISSUE TITLE
Get currently running sessionId

### ISSUE THREAD

**Issue by PandaPandaPanda** [appium/appium#15701]
## The problem

I am writing a python script to retrieve the page source of my app through
`driver.page_source`
Appium returns them in XML but I want it in JSON. So I try to send raw HTTP requests to Appium server, but I need the sessionId for that. I tried 
`self.driver.session_id`
but apparently it gives a new sessionId.
Is there any workaround for this?

Or even better, is there a way to get page_source without having Appium parse it to XML?

**Comment by PandaPandaPanda** [comment]
Turns out I was running on Windows with Tidevice proxy, that is why the session_id is not working.

**Comment by PandaPandaPanda** [comment]
Still wants to know if there is a way to get JSON page_source with the driver through.

**Comment by KazuCocoa** [comment]
Is this for iOS device thing?
Then, you can call https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/WebDriverAgentLib/Commands/FBDebugCommands.m#L28 like `http://<device ip>:<port>/source?format=json` from the Appium/WDA (or via portforwarding)

**Comment by PandaPandaPanda** [comment]
I am still facing some small problem. The query format=json only works for my proxy, but when post straight to Appium it is not working but returns XML

My Appium port is 57927, my proxy port is 57928

while the following GET request returns with XML output
http://127.0.0.1:57927/wd/hub/session/02b4d7e5-afc5-41b0-874b-04992591caeb/source?format=json
on the GET request to my proxy is the query processed
http://127.0.0.1:57928/source?format=json

**Comment by PandaPandaPanda** [comment]
> Is this for iOS device thing?
> Then, you can call https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/WebDriverAgentLib/Commands/FBDebugCommands.m#L28 like `http://<device ip>:<port>/source?format=json` from the Appium/WDA (or via portforwarding) without session id. this may help.

I am still facing some small problem. The query format=json only works for my proxy, but when post straight to Appium it is not working but returns XML

My Appium port is 57927, my proxy port is 57928

while the following GET request returns with XML output
http://127.0.0.1:57927/wd/hub/session/02b4d7e5-afc5-41b0-874b-04992591caeb/source?format=json
on the GET request to my proxy is the query processed
http://127.0.0.1:57928/source?format=json

**Comment by KazuCocoa** [comment]
It is expected. Appium itself does not provide the feature since it follows W3C WebDeiver spec.
