### ISSUE TITLE
The application crashes while running tests (xcode 12.5)

### ISSUE THREAD

**Issue by mankoffs** [appium/appium#15700]
## The problem

The application crashes after a while, with an error -  [WD Proxy] Got response with status 400: {"value":{"error":"invalid element state","message":"The application under test with bundle id '...' is not running, possibly crashed"...}}

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable):1.18.3
* Desktop OS/version used to run Appium: macOS Big Sur 11.5.1
* Node.js version (unless using Appium.app|exe): 16.2.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iPhone 11 Pro / 14.6
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium.app

## Link to Appium logs

https://gist.github.com/mankoffs/5431d74ef814970650873d7f9c3cf8f0

**Comment by mykola-mokhnach** [comment]
How the application is related to Appium?

**Comment by mankoffs** [comment]
@mykola-mokhnach  I found that similar problems were discussed in this project. And apparently, the problem was never solved. I assumed that perhaps there was some information related to this problem or something else.

**Comment by mykola-mokhnach** [comment]
I mean the fact the the application under test crashes has little to do with the automation stuff itself. Have you tried to check the application logs and fix the crash?

**Comment by mykola-mokhnach** [comment]
Closed because of no response
