### ISSUE TITLE
appium-flutter-driver automated test  Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by lztestjust** [appium/appium#15705]
## The problem

Use appium to execute pure flutter APP to automatically report errors

## Environment
1.Use npm install appium，Appium version is 1.21.0（with appium-flutter-driver）
2.Node.js version is v14.15.0
3.SDK Mobile platform/version is 29
4.Real Android device
5.python 3.7(install Appium-Python-Client,Appium-Flutter-Finder)

## Details

- 1.Start appium:

   Start appium in cmd：appium

- 2.Execute python testCase script:

  from appium.webdriver import Remote

  if __name__ == '__main__':
   ANDROID_FLUTTER_CAPS = {
      'appPackage': '[appPackage]',
      ‘appActivity’: '[appActivity]'
      'automationName': 'Flutter',
      'platformName': 'Android',
      'platformVersion': '10.0',
      'deviceName':  'Android Emulator'
  }
  driver = Remote('http://127.0.0.1:4723/wd/hub', desired_capabilities=ANDROID_FLUTTER_CAPS)

- 3.the appium-site debug info:

  [debug] [W3C] Encountered internal error running command: TypeError: Cannot read property 'match' of undefined
  [debug] [W3C]     at Object.exports.processLogToGetobservatory (C:\Users\111\AppData\Roaming\npm\node_modules\appium\node_modules\appium-flutter-driver\build\driver\lib\sessions\observatory.js:118:9)
  [debug] [W3C]     at Object.exports.getObservatoryWsUri (C:\Users\111\AppData\Roaming\npm\node_modules\appium\node_modules\appium-flutter-driver\lib\sessions\android.ts:35:21)
  [debug] [W3C]     at Object.exports.startAndroidSession (C:\Users\111\AppData\Roaming\npm\node_modules\appium\node_modules\appium-flutter-driver\lib\sessions\android.ts:26:28)
  [debug] [W3C]     at runMicrotasks (<anonymous>)
  [debug] [W3C]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
  [debug] [W3C]     at FlutterDriver.exports.createSession (C:\Users\111\AppData\Roaming\npm\node_modules\appium\node_modules\appium-flutter-driver\lib\sessions\session.ts:18:47)
  [debug] [W3C]     at AppiumDriver.createSession (C:\Users\111\AppData\Roaming\npm\node_modules\appium\lib\appium.js:387:35)
  [HTTP] <-- POST /wd/hub/session 500 8628 ms - 639
  [HTTP]
 
  ![1628503067(1)](https://user-images.githubusercontent.com/24455387/128691722-f97e91b1-afe9-49d9-a483-7d6acfcba965.png)

- 4.appium-site logs:

  [appium-site-log.txt](https://github.com/appium/appium/files/6953602/appium-site-log.txt)

**Comment by mykola-mokhnach** [comment]
Please report your issue to https://github.com/truongsinh/appium-flutter-driver
Appium team does not maintain this driver.

**Comment by lztestjust** [comment]
thanks
