### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: lower must be less than or equal to upper

### ISSUE THREAD

**Issue by shawn0726** [appium/appium#15708]
## Problem

When I use the selector function of the mobile phone keyboard to select characters from back to front, and then use appium-desktop inspector ‘Refresh Source & Screenshot’ this error occurs, but when I select the characters from front to back, there is no problem.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.15.0
* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium: macOS Mojave 10.14.6
* Node.js version (unless using Appium.app|exe): v12.11.1
* Npm or Yarn package manager: npm
* Mobile platform/version under test: vivo Android 8.1.0
* Real device or emulator/simulator: real
* Appium CLI or Appium.app|exe: n/a

## Details
error occurs：
![image](https://user-images.githubusercontent.com/53325467/128823978-fef49c69-347d-442e-b39f-2cf7d9555bc2.png)
no problem：
![image](https://user-images.githubusercontent.com/53325467/128824078-38c694e8-8e24-41d2-88f9-652a819f2cb5.png)

## Link to Appium logs
https://gist.github.com/shawn0726/beb0c610cb61ba26ffd132b803b4ad5f

**Comment by mykola-mokhnach** [comment]
It looks like some of the accessibility components on this screen returns corrupted information about its selection range (e.g. the lower bound is greater than the upper one). I'll add a workaround for this to the future versions of the server, but in order to fix the current issue the application under test must be fixed.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue. Also the patch has been pushed to appium@beta
