### ISSUE TITLE
1.22.0-beta.0 & Xcode 13 - Beta 5 - send_keys is super slow

### ISSUE THREAD

**Issue by shaky** [appium/appium#15714]
I'm using **1.22.0-beta.0** and **Xcode 13 - Beta 5** and I noticed that **send_keys** is super slow, it types letter by letter instead of sending the full string as before.

The same version of appium but with a **Xcode 13 - Beta 4** simulator works just fine. 

## Environment
* Appium version (or git revision) that exhibits the issue: **1.22.0-beta.0**
* Node.js version (unless using Appium.app|exe): **v14.17.5**
* Real device or emulator/simulator: **iPhone 11 - iOS 11 (Xcode 13 - Beta 5)**

Thank You!

**Comment by KazuCocoa** [comment]
It seems the latest iOS 15 behaves so.
Keystroke of iOS 15 was slower than older iOS simulators with Xcode 15 beta 5.
Could you check the behavior with vanilla XCTest and report it to Apple?


Note:
animationCoolOff and maxTypingFrequency did not help.

**Comment by shaky** [comment]
Thank you for your reply @KazuCocoa! We'll create a vanilla project and try to report it. 
I'll come back with feedback.

**Comment by KazuCocoa** [comment]
I haven't tested with iOS 11 as you addressed (probably a real device?), but iOS 14.7 real device had no this slowness, so I guess the latest iOS 15 has an issue.
(I don't have iOS 15 beta 4 device since I just updated to the latest my device for beta...)

**Comment by shaky** [comment]
hi @KazuCocoa, thank you for your help!

We've raised https://feedbackassistant.apple.com/feedback/9493046 as we managed to replicate on a vanilla project.

Videos attached in case anyone else runs into the same issue:
[Xcode 12.5 - WORKS](https://user-images.githubusercontent.com/4169832/129182402-d17e50ba-127a-46fd-9845-a270bc3714e3.mp4)
[Xcode-13-Beta-5 - BROKEN](https://user-images.githubusercontent.com/4169832/129182486-9cfd2c6b-0bb1-42e5-b36f-04744b814ca6.mp4)

Thank You!

**Comment by KazuCocoa** [comment]
I've also reported this issue to Apple last week. Let's close this issue since this issue is Apple's one.

I hope their next dev release will have improvement...

**Comment by KazuCocoa** [comment]
This slowness seems still happening in Xcode 15 rc1

**Comment by shaky** [comment]
hi @KazuCocoa, I'm getting the same slowness indeed. Is there a workaround I can use? thank you!

**Comment by KazuCocoa** [comment]
I think no, unfortunately. It happens also in vanilla XCTest, so the root is XCTest/iOS internal...

**Comment by KazuCocoa** [comment]
An iOS 15.1 beta real device had no this slowness. so, this issue is probably only on iOS 15.0 simulators/real devices.

**Comment by KazuCocoa** [comment]
Removed from pin
