### ISSUE TITLE
Reorganize non-W3C and non-generic routes

### ISSUE THREAD

**Issue by jlipps** [appium/appium#15729]
With Appium 2.0, we should ensure that we are not allowing any old (m)jsonwp routes/commands. At a first stage, we can simply remove these from the router to disable access. At the same time or later, we can clean up any handlers related to those routes.

* [ ] identify which if any non-W3C methods/routes we want to keep
* [ ] mark non-W3C methods as deprecated in clients
* [ ] move non-generic, driver-specific routes to the drivers that support them as extra methods exported by the drivers
* [ ] remove deprecated implementations from drivers, or migrate them to driver extensions or `mobile:` commands
* [ ] remove the moved/reorganized/deprecated routes from base driver

**Comment by KazuCocoa** [comment]
One note is some of MJSONWP are used in our regular usage.

We should move them to `mobile:` command or keep them as appium route.
Afaik, https://github.com/appium/ruby_lib_core/blob/master/lib/appium_lib_core/common/command/w3c.rb#L20-L51 is.
(`status` is now in W3C tho)

We can remove routes that are compatible with MJSONWP and W3C safely.

**Comment by mykola-mokhnach** [comment]
+1 to what @KazuCocoa mentioned
I'd rather make sure first all our drivers only use W3C protocol (Safari web context does not, for example)

**Comment by jlipps** [comment]
Yes, good idea. Let's first make sure all the internal components of every supported driver fully understand W3C.
