### ISSUE TITLE
App gets closed automatically 

### ISSUE THREAD

**Issue by aryalakshmi** [appium/appium#15731]
## The problem

While automating app and run in progress, app gets closed automatically randomly at different screens
## Environment

* Appium version (or git revision) that exhibits the issue: v1.22.0-beta.0
* Last Appium version that did not exhibit the issue (if applicable): . 1.9.1
* Desktop OS/version used to run Appium:  Windows 10
* Node.js version (unless using Appium.app|exe): 
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Reak device
* Appium CLI or Appium.app|exe: CLI 

## Details

App gets closed while execution is in progress randomly at different testcases

## Link to Appium logs
appium logs:
https://gist.github.com/aryalakshmi/cc5c55766434cff72a9b8486e29f98a4

logcat messages:
https://gist.github.com/aryalakshmi/02e96eba30ccee10709986782f1d5fb2

## Code To Reproduce Issue [ Good To Have ]

desired capabilities used:
Open Application	http://localhost:4723/wd/hub	alias=NokiaApp	platformName=Android platformVersion=10 udid=${udidA}	deviceName=Pixel	autoWebview=true	newCommandTimeout=1200	appPackage=${package}	appActivity=${package}.MainActivity	disableWindowAnimation=true	noReset=false	automationName=UiAutomator2

**Comment by mykola-mokhnach** [comment]
Not sure how this is related to Appium. Did you check the device logs for possible app crash stack traces?

**Comment by aryalakshmi** [comment]
@mykola-mokhnach There are no crash traces in app whereas appium has below error:

[W3C (a2837c02)] Driver proxy active, passing request on via HTTP proxy
[debug] [WD Proxy] Matched '/wd/hub/session/a2837c02-da5c-47aa-978e-51743992595b/source' to command name 'getPageSource'
[debug] [WD Proxy] Proxying [GET /wd/hub/session/a2837c02-da5c-47aa-978e-51743992595b/source] to [GET http://127.0.0.1:8002/wd/hub/session/1d3c035f45c35f10a5de65d19cf73b9c/source] with no body
[debug] [WD Proxy] Got response with status 200: {"value":"<html lang=\"en\" class=\"plt-android plt-phablet plt-cordova plt-capacitor plt-mobile plt-hybrid ios hydrated\" mode=\"ios\"><head>\n<script type=\"text/javascript\">window.Capacitor = { DEBUG: true };\n\n//# sourceURL=capacitor-runtime.js\n\n(function(win) {\n  win.Capacitor = win.Capacitor || {\n    Plugins: {}\n  };\n\n  var capacitor = Capacitor;\n\n  // Export Cordova if not defined\n  win.cordova = win.cordova || {};\n\n  // Add any legacy handlers to keep Cordova compat 100% good\n  addLegacyHandlers(win);\n\n  capacitor.Plugins = capacitor.Plugins || {};\n  \n  capacitor.DEBUG = typeof capacitor.DEBUG === 'undefined' ? true : capacitor.DEBUG;\n\n  // keep a collection of callbacks for native response data\n  var calls = {};\n\n  // Counter of callback ids, randomized to avoid\n  // any issues during reloads if a call comes back with\n  // an existing callback id from an old session\n  var callbackIdCount = Math.floor(Math.random() * 134217728);\n\n  var lastError = null;\n  var errorModa...
[HTTP] <-- GET /wd/hub/session/a2837c02-da5c-47aa-978e-51743992595b/source 200 424 ms - 1309997
[HTTP]
[BaseDriver] Shutting down because we waited 1200 seconds for a command
[Appium] Closing session, cause was 'New Command Timeout of 1200 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
[Appium] Removing session '69df22d5-5160-4afd-87f0-68d1304d0d90' from our master session list
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [AndroidDriver] Stopping chromedriver for context WEBVIEW_com.nokia.wifi
[debug] [Chromedriver] Changed state to 'stopping'
[debug] [WD Proxy] Proxying [DELETE /] to [DELETE http://127.0.0.1:8000/wd/hub/session/beaf0615d3e899ca8361cbd94ae6a2fc] with no body
[WD Proxy] Got response with status 500: {"value":{"error":"unknown error","message":"unknown error: Failed to kill forward port of device HT6AF0202985: 59532: . unknown error: The adb command failed. Extra response: <listener 'tcp:59532' not found>.\n  (Session info: chrome=92.0.4515.115)","stacktrace":"Backtrace:\n\tOrdinal0 [0x002D2A33+2501171]\n\tOrdinal0 [0x0026D1C1+2085313]\n\tOrdinal0 [0x00171FA8+1056680]\n\tOrdinal0 [0x001567DB+944091]\n\tOrdinal0 [0x0016162F+988719]\n\tOrdinal0 [0x00159B80+957312]\n\tOrdinal0 [0x0015ED3D+978237]\n\tOrdinal0 [0x001BAD0F+1355023]\n\tOrdinal0 [0x001B558C+1332620]\n\tOrdinal0 [0x00191D74+1187188]\n\tOrdinal0 [0x00192BD9+1190873]\n\tGetHandleVerifier [0x0044EFE6+1504438]\n\tGetHandleVerifier [0x004FDDA5+2220661]\n\tGetHandleVerifier [0x00355589+481881]\n\tGetHandleVerifier [0x00354639+477961]\n\tOrdinal0 [0x002728BD+2107581]\n\tOrdinal0 [0x00276728+2123560]\n\tOrdinal0 [0x00276862+2123874]\n\tOrdinal0 [0x0027FA81+2161281]\n\tBaseThreadInitThunk [0x767A6359+25]\n\tRtlGetAppContainerNamedObjectPath [0x772287A4+...
[debug] [W3C] Matched W3C error code 'unknown error' to UnknownError
[Chromedriver] UnknownError: An unknown server-side error occurred while processing the command. Original error: unknown error: Failed to kill forward port of device HT6AF0202985: 59532: . unknown error: The adb command failed. Extra response: <listener 'tcp:59532' not found>.
[Chromedriver]   (Session info: chrome=92.0.4515.115)
[Chromedriver]     at errorFromW3CJsonCode (C:\Users\janp\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:780:25)
[Chromedriver]     at ProxyRequestError.getActualError (C:\Users\janp\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:663:14)
[Chromedriver]     at JWProxy.command (C:\Users\janp\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:272:19)
[Chromedriver]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[Chromedriver]     at Chromedriver.stop (C:\Users\janp\AppData\Roaming\npm\node_modules\appium\node_modules\appium-chromedriver\lib\chromedriver.js:598:7)
[Chromedriver]     at AndroidUiautomator2Driver.stopChromedriverProxies (C:\Users\janp\AppData\Roaming\npm\node_modules\appium\node_modules\appium-android-driver\lib\commands\context.js:272:7)
[Chromedriver]     at AndroidUiautomator2Driver.deleteSession (C:\Users\janp\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:598:9)
[Chromedriver]     at AndroidUiautomator2Driver.startUnexpectedShutdown (C:\Users\janp\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\driver.js:378:7)
[Chromedriver]     at Timeout._onTimeout (C:\Users\janp\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\commands\timeout.js:141:5)
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: 'DELETE /' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
[debug] [ADB] Running 'C:\Users\janp\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s HT6AF0202985 shell am force-stop com.nokia.wifi'

**Comment by mykola-mokhnach** [comment]
This log message means that there was no any command from the client side within 1200 seconds, so the session has been deleted. I don't see any problems there on the server side

**Comment by aryalakshmi** [comment]
But, the server was never idle for 20minutes (1200 seconds) and the app is getting closed while its in use.

**Comment by mykola-mokhnach** [comment]
It could be that some previous session has not been closed properly. If this session was running on the same device then it also tries to delete the connection to add upon closing, which makes the current session to fail as well. Thus, make sure you manage your sessions properly or make sure to enable the `session-override` command line option to ensure previous session(s) get closed automatically as soon as new one is started.

**Comment by aryalakshmi** [comment]
@mykola-mokhnach Thanks for your support. Issue is not seen after adding session-override parameter.

Currently, appium is started as below:
appium -a 127.0.0.1 -p 4723 --chromedriver-executable C:\Users\aryalakr\AppData\Roaming\npm\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe --session-override
