### ISSUE TITLE
'POST /element' cannot be proxied to UiAutomator2 server

### ISSUE THREAD

**Issue by VitorJeremias** [appium/appium#15739]
## The problem

When I run my tests, the JUnit failure trace shows the following error:
`org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: 'POST /element' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details`

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2
* Desktop OS/version used to run Appium: Linux Mint 20 Cinnamon 4.6.7
* Node.js version (unless using Appium.app|exe): v10.19.0 
* Npm or Yarn package manager: 7.20.0
* Mobile platform/version under test: Android 11 Emulator (Based on: Android API 30 Tag/ABI: google_apis/x86_64)
* Real device or emulator/simulator: Emulator

## Details

It only happens (and always happens) the first time I run the tests after starting the Android emulator.

## Link to Appium logs
Appium Logs: https://gist.github.com/VitorJeremias/fd99c330fb1a7b279fa3efb0117b862e
Logcat output: https://gist.github.com/VitorJeremias/54807f1b27a01eb14f46ea802b7c709e

## Code To Reproduce Issue [ Good To Have ]

The test simply instantiates the driver and forces a fail (`AssertTrue(False)`). After it fails, I use TestWatcher to get some info from the error:

```
    @Rule
     public TestRule testeRule = new TestWatcher() {

		@Override
		protected void failed(Throwable exception, Description description) {
			TestReportManager reportManager = new TestReportManager(driver);
			reportManager.getAppLogFile(description);
		};

		@Override
		protected void finished(Description description) {
			closeCrashView(); // This closes any alerts that may eventually appear in the tests
                        quitDrivers();
		}

	};
```
Note: The `getAppLogFile()` method runs the following commands:
`export PATH=$PATH:/home/$USER/AndroidSDK/platform-tools ; adb -s emulator-5554 root`
`adb -s emulator-5554 pull /sdcard/Android/data/com.csg.securechat/files/logging/activity.log /home/vitor/Documents/AutomatedTests/Reports/activity.log`

**Comment by KazuCocoa** [comment]
Could you get the logcat more?
The logcat log ended with the below appium command section. https://gist.github.com/VitorJeremias/fd99c330fb1a7b279fa3efb0117b862e#file-appium-logs-L206

**Comment by VitorJeremias** [comment]
It's been truncated due to the log's size. There's a button to view the full file at the beginning of the gist.

**Comment by KazuCocoa** [comment]
I see, but the raw ends with the result of screenshot API response.
https://gist.githubusercontent.com/VitorJeremias/54807f1b27a01eb14f46ea802b7c709e/raw/324077ccb1f158a7af943bc62a388d46aed97fc3/Logcat%2520output

```
08-17 14:10:02.011  4721  4721 D goldfish-address-space: allocate: Ask for block of size 0x100
08-17 14:10:02.019  4721  4721 D goldfish-address-space: allocate: ioctl allocate returned offset 0x3efffe000 size 0x2000
08-17 14:10:02.069  4721  4721 D HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_sync_buffer_data GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_async_frame_commands ANDROID_EMU_gles_max_version_3_0 
08-17 14:10:02.418  4592  4621 I appium  : AppiumResponse: {"sessionId":"ccc5ed4e-5910-4b75-b1d2-8054ab5db550","value":"iVBORw0KGgoAAAANSUhEUgAABaAAAAoACAYAAABH9IXPAAAAAXNSR0IArs4c6QAAAARzQklUCAgI\nCHwIZIgAACAASURBVHic7N1pd5znedjx65nBThDcd4qSaC22FTny0iRNnLjN1rQv+3nyop8q5zS1\n09qJEyd1ndiKZVsLRVESdxIkQKyDmemLGzCJfZtrFvD3OwdHwnDmmQcrD//PPdddxZ//dTsAAAAA\nAKDDa…
08-17 14:10:03.056   358  4729 I adbd    : adbd restarting as root
```

**Comment by mykola-mokhnach** [comment]
The last log line is `08-17 14:10:03.056   358  4729 I adbd    : adbd restarting as root`. Since no more lines are provided I could assume that this might be a reason for an unexpected server disconnection (e.g. restarting adb also resets all active port forwarding sessions).

**Comment by VitorJeremias** [comment]
That could make sense, but why would it only display the error the first time I run the tests after starting the emulator? 🤔

**Comment by VitorJeremias** [comment]
I've rerun the tests and grabbed the logcat from after the screenshot API response: https://gist.github.com/VitorJeremias/5673d4a14a45bd94e6d89a3e9f1b71ad

**Comment by mykola-mokhnach** [comment]
> 08-17 16:35:51.097  4594  4613 E tomator2.serve: failed to connect to jdwp control socket: Connection refused

My previous assumption was correct. restarting adb in root mode also resets all connections. Nothing we could do there from Appium side though

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
