### ISSUE TITLE
Appium capability 'noReset' = true not working on Android emulators (Using android studio emulator)

### ISSUE THREAD

**Issue by Gocoollnath** [appium/appium#15736]
## The problem

Appium capability 'noReset' = true not working on Android emulators (Using android studio emulator)

## Environment

* Appium version 1.21:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: Android 11 emulator
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Appium.exe

## Details

I have set Appium capability 'noReset' to 'true'. It is working fine on real android devices but on emulator, it doesn't take effect making app data and cache to be cleared before test run.

## Code To Reproduce Issue [ Good To Have ]

      var options = new AppiumOptions { PlatformName = "Android" };
      options.AddAdditionalCapability(MobileCapabilityType.NewCommandTimeout, int.Parse(NewCommandTimeout));
      options.AddAdditionalCapability("adbExecTimeout", 150000);      
      options.AddAdditionalCapability("noReset" , true);
      options.AddAdditionalCapability("avd", "Android11");
      options.AddAdditionalCapability("avdLaunchTimeout", 300000);
      options.AddAdditionalCapability("avdReadyTimeout", 300000);
      options.AddAdditionalCapability(AndroidMobileCapabilityType.AppPackage, AppPackageName);
      options.AddAdditionalCapability(AndroidMobileCapabilityType.AppActivity, AppPackageName + "." + AppStartActivity);
      var driver = GetTestDeviceDriver(deviceName, options, true) (Custom method to initialize driver)

**Comment by mykola-mokhnach** [comment]
Please fill out the issue report properly and attach the necessary logs

**Comment by Gocoollnath** [comment]
@mykola-mokhnach added the code and other details. Please, let me know if further details are required.

**Comment by mykola-mokhnach** [comment]
The Appium server log is still missing

**Comment by Gocoollnath** [comment]
I will close the issue, as deleting and building new AVD did the trick. Thanks
