### ISSUE TITLE
renovate should ignore sample-code / examples dirs

### ISSUE THREAD

**Issue by boneskull** [appium/appium#15740]
I'm seeing open PRs from renovate which upgrade things in `sample-code`; that's unnecessary IMO.  Let's tell Renovate to ignore these.  I'm unsure where Renovate is configured.  @jlipps?

**Comment by jlipps** [comment]
I don't see any open PRs from renovate. I think you mean dependabot? I'm not sure how dependabot is configured, but it's only configured for `master` anyway. My vote is to just use renovate moving forward. I'm fine if we want to just turn off dependabot all together
