### ISSUE TITLE
[WebDriverAgent] xcodebuild exited with code '75' and signal 'null' [WebDriverAgent] xcodebuild exited with code 'null' and signal 'SIGTERM'

### ISSUE THREAD

**Issue by mdhaseebpes** [appium/appium#15764]
## The problem

Am getting this error on parallel execution via running Simulators . IF am running with individual Simulator it works fine and also if am running cross platform parallel like  emulator and simulator is working fine

Issue with via multiple instance of simulator .could you please help me in resolving this issue because mostly am in IOS automation and I could require running scripts with multiple simulator or real devices  using cucumber framework FYI

## Environment

* Appium java-client  7.5.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* 16.6.2
* 7.20.3

* simulators

**Comment by mykola-mokhnach** [comment]
Please provide the full log and make sure you follow the tutorial for parallel execution: https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/parallel-tests.md

**Comment by mykola-mokhnach** [comment]
Closed because of no response
