### ISSUE TITLE
WebDriverAgent throws exception after calling the same element 100+ times

### ISSUE THREAD

**Issue by alei01** [appium/appium#15763]
## The problem

On WebDriverAgent >=v3.10.0 we're facing an issue for iOS:
after 100+ iterations using the same element during one session, WD throws NoSuchElementError.
according to the appium server logs, this issue could be caused by caching mechanism.

## Environment

* Appium version (or git revision) that exhibits the issue: WDA >=v3.10.0
* Last Appium version that did not exhibit the issue (if applicable): v3.9.2
* Desktop OS/version used to run Appium: MacOS 11.5.1 Big sur
* Node.js version (unless using Appium.app|exe): v16.3.0
* Npm or Yarn package manager: npm 7.15.1
* Mobile platform/version under test: iOS 14.7.1, 14.6
* Real device or emulator/simulator: real
* Appium CLI or Appium.app|exe: cli

## Details

We have a simple test that loops the next scenario:
1. Open the app
2. Close system messages if exist
3. Open the debug options by clicking on the logo
4. Makes app terminate/activate

Element's search strategy is iOSNsPredicate.
After 135+ iteration test starts failing due to the element NoSuchElement message. 
This issue is reproducing only with WDA >=v3.10.0

## Link to Appium logs

[GIST](https://gist.github.com/alei01/4bd716c3cbd140228bcdc571dd60a2e3)

**Comment by mykola-mokhnach** [comment]
This looks like a bug in LRU cache implementation. Please try if https://github.com/appium/WebDriverAgent/pull/527 works for you

**Comment by alei01** [comment]
Testing passed with 200+ iterations

**Comment by mykola-mokhnach** [comment]
Thanks for checking it. Pushed the patch to appium@beta
