### ISSUE TITLE
Feature request: Can you provide iOS and Android Mobile App to test and debug Apps created with Appium?

### ISSUE THREAD

**Issue by inglesuniversal** [appium/appium#15771]
It would be awesome if it can work on a real device rather than a simulator.

Best regards

**Comment by KazuCocoa** [comment]
We usually use the below repositories for tests.
https://github.com/appium/android-apidemos
https://github.com/appium/ios-uicatalog
Prebuilt ones are https://github.com/appium/appium/tree/master/sample-code/apps

iOS requires your provisioning profile, so please build it by yourself.
https://developer.apple.com/documentation/appstoreconnectapi/profiles
