### ISSUE TITLE
Unable to getScreenshot in ReactJS hybrid app

### ISSUE THREAD

**Issue by posjkh22** [appium/appium#15783]
## The problem

when I change to the webview context in appium inspector, unable to getScreenshot.
Recently, i try to change my hybrid app from angularJs-based hybrid app to reactJs-based hybrid app.
The inspector works well in the angularJs-based hybrid app. 
But, in reactJs-based hybrid app, getScreenshot in webview context is not working well.
I just got a timeout in getScreenshot.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable):1.21.0
* Desktop OS/version used to run Appium: Android
* Node.js version (unless using Appium.app|exe): v14.16.1
* Npm or Yarn package manager: 6.14.12
* Mobile platform/version under test:  Android 9
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

## Details

But, in reactJs-based hybrid app, getScreenshot in webview context is not working well.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
