### ISSUE TITLE
Command timeout on appium-adb

### ISSUE THREAD

**Issue by kuba21333** [appium/appium#15787]
##Problem

While trying to copy apps from /data/app to my projects directory command errored saying:

`(node:17172) UnhandledPromiseRejectionWarning: Error: Command 'adb -P 5037 pull /data/app <project directory>' timed out after 60000ms
`
## Environment
OS: Win 10
Node.js:  14.16.0
Real device

## Code To Reproduce Issue [ Good To Have ]

```
const appuimADB = require('appium-adb');
const  {ADB} = appuimADB
let adb = new ADB();

getApps()

function getApps() {
    adb.root();
    adb.pull('/data/app', '<project directory>');
    console.log("pulling apps.");
};
```

**Comment by Andrewngabriel** [comment]
I've gone ahead and created a [PR here](https://github.com/appium/appium-adb/pull/575) to modify the pull command to accept an options object with default timeout.

**Comment by mykola-mokhnach** [comment]
Thanks for adding the patch @Andrewngabriel. It has been published, thus closing the issue.
