### ISSUE TITLE
I CAN NOT IMPLEMENT CUSTOM WDA SERVER TO start before test script

### ISSUE THREAD

**Issue by mohamed8681** [appium/appium#15792]
## The problem

my wda is deleted after install app through real device iOS 
i need to use the

 https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/wda-custom-server.md 

custom wda server but i failed to implantation that  i can not run the helper  class WDAServer 
 if one has the full script with all imports it will help me to make WebDriveragent existed as long as possible because the script is failed 

although i use capabilities 
  cap.setCapability(IOSMobileCapabilityType.USE_PREBUILT_WDA, true); // no need to build WDA. in case you build it manually after appium reinstall/install.
		            cap.setCapability(IOSMobileCapabilityType.USE_NEW_WDA, false); // do not update WDA on phone if it exists. use with caution! after reinstall appium you should set it true at least one time
		           cap.setCapability("wdaStartupRetries", "4");
		            cap.setCapability("wdaStartupRetryInterval", "20000");

**Comment by mykola-mokhnach** [comment]
Kindly use Appium forum to ask questions. Closed as not an issue.
