### ISSUE TITLE
appium 2.0 should automatically install a default set of drivers

### ISSUE THREAD

**Issue by boneskull** [appium/appium#15795]
## The problem

Appium 1, as we know, is batteries-included: when you install `appium@1`, you get drivers.  It's all one package.  This is not  the case with Appium 2.  To get the drivers which were previously included, users must take extra steps (e.g., `appium driver install <driver>` perhaps _multiple_ times).  

While we _personally_ may not feel this pain, **I cannot emphasize enough how poor this experience is for users**.  A major complaint for the past many years in the JS ecosystem has been this: packages like Babel don't do much and you have to install a slew of plugins to make it do literally anything.  _When you install software, that software should do something._. Sensible defaults, in other words.

I get the rationale behind decoupling modules.  However, "the unix philosophy" (like anything in software development) is a tradeoff.  I assert (without any evidence, mind you) that this philosophy is precisely why the command-line is so daunting to new developers (I'm done shaking my fist at clouds now).

## Potential Solutions

So: Appium should do something about this.  There are several ways to go about it, with the ultimate goal of providing a _better out-of-box-experience_.  Ideas:

1. A metapackage.  Unfortunately, this will be confusing for users if any package name is chosen _except_ `appium`.  So then, the metapackage would be `appium`, and the `appium@2.x` in `packages/appium` would become e.g., `@appium/core` (I am going to hand-wave over implementation details for now). 
2. Abuse `postinstall` to check `APPIUM_HOME` for installed drivers, and install the default set if no drivers are found.
3. On the first run of the server, check for drivers. If none are installed, install the default set, then continue. Provide a command-line flag to disable this behavior. I'm unsure of the interaction with `--driver` here, but I think the behavior could safely be disabled in that case (since `--driver nonexistent-driver` should fail anyway).

I prefer either 1 or 3.

**Comment by mykola-mokhnach** [comment]
is it possible to pass parameter received from `npm install` to the package? if yes then one could already request drivers to install together with the package installation, for example `npm i appium --drivers=xcuitest,uiautomator2`

**Comment by mykola-mokhnach** [comment]
The second important point - we should provide a helpful error message if the given automationName is not found. Perhaps a link to the doc where driver installation process is explained

**Comment by jlipps** [comment]
Yes @mykola-mokhnach this feature already exists and I think is documented in the migration guide.

**Comment by youngfreeFJS** [comment]
> Yes @mykola-mokhnach this feature already exists and I think is documented in the migration guide.

hi @jlipps, can we see the migration guide now? :)

**Comment by youngfreeFJS** [comment]
> > Yes @mykola-mokhnach this feature already exists and I think is documented in the migration guide.
> 
> hi @jlipps, can we see the migration guide now? :)

have been found [it](https://github.com/appium/appium/blob/2.0/docs/en/advanced-concepts/migrating-to-appium-2.0.md)!

**Comment by StephanB75** [comment]
I'am not so deep in node and npm and i have the question if its possible to put the driver and plugin informatins also in the package.json, so that a npm install within the project folder directly install everything. 
Because i have different testing projects with different appium setup, i currently use the package.json within the project to manage this.

**Comment by jlipps** [comment]
@StephanB75 I don't think it's possible for Appium, when it's being installed, to know what is in the package.json of the project that is installing it as a dependency. However you could create a `postinstall` script in your project that installs drivers, for example:

```json
{
    ...,
    "scripts": {
        "postinstall": "npx appium driver install xcuitest && npx appium plugin install images"
    }
}
```

in this case, when you `npm install` in the package, it will run these commands automatically. note that you'd probably also want to set a distinct `APPIUM_HOME` env for each project unless you want them to share drivers.

**Comment by StephanB75** [comment]
> @StephanB75 I don't think it's possible for Appium, when it's being installed, to know what is in the package.json of the project that is installing it as a dependency. However you could create a `postinstall` script in your project that installs drivers, for example:
> 
> ```json
> {
>     ...,
>     "scripts": {
>         "postinstall": "npx appium driver install xcuitest && npx appium plugin install images"
>     }
> }
> ```
> 
> in this case, when you `npm install` in the package, it will run these commands automatically. note that you'd probably also want to set a distinct `APPIUM_HOME` env for each project unless you want them to share drivers.

Thanks @jlipps ! That was what i'm looking for. I will give that a try.

**Comment by boneskull** [comment]
Please see https://github.com/appium/appium/discussions/16149 for discussion about installation of drivers via npm.

That's something I'd like to address, but isn't the aim of this issue (however, it may be a prerequisite).

**Comment by jlipps** [comment]
@boneskull I'm thinking of closing this issue. I think with the install flags available it's already easy to install appium with any of the standard tools. We could also create a special install flag that's something like `npm install -g appium --batteries-included` which comes with all officially maintained drivers and plugins and document it if you like.

**Comment by mykola-mokhnach** [comment]
This has been addressed with presets
