### ISSUE TITLE
Error: Could not cache the response identified by 'xxxx',  because it has not been completed

### ISSUE THREAD

**Issue by youngfreeFJS** [appium/appium#15794]
## The problem
Error: Could not cache the response identified by 'xxxx',  because it has not been completed

## Environment

* Appium version (or git revision) that exhibits the issue: v1.20.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 10.15
* Node.js version (unless using Appium.app|exe): v14
* Npm or Yarn package manager: Npm
* Mobile platform/version under test: iPhone11 (iOS13.5)
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

https://gist.github.com/youngfreeFJS/b4b4c9b20103233e9f70fb0288fb8370

full log: https://gist.github.com/youngfreeFJS/edae8c3feeb8594539b0c944723f19ba

**Comment by mykola-mokhnach** [comment]
Please try the most recent server version

**Comment by youngfreeFJS** [comment]
thanks @mykola-mokhnach :)
I will try the most recent server version.

Is this a known issue in the old version?

I am not sure it is an Appium issue, because from the log I see that it crash :
> Failed to create WDA session (The application under test with bundle id 'com.meituan.imeituan' is not running, possibly crashed). Retrying...

Do you have any idea why the API has no status code in the log...
> 2021-08-31 16:37:40:386 [HTTP] <-- POST /wd/hub/session - - ms - -

**Comment by mykola-mokhnach** [comment]
> Is this a known issue in the old version?

Most likely it is

> I am not sure it is an Appium issue, because from the log I see that it crash :

The noReset is set to true, which assumes the app should be already running. Is it really running and has the provided bundle identifier?

> Do you have any idea why the API has no status code in the log...

The server usually prints something like that if the client unexpectedly terminates the connection to it without waiting for an actual response. This might be happening due to network issues or due to client timeouts

**Comment by youngfreeFJS** [comment]
not a bug,  found crash log at `~/Library/Logs/DiagnosticReports`
