### ISSUE TITLE
It's the issue of internal redmi firmware and there is nothing we can do about it on appium side.

### ISSUE THREAD

**Issue by IsaiaSilva** [appium/appium#15796]
On XIOME REDMI devices

Go to: Settings > USB Debugging > DISABLE option: Enable MIUI Optimization.
As a result, the installation popup of the image window shown above will not be displayed and the application will be launched.

**Comment by KazuCocoa** [comment]
Thanks.
To resolve https://github.com/appium/appium/issues/10761 ...?
