### ISSUE TITLE
Crash of app io.appium.uiautomator2.server running instrumentation

### ISSUE THREAD

**Issue by mthorta001** [appium/appium#15797]
## The problem

uiautomator2 server crash during app running.
from appium log can see: [Instrumentation] INSTRUMENTATION_RESULT: shortMsg=Process crashed.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Desktop OS/version used to run Appium: Ubuntu 18.04.5 LTS
* Node.js version (unless using Appium.app|exe): v12.22.2
* Npm or Yarn package manager: 6.14.13
* Mobile platform/version under test: Android 11 
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: appium ctl

## Details

App automation fail, to check the Appium&logcat log found that uiautomator2 crash

## Link to Appium logs

Appium log: https://gist.github.com/mthorta001/fd19c5e4d9f4e67d4b872de4fad5055e
Logcat log: https://gist.github.com/mthorta001/d1d4b51cac61ba166f17f80676a03b5b

## Code To Reproduce Issue [ Good To Have ]

not always heppen

**Comment by mykola-mokhnach** [comment]
It is not clear to me why the process crashes from the provided logcat output. Are you able to reproduce the crash with the recent appium@beta?

**Comment by mykola-mokhnach** [comment]
also, are you sure you manage your sessions properly and old sessions are always terminated properly before starting new ones? Have you tried to run the server with --session-override enabled?

**Comment by mthorta001** [comment]
> also, are you sure you manage your sessions properly and old sessions are always terminated properly before starting new ones? Have you tried to run the server with --session-override enabled?

i will try you advice, and update the info later. thx in advance!

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by mthorta001** [comment]
check the running logs these days. use appium 1.21.0 and enable --session-override, no uiautomator2.server found again.
