### ISSUE TITLE
[iOS] Using resetApp also resets snapshotMaxDepth Setting and updateSettings does not seem to solve it

### ISSUE THREAD

**Issue by nextlevelbeard** [appium/appium#15803]
There is a setting to allow users to see the entire tree on iOS: `snapshotMaxDepth`.
But it seems that if you use `resetApp`, the following element lookups will not respect the `snapshotMaxDepth`, leading to automation not finding the elements.

### To reproduce:

Session using capability `'appium:settings[snapshotMaxDepth]': 500`, increased from default `50`
- First test: Find an element that could only be found by increasing the `snapshotMaxDepth`, success ✅
- Automation uses `resetApp` command
- Second test, same session: Try to find the same element, it fails ❌

If you skip the `resetApp` command, the second test will find the element successfully.
Since `resetApp` is an essential command for setting the app state during automation, skipping it isn't a viable solution.

### Important to note that using `updateSettings` also does not seem to work:

Session using capability `'appium:settings[snapshotMaxDepth]': 500`, increased from default `50`
- First test: Find an element that could only be found by increasing the `snapshotMaxDepth`, success ✅
- Automation uses `resetApp` command
- Update Settings  `browser.updateSettings({ snapshotMaxDepth: 500 });`
- Second test, same session: Try to find the same element, it fails ❌

**Comment by mykola-mokhnach** [comment]
I don't recommend to use resetApp whatsoever. Internally it basically kills the session and starts a new one. And it is close to impossible to move the internal state of the previous session to the newly created one.

**Comment by nextlevelbeard** [comment]
I see, how would you suggest to reset the app state then, manually uninstall the app and what?

Anyway, shouldn't the `updateSettings` command that runs after `resetApp` be applied and in effect?
If you `updateSettings` and then `getSettings`, it returns the correct value (500).
But the tree is still not showing fully and is essentially the default 50.

**Comment by mykola-mokhnach** [comment]
XCUITest driver does provide APIs to uninstall/install apps. Unfortunately iOS does not provide any other ways to reset app data except of this one

**Comment by mykola-mokhnach** [comment]
> Anyway, shouldn't the updateSettings command that runs after resetApp be applied and in effect?
> If you updateSettings and then getSettings, it returns the correct value (500).
> But the tree is still not showing fully and is essentially the default 50.

I personally really don't want to touch this part of code because it is already messy and there's no guarantee something else won't be broken thereafter. But if somebody feels lucky today then feel free to give it a punch.

**Comment by jlipps** [comment]
yeah, `resetApp` would be better named `resetSession`. along with `launchApp` and `closeApp` I think they should all disappear personally, since they just call session start and delete behavior and that is confusing for users.

**Comment by mykola-mokhnach** [comment]
Closing because the is not going to be addressed due to endpoints deprecation.

**Comment by alexstroukov** [comment]
i'm also running into this issue. @nextlevelbeard what did you end up doing?
