### ISSUE TITLE
need to remove autoLanch=false, launchApp(), closeApp(), and resetApp()

### ISSUE THREAD

**Issue by jlipps** [appium/appium#15807]
This suite of functionality is outdated and confusing and dangerous. We should remove the routes and driver implementations for these. In their place, users should rely on standard Appium session management (new session + caps, delete session), and the now-reliable app management functions (terminateApp, installApp, activateApp, startActivity, etc...)

---

[update by Kazu]
### Alternative
- terminate_app and activate_app to restart the app process
    - Other methods: examples: `mobile: terminateApp`, `mobile: activateApp`, `mobile: launchApp`, `mobile: startActivity`
- uninstall/install the app to clean the local data In iOS (iOS does not have clear the local data api, so it requires uninstalling the app to do it)
    - For iOS simulators, `mobile: clearApp` could help -> https://appium.github.io/appium-xcuitest-driver/latest/execute-methods/#mobile-clearapp
- https://github.com/appium/appium-uiautomator2-driver#mobile-clearapp to clear the local data in UIA2
- Espresso driver hasn't supportted resetApp at the beginning

**Comment by KazuCocoa** [comment]
👍 
I forgot since, but non-app and bundleid/apppackage in caps behaves as same as autoLaunch=false.

So, appium has no issue for WPA case as well after removing autoLaunch=false. On iOS, it is just a shortcut of safari on a home screen. It has no bundleid, so to automate it, a user should start a session with homescreen and find the icon, and click it.

**Comment by KazuCocoa** [comment]
for autoLaunch:

Is it good to remove the caps from https://github.com/appium/appium/blob/2.0/packages/base-driver/lib/basedriver/desired-caps.js#L23-L25 and add this in the migration guide...?
after this, we can remove relevant code https://github.com/search?q=org%3Aappium+autoLaunch&type=code 

---

other commands:

Remove them from route.js or return errors first...?
Maybe returning an error message...?

**Comment by jlipps** [comment]
@KazuCocoa yes sounds like a good plan. as for the other commands, i think we should remove them from basedriver now, without any need for deprecation notice. that will be in the migration guide. then we can remove them from the drivers once the crossover to 2.0 is complete in 6 months or whenever. so if you're using 2.0 now with 2.0 basedriver, you won't have access, but with appium 1.x there will be access until the EOL period.

**Comment by nextlevelbeard** [comment]
I would argue against the removal of`resetApp`.
Strongly.

---

It seems to me that it is working perfectly fine and it is perfectly maintainable for Android.
I realize the same can't be said for iOS/XCUITest/WDA.

Correct me I'm wrong but the app state is clean, including things like local storage, sessions.
This type of cleaning does not occur when using just `installApp` / `removeApp` / `activateApp`, does it?
It's a crucial piece for the test life cycle.

Instead of removing `resetApp` couldn't we focus on improving / refactoring it?

---

Another thing: **Creating sessions takes time and `resetApp` is a huge time saver**

Using `resetApp` is currently a **hell of a lot faster** than creating new sessions.
**_Especially when using cloud vendors_**.

There's often a limit to concurrent sessions.
There's the very real problem of cloud users competing for public hardware.
Wait times for session creation can be long.

If a user wishes to clean the app state while reusing the same session, for whatever reason, making tests atomic or to speed up test runs, they will be left without any options.

Seems the devs are a bit disconnected from the reality of owning and maintaining an Appium test suite.

---

I don't see enough of an argument to remove this functionality, even if it's for a major version.
Not without addressing these issues and providing alternatives.

**Comment by mykola-mokhnach** [comment]
> This type of cleaning does not occur when using just installApp / removeApp / activateApp, does it?

It does. Actually on iOS uninstalling an app is the only way to cleanup its data

**Comment by mykola-mokhnach** [comment]
> Especially when using cloud vendors.

`resetApp` is just a workaround for the general session startup performance issue there. I assume cloud vendors could improve their logic for stopping/starting sessions. Basically, if we are talking about pure performance then resetApp call would anyway loose to uninstall/install APIs in scope of a single session

**Comment by kdthomas2121** [comment]
What is to be used as an alternative to resetApp() in situations where we want resets between tests within the same spec file?

**Comment by KazuCocoa** [comment]
It depends on your scenario.
If the reset means uninstall/install the app, then you can call uninstall/install APIs.
If you'd like to close/create a new session again as the old espresso driver does, then you can call `quite` and `create` again.

**Comment by kdthomas2121** [comment]
So my scenario is closing and creating a new session each time. Just to clarify this is driver.quit() and driver.create()? Thanks!

**Comment by kdthomas2121** [comment]
So yea currently we do do that interally, but the actual code which resets the app is the driver.reset(). What I'm asking is what should we migrate to when that's gone? Using WDIO, XCUI and UIAutomator2 currently

**Comment by ashokkumarg** [comment]
> Then, uninstall the app -> install the app -> launch the app should be enough.

is there way to maintain the state of application when performing the above operation. I tried with full reset = false and no reset = true but could not get

**Comment by KazuCocoa** [comment]
Do you mean via https://appium.io/docs/en/commands/device/app/app-state/ ?

**Comment by pedrorfernandes** [comment]
I understand the issue regarding session management and this does seem like a better approach, however, I have a use case for `autoLanch=false`

In my Android + iOS native app test suites, devs use the following setup:
- the `autoLaunch=false` capability is set
- `browser.installApp()` the app after the session starts
- test scenario sets up network mocks in a mockserver for the app initial boot
- The app is started (through `mobile: launchApp` + `mobile: startActivity`)

If `autoLaunch=false` is removed, then the app always immediately boots before the test is running, so the mocks can only be set later and then `browser.reset()` must be called to restart the app, wasting some time

Is this not a valid use case to keep  `autoLanch=false` and the test chooses when to start the app?

**Comment by KazuCocoa** [comment]
Do non-app and bundleid/appActivity instead of autoLaunch not help?
Then http://appium.io/docs/en/commands/device/app/install-app/ can install an app.

**Comment by pedrorfernandes** [comment]
@KazuCocoa yes they do work locally and in our grid, the only issue is with cloud vendors such as browserstack, they enforce an app in the capabilities that was previously uploaded and verified through their API. Basically, installing the app during a test is forbidden.

So without `autoLaunch: false`, the only way around this is to close the app after the session starts and open it again when the test begins

**Comment by jlipps** [comment]
Yeah I was going to say, better for cloud services to figure out how to support commands like installApp and starting sessions without apps (or using just built in apps).

**Comment by jlipps** [comment]
another option could be for cloud providers to implement their own handling of some `cloud:autoLaunch=false` scenario, though that would be more work for them.

**Comment by pedrorfernandes** [comment]
tbh the cloud vendors should perfectly be capable of handling the missing `app` capability, if browserstack has `browserstack.midSessionInstallApps`, then this is perfectly possible, they simply did not implement it, so i'll raise that ticket with them. 

Don't know about other vendors, but I guess that if `app` capability is not mandatory as an appium standard, they should respect that

**Comment by StephanB75** [comment]
@jlipps @KazuCocoa 
I have read now all the comments here but i'm still unsure how to handle the removal now.
I use closeApp() to close the app between tests within one session.
When i use terminateApp now the session is closed also or am i wrong ?
How should i close now the app without terminating the session ?

**Comment by nextlevelbeard** [comment]
If we are using simply the `bundleId` to run tests, without an `app` capability, how do we clean the app state between tests? Assume you don't have a local app file (.app or .ipa) that matches the exact revision of the installed version.

Before I would invoke `resetApp`, the app state would be cleaned for the next test.
Now, to invoke `removeApp`, is fine, but you can't re-install it...

How to handle this use case now?

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-uiautomator2-driver#mobile-clearapp is for UIA2. iOS cannot clean the local state without reinstalling it.

**Comment by MishkaTheCub** [comment]
Similar situation as @nextlevelbeard described. We are using bundleId to launch a session and resetApp() is used to basically kill and relaunch the app to retry a test if something went wrong. Right now it works on iOS using Appium 1.22.3 server and java-client 7.6.0. So how come this won't work anymore? This change will break a lot of existing tests. We will need a KB page somewhere on how to transition the tests to the new version that has a lot of things that work deprecated

**Comment by KazuCocoa** [comment]
Did terminateApp/activateApp work?

I thought java client was already showing deprecation marks for long, https://github.com/appium/java-client/blob/bd66144e8a15ec9bbe1af8a4c25087d527b79e90/src/main/java/io/appium/java_client/SupportsLegacyAppManagement.java#L44 (potentially it was since v8(?))

**Comment by MishkaTheCub** [comment]
@KazuCocoa I'm currently using java_client v7 and it's not showing deprecation marks. Once I switch to v8 these methods just don't exist and I can't figure out a workaround for them. I see they are in InteractsWithApps class but don't understand how to call them

**Comment by jlipps** [comment]
I'm not sure about the Java client, but both the iOS and Android drivers offer much better and more targeted ways of closing apps. Look in the docs for those drivers for mention of things like terminateApp, launchApp, startActivity, etc...

**Comment by hariabhay1353** [comment]
removeApp method is not showing in Appium 2.0.is there any replacement method for that.

**Comment by KazuCocoa** [comment]
`removeApp` should remain. What driver did you use? (if you have the appium log, can you share it as GIST?) @hariabhay1353

**Comment by amedvedjev** [comment]
what about reset app as part of test NOT driver start?

**Comment by odemolliens** [comment]
To fix the issue where the iOS app doesn't restart with appium 2.0 👀
```
import { Simctl } from 'node-simctl';
const simctl = new Simctl();

export function resetApp() {
  if (driver.isAndroid) {
    // Android (ALL)
    driver.reset();
  } else if (browserstackExec) {
    // iOS (Browserstack)
    driver.terminateApp('my.super.package');
    driver.removeApp('my.super.package');
    driver.installApp('bs://xxxxx'); // midSessionInstallApps
    driver.launchApp();
  } else {
    // iOS (Local)
    driver.closeApp();
    driver.removeApp('my.super.package');
    driver.installApp('MySuperApp.ipa');
    // Trick is to use simctl (part of appium packages) to force the relaunch of the app
    simctl.udid = (driver.capabilities as any).udid
    simctl.launchApp('my.super.package');
    driver.launchApp();
  }
}
```

**Comment by KazuCocoa** [comment]
>  With iOS it needs reinstall

For iOS, appium internally does the same thing to remove the local data since Apple does not provide the way. Btw, not sure the what the launchApp calls behind the method, it can be activateApp, or https://github.com/appium/appium-xcuitest-driver#mobile-launchapp (if you need to specify process arguments/env ver)

>     // Trick is to use simctl (part of appium packages) to force the relaunch of the app
>    simctl.udid = (driver.capabilities as any).udid
>    simctl.launchApp('my.super.package');

ah.. I read the simulator case. Actually it calls restarting simulator. I thought the simulator also did the same as a real device

**Comment by KazuCocoa** [comment]
Eventually yes. Some clients may show deprecation warning. https://github.com/appium/dotnet-client/issues/562 is for the dotnet client.

**Comment by Dor-bl** [comment]
Yes, I'm aware of that open issue. just I saw some questions whether to keep that one or not.

**Comment by slice-karven23** [comment]
im facing issue with ios while terminating or activating the app i'm encountering the following error 
`Error: Need to implement 'codeFor_activateApp()': undefined
    at t.getCodeString (file:///Applications/Appium%20Inspector.app/Contents/Resources/app.asar/dist/renderer.e31bb0bc.js:16:1230)
    at m (file:///Applications/Appium%20Inspector.app/Contents/Resources/app.asar/dist/renderer.e31bb0bc.js:144:596)
    at c (file:///Applications/Appium%20Inspector.app/Contents/Resources/app.asar/dist/renderer.e31bb0bc.js:144:666)
    at renderWithHooks (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:16305:18)
    at updateFunctionComponent (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:19588:20)
    at beginWork (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:21601:16)
    at beginWork$1 (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:27426:14)
    at performUnitOfWork (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:26560:12)
    at workLoopSync (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:26466:5)
    at renderRootSync (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:26434:7)
    at recoverFromConcurrentError (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:25850:20)
    at performSyncWorkOnRoot (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:26096:20)
    at flushSyncCallbacks (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:12042:22)
    at /Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:25651:13`

**Comment by slice-karven23** [comment]
also 
-app is not getting reset even if i use the noReset capability,
- browse.closeApp() is not closing the app

**Comment by Portium** [comment]
Hi, just a short note about my Appium expirence using real Android devices:
- Appium 1.x using driver.quit was cloing the app and the driver
- Appium 2.x  with java client 7.x using driver.quit is not closing the app anymore, so I added before driver.closeApp additonally
- Appium 2.x  with java client 8.x using driver.quit is not closing the app anymore, so I added http api call …appium/close/app additonally

Or is there another way to close the app at test end?

Regards

**Comment by mykola-mokhnach** [comment]
@Portium Try shouldTerminateApp capability if you are talking about UIA2 driver

**Comment by mykola-mokhnach** [comment]
For now the deprecation is done for all major driver but UIA2
Also the API has been removed from major clients

**Comment by MishkaTheCub** [comment]
There's still no clear instruction on how to replace the driver.resetApp() command when only bundleID is used (.i.e. the app does not get removed and reinstalled before each test; 'bundleId' capability is used instead of 'app'.
Seems like driver.terminateApp(<bundleId>) + driver.activateApp(<bundleId>) does the trick, is that right? We basically try to simulate killing and relaunching the app on iPhones

**Comment by KazuCocoa** [comment]
yes, terminate/activate is ok for the process restart generally. In case you wanted to clear the local data, you might need to uninstall the app once as iOS. I made some suggestions at the top of this issue https://github.com/appium/appium/issues/15807#issue-988087178 
Some client deprecation warnings also may have alternative commands.

**Comment by hassanabbaskazmi** [comment]
hey guys, was navigating through google searches for my problem and i stumbled across this thread. i'll keep it short;

i'm doing some test automation for a hybrid app (based on both Android & iOS) through appium 2.1 with python and python client, on macOS Ventura. a little piece of my struggles led me here which is, 'cleaning the cache/resetting the state' of the app on the iOS platform after each test script/case. initially what i've understood from reading this thread, there is no way of doing said task except removing the app and installing it again. but then again, we're on v2.1 of appium, there might've been a way that i've missed. need some guidance regarding this issue.

Also, i'm making a hybrid automation test suite. meaning, same test script, but will run on iOS or Android depending on whichever platform is detected at the start of the script.

**Comment by fleytman** [comment]
Look to this capabilities

```  
{
  "platformName": "iOS",
  "appium:platformVersion": "16.4",
  "appium:deviceName": "iPhone 13",
  "appium:automationName": "XCUITest",
  "appium:app": "/Users/username/IdeaProjects/myproj/my.app",
  "appium:enforceAppInstall": false,
  "appium:autoLaunch": false,
  "appium:permissions": "{\"en.myapp\": {\"userTracking\":\"YES\", \"location\":\"YES\", \"calendar\":\"YES\", \"camera\":\"YES\", \"contacts\":\"YES\"}}"
  }
```
In this case.
1. myapp will be installed if the current version of the program is not installed
2. myapp will get the necessary permissions
3. myapp will not launch

If I remove `"appium:autoLaunch": false` then the app will launch. How can I install the application, get the permissions but not use the `autoLaunch` function? How can I check that the current version of a program is not installed, but not launch that application?

**Comment by eglitise** [comment]
@fleytman for checking installation I would probably run `ideviceinstaller -l | grep en.myapp`. Not sure about permission retrieval, but perhaps `libimobiledevice` provides some way to extract that, too.

**Comment by fleytman** [comment]
> @fleytman for checking installation I would probably run ideviceinstaller -l | grep en.myapp. Not sure about permission retrieval, but perhaps libimobiledevice provides some way to extract that, too.

Да, способы самому реализовать существуют, хотя не совсем очевидные (аналога `mobile:shell` для ios нет). В моём случае я использую симулятор. Но чтобы управлять теми же пермишинами, в appium есть логика когда использовать simctl, а когда applesimutils. Но KazuCocoa верно подсказал, что я могу `mobile:setPermission` использовать. Увы, для этого нет удобной обёртки в java-client, поэтому если не залезть в доку xcuitest-driver'a не так очевидно, что есть способ.

P.S. Мне хочется чтобы при внесение изменений в код аппиума не терялся функционал, который есть. В данном случае выглядит так, что указанный мной кейс с enforceAppInstall не учли. Но сама ситуация с отказом от capabilities требует требовалось вносить много изменений в код текущих проектов, настолько что у возникают дискуссии а стоит ли вообще переходить на последние версии аппиума...

**Comment by frrzy** [comment]
Hampura
