### ISSUE TITLE
Appium 2.0 Beta 8 - chromedriver-executable argument is not supported

### ISSUE THREAD

**Issue by mstrelex** [appium/appium#15805]
## The problem

`error: unrecognized arguments: --chromedriver-executable`
Was it missed or omitted on purpose?

## Environment

* Appium version (or git revision) that exhibits the issue: **2.0.0 Beta 8**
* Last Appium version that did not exhibit the issue (if applicable): **1.22**
* Appium CLI or Appium.app|exe: **CLI**

Thanks.

**Comment by mykola-mokhnach** [comment]
This is expected. We have removed driver-specific command line arguments from the main CLI. These are going to be available later through --driver-args. The pr for it is currently being worked on

**Comment by jlipps** [comment]
I'll work on getting this finished and adding this detail to the migration doc.

**Comment by mykola-mokhnach** [comment]
@jlipps It's already two months since the last update on this issue. Can we close it?

**Comment by mstrelex** [comment]
@mykola-mokhnach It works fine when providing the path via a capability when initializing the session, thanks for your help.

**Comment by manojagarwal0712** [comment]
Is there any update on this? how we can pass arugument for driver --chromedriver-executable from CLI. ?

error: unrecognized arguments: --chromedriver-executable

**Comment by jlipps** [comment]
@manojagarwal0712 this is in the migration docs: https://appium.github.io/appium/docs/en/2.0/guides/migrating-1-to-2/#chromedriver-installation-flags

**Comment by francoisbiar** [comment]
Still not working, tested with appium 2.0 beta 66, with exactly the argument given in the migration doc.
```
francoisbiar@MacBook-Pro chromedriver_mac_arm64 % appium --driver-uiautomator2-chromedriver-executable ./chromedriver 

[ERROR] Unrecognized arguments: --driver-uiautomator2-chromedriver-executable ./chromedriver
```

**Comment by jlipps** [comment]
OK, I reviewed this and it looks like the information in the migration docs is not correct. If I recall we decided not to implement the driver-specific command line argument because the same effect is achievable using a default capability. So try this instead:

```
appium -dc '{"appium:chromedriverExecutable": "/path/to/chromedriver"}'
```

**Comment by jlipps** [comment]
updated the migration guide here: https://github.com/appium/appium/pull/18635
