### ISSUE TITLE
Setting Text on Android webview EditText places cursor position at start

### ISSUE THREAD

**Issue by adityaddy** [appium/appium#15819]
## The problem

Setting text of edit field in Webview places cursor at the start, In native Android EditText fields cursor is placed at the end

`let editFields = await driver.elementsByClassName('android.widget.EditText');
    if (editFields[0]) {
      await editFields[0].type("type-something");
 }`

Using Android UiAutomator 2 driver with `wd` javascript client

Expected Result - Cursor should be placed at the end of text
Actual Result - Cursor at the start of text (if it is webview edit field)
## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: macOS Big Sur(11.4)
* Node.js version (unless using Appium.app|exe): 16.8.0
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Android 12 emulator
* Appium CLI or Appium.app|exe: Appium CLI

**Comment by mykola-mokhnach** [comment]
I'm afraid we cannot do anything about it on Appium side. The text is being assigned by UiAutomator framework itself via `setText` API, so only Google is able to fix this behaviour. As a possible workaround you could try to emulate typing by using [W3C Actions](https://appiumpro.com/editions/46-sending-arbitrary-keystrokes-with-the-actions-api) or via [mobile: type](https://github.com/appium/appium-uiautomator2-driver#mobile-type)
