### ISSUE TITLE
[2.0] sh: lint-staged: command not found

### ISSUE THREAD

**Issue by Andrewngabriel** [appium/appium#15814]
## The problem

When I tried to make a commit on a branch opened from 2.0, I got the following error:

```bash
Pre-commit checks...
sh: lint-staged: command not found
pre-commit:
pre-commit: We've failed to pass the specified git pre-commit hooks as the `precommit-lint`
pre-commit: hook returned an exit code (1). If you're feeling adventurous you can
pre-commit: skip the git pre-commit hooks by adding the following flags to your commit:
pre-commit:
pre-commit:   git commit -n (or --no-verify)
pre-commit:
pre-commit: This is ill-advised since the commit is broken.
pre-commit:
```

I'm not sure if the lint-staged shell command was updated in the 2.0 branch because I didn't encounter this before when committing on branches opened from master.

## Environment

* Appium version (or git revision) that exhibits the issue: 2.0
* Last Appium version that did not exhibit the issue (if applicable): 1.21.0
* Desktop OS/version used to run Appium: Mac OS Big Sur 11.5.1 (20G80)
* Node.js version (unless using Appium.app|exe): 14.17.1
* Npm or Yarn package manager: 6.14.13
* Mobile platform/version under test: N/A
* Real device or emulator/simulator: N/A
* Appium CLI or Appium.app|exe: N/A

**Comment by mykola-mokhnach** [comment]
Did you install all dev dependencies using `npm install` after checking out the branch?

**Comment by Andrewngabriel** [comment]
Aha! I completely forgot doing that after switching branches, I thought my node_modules would transfer over but since the 2.0 branch has the @packages refactor, I completely forgot to.

All working great now 👍 Thanks for the quick reply!
