### ISSUE TITLE
iOS:  systematic error trying to switch context from native app to WEBVIEW on iOS 

### ISSUE THREAD

**Issue by minopica** [appium/appium#15824]
I am trying to switch context from native app to webview on iOS but I always get an error.

In pycharm (I am using python as programming language) I got the exception:
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: connect ECONNREFUSED ::1:27753
 
I am running Appium server 2.0 and iPhone 12 Pro Max simulator with iOS v14.5.
I got same issue also using real iOS device on browserStack
 
 
Can you help me to find where is the problem ?

Following an example of the code wrote in python:

 
from appium import webdriver
from appium.webdriver.common.mobileby import MobileBy
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

from os import path

CUR_DIR = path.dirname(path.abspath(__file__))
APP = path.join(CUR_DIR, 'TheApp.app.zip')
APPIUM = 'http://localhost:4723'

CAPS = {
    'platformName': 'iOS',
    'platformVersion': '14.5',
    'deviceName': 'iPhone 12 Pro Max',
    'automationName': 'XCUITest',
    'app': APP
}

driver = webdriver.Remote(
    command_executor=APPIUM,
    desired_capabilities=CAPS
)

class webview_active(object): # wait.until(webview_active())

    def __call__(self, driver):
        for context in driver.contexts:
            if context != 'NATIVE_APP':
                driver.switch_to.context(context)
                return True
        return False

try:
    wait = WebDriverWait(driver, 20)
    wait.until(EC.presence_of_element_located(
               (MobileBy.ACCESSIBILITY_ID, 'Webview Demo')
    )).click()
    wait.until(EC.presence_of_element_located(
        (MobileBy.XPATH, '//XCUIElementTypeTextField[@name="urlInput"]')
    )).send_keys('https://appiumpro.com')

    driver.find_element(MobileBy.ACCESSIBILITY_ID,'navigateBtn').click()
    wait.until(webview_active())

    print(driver.current_url)
    print(driver.title)

finally:
    driver.quit()

 
 
 
Logs from Appium server:
[debug] [W3C (68d56d56)] Calling AppiumDriver.getContexts() with args: ["68d56d56-a83b-4465-adbd-a890f5ea0157"]
[debug] [XCUITest] Executing command 'getContexts'
[debug] [XCUITest] Getting list of available contexts
[debug] [XCUITest] Retrieving contexts and views
[debug] [XCUITest] Selecting by url: false 
[RemoteDebugger] Remote Debugger version 8.13.2
[debug] [RemoteDebugger] useNewSafari --> false
[debug] [RemoteDebugger] Checking which communication style to use (non-Safari on platform version '14.5')
[debug] [RemoteDebugger] Platform version equal or higher than '12.2': true
[RemoteDebugger] Setting communication protocol: using Target-based communication
[debug] [RemoteDebugger] Connecting to remote debugger through TCP: ::1:27753
[debug] [W3C (68d56d56)] Encountered internal error running command: Error: connect ECONNREFUSED ::1:27753
[debug] [W3C (68d56d56)]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1133:16)
[HTTP] <-- GET /session/68d56d56-a83b-4465-adbd-a890f5ea0157/contexts 500 83 ms - 557
[HTTP] 
[HTTP] --> DELETE /session/68d56d56-a83b-4465-adbd-a890f5ea0157

**Comment by mykola-mokhnach** [comment]
Are you able to use Safari's remote debugger in the same situation?

**Comment by minopica** [comment]
Yes, I have no problem using safari remote debugger, I can inspect all the element in the webview.
I only get an error when I try to switch context during the running of test automation.

**Comment by mykola-mokhnach** [comment]
maybe it's a timing issue. Have you tried to wait for a while before switching the context?

**Comment by minopica** [comment]
Yes I set a timeout of 30 seconds

**Comment by amedvedjev** [comment]
how many web views you have? sometimes they are several and only one is actual. in your code you just switch to whatever not NATIVE.

**Comment by minopica** [comment]
Only 1 webview.

**Comment by Dan-Maor** [comment]
1. Can you please attach the Appium server log of the full session?
2. Does it happen when using an Appium 1.x server?
3. According to the available log snippet it seems that Appium server falls back to using the default remote debugger port rather than using a socketPath (which is the way remote debugger connects when I attempted to reproduce the issue with a simulator, guess it's not finding a socket path for some reason).
4. Like mykola mentioned, I sometimes encounter issues during first connection to remote debugger too, what I'm usually doing in this case is retrieving the contexts, waiting a few seconds for the pages to be retrieved in the remote debugger and then retrieve the contexts again.

**Comment by minopica** [comment]
Hi Dan Maor,

following the log extracted from Appium server (session run on browserStack).
When the app enters in the webview I printed In the log the list of context available for around 30 sec.
As you can see I got only "NATIVE_APP":

Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']
Elenco webview: 
['NATIVE_APP']



Full log extracted from appium server:
[AppiumLog.txt](https://github.com/appium/appium/files/7150289/AppiumLog.txt)

This is a small part :

2021-09-12 20:54:04:566 - [debug] [MJSONWP (4390b11f)] Calling AppiumDriver.getContexts() with args: ["4390b11f-5d13-414d-ab74-bd5738f08857"]
2021-09-12 20:54:04:567 - [debug] [XCUITest] Executing command 'getContexts'
2021-09-12 20:54:04:567 - [debug] [XCUITest] Getting list of available contexts
2021-09-12 20:54:04:567 - [debug] [XCUITest] Retrieving contexts and views
2021-09-12 20:54:04:567 - [debug] [XCUITest] Selecting by url: false 
2021-09-12 20:54:04:567 - [RemoteDebugger] Remote Debugger version 8.13.2
2021-09-12 20:54:04:568 - [debug] [RemoteDebugger] useNewSafari --> false
2021-09-12 20:54:04:570 - [debug] [RemoteDebugger] Checking which communication style to use (non-Safari on platform version '14.1')
2021-09-12 20:54:04:570 - [debug] [RemoteDebugger] Platform version equal or higher than '12.2': true
2021-09-12 20:54:04:570 - [RemoteDebugger] Setting communication protocol: using Target-based communication
2021-09-12 20:54:04:697 - [debug] [RemoteDebugger] Sending connection key request
2021-09-12 20:54:04:698 - [debug] [RemoteDebugger] Sending '_rpc_reportIdentifier:' message (id: 0): 'setConnectionKey'
2021-09-12 20:54:04:703 - [debug] [RemoteDebugger] Sending to Web Inspector took 3ms
2021-09-12 20:54:04:703 - [debug] [RemoteDebugger] Sending connection key request
2021-09-12 20:54:04:703 - [debug] [RemoteDebugger] Sending '_rpc_reportIdentifier:' message (id: 2): 'setConnectionKey'
2021-09-12 20:54:04:709 - [debug] [RemoteDebugger] Sending to Web Inspector took 5ms
2021-09-12 20:54:04:709 - [debug] [RemoteDebugger] Selecting application
2021-09-12 20:54:04:709 - [debug] [RemoteDebugger] No applications currently connected.
2021-09-12 20:54:04:710 - [debug] [XCUITest] No web frames found.
2021-09-12 20:54:04:713 - [debug] [MJSONWP (4390b11f)] Responding to client with driver.getContexts() result: ["NATIVE_APP"]

**Comment by jlipps** [comment]
Something else I've noticed is that sometimes iOS requires interaction with the web view before it's available for debugging. So you might need to tap somewhere inside it in code before collecting contexts.

**Comment by minopica** [comment]
You are right Jonathan: after tapping in the webview it works !!!

**Comment by jlipps** [comment]
Yes, somewhere along the line, I think they added it as a security feature. Some interaction is required. Glad to know that was the issue!
