### ISSUE TITLE
customSSLCert doesn't work since appium 1.19.0

### ISSUE THREAD

**Issue by rostik404** [appium/appium#15848]
## The problem
Hello!
I want to pass my custom SSL cert using cli option `customSSLCert`. Here is my full appium run command:
```
./build/lib/main.js --default-capabilities '{"isHeadless": true, "shouldUseSingletonTestManager": false, "waitForQuietness": false, "wdaStartupRetries": 3, "reduceMotion": true, "noReset": false, "waitForQuiescence": false, "fullReset": false, "platformName": "iOS", "platformVersion": "13.3", "automationName": "XCUITest", "deviceName": "iPhone 11 # 1 13.3", "wdaLocalPort": 8600, "showXcodeLog": true, "showIOSLog": true, "locationServicesEnabled": false, "customSSLCert": "-----BEGIN CERTIFICATE-----\nMIIFGTCCAwGgAwIBA....\n-----END CERTIFICATE-----"}' -p 4444
```

It works fine for all appium versions before 1.19.0 and I see my cert in devices settings:
<img src="https://user-images.githubusercontent.com/8089139/133273811-62d5398d-144a-436f-8a06-267df08737bb.png" height="340">
But since appium 1.19.0 there is no cert in my device:
<img src="https://user-images.githubusercontent.com/8089139/133273919-bdbe6ce8-1163-427a-9049-16df7ed7a36c.png" height="340">
I also tried to pass options in format `appium:customSSLCert`, but It still not working. Where am I wrong?
## Environment

* Appium version (or git revision) that exhibits the issue: 1.19.0
* Last Appium version that did not exhibit the issue (if applicable): 1.18.0
* Desktop OS/version used to run Appium: MacOs 10.15.4
* Node.js version (unless using Appium.app|exe): v12.18.1
* Npm or Yarn package manager: 6.14.5
* Mobile platform/version under test: 13
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: cli

## Link to Appium logs

appium 1.19.0 logs https://gist.github.com/rostik404/cce46eb8258af7d08de594e3c990e4ed

**Comment by rostik404** [comment]
I just found version where it stopped working.
customSSLCert doesn't work since 1.19.0 and it still not working on fresh master.
fresh master logs https://gist.github.com/rostik404/bc9db194e0997f451afa5785eba9e694

**Comment by mykola-mokhnach** [comment]
Try if https://github.com/appium/appium-xcuitest-driver#mobile-installcertificate works for you

**Comment by rostik404** [comment]
appium 1.18.0 logs about ssl cert looks the same, but the cert is adding in device correctly.
https://gist.github.com/rostik404/b2f615b6d54f61531dc456303ac55e6c

**Comment by rostik404** [comment]
@mykola-mokhnach what cert format should I use? I have a cert in `.crt` file in format
```
-----BEGIN CERTIFICATE-----
MIIFGTCCAwGgAwIBAgIQJMM7ZIy2SYxCBgK7WcFwnjANBgkqhkiG9w0BAQ0FADAf
...
LpuQKbSbIERsmR+QqQ==
-----END CERTIFICATE-----
```
So, I'm executing the code:
```
const cert = fs.readFileSync('/Users/rostik404/YandexInternalRootCA.crt');
const content = cert.toString('base64');
await this.browser.execute('mobile: installCertificate', { content });
```
and then getting an error:
```
[debug] [W3C (8cbc6834)] Calling AppiumDriver.execute() with args: ["mobile: installCertificate",[{"content":"LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZHVENDQXdHZ0F3SUJBZ0lRSk1NN1pJeTJTWXhDQmdLN1djRnduakFOQmdrcWhraUc5dzBCQVEwRkFEQWYKTVIwd0d3WURWUVFERXhSWllXNWtaWGhKYm5SbGNtNWhiRkp2YjNSRFFUQWVGdzB4TXpBeU1URXhNelF4TkROYQpGdzB6TXpBeU1URXhNelV4TkRKYU1COHhIVEFiQmdOVkJBTVRGRmxoYm1SbGc2gxWklXZHFrZloyUVhPWjJnSDRBRWVvTi85dkVmVVB3cV...
[debug] [XCUITest] Executing command 'execute'
[debug] [simctl] Error running 'keychain': An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to read certificate
Certificate is not a supported CER or PEM certificate file
[debug] [XCUITest] Error: Command '/usr/bin/xcrun simctl keychain EF00F6FC-FE95-4261-AECD-BAB5B9F15D2C add-root-cert /var/folders/r4/hzf6lyx15sn9xxwtjt9qm6p10k3xrt/T/f6da2bea-f3d2-46b8-b1f6-f630c6f55e9b.pem' exited with code 22
[debug] [XCUITest]     at ChildProcess.<anonymous> (/Users/rostik404/projects/appium/node_modules/teen_process/lib/exec.js:113:19)
[debug] [XCUITest]     at ChildProcess.emit (events.js:315:20)
[debug] [XCUITest]     at maybeClose (internal/child_process.js:1021:16)
[debug] [XCUITest]     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
[XCUITest] The certificate cannot be installed via CLI. Falling back to UI-based deployment
```

**Comment by mykola-mokhnach** [comment]
Basically Appium simply calls `simctl keychain <sum_uuid> add-root-cert <cert_path>` command there. And the certificate string you provide is written to a temporary file `<cert_path >`. Try to make your payload working with the command above so then it could also work in Appium.

**Comment by rostik404** [comment]
The problem was in `base64` encoding. It works this way:
```
const cert = fs.readFileSync('/Users/rostik404/YandexInternalRootCA.crt');
const content = cert.toString('base64');
await this.browser.execute('mobile: installCertificate', { content });
```
So, customSSLCert capability is not working anymore and `mobile: installCertificate` is only way to add custom cert?

**Comment by mykola-mokhnach** [comment]
> The problem was in base64 encoding. It works this way:

Actually this is a bug. I hope https://github.com/appium/appium-xcuitest-driver/pull/1334 will fix it

**Comment by rostik404** [comment]
Cool, thanks!
But what about customSSLCert capability? Is it deprecated?

**Comment by mykola-mokhnach** [comment]
No, it must also be a bug. I've included both fixes into the PR above.

**Comment by rostik404** [comment]
@mykola-mokhnach, adding custom cert will not be supported for Xcode <11.4?
https://github.com/appium/appium-xcuitest-driver/pull/1334/files#diff-ed3c013edbc896bd87ef62539626fcdc8930a31f3cee7ecb37438e172af2c8e0R446
How did it work for Xcode <11.4 in older appium versions?

**Comment by mykola-mokhnach** [comment]
On Xcode below 11.4 it just uses some hacks to write certs directly to the Simulator's SQLLite DB. Although it is not always reliable.

**Comment by mykola-mokhnach** [comment]
The patch has been merged to appium@beta
