### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError, Seeing this exception thrown when automating on iPad simulator but same works fine with Real device

### ISSUE THREAD

**Issue by AyushRai95** [appium/appium#15847]
## The problem
ExpressionChangedAfterItHasBeenCheckedError
Seeing the above exception this causes UI becoming unresponsive, hence causing test case failure.
Is there any work around or fix for this ?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS Big Sur 11.4
* Node.js version (unless using Appium.app|exe): v6.14.4
* Npm or Yarn package manager: Npm
* Mobile platform/version under test: ios 14.5
* Real device or emulator/simulator:Simulator
* Appium CLI or Appium.app|exe:

**Comment by mykola-mokhnach** [comment]
Sorry, we cannot help nothing without logs

**Comment by mykola-mokhnach** [comment]
Closed because of no response
