### ISSUE TITLE
Appium ionic app raise an error when trying to use move_by_offset method

### ISSUE THREAD

**Issue by bwomsm1** [appium/appium#15845]
## The problem

I am automating an ionic application, the action which I am trying to perform is drag and drop of a range knob: [ionic range knob](https://ionicframework.com/docs/api/range)
The action which I am trying to perform does working correctly on the android app but it does not on the iOS app, for no real reason. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable): No
* Desktop OS/version used to run Appium: Mac OS 11.5.2
* Node.js version (unless using Appium.app|exe): v12.9.1
* Npm or Yarn package manager: 7.20.5
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: cli

## Details
When trying to perform on a slider WebElement the following action: 
```
range_knob = node.find_element_by_class_name('range-knob')
action_chains = ActionChains(self.driver_)
action_chains.click_and_hold(range_knob).move_by_offset(xoffset, yoffset).release().perform()
```
An exception is being raised with the following message:
```
Message: The element identified by "5010" is either not present or it has expired from the internal cache. Try to find it again
```

## Link to Appium logs
https://github.com/bwomsm1/AppiumLogs/blob/master/range_knob.log

## Code To Reproduce Issue [ Good To Have ]
```
range_knob = node.find_element_by_class_name('range-knob')
action_chains = ActionChains(self.driver_)
action_chains.click_and_hold(range_knob).move_by_offset(xoffset, yoffset).release().perform()
```

![15_31_43_before_teardown](https://user-images.githubusercontent.com/5571230/132987927-ac586a3f-394d-408a-8cc7-7827d29185ce.png)

**Comment by bwomsm1** [comment]
@mykola-mokhnach can you please help with that issue? 

Thanks!

**Comment by mykola-mokhnach** [comment]
The error is expected. Touch actions only work with native elements or absolute coorinates

**Comment by bwomsm1** [comment]
But how it does working on the **Android** ionic app?

**Comment by mykola-mokhnach** [comment]
I don't think there's a way to guess it without having any logs

**Comment by bwomsm1** [comment]
I added the logs for the ios case where its not working: 

https://github.com/bwomsm1/AutomationFramework/blob/master/range_knob.log

**Comment by mykola-mokhnach** [comment]
Unfortunately I get 404 error after the above link is clicked

**Comment by jlipps** [comment]
I think the reason it works on Android is potentially that chrome driver actually supports the touch actions and we proxy to it, whereas on iOS we don't have a full web driver implementation from the vendor.

**Comment by bwomsm1** [comment]
Adding again the log:<br>
https://github.com/bwomsm1/AppiumLogs/blob/master/range_knob.log

**Comment by bwomsm1** [comment]
@jlipps 
I tried to drag my view with custom call:
```
TouchActions(self.driver_). \
                tap_and_hold(rect['x'] + rect['width']/2, rect['y'] + rect['height']/2). \
                move(rect['x'] + rect['width'] / 2 + xoffset, rect['y'] + rect['height'] / 2). \
                release(rect['x'] + rect['width'] / 2 + xoffset, rect['y'] + rect['height'] / 2). \
                perform()
```

But it keeps telling me:
```
Encountered internal error running command: NotYetImplementedError: Method has not yet been implemented
```

**Comment by mykola-mokhnach** [comment]
https://github.com/bwomsm1/AppiumLogs/blob/0c38e92116f291c6957676db708d6a9fa58232a8/range_knob.log#L632

My assumption was correct, the client code tries to pass a reference to a web element into touch actions and that fails. Everything works there as expected from the server perspective

**Comment by bwomsm1** [comment]
thanks @mykola-mokhnach , can you might advice how I can scroll that "range-knob"? I tried everything I could think of.

**Comment by KazuCocoa** [comment]
You could call ActionChains api with x/y coordinate (instead of an element) after switching the context with "NATIVE_APP"

**Comment by mykola-mokhnach** [comment]
Please use Appium forum to ask questions
Closed as not an issue

**Comment by bwomsm1** [comment]
Sorry @KazuCocoa but as far as I understand ActionChains allows you to swipe only by providing the actual element we want to swipe:
calling to `def click_and_hold(self, **on_element**=None)`
calling to `def move_by_offset(self, xoffset, yoffset)` 
calling to `def release(self, on_element=None)`
calling to `def perform(self)`


Thanks!

**Comment by bwomsm1** [comment]
@KazuCocoa when trying to perform the scroll with TouchAction i have an issue that the "range-knob" element which I am trying to scroll has a different x,y coords in case of Webview Context and Native Context.

**Comment by bwomsm1** [comment]
@KazuCocoa I managed to perform my swipe in the native context, but I have some other problem :-(
my issue is that the WebElement rect has a different size measurements in real time,
When I capture the element with the appium desktop app I get the following measurements:
<img width="209" alt="Screen Shot 2021-09-14 at 11 59 55" src="https://user-images.githubusercontent.com/5571230/133229537-67480a35-4769-46a5-8d76-7ff9e79187e3.png">

as you can see the y value is 559

When I capture the element in real time:
<img width="660" alt="Screen Shot 2021-09-14 at 12 01 36" src="https://user-images.githubusercontent.com/5571230/133229647-ee5d71ce-7cb7-4fb3-b5a0-e872e39827f6.png">
the y value is 515

Why is that?

**Comment by KazuCocoa** [comment]
The result of rect in WebView context depends on how WebInspector (iOS side) handles it. Appium basically proxy the request to iOS(WebInspector). So I guess WebInspector returned difference rect depending on its timing.

**Comment by jlipps** [comment]
If you want to perform native touch actions on web elements, you will also need to map the web coordinate space to the native coordinate space, as they are not the same. You can do this by getting the rect of the WebView element and using it to relative the web coordinates reported inside the webview.
