### ISSUE TITLE
If the cache packet is taken after 3:35AM, the cache packet will be reset and the file will be missing

### ISSUE THREAD

**Issue by candialala** [appium/appium#15853]
## The problem

If the cached packet is taken after 3:35AM, the cached packet will be reset and the file will be corrupted.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.0-rc.6
* Mobile platform/version under test: iOS 15 Simulator
* OS Version: 11.5
* Xcode Version: 13.0 beta 4

## Details
![image](https://user-images.githubusercontent.com/22468260/133544156-c6fc2c90-ccb2-4a10-8d20-e01c11b47178.png)
The cache is fine until 3:35AM, but when the case is executed after 3:35AM, I find that when you reuse the cached file, the file is corrupted and cannot be started properly. Only 20MB left. The normal size is about 502MB.
If I manually change the MAC time, it will reappear for the first time and not for the second time. Restarting the computer also reappears for the first time.

https://gist.github.com/candialala/a1cf2bfe932c857845940385509d4834

**Comment by mykola-mokhnach** [comment]
Sorry, I don't quite understand what the issue is and how it is related to Appium. Applications cache entry is valid for 12h after being created once. Also, you could unzip the .app and provide it to Appium directly, so it does not need to cache it at all.

**Comment by candialala** [comment]
> Sorry, I don't quite understand what the issue is and how it is related to Appium. Applications cache entry is valid for 12h after being created once. Also, you could unzip the .app and provide it to Appium directly, so it does not need to cache it at all.

I would like to know whether Appium handles cached files, because this problem is very strange, I am not sure whether appium has any operation or the OS system or Xcode problem.

**Comment by mykola-mokhnach** [comment]
You may check the cache implementation at https://github.com/appium/appium-base-driver/blob/a908e8127829f19ee27347e926ab30abe282f6ed/lib/basedriver/helpers.js#L124

**Comment by mykola-mokhnach** [comment]
I don't think there is much more we could do on this issue. Please let us know if more details are available.
