### ISSUE TITLE
Access from remote address to the mjpeg server (UiAutomator2)

### ISSUE THREAD

**Issue by pespinel** [appium/appium#15854]
## The problem

When a mjpeg server is started during an iOS test (XCUITest), the endpoint is reachable from all the networks. In Android (UiAutomator2), the endpoint is only accesible from the local host. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2
* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium: macOS
* Node.js version (unless using Appium.app|exe): 15.10.0
* Npm or Yarn package manager: npm 7.17.0
* Mobile platform/version under test: iOS 14.6 / Android 7.0
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Cli

## Details

Now that the remote work is on the rise, I think that an option to access remotely to the streaming of Android devices (Like in iOS) will be great.

## Link to Appium logs

Not needed, the mjpeg server only listen in 127.0.0.1 with UiAutomator2, but it listen in 0.0.0.0 for XCUITest

**Comment by mykola-mokhnach** [comment]
This is expected. Basically the fact that iOS broadcasts to all interfaces is also not good and is a potential security threat. One could always forward/tunnel the localhost stream if necessary.

**Comment by pespinel** [comment]
I know, but it will be good to have a parameter to choose in which the stream is exposed (localhost, custom host, or all host 0.0.0.0)

**Comment by mykola-mokhnach** [comment]
This basically depends on `adb` as it does port forwarding to localhost be default. There are at least several possible ways to workaround it:
- apply https://stackoverflow.com/questions/56130335/adb-port-forwarding-to-listen-on-all-interfaces
- connect directly to the device's IP
- start a custom port forwarding tool

**Comment by pespinel** [comment]
It should work if I set the capability remoteAdbHost to 0.0.0.0? The port forwarding is the last option I want to try. Thanks

**Comment by KazuCocoa** [comment]
Might `appium:mjpegScreenshotUrl` also help?
https://github.com/appium/appium-uiautomator2-driver#mjpeg
