### ISSUE TITLE
Getting errors while installing appium

### ISSUE THREAD

**Issue by ankur-bm-ai** [appium/appium#15866]
## The problem

Not able to install appium on mac. Please help!!
"npm install -g appium"
## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

# npm audit report

axios  <0.21.1
Severity: high
Server-Side Request Forgery - https://npmjs.com/advisories/1594
fix available via `npm audit fix`
node_modules/appium/node_modules/appium-flutter-driver/node_modules/axios
  appium-base-driver  5.8.1 - 7.3.2 || 8.0.0-beta.0
  Depends on vulnerable versions of axios
  node_modules/appium/node_modules/appium-flutter-driver/node_modules/appium-base-driver

jszip  <3.7.0
Severity: moderate
Prototype Pollution - https://npmjs.com/advisories/1774
fix available via `npm audit fix`
node_modules/appium/node_modules/jszip

minimist  <0.2.1 || >=1.0.0 <1.2.3
Prototype Pollution - https://npmjs.com/advisories/1179
fix available via `npm audit fix --force`
Will install appium@1.4.16, which is a breaking change
node_modules/appium/node_modules/appium-tizen-driver/node_modules/minimist
  mkdirp  0.4.1 - 0.5.1
  Depends on vulnerable versions of minimist
  node_modules/appium/node_modules/appium-tizen-driver/node_modules/mkdirp
    @jimp/core  <=0.9.6-canary.858.667.0
    Depends on vulnerable versions of mkdirp
    node_modules/appium/node_modules/appium-tizen-driver/node_modules/@jimp/core
      @jimp/custom  <=0.8.6-canary.818.495.0 || 0.9.2-canary.815.538.0 - 0.9.3-canary.825.599.0 || 0.9.4-canary.832.606.0 - 0.9.4-canary.845.627.0 || 0.9.6-canary.857.681.0 - 0.9.6-canary.858.667.0
      Depends on vulnerable versions of @jimp/core
      node_modules/appium/node_modules/appium-tizen-driver/node_modules/@jimp/custom
        jimp  0.3.6-alpha.5 - 0.8.6-canary.818.495.0 || 0.9.2-canary.815.538.0 - 0.9.3-canary.825.599.0 || 0.9.4-canary.832.606.0 - 0.9.4-canary.845.627.0 || 0.9.6-canary.857.681.0 - 0.9.6-canary.860.700.0
        Depends on vulnerable versions of @jimp/custom
        node_modules/appium/node_modules/appium-tizen-driver/node_modules/jimp
          appium-tizen-driver  *
          Depends on vulnerable versions of jimp
          Depends on vulnerable versions of yargs
          node_modules/appium/node_modules/appium-tizen-driver
            appium  <=0.0.0-rc.0 || 0.3.0-rc.0 || 1.5.0-beta1 - 1.22.0-rc.7
            Depends on vulnerable versions of appium-android-driver
            Depends on vulnerable versions of appium-flutter-driver
            Depends on vulnerable versions of appium-ios-driver
            Depends on vulnerable versions of appium-tizen-driver
            Depends on vulnerable versions of appium-xcuitest-driver
            Depends on vulnerable versions of appium-youiengine-driver
            node_modules/appium

normalize-url  4.3.0 - 4.5.0 || 5.0.0 - 5.3.0 || 6.0.0
Severity: high
Regular Expression Denial of Service - https://npmjs.com/advisories/1755
fix available via `npm audit fix`
node_modules/appium/node_modules/normalize-url

path-parse  <1.0.7
Severity: moderate
Regular Expression Denial of Service in path-parse - https://npmjs.com/advisories/1773
fix available via `npm audit fix`
node_modules/appium/node_modules/path-parse

ws  5.0.0 - 5.2.2 || 6.0.0 - 6.2.1 || 7.0.0 - 7.4.5
Severity: moderate
Regular Expression Denial of Service - https://npmjs.com/advisories/1748
fix available via `npm audit fix`
node_modules/appium/node_modules/rpc-websockets/node_modules/ws
node_modules/appium/node_modules/ws

xmldom  *
Severity: moderate
Misinterpretation of malicious XML input - https://npmjs.com/advisories/1650
Misinterpretation of malicious XML input - https://npmjs.com/advisories/1769
fix available via `npm audit fix --force`
Will install appium@1.4.16, which is a breaking change
node_modules/appium/node_modules/appium-fake-driver/node_modules/xmldom
node_modules/appium/node_modules/xmldom
  appium-chromedriver  >=4.13.0
  Depends on vulnerable versions of xmldom
  node_modules/appium/node_modules/appium-chromedriver
    appium-android-driver  >=4.17.0
    Depends on vulnerable versions of appium-chromedriver
    node_modules/appium/node_modules/appium-android-driver
      appium  <=0.0.0-rc.0 || 0.3.0-rc.0 || 1.5.0-beta1 - 1.22.0-rc.7
      Depends on vulnerable versions of appium-android-driver
      Depends on vulnerable versions of appium-flutter-driver
      Depends on vulnerable versions of appium-ios-driver
      Depends on vulnerable versions of appium-tizen-driver
      Depends on vulnerable versions of appium-xcuitest-driver
      Depends on vulnerable versions of appium-youiengine-driver
      node_modules/appium
      appium-espresso-driver  >=1.19.0
      Depends on vulnerable versions of appium-android-driver
      node_modules/appium/node_modules/appium-espresso-driver
      appium-uiautomator2-driver  >=1.37.0
      Depends on vulnerable versions of appium-android-driver
      Depends on vulnerable versions of appium-chromedriver
      node_modules/appium/node_modules/appium-uiautomator2-driver
        appium-youiengine-driver  >=1.2.1
        Depends on vulnerable versions of appium-uiautomator2-driver
        Depends on vulnerable versions of appium-xcuitest-driver
        node_modules/appium/node_modules/appium-youiengine-driver
  appium-fake-driver  <=1.0.1 || 2.0.0 - 2.1.0
  Depends on vulnerable versions of xmldom
  node_modules/appium/node_modules/appium-fake-driver
  appium-ios-driver  >=0.0.6
  Depends on vulnerable versions of xmldom
  node_modules/appium/node_modules/appium-ios-driver
    appium-xcuitest-driver  >=2.0.0
    Depends on vulnerable versions of appium-ios-driver
    Depends on vulnerable versions of xmldom
    node_modules/appium/node_modules/appium-xcuitest-driver
      appium-flutter-driver  *
      Depends on vulnerable versions of appium-xcuitest-driver
      node_modules/appium/node_modules/appium-flutter-driver
  appium-ios-simulator  >=3.27.0
  Depends on vulnerable versions of xmldom
  node_modules/appium/node_modules/appium-ios-simulator
  plist  0.3.2 - 3.0.3
  Depends on vulnerable versions of xmldom
  node_modules/appium/node_modules/plist

yargs-parser  <=13.1.1 || 14.0.0 - 15.0.0 || 16.0.0 - 18.1.1
Prototype Pollution - https://npmjs.com/advisories/1500
fix available via `npm audit fix --force`
Will install appium@1.4.16, which is a breaking change
node_modules/appium/node_modules/appium-tizen-driver/node_modules/yargs-parser
  yargs  4.0.0-alpha1 - 12.0.5 || 14.1.0 || 15.0.0 - 15.2.0
  Depends on vulnerable versions of yargs-parser
  node_modules/appium/node_modules/appium-tizen-driver/node_modules/yargs
    appium-tizen-driver  *
    Depends on vulnerable versions of jimp
    Depends on vulnerable versions of yargs
    node_modules/appium/node_modules/appium-tizen-driver
      appium  <=0.0.0-rc.0 || 0.3.0-rc.0 || 1.5.0-beta1 - 1.22.0-rc.7
      Depends on vulnerable versions of appium-android-driver
      Depends on vulnerable versions of appium-flutter-driver
      Depends on vulnerable versions of appium-ios-driver
      Depends on vulnerable versions of appium-tizen-driver
      Depends on vulnerable versions of appium-xcuitest-driver
      Depends on vulnerable versions of appium-youiengine-driver
      node_modules/appium

27 vulnerabilities (9 low, 15 moderate, 3 high)

**Comment by mykola-mokhnach** [comment]
I don't see any issues there. All these audit errors are expected, since we lock dependencies in Appium releases. You could try to install `appium@beta` to get the most recent dependencies though.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
