### ISSUE TITLE
Xcode 13  Can't dismiss keyboard 

### ISSUE THREAD

**Issue by mochitest** [appium/appium#15861]
## The problem

org.openqa.selenium.InvalidElementStateException: Error Domain=com.facebook.WebDriverAgent Code=1 "Did not know how to dismiss the keyboard. Try to dismiss it in the way supported by your application under test." UserInfo={NSLocalizedDescription=Did not know how to dismiss the keyboard. Try to dismiss it in the way supported by your application under test.}

## Environment

* Appium v1.22.0-beta.0

## Details
driver.hideKeyboard();

**Comment by mykola-mokhnach** [comment]
Duplicate of https://github.com/appium/appium/issues/15073
