### ISSUE TITLE
In the IOS UI automated test, after entering the page, the page was stuck and did not move. Appium had no obvious save or error message, but it was waiting.

### ISSUE THREAD

**Issue by sunxiaoyu124** [appium/appium#15863]
## The problem
In the IOS UI automated test, after entering the page, the page was stuck and did not move. Appium had no obvious save or error message, but it was waiting.

## Environment

* Appium version (or git revision) that exhibits the issue:1.21.0
* Last Appium version that did not exhibit the issue (if applicable):yes
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):14.4.0
* Npm or Yarn package manager:
* Mobile platform/version under test:iPad Pro (12.9-inch) (5th generation)
* Real device or emulator/simulator:simulator
* Appium CLI or Appium.app|exe:

**Comment by mykola-mokhnach** [comment]
Please provide the full server log

**Comment by mykola-mokhnach** [comment]
Closed because of no response
