### ISSUE TITLE
Webdriver agent fails to launch our new swift iOS app

### ISSUE THREAD

**Issue by jagadish970** [appium/appium#15876]
##  Failed to create WDA session (The application under test with bundle id 'com.test.test' is not running, possibly crashed). Retrying...

Our app is recently changed from  objective C to swift, using latest app i am not able to run tests using appium. It says the above error.

It says app is crashed but app launches when i do click manually

##Appium version 1.21.0

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: IOS with xcode 12.5.1
* Real device or emulator/simulator: Simulator with version OS 14.5
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

[debug] [XCUITest] Sending createSession command to WDA
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.gigsky.gigsky","arguments":["-AppleLocale","en_US"],"environment":{"isEnterpriseMode":"NO","notificationPointId":"4","location":"IN","backendUrl":"http://192.168.1.5:8080","eSimSupported":"1","addPlanWithResult":"2","notificationPointStatus":"Executed-Success","subscriptionActiveWaitInterval":"1","addPlanWithCallBackWaitInterval":"1"},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true,"shouldTerminateApp":true}],"alwaysMatch":{}}}
[WD Proxy] Got response with status 400: {"value":{"error":"invalid element state","message":"The application under test with bundle id 'com.gigsky.gigsky' is not running, possibly crashed","traceback":"(\n\t0   CoreFoundation                      0x00007fff20422fba __exceptionPreprocess + 242\n\t1   libobjc.A.dylib                     0x00007fff20193ff5 objc_exception_throw + 48\n\t2   CoreFoundation                      0x00007fff20422c5b -[NSException init] + 0\n\t3   WebDriverAgentLib                   0x000000010ee5ca5b -[FBSession activeApplication] + 667\n\t4   WebDriverAgentLib                   0x000000010ee8c7ca +[FBSessionCommands currentCapabilities] + 90\n\t5   WebDriverAgentLib                   0x000000010ee8c699 +[FBSessionCommands sessionInformation] + 233\n\t6   WebDriverAgentLib                   0x000000010ee88f7f +[FBSessionCommands handleCreateSession:] + 3551\n\t7   WebDriverAgentLib                   0x000000010ee1b566 -[FBRoute_TargetAction mountRequest:intoResponse:] + 182\n\t8   WebDriverAgentLib                   0x000...
[debug] [W3C] Matched W3C error code 'invalid element state' to InvalidElementStateError
[debug] [XCUITest] Failed to create WDA session (The application under test with bundle id 'com.gigsky.gigsky' is not running, possibly crashed). Retrying...

**Comment by KazuCocoa** [comment]
Please attach the full log with `appium:showIOSLog` as GIST.
Our end to launch an app is via XCTest API by Apple, so I guess your got something in the launching process internally.

**Comment by jagadish970** [comment]
[appium.log](https://github.com/appium/appium/files/7209267/appium.log)

Provided logs by enabling appium:showIOSLog

**Comment by jagadish970** [comment]
@KazuCocoa Please check the attached logs

**Comment by mykola-mokhnach** [comment]
> 2021-09-22 08:57:07:034 [IOSSimulatorLog] [IOS_SYSLOG_ROW] 2021-09-22 14:27:06.965 A  GigskyApp[54687:153bd1] (CoreFoundation) Loading Preferences From System CFPrefsD
> 2021-09-22 08:57:07:035 [IOSSimulatorLog] [IOS_SYSLOG_ROW] 2021-09-22 14:27:06.980 Df GigskyApp[54687:153bd1] (libswiftCore.dylib) GigskyApp/GSStartupViewController.swift:129: Fatal error: Unexpectedly found nil while unwrapping an Optional value

It looks like your app is crashing. Please check the crash reason with your developers. Unfortunately there is nothing we could do there from Appium side.
