### ISSUE TITLE
Appium 2.0 + findImageOccurrence()

### ISSUE THREAD

**Issue by Auto81** [appium/appium#15873]
## The problem

Upgraded to Appium 2.0, now automation code (Java) errors out when attempting to 'driver.findImageOccurrence()'.

`org.openqa.selenium.UnsupportedCommandException: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource`

## Environment

* Appium version : 2.0 CLI
* - xcuitest@3.53.1 [installed (NPM)]
* Last Appium version that did not exhibit the issue (if applicable): 1.21 CLI
* Desktop OS/version used to run Appium: MAC
* Node.js version (unless using Appium.app|exe): 14.15.4
* Npm or Yarn package manager: 6.14.10
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: iPhone 13 iOS 15 Simulator
* XCode 13 RC
* Appium Doctor report : opencv4nodejs is installed at: /usr/local/lib. Installed version is: 5.6.0
* io.appium : java-client version : 7.5.1, also tried latest master (...112405b6)

## Details

As above

## Link to Appium logs

`[debug] [HTTP] No route found for /wd/hub/session/3a272448-d2d0-4be1-94ac-c291b2196438/appium/compare_images
[HTTP] <-- POST /wd/hub/session/3a272448-d2d0-4be1-94ac-c291b2196438/appium/compare_images 404 12 ms - 262`

## Thoughts

Is there a new method call to replace '.findImageOccurrence()'?

**Comment by mykola-mokhnach** [comment]
This is expected. In order to support image comparison one must install the corresponding plugin: https://github.com/appium/appium-plugins/tree/master/packages/images

**Comment by Auto81** [comment]
Thanks for response, 

Appium-doctor reporting it is installed 

```
[Appium] Plugins which can handle cmd 'compareImages': images (sessionless)
[Appium] Plugin images (sessionless) is now handling cmd 'compareImages'
[debug] [Support] Initializing opencv
[debug] [Support] Loading local package 'opencv4nodejs'
[debug] [Support] Failed to load local package 'opencv4nodejs': Cannot find module 'opencv4nodejs'
[debug] [Support] Require stack:
[debug] [Support] - /Users/automation/.appium/@appium/images-plugin/node_modules/@appium/support/build/lib/node.js
[debug] [Support] - /Users/automation/.appium/@appium/images-plugin/node_modules/@appium/support/build/lib/image-util.js
[debug] [Support] - /Users/automation/.appium/@appium/images-plugin/node_modules/@appium/support/build/index.js
[debug] [Support] - /Users/automation/.appium/@appium/images-plugin/node_modules/@appium/base-driver/build/lib/protocol/protocol.js
[debug] [Support] - /Users/automation/.appium/@appium/images-plugin/node_modules/@appium/base-driver/build/lib/protocol/index.js
[debug] [Support] - /Users/automation/.appium/@appium/images-plugin/node_modules/@appium/base-driver/build/lib/basedriver/driver.js
[debug] [Support] - /Users/automation/.appium/@appium/images-plugin/node_modules/@appium/base-driver/build/index.js
[debug] [Support] - /Users/automation/.appium/@appium/images-plugin/node_modules/@appium/images-plugin/build/lib/plugin.js
[debug] [Support] - /Users/automation/.appium/@appium/images-plugin/node_modules/@appium/images-plugin/build/index.js
[debug] [Support] - /usr/local/lib/node_modules/appium/build/lib/extension-config.js
[debug] [Support] - /usr/local/lib/node_modules/appium/build/lib/cli/parser-helpers.js
[debug] [Support] - /usr/local/lib/node_modules/appium/build/lib/cli/args.js
[debug] [Support] - /usr/local/lib/node_modules/appium/build/lib/cli/parser.js
[debug] [Support] - /usr/local/lib/node_modules/appium/build/lib/main.js
[debug] [Support] Failed to load global package 'opencv4nodejs': The "path" argument must be of type string. Received undefined
[debug] [Support] Linking package 'opencv4nodejs'
[debug] [Support] Retrying load of linked package 'opencv4nodejs'
[Support] Unable to load package 'opencv4nodejs': Cannot find module 'opencv4nodejs'
```

**Comment by mykola-mokhnach** [comment]
This is the issue of opencv4nodejs. Nothing we could do there from Appium side. Try to search/ask at Appium forum
