### ISSUE TITLE
Error accessing Appium Desktop inspector with iOS: Unable to start WebDriverAgent session because of xcodebuild failure

### ISSUE THREAD

**Issue by sam-022** [appium/appium#15885]
#### Seeing this error when trying to connect Appium Desktop with the iOS simulator - 
Error: Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: connect ECONNREFUSED 127.0.0.1:8100

## Environment

* Appium version (or git revision) that exhibits the issue: v1.22.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: macOS Big Sur - v11.4
* Node.js version (unless using Appium.app|exe): v14.17.5 (using Appium Desktop)
* Npm or Yarn package manager: v7.20.6
* Mobile platform/version under test: iOS 13 - v15.0
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium Desktop app

## Details
Tried the following options so far:
- reinstalling appium (cli and app), xcode, carthage
- building Webdriver Agent in Xcode
- using different mobile platform 

## Link to Appium logs
[appium-server-logs.txt](https://github.com/appium/appium/files/7219662/appium-server-logs.txt)

## Link to Appium Doctor logs
[appium-doctor-report.txt](https://github.com/appium/appium/files/7219692/appium-doctor-report.txt)

**Comment by mykola-mokhnach** [comment]
> Welcome to Appium v1.21.0

Appium 1.21 does not support iOS 15, so the error is expected. Please make sure you use a compatible server version.
Closed as not an issue

**Comment by sam-022** [comment]
Ah yes, that make sense. It works now with v14. Thank you!
