### ISSUE TITLE
Automating hybrid apps on Mac and Windows

### ISSUE THREAD

**Issue by lucky06688** [appium/appium#15888]
## The problem

Hi everyone, does Appium support automating hybrid apps on Windows and Mac? I noticed that `getContextHandles` and `context` are not available on Mac and Windows(https://appium.io/docs/en/writing-running-appium/web/hybrid/). Does this mean that Appium cannot be used for hybrid apps on the desktop? Are there other ways to workaround?

**Comment by mykola-mokhnach** [comment]
Unfortunately Appium does not support context switch for neither Windows nor macOS apps. Please use Appium forum to ask questions.
