### ISSUE TITLE
iOS 15 | Automation Running Overlay

### ISSUE THREAD

**Issue by aryahya** [appium/appium#15898]
## The problem

WebDriverAgent locks the screen of the iPhone asking for Passcode then after entering the Passcode a transparent overlay is displayed with the text `Automation Running  Hold both volume buttons to stop` this happens when I try to launch my application from the Appium Inspector followed by throwing `xcodebuild exited with code '65' and signal 'null'` then removing the WebDriverAgent. Before that in v1.21.0 and iOS 15 the WebDriverAgent displayed the "Automation Running" overlay and the application started fine from the integrated inspector but got frozen on getting the pagesource of the targeted app.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.22.0
* Last Appium version that did not exhibit the issue (if applicable): v1.21.0
* Desktop OS/version used to run Appium: macOS Big Sur v11.6
* Mobile platform/version under test: iOS 15
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium Server GUI

**Comment by KazuCocoa** [comment]
Just a note for visitors.
This is by design in iOS 15 for general XCTest(UI) process on real devices. Nothing can do in Appium side.
No passcode device can avoid the passcode.

**Comment by aryahya** [comment]
I managed to solve the frozen inspector issue I was facing by doing the following:

1. Upgraded Appium Desktop to Appium Server GUI v1.22.0 and install Appium Inspector because it is not bundled with Appium GUI anymore
2. Used the WebDriverAgent bundled with the new Appium Server GUI > Tested WDA > Trusted WDA from device management on the iPhone
3. Open Appium Inspector and change Remote Path to /wd/hub instead of /
4. When you start a new session from Appium Inspector it will now request you to enter your Passcode on the iPhone then display a transparent overlay on the iPhone display that reads `Automation Running - Hold both volume buttons to stop` which is something new with iOS 15 like KazuCocoa has mentioned (RESIST THE TEMPTATION OF HOLDING BOTH VOLUME BUTTONS)
5. After that, your application should open just fine and load the page source

**Comment by davidjonesdialexa** [comment]
I know this issue is closed, but I've found a related bug(?). I noticed both when running a test via my suite and when inspecting using Appium Inspector, the "Automation Running" overlay remains on screen even after I kill the driver. Has anyone else experienced this? I'm using the [Basic configuration](https://appium.io/docs/en/drivers/ios-xcuitest-real-devices/) for WDA with capabilities in both my suite and the inspector.

**Comment by KazuCocoa** [comment]
Afaik, it means probably Appium/WebDriverAgent process was still running. Usually appium stops the process as https://github.com/appium/appium-xcuitest-driver/blob/master/lib/driver.js#L775-L777 , but some cases may not. 
What about killing the WDA process with double click the home button and swipe the WDA view up? I guess it also may help... Or if the only way to prevent the screen was deleting the WDA app, probably automation process handling issue in the iOS.

**Comment by bcuervo** [comment]
@KazuCocoa @davidjonesdialexa @aryahya Hi guys nice to meet you, I have something similar, I need run a E2E test but in a intermediate point the test need enter any passcode proper of the application to can continue with the flow, do you know any capability for that on iOS? thanks a lot!

**Comment by KazuCocoa** [comment]
No via Appium. I guess sending keys via bluetooth etc may help

**Comment by bcuervo** [comment]
@KazuCocoa thanks a lot for reply, we can solved the step with biometrics https://appium.io/docs/en/commands/device/authentication/finger-print/?

**Comment by KazuCocoa** [comment]
They work only for simulators/emulators. These security functions in real devices has no APIs to manage
