### ISSUE TITLE
Make appium server able to connect with a remote adb server

### ISSUE THREAD

**Issue by arthuRHD** [appium/appium#15899]
## The problem

I have a device farm in a wireless network. Only one computer (on OSX) has access to the farm via adb TCP/IP mode and can be reached from outside thanks to `adb -a nodaemon server` 

Since I'm running appium inside a docker container to be used inside my CI pipeline, I have to connect my appium server node to my adb remote server.

## Possible solutions

- Add an argument like `--adb-host` and `--adb-port` to provide the remote adb data. Forward ADB commands to the remote server.
- Add native support for remote ADB server connections

**Comment by mykola-mokhnach** [comment]
Android drivers support [remoteAdbHost](https://github.com/appium/appium-uiautomator2-driver#adb) capability. Could it be of any use?

**Comment by arthuRHD** [comment]
> Android drivers support [remoteAdbHost](https://github.com/appium/appium-uiautomator2-driver#adb) capability. Could it be of any use?

I can work around with that, Thank you very much.

Feel free to keep this issue open if this feature is interesting. Like a permanent forwarding. Your choice.
