### ISSUE TITLE
Tests are stuck for iOS 

### ISSUE THREAD

**Issue by olegzalipskiy** [appium/appium#15904]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable): - 
* Desktop OS/version used to run Appium: MacOS Monterey, MacOS Catalina, MacOS BigSur
* Node.js version (unless using Appium.app|exe): 7.17.0
* Npm or Yarn package manager: Npm
* Mobile platform/version under test: iOS 14.5
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Details
All-time tests are stuck in different places. For tests I used Docker, but simulator and Appium without docker. Tests are stuck and nothing happened in logs, tests not failed, etc. 

## Link to Appium logs

https://gist.github.com/olegzalipskiy/55e2ef7b5ce19ee011b7b81b89b9d400

## Code To Reproduce Issue [ Good To Have ]

Cant provide any example - code is good and perfect work in Android, and sometimes on iOS too. Also, test freezing all times in different places.

**Comment by mykola-mokhnach** [comment]
Unfortunately the provided log snippet is not enough to assume anything.

Have you investigated the device logs and/or enable them? What happens in Appium logs at the time when the freeze is actually happening?

**Comment by mykola-mokhnach** [comment]
also, are you sure the session life cycle is managed properly? Have you tried to run the server in `--session-override` mode?

**Comment by olegzalipskiy** [comment]
Let me provide the all required info. Go to debug and will back to you soon.

**Comment by olegzalipskiy** [comment]
@mykola-mokhnach tried to run with `--session-override` mode - its cant help. Also, I have upated Appium to the latest version (1.22) and updated Xcode to 13 (iOS 15) - and the issue is still reproducing.
Full appium logs: https://gist.github.com/olegzalipskiy/be1562fc02f66858fdcd7f70036eee17
Simulator log: https://gist.github.com/olegzalipskiy/5112e8f5f2cb3201e11c0a50c1907be9

**Comment by mykola-mokhnach** [comment]
Where does the issue happen in this huge log?

**Comment by olegzalipskiy** [comment]
in this place

**Comment by mykola-mokhnach** [comment]
According to this log the server just stopped receiving any commands from the client. Are you sure it is an issue on the server side?

**Comment by olegzalipskiy** [comment]
Yes, a client sending commands but the server doesn't respond and looks like "don't see" this commands.

**Comment by jlipps** [comment]
It doesn't look like an issue with the Appium server itself. More likely an issue with the client or the Docker setup. The server is still running. Appium just uses Express and it's unlikely there is such a glaring bug in Express. The next step would be to debug network connections on your side to see what could cause the gap in communication between client and server.

**Comment by tivadarmolitorisz** [comment]
@olegzalipskiy could you solve this issue? I'm facing a really similar one!
