### ISSUE TITLE
Unable to automate Chrome version because it is too old for this version of Chromedriver

### ISSUE THREAD

**Issue by baselalali** [appium/appium#15901]
## The problem

I am executing a test with chrome driver/Sauce Labs. The test is fine for android version older then 10, but for other version is failed

`io.appium.java_client.NoSuchContextException: An unknown server-side error occurred while processing the command. Original error: Unable to automate Chrome version because it is too old for this version of Chromedriver.
Chrome version on the device: Chrome/93.0.4577.82
Visit 'https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md' to troubleshoot the problem.
A new session could not be created. Details: session not created: Chrome version must be between 71 and 74`

**Comment by mykola-mokhnach** [comment]
Please provide a proper issue description and attach the full server log
Have you read the tutorial from the error message link?

**Comment by baselalali** [comment]
```
POST /context 
{
	"name": "WEBVIEW_chrome"
}
"{\"status\":13,\"value\":{\"message\":\"An unknown server-side error occurred while processing the command. Original error: Unable to automate Chrome version because it is too old for this version of Chromedriver.\\nChrome version on the device: Chrome/94.0.4606.61\\nVisit 'https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md' to troubleshoot the problem.\\nA new session could not be created. Details: session not created: Chrome version must be between 71 and 75\\n  (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70 [truncated]"
```

**Comment by StephanB75** [comment]
have you tried to use the mentioned chromedriver version ?

https://chromedriver.chromium.org/downloads

**Comment by baselalali** [comment]
I can not download the chrome drive, since the i am using remote execution with sauce lab. @StephanB75 @mykola-mokhnach There is an optionality to ignore the driver version ? :)

**Comment by StephanB75** [comment]
when you execute your test in the cloud and the device is also in the cloud, than i would ask saucelabs.
Sorry for no better answer, never used saucelabs myself

**Comment by mykola-mokhnach** [comment]
Then it would make sense to create a support requests to Sauce Labs about how to provide a proper driver version. There is nothing we could do about it in Appium. Each chromedriver version only supports a limited range of Chrome versions.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by baselalali** [comment]
@jlipps any support?

**Comment by mykola-mokhnach** [comment]
@baselalali Consider using Appium forum if you have more questions.

**Comment by baselalali** [comment]
Could pls send the link for appium forum

**Comment by StephanB75** [comment]
have you checked this ?
https://docs.saucelabs.com/dev/test-configuration-options/

Saucelabs does have parameters for changing chromedriver versions. Google is your friend ;)

**Comment by mykola-mokhnach** [comment]
> Could pls send the link for appium forum

https://discuss.appium.io
