### ISSUE TITLE
getScreenShot fails while inspecting iOS 15 through Appium inspector

### ISSUE THREAD

**Issue by aamish-arora1** [appium/appium#15908]
## The problem

I updated iOS device to iOS 15 and used it for automation with Appium, Appium inspector fails to get screenshot and returns 500, though its interacting with device.  Xcode version is 13

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21
* Desktop OS/version used to run Appium: MAC iOS: 11.4
* Mobile platform/version under test: iOS 15
* Real device or emulator/simulator: real device (iPhoneSE (2020))
* Appium CLI or Appium.app|exe: Appium app

error log:
[W3C] Matched W3C error code 'unable to capture screen' to UnableToCaptureScreen
[XCUITest] Taking screenshot with WDA
[WD Proxy] Matched '/screenshot' to command name 'getScreenshot'
[WD Proxy] Proxying [GET /screenshot] to [GET http://127.0.0.1:8102/session/6544DEBD-0487-429F-9068-B868EB3211F3/screenshot] with no body
[WD Proxy] Got response with status 500: {"value":{"error":"unable to capture screen","message":"A screen capture was made impossible","traceback":""},"sessionId":"6544DEBD-0487-429F-9068-B868EB3211F3"}
[W3C] Matched W3C error code 'unable to capture screen' to UnableToCaptureScreen
[W3C (9824b81a)] Encountered internal error running command: UnableToCaptureScreen: A screen capture was made impossible
[W3C (9824b81a)]     at errorFromW3CJsonCode (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:780:25)
[W3C (9824b81a)]     at ProxyRequestError.getActualError (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:663:14)
[W3C (9824b81a)]     at JWProxy.command (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:272:19)
[W3C (9824b81a)]     at runMicrotasks ()
[W3C (9824b81a)]     at processTicksAndRejections (internal/process/task_queues.js:85:5)
[HTTP] <-- GET /wd/hub/session/9824b81a-a01d-42b1-b3ad-050e2f3fedcd/screenshot 500

**Comment by mykola-mokhnach** [comment]
Appium 1.21 does not support iOS 15. Please upgrade to a newer server version. Closed as duplicate

**Comment by aamish-arora1** [comment]
Tried with appium v 1.22 , reinstalled integration app and on installing webdriver agent appium throws error :
[XCUITest] Executing command 'getScreenshot'

[XCUITest] Taking screenshot with WDA

[WD Proxy] Matched '/screenshot' to command name 'getScreenshot'

[WD Proxy] Proxying [GET /screenshot] to [GET http://127.0.0.1:8101/session/FC05E6B5-EED5-4B62-B57C-84AA52F49DA7/screenshot] with no body

[WD Proxy] Got response with status 500: {"value":{"error":"unable to capture screen","message":"A screen capture was made impossible","traceback":""},"sessionId":"FC05E6B5-EED5-4B62-B57C-84AA52F49DA7"}

[W3C] Matched W3C error code 'unable to capture screen' to UnableToCaptureScreen

[XCUITest] Error getting screenshot: A screen capture was made impossible

what could be possible solution?

**Comment by mykola-mokhnach** [comment]
It might be that WebDriverAgent binary is cached. Try the cleanup steps from https://github.com/appium/appium/issues/15886

**Comment by aamish-arora1** [comment]
I have tried those steps and started from scratch with Appium 1.22 Xcode 13 iOS 15 : getting this error :
Failed to create session. An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65 xcodebuild error message: 2021-09-28 15:07:11.800 xcodebuild[6750:141250] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder “WebDriverAgentRunner_iphoneos15.0-arm64.xctestrun” doesn’t exist." UserInfo={NSFilePath=/Users/aamish.arora/Library/Developer/Xcode/DerivedData/WebDriverAgent-aghlrsejdreqngftgvcqwnjgrbou/Build/Products/WebDriverAgentRunner_iphoneos15.0-arm64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7faec1b84b20 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}} ** TEST BUILD FAILED ** *** If you believe this error represents a bug, please attach the result bundle at /Users/aamish.arora/Library/Developer/Xcode/DerivedData/WebDriverAgent-aghlrsejdreqngftgvcqwnjgrbou/Logs/Test/Test-WebDriverAgentRunner-2021.09.28_15-07-11-+0530.xcresult 2021-09-28 15:07:12.002 xcodebuild[6750:141175] [MT] IDETestOperationsObserverDebug: 0.192 elapsed -- Testing started completed. 2021-09-28 15:07:12.002 xcodebuild[6750:141175] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start 2021-09-28 15:07:12.002 xcodebuild[6750:141175] [MT] IDETestOperationsObserverDebug: 0.192 sec, +0.192 sec -- end Test session results, code coverage, and logs: /Users/aamish.arora/Library/Developer/Xcode/DerivedData/WebDriverAgent-aghlrsejdreqngftgvcqwnjgrbou/Logs/Test/Test-WebDriverAgentRunner-2021.09.28_15-07-11-+0530.xcresult Testing failed: Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the Signing & Capabilities editor. WebDriverAgentRunner: WebDriverAgentRunner-Runner encountered an error (Failed to install or launch the test runner. If you believe this error represents a bug, please attach the result bundle at /Users/aamish.arora/Library/Developer/Xcode/DerivedData/WebDriverAgent-aghlrsejdreqngftgvcqwnjgrbou/Logs/Test/Test-WebDriverAgentRunner-2021.09.28_15-07-11-+0530.xcresult. (Underlying Error: Executable Not Found. /Users/aamish.arora/Library/Developer/Xcode/DerivedData/WebDriverAgent-aghlrsejdreqngftgvcqwnjgrbou/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app is not a valid path to an executable file. Please rebuild the project to ensure that all required executables are created. Check your project settings to ensure that a valid executable will be built.)) ** TEST EXECUTE FAILED ** Testing started. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.

**Comment by mykola-mokhnach** [comment]
> Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the Signing & Capabilities editor

The error is expected. After WDA sources have been bumped they must be signed properly.

**Comment by aamish-arora1** [comment]
Issue Resolved , thanks
