### ISSUE TITLE
No Route Found for /wd/hub/session/element

### ISSUE THREAD

**Issue by jose-larrubia-savia** [appium/appium#15918]
## The problem

Appium is unable to route elements. Receiving 404 no route found on every configuration tested. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22
* Last Appium version that did not exhibit the issue (if applicable): None
* Desktop OS/version used to run Appium: Azure Devops Hosted MacOs-11 
* Node.js version (unless using Appium.app|exe): 
* Npm or Yarn package manager: npm
* Mobile platform/version under test: android api 27
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/jose-larrubia-savia/753937f738f54df2b8e520a2c5c4e548

**Comment by mykola-mokhnach** [comment]
The error is expected. The route for element lookup must contain a valid session identifier. Make sure your client is sending proper requests

**Comment by jose-larrubia-savia** [comment]
I don't really understand why the error is expected. The same tests with the same configuration work on a Windows 10 Local machine. How can I test my client is sending the proper requests?

**Comment by jlipps** [comment]
@jose-larrubia-savia `POST /wd/hub/session/element` is not a valid webdriver endpoint. It needs to be `POST /wd/hub/session/<some-session-id>/element`. So if the session ID is not being included in this call it likely indicates an error with the client. At any rate, the server is functioning as intended here, so I would create this issue at the repo corresponding to the webdriver/appium client you are using instead.
