### ISSUE TITLE
While running IOS automation scripts it is always picking up cache data

### ISSUE THREAD

**Issue by nanduri1805** [appium/appium#15915]
In my App am trying to scan a QR code which redirects me to web view and ask me to enter credentials  to give me Pin.

Here when ever am scanning the QR code instead of going to WebView it is giving me pin or error message. looks like data is taking from cache this is only with IOS.

Tried clearsystemFiles as true also cleared safari history before every automation script it is still same.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21
Appium logs
[appium-server-logs.txt](https://github.com/appium/appium/files/7252011/appium-server-logs.txt)
* Desktop OS/version used to run Appium:1.21
* Mobile platform/version under test: IOS 14.6
* Real device or emulator/simulator: real IOS device 
* Appium CLI or Appium.app|exe:

**Comment by mykola-mokhnach** [comment]
Not sure how your issue is related to Appium. Safari remote debugger does not provide any APIs to clear the cache. The only way to do it is to open Safari settings and click a corresponding button.

**Comment by nanduri1805** [comment]
Am opening settings and clearing the cache before every automation script but still when I scan QR code it is not redirecting me to webpage

**Comment by mykola-mokhnach** [comment]
I'm still unsure if there is anything that could be done there from Appium perspective. Try to investigate your app logs with app developers

**Comment by nanduri1805** [comment]
Manually we were able to switch to web view . we see this issue with automation....  am using clearsystemfiles capability as well. I see this behavior only in IOS

**Comment by nanduri1805** [comment]
As part of automation my code goes to settings app and clear History later the script is executed , still  the driver is not going to web view in IOS . Do I need to use any setting or capability for this

**Comment by KazuCocoa** [comment]
> Manually we were able to switch to web view

What about doing the manual stuff while an appium is running on the device?
i wonder such behavior occurs when xctest process is running on the device.

For example, Siri setup during xctest process running will be ignored when the xctest stops.
I don't know of Safari case, but I wonder such behavior could happen.

**Comment by jlipps** [comment]
Are you using Appium's getContexts command? What contexts are returned?

**Comment by nanduri1805** [comment]
it says no webcontext found and only Native_app context is showing

**Comment by jlipps** [comment]
In new versions of iOS it's necessary to interact with the webview before it will show up in the context list. So perform a tap or swipe in it as part of your automation, then look for contexts.

**Comment by nanduri1805** [comment]
oh let me check with IOS 15 Thankyou

**Comment by nanduri1805** [comment]
With IOS 14.8 it is still the same. When I scan QR in IOS, it will prompt " Do you wish to open Microsoft page" and my code clicks on continue button then page opens . When i see logs continue button  and otherTitletext button status is 200 . But ideally I am not seeing these two elements while I run automation script. Also value":"//*[@id='otherTileText'] this is webpage element


alling AppiumDriver.findElements() with args: ["xpath","//*[@label='Continue']","dff94413-88b6-4244-ba6c-9453e639e2ea"]
[XCUITest] Executing command 'findElements'
[BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id, css selector
[BaseDriver] Waiting up to 0 ms for condition
[WD Proxy] Matched '/elements' to command name 'findElements'
[WD Proxy] Proxying [POST /elements] to [POST http://127.0.0.1:8100/session/A56937C4-05C3-4C52-95A5-97620E47FD6B/elements] with body: {"using":"xpath","value":"//*[@label='Continue']"}
[WD Proxy] Got response with status 200: {"value":[],"sessionId":"A56937C4-05C3-4C52-95A5-97620E47FD6B"}
[W3C (dff94413)] Responding to client with driver.findElements() result: []
[HTTP] <-- POST /wd/hub/session/dff94413-88b6-4244-ba6c-9453e639e2ea/elements 200 316 ms - 12
[HTTP] 
[HTTP] --> GET /wd/hub/session/dff94413-88b6-4244-ba6c-9453e639e2ea/contexts
[HTTP] {}
[W3C (dff94413)] Calling AppiumDriver.getContexts() with args: ["dff94413-88b6-4244-ba6c-9453e639e2ea"]
[XCUITest] Executing command 'getContexts'
[XCUITest] Getting list of available contexts
[iOS] Retrieving contexts and views
[XCUITest] Selecting by url: false 
[RemoteDebugger] Remote Debugger version 8.13.2
[RemoteDebugger] useNewSafari --> false
[RemoteDebugger] Checking which communication style to use (non-Safari on platform version '14.6')
[RemoteDebugger] Platform version equal or higher than '12.2': true
[RemoteDebugger] Setting communication protocol: using Target-based communication
[RemoteDebugger] Sending connection key request
[RemoteDebugger] Sending '_rpc_reportIdentifier:' message (id: 0): 'setConnectionKey'
[RemoteDebugger] Sending to Web Inspector took 2ms
[RemoteDebugger] Sending connection key request
[RemoteDebugger] Sending '_rpc_reportIdentifier:' message (id: 2): 'setConnectionKey'
[RemoteDebugger] Sending to Web Inspector took 2ms
[RemoteDebugger] Selecting application
[RemoteDebugger] No applications currently connected.
[XCUITest] No web frames found.
[W3C (dff94413)] Responding to client with driver.getContexts() result: ["NATIVE_APP"]
[HTTP] <-- GET /wd/hub/session/dff94413-88b6-4244-ba6c-9453e639e2ea/contexts 200 192 ms - 24
[HTTP] 
[RemoteDebugger] Received connected automation availability state: "WIRAutomationAvailabilityAvailable"
[RemoteDebugger] Received connected applications list: PID:74
[RemoteDebugger] Received connected driver list: {}
[HTTP] --> GET /wd/hub/session/dff94413-88b6-4244-ba6c-9453e639e2ea/contexts
[HTTP] {}
[W3C (dff94413)] Calling AppiumDriver.getContexts() with args: ["dff94413-88b6-4244-ba6c-9453e639e2ea"]
[XCUITest] Executing command 'getContexts'
[XCUITest] Getting list of available contexts
[iOS] Retrieving contexts and views
[XCUITest] Selecting by url: false 
[RemoteDebugger] Sending connection key request
[RemoteDebugger] Sending '_rpc_reportIdentifier:' message (id: 4): 'setConnectionKey'
[RemoteDebugger] Sending to Web Inspector took 2ms
[RemoteDebugger] Selecting application
[RemoteDebugger] No applications currently connected.
[XCUITest] No web frames found.
[W3C (dff94413)] Responding to client with driver.getContexts() result: ["NATIVE_APP"]
[HTTP] <-- GET /wd/hub/session/dff94413-88b6-4244-ba6c-9453e639e2ea/contexts 200 6 ms - 24
[HTTP] 
[HTTP] --> POST /wd/hub/session/dff94413-88b6-4244-ba6c-9453e639e2ea/elements
[HTTP] {"using":"xpath","value":"//*[@id='otherTileText']"}
[W3C (dff94413)] Calling AppiumDriver.findElements() with args: ["xpath","//*[@id='otherTileText']","dff94413-88b6-4244-ba6c-9453e639e2ea"]
[XCUITest] Executing command 'findElements'
[BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id, css selector
[BaseDriver] Waiting up to 0 ms for condition
[WD Proxy] Matched '/elements' to command name 'findElements'
[WD Proxy] Proxying [POST /elements] to [POST http://127.0.0.1:8100/session/A56937C4-05C3-4C52-95A5-97620E47FD6B/elements] with body: {"using":"xpath","value":"//*[@id='otherTileText']"}
[WD Proxy] Got response with status 200: {"value":[],"sessionId":"A56937C4-05C3-4C52-95A5-97620E47FD6B"}
[W3C (dff94413)] Responding to client with driver.findElements() result: []
[HTTP] <-- POST /wd/hub/session/dff94413-88b6-4244-ba6c-9453e639e2ea/elements 200 235 ms - 12
[HTTP]

**Comment by nanduri1805** [comment]
Hurray  :)  it is working with IOS 15 Thankyou @jlipps  @KazuCocoa @mykola-mokhnach
