### ISSUE TITLE
Running test on real iOS device fails because of app singing error 

### ISSUE THREAD

**Issue by bwomsm1** [appium/appium#15924]
## The problem

I lately added added a new iPhone device to my automation environment, iPhone SE. 
This new iPhone is running iOS 14.7.1
When I plugged it, I took care to build the WebDriverAgentRunner on top of that new iPhone device. 

The error which I am getting on the Appium server is:
```
[debug] [35m[W3C][39m Encountered internal error running command: Error: Could not install '/Users/boazwarshawsky/workspace/builds/aeroscout_links/ios/ndev/AeroScoutLinks.app':
[debug] [35m[W3C][39m   - Unexpected data: {"Error":"ApplicationVerificationFailed","ErrorDetail":-402620394,"ErrorDescription":"Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.6gzrqp/extracted/AeroScoutLinks.app : 0xe8008016 (The executable was signed with invalid entitlements.)"}
[debug] [35m[W3C][39m   - 2021-10-04 08:45:55.394 ios-deploy[92385:2327435] [ !! ] Error 0xe8008016: The executable was signed with invalid entitlements. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)
[debug] [35m[W3C][39m 
[debug] [35m[W3C][39m     at IOSDeploy.install (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/ios-deploy.js:56:15)
```

The xcode version which I am using is: 13.0

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable): None
* Desktop OS/version used to run Appium: Mac OS Big Sur
* Node.js version (unless using Appium.app|exe): v12.9.1
* Npm or Yarn package manager: npm
* Mobile platform/version under test: 14.7.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: cli

## Details

What is weird, is that the test does running as expected with another older device I have (iPhone X, iOS 14.7.1) 
I don't understand what is wrong with that new device. 

I can confirm that I registered correctly this new iPhone device to my apple developer account portal. 
I can confirm that the same app bundle is running correctly on another iPhone device I have. 

## Link to Appium logs
https://github.com/bwomsm1/AppiumLogs/blob/master/appium_ios.log

## Code To Reproduce Issue [ Good To Have ]
Just by running any iOS test

**Comment by KazuCocoa** [comment]
> another older device I have (iPhone X, iOS 14.7.1)

Did you sign `/Users/boazwarshawsky/workspace/builds/aeroscout_links/ios/ndev/AeroScoutLinks.app` with a new provisioning after adding the new device in the provisioning profile?

**Comment by bwomsm1** [comment]
@KazuCocoa No.

**Comment by KazuCocoa** [comment]
then, the new device was not in the app's profile.

**Comment by bwomsm1** [comment]
thanks for the super fast response. I am currently building and checking that.

**Comment by bwomsm1** [comment]
Hi @KazuCocoa, 
How I can be sure that I have on my build machine the latest provisioning profile which is updated with the new iPhone device I have? 
After making sure that my device is registered on Apple Developer Account I did that on xcode:
<img width="824" alt="Screen Shot 2021-10-04 at 11 23 15" src="https://user-images.githubusercontent.com/5571230/135817974-aa170530-6b2c-4245-ad4a-d2c485c56fb5.png">

Is that all?

**Comment by KazuCocoa** [comment]
I guess the download is enough, but I must have deleted the profile once from local before to be sure it.
Btw, https://developer.apple.com/documentation/xcode/distributing-your-app-to-registered-devices is Apple's official documentation for it. It addresses the download is enough..

**Comment by mykola-mokhnach** [comment]
closed as not an issue
