### ISSUE TITLE
get_window_size() and set_window_rect() methods don't work with windows agent. 

### ISSUE THREAD

**Issue by tthompsen-foreflight** [appium/appium#15923]
## The problem

The get_window_size() and set_window_rect() methods don't work with the windows agent/driver. 

## Environment

* Appium version : Both desktop version 1.22.0 and 1.21.0 
![appium im](https://user-images.githubusercontent.com/83083395/135667107-bf240a54-3f43-482d-a0d2-099b7a4b2dfd.JPG) Windows 10 

* Windows 10 PC running a UWP app and Windows 10 pro windows surface pro 3
* Real device and PC
* Appium.app|exe

## Details

In order to dynamically adjust touch actions for different screen dimensions we need access to the window size or be able to set it... Im writing cross platform tests for iOS and Windows using Python/Pytest . The code implementation works on iOS but not windows 

Python code example :

size = self.driver.get_window_size()
center_x = size['width'] / 2
center_y = size['height'] / 2

## Link to Appium logs

[WinAppDriver] HTTP/1.1 200 OK
[WinAppDriver] Content-Length: 63
[WinAppDriver] Content-Type: application/json
[WinAppDriver]
[WinAppDriver] {"sessionId":"F16EC32C-21E9-41D2-9041-14A5BE5FC0E5","status":0}
[HTTP] --> GET /wd/hub/session/683b5e59-dbd0-4ba6-be7d-b286213dbf8c/window/rect
[HTTP] {}
[W3C (683b5e59)] Driver proxy active, passing request on via HTTP proxy
[WD Proxy] Matched '/wd/hub/session/683b5e59-dbd0-4ba6-be7d-b286213dbf8c/window/rect' to command name 'getWindowRect'
[WD Proxy] Proxying [GET /wd/hub/session/683b5e59-dbd0-4ba6-be7d-b286213dbf8c/window/rect] to [GET http://127.0.0.1:4730/wd/hub/session/F16EC32C-21E9-41D2-9041-14A5BE5FC0E5/window/rect] with no body
[WinAppDriver] ==========================================
[WinAppDriver] GET /wd/hub/session/F16EC32C-21E9-41D2-9041-14A5BE5FC0E5/window/rect HTTP/1.1
[WinAppDriver] Accept: application/json, /
[WinAppDriver] Connection: keep-alive
[WinAppDriver] Content-Type: application/json; charset=utf-8
[WinAppDriver] Host: 127.0.0.1:4730
[WinAppDriver] User-Agent: appium
[WinAppDriver] ### WinAppDriver::CommandHandler::window::HandleCommandAsMidPoint - Command  is not recognized
[WinAppDriver] HTTP/1.1 404 Not Found
[WinAppDriver] Content-Length: 147
[WinAppDriver] Content-Type: application/json
[WinAppDriver]
[WinAppDriver] {"status":9,"value":{"error":"unknown command","message":"Command not recognized: GET: /session/F16EC32C-21E9-41D2-9041-14A5BE5FC0E5/window/rect"}}
[WD Proxy] Got response with status 404: {"status":9,"value":{"error":"unknown command","message":"Command not recognized: GET: /session/F16EC32C-21E9-41D2-9041-14A5BE5FC0E5/window/rect"}}
[W3C] Matched W3C error code 'unknown command' to UnknownCommandError
[HTTP] <-- GET /wd/hub/session/683b5e59-dbd0-4ba6-be7d-b286213dbf8c/window/rect 404 6 ms - 784
[HTTP]

model/fdpx/base_view_model.py:228: in zoom_in
    size = self.driver.get_window_size()
venv3/automate/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py:1108: in get_window_size
    size = self.get_window_rect()
venv3/automate/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py:1165: in get_window_rect
    return self.execute(Command.GET_WINDOW_RECT)['value']
venv3/automate/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py:321: in execute
    self.error_handler.check_response(response)
venv3/automate/lib/python3.8/site-packages/appium/webdriver/errorhandler.py:29: in check_response
    raise wde
venv3/automate/lib/python3.8/site-packages/appium/webdriver/errorhandler.py:24: in check_response
    super(MobileErrorHandler, self).check_response(response)

## Details set_window_rect()

Python code example : 

self.driver.set_window_rect(0, 0, 1200, 900)

## Link to Appium logs

[WinAppDriver] {"sessionId":"60BA8180-7610-4762-928E-BF2DD830F5DB","status":0}
[HTTP] --> POST /wd/hub/session/ceeb0642-c89f-4e86-966a-b501671bc5f7/window/rect
[HTTP] {"x":0,"y":0,"width":1200,"height":900,"sessionId":"ceeb0642-c89f-4e86-966a-b501671bc5f7"}
[W3C (ceeb0642)] Driver proxy active, passing request on via HTTP proxy
[WD Proxy] Matched '/wd/hub/session/ceeb0642-c89f-4e86-966a-b501671bc5f7/window/rect' to command name 'setWindowRect'
[WD Proxy] Proxying [POST /wd/hub/session/ceeb0642-c89f-4e86-966a-b501671bc5f7/window/rect] to [POST http://127.0.0.1:4733/wd/hub/session/60BA8180-7610-4762-928E-BF2DD830F5DB/window/rect] with body: {"x":0,"y":0,"width":1200,"height":900,"sessionId":"ceeb0642-c89f-4e86-966a-b501671bc5f7"}
[WinAppDriver] ==========================================
[WinAppDriver] POST /wd/hub/session/60BA8180-7610-4762-928E-BF2DD830F5DB/window/rect HTTP/1.1
[WinAppDriver] Accept: application/json, */*
[WinAppDriver] Connection: keep-alive
[WinAppDriver] Content-Length: 90
[WinAppDriver] Content-Type: application/json; charset=utf-8
[WinAppDriver] Host: 127.0.0.1:4733
[WinAppDriver] User-Agent: appium
[WinAppDriver] ### WinAppDriver::CommandHandler::window::HandleCommandAsMidPoint - Command  is not recognized
[WinAppDriver] HTTP/1.1 404 Not Found
[WinAppDriver] Content-Length: 148
[WinAppDriver] Content-Type: application/json
[WinAppDriver]
[WinAppDriver] {"status":9,"value":{"error":"unknown command","message":"Command not recognized: POST: /session/60BA8180-7610-4762-928E-BF2DD830F5DB/window/rect"}}
[WD Proxy] Got response with status 404: {"status":9,"value":{"error":"unknown command","message":"Command not recognized: POST: /session/60BA8180-7610-4762-928E-BF2DD830F5DB/window/rect"}}
[W3C] Matched W3C error code 'unknown command' to UnknownCommandError
[HTTP] <-- POST /wd/hub/session/ceeb0642-c89f-4e86-966a-b501671bc5f7/window/rect 404 6 ms - 786
[HTTP]

model/fdpx/base_view_model.py:226: in zoom_in
    self.driver.set_window_rect(0,0,1200,900)
venv3/automate/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py:1180: in set_window_rect
    return self.execute(Command.SET_WINDOW_RECT, {"x": x, "y": y,
venv3/automate/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py:321: in execute
    self.error_handler.check_response(response)
venv3/automate/lib/python3.8/site-packages/appium/webdriver/errorhandler.py:29: in check_response
    raise wde
venv3/automate/lib/python3.8/site-packages/appium/webdriver/errorhandler.py:24: in check_response
    super(MobileErrorHandler, self).check_response(response)

**Comment by jlipps** [comment]
This should be reported to the WinAppDriver repo instead

**Comment by tthompsen-foreflight** [comment]
Ok ill post it there. Thanks.

**Comment by tthompsen-foreflight** [comment]
> This should be reported to the WinAppDriver repo instead

is this the correct one? https://github.com/appium/appium-windows-driver

**Comment by mykola-mokhnach** [comment]
it's https://github.com/microsoft/WinAppDriver one

**Comment by tthompsen-foreflight** [comment]
@jlipps @mykola-mokhnach  after reviewing the WinAppDriver supported API's doc https://github.com/microsoft/WinAppDriver/blob/master/Docs/SupportedAPIs.md it appears that Appium is sending requests to unsupported APIs... ex. windows/rect should be windows/size, and theres several touch actions that are different too... so is that still and window app driver issue? or is that something you guys would have to fix?

**Comment by mykola-mokhnach** [comment]
I believe this happens because the APIs above are JWP ones and your client requests W3C, which definitely does not work. 
As a possible workaround you could try to perform custom requests to the particular endpoints directly from the client or enforce it to switch to JWP mode (which is already a bad advice). See https://github.com/microsoft/WinAppDriver/issues/1610 for more details.

**Comment by mykola-mokhnach** [comment]
Theoretically we could try to perform some w3c-to-jwp conversion from inside the driver code, but this would be just an ugly workaround to the original server issue and also no guarantee all edge cases going to work as expected there. Unfortunately WinAppDriver itself has not been maintained by MS for more than two years and its source code is also not available publicly.

**Comment by tthompsen-foreflight** [comment]
@mykola-mokhnach Okay thanks for the info! I will file a bug with them and see if i get a response ... If i don't then I guess we'll have to come up with another solution.

**Comment by Liqun-Ma** [comment]
Hello, I am using Appium 2.0.0-beta.61. I tried:
`session.Manage().Window.Size = new Size(600,800);`

I got below message, @jlipps @mykola-mokhnach could you please tell me how to fix this?

[W3C] Bad parameters: BadParametersError: Parameters were incorrect. We wanted {"required":["x","y","width","height"]} and you sent ["width","height"]
