### ISSUE TITLE
Invalid number value (infinite) in JSON write error for iOS 15

### ISSUE THREAD

**Issue by ikhaled28** [appium/appium#15942]
## The problem
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Invalid number value (infinite) in JSON write

## Environment

* Appium version (or git revision) that exhibits the issue: 1.23.0 beta and 1.22.0
* Last Appium version that did not exhibit the issue (if applicable): 1.21.0
* Desktop OS/version used to run Appium: MacOS 11.6
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: iOS 15
* Real device or emulator/simulator: iPhone 11
* Appium CLI or Appium.app|exe: both

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/ikhaled28/bef9450cf3641ad5e2ac75969129a8e5

**Comment by mykola-mokhnach** [comment]
Pushed the improvement to WebDriverAgent
