### ISSUE TITLE
[iOS] deleteSession does not close the app on real devices

### ISSUE THREAD

**Issue by bswhb** [appium/appium#15958]
## The problem

We started the app through Appium Inspector, and the app was not closed when we stopped the session in appium inspector. We came across this issue just for a few weeks, is this a new feature for appium, or caused by our environment?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.23.0-beta.0
* Last Appium version that did not exhibit the issue (if applicable): perhaps 1.21.x 
* Desktop OS/version used to run Appium: macOS 11.6
* Node.js version (unless using Appium.app|exe): v16.7.0
* Npm or Yarn package manager: 7.20.3
* Mobile platform/version under test: iOS 15.0.1
* Real device or emulator/simulator: iPhone XR
* Appium CLI or Appium.app|exe: appium-inspector 

## Details

Here's the desired caps for your information:
```
{
  "platformName": "iOS",
  "platformVersion": "15.0",
  "deviceName": "iPhone",
  "udid": "<udid>",
  "automationName": "XCUITest",
  "app": "<bundle id>",
  "startIWDP": true,
  "newCommandTimeout": 0,
  "noReset": true,
  "appium:useJSONSource": true
}
```

## Link to Appium logs

```
[HTTP] --> DELETE /wd/hub/session/9dfd6948-46e7-4afe-9d78-e0760eae3c49
[HTTP] {}
[debug] [W3C (9dfd6948)] Calling AppiumDriver.deleteSession() with args: ["9dfd6948-46e7-4afe-9d78-e0760eae3c49"]
[debug] [BaseDriver] Event 'quitSessionRequested' logged at 1634114224800 (16:37:04 GMT+0800 (中国标准时间))
[Appium] Removing session 9dfd6948-46e7-4afe-9d78-e0760eae3c49 from our master session list
[debug] [WD Proxy] Matched '/session/9dfd6948-46e7-4afe-9d78-e0760eae3c49' to command name 'deleteSession'
[debug] [WD Proxy] Proxying [DELETE /session/9dfd6948-46e7-4afe-9d78-e0760eae3c49] to [DELETE http://127.0.0.1:8100/session/A7716C93-2EE1-4CBA-BF61-1686857EB142] with no body
[debug] [WD Proxy] Got response with status 200: {"value":null,"sessionId":null}
[DevCon Factory] Releasing connections for 00008020-000928220251002E device on any port number
[DevCon Factory] Found cached connections to release: ["00008020-000928220251002E:8100"]
[DevCon Factory] Releasing the listener for '00008020-000928220251002E:8100'
[debug] [iProxy@00008020:8100] Closing the connection
[debug] [DevCon Factory] Cached connections count: 0
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [BaseDriver] Event 'quitSessionFinished' logged at 1634114224816 (16:37:04 GMT+0800 (中国标准时间))
[debug] [W3C (9dfd6948)] Received response: null
[debug] [W3C (9dfd6948)] But deleting session, so not returning
[debug] [W3C (9dfd6948)] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/9dfd6948-46e7-4afe-9d78-e0760eae3c49 200 17 ms - 14
[HTTP]
[iProxy@00008020:8100] The connection has been closed
```

## Code To Reproduce Issue [ Good To Have ]

N/A

**Comment by jlipps** [comment]
It's because you have `appium:noReset` set to true. From the XCUITest driver docs on this capability:

> Prevents the device to be reset before the session startup if set to true. This means that the application under test is not going to be terminated neither its data cleaned. false by default

if you want to terminate the app even with noReset set to true, set `appium:shouldTerminateApp` to true as well.
