### ISSUE TITLE
Unable to swipe from the bottom to the top to open control center

### ISSUE THREAD

**Issue by jstephancc** [appium/appium#15950]
## The problem

In my tests on iOS devies i need to switch from Wifi to 3G/4G. Up to appium, there is no method to switch it directly by some command. So I'm opening control_center_position from the top or bottom and clicking on the menu controls.

Since appium 1.22 & iOS 15 I'm not able to swipe from the bottom to the top to open control center on iPhone 8.
Using any phone i can easily swipe in other way around (top->bottom) and then close (bottom->top).

There is no appium errors./ issues

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.0
* Last Appium version that did not exhibit the issue (if applicable): 1.21
* Desktop OS/version used to run Appium: Latest OSX
* Node.js version (unless using Appium.app|exe): 14
* Npm or Yarn package manager: 7.15
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: real, iphone 8
* Appium CLI or Appium.app|exe: CLI

## Details

My iPhone has screen size: {"width":375,"height":667}

I'm swiping:
```
        self.driver.swipe(187, 667, 187, 0, 500)
```

While replacing/switching start_y with end_y, control center will be opened from the top properly.

How can i solve this problem? Or maybe there is another way to check&control network on iOS?

**Comment by jlipps** [comment]
How is driver.swipe implemented? Is it using W3C actions or some older method? You could try constructing W3C actions yourself.

**Comment by Sylvie-qa** [comment]
@jstephancc I am having your exact problem trying to swipe up to get control centre. I have basically the same code (using TouchAction) as you showed at the top. 
This code works fine with appium 1.22 and iOS 14.8 
but **NOT** with 1.22 and **iOS 15.** 

It would be a great help if you could tell me how you solved the problem. This is a real blocker for my automatic tests on iOS 15. Thanks for your help!
