### ISSUE TITLE
Upgrade to ESLint v8.x

### ISSUE THREAD

**Issue by boneskull** [appium/appium#15952]
Appium should upgrade to the new ESLint v8 when possible, as this adds support for all manner of new syntax (including private fields).  Given some of our plugins have peer dependencies on v7.x, this won't be possible until those plugins upgrade, or we drop them.

The plugins preventing this upgrade include:

- `@babel/eslint-parser` - We may not even need this at all.  AFAICT It's only necessary if Appium is using experimental (e.g., Stage-3 or less) proposals, and I don't believe it is.
- `eslint-plugin-import` - This provides several safeguards which are useful (e.g., guards against missing modules)
- `eslint-find-rules` - I have no idea what this is or why it's here.  @jlipps?

I think we should give `eslint-plugin-import` some time (say, a month), then just go ahead with the upgrade without it.  It's useful, but not so useful it should hold us back from upgrading ESLint.

Note: this issue affects the `eslint-config-appium` package

**Comment by boneskull** [comment]
All our plugins would need to upgrade to support ESLint 8 as well, and...I think they have? So we should give this a shot.

**Comment by boneskull** [comment]
well, they aren't all upgraded, but it might work anyway. or it would... if `gulp-eslint` didn't choose an old eslint version for us.

**Comment by boneskull** [comment]
_anyway_, `eslint@8` works, _if_ we don't run it with gulp.  `gulp-eslint` hasn't been upgraded in two years.  we kind of need to stop using it.

I suspect migration away from gulp will be done incrementally (and it can be!)

**Comment by jlipps** [comment]
fine with me!
