### ISSUE TITLE
WDA only return  “LANDSCAPE” with “orientation” interface 

### ISSUE THREAD

**Issue by focalism** [appium/appium#15967]
## The problem

when  get the orienttation with the "orientation" interface， only get “LANSCAPE” whether  "LANSCAPE RIGHT" or "LANSCAPE RIGHT"

I saw the code in  [FBOrientationCommands.m](https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Commands/FBOrientationCommands.m)

![image](https://user-images.githubusercontent.com/10719644/137447830-a82ec8e6-e77e-41e3-863b-2ab727b6634f.png)

I don’t know if it’s a mistake or for other purposes

**Comment by mykola-mokhnach** [comment]
This is by design. If you'd like to know more about the current orientation then consider using rotation-related endpoints

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
