### ISSUE TITLE
Appium2.0: JWP responses within a W3C session

### ISSUE THREAD

**Issue by rillgen-saucelabs** [appium/appium#15963]
## The problem

When running tests using ChromeDriver some commands such as `/url` and `/title` return a JWP response (i.e. containing the `status` field) although the session is created as W3C.

## Environment

* Appium version (or git revision) that exhibits the issue: 2.0.0-beta.18
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS
* Node.js version (unless using Appium.app|exe): v12.22.7
* Npm or Yarn package manager:
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: cli

## Details

The session creation and session close commands return as W3C, seems to be affecting only commands ran by the chromedriver. Same version of chromedriver works as expected with appium server v1.18.3.

## Link to Appium logs

https://gist.github.com/rillgen-saucelabs/d2beb99c8d9aec4cde3d4a77ec915222

## Code To Reproduce Issue [ Good To Have ]

Here is a dump of the requests and responses in HAR format: https://gist.github.com/rillgen-saucelabs/dbd5f347c8154d25cd23289983c5064b

**Comment by rillgen-saucelabs** [comment]
I'm using the same version of chromedriver `83.0.4103.39` in appium server v1.18.3 and it returns W3C responses as expected. The binary I'm using for the v1.18.3 is the one embeded in the Appium app, while for the Appium 2.0 test I've installed the CLI and I'm passing the chromedriver location [downloaded from googleapis.com](https://chromedriver.storage.googleapis.com/chromedriver-83.0.4103.39/chromedriver_mac64.zip) using the `appium:chromedriverChromeMappingFile` and `appium:chromedriverExecutableDir` as default capabilities.

Here are the logs for the appium 1.18.3 server running the same test which returns all responses as W3C: https://gist.github.com/rillgen-saucelabs/a372329c385327e3ed94b4a4558b9d2f

I also tried passing the `{"appium:chromeOptions": {"w3c": true}}` capability (which I think it is default anyways) but it made no difference. Maybe the appium server v2.0.0 is not passing this to the chrome driver?

**Comment by rillgen-saucelabs** [comment]
I'm using the latest version of the appium java client (`7.6.0`) and doesn't seem to mind the JWP responses even when the detected dialect for the session is W3C, the test runs fine. I was analysing the traffic using different versions of standalone appium servers because I'm implementing W3C support within our systems and I found it strange that older versions of Appium return W3C as I was expecting but not the latest 2.0-beta so I decided to report it.

So, no issues right now but AFAIK the clients would eventually drop support for JWP so I guess this could _potentially_ be an issue in that scenario.

**Comment by KazuCocoa** [comment]
fyi: 2.0 branch has the same code.
https://github.com/appium/appium/blob/2.0/packages/base-driver/lib/protocol/helpers.js#L39

**Comment by KazuCocoa** [comment]
mm, it could be.

the value is detected by https://github.com/appium/appium-base-driver/blob/cfb657b29e810dd53eaa2ae23a1e7d847246b834/lib/jsonwp-proxy/proxy.js#L330

putSession into SESSIONS_CACHE is around https://github.com/appium/appium-base-driver/blob/cfb657b29e810dd53eaa2ae23a1e7d847246b834/lib/protocol/protocol.js#L318 (appium-base-driver repo). It logs current protocol in in https://github.com/appium/appium-base-driver/blob/cfb657b29e810dd53eaa2ae23a1e7d847246b834/lib/protocol/protocol.js#L292 
So, if the `SESSIONS_CACHE` had MJSONWP, then the appium log probably has MJSONWP prefix log.


btw, afaik, https://github.com/appium/appium-base-driver/compare/2.0...2.0-w3c is what I did to drop MJSONWP before.

https://github.com/appium/appium-base-driver/blob/aa47ea9ad19dfcd3655eb26d359d989c38ecaa6c/lib/basedriver/commands/session.js#L27 calls `this.setProtocolW3C();`, so at least a new session request marks `this.protocol` as W3C for now.

**Comment by mykola-mokhnach** [comment]
This should be fixed after the recent android drivers bump
