### ISSUE TITLE
iPad ViewportRect height is < 0 from driver session details

### ISSUE THREAD

**Issue by axk987** [appium/appium#15961]
## The problem

I'm trying to fetch the width and height of the iPad device to use it in my test, while trying to do so I see the height of the device is less than '0'.

<img width="484" alt="Screen Shot 2021-10-13 at 3 58 37 PM" src="https://user-images.githubusercontent.com/84145154/137204157-e8b76ec8-5110-4576-8f4c-81c33cce7d24.png">

This is happening only in case of simulator/emulator, it works fine in real device.

<img width="484" alt="Screen Shot 2021-10-13 at 4 00 13 PM" src="https://user-images.githubusercontent.com/84145154/137204297-1bc3e8e3-c918-4858-949c-8b293262d556.png">

Session details fetched as below - 
Map<String, Object> caps = driver.getSessionDetails();

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS Big Sur
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: iPad device running iOS 14.6/13.3
* Real device or emulator/simulator: emulator/simulator
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Not sure I got your question Christopher

**Comment by mykola-mokhnach** [comment]
The workaround has been published to WDA
