### ISSUE TITLE
Inconsistent behavior of getting text from an element

### ISSUE THREAD

**Issue by nkns165** [appium/appium#15983]
## The problem

I've found there are some inconsistent behavior related to an element including new lines.
- Some locator with new lines succeeds, but others fail.
- Even the same element returns different texts when found by a different locator.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: macOS 10.15 Catalina
* Node.js version (unless using Appium.app|exe): 12.13.1
* Npm or Yarn package manager: npm 6.12.1
* Mobile platform/version under test: iOS 14 / Android 10.0
* Real device or emulator/simulator: iOS simulator / iOS real device / Android emulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Suppose we have a dialog whose message contains a new line like this (This is iOS case)
![line-break-dialog](https://user-images.githubusercontent.com/1135016/137839054-12383cb1-f093-4fe8-b7b0-1a356161a9af.png)

We expect that we can use same text in locators to find the element, but actually the required locator is different between `-ios class chain` and `xpath`.  New lines in xpath is replaced with a space.  But it's not the case on Android.
Besides, even the returned text is different.  The second phenomenon looks especially strange for me.

Is it an intentional result?  We'd like to know what is the expected behavior.

| Platform | Locator strategy | Find element result | Get text result |
|:---|:---|:---|:---|
|iOS|-ios class chain|Succeeds only when the locator contains a new line|Contains a new line|
|iOS|xpath|Succeeds only when the new line is replaced with a space|Doesn't contain a new line|
|Android|xpath|Succeeds only when the locator contains a new line|Contains a new line|

## Link to Appium logs

- [iOS real device] (https://gist.github.com/nkns165/1d69ebf66a85e767833be17087755144)
- [Android emulator] (https://gist.github.com/nkns165/d39009a3d43ae7ba2acf5fedcad7018f)

## Code To Reproduce Issue [ Good To Have ]

I'm sorry it's difficult to provide it immediately because the code is tightly connected with our own system.
If detail investigation using actual code is required, please let me know.

**Comment by mykola-mokhnach** [comment]
I assume this is the default implicit behaviour for the xmllib2 parser that is used in WDA: https://www.w3.org/TR/1998/REC-xml-19980210#AVNormalize as we don't replace any line breaks explicitly in the code. Perhaps this behaviour is configurable, but it was always working like that, so changing it would breaking existing user locators and thus I'm not very convinced to do that.

**Comment by KazuCocoa** [comment]
I understand the situation... I didn't notice the differences...
Ideally, XPath iOS should not trim/replace implicitly like class chain and Android's one.

I think for future consistency, it probably would be nice to change iOS XPath by bumping the major/minor version..
(I also understand such breaking changes' concern)

**Comment by nkns165** [comment]
Thank you for your quick responses!  Then we will develop based on the current behavior.
