### ISSUE TITLE
iOS | Xcode 12.4 | Appium 1.22.0 works with Simulator 14.4 but not with 12.4

### ISSUE THREAD

**Issue by igorgiumellizup** [appium/appium#15994]
## The problem

This is yet another "_Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65_" problem. I know there're tons of issues like that opened out there, but most of them is about running on real devices, and with no solution. My problem is with simulators. My Appium test project is able to install the WDA app on a Simulator with iOS 14.4, but not on iOS 12.4. The problem is similar to [this](https://stackoverflow.com/questions/66113920/getting-xcodebuild-failed-with-code-65-error-for-ios-12-4-by-using-xcode-12-but).

## Environment

* Appium version (or git revision) that exhibits the issue: **java-client 7.6.0**
* Desktop OS/version used to run Appium: **macOS Big Sur 11.6**
* Node.js version (unless using Appium.app|exe): **14.16.0**
* Npm or Yarn package manager: **7.10.0**
* Mobile platform/version under test: **XCode 12.4**
* Real device or emulator/simulator:  **iOS Simulator, iOS 12.4, iPhone 7**
* Appium CLI or Appium.app|exe: **Appium Server 1.22.0**

## Details

```
Capabilities {app: /Users/igordgzup/Library/De..., automationName: XCUITest, deviceName: iPhone 7, noReset: true, platformName: iOS, platformVersion: 12.4, waitForQuiescence: false}
```

## Link to Appium logs

```
[DevCon Factory] Releasing connections for FFAC1B92-9690-40E6-BA55-DEC64AF1F968 device on any port number
[DevCon Factory] Found cached connections to release: ["FFAC1B92-9690-40E6-BA55-DEC64AF1F968:8100"]
[debug] [DevCon Factory] Cached connections count: 0
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [IOSSimulatorLog] Stopping iOS log capture
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1634824045926 (10:47:25 GMT-0300 (Brasilia Standard Time))
[debug] [W3C] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[debug] [W3C] xcodebuild error message:
[debug] [W3C] 
[debug] [W3C]     at quitAndUninstall (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:592:15)
[debug] [W3C]     at /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:627:11
[debug] [W3C]     at wrapped (/usr/local/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:60:13)
[debug] [W3C]     at retry (/usr/local/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:43:13)
[debug] [W3C]     at retryInterval (/usr/local/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:70:10)
[debug] [W3C]     at /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:607:7
[HTTP] <-- POST /wd/hub/session 500 115917 ms - 741
```

**Comment by mykola-mokhnach** [comment]
Have you tried to run the above xcodebuild command manually? what was the output?
