### ISSUE TITLE
launchApp() no more reseting the app on iOS platform.

### ISSUE THREAD

**Issue by ilushkafi** [appium/appium#16026]
## The problem

launchApp() no more reseting the app on iOS platform. The app is not on main screen as it was before. 
## Environment

* Appium -1.22
* Appium - 1.20
* macOS Big Sur
* Node.js 8.0
* Npm 
* iOS 15.02
* Real device 
* Appium.app|exe:
*  XCode 13
## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
