### ISSUE TITLE
WebDriver(client) <----> Appium <----> (browsers on Android) Chrome DevTools Protocol

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#16022]
## The problem

This is an idea to extend Appium's Web context availability.

I noticed when I dug https://github.com/appium/appium/issues/16010#issuecomment-953532457 in, ChromeDevTools Protocol worked even the custom browser was not debuggable.

I mean I was able to inspect browser pages (not only chrome but also other browsers like Brave) via chrome devtools protocol. (Can see available pages via chrome://inspect)

Appium also obtains `webSocketDebuggerUrl` via the below information.

```
[debug] [AndroidDriver] Passing web view details to the Chromedriver constructor: {
[debug] [AndroidDriver]   "info": {
[debug] [AndroidDriver]     "Android-Package": "com.kiwibrowser.browser",
[debug] [AndroidDriver]     "Browser": "Chrome/94.0.4606.56",
[debug] [AndroidDriver]     "Protocol-Version": "1.3",
[debug] [AndroidDriver]     "User-Agent": "Mozilla/5.0 (Linux; Android 10; Nokia 7.2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.56 Mobile Safari/537.36",
[debug] [AndroidDriver]     "V8-Version": "9.4.146.16",
[debug] [AndroidDriver]     "WebKit-Version": "537.36 (@d8ef9bd7c2fb3e21de309b53347a425d73f1a5ce)",
[debug] [AndroidDriver]     "webSocketDebuggerUrl": "ws://127.0.0.1:10900/devtools/browser"
[debug] [AndroidDriver]   },
[debug] [AndroidDriver]   "process": {
[debug] [AndroidDriver]     "name": "com.kiwibrowser.browser",
[debug] [AndroidDriver]     "id": "29548"
[debug] [AndroidDriver]   }
[debug] [AndroidDriver] }
```

So, technically Appium can attach to the webSocketDebuggerUrl and send https://chromedevtools.github.io/devtools-protocol/ to them.
Appium's interface is WebDriver,  so, like `cdp` endpoint https://github.com/appium/appium-base-driver/blob/master/lib/protocol/routes.js#L716-L719, Appium can get a CDP command via `cdp` endpoint by client (or mobile command etc), passes it to the browser via webSocketDebuggerUrl, get the result and respond it to the client.

----

Note that this is mainly for Web developers who develop Web apps for mobile browsers.

**Comment by boris779** [comment]
Hi. So are there any updates or is there a motivation to do this? Actually I'm working on a project where we need to use the dev tools for our automation, and now I'm trying to run it on mobile devices, but dev tools cannot be activated through appium.

Thx for the update

**Comment by KazuCocoa** [comment]
DevTools itself can start via Appium/UIA2 for example. https://github.com/appium/appium-uiautomator2-driver/#mobile-getcontexts shows `webSocketDebuggerUrl`, which is for DevTools Protocol. You may be able to attach to the url via DevTools protocol tools, theoretically.

**Comment by mykola-mokhnach** [comment]
I saw some third-party driver implementations to work with CDP, for example: https://github.com/AppiumTestDistribution/appium-cdp-driver

**Comment by mykola-mokhnach** [comment]
I have also created https://github.com/mykola-mokhnach/appium-devtools-plugin, which could be seen in scope of this feature
