### ISSUE TITLE
AppiumDriver.elementDisplayed() for ShadowDOM elements

### ISSUE THREAD

**Issue by popescuciprian** [appium/appium#16039]
## The problem

Elements found inside a shadow dom using Selenium Java `JavascriptExecutor` don't work anymore with `ExpectedConditions.visibilityOf(element)`, appium saying `An element command failed because the referenced element is no longer attached to the DOM.`

## Environment

* Appium version 1.22
* Last Appium version that did not exhibit the issue (if applicable): 1.21
* Desktop OS/version used to run Appium: macOS 11.6.1
* Node.js version (unless using Appium.app|exe): 16.13.0 LTS
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: real
* Appium CLI or Appium.app|exe: CLI

## Details

We are searching for the root element holding the shadow dom then call `arguments[0].shadowRoot` in order to have access to elements inside it with Selenium Java. 

After this search, we evaluate `ExpectedConditions.visibilityOf(element)` which will always fail after Appium 1.22 update for this kind of elements.

I think it might be related to the new ` :wdc:id` parsing on iOS devices ?

## Link to Appium logs
[Appium 1.22 actual behaviour](https://gist.github.com/popescuciprian/1ae7dcb8cb329b1a440281e5097066c3)
[Appium 1.21 expected behaviour](https://gist.github.com/popescuciprian/53e73be4ef37b8732f09546b1d4abc23)

**Comment by mykola-mokhnach** [comment]
It might be this is happening because elements found by `execute_script` call are not added to the cache automatically unlike the ones retrieved from findElement(s) API. I did some changes to include these as well. Please check if https://github.com/appium/appium-xcuitest-driver/pull/1350 works for you.

**Comment by popescuciprian** [comment]
> It might be this is happening because elements found by `execute_script` call are not added to the cache automatically unlike the ones retrieved from findElement(s) API. I did some changes to include them as well. Please check if [appium/appium-xcuitest-driver#1350](https://github.com/appium/appium-xcuitest-driver/pull/1350) works for you.

[Logs for appium/appium-xcuitest-driver#1350](https://gist.github.com/popescuciprian/1c2b6f5f489af1012496d4d95570d477)
Seems like it's working using this branch.
That was quick 😄

**Comment by mykola-mokhnach** [comment]
The change has been pushed to appium@beta
