### ISSUE TITLE
The ios WebView fails to slide by element

### ISSUE THREAD

**Issue by Tianglangxing-89** [appium/appium#16032]
## The problem
Environment: WebView page of the iOS App

![image](https://user-images.githubusercontent.com/59595228/139813374-8c013389-1ce7-4e3b-99ec-316cb628d867.png)
![image](https://user-images.githubusercontent.com/59595228/139813421-73f9f5b1-5d62-4b46-9136-165b00659cb4.png)
I have a requirement like the one above, find an element and swipe left and right.
Need a sliding element object is "(/ / * [@ class = 'el - slider__button el - tooltip']) [1]"
The methods used are:
        from selenium.webdriver.common.touch_actions import TouchActions
        TouchActions(driver).flick_element(on_element, xoffset, yoffset, speed).perform()
The problem is: when the element is positioned and the slide method is executed, there is no response

Below is Appium's log:
[HTTP] --> POST /wd/hub/session/031dd72c-c2f9-42ab-8965-b63e891ec599/element
[HTTP] {"using":"xpath","value":"(//*[@class='el-slider__button el-tooltip'])[1]"}
[debug] [W3C (031dd72c)] Calling AppiumDriver.findElement() with args: ["xpath","(//*[@class='el-slider__button el-tooltip'])[1]","031dd72c-c2f9-42ab-8965-b63e891ec599"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id, css selector
[debug] [BaseDriver] Waiting up to 10000 ms for condition
[debug] [RemoteDebugger] Executing atom 'find_element' with 'args=["xpath","(//*[@class='el-slider__button el-tooltip'])[1]",null]; frames='
[debug] [RemoteDebugger] Executing 'find_element' atom in default context
[debug] [RemoteDebugger] Sending javascript command: '(function(){return function(){var k=this;functi...'
[debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:13192', page '11', target 'page-29' (id: 212): 'Runtime.evaluate'
[debug] [RemoteDebugger] Received data response from send (id: 212): '"{\"status\":0,\"value\":{\"ELEMENT\":\":wdc:1635823794215\"}}"'
[debug] [RemoteDebugger] Sending to Web Inspector took 14ms
[debug] [RemoteDebugger] Received result for atom 'find_element' execution: {"ELEMENT":":wdc:1635823794215"}
[debug] [W3C (031dd72c)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"5012","ELEMENT":"5012"}
[HTTP] <-- POST /wd/hub/session/031dd72c-c2f9-42ab-8965-b63e891ec599/element 200 18 ms - 73
[HTTP] 
[HTTP] --> POST /wd/hub/session/031dd72c-c2f9-42ab-8965-b63e891ec599/touch/flick
[HTTP] {"element":"5012","xoffset":100,"yoffset":0,"speed":1000}
[debug] [W3C (031dd72c)] Calling AppiumDriver.flick() with args: ["5012",null,null,100,0,1000,"031dd72c-c2f9-42ab-8965-b63e891ec599"]
[debug] [XCUITest] Executing command 'flick'
[debug] [W3C (031dd72c)] Encountered internal error running command: NotYetImplementedError: Method has not yet been implemented
[debug] [W3C (031dd72c)]     at XCUITestDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:328:13)
[debug] [W3C (031dd72c)]     at XCUITestDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:731:24)
[debug] [W3C (031dd72c)]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:563:36)
[debug] [W3C (031dd72c)]     at runMicrotasks (<anonymous>)
[debug] [W3C (031dd72c)]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[debug] [W3C (031dd72c)]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:297:21)
[HTTP] <-- POST /wd/hub/session/031dd72c-c2f9-42ab-8965-b63e891ec599/touch/flick 405 26 ms - 757
[HTTP] 
[HTTP] --> GET /wd/hub/session/031dd72c-c2f9-42ab-8965-b63e891ec599/screenshot
[HTTP] {}
[debug] [W3C (031dd72c)] Calling AppiumDriver.getScreenshot() with args: ["031dd72c-c2f9-42ab-8965-b63e891ec599"]
[debug] [XCUITest] Executing command 'getScreenshot'
[debug] [XCUITest] Taking screenshot with WDA
[debug] [WD Proxy] Matched '/screenshot' to command name 'getScreenshot'
[debug] [WD Proxy] Proxying [GET /screenshot] to [GET http://127.0.0.1:8100/session/1D259CA0-4C02-4F6B-A03D-4AFE46B071AE/screenshot] with no body
[debug] [WD Proxy] Got response with status 200: {"value":"iVBORw0KGgoAAAANSUhEUgAAAu4AAAU2CAYAAADK1zMGAAAAAXNSR0IArs4c6QAA\r\nAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKAC\r\nAAQAAAABAAAC7qADAAQAAAABAAAFNgAAAACw0axrAAAAHGlET1QAAAACAAAAAAAA\r\nApsAAAAoAAACmwAAApsAAhI1rGZBUwAAQABJREFUeAHsnQegVcXx/40l+cVekl/K\r\nPxakCPaCAoKKDQF7YooxiemJqcYUCyp2xN7oD7Cbn9HYY4willQ1Ro0VFDRWEBQF\r\n6TD//ex938u8w30FuA/ui7Nw3rbZ2dk5Z/d8z5w5e1ezCKGB0EBoIDQQGggNhAZC\r\nA6GBtqSBxUlYf9iiLL2KFqYcx+JUwJFpISGdSflTapMSZValMsoXuGNRqudYUpqb\r\nwjuV0Q/UpPMfmlNInAvL0ZL6VLU8YbXlaRRtQgOhgdBAaCA0EBoIDYQGQgOrTAMA\r\nYn9klFwC17444+b8pzK95PdtloB3AXjiUnd6IFDftBNwJ1Z5EbRTV5ZF8kC/jCGA\r\n+zIqLMhDA6GB0EBoIDQQGggNhAZqSwMlizh2b0C2Dm81n5/KOeamY3YiSTQc9SBa\r\ngHwpgJ3pUhPo6mlzlNuW+lmY+lNP9SRlWvipjtixSbllDwHcl11n0SI0EBoIDYQG\r\nQgOhgdBAaKBmNCBXllJcAu4eLpP2wD2Bdw/IUy2AemnQngr1DEDsUTfElKVAsXoj\r\n7YMH7qTLfXiiZUgHcF8GZQVpaCA0EBoIDYQGQgOhgdBALWhgCaLG2o7V2+PqooSq\r\nE3gu1pcbL2HbELR74C6kXo/CxZs4h6UKSuBe1bmvcmbZEgHcl01fQR0aCA2EBkID\r\noYHQQGggNLDKNVBC2CUXGYB7Q4N4Fs8BaJLQLLGMVwD6ovcgPTPyf+qRPcx...
[debug] [W3C (031dd72c)] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAAAu4AAAU2CAYAAADK1zMGAAAAAXNSR0IArs4c6QAA\r\nAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKAC\r\nAAQAAAABAAAC7qADAAQAAAABAAAFNgAAAACw0axrAAAAHGlET1QAAAACAAAAAAAA\r\nApsAAAAoAAACmwAAApsAAhI1rGZBUwAAQABJREFUeAHsnQegVcXx/40l+cVekl/K\r\nPxakCPaCAoKKDQF7YooxiemJqcYUCyp2xN7oD7Cbn9HYY4willQ1Ro0VFDRWEBQF\r\n6TD//ex938u8w30FuA/ui7Nw3rbZ2dk5Z/d8z5w5e1ezCKGB0EBoIDQQGggNhAZC\r\nA6GBtqSBxUlYf9iiLL2KFqYcx+JUwJFpISGdSflTapMSZValMsoXuGNRqudYUpqb\r\nwjuV0Q/UpPMfmlNInAvL0ZL6VLU8YbXlaRRtQgOhgdBAaCA0EBoIDYQGQgOrTAMA\r\nYn9klFwC17444+b8pzK95PdtloB3AXjiUnd6IFDftBNwJ1Z5EbRTV5ZF8kC/jCGA\r\n+zIqLMhDA6GB0EBoIDQQGggNhAZqSwMlizh2b0C2Dm81n5/KOeamY3YiSTQc9SBa\r\ngHwpgJ3pUhPo6mlzlNuW+lmY+lNP9SRlWvipjtixSbllDwHcl11n0SI0EBoIDYQG\r\nQgOhgdBAaKBmNCBXllJcAu4eLpP2wD2Bdw/IUy2AemnQngr1DEDsUTfElKVAsXoj\r\n7YMH7qTLfXiiZUgHcF8GZQVpaCA0EBoIDYQGQgOhgdBALWhgCaLG2o7V2+PqooSq\r\nE3gu1pcbL2HbELR74C6kXo/CxZs4h6UKSuBe1bmvcmbZEgHcl01fQR0aCA2EBkID\r\noYHQQGggNLDKNVBC2CUXGYB7Q4N4Fs8BaJLQLLGMVwD6ovcgPTPyf+qRPcxEl5I0\r\n...
[HTTP] <-- GET /wd/hub/session/031dd72c-c2f9-42ab-8965-b63e891ec599/screenshot 200 141 ms - 430764
[HTTP] 
[HTTP] --> POST /wd/hub/session/031dd72c-c2f9-42ab-8965-b63e891ec599/context
[HTTP] {"name":null}
[debug] [W3C (031dd72c)] Calling AppiumDriver.setContext() with args: [null,"031dd72c-c2f9-42ab-8965-b63e891ec599"]
[debug] [XCUITest] Executing command 'setContext'
[debug] [XCUITest] Attempting to set context to 'NATIVE_APP' from '13192.11'
[debug] [W3C (031dd72c)] Responding to client with driver.setContext() result: null
[HTTP] <-- POST /wd/hub/session/031dd72c-c2f9-42ab-8965-b63e891ec599/context 200 1 ms - 14
[HTTP] 
[HTTP] --> GET /wd/hub/session/031dd72c-c2f9-42ab-8965-b63e891ec599/context
[HTTP] {}
[debug] [W3C (031dd72c)] Calling AppiumDriver.getCurrentContext() with args: ["031dd72c-c2f9-42ab-8965-b63e891ec599"]
[debug] [XCUITest] Executing command 'getCurrentContext'
[debug] [W3C (031dd72c)] Responding to client with driver.getCurrentContext() result: "NATIVE_APP"
[HTTP] <-- GET /wd/hub/session/031dd72c-c2f9-42ab-8965-b63e891ec599/context 200 1 ms - 22
[HTTP] 
[HTTP] --> POST /wd/hub/session/031dd72c-c2f9-42ab-8965-b63e891ec599/element
[HTTP] {"using":"-ios class chain","value":"**/XCUIElementTypeButton[`label == \"btn nav systemclose\"`]"}
[debug] [W3C (031dd72c)] Calling AppiumDriver.findElement() with args: ["-ios class chain","**/XCUIElementTypeButton[`label == \"btn nav systemclose\"`]","031dd72c-c2f9-42ab-8965-b63e891ec599"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id, css selector
[debug] [BaseDriver] Waiting up to 10000 ms for condition
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8100/session/1D259CA0-4C02-4F6B-A03D-4AFE46B071AE/element] with body: {"using":"class chain","value":"**/XCUIElementTypeButton[`label == \"btn nav systemclose\"`]"}
[debug] [WD Proxy] Got response with status 200: {"value":{"ELEMENT":"07010000-0000-0000-8833-000000000000","element-6066-11e4-a52e-4f735466cecf":"07010000-0000-0000-8833-000000000000"},"sessionId":"1D259CA0-4C02-4F6B-A03D-4AFE46B071AE"}
[debug] [W3C (031dd72c)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"07010000-0000-0000-8833-000000000000","ELEMENT":"07010000-0000-0000-8833-000000000000"}
[HTTP] <-- POST /wd/hub/session/031dd72c-c2f9-42ab-8965-b63e891ec599/element 200 2552 ms - 137
[HTTP] 
[HTTP] --> GET /wd/hub/session/031dd72c-c2f9-42ab-8965-b63e891ec599/element/07010000-0000-0000-8833-000000000000/displayed
[HTTP] {}
[W3C (031dd72c)] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [WD Proxy] Matched '/wd/hub/session/031dd72c-c2f9-42ab-8965-b63e891ec599/element/07010000-0000-0000-8833-000000000000/displayed' to command name 'elementDisplayed'
[debug] [WD Proxy] Proxying [GET /wd/hub/session/031dd72c-c2f9-42ab-8965-b63e891ec599/element/07010000-0000-0000-8833-000000000000/displayed] to [GET http://127.0.0.1:8100/session/1D259CA0-4C02-4F6B-A03D-4AFE46B071AE/element/07010000-0000-0000-8833-000000000000/displayed] with no body
[debug] [WD Proxy] Got response with status 200: {"value":true,"sessionId":"1D259CA0-4C02-4F6B-A03D-4AFE46B071AE"}
[WD Proxy] Replacing sessionId 1D259CA0-4C02-4F6B-A03D-4AFE46B071AE with 031dd72c-c2f9-42ab-8965-b63e891ec599
[HTTP] <-- GET /wd/hub/session/031dd72c-c2f9-42ab-8965-b63e891ec599/element/07010000-0000-0000-8833-000000000000/displayed 200 1110 ms - 65
[HTTP] 
[HTTP] --> GET /wd/hub/session/031dd72c-c2f9-42ab-8965-b63e891ec599/element/07010000-0000-0000-8833-000000000000/enabled
[HTTP] {}
[W3C (031dd72c)] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [WD Proxy] Matched '/wd/hub/session/031dd72c-c2f9-42ab-8965-b63e891ec599/element/07010000-0000-0000-8833-000000000000/enabled' to command name 'elementEnabled'
[debug] [WD Proxy] Proxying [GET /wd/hub/session/031dd72c-c2f9-42ab-8965-b63e891ec599/element/07010000-0000-0000-8833-000000000000/enabled] to [GET http://127.0.0.1:8100/session/1D259CA0-4C02-4F6B-A03D-4AFE46B071AE/element/07010000-0000-0000-8833-000000000000/enabled] with no body
[debug] [WD Proxy] Got response with status 200: {"value":true,"sessionId":"1D259CA0-4C02-4F6B-A03D-4AFE46B071AE"}
[WD Proxy] Replacing sessionId 1D259CA0-4C02-4F6B-A03D-4AFE46B071AE with 031dd72c-c2f9-42ab-8965-b63e891ec599
[HTTP] <-- GET /wd/hub/session/031dd72c-c2f9-42ab-8965-b63e891ec599/element/07010000-0000-0000-8833-000000000000/enabled 200 1078 ms - 65
[HTTP] 
[HTTP] --> POST /wd/hub/session/031dd72c-c2f9-42ab-8965-b63e891ec599/element/07010000-0000-0000-8833-000000000000/click
[HTTP] {"id":"07010000-0000-0000-8833-000000000000"}
[W3C (031dd72c)] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [WD Proxy] Matched '/wd/hub/session/031dd72c-c2f9-42ab-8965-b63e891ec599/element/07010000-0000-0000-8833-000000000000/click' to command name 'click'
[debug] [WD Proxy] Proxying [POST /wd/hub/session/031dd72c-c2f9-42ab-8965-b63e891ec599/element/07010000-0000-0000-8833-000000000000/click] to [POST http://127.0.0.1:8100/session/1D259CA0-4C02-4F6B-A03D-4AFE46B071AE/element/07010000-0000-0000-8833-000000000000/click] with body: {"id":"07010000-0000-0000-8833-000000000000"}
[debug] [RemoteDebugger] Web Inspector garbage collected
[debug] [WD Proxy] Got response with status 200: {"value":null,"sessionId":"1D259CA0-4C02-4F6B-A03D-4AFE46B071AE"}
[WD Proxy] Replacing sessionId 1D259CA0-4C02-4F6B-A03D-4AFE46B071AE with 031dd72c-c2f9-42ab-8965-b63e891ec599
[HTTP] <-- POST /wd/hub/session/031dd72c-c2f9-42ab-8965-b63e891ec599/element/07010000-0000-0000-8833-000000000000/click 200 2395 ms - 65
[HTTP] 
[HTTP] --> DELETE /wd/hub/session/031dd72c-c2f9-42ab-8965-b63e891ec599
[HTTP] {}

Below is my desired capabilities
from appium.webdriver import Remote
caps = {
"platformName": "iOS",
"automationName": "XCUITest",
"platformVersion": "13.3",
"deviceName": "iPhone my8",
"bundleId": "com.sinosun.bizmate.newace",
"udid": "b1003e9e562c147324245fdfde14327f170b2444",
"xcodeOrgId": "XXXXXXXXXX",
"xcodeSigningId": "iPhone Developer",
"preventWDAAttachments": False,
# "showIOSLog": True,
"noReset": False
}
## Environment

Appium version (or git revision) that exhibits the issue: 1.21.0
Last Appium version that did not exhibit the issue (if applicable):
Desktop OS/version used to run Appium: macOS Big Sur 11.3.1
Node.js version (unless using Appium.app|exe): 16.6.0
Npm or Yarn package manager: 7.19.1
Mobile platform/version under test: iOS 13.3
Real device or emulator/simulator: Real device
Appium CLI or Appium.app|exe: Appium CLI and Appium.app|exe

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
The error is expected. Actions may only be executed in native context.

**Comment by Tianglangxing-89** [comment]
I'm sorry, what do you mean?

**Comment by Tianglangxing-89** [comment]
> The error is expected. Actions may only be executed in native context.

I'm sorry, what do you mean

**Comment by mykola-mokhnach** [comment]
> [HTTP] --> POST /wd/hub/session/031dd72c-c2f9-42ab-8965-b63e891ec599/touch/flick
> [HTTP] {"element":"5012","xoffset":100,"yoffset":0,"speed":1000}
> [debug] [W3C (031dd72c)] Calling AppiumDriver.flick() with args: ["5012",null,null,100,0,1000,"031dd72c-c2f9-42ab-8965-b63e891ec599"]
> [debug] [XCUITest] Executing command 'flick'
> [debug] [W3C (031dd72c)] Encountered internal error running command: NotYetImplementedError: Method has not yet been implemented
> [debug] [W3C (031dd72c)] at XCUITestDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:328:13)
> [debug] [W3C (031dd72c)] at XCUITestDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:731:24)
> [debug] [W3C (031dd72c)] at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:563:36)
> [debug] [W3C (031dd72c)] at runMicrotasks ()
> [debug] [W3C (031dd72c)] at processTicksAndRejections (node:internal/process/task_queues:96:5)
> [debug] [W3C (031dd72c)] at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:297:21)
> [HTTP] <-- POST /wd/hub/session/031dd72c-c2f9-42ab-8965-b63e891ec599/touch/flick 405 26 ms - 757
> 

I mean the error you get in the log is expected. this does not work and is not supposed to.

**Comment by jlipps** [comment]
@mykola-mokhnach which ios webview atom would be a good alternative?

**Comment by jlipps** [comment]
i checked with the selenium team, doesn't seem like there are any atoms for actions

**Comment by jlipps** [comment]
this is where safaridriver for iOS would come in handy!
