### ISSUE TITLE
Cannot find webview element in the foreground nor its corresponding context 

### ISSUE THREAD

**Issue by beto00** [appium/appium#16031]
## The problem

We have one application with a tool drawer (similar to an application drawer) that is being opened as a webview element in the foreground (on top of the main application).
I have been unable to find said webview in order to switch to its context and interact with the items inside it.
There is one additional webview in the main app that we can see and interact with, so we know our configuration for:
WebView.setWebContentsDebuggingEnabled(true); 
is working properly 
This behavior only happens on real devices, not on emulated devices.
We have seen this behavior in the past with different elements that are being drawn on top of the main application, such as message boxes, and even this same tool drawer aback when it was a mobile element rather than a webview.
We have also confirmed that the issue happens only on saucelabs real devices, we have no issues whatsoever when working on emulated devices both locally and on saucelabs, so we can discard saucelabs issues.

## Environment

* Appium version 1.21 and 1.22:
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Mac OS 11
* Node.js version (unless using Appium.app|exe): N/A
* Npm or Yarn package manager: npm:7.23 / yarn:1.22.17
* Mobile platform/version under test: Android 11
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium.app

## Link to Appium logs

Since I cannot see the webview context I cannot switch to it and so there are no logs being generated for this issue.
Switching to the other available webview context does not present any issues.

**Comment by KazuCocoa** [comment]
Is the WebView accessible via Safari's WebInspector?

**Comment by KazuCocoa** [comment]
Also, could you share the full appium log with `appium:safariLogAllCommunication` `true`?

**Comment by beto00** [comment]
@KazuCocoa sorry if I. miss-labeled this issue, this is happening on an android device, I am not using Safari at all.

**Comment by KazuCocoa** [comment]
Oh, i see.
Then, could you share the full log with `appium:enableWebviewDetailsCollection` `true`?

Android follows the same method in both emulators and real devices. So possibly it is device or environment specific.

If the log had no weird point, I would contact the sauce's support team.

**Comment by beto00** [comment]
@KazuCocoa 
Thanks for following up, your time is really appreciated.

This are the logs for an emulated device:
https://gist.github.com/beto00/245192bb0f45313eb8180bc9224f1815
You can see on line 3476, this is where the element I am looking for can be found.

This are the logs for a real device (physical one I have, it has the same behavior as a saucelabs real device)
https://gist.github.com/beto00/52908ad419f481d1c3d499196ed1211d
You can see on line 967, this is where the element I am looking for cannot be found.

Please let me know your thoughts.
Thanks.

**Comment by KazuCocoa** [comment]
Hm, it seems chromedriver itself returned the below response.

```
[debug] [35m[WD Proxy][39m Proxying [POST /wd/hub/session/1758f5ed-fcfa-4cbb-ade7-30e0d234c8e8/element] to [POST http://127.0.0.1:8001/wd/hub/session/41988eb5a163ed29dae309db3af531c2/element] with body: {"using":"xpath","value":"//div[@id=\"TR0016\"]"}
[info] [35m[WD Proxy][39m Got response with status 404: {"value":{"error":"no such element","message":"no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//div[@id=\"TR0016\"]\"}\n  (Session info: chrome=95.0.4638.50)","stacktrace":"0   chromedriver_mac64_v95.0.4638.54    0x0000000104937c99 __gxx_personality_v0 + 579209\n1   chromedriver_mac64_v95.0.4638.54    0x00000001048c35f3 __gxx_personality_v0 + 102371\n2   chromedriver_mac64_v95.0.4638.54    0x0000000104489288 chromedriver_mac64_v95.0.4638.54 + 172680\n3   chromedriver_mac64_v95.0.4638.54    0x00000001044be25c chromedriver_mac64_v95.0.4638.54 + 389724\n4   chromedriver_mac64_v95.0.4638.54    0x00000001044f0104 chromedriver_mac64_v95.0.4638.54 + 594180\n5   chromedriver_mac64_v95.0.4638.54    0x00000001044db3cd chromedriver_mac64_v95.0.4638.54 + 508877\n6   chromedriver_mac64_v95.0.4638.54    0x00000001044edeab chromedriver_mac64_v95.0.4638.54 + 585387\n7   chromedriver_mac64_v95.0.4638.54    0x00000001044db693 chromedriver_mac64_v95.0.4638.54 + 509587\n8   chromedriver_mac64_...
```

Can you inspect with the intended WebView via `chrome://inspect` via chrome?


I also wondered if your two webviews were by chrome custom tab.

Then, once you switch to a webview (chrome custom tab), you should call `window_handlers` to switch with the page since the custom tabs are one chrome process.

e.g.
```
driver.set_context('WEBVIEW_XXXX')
driver.window_handles
driver.switch_to.window('a window_handle name')
--

I guess the diff is how chromedriver work on emulators/real devices.

**Comment by beto00** [comment]
@KazuCocoa thanks a lot for your help, I've been scratching my head with this one for quite a while.
I was able to inspect the webview with chrome and finally switching window handle did the trick for me to be able to see the webview from my automated test.
