### ISSUE TITLE
How does the WebView environment in iOS slide an element

### ISSUE THREAD

**Issue by Tianglangxing-89** [appium/appium#16033]
## The problem
![111111](https://user-images.githubusercontent.com/59595228/140000648-952cb5f9-150c-476d-8203-09bba4d7d872.png)
![222222](https://user-images.githubusercontent.com/59595228/140000678-7f78b9b6-731a-4398-b58f-e344ea8dbcbb.png)

Environment: WebView page of the iOS App
I came across an automated test scenario where, after locating an element, I swiped to the left.
I couldn't use the Touchaction, Touchactions, and swipe methods. How to realize element sliding in the WebView environment of App in iOS?

## Environment

Appium version (or git revision) that exhibits the issue: 1.21.0
Last Appium version that did not exhibit the issue (if applicable):
Desktop OS/version used to run Appium: macOS Big Sur 11.3.1
Node.js version (unless using Appium.app|exe): 16.6.0
Npm or Yarn package manager: 7.19.1
Mobile platform/version under test: iOS 13.3
Real device or emulator/simulator: Real device
Appium CLI or Appium.app|exe: Appium CLI and Appium.app|exe

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by KazuCocoa** [comment]
> How to realize element sliding in the WebView environment of App in iOS?

What the page source in the webview context?

**Comment by mykola-mokhnach** [comment]
There are at least two options:
- Via custom javascript snippet that would synthesize necessary events for the given element.
- Via [W3C Actions or mobile gestures](https://www.youtube.com/watch?v=oAJ7jwMNFVU). Although, since these would only only work in native context, it is necessary to switch away from the webview first and then properly calculate native coordinates of the corresponding element. Usually coordinates of elements in a webview and native ones don't match. After native coordinates are calculates they could be passed as gesture parameters.

Please use Appium forum to ask questions

**Comment by Tianglangxing-89** [comment]
> > How to realize element sliding in the WebView environment of App in iOS?
> 
> What the page source in the webview context?

Hello, page source is HTML

**Comment by Tianglangxing-89** [comment]
> There are at least two options:
> 
> * Via custom javascript snippet that would synthesize necessary events for the given element.
> * Via [W3C Actions or mobile gestures](https://www.youtube.com/watch?v=oAJ7jwMNFVU). Although, since these would only only work in native context, it is necessary to switch away from the webview first and then properly calculate native coordinates of the corresponding element. Usually coordinates of elements in a webview and native ones don't match. After native coordinates are calculates they could be passed as gesture parameters.
> 
> Please use Appium forum to ask questions

The W3C actions or mobile gestures you mentioned have been tried, there is no way available on iOS.
In addition, which address is the "Appium forum question" you mentioned? Do you have a specific URL?

**Comment by KazuCocoa** [comment]
https://discuss.appium.io/ is > Appium forum question

**Comment by Tianglangxing-89** [comment]
> https://discuss.appium.io/ is > Appium forum question

Thank you!
