### ISSUE TITLE
Page source command returns invalid output when < character appears on page

### ISSUE THREAD

**Issue by a-bastrykina** [appium/appium#16035]
## The problem

I'm trying to parse `driver.page_source` command output and expect it to be a valid XML in native applications contexts. This worked in the older versions of Appium server, but starting from 1.21 when a `<` symbol appear on page, the command responds with invalid XML output - a `<` symbol does not get escaped with `&lt;` as it should.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21
* Last Appium version that did not exhibit the issue (if applicable): 1.20
* Desktop OS/version used to run Appium: 1.21
* Node.js version (unless using Appium.app|exe): -
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS 14.4, XCUITest driver
* Real device or emulator/simulator: iPhone 12 simulator
* Appium CLI or Appium.app|exe: Appium.app

## Details

My steps to reproduce are:
1. Open iOS simulator
2. Open Messages application
3. In the text field, type `Test <>"'&`
4. Start session with the device using Appium client python library 
5. Query `driver.page_source()` command and try to parse its output with XML parser

Actual result: Page source contains forbidden `<` symbol inside element attribute so it cannot be parsed. Please note that  `&` and `"` get escaped as expected:
```
value="Test <>&quot;'&amp;"
```

You can check out full page source [here](https://gist.github.com/a-bastrykina/98ad8112a2ae808d95b8b4d971b9f980).

Here is my sample script: [test_page_source.py](https://gist.github.com/a-bastrykina/3c0325b950e61652ecb998a83b58d62e)

Screenshot of application state:
<img width="371" alt="Screenshot 2021-11-03 at 14 14 22" src="https://user-images.githubusercontent.com/26992487/140024925-515b1dcc-ca8d-4af0-b156-d33c6ae3d462.png">

## Link to Appium logs

https://gist.github.com/a-bastrykina/4d0e7eac28bc2e4814a0134082036e23

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by KazuCocoa** [comment]
I quickly checked `Test <>"'&` on a real device.

```
<XCUIElementTypeTextField type="XCUIElementTypeTextField" value="Teat<>&quot;'&amp;" name="messageBodyField" label="Message" enabled="true" visible="true" accessible="true" x="131" y="273" width="139" height="38" index="0"/>
```

Alternatively, you can set `appium:useJSONSource` as true in capabilities for now. Then, the part will be parsed correctly as the below:

```
<XCUIElementTypeTextField type="XCUIElementTypeTextField" enabled="true" visible="true" x="131" y="273" width="139" height="38" name="messageBodyField" label="Message" value="Teat&lt;&gt;&quot;&apos;&amp;">
</XCUIElementTypeTextField>
```

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/WebDriverAgent/pull/541 should do the job

**Comment by mykola-mokhnach** [comment]
After further investigation it seems like the problematic code is located in the xmldom module that we use to put the returned source under AppiumAUT XML root: https://github.com/appium/appium-xcuitest-driver/blob/6bc8983b0975dd0e6b44f21dbd52f444c0b3df33/lib/commands/source.js#L24

Reported it as a bug to their issue tracker: https://github.com/xmldom/xmldom/issues/339

**Comment by mykola-mokhnach** [comment]
@a-bastrykina I have published the updated dependency version to appium@beta. Please install it and verify if your issue is solved.

**Comment by KazuCocoa** [comment]
I quickly checked that `<` was escaped as `Teat&lt;>&quot;` (as the xmldom's comment)

**Comment by a-bastrykina** [comment]
Thanks for the quick response @mykola-mokhnach @KazuCocoa! Please point me out how can I install appium@beta. Is there any link to download build artifacts (I'm on MacOS so I use .app package)?

**Comment by mykola-mokhnach** [comment]
the only way to get it is via NPM: `npm i -g appium@beta`

**Comment by a-bastrykina** [comment]
Thanks. I checked with appium@beta and confirm that the issue is fixed.
