### ISSUE TITLE
Error 'cv[detectorName] is not a constructor' displays when select any Feature Matching Detector name

### ISSUE THREAD

**Issue by antuking** [appium/appium#16049]
## The problem

I want to use FeautresMatchingResult with each of Feature Detector Matching name which defined as Enum. But I'm facing the error 'cv[detectorName] is not a constructor when performing the snippet.

## Environment

* Appium version: **1.21.0**
* Desktop OS/version used to run Appium: **MacOS Catalina 10.15.7**
* Node.js version: **v14.16.1**
* Npm or Yarn package manager: **7.19.1**
* opencv4nodejs: **5.6.0**
* opencv: **4.5.3**
* Java-client version: 7.0.0

## Link to Appium logs

https://gist.github.com/antuking/8dbcf5a01bbe27a2d3e76a3091c22612

## Code To Reproduce Issue
```
public enum FeatureDetector {
    AKAZE, AGAST, BRISK, FAST, GFTT, KAZE, MSER, SIFT, ORB
}
```

```
FeaturesMatchingResult result = driver.matchImagesFeatures(bytesSrc,
                                     bytesTemp,
                                     new FeaturesMatchingOptions()
                                             .withDetectorName(FeatureDetector.AKAZE)
                                             .withGoodMatchesFactor(40)
                                             .withMatchFunc(MatchingFunction.BRUTE_FORCE_HAMMING)
                                             .withEnabledVisualization());
```

**Comment by mykola-mokhnach** [comment]
Could you please try the most recent server version and provide the log from it if that still fails?

**Comment by antuking** [comment]
Hello @mykola-mokhnach , could you please refer the failed log at https://gist.github.com/antuking/8dbcf5a01bbe27a2d3e76a3091c22612. I upgrade the appium version to 1.22.0. Help me take a look this one. Thanks in advance

**Comment by antuking** [comment]
How to verify that in my local env @mykola-mokhnach? Could you please give me some double-check script for this one?

**Comment by antuking** [comment]
@mykola-mokhnach Could you please give me more details? I guess the manual opencv4nodejs build seems that having problem. But need more information to make sure this stuff.

**Comment by mykola-mokhnach** [comment]
Unfortunately opencv4nodejs seems to be abandoned for quite a while and I don't think I could help much with that. Maybe there are some C++/Node experts around who could help you to make it working. Appium is also just a client to it

**Comment by jlipps** [comment]
My guess is that you've built a version of OpenCV which has a different API to the one Appium uses. I know that at some point I had to start building older versions of OpenCV (try OpenCV 3) to keep things working with Appium.

**Comment by antuking** [comment]
I couldn't install opencv4nodejs both automation and manually (node-gyp issue). That's a reason why I used [opencv4nodejs-prebuilt](https://www.npmjs.com/package/opencv4nodejs-prebuilt) instead of opencv4nodejs legacy to build *.node and *.dylib file.
@jlipps Unluckily, I face the same issue with OpenCV 3 :(

**Comment by jlipps** [comment]
hmm it's possible the prebuilt version has a different interface that's not compatible somehow.

**Comment by antuking** [comment]
Hmm, I got it. Thanks for your time @jlipps @mykola-mokhnach.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
