### ISSUE TITLE
General question about Appium...

### ISSUE THREAD

**Issue by DevStreamLine** [appium/appium#16043]
Hello,

We have a Mobile App we use and I would like to automate the usage of the app and I was wondering if appium is a tool we can use.  I have briefly read some of the docs and it seems like it would do it but I was wondering if would meet our requirements:

1) Automate a Mobile App Installed on one or many Android devices
2) Preferably perform Automation Over WiFi
3) Pass parameters to the Automation Script
4) No code changes to the Mobile App

To give more detail, we use an app for data collection. The automation would need to launch the app if it is not running, perform a login using passed parameters, as user may be different each time, navigate to the screens for the data collection, and save the data to a file.

Thank you for your help.

**Comment by mykola-mokhnach** [comment]
Kindly use Appium forum to ask questions. This is the place for issues.
