### ISSUE TITLE
deiver.close_app() This interface does not work in IOS  Appium Desktop 1.22.0，

### ISSUE THREAD

**Issue by duanhonggo** [appium/appium#16051]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
Closing as not an issue, since `closeApp` was intentionally removed. Instead, simply delete the session (`driver.quit()`).

**Comment by MummanaSubramanya** [comment]
@jlipps I faced the same issue https://github.com/appium/appium/issues/16140 and driver.quit() neither works.
