### ISSUE TITLE
close an iOS app and clear data on a real device using Appium

### ISSUE THREAD

**Issue by Lalith-1308** [appium/appium#16054]
The Problem

When I try to run multiple test cases together and the first test case gets passed or if there is is any failure in between the app gets stuck in the same screen and it just seems to close the app and launch it again, without actually clearing the data and when the next test case starts executing it fails due to this issue. I have tried noReset, fullReset, closeApp, quit nothing worked. Due to which all the following test case fails

Environment

* Appium version (or git revision) that exhibits the issue: v1.21.0
* Desktop OS/version used to run Appium: Mac OS Big Sur 11.6.1 
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium.app

**Comment by mykola-mokhnach** [comment]
Unfortunately Apple does not provide any APIs to clear app data except of deleting the app and installing it again.

Closed as not an issue.

**Comment by Lalith-1308** [comment]
So, there is any alternative way to run all the test cases together without deleting the app?

**Comment by mykola-mokhnach** [comment]
Maybe you could ask developers to add some backdoor. Otherwise none I know of.
