### ISSUE TITLE
xcodebuild hang issue while running Webdriveragent 

### ISSUE THREAD

**Issue by vinod-lt** [appium/appium#16061]
Problem:

Xcodebuild command for webdriveragent is hanged for all the iOS devices connected to the Mac.

Environment:
* Appium 1.21.0
* MacOS: 11.5
* Xcode 12.5
* iOS 14.x

Details
After running appium execution successfully for some iterations, xcodebuild seems to hang with no output from command line. Rebooting iOS devices also not helped to recover xcodebuild.
Is it possible to recover xcode without rebooting macOS?

**Comment by mykola-mokhnach** [comment]
Please provide logs.

Does xcodebuild also freeze being executed manually? If yes then I don't think there is much to do from Appium side.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
