### ISSUE TITLE
better errors

### ISSUE THREAD

**Issue by boneskull** [appium/appium#16073]
Appium can throw exceptions.  Lots of exceptions.  Naturally, exceptions are presented to the end-user.  Appium should carefully consider how it throws exceptions, because those exceptions _may not be actionable._. 

Regardless, Appium should do its best to help or _help the user get help_ in both of these cases.  To that end, I'd like to propose:

1. Errors which a user can receive during normal usage of Appium (e.g., an incorrectly-typed CLI argument, or an unknown driver name):
    - _Must not_ display a stack trace!!
    -  _Should_ display a concise, human-readable message
    -  _Should_ display any context-specific information (e.g., config file line numbers, usage for a specific argument, etc.)
    - _Should_ provide a URL to documentation which explains the error in more detail
    - _May_ use color and/or emojis to better convey information
1. Errors which a _developer_ can receive (e.g., you called `someFunc()` incorrectly, or your driver implementation is hosed, uncaught exception, etc.):
    - _Must_ display a stack trace
    - _Should_ display a excruciatingly thorough message
1. Further, _all_ errors _must_ display a unique, easily-searchable error code, regardless of language

Some rationale:

- Actionable errors do not need stack traces; users do not care about them.  We should not show stack traces unless we think it will help whoever is seeing it.  Stack traces are an implementation detail, and an end-user shouldn't really care if Appium is written in JavaScript or Malbolge.
- External documentation on specific errors and how to resolve them will be helpful, especially to beginners
- Using unique codes to identify each error will help the user find more information via the forums, Google, etc.
- Emojis typically aren't my taste, but they make the CLI seem friendly and "modern"
- Ultimately, _we should see less issues in the tracker around common errors_

(To be clear, I'm talking about "fatal" errors, which will cause the Appium process to exit. Anything else falls into the realm of "logs", which is another can of worms.)

* * *

Implementation-wise, it's probably Good to have named error subclasses for each type of error.  These classes should be exported to any consumers/well-typed, etc.  In other words, the use-cases for `throw new Error()` are few, if any.  If we do end up using emoji, we should not display them where they don't work. Likewise, assume "no color" if not run in a tty--but have an override--etc.

I realize the "link to docs" part definitely needs its own issue, but I'd like to get there someday.

Thoughts?

**Comment by mykola-mokhnach** [comment]
We do throw specific error where it is possible. There errors are defined by webdriver spec itself and could be found in https://github.com/appium/appium-base-driver/blob/master/lib/protocol/errors.js

Also, I remember there was an issue in nodejs while checking error classes using `instanceof` operator. It did not work for classes exported from other modules. That is why there is `isErrorType` helper in the base driver. Not sure what's the situation in the recent node releases. Also a special `es6-error` module was used there to make error classes inheritance possible.

Regarding more specific error and documentation. Our documentation in general far from a good shape. Documenting errors is something I would not try to do in the first priority. Also, it's often not only about documenting it, but also, more importantly, about maintaining already existing stuff. And this is where we suffer the most taking into account how much development resources we have.

What I was thinking of: it might be helpful to add error handing best practices into our developer/code style documentation.

**Comment by boneskull** [comment]
IMO error messages are _more_ important than documentation.  You get the errors when you run Appium; you have to go elsewhere for documentation.  A good error will keep you from having to look in the docs

**Comment by mykola-mokhnach** [comment]
This issue is too broad thus impossible to have a clear resolution criteria.
