### ISSUE TITLE
Unable to test Iphone - WDIO- Saucelabs

### ISSUE THREAD

**Issue by opensourcesensor** [appium/appium#16078]
## The problem

In appium Version 1.22.0 there could no comments be done in the Safari browser on mobile device.
You can see https://github.com/webdriverio/webdriverio/issues/7690.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.0
* Last Appium version that did not exhibit the issue (if applicable): 1.22.0
* Desktop OS/version used to run Appium: 
* Node.js version (unless using Appium.app|exe): latest
* Npm or Yarn package manager: npm latest version
* Real device or emulator/simulator: iPhone X Simulator, iOS

## Details

Cannot click any objects on Saucelabs with WDIO, using Appium.

## Link to Appium logs

WebDriver Error: An element command failed because the referenced element is no longer attached to the DOM.

Is there any issue known?
Thank you!
BR
Fabian Schmider

**Comment by mykola-mokhnach** [comment]
Please provide the full server log

**Comment by jlipps** [comment]
stale reference errors usually mean you just need to find your element again. and is this an issue which only repros on sauce labs and not appium in general? in which case you should reach out to their support instead.

**Comment by opensourcesensor** [comment]
Hi @jlipps ,
okay, then I will open a saucelabs ticket!

Thanks,
BR
