### ISSUE TITLE
Using `driver.fingerPrint(Int)` does not work when using `Espresso` automator

### ISSUE THREAD

**Issue by Baterka** [appium/appium#16085]
## The problem

Using `driver.fingerPrint(Int)` does not work when using `Espresso` automator (from latest Java Client)

## Environment

* Appium version (or git revision) that exhibits the issue: v1.22.0
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): Using Appium Server Desktop
* Npm or Yarn package manager: -
* Mobile platform/version under test: Android 11
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Using Appium Server Desktop

## Details

- Not sure if its client problem, but it seems like it is not if syntax not changed recently. Route does not exists when calling it: `No such route:`
- It works fine when using UIAutomator2

## Link to Appium logs

```
[HTTP] --> POST /wd/hub/session/e73541c6-a634-41a7-afeb-12663cc8f332/appium/device/finger_print
[HTTP] {"fingerprintId":1}
[W3C (e73541c6)] Driver proxy active, passing request on via HTTP proxy
[debug] [WD Proxy] Matched '/wd/hub/session/e73541c6-a634-41a7-afeb-12663cc8f332/appium/device/finger_print' to command name 'fingerprint'
[debug] [WD Proxy] Proxying [POST /wd/hub/session/e73541c6-a634-41a7-afeb-12663cc8f332/appium/device/finger_print] to [POST http://localhost:8305/session/807edd33-2e23-4144-8e66-b15f86bdd5d7/appium/device/finger_print] with body: {"fingerprintId":1}
[WD Proxy] Got response with status 500: {"id":"271879dd-58e5-4c47-9915-97aa1c5df34e","sessionId":null,"value":{"error":"unknown error","message":"No such route: /session/807edd33-2e23-4144-8e66-b15f86bdd5d7/appium/device/finger_print","stacktrace":"io.appium.espressoserver.lib.handlers.exceptions.AppiumException: No such route: /session/807edd33-2e23-4144-8e66-b15f86bdd5d7/appium/device/finger_print\n\tat io.appium.espressoserver.lib.http.Router.route(Router.kt:188)\n\tat io.appium.espressoserver.lib.http.Server.serve(Server.kt:51)\n\tat fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)\n\tat fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)\n\tat java.lang.Thread.run(Thread.java:923)\n"}}
[debug] [W3C] Matched W3C error code 'unknown error' to UnknownError
[HTTP] <-- POST /wd/hub/session/e73541c6-a634-41a7-afeb-12663cc8f332/appium/device/finger_print 500 15 ms - 707
```

## Code To Reproduce Issue [ Good To Have ]

Just call `driver.fingerPrint(Int)` when biometry popup is visible on Android device while using `Espresso` automation name.

**Comment by mykola-mokhnach** [comment]
I've pushed the patch to appium@beta
