### ISSUE TITLE
Appium Inspector never loads for Iphone

### ISSUE THREAD

**Issue by wrathmelior** [appium/appium#16097]
Appium inspector never loads for Iphone. The application is loaded on the device itself, however the inspector remains on 'Gathering initial app source...' with a spinning loading animation indefinitely. Rebooting the phones and computer does not resolve the issue. Nor does disconnecting and reconnecting the devices. 

Screenshot: https://monosnap.com/file/iBJv68m24aAoKrhkU0Jlptc1LZYOTn

## Environment

* Appium version (or git revision) that exhibits the issue:  1.21.0
* Desktop OS/version used to run Appium: macOS Big Sur
* Node.js version (unless using Appium.app|exe):  1.21.0
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: Iphone XS (sw 15), Iphone 12 pro (sw 14.2)
* Real device or emulator/simulator: Real Devices
* Appium CLI or Appium.app|exe: desktop app

## Appium logs
https://gist.github.com/wrathmelior/d79a0964cf3f3441eaf17a3eeac6b891

**Comment by mykola-mokhnach** [comment]
appium 1.21 does not support iOS 15, so the error is expected

**Comment by wrathmelior** [comment]
Which Appium version does support iOS 15?

**Comment by KazuCocoa** [comment]
1.22.0 (latest stable one)

**Comment by wrathmelior** [comment]
When I use 
npm install appium -g 
to update appium I still see 1.21. Is there another way to update to the most recent version?
