### ISSUE TITLE
when run appium 2.0 for UIAutomator2 installation, "--chromedriver-skip-install" is not working

### ISSUE THREAD

**Issue by JesseCodeBones** [appium/appium#16094]
## The problem

I tried to install uiautomator2 driver with command:
`node . driver install uiautomator2 --chromedriver-skip-install  --appium-home="C:\temp"`

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 2.0
* Last Appium version that did not exhibit the issue (if applicable): 1.20
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): 16
* Npm or Yarn package manager: npm
* Mobile platform/version under test: None
* Real device or emulator/simulator: None
* Appium CLI or Appium.app|exe: `node . driver install uiautomator2 --chromedriver-skip-install  --appium-home="C:\temp"`

## Link to Appium logs

C:\Users\cheruixi\IdeaProjects\appium\packages\appium>node . driver install uiautomator2 --chromedriver-skip-install  --appium-home="C:\temp"
usage: appium [-h] [-v] {server,driver,plugin} ...
appium: error: unrecognized arguments: --chromedriver-skip-install

## Code To Reproduce Issue [ Good To Have ]

`node . driver install uiautomator2 --chromedriver-skip-install  --appium-home="C:\temp"` with Appium 2.0

**Comment by StephanB75** [comment]
On Mac it works with a enviroment variable

export APPIUM_SKIP_CHROMEDRIVER_INSTALL=true

I think it should also work on PC with an enviroment variable

**Comment by JesseCodeBones** [comment]
@StephanB75 
yes, change environment variable can fix the issue, but that to say, the parameter "--chromedriver-skip-install" not working any more?

**Comment by StephanB75** [comment]
currentlich not. I don't know if there are plans to migrate this to the new driver installation process

**Comment by KazuCocoa** [comment]
Afaik, not for now.
We're still preparing the migration guide in https://github.com/appium/appium/blob/2.0/docs/en/advanced-concepts/migrating-to-appium-2.0.md , and probably address it for now.

**Comment by jlipps** [comment]
> yes, change environment variable can fix the issue, but that to say, the parameter "--chromedriver-skip-install" not working any more?

This flag will probably not exist in Appium 2.0. The reason is that it gets turned into an NPM install flag, but when using the `appium driver install` interface there is no way to send NPM install flags in. Given that another solution exists (the env var solution), we'll probably just require the use of that solution moving forward.
