### ISSUE TITLE
Android Logcat is not getting captured and the "getLogTypes" request is failing

### ISSUE THREAD

**Issue by hammzj** [appium/appium#16106]
## The problem
Whenever I run an emulated Android device using Appium, the logcat file used to be created in my `./log` directory. Just recently, those files are not being created per session, and I am not able to see log types either using the method that issues the request for device log types.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2 (using package "@wdio/appium-service@^6.12.1")
* Last Appium version that did not exhibit the issue (if applicable): 1.18.x
* Desktop OS/version used to run Appium: macOS Big Sur 11.6.1
* Node.js version (unless using Appium.app|exe): 12.20.1
* Npm or Yarn package manager: Yarn 1.22.10
* Mobile platform/version under test: Android OS 11.0 (API 30)
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Appium CLI
Edit: not sure if important, but I also have Android tools installed with Android Studio Arctic Fox 2020.3.1 Patch 3.

_Also, I am using WebDriverIO version 6.12.1 to launch Appium, but it also fails with WebDriverIO v7._

## Details
Android logcat files are not being created at the start of the session. My device capabilities are below:
```
    {
        'appium:locale': 'US',
        'appium:language': 'en',
        'appium:deviceName': "pixel_3a",
        'appium:avd': "Pixel_3a_API_30",
        'appium:platformVersion': "11.0", //API 30
        'appium:app': 'path/to/my-app.apk',
        'appium:printPageSourceOnFindFailure': true,
        excludeDriverLogs: ['bugreport', 'performance'],
        platformName: 'Android',
        maxInstances: 1,
        'appium:orientation': 'PORTRAIT',
        'appium:automationName': 'UiAutomator2',
        'appium:noReset': false,
        'appium:fullReset': true,
        'appium:allowTestPackages': true,
        'appium:newCommandTimeout': 240,
        'goog:chromeOptions': {
            'args': ['--disable-fre', '--no-first-run', '--no-default-browser-check']
        }
    };
```

As well, the endpoints for retrieving both device log types and device logs fail:
* `GET /session/:session_id/log/types`
* `POST /session/:session_id/log`

## Link to Appium logs
```
2021-11-16T15:31:29.839Z INFO webdriver: COMMAND getLogTypes()
2021-11-16T15:31:29.839Z INFO webdriver: [GET] http://localhost:4723/wd/hub/session/b2d7848b-dba4-44fa-a603-809f7c11dc79/se/log/types
2021-11-16T15:31:29.846Z WARN webdriver: Request failed with status 404 due to The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource
```

## Code To Reproduce Issue [ Good To Have ]

I am using WebDriverIO with a Cucumber framework configuration.

Firstly, launch WebDriverIO with an Android device, and then running this code will cause the failure:
```js
const logTypes = await driver.getLogTypes();
```

**Comment by mykola-mokhnach** [comment]
> 2021-11-16T15:31:29.839Z INFO webdriver: [GET] http://localhost:4723/wd/hub/session/b2d7848b-dba4-44fa-a603-809f7c11dc79/se/log/types

I'm not sure these wdio endpoints use the expected API URLs

**Comment by KazuCocoa** [comment]
i've added the selenium v4 route in https://github.com/appium/appium-base-driver/pull/517
It should be in appium 1.22.0

**Comment by hammzj** [comment]
Seeing for iOS, the path looks different:
```
2021-11-16T16:31:21.689Z INFO webdriver: COMMAND getLogTypes()
2021-11-16T16:31:21.690Z INFO webdriver: [GET] http://localhost:4723/wd/hub/session/c2abec36-9cca-4822-8c85-aa680f3487ad/log/types
2021-11-16T16:31:21.698Z INFO webdriver: RESULT [
  'syslog',
  'crashlog',
  'performance',
  'server',
  'safariConsole',
  'safariNetwork'
]
```

Android:
`/session/:session_id/se/log/types`

iOS:
`/session/:session_id/log/types`

**Comment by hammzj** [comment]
Yep, trying to do so today. I'll report back after moving to 1.12.1.

**Comment by hammzj** [comment]
Nope, still failing. Here's a snippet from the logs:

```
[35m[Appium][39m Appium v1.22.1 creating new AndroidUiautomator2Driver (v1.70.1) session
...
[35m[W3C (b28c5f8a)][39m Driver proxy active, passing request on via HTTP proxy
[debug] [35m[WD Proxy][39m Matched '/wd/hub/session/b28c5f8a-b1ef-4de7-9f9a-55d6ec374ed0/se/log/types' to command name 'getLogTypes'
[debug] [35m[WD Proxy][39m Proxying [GET /wd/hub/session/b28c5f8a-b1ef-4de7-9f9a-55d6ec374ed0/se/log/types] to [GET http://127.0.0.1:8200/wd/hub/session/77e4de4e-5a98-4321-b795-b17602c2df0e/se/log/types] with no body
[35m[WD Proxy][39m Got response with status 404: {"sessionId":null,"value":{"error":"unknown command","message":"The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource","stacktrace":"io.appium.uiautomator2.common.exceptions.UnknownCommandException: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:75)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandler...
[debug] [35m[W3C][39m Matched W3C error code 'unknown command' to UnknownCommandError
[35m[HTTP][39m [37m<-- GET /wd/hub/session/b28c5f8a-b1ef-4de7-9f9a-55d6ec374ed0/se/log/types [39m[33m404[39m [90m27 ms - 3529[39m
[35m[HTTP][39m [90m[39m

**Comment by hammzj** [comment]
So on both v1.22.1 and 1.20.2, I've encountered the same error. I can't use 1.22.1 consistently right now due to other framework issues I need to investigate on our end, but is there a way I can revert the Android path to not use the Selenium route? This change was very surprising and quite silent until I looked at the Appium logs.

Is there a way I can force the old `/session/:session_id/log/types` and `/session/:session_id/log/` path for logs?

**Comment by hammzj** [comment]
So once the Selenium route is in the UiAutomator2 driver and I pull an update, that's all that will need to happen?

**Comment by hammzj** [comment]
@KazuCocoa It will need to be in two places: the one you mentioned, and then here: https://github.com/appium/appium-uiautomator2-driver/blob/7b89e509e44941f9c1a2e3b1fcab453aae7e7f99/lib/driver.js#L97

After looking at the iOS XCUI driver, the paths are different but do not specify `/se/` either: https://github.com/appium/appium-xcuitest-driver/blob/336850c112a84125d54684e703f4679e611a3bcf/lib/driver.js#L112 
However I've not had any problems with that XCUI driver as it's not calling `/se/` paths anyway.

**Comment by mykola-mokhnach** [comment]
These endpoints are not present in NO_PROXY list. This means that the driver redirects them to UIA2 server instead of calling the corresponding handlers. Adding endpoints with `/se/` to NO_PROXY list should resolve the issue

**Comment by KazuCocoa** [comment]
I've  pushed uia2 driver as 1.73.0. You can try it our as `appium@beta`.

**Comment by hammzj** [comment]
After jumping through some hoops to uninstall my old version of Appium (1.20.2) and install the beta (1.23.0-beta.0), I can confirm that the fix in that UIAutomator2 driver successfully pushed a logcat for me. The XCUI driver for iOS also produces syslogs, so I am happy to see this again.

Now, with this change, will I have to use a version of Appium newer than 1.20.2 or can I force the UIA2 driver to be 1.73.0? 

Either way, thanks again for looking into this and fixing it!

**Comment by mykola-mokhnach** [comment]
You could switch to Appium 2. There drivers are decoupled from the server code, so it is possible to install whenever driver version is needed without touching server modules.

**Comment by hammzj** [comment]
@mykola-mokhnach that's my idea next year with our framework. I'm not there yet but I will definitely look into it.
