### ISSUE TITLE
Unknown command/Unhandled endpoint error on trying to get CSS property of WebView element

### ISSUE THREAD

**Issue by ncalaway** [appium/appium#16107]
## The problem

Trying to get the value of a CSS property of a WebView element throws and unknown command error.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS/11.6
* Node.js version (unless using Appium.app|exe): 17.0.1
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Here is the error:
```
{"value":{"error":"unknown command","message":"Unhandled endpoint: /session/5B2A238A-ABDF-4395-B859-461E16463F03/element/4E000000-0000-0000-E919-000000000000/css/class -- http://127.0.0.1:8100/ with parameters {\n    wildcards =     (\n        \"session/5B2A238A-ABDF-4395-B859-461E16463F03/element/4E000000-0000-0000-E919-000000000000/css/class\"\n    );\n}","stacktrace":"UnknownCommandError: Unhandled endpoint: /session/5B2A238A-ABDF-4395-B859-461E16463F03/element/4E000000-0000-0000-E919-000000000000/css/class -- http://127.0.0.1:8100/ with parameters {\n    wildcards =     (\n        \"session/5B2A238A-ABDF-4395-B859-461E16463F03/element/4E000000-0000-0000-E919-000000000000/css/class\"\n    );\n}\n    at errorFromW3CJsonCode (/Users/nick/.local/lib/npm-prefix/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:780:25)\n    at ProxyRequestError.getActualError (/Users/nick/.local/lib/npm-prefix/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:663:14)\n    at asyncHandler (/Users/nick/.local/lib/npm-prefix/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:373:25)"}}
```

## Link to Appium logs

[Here](https://gist.github.com/ncalaway/6ca5b160a549712a2a72cbae80c5ee3b)

## Code To Reproduce Issue [ Good To Have ]

```
curl http://127.0.0.1:4723/wd/hub/session/763bac37-bd2c-4cf9-bf82-2751e35e2169/element/4E000000-0000-0000-E919-000000000000/css/class
```

**Comment by KazuCocoa** [comment]
Did you set WebView context?

**Comment by ncalaway** [comment]
I assume I use this [command](https://appium.io/docs/en/commands/context/set-context/)

What is the value I pass into it to set WebView context?

**Comment by KazuCocoa** [comment]
It depends on the AUT.
https://appium.io/docs/en/writing-running-appium/web/hybrid/

**Comment by ncalaway** [comment]
No I did not. When I do, it works as expected.
