### ISSUE TITLE
Appium inspector error after successfully installing app. Cannot use inspector. 

### ISSUE THREAD

**Issue by wrathmelior** [appium/appium#16116]
## The problem
When I start a session in the appium inspector on my Iphone 12 pro (real device) with sw 14.2, it successfully installs the sw (but does not launch it), but then gives me an error so I cannot access the appium inspector.  https://monosnap.com/file/tUli7WLVpVcg4hH8HCzuN6t2Ah5ix9

If I click on the web driver agent on the device I get error 'Unable to Install "Remax" Please try again later' but if I click on the Remax app it launches successfully. 

https://monosnap.com/file/mmIblUUoVaFjfwntBlNqYyddufF2O8

I generated/downloaded a new provisioning profile and linked it to this device in Xcode. Xcode has no issue building to this device. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac Big Sur
* Node.js version (unless using Appium.app|exe): 12.8.1
* Npm or Yarn package manager:
* Mobile platform/version under test: iOS Iphone 12 pro sw14.2
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: appium desktop

## Link to Appium logs
https://gist.github.com/wrathmelior/b2fc1d7dfdf07b9e2f3aa93a292d2528

**Comment by mykola-mokhnach** [comment]
> [Xcode] 2021-11-17 12:54:06.550 xcodebuild[83269:1659609]  iPhoneConnect: 📱 failed to install /Users/jessical/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app - error Error Domain=com.apple.dt.MobileDeviceErrorDomain Code=-402620395 "Unable to install "WebDriverAgentRunner-Runner"" UserInfo={NSLocalizedDescription=Unable to install "WebDriverAgentRunner-Runner", NSUnderlyingError=0x7fceda8b09b0 {Error Domain=com.apple.dt.MobileDeviceErrorDomain Code=-402620395 "A valid provisioning profile for this executable was not found." UserInfo={MobileDeviceErrorCode=(0xE8008015), com.apple.dtdevicekit.stacktrace=(

Make sure WebDriverAgent is signed properly

**Comment by wrathmelior** [comment]
I followed the instructions on this page to resolve the issue. 

https://docs.katalon.com/katalon-studio/docs/installing-webdriveragent-for-ios-devices.html#configure-the-webdriveragent 

Posting in case it helps anyone else who runs into the same issue.  Thank you for your help mykola-mokhnach
