### ISSUE TITLE
[WD Proxy] Got response with status 407

### ISSUE THREAD

**Issue by mrvincenzo** [appium/appium#16124]
## The problem

I am using TestProject 3.3.1 that uses Appium v1.17.0 underneath to execute tests on Android emulator. When I start TestProject from the MacOS UI (Spotlight, Finder, etc...) and execute my tests everything works as expected. When I start TestProject from the Terminal, I am getting these Appium related errors when trying to execute the same tests. 

I understand that this is might be a TestProject's issue (and not Appium's) but I am trying my luck here.

What is that proxy Appium complains about and how can I configure it? Any help will be appreciated.

```
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:53685/wd/hub/status] with no body
[WD Proxy] Got response with status 407: <HTML><HEAD>
[WD Proxy] <TITLE>Access Denied</TITLE>
[WD Proxy] </HEAD>
[WD Proxy] <BODY>
[WD Proxy] <FONT face="Helvetica">
[WD Proxy] <big><strong></strong></big><BR>
[WD Proxy] </FONT>
[WD Proxy] <blockquote>
[WD Proxy] <TABLE border=0 cellPadding=1 width="80%">
[WD Proxy] <TR><TD>
[WD Proxy] <FONT face="Helvetica">
[WD Proxy] <big>Access Denied (authentication_failed)</big>
[WD Proxy] <BR>
[WD Proxy] <BR>
[WD Proxy] </FONT>
[WD Proxy] </TD></TR>
[WD Proxy] <TR><TD>
[WD Proxy] <FONT face="Helvetica">
[WD Proxy] Your credentials could not be authenticated: "Credentials are missing.". You will not be permitted access until your credentials can be verified.
[WD Proxy] </FONT>
[WD Proxy] </TD></TR>
[WD Proxy] <TR><TD>
[WD Proxy] <FONT face="Helvetica">
[WD Proxy] This is typically caused by an incorrect username and/or password, but could also be caused by network problems.
[WD Proxy] </FONT>
[WD Proxy] </TD></TR>
[WD Proxy] <TR><TD>
[WD Proxy] <FONT face="Helvetica" SIZE=2>
[WD Proxy] <BR>
[WD Proxy]
[WD Proxy] </FONT>
[WD Proxy] </TD></TR>
[WD Proxy] </TABLE>
[WD Proxy] </blockquote>
[WD Proxy] </FONT>
[WD Proxy] </BODY></HTML>
[WD Proxy]
```

## Environment
Appium v1.17.0
MacOS BigSur 11.15.2
Android Emulator Pixel XL API 29 (system-images;android-29;default;x86)

## Link to Appium logs
GIST link: https://gist.github.com/mrvincenzo/f5312ca1284438c388cd147897fc0a47

**Comment by jlipps** [comment]
I'm not sure, but Appium 1.17 is pretty ancient. I'd reach out to TestProject's support on this one. Or reopen this issue if you can repro with the latest version of Appium / UiAutomator2 driver, outside of TestProject.

**Comment by KazuCocoa** [comment]
Appium does not have such http response. I guess their service rejected the route by some reasons.

**Comment by mrvincenzo** [comment]
I figured it out. 

To make it work, I had to eun `export no_proxy="localhost, 127.0.0.1"` before starting the TestProject Agent from Terminal. That's the difference between running it from Mac's UI and running it from Terminal. 

Thanks for the help!
