### ISSUE TITLE
Failure on installing appium 2.0.0-beta because of missing npm package shell-quote

### ISSUE THREAD

**Issue by bwomsm1** [appium/appium#16120]
## The problem
I am willing to test the new Appium server 2.0.0-beta, but my appium server installation fails because of the following missing npm lib:
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for shell-quote@1.7.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

I am installing the appium server with the following command:
``` npm install -g appium@next ```

## Environment

* Appium version (or git revision) that exhibits the issue: 
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS 12.0.1
* Node.js version (unless using Appium.app|exe): v16.13.0
* Npm or Yarn package manager: 8.1.3
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe: CLI

## Details
when I type `npm ls` I can clearly see that `shell-quote` package is installed:
```
├── shell-quote@1.7.2
└── wd@1.14.0
```

## Link to Appium logs
Found above

**Comment by bwomsm1** [comment]
Problem solved as follow:
```
npm uninstall shell-quote
npm cache clean --force
npm install shell-quote
npm install appium@next
```

The idea is to install properly `shell-quote` package

**Comment by jlipps** [comment]
Appium has no peer dependencies. You shouldn't need to install any other NPM packages in order to install Appium. does this not work?

```
npm uninstall shell-quote
npm cache clean --force
npm install appium@next
```

**Comment by bwomsm1** [comment]
@jlipps no, I cannot,  I am getting an error that I am missing `shell-quote` package

**Comment by jlipps** [comment]
Is there a reason you're installing appium locally rather than globally? I was able to install `appium@next` just fine. I'm wondering if the problem is an interaction with the rest of your local project. If you have a local project you should use package.json to manage dependencies, not install them by hand. Then you can simply `rm -rf package-lock.json node_modules && npm install` to see if Appium can be installed alongside your other dependencies.

**Comment by bwomsm1** [comment]
I am trying what you mentioned above but currently running
`npm install -g appium@next`
is giving me:
```
npm ERR! code ENOTFOUND
npm ERR! syscall getaddrinfo
npm ERR! errno ENOTFOUND
npm ERR! network request to http://cloud-build-master16.corp.aeroscout.com:8081/nexus/content/repositories/npmjs/appium failed, reason: getaddrinfo ENOTFOUND cloud-build-master16.corp.aeroscout.com
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
``` 

In addition, `http://cloud-build-master16.corp.aeroscout.com:8081/nexus/content/repositories/npmjs/appium` is not accessible currently, I get 500 error

**Comment by jlipps** [comment]
Seems like you're using a private npm repo. We only officially support Appium being downloaded from the public npm repo. I would talk with your sysadmin.

**Comment by bwomsm1** [comment]
Sorry, I am not familiar, how do I download it from a public repo?
Where did I ask for private in my install command?

**Comment by jlipps** [comment]
You probably have some proxy or environment variable set up to use your corporate mirror of NPM. I don't know how or why it would be set up this way, but `http://cloud-build-master16.corp.aeroscout.com:8081/nexus/content/repositories/npmjs/appium` is not the public NPM.
