### ISSUE TITLE
driver.getPageSource() in NATIVE_APP context execution time is very long for hybrid applications.

### ISSUE THREAD

**Issue by KozlovAlexander** [appium/appium#16121]
## The problem

I have a simple Hybrid application on iOS and Android platform. I need to have access to App object tree in Native context. driver.getPageSource() call become takes too much time ( from driver.getEvents(): 'comand getPageSource execution time is: 39009 ') If I load some complex web page into WebView. As I can see getSource() results contains accessibility tree for WebView Content. I don't need this object tree, because I use WebView context to interact with them. 

## Environment
* Appium version 1.21.0
* client OS: Windows 10 build 19043.1348
* XCUITest driver
* iOS real device, sdkVersion=13.7:
'io.appium::java-client', version: '7.3.0'

## Details
I tried to use 'snapshotMaxDepth' setting and it is really helps to obtain native app source faster, but I need always to know which value I should set. 
Please, provide some Capability or Setting which can tell to Appium Server that I don't want to receive WebView's accessibility children in getSource() results in NATIVE_APP context. I think it will be useful for UIAutomator2 driver for Android platform too.

**Comment by mykola-mokhnach** [comment]
Unfortunately this is beyond our control. The page source is returned by XCTest and is requested for the whole application. If you know any option in XCTest that allows to customise this behaviour then let us know

**Comment by mykola-mokhnach** [comment]
You could also try https://github.com/appium/appium/issues/15015#issuecomment-759884085 as a possible workaround, because it is usually the `visible` attribute, which takes the most time to be calculated
