### ISSUE TITLE
Unable to find elements from the last column after swiping to the right

### ISSUE THREAD

**Issue by StsiapanPal** [appium/appium#16130]
## The problem

Unable to find elements from the last column after swiping to the right

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.0
* Desktop OS/version used to run Appium: iOS 15.0 
* Node.js version (unless using Appium.app|exe): 17.0.1
* Mobile platform/version under test: iPhone 11 Pro
* Real device or emulator/simulator: emulator/simulator
* Appium CLI or Appium.app|exe: Appium.app|exe

## Details

I open a page with a table that does not fit on the screen in landscape mode, then I swipe to the right and all the cells from the last columns are visible on the screen, but when I use the Appium Inspector, I cannot find these items. As a result, the test fails.
An interesting note: when the table is scrolled to the right and all the cells from the first column of the table are not visible, I can find them using Appium Inspector/Code

## Link to Appium logs

https://gist.github.com/StsiapanPal/f5a5c16f275413c51eaa806b1f39f62b

**Comment by KazuCocoa** [comment]
Was this only on iOS 15 simulators?

When I configured iOS 15 simulator on our CI https://github.com/appium/WebDriverAgent/pull/537, I saw weird behavior in find_element after actions like scroll. It was XCTest(behind Appium/WDA) was not able to find the element. Once I changed the view and back to the same view, it worked again. I haven't checked on real devices, so far, iOS 15 tended to have more issues than real device's one in my observation.
Possibly iOS 15 simulators have issues...

**Comment by mykola-mokhnach** [comment]
Elements lookup is basically controlled by XCTest. I don't think there's anything we could change there on Appium side.

**Comment by StsiapanPal** [comment]
> ed again. I haven't checked on real devices, so far, iOS 15 tended to have more issues than real device's one in my observation.

I just tried it on iPhone 11 Pro and iOS 14.4 - same issue.

**Comment by amedvedjev** [comment]
add your code. maybe some ideas will come...

**Comment by StsiapanPal** [comment]
> Was this only on iOS 15 simulators?
> 
> When I configured iOS 15 simulator on our CI [appium/WebDriverAgent#537](https://github.com/appium/WebDriverAgent/pull/537), I saw weird behavior in find_element after actions like scroll. It was XCTest(behind Appium/WDA) was not able to find the element. Once I changed the view and back to the same view, it worked again. I haven't checked on real devices, so far, iOS 15 tended to have more issues than real device's one in my observation. Possibly iOS 15 simulators have issues...



> Elements lookup is basically controlled by XCTest. I don't think there's anything we could change there on Appium side.



> Elements lookup is basically controlled by XCTest. I don't think there's anything we could change there on Appium side.

I open DOM structure using XCode inspector and there all elements are displayed correctly every time.

**Comment by StsiapanPal** [comment]
@mykola-mokhnach @KazuCocoa Please let me know if screenshots/DOM structure or other details are needed. Issue still exist and failed our tests, please assist? 
1. Outside of the code, why Appium Inspector sometimes can inspect, sometimes can not inspect an element after swipe to the right to last column in a table? (I tried to update view/ refresh screen and it didn't help)
2. Why elements that are not visible on the screen after scroll (e.g. column 1, column 2 in a wide table) still can be inspected by Appium Inspector?

P.S. @amedvedjev Context is even out of the code.

**Comment by KazuCocoa** [comment]
Only page source helps.

> Outside of the code, why Appium Inspector sometimes can inspect, sometimes can not inspect an element after swipe to the right to last column in a table? (I tried to update view/ refresh screen and it didn't help)

Afaik, it depends on XCTest (by Apple). Appium/WDA gets elements via XCTest, so the result also depends on it.

I observed an element was not able to get after actions like scroll in tableview on a simulator, for example, while it was available to get on a real device. (this was not recent, but like this case also might happen.)

> Why elements that are not visible on the screen after scroll (e.g. column 1, column 2 in a wide table) still can be inspected by Appium Inspector?

This also depends on XCTest.


Appium logs with `appium:showIOSLog` `true` capability may help to see the query from WDA to XCTest. If the result was actually by XCTest, nothing can help on Appium side, unfortunately as Mykola commented before. Then, only Apple can improve it.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
