### ISSUE TITLE
fix readme badges

### ISSUE THREAD

**Issue by boneskull** [appium/appium#16133]
The badges are broken, both in the root `README.md` and each `README.md` for each package.  Fix them

**Comment by KazuCocoa** [comment]
btw, i've fixed some main drivers' badged as https://github.com/appium/appium/issues/16440 e.g. https://github.com/appium/appium-xcuitest-driver

They have npm stuff and release build badge in GH actions.

**Comment by KazuCocoa** [comment]
[probably](https://github.com/appium/appium/issues/16133#issuecomment-1040562867) should be good enough for now. I'll fix others when i found
