### ISSUE TITLE
Unable to retreive WebView context with appium 1.22.1

### ISSUE THREAD

**Issue by TarasIvaschuk** [appium/appium#16132]
I'm trying to retrieve all available contexts from my app that contains WebView content using the driver.contexts() and it returns only Native context.  I tested the same command on Safari and got the same result. Seems like something has changed. 

It is very important for our team and kind of blocker, so I will appreciate any help and suggestions

**Comment by mykola-mokhnach** [comment]
Recently Apple has added one more security precaution, so it is necessary to interact with a web view before it gets visible to a remote debugger. Try to click it, for example.

If the web view is not visible in Safari then there is nothing we could do in Appium to make it available.

**Comment by Cocognito** [comment]
Hi, 
Just having the same issue.
Thanks to @mykola-mokhnach answer, i try to interact with the webview.
I see that Appium Inspector is able to detect the webview, so i checked the logs and see that appium send 
[HTTP] {"script":"mobile:getContexts","args":[]}  to retrieve the webviews.

So i replace getContextHandles() by executeScript("mobile:getContexts").

This trick works fine, but maybe there is a workaround to have around getContextHandles() as the method can't retrieve the webview by itself.

Other question (maybe dummy) : How can we interact with a webview if we can't detect it ?

Thanks for your feedback.

**Comment by mykola-mokhnach** [comment]
> Other question (maybe dummy) : How can we interact with a webview if we can't detect it ?

You cannot. At least using web context. this screen area would be available from native context though (but might look completely different though)

**Comment by Cocognito** [comment]
My problem is that my native app open a webview.
Then i can switch context if i m able to detect it.
The trick with getContext works with : iphone13/ios15 only.
I m still unable to detect webview in iphone12/ios14.5 or 15.

Any ideas to solve this ?

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
