### ISSUE TITLE
Getting Server side error on personal app installed on android device

### ISSUE THREAD

**Issue by awadheshxccelerata** [appium/appium#16139]
#**Getting following error when trying to launch our own app installed on android device. Preinstalled apps are working fine like chrome, youtube etc but app installed by user is not getting opened and showing following error-**

Failed to create session. An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.sterilwize.prod' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\awadh\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 shell am start -W -n com.sterilwize.prod/com.sterilwize.module.auth.LoginActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' exited with code 1'; Stderr: 'java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.sterilwize.prod/com.sterilwize.module.auth.LoginActivity } from null (pid=28855, uid=2000) not exported from uid 10089 at android.os.Parcel.readException(Parcel.java:1684) at android.os.Parcel.readException(Parcel.java:1637) at android.app.ActivityManagerProxy.startActivityAndWait(ActivityManagerNative.java:3208) at com.android.commands.am.Am.runStart(Am.java:630) at com.android.commands.am.Am.onRun(Am.java:388) at com.android.internal.os.BaseCommand.run(BaseCommand.java:51) at com.android.commands.am.Am.main(Am.java:121) at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method) at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)'; Code: '1'

* Appium version (or git revision) that exhibits the issue: v1.22.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows11
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: android
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe:

**Comment by mykola-mokhnach** [comment]
Please follow the tutorial mentioned in the error message above. Closed as duplicate.
