### ISSUE TITLE
Failed to create WDA session for iOS simulated device

### ISSUE THREAD

**Issue by Fickincool** [appium/appium#16154]
## The problem

Hello all! I am trying to set up Appium to run automated tests on simulated devices for an iOS app I am working on. The problem is that when I open the Appium app and run the inspector, apparently the WebDriverAgent is not able to communicate with the Appium server. I already did some extensive research on my issue, and although I have encountered some suggested solutions, none of them has worked for me so far and I am absolutely lost. 

I really hope you guys can help me. Any pointers will be much appreciated.

Also, please let me know if I can provide additional information to help you find the answer.

Thank you very much in advance.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2
* Desktop OS/version used to run Appium: MacOS Monterey 12.0.1
* Npm or Yarn package manager: Npm
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Simulated iPhone 13 device
* Appium CLI or Appium.app|exe: Appium.app
* Xcode version: 13.1 

## Details

My app is already running in the emulated device using Xcode. Also, I am able to build the WebDriverAgent on Xcode, but cannot see any icon on the emulated device.

### Desired Capabilities

{
  "platformName": "iOS",
  "deviceName": "iPhone 13",
  "app": "/Users/jeronimo/Library/Developer/Xcode/DerivedData/myApp/Build/Products/Debug-iphonesimulator/myApp Dev.app",
  "automationName": "XCUITest",
  "platformVersion": "15.0"
}

What I've tried so far:

- In the WebDriverAgent.xcodeproj located in `/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent/`: for both the WebDriverAgentLib and WebDriverAgentRunner targets I set up my development team and using my developing credentials.
- Tried running everything from scratch again after deleting the folders generated in `/Users/jeronimo/Library/Developer/Xcode/DerivedData/`

## Link to Appium logs

https://gist.github.com/Fickincool/8f270c59ff88b4e5123bfd7fae1bdf0d

**Comment by mykola-mokhnach** [comment]
Appium 1.20 is not compatible to iOS 15 and it is expected it fails. Please make sure you use the most recent server version

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by Fickincool** [comment]
Yup, that was exactly the problem. I tried changing to a simulator supporting iOS 14.0 and it is working now. 

Thank you very much.
