### ISSUE TITLE
Unable to find displayed element on iOS simulator 

### ISSUE THREAD

**Issue by mcoder19** [appium/appium#16167]
## The problem

I experienced a problem where elements could not be found even though they actually did exist in the user interface. 

The problem occurred around 26th september, 2021 and it lasted a few hours before it just went away and I have not experienced it since. Unfortunately, I don't have more details than what is mentioned down in environment. 

I am quite sure that the issue is the same as what is mentioned in the documentation. 

#### Issue(s) mentioned in documentation

Under [Known Issues](http://appium.io/docs/en/writing-running-appium/other/troubleshooting/#known-issues) in the Troubleshooting Appium documentation page, it says the following:
> "Sometimes iOS UI elements become invalidated milliseconds after they are found. This results in an error that looks like `(null) cannot be tapped`. Sometimes the only solution is to put the finding-and-clicking code in a retry block"

Also under the Issues header on [this page](https://appium.readthedocs.io/en/stable/en/writing-running-appium/finding-elements/) and [this page](http://appium.io/docs/en/writing-running-appium/finding-elements/) it says:
> "There's a known issue with table cell elements becoming invalidated before there's time to interact with them. We're working on a fix"

Does anybody know the status of this issue? 

## Environment

* Appium version that exhibits the issue: v.1.21.0
* Desktop OS/version used to run Appium: macOS 
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium desktop 

Additional environment info:
* Appium-Python-Client: 1.2.0
* selenium bindings for python: 3.141.0
* iOS simulator:
    - platformVersion: "14.5"
    - deviceName: "iPhone SE (2nd generation)" 
* xcuitest

**Comment by mykola-mokhnach** [comment]
I don't think there's anything to do there from Appium side. Element lookup is controlled by XCTest.
Also, it is impossible to suggest anything without detailed logs

**Comment by mcoder19** [comment]
Ok. Thank you for the rapid reply.

**Comment by mykola-mokhnach** [comment]
closed as third party issue
