### ISSUE TITLE
Facing - No package 'libimobiledevice-glue-1.0' found when brew install

### ISSUE THREAD

**Issue by ramaraj2601** [appium/appium#16173]
I am doing appium setup in mac machine. While i am running this command in terminal- brew install --HEAD libimobiledevice, I am getting this error.
configure: error: Package requirements (libimobiledevice-glue-1.0 >= 1.0.0) were not met:
No package 'libimobiledevice-glue-1.0' found
Consider adjusting the PKG_CONFIG_PATH environment variable if you installed software in a non-standard prefix.
Alternatively, you may set the environment variables limd_glue_CFLAGS and limd_glue_LIBS to avoid the need to call pkg-config.

Appium Version - 1.22.2
Last working fresh install.
OS - Montery -12.0v
Appium CLI or Appium.app|exe: - 1.20.2 (Appium Inspector)
Real Device -  iPhone.

**Comment by KazuCocoa** [comment]
I think it is not necessary for appium 1.22.2.
Perhaps https://github.com/libimobiledevice/libimobiledevice/issues/1244 may help if you need it.

**Comment by mykola-mokhnach** [comment]
Please report this issue to libmobiledevice, it is unrelated to Appium.
