### ISSUE TITLE
Driver.clear is not working in iOS.

### ISSUE THREAD

**Issue by Faizan-Mamji** [appium/appium#16176]
## driver.clear functionality

Driver.clear is not working on textfield. 

## Environment

* Appium version 1.22.0
* Real device (Iphone X, 15.1) :
* Not working with appium desktop

I have tried the solution that recommended in [https://github.com/appium/appium/issues/13288].
How to click on Select All? I have tried with longpress and after that Select All button appears.

Is there any way to handle clipboard buttons?

Please suggest how to resolve this?

**Comment by mykola-mokhnach** [comment]
Kindly use Appium forum to ask questions.

Toolbar buttons could be clicked same way as any other UI elements - by finding the corresponding element and sending `click` to it.
