### ISSUE TITLE
Can not broadcast or refrsh mediastore in Android 11

### ISSUE THREAD

**Issue by mehrdad-abdoli** [appium/appium#16184]
## The problem

When send a picture by adb or push_file in android API < 29  I use the folowing command to refresh gallery db :
 adb shell am broadcast -a android.intent.action.MEDIA_SCANNER_SCAN_FILE -d file:///mnt/sdcard/Pictures/

so it can been seen in all gallery apps or in my app when user want to upload image from gallery

but  MEDIA_SCANNER_SCAN_FILE is deprecated in Android Api >= 29 as commented  : 
https://developer.android.com/reference/android/content/Intent#ACTION_MEDIA_SCANNER_SCAN_FILE
This constant was deprecated in API level 29.
Callers should migrate to inserting items directly into MediaStore, where they will be automatically scanned after each mutation.

but how can I insert directly into MediaStore by appium or adb?

## Environment

* Appium version : 1.20.2

**Comment by mykola-mokhnach** [comment]
Not sure how this question is related to Appium itself

**Comment by StephanB75** [comment]
could it be handled by pushFile ?
https://appium.io/docs/en/commands/device/files/push-file/

**Comment by mehrdad-abdoli** [comment]
thanks  @mykola-mokhnach and @jlipps  . when it will be released?

**Comment by mehrdad-abdoli** [comment]
How can I use this new feature. Must update appium or ...?

**Comment by mykola-mokhnach** [comment]
> I installed the apk but when use as:

Are you sure the apk was given the necessary permissions?

The feature has been published to appium@beta

**Comment by mykola-mokhnach** [comment]
Closed because of no response
