### ISSUE TITLE
W3C Actions `"relative": true` moves to absolute coordinate location

### ISSUE THREAD

**Issue by ncalaway** [appium/appium#16192]
## The problem

I'm trying to touch down -> wait -> move -> touch up using absolute coordinates for the touch down and relative coordinates for the move. Unfortunately, the move is using absolute coordinates even though I have `"relative": true` set for the move.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 11.6
* Node.js version (unless using Appium.app|exe): 17.0.1
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs
[here](https://gist.github.com/ncalaway/4d17f87f75bc58791d63ed7587a0f566)

**Comment by mykola-mokhnach** [comment]
Could you please point out where this property is present in the webdriver actions standard [definition](https://www.w3.org/TR/webdriver/#pointer-actions)?

**Comment by ncalaway** [comment]
I cannot, because it is not there. I'm not sure where I got this from.

**Comment by jlipps** [comment]
Yeah, you want "origin" set to "pointer" as a way to specify a relative move.
