### ISSUE TITLE
Support finding elements by View tag on Android with UiAutomator2

### ISSUE THREAD

**Issue by JuanCarlos-Arceredillo** [appium/appium#16196]
## The problem

On the one hand UiAutomator2 supports several ways to find elements, but it doesn't offer to find by view-tag, this feature is only supported by Espresso. On the other hand Espresso doesn't support any communication with OS dialogs or menus, what is very hard to avoid during the automatization processes. Espresso has a workaround to skip the permission popups with a capability, but Android has several menus like the calendar, camera, photo gallery, sharing, etc... that are not supported due to the driver is not oriented to do that.

It would be great to add this feature to UiAutomator2 with the search by tag or even UiSelector class.

## Environment

I'm working with appium 1.22 using Espresso at the moment.

**Comment by mykola-mokhnach** [comment]
This is impossible as view tags are not exposed to the accessibility manager.

**Comment by rajdeepv** [comment]
@JuanCarlos-Arceredillo  espresso-driver has limited support of handling out of app areas using UIAutomator APIs which should be good enough if you have to deal with them only occasionally

**Comment by JuanCarlos-Arceredillo** [comment]
Hi @rajdeepv, I agree. I have checked the feature "mobile: uiautomator" and it's the perfect solution for my situation. Each time that there is any dialog or menu out of the app, I'll manage that interfaces using UiAutomator2 commands
