### ISSUE TITLE
WebDriverAgent failed when turn on WI-FI or Airplane mode on iOS devices

### ISSUE THREAD

**Issue by dmytroZhurakovskyi** [appium/appium#16197]
## The problem

Got error: "Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up" after tap related buttons in device preferences or in a control center

## Environment

iPhones: X, 11, 8, 7 (Real devices)
IOS 15.0.2
Appium 1.22.1
macOS: Big Sur, 11.6

## Details

**Devices are connected to mac by USB**
Text "Automation running Hold both volume buttons to stop" hides on a device after tap

## Link to Appium logs

After tap the related button I got next logs in appium server:

debug] [WD Proxy] Matched '/actions' to command name 'performActions'
[debug] [WD Proxy] Proxying [POST /actions] to [POST http://127.0.0.1:8100/session/F0DE8317-AA3E-4A32-B938-3A18A8C7D6C7/actions] with body: {"actions":[{"type":"pointer","id":"finger1","parameters":{"pointerType":"touch"},"actions":[{"type":"pointerMove","duration":0,"x":329,"y":151},{"type":"pointerDown","button":0},{"type":"pause","duration":500},{"type":"pointerUp","button":0}]}]}
[Xcode] 2021-12-02 19:43:41.370768+0200 WebDriverAgentRunner-Runner[14022:978162] Getting the most recent active application (out of 1 total items)
[Xcode] 
[Xcode]     t =    44.97s Find the Application 'com.apple.Preferences'
[Xcode] 
[Xcode]     t =    44.98s     Requesting snapshot of accessibility hierarchy for app with pid 13936
[Xcode] 
[HTTP] --> GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts
[HTTP] {}
[debug] [W3C (0f518184)] Calling AppiumDriver.getTimeouts() with args: ["0f518184-f638-4621-b8dd-dca67223a614"]
[debug] [XCUITest] Executing command 'getTimeouts'
[Xcode] 2021-12-02 19:43:42.059552+0200 WebDriverAgentRunner-Runner[14022:978162] Waiting up to 2s until com.apple.Preferences is in idle state (including animations)
[Xcode] 
[Xcode]     t =    45.65s Wait for com.apple.Preferences to idle
[Xcode] 
[WD Proxy] socket hang up
[debug] [W3C (0f518184)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
[debug] [W3C (0f518184)]     at JWProxy.command (/Users/qae/.nvm/versions/node/v14.17.0/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:274:13)
[debug] [W3C (0f518184)]     at runMicrotasks (<anonymous>)
[debug] [W3C (0f518184)]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[debug] [W3C (0f518184)]     at XCUITestDriver.proxyCommand (/Users/qae/.nvm/versions/node/v14.17.0/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:96:12)
[debug] [W3C (0f518184)]     at XCUITestDriver.performActions (/Users/qae/.nvm/versions/node/v14.17.0/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/gesture.js:131:10)
[HTTP] <-- POST /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/actions 500 20226 ms - 1003
[HTTP] 
[debug] [W3C (0f518184)] Responding to client with driver.getTimeouts() result: {"command":0,"implicit":0}
[HTTP] <-- GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts 304 19784 ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts
[HTTP] {}
[debug] [W3C (0f518184)] Calling AppiumDriver.getTimeouts() with args: ["0f518184-f638-4621-b8dd-dca67223a614"]
[debug] [XCUITest] Executing command 'getTimeouts'
[debug] [W3C (0f518184)] Responding to client with driver.getTimeouts() result: {"command":0,"implicit":0}
[HTTP] <-- GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts 304 1 ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts
[HTTP] {}
[debug] [W3C (0f518184)] Calling AppiumDriver.getTimeouts() with args: ["0f518184-f638-4621-b8dd-dca67223a614"]
[debug] [XCUITest] Executing command 'getTimeouts'
[debug] [W3C (0f518184)] Responding to client with driver.getTimeouts() result: {"command":0,"implicit":0}
[HTTP] <-- GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts 304 1 ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts
[HTTP] {}
[debug] [W3C (0f518184)] Calling AppiumDriver.getTimeouts() with args: ["0f518184-f638-4621-b8dd-dca67223a614"]
[debug] [XCUITest] Executing command 'getTimeouts'
[debug] [W3C (0f518184)] Responding to client with driver.getTimeouts() result: {"command":0,"implicit":0}
[HTTP] <-- GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts 304 1 ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts
[HTTP] {}
[debug] [W3C (0f518184)] Calling AppiumDriver.getTimeouts() with args: ["0f518184-f638-4621-b8dd-dca67223a614"]
[debug] [XCUITest] Executing command 'getTimeouts'
[debug] [W3C (0f518184)] Responding to client with driver.getTimeouts() result: {"command":0,"implicit":0}
[HTTP] <-- GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts 304 1 ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts
[HTTP] {}
[debug] [W3C (0f518184)] Calling AppiumDriver.getTimeouts() with args: ["0f518184-f638-4621-b8dd-dca67223a614"]
[debug] [XCUITest] Executing command 'getTimeouts'
[debug] [W3C (0f518184)] Responding to client with driver.getTimeouts() result: {"command":0,"implicit":0}
[HTTP] <-- GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts 304 1 ms - -
[HTTP] 
[Xcode] 2021-12-02 19:44:10.558234+0200 WebDriverAgentRunner-Runner[14022:978477] [Default] Exiting due to IDE disconnection.
[Xcode] 
[Xcode] 2021-12-02 19:44:10.919390+0200 WebDriverAgentRunner-Runner[14034:979346] Running tests...
[Xcode] 
[HTTP] --> GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts
[HTTP] {}
[debug] [W3C (0f518184)] Calling AppiumDriver.getTimeouts() with args: ["0f518184-f638-4621-b8dd-dca67223a614"]
[debug] [XCUITest] Executing command 'getTimeouts'
[debug] [W3C (0f518184)] Responding to client with driver.getTimeouts() result: {"command":0,"implicit":0}
[HTTP] <-- GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts 304 1 ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts
[HTTP] {}
[debug] [W3C (0f518184)] Calling AppiumDriver.getTimeouts() with args: ["0f518184-f638-4621-b8dd-dca67223a614"]
[debug] [XCUITest] Executing command 'getTimeouts'
[debug] [W3C (0f518184)] Responding to client with driver.getTimeouts() result: {"command":0,"implicit":0}
[HTTP] <-- GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts 304 1 ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts
[HTTP] {}
[debug] [W3C (0f518184)] Calling AppiumDriver.getTimeouts() with args: ["0f518184-f638-4621-b8dd-dca67223a614"]
[debug] [XCUITest] Executing command 'getTimeouts'
[debug] [W3C (0f518184)] Responding to client with driver.getTimeouts() result: {"command":0,"implicit":0}
[HTTP] <-- GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts 304 1 ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts
[HTTP] {}
[debug] [W3C (0f518184)] Calling AppiumDriver.getTimeouts() with args: ["0f518184-f638-4621-b8dd-dca67223a614"]
[debug] [XCUITest] Executing command 'getTimeouts'
[debug] [W3C (0f518184)] Responding to client with driver.getTimeouts() result: {"command":0,"implicit":0}
[HTTP] <-- GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts 304 1 ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts
[HTTP] {}
[debug] [W3C (0f518184)] Calling AppiumDriver.getTimeouts() with args: ["0f518184-f638-4621-b8dd-dca67223a614"]
[debug] [XCUITest] Executing command 'getTimeouts'
[debug] [W3C (0f518184)] Responding to client with driver.getTimeouts() result: {"command":0,"implicit":0}
[HTTP] <-- GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts 304 1 ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts
[HTTP] {}
[debug] [W3C (0f518184)] Calling AppiumDriver.getTimeouts() with args: ["0f518184-f638-4621-b8dd-dca67223a614"]
[debug] [XCUITest] Executing command 'getTimeouts'
[debug] [W3C (0f518184)] Responding to client with driver.getTimeouts() result: {"command":0,"implicit":0}
[HTTP] <-- GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts 304 1 ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts
[HTTP] {}
[debug] [W3C (0f518184)] Calling AppiumDriver.getTimeouts() with args: ["0f518184-f638-4621-b8dd-dca67223a614"]
[debug] [XCUITest] Executing command 'getTimeouts'
[debug] [W3C (0f518184)] Responding to client with driver.getTimeouts() result: {"command":0,"implicit":0}
[HTTP] <-- GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts 304 1 ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts
[HTTP] {}
[debug] [W3C (0f518184)] Calling AppiumDriver.getTimeouts() with args: ["0f518184-f638-4621-b8dd-dca67223a614"]
[debug] [XCUITest] Executing command 'getTimeouts'
[debug] [W3C (0f518184)] Responding to client with driver.getTimeouts() result: {"command":0,"implicit":0}
[HTTP] <-- GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts 304 1 ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts
[HTTP] {}
[debug] [W3C (0f518184)] Calling AppiumDriver.getTimeouts() with args: ["0f518184-f638-4621-b8dd-dca67223a614"]
[debug] [XCUITest] Executing command 'getTimeouts'
[debug] [W3C (0f518184)] Responding to client with driver.getTimeouts() result: {"command":0,"implicit":0}
[HTTP] <-- GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts 304 1 ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts
[HTTP] {}
[debug] [W3C (0f518184)] Calling AppiumDriver.getTimeouts() with args: ["0f518184-f638-4621-b8dd-dca67223a614"]
[debug] [XCUITest] Executing command 'getTimeouts'
[debug] [W3C (0f518184)] Responding to client with driver.getTimeouts() result: {"command":0,"implicit":0}
[HTTP] <-- GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts 304 1 ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts
[HTTP] {}
[debug] [W3C (0f518184)] Calling AppiumDriver.getTimeouts() with args: ["0f518184-f638-4621-b8dd-dca67223a614"]
[debug] [XCUITest] Executing command 'getTimeouts'
[debug] [W3C (0f518184)] Responding to client with driver.getTimeouts() result: {"command":0,"implicit":0}
[HTTP] <-- GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts 304 1 ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts
[HTTP] {}
[debug] [W3C (0f518184)] Calling AppiumDriver.getTimeouts() with args: ["0f518184-f638-4621-b8dd-dca67223a614"]
[debug] [XCUITest] Executing command 'getTimeouts'
[debug] [W3C (0f518184)] Responding to client with driver.getTimeouts() result: {"command":0,"implicit":0}
[HTTP] <-- GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts 304 1 ms - -
[HTTP] 
[Xcode] 
[Xcode] Restarting after unexpected exit, crash, or test timeout in -[UITestingUITests testRunner]; summary will include totals from previous launches.
[Xcode] 
[Xcode] 
[Xcode] Test Suite 'Selected tests' started at 2021-12-02 19:45:09.631
[Xcode] 
[Xcode] Test Suite 'WebDriverAgentRunner.xctest' started at 2021-12-02 19:45:09.632
[Xcode] Test Suite 'UITestingUITests' started at 2021-12-02 19:45:09.632
[Xcode]     t =      nans Suite Set Up
[Xcode] 
[Xcode] 2021-12-02 19:45:09.654369+0200 WebDriverAgentRunner-Runner[14034:979346] [User Defaults] Couldn't write values for keys (
[Xcode]     KeyboardAutocorrection
[Xcode] ) in CFPrefsPlistSource<0x281aec480> (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
[Xcode] 2021-12-02 19:45:09.654909+0200 WebDriverAgentRunner-Runner[14034:979346] [User Defaults] Couldn't write values for keys (
[Xcode]     "KeyboardAutocorrection_changedAt"
[Xcode] ) in CFPrefsPlistSource<0x281aec480> (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
[Xcode] 
[Xcode] 2021-12-02 19:45:09.655414+0200 WebDriverAgentRunner-Runner[14034:979346] [User Defaults] Couldn't write values for keys (
[Xcode]     "KeyboardAutocorrection_buildAtChange"
[Xcode] ) in CFPrefsPlistSource<0x281aec480> (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
[Xcode] 2021-12-02 19:45:09.655870+0200 WebDriverAgentRunner-Runner[14034:979346] [User Defaults] Couldn't write values for keys (
[Xcode]     "KeyboardAutocorrection_previousValue"
[Xcode] ) in CFPrefsPlistSource<0x281aec480> (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
[Xcode] 2021-12-02 19:45:09.656313+0200 WebDriverAgentRunner-Runner[14034:979346] [User Defaults] Couldn't write values for keys (
[Xcode]     "KeyboardAutocorrection_analyzedAt"
[Xcode] ) in CFPrefsPlistSource<0x281aec480> (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
[Xcode] 
[Xcode] 2021-12-02 19:45:09.667404+0200 WebDriverAgentRunner-Runner[14034:979346] [User Defaults] Couldn't write values for keys (
[Xcode]     KeyboardPrediction
[Xcode] ) in CFPrefsPlistSource<0x281aec480> (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
[Xcode] 
[Xcode] 2021-12-02 19:45:09.667998+0200 WebDriverAgentRunner-Runner[14034:979346] [User Defaults] Couldn't write values for keys (
[Xcode]     KeyboardShowPredictionBar
[Xcode] ) in CFPrefsPlistSource<0x281aec480> (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
[Xcode] 
[Xcode] 2021-12-02 19:45:09.668641+0200 WebDriverAgentRunner-Runner[14034:979346] [User Defaults] Couldn't write values for keys (
[Xcode]     DidShowGestureKeyboardIntroduction
[Xcode] ) in CFPrefsPlistSource<0x281aec480> (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
[Xcode] 
[Xcode] Test Suite 'UITestingUITests' failed at 2021-12-02 19:45:09.673.
[Xcode] 	 Executed 1 test, with 1 failure (0 unexpected) in 0.000 (0.040) seconds
[Xcode] 
[Xcode] Test Suite 'WebDriverAgentRunner.xctest' failed at 2021-12-02 19:45:09.673.
[Xcode] 	 Executed 1 test, with 1 failure (0 unexpected) in 0.000 (0.041) seconds
[Xcode] Test Suite 'Selected tests' failed at 2021-12-02 19:45:09.673.
[Xcode] 	 Executed 1 test, with 1 failure (0 unexpected) in 0.000 (0.042) seconds
[Xcode] 
[Xcode] 2021-12-02 19:45:09.568 xcodebuild[24229:495855] [MT] IDETestOperationsObserverDebug: 138.296 elapsed -- Testing started completed.
[Xcode] 
[Xcode] 2021-12-02 19:45:09.568 xcodebuild[24229:495855] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
[Xcode] 2021-12-02 19:45:09.568 xcodebuild[24229:495855] [MT] IDETestOperationsObserverDebug: 138.296 sec, +138.296 sec -- end
[Xcode] 
[Xcode] 
[Xcode] Test session results, code coverage, and logs:
[Xcode] 	/Users/qae/Library/Developer/Xcode/DerivedData/WebDriverAgent-abookjhkghisjjajfroaixdbcith/Logs/Test/Test-WebDriverAgentRunner-2021.12.02_19-42-50-+0200.xcresult
[Xcode] 
[Xcode] 
[Xcode] Failing tests:
[Xcode] 	WebDriverAgentRunner:
[Xcode] 		-[UITestingUITests testRunner]
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[Xcode] Testing started
[Xcode] 
[WebDriverAgent] xcodebuild exited with code '65' and signal 'null'
[HTTP] --> GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts
[HTTP] {}
[debug] [W3C (0f518184)] Calling AppiumDriver.getTimeouts() with args: ["0f518184-f638-4621-b8dd-dca67223a614"]
[debug] [XCUITest] Executing command 'getTimeouts'
[debug] [W3C (0f518184)] Responding to client with driver.getTimeouts() result: {"command":0,"implicit":0}
[HTTP] <-- GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts 304 1 ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts
[HTTP] {}
[debug] [W3C (0f518184)] Calling AppiumDriver.getTimeouts() with args: ["0f518184-f638-4621-b8dd-dca67223a614"]
[debug] [XCUITest] Executing command 'getTimeouts'
[debug] [W3C (0f518184)] Responding to client with driver.getTimeouts() result: {"command":0,"implicit":0}
[HTTP] <-- GET /wd/hub/session/0f518184-f638-4621-b8dd-dca67223a614/timeouts 304 1 ms - -

**Comment by mykola-mokhnach** [comment]
This is expected that all network connection to the phone get reset after WiFi state change. There is nothing we could do about it. A possible workaround that comes to my mind would be to quite the session immediately after state change and then trying to starting it again in noReset mode

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
