### ISSUE TITLE
when use Appium with UIAccessibility to test iOS app, it will often crash.

### ISSUE THREAD

**Issue by hungrytocode** [appium/appium#16209]
## The problem

 Using Appium with UIAccessibility to test iOS app, it will often crash.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.19.1
* iOS version： 14.0

**crash log**：
Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000001, 0x00000001023a635c
Termination Signal: Trace/BPT trap: 5
Termination Reason: Namespace SIGNAL, Code 0x5
Terminating Process: exc handler [2694]
Triggered by Thread:  19

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0:
0   libsystem_kernel.dylib        	0x00000001baab82d0 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x00000001baab7660 mach_msg + 76
2   AXRuntime                     	0x00000001ac758d40 _AXMIGCopyParameterizedAttributeValue + 300
3   AXRuntime                     	0x00000001ac706148 AXUIElementCopyParameterizedAttributeValueRecursive + 668
4   AXRuntime                     	0x00000001ac705e14 AXUIElementCopyParameterizedAttributeValue + 96
5   AXRuntime                     	0x00000001ac7075a8 AXConvertPointFromHostedCoordinates + 232
6   UIAccessibility               	0x00000001a1679e6c -[NSObject+ 142956 (AXPrivCategory) _accessibilityVisiblePointHitTestingAnyElement:] + 2368
7   UIAccessibility               	0x00000001a167a398 -[NSObject+ 144280 (AXPrivCategory) _accessibilityIsVisibleByCompleteHitTest] + 216
8   UIAccessibility               	0x00000001a16841a0 -[NSObject+ 184736 (AXPrivCategory) _iosAccessibilityAttributeValue:] + 6552
9   UIAccessibility               	0x00000001a16b4c30 _accessibilityAttributesForObject + 412
10  UIAccessibility               	0x00000001a16b6264 _fetchAttributesIfNecessary + 136
11  UIAccessibility               	0x00000001a16b4fac _accessibilityAttributesForObject + 1304
12  UIAccessibility               	0x00000001a16b43bc -[NSObject+ 381884 (UIAccessibilityAutomation) _accessibilityUserTestingSnapshotDescendantsWithAttributes:maxDepth:maxChildren:maxArrayCount:honorsModalViews:] + 888
13  UIAccessibility               	0x00000001a16b5fc4 -[NSObject+ 389060 (UIAccessibilityAutomation) _accessibilityUserTestingSnapshotWithOptions:] + 1112
14  UIAccessibility               	0x00000001a1681934 -[NSObject+ 174388 (AXPrivCategory) _iosAccessibilityAttributeValue:forParameter:] + 11464
15  UIKit                         	0x00000001d8158e20 -[UIApplicationAccessibility _iosAccessibilityAttributeValue:forParameter:] + 308
16  UIAccessibility               	0x00000001a165c6cc _copyParameterizedAttributeValueCallback + 408
17  AXRuntime                     	0x00000001ac70be00 ___AXXMIGCopyParameterizedAttributeValue_block_invoke + 64
18  AXRuntime                     	0x00000001ac70b60c _handleNonMainThreadCallback + 68
19  AXRuntime                     	0x00000001ac70bc88 _AXXMIGCopyParameterizedAttributeValue + 388
20  AXRuntime                     	0x00000001ac75a094 _XCopyParameterizedAttributeValue + 392
21  AXRuntime                     	0x00000001ac71b228 mshMIGPerform + 272
22  CoreFoundation                	0x000000018d376fe8 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 60
23  CoreFoundation                	0x000000018d376378 __CFRunLoopDoSource1 + 596
24  CoreFoundation                	0x000000018d37008c __CFRunLoopRun + 2360
25  CoreFoundation                	0x000000018d36f21c CFRunLoopRunSpecific + 600
26  GraphicsServices              	0x00000001a4e73784 GSEventRunModal + 164
27  UIKitCore                     	0x000000018fdadfe0 -[UIApplication _run] + 1072
28  UIKitCore                     	0x000000018fdb3854 UIApplicationMain + 168
29  RoomsController               	0x00000001021fc8c8 main + 51400 (AppDelegate.swift:15)
30  libdyld.dylib                 	0x000000018d02f6b0 start + 4

**Comment by mykola-mokhnach** [comment]
- Please use most recent Appium version
- The crash happens inside of iOS internals, so I don't think we could do much there on Appium side. Consider reporting it to Apple. It could be it works better in newer iOS versions as version 14 is pretty old

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by hungrytocode** [comment]
您好，我是陈俊城，您的邮件我已收到，如需要请拨打18650345140，谢谢。
