### ISSUE TITLE
page_source lost Text elements that under ListItem on Windows

### ISSUE THREAD

**Issue by lwwang-lw** [appium/appium#16200]
## The problem
I found the Windows's page_source will lost Text elements, if the Text elements under ListItem.
### This is part of element tree:
![image](https://user-images.githubusercontent.com/48469245/144569955-bae79993-084c-4308-aa51-e30aad501792.png)

### this is page_source:
![image](https://user-images.githubusercontent.com/48469245/144570065-c8d4bb97-adf7-464e-8f3d-f2d085e07fa6.png)

## Environment

* Appium version : 1.21.0
* WinAppDriver version: 1.2.1.0
* Desktop OS/version used to run Appium: Windows 10 19043.1348
* Node.js version : 12.8.1
* Npm: 6.14.13
* Appium Desktop

**Comment by mykola-mokhnach** [comment]
Please report your issue to https://github.com/microsoft/WinAppDriver
Appium team does not maintain it neither has access to its source code.
