### ISSUE TITLE
[XCUITest] mobile: installApp ignores the 'strategy' argument

### ISSUE THREAD

**Issue by alei01** [appium/appium#16201]
## The problem

The installApp command ignores the 'strategy' parameter: 
```
POST /wd/hub/session/90de752a-5efa-44c3-834b-8d0575e22d84/appium/device/install_app
{"appPath":"/app/testapp.ipa","options":{"strategy":"ios-deploy"}}
```
```
[XCUITest] Installing '/tmp/2021113-12-t9f6le.vhuhe/testapp.app' to the real device with UDID '13deb6e4a2cbb409a01ceeb3ab212a1c92207399'
[XCUITest] Using 'serial' app deployment strategy. You could change it by providing another value to the 'appInstallStrategy' capability
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.1
* Last Appium version that did not exhibit the issue (if applicable): --
* Desktop OS/version used to run Appium: macOS Big Sur 11.6  
* Node.js version (unless using Appium.app|exe): v17.0.1
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS 15.1
* Real device or emulator/simulator: real
* Appium CLI or Appium.app|exe: cli

## Details

- Java client

**Flow:**
1. Changed the installations strategy with Capabilities:
```
 capabilities.setCapability("appium:appInstallStrategy", "ios-deploy")
```
2. Install the app with capabilities
3. Remove the app
4. Call the installApp method to install the app from the test
- Used to pass the options
```
default void installApp(String appPath, @Nullable BaseInstallApplicationOptions options) 
```
5. Verify the App installation strategy

**Result:**
The app is installed with provided strategy using the capabilities. But installApp ignores the 'strategy' parameter passed as BaseInstallApplicationOptions and also ignores the param in capabilities.

## Link to Appium logs
 [GIST](https://gist.github.com/alei01/96118fd25a0abb1de6472aae0f52f16a)

**Comment by mykola-mokhnach** [comment]
Try `mobile: installApp` extension instead

**Comment by mykola-mokhnach** [comment]
Could you also provide your client code?

**Comment by mykola-mokhnach** [comment]
Closed as fixed
