### ISSUE TITLE
merge appium-plugins monorepo

### ISSUE THREAD

**Issue by boneskull** [appium/appium#16206]
The [`appium/appium-plugins`](https://github.com/appium/appium-plugins) is a monorepo containing plugins for Appium v2. It predates the monorepo created here.

During testing, it would make a lot of sense for these "official" plugins to execute against the latest development version of Appium.  As of this writing, the `appium-plugins` monorepo is pinned to `appium@2.0.0-beta.19`, which is... I'm not sure what to call it other than "wrong".  Using the latest published version of Appium v2 would be _helpful_ (with a semver spec of something like `next` for now), but still insufficient: neither Appium nor the plugins will know if they break each other during the course of development!

Ideally, any change to Appium should be tested against the plugins, and vice-versa.  One way to accomplish that is to just merge the monorepos together.  Otherwise, it'd need to be a bespoke script to pull and build the latest versions of either, since installing from github (e.g., `npm install https://github.com/appium/appium/tree/master/packages/appium`) would result in an unbuilt package being installed.  Expecting `appium` and `appium-plugins` to be sibling directories in a contributors's workspace is brittle (and probably has unintended consequences), even if it works for some of us.  Submodules are...yeah, no

Anyway, summary.

## Advantages to Merging

- Immediate feedback if a change will break Appium or its plugins
- One less issue tracker & repo to manage
- Enables better coordination of changes that affect both Appium _and_ its plugins (@jlipps!)

## Disadvantages to Merging

- Will necessarily embiggen this monorepo and make builds, tests, CI, etc., slower.
- `appium-plugins` does not use Gulp as a build system (which is a good thing), but mgmt of dual build systems _will_ suck to some degree
- `appium-plugins` uses TypeScript for its build, which may create conflicts with the TS configuration already present in the `2.0` branch
- It may be difficult to retain the history of changes to `appium-plugins`.  `lerna import` typically helps with this, but I'm unsure how successful this will be when the source is a monorepo, which means either a) we'd need to do it manually, or b) we'd lose the history altogether.

## My Opinion

The advantages significantly outweigh the disadvantages.

What say you?

**Comment by jlipps** [comment]
I agree we should merge them. Is there any way to modernize the main monorepo's build system at the same time? The one that's operative in the plugins repo seems to be working great. We could still keep gulp for the one-off tasks and gradually migrate those, but move off it for transpiling and linting entirely.

**Comment by mykola-mokhnach** [comment]
this is done
