### ISSUE TITLE
exec-out not recognized?

### ISSUE THREAD

**Issue by archubbuck** [appium/appium#16208]
## The problem

I am trying to use `exec-out` to send a binary image from `screencap` to my host device, not the emulator, but `exec-out` doesn't seem to be recognized. Is this expected?

## Code To Reproduce Issue [ Good To Have ]

```await adb.shell(`exec-out screencap -p > ss.png`)```

**Comment by mykola-mokhnach** [comment]
Could you please fill out the issue reporting form and attach the full server log?

**Comment by mykola-mokhnach** [comment]
Closed because of no response
