### ISSUE TITLE
Simulator iOS 15 not able to launch application using Appium v1.21.0 (The simulator has '1' bundles which have 'WebDriverAgentRunner-Runner' as their 'CFBundleName')

### ISSUE THREAD

**Issue by Laxmikanth-phtn** [appium/appium#16204]
## Trying to execute the appium mobile app test using iOS 15.0 simulator. Not able to launch application ("Output from xcodebuild will only be logged if any errors are present there. To change this, use 'showXcodeLog' desired capability")
WebdriverAgent is installing & Automatically uninstalling 

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: Mac OS 11.6
* Node.js version (unless using Appium.app|exe): 14.15.5
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: Mobile App
* Real device or emulator/simulator: Simulator 15.0
* Appium CLI or Appium.app|exe: Appium.app v 1.21.0

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

**Issue :** 
[XCUITest] Quitting and uninstalling WebDriverAgent
[WebDriverAgent] Shutting down sub-processes
[iOSSim] Building bundle path map
[iOSSim] The simulator has '1' bundles which have 'WebDriverAgentRunner-Runner' as their 'CFBundleName':
[iOSSim]     'com.facebook.WebDriverAgentRunner.xctrunner'
[WebDriverAgent] Uninstalling WDAs: 'com.facebook.WebDriverAgentRunner.xctrunner'
[XCUITest] {}
## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Please provide the full server log

**Comment by mykola-mokhnach** [comment]
BTW, Appium 1.21 does not support iOS 15. Consider updating the server to the most recent version

**Comment by mykola-mokhnach** [comment]
Closed because of no response
