### ISSUE TITLE
Unable to compile the build using Appium with Espresso Driver.

### ISSUE THREAD

**Issue by ms-sowmya** [appium/appium#16210]
## The problem
Unable to compile the build using Appium with Espresso Driver.

## Environment
* Appium version: 2.0.0-beta.23
* Mobile platform/version under test: Android Version 11

## Details
The error thrown is  
Task :app:compileDebugAndroidTestJavaWithJavac FAILED
[Gradle] [STDERR] /private/var/folders/nn/qfbfwv610ys4rvshyty5mzf80000gn/T/espresso-server-4c7889d2/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/InvocationOperation.java:26: error: cannot access Instrumentation
[Gradle] [STDERR]                 InstrumentationRegistry.getInstrumentation().runOnMainSync(runnable);

## Link to Appium logs
[Link to logs.](https://gist.github.com/ms-sowmya/29b978dd4c44dfee62015ba7e726e0e5)

**Comment by mykola-mokhnach** [comment]
Is the build obfuscated?

**Comment by ms-sowmya** [comment]
Nope. Works fine with UIAutomator2.

**Comment by mykola-mokhnach** [comment]
I don't have any other ideas then. I was observing similar errors when some application imports were missing or the build was obfuscated, so the compiler could not find appropriate classes.
In general the way Espresso works is very different from UIA2. Check https://github.com/appium/appium-espresso-driver#comparison-with-uiautomator2 for more details.

**Comment by mykola-mokhnach** [comment]
I don't think we could help anything more there. Like mentioned before the resulting flow depends a lot on how an application under test is built and which build options have been provided.
