### ISSUE TITLE
Docs: XCUITest works fine with jailbroken device

### ISSUE THREAD

**Issue by baltpeter** [appium/appium#16211]
## The problem

#14517 introduced a doc change to state that the XCUITest driver didn't work with jailbroken devices based on one user report (appium/appium-desktop#1447). However, I was able to use the driver on a jailbroken iPhone without issues.

Have there been any other reports regarding this? Otherwise, I would assume that the error reported in appium/appium-desktop#1447 had some other cause or at least the situation has changed since then.

I'd be happy to submit a PR removing the hint.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.1
* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium: macOS 11.6.1
* Node.js version (unless using Appium.app|exe): 17.2.0
* Npm or Yarn package manager: npm 8.1.4
* Mobile platform/version under test: iOS 1.48
* Real device or emulator/simulator: real iPhone 7
* Appium CLI or Appium.app|exe: CLI

**Comment by mykola-mokhnach** [comment]
The documentation has been updated. Thanks @KazuCocoa
