### ISSUE TITLE
Docs: `-allowProvisioningUpdates` argument for XCUITest driver on real device

### ISSUE THREAD

**Issue by baltpeter** [appium/appium#16212]
## The problem

The "Full manual configuration" steps on the "Appium XCUITest Driver Real Device Setup" doc page didn't work for me. I was able to get it working by adding a `-allowProvisioningUpdates` argument to the `xcodebuild` command.

I'm happy to submit a PR for that if you agree the docs should be changed accordingly.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.1
* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium: macOS 11.6.1
* Node.js version (unless using Appium.app|exe): 17.2.0
* Npm or Yarn package manager: npm 8.1.4
* Mobile platform/version under test: iOS 1.48
* Real device or emulator/simulator: real iPhone 7
* Appium CLI or Appium.app|exe: CLI

## Details

After the "Basic (automatic) configuration" (https://appium.io/docs/en/drivers/ios-xcuitest-real-devices/#basic-automatic-configuration) and "Basic (manual) configuration" (https://appium.io/docs/en/drivers/ios-xcuitest-real-devices/#basic-manual-configuration) from the docs page on using a real device with the XCUITest driver didn't work for me, I tried the steps in "Full manual configuration" (https://appium.io/docs/en/drivers/ios-xcuitest-real-devices/#full-manual-configuration).

This worked fine until the `xcodebuild` command:

https://github.com/appium/appium/blob/b9d42c2e778972bb04d7f4330abc086d5cccf71a/docs/en/drivers/ios-xcuitest-real-devices.md#L167

Running this command failed for me with the following error:

```
Testing failed:
	No profiles for 'de.benjamin-altpeter.WebDriverAgentRunner.xctrunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'de.benjamin-altpeter.WebDriverAgentRunner.xctrunner'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
	Testing cancelled because the build failed.
```

After changing the command to `xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' -allowProvisioningUpdates test` as suggested by the error, I was able to get the runner working on the device successfully.

The same error was also shown in the Appium logs when running "Basic (automatic) configuration" and "Basic (manual) configuration", so it might be worth adding the argument there, too.

Maybe relevant: I am using a free Apple developer account.

**Comment by KazuCocoa** [comment]
I see.

> Maybe relevant: I am using a free Apple developer account.

Yea, this might be. It would be nice to address `-allowProvisioningUpdates` in case the command did not work in the documentation.
PRs are welcome :)
