### ISSUE TITLE
Cannot get Android device to launch Appium inspector

### ISSUE THREAD

**Issue by markhsbc** [appium/appium#16228]
I  am trying to get my Samsung Galaxy S20 FE device to launch appium inspector on PC, but keep getting errors

I have setup my capabilities as follows:
{
  "device": "Android",
  "deviceName": "RFCR503CYWE",
  "platformName": "Android",
  "platformVersion": "11",
  "appPackage": "com.churchreactnative",
  "appActivity": "com.churchreactnative.MainActivity",
  "automationName": "UiAutomator2",
  "noSign": true,
  "noReset": true
}

PC/Laptop 
* Appium version (or git revision) that exhibits the issue: 1.10.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Windows 10 Home/ Version 20H@
* Node.js version (unless using Appium.app|exe): v14.15.1
* Npm or Yarn package manager: 6.14.8
* Mobile platform/version under test:  Samsung Galaxy S20 FE
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:  Appium app

When I launch the Appium inspector custom server with all the proper capabilities I keep getting error:
Got an unexpected response: {"code":"ECONNRESET"}

Appium log file is attached

**Comment by jlipps** [comment]
have you read the readme at https://github.com/appium/appium-inspector?

**Comment by mykola-mokhnach** [comment]
> Appium log file is attached

Sorry, but I cannot find the log

> Appium version (or git revision) that exhibits the issue: 1.10.0

Are you sure it's this version? It must be super outdated then. Try to use the most recent one

**Comment by mykola-mokhnach** [comment]
Closed because of no response
