### ISSUE TITLE
Appium XCUIElementTypeOther name attribute

### ISSUE THREAD

**Issue by roskyba** [appium/appium#16223]
## The problem

I have a React Native application that has an extremely polluted App Source when viewed via the inspector.

Every piece of text in all the child elements is being added to the name attribute of the parent XCUIElementTypeOther elements

## Environment

* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Iphone 11 / Iphone 12
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

![03c5f5ba2c412509dcf29e0d1b8115474ce8a842](https://user-images.githubusercontent.com/34886027/145026088-9d01706a-3548-4d03-8f4b-b34d5544dd28.jpeg)

**Comment by mykola-mokhnach** [comment]
The accessibility tree is generated by XCTest based on the information provided by the app under test to the accessibility manager. There is absolutely nothing one could change on Appium side to change that. 

The only possible thing to change that would be to play with how react native describes its controls to the accessibility.

**Comment by roskyba** [comment]
@mykola-mokhnach great, thanks!

In what way should I modify react-native app? Should I pass some accessibility props with `{false}` to the _parent_ ?

**Comment by mykola-mokhnach** [comment]
I cannot help there as I don't have any expertise in RN development.

**Comment by jlipps** [comment]
If you explicitly set accessibility props on an element, that should do it as RN will generate accessibility props based on child text which can get quite ugly. But yes, this is an RN issue and not an appium issue so if you have any more questions best to ask in an RN forum.

**Comment by RodolfoDodo** [comment]
Estou com o mesmo problema tem alguma solução ?

**Comment by vineet-devin** [comment]
hey @roskyba how did you manage to fix it? I am also facing the same issue with our app right now.

**Comment by renjieguo927** [comment]
Perhaps you can find the answer on the [RN](https://reactnative.dev/docs/accessibility) official website. There is relevant information about accessibilityLabel, and if you haven't set accessibilityLabel, it will combine the following texts together with spaces to display.

**Comment by apoorva-quince** [comment]
Hey @roskyba were you able to fix this issue? I am facing this same issue with my app, any inputs?
