### ISSUE TITLE
Basic and Advance features

### ISSUE THREAD

**Issue by jacksonfrye** [appium/appium#16227]
Hi everyone. This is not an issue but just a question. 
I'm a newbie in Android Developer and kinda new to Appium, so I really need an expert to explain for me about what is basic and advance features that Apium can offer for me?
I am finding Mobile Automatic Test tool.

**Comment by mykola-mokhnach** [comment]
Kindly use [Appium forum](https://discuss.appium.io) to ask questions.

**Comment by jacksonfrye** [comment]
Thank you

**Comment by jacksonfrye** [comment]
@mykola-mokhnach hi again, so I did go to the link you sent me. And I also register an account, but I have been waiting for so long for an email message. But till now, the site doesn't send me an email. My is manhhung1000000gmail.com. Can you help me?

**Comment by mykola-mokhnach** [comment]
I don't see such email address being registered there. Is it spelled properly? Have you checked if the confirmation email landed in the junk/spam box?

**Comment by jacksonfrye** [comment]
Never mind, I have registered. Thank you for spending time with me. I
appreciate it.
