### ISSUE TITLE
[Feature Request] Distinguish android devices through deviceName

### ISSUE THREAD

**Issue by DevDengChao** [appium/appium#16237]
## The problem

> On Android this capability is currently ignored, though it remains required.

As https://appium.io/docs/en/writing-running-appium/caps/#general-capabilities said, Appium currently not support distinguish android devices through `deviceName` property. 

This means user cannot establish connections/sessions progressively, as he cannot control which device should Appium work with.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.1
* Real device or emulator/simulator: Multi devices, connect to PC one by one.

## Details

If I connect two android device to my computer, and fill `deviceName` with the 2nd serial number I get from `adb devices`, then run the `wdio.remote(opts)`, the 1st device will be invoked.

## Link to Appium logs

Not available.

## Code To Reproduce Issue [ Good To Have ]

Not available.

**Comment by KazuCocoa** [comment]
Did not use `udid`?

**Comment by DevDengChao** [comment]
> Did not use `udid`?

No used, I thought it was iOS UDID before, as the document didn't say much on it.

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-uiautomator2-driver#general

We're working on changing https://appium.io/docs/en/writing-running-appium/caps to be just a pointer to each proper repositories like https://appium.io/docs/en/writing-running-appium/caps/#uiautomator2-only. Let me modify more.
The driver repository is correct for now.

**Comment by DevDengChao** [comment]
Thanks, it works after setup `udid` field.

Maybe there should be a little bit more descriptions for that property on the documents.
