### ISSUE TITLE
WebDriverAgent performance improvement on /wda/touch/perform, open question

### ISSUE THREAD

**Issue by remysabliet** [appium/appium#16230]
## The question

My question concerns WebDriverAgent sub repository.

We are using WebDriverAgent through Device Farmer (STF). And we are having slowness on Scroll/Swipe execution. The purpose is to improve the global execution performance of scroll/swipe.

I found 2 factors related to WebDriverAgent that impact significantly the swiping/scrolling.

**1. Screen streaming**

The screen screaming which is actually the mjpegServer running on port 9100 by default. Just by stoping streaming, subsequently the execution of `wda/touch/perform` is way quicker. 
Are the mjpegServer and the command also running on the same process / sessionId or could those be separated ? 
I know that it is mono-threaded and we can have only one session at a time, but maybe for the screen streaming, Apple let us to make differently (Or not).

**2.  "Requesting snapshot of accessibility hierarchy for app with pid" following every moveTo step of  `/wda/touch/perform`**
When scrolling/ Swipping the `wda/touch/perform` is executed following this pattern:
```
curl -X POST http://localhost:17403/session/B28BF7C6-B74D-4882-B79D-B36F31AF261B/wda/touch/perform \
-H 'content-type: application/json' \
-d '{"actions":[[{"action": "tap","options": { "x": 314.8047105073929, "y": 480.46292304992676 }},
   {"action": "wait","options": { "ms": 89.5 }},
   {"action": "moveTo","options": { "x": 252.25136697292328, "y": 479.13202476501465 }},
   {"action": "wait","options": { "ms": 89.5 }},
   {"action": "moveTo","options": { "x": 252.25136697292328, "y": 700.13202476501465 }},
   {"action": "release","options": { }}
  ]]}' -s -w 'Total: %{time_total}s\n'
```

Every time there is a **moveTo** step, We can see an additional log coming from WDA  which is adding an additional ~50ms latency to the `/wda/touch/perform ` action. (for the case of a Old Iphone 6 Plus)

"Requesting snapshot of accessibility hierarchy for app with pid"

Example of logs: 
```
[DEBUG] Log from wda [STDOUT]     t =  1845.43s Find the Application 'com.google.chrome.ios'
[DEBUG] Log from wda [STDOUT]     t =  1845.43s     Requesting snapshot of accessibility hierarchy for app with pid 6879
[DEBUG] Log from wda [STDOUT]     t =  1845.96s Find the Application 'com.google.chrome.ios'
[DEBUG] Log from wda [STDOUT]     t =  1845.96s     Requesting snapshot of accessibility hierarchy for app with pid 6879

```

**Question:** is there a way for WDA to Skip those "Requesting snapshot of accessibility hierarchy" actions because if we following a complex path with the mouse on the screen to Swipe, we may have 10 **moveTo** steps and if the device is a old one, it would takes **10s** to scroll.

Thank you for your feedback on those

## Environment

* WDA version (or git revision) that exhibits the issue: Not using Appium but WebDriverAgent only: 3.16.0
* Desktop OS/version used to run WDA: MACOS BigSur 11.6
* Node.js version (unless using Appium.app|exe): 12.22.1
* Npm or Yarn package manager: 6.14.12
* Real device or emulator/simulator:IPhone 6 Plus
* Appium CLI or Appium.app|exe: N/A

## Code To Reproduce Issue [ Good To Have ]

**Generate Session ID + Swipe**
`
curl -X POST $JSON_HEADER -d "{\"desiredCapabilities\":{\"bundleId\":\" jp.asurion.hako.nonprod\"}, \"capabilities\":{}}" $DEVICE_URL/session -s -w 'Total: %{time_total}s\n'
`

**Simulating a SWIPE from top to bottom (just updating the y value**
` url -X POST $DEVICE_URL/session/$SESSION_ID/wda/touch/perform   -H 'content-type: application/json'   -d '{"actions":[[{"action": "tap","options": { "x": 314.8047105073929, "y": 480.46292304992676 }},
     {"action": "wait","options": { "ms": 17 }},
     {"action": "moveTo","options": { "x": 252.25136697292328, "y": 479.13202476501465 }},
     {"action": "wait","options": { "ms": 17  }},
     {"action": "release","options": { }}
    ]]}' -s -w 'Total: %{time_total}s\n'
`

**Comment by mykola-mokhnach** [comment]
> Screen streaming

It is running in a separate thread. XCTest does allow some operation to be executed not on the main thread and taking screenshot is one of these. Although, the screenshooting operation is still quite CPU-intensive. Also all screenshot are getting resized by default to reduce their resulting size, which also needs significant CPU power taking into account this is happening at least 10 times per second. Check https://github.com/appium/WebDriverAgent/blob/c7f01c839f9f1284e1319ccce096f6ac96153a40/WebDriverAgentLib/Utilities/FBMjpegServer.m and https://github.com/appium/WebDriverAgent/blob/c7f01c839f9f1284e1319ccce096f6ac96153a40/WebDriverAgentLib/Utilities/FBImageIOScaler.m

> Requesting snapshot of accessibility hierarchy

We cannot change the way gestures are performed. Basically, WDA code is preparing actions chain which is then passed to XCTest for execution. See https://github.com/appium/WebDriverAgent/blob/c7f01c839f9f1284e1319ccce096f6ac96153a40/WebDriverAgentLib/Utilities/FBAppiumActionsSynthesizer.m for more details.

Obviously the way the functionality above is implemented may not be optimal, but this is all we have based on the current XCTest findings on their (undocumented) APIs. We'd be happy to accept any improvements.

**Comment by remysabliet** [comment]
@mykola-mokhnach Thank you all those info, very helpful ;)
