### ISSUE TITLE
Fails to open a new window on mobile Safari

### ISSUE THREAD

**Issue by nkns165** [appium/appium#16239]
## The problem

When clicked an element which opens a new window on mobile safari, only one window handle is returned.
It seems https://github.com/appium/appium/issues/11484 is happening again?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 11.6.1
* Node.js version (unless using Appium.app|exe): 12.13.1
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS 14, iOS 15
* Real device or emulator/simulator: Real device (iPhone 12, iPhone 13)
* Appium CLI or Appium.app|exe: CLI

## Details

Our test goes like this:
- Navigate to `https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_link_target`
- Click home button at the left top (which opens a new window)
- Wait until the number of window handles becomes 2

The test fails due to timeout in waiting the new window handle (only one handle is returned).

- The problem doesn't happen on Android Chrome or other PC browsers.
- We are executing tests on BrowserStack.  Looking at the recorded movie, it looks like as if the new window is actually not opened.  But it's not specific to this site.  On other sites, clicking on a normal link works well, and clicking on a link which opens a new window doesn't work well (click command succeeds, but no new window handle).  Do you have any idea?

## Link to Appium logs

(https://gist.github.com/nkns165/2bbac059d0cd812bd0f2a90bcf51730c)

## Code To Reproduce Issue [ Good To Have ]

```
describe("Open new window", () => {
  it("can assert there are two window handles", async () => {
    await browser.url("https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_link_target");
    const homeButton = await $("#tryhome");
    await homeButton.click(); // new window will be opened

    await browser.waitUntil(async () => ((await browser.getWindowHandles()).length === 2));
  });
});
```

**Comment by KazuCocoa** [comment]
Tried with iOS 14.
The click JS action was sent to the safari, but it seems safari did not click it.
Instead, clicking the tryhome element with `nativeWebTap` settings/capabilities succeeded.
https://github.com/appium/appium-xcuitest-driver


Not mobile Safari, but Desktop Safari also has similar cases. `.click` webdriver endpoint does not work while JS's click action like `arguments[0].click();` works. Not the same, but I guess mobile safari also has similar situation.

**Comment by nkns165** [comment]
Umm, now iOS 14 succeeds and iOS 15 fails.

- Add also `appium:nativeWebTapStrict` -> no luck
- Add some wait before clicking -> no luck

**Comment by KazuCocoa** [comment]
> Add also appium:nativeWebTapStrict -> no luck

This was because the safari tab bar changed the position since iOS 15.
Once you change the tab bar position via the Settings app > Safari, it should work as same as iOS 14.

https://github.com/appium/appium-xcuitest-driver/pull/1361 is to adjust the offset calculation.

**Comment by KazuCocoa** [comment]
XCUITest driver 3.59.0 has the `appium:nativeWebTapStrict` fix for iOS 15.
So far, the native tap is a workaround for Safari env.

**Comment by nkns165** [comment]
What a quick fix, thank you so much.  I will check it out.

**Comment by nkns165** [comment]
Now I was able to click the link with XCUITest driver 3.59.0 & `nativeWebTap`.
Sorry to be late confirmation, thank you so much.
