### ISSUE TITLE
Alert text becomes wrong on mobile Safari of iOS 14

### ISSUE THREAD

**Issue by nkns165** [appium/appium#16236]
## The problem

I tried to assert alert text on mobile Safari, but the text returned from Appium was different from what was actually displayed.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 11.6.1
* Node.js version (unless using Appium.app|exe): 12.13.1
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS 14 (FYI, the problem didn't happen on iOS 13 or iOS 15)
* Real device or emulator/simulator: Real device (iPhone 12)
* Appium CLI or Appium.app|exe: CLI

## Details

Our test goes like this:
- Navigate to https://the-internet.herokuapp.com/javascript_alerts
- Click `Click for JS Alert` button
- Assert the alert text is `I am a JS Alert`

But the last step failed because Appium returns alert message as `I am a JS Alert\nI am a JS Alert`.

- The problem doesn't happen on iOS 13 or iOS 15.
- Accepting the alert works well even on iOS 14.

Capture on BrowserStack:
<img width="367" alt="Screen Shot 2021-12-10 at 9 34 06 AM" src="https://user-images.githubusercontent.com/1135016/145498031-84a88cbd-9c95-4f55-9167-5443146266e3.png">

## Link to Appium logs

(https://gist.github.com/nkns165/eaade92c05337de16a9ef6bf7e21a58d)

## Code To Reproduce Issue [ Good To Have ]

Sorry I've not yet created it, but if necessary I'm pleased to create one.

**Comment by KazuCocoa** [comment]
What's the result of https://github.com/appium/appium-xcuitest-driver#mobile-source with `format: description`?

**Comment by nkns165** [comment]
Please find the attached files.
[iOS 14.4](https://github.com/appium/appium/files/7690009/source_14_4.txt)
[iOS 13.7](https://github.com/appium/appium/files/7690008/source_13_7.txt)

Due to this difference?
- 14.4
```
                          TextView, 0x600000974e00, {{20.0, 383.7}, {350.0, 54.0}}, value: I am a JS Alert
                            TextView, 0x600000974ee0, {{40.0, 399.7}, {109.3, 22.0}}, label: 'I am a JS Alert'
```

- 13.7
```
                          TextView, 0x600004c52220, {{20.0, 301.0}, {335.0, 54.0}}, value: I am a JS Alert
                            StaticText, 0x600004c51dc0, {{40.0, 317.0}, {110.0, 22.0}}, label: 'I am a JS Alert'
```

**Comment by KazuCocoa** [comment]
Yes. Current implementation returns available text on the alert element. (Both are actually alert in this case)
https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/FBAlert.m#L98-L111

**Comment by nkns165** [comment]
Sorry if I'm misunderstanding, but this part is conscious of this issue, isn't it?
```
     if ([parentText isEqualToString:text]) {
        // Avoid duplicated texts on Safari alerts
        return;
      }
```

**Comment by KazuCocoa** [comment]
It depends on the value. The values themselves depend on what value XCTest(iOS) returned as its value/label. Debugging is necessary though.

**Comment by KazuCocoa** [comment]
Hm, i tried the page with an iOS 13 device. The `return` worked on it.

**Comment by KazuCocoa** [comment]
Mm, i also tried an iOS 14.8 real device (iPhone 8). It returned as below.

```
> driver.switch_to.alert.text
=> "I am a JS Alert"
```

As same as https://gist.github.com/nkns165/eaade92c05337de16a9ef6bf7e21a58d, the session was `safari` browserName. The same page and the  same steps to click the "Click for JS Alert".

I guess your case is OS version or model specific one for now..

**Comment by nkns165** [comment]
> I guess your case is OS version or model specific one for now..

Oh, thanks.  Then I'm going to close this issue.
Thank you so much for your quick answer!
