### ISSUE TITLE
Appium Espresso server crashes when:  1. App under test is killed and relaunched using driver.terminateApp(<appPackage>) and driver.activateApp(<appPackage>) 2. Perform upgrade using installApp(<appPath>) command - First installing old version of app under test and then using installApp(<appPath>) command again to install the new version of the app. Then using driver.activateApp(<appPackage>) to launch the app and perform further test

### ISSUE THREAD

**Issue by sonugupta029** [appium/appium#16232]
## The problem

Appium Espresso server crashes when:  
1. App under test is killed and relaunched using driver.terminateApp(<appPackage>) and driver.activateApp(<appPackage>) 2. Perform upgrade using installApp(<appPath>) command - First installing old version of app under test and then using installApp(<appPath>) command again to install the new version of the app. Then using driver.activateApp(<appPackage>) to launch the app and perform further test

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.0
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Mac OS Catalina 10.15.7
* Node.js version (unless using Appium.app|exe): 14.5.0
* Npm or Yarn package manager: 6.14.8
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]
driver.terminateApp(<appPackage>)
driver.activateApp(<appPackage>)
driver.findElement(MobileBy.AndroidViewTag(<view-tag>))

or
installApp(<appPath>)
installApp(<appPath>)
driver.activateApp(<appPackage>)
driver.findElement(MobileBy.AndroidViewTag(<view-tag>))

**Comment by mykola-mokhnach** [comment]
The described behaviour is expected since Espresso server is a part of the tested application. Which means by killing the app one automatically terminates the server.

Closed as not an issue

**Comment by sonugupta029** [comment]
Hi @mykola-mokhnach , Thanks for reverting quickly. Is it expected behaviour for 2nd case as well wherein I am trying to upgrade app using installApp command and then using driver.activateApp command?

**Comment by mykola-mokhnach** [comment]
In order for app to be upgraded the old one must be terminated, so I don't see any diff. Also the new app must also be instrumented. Simply installing it won't help to make that working

**Comment by sonugupta029** [comment]
Ok thanks.
