### ISSUE TITLE
Appium click action does not take effect in subsystem for android on windows 11

### ISSUE THREAD

**Issue by atiasn** [appium/appium#16231]
## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: docker (image: appium/appium)
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:
* Subsystem for android version
![image](https://user-images.githubusercontent.com/25135479/145347793-13ab6791-ba7a-4d26-8af3-1d9b0932c3e0.png)

## Details

Appium click action does not take effect.

And my code (python)
```python
    desired_cap = {
        'platformName': 'Android',
        'platformVersion': '11',
        'deviceName': 'Pixel_5',
        'appPackage': 'com.test.test',
        'appActivity': 'com.test.test.view.activity.SplashActivity',
        'noReset': True, 
        'noSign': True,
        'newCommandTimeout': 3600,
        "automationName": "UiAutomator2",
    }
    app = AuthpointApp('http://10.10.10.11:4723/wd/hub', desired_cap)
    btn = app.driver.find_element(AppiumBy.ID, 'com.test.test/btn_activate')
    print(btn.text)
    btn.click()
```

## Appium and logcat logs
[appium and logcat logs](https://gist.github.com/atiasn/762f71a0df9bb38dbd23bdac1ae43f8a)

**Comment by mykola-mokhnach** [comment]
I can observe the click command is sent, so it must be something in the application under test that does not accept it or trigger an appropriate response to it.

What I would try to mitigate the issue:
- Try to click by coordinates instead
- Enable pointer tracking in the device developer options to see where exactly the click happens
- Enable extended debug logging in the application under test to see how it reacts to that click event

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by jacoballen55** [comment]
@atiasn  did you get this to work? looks like appium send but dosent work with WSA

**Comment by paulps2** [comment]
I also have the same problem. Is anyone able to find a solution?

**Comment by aogg** [comment]
Can appium control wsa's Android app?
