### ISSUE TITLE
Add an option to update Android GPS cache

### ISSUE THREAD

**Issue by MtDeity** [appium/appium#16238]
# The problem

[Get Geolocation](https://appium.io/docs/en/commands/session/geolocation/get-geolocation/) calls [`getLastLocation()`](https://developers.google.com/android/reference/com/google/android/gms/location/FusedLocationProviderClient#getLastLocation()) for Android [here](https://github.com/appium/io.appium.settings/blob/6214c0a74510c3ad5b4bdf0740bb56724622d8e6/app/src/main/java/io/appium/settings/LocationTracker.java#L241-L290). `getLastLocation ()` just returns the best most recent location currently available. It would be useful to add an option to Get Geolocation command (or Set Geolocation) to update Android GPS cache by calling [`FusedLocationProviderClient.getCurrentLocation()`](https://developers.google.com/android/reference/com/google/android/gms/location/FusedLocationProviderClient#getCurrentLocation(int,%20com.google.android.gms.tasks.CancellationToken)) and [`LocationManager.getCurrentLocation()`](https://developer.android.com/reference/kotlin/android/location/LocationManager#getcurrentlocation).

**Comment by mykola-mokhnach** [comment]
I spent some time working on https://github.com/appium/io.appium.settings/pull/76
Although it still does not work as expected for me, at least on emulators. The `getCurrentLocation` never gets a callback in scope of a single broadcast invocation and also background location updates don't seem to work properly. Maybe that code has bugs, so feel free to make your hands dirty and fix it.

**Comment by mykola-mokhnach** [comment]
Published https://github.com/appium/appium-uiautomator2-driver#mobile-refreshgpscache in uia2 driver v 1.74.0

**Comment by MtDeity** [comment]
@mykola-mokhnach
[`addOnCompleteListener()`](https://github.com/appium/io.appium.settings/blob/e41274f63ba90eb1c893d6e50af72906c6f187d4/app/src/main/java/io/appium/settings/LocationTracker.java#L260-L268) after `getCurrentLocation()` doesn't seem to be called yet. 

I have changed getCurrentLocation() and requestLocationUpdates() to be called in the foreground service, but failed to update the GPS cache, even though [CurrentLocationKotlin](https://github.com/android/location-samples/blob/1ea5aff80dbb015fbf306fa89e8fa1ca7b0a9099/CurrentLocationKotlin/app/src/main/java/com/example/android/location/currentlocationkotlin/MainActivity.kt#L158-L180) and other similar apps can update the cache.

**Comment by MtDeity** [comment]
@mykola-mokhnach
Thank you for working on this issue.

[`addOnCompleteListener()`](https://github.com/appium/io.appium.settings/blob/e41274f63ba90eb1c893d6e50af72906c6f187d4/app/src/main/java/io/appium/settings/LocationTracker.java#L260-L268) after `getCurrentLocation()` doesn't seem to be called yet. 

I have changed getCurrentLocation() and requestLocationUpdates() to be called in the foreground service, but failed to update the GPS cache, even though [CurrentLocationKotlin](https://github.com/android/location-samples/blob/1ea5aff80dbb015fbf306fa89e8fa1ca7b0a9099/CurrentLocationKotlin/app/src/main/java/com/example/android/location/currentlocationkotlin/MainActivity.kt#L158-L180) and other similar apps can update the cache.
