### ISSUE TITLE
./Scripts/bootstrap.sh Unknown TARGET

### ISSUE THREAD

**Issue by liang1025** [appium/appium#16233]
[h@deMac webDriverAgent % ./Scripts/build.sh 
+ define_xc_macros
+ XC_MACROS='CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO'
+ case "$TARGET" in
+ echo 'Unknown TARGET'
Unknown TARGET
+ exit 1

The error in re signature compilation is as above. How to solve this problem

**Comment by mykola-mokhnach** [comment]
Please fill out the issue report properly and provide the fill server log. If this is not an issue then please use [Appium forum](https://discuss.appium.io) to ask questions
