### ISSUE TITLE
Page source is slower with excludedAttributes: visible & default XML doesn't show everything

### ISSUE THREAD

**Issue by seanmajorpayne** [appium/appium#16245]
## The problem

In the appium-xcuitest-driver documentation, `XML` is noted to be slower than `description` format for retrieval and it's suggested that using `excludedAttributes: ["visible"]` will "[significantly speed up page source retrieval](https://github.com/appium/appium-xcuitest-driver#:~:text=One%20or%20more%20comma%2Dseparated%20attribute%20names%20to%20be%20excluded%20from%20the%20XML%20output%2C%20thus%20only%20makes%20sense%20if%20format%20is%20set%20to%20xml.%20It%20might%20be%20sometimes%20helpful%20to%20exclude%2C%20for%20example%2C%20the%20visible%20attribute%2C%20to%20significantly%20speed%2Dup%20page%20source%20retrieval.)"

I have tested this across many different applications and notice two (bugs? or unexpected behavior?).

1) Using `XML` without the `excludedAttributes` argument does not return the full page source in many cases.
2) Adding `excludedAttributes: ["visible"]` significantly increases the total number of elements returned and is much slower to execute.

I recorded the average time of 100 page source grabs with the following results. (Note that I did this on multiple pages in different applications with similar results). Here are a couple of sample results:

App 1 (with a google map embedded)
1. `xml` -> ~ .5 seconds
2. `xml + exclude visible` -> Timeout (> 10 seconds)
3. `description` -> ~ 2 seconds
4. `json` -> Timeout (> 10 seconds)

App 2 (with an iOS permission overlay)
1. `xml` -> ~.09 seconds
2. `xml + exclude visible` -> ~.26 seconds
3. `description` -> ~ .76 seconds
4. `json` -> ~ .09 seconds

In all of the tests I ran, `xml` returned significantly less page source than `xml + exclude visible` or `description` format. For the `xml` differences, adding `excludedAttributes: visible` adds up to an additional 50-70 lines of code (~25-35 elements). Is this expected behavior? The `xml + exclude visible` ends up with an equivalent number of elements as the `description` format.

On very simple application pages, all formats average around the same time.

I am using the Ruby commands:

```
@driver.execute_script("mobile: source", { format: "xml" })
@driver.execute_script("mobile: source", { format: "xml", excludedAttributes: ["visible"] })
@driver.execute_script("mobile: source", { format: "description" })
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.0 (Tested with appium-xcuitest-driver 3.43.0 & 3.58.0)
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: macOS Monteray 12.0.1
* Node.js version (unless using Appium.app|exe): 17.0.1
* Npm or Yarn package manager: Npm
* Mobile platform/version under test: iOS 14.4 (iPhone)
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

Not sure if this is a bug, but I will have to comb logs to make sure that there is nothing sensitive. Please let me know if you need logs for this ticket.

## Code To Reproduce Issue [ Good To Have ]

Roughly:

```
@thread = Thread::Mutex.new

...

def with_thread
  @thread.synchronize do
    yield
  end
end

...

(1...100).map do
  before = Time.now
  with_thread { @driver.execute_script("mobile: source", { format: "xml" }) }
  after = Time.now - before
end.sum / 100
```

**Comment by KazuCocoa** [comment]
The slowness itself was expected since Appium/WDA did additional steps to calculate element attributes. The `description` was vanilla debug data by XCTest for debugging, but it could have cases the value was not accurate. XML format was formatted by Appium/WDA, so it took extra time.

Increasing `customSnapshotTimeout` and `snapshotMaxDepth` may help in the missing XML's element tree, but they will increase the time.

**Comment by seanmajorpayne** [comment]
Thank you for the response. Is the appium-xcuitest-driver documentation incorrect when it says that adding `excludedAttributes` will speed things up?

And can you elaborate on what you mean about the value for description having cases where it is not accurate?

I am trying to select the most reliable method for getting the full page source, preferably at the quickest speed possible while retaining all elements.

**Comment by KazuCocoa** [comment]
I thought `excludedAttributes` improved the speed in many cases, especially `excludedAttributes: ["visible"]` since it skips related calculation steps. I tested a couple of apps before on a few real devices I had and simulators.  Then, it improved the speed so much. You might find some GitHub issues that the `excludedAttributes` helped to improve their test apps. 

But it may depend on the app under test as well, of course.

> And can you elaborate on what you mean about the value for description having cases where it is not accurate?

For example, I saw element rect values were incorrect cases. Then, Appium's rects also could be wrong though.
If you'd have liked to use XPath or class chain in iOS, you should check appium's page source basically.

iOS versions, Xcode versions and models like iPhone/iPad might affect the performance. I usually use `appium:useJSONSource` (so, `json` format) in capabilities by default.

**Comment by seanmajorpayne** [comment]
The timeout I was experiencing was actually RubyMine's debugger timeout. I increased the `snapshotMaxDepth` as suggested. Now I've confirmed, the `XML` source and the `XML + excludedAttributes` were the same length in one of the above examples, but excludedAttributes takes around 12 seconds vs. half a second for the xml. I have not seen a performance boost from adding `excludedAttributes` but maybe there are some scenarios where that does provide a benefit.

Can you confirm, is using `appium:useJSONSource` different from running `execute_script("mobile: source", { format: "json" })` ? Because so far, I have seen multiple examples where using the execute_script variant does not produce the full page source when using `json`.

Thank you again for your guidance!

**Comment by mykola-mokhnach** [comment]
As Kazu mentioned the duration may vary depending on the behaviour of the application under test. Basically, the most time-consuming operation is the page source snapshot retrieval. This snapshot is a tree like object with element attributes included and is used to build the actual resulting XML or JSON document. Unfortunately all the downstream stuff there belongs to undocumented/private XCTest APIs, which are also a subject of change from one SDK version to another, but you could try to dig deeper into it yourself: 
- https://github.com/appium/WebDriverAgent/blob/c7f01c839f9f1284e1319ccce096f6ac96153a40/WebDriverAgentLib/Categories/XCUIElement%2BFBUtilities.m
- https://github.com/appium/WebDriverAgent/blob/c7f01c839f9f1284e1319ccce096f6ac96153a40/WebDriverAgentLib/Categories/XCUIApplication%2BFBHelpers.m

The above statement also means we don't know all the details/pitfalls of snapshots taking. The same is true for how exactly the application under test may influence its performance. All current findings there are just results of previous experiments we've collected so far. You are welcome to add more findings on this topic

**Comment by seanmajorpayne** [comment]
Thank you @mykola-mokhnach
Yes, it's always difficult to deal with undocumented code. It's not easy to figure out what is caused by Appium, WDA, XCUITest as a user, so I am trying to understand more and that is helpful.

I am going to rerun the tests with `appium:useJSONSource` and see if my results change.

**Comment by KazuCocoa** [comment]
> Can you confirm,...

Yes. The difference is where the result converts to XML to the client, in Appium/WDA (ObjecC on iPhone/iPad) or in xcuitest-driver (NodeJS on the host machine). `appium:useJSONSource` passes the JSON tree in WDA to the xcuitest-driver (NodeJS). It converts the tree to XML and responds to the client.

**Comment by seanmajorpayne** [comment]
Thank you!

**Comment by KazuCocoa** [comment]
Close since current behavior is expected.
(Feel free to comment in this thread if needed)
