### ISSUE TITLE
start_recording_screen method on android without audio

### ISSUE THREAD

**Issue by blog4me** [appium/appium#16240]
## The problem

Hi, I'm trying to use appium to capture a 10 seconds video, the format of that video is mp4. After that, I played it on my computer found out that video had no audio, can you tell me how to get a video with audio using appium? 

## Environment

* Appium version (or git revision) that exhibits the issue:
v1.21.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
ubuntu 20.04.2
* Node.js version (unless using Appium.app|exe):
v14.17.3
* Npm or Yarn package manager:
* Mobile platform/version under test:
android 10

**Comment by mykola-mokhnach** [comment]
It is working as designed. Android does not provide any APIs to access device's audio stream
