### ISSUE TITLE
Issue with iOS 15.* Live Text

### ISSUE THREAD

**Issue by aryahya** [appium/appium#16243]
## The problem

After upgrading to iOS 15 tapping on any image/button that contains text selects the text in the image rather than tapping on it. The problem did not occur before on iOS 14. Is there a workaround for this? Can Live Text be disabled on the targeted device from Appium?
I am tapping on the below web element rather than clicking to avoid `SecurityError: Blocked a frame with origin from accessing a cross-origin frame`.
![image](https://user-images.githubusercontent.com/7752371/145690010-8e3a98fa-eb73-4ec9-9122-5a7557aeb239.png)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.0
* Last Appium version that did not exhibit the issue (if applicable): 1.21.0
* Desktop OS/version used to run Appium: Cloud execution (SauceLabs)
* Mobile platform/version under test: 15.*
* Real device or emulator/simulator: Real device

**Comment by mykola-mokhnach** [comment]
We did not apply any changes to the clicking logic. I assume this might be a new XCTest behaviour which only Apple is able to change

**Comment by StephanB75** [comment]
@aryahya 
I have a similar problem with an image button, which does not recognize the click.
Tried several different locator strategies, but finding the element worked correctly.
Finally i tried to click not in the middle of the found elment and that worked.

For me the solution was to find the element, get the dimensions and click on a specific position
`
WebElement elem = findElementBy....("your locator");

	    int width = elem.getSize().getWidth();
	    int height = elem.getSize().getHeight();
	    int startX = elem.getRect().getX();
	    int startY = elem.getRect().getY();
            int widthOffset,startY = your_widthOfffset;
            int widthOffset,startY = your_heightOffset;

	TouchAction action = new TouchAction(driver);
    	action.press(point(startX+widthOffset,startY+heightOffset)).release().perform();`

**Comment by aryahya** [comment]
@StephanB75 Unfortunately, I tried, and tapping with an offset did not work in my case.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
