### ISSUE TITLE
Bad parameters: BadParametersError: Parameters were incorrect. We wanted "MJSONWP protocol requires type and ms" and you sent {"implicit":10000}

### ISSUE THREAD

**Issue by aknurshy** [appium/appium#16247]
## The problem

Hello!
I changed the laptop, installed everything as it was on the previous laptop.
Written tests are Python, used the latest version of Appium Desktop. 
However, after changing my device, when comes the row of code:
_self.driver.implicitly_wait(10)_
I get this error:
_Bad parameters: BadParametersError: Parameters were incorrect. We wanted "MJSONWP protocol requires type and ms" and you sent {"implicit":10000}_

Another code works fine.
## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 1.22.0
* Node.js version (unless using Appium.app|exe): 8.1.2
* Npm or Yarn package manager:
* Mobile platform/version under test: Android 11.0
* Real device or emulator/simulator: Android 11.0
* Appium CLI or Appium.app|exe: 

## Link to Appium logs

https://gist.github.com/aknurshy/0eeffd4a3ad1c9da5226453b1d8f5dd6

**Comment by mykola-mokhnach** [comment]
> [debug] [BaseDriver]   "fullReset": "False",
> [Appium] Could not parse fixed W3C capabilities: 'fullReset' must be of type boolean. Falling back to JSONWP protocol

I assume the error message is pretty clear. Change the capability value to a boolean one instead of a string.

**Comment by aknurshy** [comment]
I didn't notice it.
Thank you @mykola-mokhnach!
