### ISSUE TITLE
Unable to locate elements in second webview Appium C#

### ISSUE THREAD

**Issue by Keerthanashanty** [appium/appium#16248]
Hi,

I am working on automating an android application. The first page is a webview and second page is also a webview.
I am able to locate the elements in first webview.
But when I try to locate elements in second webview, I am getting the error :  elementNotVisible.

Upon opening the application, it is showing a webpage where I should click one button. It will open another page with a form. I am able to click the first button. But when the second page is loaded, I am unable to locate any elements in the second page.

Can anyone help me to resolve this issue please? I am stuck with my automation.

Appium version :  1.22.1 (CLI)
System : Windows 10
Device :  Android api 29 - Emulator

Error : ElementNotVisible Exception

Code that I used to switch to first webview.

var appPath = SetPath() + @"\Configuration\app-qa-release.apk";
            var driverOptions = new AppiumOptions();
            driverOptions.AddAdditionalCapability(MobileCapabilityType.PlatformName, "Android");
            driverOptions.AddAdditionalCapability(MobileCapabilityType.DeviceName, "Pixel 4 XL 29");
            driverOptions.AddAdditionalCapability(MobileCapabilityType.PlatformVersion, "11");
            driverOptions.AddAdditionalCapability(MobileCapabilityType.App, appPath);
            driverOptions.AddAdditionalCapability(MobileCapabilityType.AutomationName, AutomationName.AndroidUIAutomator2);

            driverOptions.AddAdditionalCapability("chromedriverExecutable", SetPath()+ @"\Configuration\chromedriver.exe");

            _driver = new AndroidDriver<AndroidElement>(new Uri("http://localhost:4723/wd/hub"), driverOptions);

 var contexts = _driver.Contexts;

            for (int i = 0; i < contexts.Count; i++)
            {
                Console.WriteLine(contexts[i]);
                if (contexts[i].Contains("WEBVIEW"))
                {
                    _driver.Context = contexts[i];
                    break;
                }
            }

The installed version of chromedriver in the emulator is 74.

**Comment by mykola-mokhnach** [comment]
Please fill out the issue report properly and provide the requested infromation

**Comment by Keerthanashanty** [comment]
Updated the report

**Comment by mykola-mokhnach** [comment]
Please also provide the Appium server log

**Comment by mykola-mokhnach** [comment]
Closed because of no response
