### ISSUE TITLE
Appium 1.22.1+ WDA seems to crash when hitting any endpoint in a moment when animation appears on a page

### ISSUE THREAD

**Issue by Doroshchuk** [appium/appium#16257]
## The problem

I am getting hanged sessions from Appium when calling click()/.Displayed/or just executeScript on an element in a moment when animation appears on a page or even without any visible reason. Wda doesn`t return any response, Appium starts to loop with "[debug] [XCUITest] Setting custom timeout to 60000 ms for 'getAlertText' command" and test fails with "[debug] [XCUITest] Setting custom timeout to 60000 ms for 'getAlertText' command" exception.

## Environment

Use Sauce Labs platform for test execution.

Appium version (or git revision) that exhibits the issue: 1.22.1
Desktop OS/version used to run Appium: NA
Node.js version (unless using Appium.app|exe): NA
Npm or Yarn package manager: NA
Mobile platform/version under test: iOS15.1
Real device or emulator/simulator: Real Device
Appium CLI or Appium.app|exe: NA

## Details

Tried to investigate this issue by myself and added executing js script "return document.readyState" to compare it with "complete" before calling the commands as discussed at https://github.com/appium/appium/issues/16016. But unfortunately, it doesn`t help and I still face the same error on different steps in a test. 

## Link to Appium logs

https://gist.github.com/Doroshchuk/17244c1fdb1462e1cd644811cbcb0816

**Comment by mykola-mokhnach** [comment]
Please review the attached gist as it contains your secret access key

**Comment by Doroshchuk** [comment]
> Please review the attached gist as it contains your secret access key

oh, thanks! removed all mentions now

**Comment by mykola-mokhnach** [comment]
According to the attached log the script does not get any response from the recent executeScript command and times out. Alerts check is expected. See https://github.com/appium/appium/issues/16222 for more details.

**Comment by eglitise** [comment]
Closing this as the issue relates to Appium 1, which is no longer supported. Please open a new issue if this is still reproducible with Appium 2.
