### ISSUE TITLE
iOS testing fails to delete the session after taking a screenshot

### ISSUE THREAD

**Issue by earlif** [appium/appium#16250]
## The problem

iOS testing fails to delete the session after taking a screenshot.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MAC 12.0.1
* Node.js version (unless using Appium.app|exe):16.10.0
* Npm or Yarn package manager: npm 7.24.0
* Mobile platform/version under test: iOS 14.3
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

I am using java to test APP on iOS. And after calling 
File screenFile = driver.getScreenshotAs(OutputType.FILE);
to take screenshot, it fails to quit the driver
driver.quit();
And it is due to the: Cannot read properties of null (reading 'webDriverAgentUrl').

## Link to Appium logs

I am newer on Appium, and I not able to get the logs on Java.

**Comment by mykola-mokhnach** [comment]
Please provide the full server log. We cannot help nothing without it

**Comment by mykola-mokhnach** [comment]
Closed because of no response
