### ISSUE TITLE
Add xcuitest 3.55.1 to 1.23 beta

### ISSUE THREAD

**Issue by ddaypunk** [appium/appium#16259]
## The problem

Currently, we are unable to run tests that target another environment via the processArgs. It looks like this was broken in XCUITest and then fixed in their 3.55.1 build per https://github.com/appium/appium-xcuitest-driver/pull/1344

## Environment

* Appium version (or git revision) that exhibits the issue: 1.23 beta
* Last Appium version that did not exhibit the issue (if applicable): unknown, prior to 1.22.0
* Desktop OS/version used to run Appium: 1.22.0
* Node.js version (unless using Appium.app|exe): using app, but when on CLI using Node 12
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS 14.3, iOS 15.0 both tried
* Real device or emulator/simulator: sim
* Appium CLI or Appium.app|exe: Desktop app 1.22.0 and CLI 1.23.0 beta

## Details

We are providing the following processArg to the app at runtime, and the environment is not changed when we are in debug mode and able to check the sim settings for the app.

"arguments":["-environment","wiremocks"]

## Link to Appium logs

https://github.com/appium/appium-xcuitest-driver/pull/1344

**Comment by KazuCocoa** [comment]
In beta, you can install latest version by uninstalling/installing once since beta does not restrict versions by npm-shrinkwrap.json like stable released versions.
Could you uninstall your beta once?

**Comment by KazuCocoa** [comment]
Please try out re-installation once

**Comment by ddaypunk** [comment]
Okay @KazuCocoa I `npm uninstall -g appium` and then `npm install -g appium@beta` again. Is that what you meant?

**Comment by KazuCocoa** [comment]
yes. Then, the node_modules should get newer versions.

**Comment by ddaypunk** [comment]
It did not work for me. I also pulled 1.22.2 rc, built locally (after appium-doctor --dev setup), and ran with node. I see it pulling the new xcuitest version as expected, but it is still not picking up the arguments I am sending to the app:

`String createProcessArgsList(String env) {
    List<String> processArgs = new ArrayList<>(Arrays.asList("-environment", "${env}" as String))
    final JSONObject argsValue = new JSONObject()
    argsValue.put("args", processArgs)
    return argsValue.toString()
}`

**Comment by KazuCocoa** [comment]
I checked quickly. The below lines had expected launching/environment arguments. After `[app launch]` line also returned `launchArguments` as `app. launchArguments` and `app. launchEnvironment`. 

https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/WebDriverAgentLib/Commands/FBSessionCommands.m#L118-L119

But get app info did not. I'll take a look later, but potentially we no longer can get launching arg/env after getting a running process as 
https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/WebDriverAgentLib/Commands/FBCustomCommands.m#L175
https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/WebDriverAgentLib/Commands/FBCustomCommands.m#L206-L218

**Comment by ddaypunk** [comment]
Sounds good, thank you for looking into this!

**Comment by KazuCocoa** [comment]
It looked like the arguments/environments worked. I tested a simple app to check the behavior, so I guess apple restricted the behavior to get them.
