### ISSUE TITLE
Got Issue During Run Appium for real device.

### ISSUE THREAD

**Issue by PARIPATEL1988** [appium/appium#16251]
## The problem

I have connected my device It is connected but program is not running,& found some errors no idea how to resolve it I have Installed SDK tools using Node.js & didnt get tools folder in that only got Platform tools then I got error so I downloaded tools & put in my folder & gave path but still not able to run program.

## Environment

* Appium version (or git revision) that exhibits the issue:App Version 1.20.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:Windows 10
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:Android 7
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

Environment for system variables
ANDROID_HOME
C:\Users\XYZ\Desktop\Android-SDKTools
JAVA_HOME
C:\Program Files\Java\jdk1.8.0_311
PATH
%JAVA_HOME%\bin;%ANDROID_HOME%\platform-tools;%ANDROID_HOME%\tools\lib

## Link to Appium logs

Running 'C:\Users\XYZ\Desktop\Android-SDKTools\platform-tools\adb.exe -P 5037 -s 03157df3442b1b0f forward tcp:8200 tcp:6790'
[ADB] Getting install status for io.appium.uiautomator2.server
[ADB] Running 'C:\Users\XYZ\Desktop\Android-SDKTools\platform-tools\adb.exe -P 5037 -s 03157df3442b1b0f shell dumpsys package io.appium.uiautomator2.server'
[ADB] 'io.appium.uiautomator2.server' is installed
[ADB] Getting package info for 'io.appium.uiautomator2.server'
[ADB] Running 'C:\Users\XYZ\Desktop\Android-SDKTools\platform-tools\adb.exe -P 5037 -s 03157df3442b1b0f shell dumpsys package io.appium.uiautomator2.server'
[ADB] The version name of the installed 'io.appium.uiautomator2.server' is greater or equal to the application version name ('4.17.4' >= '4.17.4')
[UiAutomator2] io.appium.uiautomator2.server installation state: sameVersionInstalled
[ADB] Checking app cert for C:\Users\XYZ\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.17.4.apk
[UiAutomator2] Deleting UiAutomator2 session
[UiAutomator2] Deleting UiAutomator2 server session
[WD Proxy] Matched '/' to command name 'deleteSession'
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
[ADB] Running 'C:\Users\XYZ\Desktop\Android-SDKTools\platform-tools\adb.exe -P 5037 -s 03157df3442b1b0f shell am force-stop com.sec.android.app.popupcalculator'
[Logcat] Stopping logcat capture
[ADB] Removing forwarded port socket connection: 8200 
[ADB] Running 'C:\Users\XYZ\Desktop\Android-SDKTools\platform-tools\adb.exe -P 5037 -s 03157df3442b1b0f forward --remove tcp:8200'
[BaseDriver] Event 'newSessionStarted' logged at 1639554091325 (13:11:31 GMT+0530 (India Standard Time))
[W3C] Encountered internal error running command: Error: Cannot verify the signature of 'C:\Users\XYZ\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.17.4.apk'. Original error: Could not find 'apksigner.jar' in ["C:\\Users\\XYZ\\Desktop\\Android-SDKTools\\platform-tools\\apksigner.jar","C:\\Users\\Shiv lab\\Desktop\\Android-SDKTools\\emulator\\apksigner.jar","C:\\Users\\XYZ\\Desktop\\Android-SDKTools\\cmdline-tools\\latest\\bin\\apksigner.jar","C:\\Users\\XYZ\\Desktop\\Android-SDKTools\\tools\\apksigner.jar","C:\\Users\\XYZ\\Desktop\\Android-SDKTools\\tools\\bin\\apksigner.jar","C:\\Users\\XYZ\\Desktop\\Android-SDKTools\\apksigner.jar"]. Do you have Android Build Tools installed at 'C:\Users\XYZ\Desktop\Android-SDKTools'?
[W3C]     at ADB.checkApkCert (C:\Users\XYZ\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\apk-signing.js:270:11)
[HTTP] <-- POST /wd/hub/session 500 17268 ms - 2433

## Code To Reproduce Issue [ Good To Have ]

public class Appium_Test1 {

	 static AppiumDriver<MobileElement> driver;
	
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		try {
			System.out.println("done...");
			opencalculator();
		} catch (MalformedURLException e) {
			// TODO Auto-generated catch block
			System.out.println("not done...");
			System.out.println(e.getCause());
			System.out.println(e.getMessage());
			e.printStackTrace();
		}
}
	public static void opencalculator() throws MalformedURLException {
		DesiredCapabilities cap = new DesiredCapabilities();
		System.out.println("Application started1...");
		cap.setCapability("deviceName", "ABCD(added just for example)");
		System.out.println("Application started2...");
		cap.setCapability("udid", "01234568790000(added just for example)");
		System.out.println("Application started3...");
		cap.setCapability("platformName", "Android");
		System.out.println("Application started4...");
		cap.setCapability("platformVersion", "7");
		System.out.println("Application started5...");
		cap.setCapability("appPackage", "com.sec.android.app.popupcalculator");
		System.out.println("Application started6...");
		cap.setCapability("appActivity", "com.sec.android.app.popupcalculator.Calculator");
		System.out.println("Application started7...");
		URL url = new URL("http://127.0.0.1:4723/wd/hub");
		System.out.println("Application started8...");
		driver = new AppiumDriver<MobileElement>(url,cap);	
		System.out.println("Finally started...:)");	
	}
}

**Comment by mykola-mokhnach** [comment]
Make sure that Android Build Tools v 24.0.3 or greater are installed, and located in a proper place. See https://stackoverflow.com/questions/40004884/cant-find-apksigner-executable-to-manually-sign-apk for more details.

**Comment by PARIPATEL1988** [comment]
Still getting error...please check..
Checking app cert for C:\Users\xyz\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.17.4.apk
[ADB] Using 'apksigner.jar' from 'C:\Users\xyz\Desktop\Android-SDKTools\platform-tools\apksigner.jar'
[ADB] Starting apksigner: 'C:\\Program Files\\Java\\jdk1.8.0_311\\bin\\java.exe' -Xmx1024M -Xss1m -jar 'C:\\Users\\xyz\\Desktop\\Android-SDKTools\\platform-tools\\apksigner.jar' verify --print-certs 'C:\\Users\\xyz\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v4.17.4.apk'
[ADB] 'C:\Users\xyz\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.17.4.apk' is not signed
[UiAutomator2] Deleting UiAutomator2 session
[UiAutomator2] Deleting UiAutomator2 server session
[WD Proxy] Matched '/' to command name 'deleteSession'
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
[ADB] Running 'C:\Users\xyz\Desktop\Android-SDKTools\platform-tools\adb.exe -P 5037 -s 03157df3442b1b0f shell am force-stop com.sec.android.app.popupcalculator'
[Logcat] Stopping logcat capture
[ADB] Removing forwarded port socket connection: 8200 
[ADB] Running 'C:\Users\xyz\Desktop\Android-SDKTools\platform-tools\adb.exe -P 5037 -s 03157df3442b1b0f forward --remove tcp:8200'
[BaseDriver] Event 'newSessionStarted' logged at 1639637490464 (12:21:30 GMT+0530 (India Standard Time))
[W3C] Encountered internal error running command: Error: Could not find 'zipalign.exe' in ["C:\\Users\\xyz\\Desktop\\Android-SDKTools\\platform-tools\\zipalign.exe","C:\\Users\\xyz\\Desktop\\Android-SDKTools\\emulator\\zipalign.exe","C:\\Users\\xyz\\Desktop\\Android-SDKTools\\cmdline-tools\\latest\\bin\\zipalign.exe","C:\\Users\\xyz\\Desktop\\Android-SDKTools\\tools\\zipalign.exe","C:\\Users\\xyz\\Desktop\\Android-SDKTools\\tools\\bin\\zipalign.exe","C:\\Users\\xyz\\Desktop\\Android-SDKTools\\zipalign.exe"]. Do you have Android Build Tools installed at 'C:\Users\xyz\Desktop\Android-SDKTools'?
[W3C]     at ADB.getBinaryFromSdkRoot (C:\Users\xyz\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:125:11)
[W3C]     at ADB.getSdkBinaryPath (C:\Users\xyz\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:44:10)
[W3C]     at ADB.initZipAlign (C:\Users\xyz\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\adb-commands.js:114:3)
[W3C]     at ADB.zipAlignApk (C:\Users\xyz\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\apk-signing.js:180:3)
[W3C]     at ADB.sign (C:\Users\xyz\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\apk-signing.js:162:3)
[W3C]     at Object.helpers.signApp (C:\Users\xyz\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\helpers.js:41:3)
[W3C]     at UiAutomator2Server.installServerApk (C:\Users\xyz\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\uiautomator2.js:117:11)
[W3C]     at AndroidUiautomator2Driver.initUiAutomator2Server (C:\Users\xyz\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:485:7)
[W3C]     at AndroidUiautomator2Driver.startUiAutomator2Session (C:\Users\xyz\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:379:5)
[W3C]     at AndroidUiautomator2Driver.createSession (C:\Users\xyz\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:224:7)
[W3C]     at AppiumDriver.createSession (C:\Users\xyz\AppData\Local\Programs\Appium\resources\app\node_modules\appium\lib\appium.js:371:35)
[HTTP] <-- POST /wd/hub/session 500 3272 ms - 1959
[HTTP]

**Comment by jlipps** [comment]
is zipalign.exe in any of these paths?

"C:\Users\xyz\Desktop\Android-SDKTools\platform-tools\zipalign.exe","C:\Users\xyz\Desktop\Android-SDKTools\emulator\zipalign.exe","C:\Users\xyz\Desktop\Android-SDKTools\cmdline-tools\latest\bin\zipalign.exe","C:\Users\xyz\Desktop\Android-SDKTools\tools\zipalign.exe","C:\Users\xyz\Desktop\Android-SDKTools\tools\bin\zipalign.exe","C:\Users\xyz\Desktop\Android-SDKTools\zipalign.exe"

**Comment by mykola-mokhnach** [comment]
Please make sure that Android SDK is properly installed locally. Closing as not an Appium issue

**Comment by PARIPATEL1988** [comment]
> is zipalign.exe in any of these paths?
> 
> "C:\Users\xyz\Desktop\Android-SDKTools\platform-tools\zipalign.exe","C:\Users\xyz\Desktop\Android-SDKTools\emulator\zipalign.exe","C:\Users\xyz\Desktop\Android-SDKTools\cmdline-tools\latest\bin\zipalign.exe","C:\Users\xyz\Desktop\Android-SDKTools\tools\zipalign.exe","C:\Users\xyz\Desktop\Android-SDKTools\tools\bin\zipalign.exe","C:\Users\xyz\Desktop\Android-SDKTools\zipalign.exe"

Thank you got it & it worked:)
