### ISSUE TITLE
Appium is unable to find the element in a page if there are many records in the list view. (iOS application)

### ISSUE THREAD

**Issue by PrudhviU** [appium/appium#16265]
## Problem

Appium is unable to identify element in a page if there are too many records present in the list view.

## Environment

* All Appium versions - Able to reproduce this issue
* iOS Application - iOS 15, iOS 14.6

## Details

For the same page if the no of records in the page are low i am able to perform actions on the web element. If the record count is too high then getting no such element exception.

## Link to Appium logs
(https://gist.github.com/PrudhviU/f3e88b51ca54cbbfcc62c99d9839ad21)

Note : Perfecto is using some custom code to overcome the issue which i am reporting. Following is the link of their implementation.

https://help.perfecto.io/perfecto-help/content/perfecto/legacy/legacy___ios_object_tree_optimization.htm

With their implementation i am not seeing the issue. But since its a paid tool I am looking for solution here.

**Comment by mykola-mokhnach** [comment]
Element location is based on XCTest, so there's not much there that could be done from Appium side. You are welcome to push a PR to https://github.com/appium/WebDriverAgent if there is a known workaround for this issue

**Comment by PrudhviU** [comment]
As mentioned above Perfecto is able to handle this. Cant this be replicated by Appium team ? I feel this feature will be really useful.

**Comment by mykola-mokhnach** [comment]
> Cant this be replicated by Appium team ? 

I'm not quite sure what exactly to replicate. Perfecto is a commercial company and it is only up to them whether to publish their solutions or to keep them private and under which software license.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by jlipps** [comment]
Last I heard, Perfecto's Appium isn't even the same as open-source Appium, so it's unclear whether the strategy they've found to make things work would even be possible with WDA.
