### ISSUE TITLE
Locator Strategy 'android uiautomator' is not supported for this session

### ISSUE THREAD

**Issue by DevDengChao** [appium/appium#16261]
## The problem

I'm starting a session with `'appium:automationName': 'UiAutomator2'`, and trying to find an element by text like:
```js
device.findElement('android uiautomator', 'new UiSelector().text("example")');
```

Then it told me `InvalidSelectorError: Locator Strategy 'android uiautomator' is not supported for this session`.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.1, with appium-uiautomator2-driver 1.73.0
* Last Appium version that did not exhibit the issue (if applicable): not tested
* Desktop OS/version used to run Appium: not related
* Node.js version (unless using Appium.app|exe): not related
* Npm or Yarn package manager: not related
* Mobile platform/version under test: not related
* Real device or emulator/simulator: not related
* Appium CLI or Appium.app|exe: not related

## Details

I'm not certain if the document is missing a `-` in front of `android uiautomator` or it is intented.

I found `android uiautomator` from https://github.com/appium/appium-uiautomator2-driver#element-location, but after look around the source code, I found [`-android uiautomator` listed in the this.locatorStrategies and other places](https://github.com/appium/appium-uiautomator2-driver/blob/master/lib/driver.js#L160).
(I was pretend to create a PR to remove the strange `-` from `-android uiautomator` then stopped as I found it appares not only in the driver.js .)

## Link to Appium logs

Not related.

## Code To Reproduce Issue [ Good To Have ]

Just look at the readme.md and the implementation in [appium/appium-uiautomator2-driver](https://github.com/appium/appium-uiautomator2-driver) is enough.

**Comment by KazuCocoa** [comment]
Thank you. `-` is necessary then. The readme is wrong. => https://github.com/appium/appium-uiautomator2-driver/pull/484
