### ISSUE TITLE
[15.x iOS] [WebDriverAgent] Large text input causes iOS crash

### ISSUE THREAD

**Issue by alei01** [appium/appium#16266]
## The problem
Large text input causes iOS crash

## Environment
* Appium version (or git revision) that exhibits the issue: 1.21.1, beta
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: macOS Monterey 12.0.1 (21A559)
* Node.js version (unless using Appium.app|exe): v17.0.1
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS 15.1, 15.2
* Real device or emulator/simulator: real
* Appium CLI or Appium.app|exe: cli

## Details
Prerequisites: 
- Reproduce rate: 100%
- Affected version: 15.1, 15.2
- Not reproducing with: 14.7.1

Steps to reproduce:
1. Enter text into any text field in the app
2. Pay attention to text type speed
3. Wait until text input speed became slower 
4. Wait until text stopped to type
5. Observe the iOS device logs

Actual result:
First ±9000 symbols are typed with the same frequency, but after, the typing speed becomes slower and slower.
At about 15000 symbol application and iOS UI crashed with the next stack trace in the device logs:
```
Dec 15 11:27:27 kernel[0] <Notice>: process backboardd[64] caught allocating too many mach ports. 	    
Num of ports allocated 137898; 
```

Notes: 
1. This issue is reproducing not only with large text, but it could be also reproducing if typing the short texts in the different text fields during the long test sessions.  
2. Using the new WebDriverAgent before each test also didn't help. 
3. Issue was also reproduced with simple iOS application with only text field

## Link to Appium logs
[GIST](https://gist.github.com/alei01/e11459d58a955bef35d8a7ea9b94ddf3) 

## Link to iOS device logs
[GIST](https://gist.github.com/alei01/7c8be38592dd9b0c628ed1fac186bbde)

**Comment by mykola-mokhnach** [comment]
Are you able to reproduce this issue using a vanilla XCTest script?

**Comment by alei01** [comment]
The issue is also reproducing with a simple test:
https://github.com/alei01/ios-text-input-sample-test/blob/main/myappUITests/myappUITests.swift

Going to test the same with the latest 15.3 beta iOS

**Comment by alei01** [comment]
The issue is also reproducing with 15.3 beta (19D5026g) 
I will report the ticket to the Apple

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
