### ISSUE TITLE
close_app method doesn't close application

### ISSUE THREAD

**Issue by pcreep42** [appium/appium#16260]
## close_app method doesn't close application

close_app method doesn't close application on version 1.22, but on 1.21 does
## Environment

* 1.22.0
* 1.21.0
* MAC OS BigSur
* Node.js version v14.17.0
* Npm
* iOS 14.0
* Real device. Browserstack
* Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
<script src="https://gist.github.com/pcreep42/e2cfb6d1fbb0754b186dc6e534b41732.js"></script>

## Code To Reproduce Issue
self.driver.close_app()

**Comment by KazuCocoa** [comment]
I wondoer https://github.com/appium/appium/blob/master/CHANGELOG.md#changes-in-version-1220-from-1210 (https://github.com/appium/appium-xcuitest-driver/pull/1314) affects it since you set noReset as true.

> appium:forceAppLaunch to launch the application under test forcefully with appium:bundleId. Defaults to true unless noReset capability is set to true. appium-xcuitest-driver#1314

What about adding `appium:shouldTerminateApp` as `true`?

**Comment by mykola-mokhnach** [comment]
The above API is going to be [deprecated and removed](https://github.com/appium/appium/issues/15807). Consider replacing its usage in your client code.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
