### ISSUE TITLE
Question: Is there a built in way to deal with different screen sizes?

### ISSUE THREAD

**Issue by seanmajorpayne** [appium/appium#16264]
## The problem

I am trying to run tests on different iPhone versions, but the X, Y viewport coordinates differ slightly between iPhone models. Is there built in support to auto-scale viewport coordinates from one device to another or would this need to be coded from scratch?

I have reviewed the documentation, but I don't see anything.

**Comment by StephanB75** [comment]
When I have to use pixel coordinates than i try to work with relative coordinates and calculating it on base of the screen width and height.

this can be retrieved by
deviceWidth = driver.manage().window().getSize().width;
deviceHeight = driver.manage().window().getSize().height;

**Comment by mykola-mokhnach** [comment]
Appium does not do any assumptions about the device screen sizes. All that logic is expected to be implemented by the client side

**Comment by jlipps** [comment]
@StephanB75 is right. It's recommended to never use hard-coded pixel values in your test scripts as this will obviously not be portable based on screen size differences. If you can assume roughly the same layout across screen sizes, then working with percentages and only using calculated pixel values is the way to go.
