### ISSUE TITLE
Android test: Could not proxy command to remote server. Original error: Error: socket hang up

### ISSUE THREAD

**Issue by youngfreeFJS** [appium/appium#16274]
Appium log: https://gist.github.com/youngfreeFJS/d5b125081c6aa2b0fd4843c4481eb5cf

Android logcat: https://gist.github.com/youngfreeFJS/7a1e31b29de7a2b12a144bd3b06711f4

**Comment by Hamzastreamwide** [comment]
adb uninstall io.appium.uiautomator2.server 
adb uninstall io.appium.uiautomator2.server.test 

try this

**Comment by KazuCocoa** [comment]
I guess the system killed the appium process.
Could you fill out the issue template with the full log?

**Comment by mykola-mokhnach** [comment]
> Fri Dec 24 14:14:56 CST 2021 12-24 14:14:57.317  1335  7031 I ActivityManager: Killing 6211:io.appium.uiautomator2.server/u0a66 (adj 0): stop io.appium.uiautomator2.server
> Fri Dec 24 14:14:56 CST 2021 12-24 14:14:57.317  1335  7141 W Binder  : Outgoing transactions from this process must be FLAG_ONEWAY
> Fri Dec 24 14:14:56 CST 2021 12-24 14:14:57.317  1335  7141 W Binder  : java.lang.Throwable
> Fri Dec 24 14:14:56 CST 2021 12-24 14:14:57.317  1335  7141 W Binder  : 	at android.os.BinderProxy.transact(Binder.java:1114)
> Fri Dec 24 14:14:56 CST 2021 12-24 14:14:57.317  1335  7141 W Binder  : 	at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:164)
> Fri Dec 24 14:14:56 CST 2021 12-24 14:14:57.317  1335  7141 W Binder  : 	at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)


The exception in the attached logcat looks like a system one. Not sure there is anything to do from Appium side there.

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by mannyonfire** [comment]
> adb uninstall io.appium.uiautomator2.server adb uninstall io.appium.uiautomator2.server.test
> 
> try this

Solved my problem, but still dont know why.
