### ISSUE TITLE
Element.getScreenshotAs() results in strange behavior within Android Cordova Hybrid Webview

### ISSUE THREAD

**Issue by avenstewart** [appium/appium#16278]
## The problem

Calling the Element.getScreenshotAs() method when testing a Cordova hybrid Webview app produces a successful element screenshot, but results in bizarre momentary deforming of the application UI each time it is called. This behavior will sometimes result in a continuous ("frozen") bug state, with complete inability of a user to visualize or manually interact with the UI of the application while the test in running - however, the Appium session is able to interact with the app uninterrupted while in this state, and tests themselves are unaffected.

I am unable to upload a video of this behavior, but here are single frames from a recording of the issue. 

<img width="413" alt="Screen Shot 2021-12-27 at 4 28 26 PM" src="https://user-images.githubusercontent.com/6175652/147511187-a452af3d-b121-4906-a776-16654becb0a1.png">

<img width="413" alt="Screen Shot 2021-12-27 at 4 28 44 PM" src="https://user-images.githubusercontent.com/6175652/147511342-d10c61b4-3b92-4209-855c-48b66835c843.png">

This issue does not break tests, but often results in an unusable screen recording.

## Environment

* Appium version (or git revision) that exhibits the issue: CLI 1.22.2, GUI 1.22.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Mac OS 11.5.2, Ubuntu 20.04
* Node.js version (unless using Appium.app|exe): 14.17.1
* Npm or Yarn package manager: npm 6.14.13
* Mobile platform/version under test: Android 9
* Real device or emulator/simulator: Real device, Samsung Galaxy Note 10
* Appium CLI or Appium.app|exe: Both CLI and GUI server

## Link to Appium logs

https://gist.github.com/avenstewart/f6adde47dd50bc916e7f10b2fc648380

## Code To Reproduce Issue [ Good To Have ]

Only tested in Java at this time.

element Obj is WebElement type
`File sourceFile = element.getScreenshotAs(OutputType.FILE);`

**Comment by KazuCocoa** [comment]
mm, as appium, the behavior depends on chromedriver and its WebView.
So I guess chromedriver or the WebView behaved so. (Or the Cordova implementation affects them)

```
[debug] [35m[WD Proxy][39m Proxying [GET /wd/hub/session/95c58959-669d-440a-a892-0ceb76bb9de4/element/ddfe4239-249e-486d-9d7c-82a4ed9faa03/screenshot] to [GET http://127.0.0.1:8003/wd/hub/session/8c1e98e88919da0ffca73ad271f12ecf/element/ddfe4239-249e-486d-9d7c-82a4ed9faa03/screenshot] with no body
[debug] [35m[WD Proxy][39m Got response with status 200: {"value":"iVBORw0KGgoAAAANSUhEUgAAAXwAAAAsCAYAAABmHgOJAAAFgElEQVR4nO3dW2wUVRwG8G9mZ2d2uttdLLRQKNoCBeotiiJyUS4pJoBRxCAEH4AYqRokGogkwoPw4DU8oEYF0zQYQY0GsAQIWhClQtANYAqhLVSQxkrFUmg73fscH6bQrBXYLS3tdr7f0zb5b87Z5PTbs/8zsytN+ehjsWLUGeS6DRARUd9z1khDydmhkI78/LLIa66BGgv29JyIiKgbSLKM2n4joHhNA2qUYU9E1FeJmIn0cBPkmEPp6bkQEVE3M6BC7ulJEBHRrcHAJyKyCQY+EZFNMPCJiGyCgU9EZBMMfCIim2DgExHZBAOfiMgmGPhERDbBwCcisgkGPhGRTTDwiYhsgoFPRGQTDHwiIpvgdyNTr7Bys4FD1TG8OkvDUw9p160tr4xg6+EwqupicLskPJyvYP4EFYMzHB1qhRDYezyKHf4wTp2PwavLuDNHxvwJGkYOjq8/cDKCVV8GkJcpY9NST4e5jctX8O6zOiRJAgD802RizroWAMDW5R4M8HL/RL0bVyillE37Q3j9iwD8v8eQ5ZMQDAts/zWCok9bUVMf61C/oSyItd8EcOyPKHIyZGgKUFYRxZKNBirORZMa+/CpKPafSO45nbV+VwAHTkZuyVhkHwx8ShlVdVEU/xCCLAHvL05DyUvp2LYiHbPHOnG5VWDdjvhfbqv8M4ot5RFIksD6RW5sLPJg01IPigo1mAL45PtQ0nP4cE8QLUHRVS/pmgJhYPVXrdh5JNztY5F9sKVDKWNvhbW7nn6vgvtyraXrcEhYNEVDqT+C47Ux1NTHMHyg1aopr7TqJxe01wPArDEqGlpMQADhqICqSAmNr8gCF5qAzeUhFBW6Ep73xRYTu49GIETibxSnzscghIR3vg3ikiGwYJJ6tZVE1FkMfEoZV1o2I7Pje+8ZHhlDMmTUNpg4d8G8Gvi1DSYAYPig+Pp+bgnLZuhJjz9vgoZ...
[35m[HTTP][39m [37m<-- GET /wd/hub/session/95c58959-669d-440a-a892-0ceb76bb9de4/element/ddfe4239-249e-486d-9d7c-82a4ed9faa03/screenshot [39m[32m200[39m [90m239 ms - 1968[39m
[35m[HTTP][39m [90m[39m
```

**Comment by mykola-mokhnach** [comment]
I agree to the above statement. The request is directly proxied to chromedriver, so there is nothing we could do on Appium side about it. Please report the issue to Google.
