### ISSUE TITLE
Original error: 'POST /elements' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed)

### ISSUE THREAD

**Issue by Hamzastreamwide** [appium/appium#16273]
## The problem

An unknown server-side error occurred while processing the command. Original error: 'POST /elements' cannot be proxied to the UiAutomator2 server because the instrumentation process is not running (probably crashed).

## Environment

* Appium version (or git revision) that exhibits the issue:1.23.0-beta.0
* Last Appium version that did not exhibit the issue (if applicable):1.20
* Desktop OS/version used to run Appium: ubuntu 
* Node.js version (unless using Appium.app|exe): 1.23.0-beta.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: android 8.0
* Real device or emulator/simulator: real device 
* Appium CLI or Appium.app|exe: cli

## Details

the app start then it stops 

## Link to Appium logs

[[Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!]

https://gist.github.com/Hamzastreamwide/83d0af187f00a34b4d7954d19ad57b23

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by Hamzastreamwide** [comment]
the problem was from a method to give permission 

public void grantAndroidPermission(){
        String packageName=   mConfigProperties.getProperty(Constants.AppPackage);
        String grantCameraPermission= "adb shell pm grant " + packageName +" android.permission.CAMERA";
        String grantReadExternalStoragePermission= "adb shell pm grant " + packageName +" android.permission.READ_EXTERNAL_STORAGE";
        String grantWriteExternalStoragePermission= "adb shell pm grant " + packageName +" android.permission.WRITE_EXTERNAL_STORAGE";
        String readContactsPermission= "adb shell pm grant " + packageName +" android.permission.READ_CONTACTS";
        String grantLocationPermission= "adb shell pm grant " + packageName +" android.permission.ACCESS_FINE_LOCATION";
        String grantCalendarPermission= "adb shell pm grant " + packageName +" android.permission.READ_CALENDAR";
        String grantMicroPermission= "adb shell pm grant " + packageName +" android.permission.RECORD_AUDIO";

        String grantTelephonyPermission= "adb shell pm grant " + packageName +" android.permission.READ_PHONE_STATE";

        String revokeCameraPermission= "adb shell pm revoke " + packageName +" android.permission.CAMERA";
        String revokeLocationPermission= "adb shell pm revoke " + packageName +" android.permission.ACCESS_FINE_LOCATION";
        try {
            Runtime.getRuntime().exec(grantCameraPermission);
            Runtime.getRuntime().exec(grantTelephonyPermission);

            Runtime.getRuntime().exec(grantLocationPermission);
            Runtime.getRuntime().exec(grantWriteExternalStoragePermission);
            Runtime.getRuntime().exec(grantReadExternalStoragePermission);
            Runtime.getRuntime().exec(readContactsPermission);
            Runtime.getRuntime().exec(grantCalendarPermission);
            Runtime.getRuntime().exec(grantMicroPermission);

        } catch (IOException e) {
            e.printStackTrace();
        }

    }

i didnt have this problem on mac , but on ubentu the adb causing problems

**Comment by Hamzastreamwide** [comment]
it needs to be called before driver initialization , its fixed

**Comment by mykola-mokhnach** [comment]
Please provide the full logcat output.

**Comment by Hamzastreamwide** [comment]
@mykola-mokhnach  u can close it i fixed it , error in my code
