### ISSUE TITLE
Javla-Client: 8+: XCUITest driver document needs update of 'getId()'

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#16279]
## The problem

e.g. https://github.com/appium/appium-xcuitest-driver#mobile-tap is not valid any more:
```
params.put("element", ((RemoteWebElement) element).getId());
```

Is there any way to get element ID with java-client 8.0.0+ ?

**Comment by mykola-mokhnach** [comment]
<img width="1037" alt="id" src="https://user-images.githubusercontent.com/7767781/147565432-32df6827-a1c3-430b-b5af-920ca4a5931a.png">

This looks fine to me with the recent master. What is the compiler message in your case?

**Comment by amedvedjev** [comment]
aaaaaaaa. missed somehow...
