### ISSUE TITLE
UnsupportedCommandException is thrown when windowHandles method is used with Mac2 driver. 

### ISSUE THREAD

**Issue by TejaReddy19** [appium/appium#16285]
## The problem
 UnsupportedCommandException is thrown when windowHandles method is used with Mac2 driver. Appium logs are attached.
org.openqa.selenium.UnsupportedCommandException: Unhandled endpoint: /session/4F867B27-3B92-4935-9ADB-FEC6FF75F94F/window/handles -- http://127.0.0.1:10100/ with parameters {
    wildcards =     (
        "session/4F867B27-3B92-4935-9ADB-FEC6FF75F94F/window/handles"
    );
}
## Environment
Appium Server GUI: 1.22.0
Electron: 7.3.3
Node.js: 12.8.1

## Details

I have tried working on a native mac application which is webex.
I tried getting window handles of this application and this error is thrown.

## Link to Appium logs

-> GET /wd/hub/session/074e95ff-4a8d-4576-a1de-11946f8423ab/window/handles
[HTTP] {}
[W3C (074e95ff)] Driver proxy active, passing request on via HTTP proxy
[WD Proxy] Matched '/wd/hub/session/074e95ff-4a8d-4576-a1de-11946f8423ab/window/handles' to command name 'getWindowHandles'
[Protocol Converter] Did not know how to rewrite the original URL '/wd/hub/session/074e95ff-4a8d-4576-a1de-11946f8423ab/window/handles' for W3C protocol
[WD Proxy] Proxying [GET /wd/hub/session/074e95ff-4a8d-4576-a1de-11946f8423ab/window/handles] to [GET http://127.0.0.1:10100/session/4F867B27-3B92-4935-9ADB-FEC6FF75F94F/window/handles] with no body
[WD Proxy] Got response with status 404: {"value":{"error":"unknown command","message":"Unhandled endpoint: /session/4F867B27-3B92-4935-9ADB-FEC6FF75F94F/window/handles -- http://127.0.0.1:10100/ with parameters {\n    wildcards =     (\n        \"session/4F867B27-3B92-4935-9ADB-FEC6FF75F94F/window/handles\"\n    );\n}","traceback":""},"sessionId":"4F867B27-3B92-4935-9ADB-FEC6FF75F94F"}
[W3C] Matched W3C error code 'unknown command' to UnknownCommandError
[HTTP] <-- GET /wd/hub/session/074e95ff-4a8d-4576-a1de-11946f8423ab/window/handles 404 21 ms - 1073

## Code To Reproduce Issue [ Good To Have ]

	DesiredCapabilities caps = new DesiredCapabilities();
		caps.setCapability("platformName", "Mac");
		caps.setCapability("automationName", "Mac2");
		caps.setCapability("bundleId", "Cisco-Systems.Spark");
		caps.setCapability("showServerLogs", "true");
		System.out.println("Capabilities are set");
		driver = new AppiumDriver(new URL("http://localhost:4723/wd/hub"), caps);
               System.out.println(driver.getWindowHandle());

**Comment by mykola-mokhnach** [comment]
This is expected. Mac2 driver (and thus XCTest itself) distinguishes application windows based on location queries: https://developer.apple.com/documentation/xctest/xcuielementtypequeryprovider/1500382-windows?language=objc

**Comment by TejaReddy19** [comment]
Thank you so much!
Can you please tell me how driver.getTitle() works?
I got the same error when used this method.
Thank you so much for you help!

**Comment by mykola-mokhnach** [comment]
`driver.getTitle()` won't work for Mac2 driver as there are no windows concept. You could try to fetch an appropriate text by locating the corresponding element and fetching the appropriate attribute from it.

**Comment by TejaReddy19** [comment]
Okay. Thank you so much for your clarification.
Closing the issue 👍

**Comment by faceflame** [comment]
I am getting the same exception on finding an element for a desktop app on Mac.
