### ISSUE TITLE
PickerWheel valuesdoes work stable on Appium v1.22.1 & XCUITestDriver (v3.56.2)  & iPhone 15

### ISSUE THREAD

**Issue by baselalali** [appium/appium#16281]
## The problem

The test scenario related to PickerWheel are failed, since the value was not changed after turning the picker wheel. 

## Environment

* Appium version (or git revision) that exhibits the issue: v1.22.1
* Last Appium version that did not exhibit the issue (if applicable): 1.22.0
* XCUITestDriver (v3.56.2)
* iPhone Pro Max iOS 15.2
*

## Details

The same scenario works fine for iOS device with OS < 15 

## Link to Appium logs

POST /execute

{
	"script": "mobile: selectPickerWheelValue",
	"args": [
		{
			"offset": 0.2,
			"order": "next",
			"element": "111112-12122-22"
		}
	]
}

**Comment by mykola-mokhnach** [comment]
We have not been doing any changes to that part of the code for quite a while. I would try to change the value using swipe or sendKeys APIs. If that still does not work then only Apple is capable of fixing the issue in XCTest

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
