### ISSUE TITLE
Locator method timing slowed ~200x creating scenarios to fail

### ISSUE THREAD

**Issue by aquigriffin** [appium/appium#16298]
**The problem**
While investigating an issue where our tests were running extremely slow, I discovered a prevalent issue where locator find methods by id, accessibility id, and xpath were slowed by ~200x the regular find times when the Android keyboard is on screen. Forcing the soft keyboard hidden via desired capabilities and/or hiding during the scenario did not improve times. I suspect this issue is the underlying issue for many other situations, e.g. keyboard typing slowness.
**Environment**
Appium Inspector - App Version: 2021.9.2, Electron: 13.5.0, Node.js: 14.16.0 Appium Server GUI - App Version: 1.22.0, Electron: 7.3.3, Node.js: 12.8.1 Android Emulator - Pixel 3 Android 11 (also replicable on Android 9 & 10)
**Details**
The following are screenshots of timings taken from the Appium Inspector to demonstrate the difference between emulator keyboard being displayed/hidden.

NOTE: Previous ticket #16269 was closed earlier due to "no response".  Reopened the ticket due to issue still occurring.  Furthermore in response to @mykola-mokhnach regarding this being a duplicate of #14594, this issue appears to be unique.

**Comment by mykola-mokhnach** [comment]
> Furthermore in response to @mykola-mokhnach regarding this being a duplicate of #14594, this issue appears to be unique.

- Have you checked the logcat output to confirm it is unique? Do you see idle wait delays ther?
- Have you also tried to set the idle timeout value?

**Comment by aquigriffin** [comment]
@mykola-mokhnach Hey thanks for the quick response.  I'll double check the logcat output, but haven't tried the custom idle timeout value.  I'm using Python and the link to issue #14594 appears to be the node.js version.  I couldn't find the docs for the python version of waitForIdleTimeout... only this https://appium.io/docs/en/commands/session/timeouts/implicit-wait/
Can you point me to the correct docs?

**Comment by KazuCocoa** [comment]
It is via settings api. > waitForIdleTimeout
https://github.com/appium/appium-uiautomator2-driver#settings-api

**Comment by aquigriffin** [comment]
Oh I see.  I found this was what I was looking for:
```
self.driver.update_settings({
        "waitForIdleTimeout": 3000,  # 3 seconds
})
```
Trying this out to see if this resolves our issues.

**Comment by aquigriffin** [comment]
@KazuCocoa @mykola-mokhnach waitForIdleTimeout worked in cutting locator times down from ~20s to ~0.5s.  Thanks for all your help.

**Comment by nageshc** [comment]
Hi @mykola-mokhnach and @aquigriffin 

How to use in Webdriver IO
broswer.updateSettings( { "waitForIdleTimeout": 10000 } ) ;

Is this correct way to use in Webdriver iO Javascript

Thanks in Advance

**Comment by sudharsan-selvaraj** [comment]
> Hi @mykola-mokhnach and @aquigriffin
> 
> How to use in Webdriver IO broswer.updateSettings( { "waitForIdleTimeout": 10000 } ) ;
> 
> Is this correct way to use in Webdriver iO Javascript
> 
> Thanks in Advance

You can refer to the webdriver.io documentation for updating the settings (https://webdriver.io/docs/api/appium/#updatesettings)

**Comment by nageshc** [comment]
Thank you @sudharsan-selvaraj for the quick response.

By doing like this it works for me.

const setting = { waitForIdleTimeout:100 };
await browser.updateSettings(setting); 

Now it is executing fast.

Thanks
