### ISSUE TITLE
iOS real device Parallel test recording shorter than intended

### ISSUE THREAD

**Issue by sSpockderpantss** [appium/appium#16294]
## The problem

Appium recording on an iOS real device works fine when running one test at a time, i.e. the recording starts at `driver.start_recording()` and stops at `driver.stop_recording()`, but as soon as i start multiple tests each with its own server + driver + real iOS device + server port, all recordings still get saved but some recordings seem to be terminated before I call `driver.stop_recording(),` i.e. they are shorter than intended.

## Environment

* Appium version 1.22.2
* MacOS Monterey version 12.2 Beta
* Node.js version 17.3.0
* Npm version 8.3.0
* iOS real devices
* Appium-Python-Client Version: 2.1.2 

## Details

I run the same script at more or less the same time for 4 (up to 10) real iOS real devices. 

Here are some code snippets:

This is how I start the server:

```
self._appium_service = AppiumService()
appium_service_args = [
                    '--shell',
                    '-a', env.APPIUM_ADDRESS,
                    '-p', env.APPIUM_PORT,
                    '--robot-port', f'{env.APPIUM_PORT}7',
                    '--tmp', f'/Users/gitlabrunner/Documents/temp/{env.CI_RUNNER_DESCRIPTION}/',
                    '--log', f'/Users/gitlabrunner/Documents/log/{env.CI_RUNNER_DESCRIPTION}/',
                    '-dc', desired_caps_json_path,
                    '--debug-log-spacing',
                    '--long-stacktrace',
                    '--log-timestamp',
                    '--session-override',
                    '--relaxed-security'
                ]
self._appium_service.start(args=appium_service_args)
```

APPIUM_ADDRESS = '127.0.0.1'
APPIUM_PORT is 4720-4729 depending on the device, each device is assigned its own unique port number that never changes.

The driver is started as usual:

`self.appium_driver = webdriver.Remote(f'http://{env.APPIUM_ADDRESS}:{env.APPIUM_PORT}/wd/hub', desired_caps)`

The desired caps dict and json file are created like such:

```
desired_caps = dict(
            platformName='iOS',
            platformVersion=env.PLATFORM_VERSION,
            deviceName=env.CI_RUNNER_DESCRIPTION,
            app=os.environ['APP'],
            bundleId=env.PACKAGE_NAME,
            udid=self.device_id,
            newCommandTimeout=env.TIMEOUT_MINUTES * 60 + 60,
            xcodeOrgId=env.XCODE_ORG_ID,
            xcodeSigningId="iPhone Developer",
            wdaLocalPort=int(f'{env.APPIUM_PORT}1'),
            mjpegServerPort=int(f'{env.APPIUM_PORT}2'),
            webkitDebugProxyPort=int(f'{env.APPIUM_PORT}6'),
            noReset=True,
            autoAcceptAlerts=not env.NATIVE_AIRTEST,
            automationName='XCUITest',
            showIOSLog=True,
            showXcodeLog=True
        )

desired_caps_json_path = 'desired_caps.json'
with open(desired_caps_json_path, 'w') as outfile:
   outfile.write(json.dumps(desired_caps))
```

Example case:

Ran 4 tests in parallel, 2 out of 4 tests (test 2 and 3) have a shorter than intended recording. The remaining tests (test 1 and 4) has the intended duration recording. If it helps I made a spreadsheet with timestamps of significant events (server start, driver start, recording start, premature termination of recording, and recording stop - which is the intended stopping point of the recording etc) of all 4 tests https://docs.google.com/spreadsheets/d/1G6LQ3TVmX2zU97Wtjd3LuPhcZ05aXxEptTdwh-JLt1s/edit#gid=0.

## Link to Appium logs

logs files for all 4 tests here https://s3.eu-central-1.amazonaws.com/cos-dev-attachments/ShareX/notsimon/2022/01/TidyUFRDdZcytQxR.zip, i couldn't find anything special at the times where the recording cut short

**Comment by mykola-mokhnach** [comment]
Could you please attach logs as gists?

**Comment by sSpockderpantss** [comment]
I'm sorry but the log is too big for gists, I keep getting 'This page is taking too long to load.' error when trying to submit, I also tried pastebin but it was too big there too, it includes device logs and xcode logs, since the server logs alone didn't seem to provide the info to solve the issue to my eyes.

**Comment by mykola-mokhnach** [comment]
If the log is so big then it would probably hard for us to read it as well. Is it possible to prefilter them somehow? Also I don't have anything on my Mac to handle .rar archives. Consider repacking into .zip or .7z instead.

**Comment by sSpockderpantss** [comment]
Filtered the logs to remove device logs and saved them separately in a .zip file, originals are still present: https://s3.eu-central-1.amazonaws.com/cos-dev-attachments/ShareX/notsimon/2022/01/TidyUFRDdZcytQxR.zip

**Comment by mykola-mokhnach** [comment]
I don't observe any explicit issues in logs. The device reports about screenshots are being made and I also observe no errors from ffmpeg. Try maybe to start another ffmpeg instance manually after the test is started and enable debug logging there. Also make sure the ffmpeg itself is up to date.

**Comment by sSpockderpantss** [comment]
I started another ffmpeg instance using Popen after calling `driver.start_recording()`, with less options. What i've found is the output video of the manual ffmpeg instance is longer than the video from the Appium-Python-Client `driver.stop_recording()` call. But both are still shorter than intended.

python options:

```
self.appium_driver.start_recording_screen(forcedRestart=True,
                                                  timeLimit=600,
                                                  videoType='h264',
                                                  videoQuality='low',
                                                  videoFilters='transpose=2',
                                                  videoFps=30
                                                  )
```

manual instance options:

```
subprocess.Popen(['ffmpeg',
                          '-f', 'mjpeg',
                          '-i', f'http://{env.APPIUM_ADDRESS}:{env.APPIUM_PORT}3',  # same port as the mjpegServerPort cap
                          '-y', os.path.join(env.TMP_PATH, 'Output.mp4'),
                          '-loglevel', 'debug',
                          '-report'], stderr=ffmpeg_debug, stdout=ffmpeg_debug)
```

Here is the generated ffmpeg debug log (together with appium server logs as usual): https://s3.eu-central-1.amazonaws.com/cos-dev-attachments/ShareX/notsimon/2022/01/LwoUybiI23P3umRn.rar

I don't know how to read the log but from what I see there were `5016 frames successfully decoded, 0 decoding errors` but I also see `http://127.0.0.1:47243: Input/output error`.

**Comment by sSpockderpantss** [comment]
According to this https://unix.stackexchange.com/questions/471760/die-2-of-3-ffmpeg-recordings-freebsd having `Stream ends prematurely at` and `Input/output error` means the network or server is not reliable. 

I implemented a bad workaround that has been giving consistent positive results so far. I have a thread that checks if the ffmpeg process is running, and if its not running calls `start_recording_screen` again, and instead of using the footage from the driver I use `wget`, as suggested in the link above to stream the recording from the mjpeg port, with the following options  `--retry-connrefused` + `--tries=999`. This ensures wget remains alive even when the server dies and gives enough time to start it again using `start_recording_screen`. Afterwards I convert the ouput to a smaller file size using ffmpeg.

Would be nice if this behavior was handled by appium in the back-end though.

**Comment by mykola-mokhnach** [comment]
I think it would be possible to add retry options by default to ffmpeg. Not sure about wget though.

**Comment by mykola-mokhnach** [comment]
@sSpockderpantss Could you please check if https://github.com/appium/appium-xcuitest-driver/pull/1364 works for you?

**Comment by sSpockderpantss** [comment]
I made the modifications from that pull request manually because I could not figure out how else to do it, I hope that doesn't change the result somehow.

The ffmpeg still ended prematurely and the recording is still shorter than intended, logs: https://s3.eu-central-1.amazonaws.com/cos-dev-attachments/ShareX/notsimon/2022/01/Ap6Nr3HazaKPvB3Q.rar

debug manual instance of ffmpeg ends at `22:16:27`, appium ffmpeg throws error and ends a minute later `2022-01-05 22:17:20:603 [ffmpeg] [http @ 0x7fc4e0805600] Stream ends prematurely at 127196118, should be 18446744073709551615`, video itself ends at `22:10:56` (debug manual instance of ffmpeg recording ends sooner even at `22:10:24`). Stop recording is called at `22:19:00` `2022-01-05 22:19:00:744 [HTTP] --> POST /wd/hub/session/ca6d4448-2c25-4e8b-ae0a-3f07460e1f33/appium/stop_recording_screen`.

In another run the debug manual instance of ffmpeg remains alive the entire test, which means the wda mjpeg server remained alive, the log still shows `Stream ends prematurely` error and `Input/output error` but that happens during the test teardown a second before the test itself ends (might be caused by the thread being a daemon thread). The resulting video is still 5 mins too short though. logs for the run: https://s3.eu-central-1.amazonaws.com/cos-dev-attachments/ShareX/notsimon/2022/01/7totqLzcHERi8HZt.rar 

(also the workaround above doesn't work consistently, so i striked it out)

In another run the wda mjpeg server died `2022-01-05 23:33:49:365 [ffmpeg] http://127.0.0.1:47223: Input/output error` at the same time as an xcode failure that seems like a signing issue `2022-01-05 23:33:49:368 [WebDriverAgent] xcodebuild exited with code '65' and signal 'null'`, logs for this run: https://s3.eu-central-1.amazonaws.com/cos-dev-attachments/ShareX/notsimon/2022/01/SARaxyngYX5kbI3D.rar

Please let me know what other info I can provide

**Comment by sSpockderpantss** [comment]
Thinking it might be some suppressed xcode error I decided to use manually build the WDA and use this prebuilt WDA, but when I do this the connection to the custom mjpeg server port is refused `2022-01-06 14:50:25:720 [iProxy@bc094999:47223] Connection was refused to port 47223` and ffmpeg dies `2022-01-06 14:50:30:654 [W3C (a047e414)] Encountered internal error running command: Error: The screen capture process 'ffmpeg' died unexpectedly. Check server logs for more details`, log: https://s3.eu-central-1.amazonaws.com/cos-dev-attachments/ShareX/notsimon/2022/01/qJ9WnKvSakH7vRDA.rar

**Comment by sSpockderpantss** [comment]
The issue seems to be fixed for me, steps I followed:

- followed these steps to clean build and cache https://github.com/appium/appium/issues/11275#issuecomment-416880329 (installed appium beta `npm -g install appium@beta` instead)
- followed the steps for full manual configuration here https://appium.io/docs/en/drivers/ios-xcuitest-real-devices/ (in the build phase I specified a derived data path `xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' -derivedDataPath <derived data path> test` and then I used the `usePrebuiltWDA` capability set to true, and the `derivedDataPath` set to <derived data path>)
- changed the port of `wdaLocalPort` capability so it stops using the cached driver at the old port (also changed port numbers on all other specified ports to a new one)

I don't know if the manual configuration was necessary, will try to use auto configuration without a derived data path again later and reply here whether or not its needed.

**Comment by sSpockderpantss** [comment]
Installing xcuitest-driver explicitly with `npm -g install appium-xcuitest-driver` and using '/usr/local/lib/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj' to sign the build and make a full manual configuration with a derived data path explicitly `xcodebuild -project /usr/local/lib/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' -derivedDataPath <derived/data/path> test` and using the `usePrebuiltWDA` capbility and `derivedDataPath` capability when running appium fixed the issue for me. I have now run 15 tests in a row without a short video, I hope the trend continues. I consider this fixed

**Comment by mykola-mokhnach** [comment]
You could simply install appium@beta or use appium2 to get the most recent driver versions.

**Comment by sSpockderpantss** [comment]
Although less frequent I still get connection refused and the recording stops prematurely about 1 out of 10 times. I'm going to try and use a different machine altogether.

**Comment by sSpockderpantss** [comment]
update:

I installed ffmpeg 2.8, deleted and recreated all certificates and provisioning profiles. Now there are no longer errors in the log, but video ends halfway through the test. Logs of latest run: https://gist.github.com/sSpockderpantss/fd66eb2ab026c6e1a40aa5da7e27cb40

**Comment by sSpockderpantss** [comment]
https://discuss.appium.io/t/issue-ios-real-device-test-recording-shorter-than-intended/35347/10 

the fix seems to be adding the following:

```
videoScale="320:-2"
pixelFormat="yuv420p" 
```
