### ISSUE TITLE
[Android] ClickGesture action isn't working on Appium 1.22.1

### ISSUE THREAD

**Issue by DmytroPazykov** [appium/appium#16291]
## The problem

Based on Android mobile gestures documentation, clickGestures action should be working since Appium 1.22.1, but it is not. After triggering this action get exception:
`org.openqa.selenium.UnsupportedCommandException: Unknown mobile command "clickGesture". Only shell,execEmuConsoleCommand,dragGesture,flingGesture,doubleClickGesture,longClickGesture,pinchCloseGesture,pinchOpenGesture,swipeGesture,scrollGesture,scrollBackTo,scroll,viewportScreenshot,viewportRect,deepLink,startLogsBroadcast,stopLogsBroadcast,acceptAlert,dismissAlert,batteryInfo,deviceInfo,getDeviceTime,changePermissions,getPermissions,performEditorAction,startScreenStreaming,stopScreenStreaming,getNotifications,listSms,type,sensorSet,deleteFile,clearApp,startActivity,startService,stopService,broadcast,getContexts,installMultipleApks commands are supported.`

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.1 and 1.22.2
* Last Appium version that did not exhibit the issue (if applicable): --
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: Android
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

**Comment by DmytroPazykov** [comment]
I do see that as of today documentation has been updated:
`mobile: clickGesture
This gesture performs click action on the given element/coordinates. Available since Appium UiAutomator2 driver 1.71.0. Usage of this gesture is recommended as a possible workaround for cases where the "native" tap call fails, even though tap coordinates seem correct. This issue is related to the fact these calls use the legacy UIAutomator-based calls while this extension is based on the same foundation as W3C does.
`
Right now you referring to UiAutomator version instead of Appium version. Can you please specify Appium version?

**Comment by mykola-mokhnach** [comment]
This driver version has not been published in Appium 1 (and I'm not sure if it is going to be published at all). Consider switching to Appium 2 or try appium@beta
