### ISSUE TITLE
Connection Refused after downgrading to 1.21.0

### ISSUE THREAD

**Issue by tking16** [appium/appium#16309]
I'm trying to downgrade my Appium server as I'm trying to see if an [issue](https://github.com/appium/appium/discussions/16302#discussion-3781580) I found with the newer versions appears on older versions. But installing 1.21.0 gives this error:

```
 selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: connect ECONNREFUSED 127.0.0.1:8100
E       Stacktrace:
E       UnknownError: An unknown server-side error occurred while processing the command. Original error: Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: connect ECONNREFUSED 127.0.0.1:8100
```

While the appium logs give back nothing but

```
2022-01-07 13:15:01:893 - [WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
2022-01-07 13:15:01:894 - [debug] [XCUITest] Failed to create WDA session (An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: connect ECONNREFUSED 127.0.0.1:8100). Retrying...
2022-01-07 13:15:02:894 - [debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1641561302894 (13:15:02 GMT+0000 (Greenwich Mean Time))
```

This does happen on other versions but Appium soon works fine after a couple retries. I'm not blocked on Appium 1.22.0, the beta (1.23) or Appium 2.

Any help or reading materials on this will be appreciated

## Environment
Xcode 13.2
npm version= 6.14.15
node=v14.15.4
iOS 15.2 Simulator

[full logs](https://gist.github.com/tking16/8d7485f947208cc2db61ed5a43b27d52)

**Comment by jlipps** [comment]
Looks like there was an xcodebuild failure. If you set the showXcodeLog capability to true you might see what's going on.

**Comment by mykola-mokhnach** [comment]
Appim 1.21 is not compatible to Xcode 13+, so the error might be expected.

**Comment by tking16** [comment]
Could be the case, we did very recently upgrade from Xcode 12 to 13. Here's the logs with `showXcodeLog ` enabled https://gist.github.com/tking16/e4c24d15492b4b8b100063a2f9847403

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
