### ISSUE TITLE
installed appium desktop version 22 on mac and getting the below erroe when trying to attach the session- Failed to create session. An unknown server-side error occurred while processing the command. Original error: The desired capabilities must include either an app or a bundleId for iOS

### ISSUE THREAD

**Issue by smithabachu** [appium/appium#16305]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by KazuCocoa** [comment]
Please attach the full appium server log as GIST as the template.

**Comment by smithabachu** [comment]
Please find the attached log

[Appium] Welcome to Appium v1.22.0
[Appium] Non-default server args:
[Appium]   relaxedSecurityEnabled: true
[Appium]   allowInsecure: {
[Appium]   }
[Appium]   denyInsecure: {
[Appium]   }
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"capabilities":{"alwaysMatch":{"platformName":"iOS","appium:platformVersion":"11.1.2","appium: deviceName":"iPhoneX","appium:automationName":"XCUITest","appium:udid":"d9258de65acb5a5bb7262ea4f7ef804eda1f0d8d","appium:xcodeOrgId":"B9C7GRQCYQ","appium:xcodeSigningId":"iPhone Developer","appium:app":"/Users/smithabachuwar/Desktop/Capture.ipa","appium:noReset":"True","appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]},"desiredCapabilities":{"platformName":"iOS","appium:platformVersion":"11.1.2","appium: deviceName":"iPhoneX","appium:automationName":"XCUITest","appium:udid":"d9258de65acb5a5bb7262ea4f7ef804eda1f0d8d","appium:xcodeOrgId":"B9C7GRQCYQ","appium:xcodeSigningId":"iPhone Developer","appium:app":"/Users/smithabachuwar/Desktop/Capture.ipa","appium:noReset":"True","appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true}}
[W3C] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","appium:platformVersion":"11.1.2","appium: deviceName":"iPhoneX","appium:automationName":"XCUITest","appium:udid":"d9258de65acb5a5bb7262ea4f7ef804eda1f0d8d","appium:xcodeOrgId":"B9C7GRQCYQ","appium:xcodeSigningId":"iPhone Developer","appium:app":"/Users/smithabachuwar/Desktop/Capture.ipa","appium:noReset":"True","appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},null,{"alwaysMatch":{"platformName":"iOS","appium:platformVersion":"11.1.2","appium: deviceName":"iPhoneX","appium:automationName":"XCUITest","appium:udid":"d9258de65acb5a5bb7262ea4f7ef804eda1f0d8d","appium:xcodeOrgId":"B9C7GRQCYQ","appium:xcodeSigningId":"iPhone Developer","appium:app":"/Users/smithabachuwar/Desktop/Capture.ipa","appium:noReset":"True","appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]}]
[BaseDriver] Event 'newSessionRequested' logged at 1641459956747 (14:35:56 GMT+0530 (India Standard Time))
[Appium] Could not parse W3C capabilities: 'noReset' must be of type boolean
[Appium] Trying to fix W3C capabilities by merging them with JSONWP caps
[BaseDriver] The following capabilities are not standard capabilities and should have an extension prefix:
[BaseDriver]   platformVersion
[BaseDriver]    deviceName
[BaseDriver]   automationName
[BaseDriver]   udid
[BaseDriver]   xcodeOrgId
[BaseDriver]   xcodeSigningId
[BaseDriver]   app
[BaseDriver]   noReset
[BaseDriver]   includeSafariInWebviews
[BaseDriver]   newCommandTimeout
[BaseDriver]   connectHardwareKeyboard
[Appium] Could not parse fixed W3C capabilities: 'noReset' must be of type boolean. Falling back to JSONWP protocol
[Appium] DeprecationWarning: 'automationName' capability was not provided. Future versions of Appium will require 'automationName' capability to be set for iOS sessions.
[Appium] Appium v1.22.0 creating new IosDriver (v4.8.3) session
[Appium] Applying relaxed security to 'IosDriver' as per server command line argument. All insecure features will be enabled unless explicitly disabled by --deny-insecure
[BaseDriver] Creating session with MJSONWP desired capabilities: {
[BaseDriver]   "platformName": "iOS",
[BaseDriver]   "appium:platformVersion": "11.1.2",
[BaseDriver]   "appium: deviceName": "iPhoneX",
[BaseDriver]   "appium:automationName": "XCUITest",
[BaseDriver]   "appium:udid": "d9258de65acb5a5bb7262ea4f7ef804eda1f0d8d",
[BaseDriver]   "appium:xcodeOrgId": "B9C7GRQCYQ",
[BaseDriver]   "appium:xcodeSigningId": "iPhone Developer",
[BaseDriver]   "appium:app": "/Users/smithabachuwar/Desktop/Capture.ipa",
[BaseDriver]   "appium:noReset": "True",
[BaseDriver]   "appium:includeSafariInWebviews": true,
[BaseDriver]   "appium:newCommandTimeout": 3600,
[BaseDriver]   "appium:connectHardwareKeyboard": true
[BaseDriver] }
[BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[BaseDriver]   appium:platformVersion
[BaseDriver]   appium: deviceName
[BaseDriver]   appium:automationName
[BaseDriver]   appium:udid
[BaseDriver]   appium:xcodeOrgId
[BaseDriver]   appium:xcodeSigningId
[BaseDriver]   appium:app
[BaseDriver]   appium:noReset
[BaseDriver]   appium:includeSafariInWebviews
[BaseDriver]   appium:newCommandTimeout
[BaseDriver]   appium:connectHardwareKeyboard
[iOS] The desired capabilities must include either an app or a bundleId for iOS
[BaseDriver] Event 'newSessionStarted' logged at 1641459957565 (14:35:57 GMT+0530 (India Standard Time))
[MJSONWP] Encountered internal error running command: Error: The desired capabilities must include either an app or a bundleId for iOS
[MJSONWP]     at Object.errorAndThrow (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:94:35)
[MJSONWP]     at desiredCapValidation (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-ios-driver/lib/desired-caps.js:141:12)
[MJSONWP]     at IosDriver.validateDesiredCaps (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-ios-driver/lib/driver.js:464:12)
[MJSONWP]     at IosDriver.createSession (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/session.js:46:8)
[MJSONWP]     at IosDriver.createSession (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-ios-driver/lib/driver.js:120:41)
[MJSONWP]     at AppiumDriver.createSession (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/lib/appium.js:387:43)
[MJSONWP]     at processTicksAndRejections (internal/process/task_queues.js:85:5)
[HTTP] <-- POST /wd/hub/session 500 891 ms - 210
[HTTP]

**Comment by smithabachu** [comment]
Installed Appium  [1.22 ]desktop app for MAC-Big SUR [OS] , having xcode 13 , create session is not working

**Comment by mykola-mokhnach** [comment]
> [Appium] Could not parse fixed W3C capabilities: 'noReset' must be of type boolean. Falling back to JSONWP protocol

The error is expected. Consider fixing the noReset capability.
