### ISSUE TITLE
Unable to connect to Appium Server which share same wifi network

### ISSUE THREAD

**Issue by Manasaanand** [appium/appium#16308]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0 or 1.22.0
* Last Appium version that did not exhibit the issue (if applicable): not ssure
* Desktop OS/version used to run Appium: 11.6.2
* Node.js version (unless using Appium.app|exe): latest version
* Npm or Yarn package manager:
* Mobile platform/version under test: 14.8.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: 1.22.0

## Details

If necessary, describe the problem you have been experiencing in more detail.
I have my test automation on my windows computer.
I am running my appium client from my iMac connected my real device to mac system
Both Windows and mac are connected to same WIFI. I can ping my mac IP Address.
When try to run my test from windows by connecting appium client from my mac. the connection is not established.

Tried all possible ways even tried downgrading appium to 1.19.0. It is not at all connecting
## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by jlipps** [comment]
Please include your appium logs. You might need to run `appium -a 0.0.0.0` to listen on all interfaces and not just the default localhost if you wish to expose your server over your LAN.

**Comment by Manasaanand** [comment]
thank you. didnt run either . addinglog doesnt help as no connection established to appium so log would be nothing . There has to be at least one connection. Is there any permisison I am missing. Is it because any change in latest appium versions that is not working. same code, worked few months back and now it is not.

**Comment by mykola-mokhnach** [comment]
This looks more like a local setup issue. Make sure you run the server on the correct network interface and use appropriate address there. Unfortunately there is nothing more we could advice there as no details about network interfaces configuration have been provided.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by Manasaanand** [comment]
The issue was I could not able to put proper server IP. I should get server IP by calling ifconfig getifaddr en1
After that whatever IP displayed to be used to call appium server when trying to run tests on same wifi. Now it fixed the issue. thank you

**Comment by jlipps** [comment]
Yes, if you're accessing the server remotely you'd need to use its correct address on the network (not localhost).
