### ISSUE TITLE
Not able to perform drag and drop gesture using Appium espresso

### ISSUE THREAD

**Issue by sonugupta029** [appium/appium#16304]
## The problem

Not able to perform drag and drop gesture using Appium espresso

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2 and above
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Mac OS Catalina 10.15.7
* Node.js version (unless using Appium.app|exe): 14.5.0
* Npm or Yarn package manager: 6.14.8
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Not able to perform drag and drop gesture using Appium espresso. It seems that drag is working and while performing drop getting exception "java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus"

## Link to Appium logs

Logcat Logs:
https://gist.github.com/sonugupta029/af0a5d1d46888a3b5a103b57e5c84199

Appium Logs:
https://gist.github.com/sonugupta029/1ff4ba18627b5ca2f89ea8089869def1

## Code To Reproduce Issue [ Good To Have ]
Code tried 1:
 AndroidTouchAction(mobileDriver as PerformsTouchActions).longPress(LongPressOptions.longPressOptions().
            withElement(ElementOption.element(fromAccountElement))).
            waitAction(WaitOptions.waitOptions(Duration.ofSeconds(10))).
            moveTo(ElementOption.element(toAccountElement)).
            release().perform()

Code tried 2:
 val source: Point = fromAccountElement.center
            val target: Point = toAccountElement.center
            val finger = PointerInput(PointerInput.Kind.TOUCH, "finger")
            val dragAndDrop = Sequence(finger, 1)
            dragAndDrop.addAction(finger.createPointerMove(ofMillis(10000),
                    PointerInput.Origin.viewport(), source.x, source.y))
            dragAndDrop.addAction(finger.createPointerDown(PointerInput.MouseButton.MIDDLE.asArg()))
            dragAndDrop.addAction(Pause(finger, ofMillis(10000)))
            dragAndDrop.addAction(finger.createPointerMove(ofMillis(10000),
                    PointerInput.Origin.viewport(),
                    target.x, target.y))
            dragAndDrop.addAction(finger.createPointerUp(PointerInput.MouseButton.MIDDLE.asArg()))
            mobileDriver?.perform(singletonList(dragAndDrop))

**Comment by mykola-mokhnach** [comment]
This exception is generated by Espresso framework itself and I don't think there's anything we could do in Appium to workaround it. Try to google it for possible solutions: https://www.google.com/search?q=%22Waited+for+the+root+of+the+view+hierarchy+to+have+window+focus%22

**Comment by sonugupta029** [comment]
Thanks @mykola-mokhnach for prompt response. Can it be due to below logcat logs and may be something needs to be fixed at app side?
2022-01-06 17:21:29.812 1086-1973/? W/InputDispatcher: Permission denied: injecting event from pid 16478 uid 10685 to window drag owned by uid 1000
2022-01-06 17:21:29.813 1086-1973/? W/InputDispatcher: Permission denied, dropping the motion (isPointer=true)

**Comment by mykola-mokhnach** [comment]
It could be. Basically Espresso is limited by the application under test sandbox. Normally it is impossible to interact with other elements that don't belong to this app. We've added the https://github.com/appium/appium-espresso-driver#mobile-uiautomator extension to be able to at least partially workaround that system limitation.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
