### ISSUE TITLE
Element.getRect returns incorrect coordinates within Cordova Hybrid WebView - Android

### ISSUE THREAD

**Issue by avenstewart** [appium/appium#16313]
## Appium or Appium Desktop?

Issue occurs on both Appium Desktop GUI and Appium CLI

## The problem

Similar to closed issue described in https://github.com/appium/appium-inspector/issues/154, but still seems to persist in the latest patch (2021.9.2) that claims to fix it.

Appium is unable to obtain accurate coordinates for elements within a Cordova hybrid WebView on a physical device (Galaxy Note 10) running Android 9 and Chromedriver 96. Element coordinates returned are random and do not appear to be the result of any visible device-specific offset. Dimensions for elements are accurate, but locations are wrong. 

Expected location for the following element should be {"x": 50 , "y":827 }. Screen resolution is 1080 x 2280.

>[debug] [W3C (007c105c)] Calling AppiumDriver.getElementRect() with args: ["5c77342e-94b5-4111-8b00-c90b4b47db06","007c105c-4e3e-48f9-a899-8304bdb27f41"]
[debug] [UiAutomator2] Detected downstream chromedriver protocol: W3C
[debug] [WD Proxy] Matched '/element/5c77342e-94b5-4111-8b00-c90b4b47db06/rect' to command name 'getElementRect'
[debug] [WD Proxy] Proxying [GET /element/5c77342e-94b5-4111-8b00-c90b4b47db06/rect] to [GET http://127.0.0.1:8003/wd/hub/session/4b228370340c2d2a7284434f386d92bb/element/5c77342e-94b5-4111-8b00-c90b4b47db06/rect] with no body
[debug] [WD Proxy] Got response with status 200: {"value":{"height":44,"width":380,"x":16,"y":281}}
[debug] [W3C (007c105c)] Responding to client with driver.getElementRect() result: {"height":44,"width":380,"x":16,"y":281}
[HTTP] <-- GET /wd/hub/session/007c105c-4e3e-48f9-a899-8304bdb27f41/element/5c77342e-94b5-4111-8b00-c90b4b47db06/rect 200 71 ms - 50

It is worth mentioning, but perhaps unrelated, that using Element.getScreenshotAs() results in an accurate image of the element, demonstrating that this method is able to calculate the location accurately within itself, but public location methods are not.

## Environment

- I am running Appium CLI version 1.22.2, Desktop version 1.22.0.
- I am on:
    - [x] Mac
    - [ ] Windows
    - [x] Linux

**Comment by jlipps** [comment]
Please provide the full log for context.

**Comment by mykola-mokhnach** [comment]
These coordinates are returned by chromedriver itself. Appium simply acts as a proxy there. I don't think there is anything we could do from Appium side there. Consider reporting your issue to Google.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
