### ISSUE TITLE
Appium 2.0 : FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by StephanB75** [appium/appium#16319]
## The problem

Since yesterday (09. January) my tests failing to start/intialize drivers.
As the CI is installing everything fresh on each run, there must be something changed on the weekend which caused this issue.

## Environment

* Appium version (or git revision) that exhibits the issue: appium 2.0 beta.21
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe): 14
* Npm or Yarn package manager:
* Mobile platform/version under test: android / ios
* Real device or emulator/simulator: Simulaotr
* Appium CLI or Appium.app|exe: CLI

## Details

I tried the same Tests on my local mac without problems. Than i uninstall appium and drivers/plugins from my machine and made a npm install to reinstall all. After that the error also occurs on my machine.

![Bildschirmfoto 2022-01-10 um 08 20 01](https://user-images.githubusercontent.com/90029825/148730148-a53e34f7-25c8-40f8-aaa8-fa6c3059dedc.png)

## Code To Reproduce Issue [ Good To Have ]

my package.json
` {
  "repository": {
    "type": "",
    "url": ""
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "appium": "2.0.0-beta.21"
  },
  "scripts": {
    "postinstall": "npx appium plugin uninstall images || true && npx appium driver uninstall uiautomator2 || true && npx appium driver install uiautomator2 || true && npx appium plugin install images || true"
  },
  "name": "appium_installation",
  "version": "1.0.0"
}`

**Comment by StephanB75** [comment]
head something that the creator of fakejs and colorjs submitted a broken version... intentionally

**Comment by mykola-mokhnach** [comment]
Yes, we saw it. Working on a patch 😞

**Comment by mykola-mokhnach** [comment]
The base driver patch has been published
