### ISSUE TITLE
Need support with connectivity issues between relay Node and Appium on Selenim grid 4.

### ISSUE THREAD

**Issue by laxman1362** [appium/appium#16321]
## The problem

I am trying to setup Selenium grid 4 on minikube on my local machine and register appium and emulator on grid. I tried setting up relay node and Appium, both are up and running but facing issues in establishing connection and getting error as mentioned below.

## Environment

Appium version: 1.22.0
Selenium grid 4.x
Desktop OS/version used to run Appium: Windows
emulator: Android Emulators
Relay node

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Link to Appium logs

* daemon not running; starting now at tcp:5037
* daemon started successfully
Devices found: 0
[Appium] Welcome to Appium v1.22.0
[Appium] Non-default server args:
[Appium]   logFile: /var/log/appium.log
[Appium]   nodeconfig: /root/nodeconfig.json
[debug] [Appium] Starting auto register thread for the grid. Will try to register every 5000 ms.
[Appium] Appium REST http interface listener started on 0.0.0.0:4723

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/issues/14848#issuecomment-941243237 is all we have as Appium team does not maintain the connector module. Consider asking for support at Selenium Grid forum. You could also try https://discuss.appium.io

Closed as not an issue.

**Comment by jlipps** [comment]
I think with the Selenium 4 Grid, you set up the config on the Selenium Grid side, not the Appium side (so using Appium's node config option is no longer necessary). See https://www.selenium.dev/documentation/grid/configuration/toml_options/. Pretty sure that the grid now polls the Appium server rather than the other way around?

**Comment by laxman1362** [comment]
Do you have any .yml file to refer?

**Comment by jlipps** [comment]
No, sorry, I can only point to the documentation created for this purpose.
