### ISSUE TITLE
Finding Element Does not Works - The incorrect Element Found

### ISSUE THREAD

**Issue by NirBY** [appium/appium#16324]
## The problem
When try to find element on DOCServiceTargetSelectionBrowserView (when try saving file), the wrong element is found and finally clicked.
In below movie you can see I try clicking "On My iPhone", but actually clicking "iCloud Driver".

## Environment

* Appium version (or git revision) that exhibits the issue: V1.12.2
* Last Appium version that did not exhibit the issue (if applicable):none
* Desktop OS/version used to run Appium:iMAC
* Node.js version (unless using Appium.app|exe):V12.19.0
* Npm or Yarn package manager:--
* Mobile platform/version under test:IOS/iPhone Real Device
* Real device or emulator/simulator:Real Device
* Appium CLI or Appium.app|exe:both

## Details

Wrong element is pulled.

## Link to Appium logs
[Appium Logs](https://github.com/appium/appium/files/7841474/appiumServeriPhone8.log)

## Code To Reproduce Issue [ Good To Have ]
new WebDriverWait(driver, MIN_WAIT_TIME).until(ExpectedConditions
.visibilityOfElementLocated(MobileBy.AccessibilityId("On My iPhone"))).click();

OR

new WebDriverWait(driver, MIN_WAIT_TIME).until(ExpectedConditions
                                    .visibilityOfElementLocated(MobileBy
                                            .iOSNsPredicateString("type == 'XCUIElementTypeStaticText' AND name == 'On My iPhone'"))).click();

## Page Source
[Page Source](https://github.com/appium/appium/files/7839867/20220109040424_827.txt)

##Movie
[Movie](https://user-images.githubusercontent.com/9214815/148791792-ca8d6a44-513e-4231-9501-fe52998c137b.mp4)

**Comment by mykola-mokhnach** [comment]
Clicks are executed by XCTest itself. We cannot influence that, only Apple can fix such issue. You could try to click by coordinates as a possible workaround

**Comment by amedvedjev** [comment]
try get found element center and tap by x,y.

**Comment by NirBY** [comment]
Thank You for responding, Actually I already try it. 

The original movie and logs are with tapping by coordinates:
`
2022-01-09 16:03:58:604 [W3C (40adfe70)] Responding to client with driver.getLocation() result: {"x":56,"y":225}
2022-01-09 16:03:58:919 [W3C (40adfe70)] Responding to client with driver.getSize() result: {"width":107,"height":21}
`
And Clicking Element Center:
`
2022-01-09 16:03:58:976 [HTTP] {"actions":[{"action":"press","options":{"x":109,"y":235}},{"action":"release","options":{}}]}
`

Is there better way dealing with it?

**Comment by mykola-mokhnach** [comment]
Like I said these coordinates are returned by XCTest and it's up to Apple to change that. The only possible way would be to calculate absolute coordinates.

**Comment by amedvedjev** [comment]
in page source we have:
```
<XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="On My iPhone" name="On My iPhone" label="On My iPhone" enabled="true" visible="true" accessible="true" x="56" y="359" width="107" height="21" index="2"/>
```
where center Y  = 359 + (21 / 2). try in code get element. then ->
```
                    Rectangle rect = el.getRect();

                    int centerX = rect.x + (rect.width / 2);
                    int centerY = rect.y + (rect.height / 2);
```

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
