### ISSUE TITLE
appium 1.22.2 can't handle iOS 15 ?

### ISSUE THREAD

**Issue by iqbal115705** [appium/appium#16332]
## The problem

after update to iOS 15, then i spy using katalon all object become XCUIElementTypeAny, not detected which is the button and which is the text. i use appium 1.22.2. and spy real device

<img width="1099" alt="Screen Shot 2022-01-12 at 14 52 38" src="https://user-images.githubusercontent.com/33626649/149088676-9ec3b897-1482-4758-af64-b4d57f7ad9b0.png">

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.2
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: macOS Monterey 12.1
* Node.js version (unless using Appium.app|exe): v17.3.0
* Npm or Yarn package manager: NPM -> 8.3.0
* Mobile platform/version under test: Calculator
* Real device or emulator/simulator: iPhone 11 Pro Max, iOS 15.2
* Appium CLI or Appium.app|exe:

## Details

i spy com.apple.calculator using katalon using real device, if i use iOS 14 no problem happen, if i use iOS 15 it is become problem.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

Appium log -> https://gist.github.com/iqbal115705/be58fcb2696d13fc15a15486707606f5

**Comment by mykola-mokhnach** [comment]
The page tree is returned by XCTest. There is nothing we could do about it from Appium side. Only Apple is able to change it.
You could also try to report the issue to Katalon.

Closed as third party issue
