### ISSUE TITLE
Appium doesn't click element inside ScrollView

### ISSUE THREAD

**Issue by fedorin-git** [appium/appium#16334]
## The problem

I run acceptance tests on react-native application. There is a Sign In component that renders the regions list to be selected.
```
<ScrollView>
          {Platform.OS === 'android' && regions.map(({ name, value }) => (
            <MenuItem
              key={value}
              isSelected={value === selectedRegion}
              onPress={() => setSelectedRegion(value)}
              {...getAccessibilityIdProp(`region-${value}`)}
            >
              <MenuItemText isSelected={value === selectedRegion}>{name}</MenuItemText>
            </MenuItem>
          ))}
        </ScrollView>
```

I search element by its accecibilityID
```
When('I choose region {string}', (region) => {
 getElement('~selectRegionButton').click();
  $(`~region-europe`).click(); // this step has no effect
  $(`~doneButton`).click();
})
```

Once `~selectRegionButton` button is clicked regions list is opened and I click on element `~region-europe`, then click `~doneButton`. `~region-europe` should be selected in dropdown but it doesn't happen. The default region remains selected.

However, when I inspect app via Appium inspector, select this element and click 'Tap' it works fine so element is reachable for Appium. Appium logs can confirm that

```
[0-0] 2022-01-13T13:50:06.357Z INFO webdriver: COMMAND findElement("accessibility id", "region-europe")
[0-0] 2022-01-13T13:50:06.358Z INFO webdriver: [POST] http://localhost:4723/session/505e7ea1-7551-412b-8f64-a850eb716a2b/element
[0-0] 2022-01-13T13:50:06.358Z INFO webdriver: DATA { using: 'accessibility id', value: 'region-europe' }
[0-0] 2022-01-13T13:50:06.414Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': '00000000-0000-0025-ffff-ffff00000062',
[0-0]   ELEMENT: '00000000-0000-0025-ffff-ffff00000062'
[0-0] }
[0-0] 2022-01-13T13:50:06.427Z INFO webdriver: COMMAND elementClick("00000000-0000-0025-ffff-ffff00000062")
```

I have no idea why this step does not work because I have many scenarios where I click elements inside `scrollView`. I know it may be not Appium bug but I hope you guys will help to resolve it.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS Monterey 12.0.1
* Node.js version (unless using Appium.app|exe): 14.17.5
* Npm or Yarn package manager: yarn 1.22.10
* Mobile platform/version under test: Android 11
* Real device or emulator/simulator: Pixel_3_API_31 "system-images;android-31;google_apis_playstore;x86_64"
* Appium CLI or Appium.app|exe:

**Comment by mykola-mokhnach** [comment]
This could be a race condition. Try to add a delay/timer before clicking the destination button

**Comment by fedorin-git** [comment]
> This could be a race condition. Try to add a delay/timer before clicking the destination button

Delay does not help. The only difference is ScrollView and simple View. View is 100% positive result

**Comment by mykola-mokhnach** [comment]
Try to locate the element using UiSelector. Perhaps @amedvedjev could advice more there.
Or try to click by absolute coordinates rather that clicking the element.
Otherwise I don't have any good ideas as Appium basically reroutes all commands to UiAutomator. So only Google can change/fix anything there.

**Comment by amedvedjev** [comment]
try following:
1) add capability:
```
// Java
capabilities.setCapability("enableMultiWindows", true);
```
sometimes ScrollView showing in another window
2) try add setting:
```
// Java
((AndroidDriver) driver[0]).setSetting(Setting.WAIT_FOR_IDLE_TIMEOUT, 500);
```
more to read -> https://github.com/appium/appium-uiautomator2-driver#settings-api
3) enable in developer menu on phone show touches and coordinates. check where tap/click actually happen. if it happen :-)
4) migrate to w3c touch instead of click -> http://appium.io/docs/en/commands/interactions/actions/
5) finally if all fails follow `mykola` suggestion:
  - check that element actually found
  - find element center:
```
// Java
Rectangle rectangle = ((WebElement) el).getRect();
Point point = new Point(rectangle.x + (rectangle.width / 2), rectangle.y + (rectangle.height / 2));
```
  - click / tap on it by x,y.

**Comment by fedorin-git** [comment]
> try following:
> 
> 1. add capability:
> 
> ```
> // Java
> capabilities.setCapability("enableMultiWindows", true);
> ```
> 
> sometimes ScrollView showing in another window 2) try add setting:
> 
> ```
> // Java
> ((AndroidDriver) driver[0]).setSetting(Setting.WAIT_FOR_IDLE_TIMEOUT, 500);
> ```
> 
> more to read -> https://github.com/appium/appium-uiautomator2-driver#settings-api 3) enable in developer menu on phone show touches and coordinates. check where tap/click actually happen. if it happen :-) 4) migrate to w3c touch instead of click -> http://appium.io/docs/en/commands/interactions/actions/ 5) finally if all fails follow `mykola` suggestion:
> 
> * check that element actually found
> * find element center:
> 
> ```
> // Java
> Rectangle rectangle = ((WebElement) el).getRect();
> Point point = new Point(rectangle.x + (rectangle.width / 2), rectangle.y + (rectangle.height / 2));
> ```
> 
> * click / tap on it by x,y.

1 - 2: still fail
3: there is no tap effect at all! for both list item and 'Done' button, however 'Done' button is clicked well. Please [see video capturing](https://drive.google.com/file/d/168ffvuoJX00E_g1hiOlA92vRjg6ooBMB/view?usp=sharing)

**Comment by amedvedjev** [comment]
@fedorin-git no tap effect = element NOT found in most cases. make following:
   - while having `enableMultiWindows` = true stop on ScrollView e.g. for 5 sec and get page source:
```
// Java
System.out.println(driver.getPageSource());
```
  - share it result at https://gist.github.com/ as link

**Comment by fedorin-git** [comment]
> @fedorin-git no tap effect = element NOT found in most cases. make following:
> 
> * while having `enableMultiWindows` = true stop on ScrollView e.g. for 5 sec and get page source:
> 
> ```
> // Java
> System.out.println(driver.getPageSource());
> ```
> 
> * share it result at https://gist.github.com/ as link

[Click me](https://gist.github.com/fedorin-git/c7ac63363db3ebf73cecf4bae92e180d)

All elements containing 'region-' are ScrollView list items.

**Comment by amedvedjev** [comment]
why not ty try UIAutomator command @fedorin-git ?
```
    // Java
    @AndroidFindBy(uiAutomator = "new UiSelector().description(\"region-australia\")")
    private WebElement regionAustraliaElement;
```

**Comment by fedorin-git** [comment]
> why not to try UIAutomator command @fedorin-git ?
> 
> ```
>     // Java
>     @AndroidFindBy(uiAutomator = "new UiSelector().description(\"region-australia\")")
>     private WebElement regionAustraliaElement;
> ```

Not sure how can I implement that with JS :(

**Comment by amedvedjev** [comment]
no idea :-(
i see some examples here -> https://www.softwaretestingmaterial.com/appium-with-nodejs-for-automation-testing-of-android-applications/

**Comment by fedorin-git** [comment]
Guys, thanks to everyone for the help! Problem solved with passing prop `disableScrollViewPanResponder` to `<ScrollView>`.
[Prop description](https://reactnative.dev/docs/scrollview) from the React Native docs:
> When true, the default JS pan responder on the ScrollView is disabled, and full control over touches inside the ScrollView is left to its child components. This is particularly useful if snapToInterval is enabled, since it does not follow typical touch patterns. Do not use this on regular ScrollView use cases without snapToInterval as it may cause unexpected touches to occur while scrolling.
