### ISSUE TITLE
Native App

### ISSUE THREAD

**Issue by VaishnaviGupt** [appium/appium#16336]
Can we automate the react native app through appium????
If yes, then while automating we are not able to find elements. Attaching the Screenshot

![image](https://user-images.githubusercontent.com/71331685/149514171-11475d0b-16c1-464e-ba34-be816b38126a.png)

Page Source:

<?xml version="1.0" encoding="UTF-8"?><AppiumAUT><XCUIElementTypeApplication type="XCUIElementTypeApplication" name="SAIB" label="SAIB" enabled="true" visible="true" x="0" y="0" width="428" height="926" index="0">
  <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" visible="true" x="0" y="0" width="428" height="926" index="0">
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="428" height="926" index="0">
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="428" height="926" index="0">
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="428" height="926" index="0">
          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="428" height="926" index="0">
            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="428" height="926" index="0">
              <XCUIElementTypeOther type="XCUIElementTypeOther" name="Welcome to SAIB Username Password Ok, proceed Already a client? Create your user! Not a client? Open your first account Toolbar Toolbar" label="Welcome to SAIB Username Password Ok, proceed Already a client? Create your user! Not a client? Open your first account Toolbar Toolbar" enabled="true" visible="true" x="0" y="0" width="428" height="926" index="0">
                <XCUIElementTypeOther type="XCUIElementTypeOther" name="Welcome to SAIB Username Password Ok, proceed Already a client? Create your user! Not a client? Open your first account Toolbar Toolbar" label="Welcome to SAIB Username Password Ok, proceed Already a client? Create your user! Not a client? Open your first account Toolbar Toolbar" enabled="true" visible="true" x="0" y="0" width="428" height="926" index="0">
                  <XCUIElementTypeOther type="XCUIElementTypeOther" name="Welcome to SAIB Username Password Ok, proceed Already a client? Create your user! Not a client? Open your first account Toolbar Toolbar" label="Welcome to SAIB Username Password Ok, proceed Already a client? Create your user! Not a client? Open your first account Toolbar Toolbar" enabled="true" visible="true" x="0" y="0" width="428" height="926" index="0">
                    <XCUIElementTypeOther type="XCUIElementTypeOther" name="Welcome to SAIB Username Password Ok, proceed Already a client? Create your user! Not a client? Open your first account Toolbar Toolbar" label="Welcome to SAIB Username Password Ok, proceed Already a client? Create your user! Not a client? Open your first account Toolbar Toolbar" enabled="true" visible="true" x="0" y="0" width="428" height="926" index="0">
                      <XCUIElementTypeOther type="XCUIElementTypeOther" name="Welcome to SAIB Username Password Ok, proceed Already a client? Create your user! Not a client? Open your first account Toolbar Toolbar" label="Welcome to SAIB Username Password Ok, proceed Already a client? Create your user! Not a client? Open your first account Toolbar Toolbar" enabled="true" visible="true" x="0" y="0" width="428" height="926" index="0">
                        <XCUIElementTypeOther type="XCUIElementTypeOther" name="Welcome to SAIB Username Password Ok, proceed Already a client? Create your user! Not a client? Open your first account Toolbar Toolbar" label="Welcome to SAIB Username Password Ok, proceed Already a client? Create your user! Not a client? Open your first account Toolbar Toolbar" enabled="true" visible="true" x="0" y="0" width="428" height="926" index="0">
                          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="428" height="926" index="0">
                            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="428" height="926" index="0">
                              <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="428" height="926" index="0">
                                <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="428" height="926" index="0">
                                  <XCUIElementTypeOther type="XCUIElementTypeOther" name="Welcome to SAIB Username Password Ok, proceed Already a client? Create your user! Not a client? Open your first account Toolbar" label="Welcome to SAIB Username Password Ok, proceed Already a client? Create your user! Not a client? Open your first account Toolbar" enabled="true" visible="true" x="0" y="0" width="428" height="926" index="0">
                                    <XCUIElementTypeOther type="XCUIElementTypeOther" name="Welcome to SAIB Username Password Ok, proceed Already a client? Create your user! Not a client? Open your first account Toolbar" label="Welcome to SAIB Username Password Ok, proceed Already a client? Create your user! Not a client? Open your first account Toolbar" enabled="true" visible="true" x="0" y="0" width="428" height="926" index="0">
                                      <XCUIElementTypeOther type="XCUIElementTypeOther" name="Welcome to SAIB Username Password Ok, proceed Already a client? Create your user! Not a client? Open your first account Toolbar" label="Welcome to SAIB Username Password Ok, proceed Already a client? Create your user! Not a client? Open your first account Toolbar" enabled="true" visible="true" x="0" y="0" width="428" height="926" index="0">
                                        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="428" height="926" index="0">
                                          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="428" height="926" index="0">
                                            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="428" height="926" index="0">
                                              <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="428" height="926" index="0">
                                                <XCUIElementTypeOther type="XCUIElementTypeOther" name="Welcome to SAIB Username Password Ok, proceed Already a client? Create your user! Not a client? Open your first account" label="Welcome to SAIB Username Password Ok, proceed Already a client? Create your user! Not a client? Open your first account" enabled="true" visible="true" x="0" y="0" width="428" height="926" index="0">
                                                  <XCUIElementTypeOther type="XCUIElementTypeOther" name="Welcome to SAIB Username Password Ok, proceed Already a client? Create your user! Not a client? Open your first account" label="Welcome to SAIB Username Password Ok, proceed Already a client? Create your user! Not a client? Open your first account" enabled="true" visible="true" x="0" y="0" width="428" height="926" index="0">
                                                    <XCUIElementTypeOther type="XCUIElementTypeOther" name="Welcome to SAIB Username Password Ok, proceed Already a client? Create your user! Not a client? Open your first account" label="Welcome to SAIB Username Password Ok, proceed Already a client? Create your user! Not a client? Open your first account" enabled="true" visible="true" x="0" y="0" width="428" height="926" index="0">
                                                      <XCUIElementTypeOther type="XCUIElementTypeOther" name="Welcome to SAIB Username Password Ok, proceed Already a client? Create your user! Not a client? Open your first account" label="Welcome to SAIB Username Password Ok, proceed Already a client? Create your user! Not a client? Open your first account" enabled="true" visible="true" x="0" y="0" width="428" height="926" index="0">
                                                        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="428" height="926" index="0">
                                                          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="428" height="926" index="0"/>
                                                        </XCUIElementTypeOther>
                                                        <XCUIElementTypeOther type="XCUIElementTypeOther" name="Welcome to SAIB Username Password Ok, proceed Already a client? Create your user! Not a client? Open your first account" label="Welcome to SAIB Username Password Ok, proceed Already a client? Create your user! Not a client? Open your first account" enabled="true" visible="true" x="0" y="0" width="428" height="926" index="1">
                                                          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="16" y="50" width="396" height="24" index="0">
                                                            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="16" y="50" width="70" height="24" index="0">
                                                            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="16" y="50" width="24" height="24" index="0"/>
                                                            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="62" y="50" width="24" height="24" index="1"/>
                                                            </XCUIElementTypeOther>
                                                            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="388" y="50" width="24" height="24" index="1"/>
                                                          </XCUIElementTypeOther>
                                                          <XCUIElementTypeOther type="XCUIElementTypeOther" name="Welcome to SAIB Username Password Ok, proceed Already a client? Create your user! Not a client? Open your first account" label="Welcome to SAIB Username Password Ok, proceed Already a client? Create your user! Not a client? Open your first account" enabled="true" visible="true" x="16" y="133" width="396" height="532" index="1"/>
                                                        </XCUIElementTypeOther>
                                                      </XCUIElementTypeOther>
                                                    </XCUIElementTypeOther>
                                                  </XCUIElementTypeOther>
                                                </XCUIElementTypeOther>
                                              </XCUIElementTypeOther>
                                            </XCUIElementTypeOther>
                                          </XCUIElementTypeOther>
                                        </XCUIElementTypeOther>
                                      </XCUIElementTypeOther>
                                    </XCUIElementTypeOther>
                                  </XCUIElementTypeOther>
                                </XCUIElementTypeOther>
                              </XCUIElementTypeOther>
                            </XCUIElementTypeOther>
                          </XCUIElementTypeOther>
                        </XCUIElementTypeOther>
                      </XCUIElementTypeOther>
                    </XCUIElementTypeOther>
                  </XCUIElementTypeOther>
                </XCUIElementTypeOther>
              </XCUIElementTypeOther>
            </XCUIElementTypeOther>
          </XCUIElementTypeOther>
        </XCUIElementTypeOther>
      </XCUIElementTypeOther>
    </XCUIElementTypeOther>
  </XCUIElementTypeWindow>
  <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" visible="false" x="0" y="0" width="428" height="926" index="1">
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="428" height="926" index="0">
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="0" width="428" height="926" index="0"/>
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="625" width="428" height="301" index="1">
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="625" width="428" height="243" index="0"/>
      </XCUIElementTypeOther>
    </XCUIElementTypeOther>
  </XCUIElementTypeWindow>
  <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" visible="true" x="0" y="0" width="428" height="926" index="2">
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="428" height="926" index="0">
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="625" width="428" height="301" index="0">
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="625" width="428" height="243" index="0">
          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="625" width="428" height="301" index="0">
            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="625" width="428" height="301" index="0">
              <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="625" width="428" height="301" index="0"/>
              <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="false" x="0" y="625" width="428" height="301" index="1"/>
            </XCUIElementTypeOther>
          </XCUIElementTypeOther>
        </XCUIElementTypeOther>
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="625" width="428" height="243" index="1">
          <XCUIElementTypeKeyboard type="XCUIElementTypeKeyboard" enabled="true" visible="true" x="0" y="625" width="428" height="243" index="0">
            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="625" width="428" height="243" index="0">
              <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="625" width="428" height="243" index="0">
                <XCUIElementTypeKey type="XCUIElementTypeKey" name="1" label="1" enabled="true" visible="true" x="2" y="632" width="43" height="49" index="0"/>
                <XCUIElementTypeKey type="XCUIElementTypeKey" name="2" label="2" enabled="true" visible="true" x="44" y="632" width="43" height="49" index="1"/>
                <XCUIElementTypeKey type="XCUIElementTypeKey" name="3" label="3" enabled="true" visible="true" x="87" y="632" width="43" height="49" index="2"/>
                <XCUIElementTypeKey type="XCUIElementTypeKey" name="4" label="4" enabled="true" visible="true" x="129" y="632" width="43" height="49" index="3"/>
                <XCUIElementTypeKey type="XCUIElementTypeKey" name="5" label="5" enabled="true" visible="true" x="171" y="632" width="44" height="49" index="4"/>
                <XCUIElementTypeKey type="XCUIElementTypeKey" name="6" label="6" enabled="true" visible="true" x="214" y="632" width="43" height="49" index="5"/>
                <XCUIElementTypeKey type="XCUIElementTypeKey" name="7" label="7" enabled="true" visible="true" x="256" y="632" width="43" height="49" index="6"/>
                <XCUIElementTypeKey type="XCUIElementTypeKey" name="8" label="8" enabled="true" visible="true" x="298" y="632" width="43" height="49" index="7"/>
                <XCUIElementTypeKey type="XCUIElementTypeKey" name="9" label="9" enabled="true" visible="true" x="341" y="632" width="43" height="49" index="8"/>
                <XCUIElementTypeKey type="XCUIElementTypeKey" name="0" label="0" enabled="true" visible="true" x="383" y="632" width="43" height="49" index="9"/>
                <XCUIElementTypeKey type="XCUIElementTypeKey" name="-" label="-" enabled="true" visible="true" x="2" y="688" width="43" height="49" index="10"/>
                <XCUIElementTypeKey type="XCUIElementTypeKey" name="/" label="/" enabled="true" visible="true" x="44" y="688" width="43" height="49" index="11"/>
                <XCUIElementTypeKey type="XCUIElementTypeKey" name=":" label=":" enabled="true" visible="true" x="87" y="688" width="43" height="49" index="12"/>
                <XCUIElementTypeKey type="XCUIElementTypeKey" name=";" label=";" enabled="true" visible="true" x="129" y="688" width="43" height="49" index="13"/>
                <XCUIElementTypeKey type="XCUIElementTypeKey" name="(" label="(" enabled="true" visible="true" x="171" y="688" width="44" height="49" index="14"/>
                <XCUIElementTypeKey type="XCUIElementTypeKey" name=")" label=")" enabled="true" visible="true" x="214" y="688" width="43" height="49" index="15"/>
                <XCUIElementTypeKey type="XCUIElementTypeKey" name="$" label="$" enabled="true" visible="true" x="256" y="688" width="43" height="49" index="16"/>
                <XCUIElementTypeKey type="XCUIElementTypeKey" name="ampersand" label="ampersand" enabled="true" visible="true" x="298" y="688" width="43" height="49" index="17"/>
                <XCUIElementTypeKey type="XCUIElementTypeKey" name="@" label="@" enabled="true" visible="true" x="341" y="688" width="43" height="49" index="18"/>
                <XCUIElementTypeKey type="XCUIElementTypeKey" name="&quot;" label="&quot;" enabled="true" visible="true" x="383" y="688" width="43" height="49" index="19"/>
                <XCUIElementTypeButton type="XCUIElementTypeButton" name="shift" label="symbols" enabled="true" visible="true" x="2" y="744" width="52" height="49" index="20"/>
                <XCUIElementTypeKey type="XCUIElementTypeKey" name="." label="." enabled="true" visible="true" x="68" y="744" width="58" height="49" index="21"/>
                <XCUIElementTypeKey type="XCUIElementTypeKey" name="," label="," enabled="true" visible="true" x="126" y="744" width="58" height="49" index="22"/>
                <XCUIElementTypeKey type="XCUIElementTypeKey" name="?" label="?" enabled="true" visible="true" x="184" y="744" width="57" height="49" index="23"/>
                <XCUIElementTypeKey type="XCUIElementTypeKey" name="!" label="!" enabled="true" visible="true" x="241" y="744" width="58" height="49" index="24"/>
                <XCUIElementTypeKey type="XCUIElementTypeKey" name="'" label="'" enabled="true" visible="true" x="298" y="744" width="59" height="49" index="25"/>
                <XCUIElementTypeKey type="XCUIElementTypeKey" name="delete" label="delete" enabled="true" visible="true" x="374" y="744" width="52" height="49" index="26"/>
                <XCUIElementTypeKey type="XCUIElementTypeKey" name="more" label="letters" enabled="true" visible="true" x="2" y="800" width="107" height="49" index="27"/>
                <XCUIElementTypeKey type="XCUIElementTypeKey" name="space" label="space" enabled="true" visible="true" x="108" y="800" width="213" height="49" index="28"/>
                <XCUIElementTypeButton type="XCUIElementTypeButton" name="Return" label="return" enabled="true" visible="true" x="320" y="800" width="106" height="49" index="29"/>
              </XCUIElementTypeOther>
            </XCUIElementTypeOther>
          </XCUIElementTypeKeyboard>
        </XCUIElementTypeOther>
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="625" width="428" height="301" index="2"/>
      </XCUIElementTypeOther>
    </XCUIElementTypeOther>
  </XCUIElementTypeWindow>
</XCUIElementTypeApplication></AppiumAUT>

**Comment by mykola-mokhnach** [comment]
Please use Appium forum to ask questions.

Appium/XCTest reflects exactly what the application exposes to the Accessibility manager. See https://github.com/appium/appium/issues/6517 for more details.
