### ISSUE TITLE
Cannot pull folder from an iOS device using Appium 1.22.1 and newer

### ISSUE THREAD

**Issue by yuraBukhniy** [appium/appium#16333]
## The problem

When trying to download any folder from app container, the pull_folder command ends with error:
ENOENT: no such file or directory, open '/var/folders/wc/nnrf56b94pv_gb70b4gcc5km0000gn/T/202206-74907-z6utme.a5t9/Documents/DLogFiles/file.log'
This problem is reproduced also on 1.22.2 and 1.23.0-beta, but is not reproduced on Appium 1.22.0 and older.

## Environment

* Appium version: 1.22.1+
* Last Appium version that did not exhibit the issue: 1.22.0
* Node.js version: 16.6.1
* Npm or Yarn package manager: npm
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

Appium 1.22.1 logs with error (row 187):
https://gist.github.com/yuraBukhniy/1e981998fd3c431a6b41e56b2c4bfaab

Appium 1.22.0 logs without error:
https://gist.github.com/yuraBukhniy/a24ac4458e2e1a84dae204bb42467b65

**Comment by mykola-mokhnach** [comment]
Could you please test if the patch https://github.com/appium/appium-xcuitest-driver/pull/1366 works for you?
The branch could be deployed locally for Appium1 similarly to what's described in https://github.com/appium/appium/issues/14693#issuecomment-684878582 or simply loaded from the local path is you use Appium2

**Comment by yuraBukhniy** [comment]
I tested the patch and in general it works. But I noticed that archive with pulled folder contains Documents folder, which in turn contains folder with the same name as target folder on the device to be pulled. 
For example, I pull "files" folder (path: @<bundleId>:documents/files/) with file.log inside and receive an archive with such structure: Documents/files/file.log. But I expected to see only content of the pulled folder in the archive (just file.log in my case) as it was up to Appium 1.22.0. It would be good to fix it if possible. Thanks

**Comment by yuraBukhniy** [comment]
I checked the latest version of appium-xcuitest-driver, pulling folders fixed, but now the issue with pulling the whole container appeared after that fix. If there are only folders and no files in the container, then `driver.pull_folder(@<bundleId>:documents/)` returns only content of the first container's folder, but not the whole container content.

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium-xcuitest-driver/pull/1367 should do the trick

**Comment by yuraBukhniy** [comment]
This works fine. Thank a lot!
What version of appium will this fix be available in?

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium-xcuitest-driver/pull/1367#issuecomment-1013330580

The driver is available in Appium2. Appium reached its EOL

**Comment by tiecongli** [comment]
May I know which version of appium has this fix? I am encountering the exact same error with appium 1.22.3
