### ISSUE TITLE
Unable to set webview context : TimeOut 24000ms exceeds

### ISSUE THREAD

**Issue by nanduri1805** [appium/appium#16345]
While trying to switch webview context getting time out error. appium driver identified the webview but yet unable to set

Am using:
Appium version 1.21
Android platform
Real device 
[appium-log.txt](https://github.com/appium/appium/files/7885097/appium-log.txt)

Error:  UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded

I have attached log for more info

**Comment by jlipps** [comment]
Not sure what would be going on. Things to try next:

1. Run that same chromedriver.exe that Appium picked on its own, and try to create a session with it directly.
2. Look at the adb logcat output to see if there are any potential issues.

**Comment by mykola-mokhnach** [comment]
Some more advices on top of what Jonathan has already mentioned:
- Update Appium to the most recent version
- Make sure you can debug the web view using the standard Chrome devtools

**Comment by mykola-mokhnach** [comment]
Closed because of no response
