### ISSUE TITLE
Appium is unable to click the element on Android studio emulator device

### ISSUE THREAD

**Issue by rakesh747** [appium/appium#16349]
Hello All,

I started using Appium with Webdriver.io & mocha to automate test scenarios for my native app in emulated android devices using android studio, so I've installed everything needed and I'm trying to run a simple code to at least open the app and click the elements to get started with my framework setup.

Environment

* Appium version (or git revision) that exhibits the issue: 1.22.2
* Last Appium version that did not exhibit the issue (if applicable): No
* Desktop OS/version used to run Appium: 1.22.0
* Node.js version (unless using Appium.app|exe): 16.9.0
* Npm or Yarn package manager: npm 7.21.1
* Mobile platform/version under test: 11
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: "@wdio/cli": "^7.16.13",

"dependencies": {
    "@wdio/cli": "^7.16.13",
    "appium-uiautomator2-driver": "^1.75.0",
    "chromedriver": "^94.0.0",
    "selenium-webdriver": "^4.1.1",
    "webdriverio": "^7.0.0"
  },
  "devDependencies": {
    "@wdio/appium-service": "^7.16.13",
    "@wdio/local-runner": "^7.16.13",
    "@wdio/mocha-framework": "^7.16.13",
    "@wdio/selenium-standalone-service": "^7.16.13",
    "@wdio/spec-reporter": "^7.16.13",
    "@wdio/sync": "^7.16.13",
    "appium": "^1.22.2",
    "appium-doctor": "^1.16.0",
    "chai": "^4.2.0"
  }

Details

I can see the session has been created and successfully ended after each execution and I can also see the demo app is open during the test but somehow it couldn't able to click on any element on the app and I'm always getting the below errors when i run the test --> 

[W3C (8eba3242)] Encountered internal error running the command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
[W3C (8eba3242)]     at UIA2Proxy.command (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:274:13)
[W3C (8eba3242)]     at runMicrotasks ()
[W3C (8eba3242)]     at processTicksAndRejections (internal/process/task_queues.js:85:5)
[Instrumentation] The process has exited with code 0

full log https://gist.github.com/rakesh747/028f78914f4f1a209ae2c5498b954508 

And when I debug the test I see the below error -->

[ADB] Getting install status for io.appium.android.apis
[ADB] Running '/Users/xxx/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.android.apis'
[W3C (8b988835)] Encountered internal error running command: TypeError: Cannot read property 'jwproxy' of null
[W3C (8b988835)]     at AndroidUiautomator2Driver.doFindElementOrEls (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-driver/lib/commands/find.js:32:36)
[W3C (8b988835)]     at condFn (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-driver/lib/commands/find.js:36:28)
[W3C (8b988835)]     at condFn (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/timeout.js:151:18)
[W3C (8b988835)]     at spin (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:138:26)
[W3C (8b988835)]     at waitForCondition (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:155:16)
[W3C (8b988835)]     at AndroidUiautomator2Driver.implicitWaitForCondition (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/timeout.js:153:16)
[W3C (8b988835)]     at AndroidUiautomator2Driver.findElOrEls (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-driver/lib/commands/find.js:60:16)
[W3C (8b988835)]     at AndroidUiautomator2Driver.findElOrElsWithProcessing (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:33:23)
[W3C (8b988835)]     at AndroidUiautomator2Driver.findElement (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:53:21)
[W3C (8b988835)]     at commandExecutor (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:335:9)
[W3C (8b988835)]     at /Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/async-lock/lib/index.js:146:12
[W3C (8b988835)]     at AsyncLock._promiseTry (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/async-lock/lib/index.js:280:31)
[W3C (8b988835)]     at exec (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/async-lock/lib/index.js:145:9)
[W3C (8b988835)]     at taskFn (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/async-lock/lib/index.js:174:4)
[W3C (8b988835)]     at done (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/async-lock/lib/index.js:114:29)
[W3C (8b988835)]     at /Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/async-lock/lib/index.js:149:5
[HTTP] <-- POST /wd/hub/session/8b988835-720a-4af9-bf81-e78355d8ced8/element 500 89 ms - 773

full log https://gist.github.com/rakesh747/da868a1899fb629f4ddd2d3398f9f244 

## Code To Reproduce Issue 

test class --> 

    const dialog = require('../../pageObjects/dialog.page');
    describe('Test', ()=>{
    beforeEach(() => {
    });
    it('Verify Media button is clickable', ()=>{

        try{
            dialog.mediaBtn.click();
            dialog.graphicsBtn.click();
        }
        catch (err){
            console.log(err);
        }
    });
    
    afterEach(() => {
        driver.reset();
    });
    })

PageObject class -->

    class Dialog {
      get mediaBtn() {return $("~Media");}
    }
    module.exports = new Dialog();

wdio.config -->

    let { join } = require('path');

    exports.config = {
    runner: 'local',
    port: 4723,
    path: '/wd/hub',
    specs: [
        './test/specs/Test.js'
    ],
    exclude: [
        // 'path/to/excluded/files'
    ],
    maxInstances: 1,
    capabilities: [{
        maxInstances: 5,
        path: '/wd/hub',
        platformName: 'Android', // iOS or Android or FirefoxOS
        'appium:deviceName':'Pixel 5',
        'appium:app': join(process.cwd(),'./ApiDemos-debug.apk'),
      }],
      logLevel: 'info',
      bail: 0,
      baseUrl: 'http://localhost',
      waitforTimeout: 10000,
      connectionRetryTimeout: 90000,
      connectionRetryCount: 3,
      services: ['selenium-standalone'],
      framework: 'mocha',
      reporters: ['spec'],
      mochaOpts: {
        ui: 'bdd',
        timeout: 60000
      },
      }

**Comment by mykola-mokhnach** [comment]
> [W3C (8b988835)] Calling AppiumDriver.reset() with args: ["8b988835-720a-4af9-bf81-e78355d8ced8"]
> [HTTP] --> DELETE /wd/hub/session/8b988835-720a-4af9-bf81-e78355d8ced8
> [HTTP] {}
> [W3C (8b988835)] Calling AppiumDriver.deleteSession() with args: ["8b988835-720a-4af9-bf81-e78355d8ced8"]

Please do not use reset API as it is [deprecated](https://github.com/appium/appium/issues/15807) and we will not apply any changes or fixes there.

**Comment by mykola-mokhnach** [comment]
I'm also not quite sure why it is necessary to import `appium-uiautomator2-driver` directly. This driver is part of Appium package and must be used in combination with it.

**Comment by rakesh747** [comment]
@mykola-mokhnach Thank you so much for responding back, I removed the driver.reset() from my code, also removed the appium-uiautomator2-driver from the package.json and did npm install, and then ran the test which is still giving me 404 no such element error 

full log here https://gist.github.com/rakesh747/dd0750a657d55f4a79df8ddf96e9bd3c 

could you please take a look?

**Comment by mykola-mokhnach** [comment]
> [W3C (c02656ca)] Calling AppiumDriver.findElement() with args: ["accessibility id","Media","c02656ca-c065-4c46-8290-14094bc8a40a"]
> [HTTP] --> DELETE /wd/hub/session/c02656ca-c065-4c46-8290-14094bc8a40a
> [HTTP] {}
> [W3C (c02656ca)] Calling AppiumDriver.deleteSession() with args: ["c02656ca-c065-4c46-8290-14094bc8a40a"]
> [B

I'm not quite sure what the client code is doing, but I don't observe any issues on the server side. The delete session request has been sent right after the request to find element and the session has been deleted as one might expect.

**Comment by rakesh747** [comment]
Yes, find element is working fine but the click() operation is not working in my case, do we need to specify any waits for the appium to execute click()?

**Comment by mykola-mokhnach** [comment]
Like I said above the issue seems to lie in the client code. This log looks correct from the server perspective, which means it is not an Appium issue.

You are welcome to use Appium forum to ask questions.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by jyotiManghna** [comment]
Hi,
I am getting this error "Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or t
[appium logs latest.txt](https://github.com/appium/appium/files/11210211/appium.logs.latest.txt)
he logcat output for more details"
[appium logs latest.txt](https://github.com/appium/appium/files/11210213/appium.logs.latest.txt)

Kindly help.
