### ISSUE TITLE
Appium 2 - XcuiTest driver args unrecognized wdaLocalPort 

### ISSUE THREAD

**Issue by Auto81** [appium/appium#16340]
## The problem

When trying to use `appium server --driver-args='{"xcuitest":{"wdaLocalPort": 8104}}'` with Appium 2.0.0-beta.23 it throws the following error

`appium: error: unrecognized arguments: --driver-args`

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 2.0.0-beta.23
* Last Appium version that did not exhibit the issue (if applicable):Appium 2.0.0-beta.19 (works when i roll back to this version)
* Desktop OS/version used to run Appium: Appium 2 CLI
* Node.js version (unless using Appium.app|exe): 14.15.4
* Npm or Yarn package manager: npm
* Mobile platform/version under test: ios using xcuitest@3.59.1
* Real device or emulator/simulator: Sim

**Comment by jlipps** [comment]
`--driver-args` was abandoned in favour of config schemas. These are provided by driver devs. If you have appium 2 beta and a recent version of the xcuitest driver, you can find the appropriate driver-specific flags in the help:

```
appium server --help
```

will produce this as part of the output:

```
  --driver-xcuitest-webdriveragent-port WEBDRIVERAGENT_PORT
                        Local port used for communication with WebDriverAgent
  --driver-xcuitest-webkit-debug-proxy-port WEBKIT_DEBUG_PROXY_PORT
                        (Real device only) Port to which `ios-webkit-debug-proxy` is connected
```

So you can simply run:

```
appium server --driver-xcuitest-webdriveragent-port 8104
```

**Comment by Auto81** [comment]
Have updated all device scripts to use '--driver-xcuitest-webdriveragent-port <UniquePort>'

When running tests, commands from one test are running on the wrong device sometimes. Looks to be the same behaviour as when I just dont provide 'driver-xcuitest-webdriveragent-port' 

From logs it looks like it is just using default port across all devices on the grid

`[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100`

What else can I provide to help find a fix?

**Comment by mykola-mokhnach** [comment]
Could you please provide the full log?

**Comment by mykola-mokhnach** [comment]
also make sure the xcuitest driver itself is up to date

**Comment by Auto81** [comment]
xcuitest @ 3.59.2
xcode @ 13.2.1
appium @ 2.0.0-beta.24

Below is copy of log when running 1 test with '--driver-xcuitest-webdriveragent-port 8101' set
https://gist.github.com/Auto81/c19e8050869362c0f0d6f4dc337b3b55

**Comment by mykola-mokhnach** [comment]
Thanks. I would expect the provided wda port value to be reflected somewhere in the log, but it is not there. Might be an issue though. @boneskull could you please take a quick look?

**Comment by Auto81** [comment]
Gist of --show-config, shows that its reading it in

https://gist.github.com/Auto81/4107df8079be2ed21f28aaaa0e754d4d

**Comment by mykola-mokhnach** [comment]
I assume there might be an issue while caps are loaded from a json config file. We definitely did not test this case since Grid 4 has been released quite long time ago.

**Comment by Auto81** [comment]
Still running grid 3 here

**Comment by jlipps** [comment]
Yeah, this all looks correct to me. @boneskull can you see anything related to config that might be off here?

**Comment by jlipps** [comment]
One thing to investigate: the driver creates a new wda instance using `this.opts`. I forget where we landed on these things, but maybe driver args are not added to this.opts by default? So there would be a code update required in the xcuitest driver to merge the driver arg onto opts, or else make sure it gets passed into the WDA constructor?

**Comment by boneskull** [comment]
I'll take a look

**Comment by boneskull** [comment]
showConfig isn't behaving quite how i'd like either, ugh

**Comment by boneskull** [comment]
See appium/appium-xcuitest-driver#1372

**Comment by jlipps** [comment]
Since https://github.com/appium/appium-xcuitest-driver/pull/1372 has been merged, within the next day or two a new xcuitest driver should be auto-published, which you can then upgrade to via the CLI to get the fix.

**Comment by jlipps** [comment]
thanks to @boneskull for the fix!

**Comment by Auto81** [comment]
> Since [appium/appium-xcuitest-driver#1372](https://github.com/appium/appium-xcuitest-driver/pull/1372) has been merged, within the next day or two a new xcuitest driver should be auto-published, which you can then upgrade to via the CLI to get the fix.

Looks to have been published already :)

Installed and back to parallel glory, thank everyone and @boneskull for fix!

**Comment by boneskull** [comment]
glad it worked!  lol
