### ISSUE TITLE
setGeoLocation not setting the device location [tested on windows 10/android emulator, appium 2.0 beta]

### ISSUE THREAD

**Issue by PramodKumarYadav** [appium/appium#16341]
## The problem
setGeoLocation not setting the device location (or sets the location intermittently. Say once in 15-20 runs). 

## Environment

* Appium version (or git revision) that exhibits the issue:
   PS C:\Program Files\PowerShell\7> appium --version
   `2.0.0-beta.18`
* Last Appium version that did not exhibit the issue (if applicable):
  `Not sure`
* Desktop OS/version used to run Appium:
  `Windows 10 Pro/Version 20H2`
* Node.js version (unless using Appium.app|exe):
  PS C:\Program Files\PowerShell\7> node --version
  `v16.9.1`
* Npm or Yarn package manager:
  PS C:\Program Files\PowerShell\7> npm --version
  `7.21.1`
* Mobile platform/version under test:
  `Android/11.0`
* Real device or emulator/simulator:
  `Emulator: Pixel_2_API_30`
* Appium CLI or Appium.app|exe:
  `Appium CLI`

## Details

I am trying to set my android emulator location to a location of my test application. For this I am usin g

## Link to Appium logs

Here are full appium logs as a gist: https://gist.github.com/PramodKumarYadav/d8e0981b41f5484c2c6cd12668a30c98 

The logs to pay attention is the part where I change location using setLocation but it still gives the old location. 

```
[HTTP] --> GET /wd/hub/session/123af56c-a745-453e-a771-806b78271113/location
[HTTP] {}
[debug] [W3C (123af56c)] Calling AppiumDriver.getGeoLocation() with args: ["123af56c-a745-453e-a771-806b78271113"]
[debug] [ADB] Running 'C:\Users\Pramod Yadav\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell am broadcast -n io.appium.settings/.receivers.LocationInfoReceiver -a io.appium.settings.location'
[debug] [ADB] Got geo coordinates: {"latitude":"53.3631000","longitude":"5.8982983","altitude":"1.0000000"}
[debug] [W3C (123af56c)] Responding to client with driver.getGeoLocation() result: {"latitude":53.3631,"longitude":5.8982983,"altitude":1}
[HTTP] <-- GET /wd/hub/session/123af56c-a745-453e-a771-806b78271113/location 200 247 ms - 65
[HTTP]
[HTTP] --> POST /wd/hub/session/123af56c-a745-453e-a771-806b78271113/location
[HTTP] {"location":{"altitude":1,"latitude":52.3631,"class":"org.openqa.selenium.html5.Location","longitude":4.8983}}
[debug] [W3C (123af56c)] Calling AppiumDriver.setGeoLocation() with args: [{"altitude":1,"latitude":52.3631,"class":"org.openqa.selenium.html5.Location","longitude":4.8983},"123af56c-a745-453e-a771-806b78271113"]
[debug] [ADB] Running 'C:\Users\Pramod Yadav\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 emu geo fix 4.8983 52.3631 1'
[debug] [ADB] Running 'C:\Users\Pramod Yadav\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 emu geo fix 4,8983 52,3631 1'
[debug] [ADB] Running 'C:\Users\Pramod Yadav\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell am broadcast -n io.appium.settings/.receivers.LocationInfoReceiver -a io.appium.settings.location'
[debug] [ADB] Got geo coordinates: {"latitude":"53.3631000","longitude":"5.8982983","altitude":"1.0000000"}
[debug] [W3C (123af56c)] Responding to client with driver.setGeoLocation() result: {"latitude":53.3631,"longitude":5.8982983,"altitude":1}
[HTTP] <-- POST /wd/hub/session/123af56c-a745-453e-a771-806b78271113/location 200 313 ms - 65
```

## Code To Reproduce Issue [ Good To Have ]

Here is the class that I use to set/get geolocation: https://gist.github.com/PramodKumarYadav/2e4795b20a75dc3f4c3994cbfdb4c756

Part of the test code (in Java), where I check the location before and after setting location is  here. 
```
GeoLocation geoLocation = new GeoLocation(driver);

homeScreen.tapMyLocationButton();
log.info("location before change: {}", geoLocation.getGeoLocation());

// Change location once.
geoLocation.setGeoLocation(52.3631, 4.8983);

homeScreen.tapMyLocationButton();
log.info("location after change: {}", driver.location());
```

**Comment by mykola-mokhnach** [comment]
> [debug] [ADB] Running 'C:\Users\Pramod Yadav\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 emu geo fix 4.8983 52.3631 1'
> [debug] [ADB] Running 'C:\Users\Pramod Yadav\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 emu geo fix 4,8983 52,3631 1'

This looks totally correct to me. Maybe just wait for a while until the location is actually updated.
Also it would be good to see the logcat output

**Comment by mykola-mokhnach** [comment]
The Appium Settings app, which is actually used to fetch GPS coordinates, is configured to fetch these in [battery saving mode](https://github.com/appium/io.appium.settings/blob/7495aaaecfb7fcde90b0f09f33b3802b8d1704a7/app/src/main/java/io/appium/settings/LocationTracker.java#L139), which might take quite a while until the next coordinate refresh happens. 

As a possible workaround you could try https://github.com/appium/appium-uiautomator2-driver#mobile-refreshgpscache extension (uia2 driver must be up to date in order for it to work)

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
