### ISSUE TITLE
Unable to inspect individual elements in appium for iOS build

### ISSUE THREAD

**Issue by Sagar-D** [appium/appium#16351]
## The problem

In iOS builds, when we try to inspect elements using Appium inspector, wee see that multiple elements (or all the elements in the screen) are showing up as single node.
<img width="1792" alt="Screenshot 2022-01-17 at 1 44 23 PM" src="https://user-images.githubusercontent.com/20160725/150079485-666a9794-06df-4659-8b6d-8ecd1ef6778c.png">

## Environment

* Appium version: 1.22.2
* Desktop OS/version used to run Appium: Mac
* Node.js version : v14.15.1
* Mobile platform/version under test: iOS (ReactNative Project)
* Real device : iPhone SE

**Comment by KazuCocoa** [comment]
Perhaps developers should coordinate the elements by https://reactnative.dev/docs/accessibility , for example, so that iOS can handle each element. Probably iOS's accessibility mechanism combines elements as a single node for them.

**Comment by mykola-mokhnach** [comment]
There is nothing that could be done from Appium side to change that. It displays exactly what the application under test exposes to the accessibility layer. Closed as not an issue.
