### ISSUE TITLE
add feature uploadRecordedMedia flag in stopRecordingScreen()

### ISSUE THREAD

**Issue by napiera** [appium/appium#16361]
## The problem

There is no file upload flag in stopRecordingScreen. (docs: [stop-recording-screen](https://appium.io/docs/en/commands/device/recording-screen/stop-recording-screen/))

## Details

The uploadRecordedMedia() always called in appium-android-driver. ([SourceCode](https://github.com/appium/appium-android-driver/blob/master/lib/commands/recordscreen.js#L335))

I want to receive a recorded video file according to my condition.
So, if I don't want to receive the file, just delete the session without calling StopRecordingScreen().

## Code To Reproduce Issue [ Good To Have ]

I hope the file upload flag is added to stopRecordingScreen().

ex. 
`if(options.fileUploadFlag) {`
`    return await uploadRecordedMedia(resultFilePath, options.remotePath, options);`
`}`

**Comment by mykola-mokhnach** [comment]
Unfortunately there is no easy way to change that. Video recording sessions are coupled with driver sessions. Rewiring of that logic that would require to revamp many things in the driver.

**Comment by napiera** [comment]
Dear @mykola-mokhnach

First of all, thank you for replying to my comment.

My opinion to solve this issue, not revamp many things in the drive, just add the 'fileUploadFlag' parameter to stopRecordingScreen function. ([SourceCode](https://github.com/appium/appium-android-driver/blob/master/lib/commands/recordscreen.js#L282))


Detail logic below.
'1. Call startRecordingScreen()
'2. ...Do test...
'3. Check my condition.

'3-A. (If I want to receive the recording file) Call stopRecordingScreen( options.fileUploadFlag = true )
'3-A-1. Recevice the file from device to appium server, and send to me
'3-A-2. Delete Session

'3-B. (If I do not want to receive the recording file) Call stopRecordingScreen( options.fileUploadFlag = false )
'3-B-1. Recevice the file from device to appium server
'3-B-2. But don't send me the file. (do not call uploadRecordedMedia() functino)
'3-A-3. Delete Session

I ask for your understanding regarding this metter
Thank you

**Comment by mykola-mokhnach** [comment]
> '3-A. (If I want to receive the recording file) Call stopRecordingScreen( options.fileUploadFlag = true )
> '3-A-1. Recevice the file from device to appium server, and send to me
> '3-A-2. Delete Session
> 
> '3-B. (If I do not want to receive the recording file) Call stopRecordingScreen( options.fileUploadFlag = false )
> '3-B-1. Recevice the file from device to appium server
> '3-B-2. But don't send me the file. (do not call uploadRecordedMedia() functino)
> '3-A-3. Delete Session

Isn't this possible now? One just don't have to provide options for the remote server, so then nothing gets uploaded upon calling stopRecord
