### ISSUE TITLE
Real device iPhoneXr on iOS 15.2: Could not navigate to webview!

### ISSUE THREAD

**Issue by DuXspace** [appium/appium#16367]
## The problem

After running test on Safari browser, WebDriverAgent is signed and installed on device, Safari is opened and than test failed with error:
An unknown server-side error occurred while processing the command. Original error: Could not navigate to webview! Err: Failed to receive any data within the timeout: 5000

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22/1.23.0-beta.0 -also tried desktop version
* Last Appium version that did not exhibit the issue (if applicable): not applicable
* Desktop OS/version used to run Appium: MacOs Monterey 12.1
* Node.js version (unless using Appium.app|exe): v17.3.1
* Npm or Yarn package manager: Npm
* Mobile platform/version under test: iOS 15.2
* Real device or emulator/simulator: Real device iphone xr
* Appium CLI or Appium.app|exe:

## Details

Tried to reinstall webDriverAgent, reboot phone etc.
Checked that webView is available from Safari Remote debugger
Checked settings->developer-> Enable UI Automation
Checked settings->Safari->advanced->Web Inspector and Remote Automation are enabled

## Link to Appium logs

https://gist.github.com/DuXspace/e70051e8af1ac2bad84d91e1e5b13895

## Code To Reproduce Issue [ Good To Have ]

from appium import webdriver

desired_caps = {
    "automationName": "XCUITest",
    "platformName": "iOS",
    "deviceName": "iPhone Xr",
    "platformVersion": "15.2",
    "browserName": "Safari",
    "xcodeOrgId": "FCSM7534VM",
    "autoWebview": True,
    "xcodeSigningId": "iPhone Developer",
    "udid": "00008020-001204CA3CD8003A",
    "safariInitialUrl": "https://www.github.com",
    "webviewConnectTimeout": 90000
}

driver = webdriver.Remote('0.0.0.0:4723/wd/hub', desired_caps)

**Comment by DuXspace** [comment]
`# Appium Python client
from appium import webdriver

desired_caps = {
    "automationName": "XCUITest",
    "platformName": "iOS",
    "deviceName": "iPhone Xr",
    "platformVersion": "15.2",
    "browserName": "Safari",
    "xcodeOrgId": "FCSM7534VM",
    # "autoWebview": True,
    "xcodeSigningId": "iPhone Developer",
    "udid": "auto",
    "safariInitialUrl": "https://www.github.com",
    "orientationSet": "PORTRAIT",
    "webviewConnectTimeout": 90000
}

# Connect to Appium server on local host
driver = webdriver.Remote('0.0.0.0:4723/wd/hub', desired_caps)`

**Comment by DuXspace** [comment]
also tried to run on simulator and it works properly

**Comment by KazuCocoa** [comment]
Your log:
```
[debug] [XCUITest] Waiting for initial webview
[debug] [XCUITest] Navigating to most recently opened webview
[debug] [XCUITest] Retrieving contexts and views
[debug] [XCUITest] Selecting by url: false
[RemoteDebugger] Remote Debugger version 8.13.2
[debug] [RemoteDebugger] useNewSafari --> false
[debug] [RemoteDebugger] Checking which communication style to use (Safari on platform version '15.2')
[debug] [RemoteDebugger] Platform version equal or higher than '12.2': true
[RemoteDebugger] Setting communication protocol: using Target-based communication
[XCUITest] {}
[debug] [WD Proxy] Matched '/session/32c8730d-8fdc-4a32-a43a-75a2f49959ae' to command name 'deleteSession'
```

Quickly tested on a 15.3 device on my local with appium 1.22.2
```
2022-01-24 11:27:10:328 - [debug] [XCUITest] Waiting for initial webview
2022-01-24 11:27:10:328 - [debug] [XCUITest] Navigating to most recently opened webview
2022-01-24 11:27:10:328 - [debug] [XCUITest] Retrieving contexts and views
2022-01-24 11:27:10:328 - [debug] [XCUITest] Selecting by url: false 
2022-01-24 11:27:10:329 - [RemoteDebugger] Remote Debugger version 8.13.2
2022-01-24 11:27:10:329 - [debug] [RemoteDebugger] useNewSafari --> false
2022-01-24 11:27:10:330 - [debug] [RemoteDebugger] Checking which communication style to use (Safari on platform version '15.3')
2022-01-24 11:27:10:330 - [debug] [RemoteDebugger] Platform version equal or higher than '12.2': true
2022-01-24 11:27:10:330 - [RemoteDebugger] Setting communication protocol: using Target-based communication
2022-01-24 11:27:10:584 - [debug] [RemoteDebugger] Sending connection key request
2022-01-24 11:27:10:585 - [debug] [RemoteDebugger] Sending '_rpc_reportIdentifier:' message (id: 0): 'setConnectionKey'
2022-01-24 11:27:10:586 - [debug] [RemoteDebugger] Sending to Web Inspector took 2ms
2022-01-24 11:27:10:586 - [debug] [RemoteDebugger] Sending connection key request
2022-01-24 11:27:10:586 - [debug] [RemoteDebugger] Sending '_rpc_reportIdentifier:' message (id: 2): 'setConnectionKey'
2022-01-24 11:27:10:587 - [debug] [RemoteDebugger] Sending to Web Inspector took 1ms
2022-01-24 11:27:10:588 - [debug] [RemoteDebugger] Selecting application
```

I guess something connection issue occurred between your device under test and appium, or this was by macOS Monterey 12.1 stuff... I don't have Monterey environment for now though.

**Comment by DuXspace** [comment]
@KazuCocoa maybe, but it works properly when i using automationName: Safari driver
Maybe problem with device, next week I'll try run it on different iOS devices, also if I find another version of macOS i'll try it to

**Comment by alvarolgn** [comment]
> @KazuCocoa maybe, but it works properly when i using automationName: Safari driver Maybe problem with device, next week I'll try run it on different iOS devices, also if I find another version of macOS i'll try it to

Hi @DuXspace , did you try it in another macOS version? Did it work?

**Comment by KazuCocoa** [comment]
I've upgraded my macOS to 12.2. The version and Xcode 13.1 against iOS 15.2 did not get any issues as same as 
 https://github.com/appium/appium/issues/16367#issuecomment-1021675330 ...

I don't have 12.1 so potentially this issue could be in the version though...

**Comment by KazuCocoa** [comment]
Moves to https://github.com/appium/appium/issues/16399.
OpenSSL 1.1 based node process should work at least.
