### ISSUE TITLE
Windows app automation - Application failed to launch with multiple appArguments values

### ISSUE THREAD

**Issue by bwomsm1** [appium/appium#16371]
## The problem
My windows application is being launched with 2 arguments files.
I am adding them to the appArguments field in the capabilities, but the app won't launch with them.

**Appium version: 2.0.0-beta.24**
Running appium from CLI.

This is the code which I am trying to execute is mentioned below

## Environment

* Appium version (or git revision) that exhibits the issue: 2.0 Beta
* Last Appium version that did not exhibit the issue (if applicable): Never tried
* Desktop OS/version used to run Appium: Windows
* Node.js version (unless using Appium.app|exe):v16.13.2
* Npm or Yarn package manager: 
* Mobile platform/version under test: Windows OS app
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

[Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!
](https://github.com/bwomsm1/AppiumLogs/blob/master/win_app_appium.log)

## Code To Reproduce Issue [ Good To Have ]
```
from appium.webdriver import Remote
from time import sleep

def main():
    dc = {
        'app': 'C:\\Program Files (x86)\\AeroScout\\AeroScout Engine Manager\\bin\\Rte\\EngineManager.exe',
        'platformName': 'Windows',
        'platformVersion': '10',
        'automationName': 'Windows',
        'appArguments': "C:\\Program Files (x86)\\AeroScout\\AeroScout Engine Manager\\bin\\Config\\ShellLayout.xml C:\Program Files (x86)\\AeroScout\\AeroScout Engine Manager\\bin\\Config\\ShellCnf.xml",
    }
    driver = Remote('127.0.0.1:4723', dc)
    sleep(5)

    print(driver.page_source)

if __name__ == '__main__':
    main()
```

**Comment by KazuCocoa** [comment]
Appium sends `appArguments` as below.

> {"desiredCapabilities":{"platformName":"Windows","app":"C:\\Program Files (x86)\\AeroScout\\AeroScout Engine Manager\\bin\\Rte\\EngineManager.exe","platformVersion":"10","automationName":"Windows","appArguments":"C:\\Program Files (x86)\\AeroScout\\AeroScout Engine Manager\\bin\\Config\\ShellLayout.xml C:\\Program Files (x86)\\AeroScout\\AeroScout Engine Manager\\bin\\Config\\ShellCnf.xml"}}

So, do you know of if https://github.com/microsoft/WinAppDriver accepts space-separated `appArguments`?
I wonder the win app driver itself does not accept the format.

**Comment by bwomsm1** [comment]
@KazuCocoa thanks for replying,
I am not sure myself what is the syntax, it does not mentioned, could not find it either on web,
But it is allowed to pass a few arguments.

Do you have an idea where I can find the answer?

**Comment by bwomsm1** [comment]
Btw I tried many conventions:
'"param_1" "param_2"'
"param_1" "param_2"
.....

**Comment by KazuCocoa** [comment]
I think the best way is to ask it in https://github.com/microsoft/WinAppDriver or the community. Basically appium proxies commands to the driver, so the behavior depends on WinAppDriver.

**Comment by KazuCocoa** [comment]
https://github.com/microsoft/WinAppDriver/issues/1673

**Comment by bwomsm1** [comment]
> [microsoft/WinAppDriver#1673](https://github.com/microsoft/WinAppDriver/issues/1673)

well, that is indeed my issue I opened there, but no solution yet.

Thank you guys.
