### ISSUE TITLE
fail to quit the driver after take a screen shot on iOS simulator

### ISSUE THREAD

**Issue by earlif** [appium/appium#16373]
## The problem

fail to quit the driver after take a screen shot on iOS simulator

## Environment

* Appium version (or git revision) that exhibits the issue:1.22.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:MAC 12.0.1
* Node.js version (unless using Appium.app|exe):17.4.0
* Npm or Yarn package manager:
* Mobile platform/version under test:iOS 14.3
* Real device or emulator/simulator:simulator
* Appium CLI or Appium.app|exe:CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
https://gist.github.com/earlif/0679e85fc78f419e57ed1ad0c7dd702d

## Code To Reproduce Issue [ Good To Have ]

        RemoteWebDriver driver;
        System.out.println("init mobile driver");
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("bundleId", "com.apple.mobilecal");
        capabilities.setCapability(DEVICE_NAME, "iPhone zp");
        capabilities.setCapability(PLATFORM_NAME, "iOS");
        capabilities.setCapability(PLATFORM_VERSION, "14.3");
        capabilities.setCapability(AUTOMATION_NAME, "XCUITest");
        capabilities.setCapability(UDID, "2511ADFC-A9E7-4562-B953-BA2DAD4CE1F5");

        try {
            URL url = new URL("http://0.0.0.0:4723/wd/hub");
            driver = new IOSDriver(url, capabilities);
            System.out.println("init driver:" + driver);
        } catch (Exception e) {
            System.out.println("init driver exception:" + e.getMessage());
        }

        File screenFile = driver.getScreenshotAs(OutputType.FILE);
        File file = new File("target/screenshots/screenshotName.png");
        try {
            FileUtils.copyFile(screenFile, file);
            System.out.println("Screenshot is saved successfully: " + file.getAbsolutePath());
        } catch (IOException e) {
            System.out.println("Failed to save screenshot: " + e.getLocalizedMessage());
        }

      driver.quit();

**Comment by earlif** [comment]
If I don't set the bundleId, it can take the screenshot of the HOME page and quit successfully.

**Comment by mykola-mokhnach** [comment]
> https://gist.github.com/earlif/0679e85fc78f419e57ed1ad0c7dd702d#file-failtoquitaftertakescreenshot-L146

According to the logs XCTest is unable to fetch a screenshot from the application. Unfortunately we cannot do nothing about it as WDA also acts as a simple client there. You could try to report your issue to Apple though.

**Comment by earlif** [comment]
> > https://gist.github.com/earlif/0679e85fc78f419e57ed1ad0c7dd702d#file-failtoquitaftertakescreenshot-L146
> 
> According to the logs XCTest is unable to fetch a screenshot from the application. Unfortunately we cannot do nothing about it as WDA also acts as a simple client there. You could try to report your issue to Apple though.

Actually, it already generated this file: File file = new File("target/screenshots/screenshotName.png");

**Comment by earlif** [comment]
1. using Appium desktop 1.21.0 with bundleId "com.apple.mobilecal", can generate the image of the calculator, and quit the driver successfully.
2. using Appium 1.22.2 with bundleId "com.apple.mobilecal", can generate the image of the calculator, but fail to quit the driver.
3. using Appium 1.22.2 with NO bundleId, can generate the image of HOME and quit the driver successfully.

**Comment by earlif** [comment]
And there is another problem: If I take the screenshot of an app, and quit the driver failed, then I can not connect to the driver unless I delete "WebDriverAgent" on iOS.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue. Unfortunately we cannot do nothing about xctest-specific issues.
