### ISSUE TITLE
Not able to locate child element with Appium Inspector, but can see testID in parent app source

### ISSUE THREAD

**Issue by wjeanbaptiste** [appium/appium#16376]
Hello,

I am having some issues with locating the Navigation bar (highlighted by me in the picture) on my React Native iOS app. I have a function which handles setting test Id and accessibility, accessibilityLabel for any component and I have that on my avatar (WJ) as well as the home button. 

## Environment

* Appium version (or git revision) that exhibits the issue: Server 1.22.0 Inspector 2021.12.2
* Desktop OS/version used to run Appium: macOS Monterey 12.0.1
* Mobile platform/version under test: iOS 15.2 Simulator
* Real device or emulator/simulator: iPad Pro 12.9 5th Generation

The Appium inspector recognizes everything else on this page, except for this Navigation component.

What makes things weirder is that while I can’t identify the element with the Appium inspector (or the search for Id/Accessibility Id), I can see that in the parent component in the App Source, my test IDs are being listed along with the whole app!!

![MicrosoftTeams-image](https://user-images.githubusercontent.com/96075200/151389218-8ef1c845-b756-4dbd-8f97-72e618a042a3.png)

Furthermore, I can identify these elements when accessibility is set to true and I use the Xcode inspector. 

Is there a way to disable the entire parent component so it’s not grouping everything into one component?

Here is the return for my App.tsx, where the Navigation is being called.

```
  return (
    <AuthContext.Provider value={{authToken, setAuthToken}}>
      <NavigationContainer linking={Linking} ref={navigationRef}>
        {!authToken && (
          <Stack.Navigator>
            <Stack.Screen
              name={Routes.SIGN_IN}
              component={SignInScreen}
              options={HIDE_STACK_HEADER}
            />
          </Stack.Navigator>
        )}
        {authToken && (
          <Stack.Navigator>
            <Stack.Screen
              name={Routes.HOME}
              component={HomeScreen}
              options={HIDE_STACK_HEADER}
            />
            <Stack.Screen
              name={Routes.REQUEST_DETAILS}
              component={RequestDetailsScreen}
              options={HIDE_STACK_HEADER}
            />
          </Stack.Navigator>
        )}
      </NavigationContainer>
      {authToken && <Navigation />}
      <Drawer />
      <VideoView />
      <Toaster id={NotifierIds.TOASTER} position={ToasterPositions.RIGHT} />
    </AuthContext.Provider>
  );
```

Here is part of my Navigation component, notice I have accessibility set to false on the main component.

```
  return (
    <View accessible={false} style={[TAB_STYLES.container, PlatformHelper.isIOS && TAB_STYLES.ios]}>
…
      <View
        accessible={false}
        style={[
          TAB_STYLES.side,
          {height: height - Sizing.BASE * (PlatformHelper.isIOS ? 6 : 4)},
        ]}>
        {_.map(navRouteButtons, (button: NavigationRouteButton) => (
          <TouchableOpacity
          {...accessibility("navigation-home")}
            key={button.route}
            style={TAB_STYLES.navRouteButton}
            onPress={() => {
              InactivityHelper.onAction();
              navigate(button.route, button.params);
            }}>
            {button.icon}
          </TouchableOpacity>
    …
<View>
          <TouchableOpacity
            {...accessibility("navigation-avatar")}
            style={TAB_STYLES.avatar}
            onPress={() => {
              InactivityHelper.onAction();
              setDropdownVisible(!dropdownVisible);
            }}>
            {getUserInitials()}
          </TouchableOpacity>
        </View>
      …      </View>
    </View>
  );
```

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing that we could change there. Appium retrieves the page source from XCTest based on the accessibility info from your app. Try to report the issue to Apple or Facebook.

**Comment by jlipps** [comment]
This has to do with how React Native applies accessibility settings. It does some strange things sometimes. I'd check around the RN issues/forums to get help applying accessibility ids correctly using the RN APIs.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
