### ISSUE TITLE
Error of [INSTALL_FAILED_OLDER_SDK] when linking Android 4.2.2 Redmi phone

### ISSUE THREAD

**Issue by billy8407** [appium/appium#16377]
## The problem
Hi, 
I'm trying to start Appium server by desktop app, 
then link my phone(Redmi 1S) when using built-in message app
but it failed when started to use Appium Inspector to link the phone.

Both of the logs (please refer to the `Link to Appium logs` section which described below) 
are related about `[INSTALL_FAILED_OLDER_SDK]`,
but after searched in google,
there shows this is caused by the `android:minSdkVersion` which used when write android apps,
so I had no idea what's going on.

By the way,
my Redmi android version is 4.2.2,
and I had installed android studio which contains some tools.
the post important parts are 
`Android4.2` , `Android SDK Build-tools32`, `Android SDK Plat-form Tools`(31.0.3),
and I also tried to install the upper and lower of android versions,
but it occurred  the same problems also.

And my desktop Appium apps also set variable `ANDROID_HOME` path which showed in android studio
and `JAVA_HOME` which jdk version is `16.0.2`,
they are also setting in Windows environment variable.

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):1.22.0
* Desktop OS/version used to run Appium: windows 10 pro
* Node.js version (unless using Appium.app|exe): 12.8.1 (built in desktop apps)
* Npm or Yarn package manager: None
* Mobile platform/version under test: Android 4.2.2
* Real device or emulator/simulator: Real device (Redmi 1S)
* Appium CLI or Appium.app|exe: Appium desktop app

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
driver
* uiautomator1
desktop app error response
https://gist.github.com/billy8407/7b7285c5bc406a4b92831c025d79a5a6
server error log
https://gist.github.com/billy8407/2684178fd418c1574dec59813c9950a1
* espresso
desktop app error response
https://gist.github.com/billy8407/6dd11a6301075e00f52d856774cf9a27
server error log
https://gist.github.com/billy8407/0b577ea67d7aade817555aa6d6cbb7ae
## Code To Reproduce Issue [ Good To Have ]

Appium desktop app's json of Desired Capabilities
~~~
{
  "platformName": "Android",
  "appium:platformVersion": "4.2.2",
  "appium:automationName": "uiautomator1",
  "appium:deviceName": "6DS8UKY9QKKJFYFQ",
  "appium:appPackage": "com.android.mms",
  "appium:appActivity": ".ui.MmsTabActivity"
}
~~~

**Comment by amedvedjev** [comment]
https://appium.io/docs/en/about-appium/platform-support/ -> 
**Versions 4.3 and up** are supported via Appium's UiAutomator and UiAutomator2 libraries.

**Comment by mykola-mokhnach** [comment]
I don't think this is going to work. This phone is too old.

**Comment by billy8407** [comment]
Thanks for the remind!
I will try to upgrade my phone at first.
