### ISSUE TITLE
Unable to operate on appium table screen on ios

### ISSUE THREAD

**Issue by utkuozanocak** [appium/appium#16384]
## The problem

We have a screen with over 100 records, we cannot make events such as click, get on the objects on this screen with appium.
We can manually reduce the recordings on the screen and make an event with appium.

## Environment

* Appium version : 1.20.2
* Real Device
* ios Device Vers. : 15.3
* Mac OS : Big Sure 11.6
* Processor : Intel

## Link to Appium logs

[debug] [W3C (424d5391)] Calling AppiumDriver.findElement() with args: ["id","filterButton","424d5391-ff08-4605-9a4a-d4ef85951110"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 5000 ms for condition
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8100/session/41905F6C-99E7-4B3B-BF8E-EEB3BD474D26/element] with body: {"using":"id","value":"filterButton"}
[WD Proxy] Got response with status 404: {"value":{"error":"no such element","message":"unable to find an element using 'id', value 'filterButton'","traceback":"(\n\t0   WebDriverAgentLib                   0x00000001070bd680 FBNoSuchElementErrorResponseForRequest + 340\n\t1   WebDriverAgentLib                   0x00000001070bd430 +[FBFindElementCommands handleFindElement:] + 368\n\t2   WebDriverAgentLib                   0x000000010707f1d4 -[FBRoute_TargetAction mountRequest:intoResponse:] + 212\n\t3   WebDriverAgentLib                   0x000000010705e0b8 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 500\n\t4   WebDriverAgentLib                   0x00000001070a26e4 -[RoutingHTTPServer handleRoute:withRequest:response:] + 184\n\t5   WebDriverAgentLib                   0x00000001070a321c __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 72\n\t6   libdispatch.dylib                   0x00000001c0d5500c ED0789CD-8D80-39F4-9651-D8707D9C0337 + 12300\n\t7   libdispatch.dylib                   0x000000...
[debug] [W3C] Matched W3C error code 'no such element' to NoSuchElementError
[debug] [BaseDriver] Waited for 594 ms so far
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8100/session/41905F6C-99E7-4B3B-BF8E-EEB3BD474D26/element] with body: {"using":"id","value":"filterButton"}
[WD Proxy] Got response with status 404: {"value":{"error":"no such element","message":"unable to find an element using 'id', value 'filterButton'","traceback":"(\n\t0   WebDriverAgentLib                   0x00000001070bd680 FBNoSuchElementErrorResponseForRequest + 340\n\t1   WebDriverAgentLib                   0x00000001070bd430 +[FBFindElementCommands handleFindElement:] + 368\n\t2   WebDriverAgentLib                   0x000000010707f1d4 -[FBRoute_TargetAction mountRequest:intoResponse:] + 212\n\t3   WebDriverAgentLib                   0x000000010705e0b8 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 500\n\t4   WebDriverAgentLib                   0x00000001070a26e4 -[RoutingHTTPServer handleRoute:withRequest:response:] + 184\n\t5   WebDriverAgentLib                   0x00000001070a321c __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 72\n\t6   libdispatch.dylib                   0x00000001c0d5500c ED0789CD-8D80-39F4-9651-D8707D9C0337 + 12300\n\t7   libdispatch.dylib                   0x000000...
[debug] [W3C] Matched W3C error code 'no such element' to NoSuchElementError
[debug] [BaseDriver] Waited for 2273 ms so far
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8100/session/41905F6C-99E7-4B3B-BF8E-EEB3BD474D26/element] with body: {"using":"id","value":"filterButton"}
[WD Proxy] Got response with status 404: {"value":{"error":"no such element","message":"unable to find an element using 'id', value 'filterButton'","traceback":"(\n\t0   WebDriverAgentLib                   0x00000001070bd680 FBNoSuchElementErrorResponseForRequest + 340\n\t1   WebDriverAgentLib                   0x00000001070bd430 +[FBFindElementCommands handleFindElement:] + 368\n\t2   WebDriverAgentLib                   0x000000010707f1d4 -[FBRoute_TargetAction mountRequest:intoResponse:] + 212\n\t3   WebDriverAgentLib                   0x000000010705e0b8 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 500\n\t4   WebDriverAgentLib                   0x00000001070a26e4 -[RoutingHTTPServer handleRoute:withRequest:response:] + 184\n\t5   WebDriverAgentLib                   0x00000001070a321c __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 72\n\t6   libdispatch.dylib                   0x00000001c0d5500c ED0789CD-8D80-39F4-9651-D8707D9C0337 + 12300\n\t7   libdispatch.dylib                   0x000000...
[debug] [W3C] Matched W3C error code 'no such element' to NoSuchElementError
[debug] [BaseDriver] Waited for 4431 ms so far
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8100/session/41905F6C-99E7-4B3B-BF8E-EEB3BD474D26/element] with body: {"using":"id","value":"filterButton"}
[WD Proxy] Got response with status 404: {"value":{"error":"no such element","message":"unable to find an element using 'id', value 'filterButton'","traceback":"(\n\t0   WebDriverAgentLib                   0x00000001070bd680 FBNoSuchElementErrorResponseForRequest + 340\n\t1   WebDriverAgentLib                   0x00000001070bd430 +[FBFindElementCommands handleFindElement:] + 368\n\t2   WebDriverAgentLib                   0x000000010707f1d4 -[FBRoute_TargetAction mountRequest:intoResponse:] + 212\n\t3   WebDriverAgentLib                   0x000000010705e0b8 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 500\n\t4   WebDriverAgentLib                   0x00000001070a26e4 -[RoutingHTTPServer handleRoute:withRequest:response:] + 184\n\t5   WebDriverAgentLib                   0x00000001070a321c __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 72\n\t6   libdispatch.dylib                   0x00000001c0d5500c ED0789CD-8D80-39F4-9651-D8707D9C0337 + 12300\n\t7   libdispatch.dylib                   0x000000...
[debug] [W3C] Matched W3C error code 'no such element' to NoSuchElementError
[debug] [W3C (424d5391)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[debug] [W3C (424d5391)]     at XCUITestDriver.doNativeFind (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:126:11)
[debug] [W3C (424d5391)]     at runMicrotasks (<anonymous>)
[debug] [W3C (424d5391)]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[debug] [W3C (424d5391)]     at XCUITestDriver.findNativeElementOrElements (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:86:10)
[debug] [W3C (424d5391)]     at XCUITestDriver.findElOrEls (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:22:12)
[debug] [W3C (424d5391)]     at XCUITestDriver.findElOrElsWithProcessing (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:33:12)
[debug] [W3C (424d5391)]     at XCUITestDriver.findElement (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:53:10)
[HTTP] <-- POST /wd/hub/session/424d5391-ff08-4605-9a4a-d4ef85951110/element 404 7012 ms - 1072
[HTTP] 
[HTTP] --> POST /wd/hub/session/424d5391-ff08-4605-9a4a-d4ef85951110/element
[HTTP] {"using":"id","value":"filterButton"}
[debug] [W3C (424d5391)] Calling AppiumDriver.findElement() with args: ["id","filterButton","424d5391-ff08-4605-9a4a-d4ef85951110"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 5000 ms for condition
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8100/session/41905F6C-99E7-4B3B-BF8E-EEB3BD474D26/element] with body: {"using":"id","value":"filterButton"}
[WD Proxy] Got response with status 404: {"value":{"error":"no such element","message":"unable to find an element using 'id', value 'filterButton'","traceback":"(\n\t0   WebDriverAgentLib                   0x00000001070bd680 FBNoSuchElementErrorResponseForRequest + 340\n\t1   WebDriverAgentLib                   0x00000001070bd430 +[FBFindElementCommands handleFindElement:] + 368\n\t2   WebDriverAgentLib                   0x000000010707f1d4 -[FBRoute_TargetAction mountRequest:intoResponse:] + 212\n\t3   WebDriverAgentLib                   0x000000010705e0b8 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 500\n\t4   WebDriverAgentLib                   0x00000001070a26e4 -[RoutingHTTPServer handleRoute:withRequest:response:] + 184\n\t5   WebDriverAgentLib                   0x00000001070a321c __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 72\n\t6   libdispatch.dylib                   0x00000001c0d5500c ED0789CD-8D80-39F4-9651-D8707D9C0337 + 12300\n\t7   libdispatch.dylib                   0x000000...
[debug] [W3C] Matched W3C error code 'no such element' to NoSuchElementError
[debug] [BaseDriver] Waited for 2562 ms so far
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8100/session/41905F6C-99E7-4B3B-BF8E-EEB3BD474D26/element] with body: {"using":"id","value":"filterButton"}
[WD Proxy] Got response with status 404: {"value":{"error":"no such element","message":"unable to find an element using 'id', value 'filterButton'","traceback":"(\n\t0   WebDriverAgentLib                   0x00000001070bd680 FBNoSuchElementErrorResponseForRequest + 340\n\t1   WebDriverAgentLib                   0x00000001070bd430 +[FBFindElementCommands handleFindElement:] + 368\n\t2   WebDriverAgentLib                   0x000000010707f1d4 -[FBRoute_TargetAction mountRequest:intoResponse:] + 212\n\t3   WebDriverAgentLib                   0x000000010705e0b8 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 500\n\t4   WebDriverAgentLib                   0x00000001070a26e4 -[RoutingHTTPServer handleRoute:withRequest:response:] + 184\n\t5   WebDriverAgentLib                   0x00000001070a321c __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 72\n\t6   libdispatch.dylib                   0x00000001c0d5500c ED0789CD-8D80-39F4-9651-D8707D9C0337 + 12300\n\t7   libdispatch.dylib                   0x000000...
[debug] [W3C] Matched W3C error code 'no such element' to NoSuchElementError
[debug] [W3C (424d5391)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[debug] [W3C (424d5391)]     at XCUITestDriver.doNativeFind (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:126:11)
[debug] [W3C (424d5391)]     at runMicrotasks (<anonymous>)
[debug] [W3C (424d5391)]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[debug] [W3C (424d5391)]     at XCUITestDriver.findNativeElementOrElements (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:86:10)
[debug] [W3C (424d5391)]     at XCUITestDriver.findElOrEls (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:22:12)
[debug] [W3C (424d5391)]     at XCUITestDriver.findElOrElsWithProcessing (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:33:12)
[debug] [W3C (424d5391)]     at XCUITestDriver.findElement (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:53:10)
[HTTP] <-- POST /wd/hub/session/424d5391-ff08-4605-9a4a-d4ef85951110/element 404 6146 ms - 1072
[HTTP] 
[HTTP] --> POST /wd/hub/session/424d5391-ff08-4605-9a4a-d4ef85951110/element
[HTTP] {"using":"id","value":"filterButton"}
[debug] [W3C (424d5391)] Calling AppiumDriver.findElement() with args: ["id","filterButton","424d5391-ff08-4605-9a4a-d4ef85951110"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 5000 ms for condition
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8100/session/41905F6C-99E7-4B3B-BF8E-EEB3BD474D26/element] with body: {"using":"id","value":"filterButton"}
[WD Proxy] Got response with status 404: {"value":{"error":"no such element","message":"unable to find an element using 'id', value 'filterButton'","traceback":"(\n\t0   WebDriverAgentLib                   0x00000001070bd680 FBNoSuchElementErrorResponseForRequest + 340\n\t1   WebDriverAgentLib                   0x00000001070bd430 +[FBFindElementCommands handleFindElement:] + 368\n\t2   WebDriverAgentLib                   0x000000010707f1d4 -[FBRoute_TargetAction mountRequest:intoResponse:] + 212\n\t3   WebDriverAgentLib                   0x000000010705e0b8 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 500\n\t4   WebDriverAgentLib                   0x00000001070a26e4 -[RoutingHTTPServer handleRoute:withRequest:response:] + 184\n\t5   WebDriverAgentLib                   0x00000001070a321c __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 72\n\t6   libdispatch.dylib                   0x00000001c0d5500c ED0789CD-8D80-39F4-9651-D8707D9C0337 + 12300\n\t7   libdispatch.dylib                   0x000000...
[debug] [W3C] Matched W3C error code 'no such element' to NoSuchElementError
[debug] [BaseDriver] Waited for 3658 ms so far
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8100/session/41905F6C-99E7-4B3B-BF8E-EEB3BD474D26/element] with body: {"using":"id","value":"filterButton"}
[WD Proxy] Got response with status 404: {"value":{"error":"no such element","message":"unable to find an element using 'id', value 'filterButton'","traceback":"(\n\t0   WebDriverAgentLib                   0x00000001070bd680 FBNoSuchElementErrorResponseForRequest + 340\n\t1   WebDriverAgentLib                   0x00000001070bd430 +[FBFindElementCommands handleFindElement:] + 368\n\t2   WebDriverAgentLib                   0x000000010707f1d4 -[FBRoute_TargetAction mountRequest:intoResponse:] + 212\n\t3   WebDriverAgentLib                   0x000000010705e0b8 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 500\n\t4   WebDriverAgentLib                   0x00000001070a26e4 -[RoutingHTTPServer handleRoute:withRequest:response:] + 184\n\t5   WebDriverAgentLib                   0x00000001070a321c __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 72\n\t6   libdispatch.dylib                   0x00000001c0d5500c ED0789CD-8D80-39F4-9651-D8707D9C0337 + 12300\n\t7   libdispatch.dylib                   0x000000...
[debug] [W3C] Matched W3C error code 'no such element' to NoSuchElementError
[debug] [W3C (424d5391)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[debug] [W3C (424d5391)]     at XCUITestDriver.doNativeFind (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:126:11)
[debug] [W3C (424d5391)]     at runMicrotasks (<anonymous>)
[debug] [W3C (424d5391)]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[debug] [W3C (424d5391)]     at XCUITestDriver.findNativeElementOrElements (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:86:10)
[debug] [W3C (424d5391)]     at XCUITestDriver.findElOrEls (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:22:12)
[debug] [W3C (424d5391)]     at XCUITestDriver.findElOrElsWithProcessing (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:33:12)
[debug] [W3C (424d5391)]     at XCUITestDriver.findElement (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:53:10)
[HTTP] <-- POST /wd/hub/session/424d5391-ff08-4605-9a4a-d4ef85951110/element 404 8204 ms - 1072
[HTTP] 
[HTTP] --> POST /wd/hub/session/424d5391-ff08-4605-9a4a-d4ef85951110/element
[HTTP] {"using":"id","value":"filterButton"}
[debug] [W3C (424d5391)] Calling AppiumDriver.findElement() with args: ["id","filterButton","424d5391-ff08-4605-9a4a-d4ef85951110"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 5000 ms for condition
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8100/session/41905F6C-99E7-4B3B-BF8E-EEB3BD474D26/element] with body: {"using":"id","value":"filterButton"}
[WD Proxy] Got response with status 404: {"value":{"error":"no such element","message":"unable to find an element using 'id', value 'filterButton'","traceback":"(\n\t0   WebDriverAgentLib                   0x00000001070bd680 FBNoSuchElementErrorResponseForRequest + 340\n\t1   WebDriverAgentLib                   0x00000001070bd430 +[FBFindElementCommands handleFindElement:] + 368\n\t2   WebDriverAgentLib                   0x000000010707f1d4 -[FBRoute_TargetAction mountRequest:intoResponse:] + 212\n\t3   WebDriverAgentLib                   0x000000010705e0b8 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 500\n\t4   WebDriverAgentLib                   0x00000001070a26e4 -[RoutingHTTPServer handleRoute:withRequest:response:] + 184\n\t5   WebDriverAgentLib                   0x00000001070a321c __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 72\n\t6   libdispatch.dylib                   0x00000001c0d5500c ED0789CD-8D80-39F4-9651-D8707D9C0337 + 12300\n\t7   libdispatch.dylib                   0x000000...
[debug] [W3C] Matched W3C error code 'no such element' to NoSuchElementError
[debug] [BaseDriver] Waited for 4523 ms so far
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8100/session/41905F6C-99E7-4B3B-BF8E-EEB3BD474D26/element] with body: {"using":"id","value":"filterButton"}
[WD Proxy] Got response with status 404: {"value":{"error":"no such element","message":"unable to find an element using 'id', value 'filterButton'","traceback":"(\n\t0   WebDriverAgentLib                   0x00000001070bd680 FBNoSuchElementErrorResponseForRequest + 340\n\t1   WebDriverAgentLib                   0x00000001070bd430 +[FBFindElementCommands handleFindElement:] + 368\n\t2   WebDriverAgentLib                   0x000000010707f1d4 -[FBRoute_TargetAction mountRequest:intoResponse:] + 212\n\t3   WebDriverAgentLib                   0x000000010705e0b8 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 500\n\t4   WebDriverAgentLib                   0x00000001070a26e4 -[RoutingHTTPServer handleRoute:withRequest:response:] + 184\n\t5   WebDriverAgentLib                   0x00000001070a321c __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 72\n\t6   libdispatch.dylib                   0x00000001c0d5500c ED0789CD-8D80-39F4-9651-D8707D9C0337 + 12300\n\t7   libdispatch.dylib                   0x000000...
[debug] [W3C] Matched W3C error code 'no such element' to NoSuchElementError
[debug] [W3C (424d5391)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[debug] [W3C (424d5391)]     at XCUITestDriver.doNativeFind (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:126:11)
[debug] [W3C (424d5391)]     at runMicrotasks (<anonymous>)
[debug] [W3C (424d5391)]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[debug] [W3C (424d5391)]     at XCUITestDriver.findNativeElementOrElements (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:86:10)
[debug] [W3C (424d5391)]     at XCUITestDriver.findElOrEls (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:22:12)
[debug] [W3C (424d5391)]     at XCUITestDriver.findElOrElsWithProcessing (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:33:12)
[debug] [W3C (424d5391)]     at XCUITestDriver.findElement (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:53:10)
[HTTP] <-- POST /wd/hub/session/424d5391-ff08-4605-9a4a-d4ef85951110/element 404 10042 ms - 1072
[HTTP] 
[HTTP] --> POST /wd/hub/session/424d5391-ff08-4605-9a4a-d4ef85951110/element
[HTTP] {"using":"id","value":"filterButton"}
[debug] [W3C (424d5391)] Calling AppiumDriver.findElement() with args: ["id","filterButton","424d5391-ff08-4605-9a4a-d4ef85951110"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 5000 ms for condition
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8100/session/41905F6C-99E7-4B3B-BF8E-EEB3BD474D26/element] with body: {"using":"id","value":"filterButton"}
[WD Proxy] Got response with status 404: {"value":{"error":"no such element","message":"unable to find an element using 'id', value 'filterButton'","traceback":"(\n\t0   WebDriverAgentLib                   0x00000001070bd680 FBNoSuchElementErrorResponseForRequest + 340\n\t1   WebDriverAgentLib                   0x00000001070bd430 +[FBFindElementCommands handleFindElement:] + 368\n\t2   WebDriverAgentLib                   0x000000010707f1d4 -[FBRoute_TargetAction mountRequest:intoResponse:] + 212\n\t3   WebDriverAgentLib                   0x000000010705e0b8 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 500\n\t4   WebDriverAgentLib                   0x00000001070a26e4 -[RoutingHTTPServer handleRoute:withRequest:response:] + 184\n\t5   WebDriverAgentLib                   0x00000001070a321c __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 72\n\t6   libdispatch.dylib                   0x00000001c0d5500c ED0789CD-8D80-39F4-9651-D8707D9C0337 + 12300\n\t7   libdispatch.dylib                   0x000000...
[debug] [W3C] Matched W3C error code 'no such element' to NoSuchElementError
[debug] [W3C (424d5391)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[debug] [W3C (424d5391)]     at XCUITestDriver.doNativeFind (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:126:11)
[debug] [W3C (424d5391)]     at runMicrotasks (<anonymous>)
[debug] [W3C (424d5391)]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[debug] [W3C (424d5391)]     at XCUITestDriver.findNativeElementOrElements (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:86:10)
[debug] [W3C (424d5391)]     at XCUITestDriver.findElOrEls (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:22:12)
[debug] [W3C (424d5391)]     at XCUITestDriver.findElOrElsWithProcessing (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:33:12)
[debug] [W3C (424d5391)]     at XCUITestDriver.findElement (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:53:10)
[HTTP] <-- POST /wd/hub/session/424d5391-ff08-4605-9a4a-d4ef85951110/element 404 5512 ms - 1072
[HTTP] 
[HTTP] --> POST /wd/hub/session/424d5391-ff08-4605-9a4a-d4ef85951110/element
[HTTP] {"using":"id","value":"filterButton"}
[debug] [W3C (424d5391)] Calling AppiumDriver.findElement() with args: ["id","filterButton","424d5391-ff08-4605-9a4a-d4ef85951110"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 5000 ms for condition
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8100/session/41905F6C-99E7-4B3B-BF8E-EEB3BD474D26/element] with body: {"using":"id","value":"filterButton"}
[WD Proxy] Got response with status 404: {"value":{"error":"no such element","message":"unable to find an element using 'id', value 'filterButton'","traceback":"(\n\t0   WebDriverAgentLib                   0x00000001070bd680 FBNoSuchElementErrorResponseForRequest + 340\n\t1   WebDriverAgentLib                   0x00000001070bd430 +[FBFindElementCommands handleFindElement:] + 368\n\t2   WebDriverAgentLib                   0x000000010707f1d4 -[FBRoute_TargetAction mountRequest:intoResponse:] + 212\n\t3   WebDriverAgentLib                   0x000000010705e0b8 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 500\n\t4   WebDriverAgentLib                   0x00000001070a26e4 -[RoutingHTTPServer handleRoute:withRequest:response:] + 184\n\t5   WebDriverAgentLib                   0x00000001070a321c __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 72\n\t6   libdispatch.dylib                   0x00000001c0d5500c ED0789CD-8D80-39F4-9651-D8707D9C0337 + 12300\n\t7   libdispatch.dylib                   0x000000...
[debug] [W3C] Matched W3C error code 'no such element' to NoSuchElementError
[debug] [W3C (424d5391)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[debug] [W3C (424d5391)]     at XCUITestDriver.doNativeFind (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:126:11)
[debug] [W3C (424d5391)]     at runMicrotasks (<anonymous>)
[debug] [W3C (424d5391)]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[debug] [W3C (424d5391)]     at XCUITestDriver.findNativeElementOrElements (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:86:10)
[debug] [W3C (424d5391)]     at XCUITestDriver.findElOrEls (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:22:12)
[debug] [W3C (424d5391)]     at XCUITestDriver.findElOrElsWithProcessing (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:33:12)
[debug] [W3C (424d5391)]     at XCUITestDriver.findElement (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:53:10)

**Comment by mykola-mokhnach** [comment]
Elements location completely depends on XCTest, which is beyond our control. Please report your issue to Apple.

**Comment by utkuozanocak** [comment]
but when the number of elements is low, appium can find the object.

**Comment by mykola-mokhnach** [comment]
Again, it is not Appium finding elements, but XCTest. Appium acts as a simple proxy there for the most request types: https://github.com/appium/WebDriverAgent/blob/c7f01c839f9f1284e1319ccce096f6ac96153a40/WebDriverAgentLib/Categories/XCUIElement%2BFBFind.m#L160

Only xpath requests are handled differently because they are not native for XCTest. This is the main reason they could be much slower that other locator types.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
