### ISSUE TITLE
XCUITest returns strange accessibility id

### ISSUE THREAD

**Issue by dlanaghen** [appium/appium#16385]
## The problem

I have been running Appium tests against an iPhone.  Recently the phone was upgraded from 15.0.1 to 15.2.  My Appium test attempts to reference an element by accessibility id.  The id is `ConnectMobile.MyDayHeaderViewController.deviceButton` and was referenceable in my Appium test code prior to the iOS 15.2 upgrade.  This ID was determined by using the Appium inspector tool.  Upon upgrade to the phone to 15.2 the ID I see in the inspector now is:  `<ConnectMobile.MyDayHeaderViewController: 0x11c900a00>.deviceButton`. 

Also, not all element IDs are messed up.  There is something interesting about this element.

Summary: accessibility id returned for an element was different between iOS 15.0.1 and 15.2
15.0.1:  `ConnectMobile.MyDayHeaderViewController.deviceButton` (this is what my code is looking for)
15.2: `<ConnectMobile.MyDayHeaderViewController: 0x11c900a00>.deviceButton` (this is what the inspector is showing)

## Environment

* Appium version 1.22 and 2.0 beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MAC OS Monterey 12.1
* Node.js version (unless using Appium.app|exe): v17.3.0
* Npm or Yarn package manager: 8.3.0
* Mobile platform/version under test: iOS 15.0.1 and 15.2
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

I have attached a screenshot of the inspector which is showing the strange accessibility id.

<img width="1766" alt="appiumInspector" src="https://user-images.githubusercontent.com/627949/151450314-1639e64a-f80c-4112-b444-718d31998ad0.png">

**Comment by mykola-mokhnach** [comment]
I'm not quite sure this issue has anything to do with Appium. It just reflects what XCTest gets from accessibility. Only Apple can change that.

**Comment by dlanaghen** [comment]
I also did submit a bug with Apple thinking this might be an XCTest problem.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue. Please let us know what Apple responds to this issue
