### ISSUE TITLE
IOS Pagination Issue

### ISSUE THREAD

**Issue by shashank2086** [appium/appium#16386]
I have a testing application which has a paginated page. It loads 5 cards and as you scroll it loads further. Now when i am trying to automate with appium, it's trying to load all the cards without being scrolled which is taking hell lot of time. Is there any way to load the elements which are visible on screen instead of loading all cards?

**Comment by mykola-mokhnach** [comment]
Please provide a proper issue description according to the given template

**Comment by BijjamSuresh** [comment]
Screens with pagination [that hits api every time when user scrolls down the screen] --> in this scenario when is try to find the elements the appium is trying to find all the elements in all the paginations and taking more time around 3-5 minutes
