### ISSUE TITLE
java.lang.IllegalStateException: UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@2c7a0c0already registered!

### ISSUE THREAD

**Issue by youngfreeFJS** [appium/appium#16380]
## The problem
can not create session because android.accessibilityservice.IAccessibilityServiceClient already registered

## Environment

* Appium version (or git revision) that exhibits the issue: v1.22.2
* Last Appium version that did not exhibit the issue (if applicable): is v1.x latest version 
* Desktop OS/version used to run Appium: OSX 10.15
* Node.js version (unless using Appium.app|exe): v12.18.3
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Android emulator 9
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: CLI

## Details

each test case use a new create appium server, and use udid bind android emulator(not reboot),  we  will delete session and release server every case. 
But after running 8-10 test case， this problem will happens  and since then the test case on this emulator will all failed with this issue.

Whether the service was not deleted in the previous case? 

## Link to Appium logs

1. create session error log here: https://gist.github.com/youngfreeFJS/c5c8f04da7561570b95479d60ac67ccf
2. the previous one of this error case log (use same emualor ): https://gist.github.com/youngfreeFJS/c3700ecedceb54f25f8fb11f883e689c

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Unfortunately this exception is coming from UiAutomator itself. Only Google would be able to fix that. Try maybe to replace the device under test as a possible workaround

**Comment by mykola-mokhnach** [comment]
Also I saw some mentions in the internet that other apps using uiatomator service might be causing this error. the solution would be to make sure they are uninstalled: https://blog.csdn.net/sunzhimin1991/article/details/108600079

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by youngfreeFJS** [comment]
this is useful !!!
In the delete session API, should these apps be deleted? Why haven't they been uninstalled?
