### ISSUE TITLE
Appium Studio unable to parse ios elements

### ISSUE THREAD

**Issue by cmtanko** [appium/appium#16394]
## The problem

Once I build my IPA file and try to view it in appium studio, In android, all the elements with their appropriate name/id is shown, but for ios, it just shows maybe Parent element and nothing more. Say I have 5 text fields in the view, but appium studio wont/cant show these elements. Added an image below to make it clear.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.20.2
* Last Appium version that did not exhibit the issue (if applicable): v1.20.2
* Desktop OS/version used to run Appium: macOS
* Node.js version (unless using Appium.app|exe): 12.22.1
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: ios / 13 and below
* Real device or emulator/simulator: Both simulator/real device
* Appium CLI or Appium.app|exe: Appium.app

## Details

[Screenshot](https://drive.google.com/file/d/1HGItpOFSJ2GjQdV6JetHQKaNihE_UmGU/view?usp=sharing)
Without the id, I'm blocked with the test. If that help, I am using Appcelerator Titanium for building the app.

**Comment by mykola-mokhnach** [comment]
- Appium 1.20 is old and does not support Xcode 13. Please make sure you use the most recent Appium version. Preferably switch to Appium 2
- Everything you see as the page source is returned to XCTest by Accessibility manager and we cannot influence that at all. Only your app can or XCTest itself, which is under Apple's control.

**Comment by qazando** [comment]
up

**Comment by mykola-mokhnach** [comment]
Closed as not an issue. Consider following the "how to build an accessible application" guide for the technology used to build the app under test.
