### ISSUE TITLE
AndroidDriver getSystemBars() returns wrong values for Android 12

### ISSUE THREAD

**Issue by alexander-kachechka** [appium/appium#16390]
## The problem

AndroidDriver returns wrong values from getSystemBars() method for Android 12 but correct values for Android 11 and below. 

## Environment

* Appium version: **1.22.2**
* Emulator: **Pixel 2** (Android 11) and **Pixel 2** (Android 12)
* AutomationName: **UiAutomator2**
* Appium java-client version: **7.5.1**

## Details

Wrong values for _width_ and _height_ of **statusBar** and **navigationBar**. 
Values with Android 12: 
`{statusBar={visible=true, x=0, y=0, width=null, height=1}, navigationBar={visible=true, x=0, y=0, width=null, height=1}}`
Values with Android 11: 
`{statusBar={visible=true, x=0, y=0, width=1080, height=63}, navigationBar={visible=true, x=0, y=0, width=1080, height=126}}`

## Link to Appium logs

[Logs to Android 12](https://gist.github.com/alexander-kachechka/ab823fce25a744315063e8bc9d337ca6)
[Logs to Android 11](https://gist.github.com/alexander-kachechka/508ab7d94342b4f45594d876a65bdb7e)

## Code To Reproduce Issue

```
import io.appium.java_client.android.AndroidDriver;
import org.openqa.selenium.remote.DesiredCapabilities;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.Map;

public class AppiumSystemBarsIssue {

    public static void main(String[] args) throws MalformedURLException {
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("platformName", "Android");
        capabilities.setCapability("deviceName", "Pixel 2");
        capabilities.setCapability("platformVersion", "12.0");
        capabilities.setCapability("app", "https://applitools.jfrog.io/artifactory/Examples/android/1.3/app-debug.apk");
        capabilities.setCapability("automationName", "UiAutomator2");
        capabilities.setCapability("newCommandTimeout", 300);

        AndroidDriver driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);

        try {
            Map<String, Map<String, Object>> systemBars = driver.getSystemBars();
            System.out.println(systemBars);
        } finally {
            driver.quit();
        }
    }
}
```

**Comment by jlipps** [comment]
The code used to detect this is [here](https://github.com/appium/appium-uiautomator2-server/blob/master/app/src/main/java/io/appium/uiautomator2/handler/GetSystemBars.java#L41). It's just calling the appropriate methods from the Android instrumentation library. I'm not sure if there's anything we can do to fix.

**Comment by jlipps** [comment]
Although [this SO post](https://stackoverflow.com/questions/3407256/height-of-status-bar-in-android) does describe some situations where that method is not reliable. Maybe there's another method that an Android expert could recommend? cc @mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
I could try to move the api call into the server and use something like https://gist.github.com/hamakn/8939eb68a920a6d7a498 instead of relying on adb output parsing, which changes from one version to another. Although this will require some assistance to test it on multiple Android versions. Let me know if someone wants to help with that

**Comment by mykola-mokhnach** [comment]
I've pushed a PR, but like I said, it needs to be tested on different device versions starting from Android 5 (API 21)

**Comment by mykola-mokhnach** [comment]
Closed as fixed
