### ISSUE TITLE
The app is not closed and relaunched when testing  the  test suite in 1.22.2 version

### ISSUE THREAD

**Issue by Hamzastreamwide** [appium/appium#16396]
## The problem

Hi , si i upgraded appium to 1.22.2 , to have the fix of crash in alertview for ios , the old behavior of closing automatically the app after each test , and relaunching the session again before the test , is not working any more :( , so i want someone to help me with this why delete session is not called after the test is finished

 The precondtion :
App already open 
appium 1.22.2 on mac 
steps : 
1- run testng suite 
2- check issue 
issue : 
2- the app is not closed and relaunched 
Expected  : 
2- the app should be closed and relaunched 

NB : before upgrading to 1.22 the same scenario was working per expected result 
## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.2
* Last Appium version that did not exhibit the issue (if applicable):1.21
* Desktop OS/version used to run Appium:  big sur 11
* Node.js version (unless using Appium.app|exe):v14.13.1

* Npm or Yarn package manager:6.14.8
* Mobile platform/version under test: ios 14.2
* Real device or emulator/simulator: real device 
* Appium CLI or Appium.app|exe: appium cli

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/Hamzastreamwide/2eb8c175c3f12f24afd5db9f51bf3866

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
> "shouldTerminateApp":false

Your capabilities explicitly enforce the app to not be terminated on session close. 
Basically the fixed logic is that by default the app is only closed if it was started by the test. If the app was already running or it was started after a new session has been triggered then we don't force close it.

**Comment by Hamzastreamwide** [comment]
i found this by default in the log "shouldTerminateApp":false,"forceAppLaunch":false so i tried to set the first one as true a
            capabilities.setCapability("shouldTerminateApp",true);
Now the behavior is fixed
