### ISSUE TITLE
Does appium supports ipv6 network?

### ISSUE THREAD

**Issue by rostik404** [appium/appium#16405]
## The problem

Hello!
How can I launch appium on ipv6-network? I'm running like this:
```
./node_modules/.bin/appium -p 4444
```
And I see appium only for tcp4, how to run it for tcp6?
```
netstat -anvp tcp | grep LISTEN  
tcp4       0      0  *.4444                 *.*                    LISTEN      131072 131072  21279      0 0x0100 0x00000106
tcp46      0      0  *.9100                 *.*                    LISTEN      131072 131072  15854      0 0x0100 0x00000006
tcp4       0      0  *.9100                 *.*                    LISTEN      131072 131072  15854      0 0x0100 0x00000006
tcp46      0      0  *.8100                 *.*                    LISTEN      131072 131072  15854      0 0x0100 0x00000006
...
tcp6       0      0  fe80::aede:48ff:.49154 *.*                    LISTEN      131072 131072     77      0 0x0180 0x00000006
tcp6       0      0  fe80::aede:48ff:.49153 *.*                    LISTEN      131072 131072     77      0 0x0180 0x00000006
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 11.5.1
* Node.js version (unless using Appium.app|exe): 12.18.1
* Npm or Yarn package manager: npm
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

**Comment by mykola-mokhnach** [comment]
Appium is based on [Express.js](https://expressjs.com/en/api.html). I assume this would work if an IPv6 address is provided as `host` argument on server startup

**Comment by rostik404** [comment]
> I assume this would work if an IPv6 address is provided as host argument on server startup

I'm using appium cli so how can I do this?

**Comment by KazuCocoa** [comment]
You can see the available arguments with `-h` command.
For ipv6, `appium -a ::1` can start as `::1`. Then, like `curl -g -6 'http://[::1]:4723/wd/hub/status` command works to the instance.

**Comment by rostik404** [comment]
Thanks, it's really working.

**Comment by rostik404** [comment]
@KazuCocoa, appium really started listening on tcp6, but it cannot even open URL now (works fine on ipv4).
Here is minimal case:
```js
(async function () {
    client = await wdio.remote({
        protocol: 'http',
        hostname: '[::1]',
        // hostname: 'localhost',
        port: 4444,
        path: '/wd/hub',
        capabilities: {
            connectHardwareKeyboard: true,
            platformName: 'iOS',
            platformVersion: '15.0',
            automationName: 'XCUITest',
            customSSLCert: require('fs').readFileSync('/Users/rostik404/Downloads/cert.crt', { encoding: 'utf8' }),
            deviceName: 'ios15-test',
            version: '15.0',
            isW3C: false,
            browserName: 'safari',
            isHeadless: false,
        }
    });

    await client.url('https://yandex.ru');
})()
.catch(async (e) => {
    console.log('ERRRRR>>>>');
    console.error(e.stack);
    await client.deleteSession();
})

```

It hangs on trying to open `http://::1:4444/welcome`: https://gist.github.com/rostik404/e3a3b653b56c93ab906fa3ded01f717a
Maybe I should pass some extra settings in my wdio conf?

**Comment by rostik404** [comment]
Maybe the problem is that appium is trying to open URL `http://::1:4444/welcome`, but host should be in square brackets?

**Comment by KazuCocoa** [comment]
will take a look later.
Potentially `appium:safariInitialUrl` could help to open an arbitrary url as its default open page instead of local /welcome.

**Comment by rostik404** [comment]
Intial url changing helped, thanks. But it seems that default initial URL is not correct for ipv6 case.

**Comment by KazuCocoa** [comment]
xcuitest driver 4.1.0 (available via appium 2) can open ipv6 local host as https://github.com/appium/appium-xcuitest-driver/pull/1384 ✅

**Comment by fatfatson** [comment]
seems a problem of node 17. 
16 is fine.
