### ISSUE TITLE
Not able to start Appium due to a error- SyntaxError: Cannot use import statement outside a module  

### ISSUE THREAD

**Issue by mittalri** [appium/appium#16401]
## The problem
I am trying to start appium by java code. But, it is failing due to error,
SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)

## Environment

* Appium version (or git revision) that exhibits the issue:
Appium Version 1.22.2

* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
 Windows 10
* Node.js version (unless using Appium.app|exe):
v16.13.0
* Npm or Yarn package manager:
npm 8.4.0
* Mobile platform/version under test:
Android 11
* Real device or emulator/simulator:
emulator
* Appium CLI or Appium.app|exe:
CLI
## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Unfortunately we cannot help nothing without a detailed log. The provided information is not enough to make any assumptions.

**Comment by mittalri** [comment]
I am trying to run appium from java code. but getting error.
below is code snapshot.
 AppiumServiceBuilder builder = new AppiumServiceBuilder();
	     
	        builder.usingAnyFreePort();
	        // Tell builder where node is installed. Or set this path in an environment variable named NODE_PATH
	        builder.usingDriverExecutable(new File("C:\\Program Files\\nodejs\\node.exe"));
	        // Tell builder where Appium is installed. Or set this path in an environment variable named APPIUM_PATH
	        builder.withAppiumJS(new File("C:\\Users\\Ritesh Mittal\\AppData\\Roaming\\npm\\node_modules\\appium"));


	        HashMap<String, String> environment = new HashMap<String, String>();
	        environment.put("PATH", "/usr/local/bin:" + System.getenv("PATH"));
	        builder.withEnvironment(environment);
	        builder.withArgument(() -> "--base-path", "/wd/hub");


	        service = AppiumDriverLocalService.buildService(builder);
	        service.start();

with above code now I am getting error below error (Note;- this error is different post change in builder.withAppiumJS)

SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[35m[Appium][39m Welcome to Appium v1.22.2
[35m[Appium][39m Non-default server args:
[35m[Appium][39m   port: 55175
[35m[Appium][39m Appium REST http interface listener started on 0.0.0.0:55175
[35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/status[39m
[35m[HTTP][39m [90m{}[39m
[debug] [35m[HTTP][39m No route found for /wd/status
[35m[HTTP][39m [37m<-- GET /wd/status [39m[33m404[39m [90m17 ms - 211[39m
[35m[HTTP][39m [90m[39m
[35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/status[39m
[35m[HTTP][39m [90m{}[39m
[debug] [35m[HTTP][39m No route found for /wd/status
[35m[HTTP][39m [37m<-- GET /wd/status [39m[33m404[39m [90m24 ms - 211[39m

**Comment by mittalri** [comment]
finally solved it
was doing two mistakes
1) correct line builder.withAppiumJS(new File("C:\\Users\\Ritesh Mittal\\AppData\\Roaming\\npm\\node_modules\\appium"));
earlier it was till appium.js in lib folder. Above is expected.
2)  builder.withArgument(() -> "--base-path", "/wd/hub"); in this line removed "hub". it worked post this.
