### ISSUE TITLE
Can't acquire file From Files App in iOS Device

### ISSUE THREAD

**Issue by Oscarsgc** [appium/appium#16409]
## The problem

Currently I'm trying to acquire a file from iOS native Files application (com.apple.DocumentsApp). This file is inside the `On My iPhone` Folder, but I'm not able to acquire it. Every time I try with different paths, I'm unable to get it. I've tried with:
- `driver.pullFile("com.apple.DocumentsApp/Documents/log.txt")` 
- `driver.pullFile("com.apple.DocumentsApp/documents/log.txt")` 
-  `driver.pullFile("com.apple.DocumentsApp:Documents/log.txt")` 
-  `driver.pullFile("com.apple.DocumentsApp:documents/log.txt")` 
-  `driver.pullFile("com.apple.DocumentsApp:Documents/On My iPhone/log.txt")` 
-  `driver.pullFile("com.apple.DocumentsApp/Documents/On My iPhone/log.txt")` 
-  `driver.pullFile("com.apple.DocumentsApp/On My iPhone/log.txt")` 
-  `driver.pullFile("com.apple.DocumentsApp:On My iPhone/log.txt")` 

And I always get `An unknown server-side error occurred while processing the command. Original error: Unexpected response OBJECT_NOT_FOUND`

I tried using @ before the app bundleId but I always get `An unknown server-side error occurred while processing the command. Original error: Failed to vend into the application container. Error: InstallationLookupFailed` So that doesn't works either

## Environment

* Appium version (or git revision) that exhibits the issue:  v1.22.2
* Desktop OS/version used to run Appium: macOS 12.2 Monterey
* Node.js version (unless using Appium.app|exe): v16.13.1
* Npm or Yarn package manager: npm v8.3.1
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real Device: iPhone 11, iPhone 8, iPhone 8 Plus
* Appium CLI or Appium.app|exe:

## Details

I need to gather that file some how or at least discover a way to get the same file from inside the original application (any way to get the app file structure?). This file is being stored there trough the "Save To Files" option in the "ActivityListView" That allows to share a file via airdrop, or message or store it to Files Application.

## Code To Reproduce Issue [ Good To Have ]

`IOSDriver driver;
// Initialize Driver with capabilities and server url
driver = new IOSDriver<>(ServerUrl, iosDeviceDesiredCapabilities);
try {
       String path = ""; //Try any path mentioned above
       byte[] logAsByte = driver.pullFile(path);
       System.out.println(logAsByte.toString());
} catch (Exception e) {
       // e.printStackTrace();
       System.out.println(e.getMessage());
       System.out.println("ERROR");
}`

**Comment by KazuCocoa** [comment]
What about `push` a file to `@com.apple.DocumentsApp:documents/log.txt` and pull it?
https://appium.io/docs/en/writing-running-appium/ios/ios-xctest-file-movement/

I wonder the bundle id container does not allow to access files that are saved by another app.

**Comment by mykola-mokhnach** [comment]
In order to access app documents folder it must be shared. See https://github.com/appium/appium-xcuitest-driver#mobile-listapps for more details. you could also try [ifuse](https://github.com/libimobiledevice/ifuse) to see which file could be accessed on the phone. It works similarly to how Appium accesses files

**Comment by mykola-mokhnach** [comment]
Also I belive the current path in bundle is spelled incorrectly. It should probably be something like
`driver.pullFile("@com.apple.DocumentsApp/Documents/log.txt")`

**Comment by mykola-mokhnach** [comment]
Argument docstring:

> This variable can be prefixed with
> bundle id, so then the file will be uploaded to the corresponding
> application container instead of the default media folder, for example
>  '@com.myapp.bla:data/RelativePathInContainer/111.png'. The '@' character at the
>  beginning of the argument is mandatory in such case. The colon at the end of bundle identifier
>  is optional and is used to distinguish the container type.
>  Possible values there are 'app', 'data', 'groups', '<A specific App Group container>'.
>  The default value is 'app'.

**Comment by yangyang0722** [comment]
@mykola-mokhnach I met the same problem, did com.apple.DocumentsApp documents folder can be shared? How can I know this? I use the same way like driver.pullFile("@com.apple.DocumentsApp:documents/log.txt"). But seems the com.apple.DocumentsApp documents did not support to upload.

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-xcuitest-driver#mobile-listapps

> Having UIFileSharingEnabled set to true in the app

Did the app have the `UIFileSharingEnabled` true?

**Comment by yangyang0722** [comment]
> https://github.com/appium/appium-xcuitest-driver#mobile-listapps
When pushing file to the app we test, it can works. But for com.apple.DocumentsApp, com.apple.mobileslideshow, it will return the error Failed to vend into the application container. Error: InstallationLookupFailed.
When I am using mobile: listApps, it did not have the ios system app like com.apple.DocumentsApp, com.apple.mobileslideshow. Can you confirm if ios did not allow to push file to the ios system app.
@KazuCocoa @mykola-mokhnach

**Comment by KazuCocoa** [comment]
Did you give `applicationType` as `System` as the link's description?

**Comment by yangyang0722** [comment]
@KazuCocoa Yes, even I give it as System. It did not return the info for com.apple.DocumentsApp, com.apple.mobileslideshow

**Comment by yangyang0722** [comment]
@KazuCocoa Can you try to push file into the com.apple.DocumentsApp or com.apple.mobileslideshow to see if it works for you?

**Comment by KazuCocoa** [comment]
It did not have `UIFileSharingEnabled`, so I don't think it supported the push to the documents app.
(The below is by `System` as `applicationType` directly)
```
'com.apple.DocumentsApp': {
    UIRequiredDeviceCapabilities: [ 'arm64' ],
    DTCompiler: 'com.apple.compilers.llvm.clang.1_0',
    CFBundleInfoDictionaryVersion: '6.0',
    Entitlements: {
      'com.apple.imdpersistence.IMDPersistenceAgent-Syndication': true,
      'com.apple.private.tcc.allow': [Array],
      'com.apple.private.MobileGestalt.AllowedProtectedKeys': [Array],
      'com.apple.private.ubiquity-additional-kvstore-identifiers': [Array],
      'com.apple.security.exception.files.absolute-path.read-only': [Array],
      'com.apple.itunesstored.private': true,
      'com.apple.Pasteboard.copy-on-paste': true,
      'com.apple.private.corespotlight.search.internal': true,
      'application-identifier': 'com.apple.DocumentsApp',
      'com.apple.authkit.client.private': true,
      'com.apple.security.exception.mach-lookup.global-name': [Array],
      'com.apple.private.sociallayer.highlights': true,
      'com.apple.private.CacheDelete': [Array],
      'com.apple.private.hid.client.event-dispatch.internal': true,
      'com.apple.private.persona.write': true,
      'com.apple.managedconfiguration.profiled.sharing-access-check-messages': true,
      'com.apple.developer.icloud-services': [Array],
      'com.apple.security.exception.shared-preference.read-only': [Array],
      'com.apple.excludes-extensions': true,
      'com.apple.private.interstellar.data-access': 'collaborations',
      'com.apple.fileprovider.fetch-url': true,
      'com.apple.fileprovider.extension-host': true,
      'com.apple.spotlight.photos.entitledattributes': true,
      'keychain-access-groups': [Array],
      'com.apple.managedconfiguration.profiled.configurationprofiles': [Array],
      'com.apple.private.MobileContainerManager.lookup': [Object],
      'com.apple.mkb.usersession.info': true,
      'com.apple.security.exception.files.home-relative-path.read-write': [Array],
      'com.apple.security.exception.shared-preference.read-write': [Array],
      'com.apple.springboard.opensensitiveurl': true,
      'com.apple.private.appleaccount.app-hidden-from-icloud-settings': true,
      'com.apple.private.coreservices.canmaplsdatabase': true,
      'com.apple.accounts.appleidauthentication.defaultaccess': true,
      'com.apple.runningboard.assertions.desktopserviceshelper': true,
      'com.apple.private.trust-ubiquity-kvstore-identifier': true,
      'com.apple.private.ind.client': true,
      'com.apple.security.application-groups': [Array],
      'com.apple.private.biome.read-write': [Array],
      'com.apple.siri.koa.donate.internal': true,
      'com.apple.private.librarian.container-proxy': true,
      'com.apple.private.personas.propagate': true,
      'com.apple.private.corespotlight.internal': true,
      'com.apple.private.corespotlight.bundleid': 'com.apple.DocumentsApp',
      'com.apple.security.exception.files.home-relative-path.read-only': [Array],
      'com.apple.shortcuts.contextual-actions-client': true,
      'com.apple.accounts.appleaccount.fullaccess': true,
      'com.apple.fileprovider.acl-read': true,
      'com.apple.fileprovider.acl-write': true,
      'com.apple.private.librarian.can-get-application-info': true,
      'com.apple.private.persona.read': true,
      'com.apple.fileprovider.enumerate': true,
      'com.apple.private.security.system-application': true,
      'platform-application': true
    },
    DTPlatformVersion: '16.0',
    CFBundleName: 'Files',
    DTSDKName: 'iphoneos16.0.internal',
    ApplicationType: 'System',
    GroupContainers: {
      'group.com.apple.DocumentManager': '/private/var/mobile/Containers/Shared/AppGroup/EA715AEE-F428-49DE-B046-FC6FD7EB6185',
      'group.com.apple.FileProvider.LocalStorage': '/private/var/mobile/Containers/Shared/AppGroup/0826A378-286F-4698-880C-9228CB72C2F1'
    },
    NSPrincipalClass: 'Files.DOCApplication',
    IsAppClip: false,
    Container: '/private/var/mobile/Containers/Data/Application/85DBC57C-FB07-49C8-9A83-1A00B511863A',
    CFBundleIcons: { CFBundlePrimaryIcon: [Object] },
    ParallelPlaceholderPath: true,
    LSRequiresIPhoneOS: true,
    CFBundleDisplayName: 'Files',
    CFBundleAlternateNames: [ 'iCloud Drive' ],
    CFBundleDocumentTypes: [ [Object] ],
    DTSDKBuild: '20A350',
    CFBundleShortVersionString: '1.0',
    CFBundleSupportedPlatforms: [ 'iPhoneOS' ],
    UISupportedInterfaceOrientations: [
      'UIInterfaceOrientationPortrait',
      'UIInterfaceOrientationLandscapeLeft',
      'UIInterfaceOrientationLandscapeRight'
    ],
    BuildMachineOSBuild: '20A241133',
    DTPlatformBuild: '20A350',
    EnvironmentVariables: {
      CFFIXED_USER_HOME: '/private/var/mobile/Containers/Data/Application/85DBC57C-FB07-49C8-9A83-1A00B511863A',
      TMPDIR: '/private/var/mobile/Containers/Data/Application/85DBC57C-FB07-49C8-9A83-1A00B511863A/tmp',
      HOME: '/private/var/mobile/Containers/Data/Application/85DBC57C-FB07-49C8-9A83-1A00B511863A'
    },
    MinimumOSVersion: '16.0',
    CFBundlePackageType: 'APPL',
    IsDemotedApp: false,
    CFBundleVersion: '280.1.2',
    CFBundleDevelopmentRegion: 'en',
    DTXcodeBuild: '14A5270i',
    SequenceNumber: 1664,
    IsUpgradeable: false,
    SBMatchingApplicationGenres: [ 'Productivity', 'Utilities', 'Business' ],
    CFBundleNumericVersion: 0,
    UIDeviceFamily: [ 1, 2 ],
    UILaunchStoryboardName: 'LaunchScreen',
    CoreSpotlightContinuation: true,
    LSSupportsOpeningDocumentsInPlace: true,
    CFBundleIdentifier: 'com.apple.DocumentsApp',
    UIApplicationSceneManifest: {
      UIApplicationSupportsMultipleScenes: true,
      UISceneConfigurations: [Object]
    },
    DTXcode: '1400',
    UIFocusSystemEnabled: true,
    CFBundleExecutable: 'Files',
    IsHostBackupEligible: true,
    Path: '/private/var/containers/Bundle/Application/AC6B4A15-EDE0-458D-914A-5084556F83F6/Files.app',
    DTPlatformName: 'iphoneos',
    CFBundleURLTypes: [ [Object], [Object] ]
  },
```

---

The below is an example of keynote.
```
'com.apple.Keynote': {
    CFBundlePackageType: 'APPL',
    UILaunchStoryboardName: 'LaunchScreen',
    ...
    UIFileSharingEnabled: true,
    HasSettingsBundle: true,
  },
```

**Comment by vikramvr20** [comment]
@KazuCocoa  - I am trying to automate file upload in ios mobile web. Since it's IOS, the test runs on the safari browser and the safari driver does not support file upload using sendKeys. I am trying to use the push command in Appium to push files into "Files" App in Ios devices.

But how can we use driver.push file in IOS devices. Currently am using it like below and I am not able to see the document getting uploaded in the Files App.

File classpathRoot = new File(System.getProperty("user.dir"));
File assetDir = new File(classpathRoot, "/resources");
File txt = new File(assetDir.getCanonicalPath(), "output.txt");
driver.pushFile("@com.apple.DocumentsApp:documents", txt);

If the push command does not work for the Files App. What other options do I have? 

@Oscarsgc - Can you please let me know if you have figured this out.

**Comment by KazuCocoa** [comment]
Perhaps you may need an app to have https://developer.apple.com/documentation/bundleresources/information_property_list/uifilesharingenabled?language=objc separately.
As https://github.com/appium/appium-xcuitest-driver/blob/master/docs/ios/ios-xctest-file-movement.md, keynote.app could be an alternative
