### ISSUE TITLE
Rotate function throws exception even though it works and rotation is performed

### ISSUE THREAD

**Issue by adicusar** [appium/appium#16413]
## The problem
Using rotate function works, but throws exception.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.2 , Java client version - 7.6.0
* Desktop OS/version used to run Appium: MacOS Monterey 12.1
* Node.js version (unless using Appium.app|exe): v16.7.0
* Npm or Yarn package manager: Npm
* Mobile platform/version under test: iOS 15.3
* Real device or emulator/simulator: Real device (iPad Mini 6th gen)
* Appium CLI or Appium.app|exe: Appium CLI

## Details

During test automation there was a need to rotate device using rotate function in Appium driver. When I have called the function for transition from portrait to landscape (and vice versa) orientation then function worked as expected, but exception was thrown with **Unable To Rotate Device** cause. 

Portrait orientation lock - **OFF**

## Link to Appium logs

Gist - https://gist.github.com/adicusar/97a2948c602a02d2b82a919ad0dc2f99

## Code To Reproduce Issue [ Good To Have ]

Kotlin Code
`(driver as AppiumDriver<*>).rotate(ScreenOrientation.LANDSCAPE)`

Line with error - https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/WebDriverAgentLib/Commands/FBOrientationCommands.m#L66

**Comment by mykola-mokhnach** [comment]
I don't observe any issues there. Basically we try to change the orientation and then request the app which orientation it has. If the actual orientation does not match the expected one then the error above is thrown. All values there are returned directly from XCTest, which behaviour we cannot influence at all.

**Comment by adicusar** [comment]
@mykola-mokhnach I mean logically we usually try to switch to opposite orientation, so that is strange.
Maybe iOS behaves slow in terms of switching orientation(animation or whatever) and while this orientation switch is still performed orientation check is done and we get initial orientation instead of actual one. Only that could come in mind.
As an experiment can there be added some sort of delay to check whether this is true?

**Comment by mykola-mokhnach** [comment]
Ofc, you may try that locally. Let us know what the result is if a delay is added

**Comment by adicusar** [comment]
Sorry, I've meant that maybe before that condition (https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/WebDriverAgentLib/Commands/FBOrientationCommands.m#L62) can be added delay like 500-1000 ms.
I've tried to solve this issue by myself by adding **rotatable** capability, casting driver to Rotatable, but result was always the same.

**Comment by mykola-mokhnach** [comment]
If you cannot solve this issue locally then we probably won't be able to help. We neither have the same real device to test it nor the same app.
