### ISSUE TITLE
Appium does not respond if first session creation was aborted

### ISSUE THREAD

**Issue by rostik404** [appium/appium#16417]
## The problem

Hello!
I've found a case when appium stops responding to the client. How to reproduce:
1. Create new ios simulator:
```
> xcrun simctl create "ios15-test" com.apple.CoreSimulator.SimDeviceType.iPhone-13 com.apple.CoreSimulator.SimRuntime.iOS-15-0
8B772246-ED4F-4ADD-95BF-7C794ABB1C7B
```
2. Run appium:
```
./node_modules/.bin/appium -p 4444   
```
3. Request a session 2 times (maybe 1 time will be enough, but I'm not sure) and abort these requests after 2-3 seconds:
```
> curl -d '{"desiredCapabilities": {"browserName": "safari", "version": "15.0", "platformName": "iOS", "automationName": "XCUITest", "deviceName": "ios15-test", "safariInitialUrl": "https://github.com"}}' -H "Content-Type: application/json" -X POST http://localhost:4444/wd/hub/session
^C
> curl -d '{"desiredCapabilities": {"browserName": "safari", "version": "15.0", "platformName": "iOS", "automationName": "XCUITest", "deviceName": "ios15-test", "safariInitialUrl": "https://github.com"}}' -H "Content-Type: application/json" -X POST http://localhost:4444/wd/hub/session
^C
```
4. Request a session one more time:
```
> curl -d '{"desiredCapabilities": {"browserName": "safari", "version": "15.0", "platformName": "iOS", "automationName": "XCUITest", "deviceName": "ios15-test", "safariInitialUrl": "https://github.com"}}' -H "Content-Type: application/json" -X POST http://localhost:4444/wd/hub/session
```
5. Request from p.4 is hanged up and next requests are hanging up too. Appium creates a session but it doesn't respond to the client. See logs in attach

**UPD**

Probably, to reproduce this case, requests should be aborted, when appium trying to launch WebDriverAgent:
```
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
```
## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 11.5.1 Big Sur
* Node.js version (unless using Appium.app|exe): 12.18.1
* Npm or Yarn package manager: npm 6.14.5
* Mobile platform/version under test: ios 15
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: cli

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/rostik404/bded248fe7a5327fa49d16ff23d13882

**Comment by mykola-mokhnach** [comment]
This is expected. All opened sessions must be properly closed before starting new ones. Creating new sessions without closing existing ones transitions the driver to an undefined state.

**Comment by rostik404** [comment]
> All opened sessions must be properly closed before starting new ones.

But I'm getting the same behavior when trying to create session via webdriverio:
1. Setting `connectionRetryTimeout: 20000` - appium unable to create first session in this time
2. Using default connectionRetryTimeout - requests are hanging up like in first example
So does wdio closes sessions improperly? Or maybe there is smth wrong with my script? 
```
const wdio = require('webdriverio');

let client;

(async function () {
    client = await wdio.remote({
        protocol: 'http',
        hostname: '[::1]',
        port: 4444,
        path: '/wd/hub',
        // connectionRetryTimeout: 20000,
        capabilities: {
            safariInitialUrl: 'https://github.com',
            connectHardwareKeyboard: true,
            platformName: 'iOS',
            platformVersion: '15.0',
            automationName: 'XCUITest',
            deviceName: 'ios15-test',
            version: '15.0',
            isW3C: false,
            browserName: 'safari',
            isHeadless: false,
        }
    });

    await client.url('https://yandex.ru');
})()
.catch(async (e) => {
    console.log('ERRRRR>>>>');
    console.error(e.stack);
    await client.deleteSession();
})
```

**Comment by rostik404** [comment]
btw, in catch statement `client` is `undefined` when session was not created in `connectionRetryTimeout`. So in this case I cannot call `deleteSession`

**Comment by mykola-mokhnach** [comment]
There is a way to significantly reduce WDA startup for a simulator by prebuilding it (check usePrebuiltWda capability).

**Comment by jlipps** [comment]
Also, building WDA only happens once per XCUITest driver install, as long as you don't fiddle with files manually. But yes, prebuilding is recommended.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
