### ISSUE TITLE
Proposal: Input Keyboard Text without specifying element (iOS XCUITest)

### ISSUE THREAD

**Issue by marcosmko** [appium/appium#16419]
## The problem

Hello all! I'm automatizing our ui tests for an ios app using robot framework but I cannot use keyboard to directly input text without specifying elements. For that, I need to first add an accessibility id to my view (textfield, textview, etc) then use it to input text, but as Flutter already provides a way to input text without specifying element, I would like a way to do it for ios app natively too.

I have found a way using XCUITest, as shown below. First you tap on the text field, and then you look for all textfields and check which one has keyboard focus. The `hasKeyboardFocus` is an internal value exposed via an extension, but I already checked the [WebDriverAgent](https://github.com/appium/WebDriverAgent) and it seems it is already exposed.

I think it could be a more realistic approach, as testers would not need to modify code and insert accessibility ids for every field.

```
    let emailTextField = app.textFields["E-Mail"]
    emailTextField.tap()

    let textFields = app.descendants(matching: .textField)
    for element in textFields.allElementsBoundByIndex {
        print(element.hasKeyboardFocus)
        if element.hasKeyboardFocus {
            element.typeText("typing text")
            break
        }
    }
```

## Environment

* Appium version (or git revision) that exhibits the issue: 2.0.0-beta.24
* Desktop OS/version used to run Appium: macOS Monterey
* Mobile platform/version under test: iOS Simulator

**Comment by mykola-mokhnach** [comment]
The active element could be retrieved by using `activeElement` WebDriver API. Otherwise I'm not quite sure what else could be done there

**Comment by marcosmko** [comment]
According to [appium documentation](https://appium.io/docs/en/commands/element/other/active/), `Get Active Element` is not implemented in any platform.

That's why my idea is to use `app.descendants(matching: .textField)` to detect which element has keyboard focus and input text on it.

**Comment by mykola-mokhnach** [comment]
This documentation is probably outdated: https://github.com/appium/appium-xcuitest-driver/blob/9eec27cfce29c28cedbd220eb6b98d8f153e2d57/lib/commands/general.js#L15

**Comment by marcosmko** [comment]
Thanks! I will check here :)

**Comment by KazuCocoa** [comment]
W3C actions' send_keys also may help. It is now _send keys_ to an active element in MJSONWP one.
(some links to each diver's w3c send_keys apis) Some links for it:

https://github.com/appium/ruby_lib_core/blob/6df37c7928b125295e657f007e6c6c135090ac82/test/unit/android/webdriver/w3c/actions_test.rb#L108-L111
https://selenium-python.readthedocs.io/api.html#selenium.webdriver.common.action_chains.ActionChains.send_keys
https://www.selenium.dev/selenium/docs/api/java/org/openqa/selenium/interactions/Actions.html#sendKeys(java.lang.CharSequence...)
https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/lib/input_exports_Actions.html#sendKeys

**Comment by marcosmko** [comment]
The `Get Active Element` is working here and it is enough for me, thank you very much!

**Comment by mykola-mokhnach** [comment]
I'll keep the issue opened as a reminder about documentation update
