### ISSUE TITLE
[iOS] Label elements dose not shown in DOM in Appium desktop. User can not locate them.

### ISSUE THREAD

**Issue by mitrevsimeon** [appium/appium#16428]
## The problem

In text field input invalid e-mail address, press send button "Изпрати" and under the input field new element is shown "Невалиден e-mail формат".  I'm trying to locate this element in Appium desktop on ios device, but there is no information in DOM, and I can not locate it via Select Element button.
![ios element in xcode 1](https://user-images.githubusercontent.com/99257137/153154355-9f9593db-8d0c-4a38-8c00-6d252fec09d3.png)
![ios element in xcode](https://user-images.githubusercontent.com/99257137/153154359-d69d2605-c0c7-4ddb-b6de-521a82d3ce60.png)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1 and 1.22.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS Catanina 10.15.1 and Monterey 12.1
* Mobile platform/version under test: iOS 15.2 and iOS 13.2.3
* Real device or emulator/simulator: real devie iphone 7 and iphone xs max

## Link to Appium logs

(https://gist.github.com/mitrevsimeon/63619ab6ed350bb3d6c39288d25705f7)
[xml source.txt](https://github.com/appium/appium/files/8030749/xml.source.txt)
![Screenshot 2022-02-09 at 9 29 10](https://user-images.githubusercontent.com/99257137/153153998-fb8285e5-0961-4a7d-ade4-5a4320ee9d02.png)
![Screenshot 2022-02-09 at 9 28 48](https://user-images.githubusercontent.com/99257137/153154002-f1e29573-daf6-4c2f-8e99-27feedf8c25f.png)
[appium log.txt](https://github.com/appium/appium/files/8030752/appium.log.txt)
![ios element in xcode 1](https://user-images.githubusercontent.com/99257137/153154086-9fbb837a-d472-4845-bb3f-1964373e8e3a.png)

**Comment by mykola-mokhnach** [comment]
If the element is not shown then it is not accessible. Please make sure you follow accessibility guidelines for your particular development technology. There is absolutely nothing that could be done from Appium side.
