### ISSUE TITLE
[iOS] When we tap on the gear button ( settings button in the right upper corner ), Appium also taps on the next item in the new popup

### ISSUE THREAD

**Issue by mitrevsimeon** [appium/appium#16430]
## The problem
We run automation test at vivacom app at ios platform. 

1. User input valid email and password
2. Press login button
3. User is logged in
4. Tap on the gear button ( this action is followed with next tap at the element from new pop up "Ограничение на eSIM/SIM карта")

I added 15 seconds waits before and after tap on the gear button

When try to reproduce the issue on real device with
[appium log gear button.txt](https://github.com/appium/appium/files/8032763/appium.log.gear.button.txt)
![gear button](https://user-images.githubusercontent.com/99257137/153203363-086a2c44-48c3-4be7-b7bf-e11d26a2a897.png)
 real tap or with Appium desktop - the problem is not observed.
## Environment

Appium version (or git revision) that exhibits the issue: 1.15.1 and 1.22.0
Last Appium version that did not exhibit the issue (if applicable):
Desktop OS/version used to run Appium: Mac OS Catanina 10.15.1 and Monterey 12.1
Mobile platform/version under test: iOS 

https://user-images.githubusercontent.com/99257137/153203720-fcd1dbd3-f484-45c5-a3d9-2910f4bff381.mp4

15.2 and iOS 13.2.3
Real device or emulator/simulator: real device iphone 7 and iphone xs max

## Link to Appium logs
https://gist.github.com/mitrevsimeon/3f496965328e0012067b9f6703e7cf4c

**Comment by mykola-mokhnach** [comment]
The tap itself is done by XCTest. Nothing we could do there. Perhaps you could workaround that behaviour using W3C actions and providing a custom delay between press and release actions. Just remember it must not be greater then 125 ms

**Comment by mitrevsimeon** [comment]
Thanks for the answer. Its from this capability. When starting app, there is alert, and we add this capability to accept it. Now we will discuss with dev, is a this popup need to be alert. For me this should be a normal pop up.
