### ISSUE TITLE
Check selected ListView item doesn't work on Android but it does on Windows

### ISSUE THREAD

**Issue by Xiphereal** [appium/appium#16439]
## The problem
I'm working on testing a Xamarin Forms app, both on the Windows (UWP) and Android platforms.

When checking if an item in a ListView is selected on Windows via `WindowsElement.Selected`, it returns the expected value: true when the item is selected, false if it doesn't. Nevertheless, when checking the same ListView items on Android, the `AndroidElement.Selected` always returns false, even when the item is selected.

For other controls like Checkbox and RadioButtons, I've already seen that `AndroidElement.Selected` doesn't say when the AndroidElement is selected (which is kinda rare and confusing), and for these controls checking the `AndroidElement.GetAttribute("checked")` has worked. With the ListView items, this isn't the case. If checked the items on the Appium Inspector, and both their checked, focused and selected attributes are always false.

Any idea on what's happening? How could I verify that a ListView item is selected as I do on Windows?

Thanks in advance.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21
* Desktop OS/version used to run Appium: Windows 11 Pro
* Mobile platform/version under test: Android 30
* Real device or emulator/simulator: Samsung Galaxy A12

**Comment by mykola-mokhnach** [comment]
These values completely depend on what the particular element exposes to the accessibility. 

These attributes are read directly from the corresponding UiObject2 instance. See

- https://github.com/appium/appium-uiautomator2-server/blob/b185f317a0fa2a7fa3a59a1f466372083236d2af/app/src/main/java/io/appium/uiautomator2/model/UiObject2Element.java#L74
- https://developer.android.com/reference/androidx/test/uiautomator/UiObject2

for more details.

**Comment by Xiphereal** [comment]
> These values completely depend on what the particular element exposes to the accessibility.
> 
> These attributes are read directly from the corresponding UiObject2 instance. See
> 
>     * https://github.com/appium/appium-uiautomator2-server/blob/b185f317a0fa2a7fa3a59a1f466372083236d2af/app/src/main/java/io/appium/uiautomator2/model/UiObject2Element.java#L74
> 
>     * https://developer.android.com/reference/androidx/test/uiautomator/UiObject2
> 
> 
> for more details.

Oh, I see, thanks for the info :) So how can we check if an item on a ListView is selected on Android?
