### ISSUE TITLE
allow installation of extensions via package managers

### ISSUE THREAD

**Issue by boneskull** [appium/appium#16442]
For a JS project which depends upon `appium`, installation of extensions should be allowable via idiomatic means (e.g., npm, yarn, etc) instead of requiring consumers to learn a new workflow with the `appium` CLI.   Both methods of extension management should be supported; if we don't, it will cause significant negative UX.

**Comment by mykola-mokhnach** [comment]
@boneskull Can this issue be closed as fixed?
