### ISSUE TITLE
Add release GH actions

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#16440]
Will do for main drivers in this issue:

- [x] xcuitest driver
- [x] appium/WDA
- [x] uia2-driver
- [x] espresso-driver
- [x] mac2 driver
- [x] safari driver
- [x] geckodriver
- [x] win driver

**Comment by KazuCocoa** [comment]
Commit will be on the GH release page: e.g. https://github.com/appium/appium-mac2-driver/releases/tag/v1.0.2

**Comment by jlipps** [comment]
such a great idea, thank you!

**Comment by KazuCocoa** [comment]
I've added the release modules except for espresso since it needs a grade build. I'll need more time to complete it.

example to add the auto release change:
https://github.com/appium/appium-windows-driver/commit/62842bca74ba0c47c221b511ede1f37fbb15330b

rule: https://github.com/semantic-release/semantic-release
NPM_TOKEN: is my npm access token for automation purpose for now.

**Comment by KazuCocoa** [comment]
Ok, now, our major drivers' push is by GH actions automatically. They include npm-shrinkwrap.json for now to specify dependencies.

**Comment by KazuCocoa** [comment]
Note what we should do:

1. Add `@semantic-release/git` and `semantic-release` dependencies in the dev dependencies
2. Add [.releaserc](https://github.com/appium/appium-windows-driver/commit/62842bca74ba0c47c221b511ede1f37fbb15330b#diff-644a8fae29c8e8b6ad5405a2e66c718a3b27f2e12581b7c5e00396d32b3e5cde) (The link is an example)
    - Without this config file, the release task does not bump the `package.json` version for the release package
3. Add release GH actions
