### ISSUE TITLE
ffmpeg died unexpectedly

### ISSUE THREAD

**Issue by miguelfraire** [appium/appium#16468]
I’m trying to screen record on a simulator but I get the following ```org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: The screen capture process 'ffmpeg' died unexpectedly. Check server logs for more details.```

Any ideas would be greatly appreciated.

## Enviroment

Appium version: 1.22.2
Desktop OS/version used to run Appium: OSX Monterey 12.2.1
Node.js version: 17.5.0
Npm package manager: 8.4.1
Appium CLI or Appium.app|exe: CLI
FFMPEG version: 5.0
Mobile platform/version under test: iPhone 13 / iOS 15.2
Real device or emulator/simulator: simulator
Xcode version: 13.2.1

## Details

I'm currently on the latest version of ffmpeg but I've tried ffmpeg@4.4 as well as different screen recording options such as
 ```
 IOSStartScreenRecordingOptions()
                            .withFps(24)
                            .withVideoScale("320:-2")
                            .withVideoType("h264") // mpeg4 / h264
                            .withTimeLimit(Duration.ofMinutes(10)));
```

## Link to full CLI error

https://gist.github.com/miguelfraire/b5a733330105fc535ad58c521245a78c

## Link to Appium logs

https://gist.github.com/miguelfraire/216af02727b23f3772ba0ad3767dc870

## Link to FFMPEG Report

https://gist.github.com/miguelfraire/e8b1260f07bb4cd719768072ad5413db

## Code To Reproduce Issue

```

    companion object {
        private var capabilities: IosCapabilities? = null
        private var localService: AppiumDriverLocalService? = null
        private var internalDriver: IOSDriver<IOSElement>? = null
        val driver: IOSDriver<IOSElement>
            get() = internalDriver!!
    }

    fun setUp() {
        defaultCapabilitiesIfNotSet()
        createAndStartLocalService()
        createIosDriver(capabilities)
        startScreenRecording()
    }

```

```

    private fun startScreenRecording() {
        driver.startRecordingScreen(
            IOSStartScreenRecordingOptions()
                .withVideoType("mpeg4")
                .withVideoScale("iw/2:ih/2")
                .withTimeLimit(Duration.ofSeconds(100))
        )
    }

    private fun stopScreenRecording(saveFile: Boolean, name: String) {
        val video = driver.stopRecordingScreen()

        if (saveFile) {
            val path = "./Failures/$name.mp4"
            val decodedVideo = Base64.getDecoder().decode(video)
            val newFile = File(path)
            FileUtils.writeByteArrayToFile(newFile, decodedVideo)
        }
    }

```

**Comment by mykola-mokhnach** [comment]
> [ffmpeg] [http @ 0x7f78c7204fc0] HTTP error 426 Upgrade Required
> [ffmpeg] 
> [ffmpeg] http://127.0.0.1:9100: Server returned 4XX Client Error, but not one of 40{0,1,3,4}

What happens if you start a test, pause it and then open the above url in the browser? is it possible that some other local service is listening on the default port #9100 and prevents WebDriverAgent to use it?
