### ISSUE TITLE
Socket hang up error while taking screenshot in appium (iOS 15.4 beta & xCode 13.3 beta 2)

### ISSUE THREAD

**Issue by udaykittu** [appium/appium#16467]
## The problem

Socket hang up error while taking screenshot in appium (iOS 15.4 beta & xCode 13.3 beta 2)
Test Execution is taking place in Network mode (Wifi connection)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.2
* Last Appium version that did not exhibit the issue (if applicable): 1.22
* Desktop OS/version used to run Appium: NA
* Node.js version (unless using Appium.app|exe): 14.18.1
* Npm or Yarn package manager: Npm
* Mobile platform/version under test: iOS 15.4 beta
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Details
Take Screenshot failing as socket hangup in the latest release of Appium CLI on iOS Beta Versions
Test Execution is taking place in Network mode (Wifi connection)

## Link to Appium logs
https://gist.github.com/udaykittu/43f076fbd08b1c052235b5e3c6c4c290

**Comment by KazuCocoa** [comment]
okay, let me download the Xcode version.
I wonder the iOS version had some issues there.

```
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8200/status] with no body
[debug] [iProxy@00008030:8200] Unexpected data: {"header":{"length":294,"version":1,"type":8,"tag":1},"payload":{"MessageType":"Result","Number":2}}
[WD Proxy] socket hang up
```

Btw, what iOS version did you use?
I haven't tested probably 15.4 beta 3.

**Comment by udaykittu** [comment]
hi @KazuCocoa 

iOS 15.4 (19E5225g) - new beta version released. We are testing our apps in the latest iOS beta version

**Comment by mykola-mokhnach** [comment]
> Test Execution is taking place in Network mode (Wifi connection)

We don't support wirelessly connected devices. Only devices connected via USB are supported.

**Comment by udaykittu** [comment]
As per https://github.com/appium/appium/issues/15277#issuecomment-821867454 we are running the code over network mode. Since USB connection is giving issues related to disconnection. 

We haven't faced this issue until now from when the comment was provided. This issue is seen after upgrading to iOS latest beta version

**Comment by mykola-mokhnach** [comment]
Maybe you were lucky, but we never tested WiFi connection support. There is already a corresponding enhancement request there, although we don't have any experts that could make it possible in the team. Basically, the place to start from would be https://github.com/appium/appium-ios-device module

**Comment by mykola-mokhnach** [comment]
also for this particular error we would need the device log as it is not clear what exactly has failed from appium logs

**Comment by udaykittu** [comment]
Appium logs inclusive of ios device logs

https://gist.github.com/udaykittu/5f908a1cf3f9ba47a994af52356b2d2a

**Comment by KazuCocoa** [comment]
I quickly tried with iOS 15.4 (19E5225g) in iPhone SE2 x Xcode 13.3 beta 2, but they worked well. (usb connected)
Mm, possibly something environment/condition specific thing.

I'll take a look later again.

**Comment by mykola-mokhnach** [comment]
> [debug] [WD Proxy] Proxying [GET /screenshot] to [GET http://127.0.0.1:8200/session/C0B412EA-4D4D-45DB-8CFA-C0935860B377/screenshot] with no body
> [IOSDeviceLog] Feb 17 03:24:18 Uday-Kumar-Rajus-iPhone testmanagerd[804] <Notice>: Got system UI orientation (<AXUIElementRef 0x113d18050> {pid=483} {uid=[ID:1 hash:0x0]}[kAXApplicationOrientationAttribute]) 1
> [IOSDeviceLog] Feb 17 03:24:18 Uday-Kumar-Rajus-iPhone testmanagerd[804] <Notice>: Preparing screenshot for request: ScreenshotRequest(screenID: 217597285326913537, rect: nil, orientation: CGImagePropertyOrientation(rawValue: 1), encoding: Uniform Type Identifier 'public.jpeg', compression quality '0.800000')
> [IOSDeviceLog] Feb 17 03:24:18 Uday-Kumar-Rajus-iPhone kernel[0] <Notice>: testmanagerd[804] Corpse allowed 1 of 5
> [IOSDeviceLog] Feb 17 03:24:18 Uday-Kumar-Rajus-iPhone SpringBoard(FrontBoardServices)[483] <Notice>: [FBSystemAppProxyServiceServer] Removing client anon<testmanagerd>:804.
> [IOSDeviceLog] Feb 17 03:24:18 Uday-Kumar-Rajus-iPhone backboardd(IOKit)[69] <Notice>: Connection removed: IOHIDEventSystemConnection uuid:B04E4F89-2851-4A20-87DE-3A946B4709B4 pid:804 process:testmanagerd type:Rate Controlled entitlements:0x1c caller:testmanagerd: -[XCTDAutomationServicesProvider initWithAccessibilitySystem:timeout:error:] + 224 attributes:(null) state:0x1 events:0 mask:0x0
> [IOSDeviceLog] Feb 17 03:24:18 Uday-Kumar-Rajus-iPhone backboardd(libAccessibility.dylib)[69] <Notice>: AXS AccessibilityEnabled: (app ax: 1), ax settings: 1, cached: 1

From this log it looks like testmanagerd simply crashed. Which is possible, because it's beta. I don't think we could do much there. Try to gather process crash reports and send them to Apple.

**Comment by mykola-mokhnach** [comment]
Something from recent Xcode [release notes](https://evnik.github.io/XcodeRN/Xcode12Beta3.html):

> Screenshot capture may cause a “Lost connection to testmanagerd” test failure when running UI tests on certain iOS devices. (63946264)
> 
> Workaround: Disable automatic screenshots in your scheme or test plan.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
