### ISSUE TITLE
Ruby - Connecting to an existing session?

### ISSUE THREAD

**Issue by seanmajorpayne** [appium/appium#16460]
Is it possible to connect to an existing driver session in Ruby if you have the session ID?

As an example of the functionality I am looking for:

```
Appium::Core.for(caps: capabilities).start_driver(server_url: server_url, session_id: session_id)
```

**Comment by KazuCocoa** [comment]
No for now as same as the parent selenium ruby binding.
https://github.com/appium/ruby_lib_core/issues/336 is the issue for it.
(close this issue as the ruby_lib_core issue is it)
