### ISSUE TITLE
Can't start chrome application session

### ISSUE THREAD

**Issue by szymonjaczkowski** [appium/appium#16464]
## The problem

I'm trying to connect appium server with chrome app but session cannot be started, logs attached.

## Environment

* Appium Server GUI App Version: 1.22.0
* Appium inspector App Version: 2022.1.2
* Electron: 7.3.3
* Node.js: 12.8.1
* macOS Monterey 12.2.1 M1 Pro 
* Android 11 emulated with Android Studio 

## Details
I'm trying to connect appium server with chrom app. For testing issues I'm using android studio emulator with Pixel 4 XL device emulated. 
## Link to Appium logs

[GIST](https://gist.github.com/szymonjaczkowski/ee951290185fe8c98b80f8f375de7a68) 

## Code To Reproduce Issue [ Good To Have ]
I'm using following parameters to start session
```
{
  "platformName": "Android",
  "appium:appActivity": "org.chromium.chrome.browser.document.ChromeLauncherActivity",
  "appium:appPackage": "com.android.chrome",
  "appium:deviceName": "emulator-5554"
}
```

**Comment by mykola-mokhnach** [comment]
What are you turning to achieve? If a simple web testing session is supposed to be started then it is enough to set `browser` capability to `chrome`. The current log reflects that the given app activity cannot be started and this has nothing to do with Appium itself.

**Comment by szymonjaczkowski** [comment]
In the end I'm trying to run automated tests on emulator using robot framework. I need to you [Open Application|http://serhatbolsu.github.io/robotframework-appiumlibrary/AppiumLibrary.html#Open%20Application] keyword to run chrome browser so I pass appActivity and appPackage to keyword however I'm getting the same problem as described above.

**Comment by KazuCocoa** [comment]
What about `com.google.android.apps.chrome.Main` as the appActivity?

My local android 11 emulator device had no issue with the below command, but the above `.Main` one also worked. I wonder the main one on your env.
```
adb -P 5037 -s emulator-5554 shell am start -W -n com.android.chrome/org.chromium.chrome.browser.document.ChromeLauncherActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000
```

**Comment by mykola-mokhnach** [comment]
As you can see it doers not work with the given activity name. If you simply want to run chrome with your test then check https://stackoverflow.com/questions/28150650/open-chrome-with-adb

**Comment by szymonjaczkowski** [comment]
Thank you so much for your time so I got 2 possible solutions:
1. using `appActivity=com.google.android.apps.chrome.Main`
2. using `browserName=chrome`

**Comment by szymonjaczkowski** [comment]
Thank you so much for your time so I got 2 possible solutions:
1. using `appActivity=com.google.android.apps.chrome.Main`
2. using `browserName=chrome`
