### ISSUE TITLE
Can we press a key in Android independent of its value?

### ISSUE THREAD

**Issue by jainilparikh** [appium/appium#16479]
## Question

I need a way to press a key on an Android Keyboard ( irrespective of its language). For example, if the keyboard is in English and I press the "q" key it should type "q" but when the keyboard is in French it should show "a" (Because  Keyboard is "QUERTY" and French is "AZERTY". 
 
I tried to do this with press_keycode function but it types "q" in both cases, is there a way to press on a key irrespective of its value?

I have been through the google android docs here:  https://source.android.com/devices/input/keyboard-devices#notes

They clearly mention that this is possible through Linux key codes or HID, so is there anyway to send such an input through appium?

Extract from the docs:

> The Android key code associated with common alphanumeric and symbolic keys may vary based on the keyboard layout and language. For historical reasons, the physical scan codes and HID usages associated with keys on a keyboard are often defined positionally even though the labels printed on those keys may vary from one language to another.
> 
> On a US English (QWERTY) keyboard, the top-left alphabetic key is labeled Q. On a French (AZERTY) keyboard, the key in the same position is labeled A. Despite the label, on both keyboards the top-left alphabetic key is referred to using the HID usage 0x07 0x0014 which is mapped to the Linux key code KEY_Q.
> 
> When Android is configured with a US English keyboard layout, then the Linux key code KEY_Q will be mapped to the Android key code KEYCODE_Q and will produce the characters 'Q' and 'q'. However, when Android is configured with a French keyboard layout, then the Linux key code KEY_Q will be mapped to the Android key code KEYCODE_A and will produce the characters 'A' and 'a'.
> 
> The Android key code typically reflects the language-specific interpretation of the key, so a different Android key code may be used for different languages.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOs
* Node.js version (unless using Appium.app|exe): .app is used
* Npm or Yarn package manager:
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: .app is used

## Code To Reproduce Issue
```
# Android environment
import unittest
import time
from appium import webdriver
from appium.webdriver.common.appiumby import AppiumBy

desired_caps = dict(
    platformName='Android',
    platformVersion='10',
    automationName='uiautomator2',
    deviceName='appiumRunner'
    # app='<path-to-app>'
)

driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)

driver.press_keycode(66);
```

**Comment by mykola-mokhnach** [comment]
I have never tried anything like that, but you could start with https://github.com/appium/appium-uiautomator2-server/blob/260f3c3ae99349dcb00e4b7bff7e20e8310c3d68/app/src/main/java/io/appium/uiautomator2/handler/PressKeyCode.java#L59

Play with parameters of [KeyEvent](https://developer.android.com/reference/android/view/KeyEvent) constructor to achieve the behaviour described above.
