### ISSUE TITLE
"No signing certificate "iOS Development" found" appeared when I tested iOS Real Device.

### ISSUE THREAD

**Issue by vSatoshiK** [appium/appium#16470]
## The problem
When I try to test my iOS Device, it fails with the error "No signing certificate "iOS Development" found", even if the signing in Xcode is set correctly.
## Environment
* Appium version (or git revision) that exhibits the issue: 1.22.1
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: macOS 12.2.1
* Node.js version (unless using Appium.app|exe): 17.4.0
* Npm or Yarn package manager: npm 8.3.1
* Mobile platform/version under test: iOS 14.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appiun CLI
## Details
I followed the instruction of the Full manual configuration of the following page: https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md.
When I try to run my test script through appium, the error "No signing certificate "iOS Development" found" appeared.
For further investigation, I tried the followings:
- when I built the WDA on XCode GUI, it succeeded but the app was not installed in my device.
- when I tested the WDA on XCode GUI, it succeeded and the app is installed.
- when I tested on CLI with the command in the configuration page, it failed with the following error in xcresult.
> The network connection was lost: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.hoge.WebDriverAgentRunner.xctrunner'
## Link to Appium logs
https://gist.github.com/vSatoshiK/dfd98f7cd7fb697d002783819337a28a
## Code To Reproduce Issue
The issue seems to be related to the XCode Setting, so the error will be reproduced with any code in my environment.
I've written only the desired capability I used for reference.
> {
    "platformName": "iOS",
    "platformVersion": "14.1",
    "deviceName": "iPhone",
    "udid": "",
    "automationName": "XCUITest",
    "xcodeConfigFile": "path/to/directory/configs/config.xcconfig",
    "app": "path/to/appfile.ipa",
    "agentPath": "/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj",
    "updatedWDABundleId":"com.hoge.WebDriverAgentRunner",
}

**Comment by vSatoshiK** [comment]
> Is the profile a paid developer one?
Yes, paid one.
I tried both a paid account and a free account, but behavior does not change.

>have you tried to build the project manually from the terminal? does it produce the same error?
Yes, I got the same error.
In CLI, the test failed.

**Comment by mykola-mokhnach** [comment]
Appium simply runs a Xcodebuild command there, so I don't think there is anything to do on the server side. Try to tune your project settings, so you could build it from CLI. I'd try to ask on Apple forums or the [Appium forum](https://discuss.appium.io)

**Comment by big-hunter** [comment]
log: 
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body

is there any possiblity the [WD] not start success  at all ?
test case can not connect to [WD Proxy]?

**Comment by vSatoshiK** [comment]
@mykola-mokhnach 
Thank you for your help.
I will try to contact Apple's forum.

**Comment by vSatoshiK** [comment]
@big-hunter 
When pytest or xcodebuild command is executed, WDA does not start. 
When I executed an unit test from the GUI of Xcode>Product>Test, then WDA starts, and pytest command can communicate with it.
I don't think of a reason why WDA will not start from CLI.

**Comment by KazuCocoa** [comment]
What about providing `appium:allowProvisioningDeviceRegistration` capability?

**Comment by vSatoshiK** [comment]
@KazuCocoa 
I added appium:allowProvisioningDeviceRegistration to capability, but the same error was detected.

**Comment by KazuCocoa** [comment]
The same means the below error?

```
[debug] [W3C] Testing failed:
[debug] [W3C] 	No profiles for 'com.hoge.WebDriverAgentRunner.xctrunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.hoge.WebDriverAgentRunner.xctrunner'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
[debug] [W3C] 	No signing certificate "iOS Development" found: No "iOS Development" signing certificate matching team ID "AAAABBBB333" with a private key was found.
[debug] [W3C] 	WebDriverAgentRunner:
```

Could you share the full log? The flag adds `allowProvisioningUpdates` as https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/lib/xcodebuild.js#L193 . It means probably the xcodebuild was not able to solve the provisioning profile. Then, `allowProvisioningUpdates` probably did not work in your env.

**Comment by Yaboxi** [comment]
Hi, I'm a colleague of @vSatoshiK.
Today I've double-checked the `xcodebuild` command with the flag you mentioned in the env the problem occurs.
After several tries (not once), WDA was successfully installed, and now our tests can be passed. Thanks a lot!

**Comment by KazuCocoa** [comment]
Thank you

> (not once)

mm, interesting. I guess Apple's xcodebuild has some issues/edge cases to resolve its provision profile automatically... I don't know Xcode internal, but possibly Xcode retries the command X times internally....?

Anyway, thanks for the update.

**Comment by rraj2017** [comment]
> Hi, I'm a colleague of @vSatoshiK. Today I've double-checked the `xcodebuild` command with the flag you mentioned in the env the problem occurs. After several tries (not once), WDA was successfully installed, and now our tests can be passed. Thanks a lot!

Hey , can you please ping the fixes you applied for the same .

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
