### ISSUE TITLE
Memory error after bulid Success. also xcode will not launch the simulator at all

### ISSUE THREAD

**Issue by big-hunter** [appium/appium#16474]
## The problem

After finished the config when I try to bulid WDA to the simulator, there are some memory error happend.
![merroy error](https://user-images.githubusercontent.com/12094603/154847822-352332e3-554d-4663-8fda-b59c8c5c3c71.png)

I am not sure if i need to change this define  like "" or empty Array?
![define](https://user-images.githubusercontent.com/12094603/154847916-aa4c2b94-8d8e-4a4d-b389-dca19c849d32.png)

## Environment
* iPhone8  simulator
* IOS version 15.2
* Xcode 13.2.1
* Build version 13C100

## Details

Like the pic shows

**Comment by mykola-mokhnach** [comment]
Please provide the full appium server log

**Comment by big-hunter** [comment]
there is the log
https://github.com/big-hunter/notes-everything/blob/master/assets/logs/appium-server-logs.txt

just find keep log out :

[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body

no apps show at simulator

**Comment by mykola-mokhnach** [comment]
Please enable the showXcodeLog capability. Also, Appium 1.21 is not compatible with iOS 15+. Consider using the most recent server version.

**Comment by big-hunter** [comment]
I download the new inspector,and open success @mykola-mokhnach , thanks you !

<img width="1198" alt="wda session" src="https://user-images.githubusercontent.com/12094603/154966330-38aeddf8-143c-41f5-bc71-d3363029d595.png">

I think this may closed.
