### ISSUE TITLE
Cannot switch IOS to web context.

### ISSUE THREAD

**Issue by snoopgr2** [appium/appium#16481]
## The problem

Testing on IOS simulators and real devices.  When trying to switch to the webcontext, IOS is unable to find anything but the Native context unless I loop for a while.  (Android works immediately.)

With testing, I discovered that after about 20 seconds, IOS will discover the webcontext and allow me to switch.  However, after doing so I can no longer reach the page source.  Calling to driver.getPageSource() I start getting the error :
_Got response with status 404: {"value":{"error":"no such alert","message":"An attempt was made to operate on a modal dialog when one was not open","traceback":""},"sessionId":"2E9C4D10-C098-4791-9EDA-714D57408737"}
2022-02-22 14:50:28:693 [W3C] Matched W3C error code 'no such alert' to NoSuchAlertError_

I see in the logs that the context is correct: 
 _Responding to client with driver.getCurrentContext() result: "WEBVIEW_94703.19"_

I know this error was reported years ago but this issue was supposedly fixed many version ago in Appium.  Any suggestions on what to do here?

## Environment

* Appium version: 1.22.1
* Last Appium version that did not exhibit the issue (if applicable): n/a (Previous developer stayed in Native context when testing iOS)
* Desktop OS/version used to run Appium: MAC 11.6.2
* Node.js version (unless using Appium.app|exe): 14.17.1
* Npm or Yarn package manager: 6.14.13
* Mobile platform/version under test: iOS 15.2
* Real device or emulator/simulator: iPhone 13 simulator
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/snoopgr2/d22660ac170a94569bcece528ea81860

## Code To Reproduce Issue [ Good To Have ]

//context switcher
    public void changeDriverContextToWeb() throws InterruptedException {
        Thread.sleep(2000);
        if (getPlatform.equalsIgnoreCase("Android")) {
            Set<String> allContext = driver.getContextHandles();
            System.out.println(allContext);
            for (String context : allContext) {
                if (context.contains("WEBVIEW"))
                    driver.context("WEBVIEW_com.luminixinc.xpulsar");
                    //driver.context(context);
            }
        }
        else{
            Integer loopCount = 1;
            while(loopCount < 10)
            {
                Thread.sleep(10000);  //sleep and hope the driver eventually pulls the webview context
                Set<String> allContext = driver.getContextHandles();                
                for (String context : allContext) {
                    if (context.contains("WEBVIEW"))
                    {
                        driver.context(context);
                        loopCount = 11;
                    }
                }
                loopCount++;

            }
        } 
        
    }

//Basic test:
        changeDriverContextToWeb(); //simple call to switch context
        System.out.println(driver.getContext());
        System.out.println("Start get page source *************************");
        Thread.sleep(9000);
        System.out.println(driver.getPageSource());
        System.out.println("End get page source *************************");
        driver.findElement(MobileBy.id("popover-apps"));
        changeDriverContextToNative();

**Comment by mykola-mokhnach** [comment]
According to the given log the original web page does not respond to getPageSource command in a timely fashion. No idea why that happens though 🤷

**Comment by snoopgr2** [comment]
So with more testing I'm finding that the getContextHandlers() method is returning Webviews that are not on the current page but in a previous page.  It also seems to be retaining these views between test sessions unless I restart the device.  Is this expected behavior?

**Comment by snoopgr2** [comment]
For those who might find this thread and need to fix the context switching / missing webview issue, please know that I simply added a loop around the getcontexthandlers() method and placed a Thread.sleep() inside of the loop to allow the system to load in the webcontext.  I find that it only takes about 3 to 5 seconds (2 loops) for the webview to become available in IOS.

**Comment by KazuCocoa** [comment]
`appium:webviewConnectTimeout` in capabilities or https://github.com/appium/appium-xcuitest-driver#mobile-getcontexts also might help.

**Comment by snoopgr2** [comment]
More progress! :)  So I've found that the page source and/or webview context are getting 'stale'.  It seems that if I force the app to refresh the webpage, Appium works as expected, getting the large page source is not an issue and I'm able to test.  Happy Days.  

However, after some amount of time (I have not yet tested to see how long), Appium is no longer able to retrieve the page source.  

Any suggestions on how to refresh the page via driver command?  I tried driver.refresh() but Java tells me "The method refresh() is undefined for the type AppiumDriver<MobileElement>Java(67108964)".

**Comment by jlipps** [comment]
could try executing js like `window.location.reload()`

also in case anyone else is dealing with webview in ios issues, i've noticed that sometimes webviews must be interacted with to show up, like you need to perform a tap or take an action inside them first in order for them to be accessible to the remote debugger.

**Comment by snoopgr2** [comment]
@jlipps Thanks for the response.  I'll give that a try.  

More research on my side shows that Apple created this problem a year or 2 ago.  I didn't bother digging any further as I'm able to get Appium testing.  I now know to look for Appium to try to throw an error message to an Alert window in the webview.  When I see that error repeating over and over, I know to stop the test and refresh the webview.  

Further evidence of this being an Apple issue is Safari Developer also loses connection to the webview dom at random times.  We plan to get our app up and running on Android soon.  I'm assuming I won't see this kind of problem there.  (Fingers crossed.)

**Comment by jlipps** [comment]
yeah, webview testing on android has its own quirks but we get a full featured chromedriver implementation so it's generally more solid

**Comment by snoopgr2** [comment]
@jlipps Your note about interacting with the webpage... Have you tried my trick with looping on the webcontext to ensure it is available?  Or are you able to switch the context but still need to click on something to get testing working?

**Comment by jlipps** [comment]
in my case, no matter how much time I waited the context was never available until i took some action in it.

**Comment by snoopgr2** [comment]
@jlipps Very sorry to hear that.  How much time did you lose figuring it out?  I lost easily a week to getting all of this to work.

**Comment by jlipps** [comment]
wow sorry @snoopgr2. luckily for me it didn't take so long. i'm so used to things just not working for strange reasons and part of my debug process is trying random things, like imagining, hmm, maybe apple is hiding this for some security reason and it needs an interaction to open it up! so i got lucky. in my case the debug cycle was also tighter because i know that it's faster to check whether a webview is available by looking at debuggable pages in desktop safari. so when it didn't show up there i already knew it wouldn't work in appium, i.e., the issue was purely on the apple side of things whatever it was.

**Comment by snoopgr2** [comment]
Checking with Safari first is great advice, @jlipps.  I'm hoping this thread will help others down the road.  It is very frustrating to get stuck with a problem on features that should 'just work'.  

For those who follow us in this painful process:

If switching context for IOS to a webview doesn't work properly:

- Connect to the device with Safari and confirm the webview is available.
- Try 'touching' something in the webview and confirm with Safari that the webview is now available.
- If the webview context is not available, loop for a few iterations to allow the context to become available.
- If you switch context but get repeating 'can't find an alert module' errors described above, refresh the webview and test again.

Ultimately, Appium is at the mercy of Apple and Android for device testing.  Do your best to work around the quirks of these systems.

**Comment by EnamiYa** [comment]
Hey. I am experiencing the same issue. I tried all of the above but nothing worked. I am on an iOS 16.4 simulator and I am using an app to access a WebView. The WebView is not even listed in Safari's Web Inspector for me to debug it. I use the method getContexts() at different intervals of time and all I get is NATIVE_APP even if the WebView i.e. the webpage has loaded.

**Comment by KazuCocoa** [comment]
Possible reason: https://appium.github.io/appium-xcuitest-driver/4.33/device-preparation/#enable-web-testing-availability
Did you add `isInspectable` that is required since iOS 16.4 by Apple?

**Comment by snoopgr2** [comment]
> Hey. I am experiencing the same issue. I tried all of the above but nothing worked. I am on an iOS 16.4 simulator and I am using an app to access a WebView. The WebView is not even listed in Safari's Web Inspector for me to debug it. I use the method getContexts() at different intervals of time and all I get is NATIVE_APP even if the WebView i.e. the webpage has loaded.

EnamiYa... I know that if I am using Safari's Develop menu Inspection tool to inspect the webview on my 16.4 simulator, then Appium can connect to the sim but cannot find the pagesource and I get all sorts of issues.  Make sure you are not inspecting the webview with anything but appium.  If so, refresh the webview and Appium should be able to connect properly.

**Comment by snoopgr2** [comment]
> Hey. I am experiencing the same issue. I tried all of the above but nothing worked. I am on an iOS 16.4 simulator and I am using an app to access a WebView. The WebView is not even listed in Safari's Web Inspector for me to debug it. I use the method getContexts() at different intervals of time and all I get is NATIVE_APP even if the WebView i.e. the webpage has loaded.

EnamiYa... Also, forget Appium.  If Safari is not finding the webview then your problem is outside of Appium.  This may sound like a dumb question but always start with the basics... Are you sure the page you are viewing is a webpage and not native code?  I ask because our app starts with Native for the login process and only switches to a Webview after login is complete.

**Comment by EnamiYa** [comment]
> 

It is probably that since I was able to access the webview context in an iPhone 11 iOS 15.5 simulator. I am not familiar with iOS dev, though I tried following the link you shared to add `isInspectable` and attempted to do so in different places in the app source code but I still can't access the webview in iOS 16.4 and above

**Comment by vnuta9** [comment]
@snoopgr2 @jlipps 
I had come across this post around 6 months ago, and I happily made use of discussion in my code, successfully. I was using the **((IOSDriver) driver).getContextHandles()** looping logic given by snoopgr2 and checking whether **_(SupportsContextSwitching)driver).getContext().contains("WEBVIEW")_ _is true_** which is working fine.

Suddenly, today, the line before retrieving the **ContextHandles()** is throwing the error
`getWindowHandle()=>page-69C76D33-9B55-4A11-AA2D-808829F9855C
org.openqa.selenium.**UnsupportedCommandException**: 
The command 'GET /session/FBE0A449-3336-453C-AFB2-96ECB3A72296/context' was not found.`

I checked **xcode** project **WebDriverAgentRunner** is running OK or not, which is positive.

I don't know why it is throwing this exception today. 

Please help.
