### ISSUE TITLE
remove ios-webkit-debug-proxy-launcher

### ISSUE THREAD

**Issue by boneskull** [appium/appium#16486]
Per @KazuCocoa:

> i think it can be dropped completely. It was for some legacy iOS webview stf probably before remote-debugger, or appium-ios-driver that is already in Aappium-boneyard 

This file is in `packages/appium/bin`.

**Comment by KazuCocoa** [comment]
yes, i'd like to doube check it with @mykola-mokhnach or @jlipps (if one of you remember...)

**Comment by KazuCocoa** [comment]
I'll remove the tool part in docs later

**Comment by mykola-mokhnach** [comment]
@boneskull Can this issue be closed as fixed?
