### ISSUE TITLE
Appium Unable to launch emulator when integrating appium with jenkins server

### ISSUE THREAD

**Issue by sagar-limbani** [appium/appium#16493]
## The problem

Unable to launch android emulator when integrating appium test with jenkins, appium session is starting programatically in mac

## Environment

* Appium version : 1.22.0
* Desktop OS/version used to run Appium: Mac OS Monterey 12.1

## Details

If emulator is not running then Appium unable to auto launch emulator.  but when I launch manually and run a test then everything works fine.

## Link to Appium logs

[ADB] Using 'adb' from '/Users/ec2-user/Library/Android/sdk/platform-tools/adb'
[debug] [ADB] Running '/Users/ec2-user/Library/Android/sdk/platform-tools/adb -P 5037 start-server'
[debug] [ADB] Trying to find 'PIXEL_XL_API_28_3' emulator
[debug] [ADB] Getting connected emulators
[debug] [ADB] Getting connected devices
[debug] [ADB] No connected devices have been detected
[debug] [ADB] 0 emulators connected
[debug] [ADB] Emulator 'PIXEL_XL_API_28_3' not running
[debug] [ADB] Launching Emulator with AVD PIXEL_XL_API_28_3, launchTimeout 300000ms and readyTimeout 300000ms
[ADB] Using 'emulator' from '/Users/ec2-user/Library/Android/sdk/emulator/emulator'
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1645617719718 (12:01:59 GMT+0000 (Greenwich Mean Time))
[debug] [W3C] Encountered internal error running command: Error: Avd 'PIXEL_XL_API_28_3' is not available. No emulators have been detected on your system
[debug] [W3C]     at ADB.checkAvdExist (/usr/local/lib/node_modules/appium/node_modules/appium-adb/lib/tools/adb-emu-commands.js:466:11)
[debug] [W3C]     at ADB.launchAVD (/usr/local/lib/node_modules/appium/node_modules/appium-adb/lib/tools/system-calls.js:804:3)
[debug] [W3C]     at Object.prepareEmulator (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/android-helpers.js:172:3)
[debug] [W3C]     at Object.getDeviceInfoFromCaps (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/android-helpers.js:220:5)
[debug] [W3C]     at AndroidUiautomator2Driver.startUiAutomator2Session (/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/lib/driver.js:338:26)
[debug] [W3C]     at AndroidUiautomator2Driver.createSession (/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/lib/driver.js:229:7)
[debug] [W3C]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:387:35)
[HTTP] <-- POST /wd/hub/session 500 294 ms - 673

**Comment by sagar-limbani** [comment]
here is the full log of Jenkins build 
https://gist.github.com/sagar-limbani/757481e494025136bf5be31e9a7d8117

**Comment by mykola-mokhnach** [comment]
Not sure this issue has anything to do with Appium. Make sure Android SDK and emulators SDK are installed and configured properly for this particular user on the test VM.

The properly configured machine should list the emulator in the `adb devices -l` command output

**Comment by mykola-mokhnach** [comment]
Closed because of no response
