### ISSUE TITLE
iOS 15.0+ unable to retrieve text from List "XCUIElementTypeStaticText"

### ISSUE THREAD

**Issue by ikhaled28** [appium/appium#16497]
## The problem

Tried to get all the XCUIElementTypeStaticText elements by findElements ClassName. All the the XCUIElementTypeStaticText are listed, but when tried get the texts from the list it always returns empty array or empty string. 

## Environment

Appium version (or git revision) that exhibits the issue: Appium v2.0.0-beta.25, Appium 1.22.0, Appium 1.22.0
Last Appium version that did not exhibit the issue (if applicable): 1.20.2
Desktop OS/version used to run Appium: macOS Monterey 12.2.1 (21D62)
Node.js version (unless using Appium.app|exe):
Npm or Yarn package manager:
Mobile platform/version under test: iOS 15.3.1
Real device or emulator/simulator: iPhone 11
Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

https://gist.github.com/ikhaled28/cfadf176dafcc9c379b5858cedf7ad02

## Code To Reproduce Issue [ Good To Have ]

```
List<WebElement> searchedTexts = helper.getListElementsByClassName("XCUIElementTypeStaticText");
List<String> listToTexArray = helper.webElementToStringList(searchedTexts);
```

```
public List<WebElement> getListElementsByClassName(String className) {
		if (!driver.getContext().equals("NATIVE_APP")) {
			this.turnToNativeContext();
		}
		List<WebElement> listChildrens = driver.findElements(By.className(className));
		return listChildrens;
	}
```
```
public List<String> webElementToStringList(List<WebElement> elementList) {
		List<String> stringsArray = new ArrayList<String>();
		for (WebElement element : elementList) {
			stringsArray.add(element.getText());
		}
		return stringsArray;
	}
```

**Comment by mykola-mokhnach** [comment]
Are these texts visible in the page source?

**Comment by ikhaled28** [comment]
@mykola-mokhnach definitely yes. I added the page source and logs also. You can see that it showed four text elements but the all are empty.

https://gist.github.com/ikhaled28/0b9d07a1e8151aa446d16a742dba06dd

searchedTextList - 4
searchedText[0] - 
listToTextArray - 4
listToTextArray - [, , , ]

**Comment by mykola-mokhnach** [comment]
Could that be a race condition issue? Have you tried to use getAttribute("label") as a possible alternative?

**Comment by ikhaled28** [comment]
@mykola-mokhnach race condition not really, it is similar in all pages. Yes I tried with getAttribute("label") also but that returned null.

**Comment by mykola-mokhnach** [comment]
What output do you observe if `format: description` is provided to https://github.com/appium/appium-xcuitest-driver#mobile-source ?

Would you able to fetch these attributes using vanilla XCTest?

**Comment by ikhaled28** [comment]
@mykola-mokhnach I am not sure I can do that. I am no that advanced with stuffs. You have any documentation so that I can read and try? the issues are real I struggled whole week with this issues and posted where ultimately :( .

**Comment by mykola-mokhnach** [comment]
There's nothing too complicated in writing UI tests using Swift: https://swiftwithmajid.com/2021/03/18/ui-testing-in-swift-with-xctest-framework/

In general I assume the original issue lies in the Apple's framework, but it is necessary to confirm that first.

**Comment by ikhaled28** [comment]
Oh ok, I thought you asked me to do it via appium thats why I got confused. I will try to do so.

**Comment by ikhaled28** [comment]
```
for staticText in  app.staticTexts.allElementsBoundByIndex{
                    print(staticText.label)
                }
```
It works. 

```
for staticText in  app.staticTexts.allElementsBoundByIndex{
                    print(staticText.value)
                }   
```         
It doesn't fetch any data.

**Comment by mykola-mokhnach** [comment]
Perhaps it makes sense to report the issue to Apple. I don't think there is anything we could do about it from Appium side.

**Comment by ikhaled28** [comment]
I posted an issue in Apple Developer Forum. One off topic question was my debugging correct from the evidence I gave you?

**Comment by KazuCocoa** [comment]
it looks like we should pin this issue...

**Comment by 18060010316** [comment]
None of this text positioning really works. I used xpath when I was in the company. But I want to modify the original text positioning, which has a great impact. Is there any way to solve it?

**Comment by mykola-mokhnach** [comment]
>  Is there any way to solve it?

Report it to Apple and hope it will be addressed in the later iOS releases

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by Rahulchinki** [comment]
I

> I posted an issue in Apple Developer Forum. One off topic question was my debugging correct from the evidence I gave you?

Hi @ikhaled28 ,
did you get any update from Apple developer forum on this issue.

Regards
Rahul
