### ISSUE TITLE
Unable to interact with element during execution for iOS (It's visible when inspecting appium desktop)

### ISSUE THREAD

**Issue by ThibanKumar** [appium/appium#16511]
## The problem

- When we inspecting elements exists in DOM however during execution we are unable to interact with element.
- We try to print out the element while executing but the element does not exists in the DOM.
- We also try with different appium version for instance with appium version 1.14.0, 1.22.0 and 1.22.2. Together we try with appium desktop.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.14.0, v1.22.0 and v1.22.2
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: MacOS monterey, MacOS catalina and MacOS BigSur
* Node.js version (unless using Appium.app|exe): 13.5.0, 15.9.0 and 16.6.0
* Npm or Yarn package manager: 6.14.8, 7.6.3 and 7.19.1
* Mobile platform/version under test: iOS and version 12, 13, 14 and 15
* Real device or emulator/simulator: Simulator and Browserstack Device
* Appium CLI or Appium.app|exe: N/A

## Link to Appium logs

[GIST](https://gist.github.com/williamchufave/2d69eeeac29396a121f5df2cd25a3cc2)

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing we could do there. The page tree is generated by XCTest based on the accessibility info that the app provides. Consider reporting your issue to Apple

**Comment by ThibanKumar** [comment]
We do add explicit waits and for loop to interact with element and still it does not able to interact.

**Comment by jlipps** [comment]
Another option would be to write an XCUITest script in Swift to see if your element is visible according to Apple's returned hierarchy. If not, then as @mykola-mokhnach said there's not much Appium can do about it.

**Comment by ThibanKumar** [comment]
Thank you @jlipps for your suggestion and we definitely will try it out.

**Comment by PabloSlajOT** [comment]
Hi @ThibanKumar @jlipps im facing the same issue, do you found a workaround for this?

Thanks!

**Comment by PabloSlajOT** [comment]
I generated this post https://discuss.appium.io/t/ios-unable-to-find-an-element-during-execution/35845

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
