### ISSUE TITLE
Unexplainable timeouts when running Appium Node.js tests on iOS real cloud devices

### ISSUE THREAD

**Issue by DmitriiKrupinECM** [appium/appium#16528]
## The problem

Constant timeouts without any specific error description when running on iOS devices in Amazon Device Farm. The app gets installed to the device, then Appium server gets started on 0.0.0.0:4723, however POST requests to http://127.0.0.1:4723/wd/hub/session fail every time with the following error message:
**DEBUG webdriver: request failed due to response error: unknown error
WARN webdriver: Request failed with status 500 due to An unknown server-side error occurred while processing the command. Original error: Failed to receive any data within the timeout: 5000**

## Environment

* Appium version (or git revision) that exhibits the issue: 1.19.0 and higher
* Last Appium version that did not exhibit the issue (if applicable): lower versions also exhibit the issue
* Desktop OS/version used to run Appium: Amazon virtual machine 
* Node.js version (unless using Appium.app|exe): 17.5.0
* Npm or Yarn package manager: npm v8.4.1
* Mobile platform/version under test: iOS, all versions (newer as well as older)
* Real device or emulator/simulator: real device on Amazon Device Farm
* Appium CLI or Appium.app|exe: CLI

## Details
The same tests run successfully for Android as well as locally for iOS. The issue is specifically with the WebDriverAgent on real iOS devices.

Capabilities used by AWS:
`--default-capabilities "{\"usePrebuiltWDA\": true, \"derivedDataPath\":\"$DEVICEFARM_WDA_DERIVED_DATA_PATH\", \"deviceName\": \"$DEVICEFARM_DEVICE_NAME\", \"platformName\":\"$DEVICEFARM_DEVICE_PLATFORM_NAME\", \"app\":\"$DEVICEFARM_APP_PATH\", \"automationName\":\"XCUITest\", \"udid\":\"$DEVICEFARM_DEVICE_UDID_FOR_APPIUM\", \"platformVersion\":\"$DEVICEFARM_DEVICE_OS_VERSION\"}"`

## Link to the full test specification log

https://gist.github.com/DmitriiKrupinECM/cc43e32637f72a4296f42f7a5a9edd28

**Comment by jlipps** [comment]
The logs you provided are the client side logs, not the Appium server logs, so we have no way to say what could be going on on the Appium side. This looks like an issue with Amazon Device Farm, not Appium. You'll need to contact their support and get help that way.
