### ISSUE TITLE
Could not sign with default certificate

### ISSUE THREAD

**Issue by xiaoyuji0328** [appium/appium#16523]
## The problem

Could not sign with default certificate

## Environment

* Appium version (or git revision) that exhibits the issue: v1.22.2
* Desktop OS/version used to run Appium: Mac os 12.2.1
* Node.js version (unless using Appium.app|exe): v16.13.0
* Npm or Yarn package manager:
* Mobile platform/version under test: android
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: brazil-build FireTVAppSanityTest -DTK:appium-ip-address=http://8c8590633c23.ant.amazon.com:4725/wd/hub -DTK:udid=G070L81883550WGK

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
https://gist.github.com/xiaoyuji0328/0cba13190a0b7df3f8a192c772b5ffb7

~/.zshenv content as below
```
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home/
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

export ANDROID_HOME=/Users/amjiang/Library/Android/sdk

**Comment by mykola-mokhnach** [comment]
Please upgrade you server to the most recent version. 1.9.1 one is heavily out of date

**Comment by xiaoyuji0328** [comment]
i have updated the gist, updated the version and did some more googling, now it gives me the error 

```
Error: Neither ANDROID_HOME nor ANDROID_SDK_ROOT environment variable was exported.
```

but i did export ANDROID_HOME and i've verified that /Users/amjiang/Library/Android/sdk is a valid path

**Comment by mykola-mokhnach** [comment]
Make sure these environment variables are properly propagated to the Appium process. Check https://github.com/appium/java-client/blob/master/docs/environment.md for more details.

**Comment by xiaoyuji0328** [comment]
Thanks.

i did 

```
8c8590633c23:IMDbLivingRoomFireTVAppUITest amjiang$ env
JAVA_TOOLS_OPTIONS=-Dlog4j2.formatMsgNoLookups=true
TERM=xterm-256color
SHELL=/bin/bash
TMPDIR=/var/folders/ws/pcd2mtw92mjcqz7lyrmw7gpnl6sjm_/T/
TERM_SESSION_ID=452ee638-2d7a-4af3-9774-bf9ec0b9a215
USER=amjiang
COMMAND_MODE=unix2003
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.cIjGCdBaYH/Listeners
__CF_USER_TEXT_ENCODING=0x666CC68A:0x0:0x52
PATH=/Users/amjiang/Library/Android/sdk/platform-tools:/Users/amjiang/bin:/Users/amjiang/.toolbox/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/amjiang/Library/Android/sdk/platform-tools/:/Users/amjiang/IMDbLivingRoomFireTVApp2/env/android-sdk/platform-tools/
TERMINAL_EMULATOR=JetBrains-JediTerm
LaunchInstanceID=58D3C55E-8FEC-462F-818C-82303B5EF6F3
__CFBundleIdentifier=com.jetbrains.intellij
PWD=/Users/amjiang/IMDbLivingRoomFireTVAppUITest
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-12.0.2.jdk/Contents/Home
XPC_FLAGS=0x0
JAVA_TOOL_OPTIONS=-Dlog4j2.formatMsgNoLookups=true
XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/amjiang
LOGNAME=amjiang
LC_CTYPE=en_CA.UTF-8
SECURITYSESSIONID=186a3
OLDPWD=/Users/amjiang
_=/usr/bin/env
```
and you were right `ANDROID_HOME` was not there

then i did

```
8c8590633c23:IMDbLivingRoomFireTVAppUITest amjiang$ echo $SHELL
/bin/bash
```

then i added what was in `~/.zshenv` to `~/.bashrc`

now when i do 

```
amjiang@8c8590633c23 ~ % env
TMPDIR=/var/folders/ws/pcd2mtw92mjcqz7lyrmw7gpnl6sjm_/T/
__CFBundleIdentifier=com.apple.Terminal
XPC_FLAGS=0x0
TERM=xterm-256color
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.cIjGCdBaYH/Listeners
XPC_SERVICE_NAME=0
TERM_PROGRAM=Apple_Terminal
TERM_PROGRAM_VERSION=443
TERM_SESSION_ID=CBCCA572-063D-47B7-B28D-6B87484A5585
SHELL=/bin/bash
HOME=/Users/amjiang
LOGNAME=amjiang
USER=amjiang
PATH=/Users/amjiang/.toolbox/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
SHLVL=1
PWD=/Users/amjiang
OLDPWD=/Users/amjiang
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home/
NVM_DIR=/Users/amjiang/.nvm
ANDROID_HOME=/Users/amjiang/Library/Android/sdk
JAVA_TOOLS_OPTIONS=-Dlog4j2.formatMsgNoLookups=true
LANG=en_CA.UTF-8
_=/usr/bin/env
```

ANDROID_HOME shows up, however, I still get the error `Error: Neither ANDROID_HOME nor ANDROID_SDK_ROOT environment variable was exported. `

**Comment by mykola-mokhnach** [comment]
if the process is not executed directly from shell then it might not inherit this env above. Read carefully through the document and make sure that the **process env** is valid

**Comment by xiaoyuji0328** [comment]
ran the command directly from shell(as opposed to the IDE) and it worked! thank you so much!
