### ISSUE TITLE
WADNotFOUNDError: WinAppDriver.exe has not been found

### ISSUE THREAD

**Issue by ThatNerdUKnow** [appium/appium#16529]
## The problem

I'm trying to get the appium inspector(2022.2.1) to connect to my appium  server but i am seeing the folowing error:
`
[debug] [W3C] Encountered internal error running command: WADNotFoundError: WinAppDriver.exe has not been found in any of these locations: C:\Program Files (x86)\Windows Application Driver\WinAppDriver.exe,C:\Program Files\Windows Application Driver\WinAppDriver.exe,C:\Program Files\Windows Application Driver\WinAppDriver.exe. Is it installed?
`
The appium server has never been in a working state from what I can tell as this is a fresh setup and I'm just trying to at the very least get the inspector working

## Environment

* Appium version (or git revision) that exhibits the issue: `2.0.0-beta.25`
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: `Windows`
* Node.js version (unless using Appium.app|exe): `16.14.0`
* Npm or Yarn package manager: Npm version `8.3.1`
* Mobile platform/version under test: `testing windows platform`
* Real device or emulator/simulator: `real device`
* Appium CLI or Appium.app|exe: `CLI`

## Details

The JSON Representation of my Desired Capabilities set in the Appium Inspector
```json
{
  "platformName": "windows",
  "appium:automationName": "windows"
}
```
## Link to Appium logs
https://gist.github.com/ThatNerdUKnow/1117a1c71f959405712802f394196526

## Code To Reproduce Issue [ Good To Have ]

No code here, just using appium inspector

**Comment by mykola-mokhnach** [comment]
The error message is pretty clear there. Is WAD server installed on the destination host? Did you follow the [usage](https://github.com/appium/appium-windows-driver#usage) tutorial?

**Comment by ThatNerdUKnow** [comment]
I did follow the usage tutorial. I was under the understanding that WinAppDriver is automatically downloaded by Appium on install. I can post my results after manually installing it

**Comment by mykola-mokhnach** [comment]
How did you add the driver to appium2? In order to automatically install the server driver's install script must run something like `npm run install`.

**Comment by ThatNerdUKnow** [comment]
I ran `appium driver install windows` I believe

**Comment by ThatNerdUKnow** [comment]
https://gist.github.com/ThatNerdUKnow/1117a1c71f959405712802f394196526#file-postmanualinstall-of-winappdriver

**Comment by ThatNerdUKnow** [comment]
I think we're seeing a new error now so that's progress

**Comment by mykola-mokhnach** [comment]
The most recent log looks better, however it looks like there is an issue with the server itself:

> [WD Proxy] Got response with status 500: {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[debug] [W3C] Matched W3C error code 'unknown error' to UnknownError

Try the recent stable release of it

**Comment by ThatNerdUKnow** [comment]
how do i remove appium@next? i tried `npm uninstall -g appium@next` but `appium -v` still returns `2.0.0-beta.25`

**Comment by mykola-mokhnach** [comment]
> I ran appium driver install windows I believe

@jlipps @boneskull Could it be there is a bug in Appium2 install algorithm, so it does not run install automatically?

**Comment by mykola-mokhnach** [comment]
> how do i remove appium@next

You don't need to remove the whole Appium. I was talking about the Windows App Driver you get from Microsoft.

**Comment by ThatNerdUKnow** [comment]
The one I just installed?

**Comment by boneskull** [comment]
You mean the thing that installs drivers found in `extensions.yaml`?

**Comment by mykola-mokhnach** [comment]
> You mean the thing that installs drivers found in `extensions.yaml`?

I don't know for sure what part of the code is responsible for that. Just wanted to confirm this install script gets picked up upon adding the driver to Appium2

**Comment by mykola-mokhnach** [comment]
> The one I just installed?

the one you get from https://github.com/microsoft/WinAppDriver/releases

**Comment by ThatNerdUKnow** [comment]
and yet another different error. It looks like something's wrong with my requested capabilities now
https://gist.github.com/ThatNerdUKnow/1117a1c71f959405712802f394196526#file-winappdriver1-2-1

**Comment by ThatNerdUKnow** [comment]
I just had to set the app capability to the app I wanted to use. I'm still seeing issues but that's mostly related to the specific app i'm using taking too long to come up and appium timing out

**Comment by jlipps** [comment]
> Just wanted to confirm this install script gets picked up upon adding appium-windows-driver to Appium2

As long as NPM didn't change its install behaviour, yeah it's all still there... https://github.com/appium/appium-windows-driver/blob/master/package.json#L68
