### ISSUE TITLE
Could not parse fixed W3C capabilities: 'deviceName' must be of type string. Falling back to JSONWP protocol

### ISSUE THREAD

**Issue by willianqa** [appium/appium#16535]
I'm trying to configure a parallel.js file to run mobile automation with appium and codeceptjs in parallel. But when I try to run the command
`node bin/parallel.js`

it is showing this error:

******************************
Appium v1.22.2 creating new AndroidUiautomator2Driver (v1.70.1) session
[debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {
[debug] [BaseDriver]   "deviceName": {
[debug] [BaseDriver]     "platform": "Android",
[debug] [BaseDriver]     "app": "./app/app-homolog-debug.apk",
[debug] [BaseDriver]     "desiredCapabilities": {
[debug] [BaseDriver]       "deviceName": "Pixel_3_API_25",
[debug] [BaseDriver]       "platformVersion": "8.0",
[debug] [BaseDriver]       "automationName": "UiAutomator2",
[debug] [BaseDriver]       "noReset": false,
[debug] [BaseDriver]       "fullReset": true,
[debug] [BaseDriver]       "udid": "emulator-5554",
[debug] [BaseDriver]       "systemPort": 8200
[debug] [BaseDriver]     }
[debug] [BaseDriver]   },
[debug] [BaseDriver]   "platformVersion": "8.0",
[debug] [BaseDriver]   "noReset": false,
[debug] [BaseDriver]   "fullReset": true,
[debug] [BaseDriver]   "udid": "emulator-5554",
[debug] [BaseDriver]   "app": "/Users/xxx/app/app-homolog-debug.apk",
[debug] [BaseDriver]   "platformName": "Android"
[debug] [BaseDriver] }
[BaseDriver] SessionNotCreatedError: A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s): 'deviceName' must be of type string
******************************

My Code:

const { 
  Workers, 
  event 
} = require('codeceptjs');

const workerConfig = {
    testConfig: 'codecept.conf.js',
  };
  
  const workers = new Workers(null, workerConfig);

  const testGroups = workers.createGroupsOfSuites(2);
  
   const devices = [{
       platform: "Android",
       app: "./app/app-homolog-debug.apk",
       desiredCapabilities: {
            deviceName: "Pixel_3_API_25",
            platformVersion: "8.0",
            automationName: 'UiAutomator2', 
            noReset: false, 
            fullReset: true,
            udid: "emulator-5554",
            systemPort: 8200
          },
        },
      {
        platform: 'iOS',
        app: './app/Easynvest.app',
          desiredCapabilities: {
            deviceName: 'iPhone 11',
              platformVersion: '14.5',
              automationName: 'XCUITest',
              noReset: false,
              wdalocalport:8100
          }
      },
  ];
   runTags=['@incorrectLogin']

  const configs = devices.map(device => {
    let data =  {
      helpers: {
         Appium: {device}
      }
    }
    return data
  });
  
  for (const config of configs) {
    for (group of testGroups) {
      const worker = workers.spawn();
      worker.addTests(group);
      worker.addConfig(config);
    }
  }
  
  workers.on(event.test.failed, (failedTest) => {
    console.log('Failed : ', failedTest.title);
  });
  
  workers.on(event.test.passed, (successTest) => {
    console.log('Passed : ', successTest.title);
  });
  
  workers.on(event.all.result, () => {
    workers.printResults();
  });
  
  runWorkers();
  
  async function runWorkers() {
    try {
      await workers.bootstrapAll();
      await workers.run();
    } finally {
      await workers.teardownAll();
    }
  }

**Comment by mykola-mokhnach** [comment]
> [debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {
> [debug] [BaseDriver] "deviceName": {
> [debug] [BaseDriver] "platform": "Android",
> [debug] [BaseDriver] "app": "./app/app-homolog-debug.apk",
> [debug] [BaseDriver] "desiredCapabilities": {
> [debug] [BaseDriver] "deviceName": "Pixel_3_API_25",
> [debug] [BaseDriver] "platformVersion": "8.0",
> [debug] [BaseDriver] "automationName": "UiAutomator2",
> [debug] [BaseDriver] "noReset": false,
> [debug] [BaseDriver] "fullReset": true,
> [debug] [BaseDriver] "udid": "emulator-5554",
> [debug] [BaseDriver] "systemPort": 8200
> [debug] [BaseDriver] }

There is most likely an issue with your client script. `deviceName` is an object there and the server complains is absolutely expected.

**Comment by willianqa** [comment]
here I inform the deviceName:

"deviceName": "Pixel_3_API_25",

**Comment by KazuCocoa** [comment]
Perhaps the full appium log helps to see what capabilities were send from the client

**Comment by willianqa** [comment]
the complete log follows:

[Appium] 
[Appium]   The next major version of Appium (2.x) will **require** the 
[Appium]   'automationName' capability to be set for all sessions on all 
[Appium]   platforms
[Appium] 
[Appium]   In previous versions (Appium <= 1.13.x), the default was 
[Appium]   'automationName=UiAutomator1'
[Appium] 
[Appium]   If you wish to use that automation instead of UiAutomator2, please 
[Appium]   add 'automationName=UiAutomator1' to your desired capabilities
[Appium] 
[Appium]   For more information about drivers, please visit 
[Appium]   http://appium.io/docs/en/about-appium/intro/ and explore the 
[Appium]   'Drivers' menu
[Appium] 
[Appium] ======================================================================
[Appium] 
[Appium] Appium v1.22.2 creating new AndroidUiautomator2Driver (v1.70.1) session
[debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {
[debug] [BaseDriver]   "deviceName": {
[debug] [BaseDriver]     "platform": "Android",
[debug] [BaseDriver]     "app": "./app/app-homolog-debug.apk",
[debug] [BaseDriver]     "desiredCapabilities": {
[debug] [BaseDriver]       "deviceName": "Pixel_3_API_25",
[debug] [BaseDriver]       "platformVersion": "8.0",
[debug] [BaseDriver]       "automationName": "UiAutomator2",
[debug] [BaseDriver]       "noReset": false,
[debug] [BaseDriver]       "fullReset": true,
[debug] [BaseDriver]       "udid": "emulator-5554",
[debug] [BaseDriver]       "systemPort": 8200
[debug] [BaseDriver]     }
[debug] [BaseDriver]   },
[debug] [BaseDriver]   "platformVersion": "8.0",
[debug] [BaseDriver]   "noReset": false,
[debug] [BaseDriver]   "fullReset": true,
[debug] [BaseDriver]   "udid": "emulator-5554",
[debug] [BaseDriver]   "app": "/Users/xxxx/Documents/automacao/mobile/app/app-homolog-debug.apk",
[debug] [BaseDriver]   "platformName": "Android"
[debug] [BaseDriver] }
[BaseDriver] SessionNotCreatedError: A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s): 'deviceName' must be of type string
[BaseDriver]     at AndroidUiautomator2Driver.validateDesiredCaps (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:231:25)
[BaseDriver]     at AndroidUiautomator2Driver.validateDesiredCaps (/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/lib/driver.js:171:18)
[BaseDriver]     at AndroidUiautomator2Driver.createSession (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/session.js:46:8)
[BaseDriver]     at AndroidUiautomator2Driver.createSession (/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/lib/driver.js:177:43)
[BaseDriver]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:387:43)
[BaseDriver]     at runMicrotasks (<anonymous>)
[BaseDriver]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1646775115938 (18:31:55 GMT-0300 (Brasilia Standard Time))
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1646775115938 (18:31:55 GMT-0300 (Brasilia Standard Time))
[debug] [MJSONWP] Encountered internal error running command: SessionNotCreatedError: A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s): 'deviceName' must be of type string
[debug] [MJSONWP]     at AndroidUiautomator2Driver.validateDesiredCaps (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:231:25)
[debug] [MJSONWP]     at AndroidUiautomator2Driver.validateDesiredCaps (/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/lib/driver.js:171:18)
[debug] [MJSONWP]     at AndroidUiautomator2Driver.createSession (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/session.js:46:8)
[debug] [MJSONWP]     at AndroidUiautomator2Driver.createSession (/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/lib/driver.js:177:43)
[debug] [MJSONWP]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:387:43)
[debug] [MJSONWP]     at runMicrotasks (<anonymous>)
[debug] [MJSONWP]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[debug] [MJSONWP] Encountered internal error running command: SessionNotCreatedError: A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s): 'deviceName' must be of type string
[debug] [MJSONWP]     at AndroidUiautomator2Driver.validateDesiredCaps (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:231:25)
[debug] [MJSONWP]     at AndroidUiautomator2Driver.validateDesiredCaps (/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/lib/driver.js:171:18)
[debug] [MJSONWP]     at AndroidUiautomator2Driver.createSession (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/session.js:46:8)
[debug] [MJSONWP]     at AndroidUiautomator2Driver.createSession (/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/lib/driver.js:177:43)
[debug] [MJSONWP]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:387:43)
[debug] [MJSONWP]     at runMicrotasks (<anonymous>)
[debug] [MJSONWP]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[HTTP] <-- POST /wd/hub/session 500 9 ms - 207
[HTTP] 
[HTTP] <-- POST /wd/hub/session 500 5 ms - 207
[HTTP] 
[HTTP] --> POST /wd/hub/session
[HTTP] {"capabilities":{"alwaysMatch":{"deviceName":{"platform":"Android","app":"./app/app-homolog-debug.apk","desiredCapabilities":{"deviceName":"Pixel_3_API_25","platformVersion":"8.0","automationName":"UiAutomator2","noReset":false,"fullReset":true,"udid":"emulator-5554","systemPort":8200}},"platformVersion":"8.0","noReset":false,"fullReset":true,"udid":"emulator-5554","app":"/Users/willian.nunes/Documents/automacao/mobile/app/app-homolog-debug.apk","platformName":"Android"},"firstMatch":[{}]},"desiredCapabilities":{"deviceName":{"platform":"Android","app":"./app/app-homolog-debug.apk","desiredCapabilities":{"deviceName":"Pixel_3_API_25","platformVersion":"8.0","automationName":"UiAutomator2","noReset":false,"fullReset":true,"udid":"emulator-5554","systemPort":8200}},"platformVersion":"8.0","noReset":false,"fullReset":true,"udid":"emulator-5554","app":"/Users/xxxx/Documents/automacao/mobile/app/app-homolog-debug.apk","platformName":"Android"}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"deviceName":{"platform":"Android","app":"./app/app-homolog-debug.apk","desiredCapabilities":{"deviceName":"Pixel_3_API_25","platformVersion":"8.0","automationName":"UiAutomator2","noReset":false,"fullReset":true,"udid":"emulator-5554","systemPort":8200}},"platformVersion":"8.0","noReset":false,"fullReset":true,"udid":"emulator-5554","app":"/Users/willian.nunes/Documents/automacao/mobile/app/app-homolog-debug.apk","platformName":"Android"},null,{"alwaysMatch":{"deviceName":{"platform":"Android","app":"./app/app-homolog-debug.apk","desiredCapabilities":{"deviceName":"Pixel_3_API_25","platformVersion":"8.0","automationName":"UiAutomator2","noReset":false,"fullReset":true,"udid":"emulator-5554","systemPort":8200}},"platformVersion":"8.0","noReset":false,"fullReset":true,"udid":"emulator-5554","app":"/Users/xxxx/Documents/automacao/mobile/app/app-homolog-debug.apk","platformName":"Android"},"firstMatch":[{}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1646775115940 (18:31:55 GMT-0300 (Brasilia Standard Time))
[BaseDriver] The following capabilities are not standard capabilities and should have an extension prefix:
[BaseDriver]   deviceName
[BaseDriver]   platformVersion
[BaseDriver]   noReset
[BaseDriver]   fullReset
[BaseDriver]   udid
[BaseDriver]   app
[Appium] Could not parse W3C capabilities: 'deviceName' must be of type string
[Appium] Trying to fix W3C capabilities by merging them with JSONWP caps
[BaseDriver] The following capabilities are not standard capabilities and should have an extension prefix:
[BaseDriver]   deviceName
[BaseDriver]   platformVersion
[BaseDriver]   noReset
[BaseDriver]   fullReset
[BaseDriver]   udid
[BaseDriver]   app
[Appium] Could not parse fixed W3C capabilities: 'deviceName' must be of type string. Falling back to JSONWP protocol
[Appium] 
[Appium] ======================================================================
[Appium]   DEPRECATION WARNING:
[Appium] 
[Appium]   The 'automationName' capability was not provided in the desired 
[Appium]   capabilities for this Android session
[Appium] 
[Appium]   Setting 'automationName=UiAutomator2' by default and using the 
[Appium]   UiAutomator2 Driver
[Appium] 
[Appium]   The next major version of Appium (2.x) will **require** the 
[Appium]   'automationName' capability to be set for all sessions on all 
[Appium]   platforms
[Appium] 
[Appium]   In previous versions (Appium <= 1.13.x), the default was 
[Appium]   'automationName=UiAutomator1'
[Appium] 
[Appium]   If you wish to use that automation instead of UiAutomator2, please 
[Appium]   add 'automationName=UiAutomator1' to your desired capabilities
[Appium] 
[Appium]   For more information about drivers, please visit 
[Appium]   http://appium.io/docs/en/about-appium/intro/ and explore the 
[Appium]   'Drivers' menu
[Appium] 
[Appium] ======================================================================
[Appium] 
[Appium] Appium v1.22.2 creating new AndroidUiautomator2Driver (v1.70.1) session
[debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {
[debug] [BaseDriver]   "deviceName": {
[debug] [BaseDriver]     "platform": "Android",
[debug] [BaseDriver]     "app": "./app/app-homolog-debug.apk",
[debug] [BaseDriver]     "desiredCapabilities": {
[debug] [BaseDriver]       "deviceName": "Pixel_3_API_25",
[debug] [BaseDriver]       "platformVersion": "8.0",
[debug] [BaseDriver]       "automationName": "UiAutomator2",
[debug] [BaseDriver]       "noReset": false,
[debug] [BaseDriver]       "fullReset": true,
[debug] [BaseDriver]       "udid": "emulator-5554",
[debug] [BaseDriver]       "systemPort": 8200
[debug] [BaseDriver]     }
[debug] [BaseDriver]   },
[debug] [BaseDriver]   "platformVersion": "8.0",
[debug] [BaseDriver]   "noReset": false,
[debug] [BaseDriver]   "fullReset": true,
[debug] [BaseDriver]   "udid": "emulator-5554",
[debug] [BaseDriver]   "app": "/Users/xxxx/Documents/automacao/mobile/app/app-homolog-debug.apk",
[debug] [BaseDriver]   "platformName": "Android"
[debug] [BaseDriver] }
[BaseDriver] SessionNotCreatedError: A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s): 'deviceName' must be of type string
[BaseDriver]     at AndroidUiautomator2Driver.validateDesiredCaps (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:231:25)
[BaseDriver]     at AndroidUiautomator2Driver.validateDesiredCaps (/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/lib/driver.js:171:18)
[BaseDriver]     at AndroidUiautomator2Driver.createSession (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/session.js:46:8)
[BaseDriver]     at AndroidUiautomator2Driver.createSession (/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/lib/driver.js:177:43)
[BaseDriver]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:387:43)
[BaseDriver]     at runMicrotasks (<anonymous>)
[BaseDriver]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[debug] [UiAutomator2] Deleting UiAutomator2 session
[HTTP] --> POST /wd/hub/session

**Comment by KazuCocoa** [comment]
Your client sent the below JSON body:

> [HTTP] {"capabilities":{"alwaysMatch":{"deviceName":{"platform":"Android","app":"./app/app-homolog-debug.apk","desiredCapabilities":{"deviceName":"Pixel_3_API_25","platformVersion":"8.0","automationName":"UiAutomator2","noReset":false,"fullReset":true,"udid":"emulator-5554","systemPort":8200}},"platformVersion":"8.0","noReset":false,"fullReset":true,"udid":"emulator-5554","app":"/Users/willian.nunes/Documents/automacao/mobile/app/app-homolog-debug.apk","platformName":"Android"},"firstMatch":[{}]},"desiredCapabilities":{"deviceName":{"platform":"Android","app":"./app/app-homolog-debug.apk","desiredCapabilities":{"deviceName":"Pixel_3_API_25","platformVersion":"8.0","automationName":"UiAutomator2","noReset":false,"fullReset":true,"udid":"emulator-5554","systemPort":8200}},"platformVersion":"8.0","noReset":false,"fullReset":true,"udid":"emulator-5554","app":"/Users/xxxx/Documents/automacao/mobile/app/app-homolog-debug.apk","platformName":"Android"}}

**Comment by jlipps** [comment]
As you can see, there is some strange structure in your capabilities. Once you fix that, things should work.

**Comment by jlipps** [comment]
I'm guessing it's a bug somewhere in your worker code where you're extracting capabilities from your device map. Somehow they're getting merged or assigned inappropriately.

**Comment by willianqa** [comment]
before

const configs = devices.map(device => {
let data = {
helpers: {
Appium: {device}
}
}

after

const configs = devices.map(device => {
let data = {
helpers: {
Appium: device
}
}

Done

**Comment by jlipps** [comment]
👍  nice!
