### ISSUE TITLE
WDA continues to run even after AppiumDriver.quit()

### ISSUE THREAD

**Issue by davidjonesdialexa** [appium/appium#16536]
## The problem

I noticed both when running a test via my suite and when inspecting using Appium Inspector, the "Automation Running" overlay remains on screen even after I kill the driver. Has anyone else experienced this? I'm using the [Basic configuration](https://appium.io/docs/en/drivers/ios-xcuitest-real-devices/) for WDA with capabilities in both my suite and the inspector. If I hold down the volume buttons, the overlay clears. It will also clear if I delete the WDA "app" on the device. If I use the volume buttons to clear the overlay, I'm unable to run a test until I kill the 8100 port.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.2
* Desktop OS/version used to run Appium: Mac OS 12.2
* Node.js version (unless using Appium.app|exe): 16.1
* Npm or Yarn package manager: npm 7.13
* Mobile platform/version under test: iOS 15
* Real device or emulator/simulator: real iphone 12 mini
* Appium CLI or Appium.app|exe: both

## Link to Appium logs

[Appium Logs following test run](https://gist.github.com/davidjonesdialexa/7192b4bab274e57a43773edf9d159486)

## Code To Reproduce Issue [ Good To Have ]

    private AppiumDriverLocalService service = AppiumDriverLocalService.buildDefaultService();
    protected static AppiumDriver driver;
    protected static String OS;

    @BeforeSuite
    public void startUp() throws IOException, InterruptedException {
        startServer();
        WebDriverBuilder webDriverBuilder = new WebDriverBuilder(); 
        DesiredCapabilities capabilities = new DesiredCapabilities();
        webDriverBuilder.setCapability(capabilities);
        try {
            driver = new AppiumDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
        } catch (Exception e) {
            throw new SkipException("Unable to start driver");
        }
        OS = driver.getPlatformName();

    }

    @AfterSuite(alwaysRun = true)
    public void teardown() {
        try {
            this.driver.quit();
            System.out.println("Quit driver");
        } catch (Exception e) {
            System.out.println(e + "Unable to quit driver");
        }
        stopServer();
    }

    public void startServer() {
        service.start();
        System.out.println("Server Started");
    }

    public void stopServer() {
        service.stop();
        System.out.println("Server Stopped");
    }

WebDriverBuilder class

            capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
            capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "15.3");
            capabilities.setCapability(MobileCapabilityType.UDID, UDID);
            capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, DEVICE_NAME);
            capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");
            capabilities.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
            capabilities.setCapability("xcodeOrgId", ORG_ID);
            capabilities.setCapability("xcodeSigningId", "iPhone Developer");
            capabilities.setCapability("usePrebuiltWDA", true);
            capabilities.setCapability("derivedDataPath", "~/Library/Developer/Xcode/DerivedData");

**Comment by KazuCocoa** [comment]
hm, it seems like https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/lib/utils.js#L269 sigterm did not work or did not reach the process.

**Comment by mykola-mokhnach** [comment]
The described behaviour is expected. We deliberately don't kill WebDriverAgent process on the device to speed up the startup of the following sessions.

**Comment by KazuCocoa** [comment]
I remember `useNewWDA` capability allows to stop the xcodebuild process at the end.

**Comment by DavidHJones36** [comment]
@mykola-mokhnach Thanks for clarifying, so this just means the WDA “app” continues to run? That would make sense. I haven’t tried killing it with the app switcher but would that clear port 8100? As I noted in the issue, the volume button approach doesn’t seem to clear the port so a follow up run doesn’t work.

**Comment by davidjonesdialexa** [comment]
@mykola-mokhnach Thanks for clarifying, so this just means the WDA “app” continues to run? That would make sense. I haven’t tried killing it with the app switcher but would that clear port 8100? As I noted in the issue, the volume button approach doesn’t seem to clear the port so a follow up run doesn’t work.

**Comment by mykola-mokhnach** [comment]
If we are talking about real devices there are basically two main parts there for the generic configuration. The xcodebuild process running on the local machine and WDA running on the device. Killing any of them would automatically terminate the other one.

**Comment by davidjonesdialexa** [comment]
Ok, I think I have this figured out. I'll close this issue. @mykola-mokhnach if you have a few minutes could you take a quick look at another issue I'm having? https://discuss.appium.io/t/driver-getcontexthandles-doesnt-return-multiple-handles-using-exe-but-does-with-desktop/35855

**Comment by pweev** [comment]
> Ok, I think I have this figured out. I'll close this issue. @mykola-mokhnach if you have a few minutes could you take a quick look at another issue I'm having? https://discuss.appium.io/t/driver-getcontexthandles-doesnt-return-multiple-handles-using-exe-but-does-with-desktop/35855

Hello David. I'm having the same exact issue here and am struggling to get it resolved. How did you end up solving this?

If I close the app with the volume buttons, on my next run from my python script, am getting errors and the wda will not run and eventually get 500 with app removal. I also noticed when I run the initial build script after installing appium, it kills xcode and the wda is ended no problem. 

Thanks in advance for your help.

**Comment by androidfans** [comment]
same issue too
