### ISSUE TITLE
Unable to use FindElementByImage() method

### ISSUE THREAD

**Issue by harshcapita** [appium/appium#16544]
## The problem

I want to use FindElementByImage() method to identify some image on screen and then click on it. But it is throwing an exception- "'opencv4nodejs' module is required to use OpenCV features. Please install it first ('npm i -g opencv4nodejs') and restart Appium. Read https://github.com/justadudewhohacks/opencv4nodejs#how-to-install for more details on this topic."

## Environment

Appium version (or git revision) that exhibits the issue: 1.21.0
Last Appium version that did not exhibit the issue (if applicable): NA
Desktop OS/version used to run Appium: Windows 10 64-bit
Node.js version (unless using Appium.app|exe): v16.13.2
Npm or Yarn package manager: 8.1.2
Mobile platform/version under test: UWP app
Real device or emulator/simulator: Running on Windows 10 64-bit machine
Appium CLI or Appium.app|exe: Appium CLI

## Details

I have tried all the possibilities to get OpenCV installed on my machine using below commands-
1. npm i -g opencv4nodejs
2. npm install --save opencv4nodejs
Both these commands resulted in below error-

![OpenCVInstallationError](https://user-images.githubusercontent.com/100405531/157597267-1bc12a17-9ef3-482a-a1ee-af0efd77686a.png)

## Link to Appium logs

Below is the exception that I am getting-
  Message: 
OpenQA.Selenium.WebDriverException : An unknown server-side error occurred while processing the command. Original error: 'opencv4nodejs' module is required to use OpenCV features. Please install it first ('npm i -g opencv4nodejs') and restart Appium. Read https://github.com/justadudewhohacks/opencv4nodejs#how-to-install for more details on this topic.

## Code To Reproduce Issue [ Good To Have ]

Please refer to the below set of sample code similar to what i am using-

      public void ClickImage(string imageName)
        {
            try
            {
                // Here we are first converting the image to base64 representation
                var encodedImage = _encodingService.EncodeImageToBase64(imageName);

                // Finding image
                var imageElement = AppiumDriver.FindElementByImage(encodedImage); // **It is failing here and giving the opencv4nodejs exception.**

                Assert.True(imageElement.Displayed);
                imageElement.Click();
            }
            catch (Exception e)
            {
                _log.Error($"Error verifying image is displayed", e);
                throw;
            }
        }

**Comment by mykola-mokhnach** [comment]
Unfortunately opencv4nodejs library has not been maintained for a while and we cannot do anything to change that. Consider switching to Appium2 and adding the [image recognition](https://github.com/appium/appium-plugins/tree/master/packages/images) plugin to it. This plugin has been updated to use a different OpenCV wrapper.

**Comment by StephanB75** [comment]
Here a short installation guide i have used for installing on macs
(used node 12)
brew install opencv@3
brew link opencv@3
export OPENCV4NODEJS_DISABLE_AUTOBUILD=0
export OPENCV4NODEJS_AUTOBUILD_FLAGS=-DBUILD_LIST=core,imgproc,imgcodecs,videoio,highgui,video,calib3d,features2d,objdetect,dnn,ml,flann,photo,stitching,gapi

npm i -g opencv-build
npm i -g opencv4nodejs
sudo npm link opencv4nodejs

**Comment by harshcapita** [comment]
@StephanB75 - Thanks for your input.
On hitting this command(npm i -g opencv4nodejs), it is giving an error 'OPENCV_LIB_DIR has to be defined on windows when auto build is disabled'.
What have you set in OPENCV_LIB_DIR variable?
Also if you have set any other OPENCV variables other than this, can you please share that too.

**Comment by StephanB75** [comment]
For mac i have to install the libraries for openCV via brew before i can install opencv4nodejs via npm

Maybe you check the infos here for windows installation
https://github.com/justadudewhohacks/opencv4nodejs

**Comment by jlipps** [comment]
@harshcapita believe me, using the appium 2 image plugin will be _much_ easier than trying to figure out opencv4nodejs issues.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
