### ISSUE TITLE
Appium Issue on Mac System

### ISSUE THREAD

**Issue by NaleSupriya** [appium/appium#16543]
Hi Team, 

We are interested to use the Appium for our current application CoinOut.
I have tried the latest version dmg 1.22.2, but while opening it on my Mac system(Mac OS : 12.2.1) it just throwing an error(attaching image).
Please guide us to overcome this issue. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.2
* Mac OS/version used to run Appium: 12.2.1

<img width="261" alt="AppiumError" src="https://user-images.githubusercontent.com/88704871/157596919-dcbbe773-e9bb-43c2-8308-8ca652737096.png">
<img width="256" alt="Appium_Error" src="https://user-images.githubusercontent.com/88704871/157596931-0f9c4743-d9f2-4a85-adfb-9b875c3b8888.png">

**Comment by mykola-mokhnach** [comment]
Consider using [Appium Inspector](https://github.com/appium/appium-inspector) instead. The GUI part is not maintained anymore.

Regarding the screenshot above: please carefully check the readme: https://github.com/appium/appium-inspector#installing-on-macos

Closed as not an issue

**Comment by NaleSupriya** [comment]
Getting this error

Not enough arguments for option -c. Expected at least 1 but got 0

 for  cmd

 xattr -cr


—



Supriya Nale
Engineering Lead

+91 9860628220

***@***.******@***.***>



[signature_1383669314]<http://www.persistent.com/>



See Beyond, Rise Above

________________________________

**Comment by jlipps** [comment]
@NaleSupriya you can also just use the hosted inspector at https://inspector.appiumpro.com. as for the error, seems like you have a different version of `xattr` on your machine, maybe run `man xattr` to see the instructions. basically we want to recursively remove/clear the `com.apple.quarantine` attribute from the file(s)
