### ISSUE TITLE
Unhandled endpoint: .../css/value when testing on IOS *Native* app on simulator

### ISSUE THREAD

**Issue by Idoser99** [appium/appium#16549]
## The problem

Hi, I am testing on IOS simulator and sometimes the tests fail with the following error: 
'Unhandled endpoint: /session/90A8AC56-ED4E-4327-B748-C199A71152CB/element/9A060000-0000-0000-F14B-000000000000/css/value'
I am testing an entirely native app and does not change any context during the execution(java client).

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.2
* Last Appium version that did not exhibit the issue (if applicable): 1.22.0
* Desktop OS/version used to run Appium: MacOS(M1) Monterey 12.0.1
* Node.js version (unless using Appium.app|exe): v16.14.0
* Npm or Yarn package manager: 8.3.1
* Mobile platform/version under test: 15.2
* Real device or emulator/simulator: Simulator

## Details

the code triggers the problem:
`WebElement fruitPhoto = wait.until(visibilityOfElementLocated(MobileBy.id("fruitImage")));
  log.info("waiting up to 3 min for photos to upload");
  WebDriverWait processWait = new WebDriverWait(driver, 180);
  processWait.until(attributeToBe(fruitPhoto, "value", "1"));`
The case is as follow:
the app is loading a new page and the first action is waiting for the element to have the value "1"(will be "0" while waiting)
most of the time the test succeed but sometimes I get the error mentioned above.

Regarding to appium logs:
The invoked path: http://127.0.0.1:8100/session/37572450-9CBB-4D96-81A9-FDE13FC8C96E/element/B9060000-0000-0000-7C7F-000000000000/attribute/value
According to the response detailed here: https://appium.io/docs/en/commands/element/attributes/attribute/#:~:text=The%20value%20of%20the%20attribute%20or%20null%20if%20not%20set%20
the response contains the value null if the attribute isn't set yet.
Successful test: the attribute is "0" at the first time and then waiting until it will evaluate to "1".
Failed tests: call appium server with the path maintained above (.../attribute/value), the server return the value null.
Then, the second call triggers: .../css/value (native app)

## Link to Appium logs

Successful test: https://gist.github.com/Idoser99/0ab97366ea4ad9a50065d83fa65f0dad
Failed test: https://gist.github.com/Idoser99/6ae06cdd3e9bbfff8dd3d710cf0a39f9

**Comment by mykola-mokhnach** [comment]
Sorry, but the attached log is impossible to read.

I assume that the issue lies in the client which is using an unsupported API to request the value (there is no css in native context).

**Comment by Idoser99** [comment]
@mykola-mokhnach fixed the logs.

**Comment by mykola-mokhnach** [comment]
> 02:09:07 [debug] [WD Proxy] Matched '/wd/hub/session/407c481c-a2a1-4c81-8d48-914fd18f4363/element/9A060000-0000-0000-F14B-000000000000/css/value' to command name 'getCssProperty'

So yes, my assumption Wass correct. This call is probably ok for a web context, but it does not make much sense in the native context. Consider tuning the client code to exclude it

**Comment by Idoser99** [comment]
Ok, thanks. I'll change the code accordingly.
