### ISSUE TITLE
"Automation Running" overlay on iOS15 breaks camera based screen capture for automation

### ISSUE THREAD

**Issue by johndoe422** [appium/appium#16558]
## The problem

I am using a tool to automate tests on iPhones. The tool uses Appium as the test framework. In iOS version 15, the screen shows a dark overlay with the text "Automation Running". I am aware that this does not affect the test at all.

However, my problem is that I use a camera placed in front of the mobile phone to capture the screen and do some checks on the captured video. I have to use the camera itself since I run tests on OTT applications and there is no way to capture the video using software mechanisms because of DRM protection. This "Automation Running" overlay messes up with the checks that I am running on the video captured through the camera.

## Environment

Latest Appium Version
Latest iOS Version (15)

**Comment by mykola-mokhnach** [comment]
This overlay is a built-in Apple security feature and there is no known way to disable it while an XCTest process css running. Consider reporting your issue to Apple or changing the way screen capture is done.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by mroreo1** [comment]
Same issue i am facing for DRM is any solutuon available right now ???

**Comment by johndoe422** [comment]
No. I don't think there will be any solution for this unless Apple come to
their senses and realize that there are OTT apps also in the market, and
they need to be tested too, using automated means.
