### ISSUE TITLE
Recording parallel runs on iOS (real device) records the video of other devices that are running in parallel 

### ISSUE THREAD

**Issue by chanduguthikonda** [appium/appium#16554]
## The problem

Recording parallel runs on iOS (real device) records the video of other devices that are running in parallel

## Environment

* Appium version that exhibits the issue: **1.21.0**
* Desktop OS/version used to run Appium: **Mac Catalina v10.15.4**
* Node.js version (unless using Appium.app|exe): **v12.20.0**
* Test Framework: WebDriver.IO
* Mobile platform/version under test: **iOS 14.4.2(iPhone) and 14.3(iPad)**
* Real device or emulator/simulator: **Real Device (iOs: iPhone and iPad)**

## Details

We have 3 devices connected to an appium server with different appium ports and wdalocalports on a Mac mini. I'll call it Device A and Device B and Device C

We have a test command that triggers the tests on all the three devices and tests runs in parallel.
We have the command **driver.startRecordingScreen();** in beforeTest and **driver.stopRecordingScreen();** command in the afterTest() 
When the test runs on Device A, Device B and Device C,  the command driver.startRecordingScreen() will be triggered in the respective sessions.
When the tests on Device A, B and C is over, the command driver.stopRecordingScreen() will be triggered in the afterTest() which is supposed to return A.mp4, B.mp4, C.mp4 but: 
 
**The video A.mp4 and B.mp4 are fine. However, the video C.mp4 shows the screen of Device A.**

Device A: iPad
Device B: iPhone 1
Device C: iPhone 2

Note: All the devices have unique appium ports (4755, 4751 and 4735) and wdaLocalPort (8105, 8101 and 8102) defined in their respective capability files.

**Comment by jlipps** [comment]
@mykola-mokhnach what do you think? I know you are familiar with how the screen recording works on iOS.

**Comment by KazuCocoa** [comment]
Could you share the capabilities?
I wonder if it did not have proper `mjpegServerPort` https://github.com/appium/appium-xcuitest-driver#important-real-device-capabilities

**Comment by amedvedjev** [comment]
we running successfully video using 12 iPhones connected to macMini.

@chanduguthikonda pls provide your:
1) appium server start parameters
2) driver start capabilities

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by bswhb** [comment]
Hi @amedvedjev , could you please shed some light on how to set the mjpegServerPort params in appium server start params?

We've set different mjpegServerPort in iPhone device caps, but it seems in appium logs the ports (let's say 9101) other than 9100 can not be accessed through http://127.0.0.1:9101, and finally the start recording command failed.

Kindly please advise, thanks a lot!

**Comment by Kullapat-palo** [comment]
> Hi @amedvedjev , could you please shed some light on how to set the mjpegServerPort in appium server start params?
> 
> We've set different mjpegServerPort in iPhone device caps, but it seems in appium logs the ports (let's say 9101) other than 9100 can not be accessed through http://127.0.0.1:9101, and finally the start recording command failed.
> 
> Kindly please advise, thanks a lot!

I also face the same issue. I've tried to change mjpegServerPort to `9200` and it's won't work until I set the default one (9100)

```
[debug] [iProxy@00008120:9200] Unexpected data: {"header":{"length":294,"version":1,"type":8,"tag":1},"payload":{"MessageType":"Result","Number":2}}
[ffmpeg] http://127.0.0.1:9200: End of file
[ffmpeg]
```

**Comment by el-03** [comment]
I've got the same problem, it seems the stream to http://127.0.0.1:`mjpegServerPort`/ is failed
