### ISSUE TITLE
script mobile text error

### ISSUE THREAD

**Issue by atimofeev86** [appium/appium#16560]
## The problem

I try use script mobile text to enter text by symbols:
driver.ExecuteScript("mobile: type", new Dictionary<string, object> { { "text", ch } });

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable): 1.22.2
* Desktop OS/version used to run Appium: windows 10
andoid 10 (MIUI)
smartphone xiaomi Redmi9A

## Details

I Try to enter few symbols. First symbol "т" (cyrilyc) entered good.
on enter second symbol I got error.

## Link to Appium logs

[debug] [W3C (8dfa0359)] Calling AppiumDriver.isKeyboardShown() with args: ["8dfa0359-d38a-4304-88fa-baecc40a53f1"]
[debug] [ADB] Running 'C:\AndroidSDK\platform-tools\adb.exe -P 5037 -s PJAENB85ZLKFDUDU shell dumpsys input_method'
[debug] [W3C (8dfa0359)] Responding to client with driver.isKeyboardShown() result: true
[HTTP] <-- GET /wd/hub/session/8dfa0359-d38a-4304-88fa-baecc40a53f1/appium/device/is_keyboard_shown 200 100 ms - 14
[HTTP]
[HTTP] --> POST /wd/hub/session/8dfa0359-d38a-4304-88fa-baecc40a53f1/execute/sync
[HTTP] {"script":"mobile: type","args":[{"text":"т"}]}
[debug] [W3C (8dfa0359)] Calling AppiumDriver.execute() with args: ["mobile: type",[{"text":"т"}],"8dfa0359-d38a-4304-88fa-baecc40a53f1"]
[AndroidDriver] Executing native command 'mobile: type'
[debug] [ADB] Typing 1 character
[debug] [ADB] Running 'C:\AndroidSDK\platform-tools\adb.exe -P 5037 -s PJAENB85ZLKFDUDU shell settings get secure default_input_method'
[debug] [ADB] Running 'C:\AndroidSDK\platform-tools\adb.exe -P 5037 -s PJAENB85ZLKFDUDU shell ime enable io.appium.settings/.UnicodeIME'
[debug] [ADB] Running 'C:\AndroidSDK\platform-tools\adb.exe -P 5037 -s PJAENB85ZLKFDUDU shell ime set io.appium.settings/.UnicodeIME'
[debug] [ADB] Running 'C:\AndroidSDK\platform-tools\adb.exe -P 5037 -s PJAENB85ZLKFDUDU shell 'input text "&BEI-"''
[debug] [ADB] Running 'C:\AndroidSDK\platform-tools\adb.exe -P 5037 -s PJAENB85ZLKFDUDU shell ime set io.appium.settings/.AppiumIME'
[debug] [W3C (8dfa0359)] Responding to client with driver.execute() result: true
[HTTP] <-- POST /wd/hub/session/8dfa0359-d38a-4304-88fa-baecc40a53f1/execute/sync 200 1746 ms - 14
[HTTP]
[HTTP] --> POST /wd/hub/session/8dfa0359-d38a-4304-88fa-baecc40a53f1/execute/sync
[HTTP] {"script":"mobile: type","args":[{"text":"е"}]}
[debug] [W3C (8dfa0359)] Calling AppiumDriver.execute() with args: ["mobile: type",[{"text":"е"}],"8dfa0359-d38a-4304-88fa-baecc40a53f1"]
[AndroidDriver] Executing native command 'mobile: type'
[debug] [ADB] Typing 1 character
[debug] [ADB] Running 'C:\AndroidSDK\platform-tools\adb.exe -P 5037 -s PJAENB85ZLKFDUDU shell settings get secure default_input_method'
[debug] [ADB] Running 'C:\AndroidSDK\platform-tools\adb.exe -P 5037 -s PJAENB85ZLKFDUDU shell ime enable io.appium.settings/.UnicodeIME'
[debug] [ADB] Running 'C:\AndroidSDK\platform-tools\adb.exe -P 5037 -s PJAENB85ZLKFDUDU shell ime set io.appium.settings/.UnicodeIME'
[debug] [ADB] Running 'C:\AndroidSDK\platform-tools\adb.exe -P 5037 -s PJAENB85ZLKFDUDU shell input text &BDU-'
[debug] [ADB] Running 'C:\AndroidSDK\platform-tools\adb.exe -P 5037 -s PJAENB85ZLKFDUDU shell ime set io.appium.settings/.AppiumIME'
[debug] [W3C (8dfa0359)] Encountered internal error running command: Error executing adbExec. Original error: 'Command 'C:\\AndroidSDK\\platform-tools\\adb.exe -P 5037 -s PJAENB85ZLKFDUDU shell input text \&BDU-' exited with code 127'; Command output: /system/bin/sh: BDU-: inaccessible or not found
[debug] [W3C (8dfa0359)] Usage: input [<source>] [-d DISPLAY_ID] <command> [<arg>...]
[debug] [W3C (8dfa0359)]
[debug] [W3C (8dfa0359)] The sources are:
[debug] [W3C (8dfa0359)]       dpad
[debug] [W3C (8dfa0359)]       keyboard
[debug] [W3C (8dfa0359)]       mouse
[debug] [W3C (8dfa0359)]       touchpad
[debug] [W3C (8dfa0359)]       gamepad
[debug] [W3C (8dfa0359)]       touchnavigation
[debug] [W3C (8dfa0359)]       joystick
[debug] [W3C (8dfa0359)]       touchscreen
[debug] [W3C (8dfa0359)]       stylus
[debug] [W3C (8dfa0359)]       trackball
[debug] [W3C (8dfa0359)]
[debug] [W3C (8dfa0359)] -d: specify the display ID.
[debug] [W3C (8dfa0359)]       (Default: -1 for key event, 0 for motion event if not specified.)
[debug] [W3C (8dfa0359)] The commands and default sources are:
[debug] [W3C (8dfa0359)]       text <string> (Default: touchscreen)
[debug] [W3C (8dfa0359)]       keyevent [--longpress] <key code number or name> ... (Default: keyboard)
[debug] [W3C (8dfa0359)]       tap <x> <y> (Default: touchscreen)
[debug] [W3C (8dfa0359)]       swipe <x1> <y1> <x2> <y2> [duration(ms)] (Default: touchscreen)
[debug] [W3C (8dfa0359)]       draganddrop <x1> <y1> <x2> <y2> [duration(ms)] (Default: touchscreen)
[debug] [W3C (8dfa0359)]       press (Default: trackball)
[debug] [W3C (8dfa0359)]       roll <dx> <dy> (Default: trackball)
[debug] [W3C (8dfa0359)]       event <DOWN|UP|MOVE> <x> <y> (Default: touchscreen)
[debug] [W3C (8dfa0359)]       tmode <tmode>
[debug] [W3C (8dfa0359)]
[debug] [W3C (8dfa0359)] Error: Argument expected after "text"
[debug] [W3C (8dfa0359)]
[debug] [W3C (8dfa0359)] Error: Command 'C:\\AndroidSDK\\platform-tools\\adb.exe -P 5037 -s PJAENB85ZLKFDUDU shell input text \&BDU-' exited with code 127
[debug] [W3C (8dfa0359)]     at ChildProcess.<anonymous> (C:\Users\1\AppData\Roaming\npm\node_modules\appium\node_modules\teen_process\lib\exec.js:113:19)
[debug] [W3C (8dfa0359)]     at ChildProcess.emit (node:events:520:28)
[debug] [W3C (8dfa0359)]     at maybeClose (node:internal/child_process:1092:16)
[debug] [W3C (8dfa0359)]     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
[HTTP] <-- POST /wd/hub/session/8dfa0359-d38a-4304-88fa-baecc40a53f1/execute/sync 500 1642 ms - 2949
[HTTP]

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by atimofeev86** [comment]
when I try to enter first symbol "е" it's good, and second symbol "к" no good.

**Comment by KazuCocoa** [comment]
> [debug] [W3C (8dfa0359)] Encountered internal error running command: Error executing adbExec. Original error: 'Command 'C:\AndroidSDK\platform-tools\adb.exe -P 5037 -s PJAENB85ZLKFDUDU shell input text &BDU-' exited with code 127'; Command output: /system/bin/sh: BDU-: inaccessible or not found

Probably `shell input text &BDU-` should be `shell input text "&BDU-"` like `[debug] [ADB] Running 'C:\AndroidSDK\platform-tools\adb.exe -P 5037 -s PJAENB85ZLKFDUDU shell 'input text "&BEI-"''`

Around https://github.com/appium/appium-adb/blob/86807a3dbde31c4c2ae49e0fddfeafad368d6bdc/lib/tools/adb-commands.js#L586 ? Will take a look later.

**Comment by mykola-mokhnach** [comment]
I did several fixes there, although they are only available in newer module versions which are only available in the recent driver release only compatible to Appium2

**Comment by atimofeev86** [comment]
version 1.22.0 works correctly
