### ISSUE TITLE
Appium starts I think? Then this error appears.

### ISSUE THREAD

**Issue by danbudworthmead** [appium/appium#16573]
## The problem

I get a uncaughtException: EPIPE: broken pipe, write error

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:  Windows 10
* Node.js version (unless using Appium.app|exe): v15.0.1
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Pixel 4 & Samsung A50
* Real device or emulator/simulator: Real devices
* Appium CLI or Appium.app|exe: appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/danbudworthmead/d5763315918b4e696127cb35fea863a1

## Code To Reproduce Issue [ Good To Have ]

subprocess.Popen(cmd, stdout=subprocess.PIPE, shell=True)

where cmd = "C:/Users/acurl/AppData/Roaming/nvm/v15.0.1/appium.cmd" -a 127.0.0.1 -p 4730 -g "Z:/GitHub/lkwd/JenkinsTestrunner3/results/smoke_tests/2022-03-13_20-53-53_smoke_tests/20220313205634_appium_server.log" -bp 4724 --log-level debug --local-timezone

**Comment by mykola-mokhnach** [comment]
This exception happens in the third party logging module. I assume the destination log file is either not writeable or points to a non-existing location

**Comment by danbudworthmead** [comment]
> This exception happens in the third party logging module. I assume the destination log file is either not writeable or points to a non-existing location

That's really weird because the log snippet I sent is in the logging file?

**Comment by mykola-mokhnach** [comment]
> > This exception happens in the third party logging module. I assume the destination log file is either not writeable or points to a non-existing location
> 
> That's really weird because the log snippet I sent is in the logging file?

No idea 🤷 You could try to raise an issue for Winston module to get more details on that.

I would also try the same with Appium2 as we don't commit any changes/fixes into Appium1 anymore.

**Comment by danbudworthmead** [comment]
> > > This exception happens in the third party logging module. I assume the destination log file is either not writeable or points to a non-existing location
> > 
> > 
> > That's really weird because the log snippet I sent is in the logging file?
> 
> No idea 🤷 You could try to raise an issue for [Winston](https://github.com/winstonjs/winston) module to get more details on that.
> 
> I would also try the same with Appium2 as we don't commit any changes/fixes into Appium1 anymore.

Oh, there's an appium2? Sorry, I got dropped onto a production scale work project where all the old devs quit with little to no docs haha

**Comment by danbudworthmead** [comment]
> I would also try the same with Appium2 as we don't commit any changes/fixes into Appium1 anymore.

I'm on Appium version 1.22.2. Do you mean this by Appium2? https://www.npmjs.com/package/appium2

**Comment by mykola-mokhnach** [comment]
https://appiumpro.com/editions/122-installing-appium-20-and-the-driver-and-plugins-cli

**Comment by danbudworthmead** [comment]
> Perhaps it has something to do with the fact the code is running on Windows?

Not sure if I mentioned, but this project was initially built with macOS in mind. The previous devs all worked on mac but I don't have one so I have been fixing bits up to work on Windows. Maybe this information helps?

**Comment by wbt** [comment]
That could be something to check; try it on a non-Windows machine (if you have a big production project, maybe you have access to AWS or other ability to easily spin up another OS) and see if that makes a difference.  I don't know Appium well enough to try to figure out what console it's trying to log to but your original error log makes it look like the connection to a console is what's missing, and that connection might be running through Appium.  You might also look for ways to disable logging to console, especially if the file has all the information you need.

**Comment by danbudworthmead** [comment]
> That could be something to check; try it on a non-Windows machine (if you have a big production project, maybe you have access to AWS or other ability to easily spin up another OS) and see if that makes a difference. I don't know Appium well enough to try to figure out what console it's trying to log to but your original error log makes it look like the connection to a console is what's missing, and that connection might be running through Appium. You might also look for ways to disable logging to console, especially if the file has all the information you need.

Yeah, one of my remote colleagues says it works on their Mac device. We're not sure what's different though hmm...

**Comment by danbudworthmead** [comment]
removed the stdout=subprocess.PIPE and the code is actually running now. Not entirely sure if I need to pipe the output...

**Comment by mykola-mokhnach** [comment]
> removed the stdout=subprocess.PIPE and the code is actually running now. Not entirely sure if I need to pipe the output...

Most likely not if the log is already written to a file. As for Winston-related stuff it would probably make sense to improve the actual error message and make it more helpful

**Comment by wbt** [comment]
While Winston is open to pull requests, it seems to me like this one correctly reported a broken pipe when trying to log to console; I'm not sure what specific improvements you might suggest making to that.
