### ISSUE TITLE
iOS: Reliable way to perform double tap using w3_actions?

### ISSUE THREAD

**Issue by tarun550** [appium/appium#16583]
## The problem

No reliable way to perform double tap using w3_actions on iOS
I expect this to work correctly
```
actions = ActionChains(driver)
actions.w3c_actions = ActionBuilder(driver, mouse=PointerInput(POINTER_TOUCH, "touch"))
actions.w3c_actions.pointer_action.move_to_location(x, y)
actions.w3c_actions.pointer_action.pointer_down()
actions.w3c_actions.pointer_action.pause(0.1)
actions.w3c_actions.pointer_action.pointer_up()
actions.w3c_actions.pointer_action.pointer_down()
actions.w3c_actions.pointer_action.pause(0.1)
actions.w3c_actions.pointer_action.pointer_up()
actions.perform()
```
However, it causes the effect of two finger tap instead of single finger double tap.
I also experimented with Adding slight pauses but it gives results similar to two finger pinch gesture
I tried using `mobile: doubleTap`, but the "y" coordinates of the actual tap does not match with passed coordinates.

The code below works, but I have no idea why:

```
actions.w3c_actions.pointer_action.move_to_location(x, y)
actions.w3c_actions.pointer_action.pointer_down()
actions.w3c_actions.pointer_action.pause(0.1)
actions.w3c_actions.pointer_action.release()
actions.w3c_actions.pointer_action.pause(0.1)
actions.perform()

```
## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.2 as well as v2.0.0-beta.25 (REV 3fea5493a431ac64470d4230d4b51438cf213bd1)
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: MacOS
* Node.js version (unless using Appium.app|exe): v16.13.0
* Npm or Yarn package manager: yarn 1.22.17
* Mobile platform/version under test: iOS 15.0
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

**Comment by mykola-mokhnach** [comment]
Try the following sequence:

> move
> pause 0.05s
> up
> pause 0.2s
> down
> pause 0.05s
> up

**Comment by tarun550** [comment]
> Try the following sequence:
> 
> * move
> * pause 0.05s
> * up
> * pause 0.2s
> * down
> * pause 0.05s
> * up

So are you suggesting "move" is also causing a "down" internally? Why is happening?

**Comment by mykola-mokhnach** [comment]
> So are you suggesting "move" is also causing a "down" internally? Why is this happening?

Because it is not possible to exactly map W3C actions to iOS-specific API calls. Read  https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios/actions.md for more details. 

Btw, I've [simplified](https://github.com/appium/WebDriverAgent/pull/572/files) the implementation of `pause` action. Please check out the PR and see if it works for the chain above.

**Comment by tarun550** [comment]
My device is in landscape mode running iOS 15.0. I have passed the id of the element that I wanted to perform tap on. The x and y parameters were set as centre value of the view. Have experimented with x:0 and y:0 as well, but the tapped location is way off.

Same issue with `mobile: tap` as well.

**Comment by mykola-mokhnach** [comment]
Landscape mode could be the issue. I've already seen several issues that screen coordinates are not calculated properly for non-portrait orientations by XCTest. The worst thing is that it might work differently for different iOS SDKs

**Comment by mykola-mokhnach** [comment]
Closed because of no response
