### ISSUE TITLE
Bundle Appium 2 together with driver at one location

### ISSUE THREAD

**Issue by devwdwgui** [appium/appium#16580]
## The problem

I would like to bundle Appium 2 with the driver [uiautomator2](https://github.com/appium/appium-uiautomator2-driver). I would like to have one location where Appium 2 as well as the driver is located for easier deployment on a target machine.

## Environment

* Appium version (or git revision) that exhibits the issue: 2.0.0-beta.25
* Desktop OS/version used to run Appium: Windows 20H2
* Node.js version (unless using Appium.app|exe): v16.14.0
* Npm or Yarn package manager: Yarn  v1.22.5
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Both
* Appium CLI or Appium.app|exe: -

## Details

When I use

```
yarn add appium@next 
yarn appium driver install uiautomator2
```

the driver is located at `%UserProfile\.appium`. Then I would end up with two locations to set up on a target machine

- Location of Appium 2 e.g. in C:\Program Files\Appium
- Location of "uiautomator2" in %UserProfile%\.appium

But this is not what I intend. I would like the driver to reside directly at the Appium installation itself so that I can bundle it later and do not have to place files in the user's home directory, just like Appium 1 did.

I tried the following approaches to solve this problem myself, however with no luck:

### Setting the driver repository location

[AppiumPro](https://appiumpro.com/editions/122-installing-appium-20-and-the-driver-and-plugins-cli) states that I can use a command `appium -ah /path/to/custom/appium/home driver install xcuitest`. I used that as an example and entered `yarn appium -ah ./uiautomator2 driver install uiautomator2` Then I received:

```
usage: index.js [-h] [-v] {server,driver,plugin} ...

index.js: error: unrecognized arguments: ./uiautomator2 driver install uiautomator2

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Getting the help of the install command using `yarn appium driver install --help` it seems that there is no such option, as I get:

```
usage: index.js driver install [-h] [--json] [--source {git,github,local,npm}] [--package PACKAGENAME] driver

positional arguments:
  driver                find_by_image

optional arguments:
  -h, --help            show this help message and exit
  --json                Use JSON for output format
  --source {git,github,local,npm}
                        Where to look for the driver if it is not one of Appium's verified drivers. Possible values:
                        git, github, local, npm
  --package PACKAGENAME
                        If installing from Git or GitHub, the package name, as defined in the plugin's package.json
                        file in the "name" field, cannot be determined automatically, and should be reported here,
                        otherwise the install will probably fail.
```

### Installation as NPM-package:

Then I tried to add it as a local dependency using `yarn add appium-uiautomator2-driver@2.0.3`. That command completed successfully and then I started the server using `yarn appium server`. I got the following output

```
Starting Appium server...
[Appium] Welcome to Appium v2.0.0-beta.25
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[Appium] No drivers have been installed. Use the "appium driver" command to install the one(s) you want to use.
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
```

As it can be seen, no driver shows up when I start the Appium server. Maybe I have to write a configuration for the Appium server to pick that up?

I would be grateful if someone could please point me in the right direction how to bundle Appium together with the "uiautomator2" driver in one location.

**Comment by devwdwgui** [comment]
Thank you for your quick answer, I pretty sure there is hard work going on to make the new version a good one! I just checked, it's not a yarn or npm problem. Here's the same problem description as above using npm:


## The problem

I would like to bundle Appium 2 with the driver [uiautomator2](https://github.com/appium/appium-uiautomator2-driver). I would like to have one location where Appium 2 as well as the driver is located for easier deployment on a target machine.

## Environment

* Appium version (or git revision) that exhibits the issue: 2.0.0-beta.25
* Desktop OS/version used to run Appium: Windows 20H2
* Node.js version (unless using Appium.app|exe): v16.14.0
* Npm or Yarn package manager: Yarn  v1.22.5
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Both
* Appium CLI or Appium.app|exe: -

## Details

When I use

```
npm install -g appium@next
appium driver install uiautomator2
```

the driver is located at `%UserProfile\.appium`. Then I would end up with two locations to set up on a target machine

- Location of Appium 2 e.g. in C:\Program Files\Appium
- Location of "uiautomator2" in %UserProfile%\.appium

But this is not what I intend. I would like the driver to reside directly at the Appium installation itself so that I can bundle it later and do not have to place files in the user's home directory, just like Appium 1 did.

I tried the following approaches to solve this problem myself, however with no luck:

### Setting the driver repository location

[AppiumPro](https://appiumpro.com/editions/122-installing-appium-20-and-the-driver-and-plugins-cli) states that I can use a command `appium -ah /path/to/custom/appium/home driver install xcuitest`. I used that as an example and entered `appium -ah ./uiautomator2 driver install uiautomator2` Then I received:

```
usage: index.js [-h] [-v] {server,driver,plugin} ...

index.js: error: unrecognized arguments: ./uiautomator2 driver install uiautomator2

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Getting the help of the install command using `appium driver install --help` it seems that there is no such option, as I get:

```
usage: index.js driver install [-h] [--json] [--source {git,github,local,npm}] [--package PACKAGENAME] driver

positional arguments:
  driver                find_by_image

optional arguments:
  -h, --help            show this help message and exit
  --json                Use JSON for output format
  --source {git,github,local,npm}
                        Where to look for the driver if it is not one of Appium's verified drivers. Possible values:
                        git, github, local, npm
  --package PACKAGENAME
                        If installing from Git or GitHub, the package name, as defined in the plugin's package.json
                        file in the "name" field, cannot be determined automatically, and should be reported here,
                        otherwise the install will probably fail.
```

### Installation as NPM-package:

Then I tried to add it as a local dependency using `npm install appium-uiautomator2-driver@2.0.3`. That command completed successfully and then I started the server using `appium server`. I got the following output

```
Starting Appium server...
[Appium] Welcome to Appium v2.0.0-beta.25
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[Appium] No drivers have been installed. Use the "appium driver" command to install the one(s) you want to use.
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
```

As it can be seen, no driver shows up when I start the Appium server. Maybe I have to write a configuration for the Appium server to pick that up?


I would be grateful if someone could please point me in the right direction how to bundle Appium together with the "uiautomator2" driver in one location.

**Comment by StephanB75** [comment]
You can set a eviroment variable "APPIUM_HOME" which is used when doing a npm install.
This can be a variable path for each machine when you add this enviroment variable within you CI scripts.

I have bundled the installation of the drivers within the package.json (Thanks to jipps for this tip)


`{
  "repository": {
    "type": "",
    "url": ""
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "appium": "2.0.0-beta.25"
  },
  "scripts": {
    "postinstall": "npx appium plugin uninstall images || true && npx appium driver uninstall uiautomator2 || true && npx appium driver install uiautomator2 || true && npx appium plugin install images || true"
  },
  "name": "appium_installation",
  "version": "1.0.0"
}
`
I have added a uninstall infront of the driver installation to be sure that no old drivers are on the machine. Maybe this is not necessary for you. 
I hope i have understood your problem correctly.

**Comment by StephanB75** [comment]
i think you can only use a different APPIUM HOME when you are able to start the server with this alternativ APPIUM_HOME path. And as i know the "--appium-home" start parameter for the server was removed in [favor for the enviroment variable](https://github.com/appium/appium/discussions/16103#discussioncomment-1649803). Otherwise appium will allways use the default location. Which as it looks will be the UserProfile folder.

So is it a solution for you to install appium itself in the userfolder ?
(i only know the npm stuff for mac, maybe its the same for Windows)
navigate to the folder where appium shoud be installed and use "npm install appium@next" (without -g)
than (on mac at least) appium is not installed globally.

**Comment by devwdwgui** [comment]
Thank you for your answer, so I guess that this environment variable "APPIUM_HOME" is the only way to tell Appium where it's drivers and plugins are. It's really unfortunate that there is no way of bundling Appium and it's drivers just by putting it in one folder only.

What is the option of being able to install a driver using an NPM package like `npm install appium-uiautomator2-driver@2.0.3` good for then? I've seen a [discussion ](https://github.com/appium/appium/discussions/16149) going on around that as well. Because when I start the server afterwards, the driver is still not included - for that the above mechanism with the UserProfile folder or the environment variable has to be followed. What is the purpose of being able to install the driver via an NPM package, I wonder?

**Comment by jlipps** [comment]
> It's really unfortunate that there is no way of bundling Appium and it's drivers just by putting it in one folder only.

There is now a way thanks to @boneskull. Just npm install them both into the same directory. At least, once the next Appium 2 beta is released.

> What I am looking for is a way to deliver Appium 2 and "uiautomator2" kind of pre-packaged

You should probably create your own custom node.js project that gets bundled with https://github.com/vercel/pkg. It can include both Appium and the uiautomator2 driver as dependencies and expose its own entrypoint that calls Appium's main function. I don't know how pkg handles internal node modules paths and if it might break anything that Appium is trying to do, but that's what I'd explore.

**Comment by devwdwgui** [comment]
Oh, it's good to hear that this will be possible in the future. Thank you for that. The approach with an own custom NodeJS project is exactly what I have in mind. I already gave it a try and packed Appium itself into one exe file. Starting up the plain server seems to be working without any errors. It's just that no driver or plugin is found yet. But that should be resolved if the correspondig NPM package can be included with an NPM command.

**Comment by jlipps** [comment]
The feature is released as of the current Appium 2 beta (26).

**Comment by jlipps** [comment]
I'm going to close this issue since everything Appium can do to support this use case is already done. The rest will be up to you!

**Comment by devwdwgui** [comment]
Alright, thank you for the update. I followed your suggestion

> You should probably create your own custom node.js project that gets bundled with https://github.com/vercel/pkg. It can include both Appium and the uiautomator2 driver as dependencies and expose its own entrypoint that calls Appium's main function. 


So I created a new project using the following commands:

```
npm init
npm install appium@2.0.0-beta.27
npm install appium-android-driver
```

This worked fine. I then added the following line to the scripts of `package.json`:

`"start": "node.exe src/startapp.js",`

I ended up with the package.json:

```
{
  "name": "test",
  "version": "0.0.1",
  "description": "test",
  "main": "src\\index.js",
  "scripts": {
    "start": "node.exe src/startapp.js",
    "test": "test"
  },
  "author": "testauthor",
  "license": "ISC",
  "dependencies": {
    "appium": "^2.0.0-beta.27",
    "appium-android-driver": "^5.0.8",
    "pkg": "^5.5.2"
  }
}
```

The file `src\startapp.js` contains:

```
const appium = require("appium");
let appiumserver = undefined;

let vars = {
  "basePath": "/wd/hub"
};

async function main() {
  await appium.init(vars);
  appiumserver = await appium.main(vars);  
}

main().catch(console.log);
```


When I enter `yarn start` in the console no driver is being loaded yet.

```
yarn run v1.22.5
$ node.exe src/startapp.js
[debug] [Appium] Reading M:\Test\appiumservertest\node_modules\.cache\appium\extensions.yaml...
[debug] [Appium] Creating hash file directory: M:\Test\appiumservertest\\node_modules\.cache\appium
[Appium] Welcome to Appium v2.0.0-beta.27
[Appium] Non-default server args:
[Appium] {
[Appium]   basePath: '/wd/hub'
[Appium] }
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[Appium] No drivers have been installed in M:\Entwicklung\appiumservertest\. Use the "appium driver" command to install the one(s) you want to use.
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
```

Any ideas what to change in order to load the driver?
