### ISSUE TITLE
New setup M1 - Server seems to shutdown unexpectedly

### ISSUE THREAD

**Issue by CarlosNano** [appium/appium#16592]
## The problem

Server seems to shutdown unexpectedly
 
## Environment

* Appium version (or git revision) that exhibits the issue:  1.22.2
* Desktop OS/version used to run Appium: 12.2.1
* Node.js version (unless using Appium.app|exe): v16.14.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Mobile Android 10
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: Appium App

## Details

I'm trying to run my tests in a new machin an M1. They used to work fine in my previous machin. 

I've installed Appium Server and Appium for Mac and set up Android Path and JDK path

When I run my test the server will close unexpectedly

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

https://gist.github.com/CarlosNano/aaabd3ad0ae2b028cdc95975254299de

Capabilities set up: 
```
            caps.setCapability("appium:chromeOptions", ImmutableMap.of("w3c", false));
            caps.setCapability("platformName", "Android");
            caps.setCapability("platformVersion", "10");
            caps.setCapability("deviceName", "FA6C50302991");
            caps.setCapability("automationName", "UiAutomator2");
```

**Comment by mykola-mokhnach** [comment]
> [info] [35m[Appium][39m Appium v1.22.2 creating new MacDriver (v1.10.2) session

I'm not quite sure if the attached log matches the capabilities above. According to that log Appium tried to start MacDriver, which is deprecated, and expectedly failed.

**Comment by CarlosNano** [comment]
Hi @mykola-mokhnach, thanks for the reply

What exactly do you mean with:
> MacDriver, which is deprecated

It's the app deprecated? my particular version deprecated?

I've installed it because Appium Server app was complaining about it could not find MacDriver.

**Comment by mykola-mokhnach** [comment]
I mean this driver is deprecated and is not maintained. Consider using https://github.com/appium/appium-mac2-driver instead

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by CarlosNano** [comment]
@mykola-mokhnach thank

Sorry I'm still a bit confused:

This is my version of appium:
```
appium --version                                                                                                                                                                     
1.22.2
```

The Appium server says: 
<img width="309" alt="image" src="https://user-images.githubusercontent.com/72921935/159687777-9756256e-8f3e-43cb-9d38-3840421dd008.png">
 
But in the appium mac2 driver documentation ( https://github.com/appium/appium-mac2-driver#requirements ) says:
`Since the version 1.0.0 this driver is only compatible with Appium 2`

**Comment by mykola-mokhnach** [comment]
Server version and driver version are two different disconnected things. The main difference between Appium1 and Appium2 is the latter can manage each driver independently while Appium1 has them all bundled into the same package. Read https://appiumpro.com/editions/122-installing-appium-20-and-the-driver-and-plugins-cli for more details

**Comment by CarlosNano** [comment]
Sorry but I still don't understand it. 

The following mean that my version of appium is not Appium 2, isn't it?
```
appium --version                                                                                                                                                                     
1.22.2
```

So I won't be able to use it with https://github.com/appium/appium-mac2-driver ?

> Server version and driver version are two different disconnected things.

Or `appium --version` is not the version of appium, is something else?

> The main difference between Appium1 and Appium2 is the latter can manage each driver independently while Appium1 has them all bundled into the same package. Read https://appiumpro.com/editions/122-installing-appium-20-and-the-driver-and-plugins-cli for more details

Also for what I read in that link you said if I have Appium 1 installed I don't need to install any plugin?

**Comment by mykola-mokhnach** [comment]
This means you will be locked to the driver version below 1.0.0 if you want to use Appium1 and it will never be updated
