### ISSUE TITLE
Socket hang up with new iOS 15.4 trying to get screenshots

### ISSUE THREAD

**Issue by Alessandro-Centro** [appium/appium#16604]
## The problem

Once updated iOS from 15.2 to 15.4 on real devices, the get screenshot function doesn't work anymore.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.2
* Last Appium version that did not exhibit the issue (if applicable): 1.22.2 (with iOS 15.2)
* Desktop OS/version used to run Appium: macOS Monterey 12.3
* Node.js version (unless using Appium.app|exe): 17.7.2
* Npm or Yarn package manager: npm 8.5.2
* Mobile platform/version under test: iPhone 11/iPhone Xr iOS 15.4
* Real device or emulator/simulator: Real devices
* Appium CLI or Appium.app|exe: Appium CLI

## Details

The problem started once update iOS from 15.2 to 15.4.
Updated Xcode too to 13.3 to handle with new iOS.

While trying to get screenshot at the end of a test, the Appium server throws an exception, the message:
`An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up`

We experienced similar issues with iOS 15.1 and Appium 1.22 (desktop), solution was using Appium CLI 1.22.2, but now it the last stable version.

We found some related issues from the past, maybe it is the same problem, a couple of they are related to this [15262](https://github.com/appium/appium/issues/15262)

## Link to Appium logs

[appium.log](https://github.com/appium/appium/files/8305765/appium.log)

**Comment by mykola-mokhnach** [comment]
Please provide the device log

**Comment by KazuCocoa** [comment]
I tested. Xcode 13.3 seems to have an issue to get a screenshot. Xcode log said it got https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Utilities/FBScreenshot.m#L193 timeout error here. I guess something changed or wrong in https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Utilities/FBScreenshot.m#L168

Let me check with vanilla XCTest.

Btw, Xcode 13.0 - 13.2 had no issue for an iOS 15.4 real device, so you could use the version as a workaround for now.

**Comment by KazuCocoa** [comment]
just a note:
on an iOS real device, https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Utilities/FBImageIOScaler.m#L124 raised an exception. `image` had NSData, but potentially the format was wrong?
```
(lldb) po [UIImage imageWithData:image]
error: Execution was interrupted, reason: EXC_BREAKPOINT (code=1, subcode=0x18067ffd8).
The process has been returned to the state before expression evaluation.
```

**Comment by miroslavkovac** [comment]
On Xcode 13.3 in `_XCT_requestScreenshot:withReply:` the completion block is never called and it just hangs, probably causing some further threading issues. Also, Xcode 13.3 doesn't seem to be an issue, the issues is the runtime iOS 15.4, because iOS 15.2 works well with Xcode 13.3.

**Comment by KazuCocoa** [comment]
Then, maybe it is the combination of iOS 15.4 and Xcode 13.3 thing. (as https://github.com/appium/appium/issues/16604#issuecomment-1072959345 , Xcode 13.0 and 13.2 worked with iOS 15.4)

Could you try https://github.com/appium/WebDriverAgent/pull/573 out on your local?

I'll test more various combinations this weekend, but at least it worked in some combinations as a quick test on my local.

**Comment by miroslavkovac** [comment]
Yep, making screenID `long long` solves the issue!

**Comment by kuhivchak** [comment]
Had the same issue, changed to `long long` - works fine, checked by 1 test.

**Comment by KazuCocoa** [comment]
Thank you for your help! Then, my local test should be enough to test the fix.
I've finalized my change as https://github.com/appium/WebDriverAgent/pull/573

**Comment by KazuCocoa** [comment]
Appium 1.22.3 includes this change.

**Comment by ThorNtHu** [comment]
Thanks for your prompt, this problem disappears after updating WDA.

**Comment by raj-2352** [comment]
> Appium 1.22.3 includes this change.

Does exposed rest api (session/{sessionId}/screenshot) also have this change?
