### ISSUE TITLE
SessionNotCreatedException

### ISSUE THREAD

**Issue by ChristianErdtmann** [appium/appium#16614]
## The problem

Appium worked fine for me since days i started programming with it.
But now, and i dont know why, iam not longar able to to start my app.
The app crashed sometimes because of errors in my test-automation-code.

I get now alltimes the error:
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 404. Message: The session identified by e2e0ed9c-50cd-4578-93d7-c637d3455a33 is not known
Build info: version: '4.1.2', revision: '9a5a329c5a'
System info: host: 'DESKTOP-400F5AL', ip: '192.168.56.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.2'
Driver info: io.appium.java_client.android.AndroidDriver

I dont know whats the Problem.

The app start alltimes for 1-2 secounds and after that the app crash and close.

Any idea how to solve this?

**Comment by ChristianErdtmann** [comment]
OK the error is solved. Seems like a problem with the Emulator. After Cold boot the emulator it works now again.

**Comment by jlipps** [comment]
Yes, sometimes emulators just go bad and need to be cold booted. Alas!
