### ISSUE TITLE
Cannot register IOS developer account to add new phone

### ISSUE THREAD

**Issue by charlbury** [appium/appium#16625]
## The problem

Registering a paid IOS developer account in Appium Studio returns an error message. I am registering with an Apple ID that has a paid Apple developer account and I am using an App Specific Password when registering. I have tried this on 3 different machines, 2 in the UK and 1 in USA.

```
Failed to add developer account with appleid: apple@XXXXXXXX.com and teamid: XXXXXXXXX reason: Bad response from server.
200: OK
Server says: Authentication Error. Xcode 7.3 or later required to continue developing with your Apple ID. (3019)
Please make sure you are not using a free account, as it is not supported.
```

<img width="1062" alt="Screenshot 2022-03-17 at 11 23 16" src="https://user-images.githubusercontent.com/3824684/159243147-6ceb7739-ec42-44da-9a31-ced619dfbeec.png">

## Environment

* Appium version (or git revision) that exhibits the issue: ***22.1.8625***
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: ***Windows 10***
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/charlbury/62eb07d1697a8f2f5fa0a74cbe509168

**Comment by mykola-mokhnach** [comment]
Appium Studio is a third party, which has nothing to do with the current OSS Appium project. Consider contacting their customer support

**Comment by charlbury** [comment]
Thanks for the info. Will chase them.
