### ISSUE TITLE
applesimutils can't be found when run appium test in IntelliJ idea after upgrade mac os from big sur to Monterey

### ISSUE THREAD

**Issue by Rosepotato** [appium/appium#16620]
## The problem
applesimutils is actually installed and configured in PATH. It can be found when run appium-doctor.  And appium runs correctly when launch test by mvn clean test command line in terminal.  It's really strange that applesimutils  can't be found when run appium test in IntelliJ idea after upgrade mac os from big sur to Monterey .

The following is the test log:

[DevCon Factory] Releasing connections for 1A712FD0-BBDE-499C-8851-2AF6C69482C1 device on any port number
[DevCon Factory] No cached connections have been found
[XCUITest] Cleaning test logs in '/Users/spond/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu/Logs' folder
[HTTP] <-- POST /wd/hub/session 500 5111 ms - 851
[HTTP] 
11:23:58,552  INFO Log:52 - Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: applesimutils binary has not been found in your PATH. Please install it ('brew tap wix/brew && brew install wix/brew/applesimutils') to be able to change application permissions
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Slave-mini-trash.local', ip: '192.168.0.151', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '15.0.1'
Driver info: driver.version: IOSDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: applesimutils binary has not been found in your PATH. Please install it ('brew tap wix/brew && brew install wix/brew/applesimutils') to be able to change application permissions
    at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Slave-mini-trash.local', ip: '192.168.0.151', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '15.0.1'
Driver info: driver.version: IOSDriver

## Environment

* Appium version 1.22.3, MAC OS 12.3 Monterey, xcode 13.3(ios Simulator 15.4)
* Last xcode version that did not exhibit the issue 12.5 with appium version 1.21.0 and the MAC OS big sur:

**Comment by mykola-mokhnach** [comment]
Check https://github.com/appium/java-client/blob/master/docs/environment.md

**Comment by mykola-mokhnach** [comment]
Closed because of no response
