### ISSUE TITLE
IOS click request is correct but in fact another element is being clicked

### ISSUE THREAD

**Issue by Idoser99** [appium/appium#16628]
## The problem
I am experiencing a weird issue which I already detailed on appium discuss so I will provide a link below.

I know appium discuss is mainly for support, my problem happens on the same page each time so I thought it might be my mistake. The problem happens occasionally, and I start to think that it might be XCUITest driver internal issue because the code is the same and works well. Additionally, the same code is being used by many pages; for all, I never had the same problem.

A similar problem happened to me while testing on a different page(test is not in use so it is not a problem, currently).
It happened occasionally as well and on the same page each time - the click request was with the correct elementId but in fact another element was clicked.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.2
* Last Appium version that did not exhibit the issue (if applicable): 1.22.0
* Desktop OS/version used to run Appium: MacOS(M1) Monterey 12.0.1
* Node.js version (unless using Appium.app|exe): v16.14.0
* Npm or Yarn package manager: 8.3.1
* Mobile platform/version under test: 15.2
* Real device or emulator/simulator: Simulator

## Details

please refer to appium discuss: https://discuss.appium.io/t/ios-driver-clicks-the-wrong-element/35923

## Link to Appium logs

in the link above

## Code To Reproduce Issue [ Good To Have ]

in the link above

**Comment by mykola-mokhnach** [comment]
Try to click by coordinates as a possible workaround

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
