### ISSUE TITLE
Get different size from different orientation on iPad

### ISSUE THREAD

**Issue by focalism** [appium/appium#16635]
## The problem

The `/window/size` api return different size  at home page，when device in Landscape and portrait， the result is:

portrait: (height: 1080, width: 810)
![image](https://user-images.githubusercontent.com/10719644/159663366-251e9e4c-8e0b-416f-9dc3-8d9923aa3fe2.png)

Landscape: (height: 1080, width: 1080)
![image](https://user-images.githubusercontent.com/10719644/159663441-98d5db82-c4a8-46a6-8d18-a74018397a86.png)

I think the size should be (height: 810, width: 1080)，but the height is 1080.

## Environment

* Device: iPad 2019
* WebDriveragent: latest

**Comment by mykola-mokhnach** [comment]
Please provide the full server log. Also try it with the most recent driver release, which is available in appium2

**Comment by mykola-mokhnach** [comment]
Closed because of no response
