### ISSUE TITLE
Sessions are always overridden, regardless of --session-override flag

### ISSUE THREAD

**Issue by Micha-Mircea** [appium/appium#16640]
Hello everyone,

we are currently very confused as to what the purpose of the `--session-override` flag is. When we request two sessions consecutively (with identical, minimal capabilities), the Appium server always overrides the existing session and starts the new one.

Is this the intended behavior? We would expect that, if a session is already running on a device, we would get back a message that no session could be created. Especially considering the fact, that session-override is false by default. However as the title says, the session is overridden no matter the value of the flag.

Sadly the documentation regarding the session-override flag is very scarce. Are we misinterpreting the meaning of the flag? Is there no way to prevent Appium from starting and overriding a new session, if a session is already running on a device?

We are using Appium 2.0.0-beta.25 and sending request via Postman.

King regards.

**Comment by mykola-mokhnach** [comment]
Could you please provide the full server log where the issue shows itself?

**Comment by mykola-mokhnach** [comment]
Closed because of no response
