### ISSUE TITLE
Does appium support Hybrid mac apps?

### ISSUE THREAD

**Issue by CarlosNano** [appium/appium#16657]
## The problem

I'm trying to test a hybrid mac app, which is built with ionic and uses Chromium in the background.

I was trying to use the `appium-mac2-driver`, but it doesn't seem to work and after a chat in that repo, it seems it's not supported ( https://github.com/appium/appium-mac2-driver/issues/127 )

I could not find anything in the documentation related with desktop hybrid apps, only for mobile. 

Are hybrid mac apps supported by appium, if so which driver should I use? 

## Environment

Appium version (or git revision) that exhibits the issue: 1.22.2
Desktop OS/version used to run Appium: 12.2.1
Node.js version (unless using Appium.app|exe): v16.14.0
Npm or Yarn package manager: npm
Mobile platform/version under test: 
Real device or emulator/simulator: Real
Appium CLI or Appium.app|exe: Appium App

**Comment by mykola-mokhnach** [comment]
Mac2 driver only supports automation of native macOS apps as it is based on [XCTest](https://developer.apple.com/documentation/xctest) framework.

Kindly use Appium forum to ask questions.
