### ISSUE TITLE
element.GetAttribute returns no value in Android 12

### ISSUE THREAD

**Issue by CarolRalph** [appium/appium#16680]
## The problem

We are trying to use element.GetAttribute to return the value of an object property but in Android 12 it returns null. This worked in Android 11.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2
* Last Appium version that did not exhibit the issue (if applicable): 1.20.2
* Desktop OS/version used to run Appium: Linux (Contact SauceLabs for version)
* Node.js version (unless using Appium.app|exe): Contacting SauceLabs to get this information
* Npm or Yarn package manager: Contacting SauceLabs to get this information
* Mobile platform/version under test: Android 12 (This works with Android 11)
* Real device or emulator/simulator: Both (this example uses emulator) 
* Appium CLI or Appium.app|exe: Contacting SauceLabs to get this information

## Details

We run tests on our Mobile App using SauceLabs. We use element.GetAttribute to get a value from an object and store it as a variable. After upgrading to Android 12 the tests began to fail because the property value is no longer returned.   
In this example we load our app then enter the word "mouse" in the username field. The next step should simply use the element.GetAttribute method to return the value "mouse".

## Link to Appium logs

[Android 12](https://gist.github.com/CarolRalph/ebb3abd76f87a44972301faafab3f59d)
[Android 11](https://gist.github.com/CarolRalph/6999f1dd430b868e738af1a78f24600f)

## Code To Reproduce Issue [ Good To Have ]

[SampleCode_ToRunOnSauceLabs_C#](https://gist.github.com/CarolRalph/aaec3712c760ed80d561e7a06ebf4c4d)

**Comment by mykola-mokhnach** [comment]
The attribute value is [retrieved](https://github.com/appium/appium-uiautomator2-server/blob/700eefebb75f8c7e2d3d1feac3b6d0d13e8b339d/app/src/main/java/io/appium/uiautomator2/model/UiObject2Element.java#L75) by Google's UiAutomator framework itself. Consider reporting the issue to the original maintainers.

**Comment by mykola-mokhnach** [comment]
Also it always makes sense to try the most recent driver version. 1.20 one is pretty old

**Comment by CarolRalph** [comment]
@mykola-mokhnach Thank you for the information about the UIAutomator. I am submitting an issue with Google. 
We did run the test using the Appium Driver 1.22 version with the same result on Android 12. (Android 11 is not supported with the newest driver but we also tried 1.21 on both Android 11 and 12.)
