### ISSUE TITLE
Compilation error on WebDriverAgent.xcodeproj: Xcode 13.3:  'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.

### ISSUE THREAD

**Issue by udaykittu** [appium/appium#16682]
## The problem

Xcode WebDriverAgent.xcodeproj unable to compile webdriver agent project due to below issue

/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgentLib/Categories/XCUIDevice+FBHelpers.m:164:24: 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.

/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgentLib/Categories/XCUIDevice+FBHelpers.m:164:43: 'openURL:' is unavailable: not available on iOS (App Extension)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.3
* Last Appium version that did not exhibit the issue (if applicable): 1.22.2
* Desktop OS/version used to run Appium: Mac OS
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager: npm
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe: CLI
* XCode: 13.3
<img width="1394" alt="Screenshot 2022-03-29 at 7 34 28 AM" src="https://user-images.githubusercontent.com/25000065/160518237-bac5b6ed-4c7a-4fa8-bdcf-2e3cde36c5a4.png">

**Comment by udaykittu** [comment]
@mykola-mokhnach @KazuCocoa Can you please take a look intot it

**Comment by KazuCocoa** [comment]
What version of `version` section in `/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/package.json`?

The line number seems wrong in the appium 1.22.3's one.
https://github.com/appium/WebDriverAgent/blob/v3.17.0/WebDriverAgentLib/Categories/XCUIDevice+FBHelpers.m#L162

**Comment by udaykittu** [comment]
"version": "3.17.0",

**Comment by udaykittu** [comment]
`{
  "name": "appium-webdriveragent",
  "version": "3.17.0",
  "description": "Package bundling WebDriverAgent",
  "main": "build/index.js",
  "scripts": {
    "test": "gulp once",
    "e2e-test": "npm run build && _FORCE_LOGS=1 npx mocha -t 0 -R spec build/test/functional --exit",
    "clean": "rm -rf node_modules && rm -f package-lock.json && npm install",
    "install:dependencies": "gulp install:dependencies",
    "build": "gulp transpile",
    "prepare": "gulp prepublish",
    "prepublishOnly": "npm run bundle",
    "lint": "gulp lint",
    "lint:fix": "gulp eslint --fix",
    "precommit-msg": "echo 'Pre-commit checks...' && exit 0",
    "precommit-test": "gulp lint",
    "bundle": "node ./Scripts/build-webdriveragent.js",
    "fetch-prebuilt-wda": "node ./Scripts/fetch-prebuilt-wda"
  },
  "bin": {
    "appium-wda-bootstrap": "./build/index.js"
  },
  "pre-commit": [
    "precommit-msg",
    "precommit-test"
  ],
  "repository": {
    "type": "git",
    "url": "git+https://github.com/appium/WebDriverAgent.git"
  },
  "keywords": [
    "Appium",
    "iOS",
    "WebDriver",
    "Selenium",
    "WebDriverAgent"
  ],
  "author": "appium",
  "license": "Apache-2.0",
  "bugs": {
    "url": "https://github.com/appium/WebDriverAgent/issues"
  },
  "homepage": "https://github.com/appium/WebDriverAgent#readme",
  "devDependencies": {
    "appium-gulp-plugins": "^5.0.0",
    "appium-test-support": "^1.3.1",
    "appium-xcode": "^3.8.0",
    "chai": "^4.2.0",
    "chai-as-promised": "^7.1.1",
    "eslint-config-appium": "^4.0.1",
    "glob": "^7.1.0",
    "gulp": "^4.0.2",
    "ios-uicatalog": "^3.5.0",
    "mocha": "^9.0.0",
    "pre-commit": "^1.2.2",
    "sinon": "^12.0.0",
    "wd": "^1.11.4"
  },
  "dependencies": {
    "@babel/runtime": "^7.0.0",
    "appium-base-driver": "^7.0.0",
    "appium-ios-simulator": "^3.14.0",
    "appium-support": "^2.46.0",
    "async-lock": "^1.0.0",
    "asyncbox": "^2.5.3",
    "axios": "^0.x",
    "bluebird": "^3.5.5",
    "lodash": "^4.17.11",
    "node-simctl": "^6.0.2",
    "source-map-support": "^0.5.12",
    "teen_process": "^1.14.1"
  },
  "files": [
    "index.js",
    "lib",
    "build/index.js",
    "build/lib",
    "Scripts/build.sh",
    "Scripts/fetch-prebuilt-wda.js",
    "Scripts/build-webdriveragent.js",
    "Cartfile",
    "Cartfile.resolved",
    "Configurations",
    "PrivateHeaders",
    "WebDriverAgent.xcodeproj",
    "WebDriverAgentLib",
    "WebDriverAgentRunner",
    "WebDriverAgentTests",
    "XCTWebDriverAgentLib",
    "WebDriverAgentRunner-Runner.app.zip"
  ]
}
`

**Comment by udaykittu** [comment]
I have manually checked with 3.16.0 version and its working fine. Appium inbuilt has come up with 3.17.0

**Comment by KazuCocoa** [comment]
Thank you. The version seems correct, but did you modify WebDriverAgent code a bit?
Your attached image's L146 and 147 seems blank lines. But the code has only one blank line. https://github.com/appium/WebDriverAgent/blob/v3.17.0/WebDriverAgentLib/Categories/XCUIDevice+FBHelpers.m#L145

<img width="557" alt="Screen Shot 2022-03-28 at 22 21 19" src="https://user-images.githubusercontent.com/5511591/160538913-4900226c-dc31-497b-aec9-f1e954ef5540.png">

Then, could you uninstall appium completely once and rer-install again?

I could not reproduce the error in various Xcode versions on my env, including Xcode 13.3 for now. https://github.com/appium/appium/issues/16604#issuecomment-1074940455 also seems good.

I wonder your environment has specific environment that causes the errorr.

**Comment by KazuCocoa** [comment]
the difference between 3.16.0 and 3.17.0 is https://github.com/appium/WebDriverAgent/pull/573 , which affects only screenshots afaik.

**Comment by udaykittu** [comment]
I will try uninstall and reinstall once again. As of now i have downloaded WebDriverAgent-4.1.6 version and pointing to the data derived folder

Will check and let you know about it

**Comment by mykola-mokhnach** [comment]
Closed because of no updates
