### ISSUE TITLE
Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70 on Xcode 13.2.1 and iOS 15.4

### ISSUE THREAD

**Issue by Thuytien** [appium/appium#16696]
## The problem
I couldn't build testing app after upgrade iOS version on my iPhone 7+ to 15.4

## Environment
* Appium version (or git revision) that exhibits the issue: 1.22.3
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: Mac OS 12.3
* Node.js version (unless using Appium.app|exe): 14.6.0
* Npm or Yarn package manager: npm 7.22.0
* Mobile platform/version under test: iOS 15.4
* Real device or emulator/simulator: iPhone 7 plus
* Appium CLI or Appium.app|exe: Appium.ipa (real device)
* Xcode version: 13.2.1

## Details
<img width="304" alt="Screen Shot 2022-03-30 at 9 41 00 AM" src="https://user-images.githubusercontent.com/6836601/160961232-ea8244ff-a8ae-4024-b896-8d394fddc41b.png">

It showed error that the iOS version and the Xcode version are incompatible so it couldn't run the test. Please help if anyone got the same for iOS 15.4 and Xcode 13.2.1

## Link to Appium logs: 
https://gist.github.com/Thuytien/afbe1c8cec5f417219c1223f6d167e7f

**Comment by mykola-mokhnach** [comment]
> [error] [35m[Xcode][39m 2022-03-31 09:00:22.393 xcodebuild[1249:13476] [MT] iPhoneConnect: Failed to prepare device for development.
> [error] [35m[Xcode][39m Domain: com.apple.dtdevicekit
> [error] [35m[Xcode][39m Code: 806
> [error] [35m[Xcode][39m Recovery Suggestion: This operation can fail if the version of the OS on the device is incompatible with the installed version of Xcode. You may also need to restart your mac and device in order to correctly detect compatibility.

It looks like this error is coming from Xcode SDK itself. I don' think there is much we could do there from Appium side. Consider reporting the issue to Apple.

**Comment by Thuytien** [comment]
Xcode 13.3 will support iOS 15.4. Sorry for posting wrong issue. Thank you.

**Comment by Ashutosh4291** [comment]
Failed to create session. An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70 xcodebuild error message:

Xcode - 13.4  , iOS simulator Version : 15.5 . Appium Version : 1.22.3
