### ISSUE TITLE
UiScrollable.scrollTextIntoView() and other similar methods behave strangely in Android 12

### ISSUE THREAD

**Issue by nick-imvu** [appium/appium#16690]
## The problem

We have a view with a horizontally scrollable list of tabs. We use the `scrollTextIntoView()` method of `UiScrollable` to bring the desired tab into view. For example:

```
driver.find_element(
    AppiumBy.ANDROID_UIAUTOMATOR,
    'new UiScrollable(new UiSelector().scrollable(true).instance(0)).setAsHorizontalList().scrollTextIntoView("Tab Text")')
```

On Android 9/10/11, we see this (good) behavior:
The app scrolls to the left until the start of the list is found. Then, the app scrolls to the right until the desired tab comes into view.

On Android 12, we see this (bad) behavior:
The app scrolls to the left until the start of the list, **but then continues trying to scroll left up to 30 times** (or, i think, until all MaxSearchSwipes are exhausted). Then, the app scrolls to the right until the desired tab comes into view, as expected.

This causes tests to take _much_ more time on Android 12.

We can use `setMaxSearchSwipes()` to reduce the number of unnecessary swipe attempts when scrolling left, but then we also might not have enough swipe attempts when scrolling to the right.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.3
* Last Appium version that did not exhibit the issue (if applicable): unknown
* Desktop OS/version used to run Appium: macOS Big Sur, Windows 10
* Node.js version (unless using Appium.app|exe): 14.17.6
* Npm or Yarn package manager: npm 6.14.15
* Mobile platform/version under test: Android 12 (API 31)
* Real device or emulator/simulator: Both, but mainly Pixel 5 simulator
* Appium CLI or Appium.app|exe: Appium CLI
* Appium-Python-Client: 2.1.4

## Details

We have tried other similar methods such as `scrollDescriptionIntoView()` and `scrollIntoView()`. All exhibit the same behavior on Android 12. Even `scrollToBeginning()` and `scrollToEnd()` have this issue. It seems that these methods cannot properly identify the start/end of a scrollable list in Android 12.

## Link to Appium logs

[Appium logs](https://gist.github.com/nick-imvu/25d92415d54d797c8feafc675774ae73)

## Code To Reproduce Issue [ Good To Have ]

This code uses the ApiDemos-debug.apk app and is based on the python sample code.

The test navigates to "Views" -> "Tabs" -> "5. Scrollable" to open a view with a horizontal tab list.

The test then uses `UiScrollable.scrollTextIntoView()` to bring "Tab 15" into view.
In Android 9/10/11, this step finishes in about 10 seconds. In Android 12, it takes closer to 60 seconds.

```
    def test_uiscrollable_scroll_text_into_view(self, driver):
        import time
        from appium.webdriver.common.appiumby import AppiumBy

        window_size = driver.get_window_size()
        window_width = window_size['width']
        window_height = window_size['height']

        time.sleep(1)

        # Swipe up 3 times to make sure "Views" is visible
        for _ in range(3):
            driver.swipe(window_width * 0.5, window_height * 0.8, window_width * 0.5, window_width * 0.2)

        # Click on "Views"
        views_elem = driver.find_element(AppiumBy.ACCESSIBILITY_ID, 'Views')
        views_elem.click()
        time.sleep(1)

        # Swipe up 3 times to make "Tabs"
        for _ in range(3):
            driver.swipe(window_width * 0.5, window_height * 0.8, window_width * 0.5, window_width * 0.2)

        # Click on "Tabs"
        tabs_elem = driver.find_element(AppiumBy.ACCESSIBILITY_ID, 'Tabs')
        tabs_elem.click()
        time.sleep(1)

        # Click on "5. Scrollable"
        scrollable_elem = driver.find_element(AppiumBy.ACCESSIBILITY_ID, '5. Scrollable')
        scrollable_elem.click()
        time.sleep(1)

        start_time = time.time()
        driver.find_element(
            AppiumBy.ANDROID_UIAUTOMATOR,
            'new UiScrollable(new UiSelector().scrollable(true).instance(0)).setAsHorizontalList().scrollTextIntoView("TAB 15")')
        end_time = time.time()
        execution_time = round(end_time - start_time, 2)

        assert execution_time < 20
        print(f"scrollTextIntoView execution time: {execution_time}s")
```

**Comment by jlipps** [comment]
Given that Appium is literally just converting these calls into the Java code represented by the string you've produced, it seems that this bug should be reported to the Android UiAutomator2 project instead.

**Comment by nick-imvu** [comment]
> Given that Appium is literally just converting these calls into the Java code represented by the string you've produced, it seems that this bug should be reported to the Android UiAutomator2 project instead.

Thank you. I wondered if that might not be the case. I will open a bug there.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
