### ISSUE TITLE
Error running 'spawn': 2022-04-01 08:41:30.958 defaults[24376:17165502] Could not write domain com.apple.keyboard.preferences

### ISSUE THREAD

**Issue by tking16** [appium/appium#16707]
## The problem
My iOS tests keep failing with this strange error. I'm not sure what's causing it but have only started seeing it since upgrading to Appium 2. To fix it I have close down the simulator and open it again. To which it will run the first few Jenkins jobs successfully and then failing with this error again

```
[](https://jenkins.xxx.com/blue/organizations/jenkins/ios-at-tests/detail/ios-at-tests/5288/pipeline#log-2730)[](https://jenkins.xxx.com/blue/organizations/jenkins/ios-at-tests/detail/ios-at-tests/5288/pipeline#log-2731)[](https://jenkins.xxx.com/blue/organizations/jenkins/ios-at-tests/detail/ios-at-tests/5288/pipeline#log-2732)E       Stacktrace:

E       UnknownError: An unknown server-side error occurred while processing the command. Original error: Error running 'spawn': 2022-04-01 08:41:30.958 defaults[24376:17165502] Could not write domain com.apple.keyboard.preferences; exiting

E           at getResponseForW3CError (/Users/jenkins/build-workspace/workspace/ios-at-tests/testing/app-at/node_modules/@appium/base-driver/lib/protocol/errors.js:804:9)

E           at asyncHandler (/Users/jenkins/build-workspace/workspace/ios-at-tests/testing/app-at/node_modules/@appium/base-driver/lib/protocol/protocol.js:381:35)


```
## Environment

Appium v2.0.0-beta.25
Tests run on a Montery Macmini
Xcode 13.2
Simulator only

**Comment by mykola-mokhnach** [comment]
Please provide the full server log

**Comment by tking16** [comment]
Sorry it's kind of hard to grab the appium logs as it's running through Jenkins with Appium in the background. And I haven't been able to reproduce locally. I found an earlier error though so maybe it's something to do with some already running on the server

```
+ _env/bin/py.test tests --html=_reports/report.html --junitxml=_reports/report.xml --reruns 1 --appium_wait_for_condition appium --appium_wait_for_seconds 30 --variables variables/pytest/ios_test_simulator.json --capability deviceName 'iPhone 12 Pro Max' --capability platformVersion 15.2 --capability app /Users/jenkins/build-workspace/workspace/ios-at-tests/testing/app-at/xxx.app --brand xxx -k ''
============================= test session starts ==============================
platform darwin -- Python 3.9.10, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
capabilities: [['deviceName', 'iPhone 12 Pro Max'], ['platformVersion', '15.2'], ['app', '/Users/jenkins/build-workspace/workspace/ios-at-tests/testing/app-at/Smooth.app']]
rootdir: /Users/jenkins/build-workspace/workspace/ios-at-tests/testing/app-at, configfile: pytest.ini
plugins: variables-2.0.0, metadata-2.0.1, rerunfailures-10.2, html-3.1.1
collected 52 items / 9 deselected / 43 selected

tests/guacamole/test_article.py 2022-04-04 21:04:21:941 - [HTTP] Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.
2022-04-04 21:04:21:943 - [Appium] Could not configure Appium server. It's possible that a driver or plugin tried to update the server and failed. Original error: listen EADDRINUSE: address already in use 0.0.0.0:4723
```

**Comment by mykola-mokhnach** [comment]
Unfortunately we cannot help much without detailed logs

**Comment by tking16** [comment]
@mykola-mokhnach Apologies for the delay. I managed to remote into the server and grab the logs. Please let me know if you need more info 
Logs:
https://gist.github.com/tking16/16c8ccff09d54be33b008edc38040257

**Comment by mykola-mokhnach** [comment]
This seems to be a permissions issue. Try again with a new simulator created from scratch. If that still does not work then make sure the current user has write permissions to the corresponding simulator [folder](https://developer.apple.com/forums/thread/65272).

**Comment by tking16** [comment]
Seems to be passing after killing the simulator and restarting the machine. Something usually goes wrong throughout the night and they start failing again the next day. So will see the state of the tests tomorrow and close this if all is well.

**Comment by tking16** [comment]
Looks like things are behaving now without me constantly having to babysit and restart emulators. Thanks for the help!
