### ISSUE TITLE
Unable to connect to remote `adb` server in docker container with chromedriver on MacOS

### ISSUE THREAD

**Issue by mcoder19** [appium/appium#16708]
## The problem

**Briefly describe the issue you are experiencing (or the feature you want to see added to Appium):**
I cannot create a web session with chromedriver from a docker container.

**Tell us what you were trying to do and what happened instead.**
I'm trying to make an `adb` client in a docker container use an `adb` server on the host, on MacOS. 

This works when I'm not using chromedriver (as written in README of [the sample code](https://github.com/mcoder19/sample_code), all tests except [the test using the chromedriver](https://github.com/mcoder19/sample_code/blob/main/test/test_android_create_web_session.py) works). 

## Environment

|               **Variable**            |    **Value**    |
|:-------------------------------------:|-----------------|
| Appium version                        |      1.22.1     |
| Node.js version                       |      v17.5.0    |
| Npm or Yarn package manager           |       npm       |
| Appium CLI or Appium.app              |    Appium CLI   |
| Mobile platform/version under test    |     Android     |
| Real device or emulator/simulator     |    Real device  |
| Desktop OS/version used to run Appium |     MacOS       |
| Chromedriver version                  |       100       |

Additional comments:
- All "variables" refers to the local environment not running in docker. 

### About the docker image 

The dockerfile used ([appium.yml](https://github.com/mcoder19/sample_code/blob/main/appium.yml) in the sample code) is a small wrapper around this docker image: [https://hub.docker.com/r/appium/appium/dockerfile](https://hub.docker.com/r/appium/appium/dockerfile)

These are the values inside the docker environment:

|               **Variable**            |    **Value**    |
|:-------------------------------------:|-----------------|
| Appium version                        |     v1.22.0     |
| Node.js version                       |     v12.22.6    |
| Npm or Yarn package manager           |       npm       |
| Docker Desktop version                | Version 4.0.0 (4.0.0.12) |

## Details

**If necessary, describe the problem you have been experiencing in more detail.**

When I'm using chromedriver I get the following error `unknown error: Failed to run adb command with networking error: net::ERR_ADDRESS_INVALID. Is the adb server running? Extra response: <>`.

I do also get this entry in the appium log: 

```bash
[debug] [Chromedriver] [STDOUT] Only local connections are allowed.` when using capability `showChromedriverLog: True`.
```

**Have you tried to enable remote connections?**
- Yes, I have tried to add capabilities `chromedriverArgs: ["--whitelisted-ips=''"]` and `chromedriverArgs: ['--whitelisted-ips gateway.docker.internal']` which result in this error in the appium log 

```bash
[debug] [Chromedriver] [STDOUT] Only local connections are allowed.
```

- As far as I can see, the log entry above comes from [this part](https://github.com/appium/appium-chromedriver/blob/5c87903ac822f1f2fb659beee05f563794620048/lib/chromedriver.js#L497) in appium-chromedriver which in turn seems to invoke [this part](https://github.com/chromium/chromium/blob/main/chrome/test/chromedriver/server/chromedriver_server.cc#L419) of the chromedriver code throwing the error.

## Link to Appium logs

[Log](https://gist.github.com/mcoder19/9131b0b0ab186fc86babfe9d62d894f0) 

## Code To Reproduce Issue [ Good To Have ]

Here is [a repository containing sample code](https://github.com/mcoder19/sample_code) which contains the issue.
- The sample code also contains some logs:
- The log '[02_create_web_session_log__with_chromedriver_verbose_flag.md](https://github.com/mcoder19/sample_code/blob/main/logs/02_create_web_session_log__with_chromedriver_verbose_flag.md)' is the same log provided in the gist above. It is the case where the `--whitelisted-ips` argument to the chromedriver **is not used**.

- There are two logs where I have provided the `--whitelisted-ips` argument to the chromedriver, these may be of interest and can be seen here:
    - [03_create_web_session_log__with_chromedriver_whitelist_all.md](https://github.com/mcoder19/sample_code/blob/main/logs/03_create_web_session_log__with_chromedriver_whitelist_all.md)
    - [04_create_web_session_log__with_chromedriver_whitelist_host.md](https://github.com/mcoder19/sample_code/blob/main/logs/04_create_web_session_log__with_chromedriver_whitelist_host.md)

Please let me know if more information is needed or if something needs to be elaborated. 

I can also tweak the sample code, e.g. provide a docker compose file if that is easier.

**Comment by jlipps** [comment]
Just briefly looking at the chromedriver CLI flags (`chromedriver -h`), it doesn't look like it has any option to set the ADB server address, only the port. So somehow it seems you'll want to set up a TCP proxy? I haven't tried this but a brief google search turned up [simpleproxy](http://manpages.ubuntu.com/manpages/trusty/man1/simpleproxy.1.html) for ubuntu. So I imagine you could just turn on the proxy in your CI script, then don't bother about using `remoteAdbHost` and run everything through the proxy. From Appium's perspective then ADB will be on the local network.

**Comment by KazuCocoa** [comment]
Yea, it seems like [adb in chromedevtools](https://source.chromium.org/chromium/chromium/src/+/main:chrome/test/chromedriver/chrome/adb_impl.cc;l=333;drc=7fb345a0da63049b102e1c0bcdc8d7831110e324;bpv=1;bpt=1?q=%22Is%20the%20adb%20server%20running%22%20chrome%20driver&ss=chromium%2Fchromium%2Fsrc) has portforward implementation, but not remote adb server stuff.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by wkarasawaw** [comment]
Is a solution provided for this problem?
I am facing the same problem.
