### ISSUE TITLE
Remoteadbhost not available

### ISSUE THREAD

**Issue by shenwj** [appium/appium#16709]
ADB is deployed on a computer. I have configured a's remoteadbhost. I can't find Android_home when I start appium;
remoteadbhost；
How is remoteadbhost used？
  thranks

**Comment by shenwj** [comment]
this is my capabilitys
{
  "appPackage": "com.oxbix.spanlogistics",
  "appActivity": "com.kye.express.business.main.MainActivit",
  "platformName": "android",
  "version": "8",
  "autoLaunch": false,
  "udid": "53764178",
  "noReset": true,
  "automationName": "uiautomator2",
  "sessionOverride": true,
  "remoteAdbHost": "10.32.76.7",
  "adbPort": "5037"
}

**Comment by mykola-mokhnach** [comment]
Please provide a proper issue description along with server logs

**Comment by mykola-mokhnach** [comment]
Closed because of no response
