### ISSUE TITLE
Original error: Cannot verify the signature of 'appium/appium-1.22.0/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.24.0.apk'

### ISSUE THREAD

**Issue by rajeevmlt** [appium/appium#16712]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:
1.22.0
* Last Appium version that did not exhibit the issue (if applicable):
1.22.0
* Desktop OS/version used to run Appium:
Ubuntu Linux
* Node.js version (unless using Appium.app|exe):
v12.22.10
* Npm or Yarn package manager:
6.14.16
* Mobile platform/version under test:
Android-11 , Google Pixel
* Real device or emulator/simulator:
Emulator
* Appium CLI or Appium.app|exe:
Appium CLI
## Details
While running the selenium test, getting this error
Internal Server error 500

"message":"An unknown server-side error occurred while processing the command. Original error: Cannot verify the signature of '/root/lambda/shared-tools/volume/appium/appium-1.22.0/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.24.0.apk'. Original error: Could not find 'apksigner.jar' in [\"/root/lambda/shared-tools/android-sdk/platform-tools/apksigner.jar\",\"/root/lambda/shared-tools/android-sdk/emulator/apksigner.jar\",\"/root/lambda/shared-tools/android-sdk/cmdline-tools/latest/bin/apksigner.jar\",\"/root/lambda/shared-tools/android-sdk/tools/apksigner.jar\",\"/root/lambda/shared-tools/android-sdk/tools/bin/apksigner.jar\",\"/root/lambda/shared-tools/android-sdk/apksigner.jar\"]. Do you have Android Build Tools installed at '/root/lambda/shared-tools/android-sdk'?"}}

## Code To Reproduce Issue [ Good To Have ]
import time
from selenium import webdriver
#from appium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.common.keys import Keys
import urllib3
import sys
import threading
import json
from selenium.webdriver import ActionChains
import os
import datetime
urllib3.disable_warnings()
desired_cap = {
   #"autoGrantPermissions": True,
   "platformName" : "Android",
		"deviceName" : "Google Pixel 3",
		"platformVersion" : "11",
		"browserName" : "Chrome",
		#"version" : "96",
    "build": "Build-Android-Testing",
    "appiumVersion": "1.22.0",
    "name": "Test name",
    "video": True,
    "network": False,
    "visual": True,
    "console": True,
    "tunnel": True,
    "fixedIP": "<Server IP>",
    "showXcodeLog":True,
    "network.full.har": False,
    "emulator_simulator": True
}
options = webdriver.FirefoxOptions()
options.set_preference("media.eme.enabled",True)
options.set_preference("media.gmp-manager.updateEnabled", True)

**Comment by mykola-mokhnach** [comment]
The error seems valid to me. Android build tools are either not installed or not available to Appium.

**Comment by rajeevmlt** [comment]
Hi Mykola
We have used same apksigner.jar to create virtual emulator devices for Android 7, 8, 8.1, 9,10 and all seems working positively. Even for Android-11, for appium version 1.17.0 , the emulator is working fine, its only for new browser versions like chrome-94 to chrome-99, the error is coming. 
I also tried to copy/paste apksigner.jar at other locations but this approcah didn't worked. Also tried changing permissions of file.
If there is any apk signer application that needs to be installed or some enhanced security hass been applied on apksigner.jar and this needs to be unlocked , please do let us know

**Comment by mykola-mokhnach** [comment]
> We have used same apksigner.jar to create virtual emulator devices for Android 7, 8, 8.1, 9,10 and all seems working positively.

Are you sure you don't mix anything? apksigner is not needed to create virtual devices. It's used exclusively to sign apps and do some other signature-related operations. Check https://developer.android.com/studio/command-line/apksigner for more details.

**Comment by mykola-mokhnach** [comment]
Closed as not issue
