### ISSUE TITLE
iOS version 15.4.1 does not support latest appium version

### ISSUE THREAD

**Issue by mdelgoda-ifs** [appium/appium#16716]
## The problem

I am using appium studio for iOS test automation. Recently I’ve updated my iOS version to 15.4.1. And parallelly I’ve updated the appium version to 22.1.8625. But I am getting an error as below. I am using iPhone 7 plus

<img width="955" alt="image" src="https://user-images.githubusercontent.com/87293197/161889358-40a8a16b-58d2-480d-ae47-f3fa83b664d1.png">

**Comment by KazuCocoa** [comment]
Please ask the vendor since the Appium Studio is not our product
