### ISSUE TITLE
move official plugins into this repo

### ISSUE THREAD

**Issue by boneskull** [appium/appium#16713]
Because of the currently development workflow where `npm link appium` is often necessary, it makes sense for all official plugins living in the plugins monorepo to live in this repository instead.

Looked at this a bit already, and found that there's no good way to import them one-by-one while retaining the history, especially when commits touch multiple packages (which makes cherry-picking per-package impossible).  So we cannot easily do this piecemeal without a ton of manual rebasing.

Will add more subtasks here as needed.

**Comment by jlipps** [comment]
if it's going to be really tough to do while maintaining history, i'm fine to lose history.
