### ISSUE TITLE
Include driver with Appium

### ISSUE THREAD

**Issue by devwdwgui** [appium/appium#16715]
## The problem

I would like to bundle Appium 2 with the driver [uiautomator2](https://github.com/appium/appium-uiautomator2-driver). I would like to have one location where Appium 2 as well as the driver is located for easier deployment on a target machine. This is the follow up to the by now closed [issue](https://github.com/appium/appium/issues/16580).

## Environment

* Appium version (or git revision) that exhibits the issue: 2.0.0-beta.27
* Desktop OS/version used to run Appium: Windows 20H2
* Node.js version (unless using Appium.app|exe): v16.14.0
* Npm or Yarn package manager: NPM 8.3.1
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Both
* Appium CLI or Appium.app|exe: -

## Details

Following [issue](https://github.com/appium/appium/issues/16580) to bundle Appium with the Android driver I wanted to try the suggestion:

> You should probably create your own custom node.js project that gets bundled with https://github.com/vercel/pkg. It can include both Appium and the uiautomator2 driver as dependencies and expose its own entrypoint that calls Appium's main function. 

So I created a new project using the following commands:

```
npm init
npm install appium@2.0.0-beta.27
npm install appium-android-driver
```

This worked fine. I then added the following line to the scripts of `package.json`:

`"start": "node.exe src/startapp.js",`

I ended up with the package.json:

```
{
  "name": "test",
  "version": "0.0.1",
  "description": "test",
  "main": "src\\index.js",
  "scripts": {
    "start": "node.exe src/startapp.js",
    "test": "test"
  },
  "author": "testauthor",
  "license": "ISC",
  "dependencies": {
    "appium": "^2.0.0-beta.27",
    "appium-android-driver": "^5.0.8",
    "pkg": "^5.5.2"
  }
}
```

The file `src\startapp.js` contains:

```
const appium = require("appium");
let appiumserver = undefined;

let vars = {};

async function main() {
  await appium.init(vars);
  appiumserver = await appium.main(vars);  
}

main().catch(console.log);
```

When I enter `npm start` in the console no driver is being loaded yet.

```
> test@0.0.1 start
> node.exe src/startapp.js

[debug] [Appium] Reading M:\Test\appiumservertest\node_modules\.cache\appium\extensions.yaml...
[debug] [Appium] Creating hash file directory: M:\Test\appiumservertest\\node_modules\.cache\appium
[Appium] Welcome to Appium v2.0.0-beta.27
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[Appium] No drivers have been installed in M:\Test\appiumservertest\. Use the "appium driver" command to install the one(s) you want to use.
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
```

Any ideas what to change in order to load the driver?

**Comment by jlipps** [comment]
1. we don't support yarn
2. you'll need to actually save appium and the drivers into package.json `npm install --save` not `npm install`. otherwise they're not written to package.json and appium won't find them.

**Comment by jlipps** [comment]
`appium-android-driver` has not been supported for years. you want `appium-uiautomator2-driver`

**Comment by devwdwgui** [comment]
Thank you for your precious remarks!

- I remembered that you do not support Yarn only after my post, so I edited it slightly so that it fits the approach using NPM. I saw your comments then afterwards.
- The package file seems to be updated either using `npm install` or `npm install --save`. Also the folder `node_modules` seems to be identical. Just to make sure I will stick with `npm install --save` to avoid any errors in the future.

You're perfectly right - of course I meant to install `appium-uiautomator2-driver`. So I now did

```
npm init
npm install --save appium@2.0.0-beta.27
npm install --save appium-uiautomator2-driver
```

This time, the driver seems to be installed, once I enter `npm start`. Thank you for pointing me in the right direction.

**Comment by jlipps** [comment]
great!

**Comment by devwdwgui** [comment]
Thanks again and I'll close the issue.

**Comment by vikramvr20** [comment]
@devwdwgui - Are u able to create an exec file with the appium server and uiautomator2 driver bundled together?
