### ISSUE TITLE
Question: Separated logs for parallel tests?

### ISSUE THREAD

**Issue by seanmajorpayne** [appium/appium#16723]
## The problem

At the moment, I am seeing all logs for parallel tests in a single stream and I don't see an easy way to separate logs from parallel devices/simulators.

Is there a built in functionality to get the logs separated by device? I'm using the Ruby Core Library if that makes a difference, but I haven't found anything in the documentation.

Thank you for your time

**Comment by jlipps** [comment]
What I usually recommend is running multiple appium servers in order to keep the log streams separate. Otherwise it's a bit of a mess as you have noticed.

**Comment by seanmajorpayne** [comment]
Okay that was something I'd considered, but thought there must be some way to separate the outputs. Good to know! Thank you

**Comment by mykola-mokhnach** [comment]
I'm currently working on several log improvements that would add unique driver identifier and session id prefix to most of the logged lines. Some of these changes have been already merged to recent driver versions that are only available in appium2
