### ISSUE TITLE
Do not open appium.io on first simulator launch

### ISSUE THREAD

**Issue by rostik404** [appium/appium#16720]
## The problem

I see in logs that appium is opening appium.io page on first session creation and it may take about 20 seconds:
```
[35m[iOSSim][39m Simulator with UDID 01BD7876-1DFB-4A2E-9AFD-E30E51D1C5E4 booted in 50.222s

[debug] [35m[iOSSim][39m Safari successfully opened 'http://www.appium.io' in 20.580s
```

How can I avoid this page opening? Is there any option?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOs Big sur
* Node.js version (unless using Appium.app|exe): 12.18.1
* Npm or Yarn package manager: 6.14.5
* Mobile platform/version under test: 
* Real device or emulator/simulator: simulator 
* Appium CLI or Appium.app|exe: cli

## Link to Appium logs
https://gist.github.com/rostik404/abd9ef763c3984598ab0b30805f3a482

**Comment by mykola-mokhnach** [comment]
Try [safariInitialUrl](https://github.com/appium/appium-xcuitest-driver#web-context) capability

Please use Appium forum to ask questions

**Comment by rostik404** [comment]
It's not about initial url. Appium opens appium.io just after simulator booting, before session was created.

**Comment by mykola-mokhnach** [comment]
have you eventually tried to change it?

**Comment by mykola-mokhnach** [comment]
Please provide the full log

**Comment by rostik404** [comment]
https://gist.github.com/rostik404/4535513f70f1d2a033ac3938d2aecad1

**Comment by KazuCocoa** [comment]
it seems like https://github.com/appium/appium-ios-simulator/blob/1099c41102a35fec57dd4255085354ea9c60dd9f/lib/simulator-xcode-6.js#L646 is called since the url had `www`.
The code pointed by mykolad shold not have `www`.

```
[debug] [35m[XCUITest][39m No simulator directories found.

[debug] [35m[iOSSim][39m Attempting to launch and quit the simulator, to create directory structure
```

https://github.com/appium/appium-xcuitest-driver/blob/a94c2023228c0bff8c6645cf2612a61b0a31c7b2/lib/simulator-management.js#L314 to apply `"appium:locationServicesEnabled": false,` to the simulator.

**Comment by rostik404** [comment]
Sorry, but I didn't get, what can I do to not open this url?
According to the code, we always setting `safari=true` if browser name is `safari` https://github.com/appium/appium-xcuitest-driver/blob/c289048dc3591fab0ff3a83fb494af32429260a7/lib/driver.js#L372
So, appium.io would be opened anyway?

**Comment by KazuCocoa** [comment]
Yes, it was probably to apply the Simulator/Safari plist change in the launching time.

Dropping `"appium:locationServicesEnabled": false` can be a workaround at this time. Then, appium does not configure simulator/safari plist

**Comment by KazuCocoa** [comment]
or apply https://github.com/appium/appium-ios-simulator/pull/322 (appium-ios-simulator module v4.0.2)
