### ISSUE TITLE
Appium does not kill all chromedriver instances on session end

### ISSUE THREAD

**Issue by ostap-oleksyn** [appium/appium#16730]
## The problem

I have a hybrid application that uses 2 webviews. The flow is following
1. I start the app (webview A) - appium starts one chromedriver instance
2. In the app I click a button which redirects me to chrome(webview b) - appium starts second chromedriver
3. I perform an action in chrome which closes it and switches me back to the app - webview A

After I call driver.quit() appium kills only the second chromedriver instance, first instance leaves hanging in the memory.
We're running a lot of tests using the same appium instance without restarting it, which causes us problems since after some time there are a lot chromedriver instances in the memory.

## Environment
Appium version: 1.20.2/1.22.3
OS: Windows 7/Windows 10
Devices: Pixel 2 - Android 12/Moto e - Android 11

## Link to Appium logs
https://gist.github.com/ostap-oleksyn/603ff25dd8ca96d93d02de770a513c89

**Comment by mykola-mokhnach** [comment]
Also, please try the most recent driver version, which is only available in Appium2

**Comment by ostap-oleksyn** [comment]
@mykola-mokhnach tried both options, still the same behavior.
Here is the log from appium2 - https://gist.github.com/ostap-oleksyn/7825d6ba0e0b3e8da3dfac4d8c73f218

**Comment by mykola-mokhnach** [comment]
I have recently published a [patch](https://github.com/appium/appium-chromedriver/pull/245) there. Try to reinstall uia2 driver and make sure the version of used chromedriver is above 5.0.2

**Comment by ostap-oleksyn** [comment]
@mykola-mokhnach Will this work for appium1 or only for appium2?
I'm not that familiar with npm, should I just uninstall appium-uiautomator2-driver package and then install it again?

**Comment by mykola-mokhnach** [comment]
Appium1 does not get any updates since the new year, so only Appium2.

> I'm not that familiar with npm, should I just uninstall appium-uiautomator2-driver package and then install it again?

Yes, just do it using Appium2 CLI rather than NPM.

**Comment by ostap-oleksyn** [comment]
I reinstalled uia2 driver using appium cli. How do make sure the version of used chromedriver is above 5.0.2?

**Comment by mykola-mokhnach** [comment]
You could use [npm list](https://stackoverflow.com/questions/17937960/how-to-list-npm-user-installed-packages) for this purpose

**Comment by ostap-oleksyn** [comment]
Hm.. I don't see appium-chromedriver in my dependencies. 
https://gist.github.com/ostap-oleksyn/d477742fe7ba1755a7dee62bb4b05113

**Comment by mykola-mokhnach** [comment]
Drivers are installed into appium's home folder by default (e.g. `$HOME/.appium`).

**Comment by ostap-oleksyn** [comment]
$ npm list appium-chromedriver
.appium@ C:\Users\ostap\.appium
└─┬ appium-uiautomator2-driver@2.0.6
  ├─┬ appium-android-driver@5.0.8
  │ └── appium-chromedriver@5.0.1 deduped
  └── appium-chromedriver@5.0.1

This is what I see in .appium folder. How do I force uiautomator2 to use appium-chromedriver 5.0.2? Should I just uninstall 5.0.1 version and install 5.0.2 using npm?

**Comment by mykola-mokhnach** [comment]
make sure all leftovers are deleted after you uninstall appium-uiautomator2-driver via CLI. Maybe delete these leftovers manually from the home folder before installing the driver again

**Comment by ostap-oleksyn** [comment]
I uninstalled the driver, uninstalled appium and removed .appium folder. Then installed everything again and it still shows 5.0.1 version
$ npm list appium-chromedriver
.appium@ C:\Users\ostap\.appium
└─┬ appium-uiautomator2-driver@2.0.6
  ├─┬ appium-android-driver@5.0.8
  │ └── appium-chromedriver@5.0.1 deduped
  └── appium-chromedriver@5.0.1

**Comment by mykola-mokhnach** [comment]
Weird. I have bumped driver version to 2.0.7 -  should be getting the updated dependency now

**Comment by ostap-oleksyn** [comment]
Reinstalled everything again. Looks like it's working now. All chromedriver instances are killed.
Thanks a lot for quick help!
On more question though. Since this fix will not be available in appium1, how stable is appium2 at the moment?

**Comment by jlipps** [comment]
It could be npm took a while to reflect the package being published, that happens sometimes. In the future you should also be able to run `appium driver update uiautomator2` and it will perform the update without having to uninstall and reinstall.

**Comment by jlipps** [comment]
> how stable is appium2 at the moment

We recommend using it. Any platform-related stability is immaterial to the Appium 2 upgrade since Appium 2 doesn't change the way drivers themselves work. The only logic which has changed has to do with the way drivers are included and activated.

**Comment by ostap-oleksyn** [comment]
That's good news. I'll try switching my tests to appium2. Thanks again!

**Comment by mykola-mokhnach** [comment]
Closed as fixed
