### ISSUE TITLE
Parameters were incorrect. We wanted \"we require one of \\\"text\\\" or \\\"value\\\" params\"

### ISSUE THREAD

**Issue by rajkumar-cp** [appium/appium#16745]
## The problem

We are trying to run almost 600+ cases in Cloud Platform i.e. Using saucelabs when doing the same around 150+ cases were failing because of this issue. Encountered internal error running command: BadParametersError: Parameters were incorrect. We wanted \"we require one of \\\"text\\\" or \\\"value\\\" params\" and you sent {}

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.2
* Last Appium version that did not exhibit the issue (if applicable): Nil (It occurred even in lower version of appium 1.17.0 but not to this extent)
* Desktop OS/version used to run Appium: Nil
* Node.js version (unless using Appium.app|exe): Nil
* Npm or Yarn package manager: Nil
* Mobile platform/version under test: iOS14.5
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Nil

## Link to Appium logs

https://gist.github.com/rajkumar-cp/b9cbdc6cf15f1930516677466dfc8186

Please let me know if more details are required

**Comment by KazuCocoa** [comment]
Probably the below part?
```
    {
        "id": 759,
        "time": "19:07:36",
        "level": "VERBOSE",
        "message": "[HTTP] --> POST /wd/hub/session/870e5744-075e-456b-bd8b-f4deb378c424/element/23000000-0000-0000-A801-000000000000/value"
    },
    {
        "id": 760,
        "time": "19:07:36",
        "level": "VERBOSE",
        "message": "[HTTP] {}"
    },
```

it seems like your client sent `{}` as the POST body for `/value` endpoint that requires `text` or `value` keys as the error message.

**Comment by KazuCocoa** [comment]
this part sent `value` from your client.
```
    {
        "id": 447,
        "time": "19:07:23",
        "level": "VERBOSE",
        "message": "[HTTP] --> POST /wd/hub/session/870e5744-075e-456b-bd8b-f4deb378c424/element/1E000000-0000-0000-A801-000000000000/value"
    },
    {
        "id": 448,
        "time": "19:07:23",
        "level": "VERBOSE",
        "message": "[HTTP] {\"id\":\"1E000000-0000-0000-A801-000000000000\",\"value\":[\"https://mobilemerlinqa.aspiresys.com\"]}"
    },
```

**Comment by rajkumar-cp** [comment]
@KazuCocoa  Anything needs to be fixed in the client end means in my code ? Because we have not done anything to modify the way how appium works.

**Comment by KazuCocoa** [comment]
Yes, or somewhere between your environment and before reaching appium.

The attached log said the Appium instance got `{}` as `/wd/hub/session/870e5744-075e-456b-bd8b-f4deb378c424/element/23000000-0000-0000-A801-000000000000/value`'s request body. Some requests such as `/wd/hub/session/870e5744-075e-456b-bd8b-f4deb378c424/element/1E000000-0000-0000-A801-000000000000/value` had expected value, `{\"id\":\"1E000000-0000-0000-A801-000000000000\",\"value\":[\"https://mobilemerlinqa.aspiresys.com\"]}`. So i assumed your client did not send body in some cases.

**Comment by jlipps** [comment]
yeah it's either a client error or a sauce labs internal proxy error. either way, appium is behaving as expected here.
