### ISSUE TITLE
extensions.yaml in doc?

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#16743]
## The problem

I forgot we addressed `extensions.yaml` in past appium pro etc... but should we add `extensions.yaml` in migration guide or somewhere?
Latest code has it in `APPIUM_HOME/node_modules/.cache/appium/extensions.yaml`. It was `APPIUM_HOME/extensions.yaml` before.

This is just a note for documentation.

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by jlipps** [comment]
@KazuCocoa we should mention anything relevant about extensions.yml in the 'Managing Drivers & Plugins' doc in the new architecture (https://github.com/appium/appium/blob/jlipps/new-docs/packages/appium/docs/en/guides/managing-exts.md)

**Comment by mykola-mokhnach** [comment]
@KazuCocoa Can we close this issue now?
