### ISSUE TITLE
Add support for window/new route

### ISSUE THREAD

**Issue by titusfortner** [appium/appium#16749]
## The problem

W3C added support for [creating a new window ](https://w3c.github.io/webdriver/#new-window), which is supported by chromedriver, but not by Appium.

## Environment

N/A

## Details

Here's a user who has run into this problem:
https://stackoverflow.com/questions/71782096/org-openqa-selenium-unsupportedcommandexception-for-appium-devices-for-sauce-l/71787742

## Link to Appium logs

N/A

## Code To Reproduce Issue [ Good To Have ]

Selenium code sent to Appium Server for mobile browser:
```java
driver.switchTo().newWindow(WindowType.WINDOW);
```

**Comment by KazuCocoa** [comment]
Tested UIA2 driver/chromedriver worked with this route in appium 2
