### ISSUE TITLE
Installing Appium "next" beta 2.0.0 fails

### ISSUE THREAD

**Issue by bwomsm1** [appium/appium#16746]
## The problem
When running the following command:
```
npm install -g appium@next
```
I am getting the following error:
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for plist@3.0.5.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/boazwarshawsky/.npm/_logs/2022-04-11T04_39_56_285Z-debug-0.log
```

## Environment

* Appium version (or git revision) that exhibits the issue:latest beta 2.0.0
* Last Appium version that did not exhibit the issue (if applicable): 2.0.0-beta.25
* Desktop OS/version used to run Appium: Mac 12.2.1
* Node.js version (unless using Appium.app|exe): v16.13.0
* Npm or Yarn package manager: npm 
* Mobile platform/version under test: None
* Real device or emulator/simulator: None
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for plist@3.0.5.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/boazwarshawsky/.npm/_logs/2022-04-11T04_39_56_285Z-debug-0.log
```

## Code To Reproduce Issue [ Good To Have ]
Just by running 
```
npm install -g appium@next
```

**Comment by KazuCocoa** [comment]
What the error log in /Users/boazwarshawsky/.npm/_logs/2022-04-11T04_39_56_285Z-debug-0.log ?
The version exists in the npm package as https://www.npmjs.com/package/plist/v/3.0.5 . `appium/node_modules/plist/package.json` also had 3.0.5 one on my local what got via npm install -g just now. (PDT 10pm)

**Comment by bwomsm1** [comment]
[2022-04-11T04_39_56_285Z-debug-0.log](https://github.com/appium/appium/files/8461289/2022-04-11T04_39_56_285Z-debug-0.log)
@KazuCocoa log is attached

**Comment by KazuCocoa** [comment]
`http://cloud-build-master16.corp.aeroscout.com:8081` probably your env referred to your private registry instead of https://registry.npmjs.org? Then, please ask the administrator.

**Comment by bwomsm1** [comment]
@KazuCocoa its my own mac, 
Can you share how do I change that?

**Comment by KazuCocoa** [comment]
Probably https://stackoverflow.com/questions/41136444/how-to-reset-the-npm-registry-in-global-npm-config may help.

**Comment by bwomsm1** [comment]
@KazuCocoa thanks, definitely not on your side, but thanks for helping with that.
The following line from your link solved the issues: 
```
npm config set registry https://registry.npmjs.org/
```

**Comment by bwomsm1** [comment]
Closing the issue.
