### ISSUE TITLE
queryAppState of BACKGROUND app returns FOREGROUND

### ISSUE THREAD

**Issue by eething** [appium/appium#16755]
## The problem

* I have 2 app
  * com.aaa.foo and and com.aaa.foo2
  * I want to queryappstate of com.aaa.foo (background) while running com.aaa.foo2
  * but it always return 4 (FOREGROUND)
  * code bellow shows that it returns true because foo2 includes foo
  * it needs exact match
```
  for (const line of (await this.adb.dumpWindows()).split('\n')) {
    if (line.includes(appId) && (line.includes('mCurrentFocus') || line.includes('mFocusedApp'))) {
      return APP_STATE.RUNNING_IN_FOREGROUND;
    }
  }
```

* https://github.com/appium/appium-android-driver/blob/master/lib/commands/app-management.js

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium-android-driver/pull/737 should fix this issue
