### ISSUE TITLE
multiple versions of dependencies can cause typescript errors

### ISSUE THREAD

**Issue by boneskull** [appium/appium#16769]
So, yeah, this just happened.  `execute-driver-plugin` depended on `webdriverio`@7.19.3, but the root monorepo wanted `webdriverio`@7.19.5, which `@appium/types` also needs.  given this was a difference of a couple patch upgrades, you'd think that the types would be the same. and you'd be right! but typescript does not know to "dedupe" these; the result was that the types declared by the version of `@wdio/types` pulled in by one `webdriverio` (perhaps due to the global namespace declaration) came into conflict when the _second_ version of `@wdio/types` (they evidently were not the same) was pulled in to the compilation--since they'd already been declared elsewhere.

it's unclear to me if this can be caused by other kinds of declarations (since I haven't seen any), or if this is actually a common issue.  obviously, the root cause can be in a transitive dependency.  but if we do something like upgrade `webdriverio` in the monorepo root, but _don't_ do the same in `execute-driver-plugin`, this _will_ happen again.

to mitigate this, we'd want a script to automate syncing of dep versions.  I was thinking my [sync-mono-packages](https://www.npmjs.com/package/sync-monorepo-packages) might be a good place to add this functionality, but that tool is designed with the "single source of truth" being the monorepo root's `package.json`; this would not solve the case where package _a_'s depends on `foo@1` and package _b_ depends on `foo@2` and the monorepo root `package.json` does not depend on `foo` at all.  somebody else may have written something. 

anyway: if this keeps happening, we should do something about it.  if it doesn't, then forget it.  this is more of a note to keep an eye on the situation.

**Comment by boneskull** [comment]
an example of `tsc` output:

```
node_modules/@wdio/types/build/index.d.ts:23:13 - error TS2374: Duplicate index signature for type 'string'.

23             [key: string]: any;
               ~~~~~~~~~~~~~~~~~~~

node_modules/@wdio/types/build/index.d.ts:26:13 - error TS2374: Duplicate index signature for type 'string'.

26             [key: string]: any;
               ~~~~~~~~~~~~~~~~~~~

node_modules/@wdio/types/build/index.d.ts:29:13 - error TS2374: Duplicate index signature for type 'string'.

29             [key: string]: any;
               ~~~~~~~~~~~~~~~~~~~

node_modules/@wdio/types/build/index.d.ts:35:19 - error TS2320: Interface 'Config' cannot simultaneously extend types 'Testrunner' and 'Testrunner'.
  Named property 'after' of types 'Testrunner' and 'Testrunner' are not identical.

35         interface Config extends Options.Testrunner {
                     ~~~~~~
```

**Comment by boneskull** [comment]
fwiw, the errors above were basically misdirection, which sucks to debug if you have no idea where to start.  I only knew how to fix this because I am old

**Comment by jlipps** [comment]
👍  does the typescript repo itself have any conversation around this?

**Comment by boneskull** [comment]
@jlipps ...which repo?  microsoft/typescript?

**Comment by jlipps** [comment]
yeah, what i mean is, is this a known issue which is likely to be addressed by typescript itself?

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
