### ISSUE TITLE
Exception while wait element until visibility [Chromedriver]

### ISSUE THREAD

**Issue by Muratoi** [appium/appium#16770]
## The problem

sometimes i get timeout exception, while wait.until(EC.visibility_of_element_located) via chromedriver, not every time but often
## Environment

* Last version Appium 2
* Last version Python-Appium client
* Last Appium version that did not exhibit the issue (if applicable): -
* Mobile platform/version under test: Android 11
* Real device or emulator/simulator: Real devices
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

https://gist.github.com/Muratoi/251f9f28867669d6903493438cd49aba

## Code To Reproduce Issue [ Good To Have ]

    def element_find(self, *locator, timeout=10):
        self.driver.implicitly_wait(timeout)
        wait = WebDriverWait(self.driver, timeout)
        try:
>           wait.until(EC.visibility_of_element_located(locator))

self = <selenium.webdriver.support.wait.WebDriverWait (session="0d2ae07e-7455-4763-8c76-615927ba3f1d")>
method = <function visibility_of_element_located.<locals>._predicate at 0x105a23550>
message = ''

    def until(self, method, message=''):
        """Calls the method provided with the driver as an argument until the \
        return value does not evaluate to ``False``.
    
        :param method: callable(WebDriver)
        :param message: optional message for :exc:`TimeoutException`
        :returns: the result of the last call to `method`
        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs
        """
        screen = None
        stacktrace = None
    
        end_time = time.time() + self._timeout
        while True:
            try:
                value = method(self._driver)
                if value:
                    return value
            except InvalidSelectorException as e:
                raise e
            except self._ignored_exceptions as exc:
                screen = getattr(exc, 'screen', None)
                stacktrace = getattr(exc, 'stacktrace', None)
            time.sleep(self._poll)
            if time.time() > end_time:
                break
>       raise TimeoutException(message, screen, stacktrace)
E       selenium.common.exceptions.TimeoutException: Message:

../../../../vebn/lib/python3.8/site-packages/selenium/webdriver/support/wait.py:89: TimeoutException

 self.switch_to_webview(timeout=10)
self.input(*self._input_card_number, text=card_number)

P.S. I am sure that element located, I checked via chrome dev tools for elements

Also I have a question how I can setup impiclity wait while I switch to web view because standard impiclity wait doesn't work with chromedriver.

**Comment by mykola-mokhnach** [comment]
The visibility is returned directly by chromedriver itself. Appium acts as a proxy there. Consider reporting your issue to Google.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
