### ISSUE TITLE
appium 2 docs: figure out API docs generation system

### ISSUE THREAD

**Issue by jlipps** [appium/appium#16787]
- use JSDoc? or TSDoc?
- should be wrapped up as a set of tooling in the `docutils` package
- conventions should be documented so that 3rd party extension authors can use it to build their own docs.

**Comment by alaahong** [comment]
Do we have any guide to list the step of building the docs locally?

As displaying in the bottom of page, "Documentation built with [MkDocs](http://www.mkdocs.org/)." , but there is not such file in project [mkdocs.yml](https://www.mkdocs.org/getting-started/#creating-a-new-project) . The github actions trigger "npm run generate-docs", but seems we have to modify some path parameters locally.

And meanwhile, if Appium want to change the Docs, Hugo is another choice as the link https://www.selenium.dev/documentation/about/contributing/

**Comment by jlipps** [comment]
the new docs system is in the 2.0 branch under packages/appium. you can see some npm scripts there for building docs.

**Comment by jlipps** [comment]
@boneskull figured this out with TSDoc
