### ISSUE TITLE
appium 2 docs: ensure migration doc is up to date

### ISSUE THREAD

**Issue by jlipps** [appium/appium#16785]
for example:

- add client changes to migrating doc (`'/wd/hub'` -> `''`)

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium/blob/2.0/docs/en/advanced-concepts/migrating-to-appium-2.0.md

like https://github.com/appium/appium/issues/16743 as well.

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium/issues/16927 probably it would be helpful to address `"` for Win env

**Comment by jlipps** [comment]
yeah, we should maybe just always use quotes in our shell examples since it doesn't hurt on bash/zsh and seems like it's actually necessary on win
