### ISSUE TITLE
getPageSource hangs for 1 minute before throwing a WebDriverException 

### ISSUE THREAD

**Issue by RichardHoOoOo** [appium/appium#16782]
## The problem
I am developing an automated testing tool using Appium. I found in some specific cases (e.g., app is not responding), `driver.getPageSource()` hangs for around 1 minute before throwing a `WebDriverException`. Is there any way to set a timeout for `driver.getPageSource()`? Using `driver.manage().timeouts().pageLoadTimeout(10, TimeUnit.SECONDS)` will throw `org.openqa.selenium.UnsupportedCommandException: Not implemented yet for pageLoad`. Therefore it is not an option.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS Big Sur 11.6.2
* Node.js version (unless using Appium.app|exe): v16.13.2
* Npm or Yarn package manager:
* Mobile platform/version under test: Android 10
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe:

## Link to Appium logs

```
[debug] [W3C (72d38e45)] Encountered internal error running command: NotImplementedError: Not implemented yet for pageLoad.
```

**Comment by mykola-mokhnach** [comment]
Please provide the full server log along with the logcat output

**Comment by RichardHoOoOo** [comment]
The [adb logcat](https://gist.github.com/RichardHoOoOo/cca358ada43fd7d489b55d33e9324dd4)
The [server log](https://gist.github.com/RichardHoOoOo/8b3c0ef90b307ee8d4daf22866be8819)

Seems the reason is `Timed out after 37772ms waiting for the root AccessibilityNodeInfo in the active window. Make sure the active window is not constantly hogging the main UI thread (e.g. the application is being idle long enough), so the accessibility manager could do its work`. So when the app is buggy (e.g., doing heavy jobs on the UI thread), the accessibility cannot get the UI info. 

Is it possible to set a timeout (like 10s) for this situation? Waiting for more than 30 seconds seems not necessary.

**Comment by mykola-mokhnach** [comment]
It is actually [set](https://github.com/appium/appium-uiautomator2-server/blob/6307b54c106814f7d35ddeb52bef3fc83acfc26e/app/src/main/java/io/appium/uiautomator2/utils/AXWindowHelpers.java#L63) to 10s by default, but UiAutomator has its own internal timers, which we cannot control. Feel free to propose a PR if you know a better strategy.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
