### ISSUE TITLE
appium 2 docs: move/rewrite appium and selenium grid guide

### ISSUE THREAD

**Issue by jlipps** [appium/appium#16808]
`packages/appium/docs/en/guides/grid.md`

**Comment by KazuCocoa** [comment]
note;

Current https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/grid.md
4 https://www.selenium.dev/documentation/grid/

Probably grid 3 user still exists. Their capabilities can use with `appium:` prefix, so for now, probably we do not need to change so much.

---

I remember currently we have https://github.com/appium/appium/issues/16550 to fully work with Grid 4. As a workaround, users can use XPath as the main locator strategy (of course, especially ios, we won't recommend XPath in performance perspective though)
https://www.w3.org/TR/webdriver1/#locator-strategies

**Comment by mythsunwind** [comment]
> I remember currently we have https://github.com/appium/appium/issues/16550 to fully work with Grid 4.

What is the current plan to add support in appium for this? The needed change in selenium seems to be released in August.

**Comment by jlipps** [comment]
as far as I remember, the only fix necessary was on the Grid side. has the new Grid been released?
