### ISSUE TITLE
Selenium 4 getScreenshotAs not supported by Appium

### ISSUE THREAD

**Issue by sonali9293** [appium/appium#16827]
## The problem

getScreenshotAs method present in selenium 4, does not seem to be compatible with appium. It is using the pre-w3c endpoint, which could be the issue.

## Environment
N/A

## Details

Please refer -   [https://stackoverflow.com/questions/71871228/org-openqa-selenium-webdriverexception-for-appium-on-selenium4-for-getscreenshot](url)

## Link to Appium logs
N/A

## Code To Reproduce Issue [ Good To Have ]
`void captureScreenShotOf(WebElement el, WebDriver driver) {
    File newImg = el.getScreenshotAs(OutputType.FILE);
    try {
        FileUtils.copyFile(newImg, new File("./screenshot/expected.jpg"));
    } catch (Exception e) {
        e.printStackTrace();
    }
}`

**Comment by StephanB75** [comment]
I use it with Selenium-Java 4.1.2 / Appium Java-client 8.0.0 and Appium Server 2 Beta@30
and it still works.
File scrFile = ((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);
FileUtils.copyFile(scrFile, new File(saveDir));

**Comment by mykola-mokhnach** [comment]
Please provide the full server log and the environment information

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by sonali9293** [comment]
Apologies for being late in responding. Can we re-open this in any way ?

**Comment by mykola-mokhnach** [comment]
> Apologies for being late in responding. Can we re-open this in any way ?

We can as soon as relevant logs are provided
