### ISSUE TITLE
Appium Android driver is un installing for second time even full reset is false

### ISSUE THREAD

**Issue by rajasekherreddy** [appium/appium#16826]
## The problem

I am running Appium to test an Android app using the java client. The capabilities include noReset=false and fullReset=true for first time.So app installed.  Then i change capabilities like language and noReset=true and fullReset=false. Even I set noReset=true also app is reinstalling. below are the scenarios i am adding here.  The same process in IOS working as expected.

## Environment

* Appium version (or git revision) that exhibits the issue:1.22.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac big sur
* Mobile platform/version under test: any
* Real device or emulator/simulator: real device

## Details

Appium Android driver is un installing for second time even full reset is false. Below are cases i am attaching.

** First time installing as expected **
capabilities.setCapability("noReset", false);
capabilities.setCapability("fullReset", true);
androidDriver = makeAndroidDriver(serverUrl, capabilities);

** Here also uninstalling even fullReset= true and noReset=false**
capabilities.setCapability("noReset", true);
capabilities.setCapability("fullReset", false);
androidDriver = makeAndroidDriver(serverUrl, capabilities);

** for third time and next onwards, it is not uninstalling **
capabilities.setCapability("noReset", true);
capabilities.setCapability("fullReset", false);
androidDriver = makeAndroidDriver(serverUrl, capabilities);

** When i change capabilities fullrest=true then reinstalling as expected.but again same as above scenarios **
capabilities.setCapability("noReset", false);
capabilities.setCapability("fullReset", true);
androidDriver = makeAndroidDriver(serverUrl, capabilities);

The problem here AndroidDrviver not initializing second time properlly after fullRset=false. This one is happening only in android. In IOS its is working properlly Please help. Tq in advance.

**Comment by mykola-mokhnach** [comment]
Please upgrade the driver to the most recent version (only available in appium2) and try again. We don't backport fixes to older versions of it

**Comment by mykola-mokhnach** [comment]
Closed because of no response
