### ISSUE TITLE
iOS connect ECONNREFUSED 127.0.0.1:8100 

### ISSUE THREAD

**Issue by param-finder** [appium/appium#16846]
## The problem

I'm trying to run ios in Appium inspector to see the xpaths. But its not connecting to the appium server and giving error.

```
Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: connect ECONNREFUSED 127.0.0.1:8100
```

<img width="2202" alt="Screenshot 2022-04-22 at 12 12 11" src="https://user-images.githubusercontent.com/92723723/164704850-8281aed6-4395-4ca0-a55b-dfa2629abbcf.png">
<img width="1765" alt="Screenshot 2022-04-22 at 12 13 46" src="https://user-images.githubusercontent.com/92723723/164704860-416a1237-d012-420c-a5fd-b51ccbdb7107.png">
<img width="1488" alt="Screenshot 2022-04-22 at 12 12 51" src="https://user-images.githubusercontent.com/92723723/164704862-12754bd2-5a1e-4380-a3ba-75470f20d1e1.png">

## Environment

* Appium version (or git revision) that exhibits the issue:
* Appium server app version - 1.22.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS Monterey 12.3.1
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager: yarn
* Mobile platform/version under test: iOS iPhone 13 15.4
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium app

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
https://gist.github.com/param-finder/6f66bc25e39320a0bb13bc0ea7fc454c#file-appium-logs-txt

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
This is expected. Please update the server to the most recent version. Preferably use appium2 as Appium1 is EOLed.
