### ISSUE TITLE
Flutter: unknown server-side error when combining Descendant and Ancestor to find an element uniquely

### ISSUE THREAD

**Issue by sateeshd7** [appium/appium#16841]
unknown server-side error when combining Descendant and Ancestor to find an element uniquely

appium_version": "1.22.0"

Our app has a page with list of items in a Page and would like to find an element uniquely and written a command as below:
**FlutterElement(driver, FlutterFinder().by_descendant(FlutterFinder().by_ancestor(FlutterFinder().by_text("Bridal Makeup"),FlutterFinder().by_type("ServiceItemWidget")),FlutterFinder().by_type("ButtonLabel"))).click()**

Which converted as a below command and got the below error from appium/Flutter driver. When I tried the same combination directly in Flutter driver test, it is working fine.
**{"command":"tap","finderType":"Descendant","matchRoot":false,"firstMatchOnly":false,"of":"{"finderType":"Ancestor","of":"{""finderType"":""ByText"",""text"":""Bridal Makeup""}","matching":"{"finderType":"ByType","type":"ServiceItemWidget"}}","matching":"{"finderType":"ByText","text":"Book"}"}**

**Error:** {'status': 500, 'value': '{"status":13,"value":{"message":"Appium error: An unknown server-side error occurred while processing the command. Original error: Cannot execute command tap, server reponse {\n \"isError\": true,\n \"response\": \"Uncaught extension error while executing tap: type 'bool' is not a subtype of type 'String' in type cast\\n#0 new LinkedHashMap.from. (dart:collection/linked_hash_map.dart:187:26)\\n#1 _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)\\n#2 new LinkedHashMap.from (dart:collection/linked_hash_map.dart:186:11)\\n#3 Descendant.deserialize (package:flutter_driver/src/common/find.dart:329:9)\\n#4 DeserializeFinderFactory.deserializeFinder (package:flutter_driver/src/common/deserialization_factory.dart:32:44)\\n#5 FlutterDriverExtension.deserializeFinder (package:flutter_driver/src/extension/extension.dart:401:18)\\n#6 new CommandWithTarget.deserialize (package:flutter_driver/src/common/find.dart:32:30)\\n#7 new Tap.deserialize (package:flutter_driver/src/common/gesture.dart:14:93)\\n#8 DeserializeCommandFactory.deserializeCommand (package:flutter_driver/src/common/deserialization_factory.dart:56:30)\\n#9 FlutterDriverExtension.deserializeCommand (package:flutter_driver/src/extension/extension.dart:421:18)\\n#10 FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:366:31)\\n#11 BindingBase.registerServiceExtension. (package:flutter/src/foundation/binding.dart:602:32)\\n\\n\",\n \"type\": \"_extensionType\",\n \"method\": \"ext.flutter.driver\"\n}"},"sessionId":"270470fa25541bfe177ccfd1df2768d34bf98f4f"}'}

**Comment by mykola-mokhnach** [comment]
Sorry, but Appium team does not support this driver. Please report your issue into the appropriate issue tracker.
