### ISSUE TITLE
Stream video on rtmp server

### ISSUE THREAD

**Issue by bikee1235** [appium/appium#16856]
Hi @KazuCocoa 

Can we stream video which is coming on 9100 port to any rtmp streaming server 

can you please help in streaming mjpeg stream on rtmp server 

Thanks !

**Comment by KazuCocoa** [comment]
Perhaps you can do it with ffmpeg.
e.g. https://superuser.com/questions/1497866/using-ffmpeg-to-restream-camera-feed-to-rtmp-server

**Comment by KazuCocoa** [comment]
https://discuss.appium.io/ may also help
