### ISSUE TITLE
v2.0.0-beta.33 uiautomator2@2.0.7 did not proxy chromedriver error response

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#16850]
## The problem

I haven't dug well yet, but webbview context (chromedriver as the browserName) was not able to return error (non-200?) message to the client. I observed this with a couple of 40x responses.
Probably something base-driver's proxy.js stuff?

The appium log did not have any logs after `[Chromedriver@1bb5 (6684e194)] Got response with status 404`. Native context proxied the 404 error to the client expectedly.

```
[AndroidUiautomator2Driver@d96d (757c799f)] Driver proxy active, passing request on via HTTP proxy
[debug] [Chromedriver@1bb5 (6684e194)] Matched '/session/757c799f-2d18-4688-8369-f516849835a5/element' to command name 'findElement'
[debug] [Chromedriver@1bb5 (6684e194)] Proxying [POST /session/757c799f-2d18-4688-8369-f516849835a5/element] to [POST http://127.0.0.1:8000/session/6684e19456267c6980911faf266f9f73/element] with body: {"using":"xpath","value":"a"}
[Chromedriver@1bb5 (6684e194)] Got response with status 404: {"value":{"error":"no such element","message":"no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"a\"}\n  (Session info: chrome=100.0.4896.127)","stacktrace":"0   chromedriver_mac64_v100.0.4896.60   0x000000010b0153d9 chromedriver_mac64_v100.0.4896.60 + 5104601\n1   chromedriver_mac64_v100.0.4896.60   0x000000010afa5bf3 chromedriver_mac64_v100.0.4896.60 + 4647923\n2   chromedriver_mac64_v100.0.4896.60   0x000000010ab96b48 chromedriver_mac64_v100.0.4896.60 + 392008\n3   chromedriver_mac64_v100.0.4896.60   0x000000010abcbe26 chromedriver_mac64_v100.0.4896.60 + 609830\n4   chromedriver_mac64_v100.0.4896.60   0x000000010abcbfe1 chromedriver_mac64_v100.0.4896.60 + 610273\n5   chromedriver_mac64_v100.0.4896.60   0x000000010abfe374 chromedriver_mac64_v100.0.4896.60 + 815988\n6   chromedriver_mac64_v100.0.4896.60   0x000000010abe96ed chromedriver_mac64_v100.0.4896.60 + 730861\n7   chromedriver_mac64_v100.0.4896.60   0x000000010abfc091 chromedriver_mac64_v100.0.4896.60 + 807057\n8   chr...
# no logs more. the client did not receive this response.
# I killed the appium process with SIGINT
```

appium 1.22.3, it had `[debug] [W3C] Matched W3C error code 'no such element' to NoSuchElementError`.
```
[HTTP] --> POST /wd/hub/session/7526d2e6-33ef-4b93-8f35-6d487b94f61c/element
[HTTP] {"using":"xpath","value":"a"}
[W3C (7526d2e6)] Driver proxy active, passing request on via HTTP proxy
[debug] [WD Proxy] Matched '/wd/hub/session/7526d2e6-33ef-4b93-8f35-6d487b94f61c/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /wd/hub/session/7526d2e6-33ef-4b93-8f35-6d487b94f61c/element] to [POST http://127.0.0.1:8000/wd/hub/session/638f6f4f5c0395a23e2f93b1f376dd72/element] with body: {"using":"xpath","value":"a"}
[WD Proxy] Got response with status 404: {"value":{"error":"no such element","message":"no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"a\"}\n  (Session info: chrome=100.0.4896.127)","stacktrace":"0   chromedriver_mac64_v100.0.4896.60   0x000000010add73d9 chromedriver_mac64_v100.0.4896.60 + 5104601\n1   chromedriver_mac64_v100.0.4896.60   0x000000010ad67bf3 chromedriver_mac64_v100.0.4896.60 + 4647923\n2   chromedriver_mac64_v100.0.4896.60   0x000000010a958b48 chromedriver_mac64_v100.0.4896.60 + 392008\n3   chromedriver_mac64_v100.0.4896.60   0x000000010a98de26 chromedriver_mac64_v100.0.4896.60 + 609830\n4   chromedriver_mac64_v100.0.4896.60   0x000000010a98dfe1 chromedriver_mac64_v100.0.4896.60 + 610273\n5   chromedriver_mac64_v100.0.4896.60   0x000000010a9c0374 chromedriver_mac64_v100.0.4896.60 + 815988\n6   chromedriver_mac64_v100.0.4896.60   0x000000010a9ab6ed chromedriver_mac64_v100.0.4896.60 + 730861\n7   chromedriver_mac64_v100.0.4896.60   0x000000010a9be091 chromedriver_mac64_v100.0.4896.60 + 807057\n8   chr...
[debug] [W3C] Matched W3C error code 'no such element' to NoSuchElementError
[HTTP] <-- POST /wd/hub/session/7526d2e6-33ef-4b93-8f35-6d487b94f61c/element 404 5154 ms - 2317
```

## Environment

* Appium version (or git revision) that exhibits the issue: 2.0.0-beta.33 , uiautomator2@2.0.7
    - Haven't checked which uia2 driver with appium 2.0 did not have this issue
* Last Appium version that did not exhibit the issue (if applicable): 1.22.3
* Desktop OS/version used to run Appium: macos 12
* Node.js version (unless using Appium.app|exe): cli
* Npm or Yarn package manager: npm
* Mobile platform/version under test: android
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

## Details

as the above description.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by KazuCocoa** [comment]
@mykola-mokhnach do you have any possible ideas?
I guessed around https://github.com/appium/appium/blob/2.0/packages/base-driver/lib/jsonwp-proxy/proxy.js ... but haven't dug yet.
Will take a look further this weekend

**Comment by mykola-mokhnach** [comment]
Last time I was observing similar issue was a crash it was happening due to an unhandled exception in https://github.com/appium/appium/blob/b34b75a80e4b5d7037a5c93fef1b68fcb6d159ee/packages/base-driver/lib/jsonwp-proxy/proxy.js#L315

**Comment by KazuCocoa** [comment]
I see, thanks. Will take a look around there first.

**Comment by KazuCocoa** [comment]
i probably see. The packaged base driver was old.

**Comment by KazuCocoa** [comment]
let me configure renovate in uia2

**Comment by KazuCocoa** [comment]
Resolved with latest base driver
