### ISSUE TITLE
iOS Simulator doesn't load texts on the app after several interations

### ISSUE THREAD

**Issue by tobeitgit** [appium/appium#16864]
## The problem

After I've installed an app compiled for the iOS Simulator, I find that using the same application all the time, after several interactions using Appium, closing and opening the app, finally the texts aren't rendered in the application (for example, at the end, we see an element with text "landing_go_login"), and the only solution is to restart the iOS Simulator.

## Environment

* Appium version (or git revision) that exhibits the issue: **1.21**
* Last Appium version that did not exhibit the issue (if applicable): **Not applicable**
* Desktop OS/version used to run Appium: **macOS Big Sur 11.6.2**
* Node.js version (unless using Appium.app|exe): **v17.4.0**
* Npm or Yarn package manager: **npm**
* Mobile platform/version under test: **iOS** 
* Real device or emulator/simulator: **iOS Simulator**
* Appium CLI or Appium.app|exe: **Appium CLI**

## Details

We can demonstrate this bug if
- we launch iOS Simulator with iPhone 13 (iOS 15.2).
- we obtain the udid of the device with:                     **% xcrun simctl list devices**
- we install an app compiled for iOS Simulator with: **% xcrun simctl install <udid> package.app**
- we run the app, we do several interactions on the app, we close it
- we run the app, we do several interactions on the app, we close it, 
- repeat it continuously, until we find the texts aren't rendered properly (often after 3th iteration of the same script)

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here:
https://gist.github.com/tobeitgit/429e86deafd954be13c981685ac497f3

## Code To Reproduce Issue [ Good To Have ]

Don't applicable here, as it doesn't depend on what actions we're doing on the mobile application.

**Comment by mykola-mokhnach** [comment]
I don't think this is something that has to do with Appium. Consider reporting your issue to Apple.
Also it makes sense to better debug the app itself with developers if the case could be reliably reproduced.

**Comment by jlipps** [comment]
this seems like an issue with app localization or an apple bug, not related to Appium as @mykola-mokhnach has said. but if you explore these avenues and find any evidence that it is related to Appium, we'll happily re-open.
