### ISSUE TITLE
getSystemBars, wrong values for navigationBar in Landscape mode in Android

### ISSUE THREAD

**Issue by SophieDePaula** [appium/appium#16867]
## The problem

When using `getSystemBars` in Android, we get the dimensions of two bars `statusBar` and `navigationBar`.
The `statusBar` returns the same values for the `height` and `width` in both `portrait` and `landscape` modes, but, the `navigationBar` in `landscape` mode switches the `height` and the `width`.

I would expect the same behavior from both bars.

## Environment

* Appium version (or git revision) that exhibits the issue: `1.9.1` and `1.20.2`
* Desktop OS/version used to run Appium: `Linux`
* Node.js version (unless using Appium.app|exe):`16.1.0`
* Npm or Yarn package manager:  `Yarn`
* Mobile platform/version under test: `Android` `7.0` and `10.0`
* Real device or emulator/simulator: `emulator`
* Appium CLI or Appium.app|exe: using SauceLabs emulator

## Link to Appium logs

https://gist.github.com/SophieDePaula/c788c8bd8c62c04317acc4c6f383625b

**Comment by jlipps** [comment]
Can you try again with Appium 2 and the latest version of the UiAutomator2 driver? Appium 1.9.1 and 1.20.2 are quite old, and Appium 1.x is no longer supported.

**Comment by SophieDePaula** [comment]
@jlipps it seems that Appium 2 is still in `Beta`, I can't seem to use it with SauceLabs.
I tried to use Android 12 with appium server version `1.22.1.` which is the latest version I can use and got height of both bars as 1 pixel in both `portrait` and `landscape` modes. This is even a bigger problem because I won't be able to know what's the dimensions of the SystemBars at all.

I need to be able to get the height and width of the system bars for a variety of appium and android versions.

**Comment by jlipps** [comment]
Appium 2 has been out (in beta yes, but we've been recommending its use) for multiple years. If Sauce Labs doesn't support it yet, I would let them know they're falling behind, or ask them to suggest a workaround that they might have for using the latest Android drivers which as of today are only Appium 2 compatible.

As for the specific issue, I'm not sure if @mykola-mokhnach or @KazuCocoa know anything about it? I seem to remember something going on with the status bar functions, that might have been fixed in a recent version.

**Comment by KazuCocoa** [comment]
Afaik, the relevant change is https://github.com/appium/appium-android-driver/pull/730 (https://github.com/appium/appium/issues/16390), that expects to work with appium 2 (since the fix was after dependency's breaking change)

**Comment by mykola-mokhnach** [comment]
Unfortunately we don't provide patches to older driver versions, and since newer ones are incompatible to the EOLed Appium1, the only way to get the fix is to use Appium2.
Closed as duplicate

**Comment by SophieDePaula** [comment]
I see the same issue as in my description with Appium 2 latest beta (33).
Appium logs: https://gist.github.com/SophieDePaula/64a94ae25f56ae84d934a81701cc6409

**Comment by mykola-mokhnach** [comment]
We simply parse the actual output of `adb shell dumpsys window windows` command there (mFrame property of `StatusBar` and `NavigationBar` entries). If this output contains the same width and height values then it must be an issue in Android OS itself.
