### ISSUE TITLE
WebDriverException occurs when calling get_performance_data() on Android

### ISSUE THREAD

**Issue by 252694995** [appium/appium#16868]
## Environment

* Appium version (or git revision) that exhibits the issue:  Appium v1.22.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: windows 10
* Node.js version (unless using Appium.app|exe): 16.14.2
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Android 11
* Real device or emulator/simulator: Real device 
* Appium CLI or Appium.app|exe:

## Link to Appium logs

![1651110590(1)](https://user-images.githubusercontent.com/67477052/165660144-facb7057-6f90-4714-b3b5-2fa879ad1b9d.png)

## Code To Reproduce Issue [ Good To Have ]
desired_caps = dict(
    platformName='Android',
    platformVersion='11',
    automationName='UiAutomator2',
    deviceName='Redminot',
    noReset=True,
    appPackage='com.htinns',
    appActivity='com.huazhu.main.RnMainActivity'
)
driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
print(driver.get_performance_data('com.htinns', 'memoryinfo', 10))

**Comment by KazuCocoa** [comment]
Could you attempt the latest uia2 driver with appium2? (`npm install -g appium@next` and `appium driver install uiautomator2`))

https://github.com/appium/appium-android-driver/pull/719 is not in 1.22.3, so i guess newer version will fix it.

**Comment by 252694995** [comment]
After checking the driver (appium driver list), I found that uiautomator2 was not installed.

After installation (appium driver install uiautomator2), get_ performance_ Data can operate normally
