### ISSUE TITLE
Appium 2 - unable to find chromedriver

### ISSUE THREAD

**Issue by ostap-oleksyn** [appium/appium#16863]
## The problem

Appium is not able to find chromedriver, though it is present in the chromedriver directory.

## Environment

* Appium version (or git revision) that exhibits the issue:  Appium v2.0.0-beta.33
* Last Appium version that did not exhibit the issue (if applicable): Appium v1.22.3
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): v16.15.0
* Npm or Yarn package manager: 8.5.5
* Mobile platform/version under test: Android 12
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

I'm running appium with the following args --allow-insecure=adb_shell,chromedriver_autodownload.
From the logs I can see that it's downloading 2 chromedrivers and those drivers are present in the specified directory. But appium still fails with an error `[debug] [Chromedriver@d1f0] Error: No Chromedriver found that can automate Chrome '91.0.4472'. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md for more details`
Running appium 1 on the same pc works as it should.

## Link to Appium logs

appium 1: https://gist.github.com/ostap-oleksyn/3b48d1da287375dff39ba03f1573a39e
appium 2: https://gist.github.com/ostap-oleksyn/55eedcd0ceaf3a1b344f09297717369e

**Comment by mykola-mokhnach** [comment]
Are these files present in the folder after manual check?

**Comment by mykola-mokhnach** [comment]
The patch has been published in chromedriver 5.0.4
Please reinstall UIA2 driver and make sure this dependency is up to date. Then retry your test

**Comment by ostap-oleksyn** [comment]
Thanks! Tried it with chromedriver 5.0.4 and it works now.
