### ISSUE TITLE
Response of iOS click is 200 despite the click failed due to "Failed to scroll to visible (by AX action) Button"

### ISSUE THREAD

**Issue by NozomiIto** [appium/appium#16913]
## The problem

When I attempted to click an iOS element by Appium,  the response code of Appium server was 200 but the page transit which should have happened did not happen.

When I checked the Appium log with showXcodeLog True, I found the following error message.

`[Xcode] 2022-05-06 17:30:11.373334+0900 WebDriverAgentRunner-Runner[1273:58957] Enqueue Failure: Failed to synthesize event: Failed to scroll to visible (by AX action) Button, {{24.0, 590.5}, {327.0, 52.5}}, label: 'xxxx', error: Error kAXErrorCannotComplete performing AXAction kAXScrollToVisibleAction on element AX element pid: 1279, elementOrHash.elementID: 10778639744.17. (Underlying Error: Error kAXErrorCannotComplete performing AXAction kAXScrollToVisibleAction on element AX element pid: 1279, elementOrHash.elementID: 10778639744.17) /Users/itonozomi/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgentRunner/UITestingUITests.m 44 1`

I think this error message was enqueued at [here](https://github.com/appium/WebDriverAgent/blob/v4.4.1/WebDriverAgentLib/Utilities/FBFailureProofTestCase.m#L51).

Can Appium click this button? I guess no, because the error happened inside Xcode.
Instead, can Appium throw an error if the error `kAXErrorCannotComplete performing AXAction kAXScrollToVisibleAction on element AX element`  happens, or is there any way to know if such error is enqueued inside Xcode? If yes, I can add some workaround to my code.

## Environment

* Appium v2.0.0-beta.35. Appium 1.22.3 also has this issue.
* XCUITestDriver v4.4.1
* macOS Monterey 12.3.1
* node14.17.0
* npm6.14.13
*iOS15.4.1
* Real device. iPhone7
* Appium CLI

## Link to Appium logs

https://gist.github.com/NozomiIto/398f93feb8069a3f3c61ce46cb4c914d

## Code To Reproduce Issue

```
from appium import webdriver
from appium.webdriver.common.appiumby import AppiumBy

desired_caps = {
  "platformName": "iOS",
  "platformVersion": "12.2",
  "automationName": "XCUITest",
  "deviceName": "real device",
  "udid": "auto",
  "xcodeSigningId": "iPhone Developer",
  "xcodeOrgId": "xxxx",
  "bundleId": "xxxx",
  "showXcodeLog": True
}

driver = webdriver.Remote('http://localhost:4723', desired_caps)
el = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value='xxxx')
el.click()
```

Currently this issue happens only on one of my customer's app. So I think this client code to reproduce the issue is not useful.

**Comment by jlipps** [comment]
Yes, good idea to throw an error if possible. this error might just be present in the log though, seems like it doesn't actually result in an exception in the XCUITest library? @mykola-mokhnach do you know?

**Comment by mykola-mokhnach** [comment]
I don't think we could do much there if XCTest does not throw any exception on its own. All we do is calling https://developer.apple.com/documentation/xctest/xcuielement/1618666-tap?language=objc, which does not return any flags or anything similar, which we could use to analyze whether the action was successful or now

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by NozomiIto** [comment]
Thanks for checking!
Then I will monitor xcode log and detect and handle `Failed to scroll to visible (by AX action) Button` error on my test code..
