### ISSUE TITLE
All outgoing email has been globally disabled by an administrator...

### ISSUE THREAD

**Issue by objectivedynamics42** [appium/appium#16914]
...No email notifications of any kind will be sent.

I've been trying to sign up to discuss.appium.io and have never received a verification email. I can now see that [this was raised before and closed](https://github.com/appium/appium/issues/14068) 

Issue 14068 was closed with the justification that "it's not an issue". Does this mean that my efforts to sign up have been wasted?
If not, can someone please explain how I sign up if I'm never sent a verification email?

If it really is no longer possible to sign up, may I suggest removing that function from the site?

**Comment by jlipps** [comment]
yeah it does seem like a problem if users can't sign up! i tried to log in to see if i could do something about this and unfortunately i can't receive the password reset e-mails 😆 

@mykola-mokhnach can you explore the settings to see if there's a way to allow verification and password e-mails to be sent? otherwise the site doesn't seem very functional.

**Comment by mykola-mokhnach** [comment]
I was able to send a test verification email. I assume outgoing emails are only disabled for forum messages, but verification ones should be delivered. There could be issues with spam filters though or with the particular smtp server setup. I'm afraid I cannot help much with that

**Comment by objectivedynamics42** [comment]
> I was able to send a test verification email

I may have misunderstood what you are saying here but has the intended recipient verified that they received it?
Furthermore, have you had any new members join since _all outgoing email_ was disabled?

>I assume outgoing emails are only disabled for forum messages, but verification ones should be delivered

Do you have any evidence that they are though? @jlipps states that he isn't receiving password reset emails.

>There could be issues with spam filters

I tried signing up using two different email accounts and neither account has anything in the junk/spam folder.

>or with the particular smtp server setup

One of the accounts that I used is a Gmail account. Are we really thinking that the issues might be with Google's smtp?

I suspect that the verification emails just aren't being sent.

Do you have any other way of verifying my account?

**Comment by mykola-mokhnach** [comment]
It looks like I cannot change SMTP server settings with my current permissions. It may probably be only configurable via text configs (e.g. via SSH), which I don't have access to.

**Comment by objectivedynamics42** [comment]
OK, thanks. I appreciate your help looking into this. Can you see when you last had a new user verified and if it was before the block was applied to the outgoing emails?
