### ISSUE TITLE
Appium output log to file get stuck

### ISSUE THREAD

**Issue by aaroncarry** [appium/appium#16912]
## The problem

I redirect the Appium log to a log file when I start Appium.
e.g:
`appium -p 4737 --allow-insecure get_server_logs --log-timestamp --local-timezone >> ~/appium_logs/appium_4737.log 2>&1 &`

But in some cases, the log in the log file will get stuck and will not continue to output the log. I don't know under what conditions this is triggered.
<img width="935" alt="image" src="https://user-images.githubusercontent.com/24429337/167096685-edce7a76-457e-4a9c-96f6-d03d0fb50fd3.png">
<img width="963" alt="image" src="https://user-images.githubusercontent.com/24429337/167096835-b39362aa-6bd5-4852-934d-b46e14d305a6.png">

Sometimes there will be some strange logs at the end of the file.
e.g:
`
2022-05-06 00:09:28:497 - [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/sessions[39m
2022-05-06 00:09:28:497 - [35m[HTTP][39m [90m{}[39m
dbug Support Traversed 360 directories and 1333 files in 50595ms
dbug Support Traversed 360 directories and 1333 files in 38743ms
dbug Support Traversed 360 directories and 1333 files in 35942ms
`

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.0
* Desktop OS/version used to run Appium: Mac OS 11.5.2
* Node.js version (unless using Appium.app|exe): v14.18.0
* Package manager name and version (we only officially support NPM): npm 6.14.15
* Appium CLI or Appium.app|exe: CLI
* 

## Appium Log
https://gist.github.com/aaroncarry/66eef53bc18f3057779618a0ec515bdf

**Comment by jlipps** [comment]
have you tried the `--log` option to log to a file rather than doing output redirection?

**Comment by mykola-mokhnach** [comment]
Closed because of no response
