### ISSUE TITLE
Not possible to expand notification by force touch on iOS 15 (trackpad force touch)

### ISSUE THREAD

**Issue by vkuhi** [appium/appium#16922]
## The problem
On iOS 15 was changed the view for notifications on the Notification center.
Previous methods with the press and IOSPressOptions() with pressure, are not working at all.

## Environment

- appium 1.22.3;
- Xcode 13.3;
- iOS 15.4;
- iPhone 8 simulator;
- macOS Monterey 12.2.1.

## Details
For example, we received any notification in the notification center.

<img width="217" alt="Screenshot 2022-05-09 at 17 11 41" src="https://user-images.githubusercontent.com/44023154/167428903-8d28aafc-11bd-4df9-a1e4-56b1f2ddc3cb.png">

Manually we can expand it by force touch ( NB! Should be on: _Simulator->I/O -> Touch pressures -> Use trackpad force)_.

<img width="218" alt="Screenshot 2022-05-09 at 16 58 00" src="https://user-images.githubusercontent.com/44023154/167428769-0e64deaa-6917-450b-a1bf-ec2eb8ca3f69.png">

But there are no any ways to do this by appium methods, also by any scripts from "_mobile:..._".
E.g. tried such methods: 

```
new IOSTouchAction((PerformsTouchActions)DriverPool.getDriver())
         .press(new IOSPressOptions().withElement(ElementOption.element(DriverPool.getDriver().findElement(notif))).withPressure(2.0))
         .waitAction(WaitOptions.waitOptions(Duration.ofMillis(3000)))
         .release()
         .perform();

new TouchAction((PerformsTouchActions)DriverPool.getDriver())
                .longPress(ElementOption.element(element.getMobileElement()))
                .release()
                .perform();

mobile: touchAndHold
```

Seem like not enough press is performed for all of them.
Does this issue related to the Xcode, or it could be fixed and provided solutions by Appium?

**Comment by mykola-mokhnach** [comment]
I don't think Apple provides any other XCTest helpers to simulate force touch. Please let us know if you find some

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
