### ISSUE TITLE
Original error could not find android device

### ISSUE THREAD

**Issue by poojadhariwal** [appium/appium#16921]
[Appium] Welcome to Appium v1.15.1
[Appium] Non-default server args:
[Appium]   allowInsecure: {
[Appium]   }
[Appium]   denyInsecure: {
[Appium]   }
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/sessions
[HTTP] {}
[GENERIC] Calling AppiumDriver.getSessions() with args: []
[GENERIC] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 7 ms - 40
[HTTP] 
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"newCommandTimeout":0,"connectHardwareKeyboard":true,"browserName":"firefox","version":"","javascriptEnabled":true,"platform":"ANY"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"newCommandTimeout":0,"connectHardwareKeyboard":true,"browserName":"firefox","version":"","javascriptEnabled":true,"platform":"ANY"},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1571946962113 (01:26:02 GMT+0530 (India Standard Time))
[BaseDriver] Event 'newSessionStarted' logged at 1571946962115 (01:26:02 GMT+0530 (India Standard Time))
[MJSONWP] Encountered internal error running command: Error: You must include a platformName capability
[MJSONWP]     at AppiumDriver.getDriverAndVersionForCaps (C:\Program Files\Appium\resources\app\node_modules\appium\lib\appium.js:195:13)
[MJSONWP]     at AppiumDriver.getDriverAndVersionForCaps [as createSession] (C:\Program Files\Appium\resources\app\node_modules\appium\lib\appium.js:300:66)
[MJSONWP]     at AppiumDriver.executeCommand (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\driver.js:376:19)
[MJSONWP]     at AppiumDriver.executeCommand (C:\Program Files\Appium\resources\app\node_modules\appium\lib\appium.js:482:26)
[MJSONWP]     at executeCommand (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:306:34)
[MJSONWP]     at asyncHandler (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:432:15)
[MJSONWP]     at Layer.handle [as handle_request] (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
[MJSONWP]     at next (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\express\lib\router\route.js:137:13)
[MJSONWP]     at Route.dispatch (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\express\lib\router\route.js:112:3)
[MJSONWP]     at Layer.handle [as handle_request] (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
[MJSONWP]     at C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:281:22
[MJSONWP]     at Function.process_params (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:335:12)
[MJSONWP]     at next (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:275:10)
[MJSONWP]     at logger (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\morgan\index.js:144:5)
[MJSONWP]     at Layer.handle [as handle_request] (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
[MJSONWP]     at trim_prefix (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:317:13)
[MJSONWP]     at C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:284:7
[MJSONWP]     at Function.process_params (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:335:12)
[MJSONWP]     at next (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:275:10)
[MJSONWP]     at C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\body-parser\lib\read.js:130:5
[MJSONWP]     at invokeCallback (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\raw-body\index.js:224:16)
[MJSONWP]     at done (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\raw-body\index.js:213:7)
[MJSONWP]     at IncomingMessage.onEnd (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\raw-body\index.js:273:7)
[MJSONWP]     at IncomingMessage.emit (events.js:182:13)
[MJSONWP]     at endReadableNT (_stream_readable.js:1090:12)
[MJSONWP]     at process._tickCallback (internal/process/next_tick.js:63:19)
[HTTP] <-- POST /wd/hub/session 500 44 ms - 179
[HTTP] 
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 7 ms - 57

**Comment by KazuCocoa** [comment]
Did you attempt to work with https://github.com/appium/appium-geckodriver?

```
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"newCommandTimeout":0,"connectHardwareKeyboard":true,"browserName":"firefox","version":"","javascriptEnabled":true,"platform":"ANY"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"newCommandTimeout":0,"connectHardwareKeyboard":true,"browserName":"firefox","version":"","javascriptEnabled":true,"platform":"ANY"},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1571946962113 (01:26:02 GMT+0530 (India Standard Time))
[BaseDriver] Event 'newSessionStarted' logged at 1571946962115 (01:26:02 GMT+0530 (India Standard Time))
[MJSONWP] Encountered internal error running command: Error: You must include a platformName capability
[MJSONWP] at AppiumDriver.getDriverAndVersionForCaps (C:\Program Files\Appium\resources\app\node_modules\appium\lib\appium.js:195:13)
```

1. The driver expects W3C protocol, so please use W3C spec supported client
2. As the error message, please specify platformName. Maybe `windows` in your case
    - Please read https://github.com/appium/appium-geckodriver#usage for more details

The appium version is outdated, so please consider to use latest appium 1.22 or appium 2 beta

**Comment by mykola-mokhnach** [comment]
Closed because of no response
