### ISSUE TITLE
Having Trouble Passing More Than 1 Appium2 Plugin with --use-plugins Arg

### ISSUE THREAD

**Issue by VinayBerry** [appium/appium#16927]
## The problem

Trying to pass multiple plugins to use-plugins argument in appium2.

I'm not sure what im missing in my command but when I try passing in the images + my custom plugin it tries to join them into a single string instead of treating them as 2 separate plugins.

Command I'm using:
```appium --use-plugins=images,custom --base-path /wd/hub```

From logs:
```
info Appium Non-default server args:
info Appium {
info Appium   basePath: '/wd/hub',
info Appium   usePlugins: [
info Appium     'images custom'
info Appium   ]
info Appium }
```

## Environment

version: Appium 2.0.0-beta.25

**Comment by jlipps** [comment]
hmm i'm not able to reproduce. a couple ideas:

1. try the latest appium 2 beta
2. quote the value of use plugins, maybe your shell is doing something odd: `appium --use-plugins="images,custom"`

**Comment by VinayBerry** [comment]
thanks, that worked for me.  I was using Powershell and I thought I had tried with quotes already but I think I used single quotes instead of double.
