### ISSUE TITLE
Error installing xcuitest driver Appium 2

### ISSUE THREAD

**Issue by Auto81** [appium/appium#16923]
## The problem

Mac M1 Mini Monterey 12.2.1
XCode 13.3.1
npm@6.14.10
node@v14.15.4
Appium 2.0.0-beta.35

> appium driver list
> ✔ Listing available drivers
> - uiautomator2@2.1.0 [installed (NPM)]
> - xcuitest [not installed]

Then try to install xcuitest driver, getting the following error

> appium driver install xcuitest
> ✖ Installing 'xcuitest' using NPM install spec 'appium-xcuitest-driver'
> Error: Encountered an error when installing package: npm command 'install --save-dev --save-exact --global-style --no-package-lock appium-xcuitest-driver --json' failed with code 1.
> 
> STDOUT:
> {
>   "error": {
>     "summary": "Can't install /Users/user/.appium/appium-xcuitest-driver: Missing package name",
>     "detail": ""
>   }
> }
> 
> STDERR:
> npm ERR! Can't install /Users/user/.appium/appium-xcuitest-driver: Missing package name
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/user/.npm/_logs/2022-05-09T19_35_55_542Z-debug.log

**Comment by jlipps** [comment]
I can't reproduce this. Can you `rm -rf ~/.appium` and then try to install again?

**Comment by Auto81** [comment]
Done `rm -rf ~/.appium/appium-xcuitest` and driver now installing, thanks!
