### ISSUE TITLE
appium-adb: Make it easier to create multiple `ADB` instances

### ISSUE THREAD

**Issue by NotWoods** [appium/appium#16932]
## The problem

When managing multiple devices with Appium ADB, I want to create multiple instances of the `ADB` class with different serial numbers assigned. 

`ADB.createADB` runs some async logic to look up the ADB executable path, but this only needs to run once. Other instances could re-use the same information.

Therefore it would be nice to have a helper method like `adb.copyADB()` that creates a new instance of the `ADB` class but copies the properties set in `createADB`.

## Details

Implementation idea:

```js
methods.cloneADB = function () {
	const adb = new ADB();
	adb.sdkRoot = this.sdkRoot;
	adb.executable.path = this.executable.path;
	return adb;
}
```

Other elements of the issue template were removed since this is a feature request and not a bug.

**Comment by mykola-mokhnach** [comment]
Thanks for the proposal @NotWoods 
Feel free to push a PR there when you have time
