### ISSUE TITLE
Install Custom Appium2 Plugin From Internal NPM Registry

### ISSUE THREAD

**Issue by VinayBerry** [appium/appium#16930]
Up to now I've been using local but if I want to publish my plugin to a registry and install from there what command should I use?

**Comment by jlipps** [comment]
if your package is published on NPM as let's say `appium-random-plugin`, then you would install it like this:

```
appium plugin install --source=npm appium-random-plugin
```

**Comment by VinayBerry** [comment]
I figured that one was for the public npm registry does it also work with private registries?  Or is there something else we have to do?

**Comment by jlipps** [comment]
i don't see why it wouldn't. it will literally just call `npm install appium-random-plugin` under the hood, so it should respect your system npm registry settings.
