### ISSUE TITLE
IME methods getting removed from Selenium bindings

### ISSUE THREAD

**Issue by diemol** [appium/appium#16939]
👋 @appium folks!

A recent issue created in the Selenium repository evidenced that IME is not working in browsers. More importantly, the tests using those methods are ignored and IME is not part of W3C WebDriver. The issue is https://github.com/SeleniumHQ/selenium/issues/10573.

However, it seems some Appium users might be still use it. While scanning the code base, IME is implemented in Java, and some mentions are present in Python. I did not check further but it does seem to not be present in any other binding.

During the project meeting held on [May 11, 2022](https://www.selenium.dev/meetings/2022/tlc-05-11/), the Selenium team decided to remove those methods. Before that, we chatted with @jlipps about it, and that is why we are creating this issue, to give a heads up to the Appium team that those methods will be gone. @jlipps mentioned those commands could be moved to the Appium clients if needed.

We have not decided when this will be removed, but it could be either in Selenium 4.3 or 4.4 (current version is 4.1 and in 1-2 weeks 4.2 will be out). Based on your feedback in this issue, we will decide to either delete right away, or deprecate and then wait 2 releases to remove it.

Ideally we can use this issue to coordinate further about this.

**Comment by jlipps** [comment]
thanks for the report @diemol ! IIRC, Appium uses the IME commands to allow users to set non-default keyboards on Android devices. I imagine we will need to continue to support this feature, if only for Android.

(Note to Appium devs: this could become an example of commands moved to the newMethodMap of the UiAuto2/Espresso drivers).

Sounds like we should also create tickets for moving implementations of those client calls to the Appium clients.

**Comment by mykola-mokhnach** [comment]
I see two possible solutions:
- Either we move IME-related commands to extensions (which makes sense to me as they are only available/used on Android platform)
- Or we move the corresponding API wrappers from selenium clients to corresponding Appium clients (this will require us to modify all clients). This approach could provide better compatibility with the existing legacy code, although I'd still prefer the first one (I don't think such APIs are being frequently called in used scripts anyway).

**Comment by mykola-mokhnach** [comment]
As a very first step I'd simply mark the API calls deprecated and see if we get any feedback on that in general. Maybe, nobody is using the API at all %)

**Comment by KazuCocoa** [comment]
For IME things.
Probably we only need to add the endpoint in Java client? Otherwise, probably moving to mobile command? makes sense.

Python- https://github.com/appium/python-client/blob/593cde3777483b933bc8de5287c1978e6613c1a0/appium/webdriver/extensions/ime.py#L87
Ruby - https://github.com/appium/ruby_lib_core/blob/d10a1d83d30a18858db6eeed955fb25b51410f2c/lib/appium_lib_core/common/command.rb#L168-L172
.NET - https://github.com/appium/appium-dotnet-driver/blob/4570d11267572b861554142d39d4452d853e6118/src/Appium.Net/Appium/AppiumCommand.cs#L184

I occasionally hear the endpoint usage in android yet

**Comment by diemol** [comment]
👋 We just removed the code from Selenium, so it won't be part of the next release (4.5).

**Comment by yulian252003** [comment]
I want to ask you a question. This Framework is completely functional for Flutter or is it in the experimental phase? I didn't find a more appropriate place to ask the question.

**Comment by KazuCocoa** [comment]
You could take a look at https://github.com/appium-userland/appium-flutter-driver @yulian252003
