### ISSUE TITLE
A javascript error occurred in the main process - Error: Could not get code signature for running application

### ISSUE THREAD

**Issue by tomwattsuk** [appium/appium#16946]
## The problem

Hi there, just installed appium server and when I open it i'm seeing: Uncaught Exception: Error Could not get code signature for running applications - tried to look it up but i don't think i'm seeing the same issues on any help i've found which was only about 3 articles, so apologies if this is a known issue or something quite easy to fix, i'm VERY new to appium :) 

Before reporting the issue make sure that:
- The issue is reproducible with the most recent available server and driver versions<sup>*</sup>.
- There are no other duplicated reports of the same issue.
- Your description of the issue could be used to reproduce/understand it without any additional details.

<sup>*</sup>Appium1 is at its end of life and is not maintained actively anymore as well as compatible driver versions for it. It is highly recommended to switch to
[Appium2](https://appiumpro.com/editions/122-installing-appium-20-and-the-driver-and-plugins-cli) to have
access to the most recent server and driver fixes/updates.

## Environment
Mac OS

**Comment by jlipps** [comment]
you probably want to look at https://github.com/appium/appium-desktop, as the error you're mentioning has nothing to do with appium itself. and as the desktop server is not in working order, if your main goal is to use an inspector, then we recommend running appium from the command line and using the up to date appium inspector at https://github.com/appium/appium-inspector.
