### ISSUE TITLE
app process started by activateApp stops when the app goes to background

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#16967]
## The problem

https://github.com/appium/appium/issues/16941#issuecomment-1129626136

`--pct-syskeys 0` monkey command stops the app when it calls home.
The previous `moneky` command worked as "resume" the app instead of start particular activity,

## Environment

* Appium version (or git revision) that exhibits the issue: appium 2
* Last Appium version that did not exhibit the issue (if applicable):
* Driver version that exhibits the issue (only for Appium2): UIA2
* Last driver version that did not exhibit the issue (if applicable, only for Appium2):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Package manager name and version (we only officially support NPM):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by KazuCocoa** [comment]
Hi @SHI-ZP @Jiyvn 

Could you try out below start activity command to resume the app?


```
adb shell am start-activity --activity-single-top io.appium.android.apis/.ApiDemos -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10420000
```

So, instead of mobile command, could you try https://github.com/appium/appium-uiautomator2-driver#mobile-shell out?

`"mobile: shell", {"command": "am", "args": "start-activity", "--activity-single-top", "io.appium.android.apis/.ApiDemos", "-a", "android.intent.action.MAIN", "-c", "android.intent.category.LAUNCHER", "-f", "0x10420000"}` (probably this works...)

Or directly calls:

`adb shell am start-activity --activity-single-top io.appium.android.apis/.ApiDemos -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10420000`

`io.appium.android.apis/.ApiDemos` should be your launchable activity name.
Then, android brings the app package fromt by keeping current activity as `monkey` did.

**Comment by KazuCocoa** [comment]
`adb shell cmd package resolve-activity --brief <your package name>` returns your launchable activity name that can be `io.appium.android.apis/.ApiDemos` part.

**Comment by Jiyvn** [comment]
@KazuCocoa 
sorry but only one activity returned by `adb shell cmd package resolve-activity --brief <your package name>`
<img width="741" alt="image" src="https://user-images.githubusercontent.com/73217816/169481368-250ee558-3f0a-457b-a23f-0b641bc43df8.png">

app still restart as result of `adb shell am start-activity --activity-single-top com.viu.phone/.ui.activity.WelcomeActivity -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10420000`

**Comment by Jiyvn** [comment]
@KazuCocoa  here's the special page activity info from `dumpsys activity activities`, hope can help: https://gist.github.com/Jiyvn/2f94d0fd71ab7c2e59bf915a3aa2b7dc

**Comment by KazuCocoa** [comment]
It is expected since probably your app specifies the activity in the manfesto file. > sorry but only one activity returned by

Then, what about below patterns:

- `adb shell am start-activity --activity-single-top com.viu.phone/.ui.activity.WelcomeActivity -a android.intent.action.MAIN -c android.intent.category.LAUNCHER`
- `adb shell am start-activity --activity-single-top com.viu.phone/.ui.activity.WelcomeActivity -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x01000000`
- `adb shell am start-activity -n com.viu.phone/.ui.activity.WelcomeActivity -a android.intent.action.MAIN -c android.intent.category.LAUNCHER`
- `adb shell am start-activity -n com.viu.phone/.ui.activity.WelcomeActivity -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x01000000`

**Comment by Jiyvn** [comment]
@KazuCocoa all these patterns restart app

**Comment by KazuCocoa** [comment]
Thank you.

Hm, then, your app probably only can do the resume behavior with `monkey` command.
(I tested some apps like our test app `io.appium.android.apis` and a few apps from google play. They could keep last activity with the above commands though.)

`adb shell monkey -p appId -c android.intent.category.LAUNCHER 1`, thus probably it would be safe to explicitly issue monkey command in your code using `mobile:shell` or directly calls `adb` command.

**Comment by Jiyvn** [comment]
@KazuCocoa 
found that the command (https://github.com/appium/appium/issues/16967#issuecomment-1132579115) `adb shell am start-activity --activity-single-top com.viu.phone/.ui.activity.WelcomeActivity -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10420000` could work only after I start app with command (https://github.com/appium/appium/issues/16941#issuecomment-1131261846   (appium 1.22.2)) `adb shell am start -W -n com.viu.phone/com.viu.phone.ui.activity.WelcomeActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000` , 

looks like `-a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000` matters for launching an app.

**Comment by Jiyvn** [comment]
@KazuCocoa 
In a sum, `monkey` and `start-activity` commands to resume app work only after starting app with `adb shell am start -W -n com.viu.phone/com.viu.phone.ui.activity.WelcomeActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000`
And the app startup command seems changed at appium 2.0, which affects my case

**Comment by KazuCocoa** [comment]
Thank you...

I wonder if the default value in https://github.com/appium/appium/blob/1e30207ec4e413c64396420fbb0388392e88cc54/lib/parser.js#L641-L664 has not applied in appium 2.0.
But i think they should be in https://github.com/appium/appium-uiautomator2-driver/blob/92b8fefe9b95a895a48997c2b019939e23b1ddea/lib/driver.js#L582-L584

**Comment by KazuCocoa** [comment]
Then, could you set:

```
"appium:intentCategory": "android.intent.category.LAUNCHER",
"appium:intentAction": "android.intent.action.MAIN",
"appium:intentFlags": "0x10200000"
```

as the capabilities? Then, appium uia2 driver will start the app with them.
After that, could you call `adb shell am start-activity -n com.viu.phone/.ui.activity.WelcomeActivity -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10000000` the flag is the same as [monkey](https://android.googlesource.com/platform/development/+/ecc1a3d0cf3af3dbbf4c190e1060fc1c0f8fb8a6/cmds/monkey/src/com/android/commands/monkey/MonkeyActivityEvent.java?autodive=0%2F#43) ?

I assume this will fix your issue...

**Comment by Jiyvn** [comment]
> Then, could you set:
> 
> ```
> "appium:intentCategory": "android.intent.category.LAUNCHER",
> "appium:intentAction": "android.intent.action.MAIN",
> "appium:intentFlags": "0x10200000"
> ```
> 
> as the capabilities? Then, appium uia2 driver will start the app with them. After that, could you call `adb shell am start-activity -n com.viu.phone/.ui.activity.WelcomeActivity -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10000000` the flag is the same as [monkey](https://android.googlesource.com/platform/development/+/ecc1a3d0cf3af3dbbf4c190e1060fc1c0f8fb8a6/cmds/monkey/src/com/android/commands/monkey/MonkeyActivityEvent.java?autodive=0%2F#43) ? It is appreciated to try out `adb shell am start-activity -n com.viu.phone/.ui.activity.WelcomeActivity -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000` as well.
> 
> I assume this will fix your issue...

@KazuCocoa yes, fixed with 
```
"appium:intentCategory": "android.intent.category.LAUNCHER",
"appium:intentAction": "android.intent.action.MAIN",
"appium:intentFlags": "0x10200000"
```

**Comment by Jiyvn** [comment]
> After that, could you call `adb shell am start-activity -n com.viu.phone/.ui.activity.WelcomeActivity -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10000000` the flag is the same as [monkey](https://android.googlesource.com/platform/development/+/ecc1a3d0cf3af3dbbf4c190e1060fc1c0f8fb8a6/cmds/monkey/src/com/android/commands/monkey/MonkeyActivityEvent.java?autodive=0%2F#43) ?
It is appreciated to try out `adb shell am start-activity -n com.viu.phone/.ui.activity.WelcomeActivity -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000` as well.

@KazuCocoa both these two command can activate app.
<img width="856" alt="image" src="https://user-images.githubusercontent.com/73217816/169732541-c94d3743-1567-46d3-be24-94cf0b025333.png">

**Comment by KazuCocoa** [comment]
Thank you.
The uia2 driver `2.1.3` currently has the default values in appium 2.0 environment as well.

```
"appium:intentCategory": "android.intent.category.LAUNCHER",
"appium:intentAction": "android.intent.action.MAIN",
"appium:intentFlags": "0x10200000"
```

**Comment by KazuCocoa** [comment]
UIA2 driver v2.2.0 has both changes. Please check them, thank you for your deep-diving into the issue.
