### ISSUE TITLE
Code coverage for react native app

### ISSUE THREAD

**Issue by chyamuna** [appium/appium#16965]
We are currently using appium for react native app. We would require to get code coverage for appium functional tests.
I couldn't find any documentation regarding the same. I appreciate some help here. Thank You

Appium Version: 1.22.3
React native version: 0.64
Currently we are running on android using UiAutomator2

**Comment by mykola-mokhnach** [comment]
Appium itself is not suitable for this kind of tasks. Please use Appium forum to ask questions
