### ISSUE TITLE
appium driver fail to install on Ubuntu 18.04

### ISSUE THREAD

**Issue by alei01** [appium/appium#16975]
## The problem
Can't install the appium driver on Ubuntu:
```
# appium driver install uiautomator2
✖ Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver'
Error: Encountered an error when installing package: Cannot find module 'appium-uiautomator2-driver/package.json'
Require stack:
- /root/.appium/noop.js
```
## Environment

* Appium version (or git revision) that exhibits the issue: 2.0.0-beta.35
* Last Appium version that did not exhibit the issue (if applicable): - 
* Driver version that exhibits the issue (only for Appium2): -
* Last driver version that did not exhibit the issue (if applicable, only for Appium2): -
* Desktop OS/version used to run Appium: Ubuntu 18.04
* Node.js version (unless using Appium.app|exe): v16.15.0
* Package manager name and version (we only officially support NPM): 8.5.5
* Mobile platform/version under test: -
* Real device or emulator/simulator: - 
* Appium CLI or Appium.app|exe: CLI

## Details
Trying to set up the appium 2.0 on the Ubuntu 18.04 machine.
1. `npm install -g appium@next`
Appium successfully set up 
```
appium -v
2.0.0-beta.35
```
2. `appium driver install uiautomator2`
Throwing the error:
```
✖ Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver'
Error: Encountered an error when installing package: Cannot find module 'appium-uiautomator2-driver/package.json'
Require stack:
- /root/.appium/noop.js
cd ~/.appium    	
```
3. Checking the .appium dir content 
```
ls /root/.appium/
node_modules
```

**Comment by mykola-mokhnach** [comment]
Maybe try to install it from a non-root user account?

**Comment by alei01** [comment]
Running command as a non-root user did the trick:
```
# su - jenkins -c 'appium driver install uiautomator2'
✔ Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver'
Driver uiautomator2@2.2.0 successfully installed
- automationName: UiAutomator2
- platformNames: ["Android"]
```
Many thanks, @mykola-mokhnach!
