### ISSUE TITLE
we need to talk about Logging

### ISSUE THREAD

**Issue by boneskull** [appium/appium#16970]
I started looking at this issue in #16966.  So, the logging facilities are kind of difficult to maintain.  I am not sure how they got to where they are now, but it seems pretty organic.  From what I understand:

- The logging API which Appium calls internally is a wrapper around `npmlog`.
- `npmlog` does not actually output anything; instead, multiple `winston` transports  get configured and invoked when the `npmlog` instance (is it a singleton?) emits events.
- An end-user has some control over which transports are used
- A programmatic user may have further granular control over what happens with log messages

The actual logging API itself (e.g., `log.info('something')`) doesn't seem to deviate greatly between `winston` and `npmlog`, so I'm assuming the intent here was not due to those differences.  

I spoke on [JS Party](https://changelog.com/jsparty) about this just yesterday--most Node.js packages are either servers, CLI tools, or libraries.  But some are more than one of these.  And while there's often _some_ crossover, the use-cases are wildly different. 

For our purposes, we can split an ideal Appium into three buckets:

1. The server (listening on a port, logging requests and commands, etc)
2. The CLI (help text, warnings, spinners, etc.)
3. Crosscutting stuff (library code)

And some examples of how I think logging should be treated for each, respectively:

1. Structured logging, powerful and configurable. example: `winston`, `pino`
2. Human-readable, friendly output--optionally machine-readable. Terminal-dependent (color/emoji support).  examples: `ora`, `console.log()` with `chalk`, `ink`
3. Silent unless environment flag or configuration variable says otherwise; straightforward, human-readable, and a balance between 1 and 2. Example: `debug`.

If we had three (3) different ways to log based on the context, they shouldn't "conflict" with each other.  In practice, that'd be difficult to consume, since a contributor would need to know a) which of these to use in what bit of the codebase, and b) three different APIs.

If "what is the context in which this code runs?" is murky, then perhaps refactoring or throwing more organization at it would help (e.g., split `appium` into more packages, move things out, etc.).  That's probably good.

Along with identifying "contexts" for code, DX may be the tough part of this.  It _may_ be possible to create a great abstraction so that there's only ever one API for logging in Appium and Appium-adjacent code.  Such an API would need to be told the current context (this could be defined centrally, e.g., "modules matching this glob should be treated as libraries"). This API would run the risk of a large surface area (e.g., purpose-specific functions for logging HTTP requests).  Edge cases will arise and there should be an escape hatch (e.g., force a write to `STDERR`, write to file or custom stream, etc.).  

Not pressing, but on my mind since I'm itching to have awesome CLI output. 

What do we think of all this?

**Comment by jlipps** [comment]
I'm all for modifying or updating how we do logging. IIRC the main reason we use Winston was that npmlog didn't support things like multiple simultaneous transports (e.g. to console and file) or websocket logging (a thing we no longer need). and Winston did all those things. But it has been a huge pain, so maybe we should just go back to npmlog only, or even roll our own thing with the same API. i'm not entirely sure what all our requirements for logging are anymore so we'd probably want to be clear on them, for anything beyond "show the server log to the console where the server is running."

**Comment by boneskull** [comment]
I thought about this more last night instead of going to bed.  This is rather conceptual, so bear with.

## Structure

- _All_ log msgs should be structured (or "structurable").  That means the HTTP requests, the CLI output, any Appium internal debug logs, etc.
- The structure of a log message should be defined by a schema, with reasonable points for arbitrary data.
- We should not be shy about stuffing lots of info in a log.
- The log message should have, at minimum:
  - a unique identifier (probably a UUID)
  - a ISO9601 time
  - various bits of relevant system information
- The _context_ (see below) otherwise determines the structure (this is included in the schema).  For example:
  - anything happening during a session must have a session ID property.
  - any I/O should have a delta in ms

## Contexts
- The context, for a first pass, can be thought of as a list of tags, topics, or labels. 
- The developer specifies these tags when logging.  For example, a "log level" is part of the context, and a warning message may add the tag `warn` to the context.  
- In various parts of the system, the context is pre-populated.  For example, stuff coming out of `appium-driver-butts` may have a `driver` tag and a `appium-driver-butts` tag.  

## Transports
- Appium will provide minimal set of transports out of the box, have some enabled by default, which are otherwise user-configurable.
- Transports are composed of streams.  It begins with one or more readable streams, which are selected from contexts. 
 Transform streams are added to the pipeline, finally ending in one or more writable streams.  This could be "structured HTTP logs to file" or "human-readable debug information to stdout" or "appium cli progress bars to stderr" or "all structured logs to system journal" etc.  (Note: this sounds complicated, but is basically how `pino` works and is mostly a solved problem)

## API considerations
- This shouldn't deviate from how developers are used to writing log messages.  Ultimately, any function like `info()` is just a convenience method.  We may see some new ones.
- After the first pass, it would be useful to provide a facility for users who need special transports to bring their own.  Not sure if this should be a new class of extensions the same level with drivers/plugins, or if we can just expose an API in `BasePlugin`.  I'd like it if plugins were the canonical way to monkey with Appium in just about any capacity short of what drivers provide.
- This implies removing both `winston` and `npmlog`.  
- AFAICT there's no public API here short of what `logger` in `@appium/support` provides--which any extension can consume--so to minimize breakage we will want to provide compatibility here.  We may want to provide compat for the `--log` flag and `--log-filters`.  
- I do not think it's a great idea to do this piecemeal; the interaction within our current logging system is murky and adding another system on top would be painful.

## Performance
- Node.js streams are very fast and this is probably what we should be using. They've historically been rather painful to work with, but in more recent versions of Node.js this has been eased considerably by adoption of async iterators and the `stream.pipeline()` function.  No more `through2`.  Again, `pino` [does most everything we need](https://github.com/pinojs/pino/blob/HEAD/docs/api.md) so I think it's just a matter of writing an adapter.
