### ISSUE TITLE
Getting value of dynamic element 

### ISSUE THREAD

**Issue by nmolinero** [appium/appium#16976]
I’d like to get the video duration and the current time where the video is shown in [this image](https://discuss.appium.io/uploads/default/original/2X/0/0f49ddac540871bf28aa457b68e2c8ef170ad7a7.jpeg)

and I’m using these two lines to get those.

```
duration = driver.find_element(AppiumBy.ID, 'com.twitter.android:id/time').text
ccurrent_time = driver.find_element(AppiumBy.ID, 'com.twitter.android:id/time_current').text
```
However, they are very slow, and I can’t read the real progress of the video. Is there any alternative?

**Comment by mykola-mokhnach** [comment]
Please provide the detailed information about your testing environment. Appium supports multiple drivers, and we don't know which one is used in this particular case

**Comment by nmolinero** [comment]
> 

this is what we use:

> "platformName": "Android",
> "platformVersion": "11"
> 
> Appium 1.22.3-4
> 
> from appium import webdriver
> from appium.webdriver.common.appiumby import AppiumBy

is that information what you need? Thanks!

**Comment by mykola-mokhnach** [comment]
You could try the same workaround as in https://github.com/appium/appium/issues/16298
In general, uiautomator framework requires app under test to be in idle state, which does not apply to video playback.

**Comment by nmolinero** [comment]
thanks! do you know by any chance how to compare video frames? I mean, we are playing a video and we want to compare the image we see in second 1 with the image we see in second 2 in order to check if it was frozen.

**Comment by StephanB75** [comment]
@nmolinero i had a similar case some time ago and used a fakecamera to inject 2 different pictures (as video loop) where each picture was shown a second. So at least i could verify by screencomparison that each picture is not shown all the time (which would be if the stream is frozen). Never found an better way to verify that.

**Comment by mykola-mokhnach** [comment]
Record a video from the device screen and then analyse the video frames by comparing them. I wouldn't use uiautomator for such purpose as it also adds delays into the flow since all accessibility interactions are anyway executed on the main thread.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
