### ISSUE TITLE
Error during create session

### ISSUE THREAD

**Issue by mats9900** [appium/appium#16973]
Hello! Hello! I want to create session appium, but show me error. I don’t know what this error mean, so I will gratefull if someone help me resolve this problem.

`Failed to create session. An unknown server-side error occurred while processing the command. Original error: Cannot start the ‘com.google.android.calculator’ application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Error executing adbExec. Original error: ‘Command ‘‘C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe’ -P 5037 -s emulator-5554 shell am start -W -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000’ exited with code 1’; Command output: Error: Intent matches multiple activities; can’t stop: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 }`

**Comment by mykola-mokhnach** [comment]
Please provide a proper issue description along with the full server log

**Comment by mykola-mokhnach** [comment]
Closed because of no response
