### ISSUE TITLE
Appium 2.0: Android: Migration doc: Missing '--bootstrap-port`

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#16987]
## The problem

In migration [doc](https://github.com/appium/appium/blob/2.0/docs/en/advanced-concepts/migrating-to-appium-2.0.md) absent what to do with `--bootstrap-port` that is needed to run multiple parallel instances of appium server with Android phones.

any comment?

PS also:
- I do not see that path `wd/hub` not needed any more
- path to divers changed to local user instead where appium installed (important when configure iOS to build WDA) `USER_HOME + /.appium/node_modules`

**Comment by mykola-mokhnach** [comment]
I'm not quite sure this argument was even used anywhere. Which driver do you use?

**Comment by amedvedjev** [comment]
@mykola-mokhnach this not driver but server parameter. using it for 3+ years. started migration to Appium 2.0 and found out problem...

https://appium.io/docs/en/writing-running-appium/server-args/ -> 
```
-bp, --bootstrap-port | 4724 | (Android-only) port to use on device to talk to Appium | --bootstrap-port 4724
```

Maybe indeed not needed? Historically I used it unique per each appium server.

**Comment by mykola-mokhnach** [comment]
AFAIK it was only used in the deprecated appium-android-driver. Neither Espresso nor UIA2 need it.

**Comment by amedvedjev** [comment]
wooow. removed. works. nice. thanks!
