### ISSUE TITLE
I have been trying swipe left or swipe right action for long time without any positive response in my emulator. Is there any solution for this without using touchactions?

### ISSUE THREAD

**Issue by Balakumar-14** [appium/appium#16989]
Swipe up and swipe down actions are well executable. BUt, swipe left and right is getting failed.
While running with this action, no error produces. And, action too produced.
I a trying without using touchactions module. Because, they will be depricated soon.
So, help me with my code, as  I am a beginner. 
Thanks in advance.

Code I have tried:
`public void swipeRight() {
        JavascriptExecutor js = driver;
        HashMap<String,Object> map = new HashMap<>();
        map.put("direction","left");
        map.put("percent", 1.0);
        map.put("left", 500);
        map.put("top", 1500);
        map.put("width", 0);
        map.put("height", 500);
        map.put("speed", 500);
        js.executeScript("mobile: swipeGesture",map);
    }

    public void swipe_Left() {
        JavascriptExecutor js = driver;
        HashMap<String,Object> map = new HashMap<>();
        map.put("direction","right");
        map.put("percent", 1.0);
        map.put("left", 800);
        map.put("top", 1500);
        map.put("width", 0);
        map.put("height", 500);
        map.put("speed", 500);
        js.executeScript("mobile: swipeGesture",map);
    }

public void swipeDown()
    {
        JavascriptExecutor js = driver;
        HashMap<String,Object> map = new HashMap<>();
        map.put("direction","up");
        map.put("percent",1.0);
        map.put("left",200);
        map.put("top",500);
        map.put("width",0);
        map.put("height",1100);
        map.put("speed", 500);
        js.executeScript("mobile: swipeGesture",map);
    }

    public void swipeUp() {
        JavascriptExecutor js = driver;
        HashMap<String,Object> map = new HashMap<>();
        map.put("direction","down");
        map.put("percent", 1.0);
        map.put("left", 300);
        map.put("top", 700);
        map.put("width", 0);
        map.put("height", 1100);
        map.put("speed", 500);
        js.executeScript("mobile: swipeGesture",map);
    }`

**Comment by mykola-mokhnach** [comment]
I'm not quite sure it is going to work at all if any of swipe area dimensions is set to zero. Please use Appium forum to ask questions

**Comment by Balakumar-14** [comment]
Whether Appium forum present in appium website?

**Comment by jlipps** [comment]
https://discuss.appium.io
