### ISSUE TITLE
Android: Chrome: Cant switch context to webView

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#16996]
## The problem

In test app opens chrome browser with some link. While chrome browser in front trying to switch context to webView and it just stack/stop.

## Environment

* Appium version (or git revision) that exhibits the issue: 2.0.0-beta.35, 1.9.X
* Driver version that exhibits the issue (only for Appium2): uiautomator2@2.1.2
* Mobile platform/version under test: Android 11, 12
* Real device or emulator/simulator: real devices
* MacOS 12.3.1

## Details

It looks like problem started after some update of chrome browser. Current version: Chrome/101.0.4951.61.
While inspecting same chrome session from Chrome browser on mac - no problem

## Link to Appium logs

[logs](https://gist.github.com/amedvedjev/4880ef83490e9e993597fb718715d31e)

**Comment by mykola-mokhnach** [comment]
This looks like a ChromeDriver issue to me

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
