### ISSUE TITLE
Cannot create a string longer than 0x1fffffe8 characters when calling stopRecordingScreen

### ISSUE THREAD

**Issue by Idoserovitz** [appium/appium#17004]
## The problem

I am trying to get the screen recording at the end of my test and get the following error:
`Cannot create a string longer than 0x1fffffe8 characters
`
most of the times the video is generated but sometimes it fails the test with the mentioned error.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.3
* Last Appium version that did not exhibit the issue (if applicable): 1.22.2
* Desktop OS/version used to run Appium: macOS Monterey 12.0.1
* Node.js version (unless using Appium.app|exe): v18.2.0
* Package manager name and version (we only officially support NPM): 8.9.0
* Mobile platform/version under test: Android API 32
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: CLI

* Running using Jenkins
* Using java-client

## Details

`[AndroidDriver] Initiating screen records merging using the command 'ffmpeg -safe 0 -f concat -i /var/folders/1n/4z8ctp0s5g1f8wdxyrw1_9f40000gp/T/2022427-75512-1doit4j.rdde/config.txt -c copy /var/folders/1n/4z8ctp0s5g1f8wdxyrw1_9f40000gp/T/2022427-75512-1doit4j.rdde/merge_1653673891771.mp4'
00:15:32.178 [debug] [AndroidDriver] The size of the resulting screen recording is 474.41 MB
00:15:35.723 [debug] [W3C (d7e50d7e)] Encountered internal error running command: Error: Cannot create a string longer than 0x1fffffe8 characters
00:15:35.723 [debug] [W3C (d7e50d7e)]     at Buffer.toString (node:buffer:786:17)
00:15:35.724 [debug] [W3C (d7e50d7e)]     at uploadRecordedMedia (/opt/homebrew/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/recordscreen.js:26:53)
00:15:35.724 [debug] [W3C (d7e50d7e)]     at AndroidUiautomator2Driver.stopRecordingScreen (/opt/homebrew/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/recordscreen.js:335:12)`

It looks like the video is created properly and appium cannot convert it to base64 string. The AndroidUiautomator2Driver.stopRecordingScreen throws an exception and hence, the client cannot get the context afterwards.
Note: I do not pass any options to stopRecordingScreen.

The line in my code that throws the exception is the following:
`        String base64String = ((CanRecordScreen) driver).stopRecordingScreen();
`

## Link to Appium logs
https://gist.github.com/Idoserovitz/7ce8688051e91fe77999b2d3ec0d0127

## Code To Reproduce Issue [ Good To Have ]
        String base64String = ((CanRecordScreen) driver).stopRecordingScreen();
        byte[] data = Base64.decodeBase64(base64String);
        String destinationPath = "./output/video.mp4";
        Path path = Paths.get(destinationPath);
        if (Utils.createFolderIfNotExists(path.getParent())) {
            Files.write(path, data);
        } else {
            log.error("Failed to create output folder, cannot write to " + destinationPath);
        }

**Comment by mykola-mokhnach** [comment]
Unfortunately selenium protocol is limited, so we could only send the resulting video payload as base64-encoded string in a JSON-like response.

A possible workaround would be to provide a server url, so the resulting file could be uploaded to a remote server instead of being returned as a string.

**Comment by mykola-mokhnach** [comment]
Another possible but less stable solution would be to reduce the quality of the recorded video, so it produces smaller data chunk

**Comment by Idoserovitz** [comment]
Hi @mykola-mokhnach, first of all thank you. 
I run tests on both android and iOS and I can see that the generated iOS video is about 20MB (for 6 minutes) and the android video is about 170-200MB for the same amount of time.

According to:
` https://javadoc.io/doc/io.appium/java-client/7.1.0/io/appium/java_client/android/AndroidStartScreenRecordingOptions.html#withBitRate-int-
`I lowered the bitRate to 4000000. (running API 32)
and still, I couldn't see any improvements... do you have any suggestion to how I can lower the video size?
and if you know the cause to the massive video size differences it will be great as well. thanks.

* currently I am ok with having a lower video quality.

**Comment by mykola-mokhnach** [comment]
I would try to further reduce the bitrate and/or the video size

**Comment by mykola-mokhnach** [comment]
maybe it is also possible to record the video partially: .e.g limit the maximum duration of a single clip to 3 minutes and have two of these per single 6min test

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
